### ISSUE TITLE
transmission: download directory creation on zfs filesystems prevents zfs from mounting

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#100074]
**Describe the bug**

transmission creates the download directory in extremely early boot before zfs mounts the filesystems [here](https://github.com/NixOS/nixpkgs/blob/4da09d369baa2200edb9df27fe9c88453b0ea6cf/nixos/modules/services/torrent/transmission.nix#L149).

zfs then fails to mount a pool later with 

```
cannot mount '/somepool': directory is not empty
```

or something similar.

**To Reproduce**
1. use zfs, with secondary pools (from rootfs)
2. set transmission to use download directory in one of said secondary pools
3. boot the system.

**Expected behavior**
transmission should wait for zfs pools to be mounted before attempting any of its initialization actions (especially when I have something like

```
  systemd.services."transmission" = {
    requires = ["zfs-mount.service"];
    after = ["zfs-mount.service"];
  };
```

in my config.

**Notify maintainers**
@ju1m 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.19, NixOS, 21.03pre244817.fc3766140c4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre244817.fc3766140c4"`
 - channels(nagisa): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: transmission
```

**Comment by nagisa** [comment]
Furthermore, I am not able to "just" override that behaviour AFAICT.

**Comment by aanderse** [comment]
@nagisa what user to you run `transmission` as?

**Comment by nagisa** [comment]
Whatever the default is, I think, which is `transmission`. Perhaps also of note is that I'm running the transmission daemon, not the GUI things.

For now I worked around it by setting `services.transmission.downloadDirPermissions = "9999";`, which makes the directory creation to fail.

**Comment by aanderse** [comment]
After thinking this through using `activationScripts` was a bad idea to work with directories.

I have some ideas. I'll try and put something together this weekend if no one else gets around to it.

**Comment by aanderse** [comment]
@ju1m what if we only provision the state directory (`home`) if left as the default value. If the user specifies a custom value we rely on the sysadmin to provision the directory ahead of time with the appropriate permissions, etc...

A **very** rough sketch of what that might look like [here](https://github.com/NixOS/nixpkgs/commit/13a97d41a144fb1033cf883ecb39edc34dac86f6).

**Comment by ju1m** [comment]
> For now I worked around it by setting `services.transmission.downloadDirPermissions = "9999";`, which makes the directory creation to fail.
@nagisa another workaround could be to `zfs set overlay=on $dataset`.

```
     overlay=off|on
       Allow mounting on a busy directory or a directory which already contains files or directories. This
       is the default mount behavior for Linux file systems.  For consistency with OpenZFS on other plat‐
       forms overlay mounts are off by default. Set to on to enable overlay mounts.
```
@aanderse well, I did by best to preserve the `downloadDirPermissions` option because removing options often breaks users' config, but I personnally don't mind removing this one. Though I would like to get https://github.com/NixOS/nixpkgs/pull/96655 merged before changing things with this proposal.

**Comment by aanderse** [comment]
> Though I would like to get #96655 merged before changing things with this proposal.

That sounds good :+1:
