### ISSUE TITLE
Ability to override kicad-unstable version

### ISSUE THREAD

**Issue by matthuszagh** [NixOS/nixpkgs#100045]
I'm trying to override the commit used for kicad unstable without redefining the entire kicad build expression. I attempted to do this via an overlay, like:

```nix
final: prev:

{
  kicad-unstable = (prev.kicad-unstable.override {}).overrideAttrs (old: {
    version = "2020-10-08";

    src = prev.fetchFromGitLab {
      group = "kicad";
      owner = "code";
      repo = "kicad";
      rev = "fd22fe8e374ce71d57e9f683ba996651aa69fa4e";
      sha256 = "sha256-F8qugru/jU3DgZSpQXQhRGNFSk0ybFRkpyWb7HAGBdc=";
    };
  });
}
```

But, this still uses the version specified in [versions.nix](https://github.com/NixOS/nixpkgs/blob/3a84452a6e32131110f6094945b49443b59fa849/pkgs/applications/science/electronics/kicad/versions.nix). The reason seems to be because of [this line](https://github.com/NixOS/nixpkgs/blob/3a84452a6e32131110f6094945b49443b59fa849/pkgs/applications/science/electronics/kicad/default.nix#L102) and surrounding context. Basically, the build expression is mostly taken from [base.nix](https://github.com/NixOS/nixpkgs/blob/3a84452a6e32131110f6094945b49443b59fa849/pkgs/applications/science/electronics/kicad/base.nix) (this inherits the version info from versions.nix) and then the binaries are wrapped. Long story short, I don't see any way to override the commit used without overriding a fair number of attributes.

I could create a PR updating the unstable version in versions.nix, but this means that I can't use an overlay while I wait for the PR. More importantly though, this doesn't help me if I want to use a version that isn't the latest version.

@evils is there a way that makes sense to you to change this build expression such that a specific kicad version can be used with the above overlay?

**Comment by doronbehar** [comment]
Damn these expressions are complex. Maybe you should write a PR that will make `versions.nix` export a function, that takes a `srcs ? {
i18n = {}; symbols = {}; ...}` as a parameter, and that parameter is then used to generate the final return argument? If the relevant attribute (say `i18n`) is not set, a default is chosen, and if not, the provided is returned. Also, make it a real src - what `fetchFromGitHub` is called.

I've incorporated a somewhat similar approach here: 

- https://github.com/doronbehar/nixpkgs/blob/24f9480eed1b9111639c23ec1fef15656799fea3/pkgs/applications/radio/gnuradio/shared.nix#L8-L14
- https://github.com/doronbehar/nixpkgs/blob/24f9480eed1b9111639c23ec1fef15656799fea3/pkgs/applications/radio/gnuradio/default.nix#L184-L202

**Comment by matthuszagh** [comment]
@doronbehar I like that approach. Thanks for the insight. I ended up going with a "dummer" solution (see [PR](https://github.com/NixOS/nixpkgs/pull/100066)). I wasn't too eager to mess with version.nix, because that would mean changes to update.sh. The downside of this more limited approach is that I think it means if you want to configure kicad-unstable, you have to override the whole attribute set for it (libraries included).

**Comment by doronbehar** [comment]
Needs rebase.

**Comment by evils** [comment]
with #100066 merged, can this issue not be closed?

**Comment by evils** [comment]
and to answer the question above,
if you want to change the version of kicad you use, change versions.nix, or the attribute set it returns

**Comment by evils** [comment]
this may be a redundant statement at this point
but if you want to change where the package gets the source code, you need to override kicad.base.src or kicad.libraries.[library you want to change].src
