### ISSUE TITLE
CoreCtrl

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#100157]
**Project description**
CoreCtrl is a Free and Open Source GNU/Linux application that allows you to control with ease your computer hardware using application profiles. It aims to be flexible, comfortable and accessible to regular users.

**Metadata**

* homepage URL: https://gitlab.com/corectrl/corectrl/
* source URL: https://gitlab.com/corectrl/corectrl/
* license: gpl3
* platforms: unix, linux

**Comment by AndersonTorres** [comment]
It looks very complicated. I will look at AUR.

**Comment by Narice** [comment]
sorry for the late reply
thank you very much for looking into it :relaxed:

**Comment by AndersonTorres** [comment]
Well, I will do what I can do. I am not a huge user and packager of such graphical things, but it looks an interesting project to take on.

I will do some research.
