### ISSUE TITLE
Packaging request: Lemminx

### ISSUE THREAD

**Issue by leungbk** [NixOS/nixpkgs#100164]
**Project description**
Lemminx is an implementation of the Language Server Protocol for XML files.

**Metadata**

* homepage URL: https://github.com/eclipse/lemminx
* source URL: https://github.com/eclipse/lemminx
* license: EPL2
* platforms: GNU/Linux, Darwin

**Comment by leungbk** [comment]
unstale

**Comment by mausch** [comment]
Hi @leungbk can you give https://github.com/NixOS/nixpkgs/pull/132335 a try?

**Comment by poita66** [comment]
@mausch I gave your PR a try, but it doesn't build for me. It errors with:
```
hash mismatch in fixed-output derivation '/nix/store/yypdg12d28ld02pyk2ixkskzjpmgiyhh-lemminx':
  wanted: sha256:1vm27p68mhwlkx9860z8ipamw3sbx1pxsmd6wjlb39iwany2djbb
  got:    sha256:181da3bmd1q5sxb703wq9cphssjbbdsw83m6gvhh6iij3rpn3kab
```

Maybe the tag got moved in that repo. Do you want to try updating the SHA? Maybe also update it to the latest version (0.19.1)? I'm happy to help with testing/tweaking too

**Comment by mausch** [comment]
I've updated the SHA now, who knows what happened.
However now it fails to build on the github action but builds fine on my machine... :man_shrugging: 
What's worse the [build log](https://logs.nix.ci/?key=nixos/nixpkgs.132335&attempt_id=f3b1ddd7-33a0-4122-bcde-5031be944305) says "1 dependencies couldn't be built" but doesn't say which one failed.
