### ISSUE TITLE
cq-editor: update to Spyder 4 and Python 3.8

### ISSUE THREAD

**Issue by marcus7070** [NixOS/nixpkgs#100126]
## Issue description

Firstly, I'm the maintainer for this, but I'm a bit time-poor right now, so I'll leave this issue here until I can make the PR (hopefully in a week or so).

cq-editor has been updated to support Spyder 4 and Python 3.8: https://github.com/CadQuery/CQ-editor/pull/195

Currently `python3Packages.spyder_3` and `spyder-kernels_0_5` are only there to support the old version of cq-editor and can be dropped once this is done.

**Comment by FRidh** [comment]
Note `spyder_3` is broken now anyway, I think it was due to the Qt upgrade.

**Comment by marcus7070** [comment]
Sorry for the long comment @FRidh, I know you're busy, I'll try to be succinct.

The newer versions of cq-editor have replaced pythonocc with OCP (these are Python bindings to Opencascade). I've packaged OCP as part of this flake: https://github.com/marcus7070/cq-flake

I don't really want to include OCP into nixpkgs. It will require about 10 new Python modules, a pre-release version of Opencascade (and OCP will not work with any different versions), and the build time for just OCP is about an hour on my i7-7700K desktop.

On the other side, a CAD package is the perfect use for flakes. `nix run github:marcus7070/cq-flake/commit` is such a killer feature for CAD models. While I don't want to remove functionality from nixpkgs, I think almost all use cases would be improved by using the flake version over a direct usage of nixpkgs.

So I would like to leave nixpkgs in it's current state. If future updates to nixpkgs break `cq-editor` (beyond what simple patches can fix) then IMHO we should drop `cq-editor` rather that introduce new held back packages (like `spyder_3` vs `spyder`). Does that sound good to you @FRidh?

Also @rowanG077, are you currently using cq-editor from nixpkgs? Any thoughts on this?

**Comment by marcus7070** [comment]
Also, `spyder_3` is currently working as a library. Or at least, the Spyder code editor in `cq-editor` from nixpkgs master works on my machine.

**Comment by FRidh** [comment]
Taking certain packages out of Nixpkgs into Flakes is I think a good idea. I know opinions differ on this matter, but if you as maintainer choose to do that, then that's of course fine.

`spyder_3` was broken recently, if I am correct.

**Comment by marcus7070** [comment]
> `spyder_3` was broken recently, if I am correct.

I see now. `/nix/store/r1pg69f8k3bnh8cf5si23b50brax67n6-python3.8-spyder-3.3.6/bin/spyder3` is indeed broken. I consider this a library and forgot that was even there. `cq-editor` doesn't use the executable. I've got a patch for `spyder_3`'s setup.py that removes it and the xdg desktop app stuff.

**Comment by FRidh** [comment]
`spyder_3` exists solely for cq-editor, so I can think we can remove it.

**Comment by marcus7070** [comment]
If we remove it then we'll have to remove `cq-editor` now? I would rather we keep `cq-editor` around until we have to start holding new things back. For a user who just wants to quickly try out cq-editor, the nixpkgs version is still much more accessible than a flake.

**Comment by marcus7070** [comment]
So to reiterate, the current plan is that `cq-editor` will stay at it's current version for as long as possible, then will be dropped.
