### ISSUE TITLE
Adjusting screen brightness in the elementary greeter does not work

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#100119]
I am installing NixOS on a new laptop and I decided to try elementary. Well, it doesn’t quite work yet (still looking into the issue), but I already noticed something minor and thought I'd report it before I forgot. 

I don’t have the exact logs yet (because I’m just trying to get the laptop to work), but the idea is that I am trying to adjust screen brightness from the greeter and it does nothing. In `journalctl` there is a whole bunch of errors from `pkexec` which says:

```text
The value of the SHELL variable was not found the /etc/shells file [USER=root] [TTY=unknown] [CWD=/var/lib/lightdm] [COMMAND=/run/current-system/sw/bin/elementary-settings-daemon/gsd-backlight-helper <long drm/card0 path> <number>]
```

I think the idea here is that lightdm runs this helper as a login shell, so it needs to be listed in `/etc/shells`. Therefore, my guess would be to try to add this long path to `environment.shells` in the pantheon module.

**Notify maintainers**

cc @worldofpeace, I guess

**Comment by worldofpeace** [comment]
See https://github.com/NixOS/nixpkgs/issues/14168#issuecomment-617746483

**Comment by kirelagin** [comment]
Thanks for the link. I went through that discussion, and it looks like the problem in that case was that the they had zsh configured as the user’s shell, but it was not added to `/etc/shells` – this probably worked fine most of the time but Polkit would not allows anything to be done with the `SHELL` variable set to zsh, and it was set because the call was happening in the user’s session with the environment configured.

I’m not sure I understand how this can be related here, because I am talking about the greeter, where there is no user session yet. (My user has zsh configured as the shell indeed, but it is present in `/etc/shells`.)

**Comment by kirelagin** [comment]
That said, I am trying to figure out _what_ the `SHELL` variable is set to in the context of the greeter, but I am having trouble with that, since a) Vala is something completely new to me; b) looks like this is all handled by the GNOME Settings Daemon and the greeter just makes a DBus call to it, so I am having trouble figuring out how Polkit gets involved at all.

**Comment by worldofpeace** [comment]
> I’m not sure I understand how this can be related here, because I am talking about the greeter, where there is no user session yet. (My user has zsh configured as the shell indeed, but it is present in /etc/shells.)

I believe the greeter it still could be the same issue, because it will run with the shell of the `lightdm` user. And I can see in the `lightdm` module that no shell is set, so it's the default `shadow` which I don't think will be in `/etc/shells`. Do you think you could try setting `users.users.lightdm.shell = pkgs.bash;`?

**Comment by kirelagin** [comment]
> `users.users.lightdm.shell = pkgs.bash;`

Yes, this helped, indeed. I guess, this can be done not in pantheon, but in the lightdm’s own module then, as, I imagine, other GNOME-based DEs/greeters have the same issue.

The log is still spammed with tens of:

```
Oct 10 23:51:44 kirXps pkexec[18722]: pam_unix(polkit-1:session): session opened for user root by (uid=78)
Oct 10 23:51:44 kirXps pkexec[18722]: lightdm: Executing command [USER=root] [TTY=unknown] [CWD=/var/lib/lightdm] [COMMAND=/run/current-system/sw/bin/elementary-settings-daemon/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight 65587]
```

unfortunately, I’m wondering if there could be a way to silence these...

**Comment by worldofpeace** [comment]
> > `users.users.lightdm.shell = pkgs.bash;`
> 
> Yes, this helped, indeed. I guess, this can be done not in pantheon, but in the lightdm’s own module then, as, I imagine, other GNOME-based DEs/greeters have the same issue.
> 
> The log is still spammed with tens of:
> 
> ```
> Oct 10 23:51:44 kirXps pkexec[18722]: pam_unix(polkit-1:session): session opened for user root by (uid=78)
> Oct 10 23:51:44 kirXps pkexec[18722]: lightdm: Executing command [USER=root] [TTY=unknown] [CWD=/var/lib/lightdm] [COMMAND=/run/current-system/sw/bin/elementary-settings-daemon/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight 65587]
> ```
> 
> unfortunately, I’m wondering if there could be a way to silence these...

Everytime you press the key to change brightness it turns into a call for gsd-backlight-helper to change brightness. In the latest g-s-d (we use a fork of g-s-d for pantheon so everything still works) this is done with systemd so all that logging would be gone in later versions. I think `pkexec` gets logged default or something.
