### ISSUE TITLE
zeroad/0ad crashes when starting

### ISSUE THREAD

**Issue by zeri42** [NixOS/nixpkgs#100256]
**Bug**

The game fails during startup with two similar error messages:

(2 in 3 tries it crashes with):
X connection to :0 broken (explicit kill or server shutdown). and I hear music playing but no graphics. Other graphics applications (e.g. xonotic-sdl) and 3d acceleration work flawlessly otherwise.

(1 in 3 tries it crashes with):
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
0ad: xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

in this case I hear no music.

**To Reproduce**
nix-shell -p zeroad --run 0ad

pressing CTRL+C and C to continue until it finally crashes

**Expected behavior**

having the game start

**Additional context**

**Notify maintainers**
[0ad.log](https://github.com/NixOS/nixpkgs/files/5361405/0ad.log)
[userreport_hwdetect.txt](https://github.com/NixOS/nixpkgs/files/5361406/userreport_hwdetect.txt)
[system_info.txt](https://github.com/NixOS/nixpkgs/files/5361414/system_info.txt)
[crashlog.txt](https://github.com/NixOS/nixpkgs/files/5361415/crashlog.txt)

no meta.maintainers on this package so I selected 3 people from recent commits in https://github.com/NixOS/nixpkgs/tree/master/pkgs/games/0ad

@abbradar
@peterhoeg 
@xeji
 

**Metadata**

cthulhu% nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.69, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(zeri): `"nixos-20.03.3107.067d8e6c9f4, unstable-21.03pre246062.420f89ceb26"`
 - channels(root): `"nixos-20.09beta992.7badbf18c45"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tex** [comment]
Works fine for me.

[nix-shell:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.19-rt11, NixOS, 21.03pre246062.420f89ceb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(milan): `"nixos-20.09pre222973.7c399a4ee08, nixos-19.09-19.09.2469.e6d222fc0dd, nixos-20.03-20.03.1589.9137f05564e"`
 - channels(root): `"nixos-21.03pre246062.420f89ceb26, nixos-19.09-19.09.2522.75f4ba05c63, nixos-20.03-20.03.3107.067d8e6c9f4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by zeri42** [comment]
I further tried forking the nixpkgs repo (as described in  https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages) and adding the patch mentioned in https://trac.wildfiregames.com/ticket/4360 following the idea that it might be due my cpu (AMD Ryzen 5 3600) ... the error persists even with this patch.

**Comment by tex** [comment]
I have Dell/Latitude with (old) Intel graphics card.

**Comment by zeri42** [comment]
Ok problem solved it was the cache.cpp patch but the patch I found was outdated and overspecific (whole file contents vs. 2 lines changed) Ithis issue can be closed now. If somebody else has the same problem the easiest hotfix is adding
    sed -e 's|ENSURE|//ENSURE|g' -i source/lib/sysdep/arch/x86_x64/cache.cpp
in game.nix. If somebody wants to give me a pointer how to make a cool overlay? (not sure about terminology) like nix-shell -p zeroad.rhyzenpatch I would create a proper patch and pull request.

**Comment by mweinelt** [comment]
@zeri42 I believe this issue is no longer relevant?
