### ISSUE TITLE
texlive: mirroring is bad

### ISSUE THREAD

**Issue by utdemir** [NixOS/nixpkgs#10026]
I can not build `dblatex`(a dependency of `nix`) on nixpkgs master. It can't download some required archives. Changing mirror to `ftp.math.utah.edu` in `pkgs/tools/typesetting/tex/texlive-new/default.nix` also doesn't solve the problem.

It's not a specific dependency, on every run, a different dependency fails(depends on download order).

Steps to reproduce:
- `nix-shell -I ~/nixpkgs -p dblatex` on `nixpkgs/master`

```
trying ftp://tug.ctan.org/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/hyph-utf8.tar.xz

trying ftp://tug.ctan.org/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/gsftopk.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Tim
e     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Tim
e     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Tim
e     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
trying ftp://tug.ctan.org/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/glyphlist.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (67) Access denied: 530
error: cannot download hyph-utf8.tar.xz from any mirror
builder for ‘/nix/store/w9rz6n1wrixby1mycs6fck0sywj8vz71-hyph-utf8.tar.xz.drv’ failed with exit code 1
building path(s) ‘/nix/store/4l2xs6chhhzsa23g796ypbm2734lv16v-hyphen-base.tar.xz’
cannot build derivation ‘/nix/store/v7hq3p4pqgy2b1g2knhy448l5hwn73sq-texlive-hyph-utf8-687.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/nmnggnvhi43z4mzh3v7m2jd4xa9227y1-texlive-scripts.tar.xz’
building path(s) ‘/nix/store/swaad1cc905fh3l5lb9hid74d7f1hzxc-times.tar.xz’
building path(s) ‘/nix/store/d9pvb1fvdm6l7ax8w3760calnz21f4dp-titlesec.tar.xz’
building path(s) ‘/nix/store/2fmwf45srfqi3bgg6629k7ns0062iq34-tools.tar.xz’
building path(s) ‘/nix/store/2icg1a4x23bs7w5y63rbxbcq09rl7m05-url.tar.xz’
building path(s) ‘/nix/store/wcqf6cdilc55v4bxlwf531f0mnik1r1x-wasysym.tar.xz’
building path(s) ‘/nix/store/22yfj7scwl6a9vvzk5i8k8x83252aiih-zapfding.tar.xz’
cannot build derivation ‘/nix/store/byhr95n2lq68pciq3npiqcf5xma20rfk-texlive-combined-2015.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/byhr95n2lq68pciq3npiqcf5xma20rfk-texlive-combined-2015.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

**Comment by peti** [comment]
I just built `dblatex` on 0d0be1387869f8ddc84a9548fc327015b7745ec4, and it downloaded and compiled everything just fine:

~~~~
$ nix-build --no-out-link -A dblatex
/nix/store/wxmw9fmg8sxq3wvph3bmbyrik396hwzm-dblatex-0.3.7
~~~~~

**Comment by utdemir** [comment]
It was giving me "Access denied", a little investigation revealed that some DOS protection mechanism on the servers was getting in my way. It's also weird that the two mirrors I tried had that exact behavior. Probably some default configuration on their FTP servers.

Giving `-j 1`(`build-max-jobs`) fixed the problem. 

This is rather annoying that increasing `build-max-jobs` breaks something irrelevant like this, probably an option like "max. number of parallel requests per host"  would be useful, but given the current implementation this is pretty hard to implement(I think).

I'm closing this issue, thanks @peti .

**Comment by utdemir** [comment]
Or, I'll just rephrase the issue as "Can't compile dblatex when `build-max-jobs` is 24"

**Comment by vcunat** [comment]
As I noted in #287, we would have to mirror it ourselves. TAN only decently mirrors the *latest* TeX Live packages, not yearly releases.

**Comment by vcunat** [comment]
- I now tested and both upstream URLs resolve to the same IP (v4), so switching is meaningless.
- Dependencies and `dblatex` itself should get into binary cache soon &ndash; you reported just hour or two after I pushed it to master 9bd0bac311.

**Comment by vcunat** [comment]
> probably an option like "max. number of parallel requests per host" would be useful

Maybe, but not all hosts behave the same, e.g. for cache.nixos.org we do want to utilize many more parallel requests. (At least for checking whether paths are in the cache, though there is a separate setting for that already, `binary-caches-parallel-connections = 150`.)

**Comment by vcunat** [comment]
Now the generic URL doesn't work anymore but http://ftp.math.utah.edu still does (pushed commits to use that). I'm afraid they might be taking action as a result of nixpkgs causing lots of downloads from them, which might end up in this sole source being cut away in future.

I believe I still have the full archive on some computer if that happens (in nix store, after I was generating the hashes after unpacking).

**Comment by Mathnerd314** [comment]
We could just update the package list daily-ish and use the CTAN mirror system; TeXLive holds back most of the updates to core packages, so at least the minimal set will work on old channel versions (and probably more).
One commit per day wouldn't be any more often than Haskell: https://github.com/NixOS/nixpkgs/commits/master?author=peti

**Comment by vcunat** [comment]
I would prefer to avoid updating faster than once a year, perhaps except some important bug fixes.

Well, the core stuff should be mirrored by us already. I think the critical point was between committing and getting to channels (and hashed-mirror, perhaps), so we might be good in that already, but I haven't really checked, I think. There's also the advantage that the *unpacked* stuff is made fixed-output, so updates are no-op even if stdenv changes.

**Comment by utdemir** [comment]
It occured to me again:

```
curl: (7) Failed to connect to tug.org port 21: Connection timed out
error: cannot download texlive-20150521-source.tar.xz from any mirror
```

**Comment by vcunat** [comment]
### No working mirror anymore

Now the situation got much worse. The upstream package archive was recently overwritten by the final state of TeX Live 2015, so there is nowhere to download from, except for the packages that are in our binary cache (mainly the closure of `texlive.combined.scheme-small`). People will be getting broken hashes.

I suppose we would best import it all into our binary cache. Upstream just mirrors the daily-changing state and expects distros to solve anything else on their own. Even the unpacked packages are fixed-output derivations (by sha1); I found locally all packages required for running but not those with documentation or sources.

@edolstra: is it acceptable to mirror these at least? They're not too big:
```
$ nix-push --dest ~/texlive-cache/ (nix-build -Q -E 'with import ./. {}; lib.filter (p: p.tlType == "run") texlive.scheme-full.pkgs')
[...]
total compressed size 589.87 MiB, 34.4%
```
It's likely other users have the other types of packages as well. We all know the fixed hashes, so trust shouldn't be an issue in this step...

Any other ideas?

**Comment by edolstra** [comment]
Hm, I tried mirroring to the tarball cache, but `copy-tarballs.pl` can't find any files to mirror:
```
$ DRY_RUN=1 ./maintainers/scripts/copy-tarballs.pl --expr 'with import ./. {}; lib.filter (p: p.tlType == "run") texlive.scheme-full.pkgs'
evaluation returned 0 tarballs
mirrored 0 files, already have 0 files
```

Uploading to the binary cache won't work very well, because the tarballs will probably get garbage-collected (not being referenced by a release).

**Comment by vcunat** [comment]
The expression assumed you're in a nixpkgs tree. I assume that's the problem. Otherwise you can substitute `with import <nixpkgs> {};`.

**Comment by edolstra** [comment]
The actual problem appears to be that the `unpackPkg` derivations don't include the source tarball as a derivation attribute, so `find-tarballs` can't find them.

**Comment by vcunat** [comment]
Ah, well, I don't/didn't know how `copy-tarballs.pl` works. These would go to tarballs.nixos.org that is only checked by fetchurl and not during substitution, right? I now checked and I don't even have all these tarballs, only the unpacked and pruned /nix/store outputs.

**Comment by vcunat** [comment]
Anyway, if someone has the tarballs, I composed:
 - [list of tarballs needed during runtime](http://sprunge.us/heNd)
 - [list of all tarballs](http://sprunge.us/SXSC), i.e. including also documentation and source packages.

These are fixed-output by their md5.

**Comment by vcunat** [comment]
@edolstra: do you have those tarballs and can upload them? Or should we be searching for someone who has them?

**Comment by edolstra** [comment]
No, I don't think so. I checked the old Hydra server (lucifer), hoping it still has them, but that's apparently not the case.

**Comment by vcunat** [comment]
If noone here has a better idea, I suppose I'll post a question the the mailing-list then to find if someone still has them, as uploading the original tarballs seems the easiest way to fix stuff including all old branches.

**Comment by peti** [comment]
I have the following ~3800 tarballs available at hydra.cryp.to: http://pastebin.com/Q8SEyr5P. It's not much, but I hope it helpls.

**Comment by edolstra** [comment]
@peti Thanks! I'll try to use those.

**Comment by edolstra** [comment]
@peti Trying to use `hydra.cryp.to` as  binary cache gives:
```
Caught exception in Hydra::View::NARInfo->process "cannot open file ‘/etc/nix/hydra.cryp.to-1/secret’: Permission denied at /nix/store/5rrmjacsls56gjlgm0ydx85kbksnxfva-hydra-perl-deps/lib/perl5/site_perl/5.20.3/x86_64-linux-thread-multi/Nix/Utils.pm line 37."
```

**Comment by peti** [comment]
Oops. I broke access to the key file when I fixed the uid collision between `hydra` and `nscd` a few weeks ago. It's fixed now.

**Comment by domenkozar** [comment]
I'm also hitting this on 16.03, are there any workarounds until we have mirrored the old tarballs?

**Comment by vcunat** [comment]
@domenkozar: `nix-copy-closure` on the outputs, if you have them on another machine (they have fixed hashes). But it's unclear to me how to go about finding the rest of the tarballs...

**Comment by edolstra** [comment]
I'm now mirroring peti's tarballs...

**Comment by 7c6f434c** [comment]
I have removed the apparent duplicates from my `/nix/store/` dump and there are still some TeXLive tarballs that are not present at either Hydra (or at http://tarballs.nixos.org/ )

https://mega.nz/#!ap8XgKQI!1aVkGqFIsJQz2HQ946-Ksb9LWIaxJbzeH6f7Pus3AlM

**Comment by edolstra** [comment]
Thanks, the mirror script copied 540 tarballs from @peti and an additional 47 from @7c6f434c. That leaves about 2000 files, but hopefully this covers the most important ones...

**Comment by 7c6f434c** [comment]
@edolstra there is also @utdemir who seems to have _all_ the tarballs (see #13736 discussion)

At least the count of unique lines matches.

**Comment by 7c6f434c** [comment]
Ah no, these are all for a different version of TeXLive.

**Comment by vcunat** [comment]
Are they? I looked at a random couple and they matched the hashes from my list.

BTW, I've forgotten to mention my lists (and many others) weren't deduplicated, but piping through `sort -u` is easy enough anyway.

**Comment by 7c6f434c** [comment]
Aargh! Yes, you are right, I failed the '\r' stripping part.

`|sort|uniq` is a standard part of the processing, of course

**Comment by 7c6f434c** [comment]
@utdemir these seem to be not covered currently: https://gist.github.com/920094e39ad88f71f68900232a474de9

**Comment by utdemir** [comment]
Hey all,

I'm very sorry that I seem to have mixed up `comm` command (typed `comm -13` instead of `comm -12`), and I don't have any of the tarballs.

I just noticed when I tried to create a closure of them.

Sorry about that.

**Comment by vcunat** [comment]
:-D That's unfortunate.

**Comment by domenkozar** [comment]
![2016-04-19-103654_1208x168_scrot](https://cloud.githubusercontent.com/assets/126339/14634655/df9f8750-061a-11e6-8722-76cf015d761e.png)

No idea why it built the same thing on two machines, but it still fails for me. How are mirrored tarballs discovered?

**Comment by vcunat** [comment]
@domenkozar: they should be found by `fetchurl` on `tarballs.nixos.org` which is addressed by hashes. (I haven't tested that.)

**Comment by domenkozar** [comment]
```
$ nix-build -A texlive.inconsolata.pkgs
these derivations will be built:
  /nix/store/3mxcadhfp2i9s3yg9ac4absayhlmwilj-inconsolata.tar.xz.drv
  /nix/store/ivwljy48ir816b77f0xryywms49885ql-inconsolata.doc.tar.xz.drv
  /nix/store/q8vwz3ha6vn6kb13ri2cdsb85xzl5wh6-texlive-inconsolata.doc-1.05.drv
  /nix/store/wybn09p6d0ppwbrkavjbq6qyksaqrpvs-texlive-inconsolata-1.05.drv
building path(s) ‘/nix/store/fqlx6hxj9mh8v0r3qwyz3lg6ib7hj31z-inconsolata.doc.tar.xz’
building path(s) ‘/nix/store/h28lfjmqvhdgf0fcq93k8jlhhalckrnz-inconsolata.tar.xz’

trying http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/inconsolata.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
trying http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/inconsolata.doc.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  202k  100  202k    0     0  38007      0  0:00:05  0:00:05 --:--:-- 51468
output path ‘/nix/store/h28lfjmqvhdgf0fcq93k8jlhhalckrnz-inconsolata.tar.xz’ has md5 hash ‘40ea9f65895093fbde95821dc91fc3b1’ when ‘bc05ffdf9f18ab61d8d5972023c0ff02’ was expected
cannot build derivation ‘/nix/store/wybn09p6d0ppwbrkavjbq6qyksaqrpvs-texlive-inconsolata-1.05.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/wybn09p6d0ppwbrkavjbq6qyksaqrpvs-texlive-inconsolata-1.05.drv’ failed
```

**Comment by domenkozar** [comment]
@vcunat why don't we just update the hashes?

**Comment by vcunat** [comment]
It's good to have a stable mirror anyway, and I hoped the problems could be fixed even on older nixpkgs versions without having to update and re-test stuff.

**Comment by domenkozar** [comment]
So if we update the hashes and then mirror, the plan would work :)

**Comment by ttuegel** [comment]
Is there any progress on this? The new TeXLive packages are unusable in the latest release branch.

**Comment by namore** [comment]
Is there a way to work around this for now? I can't install texlive-full and -medium lacks packets which I need.

**Comment by ttuegel** [comment]
@namore You should be able to fix the hash in your copy of Nixpkgs by changing it [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/fixedHashes.nix).

**Comment by namore** [comment]
@ttuegel It appears both pkgs.nix and fixedHashes.nix require an update. The first file contains md5 hashes and the latter sha1 hashes.

I identified at least 2260 hashes that need updating to install texlive-full. Since I already changed them, should I open a pull request with the updated hashes?

**Comment by michalrus** [comment]
This is really unfortunate. :crying_cat_face:

**Comment by peti** [comment]
@namore, please do.

**Comment by sorpaas** [comment]
@namore, can you share the commit? I'm in need of installing the `texlive` packages, which is apparently broken now.

**Comment by namore** [comment]
@sorpaas, @peti, I pushed the commit to my fork [1]. I'm not sure if it contains *all* missing hashes, but the changes allow me to me to build texlive.combined.scheme-full.
[1] [https://github.com/namore/nixpkgs/commit/a07b7bb2637a97facae55cf8837c2a27ce1892ed]

**Comment by peti** [comment]
I've committed a (slightly modified) patch in 7abe192b05eea78610d6eea755a66fcb93a77b68. These hashes get out of sync fast! I just hope that our source tarball mirroring works now or we'll have the exact same problem again in a couple of days.

**Comment by vcunat** [comment]
> I just hope that our source tarball mirroring works now

I don't think it works in this case: https://github.com/NixOS/nixpkgs/issues/10026#issuecomment-207395665

BTW, over the long term, we might better use a combination of package versions as close as possible to what's released upstream, instead of a snapshot at some random moment.

**Comment by sorpaas** [comment]
Hi @namore, can you share the code you used to generate `fixedHashes.nix`?

**Comment by vcunat** [comment]
Note: the source files in master contain shell fragments I used to get all the generated stuff. They're in comments at the point where the generated file is included from the rest.

**Comment by namore** [comment]
@vcunat, I could not successfully use the commands in the comments and gave up trying after a while. I had the impression that they were out of date, but I may be wrong.
@sorpaas, the script I used to fix the hashes is as follows:

```
#!/bin/sh
set -u
set -e

function fh { sed -i "s/$1/$2/" pkgs.nix; }
function fh2 { sed -i "s/$1/$2/" fixedHashes.nix; }

TMP=`mktemp`
set +e
nix-env -f ~/nixpkgs --keep-going -i -A texlive.combined.scheme-full > $TMP 2>&1
cat $TMP >&2
set -e
grep '^output path.*md5 hash' $TMP |\
    awk '{ print $9 " " $7 }'|\
    sed -r 's/[‘’]//g' |\
    tee /dev/stderr |\
    while read f; do
        fh $f
    done
grep '^output path.*r:sha1 hash' $TMP |\
    awk '{ print $9 " " $7 }'|\
    sed -r 's/[‘’]//g' |\
    tee /dev/stderr |\
    while read f; do
        fh2 $f
    done
rm -f $TMP
```
I ran the script a few times until all hash related errors were resolved.

**Comment by vcunat** [comment]
Well, yes, it is possible they changed the format of tlpdb.

**Comment by vcunat** [comment]
Interested parties can pre-test texlive-2016: https://github.com/NixOS/nixpkgs/pull/16391

**Comment by vcunat** [comment]
Let's close this texlive 2015 discussion.  Problems around mirroring the current 2016 version can be discussed on https://github.com/NixOS/nixpkgs/issues/24683.
