### ISSUE TITLE
dwarf-fortress: game doesn't resize viewport when window is resized

### ISSUE THREAD

**Issue by fazo96** [NixOS/nixpkgs#10027]
The game only reacts to window resizes if ran in text mode (inside the terminal)

**Comment by abbradar** [comment]
I've seen this issue -- apparently it _does_ resize but only _sometimes_ -- I recall I was able to resize it if I _slowly_ increased the window size, or something like that.
This appears to be a DF (libgraphics) bug, sadly, I've tried to debug this long ago but to no avail.

**Comment by Profpatsch** [comment]
(triage) So it’s an upstream issue? In that case I suggest we close.

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/234f4611393a6818b317f3ad93d2e276515bdc33
