### ISSUE TITLE
Inaccurate "Manual configuration of HTTP-01 validation" documentation for NixOS 20.09

### ISSUE THREAD

**Issue by JustinLovinger** [NixOS/nixpkgs#100276]
The NixOS manual says

```
# /var/lib/acme/.challenges must be writable by the ACME user
# and readable by the Nginx user.
# By default, this is the case.
```

https://nixos.org/manual/nixos/unstable/index.html#module-security-acme-configuring

This no longer appears to be the default case in NixOS 20.09. I had to add the `nginx` user to the `acme` group.

**Comment by aanderse** [comment]
@JustinLovinger any chance you have capacity to update in a PR?

**Comment by JustinLovinger** [comment]
@aanderse I could probably do it in a few days, if nobody else wants to.

**Comment by aanderse** [comment]
ping @NixOS/acme in case anyone is motivated.

**Comment by m1cr0man** [comment]
I'll update that today, thanks for pointing it out. I'll evaluate if it's worth doing it automatically too.
