### ISSUE TITLE
Include python39.pkgs in hydra jobsets

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#100382]
python3.9 is now stable. When did you want to recurseInto the package set @FRidh ?

Seems that there was quite a bit of removals done with python3.9, I think we can wait a few weeks for upstream packages to "stabilize" before trying to do it ourselves.

**Comment by FRidh** [comment]
I think we can wait a month or two before doing that, because like you said, there is plenty of fixing to be done. Of course, now with yearly releases this will have to go faster, and I think we may need to recurse into at least one more set at a time.

**Comment by jonringer** [comment]
cc @FRidh we should probably do a `python-unstable` update before attempting python39. Probably after the current `staging-next` cycle

**Comment by jonringer** [comment]
I tried taking a stab at this on staging.

flake8 supports 3.9 on master, but they haven't cut a release yet
https://github.com/PyCQA/astroid/issues/845 is causing pylint to fail

**Comment by jonringer** [comment]
since #103360 got merged, closing

**Comment by FRidh** [comment]
Given we now release in May and Pythons new yearly releases, we likely should make 3.9 the default interpreter as well. Would probably be good to backport some 3.9 stuff to 20.09 then.
