### ISSUE TITLE
DHCP-less install: broken workaround documentation in 14.12

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#10034]
Problem components:
- DHCP is sometimes unavailable
  - this is a premise, that is outside of our control
- manual network config is wiped out by `nixos-install`, because it somehow triggers network-manager
  - this is undesirable, per se -- why not be able to continue with manual network config?
  - a supposed workaround is documented in the NixOS manual (the very beginning of https://nixos.org/nixos/manual/sec-installation.html)
- the suggested workaround (which is `systemctl stop network-manager') *does not work*
  - network-manager continues running
  - something is broken about the networkmanager's systemd service handling in NixOS
- the working alternative is:
```
nmcli nm disable
```

**Comment by domenkozar** [comment]
It's important to note here, you're using graphical installer and not minimal.

**Comment by deepfire** [comment]
@domenkozar, true.

**Comment by joachifm** [comment]
Please re-open if the problem exists in a recent release
