### ISSUE TITLE
bump Gnome to 3.18

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10031]
Gnome 3.18 is out: https://www.gnome.org/news/2015/09/gnome-3-18-released-brings-big-improvements/

**Comment by DamienCassou** [comment]
cc @lethalman are you on it? Do you need help?

**Comment by lethalman** [comment]
Yes I'm already on it. Currently debugging the new gobject-introspection build, it's failing because of custom stupid build commands.

**Comment by lethalman** [comment]
Also cc @geerds

**Comment by lethalman** [comment]
@vcunat I'm updating the whole gtk stack, will push everything to staging when it works...

**Comment by vcunat** [comment]
@lethalman: recently I pushed some gtk stack changes into staging (all just simple updates, though).

**Comment by lethalman** [comment]
Ok I've just sorted the GI build issue. Now compiling the world....

**Comment by lethalman** [comment]
So I've updated libsigc++, glib, cairomm, glibmm... and pangomm has this horrible code in context.h:

```
  Context(Context&& src) noexcept;
```

That double & is really invalid C++.

**Comment by edolstra** [comment]
No, that's valid C++11.

**Comment by lethalman** [comment]
Ok so it must be a problem with the pangomm build not specifying c++11?

**Comment by lethalman** [comment]
Ah ok, so something depending on pangomm is not compiling with c++11.

**Comment by lethalman** [comment]
And that "something" is gtkmm 2.24 :(

**Comment by vcunat** [comment]
What about remaining on pangomm-2.36.0 for now? That shouldn't break anything, right? I see only [one bug](https://bugzilla.gnome.org/show_bug.cgi?id=751531) mentioned in the news and we could pick that patch.

**Comment by lethalman** [comment]
@vcunat gtkmm requires 2.38. I will try to stick gnome c++ modules to the older version.

**Comment by vcunat** [comment]
I think, if we have some temporary solution now, someone else (upstream/distro) will find a long-term reliable one soon. The pango stable release was just a few days ago...

**Comment by lethalman** [comment]
Built the test, will push to staging today...

**Comment by geerds** [comment]
:beers:

**Comment by vcunat** [comment]
Packaged in one day!?

**Comment by lethalman** [comment]
@vcunat yep, as usual... that's nixos :D

**Comment by lethalman** [comment]
Pushed to staging. Closing this, I will put the missing bits in the usual issue #247
