### ISSUE TITLE
JuliaMono

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#100328]
**Project description**
JuliaMono - a monospaced font for scientific and technical computing

**Metadata**

* homepage URL: https://juliamono.netlify.app/
* source URL: https://github.com/cormullion/juliamono
* license:  OFL-1.0
* platforms: unix, linux, darwin, ...

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/100130

**Comment by toastal** [comment]
closed by #100130
