### ISSUE TITLE
Disabling gdm.autoSuspend still auto suspends

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#100390]
**Describe the bug**
It seems you can't disable GDM's auto suspend behaviour. Disable `gdm.autoSuspend` has no effect.

**To Reproduce**
1. Set `gdm.autoSuspend = false`
1. Your laptop will auto suspend after timeout

**Expected behavior**
Suppress auto suspend.

**Additional context**
Follow up from https://github.com/NixOS/nixpkgs/issues/42053#issuecomment-636186499

**Notify maintainers**
@NixOS/gnome 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.0, NixOS, 21.03pre246062.420f89ceb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos, home-manager, nixos-hardware, nixpkgs-master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by srid** [comment]
I'm on Wayland if that matters.

**Comment by worldofpeace** [comment]
I believe it only touches the dconf profile in gdm, and sets these settings https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/gdm.nix#L233. You probably still have those set in your actual session. See the OP of https://github.com/NixOS/nixpkgs/pull/63790#issue-291750039 for more details.

**Comment by worldofpeace** [comment]
Though I could be misremembering things

**Comment by ryantm** [comment]
Not sure if it will work yet, but I ran these commands to make my settings match the autosuspend = false settings:

```
[ryantm@home1:~]$ dconf dump /org/gnome/settings-daemon/plugins/power/
[/]
power-button-action='nothing'
sleep-inactive-ac-timeout=3600
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-timeout=1800
sleep-inactive-battery-type='nothing'

[ryantm@home1:~]$ dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout 0

[ryantm@home1:~]$ dconf dump /org/gnome/settings-daemon/plugins/power/
[/]
power-button-action='nothing'
sleep-inactive-ac-timeout=0
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-timeout=1800
sleep-inactive-battery-type='nothing'

[ryantm@home1:~]$ dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout 0

[ryantm@home1:~]$ dconf dump /org/gnome/settings-daemon/plugins/power/
[/]
power-button-action='nothing'
sleep-inactive-ac-timeout=0
sleep-inactive-ac-type='nothing'
sleep-inactive-battery-timeout=0
sleep-inactive-battery-type='nothing
```

**Comment by ryantm** [comment]
After making these changes, it still suspended. Then I killed `gdm`, and since it has restarted it has not auto suspended. I'm not sure if this is the simplest thing, but what worked for me was:

* set `gdm.autoSuspsend = false`, rebuild NixOS
* 
  ```
  dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout 0
  dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout 0
  ```
* Kill `gdm` so it restarts

**Comment by juanibiapina** [comment]
`dconf dump /org/gnome/settings-daemon/plugins/power/` returns nothing for me on unstable. I have `autoSuspend` set to false.

**Comment by ryantm** [comment]
Well, it started auto-suspending for me again, even with the above settings.

**Comment by ryantm** [comment]
I'm trying this now:

```nix
{
  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.login1.suspend" ||
            action.id == "org.freedesktop.login1.suspend-multiple-sessions" ||
            action.id == "org.freedesktop.login1.hibernate" ||
            action.id == "org.freedesktop.login1.hibernate-multiple-sessions")
        {
            return polkit.Result.NO;
        }
    });
  '';
}
```

**Comment by ryantm** [comment]
Seems to be working!

**Comment by juanibiapina** [comment]
In my case it was xorg, not gdm at all. I disabled screensaver and autosuspend with:
```
xset s off -dpms
```

**Comment by chrisguida** [comment]
Wow, it's 2023, and this still appears to be the solution https://github.com/NixOS/nixpkgs/issues/100390#issuecomment-867830400

**Comment by l0b0** [comment]
I vote to reopen this. The fix is easy to configure, but difficult to understand.

**Comment by chrisguida** [comment]
It seems like "don't suspend my system, i'm running this as a server" should just be a single config option

**Comment by telometto** [comment]
Still not working.
