### ISSUE TITLE
package nomachine-client   cannot build

### ISSUE THREAD

**Issue by bear5-lab** [NixOS/nixpkgs#100377]
**Describe the bug**
the package nomachine-client cannot build
https://github.com/NixOS/nixpkgs/blob/nixos-19.09/pkgs/tools/admin/nomachine-client/default.nix

trying https://download.nomachine.com/download/6.11/Linux/nomachine_6.11.2_1_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0      8      0  0:00:17  0:00:15  0:00:02    30
100  142k    0  142k    0     0   7033      0 --:--:--  0:00:20 --:--:-- 32884
hash mismatch in fixed-output derivation '/nix/store/qgm0ps149dm4n0z76rhyl647mvg52qar-nomachine_6.11.2_1_x86_64.tar.gz':
  wanted: sha256:1b6r9bwkr8mhaljma19ikxpkmlx8iy5r1vf5hlv27bja2zz1r8xr
  got:    sha256:1jpyp2z2qy1dh8w40qbid7yjffq6gp940krxsfd3d7n4pr9a268w
cannot build derivation '/nix/store/q4wkpnggxd0y0g4drjib6g1swxawfp1w-nomachine-client-6.11.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zzsga5l3qh8anqymvcbxl8az92ka6jy9-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/plvdk8jn20k891hrkxcb9kvr8685wnvi-nixos-system-Bach-20.03.2685.977000f149b.drv': 1 dependencies couldn't be built
error: build of '/nix/store/plvdk8jn20k891hrkxcb9kvr8685wnvi-nixos-system-Bach-20.03.2685.977000f149b.drv' failed

running on 20.03

**To Reproduce**
environment.systemPackages = with pkgs; [
  nomachine-client
];

**Notify maintainers**
@talyz

**Metadata**
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev
copying path '/nix/store/d43v6bx7r6fcaq3fbbfd5mwh1f5s7rmg-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.54, NixOS, 20.03.2685.977000f149b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by austinbutler** [comment]
May be fixed by https://github.com/NixOS/nixpkgs/pull/99395.

**Comment by wucke13** [comment]
This needs to be backported as well

**Comment by talyz** [comment]
Backported in #100564 and  #100562.
