### ISSUE TITLE
NixOS option defaults referring to store paths should display in manual

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#10039]
Relevant: 89e983786a4e2cf6dd238af4df6da373cc01e62b #10036

**Comment by Mathnerd314** [comment]
Maybe something like:
```
  mkOption {
    default = "${pkgs.xxx}";
    default-for-manual = "\${pkgs.xxx}";
  }
```

**Comment by edolstra** [comment]
That would be bad due to the code duplication.

**Comment by vcunat** [comment]
We might do the context discarding as before 5b8dae8ef3 and then delete `/nix/store/hash-` substrings (during eval-time). It would likely be relatively expensive, unless we restrict it to the beginnings of defaults, but that seems to be vast majority in 89e9837.

Perhaps a cleaner way would be to have something like `"${config.sanitizeDrv pkgs.foo}/bar/baz"`. The `sanitizeDrv` function would normally be an identity but for manual it would e.g. return `.name` instead (or perhaps some other hack in case the argument didn't have `.name`, e.g. the same strategy of discarding context and deleting hash).

**Comment by Mathnerd314** [comment]
How about evaluating the manual with ``pkgs = mapAttrs (name: value: "\${pkgs.${name}}") pkgs``?

**Comment by vcunat** [comment]
Yeah, that's probably the best way (so far) to cover most cases.

**Comment by nbp** [comment]
@vcunat removing the `/nix/store/hash-` would only remove one of the issues, which is that the manual contains references, but this does not solve the problem which is that the manual is rebuilt when you generate your configuration.

The `sanitizeDrv` sounds like an interesting idea, except that you probably expect to have a string input for the documentation.

@Mathnerd314 This sounds like a good idea! Are you interested in taking this issue?

**Comment by vcunat** [comment]
@nbp: I meant to strip the dependencies at *evaluation* time, i.e. the same derivation would be generated if only the hashes have changed, I believe.

**Comment by vcunat** [comment]
Implementation: #12357.
