### ISSUE TITLE
php: PEAR.php cannot be found

### ISSUE THREAD

**Issue by buckley310** [NixOS/nixpkgs#100440]
**Describe the bug**
On NixOS 20.09 and unstable, `PEAR.php` is not in the search path, even though it is installed with the php package.
[Some software requires this](https://github.com/phpipam/phpipam/blob/9b8abfbd1244031ca62ddc7179e7900332bdc19e/functions/PEAR/Net/IPv4.php#L24)

**To Reproduce**
[example from 20.09 system]
```
$ nix-shell -p php
$ php -r 'assert (@include_once "PEAR.php") && print("OK\n");'
Warning: assert(): assert(@include_once('PEAR.php')) failed in Command line code on line 1
```

**Expected behavior**
[example from 20.03 system]
```
$ nix-shell -p php
$ php -r 'assert (@include_once "PEAR.php") && print("OK\n");'
OK
```

**Additional context**
Debugging with `strace` reveals that on 20.09, php is searching in `$PWD`, then `/lib/php/pear/`, which fails. On 20.03, it searches in `$PWD`, then `/nix/store/xhb7bwcx29xff2zzh7rkmrhsm7rh74z6-php-7.3.23/lib/php/`, which succeeds.

On 20.09 and unstable, php74 and php73 both fail.
On 20.03, php73 (the default) works, but php74 fails, but I believe it fails for a different reason.

This line is new since release-20.03. At first glance, it seems as though `$(out)` is resolving to null here, but I'm not sure what to replace it with:
https://github.com/NixOS/nixpkgs/blob/a07508c1d34138df95c6c81ac0e4aedb42914dc3/pkgs/development/interpreters/php/default.nix#L180

**Notify maintainers**
 @aanderse @etu @globin @ma27 @talyz

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.70, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"sconfig, nixos-20.09beta1057.0b8799ecaaf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
    php
```

**Comment by etu** [comment]
@buckley310 Thanks for reporting this issue! Your guess was right on spot and it was a really simple fix it seems :slightly_smiling_face: 

As you may have seen: Right after 20.03 branched off we started a big refactoring of the PHP ecosystem. So bugs and issues was to be expected :slightly_smiling_face:
