### ISSUE TITLE
Pantheon: screenshots are darker when selecting the area

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#100434]
**Describe the bug**
When i create a screenshot using PRINT key, it's as expected.

![Screenshot from 2020-10-13 20-05-36](https://user-images.githubusercontent.com/91113/95898699-bb5f4700-0d8f-11eb-8ffe-c68384fd2e0b.png)

But when i select an area, it is darker.

![Screenshot from 2020-10-13 20-02-05](https://user-images.githubusercontent.com/91113/95898739-cca85380-0d8f-11eb-9c8f-363373c2c0c6.png)

Not when i select a window.

![Screenshot from 2020-10-13 20-08-27](https://user-images.githubusercontent.com/91113/95898791-df228d00-0d8f-11eb-99f9-8ce2da713332.png)

**To Reproduce**
1. use pantheon desktop
2. snapshot using SHIFT + PRINT
3. see snapshot

**Expected behavior**
image not altered

**Additional context**
was not an issue in 20.03

**Notify maintainers**
@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13, NixOS, 20.09beta992.7badbf18c45 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta992.7badbf18c45, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/home/davidak/.cache/nixpkgs-review/pr-99931/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
This seems to be fixed after an update.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09beta1057.0b8799ecaaf, nixos-hardware, nixos-unstable-21.03pre246062.420f89ceb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
Oh noooooooooooooooooooooooooooooooo it's there again.

**Comment by davidak** [comment]
I guess the dark space is the selection that is not removed quickly enough, so it is a timing issue.

@worldofpeace can you reproduce it? don't happen always, but in 3 of 5 cases...

this is a blocker for me since my work involves taking screenshots a lot. i don't want it to block the release, but it has higher priority than the other issues i reported

still happens in latest 20.09beta1322.ba2ec4867d7

**Comment by worldofpeace** [comment]
I've never had this issue. This has to do with the screenshot window timeouts, see these issues https://github.com/elementary/screenshot/issues/50 https://github.com/elementary/gala/issues/211. In the issue for gala someone was actually able to reproduce it recently https://github.com/elementary/gala/issues/211#issuecomment-705239902.
The issue here is, pantheon's development is steered to their upcoming release. So gala master and screenshot master are way ahead. So we'd have to try to reproduce on those, but currently gala master doesn't build https://github.com/elementary/gala/issues/915. I intend to fix that issue but I have too much to do sometimes.

**Comment by worldofpeace** [comment]
Opened a PR to fix that in gala https://github.com/elementary/gala/pull/945

**Comment by davidak** [comment]
Great. The PR was merged. Do you plan to backport it?

**Comment by worldofpeace** [comment]
> Great. The PR was merged. Do you plan to backport it?

I'd doesn't fix this exact issue. Currently those other reports I linked prove that the current state is a regression, or on your machine the timeout isn't sufficent

**Comment by davidak** [comment]
Just checked. This issue is not present in NixOS 20.03.3185.6b5f85a62c4.
