### ISSUE TITLE
Make llvmPackages_3_7 the default?

### ISSUE THREAD

**Issue by gridaphobe** [NixOS/nixpkgs#10046]
Based on #9329 it seems that OSX 10.11 will need to use clang-3.7. Are there any objections (particularly from linux-land) to making `llvmPackages_3_7` the default? 

We could set the default for darwin only, but I'd rather not do that unless there's a good reason.

**Comment by wkennington** [comment]
AFAIK we can't until mesa 11.x is used. cc @vcunat

**Comment by vcunat** [comment]
Yes, 10.x would have to be patched to compile with 3.7, but default doesn't determine what mesa uses. Typically the support needs to be tested per-package anyway, as things tend to break.

**Comment by joachifm** [comment]
As far as I can tell, llvm 3.7 is the default now.
