### ISSUE TITLE
Bad onlykey udev rule

### ISSUE THREAD

**Issue by ranfdev** [NixOS/nixpkgs#100513]
The onlykey udev rule in `modules/hardware/onlykey.udev` is different from the one available on the onlykey documentation here
https://docs.crp.to/linux.html
The onlykey isn't recognized using the udev rules currently available on the nixpkgs tree.  

I don't know why the two rules are completely different... Maybe there are two different versions of the onlykey out there using different hardware?

Anyway, my workaround to get the onlykey working:
add the correct udev rule manually, by using the `services.udev.extraRules` option in your configuration.nix
https://nixos.org/manual/nixos/stable/options.html#opt-services.udev.extraRules

**Comment by jtojnar** [comment]
Looks like it has been mentioned in the original pull request without response from the OP: https://github.com/NixOS/nixpkgs/pull/33794#issuecomment-515096098

The changes appears to have been done in https://github.com/trustcrypto/trustcrypto.github.io/commit/0bcf928adaea559e75efa02ebd1040f0a15f611d#diff-70a56882bec9bf0db6e8ef9343bdb79a311db6beae6f76803651c80fa419d529 so maybe ask there.
