### ISSUE TITLE
Raspberry Pi 3: how do I enable UART and GPIO access?

### ISSUE THREAD

**Issue by tmplt** [NixOS/nixpkgs#100620]
I'm working on a project with a Raspberry 3 Model B where I need to use SPI, UART and the GPIO pins. I'm building a bootable image by importing `<nixpkgs/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix>`.

By some help of @sorki, I've managed to get SPI up and running by [applying a device-tree overlay](https://github.com/tmplt/ed7039e/commit/f45470d905b0d463c7d61d3ca81c478d13757cdb#diff-9c43fab8d7e1cd411cd305aa92c6c5a7142f00bb61a994c5574f333849d5eb05R89) on `linuxPackages_4_19` using #79370. But thus far I've had no success with UART or GPIO.

When using `boot.kernelPackages  = pkgs.linuxPackages_rpi3` (the only kernel tried where the expected `/dev/ttyAMA0` appears), a UART loopback test (shorting the UART TX/RX pins and using `screen /dev/ttyAMA0 115200` to enter some bytes) fails.

I haven't digged as much into GPIO support yet: thus far I have tried to use [gpiozero](https://pypi.org/project/gpiozero/) which fails because it tries to parse out a "Revision\t:" field from `/proc/cpuinfo` that does not exist.

Is there a known way to properly enable GPIO and UART access? 

---

For sake of context, my NixOS configuration can be found [here](https://github.com/tmplt/ed7039e/blob/master/mmc-image.nix).

**Comment by Gaelan** [comment]
For GPIO, see if the commands from `libgpiod` work. Those use the new character device ABI (`/dev/gpiochip0`), which is the preferred way to do such things these days. If you can find a library for your language that uses that ABI, that would be best.

**Comment by adminy** [comment]
will this work for orange Pi 5 plus also?

**Comment by sorki** [comment]
> will this work for orange Pi 5 plus also?

Not sure what exactly are you asking about but  both `libgpiod` and UART should work out of box on most boards.

**Comment by sorki** [comment]
Looks very dated and no sure if there's anything actionable here, feel free to reopen if needed.
