### ISSUE TITLE
mpv-with-scripts and wrapMpv are confusing

### ISSUE THREAD

**Issue by jktjkt** [NixOS/nixpkgs#100771]
**Describe the bug**
The [wiki says](https://nixos.wiki/wiki/MPV) that this is how I'm supposed to add scripts to my `mpv` binary:

```nix
{
nixpkgs.overlays = [
  (self: super: {
    mpv = super.mpv-with-scripts.override {
      scripts = [ self.mpvScripts.<your choice> ];
    };
  })
];
}
```

That does not work:

- if I name my derivation `mpv`, then I get a binary `mpv` in my `$PATH`, not a shell script,
- if I name my derivation `mpv-with-scripts`, then I get a wrapper, but that wrapper doesn't wrap any scripts.

If I use an overlay like this:

```nix
self: super:
let
  lib = self.pkgs.lib;
  stdenv = self.pkgs.stdenv;
in rec {
  mpv = super.wrapMpv super.mpv-unwrapped {
    scripts = [
      super.mpvScripts.mpris
    ];
  };
}
```
...I get a infinite recursion. The only way that I was able to come up with (thanks to @lukebfox on IRC) was by naming the package differently, such as:
```nix
self: super:
let
  lib = self.pkgs.lib;
  stdenv = self.pkgs.stdenv;
in rec {
  mpv_jkt = super.wrapMpv super.mpv-unwrapped {
    scripts = [
      super.mpvScripts.mpris
    ];
  };
}
```

Cc: @doronbehar @AndersonTorres because of #88620.

```shell-session
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 21.03pre246543.24c9b05ac53 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre246543.24c9b05ac53"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lukebfox** [comment]
The mpvScripts.mpris derivation depends on pkgs.mpv. When one makes an mpv overlay addings mpris as a script, nix fails when evaluating the reference to mpv in mpris' buildInputs. As mpris is only script with mpv dependency maybe it was missed in translation to new wrapper style? Should probably be mpv-unwrapped now.

Quickfix for those trying to use mpv with mpris.
```nix
self: super: {
  mpvScripts.mpris = super.mpvScripts.mpris.override {
    mpv = self.mpv-unwrapped;
  };
  mpv = super.wrapMpv super.mpv-unwrapped {
    scripts = [ self.mpvScripts.mpris ];
  };
}
```

**Comment by doronbehar** [comment]
@jktjkt the wiki is outdated. Sorry for your bad experience. `mpvScripts.mpris` indeed was defined bad.   #100779 should fix it.
