### ISSUE TITLE
tinycc fails to build on darwin

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#100749]
**Describe the bug**
Currently, `tinycc` fails to build on macOS. It would be great to fix this, since `tinycc` is a valuable component for bootstrapping larger C compilers and would enable the building of a few other packages that depend on it.

Related draft PR: #100748

**Comment by wegank** [comment]
[Fixed](https://hydra.nixos.org/job/nixpkgs/trunk/tinycc.x86_64-darwin) on x86_64-darwin.
