### ISSUE TITLE
racket: fix on darwin

### ISSUE THREAD

**Issue by martinklepsch** [NixOS/nixpkgs#10073]
Racket isn't restricted to linux.

https://github.com/NixOS/nixpkgs/blob/89cec0c096d3b06c61553d616cabbab229ea616f/pkgs/development/interpreters/racket/default.nix#L79

**Comment by vcunat** [comment]
Have you tried it on Darwin? (I suppose that's what you're after.)

**Comment by martinklepsch** [comment]
I tried and couldn't get it to build on Darwin. Ultimately I decided I just want racket minimal and wrote a package for that which was easier as it had less dependencies/needs.

**Comment by domenkozar** [comment]
see 2e62f785d49f0dc386b3b93ceb20965ee9ce39cd

**Comment by gridaphobe** [comment]
fixed in 2e62f785d49f0dc386b3b93ceb20965ee9ce39cd and dd6d4ca8cc76b5396d58a1971ffed351bff090ad
