### ISSUE TITLE
Mathematica 12 does not start

### ISSUE THREAD

**Issue by bgamari** [NixOS/nixpkgs#100861]
**Describe the bug**
`Mathematica` fails to start with a Qt error.

**To Reproduce**

```
$ nix run nixpkgs.mathematica -c Mathematica
Qt issued a fatal error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.


Qt tried to load plugins from:
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/Qt/plugins
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64

Mathematica was installed in /nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/bin/Mathematica: line 139: 23864 Aborted                 (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"
```

**Expected behavior**
Mathematica starts.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1057.0b8799ecaaf (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09beta1057.0b8799ecaaf, nixpkgs-20.09beta1057.0b8799ecaaf"`
 - channels(ben): `"nixpkgs-20.09beta1083.51aaa3fa1b6, nixpkgs-20_03-20.03.3122.ff6fda61600, nixpkgs-unstable-21.03pre246624.cfed29bfcb2, nixos-18.09-18.09.2574.a7e559a5504"`
 - nixpkgs: `/home/ben/.nix-defexpr/channels/nixpkgs`


```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bgamari** [comment]
Cc @herberteuler

**Comment by bgamari** [comment]
`LD_DEBUG=libs Mathematica` suggests that it's looking for `libQt5XcbQpa.so`:
```
     24279:     find library=libQt5XcbQpa.so.5 [0]; searching
     24279:      search path=/nix/store/9sfmwj09ij65qnc8dgv8h56gf12b60nn-zlib-1.2.11/lib:/nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib          (RUNPATH from file /nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica)
```
This object is present at `/nix/store/qmjjvsygp3hcbwrw559fv3fh9idgmqns-mathematica-11.3.0/libexec/Mathematica/SystemFiles/Components/WSMCore/SystemModeler/SystemFiles/Libraries/Linux-x86-64/libQt5XcbQpa.so.5`. However, adding this directory to `LD_LIBRARY_PATH` then reveals further trouble:
```
$ LD_LIBRARY_PATH=/nix/store/qmjjvsygp3hcbwrw559fv3fh9idgmqns-mathematica-11.3.0/libexec/Mathematica/SystemFiles/Components/WSMCore/SystemModeler/SystemFiles/Libraries/Linux-x86-64:$LD_LIBRARY_PATH Mathematica
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica: error while loading shared libraries: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```
`libgthread.so` is also included in the installation; adding this directory:
```
$ LD_LIBRARY_PATH=/nix/store/qmjjvsygp3hcbwrw559fv3fh9idgmqns-mathematica-11.3.0/libexec/Mathematica/SystemFiles/Components/WSMCore/SystemModeler/SystemFiles/Libraries/Linux-x86-64:/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/Links/MIMETools/LibraryResources/Linux-x86-64:$LD_LIBRARY_PATH Mathematica
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica: /nix/store/qmjjvsygp3hcbwrw559fv3fh9idgmqns-mathematica-11.3.0/libexec/Mathematica/SystemFiles/Components/WSMCore/SystemModeler/SystemFiles/Libraries/Linux-x86-64/libQt5Core.so.5: version `Qt_5.11' not found (required by /nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica)
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica: /nix/store/qmjjvsygp3hcbwrw559fv3fh9idgmqns-mathematica-11.3.0/libexec/Mathematica/SystemFiles/Components/WSMCore/SystemModeler/SystemFiles/Libraries/Linux-x86-64/libQt5Core.so.5: version `Qt_5.11' not found (required by /nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/../../../Libraries/Linux-x86-64/Qt/lib/libQt5DBus.so.5)
```

It does appear that the derivation is doing some amount of `patchelf`ing although it's undocumented so it's quite unclear precisely what package references are patched and why.

**Comment by Wulfsta** [comment]
I can replicate this - I don't understand why #100056 worked when I tested it whereas calling Mathematica again using `USE_WOLFRAM_LD_LIBRARY_PATH=1 mathematica` appears to work. Anyone have suggestions?

**Comment by Wulfsta** [comment]
In fact, it appears my `nixpkgs/mathematica` branch does work when executing `mathematica` in a `nix-shell` with the package included. I checked `env` and `USE_WOLFRAM_LD_LIBRARY_PATH` doesn't appear to be set, so I'm at a loss as to why this is happening.

**Comment by LEXUGE** [comment]
> In fact, it appears my `nixpkgs/mathematica` branch does work when executing `mathematica` in a `nix-shell` with the package included. I checked `env` and `USE_WOLFRAM_LD_LIBRARY_PATH` doesn't appear to be set, so I'm at a loss as to why this is happening. To my understanding, the executable should still be wrapped, and doing
> 
> ```
> $ nix-shell -I nixpkgs=../nixpkgs -p mathematica
> ```
> 
> from a clone of [this](https://github.com/Wulfsta/nixpkgs/tree/mathematica) and then
> 
> ```
> [nix-shell: ... ]$ mathematica
> ```
> 
> successfully executes the software. Whereas just doing
> 
> ```
> $ nix-shell -p mathematica
> ```
> 
> and
> 
> ```
> [nix-shell: ... ]$ mathematica
> ```
> 
> fails with the same Qt error.

Would that suggest that other parts of the nixokgs changed? Changes/upgrades in other libraries may cause issue.

**Comment by Wulfsta** [comment]
> Would that suggest that other parts of the nixokgs changed? Changes/upgrades in other libraries may cause issue.

It doesn't [appear](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/make-wrapper.sh) that `makeWrapper` has changed at least.

**Comment by LEXUGE** [comment]
How about other libraries like Qt? Is Mathematica using vendor libraries or those from nixpkgs?

**Comment by bgamari** [comment]
It appears that the Qt version mismatch was due to the fact that I was adding the wrong library directory to `LD_LIBRARY_PATH`; Mathematica apparently ships with two distinct versions of `qt`.

Things may be getting a bit farther with:
```
$ LD_LIBRARY_PATH=/nix/store/qmjjvsygp3hcbwrw559fv3fh9idgmqns-mathematica-11.3.0/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64:/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/Links/MIMETools/LibraryResources/Linux-x86-64:$LD_LIBRARY_PATH nix run nixpkgs.mathematica -c Mathematica
/nix/store/skrn8xh6bs5ismnvcybg8di2cxxi7iw3-mathematica-12.1.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64/Mathematica: symbol lookup error: /nix/store/fhqsi8l4q0q46vzsp6k4w4bxx3b9ypm9-fontconfig-2.13.92-lib/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```

This appears to be due to https://bugzilla.redhat.com/show_bug.cgi?id=1645237.

**Comment by LEXUGE** [comment]
![image](https://user-images.githubusercontent.com/13804737/96357681-a38e1700-1131-11eb-8426-11e63bca11e8.png)
One of our group member suggests FHS Env is working for him. Despite being dirty, it works.

**Comment by hmenke** [comment]
Does this help?
```bash
export USE_WOLFRAM_LD_LIBRARY_PATH=1
export QT_XCB_GL_INTEGRATION=none
mathematica
```

**Comment by bgamari** [comment]
> Does this help?
> 
> ```shell
> export USE_WOLFRAM_LD_LIBRARY_PATH=1
> export QT_XCB_GL_INTEGRATION=none
> mathematica
> ```

Indeed Mathematica starts as expected with these. In fact, it looks like `USE_WOLFRAM_LD_LIBRARY_PATH` alone is sufficient.

**Comment by Wulfsta** [comment]
This is what's confusing me, the `wrapProgram` call in the derivation _should_ be executing the binary from inside an environment with `USE_WOLFRAM_LD_LIBRARY_PATH=1`.

**Comment by Wulfsta** [comment]
I think I know what's happening here; #100056 didn't trigger a rebuild of the deviation. I assume anyone having this issue has a deviation in the nix store that is not up to date with the current packaging. You will have to remove Mathematica from your system (remove from your config and do a `# nix-collect-garbage -d`, etc) and reinstall.

**Comment by bgamari** [comment]
@wulfsta, I don't see how that is possible. That PR touches `installPhase` which most certainly contributes to the input hash.

**Comment by Wulfsta** [comment]
@bgamari I don't have an exact explanation for this, but if `readlink -f $(which mathematica)` is not a bash script that sets that environment variable prior to executing `.mathematica-wrapped` then it's not up to date.

**Comment by bgamari** [comment]
Interesting. Well, indeed Mathematica in my case is not such a shell script:
```
$ cat $(readlink -f $(which mathematica))
#!/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/sh
export QT_XKB_CONFIG_ROOT="/nix/store/bgmq0wr9jwim83hh5yndj8c82wvj67mz-xkeyboard-config-2.27/share/X11/xkb"

export LD_LIBRARY_PATH=/nix/store/9sfmwj09ij65qnc8dgv8h56gf12b60nn-zlib-1.2.11/lib:/nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib/lib:/nix/store/ds88kjj0ivviba20wbjib77zk2k68yy1-libssh2-1.9.0/lib:${LD_LIBRARY_PATH}

#
#  Mathematica 12.1 Front End command file
#  Copyright 1988-2020 Wolfram Research, Inc.
...
```

**Comment by herberteuler** [comment]
Sorry for the delay.

I just tried the installation from the master branch, and it was different from your case:

```
$ cat $(readlink -f $(which mathematica))
#! /nix/store/k8p54jg8ipvnfz435mayf5bnqhw4qqap-bash-4.4-p23/bin/bash -e
export USE_WOLFRAM_LD_LIBRARY_PATH='1'
exec -a "$0" "/nix/store/cgplcwr4vk3icyhq7h2hn5n2ry5qwrv6-mathematica-12.1.1/bin/.mathematica-wrapped"  "$@"
```

There was another issue that `opencv2` was marked as broken on master, so I created another patch.

**Comment by NickHu** [comment]
I have a minor comment that doesn't warrant its own issue: the derivation doesn't include a .desktop file to start Mathematica. I would be surprised if it's not in the binary blob somewhere, and most likely the derivation just needs minor tweaking to include it.

**Comment by Wulfsta** [comment]
> I have a minor comment that doesn't warrant its own issue: the derivation doesn't include a .desktop file to start Mathematica. I would be surprised if it's not in the binary blob somewhere, and most likely the derivation just needs minor tweaking to include it.

I don't use this type of file and know nothing about them, but for anyone interested in doing this keep in mind that we launch a wrapper script to set environment variables, and simply exposing an existing file will likely show the same issues we had here.

**Comment by Wulfsta** [comment]
Closing this because it seems to be fixed; @bgamari please reopen if this is not true.

**Comment by NickHu** [comment]
> > I have a minor comment that doesn't warrant its own issue: the derivation doesn't include a .desktop file to start Mathematica. I would be surprised if it's not in the binary blob somewhere, and most likely the derivation just needs minor tweaking to include it.
> 
> I don't use this type of file and know nothing about them, but for anyone interested in doing this keep in mind that we launch a wrapper script to set environment variables, and simply exposing an existing file will likely show the same issues we had here.

I don't think this would be an issue, because the wrapper script replaces the `Mathematica` binary anyway (moving the original one to `.Mathematica-wrapped`).

**Comment by Sean1708** [comment]
@Wulfsta @bgamari This seems to have cropped up again:

```
$ Mathematica
Qt issued a fatal error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.


Qt tried to load plugins from:
/nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/Qt/plugins
/nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64

Mathematica was installed in /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica
/home/sean/.nix-profile/bin/Mathematica: line 142: 90591 Aborted                 (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"

$ USE_WOLFRAM_LD_LIBRARY_PATH=1 Mathematica
sh: /bin/uname: No such file or directory
sh: /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/Java/Linux-x86-64/bin/java: No such file or directory
```

Everything was working fine for me up until a week or two again, tried updating Mathematica but still didn't work.

If it's helpful:

```
$ uname -a
Linux srm-no-t570 5.10.52 #1-NixOS SMP Tue Jul 20 14:05:59 UTC 2021 x86_64 GNU/Linux

$ nixos-version
21.11pre305786.aaf9676fbb7 (Porcupine)

$ nix-env -q mathematica
mathematica-12.3.1
````

**Comment by Wulfsta** [comment]
> @Wulfsta @bgamari This seems to have cropped up again:
> 
> ```
> $ Mathematica
> Qt issued a fatal error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.
> 
> 
> Qt tried to load plugins from:
> /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/Qt/plugins
> /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64
> 
> Mathematica was installed in /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica
> /home/sean/.nix-profile/bin/Mathematica: line 142: 90591 Aborted                 (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"
> 
> $ USE_WOLFRAM_LD_LIBRARY_PATH=1 Mathematica
> sh: /bin/uname: No such file or directory
> sh: /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/Java/Linux-x86-64/bin/java: No such file or directory
> ```
> 
> It does work correctly (as far as I can tell) when using `USE_WOLFRAM_LD_LIBRARY_PATH`. Everything was working fine for me up until a week or two again, tried updating Mathematica but still didn't work.
> 
> If it's helpful:
> 
> ```
> $ uname -a
> Linux srm-no-t570 5.10.52 #1-NixOS SMP Tue Jul 20 14:05:59 UTC 2021 x86_64 GNU/Linux
> 
> $ nixos-version
> 21.11pre305786.aaf9676fbb7 (Porcupine)
> 
> $ nix-env -q mathematica
> mathematica-12.3.1
> ```

Weird, I just updated a few days ago and didn’t experience this. Unfortunately, I also can’t check right now because my machine is booted into a different OS training a neural network. I’ll try to remember to look in a few days if nobody else gets to this by then.

**Comment by Sean1708** [comment]
I've just noticed that launching `mathematica` (with a lowercase m) as opposed to `Mathematica` (with an uppercase M) seems to work fine:

```
$ Mathematica
Qt issued a fatal error: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.


Qt tried to load plugins from:
/nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/Qt/plugins
/nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64

Mathematica was installed in /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica
/home/sean/.nix-profile/bin/Mathematica: line 142: 146413 Aborted                 (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"

$ mathematica
sh: /bin/uname: No such file or directory
sh: /nix/store/a7inxprf8i26sncx6awdg53zv67k4h29-mathematica-12.3.1/libexec/Mathematica/SystemFiles/Java/Linux-x86-64/bin/java: No such file or directory
```

I remember that I was using `Mathematica` (with an uppercase M) because `mathematica` (with a lowercase m) didn't exist at the time that I started using Mathematica on Nix, but if `mathematica` works fine then I guess this isn't that big a deal.

**Comment by bitonic** [comment]
I've upgraded to Mathematica 13.1.0 (not yet in nixpkgs), and got this error again, fixed it by adding a couple of libraries: https://github.com/NixOS/nixpkgs/pull/194102 .

**Comment by TotallyBuiltLinuxDistro** [comment]
https://sourceforge.net/projects/totally-built-linux-distro/

src8,9 could not run 13.2 but src11 did.  it is NOT qt related it.  it is 100% having xorg i found.  all of the posts above are simply not the fact in this.

Qt is separate but integrated in Mathematica and doesn't use system Qt even if present.  Qt is always not at fault).  However Qt fails to load if your 'nix "xorg chain" isn't up to date.  (yes, past versions of MM can be gotten and do use X11 only or W95 or ?MAC only - if you downgrade - i would say 11.3 if using Xorg not XFree86, or previous if using XFree86)

the same is newly true of Mathematic 14 and (wayland xorg mesa update ?cairo? chain)

T.M.I.: Mathematia-4.x, with a few un-upgrades of minor distro files, still works well with the latest Xorg - if you know how ;)
