### ISSUE TITLE
gtest pkg-config file contains wrong include path

### ISSUE THREAD

**Issue by AtnNn** [NixOS/nixpkgs#100834]
**Describe the bug**

The `includedir` in `gtest.pc` contains the store path twice:

```
includedir=/nix/store/0kcdjakdp3mfvgvvzls5si34x0rz6z8k-gtest-1.10.0-dev//nix/store/0kcdjakdp3mfvgvvzls5si34x0rz6z8k-gtest-1.10.0-dev/include
```

**To Reproduce**

```
$ cat $(nix-build --expr 'with import (builtins.fetchTarball "https://github.com/nixos/nixpkgs/archive/24c9b05ac53e422f1af81a156f1fd58499eb27fb.tar.gz") {}; gtest.dev')/lib/pkgconfig/gtest.pc
prefix=${pcfiledir}/../..
libdir=${prefix}//nix/store/vbfv5wqhizxlqpsm3p07xjh7fpl371i1-gtest-1.10.0/lib
includedir=/nix/store/0kcdjakdp3mfvgvvzls5si34x0rz6z8k-gtest-1.10.0-dev//nix/store/0kcdjakdp3mfvgvvzls5si34x0rz6z8k-gtest-1.10.0-dev/include

Name: gtest
Description: GoogleTest (without main() function)
Version: 1.10.0
URL: https://github.com/google/googletest
Libs: -L${libdir} -lgtest -lpthread
Cflags: -I${includedir} -DGTEST_HAS_PTHREAD=1 -lpthread
```

**Notify maintainers**

@Zoomulator

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.116, NixOS, 19.09.2520.289466dd6a1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`

**Comment by bhipple** [comment]
Occasionally we have issues with pkg-config files and patching.  @danieldk implemented the start of a validatePkgConfig hook in https://github.com/NixOS/nixpkgs/pull/87866.  I'm not sure if it'd catch this particular error, but it'd be great to add and enhance it so we have automation preventing regressions like this in the future.

**Comment by jtojnar** [comment]
This should be fixed in the next release: https://github.com/google/googletest/commit/5126ff48d9ac54828d1947d1423a5ef2a8efee3b#diff-6260d2d82b8af2fa0fbed0abf2b861acd51e17a71d3e1ee58f4e3bb4b5890458

In the meanwhile, we should apply that as patches.

**Comment by AtnNn** [comment]
Thanks! I've opened https://github.com/NixOS/nixpkgs/pull/100873

I've also tried adding @danieldk's `validatePkgConfig` to the `nativeBuildInputs` but I got this error:

```
/nix/store/qjjipl9hpqppxbflirsykmhysq2kgx7j-validate-pkg-config/nix-support/setup-hook: line 16: [: -eq: unary operator expected
```
