### ISSUE TITLE
CMake not working with experimental `nix develop` command

### ISSUE THREAD

**Issue by AtnNn** [NixOS/nixpkgs#100829]
**Describe the bug**

Within `nix develop`, `buildPhase` uses `make` instead of `cmake`:

```
$ nix build -f .

  CMake Error at CMakeLists.txt:1 (message):
    used CMake

$ nix develop --build -f .

Makefile:1: *** used Make.  Stop.
```

**To Reproduce**

```
==> default.nix <==
with import (builtins.fetchTarball "https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz") {};

stdenv.mkDerivation {
  name = "nix-develop-cmake-test";
  buildInputs = [ cmake ];
  src = ./.;
}

==> Makefile <==
$(error used Make)

==> CMakeLists.txt <==
message(FATAL_ERROR "used CMake")
```

**Expected behavior**

`buildPhase` uses `cmake` within `nix develop`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.116, NixOS, 19.09.2520.289466dd6a1 (Loris)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(atnnn): `"home-manager"`
 - channels(root): `"nixos-19.09.2520.289466dd6a1, nixos-unstable-21.03pre243690.441a7da8080"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by knedlsepp** [comment]
Have you tried putting CMake into `nativeBuildInputs`.

**Comment by Artturin** [comment]
`cmakeConfigurePhase` has to be run before building
