### ISSUE TITLE
nix-env -i couchdb fails

### ISSUE THREAD

**Issue by tin6150** [NixOS/nixpkgs#10084]
nix-env -i couchdb fails to install.  

when compiling from source, defining
    CFLAGS="-D _DEFAULT_SOURCE" 
before running ./configure solves the problem.  

background info:

nix-env -i couchdb 
ends with the following error:

make[3]: Leaving directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couch_replicator'
Making all in couchdb
make[3]: Entering directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couchdb'
building all-recursive
Making all in priv
make[4]: Entering directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couchdb/priv'
building all
make  all-am
make[5]: Entering directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couchdb/priv'
building icu_driver/.dirstamp
building icu_driver/.deps/.dirstamp
building icu_driver/couch_icu_driver_la-couch_icu_driver.lo
/nix/store/r5sxfcwq9324xvcd1z312kb9kkddqvld-bash-4.3-p30/bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/snappy/google-snappy  -I/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/include  -I/nix/store/9z0f7jsw0cvkkf1v6wjgpjadwk3kizks-erlang-16B03-1/lib/erlang/usr/include -D_XOPEN_SOURCE  -I/opt/local/include -I/opt/local/include/js -I/usr/local/include -I/usr/local/include/js -I/usr/include -I/usr/include/js   -O2 -g -O2 -c -o icu_driver/couch_icu_driver_la-couch_icu_driver.lo `test -f 'icu_driver/couch_icu_driver.c' || echo './'`icu_driver/couch_icu_driver.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/snappy/google-snappy -I/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/include -I/nix/store/9z0f7jsw0cvkkf1v6wjgpjadwk3kizks-erlang-16B03-1/lib/erlang/usr/include -D_XOPEN_SOURCE -I/opt/local/include -I/opt/local/include/js -I/usr/local/include -I/usr/local/include/js -I/usr/include -I/usr/include/js -O2 -g -O2 -c icu_driver/couch_icu_driver.c  -fPIC -DPIC -o icu_driver/.libs/couch_icu_driver_la-couch_icu_driver.o
icu_driver/couch_icu_driver.c:171:9: warning: initialization from incompatible pointer type [enabled by default]
         couch_drv_control,  /* F_PTR control, port_command callback */
         ^
icu_driver/couch_icu_driver.c:171:9: warning: (near initialization for 'couch_driver_entry.control') [enabled by default]
building couch_icu_driver.la
/nix/store/r5sxfcwq9324xvcd1z312kb9kkddqvld-bash-4.3-p30/bin/bash ../../../libtool --tag=CC   --mode=link gcc  -O2 -g -O2 -module -avoid-version  -L/opt/local/lib -L/usr/local/lib  -o couch_icu_driver.la -rpath /nix/store/g8bf3xf9hrf546c6hrk8mmm7ggbwanfs-couchdb-1.6.1/lib/couchdb/erlang/lib/couch-1.6.1/priv/lib icu_driver/couch_icu_driver_la-couch_icu_driver.lo -L/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/lib -licui18n -licuuc -licudata   -L/opt/local/lib -L/usr/local/lib  -lcrypt
libtool: link: gcc -shared  -fPIC -DPIC  icu_driver/.libs/couch_icu_driver_la-couch_icu_driver.o   -L/opt/local/lib -L/usr/local/lib -L/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/lib -licui18n -licuuc -licudata -lcrypt  -O2 -O2   -Wl,-soname -Wl,couch_icu_driver.so -o .libs/couch_icu_driver.so
libtool: link: ( cd ".libs" && rm -f "couch_icu_driver.la" && ln -s "../couch_icu_driver.la" "couch_icu_driver.la" )
building couch_ejson_compare/.dirstamp
building couch_ejson_compare/.deps/.dirstamp
building couch_ejson_compare/couch_ejson_compare_la-couch_ejson_compare.lo
/nix/store/r5sxfcwq9324xvcd1z312kb9kkddqvld-bash-4.3-p30/bin/bash ../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/snappy/google-snappy  -D_BSD_SOURCE -I/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/include  -I/nix/store/9z0f7jsw0cvkkf1v6wjgpjadwk3kizks-erlang-16B03-1/lib/erlang/usr/include -D_XOPEN_SOURCE  -I/opt/local/include -I/opt/local/include/js -I/usr/local/include -I/usr/local/include/js -I/usr/include -I/usr/include/js   -O2 -g -O2 -c -o couch_ejson_compare/couch_ejson_compare_la-couch_ejson_compare.lo `test -f 'couch_ejson_compare/couch_ejson_compare.c' || echo './'`couch_ejson_compare/couch_ejson_compare.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/snappy/google-snappy -D_BSD_SOURCE -I/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/include -I/nix/store/9z0f7jsw0cvkkf1v6wjgpjadwk3kizks-erlang-16B03-1/lib/erlang/usr/include -D_XOPEN_SOURCE -I/opt/local/include -I/opt/local/include/js -I/usr/local/include -I/usr/local/include/js -I/usr/include -I/usr/include/js -O2 -g -O2 -c couch_ejson_compare/couch_ejson_compare.c  -fPIC -DPIC -o couch_ejson_compare/.libs/couch_ejson_compare_la-couch_ejson_compare.o
In file included from /nix/store/la5imi1602jxhpds9675n2n2d0683lbq-glibc-2.20/include/stdio.h:27:0,
                 from couch_ejson_compare/couch_ejson_compare.c:15:
/nix/store/la5imi1602jxhpds9675n2n2d0683lbq-glibc-2.20/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
building couch_ejson_compare.la
/nix/store/r5sxfcwq9324xvcd1z312kb9kkddqvld-bash-4.3-p30/bin/bash ../../../libtool --tag=CC   --mode=link gcc  -O2 -g -O2 -module -avoid-version  -L/opt/local/lib -L/usr/local/lib  -o couch_ejson_compare.la -rpath /nix/store/g8bf3xf9hrf546c6hrk8mmm7ggbwanfs-couchdb-1.6.1/lib/couchdb/erlang/lib/couch-1.6.1/priv/lib couch_ejson_compare/couch_ejson_compare_la-couch_ejson_compare.lo -L/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/lib -licui18n -licuuc -licudata   -L/opt/local/lib -L/usr/local/lib  -lcrypt
libtool: link: gcc -shared  -fPIC -DPIC  couch_ejson_compare/.libs/couch_ejson_compare_la-couch_ejson_compare.o   -L/opt/local/lib -L/usr/local/lib -L/nix/store/s4syvddcsw9vly934w88rcq0k8ivas33-icu4c-53.1/lib -licui18n -licuuc -licudata -lcrypt  -O2 -O2   -Wl,-soname -Wl,couch_ejson_compare.so -o .libs/couch_ejson_compare.so
libtool: link: ( cd ".libs" && rm -f "couch_ejson_compare.la" && ln -s "../couch_ejson_compare.la" "couch_ejson_compare.la" )
building couchspawnkillable
cp spawnkillable/couchspawnkillable.sh couchspawnkillable
chmod +x couchspawnkillable
building couch_js/.dirstamp
building couch_js/.deps/.dirstamp
building couch_js/couchjs-http.o
gcc -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/snappy/google-snappy   -D_XOPEN_SOURCE  -I/opt/local/include -I/opt/local/include/js -I/usr/local/include -I/usr/local/include/js -I/usr/include -I/usr/include/js  -g -Wall -Werror -D_BSD_SOURCE -I/nix/store/b2x79vbr7z6bq42a7j95ylx6v7dr1ybs-curl-7.42.1/include -DXP_UNIX -I/nix/store/m0qi5q1rim3s3grn9vj6j0wrjwx0dmn6-spidermonkey-185-1.0.0/include/js -I/nix/store/kj8m3rvgz7x35f6j7rxs122cckq731k3-nspr-4.10.8/include/nspr  -O2 -g -O2 -c -o couch_js/couchjs-http.o `test -f 'couch_js/http.c' || echo './'`couch_js/http.c
In file included from /nix/store/la5imi1602jxhpds9675n2n2d0683lbq-glibc-2.20/include/stdio.h:27:0,
                 from couch_js/http.c:13:
/nix/store/la5imi1602jxhpds9675n2n2d0683lbq-glibc-2.20/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1: all warnings being treated as errors
make[5]: *** [couch_js/couchjs-http.o] Error 1
make[5]: Leaving directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couchdb/priv'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couchdb/priv'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src/couchdb'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/nix-build-couchdb-1.6.1.drv-0/apache-couchdb-1.6.1'
make: *** [all] Error 2
builder for ‘/nix/store/59m01jkkhisp8nqv3l7fkw74g0lxl39d-couchdb-1.6.1.drv’ failed with exit code 2
error: build of ‘/nix/store/59m01jkkhisp8nqv3l7fkw74g0lxl39d-couchdb-1.6.1.drv’ failed

nixos-version 
14.12.884.4137703 (Caterpillar)

downloaded source from apache.org
successfully compiled couchdb as:

export CFLAGS="-D _DEFAULT_SOURCE"
./configure --with-js-lib=/nix/store/m0qi5q1rim3s3grn9vj6j0wrjwx0dmn6-spidermonkey-185-1.0.0/lib \
        --with-js-include=/nix/store/m0qi5q1rim3s3grn9vj6j0wrjwx0dmn6-spidermonkey-185-1.0.0/include/js 
make

**Comment by vcunat** [comment]
This was fixed on master earlier and thus works in 15.09. Now I picked the fix to 14.12 as well.

**Comment by tin6150** [comment]
Thanks!  works like a charm now :)
