### ISSUE TITLE
Literate Does Not Compile

### ISSUE THREAD

**Issue by enderger** [NixOS/nixpkgs#100902]
**Describe the bug**
The Literate package does not compile, as it is out of date

**To Reproduce**
1. Try to install the Literate package on NixOS unstable (or maybe even 20.09)

**Expected behavior**
The package to install properly

**Additional context**
The issue is patched upstream

**Notify maintainers**
@ThomasMader
@OmnipotentEntity 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/m52v606f8ni9gs7zl20bjqrbz09wx979-nix-info
copying path '/nix/store/m52v606f8ni9gs7zl20bjqrbz09wx979-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.65, NixOS, 21.03pre243690.441a7da8080 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre243690.441a7da8080"`
 - channels(enderger): `"home-manager, nixos-20.03.3122.ff6fda61600, nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/home/enderger/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: Literate
# a list of nixos modules affected by the problem
module:
```

**Comment by mweinelt** [comment]
@enderger Can you test #100903 please?

**Comment by enderger** [comment]
I will when I have time, I'm currently working on getting backups running on my computer.
