### ISSUE TITLE
bash: cannot create directory '/nix/store/...-bash-4.3-p42': File exist

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#10098]
I'm on Darwin (OSX 10.10.5) with stdenvDarwinPure and using sandboxed (chroot = true) builds. Someone mentioned about "multiple-outputs" causing similar errors elsewhere?

How should I debug or provide more info?

```
mkdir: cannot create directory '/nix/store/3yk5qfadx9zbk58gfrk0i1n973dsxy40-bash-4.3-p42': File exists
builder for ‘/nix/store/1sfhavv67z00lfm80daaz5q2rpzxrz65-bash-4.3-p42.drv’ failed with exit code 1
error: build of ‘/nix/store/1sfhavv67z00lfm80daaz5q2rpzxrz65-bash-4.3-p42.drv’ failed
```

**Comment by datakurre** [comment]
It seems that just garbage collecting and re-building a few times eventually got me past of this error (without changing anything in nixpkgs). Dirty feeling, but I close this for now.

**Comment by datakurre** [comment]
Wrong negative. Still seeing this.

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by edolstra** [comment]
I know nothing about stdenvDarwinPure or sandboxing. cc @copumpkin

**Comment by edolstra** [comment]
This may be a dupe of https://github.com/NixOS/nix/issues/639.

**Comment by domenkozar** [comment]
@datakurre are you using Nix 1.10?

**Comment by datakurre** [comment]
@domenkozar Yes.

**Comment by copumpkin** [comment]
I don't have time to look at this right now, but @pikajude knows as much as I do about it and might be able to take a look. Sorry!

**Comment by datakurre** [comment]
Just in case, I do have 1.10 with reverted https://github.com/NixOS/nix/commit/6f0c6e20e03bc82fcf0d2198cf81fa2cf25c2f6c as I was instructed in https://github.com/copumpkin/nixpkgs/issues/77 to fix some issue with darwin sandboxed builds.

**Comment by datakurre** [comment]
@pikajude said

```
<pikajude> datakurre: it's a nix bug that's exposed by darwin
<pikajude> you have to nix-store --realise /path/to/derivation.drv --option build-use-chroot false
```

Maybe I close that again now that I can get forward.

**Comment by domenkozar** [comment]
Let's keep it open if it's a bug, we'll probably get duplicates.

**Comment by wkennington** [comment]
There is a known bug in Linux for multiple derivations producing the same
error for what it's worth.

**Comment by dalaing** [comment]
This is still an issue for me, even while using `nix-store --realise` and garbage collecting over and over.

I had to blow away all of nix and rebuild everything once I hit this, and then it re-appeared as soon as I built my first haskell project.

**Comment by Profpatsch** [comment]
(triager) status?

**Comment by pikajude** [comment]
Still affects me on both NixOS and OSX.

**Comment by Profpatsch** [comment]
This seems to be a nix issue, so closing in favor of the mentioned https://github.com/NixOS/nix/issues/639
