### ISSUE TITLE
claws-mail-3.12.0: Won't build against webkitgtk2, missing icu

### ISSUE THREAD

**Issue by khumba** [NixOS/nixpkgs#10099]
I'd like to ask for some help getting Claws 3.12.0 to build.  I've simply updated the version and sha256 in the 3.11.1 expression.  I'm having trouble with the `fancy` Webkit plugin, which gives the error below.  ICU isn't a dependency of webkitgtk2 directly, but I see it's a propagatedBuildInput of harfbuzz, which is a regular buildInput of webkitgtk2.  Claws doesn't mention ICU (or Harfbuzz) directly anywhere, so adding ICU to Claws's buildInputs seems wrong, although it does fix the failure.  I took a look through the source changes between 3.11.1 and 3.12.0 and didn't see anything change w.r.t. Webkit.

Working on top of 52a8811.

    libtool: link: gcc -shared -fPIC -DPIC .libs/fancy_la-fancy_viewer.o .libs/fancy_la-fancy_prefs.o
    -Wl,-rpath -Wl,/nix/store/iq8hsy7xihwb896azgagv8fx4pa62sin-webkitgtk-2.4.9/lib -Wl,-rpath
    -Wl,/nix/store/yj2jqybixgj1hgds88fl6l6hc2gafldv-enchant-1.6.0/lib -Wl,-rpath
    -Wl,/nix/store/bqsp7ydc91rrxq2lq8d1nk6wv1vkb3vh-harfbuzz-1.0.2/lib -Wl,-rpath
    -Wl,/nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib -Wl,-rpath
    -Wl,/nix/store/nl9hws4hhbqpm71j0vgy2q8327rpp1lh-orc-0.4.23/lib -Wl,-rpath
    -Wl,/nix/store/k0zya422r44ibvbbzp4yxx7jywmgc5q1-gstreamer-1.4.5/lib -Wl,-rpath
    -Wl,/nix/store/gw94xbfpgn2lza6fac06mjm35m4xkyqc-libjpeg-turbo-1.4.1/lib -Wl,-rpath
    -Wl,/nix/store/p7p992v2y974cwkdsyj86hk236yx83nk-libsecret-0.18/lib -Wl,-rpath
    -Wl,/nix/store/m71b79ybh5y43v2b19ixlfqhwkrn5ccf-libgcrypt-1.6.4/lib -Wl,-rpath
    -Wl,/nix/store/bdy5cgqhsqkc2djxbzs7dmqymnzspkvp-libgpg-error-1.20/lib -Wl,-rpath
    -Wl,/nix/store/jgi3r2l6vf9jl6v32jyhc8b0lx4x3xkl-libxslt-1.1.28/lib -Wl,-rpath
    -Wl,/nix/store/b1xcryn2d44wsx9c1iba3swvd9jrrqrr-libwebp-0.4.3/lib -Wl,-rpath
    -Wl,/nix/store/6k2pkayyw3bvq6cklmca3mr0xnrfdwrx-libXcomposite-0.4.4/lib -Wl,-rpath
    -Wl,/nix/store/ys0z6fr2adyvgap4mdyalga8wzv2kw25-libXt-1.1.5/lib -Wl,-rpath
    -Wl,/nix/store/3mkn905m2sakzw4ghhw5vpsiwsmqc6ab-libSM-1.2.2/lib -Wl,-rpath
    -Wl,/nix/store/fjzgp80g9yqhiyvwgg8pwfkv1gbw5l2v-util-linux-2.26.2/lib -Wl,-rpath
    -Wl,/nix/store/qkmvx19fnv2ssiz84xhlyg0digbnb0bd-libICE-1.0.9/lib -Wl,-rpath
    -Wl,/nix/store/7ycg7njzr8w4fnxhb10pdy89vqyymprz-libsoup-2.50.0/lib -Wl,-rpath
    -Wl,/nix/store/gmzy89k6483nzkij24s5rapbcvr03qg3-libxml2-2.9.2/lib -Wl,-rpath
    -Wl,/nix/store/8sizyvshnfd81bxn40j54xx3vnzcdhk8-sqlite-3.8.11.1/lib -Wl,-rpath
    -Wl,/nix/store/zil4x7cbkydbpblrl086ma2iifln9p2s-curl-7.44.0/lib -Wl,-rpath
    -Wl,/nix/store/4vdbdbqy3k4qppqya0pnxfhpjl2an52g-libssh2-1.6.0/lib -Wl,-rpath
    -Wl,/nix/store/7d6aiga0mv281wc4h603mnyl08g3kvhv-gtk+-2.24.28/lib -Wl,-rpath
    -Wl,/nix/store/vrk5cs8jwk5gwq2l3papam4zrapj6ar4-pango-1.36.8/lib -Wl,-rpath
    -Wl,/nix/store/sryjy5nd1rq6lpr4bjip7bngbcyika16-harfbuzz-1.0.2/lib -Wl,-rpath
    -Wl,/nix/store/vv11j36is2hb92d3i0hfwy8j7q0gfgmv-graphite2-1.2.4/lib -Wl,-rpath
    -Wl,/nix/store/gamgjqmjypnjw3az9756sidaq604n91h-atk-2.16.0/lib -Wl,-rpath
    -Wl,/nix/store/i86vhxvh205vx8in58hc3f1qpgygliwd-cairo-1.14.2/lib -Wl,-rpath
    -Wl,/nix/store/kaysn4v5ldp6b60hx8hpfin45nfcp0gf-pixman-0.32.6/lib -Wl,-rpath
    -Wl,/nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib -Wl,-rpath
    -Wl,/nix/store/2khzsnn9raz2hbs8nmyv54azql9g35sk-wayland-1.8.1/lib -Wl,-rpath
    -Wl,/nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib -Wl,-rpath
    -Wl,/nix/store/vnyfkiwwhhxl907zw756bv4r0mx86kn9-libXrender-0.9.9/lib -Wl,-rpath
    -Wl,/nix/store/xvl6l5375332v0m8h1idh25i2naaymh8-libXdamage-1.1.4/lib -Wl,-rpath
    -Wl,/nix/store/mmr5583n34bsd0r3yk0aipdpvky6y8fr-libXfixes-5.0.1/lib -Wl,-rpath
    -Wl,/nix/store/ikl6fjq7ff74gi9rdrzjli1z1sj2h3py-libX11-1.6.3/lib -Wl,-rpath
    -Wl,/nix/store/mjv4rh16aabrxj7iwi0ilrxy5nzlh6n5-libxshmfence-1.2/lib -Wl,-rpath
    -Wl,/nix/store/2hf53fldypaiza6bka8dzlvagp35dwvm-libXxf86vm-1.1.4/lib -Wl,-rpath
    -Wl,/nix/store/y9kmwci3wlbf7qwhr2ic5jpqjh551700-libXext-1.3.3/lib -Wl,-rpath
    -Wl,/nix/store/9jydhs4d8k5bm5r6jfq7y1k3szfj9iwi-libXau-1.0.8/lib -Wl,-rpath
    -Wl,/nix/store/l90w8wx8rch5z7v67v73dmv1fx88h78i-libXdmcp-1.1.2/lib -Wl,-rpath
    -Wl,/nix/store/fgknw6f536ydhc1b8lnss4d5pijnc2ax-libdrm-2.4.64/lib -Wl,-rpath
    -Wl,/nix/store/zwkgm6zsb3di7p73n867qf0djm3dnszk-gdk-pixbuf-2.31.6/lib -Wl,-rpath
    -Wl,/nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib -Wl,-rpath
    -Wl,/nix/store/jg26n871y4psj1rg6h7bzk4fy68qmycn-libffi-3.2.1/lib/../lib64 -Wl,-rpath
    -Wl,/nix/store/lryba0frnj96n8ydc6wmn5ck77z714yg-fontconfig-2.11.1/lib -Wl,-rpath
    -Wl,/nix/store/a7lmmb7r9nbfdyj512lz3ds91jjwn87m-expat-2.1.0/lib -Wl,-rpath
    -Wl,/nix/store/sqca0hqn801cn0n8ilhc9m5zv3n9d4cw-freetype-2.5.4/lib -Wl,-rpath
    -Wl,/nix/store/7vib53pq0w141ngswrb5blm86gk6sfck-libpng-apng-1.6.18/lib -Wl,-rpath
    -Wl,/nix/store/3flgl5024da9zca0gvfpar76jciw5w67-libetpan-1.6/lib -Wl,-rpath
    -Wl,/nix/store/81gmdmvsi9a3iyhk4hnxamm8hg8d82sx-gcc-4.9.3/lib/../lib64 -Wl,-rpath
    -Wl,/nix/store/iq8hsy7xihwb896azgagv8fx4pa62sin-webkitgtk-2.4.9/lib -Wl,-rpath
    -Wl,/nix/store/yj2jqybixgj1hgds88fl6l6hc2gafldv-enchant-1.6.0/lib -Wl,-rpath
    -Wl,/nix/store/bqsp7ydc91rrxq2lq8d1nk6wv1vkb3vh-harfbuzz-1.0.2/lib -Wl,-rpath
    -Wl,/nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib -Wl,-rpath
    -Wl,/nix/store/nl9hws4hhbqpm71j0vgy2q8327rpp1lh-orc-0.4.23/lib -Wl,-rpath
    -Wl,/nix/store/k0zya422r44ibvbbzp4yxx7jywmgc5q1-gstreamer-1.4.5/lib -Wl,-rpath
    -Wl,/nix/store/gw94xbfpgn2lza6fac06mjm35m4xkyqc-libjpeg-turbo-1.4.1/lib -Wl,-rpath
    -Wl,/nix/store/p7p992v2y974cwkdsyj86hk236yx83nk-libsecret-0.18/lib -Wl,-rpath
    -Wl,/nix/store/m71b79ybh5y43v2b19ixlfqhwkrn5ccf-libgcrypt-1.6.4/lib -Wl,-rpath
    -Wl,/nix/store/bdy5cgqhsqkc2djxbzs7dmqymnzspkvp-libgpg-error-1.20/lib -Wl,-rpath
    -Wl,/nix/store/jgi3r2l6vf9jl6v32jyhc8b0lx4x3xkl-libxslt-1.1.28/lib -Wl,-rpath
    -Wl,/nix/store/b1xcryn2d44wsx9c1iba3swvd9jrrqrr-libwebp-0.4.3/lib -Wl,-rpath
    -Wl,/nix/store/6k2pkayyw3bvq6cklmca3mr0xnrfdwrx-libXcomposite-0.4.4/lib -Wl,-rpath
    -Wl,/nix/store/ys0z6fr2adyvgap4mdyalga8wzv2kw25-libXt-1.1.5/lib -Wl,-rpath
    -Wl,/nix/store/3mkn905m2sakzw4ghhw5vpsiwsmqc6ab-libSM-1.2.2/lib -Wl,-rpath
    -Wl,/nix/store/fjzgp80g9yqhiyvwgg8pwfkv1gbw5l2v-util-linux-2.26.2/lib -Wl,-rpath
    -Wl,/nix/store/qkmvx19fnv2ssiz84xhlyg0digbnb0bd-libICE-1.0.9/lib -Wl,-rpath
    -Wl,/nix/store/7ycg7njzr8w4fnxhb10pdy89vqyymprz-libsoup-2.50.0/lib -Wl,-rpath
    -Wl,/nix/store/gmzy89k6483nzkij24s5rapbcvr03qg3-libxml2-2.9.2/lib -Wl,-rpath
    -Wl,/nix/store/8sizyvshnfd81bxn40j54xx3vnzcdhk8-sqlite-3.8.11.1/lib -Wl,-rpath
    -Wl,/nix/store/zil4x7cbkydbpblrl086ma2iifln9p2s-curl-7.44.0/lib -Wl,-rpath
    -Wl,/nix/store/4vdbdbqy3k4qppqya0pnxfhpjl2an52g-libssh2-1.6.0/lib -Wl,-rpath
    -Wl,/nix/store/7d6aiga0mv281wc4h603mnyl08g3kvhv-gtk+-2.24.28/lib -Wl,-rpath
    -Wl,/nix/store/vrk5cs8jwk5gwq2l3papam4zrapj6ar4-pango-1.36.8/lib -Wl,-rpath
    -Wl,/nix/store/sryjy5nd1rq6lpr4bjip7bngbcyika16-harfbuzz-1.0.2/lib -Wl,-rpath
    -Wl,/nix/store/vv11j36is2hb92d3i0hfwy8j7q0gfgmv-graphite2-1.2.4/lib -Wl,-rpath
    -Wl,/nix/store/gamgjqmjypnjw3az9756sidaq604n91h-atk-2.16.0/lib -Wl,-rpath
    -Wl,/nix/store/i86vhxvh205vx8in58hc3f1qpgygliwd-cairo-1.14.2/lib -Wl,-rpath
    -Wl,/nix/store/kaysn4v5ldp6b60hx8hpfin45nfcp0gf-pixman-0.32.6/lib -Wl,-rpath
    -Wl,/nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib -Wl,-rpath
    -Wl,/nix/store/2khzsnn9raz2hbs8nmyv54azql9g35sk-wayland-1.8.1/lib -Wl,-rpath
    -Wl,/nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib -Wl,-rpath
    -Wl,/nix/store/vnyfkiwwhhxl907zw756bv4r0mx86kn9-libXrender-0.9.9/lib -Wl,-rpath
    -Wl,/nix/store/xvl6l5375332v0m8h1idh25i2naaymh8-libXdamage-1.1.4/lib -Wl,-rpath
    -Wl,/nix/store/mmr5583n34bsd0r3yk0aipdpvky6y8fr-libXfixes-5.0.1/lib -Wl,-rpath
    -Wl,/nix/store/ikl6fjq7ff74gi9rdrzjli1z1sj2h3py-libX11-1.6.3/lib -Wl,-rpath
    -Wl,/nix/store/mjv4rh16aabrxj7iwi0ilrxy5nzlh6n5-libxshmfence-1.2/lib -Wl,-rpath
    -Wl,/nix/store/2hf53fldypaiza6bka8dzlvagp35dwvm-libXxf86vm-1.1.4/lib -Wl,-rpath
    -Wl,/nix/store/y9kmwci3wlbf7qwhr2ic5jpqjh551700-libXext-1.3.3/lib -Wl,-rpath
    -Wl,/nix/store/9jydhs4d8k5bm5r6jfq7y1k3szfj9iwi-libXau-1.0.8/lib -Wl,-rpath
    -Wl,/nix/store/l90w8wx8rch5z7v67v73dmv1fx88h78i-libXdmcp-1.1.2/lib -Wl,-rpath
    -Wl,/nix/store/fgknw6f536ydhc1b8lnss4d5pijnc2ax-libdrm-2.4.64/lib -Wl,-rpath
    -Wl,/nix/store/zwkgm6zsb3di7p73n867qf0djm3dnszk-gdk-pixbuf-2.31.6/lib -Wl,-rpath
    -Wl,/nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib -Wl,-rpath
    -Wl,/nix/store/jg26n871y4psj1rg6h7bzk4fy68qmycn-libffi-3.2.1/lib/../lib64 -Wl,-rpath
    -Wl,/nix/store/lryba0frnj96n8ydc6wmn5ck77z714yg-fontconfig-2.11.1/lib -Wl,-rpath
    -Wl,/nix/store/a7lmmb7r9nbfdyj512lz3ds91jjwn87m-expat-2.1.0/lib -Wl,-rpath
    -Wl,/nix/store/sqca0hqn801cn0n8ilhc9m5zv3n9d4cw-freetype-2.5.4/lib -Wl,-rpath
    -Wl,/nix/store/7vib53pq0w141ngswrb5blm86gk6sfck-libpng-apng-1.6.18/lib -Wl,-rpath
    -Wl,/nix/store/3flgl5024da9zca0gvfpar76jciw5w67-libetpan-1.6/lib -Wl,-rpath
    -Wl,/nix/store/81gmdmvsi9a3iyhk4hnxamm8hg8d82sx-gcc-4.9.3/lib/../lib64
    -L/nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib
    -L/nix/store/7d6aiga0mv281wc4h603mnyl08g3kvhv-gtk+-2.24.28/lib
    -L/nix/store/i86vhxvh205vx8in58hc3f1qpgygliwd-cairo-1.14.2/lib
    -L/nix/store/sqca0hqn801cn0n8ilhc9m5zv3n9d4cw-freetype-2.5.4/lib
    -L/nix/store/lryba0frnj96n8ydc6wmn5ck77z714yg-fontconfig-2.11.1/lib
    -L/nix/store/vrk5cs8jwk5gwq2l3papam4zrapj6ar4-pango-1.36.8/lib
    -L/nix/store/zwkgm6zsb3di7p73n867qf0djm3dnszk-gdk-pixbuf-2.31.6/lib
    -L/nix/store/gamgjqmjypnjw3az9756sidaq604n91h-atk-2.16.0/lib
    -L/nix/store/jg26n871y4psj1rg6h7bzk4fy68qmycn-libffi-3.2.1/lib/../lib64
    -L/nix/store/kaysn4v5ldp6b60hx8hpfin45nfcp0gf-pixman-0.32.6/lib
    -L/nix/store/2zmlykvqx69q5bh1l3jqyhrj2493vqdx-zlib-1.2.8/lib
    -L/nix/store/7vib53pq0w141ngswrb5blm86gk6sfck-libpng-apng-1.6.18/lib
    -L/nix/store/a7lmmb7r9nbfdyj512lz3ds91jjwn87m-expat-2.1.0/lib
    -L/nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib
    -L/nix/store/ikl6fjq7ff74gi9rdrzjli1z1sj2h3py-libX11-1.6.3/lib
    -L/nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib
    -L/nix/store/9jydhs4d8k5bm5r6jfq7y1k3szfj9iwi-libXau-1.0.8/lib
    -L/nix/store/l90w8wx8rch5z7v67v73dmv1fx88h78i-libXdmcp-1.1.2/lib
    -L/nix/store/2khzsnn9raz2hbs8nmyv54azql9g35sk-wayland-1.8.1/lib
    -L/nix/store/fgknw6f536ydhc1b8lnss4d5pijnc2ax-libdrm-2.4.64/lib
    -L/nix/store/vnyfkiwwhhxl907zw756bv4r0mx86kn9-libXrender-0.9.9/lib
    -L/nix/store/y9kmwci3wlbf7qwhr2ic5jpqjh551700-libXext-1.3.3/lib
    -L/nix/store/mmr5583n34bsd0r3yk0aipdpvky6y8fr-libXfixes-5.0.1/lib
    -L/nix/store/mjv4rh16aabrxj7iwi0ilrxy5nzlh6n5-libxshmfence-1.2/lib
    -L/nix/store/xvl6l5375332v0m8h1idh25i2naaymh8-libXdamage-1.1.4/lib
    -L/nix/store/2hf53fldypaiza6bka8dzlvagp35dwvm-libXxf86vm-1.1.4/lib
    -L/nix/store/sryjy5nd1rq6lpr4bjip7bngbcyika16-harfbuzz-1.0.2/lib
    -L/nix/store/vv11j36is2hb92d3i0hfwy8j7q0gfgmv-graphite2-1.2.4/lib
    -L/nix/store/7ycg7njzr8w4fnxhb10pdy89vqyymprz-libsoup-2.50.0/lib
    -L/nix/store/iq8hsy7xihwb896azgagv8fx4pa62sin-webkitgtk-2.4.9/lib
    /nix/store/iq8hsy7xihwb896azgagv8fx4pa62sin-webkitgtk-2.4.9/lib/libwebkitgtk-1.0.so
    -L/nix/store/yj2jqybixgj1hgds88fl6l6hc2gafldv-enchant-1.6.0/lib
    -L/nix/store/bqsp7ydc91rrxq2lq8d1nk6wv1vkb3vh-harfbuzz-1.0.2/lib
    -L/nix/store/81gmdmvsi9a3iyhk4hnxamm8hg8d82sx-gcc-4.9.3/lib/../lib64
    -L/nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib
    -L/nix/store/nl9hws4hhbqpm71j0vgy2q8327rpp1lh-orc-0.4.23/lib
    -L/nix/store/k0zya422r44ibvbbzp4yxx7jywmgc5q1-gstreamer-1.4.5/lib
    -L/nix/store/gw94xbfpgn2lza6fac06mjm35m4xkyqc-libjpeg-turbo-1.4.1/lib
    -L/nix/store/p7p992v2y974cwkdsyj86hk236yx83nk-libsecret-0.18/lib
    -L/nix/store/m71b79ybh5y43v2b19ixlfqhwkrn5ccf-libgcrypt-1.6.4/lib
    -L/nix/store/bdy5cgqhsqkc2djxbzs7dmqymnzspkvp-libgpg-error-1.20/lib
    -L/nix/store/jgi3r2l6vf9jl6v32jyhc8b0lx4x3xkl-libxslt-1.1.28/lib
    -L/nix/store/gmzy89k6483nzkij24s5rapbcvr03qg3-libxml2-2.9.2/lib
    -L/nix/store/8sizyvshnfd81bxn40j54xx3vnzcdhk8-sqlite-3.8.11.1/lib
    -L/nix/store/b1xcryn2d44wsx9c1iba3swvd9jrrqrr-libwebp-0.4.3/lib
    -L/nix/store/6k2pkayyw3bvq6cklmca3mr0xnrfdwrx-libXcomposite-0.4.4/lib
    -L/nix/store/ys0z6fr2adyvgap4mdyalga8wzv2kw25-libXt-1.1.5/lib
    -L/nix/store/fjzgp80g9yqhiyvwgg8pwfkv1gbw5l2v-util-linux-2.26.2/lib
    -L/nix/store/3mkn905m2sakzw4ghhw5vpsiwsmqc6ab-libSM-1.2.2/lib
    -L/nix/store/qkmvx19fnv2ssiz84xhlyg0digbnb0bd-libICE-1.0.9/lib
    /nix/store/yj2jqybixgj1hgds88fl6l6hc2gafldv-enchant-1.6.0/lib/libenchant.so
    /nix/store/bqsp7ydc91rrxq2lq8d1nk6wv1vkb3vh-harfbuzz-1.0.2/lib/libharfbuzz-icu.so
    /nix/store/bqsp7ydc91rrxq2lq8d1nk6wv1vkb3vh-harfbuzz-1.0.2/lib/libharfbuzz.so
    /nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib/libgstapp-1.0.so
    /nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib/libgstfft-1.0.so
    /nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib/libgstpbutils-1.0.so
    /nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib/libgstaudio-1.0.so
    /nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib/libgsttag-1.0.so
    /nix/store/9m6afgbbx5y3whnafpr4ks3im83jfxzn-gst-plugins-base-1.4.5/lib/libgstvideo-1.0.so
    /nix/store/nl9hws4hhbqpm71j0vgy2q8327rpp1lh-orc-0.4.23/lib/liborc-0.4.so
    /nix/store/k0zya422r44ibvbbzp4yxx7jywmgc5q1-gstreamer-1.4.5/lib/libgstbase-1.0.so
    /nix/store/k0zya422r44ibvbbzp4yxx7jywmgc5q1-gstreamer-1.4.5/lib/libgstreamer-1.0.so
    /nix/store/gw94xbfpgn2lza6fac06mjm35m4xkyqc-libjpeg-turbo-1.4.1/lib/libjpeg.so
    /nix/store/p7p992v2y974cwkdsyj86hk236yx83nk-libsecret-0.18/lib/libsecret-1.so
    /nix/store/m71b79ybh5y43v2b19ixlfqhwkrn5ccf-libgcrypt-1.6.4/lib/libgcrypt.so
    /nix/store/bdy5cgqhsqkc2djxbzs7dmqymnzspkvp-libgpg-error-1.20/lib/libgpg-error.so
    /nix/store/jgi3r2l6vf9jl6v32jyhc8b0lx4x3xkl-libxslt-1.1.28/lib/libxslt.so
    /nix/store/b1xcryn2d44wsx9c1iba3swvd9jrrqrr-libwebp-0.4.3/lib/libwebp.so
    /nix/store/6k2pkayyw3bvq6cklmca3mr0xnrfdwrx-libXcomposite-0.4.4/lib/libXcomposite.so
    /nix/store/ys0z6fr2adyvgap4mdyalga8wzv2kw25-libXt-1.1.5/lib/libXt.so
    /nix/store/3mkn905m2sakzw4ghhw5vpsiwsmqc6ab-libSM-1.2.2/lib/libSM.so
    /nix/store/fjzgp80g9yqhiyvwgg8pwfkv1gbw5l2v-util-linux-2.26.2/lib/libuuid.so
    /nix/store/qkmvx19fnv2ssiz84xhlyg0digbnb0bd-libICE-1.0.9/lib/libICE.so
    /nix/store/7ycg7njzr8w4fnxhb10pdy89vqyymprz-libsoup-2.50.0/lib/libsoup-2.4.so
    /nix/store/gmzy89k6483nzkij24s5rapbcvr03qg3-libxml2-2.9.2/lib/libxml2.so
    /nix/store/8sizyvshnfd81bxn40j54xx3vnzcdhk8-sqlite-3.8.11.1/lib/libsqlite3.so
    /nix/store/iq8hsy7xihwb896azgagv8fx4pa62sin-webkitgtk-2.4.9/lib/libjavascriptcoregtk-1.0.so
    -licui18n -licuuc -licudata -L/nix/store/zil4x7cbkydbpblrl086ma2iifln9p2s-curl-7.44.0/lib
    /nix/store/zil4x7cbkydbpblrl086ma2iifln9p2s-curl-7.44.0/lib/libcurl.so
    -L/nix/store/safka4lxaj306r4mzkfz4d24q35w48xf-openssl-1.0.1p/lib
    -L/nix/store/4vdbdbqy3k4qppqya0pnxfhpjl2an52g-libssh2-1.6.0/lib
    /nix/store/4vdbdbqy3k4qppqya0pnxfhpjl2an52g-libssh2-1.6.0/lib/libssh2.so
    /nix/store/7d6aiga0mv281wc4h603mnyl08g3kvhv-gtk+-2.24.28/lib/libgtk-x11-2.0.so
    /nix/store/7d6aiga0mv281wc4h603mnyl08g3kvhv-gtk+-2.24.28/lib/libgdk-x11-2.0.so
    /nix/store/vrk5cs8jwk5gwq2l3papam4zrapj6ar4-pango-1.36.8/lib/libpangocairo-1.0.so
    /nix/store/sryjy5nd1rq6lpr4bjip7bngbcyika16-harfbuzz-1.0.2/lib/libharfbuzz.so
    /nix/store/vv11j36is2hb92d3i0hfwy8j7q0gfgmv-graphite2-1.2.4/lib/libgraphite2.so
    /nix/store/gamgjqmjypnjw3az9756sidaq604n91h-atk-2.16.0/lib/libatk-1.0.so
    /nix/store/i86vhxvh205vx8in58hc3f1qpgygliwd-cairo-1.14.2/lib/libcairo.so
    /nix/store/kaysn4v5ldp6b60hx8hpfin45nfcp0gf-pixman-0.32.6/lib/libpixman-1.so
    /nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib/libEGL.so
    /nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib/libgbm.so
    /nix/store/2khzsnn9raz2hbs8nmyv54azql9g35sk-wayland-1.8.1/lib/libwayland-client.so
    /nix/store/2khzsnn9raz2hbs8nmyv54azql9g35sk-wayland-1.8.1/lib/libwayland-server.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-shm.so
    /nix/store/vnyfkiwwhhxl907zw756bv4r0mx86kn9-libXrender-0.9.9/lib/libXrender.so
    /nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib/libGL.so
    /nix/store/zgypypkgz90hj2irr6fgbk5w5iwj1frf-mesa-noglu-10.6.7/lib/libglapi.so
    /nix/store/xvl6l5375332v0m8h1idh25i2naaymh8-libXdamage-1.1.4/lib/libXdamage.so
    /nix/store/mmr5583n34bsd0r3yk0aipdpvky6y8fr-libXfixes-5.0.1/lib/libXfixes.so
    /nix/store/ikl6fjq7ff74gi9rdrzjli1z1sj2h3py-libX11-1.6.3/lib/libX11-xcb.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-glx.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-dri2.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-dri3.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-present.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-randr.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-xfixes.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-render.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-shape.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb-sync.so
    /nix/store/mjv4rh16aabrxj7iwi0ilrxy5nzlh6n5-libxshmfence-1.2/lib/libxshmfence.so
    /nix/store/2hf53fldypaiza6bka8dzlvagp35dwvm-libXxf86vm-1.1.4/lib/libXxf86vm.so
    /nix/store/y9kmwci3wlbf7qwhr2ic5jpqjh551700-libXext-1.3.3/lib/libXext.so
    /nix/store/ikl6fjq7ff74gi9rdrzjli1z1sj2h3py-libX11-1.6.3/lib/libX11.so
    /nix/store/015w7xl6qc4vlkzlb5izz7h1f2q27f23-libxcb-1.11/lib/libxcb.so
    /nix/store/9jydhs4d8k5bm5r6jfq7y1k3szfj9iwi-libXau-1.0.8/lib/libXau.so
    /nix/store/l90w8wx8rch5z7v67v73dmv1fx88h78i-libXdmcp-1.1.2/lib/libXdmcp.so
    /nix/store/fgknw6f536ydhc1b8lnss4d5pijnc2ax-libdrm-2.4.64/lib/libdrm.so -lrt
    /nix/store/zwkgm6zsb3di7p73n867qf0djm3dnszk-gdk-pixbuf-2.31.6/lib/libgdk_pixbuf-2.0.so
    /nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib/libgio-2.0.so -lresolv
    /nix/store/vrk5cs8jwk5gwq2l3papam4zrapj6ar4-pango-1.36.8/lib/libpangoft2-1.0.so
    /nix/store/vrk5cs8jwk5gwq2l3papam4zrapj6ar4-pango-1.36.8/lib/libpango-1.0.so
    /nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib/libgmodule-2.0.so -ldl
    /nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib/libgthread-2.0.so
    /nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib/libgobject-2.0.so
    /nix/store/jg26n871y4psj1rg6h7bzk4fy68qmycn-libffi-3.2.1/lib/../lib64/libffi.so
    /nix/store/byaj2i4nd3dxzhbaliaag4rl27z0133d-glib-2.44.1/lib/libglib-2.0.so -lpthread
    /nix/store/lryba0frnj96n8ydc6wmn5ck77z714yg-fontconfig-2.11.1/lib/libfontconfig.so
    /nix/store/a7lmmb7r9nbfdyj512lz3ds91jjwn87m-expat-2.1.0/lib/libexpat.so
    /nix/store/sqca0hqn801cn0n8ilhc9m5zv3n9d4cw-freetype-2.5.4/lib/libfreetype.so -lbz2
    /nix/store/7vib53pq0w141ngswrb5blm86gk6sfck-libpng-apng-1.6.18/lib/libpng16.so -lz -lm
    -L/nix/store/3flgl5024da9zca0gvfpar76jciw5w67-libetpan-1.6/lib
    /nix/store/3flgl5024da9zca0gvfpar76jciw5w67-libetpan-1.6/lib/libetpan.so
    /nix/store/81gmdmvsi9a3iyhk4hnxamm8hg8d82sx-gcc-4.9.3/lib/../lib64/libstdc++.so -lssl -lcrypto -O2
    -pthread -pthread -Wl,-soname -Wl,fancy.so -o .libs/fancy.so

    /nix/store/v7h3j43vx0dz5ahhkxg5z50by2iqc6k1-binutils-2.23.1/bin/ld: cannot find -licui18n
    /nix/store/v7h3j43vx0dz5ahhkxg5z50by2iqc6k1-binutils-2.23.1/bin/ld: cannot find -licuuc
    /nix/store/v7h3j43vx0dz5ahhkxg5z50by2iqc6k1-binutils-2.23.1/bin/ld: cannot find -licudata

**Comment by vcunat** [comment]
It's not a direct dependency of webkit either but goes through `harfbuzz-icu`. Let me have a closer look. (Testing will take me quite some time, I'm afraid.)

**Comment by vcunat** [comment]
Propagating it should do the trick, so I pushed that to master.

**Comment by khumba** [comment]
Thank you!  I'm waiting for webkit to build to test this out now.  I
investigated Claws futher and found that building even the 3.11.1 tag
from git instead of the release tarball exhibits this problem, not
sure what to conclude from that though.  Maybe the switch from
automake 1.14(.x) to 1.15 is what's doing it (the failure cases of
"claws 3.12 || local autoconf run" line up).

**Comment by khumba** [comment]
Yes, you fixed it; I'm writing this from 3.12.  Thanks again.

**Comment by vcunat** [comment]
Maybe it's triggered by using a different libtool version to generate stuff, I'm not sure.
