### ISSUE TITLE
netatalk pulls in X11, even with environment.noXlibs

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#100997]
**Describe the bug**

`netatalk` depends on X11, even when `noXlibs` is `true`. This is a little surprising as it has nothing to do with X.

**To Reproduce**

- Observe that `libX11` appears in the deps of `netatalk`
    
    ```
    nix-store --query --requisites $(nix-instantiate -A netatalk) | grep X11
    ```

or

- Observe that it depends on `X11`
- Build a system using `netatalk` on a very slow armv7l server
- Observe that lots of time has passed :)

**Screenshots**

![image](https://user-images.githubusercontent.com/857308/96373211-9575e000-119d-11eb-8a00-082229b60457.png)
 
**Notify maintainers**

The most suspicious link in the chain (to me) is the dependency of pygobject on cairo, so: @jtojnar

**Comment by jtojnar** [comment]
As you can see from the expression, pygobject is being pulled by dbus-python's `checkInputs`. Cairo is required by pygobject for technical reasons – actually, the version in #98316 will make the pycairo dependency optional.

**Comment by jtojnar** [comment]
Xlibs do not seem to be needed for pycairo itself, opened #101022. Of course, cairo still needs x11.

**Comment by expipiplus1** [comment]
Cool, thanks!

**Comment by expipiplus1** [comment]
#101022 fixed the problem with pycairo it seems, however another dependency here via dbus has sprung up: 

![image](https://user-images.githubusercontent.com/857308/115168137-79231380-a0ec-11eb-9b0d-fce9ab54afcd.png)
