### ISSUE TITLE
redshift-gtk: Can't find GTK

### ISSUE THREAD

**Issue by khumba** [NixOS/nixpkgs#10097]
$ redshift-gtk
    ERROR:root:Could not find any typelib for Gtk
    Traceback (most recent call last):
      File "/nix/store/cv83zk3zndq3271mwyph52xyfq5m84ws-redshift-1.10/bin/.redshift-gtk-wrapped", line 26, in <module>
        from redshift_gtk.statusicon import run
      File "/nix/store/cv83zk3zndq3271mwyph52xyfq5m84ws-redshift-1.10/lib/python3.4/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
        from gi.repository import Gtk, GLib, GObject
    ImportError: cannot import name 'Gtk'

This happens on release-15.09 and master, and whether I run result/bin/redshift-gtk or install it in a user environment or system-wide.  I tried a few things (e.g. adding gtk3 to buildInputs) but I don't know Python and GTK+ well enough to fix this.  The daemon works fine.  What am I missing :)?  CC @mornfall, @nckx.

**Comment by nckx** [comment]
Works fine for me... until run in a separate `nix-shell`. Welp. I'll see if adding `gtk` and friends to `PYTHONPATH` fixes that.

**Comment by nckx** [comment]
I wasn't planning on closing this yet. The icon still needs fixing.

@khumba: please give `master` a whirl. `redshift-gtk` should now succesfully fail by default (`geoclue` performs an ironic pastiche of access control). Passing your location manually should work fine.

**Comment by khumba** [comment]
Success!  Thanks @nckx.  I'm using Redshift with manual location anyway.  Works (albeit without the icon) with some harmless warnings:

    $ redshift/bin/redshift-gtk -l manual
    
    ** (.redshift-gtk-wrapped:4556): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
    ERROR:root:Could not find any typelib for AppIndicator3
    Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by nckx** [comment]
> albeit without the icon

I assumed simply wrapping `XDG_DATA_DIRS` would fix that. I was wrong. Suggestions welcome.

**Comment by khumba** [comment]
Yeah, at least it works now :).

I am interesting in looking into the icon, since there's also an
icon-related file collision when trying to install both Redshift and
Claws into a user environment (not on NixOS right now, can't recall
which file, icon.theme or something like that).

**Comment by nckx** [comment]
Probably `icon-theme.cache`. If so, could you try https://github.com/nckx/nixpkgs/commit/40503a2eab2d503e572f9b53dcb6052d61055031?

**Comment by khumba** [comment]
This fixes the collision so LGTM (doesn't help the tray icon).  Would you mind pushing khumba/nixpkgs@f81109a to master please, with the corresponding fix for Claws?

**Comment by nckx** [comment]
I get the following collision as well:

> collision between ‘/nix/store/b2x4jlq82gwh25qq3qgvfc2y1jrwlmr7-shared-mime-info-1.5/share/mime/aliases’ and ‘/nix/store/2vvhsqv6mn1zbcs0yyhyg6gqb54sjb1n-claws-mail-3.11.1/share/mime/aliases’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages.

It would be nice to fix this in the same go. I *assume* `shared-mime-info`'s ought to take precedence, but IANAL.
