### ISSUE TITLE
lcms2: fails to build on darwin

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#101068]
nixpkgs-unstable seems to be blocked by lcms2 not building on darwin https://hydra.nixos.org/build/128672564/nixlog/1

I didn't see this tracked yet. Could someone add the "1.severity: channel blocker" to this issue (or to the existing issue if I missed it)?

I don't have a mac myself so I don't think I can help hunting the problem down.

**Comment by eraserhd** [comment]
It appears to have started failing long after the `lcms2`'s last update.  Bisecting is taking a long time, but I'll post back when I learn something.

**Comment by zowoq** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/101044.
