### ISSUE TITLE
`steam-run`: impossible to use opencl inside

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#101076]
**Describe the bug**

I can't find how to run a program that requires `opencl` inside a `steam-run` session, even if it works inside the host system.

**To Reproduce**
1. Enable opencl, for example adding in NixOs:
```
hardware.opengl.enable = true;
hardware.opengl.extraPackages = with pkgs; [ intel-ocl ];
```
2. Check that `clinfo` detects your hardware:
```
$ nix-shell -p clinfo

[nix-shell:~]$ clinfo
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL
[...]
```
3. Build a `steam-run` with `clinfo`, and run it:
```
$ nix-build -E "with import <nixpkgs> {}; (steam.override {extraPkgs = pkgs: [ocl-icd clinfo]; }).run" 
/nix/store/jcj8g8nk5jkb515nmc3gzz3zch3xd341-steam-run

$ ./result/bin/steam-run clinfo
Number of platforms                               0

```
4. Observe that `clinfo` fails to detect hardware.

**Expected behavior**
I would expect `clinfo` to work in `steam-run`.

**Notify maintainers**
@jagajaga 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.66, NixOS, 20.03post-git (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-unstable-21.03pre243968.2a35f664394, nixos-20.03.3002.773ef5ae783"`
 - channels(me): `"home-manager-20.03, nixos-unstable-21.03pre243434.e0759a49733"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam-run
```

**Comment by tobiasBora** [comment]
Also, I don't know if it is of interest, but `buildFHSUserEnv` does not have this issue (I was sure that `steam-run` was built on top of `buildFHSUserEnv` but maybe not...):

```
$ nix-build -E 'let pkgs = import <nixpkgs> {}; in pkgs.buildFHSUserEnv {name="fhs"; targetPkgs=pkgs:[]; multiPkgs=pkgs:[pkgs.bash pkgs.clinfo]; runScript="bash";}'
$ result/bin/fhs 
fhs-chrootenv:leo@bestos:/tmp/n$ clinfo 
Number of platforms                               1
[...]
```
So I don't what `steam-run` adds...

**Comment by tobiasBora** [comment]
Still interested.

**Comment by Artturin** [comment]
i'll take a look once https://github.com/NixOS/nixpkgs/pull/145150 is in master because currently clinfo doesn't show my devices https://nixpk.gs/pr-tracker.html?pr=145150

**Comment by Artturin** [comment]
the commands in the steps to reproduce work for me now.
