### ISSUE TITLE
dolphinEmuMaster ui doesn't match the rest of my desktop

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#101092]
**Describe the bug**

I have upgraded from `20.03` to `20.09-pre` and the `dolphinEmuMaster` `qt` ui doesn't look right anymore. See **Screenshots** section for how the ui looks. See **Expected behavior** for how the ui should look.

**To Reproduce**
1. Upgrade to `20.09`
2. Install `dolphinEmuMaster`
3. Run `dolphin-emu-master` or `dolphin-emu` and look at the ui

**Expected behavior**

I would like the ui to look like the rest of my desktop. Like this:

![Screenshot_20201019_160555](https://user-images.githubusercontent.com/7755101/96506061-fd233e00-1224-11eb-8b7e-6afbd0d4d9d1.png)

**Screenshots**

![Screenshot_20201019_155809](https://user-images.githubusercontent.com/7755101/96505502-35764c80-1224-11eb-9d29-d28f8f55d255.png)

**Additional context**

I am guessing that the issue is in `top-level/all-packages.nix` `dolphinEmuMaster` is built with `qt5.callPackage` instead of `libsForQt5.callPackage`, because when I build with the latter the ui looks fine.

**Notify maintainers**

@MP2E @ashkitten or @ttuegel in case they are able to help :man_shrugging: 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.70, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixosUnstable-20.09pre242714.a31736120c5"`
 - nixpkgs: `/nix/store/9pj63qfmvczn94wdas3vk3802hjm51m7-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: dolphinEmuMaster
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
It looks fine to me on 007126eef72271480cb7670e19e501a1ad2c1ff2 - current `nixos-unstable`. https://github.com/NixOS/nixpkgs/pull/101369 doesn't affect it at all.

**Comment by lasers** [comment]
I completed more than 3 games on stable channel with unstable dolphin-emu. Never ran into this issue. Also, your latest `Dolphin 5.0 - 11824` is more than 10 months ago. Is it still an issue today?

**Comment by aanderse** [comment]
Sorry. Yes, this was fixed. Thanks!
