### ISSUE TITLE
glibc references /etc

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#101038]
**Describe the bug**
Some glibc library functions, e.g. `getservbyport` try to access files in `/etc`, for `getservby*` that would `/etc/services`.
On NixOS or any other Linux distribution, it would find that file there.
However, if you're in the nix sandbox during a build, that file is obviously missing.

The specific thing I ran into this with is the `nft` tool from the `nftables` package. I wanted to add a rule validation build step with `nft -c`, like many other modules do, so you can already know if rules are valid during system build and not only after deployment. This fails, because of the issue outlined above.

**To Reproduce**
1. Try to use a program that uses libc functions like `getservbyname` in the nix build sandbox
2. Observe it fails

**Expected behavior**
For that program to work.

**Additional context**
The specific constant for `/etc/services` is defined in `resolv/netdb.h` and could just be patched there, but this seems like a more generic issue and question.
A quick search didn't lead me to any previous discussion on this, but I might have missed something.

Although I did find that some runtimes, like [go](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/go/1.15.nix#L106) do get patched for this.

The other files in `/etc` that aren't `services`, as determined by running `strings` are:
```
/etc/aliases
/etc/default/nss
/etc/ethers
/etc/fstab
/etc/gai.conf
/etc/group
/etc/gshadow
/etc/hesiod.conf
/etc/host.conf
/etc/hostid
/etc/hosts
/etc/hosts.equiv
/etc/ld-nix.so.preload
/etc/localtime
/etc/mtab
/etc/netgroup
/etc/networks
/etc/nsswitch.conf
/etc/passwd
/etc/protocols
/etc/publickey
/etc/.pwd.lock
/etc/resolv.conf
/etc/rpc
/etc/services
/etc/shadow
/etc/shells
/etc/suid-debug
/etc/ttys
```

Most of those are (e.g. /etc/hosts or /etc/passwd) are probably fine.

**Notify maintainers**

@edolstra @Ma27 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by edolstra** [comment]
This is intended behavior. We can't use e.g. `$out/etc` since then it would be impossible to change these configuration files without rebuilding the entire system. It would be nice if they could be overriden at runtime using an environment variable though.

**Comment by ajs124** [comment]
I get that this is intended for most of these files, but specifically for `/etc/protocols` and `/etc/services`, I doubt anyone overrides those and as outlined in my example, they can be needed in the sandbox, whereas most of the others are either needed even less often or nix actually creates "standins" or passes them (e.g. `/etc/passwd` or `/etc/resolv.conf`) in the sandbox.

That said, go has been using `/etc/protocols` directly from ~`iana_etc`~ `iana-etc` since 6039f2effea02c1ee6a716d0487f787293cd081b, which is from 2013. `/etc/services` was added a few years later.

**Comment by ajs124** [comment]
Closing since nobody will fix this and I don't plan on ever working on this, at least not in nixpkgs proper.
