### ISSUE TITLE
kubernetes: Remove or update the dashboard

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#101072]
The dashboard is very old, and should either be upgraded or, maybe, removed entirely, to avoid having users accidentally struggle with outdated software. Opened this due to comment: https://github.com/NixOS/nixpkgs/pull/101059#issuecomment-712106762

**Comment by zowoq** [comment]
Opened a PR to remove it: https://github.com/NixOS/nixpkgs/pull/150622
