### ISSUE TITLE
Gpaste needs update for gnome3.18

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10108]
The gpaste derivation version is `${gnome3.version}.3` but `3.18.3` does not exist yet. The most recent 3.18 version of gpaste is 3.18.1.1 (https://github.com/Keruspe/GPaste/releases). I can't submit a pull request yet because my computer needs to build gnome3.18 first.

**Comment by lethalman** [comment]
There's no hurry, you can package it when gnome 3.18 will be in the unstable channel.

**Comment by DamienCassou** [comment]
but won't the 3.18.3 version number break the build? This release does not exist.

**Comment by lethalman** [comment]
@DamienCassou yes it will, I believe there are also some other programs that will break. No worries :)

**Comment by DamienCassou** [comment]
This has been fixed a long time ago.
