### ISSUE TITLE
fluffychat: flutter-based Matrix client

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#101111]
**Project description**
It's a Matrix client that is built with Flutter.

I don't know how hard this will be to package for Nix. I see that Flutter is packaged, but I don't see anything being built with it.

**Metadata**

* homepage URL: https://fluffychat.im/en/
* source URL: https://gitlab.com/ChristianPauly/fluffychat-flutter
* license: AGPLv3
* platforms: linux

**Comment by colemickens** [comment]
No, this isn't.

**Comment by McSinyx** [comment]
Flutter seems spooky:

                    Welcome to Flutter! - https://flutter.dev

    The Flutter tool uses Google Analytics to anonymously report feature usage
    statistics and basic crash reports. This data is used to help improve
    Flutter tools over time.

    Flutter tool analytics are not sent on the very first run. To disable
    reporting, type 'flutter config --no-analytics'. To display the current
    setting, type 'flutter config'. If you opt out of analytics, an opt-out
    event will be sent, and then no further information will be sent by the
    Flutter tool.

    By downloading the Flutter SDK, you agree to the Google Terms of Service.
    Note: The Google Privacy Policy describes how data is handled in this
    service.

    Moreover, Flutter includes the Dart SDK, which may send usage metrics and
    crash reports to Google.

    Read about data we send with crash reports:
    https://flutter.dev/docs/reference/crash-reporting

    See Google's privacy policy:
    https://policies.google.com/privacy

I think we'll need to see how other distros cleanse of telemetry.  Also Flutter seems to be downloading dependencies by itself which is AFAICT against the Nix-way.

**Comment by genofire** [comment]
is solved -> some bugs exists, e.g. missing libcrypto.so.1.1

maybe solved in #160942, let's take a look after buildserver run.
