### ISSUE TITLE
terraform_0_13 providing wrong terraform version

### ISSUE THREAD

**Issue by dmedinag** [NixOS/nixpkgs#101129]
**Describe the bug**
Installing the terraform_0_13 module is providing the v0.13.3 executable instead of the v0.13.4 that is expected (from both the tag being used and the documentation of the module).

**To Reproduce**
1. Install terraform_0_13
2. Run `terraform --version`

**Expected behavior**
I expected the v0.13.4 version to be installed, instead of the v0.13.3

**Additional context**
I can see that the tag in [default.nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/cluster/terraform/default.nix) seems to be the right one, but the executable we're getting out if is not right.

**Notify maintainers**
- @Chili-Man
- @babariviere
- @kalbasit
- @marsam
- @peterhoeg
- @timstott
- @zimbatm

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(dmedinag): `"home-manager, nixpkgs-21.03pre244772.502845c3e31"`
 - nixpkgs: `/Users/dmedinag/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
attribute: terraform_0_13
```

**Comment by dmedinag** [comment]
Nevermind. Running `nix-channel --update` solved the issue! My bad.

**Comment by timstott** [comment]
:wave: @dmedinag, the terraform version at [`nixpkgs-21.03pre244772.502845c3e31`](https://github.com/nixos/nixpkgs/blob/502845c3e31ef3de0e424f3fcb09217df2ce6df6/pkgs/applications/networking/cluster/terraform/default.nix#L134-L136) is v0.13.3.

The link to `default.nix` you have provided points to `nixos-unstable` latest, which is ahead of `nixpkgs-21.03pre244772.502845c3e31`

**Comment by dmedinag** [comment]
yep, after running `nix-channel --update` my system metadata is now

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(dmedinag): `"home-manager, nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/Users/dmedinag/.nix-defexpr/channels/nixpkgs
