### ISSUE TITLE
Cinnamon: Screenbrightness change does not work

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#101128]
**Describe the bug**

In the Cinnmaon desktop manager, changing the screen brightness does not work. This is not a hardware support issue, `light -S 40` __does work__.

**To Reproduce**
1. Start Cinnamon DE
2. Press the brightness down/up key
3. Observe no change in screen brightness

**Expected behavior**
Screen brightness changes, and maybe a nice popup which tells me what is happening (similar to the volume popup)?

**Additional context**
Worth noting is, that I found this in my session logs:
```
$ journalctl _UID=$UID
Oct 20 10:13:23 zornpad .csd-media-keys[2394]: Failed to get old screen percentage: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dexec_2derror_2dquark.Code8: Failed to execute child process “/run/current-system/sw/bin/cinnamon-settings-daemon/csd-backlight-helper” (No such file or directory)
```
Indeed, in the `cinnamon.cinnamon-settings-daemon` package quite a lot of relevant binaries seem to reside in `libexec`, not in `bin`.

**Notify maintainers**
@worldofpeace @mkg20001 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.14, NixOS, 20.09beta1083.51aaa3fa1b6 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09beta1083.51aaa3fa1b6, nixos-unstable-21.03pre246062.420f89ceb26"`
 - channels(wucke13): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
cinnamon
```

**Comment by mkg20001** [comment]
> Screen brightness changes, and maybe a nice popup which tells me what is happening (similar to the volume popup)?

This is already supported, just the bug prevents it from working

--

My problem is that for me it's a hardware issue since the light command doesn't work on this laptop, so I can't debug this properly

**Comment by mkg20001** [comment]
Issues  seems csd-backlight-helper binary missing, link target does not exist

```
lrwxrwxrwx 2 root root 103  1. Jan 1970  /run/current-system/sw/bin/cinnamon-settings-daemon/csd-backlight-helper -> /nix/store/8b21dx7aqcq3pq74k205rdcavqwvriql-cinnamon-settings-daemon-4.6.4/libexec/csd-backlight-helper
```

**Comment by worldofpeace** [comment]
Yep, that is in fact the issue. From looking at https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/cinnamon/cinnamon-settings-daemon/csd-backlight-helper-fix.patch it should for sure be there. 

From looking at https://github.com/linuxmint/cinnamon-settings-daemon/blob/4.6.4/plugins/power/Makefile.am#L98, I think because libgudev is not in buildInputs (this is a guess), it was never compiled.

**Comment by wucke13** [comment]
Perfect, I hope it'll get back-ported soon :)

**Comment by wucke13** [comment]
Works now on 20.09 :+1:
