### ISSUE TITLE
Nvidia driver is not ready for Linux 5.9

### ISSUE THREAD

**Issue by jpotier** [NixOS/nixpkgs#101259]
**Describe the bug**
NVidia warns that they are not ready for kernel 5.9 yet.

https://forums.developer.nvidia.com/t/nvidia-driver-not-yet-supported-for-linux-kernel-5-9/157263

**To Reproduce**
0. Be at nixos 21.03pre246543.24c9b05ac53.
1. Upgrade nixos-unstable to 21.03pre248062.5265d49a36b, with:
```
{
boot.kernelPackages = pkgs.linuxPackages_latest;
}
```
on.
2. Observe that no opengl application start anymore (such as alacritty, nvidia-smi, etc.)
3. Reboot
4. Same problem after boot.

**Expected behavior**
I would expect this incompatibility to be caught during nixos-rebuild, if kernel version is > 5.9 and nvidia driver version is < than 450.66 (current), and refuse to build.

**Screenshots**

**Additional context**

**Notify maintainers**

**Comment by eadwu** [comment]
It works fine for general daily use, anything that uses nvidia-uvm is dead though. There are ways to make nvidia-uvm work but they won't be included into the repository.

**Comment by jpotier** [comment]
Indeed you are right!

Here's more tests I did this morning:

After update, but still on kernel 5.8x, neither nvidia *nor intel* opengl work:

-  running `alacritty`:

```
Created log file at "/tmp/Alacritty-2026.log"
[2020-10-22 09:15:18.750448293] [ERROR] Alacritty encountered an unrecoverable error:

        Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`
```

- running `nvidia-smi`:

```
Failed to initialize NVML: Driver/library version mismatch
```

## Rebooting to new kernel 5.9

- alacritty still does not start, **unless** I wrap it in nvidia-offload.

- nvidia-smi runs correctly:

```
Thu Oct 22 09:16:10 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.28       Driver Version: 455.28       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro T1000        Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8     2W /  N/A |      4MiB /  3914MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1464      G   ...-xorg-server-1.20.8/bin/X        4MiB |
+-----------------------------------------------------------------------------+
```

So, actually, *it seems that my Intel GPU's OpenGL is not working anymore after the upgrade*.

My configuration has only "nvidia" as  xserver videoDrivers:

```
services.xserver.videoDrivers = ["nvidia"];
```

But, everything worked fine before the upgrade.

**Comment by jpotier** [comment]
I think I'll close this for now, because the title is already irrelevant, and I have a workaround.

**Comment by yorickvP** [comment]
Spent 2 hours debugging this in nixpkgs-20.09. nvidia-uvm won't load with `Unknown symbol radix_tree_preloads (err -2)` in dmesg. The workaround is to use linux 5.4.

Search keywords: `CUDA driver version is insufficient for CUDA runtime version` `cudaGetDeviceCount returned 999` `cudaGetDeviceCount returned 35`

**Comment by yorickvP** [comment]
nixpkgs-21.05 and unstable don't have linux 5.9 anymore :)
