### ISSUE TITLE
Microsoft Edge Dev

### ISSUE THREAD

**Issue by hbjydev** [NixOS/nixpkgs#101223]
**Project description**
It's Microsoft's new Edge browser based on Chromium. It just released today with a .deb download we could easily extract and turn into a package.

**Metadata**

* homepage URL: https://microsoftedgeinsider.com
* source URL: n/a
* license: proprietary(?)
* platforms: linux

**Comment by zanculmarktum** [comment]
I've already made it.

To try it out:

```sh
git clone https://gitlab.com/zanc/overlays.git
cd overlays
nix-env -i -E 'f: with import <nixpkgs> { overlays = import ./overlays.nix; config = { allowUnfree = true; }; }; microsoft-edge-dev'
```

**Comment by olynch** [comment]
I get an error when I run edge from your overlay:

```
[1023/171818.277793:WARNING:process_reader_linux.cc(125)] no stack mapping
[1023/171818.277847:WARNING:process_reader_linux.cc(125)] no stack mapping
[1023/171818.283521:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[1023/171818.283556:ERROR:process_memory_range.cc(75)] read out of range
[30430:30430:0100/000000.373734:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
fish: 'microsoft-edge-dev' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by zanculmarktum** [comment]
Works fine here.

![screenshot](https://user-images.githubusercontent.com/16958511/97091912-a4f79c00-1669-11eb-8c0e-f7673975b4e3.png)

Tested on 20.09.

`$ nixos-version --json | jq ''`

```json
{
  "configurationRevision": "98ed418720e329a69a310e277f45b1430540b937",
  "nixosVersion": "20.09.20201020.05334ad",
  "nixpkgsRevision": "05334ad78526ead39af85f846515606d9f052a11"
}
```

**Comment by asdf8dfafjk** [comment]
Try this- https://github.com/NixOS/nixpkgs/pull/101486

**Comment by jdnixx** [comment]
@zanculmarktum here's what I get:
```
strip is /nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/sgm01jabgf4f8hwggy2jj0sgw06gpj1r-microsoft-edge-dev-88.0.673.0/bin
patching script interpreter paths in /nix/store/sgm01jabgf4f8hwggy2jj0sgw06gpj1r-microsoft-edge-dev-88.0.673.0
/nix/store/sgm01jabgf4f8hwggy2jj0sgw06gpj1r-microsoft-edge-dev-88.0.673.0/opt/microsoft/msedge-dev/xdg-settings: interpreter directive changed from "/bin/sh" to "/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/sh"
/nix/store/sgm01jabgf4f8hwggy2jj0sgw06gpj1r-microsoft-edge-dev-88.0.673.0/opt/microsoft/msedge-dev/microsoft-edge-dev: interpreter directive changed from "/bin/bash" to "/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/bash"
/nix/store/sgm01jabgf4f8hwggy2jj0sgw06gpj1r-microsoft-edge-dev-88.0.673.0/opt/microsoft/msedge-dev/xdg-mime: interpreter directive changed from "/bin/sh" to "/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/sh"
checking for references to /build/ in /nix/store/sgm01jabgf4f8hwggy2jj0sgw06gpj1r-microsoft-edge-dev-88.0.673.0...
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
patchelf: cannot find section '.dynamic'. The input file is most likely statically linked
building '/nix/store/dd7niwfw4cgakjx02jy99wh31l2ld0qx-user-environment.drv'...
created 3 symlinks in user environment
```

**Comment by zanculmarktum** [comment]
Actually it runs when you append `LD_LIBRARY_PATH`, i.e.

```
$ LD_LIBRARY_PATH=/run/current-system/sw/lib microsoft-edge-dev
```

Not sure why this is the case.

**Comment by VergeDX** [comment]
In latest version `93.0.910.5`, it says missing a shared library `libxshmfence.so.1`.
After providing the correspond package `xlibs.libxshmfence`, it crash and here is log:
```````log
[0613/122436.368641:ERROR:process_memory_range.cc(75)] read out of range
fish: Job 1, 'microsoft-edge-dev' terminated by signal SIGTRAP (Trace or breakpoint trap)
```````

**Comment by shpinog** [comment]
> In the latest version `93.0.910.5`, it says missing a shared library `libxshmfence.so.1`.
> After providing the correspond package `xlibs.libxshmfence`, it crash and here is log:
> 
> ```
> [0613/122436.368641:ERROR:process_memory_range.cc(75)] read out of range
> fish: Job 1, 'microsoft-edge-dev' terminated by signal SIGTRAP (Trace or breakpoint trap)
> ```

I have been trying to run it for several versions, the result is about the same. It would be great if someone could.

**Comment by Xe** [comment]
For me it's failing on GTK

**Comment by zanculmarktum** [comment]
I know it's a loooong due, but it's fixed now :^)

Anyway, the reason it requires `LD_LIBRARY_PATH` is because MS Edge is unable to locate `libudev.so.1` which is provided by `systemd` package, to workaround it I append `${systemd}/lib` to `opt/microsoft/msedge-dev/msedge`'s rpath using `patchelf`.

**Comment by aanderse** [comment]
Is someone willing/able to create a PR in nixpkgs for this?

**Comment by zanculmarktum** [comment]
I've added beta and stable channels.

If anyone want to make a PR go head, but if you do mention my name in the `maintainers`.

**Comment by abathur** [comment]
It looks like this was added in:
- https://github.com/NixOS/nixpkgs/pull/161064
