### ISSUE TITLE
xmlsec does not build on macOS anymore after update to 1.2.30

### ISSUE THREAD

**Issue by caleb** [NixOS/nixpkgs#101276]
**Description**

After updating `xmlsec` to 1.2.30 (https://github.com/NixOS/nixpkgs/commit/69b21e20d45cdd135cb89e4b5e7ed09a47edaa20) `xmlsec` no longer builds on macOS because the build process for `1.2.30` changed their tests to take into account macOS and thus relies on BSD `base64` flags.

Here is the relevant lines in the test from xmlsec: https://github.com/lsh123/xmlsec/blob/5dc2b1171b70aa4bf8cd5f35d41761dc6e054f3f/tests/testEnc.sh#L407-L410

As you can see he now tests whether the platform is Darwin and uses the `-D` flag to `base64`. Since nix lives in its own world it is using the GNU base64 and this flag is invalid.

Here's the output:

https://gist.github.com/caleb/d6617a615b4b2d2baa64a35df69bf995

You can see multiple errors with the text: `base64: invalid option -- 'D'`. I believe this is why the build is failing.

**To Reproduce**
1. run `nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs/archive/69b21e20d45cdd135cb89e4b5e7ed09a47edaa20.tar.gz -p xmlsec`

**Expected behavior**
xmlsec should install correctly, as it does when using a nixpkgs version before the above commit:

`nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs/archive/b0f40bef4fa81cd0d348cf6b9e9706c4efb130f7.tar.gz -p xmlsec`

**Notify maintainers**
@jonringer 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(caleb): `"home-manager, nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/Users/caleb/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: xmlsec
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
unfortunately we no longer have ofborg to build darwin, and I don't own a mac. But I would be happy to review a PR

**Comment by caleb** [comment]
I'm a pretty big novice at nix, but this seemed like a good way to patch the test.

BTW, without ofborg, does that mean binary packages won't be generated on Darwin? Or was that used for testing?

**Comment by jonringer** [comment]
> BTW, without ofborg, does that mean binary packages won't be generated on Darwin? Or was that used for testing?

ofborg is just for continuous integration. Hydra is still able to build the package set.

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/101319
