### ISSUE TITLE
Docker service not starting with ZFS storage driver.

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixpkgs#10127]
Hello. First issue here so bare with me please.

I am using the unstable channel of NixOS and have my root partition on ZFS. Naturally i wanted to use the ZFS storage driver for Docker however when I set the option `virtualisation.docker.storageDriver` the docker systemd service fails to start and gives this error:

    Error starting daemon: error initializing graphdriver: driver not supported

It appears the only storageDriver option I can set and have docker work is `devicemapper`.

My apologies if I am missing something here but I even tried to create a new ZFS volume for docker and mounted it on `/var/lib/docker` with no change in error. I looked at the source code for what triggers the error and noticed a different error is shown if your filesystem is wrong or what not and that this error appears specific to docker not supporting it as if its components were not installed.

Perhaps I am missing the obvious in that docker just does not have zfs support however it is listed as a valid option for the `virtualisation.docker.storageDriver` option. If this is the case then it should be removed from the valid options there.

Thank you for all your work on the awesomeness that is Nix/NixOS!

**Comment by Nekroze** [comment]
I did end playing around with this more and noticed that I can successfully start the docker daemon so long as I use the command in the systemd file in a shell as root. however systemd executing the same thing fails and causes the error. Oddly enough I am now getting a different error from the systemd service, the one that shows that docker is capable of using the specified storage driver but that something else went wrong.

    Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)

The part that is confusing me, and I think the crux of the issue, is that I can start the daemon in a shell as root but systemd can't.

**Comment by offlinehacker** [comment]
Hmm, i haven't tried with zfs, but it wirks for example with brtfs just fine. Are you running same version in shell as with systemd?

**Comment by Nekroze** [comment]
@offlinehacker Indeed i have tried running the executable mentioned in systemd by specifying the full path. Just dont understand why systemd fails to start the service when I can run the command it says is failing.

**Comment by cransom** [comment]
I can confirm this. The issue is that the ZFS storage driver makes calls to the zfs binary which doesn't exist in the systemd $PATH when this is started.

**Comment by Nekroze** [comment]
@cransom Thanks for figuring this one out and resolving, Cheers mate!

**Comment by Nekroze** [comment]
Hi,

I am now using the docker version that has since been patched however I have the same issue. 

Currently I have a version with this [change](https://github.com/NixOS/nixpkgs-channels/commit/424e6e501a44dc38c610f6d2039dda1cfafe9490#diff-70bfdd2fa01b2467175956249fd04bc9). I am not a nix expression writter (yet) but perhaps this is causing it to now work again?

I was not able to get in and test it before the channel moved on to this sadly so I cannot confirm that it was working with your change @cransom so it may not be that change that causes the issue to persist.
