### ISSUE TITLE
gdk-pixbuf 2.31.7 does not build on Darwin

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#10136]
@vcunat d77588d127d4916eba76a2d692184133263f7add upgraded gdk-pixbuf, but this version does not build on Darwin.  It fails with:

```
make  all-am
make[3]: Entering directory '/private/var/folders/4j/br7bdhjx4b384_snb2087gt00000gn/T/nix-build-gdk-pixbuf-2.31.7.drv-0/gdk-pixbuf-2.31.7/tests'
  CC       pixbuf-read.o
  CCLD     pixbuf-read
  CC       pixbuf-lowmem.o
  CCLD     pixbuf-lowmem
Undefined symbols for architecture x86_64:
  "___libc_free", referenced from:
      _record_bytes in pixbuf-lowmem.o
      _free in pixbuf-lowmem.o
  "___libc_malloc", referenced from:
      _malloc in pixbuf-lowmem.o
      _calloc in pixbuf-lowmem.o
      _realloc in pixbuf-lowmem.o
  "___libc_realloc", referenced from:
      _realloc in pixbuf-lowmem.o
ld: symbol(s) not found for architecture x86_64
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vcunat** [comment]
Does the next bump 23f75e9bb05 fix it (news mentions fixing some build issues)? Or there's one more released upstream.

**Comment by jwiegley** [comment]
@vcunat Nope.

**Comment by vcunat** [comment]
Are you sure that 2.31.6 works and 2.31.7 doesn't?  Could it be due to some source of non-determinism instead?

Hmm, I see that the error is in the `tests` directory, so ATM I think it will be best to just avoid tests on Darwin. I'm not sure if plainly `doCheck = false;` will be enough not to compile the tests.

**Comment by jwiegley** [comment]
I'm all for disabling the `gdk-pixbuf` tests.  That has been one of the most fragile expressions I've ever used on Darwin, as the tests sometimes fail without reason.  However, 2.31.6 does build reliably so far.

**Comment by vcunat** [comment]
I can't even test without a darwin-capable machine, so it's up to you/others to test that and push it (or create a PR, but I think you do have push access).

**Comment by gfxmonk** [comment]
I tried setting `doCheck = false`, but it's unfortunately not enough - the tests are built during the main build, and not on-demand. I tried the following in my `~/.nixpkgs/config.nix` to prevent tests from build built, which works but is very lame:


		gdk_pixbuf = lib.overrideDerivation gdk_pixbuf (o: {
			doCheck = false;
			postConfigure = "echo -e 'all install:\n\ttrue' > tests/Makefile";
		});

**Comment by clevinson** [comment]
I was getting the exact same problem with 2.31.7, but bumping to 2.32.0 (a la https://github.com/NixOS/nixpkgs/commit/23f75e9bb05454d0af44fc823a19c57eafd967e3) works for me!  I just updated the default.nix file in my local nixpkgs repo to fetch 2.32.0 with an updated sha256 hash and ran:
`nix-env -f $NIXPKGS -i gdk-pixbuf`

@jwiegley @gfxmonk it seems strange to me that 2.32.0 didn't work for either of you.  Did you do something different?

**Comment by henrytill** [comment]
Can we close this?  It seems to be building fine on master with latest Nix and `build-use-chroot` enabled.
