### ISSUE TITLE
The ghostscript build is broken on release-20.09

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#101337]
https://hydra.nixos.org/build/128863226/nixlog/1

https://hydra.nixos.org/build/128863226

https://hydra.nixos.org/job/nixos/release-20.09/nixpkgs.ghostscript.x86_64-linux

This breaks some other stuff including google-chrome, cassandra, graphicsmagick, signal-cli.

cc maintainer @viric

**Comment by ivan** [comment]
Applying #101215 to release-19.09 fixes the build.

**Comment by erictapen** [comment]
My backport of https://github.com/NixOS/nixpkgs/pull/101199 was at fault, I reverted it [here](https://github.com/NixOS/nixpkgs/pull/101199#issuecomment-714370999).
