### ISSUE TITLE
Binary caches for Haskell packages with profiling enabled?

### ISSUE THREAD

**Issue by k0001** [NixOS/nixpkgs#10143]
Would it be possible to have something like this, so that we can get a binary cache for Haskell packages compiled with profiling enabled?

```nix
# NOTE: this is just some mock code so that you get the idea. 
# Ideally this expression will be written in whatever way it is acceptable
# within `pkgs/top-level/haskell-packages.nix`
pkgs.haskell.packages.ghc7102_profiling = pkgs.haskell.packages.ghc7102.override {
  overrides = self: super: {
    mkDerivation = args: super.mkDerivation (args // { 
      enableLibraryProfiling = true; 
      enableExecutableProfiling = true; 
    });
  }
}
```

Or maybe there's a better solution? I don't know, I'm just putting the idea out here :)

**Comment by vcunat** [comment]
@peti should know. Maybe his hydra instance provides them already.

**Comment by peti** [comment]
We don't provide any profiled versions of the Haskell package set (neither on `hydra.nixos.org` nor on `hydra.cryp.to`). It's trivial to enable those kind of builds, obviously, but I'm not sure that our infrastructure can take another 7,000 builds. One factor is that our machines aren't necessarily powerful enough to build them. The second, probably even more important factor, is that we don't have enough disk space to store them, i.e. `hydra.nixos.org` is frequently running out of disk space as it is now already.

**Comment by k0001** [comment]
Hmm, that's understandable. Thanks. 

What about simply setting `enableLibraryProfiling` for the current Haskell package sets? That would ensure that [profiling-enabled libraries are packaged along with non-profiling-enabled libraries](https://www.haskell.org/cabal/users-guide/installing-packages.html). It would still take some more space, but only about half the space it would take to keep a whole different package set. 
 
With `enableLibraryProfiling` enabled for a library `foo` depended by `bar`: If `bar` is a library or executable compiled with profiling enabled, then it will use `foo`'s libraries that were compiled compiled with profiling enabled, otherwise it will use `foo`'s libraries that were compiled without profiling enabled. 

Additionally, if somebody needs to compile a particular package with `enableExecutableProfiling`, they can override just that package (which probably won't lead to a recompilation of the whole package set, as this scenario probably means that you are trying to profile that particular executable, and not any package depending on it).

**Comment by k0001** [comment]
Also, maybe it is not necessary to enable `enableLibraryProfiling` for all the current Haskell package sets. Personally, I would appreciate having this enabled for `ghc7102` and `ghcjs`. Perhaps others using some recent `lts` would appreciate that too. But maybe we don't need to enable this for older package sets not used as much.

**Comment by peti** [comment]
If we enable profiling in the default package set, then every user will build or download those extra copies of the library regardless of whether they want profiling or not. Furthermore, build of packages like `pandoc` and `darcs` will compile their entire dependency tree with profiling versions included even though they'll never be used in the build of the executable. That's not exactly an ideal situation either.

**Comment by k0001** [comment]
Hmm… that's a good point. So I guess this will have to wait until those disk space issues are solved. 

Thanks anyway @peti.

**Comment by gridaphobe** [comment]
@peti could we perhaps use multi-output derivations to separate the profiled libraries from the regular libraries?

**Comment by peti** [comment]
Yes, I suppose we could that. It's not going to be simple, though, because I don't believe that `ghc` supports different libdirs for library variants out of the box.

**Comment by vcunat** [comment]
Do the profiled and non-profiled builds share lots of work? If not, I see no reason to always perform the work for both.

**Comment by peti** [comment]
@vcunat, there's no shared work. Profiled and non-profiles builds are pretty much separate things.
