### ISSUE TITLE
Get `adb` and `fastboot` builds from source (via robotnix)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#101425]
**Describe the bug**

1. One of the few things on my systems that isn't portable over to aarch64 is `adb` and `fastboot`.
2. One of the few remaining non-free packages (or at least requiring explicit opt-in) on my system is `adb`.

It seems like Robotnix already is building `adb`/`fastboot`, but I don't know how much work it would be to extract a 'minimal' piece that could be pulled into nixpkgs.

It would be nice to have these natively, freely built from source.

cc: @danielfullmer (and since I haven't had a chance to say it anywhere else, awesome talk, awesome project, thank you!)

**Comment by xaverdh** [comment]
related (for reference): https://github.com/NixOS/nixpkgs/issues/75603

**Comment by danielfullmer** [comment]
I'll summarize some of the discussion in other issues (#75603 and https://github.com/danielfullmer/robotnix/issues/25), as well as the relevant [slides](https://cfp.nixcon.org/media/robotnix-nixcon2020-final.pdf) from my talk at Nixcon 2020.
I currently have two working ways to build `adb` / `fastboot` from source:

## Use the existing android build system (`ckati` + `soong`).
Try this using by building `sdk/adb.nix` from https://github.com/danielfullmer/robotnix
  - Pros:
    - maintainability (at least, when compared with option 2)
  - Cons:
    - Uses Google's prebuilt toolchains.  I believe these toolchains only support `aarch64` via cross-compilation from `x86_64`.
    - Likely requires checking out all (or nearly all) of the AOSP source tree (>40GB of source) to build. See #75603 for additional discussion
  - Difficulty: 4/10.  This really just requires extracting a more minimal build script from `robotnix` (and potentially refactoring the updater script).

## Use my experimental projects to convert the android build system to a nix-native build system: [blueprint2nix](https://github.com/danielfullmer/blueprint2nix) + [soongnix](https://github.com/danielfullmer/soongnix).
Try this by building the `fastboot` or `adb` attribute from the `default.nix` of https://github.com/danielfullmer/soongnix
  - Pros:
    - Uses nixpkgs toolchains. Supports native compilation on `aarch64-linux`. (Tested working on my pinebook pro)
    - Only requires checking out the subset of source that is actually needed to build the projects.
  - Cons:
    - Maintainability.  Each new android release may require serious updates for `blueprint2nix` and `soongnix`.
  - Difficulty: 7/10.  blueprint2nix / soongnix would need to updated to work with the latest `platform-tools` git tag from Google.  These projects also currently have nearly no documentation or comments throughout the source code. The code could likely use some serious refactoring as well.  Some (seemingly optional) modules used by `adb` or `fastboot` are currently unimplemented in `soongnix` (e.g. `java_binary_host` for `fastdeploy`)

I'm not exactly sure if/when I'll have time to work on this myself in the near future.  But, I'm available to help answer any questions if anyone else is interested in working on this..

**Comment by primeos** [comment]
I forgot about this issue. Since #124992 we have an `android-tools` package that should satisfy both 1. (AArch64 support) and 2. (built from source).

We can leave this issue open if we want a Robotnix build as well (which is a really awesome project! Thanks @danielfullmer) but at least we now have a viable alternative to the pre-built binaries from Google :)

**Comment by samueldr** [comment]
I'll go one step further and close this issue. The `android-tools` fork in use solves the underlying problems AFAICT.

Feel free re-open if there is a reason we would want to use the soongnix tooling instead :).
