### ISSUE TITLE
fish: math command is missing bc

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#10141]
```
> math 20
env: bc: No such file or directory
```

cc @ocharles

**Comment by jagajaga** [comment]
Install `nix-env -iA nixos.bc`.

**Comment by Profpatsch** [comment]
@jagajaga Of course, but `math` is fish default functionality, see http://fishshell.com/docs/current/commands.html#math

So it’s a dependency.

**Comment by matthiasbeyer** [comment]
On master there is a `propagatedBuildInputs = [ bc coreutils ]` ... so it should arrive in unstable soon, right?

**Comment by Profpatsch** [comment]
Is  on unstable already. Problem is `math` is implemented as a fish file and probably calls `command bc` somewhere.
