### ISSUE TITLE
nix-build isn't working with GHCJS

### ISSUE THREAD

**Issue by mayhewluke** [NixOS/nixpkgs#10148]
When using `nix-build` with a GHCJS `mkDerivation` I end up with the following message:

```
$ nix-build
...
In-place registering foo-0.0.0...
all.js:
'/nix/store/b4hm2k5lzqjr4d6zs5ikqf5y2ivijzsa-ghcjs-0.1.0/bin/ghcjs-pkg' exited
with an error:
foo-0.0.0: Warning: haddock-interfaces:
/tmp/nix-build-haskell-foo-0.0.0.drv-0/yesod/dist/doc/html/foo/foo.haddock
doesn't exist or isn't a file
foo-0.0.0: Warning: haddock-html:
/tmp/nix-build-haskell-foo-0.0.0.drv-0/yesod/dist/doc/html/foo doesn't
exist or isn't a directory
foo-0.0.0: cannot find any of
["Client.hi","Client.p_hi","Client.dyn_hi","Client.js_hi","Client.js_p_hi"]
(use --force to override)
builder for ‘/nix/store/1nq7hzgy9lhp3r9kpxjlzpcpkxr45asz-haskell-foo-0.0.0.drv’ failed with exit code 1
error: build of ‘/nix/store/1nq7hzgy9lhp3r9kpxjlzpcpkxr45asz-haskell-foo-0.0.0.drv’ failed
```

I'm not sure where this error is coming from or why I'm getting it. My derivation looks like the following:

``` nix
mkDerivation {
  pname = "foo";
  version = "0.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ ... ];
  license = "undefined";
}
```

Setting `doCheck`, `doHoogle`, and `doHaddock` to false don't appear to make a difference. As a workaround I'm just using `nix-shell --run 'ghcjs Client.hs'` instead, but it would be nice to get `nix-build` working.

**Comment by domenkozar** [comment]
This should've been fixed. Can you provide an example how to reproduce?

**Comment by mayhewluke** [comment]
Thanks for taking a look at this, @domenkozar. Unfortunately it's been long enough now that I can't remember how to reproduce this any more. It's been a while since I used GHCJS but I seem to remember I was using `nix-build` just fine in the end so it's probably safe to say that the problem I was having was indeed fixed at some point.
