### ISSUE TITLE
riscv-pk build error

### ISSUE THREAD

**Issue by rrremiii** [NixOS/nixpkgs#101492]
**Describe the bug**
I have riscv64 compatible gcc compiler but build file use standard x86 version

**To Reproduce**
1. ```nix-env -iA nixos.riscv-pk```

**Expected behavior**
Normal installation

**Screenshots**
![image](https://user-images.githubusercontent.com/33205215/97044151-515b5480-157c-11eb-8ffd-6a0a66112fcc.png)

**Notify maintainers**
@shlevy 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.03.3158.7c2a362b58a (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(remi): `"home-manager-20.03"`
 - channels(root): `"nixos-20.03.3158.7c2a362b58a, nixos-unstable-21.03pre248170.007126eef72"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
    spike
```

**Comment by r-burns** [comment]
Hey, so I think what happened here, is it tried to build riscv-pk for your native x86 build platform. The package is now correctly set as riscv-only, so if you try to build it for x86, you get
```
error: Package ‘riscv-pk-0.1pre438_e5846a2’ in pkgs/misc/riscv-pk/default.nix:36 is not supported on ‘x86_64-linux’, refusing to evaluate.
```

If you want to build it for riscv64, you can do `nix-build '<nixpkgs>' -A pkgsCross.riscv64.riscv-pk`.
