### ISSUE TITLE
Pidgin crashing with Pango error on URL mouseover in conversation history

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#101458]
See the [upstream ticket](https://developer.pidgin.im/ticket/17434) for details.
See the [fix in pango](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/214).

Seems like the solution is to bump `pango` to from `1.45.3` to `1.45.5`. I can confirm that the specific patch in `pango` does fix `pidgin`.

@rnhmjoj any chance you might volunteer to do this version bump?

ping @lunasspecto

**Comment by rnhmjoj** [comment]
If you're asking because I made the PR for Pango 1.45.3, sure I can try but I'm not familiar with the GTK ecosystem.
I'm probably going to need help myself in testing the update.

**Comment by aanderse** [comment]
I can assist with testing if you're able to draft up a PR.

**Comment by rnhmjoj** [comment]
Uhm, the latest release is already 1.47. I could make a PR to update to 1.47 in staging and 1.43.5 in 20.09.

**Comment by aanderse** [comment]
That sounds great. Thank you!

**Comment by rnhmjoj** [comment]
Done. It should be fixed next time staging is merged into master/20.09.

**Comment by aanderse** [comment]
Thank you very much! 🎉
