### ISSUE TITLE
Packaging Github actions runner

### ISSUE THREAD

**Issue by aditsachde** [NixOS/nixpkgs#101426]
**Project description**
Github actions is a CI/CD service integrated with Github, and has an ability to use self-hosted runners. I currently have a dedicated Ubuntu VM to run the runner, but I'd love to migrate it to NixOS.

**Metadata**

* homepage URL: https://github.com/features/actions
* source URL: https://github.com/actions/runner
* license: mit
* platforms: linux, darwin (Upstream officially supports Mac, Linux, and Win)

**Comment by c0deaddict** [comment]
A good start would be packaging the binary release: https://github.com/actions/runner/releases

**Comment by veehaitch** [comment]
Done! 🎉 #116775
