### ISSUE TITLE
texlive.combined.scheme-minimal: can't find the format file `pdflatex.fmt'

### ISSUE THREAD

**Issue by jfaure** [NixOS/nixpkgs#101405]
I'm trying to use inkscape's latex extension
texlive.combined.scheme-minimal derivation works, but provides a broken pdflatex that complains about missing 'pdflatex.fmt'

**Comment by veprbl** [comment]
Steps to reproduce:
```
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/release-20.09.tar.gz -p texlive.combined.scheme-minimal --pure --run "echo '\documentclass{article}' | pdflatex"
```

I suppose that it has to do with the fact that pdflatex symbolic link is present in `texlive.bin.core` whereas upstream "pdftex" package doesn't ship it. We could get rid of the symlink and let it be recreated based on formats present (in this case based on presence of `texlive.latexconfig`).

**Comment by veprbl** [comment]
One would also need to figure out how to update fmtutil.cnf to disable the missing formats, so that texlinks is prevented from re-creating symlinks in bin/ for those.
