### ISSUE TITLE
Provide the package versions in `ghcjs-boot` to GHC as well

### ISSUE THREAD

**Issue by mayhewluke** [NixOS/nixpkgs#10147]
`ghcjs-boot` uses its own versions of [several packages](https://github.com/ghcjs/ghcjs-boot/tree/master/boot). When working on a project using both GHC and GHCJS it would be good to be able to use the exact same versions of these packages across both halves of the project. This is currently not possible because `nixpkgs` just [hands off](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghcjs.nix#L16) responsibility for those packages to `ghcjs`, so there is no way to access their derivations.

I don't think it's as simple as going through and adding the derivations to [configuration-ghcjs.nix](pkgs/development/haskell-modules/configuration-ghcjs.nix), though - changing the derivations from `null` to an actual derivation seems like it would cause problems on the GHCJS side of things. I'm not sure how this could be solved, but it would be great if we could get something going!

**Comment by Profpatsch** [comment]
triage: has this been fixed?

**Comment by mayhewluke** [comment]
No clue - haven't used GHCJS in years. Feel free to close if you want.

**Comment by oxij** [comment]
@mayhewluke Could you please describe what you expected this to do? Would reusing haskellPackages expressions and overriding sources from ghcjs sources work?

**Comment by mayhewluke** [comment]
@oxij I haven't been involved with any of this in years, and the original post was almost three years ago. I don't know the original issue, or if it's still relevant any more. There's nothing more I can give you here, sorry.

**Comment by Profpatsch** [comment]
@oxij Some two hundred issues might have bubbled up in the “last changed” list, since I triaged them by going through them “reverse last changed” (so that inactive old issues can be closed if possible).

**Comment by oxij** [comment]
@Profpatsch

Yeah, I watch closed and stalled (naturally and of "make an RFC" kind) PRs and locally tag those that seem like unfixed bugs/cool features to me. If the thing seems pretty easy to do and I feel like it could be useful to me or to someone I know (like this issue) or looks like it could make somebody flip the tea table (like the channel drvs bug) I poke my head in.

Hence, since you closed a bunch of issues, I poked my head into some :)
