### ISSUE TITLE
Code - OSS

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#101534]
**Project description**
Open source code editor developed by Microsoft for Windows, Linux and macOS. It includes support for debugging, embedded Git control, syntax highlighting, intelligent code completion, snippets, and code refactoring. It is also customizable, so users can change the editor's theme, keyboard shortcuts, and preferences.

_This is not to be confused with the microsoft licensed vscode product which is already packaged._

**Metadata**

* homepage URL: https://github.com/microsoft/vscode/
* source URL: https://github.com/microsoft/vscode/
* license: mit
* platforms: unix, linux, darwin, windows

**Comment by prusnak** [comment]
PR in https://github.com/NixOS/nixpkgs/pull/86122

**Comment by Narice** [comment]
Oops, wasn't aware of the PR in progress, thanks for mentionning it ;)
