### ISSUE TITLE
claws-mail: installing collides with shared_mime_info

### ISSUE THREAD

**Issue by khumba** [NixOS/nixpkgs#10156]
$ nix-env -iA clawsMail
    ...
    $ nix-env -f /n -iA shared_mime_info
    installing ‘shared-mime-info-1.3’
    building path(s) ‘/nix/store/3b9lwyw0wij5x2lf2b973cd8gky2s7ac-user-environment’
    Wide character in die at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
    collision between ‘/nix/store/xf1ak2dgcjncwpv064qsm21xdw1qyklj-claws-mail-3.11.1/share/mime/aliases’ and ‘/nix/store/f0qq8gi9np98p679qshzwqs4dbyi07aj-shared-mime-info-1.3/share/mime/aliases’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
    builder for ‘/nix/store/26kxx0yc56i22cbnnd56yf95kwmwfizm-user-environment.drv’ failed with exit code 255
    error: build of ‘/nix/store/26kxx0yc56i22cbnnd56yf95kwmwfizm-user-environment.drv’ failed

Thanks @nckx for pointing this out.  In 268b4d5 I added this:

    ln -sT ${shared_mime_info}/share/mime $out/share/mime

so that Claws could find `DATAROOTDIR "/mime/globs"` (DATAROOTDIR being `"/nix/store/...-claws-mail-3.11.1/share"`) from C, but I didn't realize it would cause a collision.  The best fix seems to be to use makeWrapper to give `XDG_DATA_DIRS=${shared_mime_info}/share` to Claws similar to @nckx's 40503a2e, except that Claws includes its own MIME parser that doesn't search XDG_DATA_DIRS, so I'll have to punch this path through harder.

(It would be nice if the conflict resolution algorithm detected when one path is a symlink to the other though.)

[self-assign]

**Comment by lethalman** [comment]
Or just give a different priority to the claws derivation in the meta.

**Comment by vcunat** [comment]
Yes, that's probably the easiest work around.

BTW, not respecting the XDG dirs seems a violation of the freedesktop specs for MIME by claws.

**Comment by lethalman** [comment]
Yes most of that mime stuff is in glib/gio nowadays.

**Comment by khumba** [comment]
Yep, it's a known bug.  I haven't tried the attached patch to add
proper XDG support.

http://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=2850

Could set the priority.  For a "proper" fix I'd prefer to patch the
path in if that's alright since priority is somewhat magic and since
it's a link we're explicitly creating that's causing problems.
Thoughts?

**Comment by lethalman** [comment]
If it works with the priority, go for the priority.

**Comment by khumba** [comment]
Alright, sounds good.
