### ISSUE TITLE
Allow `Cutter` to use Python plugins

### ISSUE THREAD

**Issue by Pamplemousse** [NixOS/nixpkgs#101511]
One cannot use Python plugins with [`radare2-cutter`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/analysis/radare2/cutter.nix).

As stated in [their documentation](https://cutter.re/docs/plugins):
> The support for Python plugins is only available if Cutter was built with the options CUTTER_ENABLE_PYTHON and CUTTER_ENABLE_PYTHON_BINDINGS enabled.

**Comment by Pamplemousse** [comment]
I tried to add it myself, but after making very tiny progress, I can't figure why the compilation is stubbornly failing, and feel completely stuck...
What I have so far is available here: https://github.com/Pamplemousse/nixpkgs/tree/cutter .

Any suggestions @Mic92, @dtzWill?
Thanks!

**Comment by Mic92** [comment]
@Pamplemousse Could you open this as a PR? Than I can checkout the branch and push fixes as necessary.

**Comment by Pamplemousse** [comment]
@Mic92 Done!
See #101571 .

**Comment by Mic92** [comment]
I amended the PR.

**Comment by Pamplemousse** [comment]
Closing because NixOS/nixpkgs#101571 has been merged.
