### ISSUE TITLE
How to change/override the default clang compiler of stdenv globally?

### ISSUE THREAD

**Issue by nasyxx** [NixOS/nixpkgs#101662]
Hi, I would like to change the default clang compiler to clang_10 on macOS.  

I used this overlay first, but an infinite recursion appeared.

```nix
self: super:

{
  stdenv = super.overrideCC super.stdenv super.clang_10;
}
```

Currently, I use this overlay:

```nix
self: super:

{
  clangStdenv = super.overrideCC super.clangStdenv super.clang_10;
}
```

However, it not worked as except.

Can someone help me to override the default compiler of stdenv globally?

**Comment by veprbl** [comment]
In #38552 I had nixpkgs imported twice to get this working

cc @nbp regarding how one could do this with only an overlay

**Comment by nasyxx** [comment]
> In #38552 ...

Thank you!

I noticed that issue. But it is more to cover a specific package, rather than to change everything that uses stdenv or clangStdenv.

I guess if there is a temporary solution for the clang part in #40015, it will be great.

**Comment by Artturin** [comment]
https://nixos.wiki/wiki/Using_Clang_instead_of_GCC#Globally.2C_in_a_package_repository_tree
