### ISSUE TITLE
ecl: fails to build on MacOS

### ISSUE THREAD

**Issue by purcell** [NixOS/nixpkgs#101615]
**Describe the bug**

ECL (Embedded Common Lisp) supports MacOS. The derivation is marked `platforms.linux`, so I tried switching it to `platforms.unix` and encountered a mysterious build failure which I'd love to get help tackling.

**To Reproduce**
1. Switch meta.platforms from linux to unix
2. On MacOS: `nix-build -A ecl`

**Expected behavior**
Successful build.

**Additional context**
```
;;; Loading "/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/cmp/cmpstructures.lsp"
;;; Loading "/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/cmp/cmparray.lsp"
;;; Loading "/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/cmp/cmpos-run.lsp"
;;; Loading "/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/cmp/cmpos-features.lsp"

Condition of type: SIMPLE-READER-ERROR
Reader error in file #<input stream #P"/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/cmp/cmpos-features.lsp" 0x1028c8460>, position 5961:
Unmatched right parenthesis, #\)
No restarts available.

Top level in: #<process TOP-LEVEL 0x101430f80>.
>

Condition of type: SIMPLE-FILE-ERROR
Stream cannot be closed
C library explanation: Invalid argument.
No restarts available.

Top level in: #<process TOP-LEVEL 0x101430f80>.
>
/nix/store/8i9kyqfxhk2s9dzx32x0sgdk7kyx9wjc-bash-4.4-p23/bin/bash: line 0: cd: /private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/../.git: No such file or directory
tags generation failed, but this does not break the build.
make[2]: Entering directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build/doc'
cp -r /private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/doc/manual .
make MAKEINFO=/nix/store/aq2g8s6xqij7pmga75gvavj0c4zw3ybd-texinfo-6.7/bin/makeinfo -C manual info
make[3]: Entering directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build/doc/manual'
/nix/store/aq2g8s6xqij7pmga75gvavj0c4zw3ybd-texinfo-6.7/bin/makeinfo --no-split manual.txi
./macros.txi:135: warning: redefining Texinfo language command: @seealso
gzip < ecl.info > ecl.info.gz
make[3]: Leaving directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build/doc/manual'
make[2]: Leaving directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build/doc'
make[1]: Leaving directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build'
installing
install flags: SHELL=/nix/store/8i9kyqfxhk2s9dzx32x0sgdk7kyx9wjc-bash-4.4-p23/bin/bash install
cd build; make install
make[1]: Entering directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build'
install: cannot stat 'bin/ecl': No such file or directory
make[1]: *** [Makefile:197: install] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/build'
make: *** [Makefile:79: install] Error 2
note: keeping build directory '/private/tmp/nix-build-ecl-20.4.24.drv-2'
builder for '/nix/store/a7969brpj5c59xpnkri3lc421031m2fd-ecl-20.4.24.drv' failed with exit code 2
error: build of '/nix/store/a7969brpj5c59xpnkri3lc421031m2fd-ecl-20.4.24.drv' failed
```
of which the real problem seems to be:
```
Reader error in file #<input stream #P"/private/tmp/nix-build-ecl-20.4.24.drv-2/ecl-20.4.24/src/cmp/cmpos-features.lsp" 0x1028c8460>, position 5961:
Unmatched right parenthesis, #\)
```
If the position in that error is to be taken literally, it is in the snippet
```lisp

(defun update-compiler-features (&rest args)
  (setf *compiler-features* (apply #'gather-system-features args)))

#+ecl-min
(update-compiler-features
 :executable
 #+(or windows cygwin mingw32) "build:ecl_min.exe"
 #-(or windows cygwin mingw32) "build:ecl_min")

#+ecl-min
(format t ";;; System features: ~A~%" *compiler-features*)
```
and specifically the closing paren in the line
```
 #+(or windows cygwin mingw32) "build:ecl_min.exe"
```
Unsure how best to investigate this further. :-/

**Notify maintainers**

@7c6f434c 

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(steve): `"darwin, nixpkgs-21.03pre246624.cfed29bfcb2"`
 - channels(root): `"darwin, master.tar.gz"`
 - nixpkgs: `/Users/steve/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - ecl
# a list of nixos modules affected by the problem
module:
```

**Comment by 7c6f434c** [comment]
Oh wow. No idea how to debug it, indeed. Did you check if there is any difference in build instructions between macOS and Linux upstream?

**Comment by purcell** [comment]
> Did you check if there is any difference in build instructions between macOS and Linux upstream?

There are no differences in instructions, but I think some assumptions are made based on the host system. For example, the Nix `stdenv` on Darwin uses `clang` instead of `gcc`, so one thing I tried was switching to `gccStdenv` explicitly, just in case `gcc` was assumed: this then fails because some of the Apple core header files are needed, and only clang on Mac has them. So apparently `clang` is assumed on MacOS.

But, an idea: hey @dkochmanski, do you have a guess at what might be happening here, based on the info in the issue above?

**Comment by dkochmanski** [comment]
all I can say it is that it has some relation to osx:
https://gitlab.com/embeddable-common-lisp/ecl/-/issues/600

**Comment by purcell** [comment]
Hmm, thanks for the pointer. Glad it's not just me seeing this, even if it *is* still rather mysterious...

**Comment by 7c6f434c** [comment]
Maybe someone could trace and see what are the file operations in question? Just to make sure `read`'s return what they should etc.

**Comment by purcell** [comment]
Latest version builds on MacOS, so this issue is resolved.
