### ISSUE TITLE
Hold NixOS release retrospective

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#101789]
Some of the larger pain points already have some related threads around their discussion. https://discourse.nixos.org/t/what-should-stable-nixos-prioritize/9646

However, it would be nice for people to voice their opinion on pain-points (both large and small) felt across the community. 

The goal of the retrospective would be to find ways to improve the process: from people contributing to the process, schedules, tasks, human processes, etc.

cc @worldofpeace

**Comment by worldofpeace** [comment]
Yeah, I can organize this and followup with a Discourse thread with What/When/Where/How

**Comment by jonringer** [comment]
retro was held, closing. you can read about the outcomes: https://discourse.nixos.org/t/20-09-release-retrospective/9851
