### ISSUE TITLE
latte-dock broken after update

### ISSUE THREAD

**Issue by leo60228** [NixOS/nixpkgs#101756]
**Describe the bug**
After updating between two unstable versions, latte-dock no longer shows open applications. Widgets and pinned applications still display, but will always open a new instance.

**To Reproduce**
1. Install `latte-dock`
2. Start `latte-dock`

**Expected behavior**
I expect latte-dock to show my open applications.

**Screenshots**
![image](https://user-images.githubusercontent.com/8355305/97174643-bd9aab80-1768-11eb-8cf7-b8cfa6a5fd97.png)

**Additional context**
None.

**Notify maintainers**
@benley @ysndr

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.1, NixOS, 21.03pre248236.bd017760509 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-21.03pre248236.bd017760509, unstable-20.09pre239228.bd0e645f024"`
 - channels(leo60228): `"unstable-21.03pre248170.007126eef72"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: latte-dock
# a list of nixos modules affected by the problem
module:
```

**Comment by leo60228** [comment]
Building with `libsForQt514` works.

**Comment by rimmington** [comment]
Ran into this after upgrading to 20.09. Fixed by building with `libsForQt512`; I guess `unstable` is ahead of 20.09 there.

```
latte-dock = pkgs.libsForQt512.callPackage <nixpkgs/pkgs/applications/misc/latte-dock> {};
```

**Comment by leo60228** [comment]
This seems to have been fixed.
