### ISSUE TITLE
Cannot enable Quassel service due to renamed dependency

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixpkgs#10175]
So sorry if this is NixOS and should be reported else where. Please let me know if this is the case.

I can no longer enable the Quassel service via the NixOS option `services.quassel.enable = true;` as one of the dependencies have been renamed or something I think. I am getting this error:

    error: attribute ‘quasselDaemon_qt5’ missing, at /nix/store/aaj1k56gqaqr8dlmgfahxbs7l3953g29-nixos-16.03pre69762.e916273/nixos/nixpkgs/nixos/modules/services/networking/quassel.nix:6:13

Which refers to this line:

    quassel = pkgs.quasselDaemon_qt5;

**Comment by vcunat** [comment]
Fixed by d323fa9f8b.

**Comment by Nekroze** [comment]
Thanks!
