### ISSUE TITLE
google-chrome-beta has broken libxkbcommon dependency

### ISSUE THREAD

**Issue by terinjokes** [NixOS/nixpkgs#101782]
**Describe the bug**
Google Chrome Beta no longer launches after upgrading to 87.0.4280.27.

**To Reproduce**
```
$ /nix/store/l1z222qw89s3m61s2nbgddbwnfsml2k9-google-chrome-beta-87.0.4280.27/bin/google-chrome-beta
/nix/store/l1z222qw89s3m61s2nbgddbwnfsml2k9-google-chrome-beta-87.0.4280.27/share/google/chrome-beta/google-chrome-beta: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory

$ ldd /nix/store/l1z222qw89s3m61s2nbgddbwnfsml2k9-google-chrome-beta-87.0.4280.27/share/google/chrome-beta/chrome | grep libxkbcommon
	libxkbcommon.so.0 => not found
	libxkbcommon.so.0 => /nix/store/s33b1nhsq929l17j1i1kq8838aycim0g-libxkbcommon-0.10.0/lib/libxkbcommon.so.0 (0x00007f9eddec5000)
```

**Expected behavior**
Google Chrome Beta should launch.

**Notify maintainers**
@msteen @colemickens 

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.03.3178.a26e92a67d8 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3178.a26e92a67d8, unstable-21.03pre248308.5d0e2dedd55"`
 - channels(terin): `"home-manager-20.03, unstable-21.03pre248308.5d0e2dedd55"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
Hm, that's strange, especially since `libxkbcommon.so.0` appears twice in the output. I cannot reproduce this with 3088dcb148e8110aa6102e8c3a2c7ee5af1348f1 (`master`). Chrome 87.0.4280.27 launches successfully and the `ldd` output looks as expected:
```console
$ ldd /nix/store/1f3lnwc9ddbrlywdd9qlljx1gq52s504-google-chrome-beta-87.0.4280.27/share/google/chrome-beta/chrome | grep libxkbcommon
	libxkbcommon.so.0 => /nix/store/6hgr3wgfzyqqskr2h9nlz6lhwahvjpig-libxkbcommon-0.10.0/lib/libxkbcommon.so.0 (0x00007feaefcb8000)
```

Not sure what's causing the problem in your case.

**Comment by terinjokes** [comment]
It looks like `/nix/store/l1z222qw89s3m61s2nbgddbwnfsml2k9-google-chrome-beta-87.0.4280.27` was coming from the 20.03 release channel, where perhaps some infrastructure hasn't been backported?

Both nixos-unstable (which is currently behind 20.03) and master have working builds.

```
$ ldd /nix/store/apixpwmicmn5rhcmyx49l0pfnjplxb0f-google-chrome-beta-87.0.4280.20/share/google/chrome-beta/chrome | grep libxkbcommon
	libxkbcommon.so.0 => /nix/store/6hgr3wgfzyqqskr2h9nlz6lhwahvjpig-libxkbcommon-0.10.0/lib/libxkbcommon.so.0 (0x00007fc078b29000)
```

**Comment by terinjokes** [comment]
Well, 20.09 is out. Closing this ;)

**Comment by primeos** [comment]
@terinjokes oh, I missed that this was on 20.03. I backported the fix in 6b5f85a62c445c14ca344bbe0de66927b13e0c20 in case anyone needs it during the one month transition period. Thanks for the report :)

**Comment by panchoh** [comment]
Hi!

It seems that the fix did not end up in the `release-20.09` branch, so it's broken again :-(

Can we fix it here, or should we open a new issue?

Thanks!

**Comment by primeos** [comment]
Oh, indeed :o I've backported it in bfa81f72dee6184b32d765f0ce933733dd9d111d, thanks!

**Comment by panchoh** [comment]
> Oh, indeed :o I've backported it in [bfa81f7](https://github.com/NixOS/nixpkgs/commit/bfa81f72dee6184b32d765f0ce933733dd9d111d), thanks!

Thanks to you!
