### ISSUE TITLE
Packaging request ptouch

### ISSUE THREAD

**Issue by jparris** [NixOS/nixpkgs#101712]
**Project description**
 ptouch is a command line tool to print labels on Brother P-Touch printers on Linux.

The printer is accessed directly using libusb, so there is no need to install the printer in CUPS.

Currently supported Brother label printers
- PT-2420PC
- PT-1230PC
- PT-2430PC
- PT-2730 (was reported to need 48 blank lines before actual content)
- PT-E500 (was reported to need some padding white pixels)
- PT-D450

**Metadata**

* homepage URL: https://mockmoon-cybernetics.ch/computer/p-touch2430pc/
* source URL: https://mockmoon-cybernetics.ch/cgi/cgit/linux/ptouch-print.git
* license: gpl3 https://mockmoon-cybernetics.ch/cgi/cgit/linux/ptouch-print.git/tree/COPYING
* platforms:  linux

**Comment by esclear** [comment]
Closing this, as `ptouch` has been packaged.
