### ISSUE TITLE
Atom plugin cannot find shared libraries

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#10172]
I installed the atom package, and tried using the atom-typescript plugin that I installed through the executable (plugins are not packaged separately as far as I can tell).

Now the plugin is failing, and opening the Developer Console (Ctrl+Shift+I), it seems that it fails at opening libgtk-x11-2.0.so.0:

CHILD ERR STDERR /nix/store/f8b67[...]7p-atom-1.0.4/share/atom/atom: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object files: No such file or directory

The rest of the editor works fine.

Looking at
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/atom/default.nix
it seems like the proper path for the lib is there `${atomEnv}/lib`.

I am not familiar with how plugins run so I'm not sure what else to add to this report.

System: NixOS 15.09

Steps to reproduce:
    $ nix-env -i atom
    $ apm install atom-typescript
    $ atom
Within atom, you can do Edit > Preferences > Packages to see the atom-typescript package. Whenever you enable it, the console (Ctrl+Shift+I) will complain about the shared library.

**Comment by domenkozar** [comment]
We currently use debian package and just provide our libraries to it. See https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/atom/default.nix#L10

Not sure what package libgtk-x11 is coming from

**Comment by Ptival** [comment]
@domenkozar I thought libgtk-x11 was actually part of the gtk package, which is why the error was surprising to me.

I wonder whether atom somehow alters the environment for some of its subprocesses.

**Comment by Ptival** [comment]
For anyone with this issue, as a temporary workaround, one can disable asynchronous processing in atom-typescript by editing `debugSync` to `true` in `lib/worker/debug.ts`.

This makes the plugin usable, but it would still be interesting to fix the spawning environment so that it is properly nix-wrapped.

**Comment by Ptival** [comment]
This was indeed an atom-typescript issue, fixed by https://github.com/TypeStrong/atom-typescript/commit/516374197f4642ec56ff87958dbb2620ebc4f761
