### ISSUE TITLE
nixosTests.installer crashes with "Killed"

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#101732]
on master and `release-20.09`, `nixosTests.installer` just crashes with the error message "Killed"

```
[19:53:01] jon@jon-desktop /home/jon/projects/nixpkgs (master)
$ nix-build -A nixosTests.installer
Killed
```

EDIT:
looking at `dmesg`, it appears that the tests gets oom killed
```
[138162.538415] Out of memory: Killed process 7644 (nix-build) total-vm:6261432kB, anon-rss:6095456kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:12088kB oom_score_adj:0
[138162.660588] oom_reaper: reaped process 7644 (nix-build), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
Appears that the evaluation is spiking to 6GB+, and then gets oom_killed.

EDIT 2:
I can run it on my server, which has 256GB. I guess 16GB with apps running isn't enough RAM :(

**Comment by jonringer** [comment]
I guess this is more about how module evaluation is becoming a huge RAM hog...

**Comment by worldofpeace** [comment]
Yeah, those installer tests with QEMU EAT RAM. I think this took down hydra in 20.03 but with some quick thinking we found a way to make that continue to work. But yeah, I think for sure all those installer tests could not run on 16GIB, the oom killer for sure saved u.

**Comment by jonringer** [comment]
also, look like `nixosTests.installer` is actually a set of ~15 tests....

**Comment by jonringer** [comment]
no longer relevant
