### ISSUE TITLE
Post 20.09 cleanup

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#101863]
- [x] Add metadata around kernel "flavors" (e.g. zen, xen, hardened) to allow for easier conditional `meta.broken` cc @NeQuissimus 
  - [x] backport changes, and then mark appropriate linux modules as broken
- [ ] go through the failing nixosTests, mark failing tests as broken
- [x] "forward port" some of the python breakages. https://github.com/NixOS/nixpkgs/commit/87b50c25ba9f67c918353226fb202a75ea090e59

**Comment by NeQuissimus** [comment]
I am looking at allowing the `broken` (or any metadata for that matter) from within `all-packages.nix`. Is that what you are thinking, @jonringer ?

**Comment by jonringer** [comment]
I was more taking inspiration from pythonPackages. Where you ask `python3Packages.isPyPy` or something like that. In the case of kernels, it would be `linuxPackages.isZen` or `linuxPackages.kernel.isZen`. And so this way on kernel modules, I could something like:
```
  meta.broken = with kernel; isHardened || isZen || isXen;
```

**Comment by jonringer** [comment]
for more context, the remaining modules i need to mark broken are listed: https://github.com/NixOS/nixpkgs/issues/100111#issuecomment-716957919

**Comment by jonringer** [comment]
My initial impression is that we have something like:
```
  passthru = {
    isZen = false;
    isXen = false;
    isHardened = false;
    isLibre = false;
  };
```
and just override what is true in the various flavors

**Comment by NeQuissimus** [comment]
Ah, I see, this is more about the kernel modules. Makes sense. I won't be able to do this immediately but we should do this, for sure.

**Comment by andir** [comment]
I just updated a system to the latest 20.09 channel version and realized the `libtensorflow-bin` package has been marked as broken even thought it builds just fine (and is actually cached by hydra). What metric did you use to decide something should be broken? (I somehow lost track of the conversation across multiple issues & PRs).

**Comment by jonringer** [comment]
@andir I went off https://hydra.nixos.org/eval/1622004?full=1#tabs-still-fail

looks like it was an accidental casualty when marking the python tensorflow packages as broken.

**Comment by jonringer** [comment]
> Ah, I see, this is more about the kernel modules. Makes sense. I won't be able to do this immediately but we should do this, for sure.

I'll try to make a PR when I have free time

**Comment by andir** [comment]
> @andir I went off https://hydra.nixos.org/eval/1622004?full=1#tabs-still-fail
> 
> looks like it was an accidental casualty when marking the python tensorflow packages as broken.

Alright. I'll open a PR to mark it unbroken.

**Comment by jonringer** [comment]
ive done that before in a "this week in nix" PR

**Comment by jonringer** [comment]
@NeQuissimus do you mind taking a quick look at the PR?

**Comment by jonringer** [comment]
A lot of my forward ports for python are captured in https://github.com/NixOS/nixpkgs/pull/101636, checking that off
