### ISSUE TITLE
Build and cache cross-compile toolchains in cache.nixos.org

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#101814]
**Describe the bug**

More of a feature request. I use nix-shell for development on a project that uses MinGW to cross-compile from linux to windows. To get this toolchain, my shell.nix references `pkgsCross.mingwW64.buildPackages.gcc` and `pkgsCross.mingw32.buildPackages.gcc` as buildInputs.

Unfortunately these toolchains aren't built by hydra, so cache.nixos.org misses, and I have to compile 2 full gcc toolchains on my poor little laptop :(.

It would be nice to have at least C toolchains built for every cross-platform that nixpkgs supports, so that folks doing cross-development can get up and running quickly.

**To Reproduce**

1. Create a shell.nix that pulls in `pkgsCross.mingwW64.buildPackages.gcc` and `pkgsCross.mingw32.buildPackages.gcc` as buildInputs.
2. Run `nix-shell`. Observe that you're now compiling two full gcc toolchains before you can do anything.

**Expected behavior**

nix-shell should find a cache hit for those packages, and let me start hacking quickly :).

**Additional context**

My first impulse was to send a PR adding `mingw64 = pkgsCross.mingwW64.buildPackages.gcc` and `mingw32 = pkgsCross.mingw32.buildPackages.gcc` to all-packages.nix, but @samueldr suggested this would not be the correct approach. So I'm filing this issue to get some guidance on how we could get cross-compiler derivations cached correctly.

Note that some cross-compilers do get cached, as a side-effect of being pulled in as deps of either Mobile NixOS or various arm/avr tools that need access to a cross-compiler. Unfortunately, nixpkgs doesn't have anything that depends on a windows cross-compiler in all-packages.nix, so the mingw packages aren't getting cached.

While I personally care about mingw, it would probably be nice to provide cached cross-compilers for all target hosts that nixpkgs supports.

**Notify maintainers**

I have no idea who this is :/ I was told to @edolstra for wisdom on how to structure things correctly, but I don't know who else is an expert on the pkgsCross corner of the universe.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by expipiplus1** [comment]
> but I don't know who else is an expert on the pkgsCross corner of the universe.

@Ericson2314 springs to mind :D

**Comment by siraben** [comment]
There are some other toolchains built by hydra, see https://hydra.nixos.org/jobset/nixpkgs/cross-trunk. The right place to add more packages to this jobset is by adding them to `pkgs/top-level/release-cross.nix`. As an example,

```ShellSession
$  nix build .#pkgsCross.sheevaplug.ed
```

fetches the cross-compiled `ed` immediately for me on `x86_64-darwin`.

**Comment by danderson** [comment]
This was fixed some time ago, pulling mingw no longer forces a slow rebuild.
