### ISSUE TITLE
Noto CJK Font only as TTC or OTF available

### ISSUE THREAD

**Issue by phoco** [NixOS/nixpkgs#10182]
We do need the Noto CJK Fonts package optimized as TTF. files. It is not possible, as I know, to embedded nor OTF either TTC font files into PowerPoint (Version 2013). Could do you help me? Any recommendation? How we can handle the Noto Fonts for embedding in PowerPoint

**Comment by Mathnerd314** [comment]
Google doesn't provide the fonts as TTF; I would recommend asking them in https://github.com/googlei18n/noto-cjk/issues/45.
