### ISSUE TITLE
Murmur can't read generated acme keys in 20.09

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#101980]
**Describe the bug**
* The acme module lost the abitlity to set a generated certs/keys uid, only sets gid since https://github.com/NixOS/nixpkgs/pull/91121#pullrequestreview-510714303
* The murmur module only runs with `nogroup`

**Expected behavior**
The modules should fit together, preferably by the murmur module setting a proper gid.

**Notify maintainers**

@petabyteboy
@infinisil 

@NixOS/acme

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.3113.d74573d8ae6 (Markhor)`
 - multi-user?: `yes`
^[[B^[[B^[[B - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20200829_f156513`
 - channels(root): `"nixos-20.09.1469.13d0c311e3a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: [ services.murmur, security.acme ]
```

**Comment by lheckemann** [comment]
+1 for giving murmur a proper gid, stuff definitely shouldn't be running as nogroup anyway.
