### ISSUE TITLE
zsh-powerlevel10k broken with latest update

### ISSUE THREAD

**Issue by AluisioASG** [NixOS/nixpkgs#101946]
**Describe the bug**

zsh-powerlevel10k depends on an exact version on gitstatus ([v1.2.0 for the latest release](https://github.com/romkatv/powerlevel10k/blob/v1.13.0/gitstatus/build.info#L6)). The recent update of both packages just updated both to the latest releases without checking compatibility.

**To Reproduce**
1. Use and set up zsh-powerlevel10k via `${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme`
2. See an `[ERROR]: gitstatus failed to initialize.` every time you open a shell

**Expected behavior**
zsh-powerlevel10k should be paired with the correct version of gitstatus, **probably with an assertion to enforce it**. I think we can either **hold back gitstatus updates**, or **keep around a version that works** with powerlevel10k.

**Notify maintainers**
@mmlb @mweinelt

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.104-microsoft-standard, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20201020_e0ca98c`
 - channels(aasg): `"nixos-20.03-20.03.3185.6b5f85a62c4, nixos-20.09-20.09.1489.6a5fea37550, nixos-unstable-21.03pre249162.1dc37370c48, nixpkgs-21.03pre248787.7ad5e816fab"`
 - nixpkgs: `/home/aasg/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
attribute: [ "gitstatus", "zsh-powerlevel10k" ]
```

**Comment by mweinelt** [comment]
Thanks for your report, I've created a pull request including a fix.

**Comment by andrevmatos** [comment]
It seems this same issue has appeared on latest master:
```
...
    +_gitstatus_set_daemon_p9k_:1> _gitstatus_zsh_daemon=/nix/store/w7wqb0yrxc6xy7qm9d2a1mvgcjxmr3q4-gitstatus-1.3.1/bin/gitstatusd 
    +_gitstatus_set_daemon_p9k_:2> _gitstatus_zsh_version=v1.5.1 
    +_gitstatus_set_daemon_p9k_:3> _gitstatus_zsh_downloaded=0 
    +_gitstatus_install_main:157> return
    +_gitstatus_daemon_p9k_:49> [[ -n /nix/store/w7wqb0yrxc6xy7qm9d2a1mvgcjxmr3q4-gitstatus-1.3.1/bin/gitstatusd ]]
    +_gitstatus_daemon_p9k_:50> [[ -n v1.5.1 ]]
    +_gitstatus_daemon_p9k_:51> [[ 0 == [01] ]]
    +_gitstatus_daemon_p9k_:53> ((  UID == EUID  ))
    +_gitstatus_daemon_p9k_:54> local home=/home/admin
    +_gitstatus_daemon_p9k_:62> [[ -x /nix/store/w7wqb0yrxc6xy7qm9d2a1mvgcjxmr3q4-gitstatus-1.3.1/bin/gitstatusd ]]
    +_gitstatus_daemon_p9k_:63> HOME=/home/admin /nix/store/w7wqb0yrxc6xy7qm9d2a1mvgcjxmr3q4-gitstatus-1.3.1/bin/gitstatusd -G v1.5.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 16
    Version mismatch. Wanted (pattern): "v1.5.1". Actual: "v1.3.1".
    +_gitstatus_daemon_p9k_:64> local -i ret=11
    +_gitstatus_daemon_p9k_:65> [[ 11 == (0|129|130|131|137|141|143|159) ]]
    +_gitstatus_daemon_p9k_:68> ((  ! _gitstatus_zsh_downloaded  ))
    +_gitstatus_daemon_p9k_:69> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:70> [[ /nix/store/w7wqb0yrxc6xy7qm9d2a1mvgcjxmr3q4-gitstatus-1.3.1/bin/gitstatusd == /home/admin/.cache/gitstatus/* ]]
    +_gitstatus_daemon_p9k_:71> return
    +_gitstatus_daemon_p9k_:84> local -i ret=1
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /tmp/gitstatus.POWERLEVEL9K.1000.4868.1624225441.2.lock /tmp/gitstatus.POWERLEVEL9K.1000.4868.1624225441.2.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -5045
```
