### ISSUE TITLE
ipython lacks readline & colours support

### ISSUE THREAD

**Issue by gfxmonk** [NixOS/nixpkgs#10190]
I'm guessing this happened during 4.0 / jupyter upgrade. Running `ipython` (from `pythonPackages.ipython`) gives:

    $ /nix/store/hims3s84qgr9dnmvwr021yd9r7wr7620-python2.7-ipython-4.0.0/bin/ipython
    WARNING: Readline services not available or not loaded.
    WARNING: The auto-indent feature requires the readline library
    Python 2.7.10 (default, Jan 01 1970, 00:00:01) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    >>> 

Tab completion / readline doesn't work, and the prompt has no colours any more (I don't know whether this is due to `readline` missing or a separate issue).

/cc @FRidh

**Comment by FRidh** [comment]
Thanks for your report. readline is indeed missing, causing both tab completion not to work and not showing any colors. I'll add the dependency.
