### ISSUE TITLE
ACME module hitting account rate limits due to simultaneous cert creation

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#101981]
**Describe the bug**
If many certs services are started at once, they may fail and run into an account limit. @m1cr0man suspects this could be because they're writing the account data simultaneously, corrupting it.

**To Reproduce**
1. Boot a new server with several certs configured, all with the same email address, which hasn't yet generated any of them. I had 11.

**Expected behavior**
A single account is registered and used for all of the certs.

**Screenshots**

```
Oct 28 20:59:50 sosiego acme-$domain-start[20064]:         acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/, url:
```

**Notify maintainers**
@NixOS/acme 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1469.13d0c311e3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-19.09.1300.08e503bac6d"`
 - nixpkgs: `/var/lib/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by m1cr0man** [comment]
I also suspect this could be the real cause of #101445. It could be that if you have multiple certs configured, both write the account data to disk at the same time and thus form a corrupt JSON blob. I will write some tests for this at the weekend and see what is happening. It's likely we will need to implement a lock over "lego run" executions

**Comment by m1cr0man** [comment]
That's not a bad idea but the only way to do it is still to run lego, so I would need some sort of dummy domain to hit ACME with, and doing that on all Nix hosts worldwide might be a bit undesirable ;) 

My initial plan was to make all certs sharing an account folder depend on the first cert declared. In theory that would solve the issue but it assumes that none of the other certs make any writes at all and I don't know enough about lego's inner workings to know that. This would also affect your solution.

The solution proposed in #102387 utilising systemd mutexes (muticies? muti?) should solve the issue. I'll make sure there's a test for a multi-cert renew there too.

**Comment by m1cr0man** [comment]
Hey! This is now a solved issue :) I implemented a system of [account targets](https://github.com/NixOS/nixpkgs/blob/4e55c8bc6703699a016093e9bf745bd713bcdfba/nixos/modules/security/acme.nix#L744) (`acme-account-${hash}.target`) a while back to prevent multiple simultaneous account registrations and [a test](https://github.com/NixOS/nixpkgs/blob/4e55c8bc6703699a016093e9bf745bd713bcdfba/nixos/tests/acme.nix#L365) to cover it. It also stops registration spam to Let's Encrypt if for some reason registration fails on the "leader" certificate. You can still hit rate limits if you have > 5 unique email addresses configured, but that is a configuration problem that the user can solve. I'm going to close this issue now but if you see it happening again let me know.
