### ISSUE TITLE
20.03 EOL on November 27th

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#101975]
**Describe the bug**
Our new stable release 20.09 Nightingale has happened on October 27th. Our policy in the manual is to EOL after a month of the new stable release. I've opened this so it's all clear to everyone.

**Comment by roberth** [comment]
@txt-file would you mind elaborating your :-1: ?

**Comment by txt-file** [comment]
@roberth My wish is that 20.03 EOL is postponed until https://github.com/NixOS/nixpkgs/issues/102340 is resolved.
Reason is that I had a bunch of KDE Apps not instilling on 20.09 with errors that breeze is marked broken. This has gotten much better in the time since the release. My feeling is that potential new users who trigger the KDE bugs will run away and never come back. Maybe even dis-recommend NixOS to their friends. I think that would be bad.

**Comment by andir** [comment]
> @roberth My wish is that 20.03 EOL is postponed until #102340 is resolved.
> Reason is that I had a bunch of KDE Apps not instilling on 20.09 with errors that breeze is marked broken. This has gotten much better in the time since the release.

I am sympathize with the wish but I think that is not going to work. Someone (potentially one of the KDE users has to do the work to improve the situation). We are unlikely to hold everything else back (now that 20.09 has been released). Maintaining 20.03 in addition to 20.09 and unstable is more work than we can probably afford to do in the long run.

> My feeling is that potential new users who trigger the KDE bugs will run away and never come back. Maybe even dis-recommend NixOS to their friends. I think that would be bad.

How will new users end up on the "better" release aka 20.03? The downloads on the website are already pointing towards 20.09. The way you reason about this is more suitable for a release blocker - before the release not after.

**Comment by cole-h** [comment]
Today is the day!

Am I right in the assumption that 20.03 will be marked EOL in [`nixos-org-configurations`](https://github.com/NixOS/nixos-org-configurations/blob/df1c37982c348588df5025447987a66272304e43/channels.nix#L35-L46)?

**Comment by dasJ** [comment]
Can we unpin and close this?

**Comment by cole-h** [comment]
I'd say we want https://status.nixos.org/ to show 20.03 as EOL (like it does for 19.09) before we close. This means `eris` probably needs a redeploy? Don't really know how that works.

**Comment by jonringer** [comment]
cc @garbas about 20.03 still showing as current on https://status.nixos.org/

is there something I need to do in conjunction with https://github.com/NixOS/nixos-org-configurations/pull/136

**Comment by jonringer** [comment]
deprecating previous releases isn't currently documented

**Comment by dasJ** [comment]
So do we only have a single person who knows how to change this? :laughing:

**Comment by worldofpeace** [comment]
This has been done for a minute now
