### ISSUE TITLE
p4 in 20.09 needs to be updated to 2020.1.2007551

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#101955]
**Describe the bug**
Current version in 20.09 fails to build due to sha mismatch

**To Reproduce**
1. Install p4

**Expected behavior**
p4 is installed instead of failing to install due to sha mismatch

**Notify maintainers**
@corngood

**Comment by corngood** [comment]
b197c7fb487b12bb8ff6c1e014b5f10ba9ed6edf should be the fix for this

**Comment by corngood** [comment]
This will be an ongoing problem as long as the URLs aren't fully qualified.
