### ISSUE TITLE
virtualbox: Does not work since I'm on kernel 4.*, worked with 3.18.*

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#10203]
I always have to boot into older generations (with kerne 3.18.*) to use virtualbox, which is really annoying me right now.

Since I updated to 4.1.*, vbox is not working anymore and I couldn't test 4.0.* due to build failure for my ati_unfree driver.

Can someone please investigate?

The error is that virtualbox cannot access the kernel driver. When trying `modprobe vboxdrv` it tells me `modprobe: FATAL: Module vboxdrv not found.`

**Comment by matthiasbeyer** [comment]
Just got kernel 4.2 working - same issue here.

**Comment by cransom** [comment]
I'm running 4.1 on a couple boxes and virtualbox (5.0.x) has been working fine for me.  Did you rebuild virtualbox for it to rebuild the kernel modules?

**Comment by matthiasbeyer** [comment]
I guess you're talking about the guest, I'm talking about the host...

**Comment by cransom** [comment]
I'm talking about the host...

**Comment by matthiasbeyer** [comment]
Okay. Well I just enabled the appropriate service... which worked fine for me until the kernel got upgraded - nix should take care of the kernel module rebuild, shouldn't it?

**Comment by matthiasbeyer** [comment]
@cransom How can I rebuild the kernel modules?

**Comment by cransom** [comment]
If virtualbox is enabled in configuration.nix, it should automatically pull
down or rebuild the modules after a nixos-rebuild --switch.  Are you on the
15.09 channel? If not, I'd suggest updating.

**Comment by matthiasbeyer** [comment]
I'm on unstable and no, it seems that this didn't work.

**Comment by matthiasbeyer** [comment]
Can someone please help me with this? I have to boot into a generation which is now *one month old* just to get a working virtual box!

**Comment by bjornfor** [comment]
@matthiasbeyer: Sounds weird, nixos should build everything (like @cransom says). I've recently had some issues with virtualbox lockups on linux 3.18 (https://github.com/NixOS/nixpkgs/issues/9912), but no issues with the ```vboxdrv``` missing (as far as I can tell).

**Comment by matthiasbeyer** [comment]
The solution to this was changing

```
services.virtualbox.host.enable = true;
```

to

```
virtualisation.virtualbox.host.enable = true;
```

---

I'm really curious why the old syntax didn't end up in a syntax error or something like this.

**Comment by uniphil** [comment]
thanks @matthiasbeyer for posting your fix, it's what I needed too!
