### ISSUE TITLE
build-fhs-userenv: add "extraBindMounts" option?

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#10204]
I think it would be useful to have an "extraBindMounts" option, allowing the FHS chroot to see other parts of the system that it currently cannot.

**Comment by bjornfor** [comment]
For example, I have a big disk at /data that I'd like to use from the chroot.

**Comment by bjornfor** [comment]
CC @abbradar.

Do you think it's a good idea? Should it be implemented as an runtime option or a (nix) buildtime option?

**Comment by abbradar** [comment]
Hm, we can even have both (runtime and buildtime, implemented via prepending additional flags). Either way, seems a nice idea! I think I can implement it on Monday evening, of course if you want to take on it sooner I don't mind. Ruby script should be fairly straightforward to modify -- it has a dict of "things to be mounted" somewhere.

**Comment by bjornfor** [comment]
@abbradar: I saw the dict, but I don't know Ruby :-)
If you can have a look, that'd be great.

Mhm, having the Ruby-part take an envvar, which can be initialized/prepended from nix build-fhs-userenv flags (in addition to being set at runtime) sounds nice. Best of both worlds.

**Comment by abbradar** [comment]
Would you prefer flags or an environment variable? IMO second seems more convenient (mount points change rarely)...

**Comment by bjornfor** [comment]
Here is what I imagined:

At runtime:
```
$ EXTRA_BIND_MOUNTS="/data=/host-data /foo" nix-shell -A mychroot  # /foo is the same as /foo=/foo
```

At build-time:
```
  mychroot = (buildFHSUserEnv {
    name = "mychroot";
    pkgs = [ a b c ];
    extraBindMounts = [ "/data=/data" "/foo" ];
  }).env;
```

Or maybe just re-use the "profile" argument?

```
  mychroot = (buildFHSUserEnv {
    name = "mychroot";
    pkgs = [ a b c ];
    profile = ''
      export EXTRA_BIND_MOUNTS="/data=/host-data /foo"
    '';
  }).env;

**Comment by abbradar** [comment]
Nice, let's implement it via an additional option to `buildFHSUserEnv` (`profile` is sourced when we are already inside chroot). I'll take a look later!

**Comment by abbradar** [comment]
@bjornfor done in https://github.com/NixOS/nixpkgs/commit/5897433b3173906c5cd52ba33a5a164eb3de967b, use `CHROOTENV_EXTRA_BINDS` environment variable (I changed the name you proposed to have `CHROOTENV_` as an appendix -- it's somewhat a convention for environment variables). Let's not close this until I also get to document this ^_^.

**Comment by abbradar** [comment]
Format is `/mnt=test-mnt:/data` (mount `/mnt` to `/test-mnt`, mount `/data` to `/data`)

**Comment by bjornfor** [comment]
@abbradar: Sweet!

When it has docs, I'd like to backport to release-15.09.

**Comment by abbradar** [comment]
Done, see https://github.com/NixOS/nixpkgs/commit/fa53fbe086d720998709428f944ef682c6944f6d
