### ISSUE TITLE
Giara - GNOME reddit client

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#102179]
**Project description**
Giara is a A GTK app for Reddit

Announced here: https://new.reddit.com/r/gnome/comments/jkzm68/gnome_developer_creates_a_reddit_client_for_gnome/gamnfn4/?context=3

**Metadata**

* homepage URL: https://giara.gabmus.org/
* source URL: https://gitlab.gnome.org/World/giara
* license: gplv3
* platforms: linux

![image](https://user-images.githubusercontent.com/3998/97747515-7b53d000-1ac2-11eb-92b9-4af3b94279fe.png)

**Comment by fgaz** [comment]
Done in #110939
