### ISSUE TITLE
NixOS AMI Boot Time and Disk Improvements

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#102176]
## Issue description

I hit an issue where I needed a machine's root disk to be larger than 2TB, but that was impossible because we use(d) MBR. It took quite a lot of time, effort, and surgery to bodge a fix in to place. Not wanting to hit this again, it has caused a number of patches fixing various issues I've hit. Ideally, I'd like to backport to 20.09 if @jonringer and @worldofpeace will have it.

- [x] https://github.com/NixOS/nixpkgs/pull/102171 - stage-1: modprobe ext{2,3,4} before resizing (so resizing takes less than 45 minutes)
- [x] https://github.com/NixOS/nixpkgs/pull/102172 - stage-1: add datestamps to logs
- [x] https://github.com/NixOS/nixpkgs/pull/102173 - create-amis.sh: fixup shellcheck issues, improve error logging, and add configurable service names
- [x] https://github.com/NixOS/nixpkgs/pull/102174 - AMI root partition table: use GPT to support >2T partitions (I'd like @samueldr and @cleverca22 to review this one if possible)
- [x] https://github.com/NixOS/nixpkgs/pull/102175 - amazon-image: random.trust_cpu=on to cut 10s from boot

**Comment by jonringer** [comment]
A lot of this sounds backwards compatible. And most users won't notice. I'm okay with it.

**Comment by jonringer** [comment]
Also, thanks for the work, a lot of this seems painful to debug and iterate on. :)

**Comment by worldofpeace** [comment]
Yep, same. Let's put this good work into stable :+1:

**Comment by grahamc** [comment]
Backport is open: https://github.com/NixOS/nixpkgs/pull/102182

**Comment by grahamc** [comment]
Merged. Hopefully once it goes to the channel we can regenerate the AMI.

**Comment by grahamc** [comment]
Backported!
