### ISSUE TITLE
FMOD libraries source unavailable

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs#10213]
in nixpkgs/pkgs/development/libraries/fmod

```
nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'
```

output:

```
these derivations will be built:
  /nix/store/c5idl8j6xmsqdsdcsvin15v2m1asbckx-fmodapi44441linux.tar.gz.drv
  /nix/store/ki3s4civ7f3hy69nd7l651539vfpv2il-fmod-4.44.41.drv
building path(s) ‘/nix/store/s4xq3cvn3p8z803wammqk6ilwyxq74pf-fmodapi44441linux.tar.gz’

trying http://www.fmod.org/download/fmodex/api/Linux/fmodapi44441linux.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
           is unavailable.                      Dload  Upload   Total   Spent    Left  Speed
100  3317  100  3317    0     0   5707      0 --:--:-- --:--:-- --:--:--  8526
output path ‘/nix/store/s4xq3cvn3p8z803wammqk6ilwyxq74pf-fmodapi44441linux.tar.gz’ should have sha256 hash ‘0qjvbhx9g6ijv542n6w3ryv20f74p1qx6bbllda9hl14683z8r8p’, instead has ‘07jkf6m1yd6hzl5vci4nlxnbj9yl34yg86nb9954pghcd51c4nrb’
cannot build derivation ‘/nix/store/ki3s4civ7f3hy69nd7l651539vfpv2il-fmod-4.44.41.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ki3s4civ7f3hy69nd7l651539vfpv2il-fmod-4.44.41.drv’ failed
```

http://www.fmod.org/download/fmodex/api/Linux/fmodapi44441linux.tar.gz seems unavailable. I couldn't find another source.

**Comment by vcunat** [comment]
Looking at http://www.fmod.org/download/, it doesn't seem to be meant to be freely distributable anymore as they apparently require registration.

**Comment by Lassulus** [comment]
so we can either:
-delete the package and the ones that depend on them (which would be only gzdoom afaik)
-host the source our self (and ignore their copyright?)
-or mark it as broken so it won't build anymore.

@thoughtpolice because he seems to be the current maintainer of fmod

**Comment by Mathnerd314** [comment]
More solutions:
4. Use requireFile and recommend creating an account / downloading it yourself
5. Make a curl script to log in with a default Username/Password combination and download it
6. Email them nicely and ask them to make it public again

**Comment by thoughtpolice** [comment]
We should only do either 6), 1) or 4), preferably in that order, IMO. If there was some situation they would be willing to work out that would be great, but in lieu of that I'd prefer to just get rid of it I suppose...

**Comment by Mathnerd314** [comment]
Current ZDoom instructions say to use an archive.org link:
http://zdoom.org/wiki/Compile_ZDoom_on_Linux#Download_FMOD

**Comment by matthewbauer** [comment]
Same issue for the OSX binaries. Dwarf Fortress actually distributes fmod for Mac OS X.

Here's the relevant license section:

> REDISTRIBUTION LICENSE (FMOD EX AND FMOD STUDIO)
> ------------------------------------------------
> IF THE USER WISHES TO REDISTRIBUTE FMOD AS PART OF AN ENGINE OR TOOL SOLUTION,
> THE USER MUST APPLY TO FIRELIGHT TECHNOLOGIES TO BE GRANTED A 'REDISTRIBUTION
> LICENSE'.  
> TO APPLY FOR THIS LICENSE WRITE TO SALES@FMOD.COM WITH THE RELEVANT DETAILS.

**Comment by abbradar** [comment]
https://github.com/NixOS/nixpkgs/pull/21231 removes FMOD from top-level nixpkgs (it's still required for zandronum but they have their own package).
