### ISSUE TITLE
NixOS 20.09 will not work on the current gen of Dell XPS 13 (kernel regression)

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#102190]
I’m sorry, maybe I should have raised this issue _before_ the release (🙂), but there was a regression introduced in Linux 5.4, which breaks firmware loading on Intel Killer(R) Wi-Fi 6 AX1650i. It was fixed in 5.6. [Ubuntu issue](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1865962) – they backported the fix into their 5.4 kernel.

I don’t think there is a list of devices that NixOS is supposed to work on, but, I imagine, if there was one, Dell XPS 13 would definitely get on it, being one of the few officially-Linux laptops. Anyway, I don’t know what would be the best fix here, as backporting kernel patches is not a lot of fun, and I don’t know what the policy regarding bumping `kernelPackages` is.

I tried to throw in a bunch of keywords into this description, so that if someone googles for this, they find this issue. I also noticed that there is a `minimal-new-kernel` ISO, that would greatly help in getting NixOS initially installed on this laptop, but I couldn’t find it on Hydra, so it would be great if someone could post a link here.

**Comment by kirelagin** [comment]
(Oh, and just to clarify, this is, technically, _not_ a regression in NixOS, since 20.03 used the same broken 5.4 branch.)

**Comment by eadwu** [comment]
So it does work, but wifi is broken is what you mean?

If the ISO doesn't even boot that's probably some other issue as well that may be related.

**Comment by kirelagin** [comment]
Well, yes, your a right, it works but the wifi is broken.

_Although, I would say, it depends on your definition of “works”. I believe, for a laptop, if the installation of an OS cannot be done without a wired connection, that is pretty much “does not work”. Well, I suppose, it can be installed using the graphical ISO, but, again, there will be no way to get it into a “working wifi” state without a wired connection and manually overriding kernel packages._

**Comment by jonringer** [comment]
not a great solution, but you can also generate an installer iso from a configuration.nix, and just specify a later version in the configuration.

https://nixos.wiki/wiki/Creating_a_NixOS_live_CD

to create a graphical installer using the latest kernel
```
# iso.nix
{config, pkgs, ...}:
{
  imports = [
    <nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-graphical-plasma5-new-kernel.nix>

    # Provide an initial copy of the NixOS channel so that the user
    # doesn't need to run "nix-channel --update" first.
    <nixpkgs/nixos/modules/installer/cd-dvd/channel.nix>
  ];
}
```
```
nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix
```
