### ISSUE TITLE
systemsettings5 / KDE config broken with update to 20.09

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#102253]
**Describe the bug**
I've update to NixOS 20.09
in KDE config, some configuration tabs are broken displaying the message
`undefined symbol: _ZN3KIO32UntrustedProgramHandlerInterface16staticMetaObjectE`

i've searched (`rg UntrustedProgramHandlerInterface16staticMetaObjectE /nix ~/.cache/ ~/.config/ ~/.local/`) this string but found nothing

**To Reproduce**
1. have a working configuration with NixOS 20.03
2. upgrade to NixOS 20.09
3. it's broken

**Expected behavior**
KDE config should be available and working

**Screenshots**

![Screenshot_20201031_182205](https://user-images.githubusercontent.com/6325757/97786013-d95ae300-1ba8-11eb-9325-ad7b4e73481e.png)
![Screenshot_20201031_182352](https://user-images.githubusercontent.com/6325757/97786016-e4157800-1ba8-11eb-99d1-6efe3086660b.png)
![Screenshot_20201031_182505](https://user-images.githubusercontent.com/6325757/97786034-fee7ec80-1ba8-11eb-8504-303df85a8f2c.png)
![Screenshot_20201031_182557](https://user-images.githubusercontent.com/6325757/97786037-08715480-1ba9-11eb-8dcb-7311e271ed0a.png)

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(pinage404): `"home-manager-20.03, nixos-20.03.3158.7c2a362b58a, nixos-unstable-21.03pre248170.007126eef72"`
 - channels(root): `"nixos-20.09.1500.edb26126d98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

i don't know there is no maintainers in https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5/systemsettings.nix

**Comment by worldofpeace** [comment]
cc @ttuegel This is really weird though, I've not seen it in a vm.

**Comment by FRidh** [comment]
Thank you for reporting. I have not tried to reproduce this issue on 20.09. However, I can confirm it does not occur on master with https://github.com/NixOS/nixpkgs/pull/101369.

**Comment by pinage404** [comment]
what should i do ?

**Comment by pinage404** [comment]
after many `nix-channel --update`, `nixos-rebuild switch`, `home-manager switch` and `reboot`, it's solved ! (i don't know why, sorry for the inconvenience)
