### ISSUE TITLE
Neovim init.vim loading

### ISSUE THREAD

**Issue by houstdav000** [NixOS/nixpkgs#102297]
**Describe the bug**
Package `nixpkgs.neovim` is not running `$XDG_CONFIG_HOME/nvim/init.vim`.

**To Reproduce**
1. Install `nixpkgs.neovim` via `nix-env -iA`
2. Propagate `$XDG_CONFIG_HOME/nvim/init.vim` with configuration (i.e. `colorscheme desert`)
3. Run neovim and notice settings were not executed

**Expected behavior**
`init.vim` should be run

**Additional context**
Note: This was tested on multiple machines with Nix, but not on NixOS.

I don't know if the issue persists if you maintain your dotfiles with `home-manager`, but I personally use home-manager to _copy_ my dotfiles over.

**Notify maintainers**
@teto - idk, you touched the folder last

**Metadata**
these paths will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/nmzhi83mai0ckfkm9hwawal95hvb2mdd-nix-info
  /nix/store/q1zjp9grl4w92qalkdqjs2bj5d0pf8ih-stdenv-linux
copying path '/nix/store/nmzhi83mai0ckfkm9hwawal95hvb2mdd-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/q1zjp9grl4w92qalkdqjs2bj5d0pf8ih-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.15-301.fc33.x86_64, Fedora, 33 (KDE Plasma)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(david): `"home-manager, nixpkgs-21.03pre249764.680d3201230"`
 - nixpkgs: `/home/david/.nix-defexpr/channels/nixpkgs`

**Comment by teto** [comment]
acknowledged, I see where the issue is. Sorry for that, will send a fix shortly today.
