### ISSUE TITLE
wake-on-lan is not automatically turned on upon boot

### ISSUE THREAD

**Issue by yugawara** [NixOS/nixpkgs#10237]
I want to be able to shut down my home server (in order to save energy) and wake it up when I want to use it.   This used to be possible with Debian before I switched recently to NixOS using the same hardware.

I have not tested it yet but I don't think it will work.  The reason is the command ethtool enp2s0 shows  Wake-on: d

According to https://wiki.archlinux.org/index.php/Wake-on-LAN , this should show g  

My original question on the mailing list is:
   https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg16907.html

The proposed solution on the mailing list does not seem to work because that relies on going-to-sleep event.   I shut down my computer and not put it to sleep so this event will not ne triggered.

**Comment by mogorman** [comment]
is this still a problem?  on my 15.09 box my ethernet card is set correctly.  i will try to wake on lan it when i get home tonight.  Also did the comment on the mailing list adding the ethtool command to @reboot work?

**Comment by Profpatsch** [comment]
(triage) status @yugawara @mogorman

**Comment by mogorman** [comment]
if no one is around to confirm bug id close it

**Comment by mogorman** [comment]
@profpatsch sorry never came back hi this. Wake on lan works on my boxes.  I think this should be closed.

**Comment by mogorman** [comment]
@profpatsch sorry never came back hi this. Wake on lan works on my boxes.  I think this should be closed.
