### ISSUE TITLE
[unityhub] Failed to initialize Unity graphics

### ISSUE THREAD

**Issue by ericdallo** [NixOS/nixpkgs#102307]
**Describe the bug**
After recent nixos rebuild --upgrade Unity doesn't starts anymore.

**To Reproduce**
Start any unity project using any unity version (tested with 2019, 2020 LTS, and 2020 beta versions)

**Expected behavior**
Start Unity engine.

**Screenshots**
![image](https://user-images.githubusercontent.com/7820865/97793342-7463b500-1bc9-11eb-81b3-c2ad39951f6e.png)

**Additional context**
Tested using unityhub stable and unstable

**Notify maintainers**
@tesq0 @mkg20001 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.69, NixOS, 21.03pre249162.1dc37370c48 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(greg): `"home-manager, nixos-21.03pre249162.1dc37370c48"`
 - channels(root): `"nixos-21.03pre249162.1dc37370c48"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute: unityhub
```

**Comment by mkg20001** [comment]
If you've installed it via nix-env then re-install it, it fixed graphics segfaults with many packages for me

**Comment by ericdallo** [comment]
@mkg20001 thanks for the tip, it was not installed via nix-env, but I removed ran a `nix-collect-garbage -d` and installed again is `configuration.nix` and it didn't work :/
This is my config: https://github.com/ericdallo/dotfiles/blob/master/nix/configurations/desktop.nix#L38

**Comment by ericdallo** [comment]
For anyone having this issue, I solved after removing the `~/.config/unityhub` and `~/.config/unity3d` folders :)
