### ISSUE TITLE
Updating home-manager in 20.09

### ISSUE THREAD

**Issue by Guest0x0** [NixOS/nixpkgs#102313]
## Issue description
Currently the home-manager expression in 20.09 is still in version 20.03.
However, it seems that some breaking changes in 20.09 would [cause trouble](https://github.com/nix-community/home-manager/issues/1479) with older versions of home-manager.
While in the unstable channel, the home-manager expression is already updated to 20.09.
It should be desirable to keep the version of home manager synced with its channel.

### Steps to reproduce
Using NixOS 20.09 with a home-manager installation from nixpkgs, e.g.
```nix
environment.systemPackages = [ home-manager ];
```

**Comment by veprbl** [comment]
cc @rycee

**Comment by cole-h** [comment]
rycee appears to have dropped the home-manager package from his maintainership: https://github.com/NixOS/nixpkgs/blob/f0d05c42fbe21b6459260085e693a6c7f1d59fcf/pkgs/tools/package-management/home-manager/default.nix#L36-L41.

**Comment by rycee** [comment]
I never really were the maintainer of that package, the package was added by somebody who put me there as maintainer. If somebody wants to maintain it that would be great.

**Comment by cole-h** [comment]
In the meantime, I've opened a PR to the 20.09 branch updating the `home-manager` package: https://github.com/NixOS/nixpkgs/pull/102549. I'd appreciate any testing, as I use the NixOS module.

**Comment by cole-h** [comment]
https://github.com/NixOS/nixpkgs/pull/102549 was merged minutes ago, so in the next few 20.09 channel bumps this issue should be rectified.
