### ISSUE TITLE
Package "vistafonts" fails sha1 check

### ISSUE THREAD

**Issue by StefanSchroeder** [NixOS/nixpkgs#102450]
**Describe the bug**
When trying to install the font-package nixos.vistafonts, the installation fails because of a mismatch of the SHA-checksum.

**To Reproduce**
1. nix-env -iA nixos.vistafonts

**Expected behavior**
The fonts are downloaded and installed.

The SHA should match the specification in:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/vista-fonts/default.nix#L24

but it is different (0cnvy...)

**Additional context**
This package is unfree.

**Notify maintainers**
@edolstra 

**Metadata**

system: x86_64-linux
host os: Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)
sandbox: yes
version nix-env (Nix) 2.3.7

**Comment by omasanori** [comment]
My `nix-prefetch-url` displays `08wll04bkpy1f2nxxm5dh5jjxx70jjjwp2j9jm7iwymsirb77514` that does not match the current one nor the @StefanSchroeder's one... 🤔

**Comment by StefanSchroeder** [comment]
I have had another look at the downloaded file. Not only is it stored on archive.org, but also there is no indication that it was modified in recent years. I am not a Nix expert, but I'd say that some bits and pieces are considered in the computation of the hash that don't belong there.

**Comment by Kranzes** [comment]
I'm getting the same/similar issue ``nixos-rebuild``.

```
hash mismatch in fixed-output derivation '/nix/store/qq1ihlpzkdq2k5fbm1xv8g3xj97v0qd4-vista-fonts-1':
  wanted: sha256:1l27zg5jraa16zm11d3qz1w7m6f1ih3xy5avww454ylm50fw6z11
  got:    sha256:0cnvy7w18ga6m8sln7rzd9rbxzfx2b0ghl9m4pjzrmah5xfm5cn7

**Comment by jtojnar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/999e24d2472213a76e549beb9a823fe380b70483.

@omasanori You cannot use `nix-prefetch-url` since `fetchzip` builds a fixed output derivation and the hash is the checksun of the produced directory tree, not the downloaded file.

**Comment by omasanori** [comment]
@jtojnar Ah, I see. Thank you for explanation!
