### ISSUE TITLE
ihaskell-widgets doesn't build

### ISSUE THREAD

**Issue by miguel-negrao** [NixOS/nixpkgs#10245]
log: http://hydra.cryp.to/build/1279625/nixlog/1

Does this error happen when generating the documentation ? If so, can the generation of documentation be turned off ?

It also happens on version 0.2.2.0 (current for unstable channel).

    nix-instantiate --eval -E '(import <nixpkgs> {}).lib.nixpkgsVersion'
    "16.03pre70000.2702f01"

Should I report it upstream ?

Also when starting ihaskell it posts:

```
[W 20:31:00.226 NotebookApp] Unrecognized alias: '--kernel=haskell', it will probably have no effect.
[W 20:31:00.266 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
```

Which suggests that '--kernel=haskell' is not needed, and that in order for ihaskell-widgets to work in ihaskell, ipywidgets must also be added ?

**Comment by miguel-negrao** [comment]
setting in my ~/.nixpkgs/config.nix

    ihaskell-widgets = pkgs.haskell.lib.dontHaddock super.ihaskell-widgets

builds the package, so it is haddoc problem. The widgets don't work though, most probably because the python widgets are missing.

**Comment by miguel-negrao** [comment]
Adding 

```
  ipywidgets = pkgs.pythonPackages.buildPythonPackage rec {
    version = "4.0.2";
    name = "ipywidgets-${version}";

    src = pkgs.fetchurl {
      url = "https://pypi.python.org/packages/source/i/ipywidgets/${name}.tar.gz";
      sha256 = "1afwddaslf62ba75679s059z36zfamcx454q2lgd97xqsp30hqmf";
    };

    propagatedBuildInputs = with pkgs.pythonPackages; [ipython_genutils notebook decorator pyzmq ipython jupyter_client ipykernel];

    meta = {
      description = "IPython HTML widgets for Jupyter";
      homepage = http://ipython.org/;
      license = pkgs.lib.licenses.bsd3;
    };

  };
```
to my ~/.nixpkgs/config.nix makes the widgets functional.

**Comment by FRidh** [comment]
Thanks for reporting the issue. I've opened a PR (#10256) with the package.

**Comment by FRidh** [comment]
@miguel-negrao Is the issue solved for you? If so, could you close this issue?

**Comment by peti** [comment]
The package has a syntax error in its markup:

~~~~~~~
src/IHaskell/Display/Widgets/Types.hs:62:1:
    parse error on input ‘import’
~~~~~~

That should be fixed upstream.

**Comment by FRidh** [comment]
Old issue. Upstream issue. Closing this.
