### ISSUE TITLE
Optional services in Gnome 3

### ISSUE THREAD

**Issue by msteen** [NixOS/nixpkgs#10241]
Most of the services enabled by default when enabling Gnome 3 as the desktop manager are only required by the optional packages. Requiring you to disable them when you only want to use the core packages and a small subset of the optional packages.

I disabled the optional packages by excluding them:
    environment.gnome3.excludePackages = pkgs.gnome3.optionalPackages;

And added the ones I wanted to keep in environment.systemPackages. 

The following services are all optional, they only disable parts of Gnome, but are nog required for it to run correctly.

```
# Used in e.g. GParted to acquire the necessary rights
# without having to open it as administrator.
security.polkit

# GNOME Disks (gnome-disk-utility) is a GUI around this service.
services.udisks2

# As far as I could tell only required by the users settings menu.
services.accounts-daemon

# Used to determine your location, used in e.g. GNOME Maps.
services.geoclue2

# Assistive Technology Service Provider Interface,
# a framework to integrate accessibility functions in applications.
services.gnome3.at-spi2-core

# By using the evolution-data-server, other GNOME applications
# are integrating with Evolution.
services.gnome3.evolution-data-server

# These speak for themselves.
services.gnome3.gnome-documents
services.gnome3.gnome-online-accounts
services.gnome3.gnome-user-share

# Necessary for Nautilus to have the ability to automount e.g. USB sticks.
services.gnome3.gvfs

# GUI for PGP keys, works in combination with Gnome keyring.
services.gnome3.seahorse

# A quick previewer for Nautilus.
services.gnome3.sushi

# Tracker is a search engine, search tool and metadata storage system. 
services.gnome3.tracker

# Required by the sound mechnisms of Gnome.
hardware.pulseaudio

# Backend used in e.g. Empathy, the chat client.
services.telepathy

# If enabled, Gnome has integration for it in the top bar.
networking.networkmanager

# If enabled, the bluetooth settings menu can be used.
hardware.bluetooth
```

In my case for example, only having polkit, gvfs and pulseaudio will suffice. So maybe it would be better to have a setting that determines whether they should be enabled by default? Like environment.gnome3.includeOptional, which would then include pkgs.gnome3.optionalPackages and enable these services.

**Comment by Profpatsch** [comment]
(triage) @lethalman I think you are the main Gnome maintainer, what are your thoughts about this?

**Comment by lethalman** [comment]
We have `environment.gnome3.excludePackages`, I'd agree in having the same for services.

**Comment by msteen** [comment]
That would be an improvement over my current solution:

    # Disable most of the services required by the optional Gnome packages.
    # security.polkit.enable = mkForce false;
    # services.udisks2.enable = mkForce false;
    # services.accounts-daemon.enable = mkForce false;
    services.geoclue2.enable = mkForce false;
    # services.gnome3.at-spi2-core.enable = mkForce false;
    services.gnome3.evolution-data-server.enable = mkForce false;
    services.gnome3.gnome-documents.enable = mkForce false;
    services.gnome3.gnome-keyring.enable = mkForce false;
    services.gnome3.gnome-online-accounts.enable = mkForce false;
    services.gnome3.gnome-user-share.enable = mkForce false;
    # services.gnome3.gvfs.enable = mkForce false;
    services.gnome3.seahorse.enable = mkForce false;
    services.gnome3.sushi.enable = mkForce false;
    services.gnome3.tracker.enable = mkForce false;
    # hardware.pulseaudio.enable = mkForce false;
    services.telepathy.enable = mkForce false;
    # networking.networkmanager.enable = mkForce false;
    # services.upower.enable = mkForce false;
    hardware.bluetooth.enable = mkForce false;

**Comment by lethalman** [comment]
GNOME must be working with full features. You had to disable those in your config, and that's fine and expected. I can accept some more `mkDefault` in the nixos service, but I don't think we can do anything much smarter than that.

**Comment by Profpatsch** [comment]
(triage) any updates?
