### ISSUE TITLE
sonobuoy: Version has no 'v' prefix which leads to the search for a non-existent image

### ISSUE THREAD

**Issue by bryanasdev000** [NixOS/nixpkgs#102432]
**Describe the bug**

Due to the missing v character in the package version, sonobuoy generates manifests that point to a non-existent image of the package, which leads to an ImagePullBackOff within the cluster.

**To Reproduce**
1. `sonobuoy images | grep 19`
2. `sonobuoy gen | grep 19 `
3. `sonobuoy run --wait`

**Expected behavior**

Sonobuoy send the manifests with the correct version and available on the dockerhub causing the cluster to download and run the tests correctly

**Screenshots**

The correct version that should be pulled: https://hub.docker.com/layers/sonobuoy/sonobuoy/v0.19.0/images/sha256-09e7ae74580d4e3349e4ae5d0e6949352dd9005a8cfd676f004fc779d49fb0a7?context=explore

![Captura de tela_2020-11-02_02-58-58](https://user-images.githubusercontent.com/53131727/97834856-96d3fc00-1cb7-11eb-9f0d-b111aff965fa.png)
![Captura de tela_2020-11-02_00-42-11](https://user-images.githubusercontent.com/53131727/97834878-a18e9100-1cb7-11eb-96ad-f355105dadd9.png)

**Additional context**

Already mentionet at: https://github.com/vmware-tanzu/sonobuoy/issues/715.

**Notify maintainers**

@carlosdagos @saschagrunert @wilsonehusin

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.13-zen1, NixOS, 21.03pre249162.1dc37370c48 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre249162.1dc37370c48, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.sonobuoy
# a list of nixos modules affected by the problem
module:
```

**Comment by wilsonehusin** [comment]
gah I messed that one up -- apologies and thanks for bringing this up!

**Comment by wilsonehusin** [comment]
if anyone is stuck waiting for the fix to be merged, the current workaround is to manually pass `--sonobuoy-image` flag, i.e.
```
sonobuoy run --sonobuoy-image "sonobuoy/sonobuoy:v0.19.0"
```
```
sonobuoy gen --sonobuoy-image "sonobuoy/sonobuoy:v0.19.0"
```

**Comment by bryanasdev000** [comment]
> gah I messed that one up -- apologies and thanks for bringing this up!

No problem, this issue of passing the version via ldflags seems increasingly constant in golang packages related to kubernetes.

I would like to pass this dynamically, without having to hard code it in the package's `default.nix`.

BTW, Thanks for the quick response: D
