### ISSUE TITLE
gnome3.geary: The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#102487]
**Describe the bug**

Error on startup

**To Reproduce**

1. don't use gnome
2. nix-shell -p gnome3.geary
3. geary

**Expected behavior**

**Screenshots**

```
Error type: GDbusError 2
Message: The name org.freedesktop.secrets was not provided by any .service files

Back trace:
 * geary_problem_report_construct
 * application_client_create_controller_co
 * g_task_return_now
 * g_task_return.part.0
 * application_controller_construct_co
 * g_task_return_now
 * g_task_return.part.0
 * secret_mediator_construct_co
 * g_task_return_now
 * g_task_return.part.0
 * secret_mediator_check_unlocked_co
 * g_task_return_now
 * g_task_return.part.0
 * on_ensure_session
 * g_task_return_now
 * g_task_return.part.0
 * on_service_open_session_aes
 * g_task_return_now
 * g_task_return.part.0
 * reply_cb
 * g_task_return_now
 * g_task_return.part.0
 * g_dbus_connection_call_done
 * g_task_return_now
 * complete_in_idle_cb
 * g_main_context_dispatch
 * g_main_context_iterate.isra.0
 * g_main_context_iteration
 * g_application_run
 * _vala_main
 * __libc_start_main
 * _start
```

**Comment by lourkeur** [comment]
Can confirm on edb26126d98bc696f4f3e206583faa65d3d6e818 under gnome 3 but with gnome-keyring disabled. That's the thing: you need a secrets daemon alongside geary because geary doesn't store credentials on its own. ([source](https://wiki.gnome.org/Apps/Geary/FAQ#line-44)) Note that if you install Geary using `programs.geary.enable` it tries to pull in gnome-keyring. What exactly would be the expected behavior in your opinion?

**Comment by raboof** [comment]
> you need a secrets daemon alongside geary because geary doesn't store credentials on its own

Makes sense.

> What exactly would be the expected behavior in your opinion?

That is an excellent question ;).

*ideally* I think `nix-shell -p geary` would come with a 'default secrets daemon' that is started when I start geary and don't have a secrets manager of my own. That's probably prohibitively hard to do, though, since you wouldn't want to pull in that secrets manager when you already have one running, so that is tricky.

As a second choice, a better error message saying "Hey, you don't seem to have a secrets daemon running, please start one! gnome-keyring is a reasonable choice" instead of the current stack dump. I guess that's an upstream issue.

It would be great if we could also find a way to tell people about `programs.geary.enable`, but I'm not sure what would be a reasonable place to put that.

I guess I should close this issue as it's not a nixpkgs problem (though it does lead to a disappointing experience, so if we *can* come up with something more to do here feel free to reopen ;) ).
