### ISSUE TITLE
gitlab: Support Puma webserver

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#102444]
**Project description**
The default webserver in GitLab 12.9+ is no longer Unicorn, but Puma. Support for Unicorn is expected to be dropped dropped by Gitlab 14 (May 2021)

We should support Puma.

https://docs.gitlab.com/ee/administration/operations/puma.html

**Comment by mkg20001** [comment]
It's now using puma https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/gitlab.nix#L1253-L1259
