### ISSUE TITLE
Use rump kernel fs-utils to build disk images instead of a VM

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#10257]
See https://github.com/rumpkernel/fs-utils.

The problem with the VM approach is that it causes trouble for builders running in e.g., Amazon EC2, since we don't have nested virtualization, so the image-building VM is painfully slow. The slowness also applies on platforms like Darwin, where `qemu-kvm` is not a thing (no KVM) so we're forced to emulate.

`fs-utils` allows us to run filesystem operations purely in user space, which should be both cleaner and faster on EC2 and Darwin.

**Comment by edolstra** [comment]
Hm, I don't see how it's cleaner - it sounds more complicated. For instance, currently we can just run `switch-to-configuration boot` in the VM to install Grub, which presumably wouldn't work if you don't have a block device to write to.

Once upon a time we used User-Mode Linux for this sort of thing, but I don't know if that's still viable (I have the impression it's kind of dead).

**Comment by copumpkin** [comment]
Cleaner in the sense of having fewer implicit dependencies on OS-specific kernel behavior :smile:

But yeah, I guess certain things like Grub would be more difficult without an actual block device. I just find it frustrating that all these things make it so hard to operate directly on disk images.

**Comment by Profpatsch** [comment]
(triage) Does anybody want to invest time in that? Otherwise I suggest we close.
