### ISSUE TITLE
nix-collect-garbage doesn't recognise --print-*

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#10252]
**Bug:**
`nix-collect-garbage` does not recognise --print-roots, --print-live, --print-dead.

**Tested version:** Nix 1.10 on Debian Jessie (`nix-env (Nix) 1.10`)

**Solution:**
Either make nix-collect-garbage recognize the --print-parameters or fix
the documentation.

**Details:**
nix-collect-garbage --help says:

    SYNOPSIS
       nix-collect-garbage [--delete-old] [-d] [--delete-older-than period] [--print-roots |
                           --print-live | --print-dead | --delete] [--dry-run]

But --print-* are not recognized:

    $ nix-collect-garbage --print-roots
    error: unrecognised option ‘--print-roots’
    Try ‘nix-collect-garbage --help’ for more information.

    $ nix-collect-garbage --print-live
    error: unrecognised option ‘--print-live’
    Try ‘nix-collect-garbage --help’ for more information.

    $ nix-collect-garbage --print-dead
    error: unrecognised option ‘--print-dead’
    Try ‘nix-collect-garbage --help’ for more information.

**Comment by domenkozar** [comment]
Could you open an issue for at https://github.com/NixOS/nix ?

**Comment by rkoe** [comment]
-> https://github.com/NixOS/nix/issues/641
