### ISSUE TITLE
Please add the packages group `agdaPackages.*`

### ISSUE THREAD

**Issue by alissa42** [NixOS/nixpkgs#102630]
**Project description**

Agda is a dependently typed programming language. To work and play with Agda, it would be better to packaging some libraries with it. Such as the Standard Library of Agda, the *PLFA* library, Agda Prelude, Cubical Agda and so on. It would be useful that name them follow the Nix convention such as `agdaPackages.std-lib`, `agdaPackages.Prelude` and so on.

The default Agda IDE is Emacs.

Special notice should be pay attention to is that when type checking those source code (or using these libraries), the current user should have the proper permissions to create an `.agdai` file under the src's folder (also the command `agda-mdoe compile`).

**Metadata**

- homepage URL: https://github.com/agda/agda-pkg (this page may help, so I will only the extra packages that I recommend to package with in the below source URL.)
- source URL: https://github.com/HoTT-Intro/Agda
- license: specify by each sub packages
- platforms: unix, linux, darwin, ...

**Comment by veprbl** [comment]
Have you seen https://nixos.org/manual/nixpkgs/stable/#agda and https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/agda-packages.nix?

**Comment by iblech** [comment]
To add to veprbl's comment, for instance (for providing the [Agdapad](https://agdapad.quasicoherent.io/)), I use the following:

    environment.systemPackages = [ ... (pkgs.agda.withPackages (p: [ p.standard-library p.cubical p.agda-categories ])) ... ];

**Comment by laMudri** [comment]
The only thing I see here not already packaged is PLFA, but my understanding is that the PLFA project just contains the source code for the book and exercises, which I wouldn't expect anything to depend on. Looks like this issue should be closed.

**Comment by turion** [comment]
@laMudri I'm trying to package PLFA. If this is important for you, feel free to open an issue for me.
