### ISSUE TITLE
Blanket GNOME app

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#102650]
**Project description**
> Blanket is a new desktop app for Linux designed solely for the purpose of playing background noises like nature sounds (e.g., rain, storm), indistinct ambient noise (e.g., coffee shop), as well as white noise and pink noise. Nothing more, nothing less.

https://www.reddit.com/r/gnome/comments/jn7ldo/cool_gnomeish_app_i_found_on_flathub_blanket/

![image](https://user-images.githubusercontent.com/3998/98028042-86b53d00-1ddb-11eb-95be-681eacb056e5.png)

**Metadata**

* homepage URL: https://github.com/rafaelmardojai/blanket/
* source URL: https://github.com/rafaelmardojai/blanket/
* license: gpl3
* platforms: linux

**Comment by wamserma** [comment]
FTR: This requires an update of `libhandy`.
