### ISSUE TITLE
switch-to-configuration dies on line 326

### ISSUE THREAD

**Issue by msteen** [NixOS/nixpkgs#10261]
After doing `nixos-rebuild switch` a few times I got the following error message:

Died at /nix/var/nix/profiles/system/bin/switch-to-configuration line 326

Which contains:

    my $prevSystemd = abs_path("/proc/1/exe") or die;

After completely removing and reinstalling everything the error was gone. Unfortunately after a few interations of reconfigurations the error resurfaced. Using `nixos-install` to rebuild my NixOS installation does work without any problems.

The [issue 611](https://github.com/NixOS/nix/issues/611) states the same error, and I do have chroot enabled, but it did work fine with chroot enabled for some time, so I doubt that chroot is the cause.

**Comment by edolstra** [comment]
Yeah, I've seen this as well once or twice. It's mysterious since I can't imagine why reading `/proc/1/exe` would fail.

**Comment by msteen** [comment]
If I do `realpath /proc/1/exe` as root after getting the error, I indeed get `realpath: '/proc/1/exe': No such file or directory`, but when I verify this with `ls /proc/1/exe`, exe will be listed, so it should exist. I am currently working around it by just commenting out the lines that define $prevSystemd and $newSystemd and hardcode $restartSystemd to be 1, since always restarting should not cause any problems. Which works, but of course, it is no real solution.

**Comment by edolstra** [comment]
Is `/proc/1/exe` still unreadable after restarting systemd?

**Comment by msteen** [comment]
It is readable after restarting systemd, but so far, after some time, the error always returns, unfortunately I have yet to determine from which point it becomes unreadable.

**Comment by msteen** [comment]
I did a few more nixos-rebuild's and found that if I tested `realpath /proc/1/exe` right before calling `nixos-rebuild switch` would give me a valid path, but it would still crash on `abs_path("/proc/1/exe")`, after which `realpath /proc/1/exe` would give me that it could not be found. So the cause has to be in the script itself somewhere.

**Comment by msteen** [comment]
Removing the check in switch-to-configuration only worked when editing the file directly, when I tried to automate it by creating a script to do it for me, it did not work. After doing garbage collection it broke saying init-interface-version is missing in nixos-15.09.517.5f8e6fb, but using nixos-switch boot still works. Since after doing a nixos-install via a USB, the missing file bug still persists, I cannot test whether nixos-switch boot would have worked to prevent the /proc/1/exe issue, but I think it would have.

I will just continue to use nixos-rebuild boot instead for now and will just hope that the problem is isolated to using switch.

**Comment by msteen** [comment]
I have found out what the problem is. Calling `ls -la /proc/1/exe` gives me:

    lrwxrwxrwx 1 root root 0 Oct 11 23:35 /proc/1/exe -> /nmvg33m7xsd687wh6figf5hgiw1bj2qc-systemd-217/lib/systemd/systemd

The prefix `/nix/store` is missing. I will try to find the cause of why this goes wrong. One potential cause might be that my /nix/store directory is a mounted btrfs volume /nix-store.

**Comment by msteen** [comment]
After asking around in the IRC about the issue a solution has been found. It fortunately had nothing to do with BTRFS. If nix.readOnlyStore is enabled, which it is by default, and the Nix store is mounted in your file system as being writable then Nix will [remount it as a read-only filesystem](https://github.com/NixOS/nixpkgs/blob/0761f81da71fc6a940c7f51129b6c7717db78e87/nixos/modules/system/boot/stage-2-init.sh#L60) causing the problem. If Nix store is mounted as read-only this code will not be executed and the problem is resolved.

The problem only seems to occur when nix.useChroot is enabled, although initially I had chroot enabled and the problem did not occur, so I am not completely sure about this, maybe it only seemed to work, because when you enable chroot, that build will be done with the old setting. However in my current configuration, I consistently get that if nix.readOnlyStore is enabled, my mount is writable, and useChroot is disabled, it works without any problems, and after enabling it the problem will return.

I will not yet close the issue, because someone on the IRC with the same problem, which I assume is the same person as the submitter of issue 611, will be reporting whether it also solved that issue.

**Comment by cleverca22** [comment]
i suspect its caused by a lazy umount, i can reproduce a similar path problem: http://pastebin.com/XUv5DeKe

**Comment by falsifian** [comment]
I have the same problem as @msteen: /proc/1/exe points to a bad path until the first time I restart systemd. (Note: I'm on release-15.09.)

Does anyone know enough about the boot process to shed some light on exactly how systemd is first invoked? I don't, but one theory is that systemd is first run from the initrd, and the initrd is lazily umounted, leading to the problem @cleverca22 pointed out. If so, maybe the initrd should instead run systemd from the root fs?

**Comment by cleverca22** [comment]
i think the main solution is to make sure the initrd mounts /nix/store read-only, something that switches it r/w to r/o is causing the problem, so no switch would solve it
