### ISSUE TITLE
warning: unknown setting 'extra-sandbox-paths'

### ISSUE THREAD

**Issue by mudrii** [NixOS/nixpkgs#102632]
**Describe the bug**

```sh
 ~ > sudo nix-channel --update
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
unpacking channels...
warning: unknown setting 'extra-sandbox-paths'
 ~ > nixos-rebuild switch
warning: unknown setting 'extra-sandbox-paths'
building Nix...
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
building the system configuration...
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
error: --- SysError ---------------------------------------------------------------- nix-env
creating symlink from '/nix/var/nix/profiles/.0_system' to 'system-848-link': Permission denied

~ > sudo nix-channel --update && sudo nixos-rebuild switch
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
unpacking channels...
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
building Nix...
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
building the system configuration...
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
activating the configuration...
setting up /etc...
reloading user units for mudrii...
setting up tmpfiles
```

**To Reproduce**
1. Run usual system update

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```sh
nix-shell -p nix-info --run "nix-info -m"
warning: unknown setting 'extra-sandbox-paths'
warning: unknown setting 'extra-sandbox-paths'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.17, NixOS, 20.09.1599.d105075a1fd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
warning: unknown setting 'extra-sandbox-paths'
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
warning: unknown setting 'extra-sandbox-paths'
 - channels(root): `"home-manager-20.09, nixos-20.09.1599.d105075a1fd, unstable-21.03pre249162.1dc37370c48"`
warning: unknown setting 'extra-sandbox-paths'
 - channels(mudrii): `""`
warning: unknown setting 'extra-sandbox-paths'
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mudrii** [comment]
I think I find the issue 

Seems is related to nixFlaiks entry in configuration.nix

```sh
    nix.package = pkgs.nixFlakes;
    nix.extraOptions = ''
      experimental-features = nix-command flakes 
      '';
```

**Comment by manveru** [comment]
This most likely is from https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix#L43 and caused by https://github.com/NixOS/nix/commit/ff4dea63c9403880500f82ce273713ecf793d2d9

**Comment by mudrii** [comment]
If I use 

nix. package = pkgs.nixUnstable;

I can't run even basic nix expressions

```
nix eval '(1 + 1)'
warning: unknown setting 'extra-sandbox-paths'
error: --- BadURL ---------------------------------------------------------------------- nix
'(1 + 1)' is not a valid URL
```

**Comment by manveru** [comment]
that would be `nix eval --expr '(1+1)'` and is unrelated.

**Comment by kisik21** [comment]
Oh no! It seems like this breaks `boot.binfmt.emulatedSystems` support for building Nix packages! I have pushed a preliminary fix for it on [my own fork](https://github.com/kisik21/nixpkgs/blob/nix-fix-sandbox-paths/nixos/modules/services/misc/nix-daemon.nix), but it needs to be gated behind a version check, and I'm not sure how to do that.

**Comment by leotaku** [comment]
@kisik21 Do you mean a check for the Nix version? If so, the file in question already seems to have those in a few places. ([setup here](https://github.com/kisik21/nixpkgs/blob/nix-fix-sandbox-paths/nixos/modules/services/misc/nix-daemon.nix#L11))

Maybe something like this could work?

```nix
let
  sandboxSetting = if versionAtLeast nixVersion "???" then
    "sandbox-paths"
  else
    "extra-sandbox-paths";
in pkgs.writeFile "nix.conf" ''
  ...
  ${sandboxSetting} = ${toString cfg.sandboxPaths}
  ...
''

**Comment by kisik21** [comment]
@leotaku great! :sparkles: when will it drip down to nixpkgs master and then nixos-unstable?

**Comment by leotaku** [comment]
@kisik21 From what I understand, the changes from Nix master trickle down into the `nixUnstable` [package](https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/tools/package-management/nix/default.nix) like any other upstream package would. As such, it seems hard to give any useful estimate.

Currently, a [PR](https://github.com/NixOS/nixpkgs/pull/102932) for upgrading `nixUnstable` seems to be blocked by incompatibilities with Hydra, so it might take a while.

**Comment by kisik21** [comment]
```nix
nix.sandboxPaths = ["/bin/sh=${pkgs.busybox-sandbox-shell}/bin/busybox"];
```

This could help you if you use my fork branch and accidentally override your nix.conf's default sandbox path and break your system building process.

**Comment by kisik21** [comment]
I hope we can close it as solved since multiple overlapping attempts (sometimes unsuccessful, like mine) to fix this issue happened and one of them got into the main branch.
