### ISSUE TITLE
Please add the input method Fcitx5.

### ISSUE THREAD

**Issue by alissa42** [NixOS/nixpkgs#102626]
**Project description**

Fcitx5 is the under development successor of Fcitx.

- Fcitx5 is in fact one of the best choice for Chinese Arch Linux to set as the default input method. It has modern appearance and nice input experience. While more and more distributions had add it in their packages warehouse, it had just release the stable version.
- Fcitx5 itself is just a basic framework which just give a English support. Using input engine can help user to input other languages, such as Chinese or Japanese, Greek letters and so on.
- Fcitx5 also has a GUI configure tool. Themes can be change by installing more packages.
- For Chinese users, it will be better to enable extra words libraries.

**Metadata**

For more information, please visit this [site](https://wiki.archlinux.org/index.php/Fcitx5).

- homepage URL: https://github.com/fcitx/fcitx5

- source URL:
    - https://github.com/fcitx/fcitx5
    - https://github.com/fcitx/fcitx5-qt (for both Qt5 and Qt4 support, respectively)
    - https://github.com/fcitx/fcitx5-gtk
    - https://github.com/fcitx/fcitx5-configtool
    - https://github.com/felixonmars/fcitx5-pinyin-zhwiki
    - https://github.com/fcitx/fcitx5-unikey
    - https://github.com/fcitx/fcitx5-hangul
    - https://github.com/fcitx/mozc
    - https://github.com/fcitx/fcitx5-skk
    - https://github.com/fcitx/fcitx5-anthy
    - https://github.com/fcitx/fcitx5-chewing
    - https://github.com/fcitx/fcitx5-rime
    - https://github.com/fcitx/fcitx5-chinese-addons
    - https://github.com/yangshann/rime-dict
    - https://github.com/hosxy/Fcitx5-Material-Color
    - https://github.com/outloudvi/fcitx5-pinyin-moegirl
    - https://github.com/felixonmars/fcitx5-pinyin-zhwiki
    - https://github.com/outloudvi/mw2fcitx

- license: the frame itself was distribute under *LGPL-2.1-or-later*, specified by sub packages.
* platforms: unix, linux, darwin, ...

**Comment by omasanori** [comment]
As a Japanese-speaking NixOS user, the quality of Fcitx5 support will substantially affect my UX.
Thus, I'd support this if some help is needed.

**Comment by asdf8dfafjk** [comment]
@alissa42 

I use fcitx4 extensively and I am interested in fcitx5. Is there someplace where I can read about what features fcitx5 offers over fcitx4? 

I believe the first 3 points you listed are already satisfied by fctix4. (Probably the 4th too, I only use zhengma but  https://wiki.archlinux.org/index.php/Fcitx#Chinese lists quite a few chinese input methods). 

I hope fcitx5 is good and I might try to make a crude derivation. 

Noting for later: 

Looking at fcitx-anthy vs fcitx5-anthy, their last common commit was https://github.com/fcitx/fcitx5-anthy/commit/f51f29d3f3c8bb696c195d0d3290cf758bad797c  on Sept 2017.  fcitx-table also seems to have diverged https://github.com/fcitx/fcitx-table-extra/commit/feb887ea756d8cc9caab3bf07fa1addef1ab0587 

Thus it appears that using fcitx5 would also require repackaging the input methods.

**Comment by ayalhw** [comment]
> Is there someplace where I can read about what features fcitx5 offers over fcitx4?

I write a blog for Chinese user：
https://blog.coelacanthus.moe/tech/welcome-to-fcitx5/

and there are others：
https://felixc.at/2017/08/lets-try-a-new-pinyin-input-method-that-might-be-slightly-better-than-sunpinyin/
https://manateelazycat.github.io/linux/2020/06/19/fcitx5-is-awesome.html
https://h-cheung.gitlab.io/post/fcitx5_简评和使用方法/
https://www.zhihu.com/question/333951476

also in Chinese

And Fcitx5 rewrite with c++ and modular

**importantly，there will be no further maintaince for fcitx4，according to fcitx dev**

**Comment by ayalhw** [comment]
@alissa42 you seems to lose some source/package
https://github.com/fcitx/libime （as dep of Chinese addons）
https://github.com/fcitx/xcb-imdkit （as dep，a basic ime lib）
https://github.com/fcitx/fcitx5-lua （provide lua support）
https://github.com/fcitx/libime-jyutping （provide 粵語 support）
https://github.com/fcitx/fcitx5-m17n
https://github.com/fcitx/fcitx5-libthai
https://github.com/fcitx/fcitx5-sayura
https://github.com/fcitx/fcitx5-table-other
https://github.com/fcitx/fcitx5-table-extra
https://github.com/fcitx/fcitx5-chewing （for traditional Chinese）
https://github.com/fcitx/fcitx5-zhuyin（also）

**Comment by ayalhw** [comment]
Some notes about other distribution:
- Fedora has fcitx5 in official repo of Rawhide and 32/33, in copr for Fedora 31.
- openSUSE has fcitx5 in M17N repo, and prepare to submit to official repo.
- Ubuntu has fcitx5 in official repo since Ubuntu 19.10.
- Debian has fcitx5 in testing and Sid.
- AOSC OS has fcitx5 in official repo.
- Arch has fcitx5 in official repo since the beginning of this year.
- Gentoo has fcitx5 in gentoo-zh overlay.

**Comment by Vonfry** [comment]
Should we keep fcitx4 in nixpkgs or update it into 5? 

For the second one, it is not too difficult because of fcitx based on cmake and the nixos module need not  modify too much.

**Comment by jansol** [comment]
Keep it for now but mark it as deprecated with a note about fcitx5? That way existing installs continue working for the time being and users get notified that development has moved to a new fork. The fcitx5 derivation can start out as a copy of the fcitx4 one, adjusted for the new version.

**Comment by ayalhw** [comment]
> Keep it for now but mark it as deprecated with a note about fcitx5? That way existing installs continue working for the time being and users get notified that development has moved to a new fork. The fcitx5 derivation can start out as a copy of the fcitx4 one, adjusted for the new version.

I think it is appropriate.

**Comment by poscat0x04** [comment]
see also https://fcitx-im.org/wiki/Compile_from_source

**Comment by poscat0x04** [comment]
Trying to package fcitx5: https://github.com/poscat0x04/nixpkgs/tree/add-fcitx5

**Comment by berberman** [comment]
fcitx5-mozc (Japanese) is on the way: #109735

FWIW, fcitx5-pinyin-moegirl and fcitx5-pinyin-zhwiki are available in my [flake repo](https://github.com/berberman/flakes).
