### ISSUE TITLE
Propagate man pages to user profile

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#10270]
At the moment manpages are not available to the user by default, she has to duplicate the package into her profile to read them with `man <program>`. This leads to the awkward situation where you have the binary but not the manual.

It would be nice if those got propagated too.

**Comment by edolstra** [comment]
What manpages are you talking about specifically?

I know the Perl manpages are no longer available by default because we moved them into a separate output.

**Comment by Profpatsch** [comment]
Hm, happened to me quite a few times, but now I’m unsure where. They seem to be propagated by default. I’m going to open another Issue if it happens with a specific program.

**Comment by vcunat** [comment]
They aren't propagated from `systemPackages`, I believe. On the closure-size branch I was fighting with that by c2fff7283. That could be picked to master, if you think it's a good solution.

**Comment by Profpatsch** [comment]
@edolstra would have to look at it.
