### ISSUE TITLE
NixOS as guest in openVZ container.

### ISSUE THREAD

**Issue by mrqwer88** [NixOS/nixpkgs#10271]
Hello.

I try to run nixoOS in container in OpenVZ 6.

```
nixos-version 
15.09.563.f120b1d (Dingo)
```

https://nixos.org/wiki/Install_NixOS_as_OpenVZ_guest too old.
OpenVZ on node use venet, but I cannot configure it with nixos.

If up network manaul - it work good

```
ifconfig venet0  127.0.0.1 netmask 255.255.255.255
ifconfig venet0:0 $IP
ip route add default  dev venet0
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
```

But via configure.nix I cannot up it correct.
network.nix - 

```
{ config, lib, pkgs, ... }:
{
  networking = {
      hostName = "nixos0.example.org";
      nameservers = ["8.8.8.8" "8.8.4.4"];
      interfaces = [ {
          name = "venet0";
          ipAddress = "127.0.0.1";
          prefixLength = 32;
      } ];
      #{
      #    name = "venet0:0";
      #    ipAddress = "$IP";
      #    prefixLength = 32;
      #}];
      localCommands =
        ''
          ifconfig venet0:0 $IP
          ip route add default  dev venet0
        '';
  };
}
```

With "venet0:0" block systemd freeze on network-link-venet0:0.service start.
With this config it correctly up venet0 and hostname.
But resolv.conf, route and venet0:0 it not set.
And nixos-rebuild test/switch show errors only about systemd-sysctl.service, systemd-vconsole-setup.service (https://bugs.openvz.org/browse/OVZ-6172 ).

Can you help with this problem?

**Comment by sorki** [comment]
Getting NixOS running on OpenVZ is a little more complicated.

I've managed to make most of the stuff working using external network configuration (combination of vzctl distro scripts / systemd unit).

https://github.com/vpsfreecz/build-vpsfree-templates/blob/master/files/configuration.nix
https://github.com/vpsfreecz/vzctl/commit/870116d16abd201ce4fc2fcf7f1a23cc098211bd

To get vzctl exec working it also needs altering PATH, see

https://github.com/vpsfreecz/vzctl/commit/a4e9efee9826f78e9c94fb23df42ebaa4450d4c2

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by sorki** [comment]
I think this could be close as OpenVZ is pretty much dead.
