### ISSUE TITLE
Mumble cannot find CELT codec

### ISSUE THREAD

**Issue by travisbhartwell** [NixOS/nixpkgs#10275]
I am running NixOS unstable and installed the latest Mumble package into my user environment using `nix-env -i mumble`.  But when I tried to connect to my employer's Mumble server, I could not receive any audio from other users, and in the status window on the left-hand side of the Mumble window, it complained about not being able to find the CELT codec.  I notice the latest commit was switching to use the external `celt` library.

I installed Mumble from commit fc7c18a99221385060cdc0a3ba7c1d7a3dc62e55, the commit previous to the latest change, and the issue went away and I am able to hear the other users and no warning shows up about a missing codec.

cc @viric @geerds (both listed as maintainers on Mumble)
cc @abbradar (author of the commit that introduced the change)

**Comment by abbradar** [comment]
Can you please find out what version of Mumble server your employer use? It would help to identify the issue.

**Comment by travisbhartwell** [comment]
Server -> Information tells me "Protocol 1.2.10".  A person that might know from my employer indicated that's what they thought it was.

**Comment by abbradar** [comment]
@travisbhartwell Can you try out Mumble with [this patch](https://github.com/abbradar/nixpkgs/commit/035872c39998f64aa1d6a1e2a23e53e154609c7a)?

**Comment by travisbhartwell** [comment]
@abbradar I just tried it out and the same warning about the missing CELT codec came up.  I didn't get a chance to try any audio though, but I imagine the warning would indicate things aren't working.

**Comment by abbradar** [comment]
Well, I've run out of ideas and made a revert, please test: https://github.com/abbradar/nixpkgs/commit/2e22f86839f496c95f012d8467bdc9c54a4f8939 . Let's merge if it works for you.

**Comment by travisbhartwell** [comment]
Tested.  Looks good!  Thanks for trying to resolve this.

**Comment by abbradar** [comment]
Pushed to `master` as https://github.com/NixOS/nixpkgs/commit/5963d94c3c323c7262653be1607b64bb24aee489 and to `release-15.09` as https://github.com/NixOS/nixpkgs/commit/b662c2aeef9cae53a07942d6c6295d73cb0e2fd7
