### ISSUE TITLE
Racket CS

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#102704]
**Project description**
Racket on Chez Scheme (Racket CS) may become the default Racket implementation in the next release [1]

[1] https://blog.racket-lang.org/2020/11/racket-v7-9.html

**Metadata**

* homepage URL: https://racket-lang.org/
* source URL: https://download.racket-lang.org/all-versions.html
* license: MIT or Apache 2.0
* platforms: unix

**Comment by yurkobb** [comment]
Released: https://blog.racket-lang.org/2021/02/racket-v8-0.html

**Comment by yurkobb** [comment]
Just a note. Reading [how Racket CS builds](https://github.com/racket/racket/blob/master/build.md#16-more-instructions-building-racket-cs-and-racket-bc) stumbled upon the following (emphasis mine):

```Building Racket CS requires either an existing Racket or pb (portable bytecode) boot files for Chez Scheme. By default, pb boot files are **downloaded from a separate Git repository** by make```

This probably needs to be worked-around...

**Comment by iblech** [comment]
I thought I'd have a stab at a pull request for bumping to 8.0. It's still compiling, but right now it's looking good. I just had to bump the version number, the checksum and fix some hardcoded `/bin/cp` paths and their like. I'll report back when I know more!
