### ISSUE TITLE
Python-unstable "run"

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#102858]
@FRidh I feel like we're overdue for a "python-unstable" run, and now that the updater supports github, we should be able to update more packages.

My only concern is that hydra has been having issues recently.

**Comment by siraben** [comment]
What issues has hydra been having recently?

**Comment by kisik21** [comment]
the aforementioned issues are probably Hydra choking on builds, aborting some of them

**Comment by jonringer** [comment]
There was some configuration issues, in which jobs were not correctly assigning jobs. Also, I think there were some regressions in the latest release of nix. 

You can see the large number of aborted jobs with arch https://hydra.nixos.org/eval/1624335

**Comment by FRidh** [comment]
@jonringer https://github.com/NixOS/nixpkgs/pull/101636 has patch updates. I just updated it.

**Comment by jonringer** [comment]
since #101636 was merged, I'm going to close this.
