### ISSUE TITLE
wine: no sounds in 32 bit games

### ISSUE THREAD

**Issue by cirno-999** [NixOS/nixpkgs#102828]
**Describe the bug**
I can't get sound in any 32-bit apps running them with wine.

**To Reproduce**
1. use the following config
```
  sound.enable = true;
  hardware.pulseaudio.enable = true;
  hardware.opengl.driSupport32Bit = true;
  hardware.opengl.extraPackages32 = with pkgs.pkgsi686Linux; [ libva ];
  hardware.pulseaudio.support32Bit = true;
  ...
  environment.systemPackages = [ pkgs.wine ];
```
2. `wine ./game.exe`
3. enjoy no sound

**Expected behavior**
Sound working in game.

**Additional context**
Tried Among Us, Hades, Your Turn To Die ([free game](https://vgperson.com/games/yourturntodie.htm)) a few old other old games

**Notify maintainers**
@avnik @7c6f434c @bendlas 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09.1469.13d0c311e3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 3.0pre20201020_e0ca98c`
 - channels(root): `"nixos-20.09.1469.13d0c311e3a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cirno-999** [comment]
![image](https://user-images.githubusercontent.com/73712874/98182566-62a24a80-1f06-11eb-9524-085fceea91ca.png)
winecfg

**Comment by 7c6f434c** [comment]
Hmm. I get similar errors, and it looks like under a fresh user both ALSA and PulseAudio work for me.

Does, say, `pavucontrol` show some resonable output device?

**Comment by cirno-999** [comment]
> Hmm. I get similar errors, and it looks like under a fresh user both ALSA and PulseAudio work for me.
> 
> Does, say, `pavucontrol` show some resonable output device?

I actually don't have pavucontrol, if that matters (not sure)
I ran it from nix-shell, all looks good to me
![image](https://user-images.githubusercontent.com/73712874/98445875-71f9e180-211a-11eb-916b-118008d2d013.png)

**Comment by 7c6f434c** [comment]
Hmmm. I wonder if creating a fresh user, logging in as that, and rechecking would change anything (quite likely not, of course)

**Comment by cirno-999** [comment]
> Hmmm. I wonder if creating a fresh user, logging in as that, and rechecking would change anything (quite likely not, of course)

That actually worked... o.0
I'm not sure why, I think that had to do something with wineprefixes.
I deleted ~/.wine on main user, launched the game, got my precious sound.

note: i was using wine-staging for Your Turn To Die (doesn't 'just work' on 5.0), perhaps wineprefixes got mangled or something?

**Comment by 7c6f434c** [comment]
Wine prefixes can accumulate quite a bit of hard-to-instpect state…

I am _not_ any good at inspecting that state, so I often run things with freshly-created empty `$HOME`. (It's not just about Wine).

I guess if you no longer have any broken state directory, the issue can be closed?

**Comment by cirno-999** [comment]
> Wine prefixes can accumulate quite a bit of hard-to-instpect state…
> 
> I am _not_ any good at inspecting that state, so I often run things with freshly-created empty `$HOME`. (It's not just about Wine).
> 
> I guess if you no longer have any broken state directory, the issue can be closed?

yep!
