### ISSUE TITLE
recoll uses wrong pdftotext package

### ISSUE THREAD

**Issue by krgn** [NixOS/nixpkgs#10284]
The recoll package should use`pdftotext` from `poppler_utils` for indexing pdf files, rather than `xpdf`.

**Comment by pSub** [comment]
The referenced change looks good, can you make a PR?

**Comment by krgn** [comment]
Cool!

Its here: https://github.com/NixOS/nixpkgs/pull/10285
However, something strange is happening during the build process that I didn't see building locally related to python build tools, so I think this should probably not be merge until the cause is found.
