### ISSUE TITLE
services.openssh.permitRootLogin = "no" does nothing

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#10294]
I put
```
services.openssh.permitRootLogin = "no";
```
into my `configuration.nix` expecting it to disable root logins, according to the documentation, but root logins are not disabled.

**Comment by peti** [comment]
Does the generated `sshd_config` file not contain the setting you specified?

**Comment by ttuegel** [comment]
It contains
```
PermitRootLogin no
```
as expected, but this setting does not appear to be effective. I can still see in my log that bruteforce attackers are getting as far as PAM in the authentication process, which should be impossible. This is no real problem for me; I have password authentication disabled and no authorized keys for root, but still!

**Comment by peti** [comment]
What happens if you configure authorized keys for root? Can you actually log in?

**Comment by Profpatsch** [comment]
(triage) @ttuegel still a problem?

**Comment by ttuegel** [comment]
If I configure authorized keys, I still cannot log in. This is strange, but apparently not a bug.
