### ISSUE TITLE
texlive.combine results in non-reproducible derivation

### ISSUE THREAD

**Issue by typetetris** [NixOS/nixpkgs#102917]
**Describe the bug**

Using `texlive.combine` results in non-reproducible derivation.

**To Reproduce**

Content of `tex.nix`:
```
{ nixpkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/4c817f9d6e6a4e6ddb0c51dcb093a8e70adaf5c4.tar.gz") {} }:
nixpkgs.texlive.combine {
    inherit (nixpkgs.texlive) scheme-small xpatch phonenumbers helvetic supertabular booktabs xtab xecjk;
  }
```

The SHA was master as of today 2020/11/5 12:45.

First

```
nix-build tex.nix
```

and then

```
nix-build --check tex.nix
```
results in

```
...
Wrapping './bin/tlshell' Warning: unknown shebang '/usr/bin/env wish' in '/nix/store/ssqlggvl0zvv5wldmybj80dj54kgbgv2-texlive-tlshell-56461/scripts/tlshell/tlshell.tcl'
Wrapping './bin/updmap-user' and patching shebang '/bin/sh'
derivation '/nix/store/bsi2f3qjvzh3699jrhwmz7jp3scz5rb4-texlive-combined-2020.drv' may not be deterministic: output '/nix/store/fjb02b46nq25iaw1vq9139lz3a2sjw18-texlive-combined-2020' differs
error: build of '/nix/store/bsi2f3qjvzh3699jrhwmz7jp3scz5rb4-texlive-combined-2020.drv' failed
```

**Expected behavior**
Getting a reproducible derivation.

**Notify maintainers**
@vcunat @veprbl @lovek323 @jwiegley

**Comment by typetetris** [comment]
`diff -r` of the derivation with its check from `nix-build -K --check tex.nix` attached.
[diff.nix-build.K.check.tex.nix.txt](https://github.com/NixOS/nixpkgs/files/5494175/diff.nix-build.K.check.tex.nix.txt)

**Comment by iblech** [comment]
Thank you for spotting and reporting this! There seem to be three issues:

1. File names in the `ls-R` files are not sorted (should be easily fixable)
2. `.log` files contain timestamps (easily fixable: I believe that these files are not required anyway)
3. Changes in the binary `.fmt` files (I don't know about these)

How does Debian solve these issues?

**Comment by trofi** [comment]
Noticed it as well. `.fmt` files seem to contain textual build date (in .gzip in UTF-16)

**Comment by iblech** [comment]
I just checked with current master, the issue still persists.
