### ISSUE TITLE
Ferdi half working

### ISSUE THREAD

**Issue by pinage404** [NixOS/nixpkgs#102969]
**Describe the bug**
Ferdi crashes when started elsewhere than a `nix-shell --pure`

**To Reproduce**

1. use the official Ferdi AppImage https://github.com/getferdi/ferdi/releases/download/v5.5.0/Ferdi-5.5.0.AppImage
2. configure services
3. close it

i'm not sure, if this first part does anything for this issue

4. `nix-shell --packages ferdi --command ferdi` crashes after displaying this message

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Expected behavior**
Ferdi should be usable without `nix-shell`'s option  `--pure`

**Additional context**
I used to use Ferdi from there official AppImage (because it was not available for Nix when i looked for it)

With the `--pure` option, it works

```
nix-shell --pure --packages ferdi --command ferdi
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:15488) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:15488) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:15488) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:15488) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

**Notify maintainers**

@davidtwco 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(pinage404): `"home-manager-20.09, nixos-20.09.1599.d105075a1fd, nixos-unstable-21.03pre250162.34ad166a830"`
 - channels(root): `"nixos-20.09.1500.edb26126d98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: ferdi
# i think, i'm not sure how to fill this "field"
```

**Comment by bryanasdev000** [comment]
Just out of curiosity, I'm running it on my profile with the home-manager and I also have some bugs, for example, notification badges don't work, I can't disable notifications by service, yet I don't have "official" bugs like missing icons for example. When I have a bit of time I will try to track it down.

**Comment by davidtwco** [comment]
I can't say I've experienced either of these issues, but I'm running Ferdi 5.6.0-beta.2 locally, which might be making a difference:

```nix
self: super: 
{
  ferdi = super.ferdi.overrideAttrs (
    old: rec {
      version = "5.6.0-beta.2";
      name = "${old.pname}-${version}";
      src = super.fetchurl {
        url = "https://github.com/getferdi/ferdi/releases/download/${version}/ferdi_${version}_amd64.deb";
        sha256 = "0shd7p4v3dkkxzzdyi1zsh60330pxb7m0897lcr2367hr0a0j69s";
      };
    }
  );
}
```
I'd upgrade the package in nixpkgs to this version as I've previously been told that nixpkgs should stick to stable releases.

**Comment by pinage404** [comment]
I've updated [my config](https://gitlab.com/pinage404/dotfiles/-/blob/29a2c9d0dab3b704ab09e5f94f7e2e3ef4a6f6f0/nixpkgs/package/social.nix) with your snippet, it fixed my issue

**Comment by bryanasdev000** [comment]
I just did some quick tests after a heads up from @juanluisbaptiste in  https://github.com/getferdi/ferdi/issues/780 and apparently my problems were solved.

While not updated on nixpkgs:

```
    overlays = [
      (self: super: {
        ferdi = super.ferdi.overrideAttrs (old: rec {
          version = "5.6.0-beta.5";
          name = "${old.pname}-${version}";
          src = super.fetchurl {
            url =
              "https://github.com/getferdi/ferdi/releases/download/v${version}/ferdi_${version}_amd64.deb";
#              "https://github.com/getferdi/ferdi/releases/download/v5.6.0-beta.5/ferdi_5.6.0-beta.5_amd64.deb"
            sha256 = "sha256-fDUzYir53OQ3O4o9eG70sGD+FJ0/4SDNsTfh97WFRnQ=";
          };
        });
      })
    ];
  };
```

I still need to test the notification badges, but it's for another issue.

Furthermore, as no one has reported any more problems, I am closing this issue.
