### ISSUE TITLE
Heroku toolbelt core plugins don't work

### ISSUE THREAD

**Issue by rehno-lindeque** [NixOS/nixpkgs#10298]
With `heroku-3.32.0` installed on NixOS 15.09, none of the core plugins (beside `heroku-apps`) appear to work:

```
$ nixos-version
15.09.587.dbf2827 (Dingo)

$ heroku fork --help
Installing core plugins heroku-cli-addons, heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status...
 ▸    
 !    fork is not a heroku command. See `heroku help`.
```

I think this might be a regression, because I don't remember seeing `Installing core plugins heroku-cli-addons, heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status...` on every invocation of the `heroku` command before nixos-15.09.

**Comment by aflatter** [comment]
The toolbelt pulls a binary package of nodejs on runtime... :(
```
[joe@mybox:~/.heroku/node-v4.2.1-linux-x64]$ readelf -a bin/node |grep interpret
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  6198: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS interpreter-irregexp.cc
```

**Comment by aflatter** [comment]
See also heroku toolbelt v4, https://github.com/heroku/heroku-cli

**Comment by aflatter** [comment]
@rehno-lindeque As a work-around, it should be possible to grab the node tarball and compile it yourself within `~/.heroku/node-v4.2.1-darwin-x64`. Didn't try it myself yet.

**Comment by rehno-lindeque** [comment]
Thanks @aflatter

**Comment by aflatter** [comment]
There's a PR that lets us set the node path via an environment variable: https://github.com/heroku/heroku-cli/pull/104
