### ISSUE TITLE
LilyPond

### ISSUE THREAD

**Issue by thomas-morgan** [NixOS/nixpkgs#10290]
With NixOS 15.09 I get this error running LilyPond:

    $ /run/current-system/sw/bin/lilypond
    GNU LilyPond 2.18.2
    warning: not relocating, no 2.18.2/ or current/ found under /run/current-system/sw/share/lilypond/
    ERROR: In procedure primitive-load-path:
    ERROR: Unable to find file "lily.scm" in load path

I can work around this (clumsily) by using an old version of `wrapProgram` in LilyPond's `postInstall`.  This `wrapProgram` differs by not including `-a "$0"`.

    postInstall = ''
      wrapProgram() {
        local prog="$1"
        local hidden="$(dirname "$prog")/.$(basename "$prog")"-wrapped
        mv $prog $hidden
        makeWrapper $hidden $prog "$@"
      }
    
      for f in "$out/bin/"*; do
          wrapProgram "$f" --set GUILE_AUTO_COMPILE 0 \
                           --set PATH "${ghostscript}/bin"
      done
    '';

This seems to be related to https://github.com/NixOS/nixpkgs/pull/9562.  Changing `argv[0]` apparently can break some users of `wrapProgram` as well as those of `makeWrapper`.

**Comment by domenkozar** [comment]
cc @ttuegel

**Comment by vcunat** [comment]
Hmm, perhaps we should add `--no-argv0` or some similar option to handle these cases easily.

**Comment by ttuegel** [comment]
It's better to set `--argv0 "$f"` in most cases, which I just did in `master` and `release-15.09`.
