### ISSUE TITLE
vdirsyncer: why is there a default plus a stable?

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#103026]
**Describe the bug**

Currently, there is a [default](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/vdirsyncer/default.nix), which points to an upstream commit from 2018, and a [stable](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/vdirsyncer/stable.nix), which points to the latest release, from 2020-07-09.

Why not have only default, pointing to the release?
I can do a PR, if wanted.

**Notify maintainers**

Pinging the maintainer and the people that made the last few commits:
@loewenheim @DamienCassou @marsam @doronbehar

**Comment by doronbehar** [comment]
> Why not have only default, pointing to the release?

Because the project is not maintained very well upstream. See: https://github.com/pimutils/vdirsyncer/issues/790

However, we maintainers probably haven't followed that thread and there has been some good progress there, so it may be worth it to recheck. Feel free to make a PR if you think we can be a bit more rigorous. Personally I don't use this package nowadays so I lack a strong opinion. Unccing myself.

**Comment by DamienCassou** [comment]
From what I understand (which is not much, please correct me):

1. At first their was one Python version of vdirsyncer that worked fine for years. Then, maintenance decreased and the package was marked as broken in nixpkgs.
2. The original author (@untitaker) of vdirsyncer decided to re-implement (part of) vdirsyncer in Rust. Nixpkgs made `vdirsyncer` point to the Rust version and renamed the Python historical version to `vdirsyncerStable`.
3. Eventually, @untitaker gave up on the Rust version. 
4. @WhyNotHugo decided to take over maintenance of the Python version.
5. @marsam and I [updated the vdirsyncerStable](https://github.com/NixOS/nixpkgs/pull/91918) to point to the work of @WhyNotHugo and mark the package as working again.

My conclusion on what needs to be done now:
1. Remove `pkgs/development/python-modules/vdirsyncer/default.nix`;
2. Rename `stable.nix` to `default.nix`;
3. Make `vdirsyncer` and `vdirsyncerStable` point to `default.nix`;
4. Deprecate `vdirsyncerStable`.

**Comment by untitaker** [comment]
This sounds correct, thanks

**Comment by magnetophon** [comment]
OK, I'll do a PR then.
Thanks for clearing it up, @DamienCassou and @untitaker!

**Comment by magnetophon** [comment]
PR here: https://github.com/NixOS/nixpkgs/pull/103073

@DamienCassou When I tried to implement your comment, I noticed I didn't fully understand it: ``vdirsyncerStable`` doesn't point to ``default.nix`` in my PR, but just throws a message instead.  If that is not OK, please tell me what I should do.
