### ISSUE TITLE
KDE applications icon missing and theme broken

### ISSUE THREAD

**Issue by lunalunaa** [NixOS/nixpkgs#103016]
**Describe the bug**
See the screenshot. systemsettings5 and dolphin are mainly affected. Other non-KDE applications does not seem to be affected much.

**To Reproduce**
Open these apps. 

EDIT: also having `programs.qt5ct.enable = true` in `configuration.nix`

**Expected behavior**
Icons are showing and themes are consistent

**Screenshots**
![image](https://user-images.githubusercontent.com/26627218/98368197-ea589800-2071-11eb-9928-d451c92d7831.png)
![image](https://user-images.githubusercontent.com/26627218/98368231-f9d7e100-2071-11eb-9541-1d13f6b357e2.png)
![image](https://user-images.githubusercontent.com/26627218/98368262-052b0c80-2072-11eb-8a5b-0081c5308ac6.png)

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.73, NixOS, 21.03pre250162.34ad166a830 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos, nixos-unstable"`
 - channels(mono): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by monothink** [comment]
After removing the option `programs.qt5ct.enable` the issue resolves. I don't know if I should close this issue because it now seems  `qt5ct` are breaking KDE icons and themes.

**Comment by doronbehar** [comment]
I think you are missing the icons packages (such as `breeze-icons`) that you enable via qt5ct. There are many such icons packages, e.g:

```
nix search icons
```

**Comment by doronbehar** [comment]
I'm closing assuming the OP has found a fix for the issue / got along somehow.

**Comment by IPlayZed** [comment]
> I think you are missing the icons packages (such as `breeze-icons`) that you enable via qt5ct. There are many such icons packages, e.g:
> 
> ```
> nix search icons
> ```

Hi, I have a similar problem, please reopen the issue.

I am on Arch (6.1.12-arch1-1).

I have tried searching for icon packages:
```
❯ paru -Q | grep icons
breeze-icons 5.103.0-1
kemoticons 5.103.0-1
```
I would really want to give a comprehensive bug report, but the whole desktop is broken beyond logic. Some icons show, the scaling is way too big, some styles are reported as installed, but are not, etc. I do not even know where to start. Sometimes KWin crashes, sometimes it restarts. Settings are not saved.

[Here is my journal](https://justpaste.it/aqd6s), there are many crashes and warning at the end coming from KWin and so. [Some screenshots](https://imgur.com/a/mrXPRQM) as well.

I will try not to remove the desktop or touch it if you can reopen the issue.

**Comment by NotAShelf** [comment]
I am also able to reproduce this issue on Nixos 23.11. If this cannot be re-opened, should I make a new issue?

**Comment by IPlayZed** [comment]
Hi, it seems that setting QT Wayland variables causes this. After removing them (in my case from environment.d), it works normally. So I think this is a non-Nix thing.

**Comment by MakiseKurisu** [comment]
@IPlayZed can you provide which variable is causing this? I'm also suffering with black-text-on-white-background in Dolphin's terminal panel. Konsole is proper white-on-black.

**Comment by IPlayZed** [comment]
> @IPlayZed can you provide which variable is causing this? I'm also suffering with black-text-on-white-background in Dolphin's terminal panel. Konsole is proper white-on-black.

You can find them on [Arch Wiki's Wayland page under Qt envvars](https://wiki.archlinux.org/title/Wayland#Qt). I am pretty sure that if any of them were set it might behave incorrectly, but I might remember incorrectly. Also, it is worth checking if [theming envvars](https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications) were set.
