### ISSUE TITLE
Serious Security Bug on TeamSpeak

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#10318]
"We have just released a very important security update for the TeamSpeak 3 Client addressing a RFI (Remote File Inclusion) vulnerability. Please upgrade your desktop clients to version 3.0.18.1 immediately. The update is available for Windows, Linux and OS X. Mobile clients for Android and iOS are not affected by this issue."

http://forum.teamspeak.com/showthread.php/120755

**Comment by matthiasbeyer** [comment]
I'm on it.
