### ISSUE TITLE
Package for gp-saml-gui

### ISSUE THREAD

**Issue by jamal** [NixOS/nixpkgs#103167]
**Project description**
Package for [gp-saml-gui](https://github.com/dlenski/gp-saml-gui) which is a python script to authenticate to GlobalProtect VPN that uses SAML authentication, which is then used with OpenConnect.

**Metadata**

* homepage URL: https://github.com/dlenski/gp-saml-gui
* source URL: https://github.com/dlenski/gp-saml-gui
* license: gpl3
* platforms: linux

**Comment by turion** [comment]
See https://github.com/NixOS/nixpkgs/pull/225888, this has since been added.
