### ISSUE TITLE
rustPlatform.buildRustPackage-based packages: cargoBuildFlags is not overridable

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#103130]
**Describe the bug**
I tried to build i3status-rust with a custom feature and failed. Presumably this is tied to `rustPlatform.buildRustPackage` being weird.

**To Reproduce**
1. `nix build --impure --expr 'let nixpkgs = import (builtins.getFlake "nixpkgs") {}; in nixpkgs.i3status-rust.overrideAttrs (old: { cargoBuildFlags = ["--features=notmuch"]; buildInputs = old.buildInputs ++ [nixpkgs.notmuch]; })'`
2. Launch i3status-rust with following added to the [default config](https://raw.githubusercontent.com/greshake/i3status-rust/master/example_config.toml):
   ```
   [[block]]
   block = "notmuch"
   query = "tag:inbox AND tag:unread"
   threshold_warning = 1
   threshold_critical = 10
   maildir = "~/Maildir"
   interval = 30
   ```
3. Receive error: `Error in block 'notmuch': Unknown block!` signifying that the package was in fact built without the feature.
4. Alternatively, observe `nix log` output for the package - around build phase, the cargo command is printed. The build flags injected are absent.

**Expected behavior**
The build flags from overrideAttrs call are passed to Cargo.

**Screenshots**
n/a

**Additional context**
I assume this is present on every package using the function mentioned in the title.

**Notify maintainers**

cc @globin @backuitist @Ma27 as maintainers of i3status-rust

cc @Mic92 as the one who added `cargoBuildFlags` to the function and is showing up in `git blame`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.2, NixOS, 21.03.20201108.90576ad (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
 - channels(root): `""`
 - channels(vika): `""`
 - nixpkgs: `/nix/store/82mrz2yf5a8zs0b8hhgc8f1b1w4sfkgi-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
 - i3status-rust
 - rustPlatform.buildRustPackage
 - rustPlatform

# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
I just checked and it seems as I can use custom `cargoBuildFlags` on `master` (cf97b2aeec8d838b49c9ef64224ab47b4c09f1b6). @kisik21 can you check if that's still a problem for you? :)

**Comment by asdf8dfafjk** [comment]
Yes, this works fine now (and wasn't working when I subscribed).

**Comment by Ma27** [comment]
I guess we can close it then. @kisik21 in case I misunderstood something and the issue still exists, please let us know.

**Comment by kisik21** [comment]
I can confirm that the problem is resolved, as build logs indicate successful application of Cargo build flags when using the example from my original issue report.
