### ISSUE TITLE
jellyfin: update breaking ffmpeg transcoding

### ISSUE THREAD

**Issue by spacekookie** [NixOS/nixpkgs#103218]
**Describe the bug**

There is a problem with how jellyfin handles the ffmpeg path provided via the `--ffmpeg` cli option used by the nixos module, which means that updates to ffmpeg can break transcoding media.

I have reported the issue to upstream here: https://github.com/jellyfin/jellyfin/issues/4449.

Waiting for a fix from upstream is probably better than hacking around the issue in the jellyfin module, but I thought I'd report this to track the issue for nixos users specifically regardless.

**Comment by alarsyo** [comment]
For other Nix noobs like me looking for a fix to the problem, here's how to find the path to the new ffmpeg binary to set it in Jellyfin's admin interface:

1. run `systemctl status jellyfin`

   This will show you the path to the `jellyfin.service` file in the nix store.

2. `cat /nix/store/the_hash_for_jellyfin.service/jellyfin.service`

   This will show you the path to the `jellyfin` wrapper script in the nix store

3. `cat /nix/store/path_to_wrapper_script/bin/jellyfin`

   This script contains the full path to the currently used ffmpeg binary for this derivation

**Comment by elvetemedve** [comment]
This problem still exists in Nixos 21.11. Though the path to `ffmpeg` executable is correct in the config file `/var/lib/jellyfin/config/encoding.xml`, the configuration could be overridden via the web UI, which won't be changed during a version upgrade.

**Comment by justinas** [comment]
This should be fixed in Jellyfin 10.8.0. See https://github.com/NixOS/nixpkgs/issues/178123#issuecomment-1159814884.

**Comment by bjornfor** [comment]
> This should be fixed in Jellyfin 10.8.0. See [#178123 (comment)](https://github.com/NixOS/nixpkgs/issues/178123#issuecomment-1159814884).

And now that's in stable NixOS 22.11, so closing.
