### ISSUE TITLE
Redshift needs gtk python package

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#10329]
# nixos 16.03
nix-env -i redshift

```
$ redshift-gtk 
ERROR:root:Could not find any typelib for Gtk
Traceback (most recent call last):
  File "/nix/store/zinn3vapx188l4mx4m6q79barxwqa371-redshift-1.10/bin/.redshift-gtk-wrapped", line 26, in <module>
    from redshift_gtk.statusicon import run
  File "/nix/store/zinn3vapx188l4mx4m6q79barxwqa371-redshift-1.10/lib/python3.4/site-packages/redshift_gtk/statusicon.py", line 32, in <module>
    from gi.repository import Gtk, GLib, GObject
ImportError: cannot import name 'Gtk'
```

I've tried to install pygtk and gtk or gtk3, no results. Any ideas how to make gtk available for python global introspection?

**Comment by khumba** [comment]
Do you have the patches from #10097?  And also what channel are you on, see #10280.

**Comment by spinus** [comment]
@khumba thanks for pointing at this (I was looking for redshift issues but forgot to removed "open" filter), sorry about that.

I'm not sure, I use unstable so I think it should be already there but I'll test more over next days.

Is there any easy way to "go" from package name to nix expression (to check it)?

**Comment by khumba** [comment]
From https://nixos.org/channels/, it looks like nixpkgs-unstable is at
d6d88aa and nixos-unstable is at e916273 (which is older than
nixpkgs-unstable).  I'm assuming you're on nixos-unstable.  The
redshift fixes are only a handful of commits ahead of nixos-unstable
currently, but nixpkgs-unstable has them if you want to use that
channel instead.

(There's a separate open bug about the unstable channels being a bit
stale currently.)

I don't have a nice way to find Nix expression sources.  If you're
looking for the package name, git grep 'name = "..."', if you're
looking for the attribute name, search all-packages.nix...

**Comment by khumba** [comment]
"Is there any easy way to "go" from package name to nix expression (to
check it)?"

...and of course `nixos-version` to determine what commit you're at in
nixpkgs.

**Comment by spinus** [comment]
@khumba thanks for explaining this, you are right I was using nixos-unstable (and nixos-version confirmed), I added new channel: nixpkgs-unstable and installed redshift. Redshift seems to start. Thank you for help.

How priority between repositories is determined? How I know from which chanel package will be installed (if there are the same names in all of channels)

**Comment by vcunat** [comment]
It's arbitrary if you're using regular names. When using attribute names (`-A`), the channel name is prefixed...

**Comment by khumba** [comment]
"How priority between repositories is determined?"

That, I have no idea, sorry.  (Honestly I'm just using "-I nixpkgs=/n"
or "-f /n" with every command and ignoring my channel, yes I should
set this permanently :).  Perhaps it puts both package's contents in
NIX_PATH?  If it's smart I'd imagine that attribute name lookups that
fail in one check the other, and that it looks for highest versions in
both... </wild speculation>

**Comment by khumba** [comment]
Oops, didn't see your reply, thanks Vladimír.

**Comment by spinus** [comment]
Thanks guys for explaining this.

**Comment by vcunat** [comment]
:-)
