### ISSUE TITLE
clementine segfaults

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#10326]
Steps to reproduce:

1. On NixOS 15.09, install clementine: ```nix-env -iA nixos.clementine```
2. Run clementine and try to play a song.

The result is this:
```
$ clementine
...
(clementine:14064): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
Segmentation fault
```

(I don't have any gstreamer packages in my profile.)

**Comment by joachifm** [comment]
Still an issue?

**Comment by RubenAstudillo** [comment]
I can confirm this. Recently changed from XMonad to kde5 and now clementine fails with such assertion. Will checkout what is happening.

**Comment by bjornfor** [comment]
Tested on recent NixOS 16.03 and 16.09pre: clementine can play the two .mp3 files I gave it. No segfault.

@RubenAstudillo: If you still have segfault, let us know.

**Comment by RubenAstudillo** [comment]
I got the error down.  Somehow I got`nixos.clementine` without the `gstreamer-plugin-bad` codecs. Obviously I wouldn't play mp3 files!.

**Comment by castilma** [comment]
i have this problem with clementinefree.
