### ISSUE TITLE
Nixpkgs use 2 different fix-points with unclear separation.

### ISSUE THREAD

**Issue by nbp** [NixOS/nixpkgs#10323]
While looking in nixpkgs, I noticed that we use 2 different fix-point strategy, and the difference between the 2 is not clear.  #10307 highlight that there is a problem with `self` and `pkgs` are almost interchangeable but it is not clear why replacing one by the other does not work.

The problem is more than likely coming from the stdenv overrides added by the `mkOverrides` function.  The way this function is written would cause infinite loops if we were to use `pkgs` instead of `pkgsOrig` because the name of the properties are not known ahead.

The problem here is not much about having 2 self-reference fix-points, but mostly about the fact that the first stage (`pkgsOrig = pkgsFun pkgs {};`) does not have a proper meaning for the 2 self-references.  In the first stage, `pkgs` is the overloaded set of packages, while `self` is the non overloaded set of packages.

These 2 self-references are extremely confusing since `self` and `pkgs` are used interchangeably to lookup dependencies within `all-packages.nix`, either by relying on `with self;` or on `callPackage` (`pkgs`).

I will recommend that we convert one to the other and make them explicit within `all-packages.nix`, such that we can give a clear meaning to the first stage (`pkgsOrig`) which is used to compute the `stdenv`.

cc @edolstra

**Comment by Mathnerd314** [comment]
I implemented this already in https://github.com/NixOS/nixpkgs/pull/9400; I have a recent version sitting around somewhere...

**Comment by Mathnerd314** [comment]
And now #9400 is merged, so this can be closed.
