### ISSUE TITLE
nextcloud: feature request for extraConfig option

### ISSUE THREAD

**Issue by nivadis** [NixOS/nixpkgs#103320]
## Issue description
it would be nice to have an option to set other nextcloud parameters within the services.nextcloud 
e.g. 'lost_password_link' => 'disabled'

**Comment by nivadis** [comment]
as mentioned by @aanderse in https://github.com/NixOS/nixpkgs/pull/103323#discussion_r521304325_
a ```settings``` option would be nice

**Comment by onny** [comment]
Is this fixed by https://github.com/NixOS/nixpkgs/pull/118093 ?

**Comment by vikanezrimaya** [comment]
> Is this fixed by https://github.com/NixOS/nixpkgs/pull/118093 ?

Should fix my use cases, at least.
