### ISSUE TITLE
error on nix-env -u after channel update

### ISSUE THREAD

**Issue by houqp** [NixOS/nixpkgs#10337]
I am getting following error after a channel update:

```
error: attribute ‘replaceStrings’ missing, at /nix/store/22a8s3q4zvjkcrbpnv9dx8damc0mrzf9-nixpkgs-16.03pre70277.3d0c064/nixpkgs/pkgs/applications/editors/geany/with-vte.nix:2:12
```

How can I help debug this issue? FWIW:

```
 $ nix-channel --version
nix-channel (Nix) 1.9

 $ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by vcunat** [comment]
That package is trying to use `builtins.replaceStrings` which only became available with nix-1.10, so you need to upgrade it to evaluate it.

**Comment by vcunat** [comment]
- https://nixos.org/wiki/How_to_update_when_nix_is_too_old_to_evaluate_nixpkgs

**Comment by houqp** [comment]
Thanks for the quick tip, it works now :+1:

**Comment by viric** [comment]
This went to release-15.09: 729ec1ece247741687282b211bee5661b9d670ce

Should really nixpkgs 15.09 require nix 1.10? Wasn't this intended for master alone?

**Comment by edolstra** [comment]
@viric I've reverted it on the 15.09 branch, turns out it wasn't actually needed.
