### ISSUE TITLE
Python: fix packages that use poetry as build backend to use poetry-core

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#103325]
**Describe the bug**
The build backend for Poetry was split out into a separate package, `poetry-core`. Unfortunately, most packages requiring it, still refer to `poetry.masonry.api` instead of the preferred `poetry.core.masonry.api`.

Note these are upstream bugs

**Comment by FRidh** [comment]
Examples
- https://github.com/litl/backoff/issues/110
- https://github.com/pawamoy/aria2p/issues/75
- https://github.com/supakeen/pinnwand/issues/101
- https://github.com/srstevenson/xdg/issues/43

**Comment by FRidh** [comment]
waiting for 1.2.3 of https://github.com/supakeen/pinnwand/issues/101

**Comment by mweinelt** [comment]
- https://github.com/thebigmunch/audio-metadata/pull/41
- https://github.com/thebigmunch/tbm-utils/issues/2
