### ISSUE TITLE
perl aspell package

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#10335]
My nix-foo wasn't strong enough to get this package building.
This is where I got to in perl-packages. It can build the module, however fails on a handful of tests because aspell can't find the en_US dictionary, I think because of #1000
It would be handy if someone who's a little more knowledgeable about this could take a look.

```
  TextAspell = buildPerlPackage rec {
    name = "Text-Aspell-0.09";
    src = fetchurl {
      url = "mirror://cpan/authors/id/H/HA/HANK/${name}.tar.gz";
      sha256 = "0r9g31rd55934mp6n45b96g934ck4qns8x9i7qckn9wfy44k5sib";
    };
    buildInputs = [ pkgs.aspellDicts.en ];
    propagatedBuildInputs = [ pkgs.aspell ];
    NIX_CFLAGS_COMPILE = "-I${pkgs.aspell}/include";
    NIX_CFLAGS_LINK = "-L${pkgs.aspell}/lib -laspell";
  };
```

**Comment by pSub** [comment]
I have pushed a working version in 0c248d1cb154aab1f1d65aacf208e6b0346a8ec5 to master.

**Comment by expipiplus1** [comment]
Thanks!
