### ISSUE TITLE
Upgrade existing version of hsetroot 1.0.2 to 1.0.5

### ISSUE THREAD

**Issue by SeraphyBR** [NixOS/nixpkgs#103457]
**Project description**
Allows you to compose wallpapers ('root pixmaps') for X

**Metadata**

* homepage URL: https://github.com/himdel/hsetroot
* source URL: https://github.com/himdel/hsetroot
* license: gpl2+
* platforms: unix

**Comment by matthiasbeyer** [comment]
This can be closed.
