### ISSUE TITLE
Ferdi: missing dependency

### ISSUE THREAD

**Issue by Mazurel** [NixOS/nixpkgs#103440]
**Describe the bug**
Ferdi is missing sqlite dependecy when running without an online account.

```bash
$ nix-env --query | grep ferdi
ferdi-5.5.0
$ ferdi
Gtk-Message: 12:55:57.238: Failed to load module "canberra-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:11024) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:11024) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:11024) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:11024) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Starting local server on port 45569
Knex: run
$ npm install sqlite3 --save
Error: libstdc++.so.6: cannot open shared object file: No such file or directory
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/nix/store/zhqskvfxn74syxhfck1910pigffkrdac-ferdi-5.5.0/opt/Ferdi/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
info: serving app on http://127.0.0.1:45569
```

**To Reproduce**
1. Install ferdi.
2. Select "Use Ferdi without an Account"
3. Crash (stderr above)

**Expected behavior**
Not crash.

**Additional context**
When selecting any other option, Ferdi works correctly.

If you have got the same issue and want to select some other option, all you need to do is to remove config files:
```bash
rm -rf ~/.config/Ferdi
```

**Notify maintainers**
@davidtwco 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.75, NixOS, 21.03.git.945f9c5f615 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(mateusz): `"home-manager, nixpkgs-21.03pre250878.a52e974cff8"`
 - channels(root): `"home-manager, nixos-21.03pre250878.a52e974cff8, nixos-hardware"`
 - nixpkgs: `/home/mateusz/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: franz
# a list of nixos modules affected by the problem
module:
```

**Comment by davidtwco** [comment]
I can reproduce this with Ferdi 5.5.0 as packaged in nixpkgs currently, but I've noticed that it doesn't occur with Ferdi 5.6.0-beta.2, you might consider adding [this snippet](https://github.com/NixOS/nixpkgs/issues/102969#issuecomment-723578590) to your configuration to use that newer version of Ferdi.

**Comment by bryanasdev000** [comment]
> I can reproduce this with Ferdi 5.5.0 as packaged in nixpkgs currently, but I've noticed that it doesn't occur with Ferdi 5.6.0-beta.2, you might consider adding [this snippet](https://github.com/NixOS/nixpkgs/issues/102969#issuecomment-723578590) to your configuration to use that newer version of Ferdi.

I can still reproduce the problem using your snippet for the beta, even removing the old settings.

It was like that after my last switch, it seems to me was a change external to Ferdi.

**Comment by bryanasdev000** [comment]
After my last update on NixOS the application is back up and running! :D

With the @davidtwco snippet the features that were broken are also ok, however for the use of WhatsApp I had to use the solution of that issue: https://github.com/getferdi/ferdi/issues/1061

**Comment by Ekleog** [comment]
If I understand correctly this is now fixed on the NixOS side, and what remains is issues in ferdi upstream. Closing, feel free to reopen if this was a mistake on my side!

Thank you for all this feedback :)
