### ISSUE TITLE
Changing defaultGateway does not apply on `switch`

### ISSUE THREAD

**Issue by ctheune** [NixOS/nixpkgs#10344]
I changed the defaultGateway and applied nixos-rebuild switch. This did not cause the default gateway to change. :(

**Comment by ctheune** [comment]
AFAICT this has two parts:

a) the network-setup unit was not triggered
b) even triggering network-setup manually did not cause a change as long as the old default route was still active (the old route was a wrong IP on the same subnet as the new one). Looking at the start script - it seems overly simple and not able to handle this case.

**Comment by copumpkin** [comment]
Reminds me of another "basic networking" setting that was painful to change through `switch`: https://github.com/NixOS/nixpkgs/issues/6830. Mine might be unrelated though.

**Comment by ctheune** [comment]
I think it's at least related on a conceptual level. They have different activation scripts, but those scripts seem not very well integrated. Unfortunately my kung fu isn't strong enough yet: neither my systemd knowledge nor the intentions of the activation scripts are clear to me to make a fix.

**Comment by Profpatsch** [comment]
(triage) has this been fixed in the meantime?

**Comment by ctheune** [comment]
thanks for asking - no idea, too long ago :)

**Comment by globin** [comment]
This is fixed on unstable.
