### ISSUE TITLE
Hard-coded /usr, /etc, etc. paths in Zotero

### ISSUE THREAD

**Issue by Warbo** [NixOS/nixpkgs#10355]
Zotero (`nix-shell -p zotero`) seems to have a few issues, at least in my Xmonad-based system (not sure if it works in KDE, Gnome, etc.)

Problems include:
- All attempts at importing seem to fail with "The selected file is not in a supported format" (eg. for BibTeX and PDF, from files and from the clipboard)
- Choosing "Export item", the "Format" drop-down box is empty (ie. doesn't provide any options)
- Many buttons/actions in Zotero try to open a browser, but they fail (with a message like `** (zotero:2956): WARNING **: Could not launch default application for URI: Operation not supported`

At least some of these seem to be caused by hard-coded paths. For example, in about:config (Tools->Preferences->Advanced->open about:config) the following options have hard-coded values which don't exist in NixOS:
- `helpers.global_mime_types_file` = `/etc/mime.types`
- `extensions.zotero.fallbackLauncher.unix` = `/usr/bin/xdg-open`

Setting the latter to a real `xdg-open` path (eg. `/run/current-system/sw/bin/xdg-open`) makes opening a browser work.

**Comment by Warbo** [comment]
Additionally, Zotero uses (at least) the "pdftext" and "pdfinfo" commands. It provides an action in Tools -> Preferences -> Search to download pre-build binaries of these tools, but they fail with a "No such file or directory" error (presumably due to assuming a dynamic library path which doesn't exist on NixOS).

I tried swapping out these downloaded binaries for symlinks into /nix/store. The pdftext tool seems to work, but pdfinfo just prints a usage message (presumably because it's being called with an extra argument, rather than just the PDF)

**Comment by Warbo** [comment]
Replacing the pdfinfo binary (`pdfinfo-Linux-i686`) with the following shell script seems to work:

    #!/usr/bin/env bash
    pdfinfo "$1" > "$2"

**Comment by devhell** [comment]
Not the most elegant or ideal [solution](https://nixos.org/wiki/Zotero). Just fyi.

**Comment by Profpatsch** [comment]
(triage) is that still an issue?

**Comment by c0bw3b** [comment]
@Warbo PR #31699 might have solved this issue by running Zotero inside an FHS env.

**Comment by devhell** [comment]
@c0bw3b, @Warbo; Indeed it seems solved, I successfully installed those tools from within Zotero without an issue. The only thing I haven't been able to work out yet is how to make Zotero find Libreoffice so the Libreoffice plugin works. Not a big deal for me as I use LaTeX for all my writing, but I'm sure others do use LO.
