### ISSUE TITLE
Amarok: no sound when trying to play files

### ISSUE THREAD

**Issue by LuisChDev** [NixOS/nixpkgs#103543]
**Describe the bug**
As of 2020/11/11 on Nixos 20.09, Amarok does not output any sound.
opening it with `amarok --debug` and trying to play any file yields the following:

    amarok: BEGIN: void Playlist::PrettyListView::trackActivated(const QModelIndex&)
    amarok:   BEGIN: void Playlist::Actions::play(const QModelIndex&)
    amarok:     BEGIN: void Playlist::Actions::play(quint64, bool)
    amarok:       BEGIN: void EngineController::play(Meta::TrackPtr, uint, bool)
    amarok:         BEGIN: void EngineController::stop(bool, bool)
    WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
    WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
    amarok:         END__: void EngineController::stop(bool, bool) [Took: 0.003s]
    amarok:         [EngineController] play: bounded is  QObject(0x0) current "Floe"
    amarok:         [EngineController] Just a normal, boring track... :-P
    amarok:         BEGIN: void EngineController::playUrl(const QUrl&, uint, bool)
    WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
    amarok:           [EngineController] URL:  QUrl("file:///home/xyz/Music/foo/bar/Floe.mp3") "file:///home/xyz/Music/foo/bar/Floe.mp3"
    amarok:           [EngineController] Offset:  0
    WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
    WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
    amarok:         END__: void EngineController::playUrl(const QUrl&, uint, bool) [Took: 0.005s]
    amarok:       END__: void EngineController::play(Meta::TrackPtr, uint, bool) [Took: 0.009s]
    amarok:     END__: void Playlist::Actions::play(quint64, bool) [Took: 0.009s]
    amarok:   END__: void Playlist::Actions::play(const QModelIndex&) [Took: 0.009s]
    amarok: END__: void Playlist::PrettyListView::trackActivated(const QModelIndex&) [Took: 0.009s]

entering Settings > configure Amarok > Playback > Configure Phonon yields an empty pop up window:
![image](https://user-images.githubusercontent.com/24978009/98890800-cc70a600-246a-11eb-852e-7efa8676227f.png)

which might be the culprit.

**To Reproduce**
1. install Amarok from the current release, `nix-env -iA nixos.amarok` or declaratively, by placing `amarok` on `configuration.nix`, in `environment.systemPackages`.
2. open it.
3. play anything.

**Expected behavior**
playback, pop up notification.

**Screenshots**
Above.

**Additional context**

**Notify maintainers**
@peterhoeg 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.75, NixOS, 20.09.1693.d12178b1c4a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1698.96052f35023"`
 - channels(xyz): `"amarok-unstable-2020-06-12, nixos-20.09.1693.d12178b1c4a, old-nixos-20.03.3232.18f8c1fe060, unstable-21.03pre250093.0da76dab4c2, my-packages"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: amarok
# a list of nixos modules affected by the problem
module:
```

**Comment by ryneeverett** [comment]
I can reproduce this on 20.09 but not on unstable (presumably as of #116413). In 2.9.71 the "Configure Phonon" configuration is gone but it just works.

If you're not on kde you'll need to manually install `libsForQt5.phonon-backend-gstreamer` or `libsForQt5.phonon-backend-vlc`. It seems that vlc may require pulseaudio to be enabled but I prefer gstreamer so I didn't test it out.

**Comment by LuisChDev** [comment]
yep, just updated to latest unstable and it works. I suppose it'll still work in 21.05 so I'm closing this.

**Comment by LorenzoBettini** [comment]
I'm experiencing the same problem:

```
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
```

I've installed amarok with nix in KDE Neon (I hope these issues are also for Nix packages on other OSes), with

```
nix-env -iA nixpkgs.amarok
```

First of all, I need to start amarok like that to avoid the error "Could not initialize GLX":

```
QT_XCB_GL_INTEGRATION=none amarok
```

On KDE Neon I tried installing `phonon-backend-gstreamer` and `phonon-backend-vlc`, but nothing changes... Amarok does not play anything.
