### ISSUE TITLE
unstable channel hasn't updated for 14+ days

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#10353]
The [unstable-channel](https://github.com/NixOS/nixpkgs-channels) is stuck at commit e916273209560b302ab231606babf5ce1c481f08, mostly because of [test failures](https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents) related to GNOME3, but several other tests have failed in an on/off fashion, too.

**Comment by vcunat** [comment]
That's a bug preventing OpenGL in a 32-bit qemu (see e.g. discussion on #9983). We have bumps fixing this in staging IIRC, but staging failed completely due to full disk several days ago and noone has restarted the jobs yet, so there are no binaries in sight.

**Comment by vcunat** [comment]
We might disable that test for a while on master.

**Comment by peti** [comment]
I tried to restart those 40176 staging builds, but the Hydra web front can't do it. It constructs an SQL command that's too big for the database server to execute, and then all I get is "internal error".

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by domenkozar** [comment]
Just for reference:

```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR: stack depth limit exceeded
HINT: Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate. [for Statement "UPDATE Builds SET busy = ?, finished = ?, iscachedbuild = ?, locker = ? WHERE ( ( id = ? ...
```

**Comment by edolstra** [comment]
The staging thing is a separate issue. Right now, the only thing that blocks the unstable channel is nixos.tests.gnome3.i686-linux: http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents

**Comment by peti** [comment]
Well, word has it that `staging` contains a fix for the gnome3 test failure, so the fact we cannot merge it to `master` seems relevant for this issue.

**Comment by vcunat** [comment]
Updated

**Comment by vcunat** [comment]
> I tried to restart those 40176 staging builds, but the Hydra web front-end can't do it.

Would you try restarting staging now? After some updates, there are <19k abortions.
