### ISSUE TITLE
Regenerate Node packages

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#10358]
I can't build `parsoid` service on `master` now (`contextify` fails to build), and there is a new '0.4.0' version in the wild so regeneration might fix things. Unfortunately, I've stumbled into errors one after another while trying to regenerate by myself.

cc @offlinehacker (last person who regenerated packages)

**Comment by abbradar** [comment]
I've pushed https://github.com/NixOS/nixpkgs/commit/763ad3372a9719f1187d800edbbb21a82180b143 as a workaround for now.

**Comment by cstrahan** [comment]
I have some patches in the works for `npm2nix`. Should be able to regenerate soon.

**Comment by Profpatsch** [comment]
(triage) might be already fixed. Also, npm2nix will change in the near future.

**Comment by abbradar** [comment]
Let's close, I've managed to rebuild it.
