### ISSUE TITLE
perl: method to get the module directory

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#10350]
I'm overriding irssi in order to make the perl package Text::Aspell available to it like this:

```
    irssi = pkgs.stdenv.lib.overrideDerivation pkgs.irssi (oldAttrs: {
      buildInputs = oldAttrs.buildInputs ++ 
                    [ pkgs.aspell
                      pkgs.perlPackages.TextAspell
                      pkgs.makeWrapper 
                    ];
      postInstall = 
        ''
          wrapProgram "$out/bin/irssi" \
            --prefix PERL5LIB : ${pkgs.perlPackages.TextAspell}/lib/perl5/site_perl/5.20.2/x86_64-linux-thread-multi
        '';
    });
```

Having to put `lib/perl5/site_perl/5.20.2/x86_64-linux-thread-multi` feels really horrible, but I couldn't find a way of programmatically getting that path. Have I missed something?

**Comment by vcunat** [comment]
You've missed `perl.libPrefix`. I suppose it's easiest to append `/*/*` or something like that.

**Comment by Profpatsch** [comment]
(triage) can be closed.

**Comment by expipiplus1** [comment]
libprefix works well enough
