### ISSUE TITLE
TeamSpeak 3, missing libquazip.so

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#10356]
Hi there

Being on unstable-small I get now this issue when I try to start TS3:

hyper@subi:~$ ts3client
/run/current-system/sw/bin/ts3client: error while loading shared libraries: libquazip.so: cannot open shared object file: No such file or directory
hyper@subi:~$ ts3client --version
/run/current-system/sw/bin/ts3client: error while loading shared libraries: libquazip.so: cannot open shared object file: No such file or directory
hyper@subi:~$ ls -al /run/current-system/sw/bin/ts3client
lrwxrwxrwx 1 root nixbld 83 Jan  1  1970 /run/current-system/sw/bin/ts3client -> /nix/store/7qii5fzpijkx4j8rkm5is3wjgvlklkr6-teamspeak-client-3.0.18.1/bin/ts3client

**Comment by domenkozar** [comment]
@matthiasbeyer

**Comment by matthiasbeyer** [comment]
On it.

**Comment by matthiasbeyer** [comment]
I can reproduce, though `quazip` is in the `installPhase` linked. If I put `quazip` in the `buildInputs`, nothing changes.

Maybe the package maintainer should have a look at it: @nathanielbaxter

**Comment by sjau** [comment]
Hmmm, the file you can download from TS3 and extract includes a libquazip.so file. Maybe it wants to use that one?

![ts3](https://cloud.githubusercontent.com/assets/848812/10448535/c1e070fc-718d-11e5-8a56-69b1331c3f4e.png)

**Comment by matthiasbeyer** [comment]
@sjau Just tried that, results in:

```
$ ./result/bin/ts3client
./result/bin/ts3client: symbol lookup error: ./result/bin/ts3client: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject
```

**Comment by matthiasbeyer** [comment]
Hm, sorry, I don't know how to fix this. Going back to the previous version is no solution, as the previous version is vulnerable.

**Comment by peti** [comment]
If in doubt, we should mark the package broken. :disappointed:

**Comment by matthiasbeyer** [comment]
:cry:

**Comment by sjau** [comment]
but but but I need TS3 ;(

**Comment by nathanielbaxter** [comment]
Teamspeak 3.0.17 broke the use of nix provided quazip and qt libs (teamspeak wants to provide it's own but generally I prefer that we avoid using provided binaries when we can avoid it), hadn't gotten around to fixing it.

Fixed in #10372

**Comment by peti** [comment]
@sjau, does 424be52044fab5ce9a61584b88f14bb5b771886d fix the issue for you?

**Comment by sjau** [comment]
@peti 
works fine now :) thx
