### ISSUE TITLE
Include the manual on tty8 in default config?

### ISSUE THREAD

**Issue by fps** [NixOS/nixpkgs#10354]
Hi,

having the manual available on tty8 is very useful during the installation. It would be almost as useful to have it in the installed system as well. I suppose this option would be simple enough to disable for users that do not want it, but might help new users tremendously (I missed it).

<pre>
  services.nixosManual.showManual = true;
</pre>

Maybe even have the same hint as in the installation environment printed out on console until the user disables it (so people are reminded that they have the manual available on tty8 at all times)?

Another option would maybe be to have a text based browser like links or w3w installed per default, so nixos-help works out of the box on a freshly installed system?

**Comment by joachifm** [comment]
Please submit a PR
