### ISSUE TITLE
subtitleeditor produces an error upon an attempt to edit a subtitle

### ISSUE THREAD

**Issue by herzen** [NixOS/nixpkgs#10357]
To reproduce:

(1) Start subtitleeditor from a terminal so that error messages can be read.
(2) Choose "New" from the "File" menu.
(3) Choose "Insert after" from the "Edit" menu.
(4) Choose "Edit cell" from the "Edit" menu.

Result:

Nothing changes in the subtitle display area (a new space is supposed to be opened there in which you can edit the chosen subtitle), the menu bar disappears, and the following error gets reported in the terminal:

(.subtitleeditor-wrapped:2171): Gtk-CRITICAL *_: gtk_tree_view_column_cell_process_action: assertion 'GTK_IS_CELL_EDITABLE (_editable_widget)' failed

This is with subtitleeditor 0.41.0 on NixOS 14.12.885. When I do the same thing on Arch Linux (which is at version 0.52.1), an area gets opened for typing the contents of a subtitle, and a subtitle gets created.

**Comment by Profpatsch** [comment]
triage: does this still happen?
