### ISSUE TITLE
kitty tests fail on Darwin

### ISSUE THREAD

**Issue by eraserhd** [NixOS/nixpkgs#103638]
**Describe the bug**

Kitty's tests fail on Darwin on my system (using `master`).  AFAICT, it is working on hydra.  I've been using this derivation for a while without issues.

The test that fails has to do with falling back to a "last resort" font, and this started happening after installing "Input Fonts" on my system (through Nix and home-manager).   I've tried removing the font in Font Manager, but that doesn't fix the issue, so this might not be the problem.

**To Reproduce**

```
nix-build . -A kitty
```

**Expected behavior**

Tests pass.

**Screenshots**

```
test_shaping (kitty_tests.fonts.Rendering) ... ok
test_sprite_map (kitty_tests.fonts.Rendering) ... ok
test_utf_8_strndup (kitty_tests.glfw.TestGLFW) ... skipped 'Skipping test on macOS because glfw-cocoa.so is not built with backend_utils'

======================================================================
FAIL: test_fallback_font_not_last_resort (kitty_tests.fonts.Rendering)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-kitty-0.19.1.drv-0/source/kitty_tests/fonts.py", line 123, in test_fallback_font_not_last_resort
    self.assertRaises(ValueError, get_fallback_font, '\U0010FFFF', False, False)
    StringIO = <class '_io.StringIO'>
    buf = <_io.StringIO object at 0x1098b8700>
    orig = <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
    self = <kitty_tests.fonts.Rendering testMethod=test_fallback_font_not_last_resort>
AssertionError: ValueError not raised by get_fallback_font

----------------------------------------------------------------------
Ran 82 tests in 1.569s

FAILED (failures=1, skipped=1)
builder for '/nix/store/nsm2xk465aali089lz46dyafhzpb5sk4-kitty-0.19.1.drv' failed with exit code 1
building '/nix/store/vd3xzgi2vrmnmvvwg1w90cim5p1845lc-kitty-0.19.1.drv'...
cannot build derivation '/nix/store/2z8jif1mi1178w8lakzp9ni8dyiy8bn8-system-applications.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/29vhmjb7cwm8j6ms8kndkn3wa1r35sfn-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4yw2lk4457v7j5bxhsvb977s5n7g9kfd-darwin-system-21.03.git.9b44093+darwin4.56f0169.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4yw2lk4457v7j5bxhsvb977s5n7g9kfd-darwin-system-21.03.git.9b44093+darwin4.56f0169.drv' failed
```

**Notify maintainers**

@tex @rvolosatovs @Luflosi 

**Metadata**

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixpkgs-20.09pre240394.ca3fa9c32a4"`
 - nixpkgs: `/Users/jfelice/src/dotfiles/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- kitty
- input-fonts
```

**Comment by eraserhd** [comment]
I fogot to mention that I can build and run the tests successfully from the source distribution.  I'm quite puzzled.

**Comment by eraserhd** [comment]
To be clear, I used `nix-shell --pure ../dotfiles/nixpkgs -A kitty` and ran the build and check commands from the derivation, and they work.

Could it be that execution context for a multi-user build??

**Comment by eraserhd** [comment]
@kovidgoyal Thoughts on what could cause the above test failure, apparently only in some contexts on some Macs?

**Comment by eraserhd** [comment]
As a side note, it seems impossible to disable the tests.  I've tried every combination of `overrideAttrs`, `overridePythonAttrs`, `doCheck = false;`, `checkPhase = ":";` before commenting out `checkPhase` in the nixpkgs derivation.

**Comment by veprbl** [comment]
> As a side note, it seems impossible to disable the tests. I've tried every combination of `overrideAttrs`, `overridePythonAttrs`, `doCheck = false;`, `checkPhase = ":";` before commenting out `checkPhase` in the nixpkgs derivation.

It's `doInstallCheck`. Though I wonder why `overridePythonAttrs` didn't work with `doCheck`.

**Comment by Luflosi** [comment]
Does it fail reliably?
Try applying this patch to kitty and see if it prints a font while executing the tests:
```diff
diff --git a/kitty_tests/fonts.py b/kitty_tests/fonts.py
index eea9feaa..b526f6a1 100644
--- a/kitty_tests/fonts.py
+++ b/kitty_tests/fonts.py
@@ -120,7 +120,7 @@ def test_fallback_font_not_last_resort(self):
         orig, buf = sys.stderr, StringIO()
         sys.stderr = buf
         try:
-            self.assertRaises(ValueError, get_fallback_font, '\U0010FFFF', False, False)
+            print(get_fallback_font('\U0010FFFF', False, False))
         finally:
             sys.stderr = orig
         self.assertIn('LastResort', buf.getvalue())
```
Some other things you could try:
Somehow find out if any of your fonts, especially "Input Fonts" contains the symbol that can be printed with `python -c "print('\U0010FFFF')"`. `kitty --config NONE --debug-font-fallback python -c "print('\U0010FFFF');input()"` may or may not help you with that, not sure.
What happens when you modify the code of kitty in `kitty_tests/fonts.py`, line 123 and change the value in the string slightly?

**Comment by eraserhd** [comment]
* It fails every time.
* These commands don't echo visible characters.
* The output with `--debug-font-fallback` is:

```
[317 16:58:40.902534] Preloaded font faces:
[317 16:58:40.902566] normal face: /Library/Fonts/InputMonoNarrow-Light.ttf
[317 16:58:40.902576] bold face: /Library/Fonts/InputMonoNarrow-Medium.ttf
[317 16:58:40.902584] italic face: /Library/Fonts/InputMonoNarrow-LightItalic.ttf
[317 16:58:40.902592] bi face: /Library/Fonts/InputMonoNarrow-MediumItalic.ttf
```

* The output with `--config NONE --debug-font-fallback` is:

```
    [317 16:40:36.648270] Preloaded font faces:
    [317 16:40:36.648303] normal face: /System/Library/Fonts/Menlo.ttc
    [317 16:40:36.648312] bold face: /System/Library/Fonts/Menlo.ttc
    [317 16:40:36.648321] italic face: /System/Library/Fonts/Menlo.ttc
    [317 16:40:36.648328] bi face: /System/Library/Fonts/Menlo.ttc
```

None of the fonts have this character, at least in Font Book, if I paste "x\U0010FFFFx", the fonts render like so:

![Screen Shot 2020-11-12 at 4 51 46 PM](https://user-images.githubusercontent.com/147284/99000487-5cfcc400-2507-11eb-9546-11ad2b73da82.png)

However, in the kitty that I just built (disabling the tests), it looks like this:

![Screen Shot 2020-11-12 at 4 52 48 PM](https://user-images.githubusercontent.com/147284/99000585-8289cd80-2507-11eb-97f2-79ddbff6bb9f.png)

Just checked by running a few old builds of kitty from the store, and none of them print a character.

Trying the patch next.

**Comment by eraserhd** [comment]
This is the fallback font:

```
Face(family=JuliaMono, full_name=JuliaMono Light, postscript_name=JuliaMono-Light, path=/Library/Fonts/JuliaMono-Light.ttf, units_per_em=2048, ascent=12.2, descent=3.7, leading=0.1, point_sz=0.0, scaled_point_sz=14.7, underline_position=-1.0 underline_thickness=0.1)
```

Funny thing is that I had it installed earlier, but I removed it, Font Book says it is not installed and the files cannot be located by `mdfind`... 

Time to reboot, *sigh*

**Comment by eraserhd** [comment]
Solved by reboot.  Logging out was not sufficient.  Will see if installing JuliaMono causes that test to fail and report upstream if so.
