### ISSUE TITLE
Can't build ISO from channel, only from git checkout

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#10367]
It's currently not possible to build an ISO when `<nixpkgs>` resolves to channel. In other words, while this works:

    nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-minimal.nix

... this will not work:

    $ nix-instantiate --find-file 'nixpkgs'
    /nix/store/c0ivz81b5x0xfn2i9649y6r30l1im6l5-nixos-16.03pre68117.c839c98/nixos/nixpkgs
    
    $ nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=$(nix-instantiate --find-file nixpkgs)/nixos/modules/installer/cd-dvd/installation-cd-minimal.nix
    ...
    building path(s) ‘/nix/store/zz0hzi5imrg4927v6f8mv281qs6v6pbq-nixos-16.03pre69762.e916273’
    ln: failed to create symbolic link '/nix/store/zz0hzi5imrg4927v6f8mv281qs6v6pbq-nixos-16.03pre69762.e916273/nixos/nixpkgs/.': File exists
    builder for ‘/nix/store/kzsscdcfzsj5nv01px01232wmfilnz8n-nixos-16.03pre69762.e916273.drv’ failed with exit code 1

The source of the failure: [`nixos/modules/installer/cd-dvd/channel.nix`](https://github.com/NixOS/nixpkgs/blob/e916273209560b302ab231606babf5ce1c481f08/nixos/modules/installer/cd-dvd/channel.nix#L20).

Evidently, when `<nixpkgs>` points at a channel, `$out/nixos/nixpkgs` already exists. I'm not entirely sure, but I think the fix might be as simple as making the `ln` invokation predicated on the absence of `$out/nixos/nixpkgs`:

```bash
if [ ! -e $out/nixos/nixpkgs ]; then
  ln -s . $out/nixos/nixpkgs
fi
```

**Comment by cstrahan** [comment]
I'm almost positive that this used to work at some point. I *think* that this commit might have introduced this regression: https://github.com/NixOS/nixpkgs/commit/2cd7c1f19888ae73bf7ef0f41a45680cfb86334a.

**Comment by puffnfresh** [comment]
Just hit this problem again, @cstrahan thanks for taking it on :+1:

**Comment by domenkozar** [comment]
I've pushed a fix to master, if everything works correctly I'll cherry-pick it later to 15.09
