### ISSUE TITLE
termite - vte patch fails to apply.

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#103643]
**Describe the bug**
When building termite, one of the patches fails to apply.

**To Reproduce**
1. `cd nixpkgs`
2. `git checkout 0ffb6e494aa`
3. `nix build -f default.nix termite`

**Screenshots**

```
builder for '/nix/store/nb249d73lca7qw610arsf87vcc5hxscs-vte-0.62.1.drv' failed with exit code 1; last 10 log lines:
  patching file src/vte/vteterminal.h
  Hunk #1 succeeded at 190 with fuzz 2 (offset 15 lines).
  patching file src/vtegtk.cc
  Hunk #1 succeeded at 3574 with fuzz 1 (offset 794 lines).
  applying patch /nix/store/8jgzr7c9vylyywa82dr2vx8nsx3jlvmc-0002-expose-function-for-setting-cursor-position.patch
  patching file src/vte/vteterminal.h
  Hunk #1 FAILED at 378.
  1 out of 1 hunk FAILED -- saving rejects to file src/vte/vteterminal.h.rej
  patching file src/vtegtk.cc
  Hunk #1 succeeded at 3077 with fuzz 1 (offset 662 lines).
cannot build derivation '/nix/store/yp1kh1cf92148s7jxci7kq31q1pcr4p9-termite-15.drv': 1 dependencies couldn't be built
[0 built (1 failed)]
error: build of '/nix/store/yp1kh1cf92148s7jxci7kq31q1pcr4p9-termite-15.drv' failed
```

**Notify maintainers**
@koral

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.6, NixOS, 21.03.git.0ffb6e494aa (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - nixpkgs: `/home/emmanuel/projects/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - termite
# a list of nixos modules affected by the problem
module:
```

**Comment by JJJollyjim** [comment]
https://github.com/thestinger/termite/issues/760

Upstream hasn't updated the vte-ng patchset past 0.56 (I guess the same patches happened to work up until 0.62?), looks like it's ~unmaintained -- perhaps we should just keep vte 0.60 around for vte-ng?

**Comment by JJJollyjim** [comment]
Nevermind, it was actually pretty easy to update - PRing
