### ISSUE TITLE
Should we update alacritty to 0.6.0rc-1?

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#103785]
## Issue description

https://github.com/alacritty/alacritty/issues/4312

Experienced on gnome3.38 which is currently on master. alacritty 0.5.0 isn't functional at all. 0.6.0rc-1 is. Should we update in order to make our packages set functional? Or should we wait for a real, no rc release upstream?

https://github.com/alacritty/alacritty/issues/4312

@Br1ght0ne @mic92 @cole-h @ma27

**Comment by doronbehar** [comment]
@Br1ght0ne you should update yourself in the maintainers list - I had to go to https://api.github.com/user/12615679 to see who is @filalex77 .

**Comment by Mic92** [comment]
Is this a wayland issue on gnome?

**Comment by doronbehar** [comment]
Yes.

**Comment by Mic92** [comment]
Sound fine to me.

**Comment by Br1ght0ne** [comment]
> 
> 
> @Br1ght0ne you should update yourself in the maintainers list - I had to go to [api.github.com/user/12615679](https://api.github.com/user/12615679) to see who is @filalex77 .

Thanks for pointing this out. As much as I want to see my first username long gone, the change was not worth it :)
