### ISSUE TITLE
Can't enable copy-com service

### ISSUE THREAD

**Issue by wedens** [NixOS/nixpkgs#10379]
I can't enable it with `services.copy-com.enable = true;`. I get `error: The option 'services.copy-com' defined in '/etc/nixos/configuration.nix' does not exist.`
Also `copy-com` is not registered in `module-list.nix`.
I use 15.09.
/cc @nathan-gs @nckx

**Comment by nckx** [comment]
> Also copy-com is not registered in module-list.nix.

@wedens: does this imply that even adding it there doesn't solve the problem? I'll add it to `module-list.nix`, but can't reproduce the error message you're getting.

**Comment by wedens** [comment]
@nckx I don't know. I just started using NixOS, and I only use channel provided by default. 
Should I do anything other than just `services.copy-com.enable = true;`?

**Comment by nckx** [comment]
@wedens: please see https://github.com/NixOS/nixpkgs/commit/46623bfc151449a24d34da8c8d7085910efe5918 and the provided work-around.

**Comment by wedens** [comment]
@nckx thanks! should this issue be closed?

**Comment by nckx** [comment]
@wedens: if everything now works for you :-)

**Comment by wedens** [comment]
@nckx hm. service is not auto-launching. there is nothing about it in `journalctl` logs

**Comment by nckx** [comment]
Did you try setting `.debug` and looking at things like `systemctl status copy-com-$USER`?

(This just from looking at `copy-com.nix`. I stopped using copy.com and other cloud silliness some time ago. I'll have to unmaintain it it's broken.)

**Comment by wedens** [comment]
I've found the error on startup:
```
Oct 14 00:03:59 nixos CopyConsole[599]: 0x00000000b58b9940 YAgentSyncInstance:Failed to do login by auth token tasks Exception - Description: Curl failed to post data (Couldn't resolve 
Oct 14 00:03:59 nixos CopyConsole[599]: 0x00000000b58b9940 CopyConsole::YCopyConsole:Exception - Description: Curl failed to post data (Couldn't resolve host name) Original: 155 Mapped:
Oct 14 00:03:59 nixos CopyConsole[599]: Error: Curl failed to post data
```

**Comment by nckx** [comment]
There seems to be some possibly useful information truncated. Could you post the rest of those lines?

**Comment by wedens** [comment]
ah, sorry.
```
Oct 14 00:03:59 nixos CopyConsole[599]: Starting copy...0x00000000b58b9940 YAgentSyncInstance:Setting root path to '/home/wedens/Copy'
Oct 14 00:03:59 nixos CopyConsole[599]: 0x00000000b58b9940 YAgentSyncInstance:Root path is set to '/home/wedens/Copy'
Oct 14 00:03:59 nixos CopyConsole[599]: 0x00000000b58b9940 YAgentSyncInstance:Failed to do login by auth token tasks Exception - Description: Curl failed to post data (Couldn't resolve host name) Original: 155 Mapped: 155 Location: RaisePostError:/home/jenkins/workspace/Copy_Agent_Linux-1.4/libcloud/CloudSync/Core/YHttpClient.cpp:436
Oct 14 00:03:59 nixos CopyConsole[599]: 0x00000000b58b9940 CopyConsole::YCopyConsole:Exception - Description: Curl failed to post data (Couldn't resolve host name) Original: 155 Mapped: 155 Location: RaisePostError:/home/jenkins/workspace/Copy_Agent_Linux-1.4/libcloud/CloudSync/Core/YHttpClient.cpp:436
Oct 14 00:03:59 nixos CopyConsole[599]: Error: Curl failed to post data
Oct 14 00:03:59 nixos systemd[1]: copy-com-wedens.service: main process exited, code=exited, status=155/n/a
Oct 14 00:03:59 nixos systemd[1]: Unit copy-com-wedens.service entered failed state.
Oct 14 00:03:59 nixos systemd[1]: copy-com-wedens.service failed.
```

**Comment by wedens** [comment]
there are no errors when `CopyConsole` executed manually

**Comment by nckx** [comment]
OK, that journal output wasn't as helpful as I'd hoped. `CopyConsole` works fine here too, and at the moment I don't have a NixOS system around to play with.

Random idea: maybe CopyConsole tries to perform DNS lookups before the network if fully configured, fails, and doesn't try again. What does restarting the service (once you have a verified working network connection) produce?

**Comment by wedens** [comment]
> Random idea: maybe CopyConsole tries to perform DNS lookups before the network is fully configured, fails, and doesn't try again. What does restarting the service (once you have a verified working network connection) produce?
it starts without errors

**Comment by nckx** [comment]
I'm quite sure ordering non-legacy (sysvinit) services after `network.target` is never correct, so I'm going to push that to master now.

Please cherry-pick a65cf63f55b0e808f7b5bf9a52ed330b73a01f03 and try again.

**Comment by wedens** [comment]
hm, even started manually `CopyConsole` does almost nothing. It creates folders, but files are not synchronized. no errors. just stuck at `Syncing 49 kB`.  same for `CopyAgent`

**Comment by nckx** [comment]
I used this exact client version a few months ago for weeks without issues. Perhaps I didn't stress it enough, or something has changed in the meantime.

I'll try to put this on my to-do list for next week.
