### ISSUE TITLE
Fingerprint support for Lenovo P50 was reverted

### ISSUE THREAD

**Issue by cizra** [NixOS/nixpkgs#103739]
**Project description**
Lenovo P50 fingerprint reader used to be supported.
This patch
https://github.com/NixOS/nixpkgs/commit/131a28e9f2e5f51e37a60af25379cc236f6b71c7#diff-1c6ffc68dd2dd265ff949ee028fa15deecc82b2604794c7d59cf13b5fa32d4f5
... removed the support.
The standard fprintd package doesn't recognize the fingerprint reader.
What's the rationale for the removal, and is there any hope to get it back?

**Comment by LEXUGE** [comment]
Are you refering to the removal of `fprintd-thinkpad`?

**Comment by jtojnar** [comment]
The thinkpad fork was not compatible with recent libfprint and no one stepped in to maintain it: https://github.com/NixOS/nixpkgs/pull/74656#discussion_r352221817

**Comment by jtojnar** [comment]
Looks like there is libfprint2 version of the branch if someone is interested https://gitlab.freedesktop.org/3v1n0/libfprint/-/tree/vfs0090-libfprint2

**Comment by jtojnar** [comment]
And there is also https://gitlab.freedesktop.org/3v1n0/libfprint-tod-vfs0090

It is confusing https://gitlab.freedesktop.org/3v1n0/libfprint/-/issues/3

**Comment by Valodim** [comment]
for the record, 3v1n0's patched libfprint works fine for me. I'm simply using his fork for libfprint via an overlay. I documented this in the fork's readme, too: https://github.com/3v1n0/libfprint/#nixos

**Comment by Valodim** [comment]
Relatedly, #126403 merged a tod module for the vfs0090 fingerprint scanner.

I'll close this issue as stale, feel free to reopen if there are questions left.
