### ISSUE TITLE
pkgs.fetchgit, nix-prefetch-git fail when given a URL whose basename contains @

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#103747]
**Describe the bug**
If I have a URL to a git repository whose basename contains `@`, both `pkgs.fetchgit` and `nix-prefetch-git` fail when given this URL. This is because both of these use the basename of the URL as the default name of the checkout to copy to the store.

This can be worked around by passing the `name` arg to `pkgs.fetchgit` and using the `--out` flag to `nix-prefetch-git`, but this is often not doable when using other tools that use `nix-prefetch-git` internally (see https://github.com/nixcloud/dep2nix/issues/19 for an example).

These tools should just sanitize `@` by default, along with any other characters that are invalid in store names, perhaps by replacing those invalid characters with `_`.

**To Reproduce**

```
> git init foo@bar
Initialized empty Git repository in /Users/lilyball/Dev/Nix/Scratch/gittest/foo@bar/.git/
> ( cd foo@bar && git commit --allow-empty -m 'empty' )
[master (root-commit) ead6415] empty
> nix run nixpkgs.nix-prefetch-git -c nix-prefetch-git --url file://$PWD/foo@bar/
Initialized empty Git repository in /private/tmp/git-checkout-tmp-weHMwQDl/foo@bar/.git/
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (2/2), 137 bytes | 137.00 KiB/s, done.
From file:///Users/lilyball/Dev/Nix/Scratch/gittest/foo@bar
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...
error: The path name 'foo@bar' is invalid: the '@' character is invalid. Path names are alphanumeric and can include the symbols +-._?= and must not begin with a period. Note: If 'foo@bar' is a source file and you cannot rename it on disk, builtins.path { name = ... } can be used to give it an alternative name.
```

**Expected behavior**
It should sanitize the synthesized name such that it's valid to use as a store name.

**Notify maintainers**
@bennofs

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.8`
 - channels(lilyball): `""`
 - channels(root): `"nixpkgs-21.03pre250093.0da76dab4c2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [fetchgit, nix-prefetch-git]
# a list of nixos modules affected by the problem
module:
```

**Comment by roberth** [comment]
Fixed in #166383
