### ISSUE TITLE
Rust package(s) not usable

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#10378]
All of

* rustUnstable
* rustStable
* rustCargoPlatform
* rustPlatform

fail with

```
error: cannot coerce a set to a string, at /nix/store/aaj1k56gqaqr8dlmgfahxbs7l3953g29-nixos-16.03pre69762.e916273/nixos/pkgs/build-support/trivial-builders.nix:10:14
```

when calling them with `nix-shell -p <pkg>`

**Comment by matthiasbeyer** [comment]
Well... do I need to `nix-shell -p rust cargo` to play around with rust, actually? :confused:

**Comment by globin** [comment]
@matthiasbeyer use rustStable.rustc, rustStable.cargo or equivalent.

**Comment by matthiasbeyer** [comment]
@globin Ah, thanks!
