### ISSUE TITLE
icon-theme.cache conflicts

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#10370]
```
collision between ‘/nix/store/nyyx818czsikb4rrw9bijwiyqabd2b2a-synapse-0.2.99.1/share/icons/hicolor/icon-theme.cache’ and ‘/nix/store/8wcfazjsj5a9bdf2fprk9854xxxd296n-hamster-time-tracker-1.04/share/icons/hicolor/icon-theme.cache’;
```

Maybe would be nice to automatically remove all those /usr/share/icons/*/icon-theme.cache files during build process?
In other case always will be packages when someones forgot to remove it.

What do you think?

**Comment by vcunat** [comment]
We do that, but you need to depend on the hicolor icon theme. I'll fix these packages.

**Comment by spinus** [comment]
oh ok, I see. If I find any of those I'll fix as well, thanks for quick response and fix.

**Comment by vcunat** [comment]
Thanks for reporting these :-)
