### ISSUE TITLE
How to "make" wifi drivers

### ISSUE THREAD

**Issue by rajatpundir** [NixOS/nixpkgs#103792]
I have some linux drivers for a Realtek wifi card. There is a simple bash script which gets the kernel version and architecture and runs the make command. I know some nixos and that it does things differently by softlinking them into the nix store.

I installed pkgs.gnumake and run the make command. The make command could not find the linux headers, so I installed those. But 'make' still could not find linux headers in appropriate place (as it does not know about nix store), I guess it is because of softlinking. Below is output of the bash script:

`
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.75/build M=/home/rajat/Downloads/Linux/a/a1/driver/rtl8821CU_WiFi_linux_v5.2.5.3_24795.20171031_COEX20170310-1212  modules
make[1]: *** /lib/modules/5.4.75/build: No such file or directory.  Stop.
make: *** [Makefile:1893: modules] Error 2
##################################################
Compile make driver error: 2
Please check error Mesg
##################################################
`

Here's a link to drivers I am trying to install: https://drive.google.com/file/d/1WV9pv6aahT-s4J-nSZU_ne3c07r0kCUC/view?usp=sharing

So how do you "make" packages the nix way?

**Comment by SCOTT-HAMILTON** [comment]
https://nixos.org/nixpkgs/manual/ is what you're looking for.

**Comment by jansol** [comment]
The nix way is to never run `make` by hand - nix will do that for you when you install a package. So the way to go is to write a package description. If the bash script does something important, that should be done in one of the shell hooks (probably preConfigurePhase). The manual and the code in this repo have a lot of examples of such packages.

**Comment by rajatpundir** [comment]
> The nix way is to never run `make` by hand - nix will do that for you when you install a package. So the way to go is to write a package description. If the bash script does something important, that should be done in one of the shell hooks (probably preConfigurePhase). The manual and the code in this repo have a lot of examples of such packages.

It seems it will require a lot of brain power but I will try to learn the nix way. Docs on site are nice.
