### ISSUE TITLE
Gitlab version update

### ISSUE THREAD

**Issue by freezeboy** [NixOS/nixpkgs#103886]
**Project description**

Gitlab is asking me to update my stack (13.0) to latest version for security reasons,
I tried to use the update script in git repository, and it doesn't seem to work, can
someone have a look at this script and update it (and the stack if possible).

cc @fpletz @globin @krav @talyz

**Metadata**

* homepage URL: https://gitlab.com

**Comment by ajs124** [comment]
#99116
