### ISSUE TITLE
Allow deprecate / obsolete NixOS options outside of Nixpkgs/NixOS

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nixpkgs#10385]
Currently we can only define if an option is deprecate / obsolete inside NixOS. I would like to deprecate some options that are defined in nixops, so it would be nice if there would be a library, or a module available to express this inside nixops.

**Comment by copumpkin** [comment]
:beers:

**Comment by vcunat** [comment]
In nixos the renames throw warnings (unlike nixpkgs ATM), so what about a policy to annotate deprecated names with a date and allow removing them after some time?
