### ISSUE TITLE
terraform-provider-libvirt: Provider "libvirt" not available for installation

### ISSUE THREAD

**Issue by rtacconi** [NixOS/nixpkgs#103840]
**Describe the bug**
The Terraform libvirt provider is not found even if it is installed

**To Reproduce**
I have the following packages installed:

  environment.systemPackages = with pkgs; [
    wget vim curl pkgconfig pkg-config go git unzip
    terraform-providers.libvirt terraform
    libvirt libvirt-glib parted tmux 
    python38Packages.libvirt python38
    ruby_2_7 rubyPackages_2_7.ruby-libvirt
    nomad consul vault
  ];
**Expected behavior**

When I run terraform init I get the message that libvirt provider is not found:
# terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "libvirt" not available for installation.

**Notify maintainers**

**Metadata**
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.76, NixOS, 20.09.1721.896270d629e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Package:
terraform-provider-libvirt

**Comment by zowoq** [comment]
`terraform` plugins shouldn't be added to `systemPackages` or similar, they need to be specified as part of `terraform` so they are wrapped correctly.

```nix
terraform.withPlugins (p: [ p.libvirt ])
```
