### ISSUE TITLE
Kile (among others) does not find any dictionaries

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#103836]
**Describe the bug**
Kile, and many other KDE applications, cannot find any dictionaries.

**To Reproduce**
1. `nix-shell -p kate "(pkgs.aspellWithDicts (d: [d.en d.de]))" --run kile`
2. Tools > Spelling > Change Dictionary

**Expected behavior**
The combobox contains a list of all English and German language packages.

**Actual behavior**

The list empty.

**Screenshots**

![image](https://user-images.githubusercontent.com/14054505/99156108-b9561400-26be-11eb-8380-b2304462fd6f.png)

**Additional context**
I know there are a lot of issues of this kind in Nix (with LibreOffice as well I think). But I fear we'll need a solution for almost each application and dictionary library pair (maybe we can fix all KDE applications at once as they share the editor code).

I'm not even 100% shure if Kile uses aspell, I think it uses a KDE-specific middleware that may have different backends.

**Notify maintainers**

@FRidh

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.4-arch1-1, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(user): `"nixpkgs-20.09.1500.edb26126d98, nixpkgs-unstable-21.03pre249617.ebe09a7ccc6"`
 - nixpkgs: `~/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
> I'm not even 100% shure if Kile uses aspell, I think it uses a KDE-specific middleware that may have different backends.

Indeed, https://github.com/NixOS/nixpkgs/issues/26654.
