### ISSUE TITLE
Yubico U2F

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#10382]
nixos 16.03 (but 15 as well).

The manual says to put keys in ~/.yubico/u2f_keys. That's not actually true. Keys for pam-u2f should be put in ~/.config/Yubico/u2f_keys. The file specified in the docs is for other module probably or older version (not sure).

Would be nice also to add custom params to pam module (as "cue" which tells the user to touch the key).

**Comment by jagajaga** [comment]
Nothing new on this issue?

**Comment by spinus** [comment]
https://github.com/NixOS/nixpkgs/pull/11886
