### ISSUE TITLE
binutils postFixup is non-portable

### ISSUE THREAD

**Issue by grsnl** [NixOS/nixpkgs#103978]
**Describe the bug**
The binutils package has a non-portable postFixup that does not work on darwin platforms. Ordinarily this hook is not active since withAllTargets defaults to false. Trying to build binutils with all targets on darwin fails on this postFixup hook. 

**To Reproduce**
1. Run `nix-build -E 'with import <nixpkgs> { }; pkgs.binutils-unwrapped.override { withAllTargets = true; }'` on a darwin machine

This results in the following build error:
```
rm: cannot remove '/nix/store/x4vs79vlfzvn61s4hi2kx0kqmsmpfa97-binutils-2.31.1/lib/libbfd-2.31.1.so': No such file or directory
rm: cannot remove '/nix/store/x4vs79vlfzvn61s4hi2kx0kqmsmpfa97-binutils-2.31.1/lib/libopcodes-2.31.1.so': No such file or directory
```

**Expected behavior**
A version of binutils supporting all bfd targets is built

**Additional context**
As a workaround `enableShared` can be set to `false` to avoid the postFixup. The [postFixup](https://github.com/NixOS/nixpkgs/blob/f9dd0f679caa59a2c2d1adfb6ea8f51cb540d542/pkgs/development/tools/misc/binutils/default.nix#L165) should be made portable. I'm not sure if using `${stdEnv.hostPlatform.extensions.sharedLibrary}` instead of `.so` is sufficient.

**Notify maintainers**
@Ericson2314 @vcunat

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixpkgs-20.09pre232923.c925ad564c3"`
 - channels(*): `"nixpkgs-21.03pre251181.dd1b7e377f6"`
 - nixpkgs: `/Users/*/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: binutils-unwrapped
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
> I'm not sure if using `${stdEnv.hostPlatform.extensions.sharedLibrary}` instead of .so is sufficient.

I don't have access to a darwin machine, so it may be hard to move forward unless there's someone who will do such checks.

**Comment by grsnl** [comment]
Sorry, I should have been more clear. I was brief to avoid disrupting my flow at the time too much. It looks like using the shared library extension variable will at least reference files that exist. I don't quite understand the reason for the fixup. I don't know enough about the relationship between the binutils, libbfd, and libopcodes packages in this case. Sometimes darwin does need some special handling because of the way install names are embedded into libraries and programs that link against them. With a bit of explanation of the reasons behind the fixup, I could help figure out the right solution for darwin.

**Comment by vcunat** [comment]
So, for starters... what about someone testing this one?
```diff
--- a/pkgs/development/tools/misc/binutils/default.nix
+++ b/pkgs/development/tools/misc/binutils/default.nix
@@ -19 +19 @@ let
-  reuseLibs = enableShared && withAllTargets;
+  reuseLibs = enableShared && withAllTargets && stdenv.hostPlatform.isLinux;
```

**Comment by Artturin** [comment]
At some point the postFixup was removed and the command in OP builds on darwin
