### ISSUE TITLE
libreoffice: cannot open file with UTF-characters in filename

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#103908]
**Describe the bug**
Libreoffice cannot open a file that has UTF-8 symbols (in this case Nordic characters) in its filename.

```
/path/to/file/with/problematic/characters does not exist.
```

Removing the characters works around the issue.

**To Reproduce**
Use libreoffice from 20.03, 20.09 or unstable. Quite sure it worked fine when the base system was 20.03, but will need to check again.

Starting from a shell, I see
```
(soffice:29070): Gtk-WARNING **: 16:20:10.527: Locale not supported by C library.
        Using the fallback 'C' locale.
```

My locale configuration system-wide is the NixOS default. Plasma has configured for my session `en_SE`. 

```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_SE.UTF-8
LC_CTYPE="en_SE.UTF-8"
LC_NUMERIC=en_SE.UTF-8
LC_TIME=en_SE.UTF-8
LC_COLLATE=en_SE.UTF-8
LC_MONETARY=en_SE.UTF-8
LC_MESSAGES="en_SE.UTF-8"
LC_PAPER="en_SE.UTF-8"
LC_NAME="en_SE.UTF-8"
LC_ADDRESS="en_SE.UTF-8"
LC_TELEPHONE="en_SE.UTF-8"
LC_MEASUREMENT=en_SE.UTF-8
LC_IDENTIFICATION="en_SE.UTF-8"
LC_ALL=
```

**Notify maintainers**
@7c6f434c 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `libreoffice` and `libreoffice-qt`
# a list of nixos modules affected by the problem
module:
```

```
$ nixos-version
21.03.20201103.34ad166 (Okapi)
```

**Comment by FRidh** [comment]
Ok, seems it works with `$ LC_ALL=C.utf-8 libreoffice`. Indeed, by default our glibc comes with only that and `C` if I am correct. 

I suppose I should simply add the locale system-wide..

**Comment by FRidh** [comment]
Checking now `i18n.supportedLocales`.

**Comment by 7c6f434c** [comment]
Yes, sounds like correct locale should help…

**Comment by FRidh** [comment]
Locale support is not great, apparently we cannot generate `"en_SE.UTF-8/UTF-8"`. Anyway, its a different issue.
