### ISSUE TITLE
Clojure install possibly incorrect placement of exec.jar

### ISSUE THREAD

**Issue by will08rien** [NixOS/nixpkgs#103972]
**Describe the bug**
The nix install of clojure causes issues with certain workflows. For example 

```
# (using clj-new installed as per directions in its README)
will/src$ clj -X:new create :name myname/myapp
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate clojure/run/exec__init.class, clojure/run/exec.clj or clojure/run/exec.cljc on classpath.

Full report at:
/var/folders/q7/1x177f755cnc_bsbwf3ls_b00000gp/T/clojure-3283919218336854643.edn
```

**Expected behavior**
I would expect clj new to complete successfully, as per the brew equivalent:

```
will/src$ clj -X:new create :name myname/myapp
Generating a project called myapp based on the 'app' template.
will/src$                                     

```

**Additional context**
I noticed that symlinked exec.jar from `/nix/store/yl04bln30kcmcpmigv9gbgzbh7wfgwpd-clojure-1.10.1.727/` to `/nix/store/yl04bln30kcmcpmigv9gbgzbh7wfgwpd-clojure-1.10.1.727/libexec/` seemed to fix the issue; so I suspect something problematic around here:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/clojure/default.nix#L26

🤷 (maybe)

**Notify maintainers**
@bennyandresen 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.8`
 - channels(will): `"nixpkgs-21.03pre251181.dd1b7e377f6"`
 - nixpkgs: `/Users/will/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bennyandresen** [comment]
Seems like exec.jar (or clj_exec.jar as it was previously named) was never in the right location.

Thanks for the spot and the fix!

**Comment by will08rien** [comment]
Ah no problem. Thank you for the speedy response!
