### ISSUE TITLE
libreoffice-qt: incorrect wrapping on unstable and 20.09

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#103907]
**Describe the bug**
Incorrect wrapping on unstable and 20.09
**To Reproduce**
```
$ nix shell nixpkgs/nixos-20.09#libreoffice-qt
$ libreoffice
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by 7c6f434c** [comment]
Is this before or after #103734 ?

**Comment by FRidh** [comment]
Before. Thank you, that indeed solves it. I should have searched before.

**Comment by 7c6f434c** [comment]
>Before. Thank you, that indeed solves it. I should have searched before.

You are welcome.

With GitHub search being kind of flaky at Nixpkgs size, effort for me to look up a thing I remember because I merged it is actually quite a bit lower than effort for finding it from scratch…
