### ISSUE TITLE
passExtensions.pass-import not working due to breaking change in pykeepass

### ISSUE THREAD

**Issue by madetara** [NixOS/nixpkgs#104088]
**Describe the bug**

[pass-import](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/pass/extensions/import.nix) fails to run with following error:

```
[x] Error: Importing keepass, missing required dependency: pykeepass
You can install it with:
  'sudo apt-get install python3-pykeepass', or
  'pip3 install pykeepass'
```

It's likely related to this [issue](https://github.com/roddhjav/pass-import/issues/121) and should be fixed by upgrading pass-import version

But it's a major version upgrade which brings a lot of breaking changes, so I decided to make an issue prior to creating a patch

**To Reproduce**
1. Install `pass` with `pass-import` package
2. Install `python3` with `pykeepass` package
3. Create empty keepass database (e.g. using `pykeepass.create_database()`)
4. run `pass import keepass <database_name>`

**Expected behavior**
No error

**Notify maintainers**

Tagging @Mic92 as last person who upgraded the version

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 20.09.1784.29e9c10750e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1784.29e9c10750e"`
 - channels(madetara): `"home-manager, nixos-20.09.1818.98e46cec92f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
passExtensions.pass-import
```

**Comment by madetara** [comment]
Mentioning maintainers @lovek323 @fpletz @tadfisher

**Comment by Mic92** [comment]
I think you need to add pykeypass to https://github.com/NixOS/nixpkgs/blob/ba093e25d466ffdbe43b1967eb2057649887b55e/pkgs/tools/security/pass/extensions/import.nix#L4

**Comment by madetara** [comment]
I have pykeepass installed the way you proposed. 
The problem is that pass-import is [broken](https://github.com/roddhjav/pass-import/issues/121) with `pykeepass` of version 3.2.1

**Comment by Mic92** [comment]
Maybe we should upgrade to `pass-import` to master than.

**Comment by taranarmo** [comment]
Following steps to reproduce I didn't face any issues. I guess this can be closed.
