### ISSUE TITLE
gst-plugins-bad-1.18.0 does not build on Darwin

### ISSUE THREAD

**Issue by kfiz** [NixOS/nixpkgs#104062]
**Describe the bug**
Building gst-plugins-bad-1.18.0 errors out on Darwin with:
``Package ‘libmicrodns-0.2.0’ in .../libmicrodns/default.nix:26 is not supported on ‘x86_64-darwin’, refusing to evaluate.``

**To Reproduce**
On master:
``nix-shell -p gst_all_1.gst-plugins-bad``

**Expected behavior**
should compile

**Additional context**
Version bump from 1.16.2 -> 1.18.0 in 0672de5b894a15e97da9cf82bf3052bde7919691 includes new dependencies libmicrodns and libva that might be incompatible for macOS

**Notify maintainers**
@matthewbauer @nh2 @jtojnar

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
```

**Comment by nh2** [comment]
@kfiz 

https://github.com/videolabs/libmicrodns has tags `darwin` `ios` on the right so chances are that https://github.com/NixOS/nixpkgs/blob/08e6c4d00175aa8f026aea12e03b601787d69658/pkgs/development/libraries/libmicrodns/default.nix#L29 isn't true and that it works on Darwin.

Could you try

```diff
-platforms = platforms.linux;
+platforms = platforms.unix;
```

in there?

**Comment by kfiz** [comment]
> @kfiz
> 
> https://github.com/videolabs/libmicrodns has tags `darwin` `ios` on the right so chances are that
> 
> https://github.com/NixOS/nixpkgs/blob/08e6c4d00175aa8f026aea12e03b601787d69658/pkgs/development/libraries/libmicrodns/default.nix#L29
> 
> isn't true and that it works on Darwin.
> Could you try
> 
> ```diff
> -platforms = platforms.linux;
> +platforms = platforms.unix;
> ```
> 
> in there?

lead to
``Package ‘libpciaccess-0.16’ in .../nixpkgs/pkgs/servers/x11/xorg/default.nix:1135 is not supported on ‘x86_64-darwin’, refusing to evaluate.``

**Comment by kfiz** [comment]
continuing down this rabbit hole leads to
```
 libpciaccess = super.libpciaccess.overrideAttrs (attrs: {
    meta = attrs.meta // { platforms = stdenv.lib.platforms.linux; };
```
 libpciaccess is pulled in by libdrm, which is pulled in by libva, which is pulled in by gst-plugins-bad as mentioned above.
Since the cited attribute is in ``pkgs/servers/x11/xorg/overrides.nix`` I don't suppose it is feasible for Darwin.

**Comment by nh2** [comment]
@kfiz Thanks, I hadn't found that override, that's what I needed to know.

This might fix it, give it a try: PR #104098

**Comment by kfiz** [comment]
> @kfiz Thanks, I hadn't found that override, that's what I needed to know.
> 
> This might fix it, give it a try: PR #104098

build continues as expected, yet leads to
```
un-time dependency gudev-1.0 found: NO (tried pkgconfig and framework)

sys/v4l2codecs/meson.build:12:0: ERROR: Dependency "gudev-1.0" not found, tried pkgconfig and framework
```

**Comment by kfiz** [comment]
gist of meson-log.txt:
https://gist.github.com/kfiz/91df58e1c7c2a7382ca6020153a46cb6

**Comment by jtojnar** [comment]
Probably needs `-Dv4l2codecs=disabled` in `mesonFlags` on Darwin, looking at:

https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/blob/33fcb0faf028abc312524d7bbe045322068e63b3/sys/v4l2codecs/meson.build#L12

**Comment by kfiz** [comment]
so disabling v4l2codecs solved the problem. 
Complete diff:
```diff
2 files changed, 6 insertions(+), 2 deletions(-)
pkgs/development/libraries/gstreamer/bad/default.nix | 6 +++++-
pkgs/development/libraries/libmicrodns/default.nix   | 2 +-

modified   pkgs/development/libraries/gstreamer/bad/default.nix
@@ -161,7 +161,6 @@ in stdenv.mkDerivation rec {
     soundtouch
     srtp
     fluidsynth
-    libva
     libvdpau
     libwebp
     xvidcore
@@ -180,6 +179,7 @@ in stdenv.mkDerivation rec {
     faac
   ] ++ optionals stdenv.isLinux [
     bluez
+    libva # vaapi requires libva -> libdrm -> libpciaccess, which is Linux-only in nixpkgs
     wayland
     wayland-protocols
   ] ++ optionals (!stdenv.isDarwin) [
@@ -259,6 +259,9 @@ in stdenv.mkDerivation rec {
     "-Dwpe=disabled" # required `wpe-webkit` library not packaged in nixpkgs as of writing
     "-Dzxing=disabled" # required `zxing-cpp` library not packaged in nixpkgs as of writing
   ]
+  ++ optionals (!stdenv.isLinux) [
+     "-Dva=disabled" # see comment on `libva` in `buildInputs`
+  ]
   ++ optionals stdenv.isDarwin [
     "-Dbluez=disabled"
     "-Dchromaprint=disabled"
@@ -272,6 +275,7 @@ in stdenv.mkDerivation rec {
     "-Ddvb=disabled"
     "-Dfbdev=disabled"
     "-Duvch264=disabled" # requires gudev
+    "-Dv4l2codecs=disabled" # requires gudev
     "-Dladspa=disabled" # requires lrdf
     "-Dwebrtc=disabled" # requires libnice, which as of writing doesn't work on Darwin in nixpkgs
     "-Dwildmidi=disabled" # see dependencies above
modified   pkgs/development/libraries/libmicrodns/default.nix
@@ -26,7 +26,7 @@ stdenv.mkDerivation rec {
     description = "Minimal mDNS resolver library, used by VLC";
     homepage = "https://github.com/videolabs/libmicrodns";
     license = licenses.lgpl21;
-    platforms = platforms.linux;
+    platforms = platforms.unix;
     maintainers = [ maintainers.shazow ];
   };
 }
```

**Comment by kfiz** [comment]
> Probably needs `-Dv4l2codecs=disabled` in `mesonFlags` on Darwin, looking at:
> 
> https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/blob/33fcb0faf028abc312524d7bbe045322068e63b3/sys/v4l2codecs/meson.build#L12

just so that. Yes, indeed, that was the last piece. Thx.
