### ISSUE TITLE
Chromium client ID policy change

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#104067]
I got this email from Google:

> Hi,
>
> We are writing to let you know that Google will discontinue support for sign-ins to Google accounts from embedded browser frameworks, starting January 4, 2021.
>
> We are following up with you about a recent blog post outlining our effort to block less secure browsers and applications. Most of the traffic we have detected from your client ID in the last 30 days would not be affected by this change.
>
> Nevertheless, we recommend that you take the time to review your use of Google Account authorization flows in the following Google OAuth client IDs and confirm that you are in compliance with the policy before January 4, 2021:
> 
>     Chromium on NixOS
> 
> Please refer to our blog post for more information about the policy enforcement and how to test your apps for potential impact. If necessary, you may request a Policy enforcement extension request for embedded browser frameworks, expiring June 30, 2021, by providing all required information.
> 
> Sincerely,
> 
> The Google Account Security Team

This refers to the `google_default_client_id` (404761575300.apps.googleusercontent.com) in pkgs/applications/networking/browsers/chromium/common.nix.

No idea what the impact of this policy change is on Chromium in NixOS.

@primeos @thefloweringash @bendlas

**Comment by primeos** [comment]
Sorry for my delayed reply.

> We are following up with you about a recent blog post outlining our effort to block less secure browsers and applications.

This seems to be the mentioned blog post:
https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html

> Most of the traffic we have detected from your client ID in the last 30 days would not be affected by this change.

This is strange... Not sure why some of our traffic would (potentially) be affected (a precise percentage would've been nice).

> We are writing to let you know that Google will discontinue support for sign-ins to Google accounts from embedded browser frameworks, starting January 4, 2021.

This shouldn't affect us (AFAIK) as we're not using any embedded browser frameworks (at least not with that API ID).

The blog post also mentions the following though:
> This block affects CEF-based apps **and other non-supported browsers**.

But also:
> Modern browsers with security updates will continue to be supported.

Potentially affected could be:
- Development builds of Chromium (i.e. before #101467; but this seems unlikely and that PR wasn't backported to 20.09)
- `ungoogled-chromium` (sounds also unlikely and probably doesn't even use the API ID or browser sign-ins; no idea though)
- Public/private stuff outside of Nixpkgs that reuses our API credentials
  - And/or uncommon usages (e.g. as headless browser, in an automated way, or with a different / too old User-Agent string)

Overall, I think that we should be fine and can simply ignore this (but I didn't bother with testing for compatibility or reading more than the blog post).

**Comment by primeos** [comment]
For #110245 we need to remove `google_default_client_{id,secret}` anyway so I'll close this in favor of that issue (IIRC Google's mail / blog post for this issue was't very specific but it's likely related(/identical) to #110245).
