### ISSUE TITLE
gst-plugins-good-1.18.0 does not build aarch64-linux

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#104099]
In https://github.com/NixOS/nixpkgs/pull/99345#issuecomment-728849170 @samueldr found that the upgrade from gstreamer 0.16 to 0.18 broke `aarch64`: https://hydra.nixos.org/build/130355045/nixlog/42

```
Has header "bcm_host.h" : NO 

sys/rpicamsrc/meson.build:30:4: ERROR: Problem encountered: Could not find bcm_host.h. Please pass the location of this header via -Drpi-header-dir=/path
```

I think `bcm_host.h` is a RaspberryPi specific file and pulled in via `rpicamsrc`. I don't know though whether this could be build on general `aarch64-linux`, and if yes, how to get `bcm_host.h`, so some help is needed.

**Comment by lopsided98** [comment]
`bcm_host.h` can be found in `raspberrypi-tools` and `libraspberrypi`, which appear to be identical packages.

**Comment by nh2** [comment]
And can/should that be added as a general gstreamer dependency on aarch64?

**Comment by kisik21** [comment]
I feel like it should be an optional dependency. I'll file a PR real quick
