### ISSUE TITLE
Amarok icons are missing.

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#10419]
nixos 16.03

nix-env -i amarok

:(

(I'm not using kde, I'm using xfce+gtk)

**Comment by Profpatsch** [comment]
(triage) still missing?

**Comment by spinus** [comment]
Still the case on 18.09pre140958.696c6bed4e8

**Comment by Profpatsch** [comment]
ping maintainer @peterhoeg

**Comment by peterhoeg** [comment]
Amarok for Qt4/KDE4 was dropped some time ago (despite there being a recent release) so are you seeing this with the qt4 or the qt5 version?

**Comment by rasendubi** [comment]
(triage) still an issue at 66bea3d206c19c2850a540071b0f35d2165b2701

**Comment by peterhoeg** [comment]
Missing from where exactly? It's working here.

**Comment by rasendubi** [comment]
This is how amarok looks for me: 
![image](https://user-images.githubusercontent.com/1366419/50319188-a6d10100-04ce-11e9-835d-a12fcce2af20.png)

I believe there should be some icons there. The icon in the system tray is also missing.

(Tested with awesome wm.)

**Comment by peterhoeg** [comment]
That's not right. On KDE however, it's fine. I will take a look at this but I cannot promise you when.

**Comment by rasendubi** [comment]
Still an issue at e0baf5182527221e18e303805bc6fd7213bab053

@peterhoeg any chance for you to look into this?

**Comment by peterhoeg** [comment]
I haven't been using amarok in ages - @rasendubi, is this still a problem for you on 20.03 ?

**Comment by rasendubi** [comment]
Never used Amarok myself. One from nixpkgs unstable seems to grow a couple of icons but most are still missing.

I don't use KDE, so that might be the reason.

![image](https://user-images.githubusercontent.com/1366419/83664138-422a3900-a5d2-11ea-8bfc-740824a6c20b.png)

**Comment by peterhoeg** [comment]
So it's expecting to find the icons in the global environment - it's basically an impurity. I'm realistically not going to be working on this but it's very much a legit issue.

**Comment by lasers** [comment]
Please revisit this again.

![image](https://user-images.githubusercontent.com/852504/106336503-a5996300-6254-11eb-9249-080d1a71dd1a.png)

**Comment by rasendubi** [comment]
Still no icons on non-KDE (this time EXWM).

@lasers what DE/WM do you use?

![image](https://user-images.githubusercontent.com/1366419/106347383-a79c0a00-62c6-11eb-9a05-fd169620100b.png)

**Comment by lasers** [comment]
@rasendubi Apologies. I didn't see `not using KDE` part. I'm on KDE right now. Looking through stale issues.

**Comment by spinus** [comment]
@lasers thank you for reviewing stale issues!

I can confirm issue still exists. It's little better on latest unstable, there are some icons like on @rasendubi screenshot.

**Comment by ryneeverett** [comment]
Installing the `breeze-icons` package fixed this for me on unstable.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/197074
