### ISSUE TITLE
Python needs splicing

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#104135]
**Describe the bug**
Non-`buildInputs` that are python packages shouldn't be provided by the same package set in cross builds.

(Grep `__splicedPackages` so see the nasty stuff the Haskell and xorg package sets do today, that's what we need to cargo cult.)

I'm happy to help fix this, but it would be nice to do in conjunction with the python maintainers rather than pure async.

**To Reproduce**
On staging today fad48e3230131a8139fcee2063a0e9b165f6fac3:
```bash
 $ nix-diff /nix/store/ampk9xikalzrlmcnn69jk056xnj1bfma-python2.7-PyStemmer-2.0.1.drv /nix/store/78l2xl541qn32qsv2as3zg88s6dh9qr6-python2.7-PyStemmer-2.0.1.drv
- /nix/store/ampk9xikalzrlmcnn69jk056xnj1bfma-python2.7-PyStemmer-2.0.1.drv:{out}
+ /nix/store/78l2xl541qn32qsv2as3zg88s6dh9qr6-python2.7-PyStemmer-2.0.1.drv:{out}
• The input named `python2.7-Cython-0.29.21` differs
  - /nix/store/kx6nqrm0k5vsri107pshj0ar5arawzih-python2.7-Cython-0.29.21.drv:{out}
  + /nix/store/xr0g9x2m0mhy39rhsi7vb4nzjswxzbcp-python2.7-Cython-0.29.21.drv:{out}
  • The set of input names do not match:
      - aarch64-unknown-linux-gnu-gdb-10.1
      + gdb-10.1
  • The environments do not match:
      buildInputs=''
          /nix/store/nwk8rivbjixsi9f9aghdx3940ga5px0w-glibc-locales-2.32 /nix/store/pxq11mmxrlqqmzjsv2cx8r9kqq75f8j73ap194mbw5-aarch6p2jb4-unknoy6rwn-gxqfwlinu6x-gnu-gdb-10.1
      ''
• Skipping environment comparison
```
**Expected behavior**
those two derivations are the same

**Additional context**

- GDB in particular maybe could be more multi-target, but nevermind that for now.
- Cython I suppose should be able to cross compile, so it makes sense that GDB might really need to be used with non-native binaries.

**Notify maintainers**
CC @FRidh 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: HUGE, but cross-only
# a list of nixos modules affected by the problem
module: probably big too
```

**Comment by FRidh** [comment]
Yes, we definitely need this. I have however no idea how to do this.

See also https://github.com/NixOS/nixpkgs/issues/49526.

**Comment by cdepillabout** [comment]
@Ericson2314 

> Grep __splicedPackages so see the nasty stuff the Haskell and xorg package sets do today, that's what we need to cargo cult.

I think this is the code you're talking about in the Haskell stuff:

https://github.com/NixOS/nixpkgs/blob/9a38c3a11b8db6c20611e536236d3b4831ef4498/pkgs/development/haskell-modules/make-package-set.nix#L99-L114

Is there some documentation around this?  I feel like I am missing the larger picture around this, including what sort of derivations should actually make use of this functionality, how it is implemented under the hood, and what the relationship is to things like `pkgsBuildBuild`, `pkgsHostTarget`, `nativeBuildInputs`, etc.

The only documentation I've found is a comment in splice.nix, but it doesn't really give a lot to go on:

https://github.com/NixOS/nixpkgs/blob/9a38c3a11b8db6c20611e536236d3b4831ef4498/pkgs/top-level/splice.nix#L1-L23
