### ISSUE TITLE
ssh-copy-id: misplaced subshell closing parenthesis leads to misparsed heredoc

### ISSUE THREAD

**Issue by tomeon** [NixOS/nixpkgs#104223]
**Describe the bug**

Fixed upstream in [`openssh-portable` commit d9e727d](https://github.com/openssh/openssh-portable/commit/d9e727dcc04a52caaac87543ea1d230e9e6b5604#diff-f9d171cdec2bcc8d794cc23cc95e90aae27f1bf837bd2005d644d26cd6a8d3c9).

Running `ssh-copy-id auser@some.host` results in the following output from Bash:

```
/run/current-system/sw/bin/ssh-copy-id: line 251: warning: here-document at line 251 delimited by end-of-file (wanted `EOF'
/run/current-system/sw/bin/ssh-copy-id: line 250: warning: here-document at line 250 delimited by end-of-file (wanted `EOF'
/run/current-system/sw/bin/ssh-copy-id: line 254: /dev/null`: Permission denied                                            
/run/current-system/sw/bin/ssh-copy-id: line 260: EOF: command not found                                                   
```

This problem prevents `ssh-copy-id` from copying keys to the remote system. 

**To Reproduce**

Ensure you've got an SSH keypair, then attempt to copy it to a remote system with `ssh-copy-id`:

```
$ ssh-keygen -f test_id_ed25519 -t ed25519 -N ''
$ ssh-copy-id -i ./test_id_ed25519 auser@some.host
# enter password for remote account, etc.
$ ssh -o PasswordAuthentication=no -i ./test_id_ed25519 auser@some.host true
auser@some.host: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)
```

**Expected behavior**

I would expect `ssh -o PasswordAuthentication=no -i ./test_id_ed25519 auser@some.host true` to exit with status `0` and without issuing any error output.

**Notify maintainers**

Ping @aneeshusa -- happy to submit a PR for this, though I'm not sure about the best approach.  It looks like [the commit I linked above](https://github.com/openssh/openssh-portable/commit/d9e727dcc04a52caaac87543ea1d230e9e6b5604#diff-f9d171cdec2bcc8d794cc23cc95e90aae27f1bf837bd2005d644d26cd6a8d3c9) hasn't landed in an OpenSSH release yet; the Arch Linux folks [noticed the issue](https://bugs.archlinux.org/task/68117) and have [incorporated a patch into the `openssh` package build](https://github.com/archlinux/svntogit-packages/commit/cae15fd20015b991506a8e7e3d24605b23229b3e#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a).

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 20.09.1870.14cf906f33c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aneeshusa** [comment]
Closing as this appears to have been fixed with https://github.com/NixOS/nixpkgs/pull/104254 and backported to 20.09 in https://github.com/NixOS/nixpkgs/pull/106019, please comment if something is still missing.
