### ISSUE TITLE
pythonPackages.dulwich: Tests segfault on master

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#104275]
**Describe the bug**

From https://hydra.nixos.org/build/130281889:

```
test_three_way_merge_lca (dulwich.tests.test_graph.FindMergeBaseTests) ... ok
test_finder (dulwich.tests.test_greenthreads.TestGreenThreadsMissingObjectFinder) ... /nix/store/bpjmywpnw8bvwlbmzbg6gyvj2a2k1b3l-setuptools-check-hook/nix-support/setup-hook: line 4:   297 Segmentation fault      (core dumped) /nix/store/18656kvqazm74bj7k3mdkwmdlqfyf581-python3-3.8.6/bin/python3.8 nix_run_setup test
builder for '/nix/store/yhzwwhbcfw8vrm1cnqgsfa3xv1hh0s4p-python3.8-dulwich-0.20.11.drv' failed with exit code 139
```

This currently breaks at least mercurial and haskell-language-server.

**Notify maintainers**

@k0ral @FRidh @jonringer

**Comment by k0ral** [comment]
Title says "master", Hydra says "staging-next", me trying to reproduce it says "staging-next".

**Comment by maralorn** [comment]
Sorry for the wrong link. I blame hydra ui. But it is broken on master.

This is the same build from `master`: https://hydra.nixos.org/build/130780047

It is broken there and will be broken on nixos-unstable as soon as the channel gets bumped far enough, I guess.
I can reproduce the issue locally on the master branch.

**Comment by maralorn** [comment]
This problem will be solved by  #104307.

**Comment by jonringer** [comment]
well, it doesn't fix the underlying problem. Just removes it.

I tried building dulwich from source, but it doesn't seem to fix the issue. At the beginning of the tests, it mentions "there may be some abi incompatibility" then proceeds to segfault. But I couldn't even locate where the `greenlet.greenlet` module was coming from.

**Comment by maralorn** [comment]
Uh, yeah, right. That's what I meant of course.

**Comment by jonringer** [comment]
did git bisect to find offending commit:
```
4bfbcbeb383e442bb9b60d82fc401340bc38536a is the first bad commit
commit 4bfbcbeb383e442bb9b60d82fc401340bc38536a
Author: Frederik Rietdijk <fridh@fridh.nl>
Date:   Sun Oct 25 10:06:52 2020 +0100

    python3Packages.greenlet: 0.4.16 -> 0.4.17

 pkgs/development/python-modules/greenlet/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
bisect run success
```

**Comment by spacekookie** [comment]
I still run into this problem on `nixos-unstable`. Was the "fix" reverted again?
