### ISSUE TITLE
gdb auto-load safe-path should include ${pkgs.gcc}

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#10427]
by default, if you are debugging with gdb, stl containers like std::vector can't be pretty-printed using the pretty-printers that ship with gcc, because gdb doesn't know that it can trust things in /nix/store/*gcc*

the safe-path should be configured at compile time or with a wrapper to include this path

**Comment by Profpatsch** [comment]
(triage) @fkz, did your changes fix this issue?

**Comment by fkz** [comment]
@Profpatsch yes, at least back when I was using it; but only when you use the exact `gcc` version from `all-packages`. It would be nicer to add all `build-inputs` like discussed in https://github.com/NixOS/nixpkgs/pull/11139#issuecomment-160237914. 
There also seems to be a conflict currently, I'll look into this tomorrow (is issue still there with recent nixpkgs, does this patch still resolves it?)

**Comment by Profpatsch** [comment]
Okay, then we can close here. cc @jagajaga

**Comment by Tmplt** [comment]
I can replicate this on aabc61049c011b40ef15c354d7d84c840d6b6a6d on NixOS 18.09. The referenced commit doesn't seem to be merged yet. Are there plans to merge it?

**Comment by Profpatsch** [comment]
You should comment on the PR instead, it’s linked in this issue (https://github.com/NixOS/nixpkgs/pull/11139)
