### ISSUE TITLE
PyOxidizer

### ISSUE THREAD

**Issue by layday** [NixOS/nixpkgs#104218]
**Project description**
Rust tool for producing binaries which embed the Python runtime.

**Metadata**

* homepage URL: https://github.com/indygreg/PyOxidizer
* source URL: https://github.com/indygreg/PyOxidizer
* license: mpl-2.0
* platforms: all

**Comment by killercup** [comment]
see https://github.com/indygreg/PyOxidizer/issues/231#issuecomment-710027311 for a working shell.nix snippet

**Comment by layday** [comment]
Closing this as I'm no longer interested in using PyOx with nix.

**Comment by wucke13** [comment]
FYI, I packaged `pyoxidizer` in Nix, using a nixpkgs compatible approach including a python module over here: https://github.com/DLR-FT/seL4-nix-utils/blob/2963d127a04ca26991c0efe5a8aa30a1c07c9b53/pkgs/pyoxidizer.nix
