### ISSUE TITLE
ansible 2.10 fails to parse existing playbook

### ISSUE THREAD

**Issue by otavio** [NixOS/nixpkgs#104295]
**Describe the bug**

It seems somehow the 2.10 package has regressed and stopped to parse an existing playbook. Reverting back to 2.9 "fixes" the issue.

**Error**

```
ERROR! couldn't resolve module/action 'authorized_key'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/otavio/src/yocto-aws-ec2-provisioning/provisioners/ansible/playbook.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: set authorized keys for "ubuntu" user
      ^ here
```

**Maintainers**

- @joamaki 
- @costrouc  
- @hexa

**Comment by Ma27** [comment]
AFAIU this is not a packaging bug. See https://docs.ansible.com/ansible/2.10/collections/ansible/posix/authorized_key_module.html vs https://docs.ansible.com/ansible/2.9/collections/ansible/posix/authorized_key_module.html, in 2.10 you seem to have to use `ansible.posix.authorized_key`. Ansible 2.9 appears still supported, so it's fine to keep it in the package set, so I don't see anything to do here.

**Comment by otavio** [comment]
Indeed @Ma27; this solved the issue. I upgraded to use the schema of the new collection, and it worked just fine. Thanks for the help.
