### ISSUE TITLE
services/loki: Loki: Cannot connect to Loki. Unexpected error

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#104257]
Setting up the loki service with the following configuration

```
  services.loki = {
    enable = true;
    configuration = {
      auth_enabled = false;
      server = { http_listen_port = 3100; };
      ingester = {
        lifecycler = {
          address = "127.0.0.1";
          ring = {
            kvstore = { store = "inmemory"; };
            replication_factor = 1;
          };
          final_sleep = "0s";
        };
        chunk_idle_period = "5m";
        chunk_retain_period = "30s";
      };

      schema_config = {
        configs = [{
          from = "2020-05-15";
          store = "boltdb";
          object_store = "filesystem";
          schema = "v11";
          index = {
            prefix = "index_";
            period = "168h";
          };
        }];
      };

      storage_config = {
        boltdb = { directory = "/tmp/loki/index"; };

        filesystem = { directory = "/tmp/loki/chunks"; };
      };

      limits_config = {
        enforce_metric_name = false;
        reject_old_samples = true;
        reject_old_samples_max_age = "168h";
      };
    };
  };

  services.grafana.provision.datasources = [{
    name = "loki";
    type = "loki";
    url = "localhost:3100";
  }];
```

when trying to add the datasource in grafana I get the following error
`Loki: Cannot connect to Loki. Unexpected error`

I tried changing the url in the datasource to `http://127.0.0.1:3100` the error persists.

When I curl port `3100` I get a `404 page not found`

Here is my grafana config
`  services.grafana = { enable = true; };`

I have added a reverse proxy to grafana to serve on the `grafana` subdomain
here is my caddy config
```
{ config, lib, pkgs, ... }:

{
  services.caddy = {
    enable = true;
    ca =
      "https://acme-staging-v02.api.letsencrypt.org/directory"; # comment once tested
    email = "raphael@forunion.com";
    config = ''
      grafana.union.rocks {
        reverse_proxy 127.0.0.1:3000
      }
    '';
  };
}
```

Not sure what I'm missing here

@Mic92 @WilliButz I saw you were using the loki module.
I wonder what kind of config you have
I basically took the basic config from the grafana/loki website.

**Comment by Mic92** [comment]
This is my configuration:

https://github.com/Mic92/dotfiles/blob/master/nixos/rock/modules/loki.nix

I put it behind nginx with basic auth (ldap with pam in my case but you can also use text file based one). Than I just use promtail on all my other hosts like that: https://github.com/Mic92/dotfiles/blob/master/nixos/modules/promtail.nix

Did you opened up the firewall for caddy? Can you reach caddy with curl? Also your port in loki is 3100 while caddy redirects to port 3000. Use `tcpdump -i any -n port 443 or port 3000` to see if packages are proxied correctly.

**Comment by happysalada** [comment]
@Mic92 Thanks a ton!

The caddy proxying was just to enable grafana to be accessed from the outside. I didn't want to have loki available at all from the outside. Your ldap setup is very nice though! I'll definitely go that way once I have several machines.

Thanks for the promtail reference, I didn't know about it. At the moment I am considering vector just because it can filter the logs directly (removing labels...) and send a copy to S3 for backup.

My problem was fixed by adding `localhost:3100` instead of `http://127.0.0.1:3100`. I guess port `3100` needs to be open for `127.0.0.1` to work.

**Comment by Mic92** [comment]
port 3100 should be always reachable from localhost.

**Comment by happysalada** [comment]
I've tried again and both are working now. I really can't figure out why this was failing.
Even that error I got is not very descriptive.
I'll post more around this if it happens again.
Thanks again for the help!
