### ISSUE TITLE
password-store forces to use dmenu.

### ISSUE THREAD

**Issue by Vonfry** [NixOS/nixpkgs#104249]
**Describe the bug**
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/pass/default.nix#L15-L17

Dmenu must be a dependency with x11support here, but someone who use xmonad or other tools won't want this. Could it seperate to a different package like rofi-pass?

**Notify maintainers**
cc: @lovek323 @fpletz  @tadfisher @globin @Ma27

**Comment by Ma27** [comment]
The reason for that is that `passmenu` is a part of the package itself and `dmenu` is required to have it working. Installing `rofi-pass` as well should be sufficient.

Or is your problem that you really don't want to have `dmenu` in your runtime closure because you don't need it?

**Comment by Vonfry** [comment]
> Or is your problem that you really don't want to have dmenu in your runtime closure because you don't need it?

Yes

**Comment by Ma27** [comment]
Hmm, just took a brief look at `rofi-pass`: it seems as this is only using `pass`, but not `passmenu`. Therefore it should be sufficient in your case to modify `pass` in e.g. an overlay to disable X11 support (`pass.override { x11Support = false; }`) and install `rofi-pass` as well.

**Comment by Ma27** [comment]
Fixed in #104262
