### ISSUE TITLE
Syncthing doesn't work anymore on unstable-small

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#10431]
hyper@subi:~$ systemctl status syncthing
● syncthing.service - Syncthing service
   Loaded: loaded (/nix/store/gdrl33jqz93nvlby524xaiqg9pbsqss4-unit-syncthing.service/syncthing.service)
   Active: inactive (dead) since Sat 2015-10-17 10:03:27 CEST; 1min 1s ago
  Process: 1011 ExecStart=/nix/store/naijwcnfhg5jzjs13q48q373sqh58pln-go1.4-syncthing-v0.11.25-bin/bin/syncthing -no-browser -home=/home/hyper/Desktop/Syncthing (code=exited, status=2)
 Main PID: 1011 (code=exited, status=2)

**Comment by sjau** [comment]
root@subi:~# systemctl status syncthing -l
● syncthing.service - Syncthing service
   Loaded: loaded (/nix/store/gdrl33jqz93nvlby524xaiqg9pbsqss4-unit-syncthing.service/syncthing.service)
   Active: inactive (dead) since Sat 2015-10-17 10:34:52 CEST; 21s ago
  Process: 5285 ExecStart=/nix/store/naijwcnfhg5jzjs13q48q373sqh58pln-go1.4-syncthing-v0.11.25-bin/bin/syncthing -no-browser -home=/home/hyper/Desktop/Syncthing (code=exited, status=2)
 Main PID: 5285 (code=exited, status=2)

Oct 17 10:34:52 subi syncthing[5285]: /tmp/nix-build-go1.4-syncthing-v0.11.25.drv-0/go/src/github.com/syncthing/syncthing/lib/model/model.go:1001 +0x2ff
Oct 17 10:34:52 subi syncthing[5285]: created by github.com/syncthing/syncthing/lib/model.(*Model).AddConnection
Oct 17 10:34:52 subi syncthing[5285]: /tmp/nix-build-go1.4-syncthing-v0.11.25.drv-0/go/src/github.com/syncthing/syncthing/lib/model/model.go:951 +0x5c8
Oct 17 10:34:52 subi syncthing[5285]: goroutine 94 [select]:
Oct 17 10:34:52 subi syncthing[5285]: github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc208620020, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Oct 17 10:34:52 subi syncthing[5285]: /tmp/nix-build-go1.4-syncthing-v0.11.25.drv-0/go/src/github.com/syncthing/syncthing/lib/events/events.go:192 +0x3c3
Oct 17 10:34:52 subi syncthing[5285]: github.com/syncthing/syncthing/lib/model.sendIndexes(0x7f2bac7000f0, 0xc20b4c53d0, 0xc208132624, 0xc, 0xc2081364c0, 0xc20806ce60)
Oct 17 10:34:52 subi syncthing[5285]: /tmp/nix-build-go1.4-syncthing-v0.11.25.drv-0/go/src/github.com/syncthing/syncthing/lib/model/model.go:1012 +0x3d6
Oct 17 10:34:52 subi syncthing[5285]: created by github.com/syncthing/syncthing/lib/model.(*Model).AddConnection
Oct 17 10:34:52 subi syncthing[5285]: /tmp/nix-build-go1.4-syncthing-v0.11.25.drv-0/go/src/github.com/syncthing/syncthing/lib/model/model.go:951 +0x5c8

**Comment by davidak** [comment]
cc @wkennington

**Comment by devhell** [comment]
Can confirm. Discovery stopped working on both unstable and stable, therefore no synchronization is possible.

**Comment by davidak** [comment]
I think the discovery server for 0.11.x was shut down so you have to update to 0.12.x now.
I had the same problem today on my machines.

**Comment by devhell** [comment]
Yeah, looks like it. Well, upstream sure was fast in pulling the trigger on that one. I guess that also makes the idea of providing two separate versions obsolete. Might as well directly upgrade to 0.12. I don't think we have 0.12 yet.

**Comment by davidak** [comment]
The update in the webinterface works fine for me on OS X and Ubuntu. This software is so great. :)

So it should be no problem to update on NixOS.

You have to update **all** nodes because 0.11 and 0.12 is not compatible and they can't sync.

**Comment by devhell** [comment]
I'm on NixOS, and no, it doesn't work that way here. It's a bit more complicated.

I'm aware that all nodes must be updated. Thank you. ;-)

**Comment by davidak** [comment]
i know that one can't use the integrated update mechanism on NixOS. i only want to say that the update works in general so the package can get updated.

**Comment by devhell** [comment]
Ah, excellent. :-) Thank you.

**Comment by devhell** [comment]
Just to mention it quickly. It would be good if we could update stable's syncthing to 0.12 then too. Otherwise syncthing is useless on stable.

**Comment by grwlf** [comment]
+1 for 0.12.x update. They officially introduce relay server there.
By the way, I've found the goPackages.relaysrv which depends on syncthing. Does it work with 0.11.25?

**Comment by NicolasPetton** [comment]
syncthing 0.12 is in master (https://github.com/NixOS/nixpkgs/pull/11329) and syncthing works perfectly fine on my system (nixos-unstable channel). Should we close this issue?

**Comment by jokogr** [comment]
@sjau is this issue still applicable to latest unstable-small?

**Comment by fpletz** [comment]
There were quite a few updates and we have not had similar issues. Closing for noew. Feel free to reopen if this issue persists.
