### ISSUE TITLE
Kicad does not appear in the GNOME 3 application menu

### ISSUE THREAD

**Issue by adamlwgriffiths** [NixOS/nixpkgs#104381]
**Describe the bug**
After installing Kicad, I am unable to locate the application in the gnome menu.

I can see that it's present on the system from bash
![image](https://user-images.githubusercontent.com/1239156/99802038-148a7980-2b8b-11eb-8971-b5483fb2ccb2.png)

But the applications menu knows nothing about "kicad" (should be between I and M apps)
![image](https://user-images.githubusercontent.com/1239156/99802370-b4480780-2b8b-11eb-9d2a-0d832d09f191.png)

Nor any "k*" type name when searched for
![image](https://user-images.githubusercontent.com/1239156/99802085-2c61fd80-2b8b-11eb-92c2-8300e103018f.png)

**To Reproduce**
1. Add "kicad" to list of applications in home-manager
2. `home-manager switch`
3. alt+f2 > restart or logoff/on

**Expected behavior**
Kicad to have an application icon

**Notify maintainers**

@evils @kiwi @berce

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.1500.edb26126d98 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager-20.09, nixos-20.09.1500.edb26126d98, unstable-21.03pre249162.1dc37370c48"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: kicad
# a list of nixos modules affected by the problem
module:
```

**Comment by evils** [comment]
as i don't use a desktop environment, i never got around to linking through the `${base}/share/applications/*.desktop` files
this would probably be done by #88923 implicitly if i ever got around to finishing that...

i think if you can try installing that PR (maybe rebase onto current nixos-unstable to avoid rebuilding the base) it should work, but i'm not currently set up to try that

**Comment by adamlwgriffiths** [comment]
Sounds like you're right, I'll close this.
