### ISSUE TITLE
Bug in latest Intel microcode update results in failure to boot and heavy screen glitching on Dell XPS 13 9310

### ISSUE THREAD

**Issue by mitchmindtree** [NixOS/nixpkgs#104301]
**Describe the bug**

There appears to be a bug in the latest microcode from Intel that causes the XPS 13 9310 (and possibly other Tiger Lake machines) to freeze right after initrd with heavy graphical glitching presented on the screen. You can find the main bug report here https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/44. The last comment appears to be an administrator:

> This microcode update has been removed until the issue has been resolved.

Perhaps this is taken to mean that Intel advise rolling back to the previous version until a new patched version is released?

Perhaps it's worth reverting this commit temporarily? https://github.com/NixOS/nixpkgs/commit/eaf889aea041d1dbaf1e7da8180b1401f7457a28

If not, perhaps someone can offer some advice on how NixOS users on XPS 9310 can patch their `configuration.nix` file to switch back to the previous version? I'm still getting my head around Nix and it's not obvious to me what the best way to achieve this would be.

**To Reproduce**

- Run `sudo nix-channel --update` on the unstable nixos channel on a Dell XPS 13 9310 and run `sudo nixos-rebuild switch`.
- Reboot into a glitchy screen.
- To get back to a usable state, reboot once more but select the previously working generation from the nixos generation menu.

**Expected behavior**

Boot into NixOS smoothly on Dell XPS 13 9310.

**Additional context**

I'm on a mission to get the XPS 13 9310 working nicely with NixOS, and land the necessary patches in nixos/nixos-hardware. You can follow along https://github.com/NixOS/nixos-hardware/pull/207.

This bug was an unexpected regression that caught me off guard a few days ago while attempting to update my system while trying out new kernel patches to get wi-fi working.

**Notify maintainers**

cc @andir as you are listed in the `microcodeIntel` package
cc @mweinelt as you made the aforementioned commit updating the version.

**Comment by mitchmindtree** [comment]
> This microcode update has been removed until the issue has been resolved.

It looks like this is the commit the administrator is referring to that removes the update here https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/49bb67f32a2e3e631ba1a9a73da1c52e1cac7fd9.

**Comment by mitchmindtree** [comment]
Rather than revert, I'll submit a PR that updates the package to point to the aforementioned Intel commit that supposedly removes the culprit microcode.

**Comment by mweinelt** [comment]
Thanks for the report. Can you testdrive #104303?
