### ISSUE TITLE
Steam-run: can't use MIT shared memory

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#104412]
**Describe the bug**
It seems to be impossible to use shared memory inside steam-run environment. I'd expect to be able to allow some programs to use MIT shared memory.

**To Reproduce**
1. Download Natron (it uses shared memory) [here](https://github.com/NatronGitHub/Natron/releases/download/v2.3.15/Natron-2.3.15-Linux-64-no-installer.tar.xz)
2. Unpack and go to the created directory
3. Install steam-run
4. Run `steam-run ./Natron`

You should get an error:
```
 steam-run ./Natron
Natron Version 2.3.15
Copyright (C) 2013-2018 INRIA and Alexandre Gauthier-Foichat
>>>Use the --help or -h option to print usage.<<<
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  1 (X_ShmAttach)
  Serial number of failed request:  270
  Current serial number in output stream:  271
```
**Workaround**
I can force QT not to use MITSHM using:
```
QT_X11_NO_MITSHM=1 steam-run ./Natron
```
but it may be less efficient since it just disable shared memory.

**Comment by noneucat** [comment]
I got this error a while back with a Steam game itself not being able to access X shared memory (Titanfall 2 on Proton), but it seems to have disappeared on the latest master (`nixos-21.03pre252388.069f183f16c`). Are you able to reproduce this there?

If so, I would check if `/dev/shm` is still accessible within the Steam FHS environment.

**Comment by tobiasBora** [comment]
Yes, the bug is still reproducible with `069f183f16c`. So there is a folder `/dev/shm` but this folder is empty. It also turns out that this folder is also empty in the host system:

```
$ ls -al /dev/shm
total 0
drwxrwxrwt  2 root root   40 déc.  16 11:30 .
drwxr-xr-x 21 root root 4140 déc.  16 11:28 ..

$ steam-run bash
bash-4.4$ ls -al /dev/shm
total 0
drwxrwxrwt  2 nobody nogroup   40 déc.  16 11:30 .
drwxr-xr-x 21 nobody nogroup 4140 déc.  16 11:28 ..
```

**Comment by jonringer** [comment]
oh, this should be fixed in unstable

**Comment by jonringer** [comment]
In https://github.com/NixOS/nixpkgs/pull/106409 I stopped bubblewrap from creating a new IPC namespace, so the host and steam runtime should now share it.

**Comment by jonringer** [comment]
@tobiasBora can you try the latest unstable `steam-run`?

**Comment by tobiasBora** [comment]
Thanks a lot for the help. I guess we are pretty close now from a working solution. On the stable channel (commit `257cbbcd3ab` which is 6 days old, i.e. more recent compared to #106409), it does not work out of the box, however, if I copy the file `/home/me/.nix-profile/bin/steam-run` and remove the line `--unshare-pid`, then it works. So I guess we want to setup `unsharePid` to false in steamrun. Btw, any reason not to default all `unshare` to false by default (at least in nixos)?

**Comment by jonringer** [comment]
I don't see why not, we aren't really using bwrap to protect against steam being a bad actor. 

Eventually the steam runtime will do this for games, so that games can't accidentally (or maliciously) do something like delete your home directory, but not really a concern for steam.

**Comment by jonringer** [comment]
please try the new PR

```
nixpkgs-review pr 109466 --package steam-run
$ steam-run ./....
```

**Comment by tobiasBora** [comment]
Thanks a lot for taking care of that. But I guess I made something stupid, nixpkgs-review compiles `steam` but not `steam-run`:

```
$ nixpkgs-review pr 109466 --package steam-run
[...]
The following packages specified with `-p` are not rebuild by the pull request
steam-run
```
And if I just run `nixpkgs-review pr 109466` it's the same, it compiles steam, but then the `steam-run` executable is the one from the host:
```
$ nixpkgs-review pr 109466
[...]
3 packages built:
kodiPlugins.steam-launcher lutris steam

me@me$ nix-shell /home/leo/.cache/nixpkgs-review/pr-109466-2/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-109466-2]$ which steam-run 
/home/leo/.nix-profile/bin/steam-run

[nix-shell:~/.cache/nixpkgs-review/pr-109466-2]$ which steam
/nix/store/gh75yn9mamdp4368ydpm44w8zxg8fbm4-steam/bin/steam
```
And if I try to run this steam then it fails... Is it a bug of nixpkgs-review or am I missing something? I will also try to directly compile without using nixpkgs-review and see if it changes something.

**Comment by tobiasBora** [comment]
I also tried to do it manually , and it does not work:
```
$ nix-build -A steam-run
[...]
$ result/bin/steam-run /path/to/Natron
[...]
X Error of failed request:  BadAccess (attempt to access private resource denied)
[...]
$ git log
commit f1b3f7ab1a7f6372192bf4730fb315f81e9407e8 (HEAD, refs/nixpkgs-review/1)
Author: Jonathan Ringer <jonringer117@gmail.com>
Date:   Fri Jan 15 10:22:13 2021 -0800

    steam-fhsenv: don't unshare pid
    
    Some applications such as Natron need access to MIT-SHM or other
    shared memory mechanisms. Unsharing the pid namespace
    breaks the ability for application to reference shared memory.
```

**Comment by tobiasBora** [comment]
Oh, actually it makes sense, the `steam-run` package is defined via `steam-run = steam.run`, and the `steam-run` creates a [new buildFhsUserEnv](https://github.com/NixOS/nixpkgs/blob/f1b3f7ab1a7f6372192bf4730fb315f81e9407e8/pkgs/games/steam/fhsenv.nix#L292). So I guess we should add all unshare code inside this new `buildFhsUserEnv`

**Comment by jonringer** [comment]
updated PR

**Comment by tobiasBora** [comment]
Thanks a lot, I can confirm it works.
