### ISSUE TITLE
Filesystems type exfat pull in the FUSE driver regardless of native support

### ISSUE THREAD

**Issue by kk-boop** [NixOS/nixpkgs#104430]
**Describe the bug**
On kernels newer than 5.8 exfat is natively supported by the kernel. However, if `fileSystems."/mnt".type = "exfat";` is used, nix will pull in exfat package and will use the fuse driver. This can be bypassed by not using the type and mounting by hand (there is no link for `mount.exfat`, but `mount -t exfat` works still).

**To Reproduce**
1. Have an exfat volume
2. Add it to the `fileSystems` attribute, e.g.
```
  fileSystems."/exfat" = {
    device = "/dev/disk/by-label/exfat";
    fsType = "exfat";
  };
```
3. Confirm that filesystem type is `fuseblk` using `mount`.

**Expected behavior**
Using native kernel module for mounting exfat filesystems when kernel version is newer than 5.8.

**Additional context**
A check alike this already exists for the package `exfat-nofuse` (https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/exfat/default.nix#L11)
It seems that the check in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/filesystems/exfat.nix could be responsible for this.

**Notify maintainers**
@makefu 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.8, NixOS, 21.03pre252388.069f183f16c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre252388.069f183f16c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Snoop05** [comment]
https://github.com/exfatprogs/exfatprogs
should be added for proper userspace to go with the new in kernel driver

**Comment by vs49688** [comment]
Just got bitten by this on `21.05.1205.b72bde7c4a1`.
Both FUSE and native can coexist, but if `mount.exfat` (from the `exfat` package) is in the path, the `mount` utility will prefer it unless called with the `--internal-only` flag (even with `-t exfat`).

As there's no way to disable the `mount.exfat` utility from being built from current exfat, I suggest we switch to `exfatprogs` (I can submit a PR to package this) for applicable kernels.

**Comment by makefu** [comment]
Can confirm this behavior, having exfatprogs with newer kernels is definitely recommended.
