### ISSUE TITLE
Nullmailer cannot move a failed message out of the queue because of missing directory

### ISSUE THREAD

**Issue by franksergeant** [NixOS/nixpkgs#104413]
**Describe the bug**
When a message fails, nullmailer should move it from the 'queue' directory to the 'failed' directory, but it cannot because the 'failed' directory does not exist.

**To Reproduce**
1. Install the `nullmailer` service from 20.09.
2. Edit the configuration with a good remote host, etc., but with a bad defaultdomain, e.g.,
`services.nullmailer.config.defaultdomain = "Xutoh.org";`
3. `ls -l /var/spool/nullmailer` and note that, while `queue`, `tmp`, and `trigger` are present, `failed` is missing.  For comparison, `var/spool/nullmailer/failed` in *not* missing when installed on Debian or Manjaro.
4. With `mailutils` installed, send an email from the command line with `mail`.  The message, of course, does not get sent.
5. `ls -lR /var/spool/nullmailer` and note the message is still in `queue`.
6. `journalctl -u nullmailer` for additional information or to compare with good messages and settings.

**Expected behavior**
A failed message should be moved from `/var/spool/nullmailer/queue` to `/var/spool/nullmailer/failed`.

**Here is a patch to add the missing directory**
    ---
     nixos/modules/services/mail/nullmailer.nix | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

    diff --git a/nixos/modules/services/mail/nullmailer.nix b/nixos/modules/services/mail/nullmailer.nix
    index fe3f8ef9b39..18e6b95b500 100644
    --- a/nixos/modules/services/mail/nullmailer.nix
    +++ b/nixos/modules/services/mail/nullmailer.nix
    @@ -219,7 +219,7 @@ with lib;
           after = [ "network.target" ];

           preStart = ''
    -        mkdir -p /var/spool/nullmailer/{queue,tmp}
    +        mkdir -p -m 0700 /var/spool/nullmailer/{queue,tmp,failed}
             rm -f /var/spool/nullmailer/trigger && mkfifo -m 660 /var/spool/nullmailer/trigger
           '';

    -- 
    2.28.0

**Notify maintainers**
@sargon 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
     - system: `"x86_64-linux"`
     - host os: `Linux 5.4.72, NixOS, 20.09.git.f41c0fc7d8eM (Nightingale)`
     - multi-user?: `yes`
     - sandbox: `yes`
     - version: `nix-env (Nix) 2.3.7`
     - channels(root): `"nixos-20.09.1819.f41c0fc7d8e"`
     - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nullmailer.nix
```

**Comment by SuperSandro2000** [comment]
fixed with at least 7e626703b0b892181cc1bc700d9b1cc88550243c
