### ISSUE TITLE
bolt: doesn't pass tests after latest version bump

### ISSUE THREAD

**Issue by maxeaubrey** [NixOS/nixpkgs#104429]
**Describe the bug**
bolt 0.9 appears to have broken/flaky tests. As of #103213 I cannot rebuild my system. Hydra fails in the same way: https://hydra.nixos.org/build/130437438

**To Reproduce**
Build bolt-0.9, (hopefully) observe test failure.

**Expected behavior**
Bolt passes tests/has tests disabled.

**Screenshots**
N/A

**Additional context**
N/A

**Notify maintainers**
@callahad

**Metadata**
```
 nix-shell -p nix-info --run "nix-info -m"                                                 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.8, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixpkgs-maxine, home-manager"`
 - channels(maxine): `"home-manager"`
 - nixpkgs: `/var/run/current-system/systems/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
cc @peterhoeg

**Comment by roberth** [comment]
This is now blocking the nixos-unstable channel. One restart didn't fix it.

Upstream issue https://gitlab.freedesktop.org/bolt/bolt/-/issues/167. No response for two weeks.

**Comment by roberth** [comment]
The perceived nondeterminism of the test may have been caused by the presence of `noatime` mount options on some/most of the builders.
I've proposed to remove atime-dependent tests in #106113 and upstream (linked from there)
