### ISSUE TITLE
Replace insync-portable 1.x with insync-headless 3.x

### ISSUE THREAD

**Issue by VanCoding** [NixOS/nixpkgs#104515]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 1.5.7.37371
desired version: 3.0.4.10602

###### Notify maintainers

maintainers: @benley @aristidb 

###### Note for maintainers

Insync-headless 3.x was released recently to replace the ancient insync-portable. I've already tried to package it here:
https://github.com/VanCoding/nix-insync-portable/blob/master/default.nix

But sadly, even though it says it's started, the CLI does not detect it as started. I've documented that in the repository and also notified the Insync devs here: https://forums.insynchq.com/t/nixos-portable-insync/15499

If anyone of you guys know why it's not working that'd would be great. Otherwise we'll have to close this until we get from the insync devs or someone else figures out why it does not work.

**Comment by benley** [comment]
I'm not sure about the headless version, but I've got a working derivation for the GUI version of insync 3.0 that I need to push to nixpkgs.  Would that work for you?

**Comment by VanCoding** [comment]
@benley Yes, that would be even better! :)

**Comment by aristidb** [comment]
Will this new GUI version also work without GUI? I run insync both on GUI and headless machines

**Comment by benley** [comment]
I think the GUI version requires a GUI, unfortunately.  When I add it I'll make sure to keep the existing headless insync available since the GUI one is not a direct replacement.

**Comment by VanCoding** [comment]
@aristidb @benley Thanks to tinywrkb, that helped me in the insync forums, I could get the headless version to work. It seems that the binary will not work unless its located at /usr/bin/insync-headless. Therefore, I had to put it in an FHS, and as soon as I did that, it started to work.

What's currently missing in my repo is a NixOS module with a service, tough.

**Comment by cawilliamson** [comment]
> I'm not sure about the headless version, but I've got a working derivation for the GUI version of insync 3.0 that I need to push to nixpkgs. Would that work for you?

@benley I am currently trying (and failing) to get the GUI version of insync working - would you be able to provide a link or pastebin to what you have?

Mine is at: https://termbin.com/4j0k

**Comment by benley** [comment]
oh yeah I will try to get what I have up in a PR this afternoon! Sorry I forgot all about this since starting a new job recently.

**Comment by benley** [comment]
Haven't forgotten, just delayed - getting to this soon.

**Comment by benley** [comment]
Here we go: https://github.com/NixOS/nixpkgs/pull/107478

That's what was running on my nixos laptop as of a few weeks ago, but I don't have a way of testing it properly at the moment.  Hopefully the derivation still works :-)

**Comment by VanCoding** [comment]
@benley Thanks for publishing this!
Sadly, it doesn't work for me. Running `insync start` and `insync show` does nothing. It does not even output an error message.

I also had a similar problem when packaging the headless variant and the only solution was to put it into FHS (because, as found out by a user in the insync forums, the insync binaries check their install location).

**Comment by benley** [comment]
Hmmm okay.  I'm away from my nixos systems for the next few days, but when I get back I'll try to figure out what went wrong.  It was definitely working on my laptop as of a few weeks ago.

**Comment by cawilliamson** [comment]
> Hmmm okay. I'm away from my nixos systems for the next few days, but when I get back I'll try to figure out what went wrong. It was definitely working on my laptop as of a few weeks ago.

This is what I'm using these days - hope it helps someone: https://termbin.com/cis3

I remember I changed a few things but can't remember what!

**Comment by VanCoding** [comment]
@cawilliamson Your derivation works for me, thanks :)

**Comment by VanCoding** [comment]
...or not! It starts only the first time, when ~/.config/Insync isn't there. The second time, it doesn't start.. :(

**Comment by MetalArend** [comment]
@cawilliamson you still have a working insync derivation?

**Comment by cawilliamson** [comment]
This is what I have currently but I'm seeing the same issue as @VanCoding it seems - it isn't starting for me.

I haven't actually used it for a while but I'll have a look later and submit a PR for it once I have it working again. This should really be merged anyway (once working of course!)

```
{ alsaLib, autoPatchelfHook, dpkg, fetchurl, libGL, libthai, makeDesktopItem, makeWrapper, nss, qt5, stdenv, wayland, xorg, libxcb, zlib, ... }:

stdenv.mkDerivation rec {
  name = "insync-v3";
  version = "3.6.1.50206";

  src = fetchurl {
    url = "https://s.insynchq.com/builds/insync_${version}-focal_amd64.deb";
    sha256 = "sha256-OHZoZlLsLFkN5juvQP4TF3laDYQ7g4NULragJaZRniY=";
  };

  dontStrip = true;

  unpackPhase = ''
    dpkg-deb --fsys-tarfile $src | tar -x --no-same-permissions --no-same-owner
  '';

  buildInputs = [
    alsaLib
    libGL
    libthai
    nss
    qt5.qtvirtualkeyboard
    qt5.qtwebchannel
    qt5.qtwebsockets
    qt5.qtlocation
    qt5.qtwebengine
    wayland
    xorg.libxcb
    zlib
  ];

  nativeBuildInputs = [
    autoPatchelfHook
    dpkg
    makeWrapper
    qt5.wrapQtAppsHook
  ];

  postPatch = ''
    rm -f usr/lib/insync/{libGLX.so.0,libQt5*}

    substituteInPlace usr/bin/insync --replace \
      "/usr/lib/insync" "$out/lib"
  '';

  installPhase = ''
    mkdir -p $out/bin $out/lib $out/share

    cp -R usr/bin/insync $out/bin/
    cp -R usr/lib/insync/* $out/lib/
    cp -R usr/share/* $out/share/

    cp ${desktopItem}/share/applications/* $out/share/applications/

    wrapQtApp "$out/lib/insync"
  '';

  desktopItem = makeDesktopItem {
    name = "insync";
    exec = "insync start";
    icon = "insync.svg";
    type = "Application";
    desktopName = "InSync";
    categories = "Network;";
  };
}
```
