### ISSUE TITLE
google-chrome-stable fails to start with missing libxkbcommon.so.0

### ISSUE THREAD

**Issue by TinHead** [NixOS/nixpkgs#104575]
**Describe the bug**
After last nixos stable ubptate google-chrome-stable fails to start with error:
```sh
/nix/store/q7q6i1pjnii80flg4a0k38fh4kychsvd-google-chrome-87.0.4280.66/share/google/chrome/google-chrome: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory
```
**To Reproduce**
1. Start a shell `$ nix-shell -p google-chrome --pure`
2. Run it: `[nix-shell:~]$ google-chrome-stable`
3. Profit: `/nix/store/q7q6i1pjnii80flg4a0k38fh4kychsvd-google-chrome-87.0.4280.66/share/google/chrome/google-chrome: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory`

**Expected behavior**
Should start without errors

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.1889.58f9c4c7d3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1889.58f9c4c7d3a"`
 - channels(razvan): `"home-manager, unstable-21.03pre252083.2deeb58f494"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
Issue seems related to https://github.com/NixOS/nixpkgs/issues/101782

**Comment by TinHead** [comment]
Using package from nixos-unstable works ok.

**Comment by primeos** [comment]
> Issue seems related to #101782

Yes, the `nixos-20.09` channel doesn't yet contain bfa81f72dee6184b32d765f0ce933733dd9d111d but will be automatically updated soon. So this should resolve itself, but please reopen in case something is still broken in a few days.
