### ISSUE TITLE
Packaging Unity3D

### ISSUE THREAD

**Issue by jb55** [NixOS/nixpkgs#10452]
I'm stuck trying to package unity3d, I got the the point where it runs, but it shows this error:

![Chromium Embedded Framework requires that the file '/nix/store/fg8fyyf8f5n3jr9l9jb4vwwmlgp809gi-unity-editor-5.1.0f3/opt/Unity/Editor/chrome-sandbox' is owned by root and has permissions 4755](http://jb55.com/s/unity3d-chrome-sandbox.png)

I thought this would be an easy fix, but I soon discovered [setting setuid on executables is impossible in the nix store](https://github.com/NixOS/nixos/blob/5f444a4d8d49a497bcfabe2544bda264c845653e/modules/security/setuid-wrappers.nix#L30)

So I went ahead and added unity3d to my system configuration and added `chrome-sandbox` to `security.setuidPrograms`.

Here's the problem. It looks like unity3d is hardcoded to look for chrome-sandbox in the same directory as it, which happens to be the nix store, so I always get the above error even after I delete chrome-sandbox from the directory.

Is there any way to get unity to use the chrome-sandbox in /var/setuid-wrappers/chrome-sandbox? Is there a trick I can use to make this work? Symbolic links don't work because it seems to be checking the permissions on the link itself, which can't have setuid because it's in the nix store. I've been banging my head at this for about 6 hours now so I might be missing something obvious.

my progress so far is here: https://github.com/jb55/nixpkgs/commits/unity3d

**Comment by vcunat** [comment]
IIRC the same problem (or similar) is dealt with in chromium. /cc @aszlig.

**Comment by nbp** [comment]
I think you should ask the question differently, which why do they require to have such permission?
I guess you could try to modify the binary to invert this check in the program, changing a `je` instruction by a `jne`.=, and then figure out which file it is trying to access by looking at `strace`.

**Comment by jb55** [comment]
After doing some more research, the reason why our chromium-sandbox works is because it doesn't need setuid, it uses a user namespace sandbox (check about://sandbox) and also see [here](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_sandboxing.md) for different chromium sandboxing methods.

I was able to get Unity running by copying over chromium-sandbox from the chromium package. Unfortunately libcef still checks to see if the setuid bit is set so I could only [run it](http://jb55.com/s/unity-nixos.png) from a non /nix/store directory.

**Comment by aszlig** [comment]
Mhm, maybe we should replace the full libcef... I've started on packaging it a few years ago, but haven't picked up on it again: https://github.com/NixOS/nixpkgs/compare/master...aszlig:chromium-embedded

That way, we can not only replace it for Unity3d, but a few other packages which use it (for example Desurium).

**Comment by jb55** [comment]
yes! this was the next thing I was going to look into. Where did you leave off? Is there much left to do? I'll take a stab at this soon.

**Comment by aszlig** [comment]
@jb55: Ugh... that was a long time ago, don't remember anymore. But if I get time this week, I'll look into that, but no promises as I have quite a lot on my todo list.

**Comment by jb55** [comment]
@aszlig no problem

**Comment by AshSlave** [comment]
Sorry if it's a wrong place to ask. I just started to use NixOS and have little to no understanding of how Nix packaging works. Is it possible/easy to get Unity3D running at the current state for a beginner?

**Comment by edolstra** [comment]
@AshSlave No.

**Comment by jb55** [comment]
@AshSlave ue4 is packaged though thanks to @puffnfresh, I've been using that in the meantime :+1:

**Comment by AshSlave** [comment]
@jb55 I know. But sadly, I already bound to Unity: I learned C# instead of C++, I've made some progress and there is a project I want to collaborate with. If not for that, I would choose ue4 too.
So I have to boot somewhere else in the meantime. Or familiarize myself with Nixpkgs and get Unity working at least in some form.

**Comment by Radivarig** [comment]
@jb55 could you explain more about copying chromium-sandbox from chromium package? After running Unity, were you able to login and use it?

**Comment by manpages** [comment]
@Radivarig, in my opinion, the best place to ask more general issue-related questions is Nix-dev mailing list.

**Comment by abbradar** [comment]
I've packaged `libcef` some time ago -- see https://github.com/NixOS/nixpkgs/pull/15648. Someone may want to try using it for Unity3D.

**Comment by abbradar** [comment]
Unity3D is working! See #15793.

**Comment by jb55** [comment]
Closing, thanks @abbradar !
