### ISSUE TITLE
ssmtp: authPassFile not working

### ISSUE THREAD

**Issue by theoo** [NixOS/nixpkgs#104502]
**Describe the bug**
`services.ssmtp.authPassFile` option is not working

**To Reproduce**
1. set service and its `authPassFile` option in `configuration.yml`. Add `Debug = true;` as well for testing. In my case I used something similar to
```
ssmtp = {
  enable = true;
  setSendmail = true;
  hostName = "smtp.domain.net:465";
  root = "i.an.root@domain.net";
  useTLS = true;
  domain = "domain.net";
  authUser = "user@domain.net";
  authPassFile = "/etc/nixos/ssmtp_auth_pass"; # still not working
  settings = {
    Debug = true;
  };
};
```
1. ensure the password read bit is set, for the test `chmod +r /etc/nixos/ssmtp_auth_pass`
1. switch generation: `nixos-rebuild switch`
1. (eventually) inspect logs with `journalctl -a -f` in a separate terminal 
1. send a mail `echo "Thanks for all the fish" | mail -s "So long" you@domain.net`

The command might return
```
mail: cannot send message: Process exited with a non-zero status
$ echo $?
36
```

And you might find an error similar to this in your logs
```
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Set FromLineOverride="True"
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Set MailHub="smtp.domain.net"
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Set RemotePort="465"
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Set UseSTARTTLS="False"
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Set UseTLS="True"
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Set RewriteDomain="domain.net"
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Creating SSL connection to host
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: SSL connection using ECDHE-RSA-AES256-GCM-SHA384
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: 220 smtp.domain.net ESMTP dfex
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: EHLO TEST-SERVER
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: 250 HELP
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: AUTH LOGIN
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: 334 ***
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: ***=
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: 334 ***
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: ***=
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: 535 Incorrect authentication data
Nov 21 15:12:36 TEST-SERVER sSMTP[26496]: Authorization failed (535 Incorrect authentication data)
```
Tested on 19.09 and 20.09, on different machines with three different SMTP hosts, various passwords, with and without special characters.
As explicitly warn in the doc
>> Path to a file that contains the password used for SMTP auth. The file should not contain a trailing newline, if the password does not contain one. This file should be readable by the users that need to execute ssmtp. 

I ensured that the password do not contains a leading space or carriage return.

**Expected behavior**
`authPassFile` should work just as well as its former `authPass` obsolete attribute.

**Additional context**

1. I eventually check again my password in the store: `cat /nix/store/*-ssmtp-authpass` which is yet followed by the character `#`. It's obviously a control character and I cannot find a definition of its meaning. The very same command `/etc/nixos/ssmtp_auth_pass` (original pass file) won't return the `#`.
1. the following configuration works, with of course the exact same password as provided in the password file.
```
ssmtp = {
  enable = true;
  setSendmail = true;
  hostName = "smtp.domain.net:465";
  root = "i.an.root@domain.net";
  useTLS = true;
  domain = "domain.net";
  authUser = "user@domain.net";
  settings = {
    Debug = true;
    AuthPass = "FindMeIfYouCan";
  };
};
```
Which is obviously not the expected setup.

**Notify maintainers**
@basvandijk 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 20.09.1889.58f9c4c7d3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1889.58f9c4c7d3a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `authPassFile`
# a list of nixos modules affected by the problem
module: `ssmtp`
```

**Comment by pacien** [comment]
> I ensured that the password do not contains a leading space or carriage return.

Make sure that it doesn't have a __trailing__ `\n` either.
Editors like vim tend to insert one by default.

**Comment by juselius** [comment]
I can confirm.

**Comment by aanderse** [comment]
Is this still a problem?

**Comment by theoo** [comment]
I haven't been able to validate the response using `echo 'myPass' > file` or alternative editors.

**Comment by pacien** [comment]
Use `echo -n "password" > file` to avoid the trailing newline.
To check whether there's one, use `cat -e file`; with this command, newlines are displayed as `$`.
