### ISSUE TITLE
fre:ac packaging request

### ISSUE THREAD

**Issue by cirno-999** [NixOS/nixpkgs#104671]
**Project description**
fre:ac is a free audio converter and CD extractor for Microsoft Windows, Linux, macOS and FreeBSD, distributed under the GNU General Public License.[1]

Besides extracting audio from compact discs (with various features including hidden track detection), fre:ac can also convert audio files from one format to another or to the same format but a lower bitrate. fre:ac is compatible with many audio formats such as Ogg Vorbis, FLAC, MP3, MP4/M4A, AAC, WAV, WMA and more.[2][3] fre:ac uses the CDex library to convert from CDs and uses freedb to retrieve artist/song information from the internet which is written to the files as various types of ID3 tags; this library supports cdparanoia which aims to improve audio quality.[4] The user interface is multilingual with 43 languages and is able to be a portable install on a USB drive. 

**Metadata**

* homepage URL: https://www.freac.org/
* source URL: https://github.com/enzo1982/freac
* license: GNU General Public License v2.0
* platforms: Windows, macOS, Linux, FreeBSD, HaikuOS

**Comment by SCOTT-HAMILTON** [comment]
freac is already available on my nur repo http://nur.nix-community.org/repos/shamilton/. If want to avoid building it, it should be on my cachix https://scott-hamilton.cachix.org/ (for nixos-20.9, nixpkgs-unstable and nixos-unstable)
