### ISSUE TITLE
vim: YouCompleteMe autocompletion fails for Golang

### ISSUE THREAD

**Issue by khssnv** [NixOS/nixpkgs#104664]
**Describe the bug**
YouCompleteMe autocompletion fails for Golang. YouCompleteMe vim plugin [expects](https://github.com/NixOS/nixpkgs/blob/214cd89762649ffb7163b94a9a3664fbe4296101/pkgs/development/tools/misc/ycmd/default.nix#L73) Golang language server Gopls in the [gotools](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/tools/gotools) package, however it is [moved](https://github.com/NixOS/nixpkgs/blob/214cd89762649ffb7163b94a9a3664fbe4296101/pkgs/development/tools/gotools/default.nix#L14) to independent package [gopls](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/gopls/default.nix) and Ycmd fails to find it in an old package. The symlink in Ycmd package targets to unexisting binary in gotools package now.

**To Reproduce**
1. Install vim with YouCompleteMe plugin like:
```nix
programs.vim = {
  enable = true;
  plugins = with pkgs.vimPlugins; [ YouCompleteMe ];
}
```
2. Open a file ends with `*.go` using vim,
3. Now you can see YouCompleteMe reports a failure in status bar as shown below in screenshots and autocompletion does not work.

**Expected behavior**
Golang autocompletion works with YouCompleteMe plugin installed.

**Screenshots**
Neovim status bar:
![image](https://user-images.githubusercontent.com/833019/99958973-b5ec1800-2da3-11eb-8c6a-335c6db60758.png)

Text from screenshot:
```console
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/8kzby32vmzl5fxdy6nkfsz6s0873bdqh-ycmd-2020-02-22/lib/ycmd/third_party/go/src/golang.org/x/tools/cmd/gopls/gopls'
```

**Additional context**
Nothing to mention here.

**Notify maintainers**
@rasendubi @cstrahan @lnl7 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre252388.069f183f16c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre252388.069f183f16c, home-manager"`
 - channels(khassanov): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by teto** [comment]
feel free to reopen if still valid but the issue is so old I doubt it's valid anymore
