### ISSUE TITLE
(discussion) direct pushing to master/release-20.09/...

### ISSUE THREAD

**Issue by mohe2015** [NixOS/nixpkgs#104610]
I would like to know what the rules are for direct pushing to master. https://github.com/NixOS/nixpkgs/issues/20836 is discussing a broader range of security-related issues.
I found out that there are quite frequently direct pushes to master. The two most recent ones in the last 100 commits are these two (seem to be completely fine):
e6295fafa9f96f1df1010a8afeddc4d8fc97fa68
for which I couldn't find any pull request or issue reference (I don't want to blame the committer, this is just an example)

39acab635852079f9a144de0e0f3f6cf9e6a5f1d
which is https://github.com/NixOS/nixpkgs/pull/99129 where you can see that the target branch was the wrong one so they just merged it manually (and commented the commits). I also just saw that https://github.com/NixOS/nixpkgs/issues/104594 seems to try to find a better solution for cherry-picking/backporting.

Considering that it's really annoying to also check all commits and not only all pull requests I would like to know why protecting these branches from direct pushing has not been done? I think it's okay to have quite a few people who are allowed to merge pull requests as this is a pretty big project but I'm not sure if direct push access is really required.

**Comment by ajs124** [comment]
This has been discussed several times before at more or less length, e.g. here: https://github.com/NixOS/rfcs/pull/79

**Comment by mohe2015** [comment]
Thanks for the link. I searched this repo but I totally forgot that there are RFCs. I will close this as there doesn't seem to be consensus and it already was discussed.
