### ISSUE TITLE
nixpkgs-unstable:  error: attribute 'passthru' at nixpkgs-unstable-21.03pre253014.6625284c397 already defined at ...

### ISSUE THREAD

**Issue by iafuente** [NixOS/nixpkgs#104680]
Hi, 
I'm usually using the unstable channel only as specific user on my nixos 19.03 system installation.
For several weeks I have had a problem that updating packages from unstable channel does not work.
So after update the channel with "nix-channel --update" I can't get list of updated packages or update any of them.

**To Reproduce**

[unstable-nix-user@nixos1903:~]$ nix-channel --update
unpacking channels...
created 2 symlinks in user environment

[unstable-nix-user@nixos1903:~]$ nix-env -qa  > unstable-packages.txt 
error: attribute 'passthru' at /nix/store/zsyp1295faf9158p1vpska6xz04zkwfb-nixpkgs-unstable-21.03pre253014.6625284c397/nixpkgs-unstable/pkgs/development/compilers/openjdk/default.nix:155:5 already defined at /nix/store/zsyp1295faf9158p1vpska6xz04zkwfb-nixpkgs-unstable-21.03pre253014.6625284c397/nixpkgs-unstable/pkgs/development/compilers/openjdk/default.nix:34:5

Trying install any package throw the same error as well.
[unstable-nix-user@nixos1903:~]$ nix-env -i hello
error: attribute 'passthru' at /nix/store/zsyp1295faf9158p1vpska6xz04zkwfb-nixpkgs-unstable-21.03pre253014.6625284c397/nixpkgs-unstable/pkgs/development/compilers/openjdk/default.nix:155:5 already defined at /nix/store/zsyp1295faf9158p1vpska6xz04zkwfb-nixpkgs-unstable-21.03pre253014.6625284c397/nixpkgs-unstable/pkgs/development/compilers/openjdk/default.nix:34:5

[unstable-nix-user@nixos1903:~]$ cat /etc/issue 
<<< Welcome to NixOS 19.03.172286.8ea36d73256 (\m) - \l >>>
Run `nixos-help` for the NixOS manual.

[unstable-nix-user@nixos1903:~]$ nix-channel --list
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable

After unsuccessful attempts to update packages I also tried this commands without success:
[unstable-nix-user@nixos1903:~]$ sudo nix-store --delete --ignore-liveness /nix/store/zsyp1295faf9158p1vpska6xz04zkwfb-nixpkgs-unstable-21.03pre253014.6625284c397

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for unstable-nix-user: 
finding garbage collector roots...
deleting '/nix/store/73yzs2nlnjqcaspi1j3h3vfc7pbh5cln-user-environment'
deleting '/nix/store/ijziwjx1c2a1ywq4qrxxwzm7vl29kaqv-user-environment.drv'
deleting '/nix/store/s4xpscbp94nfq1if2mhws9w46a5ybgfg-env-manifest.nix'
deleting '/nix/store/zsyp1295faf9158p1vpska6xz04zkwfb-nixpkgs-unstable-21.03pre253014.6625284c397'
deleting '/nix/store/trash'
deleting unused links...
note: currently hard linking saves 0.00 MiB
4 store paths deleted, 136.07 MiB freed

**Expected behavior**
Upgrade installed packages after usual update from unstable channel.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
[unstable-nix-user@nixos1903:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/9z1b1ldrhxh7brsi6fxnyjm7gk8kiynv-bash-interactive-4.4-p23-dev
copying path '/nix/store/9z1b1ldrhxh7brsi6fxnyjm7gk8kiynv-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.35, NixOS, 19.03.172286.8ea36d73256 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2.2`
 - channels(root): `"nixos-19.03.172286.8ea36d73256"`
 - channels(nix2003unstable-nix-user): `"20.03-20.03beta695.b2935fbecea"`
 - channels(unstable-nix-user): `"nixpkgs-unstable-21.03pre253014.6625284c397"`
 - channels(nix1909-nix-user): `"19.09-19.09.2284.bf7c0f0461e"`
 - channels(nix2003-nix-user): `"20.03-20.03.1619.ab3adfe1c76"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by r-burns** [comment]
Issue is here. Should be easy enough to merge the duplicated passthrus
https://github.com/NixOS/nixpkgs/blob/919df81df148c244ca1bcf946997b76d95ff77e0/pkgs/development/compilers/openjdk/default.nix#L34
https://github.com/NixOS/nixpkgs/blob/919df81df148c244ca1bcf946997b76d95ff77e0/pkgs/development/compilers/openjdk/default.nix#L155
