### ISSUE TITLE
Melt is missing in `bin` directory of Shotcut

### ISSUE THREAD

**Issue by mfsch** [NixOS/nixpkgs#104666]
**Describe the bug**
It appears that the binary `melt` is not included in the output of the `shotcut` derivation.

**To Reproduce**
1. Install `shotcut` in NixOS 20.09.
2. Create a video, e.g. by adding a solid color with “Open Other” → “Color” & dragging it to the timeline.
3. Try to export with default settings.

**Expected behavior**

Video is exported successfully.

**Actual behavior**

Export fails with the following log message:

```
/run/current-system/sw/bin/nice: ‘/nix/store/g3gpyqh79ynj49bc7ivjr08blf5qfajy-shotcut-20.10.31/bin/melt’: No such file or directory
Failed with exit code 127
```

**Workaround**

1. Install `mlt` separately.
2. Find `/tmp/shotcut-*.mlt` file after failed export.
3. Run `melt /tmp/shotcut-*.mlt` to create the exported video.

**Notify maintainers**

- @cillianderoiste
- @woffs
- @peti

**Metadata**

```
~ » nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.1984.9da0758c1cd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(mfsch): `"nixpkgs-21.03pre252431.4f3475b113c"`
 - channels(root): `"nixos-20.09.1984.9da0758c1cd"`
 - nixpkgs: `/home/mfsch/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: shotcut
```

**Comment by woffs** [comment]
Thanks for your report, you are right, export is broken. But `melt` was also not included in $out/bin in older versions, so I guess there is a path to mlt missing somewhere, so shotcut does not find melt. We have to find out where.

**Comment by woffs** [comment]
found it, `qmelt` was changed to `melt`, just preparing a PR

**Comment by woffs** [comment]
I have to apologize for not testing the export after updating to shotcut-20.10.31

**Comment by mfsch** [comment]
Thanks, @woffs !
