### ISSUE TITLE
cups-kyodialog3: cannot be built as source is no longoer available.

### ISSUE THREAD

**Issue by mbr** [NixOS/nixpkgs#104623]
**Describe the bug**
The `cusp-kyodialog3` uses the following source definition to build (in https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/cups/drivers/kyodialog3/default.nix):

```
src = fetchzip {
    url = "https://usa.kyoceradocumentsolutions.com/content/dam/kdc/kdag/downloads/technical/executables/drivers/kyoceradocumentsolutions/us/en/Kyocera_Linux_PPD_Ver_${version}.tar.gz";
    sha256 = "11znnlkfssakml7w80gxlz1k59f3nvhph91fkzzadnm9i7a8yjal";
  };
```

This source is no longer available, returning an HTP 302 redirect to a new homepage:

```console
$ curl https://usa.kyoceradocumentsolutions.com/content/dam/kdc/kdag/downloads/technical/executables/drivers/kyoceradocumentsolutions/us/en/Kyocera_Linux_PPD_Ver_8.1601.tar.gz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://www.kyoceradocumentsolutions.us">here</a>.</p>
<hr>
<address>IBM_HTTP_Server at usa.kyoceradocumentsolutions.com Port 443</address>
</body></html>
```

Navigating the new home, this seems to be an alternative download location:

https://www.kyoceradocumentsolutions.us/content/download-center-americas/us/drivers/drivers/Kyocera_Linux_PPD_Ver_8_1601_tar_gz.download.gz

However it seems to be a different file (warning, very slow download, file is ~ 140M in size):

```console
$ nix hash-file --type sha256 --base32 Kyocera_Linux_PPD_Ver_8_1601_tar_gz.download.gz
1rb4v715anpihnszs8gj5gwhxqkmlhza1y4c8410mgkr9xyvcx8k
```

**To Reproduce**
1. nix-shell -p cups-kyodialog3

**Expected behavior**
Packabe builds properly.

**Notify maintainers**
@steveeJ 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.73, NixOS, 20.09.1984.9da0758c1cd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1984.9da0758c1cd"`
 - channels(marc): `"home-manager, nixos-21.03pre250878.a52e974cff8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mbr** [comment]
I was slightly wrong, it is the same file, the following works for me:

```
  src = fetchzip {
    url =
      "https://www.kyoceradocumentsolutions.us/content/download-center-americas/us/drivers/drivers/Kyocera_Linux_PPD_Ver_8_1601_tar_gz.download.gz#Kyocera_Linux_PPD_Ver_8_1601.tar.gz";
    sha256 = "11znnlkfssakml7w80gxlz1k59f3nvhph91fkzzadnm9i7a8yjal";
  };
```

I had to add the URL fragment to get fetchzip to extract the file though.

**Comment by fabianpage** [comment]
@mbr does kyodialog3 works this way? Could you create a merge request?
