### ISSUE TITLE
buildGoSubmodule with runVend gets stuck in a loop and eats all my disk space when trying to package Filecoin

### ISSUE THREAD

**Issue by RaghavSood** [NixOS/nixpkgs#104691]
**Describe the bug**

**To Reproduce**
1. Try and build the accompanying derivation
2. Wait for it to hit the `vend` step
3. Run `ps aux | grep vend`
4. Run `sudo ls -al /proc/<pid from step 3>/fd`
5. Observe how the process continouosly grabs a file descriptor to a path such as `/build/source/vendor/github.com/filecoin-project/lotus...`, except that over the course of a few minutes `github.com/filecoin-project/lotus` is repeated in the path many, many times.

By the time I killed the build, it had chewed through 30 gigs+ of disk space, and the file descriptor was pointing to:

```
/build/source/vendor/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/filecoin-project/lotus/github.com/aws/aws-sdk-go-v2/models/apis/ecs/2014-11-13/docs-2.json
```

**Expected behavior**

Setting `runVend = true` should not recursively duplicate the entire source tree and eat all your disk space.

**Screenshots**
N/A

**Additional context**

I suspect that there is a loop in the git submodules of the source repository, and runVend results in that being followed for as long as there is space.

**Notify maintainers**
@kalbasit @zowoq @Mic92 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.58, NixOS, 20.03.3254.16b3b1eef03 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(raghav): `"home-manager-20.03, unstable-21.03pre251181.dd1b7e377f6"`
 - channels(root): `"nixos-20.03.3254.16b3b1eef03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Derivation:

```
{ stdenv, buildGoModule, fetchFromGitHub }:

buildGoModule rec {
  pname = "lotus";
  version = "1.2.1";

  src = fetchFromGitHub {
    owner = "filecoin-project";
    repo = pname;
    rev = "v${version}";
    sha256 = "1y2bycj2xk2s9vwcr2v8dn9hnfymwlh8n7a0cjkfzyzq0mz8xky4";
    fetchSubmodules = true;
  };

  runVend = true;
  vendorSha256 = stdenv.lib.fakeSha256;

  doCheck = false;

  subPackages = [
    "cmd/lotus"
  ];

  meta = with stdenv.lib; {
    homepage = "https://docs.lotu.sh/";
    description = "Lotus is an implementation of the Filecoin Distributed Storage Network.";
    license = with licenses; [ mit asl2 ];
    maintainers = with maintainers; [ RaghavSood ];
  };
}

```

**Comment by zowoq** [comment]
Probably caused by this:

https://github.com/filecoin-project/lotus/blob/v1.2.1/go.mod#L149
```
replace github.com/filecoin-project/lotus => ./
```

**Comment by RaghavSood** [comment]
That's an interesting way of doing things, but yes, probably that.

I'll go and bother upstream, don't know how I missed that

**Comment by RaghavSood** [comment]
Actually, I still suspect vend - if I `runVend = false`, then compilation obviously fails, but it does start compiling.

That specific replace directive might be causing these issues, but they are cropping up in vend

**Comment by Mic92** [comment]
Should we also report this to `vend` upstream?

**Comment by RaghavSood** [comment]
Applying a patch to remove the offending replace directing from go.mod does allow the build to proceed - I will open tickets with both vend and the filecoin project

**Comment by noch3** [comment]
FWIW: I got lotus building here: https://gist.github.com/noch3/28218ab5bc75bf93698c0bf0e497691a

based on the great start from https://gist.github.com/mkg20001/87cfc8fe7ef40e49cf94f2d6ce4c56c1

**Comment by zowoq** [comment]
We've replaced `runVend` with `proxyVendor` which shouldn't have the same problem as it only uses `go` itself instead of another tool.
