### ISSUE TITLE
Allow to install nix under custom NIX_STORE_DIR

### ISSUE THREAD

**Issue by gleber** [NixOS/nixpkgs#10472]
I've inspected current one-line installer like this:
```
curl https://nixos.org/nix/install | less
curl -L https://nixos.org/releases/nix/nix-1.10/nix-1.10-x86_64-linux.tar.bz2 | bzcat | tar x
cat nix-1.10-x86_64-linux/install
```
at the top of that file I can see hardcoded `dest="/nix"`

Would it be possible to extend this installer to allow installing it in e.g. `$HOME/nix/`? E.g. allow to run

```
export NIX_DEST=$HOME/nix
curl https://nixos.org/nix/install | sh
```

My use case is ability to run my [dotfiles](http://github.com/gleber/dotfiles) under Travis using their new dockerized environment, which does not support root access.

**Comment by edolstra** [comment]
That won't work because the binaries downloaded by the installer are not relocatable (they have to be installed in `/nix/store` due to RPATHs etc.).

**Comment by gleber** [comment]
Does the installer basically download a closure of nix package where all binaries are built assuming that libraries are in /nix/store? How much effort would it be to make it relocatable somehow? Maybe a patcher? Or some sort of loader hack?

**Comment by edolstra** [comment]
Yeah, it downloads a closure of Nix and unpacks it into the Nix store. Making those binaries relocatable is not feasible. In the future, you can hopefully get around this using private mount namespaces (i.e. bind-mounting your own /nix without root privileges).

**Comment by vcunat** [comment]
Some reported using `proot` successfully (as a chrooting solution without root privileges).

**Comment by vcunat** [comment]
Note that it isn't just RPATH. Loads of binaries (need to) hardcode paths to all kinds of stuff.

**Comment by jluttine** [comment]
Would be nice to have (official) instructions for this somewhere. I found the (unofficial) wiki https://nixos.wiki/wiki/Nix_Installation_Guide but the instructions about `proot` don't work: https://github.com/proot-me/PRoot/issues/133. Also, chroot guide didn't work (the system didn't support it) and the following instructions also had issues with proot: https://gist.github.com/mbbx6spp/4f467adb4e0133063fd87e264c6b9f78#file-homedir_install-sh.

Related: https://github.com/NixOS/nixpkgs/issues/13185
