### ISSUE TITLE
Postfix module adds smtp to master.cf even if services.postfix.enableSmtp is set to false

### ISSUE THREAD

**Issue by ymarkus** [NixOS/nixpkgs#104715]
The postfix module keeps adding a smtp entry to master.cf even though I have set `services.postfix.enableSmtp = false`. 
I would like to overwrite the default smtp service in master.cf, but postfix uses the last entry in the file (which is always the default one).

**To Reproduce**
1. enable postfix: `services.postfix.enable = true`
2. disable smtp : `services.postfix.enableSmtp = false`
3. check in `/etc/postfix/master.cf`

**Expected behavior**
following line should be excluded from /etc/postfix/master.cf:
```
smtp                       inet  n        -       -       -        -        smtpd
```

**Additional context**
Here's the resulting master.cf file with double entries:
```
[...]
smtp                       inet  n        -       y       -        1        smtpd 
  -o smtpd_sasl_auth_enable=no
smtp                       inet  n        -       -       -        -        smtpd
[...]
```

**Notify maintainers**

@vkleen @qknight it looks like you wrote this part a while ago. Have you heard of this issue?

**Metadata**
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.1870.14cf906f33c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(ymarkus): `""`
 - channels(root): `"home-manager-20.09, nixos-20.09.1984.9da0758c1cd, nixos-hardware, nixos-unstable-21.03pre253060.a322b32e9d7, release-20.09.tar.gz-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  - services/mail/postfix.nix
```

**Comment by vkleen** [comment]
I think, I fixed this a long time ago in my private nixpkgs repository and never upstreamed the change. I'll make a pull request.

**Comment by ymarkus** [comment]
Issue seems to be fixed. Thanks for the quick help!
