### ISSUE TITLE
texlive-new: deps for minted

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#10478]
Minted is missing these deps:

```nix
{
  deps."keyval2e" = tl."keyval2e";
  deps."fancyvrb" = tl."fancyvrb";
  deps."float" = tl."float";
  deps."ifthenx" = tl."ifthenx";
  deps."ifplatform" = tl."ifplatform";
  deps."etoolbox" = tl."etoolbox";
  deps."xstring" = tl."xstring";
  deps."xcolor" = tl."xcolor";
  deps."lineno" = tl."lineno";
  # deps."pdftexcmds" = tl."pdftexcmds";
  # deps."calc" = tl."calc";
  # deps."kvoptions" = tl."kvoptions";
}
```

The last three are listed in the [manual](file:///home/philip/Downloads/minted.pdf), but I couldn’t find them. It seems to work without them.

Is the pkgs file automatically generated from CTAN?

minted also requires external programs, `pygments`, `python` and `which`; how should these be handled?

cc @vcunat 
Thanks for the superb work!

**Comment by vcunat** [comment]
It's generated from dependencies specified by upstream TeX Live. *Minted* has no dependencies in that file. <ftp://tug.ctan.org/pub/tex/historic/systems/texlive/2015/tlnet-final/tlpkg/texlive.tlpdb.xz> I believe CTAN stuff itself provides no dependency information.

However, the generated data can be overridden, and it's already used for a few packages. I don't know how to best handle the external stuff. Is it calling the binaries somehow during LaTeX compilation?

**Comment by Profpatsch** [comment]
> However, the generated data can be overridden, and it's already used for a few packages.

So this file is auto-generated; should we mark it as such (comment at the top?)



> I don't know how to best handle the external stuff. Is it calling the binaries somehow during LaTeX compilation?

No, it does a `which texlive`; so this needs to be patched.

**Comment by Profpatsch** [comment]
Reproducing depends on https://github.com/NixOS/nixpkgs/issues/13764
