### ISSUE TITLE
virtualisation.oci-containers: Systemd services fail silently, swallowing errors.

### ISSUE THREAD

**Issue by meatcar** [NixOS/nixpkgs#104750]
**Describe the bug**

When `docker run` errors out due to a bad argument, the systemd service that started it via `virtualisation.oci-containers` swallows the error. 

**To Reproduce**
Minimal configuration:
```nix
{ ... }:
{
  virtualisation.docker.enable = true;
  virtualisation.oci-containers.containers.test = {
    image = "hello-world";
    extraOptions = [
      "--sysctl=bad.sysctl.option" # causes `docker run` to fail
    ];
  };
}
```

Rebuilding starts the systemd service, which fails silently
```sh
# nixos-rebuild switch
# journalctl _SYSTEMD_INVOCATION_ID=$(systemctl show -p InvocationID --value docker-test.service) --no-pager
-- Logs begin at Thu 2020-11-05 11:36:37 EST, end at Tue 2020-11-24 02:33:50 EST. --
-- No entries --
```

**Expected behavior**
The errors returned by `docker run` should be preserved somewhere for debugging purposes. 
```sh
# journalctl _SYSTEMD_INVOCATION_ID=$(systemctl show -p InvocationID --value docker-test.service) --no-pager
-- Logs begin at Thu 2020-11-05 11:36:37 EST, end at Tue 2020-11-24 02:35:05 EST. --
Nov 24 02:17:48 hostname docker-test-pre-start[30888]: Error: No such container: test
Nov 24 02:17:48 hostname docker[30903]: invalid argument "bad.sysctl.option" for "--sysctl" flag: sysctl 'bad.sysctl.option' is not whitelisted
Nov 24 02:17:48 hostname docker[30903]: See 'docker run --help'.
Nov 24 02:17:48 hostname docker-test-post-stop[30912]: Error: No such container: test
```

**Additional context**
Looks like in 20.09 [`StandardError` is explicitly set to `null`](https://github.com/NixOS/nixpkgs/blob/4b610d814e09857c974ac2f65374a5baba0902ff/nixos/modules/virtualisation/oci-containers.nix#L233). Forcing `StandardError` and `StandardOutput` to `"journal"` (systemd default) fixes the problem. Here's the discussion on the [PR that introduced the change](https://github.com/NixOS/nixpkgs/pull/85933#discussion_r414545641).

A working example:
```nix
{ lib, ... }:
{
  virtualisation.docker.enable = true;
  virtualisation.oci-containers.containers.test = {
    image = "hello-world";
    extraOptions = [
      "--sysctl=bad.sysctl.option" # causes `docker run` to fail
    ];
  };
  systemd.services.docker-test.serviceConfig = {
    StandardOutput = lib.mkForce "journal";
    StandardError = lib.mkForce "journal";
  };
}
```

I've only tested this with Docker. It would be nice to have this be configurable at system level.

On a related note, before 20.09 I recall viewing docker container logs through `journalctl`. This was also brought up on IRC by another user [a few weeks ago](https://logs.nix.samueldr.com/nixos/2020-11-15#1605409201-1605410832;).

**Notify maintainers**

@adisbladis 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.78, NixOS, 20.09.1984.9da0758c1cd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1984.9da0758c1cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: virtualisation.oci-containers
```

**Comment by antifuchs** [comment]
This issue bit me too, just with the `podman` backend instead of docker.

**Comment by meatcar** [comment]
I've been using the following module as a work around for now:

```nix
{ config, lib, ... }:
{
  systemd.services =
    lib.attrsets.mapAttrs'
      (name: _: {
        name = "docker-${name}";
        value = {
          serviceConfig = {
            StandardOutput = lib.mkForce "journal";
            StandardError = lib.mkForce "journal";
          };
        };
      })
      config.virtualisation.oci-containers.containers;
}
```

Source:
https://github.com/meatcar/deploy.denys.me/blob/f57031f1017bd98e032b2526f5694df1900bdf81/nixos/docker-fix.nix#L1-L16
