### ISSUE TITLE
Vim plugins handling

### ISSUE THREAD

**Issue by carldong** [NixOS/nixpkgs#10488]
I am very new to Nix OS (but experienced in other distros), and now I am trying to install vim plugins using the `environment.systemPackages`. The first one I try is `vim-addon-nix`, but after a `nixos-rebuild switch`, no file is highlighted. I also read https://nixos.org/wiki/Vim_plugins , but I tried many times to put that into `configuration.nix`, and none of them succeeded. Some tell me that there is no field `vim_configurable`, some tell me that I have infinite recursion. When I stopped trying VAM, `addon-nix` either does not work at all, or has missing dependencies. Do vim plugins have dependency handled properly?

**Comment by jagajaga** [comment]
Please provide simple `configuration.nix` with your vim setup.

**Comment by carldong** [comment]
Sorry, but I just left Nix since my xorg configuration in `configuration.nix` did not have any effects.

**Comment by jagajaga** [comment]
So maybe I can close this issue?

**Comment by carldong** [comment]
Yes, if you like

**Comment by carldong** [comment]
OK, I am back again. I just did a fresh install, and just added `vimNox` and `vim-addon-nix` into the system environment. There are lots of errors when I invoke vim, like `Unknown function: funcref#Function`. I don't have Internet access on that machine yet, so I can't get the entire log. However, this looks like some missing plugins that is not installed properly.

**Comment by carldong** [comment]
Interestingly, syntax highlighting works correctly.
