### ISSUE TITLE
PCSX2 GUI functions poorly on Sway

### ISSUE THREAD

**Issue by ralsei** [NixOS/nixpkgs#104850]
**Describe the bug**
When running PCSX2 on Sway/Wayland under XWayland, the GUI performs terribly laggy and freezes consistently. Additionally, my GTK theme does not behave as expected; highlights, etc do not appear properly. After a relatively small amount of time interacting with the menus, I have to `pkill PCSX2` to escape.

This likely has to do something with the following series of errors when running `PCSX2 --help`, leading me to believe this is a nixpkgs issue rather than one with PCSX2 or Sway. It could be an issue with GTK+ under XWayland, in which case this report should be closed.

```
(PCSX2:5357): Gtk-WARNING **: 22:09:00.757: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libadwaita.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.758: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libadwaita.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.761: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.761: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.761: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.762: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.762: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.763: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.763: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.763: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.763: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.764: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64

(PCSX2:5357): Gtk-WARNING **: 22:09:00.764: /etc/profiles/per-user/hazel/lib/gtk-2.0/2.10.0/engines/libmurrine.so: wrong ELF class: ELFCLASS64
```

**To Reproduce**
1. Use Sway
2. `nix-shell -p pcsx2 --run PCSX2`
3. Observe bad

**Expected behavior**
For the GUI to not lag and for me to be able to load a game.

**Screenshots**
![image](https://user-images.githubusercontent.com/16062051/100178700-76f0bc00-2ea2-11eb-8fc0-8194e2391870.png)

Note the `GDK_IS_PIXBUF` failures in the logs.

**Notify maintainers**
@hrdinka @samuelgrf @GovanifY 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.2016.19db3e5ea27 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"home-manager-20.09, nixos-20.09.2016.19db3e5ea27, nixos-hardware, nixos-unstable-21.03pre253014.6625284c397"`
 - channels(hazel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by GovanifY** [comment]
I run sway myself. PCSX2 currently does not run in a wayland environment, try to rerun it with `GDK_BACKEND=x11`, this should fix your issues.

**Comment by samuelgrf** [comment]
I think this issue is actually related to GTK2, this also happened on my Plasma X11 install.
Getting pcsx2 from the unstable channel fixes the issue for me.

**Comment by hrdinka** [comment]
Further PCSX2 is x86 (32bit) only. It looks like your GTK theme is using the Adwaita and Murrine engine which are only available in x86 64bit.

Also try the current PCSX2 version from master. This one links against GTK3 instead of 2.

**Comment by samuelgrf** [comment]
@hrdinka PCSX2 actually compiles to x86_64 too since https://github.com/NixOS/nixpkgs/pull/100162 .

**Comment by hrdinka** [comment]
Oh, my bad, thanks for pointing that out.

@ralsei I guess switching to the current version on master/unstable will resolve all your problems. Your version is still 32bit (`wrong ELF class: ELFCLASS64`) and using GTK2.

**Comment by GovanifY** [comment]
Actually no, the 64 bit port of PCSX2 on upstream isn't finished yet, and several parts of the JIT are missing(eg the software renderer will crash) thus 64bit isn't currently supported. 
PCSX2 OpenGL window will crash on wayland iirc, so wayland is out of the question too.
The issues are mostly related to wxQT, master has a long term plan to switch away from WxWidgets but things like this takes an unfathomable amount of time.

**Comment by ralsei** [comment]
@GovanifY Running with `GDK_BACKEND=x11` doesn't help. I'll try from unstable.

**Comment by hrdinka** [comment]
@GovanifY I guess it would be best then to revert the 64bit build and maybe add it as a separate derivation?

**Comment by GovanifY** [comment]
@hrdinka This would probably be wise for the time being, yes.

**Comment by ralsei** [comment]
Using unstable worked fine. Sorry for not responding to this, I was busy with Life Stuff(tm).

If you want to close this, go right on ahead. I'd rather not since I don't know if there's still work to be done here.

**Comment by hrdinka** [comment]
Thanks for testing and reporting back :+1:  Glad to hear that everything worked out, enjoy gaming :)

@GovanifY, @samuelgrf for going forward I suggest to add another derivation. Since full x86_64 support is coming I am in favor of adding `pcsx2_32bit` as another derivation and keep `pcsx2` as is. This should also be included in the backport in https://github.com/NixOS/nixpkgs/pull/104881. Replacing the 32bit build on stable when it actually is not ready without any replacement does not feel right to me. What are your thoughts on this?

**Comment by GovanifY** [comment]
@hrdinka The current standard derivation is x86_64, which is not finalized yet. I'm more in favor of renaming the current derivation to `pcsx2_64` and then making the 32 bit one the default.

**Comment by hrdinka** [comment]
My reasoning is the following:
There is no 64 bit Nix derivation. Our “64bit” version is just the normal derivation without any constraint. This does mean it is the same architecture as the underlying OS. In this case it is x86 with or without the 64bit extension. So on a 32bit system `pcsx2_64` wont install a 64bit pcsx2 but rather a 32bit one.

On the other side `pcsx_32bit` is forced to i686 and will always be built for this architecture.

Further the constrain free package is the one to stay. If we name the default package `pcsx_64` it will go away once it is ready, which implies that we either need to add an alias or remove it which breaks stuff. On the other hand `pcsx_32bit` might be valuable for people and could stay for a while.

**Comment by GovanifY** [comment]
@hrdinka Hmm that works for me, but why in this case don't we keep this derivation and users can explicitely ask in their nix config for an x86 version?

**Comment by hrdinka** [comment]
@GovanifY yeah, I also thought about that. But this would not change much. We could either:

* Do nothing and rely on users overriding the derivation on their own. This would mean that we are still shipping a broken package by default. This is a doable approach but with something as big as the software renderer not working, this is not acceptable.
* Add a config option. This is might sound less intrusive than another package but it actually is not. It is more complex, easier to miss, has less features (does not allow to install both versions at once) and is not that clear. Once we remove the option we would still have the same problem of supporting it, with the downside that removing a derivation will be immediately noticed and understood by a user which does not hold true for the config option.

**Comment by GovanifY** [comment]
@hrdinka Well I'll trust your judgement on that one, this is a pretty finicky situation :/

**Comment by samuelgrf** [comment]
I think making the 32bit version be the default and having users override it if they want the 64bit version would be the best solution.

With that approach we would be shipping a working package by default and don't need to deal with deprecating a config option or package later. Having a working package in nixpkgs is more important than having it be 64bit.

Thoughts? @hrdinka @GovanifY
