### ISSUE TITLE
dvisvgm 2.10.1

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#104847]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: texlive-dvisvgm.bin
current version: 2.9.1
desired version: 2.10.1

###### Notify maintainers

maintainers: @veprbl 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by veprbl** [comment]
@spacekitteh Can you tell a bit about your use case?

**Comment by spacekitteh** [comment]
@veprbl I knew I forgot something! :smile: 

I'm using emacs + org-mode, and am using the =unicode-math= package with =stix2-otf= along with lualatex. In order to preview equations, the pipeline goes
> emacs makes a standalone document for compiling -> dvilualatex -> dvisvgm -> emacs loads resulting svg

/However/, =dvisvgm= 2.9.1 doesn't understand the extended font data that lualatex emits (see the comments in https://tex.stackexchange.com/questions/537281/using-opentype-font-with-dvilualatex-and-dvisvgm), and so produces corrupt output images. This was fixed in 2.10.1, which was recently released and pushed to CTAN.
