### ISSUE TITLE
Convert Gnome from Docbook to CommonMark

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#104965]
This issue tracks the conversion of `/doc/languages-frameworks/gnome.xml` from Docbook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Instructions for performing this conversion

1. Post in this issue that you intend to work on it. (Please also post if you stop working on it)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/languages-frameworks/index.xml`: change `gnome.xml` to `gnome.section.xml`.
4. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections for inspiration.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

**Comment by jtojnar** [comment]
I can try to tackle this, hopefully we will be able to figure out how to make it functionally equivalent, even if semantic equivalence is out.

**Comment by jtojnar** [comment]
I want to finish https://github.com/NixOS/nixpkgs/pull/101537 first to avoid conflicts, though.

**Comment by Mic92** [comment]
This was merged now.
