### ISSUE TITLE
Convert Texlive from Docbook to Commonmark

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#104973]
This issue tracks the conversion of `/doc/languages-frameworks/texlive.xml` from Docbook to Commonmark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Instructions for performing this conversion

1. Post in this issue that you intend to work on it. (Please also post if you stop working on it)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/languages-frameworks/index.xml`: change `texlive.xml` to `texlive.section.xml`.
4. Move `doc/languages-frameworks/texlive.xml` to `doc/languages-frameworks/texlive.section.md`.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

**Comment by lucasew** [comment]
I am working on it.

Tip: edit in github codespaces if possible. It is faster than clone the whole nixpkgs locally xD

**Comment by ryantm** [comment]
@lucasew I think you are going to have difficulty building and previewing the manual in that environment, but if not, I'd be interested to learn about it!

**Comment by lucasew** [comment]
I am just editing in codespaces. After editing I push to my branch, download the branch tarball that is very small compared with the whole repo then build locally. Also codespaces have markdown extensions because its Visual Studio Code xD
