### ISSUE TITLE
build-fhs-userenv: possibly map all UIDs?

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#10496]
I came across some code that fails in build-fhs-userenv, due to (insufficient) UID mapping in the user namespace.

The code is from Buildroot and is basically ```fakeroot -- chown -R 0:0 some-dir```. The problem is that UID/GID 0 is not mapped in the user namespace: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-fhs-userenv/chroot-user.rb#L110-L111.

The question is whether it's at all _possible_ to do what I want, as an ordinary, non-root user.

I read https://lwn.net/Articles/532593/ and http://man7.org/linux/man-pages/man7/user_namespaces.7.html, but it's still not clear to me whether it's possible or not to have a ```/proc/self/uid_map``` file containing something like ```0 0 $MAX_UID```. All my attempts so far have failed :-/

**Comment by bjornfor** [comment]
CC @abbradar.

**Comment by bjornfor** [comment]
I would have thought fakeroot should handle UID 0 for us, but it apparently doesn't work properly in our fhs-userenv.

**Comment by bjornfor** [comment]
Example, inside the fhs-userenv:

```
userenv $ id
uid=1000(bfo) gid=100(users) groups=100(users),65534(nogroup)

userenv $ fakeroot -- id
uid=0(root) gid=0(root) groups=0(root),65534(nogroup),100(users),65534(nogroup)

### all seems well, but:

userenv $ fakeroot -- chown -R 0:0 test-file 
chown: changing ownership of ‘test-file’: Invalid argument
```

**Comment by abbradar** [comment]
I recall I've tried mapping the whole UID range but failed -- it won't allow us to map more than one UID if we are not root.

I think we should see how `fakeroot` emulates `chown`. Maybe there's some debugging switch...

**Comment by bjornfor** [comment]
I had a look at fakeroot sources, tried building with -DFAKEROOT_DEBUGGING=1 and running with ```FAKEROOT_DEBUG=1 fakeroot [...]```. It didn't give any of the debug output I saw in the source code. (Did I make a typo?)

Fakeroot is apparently implemented with LD_PRELOAD and a server/client architecture over TCP. I had difficulties deciphering the strace output, but it ends up with this anyway:

```
13701 fchownat(AT_FDCWD, "test-file", 0, 0, 0) = -1 EINVAL (Invalid argument)
```

I tried running faked (the server part) by itself, because it has a --debug flag. But when trying to connect the client, from another chroot-env, it failed with "no nesting support" or something. I'll have to re-try using the same chroot-env.

**Comment by abbradar** [comment]
If I understand correctly, `fakeroot` shouldn't make any real `chown` calls at all. I suspect something calls `fchownat` circumventing `libfakeroot` library.

**Comment by bjornfor** [comment]
@abbradar: Same here, I didn't expect a real syscall.

However, have a look at this run, outside any form of chroot / namespace environment:

```
$ strace -f fakeroot -- chown -R 0:0 test-file |& grep chown
execve("/home/bfo/.nix-profile/bin/fakeroot", ["fakeroot", "--", "chown", "-R", "0:0", "test-file"], [/* 88 vars */]) = 0
[pid 24543] execve("/nix/store/jf9d3aj4fi0rcvy8rjbwpaynzffbacbp-util-linux-2.26.2/bin/getopt", ["/nix/store/jf9d3aj4fi0rcvy8rjbwp"..., "l:f:i:s:ub:vh", "--", "chown", "-R", "0:0", "test-file"], [/* 88 vars */]) = 0
[pid 24543] write(1, " -- chown -R 0:0 test-file\n", 27 <unfinished ...>
[pid 24541] <... read resumed> " -- chown -R 0:0 test-file\n", 128) = 27
[pid 24541] stat("/nix/store/vskixqm70apvvhpzizxyqq369lmfpv3b-glib-2.44.1/bin/chown",  <unfinished ...>
[pid 24541] stat("/home/bfo/bin/chown",  <unfinished ...>
[pid 24541] stat("/var/setuid-wrappers/chown",  <unfinished ...>
[pid 24541] stat("/home/bfo/.nix-profile/bin/chown",  <unfinished ...>
[pid 24541] stat("/home/bfo/.nix-profile/sbin/chown", 0x7ffcaa4afa30) = -1 ENOENT (No such file or directory)
[pid 24541] stat("/home/bfo/.nix-profile/lib/kde4/libexec/chown",  <unfinished ...>
[pid 24541] stat("/nix/var/nix/profiles/default/bin/chown",  <unfinished ...>
[pid 24541] stat("/nix/var/nix/profiles/default/sbin/chown",  <unfinished ...>
[pid 24541] stat("/nix/var/nix/profiles/default/lib/kde4/libexec/chown",  <unfinished ...>
[pid 24541] stat("/run/current-system/sw/bin/chown",  <unfinished ...>
[pid 24541] stat("/run/current-system/sw/bin/chown",  <unfinished ...>
[pid 24541] access("/run/current-system/sw/bin/chown", X_OK <unfinished ...>
[pid 24541] stat("/run/current-system/sw/bin/chown",  <unfinished ...>
[pid 24541] access("/run/current-system/sw/bin/chown", R_OK <unfinished ...>
[pid 24541] stat("/run/current-system/sw/bin/chown",  <unfinished ...>
[pid 24541] stat("/run/current-system/sw/bin/chown",  <unfinished ...>
[pid 24541] access("/run/current-system/sw/bin/chown", X_OK <unfinished ...>
[pid 24541] stat("/run/current-system/sw/bin/chown",  <unfinished ...>
[pid 24541] access("/run/current-system/sw/bin/chown", R_OK <unfinished ...>
[pid 24556] execve("/run/current-system/sw/bin/chown", ["chown", "-R", "0:0", "test-file"], [/* 90 vars */] <unfinished ...>
[pid 24556] fchownat(AT_FDCWD, "test-file", 0, 0, AT_SYMLINK_NOFOLLOW) = -1 EPERM (Operation not permitted)
```

In this setup, fakeroot succeeds, even with the fchownat syscall that returns EPERM.

Looking at the PIDs above, maybe fakeroot is using the server (or client) to "test" what works or not, and then fake the call if the real call fails with insufficient permissions?

Guess I have to dig into fakeroot sources.

**Comment by abbradar** [comment]
```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>

void check_call(const char* name, int err)
{
  if (err < 0) {
    fprintf(stderr, "error during %s (%i): %s\n", name, errno, strerror(errno));
    exit(1);
  }
}

int main()
{
  check_call("chdir", chdir("test_dir"));
  check_call("fchownat", fchownat(AT_FDCWD, "test_file", 0, 0, 0));
  return 0;
}
```
(`test_dir`, `test_file` exist)

In chroot:
```
test-env-chrootenv:shlomo@abbradarbook:~/test$ ./a.out 
error during fchownat (22): Invalid argument
```
Outside:
```
 test  ./a.out
error during fchownat (1): Operation not permitted
```

I guess that's some strange behaviour of Linux kernel in user namespaces. Maybe we should ask in LKML or search more...

**Comment by bjornfor** [comment]
We can also use unshare(1) for quick testing (makes it easier to discuss with non-Nix'ers):

```
$ touch test-file
$ ls -ln test-file
-rw-r--r-- 1 1000 100 0 okt.  21 10:12 test-file
$ fakeroot -- chown 0:0 test-file                             ### WORKS
$ unshare -U -m fakeroot -- chown 0:0 test-file               ### FAILS
chown: changing ownership of ‘test-file’: Invalid argument
$ unshare -U -m --map-root-user fakeroot -- chown 0:0 test-file    ### WORKS
```

**Comment by abbradar** [comment]
Notice -- you don't even have to use `fakeroot`:
```
 test_dir  unshare -U -m chown 0:0 test_file
chown: changing ownership of ‘test_file’: Invalid argument
 test_dir  chown 0:0 test_file 
chown: changing ownership of ‘test_file’: Operation not permitted
 test_dir  
```

**Comment by abbradar** [comment]
My current theory is that kernel would return `-EINVAL` from any syscall which tries to operate with non-mapped in the userspace UIDs. I've yet to find a definitive source on this, but if that's the case, it should be harmless to just patch `fakeroot` to handle `EINVAL` just like `EPERM`.

**Comment by bjornfor** [comment]
@abbradar: I tested adding EINVAL handling like EPERM, like you suggested.

Patch applied to fakeroot-18.4:

```
diff --git a/libfakeroot.c b/libfakeroot.c
index 68a95fb..70da8bc 100644
--- a/libfakeroot.c
+++ b/libfakeroot.c
@@ -792,7 +792,7 @@ int chown(const char *path, uid_t owner, gid_t group){
     r=next_lchown(path,owner,group);
   else
     r=0;
-  if(r&&(errno==EPERM))
+  if(r&&(errno==EPERM||errno==EINVAL))
     r=0;
 
   return r;
@@ -819,7 +819,7 @@ int lchown(const char *path, uid_t owner, gid_t group){
     r=next_lchown(path,owner,group);
   else
     r=0;
-  if(r&&(errno==EPERM))
+  if(r&&(errno==EPERM||errno==EINVAL))
     r=0;
 
   return r;
@@ -843,7 +843,7 @@ int fchown(int fd, uid_t owner, gid_t group){
   else
     r=0;
 
-  if(r&&(errno==EPERM))
+  if(r&&(errno==EPERM||errno==EINVAL))
     r=0;
 
   return r;
@@ -870,7 +870,7 @@ int fchownat(int dir_fd, const char *path, uid_t owner, gid_t group, int flags)
   else
     r=0;
 
-  if(r&&(errno==EPERM))
+  if(r&&(errno==EPERM||errno==EINVAL))
     r=0;
 
   return r;
```

It works:

```
$ unshare -U -m ./_install/bin/fakeroot -- chown 0:0 test-file     # no errors
```

I guess upstream needs to be involved at this point. (Maybe there are more syscalls that need EINVAL handling, possibly all?)

**Comment by bjornfor** [comment]
Trying to submit Debian bug with their 'reportbug' tool:

```
$ reportbug
...
What real name should be used for sending bug reports?
[Vagrant User]> Bjørn Forsman
Traceback (most recent call last):
  File "/usr/bin/reportbug", line 2211, in <module>
    main()
  File "/usr/bin/reportbug", line 1081, in main
    return iface.user_interface()
  File "/usr/bin/reportbug", line 1197, in user_interface
    offer_configuration(self.options)
  File "/usr/bin/reportbug", line 578, in offer_configuration
    realname = realname.decode(charset, 'replace')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 2: ordinal not in range(128)
```

...! :-)

**Comment by bjornfor** [comment]
Upstream bugreport: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802612

**Comment by abbradar** [comment]
Ugh, ASCII requirements!

Thanks for reporting! I've subscribed, let's see what upstream thinks...

**Comment by abbradar** [comment]
Regardless of upstream comments, we cannot map all UIDs so we can close this I suppose.

**Comment by bjornfor** [comment]
Seems right.

(On a related note, I'm disappointed by the lack of response on the upstream bug.)

**Comment by abbradar** [comment]
Yeah. Their repository shows a lack of activity for the year already too -- see https://anonscm.debian.org/gitweb/?p=users/clint/fakeroot.git
