### ISSUE TITLE
Convert Coq from Docbook to CommonMark

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#104964]
This issue tracks the conversion of `/doc/languages-frameworks/coq.xml` from Docbook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Instructions for performing this conversion

1. Post in this issue that you intend to work on it. (Please also post if you stop working on it)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/languages-frameworks/index.xml`: change `coq.xml` to `coq.section.xml`.
4. Move `doc/languages-frameworks/coq.xml` to `doc/languages-frameworks/coq.section.md`.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

**Comment by wayofthepie** [comment]
I can also look at this.
