### ISSUE TITLE
Convert Ocaml from Docbook to Commonmark

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#104968]
This issue tracks the conversion of `/doc/languages-frameworks/ocaml.xml` from Docbook to Commonmark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

# Instructions for performing this conversion

1. Post in this issue that you intend to work on it. (Please also post if you stop working on it)
2. Checkout a new branch of nixpkgs master.
3. Edit `doc/languages-frameworks/index.xml`: change `ocaml.xml` to `ocaml.section.xml`.
4. Move `doc/languages-frameworks/ocaml.xml` to `doc/languages-frameworks/ocaml.section.md`.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections for inspiration.
6. Use `nix-build` from the `doc/` folder to build the manual.
7. Preview the manual on your computer at `http://0.0.0.0:8000/manual.html` after running from `doc/` folder:
  ```
  nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'
  ```
8. When it looks good, submit a PR and reference this issue.

**Comment by AndersonTorres** [comment]
Done! 
https://github.com/NixOS/nixpkgs/pull/105648
