### ISSUE TITLE
Docker service not starting with ZFS storage driver.

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixpkgs#10492]
Hello,

My apologies, I could not re-open the previous issue #10127 I lodged with the same name which was supposed to be resolved. This issue persists or perhaps recured due to a change made after the change that closed the ticket.

All notes and my final message intended to re-open this issue can be found in issue #10127.

Again my appologies for having to do it this way.

**Comment by georgewhewell** [comment]
I started experiencing this after this commit: https://github.com/NixOS/nixpkgs/commit/a6c42b59459ad08a76fa13fc4019f93ae8d75335

It started working again after setting virtualisation.docker.socketActivation = false;

**Comment by Nekroze** [comment]
Can confirm as that `virtualisation.docker.socketActivation = false;` now solves the issue for some reason.

**Comment by benley** [comment]
Weird - I can reproduce and confirm this as well.  When socketActivation is enabled, the systemd docker.service unit being generated does not contain zfs-user in the Environment="PATH=..." line.  I don't know why that's happening.

**Comment by nathan7** [comment]
In master, 79b4e5a8 appears to solve this.

**Comment by edude03** [comment]
Hello, I'm running 16.03 where this issue is supposed to be fixed, but with the following configuration

```
  virtualisation.docker = {
        enable = true;
        storageDriver = "zfs";
        socketActivation = false;
  };
```
I'm running into the same issue where docker is unable to start at boot with the error

```
 docker.service - Docker Application Container Engine
   Loaded: loaded (/nix/store/fp4fbzs420cinjjil9rz01qldw3sbbx7-unit-docker.service/docker.service; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-07-01 08:37:09 EDT; 1 day 2h ago
  Process: 1013 ExecStartPost=/nix/store/pfabsn5c9ip6q3awghp3c637154n2ylk-unit-script/bin/docker-post-start (code=exited, status=0/SUCCESS)
  Process: 1012 ExecStart=/nix/store/6g54z15pmgzlrdfqlshzpyhq60k67j63-docker-1.10.3/bin/docker daemon --group=docker --storage-driver=zfs (code=exited, status=1/FAILURE)
 Main PID: 1012 (code=exited, status=1/FAILURE)

Jul 01 08:37:09 nixos systemd[1]: Starting Docker Application Container Engine...
Jul 01 08:37:09 nixos docker[1012]: time="2016-07-01T08:37:09.270574780-04:00" level=fatal msg="Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)"
Jul 01 08:37:09 nixos systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 08:37:09 nixos systemd[1]: Failed to start Docker Application Container Engine.
Jul 01 08:37:09 nixos systemd[1]: docker.service: Unit entered failed state.
Jul 01 08:37:09 nixos systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Comment by nathan7** [comment]
@edude03 …is your rootfs actually ZFS?

**Comment by Nekroze** [comment]
@edude03 Similar question to @nathan7 but more specifically, is your docker dir (/var/lib/docker by default I believe) a mounted zfs filesystem?

I don't believe there has been a regression in the code and the error does mention you may have the wrong filesystem type.

The way it works is that docker will create zfs datasets for containers/images that are subsets of the zfs dataset on which your docker dir is located.

**Comment by edude03** [comment]
@Nekroze yes my docker dir is on ZFS, I mounted it like so

```
  fileSystems."/var/lib/docker" =
    { device = "storage/docker";
      fsType = "zfs";
    };
```

According to the [official docker documentation](https://docs.docker.com/engine/userguide/storagedriver/zfs-driver/): 

> The zfs storage driver is only supported on a Docker host where /var/lib/docker is mounted as a ZFS filesystem.

So I think that's correct, and again, it works if I restart the docker daemon after zfs has been mounted for example

```
zfs list                                                                                                                                                                              
NAME                                                                                   USED  AVAIL  REFER  MOUNTPOINT
storage                                                                               7.80T  2.74T  5.49T  legacy
storage/backups                                                                        762G  2.74T   762G  legacy
storage/docker                                                                        30.7G  2.74T  21.6G  legacy
storage/docker/0127854058f6da157290c0ad811f27545082bb40aaa89f4a9df99a1adb5a7e44        326K  2.74T   532M  legacy
storage/docker/03632c808280415eabc9b15e0397f44c18a722217a70b5d7de08b85903ca7686        179K  2.74T   666M  legacy
storage/docker/03d165235b2af0c0074576f3f8c672825374b61c11cf35a6d137ba14efb9f92f        383K  2.74T   172M  legacy
storage/docker/06bf1568a24c8c62d457ff53a72530a4a2f8ccc7753f487327f5133a0201e76a        128K  2.74T  5.84M  legacy
storage/docker/0aa10aa980b0d0f58185a8c9cfd5e536b03e3ff2ef1328b2d531776d8ffa900a        172M  2.74T   172M  legacy
storage/docker/0bd8f0fcfaacebca7ec4e999ea29f8d14e76d901ed78059a0b919dff7c9dfb01        172M  2.74T   172M  legacy
storage/docker/0e49963598bd3fef3ec5b2dce8e4e20c6a57cf0fb1008c497d1eb2141ee35b0a
```

Works as well. 

How can I avoid this issue?

**Comment by Nekroze** [comment]
Ah, I have had issues like this with ZFS mounts (although if its not for your root partition I recommend using the new zfs mounting method rather than managing it with nixos) and various other services. You just need to make sure the mount is there before the service starts.

For your setup you may need something like this added to your nixos configuration:
```nix
systemd.services.docker.unitConfig.RequiresMountsFor = "/var/lib/docker";
```
Or it may need to reference the systemd mount service if the above does not work:
```nix
systemd.services.docker.before = "var-lib-docker.mount";
```

I can confirm the second method works even for non-explicit (non nixos managed) zfs mounts that use the newer zfs mounting style. While the first should work the documentation says that it adds "After" attributes based on the "RequiresMountsFor" but you want "Before" instead but give it a go.

**Comment by edude03** [comment]
Thanks, I tried the latter solution with a minor adjustment 

```
systemd.services.docker.after = ["var-lib-docker.mount"];
```
*it wants an array of string*

and it works. That said, I'm wondering if this should be part of the configuration for docker.nix, so that others don't run into this issue?

**Comment by Nekroze** [comment]
I don't think it can be a part of the standard `docker.nix` purely because its a `ZFS` thing and there are multiple ways to do `ZFS` at the moment which may or may not involve a mount point for /var/lib/docker AFAIK.

Would be nice though, I am finding that I am increasingly needing to add an `After` parameter for `ZFS` mounts and I haven't even been using ZFS+NixOS as my daily driver for quite some time.
