### ISSUE TITLE
firmware-linux-nonfree has no `iwlwifi-ucode-6000-6.ucode`

### ISSUE THREAD

**Issue by carldong** [NixOS/nixpkgs#10491]
It comes only with `iwlwifi-ucode-6000-4.ucode`, which causes my kernel to complain for two minuites trying with `6`, then `5`, and finally `4`. When it is trying, I get no network access on my laptop, which is quite unacceptable.

I actually have almost the same problem as https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1398458

A solution is proposed there:
 
     SUBSYSTEM=="firmware", ACTION=="add", ATTR{loading}="-1"

in udev rules. However, I did not find the correct way to add this yet

**Comment by carldong** [comment]
After I added the rule, the next boot immediately works correctly. However, I wonder how it is possible for the LiveCD to work right out of the box, but a freshly installed system cannot?

**Comment by Emm** [comment]
I'm not sure if it's due to this commit (haven't done a --upgrade since a week or two), but it now complains about not finding iwlwifi-ucode-6000-4.ucode, which breaks the wifi even more on my laptop.

**Comment by vcunat** [comment]
@Emm: that commit isn't a part of any official branch (certainly not unstable/master).

**Comment by Emm** [comment]
@vcunat, noted, I guess I'll open a separate issue.

**Comment by vcunat** [comment]
Yes, if you verify something like that really fixes it... /cc @devhell

**Comment by devhell** [comment]
Works like a charm here, however, I'm loading `iwlwifi-ucode-6000-5.ucode`.

**Comment by devhell** [comment]
Emm: Just to make sure, maybe you want to [test this](https://github.com/devhell/nixosconf/blob/master/services/services_eris.nix#L12) and see if it actually fixes your issue.

**Comment by Emm** [comment]
@devhell, sadly the udev rule doesn't seem to help.

**Comment by devhell** [comment]
@Emm huh. Then I don't know what the issue might be with yours. Sorry.

**Comment by jagajaga** [comment]
Any new information or updates?
Can you test now?

**Comment by carldong** [comment]
I cannot test as I don't have a NixOS installation now

**Comment by jagajaga** [comment]
Closing for now.
