### ISSUE TITLE
Changing the maintainer for google-chrome

### ISSUE THREAD

**Issue by msteen** [NixOS/nixpkgs#105085]
I am listed as the maintainer for the google-chrome package, as I am the one to initialize it 5 years ago, however I have not actively maintained it or followed any of its developments since. I have only seen some of it due to mentions. I have mentioned before that I am not really a maintainer for the package, but the argument was that somebody has to be listed as maintainer and given that I initialized it and am using it, I should keep being listed as the maintainer for now. However I do not like being mentioned on GitHub whenever an issue arises, as I won't be any help and I feel bad for not responding.

I know that a package should not be without maintainer, so I was hoping someone else can take over being the maintainer for google-chrome?

@primeos You maybe?

**Comment by primeos** [comment]
@msteen thanks for this issue and feel free to remove yourself as Chrome maintainer (I can merge the PR if you ping me).

> @primeos You maybe?

I can maintain it in the meantime. Or as noted in `google-chrome/default.nix`:
```
# Note from primeos: By updating Chromium I also update Google Chrome and
# will try to merge PRs and respond to issues but I'm not actually using
# Google Chrome.
```

I can help with / handle any issues/PRs. However, as I'm not using Google Chrome I might miss some run-time issues (I only perform very basic testing for each major release). For that reason I'd like to leave this issue open (at least for some time) in case anyone would like to fill that role (testing and keeping up with changes) and respond to / handle issues/PRs. I'd mainly like to avoid the testing part as I don't have a good setup for that.

So if someone(s) would like to help me maintain Chrome (mainly testing PRs, creating PRs to fix (GitHub) issues, and handling GitHub issues) that'd be very helpful :)

**Comment by msteen** [comment]
@primeos Thanks! I have removed myself from the maintainer list in a PR. I will leave the issue open as per your suggestion.

**Comment by primeos** [comment]
I'm closing this issue as it's too old to be found without searching for it and I am listed as maintainer and can handle issues/PRs until we have a new/additional maintainer. Thanks for creating this issue though :)
