### ISSUE TITLE
broken iagno package

### ISSUE THREAD

**Issue by nesnera** [NixOS/nixpkgs#105028]
**Describe the bug**
`error: Package ‘iagno-3.36.4’ in /nix/store/609hmkydz4d12wg491flk2a8wsp3yqm5-nixos-20.09.2016.19db3e5ea27/nixos/pkgs/desktops/gnome-3/games/iagno/default.nix:33 is marked as broken, refusing to evaluate.`

**To Reproduce**
1. NixOS 20.09: `nixos-rebuild switch` with services.gnome3.games.enable = true;

**Notify maintainers**
- @jtojnar

**Comment by jtojnar** [comment]
I think we will need to backport https://github.com/NixOS/nixpkgs/commit/291bb3c859332fd2b3b41715c33c5b0b87891dc6, cc @worldofpeace

**Comment by nesnera** [comment]
(BTW: Is it possible to exclude the game packages similar to [here](https://gitlab.com/nesnera/nix_configs/-/blob/master/paz_configuration.nix#L65)?)

**Comment by jtojnar** [comment]
`excludePackages` should work for games too:

https://github.com/NixOS/nixpkgs/blob/7401ac641a17ad29da495108b609c4b225444a73/nixos/modules/services/x11/desktop-managers/gnome3.nix#L454-L460

**Comment by jtojnar** [comment]
Not sure if it works for broken packages, though.

**Comment by nesnera** [comment]
> Not sure if it works for broken packages, though.

I'm afraid not |  
-- | --

**Comment by nesnera** [comment]
Pardon. I just wanted to close the debate on the possibility of excluding the package - unfortunately, it does not work.🥴
The problem with `iagno` persists.

**Comment by jtojnar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/107832

**Comment by jtojnar** [comment]
That actually fixed a different issue on master, we still need to backport https://github.com/NixOS/nixpkgs/commit/291bb3c859332fd2b3b41715c33c5b0b87891dc6 to 20.09.
