### ISSUE TITLE
Python's ctypes broken on macOS Big Sur

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#105038]
Python's ctypes support is broken on macOS Big Sur. This currently affects nixpkgs. Here's an example with `python3.8-regex`:

https://gist.github.com/dhess/e1b2662a6732618b252096e0de3a04d4

This has been fixed in CPython trunk and backported to 3.9:

https://github.com/python/cpython/pull/22855
https://github.com/python/cpython/pull/23295

Unfortunately, it's not yet been backported to 3.8, which is the default `python3Packages` set in `nixpkgs`.

**Comment by FRidh** [comment]
That's a pretty big backport! Probably in time it will be backported to 3.8 as well.

**Comment by jonringer** [comment]
once they do another release, these will be added "automatically"

**Comment by rb2k** [comment]
Has this actually been resolved in any new release?
I think 3.8.7 as well as 3.9.1 are currently both failing for me on Big Sur

```
# sw_vers
ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64
```

3.8.7:
```
nix/store/zlck50w2v1ypwk9yqkfy8mf4kmcs89c9-python3-3.8.7/bin/python3.8
Python 3.8.7 (default, Feb  5 2021, 19:55:34) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; find_library("c")
>>> 
```

And 3.9:
```
# nix/store/fk1lwfjvpzzh7d1sj8jyi832kzqczsmi-python3-3.9.1/bin/python3.9
Python 3.9.1 (default, Feb  5 2021, 19:44:28) 
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; find_library("c")
>>> 
```

**Comment by i077** [comment]
Getting a similar error when starting `jupyter lab` (which uses ctypes) on Big Sur (please forgive the ugly shell invocation):

```
% nix shell --expr '(builtins.getFlake "github:NixOS/nixpkgs/nixpkgs-unstable").legacyPackages.x86_64-darwin.python39.withPackages (ps: [ ps.jupyterlab ])' --impure -c jupyter-lab
Traceback (most recent call last):
  File "/nix/store/nzw8mizwzxxadhcwxfr1ldis8wabk50x-python3.9-jupyterlab-2.2.9/bin/.jupyter-lab-wrapped", line 6, in <module>
    from jupyterlab.labapp import main
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/jupyterlab/labapp.py", line 14, in <module>
    from jupyterlab_server import slugify, WORKSPACE_EXTENSION
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/jupyterlab_server/app.py", line 9, in <module>
    from .server import ServerApp
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/jupyterlab_server/server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/notebook/notebookapp.py", line 86, in <module>
    from .services.contents.filemanager import FileContentsManager
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/notebook/services/contents/filemanager.py", line 17, in <module>
    from send2trash import send2trash
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/nix/store/hvqz59hsvpsd7ljy58rr687z55dqfc7l-python3-3.9.1-env/lib/python3.9/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/nix/store/nvxkg44pcrijvqmv5m6inz36rf7zgshy-python3-3.9.1/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/nix/store/nvxkg44pcrijvqmv5m6inz36rf7zgshy-python3-3.9.1/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found
```

My guess is that it has something to do with the [https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/development/interpreters/python/cpython/3.9/no-ldconfig.patch] to ctypes being applied to all the python derivations.

**Comment by jonringer** [comment]
> Has this actually been resolved in any new release?

Upsteam hasn't cut any new releases yet.

**Comment by i077** [comment]
But cpython 3.9.1 (which is in nixpkgs-unstable) should work on Big Sur since it has the patch from python/cpython#23295, right?

**Comment by i077** [comment]
For reference, the latest Python 3.9 from Homebrew works on Big Sur

```
% which python3
/usr/local/bin/python3
% python3      
Python 3.9.1 (default, Jan 27 2021, 11:07:38) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library; find_library("c")
'/usr/lib/libc.dylib'
>>> 
```

**Comment by fanzeyi** [comment]
FWIW it works on Homebrew because they manually applied the patch:

https://github.com/Homebrew/homebrew-core/blob/012fff6f2506fc351fc04b5bb1516669614bcd19/Formula/python%403.9.rb#L78-L86

**Comment by fanzeyi** [comment]
So Python 3.9.1 should have ctypes work on Big Sur, this still doesn't work because nixpkg's build doesn't provide `mach-o/dyld.h` header. Causing this check to fail:

https://github.com/python/cpython/commit/41761933c1c30bb6003b65eef1ba23a83db4eae4#diff-90d08e583c4c9c6f391b2ae90f819f600a6326928ea9512c9e0c6d98e9f29ac2R12040

I'm checking if there is anyway to fix it. (I saw there is `nixpkgs.darwin.dyld` but it doesn't seem to solve the issue)

**Comment by fanzeyi** [comment]
Oh well, this is a fun digging.

So apparently dyld in nixpkgs was last updated in macOS 10.12 release to 433.5. The function used in fixing Python's ctypes issue appeared in dyld-832.7.1.tar.gz. So this issue probably is gonna hinge on #101229 but that one is only updating to 10.13, which is still three versions away from having `_dyld_shared_cache_contains_path`. Now I can certain write an overlay locally to update dyld and build Python with it but I don't know if there is a good way to have the Python in nixpkg supports it.

**Comment by groodt** [comment]
@FRidh As a maintainer of the cpython package, do you know if there are steps towards a resolution or issues we should be tracking here?

I do of course realise that cpython on Darwin is a challenge. If we have some plans or comms, then perhaps the community can assist in some way.

**Comment by FRidh** [comment]
@groodt I don't work with darwin and I am not aware of any PR's either towards adding support for big sur.

**Comment by groodt** [comment]
@LnL7 @jonringer @domenkozar Do we have anywhere public where issues such as this are prioritised? It feels like this Python issue is only going to be the start of other major blockers for darwin as more and more packages expect newer versions of Apple SDKs. I fully understand that macOS support for Nix is always a struggle, just perhaps hoping that there is an issue being tracked around Big Sur support. Not to mention M1 Apple Silicon support at some stage.

**Comment by domenkozar** [comment]
@groodt As part of https://opencollective.com/nix-macos the goal is also to come up with a central place to track macOS support in a systematic way.

**Comment by toonn** [comment]
@groodt, #105026 tracks Apple Silicon support. I will be working towards tracking the status of macOS support.

There is a great deal of friction between supporting the broadest possible userbase, which requires a stdenv based on the oldest practical Apple SDK and supporting new software which requires newer versions of the SDK.

**Comment by bergkvist** [comment]
# MacOS Catalina vs MacOS Big Sur
I set up 2 virtual machines using [OSX-KVM](https://github.com/kholia/OSX-KVM). One with Catalina, and one with Big Sur. Then I installed the latest version of nixpkgs on both VMs.

The Python-version from nixpkgs is exactly the same - but the behaviour when using ctypes.util.find_library is different.

## MacOS Catalina
```zsh
tobias@Catalina ~ % nix-shell -p python39 --run "python -c 'import ctypes.util; print(ctypes.util.find_library(\"c\"))'"
/usr/lib/libc.dylib
tobias@Catalina ~ % nix-shell -p python39 --run "which python"
/nix/store/1z0mfkg7hvdh0yzv0gljxpqplv69b4mk-python3-3.9.4/bin/python
```

## MacOS Big Sur
```zsh
tobias@BigSur ~ % nix-shell -p python39 --run "python -c 'import ctypes.util; print(ctypes.util.find_library(\"c\"))'"
None
tobias@BigSur ~ % nix-shell -p python39 --run "which python"                                                          
/nix/store/1z0mfkg7hvdh0yzv0gljxpqplv69b4mk-python3-3.9.4/bin/python
```

**Comment by bergkvist** [comment]
This might be the reason ctypes.util.find_library has stopped working on Big Sur:

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

Source: https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes

**Comment by bergkvist** [comment]
Digging into the source code in Python ctypes, we see the following code that is responsible for `None` being returned:


```py
# /nix/store/1z0mfkg7hvdh0yzv0gljxpqplv69b4mk-python3-3.9.4/lib/python3.9/ctypes/macholib/dyld.py

# ...

try:
    from _ctypes import _dyld_shared_cache_contains_path
except ImportError:
    def _dyld_shared_cache_contains_path(*args):
        raise NotImplementedError

# ...

def dyld_find(name, executable_path=None, env=None):
    """
    Find a library or framework using dyld semantics
    """
    for path in dyld_image_suffix_search(chain(
                dyld_override_search(name, env),
                dyld_executable_path_search(name, executable_path),
                dyld_default_search(name, env),
            ), env):

        if os.path.isfile(path):
            return path
        try:
            if _dyld_shared_cache_contains_path(path):
                return path
        except NotImplementedError:
            pass
# ...
```

Notice that `os.path.isfile` will work on MacOS Catalina, but it won't work on MacOS Big Sur, since the shared libraries are no longer present as files in the file system.

The `_dyld_shared_cache_contains_path`-function here seems to be an attempted solution for MacOS Big Sur. Notice that in case this function fails to import on MacOS Big Sur, dyld_find will simply return None.

Let's verify that this is indeed the case:
```sh
tobias@Catalina ~ % nix-shell -p python39 --run "python -c 'from _ctypes import _dyld_shared_cache_contains_path'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '_dyld_shared_cache_contains_path' from '_ctypes' (/nix/store/1z0mfkg7hvdh0yzv0gljxpqplv69b4mk-python3-3.9.4/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so)
```

```sh
tobias@BigSur ~ % nix-shell -p python39 --run "python -c 'from _ctypes import _dyld_shared_cache_contains_path'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '_dyld_shared_cache_contains_path' from '_ctypes' (/nix/store/1z0mfkg7hvdh0yzv0gljxpqplv69b4mk-python3-3.9.4/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so)
```

As expected, we get an import error, which explains why `ctypes.util.find_library()` always returns None on MacOS Big Sur.

**Comment by bergkvist** [comment]
It seems like the following define-flag needs to be set when compiling python/cpython:
- `HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH`

As you can see here, _dyld_shared_cache_contains_path won't exist unless HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH has been defined:
https://github.com/python/cpython/blob/2c2055884420f22afb4d2045bbdab7aa1394cb63/Modules/_ctypes/callproc.c#L1995-L1997

**Comment by bergkvist** [comment]
Python's configure-script seems to automatically define `HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH` if it can import `_dyld_shared_cache_contains_path` from `<mach-o/dyld.h>`.
https://github.com/python/cpython/blob/2c2055884420f22afb4d2045bbdab7aa1394cb63/configure.ac#L3790-L3794

This probably means that if the build server used to populate the nixpkgs cache itself was running on Big Sur, then ctypes.util.find_library would automatically work in nixpkgs.python39.

**Comment by bergkvist** [comment]
A more polymorphic/cross-compatible alternative to using `_dyld_shared_cache_contains_path` from `mach-o/dyld` is to use `dlopen`, as described in the MacOS Big Sur 11.0.1 release notes:

```c
// library_exists.c
#include <stdio.h>
#include <dlfcn.h>

int library_exists(const char* path) {
    void* handle = dlopen(path, RTLD_LAZY);
    if (handle != NULL) {
        dlclose(handle);
        return 1;
    }
    return 0;
}

int main(int argc, char** argv) {
    const char* path = argv[1];
    if (library_exists(path)) {
        printf("Library (%s) exists\n", path);
    } else {
        printf("Library (%s) not found\n", path);
    }
    return 0;
}
```

As we can see below, this can be compiled on either Big Sur or Catalina - and does not require any define-flags when compiling

### Catalina
```sh
tobias@Catalina ctest % clang library_exists.c -o library_exists
tobias@Catalina ctest % ./library_exists /usr/lib/libc.dylib
Library (/usr/lib/libc.dylib) exists
tobias@Catalina ctest % ./library_exists /usr/lib/libc1.dylib
Library (/usr/lib/libc1.dylib) not found
```

### Big Sur
```sh
tobias@BigSur ctest % clang library_exists.c -o library_exists
tobias@BigSur ctest % ./library_exists /usr/lib/libc.dylib
Library (/usr/lib/libc.dylib) exists
tobias@BigSur ctest % ./library_exists /usr/lib/libc1.dylib
Library (/usr/lib/libc1.dylib) not found
```

### ctypes change
Imagine that we have wrapped this function into a CPython function importable from `_ctypes`:

```py
# ...

from _ctypes import library_exists

# ...

def dyld_find(name, executable_path=None, env=None):
    """
    Find a library or framework using dyld semantics
    """
    for path in dyld_image_suffix_search(chain(
                dyld_override_search(name, env),
                dyld_executable_path_search(name, executable_path),
                dyld_default_search(name, env),
            ), env):

        if library_exists(path):
            return path

# ...

```

**Comment by bergkvist** [comment]
Turns out building Python on an older version of MacOS than where you intend on running it is now a legacy/deprecated approach. The way to create a portable binary (since Python 3.9) is to use MACOSX_DEPLOYMENT_TARGET when running configure:
```sh
# Support the current version of MacOS that you are compiling on, and all the way back to 10.9
./configure MACOSX_DEPLOYMENT_TARGET=10.9
```

If my PR to CPython gets merged, it will support the legacy-approach of building on an older MacOS version than the target such that find_library will start working again on Big Sur. Although only for Python >= 3.9. 

Python 3.8 has gone into security-fix-only mode, and these changes will as a result never be backported to Python 3.8 on the CPython side. That means Python 3.8 currently is in a kind of limbo-state where you can't make a version that is portable across both Catalina and Big Sur (without patching the source code)

I could create a nixpkgs-specific patch for Python 3.8 to make it portable between Catalina and Big Sur if this is of interest. In particular it would fix the issue of find_library returning None on Big Sur.

**Comment by FRidh** [comment]
> Python 3.8 has gone into security-fix-only mode, and these changes will as a result never be backported to Python 3.8 on the CPython side. That means Python 3.8 currently is in a kind of limbo-state where you can't make a version that is portable across both Catalina and Big Sur (without patching the source code)

> I could create a nixpkgs-specific patch for Python 3.8 to make it portable between Catalina and Big Sur if this is of interest. In particular it would fix the issue of find_library returning None on Big Sur.

Make the patch, post it on `bugs.python.org` on the relevant thread, and then fetch it from there.

**Comment by bergkvist** [comment]
This got backported to Python 3.8 after all: https://github.com/python/cpython/pull/28054

**Comment by bergkvist** [comment]
@larsr Although 3.9.6 -> 3.9.7 was reverted for other reasons as you describe, the patch to fix this problem was included for 3.9.6 here: https://github.com/NixOS/nixpkgs/pull/146477

**Comment by larsr** [comment]
@bergkvist It was only in the staging branch, not in nixpkgs-unstable or master, and it was removed again six days ago.

The motivation for the removal was that this is fixed in python 3.9.7 (which is true), but history shows that we were unable to just upgrade to 3.9.7.  
There must be some communication missing here.
Perhaps the patch to be kept until a successful merge of 3.9.7 is possible? 

Here is the history for cpython/3.9 in the staging branch
https://github.com/NixOS/nixpkgs/commits/staging/pkgs/development/interpreters/python/cpython/3.9


(There is no patch in nixpkgs-unstable: 
https://github.com/NixOS/nixpkgs/tree/nixpkgs-unstable/pkgs/development/interpreters/python/cpython/3.9 )

**Comment by dnadlinger** [comment]
So seems like https://github.com/NixOS/nixpkgs/pull/146477 should be applied again? Or what are the chances for 3.9.9 to be merged soon?

**Comment by bergkvist** [comment]
Seems like 3.9.9 has already been merged into the staging branch:
https://github.com/NixOS/nixpkgs/blob/373d2348bedd941512f25d145c22a53be64c9b43/pkgs/development/interpreters/python/default.nix#L132-L140

Not sure when it will make it into the master branch

**Comment by dotlambda** [comment]
Can this be closed?
I have an issue in https://github.com/NixOS/nixpkgs/pull/172274 of which I don't know whether it's related.

**Comment by abathur** [comment]
It sounds like this can be closed, and I asked someone in the macOS room on matrix to confirm:

> **abathur**
> can anyone on big sur or newer confirm that running the command below yields similar output?
> ```console
> $ nix-shell -p python39 --run "python -c 'import ctypes.util; print(ctypes.util.find_library(\"c\"))'"
> /usr/lib/libc.dylib
> ```
> 
> **Zhaofeng Li**
> Yes, both aarch64-darwin (/nix/store/qb1zy7p74iyzlzj1wz31f7qc9j8ii8vs-python3-3.9.14) and x86_64-darwin (/nix/store/lvswy3rril3p9qzxsa3msfdm35zwwh5g-python3-3.9.16) yielded the same for me
> The ARM one is on Ventura 13.5 beta, and X86 one is Ventura 13.4

Happy to reopen if I'm mistaken.
