### ISSUE TITLE
nmap licensing has changed

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#105119]
Seems like nmap changed the licence with the 7.90 release from GPL-2 to NPSL (Nmap public source licence).

NPSL is "based" on GPL but adds some nasty things such as:
> Proprietary software companies wishing to use or incorporate Covered Software within their programs must contact Licensor to purchase a separate license

Which conflicts with the freedom 0:
> The freedom to run the program as you wish, for any purpose (freedom 0).

Discussions about this:
 - Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972216
 - Gentoo: https://bugs.gentoo.org/749390
 - Upstream: https://github.com/nmap/nmap/issues/2199

The actual license file: https://svn.nmap.org/nmap/LICENSE

They also seem to bundle a GPL library, and their license doesn't seem to be GPL compatible.

#### Suggestion:
So we should probably add this new license at least. NPSL looks non-free to me.

Non-free is a good default until FSF or anyone has looked at it. We can always follow suit with what Debian does as well.

**Comment by gebner** [comment]
> Non-free is a good default until FSF or anyone has looked at it.

Another option would be to revert to 7.80 for now.  The new license seems to be a legal minefield even if you're ok with closed source.

**Comment by Ma27** [comment]
Yeah while looking at the issue in the train I thought of the same as well, will do that now.

**Comment by etu** [comment]
I just read the release annoncement for 7.90: https://seclists.org/nmap-announce/2020/1

Just to see if the license change was mentioned there. Which it is:
> We also did some long-needed license cleanup and gave the
> license a name (Nmap Public Source License) to avoid the previous confusion
> of Nmap being under "GPLv2 with various clarifications and exceptions".
> The NPSL is still based on the GPLv2, but brings in terms from some other
> popular open source licenses. See https://nmap.org/npsl

Do I read this right they weren't really GPLv2 to begin with and just clarified that? That's like a major thing...

**Comment by Ma27** [comment]
First of all I just realized that I merged the original PR, so I really have to apologize for missing that license thing back then!

cc @armijnhemel in case you currently have time and energy for that, would you mind taking a look at the issue? I'm pretty sure that you have way more knowledge and insights about that kind of licensing issue than we have :).

Is there any kind of statement from OSI or FSF yet? Also, I'm wondering if other distros that are even more focused on free software than we are (such as Guix) have e.g. started a new fork that we may want to use as well.

**Comment by etu** [comment]
More details from the changelog: https://nmap.org/changelog#7.90

> Upgraded the Nmap license form a sort of hacked-up version of GPLv2 to a cleaner and better organized version (still based on GPLv2) now called the Nmap Public Source License to avoid confusion. See https://nmap.org/npsl/ for more details and annotated license text. This NPSL project was started in 2006 (community discussion here: https://seclists.org/nmap-dev/2006/q4/126) and then it lost momentum for 7 years until it was restarted in 2013 (https://seclists.org/nmap-dev/2013/q1/399) and then we got distracted by development again. We still have some ideas for improving the NPSL, but it's already much better than the current license, so we're applying NPSL Version 0.92 to the code now and can make improvements later if needed. This does not change the license of previous Nmap releases.

@Ma27 I must say that I'm not sure if it's worth to roll the package back since it actually haven't seemed to change really. It just was weird to begin with and just now got a name on the weirdness.

**Comment by gebner** [comment]
It's not just a new name, apparently they also added new requirements in 7.90: https://bugs.gentoo.org/749390#c7

**Comment by SuperSandro2000** [comment]
I don't think we should revert it either. Add the new license and mark it unfree until this is clarified.

**Comment by Ma27** [comment]
> It's not just a new name, apparently they also added new requirements in 7.90: https://bugs.gentoo.org/749390#c7

Oof.... that's actually another reason for reverting.

**Comment by Mindavi** [comment]
I'm in favor of marking as nonfree until the FSF or some other authoritative organisation decides otherwise.

**Comment by armijnhemel** [comment]
Either revert, or mark as non-free. Or, revert and add the new, non-free, version next to it.

**Comment by gebner** [comment]
The nmap update has already been reverted.  Let's wait what upstream and the legal teams of debian/fedora say.

See also the upstream issue https://github.com/nmap/nmap/issues/2199

**Comment by Alessandro-Barbieri** [comment]
Fedora's stance
https://lists.fedoraproject.org/pipermail/legal/2014-January/002366.html
https://fedoraproject.org/wiki/Licensing/Nmap

**Comment by gebner** [comment]
@Alessandro-Barbieri That's the old license (until version 7.80).  This issue is about the new license (in version 7.90).

**Comment by oxapentane** [comment]
Fedora marked the new licence as "Bad" due to being incompatible to the open source definition

https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/message/GZIDC4DHXZP67LFU7P2OT2AQVDJRHZ2M/

**Comment by SuperSandro2000** [comment]
https://github.com/NixOS/nixpkgs/pull/109555#issuecomment-761607110

> There is an issue with the changed license. #105129 (comment)

> I think a good approach, I would approve and merge, would be to split 7.80 of with the free license and create new, unfree package that has version 7.91. Naming them nmap and nmap-unfree would probably required to remain backwards compatibility.

**Comment by etu** [comment]
So, now there's an update here that we may want to act on: https://github.com/nmap/nmap/issues/2199#issuecomment-792048244

To quote the post:
> OK. Effective immediately, Nmap 7.91 (which is the current version) and 7.90 can also be used and redistributed under the previous (Nmap 7.80) license terms. We've also added this license grant statement to the NPSL summary page and posted the old license terms on Nmap.org along with a note that they can apply to 7.90 and 7.91 as well. Meanwhile, everyone who prefers the NPSL can continue using that.
>
> We are still hoping to do a major license review before the next Nmap release, and we will consider all the great feedback posted here. But that release is probably months away, so we hope this new license grant helps in the meantime.

This means that `nmap` 7.91 is now available under the same license as 7.80 is. The license that 7.80 uses is still a "bad license" because it's still a custom license. But it's a license that we and other distributions have considered good because it was assumed to be GPLv2.

So I'm thinking that we could upgrade `nmap` to 7.91 by now, because it's still not good, but it's not worse than before except we are aware of it now.

Then we just hope that they do some good re-licensing in a future release.

**Comment by fpletz** [comment]
Merged #118158 which removed nmap-unfree. This issue is done for now. Thanks everyone.
