### ISSUE TITLE
Doc: what's the correct info string for a shell session?

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#105186]
@jtojnar requested using ShellSession in https://github.com/NixOS/nixpkgs/pull/105007#discussion_r530916783

I see various references to using `console` for sh-session files.

Is there some canonical documentation we can find to favor one over the other?

**Comment by jtojnar** [comment]
These are not standardized as fair as I can tell. ShellSession is what 
GitHub (but not GitLab) supports but it does not really support marking 
prompts non-selectable. We would need to make prompts unselectable in 
our toolchain either way and it does not really matter what we choose, 
as long as we settle on something.

**Comment by ryantm** [comment]
Okay, seems fine to use ShellSession if that works on GitHub.

**Comment by ryantm** [comment]
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml is what is used by GitHub and it does look like ShellSession is the canonical one for a shell session. `bash session` and `console` are aliases of it.
