### ISSUE TITLE
rxvt_unicode_with-plugins crashing on url-select

### ISSUE THREAD

**Issue by Lassulus** [NixOS/nixpkgs#10513]
https://github.com/NixOS/nixpkgs/commit/5877d74f03f8164af91850d439d7cc584c006d6e broke url-select in urxvt. the terminal just hangs if you start url-select.

**Comment by Lassulus** [comment]
@abbradar

**Comment by abbradar** [comment]
Indeed, it did -- strange that I've not noticed that before. Thanks for reporting, I'll revert.

**Comment by abbradar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/9c2d733426058ed933ad6c869054fc8c2dc891e3
