### ISSUE TITLE
Python on Darwin: pyobj tracking issue

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nixpkgs#105156]
This issue is about the Python Package pyobjc and all of its over 50 sub-packages.

I will use this issue to track packages which require pyobjc packaged and their status. If someone finds a package which requires pyobjc or any subpackage please leave a comment here and/or link to this issue.

To get started working on anything below #102306 is required to get merged first.

# Package list:

- swaglyrics #101360
- plover.stable
- etesync-dav #105519
- python3Packages.pynput
- swspotify https://github.com/NixOS/nixpkgs/pull/109539#issuecomment-761589937
- saltstack https://github.com/NixOS/nixpkgs/issues/105156#issuecomment-760395695
- ntfy https://github.com/NixOS/nixpkgs/issues/105156#issuecomment-764030971
- iterm2
- salt https://github.com/NixOS/nixpkgs/pull/114461#issuecomment-786841962

**Comment by christoffer-a-sinch** [comment]
Hi @SuperSandro2000 ,

I've tried installing _saltstack_ using `nix-env -i salt` and it fails with (^1):

```
...
Executing pipInstallPhase
/private/tmp/nix-build-salt-3002.2.drv-0/salt-3002.2/dist /private/tmp/nix-build-salt-3002.2.drv-0/salt-3002.2
Processing ./salt-3002.2-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement pyobjc-framework-businesschat==6.2.2 (from salt)
ERROR: No matching distribution found for pyobjc-framework-businesschat==6.2.2
builder for '/nix/store/w6p7cg9wj4wsinpsykm45v6j01bvw95x-salt-3002.2.drv' failed with exit code 1
error: build of '/nix/store/w6p7cg9wj4wsinpsykm45v6j01bvw95x-salt-3002.2.drv' failed
```

^1 It fails in a non-deterministic way, e.g. re-runs may produce failure referencing other pyobjc frameworks, e.g. `pyobjc-framework-colorsync`, or I also observed `contextlib2==0.6.0.post1`, and more variants.

**Environment details:**

macOS 10.15.7
nix version 2.3.10
channel: `nixpkgs-unstable` (https://releases.nixos.org/nixpkgs/nixpkgs-21.03pre263062.980c4c3c2f6)

Full log attached: [nix-env-i-salt.log.txt](https://github.com/NixOS/nixpkgs/files/5816349/nix-env-i-salt.log.txt)

**Comment by austinbutler** [comment]
Also affects `ntfy`:

```
installing
Executing pipInstallPhase
/private/var/folders/1s/gpt7p1x559sb7qjb_4bhq7zc75yv8y/T/nix-build-ntfy-2.7.0.drv-0/source/dist /private/var/folders/1s/gpt7p1x559sb7qjb_4bhq7zc75yv8y/T/nix-build-ntfy-2.7.0.drv-0/source
Processing ./ntfy-2.7.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /nix/store/z3nyksz6f7yqznwkdmzd8fzd2fa8xi2n-python3.8-requests-2.25.0/lib/python3.8/site-packages (from ntfy==2.7.0) (2.25.0)
ERROR: Could not find a version that satisfies the requirement pyobjc; sys_platform == "darwin" (from ntfy)
ERROR: No matching distribution found for pyobjc; sys_platform == "darwin"
builder for '/nix/store/jim8hzs0js0d8y6l0d9g7iqsr35dgbd6-ntfy-2.7.0.drv' failed with exit code 1
error: build of '/nix/store/jim8hzs0js0d8y6l0d9g7iqsr35dgbd6-ntfy-2.7.0.drv' failed
```

**Comment by austinbutler** [comment]
#102306 builds for me and allows `ntfy` to build successfully, although after that I seem to run into https://github.com/dschep/ntfy/issues/171.

**Comment by ferrine** [comment]
Hey, I have a MWE enabling the build of pyobjc-core #336801, is that helpful?
