### ISSUE TITLE
cadquery: 2.0 -> 2.0.1

### ISSUE THREAD

**Issue by s-ol** [NixOS/nixpkgs#105131]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: python37Packages.cadquery 

current version: 2.0
desired version: 2.0.1

###### Notify maintainers

maintainers: @costrouc  @marcus7070 

###### Note for maintainers
- simply updating the `src` field leads to an import error - missing package [`OCP`](https://github.com/CadQuery/OCP).
- looking at the ArchLinux AUR PKGBUILDS ([1](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-cadquery) [2](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-ocp)), the `pythonocc-core-cadquery` dependency is dropped and `python-ocp` [takes it place](https://github.com/CadQuery/cadquery/commit/98fa16a0fd3ba0a324eb10518fe3491134a10097#diff-038525cf3a6b6ddf3f5a41df557deefda198a8fbec296fb62a65951cbcd7893b). It seems that `python-ocp` also requires a fork of pywrap, which is maintained [here](https://github.com/CadQuery/pywrap). These two are above my Nix skill level at the moment, so I stopped experimenting at this point.
- python-ocp versions track opencascade releases. The latest version is 4.5-RC1. I can confirm that version 4.4-RC2 works on ArchLinux, but it seems that `cadquery` may not have compatibility with opencascade 4.5 and python-ocp 4.5 yet.
- Please tag this issue in your PR.

**Comment by marcus7070** [comment]
If you want to use cadquery/cq-editor and you can use flakes, then [here is my flake for them](https://github.com/marcus7070/cq-flake).

As far as upgrading the versions in nixpkgs, I've decided against doing that. You can see some of my reasons [here](https://github.com/NixOS/nixpkgs/issues/100126#issuecomment-706950187). In addition to what I've said there, I've also recently discovered that `opencascade-occt` has to be built with different flags as well, which would add even more compile time.

**Comment by jonringer** [comment]
If you would like to update a package, I have a video showing the steps to do so [here](https://www.youtube.com/watch?v=D_IZ2EfW_8U)

**Comment by s-ol** [comment]
@marcus7070 I'm currently on `nixos-20.09` and would like to stay there, if I understand correctly that means I cannot currently use Nix flakes?

In terms of UX, it is a bit unfortunate to find a package that seems perfect, then realize its outdated and essentially EOL'd in the repository. If/when flakes are usable in all cases, it's still somewhat annoying to learn about one mechanism of doing things (nixpkgs) and then realize that the one you really needed was another one (flakes), so it might be a good idea to add a deprecation warning somewhere in the metadata for cadquery/cq-editor.

**Comment by marcus7070** [comment]
> @marcus7070 I'm currently on `nixos-20.09` and would like to stay there, if I understand correctly that means I cannot currently use Nix flakes?

I think you actually can. The 20.09 channel version of `nixUnstable` is: https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/tools/package-management/nix/default.nix#L210, which references commit 79aa7d95183cbe6c0d786965f0dbff414fd1aa67 of NixOS/nix, which seems to have flakes defined: https://github.com/NixOS/nix/tree/79aa7d95183cbe6c0d786965f0dbff414fd1aa67/src/libexpr/flake

So I think you can follow the instructions here: https://nixos.wiki/wiki/Flakes#NixOS

> it might be a good idea to add a deprecation warning somewhere in the metadata for cadquery/cq-editor.

That's a good point. I'm not going to make a PR just for that, but next time I do something to the package I'll add a note in the description.

**Comment by s-ol** [comment]
@marcus7070 It seems you're right, the flake works fine with the setup described there :)

Should we leave this issue open as a reminder for the deprecation notice in the meantime? I can change the title to reflect that.

**Comment by marcus7070** [comment]
I would rather you keep the title as is and close the issue. It's good to know there is interest in getting a recent version of CadQuery into nixpkgs. If there was interest from a large number of users then perhaps the effort and build times could be justified.

**Comment by s-ol** [comment]
Right, then I will close this for now :)
