### ISSUE TITLE
haskellPackages.splot fails to build

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#10519]
I'm on the release-15.09 branch:

```
$ nix-env -iA nixos.haskellPackages.splot
...
Tools/StatePlot.hs:17:8:
    Could not find module ‘Data.ByteString.Lex.Double’
    Use -v to see a list of the files searched for.

Tools/SPlotMain.hs:24:8:
    Could not find module ‘Data.ByteString.Lex.Lazy.Double’
    Use -v to see a list of the files searched for.
builder for ‘/nix/store/dgqp2679sdca95dcjhai2x499zrki3cs-splot-0.3.12.drv’ failed with exit code 1
```

**Comment by peti** [comment]
What makes you think that this issue is caused by Nixpkgs?

**Comment by bjornfor** [comment]
Uhm, right, I guess I don't know. It was just a "reflex" to create the issue here. Are you implying that it is the upstream dependency info that is to blame? If so, I can make an upstream issue.

**Comment by peti** [comment]
I don't see any reason to assume that Nixpkgs might cause that error, so it's probably best to report it upstream. IMHO, the package can't cope with recent versions of `bytestring-builder`.

**Comment by Profpatsch** [comment]
Can be closed @peti

**Comment by bjornfor** [comment]
@Profpatsch: Thanks for the reminder. It works now on both NixOS 16.03 and 16.09pre/unstable/master, so closing.
