### ISSUE TITLE
Steam Aberoth libGL problem

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10526]
1) Install Steam
2) Install Aberoth game in Steam
3) Run it
```
ERROR: ld.so: object '/home/netsu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/netsu/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
jre1.6.0_45/bin/java: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by vcunat** [comment]
It looks like you are running a 32-bit game: have you set `hardware.opengl.driSupport32Bit = true;`? (I'm assuming 64-bit NixOS.)

**Comment by Pitometsu** [comment]
Looks like you right, sorry for stupid issue.

**Comment by mucaho** [comment]
I don't believe this is stupid issue, I had the same one, but figured it out eventually (had I just searched for recent steam issues in this repository, I would have found the solution faster).

Could this be documented somewhere or an error message thrown if you are on 64 bit PC trying to install steam without `hardware.opengl.driSupport32Bit = true` set?

**Comment by Pitometsu** [comment]
@mucaho in my case I just used `optirun` for *steam* instead of `optirun32`.

**Comment by mucaho** [comment]
Hmm then my issue looks like to be a different one - steam won't install on my machine without that `hardware.opengl.driSupport32Bit = true` flag.
