### ISSUE TITLE
datadog-agent: Update to v7

### ISSUE THREAD

**Issue by schneefux** [NixOS/nixpkgs#105221]
datadog-agent v7 is available (https://github.com/DataDog/datadog-agent) and uses python3 by default. There are many new integrations (https://github.com/DataDog/integrations-core) which are incompatible with v6.
The build process seems to have changed, the upgrade steps (https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/dd-agent/README.md) do not work because there is no `Gopkg.lock` in the datadog-agent repository. As someone who does not know Go I do not know how to proceed.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: datadog-agent

current version: 6.11.2
desired version: 7.24

###### Notify maintainers

maintainers: @thoughtpolice @domenkozar @rvl

###### Note for maintainers

Please tag this issue in your PR.

**Comment by schneefux** [comment]
still relevant

**Comment by john-consumable** [comment]
I took a look at this and I came up with a minimum patch that builds and runs (#136109), but I am totally unsure if the correct integrations are built. It looks like there is a lot of new build machinery using [invoke](http://www.pyinvoke.org/).

**Comment by john-consumable** [comment]
@schneefux does this work for you?

**Comment by xvello** [comment]
Hello @john-consumable, I am currently testing an upgrade to release-21.11, and the datadog-agent package lost python support: the core golang features (core checks, log collection, process-agent) work OK, but python checks don't load.
This is because the build tag for python support has changed from `cpython` to just `python`. Trying to build the package with that tag fails though, because they added a [`rt-loader` helper library](https://github.com/DataDog/datadog-agent/tree/main/rtloader) to interface with python. My guess is that we'll need to package it first, as a dependency of the agent.

Happy to help on this one, although I'm not that good at packaging.

[Here is the derivation build log](https://github.com/NixOS/nixpkgs/files/7612269/datadog-agent-build.log)

**Comment by bojanrajkovic** [comment]
I'm having this problem as well — the base agent works OK, but anything that requires a Python package doesn't work at all. @xvello, did you ever figure out a fix for the rt-loader helper library?

**Comment by xvello** [comment]
Heya @bojanrajkovic, I stopped my investigation at the rt-loader dependency and did not have the patience to try packaging it.

Instead, I worked around the issue by running the official docker image in podman containers. I managed to get journald logs tailing and network metrics (with `--network=host`) and moved on. If you want, I can cleanup my derivation and post it as a gist.

**Comment by bojanrajkovic** [comment]
Yeah, would love that — there were a couple things I was missing when
running it as a container that I was wanting to capture: host
CPU/memory/network metrics and containers. Everything else seemed to work
more or less OK.

**Comment by xvello** [comment]
@bojanrajkovic here you go: https://gist.github.com/xvello/09d8a2c5b5e1b7ee48dd744658298817

The agent is the only containers I run, so I didn't set up the podman integration, but it should work OK by mounting the right socket, as described in the documentation.

**Comment by Sohalt** [comment]
https://github.com/NixOS/nixpkgs/pull/185805 should provide the necessary fixes to run this without podman.

**Comment by domenkozar** [comment]
With the latest fixes I'm getting 

```
Could not initialize Python: could not load runtime python for version 3: Unable to open three library: libdatadog-agent-three.so: cannot open shared object file: No such file or directory
```

**Comment by domenkozar** [comment]
@Sohalt any ideas?

**Comment by Sohalt** [comment]
Nope, sorry. Don't have time to look into it rn. I can take a look next week if you haven't figured it out by then.

**Comment by actionshrimp** [comment]
I fixed the first part of the error around `libdatadog-agent-three.so` with [this commit](https://github.com/actionshrimp/nixpkgs/commit/845e54e94b4bfba4b99ce636f35415e4d5d86d08), but it looks like there are still a few issues with the python environment that the agent is given:

```
ERROR | (pkg/collector/embed_python.go:19 in pySetup) | Could not initialize Python: could not initialize rtloader: could not import base class: No module named 'datadog_checks.checks'
ERROR | (pkg/collector/scheduler.go:201 in getChecks) | Unable to load a check from instance of config 'apm': Python Check Loader: unable to import module 'apm': No module named 'apm'; Core Check Loader: Check apm not found in Catalog
ERROR | (pkg/collector/scheduler.go:248 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'apm'
ERROR | (pkg/collector/scheduler.go:201 in getChecks) | Unable to load a check from instance of config 'process_agent': Python Check Loader: unable to import module 'process_agent': No module named 'process_agent'; Core Check Loader: Check process_agent not found in Catalog
ERROR | (pkg/collector/scheduler.go:248 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'process_agent'
ERROR | (pkg/collector/scheduler.go:201 in getChecks) | Unable to load a check from instance of config 'winproc': Python Check Loader: unable to import module 'winproc': No module named 'winproc'; Core Check Loader: Check winproc not found in Catalog
ERROR | (pkg/collector/scheduler.go:248 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'winproc'
...

Inspecting the `site-packages` of the built python env built by [`integrations-core.nix`](https://github.com/NixOS/nixpkgs/blob/845e54e94b4bfba4b99ce636f35415e4d5d86d08/pkgs/tools/networking/dd-agent/integrations-core.nix#L93-L100), it seems like the necessary python modules needed haven't made it in there for some reason, but I'm not quite sure why.

**Comment by domenkozar** [comment]
@actionshrimp it looks good to me:

```
❯ ls /nix/store/kh9r0w0pjjax7zr90yhi4avb4l3sshr5-python3-3.10.9-env/lib/python3.10/site-packages/datadog_checks/
config.py  disk  errors.py  __init__.py  log.py  mongo  network  nginx  postgres  process  __pycache__
```

**Comment by actionshrimp** [comment]
@domenkozar - yeah some of them make it in ok, but some modules are missing, notably `checks` and `base` which lead to errors like the one I pasted above. I guess these should come from here: https://github.com/DataDog/integrations-core/tree/master/datadog_checks_base/datadog_checks ?

**Comment by ketzacoatl** [comment]
At this point, we can install the datadog-agent (v7) with nixos config. The service installs and runs as a systemd service. I can even see the agent register itself with datadoghq and send meta data.

However, it seems as though the agent's plugins are not all installed or available, and a lot of integrations don't work. In my testing, the docker integration is an easy example. The process checks seem to be another.

Question: do we close this issue and start a new one about the plugins not installing correctly, or do we resolve that in this issue? What do we need to do to include the agent's plugin/integration files with the agent install so they can be used by the agent?

**Comment by domenkozar** [comment]
Let's create another issue about non-working plugins.

**Comment by ketzacoatl** [comment]
@domenkozar should I create that new issue, or defer to you?

**Comment by domenkozar** [comment]
Feel free to create one.

**Comment by ketzacoatl** [comment]
Ok, is there any particular description of the problem or recommended solution that you would suggest I include? My explanation is more or less "the agent's plugins should be included in the installation".
