### ISSUE TITLE
fetchhg just started failed with SSL errors?

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#105202]
**Describe the bug**
I haven't changed anything locally, yet this started failing:

```
++ nix-prefetch --output raw -E '(import ./packages.nix).obs-wlrobs' --rev a31f4ce969bf
warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
The package wlrobs-bcc570977627 will be fetched as follows:
> fetchhg {
>   rev = "a31f4ce969bf";
>   sha256 = "1faiq2gdb7qis3m1hilm4pz8lkmkab75vzm608dbiazahhybf96p";
>   url = "https://hg.sr.ht/~scoopta/wlrobs";
> }

warning: unknown setting 'experimental-features'
error: error: --- Error --- nix-daemon
builder for '/nix/store/q56w8697f6xndv1wkkdwlnwrpvfn6gy8-hg-archive.drv' failed with exit code 255; last 3 log lines:
  getting https://hg.sr.ht/~scoopta/wlrobs (a31f4ce969bf) into /nix/store/6x3xaryr89nsizld5gw83d3kh82nl8xf-hg-archive
  (an attempt was made to load CA certificates but none were loaded; see https://mercurial-scm.org/wiki/SecureConnections for how to configure Mercurial to avoid this error)
  abort: error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
+ newsha256=
```

What's going on? As far as I can tell, `hg.sr.ht` is presenting a valid SSL certificate that Firefox trusts.

Thanks in advance...

EDIT:

this is with current `nixos-unstable`: 2247d824fe07f16325596acc7faa286502faffd1

**To Reproduce**
1. Try to build something with a source set the fetchhg shown in the error

**Expected behavior**
I expect it to use the system SSL certs to fetchhg and it to succeed.

**Comment by colemickens** [comment]
cc: @rprije who mentioned something similar happening with `fetchdarcs` in IRC https://logs.nix.samueldr.com/nixos/2020-11-28#1606523410-1606523426 (h/t to @cole-h for the log sleuthing)

**Comment by colemickens** [comment]
This repro'd in my CI environment. https://builds.sr.ht/~colemickens/job/353789

This is for `nixpkgs-wayland`. Another project, `wofi`, is also hosted on `hg.sr.ht`. It had an update 2 weeks ago that was driven by CI, and passed: https://github.com/colemickens/nixpkgs-wayland/commit/77d467d72098117d0952e4730e9f2b4071527687.

Possibly implying that whatever "broke" changed in the last couple of weeks.

**Comment by colemickens** [comment]
The CLI failure was in a pure nix-shell, but again, that was working fine a couple of weeks ago. Also, the failure I'm getting locally doesn't involve a `nix-shell`. (I even blocked direnv to make sure)

**Comment by rprije** [comment]
Thanks for cc-ing me. In case another test case is helpful, here's code that reproduces my CA error:

`backups.nix`:

```
{
  pkgs ? import (builtins.fetchTarball {
    # Commit hash for 20.09 as of 2020-11-22
    url = https://github.com/NixOS/nixpkgs/archive/9da0758c1cd4724cf09fd48fee11413f88c48c8d.tar.gz;
    sha256 = "1n8wy4a5hfrx3fqxlxkwnganb5y1l450v36255jj58j7fkcys6ss";
  })
    {
      config = { allowUnfree = true; };
    }
}:
let
  src = pkgs.fetchdarcs {
    url = "https://hub.darcs.net/rprije/backups";
    rev = "^v0\.2\.0\.1$";
    sha256 = "188vfgv1wpzmjfr6wg1sp82mhaz5d2hpp4rqcy6v0724xn5jk8zz";
  };
in
pkgs.haskellPackages.callPackage "${src}/nix/backups.nix" {}
```

Note that I'm using a recent release of 20.09 stable, not the unstable version described in this ticket.

And the error:

```
$ nix-build ./backups.nix --no-out-link
building '/nix/store/m9ns0p6s0wpnmizlc68hjgbrm9k6ngv3-fetchdarcs.drv'...
getting https://hub.darcs.net/rprije/backups  (tag ^v0.2.0.1$)  into /nix/store/vanp4bcj40aw788wk8in3i2i2z2xajra-fetchdarcs
Not a repository: https://hub.darcs.net/rprije/backups (Error getting "https://hub.darcs.net/rprije/backups/_darcs/inventory": InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa))))
builder for '/nix/store/m9ns0p6s0wpnmizlc68hjgbrm9k6ngv3-fetchdarcs.drv' failed with exit code 2
error: build of '/nix/store/m9ns0p6s0wpnmizlc68hjgbrm9k6ngv3-fetchdarcs.drv' failed
```

The certificate at `hub.darcs.net` appears to be new as of October, but I still expect its Let's Encrypt CA to be recognised as valid. I got lost trying to debug how `cacerts` gets used as a dependency in a nix build environment like this so I don't have much more to offer other than a hunch that `cacerts` itself is fine (since the same `cacerts` seems to work fine in my NixOS system environment) while its use in the build environment is broken somehow.

**Comment by colemickens** [comment]
Maybe #23128 is related?

**Comment by colemickens** [comment]
https://logs.nix.samueldr.com/nixos/2020-11-28#4296929;

**Comment by colemickens** [comment]
This was definitely user error. I was not calling `nix-prefetch` properly and so it was not evaluating with an empty sha256, but just the last old sha256 that was used with a previous rev. Not sure how this was ever working.

In case it's useful, for my project, this was fixed in https://github.com/colemickens/nixpkgs-wayland/commit/e094a4d97722be96f86d98bec9a6f2224a7aa4ee.
