### ISSUE TITLE
paprefs: requires dconf at runtime

### ISSUE THREAD

**Issue by edibopp** [NixOS/nixpkgs#105304]
**Describe the bug**
Using paprefs to change PulseAudio settings does not work. Instead a warning is shown on the command line:

**To Reproduce**
1. Install `paprefs` without explicitly installing `gnome3.dconf` (probably light-weight window managers only)
2. Start `paprefs`.
3. Go to "Simultaneous Output", tick "Add virtual output device for simultaneous output on all local sound cards".

**Expected behavior**
The box should be ticked and I get a virtual output device.
Instead this warning is shown on the command line:

```
dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

**Additional context**
I am using i3 as my window manager. And I guess this situation should only occur on light-weight window managers like it, particularly not on Gnome 3 or Cinnamon.
It looks like #11108 is related. As a workaround one can simply install `gnome3.dconf`, which fixes the issue for the end user.

**Notify maintainers**
@abbradar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.42, NixOS, 20.03.1998.93b68c7cc5a (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200521_00b562c`
 - channels(root): `"nixos-20.03.1998.93b68c7cc5a, nixos-unstable-20.09pre227294.46f975f81e0"`
 - channels(eduard): `"home-manager-20.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/52777#issuecomment-449788253.

**Comment by edibopp** [comment]
@jtojnar reading through these issues, it seems like there is no way to express this dependency and I basically messed up when setting up my homemade desktop environment without dconf enabled?

**Comment by jtojnar** [comment]
Right, you will need to enable necessary services manually. Either through NixOS config or through home-manager.

**Comment by edibopp** [comment]
Alright thanks. Then there is nothing to be done here, closing the issue.

**Comment by exarkun** [comment]
Closing the issue because it's broken but hard to fix, and then leaving each user who is impacted to discover this issue to find the workaround, seems like a less than optimal end-state.
