### ISSUE TITLE
Remove Python 2 from closure for minimal system

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#105392]
I'd like to remove python2.7 from the system closure for the NixOS minimal installation ISO. This bug is here to track this effort.

Known instances:
* parted
* asciidoc
* wafHook

Fixed instances:
???

**Comment by FRidh** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/101964.

**Comment by lukegb** [comment]
Hrm, I mostly wanted to have a separate tracking issue for specifically the minimal system ISO, but... I defer to you.
