### ISSUE TITLE
ThinLinc

### ISSUE THREAD

**Issue by NomisIV** [NixOS/nixpkgs#105399]
**Project description**
ThinLinc is a remote desktop application, like TeamViewer but for Linux. My college uses it to give students remote access to their school linux machines.

There is a generic Linux tarball and a MacOS image downloadable from their website (I have provided links below). The Linux tarball looks like something that would be moved to the filesystem root in a regular distro, and there is a global configuration file (./etc/tlclient.conf) which could be used for configuration options. I would personally find options for "FULL_SCREEN_MODE" and "OPTIONS_POPUP_KEY" particulary useful.

If someone knows how this could be done but doesn't have the time to do it themselves, please leave an explanation or a link to a relevant webpage. I would be happy to become a maintainer of this package, if I just knew the how-tos.

Here is the link to the AUR PKGBUILD for reference: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tlclient

If there are any questions, I'll be happy to provide more information

**Metadata**

* homepage URL: https://www.cendio.com/
* source URL: https://www.cendio.com/downloads/clients/tl-4.12.0-6517-client-linux-dynamic-x86_64.tar.gz (Linux) / https://www.cendio.com/downloads/clients/tl-4.12.0_6517-client-macos.iso (MacOS)
* license: nonfree (I think)
* platforms: unix, linux, darwin, (armv7?)

**Comment by veprbl** [comment]
You might want to use buildFHSUserEnv https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments , you can look at existing packages using it to see how its done

**Comment by h7x4** [comment]
Fixed in #342516
