### ISSUE TITLE
20.09: Caddy module broken with pkgs.caddy1

### ISSUE THREAD

**Issue by Moredread** [NixOS/nixpkgs#105372]
**Describe the bug**

PR #102186 broke the caddy module on 20.09.

This PR causes an error if `services.caddy.package = pkgs.caddy1`:

```
error: The option `services.caddy.agree' can no longer be used since it's been removed. this option is no longer necessary for Caddy 2
```

At https://github.com/deviant/nixpkgs/blob/6c30370d8dcc081daa744334ab352305525c08fb/nixos/modules/services/web-servers/caddy.nix#L115 the option is used for caddy1, but removed in the PR without a check for the caddy version.

The PR was a backport from unstable, where caddy1 isn't supported anymore.

**To Reproduce**

Check out the 20.09 branch of the nixpkgs repo, then

1. add after line 9 in `nixos/tests/caddy.nix`:

```
      services.caddy.package = pkgs.caddy1;
```
2. run `nix-build nixos/tests/caddy.nix`

**Additional context**

caddy1 doesn't seem to be covered for security updates by upstream anymore, see 
https://github.com/caddyserver/caddy/blob/master/.github/SECURITY.md#supported-versions

Maybe instead of fixing the issue the module could drop support for caddy1 (esp. as there hasn't been any other bug reports yet), or at least warn of the EOL status for caddy1.

**Notify maintainers**

@rushmorem @fpletz @zimbatm

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.1889.58f9c4c7d3a (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"home-manager, lorri, mozilla-overlay, nixos-20.09.1889.58f9c4c7d3a, nixos-hardware, nixos-unstable-21.03pre253060.a322b32e9d7, nixpkgs-20.09.1889.58f9c4c7d3a, nur"`
 - channels(addy): `"home-manager, lorri, mozilla-overlay, nixos-20.09.1889.58f9c4c7d3a, nixos-hardware, nixos-unstable-21.03pre253060.a322b32e9d7, nixpkgs-20.09.1889.58f9c4c7d3a, nur"`
 - nixpkgs: `/home/addy/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: caddy1
# a list of nixos modules affected by the problem
module: 
```

**Comment by aanderse** [comment]
ping @davidak just for informational purposes.

**Comment by davidak** [comment]
Caddy 1 is not supported anymore and was removed in https://github.com/NixOS/nixpkgs/pull/99371.

So it does not make sense to create a workaround for this.

We should remove caddy1 even from 20.09, since it's not supported and a security risk.

(migrating the config to caddy2 is a bit of work)
