### ISSUE TITLE
Warmux unstable-2017-10-20 is broken

### ISSUE THREAD

**Issue by vojta001** [NixOS/nixpkgs#105442]
**Describe the bug**
Running the warmux binary fails with
```
[ Run game ]
! Error in graphic/surface.cpp:50 (Warmux svn) : Unable to open image file '/nix/store/v6i46v1jaim3b45f1znnw3dqwqsir68i-warmux-unstable-2017-10-20/share/warmux/menu/background_loading.jpg': Failed loading libjpeg.so.62: libjpeg.so.62: cannot open shared object file: No such file or directory

./base/error.cpp:86: Missed assertion "false".
```

**To Reproduce**
1. Install warmux
2. `warmux`

**Expected behavior**
Warmux launches

**Additional context**
Manually building and running version 11.04.1 (f7bc33abf09c9a111b7b1d7f4eb6d322ace3efda) works.

I tried editing the expression for the current version, but adding `libjpeg_turbo` to `buildInputs ` does not help.

**Notify maintainers**

`@raskin` – Is this the real maintainer?

@c0bw3b – The author of the update to unstable-2017-10-20

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by iblech** [comment]
I cannot reproduce this on latest unstable. Can you try the following?

    $ nix-shell -I channel:nixos-unstable -p warmux
    $ warmux

Perhaps the issue, whatever it is, is already fixed. :-)

**Comment by vojta001** [comment]
You're right @iblech, sorry for false positive. I was using 9a43f55bb02dc76b2f977dca0c75997111d0b1f0; current nixos-unstable works for me as well.

**Comment by iblech** [comment]
Awesome that it works for you :-) Have a good week!
