### ISSUE TITLE
amdapp-sdk update to 3.0

### ISSUE THREAD

**Issue by blueberry** [NixOS/nixpkgs#10554]
Hi all,

I am trying to switch over to NixOS, and the most important feature for me is availability of OpenCL 2.0 on AMD radeon. I can see that ati-drivers is on 15.7 so it is ok (15.9 would be even better :), but amdapp-sdk has been on 2.8 for a long time. The latest is 3.0, which has support for OpenCL 2.0.

It would be great if someone can give me some pointers:
1. Is there any plan or interest by anyone to update the package to the latest amd's amdapp-sdk 3.0?
2. If I have to do myself, can you give me some pointers, since I am total nixos newbie?
2a. Would simply copypasting the old 2.8 data and updating it with new download locations and other easy changes for 3.0 work, or some (non-trivial) patching is needed?

**Comment by domenkozar** [comment]
cc @offlinehacker, this would also fix the build most probably.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by prusnak** [comment]
These libraries are not used by anything in the nixpkgs tree. Let's remove them instead: https://github.com/NixOS/nixpkgs/pull/86233
