### ISSUE TITLE
Pidgin: Voice and video not working

### ISSUE THREAD

**Issue by fuzzy-id** [NixOS/nixpkgs#10556]
After installing `pidgin-with-plugins` I cannot get voice and video working. I additionally installed `gstreamer` and `gst_plugins_{base,good,bad}`, but no luck either.

**Comment by fuzzy-id** [comment]
See #10559 on how to resolve this issue by setting `GST_PLUGIN_PATH`. I'd recommend to document this in the wiki as a first fix.

**Comment by hrdinka** [comment]
Please check if https://github.com/NixOS/nixpkgs/pull/13722 fixes your issue.

**Comment by rasendubi** [comment]
I believe the issue is fixed by #13722 and should be closed.

**Comment by rasendubi** [comment]
I'm closing this as it should be fixed by #13722. Feel free to reopen if the issue persists.
