### ISSUE TITLE
Pidgin: Apply patches to support newer libraries

### ISSUE THREAD

**Issue by fuzzy-id** [NixOS/nixpkgs#10558]
Pidgin is currently linked against gstreamer-0.10 which is abandoned. There [seems to exist a patch](https://hg.pidgin.im/pidgin/main/rev/2415067473ba) to make pidgin work with gstreamer-1.x. (I currently cannot access that link as pidgin.im seems to be down.) 

The [list of patches](http://pkgs.fedoraproject.org/cgit/pidgin.git/tree/) used by the Fedora project might also be of interest here.

**Comment by ktosiek** [comment]
Upgrading to 2.10.12 also gives gstreamer-1.0 support: https://developer.pidgin.im/wiki/ChangeLog#version2.10.12010216

**Comment by vcunat** [comment]
IIRC I tried the update some time ago but there were some build issues I couldn't solve immediately.

**Comment by bjornfor** [comment]
In NixOS 16.09 we now have pidgin 2.11.0 and it uses gstreamer-1.x. (Looks like it happend in 9ae2d387706b1eda07aa4952035faec88ed62b91.) Closing.
