### ISSUE TITLE
srtp crashes chromium 46.0.2490.71 (latest unstable)

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixpkgs#10555]
sites like http://rabb.it and google hangouts crash the content process within chromium, it has also been mentioned on the irc channel
```
2015-10-23 06:00:09 < obadz> if anyone is using the latest nixos-unstable with chromium, would you mind going to https://hangouts.google.com/ , clicking "Video call" and confirming that you get an "Aw, snap!" shortly after?
```
```
[clever@amd-nixos:/tmp]$ /run/current-system/sw/bin/chromium --user-data-dir=/tmp/foo/
[17865:17865:1023/060609:ERROR:navigation_entry_screenshot_manager.cc(141)] Invalid entry with unique id: 9
libpng warning: iCCP: known incorrect sRGB profile
[1618:1618:1023/060901:ERROR:sandbox_linux.cc(338)] InitializeSandbox() called with multiple threads in process gpu-process
Received signal 6
#0 0x55ad6764857e base::debug::StackTrace::StackTrace()
#1 0x55ad67648908 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fa3d3ba53e0 <unknown>
#3 0x7fa3d1c983e7 __GI_raise
#4 0x7fa3d1c997ea __GI_abort
#5 0x55ad6b9a5fae CRYPTO_sysrand
#6 0x55ad6b9a5ddb RAND_bytes
#7 0x55ad6b9a254b rand_source_get_octet_string
#8 0x55ad6b9a15ae stat_test_rand_source
#9 0x55ad6b9a17d7 stat_test_rand_source_with_repetition
#10 0x55ad6b9a0f4a crypto_kernel_init
#11 0x55ad6b99f179 srtp_init
#12 0x55ad6b937315 cricket::SrtpSession::Init()
#13 0x55ad6b937544 cricket::SrtpSession::SetKey()
#14 0x55ad6b93b5ec cricket::SrtpFilter::SetRtpParams()
#15 0x55ad6b986b34 cricket::BaseChannel::SetupDtlsSrtp()
#16 0x55ad6b98afa4 cricket::BaseChannel::ChannelWritable_w()
#17 0x55ad6bc140d0 cricket::TransportChannel::set_writable()
#18 0x55ad6bc140d0 cricket::TransportChannel::set_writable()
#19 0x55ad6bc04b98 cricket::DtlsTransportChannelWrapper::OnDtlsEvent()
#20 0x55ad6b76d7ef rtc::StreamAdapterInterface::OnEvent()
#21 0x55ad6b773cb7 rtc::NSSStreamAdapter::ContinueSSL()
#22 0x55ad6b774898 rtc::NSSStreamAdapter::OnEvent()
#23 0x55ad6bc04cda cricket::StreamInterfaceChannel::OnPacketReceived()
#24 0x55ad6bc072e5 cricket::DtlsTransportChannelWrapper::OnReadPacket()
#25 0x55ad6bc0b98c cricket::P2PTransportChannel::OnReadPacket()
#26 0x55ad6b716e59 cricket::Connection::OnReadPacket()
#27 0x55ad6a1710be content::(anonymous namespace)::IpcPacketSocket::OnDataReceived()
#28 0x55ad676b14e7 base::debug::TaskAnnotator::RunTask()
#29 0x55ad67665493 base::MessageLoop::RunTask()
#30 0x55ad676658f1 base::MessageLoop::DeferOrRunPendingTask()
#31 0x55ad676662fb base::MessageLoop::DoWork()
#32 0x55ad676687e9 base::MessagePumpDefault::Run()
#33 0x55ad6767a178 base::RunLoop::Run()
#34 0x55ad67664855 base::MessageLoop::Run()
#35 0x55ad67692881 base::Thread::ThreadMain()
#36 0x55ad6768f277 base::(anonymous namespace)::ThreadFunc()
#37 0x7fa3d3b9d484 start_thread
#38 0x7fa3d1d4c05d __clone
  r8: 000055ad6df5e0c0  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000202
 r12: 00007fa3b86317c2 r13: 0000000000000032 r14: 000000000000045a r15: 0000000000000000
  di: 0000000000000001  si: 0000000000000026  bp: 00007fa3b8631790  bx: 0000000000000032
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007fa3d1c983e7  sp: 00007fa3b8631558
  ip: 00007fa3d1c983e7 efl: 0000000000000202 cgf: 00bb000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
[clever@amd-nixos:~]$ ls -l /run/current-system/sw/bin/chromium
lrwxrwxrwx 1 root nixbld 67 Dec 31  1969 /run/current-system/sw/bin/chromium -> /nix/store/04kb35qhb64wzzzr2b47nlj40vlwi3l3-chromium-46.0.2490.71/bin/chromium
```

**Comment by obadz** [comment]
I've confirmed that 0ad0fbd is the culprit.  Shall we revert?

**Comment by bdimcheff** [comment]
fwiw I have had this problem with beta channel chromium too for at least several weeks.  I'm currently on version 46.0.2490.64, but it definitely applied to other versions.  Is there an upstream bug that anyone has seen for this?

**Comment by bdimcheff** [comment]
This seems related: https://github.com/iridium-browser/iridium-browser/issues/52... I guess there might be some issue getting /dev/urandom from inside chromium's sandbox, see: https://code.google.com/p/chromium/issues/detail?id=328475 and https://chromium.googlesource.com/chromium/src/+/10eda64c1a5c673dcdca74fbb774f522dc253ad7

**Comment by obadz** [comment]
If https://github.com/iridium-browser/iridium-browser/issues/52 is indeed our issue, then the problem is that we don't have OpenSSL enabled.

Looks like it was disabled by 8b4fae76b37d682ef3c5941429a5bdbe3540ae1f and replaced by NSS. @aszlig, do you want to comment on whether re-enabling is a good idea?

**Comment by obadz** [comment]
Looks like another solution might be to apply this patch: https://chromium.googlesource.com/chromium/src/+/10eda64c1a5c673dcdca74fbb774f522dc253ad7%5E%21/#F0

**Comment by aszlig** [comment]
OpenSSL was more or less officially supported at the time I created the Chromium source build but it was broken by upstream on a regular basis, so I switched to NSS. It however seems to have changed, see the the following document: https://docs.google.com/document/d/1ML11ZyyMpnAr6clIAwWrXD53pQgNR-DppMYwt9XvE6s/view
I'm working on Chromium this week, so I'll investigate and test this as well.

**Comment by wkennington** [comment]
Wouldnt it make more sense to just use the bundled boringssl for chromium?

**Comment by aszlig** [comment]
@wkennington: Maybe, as said, I have to catch up on all those Chromium issues these days anyway, so I'll investigate. Using as much system dependencies as possible has the advantage that it cuts down build time, so we might want to avoid using more bundled dependencies.

**Comment by wkennington** [comment]
But it has the major disadvantage of not being tested by upstream chromium
developers. I think in the case chromium where we have a solid security
story for bundled dependencies, we should use bundling as it provides more
stability. I have a hunch that we arent saving more than 10% (although
probably far less) build time by providing our own dependencies anyway. It
would be worth investigating what that breakdown actually looks like.

**Comment by obadz** [comment]
@ambrop72, thanks for fixing this in #11492 !

**Comment by layus** [comment]
@cleverca22, @aszlig : As this issue is fixed, would one of you mind to close this bug ?

**Comment by cleverca22** [comment]
yeah, srtp works great on 47 and 48
