### ISSUE TITLE
openrazer v2.8.0 -> v2.9.0

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#105576]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: openrazer

current version: 2.8.0
desired version: 2.9.0

###### Notify maintainers

maintainers:
- @evanjs 
- @roelvandijk 
###### Note for maintainers

Please tag this issue in your PR.

**Comment by prusnak** [comment]
Would you like to try sending a pull request @d4g?

Just change these two fields in the `pkgs/development/python-modules/openrazer/common.nix` file:

* set `version` to `2.9.0`
* set `src.sha256` to `1js7hq7zx5kj99brffrfaaah283ydkffmmrzsxv4mkd3nnd6rykk` (hash obtained by running `nix-prefetch-url -A python3Packages.openrazer.src` after changing the version)

**Comment by d4g** [comment]
@prusnak lets see how this plays out. I raised a pull request:  #105695

**Comment by prusnak** [comment]
Closed via https://github.com/NixOS/nixpkgs/pull/105695
