### ISSUE TITLE
setuptools: sdist reproducibility

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#105502]
**Describe the bug**

The 'sdist' intermediate source derivation of the python setuptools is not currently reproducible.

**To Reproduce**
1. `nix-store --query --graph $(nix-instantiate '<nixpkgs>' -A python3Packages.setuptools) | grep sdist`
2. find the derivation path
3. with that derivation path: `nix-build <derivation-path> --check`

**Expected behavior**

'check' should succeed.

We already untar and then retar the generated archive to control the timestamps.

While the version of setuptools we're on (47.3.1) is not very old (June 2020), upstream has since had several releases, up to v50.3.2. A quick test reveals 50.3.2 also does not yet produce stable timestamps. Upstream work on this has started (https://github.com/pypa/setuptools/pull/2136, https://github.com/pypa/setuptools/pull/1512, https://github.com/python/cpython/pull/20331) but stalled.

**Comment by FRidh** [comment]
50.3.1 is now in staging-next. https://github.com/NixOS/nixpkgs/pull/105584

As you linked to, this is in the end a distutils issue. That makes it a bit complicated, because distutils is moved out of cpython, which means any solution will likely be Python version dependent.

**Comment by raboof** [comment]
> That makes it a bit complicated, because distutils is moved out of cpython

How do you mean that? It looks like https://github.com/python/cpython/blob/master/Lib/distutils/archive_util.py is still there? (I'm not too familiar with the ecosystem, might have missed something)

**Comment by FRidh** [comment]
Still a draft though https://www.python.org/dev/peps/pep-0632/, I thought it was already accepted.

**Comment by raboof** [comment]
Long-closed by #105680
