### ISSUE TITLE
owncloud: We still ship 7.0.*, today 8.2 came out

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#10561]
I'm not using owncloud on nixos (as server instance). Anyways, 7.0.* vs. 8.2 is a word, isn't it?

Ping package maintainers: @pSub @matejc

**Comment by geerds** [comment]
We already have a PR for this: #10514

**Comment by matthiasbeyer** [comment]
Whoops. I'll close this.
