### ISSUE TITLE
KDE Menu Favourites - Entries not updated when there's an updated to the programs

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#10579]
A really annoying thing about Nixos is that in KDE you have a favourites menu where you can put the  favourite appications in so you can access the quickly.

However on upgrades, they all break. They are still there but not working anymore. So everytime I need to delete them again and readd them.

**Comment by ttuegel** [comment]
Which version of KDE are you using?

**Comment by sjau** [comment]
KDE 4

**Comment by Profpatsch** [comment]
(triage) sorry for the silence, is this still a problem?

**Comment by retrry** [comment]
At least KDE5 doesn't seem to have this problem anymore. KDE4 had this.

**Comment by Profpatsch** [comment]
We can probably close it as ”moving on” then. cc @ttuegel @sjau
