### ISSUE TITLE
Adobe flash player installer resource missing

### ISSUE THREAD

**Issue by thall** [NixOS/nixpkgs#10571]
Trying to upgrade 'Firefox with plugins', which depends on Adobe flash player. The URL to the resource is broken at the moment.

<pre>
building path(s) ‘/nix/store/n8fwbsh2xislppbiiffsdasx2j2kzzsm-install_flash_player_11_linux.x86_64.tar.gz’
 74 36.7M   74 27.3M    0     0  1426k      0  0:00:26  0:00:19  0:00:07 1502k
trying http://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.521/install_flash_player_11_linux.x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
error: cannot download install_flash_player_11_linux.x86_64.tar.gz from any mirror
builder for ‘/nix/store/bf3izgisiaqy2szx9iqmr4iwzbjlafxv-install_flash_player_11_linux.x86_64.tar.gz.drv’ failed with exit code 1
</pre>

nixos-version: 15.09.596.e4fe820 (Dingo)

**Comment by wedens** [comment]
workaround:
```nix
  nixpkgs.config = {
    allowUnfree = true;
    firefox.enableAdobeFlash = true;
    packageOverrides = pkgs: rec {
       flashplayer = pkgs.stdenv.lib.overrideDerivation pkgs.flashplayer (oldAttrs: {
        name = "flashplayer-11.2.202.535";
        src = pkgs.fetchurl {
          url = "http://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.535/install_flash_player_11_linux.x86_64.tar.gz";
          sha256 = "13fy842plbnv4w081sbhga0jrpbwz8yydg49c2v96l2marmzw9zp";
        };
      });
    };
  };
```

**Comment by vcunat** [comment]
Picked the update to 15.09.

**Comment by vcunat** [comment]
Thanks for reporting :-)
