### ISSUE TITLE
missing zsh completions

### ISSUE THREAD

**Issue by wedens** [NixOS/nixpkgs#10572]
Some derivations install completions for zsh to `${out}/share/zsh/site-functions/` but there is no common place where they're linked (like default `/usr/local/share/zsh/site-functions` or `/usr/share/zsh/site-functions`).
As workaround I've added:

``` nix
    zsh.interactiveShellInit = ''
      fpath=(
       ${pkgs.systemd}/share/zsh/site-functions/
       ${pkgs.mpv}/share/zsh/site-functions/
       ${pkgs.pulseaudioLight}/share/zsh/site-functions/
       $fpath
      )
    '';
```

Another problem is: there is no completion for `man` command.

`nixos-version: 15.09.615.af3774a (Dingo)`

**Comment by wedens** [comment]
man completion solved by adding `systemPackages = [ ... man_db]` and ` environment.etc."man_db.conf".text = "MANDATORY_MANPATH /run/current-system/sw/share/man";
`

**Comment by calbrecht** [comment]
zsh completions/site-functions enabled in  #11251 and #11271 
@wedens Could you open another issue regarding the MANPATH so this one could be closed?

**Comment by olejorgenb** [comment]
I guess it's useless pleading for enabling completion as default?

**Comment by olejorgenb** [comment]
MANPATH=$(man --path)

is another workaround for the man completion. It would be nice to get the zsh completion function to use `man --path`  if the other means fail. (this is what bash does)

**Comment by bennofs** [comment]
`manpath` seems to work on current NixOS unstable:

```
~ (master ⚡=) manpath
/home/.nix-profile/share/man:/run/current-system/sw/share/man
```

Closing this, please reopen if the issue still occurs.
