### ISSUE TITLE
add libreoffice dictionaries to hunspell

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#10575]
LibreOffice has many dictionaries. These are hunspell dictionaries. By packaging these as hunspell dictionaries, firefox and thunderbird would also benefit. Only a few languages are currenlty packaged.

git tree of the dictionaries;
http://cgit.freedesktop.org/libreoffice/dictionaries/tree/

link to packaged dictionaries sources:
http://download.documentfoundation.org/libreoffice/src/5.0.2/libreoffice-dictionaries-5.0.2.2.tar.xz

The files are packaged like this:
libreoffice-5.0.2.2/dictionaries/nl_NL/
libreoffice-5.0.2.2/dictionaries/nl_NL/hyph_nl_NL.dic
libreoffice-5.0.2.2/dictionaries/nl_NL/OpenTaal.png
libreoffice-5.0.2.2/dictionaries/nl_NL/nl_NL.dic
libreoffice-5.0.2.2/dictionaries/nl_NL/META-INF/
libreoffice-5.0.2.2/dictionaries/nl_NL/META-INF/manifest.xml
libreoffice-5.0.2.2/dictionaries/nl_NL/description.xml
libreoffice-5.0.2.2/dictionaries/nl_NL/README_NL.txt
libreoffice-5.0.2.2/dictionaries/nl_NL/license_en_EN.txt
libreoffice-5.0.2.2/dictionaries/nl_NL/nl_NL.aff
libreoffice-5.0.2.2/dictionaries/nl_NL/dictionaries.xcu
libreoffice-5.0.2.2/dictionaries/nl_NL/desc_nl_NL.txt
libreoffice-5.0.2.2/dictionaries/nl_NL/licentie_nl_NL.txt
libreoffice-5.0.2.2/dictionaries/nl_NL/desc_en_US.txt

**Comment by vcunat** [comment]
I thought Firefox and Thunderbird get dictonaries primarily as add-ons (that's how I get them at least).

**Comment by vandenoever** [comment]
Using extensions is one way of installing dictionaries. LibreOffice and Firefox can also use system dictionaries.

**Comment by Profpatsch** [comment]
(triage) status?

**Comment by vandenoever** [comment]
It would be nice if dictionaries would come as nix packages.

**Comment by kevincox** [comment]
@vandenoever  Could you do the packaging? I would like to see this as well.

**Comment by vandenoever** [comment]
Not at the moment, but perhaps in a few weeks.

**Comment by kevincox** [comment]
That would be awesome. Because I suspect this kind of thing would be quite far down the wishlist for most contributors. So if you want to see it done you will probably have to do it yourself.

**Comment by Profpatsch** [comment]
Would this be fixed by #14430? If so then I suggest we close this issue.

**Comment by vandenoever** [comment]
Yes, #14430 is the same.
