### ISSUE TITLE
Replace ssmtp with msmtp (which needs a corresponding module)

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#105710]
The ssmtp program is dead/unmaintained. The commonly suggested substitute is msmtp.

While [home-manager has a module for msmtp][1], NixOS lacks one.

[1]: https://github.com/nix-community/home-manager/blob/master/modules/programs/msmtp.nix

Let's:
- [x] ~~Add a NixOS module for msmtp.~~ __Done in #105831__

We should probably also:
- [ ] Remove the ssmtp NixOS module and add migration instructions to the release notes (https://github.com/NixOS/nixpkgs/pull/167051)
- [ ] Remove the ssmtp package (https://github.com/NixOS/nixpkgs/pull/167051)

**Comment by Videl** [comment]
The https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/msmtp.nix module works really well.
Thanks for the module @pacien.
