### ISSUE TITLE
virtualbox-modules is marked as broken

### ISSUE THREAD

**Issue by AJChapman** [NixOS/nixpkgs#105762]
**Describe the bug**
NixOS 20.09 fails to build when configured as a VirtualBox host. The error message is:

```
Package ‘virtualbox-modules-6.1.16-5.9.11’ in /nix/store/n1l85sxys8yqackp207pj6ra7vmsrga9-nixos-20.09.2122.2fbcd0b9df9/nixos/pkgs/os-specific/linux/virtualbox/default.nix:20 is marked as broken, refusing to evaluate.
```

**To Reproduce**
Using the latest 20.09, add these lines to configuration.nix:

```
  virtualisation.virtualbox.host = {
      enable = true;
      enableExtensionPack = true;
  };
  users.extraGroups.vboxusers.members = [ "my-username" ];
```

Then run `sudo nixos-rebuild switch`.

**Expected behavior**
The rebuild should succeed, installing VirtualBox.

**Additional context**
This was working before I upgraded to 20.09. I can't track down where the package is marked as broken. It isn't in pkgs/os-specific/linux/virtualbox/default.nix, or in pkgs/applications/virtualization/virtualbox/. Once I set `allowBroken = true;` it compiles and runs fine, so it doesn't really seem to be broken.

**Notify maintainers**

@svanderburg, @ma27, @flokli, @domenkozar.

**Metadata**
```
λ ~/ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.11, NixOS, 20.09.2101.2335e7354f8 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2122.2fbcd0b9df9, nixos-unstable-21.03pre255600.24eb3f87fc6"`
 - channels(my-username): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by LutzCle** [comment]
This seems to be a duplicate of issue https://github.com/NixOS/nixpkgs/issues/101823, which was fixed by PR https://github.com/NixOS/nixpkgs/pull/101493. I'd also appreciate a backport of the fix to 20.09.

**Comment by thiagokokada** [comment]
I am also seeing the same problem and I am not even using the extension pack, so the issue seems to be different from #101823.

**Comment by musteresel** [comment]
Seeing the same problem; not using extension pack.  Can we hope for a backport?

**Comment by bryanasdev000** [comment]
> Seeing the same problem; not using extension pack. Can we hope for a backport?

Need to be merged: https://github.com/NixOS/nixpkgs/pull/107421
