### ISSUE TITLE
goldendict segfault

### ISSUE THREAD

**Issue by f0086** [NixOS/nixpkgs#105872]
**Describe the bug**
```
$ goldendict 
No favorities file found
Load done
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
getResource: gdlookup://localhost?word=Welcome!&group=4294967295
scheme: gdlookup
host: localhost
In-place finish.
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
Segmentation fault (core dumped)
$ 
```

**To Reproduce**
1. install goldendict
2. reboot the system
3. start goldendict

**Expected behavior**
goldendict runs without a segfault.

**Notify maintainers**
@gebner @astsmtl @sikmir 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.03.3316.0f8a31b992b (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3316.0f8a31b992b, nixos-hardware"`
 - channels(aaron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by f0086** [comment]
Problem still exists

**Comment by sikmir** [comment]
> Problem still exists

@f0086 Please, provide core dump or at least backtrace, without it there is no way to figure out what is going wrong.

**Comment by f0086** [comment]
The problem magically disappear.
I close it.
