### ISSUE TITLE
Install from live cd media

### ISSUE THREAD

**Issue by duane** [NixOS/nixpkgs#105838]
## Issue description

I'm trying to install in a place with inconsistent/no internet. I would like to be able to read the packages from the live cd medium—I downloaded the "plasma" live cd because I thought it came with the packages to install KDE.

### Steps to reproduce

Unplug modem & attempt to install nixos from the "plasma" live cd.

**Comment by duane** [comment]
On an additional note, there are many good reasons to be able to point the package resolver at a local resource rather than a hard-coded remote one, notably caching of packages for local distribution.

**Comment by kisik21** [comment]
Actually, NixOS does use the Live media as a substituter when installing. If the install cannot be performed with a Live image, this means that the image lacks a component in /nix/store needed for your system to be realised.

I would actually expect that a basic NixOS configuration as generated by `nixos-generate-config` on a graphical ISO would be able to be built without relying on cache.nixos.org. Can you provide your `configuration.nix` here? I'd like to take a look at what you expected to install on your system.

By the way, did you know that while building the ISO with Nix you can declare an option `system.extraDependencies` to include additional packages in the image? They would get used if they're needed while installing your shiny new system :sparkles:

**Comment by kisik21** [comment]
Another issue could be different version of Nixpkgs - to increase your chances of successfully substituting all packages from the Live media, you need to use the same Nixpkgs version that was used to build the media (hint: `nixos-version --revision` will show you the Git revision that was used in producing the system you're running, this should work on a Live ISO too)

**Comment by jonringer** [comment]
Likely what's happening is there's a few packages being added to your configuration unintentionally. And thus nix will try to fetch them.

There's also the `isoImage.includeSystemBuildDependencies` option if you want to make your own iso, it will dramatically inflate the size of the iso as you're downloading all of the build dependencies as well.

**Comment by jonringer** [comment]
I would create your own iso, following https://nixos.wiki/wiki/Creating_a_NixOS_live_CD:

iso-config.nix:
```
{config, pkgs, ...}:
{
  import = [
    <nixos/modules/installer/cd-dvd/installation-cd-graphical-plasma5.nix>
  ];

  # Rest of your final configuration
  ....
}
```
then build the image with:
```
nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso-config.nix
```

that should create an iso image with all of your desired packages already on it

**Comment by duane** [comment]
Alright, this certainly doesn't need to be an open issue. However, I would have definitely downloaded a no-network install iso had it been available, so I'm just registering interest in this use case.
