### ISSUE TITLE
ImHex package request

### ISSUE THREAD

**Issue by Stupremee** [NixOS/nixpkgs#105997]
**Project description**
[ImHex](https://github.com/WerWolv/ImHex) describes itselfs as a " ... [h]ex Editor for Reverse Engineers, Programmers and people that value their eye sight when working at 3 AM."

**Metadata**

* homepage URL: https://github.com/WerWolv/ImHex
* source URL: https://github.com/WerWolv/ImHex
* license: gpl2
* platforms: Linux and Windows (mingw).

I would also like to self-assign this

**Comment by jonringer** [comment]
This will likely have to wait for #89793:
> You need a C++20 compatible compiler such as GCC 10.2.0 to compile ImHex

**Comment by Stupremee** [comment]
Right now I came across this problem :sweat_smile:

**Comment by Stupremee** [comment]
This will be implemented in #106576
