### ISSUE TITLE
flash plugin via PPAPI -> NPAPI: how should I add this package?

### ISSUE THREAD

**Issue by Axiomatic-** [NixOS/nixpkgs#10591]
The package is [freshplayerplugin](https://github.com/i-rinat/freshplayerplugin/).

I have a working .nix [here](https://github.com/Axiomatic-/nixpkgs/blob/master/pkgs/applications/networking/browsers/mozilla-plugins/fresh-player-plugin/default.nix) for it, however it requires `libpepflashplayer.so` to actually function. 

Should my package provide `libpepflashplayer.so` or should the user have to download the file, and specify where to find it via `~/.config/freshwrapper.conf`?

There is a package on the Arch Linux AUR has direct links to `libpepflashplayer.so` which one can see [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-pepper-flash-standalone) so providing `libpepflashplayer.so` is not extremely hard.

**Comment by vcunat** [comment]
This is interesting in connection with Firefox (and everyone else) [phasing out NPAPI](https://blog.mozilla.org/futurereleases/2015/10/08/npapi-plugins-in-firefox/) around the end of 2016 (and not intending to support PPAPI). They claim that flash will still be supported, but it's unclear if *this* way of getting flash will be.

In chromium I see a plugin derivation that can build flash and widevine. That can be used completely without chromium (it just uses the src). We currently build the plugins at once, but we might better build each separately to improve sharing, I believe.

**Comment by vcunat** [comment]
Oh, I see the plugins are in separate outputs already. Therefore, after applying
```diff
diff --git a/pkgs/applications/networking/browsers/chromium/default.nix b/pkgs/applications/networking/browsers/chromium/default.nix
index 9a7f4a2..d2b346f 100644
--- a/pkgs/applications/networking/browsers/chromium/default.nix
+++ b/pkgs/applications/networking/browsers/chromium/default.nix
@@ -90,5 +90,6 @@ in stdenv.mkDerivation {
 
   passthru = {
     mkDerivation = chromium.mkChromiumDerivation;
+    inherit (chromium) plugins;
   };
 }
```

You can just use `"${chromium.plugins.flash}/lib/libpepflashplayer.so"`.

**Comment by Axiomatic-** [comment]
So applied that patch to the chromium package. Within my own default.nix I did:
```patch
diff --git a/pkgs/applications/networking/browsers/mozilla-plugins/fresh-player-plugin/default.nix b/pkgs/applications/networking/browsers/mozilla-plugins/fresh-player-plugin/default.nix
index befca8b..897b060 100644
--- a/pkgs/applications/networking/browsers/mozilla-plugins/fresh-player-plugin/default.nix
+++ b/pkgs/applications/networking/browsers/mozilla-plugins/fresh-player-plugin/default.nix
@@ -2,6 +2,7 @@
 fetchFromGitHub, 
 alsaLib,
 cmake,
+chromium,
 openssl,
 pango,
 pkgconfig,
@@ -31,20 +32,21 @@ stdenv.mkDerivation rec {
   };
 
   buildPhase = ''
-#    "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .."
-    "make"
+    make
   '';
 
   installPhase = ''
     mkdir -p "$out/lib/mozilla/plugins"
     cp libfreshwrapper-flashplayer.so "$out/lib/mozilla/plugins"
-    
     mkdir -p "$out/share/${name}/plugin"
     ln -s "$out/lib/mozilla/plugins/libfreshwrapper-flashplayer.so" "$out/share/${name}/plugin"
+    mkdir -p "$out/lib/pepperflashplugin-nonfree"
+    ln -s "${chromium.plugins.flash}/lib/libpepflashplayer.so" "$out/lib/pepperflashplugin-nonfree"
   '';
 
   buildInputs = [
-    alsaLib cmake openssl pango pkgconfig ragel glib libevent gtk2 libXrandr libXrender libXcursor libv4l ffmpeg libva libvdpau libdrm libpulseaudio mesa
+    alsaLib cmake chromium openssl pango pkgconfig ragel glib libevent gtk2 libXrandr libXrender libXcursor libv4l ffmpeg libva libvdpau libdrm libpulseaudio mesa
   ];
 
   meta = with stdenv.lib; {
```

The issue is the plugin still cannot locate ```libpepflashplayer.so```. I am not sure why it fails to find ```libpepflashplayer.so``` I guess I am not doing something right; however, according to [```config_pepperflash.c```](https://github.com/i-rinat/freshplayerplugin/blob/master/src/config_pepperflash.c#L32) the path ```/usr/lib/pepperflashplugin-nonfree``` should be searched. So I am unsure on what I am doing wrong. Do you know perhaps?

**Comment by vcunat** [comment]
Well, the plugin is *not* in `/usr/lib/...`, so the source will have to get patched to search on a correct location.

**Comment by garbas** [comment]
@Axiomatic- did you try patching [config_pepperflash.c](https://github.com/i-rinat/freshplayerplugin/blob/master/src/config_pepperflash.c#L32)?

**Comment by Axiomatic-** [comment]
I have pushed my current work to: https://github.com/Axiomatic-/nixpkgs/tree/freshplayerplugin

Everything works except that freshplayerplugin, cannot find manifest.json, so it reports an incorrect version to gecko-like browsers. Should I open a pull request still since it still works?

**Comment by garbas** [comment]
@Axiomatic- :+1:
