### ISSUE TITLE
Unable to build darwin packages depending on SkyLight private framework on Big Sur

### ISSUE THREAD

**Issue by cmacrae** [NixOS/nixpkgs#105964]
I maintain a couple darwin packages (yabai & spacebar) that depend on `/System/Library/PrivateFrameworks/SkyLight.framework`.  
Since upgrading to Big Sur, I now see these errors when trying to build:  
```
building '/nix/store/kx8vmzgkfdqs6m5cfl5k88z0lqvrp426-yabai-3.3.5.drv'...
unpacking sources
unpacking source archive /nix/store/lzvs4dll6s0amxvdlsw37hh8p3fmzbwj-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/8r6qgv5ihwkwwa4r4ydjjb0h3hk4viwi-bash-4.4-p23/bin/bash
rm -rf ./bin
clang ./src/osax/loader.m -shared -O2 -mmacosx-version-min=10.13 -o ./src/osax/loader -framework Foundation
clang ./src/osax/payload.m -shared -fPIC -O2 -mmacosx-version-min=10.13 -o ./src/osax/payload -framework Foundation -framework Carbon
clang ./src/osax/mach_bootstrap.c -shared -fPIC -O2 -mmacosx-version-min=10.13 -o ./src/osax/mach_bootstrap -framework Carbon -lpthread
./src/osax/mach_bootstrap.c:31:5: warning: implicit declaration of function 'pthread_create_from_mach_thread' is invalid in C99 [-Wimplicit-function-declaration]
    pthread_create_from_mach_thread(&thread, NULL, &mach_load_payload, NULL);
    ^
1 warning generated.
xxd -i -a ./src/osax/loader ./src/osax/sa_loader.c
xxd -i -a ./src/osax/payload ./src/osax/sa_payload.c
xxd -i -a ./src/osax/mach_bootstrap ./src/osax/sa_mach_bootstrap.c
rm -f ./src/osax/loader
rm -f ./src/osax/payload
rm -f ./src/osax/mach_bootstrap
mkdir -p ./bin
clang src/manifest.m src/osax/sa_loader.c src/osax/sa_payload.c src/osax/sa_mach_bootstrap.c -std=c99 -Wall -g -O0 -fvisibility=hidden -mmacosx-version-min=10.13 -F/System/Library/PrivateFrameworks -framework Carbon -framework Cocoa -framework CoreServices -framework SkyLight -framework ScriptingBridge -o bin/yabai
ld: framework not found SkyLight
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [makefile:59: bin/yabai] Error 1
builder for '/nix/store/kx8vmzgkfdqs6m5cfl5k88z0lqvrp426-yabai-3.3.5.drv' failed with exit code 2
error: build of '/nix/store/kx8vmzgkfdqs6m5cfl5k88z0lqvrp426-yabai-3.3.5.drv' failed
```

**To Reproduce**
`nix-build -A yabai`

**Expected behavior**
The package builds successfully.

**Additional context**
I've been trying to understand what's changed and how I can fix this. Despite maintaining 2 darwin packages, I'll admit my knowledge of the build toolchain is limited. I've been digging around nixpkgs and looking at things like `__propagatedImpureHostDeps` and trying a few things out, but I've had no luck yet. I can see SkyLight is here on my system: `/System/Library/PrivateFrameworks/SkyLight.framework`, I just can't work out how to expose that in the build.

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.9`
 - channels(cmacrae): `"darwin, nixpkgs-21.03pre255633.c00959877fb"`
 - nixpkgs: `/Users/cmacrae/.nix-defexpr/channels/nixpkgs`

**Comment by cmacrae** [comment]
cc @LnL7 @matthewbauer 

Hope you guys don't mind the tag. I'd really appreciate some help understanding how this works and how to fix it

**Comment by LnL7** [comment]
The actual libraries of frameworks are no longer present on macOS 11.0 so linking against `/System/Library` directly doesn't work anymore. As a replacement tbd metadata files are used for linking now, you can find the definitions we generated for 10.12 here https://github.com/NixOS/darwin-stubs.

I suspect that either this is a framework not present on 10.12, which means we don't have a stub for it. Or it's not included in the generation scripts (see https://github.com/NixOS/darwin-stubs/pull/2).

**Comment by cmacrae** [comment]
Thanks for taking the time to explain @LnL7 👍 I'll check that out and close this off

**Comment by moinessim** [comment]
Hi @cmacrae , I tried to install yabai with nixpkgs in macos Big Sur and ran into this same issue.
Did you manage to install it?

Tried generating the stubs for SkyLight, with https://github.com/NixOS/darwin-stubs
, but it says "Framework 'SkyLight' does not have a library to stub"
I believe the framework exists in my machine, since these folders are present:
```
/System/Library/PrivateFrameworks/SkyLight.framework/
├── Resources -> Versions/Current/Resources
└── Versions
    ├── A
    │   ├── Resources
    │   │   ├── AquaAppearanceHelper.app
    │   │   │   └── Contents
    │   │   │       ├── Info.plist
    │   │   │       ├── MacOS
    │   │   │       │   └── AquaAppearanceHelper
    │   │   │       ├── PkgInfo
    │   │   │       ├── Resources
    │   │   │       ├── _CodeSignature
    │   │   │       │   └── CodeResources
    │   │   │       └── version.plist
    │   │   ├── Configuration.plist
    │   │   ├── CursorAsset
    │   │   ├── CursorAsset_base
    │   │   ├── Info.plist
    │   │   ├── SkyLightShaders.air64.metallib
    │   │   ├── WSInfo
    │   │   ├── WindowServer
    │   │   └── version.plist
    │   └── _CodeSignature
    │       └── CodeResources
    └── Current -> A
```

Thanks!

**Comment by cmacrae** [comment]
@moinessim I submitted a fix for providing SkyLight framework outputs to nixpkgs a while back: https://github.com/NixOS/nixpkgs/pull/117780

So, they are being generated. The absence of SkyLight outputs is not the issue here - yabai uses symbols not available in nixpkgs apple-sdk version.  

See this comment for some more context:
https://github.com/NixOS/nixpkgs/pull/108861#issuecomment-832110467

If you look at the comments above, there's a provided overlay to grab the binary as a workaround, if you want to run more recent versions of yabai

**Comment by moinessim** [comment]
Thanks @cmacrae , I was able to install yabai with the overlay found in the comment.
