### ISSUE TITLE
Remove the custom Plasma session script

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#105942]
The custom Plasma [session script](https://github.com/NixOS/nixpkgs/blob/0cc6e0a4106f3fc1cc0b765ab0f17b697c3d910d/nixos/modules/services/x11/desktop-managers/plasma5.nix#L195) must be removed so that the display manager will use the `.desktop` files instead. This is necessary to support Plasma on Wayland. It would also fix a bug where Plasma can be loaded with an unsupported window manager. The steps that currently run in the session script must still run at start-up; we should look at what Gnome does here.

**Comment by berbiche** [comment]
Still relevant I think

**Comment by Artturin** [comment]
Looks fixed now
