### ISSUE TITLE
Package tools for dealing with signal backups

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#106038]
https://old.reddit.com/r/signal/wiki/faq#wiki_can_i_export_my_past_sms_messages_from_signal.3F recommends the following two tools for exporting data from a signal backup:
- https://github.com/pajowu/signal-backup-decode
- https://github.com/bepaald/signalbackup-tools

**Comment by deliciouslytyped** [comment]
@deviant you mentioned that you'Ve packaged these already?

**Comment by deviant** [comment]
I had a look, but could only find package skeletons. It appears that I ended up building them outside of Nix.

**Comment by malob** [comment]
Resolved by: #150763.
