### ISSUE TITLE
Default kernel hard-locks on unstable

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#10607]
At least three people have reported hard-locks with the default kernel on unstable.

Symptoms are:

* System hard-locks (no response to local or remote input) after a few hours, regardless of load
* System may spontaneously power-off under heavy load
* System experiences data loss up to several hours prior to the lockup
* System may be a physical machine or a KVM client

The problem does not occur on systems using kernel 4.2, so the suggested workaround is to put
```
boot.kernelPackages = pkgs.linuxPackages_4_2;
```
in `/etc/nixos/configuration.nix`. We should upgrade the default kernel on unstable as soon as possible.

**Comment by vcunat** [comment]
Was that all with 4.1.10 then? There's 4.1.11 on kernel.org (for a few days already).

**Comment by ttuegel** [comment]
Yes, all the lockups have been with kernel 4.1.10.

**Comment by wizeman** [comment]
Just as another data point, I had hard lock ups with 4.1.10 on real machines too (although I simply reverted back to 3.8).

**Comment by cleverca22** [comment]
i had similar problems and was able to get the console to stay on during a crash, it said something about a hung task, the key to debuging it was to "setterm -blank 0 -powerdown 0" from the console, so the tty would stay on even after it froze up

i was also doing hardware changes at the time, so i wasn't sure if it was the software or hardware though

**Comment by domenkozar** [comment]
We can't upgrade since we have a policy to always use latest long-term kernel. So either this is going to be fixed upstream (and backported to our kernel) or we should downgrade to 3.18.

**Comment by ttuegel** [comment]
@cleverca22 I could not get to a console any of the times this happened, and it was going on every few hours for almost a week before I could work around it.

@domenkozar I think this issue is fixed in 4.1.11; there is a patch backported from 4.2 for a deadlock issue that sounds like this one.

**Comment by cleverca22** [comment]
my console problem, is that the powersave kicked in and blanked, and then it wasnt responding enough to come back on, disabling power-save locked it on, so the printk's went to the screen and stayed there as it died

**Comment by ttuegel** [comment]
Has anyone tried 4.1.12, which is in unstable now?

**Comment by vcunat** [comment]
Note: it's not in the channel yet and it's 4.1.11 (which is ~4 days old ATM). I use 4.1.11 on one machine since I pushed that update &ndash; no problems but I've had none even before. Upstream released 4.1.12 yesterday, but we don't have that in master yet.

**Comment by domenkozar** [comment]
Actually we do https://github.com/NixOS/nixpkgs/commit/658d7b285b8dc0597e8fbac2019d63ac56738640

**Comment by vcunat** [comment]
Oh, I've missed that one when searching, thanks.

**Comment by ttuegel** [comment]
This appears to be fixed now.
