### ISSUE TITLE
LightDM Background Cannot Be Set to a Colour

### ISSUE THREAD

**Issue by alex-giusi-tiri** [NixOS/nixpkgs#106109]
Hello!

I was trying to set the lightdm background to a colour, for example:
`services.xserver.displayManager.lightdm.background = "#7F7F7F";`
But, because its type is a path, it would not work.
It works with a local nixpkgs(-20.03) repository, having the type set to string.

I found the issue https://github.com/NixOS/nixpkgs/issues/12684 to be relevant;
it was fixed in commitment https://github.com/NixOS/nixpkgs/commit/ab2db6239d47a174fb3e84065c30bcb6a19cc4fc, but at some point, in one of the commitments https://github.com/NixOS/nixpkgs/commit/20bfce5060361d86fffe8b2f4d09564c5b5aa6e5 or https://github.com/NixOS/nixpkgs/commit/3d1706c28df08ca09e9502ef9e17322ea71a70a4, it was changed back to path.
Why? Could we have the type to be a string?

Thank you!
Best regards!

**Metadata**
`nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2152.e34208e1003 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2152.e34208e1003"`
 - channels(alex): `"nixos-20.03.2349.6460602eec5ced5b9720f4d9fdb0dd717b89b4fd-cust.tar.xz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
was fixed in https://github.com/NixOS/nixpkgs/commit/8e3d255347f7c9d28390563d1830da89af7ef867

**Comment by alex-giusi-tiri** [comment]
Thanks for fixing it!
I think that the letters [A-Fa-f] are missing, though.
I investigated a little further, and I found that all of these work as expected, too; upper- and lower-case letters in the #RGB format, but also color names, for example:
`"blue"` `"green"` `"yElLoW"` `"#AbCdEf"`.
I would say that it would be simpler to have a string type, which would allow all of what upstream would allow as value themselves, withouth much need for keeping the nix definition up-to-date with upstream (not necessarily that it would change often), without the need to explicitly list the all values themselves. Or, maybe it is achievable (with a rule set (strMatching)?); I'm not sure.
What do you think?
Thanks!
