### ISSUE TITLE
vim-nox is too old

### ISSUE THREAD

**Issue by zhou13** [NixOS/nixpkgs#10618]
I think vim-nox stands for vim no X.  But it still install gvim for me.  In addition, vim-nox is still in 7.3 rather than 7.4

I think vim-nox should be a vim with all the feature except the gui part. But it seems to be out of maintenance.  Now I cannot find a vim with python support on NixOS for my server.

**Comment by jagajaga** [comment]
Try `vimHugeX`. It provides python support (but with gui). But you can surely use it on a server.

**Comment by zhou13** [comment]
That helps.  Thanks.  But it pulls in all the gui dependency, and I need to compiles all of the gtk dependency as I am using nix in my home directory.

**Comment by matthiasbeyer** [comment]
@zhou13 I guess you can try `vim_configurable` and disable GUI there.

**Comment by jgillich** [comment]
Regular vim doesn't install gvim, however:
```
The program ‘gvim’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.vimHugeX
  nix-env -iA nixos.vimNox
```

So maybe it doesn't stand for `no x` after all. :confused:

**Comment by zhou13** [comment]
If the naming convension is as same as ubuntu in vim-nox, then I think there is something wrong here. We have the following from [1]:
````
  Many new features have been added: multi level undo, syntax
 highlighting, command line history, on-line help, filename
 completion, block operations, folding, Unicode support, etc.
 .
 This package contains a version of vim compiled with support for
 scripting with Lua, Perl, Python, Ruby, and Tcl but no GUI.
````

Furthermore, I do think think `vim_configurable` can be  configured to disable GUI as the GUI dependency is hard coded.

[1] https://launchpad.net/ubuntu/trusty/+package/vim-nox

**Comment by joachifm** [comment]
Please submit a PR
