### ISSUE TITLE
bundlerEnv hooks

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10617]
How can I add to `bundlerEnv`-based derivation hooks such as `shellHook` like in `mkDerivation`?
In case if I use `bundlerEnv` as a separate environment and put it into `buildInputs` in `mkDerivation`, I got error

```
installing
cp: cannot create regular file 'gems/bundler-1.7.9.gem': Permission denied
```

**Comment by Profpatsch** [comment]
(triage) sorry for the silence, still a problem?
