### ISSUE TITLE
Steam Witcher 2 fails because of gdk-pixbuf for wrong architecture.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#106119]
**Describe the bug**

The Witcher 2 under steam aborts due to an image loading error.

**To Reproduce**
1. Install Witcher 2 on steam.
2. Hit play

**Expected behavior**

The game plays.

**Additional context**

steam's stdout indicates that this is an image loading issue and appears to be architecture related. Witcher 2 is a 32 bit game but tries to load the 64 bit loader library:

```
>>> Adding process 261 for game ID 20920
pixbufFromFile() failed loading linux/launcher/Neutral/bkg.png - Unable to load image-loading module: /nix/store/f8nh02yh7j7q5vkgq48zniblk51kpr6y-gdk-pixbuf-2.40.0/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /nix/store/f8nh02yh7j7q5vkgq48zniblk51kpr6y-gdk-pixbuf-2.40.0/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: wrong ELF class: ELFCLASS64
desktop-launcher: /mnt/Storage/Development/Projects/deployment/witcher2-linux/desktop-launcher/main.cpp:132: void launcherUi::init(const char*): Assertion `m_img_background' failed.
GameAction [AppID 20920, ActionID 1] : LaunchApp changed task to Completed with ""
>>> Adding process 262 for game ID 20920
>>> Adding process 263 for game ID 20920
./saferun.sh: line 21:   263 Aborted                 (core dumped) "${EXEC}" "$@"
Game removed: AppID 20920 "", ProcID 260 
Uploaded AppInterfaceStats to Steam
Exiting app 20920
```

**Notify maintainers** @jagajaga

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.80, NixOS, 21.03pre255513.8ee7c2505f9 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(kevincox): `""`
 - channels(root): `"nixos-21.03pre255513.8ee7c2505f9, nixpkgs-21.03pre255543.752b6a95db9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module:
```

**Comment by ThibaultLemaire** [comment]
Have you tried this by any chance: https://github.com/NixOS/nixpkgs/issues/106503#issuecomment-743711583 ?

Judging by the creation time and 32bit compatibility being involved, I think it may be the same issue.

**Comment by kevincox** [comment]
It didn't fix the issue for me. This doesn't seem related to GL, it seems to be a library that is not working.

**Comment by kevincox** [comment]
I installed again and booted it up and it appears to be working. Haven't actually played but I'll close this until we have evidence that it is broken.
