### ISSUE TITLE
wireplumber

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#106128]
**Project description**
https://gitlab.freedesktop.org/pipewire/wireplumber

"Session / policy manager implementation for PipeWire"

## I have a WIP for this.

It's blocked on these two things:
* https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/20 (wireplumber build issue)
* https://github.com/skystrife/cpptoml/pull/124 (PR so that cpptoml outputs pkg-config files)

* WIP `wireplumber`: https://github.com/colemickens/nixcfg/blob/e552bb209e9fc9e09e71ba1ca7f5067cb5a010fc/pkgs/wireplumber/default.nix
* WIP `cpptoml`: https://github.com/colemickens/nixcfg/blob/e552bb209e9fc9e09e71ba1ca7f5067cb5a010fc/pkgs/cpptoml/default.nix

**Metadata**

* homepage URL: https://gitlab.freedesktop.org/pipewire/wireplumber
* source URL: https://gitlab.freedesktop.org/pipewire/wireplumber
* license: MIT
* platforms: linux

**Comment by eadwu** [comment]
Is it even necessary? I don't think I saw any differences when compared to pipewire's internal session manager. At least back when I used wireplumber, it was at least more stable but compared to the current internal manager it's far worse.

Last I checked, I couldn't even manage to get bluetooth working in wireplumber (2020-10-22).

**Comment by colemickens** [comment]
>pipewire's internal session manager

ah, pardon my ignorance, but I don't know what this is and when I google that phrase I just find `wireplumber` (I'll keep looking).

It's entirely possible this isn't needed or is redundant, I just don't really know. I was just looking for something to visually wire up sources and sinks, which I thought was possible with pipewire.

**Comment by colemickens** [comment]
Found this: https://blogs.gnome.org/uraeus/category/pipewire/

>Currently this is a simple sample session manager that Wim created himself, but we also have a more advanced session manager called Wireplumber being developed by Collabora, which they developed for use in automotive Linux usecases, but which we will probably be moving to over time also for the desktop.

**Comment by eadwu** [comment]
The internal session manager is just referring to `pipewire-media-session` if I haven't remembered incorrectly.

You're looking for JACK utilities, I don't think wireplumber provides a GUI either.

**Comment by colemickens** [comment]
I packed this anyway and have it building, I'll send it at some point, until then it's here: https://github.com/colemickens/nixcfg/blob/689413b38a596f9ac88984f4d797ef6cc8a29285/pkgs/wireplumber/default.nix

In the meantime, and related to @eadwu's hint, now that JACK-y things seem to be working better, I can indeed do some visual input/output routing in `qjackctl`.

**Comment by minijackson** [comment]
For those like me who were confused about the difference between WirePlumber and the default pipewire-media-session: 

> PipeWire upstream has a very limited example session manager. It serves as a good example for building new ones and has some functionality there for basic desktop use cases and testing, but it goes no further than that. WirePlumber serves as a replacement for this example and additionally provides a framework for building custom session managers.
> 
> The main goal of WirePlumber as a session manager is obviously to watch for streams from applications and make sure that they get linked to the appropriate device or peer application according to the rules of the use case that it implements.

[Source](https://www.collabora.com/news-and-blog/blog/2020/05/07/wireplumber-the-pipewire-session-manager/)

I think it is still desirable to have this packaged in nixpkgs in the long term, although I personally have no use for it right now (just very curious).

**Comment by jansol** [comment]
When this gets packaged it should be integrated in the pipewire NixOS module alongside the current pipewire-media-session. Haven't bothered looking into it yet since there hasn't been a release in ages and I'm fairly sure the previous release doesn't work with the current pipewire.

And it is definitely desirable to package this, since wireplumber supports scripting for smart automatic routing in fancier setups that aren't served sufficiently with only a single default card for input and output respectively. So essentially everyone who would use the pro audio profile on their main soundcard.

Checking on the releases page, looks like there is a 0.4.0 release coming up soon. I'll look into it once that lands (unless someone beats me to it)..

**Comment by GabTheBab** [comment]
It seems 0.4.0 is here and highly compatible with the current pipewire versions, could be a good time to check this issue out again.

**Comment by jakobrs** [comment]
I have something that works [here](https://github.com/jakobrs/nur-packages/blob/master/pkgs/wireplumber/default.nix). I have a few notes:

- By default, it will use `$out/etc/wireplumber` as its "config dir", `$out/share/wireplumber` as its "data dir" and `$out/lib/wireplumber-0.4` as its "module dir". These can be overridden using the `WIREPLUMBER_CONFIG_DIR`, `WIREPLUMBER_DATA_DIR` and `WIREPLUMBER_MODULE_DIR` environment variables. I think we can leave the defaults as-is, and override these variables in the systemd unit. This would allow one to run `./result/bin/wireplumber` without setting anything up and have it use the default configuration.
- `/etc/wireplumber` contains four `.conf` files, but these are separate example configurations (they don't depend on each other)
- List of environment variables that change the behaviour of WirePlumber
  - `WIREPLUMBER_DEBUG` (debug level, default is `2` and can be changed in the configuration file)
  - `WIREPLUMBER_NO_PW_LOG` (Don't replace PipeWire's logging system with WirePlumber's (I think))
  - `WIREPLUMBER_MODULE_DIR` (sets module directory, used for searching for modules)
  - `WIREPLUMBER_CONFIG_DIR` (sets config directory, used for loading configuration files *and* scripts (in `scripts` subdirectory)
  - `WIREPLUMBER_DATA_DIR` (sets data directory, also used for finding scripts (in `scripts` subdirectory) (if `$WIREPLUMBER_CONFIG_DIR/scripts` didn't contain the file), but nothing else.
  - `WPIPC_DEBUG` (wpipc debug level)
    - I'm guessing wpipc is a wireplumber inter-process communication thing
  - wpipc sets a variable called `runtime_dir` to the first one of these that exists:
    - `PIPEWIRE_RUNTIME_DIR`
    - `XDG_RUNTIME_DIR`
    - `HOME`
    - `USERPROFILE`
    - There's a fifth case that I don't understand but it looks like it's reading the runtime directory from a socket

I can create a pull request if someone else wants to be the maintainer.

**Comment by jakobrs** [comment]
If anyone wants to try out WirePlumber, the steps are as below:

1. Build the WirePlumber package
2. Copy the `etc` and `share` directories to somewhere writable: `cp result/etc result/share ./ -r`
   - You can alternatively copy `result/etc/wireplumber` and `result/share/wireplumber` into somewhere you can write to, you don't need to copy the entire `etc` directory
3. Make the new `etc` and `share` directories writable using chmod: `chmod 755 ./etc ./share -R`
4. Set the config and data dirs: `export WIREPLUMBER_CONFIG_DIR="$PWD/etc/wireplumber" WIREPLUMBER_DATA_DIR="$PWD/share/wireplumber"`
5. Stop pipewire-media-session: `systemctl stop --user pipewire-media-session`
6. Launch WirePlumber: `result/bin/wireplumber [-c configfile]`
   - Default configfile is `$WIREPLUMBER_CONFIG_DIR/wireplumber.conf`

You don't need to modify any existing PipeWire configuration to try out WirePlumber.

You can then e.g. try changing the volume with `result/bin/wpctl` or launching scripts with `result/bin/wpexec`.

**Comment by jakobrs** [comment]
There's a new release of WirePlumber, version 1.4.2. I've updated my nur package [here](https://github.com/jakobrs/nur-packages/blob/master/pkgs/wireplumber/default.nix).

**Comment by arcnmx** [comment]
fwiw I just migrated from pipewire-media-session to wireplumber by [writing a module](https://github.com/arcnmx/nixexprs/blob/master/modules/nixos/wireplumber.nix). It was a little complicated by the fact that the only way to configure wireplumber right now is to write lua scripts that generate the desired configuration json data (lua is used purely as a preprocessor so is kind of unnecessary, but is also the only way to pass data to it), so I had to include a nix attrs toLuaTable serializer.

**Comment by bryanasdev000** [comment]
Related to https://github.com/NixOS/nixpkgs/issues/102547

**Comment by legendofmiracles** [comment]
https://github.com/NixOS/nixpkgs/pull/150548 would package a bare-bones wireplumber, although the service is a bit lacking in terms of configuration.

**Comment by devhell** [comment]
So this can be closed since #150548 has been merged?

**Comment by jansol** [comment]
Good question. The package is there but it can't really be configured via the nixos module yet.

**Comment by thiagokokada** [comment]
Wireplumber is ready and it is even the default already (https://github.com/NixOS/nixpkgs/pull/159546), so I am closing this issue.
