### ISSUE TITLE
Missing menu entry to launch kicad

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#106295]
**Describe the bug**
`kicad` is missing a menu entry to launch the application.

**To Reproduce**
1. Install `kicad`

**Expected behavior**
There should be a menu entry to launch the application.

**Notify maintainers**

@evils @bgamari

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257339.83cbad92d73 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by evils** [comment]
see #104381 (probably shouldn't have been closed)
