### ISSUE TITLE
Monica

### ISSUE THREAD

**Issue by wangkev** [NixOS/nixpkgs#106354]
**Project description**
Personal CRM. Remember everything about your friends, family and business relationships.

**Metadata**

* homepage URL: https://www.monicahq.com/
* source URL: https://github.com/monicahq/monica
* license: agpl3
* platforms: unix, linux, darwin

**Comment by AndersonTorres** [comment]
This evokes me a question:

How to package those webapps?

**Comment by bryanasdev000** [comment]
> This evokes me a question:
> 
> How to package those webapps?

Take a look at:

- https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/web-apps/wallabag/default.nix#L28
- https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/nextcloud/default.nix

I think the magic is modules and its relation to a web server.

**Comment by rembo10** [comment]
@wangkev not sure if you're still interested but I submitted a draft PR which adds monica. Seems ok so far, but definitely keep backups of any important data

**Comment by elikoga** [comment]
Commenting for self note

**Comment by AkechiShiro** [comment]
This should be closed because this https://github.com/NixOS/nixpkgs/pull/224212 is Monica packaged I believe.
And this draft PR may not be useful anymore #162775 since Monica version 4.0 is actually packaged.
