### ISSUE TITLE
coin3d 4.0.0 no longer builds on nixos-unstable

### ISSUE THREAD

**Issue by kneitinger** [NixOS/nixpkgs#106329]
**Describe the bug**
When installing the [`coin3d` package](https://github.com/NixOS/nixpkgs/blob/83cbad92d73216bb0d9187c56cce0b91f9121d5a/pkgs/development/libraries/coin3d/default.nix), the build fails with error:
```
<PRIOR OUTPUT OMITTED>
-- Performing Test HAVE_HASH_QUOTING - Success
-- Performing Test DISABLE_WARNING_TAUTOLOGCOMPARE
-- Performing Test DISABLE_WARNING_TAUTOLOGCOMPARE - Success
-- Configuring done
CMake Error: install(EXPORT "Coin" ...) includes target "Coin" more than once in the export set.
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_POLICY_DEFAULT_CMP0025


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**To Reproduce**
1. Use `nixos-unstable` channel
2. `nix-shell -p pkgs.coin3d`, or any other method of build/installation

**Expected behavior**
`coin3d` can be installed explicitly or as a dependency.

**Additional context**
I encountered this issue while attempting to install `freecad`.  Curiously, I had installed `freecad` last week with no issues, and neither `coin3d` nor `freecad` have been modified since late September and October, respectively.

**Notify maintainers**
@gebner @viric 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257339.83cbad92d73 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(leaf): `""`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
related: https://github.com/awslabs/aws-c-common/issues/734

**Comment by jonringer** [comment]
we should probably patch in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5556
