### ISSUE TITLE
ExecStartPre can only be overridden, not modified

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#106307]
**Describe the bug**
I can't append a command to an existing `ExecStartPre`, if the existing one is configured using `systemd.services.<name>.preStart`. See https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/systemd.nix#L264-L267

This is a problem because I would like to customize the pre-start script for `nginx`. According to [this page](https://www.freedesktop.org/software/systemd/man/systemd.service.html#id-1.8.3.6.2.4) it's possible to run individual scripts in a systemd service with heightened privileges. In this case, I want to ensure that a certificate file is chowned to the nginx user.

**To Reproduce**
1. `services.nginx.enable = true;`
2. `systemd.services.nginx.serviceConfig.ExecStartPre = "/bin/bash -c 'echo Hello, world'"`

**Comment by doronbehar** [comment]
See https://unix.stackexchange.com/a/500267/135796 . In Nix I'd guess that you should set it to `null`? or an empty string?

**Comment by aanderse** [comment]
I'm like 99% sure @roberth fixed this 👍

**Comment by roberth** [comment]
That is correct. Nowadays, `preStart` sets `serviceConfig.ExecStartPre` to a list value, which is merged according to the usual rules (`lib.mkBefore`, etc). If you need to replace all `ExecStartPre`s you can use `lib.mkForce`.
If you use a string instead of a list of strings, I believe merging may error out.

**Comment by dz0ny** [comment]
One example in case you need to override a list with a string
```
    systemd.services.haproxy.serviceConfig.ExecStartPre = lib.mkBefore [
      "/run/current-system/systemd/bin/systemctl start haproxy-update-blocklist"
    ];

```
correctly produces 
```
ExecStartPre={ path=/run/current-system/systemd/bin/systemctl ; argv[]=/run/current-system/systemd/bin/systemctl start haproxy-up>
ExecStartPre={ path=/nix/store/y41s1vcn0irn9ahn9wh62yx2cygs7qjj-coreutils-8.32/bin/ln ; argv[]=/nix/store/y41s1vcn0irn9ahn9wh62yx>
ExecStartPre={ path=/run/haproxy/haproxy ; argv[]=/run/haproxy/haproxy -c -f /nix/store/iiy9k1r69rl1wv1c577lx55iaf3aqj22-haproxy.>
```
