### ISSUE TITLE
BAP fails to evaluate

### ISSUE THREAD

**Issue by Pamplemousse** [NixOS/nixpkgs#106365]
**Describe the bug**

`ocamlPackages.bap` fails to evaluate.

**To Reproduce**

```
nix-shell -p ocamlPackages.bap
warning: unknown setting 'extra-sandbox-paths'
error: --- ThrownError ----------------------------------------------------------------------------------------------------------------------------- nix-shell
BAP needs core_kernel-0.12 (hence OCaml 4.07)
(use '--show-trace' to show detailed location information)
```

**Notify maintainers**

Poke @maurer, @vbgl.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre251971.a371c107116 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
 - channels(pamplemousse): `"nixos-hardware"`
 - channels(root): `"nixos-21.03pre251971.a371c107116, nixos-hardware"`
 - nixpkgs: `/home/pamplemousse/Workspace/tools/nixpkgs`
```

**Comment by vbgl** [comment]
This is not a build failure. This is an evaluation failure.

If you want BAP from nixpkgs, you have to use OCaml 4.07: `ocaml-ng.ocamlPackages_4_07.bap`.

**Comment by vbgl** [comment]
Notice that [latest version of BAP](https://github.com/BinaryAnalysisPlatform/bap/releases/tag/v2.2.0) works with `core_kernel` at version 0.14, which should soon be available  in `nixpkgs`, allowing to update BAP in nixpkgs and fix the evaluation (and build) of `ocamlPackages.bap`.

**Comment by Pamplemousse** [comment]
I was looking to do that, but wasn't too sure on how to update `janestreet`'s related packages...

**Comment by vbgl** [comment]
You can check whether this PR fits your needs:  #106386
