### ISSUE TITLE
micro: add syntax highlighting for nix

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/nixpkgs#106347]
## Issue description

For `nano`, we specifically grab `.nix` syntax highlighting files from somewhere. I wanted to adapt these to `micro` and patch them into our derivation as well, but the repo doesn't have a license specified, so I'm fuzzy on the details there.

### Steps to reproduce

1. Open a `.nix` file in micro

## Technical details

n/a

**Comment by Synthetica9** [comment]
Still relevant

**Comment by Schweber** [comment]
I would also like this feature

**Comment by IndeedNotJames** [comment]
`micro` added syntax highlighting for nix in June 2021, released in version [v2.0.10](https://github.com/zyedidia/micro/releases/tag/v2.0.10) (August 2021) upstream.
See https://github.com/zyedidia/micro/issues/1769, https://github.com/zyedidia/micro/pull/2024 and #132953
