### ISSUE TITLE
ocamlPackages.janeStreet 0.14.x set

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#106356]
I've been working on updating `cstruct` to 6.0.0, currently I have a few build failures caused by different versions of dependencies being propagated in `tls`. I'm pretty sure this can be fixed by updating `ppx_sexp_conv` to 0.14.1 (which uses a newer `ppxlib`).

This begs the question: Should be provide a 0.14.x `janeStreet` package set? Are there any plans towards this yet? Any possible problems?

cc @vbgl

**Comment by vbgl** [comment]
#106386 brings JaneStreet packages at version 0.14. Then it should be easier to update `cstruct`, JSoO, etc.

**Comment by sternenseemann** [comment]
That's great! I was kinda hoping someone else could do it because I'm not too familiar with the janestreet infrastructure. I'll try to test and review the PR in the next days.
