### ISSUE TITLE
hass-nabucasa doesn't build

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#106497]
**Describe the bug**
```
building '/nix/store/57mm6v0a7kmhqxn315pzbpmg86pp7lfb-python3.8-hass-nabucasa-0.37.2.drv'...

...

ERROR: Could not find a version that satisfies the requirement attrs<20.3,>=19.3 (from hass-nabucasa)
ERROR: No matching distribution found for attrs<20.3,>=19.3
```

**To Reproduce**
1. `services.home-assistant.enable = true;`

**Additional context**

**Notify maintainers**

@Scriptkiddi 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257339.83cbad92d73 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(wmertens): `"home-manager, nixpkgs-21.03pre257733.3537ea7a835"`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73, nixos-hardware"`
 - nixpkgs: `/home/wmertens/.nix-defexpr/channels/nixpkgs`

(nixos-unstable channel)

**Comment by mvnetbiz** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/106659
