### ISSUE TITLE
feedparser: removing 2.7 compat breaks calibre-py2

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#106448]
**Describe the bug**

Change fcbd213d3856a81ca53d3d2367832e3f114be58a marked the `feedparser` library as disabled for python-2.7, which makes the calibre-py2 package uninstallable.  This is disappointing to me because that is the only version available through nixpkgs which can be used with a plugin for decrypting DRM'd books (which, I should add, I have legally purchased).

It may be that the better strategy would be to bring calibre-5 into nixpkgs (which has still-beta support for the de-DRM plugin), since this is the second break of this sort in less than a week.  To that end, I've also @-ed the calibre maintainers.

**To Reproduce**

nix-env -iA calibre-py2

**Expected behavior**

The package is in nixpkgs, it should be installable.

**Additional context**

The change that caused this problem seems to be rather specious in disabling the package for python-2.7; it worked before, and perhaps it might have made sense to conditionalize *checking* the package on whether it's 2.7, but outright disabling it seems a little anti-social.

**Notify maintainers**
@domenkozar @pSub @AndersonTorres 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by marsam** [comment]
addressed by https://github.com/NixOS/nixpkgs/pull/106457
