### ISSUE TITLE
rtl-sdr only accessible as root

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#106461]
**Describe the bug**
rtl-sdr devices can only be accessed by root user

```
Using device #0 Generic RTL2832U OEM
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
```

**To Reproduce**
1. Install gqrx (or cubicsdr) and rtl-sdr (see additional context)
2. Run gqrx and choose the device

**Additional context**

* My user is in the `plugdev` group:
```
extraGroups = ["plugdev"];
```

* The DVB driver is blacklisted:
```
boot.blacklistedKernelModules = [ "dvb_usb_rtl28xxu" ];
```

* udev rules are enabled
```
services.udev.packages = [ pkgs.rtl-sdr ];
```

* The device is listed as:
```
Bus 001 Device 010: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
```

**Notify maintainers**

@etu

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257339.83cbad92d73 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(eduardosm): `""`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by markuskowa** [comment]
Does the plugdev group actually exist?
I have a `users.groups.plugdev =  {};` in my config.

**Comment by eduardosm** [comment]
> Does the plugdev group actually exist?
> I have a `users.groups.plugdev = {};` in my config.

It didn't exist, adding the group indeed fixes the issue. I thought the group would be created automatically.
