### ISSUE TITLE
nix-prefetch-github fails to install

### ISSUE THREAD

**Issue by badly-drawn-wizards** [NixOS/nixpkgs#106482]
**Describe the bug**
Cannot install nix-prefetch-github

**To Reproduce**
1. Run `nix profile install nixpkgs#nix-prefetch-github`
2. Build fails with
```
builder for '/nix/store/xqiwgavy93n96g387gp3fxbn74z0xrm3-python3.8-nix-prefetch-github-4.0.2.drv' failed with exit code 1; last 10 log lines:
  FAILED nix_prefetch_github/core/__init__.py::ISORT - isort.exceptions.Unsuppo...
  FAILED nix_prefetch_github/core/directory.py::ISORT - isort.exceptions.Unsupp...
  FAILED nix_prefetch_github/core/effects.py::ISORT - isort.exceptions.Unsuppor...
  FAILED nix_prefetch_github/core/error.py::ISORT - isort.exceptions.Unsupporte...
  FAILED nix_prefetch_github/core/hash.py::ISORT - isort.exceptions.Unsupported...
  FAILED nix_prefetch_github/core/list_remote.py::ISORT - isort.exceptions.Unsu...
  FAILED nix_prefetch_github/core/prefetch.py::ISORT - isort.exceptions.Unsuppo...
  FAILED nix_prefetch_github/core/repository.py::ISORT - isort.exceptions.Unsup...
  FAILED nix_prefetch_github/core/revision.py::ISORT - isort.exceptions.Unsuppo...
  ============================== 37 failed in 3.64s ==============================
```

**Expected behavior**
nix-prefetch-github to be installed on my user profile

**Notify maintainers**
@seppeljordan 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.4pre20201201_5a6ddb3, channels(reuben): "", channels(root): "nixos-20.03.3310.9518fac712c", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nix-prefetch-git
# a list of nixos modules affected by the problem
module:
```

**Comment by seppeljordan** [comment]
Hi @badly-drawn-wizards 

thank you for reporting.  This issue should already be addressed on the `master` branch. If you need a workaround until nixos-unstable updates, you can install the program from its own flake at https://github.com/seppeljordan/nix-prefetch-github .
