### ISSUE TITLE
eclipse internal browser cannot open https sites (TLS/SSL support not available)

### ISSUE THREAD

**Issue by ngiger** [NixOS/nixpkgs#106455]
**Describe the bug**
Does not render the desired site
![Screenshot_20201209_154157](https://user-images.githubusercontent.com/265800/101644433-74ab6780-3a35-11eb-9349-c4c84262f9d6.png)

**To Reproduce**
Start the eclipse, eg. eclipse-java-4.17
1. Open menu Window..Show View..Other
2. Enter Internal and click on "Internal Web Browser"
3. Open an URL with https, eg. https://www.google.com/

**Expected behavior**
It should display the content of the web site

**Screenshots**
It shows TLS/SSL support not available; install glib-networking
 
**Notify maintainers**
github@matt.mchenryfamily.org

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
/nix/store/rlknkw60sngvky1rkrdws0qik3scjcln-bash-interactive-4.4-p23-dev
copying path '/nix/store/rlknkw60sngvky1rkrdws0qik3scjcln-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
- system: `"x86_64-linux"`
- host os: `Linux 5.9.12, NixOS, 20.09.2161.214e71a78a9 (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.9`
- channels(niklaus): `"nixos-20.09.2152.e34208e1003"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bb010g** [comment]
This could be related to Eclipse not using `wrapGAppsHook`? #72579
