### ISSUE TITLE
psautohints: Test broken on python38, aarch64

### ISSUE THREAD

**Issue by clkamp** [NixOS/nixpkgs#106558]
**Describe the bug**
psautohints on python38, aarch64 is currently broken due to one test failing (see https://hydra.nixos.org/build/131988272).

This results in many packages not been build for aarch64, e.g. lightdm, ssdm.

Locally I override the tests, then at least also lightdm builds fine and I detected no bugs so far.

If there is any additional information needed, please tell me.

**Notify maintainers**
@sternenseemann 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem (some of them)
attribute:
 - python38Packages.psautohint
 - lightdm
 - ssdm
```

**Comment by sternenseemann** [comment]
See #106464

**Comment by sternenseemann** [comment]
See also <https://github.com/adobe-type-tools/psautohint/issues/284>.

Issue affects x86_64 as well.
