### ISSUE TITLE
python3.8-breezy-3.1.0 cannot build, blocking nix-prefetch-bzr and cabal2nix

### ISSUE THREAD

**Issue by monothink** [NixOS/nixpkgs#106504]
**Describe the bug**

```
/build/breezy-3.1.0/dist /build/breezy-3.1.0
Processing ./breezy-3.1.0-cp38-cp38-linux_x86_64.whl
ERROR: Could not find a version that satisfies the requirement patiencediff (from breezy)
ERROR: No matching distribution found for patiencediff
builder for '/nix/store/3wf38d1nidny3ds20cgb8ra3d7mjxc5d-python3.8-breezy-3.1.0.drv' failed with exit code 1
cannot build derivation '/nix/store/3ggnx4dzrcm6ra4if5cbi3facpxv046b-nix-prefetch-bzr.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/71snm9gvvl6hs689sgicvaraiili5rhq-nix-prefetch-scripts.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/zp3w23nralr68sz78fg7rf5gj4nazf4d-cabal2nix-2.15.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/zp3w23nralr68sz78fg7rf5gj4nazf4d-cabal2nix-2.15.5.drv' failed
```

**To Reproduce**

**Expected behavior**
The package builds successfully.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03pre257339.83cbad92d73 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos, nixos-unstable"`
 - channels(mono): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3.8-breezy nix-prefetch-bzr cabal2nix
# a list of nixos modules affected by the problem
module:
```

**Comment by poscat0x04** [comment]
possible dupe of https://github.com/NixOS/nixpkgs/issues/106253

**Comment by monothink** [comment]
> possible dupe of #106253

Indeed. It seems okay now.
