### ISSUE TITLE
ACME Combination of rate limit and "account not registered"

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#106565]
**Describe the bug** 

I get many errors like this while redeploying a  nixops config after upgrading to 20.09:

```
Account syd@cs-syd.eu is not registered. Use 'run' to register a new account.
```

and

```
acme: Registering account for syd@cs-syd.eu
Could not complete registration
acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/, url:

```

**To Reproduce**

Create many nginx hosts with `enableACME`.

**Expected behavior**

No rate limiting problems, I have <50 domains and only one account should be created based on `security.acme.email`.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.78, NixOS, 20.09.2016.19db3e5ea27 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixpkgs-20.09.2016.19db3e5ea27"`
 - channels(syd): `""`
 - nixpkgs: `/nix/store/g821mqxbpl2gv0l11xxzp3s1wnpqvrfk-c92939889627636e62f7c8c01d29b2a2e462f56f.tar.gz`
```

Maintainer information:
```yaml
module: nginx
```

**Comment by NorfairKing** [comment]
Related to #101981 and #101445

**Comment by NorfairKing** [comment]
I tried `mv /var/lib/acme /var/lib/acme.bak` and am still hitting account creation rate limits instead of cert registration rate limits

**Comment by NorfairKing** [comment]
CC @m1cr0man

**Comment by m1cr0man** [comment]
Yeah the account limit (of 5) persists for 24 hours or a week, I can't remember which right now. It's a real bummer that this race condition exists. I think at this point I'm going to implement some sort of lock in the service script itself as there's enough people running into bugs with account creation to ruin the experience of cert creation in 20.09+. Also the systemd mutex work might take a bit longer than anyone wants to wait.

**Comment by NorfairKing** [comment]
@m1cr0man Ah now I understand what's going wrong! Maybe you want a `.target` for the account creation, separate from the cert generation?

**Comment by m1cr0man** [comment]
> > Yeah the account limit (of 5) persists for 24 hours or a week, I can't remember which right now.
> 
> 3 hours, so not the biggest issue :)
> 
> @m1cr0man Now I understand what's going wrong! Maybe you want a `.target` for the account creation, separate from the cert generation?

Ah yes that's a lot less time 😅 . Hm and the .target is a good suggestion. I suppose it could be done. This was suggested in the past, and my problem with it was figuring out what cert to use for account creation (you can't _just_ create an account with lego, has to be done as part of cert retrieval). I could just take the first cert associated for each account. Yeah I'll try doing that this weekend :)

**Comment by m1cr0man** [comment]
@NorfairKing could you give #106857 a test please and let me know here if it resolves your issue?

**Comment by NorfairKing** [comment]
@m1cr0man I'd like to, but I already have all my certs now. Could we make a nixos test that tries to get at least 6 certs to see if that fails to run into trouble?

**Comment by m1cr0man** [comment]
I added a test in that PR which runs 3 certs, with 2 of them containing a preStart script to ensure the account data already exists. Given that it passes, I'd safely say your issue will be resolved.

**Comment by NorfairKing** [comment]
You're the best!

**Comment by ryantm** [comment]
This worked for me.

**Comment by jtojnar** [comment]
I kept getting “Account acme@xxx is not registered. Use 'run' to register a new account.” on `nixos-rebuild switch` even on e5ce05c, which includes #106857. I managed to fix it by removing `/var/lib/acme/.lego/accounts`.
