### ISSUE TITLE
safeeyes: "Saving settings to safeeyes.json" does nothing

### ISSUE THREAD

**Issue by srghma** [NixOS/nixpkgs#106539]
**Describe the bug**

the settings are not persistent

**To Reproduce**
1. `safeeyes --debug`
2. open settings dialog
3. change something
4. close
5. see

```
2020-12-10 13:07:45,877 [INFO]:[MainThread] Saving settings to safeeyes.json
2020-12-10 13:07:45,878 [INFO]:[MainThread] Disable Safe Eyes
2020-12-10 13:07:45,880 [DEBUG]:[MainThread] Stop Smart Pause plugin
2020-12-10 13:07:45,880 [INFO]:[MainThread] Stop Safe Eye core
2020-12-10 13:07:45,881 [INFO]:[WorkThread] Pre-break waiting is over
2020-12-10 13:07:45,882 [INFO]:[MainThread] Initialize SafeEyesCore with modified settings
2020-12-10 13:07:45,882 [INFO]:[MainThread] Initialize the core
2020-12-10 13:07:45,883 [INFO]:[MainThread] Initialize the break screen
```

6. open settings again
7. the settings are reset

**Expected behavior**

settings should persist

**Screenshots**

**Additional context**

**Notify maintainers**
I am

**Metadata**

```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev
copying path '/nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2190.78dc359abf8 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.3.9`
 - channels(srghma): `""`
 - channels(root): `"nixos-20.09.2190.78dc359abf8, nixpkgs-21.03pre250093.0da76dab4c2, nixpkgs-master, nixpkgs-unstable-21.03pre250093.0da76dab4c2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.safeeyes
# a list of nixos modules affected by the problem
module: services.safeeyes
```

**Comment by srghma** [comment]
temp fix `chmod -R +wrx $HOME/.config/safeeyes`

**Comment by veprbl** [comment]
> temp fix `chmod -R +wrx $HOME/.config/safeeyes`

Could be that it copies the default config from the store and preserves read-only permissions.

**Comment by srghma** [comment]
> > temp fix `chmod -R +wrx $HOME/.config/safeeyes`
> 
> Could be that it copies the default config from the store and preserves read-only permissions.

could you check https://github.com/slgobinath/SafeEyes/issues/402, what do you think about proposed solution?

**Comment by lasers** [comment]
Please revisit this again. Bump version to `2.1.1`.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/safeeyes/default.nix
Safeeyes is now at 2.1.3
