### ISSUE TITLE
ICU should not be split into several outputs

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#106567]
Right now `icu` is split to several outputs: `out` and `dev`. This breaks software that relies on icu-config to get the configuration.

The `icu-config` states that everything is located inside the same prefix:

```
# The PREFIX is the base of where ICU is installed.
# Inside this directory you should find  bin, lib, include/unicode, 
# etc.  If ICU is not installed in this directory, you must change the
# following line.  There should exist /nix/store/7flw8mxs28mk2r1wsnyas1y59j4hjr7a-icu4c-67.1-dev/include/unicode/utypes.h
# for example.
default_prefix="/nix/store/wn2hcvdk7dzc7l3f340sva6lhkbmmsgd-icu4c-67.1"
```

And other software relies on this. For example, `rust_icu`: https://github.com/google/rust_icu/blob/master/rust_icu_sys/build.rs#L431

Splitting `icu` into several outputs does not allow to build `rust_icu` on NixOS.

cc @vcunat

**Comment by paulyoung** [comment]
What's the solution here?

**Comment by vcunat** [comment]
PR https://github.com/google/rust_icu/pull/190 is linked (indirectly).
