### ISSUE TITLE
attribute 'happy_1_19_5' missing

### ISSUE THREAD

**Issue by YuMingLiao** [NixOS/nixpkgs#106660]
**Describe the bug**
error: attribute 'happy_1_19_5' missing, at /nix/store/pk0rln8wq8jrx1lids6ih1yksikil4b4-nixos-21.03pre257780.e9158eca70a/nixos/pkgs/development/compilers/ghcjs-ng/8.6/dep-overrides.nix:10:13
(use '--show-trace' to show detailed location information)

**To Reproduce**
nix-env -iA nixos.haskell.compiler.ghcjs

**Expected behavior**
ghcjs installed.

**Screenshots**
**Additional context**
Now, happy version is 1.20.0.
And `nixpkgs/pkgs/development/compilers/ghcjs-ng/8.6/dep-overrides.nix` asks for happy_1_19_5

**Notify maintainers**
**Metadata**
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/4h960nnzvs1lpjbd8xg2as3ylvzkphvb-nix-info
copying path '/nix/store/4h960nnzvs1lpjbd8xg2as3ylvzkphvb-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre253060.a322b32e9d7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:

# a list of nixpkgs attributes affected by the problem
attribute:
haskell.packages.ghcjs
haskell.compiler.ghcjs

# a list of nixos modules affected by the problem

**Comment by YuMingLiao** [comment]
After removing the version restrictions in `nixpkgs/pkgs/development/compilers/ghcjs-ng/8.6/dep-overrides.nix` (`happy=self.happy;` `shelly=super.shelly;`) in my local repository, 
`nix-env -f $NIXPKGS -iA haskell.compiler.ghcjs` starts to compile ghcjs normally (seemly in one sleep).

**Comment by YuMingLiao** [comment]
No. ghc-api-ghcjs-8.6.5 still needs happy >=1.19 && <= 1.19.9.

**Comment by YuMingLiao** [comment]
I just found the working one is ghcjs86. 
I can use it by `nix-shell -p haskell.packages.ghcjs86.ghcWithPackages (pkgs: with pkgs; [ ... ])`.

**Comment by YuMingLiao** [comment]
```
...
...
src/Engine.hs:13:9: error:                                                                                                          
    Module ‘GHCJS.DOM.Types’ does not export ‘castToHTMLElement’                                                                    
   |                                                                                                                                
13 |        (castToHTMLElement, castToElement, Document,
   |         ^^^^^^^^^^^^^^^^^                                                                                                      
                   
src/Engine.hs:13:28: error:     
    Module ‘GHCJS.DOM.Types’ does not export ‘castToElement’                                                                        
   |                                   
13 |        (castToHTMLElement, castToElement, Document,                                                                            
   |                            ^^^^^^^^^^^^^
                                          
builder for '/nix/store/6cdaqmpndifsa0brvg4yf9ib0yzgsy3n-webkit-sodium-0.0.1.drv' failed with exit code 1                           
cannot build derivation '/nix/store/h1adh9z618c3rkv4mr2xpkzl6yhxs16a-ghcjs-8.6.0.1-with-packages.drv': 1 dependencies couldn't be bui
lt                                              
error: build of '/nix/store/h1adh9z618c3rkv4mr2xpkzl6yhxs16a-ghcjs-8.6.0.1-with-packages.drv' failed                                

```                                                      
It seems ghcjs-examples/webkit-sodium in ghcjs86 can't adopt the latest ghcjs-dom-0.9.4.0.
But I don't know the max version that can export right functions.

**Comment by cdepillabout** [comment]
@YuMingLiao I don't think there are too many people using ghcjs directly from nixpkgs, so there aren't too many people fixing things when they break.

If you are able to find fixes to these problems you have, please feel free to send PRs.

**Comment by YuMingLiao** [comment]
@cdepillabout, thanks. Good to know.

I don't know how to make ghcjs to adopt the latest happy.

I use a workaround. I assigned the happy_1_19_5 and shelly_1_8_1 variables to its relative nix files in .config/nixpkgs/config.nix. And now haskell.packages.ghcjs and haskell.packages.ghcjs86 both works.

And I can directly use ghcjs without ghcjs-examples.
So I guess I can close this issue now.
