### ISSUE TITLE
On Darwin, build-use-chroot = true broken

### ISSUE THREAD

**Issue by mikesperber** [NixOS/nixpkgs#10663]
Builds consistently end in something like this:

~~~
dyld: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: /nix/store/kp4f6acmkhslpsy6zc9v2x7jzn9417b5-perl-5.20.1/bin/perl
  Reason: no suitable image found.  Did find:
	/usr/lib/libSystem.B.dylib: stat() failed with errno=1
	/usr/lib/libSystem.B.dylib: stat() failed with errno=1
~~~

This is mentioned in #9215 and #8363, but doesn't seem to have received much attention there.

**Comment by domenkozar** [comment]
@pikajude @edolstra

**Comment by henrytill** [comment]
It would be helpful if you could give some information like the nixpkgs revision and `nix-env --version` you are using.

Also, there has been a lot of churn recently as the Pure-Darwin stdenv has become the default, so it helps to be using the latest revision of nixpkgs and the git version of Nix.  Instructions for doing so are on the [wiki page](https://nixos.org/wiki/Nix_on_OS_X), which I would recommend looking at if you haven't   recently, as it has stayed up to date with the recent work, and there might be some helpful information there.

**Comment by mikesperber** [comment]
I followed the instructions on the Wiki page, first using the regular installer, and then trying to switch to  a freshly pulled (yesterday) git version of Nix. `nix-env --version` returns 1.10.

**Comment by henrytill** [comment]
You might try installing Nix itself from HEAD, which should be version `1.11pre1234_abcdef`
```
git clone https://github.com/NixOS/nix
cd nix
nix-env -f release.nix -iA build.x86_64-darwin --option build-use-chroot false
```

**Comment by mikesperber** [comment]
Thanks for the tip - unfortunately, that makes me run into #10691 ... :-(

**Comment by mikesperber** [comment]
... but once I monkey-patch my way around #10691 (keep deleting `/share/man`), things work.  Is it OK if I include a link to here in the Wiki?

**Comment by henrytill** [comment]
I'm not opposed to putting it in the wiki if more users report having this problem.  AFAIK you are the only person with the `/share/man` issue, and it'd be better to tackle that issue in #10691, if we can get a reproducible case.  So far, the problems in the Troubleshooting section of the wiki have been ones that have affected multiple users for known reasons.  

So could we close this issue and move the discussion to #10691?

**Comment by mikesperber** [comment]
Sure. But *this* problem, other people had - see the referenced ticket at the front.

**Comment by henrytill** [comment]
And to clarify for posterity's sake:

If anyone else has this problem, they should try the [aforementioned fix](https://github.com/NixOS/nixpkgs/issues/10663#issuecomment-152108876) of installing Nix from `HEAD`, as specified in [the wiki](https://nixos.org/wiki/Nix_on_OS_X#NixOS.2Fnix_.23562).
