### ISSUE TITLE
acme: wrong permssions for .well-known/acme-challenge/* / 403

### ISSUE THREAD

**Issue by rkoe** [NixOS/nixpkgs#106603]
**Describe the bug**
Since 20.09, renewing Let's Encrypt-certificates fail with lighttpd.

The problem is, that:
- the files created below `.well-known/acme-challenge/` are not world-readable anymore (This is the bug.)
- lighttpd only serves world-readable files (for security reasons)
- so, trying to read the acme-challenge via http(s) results in 403, and the certificate creation fails: 
  log message: `acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from https://DOMAIN/.well-known/acme-challenge/...`

This is probably caused by #91121, line `UMask = 0027;`, this should probably be `UMask = 0022;`

Workaround:
- "Manually" fix the permissions during certificate-renewal, e.g. by running the following as root: 
  `while true; do ll */.well-known/acme-challenge/; chmod a+r */.well-known/acme-challenge/*; sleep 0.05; done`
- restart all renewal-services: `systemctl restart acme-DOMAIN.service`
- repeat each time new certificates are necessary, until this bug is fixed

(Note: This problem is indpendent from #101445)

**To Reproduce**
1. run lighttpd
2. add an acme-configuration for a domain, which is served by lighttpd
3. try to renew a certificate

**Notify maintainers**
@m1cr0man @flokli

**Comment by m1cr0man** [comment]
You have two options to resolve this:

1. Add the lighttpd user to the acme group in your config
2. Set the group of your cert(s) to the lighttpd group. [This is what Apache HTTPD does](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/apache-httpd/default.nix#L660)

**Comment by gstrauss** [comment]
3. lighttpd supports TLS-ALPN-01 ("acme-tls/1") since lighttpd 1.4.53, and that challenge type is supported by the `dehydrated` client, among others.  [lighttpd TLS-ALPN-01](https://redmine.lighttpd.net/projects/lighttpd/wiki/HowToSimpleSSL)

**Comment by m1cr0man** [comment]
Sorry, reading over this again I understand what you're really highlighting here. I will change the UMask to `0023`. This is safe enough as lego does a good job at not outputting sensitive files with the wrong permissions, and we have our own chmods in the renew script to do the same thing.

**Comment by m1cr0man** [comment]
@rkoe could you give #106857 a test please?
