### ISSUE TITLE
Local python packages not importable from nix-shell

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixpkgs#106785]
**Describe the bug**

I want to start a shell to develop a local python package (let's use [cryptography](https://github.com/pyca/cryptography) as an example). I am unable to import the package when I start `python` within `nix-shell`.

**To Reproduce**
1. `git clone https://github.com/pyca/cryptography.git && cd cryptography`
2. `nix-shell channel:nixos-unstable -A python3.pkgs.cryptography --command python3` (this bug does not occur on `channel:nixos-20.09`)
3. `import cryptography` (in Python interpreter)

**Expected behavior**
I expect the import statement to not produce any errors. Instead, I see:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cryptography'
```

**Additional context**
I suspect this is to do with the first entry in `PYTHONPATH` in the resulting shell. On `unstable`, it no longer contains a `site.py` file. But I don't know enough about Python packaging to be sure.

**Notify maintainers**
@FRidh - I'm not sure if there's a more specific maintainer for this functionality.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(kai): `"home-manager, nixpkgs-21.03pre258014.2c0f6135aab"`
 - channels(root): `"nixos-21.03pre249162.1dc37370c48"`
 - nixpkgs: `/home/kai/.nix-defexpr/channels/nixpkgs`

**Comment by cript0nauta** [comment]
This issue looks similar to #108525. The problem is related to the upgrade of setuptools to a newer version, in which site.py files are not included in the environment.

**Comment by kwohlfahrt** [comment]
Yeah, I think that's the same issue. I'll close this one as a duplicate.
