### ISSUE TITLE
mailspring started to fail to launch

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#106732]
**Describe the bug**

At some point after a40d653c7b633c09e87160453893ebf02c42729a mailspring got broke, and now it fails to start with:

```
mailspring: ../src/workers/open.cc:28: virtual void OpenWorker::Execute(): Assertion `sqlite3_db_mutex(db->db_handle) == __null' failed.
```

**To Reproduce**

`nix shell nixpkgs#mailspring -c mailspring`.

**Additional context**

I need to learn to bisect the issue

**Notify maintainers**

@toschmidt 

Maintainer information:
```yaml
attribute: mailspring
```

**Comment by doronbehar** [comment]
Narrowed it down to: https://github.com/NixOS/nixpkgs/compare/657fef79..c377ced8 which implies that some change that went into staging in https://github.com/NixOS/nixpkgs/pull/105584 broke it :(.

**Comment by doronbehar** [comment]
Found it! 48234fdefa3 (https://github.com/NixOS/nixpkgs/pull/101537 ) . Even on current master, if I disable `trackerSupport` for the gtk3 input of mailspring, it works!

**Comment by doronbehar** [comment]
If anyone experience this issue I'd like to get a :+1: on https://github.com/NixOS/nixpkgs/pull/106740 . If no one will do it, I'll conclude I'm the only user of this package (on unstable I guess?) and I'll merge that PR.

**Comment by toschmidt** [comment]
Hi Doron,
thanks for tracking the issue down. Your fix also works for me.
