### ISSUE TITLE
python3.8-pyOpenSSL-20.0.0 (and thus `azure-cli`)fails to build on nixos-unstable-small

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#106863]
**Describe the bug**

Looks like `azure-cli` is broken on `nixos-unstable-small`, due to (at least) pyOpenSSL being broken due to `cryptography`.

Filing this sooner rather than later. I can't look at it at the moment.

cc: @jonringer

**To Reproduce**
```
❯ nix build github:nixos/nixpkgs/nixos-unstable-small#legacyPackages.x86_64-linux.azure-cli
error: --- Error --- nix-daemon
builder for '/nix/store/b711by0zza280whlrsm2hyd65zaxq1ij-python3.8-pyOpenSSL-20.0.0.drv' failed with exit code 1; last 10 log lines:
  adding 'pyOpenSSL-20.0.0.dist-info/top_level.txt'
  adding 'pyOpenSSL-20.0.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Finished executing setuptoolsBuildPhase
  installing
  Executing pipInstallPhase
  /build/pyOpenSSL-20.0.0/dist /build/pyOpenSSL-20.0.0
  Processing ./pyOpenSSL-20.0.0-py2.py3-none-any.whl
  ERROR: Could not find a version that satisfies the requirement cryptography>=3.2 (from pyopenssl)
  ERROR: No matching distribution found for cryptography>=3.2
error: --- Error ------------------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/bwy4fnzs95rrr8id8h7zmrb5byzvwv28-python3.8-azure-cli-2.15.1.drv' failed to build
```

`nix log /nix/store/b711by0zza280whlrsm2hyd65zaxq1ij-python3.8-pyOpenSSL-20.0.0.drv`
= https://gist.github.com/colemickens/d68f73d3c2c7dbdc24e776b7cbdb6d51

**Comment by FRidh** [comment]
it's probably due to an override in `pkgs/tools/admin/azure-cli/python-packages.nix`. The "actual" `python3.pkgs.pyopenssl` builds.

**Comment by anhdle14** [comment]
#106773

**Comment by jonringer** [comment]
I dont remember the original conditions in which this was necessary. But I'll make a PR to remove the override

**Comment by jonringer** [comment]
ah yes, now I remember:
```
ERROR: Could not find a version that satisfies the requirement cryptography<3.0.0,>=2.3.1 (from azure-cli)
ERROR: No matching distribution found for cryptography<3.0.0,>=2.3.1
```

**Comment by jonringer** [comment]
we run unit tests, I'll just disable bounds

**Comment by anhdle14** [comment]
@jonringer #106773 I thought this is already done the same thing. But anyway I will close mine in favor of yours.

**Comment by jonringer** [comment]
ah, it does, sorry was out of town for a while.

**Comment by jonringer** [comment]
#106773  has been merged, closing
