### ISSUE TITLE
Old cp argument breaks dwarf fortress

### ISSUE THREAD

**Issue by nviets** [NixOS/nixpkgs#106838]
Dwarf Fortress installs successfully, but it fails on launch. The "--no-preserve" argument of cp in [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/dwarf-fortress/wrapper/dwarf-fortress-init.in#L23) appears to be out of date.

```
me@computer ~ [1]> dwarf-fortress
Using /home/me/.local/share/df_linux as Dwarf Fortress overlay directory.
If you do any changes in it, don't forget to clean it when updating the game version!
We try to detect changes based on data directories being symbolic links -- keep this in mind.

cp: unrecognized option --no-preserve=all
BusyBox v1.31.1 () multi-call binary.

Usage: cp [OPTIONS] SOURCE... DEST

Copy SOURCE(s) to DEST
	-a	Same as -dpR
	-R,-r	Recurse
	-d,-P	Preserve symlinks (default if -R)
	-L	Follow all symlinks
	-H	Follow symlinks on command line
	-p	Preserve file attributes if possible
	-f	Overwrite
	-i	Prompt before overwrite
	-l,-s	Create (sym)links
	-T	Treat DEST as a normal file
	-u	Copy only newer files
```

Could someone familiar with the expected behavior of the script take a look? @abbradar, @matthewbauer, @cole-h

**Comment by symphorien** [comment]
You have busybox in path, and the wrapper uses cp expecting gnu coreutils cp. The wrapper should start by adding coreutils (and possibly other utils used in the script) to the PATH.

**Comment by nviets** [comment]
Thanks! I didn't catch that.  The application launches now.

**Comment by symphorien** [comment]
This is still an impurity that needs fixing, and the fix looks easy enough, do you think you could open a PR?
