### ISSUE TITLE
OptiX in Blender

### ISSUE THREAD

**Issue by NomisIV** [NixOS/nixpkgs#106848]
**Feature request**
As the title says, enable OptiX in Blender. I considered adding OptiX as a package request, but it seems like Nvidia wants to be the only one to distribute that package.

**How Arch linux has implemented it**
I looked at the PKGBUILD of Blender for arch, and they package OptiX with the blender package. [source](https://github.com/archlinux/svntogit-community/blob/packages/blender/trunk/PKGBUILD)

**How the Blender documentation suggests implementing it**
[This](https://wiki.blender.org/wiki/Building_Blender/CUDA) page describes what needs to be done to activate OptiX in the build process. To summarize: Install OptiX SDK 7.0, and add the following build flags
```
WITH_CYCLES_DEVICE_OPTIX=ON
OPTIX_ROOT_DIR=/path/to/NVIDIA-OptiX-SDK-7.x.x-xxx
```

I could try implementing this myself, but I don't know if I'll succeed, since I'm very new to NixOS.
Would submitting a pull request where I've done my what I can be any helpful?

**Notify maintainers**
@cillianderoiste 
@veprbl

**Comment by InternetUnexplorer** [comment]
I'm currently using this overlay, which seems to work:
```nix
self: super:
let
  optix-include = fetchzip {
    url =
      "https://developer.download.nvidia.com/redist/optix/v7.0/OptiX-7.0.0-include.zip";
    sha256 = "1b3ccd3197anya2bj3psxdrvrpfgiwva5zfv2xmyrl73nb2dvfr7";
  };
in {
  blender = super.blender.overrideAttrs (old: {
    cmakeFlags = (old.cmakeFlags or [ ]) ++ [
      "-DWITH_CYCLES_DEVICE_OPTIX=ON"
      "-DOPTIX_ROOT_DIR=${optix-include}"
    ];
  });
}
```
I won't have much time during the next two days, but after that if no one else has done it already I'm happy to make a PR. In the meantime, using the above overlay should work if you need OptiX support right now.

**Comment by NomisIV** [comment]
I have created a pull request, to the best of my abilities: #106888
