### ISSUE TITLE
darwin: package(s) fail trying to move to /share/man/man

### ISSUE THREAD

**Issue by mikesperber** [NixOS/nixpkgs#10691]
When Nix tries to compile a package from source, most builds fail ending in this:

~~~
moving /nix/store/gqqv3rcsk0sgbxpcw451d4giav31wqc4-MacOS_SDK-10.9/share/man to /share/man
mv: cannot move '/nix/store/gqqv3rcsk0sgbxpcw451d4giav31wqc4-MacOS_SDK-10.9/share/man' to '/share/man/man': Directory not empty
~~~

This is on Mac OS X, both with a fresh regular install, and when trying to update to a git pull.

I can create and write-enable `/share/man`, and things will work for one package, but then fail with the next because `/share/man/man` will exist already.

**Comment by mikesperber** [comment]
Following the instructions on #10663, after I updated Nix itself from Git head (while continuing to delete `/share/man`), the problem was gone.

**Comment by henrytill** [comment]
Sorry if my post on the other thread was confusing, but I think we should keep this issue open in case others run into it.  I'm curious to find out if it's a reproducible problem.

**Comment by mikesperber** [comment]
It was reproducible, but it's (reproducibly) gone after upgrading Nix itself. So I'd think it's fixed, no?

**Comment by henrytill** [comment]
Oh, so you don't have to manually delete `/share/man` anymore?

**Comment by mikesperber** [comment]
Exactly.

**Comment by henrytill** [comment]
Ah, the "continuing" threw me.  Glad to hear it!
