### ISSUE TITLE
pkgsCross.armv7l-hf-multiplatform.spidermonkey_78: error: field 'ufp' has incomplete type 'user_vfp'

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#106947]
**Describe the bug**

In a [sea of benign warnings](https://gist.github.com/Atemu/1680b62e31b6deb02a9cbbaddc00bfc5), you can find:

```
In file included from Unified_cpp_js_src_wasm2.cpp:38:
/build/firefox-78.4.0/js/src/wasm/WasmSignalHandlers.cpp:540:19: error: field 'ufp' has incomplete type 'user_vfp'
  540 |   struct user_vfp ufp;
      |                   ^~~
/build/firefox-78.4.0/js/src/wasm/WasmSignalHandlers.cpp:540:10: note: forward declaration of 'struct user_vfp'
  540 |   struct user_vfp ufp;
      |          ^~~~~~~~
/build/firefox-78.4.0/js/src/wasm/WasmSignalHandlers.cpp:541:23: error: field 'ufp_exc' has incomplete type 'user_vfp_exc'
  541 |   struct user_vfp_exc ufp_exc;
      |                       ^~~~~~~
/build/firefox-78.4.0/js/src/wasm/WasmSignalHandlers.cpp:541:10: note: forward declaration of 'struct user_vfp_exc'
  541 |   struct user_vfp_exc ufp_exc;
      |          ^~~~~~~~~~~~
```

and I assume that's why the build ultimately fails.

**To Reproduce**

`nix-build -A pkgsCross.armv7l-hf-multiplatform.spidermonkey_78`

https://github.com/Atemu/nixpkgs/tree/armv7l-cross-old

**Additional context**

This might be armv7l-specific, currently building `pkgsCross.aarch64-multiplatform.spidermonkey_78` to verify...

Edit: That one works, armv7l-specific bug

https://github.com/NixOS/nixpkgs/issues/106759

**Notify maintainers**

cc @matthewbauer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by thefloweringash** [comment]
This looks a lot like upstream bug [1526653 - Spidermonkey building error on Raspberry pi 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1526653). I opened a PR for this (https://github.com/NixOS/nixpkgs/pull/86532) but haven't found the time to get back to it.

**Comment by thefloweringash** [comment]
Still important to me. This should be fixed by https://github.com/NixOS/nixpkgs/pull/114942.

**Comment by misuzu** [comment]
#114942 is merged.
