### ISSUE TITLE
buildInputs and nativeBuildInputs swapped in documentation

### ISSUE THREAD

**Issue by ursi** [NixOS/nixpkgs#106950]
https://github.com/NixOS/nixpkgs/blame/f3103172fdfa364f5b1e153956f77ad83d76342b/doc/stdenv/cross-compilation.chapter.md#L78
> And indeed `buildInputs` and `nativeBuildInputs` have covered these simpler build-time and run-time (respectively) changes for many years

They way it's worded says `buildInputs` are for build-time and `nativeBuildInputs` are for run-time. The other documentation leads me to believe it is the other way around.

**Comment by roberth** [comment]
The other documentation was correct.

Thank you @ursi for taking the time to report this!
