### ISSUE TITLE
gpac's MP4Box runtime error

### ISSUE THREAD

**Issue by aopom** [NixOS/nixpkgs#106974]
**Describe the bug**
MP4Box display this error whenever it's launched :
```
[Core] default modules not found
[core] Cannot create config file GPAC.cfg in /home/ao/.gpac directory
Fatal error: failed to initialize GPAC global configuration
```
It doesn't seem to be a filesystem permission issue, because I can create this file and directory myself.
Deleting them doesn't solve the issue.

**To Reproduce**
1. get gpac `nix-shell -p gpac`
2. run `MP4Box` or `MP4Box -info $MP4VIDEO`

**Expected behavior**
MP4Box should find this default modules it is complaining about!

**Additional context**
I tried using MP4Box on 2 computers following the 20.09 channel, and ran across this same issue.

**Notify maintainers**
@bluescreen303 @mgdelacroix
@FRidh (I saw you updated the gpac lately)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.80, NixOS, 20.09.2122.2fbcd0b9df9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2238.b94726217f7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
&
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2238.b94726217f7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2238.b94726217f7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.gpac
# a list of nixos modules affected by the problem
module:
```
And thanks for this awesome nixpkgs by the way!
It's been 2 months I intensively play with NixOS and it's my first issue so far.

**Comment by tuxinaut** [comment]
I run into the same issue, with the **gpac** version (1.0.1) from unstable the issue does not show up!
