### ISSUE TITLE
RPCS3 not building

### ISSUE THREAD

**Issue by schvabodka-man** [NixOS/nixpkgs#106955]
**Describe the bug**
Hello, i can't install rpcs3 on nixos unstable. When rpcs3 is building i'm getting error that it lacks nvidia cuda library headers on build.

**To Reproduce**
Just install rpcs3

**Expected behavior**
rpcs3 builds and isntalls correctly.

**Screenshots**

This is error i got on build:
`CMake Error at rpcs3/cmake_modules/cotire.cmake:2374 (file):
  Error evaluating generator expression:

    $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

  $<COMPILE_LANG_AND_ID:lang,id> may only be used with binary targets to
  specify include directories, compile definitions, and compile options.  It
  may not be used with the add_custom_command, add_custom_target, or
  file(GENERATE) commands.
Call Stack (most recent call first):
  rpcs3/cmake_modules/cotire.cmake:2993 (cotire_generate_target_script)
  rpcs3/cmake_modules/cotire.cmake:3383 (cotire_process_target_language)
  rpcs3/cmake_modules/cotire.cmake:3567 (cotire_target)
  rpcs3/Emu/CMakeLists.txt:425 (cotire)

CMake Error at rpcs3/cmake_modules/cotire.cmake:2374 (file):
  Error evaluating generator expression:

    $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

  $<COMPILE_LANG_AND_ID:lang,id> may only be used with binary targets to
  specify include directories, compile definitions, and compile options.  It
  may not be used with the add_custom_command, add_custom_target, or
  file(GENERATE) commands.
Call Stack (most recent call first):
  rpcs3/cmake_modules/cotire.cmake:2993 (cotire_generate_target_script)
  rpcs3/cmake_modules/cotire.cmake:3383 (cotire_process_target_language)
  rpcs3/cmake_modules/cotire.cmake:3567 (cotire_target)
  rpcs3/Emu/CMakeLists.txt:425 (cotire)
`
**Notify maintainers**

@abbradar @nocent 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

- system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03pre257780.e9158eca70a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a"`
 - channels(ivan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:rpcs3
```

**Comment by petabyteboy** [comment]
Can you try using the latest master commit for rpcs3?
Something like `nix-shell -p rpcs3 -I nixpkgs=https://github.com/nixos/nixpkgs/archive/master.tar.gz` should work.

**Comment by schvabodka-man** [comment]
Hello @petabyteboy . Your command works for me and rpcs3 runs. But then i tried sudo nixos-rebuild switch --upgrade but got same error. Is this ok behaviour(i'm not good with nixos internals and how updates roll out)

**Comment by petabyteboy** [comment]
Yes, this is expected behaviour. First you can use `sudo nix-channel --list` to check what channel you are on:

```
[pbb@onyx:~]$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-unstable

[pbb@onyx:~]$
```

Now you can check on https://status.nixos.org/ when the channel was last updated. In case of nixos-unstable it was last updated 12 days ago and it's currently stuck because of a failing test:

https://github.com/NixOS/nixpkgs/issues/106858

And the fix is pending with the next staging (mass-rebuild) iteration:

https://github.com/NixOS/nixpkgs/pull/107086

**Comment by schvabodka-man** [comment]
Thx a lot @petabyteboy I guess i'll close this issue now
