### ISSUE TITLE
Installing dependencies from python package

### ISSUE THREAD

**Issue by shunxing** [NixOS/nixpkgs#10693]
Hi everyone,

I would like to install correctly flask from nixpkgs/pkgs/top-level/python-packages.nix.
After that Nix installed it, I wanted to try it by importing the library.

When I use python intepreter, it seems that the propagatedBuildInput haven't installed some libraries that flask depends. Indeed, I got this error when I tried to do in python :
>>> import flask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: No module named werkzeug.exceptions

However, when I import on IPython there's no issue.

My function that Nix call is the following one:
```nix
flask = buildPythonPackage rec{

    name = "flask-0.10.1";
    src = pkgs.fetchurl {
      url = "http://pypi.python.org/packages/source/F/Flask/Flask-0.10.1.tar.gz";
      md5 = "378670fe456957eb3c27ddaef60b2b24";
    };

    propagatedBuildInputs = with self; [ werkzeug jinja2 ];

};
```
I would like to know where does the issue come from.

**Comment by domenkozar** [comment]
Could you explain exact steps you take to start python interpreter? I don't understand if `flask` is coming from `python-packages.nix` or somewhere else. How how exactly are you even using Nix packages.

**Comment by shunxing** [comment]
Sorry for my bad explanation 

First I upgrade my python interpreter on terminal and also installed IPython with Nix.
Then I install flask from python-packages.nix which is in this repository with:
> nix-env -f /nixpkgs/ -iA python27Packages.flask 

When I launch the python interpreter from the terminal with
>$python

and import flask with:

>>> import flask

It throws me this error:
> Traceback (most recent call last):
> File "", line 1, in
> File "flask/init.py", line 17, in
> from werkzeug.exceptions import abort
> ImportError: No module named werkzeug.exceptions

After that I try to import flask with ipython (installed by Nix) with:
>$ipython

Then :
> import flask

Nothing happen meaning that it succeed

**Comment by domenkozar** [comment]
Use:

```
$ nix-shell -p pythonPackages.flask
$ python -c "import flask"
```

See http://nixos.org/nixpkgs/manual/#sec-python for more details

**Comment by shunxing** [comment]
If we use nix-shell it means that we create a shell where there is only flask, but does it mean that we have to create a shell with all libraries that we need everytime ? Can't we "append" flask to our current environment?

If it is the only solution, I got a clone of this repository on my machine, how could I fetch my directory with nix-shell, like I did with nix-env?

**Comment by shunxing** [comment]
Thanks to reply me so fast ! :+1:

**Comment by domenkozar** [comment]
Then I'd use `python.buildEnv` http://nixos.org/nixpkgs/manual/#ssec-python-build-env
