### ISSUE TITLE
Package perl-Compress-Raw-Zlib build not isolated

### ISSUE THREAD

**Issue by noahl** [NixOS/nixpkgs#107]
When building the package 'perl-Compress-Raw-Zlib' on OS X 10.6.8, the builder tells me that my version of the zlib header file (1.2.7) doesn't match the version of zlib I have installed (1.2.3).

I think this means the build environment is being contaminated by the operating system's built-in libraries.

**Comment by mjhoy** [comment]
running `nix-env -iA nixpkgs.perlPackages.CompressRawZlib` appears to work for me (osx 10.9, nixos-unstable), although there is this curious output:

    LD_RUN_PATH="/nix/store/0s5i71y9rjnbzxlmr6msdvf48qva5v99-zlib-1.2.8/lib" cc  -bundle -undefined dynamic_lookup -L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-Libsystem-osx-10.9.5/lib -fstack-protector Zlib.o  -o blib/arch/auto/Compress/Raw/Zlib/Zlib.bundle 	\
       -L/nix/store/0s5i71y9rjnbzxlmr6msdvf48qva5v99-zlib-1.2.8/lib -lz  	\
  
    ld: warning: directory not found for option '-L/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-Libsystem-osx-10.9.5/lib'
