### ISSUE TITLE
Overridable VM options for idea-community (and other JetBrains projects)

### ISSUE THREAD

**Issue by jdaniel-at-yottly-dot-com** [NixOS/nixpkgs#107032]
## Issue description

The package hardcodes VM options such as maximum heap size. Normally one would modify the said vmoptions once his projects grow large enough for the Idea editor to start experiencing memory pressure. However in Nix this is much more difficult to do.

### Steps to reproduce

Install idea-community package. Examine /nix/store/...-idea-community-.../idea-community-.../bin/idea64.vmoptions and notice there is no way to for the user to modify this fixed setting. Could there be an optional package option that would trigger rewrite of the bin/*.vmoptions files with changed VM options? If not present the prepackaged upstream defaults would remain.

**Comment by edwtjo** [comment]
I agree, I'll take this into account in #106055
