### ISSUE TITLE
Installing mdcat/ansi2html fails

### ISSUE THREAD

**Issue by andys8** [NixOS/nixpkgs#107042]
**Describe the bug**

Installing mdcat/ansi2html fails

**To Reproduce**

```
nix-shell -p mdcat
```

**Expected behavior**

It installs

**Additional context**

```
Executing pipInstallPhase
/build/ansi2html-1.6.0/dist /build/ansi2html-1.6.0
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Processing ./ansi2html-1.6.0-py2-none-any.whl
ERROR: Package 'ansi2html' requires a different Python: 2.7.18 not in '>=3.6'
builder for '/nix/store/5firqmc7lv2gk3i3fbng3xy297a46p0y-python2.7-ansi2html-1.6.0.drv' failed with exit code 1
cannot build derivation '/nix/store/3bw11y0zdg63gdgsfn0phphcy6rrx29x-mdcat-0.22.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3bw11y0zdg63gdgsfn0phphcy6rrx29x-mdcat-0.22.1.drv' failed

```

**Notify maintainers**

*(Removed actual author github handle)*

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(andreas): `"nixpkgs-21.03pre258115.8006772a054"`
 - nixpkgs: `/home/andreas/.nix-defexpr/channels/nixpkgs`

**Comment by lunaryorn** [comment]
I do not maintain this nixpkg; this is not my bug, I don't even know what Nixis is.  You need want to mention whoever is responsible for this  packaging, but please keep me out.

**Comment by andys8** [comment]
I'm sorry. I was using the github owner field, but nixpkgs maintainer field refers to @davidtwco
