### ISSUE TITLE
Tag Editor

### ISSUE THREAD

**Issue by luxferresum** [NixOS/nixpkgs#107006]
**Project description**
A tag editor with Qt GUI and command-line interface. Supports MP4 (iTunes), ID3, Vorbis, Opus, FLAC and Matroska.

**Metadata**

* homepage URL: https://github.com/Martchus/tageditor
* source URL: https://github.com/Martchus/tageditor
* license: mit, GPLv2.0
* platforms: linux

**Comment by matthiasbeyer** [comment]
I am working on it.

Progress: https://git.beyermatthi.as/nixpkgs/log/?h=init-tageditor
