### ISSUE TITLE
nixos/apache-httpd: SSL requests fail in PHP because of missing certificates

### ISSUE THREAD

**Issue by xconstruct** [NixOS/nixpkgs#10703]
When using simple PHP in Apache, all SSL functions fail at certificate verification (e.g. `file_get_contents("https://google.com")` or `stream_socket_client()`). Looks like Apache does not find the system root certificates.

` OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`

```nix
{
  services.httpd = {
    enable = true;
    enablePHP = true;
  };
}
```

Adding `{ systemd.services.httpd.environment.SSL_CERT_FILE = "/etc/ssl/certs/ca-bundle.crt"; }` fixes this. Looks like it's related to #8247.

**Comment by cleverca22** [comment]
the same problem exists in services.phpfpm

**Comment by zimbatm** [comment]
Is this still an issue ? I think #12748 would have fixed this.
