### ISSUE TITLE
plasma-applet-virtual-desktop-bar

### ISSUE THREAD

**Issue by lasers** [NixOS/nixpkgs#107151]
**Project description**
An applet for KDE Plasma panel (or Latte Dock) that lets you switch between virtual desktops and also invoke some actions to dynamically manage them in a convenient way.

**Metadata**

* homepage URL: https://github.com/wsdfhjxc/virtual-desktop-bar
* source URL: https://github.com/wsdfhjxc/virtual-desktop-bar
* license: gpl3
* platforms: linux

**Comment by peterhoeg** [comment]
Plasma applets are straight forward to do. Do you feel like taking a stab at it? Ping me if you get lost/stuck.

Inspiration: https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5/3rdparty/addons/caffeine-plus.nix

**Comment by lasers** [comment]
>... feel like taking a stab at it?

I tried. New to Nix. Don't know Nix language, didn't read Nix pills, got a messy setup to sort out. Long road ahead. Feel free to take over. I tried things and couldn't get it to build the program. https://github.com/lasers/nixpkgs/tree/virtual-desktop-bar

**Comment by lasers** [comment]
@peterhoeg I successfully ~~took~~ gave a stab. Please take a look. 

Note: `1.5` came out, but was removed eventually. Unsure what to do here, I went for `2020-02-20`.
