### ISSUE TITLE
cargo-tarpaulin 0.17.0 has been yanked.

### ISSUE THREAD

**Issue by puzzlewolf** [NixOS/nixpkgs#107158]
`cargo-tarpaulin` 0.17.0 has been [yanked](https://crates.io/crates/cargo-tarpaulin/0.17.0). 

I noticed there was a PR for for 0.16.0, https://github.com/NixOS/nixpkgs/pull/103366, which got replaced by on for 0.17.0, https://github.com/NixOS/nixpkgs/pull/103366.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `cargo-tarpaulin`

current version: 0.17.0
desired version: 0.16.0

###### Notify maintainers

maintainers: @HugoReeves 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by HugoReeves** [comment]
Hi, thanks for bringing this to my attention. I will look into yanking the release. Thanks

**Comment by egasimus** [comment]
@HugoReeves can we update to 0.16.0 or 0.18.0-alpha3?

**Comment by puzzlewolf** [comment]
This is no longer needed, `tarpaulin` has been updated to 0.18 in e8d3c65b361bcdbeb445433660fbdde8c738434e :)
