### ISSUE TITLE
generating multiple configurations and boot entries with a single rebuild

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#107198]
Is there a way to generate several different and labeled configurations that can be selected at boot time, with a single invokation of ``nixos-rebuild`` or ``nixops deploy``?

The reason I want to do that is I need to run Windows software that requires a powerful discrete GPU. Since that so-called "operating system" is basically unmanageable without a VM, I'm using libvirt with VFIO PCIe passthrough for the discrete GPU, which is surprisingly trouble-free (with a AMD GPU - reportedly NVIDIA actively blocks virtualization unless you buy the premium cards).
For more convenience, I would like to select at boot time whether I want the discrete GPU allocated to the Linux desktop, or turned into a VFIO device (``nixos-rebuild``ing every time is somewhat annoying and requires root). This is mostly a bunch of kernel options, though it would be nice to also have libvirt disabled and not attempting to boot Windows when the discrete GPU is allocated to the Linux desktop.

**Comment by colemickens** [comment]
I think you should be able to leverage the `specialisation` option. And if you use GRUB you'll get the multiple boot entries.

**Comment by sbourdeauducq** [comment]
Awesome - that does the trick!

**Comment by sbourdeauducq** [comment]
Thanks
