### ISSUE TITLE
Integer comparison bug with /bin/sh in nix-build

### ISSUE THREAD

**Issue by kaldonir** [NixOS/nixpkgs#107145]
**Describe the bug**
Comparing integers with `test $number1 -lt $number` using /bin/sh leads to the wrong results if `$number1` is too large, but only if executed in a `nix-build` context. If executed manually from a shell, this works fine.

**To Reproduce**
1. create a `default.nix`:
   ```nix
   let
     pkgs = import <nixpkgs> {};
     script = pkgs.writeText "script" ''
       small=560493232127
       big=560493232128
       echo Small = $small
       echo Big = $big
       if test $small -lt 100000; then
         echo "Small test failed for $small"
         exit 1
       fi
       if test $big -lt 100000; then
         echo "Big test failed for $big"
         exit 1
       fi
       echo "Test succeeded"
     '';
   in pkgs.runCommand "foo" {} ''
     /bin/sh ${script}
     touch $out
   ''
   ```
2. `nix-build`
3. Build fails: 
```
these derivations will be built:
  /nix/store/fy0a2cwcjyiq4ciap7vl004ifh1x6gv8-foo.drv
building '/nix/store/fy0a2cwcjyiq4ciap7vl004ifh1x6gv8-foo.drv'...
Small = 560493232127
Big = 560493232128
Big test failed for 560493232128
builder for '/nix/store/fy0a2cwcjyiq4ciap7vl004ifh1x6gv8-foo.drv' failed with exit code 1
error: build of '/nix/store/fy0a2cwcjyiq4ciap7vl004ifh1x6gv8-foo.drv' failed
```

**Expected behavior**
The derivation defined above should build, because `560493232128` is obviously larger than `1000000`.

**Additional context**
This originally occured when trying to nixify a third-party installer which checks the available disk space and triggers this bug if a large amount of disk space is available.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2155.99f8282a658 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(kaldonir): `"home-manager-20.09, nixos-19-09-19.09.2522.75f4ba05c63, nixos-20-03-20.03.3318.030e2ce817c, nixos-unstable-21.03pre257780.e9158eca70a, nixpkgs-20.09.2238.b94726217f7, nixpkgs-unstable-21.03pre258115.8006772a054"`
 - channels(root): `"nixos-20.09.2155.99f8282a658"`
 - nixpkgs: `/home/kaldonir/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by kaldonir** [comment]
I don't know how to find out who's maintainer for this. Can somebody please help me ping the right people?

**Comment by veprbl** [comment]
This is expected as /bin/sh is provided by busybox in sandboxed build, but in host filesystem it is bash.

**Comment by kaldonir** [comment]
Okay, makes sense. The intended way to work around third-party scripts would be to nixify them with `patchShebang` anyways, to run it reproducibly.
