### ISSUE TITLE
Jupyter Notebook service

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#10713]
We have packages for Jupyter Notebook as well as Python kernels and also an Haskell kernel.
Furthermore, there is a notebook service although this one is specific to Haskell (`nixos/modules/services/misc/ihaskell.nix`).

I think it would be nice if we would have a generic notebook service and where we can specific which kernels we want to have. We could base this on the iHaskell service and perhaps have an attribute like:

```
 kernels = [ python27Packages.ipython python35Packages.ipython ihaskell irkernel ]
```

What do you think?
cc potential users @datakurre @edwtjo @Profpatsch @bjornfor

**Comment by bjornfor** [comment]
I don't use/know this enough to give useful input. Sorry :-)

**Comment by datakurre** [comment]
I'm using Nix outside NixOS, so I wouldn't need global service, but a kind of compose expression, to build notebook with required kernel in fly.

**Comment by Profpatsch** [comment]
Yes, something like `jupyterWithKernel` would probably make sense.

**Comment by datakurre** [comment]
I'm working experimenting with the idea at https://gist.github.com/datakurre/49b6fbc4bafdef029183 , but I'm not yet good enough in Nix to make it generic enough.

**Comment by edwtjo** [comment]
I think the fix/unfix approach would be nice for this also and in such a situation I would have no problem with a general ipython service. I also approve of the process to just copy the ihaskell service to an ipython one and generalize from there on.

**Comment by aragnon** [comment]
Yes, this is a good idea, but I am also not using NixOS.

**Comment by garbas** [comment]
@FRidh +1

**Comment by rehno-lindeque** [comment]
It would also be rather nice to have nix handle the installation of Jupyter extensions (e.g. https://github.com/ipython-contrib/IPython-notebook-extensions). This might need to be recorded as a separate issue though, I'm not sure?

**Comment by teh** [comment]
@rehno-lindeque notebook extensions are a pain and I'm not sure how to package them in nix. I heard rumors that they're moving to NPM which, as terrible as it sounds, might make it easier for us to package extensions.

@FRidh I'd like to revive this. For comparison I'll paste my `dask-worker` code that I use privately. The idea (which works fairly well for me) is to provide a python env for each notebook server. E.g. we'd use it like:

```nix
services.jupyter.notebooks = {
  sklearn = { pythonEnv = python.buildEnv.override { extraLibs = [ scikitlearn ]; }; port = 8888; };
  flask = { pythonEnv = python.buildEnv.override { ... }; port = 8889; };
}; 
```
and start one jupyter server per environment. The code could look roughly like this:

```nix
{ config, pkgs, lib, ... }:
with lib;
{
  options = {
    services.dask = {
      workers = mkOption {
        default = {};
        type = types.attrsOf (types.submodule ({config, options, name, ...}: {
          options = {
            aliases = mkOption {
              type = types.listOf types.str;
              default = [name];
              example = literalExample ''[ "low-memory" "gpu" ]'';
              description = "List of aliases for this worker.";
            };
            pythonEnv = mkOption {
              type = types.package;
              description = ''
            python environment created with pkgs.python.buildEnv.
            Must contain distributed package.
          '';
            };
            scheduler = mkOption {
              type = types.str;
              default = "127.0.0.1:8786";
              description = "scheduler address.";
            };
            nthreads = mkOption {
              type = types.nullOr types.int;
              default = null;
              description = "number of cores to use";
            };
          };
        }));
      };
    };
  };

  config = {
    users.extraUsers.dask-worker =  {
      description = "dask worker";
      createHome = true;
      home = "/var/lib/dask-worker";
    };

    systemd.services = let
      services = mapAttrsToList (name: cfg: nameValuePair "dask-worker@${name}" (
        let
          names = concatMapStrings (x: "  --name " + x) cfg.aliases;
          maybeNThreads = if cfg.nthreads == null then "" else "--nthreads ${toString cfg.nthreads}";
        in {
          wantedBy = [ "multi-user.target" ];
          requires = [ "network.target" ];
          after = [ "network.target" ];
          serviceConfig = {
            ExecStart = "${cfg.pythonEnv}/bin/dask-worker ${maybeNThreads} ${names} ${cfg.scheduler}";
            User = "dask-worker";
            Restart = "always";
            PrivateTmp = true;
          };
        }
      )) config.services.dask.workers;
    in listToAttrs services;
  };
}
```

What do you think?

**Comment by FRidh** [comment]
> @FRidh I'd like to revive this. For comparison I'll paste my dask-worker code that I use privately. The idea (which works fairly well for me) is to provide a python env for each notebook server. E.g. we'd use it like:

We would need one simple env which provides the notebook server, and then one env per kernel, and these can be Python env's but also Haskell, or whatever.

@teh can you share your `services.jupyter` ?

**Comment by teh** [comment]
@FRidh - there isn't much to it, it's basically:

```
```

**Comment by FRidh** [comment]
For each kernel we need
- a [connection file](https://jupyter-client.readthedocs.io/en/latest/kernels.html#connection-files)
- a [kernel spec](https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs)

An example of a kernel spec is
```py
{
 "argv": ["python3", "-m", "IPython.kernel",
          "-f", "{connection_file}"],
 "display_name": "Python 3",
 "language": "python"
}
```
This contains
1. the connection file
2. A name for the kernel.
3. A language identifier.
4. Optionally an `env` attribute with additional environment variables.

An example of a connection file
```py
{
  "control_port": 50160,
  "shell_port": 57503,
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "stdin_port": 52597,
  "hb_port": 42540,
  "ip": "127.0.0.1",
  "iopub_port": 40885,
  "key": "a0436f6c-1916-498b-8eb9-e81ab9368e84"
}
```
`signature_scheme` and `key` are used to cryptographically sign messages. We shouldn't have the latter visible in the store.

The kernel spec and connection file we take over almost one on one.

```

services.jupyter = {
  notebook = pkgs.python3.pkgs.notebook;
  kernels = {
    "mypython3" = {
      language = "python3";
      argv = []; # Would be nice if we could simplify this one
      env = "";
      connection = {
        ...
      };
    };
  };

}


```

**Comment by FRidh** [comment]
I actually think the whole logic of kernels should be put outside of the service and in some package.

**Comment by FRidh** [comment]
PR in https://github.com/NixOS/nixpkgs/pull/33673

**Comment by jb55** [comment]
Can this be closed?

**Comment by FRidh** [comment]
Yes!
