### ISSUE TITLE
documentation.info.enable broken

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#107216]
**Describe the bug**
If I would try to use `nixos-rebuild switch`
I would get the following error
```
builder for '/nix/store/ajr7idasrl5k33y8ydscb930bmsylfm6-system-path.drv' failed with exit code 1; last 2 log lines:
created 32855 symlinks in user environment
install-info: Cannot allocate memory for gzip -d
```

that guides me to this command after trying to inspect that derivation for `install-info`
https://github.com/NixOS/nixpkgs/blob/cb312f3d03dbaf2d60e2fd3917ba2e5d41ffe631/nixos/modules/misc/documentation.nix#L245

**To Reproduce**
1. Rebuild switch and somehow have a setup like mine maybe?

**Expected behavior**
`install-info` would succeed.

**Additional context**
I'm using Flakes and `nixUnstable` and my own patches on top of nixpkgs
https://github.com/worldofpeace/nixpkgs/commits/deploy. I kinda doubt it would have anything to do with this, though.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 21.03.20201219.68915ca (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - nixpkgs: *useless nix store path based on e9158eca70ae59e73fae23be5d13d3fa0cfc78b4

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

:exclamation: :exclamation: :exclamation: Disclaimer. I'm still on vacation but as I'd like to use one of my machines using NixOS I thought I would open this report. At most I am willing to relay information for reproduction of the issue.

**Comment by maralorn** [comment]
@veprbl Do you mind elaborating why this is related to Haskell? I don‘t see it.

**Comment by alyssais** [comment]
I tried and failed to reproduce this on https://github.com/worldofpeace/nixpkgs/commit/d449e65b3178dce35df73ce785832d8f7833bc0a, even with relatively low available memory and every package I could find (>350) that had info pages in `environment.systemPackages`. @worldofpeace guessing your configuration isn’t public?

**Comment by worldofpeace** [comment]
> I tried and failed to reproduce this on [worldofpeace@d449e65](https://github.com/worldofpeace/nixpkgs/commit/d449e65b3178dce35df73ce785832d8f7833bc0a), even with relatively low available memory and every package I could find (>350) that had info pages in `environment.systemPackages`. @worldofpeace guessing your configuration isn’t public?

Yeah, my configuration isn't public atm. The only other input in my configuration would be home-manager... but I don't think it would cause an issue in nixos?

I'm wondering if I have a package in an overlay with an info page that causes an issue, but even then that's really weird and shouldn't happen. Btw, u did reproduce with nix unstable and a flake.nix?

**Comment by worldofpeace** [comment]
I will note, I even thought I somehow killed my machine because this error was soo confusing that maybe my `nix store` was just done. (a good chance to repartition with a better filesystem anyways). That made no change and then I realized "wtf" and tracked it back to this. What lead me to think it was just my machine blowing up was, it seemed to happen suddenly. I'm now wondering if I can bisect my configuration to see if a change in one of the flakes caused it. (that being nixpkgs).

**Comment by worldofpeace** [comment]
Ahh, as expected bisecting my configuration is a bust for various reasons (mostly me being lazy with git since I couldn't be bothered). Perhaps I should try to build a vm configuration and see if it still happens.

**Comment by worldofpeace** [comment]
I found a lead!!!

This is the code I used
```nix
{ pkgs ? import ./. { } }:

with pkgs;
let
  myProfile = writeText "my-profile" ''
    export PATH=$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/sbin:/bin:/usr/sbin:/usr/bin
    export MANPATH=$HOME/.nix-profile/share/man:/nix/var/nix/profiles/default/share/man:/usr/share/man
    export INFOPATH=$HOME/.nix-profile/share/info:/nix/var/nix/profiles/default/share/info:/usr/share/info
  '';
in buildEnv {
  name = "my-packages";
  paths = [
    (runCommand "profile" {} ''
      mkdir -p $out/etc/profile.d
      cp ${myProfile} $out/etc/profile.d/my-profile.sh
    '')
  gnupg
  nixUnstable
  e2fsprogs # has a .info.gz which makes it break
  ];
  pathsToLink = [ "/share/man" "/share/doc" "/share/info" "/bin" "/etc" ];
  extraOutputsToInstall = [ "man" "doc" "info" ];
  postBuild = ''
        if [ -w $out/share/info ]; then
          shopt -s nullglob
          for i in $out/share/info/*.info $out/share/info/*.info.gz; do
              ${texinfo}/bin/install-info --debug $i $out/share/info/dir
          done
        fi
  '';
}

```

gnupg has an .info without a gzip archive, and `e2fsprogs` does. I noticed after adding `--debug` to install-info execution stopped after touching `e2fsprogs`. Here's the example output from the test:
```
debug: reading input file /nix/store/1nv0wl98cdd8z48sy11mjy1z9ccnlvsm-my-packages/share/info/libext2fs.info.gz
install-info: Cannot allocate memory for gzip -d
```

I don't understand what it means, but it appears that on my machine `installi-info` cannot install any `*.info.gz`.

And actually, using `nix-locate info.gz` shows me that it's lesser used if that means anything.

But I still don't understand what `Cannot allocate memory for gzip -d` means, and where that error comes from?
I read the source code a little bit to see what `open_possibly_compressed_file` does.

**Comment by worldofpeace** [comment]
So after using breakpointHook and cntr on texinfo, because I wanted to run the test suite as it has a test case for what happens with the `*.info.gz`, I noticed that my sandbox didn't have `/bin/sh`.  Dropping https://github.com/worldofpeace/nixpkgs/commit/d449e65b3178dce35df73ce785832d8f7833bc0a made `/bin/sh` return.
```
 nix show-config | grep sandbox-paths                                        ~
sandbox-paths = /bin/sh=/nix/store/bx800wdaqjf5k5346xkvcbc8ss9bmqnp-busybox-1.31.1-x86_64-unknown-linux-musl/bin/busybox
```

So if anyone ever gets highly confusing errors it seemed that inspecting that my build sandbox was okay was necessary.
