### ISSUE TITLE
haskell: do not override mkDerivation

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#10727]
```nix
  haskellPackages = self:
    let
      mkDerivation = pkgs.callPackage ./generic-builder.nix {
```

I think it is very bad style to shadow a basic symbol with your own local definition. It is also highly irritating and confusing.

The Python infrastructure uses `buildPythonPackage`, Ruby `bundlerEnv`,  golang `buildGoPackage`, Lua `buildLuaPackage`, and we should comply.

**Comment by peti** [comment]
IMHO, there is no ambiguity between `stdenv.mkDerivation` and `haskellPackages.mkDerivation`. The fact that that these two functions have the same name communicates that they do something conceptually similar, and the fact that they exist in different name spaces communicates that despite those similarity they are not identical, i.e. not the same function. IMHO, that's a perfectly accurate depiction of reality, and I don't see what we'd gain by renaming the function (other than upsetting people who depend on that name in their own code).
