### ISSUE TITLE
overrideDerivation doesn't work for setting separateDebugInfo

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#10721]
To enable debug info for a package that doesn't have it, one might naively expect this work:

```
  nixpkgs.config.packageOverrides = pkgs: {
    hello = overrideDerivation pkgs.hello (attrs: {
      separateDebugInfo = true;
    });
  };
```

However, this doesn't work because `separateDebugInfo` affects `mkDerivation`, not `derivation`. So we'd need some way to re-call the original `mkDerivation` invocation with new arguments.

**Comment by domenkozar** [comment]
How would we do that without uplifting `mkDerivation`?

**Comment by vcunat** [comment]
/participate. (BTW, if you know a better way how to do this, tell me.)

**Comment by domenkozar** [comment]
on the right you have "Subscribe" button

**Comment by vcunat** [comment]
I'm already subscribed to anything happening in the repository, and I'm tracking my interests in the *participating* tab in notifications. Maybe I'm using the interface a wrong way?

**Comment by Mathnerd314** [comment]
Nix has to be upgraded, and there are some package rebuilds to look at, but https://github.com/Mathnerd314/nixpkgs/commit/b4167e51a93dc9a756f1bc54dac9e72fee2d375f would fix this.

**Comment by edolstra** [comment]
What's the runtime cost? In general, multiple layers of `.override` are bad for (memory) performance.

**Comment by globin** [comment]
@vcunat unsubscribe -> subscribe == participate

**Comment by Mathnerd314** [comment]
@edolstra 
With change (b4167e51a93dc9a756f1bc54dac9e72fee2d375f):
```
$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode ~/nixpkgs -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:27.43 0:27.52 0:27.54
        Maximum resident set size (kbytes): 1749328 1749800 1750280

$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode --eval -E "import ~/nixpkgs {}" -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.10
        Maximum resident set size (kbytes): 16540 16560 16568

$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode ~/nixpkgs -A firefox -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.47 0:00.47 0:00.48
        Maximum resident set size (kbytes): 67324 67496 67556

$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode ~/nixpkgs/nixos -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:13.99 0:14.02 0:14.08
        Maximum resident set size (kbytes): 984820 984844 985180
```
Without change (1962484d15f401f44b220b47fdfd8f5ec179838e):
```
$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode ~/nixpkgs -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:24.90 0:24.92 0:25.12
        Maximum resident set size (kbytes): 1608744 1609020 1609164

$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode --eval -E "import ~/nixpkgs {}" -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.10
        Maximum resident set size (kbytes): 16552 16636 16656 16656 16712

$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode ~/nixpkgs -A firefox -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.40 0:00.40 0:00.41
        Maximum resident set size (kbytes): 59916 59932 59948

$ `which time` -v bash -c '~/nix/inst/bin/nix-instantiate --readonly-mode ~/nixpkgs/nixos -k --show-trace &> /dev/null'
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:12.50 0:12.52 0:12.59 0:12.75 0:12.76
        Maximum resident set size (kbytes): 864920 865424 866248 866480 866496
```
So it's about 12% overhead in memory & time.

**Comment by aneeshusa** [comment]
The original request for "some way to re-call the original mkDerivation invocation with new arguments" is precisely the new `overrideAttrs` function I introduce in #17886.

**Comment by aneeshusa** [comment]
I made a separate PR for `overrideAttrs`: #18660.

**Comment by aneeshusa** [comment]
I believe this issue can be closed now that `overrideAttrs` is merged.

**Comment by domenkozar** [comment]
I'll let @edolstra close it

**Comment by vcunat** [comment]
We should amend the documentation to use `overrideAttrs`; https://nixos.org/nixos/manual/options.html#opt-environment.enableDebugInfo and maybe some other place(s).

**Comment by aneeshusa** [comment]
@vcunat I will make a PR for that soon.
