### ISSUE TITLE
cross compiling nixos -> darwin gives infinite recursion error

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#107241]
**Describe the bug**
When cross-compiling on nixos (build system) for darwin (host system), I get an infinite recursion error.

**To Reproduce**
`nix-build '<nixpkgs>' --arg crossSystem '{ config = "x86_64-darwin"; }' -A <package>`
where `<package>` can be `hello` or `stdenv` or pretty much anything I suspect.

**Expected behavior**
A package would be compiled that would run when transfered to a mac os x computer.

**Additional context**
When run with `--show-trace`, I get the following output:
```
error: while evaluating the attribute 'defaultNativeBuildInputs' of the derivation 'stdenv-linux' at /nix/store/763lmlm4i9n77kzlb8ihjkz8dkhypj22-nixos-21.03pre257780.e9158eca70a/nixos/pkgs/stdenv/generic/default.nix:88:14:
while evaluating the attribute 'depsTargetTargetPropagated' of the derivation 'x86_64-darwin-clang-wrapper-7.1.0' at /nix/store/763lmlm4i9n77kzlb8ihjkz8dkhypj22-nixos-21.03pre257780.e9158eca70a/nixos/pkgs/stdenv/generic/make-derivation.nix:192:11:
while evaluating the attribute 'buildInputs' of the derivation 'compiler-rt-7.1.0-x86_64-darwin' at /nix/store/763lmlm4i9n77kzlb8ihjkz8dkhypj22-nixos-21.03pre257780.e9158eca70a/nixos/pkgs/stdenv/generic/make-derivation.nix:198:11:
while evaluating the attribute 'stdenv' of the derivation 'libc++abi-7.1.0-x86_64-darwin' at /nix/store/763lmlm4i9n77kzlb8ihjkz8dkhypj22-nixos-21.03pre257780.e9158eca70a/nixos/pkgs/stdenv/generic/make-derivation.nix:198:11:
infinite recursion encountered, at undefined position

```

**Notify maintainers**
This isn't about any particular packages, it's about the cross-compilation system I suspect.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre252388.069f183f16c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a, nixos-hardware"`
 - channels(qolen): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: crossSystem
# a list of nixos modules affected by the problem
module:
```

**Comment by f4814** [comment]
Git bisect tells me 0de6275003170cb82e5f9a3bdfb649ff22b8b12a is the first bad commit. I'll try to find a fix.

CC @pikajude

**Comment by f4814** [comment]
https://github.com/f4814/nixpkgs/commit/1024e0c4db9bdccf4ca7c4a8afe18449cd164e9a seems to fix the infinite recursion problem. However with this cross compiling fails while building x86_64-apple-darwin-binutils.

**Comment by Radvendii** [comment]
My knowledge of the bootstrapping process is definitely limited, but isn't this line kind of intrinsically problematic?

https://github.com/NixOS/nixpkgs/blob/0656d546fb96e234d40136bfe9a229428ad78363/pkgs/development/compilers/llvm/7/default.nix#L5

Depending on things from the *next* stage is bound to result in loops, no?

**Comment by Radvendii** [comment]
Oh never mind, I think I understand how using wrapCC, things are made to not depend on exactly the things that would cause infinite loops. That still leaves the question of why is there an infinite loop in this case, though

**Comment by Radvendii** [comment]
Am I reading the trace correctly that `stdenv-linux` (presumably some stage of the bootstrap process, though `buildPackages.stdenv`, which is also called `stdenv-linux`, builds fine) is depending, via `defaultNativeBuildInputs`, on `x86_64-darwin-clang-wrapper-7.1.0`? I would assume the darwin clang wrapper would only be needed by the darwin stdenv. 

Also, why are things that are building for darwin using `stdenv-linux` for their stdenv?

**Comment by Radvendii** [comment]
(if this stuff is tedious / difficult to explain but not actually relevant or helpful, feel free to ignore me)

**Comment by Radvendii** [comment]
I noticed that buildPackages.llvmPackages.stdenv.cc *does* compile, which seems to also just be clang. I put that in instead of buildPackages.llvmPackages.clang, and it fixed the infinite recursion but started breaking all of the compilation (command line options not recognized, for instance), which leads me to believe it's the wrong version of clang, probably from earlier in the bootstrapping process.

**Comment by Radvendii** [comment]
@vlstill you're listed as maintainer of `llvm/7/libc++abi.nix`. From searching online it seems like it should be possible to build it without `compiler-rt` (using `libunwind`?) Do you know anything about this? Or generally why we're seeing this infinite recursion.

**Comment by Radvendii** [comment]
After talking with @tomberek we've discovered that cross compilation with darwin as a target seems to just not be supported in nix (see https://github.com/NixOS/nixpkgs/pull/86223/files#r422573401). So I guess I'll close this.
