### ISSUE TITLE
gnucash fails to launch AqBanking wizard

### ISSUE THREAD

**Issue by dadada** [NixOS/nixpkgs#107213]
The AqBanking Wizard fails to launch.

**To Reproduce**
1. Launch GNUCash
2. Tools -> Online Banking Setup -> Next -> Start AqBanking Wizard
3. Nothing happens

**Expected behavior**
GNUCash launches AqBanking wizard.

**Screenshots**
![image](https://user-images.githubusercontent.com/7216772/102696990-a345f100-4232-11eb-968f-4791a4e83b67.png)

**Additional context**
[gnucash.txt](https://github.com/NixOS/nixpkgs/files/5719988/gnucash.txt)

**Notify maintainers**
@peti @domenkozar 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 21.03pre257780.e9158eca70a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(dadada): `"home-manager, nixpkgs-unstable-21.03pre258014.2c0f6135aab"`
 - channels(tim.schubert): `"home-manager"`
 - channels(root): `"nixos-21.03pre257780.e9158eca70a, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnucash
```

**Comment by dadada** [comment]
The issue seems to be related to this [upstream bug](https://github.com/flathub/org.gnucash.GnuCash/issues/37) and in my case was resolved by removing the `~/.aqbanking` directory. Closing...

**Comment by rtevans01** [comment]
> The issue seems to be related to this [upstream bug](https://github.com/flathub/org.gnucash.GnuCash/issues/37) and in my case was resolved by removing the `~/.aqbanking` directory. Closing...

That worked for me! Thanks!
