### ISSUE TITLE
Cannot use httplib2 with ansible on darwin

### ISSUE THREAD

**Issue by zeroware** [NixOS/nixpkgs#10720]
When I try to use the URI module (core ansible module) I get the following error : 

````
httplib2 is not installed
````

I'm using nix from master on OSX 10.11 with ansible 1.9.4 (from nixpkgs.ansible)
This is what I already tried without success : 

`pip install httplib2` : permission denied error
`nix-env -iA nixpkgs.python27Packages.httplib2` : problem still there.

**Comment by domenkozar** [comment]
How are you using ansible?

**Comment by domenkozar** [comment]
`nix-shell -p ansible --command "python -c 'import ansible; import httplib2'"` works for me

**Comment by domenkozar** [comment]
ping

**Comment by zeroware** [comment]
Worked with nix-shell. 
Thanks.
