### ISSUE TITLE
Per-user packages fail to install with altered user.name

### ISSUE THREAD

**Issue by DarthPJB** [NixOS/nixpkgs#107353]
If you set users.users.\<name\>.packages to include a set of per-user packages, and proceed to define a value for user.users.<name>.name, the packages will not be available on the user.

Considering this example for a configuration.nix :
```
   users.users.Foo = {
     isNormalUser = true;
     name = "Bar";
     description = "Eighty Eight";
     createHome = true;
     home = "/home/FooBar";
     packages = [ 
        pkgs.cmatrix
        ];
   };
```

You would expect nixos-rebuild to:

1. create a user named 'Bar'
2. create a home-folder named 'FooBar'
3. symlink cmatrix into the per-user folder : /etc/profiles/per-user/**Bar**/

However Instead of this, it will:

1. create a user named 'Bar'
2. create a home-folder named 'FooBar'
3. symlink cmatrix into the per-user folder : /etc/profiles/per-user/**Foo**/

As such, the per user folder **Bar** does not exist, and the user does not have the expected packages available

A brief investigation shows the error appears to be Here : 
https://github.com/NixOS/nixpkgs/blob/583470209f9d51f1c6884e0afb5a9949ac988bcd/nixos/modules/config/users-groups.nix#L583

A few lines above the ${name} attribute is used however:
https://github.com/NixOS/nixpkgs/blob/583470209f9d51f1c6884e0afb5a9949ac988bcd/nixos/modules/config/users-groups.nix#L572

This is using the attribute name (users.users.**Foo**) rather than the users.users.name ( value to create the relevant folder.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`                                              
 - host os: `Linux 5.4.80, NixOS, 20.09.2122.2fbcd0b9df9 (Nightingale)`  
 - multi-user?: `yes`                                                    
 - sandbox: `yes`                                                        
 - version: `nix-env (Nix) 2.3.9`                                        
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`     

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: users.users
# a list of nixos modules affected by the problem
module: users-groups.nix
```

**Comment by aanderse** [comment]
Great investigation work. Can you please open a PR with this change and reference this issue?

Thanks!

**Comment by nixinator** [comment]
```
   name = mkOption {
        type = types.str;
        apply = x: assert (builtins.stringLength x < 32 || abort "Username '${x}' is longer than 31 characters which is not allowed!"); x;
        description = ''
          The name of the user account. If undefined, the name of the
          attribute set will be used.
        '';
      };
```



The offending code is here.
```
    environment.profiles = [
      "$HOME/.nix-profile"
      "/etc/profiles/per-user/$USER"
    ];
```

in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/users-groups.nix

it may fix if it this is set to users.users.foo.users !!!!!!!!!!!!!!!!!!!!

    environment.profiles = [
      "$HOME/.nix-profile"
      "/etc/profiles/per-user/${user}"
    ];

however getting this ${user) into scope is tricky...

**Comment by DarthPJB** [comment]
> ```
>    name = mkOption {
>         type = types.str;
>         apply = x: assert (builtins.stringLength x < 32 || abort "Username '${x}' is longer than 31 characters which is not allowed!"); x;
>         description = ''
>           The name of the user account. If undefined, the name of the
>           attribute set will be used.
>         '';
>       };
> ```
> 
> The offending code is here.
> 
> ```
>     environment.profiles = [
>       "$HOME/.nix-profile"
>       "/etc/profiles/per-user/$USER"
>     ];
> ```
> 
> in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/users-groups.nix
> 
> it may fix if it this instead of $HOME to it's set to users.users.foo.name !!!!!!!!!!!!!!!!!!!!
> 
> ```
> environment.profiles = [
>   "$HOME/.nix-profile"
>   "/etc/profiles/per-user/${name}"
> ];
> ```
> 
> however getting this ${user) into scope is tricky... will require some nix foo..

Thank you Nixinator, I was hammering my head against this, I'm pretty green to nix.

I'll go about testing a patch shortly :+1:

**Comment by nixinator** [comment]
hey don't thank me , thank @balsoft in the freenode nix IRC channel. He kindly provided this fix. Good luck with your first Pull request... I'd be interest what you thought the contributors guide?

https://nixos.org/manual/nixpkgs/stable/#chap-quick-start

**Comment by DarthPJB** [comment]
I'm having difficulty unfortunately;

```
    environment.etc = (mapAttrs' (name: { packages, ... }: {
      name = "profiles/per-user/${user.name}";
```
This line is resolving user.name as 'Foo' rather than 'Bar' (as per my previous example)
```
    environment.profiles = [ "$HOME/.nix-profile" ]
      ++ map (user: "/etc/profiles/per-user/${user.name}")
      (builtins.attrValues cfg.users);
```
This line below resolves as 'Bar'

I've just learnt the correct process to use nix repl to query the state of these variables, which is much better than nixos-rebuilding every time :smile:

**Comment by aanderse** [comment]
@DarthPJB any progress on this?

**Comment by DarthPJB** [comment]
> @DarthPJB any progress on this?

I've had to put it on my back-burner with the start of the year.
I'm open to any suggestions; Though I haven't given up yet!

**Comment by DarthPJB** [comment]
So: here's where I am at, for anyone who might come across this.

My problem at this time is that `config.environment.etc."/profiles/per-user/<attribute-set-name>/" ` is set incorrectly to the name of the attribute set that creates the user. by the line : `name = "profiles/per-user/${user.name}";`

I'm not knowledgeable in Nix as a language enough to correctly understand how to fix this, but am actively researching it.

What i do know is that by modifying the statement that sets the `config.enviroment.profiles` variable from:
``
to:
```
    environment.profiles = [ "$HOME/.nix-profile" ]
      ++ map (user: "/etc/profiles/per-user/${user.name}")
      (builtins.attrValues cfg.users);
```
the user path is added with a value equivalent to the <attribute-set-name>.name value (rather than using the "$USER" environmental variable - plus this was suggested by someone more knowledgeable than me.

(this seems inherently more secure to me, however there may be unforeseen factors i'm not aware of; so any input here would be valued).




[All my changes so far are on my fork here](https://github.com/NixOS/nixpkgs/compare/master...DarthPJB:user.name-fix)

**Comment by nixinator** [comment]
@4z3 actually introduced per user packages , maybe they can give some advice?

**Comment by DarthPJB** [comment]
I'd love that @nixinator 

I've started figuring out the code in question, and it makes some sense to me:

`    environment.etc = (mapAttrs' (name: { packages, ... }: {
      name = "profiles/per-user/${name}";
      value.source = pkgs.buildEnv {
        name = "user-environment";
        paths = packages;
        inherit (config.environment) pathsToLink extraOutputsToInstall;
        inherit (config.system.path) ignoreCollisions postBuild;
      };
    }) (filterAttrs (_: u: u.packages != []) cfg.users));`

This uses a list of users containing per-user packages, then appears to use the name within to generate the per-user path in the line i've been looking at. I've never used mapattrs', so i'm trying to understand the scope here somewhat.

**Comment by 4z3** [comment]
The code for per-user packages wrongly uses the `config.users.users` attribute name instead of the actual user name.  This patch should fix the issue:

```diff
diff --git a/nixos/modules/config/users-groups.nix b/nixos/modules/config/users-groups.nix
index e90a7d567d4..f1503f9b392 100644
--- a/nixos/modules/config/users-groups.nix
+++ b/nixos/modules/config/users-groups.nix
@@ -568,7 +568,7 @@ in {
     # Install all the user shells
     environment.systemPackages = systemShells;
 
-    environment.etc = (mapAttrs' (name: { packages, ... }: {
+    environment.etc = (mapAttrs' (_: { packages, name, ... }: {
       name = "profiles/per-user/${name}";
       value.source = pkgs.buildEnv {
         name = "user-environment";
```

**Comment by DarthPJB** [comment]
> The code for per-user packages wrongly uses the `config.users.users` attribute name instead of the actual user name. This patch should fix the issue:
> 
> ```diff
> diff --git a/nixos/modules/config/users-groups.nix b/nixos/modules/config/users-groups.nix
> index e90a7d567d4..f1503f9b392 100644
> --- a/nixos/modules/config/users-groups.nix
> +++ b/nixos/modules/config/users-groups.nix
> @@ -568,7 +568,7 @@ in {
>      # Install all the user shells
>      environment.systemPackages = systemShells;
>  
> -    environment.etc = (mapAttrs' (name: { packages, ... }: {
> +    environment.etc = (mapAttrs' (_: { packages, name, ... }: {
>        name = "profiles/per-user/${name}";
>        value.source = pkgs.buildEnv {
>          name = "user-environment";
> ```

Wow, that is; absolutely amazing to me - learning

Thank you so much @4z3
