### ISSUE TITLE
Darktable not recognizing Sony A7 III camera

### ISSUE THREAD

**Issue by cnnrro** [NixOS/nixpkgs#107304]
**Describe the bug**

Darktable is unable to apply lens corrections for Sony a7 iii. (This camera model ILCE-7M3 does not appear in the camera model dropdown for the module.)

This is likely due to an out-of-date database for Lensfun (as was seen in #20209).

It may be resolved by fixing #99009.

**To Reproduce**

1. Download any image from https://drive.google.com/drive/folders/1QEHecPmet47UQiDhc7cyX1gEwyeVmUq0
2. Import the image into Darktable.
3. Look at the "lens correction" module.
4. The lens is being correctly detected, but the camera is unavailable.

**Expected behavior**

The camera model should be automatically detected by Darktable, as it is supported by the latest version of the Lensfun database.

**Screenshots**

![camera-not-found](https://user-images.githubusercontent.com/19591370/102734256-64d13480-430d-11eb-836b-1646022198bd.png)

**Additional context**

This camera is supported by Lensfun as noted on the [Lensfun coverage page](https://wilson.bronger.org/lensfun_coverage.html) and by Darktable as noted on the [Darktable camera support page](https://www.darktable.org/resources/camera-support/) (look for Sony ILCE-7M3).

**Notify maintainers**

Lensfun: @Enzime

Darktable: @goibhniu @flosse @mrVanDalo

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.83, NixOS, 20.09.2331.7d57790bc12 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(connor): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/q6dlb2q3lfbs0wagf8vs4930hmpy1iyb-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - lensfun
    - darktable
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
dup of https://github.com/NixOS/nixpkgs/issues/99009.
