### ISSUE TITLE
Add some missing Vim packages

### ISSUE THREAD

**Issue by ruler501** [NixOS/nixpkgs#107356]
**Project description**
Several vim plugins that don't require extra configuration to install with VimPlug.
The requested plugins can be viewed in https://github.com/NixOS/nixpkgs/commit/73f1561145ecd43ca0a2e1f4d3d8b9aa249f7b52 I don't have the setup to test it at the moment or I'd create a PR for it instead.

I'd also appreciate support for 

whonore/Coqtail which I haven't tested out with VimPlug yet so am not sure if it requires additional configuration
iamcco/markdown-preview.nvim which requires `cd app & yarn install` to build it with VimPlug.

**Comment by matthiasbeyer** [comment]
What would you suggest to test them?

**Comment by ruler501** [comment]
I'm just not sure what the requirements are for testing to get things added to nixpkgs. I've tested all the ones in the commit and only had issues with the nerd-tree git plugin so far with a manual implementation in my `home.nix`. I won't be able to test anymore until next week though.

**Comment by teto** [comment]
you can maintain an out of tree overlay with the plugins you use https://github.com/NixOS/nixpkgs/pull/126633 . Of course you can also upstream those. In both cases, I think we can close this.
