### ISSUE TITLE
[20.09] 3-minute delay at boot waiting for wpa_supplicant to restart; may also result in failure to configure the wireless interface

### ISSUE THREAD

**Issue by mebubo** [NixOS/nixpkgs#107341]
Since #104722 (backported to 20.09 as 645b8a3749d683181736c7ced2a77a5bcd01942a), the boot process hangs for 3 minutes on this message:

```
[***   ] A start job is running for Wait for udev To Complete Device Initialization
```

Even a minimal configuration with just this:

```
  networking.wireless.networks.<ssid>.psk = <psk>;
```

as the only network-relevant config displays the same behavior.

I got the same delay + message while booting a recent nixos-minimal-20.09 iso.

In addition to the delay, with `networking.useNetworkd = true;`, the wireless interface **is never configured at all** it seems.

I haven't yet tried with nixos-unstable.

Reverting 645b8a3749d683181736c7ced2a77a5bcd01942a fixes the issue.

Ping @rnhmjoj @doronbehar

**Comment by mebubo** [comment]
Relevant bits of the log

```
Dec 21 19:52:17 nixos systemd-udevd[521]: wlan0: Spawned process '/run/current-system/systemd/bin/systemctl restart wpa_supplicant.service' [693] is taking longer than 59s to complete
Dec 21 19:52:17 nixos systemd-udevd[497]: wlan0: Worker [521] processing SEQNUM=2598 is taking a long time
Dec 21 19:53:14 nixos systemd[1]: systemd-udev-settle.service: Main process exited, code=exited, status=1/FAILURE
Dec 21 19:53:14 nixos systemd[1]: systemd-udev-settle.service: Failed with result 'exit-code'.
Dec 21 19:53:14 nixos systemd[1]: Failed to start Wait for udev To Complete Device Initialization.
Dec 21 19:53:14 nixos systemd[1]: Dependency failed for Network Service.
Dec 21 19:53:14 nixos systemd[1]: Dependency failed for Wait for Network to be Configured.
Dec 21 19:53:14 nixos systemd[1]: systemd-networkd-wait-online.service: Job systemd-networkd-wait-online.service/start failed with result 'dependency'.
Dec 21 19:53:14 nixos systemd[1]: Dependency failed for Extra networking commands..

Dec 21 19:53:14 nixos systemd[1]: network-local-commands.service: Job network-local-commands.service/start failed with result 'dependency'.
Dec 21 19:53:14 nixos systemd[1]: systemd-networkd.service: Job systemd-networkd.service/start failed with result 'dependency'.
Dec 21 19:53:14 nixos systemd[1]: systemd-udev-settle.service: Consumed 7.418s CPU time, no IP traffic.

Dec 21 19:53:14 nixos systemd[1]: Starting Wait for udev To Complete Device Initialization...
Dec 21 19:53:14 nixos systemd[1]: Condition check resulted in Update is Completed being skipped.
Dec 21 19:53:14 nixos udevadm[699]: systemd-udev-settle.service is deprecated. Please fix systemd-networkd.service not to pull it in.
Dec 21 19:54:17 nixos systemd-udevd[521]: wlan0: Spawned process '/run/current-system/systemd/bin/systemctl restart wpa_supplicant.service' [693] timed out after 2min 59s, killing
Dec 21 19:54:17 nixos systemd-udevd[497]: wlan0: Worker [521] processing SEQNUM=2598 killed
Dec 21 19:54:17 nixos systemd-udevd[497]: Worker [521] terminated by signal 9 (KILL)
Dec 21 19:54:17 nixos systemd-udevd[497]: wlan0: Worker [521] failed
Dec 21 19:54:17 nixos systemd[1]: Finished Wait for udev To Complete Device Initialization.
```

**Comment by rnhmjoj** [comment]
I think I have an idea but I don't know why it's hanging. Can you try setting this?
```
systemd.services.systemd-udev-settle.enable = false;
```

**Comment by rnhmjoj** [comment]
It looks like there is a deadlock: udev is waiting for the `systemctl restart wpa_supplicant` command to complete, but this one is waiting for udev itself to settle.

The most likely cause is dhcpcd wanting [systemd-udev-settle](https://github.com/NixOS/nixpkgs/issues/73095).
This should really be removed because it's deprecated and always a troublemaker. For 20.09 I can only revert the commit, there is no other way around.

**Comment by rnhmjoj** [comment]
It's not related to wpa_supplicant in particular. It looks like having any service waiting for udev-settle will hang a `systemctl restart` indefinitely.

**Comment by rnhmjoj** [comment]
I've reverted both master (9f52d1f2342) and release-20.09 (9d6d90666e7) for now.

**Comment by knuton** [comment]
Seeing that https://github.com/NixOS/nixpkgs/pull/107382 has been merged, can https://github.com/NixOS/nixpkgs/pull/104722 be applied again or is there a different plan now?

**Comment by rnhmjoj** [comment]
No, unless systemd-udev-settle is remove from *every* service, there is still the possibility of a deadlock like this.
There are a couple of service that still requires it: prominently gnome and zfs. There's nothing I can do besides waiting for upstream to fix the issue.
