### ISSUE TITLE
[20.09] telegram-desktop crashes on startup on wayland (GNOME)

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#107367]
**Describe the bug**
When run under Gnome shell with Wayland, telegram segfaults immediately when starting.

```text
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?
fish: “telegram-desktop&” terminated by signal SIGSEGV (Address boundary error)
```

**To Reproduce**
1. Start a Gnome wayland session
2. Run ``telegram-desktop`` from ``pkgs.tdesktop``

Using ``QT_QPA_PLATFORM=wayland`` works around the problem.
NixOS 20.09.2338.3d2d8f281a2.

**Expected behavior**
Telegram starts up correctly.

**Notify maintainers**
@primeos @abbradar 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [tdesktop]
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment]
Most likely a GNOME or Telegram-Desktop issue, I don't think there's anything we can do here (apart from finding a workaround but I don't use GNOME so I cannot help with that).

Works for me on Sway, maybe because I don't get the following warning:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by sbourdeauducq** [comment]
Well, this used to work on 20.09 - something was updated and introduced this regression.

**Comment by sbourdeauducq** [comment]
Seems to be https://github.com/telegramdesktop/tdesktop/issues/8506

**Comment by sbourdeauducq** [comment]
>  I don't think there's anything we can do here (apart from finding a workaround but I don't use GNOME so I cannot help with that).

Actually there is, you could backport the Telegram update from nixpkgs-unstable which fixes this problem.

**Comment by primeos** [comment]
> Well, this used to work on 20.09 - something was updated and introduced this regression.

Yes, I only meant that this is likely an upstream issue and not a Nixpkgs specific packaging issue.
I also missed that this is on NixOS 20.09.

> Actually there is, you could backport the Telegram update from nixpkgs-unstable which fixes this problem.

No idea which update fixes the problem though - the issue doesn't seem to provide that information - and I have no Telegram-Desktop test setup for NixOS 20.09. Feel free to submit a PR, we could e.g. backport 2.3.0 for #102904 anyway (we only lack a tester/maintainer for 20.09). I can also create the PR if you want but someone would need to test it.

**Comment by srid** [comment]
What I see when launching Telegram on GNOME wayland:

```
[nix-shell:~/nix-config]$ telegram-desktop 

(process:9508): Telegram-WARNING **: 14:01:31.120: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 14:01:31.121: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 14:01:31.121: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).

(process:9508): Telegram-WARNING **: 14:01:31.121: Application was built without embedded fonts, this may lead to font issues.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

**Comment by matthiasbeyer** [comment]
Might be related to #137659 though this other issue is on X.

**Comment by primeos** [comment]
Let's close this issue in favor of #137659 then as NixOS 20.09 is not supported anymore and I'm not sure if this problem here still persists.
