### ISSUE TITLE
Mesa 20.3.1

### ISSUE THREAD

**Issue by schvabodka-man** [NixOS/nixpkgs#107339]
###### Checklist

There are currently new mesa version. It would be nice to see it in nixos unstable

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: mesa

current version: 20.2.4
desired version: 20.3.1

###### Notify maintainers

maintainers: @primeos 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by xaverdh** [comment]
actually the update went in with https://github.com/NixOS/nixpkgs/pull/105817 a few days ago, but the `unstable` channel is currently blocked due to `systemd` issues..

**Comment by primeos** [comment]
Not sure why the PR didn't appear in the GH search but the update was already merged into staging like @xaverdh already replied. I guess we can close this issue then :)

PS: If you need some Mesa updates faster you could use the internal NixOS option `hardware.opengl.package` and point that to the newer `mesa.drivers` (from a different "channel", using an overlay, etc.). That way you don't need to rebuild you whole system.
