### ISSUE TITLE
servant: override use fixed (stale) hash for servant-sphinx-documentation

### ISSUE THREAD

**Issue by quyse** [NixOS/nixpkgs#107455]
**Describe the bug**
Currently building `haskellPackages.servant` without using binary substitutes results in error:
```
hash mismatch in fixed-output derivation '/nix/store/p7ydj1qvdwjy4mlzhfxj00rjyvr6q00i-source':
  wanted: sha256:0xk3czk3jhqjxhy0g8r2248m8yxgvmqhgn955k92z0h7p02lfs89
  got:    sha256:0gkgaajky4mqhywchgxcl2hlx0x5m07g5b06i3i56dn4ig4c69f7
cannot build derivation '/nix/store/bi55bjz7n9k2xwqklyb4zmwpq47lzksh-servant-sphinx-documentation-0.18.2.drv': 1 dependencies couldn't be built
```

**To Reproduce**
Build `haskellPackages.servant` while *not* using substitutes and *not* having cached the mentioned fixed-hash derivation already.

**Expected behavior**
Build should succeed, sources should be able to fetch.

**Additional context**

`pkgs/development/haskell-modules/configuration-common.nix` has an override for `servant` docs:
```
  servant =
    let
      ver = super.servant.version;
      docs = pkgs.stdenv.mkDerivation {
        name = "servant-sphinx-documentation-${ver}";
        src = "${pkgs.fetchFromGitHub {
          owner = "haskell-servant";
          repo = "servant";
          rev = "v${ver}";
          sha256 = "0xk3czk3jhqjxhy0g8r2248m8yxgvmqhgn955k92z0h7p02lfs89";
        }}/doc";
...
```

It uses fixed `sha256` but non-fixed `ver = super.servant.version`. It seems the hash has not been updated in a while, in current master `ver = "0.18.2"`, but the hash in fact corresponds to `ver = "0.16.2"`.

I could just post a PR to update the hash, and I can see it was fixed before, for example https://github.com/NixOS/nixpkgs/pull/44948, but it looks like as it is, the override will break every time servant version is bumped, and in a mostly invisible manner to everyone (once it's cached using hash, it stays even if it cannot be fetched anymore by `rev`). Perhaps there is a better way to write it? (I did not really dig into why this override is needed at all.)

**Notify maintainers**
@peti

**Comment by peti** [comment]
I am afraid I don't know why that override is necessary either. Assuming that it *is* necessary, I don't see a better solution than updating that hash regularly. It kinda sucks, but I don't see any alternative.

**Comment by cdepillabout** [comment]
I sent a PR where I suggest that we completely drop this documentation generation: https://github.com/NixOS/nixpkgs/pull/107858.  My arguments are in https://github.com/NixOS/nixpkgs/pull/107858#issuecomment-751930363.

**Comment by quyse** [comment]
The override has been removed via the PR above, the issue should be resolved now, thanks.
