### ISSUE TITLE
lib.generators.toINI cannot generate files without "sections"

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#107491]
**Describe the bug**

According to [this](https://en.wikipedia.org/wiki/INI_file#Sections) `ini` files don't **need** sections.

**To Reproduce**
1. `nix repl`
2. `pkgs.lib.generators.toINI {} { foo = "bar"; }` -> `error: value is a string while a set was expected, at /home/aaron/nixpkgs/lib/attrsets.nix:234:39`

**Additional context**

There are at least [a](https://github.com/NixOS/nixpkgs/pull/97553) [few](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/nixos/modules/services/misc/gitea.nix#L12..L17) places that could benefit from `toINI` accepting an attribute set like this:

```
{
  keyWithoutSection = "foo";
  section = {
    keyWithSection = "bar";
  };
```

**Notify maintainers**

ping @Infinisil in case you're feeling generous / this problem appeals to you :heart:

**Comment by Infinisil** [comment]
This looks like https://en.wikipedia.org/wiki/INI_file#Global_properties instead. Sounds like something worth implementing

**Comment by aanderse** [comment]
Yeah. Interested? :heart:

**Comment by Infinisil** [comment]
Hmm, with your above suggestion, what if one wants a file like
```ini
global=value

[global]
foo=10
```

This can't be encoded with
```nix
{
  global = "value"
  global.foo = 10;
}
```

Because that's invalid Nix

Or would that be invalid INI too?

**Comment by Infinisil** [comment]
Works in a [Haskell INI library](https://hackage.haskell.org/package/ini):
```haskell
ghci> parseIni "global=10\n[global]foo=10"
Right (Ini {iniSections = fromList [("global",[("foo","10")])], iniGlobals = [("global","10")]})
```

**Comment by aanderse** [comment]
Oh right, I suppose that couldn't be encoded with `nix`. I think that's probably just a limitation we might need to live with. I have no idea how many applications might utilize something like that 🤔

**Comment by xaverdh** [comment]
You could add a namespace for the "global" config, such that say

```nix
toINI { globalNamespace = top; } { top.global = "value"; global.foo = 10; }
```
would produce
```ini
global=value

[global]
foo=10
```
and `toINI {}` (or `toINI { globalNamespace = null; }` will give you the old behavior..

**Comment by aanderse** [comment]
Hmm... that could work.

I think we should try to cover the majority of use cases (no section with the same name as a global key) and people who fall outside of this can continue to write their own solution (as is currently the situation). If we start getting too complicated it makes it harder for module authors.

My opinion isn't too strong, though.

**Comment by Infinisil** [comment]
I am conflicted. I think the `globalNamespace` thing is nice and general, but it's not very convenient to use (requires people to know what the global namespace is called in their case). The `{ keyWithoutSection = "foo"; }` idea is much more convenient, but fails miserably if there's the above-mentioned conflict.

Maybe we could have a mixed solution: The `ini` option type accepts the `{ keyWithoutSection = "foo"; section.keyWithSection = "bar"; }` syntax, but internally it turns it into `{ global.keyWithoutSection = "foo"; sections.section.keyWithSection = "bar"; }` and passes the global section as a separate argument to `toINI`. This then allows encoding
```ini
global=value

[global]
foo=10
```

with

```nix
lib.mkMerge [
  { global = "value"; }
  { global.foo = 10; }
]
```

The disadvantage of this however is that the evaluation result of the `ini`-type option won't match the definitions. So e.g. you'd have to use `config.services.myService.settings.sections.section.keyWithSection` to access a value set to `config.services.myService.settings.section.keyWithSection`. Though this might be fine, it's not a deal-breaker imo.

**Comment by aanderse** [comment]
I think adding a layer of indirection is a bad idea here. It makes things less than obvious and will likely cause problems in the scenario you highlighted when users try to access values from `settings`.

**Comment by Infinisil** [comment]
Hmm yeah. Okay what if we do the thing I suggested, but we use @xaverdh's `globalNamespace` idea. So essentially this would turn

```nix
lib.mkMerge [
  { global = "value"; }
  { global.foo = 10; }
]
```

into
```nix
{
  globalSection.global = "value";
  global.foo = 10;
}
```

Which would then both be accessible as `config.services.myService.settings` and be passed to `toINI { globalNamespace = "globalSection"; }` to generate

```ini
global=value

[global]
foo=10
```

The only problems here are that if the user wants to access values from the global section, they need to know the `globalNamespace` value the service module uses. And that the service module needs to choose a `globalNamespace` that's not used by any settings.

We could fix these problems by making the global section be `_global` by default, which is fairly easy to remember and shouldn't conflict with any actual sections.

**Comment by Profpatsch** [comment]
https://github.com/NixOS/nixpkgs/pull/118925#issuecomment-821112723

**Comment by PartemImperium** [comment]
Its not ideal and kinda feels like a hack but if you don't need support for sections at all you can use generators.toKeyValue. toINI uses that inside a section. But if you need support for sections in the same file as section-less we would have to implement one of the above suggestions.

**Comment by Profpatsch** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/164088

**Comment by tim-tx** [comment]
PR to wrap `lib.generators.toINIWithGlobalSection` in `pkgs.formats.ini`: https://github.com/NixOS/nixpkgs/pull/201569

**Comment by AndersonTorres** [comment]
Re: https://github.com/NixOS/nixpkgs/pull/201686

**Comment by tim-tx** [comment]
Re: #228051

**Comment by infinisil** [comment]
Thanks to @benaryorg and @tim-tx this is finally fully implemented with `pkgs.formats.iniWithGlobalSection` from https://github.com/NixOS/nixpkgs/pull/286399!
