### ISSUE TITLE
saned crashes on scan

### ISSUE THREAD

**Issue by cyplo** [NixOS/nixpkgs#107422]
**Describe the bug**
getting `sh: awk: command not found` when trying to scan over network (scanning from the `client`, scanner device connected to `server` via usb)

**To Reproduce**

server config:
```
hardware.sane = {
    enable = true;
    extraBackends = with pkgs; [ epkowa utsushi sane-airscan ];
    snapshot = true;
  };

  services.udev.packages = [ pkgs.utsushi ];

  services.saned = {
    enable = true;
    extraConfig = ''
      10.0.0.0/24
      XXXX
      XXXX
      [XXXXX::1]/60
    '';
  };
```

client config:
```
  hardware.sane = {
    enable = true;
    netConf = ''
      XXXXX
    '';
    snapshot = true;
    extraBackends = with pkgs; [ sane-airscan utsushi ];
  };
```

on the `client`:
2. `nix run nixpkgs.simple-scan -c simple-scan` 
3.  choose the network scanner
4. press `scan`
5. observe: `simple-scan` stops scanning immediately, server logs have an entry:  `sh: awk: command not found` from `saned`

**Notify maintainers**

Guessing here, looking at the commit log for the service definition, apologies for pinging a lot of people:
@nckx @abbradar @ttuegel @zimbatm @shlevy @andir 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

server (managed via nixpkgs):
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.03.2882.51d115ac89d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

client:
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.8.16, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(cyryl): `"home-manager, unstable-21.03pre250162.34ad166a830"`
 - channels(root): `"nixos-20.09.2344.a3a3dda3bac"`
 - nixpkgs: `/nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz`
 ```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
- hardware.sane
- services.saned
- 
# a list of nixos modules affected by the problem
module:
- services/hardware/sane.nix
```

**Comment by Artturin** [comment]
Please test #131147

**Comment by cyplo** [comment]
nice ! will do in few days as I'm moving house :)

**Comment by cyplo** [comment]
Hi @Artturin, just tested it now and it works very well !

**Comment by Artturin** [comment]
approve the pr
