### ISSUE TITLE
Fractal broken on darwin

### ISSUE THREAD

**Issue by mjlbach** [NixOS/nixpkgs#107463]
**Project description**
Fractal is a Matrix messaging app for GNOME written in Rust. Its interface is optimized for collaboration in large groups, such as free software projects. It's currently pacakged for linux, but was recently marked broken in https://github.com/NixOS/nixpkgs/pull/99195. 

I've implemented some quick hacks on libhandy and gspell to address the build failures here https://github.com/mjlbach/nixpkgs/tree/fix_fractal_macos, but the package still  fails.

To reproduce
1. Clone  https://github.com/mjlbach/nixpkgs/tree/fix_fractal_macos
2. nix develop --impure ".#fractal"
3. unpackPhase
4. cd source 
5. cargo build

```
error: failed to run custom build command for `gettext-sys v0.19.9 (https://github.com/danigm/gettext-rs?branch=no-gettext#61938b9f)`

Caused by:
  process didn't exit successfully: `/Users/michael/Repositories/nix/nixpkgs/source/target/release/build/gettext-sys-72a8eee66fcc9bd6/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=framework=CoreFoundation
  cargo:rustc-link-lib=dylib=iconv
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_DIR
  cargo:rerun-if-env-changed=GETTEXT_DIR
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_BIN_DIR
  cargo:rerun-if-env-changed=GETTEXT_BIN_DIR
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_LIB_DIR
  cargo:rerun-if-env-changed=GETTEXT_LIB_DIR
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_GETTEXT_INCLUDE_DIR
  cargo:rerun-if-env-changed=GETTEXT_INCLUDE_DIR
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-apple-darwin")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = Some("clang")
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  running: "tar" "xJf" "/Users/michael/Repositories/nix/nixpkgs/fractal-4.4.0-vendor.tar.gz/gettext-sys/gettext-0.19.8.1.tar.xz" "--strip-components" "1"

  --- stderr
  tar (child): /Users/michael/Repositories/nix/nixpkgs/fractal-4.4.0-vendor.tar.gz/gettext-sys/gettext-0.19.8.1.tar.xz: Cannot open: No such file or directory
  tar (child): Error is not recoverable: exiting now
  tar: Child returned status 2
  tar: Error is not recoverable: exiting now
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /Users/michael/Repositories/nix/nixpkgs/fractal-4.4.0-vendor.tar.gz/gettext-sys/build.rs:251:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

To continue (to a very long error message):

6. download https://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz and move to nixpkgs/fractal-4.4.0-vendor.tar.gz/gettext-sys/gettext-0.19.8.1.tar.xz
7. cargo build

cc @berbiche (if you're still interested in this)

**Metadata**

* source URL: https://gitlab.gnome.org/GNOME/fractal
* platforms: unix

**Comment by berbiche** [comment]
Hi, I'm not using my Darwin machine much anymore, so I don't think I will invest the time in fixing fractal for Darwin.

**Comment by wegank** [comment]
It actually suffices to put `GETTEXT_DIR = "${gettext}/lib";` for fractal to build on Darwin:

```
$ result/bin/fractal -V    
fractal 4.4.0
```

However, it's still kind of broken: the interface won't show up.
