### ISSUE TITLE
prometheus-json-exporter: unstable-2017-10-06 -> 0.2.0

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#107587]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

current version: unstable-2017-10-06
desired version: 0.2.0

###### Notify maintainers

maintainers: @WilliButz

**Comment by matthiasbeyer** [comment]
An option in the service definition to overwrite the package would be nice, too! :smile:

**Comment by Ma27** [comment]
> An option in the service definition to overwrite the package would be nice, too!

Why is this needed? `.package`-options are usually implemented if modifying the package in question with an overlay is a bad idea because it would mean that a lot of leaf-packages would require a rebuild as well. An example for that would be `systemd`.

**Comment by matthiasbeyer** [comment]
Ah, okay.

**Comment by matthiasbeyer** [comment]
@WilliButz could you please update this package?

**Comment by WilliButz** [comment]
Oh sure, thank you for the ping :)
