### ISSUE TITLE
Plasma's Breeze icon theme does not work in some applications

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#10758]
When Plasma's new Breeze icon theme selected, some applications have missing icons. Applications with custom icons seem to be affected the most, but some applications are also missing theme icons. The missing icons *are* present on the system, but they are not displayed. Which icons are missing seems to vary at random. The default Oxygen icon theme does not have this problem.

Affects Plasma 5.4.2.

Waiting for #10731.

**Comment by vcunat** [comment]
These are all KDE apps, not glib-based ones, right?

**Comment by ttuegel** [comment]
It affects (at least) Firefox, too. I think there is something wrong with the theme itself.

**Comment by ttuegel** [comment]
This is still present in Plasma 5.5.0. I suspect it has something to do with Breeze being an SVG-only theme, but I don't really have any evidence to support that. It's interesting to note that the desktop and Plasmoids aren't missing any icons, it's only applications. This is not really a critical bug because the Oxygen icons still work, but it's quite annoying.

**Comment by ttuegel** [comment]
It *is* an SVG issue. Installing `qtsvg` into the environment provides a plugin, and then all Qt applications can load the Breeze icons. Now, I need to figure out the equivalent for GTK 2 and GTK 3.

**Comment by ttuegel** [comment]
It looks like I need to add `librsvg` to the `loaders.cache` for `gdk_pixbuf`. @edolstra Is it possible to do this at runtime somehow?
