### ISSUE TITLE
When specifying leaveDotGit within fetchFromGitHub, it fails with an error unless fetchSubmodules is also set.

### ISSUE THREAD

**Issue by OmnipotentEntity** [NixOS/nixpkgs#107556]
**Describe the bug**
When attempting to `fetchFromGitHub` with the `leaveDotGit` option set, the fetcher within `/pkgs/build-support/fetchgithub/default.nix` will be [erroneously set to `fetchzip`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgithub/default.nix#L14) unless the option `fetchSubmodules` is also set.

**To Reproduce**
1. Run the following derivation (not picking on nix-script, it was just a handy, small example):
2. 
```
{ stdenv, haskellPackages, fetchFromGitHub }:

stdenv.mkDerivation {
  pname = "nix-script";
  version = "2020-03-23";

  src  = fetchFromGitHub {
    owner  = "bennofs";
    repo   = "nix-script";
    rev    = "7706b45429ff22c35bab575734feb2926bf8840b";
    sha256 = "0yiqljamcj9x8z801bwj7r30sskrwv4rm6sdf39j83jqql1fyq7y";
    leaveDotGit = true;
    # fetchSubmodules = true; # Uncomment for it to function
  };

  buildInputs  = [
    (haskellPackages.ghcWithPackages (hs: with hs; [ posix-escape ]))
  ];

  phases = [ "buildPhase" "installPhase" "fixupPhase" ];
  buildPhase = ''
    mkdir -p $out/bin
    ghc -O2 $src/nix-script.hs -o $out/bin/nix-script -odir . -hidir .
  '';
  installPhase = ''
    ln -s $out/bin/nix-script $out/bin/nix-scripti
  '';

  meta = with stdenv.lib; {
    description = "A shebang for running inside nix-shell";
    homepage    = "https://github.com/bennofs/nix-script";
    license     = licenses.bsd3;
    maintainers = with maintainers; [ bennofs rnhmjoj ];
    platforms   = haskellPackages.ghc.meta.platforms;
  };
}
```

**Expected behavior**
`leaveDotGit` should force `fetchgit` to be used as well.

**Notify maintainers**
@matthewbauer 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.81, NixOS, 20.09.2161.214e71a78a9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2161.214e71a78a9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by hmenke** [comment]
Note that `leaveDotGit` is (hopefully) on its way out anyway: https://github.com/NixOS/nixpkgs/issues/8567

**Comment by OmnipotentEntity** [comment]
The reason why I noticed it is because I was in the process of adding leaveDotGit to a package that (newly) requires this ability to extract the git hash during compilation.  However, if you know of a way to handle this better I'm all ears. (Up to this point, I have just been disabling the inclusion of the git hash from the compile.  But I can't just fake the hash or exclude it anymore, due to server verification.)

**Comment by hmenke** [comment]
[According to edolstra](https://github.com/NixOS/nixpkgs/issues/8567#issuecomment-133409465) the preferred solution is:

> For packages that really need `.git`, the solution is to just tar the entire tree and put it some place where it can be downloaded using `fetchurl`.

I was in the same situation previously and just [ended up fixing the build system upstream](https://github.com/gnuplot/gnuplot/commit/ef315e6f148bb3144726246cbf396aad53e3a000) to build without git.

**Comment by OmnipotentEntity** [comment]
Unfortunately, I can't seamlessly workaround needing `.git` in this case.  Given I need the commit hash for a given tag.  My options are, near as I can tell:

1. Manually upload the code to one of my personal websites or to my fork of the project for every release of the main code (Not easily verifiable that I haven't changed anything, extra steps in updating, I'm now a major point of failure)
2. Patch the CMake to not check with git, and provide the revision manually via a nix variable for every update (brittle, and I doubt the author would be happy about that, considering that he's going out of his way to ensure that the code that contributes to the project is not changed in someway).
3. Just use leaveDotGit.

**Comment by hmenke** [comment]
I also thought that 1. and 2. were infeasible but when the hash had changed for the third time within a few weeks I decided to just try and ask whether the maintainer would accept a patch to build without git.  The case I made in this situation was “building from the release tarball I downloaded via GitHub fails”.  That's probably better than saying “my exotic package manager can't deal with non-determinisitic `.git` directories” which might fall on deaf ears.

**Comment by OmnipotentEntity** [comment]
So for background, the package in question is [katago](https://github.com/NixOS/nixpkgs/blob/197ddbced2ae72efbef0f5f8838a7ad3fbd986eb/pkgs/games/katago/default.nix).  Recently, katago has begun allowing users to contribute training games to the project, so as to develop stronger and more robust go AI.  One of the checks that they implement, as a sanity check to ensure you're not accidentally or intentionally sending bad training data, is they check your git revision at compile time and compile the hash and whether or not the tree is marked as dirty into the client.

They've had an option to [compile without the git revision](https://github.com/NixOS/nixpkgs/blob/197ddbced2ae72efbef0f5f8838a7ad3fbd986eb/pkgs/games/katago/default.nix#L77) since before I initially packaged katago for nix, and I've been using that option up until now for all builds.  However, if you want to contribute to training, this is not an option because of the server side check.

I've actually already implemented both options 2 and 3.  (I implemented 2 before I knew that leaveDotGit existed.)  So either way is OK by me.  I've had 2 people tell me leaveDotGit was ok in this case, and 2 people tell me it's a horrible idea, and I'm sure this will be re-litigated whenever katago releases v1.7.1 and I make a PR.

**Comment by rnhmjoj** [comment]
> Patch the CMake to not check with git, and provide the revision manually via a nix variable for every update (brittle, and I doubt the author would be happy about that, considering that he's going out of his way to ensure that the code that contributes to the project is not changed in someway).

How does it detect the revision? It's likely calling `git rev-parse HEAD` or something like it.
The easier option, in that case, it to simply put a fake git command in the build inputs that just prints the current revision. Incidentally, I did this only a few days ago, ypou can take a look here: [coreboot.nix#L65](https://maxwell.ydns.eu/git/rnhmjoj/nixboot/src/branch/master/coreboot.nix#L65).

**Comment by OmnipotentEntity** [comment]
The command is:

`git describe --match=DummyTagNotExisting --always --abbrev=40 --dirty`

Cool idea.  I could potentially do the fake git as shell script thing.  But I still have the problem of needing the revision ID and not having an easy way to get that from the version information.

**Comment by rnhmjoj** [comment]
> But I still have the problem of needing the revision ID and not having an easy way to get that from the version information.

If you don't want to put it manually at each updated, you could do
```
(builtins.fetchGit { url = "https://github.com/lightvector/KataGo"; ref = "v1.7.0"; }).rev 
```
