### ISSUE TITLE
Vim-Plugin YouCompleteMe unavailable: Request Vim Compiled with python (3.6.0+) support

### ISSUE THREAD

**Issue by bear5-lab** [NixOS/nixpkgs#107548]
**Describe the bug**
I am upgrading the 20.03 to 20.09, the YouCompleteMe vim-plugin seems to have some issues. When using vim to edit files, it will pop message:
**YouCompleteMe unavailable: requires Vim compiled with Python (3.6.0+) support.**
, I tried to change the python with python36, but it does not seem to work.

I am using vim-configurable, and vim ---version outputs:
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 01 1980 00:00:00)
Included patches: 1-1522
Compiled by nixbld
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "
/nix/store/fapbjg2ifazx385pyixdlz2mkhx8szn7-vim_configurable-8.2.1522/share/vim
"
Compilation: see nix-store --read-log /nix/store/fapbjg2ifazx385pyixdlz2mkhx8szn7-vim_configurable-8.2.1522
Linking: see nix-store --read-log /nix/store/fapbjg2ifazx385pyixdlz2mkhx8szn7-vim_configurable-8.2.1522
 

python --version outputs:
Python 3.6.12

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
these paths will be fetched (0.12 MiB download, 0.51 MiB unpacked):
  /nix/store/ajib0wv150ah6nqbkn5b5kwmqldk368y-patchelf-0.12
  /nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev
  /nix/store/f95jkch26wxmqd076bcm976qrn7ml46i-stdenv-linux
copying path '/nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ajib0wv150ah6nqbkn5b5kwmqldk368y-patchelf-0.12' from 'https://cache.nixos.org'...
copying path '/nix/store/f95jkch26wxmqd076bcm976qrn7ml46i-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.83, NixOS, 20.09.2290.647cc06986c (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2290.647cc06986c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 -
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bear5-lab** [comment]
@jagajaga 
@MarcWeber

**Comment by OPNA2608** [comment]
This appears to be fixed on `master` through https://github.com/NixOS/nixpkgs/commit/576a9287941b279fff9684013266bf89aeb68a02. Should that commit be backported to stable @dasJ?

> I tried to change the python with python36, but it does not seem to work.

What have you tried? This works for me:
```nix
(vim_configurable.override {
  python = pkgs.python3;
}).customize {
  # …
}
```

**Comment by dasJ** [comment]
Oof, I'd rather not have that backported since it breaks Python 2 plugins (if anyone uses them) and while doing so between releases is okay IMO, it's hard to reason that in a backport.
