### ISSUE TITLE
Package Request: InfinityGhost/OpenTabletDriver

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#107544]
**Project description**

OpenTabletDriver is an open source, cross platform, user mode tablet driver. The goal of OpenTabletDriver is to be cross platform as possible with the highest compatibility in an easily configurable graphical user interface.

It supports multiple tablets that are badly supported in Linux. Even for tablets already supported by other means (i.e.: `libinput` or `xf86-input-wacom`), OpenTabletDriver offers a graphical interface, plugins and more customization.

List of supported tablets: https://github.com/InfinityGhost/OpenTabletDriver/projects/4

**Metadata**

* homepage URL: https://github.com/InfinityGhost/OpenTabletDriver
* source URL: https://github.com/InfinityGhost/OpenTabletDriver
* license: LGPLv3
* platforms: Linux, Darwin

**Comment by thiagokokada** [comment]
I tried to create a package but I can't wrap my head on how to build a .NET 5 application. Trying to follow https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/osu-lazer/default.nix just made me more and more confused.

If it helps, here it is the `PKGBUILD` from Arch Linux: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opentabletdriver-git

**Comment by cidkidnix** [comment]
I have a older OTD package in my nix overlay https://github.com/cidkidnix/nix-overlay, I just currently don't have the time to mess with it, I have a WIP .NET 5 package on my local machine that I could upload to a gist if needed

**Comment by thiagokokada** [comment]
> I have a WIP .NET 5 package on my local machine that I could upload to a gist if needed

@cidkidnix This would be great, since I am stuck on trying to compile thanks to some .NET 5 issue.

**Comment by thiagokokada** [comment]
@cidkidnix I tested your recipe in overlay and seems to work well. Still need to figure how to fix some of the following issues, though:

- Generate the `opentabletdriver-deps.nix` file automatically, so we can update this package without updating every dependency by hand
- Wrap the launcher script so the daemon is launched automatically (as it happens in the Debian package I think?). Or as an alternative, just start this as a systemd service (as the AUR package does)
- Generate the udev rules and copy it to the appropriate place. Alternatively we can just extract the udev file from the .deb package, but this involves some manual operation

Except for the first issue, for the other ones I think maybe it would be better to have a `program.opentabletdriver` so we could automatically enable the systemd service, set the udev rules and add the GUI to the `environment.systemPrograms`. This seems the cleanest way to fix those issues.

**Comment by thiagokokada** [comment]
https://github.com/NixOS/nixpkgs/pull/107638 have an initial build of OpenTabletDriver 0.4.2. It almost works, but needs some manual setup:

- Start the `OpenTabletDriver.Daemon` manually before opening `OpenTabletDriver.UX.Gtk`. Alternatively, you can start the daemon as an systemd user service
- For now, you need to add `service.udev.packages = [ opentabletdriver.udev ];` manually to your `/etc/nixos/configuration.nix`. This can be fixed if we add a `hardware.opentabletdriver` module, that once enabled do this automatically (and it may also create a systemd user service, fixing the first issue too)

Now, while it builds and kinda works, I can't seem to make it detect my tablet (Huion HS64). I thought something was wrong with the udev rules but looking at the udev logs it seems that the rules are being applied correctly. The connection between the GUI and daemon itself seems fine, since it does redirect the logs to the daemon. So now I am stuck.

@cidkidnix Do you have some idea on how to solve the issue above?

**Comment by thiagokokada** [comment]
Got the package to work with the help of OpenTabletDriver's Discord. It was missing the `libudev`.
