### ISSUE TITLE
libuv fails to build on certain systems

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#107657]
**Describe the bug**
I happened to have rebuilt `libuv` on my machine while testing a PR (https://github.com/NixOS/nixpkgs/pull/98915#issuecomment-751387547), and it failed. I thought it was due to that PR (cause on nixpkgs master it wasfetched it from the binary cache). I built master again with `nix-build --check libuv`, and was able to also get the build to fail there.

I suspected this to be somewhat CPU related. My workstation has a AMD Ryzen 9 3900X. On another machine (Intel Xeon CPUs) I seem to be able to build it.

**To Reproduce**
1.  `nix-build --check libuv` on current master
```
not ok 72 - fs_fstat
# exit code 134
# Output from process `fs_fstat`:
# Assertion failed in test/test-fs.c on line 1389: s->st_dev == (uint64_t) t.st_dev
```

**Expected behavior**
I'd expect it to build.

**Comment by yorickvP** [comment]
No reason to think this is cpu related. https://github.com/libuv/libuv/blob/v1.x/test/test-fs.c#L1439 , might be FS, kernel or env related. Works 4/4 times on my 3950x

**Comment by flokli** [comment]
```
/run/booted-system -> /nix/store/kznh8cfblpm573w2v8q7xnx7rq86l6sv-nixos-system-ws-21.03.git.3aac2c14a8dM
/run/booted-system/kernel -> /nix/store/j0rl7znhy3azfmgf7yj9xv9ihqp30sbm-linux-5.10.2/bzImage
```

```
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.3.10, channels(root): "nixos-20.09pre230335.9480bae3370", channels(flokli): "nixpkgs-21.03pre255600.24eb3f87fc6", nixpkgs: /home/flokli/.nix-defexpr/channels/nixpkgs
```

**Comment by flokli** [comment]
Okay, after a reboot (same kernel), this doesn't happen anymore. This is super scary.

**Comment by vcunat** [comment]
I found another assertion in the test repeatedly failing on Hydra, so I disabled it in 173de4efbf4a475175beb0ae9b93a760efcf264a
