### ISSUE TITLE
Cross-compiled git uses wrong bash

### ISSUE THREAD

**Issue by mdekstrand** [NixOS/nixpkgs#107639]
**Describe the bug**
The Bash scripts in a cross-compiled Git use the build host's Bash in their shebang lines instead of the target host.

**To Reproduce**
1. Build git in a cross-compiling environment (e.g. for Raspberry Pi 0):
 
       nixpkgs = {
        crossSystem = {
          system = "armv6l-linux";
          platform = lib.systems.platforms.raspberrypi;
        };

        localSystem = {
          system = "x86_64-linux";
        };

2. Inspect `git-submodule` in the resulting built package - it references native host bash
3. Try to run `git submodule` in the resulting git installed on the target host - results in the following error:

        fatal: cannot exec 'git-submodule': Exec format error

**Expected behavior**
`git submodule` correctly runs

**Notify maintainers**
@primeos @peti @wmertens @globin

**Metadata**

On the build host:

```
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev
copying path '/nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.84, NixOS, 20.09.2344.a3a3dda3bac (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(michael): `""`
 - channels(root): `"nixos-20.09.2344.a3a3dda3bac"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by matthewbauer** [comment]
You can try https://github.com/matthewbauer/nixpkgs/commit/221c739954420b883be1b3f8b2c7719f4b153b32 and https://github.com/NixOS/nixpkgs/pull/84415#discussion_r404172998 for discussion.

**Comment by flokli** [comment]
@matthewbauer there seems to be a lot more things pulling in native bash in a semi-minimal system:

![image](https://user-images.githubusercontent.com/183879/103455366-b5bd3180-4cec-11eb-8941-24ad5fd6baa1.png)

**Comment by flokli** [comment]
This is probably `pkgs/build-support/setup-hooks/patch-shebangs.sh` using wrong bash.

**Comment by flokli** [comment]
cc @LnL7 c9223a17bc86fda888b36b7fde9ebc5bed3f0463

**Comment by Artturin** [comment]
Fixed

**Comment by flokli** [comment]
@Artturin do you have a commit / PR to link to?

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/141959
