### ISSUE TITLE
fetchpatch: won't trigger rebuild when args updated

### ISSUE THREAD

**Issue by holymonson** [NixOS/nixpkgs#107701]
**Describe the bug**
When `fetchpatch`, its content is "cached", building with new args won't trigger rebuild, the only way to rebuild is deleting the output.

**To Reproduce**
1. Fetch a patch, 
```
nix-repl> :b fetchpatch { name = "patch"; url = "https://trac.webkit.org/changeset/271069/webkit?format=diff"; sha256 = "1anr3jj5qw73xsg3cmhdx3djdgd6j5mfw46dhcnvp8x74shm157x"; stripLen = 1; }

this derivation produced the following outputs:
  out -> /nix/store/9hl77pn4s519aqw1w5p7v0h8g0y244l8-patch
```
2. Add `excludes = [ "ChangeLog" ];` to build again,  we got the same result, __unexpected__, because the content is changed.
```
nix-repl> :b fetchpatch { name = "patch"; url = "https://trac.webkit.org/changeset/271069/webkit?format=diff"; sha256 = "1anr3jj5qw73xsg3cmhdx3djdgd6j5mfw46dhcnvp8x74shm157x"; stripLen = 1; excludes = [ "ChangeLog" ]; }

this derivation produced the following outputs:
  out -> /nix/store/9hl77pn4s519aqw1w5p7v0h8g0y244l8-patch
```
3. If we `nix-store --delete /nix/store/9hl77pn4s519aqw1w5p7v0h8g0y244l8-patch`, and rerun step 2, it genetates the correct result. (expected to failed because of different content with different sha256)
```
nix-repl> :b fetchpatch { name = "patch"; url = "https://trac.webkit.org/changeset/271069/webkit?format=diff"; sha256 = "1anr3jj5qw73xsg3cmhdx3djdgd6j5mfw46dhcnvp8x74shm157x"; stripLen = 1; excludes = [ "ChangeLog" ]; }
hash mismatch in fixed-output derivation '/nix/store/67af6jd56pmdm8jcrx28hc54l7qnpa7r-patch':
  wanted: sha256:1anr3jj5qw73xsg3cmhdx3djdgd6j5mfw46dhcnvp8x74shm157x
  got:    sha256:1dbkdmpxjr6p0ajzgiv1s0xm038kjhxmw9i2zmnhjq2ny1zzzcv7
```

**Expected behavior**
Building result by `fetchpatch` should changed with its args changed.

**Additional context**
I tested with args `stripLen` `excludes` `includes` and hit the same bug, guessing it may affect `extraPrefix` `revert` too.

**Notify maintainers**

@Infinisil 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```yaml
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.9`
 - channels(monson): `"nixpkgs"`
 - nixpkgs: `/Users/monson/.nix-defexpr/channels/nixpkgs`
```

**Comment by sternenseemann** [comment]
This is not a bug, but caused by `fetchpatch` producing a so called [fixed-output derivation](https://nixos.org/manual/nix/stable/#fixed-output-drvs).

This means the derivation is identified by its output hash rather than its inputs and therefore not rebuilt if the output hash is the same as already present in `/nix/store`.

This has several reasons:

* We need to pin the output hash of stuff fetched from the internet to prevent arbitrary stuff is injected into a derivation by someone controlling the used server.
* We avoid unnecessary rebuilds if an url changes because we switch to a different mirror or the upstream directory layout changes.
* …

**Comment by holymonson** [comment]
Thanks @sternenseemann , I got it.

**Comment by sternenseemann** [comment]
np, everyone gets caught out by this more than once!

**Comment by Infinisil** [comment]
I just opened NixOS/rfcs#84 which would fix this problem
