### ISSUE TITLE
Can not wrap "luajithbtex" in a TeX project that does not use luatex

### ISSUE THREAD

**Issue by ShrykeWindgrace** [NixOS/nixpkgs#107721]
**Describe the bug**
I am trying to build a simple TeX-based project with `nix-build` and the following `default.nix`:

```nix
with import <nixpkgs> {};

stdenv.mkDerivation rec {
    name = "name-of-the-project";
    buildInputs = [
        gnumake
        (texlive.combine { inherit (texlive) scheme-basic latexmk cm-super; })
    ];
    src = pkgs.lib.sources.sourceFilesBySuffices ./. [".tex" "Makefile" ".png"];
}
```
The relevant part of `Makefile` is merely `latexmk -pdf Main.tex`.

Running `nix-build` gives
```
Builder called die: Cannot wrap '/nix/store/x331fafnf79rj4b1pz1qaps4rgfys5al-texlive-bin-2020/bin/luajithbtex' because it is not an executable file
Backtrace:
7 assertExecutable /nix/store/wjf7b7gryjbxjax2ak2d7mqhk8g1m7zl-hook/nix-support/setup-hook
36 makeWrapper /nix/store/wjf7b7gryjbxjax2ak2d7mqhk8g1m7zl-hook/nix-support/setup-hook
1361 wrapBin /nix/store/wcmmm3azzxpvlh58ma2w2n8p19298drm-stdenv-linux/setup
1400 genericBuild /nix/store/wcmmm3azzxpvlh58ma2w2n8p19298drm-stdenv-linux/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh
```
The directory `/nix/store/x331fafnf79rj4b1pz1qaps4rgfys5al-texlive-bin-2020/bin/` does not contain `luajithbtex` executable (no lua* files at all). I do not use` luatex`.

**To Reproduce**
1. win10+WSL+ubuntu18+"nix-as-package-manager"
2. run nix-build against aforementioned default.nix

I do not have access to another setup to test this build in other conditions.

**Expected behavior**
The project builds - or at least tries to run latexmk

**Additional context**
I am running this on  a win10+WSL+ubuntu18+"nix-as-package-manager", following nixpkgs-unstable, updated this morning.

**Notify maintainers**

@veprbl , I guess =)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-18362-Microsoft, Ubuntu, 18.04.4 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(tzy1wsl): `"home-manager, nixpkgs-21.03pre259843.c4c899d3ef1"`
 - nixpkgs: `/home/username/.nix-defexpr/channels/nixpkgs`

**Comment by veprbl** [comment]
Can't reproduce this on macOS. The `(texlive.combine { inherit (texlive) scheme-basic latexmk cm-super; })` builds just fine.

**Comment by ShrykeWindgrace** [comment]
I now have access to another setup - ubuntu18+"nix-as-package-manager", also following nixpkgs-unstable. That machine has traces of its own texlive that I can not remove (I do not know if it is relevant in context of nix-build, but it was worth mentioning). The derivation builds just fine on that machine, too. It seems that there is an unexplored quirk of wsl setup hiding somehwere...

Unfortunately, my nix skills are not keen enough to pinpoint the exact difference between evaluations that cause the failure on one machine and success on another. I noticed however that the list of "derivations to be built" is different. Is it normal?

**Comment by veprbl** [comment]
@ShrykeWindgrace Let's make sure that we are trying the same thing. Here is how I try to reproduce your issue:
```nix
with import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/c4c899d3ef1ed21ad62481e715abda491a83ad96.tar.gz") {};
  
texlive.combine { inherit (texlive) scheme-basic latexmk cm-super; }
```
Then run "nix-build" on this nix file.

Could you try this on WSL? I assume it should give the same derivation hashes on Linux and WSL.

**Comment by ShrykeWindgrace** [comment]
@veprbl I tried it like this:
 ```bash
 $  ls
 default.nix
 $ cat default.nix
with import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/c4c899d3ef1ed21ad62481e715abda491a83ad96.tar.gz") {};

texlive.combine { inherit (texlive) scheme-basic latexmk cm-super; }
 ```
 Running `nix-build` results in
 ```
 <...>
Wrapping './bin/luahbtex'
Wrapping './bin/luajithbtex'
Builder called die: Cannot wrap '/nix/store/l3aih4w0p3y4yqrc4wqy0l6cz4av7h1c-texlive-bin-2020/bin/luajithbtex' because it is not an executable file
Backtrace:
7 assertExecutable /nix/store/wjf7b7gryjbxjax2ak2d7mqhk8g1m7zl-hook/nix-support/setup-hook
36 makeWrapper /nix/store/wjf7b7gryjbxjax2ak2d7mqhk8g1m7zl-hook/nix-support/setup-hook
1361 wrapBin /nix/store/wcmmm3azzxpvlh58ma2w2n8p19298drm-stdenv-linux/setup
1400 genericBuild /nix/store/wcmmm3azzxpvlh58ma2w2n8p19298drm-stdenv-linux/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh

builder for '/nix/store/ni2rcjjsq0bkjic9c4g7kp7b5a98wmyp-texlive-combined-2020.drv' failed with exit code 1
error: build of '/nix/store/ni2rcjjsq0bkjic9c4g7kp7b5a98wmyp-texlive-combined-2020.drv' failed

 ```
 Full logs: https://pastebin.com/sxdAmwiR

**Comment by ShrykeWindgrace** [comment]
One more tidbit of information - it appears that the version of WSL also plays its role; I tested the above derivation on a WSL2+Ubuntu-20.04, it works just fine.

**Comment by veprbl** [comment]
@ShrykeWindgrace 
Perhaps, try building with `NIX_DEBUG` and see how output of a bad build compares to a one of a successful
```
with import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/e716ddfac4be879ffbae75c3914a538dd5d4d12e.tar.gz") {};
  
(texlive.combine { inherit (texlive) scheme-basic latexmk cm-super; }).overrideAttrs (_: { NIX_DEBUG=6; })
```

**Comment by ShrykeWindgrace** [comment]
@veprbl On WSL1, the error is 
```
Builder called die: Cannot wrap '/nix/store/labjf9z6h21zkjwsmpi7vnkx23x3nhrn-texlive-bin-2019/bin/mf' because it is not an executable file 
```

**Comment by lunik1** [comment]
I have encountered this same issue on WSL2 on a Debian buster base,

**Comment by lunik1** [comment]
My mistake! I was actually on WSL1. This at least suggests this problem is exclusive to WSL1.
