### ISSUE TITLE
darwin: python: sphinx build fails for python 3.4

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#10770]
Building python34Packages.sphinx fail in darwin sandbox,
because `setlocale` call required for passing all tests fail, possibly to checking impure locale paths:

1.11.2015 5.02.42,000 kernel[0]: Sandbox: python3.5m(67569) deny(1) file-read-metadata /usr/share/locale/en_US.UTF-8/LC_COLLATE
1.11.2015 5.02.42,000 kernel[0]: Sandbox: python3.5m(67569) deny(1) file-read-metadata /usr/share/locale/en_US.UTF-8/LC_CTYPE

**Comment by FRidh** [comment]
Do you know whether this has been solved? We really need CI of Python packages again.

**Comment by datakurre** [comment]
No, unfortunately. I haven't been using much Nix on OS X since I moved to NixOS :(

**Comment by matthewbauer** [comment]
Sphinx now succeeds for me on macOS.
