### ISSUE TITLE
NOTICE: Invitations to join NixOS Organization are sending again.

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#107815]
Earlier this year, GitHub changed their API to make it so we could repeatedly send invitations to people, spamming them. Invitations were stopped because of this. @andresilva sent a PR fixing this issue, so we can send them again. Each person who is a maintainer will receive *one* more invitation, and then they won't receive any more. PR: https://github.com/NixOS/rfc39/pull/6 Thank you, @andresilva! My apologies to those who will see this last invitation as more spam.

**Comment by grahamc** [comment]
All invitations are sent. Let's leave this open and pinned for a few days in case someone comes looking.

**Comment by cole-h** [comment]
I believe this issue has run its course.
