### ISSUE TITLE
hydra.nixos.org serves broken manifests

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#10783]
~~~~
$ nix-channel --list
hydra http://hydra.nixos.org/jobset/hydra/trunk/channel/latest
nixos http://nixos.org/channels/nixos-unstable

$ nix-channel --update
downloading Nix expressions from ‘http://hydra.nixos.org/jobset/hydra/trunk/channel/latest/nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   357  100   357    0     0   2345      0 --:--:-- --:--:-- --:--:--  2364
100  9020  100  9020    0     0  27964      0 --:--:-- --:--:-- --:--:-- 7654k
downloading Nix expressions from ‘http://nixos.org/releases/nixos/unstable/nixos-16.03pre71056.c44a593//nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6925k  100 6925k    0     0  5175k      0  0:00:01  0:00:01 --:--:-- 5180k
unpacking channels...
error: syntax error, unexpected UPDATE, at (string):1:177
cannot unpack the channels at /run/current-system/sw/bin/nix-channel line 169.
~~~~~

Is this a known problem?

**Comment by cleverca22** [comment]
i had similar problems when setting up my own channel, strace revealed that it was pasting the html of a 404 error right into a nix expression, without any escaping, so the strings in the html caused syntax errors

**Comment by copumpkin** [comment]
Yeah, I encountered something similar when I was serving up a private channel from S3 and had some permissioning issues that led to a 403.

**Comment by peti** [comment]
`hydra.nixos.org` serves broken manifest files:

    nix-pull http://hydra.nixos.org/jobset/nixpkgs/trunk/channel/latest/MANIFEST

After you've pulled one of those, the Nix store is in an inconsistest state, which results -- among other things -- in the error above.

**Comment by edolstra** [comment]
Hydra has been fixed.

However, there is the separate issue that nix-channel should not ignore HTTP errors.
