### ISSUE TITLE
Make nextcloud php package customizable

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#107875]
Many nextcloud extensions like https://apps.nextcloud.com/apps/facerecognition need additional php extensions that are not part of the [extension enabled for nextcloud](https://github.com/NixOS/nixpkgs/blob/2f47650c2f28d87f86ab807b8a339c684d91ec56/nixos/modules/services/web-apps/nextcloud.nix#L16).

It would be great to either:

* Provide an option to override the php package nextcloud uses, i.e. `services.nextcloud.php.package`

Or:

* Provide an option `extraPHPExtensions`, and make the current extension selection its default value

I'm opening this as an issue to get some feedback on what the better option is, and to get the naming right.

CC maintainers @schneefux @bachp @globin @fpletz @ma27

**Comment by turion** [comment]
Meta: I'm not sure all labels I've applied make sense here. Feel free to remove inappropriate ones.

Also: There is no PHP label?

**Comment by veprbl** [comment]
cc @NixOS/php
