### ISSUE TITLE
Cling is packaged in a way that makes it slightly inconvenient to work with an external clang

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#107970]
cc @thomasjm because maintainer.

https://github.com/codedownio/nixpkgs/blob/8c36b50a23bd4cd806e573c248361b3340d89781/pkgs/development/interpreters/cling/default.nix puts clang and cling headers in the same directory, which then gets included as a single `-I` include path on the command line, meaning I have to split it up in order to `#include` clang header files from a different version without breakage. It would be more convenient if the directories were included individually and I only had to rewrite the command without the implicit clang and with my own clang.

Observe specifically `/nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/include`:
```
$ cat $(which cling)
#! /nix/store/4l7wsi6h6283194r6fqy1731qxlagq62-bash-4.4-p23/bin/bash -e
exec "/nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/bin/cling"  -isystem  /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0 -isystem  /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-unknown-linux-gnu -isystem  /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward  -nostdinc -nostdinc++ -isystem /nix/store/myska9y3fhkymhkp6rn3zqrgjwyq9wx3-glibc-2.32-10-dev/include -I /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/include -I /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/lib/clang/5.0.2/include "$@"

$ cling -v
Adding library paths from 'LD_LIBRARY_PATH':
cling version 0.7
clang version 5.0.2 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/bin
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/include
 /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/lib/clang/5.0.2/include
 /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0
 /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-unknown-linux-gnu
 /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward
 /nix/store/myska9y3fhkymhkp6rn3zqrgjwyq9wx3-glibc-2.32-10-dev/include
End of search list.
Setting up system headers with clang:
#include "..." search starts here:
#include <...> search starts here:
 /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/include
 /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/lib/clang/5.0.2/include
 /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0
 /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-unknown-linux-gnu
 /nix/store/wmzmnnrj780268ybilmcfyd3grn5qzi6-gcc-9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/../../../../include/c++/9.3.0/backward
 /nix/store/myska9y3fhkymhkp6rn3zqrgjwyq9wx3-glibc-2.32-10-dev/include
End of search list.
#include "cling/Interpreter/RuntimeUniverse.h"
namespace cling { class Interpreter; namespace runtime { Interpreter* gCling=(Interpreter*)0x7ffc7f402110;}}
extern "C" int __cxa_atexit(void (*f)(void*), void*, void*)  noexcept;
#define __dso_handle ((void*)0x7ffc7f402110)
extern "C" int atexit(void(*f)())  throw ()  { return __cxa_atexit((void(*)(void*))f, 0, __dso_handle); }
extern "C++" int at_quick_exit(void(*f)())  throw ()  { return __cxa_atexit((void(*)(void*))f, 0, __dso_handle); }
Added include paths:
  .

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ .q

$ ls /nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/include
clang  clang-c  cling
```

(tangentially related: https://github.com/root-project/cling/issues/374)

**Comment by thomasjm** [comment]
I don't quite follow what you mean by "putting clang and cling headers in the same directory". They look like two separate `-I` flags to me: https://github.com/codedownio/nixpkgs/blob/8c36b50a23bd4cd806e573c248361b3340d89781/pkgs/development/interpreters/cling/default.nix#L77-L78

You could probably override the clang one.

Note the difference between the `flags` and the `compilerIncludeFlags`. Cling is more particular about the latter flags, it probably won't work well to override those.

**Comment by deliciouslytyped** [comment]
Unless my toes are tripping over each other again, `/nix/store/5maaxj22nspy8nm4c19sxjmwy8pyijgq-cling-unwrapped-0.7/include` contains both a clang and a cling directory, both of which need to be searched for headers. This is what I would like to be split. I'm not sure whats in the other clang include dir, but that's a third thing. I think I'm asking for splitting/minimizing https://github.com/codedownio/nixpkgs/blob/8c36b50a23bd4cd806e573c248361b3340d89781/pkgs/development/interpreters/cling/default.nix#L77 .

**Comment by thomasjm** [comment]
Well, the contents of `<cling-unwrapped>/include` and `<cling-unwrapped>/lib/clang/5.0.2/include` are different. The former looks like it has more internal/AST-related stuff and the latter more for users of the clang compiler. FWIW I didn't package the includes this way deliberately, that's just the way Cling does it.

You mentioned in the `cling` issue you filed that you want to poke around with the ASTs of some other Clang version...I'm not sure how well that's going to work given that `cling` is compiled against a specific `clang` and has AST details baked in. Maybe you could build against a different `clang`. Although I have a vague memory that Cling needs to be built against Clang/LLVM 5 (not positive though).

**Comment by doronbehar** [comment]
If someone wishes to put the efforts to update cling, it should be updated to `0.9.0` as of writing and it's a bit hard to do that since the llvm cling needs requires a lot of patches. For reference, this guy is maintaining a debian package of both patched llvm and cling:

Patched LLVM/Clang 9: [salsa.debian.org/dimitry-ishenko/llvm-toolchain-9](https://salsa.debian.org/dimitry-ishenko/llvm-toolchain-9)
Patched cling: [dimitry-ishenko-cpp/cling](https://github.com/dimitry-ishenko-cpp/cling)

He helped me here:

https://github.com/jupyter-xeus/xeus-cling/issues/400#issuecomment-995976872

**Comment by thomasjm** [comment]
@doronbehar Cling has been updated to `0.9`. I never fully understood what this issue was about, can it be closed now?

**Comment by doronbehar** [comment]
Thanks for the notification @thomasjm . The situation now is a lot better then it was back in December 2021, as it seems thanks to your contribution in #202114 . However I still think the situation could be better. For instance:

- Almost all patches don't have a comment near them, explaining why upstream won't accept them. It seems you have made contact with upstream in #202114 yet still failed to document the state of these patches that.
- Also, the commit messages there don't conform to Nixpkgs' standard which was irresponsible to commit them like that in the first place IMO, as @RaitoBezarius already mentioned unfortunately  after merging.
- The `prePatch` line:
 
    `echo "add_llvm_external_project(cling)" >> tools/CMakeLists.txt`

  Could have been upstreamed as well.

In general, to make maintenance of a package easier for us, ideally you should strive to convince upstream to add cmake options that make it possible for us to distribute their software. This is relevant for all patches you have there.

One last thing: Next time, if people complain about a package you maintain in Nixpkgs - whether it's just missing an update or whatever and you have a PR open for them to test, cc them for a review **before** you get your PR merged.

**Comment by thomasjm** [comment]
@doronbehar , I'm sensing a level of entitlement here that makes me frankly not too interested in helping you out.

I didn't think this issue was the "complain about everything you don't like about Cling's packaging" issue. After an attempt to help you on this thread, and failing to get necessary clarification from you, it went stale and like 2 years went by. Even if I had remembered this thread during the Cling 0.9 PR, I still don't know what you're asking for here and this wouldn't have come to mind as relevant.

I'm happy to discuss how to do things better in general. Upstreaming the patches would be great, although the upstream seemed to have little interest as they have their own packaging system that works for them. @RaitoBezarius 's sudden merging of my PR surprised me more than anyone, as I was still testing it myself and trying to get others to exercise it.

If you want to open another issue, please make sure it's specific and actionable (and not seemingly incompatible with the design of Cling).

**Comment by RaitoBezarius** [comment]
Apologies for my sudden merge @thomasjm the context is that as a release manager, Cling was the last blocker to get rid of that dinosaur LLVM, I really appreciate your work and what you have done and the sudden merge is completely on me going too fast and not taking the time.

Also, I agree that @doronbehar tone could be better regarding the situation, please have more empathy regarding maintainer as it seems like to be a non-trivial package.

Again, sorry for everything and thank you for your time and for your efforts on Cling.

**Comment by thomasjm** [comment]
No worries @RaitoBezarius , I understood there was a release crunch going on. 

I'd like to understand the workflow that you prefer though. It seems to me that I could constantly force-push a single squashed commit in the desired format, but that would be weird for my reviewers when working through an extended review process, as tends to happen on a package as tricky as Cling. I've always used a workflow where you push your progress commit by commit, so it's easy for reviewers to see what's changed, and then once everyone agrees it's ready then the author or the committer can do the squash. But if another way is preferred on Nixpkgs I'd like to know about it.
