### ISSUE TITLE
python3 library build is not deterministic

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#107951]
**Describe the bug**

When building python3 twice, the result is not always bit-by-bit the same. This makes it harder to audit whether binaries/images have been built correctly. For more information on why this is useful see https://reproducible-builds.org .

**To Reproduce**

`nix-build '<nixpkgs>' -A python3 --check` 

**Additional context**

Notably, the ordering of some symbols (`​_Py_Mangle`, `​PyEval_GetGlobals`, several `_PyErr` ones) is not stable.

Setting `enableParallelBuilding` to false doesn't help.

**Comment by FRidh** [comment]
I've got it reproducible again. Opening a PR soon. Some people are not going to like it though...

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/107965/
