### ISSUE TITLE
nixos-generate-config produces network configuration that times out when interface is removed

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#107908]
The issue is that nixos-generate-config produces a hardware-configuration.nix that includes this:

```
  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = false;

  networking.interfaces.enp3s0.useDHCP = true;
  networking.interfaces.wlp1s0f0u4.useDHCP = true;
```

(each active interface gets its own useDHCP). Previously `networking.useDHCP` was enabled by default.

But, there is no guarantee that enp3s0 & wlp1s0f0u4 will always be available! Consider a laptop with an external USB-C to ethernet adapter connected; this interface will be removed when the user disconnects from ethernet. Another situation is when a USB Wi-Fi Adapter is used, but the USB port is changed (this changes u index I believe). The problem is either that:

- an old interface no longer exists and you get stuck waiting for "network-addresses-en*" or "network-addresses-wl*" to finish (or timeout at 1m 30s) as part of network-setup.service.
- a new interface appears which does not have useDHCP set (and the user doesn't really know how to set it).

A workaround provided by @lheckerman is to just use a wildcard like:

```
{
    systemd.network.networks."99-en-dhcp" = {
      matchConfig.Name = "en*";
      networkConfig.DHCP = "yes";
    };
    systemd.network.networks."99-wl-dhcp" = {
      matchConfig.Name = "wl*";
      networkConfig.DHCP = "yes";
    };
}
```

although it sounds like this does not work with scripted networking (https://github.com/NixOS/nixpkgs/pull/69302#issuecomment-752055980).

---

The relevant code is in https://github.com/NixOS/nixpkgs/blob/e71df047a0e0244a6b84bba506d0284fd093deb5/nixos/modules/installer/tools/nixos-generate-config.pl#L570-L586

First discussed in https://github.com/NixOS/nixpkgs/pull/69302. Opening as an issue here for better visiblity.

**Comment by lheckemann** [comment]
For the systemd-networkd-based solution, I'd suggest adding `dhcpV4Config.RouteMetric = 1025;` for `wl*` so that ethernet is preferred if available.

Related: #10001 #75515

**Comment by ryneeverett** [comment]
> Another situation is when a USB Wi-Fi Adapter is used, but the USB port is changed (this changes u index I believe).

I painfully confirmed that this is true.

**Comment by nemesamade** [comment]
FYI, for anyone looking for a quick solution to the annoying timeout on boot when ethernet adapter is unplugged, you could just use network manager instead of configuring your interface in configuration.nix:
enable network manager
`networking.networkmanager.enable = true;`
and comment out/delete
`networking.interfaces.enp0s20f0u1.useDHCP = true`
(enp0s2ofou1 being the network interface name assigned to my ethernet adapter)
This stopped the 90 sec time out on boot for me.

**Comment by zseri** [comment]
still relevant
