### ISSUE TITLE
azure-cli-2.6.0: out-of-date (2.17.0 is now available)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#107905]
###### Checklist

`azure-cli: 2.17.0` is out.

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 2.16.0
desired version: 2.17.0

###### Notify maintainers
maintainers: @jonringer (Thank you Jon!)

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jonringer** [comment]
Is there some critical feature that was added in 2.17? A lot of these releases usually just seem like incremental improvements

**Comment by colemickens** [comment]
:laughing: So, I am (for some reason) holding out hope that [my issue was closed because it was actually addressed](https://github.com/Azure/azure-cli/issues/10192#issuecomment-751411580), but I don't actually have confirmation of it. To be honest, this was somewhat just to track when it gets updated+closed so that I can go ahead and test it out again. I'll give

**Comment by jonringer** [comment]
@colemickens that's a lot of hope. that was from ~14 months ago

**Comment by jonringer** [comment]
but from the sounds of https://github.com/Azure/azure-cli/issues/10192#issuecomment-745128142 it could be this release or the next in which cli get support. Seeing as no storage packages were bumped, I think it's unlikely, unless the behavior just wasn't exposed.

**Comment by jonringer** [comment]
even bumped it to 2.17.1
