### ISSUE TITLE
Plasma: Install Discover by default

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#107988]
Discover is a graphical software manager for Plasma. While it won't help users install software with Nix, it will help those users who want to install software with Snap and Flatpak. Upstream assumes it is installed by default (it is pinned to the task manager) so we should do that.

We can add a NixOS option `programs.plasma.discover.enable` which will default to `true` when the Plasma desktop is enabled. This will make sure any required services (e.g. Snap) are also enabled, but still allow the user to disable Discover if they do not use it.

**Comment by ttuegel** [comment]
Keep this issue open.

**Comment by SuperSamus** [comment]
I'd say that something like `programs.plasma.discover.enable = mkDefault services.flatpak.enable` would make more sense.
If someone is using NixOS it doesn't mean they will want to use Flatpak/Snap, and enabling these along with a DE is probably not a nice surprise.

**Comment by ttuegel** [comment]
> If someone is using NixOS it doesn't mean they will want to use Flatpak/Snap, and enabling these along with a DE is probably not a nice surprise.

Finding out that Plasma is slightly broken without it is arguably a worse surprise! It's probably not a big deal to remove the bits of Plasma that require it.

**Comment by SuperSamus** [comment]
If the only problem of not having Discover installed is being pinned to the Task Manager, I reported a bug upstream: https://bugs.kde.org/show_bug.cgi?id=456600.

**Comment by SuperSamus** [comment]
This can now be closed: it's fixed upstream https://bugs.kde.org/show_bug.cgi?id=436667.

**Comment by SuperSamus** [comment]
@ttuegel?

**Comment by nadimkobeissi** [comment]
Hi everyone,

I am surprised to see this issue marked as closed; a new install of NixOS 23.05 from the [Plasma Desktop ISO](https://channels.nixos.org/nixos-23.05/latest-nixos-plasma5-x86_64-linux.iso) still results in the broken KDE Discover link in the default taskbar, and KDE Discover is not installed.

Furthermore, it would be good to investigate whether we should include KDE Discover by default, as it may facilitate Flatpak installations for new users.

**Comment by hydridity** [comment]
> Hi everyone,
> 
> I am surprised to see this issue marked as closed; a new install of NixOS 23.05 from the [Plasma Desktop ISO](https://channels.nixos.org/nixos-23.05/latest-nixos-plasma5-x86_64-linux.iso) still results in the broken KDE Discover link in the default taskbar, and KDE Discover is not installed.
> 
> Furthermore, it would be good to investigate whether we should include KDE Discover by default, as it may facilitate Flatpak installations for new users.

Oh I was lowkey wondering the entire time what that broken link was referring to.

Maybe it would be a good idea to include it as an option in the GUI Installer same way as the allowUnfree is, with warning that it can be used to install flatpak but cant be used to install regular packages

**Comment by ShalokShalom** [comment]
> Maybe it would be a good idea to include it as an option in the GUI Installer same way as the allowUnfree is, with warning that it can be used to install flatpak but cant be used to install regular packages

Generally, I like that idea. Still, I think Discover is a broken mess, that has never really worked for me for an extended period of time (or even shortly) 

I dont know, if we should propagade not only such an unreliable option, but something that is essentially an inferior design solution to NixOS. 

I do see that some packages may be available due to Flatpaks, who are not available in the NixOS repos.

Although these cases are rare, and the issues with Discover in general and also Flatpak in specific (particulary in combination and due to that, confusion, with the NixOS structure) seems not worth it. 

But if something like that has to be part of the ISO, its for sure better to have this an opt-out solution.

And warn appropriately of the potential conflicts.
