### ISSUE TITLE
polkit apparently taking 11.15 GB in the store

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nixpkgs#107915]
**Describe the bug**
I noticed, after running out of space, that within the last week or so, the size of my nix store has more than doubled. I've tried removing everything from profile, all result links, and ran garbage collection several times but it didn't do much. I stumbled on `nix-du` and found that, according to the output, the polkit package is using 11.15 GB of space on disk. Seeing as I can't really remove it, since everything depends on it, I was wondering if there might be a way to further debug or diagnose this to get the size under control.

**To Reproduce**
Unfortunately, I have no idea how this occurred.

**Expected behavior**
It should take a reasonable amount of space for what it contains

**Screenshots**
clip from the `nix-du` output:
![12 29 20_02 46 42_PM](https://user-images.githubusercontent.com/34083928/103316197-fcf1ac80-49e4-11eb-8165-1ada07778857.png)

**Additional context**

**Notify maintainers**

@worldofpeace 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.20201228.5adafbe (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - nixpkgs: `/nix/store/qzv8mdddhgs6w55bbi7pmbv5iamvnkqm-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: polkit
# a list of nixos modules affected by the problem
module:
```

**Comment by andersk** [comment]
This is just an artefact of the way `nix-du` labels its output nodes. It’s not telling you that `polkit` is taking up 11.15 GB; it’s telling you that if you were to remove *everything on your system that depends* on `polkit`, you’d save 11.15 GB.

```console
$ nix-du --help
nix-du 0.3.3

This program outputs a graph on stdout in the dot format which may help you figuring out which gc-roots should be
removed in order to reclaim space in the nix store.

To get started, if you are interested in freeing, say, 500MB, run
`nix-du -s 500MB | tred | dot -Tsvg > /tmp/blah.svg`
and then view the result in a browser or dedicated software like zgrviewer.

Without options, `nix-du` outputs a graph where all nodes on which the same set of gc-roots depend are coalesced into
one. The resulting node has the size of the sum, and the label of an arbitrary component. An arrow from A to B means
that while A is alive, B is also alive.

As a rule of thumb, a node labeled `foo, 30KB` means that if you remove enough roots to get rid of this node, then you
will free `30KB`. The label `foo` may or may not have a meaning.
```

The actual size of `polkit` itself is

```console
$ nix path-info -hs "$(nix eval --raw -f '<nixpkgs>' polkit)"
/nix/store/nzxrv1g1mn423dzyzpv3hs6n97502wdg-polkit-0.118-bin	 146.8K
```

and the total size of the closure of `polkit`’s dependencies is

```console
$ nix path-info -hS "$(nix eval --raw -f '<nixpkgs>' polkit)"
/nix/store/nzxrv1g1mn423dzyzpv3hs6n97502wdg-polkit-0.118-bin	 232.2M
```

which you can break down individually with `nix path-info -hrs`.
