### ISSUE TITLE
xkbcommon/libxkbcommon are behind (current 0.10.0, released 1.0.3)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#108003]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `libxkbcommon`
current version: `0.10.0`
desired version: `1.0.3`

(filling out this template is _tedious_. especially since there's no syntax highlighting to see through the dense comments)

###### Notify maintainers

maintainers: cc: @ttuegel 

cc: @jtojnar @worldofpeace who reviewed/merged the libxkbcommon last time. draft PR is incoming.

###### Note for maintainers

Please tag this issue in your PR.

**Comment by alyssais** [comment]
Looks like this can be closed now? Correct me if I’m wrong!
