### ISSUE TITLE
Chromium fails on CentOS

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#10809]
On a CentOS 6.7 system, I've installed the Nix package manager according [the appropriate documentation](http://nixos.org/nix/manual/#chap-installation), i.e. I executed `bash <(curl https://nixos.org/nix/install)`. This is a single-user installation.

The first package I installed was chromium. However, upon trying to launch chromium, I get this error:

    [4140:4140:1103/111112:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/13psa5rxjsdxk1ghnkf5q9n25985v7ly-chromium-45.0.2454.101/libexec/chromium/chrome-sandbox is owned by root and has mode 4755.
    Aborted (core dumped)

Of course, since this is a single-user installation, that file is owned by me rather than root. Doesn't look to be in the correct mode, either:

    $ ls -l /nix/store/13psa5rxjsdxk1ghnkf5q9n25985v7ly-chromium-45.0.2454.101/libexec/chromium/chrome-sandbox 
    -r-xr-xr-x 1 me mygroup 22947 Dec 31  1969 /nix/store/13psa5rxjsdxk1ghnkf5q9n25985v7ly-chromium-45.0.2454.101/libexec/chromium/chrome-sandbox

**Comment by a1russell** [comment]
I installed a multi-user system today, too, and I get the same error. The file is at least owned by root this time, but still the incorrect mode.

**Comment by vcunat** [comment]
Chromium needs either suid or a recent enough kernel. In nix store we don't allow suid. I suspect the CentOS kernel is too old. See #895 for details. I consider this a duplicate &ndash; better discuss on the original issue.

**Comment by redi-russela** [comment]
Ah, I wasn't sure. Different error message and different title on #895.

**Comment by vcunat** [comment]
> Different error message

I think the sandbox used to be optional in chromium but isn't anymore.
