### ISSUE TITLE
iwlist interface scan sometimes reports print allocation error

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#10803]
On the Live CD, occasionally the `iwlist interface scan` command returns: `print_scanning_info: Allocation failed`.

Apparently this has to do with lots of access points. My scan returns 47 cells right now.

Googling this error a bit, showed that some patches have been made for this? But I'm not really understanding why it happens and if there has been a fix, and where that fix has been applied.

Is `iw interface scan` the same thing or different?

**Comment by vcunat** [comment]
I've heard that `wireless-tools` is a deprecated interface (`iwconfig`, `iwlist`, ...) and `iw` is the future way of doing these things. Saying that, `iwlist <interface> scan` works for me and `iw <interface> scan` doesn't, but I'm always using `wpa_cli` anyway :-)

**Comment by CMCDragonkai** [comment]
Yea `iwlist interface scan` does work most of time. But sometimes it has repeated failures. How many cells does your scan return? There were bug reports saying that it has to do with lots of access points 100ish? Mine was 47 at the time it worked.

What does your `iw interface scan` do? It works out of the box on the live cd.

**Comment by vcunat** [comment]
"only" 18 ATM, so I wouldn't see the error.

**Comment by CMCDragonkai** [comment]
Should the manual expand more on setting up a network connection involving wifi, or should that go into the wiki?

**Comment by CMCDragonkai** [comment]
Closing because iwlist is deprecated.

**Comment by vcunat** [comment]
The wifi setup info doesn't seem nixos-specific &ndash; perhaps there already is some good resource that we can link or embed, perhaps with small modifications.
