### ISSUE TITLE
goPackages.buildFromGitHub missing

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#10805]
Hey, go users, is there a reason why `buildFromGitHub` isn't exported? I would like to have an externally defined/overridden package and this is missing for me. I'll push it in a few days...

**Comment by lethalman** [comment]
No reason, as usual :)

**Comment by copumpkin** [comment]
@vcunat I wrote it mostly because I saw the exact same pattern repeated a thousand times in `goPackages`, so I just factored it out without giving much thought to go packages specified elsewhere. Please export/generalize/do whatever is needed to improve things :smile:

**Comment by vcunat** [comment]
It was rather pointless of me to open this issue instead of pushing directly...

**Comment by copumpkin** [comment]
:)
