### ISSUE TITLE
No way to instantiate systemd template units

### ISSUE THREAD

**Issue by hmenke** [NixOS/nixpkgs#108054]
**Describe the bug**

Systemd has the notion of template units, e.g. `systemd-nspawn@.service` is such a unit.  These template units contain common configuration that is suppose to be shared among all instances of this template.  For example on a typical Linux distribution it would be possible to instantiate the aforementioned unit for a particular machine
```console
[root@arch] # systemctl enable systemd-nspawn@archlinux.service
Created symlink /etc/systemd/system/machines.target.wants/systemd-nspawn@archlinux.service → /etc/systemd/system/systemd-nspawn@.service.
```
Something similar is currently not possible on NixOS.  Trying to use
```nix
{
  systemd.services."systemd-nspawn@archlinux".enable = true;
}
```
will create an entirely new unit from scratch, completely ignoring the existence of the template `systemd-nspawn@.service`.  Even worse, because `/etc/systemd/system` links into the read-only Nix store, it's not even possible to instantiate the template in a stateful manner:
```console
[root@nixos] # systemctl enable systemd-nspawn@archlinux.service
Failed to enable unit: Unit file /etc/systemd/system/machines.target.wants/systemd-nspawn@archlinux.service does not exis.
```

**To Reproduce**
1. Add `systemd.services."systemd-nspawn@archlinux".enable = true;` to `/etc/nixos/configuration.nix`.
2. Rebuild
3. Compare the output of `systemctl cat systemd-nspawn@.service` and `systemctl cat systemd-nspawn@archlinux.service` and see that they have nothing to do with each other.

**Expected behavior**
Template units are a powerful concept of systemd and it would be beneficial if NixOS users could take advantage of it.

**Screenshots**

**Additional context**

**Notify maintainers**

The `systemd` module doesn't have a maintainer field, so I'm pinging the `systemd` package maintainers: @andir @eelco @flokli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.2405.e065200fc90 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - nixpkgs: `/etc/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: systemd
```

**Comment by hmenke** [comment]
Possible duplicate of #80933

**Comment by flokli** [comment]
yes, dup of https://github.com/NixOS/nixpkgs/issues/80933.

**Comment by hmenke** [comment]
Here is a workaround for those that are interested:
```nix
{ config, lib, pkgs, ... }: {

  systemd.packages = [
    (pkgs.runCommandNoCC "machines" {
      preferLocalBuild = true;
      allowSubstitutes = false;
    } ''
      mkdir -p $out/etc/systemd/system/machines.target.wants/
      ln -s /etc/systemd/system/systemd-nspawn@.service $out/etc/systemd/system/systemd-nspawn@archlinux.service
    '')
  ];

  systemd.services."systemd-nspawn@archlinux".wantedBy = [ "machines.target" ];

}
```
