### ISSUE TITLE
Emacs tree-sitter packages don't work

### ISSUE THREAD

**Issue by leungbk** [NixOS/nixpkgs#108089]
**Describe the bug**
The Emacs packages for `tree-sitter` don't successfully load.

**To Reproduce**
Run a `nix-shell` from the following `shell.nix`:

``` nix
{ pkgs ? (import <nixpkgs> {
    overlays = [
      (import (builtins.fetchTarball {
        url = https://github.com/nix-community/emacs-overlay/archive/62820bf3861af46f457ba9295f9dae16d8aa7ff7.tar.gz;
      }))
    ];
  })
}:

with pkgs;
let myEmacs =
  (emacsPackagesGen emacsUnstable).emacsWithPackages (epkgs: (with epkgs; [
    tree-sitter
    tree-sitter-langs
    tsc
  ]));
in
mkShell {
  name = "emacs-shell";
  buildInputs = [
    myEmacs
  ];
}
```

After opening Emacs from inside the `nix-shell` and running `M-: (require 'tree-sitter)`, we get the following:

``` elisp
Debugger entered--Lisp error: (file-error "Opening output file" "Read-only file system" "/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-...")
  write-region(1 4036257 "tsc-dyn.so" nil nil nil)
  mm-write-region(1 4036257 "tsc-dyn.so" nil nil nil binary t)
  mm-save-part-to-file((#<buffer  *mm*-347878> ("application/octet-stream") nil nil ("attachment" (filename . "tsc-dyn.so")) nil nil nil) "tsc-dyn.so")
  url-copy-file("https://github.com/ubolonton/emacs-tree-sitter/rel..." "tsc-dyn.so" :ok-if-already-exists)
  tsc-dyn-get--download("0.12.1")
  tsc-dyn-get-ensure("0.12.1")
  (progn (defconst tsc--dyn-version "0.12.1" "Required version of the dynamic module `tsc-dyn'.") (require 'tsc-dyn-get) (tsc-dyn-get-ensure tsc--dyn-version))
  eval((progn (defconst tsc--dyn-version "0.12.1" "Required version of the dynamic module `tsc-dyn'.") (require 'tsc-dyn-get) (tsc-dyn-get-ensure tsc--dyn-version)) t)
  #f(compiled-function (&rest body) "Like `progn', but evaluates the body at compile time and at\nload time.  In interpreted code, this is entirely equivalent to\n`progn', except that the value of the expression may be (but is\nnot necessarily) computed at load time if eager macro expansion\nis enabled." #<bytecode 0x1fcfc09bbf13>)((defconst tsc--dyn-version "0.12.1" "Required version of the dynamic module `tsc-dyn'.") (require 'tsc-dyn-get) (tsc-dyn-get-ensure tsc--dyn-version))
  (eval-and-compile (defconst tsc--dyn-version "0.12.1" "Required version of the dynamic module `tsc-dyn'.") (require 'tsc-dyn-get) (tsc-dyn-get-ensure tsc--dyn-version))
  eval-buffer(#<buffer  *load*-668460> nil "/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-..." nil t)  ; Reading at buffer position 1003
  load-with-code-conversion("/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-..." "/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-..." nil t)
  require(tsc)
  eval-buffer(#<buffer  *load*> nil "/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-..." nil t)  ; Reading at buffer position 775
  load-with-code-conversion("/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-..." "/nix/store/klpaapnrhcw0j2dnbkvl16yl0ilqihj7-emacs-..." nil t)
  require(tree-sitter)
  eval((require 'tree-sitter) t)
  eval-expression((require 'tree-sitter) nil nil 127)
  funcall-interactively(eval-expression (require 'tree-sitter) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Expected behavior**
The `tree-sitter` packages should be properly loaded, and they should offer syntax-highlighting for select languages.

**Notify maintainers**
No one has any particular responsibility for this package. But @adisbladis might be interested in this. 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.3-gnu, NixOS, 21.03pre260232.733e537a8ad (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-21.03pre260232.733e537a8ad"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SebastienWae** [comment]
I'm currently using this, but it stills need some work. 
Languages grammar are downloaded instead of being built, and I'm not happy about the `substituteInPlace` but if the grammar bins are in `site-lisp` directory `emacsWithPackages` will put them in the `load-path`.

```nix
inputs@{ ... }:
final: prev: {
  emacsPackagesFor = emacs: (prev.emacsPackagesFor emacs).overrideScope' (self: super: {
    tsc = prev.symlinkJoin {
      name = "tsc";
      paths = [
        super.tsc
        (prev.rustPlatform.buildRustPackage {
          pname = "tsc-dyn";
          version = "0.13.0";
          src = inputs.tsc-dyn;
          nativeBuildInputs = [ prev.clang ];
          configurePhase = ''
            export LIBCLANG_PATH="${prev.llvmPackages.libclang}/lib"
          '';
          postInstall = ''
            LIB=($out/lib/libtsc_dyn.*)
            TSC_PATH=$out/share/emacs/site-lisp/elpa/tsc-${super.tsc.version}
            install -d $TSC_PATH
            install -m444 $out/lib/libtsc_dyn.* $TSC_PATH/''${LIB/*libtsc_/tsc-}
            echo -n $version > $TSC_PATH/DYN-VERSION
            rm -r $out/lib
          '';
          cargoSha256 = "sha256-XO+djObxQCnAEgwBjAYnywWbYZ1i8fXgTfOTTUdTmac=";
        })
      ];
    };
    tree-sitter-langs = prev.symlinkJoin rec {
      name = "tree-sitter-langs";
      paths =
        let
          tree-sitter-grammars = prev.stdenv.mkDerivation rec {
            name = "tree-sitter-grammars";
            version = "0.9.0";
            src = prev.fetchzip {
              name = "tree-sitter-grammars-linux-${version}.tar.gz";
              url = "https://dl.bintray.com/ubolonton/emacs/${src.name}";
              sha256 = "sha256-tcqTfUfz/uifwsKkeL9nQ4WXgyid781SONHlguKmRC4=";
              stripRoot = false;
            };
            installPhase = ''
              install -d $out/langs/bin
              install -m444 * $out/langs/bin
              echo -n $version > $out/langs/bin/BUNDLE-VERSION
            '';
          };
        in
        [
          (super.tree-sitter-langs.overrideAttrs (oldAttrs: {
            postPatch = oldAttrs.postPatch or "" + ''
              substituteInPlace ./langs/tree-sitter-langs-build.el \
              --replace "tree-sitter-langs-grammar-dir tree-sitter-langs--dir"  "tree-sitter-langs-grammar-dir \"${tree-sitter-grammars}/langs\""
            '';
          }))
          tree-sitter-grammars
        ];
    };
  });
}
```

**Comment by leungbk** [comment]
Unstale

**Comment by natto1784** [comment]
facing the same issue

**Comment by natto1784** [comment]
ok so the module tries to download the prebuilt binary when emacs first starts

**Comment by natto1784** [comment]
ok so the module tries to download the prebuilt shared binary when emacs first starts, and stores the version number of the binary in a file called "DYN-VERSION". This is the overlay I'm using right now along with tree-sitter-langs overlay written above instead of compiling the binary with clang.
```nix
        tsc = epkgs.melpaPackages.tsc.overrideAttrs(oa: 
        let 
          version = "0.15.2";
          tsc-dyn = fetchurl {
            url = "https://github.com/emacs-tree-sitter/elisp-tree-sitter/releases/download/${version}/tsc-dyn.so";
            sha256 = "sha256-oOq/TAooHRUo7JypCblrB/ztABowAHv2LRhFL/ZmVrg=";
          };
          version-file = writeText "DYN-VERSION" version;
        in {
          src = fetchFromGitHub {
             owner = "emacs-tree-sitter";
             repo = "elisp-tree-sitter";
             rev = version;
             sha256 = "sha256-dGWg4dj+85kxytvm+nNEJUN9UXdr9L6pSRz5OqDMFAM=";
          };
          postInstall = ''
            cp ${tsc-dyn} $out/share/emacs/site-lisp/elpa/tsc-${oa.version}/tsc-dyn.so
            cp ${version-file} $out/share/emacs/site-lisp/elpa/tsc-${oa.version}/DYN-VERSION
          '';
        });
```

**Comment by dhess** [comment]
Same. What's going on with this issue?

**Comment by pimeys** [comment]
So, I've been looking into this a bit and kind of understand what should be done, but haven't been able to create enough code for a working PR yet.

So, basically what you want is to build a rust package from here:
https://github.com/emacs-tree-sitter/elisp-tree-sitter/tree/master/core

The result of the build is `libtsc_dyn.(dll|so|dylib)` and this needs to be built as a dependency for `emacsPackages.tree-sitter` so the file is available for it as `tsc_dyn.(dll|so|dylib)`. I think it should be enough to link whatever file gets compiled from `tsc` to the `${pkgs.emacsPackages.tree-sitter}/bin` if I read the code correctly.

Then, the next is to link all the compiled tree-sitter grammars for the emacs package to find, something copied from how the neovim plugin does this:

```nix
tree-sitter = super.tree-sitter.overrideAttrs (attrs: {
  postInstall =
    let
      grammars = with pkgs; tree-sitter.withPlugins (plugins: tree-sitter.allGrammars);
    in
    ''
      ln -s ${grammars} $out/share/emacs/site-lisp/elpa/tree-sitter-${attrs.version}/bin
    '';
});
```

I'm not completely sure where to build all these packages and I'm running out of my personal time to get this working together. What I see in the current state is many packages linking `tsc` as a dependency, but `tsc` is just building the `elisp-tree-sitter` emacs package, not using `cargo` to build whatever is in the `core` directory and linking the resulting library for the lisp libraries.

And the grammars are already in the nixpkgs, you just need to link them to a place where the emacs tree-sitter plugin can find them.

**Comment by pimeys** [comment]
Hey all. I'm still working on fixing this due to me needing tree-sitter for my emacs setup and wanting to understand nix more.

Here's the work so far: https://github.com/pimeys/nixpkgs/commit/c95778bb3bc86b0a0fa9cba802e26792d246ec41

It now compiles the rust module correctly, and uses the linking strategy from @SebastienWae for the languages. It still tries to download files from github, so I either don't link the files to the correct location, or I should patch a method to prevent the download process.

I think the best solution would be to use the grammars already available in the monorepo the same way as `nvim-treesitter` does. My first try with them was with `allGrammars`, but some of them won't work together with the emacs library due to licensing issues. And I also got myself to the download problem, but I think this is not due to files not being the pre-compiled ones from github, but again about some linking issues.

If somebody wants to try this out and give me feedback, I'm all ears. I will probably spend some Christmas holiday spare time to make the PR happen. It is very close already.

**Comment by pimeys** [comment]
I made a PR and now it works at least on my NixOS laptop. It would still be nice if we could either utilize the grammars already available in nix, or at least we'd be able to compile them in the derivation instead of just downloading the binaries. I'd be happy if you could try this out and see if it works for you.
