### ISSUE TITLE
emacsWithPackages without X dependencies

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#10811]
Is there a way to install emacsWithPackages without X dependencies?

I have tried the following without success:

- config.environment.noXlibs = true;

- ((emacsWithPackages.override {emacs = emacs24-nox;}) (with emacsPackages; [bbdb]))

Interrestingly, this doesn't pull any X dependencies:

- ((emacsWithPackages.override {emacs = emacs24-nox;}) (with emacsPackages; []))

so is there a way to specify emacs24-nox also for the emacsPackages?

Or could emacsPackages respect the noXlibs config?

**Comment by peti** [comment]
`emacsWithPackages.override { emacs = emacs24-nox; }` gives you a variant of the `emacsWithPackages` function that uses the no-X-emacs.

**Comment by peti** [comment]
Oh, and `emacsNoxPackages = emacsPackagesGen emacs24-nox emacsNoxPackages` gives you a package set compiled with the no-X-emacs.

**Comment by tohl** [comment]
Thank you for your suggestions.  However, neither of them work:

a) emacsWithPackages.override { emacs = emacs24-nox; } installs emacs without X. However, as soon as I specify single emacs package, it pulls X dependencies, as described in the original report.

b) emacsNoxPackages = emacsPackagesGen emacs24-nox emacsNoxPackages does not work.  There is no emacsNoxPackages package.  I suppose you meant emacsNoxPackages = emacsPackagesGen emacs24-nox emacsPackages but that still pulls X dependencies.

**Comment by tohl** [comment]
btw is there a way to reopen this ticket?

**Comment by tohl** [comment]
Here are the dependencies, which I dont want to be pulled:

these derivations will be built:
  /nix/store/cr6g5daqp7phpx672ijvbmfrczna73fw-kbproto-1.0.7.tar.bz2.drv
  /nix/store/2kdz3r9wc8mngagp4gbx6x9if2aab6dl-kbproto-1.0.7.drv
  /nix/store/7qpxymvxvrxdj0rpdfc16cwlsm474kd2-libX11-1.6.3.tar.bz2.drv
  /nix/store/45m26dwibqzr11rpcgcfladz57rlwp23-inputproto-2.3.1.tar.bz2.drv
  /nix/store/83kzi4g23w74sl133g51ahss22p9ff7a-inputproto-2.3.1.drv
  /nix/store/7cz3jjmzbqfcpk2j7xj22g1z15cg2nl5-xtrans-1.3.5.tar.bz2.drv
  /nix/store/krw3qh2p3x27s5sgb0apap5pxyd30da7-xtrans-1.3.5.drv
  /nix/store/6fzdyvyhmn8sgdcyjsq4snyg9jqcgw8q-xf86bigfontproto-1.2.0.tar.bz2.drv
  /nix/store/p0c6isbd8k77a9b02q5d69q0dz010v3w-xf86bigfontproto-1.2.0.drv
  /nix/store/zqsynwinr6zxfxfnpndnyjq3gsc2kvm8-xextproto-7.3.0.tar.bz2.drv
  /nix/store/pmv67058mlkw8pdmcp8a502mfprr8y4n-xextproto-7.3.0.drv
  /nix/store/11bzvvw8qn3l4qsyxpm821x8607w9r1m-xproto-7.0.28.tar.bz2.drv
  /nix/store/vficcqchnh3r4ayvlc7axpq0y4pifhwm-xproto-7.0.28.drv
  /nix/store/r0c652m3csbwfvjry7fm51qpbsmnmlax-libXau-1.0.8.tar.bz2.drv
  /nix/store/a5ml19a0fvnvxy3snbgdq8c2avbi3vjm-libXau-1.0.8.drv
  /nix/store/ad7rzawis7ahpv9my5rwa3jyz9nqyn5l-libxcb-1.11.1.tar.bz2.drv
  /nix/store/2fklpw058c7sfpaavn9zz26isi2ab2fz-xcb-proto-1.11.tar.bz2.drv
  /nix/store/d0zjjllj5inibg4v3qswgcy3pwkvh2v8-xcb-proto-1.11.drv
  /nix/store/4cs05bhp0gzn33r23gn3c3h839b8li4z-libpthread-stubs-0.3.tar.bz2.drv
  /nix/store/dhs00a2nf98qg1di0fx3j34m9wm22n04-libpthread-stubs-0.3.drv
  /nix/store/5l0v1x2n6104s06bq7dliv3nrl1j00g6-libXdmcp-1.1.2.tar.bz2.drv
  /nix/store/li1jfwwfgw2njijy4b22rhnslql7fkqy-libXdmcp-1.1.2.drv
  /nix/store/w92knilwh3j8df9f8mzd06glq0sffb8r-libxcb-1.11.1.drv
  /nix/store/05sqrny0mg193pr8qbw07z9im8gdm7rf-libX11-1.6.3.drv
  /nix/store/0ffwvygk6jyr8qmisi2ya71i78bxkqsk-libXext-1.3.3.tar.bz2.drv
  /nix/store/m32h01b0rgdzn86zrfpy38v32397na2m-db-5.3.28.tar.gz.drv
  /nix/store/nsdhjk0g0hsg6qxvjgm9mj6zqk8n48d3-db-5.3.28.drv
  /nix/store/vf9mapdbh3c7fbiv6bkpd59cxdcbaisv-cyrus-sasl-2.1.26.tar.gz.drv
  /nix/store/j7f6v1s3jibplpi4p612yj3pvfbvrkha-bison-3.0.4.tar.gz.drv
  /nix/store/23nyqf60illm6zc5w9bhw2rrp5gd95ad-bison-3.0.4.drv
  /nix/store/sx2ayw35xmh85jcxkwi2c3xwyfwhx439-krb5-1.13.2-signed.tar.drv
  /nix/store/z7l9r33clmi56ykcljadg53v6jrz4sfi-libkrb5-1.13.2.drv
  /nix/store/iijkjk00h7099bxi3vdpli3y1hkip8zd-cyrus-sasl-2.1.26.drv
  /nix/store/sqabqnq1hrj0fij99wdgj087axcanbs9-openldap-2.4.42.tgz.drv
  /nix/store/bksakqhqahc1hnbfkzb7688b55ifaq4w-openldap-2.4.42.drv
  /nix/store/igsl5bb9gbkwvr4015ka3krgd0r5s2rx-apr-1.5.2.tar.bz2.drv
  /nix/store/s05m2vf4mfnrfn2il900r787fslzylr2-apr-1.5.2.drv
  /nix/store/ynwniw64a5ljiqvsrsncpbg407xg44af-apr-util-1.5.4.tar.bz2.drv
  /nix/store/4526352c3n94l1yd0dmndw6h2a37h78c-apr-util-1.5.4.drv
  /nix/store/6fs8ij9fdz66pjy9lnpbs8hn7qsqshmx-serf-1.3.7.tar.bz2.drv
  /nix/store/nm57s7a8ad6q7075iq0xpm42ypdkxjxz-scons-2.3.6.tar.gz.drv
  /nix/store/7i9crsjk8nxn2bsp9nps1jxqsal5gln2-scons-2.3.6.drv
  /nix/store/0lp7c7r0w5wqiw0clvs9zsripc602h63-serf-1.3.7.drv
  /nix/store/zwzlk9nbxfg1vrpkd818mfzfszdz70bg-fixesproto-5.0.tar.bz2.drv
  /nix/store/0yf18mdywq39dfcvqxdwsdnhcvb9i8zy-fixesproto-5.0.drv
  /nix/store/9ciyxrypfpl5xn99ipiwxj30am8ma996-libXext-1.3.3.drv
  /nix/store/mvndw1wk2dpgrl3n2z67imjv50bwmn9y-libXrender-0.9.9.tar.bz2.drv
  /nix/store/br89lgrn2w3mdwxzxckmm412q06h7ls7-renderproto-0.11.1.tar.bz2.drv
  /nix/store/vqaw8fh3wvdzn2b8m8mbwvh8gzskbh1x-renderproto-0.11.1.drv
  /nix/store/acl474zqvipgd0sqy2byfqmx753d47wk-libXrender-0.9.9.drv
  /nix/store/dpaidqp6mngars5xmrlh24yx4467al4x-libXrandr-1.5.0.tar.bz2.drv
  /nix/store/9b7f0bzlqbd46773dwn5vzmna6r9hrn3-randrproto-1.5.0.tar.bz2.drv
  /nix/store/i4223ypzhzh8kgjf03475i9n78c66cwp-randrproto-1.5.0.drv
  /nix/store/0yym8azamgkdh2gw1a4jjgkyn3krwa1k-libXrandr-1.5.0.drv
  /nix/store/38i6qvzg99kv24cb2gkjhgxk6n5bqlfz-04-infinality-2.5.4-2014.12.07.patch.drv
  /nix/store/7qy7vkvvghxhj51lc7jiq2nw6lr0f5mp-libpng-1.6.18-apng.patch.gz.drv
  /nix/store/drzvd2vh2ylcwcdlr6vn1ahvvdqyiz51-libpng-1.6.18.tar.xz.drv
  /nix/store/7p4a00xxia9bj5lb6fdnszl8p178pjwm-libpng-apng-1.6.18.drv
  /nix/store/cxqbfh594bhwq4pgiqa4ch9qy488cfxc-freetype-2.5.4.tar.bz2.drv
  /nix/store/62rzqqgdsbil0qvsj2dmla3knf5g3mn7-freetype-2.5.4.drv
  /nix/store/sxz335shy45zfakvp18zi2ccnn6xlb64-mkfontscale-fix-sig11.patch.drv
  /nix/store/w0ga05c6fzaqjh45pp44jzpxm52xpxn5-mkfontscale-1.1.2.tar.bz2.drv
  /nix/store/vv46ff96ivhvbfsk1xkvmym4npjhys4j-libfontenc-1.1.3.tar.bz2.drv
  /nix/store/zr50bh2y2k8m68jb6qv058c5z426dlrm-libfontenc-1.1.3.drv
  /nix/store/13i8rhlknr130lv6zkn2kyiyh8aa9dii-mkfontscale-1.1.2.drv
  /nix/store/1wi54fjvln6zikky6zqblkbn7pg3yv97-compositeproto-0.4.2.tar.bz2.drv
  /nix/store/qywq0rphlzllnsw66bkyhigb0bfk0vfv-libSM-1.2.2.tar.bz2.drv
  /nix/store/ymxy4hg50s1ddc8gvsz295nfqpjz3qbz-libICE-1.0.9.tar.bz2.drv
  /nix/store/svj1p3al1bccbdzr4afqvy0aqnnc1w59-libICE-1.0.9.drv
  /nix/store/23793ycajsw15blqwq09hslq31qjkkv8-libSM-1.2.2.drv
  /nix/store/dp6c8hjaw09gbk8g9cg9f6flr4xqqa37-flex-2.5.39.tar.bz2.drv
  /nix/store/36frncm51gyaw8cyx152q5lnqkg6cdv6-flex-2.5.39.drv
  /nix/store/smx7j9ihxlnrgk97pnbib0p9akj979q7-gobject-introspection-1.44.0.tar.xz.drv
  /nix/store/4x6v014vqk9a9qff24vr34ya503ssdqn-gobject-introspection-1.44.0.drv
  /nix/store/5ilb5fz397qa45hy8bck0aaj9s0yz1j6-gdk-pixbuf-2.31.7.tar.xz.drv
  /nix/store/6fyjw9875xd6nxxh8hp3wf61v9r9vl4d-tiff-4.0.6.tar.gz.drv
  /nix/store/jkd52mj50ag6hg3b1gb6gxy662bwbybz-libjpeg-turbo-1.4.1.tar.gz.drv
  /nix/store/rrdwi0ky7jbig11y7ikg7fak1yhfm7fy-nasm-2.11.08.tar.bz2.drv
  /nix/store/lkmbvc0wi0ppfb0iv95wdhrq9mh1axdf-nasm-2.11.08.drv
  /nix/store/r8dyyaa8ifxn40y4fpdqpggn1zgplznd-libjpeg-turbo-1.4.1.drv
  /nix/store/7cswsd6nhq4m1knrlq34l7bqfvsaa3j0-libtiff-4.0.6.drv
  /nix/store/8nmw7s4cfp4vyi8192xpjr8azjbfv1j5-jasper-1.900.1.zip.drv
  /nix/store/qdx1g5wspnnzv5nbirjl0w7cm91nxd2p-jasper-1.900.1.drv
  /nix/store/353za21bmz01qvrb0nryalw2qpjfhqgm-gdk-pixbuf-2.31.7.drv
  /nix/store/3r2najsnqb3mc8vnm3a32nvq5i8sqa0p-libXcomposite-0.4.4.tar.bz2.drv
  /nix/store/qypsfqg2q1j61jd035vqa601gmrdvgh5-subversion-1.9.2.tar.bz2.drv
  /nix/store/bwqyrl2i9j0g99jx2ijykc7i306r65wg-subversion-1.9.2.drv
  /nix/store/3w846x1npkalk14n2wm5l0kmj6cfmdbr-ctags-r816.drv
  /nix/store/3z6jgpbrhd1maxsynjf77l7is5r4h7wx-libXmu-1.1.2.tar.bz2.drv
  /nix/store/407ciiniaqkfd6dz1iv910z6igwhxkyi-libXi-1.7.5.tar.bz2.drv
  /nix/store/4b4b0m2n5nf8bkg9n0gaiardb6nv6vf7-cairo-1.14.2.tar.xz.drv
  /nix/store/qgj2h9vjxp5nrqzinhd4ji5spycjgqhk-libXfixes-5.0.1.tar.bz2.drv
  /nix/store/4lha0739n6jhh27k4hw1i84319yhx93x-libXfixes-5.0.1.drv
  /nix/store/kk8d484prkhc2fc0ivzv830cmbk74g05-xineramaproto-1.2.1.tar.bz2.drv
  /nix/store/9ysgpcdvb08fa3c3sszs3gpkkydhn6iq-xineramaproto-1.2.1.drv
  /nix/store/n8zzs0489vsgq5fm293l2i359zk7x0f6-libXinerama-1.1.3.tar.bz2.drv
  /nix/store/4myj8i944dp2v0ynz18v8vm6mfspc809-libXinerama-1.1.3.drv
  /nix/store/4y5b2dj6shh3mkgnyyv50p8g6ziyflpl-librsvg-2.40.9.tar.xz.drv
  /nix/store/5pjj32zx955g3c7r8y6n8c7li6c2pfdm-libcroco-0.6.8.tar.xz.drv
  /nix/store/5sfvyg65nakbw4hrf4igr205pmlg7kpy-libdaemon-0.14.tar.gz.drv
  /nix/store/616709m7902937y684yfh8wih8xjnqn9-mkfontdir-1.0.7.tar.bz2.drv
  /nix/store/9iwvy0p8vpamydknfz32c1va38iajr91-libpaper_1.1.24.tar.gz.drv
  /nix/store/6ay5f2l9iwdgis8g2fnc78cyv6d0j025-libpaper-1.1.24.drv
  /nix/store/6ccawb4vm52kwjlhw4f6p2w03b2115df-libungif-4.1.4.tar.gz.drv
  /nix/store/6cm9qljqqfq6yrww1whn0ldc3kyizwik-pixman-0.32.6.tar.gz.drv
  /nix/store/71m1p382hizdxmgwrfh3js82gwhrnlly-libXft-2.3.2.tar.bz2.drv
  /nix/store/7vwdj214zsykd0p2iqyjcwwq9mhvg4qp-libdaemon-0.14.drv
  /nix/store/7ybxx8wpaz5l29jgq0hwglzn9dp89lbk-ctags-816.drv
  /nix/store/hxdi5vnpkh3gff5p44gdfyx9903bjn73-libXt-1.1.5.tar.bz2.drv
  /nix/store/bxzmhn9fx3k2xjkxi19l0yh0r0pj1asy-libXt-1.1.5.drv
  /nix/store/ikc7y2n5scqckrcq98p353xgq8gwzcpa-libXpm-3.5.11.tar.bz2.drv
  /nix/store/8mh6bw2kvixgvfpn9k2lym7iyg3xm7ip-libXpm-3.5.11.drv
  /nix/store/k4sfvv29rabw604nmf7l3hwda6wsmcp8-cups-2.0.4-source.tar.bz2.drv
  /nix/store/pigicjnwffiadgaskl3d6vsrvxkqn1qn-avahi-0.6.31.tar.gz.drv
  /nix/store/y9m8q5kqv82491y6dkdp1w070cmf4gsn-avahi-0.6.31.drv
  /nix/store/a8r5j6fn8pg5vxps3ny841qagc1zqwc0-cups-2.0.4.drv
  /nix/store/bfibs802fcqqh08sghq2yfkhqkwd48hw-pango-1.36.8.tar.xz.drv
  /nix/store/ik9p7dj2k6yvj9r72h2l77wbjl711liz-mkfontdir-1.0.7.drv
  /nix/store/p6y427bxi438fsmiy9h0wf8hcsv3smas-font-bh-ttf-1.0.3.tar.bz2.drv
  /nix/store/hx19bvhdbhfk4l9w02xpmwnll9xzawr7-font-bh-ttf-1.0.3.drv
  /nix/store/iq2z0b4jnj7y1w0cy563a9h76lkwm6zs-config-compat.patch.drv
  /nix/store/sl5jymhqggnm2l74zv9w9cmpa86y0lw0-fontconfig-2.11.1.tar.bz2.drv
  /nix/store/v4ka0g4wnwbxa0mvr86yi2a7hx5czrgn-fc-cache-bug-77252.patch.drv
  /nix/store/xsa7n1qg51ai7vgfj67c5j5q6m5d9qhh-fontconfig-2.11.1.drv
  /nix/store/q3p5ndnf9f8fz2s32jispzcvsc90n5x7-libXft-2.3.2.drv
  /nix/store/l867dygc307rnimp0jrq8p81g0632f6p-xlibs-wrapper.drv
  /nix/store/sd304p1f0q1dnk14kw6apjhljbg70qn9-sharutils-4.11.1.tar.bz2.drv
  /nix/store/hbymvswgvzsd4630kglckf9gz3w1nlnh-sharutils-4.11.1.drv
  /nix/store/pv1dbdpjm14fprzczz4qffpc1r0fgabq-libarchive-3.1.2.drv
  /nix/store/v86hp4b86mxz297d77hpd0wfjqiyw62v-cmake-3.3.2.drv
  /nix/store/w5lmf3p5p743gsw0vv4r9vazl2nzvsnl-graphite2-1.2.4.tgz.drv
  /nix/store/b90qp9z275g4qyk9jfjad6v3kdlipf5h-graphite2-1.2.4.drv
  /nix/store/vcypfmyb8pqp1ag1y0m8waxcq2ysj3fy-harfbuzz-1.0.3.tar.bz2.drv
  /nix/store/agvg2k02czpxwwfgxdhmlnhvcdf2wmvs-pixman-0.32.6.drv
  /nix/store/gmi614x14g4w74jjl7923wl6jvg97cgl-xcb-util-0.4.0.tar.bz2.drv
  /nix/store/mll71z7adwm3gar6l9xms6czrv5a256d-xcb-util-0.4.0.drv
  /nix/store/yavdfa3gacq3a76m191czxs22dslk0fi-cairo-1.14.2.drv
  /nix/store/n9svvivqzzhkgic2i1gb34y979hr7wb6-harfbuzz-1.0.3.drv
  /nix/store/byip5vsdh75vw9dbq7177vpn05jw7bhh-pango-1.36.8.drv
  /nix/store/jrpml12wfag6vdaz1b2jr9w48m1nck3i-compositeproto-0.4.2.drv
  /nix/store/imc51z2aay35l91k1jycnbkllaynbym1-libXcomposite-0.4.4.drv
  /nix/store/q9dy8ks3n9im7s29r43iikhm2b1xvijr-gtk+-2.24.28.tar.xz.drv
  /nix/store/qj1mlxs4wwjk28kcqbfq4rqflxj2nnvz-libXi-1.7.5.drv
  /nix/store/j582m1gnqmwnqnhda8f6wx63c8b6ap47-libXcursor-1.1.14.tar.bz2.drv
  /nix/store/s6rdqjs1pxvvv9hq8mf17v859gw0dyay-libXcursor-1.1.14.drv
  /nix/store/nmv8xmrzid7c411yxh95c328mzd3pv9r-atk-2.16.0.tar.xz.drv
  /nix/store/s7zskhyafx1c21n5r7fykbq4is1w7fmc-atk-2.16.0.drv
  /nix/store/9lllysp7vwhy403vg0974hqpsf73cxc3-gtk+-2.24.28.drv
  /nix/store/azbil9vraipccdx00ikf4flcv7clkbgx-libungif-4.1.4.drv
  /nix/store/gk042jll9lnnz5mkd291pzk5y28kckmb-libXaw-1.0.13.tar.bz2.drv
  /nix/store/mshmgp7cyx8rzs8q8gn04jkfjbc9ygrl-libXmu-1.1.2.drv
  /nix/store/f6cgas9dv3k6ghyn5k89h8dqp75lybmr-libXaw-1.0.13.drv
  /nix/store/j0831d9r2x5m44p11zq5f4mvyzcyvrs8-libcroco-0.6.8.drv
  /nix/store/vlq1m4m6p5xwkhbgszc5hlc2dh3qbcgx-libgsf-1.14.34.tar.xz.drv
  /nix/store/p8m3j18f5nb51mjp425cbqrxwx20by04-libgsf-1.14.34.drv
  /nix/store/khksjjkp27glb41x5cc9ar3sr4qmw21a-librsvg-2.40.9.drv
  /nix/store/z23najhyq2jz4r0z9ik6q5w9vqyq99yd-emacs-24.5.drv
  /nix/store/ygwhs846rqmajpgaidwzc3ym8qij2r3i-bbdb-2.36.drv
  /nix/store/hdqrhp0k5d9p46a6b164hk0imsrvqqir-emacs-nox-with-packages-24.5.drv

**Comment by tohl** [comment]
This doesnt work either:

- ((emacsWithPackages.override {emacs = emacs24-nox;}) (with (emacsPackagesGen emacs24-nox emacsPackages); [bbdb]))

**Comment by tohl** [comment]
I suspect that the overrides don't make it down to the emacs package level. You might still get emacs without X but the build depends on X libraries, because the emacs packages pull those via un-overrided emacs dependency. This is unfortunate for those who want emacs without X on a server or on systems, where X doesn't build (e.g. on ARM).

**Comment by tohl** [comment]
This works:

- ((emacsWithPackages.override {emacs = emacs24-nox;}) [(emacsPackages.bbdb.override {emacs = emacs24-nox;})])

so the only way to achieve that is to explicitly override emacs for each emacs package.

**Comment by peti** [comment]
I am sorry, I guess I should have posted a more complete example how to achieve the desired outcome. Put this code into your `~/.nixpkgs/config.nix` file:

~~~~~
{
  packageOverrides = super: let self = super.pkgs; in {
    emacsWithNoXPackages = super.emacsWithPackages.override { emacs = self.emacs24-nox; };
    emacsNoXPackages = self.emacsPackagesGen self.emacs24-nox self.emacsNoXPackages;
    emacsNoX = self.emacsWithNoXPackages [self.emacsNoXPackages.bbdb];
  };

}
~~~~~

Now install `nix-env -iA emacsNoX`.

**Comment by tohl** [comment]
Thank you very much for the great example, Peter!  This works great.
