### ISSUE TITLE
`machinectl pull-tar` doesn't work anymore

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#108158]
**Describe the bug**
I'm unable to pull an image via `machinectl pull-tar` - this used to work in 20.03 IIRC.
The following error is produced (both in the terminal as well as in the journal of `systemd-importd`):

```
Failed to rename to final image name to /var/lib/machines/.tar-https:\x2f\x2fnspawn\x2eorg\x2fstorage\x2fubuntu\x2fbionic\x2ftar\x2fimage\x2etar\x2exz.\x22q9k48qdh3s4\x22: Read-only file system
```

**To Reproduce**
1. run `machinectl pull-tar --verify=checksum https://nspawn.org/storage/ubuntu/bionic/tar/image.tar.xz`

**Expected behavior**
The image is pulled just fine and ready to be used.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.18, NixOS, 20.09.2405.e065200fc90 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2405.e065200fc90, nixos-unstable-21.03pre257780.e9158eca70a"`
 - channels(wucke13): `"nixos-unstable-21.03pre246062.420f89ceb26, nixpkgs-unstable-19.09pre170896.6e5caa3f8ac, nixos-unstable-small-19.03pre161392.50bb0afa7ce"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ryanofsky** [comment]
I'm seeing the same bug. I'm not sure exactly how this results in the read-only file system error but on a non-nixos system I observe temporary files being written to paths like:

```
/var/lib/machines/.#tard03fabc7d2666278/var/...
```

while on nixos the temporary paths instead look like:

```
/var/lib/machines/.#/nix/store/sg7xqwqwg9aizcl4mcg7w1kkiwxrvg06-gnutar-1.34/bin/tar6aea77d8a9d43b6c/var/...
```

Aside from the fact that the paths are extra long and nested I don't see where the read-only file system error comes from, but clearly the systemd-import code is getting confused by the nix package layout and trying to read and write things to weird places.

**Comment by ryanofsky** [comment]
```
wget URL
machinectl import-tar FILENAME
```

does seems to function as workaround for

```
machinectl pull-tar URL
```

**Comment by Artturin** [comment]
After writing this comment i searched systemd issues and found this https://github.com/systemd/systemd/issues/21397 which matches the current issue. not sure about the issue reported in this issue though


~~
Now it fails with
```
Failed to rename to final image name to /var/lib/machines/.tar-https:\x2f\x2fnspawn\x2eorg\x2fstorage\x2fubuntu\x2fbionic\x2ftar\x2fimage\x2etar\x2exz.\x221408658-5d118bf3c7776\x22: Operation not permitted
```

some relevant sections

https://github.com/systemd/systemd/blob/14efbfd96d67800e55137f89ec7a09d81049d176/src/import/pull-tar.c#L507

https://github.com/systemd/systemd/blob/14efbfd96d67800e55137f89ec7a09d81049d176/src/basic/tmpfile-util.c#L171 

```
sudo tree -a /var/lib/machines -L 6
/var/lib/machines
└── .#
    └── nix
        └── store
            └── nwg8in201f7y6vdm787v3j84jjrn0ayw-gnutar-1.34
                └── bin
                    ├── tar3c6aa310bf327def
                    ├── tar80aa3b07a301ea7d
                    ├── tar90f1cd9bf4e97f5d
                    ├── tar93245c3df854b83d
                    ├── tarb7cad9f91851bff4
                    └── tard8cfa9405bc42866
```
~~

**Comment by flokli** [comment]
As said in https://github.com/systemd/systemd/issues/21397#issuecomment-971714862, https://github.com/systemd/systemd/commit/c40d82abf7b23803aa7394a7a7e24c40c32af851 should have fixed this.

Unfortunately, it was never backported to any 249.x stable release, but can you check if https://github.com/NixOS/nixpkgs/pull/150491 fixes it for you?

**Comment by flokli** [comment]
We could probably also extend `nixos/tests/systemd-nspawn.nix` to invoke `machinectl pull-tar`, to produce an easy regression test…

**Comment by flokli** [comment]
At least in current master (systemd 250.4), this seems fixed.

I extended the test case, it now also invokes `machinectl pull-tar`, and verifies extracting works as expected.

PR up at https://github.com/NixOS/nixpkgs/pull/171822.
