### ISSUE TITLE
qutebrowser tab crashes on certain websites

### ISSUE THREAD

**Issue by afreakk** [NixOS/nixpkgs#108227]
**To Reproduce**
1. visit https://www.tradingview.com/ with qutebrowser
2. tab then crashes and shows
```
Unable to load page
Error while opening https://www.tradingview.com/
Renderer process was killed
```
In stderr it outputs 
```
libpng warning: iCCP: known incorrect sRGB profile
[2369:2369:0102/160144.650878:ERROR:render_process_host_impl.cc(5024)] Terminating render process for bad Mojo message: Received bad user message: No binder found for interface blink.mojom.InstalledAppProvider for the frame/document scope
[2369:2369:0102/160144.651366:ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
16:01:44 ERROR: Renderer process was killed
```
Not quite sure if its something wrong with webengine, or qutebrowser, or the nix-package.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.85, NixOS, 21.03pre260232.733e537a8ad (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre260232.733e537a8ad"`
 - channels(afreak): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by svrana** [comment]
This looks to be https://github.com/qutebrowser/qutebrowser/issues/5997

**Comment by The-Compiler** [comment]
Upstream here - yep, it's that, and essentially a bug in QtWebEngine 5.15.2. There's a workaround in qutebrowser v2.0.0 (which I just released), but (as mentioned over there) you can also add `disable-features=InstalledApp` to `qt.args` as a workaround with older qutebrowser versions.

**Comment by afreakk** [comment]
This seem to not happen anymore with qutebrowser from master branch, so closing.
