### ISSUE TITLE
libcap 2.27 -> 2.44: breaks security wrapper for cap_dac_override

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#108228]
**Describe the bug**
After update libcap from `2.27` to `2.44` error working capabilites.
```
2021-01-02 18:10:15: /nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin ERROR : MAIN : PROCFILE: Cannot open file '/proc/slabinfo' (errno 13, Permission denied)
2021-01-02 18:10:15: /nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin ERROR : MAIN : <- Cannot open file '/proc/slabinfo
```
and
```
cat /proc/slabinfo
cat: /proc/slabinfo: Permission denied
```

Netdata configuration:
```
  services.netdata = {
    enable = true;
    config = {
      plugins = {
        "enable running new plugins" = "no";
        "proc" = "yes";
        "diskspace" = "no";
        "cgroups" = "no";
        "tc" = "no";
        "idlejitter" = "no";
        "slabinfo" = "yes";
        "ebpf_process" = "no";
        "charts.d" = "no";
        "nfacct" = "no";
        "fping" = "no";
        "go.d" = "no";
        "ioping" = "no";
        "python.d" = "no";
        "node.d" = "no";
        "perf" = "no";
        "freeipmi" = "no";
        "apps" = "no";
      };
    };
  };
```

Wrappers cat:
```
    security.wrappers.cat = {
      source = "${pkgs.coreutils}/bin/cat";
      capabilities = "cap_dac_override=ep";
    };

```
**Notify maintainers**
cc @Mic92 @flokli @ajs124

**Comment by ajs124** [comment]
If it's being denied by apparmor, it should say something along those lines in the kernel log.

Are you actually running apparmor though?

**Comment by Izorkin** [comment]
The apparmor service is in use. Does not write an error in the logs.

Disabling apparmor service doesn't fixed error:
```
2021-01-02 19:29:35: netdata INFO  : PLUGINSD[slabinfo] : connected to '/nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin' running on pid 12653
2021-01-02 19:29:35: /nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin ERROR : MAIN : PROCFILE: Cannot open file '/proc/slabinfo'  (errno 13, Permission denied)
2021-01-02 19:29:35: /nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin ERROR : MAIN : 
2021-01-02 19:29:35: netdata INFO  : PLUGINSD[perf] : connected to '/nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/perf.plugin' running on pid 12654<- Cannot open file '/proc/slabinfo
```

Worked with this patch:
```
 pkgs/os-specific/linux/apparmor/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/pkgs/os-specific/linux/apparmor/default.nix b/pkgs/os-specific/linux/apparmor/default.nix
index 3ce310acf23..64fa92be865 100644
--- a/pkgs/os-specific/linux/apparmor/default.nix
+++ b/pkgs/os-specific/linux/apparmor/default.nix
@@ -14,7 +14,7 @@

 let
   apparmor-series = "2.13";
-  apparmor-patchver = "6";
+  apparmor-patchver = "5";
   apparmor-version = apparmor-series + "." + apparmor-patchver;

   apparmor-meta = component: with stdenv.lib; {
@@ -27,7 +27,7 @@ let

   apparmor-sources = fetchurl {
     url = "https://launchpad.net/apparmor/${apparmor-series}/${apparmor-version}/+download/apparmor-${apparmor-version}.tar.gz";
-    sha256 = "13xshy7905d9q9n8d8i0jmdi9m36wr525g4wlsp8k21n7yvvh9j4";
+    sha256 = "05x7r99k00r97v1cq2f711lv6yqzhbl8zp1i1c7kxra4v0a2lzk3";
   };

   prePatchCommon = ''

```

**Comment by flokli** [comment]
Sorry, don't maintain neither netdata nor apparmor.

**Comment by Mic92** [comment]
So basically apparmor 2.13.6 introduced this regression?

**Comment by Izorkin** [comment]
Sorry, wrong checked.
Working with branch d4905b1370d, with branch f1c65de110f - not working - f1c65de110f.
Compare - https://github.com/NixOS/nixpkgs/compare/d4905b1370d...f1c65de110f
Looking for a error further.

**Comment by ajs124** [comment]
The diff between these versions is quite small https://gitlab.com/apparmor/apparmor/-/compare/v2.13.5...v2.13.6

I don't think that should be responsible.

**Comment by Izorkin** [comment]
Found. Working with rollback libpcap to `2.27`
```
diff --git a/pkgs/os-specific/linux/libcap/default.nix b/pkgs/os-specific/linux/libcap/default.nix
index 713c4b5d13d..0c989686358 100644
--- a/pkgs/os-specific/linux/libcap/default.nix
+++ b/pkgs/os-specific/linux/libcap/default.nix
@@ -3,11 +3,11 @@

 stdenv.mkDerivation rec {
   pname = "libcap";
-  version = "2.44";
+  version = "2.27";

   src = fetchurl {
     url = "mirror://kernel/linux/libs/security/linux-privs/libcap2/${pname}-${version}.tar.xz";
-    sha256 = "1qf80lifygbnxwvqjf8jz5j24n6fqqx4ixnkbf76xs2vrmcq664j";
+    sha256 = "0sj8kidl7qgf2qwxcbw1vadnlb30y4zvjzxswsmfdghq04npkhfs";
   };

   patches = lib.optional static ./no-shared-lib.patch;

```

**Comment by Izorkin** [comment]
In kernel 5.8 added new capability - `CAP_PERFMON` - https://lwn.net/Articles/812719/
Service netdata with add `CAP_PERFMON` not working:
```
iff --git a/nixos/modules/services/monitoring/netdata.nix b/nixos/modules/services/monitoring/netdata.nix
index db51fdbd2c6..c2f5eb09371 100644
--- a/nixos/modules/services/monitoring/netdata.nix
+++ b/nixos/modules/services/monitoring/netdata.nix
@@ -175,6 +175,7 @@ in {
           "CAP_SYS_PTRACE"        # is required for apps plugin
           "CAP_SYS_RESOURCE"      # is required for ebpf plugin
           "CAP_NET_RAW"           # is required for fping app
+          "CAP_PERFMON"
         ];
         # Sandboxing
         ProtectSystem = "full";
@@ -205,7 +206,7 @@ in {

     security.wrappers."perf.plugin" = {
       source = "${cfg.package}/libexec/netdata/plugins.d/perf.plugin.org";
-      capabilities = "cap_sys_admin+ep";
+      capabilities = "cap_sys_admin,cap_perfmon+ep";
       owner = cfg.user;
       group = cfg.group;
       permissions = "u+rx,g+rx,o-rx";
@@ -213,7 +214,7 @@ in {

     security.wrappers."slabinfo.plugin" = {
       source = "${cfg.package}/libexec/netdata/plugins.d/slabinfo.plugin.org";
-      capabilities = "cap_dac_override+ep";
+      capabilities = "cap_dac_override,cap_perfmon+ep";
       owner = cfg.user;
       group = cfg.group;
       permissions = "u+rx,g+rx,o-rx";
```

**Comment by Izorkin** [comment]
Problem with `libcap` version `2.44`.

**Step to reproduce**
Add to configuration:
```
    security.wrappers.cat = {
      source = "${pkgs.coreutils}/bin/cat";
      capabilities = "cap_dac_override=ep";
    };
```
and running from user:
```
cat /proc/slabinfo
```
In version 20.09 correct work, in master - bad work - `Permission denied`.

**Comment by Izorkin** [comment]
cc libcap contributors - @edolstra @vcunat @dtzWill @matthewbauer @zowoq @expipiplus1 @Ericson2314

**Comment by Izorkin** [comment]
Working with revert this commit - https://git.kernel.org/pub/scm/linux/kernel/git/morgan/libcap.git/commit/?id=177cd418031b1acfcf73fe3b1af9f3279828681c

Need support new output of the `getcap` program from `"= cap_foo+..."` to `"cap_foo=..."`

**Comment by Mic92** [comment]
Maybe also report the bug here, since you have a reproducible bug: https://bugzilla.kernel.org/buglist.cgi?component=libcap&list_id=1047723&product=Tools&resolution=---

**Comment by Mic92** [comment]
cc @AndrewGMorgan since the bug tracker seems to be unused.

**Comment by Izorkin** [comment]
> Maybe also report the bug here, since you have a reproducible bug: https://bugzilla.kernel.org/buglist.cgi?component=libcap&list_id=1047723&product=Tools&resolution=---

This error is not reproducible in another distribution. Checked on ArchLinux - not reproduced.

**Comment by AndrewGMorgan** [comment]
The kernel.org bug tracker **is** used. It is just the case that there are no open bugs right now. Please file a bug there if you believe libcap has a bug. Please include an example sufficient to reproduce it.

**Comment by Izorkin** [comment]
This error reproduced only NixOS. I can build a live-cd with this error. Can you use this variant?

**Comment by Mic92** [comment]
> The kernel.org bug tracker **is** used. It is just the case that there are no open bugs right now. Please file a bug there if you believe libcap has a bug. Please include an example sufficient to reproduce it.

Ok. Thanks. I think this is not a bug but rather an incompatibility regarding cap_to_text output that changed.

**Comment by AndrewGMorgan** [comment]
The output format did become more compact in 2.41. This default output format also changed with the resurrection of meaningful support for `all` in 2.29. That change is potentially more significant:

https://git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=afef3ef1c62613e1cac12a2bbec6017f7d5e033e

Note: the official sources for libcap are here: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/

**Comment by AndrewGMorgan** [comment]
FWIW I would have suggested using the iab abstraction in libcap (introduced in libcap-2.33). What you are trying to do would then look like this:

cap_t working = cap_get_proc();
cap_iab_t iab = cap_iab_init();
cap_iab_fill(iab, CAP_IAB_AMB, working, CAP_PERMITTED);
cap_iab_set_proc(iab);
cap_free(iab);
cap_free(working);

**Comment by Mic92** [comment]
> FWIW I would have suggested using the iab abstraction in libcap (introduced in libcap-2.33). What you are trying to do would then look like this
> 
> cap_t working = cap_get_proc();
> cap_iab_t iab = cap_iab_init();
> cap_iab_fill(iab, CAP_IAB_AMB, working, CAP_PERMITTED);
> cap_iab_set_proc(iab);
> cap_free(iab);
> cap_free(working);

But how does one get the capabilities of a file without string parsing?

**Comment by AndrewGMorgan** [comment]
cap_t working = cap_from_file("/the/file/of/interest");

**Comment by AndrewGMorgan** [comment]
Perhaps I misunderstood? If you want to load the capabilities from a text string and not from the file-capabilities of the file itself:

   cap_t working = cap_from_text("...");

That is, cap_t is libcap's abstraction for a capability set and you are trying to import them from somewhere. There is also a portable binary format cap_copy_ext()/cap_copy_int(). However, there haven't been many users of this - the draft 1e spec intended it for things like tar and cpio to use.

**Comment by Mic92** [comment]
> cap_t working = cap_get_file("/the/file/of/interest");

We basically use both. Our setcap wrapper has capabilities set on its file and it will convert those to ambient capabilities at runtime. It seems that iab abstraction was not there when the original code was written. So there was no obvious way of using cap_t to set ambient capabilities.
