### ISSUE TITLE
Spotify can't connect to the internet 

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#108250]
**Describe the bug**

When launching Spotify, you're stuck in offline mode.

This is what it prints:

```
/nix/store/4rzsppz4691825dq4875xvsk6xjcw5d1-spotify-1.1.46.916.g416cacf1/bin/.spotify-wrapped: /nix/store/ia429zh1fwri3wyq66671i86fqbkhx8q-curl-7.74.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/4rzsppz4691825dq4875xvsk6xjcw5d1-spotify-1.1.46.916.g416cacf1/bin/.spotify-wrapped)
/nix/store/l3ngqlwk5qrczva404kyaxfzls88fkgq-spotify-unwrapped-1.1.46.916.g416cacf1/share/spotify/.spotify-wrapped: /nix/store/ia429zh1fwri3wyq66671i86fqbkhx8q-curl-7.74.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/l3ngqlwk5qrczva404kyaxfzls88fkgq-spotify-unwrapped-1.1.46.916.g416cacf1/share/spotify/.spotify-wrapped)
/nix/store/l3ngqlwk5qrczva404kyaxfzls88fkgq-spotify-unwrapped-1.1.46.916.g416cacf1/share/spotify/.spotify-wrapped: /nix/store/ia429zh1fwri3wyq66671i86fqbkhx8q-curl-7.74.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/l3ngqlwk5qrczva404kyaxfzls88fkgq-spotify-unwrapped-1.1.46.916.g416cacf1/share/spotify/.spotify-wrapped)
/proc/self/exe: /nix/store/ia429zh1fwri3wyq66671i86fqbkhx8q-curl-7.74.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
```

Anyone able to reproduce?

**Additional context**

Tried with state from a working Spotify from a previous Nixpkgs rev and after deleting Spotify's cache & config dirs.

Logging in worked, weirdly.

**Notify maintainers**

@timokau @ma27

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
Please tell us which revs you tried out. This can be done by running `nix-shell -p nix-info --run "nix-info -m"` (as stated in the issue template).

**Comment by Atemu** [comment]
Tried unstable, master and 20.09, so all revs NixOS users would using/basing their trees off of. Maybe should've put that piece of info in but I was more interested in others *not* having the issue.  
Does it work on your machine?

System closure was built using unstable with a few minor patches, merges and backports.

**Comment by Ma27** [comment]
I get the same warnings, however it works fine for me. Maybe try removing any existing cache/state files?

**Comment by jakeisnt** [comment]
I concur, am om unstable with NixOS and all is well.  Try removing all of the spotify configuration in userland and restarting.

**Comment by Atemu** [comment]
Unless there's some spotify state outside of .cache and .config. I did remove it all.

It just randomly started working again though, weird.

Thank you two!

**Comment by peri4n** [comment]
I ran into this recently. Removing ~/.cache/spotify did the trick.
