### ISSUE TITLE
Implement GRUB_SAVEDEFAULT and GRUB_DEFAULT=saved options

### ISSUE THREAD

**Issue by frogamic** [NixOS/nixpkgs#108206]
**Describe the bug**
Not 100% sure this counts as a bug because really it's a feature disparity with upstream GRUB. The issue is it is not possible to easily cause grub to reboot into the same selected menuentry as last time.

**To Reproduce**
1. Install Nix using `boot.loader.grub.enable = true`
2. Look for where to add `GRUB_SAVEDEFAULT=true` and `GRUB_DEFAULT=saved` or an equivalent nix option

**Expected behavior**
Adding `GRUB_SAVEDEFAULT=true` and `GRUB_DEFAULT=saved` to `boot.loader.grub.extraConfig` would add these to a config in `/etc/grub.d/00_custom` or somesuch and then `grub-mkconfig` would be used at install time to generate a `grub.cfg` with savedefault behaviour.

**Additional context**
[More discussion of the problem on Reddit.](https://www.reddit.com/r/NixOS/comments/klahwf/how_do_i_make_grub_remember_the_last_accessed/), another user and I both want this feature, I tried to implement it using the options available.

Possible solutions I see are adding an option to implement this behaviour in `nixos/modules/system/boot/loader/grub/install-grub.pl` directly, thus duplicating the work of upstream grub maintainers, or to rewrite that to use `grub-mkconfig` and probably cause massively breaking changes to the grub options. 

**Notify maintainers**
@edolstra 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.85, NixOS, 20.09.2405.e065200fc90 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2405.e065200fc90"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by AndersonTorres** [comment]
>  thus duplicating the work of upstream grub maintainers

NixOS takes this approach indeed. It prefers to generate the GRUB files directly instead of relying on GRUB generating tools.

**Comment by frogamic** [comment]
Then in that case I guess this is a feature request 🙂
I am new to Nix but would be happy to attempt a PR for a `boot.loader.grub.savedefault` option.

**Comment by SrTobi** [comment]
Hi I'd really like to have this feature and feel compentent enough to try to implement this. If you @frogamic want to attempt it though, I won't want to steal that from you 😃. Are you going to work on this? We can also collaborate if you want.

On a further note:
@AndersonTorres are there normally tests for this kind of functionallity? couldn't find any for the grub generation, but maybe I didn't look hard enough.

**Comment by frogamic** [comment]
Hey @SrTobi go for it, do let me know if I can assist in any way.

**Comment by SrTobi** [comment]
@frogamic I made a PR here: #109302; if you want to have a look.
With this you can activate the safedefault behavior by setting `boot.loader.grub.default = "saved"`.

**Comment by SrTobi** [comment]
@frogamic this feature has been implemented and is now available in the unstable version. you can activate it by settings `boot.loader.grub.default = "saved"`

**Comment by frogamic** [comment]
Outstanding, I have just enabled it and it works perfectly.
