### ISSUE TITLE
Agda doesn't build – hidden package ‘transformers’

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#108376]
**Describe the bug**
On the most recent nixos-unstable (56bb1b0f7a33e5d487dc2bf2e846794f4dcb4d01), Agda does not build, giving error messages such as:

```
src/full/Agda/Utils/Update.hs:23:1: error:
    Could not load module ‘Control.Monad.Trans.Identity’
    It is a member of the hidden package ‘transformers-0.5.6.2’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
23 | import Control.Monad.Trans.Identity
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**To Reproduce**
`nix-build -A agda`

**Additional context**
Commit 54f0a1be81abe1c5c6e16a65de8e892255477bc5 appears to remove the dependency `transformers` from `haskellPackages.Agda`. However, naïvely adding the word `transformers` where it was removed does not fix the issue. Neither does reverting 54f0a1be81abe1c5c6e16a65de8e892255477bc5, or reverting both that and the previous update of hackage-packages.nix 06279ee84f5dd629f9af6362a542aa51e3f88f37.

**Notify maintainers**
@alexarice @abbradar 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.75, NixOS, 21.03.git.73162f1d915 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(james): `"home-manager, nixpkgs-20.09pre242495.3c0e3697520"`
 - nixpkgs: `/home/james/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: agda
# a list of nixos modules affected by the problem
module:
```

**Comment by alexarice** [comment]
Will this be fixed by https://github.com/NixOS/nixpkgs/commit/20a63c490ffe4d7d62ec06469954d184c0731ed8 ?

**Comment by alexarice** [comment]
Just checked and agda copies from cache when I nix-build it from master.

**Comment by alexarice** [comment]
https://github.com/agda/agda/issues/5109 upstream issue

**Comment by cdepillabout** [comment]
This is currently working on `master` (at least from a334367e, but probably before that as well when the `haskell-updates` branch with 20a63c4 was merged into `master`).

Thanks for pointing this out @alexarice
