### ISSUE TITLE
switching users doesn't work since staging merge

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#108313]
**Describe the bug**

Running

`$ su - pbb`

results in the following error:

`su: Module is unknown`

**To Reproduce**
1. Build a nixos vm with two users from master, for example with this nixos-config:

```
{ ... }:

{
  users.users.root.initialPassword = "123";
  users.users.a = {
    isNormalUser = true;
    initialPassword = "123";
  };
  users.users.b = {
    isNormalUser = true;
    initialPassword = "123";
  };
}
```

2. log in as a
3. attempt to switch the user using "su - b"

**Expected behavior**
After entering the correct password, a shell in the requested user should be started.

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/3250809/103478507-87605480-4dc7-11eb-82e0-9e87e3e6965a.png)

**Additional context**
I commented in https://github.com/NixOS/nixpkgs/pull/107783#issuecomment-753126619 before it was merged to raise awareness of this problem.

I hope this will not reach nixos-unstable and lock someone out of their system.

**Notify maintainers**

**Metadata**

`shadow` doesn't have a mantainer, but these people changed it previously:

@NeQuissimus @dtzWill @TredwellGit 

Also pinging @FRidh because this was part of the staging PR

**Comment by FRidh** [comment]
pam was upgraded d703c1ef25775dbe94e9120fe988db24c2df48c3.

**Comment by flokli** [comment]
This PR also seems to also have removed `pam_tally`, while it's still referred in the module system…

**Comment by petabyteboy** [comment]
> pam was upgraded #107185. Could you rebuild and test without that commit?

Indeed, reverting d703c1ef25775dbe94e9120fe988db24c2df48c3 fixes the problem

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/107185#issuecomment-753625243

> We don't need to revert, changing pam_tally to pam_faillock also fixes the su issue.
