### ISSUE TITLE
stdenv: let aarch64 use gcc ≥10

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#108305]
**Describe the bug**
Nixpkgs upgraded to gcc 10 in https://github.com/NixOS/nixpkgs/pull/89793. Unfortunately, there were [issues](https://github.com/NixOS/nixpkgs/commit/22f1c746dfbd9f83f63002f5ad79bc48dec21189) with aarch64 so aarch64 still uses gcc 9.

**Comment by ilya-fedin** [comment]
Is there any progress on this issue? I maintain a package that has ICE with gcc 9 and has #108111 with gcc 10 on aarch64, so it was marked as broken on aarch64 in #173671.

**Comment by ajs124** [comment]
See https://github.com/NixOS/nixpkgs/pull/167726#issuecomment-1108264067

**Comment by dotlambda** [comment]
In https://github.com/NixOS/nixpkgs/pull/153329 adding `gcc11` to `nativeBuildInputs` did the trick.

**Comment by ilya-fedin** [comment]
:thinking: changing stdenv to gcc11Stdenv doesn't work?

**Comment by dotlambda** [comment]
> 🤔 changing stdenv to gcc11Stdenv doesn't work?

True. That's a cleaner solution if it does work in your case.

**Comment by K900** [comment]
Another blocker: https://github.com/NixOS/nixpkgs/pull/191357

**Comment by K900** [comment]
Another victim: https://github.com/NixOS/nixpkgs/pull/210859

**Comment by roberth** [comment]
Another victim:
 - https://github.com/NixOS/nix/pull/7203

**Comment by roberth** [comment]
Potential solution:
 - https://github.com/NixOS/nixpkgs/pull/209870
 
(If I may summarize what can be inferred from the issue page)

**Comment by amjoseph-nixpkgs** [comment]
FWIW the commit message and leading comment for #209870 both contain this text:

```
- Closes #108305
```

but for some reason github isn't processing it.

**Comment by ilya-fedin** [comment]
> but for some reason github isn't processing it.

![изображение](https://user-images.githubusercontent.com/17829319/218330617-cd08a11a-0876-4e50-85de-1fe1401d965f.png)

**Comment by K900** [comment]
Github is having a pretty bad day it seems, it'll probably catch up in a bit.

**Comment by amjoseph-nixpkgs** [comment]
> but for some reason github isn't processing it.

Specifically, this PR doesn't show a "merging #209870 may close this bug" or list this as a "linked issue" of that PR.  It should say "Development Successfully merging this pull request may close these issues: #209870"

For an example of what it should look like, check out e.g. number 216163 (no hyperlink to avoid noise in that PR).

**Comment by K900** [comment]
Note to self: https://github.com/NixOS/nixpkgs/pull/211767/commits/6d6a98068ff9a491be1bc5c602f26cc3d36607f0 will need to be reverted when any of the solutions land.

**Comment by dotlambda** [comment]
@wegank Can you link the PR in which this was fixed?
