### ISSUE TITLE
Hyperion packaging request

### ISSUE THREAD

**Issue by Split7fire** [NixOS/nixpkgs#108333]
**Project description**
Hyperion is an open source ambient light software. Hyperion is an opensource Bias or Ambient Lighting implementation which you might know from TV manufacturers. It supports many LED devices and video grabbers.

**Metadata**

* homepage URL: https://docs.hyperion-project.org/
* source URL: https://github.com/hyperion-project/hyperion.ng
* license: MIT
* platforms: Linux, Darwin, Windows

**Comment by breuerfelix** [comment]
bump, maybe i will work on this one time since i am using it myself

**Comment by Algram** [comment]
@Split7fire and @breuerfelix would you mind checking this PR here if hyperion is working for you correctly?

https://github.com/NixOS/nixpkgs/pull/168897
