### ISSUE TITLE
foliate: eBook viewer

### ISSUE THREAD

**Issue by anonimasusan** [NixOS/nixpkgs#108461]
**Project description**
A simple and modern eBook viewer for Linux desktops

**Metadata**

* homepage URL: https://johnfactotum.github.io/foliate/
* source URL: https://johnfactotum.github.io/foliate/
* license: bsd
* platforms: linux

**Comment by nagy** [comment]
I have started this here in my NUR repository: https://github.com/nagy/nur-packages/blob/foliate/pkgs/foliate/default.nix

However, I am getting this error when starting the binary:
```
(.com.github.johnfactotum.Foliate-wrapped:29964): Gjs-CRITICAL **: 14:31:50.457: JS ERROR: ImportError: No JS module 'main' found in search path
@/nix/store/ln5all7k93hpw1plxawq996r1rkiwvcs-foliate-2.5.0/bin/.com.github.johnfactotum.Foliate-wrapped:9:1


(.com.github.johnfactotum.Foliate-wrapped:29964): Gjs-CRITICAL **: 14:31:50.457: Script /nix/store/ln5all7k93hpw1plxawq996r1rkiwvcs-foliate-2.5.0/bin/.com.github.johnfactotum.Foliate-wrapped threw an exception
```

This might be, that the derivation right now does not install a `lib` directory. But I dont know how to fix it.

**Comment by nagy** [comment]
@anonimasusan you mention that the license is bsd. But it looks like it is gpl3: https://github.com/johnfactotum/foliate/blob/master/COPYING

**Comment by AndersonTorres** [comment]
Am I wrong or it is a Javascript program?

**Comment by anonimasusan** [comment]
Yes I think it is javascript.

**Comment by PanAeon** [comment]
@nagy I have found a similar issue  #31168 with Gnome characters app.
I was able to successfully build and launch the app with the following build, notice that there was missing `webkitgtk`:
```
{ stdenv, fetchFromGitHub, meson, gettext, glib, gjs, ninja, python3, gtk3, webkitgtk
, gsettings-desktop-schemas, wrapGAppsHook, desktop-file-utils
, gobject-introspection }:

stdenv.mkDerivation rec {
  pname = "foliate";
  version = "2.6.2";

  src = fetchFromGitHub {
    owner = "johnfactotum";
    repo = pname;
    rev = version;
    sha256 = "00y08564lim3107bm6b1qdayldj92q7pvhks1824y2j06crxkyw5";
  };

  nativeBuildInputs =
    [ meson ninja python3 wrapGAppsHook ];

  postPatch = ''
    patchShebangs build-aux/meson/postinstall.py
  '';

  postFixup = ''
    echo "fixing wrapper"
    sed -i "1 a imports.package._findEffectiveEntryPointName = () => 'com.github.johnfactotum.Foliate';" $out/bin/.com.github.johnfactotum.Foliate-wrapped 
  '';

  buildInputs = [
    gettext
    glib
    gjs
    gtk3
    webkitgtk
    desktop-file-utils
    gobject-introspection
    gsettings-desktop-schemas
  ];

  meta = with stdenv.lib; {
    description = "A simple and modern GTK eBook reader";
    homepage = "https://johnfactotum.github.io/foliate/";
    license = licenses.gpl3;
  };
}
```
If there's a person who has just a little bit more experience with gnome than me, the PR is very welcome, as the app is quite good actually.

**Comment by nagy** [comment]
thanks @PanAeon , I can also get it to start and I have updated my branch with your code as well.

**Comment by austinbutler** [comment]
This is now available.
