### ISSUE TITLE
wine: audio not working

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#10848]
I have ran into a problem with audio in `wine` (both the stable and unstable versions) having inexplicably stopped working, when just a few hours before (when I had the stable version installed) it was working fine, without having made a configuration change in-between (at least, that I can remember), and without any visible disk or nix store corruption.

It seems that for some reason, the 32-bit `wine` binary is now trying to pick up a 64-bit alsa plugin, and failing:
```
$ wine age2_x1.exe
(...)
ALSA lib pcm.c:2259:(snd_pcm_open_conf) Either /
nix/store/m97izygsdhf2ndx2jjfiy22p3zw8bpna-alsa-
plugins-1.0.29/lib/alsa-lib/libasound_module_pcm
_pulse.so cannot be opened or _snd_pcm_pulse_ope
n was not defined inside                       
ALSA lib pcm.c:2259:(snd_pcm_open_conf) Either /
nix/store/m97izygsdhf2ndx2jjfiy22p3zw8bpna-alsa-
plugins-1.0.29/lib/alsa-lib/libasound_module_pcm
_pulse.so cannot be opened or _snd_pcm_pulse_ope
n was not defined inside                       
ALSA lib pcm.c:2259:(snd_pcm_open_conf) Either /
nix/store/m97izygsdhf2ndx2jjfiy22p3zw8bpna-alsa-
plugins-1.0.29/lib/alsa-lib/libasound_module_pcm
_pulse.so cannot be opened or _snd_pcm_pulse_ope
n was not defined inside
(...)
```

`winecfg` also fails to play the test sound, with the same error messages.
Alsa by itself (`aplay`, specifically) works fine, and other PulseAudio applications also seem to be working fine.
My first guess is that the alsa library linked into wine is reading the global alsa configuration, which points to a 64-bit alsa plugin, which fails to load since wine is compiled as a 32-bit binary (which would probably mean we would need some kind of wrapper?), but not knowing much about alsa I can be completely wrong here.

cc @7c6f434c

**Comment by wizeman** [comment]
#6860 seems to be somewhat related.

**Comment by abbradar** [comment]
Do you have `hardware.pulseaudio.support32Bit` enabled? (I understand that you haven't changed the configuration at all, but it was the source of problem for me).

**Comment by wizeman** [comment]
@abbradar Yup, that fixed it for me. I don't know how it was working before, and how it suddenly stopped working even though I haven't changed my audio config in months. Anyway, thanks!

Closing the issue now.
