### ISSUE TITLE
Eclipse SDK doesn't contain JUnit anymore

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10844]
This is how I install Eclipse on my system:

```nix
eclipse =
  let plugins =
    callPackage <nixpkgs/pkgs/applications/editors/eclipse/plugins.nix> {};
  in
    (eclipses.eclipseWithPlugins {
             eclipse = eclipses.eclipse_sdk_45;
             plugins = [plugins.eclemma];
     });
```

Everything was fine until Eclipse started to not have JUnit anymore embedded:

1. when adding a library to a project, JUnit does not appear anymore
2. the JUnit view does not exist anymore

**Comment by DamienCassou** [comment]
I tried adding `jdt` but without success:

```nix
eclipse =
  let plugins =
    callPackage <nixpkgs/pkgs/applications/editors/eclipse/plugins.nix> {};
  in
    (eclipses.eclipseWithPlugins {
             eclipse = eclipses.eclipse_sdk_45;
             plugins = [plugins.eclemma plugins.jdt];
     });
```

**Comment by bjornfor** [comment]
No ideas here, sorry. (I don't use eclipse that often, and when I do it's for C and/or embedded programming.)

**Comment by DamienCassou** [comment]
When I go to `Help`, `About`, `Installation Details`, `Plugins`, I see 4 lines related to Junit:

- JDT JUnit Runtime Support
- JDT Junit 4 Runtime Support
- JUnit Testing Framework
- PDE JUnit Runtime Support

**Comment by DamienCassou** [comment]
No error in Eclipse log (`Help`, `About`, `Installation Details`, `Configuration`)

**Comment by DamienCassou** [comment]
@rycee recommended to remove `~/.eclipse` and it worked. Thank you
