### ISSUE TITLE
nixpkgs 20.09 release is gone 

### ISSUE THREAD

**Issue by tim2CF** [NixOS/nixpkgs#108568]
```shell
evaluating file '/app/nix/nixpkgs20.nix'
downloading 'https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz'...
error: while evaluating the attribute 'buildInputs' of the derivation 'coins-agent-shell' at /app/nix/shell.nix:21:3:
while evaluating 'getOutput' at /nix/store/ljscppi60hbm0g2b3y85g9dsq6jkfsya-source/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /nix/store/ljscppi60hbm0g2b3y85g9dsq6jkfsya-source/pkgs/stdenv/generic/make-derivation.nix:142:17, called from undefined position:
while evaluating the file '/app/nix/nixpkgs20.nix':
unable to download 'https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz': HTTP error 404
```

**Comment by andersk** [comment]
The URL is https://github.com/NixOS/nixpkgs/archive/nixos-20.09.tar.gz. (See also [pinning nixpkgs](https://nix.dev/reference/pinning-nixpkgs.html).)

**Comment by tim2CF** [comment]
Hmm, I'm sure that `https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz` worked yesterday, but thanks for the help!

**Comment by tim2CF** [comment]
Or maybe I used wrong url with old hash, and it worked because of nix laziness

**Comment by andersk** [comment]
Hmm, you seem to be right that the tag used to exist. I’ll reopen this for someone else to look at.

**Comment by alyssais** [comment]
@NixOS/nixos-release-managers

**Comment by primeos** [comment]
That's indeed very surprising. All of the release tags are suddenly gone but I don't see anything in the IRC logs or my GitHub news feed for the NixOS organization.

<details>
<summary>Release tags in my local repository</summary>
<pre>
15.09
15.09-beta
16.03
16.03-beta
16.09
16.09-beta
17.03
17.03-beta
17.09
17.09-beta
18.03
18.03-beta
18.09
18.09-beta
19.03
19.03-beta
19.09
19.09-beta
20.03
20.03-beta
20.09
20.09-alpha
20.09-beta
</pre>
</details>

Maybe someone accidentally deleted them? It's also quite sad that GitHub still doesn't allow to protect tags (AFAIK only branches can be protected).

**Comment by alyssais** [comment]
It’s unlikely that we’ll ever know what happened here unless the person who did it realises and tells us — we’ve consulted logs, but GitHub doesn’t notify when >3 tags are delete at once. I’ve restored all the tags, and compared my hashes with @andir’s for all the release tags to make sure they’re the right ones.

I don’t think there’s anything to do here, so I’ll close this now.

**Comment by jonringer** [comment]
I'm not sure what happened, interesting that the tags disappeared though.

In general though, you'll want to avoid using the tags, as they are fixed in time. The release branch will receive some updates for security.

**Comment by primeos** [comment]
Link to the IRC logs for some additional information (discussion starts around 13h): https://logs.nix.samueldr.com/nixos-dev/2021-01-06

There are two things about GitHub that really bother me regarding this incident:
- The tag deletions didn't appear in any logs (audit log, webhook events, org news feed)
- GitHub doesn't make it possible to protect tags (which could've/should've prevented this from happening)

**Comment by grahamc** [comment]
@AndersonTorres it looks like you've accidentally deleted some tags, perhaps a lot of tags by mistake -- do you know how you might be doing that?

```
15:22 -- Notice({^_^}): [nixpkgs] @AndersonTorres pushed 0 commits to refs/tags/black@2016-06-02: https://git.io/fAl5r
15:22 -- Notice({^_^}): [nixpkgs] @AndersonTorres pushed 0 commits to refs/tags/black@2016-08-31: https://git.io/fAl5o
15:22 -- Notice({^_^}): [nixpkgs] @AndersonTorres pushed 0 commits to refs/tags/black@2016-09-01: https://git.io/fAl5K
```

**Comment by AndersonTorres** [comment]
Oh hell! It was a wrong command I used in magit.

**Comment by grahamc** [comment]
Ah! Great, it is good to know how this happened :). I think we sorted it all and got them all recovered, thanks!

**Comment by NinjaTrappeur** [comment]
I feel like this is a concerning side effect of embedding the release tags to directly to NixPkgs instead of managing them in a specific repository (ie. deprecating nixpkgs-channels). All in sudden, any NixPkgs commiter is de-facto granted with the release manager ACLs.

It seems like there's sadly no way to grant write/edit/delete access for a tag to a specific set of people on the github interface.

We're all human and make mistake on a hourly basis. Knowing there are ~150 NixPkgs committers, I'm concerned about this being bound to happen again.
