### ISSUE TITLE
Improve assertion messages in pipewire

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#108528]
**Describe the bug**
Here are the current assertion messages
`PipeWire based PulseAudio server emulation replaces PulseAudio`
`PipeWire based JACK emulation doesn't use the JACK service`

are all simple statement. They don't tell you why the assertion has been triggered and what to do.

I'd prefer
```
services.pipewire: PipeWire based PulseAudio server emulation replaces PulseAudio. Disable `hardware.pulseaudio.enable`
```

```
services.pipewire: PipeWire based JACK emulation doesn't use the JACK service. Disable `services.jack.jackd.enable`
```

**Comment by MetaDark** [comment]
@worldofpeace I wasn't sure if someone else was already taking care of this, but it's a simple fix, so I submitted a PR for it.
