### ISSUE TITLE
Raspberry Pi Imager

### ISSUE THREAD

**Issue by danwdart** [NixOS/nixpkgs#108538]
**Project description**
Flash various images to SD cards

**Metadata**

* homepage URL: https://www.raspberrypi.org/software/
* source URL: https://downloads.raspberrypi.org/imager/imager_1.5_amd64.deb
* license: Unknown
* platforms: unix, linux, darwin, windows

**Comment by ymarkus** [comment]
Package merged now, but marked as broken on darwin for now. I'll get around fixing it soon when I'm able to test it on a MacBook.

**Comment by danwdart** [comment]
Awesome, thanks!

**Comment by ymarkus** [comment]
Just so you know, it might take some time for changes to appear in the channels, see this quote from the [NixOS Wiki](https://nixos.wiki/wiki/Nixpkgs/Update_a_package#Waiting_for_your_changes_to_appear_on_the_nix_channel)

> If your pull request is accepted, your changes will be part of NixOS/nixpkgs.
Once the changes enter the official repository they are more likely to be seen and probably used by other users.
In addition to that, if they enter the master branch, Hydra will eventually build the improved versions or new packages, and then the resulting binaries will be available on the NixOS channel.

**Comment by danwdart** [comment]
Okay - thanks for clearing that up!
