### ISSUE TITLE
nix-push fails on Darwin when build-use-chroot = true

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#10853]
(I filed this bug on `nix` as well but I'm not getting any traction there. See https://github.com/NixOS/nix/issues/673. Anyway, it's not clear to me where this should be filed so I'll try here as well.)

I use Nix on several OS X machines, all with an identical environment, so I've recently been building packages on one of them and then pushing the binary packages to my own binary cache, so that the other machines can simply download and install them directly. The relevant part of the script looks like this:

`nix-push --dest ~/Documents/nix-binary-cache/ --link --url-prefix http://nix-binary-cache.drewhess.com/ $(nix-instantiate '<nixpkgs>' -A meta-env)`

(`meta-env` is the collection of all the packages I use in my environment, so that I can rebuild them with a single `nix-env` command.)

I've switched to the new Darwin pure stdenv and sandboxed builds. That all works great and I was able to rebuild my whole environment from scratch successfully. However, now the binary cache script fails on the `nix-push` step like so:

``` shell
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
building compressed archives...
...
  /nix/store/znd6apsyigf80vzyxg5651ip345fzxay-bash43-033
  /nix/store/zsifjqz8x8r2w5wb7379d00hbqv5pzhh-nss-3.20.1.tar.gz
  /nix/store/zzxwmlxqygvi1micr7715xfnw33l4y8q-Libc-997.90.3
building path(s) ‘/nix/store/c5q2ry5qmgb0wh000lz9vfrinf5ks6s4-nar’
dyld: Library not loaded: /usr/lib/system/libcache.dylib
  Referenced from: /nix/store/v81lhzyangi203cgbx1w82dxscmlgyqf-Libsystem-1197.1.1/lib/libSystem.dylib
  Reason: no suitable image found.  Did find:
    /usr/lib/system/libcache.dylib: stat() failed with errno=1
builder for ‘/nix/store/01rphiz5ppz5g38sivx24949013xd6dk-nar.drv’ failed due to signal 5 (Trace/BPT trap: 5)
error: build of ‘/nix/store/01rphiz5ppz5g38sivx24949013xd6dk-nar.drv’ failed
nix-build failed: 25600 at /Users/dhess/.nix-profile/bin/nix-push line 168.
```

If I remove `build-use-chroot = true` from my `nix.conf`, it appears to work but starts a full rebuild of `meta-env`, which is obviously not what I want.

**Comment by sjourdois** [comment]
are you using latest nix ( https://nixos.org/wiki/Nix_on_OS_X#Install_a_recent_version_of_Nix )?

**Comment by dhess** [comment]
Yes, compiled from Git.

**Comment by retrry** [comment]
@copumpkin maybe there should be an umbrella issue for Darwin sandbox support? I didn't find one and it would be nice to have all information concerning sandbox support in one place.

**Comment by copumpkin** [comment]
@retrry that sounds good. Want to make one for nixpkgs? We can then link it to a nix issue, and I'll work on it eventually if nobody gets to it first.

**Comment by retrry** [comment]
@copumpkin I think you should make it as you have knowledge about current state and I'm only trying to research it.

**Comment by dhess** [comment]
I haven't used Darwin sandboxes for months, so I'm not even sure this is still an issue. What is an issue, however, is that non-sandboxed Darwin stdenv won't build from master (and hasn't since around April 1?). Is this a known problem? Is anybody maintaining the Darwin port?

**Comment by copumpkin** [comment]
@dhess is there an issue filed for that? I fixed a bug in the stdenv a few days ago and it seemed to work fine after I fixed it. I haven't had much time for nixing recently so I'm not actively monitoring whether something passes or fails, but if someone highlights me in a bug that breaks the entire platform, I'll generally make some time to look into it.

**Comment by dhess** [comment]
No issue filed last I looked, no. I haven't tried in a few days, let me pull master and try again.

**Comment by dhess** [comment]
Yep, Darwin stdenv builds again. Thanks!

However, I'm still building non-sandboxed so I can't say whether this particular issue (i.e., this nix-push issue) is resolved. According to the wiki, Darwin sandboxed builds are known to be broken; is that still the case?

**Comment by matthewbauer** [comment]
'nix-push' is no longer supported on Nix.
