### ISSUE TITLE
texinfo: texinfoInteractive t/malformed-split.sh hangs

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#108675]
**Describe the bug**

When (re)building texinfoInteractive, all tests up until `t/split.sh` pass, but `t/malformed-split.sh` hangs.

**To Reproduce**

`nix-build '<nixpkgs>' -A texinfoInteractive --check` (in my case on nixos-unstable, 1a57d96edd156958b12782e8c8b6a374142a7248 and d9dba88d08a9cdf483c3d45f0d7220cf97a4ce64)

**Additional context**

Interesting comment at https://www.mail-archive.com/cygwin-patches@cygwin.com/msg08053.html

**Comment by andir** [comment]
What revision was this on? I've just tried to reproduce this but the package did build just fine on 1a57d96edd156958b12782e8c8b6a374142a7248.

**Comment by andir** [comment]
Also works for me on the current master branch: c1891ad2e0f6e280b862cfcd16f528639fba21d7

**Comment by raboof** [comment]
rebooting and switching terminal/shell didn't help.

it works for me on 950c5e1879e57d9aedf64db53b4ec6f59f2ac17f (after a 'nixos-rebuild switch') though, so I can bisect where it started going wrong for me...

**Comment by raboof** [comment]
adding `--option sandbox yes` doesn't change the behaviour.

bisecting shows the problem started since the upgrade of busybox from 1.31.1 to 1.32.0 in 565c6a2a572c4e06ddb986a80dcd85b02d360bbf . Indeed https://busybox.net/?var=a mentions 1.32.1 fixes a deadlock issue, and indeed upgrading busybox fixes the problem for me \o/. Will PR.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/108708 did not fix this.

**Comment by raboof** [comment]
> #108708 did not fix this.

Hmm, I just double-checked and it does fix it for me: hangs on `66dc4881b2f6b8415d2afaaa178f481b660c7a52^` and succeeds on `66dc4881b2f6b8415d2afaaa178f481b660c7a52`.

I have to actually `nixos-rebuild switch` for the fix to take effect, though: updating the nixpkgs used by `nix-build` isn't sufficient.

**Comment by TredwellGit** [comment]
I can't `nixos-rebuild switch` because it hangs. That is also really unusual behavior.

**Comment by raboof** [comment]
> That is also really unusual behavior.

It is, isn't it!

**Comment by Artturin** [comment]
It's 2 years later and busybox is at 1.36 so perhaps it's fixed now
