### ISSUE TITLE
gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#108672]
**Describe the bug**
I updated my system (unstable) channel and now `gdm` refuses to start:

**To Reproduce**
The important parts of my configuration (I hope this is enough to reproduce):

```nix
{ config, pkgs, ... }: {
  imports = [ ./hardware-configuration.nix ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  environment.systemPackages = with pkgs; [ libinput iio-sensor-proxy ];
  hardware.sensor.iio.enable = true;
  services.xserver.enable = true;
  services.xserver.libinput.enable = true;
  services.xserver.displayManager.gdm = {
    enable = true;
    wayland = true;
  };
  services.xserver.displayManager.autoLogin = {
    enable = true;
    user = "piegames";
  };
  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.desktopManager.gnome3.sessionPath =
    [ pkgs.gnome3.gedit pkgs.gnome3.mutter ];
  system.stateVersion = "20.03"; # Did you read the comment?
}
```

I was previously on nixpkgs commit `61525137fd1002f6f2a5eb0ea27d480713362cd5` (something from september 2020), and updated to latest unstable as of 2021-01-06 (cannot easily copy commit atm, maybe `b349d080d79d9d4e7ae3a88d199aa4161ace57f8`).

**Expected behavior**
Gdm starts just fine, just as it did before.

**Notify maintainers**
Gnome team: @hedning @jtojnar @worldofpeace @dasj19 

**Metadata**
- system: `"x86_64-linux"`
- host os: `Linux 5.4.86, NixOS, 21.03pre261529.d9dba88d08a, nixpkgs-unstable-21.03pre261714.44c443a7a60`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.10`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- gnome3.gdm
- gnome3.gnome-shell
- gnome3.mutter
# a list of nixos modules affected by the problem
module:
```

**Comment by benneti** [comment]
Could it be related that my gnome-wayland session does not show up?

**Comment by piegamesde** [comment]
I forgot to add this, `systemctl status gdm.service` outputs `gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation`. @benneti If your Gnome-session does not show up, run that command to see if you get the same error message.

Also, it seems like the bug is not 100% deterministic: when rebooting often enough, it will work sometimes. So I suppose that there is some race hazard between two services owning that dbus name. Maybe I'll try looking at the session to find out which service took the name.

**Comment by benneti** [comment]
no I do not, so probably my issue is not related.
Still we could also compare (I have gdm.debug = true)
`journalctl -u display-manager -b`
[gdm.log](https://github.com/NixOS/nixpkgs/files/5792932/gdm.log)
Where I think for me there are a few interesting lines,
the ones related to wayland (I do not get why I am not seeing a wayland session) but I don't see any particularly interesting ones
and
`Failed to identify the current session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files` and similar

**Comment by 06kellyjac** [comment]
@piegamesde I have the same error. I booted into an older generation gdm worked fine (could be a lucky reboot or the older generation is fine :shrug:) but when I'm in i3 running `systemctl status gdm.service` I still see that error.


Slightly trimmed config:


```nix
{ config, pkgs, ... }:

let
  linuxPackages = pkgs.linuxPackages_latest;
  hasklig = pkgs.callPackage ./hasklig.nix { };
  hm = import <home-manager> {};
in {
  imports = [
    ./hardware-configuration.nix
    ./nixos-hardware/lenovo/thinkpad/x1-extreme/gen1
  ];

  nix = {
    package = pkgs.nixFlakes;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };

  boot.tmpOnTmpfs = true;
  # Use the systemd-boot EFI boot loader.
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    kernelPackages = linuxPackages;
    kernelModules = [ "kvm-intel" ];
    # extraModulePackages = [ config.boot.kernelPackages.exfat-nofuse ]; exfat should be in kernel >= 5.4
    extraModulePackages = [ linuxPackages.v4l2loopback ];
  };

  system.activationScripts.symlinkBinBash = ''
    ln -sf /run/current-system/sw/bin/bash /bin/bash
  '';

  time.timeZone = "Europe/London";

  programs = {
    nm-applet.enable = true;
    bash.enableCompletion = true;
  };

  # Required for zsh completion
  environment.pathsToLink = [ "/share/zsh" ];


  # Sound
  boot.extraModprobeConfig = ''
    options snd slots=snd-hda-intel
  '';

  nixpkgs.config.allowUnfree = true;

  services = {
    fstrim.enable = true;
    gvfs.enable = true;
    xserver = {
      enable = true;
      layout = "gb";
      libinput.enable = true;
      # displayManager.startx.enable = true;
      autorun = true; # swap hm
      displayManager.defaultSession = "none+i3"; # swap hm
      # desktopManager.default = "none";
      displayManager.gdm.enable = true;
      # dpi = 282;
      windowManager = {
        i3 = {
          enable = true;
          package = pkgs.i3-gaps;
        };
        # default = "i3";
      };
    };
  };

  # Hardware encoding
  nixpkgs.config.packageOverrides = pkgs: {
    vaapiIntel = pkgs.vaapiIntel.override { enableHybridCodec = true; };
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      inherit pkgs;
    };
  };

  hardware = {
    bluetooth.enable = true;
    cpu.intel.updateMicrocode = true;
    # bumblebee.enable = true;
    opengl = {
      enable = true;
      driSupport32Bit = true; # steam fix
      extraPackages = with pkgs; [
        vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
        intel-media-driver # only available starting nixos-19.03 or the current nixos-unstable
      ];
    };
  };

  # Optimus
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware = {
    nvidia = {
      modesetting.enable = true;
      prime = {
        sync.enable = true;
        nvidiaBusId = "PCI:1:0:0";
        intelBusId = "PCI:0:2:0";
      };
    };
  };

  # Auto suspend settings
  powerManagement.enable = true;
  services.logind = {
    lidSwitch = "suspend";
    lidSwitchDocked = "ignore";
    lidSwitchExternalPower = "ignore";
  };
  services.tlp.enable = true;

  users = {
    users.yo = {
      isNormalUser = true;
      extraGroups = [ "wheel" "docker" "networkmanager" "video" "audio" ];
    };
  };

  system.stateVersion = "20.09";
}
```

**Comment by piegamesde** [comment]
Okay, I just found that a gdm process is *already* running (supposedly outside of systemd?!). Killing it will boot up my GUI. However, the systemd unit stays broken no matter what I do. It will always say the unit's not started and that it can't start it due to the bus name collision. Even after killing everything including dbus itself, the error is the same. Very weird.

**Comment by ishan9299** [comment]
@piegamesde  I have the same issue plus I have couple of problems. Even if I use open-source nvidia driver gdm doesn't show me wayland. Also nvidia-prime doesn't work for me.

**Comment by piegamesde** [comment]
I think the only way to make progress on this issue if someone goes ahead and bisects it. And I probably won't do it because I reverted back to Arch Linux for now and don't have any non-headless NixOS machines anymore.

**Comment by benneti** [comment]
I can try to help and also think it might be related to some issues with pam on nixos-unstable or related to flakes.
I think this because when I tried to increase the file descriptors limit with 
``` nix
security.pam.loginLimits = [
      {
        domain = "*";
        type = "soft";
        item = "nofile";
        value = "4096"; # four times the default; hopefully sufficient
      }
    ];
```
`ulimit -nS` still reports 1024.

But I am not sure what else could be done to bisect it (relatively new to nix).

**Comment by piegamesde** [comment]
The best way for bisecting it would be to write a test that triggers the issue. `./nixos/tests/gnome3.nix` should be a good starting point. Then, `nix-build` on the test file to bisect it. However, I haven't managed to find a configuration that reproduces it in the VM. Maybe it isn't event reproducible at all this way.

**Comment by ryantm** [comment]
I'm hitting this same issue. It looks like gdm-wayland-session fails to start, and then it starts a gnome x session which fails because of some duplication.

https://gist.github.com/ryantm/6b07cab6e36731c5279845b09a4fe6e6 has the part of journalctl where wayland fails.

**Comment by ryantm** [comment]
I can log in with a low-resolution graphical display if I change the displayManager from `gdm` to `lightdm`.

**Comment by ryantm** [comment]
I was able to solve my issue with 

```
services.xserver.videoDrivers = [ "ati" ];
```

For reference, I have a R7 360 graphics card.

**Comment by ishan9299** [comment]
@ryantm I had the same problem I removed 
these options:-
```nix
  security = {
    hideProcessInformation = true;
    protectKernelImage = true;
  };
```

**Comment by fakedrake** [comment]
This affects me too, `sudo pkill gdm` on every boot runs gdm ok.

**Comment by skogsbrus** [comment]
Getting hit by this now and again on 21.05. So far it's always worked on boot, but the gui crashes every few hours.

Thanks @piegamesde for the temp fix of killing the other instance of gdm.

Looking in journalctl:

```
journalctl -u gdm.service
-- Journal begins at Mon 2021-07-19 10:45:21 CEST, ends at Tue 2021-07-20 00:12:02 CEST. --
Jul 19 16:23:24 voidm systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager,>
Jul 19 16:23:33 voidm systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager,>
-- Boot f4d9631633ad411c83de312db077405a --
Jul 19 23:58:16 voidm systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager,>
Jul 20 00:03:23 voidm systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager,>
lines 1-6/6 (END)

```

```
journalctl -u display-manager -b
-- Journal begins at Mon 2021-07-19 10:45:21 CEST, ends at Tue 2021-07-20 00:06:02 CEST. --
Jul 19 18:52:08 voidm systemd[1]: Starting X11 Server...
Jul 19 18:52:08 voidm systemd[1]: Started X11 Server.
Jul 19 18:52:14 voidm gdm-password][1769]: gkr-pam: unable to locate daemon control file
Jul 19 18:52:14 voidm gdm-password][1769]: gkr-pam: stashed password to try later in open session
Jul 19 18:52:14 voidm gdm-password][1769]: pam_unix(gdm-password:session): session opened for user johanan(uid=1000) >
Jul 19 18:52:14 voidm gdm-password][1769]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
Jul 19 18:52:18 voidm gdm[1432]: Gdm: Child process -1474 was already dead.
Jul 19 23:55:00 voidm gdm[1432]: GLib: g_hash_table_foreach: assertion 'version == hash_table->version' failed
Jul 19 23:55:00 voidm systemd[1]: display-manager.service: Succeeded.
Jul 19 23:55:00 voidm systemd[1]: display-manager.service: Scheduled restart job, restart counter is at 1.
Jul 19 23:55:00 voidm systemd[1]: Stopped X11 Server.
Jul 19 23:55:00 voidm systemd[1]: Starting X11 Server...
Jul 19 23:55:00 voidm systemd[1]: Started X11 Server.
Jul 19 23:55:06 voidm gdm-password][39898]: gkr-pam: unable to locate daemon control file
Jul 19 23:55:06 voidm gdm-password][39898]: gkr-pam: stashed password to try later in open session
Jul 19 23:55:06 voidm gdm-password][39898]: pam_unix(gdm-password:session): session opened for user johanan(uid=1000)>
Jul 19 23:55:06 voidm gdm-password][39898]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
Jul 19 23:55:09 voidm gdm[39642]: Gdm: Child process -39660 was already dead.
lines 1-19/19 (END)


```



Some other configs:

```
$ echo $XDG_SESSION_TYPE
wayland
```

```
systemctl status gdm.service
● gdm.service - GNOME Display Manager
     Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
     Active: inactive (dead)

Jul 19 23:58:16 voidm systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager,>
Jul 20 00:03:23 voidm systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager,>
lines 1-6/6 (END)
```

```
{ config, pkgs, ... }:

{
  services.xserver = {
    # Enable the X11 windowing system.
    enable = true;

    # Enable touchpad support (enabled default in most desktopManager).
    libinput.enable = true;

    # Enable the GNOME 3 Desktop Environment.
    displayManager.gdm.enable = true;
    desktopManager.gnome.enable = true;

    # Add custom keyboard layout
    extraLayouts.us-swedish = {
      description = "US layout with alt-gr Swedish";
      languages = [ "eng" ];
      symbolsFile = ./keyboard/symbols/us-swedish;
    };

    # Configure keymap in X11
    layout = "us-swedish";
    xkbOptions = "caps:escape";

  };
}

```

**Comment by doronbehar** [comment]
I almost never experience the issue where gdm doesn't start at all, but even when it's running and everything is OK, I see in `systemd status gdm.service` the error:

```
gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation
``` 

Indeed both systemd files `gdm.service` and `display-manager.service` have the `BusName` deriviative:

```
/run/current-system/etc/systemd/system/gdm.service:BusName=org.gnome.DisplayManager
/run/current-system/etc/systemd/system/display-manager.service:BusName=org.gnome.DisplayManager
```

And we do add both of them with:

https://github.com/NixOS/nixpkgs/blob/5035f0924ce98788c63863f16ae0f1af3bceca5e/nixos/modules/services/x11/display-managers/gdm.nix#L164

And:

https://github.com/NixOS/nixpkgs/blob/5035f0924ce98788c63863f16ae0f1af3bceca5e/nixos/modules/services/x11/display-managers/gdm.nix#L201-L205

Where `gdm.service` brings the `BusName` derivative from the source package.

I think it should be fairly easy to remove the `BusName` derivative from one of the services, even from `gdm.service` - although it's from a package. I don't know how to decide which to remove, `systemd.services.display-manager` from `xserver.nix` seems redundant compared to upstream's `gdm.service`.

This issue is somewhat related to https://github.com/NixOS/nixpkgs/issues/53394 and https://github.com/NixOS/nixpkgs/issues/94799 .
