### ISSUE TITLE
flutter: 1.22.0 -> 1.22.4, drop non-stable versions

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#108606]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 1.22.0
desired version: 1.22.4

###### Notify maintainers

maintainers: @babariviere @ericdallo 

###### Note for maintainers

I am trying to make this bump happen, but one of the difficult that I am having is that we need to bump 3 different channels: `stable`, `beta`, `unstable`. However, I don't think having 3 different Flutter channels makes too much sense:

- I don't think we have multiple different packages supporting beta or development versions of other compilers/frameworks (we support multiple versions of GCC for example, but it is multiple stable versions instead of unstable/development versions)
- We already have a `mkFlutter` function exposed in `all-packages` that allows users that need to run a different version of Flutter that is packaged currently

Having 3 different versions make this bump really difficult, specially since we also need to patch Flutter.

So I have a proposal of dropping the beta and dev versions and only keep stable branch, WDYT @ericdallo @babariviere ?

**Comment by ericdallo** [comment]
Not sure, if there any user that wants to have the latest nix dev branch always updated automatically, it wouldn't be possible doing that

**Comment by thiagokokada** [comment]
> Not sure, if there any user that wants to have the latest nix dev branch always updated automatically, it wouldn't be possible doing that

But the way it currently is, instead of running the latest dev version we are running a very old dev version that nobody bothers to bump since it is very difficult to do so.

**Comment by ericdallo** [comment]
Since bump it in nixpkgs is not that easy/fast I think it's OK keeping only the stable one and keep exposing mkFlutter

**Comment by thiagokokada** [comment]
Pinging @GRBurst since he is the maintainer of `dart` (we could do something similar there).

**Comment by GRBurst** [comment]
I agree, it is better to have one up to date stable branch than having two outdated (stable + dev) branches :+1:
Thanks for pinging, will consider this for the dart package :-)

**Comment by thiagokokada** [comment]
Created a PR #109477.
