### ISSUE TITLE
Packaging Request: yabridge/yabridgectl

### ISSUE THREAD

**Issue by thornycrackers** [NixOS/nixpkgs#108791]
**Project description**
Yet Another way to use Windows VST plugins on Linux. Yabridge seamlessly supports using both 32-bit and 64-bit Windows VST2 and VST3 plugins in a 64-bit Linux VST host as if they were native VST2 and VST3 plugins, with optional support for plugin groups to enable inter-plugin communication for VST2 plugins and quick startup times. Its modern concurrent architecture and focus on transparency allows yabridge to be both fast and highly compatible, while also staying easy to debug and maintain.

If I understand correctly, this provides similar functionality to the airwave package. I think the big plus to this package though is that it emulates as if they were native which means the build process doesn't need to require the user to go to the steinberg site and download the VST SDK (as airwave currently does). I used this on Arch with Reaper and it was extremely easy to get going. I had a much easier time using yabridge than trying to get carla set up and running. There are multiple AUR packages for installing from source or just pulling in the binaries. I've tried to package this myself but it's just a bit beyond my means. I think that if someone is more familiar with packaging wine related binaries or compiling with meson from source this would be a quick win.

* homepage URL: https://github.com/robbert-vdh/yabridge
* source URL: https://github.com/robbert-vdh/yabridge
* license: GPL 3.0
* platforms: linux

**Comment by MetaDark** [comment]
I probably won't have time today, but I can take a look at this later. I'm pretty familiar with the nixpkgs wine build, and I've worked with the ZynAddSubFx build to add support for the Zyn-Fusion ui.

**Comment by thornycrackers** [comment]
@MetaDark Amazing. I was able to take your PR and get Upright Piano working with Reaper as well. Thank you so much for the quick turn around, I really appreciate it.

**Comment by robbert-vdh** [comment]
Hi! I don't use NixOS myself, but if it helps, there's one person in the yabridge Discord currently using yabridge's master branch with NixOS. And I've also ran into another Nix build definition on GitHub in the past (but that one's pretty outdated by now).

**Comment by robbert-vdh** [comment]
I've just released [yabridge 3.0.0](https://github.com/robbert-vdh/yabridge/releases/tag/3.0.0) with a _lot_ of important new features, fixes and improvements including the first ever Linux <-> Windows VST3 plugin bridge. I saw that the package created by @MetaDark for yabridge 2.2.1 has not been merged yet, but please let me know if you want to update the yabridge and yabridgectl packages for yabridge 3.0.0 and need any help! One additional dependency is now a patched version of the VST3 SDK which is patched to compile under winegcc and with support for Meson. I'm not quite sure how Nix packaging handles those things.

**Comment by MetaDark** [comment]
@robbert-vdh Thanks, I have it building right now. I'm just testing out vst3 plugins right now :smile:

**Comment by MetaDark** [comment]
:cry: For some reason neither the vst2 or vst3 plugins are working, even though they get installed. I think it might be an issue with my system installed wine. I'll submit my changes anyway so other people can test it out.

**Comment by alpmestan** [comment]
@MetaDark So they are found but yabridge fails to load them? Which Wine are your derivations using?

**Comment by robbert-vdh** [comment]
> cry For some reason neither the vst2 or vst3 plugins are working, even though they get synced. I think it might be an issue with my system installed wine. I'll submit my changes anyway so other people can test it out.

You can try running `yabridge-host.exe` manually to see if that is the issue. A plain `yabridge-host.exe` call should print:

```
Usage: yabridge-host.exe <plugin_type> <plugin_location> <endpoint_base_directory>
```

And `yabridge-host.exe foo bar baz` should print:

```
Initializing yabridge host version 3.0.0
Preparing to load <unknown> plugin at 'bar'
Unknown plugin type 'foo'
```

**Comment by MetaDark** [comment]
@alpmestan I'm able to sync them with yabridgectl, but they fail to load in Reaper. I'm using `wineWowPackages.minimal` (currently version 6.1) to build yabridge, but I have a custom build of wine staging 6.0 currently installed.

@robbert-vdh `yabridge-host.exe` seems to be working fine:
```
> /nix/store/fyahkj0qsg1prd8ihj6lrb0xsshp3q47-yabridge-3.0.0/bin/yabridge-host.exe
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0050:err:ole:start_rpcss Failed to start RpcSs service
Usage: yabridge-host.exe <plugin_type> <plugin_location> <endpoint_base_directory>
```
```
> /nix/store/fyahkj0qsg1prd8ihj6lrb0xsshp3q47-yabridge-3.0.0/bin/yabridge-host.exe foo bar baz
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.0 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0060:err:ole:start_rpcss Failed to start RpcSs service
Initializing yabridge host version 3.0.0
Preparing to load <unknown> plugin at 'bar'
Unknown plugin type 'foo'
```

**Comment by robbert-vdh** [comment]
@MetaDark That indeed seems to work as expected, that's great news! If you start REAPER with `env YABRIDGE_DEBUG_LEVEL=1 YABRIDGE_DEBUG_FILE=/tmp/yabridge.log reaper` and then take a look at `/tmp/yabridge.log` after trying to scan/load a plugin then you'll probably figure out what's wrong very quickly.

**Comment by MetaDark** [comment]
@robbert-vdh Hmm, apparently the path to the VST host is too long :stuck_out_tongue: 
```
[Upright Piano-6EIMQWuy] Initializing yabridge version 3.0.0
[Upright Piano-6EIMQWuy] host:          '/home/kira/.nix-profile/bin/yabridge-host.exe'
[Upright Piano-6EIMQWuy] plugin:        '/home/kira/Downloads/Upright_Piano_Windows_VST3_64-bit/Upright Piano Windows VST3 64-bit/Upright Piano.vst3'
[Upright Piano-6EIMQWuy] plugin type:   'VST3'
[Upright Piano-6EIMQWuy] realtime:      'no'
[Upright Piano-6EIMQWuy] sockets:       '/run/user/1000/yabridge-Upright Piano-6EIMQWuy'
[Upright Piano-6EIMQWuy] wine prefix:   '<default>'
[Upright Piano-6EIMQWuy] wine version:  '6.0 (Staging)'
[Upright Piano-6EIMQWuy] 
[Upright Piano-6EIMQWuy] config from:   '<defaults>'
[Upright Piano-6EIMQWuy] hosting mode:  'individually, 64-bit'
[Upright Piano-6EIMQWuy] other options: '<none>'
[Upright Piano-6EIMQWuy] 
[Upright Piano-6EIMQWuy] Enabled features:
[Upright Piano-6EIMQWuy] - VST3 support
[Upright Piano-6EIMQWuy] 
[Upright Piano-6EIMQWuy] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk wine-staging 6.0 is a testing version containing experimental patches.
[Upright Piano-6EIMQWuy] [Wine STDERR] 002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
[Upright Piano-6EIMQWuy] [Wine STDERR] 0050:err:ole:start_rpcss Failed to start RpcSs service
[Upright Piano-6EIMQWuy] [Wine STDOUT] Initializing yabridge host version 2.2.1
[Upright Piano-6EIMQWuy] [Wine STDERR] Error while initializing Wine VST host:
[Upright Piano-6EIMQWuy] [Wine STDERR] File name too long
[Upright Piano-6EIMQWuy] The Wine host process has exited unexpectedly. Check the output above for more information.
```

**Comment by robbert-vdh** [comment]
Huh I can't think of from the top of my head what would be throwing such an exception. That message printed after `Error while initializing Wine VST host:` comes from a try-catch around the entire plugin startup that catches and prints any `std::exception`. Windows (and thus Wine, because it has to be compatible haha) has a path name limit of 255 characters, but none of those paths sound like they should come close to that.

**Comment by MetaDark** [comment]
@robbert-vdh Yeah, sorry. It was just a problem with my home environment. I was trying to test it without installing because I lost the nixpkgs commit I used to generate my home-manager environment. REAPER was just loading the old 2.2.1 yabridge-host.exe... :woman_facepalming: 

I just finished rebuilding my home environment with a news nixpkgs commit, and it's working now :smile: .
