### ISSUE TITLE
Qt 5.5 qtmultimedia has missing plugins (gstreamer)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#10879]
These are the mediaservice plugins in Qt 5.5:

```
$ nix-build -A qt55.qtmultimedia -Q && ls -1 result/lib/qt5/plugins/mediaservice/
/nix/store/ji28da47s9ib8ysg7ns7f88awglqz6vh-qtmultimedia-5.5.0
libqtmedia_audioengine.so
```

It lacks a few libraries compared to Qt 5.4:

```
$ nix-build -A qt54.multimedia -Q && ls -1 result/lib/qt5/plugins/mediaservice/
/nix/store/0anpmz654yfsaz5ygjv8x4xp3ghkd2rs-qtmultimedia-5.4.2
libgstaudiodecoder.so
libgstcamerabin.so
libgstmediacapture.so
libgstmediaplayer.so
```

I thought adding pkgconfig to qtmultimedia buildInputs would fix it, similarly to 449b6028a64fae427fdce4abf126825bd8aaf260 ("qt5.multimedia: fix gstreamer support"). But that didn't add more libraries to the mediaservice/ directory.

**Comment by bjornfor** [comment]
CC @ttuegel, @gebner.

**Comment by bjornfor** [comment]
Looking at the build log. Qt 5.4 says:

```
Checking for openal... no
Checking for gstreamer... yes
Checking for gstreamer_photography... no
Checking for gstreamer_encodingprofiles... yes
Checking for gstreamer_appsrc... yes
Checking for linux_v4l... yes
Checking for resourcepolicy... no
```

Whereas Qt 5.5 says:

```
Checking for openal... no
/tmp/nix-build-qtmultimedia-5.5.0.drv-0/qtmultimedia-opensource-src-5.5.0/qtmultimedia.pro:28: Variable GST_VERSION is not defined.
Checking for resourcepolicy... no
```

Adding pkgconfig to buildInputs doesn't change the qt55 build log (still complains about missing GST_VERSION).

**Comment by bjornfor** [comment]
Relevant snippet from qtmultimedia-opensource-src-5.5.0/qtmultimedia.pro:

```
    isEmpty(GST_VERSION) {
        contains(QT_CONFIG, gstreamer-0.10) {
            GST_VERSION = 0.10
        } else: contains(QT_CONFIG, gstreamer-1.0) {
            GST_VERSION = 1.0
        }
    }
    cache(GST_VERSION, set)
    !isEmpty(GST_VERSION):qtCompileTest(gstreamer) {
        qtCompileTest(gstreamer_photography)
        qtCompileTest(gstreamer_encodingprofiles)
        qtCompileTest(gstreamer_appsrc)
        qtCompileTest(linux_v4l)
    }
```

I'm not sure yet the proper way to set either GST_VERSION (directly) or via QT_CONFIG. It doesn't look like we have "qmakeFlags" in nixpkgs.

**Comment by ttuegel** [comment]
@bjornfor `qmake` will respect `configureFlags`.

**Comment by bjornfor** [comment]
Doh! Thanks! :-)

Passing "GST_VERSION=1.0" to qmake fixes it. Will send PR soon.

**Comment by bjornfor** [comment]
PR: https://github.com/NixOS/nixpkgs/pull/10916
