### ISSUE TITLE
Python3x vs Python3xFull # pkgs broken and overlay without effect

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#108773]
**Describe the bug**
I was wondering about the difference of python3x and python3xFull because I needed tkinter
- but python3xFull appears to be not only python3x (+tkinter, ++ 4 more pkgs)

---- 
Where can I find the exact way of how python3xFull is build? (Some documentation would be nice)

----

**To Reproduce**
#works
`pkgPy="pandas"; versionPy="38";  nix-shell -p "python${versionPy}.withPackages( pp: [pp.${pkgPy}])" --run "python -c 'import sys; print(sys.version); import ${pkgPy}; print(${pkgPy}.__version__)'" `
#fails
`pkgPy="pandas"; versionPy="38";  nix-shell -p "python${versionPy}Full.withPackages( pp: [pp.${pkgPy}])" --run "python -c 'import sys; print(sys.version); import ${pkgPy}; print(${pkgPy}.__version__)'" `

----
```
Current thread 0x00007ffff7841f40 (most recent call first):
  File "/nix/store/idf6csvf721yi5v513003dnqjas1fy2y-python3.8-scipy-1.5.2/lib/python3.8/site-packages/scipy/cluster/vq.py", line 522 in _krandinit
  File "/nix/store/idf6csvf721yi5v513003dnqjas1fy2y-python3/nix/store/f95jkch26wxmqd076bcm976qrn7ml46i-stdenv-linux/setup: line 1303: 10537 Segmentation fault      (core dumped) /nix/store/lwzwzg26jrfrmq4wsbx7nnmwm0kq3s5w-python3-3.8.5/bin/python3.8 -c 'import scipy; scipy.test("fast", verbose=10)'
builder for '/nix/store/bgv6bfxqppsybv4av96jwjrnp2z777n5-python3.8-scipy-1.5.2.drv' failed with exit code 139
cannot build derivation '/nix/store/yb2k5r33mqyx9n5j789ma0pk1f5x7j72-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/yb2k5r33mqyx9n5j789ma0pk1f5x7j72-python3-3.8.5-env.drv' failed
```

------
#fails with python3xFull but works with python3x
```
overlays = [ ( self: super: {
            python38Full = super.python38Full.override {
            #python38 = super.python38.override {
              packageOverrides = python-self: python-super: {
                pytorch = python-super.pytorch-bin.overrideAttrs (oldAttrs: {
                  pname = "pytorch_bin";
                });
              };
            };
          }) ]
pkgs= import <nixpkgs>  { inherit overlays; }
pkgs.python38Packages.pytorch.pname

```

------

any py-pkgs in `extraLibs` will not be recognized for python38 (fails for python38Full independent of the nixpkgs channel)
```
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz) {} }:
#{ pkgs ? import <nixpkgs> {} }:
let
  #python3 = pkgs.python38.buildEnv.override {
  python3 = pkgs.python38Full.buildEnv.override {
    extraLibs = [ 
        pkgs.python38Packages.pandas 
        #pkgs.python38Full.pkgs.pandas 
        ];
  };
in let
envPy =  pkgs.mkShell {
    name = "shellPy";
    buildInputs = [ python3 ];
    shellHook = ''
                echo ""
                ${python3}/bin/python -c "import pandas as pd; print(pd.__version__) "
                '';
} ;
in 
envPy
```

**Expected behavior**
- both shells should build a working shell env
- overlay should work for python3xFull as good as for python3x

**Notify maintainers**
@FRidh 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.15, NixOS, 20.09.2344.a3a3dda3bac (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2344.a3a3dda3bac"`
 - channels(ae): `"nixos-20.09.2152.e34208e1003"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- python38Full
```

**Comment by FRidh** [comment]
`tkinter` is available as `python3.pkgs.tkinter`, no need to work with `python3Full`.

**Comment by InLaw** [comment]
I know but in general I would like to use the original Python (and not the shortened one "python38"). 
E.g. if working with additional tooling like withJupyther or mach-nix it would be more useful to have a python3xFull/original sized interpreter

**Comment by FRidh** [comment]
Segmentation fault is likely resolved with https://github.com/NixOS/nixpkgs/pull/101780.

**Comment by InLaw** [comment]
Why is the issue not occurred in both python variants (IF the pkgs are the same)?

**Comment by FRidh** [comment]
> Segmentation fault is likely resolved with #101780.

blas issues are often chip specific.

**Comment by InLaw** [comment]
any py-pkgs in `extraLibs` will not be recognized for python38 (fails for python38Full independent of the nixpkgs channel) [please have a look at the updated issue]

**Comment by FRidh** [comment]
that's because your override is incorrect. You need to pass `self = python38Full;`. Check the Nixpkgs manual Python section. Closing this.

**Comment by InLaw** [comment]
Why is the issue closed? 

----

Could you show me your working example of the overlay (I cannot get the point/cannot get it running)?
- `self = python38Full;` would mean that `[pkgs.]python38Full `be not defined if `pkgs` will be defined after the `overlay` // but the overlay has to be defined before the pkgs import?

----

Could you tell me, why pandas is not working `python38Full` but for `python38` if it would be the **same** pkg?
- I would expect both to fail and not only one (openblas is a fact for both pkgs, no?)

----


 Why will any py-pkgs in extraLibs not be recognized for `python38Full` but for `python38` (fails for `python38Full` independent of the `nixpkgs` channel [with openblas-0.3.12, too]) 

- here NO self is explicitly used, is it?
```
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz) {} }:
#{ pkgs ? import <nixpkgs> {} }:
let
  #python3 = pkgs.python38.buildEnv.override {
  python3 = pkgs.python38Full.buildEnv.override {
    extraLibs = [ 
        pkgs.python38Packages.pandas 
        #pkgs.python38Full.pkgs.pandas 
        ];
  };
in let
envPy =  pkgs.mkShell {
    name = "shellPy";
    buildInputs = [ python3 ];
    shellHook = ''
                echo ""
                ${python3}/bin/python -c "import pandas as pd; print(pd.__version__) "
                '';
} ;
in 
envPy
```
results in:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas'
```

**Comment by InLaw** [comment]
> that's because your override is incorrect. You need to pass `self = python38Full;`. Check the Nixpkgs manual Python section. Closing this.

Your are not referencing to "`Nixpkgs manual Python section`" (would be nice to get a specific link) instead you are talking about 
`nixpkgs-channels/pkgs/top-level/all-packages.nix:10153:`
```
python38Full = python38.override {
self = python38Full;
```

Why this confusion?
