### ISSUE TITLE
gitlab-runner module: the `dockerImage` is also mandatory for the “docker+machine” executor

### ISSUE THREAD

**Issue by MartinPotier** [NixOS/nixpkgs#108759]
https://github.com/NixOS/nixpkgs/blob/5000e5707bcd9010669e2ad7da8042dbf68f85c7/nixos/modules/services/continuous-integration/gitlab-runner.nix#L69

This test should also add the `dockerImage` option if it is set, and the executor is “docker+machine”.

**Comment by MartinPotier** [comment]
fyi @misuzu (git blame says you're the last person to edit this section)

**Comment by misuzu** [comment]
@MartinPotier please [test](https://discourse.nixos.org/t/call-for-testing-gitlab-runner-module/6765) this pull-request: https://github.com/NixOS/nixpkgs/pull/108763

**Comment by MartinPotier** [comment]
> @MartinPotier please [test](https://discourse.nixos.org/t/call-for-testing-gitlab-runner-module/6765) this pull-request: #108763

Sorry, I'm testing mine right now :) Could you review it?
