### ISSUE TITLE
perl5.32.0-Glib-Object-Introspection-0.048 marked as broken

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#108857]
**Describe the bug**
On current Nixos Unstable perl5.32.0-Glib-Object-Introspection-0.048 is marked as broken, which causes me not to be able to rebuild.

```
unpacking channels...
created 1 symlinks in user environment
building Nix...
building the system configuration...
trace: warning: The option `services.tor.controlPort' defined in `/etc/nixos/configuration.nix' has been renamed to `services.tor.settings.ControlPort'.
error: Package ‘perl5.32.0-Glib-Object-Introspection-0.048’ in /nix/store/bx8vdln5jadhjm518i3n6mrqj2jblvnw-nixos-21.03pre262020.f211631c1cb/nixos/lib/attrsets.nix:344 is marked as broken, refusing to evaluate.

a) To temporarily allow broken packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_BROKEN=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.85, NixOS, 21.03pre259556.e7659b6288d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(hyper): `"nixos-20.09pre242769.61525137fd1"`
 - channels(root): `"nixos-21.03pre262020.f211631c1cb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
ping @stigtsp in case they are feeling generous and willing to take a look ❤️

**Comment by eduardosm** [comment]
This has been fixed in https://github.com/NixOS/nixpkgs/pull/113732.
