### ISSUE TITLE
pkgs.python38Packages # Python3x.pkgs vs Python3xFull.pkgs - e.g. pandas

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#108837]
**Describe the bug**
The expectation is that any package named in `pkgs.python38Packages` should fail or succeed it's build the same way - for `pkgs.python38.pkgs` as for `pkgs.python38Full.pkgs` 
- an example of a package could be `pandas`

For pandas the situation is that it only works for `pkgs.python38.pkgs` NOT for `pkgs.python38Full.pkgs` 

**Additional context**
- this issue is not focused on the pandas error itself but onto the context of `pkgs.python38.pkgs` with `pkgs.python38Full.pkgs` / `pkgs.python38.pkgs`

----

**To Reproduce**
fails for `python38Full.pkgs` but succeeds for `python38.pkgs`
```
# "rev": "502845c3e31ef3de0e424f3fcb09217df2ce6df6"
# { pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz) {} }:
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixos-20.09.tar.gz) {} }:
let
  #py = pkgs.python38
  py = pkgs.python38Full;
  python3 = py.buildEnv.override {
    extraLibs = [ 
        py.pkgs.pandas 
        #pkgs.python38Full.pkgs.pandas 
        ];
  };
in let
envPy =  pkgs.mkShell {
    name = "shellPy";
    buildInputs = [ python3 ];
    shellHook = ''
                echo ""
                ${python3}/bin/python -c "import pandas as pd; print(pd.__version__) "
                '';
} ;
in 
envPy
```
#fails
`pkgPy="pandas"; versionPy="38";  nix-shell -p "python${versionPy}Full.withPackages( pp: [pp.${pkgPy}])" --run "python -c 'import sys; print(sys.version); import ${pkgPy}; print(${pkgPy}.__version__)'" `

----
```
../cluster/tests/test_vq.py::TestKMean::test_krandinit <- ../../nix/store/y54ryyqlvn983g2hdwvqd6dlcijw9llg-python3.8-scipy-1.5.2/lib/python3.8/site-packages/scipy/cluster/tests/test_vq.py Fatal Python error: Segmentation fault/nix/store/f95jkch26wxmqd076bcm976qrn7ml46i-stdenv-linux/setup: line 1303: 10537 Segmentation fault      (core dumped) /nix/store/09izmcv354l9kgdrcsj1vd39hnywg25d-python3-3.8.5/bin/python3.8 -c 'import scipy; scipy.test("fast", verbose=10)'
builder for '/nix/store/972chr1q6xhh42dwq6xqs6wz7191qr4i-python3.8-scipy-1.5.2.drv' failed with exit code 139
cannot build derivation '/nix/store/w4gv52i9f2jgkgqsran1di8fbq6ksmbd-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/w4gv52i9f2jgkgqsran1di8fbq6ksmbd-python3-3.8.5-env.drv' failed
```

**Expected behavior**
- both shells/packages should fail or succeed to build but not only one of those 

**Notify maintainers**
@FRidh 
@raskin  
@knedlsepp

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.15, NixOS, 20.09.2344.a3a3dda3bac (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"nixos-20.09.2344.a3a3dda3bac"`
 - channels(ae): `"nixos-20.09.2152.e34208e1003"`
 - nixpkgs:

**Comment by InLaw** [comment]
any information on this?

**Comment by InLaw** [comment]
any information regarding this topic?

**Comment by FRidh** [comment]
Yes, the packages using the full interpreter should also pass when the others pass. It's strange that sometimes it does not. However, Full is hardly used and we have no CI set up for it (nor the capacity for it).

I don't see anything we can do here really. Most packages will build just fine. When one doesn't, it's...strange, but then those could be investigated on a case-by-case base.
