### ISSUE TITLE
Add syndaemon configuration options

### ISSUE THREAD

**Issue by sindikat** [NixOS/nixpkgs#10889]
The command [`syndaemon`](http://linux.die.net/man/1/syndaemon) temporarily disables keyboard when you're typing, which prevents messing up with the text by relocating cursor and accidentally clicking things. E.g.:

```
syndaemon -i 4 -d -t -K
```

I propose a configuration option under `services.xserver.synaptics`, or maybe a separate one to configure `syndaemon` for NixOS.

**Comment by nbp** [comment]
@sindikat would you be interested in making this change? if you want we can guide you into NixOS.

**Comment by sindikat** [comment]
@nbp, I'd love to be a NixOS contributor :). But I'm not sure I have time right now. As this is not a pressing improvement, I'll message you once I have some time and desire to do that. Is that alright?

**Comment by nbp** [comment]
@sindikat I think this would be fine, I will flag this bug as good-first-bug.

The idea of this bug would be to create a new module, as described in the manual [1] and to register a systemd job [2] which starts the `syndaemon` program which is already packaged as part of `xorg.xf86inputsynaptics`. 

This module can be tested manually by rebuilding the configuration of NixOS, and checking it it appears in the list of systemd services [3].

[1] http://nixos.org/nixos/manual/index.html#sec-writing-modules
[2] http://nixos.org/nixos/options.html (search for `systemd.services`)
[3] http://nixos.org/nixos/manual/index.html#sec-systemctl

**Comment by Profpatsch** [comment]
triage: has this been fixed?

**Comment by Profpatsch** [comment]
@RostakaGmfun I can’t find such a module either (at least nothing that references the `syndaemon` command). Feel free!

If you need help, you can ping me on freenode, where I have the same user name. Or ask in `#nixos`.

**Comment by RostakaGmfun** [comment]
@Profpatsch just wondering if this is still required as syndaemon is deprecated and replaced by libinput in 18.03. libinput seems to have its own "disable-while-typing" option.

**Comment by Profpatsch** [comment]
Hm, if `libinput` is the standard for NixOS and it supports that, then we shouldn’t add extra functionality to `synaptic`, yeah.
