### ISSUE TITLE
qtwebengine pipewire support

### ISSUE THREAD

**Issue by petabyteboy** [NixOS/nixpkgs#108877]
qtwebengine should be built with `RTC_USE_PIPEWIRE=1` just like chromium to support screen capture via pipewire.

**Comment by peterhoeg** [comment]
Isn't this fixed by #123724 and #124078?

**Comment by Artturin** [comment]
yes https://github.com/archlinux/svntogit-packages/blob/d252234e1b24fba714c32845911cafb490cf5ce9/trunk/PKGBUILD#L46

RTC_USE_PIPEWIRE=1 is a chromium/electron thing afaik
