### ISSUE TITLE
Incorrect Home Directory Permissions

### ISSUE THREAD

**Issue by alunduil** [NixOS/nixpkgs#10888]
When I declare a user such as:

```
    users.users = {
      username = {
        home = "/home/foo/username";
        isNormalUser = true;
        };
    };
```

The directory, `/home/foo`, gets created with permissions 0700 and owned by root.  This unfortunately means that user, username, is unable to access their home directory.  

I've tracked the problem here:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/update-users-groups.pl#L179

I'm not sure what the best way to fix this little snippet of perl is but I'm willing to give it a shot.  Is it a crazy idea to split the path and create it in two parts with the differing permissions?

**Comment by Profpatsch** [comment]
(triage) does this still happen?

**Comment by swarren83** [comment]
I can confirm that this is still occurring.

NixOS Version: 16.09.git.f191b65 (Flounder)

```
[root@nixos:~]# ls -lah /home/
total 12K
drwxr-xr-x  3 root root 4.0K Aug 15 09:27 .
drwxr-xr-x 16 root root 4.0K Aug  9 12:40 ..
drwx------  3 root root 4.0K Aug 15 09:27 foo

[root@nixos:~]# ls -lah /home/foo/
total 12K
drwx------ 3 root     root  4.0K Aug 15 09:27 .
drwxr-xr-x 3 root     root  4.0K Aug 15 09:27 ..
drwx------ 2 username users 4.0K Aug 15 09:27 username

[root@nixos:~]# su - username
No directory, logging in with HOME=/

[username@nixos:/]$ touch test
touch: cannot touch 'test': Permission denied

[username@nixos:/]$
```

**Comment by berot3** [comment]
Same here on 17.03pre92039.adfcc2d (Gorilla)

**Comment by berot3** [comment]
on version 17.03 I first had the issue too. Don't know why but I deleted the user-folders, did a rebuild and it worked!
I will test this again when I set up a new VM

**Comment by globin** [comment]
I think I've experienced that too recently on master.

**Comment by domenkozar** [comment]
The fix would be to create intermediate paths (in this case /home/foo/username) with less strict permissions.

I wanted to see what `useradd` does and:

```
$ sudo useradd -d /home/foo/username -m foo
[sudo] password for ielectric: 
useradd: cannot create directory /home/foo/username
```

**Comment by WhittlesJr** [comment]
Still happening

**Comment by tomberek** [comment]
close?

**Comment by alunduil** [comment]
I'm fine with closing this as I don't use nested homes on my NixOS machines anymore but it looks like this is still an issue from the comments.  I'll leave it in your discretion as well as anyone else watching this to see if it's important enough to fix.

**Comment by cyounkins** [comment]
I see a few ways to handle this:
1. Have update-users-groups.pl implicitly create intermediate directories. I did this in #50857

2. Require the user explicitly make the directories outside Nix and treat it as a mutable component. In this case I think we should warn/error when the directories are not configured correctly.

3. Require the user to explicitly configure the directories and ownership within Nix. As @Mic92 said, "We don't really know, what the intention of the users is in that case. The upper directory could be also owned by the user itself."

Personally I think 1 or 3 are better than 2. For 1 vs 3, on the one hand we want Nix to do something sensible and secure like make the directories so the user definition works. On the other hand, create-users-groups.pl isn't pure and depends on the current state of the system, breaking reproducibility.

Q: Do we rely on packages to create log directories at runtime if required?

**Comment by alunduil** [comment]
In regards to log directories, the common solution I've seen is to create directories and such for runtime state in the service's unit.  

I personally would vote for option three if an error message could indicate what action the user should take.  This would keep everything predicable while letting the user know the best course of action to proceed.

**Comment by Mic92** [comment]
Please use tmpfiles rules to manually fix this usecase: https://github.com/NixOS/nixpkgs/pull/50857#issuecomment-440728087
This is a special case and I don't see a good generic default.
