### ISSUE TITLE
oraclejdk8: request bump, 8u261 -> 8u271

### ISSUE THREAD

**Issue by kini** [NixOS/nixpkgs#108810]
I'd do this bump myself, but it seems that the "ARM 64 Hard Float ABI" tarball for aarch64 is [no longer provided by upstream](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html), and I don't have access to an aarch64 machine to play around with to see how to make things work on that platform with a different tarball.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: nixpkgs.oraclejdk8

current version: 8u261
desired version: 8u271

###### Notify maintainers

maintainers: None. Pinging @Ma27, who last bumped the version.

###### Note for maintainers

Please tag this issue in your PR.

**Comment by lourkeur** [comment]
I have an arm64 machine so when Oracle comes back online, I'll look into that.

Do you have the hashes handy by any chance?

[speculation]I suspect the change wrt ARM64 Hard Float is just a renaming since VFP is mandatory in ARMv8, but I'm not sure.

**Comment by kini** [comment]
Not sure what you mean by "when Oracle comes back online" (?), but here are the hashes I have for the three tarballs that aren't the ARM 64 Hard Float one:

```
[1] [kkini@kkini:/tmp]$ for x in jdk-*.tar.gz ; do nix-prefetch-url file:///tmp/$x ; done
[73.5 MiB DL]
path is '/nix/store/y8a5a7ya3slx1lrf8fl95inknfbz5c1m-jdk-8u271-linux-arm32-vfp-hflt.tar.gz'
04rkqyp7q5gpdpllzv1f2463m33mamxs8ra80na2mvqz4p99g4k1
[136.7 MiB DL]
path is '/nix/store/1a4jkzyzxz8sg5aqhzrnvfghj7f6cnaa-jdk-8u271-linux-i586.tar.gz'
0v9cnymg85cjzqcmyl5hgks2gmd993rhjjr9m3b17l73612mnbcw
[136.5 MiB DL]
path is '/nix/store/g51h2dcwsmb5mahx6h6z7bvbj45n7ijy-jdk-8u271-linux-x64.tar.gz'
0y1c8l5mdwlnlbmislxm1yq44v1l4kk2ql0w9rpmrdivd1m959zb
```

**Comment by lourkeur** [comment]
> Not sure what you mean by "when Oracle comes back online" (?)
This is what I'm referring too. It's still down for me as we speak, lmk if it's different for you.
![image](https://user-images.githubusercontent.com/15657735/104233617-77451680-5452-11eb-9edc-13bccc6d6974.png)

**Comment by kini** [comment]
Hmm, it's working fine for me... odd.

**Comment by lourkeur** [comment]
Can you log in and download tarballs?

**Comment by kini** [comment]
Yes. I had to get off my work VPN first, though (but I got a different looking error screen from yours, saying something more like "authentication failed").

**Comment by lourkeur** [comment]
I cant get anything from home, from Tor, or from my uni's VPN. is it my Oracle account then...?

**Comment by kini** [comment]
Could be, I'm not sure. I'm probably not the best person to test this, though, since I actually work at Oracle 😅 (not on anything related to Java, though).

**Comment by lourkeur** [comment]
Oh nvm I think it might be me being too aggressive with Firefox privacy settings. Files have been downloaded legitimately.
