### ISSUE TITLE
Xed Text Editor

### ISSUE THREAD

**Issue by boyd8444** [NixOS/nixpkgs#108817]
**Xed Text Editor from Linux Mint**
_Text editor from the Linux Mint distribution_

**xed text editor**

* homepage URL: https://www.linuxmint.com
* source URL: https://github.com/linuxmint/xed
* license: gpl2
* platforms: linux

**Comment by tu-maurice** [comment]
needs an update of a dependency #109475 to package newest version 2.8.4
