### ISSUE TITLE
Python3x vs Python3xFull # interpreter does not know about replaced/stripped pacakges of minimal python called pkgs.python38

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#108840]
**Describe the bug**
`pkgs.python3[8]` has been cut by [certain packages](https://github.com/NixOS/nixpkgs/pull/19309) but the interpreter itself is not aware of that
- This is greatly confusioning (since some [time](https://github.com/NixOS/nixpkgs/issues/19255)) and can lead easily to bugs (which are not adequate to test in test automation processes if the interpreter returns wrong results)

To use nixpkgs effectivly and e.g. in combination with tools like mach-nix or withJupyter it is importend that the pyton interprteter knows what packages are droped and which not.

**Additional context**
This issue is not about how to intall `pkgs.python38.Packages.tkinter` to the minimal python version named `pkgs.python38` in `nixos-20.09`/`nixpkgs-unstable`

**To Reproduce**
In `NixOS`/`nixpkgs` 
`pkgs = import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixos-20.09.tar.gz) {}  # "rev": "502845c3e31ef3de0e424f3fcb09217df2ce6df6" `

`nix-shell -p python38 --run "python -c 'import tkinter; print(tkinter.__name__) ; print(tkinter.__version__) '" `
fails with:
```
3.8.5 (default, Jul 20 2020, 13:26:22) 
[GCC 9.3.0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/v72cj06nk69cynckz2s12rhar25k1h7v-python3-3.8.5/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

but querying python (here `pkgs.python38`) about tkinter would give the answer that the package is installed:
```
print( help('modules tkinter') )

Here is a list of modules whose name or summary contains 'tkinter'.
If there are any, enter a module name to get more help.

idlelib.calltip_w - A call-tip window class for Tkinter/IDLE.
idlelib.config_key - Dialog for building Tkinter accelerator key bindings
idlelib.idle_test.mock_tk - Classes that replace tkinter gui objects used by an object being tested.
idlelib.multicall - MultiCall - a class which inherits its methods from a Tkinter widget (Text, for
tkinter - Wrapper functions for Tcl/Tk.
```

**Expected behavior**
- the minimal python packge - currently named `pkgs.python38` - would have an interpreter at is aware of which packges have been striped off  
- `pkgs.python38` should reference to an python interpreter that most equivalent to the `original Python[38]` https://www.python.org/

**Notify maintainers**
@fridh

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
- python38
- python38Full
```

**Comment by flokli** [comment]
I'm confused - how is this issue any different from https://github.com/NixOS/nixpkgs/issues/108842?

**Comment by InLaw** [comment]
In this issue it's about  the fact that python does not recognize modules missing like tkinter (which are part/builtin of the original `Python3.8` interpreter) and assumes that they are installed
- in  #108842 it's about the package naming/calling semantic where nixos/nixpkgs brakes with the standard (without a reason?) - so current `pkgs.python38` is a minimal version and should be names accordingly  e.g. `python38-slim`

**Comment by flokli** [comment]
There's a reason - closure size, and that's documented in the nixpkgs Python section: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#missing-tkinter-module-standard-library.

As explained there as well, getting an environment with tkinter, or any other python package is super simple. Adding tkinter (and its dependencies) by default is most likely not expected by nixpkgs users and would be observed as a regression.

I'm tempted this (and the other related issues) are a "works as designed", but let's wait for @FRidh 's answer.

**Comment by InLaw** [comment]
IT is NOT about changing the world. It's about change the name of a slim version of Python according to the standard semantic which very developer would expect (e.g. see docker)

----

one of THE MAIN reasons why it is necessary, is that all pypi packages expect the original python interpreter to be installed with - NOT a slim version. 
-> only with the python interpreter that represents the original one technically, there will be a way to enable smoothly and with "ease" pypi package imports without running into unnecessary issues and errors 

----

Sorry but 

please see the topic on [discourse](https://discourse.nixos.org/t/understand-nixpkgs-structure-semantic/10813) 
- it shows clearly that no one (not experts) could explain it (or know about the origin/reason)
- there is [no other reason](https://discourse.nixos.org/t/python3x-vs-python3xfull-package-name-change-in-2016-vs-standardized-semantic-adopt-to-standard-python-semantic/10896/3) mentioned then the difference in size of python38 and python38Full 

-> everyone who cares about <3.4M (e.g. for micro-services) can use the current slim python version // so no reason to not rename it to what current python38 is
-> do the double check and see that due to the python package dependencies there will be "never" really a difference ==3.4M of overhead. The package dependencies which will come with other installed packages will vanish die difference to zero 
- create a web development environment
- create a data science environment 
- ...
and test the size like I did!

"no one" with think about the right semantic as regression (for sure there could be FRidh, ..)

----

I don't know "any one" who would think of calling a slim python version "python38-slim" instead of python38 (which creates confusion to be mixed up with the original Python38 interpreter) wouldn't be a progress into the right direction.

To open nix python development to a broader user group of developers [which currently not working with it because it fails .. for their environments] - it would be helpful

Not only me wasted hours because environments failed "without" a clear reason 
- most people do not investigate the reason but using e.g. ubuntu/conda instead

**Comment by InLaw** [comment]
> "works as designed"

For sure no one can force you to to the right thing but with python38 not knowing that modules/packages like tkinter are not installed - which is a bug (we all agree on, right?) - can not be called "works as designed" by a developer


```
print( help('modules tkinter') )

idlelib.calltip_w - A call-tip window class for Tkinter/IDLE.
idlelib.config_key - Dialog for building Tkinter accelerator key bindings
idlelib.idle_test.mock_tk - Classes that replace tkinter gui objects used by an object being tested.
idlelib.multicall - MultiCall - a class which inherits its methods from a Tkinter widget (Text, for
tkinter - Wrapper functions for Tcl/Tk.
```

**Comment by flokli** [comment]
> IT is NOT about changing the world. It's about change the name of a slim version of Python according to the standard semantic which very developer would expect (e.g. see docker)
> 
> one of THE MAIN reasons why it is necessary, is that all pypi packages expect the original python interpreter to be installed with - NOT a slim version.
> -> only with the python interpreter that represents the original one technically, there will be a way to enable smoothly and with "ease" pypi package imports without running into unnecessary issues and errors
> 
> Sorry but
> 
> please see the topic on [discourse](https://discourse.nixos.org/t/understand-nixpkgs-structure-semantic/10813)

If you open an issue here too, please be prepared to have some discussion here too.

>     * it shows clearly that no one (not experts) could explain it (or know about the origin/reason)
> 
>     * there is [no other reason](https://discourse.nixos.org/t/python3x-vs-python3xfull-package-name-change-in-2016-vs-standardized-semantic-adopt-to-standard-python-semantic/10896/3) mentioned then the difference in size of python38 and python38Full
[…]

https://discourse.nixos.org/t/understand-nixpkgs-structure-semantic/10813/7 names the reason (closure size), especially the sudden increase if we'd add this now. This is documented in the nixpkgs manual. Pypi isn't really used to compose python environments, but the tools described there, too.

I trust @FRidh's experience with the nixpkgs tool set, and if he thinks it should stay that way, I don't see why a separate discussion here would change something. I propose moving the discussion over to discourse until some consensus has been reached.

**Comment by InLaw** [comment]
> I trust @FRidh's experience

I trust facts - NOT opinions 

Fact is
- python don't know about the manipulation of original modules 
-- this is a bug 
- size is not an argument (because slim version still can be used and 3.4M will vanish to zero in the majority of projects)
- nixpkgs breaking the semantic standard every developer expects (see e.g. docker's python3.8)

- the was [doubt](https://github.com/NixOS/nixpkgs/pull/19309) about FRidh's "sole" decision from the beginning e.g. from @vcunat 

----

Opinion is
- "Semantics is a part of best practices which is something we’re all still learning about."
-- I cannot feel that he is listening or learning - instead he is blocking : "[No](https://discourse.nixos.org/t/understand-nixpkgs-structure-semantic/10813/4). " "the fat version for no reason" 
-- it is rude when not going in a technical discussion but starting up unobjective with "vat" to stop any communication

"python3Full was at some point non-existent. It should be used in Nixpkgs only when absolutely necessary."
- WHAT are his technical arguments?? I'm open to get convinced if someone could proof it (like I tried it with tests)
- Please post that information directly on the nix website and the nix python pages (be transparent at least)

"can you explain why you are so desperate about the original Python interpreter/ python3Full as its derivative in nixpkgs?"
- FRidh is not reacting at all

**Comment by InLaw** [comment]
> until some consensus has been reached

1. When is the deadline
2. what is the criteria for "consensus"

**Comment by InLaw** [comment]
> especially the sudden increase if we'd add this now.

No one set a certain deadline for the change. Get it in the upcoming release would be fine ..

**Comment by InLaw** [comment]
> Pypi isn't really used to compose python environments

Perhaps we live in parallel universes 
- I [haven't seen](https://discourse.nixos.org/t/mixed-python-c-with-python-runtime-dependencies/7679) any real project that does not need to get additional [packages](https://discourse.nixos.org/t/unable-to-get-development-shell-with-for-a-local-python-package/10877/2) from pypi repo/or github (that is one reason why mach-nix exists)
-- pypi or github or conda-forge .. any repo release packages by default only compiled/compatible with the original (sized) python interpreter

the contrary is the case
- there are a hand full of nixpkgs which are used (e.g. python3x, tensorflow, [py]torch,..) [all other packages](https://discourse.nixos.org/t/unable-to-get-development-shell-with-for-a-local-python-package/10877/2) get imported via non-nixpkgs repos

**Comment by flokli** [comment]
Please stay respectful. "Perhaps we live in parallel universes" is not. 

I didn't set any deadline or anything, I just said it doesn't make sense to open 3 different GitHub issues (as of now) about something closely related (the set of "base" packages included in python3(Full)*), if there's already a discussion in discourse too:

 -  https://discourse.nixos.org/t/understand-nixpkgs-structure-semantic/10813
 -  https://github.com/NixOS/nixpkgs/issues/108773
 -  https://github.com/NixOS/nixpkgs/issues/108840
 -  https://github.com/NixOS/nixpkgs/issues/108840

I left https://github.com/NixOS/nixpkgs/issues/108852 open. While related, not being able to use the python3Full overlay without quirks sounds like an UX issue to me.

> I trust @FRidh's experience with the nixpkgs tool set, and if he thinks it should stay that way, I don't see why a separate discussion here would change something. I propose moving the discussion over to discourse until some consensus has been reached.

My opinion about this stays. Keep the discussion in Discourse (as it started there), and speak with @FRidh and other involved Python nixpkgs Ecosystem maintainers about this. There's also an [RFC process](https://nixos.org/governance.html) if you want to be this a more formal process.

Let's keep the nixpkgs issue tracker to actionable and not too controversial issues.

**Comment by InLaw** [comment]
> While related, not being able to use the python3Full overlay without quirks sounds like an UX issue to me.

For now, I would be pleased to have any kind of working code to get it done, with quirks would be fine (if the result is the "right" one).

**Comment by InLaw** [comment]
I would be interested get to know about any quirks or workarounds.
