### ISSUE TITLE
Deprecate use of stdenv.lib across Nixpkgs

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#108938]
Carry over discussion from IRC #nixos-dev and #108934. Inspired by the doc change in c06b2b3d671da4847f950e7e9041920b40eca0bf recommending top-level usage of `lib` over `stdenv.lib`, we want to reduce confusion for newcomers and unnecessary complexity by making `lib` the canonical way to access the Nix library. We may still want to keep `stdenv.lib` to not break external code, and place a `trace` or similar at its definition site.

```ShellSession
$ nix-shell -p ag --run 'ag "stdenv\.lib" -l | wc -l'
11783
```

There are over 11000 files where `stdenv.lib` occurs at least once. Beyond splitting this change across multiple PRs, in what ways can the change be automated?

Pinging @alyssais @Profpatsch @FRidh @Atemu @ehmry

**Comment by siraben** [comment]
In the short term, we could add this check in ofbrorg and [nix-hammering](https://github.com/jtojnar/nixpkgs-hammering), and update any examples in the documentation to reduce new usage of `stdenv.lib`.

**Comment by TredwellGit** [comment]
```
$ rg '[sS]tdenv.*\.lib' | wc -l
45311
```
Don't forget things like `stdenvNoCC.lib` and `clangStdenv.lib`.

**Comment by siraben** [comment]
Ah. So 45K occurrences across 11.8K files.

```ShellSession
$ ag '[sS]tdenv.*\.lib' -l | wc -l
11853
```

**Comment by Profpatsch** [comment]
toplevel is done https://github.com/NixOS/nixpkgs/pull/108934

**Comment by Profpatsch** [comment]
the xorg dep generator also doesn’t put it in its output anymore https://github.com/NixOS/nixpkgs/pull/108935

**Comment by Profpatsch** [comment]
`with meta = stdenv.lib;` trewide rewrite in https://github.com/NixOS/nixpkgs/pull/108978

**Comment by Profpatsch** [comment]
doc changes in https://github.com/NixOS/nixpkgs/pull/108979

**Comment by alyssais** [comment]
Graph of stdenv.lib occurrences over time:
https://edef.eu/~qyliss/nix/lib/

**Comment by siraben** [comment]
Nice! What scripts did you use to generate it?

**Comment by alyssais** [comment]
> Nice! What scripts did you use to generate it?

There's a source code link now :)

**Comment by rnhmjoj** [comment]
Found another large source of `stdenv.lib`s. Fixing cabal2nix should remove around 24k occurrences in `hackage-packages.nix`.

**Comment by siraben** [comment]
Status report
```
$ for i in pkgs/*; do printf "%s %s\n" "$i" "$(rg '[sS]tdenv\.lib' "$i" | wc -l)"; done 
pkgs/applications 2
pkgs/build-support 70
pkgs/common-updater 1
pkgs/data 0
pkgs/desktops 0
pkgs/development 30604
pkgs/games 0
pkgs/misc 0
pkgs/os-specific 452
pkgs/pkgs-lib 0
pkgs/servers 1
pkgs/shells 0
pkgs/stdenv 1
pkgs/test 8
pkgs/tools 1
pkgs/top-level 0
```

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/issues/108938#issuecomment-757474285
```
for i in pkgs/*; do printf "%s %s\n" "$i" "$(rg '[sS]tdenv.*\.lib' "$i" | wc -l)"; done 
pkgs/applications 115
pkgs/build-support 85
pkgs/common-updater 1
pkgs/data 6
pkgs/desktops 0
pkgs/development 30767
pkgs/games 24
pkgs/misc 11
pkgs/os-specific 467
pkgs/pkgs-lib 0
pkgs/servers 10
pkgs/shells 4
pkgs/stdenv 9
pkgs/test 15
pkgs/tools 36
pkgs/top-level 23
```

**Comment by siraben** [comment]
Just found out that counts stuff like `stdenv.libc` as well, so

```
$ for i in pkgs/*; do printf "%s %s\n" "$i" "$(rg '[sS]tdenv.*\.lib\b' "$i" | wc -l)"; done 
pkgs/applications 77
pkgs/build-support 84
pkgs/common-updater 1
pkgs/data 6
pkgs/desktops 0
pkgs/development 30640
pkgs/games 22
pkgs/misc 7
pkgs/os-specific 457
pkgs/pkgs-lib 0
pkgs/servers 7
pkgs/shells 0
pkgs/stdenv 1
pkgs/test 8
pkgs/tools 15
pkgs/top-level 0
```

**Comment by siraben** [comment]
Is it ok to rewrite `stdenv.cc.cc.lib` to `lib`?

**Comment by sternenseemann** [comment]
> Is it ok to rewrite stdenv.cc.cc.lib to lib?

That's the lib output of `stdenv.cc.cc`, so no.

**Comment by xaverdh** [comment]
> Is it ok to rewrite `stdenv.cc.cc.lib` to `lib`?

an easy way to find out is to evaluate both in `nix repl`

**Comment by prusnak** [comment]
Subfolders of `pkgs/development` with <10 changes needed in PR https://github.com/NixOS/nixpkgs/pull/109648

**Comment by prusnak** [comment]
> pkgs/development 30640

Around 24000+ replacements out of 30k+ are concentrated in `pkgs/development/haskell-modules`

**Comment by rnhmjoj** [comment]
> Around 24000+ replacements out of 30k+ are concentrated in pkgs/development/haskell-modules/hackage-packages.nix - should be trivial to regenerate the file with the new desired contents.

I'm working on it but it's a bit more complicated than I anticipated.

**Comment by siraben** [comment]
> I'm working on it but it's a bit more complicated than I anticipated.

What problems are you running into?

**Comment by rnhmjoj** [comment]
Part of code generation of cabal2nix is in an external dependency, so I had to open two PRs.
The dependency is itself on Hackage, so we may have to wait until the change propagates to Stackage LTS and then Nixpkgs, unless peti will use an override or something: I'm not familiar with the cabal2nix workflow.

**Comment by sternenseemann** [comment]
I think the haskell-updates are mostly done from a local checkout of cabal2nix, so it depends mostly on what version peter is using. You can also probably just ask him, he is generally available for such things on his [friday](https://github.com/NixOS/nixpkgs/pull/109474#issue-555926853) [livestream](https://www.twitch.tv/peti343).

**Comment by SuperSandro2000** [comment]
@peti could you help here?

**Comment by peti** [comment]
The Haskell infrastructure has switched to the new style with commit c78d10c8d3d57af385c0a3fd065403077756d715. It will land in `master` this Friday. I have also updated the generator code and released new versions to Hackage, so I guess the Haskell infrastructure can be considered *done*.

**Comment by rnhmjoj** [comment]
Thank you @peti!

**Comment by SuperSandro2000** [comment]
```
$ for i in pkgs/*; do printf "%s %s\n" "$i" "$(rg '[sS]tdenv.*\.lib\b' "$i" | wc -l)"; done 
pkgs/applications 75
pkgs/build-support 36
pkgs/common-updater 0
pkgs/data 0
pkgs/desktops 0
pkgs/development 123
pkgs/games 19
pkgs/misc 8
pkgs/os-specific 4
pkgs/pkgs-lib 0
pkgs/servers 6
pkgs/shells 0
pkgs/stdenv 1
pkgs/test 0
pkgs/tools 12
pkgs/top-level 0
```

**Comment by siraben** [comment]
More accurate regex: (the one above captures stuff like `stdenv.cc.cc.lib`

```
$ for i in pkgs/*; do printf "%s %s\n" "$i" "$(rg '[sS]tdenv[a-zA-Z0-9]*\.lib\b' "$i" | wc -l)"; done
pkgs/applications 5
pkgs/build-support 84
pkgs/common-updater 1
pkgs/data 0
pkgs/desktops 0
pkgs/development 94
pkgs/games 2
pkgs/misc 1
pkgs/os-specific 1
pkgs/pkgs-lib 0
pkgs/servers 3
pkgs/shells 0
pkgs/stdenv 1
pkgs/test 8
pkgs/tools 3
pkgs/top-level 0
```

**Comment by siraben** [comment]
When #110917 is merged, this will be the result

```ShellSession
$ for i in pkgs/*; do printf "%s %s\n" "$i" "$(rg '[sS]tdenv[a-zA-Z0-9]*\.lib\b' "$i" | wc -l)"; done
pkgs/applications 0
pkgs/build-support 0
pkgs/common-updater 0
pkgs/data 0
pkgs/desktops 0
pkgs/development 66
pkgs/games 0
pkgs/misc 0
pkgs/os-specific 0
pkgs/pkgs-lib 0
pkgs/servers 0
pkgs/shells 0
pkgs/stdenv 0
pkgs/test 0
pkgs/tools 0
pkgs/top-level 0
```

Three Nix files remain that use `stdenv.lib` directly.

```ShellSession
$ rg "[sS]tdenv[a-zA-Z0-9_'-]*\.lib\b" -lc | grep nix
pkgs/development/compilers/elm/packages/node-env.nix:22
pkgs/development/node-packages/node-env.nix:22
pkgs/development/web/newman/node-env.nix:22
```

**Comment by siraben** [comment]
The last usages of it can be found by commenting out where it is inherited in `pkgs/stdenv/generic/default.nix`.

**Comment by samuela** [comment]
I just got this warning while doing a `home-manager switch`, but it doesn't give me any info as to which derivations are at fault. Is there any way we could improve the message to identify culprits?

**Comment by jtojnar** [comment]
@samuela With `config.nixpkgs.allowAliases = false;`, you should get a hard error which will allow you to use `--show-trace`. Or you can update Nixpkgs, since it has been removed in https://github.com/NixOS/nixpkgs/commit/d2c9f816e3e8dd1bcb2069276206c19688b62baf.
