### ISSUE TITLE
plasma5 not overridable

### ISSUE THREAD

**Issue by noonien** [NixOS/nixpkgs#108992]
**Describe the bug**
When trying to use overrideScope' on plasma5, an error occurs.

**To Reproduce**
Have the following in configuration.nix:
```\
  nixpkgs.overlays = [
    (final: prev: {
      plasma5 = prev.plasma5.overrideScope' (sfinal: sprev: lib.makeOverridable { });
    })
  ];
```

**Expected behavior**
plasma5 to be successfully overriden. Instead, this error occurs:
```
error: --- EvalError ------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
at: (14926:14) in file: /nix/store/agbj0icd0bx0zlrbk3f0qsrzv4v8dpap-source/pkgs/top-level/all-packages.nix

 14925| 
 14926|     inherit (plasma5.override { libsForQt5 = self; })
      |              ^
 14927|       kdecoration khotkeys libkscreen libksysguard bluedevil

attribute 'override' missing
```

**Screenshots**

**Additional context**
I'm actually trying to modify an output file of plasma-desktop, in this case, ${plasma5.plasma-desktop}/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js.

I want to patch the file so that new users use the Application Menu (kicker), not Application Launcher (kickoff), by default. 
I'm trying to patch the **output** so there's no need to recompile plasma-desktop.

**Notify maintainers**

**Metadata**
I'm in the process of migrating to flakes, nix-info doesn't seem to work right now.
My nix version is:  `nix (Nix) 2.4pre20201201_5a6ddb3`
nixpkgs (branch nixpkgs-20.09) (from flakes.lock):
```json
      "locked": {
        "lastModified": 1609725427,
        "narHash": "sha256-Yn97AVjFvQunGmwK3nnr7LihzMnp72jyaYNRRaJvAZ4=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "c5c6009fb436efe5732e07cd0e5692f495321752",
        "type": "github"
      }
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: plasma5
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
The change that would allow something like that is currently in staging https://github.com/NixOS/nixpkgs/pull/102168.
```
final: prev: {
  plasma5Packages = super.plasma5Packages.overrideScope' (self: super: {
    ...
  });
}

**Comment by noonien** [comment]
I see, thank you!
