### ISSUE TITLE
zeal: startup = segfault

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#10891]
Zeal does not work, it segfauls when starting.

**Comment by matthiasbeyer** [comment]
@vcunat :+1:

**Comment by svenkeidel** [comment]
I will take a look at it. Sorry for the dealy

**Comment by svenkeidel** [comment]
Cannot reproduce. Are you trying this on a mac?

**Comment by matthiasbeyer** [comment]
@svenkeidel Nope, I'm on nixos.

**Comment by svenkeidel** [comment]
Which channel do you use?

**Comment by matthiasbeyer** [comment]
unstable. It works now. Maybe the latest update fixed this.

Thanks you for your patience!

**Comment by svenkeidel** [comment]
No problem, it probably was a problem with one of the dependencies of zeal. Thanks for reporting.

**Comment by matthiasbeyer** [comment]
Reopening this because zeal segfaults again.

```
$ nix-shell -p zeal --run zeal
/run/user/1000/nix-shell.fHgdoF/rc: Zeile 1:  4450 Segmentation fault      zeal
```

On unstable at 

```
$ nixos-version
16.03pre73316.93d8671 (Emu)
```

**Comment by jgillich** [comment]
Cannot reproduce on a fairly recent master (16.03.git.c3bb681M)

**Comment by matthiasbeyer** [comment]
Cannot reproduce on latest unstable as well. Closing again.
