### ISSUE TITLE
Can't build ghci-ng

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#10897]
Can't build [ghci-ng](https://github.com/chrisdone/ghci-ng/issues/23)
```
Preprocessing executable 'ghci-ng' for ghci-ng-7.6.3.5...

ghc/Main.hs:43:8:
    Could not find module ‘StaticFlagParser’
```
Have try to build with current `ghc 7.10.2` and with `ghc763`. The same error.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L1275

**Comment by peti** [comment]
`ghci-ng` depends on rather specific, outdated versions of its build inputs, and we don't have those versions in Nixpkgs, nor can we easily provide them. IMHO, the package should be update upstream. Once a new release show up on Hackage, we'll have it in Nixpks within a couple of hours.

**Comment by Pitometsu** [comment]
Ok, it build as:
```nix
    haskellPackageOverrides = self: super: with pkgs.haskell-ng.lib; {
      ghci-ng = overrideCabal super.ghci-ng (attrs: {
        src = pkgs.fetchFromGitHub {
          owner = "chrisdone";
          repo = "ghci-ng";
          rev = "738f66f3d1f1a3b7ba574fb9c83da793179a42c3";
          sha256 = "0flawgqdn01axkzac3zkzzqgbjm7z7b4y0xwcvr360x1fbnmmp52";
        };
        executableHaskellDepends =
          let deps = with super; [ containers syb time transformers ];
          in attrs.executableHaskellDepends ++ deps;
        version = "0.0.0";
        homepage = "https://github.com/chrisdone/ghci-ng#readme";
	description = "Next generation GHCi";
      });
    };
```
