### ISSUE TITLE
packaging request: SuperSlicer

### ISSUE THREAD

**Issue by anna328p** [NixOS/nixpkgs#109086]
**Project description**
Fork of PrusaSlicer with features rejected by upstream.

**Metadata**

* homepage URL: https://github.com/supermerill/SuperSlicer
* source URL: https://github.com/supermerill/SuperSlicer
* license: agpl3
* platforms: unix, linux, darwin

**Comment by lovesegfault** [comment]
It's already packaged. It's `super-slicer`.
