### ISSUE TITLE
Haskell: Multi-package development environments

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#10902]
It's often nice to work on multiple packages at the same time, where some of those packages depend on others of them. I hear Cabal wants to better support such a development idiom some day, but we can get a head start right now.

The basic task is given a set of packages `P`, we want the following package in our environment: `(Union_{q in Q} deps(q)) \ Q` I propose an implementation like the following:

``` nix
pkgSet: listofAttrs: let
  perms = /*all permutations of listofAttrs */;
  mkPkgSet = attr: rest: pkgSet.overrride {
    overrides = listToAttrs (map (a: { name = a; value = null; }) rest);
  };
  pkgs = map (as: mkPkgSet (head as) (tail as).${head as}) perms;
in union (map (p: p.deps) pkgs)
```

The idea is given a list of package (attributes in the package set). Get a build plan for each package with the others "nulled out". Then union all those packages together.

In a future where we have package functions, and we can make one package set with all the packages "nulled out", and then callPackage each package fun to define `pkgs`.

``` nix
pkgSet: listofAttrs: let
  pkgSet2 = pkgSet.overrride {
    overrides = listToAttrs (map (a: { name = a; value = null; }) listofAttrs);
  };
  pkgs = map (p: pkgSet2.callPackage pkgSetFuns.${p} {}) listofAttrs;
in union (map (p: p.deps) pkgs)
```

Hopefully this makes some sense :).

CC @peti @pchiusano

**Comment by Profpatsch** [comment]
You can do this like so:

```nix
let
  hp = haskellPackages.override {
   overrides = self: super: {
      pkg1 = self.callPackage ./pkg1 {};
      pkg2 = self.callPackage ./pkg2 {};
    };
  };
in hp.pkg1
```

Close @peti

**Comment by Ericson2314** [comment]
@Profpatsch mm the key word here is *work on*. One thing that `stack repl` (but not `cabal repl`, last I checked) can do is more than one package's source at a time, so multiple packages can be simultaneously developed.

Let's assume in your example that `pkg1` depends on `pkg2`. If one edits both packages and then loads a shell for `pkg2`, `pkg1` will be rebuilt. I want a way to make a shell for *both* packages, such only dependencies which rely on neither are built by nix. Then it's up to `stack repl` or `cabal repl` to build everything else depending on any of the packages being edited.

**Comment by Profpatsch** [comment]
Hm, how about:

shell.nix
```haskell
(haskellPackages.ghcWithPackages (hp: [ hp.pkg1 hp.pkg2 ]).env
```

I’m not sure whether that gives both environments, though. It probably isn’t transitive enough, right?

**Comment by Ericson2314** [comment]
@Profpatsch but that's both packages pre-built. I want all the dependencies of each that don't themselves depend on any of `pkg1` or `pkg2`.

**Comment by Profpatsch** [comment]
I remember stumbling on that, too. Often one or both don’t build (because you are working on them).

**Comment by Profpatsch** [comment]
(triage) what’s the status?

**Comment by Ericson2314** [comment]
@elvishjerricco's `shellFor` has perfectly solved the common case where the packages under development immediately, rather than transitively, depend on each other.
