### ISSUE TITLE
Package request: FreeTube 

### ISSUE THREAD

**Issue by Flygrounder** [NixOS/nixpkgs#109014]
**Project description**
FreeTube is a private, open source client for YouTube. It allows watching videos and subscribing channels locally, without logging into Google account.

**Metadata**

* homepage URL: https://freetubeapp.io/
* source URL: https://github.com/FreeTubeApp/FreeTube
* license: AGPL v3.0
* platforms: linux, darwin

**Comment by neonfuz** [comment]
https://github.com/NixOS/nixpkgs/pull/109036
Looks like a package is on the way. Current version needs some work before it's merged but you can try it out with:
`nix-env -f https://github.com/ryneeverett/nixpkgs/archive/freetube-init.tar.gz -iA freetube`
(installs to nix-env)

**Comment by ryneeverett** [comment]
Resolved via #109036.
