### ISSUE TITLE
darwin: propose exporting headers to $out/usr/include

### ISSUE THREAD

**Issue by holymonson** [NixOS/nixpkgs#109078]
Normally we export headers to `$out/include`. However, according to https://clang.llvm.org/docs/UsersManual.html#relocatable-pch-files
> If the headers are installed in some other system root, the -isysroot option can be used provide a different system root from which the headers will be based. For example, -isysroot /Developer/SDKs/MacOSX10.4u.sdk will look for mylib.h in /Developer/SDKs/MacOSX10.4u.sdk/usr/include/mylib.h.

In order to use `-isysroot`, the prefix `/usr` can not be striped, otherwise we can only use `-I`. I have found several cases where we are patching Makefile with `-I${someLib}/include`, but in fact we could have it solved  by simply setting variable `SDKROOT=${someLib}`. 

Therefore, I hope we can make an agreement following apple's sdk structure, for darwin libraries we should use `$out/usr/include` `$out/usr/lib` rather than `$out/include` `$out/lib`, and `$out/System/Library` rather than `$out/Library`.

ping @LnL7 @matthewbauer @Infinisil @SuperSandro2000 @siraben

**Comment by SuperSandro2000** [comment]
Would you symlink the old paths?

**Comment by holymonson** [comment]
> Would you symlink the old paths?

Yes we can. In fact all Makefiles shipped by apple opensource packages are written with `/usr` prefixed (private files with `/usr/local`). For each of them, we are either patching Makefile before build, or moving to upper level after.

Here is a solution that we keep the `/usr` prefix, and link `include -> usr/inculde` `lib -> usr/lib` to follow common rules.

**Comment by holymonson** [comment]
FYI, `-sysroot` or `--sysroot` is also available in gcc, though it's mainly used by clang. https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html

**Comment by SuperSandro2000** [comment]
> For each of them, we are either patching Makefile before build, or moving to upper level after.

I was more thinking about maintaining compatibility with packages we currently overwrite. Not sure if it is worth the effort and if there are only 5 or 10 of them we can also fix them up really quick but if like 500 packages have that patch it could take us a little longer. 

> Here is a solution that we keep the /usr prefix, and link include -> usr/inculde lib -> usr/lib to follow common rules.

I would be fine with that but I am not a core darwin maintainer.

**Comment by holymonson** [comment]
After thinking twice, this may be not worth it, `-I` can do the job inside nixpkgs. I'm closing it unless other maintainer want to discuss.
