### ISSUE TITLE
create virtual ip

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#10909]
i want to create a virtual interface, debian equivalent would be:

```
auto eth0:1
 iface eth0:1 inet static
 address 10.0.0.5
```

the `nixos-rebuild switch` works with this configuration.nix, no syntax error, but `ifconfig` don't show the second interface.

```
networking.interfaces = { 
  eth0.ip4 = [ { address = "10.0.0.13"; prefixLength = 24; } ];
  "eth0:1".ip4 = [ { address = "10.0.0.5"; prefixLength = 24; } ];
};
```

i tried with the `virtual` option but i think that is something different:

```
networking.interfaces = { 
  eth0.ip4 = [ { address = "10.0.0.13"; prefixLength = 24; } ];
  "eth0:1" = {
    ip4 = [ { address = "10.0.0.5"; prefixLength = 24; } ];
    virtual = true;
    virtualType = "tun";
  };
};
```

```
starting the following units: network-addresses-eth0.service, systemd-modules-load.service
warning: the following units failed: eth0:1-netdev.service

● eth0:1-netdev.service - Virtual Network Interface eth0:1
   Loaded: loaded (/nix/store/2npfn9nh1f82xr2qvhsyvqbggag6aasy-unit-eth0-1-netdev.service/eth0:1-netdev.service)
   Active: failed (Result: exit-code) since Mo 2015-11-09 01:45:34 CET; 1min 30s ago
  Process: 5704 ExecStart=/nix/store/g3q774xh9qdrwabzz52ngl3yb10aviqi-unit-script/bin/eth0:1-netdev-start (code=exited, status=1/FAILURE)
 Main PID: 5704 (code=exited, status=1/FAILURE)

Nov 09 01:45:34 cg-gw eth0:1-netdev-start[5704]: ioctl(TUNSETIFF): Invalid argument
Nov 09 01:45:34 cg-gw systemd[1]: eth0:1-netdev.service: main process exited, code=exited, status=1/FAILURE
Nov 09 01:45:34 cg-gw systemd[1]: Failed to start Virtual Network Interface eth0:1.
Nov 09 01:45:34 cg-gw systemd[1]: Unit eth0:1-netdev.service entered failed state.
Nov 09 01:45:34 cg-gw systemd[1]: eth0:1-netdev.service failed.
warning: error(s) occured while switching to the new configuration
```

when i use this configuration, i have 2 ips on `eth0`, but i need a second interface to apply iptables rules to it.

```
networking.interfaces = { 
  eth0.ip4 = [ { address = "10.0.0.13"; prefixLength = 24; } { address = "10.0.0.5"; prefixLength = 24; } ];
};
```

```
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether be:54:2b:f2:81:ae brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.13/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.5/24 scope global secondary eth0
       valid_lft forever preferred_lft forever
```

**Comment by copumpkin** [comment]
This might be related: https://github.com/NixOS/nixpkgs/issues/7227

**Comment by davidak** [comment]
Maybe this is also related: https://github.com/NixOS/nixpkgs/issues/2590

**Comment by copumpkin** [comment]
Looks like we have a lot of duplicates :smile: 

@wkennington seemed to know a lot about this problem when I talked to him about my loopback issue, but he suggested that my loopback problem was due to some special-casing in some of the systemd code. Not sure what causes your issue.

**Comment by Profpatsch** [comment]
(triage) what’s the status?

**Comment by davidak** [comment]
that still don't work and we need a solution / documentation.

**Comment by mbrock** [comment]
I'm using this configuration.

    boot.kernelModules = ["dummy"];
    networking.interfaces = {
      dummy0.ip4 = [{
        address = "172.16.0.1";
        prefixLength = 24;
      }];
    };

It seems to work fine without touching my real interfaces nor interfering with NetworkManager.

I'm a networking newbie so I don't know exactly what a `dummy` interface is, but it seems to work for me as a virtual local interface.

**Comment by davidak** [comment]
To create a virtual IP or Interface alias (as the debian wiki called it), you can just specify multiple IPs like this:

```
    interfaces = {
      ens3.ip4 = [
        { address = "192.168.0.2"; prefixLength = 24; }
        { address = "192.168.0.3"; prefixLength = 24; }
      ];
      ens3.ip6 = [
        { address = "2a01:03f8:0c17:5c0e::1"; prefixLength = 64; }
        { address = "2a01:03f8:0c17:5c0e::2"; prefixLength = 64; }
        { address = "2a01:03f8:0c17:5c0e::3"; prefixLength = 64; }
        { address = "2a01:03f8:0c17:5c0e::4"; prefixLength = 64; }
        { address = "2a01:03f8:0c17:5c0e::15"; prefixLength = 64; }
      ];
    };
```

The `networking.interfaces.<name?>.ip4` option describes this now clearly:

>List of IPv4 addresses that will be statically assigned to the interface.

So this issue can get closed now :)

**Comment by mkg20001** [comment]
There's another solution which is to use macvlans, which is pretty close and exactly what I needed

(In my case this allows olsrd to run on it's own interface without having network manager interfere)

```nix
{
  networking = {
    macvlans.mesh0 = {
      interface = "eth0";
    };
    interfaces = {
      mesh0 = {
        ipv4 = {
          addresses = [
            {
              address = ''10.12.23.66'';
              prefixLength = 16;
            }
          ];
        };
      };
  };
}
```

**Comment by ipochto** [comment]
> To create a virtual IP or Interface alias (as the debian wiki called it), you can just specify multiple IPs like this:
> 
> ```
>     interfaces = {
>       ens3.ip4 = [
>         { address = "192.168.0.2"; prefixLength = 24; }
>         { address = "192.168.0.3"; prefixLength = 24; }
>       ];
>     };
> ```
> 
> So this issue can get closed now :)

Hi there.

But you've mentioned : 
> when i use this configuration, i have 2 ips on eth0, but i need a second interface to apply iptables rules to it.

With this solution you still have a single interface.

**Comment by zoechi** [comment]
#issuecomment-375982216

This doesn't work with DHCP and firewall rules, like opening a port only on a specific ip address also doesn't work.
