### ISSUE TITLE
ssh pubkey login not working

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#10904]
i have set my public key in `configuration.nix` like this:

`users.extraUsers.root.openssh.authorizedKeys.keys = [ "ssh-rsa AAAA... davidak" ];`

the [options page](http://nixos.org/nixos/options.html) says that the option is `users.users.<name?>.openssh.authorizedKeys.keys` but it also don't work.

if i try to login i get a password prompt:

```
$ ssh -v server
[...]
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/davidak/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Offering RSA public key: /Users/davidak/.ssh/id_rsa_git
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: /Users/davidak/.ssh/id_dsa
debug1: Next authentication method: keyboard-interactive
Password:
```

the key is in `/etc/ssh/authorized_keys.d/root` but in 3 lines, is that correct?

```
ssh-rsa
AAAA...
davidak

```

NixOS 15.09 but i had it also with 14.12.

**Comment by vcunat** [comment]
> the key is in /etc/ssh/authorized_keys.d/root but in 3 lines, is that correct?

That's likely the cause. At least `~/.ssh/known_hosts` uses one like per key.

**Comment by peti** [comment]
Are you sure that the value

    "ssh-rsa AAAA... davidak"

is given in one line in your configuration.nix?

**Comment by davidak** [comment]
>Are you sure that the value is given in one line in your configuration.nix?

no :D

i pasted the config again from my editor over ssh and now it works.
maybe it was due to some paste error before the nixos-install.

i installed another vm yesterday where it works directly.

**Comment by vcunat** [comment]
:-)
