### ISSUE TITLE
Sqlite needs sqlite_unlock_notify tag to prevent deadlock

### ISSUE THREAD

**Issue by zeripath** [NixOS/nixpkgs#109004]
At:

https://github.com/NixOS/nixpkgs/blob/ffce5a082b464f0715ac4028d7bc79171f20203e/pkgs/applications/version-management/gitea/default.nix#L40

This should also add `sqlite_unlock_notify` as per Gitea's docs. (https://docs.gitea.io/en-us/install-from-source/#build )

Without this tag sqlite will frequently report that the database is locked and cause multiple internal server errors.

See https://github.com/go-gitea/gitea/issues/14274#issuecomment-757681995

**Comment by sbourdeauducq** [comment]
If spmeone needs a quick fix in ``configuration.nix``:

```
  nixpkgs.config.packageOverrides = super: let self = super.pkgs; in {
    gitea = super.gitea.overrideAttrs(oa: {
      preBuild = let tagsString = "pam sqlite sqlite_unlock_notify"; in ''
        export buildFlagsArray=(
          -tags="${tagsString}"
          -ldflags='-X "main.Version=${oa.version}" -X "main.Tags=${tagsString}"'
        )
      '';
    });
  };
```
