### ISSUE TITLE
Document staging purpose

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#10915]
http://comments.gmane.org/gmane.linux.distributions.nixos/13447

- [ ] document how merging is done

**Comment by lethalman** [comment]
https://nixos.org/nixpkgs/manual/#idm140737319144352

**Comment by vcunat** [comment]
That seems the proper place to me.

**Comment by vcunat** [comment]
Reopen if you believe it needs improving.

**Comment by primeos** [comment]
> http://comments.gmane.org/gmane.linux.distributions.nixos/13447

Sadly that link isn't available anymore. Probably due to the following:

http://gmane.org/about/:
> At the end of July 2016, Gmane briefly closed and was acquired by Yomura in mid August. 
>
> Gmane is currenly being rebuilt in Python and PHP and uses ElasticSearch for its underlying document store. At the time of writing, we have just over 112M documents indexed.

Do we have a "backup" of that information?

And sorry for commenting on this old & closed issue...

**Comment by vcunat** [comment]
It's in the [nixpkgs manual](http://nixos.org/nixpkgs/manual/).  I thought it would be understood from the discussion, but let me say it more explicitly.  There's no "named" (i.e. stable) link directly to that section, so that's why the exact old link doesn't work anymore.

**Comment by primeos** [comment]
I might be wrong here but I think you understood that the link to the section in the nixpkgs manual is broken: https://nixos.org/nixpkgs/manual/#idm140737319144352

But I actually meant the link we referred to inside the manual: http://comments.gmane.org/gmane.linux.distributions.nixos/13447

This is the relevant excerpt:
> It's only for non-breaking mass-rebuild commits. That means it's not to be used for testing, and changes must have been well tested already. [Read policy here](http://comments.gmane.org/gmane.linux.distributions.nixos/13447).

**Comment by vcunat** [comment]
@primeos: I see now, thanks!  That should get fixed.

**Comment by l2dy** [comment]
The broken link hasn't been fixed yet. https://github.com/NixOS/nixpkgs/blob/77161de4546697f9bf2da6d081eeba4c399b3313/doc/submitting-changes.xml#L479
