### ISSUE TITLE
A question about kernel module configs and it not being found on Live CD

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#10912]
What is the kernel module `configs`?

I noticed it being mentioned here: https://github.com/NixOS/nixpkgs/issues/6444#issuecomment-75075591

The reason I ask is because running the below on the Live CD:

```
systemctl status systemd-modules-load
```

Shows:

```
nixos systemd-modules-load[482]: Failed to find module 'configs'
```

Inside `/etc/modules-load.d/nixos.conf` shows `configs` as one of the modules scheduled to be loaded at boot.

It appears to be specified here: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/kernel.nix#L161

I googled around and got no information on this kernel module, and why it isn't found on the Live CD?

Running `modprobe configs` or `modinfo configs` shows nothing.

--EDIT--

I found this: https://wiki.gentoo.org/wiki/Kernel/IKCONFIG_Support

Still no idea why `configs` is not available in the Live CD then?

According to the gentoo docs, a `/proc/config.gz` should exist if IKCONFIG is built into the kernel. And this file does exist on the Live CD. Does this mean that the kernel that NixOS is running on already has `configs` module already built in, and hence doesn't require loading it as a loadable module on boot?

Running `zcat /proc/config.gz | grep IKCONFIG` shows that the current kernel has IKCONFIG built in, hence there's no need to load the `configs` module manually. So can we remove it from here? https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/kernel.nix#L161 That way I can minimise my systemctl errors on startup.

**Comment by nbp** [comment]
@wkennington , any ideas?

**Comment by dezgeg** [comment]
Yes, it would appear that the `configs` module only exists if `CONFIG_IKCONFIG=m`. Since we always set it to `y` in `common-config.nix`, it could be removed from `boot.kernelModules`.

**Comment by javins** [comment]
I came across the error @CMCDragonkai mentioned when auditing the systemd journal to make sure I understood all the >= err severity entries in systemd's journal on my new nixos system.

Here's some history I dug up while investigating:

@edolstra enabled the configs module by default for all nixos systems 2014-05 here: https://github.com/NixOS/nixpkgs/commit/6572708d3914a07a1c58f6162b999925ee3d695e

@dezgeg set `IKCONFIGS y` to always be part of the common kernel build config here in 2015-06:  https://github.com/NixOS/nixpkgs/commit/6be70d17c0f43368b008f54e3c3f2aa093249e63

It's pretty apparent we don't need both of these.  If the approach is gonna be to build ikconfig not as a module we should remove it from `boot.kernelModules`.

The alternative would be in top-level/platforms.nix to setup `IKCONFIG m` for arm platforms in `kernelExtraConfig`.  This is an alternative approach to @dezgeg's change (see discussion in #8173) that gets `/proc/config.gz` available on the platforms they care about.  This would go with the philosophy of keeping the kernel more modular and give users the option to add `boot.blacklistedKernelModules = [ "configs" ];` to their machine's configuration.nix if they really didn't want the functionality.

Honestly I'd prefer the latter, as it gives the user a bit more control.

**Comment by javins** [comment]
Thinking about the issue further, I don't even think we'd want to bother with `kernelExtraConfigs` for plaforms that don't have a `kernelAutoModules`.  We can keep the setting in common-config.nix, and just replace `IKCONFIG y` with `IKCONFIG m`, which will satisfy `IKCONFIG_PROC`s dependency.

**Comment by vcunat** [comment]
Thanks for digging up some of the details. The original introduction seems older than @dezgeg's `IKCONFIGS y` and goes to `IKCONFIG_PROC y`, but anyway... let's keep this simple for now, i.e. always built-in.

**Comment by javins** [comment]
Thanks @vcunat!

**Comment by CMCDragonkai** [comment]
Was this backported to 15.09? Thanks @vcunat.

**Comment by vcunat** [comment]
I see it was in 5b1a0a9584.
