### ISSUE TITLE
clang-format from clang overrides clang-format from clang-tools on macOS

### ISSUE THREAD

**Issue by sjoerdvisscher** [NixOS/nixpkgs#109116]
**Describe the bug**
On macOS I don't get the right version of clang-format in a nix shell

**To Reproduce**
1. Run `nix-shell --pure -p clang-tools which` on a macOS
2. `$ which clang-format`
3. The result is: `/nix/store/19gxjliz9sbhm2aqlghryk67n6r40z6f-clang-7.1.0/bin/clang-format`

**Expected behavior**
Expected result would be `/nix/store/fb52vzv8rhw2vfqaid12rswhiqwp3mr8-clang-tools-10.0.0/bin/clang-format`

**Additional context**
Does not happen on Linux

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(sjoerdvisscher): `"nixpkgs-20.09pre235494.225628ff02c"`
 - nixpkgs: `/Users/sjoerdvisscher/.nix-defexpr/channels/nixpkgs`

**Comment by veprbl** [comment]
The `nix-shell -p` will intentionally include the compiler from `stdenv`: https://github.com/NixOS/nix/blob/a93916b1905cd7b968e92cd94a3e4a595bff2e0f/src/nix-build/nix-build.cc#L266-L270
A workaround for this would be write a shell.nix or use `-E` and ask for `stdenvNoCC`:
```
# nix-shell --pure -p clang-tools which --run "which clang-format"
/nix/store/y560ky7gjz05zsfr3sjx139hzkih9xad-clang-7.1.0/bin/clang-format
# nix-shell --pure -E '(with import <nixpkgs> {}; runCommandNoCC "shell" { buildInputs = [ clang-tools which ]; }) ""' --run "which clang-format"
/nix/store/61c4ll3a7sakb8l8nc7899wgy1cwv18i-clang-tools-11.0.0/bin/clang-format
```

The `nix shell` command from the new interface currently doesn't have this problem:
```
# nix shell nixpkgs#{clang-tools,which} -ic which clang-format
/nix/store/61c4ll3a7sakb8l8nc7899wgy1cwv18i-clang-tools-11.0.0/bin/clang-format
```

**Comment by sjoerdvisscher** [comment]
Hmm, I think I still want the other CC tools, just not `clang-format`. I do have a `shell.nix` file. How could I do this?

**Comment by veprbl** [comment]
```nix
{ pkgs ? import <nixpkgs> {} }:
  
with pkgs;

mkShell.override { stdenv = stdenvNoCC; } {
  buildInputs = [ clang-tools which ];
}
```

**Comment by veprbl** [comment]
```nix
{ pkgs ? import <nixpkgs> {} }:
  
with pkgs;

mkShell.override { stdenv = stdenvNoCC; } {
  buildInputs = [ clang-tools which stdenv.cc ];
}
```

```
# nix-shell --run "which clang-format; which clang"
/nix/store/61c4ll3a7sakb8l8nc7899wgy1cwv18i-clang-tools-11.0.0/bin/clang-format
/nix/store/q6la7x65vy350bawxkxmnhcvi0vhqmyh-clang-wrapper-7.1.0/bin/clang
```

**Comment by sjoerdvisscher** [comment]
Thanks, this works perfectly!
