### ISSUE TITLE
Merge staging into master

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#10925]
[Remaining issues](http://hydra.nixos.org/eval/1229961?compare=trunk&full=1#tabs-now-fail):

- [x] darwin is broken http://hydra.nixos.org/build/27514654
- [x] node 4 is failing http://hydra.nixos.org/build/27568228
- [x] some python regressions? http://hydra.nixos.org/build/27613951 http://hydra.nixos.org/build/27560001

**Comment by domenkozar** [comment]
@pikajude @datakurre could you take a look why is ncurses failing on `staging`?

**Comment by vcunat** [comment]
The darwin breakage is being discussed on #10622. I would have merged, only I originally wanted to have @pikajude reaction as he deleted the patch on staging, but perhaps it wasn't intended?

**Comment by vcunat** [comment]
Hydra is stuck &ndash; it has done nothing during the last hour at least, /cc @edolstra @rbvermaa (or whom we should ping with such things?).

**Comment by domenkozar** [comment]
I've pushed 4d1129828a7c8af8e75c54175141c009e6f0651f and 3d02d332b0633dba21888de5fabac7cd412cf468 to fix nodejs on staging.

**Comment by pSub** [comment]
xulrunner is failing on staging (http://hydra.nixos.org/build/27566997/) but fixed (60b4d47f90cb872ac4552be049ebdf8dc4791191) on master. Does it make sense to pick that commit to staging before merge?

**Comment by domenkozar** [comment]
I'll merge master into staging.

**Comment by pSub** [comment]
Ok, thanks.

**Comment by domenkozar** [comment]
Done.

**Comment by lethalman** [comment]
@wkennington why did you update mesa in 0ba740d26b3e851a181034d8650ece94163d0fae ? Was that so necessary?

**Comment by pikajude** [comment]
@vcunat the patch deletion was accidental and should be reversed if it hasn't been already

**Comment by vcunat** [comment]
@pikajude: it was done in 63385e971.

**Comment by wkennington** [comment]
@lethalman Just merge staging without that commit when it builds and then
eventually merge the mesa commit. It should be fairly easy to merge if you
just merge checkpoints hydra has built.

**Comment by domenkozar** [comment]
I've fixed Python but now webkitgtk fails (probably due to gtk3+ bump): http://hydra.nixos.org/build/27677697

**Comment by lethalman** [comment]
On Fri, Nov 13, 2015 at 5:47 PM, William A. Kennington III <
notifications@github.com> wrote:

> @lethalman Just merge staging without that commit when it builds and then
> eventually merge the mesa commit. It should be fairly easy to merge if you
> just merge checkpoints hydra has built.


It's not about being able to merge it, it's about hydra computational power
not able to complete that evaluation. Looks like now however hydra has been
super responsive, that's good.


-- 
NixOS Linux <http://nixos.org>

**Comment by peti** [comment]
Does anyone know what might have caused https://github.com/NixOS/nixpkgs/issues/11084?

**Comment by peti** [comment]
Closing this issue because staging has been merged.
