### ISSUE TITLE
tlp: No batteries detected.

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10923]
I've installed `serviced.tlp`. Sometimes, after I reboot my computer, the battery disappears from both `tlp stat` and Gnome3.

```
$ tlp stat
+++ Battery Status
No batteries detected.
```

**Comment by abbradar** [comment]
Hmm, I *think* this is a hardware/kernel issue but I'm not sure. Let's investigate:

1. `ls /sys/class/power_supply`, notice anything battery-ish (suppose it's `BAT0`).
2. `cat /sys/class/power_supply/BAT0/energy_now` (to make sure it works).
3. Trigger the bug.
4. Try (2) again.

If this works then I suppose it's a bug in TLP *and* Gnome3. If not, it's likely an ACPI issue.

**Comment by DamienCassou** [comment]
With no battery detected:

```
$ ls /sys/class/power_supply/
ADP1
```

With battery detected:

```
$ ls /sys/class/power_supply/
ADP1  BAT0
$ ls /sys/class/power_supply/BAT0/
alarm        charge_full_design  current_now  manufacturer  present    technology  uevent
capacity     charge_now          cycle_count  model_name    status     temp        voltage_min_design
charge_full  current_avg         device       power         subsystem  type        voltage_now
```

Nothing called `energy_now` here.

I never experienced the bug before I installed tlp a few hours ago.

**Comment by abbradar** [comment]
Hmm, do you have a ThinkPad? `tlp` supports advanced operations on ThinkPad's battery, maybe it's breaking something.

Also please share your `dmesg` on good and bad boots.

Meanwhile, have you noticed any patterns which trigger the bug (aside from a reboot and some random factor)?

**Comment by DamienCassou** [comment]
I can't reproduce anymore. Should I close the issue?

**Comment by abbradar** [comment]
Yes, let's do this. Please reopen if problem shows itself again.
