### ISSUE TITLE
biber isn't packaged in texlive (-new)

### ISSUE THREAD

**Issue by YPares** [NixOS/nixpkgs#10926]
When running
`nix-shell -p 'texlive.combine {inherit (texlive) biber scheme-small; }' --pure`
the `biber` executable cannot be found.

I'm using `nixpkgs-16.03pre71332.f490186`

**Comment by vcunat** [comment]
Yes, that's a known bug, i.e. it hasn't been packaged properly yet as it needs special care unlike most texlive.

**Comment by devhell** [comment]
Damn. Back to texliveFull. :/

**Comment by vcunat** [comment]
Someone around here claimed the biber executable from the old packaging can be used along with the newly packaged TeX stuff.

**Comment by nbp** [comment]
@vcunat Do we know who is going to fix this issue, and when?

**Comment by vcunat** [comment]
I know about these open TeX issues, but I don't know when they get to the top of my ToDo, and neither I do know about anyone else planning to solve them (there's the assignee slot for that).

**Comment by ashgillman** [comment]
Has anyone got a working version of Biber? I have tried multiple installation combinations (TexLive, TexLive combine, TexLive Full, with and wihtout separate Biber), using 16.03 and unstable channels, but can't get Biber and BibLaTeX to work together.

**Comment by gebner** [comment]
`nix-shell -p biber` gives a working `biber` command.  However, the `biber` and the latex `biblatex` packages need to have precisely corresponding versions, see the table here: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/documentation/biber.pdf/download

Right now we have biber 2.5 and biblatex 2.9a, which are apparently not compatible:
```
± biber hg.bcf
INFO - This is Biber 2.5
INFO - Logfile is 'hg.blg'
INFO - Reading 'hg.bcf'
Use of uninitialized value $bltxversion in concatenation (.) or string at /nix/store/vdgvbdwax4izpsf91hsf4z07flc80wlq-perl-biber-2.5/lib/perl5/site_perl/5.22.2/Biber.pm line 415.
ERROR - Error: Found biblatex control file version 3.0, expected version 3.1.
This means that your biber (2.5) and biblatex () versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
```

**Comment by vcunat** [comment]
@ttuegel (maintainer): what about updating biber then?

**Comment by gebner** [comment]
It's actually the other way around: our biber version is too new for biblatex version in texlive.  Either we upgrade biblatex, or we downgrade biber to version 1.9 (if I read the documentation correcly).

Given that these packages are that closely linked, shouldn't biber be packaged as part of texlive then?

**Comment by vcunat** [comment]
Oh, then it might be fixed by https://github.com/NixOS/nixpkgs/pull/16391.

**Comment by vcunat** [comment]
I suppose it could be integrated. I haven't done it because it's considered nontrivial: http://tug.org/texlive/build.html#biber

**Comment by gebner** [comment]
> Oh, then it might be fixed by #16391.

Yes, biber 2.5 corresponds to the biblatex 3.4 in texlive 2016.  We just need to make sure to only upgrade biber when we upgrade texlive.

**Comment by ashgillman** [comment]
Yes, it looks like Biber was updated to work with that PR
https://github.com/NixOS/nixpkgs/pull/16391#issuecomment-229350134

If anyone is having the same issue, this package override worked for me:

    biber = pkgs.biber.overrideDerivation (
      oldAttrs: rec {
        version = "2.4";
        name = "biber-${version}";
        pn = "biblatex-biber";
        src = fetchurl {
          url = "mirror://sourceforge/project/${pn}/${pn}/${version}/${pn}.tar.gz";
          sha256 = "1gccbs5vzs3fca41d9dwl6nrdljnh29yls8xzfw04hd57yrfn5w4";
        };
      }
    );

But for that to work you have to override as a downgrade from Biber 2.5 rather than an upgrade from Biber 1.9, (i.e., use the unstable channel) because 16.03 doesn't seem to have the right Perl dependencies.

**Comment by jokogr** [comment]
@vcunat: could we close this issue now that TeXLive 2016 is integrated?
