### ISSUE TITLE
Black screen when turning on a display connected via DisplayPort

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#109289]
**Describe the bug**

Turning display off and on again result in black screen if X server is active.

**To Reproduce**
1. Be sure X server is running and active
2. Turn off the display
3. Turn the display on

Note the display works as expected if you switch to a VT before turning on the display.

**Expected behavior**
Turning on the display should not result in black screen.

**Additional context**

```
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.10.5, LLVM 11.0.0)
```

The `amdgpu` driver is used.

**Metadata**

Nixpkgs used:

```json
    "nixpkgs_2": {
      "locked": {
        "lastModified": 1610219734,
        "narHash": "sha256-hCsGe2nDz+SX4uO+lj0qPVcSGZdt52R9Yk5MOYs4djw=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "257cbbcd3ab7bd96f5d24d50adc807de7c82e06d",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
```

**Comment by nagy** [comment]
I can confirm this. With the same gpu, this happened to me as well with a recent nixpkgs update.

Thanks for the workaround btw.

**Comment by aristaeus** [comment]
I can also reproduce, same GPU. I'm not sure how recent it is - I only just got my DP display and assumed it was something to do with the protocol! I can't reproduce this with VGA, DVI, HDMI etc.

**Comment by nagy** [comment]
For me, the problem has disappeared after a recent nixpkgs update and a restart. Unfortunately I cannot tell what the fix was.

**Comment by aristaeus** [comment]
Likewise, I can no longer reproduce this.

**Comment by ryuheechul** [comment]
(maybe not strictly the same issue) but just in case someone is having similar experience for the first time, in my case the fix was [just simply to delete `.config/monitors.xml*`](https://askubuntu.com/a/1450629/1666783) and reboot.
