### ISSUE TITLE
tlp: Missing x86_energy_perf_policy

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10922]
```
$ sudo tlp stat
[...]
x86_energy_perf_policy: program not installed.
```

I found some references about that on the web:

- https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/linux-tools#n84
- https://www.archlinux.org/packages/community/i686/x86_energy_perf_policy/

Usually I would package that myself for nixpkgs, but this case is a bit different because the code seems to be part of the linux kernel.

**Comment by DamienCassou** [comment]
According to [webupd8](http://www.webupd8.org/2015/02/advanced-power-management-tool-tlp-sees.html), `tlp` now requires `kernel modules msr and x86_energy_perf_policy from linux-tools`

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/265718c9854957a5f724416429a4a208e33f7726 and https://github.com/NixOS/nixpkgs/commit/23845d7084583a87ca30bb937d4c44b3c203b3af. As a side effect, `tlp-rdw` should work properly now.
