### ISSUE TITLE
Alias for major GHC version

### ISSUE THREAD

**Issue by guibou** [NixOS/nixpkgs#109256]
**Describe the bug**

Currently we can access ghc and haskell packaging using either:

- An arbitrary version (the "current" one) using either `ghc` or `haskellPackages`
- A precise version, including minor version number, using for example `ghc.compiler.ghc8103` and `haskell.packages.ghc8103`.

The problem with this approach is that:

- binary caches may only provides cached version for the "latest" minor version. for example, if `ghc8101`, `ghc8102` and `ghc8103` exists, there may only be cached version for `ghc8103`.
- user may want to depend on a specific "major" version of GHC, for example `ghc 8.10` (i.e. `ghc810x`) and update "automatically" to the latest "minor" version available.

**Expected behavior**

I propose to introduce aliases for major ghc version. for example, `ghc810x` -> `ghc8103`.

However, a "safety" mecanism must be introduced in nixpkgs in order to ensure that the alias stays in sync.

**Notify maintainers**

@peti

**Comment by roberth** [comment]
Ideally we'd have the full version number so the most recent one can be computed and thus remain correct. The current naming convention can also be derived from the full version numbers, assuming we want to preserve it.

**Comment by peti** [comment]
I am in favor of adding those aliases. Would you like to submit a pull request?

**Comment by roberth** [comment]
Here's some progress towards it. Sadly, I can't prioritize it though :( https://github.com/NixOS/nixpkgs/pull/109815

**Comment by cdepillabout** [comment]
This has been implemented.  We now have aliases like `ghc810` (for `ghc8107`), etc.
