### ISSUE TITLE
tlp says bluetooth is on

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#10921]
tlp reports that bluetooth is activated on my computer:

```
$ sudo tlp stat
[...]
+++ Wireless
bluetooth = on
```

But nixos disagrees:

```
$ sudo nixos-option hardware.bluetooth.enable
[sudo] password for cassou: 
Value:
false

Default:
false

Description:

Whether to enable support for Bluetooth.
Declared by:
  "/home/cassou/nixpkgs/nixos/modules/services/hardware/bluetooth.nix"

Defined by:
  "/home/cassou/Documents/configuration/configuration.nix"
```

Gnome3 says `"No Bluetooth adapters found"`

**Comment by abbradar** [comment]
What does `rfkill list` report?

**Comment by DamienCassou** [comment]
Agrees with tlp:

```
$ rfkill list
$ rfkill list
0: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
```

**Comment by abbradar** [comment]
Looks like you indeed have an enabled Bluetooth adapter. `config.hardware.bluetooth.enable` only enabled services required for Bluetooth to work (and for GNOME to see it), but it doesn't touch the physical adapter.

**Comment by DamienCassou** [comment]
Oh, thanks. Any idea how to deactivate bluetooth so that it does not consume battery anymore?

**Comment by abbradar** [comment]
You can just use TLP for that -- I can't remember the exact configuration though. Also you can use "systemd-rfkill@hci0" service but I can't remember how exactly, too (I suppose it should just be enabled).

**Comment by abbradar** [comment]
Let's close this as it's not a TLP bug.
