### ISSUE TITLE
PHP_INI_SCAN_DIR env variable ignored by php binary

### ISSUE THREAD

**Issue by dxops** [NixOS/nixpkgs#109383]
Since https://github.com/NixOS/nixpkgs/commit/82cd2fbbf470b0b53005737e8fd833a77cf2f38c it's not possible to use PHP_INI_SCAN_DIR variable to pass additional php configuration. That breaks https://github.com/symfony/cli https://symfony.com/doc/current/setup/symfony_server.html#overriding-php-config-options-per-project tools also.

**To Reproduce**
1 . Install php74
2. `php -i | grep scan`

```
Scan this dir for additional .ini files => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
PHP_INI_SCAN_DIR => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
$_SERVER['PHP_INI_SCAN_DIR'] => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
$_ENV['PHP_INI_SCAN_DIR'] => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
```

3. `echo 'memory_limit = -1' > /tmp/php.ini`
4. `env PHP_INI_SCAN_DIR=/tmp php -i | grep -i scan`

```
Scan this dir for additional .ini files => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
PHP_INI_SCAN_DIR => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
$_SERVER['PHP_INI_SCAN_DIR'] => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
$_ENV['PHP_INI_SCAN_DIR'] => /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib
```

**Expected behavior**
`env PHP_INI_SCAN_DIR=/tmp php -i | grep -i scan`

```
Scan this dir for additional .ini files => /tmp
PHP_INI_SCAN_DIR => /tmp
$_SERVER['PHP_INI_SCAN_DIR'] => /tmp
$_ENV['PHP_INI_SCAN_DIR'] => /tmp
```

**Notify maintainers**
@globin @etu @ma27

**Metadata**
```
 nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev
copying path '/nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.2577.808b5dd5cbb (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2577.808b5dd5cbb, nixos-legacy-20.03.3324.929768261a3, nixos-unstable-21.03pre262347.257cbbcd3ab"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by dxops** [comment]
` cat /nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/bin/php`

```
#! /nix/store/a3fc4zqaiak11jks9zd579mz5v0li8bg-bash-4.4-p23/bin/bash -e
export PHP_INI_SCAN_DIR='/nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/lib':$(PHP_INI_SCAN_DIR)
exec -a "$0" "/nix/store/1khli85mg6g0mrl66fnpy6wlm90m8qsh-php-with-extensions-7.4.12/bin/.php-wrapped"  "$@"
```

Env variable concatenation should fix it

**Comment by aanderse** [comment]
This was intentional to avoid impure state, IIRC.

The `php` expressions we have now are **very** flexible. You can create a `php` executable to include any configuration desired on the fly like so:
`nix-shell -p 'php.buildEnv { extraConfig =
 "memory_limit = -1"; }'`.

Also keep in mind you can pass configuration via `-d memory_limit=-1` to any `php` instance.

**Comment by aanderse** [comment]
By the way... are you familiar with `direnv`? Combine `nix` with `direnv` and you have a really powerful combo that accomplishes what you want and more.

**Comment by dxops** [comment]
@aanderse sure, I'm working on this kind of setup for my long running projects and I love it. Just migrated from 20.03 where we haven't soo much options.

However, for some short term scenarions (like clone, patch, test, remove) creating nix config is not an option. Most of projects maintain their own php.ini and symfony tool use them both for cli and web/fpm without any additional setup and cost.

I'm ok to use php -d / php -c php.ini, but https://symfony.com/doc/current/setup/symfony_server.html#enabling-php-fpm still ignores custom ini files on 20.09

**Comment by Ma27** [comment]
I didn't know that HP_INI_SCAN_DIR can have multiple directories, but if that's the case, prefixing it in `makeWrapper` is fine.

I mean, we also do that for many other env vars such as `PATH`, `LD_LIBRARY_PATH` etc.

**Comment by aanderse** [comment]
Yeah I think that should be fine. I would like @etu and @talyz to give a thumbs up first, just to make sure the idea is congruent in their minds.

You're still happy if we don't automatically import `/etc/php.d` though, right?

**Comment by etu** [comment]
> Most of projects maintain their own php.ini and symfony tool use them both for cli and web/fpm without any additional setup and cost.

This claim seems interesting to me, I have, probably never seen a project provide a php.ini. And I've  been working professionally with PHP for about 10 years. And from what I can recall I haven't ever seen this before. Even working with symfony components along that way. So maybe some does, but I wouldn't say that "most projects does".

> I didn't know that PHP_INI_SCAN_DIR can have multiple directories, but if that's the case, prefixing it in `makeWrapper` is fine.

I wasn't aware of this either, but from reading the documentation again: https://www.php.net/manual/en/configuration.file.php#configuration.file.scan

It's kinda clear that it allows the variable to be `:` separated as any other `PATH` like variable.

I'm fine with introducing the possibility for such impurity just for flexibility for usages such as @dxops

**Comment by dxops** [comment]
@talyz there is backported version also https://github.com/NixOS/nixpkgs/pull/125407
can we merge it too?
