### ISSUE TITLE
antBuild doesn't call the standard pre/post hooks

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#10931]
I stared at it for a while wondering my `preBuild` wasn't getting called before realizing that it was overriding `buildPhase` without calling `runHook preBuild` and friends. Doesn't seem ideal!

**Comment by nbp** [comment]
I think this would be a nice addition to `setup.sh`, but I do not see any other way to warn about it without having a mass-rebuild.

**Comment by copumpkin** [comment]
It seems like it would only need to touch `antBuild`, right? Or what am I missing?

**Comment by nbp** [comment]
I thought that setup.sh would have been a good place to add assertions for that in general.

**Comment by Profpatsch** [comment]
(triage) is that still the case?

**Comment by rasendubi** [comment]
Checked the source and that's still an issue. Opened a PR to fix that: https://github.com/NixOS/nixpkgs/pull/17241

**Comment by Profpatsch** [comment]
Very good. Will the “Fixes #bla” automatically close this issue once it is merged?

**Comment by rasendubi** [comment]
Yes, it should.
