### ISSUE TITLE
CudaText pkg: disable 'gtk3'

### ISSUE THREAD

**Issue by Alexey-T** [NixOS/nixpkgs#109361]
**Describe the bug**
CudaText pkg has support for gtk2, gtk3, qt5.
Lazarus GTK3 is NOT ready! Any big app will be broken with gtk3 (crashes, paint bugs). 

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/cudatext/default.nix#L27

**Comment by sikmir** [comment]
There is nothing to disable, as far as there is no **cudatext-gtk3** package exposed in [all-packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L22165-L221657):
```nix
  cudatext-qt = callPackage ../applications/editors/cudatext { widgetset = "qt5"; };
  cudatext-gtk = callPackage ../applications/editors/cudatext { widgetset = "gtk2"; };
  cudatext = cudatext-qt;
```
Possibility to override widgetset to gtk3 exists for those who still wants to try gtk3. But nevertheless gtk3 is not an option available from all-packages.nix.
