### ISSUE TITLE
nixos-20.09 got force push?

### ISSUE THREAD

**Issue by mohe2015** [NixOS/nixpkgs#109384]
## Issue description
Hi, I just got:
```
git fetch upstream 
remote: Enumerating objects: 1078, done.
remote: Counting objects: 100% (1078/1078), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 1547 (delta 1054), reused 1069 (delta 1051), pack-reused 469
Receiving objects: 100% (1547/1547), 1.08 MiB | 3.01 MiB/s, done.
Resolving deltas: 100% (1189/1189), completed with 327 local objects.
From github.com:NixOS/nixpkgs
   8eb0bdc1469..bede7ee08c6  haskell-updates      -> upstream/haskell-updates
   c8d8d172933..80badc893dc  master               -> upstream/master
 + aa5b9cd16b9...808b5dd5cbb nixos-20.09          -> upstream/nixos-20.09  (forced update)
   d7d6f82e869..6d06166fb72  nixos-20.09-small    -> upstream/nixos-20.09-small
   5ff4a674125..79150e05734  nixos-unstable-small -> upstream/nixos-unstable-small
   875bcac79d4..0768790e7cd  nixpkgs-20.09-darwin -> upstream/nixpkgs-20.09-darwin
   875bcac79d4..3d8fa5f7215  release-20.09        -> upstream/release-20.09
   e85084a85bd..44f5b1d3bd2  staging              -> upstream/staging
   8f2460d407f..7172fda5c71  staging-20.09        -> upstream/staging-20.09
   318e673af06..730ff71234d  staging-next         -> upstream/staging-next
```
Why is nixos-20.09 not protected from force pushes and why was there a force push?

**Comment by mohe2015** [comment]
https://github.com/NixOS/nixpkgs/compare/nixos-20.09...aa5b9cd16b91d8a24681c3888951d7c3dc612314 maybe https://github.com/NixOS/nixpkgs/commit/aa5b9cd16b91d8a24681c3888951d7c3dc612314 got removed?

**Comment by primeos** [comment]
Seems like this happened here: https://github.com/NixOS/nixpkgs/pull/107699

**Comment by domenkozar** [comment]
I've posted https://github.community/t/protect-branch-push-from-administrators/155827

**Comment by zimbatm** [comment]
One way to work around that issue would be to add a "never-pass" CI check, that never succeeds. And then add it to the branch protection:
![image](https://user-images.githubusercontent.com/3248/104816291-234f7e80-5812-11eb-9567-3cb3886c6b98.png)

**Comment by zimbatm** [comment]
^ see the mention for a proposed fix.

**Comment by mohe2015** [comment]
An additional protection may be a client-side hook to prevent direct pushes. This is of course just to avoid accidents as it would not actually protect anything. This would need manual installation though.

**Comment by edolstra** [comment]
@zimbatm Wouldn't that also prevent the channel mirroring script from pushing?

**Comment by zimbatm** [comment]
@edolstra not this PR, but the branch protection might. I think it's fine, but we need to test it. I think the best would be to sync on IRC and try it, see if it breaks anything, and quickly revert otherwise. Worst case, we still have the PR returning a broken status, but not enforced.

**Comment by mohe2015** [comment]
root causes still an issue afaik

**Comment by primeos** [comment]
I guess with #109543 merged this can be closed then. At least that check should avoid the problem caused this issue.
As for branch protection rules in general I've opened #121589 a while ago.
