### ISSUE TITLE
CudaText: micro suggestion

### ISSUE THREAD

**Issue by Alexey-T** [NixOS/nixpkgs#109435]
For this patch https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/cudatext/dont-check-update.patch

I added to CudaText the global variable which you can change to False.
to disable "Help / Check for updates".

https://github.com/Alexey-T/CudaText/commit/d21fedd9a3f608220938b6103421ebf3cdb4e0e4
@sikmir

**Comment by sikmir** [comment]
OK, I will use it with next release.
