### ISSUE TITLE
check-meta: should we explicitly state broken reason?

### ISSUE THREAD

**Issue by holymonson** [NixOS/nixpkgs#109424]
In nixpkgs we have many packages marked `broken`, usually come with a comment in code to state the reason. But it's unclear on running nix-build, we have to track in code to find that comment.

Should we make it or something like `meta.knownVulnerabilities`, a string explicitly stating the broken reason, so that user can know why immediately on evaluation?

**Comment by B4dM4n** [comment]
There is an open draft to allow specifying a descriptive error message in `meta.broken`

#109407

This feature will be very useful to improve handling of `disabled` Python packages (#48663).

**Comment by holymonson** [comment]
#109407 comes at the right time.
