### ISSUE TITLE
`nix run ...` error: unfree license, but no option to allow unfree

### ISSUE THREAD

**Issue by rubenmoor** [NixOS/nixpkgs#109421]
I run

    > sudo nix run nixpkgs.hplipWithPlugin -c sudo hp-setup

following the manual regarding printing (I have a HP printer): 

https://nixos.wiki/wiki/Printing

I get

```
error: Package ‘hplip-3.20.5’ in /nix/store/bxbqn6c5s3adpjawj8rqb5p157v3mcs0-nixos-20.09.2577.808b5dd5cbb/nixos/pkgs/misc/drivers/hplip/default.nix:237 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

I do have configured nixos to allow unfree packages in `/etc/nixos/configuration.nix`:

```
nixpkgs.config = {
  allowUnfree = true;
};

On NixOs 20.09.2577.808b5dd5cbb (Nightingale)

**Comment by petabyteboy** [comment]
I think you just posted the answer to your own question. It's in the output you are getting. It explains exactly what is going on:


a) **For nixos-rebuild** you can set
  { nixpkgs.config.allowUnfree = true; }
**in configuration.nix** to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or **any other Nix command** you can add
  { allowUnfree = true; }
to **~/.config/nixpkgs/config.nix.**

**Comment by rubenmoor** [comment]
I have set `{ nixpkgs.config.allowUnfree = true; }` without effect.

And I tried to set `{ allowUnfree = true; }` in *~/.config/nixpkgs/config.nix*, to no avail.

**Comment by petabyteboy** [comment]
`~/.config/nixpkgs/config.nix` _should_ apply for `nix run`, but just in case you can set the environment variable `NIXPKGS_ALLOW_UNFREE=1` and try again. If this works, we can maybe investigate further why `~/.config/nixpkgs/config.nix` didn't work.

**Comment by andersk** [comment]
Note that since you’re running `nix run` as root, you’ll need to put that in root’s home directory (`/root/.config/nixpkgs/config.nix`), not your own home directory.

**Comment by matthewbauer** [comment]
On Nix 2.4, you will need to pass `--impure` to allow Nix to read config / environment variables.

**Comment by colemickens** [comment]
@rubenmoor some of us re-export an unfree nixpkgs from our own flakes.

I can run it, for example, with `nix shell github:colemickens/nixcfg/c99653cda#pkgs.x86_64-linux.hplipWithPlugin -c sudo hp-setup` (note, `nix shell` since `nix run` doesn't take `--command` anymore.)
