### ISSUE TITLE
Update vapoursynth R49 -> R52

### ISSUE THREAD

**Issue by abvbv** [NixOS/nixpkgs#109574]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vapoursynth

current version: R49
desired version: R52 (bug fixes)

###### Notify maintainers

maintainers: @rnhmjoj @tadeokondrak 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by rnhmjoj** [comment]
Thank you for the reminder, I had completely forgotten about it.
