### ISSUE TITLE
Helvetica Font Source Invalid?

### ISSUE THREAD

**Issue by tbidne** [NixOS/nixpkgs#109582]
**Describe the bug**
I believe the source for the `helvetica-neue-lt-std` package might no longer be valid:

```
http://www.ephifonts.com/downloads/helvetica-neue-lt-std.zip
```

Accessing it in the browser shows a 404, and the home page -- http://www.ephifonts.com/ --  appears to just be a portal for serving sponsored links. The Wayback Machine shows that the [download page](https://web.archive.org/web/20200401000000*/ephifonts.com/downloads) has not been archived since February 2020, and [other tools](https://www.websiteplanet.com/webtools/down-or-not/?dorn=http://ephifonts.com/downloads/helvetica-neue-lt-std.zip) also get the same 404. There was a [DNS change](https://completedns.com/dns-history/?domain=ephifonts.com) in Septermber 2020, but I'm unsure if this was the cause.

Thanks!

**To Reproduce**
1. Run `nix-env -iA nixos.helvetica-neue-lt-std`.

**Expected behavior**
Installation should not hang, and the font should be installed.

**Screenshots**
```
> nix-env -iA nixos.helvetica-neue-lt-std
installing 'helvetica-neue-lt-std-2013.06.07'
these derivations will be built:
  /nix/store/7ifs05fw2nx2idc2lzmkxn5k71s8p9r4-helvetica-neue-lt-std-2013.06.07.drv
building '/nix/store/7ifs05fw2nx2idc2lzmkxn5k71s8p9r4-helvetica-neue-lt-std-2013.06.07.drv'...

trying http://www.ephifonts.com/downloads/helvetica-neue-lt-std.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:04:38 --:--:--     0
curl: (28) Failed to connect to www.ephifonts.com port 80: Connection timed out
```

**Additional context**
`aileron` appears to be an alternative to Helvetica, so I'm unsure how important this package is. But I figured this error should be documented. As far as I can tell, `helvetica-neue-lt-std` is the only package using `ephifonts`, so if this domain is indeed no longer usable then nothing else should be impacted.

**Notify maintainers**
@romildo 

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 20.09.1758.3090c650411 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- helvetica-neue-lt-std
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
> Helvetica Neue LT Std by Linotype is sold/licensed through myfonts.com. See the license on the My Fonts website for more information.

but the link is also dead: https://www.myfonts.com/fonts/adobe/helvetica-neue/

so i would ask there where the font is available and if it is freely licensed now. it was also licensed by adobe at some point

it seem to ba available from several shady websites, like https://fontsio.com/free-helvetica-font-download-helvetica-neue-lt-std/ but that's clearly illegal and shouldn't be packaged in nixpkgs

freely licensed alternatives are:

https://www.fontsquirrel.com/fonts/TeX-Gyre-Heros

https://github.com/ArtifexSoftware/urw-base35-fonts/releases (Nimbus Sans)

**Comment by gabysbrain** [comment]
Could the helvetica-neue-lt-std package be removed or at least generate a better error than a 404 when it tries to download the font? 

I ran into this error while doing a nixos-install so it took a while to find the specific package that was causing my build to fail.

**Comment by Artturin** [comment]
#136467

**Comment by tbidne** [comment]
Thank you @Artturin!
