### ISSUE TITLE
Add sphinx-autobuild

### ISSUE THREAD

**Issue by HolgerPeters** [NixOS/nixpkgs#109564]
Autobuilding of python.sphinx documentations

**Metadata**

* homepage URL: https://pypi.org/project/sphinx-autobuild/
* source URL: https://github.com/executablebooks/sphinx-autobuild
* license: mit
* platforms: generic

**Comment by abathur** [comment]
Looks like the reporter successfully added this in https://github.com/NixOS/nixpkgs/pull/109565.
