### ISSUE TITLE
Xapps for nixos

### ISSUE THREAD

**Issue by bootstrap-prime** [NixOS/nixpkgs#109578]
**Project description**
Add the linux mint generic viewer apps (xapps) like xreader, xviewer, xed, xplayer and pix to nixpkgs.

**Metadata**

* website: https://linuxmint-developer-guide.readthedocs.io/en/latest/xapps.html
* xviewer source URL: https://github.com/linuxmint/xviewer
* xreader source URL: https://github.com/linuxmint/xreader
* xed source URL: https://github.com/linuxmint/xed
* xplayer source URL: https://github.com/linuxmint/xplayer
* pix source URL: https://github.com/linuxmint/pix
* platforms: linux 
* license: gpl2

**Comment by tu-maurice** [comment]
xed has already been requested here: #108817. I'm trying to package the latest version of xed, but cinnamon.xapps is outdated, which is why I've requested an update here #109475. I believe the other xapps might require this update too.
