### ISSUE TITLE
"A stop job is running for container" on host shut down

### ISSUE THREAD

**Issue by mrobbetts** [NixOS/nixpkgs#109695]
**Describe the bug**

So, I seem to be seeing an issue that more or less exactly matches the description of #6212 on nixos today.

I have a number of containers hosting websites, and none of them are shut down gracefully when I shut the host down. I must wait for the 90-second systemd timeout, and see them forcibly shut down. The mysql database in one container doesn't seem to enjoy this.

If I shut down a container manually, via `nixos-container stop containerName`, it works flawlessly. But somehow this is not triggered when I shut down the host.

**To Reproduce**

There are details, but the meat and potatoes is that I have some containers defined in my `configuration.nix`, and then try to reboot my host with `reboot`.

**Additional context**

My containers reside on ZFS filesystems? That's all I can think of.

**Notify maintainers**

@adisbladis 
@zowoq 
@saschagrunert 

**Metadata**

```
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.19, NixOS, 21.03.git.b3616bd9640M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/nixpkgs`
```

**Comment by radhus** [comment]
I have the same issue. Note that I am very new to NixOS, so I might have missed something 😅 

This is a workaround that works for me:
```nix
  systemd.services."shutdown-containers" = {
    description = "Workaround for nixos-containers shutdown";
    enable = true;

    unitConfig = {
      DefaultDependencies = false;
      RequiresMountFor = "/";
    };
    before = [ "shutdown.target" "reboot.target" "halt.target" "final.target" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeScript "containers-shutdown" ''
        #! ${pkgs.runtimeShell} -e
        ${pkgs.nixos-container}/bin/nixos-container list | while read container; do
          ${pkgs.nixos-container}/bin/nixos-container stop $container
        done
      '';
    };
  };
```
