### ISSUE TITLE
NixOS 15.09 ISO images cannot be mounted under Mac OS

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#10970]
For some reason i cannot boot my partition with NixOS 14.12 anymore (after i have reinstalled Mac OS on another partition), so i wanted to reinstall NixOS.

I have downloaded the minimal ISO image of 15.09 and tried to create a bootable USB drive (for (U)EFI MacBook) as i had done before: by mounting the ISO image and dragging and dropping its contents to a properly formatted USB drive labelled `NIXOS_ISO`.

However, clicking on the ISO image of 15.09 (under Mac OS) failed to mount it and opened a window of DiskImageMounter with a warning: "nixos-minimal-15.09-... no mountable file system". The same operation works fine with ISO images of 14.12.

Can this be fixed? Should i maybe follow a different procedure to create a bootable NixOS USB drive?

**Comment by alexeymuranov** [comment]
I have managed to unpack the ISO image instead of mounting it, so this has solved my problem. I am not closing the issue yet because i am not sure that making the "Mac-OS-unmountable" ISO image for 15.09 was intentional.

**Comment by alexeymuranov** [comment]
I am not sure i would have time to make a pull request to update the installation documentation, but here is [my account of installing NixOS on a MacBook](http://superuser.com/a/796642/142426), in case it helps.

**Comment by Profpatsch** [comment]
(triage) do you still have a problem with this?

**Comment by alexeymuranov** [comment]
With 16.03 -- yes.

However, i succeeded to create a bootable flash drive from it with `dd` command.

**Comment by Profpatsch** [comment]
Okay, then we can close. @jagajaga

**Comment by alexeymuranov** [comment]
The same with Ubuntu image 16.04, by the way. Maybe it is ok, as long as `dd` works.

**Comment by alexeymuranov** [comment]
As long as the procedure is explained in the documentation!
