### ISSUE TITLE
HeroicGamesLauncher app request

### ISSUE THREAD

**Issue by arouzing** [NixOS/nixpkgs#109733]
**This app is a Linux GUI for the tool [Legendary](https://github.com/derrod/legendary), a Linux native alternative to the Epic Games Launcher.**
_While this is based on and uses legendary CLI it ads an easy to use GUI interface making it much more convenient for an average user._

Thank-you very much in advance to the individual that ports this to nixos!

**Gaming, Epic Games, GUI, PKGBUILD**

* homepage URL: N/A 
* source URL: [flavioislima](https://github.com/flavioislima/HeroicGamesLauncher)
* license: GNU version 3
* platforms: linux

**Comment by abhinav3967** [comment]
would love to see this

**Comment by SuperSamus** [comment]
Merged: #148470

**Comment by kira-bruneau** [comment]
Duplicates #131620
