### ISSUE TITLE
python scikitlearn: fails to build since openblas update

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#10983]
Since [openblas 2.14 -> 2.15](3d87c5f9c3104739c5c47c2d387101afba2b0089) scikitlearn [fails](http://hydra.nixos.org/build/27432158/nixlog/1/raw) with a segmentation fault. While I am not entirely sure it is due to openblas it seems the most likely cause. 

The log shows a failure with scikit-learn 0.17b1, the same occurs when using the final 0.17.0.  Upstream tests using Travis with openblas 2.14 that is provided via conda. 

Could the issue be on our side, or would this be an upstream issue? (None such issues reported there yet). 
Any ideas what is causing this? @ttuegel @datakurre

**Comment by ttuegel** [comment]
Segmentation faults with OpenBLAS are usually caused by using `openblas` instead of `openblasCompat` or vice versa. Packages that can use any BLAS implementation usually need `openblasCompat`, whereas packages that need OpenBLAS specifically usually need `openblas`. The first thing I would try is switching out the OpenBLAS build.

**Comment by FRidh** [comment]
I took master and reverted 3d87c5f9c3104739c5c47c2d387101afba2b0089 and the segmentation fault did not occur. Let's see what upstream thinks about this.

For now scikitlearn can be fixed by overriding openblas to 0.2.14.

**Comment by FRidh** [comment]
scikitlearn checks which version of openblas numpy uses, and sets the path to that one. 
If I am correct, scikitlearn should indeed also have the same version of openblas.
Using 0.2.14 just for scikitlearn therefore does not work. An openblas 0.2.14 is needed for numpy/scipy/scikitlearn.
#10928

**Comment by domenkozar** [comment]
I've built scikitlearn successfully locally so I'm not sure what's going on at hydra.

**Comment by FRidh** [comment]
Seems to segfault on Hydra again. Only with Python 2.7 though.
http://hydra.nixos.org/build/28584750

**Comment by FRidh** [comment]
scikitlearn builds again for some time so closing.

**Comment by FRidh** [comment]
Just as I had closed this issue a segfault occurred again, this time with Python 3.4
I will have a look whether using Atlas instead resolves this issue. The upcoming scipy 0.17 also fails with OpenBlas.

**Comment by FRidh** [comment]
building scikitlearn with `openblasCompat` like done with numpy and scipy does not solve the issue. However, downgrading to openblas 0.2.14 does solve the issue. Furthermore, [scipy 0.17.0rc2](#12129) also builds with openblas 0.2.14 while it doesn't with 0.2.15.

@ttuegel 
Since upstream also tests against 0.2.14 (Travis) I propose we add openblas 0.2.14 and use it for numpy/scipy/scikitlearn. Shall I just make a copy of `default.nix` named `0.2.14.nix` or add a version parameter to openblas?

Note to self: scikitlearn 0.17 is incompatible with scipy 0.17 because of deprecated function `lena()`, therefore we need to keep scipy 0.16 as we were planning already anyway.

**Comment by ttuegel** [comment]
> Shall I just make a copy of default.nix named 0.2.14.nix

This one. I don't like to add version parameters to expressions because it gets complicated if we need to add version-specific fixes later.

**Comment by FRidh** [comment]
closed with #12826
