### ISSUE TITLE
gperftools: can't be installed in mac OS (blocking mongodb)

### ISSUE THREAD

**Issue by ashkan-leo** [NixOS/nixpkgs#109903]
**Describe the bug**
I can't install mongodb in mac OS. I get the following errors when using nix shell

```
checking how clang reports undeclared, standard C functions... configure: error: in `/private/tmp/nix-build-gperftools-2.8.drv-0/gperftools-2.8':
configure: error: cannot detect from compiler exit status or warnings
See `config.log' for more details
builder for '/nix/store/31v0wys0dz9clxyvjx3lc3jrnwnl3iqh-gperftools-2.8.drv' failed with exit code 1
cannot build derivation '/nix/store/zgxzf15h0dbbp9rr04kklgaflqk6pd20-mongodb-3.4.24.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z25i9ykzh4s75l6q1dffqyvdl9nnyckk-lorri-keep-env-hack-nix-shell.drv': 1 dependencies couldn't be built
error: build of '/nix/store/z25i9ykzh4s75l6q1dffqyvdl9nnyckk-lorri-keep-env-hack-nix-shell.drv' failed
```

and the following if I do a vanilla install `nix-env -i mongodb`
```
checking how clang reports undeclared, standard C functions... configure: error: in `/private/tmp/nix-build-gperftools-2.8.drv-0/gperftools-2.8':
configure: error: cannot detect from compiler exit status or warnings
See `config.log' for more details
builder for '/nix/store/31v0wys0dz9clxyvjx3lc3jrnwnl3iqh-gperftools-2.8.drv' failed with exit code 1
cannot build derivation '/nix/store/zgxzf15h0dbbp9rr04kklgaflqk6pd20-mongodb-3.4.24.drv': 1 dependencies couldn't be built

```

**To Reproduce**
try installing mongodb by `nix-env -i mongodb` and observe the error.
**Expected behavior**
Should be able to install mongodb on mac os. 

**Screenshots**

**Additional context**

**Notify maintainers**
@kevincox @mohe2015 @timokau @dasJ @Mic92 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-20.09pre236005.2b7c0dcdaab"`
 - channels(ashkanaleali): `"darwin, home-manager, nixpkgs-21.03pre264143.7d71001b796, nixpkgs-unstable-21.03pre264143.7d71001b796"`
 - nixpkgs: `/Users/ashkanaleali/.nix-defexpr/channels/nixpkgs`

**Comment by mohe2015** [comment]
I'm not an expert but the error message seems to mean that the underlying issue is building gperftools.

**Comment by prusnak** [comment]
Yes, this is a build failure of gperftools - assigning @vcunat (maintainer)

**Comment by kevincox** [comment]
I don't use macOS, gperftools or MongoDB so I don't know why I was tagged. I'm going to unsubscribe but feel free to tag me back in if I can somehow be of assistance.

**Comment by vcunat** [comment]
It [appears](https://hydra.nixos.org/job/nixpkgs/trunk/gperftools.x86_64-darwin) to be a recent regression.  I don't have any macOS and don't know the platform well.  If you add `--keep-failed` to the nix command, perhaps that `config.log` will be helpful.

**Comment by prusnak** [comment]
`config.log` from failed build: https://gist.github.com/prusnak/ce092a278a2c4d0445f5fe4d2afdbc17

**Comment by vcunat** [comment]
Can you/someone test?  https://github.com/NixOS/nixpkgs/pull/109996

**Comment by prusnak** [comment]
@vcunat I confirm that removing `-Wno-aligned-allocation-unavailable` from `NIX_CFLAGS_COMPILE` fixes the build of `gperftools`.
