### ISSUE TITLE
nixpkgs.pwsafe fails to build (but possibly merely a dependency problem)

### ISSUE THREAD

**Issue by nxg** [NixOS/nixpkgs#109957]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls): when I search the pulls for `pwsafe`, I see [pull 73145](https://github.com/NixOS/nixpkgs/pull/73145).  It's not obvious to me why this is relevant, but see below

###### Project name
`nix search` name: nixpkgs.pwsafe

current version: 3.53.0
desired version:

###### Notify maintainers

maintainers: @c0bw3b @pjones 

This fails to build for me, crashing out on the build of `wxwidgets` (which is presumably where the link to pull 73145 comes from).  Given this is apparently a failure in a dependency, it may be that `pwsafe` will automatically start building again once this is resolved.  If that's so, then this report is redundant; in which case, apologies.  But I'll add it nonetheless in case the fix is not that automatic (I'm a bit vague about how fixes propagate around the wonderful wonderland of Nix).

    clang++ -mmacosx-version-min=10.7 -c -o htmldll_helpdata.o  -D__WXOSX_COCOA__      -DWXBUILDING      -I./src/regex  -DWXUSINGDLL -DWXMAKINGDLL_HTML -dynamic -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -D_FILE_OFFSET_BITS=64 -I/private/tmp/nix-build-wxwidgets-3.0.4.drv-0/source/lib/wx/include/osx_cocoa-unicode-3.0 -I./include -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -O2 -fno-strict-aliasing -fno-common -fvisibility=hidden -fvisibility-inlines-hidden ./src/html/helpdata.cpp
    ./src/osx/cocoa/mediactrl.mm:470:9: fatal error: 'AVFoundation/AVFoundation.h' file not found
    #import <AVFoundation/AVFoundation.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [Makefile:39594: mediadll_osx_cocoa_mediactrl.o] Error 1
    make: *** Waiting for unfinished jobs....
    builder for '/nix/store/wm81bmbkzk2ziyk5v3spdz4647n1v5vn-wxwidgets-3.0.4.drv' failed with exit code 2
    cannot build derivation '/nix/store/y5b7m6vlp8l5046sf7g41bz88w2dv9gn-pwsafe-3.53.0.drv': 1 dependencies couldn't be built
    error: build of '/nix/store/y5b7m6vlp8l5046sf7g41bz88w2dv9gn-pwsafe-3.53.0.drv' failed

This is with the unstable channel fully updated:

    $ nix-env -qa --drv-path --out-path pwsafe
    pwsafe-3.53.0  /nix/store/y5b7m6vlp8l5046sf7g41bz88w2dv9gn-pwsafe-3.53.0.drv  /nix/store/lvikq70mprd98ny90glpsh04llzs77nz-pwsafe-3.53.0

Platform: macOS 10.15.7 (Catalina).

###### Note for maintainers

Please tag this issue in your PR.

**Comment by iblech** [comment]
I just tested it on Linux, there it works just fine. Thank you for your report, and sorry that I cannot be of further assistance!
