### ISSUE TITLE
nix-build should tell about NIXPKGS_ALLOW_UNFREE when relevant

### ISSUE THREAD

**Issue by spease** [NixOS/nixpkgs#110070]
**Describe the bug**
nix-build does not describe NIXPKGS_ALLOW_UNFREE, which is the fastest way to allow unfree on a per-command basis

**To Reproduce**
```
$ nix-build -A pkgsCross.iphone64.hello
error: Package ‘Xcode.app’ in /Users/spease/Projects/nixpkgs/pkgs/os-specific/darwin/xcode/default.nix:36 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Expected behavior**
The error message should mention NIXPKGS_ALLOW_UNFREE somewhere as an option.

**Notify maintainers**

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.2.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(spease): `"darwin, nixpkgs-21.03pre262620.a67cfc0cdc1"`
 - channels(root): `"darwin, nixpkgs-21.03pre262620.a67cfc0cdc1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by tu-maurice** [comment]
Commit 4a26f177c93099e551ed5cd949a89f631da53a52 added that.

**Comment by spease** [comment]
Cool, I’ll close this then
