### ISSUE TITLE
maintainers/scripts/update-luarocks-packages uses stdenv.lib instead of lib and urls as non-strings

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#110157]
I tried adding to `maintainers/scripts/luarocks-packages.csv`, then running `maintainers/scripts/update-luarocks-packages` and noticed in the diff this still uses `stdenv.lib`, and non-string URLs. 

**To Reproduce**
1. `maintainers/scripts/update-luarocks-packages pkgs/development/lua-modules/generated-packages.nix`
2. `git diff`

**Expected behavior**
The diff shouldn't contain non-string URLs, and not use `lib` via `stdenv.lib`.

**Notify maintainers**
@thoughtpolice 
@Shados 
@teto

**Comment by teto** [comment]
luarocks-nix needs to be updated. Its current state is messy (not clear which branch to use), I will update it.
