### ISSUE TITLE
Installation of "hello" fails on Raspberry Pi

### ISSUE THREAD

**Issue by martinvahi** [NixOS/nixpkgs#11018]
After freshly compiling Nix on Raspberry Pi ([Raspbian](https://www.raspbian.org/) OS) the "hello" fails to install. The key phrase here is:

```
error: substituter ‘download-from-binary-cache.pl’ died unexpectedly
```

The details:

```
pi@raspberrypi ~ $ which nix-
nix-build             nix-daemon            nix-install-package   nix-pull              
nix-channel           nix-env               nix-instantiate       nix-push              
nix-collect-garbage   nix-generate-patches  nix-log2xml           nix-shell             
nix-copy-closure      nix-hash              nix-prefetch-url      nix-store             
pi@raspberrypi ~ $ nix-channel --add http://nixos.org/channels/nixpkgs-unstable
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_CTYPE = "en_US.UTF-8",
    LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
pi@raspberrypi ~ $ ls /nix/
var
pi@raspberrypi ~ $ ls /nix/var/
nix
pi@raspberrypi ~ $ ls /nix/var/nix/
profiles
pi@raspberrypi ~ $ ls /nix/var/nix/profiles/
per-user
pi@raspberrypi ~ $ ls /nix/var/nix/profiles/per-user/
pi
pi@raspberrypi ~ $ ls /nix/var/nix/profiles/per-user/pi/
pi@raspberrypi ~ $ nix-channel --update
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_CTYPE = "en_US.UTF-8",
    LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
downloading Nix expressions from ‘http://nixos.org/releases/nixpkgs/nixpkgs-16.03pre71923.3087ef3//nixexprs.tar.xz’...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LC_CTYPE = "en_US.UTF-8",
    LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6095k  100 6095k    0     0   897k      0  0:00:06  0:00:06 --:--:--  940k
unpacking channels...
download-using-manifests.pl: perl: warning: Setting locale failed.
download-using-manifests.pl: perl: warning: Please check that your locale settings:
download-using-manifests.pl:    LANGUAGE = (unset),
download-using-manifests.pl:    LC_ALL = (unset),
download-using-manifests.pl:    LC_CTYPE = "en_US.UTF-8",
download-using-manifests.pl:    LANG = "en_GB.UTF-8"
download-using-manifests.pl:     are supported and installed on your system.
download-using-manifests.pl: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
download-from-binary-cache.pl: perl: warning: Setting locale failed.
download-from-binary-cache.pl: perl: warning: Please check that your locale settings:
download-from-binary-cache.pl:  LANGUAGE = (unset),
download-from-binary-cache.pl:  LC_ALL = (unset),
download-from-binary-cache.pl:  LC_CTYPE = "en_US.UTF-8",
download-from-binary-cache.pl:  LANG = "en_GB.UTF-8"
download-from-binary-cache.pl:     are supported and installed on your system.
download-from-binary-cache.pl: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
created 2 symlinks in user environment
pi@raspberrypi ~ $ nice -n10 nix-env -i hello
installing ‘hello-2.10’
download-using-manifests.pl: perl: warning: Setting locale failed.
download-using-manifests.pl: perl: warning: Please check that your locale settings:
download-using-manifests.pl:    LANGUAGE = (unset),
download-using-manifests.pl:    LC_ALL = (unset),
download-using-manifests.pl:    LC_CTYPE = "en_US.UTF-8",
download-using-manifests.pl:    LANG = "en_GB.UTF-8"
download-using-manifests.pl:     are supported and installed on your system.
download-using-manifests.pl: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
download-from-binary-cache.pl: perl: warning: Setting locale failed.
download-from-binary-cache.pl: perl: warning: Please check that your locale settings:
download-from-binary-cache.pl:  LANGUAGE = (unset),
download-from-binary-cache.pl:  LC_ALL = (unset),
download-from-binary-cache.pl:  LC_CTYPE = "en_US.UTF-8",
download-from-binary-cache.pl:  LANG = "en_GB.UTF-8"
download-from-binary-cache.pl:     are supported and installed on your system.
download-from-binary-cache.pl: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
download-from-binary-cache.pl: still waiting for ‘https://cache.nixos.org/36ifik4hak3p8j7r1q5w1r13fnwazyjf.narinfo’ after 5 seconds...
error: substituter ‘download-from-binary-cache.pl’ died unexpectedly
pi@raspberrypi ~ $ nice -n10 nix-env -i hello
installing ‘hello-2.10’
download-using-manifests.pl: perl: warning: Setting locale failed.
download-using-manifests.pl: perl: warning: Please check that your locale settings:
download-using-manifests.pl:    LANGUAGE = (unset),
download-using-manifests.pl:    LC_ALL = (unset),
download-using-manifests.pl:    LC_CTYPE = "en_US.UTF-8",
download-using-manifests.pl:    LANG = "en_GB.UTF-8"
download-using-manifests.pl:     are supported and installed on your system.
download-using-manifests.pl: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
download-from-binary-cache.pl: perl: warning: Setting locale failed.
download-from-binary-cache.pl: perl: warning: Please check that your locale settings:
download-from-binary-cache.pl:  LANGUAGE = (unset),
download-from-binary-cache.pl:  LC_ALL = (unset),
download-from-binary-cache.pl:  LC_CTYPE = "en_US.UTF-8",
download-from-binary-cache.pl:  LANG = "en_GB.UTF-8"
download-from-binary-cache.pl:     are supported and installed on your system.
download-from-binary-cache.pl: perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
error: substituter ‘download-from-binary-cache.pl’ died unexpectedly
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux
pi@raspberrypi ~ $ date
Sat Nov 14 11:29:42 UTC 2015
pi@raspberrypi ~ $ nix-env -v
error: no operation specified
Try ‘nix-env --help’ for more information.
pi@raspberrypi ~ $ nix-env --version
nix-env (Nix) 1.10
pi@raspberrypi ~ $ echo $CFLAGS 
-mtune=native -ftree-vectorize
pi@raspberrypi ~ $ echo $PATH
/home/pi/inst/nix/bin:/home/pi/.nix-profile/bin:/opt/mmmv/ruby/v_x_x_x_in_use/bin::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
pi@raspberrypi ~ $ df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        7572648 7011884    156336  98% /
devtmpfs          218252       0    218252   0% /dev
tmpfs             222520       0    222520   0% /dev/shm
tmpfs             222520    4616    217904   3% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs             222520       0    222520   0% /sys/fs/cgroup
tmpfs              51200       8     51192   1% /tmp
/dev/mmcblk0p1     57288   20232     37056  36% /boot
tmpfs              44508       0     44508   0% /run/user/1000
/dev/sdb1       15256976  163652  14295272   2% /nix
pi@raspberrypi ~ $ which nix-env
/home/pi/inst/nix/bin/nix-env
pi@raspberrypi ~ $ whoami
pi
pi@raspberrypi ~ $
```

The environment, before compilation of the Nix, can be replicated by using 
[this 8GiB flash card image](http://technology.softf1.com/mmmv_raspbian_t1/2015/bittorrent_seeds/2015_11_14_8GiB_flashcard_image_of_mmmv_raspbian_t1.img.bz2). An external storage device has to be mounted to /nix and the original source resides at 

```
/home/pi/mmmv_raspbian_t1/src
```

The lines to use in Nix src folder: 

```
 rm -fr /home/pi/inst/nix/*
./configure --prefix=/home/pi/inst/nix
```

The 

```
/nix
```

was owned by user "pi" and had permissions 0755

**Comment by cleverca22** [comment]
nix-env -i will consume ~300mb of ram, and that causes an OOM on my pi's

the solution is to always use -iA and the full attribute path

**Comment by martinvahi** [comment]
Thank You for Your answer, but I'm new to the Nix package system and I do not know, what does the expression "full attribute path" mean. Could You please give a command line example that installs the "hello" by using the "full attribute path"?

Here's my current experience:

    pi@raspberrypi ~/.nix-profile/channels/nixpkgs $ nice -n10 nix-env -iA pkgs.hello
    error: attribute ‘pkgs’ in selection path ‘pkgs.hello’ not found
    pi@raspberrypi ~/.nix-profile/channels/nixpkgs $ nice -n10 nix-env -iA nixpkgs.hello
    error: ‘/nix/var/nix/profiles/per-user/pi’ is not a symlink
    pi@raspberrypi ~/.nix-profile/channels/nixpkgs $ nice -n10 nix-env -iA nixpkgs.pkgs.applications.misc.hello
    error: attribute ‘applications’ in selection path ‘nixpkgs.pkgs.applications.misc.hello’ not found
    pi@raspberrypi ~/.nix-profile/channels/nixpkgs $ nice -n10 nix-env -iA nixpkgs.applications.misc.hello
    error: attribute ‘applications’ in selection path ‘nixpkgs.applications.misc.hello’ not found
    pi@raspberrypi ~/.nix-profile/channels/nixpkgs $ nice -n10 nix-env -iA applications.misc.hello
    error: attribute ‘applications’ in selection path ‘applications.misc.hello’ not found
    pi@raspberrypi ~/.nix-profile/channels/nixpkgs $

**Comment by cleverca22** [comment]
```nix-env -iA nixpkgs.hello``` is the correct command, you appear to have something else wrong with your nix profile
what does ```ls -lha /nix/var/nix/profiles/per-user/``` return?

**Comment by martinvahi** [comment]
Thank You for Your anser.  :-) My "results":

    pi@raspberrypi / $ nice -n10 nix-env -iA nixpkgs.hello
    error: ‘/nix/var/nix/profiles/per-user/pi’ is not a symlink
    pi@raspberrypi / $ ls -lha /nix/var/nix/profiles/per-user/
    total 12K
    drwxr-xr-x 3 pi pi 4.0K Nov 18 21:50 .
    drwxr-xr-x 3 pi pi 4.0K Nov 18 21:50 ..
    drwxr-xr-x 2 pi pi 4.0K Nov 19 08:07 pi
    pi@raspberrypi / $ date
    Thu Nov 19 08:08:37 UTC 2015
    pi@raspberrypi / $ uname -a
    Linux raspberrypi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux
    pi@raspberrypi / $ which nix-env 
    /home/pi/inst/nix/bin/nix-env
    pi@raspberrypi / $ nix-env --version
    nix-env (Nix) 1.10
    pi@raspberrypi / $

**Comment by cleverca22** [comment]
/nix/var/nix/profiles/per-user/pi must be a symlink, not a directory, you've done something wrong during your install, try moving that out of the way and then re-run nix-env

**Comment by martinvahi** [comment]
No luck with that either. 

    pi@raspberrypi / $ rm -fr /nix/var/nix/profiles/per-user/pi
    pi@raspberrypi / $ nix-env --version
    nix-env (Nix) 1.10
    pi@raspberrypi / $ ls -lha /nix/var/nix/profiles/per-user/
    total 8.0K
    drwxr-xr-x 2 pi pi 4.0K Nov 19 09:49 .
    drwxr-xr-x 3 pi pi 4.0K Nov 18 21:50 ..
    pi@raspberrypi / $ nice -n10 nix-env -iA nixpkgs.hello
    error: attribute ‘nixpkgs’ in selection path ‘nixpkgs.hello’ not found
    pi@raspberrypi / $

**Comment by cleverca22** [comment]
your nix channel was in there, so you need to re-add it with ```nix-channel --add https://nixos.org/channels/nixpkgs-unstable```

**Comment by martinvahi** [comment]
Well, thank You again, but it seems that that does not save the day either. :-/ 

Quite a mystery. Should it be of any help, I mention that I'm using the oldr Raspberry Pi that has 512MiB RAM and a single core. The /nix is actually a 16GiB USB disk, mounted to the /nix, and to save the flash card from tear and wear, the /tmp is a RAM-fs and the swap aprtition is switched off, again, to save the flash card from wearing. The /tmp is a 50MiB, RAM based, partition.

    pi@raspberrypi / $ nix-channel --add https://nixos.org/channels/nixpkgs-unstable
    perl: warning: Setting locale failed.
    perl: warning: Please check that your locale settings:
    	LANGUAGE = (unset),
    	LC_ALL = (unset),
    	LC_CTYPE = "en_US.UTF-8",
    	LANG = "en_GB.UTF-8"
        are supported and installed on your system.
    perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
    pi@raspberrypi / $ nice -n10 nix-env -iA nixpkgs.hello
    error: attribute ‘nixpkgs’ in selection path ‘nixpkgs.hello’ not found
    pi@raspberrypi / $ df
    Filesystem     1K-blocks    Used Available Use% Mounted on
    /dev/root        7572648 7060780    107440  99% /
    devtmpfs          218252       0    218252   0% /dev
    tmpfs             222520       0    222520   0% /dev/shm
    tmpfs             222520    8712    213808   4% /run
    tmpfs               5120       4      5116   1% /run/lock
    tmpfs             222520       0    222520   0% /sys/fs/cgroup
    tmpfs              51200       8     51192   1% /tmp
    /dev/mmcblk0p1     57288   20232     37056  36% /boot
    tmpfs              44508       0     44508   0% /run/user/1000
    /dev/sda1       15256976  160332  14298592   2% /nix
    pi@raspberrypi / $

**Comment by martinvahi** [comment]
I assembled a [test case](http://temporary.softf1.com/2015/2015_11_19_NixOS_nixpkgs_flsaw_11018_test_case_1.img.bz2) (~2.5GiB). The 2.5GiB bz2 is actually ~8GiB after unpacking. It is a flash card image for ~8GiB size flash card. It's a raspbian distro with plain administration based customizations. 

    user: pi
    password: raspberry

Further instructions reside at the 

    /home/pi/<you'll figure it out>

The raspberry Pi was the single core based version that has about 512MiB of RAM. In addition to the ~8GiB (OK to be bigger than that) flash card and the Raspberry Pi, some USB-storage is needed.

**Comment by cleverca22** [comment]
```The /nix is actually a 16GiB USB stick, mounted to the /nix, ```

which filesystem is it formatted with?

**Comment by martinvahi** [comment]
ext4, default parameters

**Comment by cleverca22** [comment]
somethings very wrong, it should have been making symlinks not directories in per-user

**Comment by martinvahi** [comment]
The snapshot of the Nix package manager src that I used on both cases is part of the test case flash-card image:

    /home/pi/mmmv_raspbian_t1/src/2015_11_xx_Nix_package_system.tar.bz2

I forgot to post the sha256 of the image, but it is 

    c16eee6aca6a01c1e7cffa6de211428789aeebe1905903733cf6b403a6234c84

**Comment by Profpatsch** [comment]
(triage) is this still a problem?

**Comment by mogorman** [comment]
@Profpatsch no response in 2 years i think we can close

**Comment by martinvahi** [comment]
Thank You for not forgetting this bug report. 
Honestly, thank You, but I have came to a conclusion that absolutely
ALL current package COLLECTIONS, not necessarily packaging systems,
are flawed, because in reality a binary should have a unique version
that changes whenever at least one of the following things changes:

- compiler version
- compiler "make"(GCC vs LLVM vs the abandoned Borland C++ vs whatever other compiler)
- operating system (Linux vs BSD vs MINIX vs ...)
- CPU (ARM_version_something vs i386 vs i486 vs Pentium_1 vs Pentium_2 vs ... RISCV_someversion)
- hardware (x86 vs Raspberry Pi 1, vs Raspberry Pi 2 vs R.Pi3 vs ...)
- any of the compiler flags
- version of any of the dependencies
- the set of dependencies

Alternative is some truly rigorous set of tests, but that is not the reality right now and 
I do not see, how any packaging system can even enforce it, because it's the job
of a package maintainer to create the tests and I do not see, how it would be
socially possible. 

Also, from privacy and censorship point of view the assumption that 
there is always some package distribution server available online
DOES NOT HOLD. The current packaging systems, as far as I know,
all use some central servers, which can be CENSORED CENTRALLY.

So, thank You, but I'm actually trying to build my own set of packages
that use my own "standards". I do not see, how anybody can help me with that.

Thank You for reading my comment and 
thank You for trying to help me  :-)

**Comment by bjornfor** [comment]
> [...] in reality a binary should have a unique version
that changes whenever at least one of the following things changes:

What you're describing sounds like Nix to me. What is missing?

**Comment by Profpatsch** [comment]
I’m closing this, feel free to continue the discussion anyway. :)
