### ISSUE TITLE
libvirt default network is broken

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#110142]
**Describe the bug**
Libvirt usually handles virtual network devices, interfaces, bridges and also the DHCP range. This seems to be broken.

**To Reproduce**
1. Start a VM connected to the default network
2. Don't get an IP

**Expected behavior**
DHCP is working

**Screenshots**

**Notify maintainers**
@fpletz 
@grahamc
@offlinehacker 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.6-zen1, NixOS, 21.03pre263901.68398d2dd50 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre263901.68398d2dd50"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  libvirt
```

**Comment by mohe2015** [comment]
@d4g Likely fixed by https://github.com/NixOS/nixpkgs/pull/109722

**Comment by d4g** [comment]
Thanks @mohe2015 - looks right. I will try to use the overlay first.

**Comment by tfmoraes** [comment]
I think it's related... When I try to start a VM using Gnome-boxes or Virtual-manager with VM using bridge this error happens:

```
Erro ao iniciar o dominio: internal error: /run/wrappers/bin/qemu-bridge-helper --br=virbr0 --fd=33: failed to communicate with bridge helper: Transport endpoint is not connected
stderr=failed to parse default acl file `/nix/store/2h7s274cwhw708giflvr1p3329ypm3vr-qemu-5.2.0/libexec/../etc/qemu/bridge.conf'


Traceback (most recent call last):
  File "/nix/store/dhn1d3f5pwgqzzkjzl6miyfz09hcr5pb-virt-manager-3.1.0/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/nix/store/dhn1d3f5pwgqzzkjzl6miyfz09hcr5pb-virt-manager-3.1.0/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "/nix/store/dhn1d3f5pwgqzzkjzl6miyfz09hcr5pb-virt-manager-3.1.0/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/nix/store/dhn1d3f5pwgqzzkjzl6miyfz09hcr5pb-virt-manager-3.1.0/share/virt-manager/virtManager/object/domain.py", line 1330, in startup
    self._backend.create()
  File "/nix/store/c2k97p6l7w3ga58slpzlc84ca9djl2df-python3.8-libvirt-6.8.0/lib/python3.8/site-packages/libvirt.py", line 1334, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: /run/wrappers/bin/qemu-bridge-helper --br=virbr0 --fd=33: failed to communicate with bridge helper: Transport endpoint is not connected
stderr=failed to parse default acl file `/nix/store/2h7s274cwhw708giflvr1p3329ypm3vr-qemu-5.2.0/libexec/../etc/qemu/bridge.conf'
```

**Comment by mohe2015** [comment]
@tfmoraes have you updated to the latest nixos-unstable version? This issue itself should be fixed and you should probably create a new issue if your problem persists.

**Comment by tfmoraes** [comment]
@mohe2015 it's still happening, even with the last version.

**Comment by mohe2015** [comment]
@tfmoraes then you should probably create a new issue as I don't think it's the same issue. It may still be related so maybe reference this issue.
