### ISSUE TITLE
usbmuxd on unstable has libinput errors

### ISSUE THREAD

**Issue by Technical27** [NixOS/nixpkgs#110260]
**Describe the bug**
usbmuxd on the latest nixos-unstable doesn't detect any devices and instead prints libinput errors.
```
[20:30:28.940][3] usbmuxd v1.1.1 starting up
[20:30:28.943][3] Successfully dropped privileges to 'usbmux'
[20:30:28.943][3] Using libusb 1.0.24
[20:30:28.969][3] Initialization complete
libusb: warning [parse_config_descriptors] config length mismatch wTotalLength 39 real 30
libusb: error [parse_config_descriptors] descriptor is not a config desc (type 0x00)
```

This is the output of usbmuxd from nixos-20.09 and works as expected:
```
[20:31:32.713][3] usbmuxd v1.1.1 starting up
[20:31:32.716][3] Successfully dropped privileges to 'usbmux'
[20:31:32.746][3] Initialization complete
[20:31:32.746][3] Connecting to new device on location 0x1001e as ID 1
[20:31:32.747][3] Connected to v2.0 device 1 on location 0x1001e with serial number 00000000-0000000000000
```

**To Reproduce**
1. use usbmuxd from nixos-unstable
2. run `sudo usbmuxd --foreground --user usbmux`

**Expected behavior**
My phone should appear to utilities like `ideviceinfo`

**Notify maintainers**

@infinisil

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.7, NixOS, 21.03.20210117.68398d2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre263901.68398d2dd50"`
 - channels(aamaruvi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: usbmuxd
# a list of nixos modules affected by the problem
module: nixos/usbmuxd
```

**Comment by Infinisil** [comment]
Can you try a bisection to figure out what broke this?

**Comment by S-NA** [comment]
This seems to be libusb/libusb#825.

**Comment by Infinisil** [comment]
@S-NA Hmm, but the logs that were posted show version 1.1.1 for both before and after

**Comment by S-NA** [comment]
Correct, usbmuxd reports version 1.1.1 but the issue is not with it but with libusb. According to the first log libusb reports version 1.0.24, which according to the issue I referenced above seems to be affected.

**Comment by Infinisil** [comment]
Ahh I see, makes sense

**Comment by Technical27** [comment]
It is the libusb issue, building libusb from master solved the issue.

**Comment by Technical27** [comment]
Closing, because libusb is now built with a patch that fixes this.
