### ISSUE TITLE
Cleanup Adobe Flash Player plugin support in Nixpkgs

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#110314]
## Progress (copied from @taku0's comment below)

Related packages:

- [ ] `pkgs/applications/networking/browsers/mozilla-plugins/flashplayer/`
- [x] `pkgs/applications/networking/browsers/chromium/plugins.nix`
- [ ] `pkgs/os-specific/linux/hal-flash`
- [ ] `pkgs/applications/networking/browsers/firefox/wrapper.nix`
- [x] `pkgs/applications/networking/browsers/chromium/default.nix`
- [ ] `pkgs/development/libraries/qt-5/modules/qtwebkit.nix` (`flashplayerFix`)
- [ ] `pkgs/development/libraries/qt-4.x/4.8/default.nix` (`flashplayerFix`)

Related documents:

- [ ] `doc/using/configuration.xml`
- [ ] `nixos/doc/manual/configuration/customizing-packages.xml`

## Chromium

I haven't looked into this but the Flash support should be completely removed since Chromium 88+ (#110010):
> Flash support/ capability will be complete removed from Chromium.  It will no longer be possible to enable Flash Player with Enterprise policy in Chrome 88+.
> **Source**: https://www.chromium.org/flash-roadmap#TOC-Flash-Support-Removed-from-Chromium-Target:-Chrome-88---Jan-2021-
> **Also**: https://chromestatus.com/feature/5643527180517376

So I guess we can cleanup `pkgs/applications/networking/browsers/chromium/plugins.nix` and the related logic (`enablePepperFlash`) now?

cc @taku0

**Comment by taku0** [comment]
Related packages:

- `pkgs/applications/networking/browsers/mozilla-plugins/flashplayer/`
- `pkgs/applications/networking/browsers/chromium/plugins.nix`
- `pkgs/os-specific/linux/hal-flash`
- `pkgs/applications/networking/browsers/firefox/wrapper.nix`
- `pkgs/applications/networking/browsers/chromium/default.nix`
- `pkgs/development/libraries/qt-5/modules/qtwebkit.nix` (`flashplayerFix`)
- `pkgs/development/libraries/qt-4.x/4.8/default.nix` (`flashplayerFix`)

Related documents:

- `doc/using/configuration.xml`
- `nixos/doc/manual/configuration/customizing-packages.xml`

**Comment by primeos** [comment]
cc maintainers of affected packages (FYI):
- `firefox`: @edolstra @lovesegfault 
- `hal-flash`: @malyn
- `qt5.qtwebkit`: @abbradar @periklis
