### ISSUE TITLE
10081 packages disapeared from packages.json

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#110348]
**Describe the bug**
![Screenshot from 2021-01-21 15-43-20](https://user-images.githubusercontent.com/91113/105366254-69845380-5bff-11eb-916e-7605ec3f8b33.png)

https://repology.org/repository/nix_unstable

was something changed about the exported package list?

**Expected behavior**
same number of packages or even more

**Additional context**
we used to have the most packages, but now AUR is on top again

https://repology.org/repositories/statistics/total

**Comment by tu-maurice** [comment]
Maybe #110346 has to do with this.

**Comment by Atemu** [comment]
Might also be a redefinition of a "project" on the repology side, i.e. duplicates that weren't detected before.

Do we know the revisions of before and after? We could check whether anything went missing from packages.json in the tarball because that's the source of Repology's data.

**Comment by tu-maurice** [comment]
Well it must've happened on January 16th so we could use one commit from the 15th and 17th and see if there are suspicious changes in the that json file in between.

Using `git log --pretty=format:'%h %cD %s' --grep "Merge pull request"` we can pick a merge commit from the 15th e.g. 809dc63c16d1b0db8c0c7daf043bc9f81d19d33b and one from the 17th e.g. faed1fc0eb3104ecbe2079a3bb141a46c4e397d2

**Comment by Atemu** [comment]
We need to know the state of the unstable channel on those dates, it's days or sometimes even weeks behind master.

Don't really have time for this right now but https://channels.nix.gsc.io/nixos-unstable/history is probably what we need.

**Comment by davidak** [comment]
>Well it must've happened on January 16th

It did appear in Repology on 16. January, but our channel take some time after a commit was done. So i would check the 9. Jan. (63f533d4290).

There is 1 successful channel evaluation on 2021-01-16: https://hydra.nixos.org/build/135156379
Here is the packages.json.br build: https://hydra.nixos.org/build/135155191

`nix run nixpkgs.brotli -c brotli --decompress packages-2021-01-16.json.br`

so, how to count? some jq magic?
---

There was no relevant change in https://github.com/NixOS/nixos-homepage/commits/master/Makefile

There was a change of https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/packages-config.nix on 13. Jan. (https://github.com/NixOS/nixpkgs/commit/4003f8cbc711493f061f993971557fe8b134eeb7#diff-1ee1ff8bddabfe1a4b0f70ecc57350191d91d848d3d9f2b6bcab2dbc20a870bb).

**Comment by adisbladis** [comment]
@davidak `emacs26Packages`, `emacs27Packages` and so on were moved to their respective interpreters as `emacs26.pkgs` & `emacs27.pkgs` in https://github.com/NixOS/nixpkgs/pull/107152.

The old names now only exists as aliases which probably explains why they have disappeared from Repology.

I think this opens up a question regarding if we should remove `dontRecurseIntoAttrs` from `emacs*.pkgs`.

**Comment by davidak** [comment]
I think such tools should show packages only once, even when they exist for different interpreters like emacs26 and emacs27. But it should be obvious that you can use both.

The raw package list should still contain all i guess, so tools like repology get all nixpkgs has to offer.

But that is a big topic and it's about UX.

For example in the search. Now it looks like this:
![Screenshot from 2021-02-19 11-28-56](https://user-images.githubusercontent.com/91113/108492658-b5312800-72a5-11eb-8848-5d68c026bbdd.png)

But this would be less cluttered and more user friendly:

![Screenshot from 2021-02-19 11-37-28](https://user-images.githubusercontent.com/91113/108493716-ed853600-72a6-11eb-8dab-0e498f8675ac.png)

Same in `nix search`.

**Comment by Atemu** [comment]
The bug is probably here:

https://github.com/NixOS/nixpkgs/blob/b310f4915d350853d66cf3cec2762a25e4168647/pkgs/top-level/packages-config.nix#L37

@adisbladis did update the set names here too but I don't think sub-attributes work in that construct.

**Comment by adisbladis** [comment]
@Atemu Nice catch! I've attempted to conjure up a fix in https://github.com/NixOS/nixpkgs/pull/113680 but it needs more testing before I'm comfortable merging.

**Comment by davidak** [comment]
Status: rPackages is fixed

https://github.com/NixOS/nixpkgs/blob/c54c8f8dfa382b9ecac1dcab2838aa16f4831b72/pkgs/top-level/packages-config.nix#L28

See for example "tidytidbits" on [search.nixos.org](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=tidytidbits) or [repology](https://repology.org/projects/?search=tidytidbits&maintainer=&category=&inrepo=nix_unstable&notinrepo=&repos=&families=&repos_newest=&families_newest=).

In the package set list is also emacs27, but i don't find any packages.

https://github.com/NixOS/nixpkgs/blob/c54c8f8dfa382b9ecac1dcab2838aa16f4831b72/pkgs/top-level/packages-config.nix#L37

When i search for random packages that existed before, like "pony-mode" i don't find it now in search or repology.

https://gist.github.com/davidak/8bee60e5485259b42a21d9b7916093da/92925357cd2d5b530d19e40e909519147861c1b9#file-gistfile1-txt-L8784
https://search.nixos.org/packages?channel=20.09&from=0&size=50&sort=relevance&query=pony-mode

The name does exist in `./pkgs/applications/editors/emacs/elisp-packages/recipes-archive-melpa.json` which is not found in github search, probably because the file is too big.

On repology you find only 1 emacs package in nixpkgs!

https://repology.org/projects/?search=emacs%3A&maintainer=&category=&inrepo=nix_unstable&notinrepo=&repos=&families=&repos_newest=&families_newest=
https://repology.org/projects/?search=emacs-&maintainer=&category=&inrepo=nix_unstable&notinrepo=&repos=&families=&repos_newest=&families_newest=

https://hydra.nixos.org/build/149921732

```
[davidak@gaming:~/Downloads]$ nix run nixpkgs.brotli -c brotli --decompress packages.json.br
[davidak@gaming:~/Downloads]$ jq '.packages | keys' packages.json | grep magit
  "vimPlugins.vimagit",
  "vscode-extensions.kahole.magit",

[davidak@gaming:~/Downloads]$ jq '.packages | keys' packages.json | grep pony-mode

[davidak@gaming:~/Downloads]$ jq '.packages | keys' packages.json | grep emacs
  "emacs",
  "emacs-all-the-icons-fonts",
  "emacs-nox",
  "emacsMacport",
  "haskellPackages.emacs-keys",
  "haskellPackages.emacs-module",
  "haskellPackages.yi-emacs-colours",
  "haskellPackages.yi-keymap-emacs",
  "pinentry-emacs",
  "qemacs",

```

So the package set emacs27 is still missing from `packages.json`.
