### ISSUE TITLE
apt went "missing"

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#110346]
**Describe the bug**
Between bdce0b36b28f3750a8993316850ccaadf428a068 and 6c45ecfdbee86ed80f858717901b20b90ec31dbc, apt somehow got reintroduced into the repository ([pkgs/tools/package-management/apt](https://github.com/NixOS/nixpkgs/commit/d6aeae8f90a4935525915431e3b08ebf1b7d5bf3)) but without an entry in all-packages.nix.

- It could be bumped to 2.1.18 - Out-of-date package report
- It doesn't compile for the same reason for which it was originally removed from Nixpkgs and I don't know how to fix it - bug report
  ```
  [ 33%] Building CXX object apt-pkg/CMakeFiles/apt-pkg.dir/acquire-item.cc.o
  In file included from /nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/ext/string_conversions.h:41,
                   from /nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/bits/basic_string.h:6535,
                   from /nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/string:55,
                   from /build/source/build/include/apt-pkg/hashes.h:18,
                   from /build/source/build/include/apt-pkg/acquire.h:68,
                   from /build/source/build/include/apt-pkg/acquire-item.h:22,
                   from /build/source/apt-pkg/acquire-item.cc:17:
  /nix/store/kg2s3k77ifsyd59ac08mjmmjjmsvgsvg-gcc-10.2.0/include/c++/10.2.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
     75 | #include_next <stdlib.h>
        |               ^~~~~~~~~~
  compilation terminated.
  make[2]: *** [apt-pkg/CMakeFiles/apt-pkg.dir/build.make:82: apt-pkg/CMakeFiles/apt-pkg.dir/acquire-item.cc.o] Error 1
  ```
- I need apt for another package to work properly (apt -> python-apt -> python-debian -> click: https://github.com/NixOS/nixpkgs/pull/108366) - packaging request?

**To Reproduce**
1. [Search](https://search.nixos.org/packages?channel=unstable&query=apt) for apt package -> not packaged
2. [Search](https://github.com/NixOS/nixpkgs/search?q=apt&type=code) in Nixpkgs repo -> but package code exists?
3. Check commit/PR history -> #68029 (staging) removed all apt code, #69571 (master) bumped apt

**Expected behavior**
apt being either in all-packages.nix or missing from the repository completely. Preferably, a working apt derivation.

~~**Screenshots**~~

**Additional context**
https://github.com/NixOS/nixpkgs/pull/108366

**Notify maintainers**
@cstrahan, package maintainer for apt
@georgyo, last bump to package
@fpletz, originally removed the package

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.2642.88f00e7e12d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2642.88f00e7e12d"`
 - channels(bt1cn): `"unstable-21.03pre259928.2f47650c2f2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ apt ]
# a list of nixos modules affected by the problem
module:
```

**Comment by iblech** [comment]
FWIW, I briefly looked into this: Switching to gcc9 hides the detailed error message, but compilation still fails.

**Comment by tobim** [comment]
I looked into this a little. #113180 fixes the build, but the binary that can be produced is far from functional. `strace` reveals that apt expects several other files relative to its install location to exist.

As the package is currently defunct and unreachable, I think it is best to remove it.

**Comment by OPNA2608** [comment]
Bump, `pkgs/tools/package-management/apt/default.nix` still exists.
