### ISSUE TITLE
ZFS legacy mounting not working after recent version update (zfs: 2.0.0 -> 2.0.1)

### ISSUE THREAD

**Issue by Philipp-M** [NixOS/nixpkgs#110376]
**Describe the bug**

When booting with ZFS legacy mountpoints like this:

```nix
{
  fileSystems."/tank/media" = {
    device = "tank/media";
    fsType = "zfs";
  };
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.enableUnstable = true; # this doesn't seem to matter
}
```
the boot fails as described in this post: 
https://discourse.nixos.org/t/since-updating-zfs-recently-one-of-my-volumes-fails-to-mount-at-boot/11054

**To Reproduce**
I guess this is difficult if not anyone is having this issue with legacy mountpoints, but it seems that in the linked discourse post, I'm not the only one with this issue.

But I've tested it just on this commit: https://github.com/NixOS/nixpkgs/commit/e44a4abdbeb479a6cff041a80be9ec9e2cfa78ce
where it fails, and on this (just one commit before): https://github.com/NixOS/nixpkgs/commit/c92a996c8f82467bcdd8566981d0c71b42c74833
And there everything works.

**Expected behavior**

Mounting of legacy ZFS mountpoints succeeds while booting.

**Notify maintainers**
@hmenke @jcumming @jonringer  @wizeman @fpletz @globin @Mic92

**Comment by Mic92** [comment]
Can you check if this is fixed by https://github.com/openzfs/zfs/commit/03f036cbccdd8699f5fe8540ef317595a35bceb8 ?

**Comment by Emiller88** [comment]
@Mic92 I tried with this overlay:
```nix
self: super: {
  zfs = super.zfs.overrideAttrs (old: {
    extraPatches = (old.extraPatches or [ ]) ++ [
      (super.fetchpatch {
        url =
          "https://github.com/openzfs/zfs/commit/03f036cbccdd8699f5fe8540ef317595a35bceb8.patch";
        sha256 = "07sx98d422589gxr8wflfpkdd0k44kbagxl3b51i56ky2wfix7rc";
      })
    ];
  });
}
```
Not sure if that's the way to do it, but it didn't work.

**Comment by jonringer** [comment]
it should probably be
```
self: super: {
  zfs = super.zfs.overrideAttrs (old: {
    patches = (old.patches or [ ]) ++ [
      (super.fetchpatch {
        url =
          "https://github.com/openzfs/zfs/commit/03f036cbccdd8699f5fe8540ef317595a35bceb8.patch";
        sha256 = "07sx98d422589gxr8wflfpkdd0k44kbagxl3b51i56ky2wfix7rc";
      })
    ];
  });
}
```

**Comment by Emiller88** [comment]
Thanks I tried that, and it didn't work. Not sure how to confirm the patch got applied properly though.

**Comment by jonringer** [comment]
if you have the log output, you will have something like:
```
patchPhase
applying patches to ....
```

**Comment by bryanasdev000** [comment]
Guys, just to report, I'm in the latest zen with ZFS 2.0.1-1 with encryption, unstable channel and I'm not having any problems.

**Comment by Philipp-M** [comment]
I've just found time to test this, thanks for the research.

The patch did indeed fix the issue for me!
(I've checked the log output for the application of the patch).

For the sake of completeness the overlay I've applied (needed a slightly different sha256 sum for me):

```nix
{
  nixpkgs.overlays = [
    (self: super: {
      zfs = super.zfs.overrideAttrs (old: {
        patches = (old.patches or [ ]) ++ [
          (super.fetchpatch {
            url =
              "https://github.com/openzfs/zfs/commit/03f036cbccdd8699f5fe8540ef317595a35bceb8.patch";
            sha256 = "0b2p8ylhm5dgscjmr650gx1f3lnsvkz4hb9nlx2hllm8v50z3fl2";
          })
        ];
      });
    })
  ];
}
```

**Comment by Mic92** [comment]
> I've just found time to test this, thanks for the research.
> 
> The patch did indeed fix the issue for me!
> (I've checked the log output for the application of the patch).
> 
> For the sake of completeness the overlay I've applied (needed a slightly different sha256 sum for me):
> 
> ```nix
> {
>   nixpkgs.overlays = [
>     (self: super: {
>       zfs = super.zfs.overrideAttrs (old: {
>         patches = (old.patches or [ ]) ++ [
>           (super.fetchpatch {
>             url =
>               "https://github.com/openzfs/zfs/commit/03f036cbccdd8699f5fe8540ef317595a35bceb8.patch";
>             sha256 = "0b2p8ylhm5dgscjmr650gx1f3lnsvkz4hb9nlx2hllm8v50z3fl2";
>           })
>         ];
>       });
>     })
>   ];
> }
> ```

Could you make a PR adding the patch to zfs?
