### ISSUE TITLE
Haskell "pkg.env" attributes don't contain propagated build inputs

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#11049]
The generic builder constructs a `nix-shell` environment that contains the build inputs specified directly for `pkg`, but it does not include those dependencies that are propagated by the dependencies of `pkg`. This causes inconsistent behavior i.e. when building `taffybar`.

**Comment by Profpatsch** [comment]
(triage) does that bug still exist?

I’ve got a patch in my taffybar, and everytime it changes upstream that is lost again until I do a change in the config. Is that related?

**Comment by Profpatsch** [comment]
I’m gonna close, feel free to reopen if the bug still exists.
