### ISSUE TITLE
Systemd 227 Failing to unmount during shutdown / reboot

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#11059]
http://i.imgur.com/0oHBSgT.jpg

This was never an issue when running on 217.

**Comment by edolstra** [comment]
Does it hang or just fail to unmount?

**Comment by wkennington** [comment]
It hangs but eventually reboots / powers off. I think there is some timeout
of 1 minute 30 seconds or 3 minutes. This doesn't happen every shutdown,
but happens frequently enough to be annoying. There is an upstream bug that
seemed somewhat similar, ill track it down.

**Comment by wkennington** [comment]
https://github.com/systemd/systemd/issues/867

**Comment by domenkozar** [comment]
Can you try applying https://github.com/systemd/systemd/pull/1516

**Comment by devhell** [comment]
Any news about this?

**Comment by wkennington** [comment]
It still fails on 228

**Comment by domenkozar** [comment]
@wkennington 227 or 228?

**Comment by wkennington** [comment]
Both

**Comment by grahamc** [comment]
I'm seeing this error as well, periodically, on 16.03.

**Comment by c0bw3b** [comment]
(triage) Was this observed again in 17.03 and 17.09? It's probably resolved since 232 or 234

**Comment by domenkozar** [comment]
Seems dead to me since a year. If someone has seen it on 17.XX, please reopen.
