### ISSUE TITLE
Support for F2FS compression in kernel is missing

### ISSUE THREAD

**Issue by tommy4st** [NixOS/nixpkgs#110534]
**Describe the bug**
Even so the f2fs-tools support enabling compression, the kernel doesn't right now. 

**To Reproduce**
1. Create a f2fs filesystem with `mkfs.f2fs -O extra_attr,compression /dev/sda1`
2. Mount it: `mount -o compress_algorithm=lz4 /dev/sda1 /mnt`
3. Enable compression for all files and folders there: `chattr -R +c /mnt`
4. Create new file: `touch /mnt/wontwork`
5. Try to read it: `cat /mnt/wontwork`
6. Result: "Operation not supported"

**Expected behavior**
The file should be readable.

**Additional context**
ArchLinux and Debian both use the following kernel config:
```
CONFIG_F2FS_FS=m
CONFIG_F2FS_STAT_FS=y
CONFIG_F2FS_FS_XATTR=y
CONFIG_F2FS_FS_POSIX_ACL=y
CONFIG_F2FS_FS_SECURITY=y
CONFIG_F2FS_FS_COMPRESSION=y
CONFIG_F2FS_FS_LZO=y
CONFIG_F2FS_FS_LZ4=y
CONFIG_F2FS_FS_ZSTD=y
CONFIG_F2FS_FS_LZORLE=y
```
F2FS compression is available since 5.6.

**Notify maintainers**
@Atemu ?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.6-zen1, NixOS, 21.03pre265130.f217c0ea7c1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre265130.f217c0ea7c1, home-manager, nixos-hardware, nixpkgs-21.03pre264882.92c884dfd71"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Atemu** [comment]
Not -zen specific, we don't enable it in any Linux build for some reason. Makes me wonder what other cool features we're missing because we're simply not enabling them.

The compressor-specific options are on by default, so we should only need to enable `F2FS_FS_COMPRESSION`:

https://github.com/NixOS/nixpkgs/pull/110542
