### ISSUE TITLE
Wireguard client unstoppable?

### ISSUE THREAD

**Issue by Abdillah** [NixOS/nixpkgs#110559]
**Describe the bug**
Both `networking.wireguard.interfaces` and `networking.wg-quick.interfaces` create SystemD unit service that started on boot (CMIIW) and once started, we should do some step in order to stop it: move the private key file and stop the system, or... just rebuild switch. The autostart property due to multi-user target also cannot be disabled (`systemctl disable wireguard-wg0` failed).

This is far from user friendly.

**To Reproduce**
1. Follow wireguard client creation on [nixos.wiki](https://nixos.wiki/wiki/Wireguard), use the privateKeyFile instead of directly type the key.
2. Disable unit `sudo systemctl disable wireguard-wg0`.
3. Stop unit `sudo systemctl stop wireguard-wg0`.
4. Check unit status `sudo systemctl status wireguard-wg0`.

**Expected behavior**
Unit will be disabled on step 2, and stopped on step 3.

**Screenshots**
![Screenshot from 2021-01-23 08-34-13](https://user-images.githubusercontent.com/3030950/105564797-546e0880-5d56-11eb-84d2-07d4b00b9df5.png)
![Screenshot from 2021-01-23 08-34-39](https://user-images.githubusercontent.com/3030950/105564798-559f3580-5d56-11eb-993b-1afb32acb0bd.png)

**Additional context**
I may missed something due to limited info on this matter.

**Notify maintainers**
@ericsagnes @grahamc 

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"                                                            5.6s  Sat 01:41
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.80, NixOS, 20.09.2122.2fbcd0b9df9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201118_79aa7d9`
 - channels(fazbdillah): `"nixos-19.09.1778.db3e8325a9b"`
 - channels(root): `"nixpkgs-unstable-21.03pre259711.be0b453d7c7, nixos-20.09.2122.2fbcd0b9df9, nixos-20.09-20.09.2122.2fbcd0b9df9, nixpkgs-20.09.2122.2fbcd0b9df9, nixpkgs-19.09-19.09.2522.75f4ba05c63, nixpkgs-20.03-20.03.3316.0f8a31b992b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by Abdillah** [comment]
Turns out the `wg-quick` is the way to go. It is stopable and properly setup connection and route.

**Comment by cole-h** [comment]
FYI, in case anybody comes across this: you need to stop the `.path` unit: `# systemctl stop wireguard-wg0.path` (as implied by the message "Warning: Stopping wireguard-wg1.service, but it can still be activated by: wireguard-wg1.path").

**Comment by Abdillah** [comment]
@cole-h Is there a way to prevent autostart on wg-quick? I unsuccessfully tried in removing `wantedBy` from the service.
To imagine, I have a VPN that used only for company work only, the current service is auto-start at boot and that really an inconvenient. I will file a bug report and maybe a PR about option to remove "multi-user.target" from `wantedBy` if that a valid point.

**Comment by cole-h** [comment]
`systemd.services."wireguard-wg0".wantedBy = lib.mkForce [ ];` should work. (Replace `wg0` with your interface name.)
