### ISSUE TITLE
The matomo web-analytics service has a constrained url for archiving requests

### ISSUE THREAD

**Issue by JosephLucas** [NixOS/nixpkgs#110547]
The mamoto service is a self-hosted and open source alternative to google analytics.
I managed to make the [matomo service](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/matomo.nix) almost work except for a constrained url in the nix module.  

**Expected behavior**
When archiving requests. I would expect the matomo service to allow me to configure the url of the service, for instance
```
matomo-console core:archive --url=https://matomo.mywebsite.com
```
intsead I am constrained to this
```
matomo-console core:archive --url=https://${user}.${fqdn}"
``` 
and `fqdn` is grosso modo `config.networking.hostName+config.networking.domain` IIUC.

**Additional context**
I know that the default config using NGINX should make the choice of the url for me, but I want to use the caddy server, since it is already running on the machine. There is an option in the matomo module anyway and the url of the service is free so the functioning is misleading right now.

Here is my config 
```
services.matomo = {
    enable = true;
    webServerUser = "caddy";
};
```
and the caddy config
```
"https://matomo.pambda.com" {
  root * ${pkgs.matomo}/share
  php_fastcgi / unix/${fpm.socket}
  php_fastcgi /index.php  unix/${fpm.socket}
  php_fastcgi /matomo.php unix/${fpm.socket}
  php_fastcgi /piwik.php  unix/${fpm.socket}
  file_server
}'';
```
with `fpm = config.services.phpfpm.pools.matomo`

The package of matomo is a bit outdated, but [matomo4nix](https://git.helsinki.tools/helsinki-systems/matomo4nix) has recent updates.

**Suggestion**

Maybe we could add an option in the module that would set the url used when archiving.

**Comment by exarkun** [comment]
This problem also affects me.

Also, I don't even understand how it makes sense to prefix a "user" component on the hostname.  If `networking.hostName` is "matomo" and `networking.domain` is "example.com" then the Matomo service computes a URL of `https://matomo.matomo.example.com` which is just wrong.

I'm not trying to use caddy. I just have a straightforward Matomo / nginx configuration - but it seems broken out of the box to me.

I'm currently working around this using this line in my configuration:

```
systemd.services.matomo-archive-processing.serviceConfig.ExecStart = pkgs.lib.mkForce "${config.services.matomo.package}/bin/matomo-console core:archive --url=https://mydomainname";
```

**Comment by ThibautMarty** [comment]
Agreed.
When using nginx, this should probably be:
```nix
ExecStart = "${cfg.package}/bin/matomo-console core:archive --url=https://${cfg.nginx.serverName}";
```
with maybe some logic for http/https.

cc @florianjacob
