### ISSUE TITLE
kdeApplications attribute is not defined

### ISSUE THREAD

**Issue by alapshin** [NixOS/nixpkgs#110617]
**Describe the bug**
When building system with configuration that installs KDE applications using `kdeApplications.<appname>` build fails with
```
error: --- UndefinedVarError ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
at: (17:5) in file: /nix/store/k8arnxqi994qk5klsvyrkhvflmg82mkf-source/users/alapshin/apps.nix

    16|     libreoffice-fresh
    17|     kdeApplications.ark
      |     ^
    18|     dolphin

undefined variable 'kdeApplications'
(use '--show-trace' to show detailed location information)
```

But if same application is specified without using `kdeApplication` prefix then build succeeds, however not every application is available directly from top-level scope. 

**Expected behavior**
Applications should be available via kdeApplications scope 

**Additional context**
It was working fine with nixpkgs at revision at `b3616bd96400ce0252c241d76fcafb64389defc6`. 
If there is some way to bisect nixpkgs revisions when they are specified in `flake.lock` I would appreciate it. Then I can try to find commit that broke this using bisect.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.9, NixOS, 21.03.20210122.b60a6af (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre259923.c958c1b6b2f"`
 - channels(alapshin): `""`
 - nixpkgs: `/nix/store/d8rbyy2cprgx9v8iyjrak1hznpjjaqdq-source`
```

**Comment by alapshin** [comment]
I was able to pinpoint this issue to commit b209617ff0a8f26ea1d1fe3716a7fa717a50dd95
There new set `plasma5Packages` is introduced. Using this set applications can be installed as `plasma5Packages.ark` instead of `kdeApplications.ark`.

@FRidh Could you confirm if this is expected behavior or not?

**Comment by anund** [comment]
It's also possible there's a scoping mistake. `plasma5Packages.kdeApplications.ark` will also work.

**Comment by FRidh** [comment]
Moving `kdeApplications` was on purpose. I am not sure whether we should keep the subset `kdeApplications`, because it may be harder to override.

`plasma5Packages` is an alias to the `libsForQt5` used to build the Plasma desktop.

**Comment by FRidh** [comment]
There is still the task to link individual applications from top-level.

**Comment by worldofpeace** [comment]
Believe we also need to update Qt docs for nixpkgs?
