### ISSUE TITLE
tree-sitter 0.18.0 is out

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#110662]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.17.3
desired version: 0.18.0

###### Notify maintainers

maintainers: @Profpatsch 

I am not sure exactly what rev I bumped to, but some newer rev fixes compilation on aarch64, so whenever we bump it up, we can probably unmark it as broken.

**Comment by Profpatsch** [comment]
@colemickens should be easy enough to bump if you want to take a shot.
