### ISSUE TITLE
Fishnet

### ISSUE THREAD

**Issue by lxea** [NixOS/nixpkgs#110678]
**Project description**
"Distributed Stockfish analysis for lichess.org

**Metadata**

* homepage URL: lichess.org
* source URL: https://github.com/niklasf/fishnet
* license: gpl3
* platforms: linux, darwin, windows

I made an attempt to package it below, however it depends on its own version of stockfish which when it tries to execute it it gets a `file not found error` when trying to load `libstdc++.so.6` so I'm not sure how to resolve that. 
ldd output: 

```
$ ldd /tmp/fishnet-aNOtb9/stockfish-x86-64-avx2 
        linux-vdso.so.1 (0x00007fff65c69000)
        libpthread.so.0 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libpthread.so.0 (0x00007f1928eaf000)
        libstdc++.so.6 => not found
        libm.so.6 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libm.so.6 (0x00007f1928d6e000)
        libgcc_s.so.1 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libgcc_s.so.1 (0x00007f1928d54000)
        libc.so.6 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib/libc.so.6 (0x00007f1928b95000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f1928ed2000)
```

```
{ lib, stdenv, rustPlatform, fetchgit }:

rustPlatform.buildRustPackage rec {
  pname = "fishnet";
  version = "2.2.2";

  src = fetchgit {
    url = "https://github.com/niklasf/${pname}";
    rev = "v${version}";
    deepClone = true;
    sha256 = "1w94vdgkhmzpjbrjhg5x8mwlr91j9pq4ww119b9alzx4yd4fwcjc";
  };

  cargoSha256 = "03r25ms3xysdh1ydb8x5c6va7xd3phkykym1kr9sa1vc8l6qvk48";

  meta = with lib; {
    description = "Distributed Stockfish analysis for lichess.org";
    homepage = "https://github.com/niklasf/fishnet";
    license = licenses.gpl3;
   };
}
```

**Comment by tu-maurice** [comment]
Builds and starts for me on unstable. Though I had to replace your src.sha256 with `1i029dhv3swdyjgrcqp5hjx1jdhh99228qsm304gk1b83ciqz4zh`.

Are you sure your downloaded sources were correct?

If I run it, it prints
```
#   _________         .    .
#  (..       \_    ,  |\  /|
#   \       O  \  /|  \ \/ /
#    \______    \/ |   \  /      _____ _     _     _   _      _
#       vvvv\    \ |   /  |     |  ___(_)___| |__ | \ | | ___| |_
#       \^^^^  ==   \_/   |     | |_  | / __| '_ \|  \| |/ _ \ __|
#        `\_   ===    \.  |     |  _| | \__ \ | | | |\  |  __/ |_
#        / /\_   \ /      |     |_|   |_|___/_| |_|_| \_|\___|\__| 2.2.2
#        |/   \_  \|      /
#               \________/      Distributed Stockfish analysis for lichess.org

### Configuration

Personal fishnet key (append ! to force, https://lichess.org/get-fishnet):
```

ldd says:
```
	linux-vdso.so.1 (0x00007ffc11baf000)
	libgcc_s.so.1 => /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libgcc_s.so.1 (0x00007f484bc9f000)
	libpthread.so.0 => /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libpthread.so.0 (0x00007f484bc7e000)
	libm.so.6 => /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libm.so.6 (0x00007f484bb3b000)
	libdl.so.2 => /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libdl.so.2 (0x00007f484bb36000)
	libc.so.6 => /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libc.so.6 (0x00007f484b975000)
	/nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/ld-linux-x86-64.so.2 => /nix/store/33idnvrkvfgd5lsx2pwgwwi955adl6sk-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f484cfc7000)
```

**Comment by lxea** [comment]
This config was working for me as far as showing fishnet logo etc, however the stockfish that it extracts to /tmp were giving me issues, you need to provide your user key for it to get that far though.

I think the binaries in assets/ need to be unzipped and have their contents patched with so they can find C++ libs, and im not sure that will lead to particularly reproducible builds which is less than ideal

if you git clone --recursive $fishnet_repo and unxz/ldd one of the assets binaries it might be more easy to test if you dont have a lichess key

**Comment by tu-maurice** [comment]
Ah. My bad. I should've read it more thoroughly.

**Comment by tu-maurice** [comment]
Sorry for the delay. Got myself a lichess key. And got fishnet to work. Though the derivation is rather ugly. The assets have to be modified before fishnet is built as they embed the assets into the rust binary. My plan to improve the derivation is to make a separate derivation for the patched assets which then used as a build time dependency for fishnet. Stay tuned.

Here: [tu-maurice/nixpkgs@unstable/fishnet-2.2.2](https://github.com/tu-maurice/nixpkgs/tree/unstable/fishnet-2.2.2)

**Comment by lxea** [comment]
No worries! I appreciate you taking the time to look into it! Thanks!

**Comment by tu-maurice** [comment]
Cleaned it up a little and am using v2.2.3 now: [tu-maurice/nixpkgs@unstable/fishnet-2.2.3](https://github.com/tu-maurice/nixpkgs/tree/unstable/fishnet-2.2.3)

I'll make a PR. Maybe the Gurus of NixOS have some more ideas for improvements.

**Comment by tu-maurice** [comment]
Okay. It's been merged however a corresponding service module is missing. I've done some preliminary work on that however I cannot easily test it on my only NixOS machine as it is using the 20.09 channel, so I cannot be the maintainer for it.

https://github.com/tu-maurice/nixpkgs/commit/c147fbd0aa7236e7da7c56198ea1bb5f6f37c085
