### ISSUE TITLE
Linux kernel 5.10.5 hardened: changed extra

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#110667]
**Describe the bug**
In kerel hardened patch changed extra suffics from `.a` to `-hardened1`
https://github.com/anthraxx/linux-hardened/commit/9e313d9cd26cb69212a7e8632ae5d755a9eedd97
Result `uname -a`
```
Linux tech 5.10.10-hardened1-hardened #1-NixOS SMP Sat Jan 23 15:04:06 UTC 2021 x86_64 GNU/Linux
```
Need remove suffics `hardened` or `hardened1`?
cc @NeQuissimus

**Comment by NeQuissimus** [comment]
:roll_eyes: Just noticed this, too :D Let me check what we need to adjust.
