### ISSUE TITLE
nixpkgs.localSystem gccarch issue

### ISSUE THREAD

**Issue by fabianhjr** [NixOS/nixpkgs#110651]
**Describe the bug**

I have been using 

```
  nixpkgs.localSystem = {
    gcc.arch = "znver2";
    gcc.tune = "znver2";
    system = "x86_64-linux";
  };
```

as part of my config for a while and recently (between yesterday and today) `nixos-rebuild` started complaining about not having that arch extension:

```
error: a 'x86_64-linux' with features {gccarch-znver2} is required to build '/nix/store/968sn36k96cy80gclrxg7df5zlac0fzv-bootstrap-stage0-glibc.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

**Additional context**
Will attempt to bisect the git history to check what changed but in case anyone is having issues will leave this documented.

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.8.a-hardened, NixOS, 21.03.git.66744709d5d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre264299.01291474ea9"`
 - channels(fabian): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fabianhjr** [comment]
My issue started with:

```
9c213398b312e0f0bb9cdf05090fd20223a82ad0 is the first bad commit
commit 9c213398b312e0f0bb9cdf05090fd20223a82ad0
Author: John Ericson <John.Ericson@Obsidian.Systems>
Date:   Fri Jan 22 20:33:55 2021 -0500

    lib: Clean up how linux and gcc config is specified
    
    Second attempt of 8929989614589ee3acd070a6409b2b9700c92d65; see that
    commit for details.
    
    This reverts commit 0bc275e63423456d6deb650e146120c39c1e0723.
```

**Comment by fabianhjr** [comment]
My issue was caused by a changed I didn't catch on the release notes:

```
+   <listitem>
+    <para>
+     Platforms, like <varname>stdenv.hostPlatform</varname>, no longer have a <varname>platform</varname> attribute.
+     It has been (mostly) flattoned away:
+    </para>
+    <itemizedlist>
+     <listitem><para><varname>platform.gcc</varname> is now <varname>gcc</varname></para></listitem>
+     <listitem><para><literal>platform.kernel*</literal> is now <literal>linux-kernel.*</literal></para></listitem>
+    </itemizedlist>
```

**Comment by Superfly-Johnson** [comment]
Uh, how did you solve your problem? I'm having the same issue

**Comment by fabianhjr** [comment]
Well, unsure how to help, I was able to narrow down the change by bisecting unsure if that is a possibility. (Hopefully there are better error messages now to avoid looking through changes)
