### ISSUE TITLE
Error while installing akonadi 20.08.2 in NixOS 20.09: `../../bin/protocolgen: Permission denied`

### ISSUE THREAD

**Issue by hahey** [NixOS/nixpkgs#110637]
**Describe the bug**
While running the following command:
```console
$ nix-env -iA nixos.akonadi
```
I found this is interrupted by the following reports:
```
[  4%] Generating Protocol implementation
/nix/store/a3fc4zqaiak11jks9zd579mz5v0li8bg-bash-4.4-p23/bin/bash: ../../bin/protocolgen: Permission denied
make[2]: *** [src/private/CMakeFiles/generate_protocol.dir/build.make:81: src/private/protocol_gen.cpp] Error 126
make[1]: *** [CMakeFiles/Makefile2:1149: src/private/CMakeFiles/generate_protocol.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
builder for '/nix/store/84g4zmbkkp48ja57ab67skzn6fkial2i-akonadi-20.08.2.drv' failed with exit code 2
error: build of '/nix/store/84g4zmbkkp48ja57ab67skzn6fkial2i-akonadi-20.08.2.drv' failed
```

**To Reproduce**
Steps to reproduce the behavior: (NixOS version: 20.09)
1. `nix-env -iA nixos.akonadi`

**Expected behavior**
`akonadi` should be installed without permission error.

**Notify maintainers**
@ttuegel @vandenoever @nyanloutre

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 20.09.2669.ce4a93e13a7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2669.ce4a93e13a7"`
 - channels(XXXXX): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ttuegel** [comment]
I cannot reproduce this at 06b11191834abae2b9ccace27818b74fe5a4b293.
