### ISSUE TITLE
Remove go_bootstrap from all-packages.nix

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#110794]
Wouldn't it make sense to remove go_bootstrap from `all-packages.nix`?
No-one is supposed to use it except for the expressions in `pkgs/development/compilers/go`.
Also, vulnix creates a lot of reports regarding it which just clutter the issue tracker.

cc @NixOS/golang

**Comment by mdlayher** [comment]
Seems like a good call to me.

**Comment by c00w** [comment]
+1 - Another issue is if you do nix-env -i go, you're prompted if you want go_boostrap, or a modern go version, and I think I've definitely installed go_bootstrap when I was a newbie and gotten very confused.

**Comment by zowoq** [comment]
I've been thinking about dropping the source bootstrap (which are x86_64 only, aarch64-linux is a binary) and switching to using binary only, similar to what we do for `rust`.

I expect that we'll need to make some changes here soon anyway to add support for `aarch64-darwin`.

**Comment by dotlambda** [comment]
> I expect that we'll need to make some changes here soon anyway

Maybe someone can just implement the change suggested in this issue until someone gets around to make those further changes. Shouldn't be too much work and would allow us to close a bunch of issues.

**Comment by bobrik** [comment]
#113230 👀
