### ISSUE TITLE
i3-dmenu-desktop no longer works

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#110852]
## Issue description

After a recent upgrade on unstable, I can no longer launch apps using i3-dmenu-desktop. I get the following error message when invoking it from the console:

### Steps to reproduce

```
$ i3-dmenu-desktop 
/nix/store/qq2bc9dlmxyjavn4n02lbrivvnqqx9b2-mpv-with-scripts-0.33.0/share/applications/mpv.desktop is encountered a second time at /nix/store/0akzg9fx7yi2cgzlxs41fymprnnjvcrm-perl-5.32.0/lib/perl5/5.32.0/File/Find.pm line 79.
```

I think it's complaining because I've installed mpv both in my system profile and in my user profile. However, this used to work just fine.

## Technical details

Last commit known to work: b333263534e
This commit definitely doesn't work: de121de16ef

Unfortunately, bisecting is not easy as it requires installing the entire system (it is technically possible though...)

There was a big CPAN update on dec 13 (cc @stigtsp). Maybe related?

**Comment by stigtsp** [comment]
Hi there,

I'm not able to reproduce this problem on aa8868c7cca

``` 
$ nix-shell -p j4-dmenu-desktop --run i3-dmenu-desktop
[{"success":true}]
```

Was able to start `mpv`

**Comment by obadz** [comment]
Pretty sure this upstream change caused the issue: https://github.com/i3/i3/pull/4013

(Rolled out in nixpkgs via af56bbf6ac976d2c6b887110da84f5d6bf21906d)

**Comment by Zimmi48** [comment]
I've just upgraded to NixOS 21.05 and I've encountered this issue as well. Launching in the console gives:

```
/run/current-system/sw/share/applications/mendeleydesktop.desktop is encountered a second time at /nix/store/07j6d0lr6p1gjxi2qhf6wn88nl81x5jj-perl-5.32.1/lib/perl5/5.32.1/File/Find.pm line 79.
```

I'm surprised that it finds Mendeley twice (I've only installed it once).

@obadz Did you find a workaround? Did you test the other versions mentioned in https://github.com/i3/i3/pull/4013#issuecomment-768349001?

**Comment by obadz** [comment]
@Zimmi48, I've reverted to i3 4.18.3 and I'm still using that… Have you found anything better?

**Comment by Zimmi48** [comment]
I uninstalled Mendeley system-wide and installed it in my user profile to work around the problem. Still unsure what difference it makes but it works.

**Comment by obadz** [comment]
I've filed https://github.com/i3/i3/issues/4522 upstream.

**Comment by obadz** [comment]
Also got tired of using an old version of i3 so for now I've put this in my overrides to patch `i3-dmenu-desktop`:

```nix
{
  i3 = super.i3.overrideDerivation (oldAttrs: {
    postInstall = oldAttrs.postInstall + ''
      ${pkgs.ed}/bin/ed $out/bin/i3-dmenu-desktop << EOF
      /follow_fast => 1
      s/^/# /
      wq
      EOF
    '';
  });
}
```

**Comment by stigtsp** [comment]
Works for me :)
