### ISSUE TITLE
Package request: Foxit Reader

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#110839]
**Project description**

Foxit Reader goes beyond a PDF viewer, it's ConnectedPDF Powered. ConnectedPDF is leading edge technology that powers cloud-based services for PDF files.

The issue with this package is that it has a UI installer which makes it harder to package and the source is not open.

**Metadata**

* homepage URL: [Foxit Software](https://www.foxitsoftware.com)
* source URL: [Foxit Reader](https://www.foxitsoftware.com/pdf-reader/)
* license: [unfree](https://www.foxitsoftware.com/pdf-reader/eula.html)
* platforms: unix, linux, darwin

**Comment by mausch** [comment]
Arch package for reference (though it seems rather old):
https://aur.archlinux.org/packages/foxitreader/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=foxitreader

**Comment by rhoriguchi** [comment]
After viewing the archlinux package I came up with this bash script:
```bash
file="FoxitReader.enu.setup.2.4.4.0911(r057d814).x64.run"

mkdir build

grep --only-matching --byte-offset --binary --text $'7z\xBC\xAF\x27\x1C' ${file} | cut -f1 -d: |
while read position; do
    dd if=${file} bs=1M iflag=skip_bytes status=none skip=${position} of="part.7z"
    7z x -bd -y -o"build" part.7z 1>/dev/null 2>&1 || true
done

rm -f part.7z
```
But when I try to create a derivation with nix, `dd` for some reason breaks the loop. When I commented out the `dd` and '7z` command it iterates through the loop with no issues.
```nix
{ pkgs ? import <nixpkgs> { } }:
pkgs.callPackage ({ stdenv, lib, fetchzip, p7zip }:
  stdenv.mkDerivation rec {
    pname = "foxit-reader";
    version = "2.4.4.0911";

    src = fetchzip {
      url = "https://cdn01.foxitsoftware.com/pub/foxit/reader/desktop/linux/${lib.versions.major version}.x/${
          lib.versions.majorMinor version
        }/en_us/FoxitReader.enu.setup.${version}.x64.run.tar.gz";
      sha256 = "0ff4xs9ipc7sswq0czfhpsd7qw7niw0zsf9wgsqhbbgzcpbdhcb7";
    };

    nativeBuildInputs = [ p7zip ];

    buildPhase = ''
      file=$src/*.run

      mkdir build

      grep --only-matching --byte-offset --binary --text $'7z\xBC\xAF\x27\x1C' $file | cut -f1 -d: |
      while read position; do
        echo $position
        dd if=$file bs=1M iflag=skip_bytes status=none skip=$position of="part.7z"
        7z x -bd -y -o"build" part.7z 1>/dev/null 2>&1 || true
      done

      rm -f part.7z
    '';
  }) { }
  ```
