### ISSUE TITLE
gnucash test suite failure after staging merge

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#11084]
Citing from http://hydra.cryp.to/build/1365143/log/raw:

~~~~
TEST: test-qof... (pid=8603)
* 15:25:26 OTHER <GLib> duplicate test case path: /qof/qofbook
FAIL: test-qof
/nix/store/gb2dwphbdjk56h0lbbyma32rlid022ad-bash-4.3-p42/bin/bash: line 1:  8602 Terminated              gtester --verbose test-qof
Makefile:778: recipe for target 'test' failed
make[5]: *** [test] Error 143
make[5]: Leaving directory '/tmp/nix-build-gnucash-2.4.15.drv-0/gnucash-2.4.15/src/libqof/qof/test'
~~~~

**Comment by vcunat** [comment]
I suspect it might've been triggered by some updates in the gtk/glib stack, but the error message isn't very suggestive. https://bugs.freedesktop.org/show_bug.cgi?id=92245

**Comment by vcunat** [comment]
Ah, yes:

> Don't use the same test name for multiple tests. GLib 2.46.0 doesn't allow this any more, and so the testsuite fails.

**Comment by peti** [comment]
I suppose this means that we either patch Gnucash 2.4.15 to play nicely with the new Glib or we disable the test suite. Any other options?

**Comment by vcunat** [comment]
Yes. It's also possible that upstream has a patch already.

**Comment by peti** [comment]
I couldn't find any in the downloads section.

**Comment by aristidb** [comment]
@peti You mentioned in the commit to update to 2.6 - did you figure out how to package gnucash 2.6 correctly, because the gnucash 2.6 from my branch that you merged only works partially.

**Comment by peti** [comment]
@aristidb, I haven't looked at 2.6.x yet. I still use version 2.4.x.
