### ISSUE TITLE
kernelPatches.export_kernel_fpu_functions doesn't apply on 5.10.11

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#110956]
## Issue description

As of https://github.com/gregkh/linux/commit/f5ee8afc19711e1dd7bacae23712e224c1b22ba4, the patch doesn't apply anymore.

Do we still need it? How can one reproduce (and obvserve) the issue its supposed to fix?

cc @Mic92 @NeQuissimus

**Comment by Mic92** [comment]
No. zfsonlinux has now an upstream fix.
