### ISSUE TITLE
nixos-rebuild switch on LiveCD needs CI

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#11091]
Running `nixos-rebuild switch` or `nixos-rebuild switch --upgrade` at boot-up of a fresh LiveCD gives back:

```
downloading Nix expressions from ‘https://nixos.org/releases/nixos/15.09/nixos-15.09.706.45128de//nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
unpacking channels...
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/6vi87s24avbaryb46pbwpb9ly6m3rslv-unit-polkit.service.drv
  /nix/store/8yq9sfxbhg25mcg5wncr23pgnnkn6r5d-unit-dbus.service.drv
  /nix/store/2s5hfk5jw4q7lpcja49jvs39khv8vfxa-system-units.drv
  /nix/store/zlq9ipfm40mbpaqrx0x9d2i97207crmw-nixos-15.09.706.45128de.drv
  /nix/store/aggw51mrm37bhm4p1l8ki8s6w4qb4p4k-local-cmds.drv
  /nix/store/5jmgsc5hd87cqixb7n27niza9rrm83af-stage-2-init.sh.drv
  /nix/store/m1wfaa7imnipldswyp1j9yq2k6r82abg-etc.drv
  /nix/store/snnizglbw49p83nlxkkixaigdr9b5b0c-nixos-15.09.706.45128de.drv
building path(s) ‘/nix/store/l7njqrvibrq7ynnx2z7gjfh8lbk1zzmn-unit-dbus.service’
building path(s) ‘/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de’
ln: failed to create symbolic link '/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de/nixos/nixpkgs/.': File exists
builder for ‘/nix/store/zlq9ipfm40mbpaqrx0x9d2i97207crmw-nixos-15.09.706.45128de.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/aggw51mrm37bhm4p1l8ki8s6w4qb4p4k-local-cmds.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/x6bkgp4lxm4dcpmh8igzp362wiq9ny89-unit-polkit.service’
cannot build derivation ‘/nix/store/5jmgsc5hd87cqixb7n27niza9rrm83af-stage-2-init.sh.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/snnizglbw49p83nlxkkixaigdr9b5b0c-nixos-15.09.706.45128de.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/snnizglbw49p83nlxkkixaigdr9b5b0c-nixos-15.09.706.45128de.drv’ failed
```

This happened a couple weeks back too on a previous LiveCD version.

**Comment by dezgeg** [comment]
Sounds like the same underlying issue as #10367

**Comment by CMCDragonkai** [comment]
@dezgeg You're referring to the similarity in:

````
ln: failed to create symbolic link '/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de/nixos/nixpkgs/.': File exists
```

vs @cstrahan issue

```
ln: failed to create symbolic link '/nix/store/zz0hzi5imrg4927v6f8mv281qs6v6pbq-nixos-16.03pre69762.e916273/nixos/nixpkgs/.': File exists
```

The command above definitely worked in 14.04, so there was some regression that's causing nixos-rebuild not to work.

**Comment by vcunat** [comment]
> Does anybody even use the LiveCD ISOs?

It isn't typical to do `nixos-rebuild` on an ISO. People rather tend to try pre-installed stuff in there and install nixos.

**Comment by CMCDragonkai** [comment]
@vcunat In 14.04, I took an CD ISO and ran a nixos-rebuild in order to install change some settings and install things before installing nixos onto the hard disk.

Right now the usecase is to change the `hostId` and `hostName` from the default in NixOS so I won't get the same `hostId` and `hostName` for all the machines, which is relevant for ZFS. I'm sure there are other usecases too.

**Comment by vcunat** [comment]
I wasn't trying to say it isn't a bug, just that most people don't need it (but I have used it myself).

**Comment by holstgr-kaust** [comment]
I just wanted to add my 'me too' to this issue.  In my case it is a NixOS 14.12.885.b373bf9 (Caterpillar) installation into Virtual Box.  I followed the instructions in the manual:

    sudo nix-channel --add https://nixos.org/channels/nixos-15.09 nixos
    sudo nixos-rebuild switch --upgrade

But I got the 'ln: failed to create symbolic link' issue shown here.  Now, when I do a 'sudo nixos-rebuild build --upgrade' I get the error along with the following (reduced) output:

    > sudo nixos-rebuild build --upgrade
    downloading Nix expressions from ‘https://nixos.org/releases/nixos/15.09/nixos-15.09.706.45128de//nixexprs.tar.xz’...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    unpacking channels...
    building Nix...
    building the system configuration...
    these derivations will be built:
      /nix/store/zlq9ipfm40mbpaqrx0x9d2i97207crmw-nixos-15.09.706.45128de.drv
      /nix/store/i4hscwn4rmwly2bj6xl9p9sb8zv6khdk-local-cmds.drv
      /nix/store/b70bbsaxid3qn5q1000p22m74saqamas-stage-2-init.sh.drv
      /nix/store/33907gdv6y921pq4lrf8z2gqnsprpkb3-nixos-15.09.706.45128de.drv
    building path(s) ‘/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de’
    ln: failed to create symbolic link '/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de/nixos/nixpkgs/.': File exists
    builder for ‘/nix/store/zlq9ipfm40mbpaqrx0x9d2i97207crmw-nixos-15.09.706.45128de.drv’ failed with exit code 1
    cannot build derivation ‘/nix/store/i4hscwn4rmwly2bj6xl9p9sb8zv6khdk-local-cmds.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/b70bbsaxid3qn5q1000p22m74saqamas-stage-2-init.sh.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/33907gdv6y921pq4lrf8z2gqnsprpkb3-nixos-15.09.706.45128de.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/33907gdv6y921pq4lrf8z2gqnsprpkb3-nixos-15.09.706.45128de.drv’ failed

After this error I see this *.lock files in /nix/store:

    [demo@nixos:/nix/store]$ ls -al *.lock
    -rw------- 1 root root 0 Nov 14 15:05 g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de.lock


And I see the following files in '/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de/nixos/nixpkgs':

    [demo@nixos:/nix/store/g1xbpwkc7agbfkcvs3fbz8rqwcsn4zk7-nixos-15.09.706.45128de/nixos/nixpkgs]$ ls -al
    total 3908
    drwxr-xr-x  7 nixbld1 nixbld    4096 Jan  1  1970 .
    drwxr-xr-x  3 nixbld1 nixbld    4096 Nov 28 15:21 ..
    -rw-r--r--  1 nixbld1 nixbld     599 Jan  1  1970 CONTRIBUTING.md
    -rw-r--r--  1 nixbld1 nixbld    1650 Jan  1  1970 COPYING
    -rw-r--r--  1 nixbld1 nixbld     352 Jan  1  1970 default.nix
    drwxr-xr-x  3 nixbld1 nixbld    4096 Jan  1  1970 doc
    -rw-r--r--  1 nixbld1 nixbld      40 Jan  1  1970 .git-revision
    drwxr-xr-x  3 nixbld1 nixbld    4096 Jan  1  1970 lib
    drwxr-xr-x  4 nixbld1 nixbld    4096 Jan  1  1970 maintainers
    drwxr-xr-x  7 nixbld1 nixbld    4096 Jan  1  1970 nixos
    lrwxrwxrwx  1 nixbld1 nixbld       1 Jan  1  1970 nixpkgs -> .
    drwxr-xr-x 16 nixbld1 nixbld    4096 Jan  1  1970 pkgs
    -rw-r--r--  1 nixbld1 nixbld 3935232 Jan  1  1970 programs.sqlite
    -rw-r--r--  1 nixbld1 nixbld    2412 Jan  1  1970 README.md
    -rw-r--r--  1 nixbld1 nixbld      13 Jan  1  1970 svn-revision
    -rw-r--r--  1 nixbld1 nixbld     231 Jan  1  1970 .travis.yml
    -rw-r--r--  1 nixbld1 nixbld       5 Jan  1  1970 .version
    -rw-r--r--  1 nixbld1 nixbld      12 Jan  1  1970 .version-suffix

If there is any additional info that would help debug this issue, let me know. (note: --show-trace doesn't seem to provide any additional debugging output)

**Comment by CMCDragonkai** [comment]
If it happens on 14.12 then this means it's a pretty old bug. Perhaps we can pinpoint which version the bug was introduced?

**Comment by domenkozar** [comment]
We also need a test once this is fixed.

**Comment by Profpatsch** [comment]
(triage) status?

**Comment by CMCDragonkai** [comment]
Well we need to try the commands again on the live cd. I suggest to put it in the CI system.

**Comment by fpletz** [comment]
Removed milestone because this is fixed. Needs tests.

**Comment by c0bw3b** [comment]
Just tested it with a live CD of `nixos-18.09-minimal` and I was able to `nixos-rebuild switch` and change env parameters and install packages.
