### ISSUE TITLE
fwup is out-of-date

### ISSUE THREAD

**Issue by francishamel** [NixOS/nixpkgs#110991]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: nixpkgs.fwup

current version: 1.5.2
desired version: 1.8.3

###### Notify maintainers

maintainers: @georgewhewell 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by francishamel** [comment]
I managed to use this overlay for now:

```
self: super:
{
  fwup = super.fwup.overrideAttrs (old: {
    src = super.fetchFromGitHub {
      owner = "fhunleth";
      repo = "fwup";
      rev = "v1.8.3";
      sha256 = "0p3kp1kai5zrgagjzhd41gl84gfqk04qnq1d1dnf0ckvhsfdq9vb";
    };
    
    buildInputs = with super; [
      libarchive
      libconfuse
      which
      xdelta
    ];
  });
}
```

**Comment by fabaff** [comment]
@francishamel, could you please take #111006 for a test run? Thanks

**Comment by francishamel** [comment]
Checked out the branch and it seems to be working :smile:
