### ISSUE TITLE
Mattermost service fails to build in pure evaluation mode (e.g. with flakes)

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#111076]
**Describe the bug**

Enabling the mattermost service causes the the nixos configuration to fail building in `pure` mode. This makes the mattermost inusable with a flake-enabled setup.

When rebuilding this: https://github.com/NixOS/nixpkgs/blob/85abeab48b5feda4b163e5bb32f50aad1164e415/nixos/modules/services/web-apps/mattermost.nix#L9-L11

Causes this error:

```
error: --- RestrictedPathError --- nix
access to path '/nix/store/a0r1z2n1qy2if2r5yxfi7px01kn0xavh-mattermost-webapp-5.25.3/config/config.json' is forbidden in restricted mode
```

**To Reproduce**
1. Enable mattermost service on flake system
2. Rebuild nixos config

Alternatively, the error should be reproducable by rebuilding a non-flakes system with `--pure`.

**Expected behavior**
Service runs

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.91, NixOS, 21.03.20210121.f217c0e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `""`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/store/pl5nzbz7s187b7x2scj27b4wpkm1g93h-source`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
 - services.mattermost
# a list of nixos modules affected by the problem
module:
 - services.mattermost
```

**Comment by FRidh** [comment]
Right, this is importing from a derivation and within Nixpkgs that is considered a bug. Either `config.json` is included in the Nixpkgs repo, or `defaultConfig` is created explicitly.

**Comment by pinpox** [comment]
Any progress on this? How could I fix this?

**Comment by collares** [comment]
Easiest way to fix it is to to copy the file represented by `${pkgs.mattermost}/config/config.json` into the nixpkgs repository and make `readFlie` use that instead.

**Comment by kisik21** [comment]
Could also create a config by using `pkgs.runCommandNoCC` - copy the config, apply transformations using shell language, output it to $out and use it as a path.

**Comment by pinpox** [comment]
Is a config.json even necessary? The [mattermost docs](https://docs.mattermost.com/administration/config-settings.html#environment-variables) say you can just use env vars:

- Find the setting in config.json. In this case, ServiceSettings.SiteURL.
- Add MM_ to the beginning and convert all characters to uppercase and replace the . with _. For example, MM_SERVICESETTINGS_SITEURL.
- The setting becomes export MM_SERVICESETTINGS_SITEURL="http://example.com".

Maybe it's simpler to just set the env vars in the systemd service and skip the config.json alltogether?

**Comment by kisik21** [comment]
Environment variables do sound cleaner!

**Comment by numinit** [comment]
@pinpox I fixed this by using jq in the startup script. See #119200, it should fix your usecase.

**Comment by numinit** [comment]
To add on: config.json is probably necessary because it contains a bunch of preconfigured "reasonable defaults." But it's not necessary to merge them with configured options using Nix.

**Comment by numinit** [comment]
I think this can be closed now.
