### ISSUE TITLE
`mktemp -p x -t yX` broken

### ISSUE THREAD

**Issue by gurjeet** [NixOS/nixpkgs#111091]
**Description**

The combination of `-p` and `-t` flags of `mktemp` lead to buggy behavior. 

**To Reproduce**

Install coreutils, if not already installed, and run the command with these options. I'm using Nixpkgs on Darwin, fwiw.

Use the optional `--dry-run` to prevent the command from cluttering your machine.

    nix-env -i coreutils
    mktemp --dry-run -p /tmp -t delXXX

**Current Output**

    /var/folders/n0/vljlpr0121j4bh5cd0hwqyy00000gn/T/del5BZ

**Expected Output**

    /tmp/delBJQ

**Notify maintainers**

@eelco (since they're listed as maintainer in tools/misc/coreutils/default.nix)
@rtburns-jpl (since rtburns@protonmail.com is the latest committer)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(gurjeetsingh): `"nixpkgs-20.09pre237807.0dc87c6e54f, nixos-18.09-18.09.2327.37694c8cc0e"`
 - nixpkgs: `/Users/gurjeetsingh/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by abathur** [comment]
While I agree that this behavior is **absurd**, AFAIK it does work as-documented:
```console
  -t                  interpret TEMPLATE as a single file name component,
                        relative to a directory: $TMPDIR, if set; else the
                        directory specified via -p; else /tmp [deprecated]
```

The behavior you're reporting is the same as you'd see with homebrew-installed coreutils:
```console
$ gmktemp --dry-run -p /tmp -t delXXX
/var/folders/hg/pt5wsk1n54d1prjyg9pff5_r0000gn/T/delmGh
```
If you remove the `-t`, you'll see that `-p` works as you're expecting in both nix- and homebrew-installed coreutils:
```console
$ mktemp --dry-run -p /tmp
/tmp/tmp.uOvabLhQwT
$ gmktemp --dry-run -p /tmp
/tmp/tmp.glLzz4GKBr
```
Likewise, it also works as you expect if you unset TMPDIR before running your command:
```console
$ ( unset TMPDIR; mktemp --dry-run -p /tmp -t delXXX; )
/tmp/delFv6
$ ( unset TMPDIR; gmktemp --dry-run -p /tmp -t delXXX; )
/tmp/delFts
```
