### ISSUE TITLE
ethminer/amdgpu ring sdma0 timeout

### ISSUE THREAD

**Issue by urlordjames** [NixOS/nixpkgs#111189]
**Describe the bug**
When using ethminer, I am consistently able to trigger an amdgpu ring sdma0 timeout error when switching workspaces in i3.  Note that I am not using ethminer in nixpkgs, I am using a custom build to circumvent downloading CUDA files because I'm using AMD and I don't need it.  After swapping workspaces during mining, it causes i3 to remain unresponsive until I quit my X11 session (see log below).  I suspect this is an issue with nixpkgs's amdgpu, OpenCL, or ROCm packages and not ethminer.  I get 0 hashes/second from ethminer regardless of if I swap workspaces or not.

**To Reproduce**
1. clone ethminer `git clone https://github.com/ethereum-mining/ethminer.git --recursive && cd ethminer`
2. enter nix-shell `NIXPKGS_ALLOW_UNFREE=1 nix-shell` ([shell.zip](https://github.com/NixOS/nixpkgs/files/5895553/shell.zip))
3. edit `libpoolprotocols/CMakeLists.txt`, on line 14 change `jsoncpp_lib_static` to `jsoncpp_lib`
4. configure and build with cmake `mkdir build && cd build && cmake --configure .. -DHUNTER_ENABLED=OFF -DETHASHCL=ON -DETHASHCUDA=OFF -DETHDBUS=OFF -DBINKERN=OFF -DAPICORE=OFF -DCMAKE_BUILD_TYPE=Release -GNinja && cmake --build . -j 12`
5. run ethminer in test mode `ethminer/ethminer -Z 1`
6. swap workspaces in i3 with $mod+num

**Additional context**
relevant portion of dmesg log:
```
[  426.867276] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma0 timeout, signaled seq=2879, emitted seq=2881
[  426.867307] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
[  426.867310] amdgpu 0000:08:00.0: amdgpu: GPU reset begin!
[  426.867328] Evicting PASID 0x800a queues
[  426.867524] amdgpu 0000:08:00.0: amdgpu: Guilty job already signaled, skipping HW reset
[  426.867532] amdgpu 0000:08:00.0: amdgpu: GPU reset(1) succeeded!
```

you can view the entire log here
[log.txt](https://github.com/NixOS/nixpkgs/files/5895569/log.txt)

here is my clinfo output
[clinfo.txt](https://github.com/NixOS/nixpkgs/files/5895652/clinfo.txt)

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.16, NixOS, 20.09.2750.85abeab48b5 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(james): `""`
 - channels(root): `"nixos-20.09.2750.85abeab48b5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by urlordjames** [comment]
I think this would be a problem with mesa, which seems to be relatively up to date, so I think I'll open an issue there instead.

**Comment by DieracDelta** [comment]
@urlordjames did you ever figure this out?

**Comment by urlordjames** [comment]
@DieracDelta sorry for being unresponsive, I've been busy recently.  I believe I was able to fix this by setting `hardware.cpu.amd.updateMicrocode = true;`.  Let me know if that works for you.

**Comment by DieracDelta** [comment]
@urlordjames thanks for the response! Glad to hear you got it working. Sadly I already have that attribute set to true. Would you mind sharing the part of your config you're using to configure AMD drivers (amdgpu specifically) or even just the nixpkgs hash/ release you're using? That would give me something to reverse engineer off of.

**Comment by urlordjames** [comment]
@DieracDelta here's what I've got that:
```
hardware.opengl.driSupport = true;

hardware.opengl.extraPackages = with pkgs; [
  amdvlk
  rocm-opencl-icd
  rocm-opencl-runtime
];
```

I'm also using `ethminer-free` from `nixpkgs-unstable`.  Not sure if this had any impact whatsoever but I also updated my BIOS at some point.
