### ISSUE TITLE
Nextcloud fresh install - Error: Command "upgrade" is not defined.

### ISSUE THREAD

**Issue by afix-space** [NixOS/nixpkgs#111175]
Hi,
I'm testing nextcloud it seem there is an issue.
I'm tying to install a fresh nextcloud and with the minimal example of the man : https://nixos.org/manual/nixos/stable/index.html#module-services-nextcloud

I get :

janv. 29 16:56:31 cloud systemd[1]: Starting nextcloud-setup.service...
janv. 29 16:56:31 cloud nextcloud-setup-start[20532]: Nextcloud is not installed - only a limited number of commands are available
janv. 29 16:56:31 cloud nextcloud-setup-start[20532]:                                      
janv. 29 16:56:31 cloud nextcloud-setup-start[20532]:   Command "upgrade" is not defined.

nextcloud-setup-start try to update a new install

same result with :
`  nixpkgs.config.permittedInsecurePackages = [
    "nextcloud-19.0.6"
  ];
`
or
`package = pkgs.nextcloud20;`

 - system: `"x86_64-linux"
 - host os: `Linux 5.4.88, NixOS, 21.03pre266581.e5ce05cc1ee (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2750.85abeab48b5, nixpkgs-21.03pre266581.e5ce05cc1ee"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

@Ma27 @beardhatcode @Mic92
I may not be calling all the maintainers in case it's a false alarm :-)

**Comment by IslandUsurper** [comment]
I just ran into this too, with `nextcloud20` as my package. Running `nextcloud-occ list` doesn't show an `upgrade` command.

**Comment by IslandUsurper** [comment]
I ran the `maintenance:install` command manually, and now `upgrade` shows up. Not sure why it didn't install through nix, though.

**Comment by afix-space** [comment]
Thanks it's work for me too.
It must certainly come from the test.
` if [[ ! -e /var/lib/nextcloud/config/config.php ]]; then `
I'll check that later.

**Comment by Ma27** [comment]
Cannot reproduce this on latest master and release-20.09. Can you please give me a minmal VM config that I can use to reproduce?

**Comment by afix-space** [comment]
Same config works in a  test VM.
https://gist.github.com/afix-space/da78514893fc2a614492316e08cb99e9
I'll try to take a closer look next week if it's still relevant.

**Comment by DieracDelta** [comment]
I am running into this error as well with about the same config as `afix-space`. Specifically I'm using [this](https://gist.github.com/jneplokh/62c4d8e79421a9bf8174c8c275163734) configuration without the nginx stuff (e.g. lines 5 to 27 commented out and `services.nextcloud.nginx.enable` not set).

**Comment by DieracDelta** [comment]
It doesn't look like the builds of nextcloud and postgres are pure (I don't even know if it's possible for them to be pure?), which is where it looks like this problem is coming from. Specifically, I had built nextcloud and postgres several times while I worked out the configuration settings I wanted. It turns out there were nextcloud and postgres folders in `/var/lib` that still remained after I uninstalled both apps. Removing those two folders, then reinstalling these programs via nix fixed the error for me.

**Comment by beardhatcode** [comment]
When I've first set up Nextcloud i encountered the same issues @DieracDelta is describing, but since then everything has run smoothly for me.

**Comment by eliasp** [comment]
It might sense to verify the `installed: true/false` result of `status` after the `maintenance:install` block, before executing `upgrade`.

**Comment by Ma27** [comment]
#112013 may prevent corrupted installations in some cases. But I'm still missing a minimal VM setup to reproduce.

**Comment by afix-space** [comment]
I thought I gave one. I 'm very new with nixos but I would be delighted to learn more. maybe you can give me a link or guide me to do this?  or pass the assignees to someone that can reproduce it. thanks

**Comment by Ma27** [comment]
Well, that's the test VM's config that I already checked. Was there any existing state in /var/lib/nextcloud during your install attempt?

**Comment by afix-space** [comment]
I don't know I need to reproduce this on the machine in question. i can try

**Comment by Ma27** [comment]
@eliasp have you checked whether repeated `occ:install` calls are actually safe? Especially if you want to "work out" your options iteratively.

> I don't know I need to reproduce this on the machine in question. i can try

Yeah please do that. You can also answer my question "Was there any existing state in /var/lib/nextcloud during your install attempt?". This is IIRC the main cause for problems like this.

**Comment by afix-space** [comment]
I don't have access to the machine but I've just started a vps and the same config works with the same steps.
the problem would not have been solved :-) ?
I'm going to look at the merge for the fun

**Comment by afix-space** [comment]
cool merge :-)   I've used adminpass = "abcd1234" on vps may be this is the trick

**Comment by afix-space** [comment]
@Ma27 do you really need me to reproduce the problem ? it's really very easy and I know you are active in others post who explain the problem.
If you really need that I have a vps whith the bug.

**Comment by Ma27** [comment]
Well, I'm trying to check if there are any other causes apart from an existing state. Hence my question whether there was any existing state when you encountered the issue.

**Comment by afix-space** [comment]
I don't know in any case, /var/lib/nextcloud/* seems to be the same between the 2 generations

**Comment by alarsyo** [comment]
Hit this too:

I'd misconfigured the postgres database (the nextcloud module doesn't setup a nextcloud user and role on the db, which I'm used to for other modules), so the `nextcloud-setup` service errored out with a database "role doesn't exist" issue. Once I fixed this, I hit this problem, which went away with a good old `rm -rf /var/lib/nextcloud`.

**Comment by poly2it** [comment]
I'm getting this issue on unstable.

**Comment by poly2it** [comment]
`rm -rf /var/lib/nextcloud` "worked" for me.

**Comment by axelsimon** [comment]
I'm getting it on 24.11:
`nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11"`

No luck on removing the /var/lib/nextcloud dir either.

**Comment by Ma27** [comment]
I'll lock this issue now. It is four years old and the module has changed in a lot of ways, so I doubt that any of this is related to the original problem.

If you encounter this: file a __clear & concise__ bug-report that includes nixpkgs rev, logs, nixos config, things you've tried, whether it's a fresh install. There's even an __entire section__ in the manual for things to check!

I can't help anyone if the bugreports consist of two sentences missing 99% of the information I'd need to give a qualified answer.
