### ISSUE TITLE
wally-cli hangs and makes keyboard unresponsive

### ISSUE THREAD

**Issue by nixin72** [NixOS/nixpkgs#111199]
**Describe the bug**
The wally-cli tool doesn't work. I download the new firmware from the Oryx configuration tool and try to flash it, but my keyboard just becomes unresponsive until I unplug it and plug it back in. 

**To Reproduce**
1. Install wally-cli (through either `nix-env` or in `configuration.nix`)
2. Run `wally-cli` pointing to a file from Oryx 
3. Click the reset button on the keyboard

**Expected behavior**
The wally-cli tool will prompt me to hit the reset button on my keyboard, which it does, and after hitting it, the firmware will be flashed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22285063/106322084-497a1300-6243-11eb-9844-e4f7ed95a3b5.png)

**Additional context**
This happens using wally 1.1.1 and 2.0.0 from 20.09 and unstable respectively.

**Notify maintainers**
@spacekookie @r-burns 

**Metadata**
```
❯ nix-shell -p nix-info --run "nix-info -m"                                                             ~
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 20.09.2635.f5f66148b28 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(nixin72): `"home-manager-20.09"`
 - channels(root): `"unstable-21.03pre263901.68398d2dd50, nixos-20.09.2635.f5f66148b28"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

Please let me know if there's anything I've done wrong and if this is my fault, I'm new to Nix/NixOS, so I apologize if I did something wrong and this actually works fine :confused:

**Comment by r-burns** [comment]
Hi! First off, are you using the ZSA udev rules? Make sure you have something like this in your NixOS configuration.nix:
```nix
{
services.udev.packages = with pkgs; [ zsa-udev-rules ];
}
```

**Comment by nixin72** [comment]
Hi, once I figured out how to add packages from unstable so I could add this line, it worked fine! Thank you so much, sorry for the trouble. 

I think it should probably be specified somewhere that the wally package relies on this one though, because I didn't realize I was missing anything and looking back now, I don't see anything mentioning the `zsa-udev-rules` package.

**Comment by r-burns** [comment]
That's a really good point - I think even the working method I'm using is outdated; there's actually a built-in ZSA module in NixOS now: https://github.com/NixOS/nixpkgs/pull/91203
Clearly we're in need of some better documentation, so I went ahead and created a wiki page for this: https://nixos.wiki/wiki/ZSA_Keyboards

**Comment by nixin72** [comment]
Awesome, thank you! I've spent all day playing around with the layout on this thing now that it's working hahah :joy: Well, with that being documented now, I'll close the issue.
