### ISSUE TITLE
tailscale doesn't work when cross-compiled (for armv6/raspi0)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#111251]
**Describe the bug**

I am building a raspberry pi zero sd card and cross compiling the system.

tailscale 1.4.0 fails to start-up with `Exec format error`:
```
-- Boot 9835287340dc40e69c000353db1670ff --
Jan 01 00:00:27 rpizero1 systemd[580]: tailscaled.service: Failed to execute /nix/store/z13kx5i55z15jr4l71hmrrp2h3nrsayz-tailscale-1.4.0-armv6l-unknown-linux-gnueabihf/bin/tailscaled: Exec format error
Jan 01 00:00:27 rpizero1 systemd[580]: tailscaled.service: Failed at step EXEC spawning /nix/store/z13kx5i55z15jr4l71hmrrp2h3nrsayz-tailscale-1.4.0-armv6l-unknown-linux-gnueabihf/bin/tailscaled: Exec format error
Jan 01 00:00:27 rpizero1 systemd[1]: tailscaled.service: Control process exited, code=exited, status=203/EXEC
Jan 01 00:00:27 rpizero1 systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Jan 01 00:00:27 rpizero1 systemd[1]: Failed to start Tailscale node agent.
```

**To Reproduce**
```
    nixpkgs.crossSystem = lib.systems.examples.raspberryPi;
    services.tailscale.enable = true;
```

Build, boot the system.

Maybe this is because of how the wrapper is built?

**Notify maintainers**
cc: @danderson @martinbaillie (tailscale module/pkg maintainers)

**Metadata**
This is on `nixos-unstable-small`: b43756e22b3128f9415fdcd954a5b1e3b865680a

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tailscale
# a list of nixos modules affected by the problem
module: tailscale
```

**Comment by danderson** [comment]
What does `file /nix/store/z13kx5i55z15jr4l71hmrrp2h3nrsayz-tailscale-1.4.0-armv6l-unknown-linux-gnueabihf/bin/tailscaled` say? Curious what kind of format it ends up with, e.g. whether we're building for the wrong ARM variant.

Preposterously, I don't have an rpi to reproduce, so my ability to debug hands on is going to be limited.

**Comment by colemickens** [comment]
Thanks for the fast response @danderson. This is by no means a pressing issue, it was more to see if I could, than because I desperately need to. 

Anyway, as I had thought, it looks related to the wrapper. If I copy over `tailscaled`, it's a wrapper:
```
/tmp/tailscaled: a /nix/store/dskh7v2h3ly3kdkfk3xmjlqql1zr0hnw-bash-4.4-p23/bin/bash -e script, ASCII text executable
```

And if I look at the interpreter, it's the wrong bash:
```
/tmp/bash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

And if I run the real `tailscaled` manually, it at least starts up fine:
```
"/nix/store/z13kx5i55z15jr4l71hmrrp2h3nrsayz-tailscale-1.4.0-armv6l-unknown-linux-gnueabihf/bin/.tailscaled-wrapped"
logtail started
Program starting: v1.4.0, Go 1.15.7: []string{"/nix/store/z13kx5i55z15jr4l71hmrrp2h3nrsayz-tailscale-1.4.0-armv6l-unknown-linux-gnueabihf/bin/.tailscaled-wrapped"}
LogID: e8ce86fa70797dbc57394ea835aba440de7050164a967ecdddebaf2aa7f5f6a7
logpolicy: using UserCacheDir, "/home/cole/.cache/Tailscale"
logpolicy.Read /home/cole/.cache/Tailscale/tailscaled.log.conf: open /home/cole/.cache/Tailscale/tailscaled.log.conf: no such file or directory
--state is required

```

**Comment by samueldr** [comment]
From a discussion on IRC, it looks like there's no tailscale issue.

See a simple reproducer for the issue:

https://gist.github.com/samueldr/f23c6b7b31e253113a1b7d5303640312

Tested against 891f607d5301d6730cb1f9dcf3618bcb1ab7f10e

**Comment by colemickens** [comment]
I don't know if there was ever a tracking issue for the root cause, but this is solved.

Now if only Tailscale used kernel wireguard and didn't eat up a noticeable amount of CPU on these devices...
