### ISSUE TITLE
iwd: declarative wireless networks

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#111252]
**Describe the bug**

We should support declarative networks for `iwd`.

Copying and pasting this from Discourse: https://discourse.nixos.org/t/iwd-declarative-wifi-configs-networks-credentials/11267

The only things I see in nixpkgs right now are very wpa_supplicant centric.

To declare networks for iwd, it looks like one must calculate a PreSharedKey and provide it with the Passphrase in a ini file in /var/lib/iwd/[ssid].psk:

> sudo cat /var/lib/iwd/chimera-wifi.psk
[Security]
PreSharedKey=[hex str]
Passphrase=[my wifi password in plaintext]

Unfortunately:

* I don’t see anything about it reading from `/etc/iwd/*.psk`
* I’m not finding any sort of `PassphraseFile=` line that would tell `iwd` to read the password from a file, such as one placed by sops-nix. Maybe I’ll file a feature request on `iwd` after looking more.

Thoughts? Others interested? Would we just write a systemd oneshot service that symlinks the configs in `/var/lib/iwd` at boot? Patch iwd to look in /etc/iwd for networks?

Is it important that the PSK be re-used for a given device, or can the one-shot just generate the PSK from the passphrase on each boot?

**Comment by bqv** [comment]
Once upon a #75800

**Comment by colemickens** [comment]
Well, huge shout-out to @Ma27 for doing far more work than I'd be willing to to try and support this. I guess I'll leave this open, since I still think it would be a nice-to-have some day.

**Comment by Ma27** [comment]
The very latest state of my work is linked in https://github.com/NixOS/nixpkgs/pull/75800#issuecomment-703132361. But as I said, I'm not really sure if it's a good idea to implement this.

If you really want to have declarative networks, you can also use the current state of the linked PR. In fact, I'm still using it as it works quite fine and I wasn't motivated to rewrite my Wifi setup until now :D

**Comment by Ma27** [comment]
@colemickens in case you're interested in a solution which supports both "imperative" and declarative networks (and not strictly `iwd`), you may be interested in trying out #113716. It's kinda ready now, I'm using it for >2 months now on my machine :)

**Comment by colemickens** [comment]
This could certainly be cleaned up, use a function to DRY, etc, but here's what I'm doing for declarative IWD networks. It works fine.

(The plaintext network is defunct/retired, and the psk is already leaked other places in the repo, don't judge too harshly.)

https://github.com/colemickens/nixcfg/blob/b8accd1c25d3df273a501f55673021aaf264d77a/mixins/iwd-networks.nix

**Comment by colemickens** [comment]
Given that this mostly "just works",  I don't think there's really a need to directly support this more, other than documenting/blogging it maybe. As such, I'm going to close this.
