### ISSUE TITLE
glibcLocales equivalent on OSX

### ISSUE THREAD

**Issue by YPares** [NixOS/nixpkgs#11125]
Is there an equivalent to glibcLocales on OSX?

When using GHC inside a pure nix-shell I get:
`Warning: unable to set locale to UTF-8 encoding; GHC may fail with 'invalid character'`
and on Ubuntu adding glibcLocales in the buildInputs made that go away.

**Comment by pikajude** [comment]
@YPares The darwin locales package will be added to nixpkgs as part of the `sandbox-profiles` branch and will be available as the attrpath `darwin.locale`. The locale path will also be set in the generic preHook though so you shouldn't need to worry about it. (See https://github.com/NixOS/nixpkgs/pull/11001)

**Comment by YPares** [comment]
@pikajude Thank you for the news. Is the generic preHook an OSX specific thing or will it also be set on Linux?

**Comment by vcunat** [comment]
I think it would be nice to create a locale abstraction in nixpkgs that acts as a common interface to both glibc and Darwin locale (and perhaps others in future).

**Comment by Profpatsch** [comment]
(triage) any actionable items?

**Comment by knedlsepp** [comment]
@pikajude: I'm currently fixing pandas on darwin, which has the line `++ optional isDarwin pkgs.darwin.locale; # provides the locale command`
But actually if I try to run
```
nix-shell -p darwin.locale --pure --run "locale"
```
I get `locale: command not found`. Did this `darwin.locale` ever work, as you mention:

> locale path will also be set in the generic preHook though so you shouldn't need to worry about it
