### ISSUE TITLE
Update Erlang to version 18.1

### ISSUE THREAD

**Issue by rolkar** [NixOS/nixpkgs#11123]
Newest version of Erlang have now been increased from 18.0 to 18.1.

I propose a change that can handle both 18.0 and 18.1

**Comment by ericsagnes** [comment]
Genuine question here, [NixOS policy](https://nixos.org/nixpkgs/manual/#sec-versioning) is to generally keep "versions that differ significantly in functionality", is there a particular reason (like newly introduced bugs or compatibility breaks) that motivate having both 18.0 and 18.1?

**Comment by rolkar** [comment]
Hi guys, tremendous work you are doing with nearly 3000 modules and nearly 8000 versions. My need was to be able to compile several versions of Erlang and do simple switch between them. This do not really scale in your case. So, I will use kerl or envirius instead. So, I withdraw my pull request.

Maybe I will make a simple pull request to upgrade to 18.1 instead, we will see.

/Take care
