### ISSUE TITLE
Standardize input method management

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#11138]
This issue's goal is in a first time to gather input methods users and maintainers feedback to standardize input method management in NixOS. 
Everybody input is welcomed.

After that, sub-issues could be generated for related tasks, and this issue could be used to track the overall process.

---

Currently, input methods are managed in different ways:

- [ibus](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/ibus.nix) is using `programs.ibus.enable` and `programs.ibus.plugins` modules.
- [uim](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/uim.nix) is using `uim.enable` module and has no particular way to manage plugins.
- [fcitx](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/inputmethods/fcitx/wrapper.nix) use a wrapper package where plugins can be specified by overriding the derivation.
- [nabi](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/inputmethods/nabi/default.nix) is a standard package.

Propositions:

#### 1. Use a consistent module namespace

input methods in:
- `programs` namespace: `uim.enable` would change to `programs.uim.enable`.
- root: `programs.ibus.enable` would change to `ibus.enable`.
- a new dedicated namespace, eg `i18n.inputMethod.ibus.enable`.

**Currently chosen implementation: new `i18n.inputMethod` namespace.**

#### 2. Provide modules for every input method

Input methods usually require a few tweaks, like gtk and qt modules to be set in the environment, to work.
As NixOS modules are a user-friendly way to manage this problem, modules should be provided for every input method if possible.
In current state that would translate in adding modules for `nabi` and `fcitx`.

#### 3. Factorize pkgs hierarchy

Currently there is one folder per input method and per engine. As we add engines, `pkgs/tools/inputmethods` will get crowded. This has no undesirable effect, but it might be a good idea to keep the directory clean and structured.

Propositions:
a. do like pidgin, have a `{input-method}-engines` folder for each input method and put each engine in a sub directory:
````
./pkgs/tools/inputmethods/fcitx-engines
├── fcitx-anthy
│   └── default.nix
├── fcitx-hangul
│   └── default.nix
├── fcitx-mozc
│   └── default.nix
└── fcitx-skk
    └── default.nix
````
b. create a sub-folder `engines` in each input method:
````
./pkgs/tools/inputmethods/fcitx/engines
├── fcitx-anthy
│   └── default.nix
├── fcitx-hangul
│   └── default.nix
├── fcitx-mozc
│   └── default.nix
└── fcitx-skk
    └── default.nix
````
c. or keep the status quo and keep adding every engine under `pkgs/tools/inputmethods`

**Currently chosen implementation: a.**

---

update: 
- added "3. Factorize pkgs hierarchy"
- updated "1. Use a consistent module namespace" dedicated namespace to `i18n.inputMethod`
- added status

---

#### Status

see work in progress PR #11254

---

cc 
@gebner ibus maintainer
@iyzsong fcitx maintainer
@wavewave nabi maintainer
@taku0 uim main commiter

**Comment by taku0** [comment]
Dedicated namespace will help users to choose their input method since NixOS options are sorted by qualified name in the manual, so I :+1: to a new dedicated namespace.

**Comment by iyzsong** [comment]
Sure, I'd like `i18n.inputMethod`.
But since I only use nix but not NixOS these days, so I won't be very helpful for modules, sorry :-

**Comment by ericsagnes** [comment]
Thanks for the suggestion!
I updated the namespace proposition with `i18n.inputMethod` as it is a better one, and added a proposition for managing package hierarchy.

**Comment by ericsagnes** [comment]
@iyzsong I tried to use fcitx with anthy (I usually use ibus) and pressing `enter` key after having wrote some text just make fcitx froze and dont display the candidates window. 
Had you experienced this issue too?

**Comment by iyzsong** [comment]
No, it once worked for me, but I don't use it rectently, so can't be sure.

Nice work, I think some changes you have made can be merged immediately,
how about create a WIP pull request and link it here, so we can push them incremental?
Thanks!

**Comment by ericsagnes** [comment]
@iyzsong Good idea, I linked the PR in the original message.

**Comment by iyzsong** [comment]
Hi, about the pkgs hierarchy, I think the current one that fcitx using is good enough.
the `engines` are anthy,  mozc, etc. , be used by both fcitx and ibus (`frameworks`) through
`fcitx-anthy`, `ibus-anthy`, etc. (`plugins`).

How about move the plugins for ibus into the ibus folder?
```
inputmethods/
├── anthy
│   └── default.nix
├── fcitx
│   ├── default.nix
│   ├── fcitx-anthy.nix
│   └── fcitx-qt5.nix
├── ibus
│   ├── default.nix
│   ├── ibus-anthy.nix
│   └── ibus-table.nix
└── mozc
    └── default.nix
```

**Comment by ericsagnes** [comment]
The in-progress work is using `{input-method}-engines/{input-method}-{engine}/default.nix` to have some uniformity with [pidgin-plugins](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/networking/instant-messengers/pidgin-plugins). 
The contributor manual is a little [vague](https://nixos.org/nixpkgs/manual/#sec-organisation) regarding this topic, so I would love to have more inputs of people aware of dos and donts on the package file hierarchy. (It could be a good occasion to add guidelines for such cases in the manual)

As a side note, current `inputmethods/mozc/default.nix` is specialized to `ibus` (`fcitx-mozc` is using a different version, dependencies and set of patches), so it is planned to be renamed to `ibus-mozc` and moved to the corresponding hierarchy .

**Comment by vcunat** [comment]
> The contributor manual is a little vague regarding this topic, so I would love to have more inputs of people aware of dos and donts on the package file hierarchy.

Probably don't put much effort into the hierarchy. My feeling after NixCon is that there is a general agreement that the file hierarchy is confusing, and it's likely we will (1) flatten it significantly (so that you don't need to guess where a package might be located) and (2) make it closer to the attribute hierarchy. The problem with this is that doing such a thing would make a terrible mess with any merges and cherry-picks between versions before and after the renames.

**Comment by iyzsong** [comment]
Done in #11254.
