### ISSUE TITLE
mailspring: GLib-GIO-ERROR: Settings schema 'org.gtk.Settings.FileChooser' is not installed

### ISSUE THREAD

**Issue by au-phiware** [NixOS/nixpkgs#111368]
## Description

[Mailspring](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/applications/networking/mailreaders/mailspring/default.nix) crashes when attempting to open any file dialog, such as saving an attachment.

## Steps to reproduce

1. Launch mailspring
2. From the menu bar select Edit > Install Theme...

**Expected behavior**

A "Choose Directory" file dialog should open

**Actual Behaviour**

Mailspring crashes with the following output:

```
(mailspring:11833): GLib-GIO-ERROR **: 11:14:35.289: Settings schema 'org.gtk.Settings.FileChooser' is not installed
Cannot upload crash dump: cannot exec /usr/bin/wget
Failed to get crash dump id.
Report Id:
[1]    11833 trace trap (core dumped)  mailspring
```
## Workaround

Adding to `$XDG_DATA_DIRS` resolves the issue:

```
XDG_DATA_DIRS="$XDG_DATA_DIRS:/nix/store/2h88jnwvhj0cj209vp2wpsfdbgm0gqbf-gtk+3-3.24.21/share/gsettings-schemas/gtk+3-3.24.21" mailspring
```

## Additional context

I have added mailspring to `environment.systemPackages` in my system's `configuration.nix` file.

**Notify maintainers**
@toschmidt

**Metadata**
Results of `nix-shell -p nix-info --run "nix-info -m"`:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.10, NixOS, 20.09.2787.6e7f25001fe (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2787.6e7f25001fe, home-manager, unstable-21.03pre265961.891f607d530"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mailspring
```

**Comment by au-phiware** [comment]
I tried installing from unstable but to no avail.

**Comment by worldofpeace** [comment]
This package is missing `wrapGAppsHook` in `nativeBuildInputs`. See the gnome section of the nixpkgs manual
