### ISSUE TITLE
 Package request: telega.el

### ISSUE THREAD

**Issue by andreoss** [NixOS/nixpkgs#111497]
**Project description**

 *telega* is full featured _unofficial_ client for Telegram platform for GNU Emacs. 

**Metadata**

* homepage URL: https://zevlg.github.io/telega.el/
* source URL: https://github.com/zevlg/telega.el
* license: gpl3
* platforms: linux

**Extra** 
There is a package definition for Guix https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/emacs-xyz.scm#n24396, which probably can be easily ported.

**Comment by veprbl** [comment]
It's already packaged: `emacsPackages.melpaStablePackages.telega`
