### ISSUE TITLE
regression in gnome shell ssh agent between 20.09 and unstable

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#111457]
**Describe the bug**

Previously an ssh-agent was started

**To Reproduce**

- Boot a 20.09 system to gnome-shell
- Try to use an ssh key
- Observe the following askpass program appearing
    
    ![image](https://user-images.githubusercontent.com/857308/106383536-a1f70f00-6401-11eb-9cb7-670cca83ee01.png)

- Observe that this key is stored in an agent
- Boot an `unstable-small` system to gnome-shell
- Observe that there is no agent running and `SSH_AUTH_SOCK` is not set

**Expected behavior**

This handy agent works

**Notify maintainers**

Not sure what program's responsible.

cc @NixOS/gnome

**Comment by jtojnar** [comment]
Possibly fixed by https://github.com/NixOS/nixpkgs/pull/111557.

**Comment by worldofpeace** [comment]
Just noticed this on my machine. I'm currently updating to https://github.com/NixOS/nixpkgs/pull/111557 to see if that works

**Comment by expipiplus1** [comment]
I think this is all fixed now
