### ISSUE TITLE
docker: version 20.10.2, using --host=fd:// gives socket error

### ISSUE THREAD

**Issue by exFalso** [NixOS/nixpkgs#111578]
**Describe the bug**
Apparently this bug was already caught in the original PR https://github.com/NixOS/nixpkgs/pull/108960, but for some reason the fix got later reverted in https://github.com/NixOS/nixpkgs/pull/109447? 

The error message from systemd is:
```
Feb 01 16:20:16 asd dockerd[21349]: time="2021-02-01T16:20:16.197031255+01:00" level=info msg="Starting up"
Feb 01 16:20:16 asd dockerd[21349]: failed to load listeners: no sockets found via socket activation: make sure the service was started by systemd
Feb 01 16:20:16 asd systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
```

**To Reproduce**

```
  virtualisation.docker.enable = true;
```

**Expected behavior**

docker should start

**Additional context**

`--host=unix://` fixes it

**Notify maintainers**

@mikroskeem @roberth 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.91, NixOS, 21.03pre265130.f217c0ea7c1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(exfalso): `"nixos-21.03pre265130.f217c0ea7c1"`
 - channels(root): `"nixos-21.03pre265130.f217c0ea7c1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mikroskeem** [comment]
See reason for the fix: https://github.com/NixOS/nixpkgs/pull/109418#issuecomment-760935552. This issue was originally caused by build misconfiguration (Moby build flags in wrong place perhaps).

**Comment by mikroskeem** [comment]
Unable to reproduce this on my system with following configuration:
```nix
virtualisation.docker.enable = true;
```
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.93, NixOS, 21.03pre267299.5ff6700bb82 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre267299.5ff6700bb82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by exFalso** [comment]
Just tried with an explicit `systemctl start docker.socket`, this fixes the issue. Looking at logs of `docker.socket`:
```
Feb 01 16:17:44 asd systemd[1]: docker.socket: Socket service docker.service already active, refusing.
Feb 01 16:17:44 asd systemd[1]: Failed to listen on Docker Socket for the API.
```
This happened the first time it tried to start docker. I think this is a race in startup, docker starts before the socket, prevents `docker.socket` from starting, then `docker.socket` start fails with this error.

According to systemd docs:
> No implicit WantedBy= or RequiredBy= dependency from the socket to the service is added. This means that the service may be started without the socket, in which case it must be able to open sockets by itself. To prevent this, an explicit Requires= dependency may be added.

So perhaps we just need to add a `Requires=docker.socket` line to `docker.service`?

**Comment by mikroskeem** [comment]
Seems like this is exactly the case.
