### ISSUE TITLE
tree-sitter: buildPhase incorrectly searches for scanner resulting in undefined symbols?

### ISSUE THREAD

**Issue by colinxs** [NixOS/nixpkgs#111526]
**Describe the bug**

The `parser` libraries generated via the `tree-sitter` derivation results in a an `.so` with undefined symbols. I believe this is because of [these lines](https://github.com/NixOS/nixpkgs/blob/86d5d9650d39128b028d0de33c5354cc20bb4608/pkgs/development/tools/parsing/tree-sitter/grammar.nix#L29) in `grammars.nix`:
```
    scanner_cc="$src/src/scanner.cc"
    if [ ! -f "$scanner_cc" ]; then
      scanner_cc=""
    fi
```
which doesn't take into account scanners ending in ".c" (e.g. tree-sitter-bash).

The following overlay fixes the issue:
```
let
  patchGrammar = grammar: drv: (drv.overrideAttrs (oa: {
    buildPhase = ''
      runHook preBuild
      scanner_c=""
      if [ -f "$src/src/scanner.c" ]; then
        scanner_c="$src/src/scanner.c"
      elif [ -f "$src/src/scanner.cc" ]; then
        scanner_c="$src/src/scanner.cc"
      fi
      $CC -I$src/src/ -shared -o parser -Os $src/src/parser.c $scanner_c -lstdc++
      runHook postBuild
    '';
  }));
in
final: prev: {
  tree-sitter = prev.tree-sitter.overrideAttrs (oa: {
    passthru.builtGrammars = prev.lib.mapAttrs patchGrammar oa.passthru.builtGrammars;
  });
}

```

Although perhaps a better solution is to explicitly list out the files to be compiled like [nvim-treesitter does](https://github.com/nvim-treesitter/nvim-treesitter/blob/a0f03ec333646f9b9f542a08423d24691f24bb78/lua/nvim-treesitter/parsers.lua).

**To Reproduce**
On `nixpkgs` `master`:
```
nm -gD /nix/store/3kayc2dmhffbgaj0hr36960mpd2s32xp-tree-sitter-css-grammar-0.17.3/parser
                 w __cxa_finalize
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
00000000000067d6 T tree_sitter_css
                 U tree_sitter_css_external_scanner_create
                 U tree_sitter_css_external_scanner_deserialize
                 U tree_sitter_css_external_scanner_destroy
                 U tree_sitter_css_external_scanner_scan
                 U **tree_sitter_css_external_scanner_serialize**
```

**Expected behavior**
Defined symbols.

**Screenshots**

**Additional context**

**Notify maintainers**
@Profpatsch 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-7630-generic, Pop!_OS, 20.04 LTS`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(colinxs): `"nixpkgs-21.03pre264882.92c884dfd71"`
 - nixpkgs: `/home/foo/.nix-defexpr/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ tree-sitter.builtGrammars ]
# a list of nixos modules affected by the problem
module:
```

**Comment by jlesquembre** [comment]
@colinxs looks like there is already a PR: #108639

**Comment by colinxs** [comment]
@jlesquembre awesome, I missed that one!

**Comment by cole-h** [comment]
https://github.com/NixOS/nixpkgs/pull/108639#issuecomment-790043957
