### ISSUE TITLE
overrideAttrs on kernel derivation loses passthru values

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#111504]
**Describe the bug**

There is an oddity with how the kernel derivations react when `overrideAttrs` is used with them. Some `passthru` values are lost, namely `features` and `commonStructuredConfig`.

In turn, this makes customizing them harder than expected. These values are used in the NixOS modules.

**To Reproduce**

Using `overrideAttrs`, the `passthru` value given to the function does not hold all values found on the derivation's own passthru.

Details:

 - https://gist.github.com/samueldr/5cb327043a2f451edb5b38175eb07c73

``` nix
let
  kernel = pkgs.linux_latest;
  overriddenKernel = kernel.overrideAttrs({ passthru ? {}, ... }: {
    passthru = passthru // {
      world = "y'all";
    };
  });
in
  /* ok   */ assert kernel ? features;
  /* ok   */ assert kernel ? commonStructuredConfig;
  /* fail */ assert overriddenKernel ? features;
  /* fail */ assert overriddenKernel ? commonStructuredConfig;
```

**Expected behavior**

Values in `passthru` on the derivation should all be present in the `overrideAttrs` call.

**Workaround**

``` nix
let
  kernel = pkgs.linux_latest;
  overriddenKernel = kernel.overrideAttrs({ passthru ? {}, ... }: {
    passthru = kernel.passthru // { # <- use the derivation rather than the param
      world = "y'all";
    };
  });
in
```

**Additional context**

 - https://gist.github.com/samueldr/5cb327043a2f451edb5b38175eb07c73

And where I suspect this is coming from:

 - https://github.com/NixOS/nixpkgs/blob/21a2aebf314c385ac44c09492c76c31f846ae3e3/pkgs/os-specific/linux/kernel/generic.nix#L179-L187

This is can be observed against 891f607d5301d6730cb1f9dcf3618bcb1ab7f10e, and is an evaluation issue. No builds happened.

The linked gist contains a full reproduction.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Infinisil** [comment]
Haven't tested this properly, but
```diff
diff --git a/pkgs/os-specific/linux/kernel/generic.nix b/pkgs/os-specific/linux/kernel/generic.nix
index dd3050a93ee..a90245b8a91 100644
--- a/pkgs/os-specific/linux/kernel/generic.nix
+++ b/pkgs/os-specific/linux/kernel/generic.nix
@@ -186,4 +186,6 @@ let
     passthru = kernel.passthru // (removeAttrs passthru [ "passthru" ]);
   };
 
-in lib.extendDerivation true passthru kernel
+in kernel.overrideAttrs (old: {
+  passthru = old.passthru // passthru;
+})
```
We wouldn't have these kinds of problems if some generic override interface like https://github.com/NixOS/rfcs/pull/67#issuecomment-747822045 existed

**Comment by Infinisil** [comment]
Short explanation: `extendDerivation` updates the derivation without updating all the override functions. So `.overrideAttrs` still points to the one from `kernel`. So once you call that, all the changes from `extendDerivation` are undone.

**Comment by MetaDark** [comment]
Wow what a coincidence. I ran into this same problem today trying to adapt @thefloweringash's [port of lg-hammerhead](https://github.com/NixOS/mobile-nixos/pull/144) to work on Mobile NixOS's master :smile: (specifically with the `kernelWithDTB` wrapper).

**Comment by ShamrockLee** [comment]
I made a new PR (#288154) to tackle this issue. Please take a look.
