### ISSUE TITLE
Signal-desktop segfault on startup

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#111593]
**Describe the bug**
When starting signal-desktop (also tried the version from 20.03), it segfaults:
```
$ signal-desktop
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /nix/store/1aqrz90b3m8pmk0c1rm6n3hyfq50g5g4-signal-desktop-1.39.6/lib/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/me/.config/Signal
config/get: Did not find user config file, cache is now empty object
x-attr dependency did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
No protocol specified
Segmentation fault (core dumped)
```

**To Reproduce**
1. Install signal-desktop, for example via `nix-env -iA nixos.signal-desktop`
2. Run it via `signal-desktop`

**Additional context**
People seem to report similar issues due to sandboxing of electron app.

**Notify maintainers**

@ixmatus @primeos @equirosa 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

warning: unknown setting 'extra-sandbox-paths'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.77, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
warning: unknown setting 'extra-sandbox-paths'
 - channels(root): `"nixos-21.03pre257780.e9158eca70a, nixos-unstable-21.03pre257780.e9158eca70a"`
 - channels(me): `"local-nixpkgs-unstable-21.03pre267409.f5daa8ab31f, nixos-20-03-20.03.3324.929768261a3, local-nixos-unstable-21.03pre262347.257cbbcd3ab, test, home-manager, nixos-unstable-21.03pre250162.34ad166a830"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

EDIT: if I install signal directly from my `configuration.nix` (it is an older version 1.37 since my configuration is lying a bit behind) then it does not segfault... But of course it's outdated.

**Comment by primeos** [comment]
Hm, strange... But since I test every update I obviously cannot reproduce this.
`No protocol specified` hint's at a "connection" issue to the X11 server, IIRC.
Is `$DISPLAY` set and does e.g. `xorg.xeyes` run?

**Comment by tobiasBora** [comment]
Thanks for your comment. Ohh I think I understood the issue, and it's related to this issue [here](https://github.com/NixOS/nixpkgs/issues/110494): sometimes all my open applications "lose access to X11" and it's hard to notice, except when I get errors when running any graphical application. So my bad, the problem is not on signal-desktop. Sorry, and thanks for your quick answer!
