### ISSUE TITLE
GhostScript broken on Darwin

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#11165]
If I install ghostscript in the global environment and execute it, I get the following message.

```sh
$ gs
dyld: Library not loaded: libgs.dylib.9.15
  Referenced from: /Users/svenkeidel/.nix-profile/bin/gs
  Reason: image not found
[1]    2272 trace trap  gs
```

Any idea how to fix this?

Best,
Sven

**Comment by pSub** [comment]
I don't have a Mac to test/fix this, but it looks like `install_name_tool` can help you. Just grep for it in nixpkgs and look into http://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-loaded. I hope this helps.

**Comment by svenkeidel** [comment]
I'll give it a try. Thanks

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/12161.
