### ISSUE TITLE
flutter: 1.22.4 -> 1.22.5/1.22.6

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#111620]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `flutter`

current version: `1.22.4`
desired version: `1.22.5` or `1.22.6`

###### Notify maintainers

maintainers: @thiagokokada @ericdallo @babariviere 

###### Note for maintainers

I had to [revert](https://github.com/NixOS/nixpkgs/pull/111187) the bump for `1.22.5` version of Flutter because while it builds it doesn't work. While investigating the issue today I discovered that the issue is that `flutter` (not `flutter_tools`, that is the CLI for `flutter`) seems to either not shipping with `sky_engine` anymore or something else.

I tried to build `flutter` but it can't resolve `sky_engine` dependency, probably because this is some internal `flutter` dependency (it seems Sky Engine was the name of Flutter before). So the build system for Flutter is broken for any newer version of Flutter (assuming this is the way Google will ship Flutter from here on).

I did some initial investigation on how to fix it. Assuming we will need to build Flutter from scratch we can follow this: https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment. However this seems fairly complicated, and Google changes its build system constantly (just see Chromium for example). So I don't think we will want to follow this path.

We have some other options: we could simply download the Flutter, mount a `buildFHSUserEnv` and assume that Flutter is impossible to package. Or some other idea, I am opening this issue so we maintainers can discuss it.

**Comment by ericdallo** [comment]
Yeah, it's really a problem now, I'd like to hear @babariviere and maybe @GRBurst opinions

**Comment by NANASHI0X74** [comment]
2.0.0 was released today🎉

**Comment by babariviere** [comment]
Sorry for the late reply, I have tried with `buildFHSUserEnv` and it has some issues with the client certificates. Also, it will prompt you to download new versions and if I remember correctly, it will try to modify itself by downloading external dependencies.

Otherwise, I think it's a great idea but it will take some time to make it work.
