### ISSUE TITLE
MOC: (81!) Resampling not supported!

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11169]
When use `mocp` over `jack` it can't change sample rate. Should use `libresamplerate` for this.

**Comment by jagajaga** [comment]
We need to change input library?

**Comment by Pitometsu** [comment]
Probably, I'm not sure.

**Comment by Pitometsu** [comment]
From MOC's Readme:
> For resampling (playing files with sample rate not supported by your hardware):
> libresamplerate version 0.1.2 (http://www.mega-nerd.com/SRC/)

**Comment by Pitometsu** [comment]
We can add:
```nix
, samplerateSupport ? true, libsamplerate
```
and
```nix
++ opt samplerateSupport libsamplerate
```

**Comment by Pitometsu** [comment]
Strange: I added `libsamplerate` to `buildInputs`, but on configuration phase still:
```
checking for samplerate... no
```
:-( ...What did do I whong???

**Comment by Pitometsu** [comment]
Currently I have:
```nix
      moc = pkgs.stdenv.lib.overrideDerivation pkgs.moc (attrs: {
        buildInputs = attrs.buildInputs ++ (with pkgs; [ libsamplerate taglib libmpcdec wavpack faad2 curl file ]); # +librcc +libmagic -libmpc
	configureFlags = "--with-rcc --without-oss --with-alsa --with-jack --with-aac --with-mp3 --with-musepack --with-vorbis --with-flac --with-wavpack --with-sndfile --with-modplug --with-ffmpeg --with-speex --with-timidity --with-samplerate --with-curl --with-sidplay2 --with-magic --disable-cache --disable-debug";
      });
```

**Comment by nbp** [comment]
@Pitometsu frequently, you will have configure options which are expecting the path to be given as argument, so you might have to specify  `--with-samplerate=${libsamplerate}` or something similar.

If you need to, you can investigate with either the `nix-shell` or `nix-build -K`.

**Comment by jagajaga** [comment]
Try override like I do https://github.com/jagajaga/my_configs/blob/master/.nixpkgs/common.nix#L16

**Comment by Profpatsch** [comment]
(triage) is this solved?

**Comment by Pitometsu** [comment]
yes, thanks.
