### ISSUE TITLE
goimapnotify: sh not found in $PATH when retrieving password

### ISSUE THREAD

**Issue by collares** [NixOS/nixpkgs#111688]
**Describe the bug**
When running as a systemd service [via home-manager](https://github.com/nix-community/home-manager/blob/5263fe459413a411e51355bfae5b5673b481dbe3/modules/services/imapnotify.nix), goimapnotify fails to fetch mail with:

```Feb 02 19:27:29 hostname goimapnotify[10072]: 2021/02/02 19:27:29 Can't retrieve password from command: exec: "sh": executable file not found in $PATH```

This comes from https://gitlab.com/shackra/goimapnotify/-/blob/master/command.go#L38, which might need patching.

**Notify maintainers**
@wohanley @duairc

**Comment by wohanley** [comment]
Patching Nix packages is not something I know a lot about, and I'm struggling with the documentation... it seems like there are a few options here:
1. patch the source
2. patch the binary
3. wrap the binary, ensuring a usable `sh` is added to `PATH`

I don't know which one is the right choice. @collares or @duairc, if either of you can enlighten me, that would be great, although I will keep digging on my own. Alternatively, if either of you knows how to solve this problem and that would be faster than explaining it to me, don't let me hold you up :)

**Comment by duairc** [comment]
I'm not an expert either, but I think something like this would work:

```diff
diff --git a/pkgs/tools/networking/goimapnotify/default.nix b/pkgs/tools/networking/goimapnotify/default.nix
index 4232a5a4fed..6ee95f2df99 100644
--- a/pkgs/tools/networking/goimapnotify/default.nix
+++ b/pkgs/tools/networking/goimapnotify/default.nix
@@ -13,6 +13,10 @@ buildGoPackage rec {
     sha256 = "1d42gd3m2rkvy985d181dbcm5i3f7xsg2z8z6s4bpvw24pfnzs42";
   };
 
+  postPatch = ''
+    substituteInPlace command.go --replace '"sh"' '"/bin/sh"'
+  '';
+
   goDeps = ./deps.nix;
 
   meta = with lib; {
```

**Comment by wohanley** [comment]
@collares, are you in a position to make that change and see if it works for you? I don't see this problem in my environment, and I assume neither does @duairc, so I expect you've got the best test case if you have enough of a development environment to try it.

**Comment by collares** [comment]
The above patch fixes the issue for me. Thanks!
