### ISSUE TITLE
qemu-5.2.0 build on unstable possibly broken.

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#111651]
**Describe the bug**
Adding the line `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` to [vm.nix](https://github.com/Mic92/nixos-shell/blob/93df1dde693635f2573d584c001cc454dd983a1d/examples/vm.nix) and running `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz make test` I get

>rm: cannot remove '/nix/store/60nv5372byadkkwkwvdimmzn4jm9r3d4-qemu-5.2.0/share/applications/qemu.desktop': No such file or directory
[log file](https://gist.githubusercontent.com/573/0f3e1f4c80183da5f6fd7a034d20a6a5/raw/2d4d80f4abb3fd68aa7ce338b4cbc11417fa4db2/rfhpc57x4qlf5scnnkg4iq6xkjvaby5z-qemu-5.2.0.drv.log)

_Originally posted by @573 in https://github.com/NixOS/nixpkgs/issues/106988#issuecomment-771552800_

**To Reproduce**
1. Using https://github.com/Mic92/nixos-shell, when I add the line `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` to [vm.nix](https://github.com/Mic92/nixos-shell/blob/93df1dde693635f2573d584c001cc454dd983a1d/examples/vm.nix)
2. run (using [this](https://github.com/NixOS/nixpkgs/pull/106988/commits/9e403b19a1444b373874b6e9efdd728613c6badc) commit):
```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz make test
```

**Expected behavior**
qemu-5.2.0 and vm built and started, as in i. e.
```
NIX_PATH=nixpkgs=https://channels.nixos.org/nixos-20.09/nixexprs.tar.xz make test
```
see screenshots.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/123878/106609044-6ecd9080-6565-11eb-840a-970db2a679a7.png)

**Additional context**

Without the line `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` the build (`NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz`) runs fine.

**Notify maintainers**
cc @Mic92 @blitz @flokli ?

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-19041-Microsoft, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.8`
 - channels(user): `""`
 - nixpkgs: `/nix/store/w2h7sxjzpg21xxbmr7ghy0042zyxgb2n-9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Mic92** [comment]
@Izorkin mind to have a look?

**Comment by Izorkin** [comment]
Check with this patch:
```
diff --git a/pkgs/applications/virtualization/qemu/default.nix b/pkgs/applications/virtualization/qemu/default.nix
index 0f585a3f613..b381008d9e5 100644
--- a/pkgs/applications/virtualization/qemu/default.nix
+++ b/pkgs/applications/virtualization/qemu/default.nix
@@ -143,7 +143,7 @@ stdenv.mkDerivation rec {

   postFixup = ''
     # the .desktop is both invalid and pointless
-    rm -f $out/share/applications/qemu.desktop
+    test -e $out/share/applications/qemu.desktop && rm -f $out/share/applications/qemu.desktop

     # copy qemu-ga (guest agent) to separate output
     mkdir -p $ga/bin

```

**Comment by 573** [comment]
Seem to not get applied for starters. Can sbd help pls.

```
let
nixpkgs = import <nixpkgs> {
   overlays = [ (final: prev: {
     qemu = prev.qemu.overrideAttrs (old: {
        name = "my-patched-qemu-${old.version}";
    patches = (old.patches or []) ++ [
      (prev.fetchpatch {
        url = "https://gist.githubusercontent.com/573/29b1ad750bd88102177e8dcdfcaf540e/raw/0cb9ddfb8ac4d50ef4e6e290aacb7fa4bbdf0b7c/qemu-5.2.0-111651.patch";
        # nix-hash --flat --type sha256 qemu-5.2.0-111651.patch
	sha256 = "92e8305303f86e559eaaf989a3a8617dbbad2fb8c51772e4ebd6334d93569700";	#"0mw0ramg4ydqdqs33kw9m0rjvw5fvfa0scsq753pn7biwx6gx9hx";
      })
    ];
    });
  })];
}; in
with nixpkgs;
stdenv.mkDerivation {
  name = "nixos-shell";
  src = ./.;
  buildInputs = [ bash ];
  preConfigure = ''
    export PREFIX=$out
  '';
}
```

**Comment by Mic92** [comment]
> Seem to not get applied for starters. Can sbd help pls.
> 
> ```
> let
> nixpkgs = import <nixpkgs> {
>    overlays = [ (final: prev: {
>      qemu = prev.qemu.overrideAttrs (old: {
>         name = "my-patched-qemu-${old.version}";
>     patches = (old.patches or []) ++ [
>       (prev.fetchpatch {
>         url = "https://gist.githubusercontent.com/573/29b1ad750bd88102177e8dcdfcaf540e/raw/0cb9ddfb8ac4d50ef4e6e290aacb7fa4bbdf0b7c/qemu-5.2.0-111651.patch";
>         # nix-hash --flat --type sha256 qemu-5.2.0-111651.patch
> 	sha256 = "92e8305303f86e559eaaf989a3a8617dbbad2fb8c51772e4ebd6334d93569700";	#"0mw0ramg4ydqdqs33kw9m0rjvw5fvfa0scsq753pn7biwx6gx9hx";
>       })
>     ];
>     });
>   })];
> }; in
> with nixpkgs;
> stdenv.mkDerivation {
>   name = "nixos-shell";
>   src = ./.;
>   buildInputs = [ bash ];
>   preConfigure = ''
>     export PREFIX=$out
>   '';
> }
> ```

This is not a patch for qemu but for nixpkgs.

**Comment by 573** [comment]
Thanks @Mic92, now IC !
But still, how to [apply patches](https://github.com/NixOS/nixpkgs/pull/59990) in this case to nixpkgs ?

Cannot wrap my head around it.

As a workaround for now I am applying (with running - assumes using unmodified [`make test-forward` (examples/vm-forward.nix)](https://github.com/Mic92/nixos-shell/blob/dc5153580077a1d214a895d146f8cbbfbaf8d3e1/Makefile#L12) - nixos-shell do `ssh nixos-shell ls -d /nix/store/*-qemu-5.2.0` to figure path)
```
NIX_PATH=nixpkgs=https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz NIX_BUILD_TOP=/tmp/remote-build nix-build '<nixpkgs>' -A fortune --argstr system aarch64-linux --option extra-sandbox-paths "/run/binfmt /nix/store/12d5ir0qyw7lcd77ms3pj85j0pqhzpvy-qemu-5.2.0" --option extra-platforms aarch64-linux --builders 'ssh://nixos-shell aarch64-linux' -j0
```

**Comment by Mic92** [comment]
> Thanks @Mic92, now IC !
> But still, how to [apply patches](https://github.com/NixOS/nixpkgs/pull/59990) in this case to nixpkgs ?
> 
> Cannot wrap my head around it.
> 
> As a workaround for now I am applying (with running - assumes using unmodified [`make test-forward` (examples/vm-forward.nix)](https://github.com/Mic92/nixos-shell/blob/dc5153580077a1d214a895d146f8cbbfbaf8d3e1/Makefile#L12) - nixos-shell do `ssh nixos-shell ls -d /nix/store/*-qemu-5.2.0` to figure path)
> 
> ```
> NIX_PATH=nixpkgs=https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.xz NIX_BUILD_TOP=/tmp/remote-build nix-build '<nixpkgs>' -A fortune --argstr system aarch64-linux --option extra-sandbox-paths "/run/binfmt /nix/store/12d5ir0qyw7lcd77ms3pj85j0pqhzpvy-qemu-5.2.0" --option extra-platforms aarch64-linux --builders 'ssh://nixos-shell aarch64-linux' -j0
> ```

```console
$ git clone https://github.com/NixOS/nixpkgs
$ cd nixpkgs
$ git am < some.patch
$ NIX_PATH=nixpkgs=$PWD ...
```

**Comment by 573** [comment]
Using modified [default.nix](https://github.com/Mic92/nixos-shell/blob/ce3bbd0202008d2b26f36f989a20aeeba5d911ed/default.nix):
```
let
  originNixpkgs = #import ./nixpkgs.nix;
(builtins.fetchTarball {url="https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz"; sha256="13vaja71pspnnq5hbdidn1m3p6jx1rh0bhcqpng4ym2k19i54k1q";});
  originPkgs = import originNixpkgs {};
  nixpkgsPatches = [
      {
         name = "nixpkgs-qemu-5.2.0-desktop.patch";
         url = "https://gist.githubusercontent.com/573/29b1ad750bd88102177e8dcdfcaf540e/raw/0cb9ddfb8ac4d50ef4e6e290aacb7fa4bbdf0b7c/qemu-5.2.0-111651.patch";
	 sha256 = "sha256:1dixygyrdjaaqpvy04wb4jxvj8lxg8s0v9kmwbx4az2xvg18cyl1";
      }
];
  localNixpkgsPatches = [
  ];
  nixpkgs = originPkgs.stdenv.mkDerivation {
    name = "nixpkgs-patched";
    src = originNixpkgs;
    phases = [ "unpackPhase" "patchPhase" ];
    patches = map originPkgs.fetchpatch nixpkgsPatches ++ localNixpkgsPatches;
    postPatch = ''
      patch=$(printf '%s\n' ${builtins.concatStringsSep " " (map (p: p.sha256) nixpkgsPatches)} |
        sort | sha256sum | cut -c -7)
      mv $PWD $out
      echo "+patch-$patch" >$out/.version-suffix
    '';
  };
  pkgs = import nixpkgs {
    config = {}; # Make the config pure, ignoring user's config.
    #overlays = import ./overlays.nix;
  };
in
pkgs.stdenv.mkDerivation {
  name = "nixos-shell";
  src = ./.;
  buildInputs = [ pkgs.bash ];
  preConfigure = ''
    export PREFIX=$out
  '';
}
```

I got now

>@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/jhqf85cicnqwbp7lxyf82z3qa6gl0jpm-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/af37i75c1qyra42k0bdn4mhd4ci7j2gj-nixpkgs-qemu-5.2.0-desktop.patch
patching file pkgs/applications/virtualization/qemu/default.nix
patch unexpectedly ends in middle of line
Hunk #1 FAILED at 143.
1 out of 1 hunk FAILED -- saving rejects to file pkgs/applications/virtualization/qemu/default.nix.rej

**Comment by 573** [comment]
>git am < ~/nixos-shell-2/qemu-5.2.0-111651.patch
Applying:
error: corrupt patch at line 13
Patch failed at 0001
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by Izorkin** [comment]
@573 replace manually the line in file `pkgs/applications/virtualization/qemu/default.nix`
```
rm -f $out/share/applications/qemu.desktop
```
to
```
test -e $out/share/applications/qemu.desktop && rm -f $out/share/applications/qemu.desktop
```

**Comment by 573** [comment]
With manual replacement it works.

Patch application doesn't work.

**Comment by Mic92** [comment]
> With manual replacement it works.
> 
> Patch application doesn't work.

than you can make a pull request out of it.

**Comment by 573** [comment]
> Using [modified (see link for ref.)](https://discourse.nixos.org/t/better-way-to-use-nixpkgs-git-repo/6376/5) [default.nix](https://github.com/Mic92/nixos-shell/blob/ce3bbd0202008d2b26f36f989a20aeeba5d911ed/default.nix):
> 
> ```
> let
>   originNixpkgs = #import ./nixpkgs.nix;
> (builtins.fetchTarball {url="https://github.com/NixOS/nixpkgs/archive/9e403b19a1444b373874b6e9efdd728613c6badc.tar.gz"; sha256="13vaja71pspnnq5hbdidn1m3p6jx1rh0bhcqpng4ym2k19i54k1q";});
>   originPkgs = import originNixpkgs {};
>   nixpkgsPatches = [
>       {
>          name = "nixpkgs-qemu-5.2.0-desktop.patch";
>          url = "https://gist.githubusercontent.com/573/29b1ad750bd88102177e8dcdfcaf540e/raw/0cb9ddfb8ac4d50ef4e6e290aacb7fa4bbdf0b7c/qemu-5.2.0-111651.patch";
> 	 sha256 = "sha256:1dixygyrdjaaqpvy04wb4jxvj8lxg8s0v9kmwbx4az2xvg18cyl1";
>       }
> ];
>   localNixpkgsPatches = [
>   ];
>   nixpkgs = originPkgs.stdenv.mkDerivation {
>     name = "nixpkgs-patched";
>     src = originNixpkgs;
>     phases = [ "unpackPhase" "patchPhase" ];
>     patches = map originPkgs.fetchpatch nixpkgsPatches ++ localNixpkgsPatches;
>     postPatch = ''
>       patch=$(printf '%s\n' ${builtins.concatStringsSep " " (map (p: p.sha256) nixpkgsPatches)} |
>         sort | sha256sum | cut -c -7)
>       mv $PWD $out
>       echo "+patch-$patch" >$out/.version-suffix
>     '';
>   };
>   pkgs = import nixpkgs {
>     config = {}; # Make the config pure, ignoring user's config.
>     #overlays = import ./overlays.nix;
>   };
> in
> pkgs.stdenv.mkDerivation {
>   name = "nixos-shell";
>   src = ./.;
>   buildInputs = [ pkgs.bash ];
>   preConfigure = ''
>     export PREFIX=$out
>   '';
> }
> ```
> 
> I got now
> 
> > @nix { "action": "setPhase", "phase": "unpackPhase" }
> > unpacking sources
> > unpacking source archive /nix/store/jhqf85cicnqwbp7lxyf82z3qa6gl0jpm-source
> > source root is source
> > @nix { "action": "setPhase", "phase": "patchPhase" }
> > patching sources
> > applying patch /nix/store/af37i75c1qyra42k0bdn4mhd4ci7j2gj-nixpkgs-qemu-5.2.0-desktop.patch
> > patching file pkgs/applications/virtualization/qemu/default.nix
> > patch unexpectedly ends in middle of line
> > Hunk #1 FAILED at 143.
> > 1 out of 1 hunk FAILED -- saving rejects to file pkgs/applications/virtualization/qemu/default.nix.rej

Got the patch to be applied via `git format-patch` or say it is applied though not to the right set of nixpkgs. Have a suspicion it to do with using nixpkgs twice in the expression cited above. Where it says `nixpkgs =` should rather use `nixpkgsPatched =` and stick to that new identifier.

**Comment by 573** [comment]
@Mic92 will try and get my hands-on.

**Comment by 573** [comment]
https://github.com/NixOS/nixpkgs/pull/113189

**Comment by flokli** [comment]
With https://github.com/NixOS/nixpkgs/pull/113189 merged, this can be closed?
