### ISSUE TITLE
Launching either Brave, Chromium, or Kitty freezes the system with loud CPU fan on latest unstable

### ISSUE THREAD

**Issue by a4d442663580** [NixOS/nixpkgs#111657]
I just upgraded to latest unstable a few hours ago. After the upgrade, the system keeps freezing if I run any of the program mentioned in this issue title. When I did a rollback to the version before upgrade, the problem persist.

Also, an unrelated problem is that all of my passwords saved in Brave have been replaced with jumbled binary blob. Not sure if due to the incompatible version between the upgrade from Brave 1.17.73 to 1.19.88 or something else. I currently lost access to most of my accounts because my passwords were autogenerated. Obviously this is a throwaway account because I can't access github with my usual account (@rht). Ugh!

**Comment by rht** [comment]
I managed to recover my passwords. All I did was to delete the `Login Data` file from `~/.config/BraveSoftware/Default`. 

> When I did a rollback to the version before upgrade, the problem persist.

This is no longer true. The problem has gone when I did the rollback. I have tried doing an upgrade again though, with the same freezes problem.

**Comment by xaverdh** [comment]
does a reboot fix the problem?

**Comment by rht** [comment]
The system was frozen, so I had to hard-reboot my laptop. And the problem still persisted.

**Comment by rht** [comment]
This is different from #80936. I tried launching kitty from xterm (xterm worked), and didn't observe any error message.

**Comment by rht** [comment]
More info: launching Firefox was fine.

**Comment by rht** [comment]
Just tried upgrading. Still the same problem. My system is stuck at Dec 2020 nixos-unstable.

**Comment by rht** [comment]
Pinging @primeos (since you are a maintainer of Mesa). Does this look like a Mesa problem?

**Comment by primeos** [comment]
Mesa could e.g. trigger GPU bugs but IMO it's always the kernel diver's fault.
In any case: This should be a kernel bug/issue but debugging those is often very difficult.
You could e.g. allow pinging your system and see if it still responds when this happens (in which case it's likely only the GPU module that's affected). And I'd also set `kernel.sysctl."kernel.sysrq" = 1;` (or similar) and try to regain control of the keyboard (https://en.wikipedia.org/wiki/Magic_SysRq_key - R for unraw and then switch to a different tty).
Anyway, this might help to get started but unfortunately I don't have time/motivation help with such issues. Good luck ;)

**Comment by rht** [comment]
So it could be a kernel problem. I tried upgrading to Linux 5.10 instead of 5.11, and still encountered the problem. My system is a generic Thinkpad x280, which I'm sure a lot of people use. I wonder why I am the only one with this problem.

**Comment by rht** [comment]
More info: I downgraded to 5.4 and encountered no problem at all. So it is a kernel problem, not some xorg video driver. I can only wait to test 5.12 later on, for now.

**Comment by rht** [comment]
Tested on 5.10.36, it works. No longer an issue.
