### ISSUE TITLE
defaultGateway not changed after nixos-rebuild switch

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#11176]
changing **networking.defaultGateway** should take effect after `nixos-rebuild switch`, but i have still the old gateway (checked with `route -n`)

i had to `systemctl restart network-addresses-eth0.service` manually.

cc @wkennington

**Comment by copumpkin** [comment]
Probably related to https://github.com/NixOS/nixpkgs/issues/6830?

**Comment by Profpatsch** [comment]
(triage) does this still happen?

**Comment by davidak** [comment]
@Profpatsch yes.

## Technical details

* System: NixOS 16.09pre87354.d217279 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre87354.d217279" (nixos-unstable)

**Comment by globin** [comment]
Tested this, fixed,
