### ISSUE TITLE
Alternative solutions to building ghc compiler from scratch?

### ISSUE THREAD

**Issue by Cmdv** [NixOS/nixpkgs#111721]
## Issue description
When using nix with Haskell, if the project I invoke isn't using a version of ghc I've already built via nix. Then the whole process has to happen again. Unfortunately for my self I'm on MacOs and this process can take 6-8 hours! 😞

(Also with only 2 versions of ghc & 4-5 projects, it's taken up 115gig of hard drive space 😨 )

### Question
Is there an alternate way of achieving quicker build times or could it instead just pull down a pre compiled ghc?
Hopefully my question isn't too naive, I've tried looking for a solution through other peoples projects, blog posts, FP slack etc, but to no avail.

**Comment by veprbl** [comment]
There are several binary versions available
https://github.com/NixOS/nixpkgs/blob/dfab15bd086ed794229200fe256b836b466b4017/pkgs/top-level/haskell-packages.nix#L50-L56
which use binaries from upstream
https://github.com/NixOS/nixpkgs/blob/dfab15bd086ed794229200fe256b836b466b4017/pkgs/development/compilers/ghc/8.2.2-binary.nix#L39-L42

**Comment by Cmdv** [comment]
@veprbl ah superb thanks so much, I need to familiarise my self more with the repo when search for answers like this! for some reason when using the github search for `ghc865` doesn't return any code results 🤷 

Would it be acceptable to add some more binary versions in a PR?

**Comment by veprbl** [comment]
> Would it be acceptable to add some more binary versions in a PR?

Probably depends on whether you can make case for having those. As an alternative, you can always have them defined in your local expressions.

cc @cdepillabout @peti

**Comment by cdepillabout** [comment]
As far as I know, we generally only use the binary versions of GHC for bootstrapping the versions of GHC that are built from source.

However, I don't think we really have any policy on which versions of GHC to provide, and which of those should be built from source.  Although in general, Nixpkgs seems to strive for having more stuff built from source, and less `patchelf`ed binaries.

> the project I invoke isn't using a version of ghc I've already built via nix. Then the whole process has to happen again. Unfortunately for my self I'm on MacOs and this process can take 6-8 hours! 

I'm somewhat surprised by this.  Taking a look at https://status.nixos.org/, there is a `nixpkgs-20.09-darwin` channel.  My guess is that this channel should have GHCs being built without problems, so you won't have to do a source build.

Or maybe your projects are pinning to the non-MacOS channel, and they just happen to not be built by Hydra?

It kind of seems like this isn't really a Haskell-related problem, but more of a general Nix CI / Hydra problem?  I'm not an OSX user, so I don't know the specifics here, but maybe you could look into why these things aren't being built by Hydra?

Also, possibly related: https://discourse.nixos.org/t/recurring-funding-for-making-macos-first-class-citizen-in-nix-ecosystem/11386

> Also with only 2 versions of ghc & 4-5 projects, it's taken up 115gig of hard drive space 

115 gig seems somewhat excessive!  By "2 versions of GHC and 5 projects", you mean that you have 2 versions of GHC for 5 different projects, so 10 versions of GHC total?

On Linux, the size of the closure for GHC is only about 2gb, so 115 gigs seems too big!  Maybe `nix-collect-garbage` would help get rid of the now-unneeded build-time deps for GHC?

**Comment by veprbl** [comment]
@Cmdv Is there any remaining concern?

**Comment by Cmdv** [comment]
@veprbl I'll close it as ended up getting a linux laptop for developing 😅 but I might be going back to deving on macOS in the future and if I run into this again I'll reopen 😄
