### ISSUE TITLE
Traffic Server

### ISSUE THREAD

**Issue by heroku-miraheze** [NixOS/nixpkgs#111750]
**Project description**
Traffic Server is a Apache product.

**Metadata**

* homepage URL: http://trafficserver.apache.org/
* source URL: https://github.com/apache/trafficserver
* license: mit, bsd, gpl2+, etc.
* platforms: unix, linux, darwin, etc.

**Comment by siraben** [comment]
> **Project description**
> Traffic Server is a Apache product.
> 
> **Metadata**
> 
>     * homepage URL: http://trafficserver.apache.org/
> 
>     * source URL: https://github.com/apache/trafficserver
> 
>     * license: mit, bsd, gpl2+, etc.
> 
>     * platforms: unix, linux, darwin, etc.

@heroku-miraheze please fill out the template correctly and update the license and platforms accordingly.
