### ISSUE TITLE
nixpkgs Upstream Dependencies are Offline or Their Declared hash Differs from Actual hash

### ISSUE THREAD

**Issue by martinvahi** [NixOS/nixpkgs#11177]
I first tried to write about that to 

    nix-dev@lists.science.uu.nl

but my letter got stuck to some spam filter or just did not go through due to some weird reason. So, the following is a Copy/Paste with Markup related modifications.

    ---citation--start---

nixpkgs dependencies availability test is about 300MiB in size due to a clone of the

    https://github.com/NixOS/nixpkgs

and resides at [a location at my web site](http://technology.softf1.com/nix/2015/2015_11_19_NixOS_nixpkgs_download_test_by_martin_vahi_at_softf1_com.tar.bz2)

sha256:
f05cf8bb85527a14f22adf0e2b3a7fa56f63461b7580620e4d54204c4d2db1ba

The idea is roughly:

    git clone https://github.com/NixOS/nixpkgs
    cd nixpkgs
    find . -name '*.nix' > list_of_nixfiles.txt

and then each of the nix-files is searched for pairs of fetch-url's and hash values and a gigantic bash-script is generated that contains lines of calls to the nix-prefetch-url

    ---a--demo--excerpt--start---
    nix-prefetch-url --type sha256
    http://bits.xensource.com/oss-xen/release/4.5.1/xen-4.5.1.tar.gz
    0w8kbqy7zixacrpbk3yj51xx7b3f6l8ghsg3551w8ym6zka13336 ;
    nix-prefetch-url --type sha256 sourceInfo.url sourceInfo.hash ;
    nix-prefetch-url --type sha256
    http://download.belastingdienst.nl/belastingdienst/apps/linux/ib2007_linux.tar.gz
    13p3gv086jn95wvmfygdmk9qjn0qxqdv7pp0v5pmw6i5hp8rmjxf ;
    ---a--demo--excerpt--end---

I executed the gigantic bash script and my conclusion is that many up-stream packages, their files, are offline or their hashes do not match, specially those of the [npm](https://www.npmjs.com/).

In those circumstances it is absolutely no wonder that there are various build problems. I propose that in addition to "stable" and "unstable" packages would be classified as "Nix-contained" and
"up-stream-dependent".

The "Nix-contained" packages would be buildable without downloading anything from any server other than the Nix project servers and various caches. I believe that package specific, up-stream dependent, package upgrade tools might be bundled with the "Nix-contained" packages, so that when the up-stream servers come online, the package upgrade could be _manually_ made and the "Nix-contained" set of packages is supplemented with a new version of the package without removing the old version.

Currently it seems to me that the up-stream dependent package build scripts try to do 2 in one: build a Nix package and upgrade its dependencies. In the case of the "Nix-contained" packages the package building would work without downloading anything from upstream and all testing and experimentation that is related to the upgrade of the dependencies of a "Nix-contained" package, would be carried out by the package maintainer at a time, when he/she has the time to work on the package, not whenever the package is being automatically built.

Thank You for reading my letter and I hope to receive criticism that tells that I'm missing/omitting
a lot of important issues or have otherwise come up with a spectacular blunder. 

Regards,
Martin.Vahi@softf1.com

P.S. The "manual" upgrade of dependencies will probably be a requirement even due to computational limitations and security requirements. Formal verification might take a lot of CPU-power and it might not be optimal to run that every time a package is built.

    ---citation--end-----

**Comment by nbp** [comment]
@martinvahi I can see you message on the mailing list, as you also got a reply.
In the worse case you can see it on http://lists.science.uu.nl/pipermail/nix-dev/2015-November/018688.html

Closing.

**Comment by martinvahi** [comment]
Strange, I can not find it, but the link that You provided was very useful. I'll look into the [proposed](http://lists.science.uu.nl/pipermail/nix-dev/2015-November/018699.html) 

    nix-store -r $(grep -l outputHash $(nix-store -qR $(nix-instantiate '<nixpkgs>' -A foobar) | grep '.drv$'))

but it seems to me that nobody addressed the issue that some dependencies of the nixpkgs are occasionally offline and some of the nixpkgs packages upgrade their dependencies as part of the build task. Any upgrade of dependencies can actually break a package and needs testing and probably package code modifications. In that sense I do not think that this issue should be closed, id est this bug report here should be re-opened.

**Comment by vcunat** [comment]
> Strange, I can not find it, but the link that You provided was very useful.

IIRC the mailer doesn't send messages to people that are known to already have the message, e.g. the sender or additional recipients.

**Comment by martinvahi** [comment]
First of all, thank You all/both for Your answers. I took a second look at the mailing list digests and it seems that indeed, replies to my both letters are present, but my own letter seems to be omitted, as described by vcunat. However, what regards to the nixpkgs packages that download upstream dependencies as part of their build process, then it seems to me that I have to create some utility for myself that classifies the different nixpkgs packages, generates a list of pacakges that can be classified as "Nix-contained". The utility would act on the nixpkgs packages a bit like the [PricewaterhouseCoopers](http://www.pwc.com/) acts on companies, giving them marks in different categories. 

To avoid re-implementing a wheel, does there exist some utility that tries to do something similar already?

**Comment by vcunat** [comment]
That's what the `outputHash` grep is for, I believe. Only fixed-output derivations can access network and thus download http://nixos.org/nix/manual/#fixed-output-drvs Usage of them for anything but fetches is rare, I think, except for the recently added `texlive` packages (all of them, i.e. thousands).

**Comment by martinvahi** [comment]
A citation from the manual:

    It sometimes happens that the URL of the file changes, e.g., because servers are reorganised or no longer available. We then must update the call to fetchurl, e.g.,

Is there a way to add more then one fetch URL, so that when one of the servers is offline, then another URL is tried? If the hash of the downloadable file is already known, then if anonymity is discarded, it should not matter, which URL is used.

Second question is, is there some plugin mechanism so that for some type of network, for example, [Tor](https://www.torproject.org/) or [GNUnet](https://gnunet.org/) or [whatever else](https://freenetproject.org/), the downloading of a pacakge could be delegated to some other application. The mechanism would be that first the URL is classified, a bit like files are classified to MIME types, and then according to the type of the URL the download task is handed over to a program that is able to handle the given type of URL. The URL might even be some [Magnet link](https://en.wikipedia.org/wiki/Magnet_URI_scheme).

**Comment by nbp** [comment]
(reopen as the discussion moved to github)

**Comment by martinvahi** [comment]
May be a dirty workaround might be the use of some proxy, like

    url = http://www.my_proxy_site.com/nix_proxy.php?hash_algorithm=foo&hash_value=bar&network=tor&hint_url_1=<the first url to try>&hint_url_2=<the second URL to try>&<etc.>

and for local proxies the .nix file is preprocessed by replacing 

    www.my_proxy_site.com/
    with
    localhost:<some port number>/

Probing for different, mirroring, URL-s would then be the task of the proxy.

**Comment by vcunat** [comment]
@martinvahi: `fetchurl` supports using a list in `urls` instead of `url`.

**Comment by vcunat** [comment]
Second question: you can code an arbitrary fetcher &ndash; we have fetchgit, fetchzip, fetchsvn, ... it's an arbitrary builder that is given access to network because the hash of output is specified in advance.

**Comment by martinvahi** [comment]
On my AMD64:

    ts2@linux-0fiz:/nix$ nix-instantiate '<nixpkgs>' -A hello
    error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I)

The whole excerpt:

    ts2@linux-0fiz:/nix$ nix-env version
    error: no operation specified
    Try ‘nix-env --help’ for more information.
    ts2@linux-0fiz:/nix$ nix-env --help
    No manual entry for nix-env
    ts2@linux-0fiz:/nix$ uname -a
    Linux linux-0fiz 3.16.7-29-desktop #1 SMP PREEMPT Fri Oct 23 00:46:04 UTC 2015 (6be6a97) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:/nix$ nix-instantiate '<nixpkgs>' -A hello
    error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I)
    ts2@linux-0fiz:/nix$ which nix-env 
    /home/ts2/inst/nix/bin/nix-env
    ts2@linux-0fiz:/nix$ date
    Sat Nov 21 22:56:31 EET 2015
    ts2@linux-0fiz:/nix$ hello
    Hello, world!
    ts2@linux-0fiz:/nix$ which hello
    /home/ts2/.nix-profile/bin/hello
    ts2@linux-0fiz:/nix$

**Comment by martinvahi** [comment]
Well, my suspicion about the lack of tests before commits seems to hold. I downloaded the 2015_11_22 early morning version of the Nix src from GitHub and the compilation failed.

    ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/lemmestega_seonduv/Nix_projektid/kompil/v2015_11_21_Nix$ ./configure --prefix=/home/ts2/inst/nix 
    configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
    checking for a sed that does not truncate output... /usr/bin/sed
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking for the canonical Nix system name... x86_64-linux
    checking for gcc... clang
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether clang accepts -g... yes
    checking for clang option to accept ISO C89... none needed
    checking whether we are using the GNU C++ compiler... yes
    checking whether clang++ accepts -g... yes
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    checking for pubsetbuf... yes
    checking for chroot... yes
    checking for unshare... yes
    checking for statvfs... yes
    checking how to run the C preprocessor... clang -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking sched.h usability... yes
    checking sched.h presence... yes
    checking for sched.h... yes
    checking sys/param.h usability... yes
    checking sys/param.h presence... yes
    checking for sys/param.h... yes
    checking for sys/mount.h... yes
    checking sys/syscall.h usability... yes
    checking sys/syscall.h presence... yes
    checking for sys/syscall.h... yes
    checking for lutimes... yes
    checking for sched_setaffinity... yes
    checking whether it is possible to create a link to a symlink... yes
    checking how to run the C++ preprocessor... clang++ -E
    checking locale usability... yes
    checking locale presence... yes
    checking for locale... yes
    checking err.h usability... yes
    checking err.h presence... yes
    checking for err.h... yes
    checking linux/fs.h usability... yes
    checking linux/fs.h presence... yes
    checking for linux/fs.h... yes
    checking for curl... /usr/bin/curl
    checking for bash... /bin/bash
    checking for patch... /usr/bin/patch
    checking for xmllint... /usr/bin/xmllint
    checking for xsltproc... /usr/bin/xsltproc
    checking for flex... /usr/bin/flex
    checking for bison... /usr/bin/bison
    checking for perl... /usr/bin/perl
    checking for sed... /usr/bin/sed
    checking for tar... /bin/tar
    checking for bzip2... /usr/bin/bzip2
    checking for gzip... /usr/bin/gzip
    checking for xz... /usr/bin/xz
    checking for dot... /usr/bin/dot
    checking for dblatex... /usr/bin/dblatex
    checking for pv... /usr/bin/pv
    checking whether Perl is recent enough... yes
    checking for the Perl installation prefix... ${exec_prefix}/lib64/perl5/site_perl/5.20.1/x86_64-linux-thread-multi
    checking for cat... /usr/bin/cat
    checking for tr... /usr/bin/tr
    checking for openssl... /usr/bin/openssl
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for OPENSSL... yes
    checking for BZ2_bzWriteOpen in -lbz2... yes
    checking bzlib.h usability... yes
    checking bzlib.h presence... yes
    checking for bzlib.h... yes
    checking for SQLITE3... yes
    checking for LIBCURL... yes
    checking for SODIUM... yes
    checking for LIBLZMA... yes
    checking whether DBD::SQLite works... yes
    checking whether WWW::Curl works... yes
    checking for otool... no
    checking that otool works... not needed
    checking whether to build the Perl bindings... yes
    checking for setresuid... yes
    checking for setreuid... yes
    checking for lchown... yes
    checking for strsignal... yes
    checking for posix_fallocate... yes
    checking for nanosleep... yes
    checking for sysconf... yes
    checking if you have a recent GNU tar... yes
    configure: creating ./config.status
    config.status: creating config.h
    ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/lemmestega_seonduv/Nix_projektid/kompil/v2015_11_21_Nix$ time nice -n20 make
      GEN    Makefile.config
      GEN    doc/manual/version.txt
      GEN    doc/manual/manual.xmli
      GEN    doc/manual/manual.is-valid
    I/O error : Attempt to load network entity http://docbook.org/xml/5.0/rng/docbook.rng
    warning: failed to load external entity "http://docbook.org/xml/5.0/rng/docbook.rng"
    Relax-NG parser error : xmlRelaxNGParse: could not load http://docbook.org/xml/5.0/rng/docbook.rng
    Relax-NG schema http://docbook.org/xml/5.0/rng/docbook.rng failed to compile
    -:1: parser error : Document is empty
    
    ^
    -:1: parser error : Start tag expected, '<' not found
    
    ^
    doc/manual/local.mk:29: recipe for target 'doc/manual/manual.is-valid' failed
    make: *** [doc/manual/manual.is-valid] Error 1
    
    real	0m0.655s
    user	0m0.202s
    sys	0m0.150s
    ts2@linux-0fiz:~/Projektid/progremise_infrastruktuur/lemmestega_seonduv/Nix_projektid/kompil/v2015_11_21_Nix$

Within my limited capabilities I might try to help with deliverables, but I can not do anything about the habits of other people. Right now I do not know, if the [GNU Guix](http://www.gnu.org/software/guix/) is any better, but I'll experiment with it. I guess that regardless of the state of the GNU Guix project it still takes some time, till the Nix project people get their social aspects sorted out. It is possible that I have misunderstood something again, but I have not noticed that there would be a Git repository for "stable" code or, "release candidates" code, something that new developers could download as a WORKING example to learn and dig into.

**Comment by copumpkin** [comment]
Check github.com/NixOS/nixpkgs-channels if you want git refs that match stable/tested versions.

**Comment by vcunat** [comment]
@martinvahi: nix-1.10 compiles fine if you set up the environment correctly, i.e. `nix-build -A nix` works in nixpkgs. (And many people seem to be using it.) In your case you were missing some docbook stuff needed for documentation.

**Comment by martinvahi** [comment]
Thank You for the answers and thank You for the [link](https://github.com/NixOS/nixpkgs-channels). I'm just trying to figure out, how to use the link. The way I currently understand the "channels" concept, a channel is basically a "bookmark collection" that tells, where the packages are. However, when I look at the [MANIFEST](http://nixos.org/releases/nixpkgs/nixpkgs-16.03pre71923.3087ef3/MANIFEST) file of the nixpkgs-unstable, then it contains keywords like NarURL, NarHash and when I search for those keywords from the [Nix manual](http://nixos.org/nix/manual/), the keywords are not even mentioned at the manual. On the other hand, the aforementioned [https://github.com/NixOS/nixpkgs-channels](https://github.com/NixOS/nixpkgs-channels) does not contain any MANIFEST file either, which hints that I should assemble my own MANIFEST file, if I want to use the [https://github.com/NixOS/nixpkgs-channels](https://github.com/NixOS/nixpkgs-channels). 

Could You please write, if there are any solutions smarter than the one that I just planned?

http://nixos.org/releases/nixpkgs/nixpkgs-16.03pre71923.3087ef3/MANIFEST

**Comment by vcunat** [comment]
- Our manifest files are superseded by binary caches nowadays.
- The nixpkgs-channels repository are just branches pointing into versions of nixpkgs repository that were put into the binary cache (after builds and tests succeeded). Therefore the two repositories are "used the same way". Our binary cache is one and shared by all channels/branches.

**Comment by martinvahi** [comment]
Thank You for the binary cache related reply. I gather that the Nix manual section that talks about channels is then out of date. Is there any way to contribute documentation without using DocBook? To put it directly, editing some archaic, custom semantics based, XML and setting up a  complex development environment just to write structured text with image based illustrations and links is a waste of my time, so DocBook is certainly not an option for me. LaTeX is acceptable, because I can edit that with a plain text editor and see the generated PDF or DVI with a single console command. The [GNU TeXmacs](http://www.texmacs.org/tmweb/home/welcome.en.html) is also attractive.

The way I remember the discussion from the Nix mailing list, people wanted to kill the wiki, because uninformed contributers write uninformed claims there. They also wanted to keep the documentation "near the source". The [Fossil](http://fossil-scm.org/) places the whole central repository, bugtrack, wiki with all its history, code submissions with all the history, users-and-passwords to a single file. It is also possible to "clone" the Fossil repository so that it contains everything public, but lacks the info about users and passwords. The "clone" can be placed to the documentation folder of the Nix package manager and the the [Fossil](http://fossil-scm.org/) is actually really stable, compiles to a single binary that can be hosted as a CGI-script or it can be run as a wiki-serving-web-server on localhost by giving the "clone" as one of its console arguments. As a matter of fact, I even host a [separate Fossil repository](http://business.softf1.com/flaws/en/)*(You might try "raudrohi", "sirel", "kibuvits")* for all of my open source projects and client projects and at the end of the client project I give the client a copy of the Fossil repository file that contains all bug reports (with history), wiki (with history), central code repository, etc. That is to say, the Fossil is really great and might be a solution for the Nix documentation project. If people would just accept it.

**Comment by vcunat** [comment]
> I gather that the Nix manual section that talks about channels is then out of date.

There seems nothing wrong about [the manual section](http://nixos.org/nix/manual/#sec-channels). It's mentioned (in a few words) that channels contain a manifest, and they still do, I think, only it's not really relevant for nowadays usage.

> Is there any way to contribute documentation without using DocBook?

I think @domenkozar wrote some parts in some markdown-like format, but most is in DocBook (which is a format quite often used for technical docs). There are various convertors, so you might well write in anything else and then jut export.

> That is to say, the Fossil is really great and might be a solution for the Nix documentation project.

Switching from git to fossil seems extremely unlikely in near future. There would have to be much clearer advantages to go with another switch. And I remember fossil *was* considered when we were switching svn -> git(hub).

**Comment by martinvahi** [comment]
As of 2015_11_25 it seems to me that there is no point on working on the package collection related issues before the package maintenance part, the Nix, has been fixed at least to the extent thet the [#718](https://github.com/NixOS/nix/issues/718) has been fixed. I'm not sure, what the tag of the current flaw report should be, but a word **"pending"** might suit.

**Comment by peti** [comment]
Personally, I would prefer if this discussion moved to the nix-dev mailing list. Github issues are really a poor forum for technical discussions.
