### ISSUE TITLE
[gitlab-runner] `services.gitlab-runner.services.<name>.registrationConfigFile` ends up in the nix store

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#111746]
**Describe the bug**
A file that is explicitly created to contain secrets, namely the `REGISTRATION_TOKEN` for new gitlab runners ends up in the nix store

**To Reproduce**
1. register a gitlab runner with the module

**Expected behavior**
Secrets don't end up in the nix store

**Screenshots**
```
#!/nix/store/a3fc4zqaiak11jks9zd579mz5v0li8bg-bash-4.4-p23/bin/bash
export CONFIG_FILE=$HOME/.gitlab-runner/config.toml

mkdir -p $(dirname $HOME/.gitlab-runner/config.toml)

# remove no longer existing services
gitlab-runner verify --delete

# current and desired state
NEEDED_SERVICES=$(echo [redacted]_2eb9db2bdcdd | tr " " "\n")
REGISTERED_SERVICES=$(gitlab-runner list 2>&1 | grep 'Executor' | awk '{ print $1 }')

# difference between current and desired state
NEW_SERVICES=$(grep -vxF -f <(echo "$REGISTERED_SERVICES") <(echo "$NEEDED_SERVICES") || true)
OLD_SERVICES=$(grep -vxF -f <(echo "$NEEDED_SERVICES") <(echo "$REGISTERED_SERVICES") || true)

# register new services
if echo "$NEW_SERVICES" | grep -xq [redacted]; then
  bash -c 'set -a && source /nix/store/g66mg8nnahgf0q76x8qi97zs3awqyciw-[redacted].registration && \
 gitlab-runner register \
 --non-interactive \
 --name [redacted]_2eb9db2bdcdd \
[...]
```
Contents of  `/nix/store/g66mg8nnahgf0q76x8qi97zs3awqyciw-[redacted].registration`:
```
CI_SERVER_URL=https://gitlab.[redacted].de/
REGISTRATION_TOKEN=[redacted]
SSH_USER=mainsite
SSH_HOST=localhost
SSH_PORT=22
SSH_IDENTITY_FILE=/var/lib/gitlab-runner/.ssh/id_ed25519
```

**Notify maintainers**
@misuzu
@bachp @zimbatm @globin

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94, NixOS, 20.09.2936.90cec09c364 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2936.90cec09c364"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: gitlab-runner
```

**Comment by misuzu** [comment]
> A file that is explicitly created to contain secrets, namely the `REGISTRATION_TOKEN` for new gitlab runners ends up in the nix store

Could you please share your config?

**Comment by pstn** [comment]
```
services.gitlab-runner = {
        enable = true;
        extraPackages = with pkgs; [ git php php74Packages.composer ];
        services."[redacted]" = {
                registrationConfigFile = /var/lib/gitlab-runner/[redacted].registration;
                executor = "ssh";
                
        };
};
```

**Comment by misuzu** [comment]
> services.gitlab-runner = {
>         enable = true;
>         extraPackages = with pkgs; [ git php php74Packages.composer ];
>         services."[redacted]" = {
>                 registrationConfigFile = /var/lib/gitlab-runner/[redacted].registration;
>                 executor = "ssh";
>                 
>         };
> };

Using unquoted paths will always copy them to nix store. You should use `registrationConfigFile = "/var/lib/gitlab-runner/[redacted].registration";` instead of `registrationConfigFile = /var/lib/gitlab-runner/[redacted].registration;`

**Comment by pstn** [comment]
Yes, but there should be a check that this doesn't happen. It's still an information disclosure.

**Comment by misuzu** [comment]
> Yes, but there should be a check that this doesn't happen. It's still an information disclosure.

What if user wants them to be in nix store?

**Comment by misuzu** [comment]
> Yes, but there should be a check that this doesn't happen. It's still an information disclosure.

I could add a warning if `registrationConfigFile` is in `/nix/store`. This will still allow doing whatever user wants to. Should I open pull-request with this change?

**Comment by pstn** [comment]
I think that is a good compromise.

**Comment by misuzu** [comment]
@pstn please take a look at https://github.com/NixOS/nixpkgs/pull/111768

**Comment by mschwaig** [comment]
I appreciate that you did something about this problem.

I also get this warning for my config, which does something like this:
```
let
  registrationTokenFile = "/root/.gitlab/registration_token.txt";
  registrationConfigScript = pkgs.writeShellScript "gitlab-runner-registration" ''
    CI_SERVER_URL=${ciServerUrl}
    REGISTRATION_TOKEN=$(cat "${registrationTokenFile}")
  '';
in {
  services.gitlab-runner = {
    enable = true;
    services = {
      nix = {
        registrationConfigFile = registrationConfigScript;
        [...]
```
In that case the warning is a false positive, because the registration token itself does not actually end up in the store. I think to avoid this problem the secret by itself would have to be represented in its own field as part of the service configuration so that the warning can look at that field by itself. I'm not sure if what I am doing in my config is a good way to make that happen and it's not a universal solution. Usually I would prefer my configs to not run code.

Maybe this can be taken into account as part of some future work, for example if someone implements https://github.com/NixOS/nixpkgs/issues/158284 and changes registration anyways.

It would be great if there was a better solution for this general problem, because even if a user sees the warning and fixes the issue the registration token is already in the store at that point and getting it back out is a pain. Right now probably not even an error would prevent it from ending up in the store.

**Comment by teto** [comment]
I use sops and I've had a related issue where I can only reference the path to the token. I ended up with:
 ```
        registrationConfigFile = "/dev/null";  # nix asks for it
        registrationFlags = [
          "--url ${gitlabUrl}"
          "--token $(cat /run/secrets/${runnerName}/nix)"
        ];
```

**Comment by teto** [comment]
@mschwaig nevermind this seems to break the way the gitlab module works (my module contains 3 runners, the gitlab module creates the 3 but then remove 1 in a cyclic fashion). I will try your solution instead
