### ISSUE TITLE
[20.09] zfs upgrade from 0.8.6 to 2.0.1 fails to mount cloned filesystems without reboot

### ISSUE THREAD

**Issue by thefloweringash** [NixOS/nixpkgs#111872]
**Describe the bug**

After updating nixos-20.09 from 8230a316357f8f87cc4c361510453dc5d99e5fbc to 
90cec09c3642b9be6699015a35e404ecb503aa0d without rebooting (ie, `nixos-rebuild switch`), zfs is unable to mount filesystems cloned from snapshots. 

Attempts to mount fail with
```
cannot mount 'rpool/fs-clone': Dataset is not complete, was created by receiving a redacted zfs send stream
```

This is probably caused by using the old 0.8.6 kernel module with the new 2.0.1 userland. Rebooting will probably solve this problem by syncing the kmod version.

I don't know if this is something to be fixed in nixos so might just be a PSA, but I was surprised to see a version bump of zfs in the stable branch that caused visible breakage.

See also: https://github.com/NixOS/nixpkgs/pull/111020#issuecomment-769476009

**To Reproduce**

<details>
<summary>NixOS Test</summary>

```nix
let
  oldPkgsSrc = builtins.fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/8230a316357f8f87cc4c361510453dc5d99e5fbc.tar.gz";
    sha256 = "0apv1k14ryc09ja8mz5i85nzyhch5cqpgppl16fl0dy4qf3q1qfs";
  };

  newPkgsSrc = builtins.fetchTarball {
    url = "https://github.com/nixos/nixpkgs/archive/90cec09c3642b9be6699015a35e404ecb503aa0d.tar.gz";
    sha256 = "0134xglcwrq8wp4mnxn6byww9pf2iipxghwpm92bdyknf79msdv1";
  };

  newPkgs = import newPkgsSrc {};

  makeZfsTest = { name, nixpkgsSrc, testScript }:
      import (nixpkgsSrc + "/nixos/tests/make-test-python.nix") ({ ... }: {
        name = "zfs-test-${name}";

        nodes = {
          node = { ... }: {
            virtualisation.emptyDiskImages = [ 1024 ];
            networking.hostId = "deadbeef";
            boot.supportedFilesystems = [ "zfs" ];
          };
        };

        testScript = ''
          node.start()
          node.wait_for_unit("multi-user.target")

          node.succeed(
              "modprobe zfs",
              "mkdir /tmp/mnt",
              "zpool create rpool /dev/vdb",
              "zfs create -o mountpoint=none rpool/fs",
              "zfs snapshot rpool/fs@snap",
              "zfs clone rpool/fs@snap rpool/fs-clone",
          )
        '' + testScript;
      });
in
  {
    # Interesting case: a machine running 20.09, upgrading to a newer version
    # of 20.09. zfs kmod is 0.8.6, zfs userland is 2.0.1.

    upgradeTest = makeZfsTest {
      name = "upgrade";
      nixpkgsSrc = oldPkgsSrc;
      testScript = ''
        node.succeed(
            "${newPkgs.zfs}/bin/zfs set mountpoint=/tmp/mnt rpool/fs-clone",
            "${newPkgs.zfs}/bin/zfs mount rpool/fs-clone || true",
            "test $(${newPkgs.zfs}/bin/zfs list -H -o mounted rpool/fs-clone) = yes",
        )
      '';
    };

    # Sanity checks: a machine booted into either the old or new version
    # of 20.09 will succeed the test.

    oldTest = makeZfsTest {
      name = "old";
      nixpkgsSrc = oldPkgsSrc;
      testScript = ''
        node.succeed(
            "zfs set mountpoint=/tmp/mnt rpool/fs-clone",
            "zfs mount rpool/fs-clone || true",
            "test $(zfs list -H -o mounted rpool/fs-clone) = yes",
        )
      '';
    };

    newTest = makeZfsTest {
      name = "new";
      nixpkgsSrc = newPkgsSrc;
      testScript = ''
        node.succeed(
            "zfs set mountpoint=/tmp/mnt rpool/fs-clone",
            "zfs mount rpool/fs-clone || true",
            "test $(zfs list -H -o mounted rpool/fs-clone) = yes",
        )
      '';
    };
  }

```

</details>

**Comment by hmenke** [comment]
ZFS had to be bumped because Linux was bumped to 5.10 and ZFS 0.8.6 only supports Linux 5.9.  The Linux kernel version bump was necessary because 5.9 is EOL.  The stable channel of the Linux kernel doesn't live that long so version bumps are common and frequent.

Regarding your problem, I think this should be reported upstream.  Naively I would expect the new userspace tools to work the old kernel module.

**Comment by thefloweringash** [comment]
> ZFS had to be bumped because Linux was bumped to 5.10 and ZFS 0.8.6 only supports Linux 5.9. The Linux kernel version bump was necessary because 5.9 is EOL. The stable channel of the Linux kernel doesn't live that long so version bumps are common and frequent.

The Linux kernel version in 20.09 (`pkgs.linux`) is 5.4, and as I understand it, is chosen to be the latest LTS at the time of release so that it won't become end of life during the stable lifecycle. The latest version, currently linux 5.10, is also available but it's not a default configuration. Is it reasonable to require that users configuring a non-default kernel must also configure a non-default version of zfs?
 
> Regarding your problem, I think this should be reported upstream. Naively I would expect the new userspace tools to work the old kernel module.

Filed an issue with upstream: https://github.com/openzfs/zfs/issues/11581

**Comment by hmenke** [comment]
The default kernel on the NixOS release channel is always the LTS version which, as you correctly observed is 5.4.96.  However, at the same time the stable channel of the Linux kernel is also always accessible as `linuxPackages_latest`.  Even though that's not the default configuration, users expect that the stable kernel is available and up-to-date.  It's not a good idea to leave the stable kernel hanging at some unsupported release which could potentially accumulated unfixed vulnerabilities just to not break a single out-of-tree kernel module.  So it's kind of your fault for using a filesystem that is not officially supported by Linux. (Don't get me wrong, I'm also using ZFS on all my machines)

**Comment by thefloweringash** [comment]
> The default kernel on the NixOS release channel is always the LTS version which, as you correctly observed is 5.4.96. However, at the same time the stable channel of the Linux kernel is also always accessible as `linuxPackages_latest`. Even though that's not the default configuration, users expect that the stable kernel is available and up-to-date. It's not a good idea to leave the stable kernel hanging at some unsupported release which could potentially accumulated unfixed vulnerabilities just to not break a single out-of-tree kernel module. 

Definitely agreed on all points here. I'm not wanting to hold back kernel versions. If anything I propose to hold back zfs versions, or at least not bump the default zfs version. There's currently `zfs` and `zfsUnstable`. To not introduce a major version bump to 20.09's default configuration, we could have added `zfs2` and add an option that works like `boot.zfs.enableUnstable` to switch to it for configurations using the latest kernel. Not ideal, I admit.

Might as well see what upstream has to say about compatibility, and if this is a bug to be fixed upstream or a configuration to be avoided downstream.

> So it's kind of your fault for using a filesystem that is not officially supported by Linux. (Don't get me wrong, I'm also using ZFS on all my machines)

The friction between the kernel and zfs is quite unfortunate 😞

**Comment by SuperSandro2000** [comment]
Closing as stale as it seems to no longer happen with the last many updates.
