### ISSUE TITLE
OctoPrint build breaks on unstable because of a missing watchdog==0.10.4 dependency

### ISSUE THREAD

**Issue by ronthecookie** [NixOS/nixpkgs#111810]
**Describe the bug**
Building `octoprint` on the latest unstable channel (currently commit https://github.com/NixOS/nixpkgs/commit/fab6fcdceb2560a4ab943830a2b1632458c7a6ff) fails due to pip not being able to find `watchdog==0.10.4`.

**To Reproduce**
1. Update to the latest unstable channel.
2. Run `nix-shell -p octoprint` to trigger a build
3. Observe the breakage (:

**Expected behavior**
I expected the build to not break.

**Screenshots**
`nix-shell -p octoprint`
```
[..cut..]
ERROR: Could not find a version that satisfies the requirement watchdog==0.10.4 (from octoprint)
ERROR: No matching distribution found for watchdog==0.10.4
builder for '/nix/store/4v8asgaqddjq6h37r9i8i2cfiin7w1wg-python3.8-OctoPrint-1.5.3.drv' failed with exit code 1
error: build of '/nix/store/4v8asgaqddjq6h37r9i8i2cfiin7w1wg-python3.8-OctoPrint-1.5.3.drv' failed
```

**Additional context**
- I don't know much about python tooling so I can't fix this on my own. 
- This didn't happen before I updated to the latest unstable. (I was a few weeks behind)

**Notify maintainers**
@abbradar @gebner @WhittlesJr

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 21.03pre267696.fab6fcdceb2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre267696.fab6fcdceb2"`
 - channels(ron): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: octoprint
# a list of nixos modules affected by the problem
module:
```

**Comment by fabaff** [comment]
I updated watchdog to 1.0.2 [recently](https://github.com/NixOS/nixpkgs/pull/111619). In https://github.com/NixOS/nixpkgs/pull/111661/commits/7938f40c354de69a08e3ddfdd75f984abf872739 `octoprint` was made aware of this change yesterday.

**Comment by fabaff** [comment]
The root cause of the problem is that `octoprint is pinning the watchdog release. Let's see if they are willing to lift the version constraint: https://github.com/OctoPrint/OctoPrint/issues/4002

**Comment by ronthecookie** [comment]
Oh it seems I missed https://github.com/NixOS/nixpkgs/commit/7938f40c354de69a08e3ddfdd75f984abf872739 since it hadn't gotten into the unstable branch yet. Sorry about that.

Anyhow, it seems the OctoPrint folks aren't budging so I'll close this issue for now.
