### ISSUE TITLE
Add a label named `needs-documentation`

### ISSUE THREAD

**Issue by nbp** [NixOS/nixpkgs#11180]
I suggest we add a label named `needs-documentation` in a similar way as we have a label named `needs-changelog`.

**Comment by copumpkin** [comment]
@nbp as collaborators on github, we can add our own labels. I just created one called `needs-documentation`. Feel free to change the color :smile:

**Comment by nbp** [comment]
Oh, I did not noticed that I had the right to do that.
Thanks.
