### ISSUE TITLE
systemd Capabilities issue

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#11184]
i want to start Transmission on port 80 and it runs as unprivileged user, so i added *CAP_NET_BIND_SERVICE* capabilitie like in the [diod module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/network-filesystems/diod.nix#L156) (there it works btw.)

here is my branch: https://github.com/davidak/nixpkgs/commit/1a9e6adcd9958faada7938661a5423ddc631ad05

the line in the systemd service definition looks the same.

but i get this error:
`systemd[1]: [/nix/store/yw21nmpzwzsvqjs6b7rmg75jddzihi0k-unit-transmission.service/transmission.service:12] Failed to parse capabilities, ignoring: cap_net_bind_service+=ep`

which is defined here: https://github.com/systemd/systemd/blob/master/src/core/load-fragment.c#L966

**Comment by nbp** [comment]
cc @ts468

**Comment by zimbatm** [comment]
still valid ?

**Comment by joachifm** [comment]
Shouldn't it be `=+pe`? Maybe I'm just failing at reading, but my interpretation of the docs is that the `+` operator must be followed by one or more flags, whereas `=` is an operator.

**Comment by joachifm** [comment]
Am I right that diod runs as root anyways? If so perhaps that's why it appears to work there but not for transmission.

**Comment by joachifm** [comment]
Hm, I wonder if `Capabilities` supports that syntax at all; `cap_from_text()` would, but systemd uses `cap_from_name()`. Setting `serviceConfig.AmbientCapabilities = "cap_net_bind_service"` works for me. I can then run transmission as an unprivileged user, listening and responding to queries on port 80. Tested with `curl localhost:80`.

**Comment by zimbatm** [comment]
Nice. Would it be worth adding it to the NixOS doc ? I don't find AmbientCapabilities when search on nixos.org

**Comment by joachifm** [comment]
Sure, or perhaps dump it into a nixos-config-snippets kind of repo (perhaps one exists already?)

**Comment by joachifm** [comment]
I wonder if the service API should make this more convenient and discoverable for people who have not and do not want to spend too much time reading `systemd.exec(5)` and friends. I think that'd encourage service writers to minimize privileges &c to a greater extent than what we currently see in NixOS.

**Comment by joachifm** [comment]
Perhaps we should open a separate issue for this? A good first step would be writing a brief section on "useful" systemd directives, which could be a part of the chapter that describes how to write a new service.

**Comment by joachifm** [comment]
Closing, I believe this issue is a mis-configuration problem.

**Comment by davidak** [comment]
@joachifm thanks. the service starts with port 80 but don't bind it. i opened the firewall and tryed rebooting.

**Comment by joachifm** [comment]
I tested it in a vm, worked for me.

**Comment by joachifm** [comment]
I re-checked: lsof reports that the daemon indeed is listening on `*:80`. It also indicates that transmission is listening for inet connections on the rpc port as well, which I think is somewhat of a concern ... but that's a different issue entirely.

**Comment by joachifm** [comment]
At any rate, you're probably better served by `proxy_pass`ing from nginx to transmission than exposing transmission to `*:80` directly.

**Comment by davidak** [comment]
```
Unknown lvalue 'AmbientCapabilities' in section 'Service'
```

I have systemd 227 (at my working branch of this issue), this setting came in 229.
