### ISSUE TITLE
package neovide: a fancy rust neovim GUI

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#111972]
**Project description**
neovide is a rust GUI for neovim with some fancy effects (cursor/emojis).

Its author has found some bugs in neovim (for instance https://github.com/neovim/neovim/issues/13416) I would like to fix and I would like to be able to run the project to test my fixes.

I've picked up https://gist.github.com/theotherjimmy/d830cc971c9a9c4f0385eb7bd687d814 and added it in my overlay with some fixes
https://github.com/teto/home/commit/c781bd443e4caee85a0af14951a95b23e667ddcc
but it fails with
```
   Compiling rust-embed v5.5.1
   Compiling wayland-commons v0.23.6
   Compiling futures-util v0.3.4
   Compiling pathfinder_geometry v0.5.1
   Compiling andrew v0.2.1
   Compiling pin-project v0.4.9
error: failed to run custom build command for `sdl2-sys v0.33.0`

Caused by:
  process didn't exit successfully: `/build/source/target/release/build/sdl2-sys-1b04d26a935d8406/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Error running command 'curl': No such file or directory (os error 2)', /build/neovide-0.6.0-vendor.tar.gz/sdl2-sys/build.rs:50:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
note: keeping build directory '/tmp/nix-build-neovide-0.6.0.drv-0'
```

**Metadata**

* homepage URL: https://github.com/Kethku/neovide
* source URL: https://github.com/Kethku/neovide
* license: mit 
* platforms: unix, linux, darwin, ...

**Comment by teto** [comment]
I managed to remove this error by removing some platform dependant sdl2 commands in cargo.toml. Still blocked on a fontconfig error https://github.com/Kethku/neovide/issues/465

**Comment by Ninlives** [comment]
Hi, is there a buildable version now?

**Comment by teto** [comment]
nope you can check the linked issue, it's difficult.

**Comment by teto** [comment]
packaged in linked PR
