### ISSUE TITLE
Wanna have some audio packages

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11190]
Currently _NixOS_ miss some important packages for **audio**. Would be really glad and grateful if someone find some time to write derivations for it. Bellow a little list of some of this packages:
- Patch bay [patchage](http://drobilla.net/software/patchage/)
- Session [ladish gladish](https://github.com/LADI/ladish)
- Session [claudia](http://kxstudio.linuxaudio.org/Applications:Claudia)
- Spectrogram [baudline](http://www.baudline.com/)
- Spectrogram [spectrojack](http://sed.free.fr/spectrojack/)
- LV2 rack [zynjacku lv2rack](http://home.gna.org/zynjacku/)
- Audio editor [laoe](http://www.oli4.ch/laoe/download.html)
- Mastering [jamin](http://jamin.sourceforge.net/en/about.html)
- Mixer [luppp](http://openavproductions.com/luppp/)
- Graphical sequencer [iannix](http://www.iannix.org/en/)
- Graphical sequencer [algoscore](http://kymatica.com/Software/AlgoScore)
- Intonation sequencer [rationale](http://rationale.sourceforge.net/)
- Modular synth [galan](http://galan.sourceforge.net/)
- Plugins rack [carla](http://kxstudio.linuxaudio.org/Applications:Carla)
- Modular DAW [non_sequencer non_mixer non_timeline nsm](http://non.tuxfamily.org/)
- Audio editor [reZound](http://sourceforge.net/projects/rezound/)

Regards, have a nice... Time of the day :)

**Comment by nbp** [comment]
Hi @Pitometsu , feel free to start packaging these as the best person capable of packaging software is the person who is relying on it.  We have a lot of documentation which explains how you can do that [1], and if you have any issue the Nix community is usually reactive on IRC (freenode #nixos).

[1] http://nixos.org/nixpkgs/manual/#chap-quick-start

**Comment by Pitometsu** [comment]
@nbp thank you for reference, just leave this here for now.
Will implement it as soon as became strong enough for it.

**Comment by Mathnerd314** [comment]
I was curious so I looked at baudline and what other distros have done:
* Debian examined it and wontfix'd it after finding out it wasn't GPL
* Gentoo has had an [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-sound/baudline/baudline-1.08-r1.ebuild) for some time
* Arch has had a [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=baudline-bin) for some time
* OpenSUSE has had various people write specfiles, most recent seems to be [this](https://build.opensuse.org/package/view_file/home:mnhauke:sdr/baudline/baudline.spec?expand=1)
* Slackware has some [user repo](http://packages.slackonly.com/pub/packages/14.1-x86_64/ham/baudline/) in flagrant violation of the license
* FreeBSD has a [distfile](https://svnweb.freebsd.org/ports/head/audio/baudline/)
* Other distros don't exist as far as baudline is concerned

**Comment by bjornfor** [comment]
baudline is in nixpkgs master.

**Comment by Mathnerd314** [comment]
Interesting. I guess I missed that and http://bugtraq-team.com/, they were on page 30 or so of Google.

**Comment by magnetophon** [comment]
@Pitometsu
Thanks for the tips, I didn't know about a ot of these.
Most of them seem old and unmaintained though.
Tbh I have a hard time imagening you're using all of these.
Could you tell us which ones you use (most)?
For example do we really want baudline and spectrograph when we already have [jaaa](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/jaaa/default.nix) ?

**Comment by Pitometsu** [comment]
@magnetophon welcome!
Most of them I used for fun some time ago, some just wish to try.
About spectrogram: jaaa different. It plot just wave at this moment, not history of wave.
Baudline bad, old, proprietary, but it's best spectrogram tool for Linux :(
And even baudline have disadvantage: it's linear, for audio better logarithmic. There is one calf analyzer lv2 plugin with spectrogram, but it looks more like a toy :(

I think, JaMin, Claudia, Carla, and Non DAW  most interesting packages from this list.

**Comment by Pitometsu** [comment]
@Mathnerd314 @bjornfor thanks for *baudline*!

**Comment by magnetophon** [comment]
@Pitometsu 
Oh, almost forgot: I have a [WIP pkg](https://github.com/magnetophon/nixpkgs/blob/carla/pkgs/applications/audio/carla/default.nix) for Carla.

**Comment by Pitometsu** [comment]
@magnetophon would u make PR then?

**Comment by magnetophon** [comment]
@Pitometsu
Well, it's Work In Progress, it doesn't actually do anything yet.

**Comment by joelmo** [comment]
I have a working derivation for carla. Some patches for the python scripts is needed for the guis to work. I can post them when i come home. I also have working derivations for airwave and wineasio if its interesting. These havent been accepted in nixpkgs because of nonfree dependencies.

**Comment by joelmo** [comment]
Here is carla, https://github.com/joelmo/pkgs/blob/master/carla/default.nix

**Comment by Pitometsu** [comment]
@joelmo awesome, thanks a lot for your work!

**Comment by joelmo** [comment]
@Pitometsu np :). After you have test them, feel free to submit them to nixpkgs, carla should be accepted at least. I used them ~2 months ago but should still work against unstable.

**Comment by magnetophon** [comment]
@joelmo thanks!

**Comment by nico202** [comment]
i added "[https://github.com/NixOS/nixpkgs/blob/eaf10642093ba652d536f4b8fd9ba7526c69886a/pkgs/applications/audio/non/default.nix](non)" some time ago.
I think I'll add jamin and patchage when I can.
Why carla has still not been mereged?

**Comment by sleexyz** [comment]
i added spectrojack
https://github.com/NixOS/nixpkgs/pull/12964

**Comment by nico202** [comment]
I added jamin #12951, timemachine #12959  and patchage #12955

**Comment by nico202** [comment]
Iannix #12965

**Comment by magnetophon** [comment]
Thanks @nico202 and @sleexyz !

**Comment by bjornfor** [comment]
@Pitometsu: It seems some packages from your original list has been integrated into nixpkgs. Care to update the list of packages you still miss (if relevant)?

**Comment by Pitometsu** [comment]
Thanks a lot for all added packages!

Here what missed in nixpkgs yet:

- claudia
- ladish & gladish
- laoe
- carla (not in master yet)
- algoscore
- zynjacku & lv2rack

Propose to keep this issue open for audio packages discussions.

**Comment by Profpatsch** [comment]
triage: what’s the current status?
