### ISSUE TITLE
Modemmanager systemd service missing?

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#11197]
I'm on 16.03pre71289.7ae05ed, amd64.

I wanted to use 4g modem but have some problems with it. I added modemmanager to system packages in /etc/nixos, the package is installed but looks like service is missing, there is no configuration option to enable it and there is no systemd service despite the fact that service provides systemd service file.

Am I missing something?

Similar problem I have with geoclue2 package, but this is even more fun.
The geoclue2 package provides systemd serivce and provides configuration option: ``services.geoclue2.enable``. Despite the fact I enabled it and added manually to system packages as well I don't have geoclue2 service in my system :(

**Comment by lethalman** [comment]
You don't install services just by adding them to system packages. Try
enabling the networkmanager service, that one should also expose
modemmanager.

On Sun, Nov 22, 2015 at 12:03 AM, Tomasz Czyż <notifications@github.com>
wrote:

> I'm on 16.03pre71289.7ae05ed, amd64.
>
> I wanted to use 4g modem but have some problems with it. I added
> modemmanager to system packages in /etc/nixos, the package is installed but
> looks like service is missing, there is no configuration option to enable
> it and there is no systemd service despite the fact that service provides
> systemd service file.
>
> Am I missing something?
>
> Similar problem I have with geoclue2 package, but this is even more fun.
> The geoclue2 package provides systemd serivce and provides configuration
> option: services.geoclue2.enable. Despite the fact I enabled it and added
> manually to system packages as well I don't have geoclue2 service in my
> system :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/11197>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by spinus** [comment]
yep, it's enabled and working (I'm using it for wifi).

**Comment by lethalman** [comment]
So you should have it running: systemctl status ModemManager

On Sun, Nov 22, 2015 at 12:29 AM, Tomasz Czyż <notifications@github.com>
wrote:

> yep, it's enabled and working (I'm using it for wifi).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/11197#issuecomment-158690339>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by spinus** [comment]
```
grep -i network /etc/nixos -R
/etc/nixos/modules/network-wifi.nix:  networking.wireless.enable = false;
/etc/nixos/modules/network-wifi.nix:  networking.networkmanager.enable = true;
```
```
# systemctl | grep -i network-manager
  network-manager.service                                                                  loaded active running   Network Manager
```
```
# systemctl |grep -i modem
<empty> - that's why I thought it's not loaded
```
```
systemctl status ModemManager
● ModemManager.service - Modem Manager
   Loaded: loaded (/nix/store/lq10njq3fdwdjhwhkx5jpz9swx6mwcsm-ModemManager-1.4.6/etc/systemd/system/ModemManager.service)
   Active: inactive (dead)
```
after manual ``systemctl start`` it's working.

Looks like it's not enabled by default?

**Comment by lethalman** [comment]
I think it should be auto activated if something tries to
access org.freedesktop.ModemManager1 . Also it should be renamed to
modem-manager.

On Sun, Nov 22, 2015 at 12:37 AM, Tomasz Czyż <notifications@github.com>
wrote:

> grep -i network /etc/nixos -R
> /etc/nixos/modules/network-wifi.nix:  networking.wireless.enable = false;
> /etc/nixos/modules/network-wifi.nix:  networking.networkmanager.enable = true;
>
> # systemctl | grep -i network-manager
>   network-manager.service                                                                  loaded active running   Network Manager
>
> # systemctl |grep -i modem
> <empty> - that's why I thought it's not loaded
>
> systemctl status ModemManager
> ● ModemManager.service - Modem Manager
>    Loaded: loaded (/nix/store/lq10njq3fdwdjhwhkx5jpz9swx6mwcsm-ModemManager-1.4.6/etc/systemd/system/ModemManager.service)
>    Active: inactive (dead)
>
> after manual systemctl start it's working.
>
> Looks like it's not enabled by default?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/11197#issuecomment-158690843>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by spinus** [comment]
I agree that it should :-)
btw, shouldn't that have separate service.modem-manager.enable option (I can imaging that not everyone needs that).

**Comment by lethalman** [comment]
It's just shipped with NM, and nobody complained about it :)

On Sun, Nov 22, 2015 at 12:44 AM, Tomasz Czyż <notifications@github.com>
wrote:

> I agree that it should :-)
> btw, shouldn't that have separate service.modem-manager.enable option (I
> can imaging that not everyone needs that).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/11197#issuecomment-158691216>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by spinus** [comment]
looks like I'm "nobody" :-)

anyway, I'm using network manager with nixos on 3 different machines and all work the same way (ModemManager service is "dead" from the start). I did just small grepping in /etc/udev and probably there are some udev rules to activate modem manager only where needed, or udev/systemd integrations which are activating that.

For me those rule are not working as I'm using Huawei E3372 and in nixos there are no udev rules to handle that mdodem. Looks like I had to do "usb_modeswitch" to make modem properly detected. Hence my problems with it.

**Comment by lethalman** [comment]
@spinus the modemmanager service is activated when someones tries to use `org.freedesktop.ModemManager1` in dbus. 

geoclue2 works the same way, the service is auto activated only when `org.freedesktop.GeoClue2` is used.

See http://dbus.freedesktop.org/doc/system-activation.txt

**Comment by gebner** [comment]
I had to enable ModemManager manually as well using `systemd.services.ModemManager.enable = true`, otherwise my built-in modem wouldn't show up in nm-applet.

This is on a Lenovo T450s:
```
$ lsusb | grep Ericsson
Bus 001 Device 081: ID 0bdb:193e Ericsson Business Mobile Networks BV
```

**Comment by lethalman** [comment]
Is there anything up in journalctl ? If  `nm-applet` is trying to contact ModemManager via dbus, it should have been automatically started by auto activation.

**Comment by gebner** [comment]
I don't think nm-applet calls ModemManager directly, it just waits for the interfaces to pop up in NetworkManager, which only happens if ModemManager is running.

**Comment by spinus** [comment]
@lethalman thank you for clarification. It looks like there are no proper dbus/udev rules to support my modem and that's why it's not activated.

btw, geoclue2 is not working but I use redshift which requires dbus for geoclue2 and is says geoclue2 is not present instead of activating it, so looks like somehing is broken here.

@gebner I was looking in manual for modem (for ModemManager) but looks like it was added in new version and that's why I couldn't find it :(, I'll add this as well, thank you for tip.

**Comment by lethalman** [comment]
@spinus maybe redshift checks for the existence of the dbus path, instead of calling it directly?

Btw for all those cases where the dbus api is not called, you can just add a `wantedBy = [ "multi-user.target" ];` in the respective service. Auto activation is a good thing for not cluttering up the system, so it's up to the apps using those services.

If you have evidence that the dbus api is indeed called, and that the service does not start, feel free to reopen this issue. Closing for now.

**Comment by spinus** [comment]
@lethalman cool. I'll check how redshift is using that dbus stuff and compare it to debian (I think it was working there for me).

For modem: I'm not sure why it's not starting but as I wrote I assume that some activation rules are missing, I'll try to look at this as well.

Thank you for help.

**Comment by abcdw** [comment]
Also has a problem with ModemManager, I have to start it manually to see my wwan device and connections.

**Comment by spinus** [comment]
@abcdw try to add     mobile_broadband_provider_info     usb-modeswitch    usb-modeswitch-data
packages which provide udev rules and boradband info.

**Comment by arximboldi** [comment]
I have this problem on latest NixOS. I have also `mobile_broadband_provider_info usb-modeswitch usb-modeswitch-data` in NixOS as suggested. I use network manager via `nm-cli`. Also:
```
mmcli -L
error: couldn't find the ModemManager process in the bus
```
I need to manually `systemctl start modem-manager` for things to work.

**Comment by arximboldi** [comment]
I have tried `systemd.services.modem-namager.enable = true` without success.

**Comment by arximboldi** [comment]
Ok, found a workaround, invoke this as part of my session start:
```
dbus-send --system --dest=org.freedesktop.ModemManager1 --print-reply /org/freedesktop/ModemManager1 org.freedesktop.DBus.Introspectable.Introspect
```
Not really nice though, I think it would be nice to have an `option` to unconditionally launch the service on boot.
