### ISSUE TITLE
*FlagsArray do not work as people expect them to

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#112054]
**Describe the bug**

`buildGoModule` ignores `buildFlagsArray`

For example `nebula` is built without `-ldflags='-X main.Build=${version}'` despite the instruction
https://github.com/NixOS/nixpkgs/blob/bff1304ec286592736aafc9db3e4c449d57be76d/pkgs/tools/networking/nebula/default.nix#L20

**To Reproduce**
```
$(nix-build -E "with (import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/master.tar.gz) {}); nebula")/bin/nebula -version
$(nix-build -E "with (import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/release-20.09.tar.gz) {}); nebula")/bin/nebula -version
$(nix-build -E "with (import (builtins.fetchTarball https://github.com/NixOS/nixpkgs/archive/release-20.03.tar.gz) {}); nebula")/bin/nebula -version
```

**Expected behavior**
```
Version: 1.3.0
```

**Screenshots**
```
Version: 
```

**Notify maintainers**
@zowoq @flokli @c00w @kalbasit @marsam @basvandijk @Mic92 @Br1ght0ne

**Metadata**
reproducible with `release-20.03`, `release-20.09` and `master`

**Comment by Mic92** [comment]
It is not ignored in general for other packages i.e. glow:

```
nix-shell -p glow --run 'glow --version'
```

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/112104

**Comment by kvtb** [comment]
> It is not ignored in general for other packages i.e. glow:
> 
> ```
> nix-shell -p glow --run 'glow --version'
> ```

No, this is not a `nebula` derivation bug, `nebula` just a symptom
If another package works that means it might have a workaround for the bug like one you did in #112104

There is still a mismatch between `buildFlagsArray` and `go build` command line

If I run `go build` manually:
1. `go build -ldflags='-X main.Build=${version}'  ./cmd/nebula` <-- this works
2. `go build -ldflags '-X main.Build=${version}'  ./cmd/nebula` <-- this works
3. `go build -ldflags= '-X main.Build=${version}' ./cmd/nebula` <-- fails with "flag provided but not defined: -X main.Build"

You did the #112104 fix by switching correct flags (1) to invalid (3)
That means `buildFlagsArray` gets passed to `go build` command line in damaged form

**Comment by kvtb** [comment]
It should be fixed in `buildGoModule` code, and nebula "fix" is to be reverted.

**Comment by kvtb** [comment]
please reopen

**Comment by Mic92** [comment]
Can you provide a pull request with a fix? I don't see why I should revert the fix for nebula. It now correctly displays the version.

**Comment by kvtb** [comment]
Who cares how nebula displays the version?
It is too minor an issue to fix.

The real issue is:
1. `buildFlagsArray = [ "-ldflags='-X main.Build=${version}'" ];` resulted in empty version
2. `buildFlagsArray = [ "-ldflags=" "'-X main.Build=${version}'" ];` resulted in build success (should be build error)

**Comment by kvtb** [comment]
I suspect `'` symbol is not escaped properly when passed to bash

**Comment by Mic92** [comment]
> Who cares how nebula displays the version?
> It is too minor an issue to fix.

Sorry for wasting your time. Please don't ping me in future.

**Comment by kvtb** [comment]
`buildFlagsArray = [ "-ldflags=" "-X main.Build=${version}" ];` is definitively wrong,
because `go build -ldflags= '-X main.Build=${version}' ./cmd/nebula` fails with "flag provided but not defined: -X main.Build".
Those flags should not work at all.

Even if it fixes the minor issue with nebula version, it is working around of bash escaping bug by adding another bug.
I see very suspicious the hurry that PR has been merged, it is like someone needs the bash escaping bug to be kept (perhaps, for the purposes of backdooring or a supply chain attack)

**Comment by grahamc** [comment]
> I see very suspicious the hurry that PR has been merged, it is like someone needs the bash escaping bug to be kept (perhaps, for the purposes of backdooring or a supply chain attack)

This is preposterous. If you find a credible problem, please report it to the NixOS Security Team.

**Comment by yorickvP** [comment]
Yes, this looks like a `buildGoModule` bug and we'd be happy to merge a fix for that. In the meantime, I don't think we should refuse to work around it, since that would cause breakage for users.

**Comment by jtojnar** [comment]
This is not just `buildGoModule` issue,  it happens with `stdenv.mkDerivation` too.

If you pass a list of strings to `mkDerivation`, Nix will intercalate the elements with spaces and pass the whole list to the builder as a single string. The builder will then only be able to extract a single item from `"${buildFlagsArray[@]}"`, containing all elements of the list concatenated together.

That means the single quotes in the original value got passed as literals (bash does not really interpret the values of variables passed to derivations), which is why it did not work. The [“fixed”](https://github.com/NixOS/nixpkgs/pull/112104) nebula only works because it actually resolves into a single flag (even if the new quoting in the Nix expression is misleading).

That is why I recommend using `buildFlags` in Nix if you are certain your list items do not contain spaces. If any of them may contain spaces, you will have to switch to setting `buildFlagsArray` in Bash (e.g. in `preBuild`). Unfortunately, we cannot really do any better until we switch to [`__structuredAttrs`](https://github.com/NixOS/nixpkgs/pull/72074).

**Comment by kalbasit** [comment]
Perhaps `buildGoModule` should expose ldflags as a list, and abstracts away the buildFlagsArray?

**Comment by kalbasit** [comment]
> Perhaps `buildGoModule` should expose ldflags as a list, and abstracts away the buildFlagsArray?

Anothet reason why I think this might the right way to go is to abstract away the -s and -w flags we ask package maintainers to set on their packages.

**Comment by jtojnar** [comment]
For now, I opened a PR adding a lint for this to nixpkgs-hammering: https://github.com/jtojnar/nixpkgs-hammering/pull/30

**Comment by kvtb** [comment]
> Unfortunately, we cannot really do any better until we switch to [`__structuredAttrs`](https://github.com/NixOS/nixpkgs/pull/72074).

Isn't it just a case to find implicit List's `toString` and replace it with `lib.escapeShellArgs` ?
`toString` works like `lib.concatStringsSep " "` but often used in places where `lib.escapeShellArgs` should be

**Comment by kvtb** [comment]
> For now, I opened a PR adding a lint for this to nixpkgs-hammering: [jtojnar/nixpkgs-hammering#30](https://github.com/jtojnar/nixpkgs-hammering/pull/30)

If you have a linter, it would be nice to warn on every List's `toString` forcing user to make a choice between `lib.concatStringsSep " "` and `lib.escapeShellArgs` and white that explicitly.

**Comment by jtojnar** [comment]
> Isn't it just a case to find implicit List's `toString` and replace it with `lib.escapeShellArgs` ?
> `toString` works like `lib.concatStringsSep " "` but often used in places where `lib.escapeShellArgs` should be

Adding explicit escaping will not work, Nix passes everything to Bash as a literal string so all the backslashes and quotes would just become literal parts of the first array item, AFAICT. See https://github.com/NixOS/nixpkgs/pull/112104#discussion_r571627614
