### ISSUE TITLE
outdated PureScript Spago; go to 0.19.1

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#112002]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.19.0
desired version: 0.19.1

###### Notify maintainers

maintainers: @cdepillabout

###### Note for maintainers

dhall version updated
https://github.com/purescript/spago/pull/739
windows cache fix
https://github.com/purescript/spago/pull/741

**Comment by cdepillabout** [comment]
It doesn't look like there is a github release yet, but here are the release notes: https://github.com/purescript/spago/pull/741/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

It looks like the only differences are windows-related, so I probably won't do this update.

**Comment by toastal** [comment]
Wouldn't it allow you to use the latest Dhall again, or's that not a priority?

**Comment by cdepillabout** [comment]
Ah, sorry, I should have explained that.  I fixed the dhall problem in https://github.com/NixOS/nixpkgs/pull/111634 by hardcoding use of an old dhall version.

That should hopefully continue working (for a while at least).
