### ISSUE TITLE
trunk-combined channel hasn't updated for 17 days

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#11205]
- tested job http://hydra.nixos.org/build/28002207#tabs-constituents

Failing tests:

- [ ] gnome3 http://hydra.nixos.org/build/28002102
- [x] kde http://hydra.nixos.org/build/28002228

cc @lethalman @wkennington @ttuegel

**Comment by vcunat** [comment]
KDE4 tests were working for me on 3c397e8e. I posted before to #11097.

**Comment by domenkozar** [comment]
Ah, I haven't seen that.

**Comment by Mathnerd314** [comment]
If we used a bulletin board, we could pin Hydra failure threads at the top. It seems GitHub doesn't have that feature though.
