### ISSUE TITLE
collisions

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11200]
I got something like "collision between `/nix/store/cviz20jv8f1vs9pi9md64cvw39z5a85z-util-linux-2.26.2/bin/mount` and `/nix/store/vh8554xqwr9aip4l0r2q9q0712mip237-util-linux-2.26.2/bin/mount`'" on each time I install something by nixos-rebuild switch.
I have `utillinuxCurses` in `systemPackages`.

**Comment by vcunat** [comment]
`utillinux` (without curses) is added automatically, so they collide. I think using `(hiPrio utillinuxCurses)` instead should make it work.

**Comment by Profpatsch** [comment]
(triage) Close @vcunat?

**Comment by Pitometsu** [comment]
Can't check right now, but @vcunat answer should solve this issue, thanks.
