### ISSUE TITLE
mhWaveEdit mp3

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11203]
In mhWaveEdit I can't open mp3 files. But should be able.

**Comment by Pitometsu** [comment]
If I add `lame` to `buildInputs` it not work. But if I just additionally install `lame` -- work just fine...

**Comment by Pitometsu** [comment]
@pSub could you add `vorbisTools` as well, please?

**Comment by pSub** [comment]
Done in f591a171f884e7a865b90c1bbe104203ef33a86b. You are welcome!

**Comment by Pitometsu** [comment]
Cool, thanks!
