### ISSUE TITLE
Package priority doesn't work in `{build,nativeBuild}Inputs` of `mkShell`

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#112029]
**Describe the bug**

It's a common pattern to use `mkShell` with dependencies written in `buildInputs` for a development shell. When their output paths collide, currently the former in the list will override the latter without any message.
I try to use `lib.{low,hi,set}Prio` to set package priority. But it doesn't make sense at all.

**To Reproduce**
1. `nix-shell -E 'with import <nixpkgs> {}; mkShell { buildInputs = [ python2 (lib.hiPrio python3) ]; }' --run 'python --version'`
   It prints python 2.*.

**Expected behavior**
   It prints python 3.*.

**Additional context**
This coments mentioned that `lib.{hi,low}Prio` can be used to adjust priority in `buildInputs`, but it does not (currently).  https://github.com/NixOS/nixpkgs/issues/78353#issuecomment-586554276

Related: https://github.com/oxalica/rust-overlay/issues/13

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94, NixOS, 21.03.20210202.fab6fcd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/store/dyxka00cvc00x2vfd8kdxib3h45y8hnc-source`

(nixpkgs revision: fab6fcdceb2560a4ab943830a2b1632458c7a6ff)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - mkShell
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
From the Nixpkgs manual:

> The priority of the package, used by nix-env to resolve file name conflicts between packages. See the Nix manual page for nix-env for details. Example: "10" (a low-priority package). 

Priority is not meant for how you're using it. The inputs ignore it, and add the items from the list in order to say `PATH`.
