### ISSUE TITLE
chromium.nix test failure

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#11208]
Newbie user bug report:

I am experimenting with the NixOS test suite and I found that one of the standard tests is failing:

```
$ nix-build '<nixpkgs/nixos/tests/chromium.nix>' 
...
trying http://tesseract-ocr.googlecode.com/files/tesseract-ocr-3.02.eng.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0        0 --:--:-- --:--:-- -  0    0     0-:--:--     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
error: cannot download nixos.svg from any mirror
builder for ‘/nix/store/jgis2if9p0p8cb4mhvlpdpi6b6d45hjw-nixos.svg.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/0026wmbiakn5n6rrmm0h5qj60finia8z-chromium-startup.html.drv’: 1 dependencies couldn't be built
...
```

Questions:

1. How can I see whether this test is running/passing/failing on the upstream Hydra?
1. How do I find the root cause?
1. How do I fix it?

**Comment by pSub** [comment]
For 1. See https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents, https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.chromium.i686-linux, https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.chromium.x86_64-linux. That stuff is also linked in README.md

**Comment by domenkozar** [comment]
```
$ nix-store -r /nix/store/jgis2if9p0p8cb4mhvlpdpi6b6d45hjw-nixos.svg.drv
these derivations will be built:
  /nix/store/jgis2if9p0p8cb4mhvlpdpi6b6d45hjw-nixos.svg.drv
building path(s) ‘/nix/store/gfb0gh7bmx081d2s63ddhgcjfm6wv8v2-nixos.svg’

trying http://nixos.org/logo/nixos.svg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
error: cannot download nixos.svg from any mirror
builder for ‘/nix/store/jgis2if9p0p8cb4mhvlpdpi6b6d45hjw-nixos.svg.drv’ failed with exit code 1
error: build of ‘/nix/store/jgis2if9p0p8cb4mhvlpdpi6b6d45hjw-nixos.svg.drv’ failed
```

This is an actual problem that svg logo is gone. cc @aszlig

**Comment by lukego** [comment]
Continuing to use this issue to learn about Nix:

I suppose that it is common for files to disappear from the internet. Does this usually "break the build" or does the nix/hydra binary cache usually include all such files? (If the latter then would it be a catastrophe to lose the upstream binary cache if that is acting as a backup of external media that NixOS depends on to build?)

Perhaps one of the manuals or papers discusses this topic?

**Comment by domenkozar** [comment]
We do have some support for caching tarballs, but it has to be used explicitly. I think only bootstrap files are cached.

If upstream file is missing, you won't be able to build the package (build will break). If hydra has built it, then nix will use the binary and not even care about source.

We try to mitigate with mirrors, but not all hosting sites have one.
