### ISSUE TITLE
bcrypt for hashedPassword(?)

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11201]
Currently `users.users.<name?>.hashedPassword` use _sha-512_. Is it secure enough? Probably better to use more secure hash like `bcrypt`?

**Comment by fpletz** [comment]
bcrypt is unfortunately not supported by `crypt()` from glibc. Also see https://en.wikipedia.org/wiki/Crypt_(C) for reference.

**Comment by Pitometsu** [comment]
Is it outdated: http://serverfault.com/questions/378093/changing-shadow-hash-algorithm-to-bcrypt-how-to-rehash ?

**Comment by rnhmjoj** [comment]
SHA (or any other fast hash algorithm) is not safe for password hashing, that's for sure.
http://security.blogoverflow.com/2013/09/about-secure-password-hashing/

**Comment by Pitometsu** [comment]
redhat [article](https://access.redhat.com/articles/1519843)

**Comment by joachifm** [comment]
Could someone link a proper source that explains how glibc's SHA-512 based `crypt()` method is broken? I see no evidence of that linked anywhere here. Seems to me like enforcing good passphrase policies will do more for real security than changing the hashing method (unless it is trivially broken, of course).

**Comment by vcunat** [comment]
The whole intended point is very simple: "standard" hashes are designed to cost few resources to compute, so attacks can be a bit faster, e.g. with special HW for it.

**Comment by vcunat** [comment]
There are some distros that (optionally) support e.g. that desired bcrypt scheme, so if anyone is interested, the best step forward is to find it and file a PR adding the support to our glibc/pam or wherever it should go. I see no reason not to accept such a patch in general. (I read about OpenSUSE and Debian having it.)

**Comment by Pitometsu** [comment]
[BTW](https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016) bcrypt not best solution for paranoics.

**Comment by joachifm** [comment]
@vcunat but does using a fast primitive mean that the overall construction is broken? I'm curious about what the evidence for that is, not being a cryptographer. What is the difference in dollar cost of reversing SHA-512 based `crypt()` with a reasonable iteration count vs `bcrypt()`? This is the metric used by the scrypt paper, which regrettably only considers md5 and DES based `crypt()` variants. My understanding of that paper is that `bcrypt()`'s memory usage is constant, only increasing in CPU time, which is what you appear to also accomplish by increasing the number of SHA iterations.

Anyway, if switching to `bcrypt` makes people feel good, then why not, but I'd like to see a principled comparison, to assess what the actual gain is.

**Comment by vcunat** [comment]
*This is probably no good place to discuss it.* I personally think it's mostly a nitpick. It will make no *significant* difference in the arguably most common cases:
- "high-entropy" passwords, as in any case the attack cost is multiplied by 2^(entropy bits);
- dictionary passwords (unless you use just your phone to crack it).

And, having spent a couple years with computational complexity theory, I'd also rather go for memory-costly algorithms than CPU-costly ones.

**Comment by Pitometsu** [comment]
https://github.com/jameswhite/pam_d_blowfish
