### ISSUE TITLE
Nix method for dynamic resource allocation (CPU cores, PCI devices)?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#11217]
I am wondering whether Nix could solve a long standing resource sharing problem for us...

We develop networking applications on shared servers running NixOS. These applications require dedicated hardware resources: CPU cores and PCI network devices. Each server has a number of these resources and the problem is how to share these between multiple users who are running tests (either interactively or in the background e.g. CI).

For example a server may have 24 CPU cores and 20 PCI devices. Several people may want to run tests on this machine and each test will need a specific amount of resources e.g. two CPU cores and two PCI devices to run a load generator + simple application. To a first approximation it doesn't matter which cores or PCI devices are used except that two tests must not both use the same ones at the same time.

I feel like we need some mechanism resembling a DHCP lease where I could say "Please give me four cores and two PCI devices" and it will say "okay, you have CPU cores 2,3,4,5 and PCI devices 01:00.0 and 01:00.1 for the next 12 hours or until your process terminates."

Is this a problem we could solve neatly with Nix?

**Comment by domenkozar** [comment]
Nix doesn't handle anything at runtime (well except nixos tests). It's limited to build/configure time.

It's a hard problem to solve without too much abstraction, http://mesos.apache.org/ is one of the solutions (not sure it supports PCI network devices, but I'd imagine it does).

**Comment by CMCDragonkai** [comment]
Potentially if Nix can configure containers with resource limits. But again it's a fixed static build-time configuration, not something that is meant to be bootstrapped and teared down at runtime depending on the system's needs.

**Comment by lethalman** [comment]
In such cases this is what you could do:
1. find a system that does dynamic resource allocation
2. make it generate a minimal .nix with the new system
3. import that generated .nix, eventually manipulate it, and do the deployment

**Comment by Profpatsch** [comment]
If your CI is done with nix I’m sure Hydra can be configured (or patched) to handle something like this for jobsets.

(triage) Is this still an issue @lukego or have you found a different solution in the meantime?

**Comment by lukego** [comment]
Thanks for the ideas. Closing. The nearest I came to a solution is SnabbCo/snabbswitch#773.
