### ISSUE TITLE
vim_configurable does not set the `backspace` option

### ISSUE THREAD

**Issue by madonius** [NixOS/nixpkgs#112150]
**Describe the bug**
When I install vim with vim_configurable the `backspace` option is not being set. This leads to rather wonky behaviour.

**To Reproduce**
1. Add 
    ```
      {
        environment.variables = { EDITOR = "vim"; };
      
        environment.systemPackages = with pkgs; [
          ((vim_configurable.override { python = python3; }).customize{
            name = "vim";
            vimrcConfig.packages.myplugins = with pkgs.vimPlugins; {
              start = [
              ];
              opt = [];
            };
            vimrcConfig.customRC = ''
            '';
          }
        )];
      }
   ```
2. Start editing a file
3. Try to delete a newline with backspace

**Expected behavior**
Default behaviour same as with the vim package

**Notify maintainers**
@jonringer 

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev
copying path '/nix/store/ajidkqg53y0zvh0m5cjgqiw3pf9cvlf0-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94, NixOS, 20.09.2947.2b9daa020d4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jonringer** [comment]
cc @teto

**Comment by teto** [comment]
`:h 'backspace'` shows it's empty by default on vim` (it's set in defaults.vim I think but that thing is a complete mess). I dont think it's nix's role to override that default. As a datapoint, neovim sets backspace to "indent,eol,start" by default so you may want to use that instead.

**Comment by madonius** [comment]
I just can say that most users are used to the defaults set by `neovim` and `vim_configurable`'s behaviour may surprise them.

**Comment by teto** [comment]
> I just can say that most users are used to the defaults set by neovim and vim_configurable's behaviour may surprise them.

Neovim was created because some changes were too hard to get into vim, if we leverage nixos to make vim look like neovim, I feel it's not respectful of vim users ? If people prefer neovim, can't they use that instead ?

**Comment by teto** [comment]
closing as wontfix.
