### ISSUE TITLE
python38Packages.pikepdf fails to build

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#112291]
**Describe the bug**

`python38Packages.pikepdf` fails to build on master and unstable

[Build log](https://github.com/NixOS/nixpkgs/files/5938893/build-log.txt)

**Notify maintainers**

@kiwi

**Comment by fabaff** [comment]
@eduardosm, could you please take a look at #112305?

**Comment by eduardosm** [comment]
> @eduardosm, could you please take a look at #112305?

Thanks
