### ISSUE TITLE
Steam cannot be installed (master) 

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11227]
While doing a `nixos-rebuild switch --upgrade` using a checkout of master (head at cbf30d2bc912b9aa1498a8fbdf2e434ced8d5f03), I got the following error:
```
cp: cannot create directory 'include/include': Permission denied
builder for ‘/nix/store/mjvksva8h08qs88vb5w2i71k0pfh0c9b-steam-fhs.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/m468hxsvsnmviqn92mlf64kgs7767ck3-steam.drv’: 1 dependencies couldn't be built
```
cc @abbradar

**Comment by abbradar** [comment]
_How has it even worked earlier?_ Thanks, pushed the fix in https://github.com/NixOS/nixpkgs/commit/6d6c1d352336ddde41b50a78196018b676957571. cc @bjornfor in case my fix would break something for you.

**Comment by bjornfor** [comment]
Thanks for the heads up. I was just testing this to see if I could reproduce.

**Comment by FRidh** [comment]
Thanks for fixing! Indeed surprising that this didn't show up before.

**Comment by abbradar** [comment]
cc @wkennington (I was too lazy to check `git blame` before and assumed I've left it broken) -- what have you tried to fix? My fix (above) should work for you, but it would be nice if you test it for yourself.

**Comment by abbradar** [comment]
Aha, I've been copying things around instead of symlinking them. https://github.com/NixOS/nixpkgs/commit/0427b21abaafe592d6ab43bec6e068188904db53 should fix this.
