### ISSUE TITLE
Materialize DB

### ISSUE THREAD

**Issue by jtrakk** [NixOS/nixpkgs#112249]
**Project description**

Materialize is a streaming database for real-time applications. Written in Rust.

**Metadata**

* homepage URL: https://materialize.com/
* source URL: https://github.com/MaterializeInc/materialize.git
* license: Business Source License. "Materialize is source-available and licensed under the BSL 1.1, converting to the open-source Apache 2.0 license after 4 years. As stated in the BSL, Materialize is free forever on a single node."
* platforms:

**Comment by jtrakk** [comment]
still relevant

**Comment by figsoda** [comment]
Looks like this is already in nixpkgs, both 21.05 and unstable
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=materialize
