### ISSUE TITLE
sddm: 0.12 -> 0.13 update broken

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#11224]
The sddm update in commit 0b1ddbfd6dc1acfa7b5bb46c096a804a1ea23c4f broke sddm. It crashes at startup with the following error message:
```
*** Error in `/nix/store/22d8gkdcjlx77ip50zayx73zrd60ig58-sddm-0.13.0/bin/sddm': corrupted double-linked list: 0x096a1490 ***
```
/cc @abbradar

**Comment by ttuegel** [comment]
Checking the example config (`sddm --example-config`) works, but one line is questionable:
```
# Hidden users
HideUsers=nixbld1,nixbld2翹▒,닰t댠t,1,욘췓翹 ,뢀뮮翿,,
```
That looks garbled to me, like it's the source of the corrupted list message.

**Comment by ttuegel** [comment]
That's definitely part of the problem; here's the relevant line from `/etc/sddm.conf`:
```
HideUsers=nixbld1,nixbld2,nixbld3,nixbld4,nixbld5,nixbld6,nixbld7,nixbld8,nixbld9,nixbld10
```

**Comment by ttuegel** [comment]
It looks like this issue was already [reported upstream](https://github.com/sddm/sddm/issues/560). I am testing the fix suggested there.

**Comment by ttuegel** [comment]
I fixed the corrupted configuration, but sddm still won't start.

**Comment by ttuegel** [comment]
To recap, sddm will start now in a VM, but it won't start on my physical machine. Moreover, the physical machine hangs, i.e. it becomes unresponsive to keyboard input. The log shows this:
```
Nov 23 08:24:38 mugen systemd[1]: Starting X11 Server...
Nov 23 08:24:38 mugen systemd[1]: Started X11 Server.
Nov 23 08:24:38 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):1:  bad "remove" command line
Nov 23 08:24:38 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):2:  bad "add" command line
Nov 23 08:24:38 mugen sddm-helper[1214]: pam_systemd(sddm-greeter:session): Failed to create session: Resource deadlock avoided
Nov 23 08:24:38 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):1:  bad "remove" command line
Nov 23 08:24:38 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):2:  bad "add" command line
Nov 23 08:24:38 mugen sddm[1211]: QProcess: Destroyed while process ("/nix/store/lf95ixzf9pqrk8jx06mnz5j715j6234h-sddm-0.13.0/libexec/sddm-helper") is still running.
Nov 23 08:24:38 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):1:  bad "remove" command line
Nov 23 08:24:38 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):2:  bad "add" command line
Nov 23 08:24:38 mugen sddm[1211]: QProcess: Destroyed while process ("/nix/store/lf95ixzf9pqrk8jx06mnz5j715j6234h-sddm-0.13.0/libexec/sddm-helper") is still running.
Nov 23 08:24:39 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):1:  bad "remove" command line
Nov 23 08:24:39 mugen display-manager-start[1211]: /nix/store/nhsqqwjyljfbfsqkl4wx34h00ajcdkch-xauth-1.0.9/bin/xauth: (stdin):2:  bad "add" command line
Nov 23 08:24:39 mugen sddm[1211]: QProcess: Destroyed while process ("/nix/store/lf95ixzf9pqrk8jx06mnz5j715j6234h-sddm-0.13.0/libexec/sddm-helper") is still running.
Nov 23 08:24:39 mugen sddm-helper[1243]: Received a wrong opcode instead of AUTHENTICATED: 0
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Main process exited, code=killed, status=11/SEGV
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Unit entered failed state.
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Failed with result 'signal'.
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Service hold-off time over, scheduling restart.
Nov 23 08:24:39 mugen systemd[1]: Stopped X11 Server.
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Start request repeated too quickly.
Nov 23 08:24:39 mugen systemd[1]: Failed to start X11 Server.
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Unit entered failed state.
Nov 23 08:24:39 mugen systemd[1]: display-manager.service: Failed with result 'start-limit'.
```

**Comment by FRidh** [comment]
Odd. I just did a `nixos-rebuild --switch` based on master, and am using sddm without any issues.

**Comment by abbradar** [comment]
@ttuegel Thanks for the patch! It's strange, because it works for me even without it (I use SDDM on daily basis). What's those `xauth` errors? I haven't seen likes before -- maybe they are the clue.

**Comment by ttuegel** [comment]
I don't know what the `xauth` errors are, but I'm assuming they're the problem. I suspect that `sddm` has some hidden state, since it works correctly in a VM (a clean install). I'll try cleaning out `/tmp` etc.

**Comment by abbradar** [comment]
It would be nice to find out what the state is -- we had similar problems in https://github.com/NixOS/nixpkgs/issues/8143

**Comment by ttuegel** [comment]
I don't think this is a left-over state problem anymore. I deleted `/tmp`, `/var/lib/sddm`, and `/run/sddm`, but it still won't start. It gives the same `xauth` error as above.

Here's one hint about what's going on: normally, `sddm` creates Xauthority files named `/tmp/sddm-$DISPLAY-xxxxxx`. However, when I get the `xauth` error, the files are named `/tmp/sddm--xxxxxx` as if `$DISPLAY` were empty. `sddm-helper` has to specify `$DISPLAY` for `xauth`, so its absence would certainly cause an error such as what I'm seeing. But, how could it be unset?!

**Comment by ttuegel** [comment]
The remaining error (the `xauth` error) has nothing to do with `sddm` because `slim` doesn't work either.
