### ISSUE TITLE
The SpiderOak version in 15.09 doesn't work cause it is too old.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#11229]
I have the same problem as the person here:
https://forums.gentoo.org/viewtopic-t-1024346.html?sid=61f576017c8a74452e489ac8978a37b7

Apparently the solution is to upgrade to version 5.2 (presumably 5.2 or higher)

**Comment by nbp** [comment]
cc @amorsillo

**Comment by magnetophon** [comment]
Maybe I was unclear, but all that is needed to fix this, is to merge the master pkg into 15.09.
Would it help if I do a (trivial) PR?

**Comment by ericsagnes** [comment]
#10341 should have fixed this, and is available in current unstable.
Can you check it is working for you and update the issue?

**Comment by magnetophon** [comment]
@ericsagnes
Yes, the version in master/unstable works just fine.
This is just a request to put it in 15.09 as wel.

**Comment by magnetophon** [comment]
Fixed in `16.03`.
