### ISSUE TITLE
apacheHttpd package options cannot be properly overridden

### ISSUE THREAD

**Issue by spacefrogg** [NixOS/nixpkgs#11226]
**Problem:** apacheHttpd is called with standard arguments like `sslSupport = true` and should be overridable via config.packageOverrides infrastructure.

```
{ config, pkgs, lib, ... }:
{
  nixpkgs.config.packageOverrides = pkgs:
  rec {
    apacheHttpd_2_2 = pkgs.apacheHttpd_2_2.override { ldapSupport = false; sslSupport = false; };
    apacheHttpd_2_4 = pkgs.apacheHttpd_2_4.override { ldapSupport = false; sslSupport = false; };
    aprutil = pkgs.aprutil.override { ldapSupport = false; sslSupport = false; };
  };
}
```

**Result:**

```
# nixos-rebuild --show-trace build
building the system configuration...
error: while evaluating the attribute ‘buildCommand’ of the derivation ‘nixos-system-*-16.03.git.6d31e9bM’ at /.../nixpkgs/nixos/modules/system/activation/top-level.nix:102:7:
...
assertion failed at /.../nixpkgs/pkgs/servers/http/apache-httpd/2.4.nix:13:1
```

Where 2.4.nix line 13 is the assertion:

```
assert sslSupport -> aprutil.sslSupport && openssl != null;
```

**Expected result:** It should work and build apacheHttpd and aprutil without `sslSupport`.

**Reproducible:** Always.

**Further remarks:**
- apacheHttpd reacts on changing overrides and produces different derivations
- The problem can be mitigated by setting the default values for `sslSupport ? false` and `ldapSupport ? false` in the function argument list of apacheHttpd in 2.4.nix. Then, the overrides get correctly detected and the assertions evaluate properly (including asserting `aprutil.sslSupport`).

**Comment by lethalman** [comment]
Clearing up things:
- The `services.httpd.package` defaults to `pkgs.apacheHttpd`, but it does not pick the version from the `packageOverrides`.
- Applying the override directly in `services.httpd.package` works.

So it's like the `pkgs` passed as argument to the module is not taking in account the overrides from `nixpkgs.config.packageOverrides`. I confirmed this.

cc @nbp

**Comment by lethalman** [comment]
I think I'm coming to the conclusion. The problem is `apacheHttpd.override`, together with the `aprutil`. It's not possible to call `.override` on apacheHttpd because it will fail due to aprutil not supporting ssl.

However I wonder why this happens, since `pkgs.apacheHttpd.override` should be using the older pkgs...

**Comment by lethalman** [comment]
Ah.

This works:
```
apacheHttpd = super.callPackage .../pkgs/servers/http/apache-httpd/2.4.nix { sslSupport = false; ldapSupport = false; }
```

This doesn't:
```
apacheHttpd = super.apacheHttpd.override { sslSupport = false; ldapSupport = false; };
```

So it's `.override` that is using the new pkgs... is that the correct behavior?

cc @edolstra

**Comment by Mathnerd314** [comment]
This is another strictness issue similar to #11094. ``.override`` needs to evaluate the original package to check whether it is a function or a set; that hits the assertions because aprutil is compiled without ssl/ldap support.
Moving the asserts down like
```
    optional ldapSupport (assert aprutil.ldapSupport && openldap != null; openldap) ++    # there is no --with-ldap flag
```
should work.

**Comment by lethalman** [comment]
Or let callPackage/override use the old pkgs when checking if it's a function/set ?

**Comment by danbst** [comment]
So, thanks to research done in https://github.com/NixOS/nixpkgs/issues/31884 I've got list of problematic asserts:
```
/home/danbst/dev/nixpkgs/pkgs/applications/version-management/subversion/default.nix:assert bdbSupport -> aprutil.bdbSupport;
/home/danbst/dev/nixpkgs/pkgs/servers/http/apache-httpd/2.4.nix:    assert ldapSupport -> aprutil.ldapSupport && openldap != null;
/home/danbst/dev/nixpkgs/pkgs/servers/http/apache-httpd/2.4.nix:    assert sslSupport -> aprutil.sslSupport && openssl != null;
/home/danbst/dev/nixpkgs/pkgs/development/libraries/libxslt/default.nix:    assert pythonSupport -> libxml2.pythonSupport;
/home/danbst/dev/nixpkgs/pkgs/development/tools/misc/dialog/default.nix:      assert unicodeSupport -> ncurses.unicode && ncurses != null;
```
and here is module that show problems with these overrides:
```
{ config, pkgs, lib, ... }:
let
    brokenApache = {
        environment.systemPackages = [ pkgs.apacheHttpd ];
        nixpkgs.overlays = [ (self: super: {
            apacheHttpd = super.apacheHttpd.override { ldapSupport = false; sslSupport = false; };
            aprutil = super.aprutil.override { ldapSupport = false; sslSupport = false; };
        })];
    };
    brokenSubversion = {
        environment.systemPackages = [ pkgs.subversion ];
        nixpkgs.overlays = [ (self: super: {
            aprutil = super.aprutil.override { bdbSupport = false; };
            subversion = super.subversion.override { bdbSupport = false; };
        })];
    };
    brokenXslt = {
        environment.systemPackages = [ pkgs.libxslt ];
        nixpkgs.overlays = [ (self: super: {
            libxml2 = super.libxml2.override { pythonSupport = false; };
            libxslt = super.libxslt.override { pythonSupport = false; };
        })];
    };
in {
    config = lib.mkMerge [
        ({
            fileSystems."/".device = "nodev";
            boot.loader.grub.devices = [ "nodev" ];
        })
        brokenApache
        brokenSubversion
        brokenXslt
    ];
}
```
This crap happened because asserts are done before `.override` can be monkeypatched into derivation. If we move them inside derivation, then override machinery starts to work. It isn't hard to fix these cases, but how to prevent them in future?

**Comment by spacefrogg** [comment]
I believe this one has outlived itself.
