### ISSUE TITLE
Mounting vboxsf filesystem always mounts for root, ignores uid option

### ISSUE THREAD

**Issue by tilmans** [NixOS/nixpkgs#11238]
I am trying to mount a Virtualbox shared folder into my NixOS with the following settings:

```
fileSystems."/virtualbox" = {
  fsType = "vboxsf";
  device = "tschlenk";
  options = "rw,uid=1000,gid=100";
};
```

As a result I get a mount at `/virtualbox` with 700 for root/root. Trying the same via mount gives me the expected result:

```
sudo mount -t vboxsf -o rw,uid=1000,gid=100 tschlenk /mnt
```

This will mount to `/mnt` with 700 for tschlenk/users (user id 1000, group id 100).

These are my first tests of NixOS an maybe I'm just missing a dependency here between user definition and permission?

**Comment by nbp** [comment]
cc @edolstra, @shlevy and @azlig might know.

**Comment by devhell** [comment]
@nbp you mean @aszlig ;)

**Comment by aszlig** [comment]
@tilmans: Does this still happen after f40c7ed1435d9507868337ae7509fe6d0392498b?

**Comment by Profpatsch** [comment]
No response, close @aszlig

**Comment by bts** [comment]
I can confirm that the `uid` option works

**Comment by Profpatsch** [comment]
> I can confirm that the uid option works

@bts Does that mean we can close this issue?

**Comment by bts** [comment]
@profpatsch Yeah -- I think this can be closed.
