### ISSUE TITLE
strawberry: streaming from Subsonic with Gstreamer over TLS fails due to missing glib-networking 

### ISSUE THREAD

**Issue by DeeUnderscore** [NixOS/nixpkgs#112334]
**Describe the bug**
The Strawberry music player, when configured with the Gstreamer backend, won't play music from a Subsonic-compatible server if the server is behind https. 

**To Reproduce**
1. Run current `nixpkgs.strawberry`
2. Configure backend to Gstreamer
3. Add a Subsonic server behind an https address
4. Try to play something from the Subsonic server

**Expected behavior**
Strawberry should be able to stream music from a Subsonic server behind https.

**Additional context**
Downloading the track list from the server works fine, and playing via the VLC backend works fine as well. When Gstreamer is selected, and you push play, an error is printed to stdout with a hint:

```
ErrorMessageReceived ID: 3 Domain: 2031 Code: 5 Debug: "../ext/soup/gstsouphttpsrc.c(1382): gst_soup_http_src_parse_status (): /GstPlayBin:playbin-10/GstURIDecodeBin:uridecodebin2/GstSoupHTTPSrc:source:\nTLS/SSL support not available; install glib-networking (6)
```

Rebuilding with `glib-networking` added to `buildInputs` did not work for me, but I can set an environment variable and run it like `GIO_EXTRA_MODULES=/nix/store/mbsp73ypp5mg2wckr4vrmbn47wlphjr2-glib-networking-2.66.0/lib/gio/modules strawberry` and it'll run correctly (provided glib-networking is under that path, obviously). I don't know if and how to add this to the wrapper, though. 

This missing dependency seems to have been a problem for people on other OSes as well:  
strawberrymusicplayer/strawberry#266

**Notify maintainers**
@peterhoeg

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.93, NixOS, 20.09.2812.f18fbc33930 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2812.f18fbc33930"`
 - channels(d): `"home-manager-20.09, nixos-20.09.3009.8e78c2cfbae, nixos-unstable-21.03pre268206.536fe36e23a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
#130966
