### ISSUE TITLE
Change to buildFHSChrootEnv broke steam

### ISSUE THREAD

**Issue by aristidb** [NixOS/nixpkgs#11231]
In 6602f49495c94e8533c8b482698bcf570a8d8933 (re #9543), @wkennington among other things committed a change to buildFHSChrootEnv that broke steam:

```
--- a/pkgs/build-support/build-fhs-chrootenv/env.nix
+++ b/pkgs/build-support/build-fhs-chrootenv/env.nix
@@ -157,11 +157,19 @@ let
   setupLibDirs = if isTargetBuild then setupLibDirs_target
                                   else setupLibDirs_multi;
 
+  setupIncludeDir = ''
+    if [ -x "${staticUsrProfileTarget}/include" ]
+    then
+        ln -s "${staticUsrProfileTarget}/include"
+    fi
+  '';
+
   # the target profile is the actual profile that will be used for the chroot
   setupTargetProfile = ''
     mkdir -m0755 usr
     cd usr
     ${setupLibDirs}
+    ${setupIncludeDir}
     for i in bin sbin share include; do
       cp -r "${staticUsrProfileTarget}/$i" $i
     done
```

This will try to copy the include directory twice, and fail.

@wkennington why did you try to change it to a symlink rather than a copy, and why did it not fail for you?

**Comment by FRidh** [comment]
see also #11227 and a fix in https://github.com/NixOS/nixpkgs/commit/6d6c1d352336ddde41b50a78196018b676957571

**Comment by aristidb** [comment]
Oops, guess I forgot to git pull before making this issue.
