### ISSUE TITLE
How do functors work?

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#11233]
...because maybe I'm not understanding the way they are intended in the nix manual:

```
with import <nixpkgs> {};

{ __functor = self: runCommand "foo" {} ''
  echo foo > $out
  '';
}
```

```
$ nix-build functor.nix
$
```

No result. Removing the `self` argument to the functor instead produces the derivation.

cc @shlevy

**Comment by lethalman** [comment]
Oh I guess the set itself is taken by `nix-build` instead of expanding the functor. That makes it almost useless if I understood the problem...

**Comment by shlevy** [comment]
I'm not quite sure what you're trying to do here. Note that `__functor` should take two arguments, and this "works" for some definition of works:

with import <nixpkgs> {};

```nix
{ __functor = self: arg: runCommand "foo" {} ''
    echo foo > $out
  '';
} {}
```

**Comment by lethalman** [comment]
@shlevy that won't produce any derivation with `nix-build`. So my definition of "work" here is, nix build should not stop at function/set encountered, but check generically if it's callable.

**Comment by shlevy** [comment]
That does produce a derivation with nix build.

**Comment by shlevy** [comment]
Again, what are you trying to accomplish?

**Comment by shlevy** [comment]
(also, this probably belongs in the nix repo)

**Comment by lethalman** [comment]
I see what you mean. So this is more like a feature request.

Make this:

```
When evaluating Nix expressions, the expression evaluato will automatically try to call functions that it encounters.
```

to be:

```
When evaluating Nix expressions, the expression evaluator will automatically try to call callables that it encounters.
```

So that I don't need that extra `{}`.

**Use case**: remove `.overrideDerivation`.

Let `mkDerivation' = args: args // { __functor = mkDerivation; }`.
Now ```overrideDerivation (mkDerivation args) (args: { foo = "bar"; })``` would be (almost) equivalent to `(mkDerivation' args) // { foo = "bar"; }` to nix-build. If I have to add an extra fake argument, I lose the property of bubbling a derivation up to nix-build.

**Current use case for me**. I have a `buildImage = args: somedrv;`.

Without functor, to make it overridable I'd need:

```
buildImage = args: (somedrv // { override = newargs: buildImage (args // newargs); });
image1 = buildImage {...};
image2 = image1.override { overrides... };
```

With functor it *could* be (but it's not because nix-build does not call the functor):

```
buildImage = args: args // { __functor = self: somedrv; };
image1 = buildImage {...};
image2 = image1 // { overrides... };
```

**Comment by lethalman** [comment]
@shlevy ups sorry, I really thought I were in the nix repo...

**Comment by shlevy** [comment]
@lethalman Can you test if NixOS/nix#717 does what you want? Note that the second argument of `__functor` has to be a `{}` style argument, but this works for me:

```nix
with import <nixpkgs> {};

{ __functor = self: {}: runCommand "foo" {} ''
    echo foo > $out
  '';
}
```

**Comment by lethalman** [comment]
@shlevy thought so, I've edited the comment accordingly ;) Closing this as I've copy-pasted on the nix issue.

**Comment by aakropotkin** [comment]
I know that this is the oldest thread of all time, but this is the top search result hit for "nix __functor" every time. I optimistically plan to improve the manual's docs, but in case I forget. Sadly the manual's example honestly doesn't show WHY `__functors` are useful - they basically just show that you can convert a set to a function, but that isn't in and of itself useful considering we use destructured argument sets all the time.

What makes functors' useful is currying, specifically how they interact with commands like `nix build`; but for a blurb this illustrates in the REPL:

```
nix-repl> adder = { __functor = self: y: if builtins.isInt y then self // { x = self.x + y; } else self.x; x = 0; }
nix-repl> adder 1 2 3 4 {}                                                                                          
10
nix-repl> adder 1 2 3 {}                                                                                          
6
nix-repl> adder 1 2 3 4                                                                                             
{ __functor = «lambda @ (string):1:16»; x = 10; }
```

**Comment by shadowrylander** [comment]
To add my two cents, with what I think may be a useful example as well:
```nix
nix-repl> t1 = { __functor = self: x: x (x self); }

nix-repl> t1 (self: { a = 1; b = 2; sa = self.a; sb = self.b; })
{ a = 1; b = 2; sa = 1; sb = 2; }

nix-repl> t2 = let
              shared = { c = 3; };
          in { __functor = self: x: x ((x self) // shared); }

nix-repl> t2 (self: { a = 1; b = 2; d = self.c + 1; })
{ a = 1; b = 2; d = 4; }

nix-repl> t3 = let
              shared = { c = 3; };
          in { __functor = self: x: (x ((x self) // shared)) // shared; }

nix-repl> t3 (self: { a = 1; b = 2; d = self.c + 1; })
{ a = 1; b = 2; c = 3; d = 4; }
```
