### ISSUE TITLE
libopus doesn't compile

### ISSUE THREAD

**Issue by cheecheeo** [NixOS/nixpkgs#11232]
On commit 33292cd618c5e50eab38cd50fce48565709e93ab

```
% nix-env --file $NIXPKGS -iA libopus
...
checking for C99 variable-size arrays... yes
checking for cos in -lm... yes
./configure: 12810: ./configure.lineno: Bad substitution
builder for ‘/nix/store/rpv9jqpbfgnnpb8vqpysbd71dqxdr6nw-libopus-1.1.drv’ failed with exit code 2
error: build of ‘/nix/store/rpv9jqpbfgnnpb8vqpysbd71dqxdr6nw-libopus-1.1.drv’ failed
```

**Comment by vcunat** [comment]
I assume `x86_64-linux`, right? On that exact commit it builds on Hydra, and also `--check` locally succeeds for me. I suspect the problem is worked around by using chrooted builds.

**Comment by cheecheeo** [comment]
Yes, `x86_64-linux`. Is there some documentation on how to use chrooted builds? I'm using nix as my package manager on Ubuntu with my configuration stored in $HOME/.nixpkgs/config.nix.

**Comment by vcunat** [comment]
There's some documentation [in the nix manual](http://nixos.org/nix/manual/#conf-build-chroot-dirs). On NixOS it's just `nix.useChroot = true;` instead.

**Comment by domenkozar** [comment]
It passes on Hydra, so using chroot should help: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.libopus.x86_64-linux
