### ISSUE TITLE
NixOS-20.09 AMI ignores user-data

### ISSUE THREAD

**Issue by anandsuresh** [NixOS/nixpkgs#112354]
minor edits after original submission to improve readability.

**Describe the bug**
I'm trying to spin up a new instance on AWS (us-east-1) using the AWS Community AMI nixos-20.09pre-git-6-x86_64-hvm-ebs (ami-02700dd542e3304cd). I set the user-data for the new instance to my desired NixOS configuration, expecting to see the configuration be reproduced at `/etc/nixos/configuration.nix` and have the instance boot into the desired configuration.

However, when I log into the instance, `/etc/nixos/configuration.nix` does not exist. Consequently, the desired configuration is not applied.

**To Reproduce**
1. Create a new instance on AWS using nixos-20.09pre-git-6-x86_64-hvm-ebs (ami-02700dd542e3304cd).
2. Add the desired configuration to the instance's user-data section.
3. Boot the instance.

**Expected behavior**
- The file `/etc/nixos/configuration.nix` should be created and must contain the configuration passed to `user-data`.
- The nixos configuration should have been applied.

**Screenshots**
Looking over the logs in `journald`, I can see the following:
```
...
...
Feb 08 01:25:18 ip-172-31-19-35.ec2.internal systemd[1]: Starting Reconfigure the system from EC2 userdata shell script on startup...
Feb 08 01:25:18 ip-172-31-19-35.ec2.internal amazon-shell-init-start[1344]: script not recognized, ignoring
Feb 08 01:25:18 ip-172-31-19-35.ec2.internal systemd[1]: Finished Reconfigure the system from EC2 userdata shell script on startup.
Feb 08 01:25:18 ip-172-31-19-35.ec2.internal systemd[1]: Startup finished in 26.884s (kernel) + 10.969s (userspace) = 37.853s.
...
...
```

**Additional context**
I searched for the string "Reconfigure the system from EC2 userdata shell script on startup", but it does not seem to exist in this repository. The closest I could find was the systemd service being created in [`amazon-init.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/amazon-init.nix).

Looking over that file, it doesn't seem like the AMI was created from the same source. Is this expected?

Attached below are logs from the instance I spun up.
```
[root@hostname:~]# systemctl cat amazon-shell-init.service
# /nix/store/aj1kyhchryvk34pv9kzcpv26npmq5133-unit-amazon-shell-init.service/amazon-shell-init.service
[Unit]
After=multi-user.target
Description=Reconfigure the system from EC2 userdata shell script on startup
Requires=network-online.target
X-StopOnRemoval=false

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/4p9w65np73bynmmq98nn2z1an0py0jvn-glibc-locales-2.31/lib/locale/locale-archive"
Environment="PATH=/nix/store/d9nbq7v3sll90li95wkp49b87igni1zi-sops-3.6.0/bin:/nix/store/ajpsqn2gkx5mnc9xfdjd6k0zb2z5mjch-awscli-1.18.93/bin:/nix/store/4g4f5xy720443g4zbsk1j9g51wnlr6z4-nix-2.4pre20200719_a79b6dd/bin:/nix/store/g0j3pan49fp>
Environment="TZDIR=/nix/store/1h9jyn0fllqvgpa0xwck25awdvmbclss-tzdata-2019c/share/zoneinfo"

X-RestartIfChanged=false


ExecStart=/nix/store/m4r6h3ip7h3kykrcq629k4218ggar1n5-unit-script-amazon-shell-init-start/bin/amazon-shell-init-start
RemainAfterExit=true
Type=oneshot
```

```
[root@hostname:~]# cat /nix/store/m4r6h3ip7h3kykrcq629k4218ggar1n5-unit-script-amazon-shell-init-start/bin/amazon-shell-init-start
#!/nix/store/c4wxsn4jays9j31y5z9f83nr2cp7l4pa-bash-4.4-p23/bin/bash -e
#!/nix/store/c4wxsn4jays9j31y5z9f83nr2cp7l4pa-bash-4.4-p23/bin/bash -eu

userData=/etc/ec2-metadata/user-data
if grep '# amazon-shell-init' $userData; then
  source $userData
else
  echo script not recognized, ignoring
fi
```

**Comment by thefloweringash** [comment]
That AMI doesn't seem to be one of the official NixOS AMIs. The AMIs are listed in [nixos/modules/virtualisation/ec2-amis.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix#L338), which lists `ami-0a2cce52b42daccc8` (owned by `080433136561`).

For comparison, the mentioned AMI is owned by `341718127296`.

**Comment by manveru** [comment]
This is actually one of the images we generated for use with https://github.com/input-output-hk/bitte and the source for the service you found is at https://github.com/input-output-hk/ops-lib/blob/zfs-image/zfs/amazon-shell-init.nix

As you found, it simply sources the user_data and expects it to be a shell script.

An example of its use is at https://github.com/input-output-hk/bitte/blob/master/modules/terraform.nix#L669-L682 where it helps get autoscaling instances to rebuild themselves faster using nix flakes and a matching binary cache.

So yes, it's definitely not one of the official NixOS AMIs, but I can see how the name might be confusing.

**Comment by jonringer** [comment]
The official ami's can be found at https://nixos.org/download.html#nixos-amazon

**Comment by anandsuresh** [comment]
Thanks for the updates guys. Much appreciated. I'll close this out now.

**Comment by thefloweringash** [comment]
> As you found, it simply sources the user_data and expects it to be a shell script.

Incidentally, would https://github.com/NixOS/nixpkgs/pull/67345 mean this use case wouldn't require a custom AMI?
