### ISSUE TITLE
rPackages.MASS: download error

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11230]
```
nix-env -i R
````
fails on Ubuntu Linux 14.04.2.

with messages about MASS like:
```
trying http://brieger.esalq.usp.br/CRAN/src/contrib/MASS_7.3-44.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

and in other cases with messages related to invalid sha256 hashes.

```
output path ‘/nix/store/1r6cy4qagvd5b87nzcn3g92nskp5flrd-MASS_7.3-44.tar.gz’ should have sha256 hash ‘16z7z1afavfhis5jp4v7ybgy7arj8ivpggxqhkx449r28wjy4pw3’, instead has ‘102rw6gw1mrbr00s8b1bnz2yh2nqk411qdhs6kncs6scalixjb5p’
building path(s) ‘/nix/store/r92jcf1p0xj407l7r5zgsgcywjxhyxl0-Matrix_1.2-2.tar.gz’
cannot build derivation ‘/nix/store/gzcmrc9bd22j59111x0marpg0mydmgg7-r-MASS-7.3-44.drv’: 1 dependencies couldn't be built
killing process 26600
cannot build derivation ‘/nix/store/ayh5d25xcvgw24lpm0la4vixwsjx1ic2-R-3.2.2-wrapper.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ayh5d25xcvgw24lpm0la4vixwsjx1ic2-R-3.2.2-wrapper.drv’ failed
``` 

Is R meant to be broken or known to be broken? IIRC, it has been this like at least 6 months.

**Comment by FRidh** [comment]
And `nix-shell -p R`?
I have the impression you haven't updated your channel.

**Comment by vcunat** [comment]
On master we have 7.3.45 and it downloads fine (maybe not in the channel yet), but on 15.09 it gets just 404. @peti: what's the general strategy about backporting `rPackages` updates to stable releases?

**Comment by vcunat** [comment]
BTW, having a stable URL is always preferred, I believe.

**Comment by peti** [comment]
Upstream edits and removes published versions of R modules at will, so it's near impossible to provide a stable release of R unless we mirror all source tarballs. I suppose this means that we *must* update `pkgs/development/r-modules` in our release branches, because otherwise they just won't build after a couple of weeks.

**Comment by peti** [comment]
I've enabled Hydra builds for R in the `release-15.09` branch in 6c9911ddee66a52fc078bb3ed550c2676c43e86d. Hopefully, that will make those source tarballs available in our cache and mitigate those kind of problems in the future.

**Comment by abbradar** [comment]
FWIW, there's an awesome MRAN (Managed R...) with daily complete CRAN snapshots available from Revolution Analytics [1]. I've sent them an e-mail asking for permission to use their mirror as our main source of package sources nearly two months ago, but got no answer. All the rhetoric on the website suggest that this mirror is "open" and "available to the R community" but I don't know if we should use it without a permission...

**Comment by peti** [comment]
I think we totally should! Tracking this issue at https://github.com/NixOS/nixpkgs/issues/11243.
