### ISSUE TITLE
kde5: cannot modify screen, kscreen is missing

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11244]
Using a checkout of master, it is not possible to adjust screen settings using KDE's systemsettings; kscreen seems to be missing.
cc @ttuegel

**Comment by ttuegel** [comment]
Are you using `plasma5_stable` or `plasma5_latest`?

**Comment by FRidh** [comment]
I have 
```
services.xserver.desktopManager.kde5.enable = true;
```
and 
```
    kde5.okular
    kde5.plasma-workspace
    kde5.plasma-desktop
    kde5.kate
```
in systemPackages.

In `all-packages.nix` is specified that
```
  plasma54 = recurseIntoAttrs (import ../desktops/plasma-5.4 { inherit pkgs; });
  plasma55 = recurseIntoAttrs (import ../desktops/plasma-5.5 { inherit pkgs; });
  plasma5_stable = plasma54;
  plasma5_latest = plasma55;

  kde5 = kf5_stable // plasma5_stable // kdeApps_stable;
```
and in the module kde5.nix
```
  kf5 = pkgs.kf5_stable;
  plasma5 = pkgs.plasma5_stable;
  kdeApps = pkgs.kdeApps_stable;
```
so the answer to your question in `plasma5_stable` :-)

**Comment by ttuegel** [comment]
The default backend for `kscreen` seems to be missing. I am investigating.

**Comment by retrry** [comment]
Just updated my NixOS installation and it seems that I too have this problem.
```
No kscreen backend found. Please check your kscreen installation.
```

**Comment by ttuegel** [comment]
This is fixed in 98bd11125f0513e2c04ddf6a8faa06f2b6673fea.

**Comment by FRidh** [comment]
Thanks a lot!

**Comment by rolfschr** [comment]
I had this issue on NixOS 22.11 and wasn't able to resolve it by installing manually `kscreen`. However, I also manually installed libkscreen (`sudo nix-env -iA libsForQt5.libkscreen`) and after rebooting it worked.
