### ISSUE TITLE
kde5 plasma segfaults when using slim dm

### ISSUE THREAD

**Issue by dlukes** [NixOS/nixpkgs#11241]
What the title says :) Mouse works, the errors are reported in GUI windows, but there's no shell. I know sddm is recommended, so perhaps slim is not even expected to work? In that case, it might be useful to just state it for the record here and close the issue.

Tested using both channels/nixos-15.09 and channels/unstable (`16.03.git.7ae05edM (Emu)`). Here's my [`configuration.nix`](https://github.com/dlukes/dotfiles/blob/master/configuration.nix), in case it's of any help. I've manually added a few packages to my nixpkgs, but that shouldn't be the issue, they aren't related to Qt or the GUI at all.

Anticipating a possible follow-up question: I thought the `kde4.*` packages in my config might be to blame, so I tested the whole setup without them; same story.

**Comment by domenkozar** [comment]
cc @ttuegel

**Comment by ttuegel** [comment]
Any display manager *should* work. I'll try to reproduce this.

**Comment by dlukes** [comment]
Thanks! Let me know if I can be of any help :)

**Comment by dlukes** [comment]
Whew, so I got lucky and actually traced this to an environment variable I put in my `.zprofile` way back when to prevent Emacs from crashing due to some GTK bug. So, as [per recommendation](https://xkcd.com/979/), "dear people of the future": don't put `export XLIB_SKIP_ARGB_VISUALS=1` into any file that is sourced upon logging into KDE :) (Other related variables might conceivably mess things up as well.)
