### ISSUE TITLE
stdenv.x86_64-darwin fails on staging-next

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#112417]
The `stdenv.x86_64-darwin` build is failing on staging-next (#112095) and I don't know what could cause this.

The earliest hydra job this failed on is https://hydra.nixos.org/build/136505930.

The log since then always looks like this:
```
output '/nix/store/hd0fxaykxgp3a8bc3ia17n18zsb06fbd-stdenv-darwin' is not allowed to refer to the following paths:
  /nix/store/2q831bygr0ddkjk4bgix42ym9ha1jpmm-bootstrap-stage0-clang
  /nix/store/6jysbyhc43sjvfiyh1bpvi1n3zbz212r-bootstrap-tools
```

Pinging people that touched the darwin stdenv in recent times:
@thefloweringash @holymonson

**Comment by veprbl** [comment]
This bisects to 2dcc858efc723e3865629ba140b28c5365069ed1 #94642. Reverting 6e3f4c90790f112f6b6da54b9f1eb0e85310ee64 seems to fix the issue.

cc @Mic92

**Comment by thefloweringash** [comment]
There's a reference through ncurses, which includes the log line (from `nix log -f . ncurses`)

```
patching script interpreter paths in /nix/store/02i92p37znanj417a23jynq20lrlknjv-ncurses-6.2-dev
/nix/store/02i92p37znanj417a23jynq20lrlknjv-ncurses-6.2-dev/bin/ncursesw6-config: interpreter directive changed from "#!/nix/store/gqqv7d993qsys71l3q8cp8zajp4ys31n-bash-4.4-p23/bin/bash" to "/nix/store/2q831bygr0ddkjk4bgix42ym9ha1jpmm-bootstrap-stage0-clang/bin/bash"
```

It's unfortunate to have an ambiguity of multiple `bash` instances on the path, but as far as I can tell ncurses is doing the right thing and referring to `$SHELL`. `patch-shebangs.sh` has an [explicit case](https://github.com/NixOS/nixpkgs/blob/1e6c110bc49a2415374e72cd9ae2f6987d29ee23/pkgs/build-support/setup-hooks/patch-shebangs.sh#L89) to not rewrite interpreters that are already store paths, but tracing through this it looks like there's an off by one in parsing the `oldInterpreterLine`, introduced by ab4c35982269e8f1f15e07afa7fedf65c749f276.

Note the critical difference between the old way and the new way:
```
$ echo "hello world" | tail -c+3
llo world
$ str="hello world"; echo ${str:3}
lo world
```

**Comment by Mic92** [comment]
From what I understand this should be fixed by https://github.com/NixOS/nixpkgs/pull/112458
