### ISSUE TITLE
NixOS: default = {} for submodule not respected

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixpkgs#112494]
**Describe the bug**
Setting a submodule default value to `{}` does not actually result in an empty set. Setting no default value leads to the option being *not defined*, but using `default = {};` fills the set with attributes declared in its options.

**To Reproduce**
Minimal example configuration:
```nix
# config.nix
{ ... }:
let
  extension = { lib, ... }: {
    options = with lib; with types; {
      users.users = mkOption {
        type = attrsOf (submodule {
          options.foo = mkOption {
            description = "a foo extension for users";
            default = {};
            type = submodule {
              options = { bar = mkOption { type = str; }; };
            };
          };
        });
      };
    };
  };
in
{
  imports = [ extension ];

  users.users = {
    extended = {
      foo = { bar = "baz"; };
    };
    vanilla = {};
  };
}
```
```shell
$ nix repl -E 'import <nixpkgs/nixos> { configuration = ./config.nix; }'
nix-repl> config.users.users.extended.foo
{ bar = "baz"; }
nix-repl> config.users.users.vanilla.foo
{ bar = «error: The option `users.users.vanilla.foo.bar' is used but not defined.»; }
```
**Expected behavior**
```shell
$ nix repl -E 'import <nixpkgs/nixos> { configuration = ./config.nix; }'
nix-repl> config.users.users.extended.foo
{ bar = "baz"; }
nix-repl> config.users.users.vanilla.foo
{ }
```

**Additional context**

My use case is to extend `users.users.<name>` with a new submodule option (here `foo`), which should only be acted upon if a value is actually set. Following the NixOS manual there is no indication that `default = {}` will still populate the set. Not setting `default` does not help either, because there is no (obvious) way to check if a value has been set, since the `not defined` exception will trigger on evaluation.

Sure, the workaround is to just wrap the submodule in a `nullOr` type and `default = null`
```nix
mkOption {
  description = "a foo extension for users";
  default = null;
  type = nullOr (submodule {
    options = { bar = mkOption { type = str; }; };
  });
}
```

and check for `null` in the implementation.

This should at least be documented (which it is now, here...), but I'd much prefer that the behavior of `default = {}` was less surprising. I'd submit a PR but I'd need some hand holding to dig through `/lib/modules.nix`, because so far I could not find how exactly it comes that the default empty set is not the final value.

**Notify maintainers**
@Infinisil @danbst

**Comment by roberth** [comment]
This is probably best solved by attacking the use case directly, by implementing "optional" options that do not appear in `config` when they're not set. This feature is also desirable for RFC42 options.

In your example specifically, the `foo` option should be optional with such a new feature.

I don't think we can change the module system such that a single setting always ends up in `config` unmodified. We have too many uses of value-altering types, including `submodule` and `coercedTo` which is useful for compatibility with out-of-tree modules (including user configurations). The `mkOption` `apply` parameter and - to some degree - value merging would not make much sense either if this was a goal.
So, I agree it should be documented that values change when they go through the module system.

**Comment by fricklerhandwerk** [comment]
What exactly do you mean by "optional" option here? But I see that changing behavior is probably not practical.

Where would we put a note on the current behavior in the NixOS manual? I propose we [extend this paragraph or annotate the example](https://github.com/NixOS/nixpkgs/blob/c27692c75b4e431b9c3e84e4425ac966c62e9efa/nixos/doc/manual/development/option-types.xml#L508-L538).

**Comment by roberth** [comment]
So the idea is that an option like this

```nix
foo = mkOption {
  description = "a foo extension for users";
  optional = true;
  type = submodule {/* ... */};
}
```

would cause the `foo` in `config` to be missing entirely instead of being defined as an error call, it's not quite the same as what you described in Expected behavior. It'd be

```
$ nix repl -E 'import <nixpkgs/nixos> { configuration = ./config.nix; }'
nix-repl> config.users.users.extended
{ /* ...; */ foo = { bar = "baz"; } }
nix-repl> config.users.users.vanilla
{ /* ...; */ }
```

I hope that's acceptable.

Another idea is to add @lheckemann's `lib.unset` idea, which would belong to the family of `lib.mkBefore`, `lib.mkDefault` etc. In that case, it'd be

```
foo = mkOption {
  description = "a foo extension for users";
  default = lib.unset;
  type = submodule {/* ... */};
}
```

https://github.com/NixOS/rfcs/pull/42#issuecomment-703006619

I believe it'd behave the same for this use case, but perhaps it's a more general solution? I don't know if it makes sense to use it in other places. I suspect usually `mkIf false` fulfills its role.

**Comment by fricklerhandwerk** [comment]
Yes, this is a valid solution to the problem, because then you can check existence with `hasAttr "foo" user`. I don't really care how it would be implemented, but thinking about it, adding another special `unset` type just for the module system, to taper over the fact that it produces values where none are expected, seems confusing. Adding another option `optional = true` and explaining why it's different from `default = {}` or no default, seems easier than explaining the subtle difference between no default (`not defined` exception), `null` (type error for submodules) and `unset`.

Then again, this discussion is only about trading complexity in the module system for complexity in module implementation. You can already check for `null`, `{}`, or any known value in your implementation. So my use case is satisfied, it's just that it's not obvious how  exactly to achieve it. The core of my issue is that the semantics of `default = {}` are not intuitive and not documented. Either document properly (ideally in a way that the reader will not think *"why the hell is this so weird - ah, the module system is just a tangled mess"*) or change the semantics.

> I don't think we can change the module system such that a single setting always ends up in `config` unmodified.

That change would only concern the `default` parameter. What exactly would speak against that? So far I'm still thinking *the module system is a tangled mess*, because the code is really hard to see through, and I haven't seen a high-level explanation why we can't just pass `default = {}` and get `{}` out.

**Comment by roberth** [comment]
> a high-level explanation why we can't just pass default = {} and get {} out.

The `default` is a module, not the final value. Its "`options` and `config` values", which are none, are combined with the existing options, which have defaults, and those show up in the final value.

Other option types can transform their config values too.

**Comment by Infinisil** [comment]
I don't think this is anything that needs to be changed other than perhaps improving the docs. You can check for whether options are set or not using `options.foo.isDefined`, but I'd also recommend against that since you can never force an unset (unless something like `lib.mkUnset` is added, which might be the case at some point). But in general, the type of the option should be descriptive of the values it can have, including defaults and all values that influence the module.

And for submodule specifically, changing them to allow for options to not be present at all is infeasible imo, it would change the module semantics too drastically regarding laziness of option existence.
