### ISSUE TITLE
cmus: on macOS, CoreAudio support is broken because AudioUnit dependency is not provided; @oxij

### ISSUE THREAD

**Issue by protoboolean** [NixOS/nixpkgs#112459]
**Describe the bug**

No audio. Error message in cmus status bar:

`Error: opening audio device: couldn't initialize required output plugin`

**To Reproduce**

1. Install CMUS on macOS (I tested BigSur 11.2)
2. Try to play any audio.

**Expected behavior**

Obvious.

**Additional context**

- tested on macOS version 11.2 (BigSur)

**Notify maintainers**

@oxij 

**Metadata**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-21.03pre268255.e5b478271ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

NOTE: host os is reported as macOS 10.16, but I am running 11.2

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cmus
```

**Comment by smancill** [comment]
I believe this was closed by #112461
