### ISSUE TITLE
Calibre-web package and service

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#112430]
**Calibre-web**
Calibre-Web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database.

It is a python package, using versionned releases, with optional dependencies to add support for GDrive, OAuth, LDAP, etc...

A NixOS specific issue for this program would be the integration with `calibre`, which requires providing a path to its converter tool in the webui.

**Metadata**

* homepage URL: https://github.com/janeczku/calibre-web
* source URL: https://github.com/janeczku/calibre-web
* license: GPLv3
* platforms: all python platforms

**Comment by pborzenkov** [comment]
I'm interested in running `calibre-web` on NixOS as well. I've created an initial PR that adds `calibre-web` package: #113994.
Once it's merged, I'm planning to introduce a service with basic declarative config for it.

**Comment by Ambroisie** [comment]
@pborzenkov you might be interested by the issue I opened [here](janeczku/calibre-web#1856)

**Comment by pborzenkov** [comment]
@Ambroisie Yeah, I've seen the issue. I hope it gets implemented, so the configuration process won't need to modify the DB. Until then, it looks like the only way to configure `calibre-web` declaratively is gonna be via `sqlite3`...

**Comment by symphorien** [comment]
> Once it's merged, I'm planning to introduce a service with basic declarative config for it.

Note that it's easier to review with a module.

**Comment by pborzenkov** [comment]
> Note that it's easier to review with a module.

@symphorien  Ok. Should I update the PR with the module itself? It's my first contribution to NixOS, so I'm not yet familiar with the process.

**Comment by symphorien** [comment]
I think adding the module as a separate commit is fine.

**Comment by ambroisie** [comment]
This was closed by #113994
