### ISSUE TITLE
R: download source tarballs from the MRAN mirror

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#11243]
Add support for downloading source tarballs from the MRAN (Managed R) mirror to our R package set: <https://mran.revolutionanalytics.com/snapshot/>.

**Comment by abbradar** [comment]
I swayed towards "we should" now too -- after all, the mirror is open and I don't think we would generate much traffic.

**Comment by abbradar** [comment]
I'll look at this later today.

**Comment by abbradar** [comment]
I'll look at this later today.

**Comment by abbradar** [comment]
Closed by #11247
