### ISSUE TITLE
Issue with Numix icons

### ISSUE THREAD

**Issue by GCerar** [NixOS/nixpkgs#11259]
I have installed Numix theme `numix-gtk-theme` and numix icon sets `numix-icon-theme` and `numix-icon-theme-circle`. When I wanted to change xfce's appearance selecting one of those sets, gtk always displays default icon set. (restarting, clearing ~/.cache/xfce or deleting ~/.gtkrc-2.0 or settings.ini, etc. didn't help) Changing to numix gtk theme has no issues.

At first I assumed it is missing path or gtk icon cache problem. I removed both icon sets.  Put icons directly from designer's git into ~/.icons directory as I had on Gentoo and Ubuntu. Xfce alerts be about missing gtk icon cache (yellow triangle in appearance menu). I executed `gtk-update-icon-cache ` command on each of icon sets directory. Still not showing desired icons.

I'm blindly guessing the problem is in `gtk-update-icon-cache` or maybe my config simply missing some package to handle those icons. Can't figure it out. Does anyone know how to debug those kind of issues?

Using NixOS stable 15.09. Tried unstable yesterday, same result.

[nixos config](https://github.com/GCerar/nixos-config/blob/master/proteus.nix), other things I tried are in comments
[gtk2 config](https://github.com/GCerar/home-config/blob/master/.gtkrc-2.0)
[gtk3 config](https://github.com/GCerar/home-config/blob/master/.config/gtk-3.0/settings.ini)

**Comment by domenkozar** [comment]
cc @lethalman

**Comment by wedens** [comment]
I've copied icon/theme setup from @bennofs [nix configuration](https://github.com/bennofs/etc-nixos/blob/master/conf/desktop.nix#L26). works fine (with Numix)

**Comment by GCerar** [comment]
Tnx @wedens and @bennofs for his config. The problem was missing `GDK_PIXBUF_MODULE_FILE`. 

Q: Would it be good idea to set such variable inside numix icon definition? Or somewhere else? Would it affect other packages?

**Comment by wedens** [comment]
@GCerar I think it's part of https://github.com/NixOS/nixpkgs/issues/247#issuecomment-41255168

**Comment by GCerar** [comment]
Oh, I didn't know. Nice :). My issue is solved with workaround. Final solution will came with NixOS 16.xx. Closing.
