### ISSUE TITLE
Neochat segfaults

### ISSUE THREAD

**Issue by crazazy** [NixOS/nixpkgs#112542]
**Describe the bug**
When launching neochat, it returns a segmentation fault

**To Reproduce**
1. run `nix run nixpkgs.neochat`
2. run `neochat`

**Expected behavior**
The neochat GUI should launch

**Notify maintainers**
@peterhoeg 
@mjlbach 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `0`
 - host os: `Linux 5.4.94, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(crazazy): `"nixUnstable-21.03pre268853.d9c6f13e13f"`
 - channels(root): `"NUR, nixos-21.03pre268835.8c8731330b5"`
 - nixpkgs: `/nix/store/izhxapswz2jp7z0w3fdrgfgwbgy2j5zn-nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# these all link to the same derivation but..
- neochat
- matrique
- spectral
# a list of nixos modules affected by the problem
module:
# n/a
```

**Comment by mjlbach** [comment]
I think this issue is localized to trying to run neochat from nix run. Does it work if you install it via configuration.nix/home.nix? I think the libsForQt5 helpers do some manipulation of the environmental variables which may not be present when running with `nix run`. FWIW I use neochat daily on unstable and it works for me without segfaults.

**Comment by crazazy** [comment]
I originally found out about it when trying to run neochat as it's part of my system setup. I can confirm this does not just happen when using neochat via `nix run`

**Comment by crazazy** [comment]
It seems this is the corresponding existing bug report that is consistent with the segmentation fault I found...
https://invent.kde.org/network/neochat/-/issues/215

**Comment by mjlbach** [comment]
Seems like it's upstream then? I'll of course update the package when presumably they fix the issue and cut a release.

**Comment by peterhoeg** [comment]
Fixed.
