### ISSUE TITLE
krb5.kdc option should accept an array

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#11268]
The `krb5.kdc` NixOS option should accept an array so that multiple kdc entries can be specified for a realm. The output would look similar to the snippet at http://web.mit.edu/kerberos/krb5-devel/doc/admin/install_kdc.html#krb5-conf : 

```
[realms]
    ATHENA.MIT.EDU = {
        kdc = kerberos.mit.edu
        kdc = kerberos-1.mit.edu
        admin_server = kerberos.mit.edu
    }
```

I believe `krb5.kerberosAdminServer` should also support the same, although I'm not certain of this one. An example of multiple admin_server lines is at: https://help.ubuntu.com/lts/serverguide/kerberos-ldap.html

**Comment by a1russell** [comment]
Pinging @wkennington who performed the last commit on the relevant file.

**Comment by Profpatsch** [comment]
(triage) Was this solved?

**Comment by a1russell** [comment]
No.

**Comment by Profpatsch** [comment]
Do you want to create a PR then?

**Comment by a1russell** [comment]
No. I filed this once I became aware of the disconnect between the kdc config and NixOS', but I personally don't use either. Was thinking that the maintainer might care, but I suppose I was wrong.

**Comment by Profpatsch** [comment]
I suppose we tag this with the `good-first-bug` thingy. cc @bennofs

**Comment by a1russell** [comment]
Closing this due to lack of interest in fixing it, and I've moved on to another distro.
