### ISSUE TITLE
Question: how to install scikitimage? 

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11260]
```
% nix-env -i -A nixpkgs.python27Packages.scikitlearn                                                                                                                                                           master
installing ‘python2.7-scikit-learn-0.17b1’
^Cerror: interrupted by the user
t% nix-env -i -A nixpkgs.python27Packages.scikitimage                                                                                                                                                           master
error: attribute ‘scikitimage’ in selection path ‘nixpkgs.python27Packages.scikitimage’ not found
```

```
pkgs/top-level/python-packages.nix
5544:      [ joblib matplotlib six scikitlearn decorator audioread samplerate ];
5557:    name = "scikits.samplerate-${version}";
16051:  scikitimage = buildPythonPackage rec {
16052:    name = "scikit-image-${version}";
16056:      url = "https://pypi.python.org/packages/source/s/scikit-image/${name}.tar.gz";
16066:      homepage = http://scikit-image.org;
16072:  scikitlearn = buildPythonPackage rec {
16073:    name = "scikit-learn-${version}";
16075:    disabled = stdenv.isi686;  # https://github.com/scikit-learn/scikit-learn/issues/5534
16078:      url = "https://github.com/scikit-learn/scikit-learn/archive/${version}.tar.gz";
16095:      homepage = http://scikit-learn.org;
```

In the python packages a variable scikitimage is defined, but why can't I install it?

**Comment by FRidh** [comment]
@aragnon If I am correct you are now using nixos-unstable. To be more precise, you are using the nixos-unstable channel. If you look at the Git repository, on master, then you can indeed see scikitimage. However, this update is not yet available in nixos-unstable.

It always takes some time before the channels, in this case nixos-unstable, are updated with the changes that have been merged into the Git master branch. A nice overview of how old the channels are can bee seen at http://howoldis.herokuapp.com/

How does it know how old the channels are? Well, you can check the repository [nixpkgs-channels](https://github.com/NixOS/nixpkgs-channels/commits/nixos-unstable).

Often it takes only a few days before the channel is updated, sometimes a bit longer, like now (#11097).

**Comment by FRidh** [comment]
@aragnon if you still want to get `scikitimage`, then what you can do is clone this repository, and run
```
nix-shell -I nixpkgs=/path/to/nixpkgs -p python27Packages.scikitimage
```
Doing this results in a shell where you can run `python` and which can access scikitimage.

On a sidenote, if you like living on the edge, and are running NixOS, then what you could do is
```
nixos-rebuild switch --upgrade -I nixpkgs=/path/to/nixpkgs
```
Note however that often you will have to compile a lot then.

**Comment by domenkozar** [comment]
As @FRidh nicely explained, I'm closing this one.
