### ISSUE TITLE
command_not_found_handle() gives inaccurate hint on how to install "gpg"

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#1126]
Before installing gnupg on my system, typing `gpg` at the command line results in the usual message telling me I don't have the package, but I can install it with one of the following:

     `nix-env -i gnupg`
     `nix-env -i gnupg1compat`

After installing gnupg and typing `gpg`, I get the same error message. Shouldn't the recommendation be changed if the gnupg package doesn't actually provide `gpg`?

**Comment by spwhitt** [comment]
Can we just modify command-not-found to use attribute names? This would remove the ambiguity and boost performance.

**Comment by edolstra** [comment]
Yeah, it would definitely be better to use attribute names.

**Comment by domenkozar** [comment]
This can be closed now since we a re using attribute names.
