### ISSUE TITLE
Ryujinx

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#112607]
**Describe the bug**
Ryujinx crashes on startup. I tired deleting `.config/Ryujinx` and it still occured.

**To Reproduce**
<pre>% nix run nixos.ryujinx  -c Ryujinx
<font color="#34E2E2">00:00:00.476 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6498</font>
<font color="#34E2E2">00:00:00.501 |N| Application PrintSystemInfo: Operating System: Linux 5.4.95 #1-NixOS SMP Wed Feb 3 22:26:02 UTC 2021 (X64)</font>
<font color="#34E2E2">00:00:00.502 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz</font>
<font color="#34E2E2">00:00:00.504 |N| Application PrintSystemInfo: Total RAM: 15467 MB</font>
<font color="#34E2E2">00:00:00.509 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub</font>
<font color="#FF6B6B">00:00:01.012 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.</font>
<font color="#FF6B6B">   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /build/source/Ryujinx/Ui/MainWindow.cs:line 105</font>
<font color="#FF6B6B">   at Ryujinx.Program.Main(String[] args) in /build/source/Ryujinx/Program.cs:line 138</font>
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /build/source/Ryujinx/Ui/MainWindow.cs:line 105
   at Ryujinx.Program.Main(String[] args) in /build/source/Ryujinx/Program.cs:line 138
zsh: abort (core dumped)  nix run nixos.ryujinx -c Ryujinx
</pre>

**Notify maintainers**
@IvarWithoutBones 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.95, NixOS, 21.03pre268206.536fe36e23a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(kevincox): `""`
 - channels(root): `"nixos-21.03pre268206.536fe36e23a, nixpkgs-21.03pre268731.078f8937952"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute:
- ryujinx
```

**Comment by IvarWithoutBones** [comment]
This doesn't seem to be an issue in nixpkgs, but rather [upstream](https://github.com/Ryujinx/Ryujinx/issues/1393). I assume you are using Wayland, in which you need to specify the `GDK_BACKEND` environment variable to be `x11`.

**Comment by kevincox** [comment]
I can confirm that that worked. Thanks, I'll watch the upstream issue.
