### ISSUE TITLE
Can't build udisks

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#11281]
Trying to build locally `spaceFM` and having `udisks 1.0.5` as a dependency.
Can't build this pkg due to error. Indeed that one https://bugs.freedesktop.org/show_bug.cgi?id=90778
What do we need to do? Patch `udisks` in `nix`?

**Comment by domenkozar** [comment]
Yes, patch udisks 1.0.5

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/commit/1af969f8f326511c08ac7e05a9b9cad049b18df4
