### ISSUE TITLE
DOC Python: python setup.py develop is not used anymore

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11285]
Thanks for https://github.com/NixOS/nixpkgs/pull/11086 @domenkozar 

As I was just writing parts in the [tutorial](https://github.com/FRidh/python-on-nix/blob/master/tutorial.md) about Python development I noticed that the manual still mentions that `python setup.py develop` is used although it now uses `pip install -e`.

**Comment by domenkozar** [comment]
fixed in c368489
