### ISSUE TITLE
Several go packages fail for lack of perl in path

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#11282]
I cannot identify clear culprit, but some time in the last 48 hours or so, something seems to have changed such that a range of go packages have begun failing for want of perl (which is, incidentally, hilarious :):

```
building path(s) ‘/nix/store/3j14b2xc0h3kni3c1mp4myawlk9x1raj-go1.5-govers-2015-01-09’, ‘/nix/store/695d3iyl9rr8xrs02hngvz6szgpq70ls-go1.5-govers-2015-01-09-bin’
unpacking sources
unpacking source archive /nix/store/sx0z80s66yq7pjfphrqfkqm7m3xj57pg-govers-3b5f175f65d601d06f48d78fcbdb0add633565b9-src
source root is govers-3b5f175f65d601d06f48d78fcbdb0add633565b9-src
patching sources
configuring
building
sh: perl: command not found
parallel: Error: No more processes: cannot run a single job. Something is wrong at github.com/rogpeppe/govers.
builder for ‘/nix/store/p5w8d92gbpr5bd9c2g9iv9n8p4a6srg0-go1.5-govers-2015-01-09.drv’ failed with exit code 255
```

I don't know how widespread the issue is.

**Comment by mdorman** [comment]
@pSub A git bisect identified your commit, ed2b30dc283f2ec326fe80dc5259682d1f0f4fb3 as the commit that broke this.  Your change to get a new version of parallel is fine, but the other changes in the code fail.

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/11283.
