### ISSUE TITLE
nodePackages: generate.sh

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#112846]
**Describe the bug**
when running the generate.sh script to add a new nodePackage, I get the following error
`Error: ENOENT: no such file or directory, open '/nix/store/pr5lnglmrcbbrdl0d2cbgzaln4rk6293-node_node2nix-1.9.0/lib/node_modules/node2nix/nix/node-env.nix'`

Here are the whole content of the file
```
#!/usr/bin/env bash
set -eu -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
node2nix=$(nix-build ../../.. --no-out-link -A nodePackages.node2nix)

cd ${DIR}
rm -f ./node-env.nix
${node2nix}/bin/node2nix -i node-packages.json -o node-packages.nix -c composition.nix
```
I'm guessing that rm -f command is failing.

**To Reproduce**
1. add the two packages `@swc/core` and `@swc/cli` to the file located in `./pkgs/development/node-packages/node-packages.json` 
2. run the script `cd pkgs/development/node-packages && ./generate.sh`
3. it should give you the failure.

**Expected behavior**
script to run to add a node package should run without failing

**Screenshots**

**Additional context**
I'm running on darwin, that could explain it.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by svanderburg** [comment]
@happysalada Can you check the content of that directory: `/nix/store/pr5lnglmrcbbrdl0d2cbgzaln4rk6293-node_node2nix-1.9.0/lib/node_modules/node2nix/nix`? 

There should be a file called: `node-env.nix` in it. Probably, it's missing and as a result it can no longer be copied.

Maybe the package got modified in the Nix store?

You can try garbage collecting it (e.g. by making sure `node2nix` is no longer use by having it in a Nix profile), then run:

```bash
nix-store --delete `/nix/store/pr5lnglmrcbbrdl0d2cbgzaln4rk6293-node_node2nix-1.9.0
```

The above command will succeed if node2nix is considered garbage.

Then try installing it again. It will be redeployed from scratch, most likely bringing that missing file back again.

**Comment by happysalada** [comment]
It's weird, I don't have that folder at all
```
❯ exa /nix/store/pr5lnglmrcbbrdl0d2cbgzaln4rk6293-node_node2nix-1.9.0
"/nix/store/pr5lnglmrcbbrdl0d2cbgzaln4rk6293-node_node2nix-1.9.0": No such file or directory (os error 2)
```
I have node2nix installed on my system
``` 
❯ which node2nix
/run/current-system/sw/bin/node2nix
```

however it doesn't appear in my store
```
❯ nix-env --query --installed
home-manager-path
jq-1.6
```
I'm not sure why that is

I am using home-manager on darwin. I tried installing node2nix on nix-darwin directly, but the error persists.
Not sure what to do next.

**Comment by happysalada** [comment]
After doing some more digging, this is the version of node2nix that I have installed
/nix/store/1s2r52mndlpg6qjxvpdpjyczxjrvxg1j-node_node2nix-1.9.0
the nix version that gives me an error is the one generated by the generate.sh script.
To make sure I added `echo ${node2nix}` after `cd ${DIR}`
and this is what I got
/nix/store/pr5lnglmrcbbrdl0d2cbgzaln4rk6293-node_node2nix-1.9.0

So it is the result of the command
`node2nix=$(nix-build ../../.. --no-out-link -A nodePackages.node2nix)`
if i put a ls to verify the existence of the missing file, it appears
`ls ${node2nix}/lib/node_modules/node2nix/nix/`
will give `node-env.nix`

looking at the generate.sh, I noticed the --no-out-link. Meaning that perhaps my gc is running too often.
My settings are the following though
```
    gc = {
      automatic = true;
      options = "--delete-older-than 7d";
      interval = {
        Hour = 24;
        Minute = 0;
      };
    };
```
I don't know what could be triggering the garbage collector. That is the only explanation I see for why the folder can't be found after I run the script.
I'm trying with deleting the `--no-out-link` to see if it has any effect.

**Comment by happysalada** [comment]
Just opened a PR for a potential fix in case you are interested
https://github.com/NixOS/nixpkgs/pull/113170

**Comment by svanderburg** [comment]
@happysalada I already thought this could have something to do with it. I'll see if I can take a look at the PR.

**Comment by happysalada** [comment]
@svanderburg thanks!

**Comment by roberth** [comment]
Can't close with magic comments  https://github.com/NixOS/nixpkgs/pull/113170#issuecomment-779655520, so closing manually for you.

**Comment by happysalada** [comment]
@roberth Thanks!
