### ISSUE TITLE
Why do we need a shebang in nix-prefetch-git?

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#11284]
At

https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/nix-prefetch-git#L1

we have a /bin/sh shebang without explanation for its necessity. We were just bitten by it: we have a copy of the file with some extra modifications and on my NixOS system it behaved differently inside `nix-build` than on my colleague's non-NixOS system as `/bin/sh` means something else for both of us.

Can we just remove the shebang? I was told that by default (nix-provided) bash will be used to run the scripts in nix-build environment and if that's true, that's a free impurity we can remove.

**Comment by peti** [comment]
The shebang is necessary, IMHO, but we should have it refer to `/usr/bin/env bash` rather than `/bin/sh` if the script depends on `bash` rather than `sh`.

**Comment by Fuuzetsu** [comment]
It still seems like an impurity we could get rid of to me. If we want the shebang so we can execute it as stand-alone thing, why not have two versions? One without shebang which would use the bash provided by the build-env and this is the version that would be used by fetchgit and another with shebang that user could call wherever which would probably in turn just call shebang-less version.

**Comment by peti** [comment]
I don't see what impurity you refer to. When that the generic builder's `fixup` hook is done with that script, the `/usr/bin/env bash` construct will have been replaced by a straight `bash` shebang will complete path and everything.

Generally speaking, I don't understand where the notion comes from that bash scripts could be executed without a shebang in the first place. Do you have a resource that explains this phenomenon? When users install the `nix-prefetch-script` package, I'm pretty sure that they'll be surprised to find that they have to execute the provided binaries by calling `bash /some/path/nix-prefetch-git`.
