### ISSUE TITLE
etebase-server customIni option is broken

### ISSUE THREAD

**Issue by critbase** [NixOS/nixpkgs#112834]
**Describe the bug**
using the `services.etebase-server.customIni` option doesn't override the default config properly; rather, it just sets `ETEBASE_EASY_CONFIG_PATH` in the etebase-server.service unit file to the value of `customIni` verbatim.
**To Reproduce**
1. enable etebase-server and set customIni to anything
2. watch as the service file fails instantly

**Expected behavior**
etebase-server working;
more specifically:
for the contents of customIni to be added to a file in /nix/store and for ETEBASE_EASY_CONFIG_PATH to be set to the path of that file

**Screenshots**
![image](https://user-images.githubusercontent.com/12738442/107713622-a640e900-6c99-11eb-8647-2d4711b5b81e.png)
![image](https://user-images.githubusercontent.com/12738442/107713658-bf499a00-6c99-11eb-9396-ce3df7f41110.png)

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.13, NixOS, 21.03.20210210.758b29b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre269213.3d5946bfbec, nixpkgs-21.03pre268853.d9c6f13e13f"`
 - channels(tatsuya): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by felschr** [comment]
Good catch, `customIni` requires a file path while the documentation makes it seem like the config should be inlined.
I'll start working on improving this right away.

For now, you can do something like this if you don't want to reference a file outside the nix store:
```
services.etebase-server.customIni = toString (pkgs.writeText "etebase-server.ini" ''
  [global]
''
```
