### ISSUE TITLE
Rofi-calc is broken

### ISSUE THREAD

**Issue by jdupak** [NixOS/nixpkgs#112938]
**Describe the bug**
Package rofi-calc does not add calc ability to rofi. Seem like it does not modify rofi. See screenshot for details.

I am still not entirely sure, how plugins are supposed to work in nix, so I was not aple to debug deeper.

**To Reproduce**
1. `nix-env -iA nixpkgs.rofi nixpkgs.rofi-calc`
2. `rofi -show calc -modi calc -no-show-match -no-sort`

**Expected behavior**
Rofi opens with calculator.

**Screenshots**
![image](https://user-images.githubusercontent.com/22683640/107819148-f93d9d80-6d78-11eb-9386-11ee2df936b2.png)

**Notify maintainers**
@luc65r
@albakham

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(viper): `"home-manager, nixpkgs-21.03pre259350.2ae527c50e0"`
 - nixpkgs: `/home/viper/.nix-defexpr/channels/nixpkgs`

**Comment by luc65r** [comment]
You need to override the rofi package:
```nix
rofi.override { plugins = [ rofi-calc ]; }
```

**Comment by jdupak** [comment]
Thanks, that explains a lot.

**Comment by jdupak** [comment]
It might be a good idea, to add it to the package source in a comment for people not yet fluent with nix. That was the first place I looked for help.

**Comment by jdupak** [comment]
![image](https://user-images.githubusercontent.com/22683640/107823491-2b9ec900-6d80-11eb-8a55-0455e2ec049f.png)
I this, this is what mislead me the most.

**Comment by chapa** [comment]
@luc65r @albakham I aggree with @jdupak, it's really non trivial to have to install a package this way.

Especially since when you go to the sources of `rofi` you will not find any mention of this `plugin` attribute (because it stands in [wrapper.nix](https://github.com/NixOS/nixpkgs/blob/f4a5fb66058a6b5a1efa57f78b039b7bd9c44215/pkgs/applications/misc/rofi/wrapper.nix))
