### ISSUE TITLE
package proxychains is broken

### ISSUE THREAD

**Issue by fruit-in** [NixOS/nixpkgs#112929]
**Describe the bug**
Failed to build `pkgs.proxychains`.

**To Reproduce**
1. add `pkgs.proxychains` in `environment.systemPackages`
2. nixos-rebuild switch

**Expected behavior**
Build successful.

**Screenshots**
![](https://raw.githubusercontent.com/inpic/pic/pic/issues/nixpkgs/112929/build-proxychains.png)

**Additional context**
[My configuration.nix](https://github.com/fruit-in/my-little-configuration/blob/edd86666bd552fac277d9a9a9d1c2dc825132a9b/nixos/configuration.nix#L129)

**Notify maintainers**
@siraben

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.96, NixOS, 21.03pre269485.a58a0b5098f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fabaff** [comment]
New warnings/error are introduced with new GCC releases.

**Comment by fabaff** [comment]
@fruit-in, could you please give #112994 a try?

**Comment by fruit-in** [comment]
> @fruit-in, could you please give #112994 a try?

Yes. It works.
