### ISSUE TITLE
ec2_sd_config filters field not generated correctly in yaml

### ISSUE THREAD

**Issue by sylvainf911** [NixOS/nixpkgs#112919]
**Describe the bug**
When generating the prometheus.yml file from Nix, the ec2_sd_config type allows to add a `filters`
field with a list of `name` and `value` in attribute sets.

When the `prometheus.yml` file is generated and checked with `promtool`, it returns the following:

```
FAILED: parsing YAML file /nix/store/7b70mdjan99jk922xb1gwk3jfsmrvpmq-prometheus.yml-checkconfig-checked: yaml: unmarshal errors:
line 36: field value not found in type ec2.Filter
```

The generated file being invalid, the Prometheus configuration is not accepted.

**To Reproduce**

Add a `filters` to your `ec2_sd_configs`

```
filters = [
  { name = "instance-state-name"; value = ["running"]; }
];
```
and do a `nixos-rebuild switch`. The promtool should give you an error about `ec2.Filter`.

**Expected behavior**

The Prometheus documentation state the filters value should be named `values` (plural) instead of singular:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config

So the key `values` should be used instead of `value`.

**Notify maintainers**
@willibutz

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.96, NixOS, 20.09.3087.2394284537b (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by MrRacoon** [comment]
Looks like this was fixed via: #86239

**Comment by sylvainf911** [comment]
Yes your are right, this commit fixes it in master. But it is still "value" (singular) in nixos-20.09.

Thank you.

**Comment by MrRacoon** [comment]
https://github.com/NixOS/nixpkgs/commit/3130543238aed25989010d6dab09244616214a0f

I believe it's on its way now

**Comment by sylvainf911** [comment]
Ok, great. Thank you.
