### ISSUE TITLE
package wkhtmltopdf wants a patched qt

### ISSUE THREAD

**Issue by Renha** [NixOS/nixpkgs#112926]
## Issue description
While trying to use wkhtmltopdf I could not use some of its features because it complains that it needs a patched qt which is located at https://github.com/wkhtmltopdf/qt 

### Steps to reproduce
Run `wkhtmltopdf` with an option `--enable-forms` and observe a message stating that qt is unpatched.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-134-generic, Ubuntu, 18.04.5 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(tecon-user): `"nixpkgs-20.09.2555.41dddb12837"`

**Comment by elohmeier** [comment]
related PR: #96379

**Comment by zimbatm** [comment]
fixed by switching to wkhtmltopdf-bin in #327641
