### ISSUE TITLE
Python: nix-shell with buildEnv is broken

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11303]
Executing `nix-shell` with a `shell.nix` containing
```
with import <nixpkgs> {};

( pkgs.python35.buildEnv.override  {
  extraLibs = with pkgs.python35Packages; [ numpy toolz ];
}).env
```
will give you the interpreter, but not the extra libs `numpy` and `toolz`.
@domenkozar

**Comment by domenkozar** [comment]
It works for me. Note that `python` is `python2.7` from your system, you should invoke `python3 -c "import numpy"`

**Comment by FRidh** [comment]
oh my, I must be sleepy still...
Thanks.

**Comment by domenkozar** [comment]
Happy to help :)

**Comment by FRidh** [comment]
ok, I really do have an issue here. When I try again it just does not work.
```
freddy@fr-laptop:/tmp$ cat shell.nix 
with import <nixpkgs> {};

( pkgs.python35.buildEnv.override  {
  extraLibs = with pkgs.python35Packages; [ numpy toolz ];
}).env
```

```
freddy@fr-laptop:/tmp$ nix-shell -I nixpkgs=~/Code/nixpkgs --option extra-binary-caches https://hydra.nixos.org --pure --run "python3 -c 'import toolz'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'toolz'
```

```
freddy@fr-laptop:~/Code/nixpkgs$ git log -1
commit ade9f7167dd1fec622c1f0ff7725cb6f6743b45d
Author: Peter Simons <simons@cryp.to>
Date:   Fri Nov 27 11:16:29 2015 +0100

    nix-prefetch-git: make sure the script is interpreted by bash
    
    Fixes https://github.com/NixOS/nixpkgs/issues/11284.
```

**Comment by domenkozar** [comment]
@FRidh can you pull master and try again?

**Comment by FRidh** [comment]
It seems that while the `nix-shell` is active, dependencies, like `toolz` can be garbage-collected. I don't think that should be possible. I just tested, and that was not possible before.

**Comment by FRidh** [comment]
Just tested, and indeed it's fixed. They aren't gc-ed anymore either.

**Comment by domenkozar** [comment]
Yes, packages used with `nix-shell` are not added to gc root. You have to use something like https://nixos.org/wiki/Development_Environments#Making_a_Persistent_nix-shell_Environment

**Comment by FRidh** [comment]
What I meant was, when I ran `nix-collect-garbage -d` while I still had the `nix-shell` open. Before the fix, dependencies of the environment were `gc-ed`, while now they aren't.

Anyhow, its works now :)
