### ISSUE TITLE
server/trafficserver: 9.0.0

### ISSUE THREAD

**Issue by heroku-miraheze** [NixOS/nixpkgs#113016]
**Project description**
Apache Traffic Server

**Metadata**

* homepage URL: https://trafficserver.apache.org
* source URL: https://downloads.apache.org/trafficserver/trafficserver-9.0.0.tar.bz2
* license: gpl2+
* platforms: unix

**Comment by dotlambda** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/111750
