### ISSUE TITLE
Libreddit as service (Rust-based frontend to reddit)

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#113066]
**Project description**
10 second pitch: Libreddit is a portmanteau of "libre" (meaning freedom) and "Reddit". It is a private front-end like Invidious but for Reddit. Browse the coldest takes of r/unpopularopinion without being tracked.

Demo: https://libredd.it/

**Metadata**

* homepage URL: https://libredd.it/
* source URL: https://github.com/spikecodes/libreddit
* license: agpl3
* platforms: unix, linux, darwin, ...

**Comment by fabaff** [comment]
@srid, could you please give #113185 a try? Thanks

**Comment by srid** [comment]
@fabaff That's just the package, but not a service (like `services.nginx`) right?

**Comment by fabaff** [comment]
Yes, it's only the package for the moment.

**Comment by fabaff** [comment]
There seems to be a bug https://github.com/spikecodes/libreddit/issues/128 present in the latest release. 

I opened a feature request (https://github.com/spikecodes/libreddit/issues/127) which could improve the service.

Sorry, it will take some time till we can finish this.
