### ISSUE TITLE
gcc wrapper has undeclared runtime dependency on coreutils in PATH

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#11307]
while playing around with the new docker integration (https://github.com/NixOS/nixpkgs/pull/11156), I ran into an issue that the gcc wrapper isn't self contained - it depends on someone else having set the PATH to include coreutils. the wrapper should either set the path itself, or use absolute paths. Here's what I see.

```
[anders@gurney:~/playground/nix-docker]
$ cat gcc.nix 
with import <nixpkgs> { };
with dockerTools;

rec {
  image = buildImage {
    name = "gcc";
    config = {
      Cmd = [ "${gcc}/bin/gcc" ];
    };
  };
}
[anders@gurney:~/playground/nix-docker]
$ nix-build gcc.nix -Q -A image && sudo docker load -i result && sudo docker run --rm gcc
/nix/store/wxzm781xqshv47sz2siznwjq6jhncq7l-gcc.tar.gz
/nix/store/4n9yj90rdggqcx34ylbshryg3rf9cqpj-gcc-wrapper-4.9.3/nix-support/add-flags.sh: line 5: cat: command not found
/nix/store/4n9yj90rdggqcx34ylbshryg3rf9cqpj-gcc-wrapper-4.9.3/nix-support/add-flags.sh: line 17: cat: command not found
/nix/store/4n9yj90rdggqcx34ylbshryg3rf9cqpj-gcc-wrapper-4.9.3/nix-support/add-flags.sh: line 25: cat: command not found
gcc: fatal error: no input files
compilation terminated.
```

**Comment by garbas** [comment]
@anderspapitto i think gcc is intended to be used from stdenv ... could you try it with ``${stdenv}/bin/gcc``?

**Comment by garbas** [comment]
@anderspapitto ignore me .. that was not good idea from me

**Comment by garbas** [comment]
you think you could provide a patch against ``staging`` branch for this?

**Comment by vcunat** [comment]
This was fixed during https://github.com/NixOS/nixpkgs/pull/11798. Now it works well to run e.g. `env PATH= ./result/bin/gcc hello.c`
