### ISSUE TITLE
leksah does not start

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#11304]
I've installed leksah and try to run it but it fails with this output:

====
Using default Yi configuration

** (leksah:24955): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Linked with -threaded
Reading keymap from /nix/store/d7l1l0vl3xdnm1ka4xk8ac1y9p5cqlal-leksah-0.15.1.4/share/x86_64-linux-ghc-7.10.2/leksah-0.15.1.4/data/keymap.lkshk

(leksah:24955): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

(leksah:24955): GLib-GObject-WARNING **: The property GtkToolButton:stock-id is deprecated and shouldn't be used anymore. It will be removed in a future version.
Icon 'window-close' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'document-new' for stock: Icon 'document-new' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'document-save' for stock: Icon 'document-save' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'window-close' for stock: Icon 'window-close' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'edit-undo' for stock: 

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'edit-redo' for stock: 

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'edit-find' for stock: Icon 'edit-find' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'go-previous' for stock: 

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'go-next' for stock: 

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'go-previous' for stock: 

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'go-next' for stock: 

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'edit-find-replace' for stock: Icon 'edit-find-replace' not present in theme Adwaita

(leksah:24955): Gtk-WARNING **: Error loading theme icon 'window-close' for stock: Icon 'window-close' not present in theme Adwaita
Now updating system metadata ...
callCollector
leksah: Icon 'window-close' not present in theme Adwaita

===

**Comment by vcunat** [comment]
I'd expect this is intended to be solved in #10351.

**Comment by puffnfresh** [comment]
Confirmed it didn't work in 15.09 but now works for me on master :+1:
