### ISSUE TITLE
Nextcloud well-known rules use scheme from nginx, causing potential issues behind reverse proxies.

### ISSUE THREAD

**Issue by witchof0x20** [NixOS/nixpkgs#113155]
**Describe the bug**
Relatively minor issue, but the redirect rules caldav/carddav use the $scheme variable from nginx, which causes them to return an `http://` redirect even when behind an https reverse proxy. I believe this causes a warning in the nextcloud administration area.

Having these instead use the value of `services.nextcloud.config.overwriteProtocol` or `services.nextcloud.https` might be a good idea 

https://github.com/NixOS/nixpkgs/blob/2118cf551b9944cfdb929b8ea03556f097dd0381/nixos/modules/services/web-apps/nextcloud.nix#L597
https://github.com/NixOS/nixpkgs/blob/2118cf551b9944cfdb929b8ea03556f097dd0381/nixos/modules/services/web-apps/nextcloud.nix#L600

**To Reproduce**
1. `curl -v https://my.nextcloud.domain/.well-known/caldav` when nextcloud is behind a HTTPS reverse proxy

**Expected behavior**
`Location` is `https://my.nextcloud.domain/remote.php/dav` rather than `http://my.nextcloud.domain/remote.php/dav`

**Screenshots**
![nextcloud](https://user-images.githubusercontent.com/36118348/107889646-1772dd00-6ee2-11eb-82d3-a176fad2c2e5.png)

**Notify maintainers**
@Ma27 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94-hardened1, NixOS, 20.09.2947.2b9daa020d4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2947.2b9daa020d4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
Thanks for your report and the `curl`-oneliner to reproduce! :) 
I'll probably have some time tomorrow to write a fix.
