### ISSUE TITLE
QEmu: virtiofsd prone to be garbage collected.

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#113172]
**Describe the bug**
libvirt can't find `virtfiofsd`
I'm unsure how to reference virtiofsd via libvirt xml without it being garbage collected.
I'm currently hard coding nix store:
```
$ find /nix -name 'virtiofsd'
/nix/store/c3nr4r9ld8np3yz31circxfqipinfchq-qemu-5.2.0/libexec/virtiofsd
/nix/store/2h7s274cwhw708giflvr1p3329ypm3vr-qemu-5.2.0/libexec/virtiofsd
```

**Expected behavior**
A consistent reference to virtiofsd either via a link in `/run/current-system` or putting it on the $PATH.

**Additional context**
https://libvirt.org/kbase/virtiofs.html#host-setup

**Notify maintainers**
@eelco

**Comment by anton-dessiatov** [comment]
It's not not perfect, but adding the following snippet to `configuration.nix` does the trick for me.

```nix
  environment.systemPackages = [
    (pkgs.stdenv.mkDerivation {
      name = "virtiofsd-link";
      buildCommand = ''
        mkdir -p $out/bin
        ln -s ${pkgs.qemu}/libexec/virtiofsd $out/bin/
      '';
    })
  ];
```

I have the following line in my virtual machine XML to make use of it:
```
<binary path='/run/current-system/sw/bin/virtiofsd' xattr='on'>
```

**Comment by Madouura** [comment]
Still important to me.

**Comment by ckiee** [comment]
Sorry about the spam, I had to push to my fork in order to test it and I managed to have this crappy typo that I missed for a while.. Anyway, that PR should fix it.

**Comment by kvtb** [comment]
That's what `/run/libvirt/nix-emulators/` and `/run/libvirt/nix-helpers/` are for.
Th have stable links in xml files which survive upgrades of `libvirt` and `qemu`, hibernation of guests, reboots of host, GCs and all of those interleaved.
