### ISSUE TITLE
qutebrowser: gstreamer doesn't work.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#11328]
@jagajaga 
When opening a media file, it'll try to download instead of stream.

At first I was testing with mp3's and I though lack of bad/ugly was the problem, but that didn't help.
[Here](https://github.com/magnetophon/nixpkgs/blob/8c44b45-borknix/pkgs/applications/networking/browsers/qutebrowser/default.nix) is my WIP, which also fixes https://github.com/NixOS/nixpkgs/issues/8568

**Comment by jagajaga** [comment]
Maybe you will create PR? :)

**Comment by magnetophon** [comment]
@jagajaga 
The pkg I linked too fixes the :help issue, but not the gstreamer one.
I'm hoping to get both working before I do a PR, if that's OK.

**Comment by jagajaga** [comment]
That's OK.

**Comment by magnetophon** [comment]
Got an idea why gstreamer doesn't work?  Or does it, for you?

**Comment by jagajaga** [comment]
It doesn't work for me, but I thought that that's a default behavior..

**Comment by magnetophon** [comment]
According to @The-Compiler, opening a media file should automatically stream it.

**Comment by jagajaga** [comment]
Maybe we can take a look how `firefox` is packaged in nixpkgs?

**Comment by rnhmjoj** [comment]
I think [jumanji](https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/pkgs/applications/networking/browsers/jumanji/default.nix), another vim-like browser, has the same problem.
Even after enabling web plugins it still downloads the media while it should stream them instead.

**Comment by Profpatsch** [comment]
(triage) is it still broken?

**Comment by FRidh** [comment]
This is a very old issue, and since nobody replied last time either I am closing this. Please open a new issue if the problem still exists.
