### ISSUE TITLE
python: hash mismatch setuptools 18.2, Python 2.7

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11320]
```
hash mismatch in downloaded path ‘/nix/store/a45l8r0zqfr5jhqswqqcya28h59n63js-python2.7-setuptools-18.2’: expected 50db90fe916eca8cbba2f3a1a00dae35c4f3d40a25ff693487938bf38ae8ff3a, got 563b3d1b693c5579ef6f05544ff72fc30a26e13e506ee5265eea81081c331b6d
```
Odd that the hash has changed.
@domenkozar

**Comment by domenkozar** [comment]
Huh, hash should be `07avbdc26yl2a46s76fc7m4vg611g8sh39l26x9dr9byya6sb509`. Can you run `nix-store --repair --verify` as root?

**Comment by FRidh** [comment]
Nothing shows up.

I am running `16.03pre71289.7ae05ed ` and was using current master to build Google Chrome when this occurred.

**Comment by FRidh** [comment]
actually, not sure exactly where head was at the time. Since I can't reproduce it I will close it for now.
