### ISSUE TITLE
MPV convert script is broken

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#113202]
**To Reproduce**
1. Install mpv with the convert script as explained in https://nixos.wiki/wiki/MPV
2. Start mpv and press alt+w to mark the start and end of the segment to convert
3. Press OK in the dialog that pops up

**Expected behavior**
Converted clip gets saved to $HOME as per the script's documentation

**Actual behavior**
When launching mpv it prints a warning: `[convert_script] The 'tick' event is deprecated and will be removed.`

Invoking the script causes it to crash upon pressing OK in the popup dialog:
```
[convert_script]
[convert_script] stack traceback:
[convert_script] 	[C]: in function 'fmod'
[convert_script] 	[string "/nix/store/xkpx5f50pv7kvnj4flwgahi0h5p8ngrm-m..."]:592: in function 'call_gui'
[convert_script] 	[string "/nix/store/xkpx5f50pv7kvnj4flwgahi0h5p8ngrm-m..."]:163: in function 'fn'
[convert_script] 	mp.defaults:230: in function 'fn'
[convert_script] 	mp.defaults:65: in function 'handler'
[convert_script] 	mp.defaults:370: in function 'handler'
[convert_script] 	mp.defaults:500: in function 'call_event_handlers'
[convert_script] 	mp.defaults:534: in function 'dispatch_events'
[convert_script] 	mp.defaults:493: in function <mp.defaults:492>
[convert_script] 	[C]: in ?
[convert_script] 	[C]: in ?
[convert_script] Lua error: [string "/nix/store/xkpx5f50pv7kvnj4flwgahi0h5p8ngrm-m..."]:592: bad argument #1 to 'fmod' (number expected, got nil)
```
This does not crash mpv itself but unregisters the script and fails to produce an output file.

**Notify maintainers**

@Profpatsch

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.11, NixOS, 21.03.git.3d696882893 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.03pre268835.8c8731330b5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mpv-with-scripts
```

**Comment by sternenseemann** [comment]
Seems like the upstream gist hasn't been updated to reflect the breakage and we need to update [this patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/mpv/scripts/convert.patch) to fix the upstream changes.

**Comment by Profpatsch** [comment]
uh

**Comment by Profpatsch** [comment]
Time to fix it I guess.

I pinged the author so we can get a license https://gist.github.com/Zehkul/25ea7ae77b30af959be0#gistcomment-3715700
