### ISSUE TITLE
dbeaver: hash mismatch

### ISSUE THREAD

**Issue by Vandivier** [NixOS/nixpkgs#113224]
**Describe the bug**
similar to https://github.com/NixOS/nixpkgs/issues/81829

but applies to `https://dbeaver.io/files/7.3.5/dbeaver-ce-7.3.5-macos.dmg`

**To Reproduce**
`brew install --cask dbeaver-community`

**Expected behavior**
expect clean install

instead, receive:
```
Error: SHA256 mismatch
Expected: 953e96c1794f5b58dc10045cba799817136590ab66b88657a6f188d314d5a70b
  Actual: 12d7cd6167a411f57ab9ece5f68dbbf0a0c689058836bb52fd0d140e5970217b
```

**Comment by yamoinza** [comment]
==> Downloading https://dbeaver.io/files/21.0.0/dbeaver-ce-21.0.0-macos.dmg
Error: SHA256 mismatch
Expected: db25d2369bbfaa452538e56adfa272f2e6dcca08055a2c5eb2a41884d08eb39b
  Actual: 9e0e6dd8248b7a100aa56668684769b1d7d74a667bb516ae60e1fed18eb3e70f

**Comment by bnjmnt4n** [comment]
Seems like you used homebrew for installation of dbeaver, so this issue shouldn't be opened in the nixpkgs repository.

**Comment by Vandivier** [comment]
@bnjmnt4n agree
