### ISSUE TITLE
Shebangs of some perl packages have several duplicates

### ISSUE THREAD

**Issue by xworld21** [NixOS/nixpkgs#113330]
**Describe the bug**
Some Perl packages have `-I` entries that are repeated several times. This breaks the `bin` outputs on macOS, where the shebang must fit within 512 characters or so.

I am submitting PRs to add `shortenPerlShebang` when I hit this problem, but it feels like a bandaid.

**To Reproduce**
See the `PerlTidy` and `DevelNYTProf` outputs before my `shortenPerlShebang` PRs. For instance, the `perltidy` script without using `shortenPerlShebang` starts with (newlines added for readability):
```
#!/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/bin/perl
  -I/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/lib/perl5/site_perl
  -I/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/lib/perl5/site_perl
  -I/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/lib/perl5/site_perl
  -I/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/lib/perl5/site_perl
  -I/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/lib/perl5/site_perl
  -I/nix/store/kphxjbcg6gkybal8a9zxmqwvhhbrnc40-perl5.32.0-Perl-Tidy-20201207/lib/perl5/site_perl
```

**Expected behavior**
The shebang should not have duplicates, for instance `perltidy` can be
```
#!/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/bin/perl
  -I/nix/store/4x1n703dm62d173qz3xzyhqwiwcmgkw2-perl-5.32.0/lib/perl5/site_perl
  -I/nix/store/kphxjbcg6gkybal8a9zxmqwvhhbrnc40-perl5.32.0-Perl-Tidy-20201207/lib/perl5/site_perl
```

**Additional context**
I am not entirely sure this is a `nixpkgs` problem, or a `MakeMaker` problem. I confess I don't understand the build system well enough, and the `shortenPerlShebang` is a reasonable solution at any rate.

**Notify maintainers**

@veprbl might know about this?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels: `"nixpkgs-21.03pre269455.3155a9e966a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by veprbl** [comment]
@xworld21 If you want to investigate, then the shebang is built here
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/perl-modules/generic/builder.sh
the value of PERL5LIB is formed here
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/perl/setup-hook.sh

**Comment by xworld21** [comment]
Ok, so I can deduplicate `PERL5LIB` in `builder.sh` to start. But I am stuck on testing. @veprbl how can I test my patch without rebuilding Perl itself? I am trying to override `builder` just for `PerlTidy`, but I am not getting anywhere. Is it even possible?

**Comment by veprbl** [comment]
Try
```nix
perlPackages.PerlTidy.overrideAttrs (_: {
  args = [ "-e" ./builder.sh ];
})
```

**Comment by aanderse** [comment]
Also keep in mind `perl.withPackages` will **always** guarantee a nice and short `PERL5LIB` value, no matter how many dependencies are listed.

ping @stigtsp in case of additional advise.

**Comment by xworld21** [comment]
A small update: patching https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/perl-modules/generic/builder.sh with the following
```bash
perlFlags=
for i in $(IFS=:; echo $PERL5LIB); do
    case "$perlFlags " in
        *" -I$i "*) ;;
        *) perlFlags="$perlFlags -I$i"
    esac
done
```
seems to deduplicate well, at least in my only test.

But the problem is deeper: by the time `builder.sh` is called, `PERL5LIB` already contains 5 copies of `perl-5.32.0/lib/perl5/site_perl`. Maybe `addPerlLibPath` is being called too many times?

It is taking me time to debug this: as soon as I touch something in the `pkgs/development/interpreters/perl` or `pkgs/development/perl-modules` folders, my computer tries to rebuild everything (binutils, gzip, python...). I think this is above my pay grade!

I can submit the PR patching `builder.sh`, which is a reasonable workaround I guess, but it will cause a substantial rebuild. Should I go ahead?

**Comment by veprbl** [comment]
> But the problem is deeper: by the time `builder.sh` is called, `PERL5LIB` already contains 5 copies of `perl-5.32.0/lib/perl5/site_perl`. Maybe `addPerlLibPath` is being called too many times?

I suppose it is natural for "env hooks" to be called several times. Perhaps it is the `addToSearchPath` that should be performing deduplication instead.

> I can submit the PR patching `builder.sh`, which is a reasonable workaround I guess, but it will cause a substantial rebuild. Should I go ahead?

Substantial rebuilds are not an issue. Just make sure to submit your PR against the "staging" branch.

**Comment by xworld21** [comment]
Many thanks @veprbl @aanderse for all the help! I have submitted a PR changing `addToSearchPath`, it seems like the sensible option. Assuming it does not break anything, of course. If the change works well, I will undo the unnecessary `shortenPerlShebang`.

**Comment by veprbl** [comment]
Time to nuke the `shortenPerlShebang`?

**Comment by veprbl** [comment]
So I've tested removing it on `biber` and it broke. This makes me conclude that the repetitions are not the only reason why those shebangs were getting too long.

**Comment by xworld21** [comment]
@veprbl thanks for noticing this, I was forgetting about it. It looks like 6 distinct dependencies are already enough to break the scripts on darwin so deduplicating is not enough. I should be able to revert my old changes to perltidy and NYTProf, though, let me check.
