### ISSUE TITLE
enable automerge in GitHub settings?

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/nixpkgs#113354]
GitHub repos recently gained a setting that you can enable to show a button for [automatically merging PRs when CI passes](https://github.blog/changelog/2020-12-16-pull-request-auto-merge-public-beta/).

It would be nice to turn this on in Nixpkgs.  

## What is this setting?

In the "Merge Button" GitHub settings, there is a option "Allow auto-merge":

![image](https://user-images.githubusercontent.com/64804/108141578-59c93380-7107-11eb-9c6d-7adfcaa1a5f8.png)

If you tick this, then you get a new "Enable auto-merge" button on the PR screen:

![image](https://user-images.githubusercontent.com/64804/108143077-5be0c180-710a-11eb-8467-e8af54b62e79.png)

If you click this button, then the PR will automatically be merged after CI passes.

## Why is this useful?

Sometimes I'll make small changes to PRs submitted by other users (usually just adding comments).  I'd like to immediately merge in these PRs, but just to be safe I wait for ofborg to make sure the PR still evaluates.  I have to keep the github tab open and remember to check on it in a few minutes.  This is somewhat annoying.

If we had the automerge option enabled, I could just click "Enable auto-merge" and close the browser tab.

## Who could enable this?

It looks like an Admin would be needed to enable this.  Possibly someone like @domenkozar or @peti?

**Comment by cdepillabout** [comment]
Hmm, it appears that there is a big problem in order for Nixpkgs to enable automerge.

In order to be able to use automerge, you _must_ have branch protection rules set for the branch being merged into.

Here's what the branch protection rules setting looks like:

![image](https://user-images.githubusercontent.com/64804/108144250-a400e380-710c-11eb-9b13-8325fd107410.png)

I don't think Nixpkgs has any required CI tasks?  That means that even if we enable automerge here in Nixpkgs, you can't actually use it.  The button doesn't appear on the PR screen.

---------------------------------------

I guess this means that for now we won't be able to use automerge.

However, hopefully at some point GitHub would change the implementation, and automerge would be useful in the situation I described above.  I guess I'll leave this open for now.

**Comment by domenkozar** [comment]
That's right, we'd need to make some checks required (auto-merge is already enabled).

The problem with making checks required is that you can't commit to master anymore - so that requires careful planning.

**Comment by SuperSandro2000** [comment]
Would that make darwin ofborg checks required? They time out a lot.

**Comment by cdepillabout** [comment]
@SuperSandro2000 The GitHub settings let you pick which CI checks are required before auto-merge.

The problem that if you make _all_ checks required, then you can no longer merge things where some checks fail/timeout.  This is a problem for things like the darwin checks.

If you instead make only some checks required, then I think auto-merge might merge the PR before all the checks have finished running.  There may be times you are actually really interested in the result of darwin ofborg.

Also, @domenkozar points out that if you make checks required, you can no longer commit directly to `master`.  (I'm assuming this means without making a PR.)

Personally I feel like this is probably a good thing, but I imagine it might break some people's workflow, so we'd probably have to think long and hard about that before making this change.

**Comment by SuperSandro2000** [comment]
> Personally I feel like this is probably a good thing, but I imagine it might break some people's workflow, so we'd probably have to think long and hard about that before making this change.

Not a bad thing in my opinion. People need to stop doing that.

> If you instead make only some checks required, then I think auto-merge might merge the PR before all the checks have finished running.

This wouldn't allow us to fix ofborg if it is broken.

**Comment by cdepillabout** [comment]
Due to the way automerge corresponds with the branch protection rules, I imagine it won't be feasible for us to turn on, at least for the time-being.

Maybe we can come back to this issue if the functionality around automerge or branch protection rules changes.
