### ISSUE TITLE
Missing dependencies in Haskell environment for clash-prelude

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#11334]
When trying to make a nix environment for this repo on master, I get missing dependencies.

- At the moment, master points to this commit: https://github.com/clash-lang/clash-prelude/commit/48409067850b23d6f69d8261d90b11540d88d4a0

- I am on nixos-unstable which is at https://github.com/NixOS/nixpkgs-channels/commit/7ae05edcdd14f6ace83ead9bf0d114e97c89a83a

- `cabal2nix ./. > default.nix` is:
  ```nix
{ mkDerivation, array, base, data-default, doctest, ghc-prim
, ghc-typelits-extra, ghc-typelits-natnormalise, Glob, integer-gmp
, lens, QuickCheck, reflection, singletons, stdenv
, template-haskell, th-lift
}:
mkDerivation {
  pname = "clash-prelude";
  version = "0.10.3";
  src = ./.;
  libraryHaskellDepends = [
    array base data-default ghc-prim ghc-typelits-extra
    ghc-typelits-natnormalise integer-gmp lens QuickCheck reflection
    singletons template-haskell th-lift
  ];
  testHaskellDepends = [ base doctest Glob ];
  homepage = "http://www.clash-lang.org/";
  description = "CAES Language for Synchronous Hardware - Prelude library";
  license = stdenv.lib.licenses.bsd2;
}
  ```

- I run `nix-shell -E '(import <nixpkgs> {}).haskellPackages.callPackage ./. {}'` to get in the shell, but `cabal configure` complains:
  ```
cabal: At least the following dependencies are missing:
QuickCheck >=2.7 && <2.9,
data-default >=0.5.3,
ghc-typelits-extra >=0.1,
ghc-typelits-natnormalise >=0.3,
lens >=4.9,
reflection >=2,
singletons >=1.0 && <3.0,
th-lift >=0.5.6
  ```

- `ghc-pkg list` in shell:
  ```
/nix/store/i4rq67jd9bzbhkqzfyhfdz1pja9fapl4-ghc-7.10.2/lib/ghc-7.10.2/package.conf.d:
    Cabal-1.22.4.0
    array-0.5.1.0
    base-4.8.1.0
    bin-package-db-0.0.0.0
    binary-0.7.5.0
    rts-1.0
    bytestring-0.10.6.0
    containers-0.5.6.2
    deepseq-1.4.1.1
    directory-1.2.2.0
    filepath-1.4.0.0
    (ghc-7.10.2)
    ghc-prim-0.4.0.0
    haskeline-0.7.2.1
    hoopl-3.10.0.2
    hpc-0.6.0.2
    integer-gmp-1.0.0.0
    pretty-1.1.2.0
    process-1.2.3.0
    template-haskell-2.10.0.0
    terminfo-0.4.0.1
    time-1.5.0.1
    transformers-0.4.2.0
    unix-2.7.1.0
    xhtml-3000.2.1
```

**Comment by peti** [comment]
These commands work:

    /tmp$ git clone https://github.com/clash-lang/clash-prelude.git

    /tmp$ cd clash-prelude/

    /tmp/clash-prelude$ cabal2nix . --shell >shell.nix

    /tmp/clash-prelude$ nix-shell 

    /tmp/clash-prelude$ cabal configure 
    Resolving dependencies...
    Configuring clash-prelude-0.10.3...

    /tmp/clash-prelude$ 

It might be worthwhile to check out http://nixos.org/nixpkgs/manual/#users-guide-to-the-haskell-infrastructure, which describes these commands in great detail.

**Comment by Ericson2314** [comment]
Ah, I forgot had forgotten the `.env` in my `nix-shell` invocation. Out of curiosity, know why it makes such a difference? I thought the differences between the shell environment and normal derivation were minimal/uninteresting.

**Comment by peti** [comment]
The generic builder does not use a `ghcWithPackages` environment to compile Haskell packages, so the build environment looks quite different from what you get in the `env` attribute.

**Comment by Ericson2314** [comment]
Ah ok, that explains it. Thanks for the info!
