### ISSUE TITLE
Package stressapptest

### ISSUE THREAD

**Issue by p4block** [NixOS/nixpkgs#113403]
Stressful Application Test (or stressapptest, its unix name) is a memory interface test. It tries to maximize randomized traffic to memory from processor and I/O, with the intent of creating a realistic high load situation in order to test the existing hardware devices in a computer. It has been used at Google for some time [...]

In my experience it's an absolute monster in finding random memory errors that don't show up over weeks of real world usage. Until ECC is commonplace, running this software is necessary. 

**Metadata**

* source URL: https://github.com/stressapptest/stressapptest
* license: Apache 2.0
* platforms: linux

**Comment by fabaff** [comment]
@p4block, could you please give #113523 a try?

**Comment by p4block** [comment]
@fabaff worked no problem, thanks a lot!
