### ISSUE TITLE
Ark can't find tar #nixos

### ISSUE THREAD

**Issue by wvhulle** [NixOS/nixpkgs#11343]
I installed the gnutar archiving program and ark-15.04.3 in #nixos 15.09.706.45128de (Dingo). It is not possible to select tar as a filetype for unarchiving.

The tar binary is in my path.
[wvhulle@nord:~]$ which tar
/nix/var/nix/profiles/default/bin/tar

Ark can find most other formats as rar, 7z, and so on.

**Comment by FRidh** [comment]
Same bug occurs in unstable with 2.19 (4.14.14) 

cc @ttuegel

**Comment by ttuegel** [comment]
This is fixed in unstable with ark-15.12.0 or later.

**Comment by peti** [comment]
Has that update been backported to `release-15.09`?

**Comment by vcunat** [comment]
I'm not certain that the set of KDE packages should be updated on 15.09.

**Comment by peti** [comment]
Ah, okay. I was just wondering because @wvhulle asked specifically for help with the `release-15.09` channel, so the response "that's fixed in unstable" felt like it didn't quite address his question.

**Comment by wvhulle** [comment]
Thanks, so the set of KDE packages in 15.09, the stable one, will not get fixed?
