### ISSUE TITLE
Package request: "calendar"

### ISSUE THREAD

**Issue by bootstrap-prime** [NixOS/nixpkgs#113483]
**Project description**
A BSD util that looks for calendar files to read reminders and events attached to a date. Primarily used for "on this day in history, this happened:", and a great little utility to put alongside fortune at terminal startup.

**Metadata**

* homepage URL: https://www.openbsd.org/ 
* source URL: https://github.com/openbsd/src/tree/master/usr.bin/calendar or https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/calendar/
* license: bsd
* platforms: unix, linux, darwin

**Comment by SCOTT-HAMILTON** [comment]
This needs openbsd make https://man.openbsd.org/make.

**Comment by SCOTT-HAMILTON** [comment]
I've got a working derivation here https://github.com/SCOTT-HAMILTON/nixpkgs/blob/openbsd-calendar/pkgs/tools/misc/openbsd-calendar/default.nix, waiting for https://github.com/NixOS/nixpkgs/pull/113689 to be merged.

**Comment by Aleksanaa** [comment]
`calendar` is part of [outils](https://search.nixos.org/packages?channel=unstable&show=outils&from=0&size=50&sort=relevance&type=packages&query=outils). Correct me if I'm wrong.
