### ISSUE TITLE
boot.loader.grub.forcei686 fails when used in a flake

### ISSUE THREAD

**Issue by edrex** [NixOS/nixpkgs#113581]
I just installed nixos on an old intel mac with 32 bit uefi, so I have grub `forcei686` set.

However, when I use the experimental flake.nix support `nixos-rebuild switch` this fails with:
```
error: --- ThrownError ------------------------------------------------------------------------ nix
i686 Linux package set can only be used with the x86 family.
...
trace: while evaluating the attribute 'installBootLoader'
```

**To Reproduce**
Machine config here:
https://github.com/edrex/nixos-config/blob/master/machines/silversurfer/configuration.nix

**Expected behavior**
option works the same as without /etc/nixos/flake.nix

@matthewbauer @FlorianFranzen @edolstra

**Comment by edrex** [comment]
- Error is thrown in [stage.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/stage.nix#L181-L193).
- grub.forcei686 [seems to](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/system/boot/loader/grub/grub.nix#L13) do the [pkgs.pkgsi686Linux dance](https://nixos.wiki/wiki/Packaging/32bit_Applications) correctly.
- Only happens with /etc/nixos/flake.nix

I am new here. What am I missing? :)

**Comment by colemickens** [comment]
**flakes are not magic, they're just syntax at the edge**

This config will produce the same error without flake, if built with a nixpkgs configured for `aarch64-linux`. The error indicates that option is only valid with x86 families, and you're explicitly building that config for `aarch64-linux`: 

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }: {
     nixosConfigurations = {
       # ...
       silversurfer = nixpkgs.lib.nixosSystem {
         system = "aarch64-linux";
         modules = [ ./machines/silversurfer/configuration.nix ];
       };
     };
  };
}
```

**Comment by edrex** [comment]
Oh ok.. 
as I understand it, the purpose of the grub.forcei686 option is to install an i686 grub on an aarch64 system. Without the flake, the rest of my system is still aarch64. How can I get the same result with the flake?
