### ISSUE TITLE
Outdated JRE

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11353]
```
***
Unfortunately, we may not download file jdk-6u45-linux-x64.bin automatically.
Please, go to http://www.oracle.com/technetwork/java/javase/downloads/jdk6downloads-1902814.html, download it yourself, and add it to the Nix store
using either
  nix-store --add-fixed sha256 jdk-6u45-linux-x64.bin
or
  nix-prefetch-url --type sha256 file://path/to/jdk-6u45-linux-x64.bin

***
```
But latest JDK is *JDK 8u66* http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by markWot** [comment]
Did I try to install `oraclejdk8` (8u65) or `oraclejdk8psu` (8u66) instead of `oraclejdk`?
You can look here for other versions, by searching for oraclejdk:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix

or here:

https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/oraclejdk

**Comment by Pitometsu** [comment]
I just tried to enable jre for firefox. For now switched to iced-tea.

**Comment by markWot** [comment]
Have you tried: https://nixos.org/wiki/Using_Oracle_JDK_instead_of_Open_JDK ?

**Comment by rasendubi** [comment]
@Pitometsu adding this to your `configuration.nix` allows using newer version:

```
  nixpkgs.config.packageOverrides = pkgs: rec {
    jrePlugin = pkgs.oraclejre8;
  };
```

**Comment by Pitometsu** [comment]
@rasendubi thanks, will test it later. Plz, check it someone and close if you can. Thanks!

**Comment by grahamc** [comment]
1mo later -- anyone checked this?

**Comment by rasendubi** [comment]
I'm running with this configuration -- works fine.

**Comment by vcunat** [comment]
On master the default is Oracle's JDK 8.

**Comment by taku0** [comment]
Should we rename `jrePlugin` to `oracleJrePlugin` and make `jrePlugin` an alias for `icedtea_web`? If so, we should also rename `cfg.jre`.

**Comment by rasendubi** [comment]
`jrePlugin` is now `jre8Plugin`. Should the issue be closed?

**Comment by Pitometsu** [comment]
It's ok for me.
