### ISSUE TITLE
Caddy: import Error during parsing: File to import not found

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#113534]
**Describe the bug**
When i try to import a config file, i get an error:

```
[root@atomic:~]# nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/46lw9nk6d072s8mr7ng8mkla46zbfrmv-caddy-config-adapted.json.drv
  /nix/store/wafrwbya0svld763lcw4lj6scvinl0xb-caddy-config.json.drv
  /nix/store/ydn9bskp918zdc14fygzim0i976yy0vb-unit-caddy.service.drv
  /nix/store/gdz7d9dpq867pc3qpbk2iqj8if481izd-system-units.drv
  /nix/store/m20jyx53lr14dbkc5r5spcw6dc2wdh27-etc.drv
  /nix/store/mbw9jz7n76wvr5fay72pz2y1wyw3llay-nixos-system-atomic-20.09.3152.08327493801.drv
building '/nix/store/46lw9nk6d072s8mr7ng8mkla46zbfrmv-caddy-config-adapted.json.drv'...
adapt: /nix/store/2d0l5sv1qzhdwr892852qhgq0fjawb2y-Caddyfile:35 - Error during parsing: File to import not found: /var/www/davidak/web/Caddyfile
builder for '/nix/store/46lw9nk6d072s8mr7ng8mkla46zbfrmv-caddy-config-adapted.json.drv' failed with exit code 1
cannot build derivation '/nix/store/wafrwbya0svld763lcw4lj6scvinl0xb-caddy-config.json.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ydn9bskp918zdc14fygzim0i976yy0vb-unit-caddy.service.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gdz7d9dpq867pc3qpbk2iqj8if481izd-system-units.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/m20jyx53lr14dbkc5r5spcw6dc2wdh27-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/mbw9jz7n76wvr5fay72pz2y1wyw3llay-nixos-system-atomic-20.09.3152.08327493801.drv': 1 dependencies couldn't be built
error: build of '/nix/store/mbw9jz7n76wvr5fay72pz2y1wyw3llay-nixos-system-atomic-20.09.3152.08327493801.drv' failed
```

When i copy the exact same text in `services.caddy.config`, it does work.

The file does exist and i can read it, even with the caddy user!

```
[root@atomic:~]# sudo -u caddy cat /var/www/davidak/web/Caddyfile
www.davidak.de {
  redir https://davidak.de{uri}
}

davidak.de {
  file_server
  root * /var/www/davidak/web/
  encode gzip

  # Redirect old URLs
  redir /blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29-1024x640.png /images/celtx_auf_osx_wortspiele_polysemia.thumbnail.png permanent
  redir /blog/wp-content/uploads/2010/12/Bildschirmfoto-2010-12-14-um-19.47.29.png /images/celtx_auf_osx_wortspiele_polysemia.png permanent
  redir /fotos https://www.flickr.com/photos/davidak permanent
  redir /blog/feed /rss.xml permanent
...
}
```

So this seem to be a bug.

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Notify maintainers**
@Br1ght0ne

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 20.09.3152.08327493801 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3152.08327493801, nixos-unstable-21.05pre269929.ff96a0fa563"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: caddy2
# a list of nixos modules affected by the problem
module: caddy
```

**Comment by aanderse** [comment]
Without knowing anything about `caddy` my first guess would be this: https://github.com/NixOS/nixpkgs/blob/5c53c720ff690ef82a9fe4849e7b70c104e1c82f/nixos/modules/services/web-servers/caddy.nix#L20

Is it possible this command is evaluating your `caddy` configuration? If so, the issue is that the command is being run sandboxed so has no access outside the sandbox to your file. Build time commands can be tough.

**Comment by davidak** [comment]
That would make sense. So NixOS brakes the import feature.

**Comment by aanderse** [comment]
Out of curiosity can you please paste your relevant `caddy` config?

**Comment by davidak** [comment]
@aanderse what exactly do you want to see?

For a workaround, i just copied everything into the NixOS option: https://codeberg.org/davidak/nixos-config/src/commit/72097b257c91d9f03a9d58d36a476d3c343be5d4/machines/atomic/configuration.nix#L223-L380

But in some cases, it's nice to have the webserver config. together with the website sourcecode: https://codeberg.org/davidak/webseite/src/commit/15dbc025bb6b175b7f26e10fbe088ae18970be10/files/Caddyfile

**Comment by aanderse** [comment]
Thanks for posting. The context helps.

I think this is what you want:
```
services.caddy.config = builtins.readFile "/var/www/davidak/web/Caddyfile";
```

**Comment by symphorien** [comment]
It could make sense to add an off-by-default option to opt-out build-time configuration check.

**Comment by aanderse** [comment]
Given my above solution, I'm not sure what value it would offer in this scenario. What scenario did you have in mind @symphorien? Can this config file hold secrets maybe?

**Comment by davidak** [comment]
Then you don't have to use such a workaround on NixOS and can just use it as described in it's documentation. There can be secrets in it, but i don't see how that's relevant here: https://caddyserver.com/docs/caddyfile/directives/basicauth

**Comment by Br1ght0ne** [comment]
@symphorien Hi, module maintainer here. I was the person who made the original PR for adapting `Caddyfile`s for Caddy 2, and I had no idea about the `import` directive at the time.

The motivation was to generate TLS settings from the module options and merge them with JSON-ified `Caddyfile`. Please use `builtins.readFile` as @aanderse suggested for now, and I'll see how I can make this easier in the future.
