### ISSUE TITLE
Strange kernel config merging behaviour

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#113612]
**Describe the bug**
When including the hardened profile, a set of kernel config options are added to the common config.
This largely works as expected but the module merging seems to behave different from expectations.
New options are merged in properly, existing options are not rewritten.

**To Reproduce**
1. Import `<nixpkgs/nixos/modules/profiles/hardened.nix>` into your NixOS config
2. `nixos-rebuild boot`
3. Reboot
4. `zcat /proc/config.gz | grep PAGE_POISONING | head -1` should show `CONFIG_PAGE_POISONING=y` (correct, new option from hardened config)
5. `zcat /proc/config.gz | grep INET_DIAG | head -1` should show `CONFIG_INET_DIAG=n` but shows `CONFIG_INET_DIAG=m` instead. (Wrong, option should be overwritten by hardened config)

You can expand this by setting `MODULES=n` in `common-config.nix`, which will fail the build for `nix-build -A linux_latest_hardened.configfile` because `INET_DIAG` is not properly set to `no`.

**Expected behavior**
Config flags set in hardened config should properly overwrite values from common config.

**Additional context**
- The config is passed into `structuredExtraConfig` here: https://github.com/NixOS/nixpkgs/blob/d73afe9462a9d61006fff9f1aa6b601129a6d1f7/pkgs/top-level/all-packages.nix#L19531
- Common and hardened config get merged here: https://github.com/NixOS/nixpkgs/blob/d73afe9462a9d61006fff9f1aa6b601129a6d1f7/pkgs/os-specific/linux/kernel/generic.nix#L159
- The order of the modules to be merged does not seem to matter. Swapping common and hardened configs in the list passed to `evalModules` does not change anything

**Notify maintainers**
- @teto Added the structured config merging
- @joachifm Added the hardened config
- @talyz Seems to use the hardened profile
- @emilazy Seems to use the hardened profile

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.17-hardened1, NixOS, 21.05.git.983f4d6894d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-20.09.3160.5c53c720ff6"`
 - channels(nequi): `"home-manager, nixpkgs-21.03pre264299.01291474ea9"`
 - nixpkgs: `/home/nequi/.nix-defexpr/channels/nixpkgs`

**Comment by teto** [comment]
This was already reported. This MR doesn't work but you can follow the linked issues https://github.com/NixOS/nixpkgs/pull/106395 
Bottomline is the default merging strategy is not a good idea after all. Someone proposed to remove it altogether. Maybe it's best to disable it by default but it risks to break a few configs so it needs some thought.

**Comment by NeQuissimus** [comment]
@teto Oh! I indeed missed that PR. Thanks. Closing this as a duplicate.
