### ISSUE TITLE
bee and bee-clef systemd units contain unpatched paths

### ISSUE THREAD

**Issue by paulperegud** [NixOS/nixpkgs#113697]
Both bee.service and bee-clef.service contain ExecStart and ExecStop paths pointing to `/usr/bin/...` instead of `/nix/store/...` 

As a result, units can't be started successfully after installation.

@attila-lendvai

**Comment by sternenseemann** [comment]
See also <https://github.com/NixOS/nixpkgs/pull/109393#issuecomment-777506571>

**Comment by attila-lendvai** [comment]
@paulperegud can you tell me the steps that you did and the error that you saw?

it is expected that those files contain /usr/bin stuff because the nix service machinery will generate another service file that customizes the vanilla upstream, and upstream ExecStart/ExecStop are shadowed by it.

**Comment by attila-lendvai** [comment]
ok, my understanding of systemd, especially its user services, is clearly lacking. i'll try to catch up with them.

meanwhile, more detailed instructions would help, or examples of such services in nixpkgs, or pointers to docs that i should read.

until i can test it myself, i'll just blindly patch the bee.service and bee-clef.service files and hope that it'll be enough.

**Comment by aanderse** [comment]
The service you printed out is a `systemd` **system** level service, not a **user** level service.

This `.service` file contains several directives that entirely preclude it from being run the way you are trying to.

What you want to do cannot directly be done. You should write your own `.service` by modifying the existing to remove the offending directives (like `User`, `Group`, etc...)

**Comment by sternenseemann** [comment]
Maybe we should not install the `.service` files in the `bee-clef` derivation as it has limited usefulness anyways (as we have a proper module for it).

**Comment by aanderse** [comment]
> Maybe we should not install the `.service` files in the `bee-clef` derivation as it has limited usefulness anyways (as we have a proper module for it).

I thought the module was using the `.service` file from the package....

**Comment by attila-lendvai** [comment]
@aanderse i have added a feature to the module to start `n` bee instances (the proper way to scale up the bee service, due to architectural reasons). so, i have ended up *not* using the upstream .service file, because i dynamically generate multiple services called `bee-n`.

draft PR: https://github.com/NixOS/nixpkgs/pull/113940

i don't yet have a clear perspective what these all mean in the context of running the service as a user service.

**Comment by attila-lendvai** [comment]
short of a wiser advice, i have added a TODO not to package the upstream `.service` file.

**Comment by attila-lendvai** [comment]
https://github.com/NixOS/nixpkgs/pull/113940 is ready for review/merging. it makes it possible to start `n` number of service instances, and removes the .service files.
