### ISSUE TITLE
sshuttle: python not found

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#113734]
**Describe the bug**
Upon invokation, sshuttle immediately exits:

```
/bin/sh: line 0: exec: python: not found
client: fatal: server died with error code 127
```

**To Reproduce**
1. Install shuttle via `nix-env -iA nixos.sshuttle`
2. Run sshuttle, e.g. `sshuttle -r johannes@xx.xx.xx.xxx 0.0.0.0/0`
3. sshuttle may ask for local sudo password (as expected) before immediately crashing with above output

**Expected behavior**
Shuttle applies firewall rules and functions as a VPN over SSH

**Notify maintainers**

@domenkozar
@carlosdagos

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.10-zen1, NixOS, 21.05pre270709.6b1057b452c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre270709.6b1057b452c"`
 - channels(johannes): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by JohnAZoidberg** [comment]
https://sshuttle.readthedocs.io/en/stable/requirements.html#server-side-requirements

Is python installed on your server?

**Comment by j0hax** [comment]
@JohnAZoidberg solved!

Didn't realize the error was due to the server side. Python must have been removed from it at some point.
