### ISSUE TITLE
haskellPackages.amazonka: broken as of 21.05pre270709.6b1057b452c

### ISSUE THREAD

**Issue by LuisChDev** [NixOS/nixpkgs#113745]
**Describe the bug**
haskellPackages.amazonka is broken.

**To Reproduce**
1. nix-shell -p "ghc.withPackages (ps: with ps; [amazonka])"
You'll get a "marked as broken, refusing to evaluate" error

2. if ran with NIXPKGS_ALLOW_BROKEN=1:
(...)

``` bash
Using Parsec parser
Configuring amazonka-1.6.1...
CallStack (from HasCallStack):
  $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing or private dependencies:
unliftio-core ==0.1.*
```

this package was working fine in 20.09, but unliftio-core got updated recently to 0.2.1.0, and the previous version seems to be no longer available in current nixpkgs.

**Expected behavior**
amazonka can be loaded as usual.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.89, NixOS, 21.05pre270709.6b1057b452c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre270709.6b1057b452c"`
 - channels(chava): `"nixos-21.05pre270709.6b1057b452c, awless-0.1.11, inkscape-1.0.1, obs-studio-26.0.2, ibus-1.5.23, ngrok-2.3.35, thunderbird-78.6.1, screenkey-1.2, kmail-account-wizard-20.08.3, my-packages, kmail-20.08.3, gcc-wrapper-9.3.0, nix-du-0.3.3, git-filter-repo-2.29.0, pokerth-client-1.1.2, pavucontrol-qt-0.15.0, lsof-4.94.0, steam-run, ihp-new"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
attribute:
- haskellPackages.amazonka-*  # not necessarily broken, but harder to use
module:
-
```

**Comment by cdepillabout** [comment]
@LuisChDev If you (or anyone else) would like this fixed in `master`, please figure out what exactly needs to be fixed and send a PR to `haskell-updates`.

If you have trouble figuring this out, feel free to ask here.
