### ISSUE TITLE
cmake / Qt5 error when trying to compile newer version of RStudio

### ISSUE THREAD

**Issue by dlukes** [NixOS/nixpkgs#11385]
The derivation for the [RStudio](https://www.rstudio.com/) IDE currently available in `nixpkgs` is an older version (0.98.110) which doesn't have some of the functionality I've come to rely on. I've therefore tried to update the derivation to build version 0.99.489, which is the current stable one for which [pre-compiled binaries are available](https://www.rstudio.com/products/rstudio/download/).

The main change between the two versions seems to be that the Qt dependency has been bumped from the 4.x to the 5.x series. I therefore tried to update the build environment in the derivation accordingly (see 5b216a941a16c87f0a3e935fd0b64821feac0ef1), but I get stuck at the following error:

```
CMake Error at src/cpp/desktop/CMakeLists.txt:69 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at //lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file

     "///include/"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "//lib/cmake/Qt5Core/Qt5CoreConfig.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  //lib/cmake/Qt5Core/Qt5CoreConfig.cmake:52 (_qt5_Core_check_file_exists)
  src/cpp/desktop/CMakeLists.txt:76 (find_package)


-- Configuring incomplete, errors occurred!
```

Might this be an error that will affect other derivations depending on Qt 5?

`nixos-version` is `16.03.git.b6e1e73 (Emu)` (based on `channels/nixos-unstable`).

**Comment by knedlsepp** [comment]
Should be fixed by now.

**Comment by dlukes** [comment]
I don't have a NixOS install at hand anymore, but it's very likely, since the official RStudio derivation is currently at 1.1.351 :) I think this can be closed.
