### ISSUE TITLE
Allow nixos-rebuild without NIX_REMOTE=daemon

### ISSUE THREAD

**Issue by viric** [NixOS/nixpkgs#11384]
Currently, the only way to disable the use of NIX_REMOTE=daemon is to have the envvar undefined or with null string.

Neverthless, nixos-rebuild checks for the nix-daemon being alive, and in that case, it uses:

```
export NIX_REMOTE=${NIX_REMOTE:-daemon}
```

So, the only way to disable the remote in nixos-rebuild is to stop nix-daemon and unset NIX_REMOTE, all together.

One solution would be to allow NIX_REMOTE=0 or NIX_REMOTE=false in nix, but maybe someone can propose something simpler.

**Comment by lethalman** [comment]
It's possible to check for an unset var in bash like this:

```
if [ ! -v NIX_REMOTE ]; then
NIX_REMOTE="nix-daemon"
fi
```

This will allow an empty NIX_REMOTE.

**Comment by viric** [comment]
How can a bash program be called with a variable unset?  NIX_REMOTE= nixos-rebuild, will get it null string.

**Comment by lethalman** [comment]
@viric with `NIX_REMOTE=` it will stay empty, and with my code it will work as expected, empty remote.

If one doesn't have it unset, it will set `nix-daemon` by default. To unset a variable in bash: `unset NIX_REMOTE`.

**Comment by viric** [comment]
Ah! Empty, without remote. Unset or "daemon", with remote.

**Comment by lethalman** [comment]
Basically with the above code, `NIX_REMOTE= nixos-rebuild` works because the empty string is honored.

**Comment by Profpatsch** [comment]
(triage) any action items?

**Comment by bachp** [comment]
I tried to `NIX_REMOTE= nixos-rebuild switch` but the downloads are still going trough the deamon. It seems there is still something not working as expected.
