### ISSUE TITLE
Use systemd Out-Of-Memory Killer

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#113903]
**Describe the bug**
Systemd has implemented an Out-Of-Memory Killer in 247, and I would for sure love to have this and use it default.
Fedora has been taking measures to introduce this in their next release over recently using earlyoom
* https://fedoraproject.org/wiki/Changes/EnableSystemdOomd
* https://src.fedoraproject.org/rpms/systemd/commits/rawhide
* https://pagure.io/releng/issue/9913

and as you can see from their recent commits in their systemd build expressions they're actively tweaking the defaults.

**Comment by Profpatsch** [comment]
> How will this work if everything is in the same cgroup?
>
> It will not work as systemd-oomd acts on a per-cgroup level. Applications will need to spawn processes into separate cgroups (e.g. with systemd-run) or use a desktop environment (e.g. GNOME, KDE) that does this for them.

**Comment by kanashimia** [comment]
If you want to try oomd right now:
```nix
{ pkgs, ... }:

{
  systemd.package = pkgs.systemd.override { withOomd = true; };
  systemd.additionalUpstreamSystemUnits = [ "systemd-oomd.service" ];
  systemd.services.systemd-oomd.wantedBy = [ "multi-user.target" ];

  users.groups.systemd-oom.gid = 666;
  users.users.systemd-oom.uid = 666;
  users.users.systemd-oom.group = "systemd-oom";

  systemd.slices."-".sliceConfig.ManagedOOMSwap = "kill";
}
```

**Comment by hyperfekt** [comment]
What does everyone think about turning oomd on by default? At least my system livelocks so badly (for dozens of minutes) without oomd that it is frankly unconscionable to be shipped to end users that way.

**Comment by mohe2015** [comment]
> What does everyone think about turning oomd on by default? At least my system livelocks so badly (for dozens of minutes) without oomd that it is frankly unconscionable to be shipped to end users that way.

I agree, I also always enable earlyoom.

**Comment by hyperfekt** [comment]
Looking into this, my understanding is that systemd-oomd only became fully supported with systemd 248 and was still experiencing notable changes after the release of 247, but those changes are being backported to stable, so we should be good to enable it by default even though 21.05 will be released with systemd 247.

**Comment by Profpatsch** [comment]
Maybe the `earlyoom` should give a warning if both `oomd` and `earlyoom` are enabled?

**Comment by ilya-fedin** [comment]
Is there any progress? :thinking: 
I would love to migrated from earlyoom to systemd-oomd

**Comment by kanashimia** [comment]
> What does everyone think about turning oomd on by default? At least my system livelocks so badly (for dozens of minutes) without oomd that it is frankly unconscionable to be shipped to end users that way.

Note that turning this on by default is a _horrible_ idea, as of:
> How will this work if everything is in the same cgroup?
> It will not work as systemd-oomd acts on a per-cgroup level. Applications will need to spawn processes into separate cgroups > (e.g. with systemd-run) or use a desktop environment (e.g. GNOME, KDE) that does this for them.

In practice it means that it will kill _whole user session_ if you are using a window manager.
I have managed to hack around xmonad to start every app in a separate cgroup using `systemd-run`, but requiring every user to do this is bogus.

**Comment by Profpatsch** [comment]
Whoops sorry wrong button.


> I have managed to [hack around xmonad](https://github.com/kanashimia/nixos/blob/e2931ba7c3e59392b73085f7b6e04197a8df8831/modules/window-managers/xmonad/xmonad.hs#L20-L26) to start every app in a separate cgroup using `systemd-run` , but requiring every user to do this is bogus.

I would love to have a “thing” that captures orphaned processes into a systemd-run context, but idk if you can change cgroups after the fact. Getting these cgroups right “by construction” will require a lot of patching and policy and setup to existing tools. (Maybe a `LD_PRELOAD` around execve? But hard to get correct in general without breaking everything horribly.)

**Comment by Profpatsch** [comment]
But yes, for a desktop system, where your use-case is “don’t hang my desktop indefinitely when the load goes over 1 per CPU” I’ve had much success with just enabling `earlyoom`.
It will even kill single hungry browser tabs, since modern browsers spawn one process per tab.

Maybe both can be productively used together. Given that `systemd-oomd` works with cgroups, it sounds like it’s best for a server environment where everything is managed by systemd services.

**Comment by kanashimia** [comment]
> I would love to have a “thing” that captures orphaned processes into a systemd-run context, but idk if you can change cgroups after the fact. Getting these cgroups right “by construction” will require a lot of patching and policy and setup to existing tools. 

You can, just not using systemd-run, you would directly use dbus, or can even change them by hands using sysfs

Tbh i'm not even sure how they do it by construction, when i used dbus interface, they only had option to add existing pid, probably should look into it again.

Also not sure orphanated is the right word, but yes you probably can do something to move processes to their own cgroups, but doing it the "right way" ™ would require some thinking process.

I will try to look into it, i think some daemon that moves processes from a window manager scope to different scopes should be easily implementable, albeit sounds like a stupid hack.

Well at least GNOME and KDE Plasma have their management thing, like the one i made for xmonad, so oomd can safely enabled for them.
Actually my hack was directly inspired by their session management.

**Comment by byrongibson** [comment]
> > What does everyone think about turning oomd on by default? At least my system livelocks so badly (for dozens of minutes) without oomd that it is frankly unconscionable to be shipped to end users that way.
> 
> Note that turning this on by default is a _horrible_ idea, as of:
> 
> > How will this work if everything is in the same cgroup?
> > It will not work as systemd-oomd acts on a per-cgroup level. Applications will need to spawn processes into separate cgroups > (e.g. with systemd-run) or use a desktop environment (e.g. GNOME, KDE) that does this for them.
> 
> In practice it means that it will kill _whole user session_ if you are using a window manager.
> I have managed to [hack around xmonad](https://github.com/kanashimia/nixos/blob/e2931ba7c3e59392b73085f7b6e04197a8df8831/modules/window-managers/xmonad/xmonad.hs#L20-L26) to start every app in a separate cgroup using `systemd-run` , but requiring every user to do this is bogus.

One reason it should be opt-in is that, unless I misunderstand, it seems to require swap.  But swap is less and less necessary as RAM gets cheaper.  I'm not running any swap at all these days, just enough RAM that swap isn't needed.

**Comment by buckley310** [comment]
Based on my reading, they encourage the use of swap, but do not require it. systemd-oomd has two criteria it can react to, one being swap usage, and the other being "memory pressure". That might mean oomd needs to be configured differently for swap-enabled systems than for swap-less systems.

Personally, I generally do not swap to disk, but I do enable zramSwap.

**Comment by quantmint** [comment]
Any news on this? I would really like to have systemd-oomd on nixos.

**Comment by fgaz** [comment]
> But swap is less and less necessary as RAM gets cheaper. I'm not running any swap at all these days, just enough RAM that swap isn't needed.

Counterintuitively, swap is useful even under no/low memory contention: https://chrisdown.name/2018/01/02/in-defence-of-swap.html

**Comment by lfdominguez** [comment]
I think that oomd is not yet ready for desktop systems. In my experience earlyoom is by far more reliable than oomd, oomd kill even my DE process.

**Comment by Dietr1ch** [comment]
It seems `systemd-oomd` has been default in Fedora since [April 2021 (Fedora 34)](https://fedoraproject.org/wiki/Changes/EnableSystemdOomd). Is it really that unreliable? I haven't used it, but I'd guess it's ok and wanted to shop for an OOM-killer and give it a try in case it supports `notify-send` or something alike to avoid digging into dmesg to understand why things suddenly disappear.

**Comment by martinetd** [comment]
Hmm, my understanding is still that the default configuration it shouldn't be able to kill anything, so I'm obviously missing something here, thanks for pointing that out!

My understanding is that an half-configured systemd-oom is problematic -- it's limited in what it can kill when memory pressure happens, so it likely can't kill the culprit and will likely just kill some random slice instead..
(But I must have been understanding that wrong too if it's killing things in the default settings...)
