### ISSUE TITLE
QEMU Agent module on unstable is broken

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#113909]
**Describe the bug**
The QEMU Agent NixOS module cannot work properly as the `statedir` is incorrectly set.

**To Reproduce**
1. Run the QEMU Agent NixOS on latest version.
2. See failure of the unit.
3. Also, `nix-shell -p qemu.ga --run "qemu-ga --help"` proves the same thing.

**Expected behavior**
Either, the package does not embed the Nix path in the configuration, either it is passed `-t` to the module.

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.16-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixpkgs-21.05pre271547.a964d7094a3"`
 - channels(raito): `"nixpkgs-21.05pre271547.a964d7094a3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
attribute: qemu.ga
module: services.qemuGuest
```

cc @andir @teto

**Comment by SCOTT-HAMILTON** [comment]
I can reproduce with this ugly test ```nix
import ./make-test-python.nix ({ pkgs, ... }: {
  name = "qemu";
  meta = with pkgs.lib.maintainers; {
    maintainers = [ shamilton ];
  };

  nodes = {
    machine = { pkgs, lib, ... }: {
      services.qemuGuest.enable = true;
      environment.systemPackages = with pkgs; [ gnugrep ];
    };

  };

  testScript = { nodes, ... }: ''
    import sys 

    start_all()
    print("\n\n[log] searching for qemu service...", file=sys.stderr)
    machine.succeed('systemctl list-unit-files "*qemu*" 1>&2')
    print("\n\n", file=sys.stderr)
    print("[log] searched for qemu service")
    machine.succeed("systemctl start qemu-guest-agent.service; exit 0")
    machine.succeed("systemctl status qemu-guest-agent.service; exit 0")
    machine.succeed("journalctl -xe -u qemu-guest-agent.service 1>&2")
    machine.wait_for_unit("qemu-guest-agent.service")
  '';
})```

**Comment by TredwellGit** [comment]
Have you tried https://github.com/NixOS/nixpkgs/pull/112886?

**Comment by RaitoBezarius** [comment]
That looks like it will fix the bug, indeed
