### ISSUE TITLE
bumblebee fails to build due to xorg.conf.d/10-evdev.conf collision

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixpkgs#11396]
While trying to build a configuration from a recent commit of the master branch, while enabling NixOS' bumblebee module, the `bumblebee-env` derivation fails to build with this error (this is the full log):
```
collision between `/nix/store/qrmwam8gg6pxjir727psg2c749q4s4mq-xf86-input-evdev-2.10.0/share/X11/xorg.conf.d/10-evdev.conf' and `/nix/store/39dc3fjcfmrwp74dma66l2amnc074d3l-xorg-server-1.17.2/share/X11/xorg.conf.d/10-evdev.conf'
<3>builder for ‘/nix/store/r7rnfy1ajzd48sqb5s4aazp75jky2142-bumblebee-env.drv’ failed with exit code 2
```

I believe the `bumblebee-env` derivation is defined here: https://github.com/NixOS/nixpkgs/blob/7afc07713985a8c901a71c835504e0f15996d567/pkgs/tools/X11/bumblebee/default.nix#L42-L57

Any idea what the problem might be?

**Comment by abbradar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/95629cf6f83cee1b8200f6fd408a206ea4e858b1 . I did lots of other fixes to, e.g. we don't have separate `optirun` and `optirun32` now for those who use them, and have nouveau support!
