### ISSUE TITLE
git error when running nix-prefetch-git on some repositories

### ISSUE THREAD

**Issue by CajuM** [NixOS/nixpkgs#113926]
When running nix-prefetch-git on some repositories, the following error is thrown:
`fatal: git cat-file: could not get object info`
This is the case for repositories with submodules. And if any submodule points to a ref outside a branch.

**To Reproduce**
1. `nix-prefetch-git --builder --url https://github.com/decaf-emu/decaf-emu.git --out source --rev 6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6 --fetch-submodules`

**Expected behavior**
The above command ought complete successfully.

**Notify maintainers**
@thomasjm

**Context**
The above command was taken from fetchFromGitHub. The error was seen when trying to build a derivation with:
```nix
fetchFromGitHub {
  owner = "decaf-emu";
  repo = "decaf-emu";
  fetchSubmodules = true;
  rev = "6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6";
  sha256 = "1aa1ld00vczzndb3iy7i8zll4175gx20zgz003n5f03113jpr3as";
}
```
The offending submodule in this case is:
`
 4b796627ad0fa42640f5fdb96f23c4a0d9ee084f libraries/gsl-lite (4b79662)
`

**Comment by CajuM** [comment]
Would the following be a proper fix?

```diff
diff --git a/pkgs/build-support/fetchgit/nix-prefetch-git b/pkgs/build-support/fetchgit/nix-prefetch-git
index f2df9d9a869..a44df7618f3 100755
--- a/pkgs/build-support/fetchgit/nix-prefetch-git
+++ b/pkgs/build-support/fetchgit/nix-prefetch-git
@@ -148,7 +148,7 @@ checkout_hash(){
         hash=$(hash_from_ref "$ref")
     fi

-    clean_git fetch -t ${builder:+--progress} origin || return 1
+    clean_git fetch -t ${builder:+--progress} origin $hash || return 1

     local object_type=$(git cat-file -t "$hash")
     if [[ "$object_type" == "commit" ]]; then
```

**Comment by MetaDark** [comment]
I've also run into this problem with one of my NUR packages. This may fail on some git servers that don't `uploadpack.allowReachableSha1InWant` enabled, so it should fall back to a normal clone.

I've been using this patch that allows performs a shallow clone: https://github.com/MetaDark/nixpkgs/commit/ec5940e4149bc30c12520abb40571673b3e7286a.
