### ISSUE TITLE
Declarative containers broken since systemd-219

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#11408]
NixOS declarative containers (`containers.<name>.*`) have been broken since the upgrade to systemd-219 (fe952a42a7898574a1a2f5ac4b386c6bdd713b2e). The containers fail to start. There is nothing relevant in `dmesg`, and the system journal looks like this:
```
Dec 02 10:14:45 mugen systemd[1]: Starting Container 'quassel'...
Dec 02 10:14:45 mugen container quassel[786]: Spawning container quassel on /var/lib/containers/quassel.
Dec 02 10:14:45 mugen container quassel[786]: Press ^] three times within 1s to kill container.
Dec 02 10:14:45 mugen container quassel[786]: Container quassel failed with error code 1.
Dec 02 10:14:45 mugen systemd[1]: container@quassel.service: main process exited, code=exited, status=1/FAILURE
Dec 02 10:14:45 mugen container quassel[795]: cat: /run/containers/quassel.pid: No such file or directory
Dec 02 10:14:45 mugen systemd[1]: container@quassel.service: control process exited, code=exited status=1
Dec 02 10:14:45 mugen systemd[1]: Failed to start Container 'quassel'.
Dec 02 10:14:45 mugen systemd[1]: Unit container@quassel.service entered failed state.
Dec 02 10:14:45 mugen systemd[1]: container@quassel.service failed.
Dec 02 10:14:45 mugen systemd[1]: container@quassel.service holdoff time over, scheduling restart.
```

A minimal configuration which reproduces this is:
`quassel.nix`:
```
{ config, lib, pkgs, ... }:
{
  services.openssh.enable = true;
  environment.systemPackages = with pkgs; [
    openssl
  ];
  users.mutableUsers = false;
}
```
`configuration.nix`:
```
...
  containers.quassel = {
    autoStart = true;
    config = import ./quassel.nix;
  };
...
```

@edolstra Is there any way I can help debug this further?

**Comment by copumpkin** [comment]
Sounds like there's a missing NixOS VM test as well :smile:

**Comment by ttuegel** [comment]
Actually, I didn't check for a NixOS containers test because it's not on Hydra! Trying that now...

**Comment by ttuegel** [comment]
Well, `nixos.tests.containers` passes, so that's a little strange. I hypothesize this has something to do with `autoStart = true`.

**Comment by ttuegel** [comment]
I have ruled out `autoStart = true` having anything to do with it. It seems that containers simply work fine in a VM, but fail on a physical machine.

**Comment by copumpkin** [comment]
:scream:

**Comment by ttuegel** [comment]
The problem is `privateNetwork = false`; containers with `privateNetwork = true` start. This is a problem for me though, as I want the container to be accessible over the network.

**Comment by ttuegel** [comment]
It gets worse. Containers with `privateNetwork = false` don't start on my physical machine, but they *do* start in the VM.

**Comment by copumpkin** [comment]
lolwtf. And there's nothing in the journal that indicates what's failing?

**Comment by ttuegel** [comment]
Here's the output of `journalctl -xe`:
```
Dec 02 16:21:05 mugen systemd[1]: Starting Container 'quassel'...
Dec 02 16:21:05 mugen container quassel[16088]: Spawning container quassel on /var/lib/containers/quassel.
Dec 02 16:21:05 mugen container quassel[16088]: Press ^] three times within 1s to kill container.
Dec 02 16:21:05 mugen container quassel[16088]: /etc/localtime does not point into /usr/share/zoneinfo/, not updating container timezone.
Dec 02 16:21:05 mugen container quassel[16088]: Failed to create mount point /var/lib/containers/quassel/var/lib/private/host-notify: No such device or address
Dec 02 16:21:05 mugen systemd[1]: container@quassel.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 16:21:05 mugen container quassel[16106]: cat: /run/containers/quassel.pid: No such file or directory
Dec 02 16:21:05 mugen systemd[1]: container@quassel.service: Control process exited, code=exited status=1
Dec 02 16:21:05 mugen systemd[1]: Failed to start Container 'quassel'.
Dec 02 16:21:05 mugen systemd[1]: container@quassel.service: Unit entered failed state.
Dec 02 16:21:05 mugen systemd[1]: container@quassel.service: Failed with result 'exit-code'.
Dec 02 16:21:05 mugen systemd[1]: container@quassel.service: Service hold-off time over, scheduling restart.
Dec 02 16:21:05 mugen systemd[1]: Stopped Container 'quassel'.
```
The only thing that looks like a failure is
```
Failed to create mount point /var/lib/containers/quassel/var/lib/private/host-notify: No such device or address
```
Oh, if I delete that file, it starts!

OK, so why do I have to manually intervene here? Why does that error message bear so little resemblance to the solution? Why did this work before systemd-219?

**Comment by ttuegel** [comment]
I'm going to go ahead and close this. There should be no way for a bind mount to persist in this fashion.

**Comment by aflatter** [comment]
Had the same issue, deleting the file solved the problem.

**Comment by reinhardt** [comment]
Same issue here after switching to unstable on the host system. Deleting host-notify worked for me as well.
