### ISSUE TITLE
Support SSSD

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#11407]
Add a package for the [System Security Services Daemon (SSSD)](https://fedorahosted.org/sssd/). Replace `nslcd` usage with this for the `users.ldap.daemon` NixOS options.

SSSD seems to be the more widely used and accepted option, now, with RHEL recommending it.

**Comment by e-user** [comment]
I'm trying to adopt the effort but not receiving any feedback at #14697, anyone willing to help?

**Comment by e-user** [comment]
This can be closed now, SSSD is merged.
