### ISSUE TITLE
conda-shell fails to start "no such file"

### ISSUE THREAD

**Issue by costrouc** [NixOS/nixpkgs#114183]
**Describe the bug**

Conda fails to start with `conda-shell`

```shell
$ conda-shell
** (process:3875): ERROR **: 22:38:18.322: main: execvp(*argv, argv): No such file or directory
Trace/breakpoint trap (core dumped)

```

**To Reproduce**

I wish that I could give a detailed way to reproduce but I get this error on my laptop and pc with the same nixos configuration. I have a detailed `strace` if this helps with debugging.

```shell
strace conda-shell
````

[strace.txt](https://github.com/NixOS/nixpkgs/files/6032190/strace.txt)

May be related to https://github.com/NixOS/nixpkgs/issues/33106 but I checked and my home directory has no broken symlinks.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/store/sbwy9hbh8cr63rwiw5bsg7d72x3aly9l-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
 - conda
# a list of nixos modules affected by the problem
module: []
```

**Comment by mausch** [comment]
@costrouc  Is this still happening for you? I've been using conda-shell for almost a year now I think and I've had many issues but never seen this one.

**Comment by costrouc** [comment]
@mausch it is a weird error. Suddenly (2 weeks ago) on my pc `conda-shell` now works. But on my laptop which has an identical nixos/home-manager configuration I get this error. I'm convinced this has something to do with chroot and conda possibly.

**Comment by mausch** [comment]
BTW I've given up on Conda on Nix. I got [micromamba merged into nixpkgs](https://github.com/NixOS/nixpkgs/pull/129583), which is much simpler (no `conda-shell` or `conda-install`) and does everything I need...

**Comment by costrouc** [comment]
Thanks for your work here @mausch! I'm a big fan of micromamba for many of the reasons you listed in that PR. I'll also add that is uses much less memory for solves and seems to be more of a community effort. 

> Does not require any special FHS to operate (though environments created by conda/mamba still require FHS to be consumed)

Could you explain how you would then use the environments created from this? Do we have to do similar tricks to `chrootenv`?

**Comment by costrouc** [comment]
Okay I figured out my issue! Turns out that for some reason there was a directory on my laptop `/host` which chrootenv https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/build-support/build-fhs-userenv/chrootenv/chrootenv.c uses. No clue it was created sometime in 2019.

```shell
$ ls -la /host/path/nginx.conf/
total 8
drwxr-xr-x 2 root root 4096 Dec 21  2019 .
drwxr-xr-x 3 root root 4096 Dec 21  2019 ..
```

Definitely not intentional.

**Comment by costrouc** [comment]
Was able to use mamba similar to the conda way (not sure if this is the recommended way).

```shell
nix-shell -p conda micromamba
$ conda-shell
$ micromamba ...
```

I see how you can use micromamba outside of the conda-shell as well. But if you want to activate an environment you'll need to be in `conda-shell`. @mausch correct me if there is a better way.

**Comment by mausch** [comment]
Yep that's what I meant with that comment about requiring a FHS to consume an environment.
But I think you can just use pretty much any FHS really. For example:

```
# Create the environment, which doesn't need FHS e.g.

$ micromamba create -p $PWD/.mamba python=3.7 numpy=1.21.0 -c conda-forge

# Now enter a trivial FHS shell to activate the environment:

$ nix-shell -E 'with import <nixpkgs> {}; (pkgs.buildFHSUserEnv { name = "fhs"; }).env'
$ eval "$(micromamba shell hook -s bash)"
$ micromamba activate $PWD/.mamba
$ python
>>> import numpy as np

```

Or you might want to write a shell.nix to customise the FHS a bit more e.g. set MAMBA_ROOT_PREFIX, PS1, put the micromamba shell hook in there, whatever.

You can of course also use named environments, or install things imperatively within the FHS shell, etc.

In some of the repos I work with I have both anaconda and pypi dependencies and this setup makes it really easy to use what I already have i.e. I install pip through micromamba then activate the environment then run `pip install -r requirements.txt`.
I put this all in a shell.nix then all I have to do is run `nix-shell` to build and enter the environment.

**Comment by mausch** [comment]
Just documented this in https://nixos.wiki/wiki/Python#micromamba
