### ISSUE TITLE
resolved don't use default dns server

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#114118]
**Describe the bug**
I use systemd-resolved in combination with nm.
The DNS server is set by DHCP.

The DNS resolution is broken for my local domains that only my gateway knows about.

```
[davidak@gaming:~]$ host nas.lan
Host nas.lan not found: 3(NXDOMAIN)
```

This command helps for some seconds/minutes, but then it's broken again.

```
[davidak@gaming:~]$ resolvectl flush-caches

[davidak@gaming:~]$ host nas.lan
nas.lan has address 10.0.0.4
Host nas.lan not found: 3(NXDOMAIN)
Host nas.lan not found: 3(NXDOMAIN)
```

The config. seem correct.

```
[davidak@gaming:~]$ resolvectl status
Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported                                                                     
    resolv.conf mode: stub                                                                                                               
Fallback DNS Servers: 1.1.1.1 8.8.8.8 1.0.0.1 8.8.4.4 2606:4700:4700::1111 2001:4860:4860::8888 2606:4700:4700::1001 2001:4860:4860::8844

Link 2 (enp4s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6                                   
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.0.0.1                                                    
       DNS Servers: 10.0.0.1                                                    
        DNS Domain: lan ~.                                                      

Link 3 (virbr0)
Current Scopes: none                                                        
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 4 (docker0)
Current Scopes: none                                                        
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

[davidak@gaming:~]$ cat /etc/resolv.conf 
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search lan

[davidak@gaming:~]$ cat /etc/resolvconf.conf 
echo "resolvconf is disabled on this system but was used anyway:" >&2
echo "$0 $*" >&2
exit 1
```

I guess the Fallback DNS Servers are used for some reason.

I can't remember having this issue ever. Used 20.09 until yesterday.

Related to https://github.com/NixOS/nixpkgs/issues/63754

**To Reproduce**

Here is my config.: https://codeberg.org/davidak/nixos-config/src/commit/4c1217aa2a68ee186b4514ccd6d9ba72981496ff/machines/gaming/configuration.nix

resolved specific: https://codeberg.org/davidak/nixos-config/src/commit/4c1217aa2a68ee186b4514ccd6d9ba72981496ff/services/dns.nix

**Expected behavior**
No DNS issues.

**Notify maintainers**

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05.git.f9d9740e68e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.3246.d4189f68fdb, nixos-hardware, nixos-unstable-21.05pre271444.9816b99e71c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

On branch https://github.com/NixOS/nixpkgs/pull/114000

@worldofpeace do you also use a local DNS server and can verify if you have this isuse?

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
This (https://github.com/NixOS/nixpkgs/issues/63754#issuecomment-570799499) does not fix it:

```
{ # ...
  networking.resolvconf.dnsExtensionMechanism = false;
}
```

**Comment by benley** [comment]
(please ignore the "benley pinned/unpinned this issue", that was an accidental click)

**Comment by davidak** [comment]
I have the issue again with NixOS 21.11.335443.e84444b14cc. I did not have it the last months.

**Comment by davidak** [comment]
I don't have this issue on NixOS 22.05. If you still have this issue, leave a comment and it can be reopened.

If you have this issue again, please open a new issue. It might be unrelated.
