### ISSUE TITLE
Neo layout - 4th layer arrow keys not working in JetBrains IDEs

### ISSUE THREAD

**Issue by akrger** [NixOS/nixpkgs#114299]
**Describe the bug**
The 4th layer arrow keys for the Neo keyboard layout don't work in all JetBrains IDEs (Android Studio works, though).
I tested also on the stable channel before switching to nixos-unstable, and there the arrow keys from the 4th layer worked fine, even without enabling `Use national layouts for shortcuts` from the Settings (Keymap), how it is explained here: https://youtrack.jetbrains.com/issue/IDEA-256569.
Enabling `Use national layouts for shortcuts` on the nixos-unstable builds of the IDEs unfortunately doesn't solve the problem, only applying this patch does: https://github.com/chenkelmann/neo2-awt-hack

**To Reproduce**
1. Choose the Neo 2 layout
2. Install a JetBrains IDE like CLion and open a text file
3. The arrow keys, which can be accessed on the 4th layer, don't work

**Expected behavior**
The arrow keys in the 4th layer should work in all JetBrains IDEs like they did in the nixos-20.09 channel, without having to apply the neo2-awt-hack and without enabling `Use national layouts for shortcuts`.

**Additional context**
Information about the layout (e.g. how to access the 4th layer arrow keys): https://neo-layout.org/

**Notify maintainers**

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05pre271938.c7d0dbe094c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre271938.c7d0dbe094c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by petabyteboy** [comment]
From the upstream issue it looks like this will be fixed in the 2021.1 release of the Jetbrains IDEs. I don't see anything nixpkgs-specific to do here other than packaging the 2021.1 versions once they're released.

**Comment by akrger** [comment]
This is unfortunately still an issue with the IDEs installed from this commit: ac1d24c91176805a561116fbc5be249e96180717

I also don't see a reason why 2021.1 should fix this, because as far as I understood it, besides other updates/fixes in that release, they only enable `Use national layouts for shortcuts` as a default. But even with that option, the arrow keys don't work.

**Comment by akrger** [comment]
Btw: The arrow keys also worked fine when I enabled `Use national layouts for shortcuts` in the IDEs installed from JetBrains Toolbox on Fedora Workstation 33, so I would assume that some patching for either the JetBrains JDK or the IDEs themselves broke during some commit from nixos-20.09 to master.

**Comment by akrger** [comment]
It is working now with 2021 release.
