### ISSUE TITLE
Add nixpkgs-unstable branch to nixpkgs-channels repo

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11427]
We already have all the NixOS ones, but there's nothing representing the last successful Hydra build of nixpkgs for those of us not on Linux.

cc @edolstra who I think runs that process

**Comment by vcunat** [comment]
:+1:

**Comment by pSub** [comment]
:+1:

**Comment by copumpkin** [comment]
Thanks!
