### ISSUE TITLE
VimOutliner hoist plugin doesn't do anyrhing.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#11437]
My config has:
```
let g:vo_modules_load = "checkbox:tags:smart_paste:newhoist"
let maplocalleader = ',,'
```

When I do ``,,h``, nothing happens. 
The other ``,,`` mappings work, also (some of) those related to optional plugins.
For example: ``,,cb``, which uses the checkbox plugin.

**Comment by Profpatsch** [comment]
(triage) is this even nixpkgs related? Do you still need this?

**Comment by magnetophon** [comment]
Yes it's nixpkgs related, but no I don't need it anymore.
[Spacemacs](http://spacemacs.org) FTW!

**Comment by Profpatsch** [comment]
> Spacemacs FTW!

Preach it!
