### ISSUE TITLE
Steam has no .desktop file

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#11433]
Title says it all. :)

@jagajaga

**Comment by jgillich** [comment]
Trying to figure this out, I can't even manage to get it building. Tons of the runtime stuff 404's and `update-runtime.py` just gives me `nix-prefetch-url: unknown flag ‘--name’`. Hmm.

**Comment by jagajaga** [comment]
Do you talk about `steam` or `steam-original`?

**Comment by jgillich** [comment]
`steam`

**Comment by jagajaga** [comment]
I don't know if we can create desktop file for it..
cc @abbradar

**Comment by jgillich** [comment]
There's already one in the tarball from Valve, should be a matter of moving it to the right location. Or not, I don't really know haha.

**Comment by abbradar** [comment]
@jgillich I've fixed that along with a bunch of other things. To update the runtime you need to run the script inside `update-runtime-shell.nix`. It also needs unstable Nix version; I've fixed the shell to bring it into environment. I'll push the fixes after runtime finishes updating.

**Comment by jgillich** [comment]
@abbradar Awesome! I figured that I'd need unstable already, currently running the upgrade. Firefox takes sooooo long to compile.

**Comment by abbradar** [comment]
Ouch, while commiting things I've noticed that I haven't really committed the shell environment earlier!

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/fc6a5f746b6942f91e33b50eb967a382f97599a6.
