### ISSUE TITLE
vim_configurable doesn't have ``view``

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#11442]
I have [this vim](https://github.com/magnetophon/nixosConfig/blob/master/vim.nix) as the only vim on my system.
When I run `view`, I get:

```
The program ‘view’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.qvim
  nix-env -iA nixos.vim
  nix-env -iA nixos.vimHugeX
  nix-env -iA nixos.vimNox
```

**Comment by jagajaga** [comment]
Because there is only one name to call your configurable vim. And it's defined by https://github.com/magnetophon/nixosConfig/blob/master/vim.nix#L7. So there is also no `gvim`, but there is `vim -g`.

**Comment by joachifm** [comment]
Seems like this was answered conclusively

**Comment by magnetophon** [comment]
Answered yes, solved not.
Isn't it usefull to keep a reminder around that this would be nice to have?

**Comment by joachifm** [comment]
Okay

**Comment by dtzWill** [comment]
Similarly `vimdiff` (`vim -d`).

**Comment by timokau** [comment]
Ideally we would just make the vim interface identical to the neovim interace (so `vim.override{}` instead of `vim_configurable.customize` and remove the `name` thing altogether. The old interface can then be left as-is for backwards compatibility.

**Comment by magnetophon** [comment]
I personally switched to Doom Emacs, with occasional vim use.
This was never really important to me, and now even less so.
Since its been a while and nobody seems to care enough to fix it, Ill close this.
