### ISSUE TITLE
linbox: fatal error: CL/cl.h: No such file or directory

### ISSUE THREAD

**Issue by omasanori** [NixOS/nixpkgs#114471]
**Describe the bug**
Building `linbox` with `withSage = true` fails with the following error:

```
In file included from ../../linbox/matrix/matrix-domain.h:73,
                 from ../../linbox/matrix/transpose-matrix.h:47,
                 from ../../linbox/matrix/matrixdomain/matrix-domain.inl:33,
                 from ../../linbox/matrix/matrixdomain/matrix-domain.h:1233,
                 from ../../linbox/matrix/densematrix/blas-matrix.h:55,
                 from ../../linbox/matrix/dense-matrix.h:79,
                 from ../../linbox/solutions/methods.h:26,
                 from ../../linbox/algorithms/rational-solver.h:41,
                 from ../../linbox/algorithms/diophantine-solver.h:29,
                 from diophantine-solver.C:26:
../../linbox/matrix/matrixdomain/opencl-domain.h:43:10: fatal error: CL/cl.h: No such file or directory
   43 | #include <CL/cl.h>
      |          ^~~~~~~~~
compilation terminated.
```

**To Reproduce**
1. `nix-build -E 'with (import ./. {}); pkgs.linbox.override { withSage = true; }'`

**Expected behavior**
It succeeds to build.

**Notify maintainers**

@timokau, @7c6f434c and @omasanori

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-1160.11.1.el7.x86_64, CentOS Linux, 7 (Core)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ogino): `"nixpkgs-21.05pre272691.04ac9dcd311"`
 - nixpkgs: `/home/ogino/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - linbox
  - sage
# a list of nixos modules affected by the problem
module:
```

**Comment by omasanori** [comment]
I found that it occurs if sandbox is disabled and `/opt/AMDAPP/CL/cl.h`, `/usr/include/CL/cl.h` or `/usr/local/include/CL/cl.h` exists.

**Comment by timokau** [comment]
Linbox checks for opencl support in the configuration phase and uses it if available. It detects opencl support on your machine without sandboxing if the header is present and tries to use it. I'm not sure why it fails to use it. Either way we should either support or [disable](https://github.com/linbox-team/linbox/blob/c48e8651f31c0c1d0dd49f8d31d06cbfe0f842d8/macros/ocl-check.m4#L30) opencl to avoid issues with unsandboxed builds.

**Comment by omasanori** [comment]
Thank you for explanation, @timokau! I guess there may be some mismatches between the system (CentOS 7)'s toolchain and/or ABIs and nixpkgs' one. As OpenCL related packages seems not in the inputs of `linbox` now, disabling it would be fine until someone really wants to use it.

**Comment by FliegendeWurst** [comment]
Works for me on NixOS 21.11
