### ISSUE TITLE
request newer v8 versions/advice

### ISSUE THREAD

**Issue by 06kellyjac** [NixOS/nixpkgs#114450]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: v8

current version: 7.4.255
desired version: ideally the latest 9.0.259, 8.2.126 is the oldest release I've found that has the new `v8-fast-api-calls.h` header file, there might be other header files I need

---

My problem: I am trying to bump the version of deno but it currently depends on prebuilt copies of `librusty_v8.a`
This was working ok but recently they have stopped vendoring aarch64 linux versions because sccache is having issues so build times are long in their CI.

https://github.com/NixOS/nixpkgs/pull/110156

I'm in the process of trying to get rusty_v8 to work without fetching their pre-built `librusty_v8.a`
There are two options really

**Building off of a prebuilt `libv8.a`:**

`librusty_v8.a` Is just `libv8.a` built with some gn options and includes an extra `src/binding.cc`
I might be able to use `libv8.a` and link `bindings.o` or manage to merge the two.
This is quite a bit of faffing about and it's going to be a bit different to `librusty_v8.a` that all other deno releases will be using.
The benefit is the build should be really fast as it'll just be compiling the binding and linking.

**Building from source (also requires build v8 from source completely separate to any effort we have elsewhere in nixpkgs):**

I could try and build the same kind of `librusty_v8.a` with the same gn options etc from scratch but the worry is v8 takes a long time to build. I'm not sure who would get to make the final decision but also I haven't tried this yet on my machine so I don't have a full grasp of how easy/hard this will be.

---

Also why is `v8_6_x = v8;` and `v8` is `7.4.255`?? Shouldn't it be `v8_7_x = v8;`?

I guess it's not a big deal because I don't seem to see it in nixos.org search..

###### Notify maintainers

maintainers: @cstrahan @proglodyte @matthewbauer

###### Note for maintainers

Please tag this issue in your PR.

**Comment by JamieMagee** [comment]
v8 was updated to `9.7.106.18` in #154007
