### ISSUE TITLE
linux-firmware: Unrecognized git object type: tag

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#114439]
Building linux-firmware currently fails locally with:

```
nitialized empty Git repository in /nix/store/m1rj36cajnh0nmrjlcj0m44ccj01ynxz-linux-firmware-2021020/.git/
remote: Enumerating objects: 383, done.
remote: Counting objects: 100% (383/383), done.
remote: Compressing objects: 100% (374/374), done.
remote: Total 10822 (delta 202), reused 1 (delta 1), pack-reused 10439
Receiving objects: 100% (10822/10822), 367.12 MiB | 6.23 MiB/s, done.
Resolving deltas: 100% (7037/7037), done.
From https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware
 * [new branch]      main       -> origin/main
 * [new branch]      master     -> origin/master
 * [new tag]         20190312   -> 20190312
 * [new tag]         20190416   -> 20190416
 * [new tag]         20190514   -> 20190514
 * [new tag]         20190618   -> 20190618
 * [new tag]         20190717   -> 20190717
 * [new tag]         20190815   -> 20190815
 * [new tag]         20190923   -> 20190923
 * [new tag]         20191022   -> 20191022
 * [new tag]         20191215   -> 20191215
 * [new tag]         20200122   -> 20200122
 * [new tag]         20200316   -> 20200316
 * [new tag]         20200421   -> 20200421
 * [new tag]         20200519   -> 20200519
 * [new tag]         20200619   -> 20200619
 * [new tag]         20200721   -> 20200721
 * [new tag]         20200817   -> 20200817
 * [new tag]         20200918   -> 20200918
 * [new tag]         20201022   -> 20201022
 * [new tag]         20201118   -> 20201118
 * [new tag]         20201218   -> 20201218
 * [new tag]         20210208   -> 20210208
Unrecognized git object type: tag
Unable to checkout 20210208 from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git.
builder for '/nix/store/d3lj3ip1ypxl3iaww874s6xj80xgbb78-linux-firmware-2021020.drv' failed with exit code 1
```

To reproduce:

```
ISO_DRV=$(nix-instantiate nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux)
FIRMWARE_DRV=$(nix-store -q -R $ISO_DRV | grep linux-firmware)
nix-build $FIRMWARE_DRV --option substitute false
```

**Comment by baloo** [comment]
```
error: object b5637a2a32eefcfbb39f072abbb2e7eab96385ac: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed
```

The remote git repository is corrupted and would need a `git fsck`

**Comment by raboof** [comment]
> ```
> error: object b5637a2a32eefcfbb39f072abbb2e7eab96385ac: zeroPaddedFilemode: contains zero-padded file modes
> fatal: fsck error in packed object
> fatal: index-pack failed
> ```

How do you get that? When I check out that repo and run `git fsck` I do see `zeroPaddedFilemode: contains zero-padded file modes` warnings but no `fatal: fsck error in packed object`

> The remote git repository is corrupted and would need a `git fsck`

If I clone the repo, `git fsck` doesn't see problems. When I push it somewhere else and point ./pkgs/os-specific/linux/firmware/firmware-linux-nonfree/default.nix to that, it shows the same problem with that repo.

**Comment by logan12358** [comment]
It seems like this happens because the tag looks like a hash (i.e. contains only hexadecimal characters). Before #104714 this worked because `nix-prefetch-git`'s `checkout_hash` function worked (surprisingly) when a tag was passed as the `hash` argument. It might be better to specify `rev = "refs/tags/${lib.replaceStrings ["-"] [""] version)";` than to use the commit hash.

**Comment by raboof** [comment]
> It seems like this happens because the tag looks like a hash (i.e. contains only hexadecimal characters). Before #104714 this worked because `nix-prefetch-git`'s `checkout_hash` function worked (surprisingly) when a tag was passed as the `hash` argument. It might be better to specify `rev = "refs/tags/${lib.replaceStrings ["-"] [""] version)";` than to use the commit hash.

Ah, thanks! submitted #116306

**Comment by primeos** [comment]
I've opened #116307 for the `nix-prefetch-git` issue/regression (might affect other packages as well).
Thanks @logan12358 for noticing this!
