### ISSUE TITLE
Yakuake was unable to load the Konsole component. A Konsole installation is required to use Yakuake.

### ISSUE THREAD

**Issue by ihipop** [NixOS/nixpkgs#114433]
**Describe the bug**
Konsole install via nix-env ,but Yakuake still say: 
`Yakuake was unable to load the Konsole component. A Konsole installation is required to use Yakuake.`

**To Reproduce**
1. `nix-env --install yakuake`
2. `~/.nix-profile/bin/yakuake` 
3. PRESS `yakuake`  hotkey

**Expected behavior**
`yakuake` run normally

**Screenshots**
![截图录屏_yakuake_20210226125705](https://user-images.githubusercontent.com/423077/109257900-1fad0f80-7834-11eb-9f67-daa816442ec4.png)

**Additional context**

**Notify maintainers**
@FRidh 

**Metadata**
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.70-amd64-desktop, Deepin, 20.1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(ihipop): `"nixpkgs"`
 - nixpkgs: `/home/ihipop/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# https://github.com/NixOS/nixpkgs/blob/92cc194/pkgs/applications/kde/yakuake.nix
```

**Comment by FliegendeWurst** [comment]
Works for me on NixOS 21.11

**Comment by herberteuler** [comment]
@ihipop I had the same issue after switching to 22.11. After manually quitting Yakuake by right-clicking the Yakuake icon on the taskbar and selecting Quit and then restarting Yakuake, the problem was resolved.

**Comment by DaraMac** [comment]
I also have this issue and have been unable to resolve it

**Comment by DaraMac** [comment]
> @ihipop I had the same issue after switching to 22.11. After manually quitting Yakuake by right-clicking the Yakuake icon on the taskbar and selecting Quit and then restarting Yakuake, the problem was resolved.

Never mind I did manage to solve it with this, thanks!
