### ISSUE TITLE
No such schema “org.gnome.mutter”

### ISSUE THREAD

**Issue by tad-lispy** [NixOS/nixpkgs#114514]
**Describe the bug**

Following [the Arch Wiki on HiDPI](https://wiki.archlinux.org/index.php/HiDPI#Wayland) I'm trying to enable fractional scaling in Gnome 3.36.5 (installed via nixos-20.09 channel).

**To Reproduce**
1. Install Gnome DE with Wayland

   ```nix
   {
     services.xserver.enable = true;
     services.xserver.desktopManager.gnome3.enable = true;
     services.xserver.displayManager.gdm.wayland = true;
     services.xserver.displayManager.gdm.enable = true;
   }
   ```
2. Try enabling the fractional scaling

   ```
   $ gsettings set org.gnome.mutter experimental-features '["scale-monitor-framebuffer"]'
   No such schema “org.gnome.mutter”
   ```

**Expected behavior**

Fractional scaling option visible in Gnome Settings

**Screenshots**

Firefox window correctly scaled on primary display (200%)
![image](https://user-images.githubusercontent.com/1684495/109359997-b86c7b00-7886-11eb-925a-4b656f8b181b.png)

Same window on secondary display (should be 100%, but all elements are too big)
![image](https://user-images.githubusercontent.com/1684495/109360065-d9cd6700-7886-11eb-9798-0906a13af3fa.png)

The fractional scaling toggle should be visible here:
![image](https://user-images.githubusercontent.com/1684495/109359888-8529ec00-7886-11eb-9ed8-cb3871f2e5e5.png)

**Additional context**

The same issue is reported in the Mutter repo on GNOME GitLab: https://gitlab.gnome.org/GNOME/mutter/-/issues/1569

Reporter claims that the scaling was correct in GNOME version 3.36, but I can't confirm it.

**Notify maintainers**

@hedning
@jtojnar
@worldofpeace
@dasj19

**Metadata**

```
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18, NixOS, 20.09.3301.42809feaa9f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3301.42809feaa9f"`
 - channels(tad): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
NixOS avoids installing data of libraries globally. That includes GSettings schemas.

You can get the schemas into scope manually using `env GSETTINGS_SCHEMA_DIR=$(nix-instantiate -I nixpkgs=$HOME/Projects/nixpkgs --eval --json -E 'with import <nixpkgs> { }; glib.passthru.getSchemaPath gnome3.mutter' | jq --raw-output) gsettings set org.gnome.mutter experimental-features '["scale-monitor-framebuffer"]'`.

Or you could try to write into the dconf database directly (without validation against schema): `dconf write /org/gnome/mutter/experimental-features "['scale-monitor-framebuffer']"`

See also https://github.com/NixOS/nixpkgs/issues/33277#issuecomment-354689755.

**Comment by tad-lispy** [comment]
Thank you. I wrote without validation and it solves the problem. After restart all windows are scaled correctly.

Feel free to close the issue.

**Comment by wmertens** [comment]
Aha, that's why. I think this is a bug on our side, no?

Shouldn't mutter be made part of the global schema?

**Comment by worldofpeace** [comment]
![Screenshot from 2021-02-27 04-46-52](https://user-images.githubusercontent.com/28888242/109383791-dd78e200-78b6-11eb-98b0-fe126885cf08.png)

I was able to get this working. I had to use the home-manager dconf module (because of that I had to logout, but that's just a detail of how that module works IIRC). The issue here is that, ideally we'd have these as another option in the gnome3 module, and have a much better dconf module in nixpkgs. Honestly wondering what we think of the code in home-manager.

Anyways, I'm closing this. An issue we could work on is document how to properly use `gsettings` https://github.com/NixOS/nixpkgs/pull/86288 

Ref https://github.com/NixOS/nixpkgs/issues/54150

**Comment by louwers** [comment]
Tried this but no luck...

```
  services.xserver.desktopManager.gnome = {
   enable = true;
   extraGSettingsOverrides = ''
     [org.gnome.mutter]
     experimental-features=['scale-monitor-framebuffer']
   '';
  };
```

**Comment by jtojnar** [comment]
You also need `extraGSettingsOverridePackages = [ pkgs.gnome.muttter ];`

**Comment by hacker1024** [comment]
This can also be done quite easily through home-manager:

```nix
{
  dconf.settings = {
    "org/gnome/mutter" = {
      experimental-features = [ "scale-monitor-framebuffer" ];
    };
  };
}
```

**Comment by shd101wyy** [comment]
The fonts become super blurry after I use the fractional scaling. Is there any suggestions on how to improve it? Thanks

**Comment by jtojnar** [comment]
Do you have `GTK_USE_PORTAL` environment variable set by chance? If yes, try disabling it. Either way you are better of opening a new issue.

**Comment by desmond-git** [comment]
> NixOS avoids installing data of libraries globally. That includes GSettings schemas.
> 
> You can get the schemas into scope manually using `env GSETTINGS_SCHEMA_DIR=$(nix-instantiate -I nixpkgs=$HOME/Projects/nixpkgs --eval --json -E 'with import <nixpkgs> { }; glib.passthru.getSchemaPath gnome3.mutter' | jq --raw-output) gsettings set org.gnome.mutter experimental-features '["scale-monitor-framebuffer"]'`.
> 
> Or you could try to write into the dconf database directly (without validation against schema): `dconf write /org/gnome/mutter/experimental-features "['scale-monitor-framebuffer']"`
> 
> See also [#33277 (comment)](https://github.com/NixOS/nixpkgs/issues/33277#issuecomment-354689755).

Using dconf write works well.
But what is the way to make an application schema show up in gsettings so it can be changed from there.?
I needed to change a Nautilus setting which is not listed in dconf or gsettings so I had to use dconf write because I didn't manage to make the schema being loaded.

I tried to add "/nix/store/3529xda7wikbf1886c40wvxnm5rlgzm4-nautilus-43.0/share/gsettings-schemas/nautilus-43.0" to env XDG_DATA_DIRS and i see it listed with "echo $XDG_DATA_DIRS" but it doesn't appear in gconf or gsettings.

Thanks!

**Comment by tobiasvandriessel** [comment]
@martin-braun Possibly that's because of the applications not being Wayland applications (if you're running Wayland), if I'm not mistaken.

**Comment by avinashkanaujiya** [comment]
I added this to my config.
```
services.xserver.desktopManager.gnome = {
    # enable = true;
    extraGSettingsOverridePackages = [ pkgs.gnome.mutter ];
    extraGSettingsOverrides = ''
      [org.gnome.mutter]
      experimental-features=['scale-monitor-framebuffer', 'x11-randr-fractional-scaling']
    '';
  };
```

But I am getting below error, what should I do?
```
stderr: building Nix...

stderr: building the system configuration...

stderr: these 6 derivations will be built:

stderr:   /nix/store/s9nl9y7zsshdyjqqad680d408xh3g2pz-gnome-gsettings-overrides.drv
  /nix/store/v3j0jjllixmjjdypv2yviw7wrkf9w8mm-set-environment.drv
  /nix/store/h5k91z90a8y4109r8jciwyqsxnsrvizl-etc-profile.drv
  /nix/store/r0a5i2dwkn1lvsvmbls0x3rwf7ww96xj-etc-pam-environment.drv
  /nix/store/37xzbzgh6mskn61dal9w161vlih20n1z-etc.drv
  /nix/store/sp9rb8pjvy2dgr3g53dz2y6k5ca5l2k8-nixos-system-nixos-24.05beta357.19cbff58383a.drv

stderr: building '/nix/store/s9nl9y7zsshdyjqqad680d408xh3g2pz-gnome-gsettings-overrides.drv'...

stderr: Warning: Schema ?org.gnome.system.locale? has path ?/system/locale/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy? has path ?/system/proxy/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.http? has path ?/system/proxy/http/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.https? has path ?/system/proxy/https/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.ftp? has path ?/system/proxy/ftp/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Warning: Schema ?org.gnome.system.proxy.socks? has path ?/system/proxy/socks/?.  Paths starting with ?/apps/?, ?/desktop/? or ?/system/? are deprecated.
Override for key “experimental-features” in schema “org.gnome.mutter” in override file “/nix/store/4ryx9gljzzj0ms6rxc4ybsfq4rhxzh7d-gnome-gsettings-overrides/share/gsettings-schemas/nixos-gsettings-overrides/glib-2.0/schemas/zz-nixos-defaults.gschema.override” is not in the list of valid choices and --strict was specified; exiting.

stderr: error: builder for '/nix/store/s9nl9y7zsshdyjqqad680d408xh3g2pz-gnome-gsettings-overrides.drv' failed with exit code 1

stderr: error: 1 dependencies of derivation '/nix/store/r0a5i2dwkn1lvsvmbls0x3rwf7ww96xj-etc-pam-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v3j0jjllixmjjdypv2yviw7wrkf9w8mm-set-environment.drv' failed to build

stderr: error: 1 dependencies of derivation '/nix/store/37xzbzgh6mskn61dal9w161vlih20n1z-etc.drv' failed to build

stderr: error: 1 dependencies of derivation '/nix/store/sp9rb8pjvy2dgr3g53dz2y6k5ca5l2k8-nixos-system-nixos-24.05beta357.19cbff58383a.drv' failed to build

child process exited with code 100

```

**Comment by jtojnar** [comment]
`x11-randr-fractional-scaling` is not a thing:

https://gitlab.gnome.org/GNOME/mutter/-/blob/45.1/data/org.gnome.mutter.gschema.xml.in#L117-135

Apparently, Ubuntu patches Mutter to add this feature:

https://salsa.debian.org/gnome-team/mutter/-/blob/f0a4b16dd0a5d66d7b27fdf3de5bc61dbea5954e/debian/patches/ubuntu/x11-Add-support-for-fractional-scaling-using-Randr.patch
