### ISSUE TITLE
Tlauncher

### ISSUE THREAD

**Issue by dragon-so** [NixOS/nixpkgs#114571]
**Project description**
_describe the project a little_

**Metadata**

* homepage URL:Tlauncher.org
* source URL:??????
* license: mit, bsd, gpl2+ , ...
* platforms: window, linux, mac , ...

**Comment by Mindavi** [comment]
Please put more effort in a packaging request.

**Comment by lucasew** [comment]
Just for SEO purposes cause this is the only place that mentions Nix and TLauncher together

I have something working

Might upstream later

You are free to steal and add to your overlay

https://github.com/lucasew/nixcfg/blob/master/packages/tlauncher.nix
