### ISSUE TITLE
Cross-compilation support for systemd broken

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#114687]
**Describe the bug**

Somehow cross-compilation support for systemd is broken by this change: https://github.com/NixOS/nixpkgs/pull/112276 (specifically the top-level change: e89933197249). When I revert that change, systemd cross-compiles successfully again. However, I assume that just reverting it is not really the correct solution.

Any idea how this can be fixed?

E.g. this fails: `nix build https://github.com/NixOS/nixpkgs/archive/ddf21160e30fbd75c344a8939cc6d518f88409a1.tar.gz#pkgsCross.aarch64-multiplatform.systemdMinimal` (current latest commit on master)

**To Reproduce**
1. `nix build https://github.com/NixOS/nixpkgs/archive/ddf21160e30fbd75c344a8939cc6d518f88409a1.tar.gz#pkgsCross.aarch64-multiplatform.systemdMinimal`

**Expected behavior**

Cross-compiling systemd works, as it seems to do with that change reverted.

**Additional context**

<details><summary>Build error log</summary>

```
rick@nixos-asus:~/hobby/mobile-nixos$ nix build https://github.com/NixOS/nixpkgs/archive/master.tar.gz#pkgsCross.aarch64-multiplatform.systemdMinimal
error: --- Error ----------------------------------------------------------------------------------------------- nix
builder for '/nix/store/971im6rrzr40h9z0zk2wp6cfaw4lbgrv-systemd-minimal-247.3-aarch64-unknown-linux-gnu.drv' failed with exit code 2; last 10 log lines:
      pc, self.stdout, self.stderr = self.run_command(cmd, args, env, source_dir, build_dir, subdir, mesonintrospect, in_builddir, check)
    File "/nix/store/0wjnbyh3dpgx43kzvh6wcsdx9fg92rwd-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 200, in run_command
      p, o, e = Popen_safe(command_array, stdout=stdout, env=child_env, cwd=cwd)
    File "/nix/store/0wjnbyh3dpgx43kzvh6wcsdx9fg92rwd-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/mesonlib.py", line 1217, in Popen_safe
      p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
    File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/subprocess.py", line 1706, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 8] Exec format error: '/build/source/tools/xml_helper.py'
rick@nixos-asus:~/hobby/mobile-nixos$ nix build https://github.com/NixOS/nixpkgs/archive/master.tar.gz#pkgsCross.aarch64-multiplatform.systemdMinimal
error: --- Error ----------------------------------------------------------------------------------------------- nix
builder for '/nix/store/971im6rrzr40h9z0zk2wp6cfaw4lbgrv-systemd-minimal-247.3-aarch64-unknown-linux-gnu.drv' failed with exit code 2; last 10 log lines:
      pc, self.stdout, self.stderr = self.run_command(cmd, args, env, source_dir, build_dir, subdir, mesonintrospect, in_builddir, check)
    File "/nix/store/0wjnbyh3dpgx43kzvh6wcsdx9fg92rwd-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 200, in run_command
      p, o, e = Popen_safe(command_array, stdout=stdout, env=child_env, cwd=cwd)
    File "/nix/store/0wjnbyh3dpgx43kzvh6wcsdx9fg92rwd-meson-0.56.0/lib/python3.8/site-packages/mesonbuild/mesonlib.py", line 1217, in Popen_safe
      p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
    File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/lib/python3.8/subprocess.py", line 1706, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 8] Exec format error: '/build/source/tools/xml_helper.py'
```

</details>

I've looked into what fails to execute -- it's trying to execute a cross-compiled python (build for aarch64). I find this weird, as it's only listed in the nativeBuildPackages. `patchShebangs` is called on the tools dir, but apparently that doesn't inject the wrapped python version properly.

I find it hard to figure out where it goes wrong, but I think this has something to do with patchShebangs and how it replaces the shebang. It should replace the python with the wrapped version, but I'm not sure how that would be done and if there's any script we normally use for that (other than substituteInPlace).

**Notify maintainers**

- systemd: @andir @flokli @Kloenk
- the top-level shell change: @siraben 

**Metadata**

rick@nixos-asus:~$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.17-hardened1, NixOS, 21.05pre272380.f6b5bfdb470 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(rick): `""`
 - channels(root): `"nixos-21.05pre272380.f6b5bfdb470, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: systemdMinimal
# a list of nixos modules affected by the problem
module:
```

**Comment by siraben** [comment]
@Ericson2314 why would changing the shell for makeWrapper break cross-compilation like this?

**Comment by samueldr** [comment]
Without actively looking, I'll give a guesstimate of what I think happens.

```
  OSError: [Errno 8] Exec format error: '/build/source/tools/xml_helper.py'
```

This is likely because the build tries to execute *something* for the wrong platform. It might be that the shell wrapper for *something* was made with the wrong makeWrapper. E.g. the makeWrapper for the target, and not the host. It might be that *something* needs both makeWrappers to exist.

This might be *further* muddied by the fact that libc `exec` will *fall back to /bin/sh if the interpreter is not executable*.

> If the header of a file isn't recognized (the attempted execve(2) failed with the error ENOEXEC), these functions will execute the shell (/bin/sh) with the path of the file as its first argument. (If this attempt fails, no further searching is done.)

— https://man7.org/linux/man-pages/man3/exec.3.html

It was known that things in cross-compiled NixOS systems used the wrong `runtimeShell` on the target. But it wasn't an issue, in the end, by sheer coincidence and luck that libc has this dangerous fallback behaviour.

* * *

That treewide change probably shouldn't have been merged without a much much much in-depth test. It is showing that things might have been working by luck, but they were working. Furthermore, the way the treewide change was authored (one giga-commit) makes it extremely hard to bisect *which* changes are causing issues :/. This wasn't a trivial treewide change I think. Even though it may have looked like one on the surface.

**Comment by r-burns** [comment]
It looks like this issue has been encountered before:

https://github.com/NixOS/nixpkgs/blob/5f7a2783db5d7082d1cbab492c60fbff48e2b5cb/pkgs/applications/misc/elogind/default.nix#L52

**Comment by Mindavi** [comment]
elogind requires some patching to get to work, and seems to fail on the same issue, so don't think that is of much use.

I've looked into this some more, and this (the wrapped python) seems to be the culprit:

```
#! /nix/store/lgz912kkvxlxci75y0il50a768nxi8nw-bash-4.4-p23-aarch64-unknown-linux-gnu/bin/bash -e
export NIX_PYTHONPREFIX='/nix/store/l7apqildsw74vncghsi027ingm8xy9xz-python3-3.8.8-env'
export NIX_PYTHONEXECUTABLE='/nix/store/l7apqildsw74vncghsi027ingm8xy9xz-python3-3.8.8-env/bin/python3.8'
export NIX_PYTHONPATH='/nix/store/l7apqildsw74vncghsi027ingm8xy9xz-python3-3.8.8-env/lib/python3.8/site-packages'
export PYTHONNOUSERSITE='true'
exec "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3"  "$@"
```

```
#! /nix/store/f7jzmxq9bpbxsg69cszx56mw14n115n5-bash-4.4-p23/bin/bash -e
export NIX_PYTHONPREFIX='/nix/store/7c2ww79kzjip95n763wd0995v8lwdcaz-python3-3.8.8-env'
export NIX_PYTHONEXECUTABLE='/nix/store/7c2ww79kzjip95n763wd0995v8lwdcaz-python3-3.8.8-env/bin/python3.8'
export NIX_PYTHONPATH='/nix/store/7c2ww79kzjip95n763wd0995v8lwdcaz-python3-3.8.8-env/lib/python3.8/site-packages'
export PYTHONNOUSERSITE='true'
exec "/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3"  "$@"
```

Somehow the target shell is injected in the wrapped python, even though python3.withPackages is listed in nativeBuildInputs.

Also running into an unrelated issue, but it is annoying that `nix develop` doesn't work for this package.

It doesn't seem like giving patchShebangs a hint with `--build` helps in this case.

Or am I misunderstanding something here?

**Comment by Ericson2314** [comment]
Ah yes, I just saw something like this. The wrapped python isn't get spliced for some reason. I guess we can use `buildPackages.python.pkgs.wrapPython` until we figure it out?

**Comment by Mindavi** [comment]
I think that's already happening...

https://github.com/NixOS/nixpkgs/blob/80308388cd77ee58823c9b6f24b46892cd359145/pkgs/os-specific/linux/systemd/default.nix#L276

**Comment by Ericson2314** [comment]
@Mindavi I thought it was a wrapped python from a dependency, but I suppose I am not sure.

**Comment by Ericson2314** [comment]
Got a fix, will open in a second.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/114902 here it is

**Comment by Mindavi** [comment]
I've started a build, will update whenever I get some results. Great to see a fix coming in! Now I can move on (I hope) with fixing other breakages that are in the way of cross-compiling my favorite packages.

**Comment by siraben** [comment]
@Mindavi just curious, do you have a darwin machine to test cross-compilation of perl?

**Comment by Mindavi** [comment]
@siraben I don't, just have x86_64 machines and a PinePhone (aarch64). Not planning to compile anything on the pinephone anytime soon :p.

**Comment by Mindavi** [comment]
Build is finished and everything has at least built now. Closing.
