### ISSUE TITLE
mesa: some drivers have problems with llvm-3.7

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#11467]
At eeb2935 on a virtualbox:

```
Dec 04 17:40:13 nixos gdm-Xorg-:0[544]: LLVM ERROR: inconsistency in registered CommandLine options
Dec 04 17:40:13 nixos gdm-Xorg-:0[544]: : CommandLine Error: Option 'no-x86-call-frame-opt' registered more than once!
```

It might be a problem triggered by llvm 3.6.2 -> 3.7.0. Notice that:

```
# nix-store -qR /run/opengl-driver|grep mesa
/nix/store/3s22ks02pqd2s1kgi9lbyjnc8arrjndc-mesa-noglu-11.0.5
/nix/store/8ajx9qy0wmjxkr8034k4apdr0mi5r9xh-mesa-noglu-11.0.5-drivers
/nix/store/h3ywnkhxdrbgqzdl7bp5sj8i9aa2m232-mesa-noglu-11.0.5
/nix/store/1zpr85cc413j0fvym842cxx5x3pflhjs-mesa-drivers+txc-11.0.5
```

Shows `mesa-noglu` twice, which might be registering some kind of plugins with llvm, which now triggers this new error.

Could it be? If anybody knows please tell before I dive fixing this duplicated reference to mesa.

**Comment by domenkozar** [comment]
@lethalman 

```
$ nix-build -A mesa_noglu
/nix/store/h3ywnkhxdrbgqzdl7bp5sj8i9aa2m232-mesa-noglu-11.0.5

$ nix-build -A mesa_drivers
/nix/store/8ajx9qy0wmjxkr8034k4apdr0mi5r9xh-mesa-noglu-11.0.5-drivers

$ nix-store -qR /nix/store/8ajx9qy0wmjxkr8034k4apdr0mi5r9xh-mesa-noglu-11.0.5-drivers|grep mesa
/nix/store/3s22ks02pqd2s1kgi9lbyjnc8arrjndc-mesa-noglu-11.0.5
```
I wouldn't say that's the issue though

**Comment by domenkozar** [comment]
Note that I can not reproduce this with `i3wm` + `xfce` and intel drivers

**Comment by vcunat** [comment]
Related, though perhaps a different cause: #11367.

**Comment by lethalman** [comment]
Anybody else can try nixos in virtualbox?

**Comment by lethalman** [comment]
Using llvm 36 as in #11367 works for me. Pretty sure it's something to do with the two mesa versions.

**Comment by NeQuissimus** [comment]
I am running in VirtualBox 5.0.10

The duplicate mesa-noglu is nothing new:

```
~> nix-store -qR /run/opengl-driver | grep mesa
/nix/store/8sxa34shq6zkdh8i6869mn3ksrx7qbbc-mesa-noglu-10.6.9
/nix/store/jcigz9kr14vnqyjwsj8q3rfr4ac9ijbg-mesa-noglu-10.6.9
/nix/store/kv1b19hx18g8kwqb62v15hnrnnqw3369-mesa-noglu-10.6.9-drivers
/nix/store/rz15qah68x7iw26vpl2ncl735j5s08kl-mesa-drivers+txc-10.6.9
~> nix-store -qR /run/opengl-driver | grep llvm
/nix/store/qyi57rvy210bkrkj7wfg4hqw9gs8aivr-llvm-3.6.2
```

Updated to master and X starts just fine:
```
~> nix-store -qR /run/opengl-driver | grep mesa
/nix/store/6j2j155gwn00n8dh22dpb20xzwzfddws-mesa-noglu-11.0.5
/nix/store/z9araisk7yp5h1gr8m353v3v77vsa440-mesa-noglu-11.0.5
/nix/store/dk2s1yzbixfjhp7qqb9rkqv2mhs92zbg-mesa-noglu-11.0.5-drivers
/nix/store/nc1xkbdllm6ldmgqv7szzc5srgkzdzz4-mesa-drivers+txc-11.0.5
 ~> nix-store -qR /run/opengl-driver | grep llvm
/nix/store/1g96l7b6x9jahkpshj9lbz51xc7dw7vh-llvm-3.7.0
```

Config: https://gist.github.com/NeQuissimus/dcfb0a062dfb17671e4d

Could it be in gdm?

**Comment by lethalman** [comment]
Thanks for testing, at this point I wonder if it's gdm pulling some duplicate stuff, or perhaps it's the virtualbox guest additions with its drivers or such...

**Comment by NeQuissimus** [comment]
`nix-store -q --referrers` should give me what is using a particular path, correct?

If I follow my first noglu, it looks something like this:

```
~> nix-store -q --referrers /nix/store/8sxa34shq6zkdh8i6869mn3ksrx7qbbc-mesa-noglu-10.6.9
/nix/store/kv1b19hx18g8kwqb62v15hnrnnqw3369-mesa-noglu-10.6.9-drivers
~> nix-store -q --referrers /nix/store/kv1b19hx18g8kwqb62v15hnrnnqw3369-mesa-noglu-10.6.9-drivers
/nix/store/rz15qah68x7iw26vpl2ncl735j5s08kl-mesa-drivers+txc-10.6.9
~> nix-store -q --referrers /nix/store/rz15qah68x7iw26vpl2ncl735j5s08kl-mesa-drivers+txc-10.6.9
/nix/store/02jnd4xlawqxsslcv906gnb16yk5hk9s-nixos-15.09.753.18f1e6a
/nix/store/1r0g5ln2dbrviddh62gd86v0947c3vsq-nixos-15.09.760.ba0d05c
/nix/store/6zqyrrxfhy9h26rs2svl6127ici52wpa-nixos-15.09.760.ba0d05c
/nix/store/hnpzy54syzbspxgsywrrh80wyslj4k45-nixos-15.09.760.ba0d05c
/nix/store/hw8slvvsw3710x73b8840ssshmjzc642-nixos-15.09.760.ba0d05c
```

The other one looks like this:

```
~> nix-store -q --referrers /nix/store/jcigz9kr14vnqyjwsj8q3rfr4ac9ijbg-mesa-noglu-10.6.9
/nix/store/jcigz9kr14vnqyjwsj8q3rfr4ac9ijbg-mesa-noglu-10.6.9
/nix/store/s72qjbjpzf7lnjrfj8pcsly3srs1zvgx-cairo-1.14.2
/nix/store/mlmvn82lxbdnwi0izic6vix5n606gw6w-pango-1.36.8
/nix/store/0bawfajvmg9sys1x0wycxbhyqh8wlilq-gtk+-2.24.28
/nix/store/2v17m8j6vrmyd8665wqnk5gqrcgm2pnh-cairomm-1.11.2
/nix/store/3zbs04a23vxyxwg5k9bidr6rl0rbgxb1-xorg-server-1.17.2
/nix/store/pgzzd0dngibdzh8fba92c8a6dy8dh8cl-glu-9.0.0
/nix/store/6644803i3q2bi50hnb9vpq2bad48j4z2-qtbase-5.4.2
/nix/store/c492y93z1xyfspfw98a8233aciwv7k1d-qtsvg-5.4.2
/nix/store/a8v64ljpxjp52l3qdl3gf0s9m8qs07g8-qtdeclarative-5.4.2
/nix/store/gc4x40ar7kkrw9824fa8m41b13fa3lxs-gst-plugins-base-0.10.36
/nix/store/qik60ymyw7wm6c24wbyxibhjwp7yb3lk-qtmultimedia-5.4.2
/nix/store/8kkh7l5dh8jcc1fn7fpdn51vbx4i7kwz-qtlocation-5.4.2
/nix/store/v2i1bwa81b2aywdv9dzpwnbwdj34fk1q-qtsensors-5.4.2
/nix/store/hbf6qv1smm0icmd1b4k9a65fy18f0vzq-qtwebkit-5.4.2
/nix/store/kxk8902v47wlc8c4yazpa8s6rqyxd7c9-mesa-10.6.9
/nix/store/zhxkznndkxslvbgly1679alcr6cbxl0c-pangomm-2.34.0
/nix/store/rxyyaym10nlgipxy6nmnyslvpcp9jp62-gtkmm-2.24.4
/nix/store/nzc2177mndjcdm5jbcbz44dfzjsvc3k5-open-vm-tools-9.10.0-2476743
/nix/store/rz15qah68x7iw26vpl2ncl735j5s08kl-mesa-drivers+txc-10.6.9
```

I noticed that the mesa-drivers+txc is in both outputs.

So I did `nix-store -qR /nix/store/rz15qah68x7iw26vpl2ncl735j5s08kl-mesa-drivers+txc-10.6.9` and I am going to spare you the output (See https://gist.github.com/NeQuissimus/9f60d190f4dfa329036b if really curious), but this is where the two noglus seem to be coming from:

```
[...]
/nix/store/nmvg33m7xsd687wh6figf5hgiw1bj2qc-systemd-217
/nix/store/nrfya0bfgfv8qf4kxm0ngx1l11y506r6-libXext-1.3.3
/nix/store/xnhxsxi92b02szh8d6hs11dhmlx28jmj-libXxf86vm-1.1.4
/nix/store/8sxa34shq6zkdh8i6869mn3ksrx7qbbc-mesa-noglu-10.6.9
/nix/store/jcigz9kr14vnqyjwsj8q3rfr4ac9ijbg-mesa-noglu-10.6.9
/nix/store/jlilsfyc0cwik6bix13lrixrxzj90i79-libtxc_dxtn_s2tc-1.0
/nix/store/vwmsvqbc0phcqq2r56b0cg9rlsb2f8aw-ncurses-5.9
/nix/store/qyi57rvy210bkrkj7wfg4hqw9gs8aivr-llvm-3.6.2
[...]
```

**Comment by lethalman** [comment]
So with lightdm I don't see anything and cannot switch tty. Cannot find anything relevant in the logs yet...

**Comment by lethalman** [comment]
The only relevant line is:
```
display-manager-start[1569]: ** (lightdm:1569): CRITICAL **: session_get_login1_session_id: assertion 'session != NULL' failed
```
Then the service just fails and restarts.

**Comment by dezgeg** [comment]
BTW master has a new systemd version (228) which fixes a known issue (#11480), maybe it's worth to try that one as well.

**Comment by lethalman** [comment]
Ok I realized it's a problem when using the vboxvideo driver. With vesa everything seems ok.

`systemctl start virtualbox` hangs and cannot start cc @aszlig :
```
# systemctl list-jobs
virtualbox.service  start waiting
multi-user.service  start waiting
dev-vboxguest.device start running
```

On a side note, I don't see anymore problems about umounting stuff from systemd.

**Comment by lethalman** [comment]
Doing a `modprobe vboxguest` make `systemctl start virtualbox` work. So for some reason the kernel module is not auto loaded.

**Comment by lethalman** [comment]
@aszlig maybe those vbox modules should go into `/etc/modules-load.d/nixos.conf` ?

**Comment by lethalman** [comment]
@edolstra @aszlig I think we have a serious problems with `*.device`. With the new systemd they are all loaded/inactive, and starting them hangs.

**Comment by lethalman** [comment]
Sorry something wrong is happening now and then. `systemctl status` says it's active after the manual `modprobe vboxguest`. But starting `dev-vboxguest.device` does not load the module.

**Comment by lethalman** [comment]
This is how archlinux does it by manually loading the modules: https://projects.archlinux.org/svntogit/community.git/tree/trunk/vboxservice.service?h=packages/virtualbox

I wonder, why were the modules loaded automatically before our systemd 227 switch? We changed something in nixos or virtualbox service?

**Comment by NeQuissimus** [comment]
@lethalman 

I just updated with 146784f835a6cadc65812c5adf76533c18e5be61 master.
My VirtualBox VM works fine after multiple reboots.

```
~> systemctl --version
systemd 228
+PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

Immediately after reboot:
```
~> systemctl status dev-vboxguest.device
● dev-vboxguest.device - /dev/vboxguest
   Follow: unit currently follows state of sys-devices-virtual-misc-vboxguest.device
   Loaded: loaded
   Active: active (plugged) since Fri 2015-12-11 16:41:40 UTC; 49s ago
   Device: /sys/devices/virtual/misc/vboxguest

Dec 11 16:41:40 nixie systemd[1]: Found device /dev/vboxguest.
```

services section in my `configuration.nix`:
```
services = {
    xserver = {
      enable = true;
      defaultDepth = 24;
      videoDriver = "virtualbox";
      exportConfiguration = true;
      autorun = true;
      monitorSection = ''ModeLine "1920x1080" 146.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync'';
      resolutions = [ {x = 1920; y = 1080;} ];
      windowManager.awesome.enable = true;
      desktopManager.xterm.enable = false;
      displayManager.slim.enable = true;
    };

    openssh = {
      enable = true;
      passwordAuthentication = false;
      permitRootLogin = "no";
    };

    nscd.enable = false;
  };
```

**Comment by aszlig** [comment]
This is probably related to NixOS/systemd#3 also why the `virtualbox` VM test fails. I have to leave in a few minutes but will update `systemd` later (until someone else did it in the meantime).

**Comment by lethalman** [comment]
@NeQuissimus thanks, that's weird... you don't have anything else vbox specific in your config?

**Comment by NeQuissimus** [comment]
@lethalman This is my full config: https://github.com/NeQuissimus/DevSetup/blob/master/VM.configuration.nix

**Comment by aszlig** [comment]
@NeQuissimus: Can you check whether fb37fc631ae299ed5f2d515b420cef13bb0e2a26 fixes this?

**Comment by lethalman** [comment]
Thanks will investigate further tomorrow I hope...

**Comment by NeQuissimus** [comment]
@aszlig I never had any issues. 
Just helping out @lethalman with the investigation here :-) 
If I find the time, I can check out prior to that commit and `nixos-rebuild switch` I suppose. But it may be a few days...

**Comment by NeQuissimus** [comment]
BTW, I checked out master just before fb37fc6 and rebuilt. My virtualbox.service hangs as part of the `nixos-rebuild`. Once I reboot, everything is fine.

**Comment by xor-xor** [comment]
I've got the same error as originally reported by @lethalman (`CommandLine Error: Option 'no-x86-call-frame-opt'` etc.) - but instead of a virtualbox, I got this on my host OS (after I did `nix-channel --update` followed by `nixos-rebuild switch`; I'm on `nixos-unstable`, btw).

Thankfully, I had my previous configuration available :wink:

Happy to provide any further info, if needed.

**Comment by lethalman** [comment]
@xor-xor It can be workarounded with https://github.com/NixOS/nixpkgs/pull/11367

**Comment by xor-xor** [comment]
Yep, #11367 works for me too. Thanks!

**Comment by joriskcf** [comment]
I have this problem as well. Will I have to keep relying on the workaround or will this be fixed at some point?

**Comment by lethalman** [comment]
It has to be fixed of course. I'm currently on vacation so won't work on
it... needs quite some debugging to understand what's going on. I've found
that some other distros had this problem for some time too, so it must be
caused by some conditions.

On Sat, Jan 2, 2016 at 11:16 PM, joriskcf <notifications@github.com> wrote:

> I have this problem as well. Will I have to keep relying on the workaround
> or will this be fixed at some point?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/11467#issuecomment-168434864>.
>



-- 
NixOS Linux <http://nixos.org>

**Comment by roconnor** [comment]
I have this issue too.  I haven't been able to boot from the unstable channel since the end of november.  I'll try the workaround.

**Comment by auntieNeo** [comment]
This issue affects my laptop with a Radeon HD 6310. The override also works for me.

Ping me if anyone needs to test this issue on actual hardware. I'm not sure where to grab logs because half of the time it freezes my laptop and I need to hard-reset.

**Comment by lethalman** [comment]
You can read the logs of the previous boot with journalctl.

**Comment by lethalman** [comment]
The llvm 3.6 fix is on master. But let's leave this issue open, we have to upgrade llvm at some point also for mesa.

**Comment by roconnor** [comment]
Do we think this is a build configuration error (i.e. we are responsible) or software error (i.e. upstream is responsible)?

**Comment by lethalman** [comment]
@roconnor it's our problem, given other distros are using mesa with llvm 3.7. Btw IIRC I've seen redhat having this kind of problem but I didn't understand how they solved it.

**Comment by domenkozar** [comment]
I'm getting this on f727f81. 

```
$ nix-shell -p xorg.xorgserver --command "Xvfb -screen 0 1024x768x16 -ac"
: CommandLine Error: Option 'no-x86-call-frame-opt' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**Comment by vcunat** [comment]
Ugh, so that would be even with llvm-3.6.1...

**Comment by domenkozar** [comment]
Following patch fixes the issue for me:

```
-  mesa_noglu = mesaDarwinOr (callPackage ../development/libraries/mesa {
-    # makes it slower, but during runtime we link against just mesa_drivers
-    # through /run/opengl-driver*, which is overriden according to config.grsecurity
-    grsecEnabled = true;
-  });
-  mesa_glu =  mesaDarwinOr (callPackage ../development/libraries/mesa-glu { });
-  mesa_drivers = mesaDarwinOr (
-    let mo = mesa_noglu.override {
-      grsecEnabled = config.grsecurity or false;
-      llvmPackages = llvmPackages_36; # various problems with 3.7; see #11367, #11467
-    };
-    in mo.drivers
-  );
+  mesa_noglu = mesaDarwinOr (callPackage ../development/libraries/mesa {  grsecEnabled = false;});
+  mesa_glu =  mesaDarwinOr (callPackage ../development/libraries/mesa-glu { grsecEnabled = false;});
+  mesa_drivers = mesaDarwinOr (mesa_noglu.drivers);
```

**Comment by vcunat** [comment]
That's strange. Mainly, it shouldn't matter what mesa you *build* against but which you *run* against, i.e. `/run/opengl-driver/lib` that should be pointed-to by `$LD_LIBRARY_PATH` and populated by `mesa_drivers` (if you use those).

**Comment by vcunat** [comment]
Ah, well this path is set up by the display-manager job, which might not be in your test case. It's possible that the grsecurity-enabled variant is less reliable, but the main problem is that probably in some cases we load a version that we shouldn't load.

**Comment by nrolland** [comment]
I am trying to upgrade eventstore to 3.4.0 from a 15.09 nispkgs release, and I hit that problem. is adding the @domenkozar override the best way to solve this at my level ?

**Comment by domenkozar** [comment]
@nrolland best to try it out, it worked for me.

**Comment by tdimiduk** [comment]
I am using nixos unstable on a Radeon HD5750 and used to have this problem, but am now able to boot without @domenkozar's patch.

**Comment by domenkozar** [comment]
@vcunat did you fix this? :)

**Comment by vcunat** [comment]
I don't know &ndash; there were some changes in the meantime that could have fixed it, so I [asked](https://github.com/NixOS/nixpkgs/pull/11367#issuecomment-220393282) but getting no reply I dropped the override to llvm-3.6 and used llvm-3.8 instead.

**Comment by vcunat** [comment]
Note that this patch was included in master (so wasn't needed) and I only dropped it recently. And some people could never reproduce the bug, e.g. myself.

**Comment by vcunat** [comment]
Well, reopen if this happens again.
