### ISSUE TITLE
Add remacs 0.1

### ISSUE THREAD

**Issue by haller33** [NixOS/nixpkgs#114606]
**Project description**
fork of gnu emacs in rust

**Metadata**

* homepage URL: https://github.com/remacs
* source URL: https://github.com/remacs/remacs.git
* license: gpl+3
* platforms: linux and macOS

**Comment by AndersonTorres** [comment]
This is a huge and still unstable software indeed.

**Comment by leungbk** [comment]
There is some ongoing work packaging emacs-ng: https://github.com/nix-community/emacs-overlay/issues/114

I think packaging that makes more sense than packaging remacs 0.1, which is based on Emacs 26.

**Comment by bhipple** [comment]
Last I looked at it, it seemed remacs development had stalled and the project might be dying, so it's probably not appropriate to include in nixpkgs proper (perhaps use NUR).  If you're interested for the Rust portion that's fine, but if you're looking for just some newer / faster / better emacs, we do have [gccemacs packaged](https://github.com/NixOS/nixpkgs/issues/87400) in the community overlays.

**Comment by haller33** [comment]
I'm really interesting in remacs just because of the rust core, not because is faster / better

**Comment by brotzeit** [comment]
As a former remacs maintainer I can confirm that it's better to close this pull request. emacs-ng is the replacement for remacs.
