### ISSUE TITLE
gnome-tour: build fails to find generated resources

### ISSUE THREAD

**Issue by collares** [NixOS/nixpkgs#114659]
**Describe the bug**
`gnome-tour` fails to compile with 

```

error: couldn't read /build/gnome-tour-3.38.0/build/data/resources.gresource: No such file or directory (os error 2)
 --> src/static_resources.rs:9:21
  |
9 |     let res_bytes = include_bytes!("/build/gnome-tour-3.38.0/build/data/resources.gresource");
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `gnome-tour`
```

**Additional context**
See https://github.com/NixOS/nixpkgs/pull/112804#issuecomment-787451363 for a possible cause.

**Notify maintainers**
cc @worldofpeace @danieldk @jtojnar (sorry for notifying you here and in the PR!)

**Comment by worldofpeace** [comment]
Gonna try to just switch it to `cargoSetupHook`. We should probably update gnome docs for Rust+Gnome packages

**Comment by danieldk** [comment]
> Gonna try to just switch it to `cargoSetupHook`. We should probably update gnome docs for Rust+Gnome packages

Yeah, I think that would be best. The idea of the hooks is that `buildRustPackage` is not necessary anymore in mixed projects. I will also do a PR for cargoBuildHook, since it should not be used when `buildPhase` is set explicitly.
