### ISSUE TITLE
Packaging Swift

### ISSUE THREAD

**Issue by jb55** [NixOS/nixpkgs#11463]
I [spent a little time](https://gist.github.com/jb55/cfe98b39cc64a473fd93) on this last night, thought I'd write down some of the things that need to get done.

Swift uses it's own custom llvmPackages. I initially tried to do the naive thing and download all the [apple/swift-{llvm,clang,...}](https://github.com/apple/swift#getting-sources-for-swift-and-related-projects)  sources and let their build script do it's thing. The problem with that is, their build script attempts to symlink clang into the llvm folder, which was a no go.

Alternatively we could make a llvmPackages_swift and see if that works, I haven't looked into that yet.

I'm sure one of you nix ninjas can figure this out quicker than I can, I thought I'd open this issue to prevent double work.

**Comment by jb55** [comment]
Now that I think about it I could just copy the llvm and clang folder into the build dir, think I'll try that next.

**Comment by jb55** [comment]
It's compiling! PR soon hopefully.

**Comment by copumpkin** [comment]
w00t! cc @pikajude who was also talking about doing this

**Comment by jb55** [comment]
Got it to compile, have some remaining issues compiling libs because of some [ninja assumptions](https://github.com/apple/swift/blob/5a54c7ef2188c8e890f2b809894d3f0e5c1bb0c1/stdlib/public/Glibc/module.map#L28)

**Comment by copumpkin** [comment]
`substituteInPlace` all the things!

**Comment by jb55** [comment]
hmm strange, I fixed up the map file. but it seems like the swift compiler still isn't picking up the lib path:
```
+ /nix/store/0hxhy52fynrik1myrxg4h6l16a27h146-cmake-3.3.2/bin/cmake --build /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64 -- all swift-stdlib-linux-x86_64
[2/15] Compiling /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/stdlib/public/Glibc/linux/x86_64/Glibc.o
FAILED: cd /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/stdlib/public/Glibc && /nix/store/0hxhy52fynrik1myrxg4h6l16a27h146-cmake-3.3.2/bin/cmake -E make_directory /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/stdlib/public/Glibc/linux/x86_64 && /nix/store/0hxhy52fynrik1myrxg4h6l16a27h146-cmake-3.3.2/bin/cmake -E make_directory /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/./lib/swift/linux/x86_64 && /home/jb55/dev/swift/swift/utils/line-directive /home/jb55/dev/swift/swift/stdlib/public/Glibc/Glibc.swift -- /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/./bin/swiftc -c -sdk / -target x86_64-unknown-linux-gnu -Onone -g -D INTERNAL_CHECKS_ENABLED -I /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/./lib/swift/linux/x86_64 -module-cache-path /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/./clang-module-cache -no-link-objc-runtime -autolink-force-load -module-link-name swiftGlibc -force-single-frontend-invocation -parse-as-library -emit-module -emit-module-path /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/./lib/swift/linux/x86_64/Glibc.swiftmodule -o /home/jb55/dev/swift/Ninja-DebugAssert/swift-linux-x86_64/stdlib/public/Glibc/linux/x86_64/Glibc.o /home/jb55/dev/swift/swift/stdlib/public/Glibc/Glibc.swift
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h"
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:10: error: 'features.h' file not found with <angled> include; use "quotes" instead
#include <features.h>
         ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h"
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:10: note: in file included from /nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:
#include <features.h>
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/features.h:343:10: error: 'stdc-predef.h' file not found with <angled> include; use "quotes" instead
#include <stdc-predef.h>
         ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h"
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:10: note: in file included from /nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:
#include <features.h>
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/features.h:365:12: error: 'sys/cdefs.h' file not found with <angled> include; use "quotes" instead
#  include <sys/cdefs.h>
           ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h"
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:10: note: in file included from /nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/complex.h:25:
#include <features.h>
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/features.h:365:12: note: in file included from /nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/features.h:365:
#  include <sys/cdefs.h>
           ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/sys/cdefs.h:402:10: error: 'bits/wordsize.h' file not found
#include <bits/wordsize.h>
         ^
/home/jb55/dev/swift/swift/stdlib/public/Glibc/Glibc.swift:13:19: error: could not build Objective-C module 'SwiftGlibc'
@_exported import SwiftGlibc // Clang module
                  ^
ninja: build stopped: subcommand failed.
./utils/build-script: command terminated with a non-zero exit status 1, aborting
```
will have to look into swift include paths...

**Comment by jb55** [comment]
oh, I think I just need to add those missing files to the module.map! almost there...

**Comment by jb55** [comment]
I was able to fix most of the errors by moving module definitions around in the `module.map` file:

```
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/sys/cdefs.h"
         ^
/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/include/sys/cdefs.h:23:11: error: 'features.h' file not found
# include <features.h>
          ^
/home/jb55/dev/swift/swift/stdlib/public/Glibc/Glibc.swift:13:19: error: could not build Objective-C module 'SwiftGlibc'
@_exported import SwiftGlibc // Clang module
                  ^
ninja: build stopped: subcommand failed.
./utils/build-script: command terminated with a non-zero exit status 1, aborting
```

but it seems that `feature.h` and `sys/cdefs.h` have a circular reference on each other, and I'm not sure how to represent that in the `module.map`. Which I also learned is a [Clang Module](http://clang.llvm.org/docs/Modules.html) file

**Comment by jb55** [comment]
I got stuck on this point and I don't have much time to work on it this week, if anyone else wants to take a stab at it.

**Comment by jb55** [comment]
Looks like their latest snapshot cmakeified the glibc stuff, trying again

**Comment by copumpkin** [comment]
@jb55 how did that go? feel free to come hang out in ##nix-darwin on freenode if you want guidance/help!

**Comment by jb55** [comment]
I got reallly close, it compiled and everything. I just need to do the final 1% of patching some LD library paths if I remember correctly. I've updated the gist: https://gist.github.com/jb55/cfe98b39cc64a473fd93

for testing I was doing this:

$ nix-shell
$ genericBuild

and after that I was running `./utils/build-script` manually.

**Comment by paspanag** [comment]
Hi @jb55, How did you get around the feature.h and sys/cdefs.h dependency? I'm having the same problem at the moment with netbsd rumpkernel.

**Comment by matthewbauer** [comment]
How is this effort going?

**Comment by jb55** [comment]
It's almost been a year! I'll take a stab at this again over the Holidays.

**Comment by dtzWill** [comment]
Ping! Any progress (or blockers) on this?

**Comment by dtzWill** [comment]
I'm poking at this now in some spare time, I'll share if I get anything that seems to work! :)

**Comment by mhsjlw** [comment]
Awesome. This will be the last piece of the puzzle for me to switch my OS to nixOS :)

**Comment by dtzWill** [comment]
Testing/feedback/review requested, if you're interested:

Swift 3.1-dev: https://github.com/NixOS/nixpkgs/pull/22098
WIP support for building Swift things with Nix:  https://github.com/NixOS/nixpkgs/issues/22138

**Comment by matthewbauer** [comment]
Can we close this one? @dtzWill @jb55

At some point I want to get Swift working on OS X but for now I think we can at least close this issue.

**Comment by dtzWill** [comment]
Sounds good!

**Comment by jb55** [comment]
👍
