### ISSUE TITLE
closure-size:  bash-4.3-p42 sha256sum wrong?

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#11475]
For a certain, supposedly irrelevant `default.nix` (do tell if the assumption is invalid[1]):
```
[deepfire@andromedae:~/src/foo]$ nix-shell
these derivations will be built:
  /nix/store/1jbcg5g2q94vfjdmysm21cfak1p39h0b-patchelf-0.8.tar.bz2.drv
  /nix/store/8p74xc5qh6rnpbcirbs3nh3yqzp3qqqa-binutils-2.23.1.tar.bz2.drv
  /nix/store/nq2ls2c1h79i5ap1gnmd6w2cw8hlxk0n-stdenv-linux-boot.drv
  /nix/store/5b7m6x9rqmyxh0jjlrxnzazqxyivq2n3-zlib-1.2.8.tar.gz.drv
  /nix/store/rv12b2m2bxfwaxsmap00ll2xgwh69hd2-zlib-1.2.8.drv
  /nix/store/4ahinajcr73pvqjr6ygpdbxrfm2al68k-binutils-2.23.1.drv
  /nix/store/fvf5y1jz49jh0zwm2hvjxzwilykw9vkf-bootstrap-gcc-wrapper.drv
  /nix/store/s72725vfv5085h80v2r6gvk8h0l2nj2r-stdenv-linux-boot.drv
  /nix/store/19dn1d7gwghimvsqbdn7vhrh0r3yydqn-patchelf-0.8.drv
  /nix/store/sx0wpzfny8vkyxlz8ya3f6fmd7kr4phd-paxctl-0.9.tar.gz.drv
  /nix/store/3c6602knqai4r39xxy68qmdbmfyj15xg-paxctl-0.9.drv
  /nix/store/zqxpypd8jwr404rk0m53zqhgxazna8yq-bootstrap-gcc-wrapper.drv
  /nix/store/236v1spw1bsr1268k4zyf0yvy0lk4sm6-stdenv-linux-boot.drv
  /nix/store/aymidq3z2qf46xg92ziapkylm9p471rq-xz-5.2.2.tar.bz2.drv
  /nix/store/1hj1lpb7sh80sw1x2l3lgwkm3xi8sz82-xz-5.2.2.drv
  /nix/store/4igcpagb596hbx72c8mjhbjb2a3sp783-bash43-042.drv
  /nix/store/izrbfh6c7x7256f4iy9fri58j0j5l4jy-m4-1.4.17.tar.bz2.drv
  /nix/store/dracj7vyihgd1yr719m2ndax3ba2wb5h-gnum4-1.4.17.drv
  /nix/store/4pbmlndgy3rhdhxshnnn9bjyaqr6nn61-perl-5.20.2.tar.gz.drv
  /nix/store/m4f74x8xgc7vy7lwz5fv3q1hx8dzdznl-perl-5.20.2.drv
  /nix/store/5zsmd6q6b680zw2zkbxq6q0xdax1kg7i-gcc-wrapper-5.2.0.drv
  /nix/store/zn62936j2f3b2y6x65qfmdkysas85dhl-stdenv-linux-boot.drv
  /nix/store/7c28hg63yilkxpr1407krbks00pd8afx-bison-3.0.4.drv
  /nix/store/j87cf4j1k43fn8pwr854vpkj55y3jkh5-bash-4.3.tar.gz.drv
  /nix/store/30iik7j8h1bz57700af4a09nrcd24qab-bash-4.3-p42.drv
building path(s) ‘/nix/store/vs9n9mc6gr5xb1qrwwhwy1c81m4hih65-bash-4.3.tar.gz’
building path(s) ‘/nix/store/pdwz581jbf27cm2lvmngrhnrbyd5bv7a-bash43-042’
building path(s) ‘/nix/store/y5m8m5w71mj01f7chl7xp5vnyq5bqh8n-m4-1.4.17.tar.bz2’
building path(s) ‘/nix/store/6zgj0paw1dys71fs42a5wqa0r49fpzcw-patchelf-0.8.tar.bz2’
building path(s) ‘/nix/store/03x74ppaffnr30qwbgf9s20v3khnchln-perl-5.20.2.tar.gz’
building path(s) ‘/nix/store/l319rldii28z3w44r0irafphn34xs8f1-stdenv-linux-boot’
building path(s) ‘/nix/store/v7qfzxx0px8k7898k8zibym2hr11x2ap-xz-5.2.2.tar.bz2’
building path(s) ‘/nix/store/n69kz335c800n2b6izsjbw60rlnvp87c-binutils-2.23.1.tar.bz2’
building path(s) ‘/nix/store/0a10anrr73r5b4215mp6y1241cbrrl6c-paxctl-0.9.tar.gz’
output path ‘/nix/store/pdwz581jbf27cm2lvmngrhnrbyd5bv7a-bash43-042’ should have sha256 hash ‘1bwhssay66n75fy0pxcrwbm032s6fvfg7dblzbrzzn5k38a56nmp’, instead has ‘06a90k0p6bqc4wk2dsmapna69124an76xvlnlj3xm497vci968dc’
cannot build derivation ‘/nix/store/30iik7j8h1bz57700af4a09nrcd24qab-bash-4.3-p42.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/30iik7j8h1bz57700af4a09nrcd24qab-bash-4.3-p42.drv’ failed
/home/deepfire/.nix-profile/bin/nix-shell: failed to build all dependencies
```

--
1. If it is important, default.nix depends on:
```
mkDerivation stdenv
python pythonPackages curl wsmancli sshpass
base base-unicode-symbols binary bytestring containers
directory GenericPretty ghc-prim hashable interpolatedstring-perl6 MissingH pretty QuasiText c2hs
process shake tuple unordered-containers
ghc.cabal-install
ghci-ng hell-git
emacs git gitAndTools.git-extras silver-searcher w3m zim
```

**Comment by deepfire** [comment]
Also, curiously, it worked with `883109b36aebcd27aba5fe60de1e23d830c11e14`.
It broke after I rebiuld-switched into `34b5d193c0c0c02bd0f17b8af9d8fa9422c75782`, rebooted and attempted to re-enter the nix-shell environment.

**Comment by copumpkin** [comment]
It's fixed in staging. See #11456 and several other fixes

**Comment by deepfire** [comment]
when is closure-size supposed to have staging merged into it?

**Comment by copumpkin** [comment]
Not sure, but @vcunat might know.

**Comment by vcunat** [comment]
I don't want to cause mass rebuilds too often, so probably not yet. Currently there are thousands of various failures in the Hydra job. Those are independent, as Hydra doesn't re-download the patch, so I would prefer to move on with the fixing before staging merge, as it's much easier when binaries from Hydra are available.

Also, there's indication that some stdenv fixes will be needed in closure-size.

**Comment by acowley** [comment]
This is tough on darwin users as `nixos-unstable` is currently offering neither binaries nor buildable derivations (namely, this bash issue). Is there any suggestion for how to better navigate this kind of trouble?

**Comment by vcunat** [comment]
@acowley: nixos-* channels aren't meant for darwin. If you want binaries for darwin from nixos.org, use nixpkgs-unstable. (You also don't seem to be interested in the closure-size branch, which is what's discussed in this particular ticket.) Maybe there are (still) unofficial sources with fresher binaries http://comments.gmane.org/gmane.linux.distributions.nixos/15108. There's just a single Mac Mini in the official build farm ;-)

**Comment by acowley** [comment]
Yeah, sorry for the tangent, but other issues (eg #11593) are closed as duplicates of this one. The zalora cache is also not up to date at the moment. I couldn't find a repo with a `nixpkgs-unstable` branch similar to the `nixos-unstable` channel branch last time I looked, and I was told they were similar enough to not be worth worrying about. My point really was just to point out that the delay in getting the bash fixes merged into unstable isn't preserving a good status quo at least for Darwin users, as I know you're not on Darwin and I'm not sure who else is minding the hydra and related merges.

**Comment by vcunat** [comment]
#11456 is the original PR. I'm not sure but I think Darwin people here mostly just rebuild themselves &ndash; supposedly they've got strong machines. Several weeks ago on NixCon there were thoughts about using some service that offers "hiring remote Macs", but there was lots of talking in general and very little subsequent action so far.

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/11456.
