### ISSUE TITLE
Please add derivations for Amazon Corretto JDK (8, 11, 15)

### ISSUE THREAD

**Issue by ldeck** [NixOS/nixpkgs#114795]
**Project description**
No-cost, multiplatform, production-ready distribution of OpenJDK.

**Metadata**

* homepage URL: https://aws.amazon.com/corretto/
* source URL: https://github.com/corretto/corretto-8, https://github.com/corretto/corretto-11, https://github.com/corretto/corretto-jdk.
* license: gpl2+
* platforms: unix, linux, darwin

**Comment by petabyteboy** [comment]
I'm not even sure if we would be allowed to redistribute the Corretto JDK for trademark reasons.

> 1. Can I create and redistribute my own builds of Amazon Corretto? : If you build Amazon Corretto from source and redistribute the results, you may use the Corretto Trademarks only if it is clear in both the name of your distribution and the content associated with it that your distribution is your build of Amazon Corretto and not the official build, and you must identify the commit from which it is built, including the commit date.

Why would you want to use Coretto JDK instead of the normal jdk11 builds or AdoptOpenJDK binary releases?

**Comment by ldeck** [comment]
I'd misread the prerequisites for AWS CDK (https://cdkworkshop.com/15-prerequisites/800-java.html), actually. 

Nevertheless, other packager managers (e.g., Homebrew's [correto cask](https://formulae.brew.sh/cask/corretto)) seem to provide this as a package, so I thought it would be useful for it to be available via nix.

Perhaps rather than building from source, it could be a derivation linking to the official packages?

**Comment by petabyteboy** [comment]
> Perhaps rather than building from source, it could be a derivation linking to the official packages?

It's not trivial to run prebuilt binaries in a Nix environment. They need to be patched to reference (link to) shared libraries in the Nix store. Even then, I'm not sure if we would still be allowed to call it Amazon Coretto JDK since we would have to modify the binaries.

> Nevertheless, other packager managers (e.g., Homebrew's correto cask) seem to provide this as a package, so I thought it would be useful for it to be available via nix.

Unless there's some feature missing in our own OpenJDK builds, I would strongly prefer not to package yet another binary JDK.

**Comment by ldeck** [comment]
Fair enough @petabyteboy. Thanks for the explanation.
