### ISSUE TITLE
Agda fails to build Hello world

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#114787]
**Describe the bug**

```
% cat leftpad.agda
module leftpad where

open import IO

main = run (putStrLn "Hello, World!")
% agda leftpad.agda
Checking leftpad (/home/suhr/Projects/agda-examples/leftpad.agda).
/home/suhr/Projects/agda-examples/leftpad.agda:3,1-15
Failed to find source of module IO in any of the following
locations:
  /home/suhr/Projects/agda-examples/IO.agda
  /home/suhr/Projects/agda-examples/IO.lagda
  /nix/store/kyqkdysxq61v6z0s6wsk1lccilqnch7c-Agda-2.6.1.3-data/share/ghc-8.10.4/x86_64-linux-ghc-8.10.4/Agda-2.6.1.3/lib/prim/IO.agda
  /nix/store/kyqkdysxq61v6z0s6wsk1lccilqnch7c-Agda-2.6.1.3-data/share/ghc-8.10.4/x86_64-linux-ghc-8.10.4/Agda-2.6.1.3/lib/prim/IO.lagda
when scope checking the declaration
  open import IO
```

**To Reproduce**
1. Install `agdaPlus = pkgs.agda.withPackages (p: [ p.standard-library p.cubical ]);` with `nix profile install self#agdaPlus`
2. Create a file containing Hello world in Agda
3. Try to build Hello world

**Expected behavior**
Agda should find the standard library.

**Additional context**
There's no documentation on how to make a usable Agda environment in NixOS.

**Notify maintainers**
cc @turion @alexarice 

**Metadata**
```
% nix shell self#nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05.20210228.0aeba64 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"home-manager, nixos-21.05pre271444.9816b99e71c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by turion** [comment]
I can reproduce on nixos-21.03pre268206.536fe36e23a with an equivalent `nix-shell`.

On an unrelated note: We now have an agda label :tada:

**Comment by alexarice** [comment]
> **Expected behavior**
> Agda should find the standard library.
> 

Could you try 
```
agda -l standard-library-1.5 leftpad.agda
```
and see if this resolves the issue. Nix lets agda know where it can find the standard library, but does not tell it to use it.

> **Additional context**
> There's no documentation on how to make a usable Agda environment in NixOS.
> 

Does this not contain the information you need? https://nixos.org/manual/nixpkgs/stable/#agda if not there is a current pr (https://github.com/NixOS/nixpkgs/pull/110491) trying to improve this documentation

**Comment by alexarice** [comment]
@turion as a side note the agda test https://github.com/NixOS/nixpkgs/blob/80308388cd77ee58823c9b6f24b46892cd359145/nixos/tests/agda.nix#L39 is almost certainly broken ever since standard library moved from having the name as `standard-library` to `standard-library-${version}`

**Comment by turion** [comment]
> Could you try
> 
> ```
> agda -l standard-library-1.5 leftpad.agda
> ```
> 
> and see if this resolves the issue. Nix lets agda know where it can find the standard library, but does not tell it to use it.

I get: 


```
$ agda -l standard-library-1.5 leftpad.agda
/home/turion/elixir/nx_showcase/leftpad.agda:1,8-15
The name of the top level module does not match the file name. The
module leftpad should be defined in one of the following files:
  /nix/store/yym449y2zinsp5jrqpg6nykkdyz2aidi-standard-library-1.5/src/leftpad.agda
  /nix/store/yym449y2zinsp5jrqpg6nykkdyz2aidi-standard-library-1.5/src/leftpad.lagda
  /nix/store/xdw06lf04s5qigckz6gyvmcs5sm2fls8-Agda-2.6.1.2-data/share/ghc-8.10.3/x86_64-linux-ghc-8.10.3/Agda-2.6.1.2/lib/prim/leftpad.agda
  /nix/store/xdw06lf04s5qigckz6gyvmcs5sm2fls8-Agda-2.6.1.2-data/share/ghc-8.10.3/x86_64-linux-ghc-8.10.3/Agda-2.6.1.2/lib/prim/leftpad.lagda
```

This works though:

```
$ agda -l standard-library-1.5 -i . leftpad.agda
Checking leftpad (/home/turion/elixir/nx_showcase/leftpad.agda).
Unsolved metas at the following locations:
  /home/turion/elixir/nx_showcase/leftpad.agda:5,8-11
```

This is also how it is called [in the integration test](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/agda.nix), and thus the behaviour that is guaranteed to work.

> > **Additional context**
> > There's no documentation on how to make a usable Agda environment in NixOS.
> 
> Does this not contain the information you need? https://nixos.org/manual/nixpkgs/stable/#agda

It seems that you're using nix flakes? I haven't tried them yet, but if this is the case, and you get it to work, can you comment here briefly and we can work that into a PR.

**Comment by turion** [comment]
> @turion as a side note the agda test
> 
> https://github.com/NixOS/nixpkgs/blob/80308388cd77ee58823c9b6f24b46892cd359145/nixos/tests/agda.nix#L39
> is almost certainly broken ever since standard library moved from having the name as `standard-library` to `standard-library-${version}`

No, it works without the version number as well:

```
$ agda -l standard-library -i . leftpad.agda
Checking leftpad (/home/turion/elixir/nx_showcase/leftpad.agda).
Unsolved metas at the following locations:
  /home/turion/elixir/nx_showcase/leftpad.agda:5,8-11
```

**Comment by suhr** [comment]
But `Unsolved metas` is a some kind of error?

**Comment by alexarice** [comment]
> 
> 
> But `Unsolved metas` is a some kind of error?

see https://github.com/agda/agda/issues/4250. In particular the message ~28 days ago. This is an agda issue, not a nix issue

**Comment by turion** [comment]
> But `Unsolved metas` is a some kind of error?

Yes, it means that Agda failed to resolved some meta variables (like types, or kinds of types). But this is a good sign in your case, it means that at least running Agda succeeded, and it found a type error.

**Comment by suhr** [comment]
So the correct version of Hello world is the following:

```
module leftpad where

open import IO
open import Level

main = run {0ℓ} (putStrLn "Hello, World!")
```

And also you need an `.agda-lib` file in the project root:

```
name: <library name>
depend:
    standard-library
include: src
```

**Comment by neosimsim** [comment]
> > @turion as a side note the agda test
> > https://github.com/NixOS/nixpkgs/blob/80308388cd77ee58823c9b6f24b46892cd359145/nixos/tests/agda.nix#L39
> > 
> > is almost certainly broken ever since standard library moved from having the name as `standard-library` to `standard-library-${version}`
> 
> No, it works without the version number as well:
> 
> ```
> $ agda -l standard-library -i . leftpad.agda
> Checking leftpad (/home/turion/elixir/nx_showcase/leftpad.agda).
> Unsolved metas at the following locations:
>   /home/turion/elixir/nx_showcase/leftpad.agda:5,8-11
> ```

Agda supports versioned libraries. It was just never used. https://agda.readthedocs.io/en/v2.6.1.3/tools/package-system.html#version-numbers

**Comment by neosimsim** [comment]
Does anyone know why the '-i' option or an `.agda-file` is required as soon as the `-l` options is passed?

**Comment by neosimsim** [comment]
> And also you need an `.agda-lib` file in the project root:
> 
> ```
> name: <library name>
> depend:
>     standard-library
> include: src
> ```

I believe instead of the `.agda-lib` file you could also add `standard-libary` to `$HOME/.agda/defaults`.

**Comment by suhr** [comment]
@neosimsim It seems like the `-i` option also specifies the project root.

> I believe instead of the .agda-lib file you could also add standard-libary to $HOME/.agda/defaults.

Indeed, but `.agda-lib` is probably a better way, since it does not depend on user configuration.

**Comment by turion** [comment]
Ok, is there still something to be fixed here? Documentation perhaps? Or shall we close?

**Comment by suhr** [comment]
The only thing that needs to be improved is the *Agda* documentation. So I close this.
