### ISSUE TITLE
fractal fails to build

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#114850]
**Describe the bug**

```
   Compiling fractal-gtk v4.4.0 (/build/source/fractal-gtk)
error: couldn't read /build/source/build/fractal-gtk/res/resources.gresource: No such file or directory (os error 2)
  --> fractal-gtk/src/static_resources.rs:8:9
   |
8  | /         include_bytes!(
9  | |             "/build/source/build/fractal-gtk/res/resources.gresource"
10 | |         );
   | |_________^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `fractal-gtk`

To learn more, run the command again with --verbose.
builder for '/nix/store/ag110w75i2dfqkb1sk827bf1frxcj8sl-fractal-4.4.0.drv' failed with exit code 101
```

**To Reproduce**
1. ...
2. ...
3. ...

**Notify maintainers**
@dtzWill @worldofpeace

**Metadata**
Trying to upgrade on unstable

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05.git.f9d9740e68e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-21.05pre273435.0aeba64fb26, nixos-hardware, nixos-unstable-21.05pre273435.0aeba64fb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: fractal
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Will be fixed by https://github.com/NixOS/nixpkgs/pull/114716.

**Comment by jtojnar** [comment]
It is still an issue on master and we should modernize the expression anyway.

**Comment by davidak** [comment]
Could that get backported to stable? It's there broken too.

**Comment by worldofpeace** [comment]
I have a realized path on nixos-20.09 `/nix/store/6qv7w1pzbz9ki2pbq6db4hp2q0vjg4rz-fractal-4.4.0`, so I don't think it's a problem
