### ISSUE TITLE
neovim: after installation python2 in neovim doesn't function

### ISSUE THREAD

**Issue by kyren** [NixOS/nixpkgs#11487]
After installing neovim, executing: ':python print "hello"' in neovim results in

> line   18:  
> Invalid channel "1"                                                                                                                                   

g:python_host_prog in python points to the nvim-python inside the nix store of the neovim-0.1.0 package.  g:loaded_python_provider is "1" though (which is apparently indicative of an error).

If I run nvim-python manually, it works fine, and if I do 'import "neovim"' inside that shell, that also works fine.  Also, running ':python3 print("hello")' works just fine.

By the way, I'm having trouble building the version from nixpkgs master, so this is with the unstable snapshot at 3087ef3.

**Comment by kyren** [comment]
sorry, this doesn't apply to python2.7-neovim, it applies to the neovim package itself

**Comment by FRidh** [comment]
Do you still have the issue? I just installed neovim with Nix Shell and ran `:python print('hello')` and it printed hello.

**Comment by manveru** [comment]
I think we can close this?
