### ISSUE TITLE
waybar: Wrong size of RFKILL event

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#114870]
**Describe the bug**
`waybar` crash on startup

```
asbachb@nixo-t14s  /tmp/waybar  waybar -c config -s style
[2021-03-02 11:22:44.083] [info] Resources files: config, style
terminate called after throwing an instance of 'std::runtime_error'
  what():  Wrong size of RFKILL event
[1]    7521 IOT instruction (core dumped)  waybar -c config -s style
```

**To Reproduce**
1. Obtain example config: https://raw.githubusercontent.com/Alexays/Waybar/master/resources/config
2. Obtain example style.css: https://raw.githubusercontent.com/Alexays/Waybar/master/resources/style.css
3. run waybar: `waybar -c config -s style.css`

**Expected behavior**
Normal application startup. No crash.

**Notify maintainers**
@FlorianFranzen @minijackson @Synthetica9 

**Metadata**
```
  /nix/store/zbiyhpj0gk7c5kbqj4nh4c5zhscmxpg4-bash-interactive-4.4-p23-dev
copying path '/nix/store/zbiyhpj0gk7c5kbqj4nh4c5zhscmxpg4-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(asbachb): `"nixos-21.03pre265961.891f607d530, nixos-20.09-20.09.2787.6e7f25001fe"`
 - channels(root): `"nixos-21.05pre273435.0aeba64fb26, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- waybar

# a list of nixos modules affected by the problem
module:
- programs.waybar.enable
```

**Comment by pimeys** [comment]
Same issue here.

**Comment by minijackson** [comment]
This seems like an upstream issue: https://github.com/Alexays/Waybar/issues/994 and will be fixed in the next release: https://github.com/Alexays/Waybar/pull/1015. Could you test with waybar master?

Recommended temporary solution is to disable the `network` and `bluetooth` module.

**Comment by berbiche** [comment]
Waybar master is available as an overlay/package from https://github.com/colemickens/nixpkgs-wayland :smile:

**Comment by toon23** [comment]
I have the same issue. This is related to [waybar issue #822](https://github.com/Alexays/Waybar/issues/822).

A workaround is to disable the network module of waybar.

**Comment by pimeys** [comment]
Tested the master version and it fixed the problems for me. Thank you.
