### ISSUE TITLE
gimp plugin wavelet-sharpen replaces gimp on upgrade

### ISSUE THREAD

**Issue by xunam** [NixOS/nixpkgs#114995]
**Describe the bug**
Using the current unstable channel, if install `gimp` in my user environment and then do an upgrade, Nix replaces `gimp` with the `wavelet-sharpen` plugin and effectively uninstalls `gimp` itself from the user environment. This does not happen in the stable branch `20.09`.

**To Reproduce**
Here is a transcript of what happens:
```
$ which gimp
which: no gimp in (/run/wrappers/bin:/home/manu/.nix-profile/bin:/etc/profiles/per-user/manu/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin)
$ nix-env -iA nixpkgs.gimp
installing 'gimp-2.10.22'
$ which gimp
/home/manu/.nix-profile/bin/gimp
$ nix-env -q | grep gimp
gimp-2.10.22
$ nix-env --upgrade
upgrading 'gimp-2.10.22' to 'gimp-2.10.22-plugin-wavelet-sharpen-0.1.2'
$ which gimp
which: no gimp in (/run/wrappers/bin:/home/manu/.nix-profile/bin:/etc/profiles/per-user/manu/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin)
$ nix-env -q | grep gimp
gimp-2.10.22-plugin-wavelet-sharpen-0.1.2
$ nix-env --uninstall gimp
uninstalling 'gimp-2.10.22-plugin-wavelet-sharpen-0.1.2'
```

**Expected behavior**
I expect `gimp` to be upgraded.

Apparently, the fact that that `gimp-2.10.22-plugin-wavelet-sharpen-0.1.2` contains numbers in the middle is the source of the problem, as if `2.10.22-plugin-wavelet-sharpen-0.1.2` was a version number, and higher than `2.10.22`.

**Notify maintainers**
The `gimp` package is maintained by @jtojnar, I don't know about the `wavelet-sharpen` plugin.

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 20.09.3246.d4189f68fdb (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(manu): `"nixpkgs-21.05pre273332.5df05c902cd"`
 - channels(root): `"nixos-20.09.3343.8d82c865b41"`
 - nixpkgs: `/home/manu/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gimp
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Ugh, I can’t wait for `nix-env` to be abandoned.

This is a regression caused by https://github.com/NixOS/nixpkgs/commit/ef5475235ce4f3d1405dca5653cbe3599f0ff637 cc @erictapen

**Comment by symphorien** [comment]
On NixOS you probably shouldn't use nix-env at all (use configuration.nix or home-manager instead) and documentation should not encourage to use it imo: https://github.com/NixOS/nixos-homepage/issues/672

**Comment by xunam** [comment]
I'm all for using the declarative approach to handle user packages, and actually my current setup consists mostly in defining an environment with `buildEnv` in `~/.config/nixpkgs/config.nix` with the packages I want. However I find the stateful system of `nix-env` to be a useful middle-ground between full declarative and using `nix-shell` for short-term usage of specific packages.

As a side note, Gimp ended up installed through `nix-env` instead of `config*.nix` because of space constraints. On a system with a few gigabytes of storage allocated for `/nix/store`, upgrading a whole system with several big packages (e.g. Gimp, TeXlive, Haskell and other things) becomes a problem because you must have two versions of each present at the same time before you can switch to the new generation and garbage-collect the old one. At least, with `nix-env`, you can uninstall those, collect garbage, upgrade and then install them back without having to hack on your declarative configuration.

As for Home Manager, I admit I am reluctant to make the switch from my years-old tuned and portable home configuration as long as the first words of its documentation are a big warning on the fact that it may break things.

**Comment by veprbl** [comment]
> Ugh, I can’t wait for `nix-env` to be abandoned.
> 

To be fair, we would need to also get rid of this behaviour:

```
nix-repl> builtins.parseDrvName "gimp-2.10.22-plugin-wavelet-sharpen-0.1.2"
{ name = "gimp"; version = "2.10.22-plugin-wavelet-sharpen-0.1.2"; }
```

**Comment by jtojnar** [comment]
Yes, I would kill `parseDrvName` too, if I could.
