### ISSUE TITLE
elfutils and stack packages conflict

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#11494]
Both the `elfutils` and `stack` packages provide a `stack` binary, which conflict.

**Comment by joachifm** [comment]
The standard solution is to indicate a precedence to manually resolve the conflict. What else would you propose?

**Comment by a1russell** [comment]
Debian and Linux from Scratch prefix all scripts from elfutils with "eu-":

https://packages.debian.org/jessie/amd64/elfutils/filelist
http://www.linuxfromscratch.org/blfs/view/svn/general/elfutils.html

**Comment by joachifm** [comment]
@edolstra is listed as the maintainer of elfutils

**Comment by a1russell** [comment]
Closing since there doesn't seem to be any interest in fixing this, and I've moved on to another distro.
