### ISSUE TITLE
cross: regression with armv7 pkgsStatic (error: C compiler cannot create executables)

### ISSUE THREAD

**Issue by samueldr** [NixOS/nixpkgs#114953]
**Describe the bug**
With #101606 many `pkgsCross.armv7l-hf-multiplatform.pkgsStatic.` attributes that were working stopped building.

**To Reproduce**
```
 $ env -i nix-build -A pkgsCross.armv7l-hf-multiplatform.pkgsStatic.hello
[...]
configure: error: in `/build/hello-2.10':                                                                                                    
configure: error: C compiler cannot create executables                                                                                       
See `config.log' for more details                                                                                                            
builder for '/nix/store/ik89nsfcnjwrb5vz7chwc2accp604grh-hello-2.10-armv7l-unknown-linux-musleabihf.drv' failed with exit code 77            
```

**Additional context**
Reverting 4e9dc46dea0ef8cf15c567fa863796bb23099d0b makes many thing work again.

I'm not sure what should be done here. On one hand I *assume* PIE is desired. But it definitely provably breaks things with cross-compilation.

It seems to be limited to armv7; the equivalent aarch64 builds work fine.

**Notify maintainers**
@Ericson2314 @matthewbauer as cross-compilation aficionados
@utsl42 author of the change

**Comment by r-burns** [comment]
Relevant `config.log` excerpt:

```
configure:4014: checking whether the C compiler works
configure:4036: armv7l-unknown-linux-musleabihf-gcc    conftest.c  >&5
/nix/store/lxzkkscp52ighr658k33wl71749rf8sk-armv7l-unknown-linux-musleabihf-binutils-2.35.1/bin/armv7l-unknown-linux-musleabihf-ld: /nix/store/8939rxc7d16hh25cxbcgym0pk9202s2a-armv7l-unknown-linux-musleabihf-stage-final-gcc-debug-10.2.0/lib/gcc/armv7l-unknown-linux-musleabihf/10.2.0/crtbeginT.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/nix/store/8939rxc7d16hh25cxbcgym0pk9202s2a-armv7l-unknown-linux-musleabihf-stage-final-gcc-debug-10.2.0/lib/gcc/armv7l-unknown-linux-musleabihf/10.2.0/crtbeginT.o:(.init_array+0x0): dangerous relocation: unsupported relocation
/nix/store/8939rxc7d16hh25cxbcgym0pk9202s2a-armv7l-unknown-linux-musleabihf-stage-final-gcc-debug-10.2.0/lib/gcc/armv7l-unknown-linux-musleabihf/10.2.0/crtbeginT.o:(.fini_array+0x0): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
configure:4040: $? = 1
configure:4078: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU Hello"
| #define PACKAGE_TARNAME "hello"
| #define PACKAGE_VERSION "2.10"
| #define PACKAGE_STRING "GNU Hello 2.10"
| #define PACKAGE_BUGREPORT "bug-hello@gnu.org"
| #define PACKAGE_URL "http://www.gnu.org/software/hello/"
| #define PACKAGE "hello"
| #define VERSION "2.10"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4083: error: in `/build/hello-2.10':
configure:4085: error: C compiler cannot create executables
```

**Comment by veprbl** [comment]
We could do something like
```nix
gcc.hardeningUnsupportedFlags = optional (stdenv.hostPlatform.isAarch32 && stdenv.hostPlatform.isStatic) "pie";
```

**Comment by samueldr** [comment]
@veprbl I'm not sure where `hardeningUnsupportedFlags` are defined. I'm not sure where it should be defined in an appropriate manner for all compilers(?). The only current definition is in `pkgs/development/compilers/gcc/4.8/default.nix`. And it does not look like it would be automatically merged if it were to be inherited from a more global location.

**Comment by veprbl** [comment]
@samueldr I agree with your assessment. We would need to apply it to all needed compilers individually.

**Comment by samueldr** [comment]
I don't feel this is the right solution.

Couldn't we work this into the conditional here instead?

https://github.com/NixOS/nixpkgs/pull/101606/files#diff-282a02cc3871874f16401347d8fadc90d59d7ab11f6a99eaa5173c3867e1a160R279

After all, this is where it is being set globally.

**Comment by veprbl** [comment]
@samueldr To my taste, the hardening flag logic doesn't belong to stdenv, but to cc/cc-wrapper. Especially given that we don't do any eval-time validation there.

**Comment by samueldr** [comment]
Though it is not the way it's done currently. The flag logic is in stdenv. I'm not interested into having to refactor something I don't really understand in depth, to get things back to a working state.

https://github.com/NixOS/nixpkgs/blob/a6840c55c2e26075adae7a4a2ef4fa947f1d01b5/pkgs/stdenv/generic/make-derivation.nix#L108

I see that there's already a conditional for musl to add pie, why not fix it there? After all, it's there that it's being globally added.

https://github.com/NixOS/nixpkgs/blob/a6840c55c2e26075adae7a4a2ef4fa947f1d01b5/pkgs/stdenv/generic/make-derivation.nix#L109-L111

**Comment by veprbl** [comment]
@samueldr Speaking of musl, shouldn't pkgsStatic set `isMusl = true`? Could that be the actual issue at hand?

**Comment by samueldr** [comment]
It does already:

```
nix-repl> pkgsStatic.hostPlatform.isMusl
true
```

And the conditional removes "pie" *when it's not musl*, so if I understand things right, it'd be rewritten 

```
stdenv.hostPlatform.isMusl && !(stdenv.hostPlatform.isAarch32 && stdenv.hostPlatform.isStatic)
```

Though, non-static armv7 with musl should be verified too.

**Comment by veprbl** [comment]
@samueldr I got the condition wrong. This looks like a relevant bug
https://bugs.launchpad.net/ubuntu/+source/gcc-4.4/+bug/503448
Your proposed solution appears reasonable to me.

**Comment by samueldr** [comment]
Things may be more subtle than expected.

I hadn't tested in depth with aarch64, only compiled to see if it was compiling still. (I'm working on tests to check things)

`pkgsCross.aarch64-multiplatform.pkgsStatic.hello` when `"pie"` is in the hardening flags, produces dynamic binaries! Furthermore, it segfaults!

Still investigating, will open a PR with the changes that at least works around the regression, and maybe will be the solution.
