### ISSUE TITLE
ecasound fails to compile

### ISSUE THREAD

**Issue by IvarWithoutBones** [NixOS/nixpkgs#114987]
**Describe the bug**
ecasound fails to compile, as it relies on c++11 behaviour.

**To Reproduce**
1. `nix run nixpkgs.ecasound`

**Expected behavior**
ecasound would succesfully compile/be fetched from the binary cache.

**Additional context**
```
builder for '/nix/store/ylikb73bagkx8c4phdmmvclx0jhd1i57-ecasound-2.9.3.drv' failed with exit code 2; last 10 log lines:
  /nix/store/h2kpqraklbg16bkjcd8m41yscbnw7ni5-lilv-0.24.12/include/lilv-0/lilv/lilvmm.hpp:399:31: warning: defaulted and deleted functions only available with '-std=c++11' or '-std=gnu++11'
    399 |   World& operator=(World&&) = delete;
        |                               ^~~~~~
  make[3]: *** [Makefile:968: eca-object-factory.lo] Error 1
  make[3]: Leaving directory '/build/ecasound-2.9.3/libecasound'
  make[2]: *** [Makefile:987: all-recursive] Error 1
  make[2]: Leaving directory '/build/ecasound-2.9.3/libecasound'
  make[1]: *** [Makefile:341: all-recursive] Error 1
  make[1]: Leaving directory '/build/ecasound-2.9.3'
  make: *** [Makefile:270: all] Error 2
[0 built (1 failed), 7 copied (1.4 MiB), 0.4 MiB DL]
```

**Notify maintainers**
@JoshuaFern @FRidh 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre273435.0aeba64fb26"`
 - channels(ivv): `"home-manager, nixpkgs-21.05pre273332.5df05c902cd"`
 - nixpkgs: `/home/ivv/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ecasound
attribute: yuzu-{mainline,ea}
attribute: ssr
```

**Comment by hrhino** [comment]
Not sure what changed but I can run `nix-build --check -A ecasound` on current `master` successfully.

**Comment by FliegendeWurst** [comment]
Build works on 21.11.
