### ISSUE TITLE
vim-addon-local-vimrc does not source anything

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#11502]
It does get instaled; vim autocompletes it's commands, but even when manually calling `:SourceLocalVimrc` it doesn't echo back my test-echo.
When I `:source /path/to/my/.vimrc` it does echo back.

It looks like no one is using it, or at least [no one on github](https://github.com/search?q=vim-addon-local-vimrc+language%3ANix&ref=searchresults&type=Code&utf8=%E2%9C%93).

**Comment by jagajaga** [comment]
cc @MarcWeber

**Comment by MarcWeber** [comment]
http://vim-wiki.mawercer.de/wiki/topic/debugging-viml.html   Thus try :debug SourceLocalVimrc

**Comment by Profpatsch** [comment]
(triage) close? cc @MarcWeber
