### ISSUE TITLE
Unable to build meson-built derivations (nix build permission denied errors)

### ISSUE THREAD

**Issue by jboyens** [NixOS/nixpkgs#115018]
**Describe the bug**
Using nixos-unstable in a flake, a recent rebuild on an un-updated package geoclue2/xdg-desktop-portal-wlr has caused what looks to be a meson bug, but I've been seeing an epidemic of permission denied errors trying to run scripts or other pieces across many derivations in the last week or so.

**To Reproduce**
I do not, unfortunately, have a minimized reproduction. This drv hasn't been updated recently, and it was working properly prior to a nixpkgs update. I plan on trying to bisect the flake to find the breaking commit.

**Expected behavior**
Expected geoclue2/xdg-desktop-portal-wlr to build properly (or at least have a built package on nix cache)

**Screenshots**
```
builder for '/nix/store/37l54ysfjqp8n1kq8lbfrpa1h503afsa-geoclue-2.5.6.drv' failed with exit code 1; last 10 log lines:
  Source dir: /build/source
  Build dir: /build/source/build
  Build type: native build
  Project name: geoclue
  Project version: 2.5.6
  Using 'CC' from environment with value: 'gcc'

  meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 13] Permission denied: '/build/source/build/meson-private/sanitycheckc.exe'.
```

```
builder for '/nix/store/s33fjhbkbd7j6n4y88l2zin74gvj7y6w-xdg-desktop-portal-wlr-0.2.0.drv' failed with exit code 1; last 10 log lines:
  Source dir: /build/source
  Build dir: /build/source/build
  Build type: native build
  Project name: xdg-desktop-portal-wlr
  Project version: 0.2.0
  Using 'CC' from environment with value: 'gcc'

  meson.build:1:0: ERROR: Could not invoke sanity test executable: [Errno 13] Permission denied: '/build/source/build/meson-private/sanitycheckc.exe'.

  A full log can be found at /build/source/build/meson-logs/meson-log.txt
```

**Additional context**
This exact derivation has built in the past and no changes have recently been committed.

**Notify maintainers**
@minijackson  

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0, NixOS, 21.05.20210224.f6b5bfd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/store/zfmxqr26bm36kmk22x2zsk0qbcd559qs-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: geoclue2 xdg-desktop-portal-wlr
# a list of nixos modules affected by the problem
module:
```

**Comment by minijackson** [comment]
Hello! I'm not sure I fully understand your situation. What exactly do you mean by "un-updated"? Are you using `geoclue2` or `xdg-desktop-portal-wlr` through overlay?

Like you said, it sounds to me like a global meson or compiler problem, you probably need meson maintainers instead. Here is the meson sanity check, for reference: https://github.com/mesonbuild/meson/blob/ed252b87e02c39f7ab7ef81c681e3d933b600041/mesonbuild/compilers/c.py#L77-L79

**Comment by jboyens** [comment]
Finally figured this out. NixOS will fail in fun ways if your /tmp dir is set to mount with 'noexec' see https://github.com/NixOS/nix/issues/157, https://github.com/CaptainSpof/dotfiles/commit/ddbfce1ff75ca7ccffb9c7a2e2a3009fdcd916b9, and https://github.com/mesonbuild/meson/issues/5765 and which lead me to the path to get this fixed

**Comment by Lillecarl** [comment]
I've just recently experienced issues like the following, also other issues like

```
Executables created by c compiler gcc are not runnable.
```
I used
```
boot.tmp.useTmpfs
```
with a reboot to resolve my issues, thanks @jboyens 😄
