### ISSUE TITLE
Inaccesible info pages

### ISSUE THREAD

**Issue by oxij** [NixOS/nixpkgs#11500]
`info` pages get less and less accessible with packages getting multiple-outputs and as `closure-size` branch get updated.

E.g. currently I can't access `gcc`'s info pages from NixOS altogether except by directly browsing `/nix/store` because
- `wrapCC` in `master` doesn't export any `doc` outputs, so one can't put that into `buildEnv` in NixOS. So I thought I'd just fix that, but then
- `wrapCC` in `closure-size` splits `info` and `man` from `doc` and exports `man` in the default output, but `info`, again, gets completely ignored.

I propose that
- `wrapCC` should reexport all non-default outputs for a given compiler (no idea how one is to implement that),
- NixOS gets `environment.doc.man` (which `programs.man`, if it were to continue to exist, should imply), `environment.doc.info` (as a bonus `texinfo` becomes optional in NixOS), and, possibly, `environment.doc.share/other` (for those who don't want to see `/run/current-system/sw/share/doc`), that together control what gets imported from `environment.systemPackages` (I can do that).

As the result, everyone get's happy:
- I get to read all the docs in my lovely emacs bunker with no internet access,
- people that refetch their documentation from the internet every time they need it get the chance to tell google everything about what they are going about at the moment while saving their precious 25Mb (or ~700Mb in case you use `ghcWithHoogle` with a ton of stuff) of disk space.

[1] top-level issue #11499

**Comment by oxij** [comment]
By analyzing the blame information off the related files
/cc @vcunat @wkennington @shlevy @edolstra @gridaphobe

**Comment by Profpatsch** [comment]
In my experience the info menus are often structured quite arbitrarily.
Is it possible that we enforce a system-wide scheme for them that makes sense?

**Comment by oxij** [comment]
The structure is defined within the info pages themselves, e.g. `as.info`:

    INFO-DIR-SECTION Software development
    START-INFO-DIR-ENTRY
    * As: (as).                     The GNU assembler.
    * Gas: (as).                    The GNU assembler.
    END-INFO-DIR-ENTRY

All `info` does is merge those from a bunch of files.

We can patch `INFO-DIR-SECTION` lines if we want to. E.g. we can create
a post-install patch phase that rewrites those using information from,
e.g. `meta` of the derivation:

    ...
    mkDerivation {
      ...
      meta = {
        ...
        section = "Compilers";
        ...
      };
    }

Personally, I just search and navigate using index, but it can be done,
yes.

**Comment by vcunat** [comment]
>  wrapCC should reexport all non-default outputs for a given compiler (no idea how one is to implement that)

:+1: It seems relatively easy to me, but I'm very scarce on time ATM.

> NixOS gets environment.doc.man

There are some WIPs on that, e.g. `outputsToLink`; also /cc @lethalman. I think the whole thing about *what outputs to install by default* needs some more careful thinking to get a good design, including also `nix-env`, etc. Discover-ability also seems worse after splitting.

Improving the structure of `*.info` files seems a well-separated issue.

**Comment by vcunat** [comment]
> By analyzing the blame information off the related files

:-D My head was working for minutes on how the bot could've deduced whom to ping when there's no code attached.

**Comment by Profpatsch** [comment]
(triage) has this been improved?

**Comment by oxij** [comment]
First proposal got implemented by #35071 and is merged. #38114 implements the second one, currently pending.

**Comment by Profpatsch** [comment]
They are both merged, really great work!

I’ll close this issue.
