### ISSUE TITLE
Nix-shell as shebang for ghcWithPackages

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#11514]
Hello!
I'm trying to use nix-shell as an interpreter.
Running this
```haskell
#! /usr/bin/env nix-shell
#! nix-shell -i runghc -p haskellPackages.scotty haskellPackages.blaze-html

{-# LANGUAGE OverloadedStrings #-}

import Web.Scotty

import qualified Text.Blaze.Html5 as H
import Text.Blaze.Html5 (toHtml, Html)
import Text.Blaze.Html.Renderer.Text (renderHtml)

greet :: String -> Html
greet user = H.html $ do
  H.head $
    H.title "Welcome!"
  H.body $ do
    H.h1 "Greetings!"
    H.p ("Hello " >> toHtml user >> "!")

app = do
  get "/" $
    text "Home Page"

  get "/greet/:name" $ do
    name <- param "name"
    html $ renderHtml (greet name)

main :: IO ()
main = scotty 8000 app
```
And getting `Could not find module 'Web.Scotty'`.
Ok, I'm trying to run with
```haskell
#! /usr/bin/env nix-shell
#! nix-shell -i runghc -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [scotty blaze-html])" 

{-# LANGUAGE OverloadedStrings #-}

import Web.Scotty
.....
```
And getting `build input haskellPackages.ghcWithPackages) does not exist`. 
What do I need to do to run my program as `./foo.hs`?

**Comment by jagajaga** [comment]
cc @peti

**Comment by jagajaga** [comment]
cc @edolstra cc @puffnfresh

**Comment by puffnfresh** [comment]
I'd say this is a bug in Nix. You can see that nix-build just does a split on spaces, so you can't supply any parameters which need to be quoted:

https://github.com/NixOS/nix/blob/master/scripts/nix-build.in#L59

**Comment by puffnfresh** [comment]
@jagajaga got a fix for you at https://github.com/NixOS/nix/pull/732.

**Comment by jagajaga** [comment]
@puffnfresh thank you. Waiting for merging.

**Comment by rnhmjoj** [comment]
@jagajaga you may be interested in [this](https://github.com/bennofs/nix-script).

**Comment by dezgeg** [comment]
This can be closed now, right?

**Comment by puffnfresh** [comment]
@dezgeg yes, it's in 1.11.2!
