### ISSUE TITLE
gnunet-gtk fail to build

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#115112]
**Describe the bug**
```
[davidak@gaming:~]$ nix run nixpkgs.gnunet-gtk -c gnunet-gtk
builder for '/nix/store/w1a305jwbbnn2h723w0hwl1xlflhg2w9-gnunet-gtk-0.13.1.drv' failed with exit code 1; last 10 log lines:
  checking gnutls/abstract.h presence... yes
  checking for gnutls/abstract.h... yes
  checking for gnutls_pubkey_import in -lgnutls... yes
  checking for GNUnet core... --with-gnunet not specified
  checking for gnunetutil >= 0.9.0... yes
  checking GNUNET_CFLAGS... -I/nix/store/aawda90f2iv5x0dxp3ag74i37bclwc80-gnunet-0.14.0/include
  checking GNUNET_LIBS... -L/nix/store/aawda90f2iv5x0dxp3ag74i37bclwc80-gnunet-0.14.0/lib -lgnunetutil
  checking for gnunet/gnunet_conversation_service.h... no
  checking for gnunet/gnunet_fs_service.h... no
  configure: error: compiling gnunet-gtk requires GNUnet core headers
[0 built (1 failed), 6 copied (33.3 MiB), 9.2 MiB DL]
error: build of '/nix/store/w1a305jwbbnn2h723w0hwl1xlflhg2w9-gnunet-gtk-0.13.1.drv' failed
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Notify maintainers**
@pstn and @jonringer edited it last

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1, NixOS, 21.05pre273435.0aeba64fb26 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-21.05pre273435.0aeba64fb26, nixos-hardware, nixos-unstable-21.05pre273435.0aeba64fb26"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
I really have no idea, `gnunet` contains it, even bumping gnunet-gtk to be the same release version still doesn't fix it.

**Comment by pstn** [comment]
Have you tried applying https://github.com/NixOS/nixpkgs/pull/110606?
