### ISSUE TITLE
 package request: psst - "Native Spotify client for the Gnome desktop"

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#115155]
**Project description**

>Fast and multi-platform Spotify client with native GUI

>Fast Spotify client with native GUI, without Electron, built in Rust. Very early in development, lacking in features, stability, and general user experience. It is being tested only on Mac so far, but aims for full Windows and Linux support. Contributions welcome!

**Metadata**

* homepage URL: https://github.com/jpochyla/psst
* source URL: https://github.com/jpochyla/psst
* license: **mit**
* platforms: **darwin, linux**

**Comment by jtojnar** [comment]
Another: https://github.com/NixOS/nixpkgs/issues/114784

**Comment by figsoda** [comment]
psst is now in nixpkgs
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/psst/default.nix
