### ISSUE TITLE
Firefox (and maybe other GTK applications) file dialog does not correctly conform to DPI scaling

### ISSUE THREAD

**Issue by winterqt** [NixOS/nixpkgs#115144]
**Describe the bug**
Firefox (and maybe other applications) file dialog does not correctly conform to DPI scaling.

**To Reproduce**
1. Set DPI to `144` via either Xresources or `services.xserver.dpi`.
2. Open Firefox, observe all UI components render at an adequate size and scale.
3. Attempt to use the file picker

**Expected behavior**
Notice the dialog is zoomed in to the point of not being able to use it, and not a small window as it is with no DPI scaling override.

**Screenshots**
![2021-03-04-163912_2256x1504_scrot](https://user-images.githubusercontent.com/78392041/110034256-3954c800-7d08-11eb-8efb-affce6255f59.png)

**Additional context**
I've tried playing with the `GDK_SCALE` and `GDK_DPI_SCALE` environment variables, as well as setting `Xft/DPI` to `(current DPI) * 1024` via Xsettings as per the Debian wiki.

I have not had this issue on any other distributions, specifically Arch.

**Notify maintainers**
@lovesegfault 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.2, NixOS, 21.05.20210228.0aeba64 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by winterqt** [comment]
I'm able to reproduce this with other GTK applications, so I'll ping the GTK maintainers (if this is a nonissue let me know, but I can't reproduce this on other distributions..)

@7c6f434c @lethalman @worldofpeace

**Comment by 7c6f434c** [comment]
I have no idea, I do not run NixOS (and that I am still listed in GTK maintainers is a bug, in a sense), does the problem stay for applications run after `xrandr --dpi 144` ?

**Comment by winterqt** [comment]
@7c6f434c I appreciate you taking the time to respond anyways.

> does the problem stay for applications run after `xrandr --dpi 144`?

It does, sadly.

**Comment by 7c6f434c** [comment]
Hm. I have no idea if `xrdb -query` should say anything, and also — does, say, `gvim` appearance depend on the DPI you set via xrandr? (I am not sure if you can easily spawn a second X session with something minimal like JWM and also test there; I stopped using NixOS specifically because keeping up with the proper way of spawning second X session after systemd update was more work than writing minimal boot scripts)

**Comment by winterqt** [comment]
As I noted in the issue description, every application renders completely fine *except* for the file picker dialog used in GTK applications. Literally everything else! Which is why this is so confusing...

**Comment by 7c6f434c** [comment]
Hm, have you checked whether this is theme-dependent?

**Comment by winterqt** [comment]
Not sure, I've never really dabbled in GTK themes... so not really sure how I'd debug that. I'm sure there's an option in home-manager or nixpkgs to switch themes, maybe?

**Comment by 7c6f434c** [comment]
Wait, you want to say that the dark theme is the default?

**Comment by winterqt** [comment]
This is the default dark theme as far as I know, yes. I enabled it by setting `gtk-application-prefer-dark-theme` to `true` in my GTK `settings.ini`.

**Comment by 7c6f434c** [comment]
>This is the default dark theme as far as I know, yes. I enabled it by setting `gtk-application-prefer-dark-theme` to `true` in my GTK `settings.ini`.

And does the effect persist with the true default theme (the light one)? I have no clue, but that feels like a thing to triage.

**Comment by winterqt** [comment]
The effect does persist, yes.

**Comment by 7c6f434c** [comment]
Hm. Just to make sure, what about any other GTK application? Gnome3 gedit, for example? Firefox might be a little different or something.

**Comment by winterqt** [comment]
I run into the same issue with VSCode, yeah.

**Comment by 7c6f434c** [comment]
OK, so we are talking about Firefox and Chromium… maybe something actually native (and maybe even coming from Gnome) would be a good check (both for the normal way of setting DPI and xrandr, I guess).

**Comment by winterqt** [comment]
The issue persists when using `gedit`.

**Comment by 7c6f434c** [comment]
Thanks!. Next step at triaging I can imagine is probably finding something that uses the default GTK ColorChooserDialog or FontChooserDialog and checking if text there is wrong size… (presumably message dialogs are fine or you would have noticed that by now)

**Comment by winterqt** [comment]
I'm unsure if this is still an issue, as I'm no longer running NixOS, so I'll close it for the time being.
