### ISSUE TITLE
networkmanager is outdated

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#115137]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: networkmanager

current version: 1.26
desired version: 1.30

###### Notify maintainers

maintainers: @Phreedom @domenkozar @worldofpeace @obadz 

###### Note for maintainers

Nothing notable in changelog: https://github.com/NetworkManager/NetworkManager/blob/master/NEWS

Motivation: https://www.xmodulo.com/wireguard-vpn-network-manager-gui.html says wireguard support comes with 1.26.2

Please tag this issue in your PR.

**Comment by worldofpeace** [comment]
Yep, will try to get this and also do minor updates to stable.
