### ISSUE TITLE
Package request: pantheon-tweaks

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#115222]
**Project description**
Pantheon Tweaks is a Switchboard plug allowing users to somewhat tweak Pantheon (elementary OS's DE) settings of the more hidden kind, not normally available from Switchboard. As NixOS has Pantheon packaged, it might be of use in Nixpkgs.

**Metadata**

* homepage URL: https://github.com/pantheon-tweaks/pantheon-tweaks/
* source URL: https://github.com/pantheon-tweaks/pantheon-tweaks/
* license: `stdenv.lib.meta.licenses.gpl3Only`
* platforms: same as Pantheon

Depending on Pantheon version currently in Nixpkgs, the predecessor elementary-tweaks, also GPLv3, might be of more use: https://github.com/elementary-tweaks/elementary-tweaks

**Comment by worldofpeace** [comment]
`elementary tweaks` is archived, and I think it should be totally broken.

As I maintain Pantheon in NixOS, I approve of this being packaged in the future, but not `elementary-tweaks`, because it's archived and IIRC I denied that in the past.

**Comment by kisik21** [comment]
Then we should probably do it once Pantheon in NixOS advances to whatever version elementary OS 6 Odin will have - this'll probably happen once elementary OS 6 will get released.

**Comment by worldofpeace** [comment]
> Then we should probably do it once Pantheon in NixOS advances to whatever version elementary OS 6 Odin will have - this'll probably happen once elementary OS 6 will get released.

Ah yes, the repo says "Pantheon Tweaks is currently only supported on elementary OS Odin" :+1:

**Comment by bobby285271** [comment]
@davidak @kisik21 Did some initial work for this (https://github.com/bobby285271/nixpkgs/commit/eed53474a2a9b6d7ab4f67edaad98fc850137cb4), would you like to try that?

Will need Pantheon 6 and following line in your NixOS configuration file:

```nix
services.xserver.desktopManager.pantheon.extraSwitchboardPlugs = [ pkgs.pantheon.pantheon-tweaks ];
```
