### ISSUE TITLE
Add an option to disable imagick in NextCloud

### ISSUE THREAD

**Issue by BBBSnowball** [NixOS/nixpkgs#115279]
There is [some discussion](https://github.com/nextcloud/server/issues/13099) about the use of imagemagick in NextCloud due to [past CVEs](https://www.cvedetails.com/vulnerability-list.php?vendor_id=1749&cvssscoremin=9). Admins may want to disable it unless they are certain that users won't upload untrusted files (which can easily happen by accident if folder sync is active).

NextCloud is only passing certain file types to imagemagick but it is doing so based on the file extension. Therefore, an attacker can pass any file type to imagemagick. I have tested this with a PNM image (not supported by NextCloud) that I have renamed to `tux.heif`. `tux.pnm` doesn't get a preview image but `tux.heif` does, i.e. NextCloud thinks it is HEIF and passes it to ImageMagick, which processes it as PNM.

There are several ways to disable imagick:
1. Disable `enable_previews` in the NextCloud config. This will not only disable imagick but also previews for PNG and JPEG (which do not use imagick).
2. Set `enabledPreviewProviders`in the NextCloud config. This may need manual adjustment after a NextCloud update.
3. Disable the `imagick` extension for PHP. This also disables it for NextCloud plugins.

Option 1 and 2 can already be used by an admin if the drawbacks are acceptable. However, I think 3 is the best option in most cases. [This commit](https://github.com/NixOS/nixpkgs/commit/0ff63a3fa6f5a3da5bc7d85f6fe0cc5f87df94b3) has added options that disable the other PHP extensions that used to be added by default. I think we should do the same for imagick.

If imagick is disabled, NextCloud will automatically disable the preview generators that need it. It will also show a warning about that (which is subject to debate in the issue linked above) and there may be some implications for the themes app (which I don't use). Therefore, I think we should keep imagick enabled by default and leave the decision to the admin.

We could also add a suitable policy for ImageMagick and thereby disable any file formats or features that are considered insecure. I don't think I could write such a policy and be sure that it is secure (or even "secure enough"). In addition, we will have to keep it up-to-date with newer versions and CVEs. That is why I recommend that we only add a simple off switch.

The above information is based on NextCloud 20. I will wait until [this commit](https://github.com/NixOS/nixpkgs/pull/115089) and NextCloud 21 have landed in nixos-unstable (and on my server) and then test again and create a PR if there is any interest in having this upstream.

**Comment by Ma27** [comment]
Ouch, decisions based purely on a file ext is a behavior that sounds pretty broken to me :/ 

Optiobally disabling imagemagick and adjusting the config accordingly sounds reasonable to me, so feel free to file a PR. You can ping me for a review or if you need assistance with modifying the module :)

**Comment by BBBSnowball** [comment]
> Ouch, decisions based purely on a file ext is a behavior that sounds pretty broken to me :/

It's ok for what they do with it. It won't do double duty as a mitigation but I guess that was never intended.

> Optiobally disabling imagemagick and adjusting the config accordingly sounds reasonable to me, so feel free to file a PR. You can ping me for a review or if you need assistance with modifying the module :)

Thanks. Any suggestions on a name for the new option? Simply `services.nextcloud.imagemagick` ?

Should I add any tests for that? The existing tests only test three different configurations so adding one just for imagick seems like overkill. It should be quite easy though. If we want to test that previews actually aren't generated... Well, that's a different story. We would have to automate the web interface, for that. I think the existing tests are only testing the service, CLI and WebDAV.

**Comment by Ma27** [comment]
> Thanks. Any suggestions on a name for the new option? Simply services.nextcloud.imagemagick ?

As imagemagick enabled will remain the default, I'd suggest `services.nextcloud.disableImagemagick`.

> The existing tests only test three different configurations so adding one just for imagick seems like overkill. It should be quite easy though

Yes, adding a fourth VM test just for imagemagick is indeed an overkill IMHO since those tend to be fairly expensive. I'd suggest to write a testcase in `nextcloud/basic.nix`, other integrations such as `davfs` are also tested there.

> Well, that's a different story. We would have to automate the web interface, for that. I think the existing tests are only testing the service, CLI and WebDAV.

Right that could be a non-trivial thing to solve. Maybe check if there's a REST API or a way to implement this with the CLI of `nextcloud-client`. But I don't think it'd be worth spending too much time on this if there's no reasonable way to test :)

**Comment by BBBSnowball** [comment]
I think we still want to test the default option in `basic.nix` so we will need a second configuration that disables imagick. We don't have to start that VM if we only want to check whether imagick is in its closure. As there isn't any test helper for that, we probably don't want to do that though ;-)

see https://github.com/NixOS/nixpkgs/pull/115372/commits/d83a43a396c7ec5ac2cd633262648306e25c6789

Unfortunately, qemu on ARM big.little is too unreliable for the automatic tests because qemu crashes when started on one of the little cores (i.e. 4 out of 6 times). I have done some interactive testing of the above commit but not an automated run. I will have to find some system that is not ARM, not high-security, not already virtualized...

**Comment by BBBSnowball** [comment]
Qemu/KVM does work if a kernel build or stress-ng is hogging the big cores :)

@Ma27 https://github.com/NixOS/nixpkgs/pull/115372 is ready for review.
