### ISSUE TITLE
[20.09] dependencies of fetchurl are not in the binary cache, causing a lengthy rebuild of coreutils, curl etc

### ISSUE THREAD

**Issue by mebubo** [NixOS/nixpkgs#115299]
The nixos-20.09 channel is currently at https://github.com/NixOS/nixpkgs/commit/1ac507ba981970c8e864624542e31eb1f4049751

With this state of the channel, updating a system with `systemPackages` containing e.g. `google-chrome-stable` (relies on fetchurl to retrieve the .deb file) triggers the following rebuild:

```
these derivations will be built:
  /nix/store/83vicchl2h6by2n0wi1sf6r7ksiysjjv-coreutils-8.31.drv
  /nix/store/dvn13hwx2hxp12gy248h5517wvqyfiz6-openssl-1.1.1j.drv
  /nix/store/4m8d3rx5vmmwsrj4jap05akgny0710fx-nghttp2-1.41.0.drv
  /nix/store/gw92af1pvs18df8cyvi435x4bjlqi3kb-libkrb5-1.18.drv
  /nix/store/jv1wmaarj80hr073hd7x806381gds41z-libssh2-1.9.0.drv
  /nix/store/rx6sirqy83si88x5w9x14fakpv2kmdfa-curl-7.74.0.drv
  /nix/store/azmnb7qc4g8vwg0bpni2mk7fshnqzfhh-example.com.drv
building '/nix/store/83vicchl2h6by2n0wi1sf6r7ksiysjjv-coreutils-8.31.drv'...
[...]
```

Building the above derivations takes a substantial amount of time on slow machines.

I have never observed this in the past with the nixos-20.09 channel and the same system config. (In general, system rebuilds tracking the channel almost never trigger lengthy rebuilds with this config, that's why I thought it may deserve filing an issue.)

Here is a minimal example with a dummy derivation; leads to the same exact rebuild as above:

```
let

    nixpkgs = builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/1ac507ba981970c8e864624542e31eb1f4049751.tar.gz";
        sha256 = "1r05lrkvmjhygpmxj4h0rmvz53c7zmy5lff5az09bi1nwqm1xr42";
    };

    pkgs = import nixpkgs {};

in

    pkgs.fetchurl {
        url = "https://example.com";
        sha256 = "1111111111111111111111111111111111111111111111111111";
    }
```

Edit: rearranged for clarity.
Edit2: reword.

**Comment by roberth** [comment]
On `x86_64-linux` I'm getting a different hash for coreutils.

```
nix-instantiate channel:nixos-unstable -A coreutils
unpacking 'https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz'...
/nix/store/151ql4p9mankmwc618sgrv45s8gyyw7y-coreutils-8.32.drv
```

This derivation is in the cache.

Which system type do you use and did you configure any overlays or package overrides?

**Comment by maralorn** [comment]
I have the same issue on x86_64-linux.

**Comment by maralorn** [comment]
@roberth It's on nixos-20.09. You apparently tested unstable.

**Comment by mebubo** [comment]
@roberth FWIW it's not the normal `coreutils`, but rather this one, overridden just to bootstrap `fetchurl` (as far as I understand):

https://github.com/NixOS/nixpkgs/blob/f39798eb72999d7533032bf1b478ed3db845b1d7/pkgs/top-level/all-packages.nix#L432

**Comment by roberth** [comment]
Oh that makes a lot of sense actually. Fixed-output derivations are only built when the output isn't already available, so when the fetcher changes, there's no need to build it, until a truly new hash needs to be downloaded.
New downloads are fetched all the time, so normally it's not a problem, but release-20.09 doesn't get quite as much changes so it can remain unbuilt for a longer time.

This problem can be solved by turning the fetchurl dependencies into proper top-level attributes. Probably a good idea to add a comment then, explaining their purpose, presumably to reduce the number of downloads in the closure of the fetcher to avoid infinite recursion.

**Comment by roberth** [comment]
On second thought, it may be easier to maintain when we create a new attribute with something like
```
fetchurlDependencies = (fetchurl { /* bogus values */ }).overrideDerivation(o: {
  # overrides to turn it back into a regular derivation
})
```

that way it captures all dependencies by default.

**Comment by Atemu** [comment]
20.09 has been EOL for a long time, create a new issue if this is still relevant.
