### ISSUE TITLE
Nginx is not serving files

### ISSUE THREAD

**Issue by mrkkrp** [NixOS/nixpkgs#115208]
**Describe the bug / To Reproduce**

At 891f607d5301d6730cb1f9dcf3618bcb1ab7f10e.

With this configuration:

```nix
{ config, pkgs, ... }:
{
  services.nginx.virtualHosts = {
    localhost = {
       listen = [
         {
           addr = "localhost";
           port = 5000;
         }
       ];
       locations."/" = {
         root = "/some/path";
         index = "posts.html index.htm";
         extraConfig = "error_page 404 = /404.html;";
       };
    };
  };
  services.nginx.user = "mark"; # Replace accordingly, I just use my normal user
  services.nginx.enable = true;
  services.nginx.logError = "/var/log/nginx/error.log debug";
}
```

With `/some/path` permissions set to 755, with `posts.html` existing and also set to 755, with every file and the folder owned by the user specified in `services.nginx.user`. Nginx fails to serve the file:

```
2021/03/04 22:26:21 [error] 29456#29456: *3 "/some/path/posts.html" is forbidden (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "127.0.0.1:5000"
2021/03/04 22:26:21 [error] 29456#29456: *3 open() "/some/path/favicon.ico" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1:5000", referrer: "http://127.0.0.1:5000/"
```

In a browser one can see `403 Forbidden`.

Now, you might be thinking, "So, what? the solution is probably simple and has nothing to do with Nixpkgs." The thing is, this exact configuration totally used to work before. I think the switch to 891f607d5301d6730cb1f9dcf3618bcb1ab7f10e broke it, but it's been a while since I checked this local server. Online, one can find answers related to SELinux, but SELinux, as far as I can tell, is not a thing (yet?) on NixOS, so those explanations do not apply.

**Expected behavior**

It would be nice if Nginx worked.

**Screenshots**

![403 Forbidden](https://user-images.githubusercontent.com/8165792/110168088-f887ac80-7df6-11eb-9e8a-26d5505da1bf.png)

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.92, NixOS, 21.03.git.891f607d530 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - nixpkgs: `/home/mark/nixpkgs`

**Comment by Patagonicus** [comment]
I just tried this in a VM with a user called "nixos". With this setup:

```
sudo install -d -m 755 -o nixos -g users /some /some/path
echo '<html><body>It works!</body></html>' | sudo tee /some/path/posts.html
sudo chown nixos:users /some/path/posts.html
```

I'm unable to reproduce this, nginx happily serves the file:

```
nixos@nixos ~> curl -v http://localhost:5000/posts.html
*   Trying ::1:5000...
* Connected to localhost (::1) port 5000 (#0)
> GET /posts.html HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Server: nginx
< Date: Sat, 06 Mar 2021 10:01:30 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
< 
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host localhost left intact
```

However, if I remove `nixos` access to `/some` I can reproduce the permission denied:

```
nixos@nixos ~> sudo chown root:root /some; sudo chmod 700 /some
nixos@nixos ~> curl -v http://localhost:5000/posts.html
*   Trying ::1:5000...
* Connected to localhost (::1) port 5000 (#0)
> GET /posts.html HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Server: nginx
< Date: Sat, 06 Mar 2021 10:01:30 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
< 
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host localhost left intact
```

Nginx needs the execute bit for all directories starting from / to be able to serve a file, see [this StackExchange post for example](https://serverfault.com/questions/748561/nginx-doesnt-have-permission-to-access-files-with-the-same-ownership/748562). Does your user have the right permissions for all directories in the path to the file you're trying to serve?

**Comment by mrkkrp** [comment]
I just checked. I wish it were so simple. I set all folders to `777` and the problem still persists. They are all owned by the user `services.nginx.user`. Moreover, this used to work and there were no changes of any sort to the filesystem that could affect anything. I'm trying to figure out whether I have added something that might interfere with Nginx...

**Comment by Patagonicus** [comment]
Hmm. Do you have older system generations still available that you could try? I currently see three possible causes: 1. a change in nixpkgs 2. a change in your configuration.nix or 3. something in the mutable files on your filesystem.

We know that it does not work with current nixpkgs and your current configuration. If you have old generations and it does not work there either, it would strongly point to something on your filesystem. If it does work with old generations, that means that (current nixpkgs + current configuration) is broken, but (old nixpkgs + old configuration) works.

The next step then would be to build your current configuration with old nixpkgs. Whether that fails or not would tell you if it's a change in nixpkgs or in your configuration is the problem. In either case we could narrow it down further (either by bisecting nixpkgs or by diffing your old and new systems to see the changes in the config).

**Comment by mrkkrp** [comment]
I re-built my configuration (with minimal adjustments because of renamed attributes and such) with 32b46dd897ab2143a609988a04d87452f0bbef59 and it works fine. I believe that whatever broke it happened between 32b46dd897ab2143a609988a04d87452f0bbef59 and ae47c79479a086e96e2977c61e538881913c0c08.

**Comment by mrkkrp** [comment]
Created a diff between those commits.

Maybe this causes it?

```
+     <para>
+       Nginx is also started with the systemd option <literal>ProtectHome = mkDefault true;</literal>
+       which forbids it to read anything from <literal>/home</literal>, <literal>/root</literal>
+       and <literal>/run/user</literal> (see
+       <link xlink:href="https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ProtectHome=">ProtectHome docs</link>
+       for details).
+       If you require serving files from home directories, you may choose to set e.g.
+<programlisting>
+systemd.services.nginx.serviceConfig.ProtectHome = "read-only";
+</programlisting>
+     </para>
```

**Comment by mrkkrp** [comment]
Yeah, that's it. So for posterity, this is how you fix it:

```nix
systemd.services.nginx.serviceConfig.ProtectHome = "read-only";
```

**Comment by Patagonicus** [comment]
Was just about to post that I can now replicate the problem by using `/home/nixos` instead of `/some/path`. Incidentally I have machines that run into the same problem, they are just so rarely used that I hadn't noticed yet
