### ISSUE TITLE
Infinite recursion in targetPackages.stdenv for LLVM cross targets

### ISSUE THREAD

**Issue by ehmry** [NixOS/nixpkgs#115348]
**Describe the bug**

Cannot peer into `targetPackages.stdenv` when cross-compiling from a GCC build platfrom to an LLVM platform. 
Or I'm doing something wrong.

**To Reproduce**
```
let
  system = builtins.currentSystem;
  pkgs = import ./. {
    localSystem = {
      inherit system;
      useLLVM = false;
    };
    crossSystem = {
      inherit system;
      useLLVM = true;
    };
  };
in pkgs.targetPackages.stdenv.cc
```

**Additional context**
Would be nice to inspect targetPackages.stdenv to build a compiler wrapper for Nim - #115195

**Notify maintainers**
@Ericson2314

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.7.19, NixOS, 21.03.20210126.79e5761 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`

**Comment by ehmry** [comment]
FWIW I was able to work around this by late-binding the toolchain at build-time.

**Comment by arcnmx** [comment]
#119068 fixes the infinite recursion, though it's worth noting I had to modify the example:

```nix
(import ./. {
    localSystem = {
      system = builtins.currentSystem;
      useLLVM = false;
    };
    crossSystem = {
      system = builtins.currentSystem;
      useLLVM = true;
    };
    # because when it uses llvm 7 by default it's broken for some reason?
    crossOverlays = [ (self: super: { stdenv = super.overrideCC super.stdenv self.llvmPackages_10.lldClang; }) ];
}).stdenv.cc
```
