### ISSUE TITLE
[20.09] google-chrome-89.0.4389.72 fails to start because libxshmfence is not found

### ISSUE THREAD

**Issue by Patagonicus** [NixOS/nixpkgs#115387]
**Describe the bug**
`google-chrome-stable` from the 20.09 channel fails to start:

```
./result/bin/google-chrome-stable --version
/nix/store/5g9v3lvi4n811xsjhizzplgz0vc53ki2-google-chrome-89.0.4389.72/share/google/chrome/google-chrome: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
```

**To Reproduce**
Check out fca3d68619f8da6a15083f114c98f76150f5cba6 and run `nix-build . -A google-chrome && ./result/bin/google-chrome-stable`

**Expected behavior**
Chrome starts and shows a window instead of crashing.

**Screenshots**
NA

**Additional context**
Bisecting has shown that fca3d68619f8da6a15083f114c98f76150f5cba6 is the commit that broke it. That commit is a chromium version upgrade.

At 37b47da04ca (the commit my 20.09 channel synced to last night) google-chrome is still broken, but chromium works. I did not try chromium at the commit above since it wants to build quite a few derivations - I suspect it'll work there as well.

It looks like 351f3c043d80009569d646a332025f7870b11cf3 added libxshmfence to chromium's common at the end of last year to "fix the build". My guess is that google-chrome now has that dependency as well.

**Notify maintainers**

@primeos 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.3376.1ac507ba981 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3383.37b47da04ca"`
 - channels(philipp): `"nixos-20.03-20.03.3325.462c6fe4b11, home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: google-chrome
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment]
Thanks! I've pushed e0903936cb04ef00ec8a23677b131d4fe9c4895c to fix this (forgot to backport that commit).
I did update my script for backporting Chromium commits to consider the ones for Google Chrome as well so that should hopefully help avoiding such issues in the future.
