### ISSUE TITLE
The boot.loader.grub.zfsSupport property is ignored

### ISSUE THREAD

**Issue by msteen** [NixOS/nixpkgs#11533]
When I updated my nixpkgs repo to the latest version of the 15.09 channel, I saw that zfs-user was being build even though I do not use ZFS. I checked all-packages.nix and grub.nix and found the defaults no longer match the assumptions made in grub.nix.

Currently all-packages.nix contains the following:

```
grub2 = grub2_full;

grub2_full = callPackage ../tools/misc/grub/2.0x.nix { };

grub2_efi = grub2_full.override {
  efiSupport = true;
};

grub2_light = grub2_full.override {
  zfsSupport = false;
};
```

While grub.nix still has the following:

```
realGrub = if cfg.version == 1 then pkgs.grub
  else if cfg.zfsSupport then pkgs.grub2.override { zfsSupport = true; }
  else if cfg.enableTrustedBoot then pkgs.trustedGrub
         else pkgs.grub2;
```

Since `pkgs.grub2` is defined as `grub2_full`, which has `zfsSupport ? true`, there currently is no difference between `pkgs.grub2.override { zfsSupport = true; }` and `pkgs.grub2`. I do not see the need for `grub_full`, `grub_efi` and `grub_light`. Would it not be better to keep things configurable the way they are using options such as `boot.loader.grub.zfsSupport`?

**Comment by wkennington** [comment]
They are defined this way to ensure zfs support is included when running
grub with zfs but not necessarily building with it at the top level(even
though in this instance we are building with it).

**Comment by wkennington** [comment]
You need grub2_efi if you want to support efi systems and have hydra build
the binary for you. Unfortunately the way to the grub build works,
grub2_efi is mutually exclusive from grub2_full in that it only has efi
binaries while grub2_full has bios compatible binaries.

**Comment by msteen** [comment]
The reason to have those different packages is to have the binaries build for you by Hydra, that answers my question why there are three versions of grub in all-packages.nix, but it does not address the issue. Or I must be misunderstanding something about your first comment. And why not `grub2` (with `zfsSupport ? false`) and `grub2_zfs`, instead of `grub_full` and `grub_light`? Should grub.nix not be changed e.g. like this:

    realGrub = if cfg.version == 1 then pkgs.grub
      else if cfg.zfsSupport then pkgs.grub2_full
      else if cfg.enableTrustedBoot then pkgs.trustedGrub
             else pkgs.grub2_light;

**Comment by wkennington** [comment]
That doesn't really make a difference as this function is used not only for
grub2_full but also applies to grub2_efi to make sure the efi binaries also
support zfs. This is much cleaner than having a derivation for every single
permutation listed in the NixOS module.

**Comment by msteen** [comment]
I understand that you would not want to have a version for each permutation, but there are 3 versions, of which only two are available through the NixOS module options. Or how can I configure my NixOS such that `pkgs.grub2_light` is being used?

**Comment by msteen** [comment]
Or to put it another way, what is the use of `boot.loader.grub.zfsSupport` if it is being ignored anyway? Since I am currently getting ZFS support, while I have no need for it.

**Comment by Profpatsch** [comment]
(triage) still an issue?
