### ISSUE TITLE
where did you get this zile versio from?

### ISSUE THREAD

**Issue by soloturn** [NixOS/nixpkgs#115324]
the file or version you are referencing,   name = "zile-2.6.0.90";  is not known on the gnu source server. where is this from?

https://github.com/NixOS/nixpkgs/blob/247c6f4ce39c14c5845467d93c0cd869a8987572/pkgs/applications/editors/zile/default.nix#L4

**Comment by roberth** [comment]
@austinbutler @pSub zile sources seem to be unretrievable.

**Comment by austinbutler** [comment]
At the time that was the latest version [at the source](https://ftp.gnu.org/gnu/zile/). Now that version has apparently moved to [an alpha server](https://alpha.gnu.org/gnu/zile/).
