### ISSUE TITLE
Audio muted every time the headphone jack is plugged in with the Mac Mini 7,1

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nixpkgs#11540]
I installed NixOS unstable (16.03) on my Mac Mini 7,1 and have the following probem with it.

First I thought my audio output jack isn't working at all, after some fiddling around I realized it must be a software problem. (Intel Corporation Haswell-ULT HD Audio Controller [8086:0a0c])
If I fully pushed my headphones into the jack I didn't hear any sound at all. 
By coincidence I discovered that if the jack is not fully inserted I get the desired output on my headphones.
After some more fiddling around with the alsamixer I saw that whenever I fully insert my headphones, the Speaker and the Master of my PCH device and the master of the PulseAudio will be automatically muted and that there is no audio on my headphones with muted Speaker.
I got it working by disabling PulseAudio (don't know if that is needed at all), setting the volume level of my Speaker to 0 (So nothing comes out of my internal speaker in addition to my headphones) and unmuting all others and setting the volume levels appropriately.
The remaining issue I have is, that every time I unplug and plug in again, either the Speaker or the headphones are muted and Master is muted too or set to 0 volume.
I also disabled Auto-Mute but that doesn't seem to change aynthing.

**Comment by ThomasMader** [comment]
I should add that my WiFi may need the following in the /etc/nixos/configuration.nix:

  networking.networkmanager.enable = lib.mkForce true;
  networking.wireless.enable = lib.mkForce false;

Disabling pulseaudio in the configuration:

  hardware = {
        pulseaudio.enable = false;
  };

**Comment by joachifm** [comment]
Hi, would you please turn this into separate, specific issues? As it is, I don't see what to do with this.

**Comment by ThomasMader** [comment]
Created new issue #15162 to separate the missing audio driver problem from this one.

**Comment by vcunat** [comment]
AFAIK pulseaudio has separate volume control for the case when headphones are plugged in (by default, and I do find that very useful). Isn't it just a misunderstanding? I'd assume you can unmute or increase volume after you plugged them in.

**Comment by zimbatm** [comment]
@ThomasMader like @vcunat said, pulseaudio uses different sound profiles whenever the headphone is plugged-in or not. It's very useful because most of the time you don't want to have the same volume on the loud speaker or banging in your ears. Sorry to ask but did you try to un-mute and push the volume up once the headphones where plugged?

Things that might help (with pulseaudio):
* output of `pactl info`
* right-click on the pa-applet to see what output is selected before/after plugging the jack

**Comment by ThomasMader** [comment]
@zimbatm, @vcunat: You might be right about the separate volume controls but for me it seems to be the other way around.

I now check the state of the audio output via the pa-applet and when nothing is plugged in, the headphones are selected as the audio output device.
As soon as I plug something in the internal Speaker is selected.
So it is exactly the other way around.
I just triggered a system update to 16.03. Will try again with this last release and report back.

**Comment by ThomasMader** [comment]
After the update to 16.03 everything behaves as it should.
This seemed to be a bug in 15.09 but is now fixed.

Thank you for your comments, will close this issue now.

**Comment by ThomasMader** [comment]
> I installed NixOS unstable (16.03) on my Mac Mini 7,1 and have the following probem with it.

Reading this first line of my first comment in this issue again it must have been a bug in 16.03 unstable but is resolved with 16.03 stable.
