### ISSUE TITLE
WHERE GONE bumblebee.extraDeviceOptions ???

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#11543]
How to configure bumblebee xorg driver now???

**Comment by abbradar** [comment]
Use `extraNvidiaDeviceOptions`; I've splitted it from `extraNouveauDeviceOptions` while adding nouveau support.

**Comment by Pitometsu** [comment]
Thanks.

**Comment by abbradar** [comment]
Glad it helped. I've also added a mention in release notes: https://github.com/NixOS/nixpkgs/commit/ca3b47cccc2c2acfd8b3027175f637c0e36f250a.

**Comment by dezgeg** [comment]
Typically deleted options are marked deleted in the nix code as well - see `nixos/modules/rename.nix`.

**Comment by domenkozar** [comment]
Also make sure you set it as obsolete in `nixos/modules/rename.nix`

**Comment by abbradar** [comment]
It's not a NixOS option, it's a package option instead. Can we mark those as deleted at all?

**Comment by domenkozar** [comment]
Ah, sadly, no.

**Comment by abbradar** [comment]
I _think_ we actually can with a clever hack, e.g.

```
{ ..., oldOption ? null, ... }: # or other default which would be unexpected for the old option

if oldOption != null then abort "Use newOption instead" else
...
```

**Comment by domenkozar** [comment]
even better as resuable, documented function :)

**Comment by abbradar** [comment]
Sadly I don't know how this can be wrapped as a function (although this can be done somewhere at `callPackage` level instead, I think)  -- any ideas?
