### ISSUE TITLE
BloomRPC

### ISSUE THREAD

**Issue by dmrzh** [NixOS/nixpkgs#115530]
**Project description**
GUI Client for exploring and querying GRPC services

**Metadata**

* homepage URL: https://github.com/uw-labs/bloomrpc
* source URL: https://github.com/uw-labs/bloomrpc
* license: gpl3
* platforms: unix, linux, darwin, ...

**Comment by abathur** [comment]
This appears to have been added in:
- https://github.com/NixOS/nixpkgs/pull/120292
