### ISSUE TITLE
Is nix.gc.dates still in use or nixos-only?

### ISSUE THREAD

**Issue by spease** [NixOS/nixpkgs#115699]
On this wiki page:
https://nixos.wiki/wiki/Storage_optimization

This example is given:

```
nix.gc = {
  automatic = true;
  dates = "weekly";
  options = "--delete-older-than 30d";
};
```

However when attempting to use it with nix-darwin, I get this:

```
building the system configuration...
error: while evaluating 'evalModules' at /nix/store/r0s01vbhnmpc1s1w81sbq2gp22js7kbb-nixpkgs-21.03pre269455.3155a9e966a/nixpkgs/lib/modules.nix:62:17, called from /nix/store/mvaxd88862wfnlgzqj7qsck0cgikkrxk-darwin
/darwin/eval-config.nix:25:10:
The option `nix.gc.dates' does not exist. Definition values:
- In `/Users/spease/.nixpkgs/darwin-configuration.nix': "weekly"
```

Is this option nixos-only?

Thanks.

**Comment by hmenke** [comment]
The option `nix.gc.dates` exists in NixOS.  For darwin I don't know, but this is also not the correct issue tracker.  Please go to https://github.com/LnL7/nix-darwin/issues
