### ISSUE TITLE
Python: Move packages from all-packages.nix to python-packages.nix

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11567]
Most Python packages are defined or called from `python-packages.nix`, but not all. Some are called from `all-packages.nix` and this can cause [trouble](https://github.com/NixOS/nixpkgs/commit/6cf4e29c4f33d40c6560e25f38071c3c6a876cbb) when including such package in a Python environment with a different version of the Python interpreter.

The solution is to call all Python packages/modules via `python-packages.nix`. That also means any `callPackage ../path/to/package/default.nix` in `all-packages.nix` needs to be moved to `python-packages.nix`. Preferably, the Nix expressions would also be using `buildPythonPackage` and be moved into `python-packages.nix` but this is not always possible.

List of modules to look at:
- [x] `foursuite`. I moved it already.
- [x] `ecdsa`. Removed duplicate.
- [x] `numeric`. Old, unmaintained, superseeded 10 years ago by numpy. I think we can drop it. The game castle_combat depends on it but is broken as well.
- [ ] `pyatspi`. Only Python 3 available now, but this is not clear since it is in `all-packages.nix` and not in `python-packages.nix`. Could you move this, @jgeerds ?
- [x] `psyco`. Last release from 2007. i686 only, and not used in nixpkgs. Drop it.
- [x] `pycups` Moved and updated it.
- [x] `pyside` should use [pyside-setup](https://github.com/PySide/pyside-setup) repository to get pip compatible version of pyside and ofcourse move it to python-packages.nix (by @garbas)

I will open a PR soon with some of the changes.

cc @domenkozar @garbas 

See also https://github.com/NixOS/nixpkgs/issues/1819

**Comment by garbas** [comment]
i'm currently hitting very similar problem with pyqt since for my current project i need it to work for different python and different qt version

+1 from my side

**Comment by FRidh** [comment]
@jagajaga 
There are three things which I am doing here:

1. expose all Python packages via `python-packages.nix`
2. rewrite expressions using `buildPythonPackage` when that makes sense
3. move expressions from separate files into `python-packages.nix`

Why is that? Let's discuss each point separately.

1. Packages that are used that don't go via `python-packages.nix` are generally only available for Python 2, and are also by default Python 2. In https://github.com/NixOS/nixpkgs/pull/11389 this caused some weird behavior. A Python 3 version of a package was not building because somehow a Python 2 version got into the environment. This was fixed in https://github.com/NixOS/nixpkgs/commit/6cf4e29c4f33d40c6560e25f38071c3c6a876cbb as cited by @domenkozar . To prevent this behavior, and to actually make packages available for all interpreters and versions, we put the expressions in, or call them from, `python-packages.nix.
2. This one I think is obvious. It will reduce duplicate work, errors, and so on.
3. Moving the actual expressions can indeed be discussed. While calling them from here is sufficient, as explained in 1), actually moving them is not necessary. However, it can make it easier, because comparable expressions are in the same file.

**Comment by globin** [comment]
I'm not in favour of 3) as the *-packages.nix files are getting really large and hard to deal with, I'd personally prefer keeping expressions in seperate files.

But 1 + 2 :+1:

**Comment by garbas** [comment]
i'm also with @globin on 3. i would rather see smaller python-packages.nix

**Comment by FRidh** [comment]
Having smaller, more easier to handle files, is a fair argument. You can indeed notice that GitHub already gets slow loading such large files.

I like having it in a single file as it makes searching easier; searching over a lot of files generally gets a lot slower in my editor (kate) although I could probably just use `git grep` instead.

But how would you split expressions in files then? One file per expression? We would get a lot of files, and you would still need to add `callPackage ` in `python-packages.nix` with the occasional arguments as well, making it again error prone. 

In my opinion both have ways have their advantages and disadvantages, but if you would consider the extreme cases (all in one, or all in their own files) I would prefer the former.

Or maybe something in between? A file per first letter, and then just concatenate the attribute sets?
For some letters (`p`) the files will still be large but it should at least be manageable.

**Comment by copumpkin** [comment]
No opinion on the specific issue, but `awscli` and `ansible`/`ansible2` also fall into the bucket of python packages that live in `all-packages.nix`.

**Comment by FRidh** [comment]
@copumpkin thanks, I'll have a look at them as well. There are quite some Python applications/packages out there that are outside of `python-modules/` and `python-packages.nix`.

Note thata it is also important to distinguish between a library and an application. In most cases, it is sufficient to have the application for only one Python version (generally 2.7), and moving it then into `python-packages.nix` is not necessary. In other cases you do want it for several versions (example: `ipython`).

**Comment by garbas** [comment]
@FRidh is it ok if i created a checklist out of above bullet points? i've added pyside to the list which i plan to work soonish

**Comment by FRidh** [comment]
@garbas sure go ahead. Note that pyside is in `python-packages.nix` since #11572 and works now with both 2.7 and 3.x.

**Comment by FRidh** [comment]
A little update.

As far as I know all Python libraries are now called via `python-packages.nix`. Therefore I am closing this issue. Furthermore. when adding now or updating current libraries we should indeed put the expressions in separate files in `python-modules.nix` and call them via `python-packages.nix`. During the last year the `python-packages.nix` file has grown quite a bit...

**Comment by jgeerds** [comment]
@FRidh We should mention this new convention (e.g. separate files inside `python-modules`) in our changelog

**Comment by globin** [comment]
ping @FRidh

**Comment by globin** [comment]
ping
