### ISSUE TITLE
pptp package contains pptpsetup, which references pptpd, but not pptpd

### ISSUE THREAD

**Issue by apatil** [NixOS/nixpkgs#11563]
The pptp package generates a shell script called pptpsetup, which references an executable called pppd.

``` shell
anand@anand-mbp> grep which /home/anand/.nix-profile/sbin/pptpsetup                               
    my $command = q/strings `which pppd`|grep -i mppe|wc --lines/;
```

pppd is present in the Nix store, but is not symlinked into the environment:

``` shell
anand@anand-mbp> sudo find / -name pppd                                  ~
/nix/store/4sfdrfz0ldcrf6kd027jslpbjy93sq5j-ppp-2.4.7/include/pppd
/nix/store/4sfdrfz0ldcrf6kd027jslpbjy93sq5j-ppp-2.4.7/bin/pppd
/nix/store/4sfdrfz0ldcrf6kd027jslpbjy93sq5j-ppp-2.4.7/lib/pppd
[1] anand@anand-mbp> which pppd                                              ~
pppd not found
```

Consequently, there's an error when I try to run pptpsetup:

``` shell
sh: which: command not found
```

**Comment by jgillich** [comment]
I could be wrong, but doesn't sh say `which` is not found?

**Comment by apatil** [comment]
That's what I thought at first, then I changed my mind, and now I think you're right. :) Pppd should probably be symlinked either way though.

**Comment by zimbatm** [comment]
Yes, pptpsetup  should be patched to replace
 ```
`which pppd`
```

by `${pptp}/bin/pptp`

**Comment by Profpatsch** [comment]
(triage) Looks like this was patched by @obadz.

**Comment by obadz** [comment]
I have not patched this particular instance. What is the purpose of this script?

**Comment by mmahut** [comment]
Are there any updates to this issue, please?
