### ISSUE TITLE
vscode-extensions: package CMake utils

### ISSUE THREAD

**Issue by fogti** [NixOS/nixpkgs#115650]
**Project description**
Personally, I use the vscode extensions `twxs.cmake` and `ms-vscode.cmake-tools` on a Gentoo box. They make editing CMake files in VSCode easier. Currently, these extensions aren't packaged in `nixpkgs`, but it would be more practical if they were.

**Metadata**

* [`twxs.cmake`](https://marketplace.visualstudio.com/items?itemName=twxs.cmake)
* [`ms-vscode.cmake-tools`](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools)
* License: both MIT

**Comment by jonringer** [comment]
could use #99968 which would allow you to run a variant of vscode which doesn't require explicit nixification.

**Comment by ThibaultLemaire** [comment]
It is now possible to install extensions from within VSCode without going through nix.

However, I manage all my other vscode extensions through nix, and I would like to add the cmake extensions mentioned here to that set.

I can make a PR. Where should I start looking to add an extension to `vscode-extensions` ?
