### ISSUE TITLE
Murmur doesn't build without re2, doesn't depend on it

### ISSUE THREAD

**Issue by DIzFer** [NixOS/nixpkgs#115745]
**Describe the bug**
murmur failed to build on current nixos-unstable (29b0d4d0b600f8f5dd0b86e3362a33d4181938f9). Stated reason is ld being unable to find re2... while I can't verify it should be depending on re2 at all.

As expected, adding re2 to the mumble server buildInputs let it build fine.

**To Reproduce**
1. git checkout a526d49118f9fd29c996672920fe0d48c7c72732
2. nix build nixpkgs.murmur ←fails

1. git checkout a526d49118f9fd29c996672920fe0d48c7c72732^
2. nix build nixpkgs.murmur ← succeeds

**Additional context**
Apparent source of this issue seems to be a526d49118f9fd29c996672920fe0d48c7c72732. This feels weird, does this mean dependencies are/were somehow bleeding through? Why doesn't murmur build when re2 is vendored in grpc (which is what I understand this commit is doing?).

I'd just PR 10910c4d0d233437768762d2f808f0d9b107c00f, but this is too weird to just add an undocumented dependency and carry on...

**Notify maintainers**
@petabyteboy
@Infinisil

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.1-zen1, NixOS, 21.05.git.9ef0f2df3c1M (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(zurdo): `""`
 - channels(root): `"home-manager"`
 - nixpkgs: `/home/zurdo/src/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: murmur
# a list of nixos modules affected by the problem
module: services.murmur
```

**Comment by mohe2015** [comment]
I have no idea but what about:
https://github.com/NixOS/nixpkgs/compare/master...mohe2015:mumble

**Comment by DIzFer** [comment]
On 14/03/2021 00:17, Moritz Hedtke wrote:
> I have no idea but what about:
> https://github.com/NixOS/nixpkgs/compare/master...mohe2015:mumble

This does it, and I assume is the properer fix. Now off to find out why
I thought Nix was magically supposed to figure these things out...

**Comment by mohe2015** [comment]
@DIzFer I think this can be closed now.
