### ISSUE TITLE
Python: extracting package information from PyPI (WIP)

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11587]
# Introduction

As with some of the other languages that are available in Nix we would like to have the entire [PyPI](https://pypi.python.org/pypi) in Nix as well. Unfortunately, as explained during NixCon, Python packaging is a bit of a mess, with the biggest issue being that dependencies are not available.

I would like to discuss here how we could extract as much information from PyPI as possible, and how we would make that information available in Nix to build packages.

_See also [Python to-do list](https://github.com/NixOS/nixpkgs/issues/1819)_
# What's available?
## PyPI api

PyPi has two api's, [JSON](https://wiki.python.org/moin/PyPIJSON) and [XMLRPC](https://wiki.python.org/moin/PyPIXmlRpc).

With the api's we can directly and reliably extract:
- name
- version
- description
- available source archives with md5 (unfortunately not sha256)
- description

With a bit of regex applied to the `license` field we can come up with a guess of the license as well.
## source archive

If we would download the source files, then we can 
- determine sha256
- come up with a much better guess of the license 
## pypi2nix

With [pypi2nix](https://github.com/garbas/pypi2nix) we should be able to
- extract build inputs, although I don't think we can distinguish between `buildInputs` and `propagatedBuildInputs`
- come up with a much better guess of the license
# How to implement in nixpkgs?

Eventually, we want to have a script that would automatically build as good as possible Nix expressions. Still, it is likely that many derivations need to be manually corrected, especially the cases when extension types are included.

So, how would this then look like in nixpkgs? Let's have a look at how other such collections in nixpkgs are implemented and maintained.
### Perl

For Perl there is a [tool](http://nixos.org/nixpkgs/manual/#ssec-generation-from-CPAN) that creates a Nix expression for a package from CPAN (so similar to `pypi2nix`). However, the index of packages is still maintained entirely manually.
### KDE / Plasma 5

A [nix expression](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5.5/srcs.nix) is [generated](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5.5/fetchsrcs.sh) with an attribute set that contains per package the version, along with source url and sha256 hash, which are obtained by downloading all files. A function, `plasmaPackage`, is used to generate derivations based on these sets.
## Other related issues

Issues to consider also are
- **size of files**. While it is likely not a problem if an autogenerated file is huge, files that need to be modified by us, e.g. to override what is autogenerated, should have a manageable size. See also discussion in https://github.com/NixOS/nixpkgs/issues/11567#issuecomment-163346186
# Proposal

At the time of writing there are 70835 packages on PyPI. This will include a significant amount of broken and outdated packages as well. I think we only want to build derivations for those that are supposed to work.

We might want to consider two different stages here:
1. when we use PyPI, and possibly (or optionally) download the source files as well;
2. when we also use `pypi2nix`.
## Stage 1

In stage 1 we use use just PyPI and optionally also the source archives. In this stage we want to only have derivations for those packages that are actually supposed to work. We could therefore have one single file (JSON, or nix set) with all the data that is collected from PyPI and possibly from the source archive. In `python-packages.nix` we then use `buildPythonpackage`, like we do now, in conjunction with the raw source data. For convenience, we might want to have a helper function `buildPyPIPackage` function (like `plasmaPackage` for KDE/Plasma) that calls `buildPythonPackage` and then override to modify/correct the derivation.

Files:
- autogenerated index `pypi_sources.json` containing just sets. 
- curated `pypi_curated.nix` which contains derivations based on the entries in `pypi_sources.json`.
- `python-packages.nix` which contains all Python derivations, that is the whole set of packages that is in `pypi_curated.nix` as well as those from a different source.

To have files of manageable size we could split the packages on initial letter of their names (again, see https://github.com/NixOS/nixpkgs/issues/11567#issuecomment-163346186).
## Stage 2

In this stage we use `pypi2nix`, or at least Python wheels, to extract relevant information. This extra info would then be fed back into `pypi_sources.json`. 
We would also have a `pypi_generated.nix` that would contain automatically generated, **working** derivations, built from `pypi_sources.json`.

To be able to build a wheel, the actual inputs needs to be available. Obviously this can be problematic; `numpy` will most definitely not _just_ work, however, many packages do depend on it. Therefore, for this process, we already also need a (minimal) curated `pypi_curated.nix`. 

Files: 
- the above mentioned files
- `pypi_generated.nix` with automatically generated and working derivations
# More to follow...

**Comment by domenkozar** [comment]
My plan was to use `wheel` could to do `setup.py` -> `setup.json` conversion and extract all information from there. The JSON files should be stored in a git repository for "caching" :)

**Comment by garbas** [comment]
if you check pypi2nix master what you describe here in this PR is exactly what is happening

**Comment by garbas** [comment]
also give it a try, almost all projects for last month. i got it quite close to working (just few lines in override file were needed)

**Comment by FRidh** [comment]
@garbas indeed, the [Readme](https://github.com/garbas/pypi2nix#design) mentions the procedure.

What I am missing is how other Python packages fit in, and most importantly, how you would deal with packages for which you still do not know all dependencies (extension types e.g.).

An example is running `python setup.py bdist_wheel` when the package imports `numpy` in `setup.py`. If `numpy` is not available you cannot generate the wheel, right?

Yes, I will give it a try.

**Comment by garbas** [comment]
@FRidh actually i think i need to update the design a bit.

stage0: i use ``pip wheel`` command to create wheelhouse and run `pip freeze` to create requirements.txt

stage1: requirements.txt is used to get source url and md5 (i was hoping i could also get this in stage0, but without luck for now)

stage2: figure out dependencies between packages in requirements.txt (that is why haveing stage0 is so important)

stage3: generate requirement.nix, requirement_generated.nix and (empty) requirement_overrides.nix (with list of dependencies from stage2 and wheelhouse from stage0) we can generate above files)

**Comment by garbas** [comment]
initially i was parsing wheel's ``metadata.json`` but found this very error prone. i got much better results with above described way.

i'm not saying info about dependencies in ``metadata.json`` is useless but that it will take us quite an effort to get it right. also we can add it at any time alongside current solution.

**Comment by FRidh** [comment]
## Stage 1
So I wrote a script to extract from PyPI as much relevant data for Nix as possible. The resulting JSON file is large, 156 MB. Included is the `longDescription` which I think we should just remove because it is generally very ugly formatted as well. I would guess we could save at least half the size there. However, build inputs are *not* included, so keep that in mind.

In my current implementation it takes I think just over half an hour to perform all 71.000 requests. It was my first time using `asyncio`, so I suppose improvements are possible here.

### To do
- Match PyPI licenses with what's available in Nixpkgs `lib.licenses`.
- Create `pypi_curated.nix`.

## Stage 2

Now that we have `pypi_sources.json` it is time to integrate `pypi2nix`. 

### pypi2nix

- pypi2nix needs only a list of package names in a `requirements.txt` to start building. Therefore, what I have in my stage 1 is largely unneeded. Obtaining a list of all packages on PyPI can be done with xmlrpc in a single call.

- `cli.py` goes through three stages:
    1. `wheelhouse.do` to build initial wheels. A local cache is created, and then `nix-build` builds a wheel for each requirement using `pip.nix`. The sources archives are not stored in the Nix store though.
    2. `parse_wheels.do` does the parsing and extracts the relevant data.
    3. `stage3.do` writes a Nix expression

- Files that are not used anymore:

  - `json2wheels.py` attemps to build wheels for each package in a JSON file. It uses `nix-build` for that, thereby caching the source archives and produced wheels. However, it seems it needed a modified `nixpkgs` (`python27.wheels.build`) and has been deprecated in favor of *stage 1* ? @garbas 
  - `wheels2nix.py`
  - ...

### Nice to have

Patch pip to perform a `nix-build` of the source archive whenever pip needs a source file. That way we don't have to download source archives twice (first time for creating a Nix expression, and a second time to actually build the package in case you want to have it.)

**Comment by domenkozar** [comment]
@FRidh good job! I think `pip` supports `--find-links=/tmp/` and if you put the source files there it will reuse them

**Comment by FRidh** [comment]
@domenkozar but that doesn't help with building the final expression, right? When building those expressions it would have to download the source archives again. If we would store all the archives in the Nix store, then the cache that `pypi2nix` creates/needs could just consist of symlinks to each source archive in the store. Anyway, it's a minor thing, and likely harder to implement compared to what it is worth.

**Comment by FRidh** [comment]
The url scheme of pypi has changed as @grahamc mentioned on nix-dev. That means with each package update, we need to update the url.

Pre-preduction deployment of the new pypi, warehouse, is now available at https://pypi.org (was https://warehouse.python.org). I just checked and the `simple` API is still there, and it includes sha256 :-)

**Comment by Profpatsch** [comment]
triage: what’s the status?

**Comment by FRidh** [comment]
The https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/update-python-libraries script works "ok" for now. No need to keep this open.
