### ISSUE TITLE
Firefox lacks /share/applications/

### ISSUE THREAD

**Issue by shiftypenguin** [NixOS/nixpkgs#11588]
I've installed firefox via nix-env, both root and otherwise, and it doesn't put a /share/applications/ in its /nix/store/*firefox*/ directory. GUI apps usually put a .desktop file there so DEs can display the apps.

Edit: same is true for ESR version

**Comment by abbradar** [comment]
You need to use `firefoxWrapper`, among other things it has a `.desktop` file.

**Comment by shiftypenguin** [comment]
Oh. thanks. That hadn't occurred to me. Maybe worth putting that in the package description?

**Comment by abbradar** [comment]
I thought so too, but I'm unsure where should that go to be visible enough for users. I think that we may just rename `firefox` -> `firefox-original` and `firefoxWrapper` -> `firefox`, as we've done with Steam -- I've seen at least a couple of such questions asked on IRC and issues, and was one of the confused croud myself some time ago.

cc @wkennington @edolstra @ttuegel (I'm unsure who the real maintainer of `firefoxWrapper` is)

**Comment by vcunat** [comment]
Yes, I agree with renaming. We're (slowly) moving towards preferring attribute names, so the "default versions" should have the simple attribute name that people can guess.

**Comment by abbradar** [comment]
I think the rule might be:
Wrappers which introduce plugins but are not necessary needed for the application to actually "work" (including .desktop shortcuts and things) might be called `app-with-plugins`, with App being just `app`.
Wrappers which are needed for application to work might be called `app`, and App `app-original`.

**Comment by vcunat** [comment]
Or the wrapper can use an empty plugin list by default, if none are really needed for the application to run. We could also provide `app.unwrapped` for those who really want an unwrapped version, etc. &ndash; there are many ways of doing it...

**Comment by abbradar** [comment]
Hm, indeed that's even nicer -- empty wrapper overhead would be tiny (if any) anyway, compared to convenience.

**Comment by ttuegel** [comment]
> We could also provide app.unwrapped for those who really want an unwrapped version

I am already doing this for other applications, such as [Clementine](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/clementine/default.nix#L94) and [SDDM](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/display-managers/sddm/default.nix#L70).

Whatever we are going to do, I think we should 1) standardize across Nixpkgs to the extent possible, and 2) document the choice in the Nixpkgs manual.

**Comment by cleverca22** [comment]
chromium solved this issue by hiding the true base chromium package in a let block, then exposing the wrapper to nixpkgs, so your always using the wrapped version

**Comment by vcunat** [comment]
Wrappers renamed in PR #12299.
