### ISSUE TITLE
packaging request: chromium-bsu (arcade game)

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#115993]
**Project description**
> Chromium B.S.U. is a fast paced, arcade-style, top-scrolling space shooter.

This package is available in the Gentoo package repository: https://packages.gentoo.org/packages/games-action/chromium-bsu; [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/games-action/chromium-bsu/chromium-bsu-0.9.15.1-r1.ebuild) (the ebuild isn't for the latest released version, tho)

**Metadata**

* `pname = "chromium-bsu"`
* homepage URL: http://chromium-bsu.sourceforge.net/
* source URL: `mirror://sourceforge/${pname}/${pname}-${version}.tar.gz`
  gentoo url, nixos has an equivalent to the sourceforge mirrors, but I don't know how to translate it.
  see also: http://sf.net/projects/chromium-bsu/files
* license: (according to gentoo) `Clarified-Artistic`, (according to project homepage) [The "Artistic License"](http://chromium-bsu.sourceforge.net/LICENSE)
* platforms: unix. requires OpenGL

**Comment by AndersonTorres** [comment]
Please do the honors, @zseri
