### ISSUE TITLE
Python:  buildPythonPackage downloaded packages from PyPI

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#11599]
In https://github.com/NixOS/nixpkgs/pull/11595 I noticed that  a single package (`wheel`) built with `buildPythonPackage` was able  to connect and download dependencies from PyPI while it was not supposed to.

In general retrieving dependencies is indeed blocked; you can test this by just removing a build input and see what happens
```
installing
/tmp/nix-build-python2.7-odo-0.3.3.drv-0/odo-0.3.3/dist /tmp/nix-build-python2.7-odo-0.3.3.drv-0/odo-0.3.3
Ignoring indexes: https://pypi.python.org/simple
Processing ./odo-0.3.3-py2-none-any.whl
Collecting networkx (from odo==0.3.3)
  Could not find a version that satisfies the requirement networkx (from odo==0.3.3) (from versions: )
```
That's what we like to see.

However, `wheel` was still able to download its dependencies, and maybe other packages are capable of doing this as well...

**Comment by FRidh** [comment]
I guess it is the `tests_require`

**Comment by FRidh** [comment]
Possibly relevant, `pip.conf` or `~/.pypirc`: http://stackoverflow.com/questions/30437446/how-change-setup-py-test-to-use-different-pypi-server

**Comment by FRidh** [comment]
@domenkozar any way we can block in `checkPhase` as well?

**Comment by FRidh** [comment]
Adding
```
    printf "[easy_install]\n--allow-hosts=None" >> setup.cfg
```
to `installCheckPhase` doesn't seem to help.

**Comment by domenkozar** [comment]
Oh, that's setuptools stuff. Blah. I removed easy_install restrictions since I thought they're not needed anymore.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/pull/11086/files#diff-2562f94de4e4fd2ddc677187fa2e2848L69

I hope we can find a better way.

**Comment by FRidh** [comment]
Ha, okay. Well, more for the to do list hm.

**Comment by Profpatsch** [comment]
(triage) was this solved in the meantime?

**Comment by FRidh** [comment]
I don't think it has been solved but I haven't encountered it anymore and as I was the only noticing it I am closing this.
