### ISSUE TITLE
packaging request: kaitai_compress

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#115931]
**Project description**
kaitai_compress is a helper package for use in the Kaitai Struct runtime environment providing some extra functionality. Currently nixpkgs only has the Python runtime environment for Kaitai Struct but more could follow in the future. I am wondering what the best way to package this would be:

* supplying it as an input to the kaitai struct runtime environment
* creating a separate module and somehow combining it

Guidance would be appreciated. I think the first would be the easiest, but not entirely sure.

**Metadata**

* homepage URL: http://kaitai.io/
* source URL: https://github.com/kaitai-io/kaitai_compress
* license: MIT
* platforms: linux

**Comment by cole-h** [comment]
Resolved in https://github.com/NixOS/nixpkgs/pull/119992.
