### ISSUE TITLE
nox is broken  

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11594]
```
nix-channel --list
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

Ubuntu 14.04. 

`nox nox`
```
Traceback (most recent call last):
  File "/nix/store/33pg4ryh11x02gikp0a5ivw2zshjd30h-nox-0.0.2/bin/.nox-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/ljji9lp3iq57p1a1bj40iv1n3ilrsmxw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/ljji9lp3iq57p1a1bj40iv1n3ilrsmxw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 655, in main
    raise RuntimeError('Click will abort further execution '
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```

**Comment by FRidh** [comment]
How did you install `nox`? Were there any other Python packages in the same environment? (`nox` is written in Python`)
cc @madjar

**Comment by FRidh** [comment]
@aragnon 
what's the output of `nix-env -q`?

**Comment by madjar** [comment]
I've seen this before (https://github.com/madjar/nox/issues/19), this is a locale problem (plus the fact that click is not tolerant at all with locale problems).

The reason nox is fails is the same reason that perls gives a warning: locale is not set correctly.

**Comment by aragnon** [comment]
@FRidh $ `nix-env -q`
```
nix-1.10
nox-0.0.2
scala-2.11.7
```

**Comment by aragnon** [comment]
@madjar I'd argue that no locale should actually be "wrong". nox should just detect the situation and set a reasonable one with a warning to stderr along with a link to how to set it "correctly". Programs should degrade gracefully.

**Comment by madjar** [comment]
@aragnon That is a valid position. Sadly, the creator of the click library, which handles command line parsing and output in click does not agree with this (mostly because guessing in the face of ambiguity can be even worst).

I'm not sure if I'll use click on my next project, but for now, all I can do is urge you to look into your locale configuration problem.
