### ISSUE TITLE
KDE5 version of kmix is missing

### ISSUE THREAD

**Issue by retrry** [NixOS/nixpkgs#11598]
I'm trying to upgrade my system, but Nix can't find kde5 version kmix. I have kde5.kmix in my configuration.nix. Kmix was available before the big changes to KDE5 packaging.

```
nix-env -qa kmix
```
Only returns returns kde4 version - kmix-4.14.3

cc @ttuegel

**Comment by FRidh** [comment]
As explained by @ttuegel in https://github.com/NixOS/nixpkgs/pull/10731 a lot of packages were not packaged because more maintainers are needed.

**Comment by ttuegel** [comment]
Specifically, I did not package `kmix` because it is not being updated upstream. There is `plasma-pa` for PulseAudio, and in the future this will be the only supported configuration.

**Comment by retrry** [comment]
Sorry and thank you for the explanation :)
