### ISSUE TITLE
Brave and Wayland

### ISSUE THREAD

**Issue by maxhille** [NixOS/nixpkgs#115956]
I want to run Brave as a native Wayland app with working screensharing on Sway. As I already had set up Chromium a while ago to do the same I kind of knew what to do already. I prepared two changes which I am running right now and which seem to work:

* 185218ce8ef1ea39a34de49405ee215732c6f552 adds the Pipewire client library to the package to make Wayland screensharing work. There are continuous error outputs on the console while sharing the screen but it seems to work fine.
* b5eec621761fa8935c9dcf596d3c631cfddead78 adds a way to let the user supply command line arguments via a config file. This is how Arch has it set up. The Nix Chromium build makes this possible via a more elaborate Chromium package.

Since maintaining user modified Nix packages is very annoying and I am too stupid to inject the Pipewire depedency via an overlay, I open this issue so we can maybe get these changes Nix-upstream and use this as a place to track the progress of making Brave in NixOS run well in Wayland.

**Comment by maxhille** [comment]
Update (also to unstale this):

Ozone/Wayland activation per setting:
https://github.com/NixOS/nixpkgs/pull/115961 is superceded by a better approach in https://github.com/NixOS/nixpkgs/pull/136591

Pipewire client library has been merged with https://github.com/NixOS/nixpkgs/pull/115959

As of the time of this post. Brave/OzoneWayland is broken (at least on my machine): https://github.com/NixOS/nixpkgs/issues/133331

**Comment by wmertens** [comment]
See also #147557

**Comment by maxhille** [comment]
Closing this as obsolete because the Pipewire integration is merged and the command line / wayland situation is addressed in a more generic way via https://github.com/NixOS/nixpkgs/pull/147557
