### ISSUE TITLE
Proper way to set owner of config file

### ISSUE THREAD

**Issue by katyo** [NixOS/nixpkgs#11604]
I have used a `pkgs.writeText` for generating my own config for **msmtp** utility.

When my app run it, in security reasons **msmtp** throws an error like this:

```
msmtp: /nix/store/1qncl9naf6wgm2i5v4irlnhw7sibz04r-msmtprc: must be owned by you
```

But I can't find a proper way to fix owner.

I have tried the next solution but something went wrong and actual owner is _root_ (not _www_):

``` nix
let
  fixOwner = owner: path: rec {
      inherit path;
      res = runCommand "fixOwner" { inherit owner path; } ''
        chown $owner "$path"
      '';
    }.path;
  myConf = fixOwner "www" writeText "msmtprc" ''
    ...
  '';
in
...
```

```
[kayo@nixie:~]$ ls -al /nix/store/*msmtprc*
-r--r--r-- 1 root nixbld  320 Jan  1  1970 /nix/store/1qncl9naf6wgm2i5v4irlnhw7sibz04r-msmtprc
```

**Comment by lethalman** [comment]
You cannot and shouldn't change ownership of files in nix store. If you need that, write stuff in `/etc` with `environment.etc`.

**Comment by katyo** [comment]
Ok. Thanks.

**Comment by grahamc** [comment]
Looks like this is resolved.

**Comment by nh2** [comment]
> write stuff in `/etc` with `environment.etc` on nixos.

How do I change the `chown` with `environment.etc`?

**Comment by nh2** [comment]
> How do I change the chown with environment.etc?

Aha, found it with https://nixos.org/nixos/options.html#etc.

Example:

```
    environment.etc.myfile = {
      target = "mydir/myfile1";
      text = "blabla";
      mode = "0440";
      uid = config.ids.uids.postgres;
    };
```
