### ISSUE TITLE
On aarch64-linux, any hackage package which isn't available on all platforms is unsupported

### ISSUE THREAD

**Issue by Thra11** [NixOS/nixpkgs#116095]
**Describe the bug**
There are a large number of hackage packages which nixpkgs thinks aren't supported on aarch64-linux, but which should be (and build just fine).

It appears that if a package is listed in `pkgs/development/haskell-modules/configuration-hackage2nix.yaml`'s `unsupported-platforms` section, (e.g. `sdl2-ttf: [ x86_64-darwin ]`), hackage2nix will subtract the given set of unsupported platforms from the following set of packages: [ armv7l-linux i686-linux x86_64-linux x86_64-darwin ] (I Haven't managed to track down where that set comes from exactly), using the result as `platforms` in the nix expression. This results in this for `sdl2-ttf`:
```
       platforms = [ "armv7l-linux" "i686-linux" "x86_64-linux" ];
```
It looks like configuration-hackage2nix.yaml was trying to say that `sdl2-ttf` wasn't supported on x86_64-darwin. However as a result of that, the nix expression ends up changing from platforms being empty (implicitly supporting all platforms, including aarch64-linux) to platforms being restricted to three platforms (excluding aarch64-linux).

Needless to say, this is inconvenient on aarch64-linux as it means you have to enable "allow unsupported system" (meaning you can no longer tell which packages which are genuinely unsupported), and many packages aren't built by hydra, so you have to build them locally.

**To Reproduce**
1. On aarch64, run `nix-build '<nixpkgs>' -A haskellPackages.sdl2-ttf` (`sdl2-ttf` is simply one example of many affected packages.
```
error: Package ‘sdl2-ttf-2.1.2’ in /home/thrall/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:228481 is not supported on ‘aarch64-linux’, refusing to evaluate.
```
 
**Expected behavior**
It should build or fetch haskellPackages.sdl2-ttf without requiring "allow unsupported system" to be enabled (sdl2-ttf works just fine on aarch64 if you enable it and build it yourself).

**Notify maintainers**
@peti 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.0-rc5, NixOS, 21.03.git.c49054f5b0e (Okapi)`
 - multi-user?: `yes`
\<process hung\>

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    haskellPackages
```

**Comment by cdepillabout** [comment]
@Thra11 maybe you could take a look in https://github.com/NixOS/cabal2nix to figure out where this implicit list `[ armv7l-linux i686-linux x86_64-linux x86_64-darwin ]` comes from, and add `aarch64-linux` to it?

**Comment by Thra11** [comment]
Think this might be it https://hackage.haskell.org/package/distribution-nixpkgs-1.4.0/docs/src/Distribution.Nixpkgs.Meta.html#allKnownPlatforms

**Comment by Thra11** [comment]
With #116096 merged, I believe this is fixed. Thanks!
