### ISSUE TITLE
wget 1.21.1 is broken on macOS

### ISSUE THREAD

**Issue by dhess** [NixOS/nixpkgs#116035]
Looks like https://github.com/NixOS/nixpkgs/pull/115698 broke wget on macOS:

https://hydra.nixos.org/build/138814998

This has also been indirectly reported elsewhere:

https://github.com/NixOS/nixpkgs/pull/115487#issuecomment-795393098

**Comment by midchildan** [comment]
Homebrew seems to have solved this by specifying `--without-included-regex` in the configure options. https://github.com/Homebrew/homebrew-core/pull/68667

From the GNU mailing list:

> Ah, yes, I see that your build uses the flag `--without-included-regex`. That should probably take care of the build failure I'm seeing. Thanks for the tip, Ryan.
>
> The header of regex.c says it's part of glibc, though, so it's no surprise that it leads to build failures on macOS. wget probably shouldn't be using this on non-Linux platforms.

https://lists.gnu.org/archive/html/bug-wget/2021-01/msg00076.html

**Comment by midchildan** [comment]
BTW findutils 4.8.0 would need fixing too. (nixpkgs is currently at 4.7.0)

**Comment by midchildan** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/110647#issuecomment-766300643

**Comment by veprbl** [comment]
@dhess @midchildan Thanks
