### ISSUE TITLE
nextcloud: how to configure caching / no extraOptions-like hook?

### ISSUE THREAD

**Issue by stuebinm** [NixOS/nixpkgs#116189]
Currently, the nextcloud modules has a set list of config options (in `services.nextcloud.config`), and no `extraOptions`-style hook for freeform text which should be appended to nextcloud's configuration file.

In particular, I am unable to figure out how to set up redis caching with the nextcloud module — the description for [services.nextcloud.caching.redis](https://search.nixos.org/options?channel=20.09&show=services.nextcloud.caching.redis&from=0&size=50&sort=relevance&query=services.nextcloud.caching.redis) states that "you still need to enable Redis in your config.php", but there is no description of how to do that, and no corresponding option in the module.

I think the module should offer something like `services.nextcloud.config.extraOptions`, particular since this is probably also an issue for other possible configurations of nextcloud (given that its [full list of configuration paramaters](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html) is prohibitively long) — or am I just missing something obvious?

**Comment by genofire** [comment]
Same problem ;(
