### ISSUE TITLE
steam browser protocol always opens a new copy of steam

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#116125]
**Describe the bug**

**To Reproduce**
1. install `steam`
2. open an instance of `steam`
3. run `steam steam://rungameid/1055540` (or substitute the game id for any game id you have installed, you can find the app id for any game [here](https://steamdb.info/apps/)) - note how a **new** instance of `steam` is launched to run the game

**Expected behavior**

I used to run `steam steam://rungameid/1055540` and the already open instance of `steam` would launch a game, but now when I run this command a new instance of `steam` is launched and the game runs.

**Screenshots**

**Additional context**

I'm not sure when this problem started... it used to work fine, but I haven't checked in a while :man_shrugging: 

https://developer.valvesoftware.com/wiki/Steam_browser_protocol

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.97, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.2642.88f00e7e12d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module:
```

random ping of people who I think use `steam` on NixOS: @danieldk @jonringer @bbigras @danieldk @nyanloutre @ashkitten

**Comment by ashkitten** [comment]
this works on nixos-unstable, may need a stable backport of 721ea006a841176e6045b479e2d44ed2b47ed3d0.

**Comment by jonringer** [comment]
note, you will also have to backport my changes to buildFHSUserEnv, which allows for `unsharePid` to be exposed

**Comment by aanderse** [comment]
Thanks again everyone! We're getting close enough to a new release that I usually switch my personal boxes over to unstable for testing soon anyways, so this issue will be resolved for me shortly.
