### ISSUE TITLE
Partial autogeneration of AppArmor profiles?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11610]
Looking through [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/torrent/transmission.nix#L108-L144), it seems like much of the current profile is just enumerating runtime dependencies, and most of the rest is covering where runtime state goes. Could we come up with a decent approximation for something that computes such a list on the fly, but also allows manual tweaks?

**Comment by qknight** [comment]
like nix-copy-closure detecting all deps and then create a white-list from that?

**Comment by joachifm** [comment]
Wrt. manual tweaks, AppArmor profiles are composable, in the sense that you can impose additional restrictions as you please (my understanding is that the final profile is the most restrictive subset of the union of all the rules attached to a given path). 

My opinion is that rules such as "may not execute random shell code at current privilege level" are more important than listing exact store paths of shared libraries that an application loads into memory.

I believe that effort is best spent re-using upstream profiles to the extent possible, adding shims as necessary to account for discrepancies between NixOS and Ubuntu file systems.  As I recall, many
profiles looked to be re-usable with only light patching on our end, but I never pursued it further, so I might be mistaken. Perhaps you'd end up with so much tweaking that you'd basically rewrite everything anyway, but it is worth exploring IMO, given the amount of work (by upstream) that's already gone into defining usable profiles.

**Comment by Profpatsch** [comment]
(triage) I don’t see an action item here, can we close?

**Comment by joachifm** [comment]
Currently, apparmor is basically just cruft that does very little for us. If we decide not to improve how we deal with apparmor profiles, we might as well disable it outright, IMO. This course of action is supported by the lack of interest in apparmor overall.
