### ISSUE TITLE
todoist-electron requires electron v11

### ISSUE THREAD

**Issue by jonknapp** [NixOS/nixpkgs#116101]
**Describe the bug**
After electron 12 came out, adding `todoist-electron` in home-manager succeeds, but trying to start the app fails mentioning a missing javascript function from an older version of electron.

**To Reproduce**
1. Add `todoist-electron` to home-manager's `home.packages`
2. Run `home-manager switch`
3. Start app from terminal with `todoist`

**Expected behavior**
Expected the application start as it had before.

**Additional context**
I was able to get it working locally by providing an overlay to home-manager:

```nix
nixpkgs.overlays = [
  (self: super: {
    todoist-electron =
      super.todoist-electron.override { electron = pkgs.electron_11; };
  })
];
```

I would have created a PR myself, but I'm still new to nix and not sure entirely how to require a different electron version in the package derivation.

**Notify maintainers**
@i077 @kylesferrazza

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-7642-generic, Pop!_OS, 20.10`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(jon): `"home-manager, nixpkgs-21.05pre275183.0867f627424"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/todoist-electron/default.nix

**Comment by i077** [comment]
@jonknapp thanks for catching this! Just fixed in the PR above.
