### ISSUE TITLE
SDDM Setup Script

### ISSUE THREAD

**Issue by carldong** [NixOS/nixpkgs#11622]
Is there a way to manage the setup scripts for SDDM? A custom `XSetup` script is needed to use NVIDIA Optimus driver without Bumblebee (which does not work in my case). I am using KDE plasma 5 so SDDM is preferred.

Side problem: Apparently SDDM theme "breeze" does not work as intended. I will test those on both 15.09 and unstable

Reference:
https://wiki.archlinux.org/index.php/NVIDIA_Optimus#SDDM

**Comment by ttuegel** [comment]
The Breeze SDDM theme was not installed by unstable until a few hours ago, but it should be working now.

**Comment by carldong** [comment]
Still, I would need the `XSetup`...

**Comment by ttuegel** [comment]
@carldong This is implemented in the lastest `master` now as the option `services.xserver.displayManager.sddm.setupScript`.

**Comment by carldong** [comment]
Is master pushed to unstable every few days?

**Comment by ttuegel** [comment]
The unstable channel is updated when it passes the tests; [the NixOS FAQ](https://nixos.org/wiki/FAQ#What_are_channels_and_how_they_get_updated.3F) has more information.

**Comment by carldong** [comment]
It still doesn't update after a week. I hope can directly use the Master branch of this repo in my system despite the possibility of breaking anything, but I don't see the information
