### ISSUE TITLE
'Unit fprintd.service could not be found

### ISSUE THREAD

**Issue by mcdviii** [NixOS/nixpkgs#116291]
## Issue description
`sudo systemctl status/start fprintd` returns `Unit fprintd.service could not be found.`

### Steps to reproduce
Add user to `input` group via `extraGroups` & install `fprintd`, `libfprint` & `imagemagick` using `environment.systemPackeges`

## Technical details

`nix-shell -p nix-info --run "nix-info -m"`:

- system: `"x86_64-linux"`
- host os: `Linux 5.4.89, NixOS, 20.09.2642.88f00e7e12d (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.10`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
Applications added to `environment.systemPackages` are not made available to `systemd` - that's intended behaviour. Set `services.fprintd.enable = true;` which will pull in what you need.
