### ISSUE TITLE
nim: unresolved symbols with host 20.09 and nim from unstable

### ISSUE THREAD

**Issue by adamlwgriffiths** [NixOS/nixpkgs#116368]
**Describe the bug**
Running NixOS 20.09.
Using Niv to gain access to unstable.

Attempting to run `nim` to compile anything leads to "unresolved symbol" errors.

A work around I've found is to install `nim-unwrapped` which seems to provide a working nim.
[Example repo demonstrating this fix](https://github.com/adamlwgriffiths/nix-nim).

```
$ nim compile test.nim 
Hint: used config file '/nix/store/92r6yp0i2n3wb5mv1fr6wfpv57dm5h8q-x86_64-unknown-linux-gnu-nim-wrapper-1.4.2/etc/nim/nim.cfg' [Conf]
....CC: stdlib_io.nim
CC: stdlib_system.nim
/bin/sh: symbol lookup error: /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
CC: test.nim
/bin/sh: symbol lookup error: /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE

Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/nix/store/impyg4875ygammahsaa73s7w6h91wpmz-nim-unwrapped-1.4.2/nim/lib -I/home/adam/Workspace/nim-test -o /home/adam/.cache/nim/test_d/stdlib_io.nim.c.o /home/adam/.cache/nim/test_d/stdlib_io.nim.c' failed with exit code: 127


/bin/sh: symbol lookup error: /nix/store/m0xa5bz7vw7p43wi0jppvvi3c9vgqvp7-glibc-2.32-25/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE
```

**To Reproduce**

1. Get nix shell with unstable packages.
I used niv.
$ niv init
$ niv update nixpkgs -b nixpkgs-unstable

2. shell.nix (gcc glibc added to try and fix this, did nothing)
```
let
    sources = import ./nix/sources.nix;
    pkgs = import sources.nixpkgs {};
in
pkgs.mkShell {
    nativeBuildInputs = [
    ];
    buildInputs = [ pkgs.nim ];

    NIMBLE_DIR = toString ./.nimble;

    shellHooks = ''
        export CFLAGS_COMPILE=$NIX_CFLAGS_COMPILE
        export LDFLAGS=$NIX_LDFLAGS
        export LD_LIBRARY_PATH=$NIX_LD_LIBRARY_PATH
    '';
}
```

3. test.nim

```
echo "What's your name? "
var name: string = readLine(stdin)
echo "Hi, ", name, "!"
```

4. enter the nix shell.
5. `nim compile test.nim`

**Expected behavior**
Compilation to succeed.

**Additional context**
[Discourse link](https://discourse.nixos.org/t/unresolved-symbols-using-nim/11320)

**Notify maintainers**
@ehmry 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.86, NixOS, 20.09.2497.4a75ca4a4e7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.9`
 - channels(root): `"home-manager-20.09, nixos-20.09.3415.2821518e360, unstable-21.05pre275232.29b0d4d0b60"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nim
```

**Comment by FliegendeWurst** [comment]
Works on NixOS 21.11.
