### ISSUE TITLE
Upgrading to git-MASTER on Mac OS X gives me "unknown pre-build hook command ‘’"

### ISSUE THREAD

**Issue by mikesperber** [NixOS/nixpkgs#11632]
When I try to upgrade to git-MASTER, I get this:

~~~
...
  /nix/store/ig6dlpar68fm3274kfdvxh4f74lvxfds-python2.7-Pygments-2.0.2.drv
building path(s) ‘/nix/store/jpxrfhxwrw1vjw5qjkbr84sdq2hvwcpd-stdenv-darwin-boot-0’
error: unknown pre-build hook command ‘’
 ~~~

(I have nix itself from a MASTER build a few weeks ago, but can't upgrade that because of #11456.)

**Comment by peti** [comment]
Does this problem still exist? Can other Mac users confirm that they have the same issue, please?

**Comment by cresh** [comment]
I've just ran into this after pulling today:
```
> nix-env -iA nixUnstable --option build-use-chroot false
replacing old ‘nix-1.11pre4273_71039be’
installing ‘nix-1.11pre4334_7431932’
these derivations will be built:
[...]
  /nix/store/9c2as0ahhvy88s8j0hisij88arl419n1-nix-1.11pre4334_7431932.drv
building path(s) ‘/nix/store/jpxrfhxwrw1vjw5qjkbr84sdq2hvwcpd-stdenv-darwin-boot-0’
error: unknown pre-build hook command ‘’
```

**Comment by benley** [comment]
I'm seeing this today as well.

**Comment by benley** [comment]
After downgrading nix to 1.10 (nixStable) rather than nixUnstable, the error went away.  No idea if this is a nix bug or something introduced in nixpkgs, though.

**Comment by cresh** [comment]
Thanks for the tip, that worked for me, too. I downgraded to stable and then was able to upgrade to unstable again. Using `nix-env` with sandbox support enabled currently works for me.

**Comment by Profpatsch** [comment]
(triage) @benley @cresh do you still see that bug on a current master?

**Comment by cresh** [comment]
@Profpatsch No, I don't see that currently.

**Comment by Profpatsch** [comment]
@peti I think we can close then.

**Comment by benley** [comment]
It seems to have gone away for me as well. Please reopen if the issue returns.
