### ISSUE TITLE
Build util-linux with systemd support.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#11637]
This is more of a question the a bug, but it would be nice to find the best solution.

Some util-linux programs have extra features that are available when compiled with systemd support. For example `logger --journald` can be used to add structured data into the journal from the shell.

The hard part is that in nixos systemd depends on util-linux which creates a dependency cycle so it isn't as simple as adding `systemd pkgconfig` to the requirements.

Below I have included a workaround that creates a new package with systemd support, however this isn't particularly nice because it means that you have to have two versions of util-linux.

``` nix
{
    nixpkgs.config.packageOverrides = pkgs: rec {
        utillinux-sd = pkgs.stdenv.lib.overrideDerivation pkgs.utillinux (old: {
        nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.systemd pkgs.pkgconfig ];
            configureFlags = old.configureFlags + ''
                --with-systemd
                --with-systemdsystemunitdir=$out/lib/systemd/system/
            '';
        });
    };
}
```

The `--with-systemd` flag isn't required but it is nice because it causes a failure if systemd isn't found.

`--with-systemdsystemunitdir` is required otherwise it tries to write it's unit file into the systemd store directory.

**Comment by Mathnerd314** [comment]
The easiest thing would be to point systemd to ``/run/current-system/sw/bin/<prog>`` for every program in util-linux. This is already done for polkit: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/systemd/default.nix#L101

**Comment by kevincox** [comment]
Would anything special be required to ensure that util-linux is installed when systemd is? Or is it part of some "base" set?

**Comment by lethalman** [comment]
@Mathnerd314 that variable would be `PATH`. Anyway, this issue is about util-linux depending on systemd, not viceversa, right? Didn't understand much your comment.

**Comment by kevincox** [comment]
@lethalman IIUC The problem is that making util-linux depend on systemd would create a circular dependency. So @Mathnerd314 is suggesting that the explicit dependency `systemd -> utillinux` be removed so that the dependency `utillinux -> systemd` can be added, as this is a build dependency where as the `systemd -> utillinux` is only a runtime dependency.

**Comment by lethalman** [comment]
Ah ok makes sense.

**Comment by Mathnerd314** [comment]
> Would anything special be required to ensure that util-linux is installed when systemd is? Or is it part of some "base" set?

It's required to be in the system path: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/system-path.nix#L42

> that variable would be PATH

In an ideal world, maybe, but many programs are written with an absolute path in mind. Grep ``current-system`` in nixpkgs to see all the hacks in place. Since it is not going away anytime soon the next-best thing is to abstract it so that we can find all usages and modify them easily.

**Comment by cleverca22** [comment]
there are already 2 variants of util-linux in nixpkgs, utillinux and utillinuxCurses

one solution would be to have systemd depend on the light version, then put the full version into systemPackages

**Comment by vcunat** [comment]
Yeah, I expect that solution to have the best ratio of packaging work vs. cleanliness of result.

**Comment by kevincox** [comment]
What do you want to rename them to? `utillinux` and `utillinuxFull`? Leaving the others as aliases for now? `utillinuxMinimal` also isn't a bad name

**Comment by nckx** [comment]
+1 for `bikeshedMinimal` over `bikeshedFull`.

**Comment by kevincox** [comment]
Please see my [other PR](#12952) which implements `utillinuxMinimal` and `utillinux`.
