### ISSUE TITLE
cheese can't find the vp8enc preset in gst-plugins-good

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#11634]
As reported by @bjornfor in #11491,
cheese use the vp8enc element for realtime encoding, and specified `deadline=1`
in [Profile Realtime] of the GstVP8Enc.prs file from `gst-plugins-good`.

but, can't find it when running, warn with:

```
(cheese:9615): cheese-WARNING **: Can't find vp8enc preset: "Profile Realtime",
using alternate preset: "Cheese Realtime".
If you see this, make a bug report!
```

then, a user GstVP8Enc.prs preset will be created in `~/.local/share/gstreamer-1.0/presets`
with `deadline=0`, which will give poor recordings.

It seems that gstreamer only search system presets under:
`$gstreamer/share/gstreamer-1.0/presets`
and cheese don't modify parameters when creating the fallback user profile.

**Comment by lheckemann** [comment]
I think this is fixed by now? I'm not seeing this message. Suggest close.

**Comment by lheckemann** [comment]
Ah yes, I didn't remove the directory before trying. Can reproduce it after all.

**Comment by jtojnar** [comment]
Reported it upstream: https://bugzilla.gnome.org/show_bug.cgi?id=791119

**Comment by jtojnar** [comment]
> It seems that gstreamer only search system presets under:
> `$gstreamer/share/gstreamer-1.0/presets`

You are right, that is the problem.

Adding `${gst_all_1.gst-plugins-good}/share/gstreamer-1.0/presets` to the `GST_PRESET_PATH` variable fixes this issue.
