### ISSUE TITLE
Emacs lsp-mode broken on nixos-unstable

### ISSUE THREAD

**Issue by spacekookie** [NixOS/nixpkgs#116354]
**Describe the bug**

Installing and using `lsp-mode` has been broken for a few days now.

**To Reproduce**
1. Install `emacs`
2. Install `lsp-mode`
3. Start emacs and try to start `lsp`

Log messages:

```
Unable to activate package ‘lsp-mode’.
Required package ‘f-0.20.0’ is unavailable
Unable to activate package ‘lsp-ui’.
Required package ‘lsp-mode-6.0’ is unavailable
Unable to activate package ‘lsp-mode’.
Required package ‘f-0.20.0’ is unavailable
```

**Expected behavior**

`lsp-mode` is started.

**Comment by avdv** [comment]
Hi @spacekookie ,

could you provide more details how to reproduce this. Is it still the case for you?

**Comment by nagy** [comment]
Closing for irreproducibility.
