### ISSUE TITLE
Ledger Live Desktop does not work with Ledger HW devices due to use of fhsUserEnv

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#116361]
**Describe the bug**

From IRC: https://logs.nix.samueldr.com/nixos/2021-03-14#1615762150-1615762514;

```
22:49 <clever> colemickens: fhs-env, i see the problem!
22:49 <clever> daedalus had the exact same issue
22:49 <colemickens> >:(
22:49 * colemickens haha matrix shows it as a quote
22:49 <clever> colemickens: hotplug events from udevd, are fired into the kernel, which then re-broadcasts them over a special socket, to every libudev client listening for hotplug
22:50 <clever> colemickens: when the kernel does that, it will try to preserve the uid of the sender
22:50 <clever> colemickens: but, a non-root namespace (like the fhs-env) cant map root to a uid, for security reasons, so the uid of the sender becomes nobody
22:50 <clever> and libudev actively rejects such messages
22:50 <clever> colemickens: https://github.com/input-output-hk/daedalus/blob/develop/nix/systemd.patch
22:51 <colemickens> I wonder if this is why LLD segfaults in some of these cases on exit :P
22:51 <clever> likely unrelated
22:51 <clever> the above patch, disables that bit of security in libudev
22:51 <clever> running it outside of a fhs-env would also work
22:51 <colemickens> it segfaults in libudev.so.1.7.0[7f60e96f3000+22000]
22:53 <colemickens> clever: sorry if this is a dumb question, but systemd has to be patched system-wide or that "fix" applies client-side?
22:54 <clever> colemickens: client side fix, only the libudev inside the fhs-env needs it
22:55 <clever> colemickens: running it without the fhs-env would likely also work 
```

Looks like we currently just use their appimage:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/blockchains/ledger-live-desktop/default.nix#L16

and our appimage tooling uses buildUserFHSEnv:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/appimage/default.nix#L10

It seems like we can either:
1. Stop using `fhsUserEnv` (build from source, maybe?)
2. Patch `libudev` similar to how iohk patches Daedalus.

**Comment by asymmetric** [comment]
@colemickens I tried packaging it with yarn2nix, but stumbled upon [this](https://github.com/nix-community/yarn2nix/issues/121), unfortunately.

**Comment by DavHau** [comment]
I don't know much about the appimage architecture. Why exactly can we not run appimages natively without FhsUserEnv?
Is it just because binaries linking against fhs paths?
In this case we probably could run autoPatchelfHook on the contents of the appimage and produce a new image that links against nix libs.

**Comment by colemickens** [comment]
@cleverca22 how difficult would it be to lift Daedalus's patch and use it for the libudev inside the fhs? I've never worked with FHS before, but also don't want to build ledger live from source...

**Comment by andresilva** [comment]
I tried to build ledger live from source and it didn't work because of the `yarn2nix` issue that @asymmetric mentioned. Patching libudev worked though.

**Comment by colemickens** [comment]
@andresilva can you link to the patch? It would be great to be able to use my more-trusted nixos machines for these types of activities.

**Comment by andresilva** [comment]
I already created a PR for it and it's linked above. This one: https://github.com/NixOS/nixpkgs/pull/138969

**Comment by andresilva** [comment]
Feel free to comment in the PR whether it actually works for you :)

**Comment by flokli** [comment]
The patch had to be re-done in https://github.com/NixOS/nixpkgs/pull/205193.

Should this problem probably be communicated to upstream, so we can think about how to fix this long-term in a more sustainable fashion?
