### ISSUE TITLE
GSConnect requires manual iptables configuration to work

### ISSUE THREAD

**Issue by tad-lispy** [NixOS/nixpkgs#116388]
**Describe the bug**

On NixOS after installing GSConnect Gnome extension it won't discover Android devices on the network untill ports 1714 - 1764 are open. Perhaps it would be possible to open those ports automatically when the extension is installed?

**To Reproduce**

1. Install the extension by adding the following to `/etc/nixos/configuration.nix`:

   ```nix
   environment.systemPackages = with pkgs; [
     # ...
     gnomeExtensions.gsconnect
   ]
   ```
2. Run `nixos-rebuild switch` and reboot.
3. Open connect Android device to the same WiFI network as the computer
4. Open KDEConnect on the device and set it to pairing.
5. Open GSConnect on NixOS. The devices won't see each other.
6. Open the ports in the firewall configuration:

   ```nix
   networking.firewall.allowedTCPPortRanges = [
     # KDE Connect
     { from = 1714; to = 1764; }
   ];
   networking.firewall.allowedUDPPortRanges = [
     # KDE Connect
     { from = 1714; to = 1764; }
   ];
   ```

7. Try connecting again. It works.

**Expected behavior**

Devices should just connect without step 6 above.

**Screenshots**

![image](https://user-images.githubusercontent.com/1684495/111127341-04e8d380-8574-11eb-8e9d-5b2cd7043e87.png)

**Additional context**

This issue by @doronbehar led me to discover the workaround: https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/901

**Notify maintainers**

@etu 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.18, NixOS, 20.09.3341.df8e3bd1109 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-20.09.3341.df8e3bd1109"`
 - channels(tad): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/tad/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

_edit: imperatively opening ports with `iptables` seems to have broken my system. After reboot it wouldn't start the network service._

**Comment by doronbehar** [comment]
Hi :)

First of all, it could be super awesome if there was a `programs.kdeconnect.enable` or `programs.phone-connect.enable` option that would free the correct ports **and** choose the right package - `kdeconnect` or `gsconnect` (at least by default) based on whether gnome or plasma DE is enabled. 

2ndly, when I had these issues with gsconnect, I did not have firewall enabled at all. Still I had issues only during the transition from kdeconnect to gsconnect and I can't put my finger on their source. I'm happy though that it helped you figure out what's needed to make it work.

**Comment by doronbehar** [comment]
https://github.com/NixOS/nixpkgs/pull/63899 Addresses some of the issues here, though there's a lot of work to do there.

**Comment by doronbehar** [comment]
I will close this, as https://github.com/NixOS/nixpkgs/pull/63899 was merged and it includes a suggestion to use GSConnect, and it mentions that it opens the mentioned ports.

**Comment by ahydronous** [comment]
Only marginally relevant, but since this is the only NixOS issue about this on the first page of search engines, let me just post the fix for anyone having this problem in the future:

```
programs.kdeconnect = {
  enable = true;
  package = pkgs.gnomeExtensions.gsconnect;
}
```
Make sure that the GSconnect extension isn't already imperatively installed by the user, before doing a `nixos-rebuild` or GSconnect won't work until you manually uninstall it, then reboot. You might also need to logout.
