### ISSUE TITLE
Fix usbip listing functionality

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#116380]
Add `configureFlags = [ "--with-usbids-dir=${hwdata}/share/hwdata/" ];` to
https://github.com/NixOS/nixpkgs/blob/3e6571316c65638e7a4c1aa2f2700e405be82487/pkgs/os-specific/linux/usbip/default.nix based on
https://github.com/NixOS/nixpkgs-channels/blob/4762fba469e2baa82f983b262e2c06ac2fdaae67/pkgs/tools/admin/lxd/default.nix#L32 and 
https://github.com/torvalds/linux/blob/fcadab740480e0e0e9fa9bd272acd409884d431a/tools/usb/usbip/configure.ac#L90

before: 
```
$ usbip list -l
usbip: error: failed to open /usr/share/hwdata//usb.ids
 - busid 1-1 (0483:3748)
   unknown vendor : unknown product (0483:3748)
```

after: 
```
$ usbip --debug list -l
 - busid 1-1 (0483:3748)
   STMicroelectronics : ST-LINK/V2 (0483:3748)
```

**Comment by Luflosi** [comment]
Is there a reason you didn't make a PR? I tested your suggestion and it seems to work fine.

**Comment by deliciouslytyped** [comment]
No, I just didn't feel like doing it at the time, feel free to PR.
