### ISSUE TITLE
appimagekit / appimagetool fails with "mksquashfs: invalid option"

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#116331]
**Describe the bug**
appimagetool from nixpkgs fails with an error about invalid options to mksquashfs

**To Reproduce**
1. `nix-shell -p appimagekit`
2. `ARCH=x86_64 appimagetool ./thing.AppDir`
3. error

**Expected behavior**
An AppImage will be produced

**Additional context**
A similar issue is mentioned here: https://github.com/AppImage/AppImageKit/issues/592 and the conclusion is that they were using an outdated version of AppImageKit, whereas more recent versions are bundled with a modified version of mksquashfs.

Our version is fairly outdated, so it might be that, but it might also be that we specifically tell AppImageKit to use our system version of mksquashfs (https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/appimagekit/default.nix#L93), which presumably does not have those modifications. I see that we apply some modifications to squashfuse (https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/appimagekit/default.nix#L18), should we do the same thing with mksquashfs?

I tried messing with some of these things, and couldn't get anything to build.

**Notify maintainers**
@pedropombeiro you were the last person to make any significant change to this package. Did it work when you did? Does it still work? Do you know what might be going wrong?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.99, NixOS, 21.05pre272380.f6b5bfdb470 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.05pre272380.f6b5bfdb470, nixos-hardware"`
 - channels(qolen): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: appimagekit
# a list of nixos modules affected by the problem
module:
```

**Comment by piegamesde** [comment]
#116501 very probably resolved this, as I can no longer reproduce the issue.

**Comment by Radvendii** [comment]
Oh, good catch. It also fixed it for me. Not sure why I didn't close the issue; I probably just forgot.
