### ISSUE TITLE
starting software in nix-shell: icon in taskbar not shown

### ISSUE THREAD

**Issue by fkz** [NixOS/nixpkgs#11641]
I started spotify with `nix-shell -p spotify --run spotify`. Instead of the spotify icon, it shows a 'txt paper'. When installing with `nix-env` or `configuration.nix` instead, the icon is correctly shown.

**Comment by ttuegel** [comment]
This is expected behavior. The icon must be installed to `/run/current-system/sw/share/icons/hicolor` for the taskbar, window manager, etc. to find it.
