### ISSUE TITLE
mattermost service: how to specify secrets?

### ISSUE THREAD

**Issue by stuebinm** [NixOS/nixpkgs#116421]
The mattermost module has an option to make mattermost's config immutable (`services.mattermost.mutableConfig = false`), and specify the server's entire config via the module / `extraConfig` hook. Doing this, however, I cannot figure out a way of then specifying secrets (e.g. the password for mattermost's mail account) without putting them in the nix store, which is world-readable.

Have I missed something, or is there currently really no way to do that?

**Comment by Pacman99** [comment]
You will probably have to set mutableConfig to true and add secrets through the console. Other nixos modules have started copying config files to the service's data directory using `envsubst`, which will look for all variables referenced in a file and replace with the relevant environment variable. So you can set secrets using systemd's EnvironmentFiles which won't be in the nix store, and reference them within config files. 
But mattermost doesn't do this. So the best current option with the current module is to set secrets imperatively. Optimally, the module would be changed to allow for setting declarative secrets.
