### ISSUE TITLE
usb_modeswitch-data and udev rules missing

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#11647]
According to that: https://github.com/NixOS/nixpkgs/issues/11197

I found that usb-modeswitch is provided with usb-modeswitch-data  (on http://www.draisberghof.de/usb_modeswitch/). usb-modeswitch-data package contains data for modems and udev rules as well to activate modems (switch usb from usb-storage mode to modem-mode).

usb-modeswitch-data package is missing from nixos. I think would be nice to add this :-)

**Comment by spinus** [comment]
I create pull request with udev rules for modems https://github.com/NixOS/nixpkgs/pull/14133.
But there is one issue there, I have no idea how to expose udev rules from a package.

Do I need to create some system glue/system service/system module in nixos to do that? Or there is a way to expose those rules from a package level?

**Comment by zimbatm** [comment]
Once master goes to nixpkgs-unstable you will be able to use `services.udev.packages = with pkgs; [ usb-modeswitch-data ];`. It will install the udev rules on the next `nixos-rebuild switch`.

**Comment by spinus** [comment]
huh, interesting. Do you think it's better to do it that way rather than create let's say "modem" service which inject this package to udev.packages?

**Comment by zimbatm** [comment]
Not necessarily but it's one available option.

Do you know if this package cover *all* the modems ?

Adding more abstraction always has a cost and I don't understand the specific modem domain space enough to know what is the best option to be honest.

**Comment by spinus** [comment]
Definitely not cover all, but it's what debian is using, I think ubuntu may use this + they add some extra stuff usually to cover corner cases. I think this package should cover most stuff.

**Comment by zimbatm** [comment]
Before building a module around this I think it would be worth testing the udev rules to see if they work with nixos properly. Do you have any modems at hand you could use for that ?

**Comment by spinus** [comment]
@zimbatm yes, I have one which requires that (that's why I started that). I'll test over the weekend to make sure it works properly and report here.

**Comment by zimbatm** [comment]
Okay great. Feel free to ping me on irc if you hit any snag. I might be there but not guaranteed :)

**Comment by Profpatsch** [comment]
triage: any updates?

**Comment by spinus** [comment]
Unfortunately not, I left that topic. I don't know if that was fixed by someone else.

**Comment by Profpatsch** [comment]
cc @zimbatm

**Comment by spinus** [comment]
Looks like that is done and now you can enable udev rules with ``hardware.usbWwan.enable=true;``.

**Comment by nyanloutre** [comment]
Hello, the rules doesn't seems to work. I am using a Logitech G920 which is configured by usb_modeswitch.

I added usb-modeswitch-data to the udev rules, it shows up in /etc/udev but nothing gets applied.

It look like the package is missing something
