### ISSUE TITLE
go-task do not creates expected `task` executable

### ISSUE THREAD

**Issue by endorama** [NixOS/nixpkgs#116555]
Hello everyone, I recently tried to install `go-task` package. 

The website and all the documentation refers to the executable as `task`, but I noticed that the Nix package has a `postInstall` command that changes the name to `go-task`:

https://github.com/NixOS/nixpkgs/blob/266dc8c3d052f549826ba246d06787a219533b8f/pkgs/development/tools/go-task/default.nix#L24-L26

This behaviour is unexpected. In my case, I was expecting the Nix installed executable to be used while I was using another one due to this inconsistency (to the project documentation).

I was wondering what is the reason for this behaviour and if it was possible to change it to the documented value of `task`. Happy to submit a PR if the change is accepted.

Thanks!

**Comment by veprbl** [comment]
cc @Parasrah

**Comment by Parasrah** [comment]
This change was intentional as otherwise it would conflict with the `task-warrior` binary, and was a requested change on my original PR prior to it being approved. I agree it is inconvenient, and I myself include `go-task` as an overlay in my projects to preserve the original binary name

**Comment by veprbl** [comment]
cc @danieldk 
cc #93619

It should be fine to not not rename: nix-env should be able to handle it using `nix-env --set-flag priority 10 task-warrior`, `buildInputs` should preserve the order in the $PATH, and there is always an option to refer to an executable by its full name as `${go-task}/bin/task`.

**Comment by endorama** [comment]
@Parasrah may you share the overlay? I'm pretty new to all this and struggle a bit in creating working overlays. That would help a lot :)

**Comment by Parasrah** [comment]
@endorama yeah for sure, this is an trimmed down overlay that I use in one of my projects:

```
self: super:
{
  go-task =
    super.buildGoModule
      rec {
        pname = "go-task";
        version = "3.2.2";

        src = super.fetchFromGitHub {
          owner = pname;
          repo = "task";
          rev = "v${version}";
          sha256 = "0x94z023rsl7h9prw0i4zkwb5xf2frjz8f15mmcknw48r9ymw598";
        };

        vendorSha256 = "05sh4jbva23ggg2viknl49bwgkhf8dfvsv3rqkl4wwi9ag64qgha";

        doCheck = false;

        subPackages = [ "cmd/task" ];

        buildFlagsArray = [
          "-ldflags=-s -w -X main.version=${version}"
        ];

        meta = with super.lib; {
          homepage = "https://taskfile.dev/";
          description = "A task runner / simpler Make alternative written in Go";
          license = licenses.mit;
          maintainers = with maintainers; [ parasrah ];
        };
      };
    }
```

There is likely a shorter way to do this, but I was in a rush at the time and this works.

[This](https://search.nixos.org/options?channel=20.09&show=nixpkgs.overlays&from=0&size=50&sort=relevance&query=nixpkgs) shows how to apply an overlay like this on `NixOS`. [This](https://nixos.wiki/wiki/Overlays) is also a good resource.

That said it sounds like it would be okay for you to remove that `postInstall` hook that changes the binary name, I would have preferred to have it remain `task` as well.
