### ISSUE TITLE
eval errors: makeWrapper problems with runtimeShell

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#116504]
**Describe the bug**

There are still packages / wrappers broken (as in, they don't eval) due to https://github.com/NixOS/nixpkgs/pull/112276. This affects cross-compilation of those packages.

Related to https://github.com/NixOS/nixpkgs/issues/114687.

Seems to be related to makeWrapper. Removing makeWrapper as input (sometimes) works, but doesn't seem like the right solution.

**To Reproduce**

- `nix build --dry-run .#pkgsCross.aarch64-multiplatform.xwayland`
- `nix build --dry-run .#pkgsCross.aarch64-multiplatform.weston`
- `nix build --dry-run .#pkgsCross.aarch64-multiplatform.vorta`
- `nix build --dry-run .#pkgsCross.aarch64-multiplatform.tmux`
- `nix build --dry-run .#pkgsCross.aarch64-multiplatform.kdiff3`
- `nix build --dry-run .#pkgsCross.aarch64-multiplatform.asciidoctor`

On master (bed86681367c1f57324249db181d142e2efc1f0b). Seems to be the same on staging (611019db382135e0bd3d8a6a03dcc2375388400f).

**Expected behavior**

Eval works (I don't expect these packages to build properly, yet, but I'm looking into how far I can go). This might all be the exact same issue.

**Additional context**

```
rick@nixos-asus:~/nixpkgs$ nix build --dry-run .#pkgsCross.aarch64-multiplatform.xwayland
error: --- EvalError ------------------------------------------------------------------------------------------- nix
at: (524:79) in file: /nix/store/lh57rp2235jzkzgfp6dfk4cpzydw5g1j-source/pkgs/top-level/all-packages.nix

   523| 
   524|   makeWrapper = makeSetupHook { deps = [ dieHook ]; substitutions = { shell = targetPackages.runtimeShell; }; }
      |                                                                               ^
   525|                               ../build-support/setup-hooks/make-wrapper.sh;

attribute 'runtimeShell' missing
```

**Notify maintainers**

@Ericson2314 (who else to ask?)

PS: I wish I could figure out these issues myself, how would I go about it? I find it very hard to trace back where the issues come from.

**Comment by FRidh** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/116207.

**Comment by Mindavi** [comment]
Let's close this then.

**Comment by Mindavi** [comment]
Moving makeWrapper to nativeBuildInput might help for this.
