### ISSUE TITLE
Broken Nixops builds when documentation is enabled

### ISSUE THREAD

**Issue by cab404** [NixOS/nixpkgs#116668]
**Describe the bug**

Configurations break when documentation is enabled.

Error:
```
building all machine configurations...
error: --- ThrownError --------------------------------------------------------------------------------------------------------------------------------------------- nix-build
Nextcloud v18 has been removed from `nixpkgs` as the support for it was dropped
by upstream in 2021-01. Please upgrade to at least Nextcloud v19 by
declaring

    services.nextcloud.package = pkgs.nextcloud19;

in your NixOS config.

[1] https://docs.nextcloud.com/server/18/admin_manual/release_schedule.html
``` 
[Complete trace here](https://gist.github.com/cab404/75e7400487bb50a774f493de846eaf53)

**To Reproduce**
1. Checkout https://github.com/cab404/nixpkgs-nextcloud-bug
2. `nix-shell -p nixFlakes`
3. `nix develop / direnv` to get correct environment
4. `nixops create -n testconfig ./machines.nix; nixops deploy -d "output uuid of nixops create"`

**Notify maintainers**

@Ma27 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.2, NixOS, 21.05.20210306.102eb68 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-21.03pre269343.758b29b5a28"`
 - channels(cab): `"home-manager, nixos-stable-20.09.3087.2394284537b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
Since it's related to Nextcloud, I'll take a look tonight.

**Comment by Ma27** [comment]
@cab404 can you please check if you didn't do an accidental mixup of multiple nixpkgs versions? My first attempt to `nixops deploy --build-only` failed during evaluation (with a different error though) because of my `NIX_PATH`. By running `env NIX_PATH=nixpkgs=/nix/store/ki85w24ipk7czgqqr1n86h37y1by5hfx-source nixops deploy -d testconfig --build-only` (according to `nix develop -vv`, that's the store-path points to the nixpkgs input you're using) I managed to build your deployment.

The store-path I got was `/nix/store/5mvxgz2pjal8zyi7lvjy0qn146mlajab-nixops-machines` btw.

**Comment by cab404** [comment]
Ran bisect on nixpkgs, points to nextcloud commit
```
git bisect start
# good: [a2040f58f31c6167fa3a877d49660420a0dfe71a] Merge pull request #114451 from adisbladis/libgccjit-darwin
git bisect good a2040f58f31c6167fa3a877d49660420a0dfe71a
# bad: [f137bcd5c92906ae0f924769a95b8c8e6602f90b] awscli: 1.19.27 -> 1.19.29
git bisect bad f137bcd5c92906ae0f924769a95b8c8e6602f90b
# bad: [f38b9b258f3f4db5ecf7dd27a7d5b48f23202843] Merge pull request #113714 from ilian/steam-firewall
git bisect bad f38b9b258f3f4db5ecf7dd27a7d5b48f23202843
# good: [28360094d87a15cfe9ef67c51380713a9bafec47] pythonPackages.sfepy: 2019.4 -> 2020.4
git bisect good 28360094d87a15cfe9ef67c51380713a9bafec47
# bad: [09cf3142e0d1a67830fdd39341bdac4f3a75f39b] Merge master into staging-next
git bisect bad 09cf3142e0d1a67830fdd39341bdac4f3a75f39b
# bad: [2c0e6a0e69af6c9a132f93d8500d50606e074f1f] Merge pull request #114586 from hjones2199/indi-full
git bisect bad 2c0e6a0e69af6c9a132f93d8500d50606e074f1f
# good: [2afe5198cdd1b7f59f07ddcb9ea4438119890c0c] Merge pull request #114283 from zseri/zs-apc-spdu-ctl
git bisect good 2afe5198cdd1b7f59f07ddcb9ea4438119890c0c
# bad: [f4bfd7512879573461f6b92ce8b2a826e5e5d27b] Merge pull request #115141 from TredwellGit/electron_12
git bisect bad f4bfd7512879573461f6b92ce8b2a826e5e5d27b
# good: [6402bee9d4ace8edb050b08d49fdc4b69f45f07e] Merge pull request #113203 from leonardp/ceph-fix
git bisect good 6402bee9d4ace8edb050b08d49fdc4b69f45f07e
# good: [4003206152592b239d8bd02dca4fdb3966a880d8] Merge pull request #115131 from adisbladis/emacs-pdf-tool-darwin
git bisect good 4003206152592b239d8bd02dca4fdb3966a880d8
# bad: [b1ef946de6c436a3544bb19c0665a2622de8a06e] nextcloud19: update todo note
git bisect bad b1ef946de6c436a3544bb19c0665a2622de8a06e
# bad: [b1f65920c357b5cdde7123fabdc7a2af4d07f93e] nixos/nextcloud: add `defaultPhoneRegion` option for v21
git bisect bad b1f65920c357b5cdde7123fabdc7a2af4d07f93e
# bad: [f7011c70f30acf0fe5a229b77e4ad22041b8872e] nextcloud21: init at 21.0.0, set as default version
git bisect bad f7011c70f30acf0fe5a229b77e4ad22041b8872e
# first bad commit: [f7011c70f30acf0fe5a229b77e4ad22041b8872e] nextcloud21: init at 21.0.0, set as default version
```

**Comment by cab404** [comment]
> @cab404 can you please check if you didn't do an accidental mixup of multiple nixpkgs versions? My first attempt to `nixops deploy --build-only` failed during evaluation (with a different error though) because of my `NIX_PATH`. By running `env NIX_PATH=nixpkgs=/nix/store/ki85w24ipk7czgqqr1n86h37y1by5hfx-source nixops deploy -d testconfig --build-only` (according to `nix develop -vv`, that's the store-path points to the nixpkgs input you're using) I managed to build your deployment.
> 
> The store-path I got was `/nix/store/5mvxgz2pjal8zyi7lvjy0qn146mlajab-nixops-machines` btw.

Looks promising, will try in a sec

**Comment by cab404** [comment]
@Ma27 Yup, your solution works!
I guess the only thing left to find out is why `eval` in nixops is done via system nixpkgs)

**Comment by Ma27** [comment]
@cab404 I guess this happens because it looks up in NIX_PATH by default. IIRC you should be able to set e.g. `network.nixpkgs = ...`.
