### ISSUE TITLE
LLVM 12

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#116629]
LLVM 12 (not yet released, currently at RC3) will be required for building Chromium M90+ (currently in the beta channel; stable release planned for 2021-04-13; s. 5e42fea124a2882cd6ac5e27c9827bdf97c29282).
cc @ggreif: I couldn't find a draft PR for LLVM 12 yet. Are you already working on it or currently busy?

LLVM Release Schedule:
- 12.0.0:
  - Jan 26: release/12.x branch, 12.0.0-rc1
  - Feb 23: 12.0.0-rc2
  - Mar 2: 12.0.0-final

**Comment by ggreif** [comment]
I have't started yet. But I think I have a few minutes now!

**Comment by ggreif** [comment]
Just a heads-up, we have
> pkgs/top-level/all-packages.nix:    llvm = llvm_10;
Should that transition to `llvm_11`?

**Comment by ggreif** [comment]
I have to hand this over to you, Borg says the unit tests fail (on both platforms, consistently). Maybe the testing framework needs a bump?

**Comment by kvtb** [comment]
Actually, LLVM 12 rcX is not enough
I tested with 12-rc.2 and the key commit https://github.com/llvm/llvm-project/commit/81a9707723845a5b880245da24633c519493205c seems not included into 12-rc.3

You have to wait for 12.0.0 or compile LLVM `master`

related https://github.com/NixOS/nixpkgs/issues/114828

**Comment by primeos** [comment]
The `pkgs/top-level/all-packages.nix: llvm = llvm_10;` match is a bit out of context:
```
  faust2 = callPackage ../applications/audio/faust/faust2.nix {
    llvm = llvm_10;
  };
```

We have `llvmPackages_latest = llvmPackages_11;` so everything should be fine.

@kvtb ok, thanks for that information! If I understand that correctly you've tried compiling `chromiumBeta` or `chromiumDev` with #116646 and it requires cherry-picking https://github.com/llvm/llvm-project/commit/81a9707723845a5b880245da24633c519493205c as well (which would be unfortunate because that commit might not be part of the final release; they don't seem to have a dedicated branch for the LLVM 12 release and I don't know where/how/if they track and provide that information).

**Comment by kvtb** [comment]
I built `clang_13` (from llvm master, simple replacing `fetch`with fetchFromGitHub and removing some lines in `postUnpack`) and it builds Chromium 91

**Comment by primeos** [comment]
RC3 added in https://github.com/NixOS/nixpkgs/commit/7c27d4981556c0a0a5ca9cf0e8eeaf579538883e.
