### ISSUE TITLE
Julia 1.6.0

### ISSUE THREAD

**Issue by uncomfyhalomacro** [NixOS/nixpkgs#116697]
**Project description**
_Julia 1.6.0-rc2_

**Metadata**

* homepage URL: https://julialang.org/
* source URL: https://github.com/JuliaLang/julia/releases/download/v1.6.0/julia-1.6.0.tar.gz
* license: mit
* platforms: unix, linux, darwin

**Comment by GTrunSec** [comment]
Did you try the overlay ?

**Comment by aaronjanse** [comment]
Right now I'll compiling 1.6.0-rc3 (released 30 mins ago) via the overlay. I'll report back

**Comment by aaronjanse** [comment]
I'm getting a curl issue what was not resolved by adding curl in a bunch of places
```diff
diff --git a/pkgs/development/compilers/julia/1.5.nix b/pkgs/development/compilers/julia/1.5.nix
index a523336b7b9..5ac0b896c02 100644
--- a/pkgs/development/compilers/julia/1.5.nix
+++ b/pkgs/development/compilers/julia/1.5.nix
@@ -18,9 +18,10 @@ with lib;

 let
   majorVersion = "1";
-  minorVersion = "5";
-  maintenanceVersion = "3";
-  src_sha256 = "sha256:0jds8lrhk4hfdv7dg5p2ibzin9ivga7wrx7zwcmz6dqp3x792n1i";
+  minorVersion = "6";
+  maintenanceVersion = "0-rc3";
+  url = "https://github.com/JuliaLang/julia/releases/download/v1.6.0-rc3/julia-1.6.0-rc3-full.tar.gz";
+  src_sha256 = "sha256-VhQrs19jYQY+Xd2jEwiCNYoOpOi+3eBKrLuuimKDwlU=";
   version = "${majorVersion}.${minorVersion}.${maintenanceVersion}";
 in

@@ -62,10 +63,10 @@ stdenv.mkDerivation rec {
   buildInputs = [
     arpack fftw fftwSinglePrec libgit2 libunwind mpfr
     pcre2.dev blas lapack openlibm openspecfun readline utf8proc
-    zlib
+    zlib curl
   ] ++ lib.optionals stdenv.isDarwin [CoreServices ApplicationServices];

-  nativeBuildInputs = [ curl gfortran m4 makeWrapper patchelf perl python2 which cmake ];
+  nativeBuildInputs = [ gfortran m4 makeWrapper patchelf perl python2 which cmake curl ];

   makeFlags =
     let
@@ -116,7 +117,7 @@ stdenv.mkDerivation rec {

   LD_LIBRARY_PATH = makeLibraryPath [
     arpack fftw fftwSinglePrec libgit2 mpfr blas openlibm
-    openspecfun pcre2 lapack
+    openspecfun pcre2 lapack curl
   ];

   # Julia's tests require read/write access to $HOME
   ```
   
   https://gist.github.com/aaronjanse/aab710f27ca5fb60b5018cff532b6d61

**Comment by GTrunSec** [comment]
> Edit: ah, I see [JuliaLang/julia#37340](https://github.com/JuliaLang/julia/pull/37340)

I guess using replace string to https://github.com/JuliaLang/julia/blob/7d117dceb0f791e9ab9a7d5864e32809c3ce16c0/stdlib/LibCURL_jll/src/LibCURL_jll.jl#L44 path of ${curl.out}/lib will be fine.

Can you try it?

**Comment by aaronjanse** [comment]
Ooh, good catch. I'll give that a try and report back before going to bed tonight :-)

**Comment by GTrunSec** [comment]
> Ooh, good catch. I'll give that a try and report back before going to bed tonight :-)

- looks like we need to replace all of stdlib paths to static libs such as
```
    preConfigure = ''
      substituteInPlace stdlib/LibCURL_jll/src/LibCURL_jll.jl \
      --replace 'libcurl = "libcurl.so"' 'libcurl = "${prev.curl.out}/lib/libcurl.so"'
      substituteInPlace stdlib/nghttp2_jll/src/nghttp2_jll.jl \
      --replace 'libnghttp2 = "libnghttp2.so.14"' 'libnghttp2 = "${prev.lib.getLib prev.nghttp2}/lib/libnghttp2.so.14"'
    '';
```
test overlay:
```

final: prev:
{
  julia_15 = prev.julia_15.overrideAttrs (oldAttrs: {
    src = prev.fetchzip {
      url = "https://github.com/JuliaLang/julia/releases/download/v1.6.0-rc3/julia-1.6.0-rc3-full.tar.gz";
      sha256 = "sha256-VhQrs19jYQY+Xd2jEwiCNYoOpOi+3eBKrLuuimKDwlU=";
    };

    preConfigure = ''
      substituteInPlace stdlib/LibCURL_jll/src/LibCURL_jll.jl \
      --replace 'libcurl = "libcurl.so"' 'libcurl = "${prev.curl.out}/lib/libcurl.so"'
      substituteInPlace stdlib/nghttp2_jll/src/nghttp2_jll.jl \
      --replace 'libnghttp2 = "libnghttp2.so.14"' 'libnghttp2 = "${prev.lib.getLib prev.nghttp2}/lib/libnghttp2.so.14"'
    '';

    enableParallelBuilding = true;

    LD_LIBRARY_PATH = (oldAttrs.LD_LIBRARY_PATH or [ ]) + prev.lib.makeLibraryPath [
      prev.curl
      prev.nghttp2
    ];

    checkTarget = "";
  });
}

```
let me test more to know which Lib should be replaced.

**Comment by aaronjanse** [comment]
Oh, I think it's okay to override that `n_succeeded > 1200` assertion, especially since it's [now a warning](https://github.com/JuliaLang/julia/blob/2b6c7549915a04cc25847e620784be3bb24da1b9/contrib/generate_precompile.jl#L393-L395).

```diff
diff --git a/contrib/generate_precompile.jl b/contrib/generate_precompile.jl
index 41e7c16..3224c93 100644
--- a/contrib/generate_precompile.jl
+++ b/contrib/generate_precompile.jl
@@ -322,7 +322,7 @@ function generate_precompile_statements()
     if have_repl
         # Seems like a reasonable number right now, adjust as needed
         # comment out if debugging script
-        @assert n_succeeded > 1200
+        @assert n_succeeded > 1100
     end

     tot_time = time_ns() - start_time
```

I feel like we're supposed to be using `USE_SYSTEM_NGHTTP2=1` and `USE_SYSTEM_CURL=1`, but I can't get those to work.

**Comment by GTrunSec** [comment]
this issue already in PR list https://github.com/NixOS/nixpkgs/pull/118000

**Comment by samuela** [comment]
there's also https://github.com/NixOS/nixpkgs/pull/118483. right now we're all stuck on test failures AFAIU

**Comment by ninjin** [comment]
On Sun 04 Apr 2021, Samuel Ainsworth wrote:
> 
> there's also https://github.com/NixOS/nixpkgs/pull/118483. right now we're all stuck on test failures AFAIU

Indeed, v1.6.0 really has proven to be challenging although I am optimistic to have this resolved shortly. On the flip side, we now have a few battle hardened Julia/Nix porters after having smashed their heads against a wall for about a week. =)

**Comment by ninjin** [comment]
On Tue 06 Apr 2021, ninjin wrote:
> 
> On Sun 04 Apr 2021, Samuel Ainsworth wrote:
> > 
> > there's also https://github.com/NixOS/nixpkgs/pull/118483. right now we're all stuck on test failures AFAIU
> 
> Indeed, v1.6.0 really has proven to be challenging although I am optimistic to have this resolved shortly. On the flip side, we now have a few battle hardened Julia/Nix porters after having smashed their heads against a wall for about a week. =)

A v1.6.x source-based derivation proved to be one hard nut to crack [1], but there is now a PR with a working derivations for v1.6.1 by patching the official binary release [2]. While not ideal, it should get you guys up and happily hacking with a supported and up-to-date version of Julia. Not sure if it will suffice to close the issue if merged, but you tell me.

[1]: https://github.com/NixOS/nixpkgs/pull/117881
[2]: https://github.com/NixOS/nixpkgs/pull/123188

**Comment by samuela** [comment]
I think we can close this now that @ninjin got `julia_16-bin` (https://github.com/NixOS/nixpkgs/pull/123188) landed...

**Comment by 7c6f434c** [comment]
Arguably no, because there seems to be an almost working source build that could be finished? Or maybe published as a draft PR and declared up for grabs.

**Comment by samuela** [comment]
Maybe we should edit the issue title to be for a source build then. I think it's fair to say we have Julia 1.6 packaged now, it's just that none of the Julia source builds are working.

**Comment by izzues** [comment]
Sorry if this is not the right place to ask, but how was I supposed to know that the package `julia_16-bin` exists? I searched for it on https://search.nixos.org/packages but no results were returned.

Thanks for your great work!

**Comment by samuela** [comment]
@izzues Hmm, that's a great question... I have no idea why it's not showing up in search.nixos.org. That seems like a bug with the site. I'm not sure how/where to report such bugs, but starting with a question on discourse.nixos.org is prob a good place to start.

I created https://nixos.wiki/wiki/Julia to help point users in the right direction, but getting search.nixos.org to show `julia_16-bin` is also essential.

**Comment by vcunat** [comment]
> Arguably no, because there seems to be an almost working source build that could be finished?

We seem to have source builds now.  For newer versions than 1.6.
