### ISSUE TITLE
Allow vim_configurable to disable X11

### ISSUE THREAD

**Issue by xunam** [NixOS/nixpkgs#116716]
The `vim_configurable` package hard-codes various X11 libraries as dependencies while making many other features optional, including GUIs. It would be nice to have an option to disable the X11 feature and the related `buildInputs`.

The use case I have in mind is installing a custom Vim on a remote server. Pulling X libraries, even without enabling a GUI, adds a few dozen megabytes for something essentially useless.

An approach is doing something like this:
```nix
vim_configurable.override {
  libX11 = null; libXext = null; libSM = null; libXpm = null;
  libXt = null; libXaw = null; libXau = null; libXmu = null; libICE = null;
  config.vim.gui = "none";
}
```
but it doesn't feel very clean...

Any thoughts from @lovek323 or @equirosa ?

**Comment by doronbehar** [comment]
I agree. It would have been nice if these X dependencies would have been added to `buildInputs` only if `gui` is `"gtk2"` or `"gtk3"`.

**Comment by xunam** [comment]
I'm all for testing new things and neovim is on my list. But according to `nix-tree`, the neovim package pulls 428MiB of dependencies, half of which for Ruby, the other half for both Python 3 and Python 2 (seriously?). Is there a way, by any chance, to configure neovim to avoid this bloat ?

**Comment by teto** [comment]
admittedly I've never tried to configure a mininmal version but one can unselect these ecosystems: https://github.com/teto/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/neovim/wrapper.nix#L18

**Comment by doronbehar** [comment]
See https://github.com/NixOS/nixpkgs/pull/117022 .
