### ISSUE TITLE
paperless: out-of-date / upstream archived

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixpkgs#116761]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `paperless`

current version: https://github.com/the-paperless-project/paperless
desired version: https://github.com/jonaswinkler/paperless-ng

###### Notify maintainers

maintainers: @erikarvstedt 

###### Note for maintainers

Please tag this issue in your PR.

The original project was archived and its author now suggests the linked project as replacement.

**Comment by mnajib** [comment]
need this package

**Comment by Flakebi** [comment]
I packaged paperless-ng in #123046.
