### ISSUE TITLE
packaging request: xfce4-screensaver

### ISSUE THREAD

**Issue by berbiche** [NixOS/nixpkgs#116795]
**Project description**

> Xfce4-screensaver is a screen saver and locker that aims to have simple, sane, secure defaults and be well integrated with the desktop.
> [...]. It has been tightly integrated with the Xfce desktop, utilizing Xfce libraries and the Xfconf configuration backend.

**Metadata**

* homepage URL: https://gitlab.xfce.org/apps/xfce4-screensaver, https://docs.xfce.org/apps/xfce4-screensaver/start
* source URL: https://gitlab.xfce.org/apps/xfce4-screensaver
* license: LGPL, GPL-2
* platforms: Linux

**Comment by berbiche** [comment]
Things to consider about the license: https://gitlab.xfce.org/apps/xfce4-screensaver/-/issues/71

**Comment by berbiche** [comment]
Still interested although I don't use xfce/x11 much anymore

**Comment by bobby285271** [comment]
Closing as we have this packaged in #165873
