### ISSUE TITLE
Package suggestion: letsencrypt

### ISSUE THREAD

**Issue by stites** [NixOS/nixpkgs#11688]
[Let's Encrypt just went public beta last week][1] and I was hoping that I could set up some certificates via my NixOS instance. I'm pretty new to Nix and am a little crunched for time today, so I figured I'd file an issue.

[1]:https://letsencrypt.org/2015/12/03/entering-public-beta.html

**Comment by jgillich** [comment]
There's `letsencrypt` and `simp_le` already (in unstable, at least). :)

**Comment by stites** [comment]
Cool! Thanks for the speedy response.
