### ISSUE TITLE
`git maintenance start` doesn't use `launchctl` on Darwin

### ISSUE THREAD

**Issue by evanrelf** [NixOS/nixpkgs#116961]
**Describe the bug**
The `git` package provided by Nixpkgs doesn't handle `git maintenance start` on Darwin properly.

The `git maintenance start` command attempts to modify the user's crontab to schedule regular maintenance tasks, but this doesn't work on Darwin:

> While macOS technically supports `cron`, using `crontab -e` requires elevated privileges and the executed process does not have a full user context. Without a full user context, Git and its credential helpers cannot access stored credentials, so some maintenance tasks are not functional.
>
> Instead, `git maintenance start` interacts with the `launchctl` tool, which is the recommended way to schedule timed jobs in macOS. Scheduling maintenance through `git maintenance (start|stop)` requires some `launchctl` features available only in macOS 10.11 or later.
>
> ...

From <https://git-scm.com/docs/git-maintenance>

**To Reproduce**
1. Install `pkgs.git` from a recent revision of Nixpkgs on a Darwin machine
2. Go into a random Git repository
3. Run `git maintenance start`

**Expected behavior**
Git exits without any error, indicating it started/scheduled the tasks successfully.

**Actual behavior**

```
λ git maintenance start
crontab: no crontab for evan
```

**Additional context**
After running into the error above, I installed Git from Homebrew via `brew install git`, and was able to successfully start/schedule the maintenance tasks.

After running `git maintenance start` with Git provided by Homebrew, the Git I got from Nixpkgs started working (`stop` and `start` both execute without any errors, in all the repositories I tried).

**Notify maintainers**
@primeos @peti @wmertens @globin

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-21.03pre264882.92c884dfd71"`
 - nixpkgs: `/Users/evan/.nix-profile/channels/default`
```

```
# Nixpkgs
λ ~/.nix-profile/bin/git --version
git version 2.30.0

# Homebrew
λ /usr/local/bin/git --version
git version 2.30.1
```

Maintainer information:
```yaml
attribute:
  - "git"
  - "gitAndTools.gitFull"
```

**Comment by n8henrie** [comment]
Seems to work now, @evanrelf do you think this can be closed?

```console
$ sw_vers
ProductName:            macOS
ProductVersion:         14.3.1
BuildVersion:           23D60
$ nix-info -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.3.0, macOS 14.3.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.19.3`
 - channels(n8henrie): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/64npyyxn3bb6cxciz12yigldfc2p9fh1-source`
```

**Comment by evanrelf** [comment]
Yup, seems to work now! 🎉 Thanks to whoever fixed it.
