### ISSUE TITLE
`mermaid-cli` deprecated—replace `mermaid-cli` with `mermaid`

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#116951]
As of mermaid v0.3.0, `mermaid-cli` is **deprecated** with functionality merged into mermaid core.

Deprecation notice available at: https://www.npmjs.com/package/mermaid-cli

I believe the correct course of action is to replace `mermaid-cli` in `nodePackages` with `mermaid`.

**Metadata**

* homepage URL: https://www.npmjs.com/package/mermaid
* source URL: https://github.com/mermaid-js/mermaid
* license: MIT
* platforms: Unix

**Comment by marsam** [comment]
we don't package `mermaid-cli`, we use [`@mermaid-js/mermaid-cli`](https://github.com/mermaid-js/mermaid-cli) which is still maintained
https://github.com/NixOS/nixpkgs/blob/e6ca7b6e5b222cbbd0c91289a78c1f59a47f946d/pkgs/development/node-packages/node-packages.json#L152

**Comment by matthew-piziak** [comment]
My mistake, thank you @marsam!
