### ISSUE TITLE
bakoma ttf not found

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#11696]
trying http://tarballs.nixos.org/bakoma-ttf.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
error: cannot download bakoma-ttf.tar.bz2 from any mirror
builder for ‘/nix/store/msyrlvfn359bsqgq88fz2qqb59kc8mn4-bakoma-ttf.tar.bz2.drv’ failed with exit code 1

**Comment by copumpkin** [comment]
cc @edolstra

**Comment by edolstra** [comment]
Fixed.
