### ISSUE TITLE
Mopidy fails to load extensions with additional dependencies

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#11706]
Mopidy fails to load extensions that have additional dependencies. `mopidy-spotify` fails because it depends on `pyspotify`:
```
mopidy[2776]: INFO     Disabled extension spotify: Dependency The 'pyspotify<1.999,>=1.9' distribution was not found and is required by the application not found
```

I guess this is because [only the extension path is added to PYTHONPATH](https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/nixos/modules/services/audio/mopidy.nix#L23) and not the path of any sub-dependencies, but I don't know much about Python.

**Comment by domenkozar** [comment]
I suggest using http://nixos.org/nixpkgs/manual/#ssec-python-build-env

**Comment by spwhitt** [comment]
I got mopidy-spotify working at home a couple days ago but haven't made a PR for the changes yet. I'll do that tonight (~8hrs from now)

**Comment by jgillich** [comment]
@spwhit That is great to hear :+1:

**Comment by spwhitt** [comment]
@jgillich Just ran into this problem by rebasing onto a more recent nixpkgs, I see what you're talking about now. I'm working around it for now by adding the extra dependencies to mopidy's package, but I'll look into @domenkozar 's suggestion if I find time..
