### ISSUE TITLE
Package Apple's shell_cmds project

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11707]
`fish` is currently using `hostname` from its environment on Darwin (see #11691). It should probably just build [the Mac OS `hostname` utility from `shell_cmds`](http://www.opensource.apple.com/source/shell_cmds/shell_cmds-118/hostname/hostname.c).

**Comment by rasendubi** [comment]
(triage) does `hostname` from `inetutils` work on Mac? Any volunteer to package `hostname` from `shell_cmds`?

**Comment by rasendubi** [comment]
Answer to myself: `inetutils` is broken on Darwin.
