### ISSUE TITLE
git-annex assistant

### ISSUE THREAD

**Issue by ellis** [NixOS/nixpkgs#11708]
To sync data between my offices, I used git-annex extensively.  I installed nixos 15.09 recently, and the "assistant" part of git-annex (which does the syncing) no longer appears to be available.  In nixpkgs, there a note about using git-annex-with-assistant (or something similar), but it didn't look to be accessible to me.

Anything reasonably quick I can do to get back my beloved assistant?

**Comment by peti** [comment]
The command `git annex assistant` seems to work just fine after installing `nix-env -iA gitAndTools.gitAnnex`. What makes you say that the Assistant would be missing? How did you install `git-annex`?

**Comment by ellis** [comment]
my /etc/nixos/configuration.nix installs gitAndTools.gitAnnex as a
systemPackage.  These are the relevant files in /nix/store:

    /nix/store/rvm17dxhjli1j8wrcc3r4cj1l9bhjljk-git-annex-5.20151102.1/

/nix/store/0nm72kfxywfv3qy77a6ixj03m170bgyq-git-annex-5.20151102.1.tar.gz.drv
    /nix/store/s46h63rfipg1ma4j3qq1hhf7mdw8jqfm-git-annex-5.20151102.1.drv

Here's what the command line says:

    % git annex assistant --autostart
    Invalid argument `assistant'

This is on Nixos 15.09.  Any ideas?

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/ffd10ac482e24b76d2d7b6f7f172f36e4895a541.

**Comment by ellis** [comment]
Thanks!
