### ISSUE TITLE
.pad folder when making torrents in qbittorrent-4.3.3 (unstable)

### ISSUE THREAD

**Issue by idcretard** [NixOS/nixpkgs#117130]
**Description**
A .pad folder is created when making torrents using qbittorrent

**To Reproduce**
1. Switch to the unstable branch
2. Install qbittorrent (It should be 4.3.3)
3. Go to Tools -> Torrent Creator
4. Create a torrent

**Expected behavior**
A .pad folder should NOT be created

**Screenshots**
![](https://ptpimg.me/sh82u5.png)

**Additional context**
This really creates problems when creating torrents for private trackers as they render such torrents invalid

**Notify maintainers**
@Anton-Latukha 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 21.05pre276515.1f77a4c8c74 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre276515.1f77a4c8c74, nixpkgs-21.05pre276933.fcab19deb78"`
 - channels(otaku619): `"nixos-21.05pre277486.f5e8bdd07d1, nixos-old-20.03.3325.462c6fe4b11, nixos-stable-20.09.3545.66f4dc4fd1b, nixpkgs-21.05pre277683.4e0d3868c67"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Anton-Latukha** [comment]
I'm tracking `qbittorent` releases and changelogs, somehow not remember anything about what `.pad` is.

Would look into it.

**Comment by idcretard** [comment]
Apparently the 'optimise alignment' option has been removed since 4.3.1 I think and turning it on causes it. The new 'Torrent Type' option defaults to 'Hybrid' resulting in the creation of these files, setting it to V1 prevents creation of such files. Not a nixpkgs issue closing it
