### ISSUE TITLE
OnlyOffice

### ISSUE THREAD

**Issue by dmrzh** [NixOS/nixpkgs#117109]
**Project description**   collaborative online office suite 
_describe the project a little_  free collaborative online office suite comprising viewers and editors for texts, spreadsheets and presentations,

**Metadata**

* homepage URL: https://www.onlyoffice.com/
* source URL: https://github.com/ONLYOFFICE/DocumentServer
* license:  AGPL v3 
* platforms: linux ...

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/116343
