### ISSUE TITLE
`gtk-doc` fails to cross-compile for aarch64 on `nixos-unstable`

### ISSUE THREAD

**Issue by rajivr** [NixOS/nixpkgs#117181]
**Describe the bug**

`glib` fails to cross-compile for commit  `f5e8bdd07d1a`. (I am trying to use `mobile-nixos` cache for the toolchain).

**To Reproduce**

This [gist](https://gist.github.com/rajivr/36901798d440fd372db06014f9c322db) has `flake.nix`, `flake.lock` and `cross-hacks.nix` needed to reproduce the issue.

Running `nix build` with the above files in a directory, will reproduce the build failure, with the following error.

```
error: --- Error --- nix-daemon
builder for '/nix/store/1fhg4sfqix16p9w16b4gsf93mh0wg0nz-gtk-doc-1.33.2-aarch64-unknown-linux-gnu.drv' failed with exit code 2; last 10 log lines:                                                                             
      p, stdout, stderr = mesonlib.Popen_safe(cmd)
    File "/nix/store/3hmi5hcpvnanxxkwqbi1vxiil2b4ba0p-meson-0.57.1/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1320, in Popen_safe
      p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
    File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/subprocess.py", line 1596, in _execute_child
      self._posix_spawn(args, executable, env, restore_signals,
    File "/nix/store/v3bj7jrns4sk6yj2rp30p6v2l7p707az-python3-3.8.8/lib/python3.8/subprocess.py", line 1547, in _posix_spawn
      self.pid = os.posix_spawn(executable, args, env, **kwargs)
  OSError: [Errno 8] Exec format error: '/nix/store/l2chfxk5ci12hg171fxk11y55kj4znfg-python3-3.8.8-aarch64-unknown-linux-gnu/bin/python3'
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/8dwpqd7i970liw23hm41gyrf3pjf0bzv-glib-2.66.4-aarch64-unknown-linux-gnu.drv' failed to build                                                                                                         
```

**Notify maintainers**

@lovek323 @worldofpeace @Mic92 @samueldr

**Comment by samueldr** [comment]
cc @Ericson2314 

Likely to be another issue made discovered by the makeWrapper change, since it's an aarch64 bash being called in a cross-compilation.

**Comment by matthewmazzanti** [comment]
Getting the same error on staging.

Doing some digging, looks like they import python here in the meson build: https://gitlab.gnome.org/GNOME/gtk-doc/-/blob/master/meson.build#L10. The build looks like it dies right after it finds the aarch64 python so I assume thats the root cause.

Stepping back, I was able to get glib to cross compile by removing gtk-doc from the build inputs while cross-compiling. Not sure if thats the correct approach, however.

**Comment by Mindavi** [comment]
This was introduced by adding gtk-doc as buildInput (which was needed, so is correct) here: 884a83cacb69.

Doing this:

```patch
commit 5e82a07be0b1e14ee62d3d3e6c6648c94b096563
Author: Rick van Schijndel <rol3517@gmail.com>
Date:   Fri Mar 19 11:37:38 2021 +0100

    gtk-doc: fix cross-compilation

diff --git a/pkgs/development/tools/documentation/gtk-doc/default.nix b/pkgs/development/tools/documentation/gtk-doc/default.nix
index e74a6b9c3c6..b9a70990542 100644
--- a/pkgs/development/tools/documentation/gtk-doc/default.nix
+++ b/pkgs/development/tools/documentation/gtk-doc/default.nix
@@ -32,6 +32,11 @@ python3.pkgs.buildPythonApplication rec {
     passthru.respect_xml_catalog_files_var_patch
   ];
 
+  depsBuildBuild = [
+    python3
+    pkg-config
+  ];
+
   nativeBuildInputs = [
     pkg-config
     gettext
```

helps, but I'm pretty sure that it's just a bandaid, since I've seen errors down the line when gtk-doc is actually used (not in glib though). So this requires some looking into.
