### ISSUE TITLE
dnsmasq error: cannot open or create lease file

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#11718]
Pretty standard config:

```
  services.dnsmasq = {
    enable = true;
    servers = [ "8.8.8.8" "8.8.4.4" ];
    extraConfig = ''
      interface=wlp4s0,enp2s0,enp3s0
      bind-interfaces
      dhcp-range=192.168.1.10,192.168.1.254,24h
      dhcp-range=192.168.2.10,192.168.2.254,24h
      dhcp-range=192.168.3.10,192.168.3.254,24h
    '';
  };
```
```
Dec 14 19:51:04 apu systemd[1]: Starting Dnsmasq Daemon...
Dec 14 19:51:04 apu dnsmasq-pre-start[11323]: dnsmasq: syntax check OK.
Dec 14 19:51:04 apu dnsmasq[11329]: cannot open or create lease file /var/lib/misc/dnsmasq.leases: No such file or directory
Dec 14 19:51:04 apu dnsmasq[11329]: FAILED to start up
Dec 14 19:51:04 apu dnsmasq[11329]: dnsmasq: cannot open or create lease file /var/lib/misc/dnsmasq.leases: No such file or directory
Dec 14 19:51:04 apu systemd[1]: dnsmasq.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 14 19:51:04 apu systemd[1]: Failed to start Dnsmasq Daemon.
Dec 14 19:51:04 apu systemd[1]: dnsmasq.service: Unit entered failed state.
Dec 14 19:51:04 apu systemd[1]: dnsmasq.service: Failed with result 'exit-code'.

```

**Comment by domenkozar** [comment]
also note https://github.com/NixOS/nixpkgs/issues/10101

**Comment by jgillich** [comment]
Hah, thank you! I actually read that issue already, but I missed that ISC dhcpd isn't affected but dnsmasq is. I have a fix for this issue, but that won't be of much use until #10101 is fixed.

**Comment by jgillich** [comment]
I disabled `checkReversePath` and patched dnsmasq to use `/var/lib/dnsmasq/dnsmasq.leases`, but it still doesn't respond to DHCP requests. Nothing in the logs at all, so weird..

**Comment by fpletz** [comment]
Out of curiosity, does it work if you add the interfaces to `networking.firewall.trustedInterfaces`?

**Comment by jgillich** [comment]
All internal interfaces are in `trustedInterfaces`. The ISC dhcpd works fine even when they're not trusted, but I added them to get the DNS part of dnsmasq working.

**Comment by domenkozar** [comment]
I think dnsmasq changed directory location so we have to create the supporting directory.

**Comment by jgillich** [comment]
I changed a few other things and now it responds to dhcp requests..oh well, whatever.
