### ISSUE TITLE
Ansible package marked as "broken" on nixos

### ISSUE THREAD

**Issue by avnik** [NixOS/nixpkgs#11722]
```
error: Package ‘python2.7-ansible-1.9.4’ in ‘/home/avn/nixos/nixpkgs/pkgs/top-level/python-packages.nix:607’ is not supported on ‘x86_64-linux’, refusing to evaluate.
```

**Comment by domenkozar** [comment]
@FRidh

**Comment by FRidh** [comment]
ahh, 
`platforms = with platforms; [ linux darwin] `
should be
`platforms = with platforms; linux ++ darwin;`

**Comment by FRidh** [comment]
Packages `ansible`, `ansible2` and `mygpoclient` in `python-packages` need this fix

**Comment by FRidh** [comment]
I do find it odd that this wasn't enforced on me when building with the 'wrong' platforms.

**Comment by domenkozar** [comment]
`meta` is not checked when doing `nix-build`
