### ISSUE TITLE
pythonPackages.arrow: major version bump to version 1.0.3

### ISSUE THREAD

**Issue by oxzi** [NixOS/nixpkgs#117227]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: arrow

current version: 0.17.0
desired version: 1.0.3

###### Notify maintainers

maintainers: @thoughtpolice 

###### Note for maintainers

The `arrow` Python package was recently bumped to the new major version one. Due to multiple packages depending on it - and transitive dependencies - just bumping the package version results in a huge amount of failed builds. I tried this in #116831 because the new arrow version is a new dependency for watson. However, this does not went as planed.

Thus, I would like to notify the maintainer, @thoughtpolice. Thanks a lot for your work.

Please tag this issue in your PR.

**Comment by fabaff** [comment]
Was updated in https://github.com/NixOS/nixpkgs/commit/3ec31ffe8ca3d650a071b66321c4b0870435717f
