### ISSUE TITLE
Podgrab self-hosted podcast manager package & module

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#117284]
**Project description**
Podgrab is a is a self-hosted podcast manager which automatically downloads latest podcast episodes. It is a light-weight application built using GO.

It works best if you already know which podcasts you want to monitor. However there is a podcast search system powered by iTunes built into Podgrab

**Metadata**

* homepage URL: https://github.com/akhilrex/podgrab/
* source URL: https://github.com/akhilrex/podgrab/
* license: gpl3 (I think, see [here](https://github.com/akhilrex/podgrab/issues/68) about a typo)
* platforms: unix, I think, it's a Go package

**Comment by Ambroisie** [comment]
If I have some time this week-end, I might tackle this issue myself. The repo has `go.mod` and `go.sum` files so it should be pretty easy for a first contribution :-)

**Comment by Ambroisie** [comment]
So I'm having issues with the package's tests, I have opened an upstream issue to discuss it.
