### ISSUE TITLE
Steam version 1.0.0.68 not available from steam servers (package broken)

### ISSUE THREAD

**Issue by mixmixmix** [NixOS/nixpkgs#117347]
In current master We are building version 1.0.0.68
https://github.com/NixOS/nixpkgs/blob/f5e8bdd07d1afaabf6b37afc5497b1e498b8046f/pkgs/games/steam/steam.nix#L5
using a fetch link:
https://github.com/NixOS/nixpkgs/blob/f5e8bdd07d1afaabf6b37afc5497b1e498b8046f/pkgs/games/steam/steam.nix#L12
However only 61 and 69 are available currently on that server

```
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /nix/store/rxkghln0km9axapv94iz3pcsln6ricms-gnugrep-3.4/bin/grep
checking for egrep... /nix/store/rxkghln0km9axapv94iz3pcsln6ricms-gnugrep-3.4/bin/grep -E
checking for ANSI C header files... yes
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
error: cannot download steam_1.0.0.68.tar.gz from any mirror
builder for '/nix/store/mdqdm46dn5srkbpq7nj5b3myw5ibsmx7-steam_1.0.0.68.tar.gz.drv' failed with exit code 1
cannot build derivation '/nix/store/1dfpdgnjx23iar1misrcpnn0f8y05ja0-steam-original-1.0.0.68.drv': 1 dependencies couldn't be built
building '/nix/store/4y9jdgyccpq35v66zmkh4m9mn7icp11f-system-generators.drv'...
cannot build derivation '/nix/store/484razp2idrn3gb3kdg6lki1jlh4wpph-steam.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/996p5iw6w1zayq1zpavcq5ndfxnsr4mv-system-path.drv': 1 dependencies couldn't be built
building '/nix/store/m0gk66q6pmf4d4b0nd72najf8jp7wn4k-system-shutdown.drv'...
building '/nix/store/gx2nm1z7r5a3yfm7aagzv6hrply3gnf4-udev-rules.drv'...
building '/nix/store/km9fp79wbvmfcbrg0bvc5669cjy7y42a-unit-NetworkManager-dispatcher.service.drv'...
building '/nix/store/rxlb77v3xjrpxc3vhha459fsm1zyi71g-unit-NetworkManager-wait-online.service.drv'...
building '/nix/store/vgh3ryvx97j4qwx0qy2fwhqh0vhkhmvs-unit-NetworkManager.service.drv'...
building '/nix/store/af0h4aymr19ysrby9q7rcnynyjjdlcvi-unit-acpid.service.drv'...
cannot build derivation '/nix/store/mgsyp4s55qrxa21r02spvkkldnhj0h26-nixos-system-badger-20.09.3549.6109ba4f307.drv': 1 dependencies couldn't be built
error: build of '/nix/store/mgsyp4s55qrxa21r02spvkkldnhj0h26-nixos-system-badger-20.09.3549.6109ba4f307.drv' failed
```

I believe @jonringer you did last update of the version.

**Comment by OPNA2608** [comment]
Current master has 1.0.0.69.

https://github.com/NixOS/nixpkgs/blob/e31c3509c506dd75149d468e6966810dd9989906/pkgs/games/steam/steam.nix#L5

The bump to 1.0.0.69 happened 3 days ago, it needs some time to reach the unstable channel (which I assume is [what you're looking at](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/steam/steam.nix), not [master](https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/steam/steam.nix)).

**Comment by mixmixmix** [comment]
Ah thanks! I understand, I'm a bit new to it, forgot to check if it has been done in master :O

**Comment by OPNA2608** [comment]
No problem! I hit the same problem last night while trying to get Proton's runtime working. The unstable channel will advance on its own eventually, until then you can build off of the git master branch or carry [the bump commit](https://github.com/NixOS/nixpkgs/commit/826c65988b0602885312d62b74b297019e27e352) as an overlay.
