### ISSUE TITLE
phc-intel fails to build

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#11733]
[phc-intel](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/phc-intel/default.nix) fails to build because the source is not found.

```
trying http://www.linux-phc.org/forum/download/file.php?id=167
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
error: cannot download phc-intel-pack-rev18.tar.bz2 from any mirror
<3>builder for ‘/...-phc-intel-pack-rev18.tar.bz2.drv’ failed with exit code 1
```

[Hydra logs](http://hydra.nixos.org/build/28546452/nixlog/10)

Upstream [archive page](http://www.linux-phc.org/forum/viewtopic.php?f=13&t=2)

cc maintainer @nckx

**Comment by nckx** [comment]
Not sure where you found that outdated 'archive page'? The correct thread is linked in `meta.downloadPage`, though I can't fault anyone for getting lost in those forums

There is in fact a [new release](http://www.linux-phc.org/forum/viewtopic.php?f=7&t=267&start=30#p7745) available. I'll bump, test and push it in a few hours if all goes well.

Thanks.

**Comment by ericsagnes** [comment]
Thanks! (and thanks for pointing `meta.downloadPage` too, I overlooked it)

**Comment by vcunat** [comment]
I wonder how it's best to solve this error on release-15.09.

**Comment by nckx** [comment]
Mirror it ourselves, I suppose. If that's allowed. I always assumed t.n.o was for Important or Core Packages, which this definitely isn't.

If it would be possible, I think I have a copy of the old tarball. Can't check the hash right now.

**Comment by nckx** [comment]
Maybe [this](https://github.com/loxdegio/SystemdZramService/blob/ea04843dc87ed7a3e57959ffee064b77822ad041/phc/phc-intel-pack-rev18.tar.bz2) checks out.

**Comment by vcunat** [comment]
> Maybe this checks out.

It has the same name but a different hash. That's suspicious.
