### ISSUE TITLE
Firewall service fails to start at boot when docker is enabled

### ISSUE THREAD

**Issue by Kazimazi** [NixOS/nixpkgs#117380]
**Describe the bug**
Firewall is enabled, but it can't start at boot time, afterwards I can **start** it manually.
```
$ systemctl status firewall
● firewall.service - Firewall
     Loaded: loaded (/nix/store/f4vkvafqx48clcm3rmzg54yy48xcrnlv-unit-firewall.service/firewall.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-03-23 04:02:43 CET; 13h ago
    Process: 799 ExecStart=firewall-start (code=exited, status=4)
   Main PID: 799 (code=exited, status=4)
         IP: 0B in, 0B out
        CPU: 58ms

Mar 23 04:02:41 amdboi systemd[1]: Starting Firewall...
Mar 23 04:02:43 amdboi firewall-start[1657]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Mar 23 04:02:43 amdboi systemd[1]: firewall.service: Main process exited, code=exited, status=4/NOPERMISSION
Mar 23 04:02:43 amdboi systemd[1]: firewall.service: Failed with result 'exit-code'.
Mar 23 04:02:43 amdboi systemd[1]: Failed to start Firewall.

```

I will test stuff and gradually add more info.

**Additional context**
This issue only happens as long as I have `virtualisation.docker.enable = true;` in my config.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/b0v7njdsxpyn91j0hp1kbjw283ma3x2l-nix-info
copying path '/nix/store/b0v7njdsxpyn91j0hp1kbjw283ma3x2l-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.7, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(kazimazi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: services.networking.firewall virtualisation.docker
```

Edit 1: added context about docker.

**Comment by primeos** [comment]
I guess it would indeed be best to use the `-w` option in the NixOS module (`Another app is currently holding the xtables lock. Perhaps you want to use the -w option?`).

From `man iptables`:
>        -w, --wait [seconds]
>              Wait for the xtables lock.  To prevent multiple instances of the program from running concurrently, an attempt will be made to obtain an exclusive lock at launch.  By default, the program will
>              exit if the lock cannot be obtained.  This option will make the program wait (indefinitely or for optional seconds) until the exclusive lock can be obtained.

Not sure what the best limit would be but I guess we shouldn't give it more than 60 seconds (maybe 15 or even 30 seconds? - we could try to start with a short limit and still increase it if necessary or even make it configurable).

[The current NixOS module](https://github.com/NixOS/nixpkgs/blob/7865db274bffa497feef0c07aa7d7ace86734561/nixos/modules/services/networking/firewall.nix)

(See also my second suggestion in https://github.com/NixOS/nixpkgs/issues/21974#issue-201614937 (but ignore the rest, unfortunately I never got around to finishing this)).

**Comment by Kazimazi** [comment]
can't reproduce anymore
