### ISSUE TITLE
luksroot: blockers for 21.05

### ISSUE THREAD

**Issue by hugolgst** [NixOS/nixpkgs#117449]
- [ ] https://github.com/NixOS/nixpkgs/pull/107038 (Most important)

The other two are in addition to the first one
- [ ] https://github.com/NixOS/nixpkgs/pull/115832
- [ ] https://github.com/NixOS/nixpkgs/pull/115451

**Comment by jonringer** [comment]
Has there been any progress?

**Comment by hugolgst** [comment]
The PRs are waiting I guess

**Comment by dasJ** [comment]
Is this issue still relevant? The 21.05 release seems to be released without these PRs merged so I guess we don't need this tracking issue anymore and can keep the PRs?
