### ISSUE TITLE
soapui: 5.5.0 does not work with jdk15

### ISSUE THREAD

**Issue by jbalme** [NixOS/nixpkgs#117477]
**Describe the bug**
The version of SoapUI provided by nixpkgs unstable (5.5.0) does not run against jdk15, the new default.

**To Reproduce**
1. `nix-shell -p soapui --run soapui` 

**Expected behavior**
SoapUI runs.

**Actual behavior**
SoapUI hangs on the splash screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/2133510/112330294-47a25e00-8c8e-11eb-8a8f-93642f64d01b.png)

**Additional context**
Changing the derivation to use JDK8 would be trivial, but it might be preferable to finish and merge #93433 instead.

Upstream bug: https://github.com/SmartBear/soapui/issues/487

**Notify maintainers**

@Gerschtli 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.24, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `"nixos-21.05pre275232.29b0d4d0b60"`
 - channels(user): `"nixos-21.05pre276515.1f77a4c8c74"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ soapui ]
# a list of nixos modules affected by the problem
module: []
```

**Comment by jbalme** [comment]
Workaround while this is open: `nix-shell -p 'soapui.override { jdk = jdk8; maven = maven.override { jdk = jdk8; }; }'`

**Comment by asbachb** [comment]
Seems that SoapUI currently just support up to java 12: https://www.soapui.org/downloads/latest-release/release-notes/

> Support for openJDK 12.
