### ISSUE TITLE
Failed to open fglrx_dri.so

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#11740]
After installing the AMD Catalyst driver (fglrx) in NixOS 15.09 by setting `services.xserver.videoDrivers = [ "ati_unfree" ];`, direct rendering is not enabled. Details are:

```
$ LIBGL_DEBUG=verbose glxinfo | grep direct
libGL: AtiGetClientDriverName: 15.20.3 fglrx (screen 0)
libGL error: OpenDriver: failed to open /usr/X11R6/lib64/modules/dri/fglrx_dri.so, error[/usr/X11R6/lib64/modules/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
libGL error: OpenDriver: failed to open /usr/lib64/dri/fglrx_dri.so, error[/usr/lib64/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
libGL error: OpenDriver: failed to open /run/opengl-driver/lib/dri/fglrx_dri.so, error[libstdc++.so.6: cannot open shared object file: No such file or directory]
libGL error: OpenDriver: failed to open /usr/lib/dri/fglrx_dri.so, error[/usr/lib/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
libGL error: OpenDriver: failed to open /usr/X11R6/lib32/modules/dri/fglrx_dri.so, error[/usr/X11R6/lib32/modules/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
libGL error: OpenDriver: failed to open /usr/lib32/dri/fglrx_dri.so, error[/usr/lib32/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
libGL error: dlopen fglrx_dri.so failed
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
```

The [AMD Catalyst Arch wiki section for this "failed to open fglrx_dri.so" error](https://wiki.archlinux.org/index.php/AMD_Catalyst#Failed_to_open_fglrx_dri.so) says to create symlinks for the missing requested paths, which I suppose might be a workaround, but really shouldn't Nix be taking care of this?

On the other hand, `/run/opengl-driver/lib/dri/fglrx_dri.so` does actually exist, so maybe the error is with finding `libstdc++.so.6`?

**Comment by a1russell** [comment]
Pinging @nathanielbaxter, @jgeerds, @vcunat, and @offlinehacker for involvement in #3989 and #4185.

Could the issue be at https://github.com/NixOS/nixpkgs/blob/1a86bf8aae151c40747f4e47e791356ff0084e2b/nixos/modules/hardware/video/ati.nix#L22 where `libPath` is set?

Setting `environment.extraInit = pkgs.lib.mkIf (videoDriver == "ati_unfree") "export LD_LIBRARY_PATH=${pkgs.gcc_multi.cc}/lib:${pkgs.gcc_multi.cc}/lib64:$LD_LIBRARY_PATH'';` and creating the `/usr/X11R6/lib64/modules/dri` -> `/run/opengl-driver/lib/dri` symlink causes `glxinfo` to segfault but gets rid of the above errors.

**Comment by vcunat** [comment]
I know little about the proprietary ATI drivers in particular. From what you write, there seem to be some ugly hacks done, perhaps prone to break. You can test `ldd /run/opengl-driver/lib/dri/fglrx_dri.so` to find if that file links correctly at least.

**Comment by nathanielbaxter** [comment]
I suggest having a look at the [driver package](https://github.com/NixOS/nixpkgs/tree/master/pkgs/os-specific/linux/ati-drivers) if you haven't already, more likely to be an issue there (where the ugly hacks are) than in the module. 

I haven't used these drivers for over a year, so I'm unsure what state they're in at the moment, last update was made by @dfoxfranke

**Comment by a1russell** [comment]
@vcunat 
```
$ ldd /run/opengl-driver/lib/dri/fglrx_dri.so
	linux-vdso.so.1 (0x00007ffe240e1000)
	libstdc++.so.6 => not found
	libpthread.so.0 => /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/libpthread.so.0 (0x00007ffa6f4aa000)
	librt.so.1 => /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/librt.so.1 (0x00007ffa6f2a2000)
	libdl.so.2 => /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/libdl.so.2 (0x00007ffa6f09e000)
	libm.so.6 => /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/libm.so.6 (0x00007ffa6ed9b000)
	libgcc_s.so.1 => /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/libgcc_s.so.1 (0x00007ffa6eb85000)
	libXext.so.6 => /run/opengl-driver/lib/libXext.so.6 (0x00007ffa6e973000)
	libX11.so.6 => not found
	libc.so.6 => /nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib/libc.so.6 (0x00007ffa6e5d3000)
	/nix/store/npfsi1d9ka8zwnxzn3sr08hbwvpapyk7-glibc-2.21/lib64/ld-linux-x86-64.so.2 (0x00007ffa71f27000)
	libX11.so.6 => /nix/store/cwzl5vyl3lqzilh4hklff0h8zh3c77w4-libX11-1.6.3/lib/libX11.so.6 (0x00007ffa6e296000)
	libxcb.so.1 => /nix/store/dfwj9b6vb2g65asg681yw2w8knpmlqq4-libxcb-1.11/lib/libxcb.so.1 (0x00007ffa6e078000)
	libXau.so.6 => /nix/store/p408ns8dn0cfi4z4fzd6f10b9pvlfhss-libXau-1.0.8/lib/libXau.so.6 (0x00007ffa6de75000)
	libXdmcp.so.6 => /nix/store/xm4jqqq9m2nb9mczvv02z1lsyj225kvf-libXdmcp-1.1.2/lib/libXdmcp.so.6 (0x00007ffa6dc70000)
```

@nathanielbaxter Thanks for pointing me to the driver package. That does seem like it would be more likely what needs to be updated.

**Comment by vcunat** [comment]
Then I think the best step is to use patchelf to extend RPATH so that it finds those libraries, probably from packages `stdenv.cc.cc` and `xorg.libX11`.

**Comment by nathanielbaxter** [comment]
The hacks that you are probably looking for are [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/ati-drivers/builder.sh#L194-L230); using sed to replace paths in binary files is ugly but such is life.

As vcunat said you may need to run patchelf on "$out/lib/dri/fglrx_dri.so" and/or other libs provided by ati, patchelf is already used in builder.sh to fix references to libstdc++ for other libs.

**Comment by a1russell** [comment]
I did create a pull request with my changes at #11817. As I mention there, I am still getting the segfault. Would you mind please helping me? I know little about driver issues.

**Comment by a1russell** [comment]
Is this related to #8676?

**Comment by heydojo** [comment]
/nix/store/HASHPATH/ati-drivers-15.7/lib/fglrx/switchlibglx
```
Usage:
switchlibglx   amd|intel|query
amd:   switches to the AMD version of libglx.so .
intel: switches to the open-source version of libglx.so .
```

FTW we should delete or adapt the scripts in that directory because they won't work as is in nixos.
glxinfo is for when using the open-source version of libglx.so.
fglrxinfo is for when using the AMD version of libglx.so.
The nixos package definitely does not use the open-source version of libglx.so by default.
In order to fix glxinfo to work as OP expects, the open-source version of libglx.so needs to be re-built or patched to look at the correct paths if ati-drivers is installed.
As we don't use the open-source version of libglx.so in ati-drivers - glxinfo failing is a non-issue unless the option to use the open-source version of libglx.so is added to ati-drivers.

What this report did expose is that in ati-drivers there are missing library paths to libstdc++.so.6 and that there is also an empty entry pointing to libX11.so.6.
Fixing those two issue likely solves any other issues people (like me) were having with ati-drivers.

**Comment by a1russell** [comment]
That's super confusing to me. Shouldn't `glxinfo`, and anything else, use the unfree `libglx.so` when that is the one that is installed? Does NixOS have different packages bypassing the driver that's installed and using whatever driver they choose?

**Comment by heydojo** [comment]
libglx.so is part of the opengl implementation. The open source implementation named mesa is not feature complete. That is to say that it does not fully support all current opengl standards. It is on going work and is progressing.
AMD cards support opengl extensions which are proprietary which are not part of the current opengl standards so AMD bundle libglx.so with their driver which supports their own proprietary opengl extensions (which are not part of the opengl specification) and may (or may not) include feature completeness for existing opengl standards which are not complete in mesa.
So it is better for catalyst to not use libglx.so provided by mesa if you want to use AMD supported opengl feature x or proprietary extension x which is provided by the opengl library AMD have bundled with their driver.

This relates to glxinfo because glxinfo is a tool to look at opengl information supported by a driver. Depending upon whether the driver uses libglx.so from AMD or not will depend upon what is returned by the program. switchlibglx is supposed to enable a user to switch between the driver using mesa opengl or the AMD bundled opengl. In it's current form it will not work in nixos.

glxinfo not working does not effect direct rendering. glxinfo only reports that direct rendering is not enabled because it cannot probe to find out.
clinfo from the AMD sdk is actually how you check the AMD catalyst driver. I haven't tried it although it has been packaged.

nixpkgs/pkgs/tools/graphics/glxinfo/ needs to be patched using patchelf or compiled so that the paths to the libraries are correct should ati-drivers be installed (and I suspect also the non free nvidia drivers also) in order that it works should a non-free driver be installed.

**Comment by a1russell** [comment]
Thanks @heydojo for the explanation. Some of that was already clear to me, but I think what I am still having trouble understanding is why any application, `glxinfo` or not, would need to be patched based on what driver is installed. It may end up to be the correct solution to simply patch it, but how would we know that `glxinfo` is the only app not seeing the correct library paths?

I have at least one other app not working correctly when I use unfree Catalyst, so I'm concerned this is a systemic problem.

Shouldn't every app, including `glxinfo`, be using whatever is in `/run/opengl-driver` as the driver?

**Comment by heydojo** [comment]
>Why any application, glxinfo or not, would need to be patched based on what driver is installed?

Purity in Nixos. When glxinfo is built it cannot see ati-drivers and does not know that ati-drivers are installed (should it need to.)
In your debug you can see glxinfo is looking for /usr/X11R6/lib64/modules/dri/fglrx_dri.so and that path is clearly wrong. The root of that problem lies either with glxinfo or the opengl library.

>But how would we know that glxinfo is the only app not seeing the correct library paths?

You can test, use ldd to check paths and run strace on programs.

>I have at least one other app not working correctly when I use unfree Catalyst, so I'm concerned this is a systemic problem.

Which app is not working? You have one other app not working or you have more than one not working? Maybe this is a systemic problem. It wouldn't be a reason to be concerned.

>Shouldn't every app, including glxinfo, be using whatever is in /run/opengl-driver as the driver?

I don't understand. Graphical applications talk to the xserver, usually using a toolkit library and the xserver handles the driver.

**Comment by a1russell** [comment]
> When glxinfo is built it cannot see ati-drivers and does not know that ati-drivers are installed
If `glxinfo` relies on drivers to work, I do think it should know about the drivers that are installed when it is built, at least if I understand the problem correctly. If this isn't the case, `glxinfo` ceases to have a purpose.

> use ldd to check paths and run strace on programs
Seems like an overwhelmingly large task.

> Which app is not working?
HipChat, that I know of so far...

> Maybe this is a systemic problem. It wouldn't be a reason to be concerned.
So far NixOS has been the most painful distro I have used in terms of configuration. I am still new to it, and I haven't given up because I have the ability to contribute, and I think the core idea is good. However, if I can't convince myself that installing an application will guarantee that the application will work, including using the correct graphic driver, I will probably move to another distro.

> I don't understand. Graphical applications talk to the xserver, usually using a toolkit library and the xserver handles the driver.
If you don't understand, imagine how I must feel. You are saying only the xserver needs to know about the driver? Why does the xserver not handle things for glxinfo, if you are correct? Why is that an exception? How many exceptions are there?

**Comment by heydojo** [comment]
>Seems like an overwhelmingly large task.

Welcome to the world of developing nix expressions where every path should be checked for purity. :)

>So far NixOS has been the most painful distro I have used in terms of configuration.

But it is improving and has huge potential. I was a distro shuffler for about two years. Then I dug in, read documentation, studied and gained enough skills to get by.

>Why does the xserver not handle things for glxinfo

If you look at the builder for glxinfo you will see that it is a small stand alone program. Look at the source code for glxinfo if you want to understand how it works.

**Comment by vcunat** [comment]
I don't understand what's not clear about libglx; I believe the state is this:

our X server has its own libglx implementation, and in addition it is set up to search for modules in `/run/opengl-driver/lib/xorg/modules/extensions` where the proprietary drivers are supposed to install their libglx versions. It is nixos who does the switching. (Therefore you're correct that fglrx switching script would better not be installed.)

**Comment by a1russell** [comment]
> I don't understand what's not clear about libglx

I don't have the background/understanding of how any given app (including `glxinfo`) interacts with the graphics drivers. I'll try to again re-state my current understanding and my outstanding questions.

I have gathered that libglx is a part of the graphics driver "suite", there there are conflicting versions of it, and that it's up to NixOS to resolve that conflict.

I'm not sure if libglx is special, but it seems to me that for any app that needs any library belonging to the graphics driver, Nix should make the appropriate connection. Note that it's not clear to me precisely by what means this "connection" should be made, whether it takes the form of LD_LIBRARY_PATH, patchelf, or something else.

The specific case in question for this issue, which has not been answered in a way that I can understand, is why the app `glxinfo` does not use the unfree ATI driver (fglrx) when it is installed. If libglx is a relevant library to glxinfo that is a part of the fglrx driver, and NixOS is responsible for the "switching", what needs to happen to set things right? And also important to me: can it be solved in a way that also ensures other applications do not have this problem?

**Comment by vcunat** [comment]
I believe this GPU driver switching works fine in general on NixOS. I'm using the proprietary nvidia drivers for years, even for various heavier use cases (steam and other games). The glxinfo+fglrx breakage may well be unrelated to this directly, IMHO.

**Comment by a1russell** [comment]
Thanks @vcunat. Knowing that will at least keep me from going down a very scary rabbit-hole.

**Comment by ocharles** [comment]
I don't think the `glxinfo` problem is entirely unrelated. I now have R7 370, and if I try and run my own personal SDL2 projects:

```
Preprocessing executable 'ssao-example' for ssao-example-0.1.0.0...
Running ssao-example...
libGL: AtiGetClientDriverName: 15.20.3 fglrx (screen 0)
libGL error: OpenDriver: failed to open /usr/X11R6/lib64/modules/dri/fglrx_dri.so, error[/usr/X11R6/lib64/modules/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
libGL error: OpenDriver: failed to open /usr/lib64/dri/fglrx_dri.so, error[/usr/lib64/dri/fglrx_dri.so: cannot open shared object file: No such file or directory]
ukiDynamicMajor: found major device number 249
ukiDynamicMajor: found major device number 249
ukiDynamicMajor: found major device number 249
ukiOpenDevice: node name is /dev/ati/card0
ukiOpenDevice: open result is 4, (OK)
ukiGetBusid returned 'PCI:1:0:0'
ukiOpenDevice: node name is /dev/ati/card1
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card2
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card3
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card4
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card5
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card6
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card7
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card8
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card9
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card10
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card11
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card12
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card13
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card14
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiOpenDevice: node name is /dev/ati/card15
ukiOpenDevice: UKI_ERR_NOT_ROOT
ukiDynamicMajor: found major device number 249
ukiOpenByBusid: Searching for BusID PCI:1:0:0
ukiOpenDevice: node name is /dev/ati/card0
ukiOpenDevice: open result is 4, (OK)
ukiOpenByBusid: ukiOpenMinor returns 4
ukiOpenByBusid: ukiGetBusid reports PCI:1:0:0
ukiDynamicMajor: found major device number 249
ukiDynamicMajor: found major device number 249
ukiOpenByBusid: Searching for BusID PCI:1:0:0
ukiOpenDevice: node name is /dev/ati/card0
ukiOpenDevice: open result is 5, (OK)
ukiOpenByBusid: ukiOpenMinor returns 5
ukiOpenByBusid: ukiGetBusid reports PCI:1:0:0
Segmentation fault
```

I also get a segmentation fault, like `glxinfo`.
