### ISSUE TITLE
vscode: Download location has changed

### ISSUE THREAD

**Issue by tcmal** [NixOS/nixpkgs#117592]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vscode
current version: 1.54.2
desired version: 1.54.3

###### Notify maintainers

maintainers: @eadwu @Synthetica9 

###### Note for maintainers

Update server has moved to `https://update.code.visualstudio.com`, old url (`https://vscode-update.azurewebsites.net/1.54.2/linux-x64/stable`) 404s.

**Comment by Synthetica9** [comment]
Wasn't this fixed in #117473 and #117479 ?

**Comment by tcmal** [comment]
my bad - forgot the search page links to the live version not `master`.
