### ISSUE TITLE
packaging request: DN42 root certificate

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#117530]
**Project description**

> dn42 root certificates for *.dn42 and 172.22.0.0/15 (and probably also fd00::/8)

this would be something nice-to-have... but the important part of it is that the certificate should be automatically kept up-to-date, thus an update script should be also provided.

cc @Mic92 

**Metadata**

* packaged in AUR: https://aur.archlinux.org/packages/ca-certificates-dn42/
* homepage URL: https://dn42.dev/services/Certificate-Authority
* source URL:
  * well, this is the tricky part: the cert is hosted on two URLs:
  * DN42: https://ca.dn42/crt/root-ca.crt
  * clearnet: https://ca.dn42.us/crt/root-ca.crt
  * but the clearnet endpoint is currently down
  * mirror: https://aur.archlinux.org/ca-certificates-dn42.git
* license: `custom:RDL` ??
* platforms: probably all, but at least unix

**Comment by Mic92** [comment]
Not quite sure if we even need a package for that?

Just put that on the dn42 wiki (maybe you can replace the AUR url even with something else)

```
{ pkgs, ... }: {
  security.pki.certificateFiles = [
    (pkgs.fetchurl {
      url = "https://aur.archlinux.org/cgit/aur.git/plain/dn42.crt?h=ca-certificates-dn42&id=646f7effb290adf25c7e9fea3b41bf055522ba29";
      name = "dn42.crt";
      sha256 = "sha256-wsMeC9/tlppSNZGrqfZFLAjv3AMj1KwIAWeh2XBpiYs=";
    })
  ];
}
```

**Comment by zseri** [comment]
The reason why a package for that would be helpful is because it would make automatic updates way easier, because not everyone installing the cert needed to keep track of updates, an update of the channel/flake input would suffice.

**Comment by Mic92** [comment]
Not sure if the monotone is still a thing, but it could be a nixos module in this repository.

**Comment by zseri** [comment]
@Mic92 maybe you could add an appropriate `flake.nix` to the AUR repo, effectively making it a flake and basically fixing this?

**Comment by Mic92** [comment]
@zseri I disowned all AUR packages actually since I don't actively use them.

**Comment by zseri** [comment]
I'll try to submit the following patch, if it doesn't get through, I'll just add the necessary content to my own nixos-configs repo, but I would really like to integrate it into the AUR repo to avoid a fragmentation of repos ("concerns") dealing with that.
```patch
From bd870aab4a41c0ded205e3c7d6fea385ad58506f Mon Sep 17 00:00:00 2001
From: Alain Zscheile <zseri.devel@ytrizja.de>
Date: Tue, 15 Jun 2021 16:44:05 +0200
Subject: [PATCH] add a flake.nix file to ease integration with NixOS

suggested here: https://github.com/NixOS/nixpkgs/issues/117530#issuecomment-860937335

this is easier than providing a package in nixpkgs and keeping that up-to-date
and avoids duplicate book-keeping of certificate revisons.
---
 flake.nix | 12 ++++++++++++
 1 file changed, 12 insertions(+)
 create mode 100644 flake.nix

diff --git a/flake.nix b/flake.nix
new file mode 100644
index 0000000..6774f6e
--- /dev/null
+++ b/flake.nix
@@ -0,0 +1,12 @@
+{
+  description = "dn42 root certificates for *.dn42 and 172.22.0.0/15";
+  outputs = { self }: {
+    nixosModules.ca-certificates-dn42 = { config, lib, ... }: {
+      options.security.pki.dn42.enable =
+        lib.mkEnableOption "dn42 root certificates";
+
+      security.pki.certificateFiles =
+        lib.mkIf config.options.security.pki.dn42.enable [ ./dn42.crt ];
+    };
+  };
+}
-- 
2.26.3

```

**Comment by buzo-ffm** [comment]
I'm the maintainer of the AUR package. I think NixOS is a cool project, so I'd like to help.

Would this file need to be part of the Arch package, or does it just need to be in the AUR git?

But keep in mind that I'm just a packager here, too, like you. So the AUR is definitely not an “official” source for anything regarding DN42.

**Comment by zseri** [comment]
AUR git suffices. The underlying problem tho is that the upstream clearnet mirror is down too often and afaik not versioned.

**Comment by buzo-ffm** [comment]
> AUR git suffices. The underlying problem tho is that the upstream clearnet mirror is down too often and afaik not versioned.

done

**Comment by zseri** [comment]
urgh, made a mistake, `config.` should be added in front of `security.pki.certificateFiles`, e.g. `config.security.pki.certificateFiles`, otherwise it results in an error:
error: Module `:anon-1141' has an unsupported attribute `security'. This is caused by introducing a top-level `config' or `options' attribute. Add configuration attributes immediately on the top level instead, or move all of them (namely: security) into the explicit `config' attribute.

**Comment by buzo-ffm** [comment]
changed

**Comment by zseri** [comment]
thanlks
