### ISSUE TITLE
Kodi plugin inputstream-adaptive - cannot be found by Search

### ISSUE THREAD

**Issue by nesnera** [NixOS/nixpkgs#117576]
**Describe the bug**
Inputstream-adaptive cannot be found using Add-ons > Add-ons browser > Search
\+ I believe it [should be displayed](https://www.kodi-guide.com/how-to-enable-inputstream-adaptive-in-kodi/) below Add-ons > Add-ons browser > Install from repository > Kodi Addon Repository > VideoPlayer InputStream. Currently I can only find it under the Add-ons > Add-ons browser > My add-ons > VideoPlayer InputStream

**To Reproduce**
1. Install plugin by `nixpkgs.config.kodi.enableInputStreamAdaptive = true;`
2. Restart Kodi and try to find the string "Input" among add-ons.

**Expected behavior**
The add-on will be found
\+ will be displayed under the community repository 

**Additional context**
The same goes for the `nixpkgs.config.kodi.enablePVRIPTVSimple = true;`
log file:
```
..
2021-03-25 10:07:41.921 T:139863748228032  NOTICE: ADDON: inputstream.adaptive v2.3.12 installed
..
2021-03-25 10:07:41.922 T:139863748228032  NOTICE: ADDON: pvr.iptvsimple v3.5.7 installed
..
```

**Notify maintainers**
@sephalon 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.96, NixOS, 20.09.3072.d4c29df154d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ln): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
@nesnera I'm sorry but I'm not a `home-manager` user so I don't understand the what channel you are on from the output you provided. Are you installing `kodi` from the `20.09` stable branch, or from unstable? Which version of `kodi` are you running?

The `kodi` package and package set was recently rewritten for the release of `kodi 19.x` so on unstable you can do this now:
```
# install inputstream-adaptive plugin
environment.systemPackages = with pkgs; [
  (kodi.withPackages (p: with p; [ inputstream-adaptive ]))
];
```

Or maybe you just want the `netflix` plugin:
```
# install netflix plugin, as well as inputstream-adaptive which is a dependency
environment.systemPackages = with pkgs; [
  (kodi.withPackages (p: with p; [ netflix ]))
];
```

**Comment by aanderse** [comment]
@nesnera please let me know if your issue hasn't been resolved.
