### ISSUE TITLE
kdeApplications was removed without release notes (for the 21.05 release)

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nixpkgs#117542]
@FRidh As part of b209617ff0a8f26ea1d1fe3716a7fa717a50dd95, `kdeApplications` has been removed.

However, I can't find in the release notes nor by trying to guess in the code how the applications were refactored. Would it be possible for you, who hopefully know where people should now be taking the applications, to write the release notes entry? If the applications should just be re-searched on the package search it may make sense, but if kdeApplications was just relocated elsewhere it'd probably be good to mention it — and as the commit is pretty big I'm not sure about what exactly was the intended change :/

**Comment by FRidh** [comment]
Yes, good that you mention this. There were a bunch of Qt5/KDE changes before this one, and we never really finished it either.

To reduce the mixing of Qt versions a separate extension was created, `qt5-packages.nix`, that should contain Qt packages. In the top-level, one should inherit then the version of the package one wants. It is my understanding that not all KDE applications build with a certain Qt version, and hence it was removed. We should revisit this, and the creation of a lot of Qt/KDE aliases before branch-off.
