### ISSUE TITLE
Custom xkb layouts with xkeyboard-config v2.33

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#117657]
Further to #47764, xkeyboard-config v2.33 will have upstream support for a `custom` layout which means that we can adapt the `extraLayouts` functionality to write to `/etc/xdg` using the same `custom` layout and we no longer need to recompile anything in case of custom layouts. Yeay!

Reference:
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/189

Cc: @rnhmjoj

**Comment by rnhmjoj** [comment]
Uhm, it will work only if adding a single layout with a single `symbols` file: for multiple layouts or when adding keycodes we still need to recompile. It could be done opportunistically, though.

**Comment by rnhmjoj** [comment]
This issue can now be closed: since #138207 we don't need to rebuild anymore.
