### ISSUE TITLE
Plasma System Monitor

### ISSUE THREAD

**Issue by ZhoraBartolomey** [NixOS/nixpkgs#117686]
### Plasma System Monitor

It's a new system monitor, replacement for KSysGuard.

* homepage URL: https://apps.kde.org/en/plasma-systemmonitor
* source URL: https://github.com/KDE/plasma-systemmonitor
* license: LGPL-3.0-or-later
* platforms: Linux

**Comment by aanderse** [comment]
https://github.com/NixOS/nixpkgs/pull/117104
