### ISSUE TITLE
Issues with GRUB 0.97 on a VPS

### ISSUE THREAD

**Issue by myrheimb** [NixOS/nixpkgs#117669]
## Issue description
Hey! I'm working on installing NixOS on several different hosting providers and have run into an issue with some that are using GRUB 0.97. These providers have no way of using a custom ISO, so I'm left with infecting Ubuntu or CentOS with a script based on https://github.com/elitak/nixos-infect/blob/master/nixos-infect.
The biggest change I made was to remove the `hardware-configuration.nix` from it and instead generate it with this:
```bash
nix-env -iE "_: with import <nixos/nixos> { configuration = {}; }; with config.system.build; [ nixos-generate-config ]"
nixos-generate-config
sed -i '/fileSystems."\/var\/lib\/lxcfs"/,+4d' /etc/nixos/hardware-configuration.nix
```

I tried simply setting `boot.loader.grub.version = 1;` which is able to create the necessary files and menu entries in `/boot` but ultimately fails with the following:
```bash
installing the GRUB 1 boot loader on /dev/vda...
Probing devices to guess BIOS drives. This may take a long time.
/dev/vda does not have any corresponding BIOS drive.
/nix/store/...-install-grub.pl: installation of GRUB on /dev/vda failed
warning: error(s) occurred while switching to the new configuration
```

I've also tried numerous other configurations with no luck or less than optimal results.

After poking at this for a while I came across the `boot.loader.generationsDir.enable` setting which creates statically named symlinks of the default generation as well as all other generations in the `/boot` folder.
This setting also appears to prevent GRUB 1/2 from being updated at all during a `nixos-rebuild`.
I then wrote my own workaround which works well, but I keep wondering if there's a better, cleaner way of solving this?
```nix
{ ... }:
{
  system.activationScripts = {
    configureGrub = {
      text = ''
        mkdir -p /boot/grub

        cat > /boot/grub/menu.lst << EOF
        # Automatically generated.  DO NOT EDIT THIS FILE!

        default 0
        timeout 30


        title NixOS - Default
          kernel /boot/default/kernel systemConfig=/boot/default/system init=/boot/default/init loglevel=4
          initrd /boot/default/initrd
        EOF

        for generation in $(ls -rdv /boot/system-*)
        do
          cat >> /boot/grub/menu.lst << EOF


        title NixOS - Configuration $(echo $generation | grep -o '[0-9]*')
          kernel $generation/kernel systemConfig=$generation/system init=$generation/init loglevel=4
          initrd $generation/initrd
        EOF
        done

        ln -sf /boot/grub/menu.lst /boot/grub/grub.conf
      '';
      deps = [ ];
    };
  };
}
```

Is there anyone here who has any ideas or knows of a solution that's less MacGyver and more `off-the-shelf`?

### Update 2021.03.29
Reran `grub-install --recheck /dev/vda` on a fresh reinstall of both Ubuntu and NixOS with `grub-install (GNU GRUB 0.97)`
It works on Ubuntu but not on NixOS.
```bash
root@ubuntu:~# grub-install --recheck /dev/vda
Probing devices to guess BIOS drives. This may take a long time.
Unknown partition table signature
Searching for GRUB installation directory ... found: /boot/grub
Unknown partition table signature
Unknown partition table signature
Unknown partition table signature
Unknown partition table signature
Unknown partition table signature
Unknown partition table signature
Unknown partition table signature
Unknown partition table signature
Installing GRUB to /dev/vda as (hd0)...
Unknown partition table signature
Installation finished. No error reported.
This is the contents of the device map /boot/grub/device.map.
Check if this is correct or not. If any of the lines is incorrect,
fix it and re-run the script `grub-install'.

(fd0)	/dev/fd0
(hd0)	/dev/vda
(hd1)	/dev/vdb
```

```bash
[root@nixos:~]# grub-install --recheck /dev/vda
Probing devices to guess BIOS drives. This may take a long time.
/dev/vda does not have any corresponding BIOS drive.
```

### Steps to reproduce
Hop on a VPS with GRUB 0.97 and [infect](https://github.com/elitak/nixos-infect/blob/master/nixos-infect) it with NixOS.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
Run from a system that has been infected with the workaround above, and is using GRUB 0.97.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.84, NixOS, 20.03.3325.462c6fe4b11 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.3325.462c6fe4b11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by domenkozar** [comment]
According to https://www.linuxquestions.org/questions/linux-software-2/solved-grub-install-dev-hdx-does-not-have-any-corresponding-bios-drive-error-401582/ you might try passing `--recheck` to when grub is invoked.

**Comment by myrheimb** [comment]
Hey, thanks for answering! 

Here's the output with `boot.loader.grub.version = 2;`.
It works but, unfortunately, it doesn't help since GRUB is actually 0.97 and won't boot any GRUB 2 menu entries.
```bash
grub-install --recheck /dev/vda
Installing for i386-pc platform.
Installation finished. No error reported.
```

And here is the output from `boot.loader.grub.version = 1;`:
```bash
grub-install --recheck /dev/vda
Probing devices to guess BIOS drives. This may take a long time.
/dev/vda does not have any corresponding BIOS drive.
```

Here's the content of `/boot/grub/device.map` which I've tried manually adding the drives to before, but it gets overwritten when running `nixos-rebuild`.
```bash
[  8:38AM ]  [ root@nixos:~ ]
 $ cat /boot/grub/device.map                   
(fd0)	/dev/fd0
```

**Comment by domenkozar** [comment]
It might be that grub doesn't have the following patch to detect vda* drives: https://salsa.debian.org/grub-team/grub-legacy/raw/1dad5507d74ef97fdd3c6cf2a028084f6f2850c3/debian/patches/grub-install_xvd.patch

Is there a way for your to update grub on those machines before infecting?

**Comment by domenkozar** [comment]
Maybe @elitak has some experience with this (this issue happens in nixpkgs but really it's closer related to nixos-infect).

**Comment by myrheimb** [comment]
I'm sorry, I'm not sure what to do with the `.patch` file you linked, but I have tried upgrading GRUB on Ubuntu before infecting by using `grub-pc` and `upgrade-from-grub-legacy` which doesn't work well, and at one point I completely crashed the VPS 😅

**Comment by NorfairKing** [comment]
CC @Infinisil  because you're in the `git blame` of `nixos/modules/system/boot/loader/grub/grub.nix` for the line that checks for the grub version.

**Comment by myrheimb** [comment]
I added an update to the issue under `Update 2021.03.29` where I re-ran `grub-install --recheck /dev/vda` on a fresh reinstall of both Ubuntu and NixOS.

**Comment by nh2** [comment]
> I'm sorry, I'm not sure what to do with the `.patch` file you linked

@myrheimb I believe @domenkozar suggests to apply it to the Grub 0.97 source code when building, that is, putting it in here (https://github.com/NixOS/nixpkgs/blob/d69579b188482caa773e4a6bfb659933dd4cbfa3/pkgs/tools/misc/grub/default.nix#L11) by changing nixpkgs, or a package `overrideAttrs`.

**Comment by myrheimb** [comment]
I spent some time looking into the suggestions from @nh2 and @domenkozar and it seems that [the patch mentioned](https://github.com/NixOS/nixpkgs/issues/117669#issuecomment-808042091) is already included.

First when we set `boot.loader.grub.version = 1;` it will determine which grub package to install here:
https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/nixos/modules/system/boot/loader/grub/grub.nix#L11-L15

So that's `pkgs.grub` which by looking at [search.nixos.org/packages](https://search.nixos.org/packages?channel=20.03&show=grub&from=0&size=50&sort=relevance&query=grub) and clicking on `Source` points to 
https://github.com/NixOS/nixpkgs/blob/nixos-20.03/pkgs/tools/misc/grub/default.nix

If we then look at what's included in `patches` we find that `grub1.patches.nix` is included here:
https://github.com/NixOS/nixpkgs/blob/462c6fe4b115804ea4d5bee7103c0f46ff9f9cfb/pkgs/tools/misc/grub/default.nix#L18

Which as it turns out includes the patch that @domenkozar linked:
https://github.com/NixOS/nixpkgs/blob/d69579b188482caa773e4a6bfb659933dd4cbfa3/pkgs/tools/misc/grub/grub1.patches.nix#L20

Thank you very much for your help so far 🙇

**Comment by samueldr** [comment]
GRUB 0.97 has been removed with #167204.

Sorry that this couldn't be resolved in its lifetime.
