### ISSUE TITLE
Carla: compatibility issues with NSM (because of double wrapping?)

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#117781]
**Describe the bug**
NSM (New-Session-Manager and Non-Session-Manager) is useful to save the state of multiple MAO programs to allow users to quickly configure multiple programs at once. Carla is supposed to be usable with NSM, but in NixOs this fails.

I suspect the double-wrapping of Carla to be an issue. Notably, the second wrapper has a line:

```
exec $PYTHON "$INSTALL_PREFIX"/share/carla/carla --with-appname="$0" --with-libprefix="$INSTALL_PREFIX" "$@"
```

and `--with-appname` is therefore set to `.carla-wrapped` which is not the name of a valid executable... I suspect that is perturbs NSM since NSM actually tries to start `.carla-wrapped` instead of `carla`.

**To Reproduce**

See https://github.com/jackaudio/new-session-manager/issues/73

**Notify maintainers**

@minijackson 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.93, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-unstable-21.03pre267299.5ff6700bb82, nixos-21.03pre267299.5ff6700bb82"`
 - channels(me): `"local-nixos-unstable-21.05pre274338.102eb68ceec, home-manager, local-nixpkgs-unstable-21.03pre267409.f5daa8ab31f, nixos-20-03-20.03.3324.929768261a3, test, nixos-unstable-21.03pre250162.34ad166a830"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

(I installed new-session-manager (also tested with non) from local-nixos-unstable) 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by tobiasBora** [comment]
People confirmed that the bug is due to `--with-appname` that should be set to `carla` directly (or one must remove the double wrap to ensure `$0` is carla).

**Comment by turboMaCk** [comment]
@tobiasBora where do you see `--with-appname` is being used?

**Comment by turboMaCk** [comment]
got it:

```
 cat /nix/store/3lqw7fib4nfrba989qcsqqzpbgzhx1m1-carla-2.2.0/bin/.carla-wrapped
#!/nix/store/w65ydq10abi813fi7d5j7afdcrxj3aqq-bash-4.4-p23/bin/bash

PYTHON=$(which python3 2>/dev/null)

if [ ! -f ${PYTHON} ]; then
  PYTHON=python
fi

if [ "$1" = "--gdb" ]; then
  PYTHON="gdb --args $PYTHON"
fi

INSTALL_PREFIX="/nix/store/3lqw7fib4nfrba989qcsqqzpbgzhx1m1-carla-2.2.0"
export PATH="$INSTALL_PREFIX"/lib/carla:$PATH
exec $PYTHON "$INSTALL_PREFIX"/share/carla/carla --with-appname="$0" --with-libprefix="$INSTALL_PREFIX" "$@"
```

I suspect this is part of carla rather than something that is specific to nixos. Anyway `$0` will become `.carla-wrapped` rather than `carla`.  The another wrapper that nixos is using is `/nix/store/3lqw7fib4nfrba989qcsqqzpbgzhx1m1-carla-2.2.0/bin/carla`

**Comment by turboMaCk** [comment]
@tobiasBora I've opened PR with fix. In mean time you can test if this resolves this problem for you by putting this code into your `configuration.nix`:

```nix
  nixpkgs.overlays = [ (self: super:
    {
      carla = super.carla.overrideAttrs (old: {
        postFixup = old.postFixup + ''
                 sed -i 's/--with-appname="$0"/--with-appname="carla"/g' $out/bin/.carla-wrapped
             '';
      });
    }
  )];
```

**Comment by tobiasBora** [comment]
Thanks a lot for the PR, I can confirm it solves the problem, thanks again!

However, I'm curious, where can you see this part is done by the python wrapper?  I can't find any reference to `--with-appname` in the nixpkg repository, while carla package definitely has a very similar file [here](https://github.com/falkTX/Carla/blob/main/data/carla). I guess we can continue the discussion [here](https://github.com/NixOS/nixpkgs/pull/117880#discussion_r602938093) since there is already a question about wrappers there.

**Comment by turboMaCk** [comment]
@tobiasBora you're right! Full answer is https://github.com/NixOS/nixpkgs/pull/117880#discussion_r603077706

**Comment by tobiasBora** [comment]
Still interested. I proposed a fix here https://github.com/NixOS/nixpkgs/pull/140129, it fixes all executable automatically.

**Comment by tobiasBora** [comment]
Solved in https://github.com/NixOS/nixpkgs/pull/140129
