### ISSUE TITLE
Package request: modipy with plugins

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#117720]
**Project description**

Mopidy is an extensible music server written in Python. 

**Metadata**

* homepage URL: https://mopidy.com/ ,  https://mopidy.com/ext/
* source URL: https://github.com/mopidy
* license: Apache-2.0
* platforms: unix

**Comment by dotlambda** [comment]
There is a package called `mopidy`. See [`pkgs/applications/audio/mopidy`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/audio/mopidy).

**Comment by matthiasbeyer** [comment]
ah, seems I missed that.
