### ISSUE TITLE
Packaging Request: OpenSnitch

### ISSUE THREAD

**Issue by herrmoltke** [NixOS/nixpkgs#117783]
**Project description**
OpenSnitch is an application firewall. It is a port of MacOS' Little Snitch.

**Metadata**

* homepage URL: https://github.com/evilsocket/opensnitch
* source URL: https://github.com/evilsocket/opensnitch
* license: GPL 3.0
* platforms: Linux

**Comment by prusnak** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/76610
