### ISSUE TITLE
copy/move LaTeXML outside of perl-packages

### ISSUE THREAD

**Issue by xworld21** [NixOS/nixpkgs#117740]
**Describe the bug**
LaTeXML (LaTeX to XML converter written in perl) currently sits inside perl-packages, but it may be better placed outside. The idea came up in a PR https://github.com/NixOS/nixpkgs/pull/117161#discussion_r599094300, for different reasons:
 - the default installation could benefit from overriding `imagemagick` with `imagemagickBig`
 - upgrade/installation/removal is different from an application
 - users are probably more interested in the `latexml*` executable rather than the modules anyway

**To Reproduce**
For installation/upgrade/removal, one needs to install `nix-env -i perl5.32.0-LaTeXML` (or `nix-env -iA nixpkgs.perlPackages.LaTeXML`). As far as I can tell, it will stop getting updates when perl5.32 gets out of nixpkgs.

**Expected behavior**
I think `nix-env -i/-u/-e latexml` would be more inline with user expectations, or at least mine. Ideally, `latexml` should install only binaries and manpages; for the perl modules one should still use `perlPackages.LaTeXML`.

**Notify maintainers**

@veprbl @stigtsp @matthuszagh

**Comment by xworld21** [comment]
I got just a bit creative:
```nix
{ lib, linkFarm, perlPackages }:
let LaTeXML = perlPackages.LaTeXML; in
lib.addMetaAttrs
  LaTeXML.meta
  (linkFarm "latexml-${LaTeXML.version}" [
    { name = "bin"; path = LaTeXML + "/bin"; }
    { name = "share"; path = LaTeXML + "/share"; }
  ])
```
It does exactly what I'd like – `latexml` is a binary + docs only package independent of perl, while the modules (with their own binaries) remain available under `perlPackages`. And the two versions conflict with each other, which seems wise.

But I haven't seen other packages use `linkFarm` in this way. Is that too hacky?

**Comment by AndersonTorres** [comment]
Can we make it like `pythonPackages`?

**Comment by xworld21** [comment]
> Can we make it like `pythonPackages`?

On the other hand, I have just checked `nixpkgs.wfuzz`, which uses `toPythonApplication`, and I am getting modules in my profile. I am not too fond of that – you end up with modules you are not supposed to touch, because they won't move in lockstep with your python.

**Comment by xworld21** [comment]
Ah, after some reading of nixpkgs, I gather that `buildEnv` is the idiomatic way, and it's also very simple
```nix
{ buildEnv, perlPackages }:
let LaTeXML = perlPackages.LaTeXML; in
buildEnv {
  inherit (LaTeXML) meta;
  name = "latexml-${LaTeXML.version}";
  paths = [ LaTeXML ];
  pathsToLink = [ "/bin" "/share" ];
}
```
It seems easy to generalise to a `toPerlApplication`, just make a thin wrapper around `buildEnv` with defaults and `pname` instead of `name`. That could help with a few other packages (`xmlsort`, `exiftool`, ...).

At this stage, I can send a PR just for `latexml`. It seems solid and it can be reviewed later. But if you are mulling over a generic `toPerlApplication`, I suppose I should wait!

**Comment by veprbl** [comment]
I don't think we should do anything towards fixing the use with nix-env. There are fine alternatives to address packages by their attribute paths. It should be fine to add a simple alias `latexml = perlPackages.latexml;`, but I feel like rolling any one-of-a-kind additional wrappers is not worth it.

**Comment by xworld21** [comment]
> but I feel like rolling any one-of-a-kind additional wrappers is not worth it

That's fair. And `nix-env -u` does not seem to be in good shape anyway.

Since `nix-env -u` was the main reason for asking this, unless there is appetite for a generic `toPerlApplication`, I guess this issue should be closed.
