### ISSUE TITLE
Can't boot into NixOS

### ISSUE THREAD

**Issue by lostdj** [NixOS/nixpkgs#11788]
Was lucky enough to login twice, but everything froze. The issue seems to be with laptop display backlight system / service / however it handled, because it's either booting process stops somewhere on 'loading backlight blah blah', or everything becomes completely unresponsive to anything with pressing Fn + 'backlight +/-'.

I'm on ThinkPad W520.
With custom package tree (identical to this repo). Tried to base the build on these two commits: https://github.com/nixos/nixpkgs/commit/33eddc4e906d93ccc1bc6da33e47cf5d35d04c1b and https://github.com/nixos/nixpkgs/commit/93d8671e2c6d1d25f126ed30e5e6f16764330119 Hoping that it was magically fixed in a time between them.

Tried disabling as much as possible in BIOS, turning on/off NV Optimus. Nothing.

I haven't updated since march-may and will try out a stable 15.09 later. But meanwhile, were there any big changes related to this after 15.09?

**Comment by vcunat** [comment]
> But meanwhile, were there any big changes related to this after 15.09?

I don't remember any, but such things should be in [release notes](http://nixos.org/nixos/manual/release-notes.html).

**Comment by lostdj** [comment]
This is for 15.09, not after. :)

**Comment by vcunat** [comment]
There's [latest manual build](http://hydra.nixos.org/job/nixos/trunk-combined/nixos.manual.x86_64-linux/latest/download/2/nixos/release-notes.html) as well. You confused me by saying you wanted to try 15.09.

**Comment by lostdj** [comment]
Sorry.

Well nothing there, too.

**Comment by lostdj** [comment]
Tried to play with some options.

Kernel boot argument `systemd.restore_state=0` as seen here: http://www.freedesktop.org/software/systemd/man/systemd-backlight@.service.html and here: https://wiki.archlinux.org/index.php/Backlight#systemd-backlight_service

`systemctl mask systemd-backlight@.service` gives something like `Failed: file already exists`, and `systemctl mask systemd-backlight.service` throws `Read-only filesystem`.

Commented out this line https://github.com/NixOS/nixpkgs/blob/1da87d40628c99081bac0a5d8b32c27123889826/nixos/modules/system/boot/systemd.nix#L102

It's 50/50 chance I'll be able to login, but then it still may freeze randomly or by changing display brightness manually. :(

**Comment by grahamc** [comment]
Have you managed to sort out the issue?

**Comment by lostdj** [comment]
@grahamc no. And I haven't tried to since.
