### ISSUE TITLE
librewolf browser

### ISSUE THREAD

**Issue by DaxGoon** [NixOS/nixpkgs#117825]
**Project description**
Add librewolf browser to nixos packages repo.

**Metadata**

* homepage URL: https://librewolf-community.gitlab.io/
* source URL: https://gitlab.com/librewolf-community/browser
* license: Mozilla Public License 2.0.
* platforms: gnu/linux, darwin, windows

**Comment by dotlambda** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/94918
