### ISSUE TITLE
mftrace

### ISSUE THREAD

**Issue by xworld21** [NixOS/nixpkgs#117876]
**Project description**
From the project website: "mftrace is a small Python program that lets you trace a TeX bitmap font into a PFA or PFB font (A PostScript Type1 Scalable Font) or TTF (TrueType) font."

I came across it while trying to compile the [Comprehensive LaTeX Symbol list](https://ctan.org/tex-archive/info/symbols/comprehensive). It doesn't seem to be used a lot, but it seems nice to have, and I have just packaged it for myself anyway.

Working packaging attempt [here](https://github.com/NixOS/nixpkgs/compare/master...xworld21:mftrace), just two notes:
- mftrace needs texlive at runtime only (it finds fonts via `kpsewhich` and uses metafont binaries), I have left it out so that it works with any installed texlive, but it's also broken if there is none, is that ok?
- I have not added a maintainer!

**Metadata**

* homepage URL: https://lilypond.org/mftrace/
* source URL: https://github.com/hanwen/mftrace
* licenses: gpl2-only, free
* platforms: unix, windows (judging from the source – I have not tested it)

**Comment by dotlambda** [comment]
> I have left it out so that it works with any installed texlive, but it's also broken if there is none, is that ok?
If it only needs a small texlive without many packages, it might be worth adding that to `wrapProgram`.

> licenses: gpl2-only, free
Is there a part that's licensed under GPLv2?

> I have not added a maintainer!
Besides that, you should use `platforms.all`. Then nothing should stop a pull request from being merged.

**Comment by xworld21** [comment]
> If it only needs a small texlive without many packages, it might be worth adding that to `wrapProgram`.

Ok, I know which binaries are needed, I can try. If it doesn't work out, I'll add a comment.

> Is there a part that's licensed under GPLv2?

All of the python files are GPLv2 without the "any later version" text and COPYING is GPLv2. The C file has a custom free license from `xdvi`. The README claims that `mftrace` is licensed under the GPL (no version) with a generic link, but it's also a 15 years old line... I would err on the side of `gpl2Only free`.

> > I have not added a maintainer!
> 
> Besides that, you should use `platforms.all`. Then nothing should stop a pull request from being merged.

Ah, sure!

I suppose I can add myself to the maintainer list if nobody wants it. This should be a very low maintenance package anyway.

I'll send a PR in a few days, after I have time to sort out the runtime binaries issue.

**Comment by xworld21** [comment]
PR is up, with a few tweaks compared to my first attempt. Thanks for the pointers @dotlambda!
