### ISSUE TITLE
qtcreator-3.4.2 is ancient

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11787]
The most recent version is 5.5.X (and it would also be nice if it would work on MacOSX El Capitan).

**Comment by bjornfor** [comment]
Are you sure you're not mixing Qt and QtCreator version numbers? I think I recently updated QtCreator to the latest version in master, 3.5.2 or something. (Not completely sure I pushed it.)

**Comment by ttuegel** [comment]
@bjornfor Actually, Qt Creator 3.6.0 was recently released, but 3.5.1 is hardly ancient. Whether or not it works on Darwin is a separate issue.

We have Qt Creator 3.5.1, Qt 5.5.1, and Qt 5.4.2 for those packages that don't yet build with Qt 5.5.
