### ISSUE TITLE
Firefox and Thinderbird misuse `config`

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#117983]
**Describe the bug**

`config.i18n.defaultLocale` is a NixOS option

https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/nixos/modules/config/i18n.nix#L26

which is used in nixpkgs by Firefox and Thundebird
where `config` is not the top-level NixOS config but its `config.nixpkgs.config`

https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/applications/networking/mailreaders/thunderbird-bin/68.nix#L61
https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/applications/networking/browsers/firefox-bin/default.nix#L52

**Comment by kvtb** [comment]
related https://github.com/NixOS/nixpkgs/issues/30962

**Comment by dotlambda** [comment]
cc @taku0 @mweinelt

**Comment by mweinelt** [comment]
Unrelated to the `firefox` package, which I maintain.

**Comment by taku0** [comment]
Solution sketch:

- Take a parameter `locale`, defaults to null.
- If the parameter is null, try the followings in order:
  1. `config.i18n.defaultLocale`
  2. `config.i18n.defaultLocale` without modifier
  3. `config.i18n.defaultLocale` without modifier or codeset
  4. `config.i18n.defaultLocale` without modifier, codeset, or territory
  5. "en-US"

https://www.gnu.org/software/libc/manual/html_node/Locale-Names.html

**Comment by taku0** [comment]
I get the problem. We cannot detect the system locale via `config.i18n.defaultLocale`. So, what should we do?

**Comment by taku0** [comment]
Related: #58153
