### ISSUE TITLE
Error message with root installation

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#11792]
```
nix-env -i irssi --show-trace
installing ‘irssi-0.8.17’
error: opening lock file ‘/nix/store/amgxsp45kk5gp6flz43frgybs9idic73-env-manifest.nix.lock’: Permission denied
```

Just print out the required root command for a multi-user setup with a link to the documentation or something similar to fix this situation.

**Comment by jgillich** [comment]
I don't think this is supposed to happen(?). Did you set up multi user mode correctly? http://nixos.org/nix/manual/#ssec-multi-user

**Comment by rbru** [comment]
@jgillich This happens when I run it as root. As a normal user with 
`export NIX_REMOTE=daemon` it does work.

**Comment by domenkozar** [comment]
This issue should be migrated to github.com/NixOS/nix

**Comment by Profpatsch** [comment]
(triage) still a problem @aragnon?

**Comment by MP2E** [comment]
Closing since there hasn't been any update in over 1 year
