### ISSUE TITLE
pCloud Command Line Interface (pcloudcc)

### ISSUE THREAD

**Issue by NicolasGuilloux** [NixOS/nixpkgs#117916]
**Project description**
pCloud made a CLI to mount their drive. It would be great to have it as a package.

Something awesome would be to choose between Europe or American API (more information: https://github.com/pcloudcom/console-client/issues/130#issuecomment-720623179).

Maybe it would be great to build a service to easily mount it using a module.

**Metadata**

* homepage URL: https://github.com/pcloudcom/console-client
* source URL: https://github.com/pcloudcom/console-client
* license: Unknown
* platforms:  linux

**Comment by jwdevantier** [comment]
The tool has not been updated for years at this point - it seems abandoned.
The fork I could find ( https://github.com/sergeyklay/pcloud-console-client/tree/master ) is likewise abandoned.

**Comment by NicolasGuilloux** [comment]
It appears that none of their public repository has activity. I don't use much their drive as a filesystem so I didn't check for a long time if it still does work.
I'll close this issue since it seems to have no security update either, so I wouldn't be confident adding it as a package in the nixpkgs codebase.

Thanks for the headsup @jwdevantier, I forgot this issue ;)
