### ISSUE TITLE
KDE audio control tray icon is gone when using pipewire

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#117966]
**Describe the bug**
I switched from `pulseaudio` to `pipewire` on KDE. But the audio control tray icon is gone. Media keys don't work either.
Note that `pavucontrol` can adjust audio volume and switching devices without issue. Audio output is also fine.

Not sure it's an issue from KDE or pipewire side.

Here is my configuration:
```
  security.rtkit.enable = true; # Better installed with pipewire.
  services.pipewire = {
    enable = true;
    media-session.enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
```

`pipewire.service` and `pipewire-media-session.service` are both running. The latter one has some error but still running as well.
```
Mar 29 11:06:38 invar pipewire-media-session[25853]: oFono: Registering Profile /Profile/ofono failed
Mar 29 11:06:38 invar pipewire-media-session[25853]: hsphfpd: Registering application /Profile/hsphfpd/manager failed
```

**To Reproduce**
1. Enable X11 and KDE.
2. Add sound configuration above.
3. `nixos-rebuild test`, log out and re-log in.
4. The audio icon in system tray is gone. Media keys don't work any more.

**Expected behavior**
Audio control from KDE and media keys all work.

**Screenshots**
![image](https://user-images.githubusercontent.com/14816024/112889215-eeac4d00-9107-11eb-93e4-86730285ef19.png)

**Additional context**
Also mentioned in https://github.com/NixOS/nixpkgs/issues/102547#issuecomment-797040280

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 21.05.20210319.f5e8bdd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(oxa): `"home-manager"`
 - nixpkgs: `/nix/store/mz372xs1z8r6b3337zs0qxkg0ffrbnn3-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- pipewire
- plasma5
```

**Comment by floyza** [comment]
I believe the solution is just to have `kmix` and `plasma-pa` installed, so you can install them manually for now and that should work.

**Comment by peterhoeg** [comment]
I switched to pipewire some time ago and subsequently forgot all about it (things just worked) and I haven't had the tray icon disappear at any point. I cannot comment on media keys. Keyboard doesn't have them.

**Comment by oxalica** [comment]
@floyza 
After adding `kmix` and `plasma-pa` into `environment.systemPacakges`, and a reboot. The tray icon appears in a wired state.
There are two forever-muted icon shown.
- One prompts the original "Audio Volume" window, but shows `no output or input devices found`. Though the audio plays well.
![image](https://user-images.githubusercontent.com/14816024/113864449-7ddaf400-97dd-11eb-9a6c-8c239ef6f34a.png)
- Another prompts a small window shows several volume slider. The "Master" has no effect, but per-application control works.
  (Another strange thing. When opening this window, any shortcut of KDE doesn't work anymore, including my screenshot key and `alt-tab`)
![image](https://user-images.githubusercontent.com/14816024/113864630-b549a080-97dd-11eb-9c4f-26f89a793034.png)
- Pressing any media key including toggle mute, increase and decrease volume keys, always shows a "Audio Muted" tip.

**Comment by oxalica** [comment]
Note that `pavucontrol` doesn't work anymore after updating to current nixos-unstable 3d1a7716d7f1fccbd7d30ab3b2ed3db831f43bde. It shows "Establishing connection to PulseAudio. Please Wait..." forever, while `pipewire{,-pulse,-media-session}.service` are just running fine.
Not sure if it is caused by the pipewire version bump fbdb248e54c1d824788b39b2274ff55319d7a411

**Comment by archseer** [comment]
Sidenote: `sound.enable = true` should be removed from your config, according to #102547. I think it enables ALSA. 

Kind of annoying, but similar to how `networking.wireless.enable` should be false if using `networking.wireless.iwd.enable`.

**Comment by oxalica** [comment]
@archseer 
> sound.enable = true should be removed from your config, according to #102547. I think it enables ALSA.

Tried but it made no difference.

**Comment by yourfavouriteuncle** [comment]
Works fine for me with `kmix` and `pulse-pa` installed from home-manager. I have the pipewire setup in my `configure.nix`.

**Comment by IsidoreSong** [comment]
I'm using pure pulseaudio facing the same problem.
After installing kmix and plasma-pa, I also get two audio icons and the other situations like the picture.
I believe one of the is for the original plasma which is muted and the other is from kmix.
By the way, I'm on an old laptop and the media key is not working until I installed kmix.

**Comment by c0n5um3r** [comment]
> After installing kmix and plasma-pa, I also get two audio icons and the other situations like the picture.

Sorry for necroposting. Any updates on this? I have this problem too.
