### ISSUE TITLE
Add g810-led

### ISSUE THREAD

**Issue by SeraphyBR** [NixOS/nixpkgs#117951]
**Project description**
Linux led controller for Logitech G213, G410, G413, G512, G513, G610, G810, G815, G910 and GPRO Keyboards.

**Metadata**

* homepage URL: https://github.com/MatMoul/g810-led
* source URL: https://github.com/MatMoul/g810-led
* license: gpl3
* platforms: linux

**Comment by samuelgrf** [comment]
There are closed pull requests for both a [package](https://github.com/NixOS/nixpkgs/pull/92119) and [module](https://github.com/NixOS/nixpkgs/pull/92124).
If you want to you can update it based on the suggestions and open your own PR.
