### ISSUE TITLE
Android Studio Native debugging is broken on Canary and Dev

### ISSUE THREAD

**Issue by IvarWithoutBones** [NixOS/nixpkgs#117985]
**Describe the bug**
Android Studio deploys some script to Android devices for native debugging, which shouldn't have a /nix/store shebang as Android does not understand this. To fix this, the [dontPatchShebangs flag is used](https://github.com/NixOS/nixpkgs/blob/059d331839e2a60dfbc0dce6fbc30fa54772fd2c/pkgs/applications/editors/android-studio/common.nix#L156). 

A few days ago the package got [bumped](https://github.com/NixOS/nixpkgs/pull/116837/commits/148758e4ff00da00f6cfb1b1d4a529f9df8d358f), and somehow this was broken, as now the shebang is patched again. When reverting this change, the shebang is unpatched again as it should. 

It should also be noted that `androidStudioPackages.beta` and `androidStudioPackages.stable` do not have this issue, but `androidStudioPackages.dev` does.

**To Reproduce**
1. `nix run nixpkgs.androidStudioPackages.canary`
2. `cat /nix/store/8an00vr7prbsi7ym0k969259i8jw6g2b-android-studio-canary-2020.3.1.10-unwrapped/bin/lldb/android/start_lldb_server.sh`
3. Notice the shebang being patched, even though `dontPatchShebangs` is set to `true`.

**Expected behavior**
Shebangs in `$out/bin/lldb/android/start_lldb_server.sh` are unpatched, which makes this work on the Android devices it gets deployed to.

**Additional context**
This was fixed with #112349, but seems to have somehow broken again with #116837.

**Notify maintainers**
@meutraa 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.8, NixOS, 21.05pre279012.ad47284f8b0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre279012.ad47284f8b0"`
 - channels(ivv): `"home-manager, nixpkgs-21.05pre278688.c0e88185200"`
 - nixpkgs: `/home/ivv/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: androidStudioPackages.{canary,dev}
```

**Comment by PixelyIon** [comment]
I can reproduce this locally as well. It's arbitrarily broken with `Android Studio 2020.3.1 Canary 10` from `Android Studio 2020.3.1 Canary 7` with no viable differences in the derivation that would cause this. It points to an issue with `dontPatchShebangs` where it somehow doesn't work.

**Comment by IvarWithoutBones** [comment]
Logs do seem to confirm `dontPatchShebangs` not being respected.
```
android-studio-canary> patching script interpreter paths in /nix/store/z5v2xsssia1b7j5q056svwwslhnpv59l-android-studio-canary-2020.3.1.10-unwrapped
android-studio-canary> /nix/store/z5v2xsssia1b7j5q056svwwslhnpv59l-android-studio-canary-2020.3.1.10-unwrapped/bin/lldb/android/start_lldb_server.sh: interpreter directive changed from "#!/system/bin/sh" to "/nix/store/w65ydq10abi813fi7d5j7afdcrxj3aqq-bash-4.4-p23/bin/sh"
```

I am unsure as to why this happens only on the `dev` and `canary` branches, as they get called in the exact same way as the `stable` and `beta` branches which do not have this issue.
