### ISSUE TITLE
KDE Applications has been renamed to KDE Gear

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#118189]
We probably should too to make things consistent.

https://community.kde.org/Schedules/KDE_Gear_21.04_Schedule

Cc: @NixOS/qt-kde

**Comment by FRidh** [comment]
related is the issue regarding `kdeApplications` being removed from top-level https://github.com/NixOS/nixpkgs/issues/117542

**Comment by ttuegel** [comment]
As far as I can tell, this is not effective until the 21.04 release, at which time I agree we should rename the package set.

**Comment by samueldr** [comment]
Fixed with #120514 ?

**Comment by ttuegel** [comment]
Yes.
