### ISSUE TITLE
`services.nsd.keys` is broken

### ISSUE THREAD

**Issue by davidtwco** [NixOS/nixpkgs#118140]
**Describe the bug**
Using `services.nsd.keys` causes the generated `nsd.conf` to fail to validate. 

`services.nsd.keys` configures the `nsd` systemd unit to read key files and generate configuration containing their secrets (placed in `${stateDir}/private/${keyName}`, during pre-start) which is referenced by the primary `nsd.conf` configuration file using nsd's `include` functionality.

Within the sandbox of the `nsd-env` build, the referenced files cannot be present - systemd's `PreStart` cannot have run to create them - which causes `nsd-checkconf` to fail because it cannot find the referenced files.

**To Reproduce**
This issue can be reproduced by using `service.nsd.keys` in any way, but to simplify reproduction, you can modify the `nixos/tests/nsd.nix` test to trigger the issue:

1. Apply the patch below to a nixpkgs checkout:

```diff
diff --git a/nixos/tests/nsd.nix b/nixos/tests/nsd.nix
index a558ee0a425..52977b6b2a3 100644
--- a/nixos/tests/nsd.nix
+++ b/nixos/tests/nsd.nix
@@ -34,6 +34,7 @@ in import ./make-test-python.nix ({ pkgs, ...} : {

     server = { lib, ... }: {
       imports = [ common ];
+      environment.etc."nsd-key".text = "DEswtm5mHoeE3DlorIID4cttKXqAL5l2fiMtlPv0C3U=";
       networking.interfaces.eth1.ipv4.addresses = [
         { address = "192.168.0.1"; prefixLength = 24; }
       ];
@@ -42,7 +43,8 @@ in import ./make-test-python.nix ({ pkgs, ...} : {
       ];
       services.nsd.enable = true;
       services.nsd.rootServer = true;
       services.nsd.interfaces = lib.mkForce [];
+      services.nsd.keys."nsd-key" = { algorithm = "hmac-md5"; keyFile = "/etc/nsd-key"; };
       services.nsd.zones."example.com.".data = ''
         @ SOA ns.example.com noc.example.com 666 7200 3600 1209600 3600
         ipv4 A 1.2.3.4
```

2. Run `nix-build nixos/tests/nsd.nix` and observe the build failure:

```
error: builder for '/nix/store/35x0dcx4z52fbwq6hk238prwxigcjbvg-nsd-env.drv' failed with exit code 2;
       last 10 log lines:
       > |- checking zone '/nix/store/8rfp13chfysrw2l52xag5k6w2g4cazar-nsd-env/zones/deleg.example.com.'
       > zone deleg.example.com. is ok
       > |- checking zone '/nix/store/8rfp13chfysrw2l52xag5k6w2g4cazar-nsd-env/zones/example.com.'
       > zone example.com. is ok
       > |- checking zone '/nix/store/8rfp13chfysrw2l52xag5k6w2g4cazar-nsd-env/zones/root'
       > zone root is ok
       > checking configuration file
       > /nix/store/8rfp13chfysrw2l52xag5k6w2g4cazar-nsd-env/nsd.conf:51: error: cannot open include file '/var/lib/nsd/private/nsd-key': No such file or directory
       > /nix/store/8rfp13chfysrw2l52xag5k6w2g4cazar-nsd-env/nsd.conf:54: error: tsig key nsd-key has no secret blob
       > read /nix/store/8rfp13chfysrw2l52xag5k6w2g4cazar-nsd-env/nsd.conf failed: 2 errors in configuration file
       For full logs, run 'nix log /nix/store/35x0dcx4z52fbwq6hk238prwxigcjbvg-nsd-env.drv'.
error: 1 dependencies of derivation '/nix/store/rzggx6m6wpzl0gwky8a3fi0asnq0n3x3-unit-nsd.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6y4fmrz211lbhxy7y4jwgzgsh5gh50yp-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fw5kqaz034ribzjilq5sram34wz2jk98-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/pjjsfvax6n05rprkm1w4fhbz7y4lq1s2-nixos-system-server-21.05pre-git.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kv8xiiqa5vsr4pg8p4vpsqclidis1c4p-nixos-vm.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vmiryjr4m4if722jqm56wivjrxh9dnc5-nixos-test-driver-nsd.drv' failed to build
error: 1 dependencies of derivation '/nix/store/qws7ms9hdhsg0ik1p8ha5rk38sp76588-vm-test-run-nsd.drv' failed to build
```

**Expected behavior**
nsd configuration is validated successfully and configured keys are working.

**Screenshots**
N/A

**Additional context**
N/A

**Notify maintainers**
@hrdinka

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.107, NixOS, 21.05.20210323.b38923b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - nixpkgs: `/etc/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: nsd
```

**Comment by hrdinka** [comment]
Hi @davidtwco,

Thanks, for the bug report. This one however is not an easy one to fix. Maybe it can create dummy files in the build env before the check takes place. If this does not work however, we can only disable the check if an external file might be used somewhere. I will look into it, but this might take some time.

**Comment by pschyska** [comment]
I also hit this bug. An extra complication is that when using nixops' `deployment.keys` to prevent the secrets from entering the nix store, the file source `/run/keys/...` can never be readable by the builder (i.e. my workstation), as it would only exist on the deployment target.

I think the configtest should be skipable or phony keys generated to make it work during build-time (there is a slight advantage of being notified about errors before the deploy, but in my use-case it's not too important)

**Comment by pschyska** [comment]
@hrdinka I took a stab at this, please take a look.
We don't get around modifying nsd.conf in any case, so I opted to inject fake keys temporarily (just dropping the keys didn't work, because then `nsd-checkconf` complained at their references).
This still retains the usefulness of checkconf during buildtime - at least partially because the build can't check the to-be-included keys, obviously.
The only other option that I'm seeing right now is to skip checkconf alltogether.

**Comment by hrdinka** [comment]
@pschyska Thanks a lot. I haven’t forgotten about this issue. I just did not have any free time or even a weekend in the last months. The fix seems great, I am currently testing it and will merge soon. Have a nice day :+1:
