### ISSUE TITLE
Steam / gtk+3 broken on master

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#118155]
`gtk+3` is broken on master

```
       > FAILED: docs/reference/libtracker-sparql/examples/writeonly-example.p/writeonly-example.c.o
       > gcc -Idocs/reference/libtracker-sparql/examples/writeonly-example.p -Idocs/reference/libtracker-sparql/examples -I../docs/reference/libtracker-sparql/examples -Isrc -I../src -I/nix/store/w98bzaw8cgpd3h9vwhg0qs2qgm96wxg0-glib-2.66.8-dev/include/glib-2.0 -I/nix/store/l8k9ji93sb9yd6mfig1jgh4g0imr7ygx-glib-2.66.8/lib/glib-2.0/include -I/nix/store/w98bzaw8cgpd3h9vwhg0qs2qgm96wxg0-glib-2.66.8-dev/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wformat -Wformat-security -Wno-pointer-sign -DTRACKER_COMPILATION '-DG_LOG_DOMAIN="Tracker"' -DG_LOG_STRUCTURED=1 -MD -MQ docs/reference/libtracker-sparql/examples/writeonly-example.p/writeonly-example.c.o -MF docs/reference/libtracker-sparql/examples/writeonly-example.p/writeonly-example.c.o.d -o docs/reference/libtracker-sparql/examples/writeonly-example.p/writeonly-example.c.o -c ../docs/reference/libtracker-sparql/examples/writeonly-example.c
       > In file included from ../docs/reference/libtracker-sparql/examples/writeonly-example.c:1:
       > ../src/libtracker-sparql/tracker-sparql.h:36:10: fatal error: libtracker-sparql/tracker-sparql-enum-types.h: No such file or directory
       >    36 | #include <libtracker-sparql/tracker-sparql-enum-types.h>
       >       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       > compilation terminated.
       > [32/168] Generating tracker-enum-types.h with a custom command (wrapped by meson to capture output)ls[Kresdump.vala src/libtracker-sparql/tracker-sparql-3.0.vapi
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/rpaqyf426i2lv6q478kzfy2882cxgp30-tracker-3.0.3.drv'.
 ```
 The header is from `gnome3.tracker`, which seems to be passed
 ```
 $ nix-locate libtracker-sparql/tracker-sparql-enum-types.h
gnome3.tracker.dev                                  916 r /nix/store/cqdzv09xdwqbkz9ymajgmch5fs5n4lvb-tracker-3.0.1-dev/include/tracker-3.0/libtracker-sparql/tracker-sparql-enum-types.h
$ nix show-derivation /nix/store/biqlzpi9blxhqa270ppckdlz42visxbr-gtk+3-3.24.27.drv | grep tracker
      "/nix/store/rpaqyf426i2lv6q478kzfy2882cxgp30-tracker-3.0.3.drv": [
      "buildInputs": "/nix/store/ldzagpm90b9577ibxk6k73sgk8knm64k-libxkbcommon-1.1.0-dev /nix/store/3w4hvwb5bjrhafx5g0ahj020p8vy68zk-epoxy-1.5.4-dev /nix/store/s66rfjj9rpwbi2dls044jjn527x8vxd2-json-glib-1.6.2-dev /nix/store/z526yrbi0lmpcfcam8cccqgpmpj4h34d-iso-codes-4.6.0 /nix/store/w7glqhm22zhscawjhy1nv382ypr3d8cc-tracker-3.0.3-dev",
      "mesonFlags": "-Dgtk_doc=true -Dtests=false -Dtracker3=true -Dbroadway_backend=true",
```
I haven't pin-pointed the failing commit yet, but it looks like meson isn't getting the include path correctly.

cc @NixOS/gnome

**Comment by jonringer** [comment]
actually, this seems to be from the 32bit version failing to build, the 64bit builds fine.

**Comment by SFrijters** [comment]
I'm seeing the same issue - currently bisecting, but it's a long run that'll have to continue overnight for me.

**Comment by bkchr** [comment]
This https://github.com/NixOS/nixpkgs/pull/118365 fixes it for me

**Comment by jonringer** [comment]
This is odd, my server can build this just fine, but my desktop fails to build it...

**Comment by jonringer** [comment]
> actually, this seems to be from the 32bit version of `tracker` failing to build, the 64bit builds fine.

This is only because hydra has a cache hit on this.

**Comment by jbalme** [comment]
Does Hydra even build gtk3 32-bit anymore?

`https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.gtk3.i686-linux/latest` redirects to a build from 2017.

**Comment by avnik** [comment]
Happens with 64bit as well. Updating tracker to 3.1.1 fix it. (also require python-tap for new tests).  I can PR in a hour or so. (at least ti builds, but full system build will take ~36hours more, so I'd like if someone will be able build/test fast before merge

**Comment by vcunat** [comment]
@jbalme: the 32-bit tracker gets built on Hydra as dependency of some other jobs, e.g. wine or steam.

**Comment by mweinelt** [comment]
Bisected to

```
9d03ff52229f36ff4b4e9d0ee2db4a46b90512bb is the first bad commit
commit 9d03ff52229f36ff4b4e9d0ee2db4a46b90512bb
Author: Frederik Rietdijk <fridh@fridh.nl>
Date:   Wed Dec 30 14:49:10 2020 +0100

    python: reproducible builds
    
    Achieve reproducible builds of the interpreter. Note this meant
    disabling optimizations again.

 doc/languages-frameworks/python.section.md         | 17 ++++++++++
 nixos/doc/manual/release-notes/rl-2105.xml         |  6 ++++
 .../interpreters/python/cpython/2.7/default.nix    | 36 ++++++++++++++++------
 .../interpreters/python/cpython/default.nix        | 33 ++++++++++++--------
 4 files changed, 71 insertions(+), 21 deletions(-)
bisect run success
```

And indeed it fails differently after reverting that

```
25/31 tracker:data+slow / sparql                      FAIL             1.15s   killed by signal 5 SIGTRAP
```

**Comment by SFrijters** [comment]
Is this for the 32bit build, or 64, or both? And how does this interact with the update of tracker to 3.1.1?

**Comment by mweinelt** [comment]
This was for the i686-linux version of tracker. Sorry, should've mentioned that.

**Comment by SFrijters** [comment]
As far as I understand it now, #118365 exhibits the same test failure as above with tracker 3.1.1, without reverting 9d03ff5.
In my opinion this is an upstream bug (https://gitlab.gnome.org/GNOME/tracker/-/issues/292).
So I think the best option is to go to the new version and disable the two failing tests (if you disable this one there is another one that fails), as I also mentioned in the PR.

**Comment by mweinelt** [comment]
FWIW: tracker-3.0.3 for x86_64-linux builds with this revert.

**Comment by dschrempf** [comment]
A short question, I am using the nixpkgs-unstable channel but still, I am hit by this bug (where the test fails). Has this moved from master to unstable, or am I somehow compiling against master without my knowledge?

**Comment by teto** [comment]
you can check the git logs but I hit this on nixos-unstable so it has reached the channels.

**Comment by buckley310** [comment]
I'm curious how the nixos.iso_gnome test is passing while gnome is broken 🤔

**Comment by vcunat** [comment]
I think we're mixing two issues here.  One only happens sometimes (and the build farm got lucky and/or retried); the other only happens on i686 where tracker is _not_ in the release-critical set (nor its closure).

**Comment by dschrempf** [comment]
I consistently get the SIGTRAP error of the test.

**Comment by andoriyu** [comment]
Happens to me on amd64. Unless something is pulling 32bit packages...

**Comment by mweinelt** [comment]
> Happens to me on amd64. Unless something is pulling 32bit packages...

At least wine and steam do.

**Comment by jonringer** [comment]
> Unless something is pulling 32bit packages...

buildFHSUserEnv has a `multiPkgs` argument, which will build both 64 and 32 bit versions of everything defined. As there's many games which need a 32bit version to run, so this makes sense.

**Comment by lovesegfault** [comment]
The issue seems to have been fixed upstream: https://gitlab.gnome.org/GNOME/tracker/-/commit/57386f7e5a722a4b24ec503cb4cf1da57b44588c

**Comment by jbalme** [comment]
> > Unless something is pulling 32bit packages...
> 
> buildFHSUserEnv has a `multiPkgs` argument, which will build both 64 and 32 bit versions of everything defined. This was done because many games require 32bit versions of some libraries to be available.

I believe Steam itself is 32-bit, unless that changed in recent years.

> The issue seems to have been fixed upstream: https://gitlab.gnome.org/GNOME/tracker/-/commit/57386f7e5a722a4b24ec503cb4cf1da57b44588c

Any idea how long it will take until that makes it into a release? Should we keep it as a patch against 1.1.1 in the meanwhile?

**Comment by mweinelt** [comment]
@bkchr @SFrijters Can you try to apply that patch on top of 3.1.1?

**Comment by SFrijters** [comment]
@mweinelt Looking at the commits we need more than one patch since e.g. dad7a4b6 in the same MR adds the helper functions that are used to fix the issue. Quoting upstream https://gitlab.gnome.org/GNOME/tracker/-/issues/292#note_1076661

> GNOME 40.1 is scheduled for May 1st from a look at https://wiki.gnome.org/Forty. I'll be releasing Tracker 3.1.2 around then the latest :). In the mean time it's fair to pick the fix.

I don't know if there is a nice nix(pkgs) way to pick a range of commits as patches? Alternatively, is it allowed to go to version `unstable-2021-04-07` and use the non-master commit e1c060e3e495491ee424d21cb2d10abcd474f793 for the time being?

**Comment by jonringer** [comment]
> I don't know if there is a nice nix(pkgs) way to pick a range of commits as patches?

probably not, it may be easier to generate the patch from the repo itself, then just add the patch
```
patches = [
  ./fix-build.patch
];
```

**Comment by SFrijters** [comment]
I've followed vcunat's suggestion and prepared a commit at https://github.com/SFrijters/nixpkgs/commit/243f7213c7acaaf5bb690d37bb7ce49c1d94c29a .

**Comment by jonringer** [comment]
@SFrijters probably with using the PR #, is the PR is still open. If changes are pushed to it, then the patch will be come invalid for others, and we will see a sha mismatch.

**Comment by vcunat** [comment]
What about additional quick workaround?  #118823

**Comment by Lillecarl** [comment]
Unstable is indeed failing on me because of wine.

```
Summary of Failures:

26/31 tracker:data+slow / sparql                      FAIL             2.44s   killed by signal 5 SIGTRAP
------------------
error: builder for '/nix/store/rpaqyf426i2lv6q478kzfy2882cxgp30-tracker-3.0.3.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/biqlzpi9blxhqa270ppckdlz42visxbr-gtk+3-3.24.27.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fnip1p2y5h8prxy9p3a23j6vmc3vg2i2-wine-wow-6.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j8jz5cwl95jb5cavsnnyfr0m9d0nqcib-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4ds55dzz905vgfxv6237yg6qyhngcqaf-nixos-system-shitbox-21.05pre281004.3d1a7716d7f.drv' failed to build
```

**Comment by jonringer** [comment]
@Lillecarl 
> nixos-system-shitbox
Nice :)

**Comment by Lillecarl** [comment]
> @Lillecarl
> 
> > nixos-system-shitbox
> 
> Nice :)

![20210408_200007](https://user-images.githubusercontent.com/207073/114074907-3455dc00-98a5-11eb-9c6e-b30032eb4c95.jpg)
Very off topic but this is the one! :)

**Comment by vcunat** [comment]
NixPkgs master now has workarounds and [binaries](https://hydra.nixos.org/eval/1661519#tabs-now-succeed) in cache; I expect this commit will soon hit the `nixos-unstable` channel, too.

**Comment by davidak** [comment]
You will see here when it lands in unstable channel: https://nixpk.gs/pr-tracker.html?pr=118823
Thanks to everyone involved in fixing it!

**Comment by vcunat** [comment]
Weird, my git shows that it's in `nixos-unstable-small` already but that page disagrees.

**Comment by wedens** [comment]
> You will see here when it lands in unstable channel: https://nixpk.gs/pr-tracker.html?pr=118823

This page doesn't display it properly :( I've noticed it with several MRs that were already in nixos-unstable.

**Comment by vcunat** [comment]
For reference, the fix is in all the three channels already.

**Comment by jonringer** [comment]
> For reference, the fix is in all the three channels already.

I'm going to consider this issue closed, as the user experience is not impacted on updated channels. But a proper fix like https://github.com/NixOS/nixpkgs/pull/118365 should still be prioritized.
