### ISSUE TITLE
tome4 doesn't render screen

### ISSUE THREAD

**Issue by sindikat** [NixOS/nixpkgs#11815]
I install `tome4` (roguelike game, http://te4.org) and run it, and while the program runs and the sound is heard, there is no game screen. The first few lines of a debug messages are:

```
WebCore config: library(/nix/store/wfzy42pifghrpr7wdpsgg7mjh8qc7ryj-tome4-1.3.1/opt/tome4/libte4-web.so) spawn(/nix/store/wfzy42pifghrpr7wdpsgg7mjh8qc7ryj-tome4-1.3.1/opt/tome4/cef3spawn)
Loading WebCore: Failed loading /nix/store/wfzy42pifghrpr7wdpsgg7mjh8qc7ryj-tome4-1.3.1/opt/tome4/libte4-web.so: /nix/store/wfzy42pifghrpr7wdpsgg7mjh8qc7ryj-tome4-1.3.1/opt/tome4/libte4-web.so: cannot open shared object file: No such file o
[CPU] Detected 4 CPUs
OpenAL device available: OpenAL Soft (default OpenAL Soft)
Available video driver: x11
Available video driver: dummy
NO SELFEXE: bootstrapping from CWD
```

I can provide more trace. Can it be package's fault, because there's no file `libte4-web.so` present, because of underspecified dependencies? Or Nix has nothing to do with it?

**Comment by ktosiek** [comment]
It works for me, with the same store path. I do also see that message, so it might not be related to the problem you're having.

**Comment by Profpatsch** [comment]
(triage) Works here. I suggest we close. cc @jagajaga

**Comment by pSub** [comment]
Works for me as well. Please reopen if the problem remains.
