### ISSUE TITLE
xdvi isn't packaged with the new texlive infrastructure

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#11816]
I tried

    self.texlive.combine { inherit (self.texlive) scheme-medium xdvi; };

etc., but I did not manage to get my hands on an `xdvi` executable. Can I install that tool somehow with the new texlive infrastructure?

Cc: @vcunat

**Comment by vcunat** [comment]
No, I haven't packaged binaries for that one yet. For reference, it would be in https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/bin.nix.

**Comment by vcunat** [comment]
Christmas time! It works for my files. Hopefully it will for yours &ndash; otherwise I can try to fix...

**Comment by peti** [comment]
Works like a charm. Thank you so much!
