### ISSUE TITLE
freecad no longer builds

### ISSUE THREAD

**Issue by rowanG077** [NixOS/nixpkgs#118164]
**Describe the bug**
Freecad no longer builds since a `qtwebengine` was updated to `5.15.3` while the other qt modules are still at `5.15.2`. The error was introduced with [this](https://github.com/NixOS/nixpkgs/commit/3aba63ab29e4ed073c689e7e9995ca682d133173) commit:

```
CMake Error at /nix/store/rnaf9x5rfx8s0in4rzn3f6mfmy1xabc9-qtwebengine-5.15.3-a059e74-dev/lib/cmake/Qt5WebEngineCore/Qt5WebEngineCoreConfig.cmake:97 (find_package):
  Could not find a configuration file for package "Qt5Quick" that is
  compatible with requested version "5.15.3".

  The following configuration files were considered but not accepted:

    /nix/store/0wq9q2iimmpwpfilqnkh49fxcrj24irj-qtdeclarative-5.15.2-dev/lib/cmake/Qt5Quick/Qt5QuickConfig.cmake, version: 5.15.2

Call Stack (most recent call first):
  /nix/store/rnaf9x5rfx8s0in4rzn3f6mfmy1xabc9-qtwebengine-5.15.3-a059e74-dev/lib/cmake/Qt5WebEngineWidgets/Qt5WebEngineWidgetsConfig.cmake:97 (find_package)
  cMake/FreeCAD_Helpers/SetupQt.cmake:85 (find_package)
  CMakeLists.txt:69 (include)
```

**To Reproduce**
With the current master try to build `freecad`

**Expected behavior**
`freecad` builds successfully.

**Screenshots**
See attached build log
[freecad.log](https://github.com/NixOS/nixpkgs/files/6237893/freecad.log)
.

**Notify maintainers**
@viric @gebner @AndersonTorres
Although this is not the fault of the freecad package I think. So I will ping the person who updated qtwebengine as well.

@rnhmjoj 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.8, NixOS, 21.05pre271938.c7d0dbe094c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(rowan.goemans): `""`
 - channels(root): `"nixos-21.05pre279012.ad47284f8b0, nixos-hardware, stable-20.09.3654.3a8a85da229"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Although I used the local nixpkgs master to verify this issue.

**Comment by rnhmjoj** [comment]
I should have just fixed this error with #118084. Can you try again
after rebasing your branch?

**Comment by rowanG077** [comment]
It's building. I will let you know!

**Comment by bryanasdev000** [comment]
Can be the same for https://github.com/NixOS/nixpkgs/issues/118173

**Comment by rowanG077** [comment]
Can confirm freecad builds now, Thanks!
