### ISSUE TITLE
libva errors due to missing dependency on google-chrome

### ISSUE THREAD

**Issue by resolritter** [NixOS/nixpkgs#118240]
**Describe the bug**

when launching google-chrome

```
libva error: dlopen of /usr/lib/dri/radeonsi_drv_video.so failed: libLLVM-11.so: cannot open shared object file: No such file or directory
```

libva on google-chrome: 
https://github.com/NixOS/nixpkgs/blob/04a2b269d8921505a2969fc9ec25c1f517f2b307/pkgs/applications/networking/browsers/google-chrome/default.nix#L44

apparently the LLVM dependencies are included on Chromium, but not Chrome?

https://github.com/NixOS/nixpkgs/blob/04a2b269d8921505a2969fc9ec25c1f517f2b307/pkgs/applications/networking/browsers/chromium/default.nix#L29

**To Reproduce**
1. `NIXPKGS_ALLOW_UNFREE=1 nix-env -iA nixpkgs.google-chrome`
2. run `google-chrome-stable`

**Expected behavior**

Error shouldn't happen

**Additional context**

```
> uname -m
x86_64
```

```
> lshw -class display
  *-display                 
       description: VGA compatible controller
       product: Vega 10 XL/XT [Radeon RX Vega 56/64]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:2b:00.0
       version: c3
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
```

**Notify maintainers**

@primeos

**Comment by primeos** [comment]
Does this only print an error or does Chrome fail to launch?
From `dlopen of /usr/lib/dri/radeonsi_drv_video.so failed` I assume that this not on NixOS. GPU drivers are unfortunately handled in a pretty impure way (it's complicated) so this often causes issues, especially outside of NixOS.

The output of `ldd /usr/lib/dri/radeonsi_drv_video.so` might be helpful. Not sure if we can do something about this as it seems like `radeonsi_drv_video.so` (outside of the control of Nixpkgs) requires `libLLVM-11.so` (and depending on the OS/distro version it could depend on a different LLVM version). If you want/need VA-API support you might be able to use `$LD_LIBRARY_PATH`.

**Comment by resolritter** [comment]
Ah, right... I thought this could be solved by adding LLVM to the `.nix` file

If it's an external issue then I'll try to figure out on my own. Thanks.

> Does this only print an error or does Chrome fail to launch?

It only prints an error. It's not strictly necessary for running the program... Although GPU acceleration then gets disabled, which is unfortunate. Oh, well. Thanks for the response.
