### ISSUE TITLE
git annex assistant should probably have lsof as a dependency

### ISSUE THREAD

**Issue by ellis** [NixOS/nixpkgs#11824]
I'm currently running on nixos 15.09 and installed git-annex with assistant via:

> nix-env -iA nixos.haskellPackages.git-annex-with-assistant

When I started the assistant, it printed a disconcerting warning:

> % git annex assistant --autostart
> git-annex autostart in /home/ellis/repo/doc-ver
> git-annex: The lsof command is needed for watch mode to be safe, and is not in PATH.
> To override lsof checks to ensure that files are not open for writing
> when added to the annex, you can use --force
> Be warned: This can corrupt data in the annex, and make fsck complain.

Installing lsof resolved the problem.  Should lsof be made a dependency of git-annex?

**Comment by peti** [comment]
I think it's fine to have it as an optional dependency, especially considering that `git-annex` provides such a clear error message.

**Comment by jgillich** [comment]
Watching files is the entire point of the assistant, right? I don't think this should be treated as a optional dependency.

**Comment by garbas** [comment]
i would also expect nix to install ``lsof`` and sed needed files to use nix's lsof

**Comment by peti** [comment]
Well, a patch for `git-annex` that implements this properly would be welcome.

**Comment by mogorman** [comment]
in master its part of the package and has a executableSystemDepends of it.  Isn't that is all that is needed?

**Comment by Profpatsch** [comment]
(triage) Looks like it is patched in and solved, yes. cc @ellis @peti
