### ISSUE TITLE
teamviewer hash mismatch

### ISSUE THREAD

**Issue by glaebhoerl** [NixOS/nixpkgs#11840]
After adding `services.teamviewer.enable = true;` to `configuration.nix`, when trying `nixos-rebuild switch` I get:

    output path ‘/nix/store/40hxq02a8wv6d508yrb51l83kc47nrlc-teamviewer_amd64.deb’ should have sha256 hash ‘10risay1a5a85ijbjaz2vxqbfxygpxslvh0dvzz32k988hr9p1gk’, instead has ‘0j4al1wns22aaxn78s1c99kxxvkffi8lpdqk780h0nx2g4vcj96n’
    cannot build derivation ‘/nix/store/vkkvxnlfnmlckc4jbr3b5j68b08a1bfi-teamviewer-10.0.37742.drv’: 1 dependencies couldn't be built

I'm on the 15.09 channel and have done `nix-channel --update`.

    # nixos-version 
    15.09.706.45128de (Dingo)

(Also, with apologies for the unrelated question: `nix-env -qaP --description | grep -i teamviewer` returns zero results. Is enabling the service the only way to install it? Do I need to pass some special flags for `nix-env` to find it? I do have `nixpkgs.config.allowUnfree = true;`.)

**Comment by ktosiek** [comment]
That's because TeamViewer doesn't have stable URLs for their .debs (or any installers actually). They know about it, and don't really care (see also #970). You can use nixpkgs.config.teamviewer10.sha256 to override the current hash:

    nixpkgs.config.teamviewer10.sha256 = "0j4al1wns22aaxn78s1c99kxxvkffi8lpdqk780h0nx2g4vcj96n";

About the nix-env question: you need allowUnfree in ~/.nixpkgs/config.nix for that (nix-env won't look at configuration.nix). But TeamViewer won't work without the service anyway.

**Comment by glaebhoerl** [comment]
Thanks. That helped, but there were (and still are...) /many/ other problems as well. I opened https://github.com/NixOS/nixpkgs/pull/11872

**Comment by abbradar** [comment]
Is this still a problem after ca431d1db994194df89bb9bf4b54051aadb35027?

**Comment by layus** [comment]
@glaebhoerl It seems to me that teamviewer is now fixed, right ?
We would like to close this issue if it is no longer relevant to you.

**Comment by glaebhoerl** [comment]
Just tried: installed and started fine, but there is still no Connect button. (Of course, that's a separate issue.)

**Comment by layus** [comment]
Then maybe open a new issue and tag abbradar and/or jagajaga in it to get focus on this issue ?
I am no expert in teamviewer, but it seems more difficult to fix than a wrong hash.

**Comment by jarry9** [comment]
Can we please make a portable version of teamviewer: We can make a new package for portable teamviewer: https://github.com/NixOS/nixpkgs/issues/26137
