### ISSUE TITLE
steam-run: ALSA issues / no sound

### ISSUE THREAD

**Issue by cirno-999** [NixOS/nixpkgs#118448]
**Describe the bug**
I apologize for bothering you with such a trivial issue but this has been bothering me and I haven't been able to figure it out.
I have been trying to play the [DRM free](https://www.gog.com/game/umineko_when_they_cry_question_arcs) version of Umineko When They Cry: Question Arcs. It's a Ponscripter game. I've been using steam-run-native, which spits out these relevant bits:
```
ALSA lib pcm.c:2651:(snd_pcm_open_conf) Either /nix/store/rqw1c4qvsn3ql5ibx5jwznkpyd0bcay9-alsa-plugins-1.2.2/lib/alsa-lib/libasound_module_pcm_pulse.so cannot be opened or _snd_pcm_pulse_open was not defined inside
ALSA lib pcm.c:2651:(snd_pcm_open_conf) Either /nix/store/m0l6c4m1xbmyadj4cxldgq83xz3gq67x-alsa-plugins-1.2.2/lib/alsa-lib/libasound_module_pcm_pulse.so cannot be opened or _snd_pcm_pulse_open was not defined inside
Couldn't open audio device!
  reason: [ALSA: Couldn't open audio device: No such device or address].
  ```
meanwhile normal steam-run doesn't output these messages, but has no sound as well.
**To Reproduce**
1. Run Umineko When They Cry: Question Arcs (or any Ponscripter game? The engine should be free and open source, but I don't know how to compile it.) with steam-run
2. Get no sound

**Screenshots**
![image](https://user-images.githubusercontent.com/73712874/113500655-075d9e00-9520-11eb-8a3c-143bde560037.png)

**Additional context**
Rest of the game seems to work fine.
My sound config:
```
{ pkgs, ... }:

{
  sound.enable = true;
  hardware.pulseaudio.enable = true;
  hardware.pulseaudio.support32Bit = true;
  hardware.pulseaudio.package = pkgs.pulseaudioFull; # added recently during troubleshooting
}
```

**Notify maintainers**
Couldn't see but @jagajaga @jonringer were mentioned in steam.nix

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.104, NixOS, 20.09.3676.7640739f71e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-20.09.3676.7640739f71e, unstable-21.03pre257339.83cbad92d73"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
there's a convenient `programs.steam.enable = true;` which should bel able to configure everything for you now

**Comment by cirno-999** [comment]
> there's a convenient `programs.steam.enable = true;` which should bel able to configure everything for you now

Thanks, but I have all that manually configured so I think it's fine ;P (if I'm not mistaken)

Also. After upgrading today the sound in the game started working. (I switched to pipewire sometime ago, but it wasn't working then, still)

```
$ pipewire --v
pipewire
Compiled with libpipewire 0.3.30
Linked with libpipewire 0.3.30
```

```
[cirno@berlin:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.1268.21b696caf39, unstable-21.11pre292748.6933d068c5d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

I think it's good enough to close the issue, but feel free to ask further if you want.

**Comment by tazjin** [comment]
For anyone else running into this issue and finding this thread, I solved this exact problem by setting `services.pipewire.alsa.support32Bit = true;`.
