### ISSUE TITLE
Create opensnitch nixos module

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#118463]
## Issue description

A package for opensnitch was added in https://github.com/NixOS/nixpkgs/pull/117893, but it is not easy to use.

There is a How To from @onny: https://blog.project-insanity.org/2021/04/01/setup-opensnitch-on-nixos/

It would be great to have a nixos module to set it up.

cc @raboof

**Comment by raboof** [comment]
This would indeed be great! There's even some existing work in #76897, but I didn't want to just blindly copy that approach without first understanding whether that is (still) the way that makes most sense ;) )

**Comment by chuahou** [comment]
This was done in #132319, so I'm closing this. Please reopen if there's a need to, thanks.
