### ISSUE TITLE
python-modules/cartopy: globe tests fail

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#118449]
**Describe the bug**

cartopy is currently marked broken because various tests are failing

**To Reproduce**

```
$ NIXPKGS_ALLOW_BROKEN=1 nix-shell -p python3Packages.cartopy
(...)
= 4 failed, 495 passed, 2 skipped, 113 deselected, 2 xfailed, 133 warnings in 7.21 seconds =
```

**Notify maintainers**

@mredaelli 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.26, NixOS, 21.05.git.04a2b269d89 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/home/aengelen/nixpkgs`

**Comment by lsix** [comment]
Those tests fail because `numpy` adds some new `warnings`. Those tests actually count the warning during certain operations, and the new `numpy` warnings mess with the count.

I have a PR that disables those tests (#119168) for the time being. I have also reported the issue upstream.
