### ISSUE TITLE
Undetected screen resolution

### ISSUE THREAD

**Issue by Martin-Masson** [NixOS/nixpkgs#118423]
## Issue Description
I installed NixOS just a few days ago and took the same configuration of a friend of mine. His screen is rather standard 1080p while mine is a 2560x1600. All the windows are zoomed out and all the text is thus very tiny. Can anyone help me figure out how to solve this ?

I've looked in the config files and didn't find anything related to screen resolution. I might need to specify that my friend help me for almost the entire installation as he is way more aquainted with NixOS than I am.

**Metadata**
- system: `"x86_64-linux"`
 - host os: `Linux 5.11.9, NixOS, 20.09.3670.310885ec804 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3670.310885ec804, nixos-unstable-21.05pre279012.ad47284f8b0"`
 - channels(martin): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fuzzypixelz** [comment]
If you are running X, try setting `services.xserver.dpi` to an appropriate value.
See https://www.sven.de/dpi/ for example.
However, according to the [Arch Wiki](https://wiki.archlinux.org/index.php/HiDPI), 

> For Xft.dpi, using integer multiples of 96 usually works best, e.g. 192 for 200% scaling.

Also, for GNOME/KDE and friends, there is usually a font scaling option in the settings.

**Comment by Martin-Masson** [comment]
I try settings it to 138 (for 150% zoom since 192 was too much) and it worked perfectly fine.
Thanks for the help !
