### ISSUE TITLE
Discord silently fails to open links in firefox

### ISSUE THREAD

**Issue by ooesili** [NixOS/nixpkgs#118432]
**Describe the bug**

I use Firefox as a web browser. When I click on links in discord, nothing happens. If I run `Discord` from the command line there no errors are displayed when clicking on links.

I used `strace` to see what discord was doing and found the exact `execve` call to `firefox` that is failing. I used that debug information to create a shell script that invokes `execve` with the same args and environment variables and ran that directly and saw the following error message:

```
XPCOMGlueLoad error for file /nix/store/chvdh5g7516rd7krss8pjsxb63naqnhp-firefox-unwrapped-87.0/lib/firefox/libxul.so:
/nix/store/bli00bnggzsir939wzy6b0jr2myw2qvd-nss-3.56/lib/libnss3.so: version `NSS_3.58' not found (required by /nix/store/chvdh5g7516rd7krss8pjsxb63naqnhp-firefox-unwrapped-87.0/lib/firefox/libxul.so)
Couldn't load XPCOM.
```
One of the environment variables that I noticed was `LD_LIBRARY_PATH` which is set by [a wrapper script around discord](https://github.com/NixOS/nixpkgs/blob/577a220c1650ea8d1f0ed56c305235f92371b4fe/pkgs/applications/networking/instant-messengers/discord/base.nix#L52). I also noticed that firefox and discord are built against different versions of `nss`. Firefox uses the `nss_latest` attribute and Discord uses `nss`. Discord forks and execs firefox when you click on a link, and the `LD_LIBRARY_PATH` environment variable that is set by the discord wrapper script is inherited by the firefox process which points firefox at a *different* version of nss than what it is compiled with.

As a temporary workaround, I made a local fork of the discord derivation that uses `nss_latest` instead of `nss` and links are working now. I would have made a PR but that feels like a fragile workaround because discord and firefox should not need to be compiled against the same version of nss. I think the proper fix is to use a different mechanism to point discord at the the paths in `LD_LIBRARY_PATH` so that it is not inherited by child processes, but I'm not quite sure how to do that.

**To Reproduce**

1. Install firefox and discord
2. Make sure that firefox is set as the default browser
3. Open firefox and discord
3. Try to click on a link in discord

**Notify maintainers**
@ldesgoui  @MP2E @tadeokondrak 

**Metadata**

```
- system: `"x86_64-linux"`
- host os: `Linux 5.4.108, NixOS, 20.09.3662.d88cdc7bc1a (Nightingale)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.10`
- channels(ooesili): `""`
- channels(root): `"nixos-20.09.3662.d88cdc7bc1a, unstable-21.05pre279012.ad47284f8b0"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- discord
# a list of nixos modules affected by the problem
module: []
```

**Comment by ldesgoui** [comment]
There's a wrapper to `firefox` that appends to `LD_LIBRARY_PATH`, shouldn't it prepend instead? https://github.com/NixOS/nixpkgs/blob/42a03e4728fc05cb9f123057670e41967f628360/pkgs/applications/networking/browsers/firefox/wrapper.nix#L124

**Comment by fuzzypixelz** [comment]
Also, why does Discord fork `firefox-unwrapped` according to the error message?

**Comment by ldesgoui** [comment]
By fork, do you mean launch the subprocess? I think that's just what `xdg-open` does

**Comment by fuzzypixelz** [comment]
Shouldn't it be the wrapped `firefox` instead?

**Comment by ldesgoui** [comment]
It does call the wrapper script, wihch appends to `LD_LIBRARY_PATH` so the paths set by `discord`'s wrapper are found and used first, hence the issue of `firefox-unwrapped` failing to start as it needs `nss_latest` and is given `nss`

**Comment by ooesili** [comment]
> By fork, do you mean launch the subprocess? I think that's just what `xdg-open` does

Yes I do mean this. I had my `strace` goggles on and was thinking in terms of system calls (launching a process involves `fork(2)`-ing the current process and `execve(2)`-ing the program)

**Comment by ooesili** [comment]
> There's a wrapper to `firefox` that appends to `LD_LIBRARY_PATH`, shouldn't it prepend instead?
> 
> https://github.com/NixOS/nixpkgs/blob/42a03e4728fc05cb9f123057670e41967f628360/pkgs/applications/networking/browsers/firefox/wrapper.nix#L124

I think you're right about this. I dug through the commit history for that `wrapper.nix` file and it doesn't look like there was any particular reason for using `--suffix` over `--prefix`. I also noticed that `--prefix` is used in most derivations in this repo, so it's probably a safe bet.

```
nixpkgs $ rg -- '--suffix LD_LIBRARY_PATH' | wc -l
19
nixpkgs $ rg -- '--prefix LD_LIBRARY_PATH' | wc -l
179
```

I'll make a PR if a contributor can give me a 👍🏻 on the approach. The firefox derivation scares me a little bit and I'm not sure what consequences that change might have.
