### ISSUE TITLE
Unstable channel hasn't updated in 2 weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#11865]
https://github.com/nixos/nixpkgs-channels is currently at a commit that's 13 days old. The channel appears to be stuck mostly because of failing Chromium and kde4 tests at https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents.

**Comment by vcunat** [comment]
The problem with `telepathy_qt` not building was fixed some time ago and Hydra even has binaries for it already.

**Comment by Mathnerd314** [comment]
Past issues: #7083 #7589 #8057 #10353 #11097.

I think this is more a problem with Hydra than with nixpkgs...

**Comment by vcunat** [comment]
I'm getting loads of timeouts just on evaluation, consistently during the last months most of staging attempts seem to timeout...

**Comment by domenkozar** [comment]
There are issues with tests itself, like https://hydra.nixos.org/build/29218960/nixlog/1/raw

**Comment by domenkozar** [comment]
cc @aszlig I have a feeling that tests are indeed way slower now without `msize`. We should definately look into moving `9p` into fuse.

**Comment by ttuegel** [comment]
Evaluation is now failing with
```
hydra-eval-jobs returned signal 6:
warning: SQLite database is busy
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

**Comment by domenkozar** [comment]
@ttuegel I've forced an eval, let's see.

Current culprit are tests, they timeout now. I think https://github.com/NixOS/nixpkgs/commit/a5bc11f9eb70482daf559019f9b775c285defb63 made things worse by making `9p` really slow (that was the intention of bigger `msize`).

**Comment by domenkozar** [comment]
It worked, but all tests still fail: http://hydra.nixos.org/eval/1235190

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs-channels/tree/nixpkgs-unstable is even farther behind, having last updated a month and a half ago :frowning:

**Comment by domenkozar** [comment]
That's due to darwin: http://hydra.nixos.org/build/29453741/nixlog/1/raw

**Comment by copumpkin** [comment]
@domenkozar that should be fixed now by https://github.com/NixOS/nixpkgs/commit/527f3574b7ecf317b1873165a1724715a801ba21, thanks!

**Comment by dezgeg** [comment]
I don't think the 9p tweaks are causing the test breakage, since they're quite broken on 15.09 as well: http://hydra.nixos.org/job/nixos/release-15.09/tested#tabs-constituents, and those changes weren't cherry-picked there.

**Comment by domenkozar** [comment]
@dezgeg Eelco fixed that today (it was a Nix bug). I've fixed Chromium (hopefully, it did build locally).

What's left is:

- lvm test fails due to missing `/mnt` mount http://hydra.nixos.org/build/29615754/nixlog/2/raw
- firewall test fails to resolve DNS http://hydra.nixos.org/build/29614963/log/raw

**Comment by domenkozar** [comment]
Actually tested job is totally broken..

**Comment by vcunat** [comment]
[On 15.09 it is also rather broken](http://hydra.nixos.org/job/nixos/release-15.09/tested#tabs-constituents) ATM, but there it's waiting to evaluate a forced rebuild, so maybe it's not really that bad.

**Comment by vcunat** [comment]
Now we're getting thousands of abortions due to *unexpected end of file*.

**Comment by domenkozar** [comment]
Yeah, hopefully @edolstra will have time to look at it soon :)

**Comment by exi** [comment]
Wow, if i run the current master firefox.nix test, it fails immediately.

If I just put a "sleep 15" in nixpkgs/nixos/modules/virtualisation/qemu-vm.nix:385 to force a random rebuild, it works sometimes.

This looks like a weird timing bug + something i cannot identify => why does it work if i force a local rebuilt?

**Comment by obadz** [comment]
Any idea what causes this error?

http://hydra.nixos.org/build/29873328/log#line-1262

```
cleaning up
killing backend1 (pid 65)
killing proxy (pid 76)
killing client (pid 87)
killing backend2 (pid 98)
vde_switch: EOF on stdin, cleaning up and exiting
vde_switch: Could not remove ctl dir '/tmp/nix-build-vm-test-run-proxy.drv-0/vde1.ctl': Directory not empty
builder for ‘/nix/store/xfwy21mpamrrlmh8956hfjfv5ryxhr9p-vm-test-run-proxy.drv’/...-vm-test-run-proxy.drv’ failed with exit code 255
```

**Comment by domenkozar** [comment]
I think it was out of HDD on hydra (which should be fixed now).

**Comment by domenkozar** [comment]
28 days.

**Comment by domenkozar** [comment]
swraid test is failing with out of memory exception, reverting https://github.com/NixOS/nixpkgs/commit/00aac09d24343b7beb8a07cbd5affdb110199c67 actually fixes it but then following error occurs:

```
machine: must succeed: nixos-rebuild switch >&2
machine# > > > > > > > > > > > > > > > > > > > building Nix...
machine# [    9.366267] dhcpcd[692]: eth0: probing for an IPv4LL address
machine# [    9.495965] systemd[1]: Started Nix Daemon.
machine# [    9.502463] nix-daemon[716]: accepted connection from pid 715, user root (trusted)
machine# [    9.619185] nix-daemon[716]: accepted connection from pid 719, user root (trusted)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/37lk94lzfgmf3x3si23bi7xwgrhyy177.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/6flnja8068w1lwnhjw88f9lsgf77lg89.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/fl641x87p42i4r0nf74brm6lwjvapa4g.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/aymhkd65g8fy03ar4c3yssp180dnh4pv.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/4l3nkwjv4z2lvkhxr1i94f4lqw5isswn.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/w3y63q62a4y99m9j51zx05acspw1wxkq.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/z4z6la8bkkhc227n68vrq7zqbfdmrw4b.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/k8i9i1vmlipaxajj95bgn2zjkdmz36v7.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/k0vqprjmxybr7clvfljk13zsdjwklcch.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/nyw8s7kqbwapr0hlx3xxw6j3zqa1dlsx.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/ldj18wicxhjf0739kr08p0rbnsby7zr9.narinfo’ (Curl error 6)
machine# these derivations will be built:
machine#   /nix/store/4z0jdl9baq0sv7353n5xv738bxinx08x-bootstrap-tools.tar.xz.drv
machine#   /nix/store/8pvv9kjda7hs0mrrn9km3f5wmhp3fygs-mirrors-list.drv
machine#   /nix/store/6brhkj9bxyg56jhj62m2gvnjn5nm38dy-nix-1.10.tar.xz.drv
machine#   /nix/store/pi866p41dsp26rlpq5r79h2a35gx2vrn-busybox.drv
machine#   /nix/store/rlbfc41y1hkdhympy67lbfg8r6nc93ab-bootstrap-tools.drv
machine#   /nix/store/x40as51v8pj51s33l8hmziqrx8dcs8vc-stdenv-linux-boot.drv
machine#   /nix/store/zrlcc9g3vw579c3vskvgb387ad7x6gjy-mirrors-list.drv
machine#   /nix/store/l3ibd0rcvaqq0n8p5j780b0gw9zyykpc-pkg-config-0.29.tar.gz.drv
machine#   /nix/store/q1rl94kqphsx90hd765vwxc2vk8l0d48-pkg-config-0.29.drv
machine#   /nix/store/mq209nls1l67nrhv6qxqak7c60wxipz5-nix-1.10.drv
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/37lk94lzfgmf3x3si23bi7xwgrhyy177.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/6flnja8068w1lwnhjw88f9lsgf77lg89.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/aymhkd65g8fy03ar4c3yssp180dnh4pv.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/fl641x87p42i4r0nf74brm6lwjvapa4g.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/4l3nkwjv4z2lvkhxr1i94f4lqw5isswn.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/w3y63q62a4y99m9j51zx05acspw1wxkq.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/k0vqprjmxybr7clvfljk13zsdjwklcch.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/k8i9i1vmlipaxajj95bgn2zjkdmz36v7.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/z4z6la8bkkhc227n68vrq7zqbfdmrw4b.narinfo’ (Curl error 6)
machine# building path(s) ‘/nix/store/4l3nkwjv4z2lvkhxr1i94f4lqw5isswn-mirrors-list’
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/nyw8s7kqbwapr0hlx3xxw6j3zqa1dlsx.narinfo’ (Curl error 6)
machine# download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/ldj18wicxhjf0739kr08p0rbnsby7zr9.narinfo’ (Curl error 6)
machine# building path(s) ‘/nix/store/nyw8s7kqbwapr0hlx3xxw6j3zqa1dlsx-bootstrap-tools.tar.xz’
machine# downloading ‘http://tarballs.nixos.org/stdenv-linux/x86_64/8d66a51a872af1ab58edc68a2ebddcc79958b563/bootstrap-tools.tar.xz’...
machine# error: unable to download ‘http://tarballs.nixos.org/stdenv-linux/x86_64/8d66a51a872af1ab58edc68a2ebddcc79958b563/bootstrap-tools.tar.xz’: Couldn't resolve host name (6)
machine# builder for ‘/nix/store/4z0jdl9baq0sv7353n5xv738bxinx08x-bootstrap-tools.tar.xz.drv’ failed with exit code 1
machine# cannot build derivation ‘/nix/store/rlbfc41y1hkdhympy67lbfg8r6nc93ab-bootstrap-tools.drv’: 1 dependencies couldn't be built
machine# building path(s) ‘/nix/store/aymhkd65g8fy03ar4c3yssp180dnh4pv-nix-1.10.tar.xz’
machine# cannot build derivation ‘/nix/store/l3ibd0rcvaqq0n8p5j780b0gw9zyykpc-pkg-config-0.29.tar.gz.drv’: 1 dependencies couldn't be built
machine# cannot build derivation ‘/nix/store/q1rl94kqphsx90hd765vwxc2vk8l0d48-pkg-config-0.29.drv’: 1 dependencies couldn't be built
machine# cannot build derivation ‘/nix/store/mq209nls1l67nrhv6qxqak7c60wxipz5-nix-1.10.drv’: 1 dependencies couldn't be built
machine# error: build of ‘/nix/store/mq209nls1l67nrhv6qxqak7c60wxipz5-nix-1.10.drv’ failed
machine: exit status 1
machine: output: 
error: command `nixos-rebuild switch >&2' did not succeed (exit code 1)
```

**Comment by copumpkin** [comment]
@domenkozar that looks like my `ec2-config` test failing, but I see no indication of my test being in there. Can you disable `ec2-config` for now and see if that fixes it?

**Comment by domenkozar** [comment]
Probably most of the tests fail this way. I'll bisect. @ttuegel any idea why would above revert fix the issue?

**Comment by ttuegel** [comment]
@domenkozar No idea, looks totally unrelated.

**Comment by domenkozar** [comment]
@rickynils the above test fails to build because of ca0c46040649ab4a6d5d7bc838b393fdcbcae10c, you can test it with `nix-build -A tests.installer.swraid.x86_64-linux nixos/release.nix`. You'll probably have to revert https://github.com/NixOS/nixpkgs/commit/00aac09d24343b7beb8a07cbd5affdb110199c67 first to get rid of message `out of memory`

**Comment by ttuegel** [comment]
@domenkozar I realized why 00aac09 causes the swraid test to fail: the swraid test uses `nix-env -i` instead of `nix-env -iA`, so nix-env is searching through the entire package set. That commit adds many new packages.

**Comment by obadz** [comment]
@ttuegel nice catch!

**Comment by domenkozar** [comment]
@ttuegel fixed in 313fa2ebc69aa9b49055c6242ae6d4b78e9f0467.

@rickynils I've reverted ca0c46040649ab4a6d5d7bc838b393fdcbcae10c. since it's blocking a channel update. Sorry I couldn't find time to fix the issue, please open a PR and make sure one of the installer tests is passing.

**Comment by rickynils** [comment]
@domenkozar no problems, I'll look into it.

**Comment by lethalman** [comment]
I'm seeing new errors in nixos tests:
```

**Comment by lethalman** [comment]
I'm seeing new errors in nixos tests (http://hydra.nixos.org/build/30325559/log/raw):
```
machine# qemu-system-x86_64: -drive index=0,id=drive1,file=/tmp/nix-build-vm-test-run-installer-btrfsSimple.drv-0/vm-state-machine/machine.qcow2,if=virtio,cache=none,werror=report: file system may not support O_DIRECT
machine# qemu-system-x86_64: -drive index=0,id=drive1,file=/tmp/nix-build-vm-test-run-installer-btrfsSimple.drv-0/vm-state-machine/machine.qcow2,if=virtio,cache=none,werror=report: Could not open '/tmp/nix-build-vm-test-run-installer-btrfsSimple.drv-0/vm-state-machine/machine.qcow2': Invalid argument
vde_switch: EOF data port: No such file or directory
error: the VM quit before connecting
```

Is that an out of disk space?

**Comment by dezgeg** [comment]
The `file system may not support O_DIRECT` makes me think it could be related to the `cache=none` change in 6353f580f90c0fdd2b418fa853a78ec508bda2a5

**Comment by lethalman** [comment]
@dezgeg that's not supposed to be a problem, it's only a notice

**Comment by dezgeg** [comment]
To me that sounds like the `/tmp` filesystem is incapable of being used for `cache=none` disk access, which makes QEMU then error out.

**Comment by domenkozar** [comment]
That's unfortunate, it seems to not work with fuse and journaled FS: http://www.mygnu.de/index.php/2012/02/qemu-kvm-with-cachenone-fails-on-ext4-filesystem-with-journal_data-option/

I'll revert.

**Comment by jgeerds** [comment]
This looks much better: https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents

**Comment by domenkozar** [comment]
Yes, it was a long fight but it appears we'll get a channel tomorrow.

**Comment by obadz** [comment]
Thanks for pushing this through @domenkozar! :clap:

**Comment by NeQuissimus** [comment]
:clap:

**Comment by vcunat** [comment]
Great work! The `tested` job succeeded twice in a row now. The big channel hasn't updated yet, but that's probably only waiting for non-critical builds to finish.

**Comment by lethalman** [comment]
Yep. Let's close this?

**Comment by domenkozar** [comment]
updated.
