### ISSUE TITLE
p7zip wrapper reveals password

### ISSUE THREAD

**Issue by Donaim** [NixOS/nixpkgs#118654]
**Describe the bug**
7z supports encryption via `-p` CLI switch. 
The issue with it being a CLI argument is that password may be visible from ex. htop.
The solution that 7z uses is that it modifies its process info so that the password is replaced by "*".

However, nixos runs 7z executable via wrapper script:
```
#!/nix/store/$hash-bash-4.4-p23/bin/sh
"/nix/store/$hash-p7zip-17.01/lib/p7zip/7z" "$@"
```
Now "bash" does not hide its CLI arguments, so the password is visible again.

**To Reproduce**
1. truncate -s 10G temporary # create experimental file
2. 7z a -p1234 x.7z temporary
3. ps -af | grep "7z.*temporary"
4. echo wow # observe the password in plaintext

**Expected behavior**
Password is hidden.

**Additional context**
7z version:
```
readlink -f $(which 7z)
/nix/store/kb39lv96mdcpzxqn3k6yrc4rnc6rv81i-p7zip-17.01/bin/7z
```

**Notify maintainers**
@7c6f434c

**Metadata**
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 20.09.3670.310885ec804 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(admin): `"nixos-unstable-21.05pre279456.04a2b269d89, nixpkgs-20.09.3732.91b77fe6942"`
 - nixpkgs: `/home/admin/.nix-defexpr/channels/nixpkgs`
```

**Possible solution**
Add `exec` to the wrapper script, so the bash process will be replaced by 7z process

**Comment by vcunat** [comment]
I think this approach for hiding (parts of) CLI is racy in principle, i.e. the original CLI will be visible for a split-second anyway (even with unwrapped 7z directly), but it still seems better to do the imperfect protection anyway.

**Comment by buckley310** [comment]
If I'm reading this all correctly, it looks like the correct place to fix this issue is upstream:
https://github.com/jinfeihan57/p7zip/blob/295dac87f657de12f6165cb9d81404e079651a50/install.sh#L12-L13
An upstream PR to add the `exec` keyword seems appropriate. I can probably double-check this tomorrow and write one.

**Comment by buckley310** [comment]
Lets see where this goes https://github.com/jinfeihan57/p7zip/pull/136

**Comment by buckley310** [comment]
Upstream has just merged the patch. I suppose we wait for the next stable release now.

**Comment by Donaim** [comment]
Hi @patka-123 

I cannot verify this at the moment because I switched to Guix some time ago.
But I think this issue does not depend on my particular setup, and anyone can verify the fix.

**Comment by buckley310** [comment]
P7zip 17.05 does not contain the fix.

**Comment by buckley310** [comment]
We could close the issue anyway IMO, since the bug isn't affecting OP anymore.
Passwords on the commandline are a known bad practice, and upstream did accept the patch.
