### ISSUE TITLE
Meld GTK icons missing

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#118621]
**Describe the bug**

Meld can't find any GTK icons, and doesn't render text.

**To Reproduce**

Install meld under 20.09. Open two directories under meld (i.e. `meld dir1/ dir2/`)

**Expected behavior**

Useful directory diffs etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/127548/113614001-c4c2c100-9606-11eb-8f09-257f31e41270.png)

**Additional context**

This is installed from most recent 20.09, via home-manager.

The console meld was run from produces error logs like:
```
Traceback (most recent call last):
  File "/nix/store/q1fgpmgk5yvqzyl0llfxk8qc3qrgdb8p-meld-3.21.0/lib/python3.8/site-packages/meld/ui/emblemcellrenderer.py", line 76, in do_render
    pixbuf = self._get_pixbuf(self.icon_name, self._icon_size)
  File "/nix/store/q1fgpmgk5yvqzyl0llfxk8qc3qrgdb8p-meld-3.21.0/lib/python3.8/site-packages/meld/ui/emblemcellrenderer.py", line 64, in _get_pixbuf
    pixbuf = icon_theme.load_icon(name, size, 0).copy()
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'folder' not present in theme hicolor (0)
cairo.Error: Context.restore() without matching Context.save()
cairo.Error: Context.restore() without matching Context.save()
cairo.Error: Context.restore() without matching Context.save()
cairo.Error: Context.restore() without matching Context.save()
```

entries are triggered as the mouse moves over the meld window

**Notify maintainers**

@jtojnar @mimame

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.97, NixOS, 20.09.3124.2118cf551b9 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-20.09.3732.91b77fe6942, nixpkgs-20.09.3732.91b77fe6942"`
 - channels(judson): `"home-manager-20.09, nixpkgs-20.09.3732.91b77fe6942"`
 - nixpkgs: `/home/judson/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
This should be fixed by https://github.com/NixOS/nixpkgs/commit/f02fc10d0dd79559de62e265da091d58f251a030, if someone wants it in 20.09, they will need to backport it.

**Comment by nyarly** [comment]
I thought this had been pulled into unstable, but `https://github.com/nixos/nixpkgs-channels/archive/4762fba469e2baa82f983b262e2c06ac2fdaae67.tar.gz` doesn't appear to have it (unstable as of 3/3/21)

If I need to bring it in by copying, that's fine. A backport seems warranted, since it's effectively broken there.
