### ISSUE TITLE
python38Packages.weasyprint: broken tests

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixpkgs#118625]
**Describe the bug**
Seems to be missing/incorrect fonts used during testing.

**To Reproduce**
1. https://hydra.nixos.org/job/nixpkgs/trunk/python38Packages.weasyprint.x86_64-linux
2. `nix build https://github.com/NixOS/nixpkgs/archive/master.tar.gz#python38Packages.weasyprint -L`

**Expected behavior**
passed tests, successful build

**Additional context**
Attempted to add fonts via the FONTCONFIG_FILE variable which did make a few of the font tests pass, but could not figure out how to make the rest pass.

Looked at Cairo, but it seems 1.16.0 is exactly what is needed for weasyprint.

Maintainer information:
```yaml
python38Packages.weasyprint
sourcehut.metasrht
```

**Comment by misuzu** [comment]
@elohmeier could you please take a look at this?

**Comment by malte-v** [comment]
In the meantime, does anyone have a workaround? I've tried the following, but the tests still run.
```nix
nixpkgs.overlays = [
  (final: prev: {
    python = prev.python.override {
      packageOverrides = pythonFinal: pythonPrev: {
        weasyprint = pythonPrev.weasyprint.overrideAttrs (_: {
          doCheck = false;
        });
      };
    };
  })
];
```

**Comment by austinbutler** [comment]
I think it's likely we're hitting this: https://github.com/Kozea/WeasyPrint/issues/1333

Locally I tried using the `52.x` branch with the Nix package and while it doesn't fully work yet it's past the point I was at before where it stopped during testing and just uses increasingly more memory.

**Comment by austinbutler** [comment]
Tried the linked patch instead and that seems to fix it. I'll get a PR going.

**Comment by d3zd3z** [comment]
> In the meantime, does anyone have a workaround?

I was able to get it to build by commenting out the `pytest -k 'not test_font_stretch'` line (with a `#`).

**Comment by mweinelt** [comment]
The package builds on master, not sure what your comment is about.

**Comment by d3zd3z** [comment]
> The package builds on master, not sure what your comment is about.

Yeah, realized my comment was too late, now that it has been fixed.
