### ISSUE TITLE
toybox: fetchTarball uses toybox's tar implementation and fails

### ISSUE THREAD

**Issue by RasmusRendal** [NixOS/nixpkgs#118651]
**Describe the bug**
When trying to enter a nix-shell using fetchTarball and having toybox installed, I get the following error:
```
tar: Unknown option 'strip-components' (see "tar --help")
error: program 'tar' failed with exit code 1
```

**To Reproduce**
Create a nix-shell that uses fetchTarball like such:
```nix
let
  unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) { };
in
  unstable.mkShell {
    buildInputs = with unstable; [ unstable.gcc ];

  }
```
while having toybox available (I had it in home-manager).

**Expected behavior**
The same implementation of tar should be used for fetchTarball, whether I have toybox installed or not.

**Additional context**
The example is just one I drew up real quick, it happens with all the tarballs I try from GitHub.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.107, NixOS, 20.09.3732.91b77fe6942 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3732.91b77fe6942"`
 - channels(rendal): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hmenke** [comment]
Cannot reproduce. I saved your code as `shell.nix` and ran `nix-shell`.

Unrelated: Unquoted URLs are deprecated.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.10, NixOS, 20.09.20210404.cadb063 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - nixpkgs: `/etc/nixpkgs`

**Comment by RasmusRendal** [comment]
Turns out, the issue is caused when having toybox installed, in the normal `/etc/nixos/configuration.nix` or in home-manager.

**Comment by hmenke** [comment]
This is acutally a bug in Nix (only in 2.3, not in 2.4) and should be migrated.  From the Nix source:
```cpp
            // FIXME: this requires GNU tar for decompression.
            runProgram("tar", true, {"xf", store->toRealPath(storePath), "-C", tmpDir, "--strip-components", "1"});
```
https://github.com/NixOS/nix/blob/2.3.10/src/libstore/download.cc#L913-L914

**Comment by RasmusRendal** [comment]
It has been migrated. Thank you for the help, hmenke!
