### ISSUE TITLE
enabling virtualisation.podman.enableNvidia leads to a corrupt /etc/containers/containers.conf

### ISSUE THREAD

**Issue by herredgar** [NixOS/nixpkgs#118680]
**Describe the bug**

`enableNvidia` creates a defect `containers.conf` as the `[engine]` block is defined two times.

```bash
[network]
cni_plugin_dirs = ["/nix/store/qhhgkk70ygsiqiq6fnnffh0hs5hqd92b-cni-plugins-0.9.1/bin/"]

[engine]
init_path = "/nix/store/nyfxrp429882i8a9wsyq3h3bdq1h6vdm-catatonit-0.1.5/bin/catatonit"

[engine]
conmon_env_vars = ["PATH=/nix/store/j154cm1ibgk5n351zacwjb83pv34da1q-nvidia-podman/bin"]

[engine.runtimes]
nvidia = ["/nix/store/j154cm1ibgk5n351zacwjb83pv34da1q-nvidia-podman/bin/nvidia-container-runtime"]
```

```bash
$ podman

ERRO[0000] error reading system config "/etc/containers/containers.conf": unable to decode configuration /etc/containers/containers.conf: Near line 7 (last key parsed ''): Key 'engine' has already been defined. 
```

**To Reproduce**

Enable `podman` and `enableNvidia`

```nix
virtualisation.podman.enable = true;
virtualisation.podman.enableNvidia = true;
```

**Expected behavior**
`init_path` and `common_env_vars` should be merged to one `engine` block.

**Additional context**
I'm on zfs.

**Notify maintainers**
@cpcloud 

**Metadata**

- system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05pre281004.3d1a7716d7f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(plumps): `"nixos-unstable-21.05pre280949.fae6b041601"`
 - channels(root): `"nixos-21.05pre281004.3d1a7716d7f, nixos-unstable-21.05pre281004.3d1a7716d7f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by cpcloud** [comment]
I have a PR up to fix this https://github.com/NixOS/nixpkgs/pull/118409
