### ISSUE TITLE
CUPS cannot print to network printer due to mdns timeouts

### ISSUE THREAD

**Issue by wentasah** [NixOS/nixpkgs#118628]
**Describe the bug**

When printing to Brother MFC-L2700DW printer (with [this package](https://github.com/wentasah/nix-conf/blob/main/pkgs/mfcl2700dwcupswrapper.nix) created from a similar model in nixpkgs), CUPS often (but not always) complains about "_Impossible to connect to printerCCB4208.local: Name or service not known_" even though I followed the [instructions from NixOS wiki](https://nixos.wiki/wiki/Printing#Client_.28Linux.29) and enabled `services.avahi.nssmdns`.

**To Reproduce**
1. Get Brother MFC-L2700DW printer.
2. Configure NixOS as follows:
   ```nix
   {
     services.printing.enable = true;
     services.printing.drivers = with pkgs; [
       mfcl2700dwlpr
       mfcl2700dwcupswrapper
     ];
     services.avahi.enable = true;
     # Important to resolve .local domains of printers, otherwise you get an error
     # like  "Impossible to connect to XXX.local: Name or service not known"
     services.avahi.nssmdns = true;
   }
   ```
   (full configuration [available here](https://github.com/wentasah/nix-conf/blob/bc87611c9bab9bdeb46a99d13cb16e12f3cec123/steelpick/configuration.nix#L218-L230))
3. Print something
4. Browse to http://localhost:631/printers/Brother_MFC-L2700DW_series and see the "_Impossible to connect to printerCCB4208.local: Name or service not known_" message.

**Expected behavior**
The job is sent to the printer and printed.

**Additional context**
When the printer cannot be connected, running `systemctl restart cups nscd` usually helps and the stuck job gets to the printer.

After my investigation, I think that the cause is long delay in mDNS name resolution. By default NixOS uses `mdns` NSS module, which tries to resolve both IPv4 and IPv6 addresses sequentially. It seems to start with IPv6, which does not resolve to a valid address so after 5s timeout the resolution continues with IPv4. So the address of the printer is returned after slightly more that 5 seconds (can be verified with `time getent hosts printerCCB4208.local`), which seems to be too long for CUPS so it gives up and tries again later and the same repeats, because nscd in NixOS does not cache the results.

My current solution to the problem is to switch from `mdns` NSS to `mdns4` with the following in my `configuration.nix`:
```nix
{
  services.avahi.nssmdns = false; # Use my settings from below
  # settings from avahi-daemon.nix where mdns is replaced with mdns4
  system.nssModules = with pkgs.lib; optional (!config.services.avahi.nssmdns) pkgs.nssmdns;
  system.nssDatabases.hosts = with pkgs.lib; optionals (!config.services.avahi.nssmdns) (mkMerge [
    (mkOrder 900 [ "mdns4_minimal [NOTFOUND=return]" ]) # must be before resolve
    (mkOrder 1501 [ "mdns4" ]) # 1501 to ensure it's after dns
  ]);
}
```

I've also tried `services.avahi.ipv6 = false;` but it didn't help.

The question is whether to make it easier for others. Possible things that come to my mind:
- Document this at Wiki
- Extend [avahi-daemon.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/avahi-daemon.nix#L203) to provide e.g. `nssmdns4` option.
- Enable caching in nscd
- Something else?

**Notify maintainers**

@matthewbauer @andir

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05pre279456.04a2b269d89 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre279456.04a2b269d89, nixos-hardware"`
 - channels(wsh): `"home-manager"`
 - nixpkgs: `/home/wsh/nix/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- cups
# a list of nixos modules affected by the problem
module:
- avahi-daemon
```

**Comment by wentasah** [comment]
I wanted to link this issue from the [wiki](https://nixos.wiki/wiki/Printing#Client_.28Linux.29) and found that @Juanibiapina added there a comment suggesting that he might have the same problem. @Juanibiapina, does the above workaround make your setup work without restarting cups after booting?

If yes, I'd update your comment, because it's not accurate. The `nssmdns` is not needed, because it is pulled in by `services.avahi.nssmdns = true;` mentioned on the previous line.

**Comment by juanibiapina** [comment]
Hi, I'm back and I'll test your workaround soon.

About `nssmdns`, I thought it should have been pulled, but it wasn't at the time. I vaguely remember triple checking and it wasn't there.

**Comment by juanibiapina** [comment]
Sorry, I can't test it again. My printer is busted.

**Comment by wentasah** [comment]
OK, thanks for letting me know :-)

**Comment by juanibiapina** [comment]
Ok, my printer has sudently revived and this solves the issue for me as well.

**Comment by wentasah** [comment]
Confirming that the issue still exists with current nixos-unstable.

**Comment by tobiasBora** [comment]
Out of curiosity, is this workaround supposed to break or use outdated softwares? If not, would it make sense to directly apply your workaround by default?

**Comment by wentasah** [comment]
This workaround makes mDNS working only for IPv4. If you are on a IPv6-only network, mDNS won't work for you. On mixed IPv4/IPv6 network, you might not see some devices. That's definitely not what some people want :-)

Btw, #146406 may be relevant to this problem. I've not read all the comments there, but the keywords seem similar to what I remember when debugging this issue.

I think the solution might be to increase or decrease some timeout somewhere, but I'm not sure where. More debugging/analysis is needed.

**Comment by pedrovelho** [comment]
Same happening here with a Canon MF643C. I found a workaround, but yours seems better. Mine was to manually add the name.local expected on '/etc/hosts' file. This only works if your printer has a fixed ip (like 10.1.2.3).

  networking.extraHosts =
  ''
    10.1.2.3 CanonMF643C.local
  '';

**Comment by googleson78** [comment]
I also hit this issue. Given that (I assume) most people are running ipv4, can we not try the v4 exclusive module first, and still fallback to the one that also works with v6, so that it "just works" for this rather common use case?

Given, that will slowdown v6 name resolution, but I guess we could also add a big warning in the option.

**Comment by Ten0** [comment]
Looks like this is closed by https://github.com/NixOS/nixpkgs/commit/bba808dbfa89c8d974b248f4bf3c7716312dc704

**Comment by wentasah** [comment]
Unfortunately, that commit is not sufficient for me. Current version of CUPS complains with:

_"No destination host name supplied by cups-browsed for printer "Brother_MFC_L2700DW_series_mDNS", is cups-browsed running?"_

The referenced commit makes my `/etc/nsswitch.conf` contain the following line:

    hosts:     mymachines mdns4_minimal [NOTFOUND=return] files myhostname dns mdns

With it, running `getent hosts printerCCB4509.local` returns an IPv6 address:

    fd76:76f3:2dcb:0:3205:5cff:fecb:4509 printerCCB4509.local

From the output of `strace -f -p $(pidof nsncd)` it seems that the command first asks for IPv6 address, so the `mdns4_minimal` is somehow ignored and the address is returned by `mdns` at the end of the line. I can ping and connect that address via `nc` so I don't know why CUPS cannot print to it.

Anyway, if I disable IPv6 in the printer, `getent hosts` returns the IPv4 address, but only after the 5 second timeout, which is too long for CUPS.

What I need is `mdns4` also at the end of `nsswitch.conf` line. I'll ask at #258424 and submit a PR to do that if people do not complain.

**Comment by SuperSandro2000** [comment]
Please submit a PR.

**Comment by adingbatponder** [comment]
https://fosstodon.org/@adingbatponder/111716425335189702

Uses a direct printer install. Same sort of problems encountered.

**Comment by James-E-A** [comment]
I got hit by this, too, on NixOS 24.05 — *with* `services.avahi.nssmdns4 = true` in my config.

It was “fixed” by `sudo systemctl restart cups nscd`, h/t OP.

**Comment by brianmay** [comment]
On my computers (with NixOS 24.11) I have had to manually create printers using the IP address. Possibly overkill but it works, and seems to be reliable, so far.

**Comment by James-E-A** [comment]
Hmm, this issue has returned with a vengeance. Despite the printer *appearing* in the output of `avahi-browse -a`, the service restart workaround is no longer helping at all. I guess I'll have to switch to hard-coding the IP address...

**Comment by markasoftware** [comment]
can confirm this is back, sometimes gets fixed by running cups-browsed manually or restarting random systemd services

**Comment by wentasah** [comment]
What is your value of `services.avahi.nssmdns6`? What's the output of `grep hosts /etc/nsswitch.conf`?

Does it help to set `services.avahi.nssmdns6` or `services.avahi.ipv6` to `false`?

**Comment by brianmay** [comment]
I have had this exact same issue, so will respond to the questions above.

> What is your value of services.avahi.nssmdns6?

[services.avahi.nssmdns6 - default (false)](https://github.com/NixOS/nixpkgs/issues/118628#issuecomment-2887981362)
services.avahi.ipv6 - default  (false)

To be precise my config is:

```nix
  services.avahi = {
    enable = true;
    publish = {
      enable = true;
      addresses = true;
      workstation = true;
    };

    # see https://nixos.wiki/wiki/Printing
    # see https://github.com/NixOS/nixpkgs/issues/118628
    nssmdns4 = true;
  };
```

> What's the output of grep hosts /etc/nsswitch.conf?

```
passwd:    files systemd
group:     files [success=merge] systemd
shadow:    files
sudoers:   files

hosts:     mymachines mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns mdns4
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

> Does it help to set services.avahi.nssmdns6 or services.avahi.ipv6 to false?

I believe that is the case already.

In the past I used the hack described in https://github.com/NixOS/nixpkgs/issues/118628#issuecomment-2887981362 but it looks like I got something very similar anyway, possibly because I am setting `nssmdns4`.

**Comment by brianmay** [comment]
Curiously I always seem to get two discovered printers. And the connection is different on different computers (that might be my fault playing around trying to fix said issue).

On one computer (which I think I haven't played around with) I have three printers:

```
HP_Officejet_Pro_8630_765CE9_8
Description:	HP_Officejet_Pro_8630_765CE9_8
Location:	
Driver:	Local Raw Printer (grayscale, 2-sided printing)
Connection:	implicitclass://HP_Officejet_Pro_8630_765CE9_8/
Defaults:	job-sheets=none, none media=iso_a4_210x297mm sides=one-sided
```

and 

```
HP_Officejet_Pro_8630_765CE9_8@HPFC3FDB765CE9-7.local
Description:	HP_Officejet_Pro_8630_765CE9_8@HPFC3FDB765CE9-7.local
Location:	
Driver:	HP Officejet Pro 8630, driverless, cups-filters 1.28.17 (color, 2-sided printing)
Connection:	implicitclass://HP_Officejet_Pro_8630_765CE9_8%40HPFC3FDB765CE9-7.local/
Defaults:	job-sheets=none, none media=iso_a4_210x297mm sides=one-sided
```

and (this printer manually configured to solve the immediate problem):

```
Description:	HP Officejet Pro 8630
Location:	Local Printer
Driver:	Officejet Pro 8630 - IPP Everywhere (color, 2-sided printing)
Connection:	ipp://HPFC3FDB765CE9-7.local:631/ipp/print
Defaults:	job-sheets=none, none media=iso_a4_210x297mm sides=two-sided-long-edge
```

That DNS address supplied in the 2nd and 3rd printer is correct:

```console
$ ping HPFC3FDB765CE9-7.local
PING HPFC3FDB765CE9-7.local (192.168.3.4) 56(84) bytes of data.
64 bytes from pluto.pri (192.168.3.4): icmp_seq=1 ttl=254 time=0.633 ms
64 bytes from pluto.pri (192.168.3.4): icmp_seq=2 ttl=254 time=0.826 ms
64 bytes from pluto.pri (192.168.3.4): icmp_seq=3 ttl=254 time=0.917 ms
64 bytes from pluto.pri (192.168.3.4): icmp_seq=4 ttl=254 time=0.695 ms
64 bytes from pluto.pri (192.168.3.4): icmp_seq=5 ttl=254 time=0.693 ms
64 bytes from pluto.pri (192.168.3.4): icmp_seq=6 ttl=254 time=0.648 ms
^C
--- HPFC3FDB765CE9-7.local ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5037ms
rtt min/avg/max/mdev = 0.633/0.735/0.917/0.102 ms
```

The 1st printer gives the following status: `Paused - "No destination host name supplied by cups-browsed for printer "HP_Officejet_Pro_8630_765CE9_8", is cups-browsed running?"`

The 2nd printer gives the following status: `Paused - "No destination host name supplied by cups-browsed for printer "HP_Officejet_Pro_8630_765CE9_8@HPFC3FDB765CE9-7.local", is cups-browsed running?"`

The 3rd printer just works, no dramas.


On another printer/computer - one which I have been fiddling more, the autodetected address is `dnssd://HP%20Officejet%20Pro%208630%20%5B765CE9%5D%20(8)._ipp._tcp.local/?uuid=1c852a4d-b800-1f08-abcd-fc3fdb765ce9` or `HP Officejet Pro 8630 [765CE9] (8)._ipp._tcp.local`. This does not appear to be valid. (are spaces in DNS names even allowed???)

```console
$ ping 'HP Officejet Pro 8630 [765CE9] (8)._ipp._tcp.local'
ping: HP Officejet Pro 8630 [765CE9] (8)._ipp._tcp.local: Name or service not known
```

Note I used ping, not the host command to lookup DNS addresses, because the host command I believe bypasses the libc resolving, and as such bypasses MDNS (just in case this causes any confusion - I initially forgot).
