### ISSUE TITLE
Please backport this virtualbox fix to 20.09

### ISSUE THREAD

**Issue by twoolie** [NixOS/nixpkgs#118727]
###### Project name
`nix search` name: nixos.linuxPackages_latest_hardened.virtualbox > virtualbox-modules-6.1.18-5.11.10

This fix [4499318](https://github.com/NixOS/nixpkgs/commit/44993187127edd1e0a20dbe03bcf5bea22943d74) is needed on nixos-20.09 or virtualbox-modules will fail to build against 5.11 kernel.

Please can someone cherry-pick this fix.

###### Notify maintainers

maintainers: @andresilva @svanderburg 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by Artturin** [comment]
20.09 eol
