### ISSUE TITLE
Dead link in pkgs/development/tools/documentation/gi-docgen/default.nix

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#118728]
In 17e45089daea0c2bd7c97b295598acfb6ae82bf5 @jtojnar fetches a patch from https://gitlab.gnome.org/ebassi/gi-docgen/commit/d65ed2e4827c4129d26e3c1df9a48054b4e72c50.patch, but that URL seems dead now (maybe a rebase there).

**Comment by jtojnar** [comment]
Sorry, that should have been `https://gitlab.gnome.org/jtojnar/gi-docgen/commit/d65ed2e4827c4129d26e3c1df9a48054b4e72c50.patch`. Must have pushed a wrong commit.

This patch is not necessary on master and the upcoming 0.0.3 version.

**Comment by nomeata** [comment]
Thanks!
