### ISSUE TITLE
Firefox always managed by organization

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#118860]
**Describe the bug**
Since eedee46f `pkgs.firefox` is always "managed by your organization". This is because the `Extensions` section of `enterprisePolicies` is always set, probably due to broken bracketing here:

https://github.com/NixOS/nixpkgs/blob/6da2f72f69ff212ca7ee842744e122bacdc18788/pkgs/applications/networking/browsers/firefox/wrapper.nix#L99-L127

resulting in `policies.json` always containing at least:

```json
{"policies":{"Extensions":{"Install":[]}}}
```

*I'm not sure, but I think this broke the auto update of my addons, which are not managed by NixOS.*

**Expected behavior**
Have managed firefox be completely opt-in.

**Author**
@Luis-Hebendanz

**Comment by andir** [comment]
Maybe it is time to write some tests for the complex wrapper script? Not sure if anyone has raised that before.

**Comment by Luis-Hebendanz** [comment]
Thanks for reporting! Hmm I see this wasn't broken bracketing, more like unknown side effects. This should be quick to fix, I will work on it
