### ISSUE TITLE
firefox-bin wrong ELF class

### ISSUE THREAD

**Issue by alsoijw** [NixOS/nixpkgs#118824]
**Describe the bug**
Despite I install x86 application, it try to use x64 and crash on x64 NixOs.

**To Reproduce**
1. `$ nix-shell shell.nix`
2. `nix-shell $ firefox`. There are many warnings like that, but aplication still running. I copy only cople first lines.
```/nix/store/1nym2w2r87gp87ag7g245ahrjnymg2nz-glib-networking-2.64.3/lib/gio/modules/libgiognomeproxy.so: wrong ELF class: ELFCLASS64
Failed to load module: /nix/store/1nym2w2r87gp87ag7g245ahrjnymg2nz-glib-networking-2.64.3/lib/gio/modules/libgiognomeproxy.so
/nix/store/1nym2w2r87gp87ag7g245ahrjnymg2nz-glib-networking-2.64.3/lib/gio/modules/libgiognutls.so: wrong ELF class: ELFCLASS64
```
3. Press Ctrl + O or Ctrl + S. After that it crush with this error
```(crashreporter:14425): Gtk-WARNING **: 18:04:30.056: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/Adwaita/16x16/status/image-missing.png: Не удалось загрузить модуль загрузки изображений: /nix/store/26qasd617ydbms711kqp7mm1f699j55m-gdk-pixbuf-2.40.0/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /nix/store/26qasd617ydbms711kqp7mm1f699j55m-gdk-pixbuf-2.40.0/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: wrong ELF class: ELFCLASS64 (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/Adwaita/16x16/status/image-missing.png: Не удалось загрузить модуль загрузки изображений: /nix/store/26qasd617ydbms711kqp7mm1f699j55m-gdk-pixbuf-2.40.0/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /nix/store/26qasd617ydbms711kqp7mm1f699j55m-gdk-pixbuf-2.40.0/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: wrong ELF class: ELFCLASS64 (gdk-pixbuf-error-quark, 5)
```

**Expected behavior**
Use correct library's version.

**Additional context**
```$ cat shell.nix 
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    nativeBuildInputs = [ pkgs.pkgsi686Linux.firefox-bin ];
  }
```

**Notify maintainers**
@taku0

**Metadata**
```$ $  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.24, NixOS, 20.09.3732.91b77fe6942 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3732.91b77fe6942, nixos-unstable-21.03pre261422.1a57d96edd1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
- pkgsi686Linux.firefox-bin
```

**Comment by taku0** [comment]
It may be related to GNOME.  It works on KDE for `master`; Ctrl+S opens a dialog without errors.

**Comment by taku0** [comment]
I couldn't build GNOME virtual machine, so I cannot reproduce this.

**Comment by alsoijw** [comment]
Yes, I have installed GNOME. @taku0, do you have any gtk application without firefox?

**Comment by taku0** [comment]
I can run `pkgsi686Linux.gnome3.gedit` on KDE and open save/open dialog boxes.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.88, NixOS, 20.09.2555.41dddb12837 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3732.91b77fe6942"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by alsoijw** [comment]
I found finally part. I need to use `--pure` flag, it create system without inherits installed packages. It also unset system variables, so need `--keep` and list vars like WAYLAND_DISPLAY, XDG_RUNTIME_DIR. And for working hardware video decoding include pkgsi686Linux.libva-utils to nix file.
