### ISSUE TITLE
rustc is outdated

### ISSUE THREAD

**Issue by Riey** [NixOS/nixpkgs#118874]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: rustc

current version: 1.50.0
desired version: 1.51.0

###### Notify maintainers

maintainers: @Ericson2314 

###### Note for maintainers

Please tag this issue in your PR.

Since 1.51.0 ship important feature `min_const_generic` many crates start require 1.51.0

**Comment by marsam** [comment]
Rust 1.51.0 is already in the current `staging-next` branch, and it will be merged into master in #118312

**Comment by Riey** [comment]
@marsam Thank you!
