### ISSUE TITLE
keyboard stops working for 50 minutes

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#118954]
**Describe the bug**
I finally create this bug report, but i still don't know much about the issue.

When i press the mute key on my keyboard several times, the computer does not compute any inputs for some time. It can be 5 minutes or 50. The keyboard still works, has power, but the computer seem to ignore all input.

The mouse still works. So it's not that USB stops working completely.

Sometimes it goes away when i open the on-screen keyboard.

I don't see anything relevant in the logs when this happens, so i have no clue what the issue is and how to fix it.

Do you noticed similar behavior or have a clue what could cause such issue?

**To Reproduce**

It happens when i watch youtube for hours and just use the keyboard to mute when ads play and unmute again when i have skipped them.

I can not reproduce it by quickly hitting the mute key 200 times. It seem to have a timing component where the key has to be pressed like every 5 minutes in 1 hour or so.

I have this issue multiple times a week since i'm currently watching youtube a lot... :grimacing: 

**Expected behavior**
the computer should be able to receive keyboard inputs

**Screenshots**
I noticed that text input fields look inactive when the system is in that state. So the system seam to know that there can't be any keyboard input.

For example the pantheon terminal:

When it can receive inputs there is a solid cursor blinking:

![Screenshot from 2021-04-10 05-02-18](https://user-images.githubusercontent.com/91113/114256514-031b0000-99ba-11eb-98c0-34953e6bbd48.png)

but when it's not, there is just a non-blinking outline:

![Screenshot from 2021-04-10 05-01-31](https://user-images.githubusercontent.com/91113/114256522-1928c080-99ba-11eb-9c5f-82ad06649052.png)

here is also a short video which shows also an additional issue with the files program that does not happen every time

https://youtu.be/RZwsGOoCOqw

**Additional context**
I use the pantheon desktop.

The full config is here: https://codeberg.org/davidak/nixos-config/src/commit/36be7df14e5b62d26adcea07b07c7d6fd01bba73/machines/gaming/configuration.nix

Right now i use the latest nixos-unstable, but had it also with 20.09 and i think 20.03. Before i don't had a keyboard with a mute key.

**Notify maintainers**
@worldofpeace do you have any idea which system component could cause this? do you ever heard of a similar issue?

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.11, NixOS, 21.05pre281538.9e377a6ce42 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-21.05pre281538.9e377a6ce42, nixos-hardware, nixos-unstable-21.05pre281538.9e377a6ce42"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ishan9299** [comment]
What is the keyboard model?

**Comment by davidak** [comment]
@ishan9299 it's an [Ergodox EZ](https://ergodox-ez.com/) which uses the [Quantum Mechanical Keyboard Firmware](https://github.com/qmk/qmk_firmware) (QMK). Here is the configuration: https://configure.zsa.io/ergodox-ez/layouts/9wVNO/latest/0

**Comment by nixinator** [comment]
to rule out the keyboard , when it happens, plug in another keyboard..and see what happens. Might be a bug in the USB subsystem/drivers for the keyboard.

Also what happens when you unplug your keyboard, and attached it?

**Comment by davidak** [comment]
>to rule out the keyboard , when it happens, plug in another keyboard..and see what happens.

nothing. the additional keyboard also has power, but the computer does not receive inputs from it either

>Also what happens when you unplug your keyboard, and attached it?

nothing. still same issue

>try also to have on screen keyboard open, and see if the terminal can receive keyboard events from that...

some times the issue was solved in the second i opened the on screen keyboard (that can be activated in the pantheon settings), but now even that can't type!

>evtest

nice. that's what i was looking for

```
[nix-shell:~]$ sudo evtest
[sudo] password for davidak: 
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Sleep Button
/dev/input/event1:	Power Button
/dev/input/event2:	Power Button
/dev/input/event3:	HDA ATI HDMI HDMI/DP,pcm=3
/dev/input/event4:	HDA ATI HDMI HDMI/DP,pcm=7
/dev/input/event5:	HDA ATI HDMI HDMI/DP,pcm=8
/dev/input/event6:	HDA ATI HDMI HDMI/DP,pcm=9
/dev/input/event7:	HDA ATI HDMI HDMI/DP,pcm=10
/dev/input/event8:	HDA ATI HDMI HDMI/DP,pcm=11
/dev/input/event9:	HDA Intel PCH Front Mic
/dev/input/event10:	HDA Intel PCH Rear Mic
/dev/input/event11:	HDA Intel PCH Line
/dev/input/event12:	HDA Intel PCH Line Out
/dev/input/event13:	HDA Intel PCH Front Headphone
/dev/input/event14:	ZSA Ergodox EZ
/dev/input/event15:	ZSA Ergodox EZ System Control
/dev/input/event16:	ZSA Ergodox EZ Consumer Control
/dev/input/event17:	ZSA Ergodox EZ Keyboard
/dev/input/event18:	Logitech G403 HERO Gaming Mouse
/dev/input/event19:	Logitech G403 HERO Gaming Mouse Keyboard
/dev/input/event20:	Logitech G403 HERO Gaming Mouse Consumer Control
/dev/input/event21:	Logitech G403 HERO Gaming Mouse System Control
/dev/input/event22:	Tdlasunnic Sharkoon Gaming DAC Pro S
/dev/input/event23:	PWC snapshot button
/dev/input/event24:	WH-1000XM3 (AVRCP)
Select the device event number [0-24]: 14
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0xfeed product 0x1307 version 0x111
Input device name: "ZSA Ergodox EZ"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
...
```

when i hit enter, i see this while the keyboard works

```
Event: time 1618718328.979333, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70028
Event: time 1618718328.979333, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1618718328.979333, -------------- SYN_REPORT ------------
```

i don't see anything when pressing the volume up, down or mute key.

that's in the other device "ZSA Ergodox EZ Consumer Control" (16)

```
Event: time 1618718468.307184, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1618718468.307184, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1618718468.307184, -------------- SYN_REPORT ------------
Event: time 1618718468.395137, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1618718468.395137, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1618718468.395137, -------------- SYN_REPORT ------------

Event: time 1618718470.931183, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1618718470.931183, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 1
Event: time 1618718470.931183, -------------- SYN_REPORT ------------
Event: time 1618718471.011131, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1618718471.011131, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 0
Event: time 1618718471.011131, -------------- SYN_REPORT ------------

Event: time 1618718472.787186, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e2
Event: time 1618718472.787186, type 1 (EV_KEY), code 113 (KEY_MUTE), value 1
Event: time 1618718472.787186, -------------- SYN_REPORT ------------
Event: time 1618718472.875135, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e2
Event: time 1618718472.875135, type 1 (EV_KEY), code 113 (KEY_MUTE), value 0
Event: time 1618718472.875135, -------------- SYN_REPORT ------------
```

let's see how it looks when the issue appears again

>So get your vala debugging skills out! :-)

they are pretty much non-existent and i don't want to go so deep into this by recompiling packages. i would have to research how to do that...

**Comment by nixinator** [comment]
If you don't want to go deep dive into the weeds, then god debug, and a way to reproduce is going to help in fixing this. Good luck..

**Comment by davidak** [comment]
Some new insights:

When the issue happens and the input is not recognized, i still see it in evtest!

I also don't see a blinking cursor in Firefox textbox where i was just typing.

The issue with the file explorer not changing view seems reproducible when it happens, so might be caused by it. Don't really makes sense. When i try to move the window, it freezes shortly and then the typing issue is recovered.

This time i opened a new terminal window in which i couldn't type, but when i moved it, it froze shortly and the issue was gone.

So this seem to be a software issue.

**Comment by nixinator** [comment]
if evtest see's the input coming in, the it must be related to your window manager , or X server, or changing window focus. It's going to be hard one to debug.. Is there anyway to increase debug levels in the software, seeing any buffer sizes of incoming input might be useful too.

this looks handy code.

https://gist.github.com/javiercantero/7753445

**Comment by Artturin** [comment]
Do you still have this issue?

**Comment by davidak** [comment]
I did not encounter it in some time, but i'm not sure it's fixed.

We can close it for now.
