### ISSUE TITLE
texlive add custom .sty file

### ISSUE THREAD

**Issue by fkz** [NixOS/nixpkgs#11893]
I first tried to add a new package that I could add to `texlive.combine` but couldn't figure out how to do that. So I just did something like the following:

    simple-package = stdenv.mkDerivation {
      name = "name";
      inherit src;
      installPhase = ''
        mkdir -p $out/share/texmf-nix/tex/latex
        cp custom.sty $out/share/texmf-nix/tex/latex
    }

But when I want to use it, it doesn't work:

    generate-some-pdf = stdenv.mkDerivation {
      ...
      buildInputs = [ (texlive.combine {...}) simple-package ];
      ...
    };

Instead, I have to add `texlive.bin.core` to the `buildInputs` to get the `setupHook` fired and customize `$TEXINPUTS` accordingly:

    generate-some-pdf = stdenv.mkDerivation {
      ...
      buildInputs = [ (texlive.combine {...}) texlive.bin.core simple-package ];
      ...
    };

. The priorities of the executables like `pdflatex` seem to be handled right, so this works flawlessly. But is this expected? Am I doing something stupid? Are there better ways to archive this?

@vcunat

**Comment by vcunat** [comment]
> cp custom.sty $out/share/texmf-nix/tex/latex

You tried a different path than `texlive.combine` uses. You need `$out/tex/latex` directly to use it that way; I believe it should work fine after that change. `$TEXINPUTS` is probably another valid way, but I don't know if the resulting search sequence is equivalent to this or not.

Note: `texlive.bin.core` should be included by `texlive.combine` automatically.

**Comment by fkz** [comment]
Indeed, the following worked for me:

    simple-package = stdenv.mkDerivation rec {
      name = "name";
      inherit src;
      installPhase = ''
        mkdir -p $out/tex/latex
        cp custom.sty $out/tex/latex
      '';
      pname = name;
      tlType = "run";
    };
    tex = texlive.combine {
      inherit (texlive) scheme-small ...;
      simple-package = {
        pkgs = [ simple-package ];
      };
    };

Is this, how it's supposed to be used? What should I set `pname` and `tlType` to?

I added the `texlive.bin.core` in the previous workaround because this added the [setup hook](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/setup-hook.sh). Although `texlive.combine` does include `texlive.bin.core`, this setup hook isn't added automatically. Is this a bug?

**Comment by vcunat** [comment]
Yeah, I first forgot you need `pname` and `tlType`. `tlType = "run"` is the correct one, meaning stuff useful for running tex* commands; in `pname` you can have any string, preferably without version and not colliding with any TeX Live package name.

That setup hook... was copied from the old `texLive` infrastructure, as I didn't know if some packages used it or needed it. Now I see I didn't do it properly, so I might as well remove it. I don't know &ndash; I certainly don't have any plans yet for the hook or passing `$TEXINPUTS`.

**Comment by vcunat** [comment]
To be honest, I haven't yet thought much about how to plug-in stuff that is not in upstream TeX Live.

**Comment by schmittlauch** [comment]
@vcunat It'd be useful to implement packaging of custom LaTeX classes and how to add them to a texlive.combine environment.
Do you intend to change this or can I try to document the mentioned approach in the nixpkgs manual?

**Comment by vcunat** [comment]
@schmittlauch I have no such plans.  Actually, I've done basically nothing around TeX in the past few years; occasional update or fixes were done by others.  /cc @veprbl (who's closer to being a real maintainer of this)

**Comment by veprbl** [comment]
@schmittlauch If you are willing to work on documenting and/or improving our TeX stuff, I would be happy to help with reviewing that.

See also #17748

**Comment by AkechiShiro** [comment]
@StefanSchroeder is this still maintained and usable ?

**Comment by StefanSchroeder** [comment]
> @StefanSchroeder is this still maintained and usable ?

Nixos 24.05 has seen some major refurbishment of the Texlive infrastucture. I haven't looked at this yet. The major change seems to be the breakup of the texlive behemoth package into smaller packages (one per CTAN pacakge?) I have to look into it.

**Comment by ngn999** [comment]
After providing the latest [document](https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/doc/languages-frameworks/texlive.section.md), the LLM generated a working solution:
```nix
{
  description = "LaTeX Document Demo";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
    }:
    with flake-utils.lib;
    eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Create a custom pgf-go package
        pgfGoPkg = pkgs.stdenvNoCC.mkDerivation {
          pname = "pgf-go";
          version = "0.2025.03.07";

          # Use multiple outputs as expected by texlive.combine
          outputs = [
            "out"
            "tex"
            "texdoc"
          ];

          # Add texlive dependencies (pgf is required by pgf-go)
          passthru.tlDeps = with pkgs.texlive; [ pgf ];

          src = pkgs.fetchzip {
            url = "https://mirrors.ctan.org/graphics/pgf/contrib/pgf-go.zip";
            sha256 = "sha256-q52jF5HHXJY/F0K/eIfOaiPd3Xnfj1R0B/WnsHGuBWY="; # Replace if this doesn't work
            stripRoot = false;
          };

          dontConfigure = true;
          dontBuild = true;

          installPhase = ''
            runHook preInstall

            # Install runtime files in the "tex" output according to TDS
            mkdir -p $tex/tex/latex/pgf-go
            cp -r pgf-go/latex/*.sty $tex/tex/latex/pgf-go/

            # Install documentation in the "texdoc" output
            mkdir -p $texdoc/doc/latex/pgf-go
            cp -r pgf-go/doc/* $texdoc/doc/latex/pgf-go/
            cp pgf-go/*.pdf $texdoc/doc/latex/pgf-go/

            # We need at least an empty out directory
            mkdir -p $out

            runHook postInstall
          '';

          meta = {
            description = "Drawing Go positions and diagrams with PGF/TikZ";
            license = pkgs.lib.licenses.gpl2;
            platforms = pkgs.lib.platforms.all;
          };
        };

        tex = pkgs.texlive.combine {
          inherit (pkgs.texlive)
            scheme-small
            scheme-context
            context-simpleslides
            latex-bin
            latexmk
            nicematrix
            coffeestains
            luatexja
            pxrubrica
            titlesec
            colortbl
            emoji
            haranoaji
            haranoaji-extra
            luacode
            go
            ;
          # Add the custom pgf-go package
          pgf-go = pgfGoPkg;
        };
      in
      rec {
        packages = {
          document = pkgs.stdenvNoCC.mkDerivation rec {
            name = "latex-demo-document";
            src = self;
            buildInputs = [
              pkgs.coreutils
              tex
            ];
            phases = [
              "unpackPhase"
              "buildPhase"
              "installPhase"
            ];
            buildPhase = ''
              export PATH="${pkgs.lib.makeBinPath buildInputs}";
              export HOME=''$(mktemp -d);
              luaotfload-tool --cache=erase --flush-lookups --force --update;
              mkdir -p .cache/texmf-var;
              latexmk -interaction=nonstopmode -pdf -lualatex \
                japanese.tex
            '';
            installPhase = ''
              mkdir -p $out
              cp japanese.pdf $out/
            '';
          };
        };
        defaultPackage = packages.document;
      }
    );
}
```
