### ISSUE TITLE
Musescore opens .zip instead of Ark

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#118916]
**Describe the bug**
When opening a .zip file in KDE, I would expect Ark to open it (it has always done that before). However, since I installed Musescore, musescore has priority over Ark to open zip, and therefore the opening crashes. I guess it's just matter of setting some priorities.

I know it's simple to override on user side, but I think to remember it's possible to override that directly in the `.desktop` file by putting a lower priority number, and it may help inexperienced users. Actually, I even think that Musescore should not open .zip at all since it can't deal with them properly.

**To Reproduce**
1. Install Ark and Musescore in KDE
2. Open a .zip file
3. See error when Musescore (instead of Ark) opens it

**Notify maintainers**
@vandenoever @turio @ttuegel 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.93, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(root): `"nixos-unstable-21.03pre267299.5ff6700bb82, nixos-21.03pre267299.5ff6700bb82"`
 - channels(me): `"local-nixos-unstable-21.05pre279012.ad47284f8b0, home-manager, local-nixpkgs-unstable-21.03pre267409.f5daa8ab31f, nixos-20-03-20.03.3324.929768261a3, test, nixos-unstable-21.03pre250162.34ad166a830"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by dotlambda** [comment]
`share/applications/mscore.desktop` doesn't mention `application/zip`:
```
MimeType=application/x-musescore;application/x-musescore+xml;application/vnd.recordare.musicxml;application/vnd.recordare.musicxml+xml;audio/midi;application/x-bww;application/x-biab;application/x-capella;audio/x-gtp;application/x-musedata;application/x-overture;audio/x-ptb;application/x-sf2;application/x-sf3;
```
What does `file -Lb --mime-type file-youre-trying-to-open.zip` say?

**Comment by tobiasBora** [comment]
Hum, strange... I get:
```
$ file -Lb --mime-type myfile.zip
application/zip
```
(the file is just produced with the `zip` command line)

I tried to check the .desktop file, I can see :
```
$ ll $(which musescore)
lrwxrwxrwx 1 root root 71 janv.  1  1970 /run/current-system/sw/bin/musescore -> /nix/store/zy314bxnjg8hbb3jnj4c46l66ym9zgp5-musescore-3.6/bin/musescore

$ cat /nix/store/zy314bxnjg8hbb3jnj4c46l66ym9zgp5-musescore-3.6/share/applications/mscore.desktop 
[Desktop Entry]
Version=1.0
Name=MuseScore 3.6
GenericName=Music notation
GenericName[de]=Notensatz
GenericName[fr]=Notation musicale
Comment=Create, play and print sheet music
Comment[ru]=Визуальный редактор нотных партитур
Comment[fr]=Gravure de partitions musicales
Exec=mscore %F
Icon=mscore
StartupNotify=true
StartupWMClass=mscore
Terminal=false
Type=Application
Categories=Qt;Audio;Sequencer;Midi;AudioVideoEditing;Music;AudioVideo;
Keywords=music;notation;composition;composing;arranging;making;sheet music;music notation software;lead sheet;leadsheet;score;full score;scorewriter;MIDI;musicxml;playback;instrument;
Keywords[de]=Musik;Noten;Musiknoten;Komposition;Komponieren;Arrangieren;Notenblatt;Notenblätter;Notationsprogramm;Musiknotationsprogramm;Musiknotation;Tabulatur;MIDI;musicxml;Instrument;
MimeType=application/x-musescore;application/x-musescore+xml;application/vnd.recordare.musicxml;application/vnd.recordare.musicxml+xml;audio/midi;application/x-bww;application/x-biab;application/x-capella;audio/x-gtp;application/x-musedata;application/x-overture;audio/x-ptb;application/x-sf2;application/x-sf3;
```

Also, I'm not sure what happens: if I use `xdg-open myfile.zip`, it opens with Ark. The problem is rather when I open it with Dolphin. Also, I just tried to right click/open with/other application, select Ark, and select "Memorize the association between the software and application/zip"... and now it opens with Ark, but Musescore is still in the "Open with" list. Don't know why Dolphin tries Musescore by default...

**Comment by dotlambda** [comment]
This sounds like an upstream issue. Please open an issue on Dolphin's issue tracker.

**Comment by SuperSamus** [comment]
I tried installing Musescore with nix-env on KDE, and Dolphin still uses Ark as default when selecting a .zip file.
I think that this can be closed,

**Comment by tobiasBora** [comment]
Cool,thanks, I'll close it then, and reopen if I experience this again.
