### ISSUE TITLE
pkgsi686Linux.OVMF compilation broken

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#118985]
**Describe the bug**

OVMF will not build under pkgsi686Linux, which seems to be the only current way to get IA32 OVMF files.

**To Reproduce**
1. nix-build -E 'with import <nixpkgs> { }; pkgsi686Linux.OVMF'

output is : 

```
Building ... /build/edk2/MdePkg/Library/BaseSafeIntLib/BaseSafeIntLib.inf [IA32]
cc1: error: LTO support has not been enabled in this configuration
make: *** [GNUmakefile:384: /build/edk2/Build/OvmfIa32/RELEASE_GCC5/IA32/MdePkg/Libra
```

**Expected behavior**

OVMF builds

**Screenshots**

**Additional context**

edk2/OVMF seems buildable with IA32 when using the 64-bit env. With some modifying this seems to work (stdenv is 64bit but targetArch is overriden to IA32):

```
packageOverrides = pkgs: rec {
...
    edk2_32bit = (pkgs.callPackage ./pkgs/edk2.nix {
      targetArch = "IA32";
    });

    OVMF_32bit = (pkgs.callPackage ./pkgs/OVMF.nix {
      util-linux = pkgs.utillinux;
      projectDscPath = "OvmfPkg/OvmfPkgIa32.dsc";
      edk2 = edk2_32bit;
    });
...
}

% nix repl '<nixpkgs>'
Welcome to Nix version 2.3.10. Type :? for help.

Loading '<nixpkgs>'...
Added 12466 variables.

nix-repl> stdenv.platform
{ kernelArch = "x86_64"; kernelAutoModules = true; kernelBaseConfig = "defconfig"; kernelTarget = "bzImage"; name = "pc"; }
nix-repl> pkgs.OVMF_32bit.stdenv.platform
{ kernelArch = "x86_64"; kernelAutoModules = true; kernelBaseConfig = "defconfig"; kernelTarget = "bzImage"; name = "pc"; }
nix-repl> :b pkgs.OVMF_32bit
[4 built, 38 copied (196.6 MiB), 39.3 MiB DL]

this derivation produced the following outputs:
  fd -> /nix/store/pyx64hz9bsm66hs196s61dm9xl943l12-OVMF-202011-fd
  out -> /nix/store/xcsjqddprha1ykk8v58sjbq80s1rwbwh-OVMF-202011
% dir /nix/store/xcsjqddprha1ykk8v58sjbq80s1rwbwh-OVMF-202011
AutoGen  BuildOptions  FV  GlobalVar_5a9e7754-d81b-49ea-85ad-69eaa7b1539b_IA32.bin  IA32  Ovmf.map  PcdTokenNumber
```

I do not mind making this an optional mode within nixpkgs. There are no attached maintainers so I am not sure who would be the decider on this.

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 20.09.3554.f8929dce13e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3774.a6847cb5460"`
 - channels(sheenobu): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsi686Linux.OVMF
# a list of nixos modules affected by the problem
module:
```

**Comment by FliegendeWurst** [comment]
pkgsi686Linux.OVMF build works on 21.11.
