### ISSUE TITLE
Generated neovim config breaks plugins (shouldn't enable filetype detection nor syntax highlighting)

### ISSUE THREAD

**Issue by colinxs** [NixOS/nixpkgs#118953]
**Describe the bug**
The neovim module currently creates a config file containing `filetype indent plugin on | syn on` at the top, before any user config. This breaks the configuration of ftplugins like this:
```
" How it should be:
let g:polyglot_disabled = ['sensible', 'nix']
filetype indent plugin on | syn on

" The current broken behavior (plugin loaded before config, so config is ignored)
filetype indent plugin on | syn on
let g:polyglot_disabled = ['sensible', 'nix']
```

**Expected behavior**
I feel like the modules in home-manager shouldn't modify default program behavior when possible. That means removing the `filetype indent plugin on | syn on` line alogether and letting the user set it.

**Screenshots**

**Additional context**

**Notify maintainers**
@manveru @rvolosatovs @ma27

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-7642-generic, Pop!_OS, 20.10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-21.05pre278688.c0e88185200"`
 - nixpkgs: `/home/colinxs/.nix-defexpr/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by teto** [comment]
agreed it's an opiniated default that can't be overridden. If anything it should be moved to a default `extraConfig`

**Comment by teto** [comment]
I've started a fix. Note that it's not specific to neovim, neovim leverages vimrcContent that just inconditionnally adds this bit of config along with nocompatible for vim (for no reason). We've a similar issue in neovim core https://github.com/neovim/neovim/pull/14361

**Comment by teto** [comment]
if you use use configure.packages (not configure.vam or configure.pathogen) this should be fixed. I haven't fixed it for the other package managers which should be removed anyway IMO.

**Comment by teto** [comment]
Feel free to reopen if this was not fixed for you.
