### ISSUE TITLE
pango: devdoc target is not reproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#118910]
**Describe the bug**

Building the `devdoc` output of `pango` does not produce the exact same output each time it is build.

Having bit-by-bit reproducible derivations makes auditing build processes easier. This package is especially interesting since it is part of the milestone tracked by https://r13y.com

**To Reproduce**

`nix-build "<nixpkgs>" -A pango.devdoc --check`

**Expected behavior**

Success!

**Additional context**

There is an upstream patch to gi-docgen at https://gitlab.gnome.org/GNOME/gi-docgen/-/merge_requests/53/diffs.patch that might help, but doesn't seem to completely fix the issue yet. Starting point:

```
diff --git a/pkgs/development/tools/documentation/gi-docgen/default.nix b/pkgs/development/tools/documentation/gi-docgen/default.nix
index 72b5364eb45..57dbe62a667 100644
--- a/pkgs/development/tools/documentation/gi-docgen/default.nix
+++ b/pkgs/development/tools/documentation/gi-docgen/default.nix
@@ -61,6 +61,11 @@ python3.pkgs.buildPythonApplication rec {
       url = "https://gitlab.gnome.org/jtojnar/gi-docgen/commit/08dcc31f62be1a5af9bd9f8f702f321f4b5cffde.patch";
       sha256 = "vAT8s7zQ9zCoZWK+6PsxcD5/48ZAfIOl4RSNljRCGWQ=";
     })
+    # make DevHelp sections & index.json have stable ordering
+    (fetchpatch {
+      url = "https://gitlab.gnome.org/GNOME/gi-docgen/-/merge_requests/53/diffs.patch";
+      sha256 = "sha256-nG0Dt///w7agXAvWNtGdBQSaKMXNHraGO1svmn9FynI=";
+    })
   ];
 
   nativeBuildInputs = [
```

**Comment by Zopieux** [comment]
The lastest commit should address all issues, but I need help reproducing the (lack of) reproducibility. Can anyone check compiling pango before/after patching, to confirm the `devhelp` and `index.json` diffs are now gone? Thanks.

**Comment by Zopieux** [comment]
OK managed to reproduce pango not being reproducible at HEAD. With the patch, I cannot get it to fail after multiple attempts event under `stress(1)` load.

**Comment by Zopieux** [comment]
Now waiting for [upstream](https://gitlab.gnome.org/GNOME/gi-docgen/-/merge_requests/53/) to merge.

**Comment by raboof** [comment]
Can confirm this fixes it here as well!

PR'ed as #118978 to get the patch in for 21.05

**Comment by oxalica** [comment]
Maybe this can be closed now?
