### ISSUE TITLE
generic/setup.sh : host binaries in path cause problems

### ISSUE THREAD

**Issue by aboseley** [NixOS/nixpkgs#11901]
In this example I want to build a package like, util linux for my pie.

The package uses the "xz" library as part of the build process so it's cross compiled for the host (cross.target) 

Things go badly when the stdenv/generic/setup.sh puts these 'host' binaries in the path via "_add_to_CrossEnv"

I don't understand the benefit of putting host binaries in that path they are typically incompatible with the build machine and won't run

In this particular case it causes the unpack script to fail  when it tries to run the incompatible xz binary

Paste the following into a file and nix-build it

```
let
  pkgsNoParams = import <nixpkgs> {};
  system = builtins.currentSystem;

  rasberryPieCross = {
    config = "armv6l-unknown-linux-gnueabi";
    bigEndian = false;
    arch = "arm";
    float = "hard";
    fpu = "vfp";
    withTLS = true;
    libc = "glibc";
    platform = pkgsNoParams.platforms.raspberrypi;
    openssl.system = "linux-generic32";
    gcc = {
      arch = "armv6";
      fpu = "vfp";
      float = "softfp";
      jabi = "aapcs-linux";
    };
  };

  utils_linux_or_similar = 
    { stdenv, fetchurl, xz }:                      
    stdenv.mkDerivation rec {                                                          
      name = "util-linux-or-similar";
      buildInputs = [ xz ];
      src = fetchurl {                                                                 
        url = "mirror://kernel/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz";
        sha256 = "1452hz5zx56a3mad8yrg5wb0vy5zi19mpjp6zx1yr6p9xp6qz08a";
      };
      phases = [ "unpackPhase" "installPhase" ];
      installPhase = ''
        mkdir $out;
      '';
    };

  # package set
  pkgs = import <nixpkgs> {
    inherit system;
    crossSystem = rasberryPieCross;
    config = { 
      packageOverrides = pkgs : with pkgs; rec { 
        problems = callPackage utils_linux_or_similar{ };
      };
    };
  };
in
  pkgs.problems.crossDrv
  #pkgs.problems.nativeDrv
```

**Comment by aboseley** [comment]
The use of this function, means that some of the crossDrv can run on the build machine
```
 forceNativeDrv = drv : if crossSystem == null then drv else                   
                            (drv // { crossDrv = drv.nativeDrv; });  
```
An example is the gcc-cross-wrapper, which needs to be in the path, especially as a crossDrv.

How do we identify the target architecture of a derivation, if not by crossDrv vs nativeDrv?

**Comment by Profpatsch** [comment]
(triage) sorry for the silence, @aboseley does this still pose a problem?

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/issues/21191 narrows in on the exact issue more clearly. Closing in lieu of that
