### ISSUE TITLE
idris2Packages.withPackages

### ISSUE THREAD

**Issue by locallycompact** [NixOS/nixpkgs#119175]
**Project description**
nixpkgs currently has an idris1 package shell 'idrisPackages.with-packages'.

I'd like this for idris2. The current package format for the idris1 libraries in idris-modules is not compatible with idris2, and mostly neither is the code.

Happy to work on this but I'd need some instruction.

**Comment by srid** [comment]
Looks like @wchresta's https://github.com/NixOS/nixpkgs/pull/154649 provides this.

**Comment by mattpolzin** [comment]
I believe the need for `idris2.withPackages` is fulfilled by the `idris2Packages.buildIdris` function we now have. We can reopen this ticket and I am happy to think on it more if that's not the case. One small difference is that `idris2Packages.buildIdris` requires an `ipkg` file, but creating a simple `ipkg` file is a low barrier, even just for a directory where you are experimenting with something. The `buildIdris` function puts any number of packages into Idris2's package path at build time and it offers a shell hook that adds those packages to the package path as well for development purposes.
