### ISSUE TITLE
GnuPG 2 compatability issue

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixpkgs#11912]
The GnuPG version 2 package comes with gpgkey2ssh however it looks for an executable in path called gpg where as in the GnuPG version 2 package this is gpg2.

This can be resolved by installing the gnupg1compat package but without that, by default, it is broken.

Not a major issue but it's something.

**Comment by vcunat** [comment]
I don't see what's the problem (perhaps it's just that I rarely use gnupg). There's gpg2 by default and compat package for those who want gpg1 interface &ndash; what to want more?

**Comment by copumpkin** [comment]
@vcunat as far as I can tell @Nekroze is saying that the gpg2 package isn't internally consistent. The package bundles a `gpg2` binary but also comes with a script that expects a `gpg` binary.

@Nekroze in general, we patch scripts like that to refer to absolute store paths rather than utilities from the `PATH`. That's probably what is needed here.

**Comment by vcunat** [comment]
Oh, I'm sorry I didn't get it. I'm probably too tired.

**Comment by Nekroze** [comment]
@vcunat Its ok, I'm not always as clear as I wish I was.

@copumpkin I am still new to the Nix language and have had little time to learn it so I am not sure what the fix is.

For clarity through, the `gpg2` package contains a binary `gpgkey2ssh` and that binary is looking for a binary called `gpg` which is available in the `gnupg1compat` package. It seems like we should not have a binary in a package that requires a different package to use it, so I assumed this was a mistake/issue.

**Comment by peti** [comment]
GPG installs this tools unconditionally. Apparently upstream intends it to be installed even if `gpg` is not provided by the installation. Not sure whether that's a good idea or not

I would say, however, that this topic should be reported to the authors of GNU Privacy Guard.

**Comment by peti** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/11980.

**Comment by Nekroze** [comment]
@peti Thanks mate!
