### ISSUE TITLE
NixOS has issues with performace on btrfs filesystem.

### ISSUE THREAD

**Issue by ishan9299** [NixOS/nixpkgs#119100]
**Describe the bug**
I had a year old NixOS installation on btrfs + encryption alongwith a swap partition with zswap enabled. I was and still am using the nix flakes with my configuration. I didn't notice this right away but I had a lot performance issues when the OS booted up because I had enabled auto garbage collection and store optimizations in my configuration. After disabling those performance was reasonable but always came up whenever I used the nix command. I also checked my fstab there were no options like noatime,space_cache present which are supposed to increase the speed, so I did add those to my configuration but it didn't help a lot. I have reinstalled my system with xfs + encryption and these issues don't seem to be present anymore. So my guess would be these issues came up because I had not disabled copy-on-write for btrfs on nix store. So if possible can someone test this out? I might have provided more info by using a virtual machine but I have a data cap and online classes sorry.

**Comment by xaverdh** [comment]
I have been using btrfs for the nix store for quite some time without any issues. I do garbage collection manually from time to time though.
There used to be a problem with compression being ignored (https://github.com/NixOS/nix/issues/3550), which should be fixed now. `copy-on-write` is certainly not an issue (unless there is a bug), since data from the nix store is never modified at all.

Maybe btrfs has issues with the `heavy read + delete` pattern that occurs when gc happens while booting?
Also while data in the store proper (/nix/store) is never modified, /nix/var/ contains logs and a database, so it might be worth setting `nocow` on that directory.
Also nix with flakes writes to a cache in the home directory I think, so if that is on btrfs as well, it might also potentially affect performance.

**Comment by xaverdh** [comment]
ah other things of interest would be the hardware (ssd or rotating) and the kernel version used (there is still a lot of change in btrfs land even these days).

**Comment by ishan9299** [comment]
My entire drive was formatted with btrfs, so yes the home directory was also btrfs.
My drive is rotating. 
Kernel Version is :- 
`Linux X542URR 5.11.11 #1-NixOS SMP Tue Mar 30 12:30:31 UTC 2021 x86_64 GNU/Linux`
There was an issue which made btrfs slower in 5.10 I think but this issue was experienced even in the lts(5.4 at the time) and 5.11.

**Comment by emmanuelrosa** [comment]
I use btrfs. It works fine but some files do get heavily fragmented overtime, such as sqlite databases and the systemd journal. I have a systemd timer which runs a btrfs defrag on such files. The job runs about 10 minutes after booting and it keeps fragmentation under control. With an SSD fragmentation isn't as big of an issue, in my experience. But, it does consume metadata, thus I still use the aforementioned defrag job.

**Comment by ishan9299** [comment]
@emmanuelrosa are these the files you are referencing?
```
me on X542URR in ~/.cache/nix
at 🕙17:45:50 ❯ ls
binary-cache-v6.sqlite
binary-cache-v6.sqlite-journal
eval-cache-v2
fetcher-cache-v1.sqlite
fetcher-cache-v1.sqlite-journal
flake-registry.json -> /nix/store/qi48i5dkbffrdxc15rhdz1x4mpm6q6n3-flake-registry.json
```
If that is the case I might try it in a VM.

**Comment by Atemu** [comment]
Does Nix check the integrity of its DBs and caches? I'm not sure how comfortable I'd be disabling checksumming/cow on those if not.

**Comment by emmanuelrosa** [comment]
I was referring to sqlite databases in general. But more broadly, I defrag files I know get fragmented due to many random writes.

In some cases that's not enough. For example, for VMs I have a dedicated LVM volume group. For my bitcoin lightning node (clightning), it put its data files on ext4.

**Comment by ishan9299** [comment]
@emmanuelrosa then can I close the issue? It can still be used for discussion about the matter.

**Comment by emmanuelrosa** [comment]
Yes, I think so.
