### ISSUE TITLE
gparted: installation-cd-graphical-base.nix: Unable to resize FAT32 and other filesystems

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#119177]
**Describe the bug**
GParted in the installation ISO images cannot create, resize, move and do other operations on many filesystems such as FAT32.

This problem is due to absence of related (optional) run-time dependencies such as `dosfstools` and `mtools` (in the case of FAT32). `nix-env -iA [needed-packages]` in live session doesn't solve the problem.

The supports to filesystems other than ext4 is important especially when you need to operate on the EFI System Partition (ESP), NTFS for Windows, HFS for Mac, and BTRFS used by some other Linux distributions.

Possible solution includes:
1. Put all the run-time dependencies required for GParted to operate on those filesystems in the `environment.systemPackages` list in `installation-cd-graphical-base.nix`.
2. Make a new package, `gparted-full`, and show it in `all-packages.nix`. Replace `gparted` with 'gparted-full' in `environment.systemPackages` list in `installation-cd-graphical-base.nix`.

**To Reproduce**
1.  Go to https://nixos.org/download.html and download the 64bit Plasma Desktop ISO image, which is https://channels.nixos.org/nixos-20.09/latest-nixos-plasma5-x86_64-linux.iso
2. Boot the image after burning it to a USB stick or attaching to a virtual machine.
3. Make sure that there is a FAT32 partition on your machine. Most computers have EFI System Partition, which is usually FAT32. If there isn't any, an USB stick with a FAT32 partition can be attachede
4. Open GParted and right-click on the FAT32 partition, it can be noticed that some options including `Resize/Move` are grayed out.
5. Right-click on an un-allocated space, click `New`, and it can be seen that many options including FAT32 have been grayed out.

**Expected behavior**
GParted on the ISO installation image can operate on all or most of the supported file systems.

**Screenshots**

**Additional context**
Filesystems supported by GParted:
https://gparted.org/features.php

**Notify maintainers**

@snicket2100 @nckx

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - config.system.build.isoImage
# a list of nixos modules affected by the problem
module:
  - gparted
  - installation-cd-graphical-base.nix
```

**Comment by turion** [comment]
I had the same issue now.

**Comment by Artturin** [comment]
Related #132094

**Comment by qwabra** [comment]
`NixOS 21.11 (Porcupine); Build ID: 21.11.335733.f6ddd55d5f9`

console `parted` and "disks" - fat32 fail

GPartet - ok
