### ISSUE TITLE
NetworkManager[496]: <error> [1450947554.023776] [nm-modem.c:532] ppp_stage3_ip_config_start(): (ttyUSB2): error starting PPP: (1) Could not find  "pppd" binary

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#11922]
Can't connect through the usb 3g modem.
That message appears in the log while NetworkManager trying to connect .
ppp package is installed.
nix-env -q => ppp-2.4.7

ModemManager is running.
usb_modeswitch is runned also.

**Comment by jgillich** [comment]
Which NixOS version are you running? The package sets `--with-pppd=${ppp}/bin/pppd` so this shouldn't happen..

**Comment by danykey** [comment]
15.09.784.7b85b8a
Before I had use some previous branch of 15.09. Later I had upgrade to current 15.09 and did nixos-rebuild switch --upgrade, reboot and the problem still exists.

**Comment by rasendubi** [comment]
(triage) does this still happen?

**Comment by rasendubi** [comment]
Issue is old and silent -- closing.
