### ISSUE TITLE
Ardour does not find LADSPA Plugins 

### ISSUE THREAD

**Issue by karthikiyengar** [NixOS/nixpkgs#119265]
**Describe the bug**
The ladspa plugins are not detected by ardour with `ladspaPlugins` installed. 

**To Reproduce**
Install ardour and ladspaPlugins and check the Plugin Manager 

**Expected behavior**
The plugin should be detected and the related effects should show up 

**Notify maintainers**
@goibhniu @magnetophon @mitchmindtree

**Comment by mitchmindtree** [comment]
I have this in `home.sessionVariables` within my home manager config:

```nix
        # Plugin paths.
        DSSI_PATH   = "$HOME/.dssi:$HOME/.nix-profile/lib/dssi:/run/current-system/sw/lib/dssi";
        LADSPA_PATH = "$HOME/.ladspa:$HOME/.nix-profile/lib/ladspa:/run/current-system/sw/lib/ladspa";
        LV2_PATH    = "$HOME/.lv2:$HOME/.nix-profile/lib/lv2:/run/current-system/sw/lib/lv2";
        LXVST_PATH  = "$HOME/.lxvst:$HOME/.nix-profile/lib/lxvst:/run/current-system/sw/lib/lxvst";
        VST_PATH    = "$HOME/.vst:$HOME/.nix-profile/lib/vst:/run/current-system/sw/lib/vst";
        VST3_PATH   = "$HOME/.vst3:$HOME/.nix-profile/lib/vst3:/run/current-system/sw/lib/vst3";
```

From memory it worked after adding this, though I think I've only used LV2 plugins (don't think I've tested ladspa plugins yet). If not using home-manager, there's probably some way to set these env vars in the regular nix config.

All that said, I agree it would be nice if we could have all these plugin path env vars set by default, or some other solution that was a little easier. Perhaps nixpkgs could have some convention where, any audio plugin host (i.e. ardour, reason, etc) enables these paths in a user's config by default if included? I'm unsure where exactly that option should live though.

**Comment by magnetophon** [comment]
The above code (probably) came from [musnix](https://github.com/musnix/musnix/blob/master/modules/base.nix#L69), a handy way to do all realtime audio settings in one go.
Might be worth taking a look if you want to make music on NixOS.

**Comment by karthikiyengar** [comment]
Thanks for the examples, I got it to work! I'm not sure how other distros handle it, but as @mitchmindtree mentioned, it'd be super cool if the paths were picked up automatically! 

Feel free to close the issue as appropriate :-)
