### ISSUE TITLE
bash 4.4 fails to cross-compile for Windows (pkgsCross.mingwW64.bash)

### ISSUE THREAD

**Issue by ramirez7** [NixOS/nixpkgs#119206]
**Describe the bug**
`pkgsCross.mingwW64.bash` fails with

```
nix-repl> :b p.pkgsCross.mingwW64.bash
builder for '/nix/store/wpxw7f2dh4aandb84r8jw84r9vq9dc4k-bash-4.4-p23-x86_64-w64-mingw32.drv' failed with exit code 2; last 10 log lines:
  rm -f mksyntax.exe
  gcc  -DPROGRAM='"bash.exe"' -DCONF_HOSTTYPE='"x86_64"' -DCONF_OSTYPE='"mingw32"' -DCONF_MACHTYPE='"x86_64-w64-mingw32"' -DCONF_VENDOR='"w64"' -DLOCALEDIR='"/nix/store/z8fqks8jcmkd203yjwqlpf5dj6zivk69-bash-4.4-p23-x86_64-w64-mingw32/share/locale"' -DPACKAGE='"bash"' -DSHELL -DHAVE_CONFIG_H   -I.  -I. -I./include -I./lib -I./lib/intl -I/build/bash-4.4/lib/intl  -g -DCROSS_COMPILING  -g -DCROSS_COMPILING -o mksyntax.exe ./mksyntax.c 
  In file included from ./mksyntax.c:23:
  ./config.h:353:19: error: two or more data types in declaration specifiers
    353 | #define socklen_t unsigned int
        |                   ^~~~~~~~
  ./config.h:353:28: error: two or more data types in declaration specifiers
    353 | #define socklen_t unsigned int
        |                            ^~~
  make: *** [Makefile:691: mksyntax.exe] Error 1
[0 built (1 failed), 58 copied (2551.9 MiB), 443.8 MiB DL]
error: build of '/nix/store/wpxw7f2dh4aandb84r8jw84r9vq9dc4k-bash-4.4-p23-x86_64-w64-mingw32.drv' failed
```

**To Reproduce**
1. Build `pkgsCross.mingwW64.bash` on either `20.09` or current HEAD (`61886ca7b264a83dad1bcdf10d1a6965aab6556f`)

**Expected behavior**
The package would build correctly.

**Screenshots**
n/a

**Additional context**
n/a
**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ramirez7** [comment]
Looking further, I believe that bash's configure is doing this bad define because `sys/socket.h` is missing..which is a POSIX header, so it makes sense it isn't present for mingwW64

Maybe the issue here isn't bash but rather the fact that I'm trying to build it to begin with?

**Comment by jbalme** [comment]
> Maybe the issue here isn't bash but rather the fact that I'm trying to build it to begin with?

I believe this is correct.

Bash doesn't natively support Windows - you need to build for Cygwin (or MSYS) instead

**Comment by ramirez7** [comment]
> Bash doesn't natively support Windows - you need to build for Cygwin (or MSYS) instead

I'm actually only building bash transitively, so it sounds like one package in my dependency graph is not properly packaged for Windows. I'll have to hunt down the offender.

Thanks!
