### ISSUE TITLE
Adopt a convention for a *persistent* mutable systemd unit directory.

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#119306]
This is following up on https://github.com/NixOS/nixpkgs/pull/112891 after it may or may not have broken some extra-container functionality.

cc @flokli 

I understand the desire to decrease divergence from upstream, but we are not upstream and our system does not work the same way. `/run/systemd/system` may be mutable, but it adds a burden on users and applications that did not previously exist with the hard-patched path, if they wish to use persistence. 

The system should provide a mutable persistent directory so that applications and users don't have to worry about modifying system configuration (configuration.nix) or about modifying system state (https://github.com/NixOS/nixpkgs/pull/116455#issuecomment-806510416). There was no need for either of these before and there shouldn't be now. This is functionality that should be provided by the system.

I understand that the proposed alternatives are running some sort of service that restores units on startup to the /run directory, or adding user or application specified search directories. This seems unnecessarily fragile and fragments the ecosystem, when there is no need to.

By removing this function without providing an alternative, you impose an extra burden on applications and users needing to configure their system for said applications, which didn't exist before, and fragments configuration unnecessarily.

cc @erikarvstedt (sorry for all the mentions today)

It doesn't matter that this was an undocumented feature that people just started using, that's a non-argument, Nix* projects are largely undocumented ("self-documenting") anyway. 

I don't care about the actual mechanism used, if you don't like diverging from upstream with that relatively simple-seeming patch; it worked for years, please don't remove it without providing an alternative with feature parity.

Edit: linked wrong PR

**Comment by deliciouslytyped** [comment]
The best solution offhand seems to be to give https://github.com/NixOS/nixpkgs/pull/116455/files#diff-56652f3dbfb669e8cb7c4ee4c16cc79ccdb8c6b89bbbf8d92751ad92c57288a9R90 a default value.

It's less complex than a restoration service for /run/whatever, which you probably want to be ephemeral anyway.

**Comment by deliciouslytyped** [comment]
So to come full circle, how about setting it to "/etc/systemd-mutable"?

**Comment by deliciouslytyped** [comment]
@svanderburg

**Comment by aanderse** [comment]
How about letting the user pick and supply the value? I'm trying to understand the problem with that. We're talking about a minority of nixos users, I'm not sure what the problem with adding 1 additional path is 🤷‍♂️ 

You could even let a module control this... I bet that is what @svanderburg will do, eliminating the need for what you're suggesting is his case.

**Comment by pasqui23** [comment]
Why don't we use `/usr/lib/systemd`? It is the place designated by upstream for units to be installed by the "pacckage manager" (`nixos-rebuild` in our case) and it would allow us use of `systemctl mask`.

**Comment by deliciouslytyped** [comment]
As a side note, this led to a bit of an insidious issue that I only figured out just now. Turns out that extra-container and declarative containers use the same thing to generate files, but since the systemd-mutable directory was removed from the search path, the services started using the container unit template from the system, which only coincidentally worked, because it had the same content.

Things became very confusing once I diverged from the system template and couldn't figure out why my containers weren't reacting.


@aanderse why not just have a standard directory for this?

**Comment by flokli** [comment]
> Why don't we use /usr/lib/systemd? 

For the same reasons we don't randomly pick up libraries from a `/usr/lib` - these interdependencies should be explicit.

In fact, `/usr/lib/systemd` is `${systemd}/lib/systemd` in NixOS (mostly cause that's where systemd also adds its own files).

Randomly picking up things from stateful paths, that survive reboots easily gets hairy, especially if multiple things are managing that folder. We shouldn't do this, especially not by default.

`/run/systemd/system` (and the and the difficulties due to it being lost after reboot) is unrelated to this discussion.

There is https://github.com/NixOS/nixpkgs/pull/112891, which provides a simple attribute to explicitly add other paths to look for unit files, including in more persistent locations.

Dysnomia has moved to just set that option, and I just filed a PR to update the docs on extra-container: https://github.com/erikarvstedt/extra-container/pull/20

I wasn't aware extra-container did also piggy-back on the path that was patched in for Dysnomia (which was long broken in nixpkgs).

In addition to the PR for extra-containers, I added a release note entry, in case there's anything else using that path: https://github.com/NixOS/nixpkgs/pull/119368

**Comment by aanderse** [comment]
> declarative containers use the same thing to generate files

Are you saying declarative containers are broke? I'm pretty sure tests would fail if that was the case...

**Comment by deliciouslytyped** [comment]
@aanderse no, they aren't; another way to say it is that the declarative container unit template accidentally ended up being an unintended fallback.

**Comment by deliciouslytyped** [comment]
Well, I'm not happy with this, but I'm not the maintainer, and it looks like the maintainer isn't going to change their opinion.

**Comment by flokli** [comment]
> I bet that is what @svanderburg will do, eliminating the need for what you're suggesting is his case.

The re-introduced NixOS Dysnomia module already does set that option.

**Comment by svanderburg** [comment]
@deliciouslytyped I didn't like this change in the beginning either, but making `SYSTEMD_UNIT_PATH` configurable solved the problem for me.

I have also readded the Dysnomia module that now uses this new configuration property to provide a mutable persistent systemd folder.
