### ISSUE TITLE
Several packages have sbin folders

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11939]
My understanding was that nix rejected the `bin`/`sbin` distinction and we avoided having `sbin` folders in our outputs.

At the same time, I see that at least the following packages have nontrivial `sbin` output folders:
* `iptables`
* `iproute`
* `ebtables`
* `lvm2`
* `udev`
* probably several more

And that we have workarounds like https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libvirt/default.nix#L27 in place to deal with that fact.

Questions:
* Are those packages supposed to have `sbin` output folders? Is the exception policy described somewhere?
* What mechanism is suppressing [this script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/move-sbin.sh) in [`iptables`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/iptables/default.nix), for example?
* It looks like at least for `ebtables`, the `sbin` was intentional: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/ebtables/default.nix#L13

**Comment by Mathnerd314** [comment]
Are you sure they're not symlinks? E.g. for iptables ``sbin`` is a symlink: http://hydra.nixos.org/build/28549743/contents/1. The script seems to be working fine here and on Hydra.

For the other examples, they were written before the move-sbin-to-bin script, so they can probably just be fixed to use /bin.

A stricter policy would be to remove /sbin completely; I like that, as the current approach does cause some overhead, particularly in buildEnv (It's not smart enough to merge all the symlinks together)

**Comment by vcunat** [comment]
> A stricter policy would be to remove /sbin completely;

That would first need quite some changes in nixpkgs:
```
$ git grep '}/sbin' | wc -l
315
```
but it should be safe to sed this without much checking.

**Comment by vcunat** [comment]
> What mechanism is suppressing this script in iptables, for example?

All packages on this list **do** have sbin only as symlink to bin (x86_64-linux, master). Perhaps some buildEnv confused you? (It seems you meant the same platform.)

> It looks like at least for ebtables, the sbin was intentional

The `sbin` string there was added very long ago: bb2bd151af.

**Comment by Profpatsch** [comment]
(triage) Is there an action item? Are the sbin folders problematic?

**Comment by cleverca22** [comment]
i believe there is a fixupPhase that moves all sbin items to bin, but then symlinks sbin to bin incase sbin paths where hard-coded into things

that may be part of what is adding confusion to this

**Comment by vcunat** [comment]
In all the cases above it's just a `sbin -> bin` symlink, as there's that hook moving stuff around. It doesn't seem likely to me that someone would really want to eliminate all `sbin` references, as it's nontrivial work with risks of breakage and very little to gain IMHO.

(Also, contrary to `/usr` merge that is quite common nowadays, I haven't noticed any other distro getting rid of `sbin`.)
