### ISSUE TITLE
kodi fails to start due to libEGL glibc version mismatch

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#119329]
**Describe the bug**

kodi & kodi-wayland fails to start on nixos-20.09

when installed from nixpkgs-unstable, it works fine

**To Reproduce**

```
> nix-env -iA nixos.kodi-wayland

> kodi
libEGL warning: MESA-LOADER: failed to open i965: /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /run/opengl-driver/lib/dri/i965_dri.so) (search paths /run/opengl-driver/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /run/opengl-driver/lib/dri/swrast_dri.so) (search paths /run/opengl-driver/lib/dri)

ERROR: Unable to create GUI. Exiting
```

**Notify maintainers**

@domenkozar @titanous @edwtjo @peterhoeg @sephalon

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.104, NixOS, 21.05pre275813.c5147860e23 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-21.05pre278688.c0e88185200, nixos-20.09.3451.aceb539221d, nixos-unstable-21.05pre275822.916ee862e87"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by symphorien** [comment]
It looks like you installed kodi from unstable on stable. libgl is impure even on nixos so you probably shouldn't mix versions like that.

**Comment by tg-x** [comment]
actually installing it from unstable it worked.
the one from the stable channel did not, though i did not upgrade all the other stable packages before on this 20.09 system, perhaps that's why?

**Comment by peterhoeg** [comment]
As it works on unstable (and presumably 21.11), I'll close this.

**Comment by shymega** [comment]
I believe there's been a re-emergence of this bug. I will open a new bug report shortly, as it's on 23.05,  but I will link it here. Haven't been able to test on unstable yet.

Essentially, similar error with `glibc` and a subsequent segfault. If I forget to open a bug report, feel free to @ me.
