### ISSUE TITLE
Two copies of dylibbundler

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#119385]
there are two copies of (mac)dylibbundler in the nixpkgs tree:
`pkgs/development/tools/misc/macdylibbundler` with @alexfmpe as maintainer and `pkgs/tools/misc/dylibbundler` with @nomeata as maintainer. Presumably one of them should remain and the other should be removed. I'll leave it to the maintainers to work that out, though macdylibbundler seems more fleshed out and was committed more recently.

**Comment by nomeata** [comment]
You listed them in the wrong order, `pkgs/tools/misc/dylibbundler/default.nix` is by @alexfmpe and `pkgs/development/tools/misc/macdylibbundler/default.nix` is by me.

Embarrassing that I didn’t find the other one. Maybe because I was grepping for `macdylibbundler`, sorry for that.

Happy to yield maintainership to @alexfmpe, but if we remove mine, idallly include the change that makes it propagate the dependency on `otool` (See #103163 and subsequent refinements.)

**Comment by Radvendii** [comment]
We could also keep both of you as maintainers.

I think the only decision left then is whether to call it "dylibbundler" or "macdylibbundler", given that you didn't find the one that was called "dylibbundler", but someone searching for "dylibbundler" *would* find "macdylibbundler", maybe it makes sense to call it "macdylibbundler"? Maybe leave a package alias so "dylibbundler" will continue to work as a package name. I don't know if we try to avoid package aliases or not.

I'm also happy to make the changes and submit a PR, just wanted to make sure I knew what should go in the PR first.

**Comment by alexfmpe** [comment]
> Happy to yield maintainership to @alexfmpe, but if we remove mine, idallly include the change that makes it propagate the dependency on otool (See #103163 and subsequent refinements.)

Mine's over two years old so might be best to just keep yours as it's basically a bump I think.

> We could also keep both of you as maintainers.

I have no problems with being co-maintainer or yielding it over. Have barely touched mac for a year.


> I think the only decision left then is whether to call it "dylibbundler" or "macdylibbundler", given that you didn't find the one that was called "dylibbundler", but someone searching for "dylibbundler" would find "macdylibbundler", maybe it makes sense to call it "macdylibbundler"? Maybe leave a package alias so "dylibbundler" will continue to work as a package name. I don't know if we try to avoid package aliases or not.

Makes sense to me
