### ISSUE TITLE
Moneyplex is Out-of-date and Links are broken

### ISSUE THREAD

**Issue by oyren** [NixOS/nixpkgs#119349]
The Moneyplex package is quite old, which was not a problem as the package could update itself. But now the links to the old versions are dead, so the package should be updated to version 20. 

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

current version: 16.0.22424
desired version: 20

###### Notify maintainers

maintainers: tstrobel (Thomas Strobel, 4ZKTUB6TEP74PYJOPWIR013S2AV29YUBW5F9ZH2F4D5UMJUJ6S@hash.domains) @ts468

###### Note for maintainers

Please tag this issue in your PR.

**Comment by dotlambda** [comment]
@oyren Unless you plan on updating the package yourself, I think we ought to remove it from nixpkgs. @ts468 isn't active anymore.

**Comment by oyren** [comment]
It will then probably have to be removed, unfortunately, as my knowledge is not sufficient to fix the package. I had already looked at it, but the new installer of Moneyplex is GUI based. There should be a console mode and silent mode, but these do not work for me even under Kubuntu.
``` console
$ ./moneyplex_setup64 --help
Usage: moneyplex_setup64 [options ...]

Available Options:
  --help           display this information
  --mode [ARG]     set the mode to run the installer in
                   Available values: console, default, silent or standard
  --prefix [ARG]   set the installation directory
  --temp [ARG]     set the temporary directory used by this program
  --version        display installer version information
```

``` console
$ ./moneyplex_setup64 --mode console
```

I also tried a few other combinations with ", ' etc., but nothing happens. Does nixpkgs support using GUI installer in any way?

I will write a mail to the developer today.

**Comment by dotlambda** [comment]
> I will write a mail to the developer today.

Let us know when you hear back from them.
