### ISSUE TITLE
Infinite recursion when evaluating NetBSD

### ISSUE THREAD

**Issue by alyssais** [NixOS/nixpkgs#119323]
Since 00a2084a409e65e9781e9792644bbf5b1b1bca5a (cc @Mic92), trying to evaluate any packages in the "netbsd" namespace when targeting NetBSD has resulted in an infinite recursion:

```
% nix-instantiate -A pkgsCross.amd64-netbsd.netbsd.column
error: infinite recursion encountered, at undefined position
```

This appears to be coming from `stdenv.cc.isGNU`:

<details>
<summary>Stack trace</summary>
<pre>error: while evaluating 'mkAttrOverridable' at /home/src/nixpkgs/lib/customisation.nix:133:33, called from undefined position:
while evaluating 'makeOverridable' at /home/src/nixpkgs/lib/customisation.nix:67:24, called from /home/src/nixpkgs/lib/customisation.nix:133:36:
while evaluating anonymous function at /home/src/nixpkgs/lib/customisation.nix:133:53, called from /home/src/nixpkgs/lib/customisation.nix:69:16:
while evaluating the attribute 'column' at /home/src/nixpkgs/pkgs/os-specific/bsd/netbsd/default.nix:494:3:
while evaluating 'makeOverridable' at /home/src/nixpkgs/lib/customisation.nix:67:24, called from /home/src/nixpkgs/pkgs/os-specific/bsd/netbsd/default.nix:494:12:
while evaluating anonymous function at /home/src/nixpkgs/pkgs/os-specific/bsd/netbsd/default.nix:25:39, called from /home/src/nixpkgs/lib/customisation.nix:69:16:
while evaluating 'optionalAttrs' at /home/src/nixpkgs/lib/attrsets.nix:349:25, called from /home/src/nixpkgs/pkgs/os-specific/bsd/netbsd/default.nix:70:8:
while evaluating the attribute 'cc.isClang' at /home/src/nixpkgs/pkgs/stdenv/generic/default.nix:166:14:
while evaluating the attribute 'gcc' at /home/src/nixpkgs/pkgs/top-level/all-packages.nix:10160:3:
while evaluating 'addMetaAttrs' at /home/src/nixpkgs/lib/meta.nix:15:28, called from /home/src/nixpkgs/pkgs/top-level/all-packages.nix:10351:11:
while evaluating 'wrapCC' at /home/src/nixpkgs/pkgs/top-level/all-packages.nix:11515:12, called from /home/src/nixpkgs/pkgs/top-level/all-packages.nix:10351:20:
while evaluating 'wrapCCWith' at /home/src/nixpkgs/pkgs/top-level/all-packages.nix:11489:5, called from /home/src/nixpkgs/pkgs/top-level/all-packages.nix:11515:16:
while evaluating 'callPackageWith' at /home/src/nixpkgs/lib/customisation.nix:117:35, called from /home/src/nixpkgs/pkgs/top-level/all-packages.nix:11503:7:
while evaluating 'makeOverridable' at /home/src/nixpkgs/lib/customisation.nix:67:24, called from /home/src/nixpkgs/lib/customisation.nix:121:8:
while evaluating anonymous function at /home/src/nixpkgs/pkgs/build-support/cc-wrapper/default.nix:8:1, called from /home/src/nixpkgs/lib/customisation.nix:69:16:
while evaluating the attribute 'NIX_CFLAGS_COMPILE' of the derivation 'libc-netbsd-8.0-x86_64-unknown-netbsd' at /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:
while evaluating the attribute 'extraPaths' of the derivation 'csu-netbsd-8.0-x86_64-unknown-netbsd' at /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:203:11:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'cvs-export' at /home/src/nixpkgs/pkgs/build-support/fetchcvs/default.nix:11:3:
while evaluating the attribute 'buildInputs' of the derivation 'openssh-8.5p1' at /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:197:11:
while evaluating 'getOutput' at /home/src/nixpkgs/lib/attrsets.nix:482:23, called from undefined position:
while evaluating anonymous function at /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:148:17, called from undefined position:
while evaluating 'spliceReal' at /home/src/nixpkgs/pkgs/top-level/splice.nix:28:16, called from /home/src/nixpkgs/pkgs/top-level/splice.nix:72:65:
while evaluating 'tryGetOutputs' at /home/src/nixpkgs/pkgs/top-level/splice.nix:63:25, called from /home/src/nixpkgs/pkgs/top-level/splice.nix:78:30:
while evaluating 'getOutputs' at /home/src/nixpkgs/pkgs/top-level/splice.nix:66:22, called from /home/src/nixpkgs/pkgs/top-level/splice.nix:65:12:
while evaluating 'genAttrs' at /home/src/nixpkgs/lib/attrsets.nix:309:21, called from /home/src/nixpkgs/pkgs/top-level/splice.nix:66:29:
while evaluating 'optionalAttrs' at /home/src/nixpkgs/lib/attrsets.nix:349:25, called from /home/src/nixpkgs/pkgs/top-level/splice.nix:65:24:
while evaluating the attribute 'openssl' at /home/src/nixpkgs/pkgs/top-level/all-packages.nix:16752:3:
while evaluating the attribute 'openssl_1_1' at undefined position:
while evaluating 'mkAttrOverridable' at /home/src/nixpkgs/lib/customisation.nix:133:33, called from undefined position:
while evaluating 'makeOverridable' at /home/src/nixpkgs/lib/customisation.nix:67:24, called from /home/src/nixpkgs/lib/customisation.nix:133:36:
while evaluating anonymous function at /home/src/nixpkgs/lib/customisation.nix:133:53, called from /home/src/nixpkgs/lib/customisation.nix:69:16:
while evaluating the attribute 'openssl_1_1' at /home/src/nixpkgs/pkgs/development/libraries/openssl/default.nix:182:3:
while evaluating 'common' at /home/src/nixpkgs/pkgs/development/libraries/openssl/default.nix:25:12, called from /home/src/nixpkgs/pkgs/development/libraries/openssl/default.nix:182:17:
while evaluating 'mkDerivation' at /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:22:5, called from /home/src/nixpkgs/pkgs/development/libraries/openssl/default.nix:26:4:
while evaluating 'extendDerivation' at /home/src/nixpkgs/lib/customisation.nix:144:43, called from /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:348:7:
while evaluating anonymous function at /nix/store/pvm3jaq8ca43i13qzvlb1if6nwymylcr-nix-2.3.10/share/nix/corepkgs/derivation.nix:4:1, called from /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:384:10:
while evaluating 'optional' at /home/src/nixpkgs/lib/lists.nix:254:20, called from /home/src/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:101:29:
while evaluating the attribute 'cc.isGNU' at /home/src/nixpkgs/pkgs/stdenv/generic/default.nix:166:14:
infinite recursion encountered, at undefined position</pre>
</details>

cc @matthewbauer @dtzWill @Ericson2314 (people who have previously worked on NetBSD packages in Nixpkgs)

**Comment by veprbl** [comment]
Possibly relevant to #119076

**Comment by Mic92** [comment]
Does this mean that cc depends on openssl somehow?

**Comment by sternenseemann** [comment]
> Does this mean that cc depends on openssl somehow?

Yes via fetchcvs which needs openssh which depends on openssl. At least that's what it looks like when instantiating `pkgsCross.amd64-netbsd` which is a even more minimal reproducer.

**Comment by Mic92** [comment]
Would this work as a work-around?

```
 separateDebugInfo = stdenv.hostPlatform.isLinux &&  stdenv.cc.isGNU;
```

Or do we need the netbsd namespace on Linux as well?

**Comment by alyssais** [comment]
> Would this work as a work-around?
>
> ```
>  separateDebugInfo = stdenv.hostPlatform.isLinux &&  stdenv.cc.isGNU;
> ```
>
> Or do we need the netbsd namespace on Linux as well?

It's good to have on Linux -- lots of the stuff in there is portable.
And we definitely need it on Darwin, because we use bits of NetBSD
whenever macOS is insufficient.

**Comment by sternenseemann** [comment]
Native evaluation is not an issue, turns out the issue was just that depending on the evaluation of `stdenv.cc` tripped up the evaluation of the cross stdenv for `amd64-netbsd`: #119430.
