### ISSUE TITLE
VScodium 1.55.0 not working on darwin

### ISSUE THREAD

**Issue by Feliix42** [NixOS/nixpkgs#119360]
**Describe the bug**
On macOS 10.14.6, the latest version of the `vscodium` package is not working. It seems that the `codium` binary is missing. It should be in `Applications/VSCodium.app/Contents`, but the directory does only contain these files:
```
[felix@tycho] $ ls Applications/VSCodium.app/Contents
_CodeSignature    Frameworks    Info.plist    MacOS    PkgInfo    Resources
```

**To Reproduce**
Run this on a darwin system:
```
nix-env -iA nixpkgs.vscodium
```

**Expected behavior**
A normal invocation of the program like `codium .` should work.

**Screenshots**
n/a

**Additional context**
Installing the package already hints towards the problem:

```
installing 'vscodium-1.55.0'
building '/nix/store/3ydfcjy3g98qfgrqqq6rvqdgqvq45bks-user-environment.drv'...
warning: skipping dangling symlink '/nix/store/qpahs85yhjaccbjff6f3vgddmi6khp5p-user-environment/bin/codium'
created 1121 symlinks in user environment
```

**Notify maintainers**
@Synthetica9 and @turion are listed as maintainers.

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(felix): `"nixpkgs-21.05pre282548.4c87cb87a2d"`
 - nixpkgs: `/Users/felix/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by enderger** [comment]
Unfortunately, like most electron apps, to fix this would require a separate expression for Darwin to build (the file structure of Electron is very different on OSX compared to Windows and Linux).

**Comment by Feliix42** [comment]
But was there any significant change between versions `<1.55.0` and the current one? Previous versions installed and ran without issue.

**Comment by layday** [comment]
The issue here is that the bundled executable is no longer called "code" but "codium" and the generated symlink is broken.  The offending line is:

https://github.com/NixOS/nixpkgs/blob/e5cc06a1e806070693add4f231060a62b962fc44/pkgs/applications/editors/vscode/generic.nix#L78

**Comment by enderger** [comment]
Ah, sorry. I thought that VSCodium just wasn’t packaged for Mac yet.

**Comment by Artturin** [comment]
the symlink line in the expr is now 
```
      ln -s "$out/Applications/${longName}.app/Contents/Resources/app/bin/${sourceExecutableName}" $out/bin/${executableName}
```
