### ISSUE TITLE
write tests that work despite differences in store path / can we bring some of home-manager's testing infra in nixpkgs ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#119474]
**Project description**
In https://github.com/NixOS/nixpkgs/pull/119467 I wanted to write tests and check that the generated vimrc matches a certain template
```
set nocompatible
set packpath=/nix/store/xxxxx
....
```
Now because the generated vimrc contains store paths, I can't just diff it against a saved valid vimrc (since store paths would change). 

home-manager allows to check the generated file is similar via assertFileContent cf https://github.com/nix-community/home-manager/blob/master/tests/modules/programs/neovim/plugin-config.vim and https://github.com/nix-community/home-manager/blob/master/tests/modules/programs/neovim/plugin-config.nix

Do we have something similar in nixpkgs ? could we bring these from home-manager ? @rycee

**Comment by berbiche** [comment]
The test assertions used in HM: https://gitlab.com/rycee/nmt/-/blob/master/bash-lib/assertions.sh

**Comment by teto** [comment]
yes thanks, I've already started playing with
```
   nmt = pkgs.fetchFromGitLab {
    owner = "rycee";
    repo = "nmt";
    rev = "d2cc8c1042b1c2511f68f40e2790a8c0e29eeb42";
    sha256 = "1ykcvyx82nhdq167kbnpgwkgjib8ii7c92y3427v986n2s5lsskc";
  };
```

**Comment by teto** [comment]
importing nmt fulfills my need.
