### ISSUE TITLE
appimage-run cache requires sudo to remove

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#119442]
**Describe the bug**
the files appimage-run produces in `$HOME/.cache/appimage-run/` require sudo privileges to remove. This isn't a huge problem for me personally because I have sudo privileges, but it's not great UX, and it might cause problems for multi-user setups.

**To Reproduce**
1. `nix-shell -p appimage-run --run "appimage-run Some.AppImage"`
2. `rm -rf ~/.cache/appimage-run`
3. permission denied.

**Expected behavior**
Files in `$HOME/.cache` are removable by me without sudo.

**Notify maintainers**
@symphorien @bignaux @timokau touched appimage-run somewhat recently.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05pre281538.9e377a6ce42 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-21.05pre281538.9e377a6ce42, nixos-hardware"`
 - channels(qolen): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:appimage-run
# a list of nixos modules affected by the problem
module:
```

**Comment by enderger** [comment]
I've found that is an issue with extracting AppImages in general (not just on Nix). I think it's a file permissions issue where extracted files say they are owned by `root`.

**Comment by Radvendii** [comment]
Oh, huh. Good to know, thanks. I'll submit an issue upstream then (if it's not already).

**Comment by symphorien** [comment]
1. I can't reproduce
2. How can appimage-run create files owned by root if you run it as your user?
I think you ran appimage-run as sudo withouth resetting HOME or XDG_WHATEVER_DIR.

**Comment by enderger** [comment]
@symphorien I think the files keep their ownership when converted to an AppImage, some of which were originally created as root.

**Comment by Radvendii** [comment]
Yes. This is using an appimage that is converted from a nix package, so the files were originally in the nix store, then got put in an AppImage, then the AppImage got run using appimage-run. Is this the expected behaviour? I would expect putting something in an AppImage and back to wipe the permissions, but I'm not sure if that's a reasonable expectation.

**Comment by symphorien** [comment]
Yes, but the files are copied to ~/.cache as user so they can't keep their original owner in ~/.cache.

**Comment by Radvendii** [comment]
You're right. It's owned by user it just has no write permissions. That's something I can fix when I create the AppImage.
