### ISSUE TITLE
searx: 0.18.0 -> 1.0.0

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#119414]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.18.0
desired version: 1.0.0

###### Notify maintainers

maintainers: matejc fpletz globin danielfullmer

###### Note for maintainers
I think there are quite some changes also in the `settings.yml` file. This may be relevant for the declarative configuration available in NixOS.

**Comment by pniedzwiedzinski** [comment]
#119529

**Comment by Lassulus** [comment]
closed by https://github.com/NixOS/nixpkgs/pull/119529
