### ISSUE TITLE
flash plugin in 15.09 no longer installs

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#11941]
there was a security update to flash.  so adobe seems to have removed the former url from their site.  It looks like this bug is already patched in master just needs a back port

**Comment by jgillich** [comment]
IMO, flash should be dropped altogether.

http://www.itgovernance.co.uk/blog/list-of-flash-vulnerabilities-in-2015/

**Comment by vcunat** [comment]
The HEAD of 15.09 downloads https://fpdownload.macromedia.com/pub/flashplayer/installers/archive/fp_11.2.202.554_archive.zip which seems perfectly fine to me. Note that the **channel** often lags behind https://nixos.org/wiki/FAQ#What_are_channels_and_how_they_get_updated.3F
