### ISSUE TITLE
xorg package set does not allow proper overriding of its elements

### ISSUE THREAD

**Issue by exi** [NixOS/nixpkgs#11944]
I tried to change pkgs.xkeyboard_config via overrideDerivation but noticed that internally, pkgs.xkeyboard_config is just an assignment from xorg.xkeyboardconfig.
This is a problem because sub-components of xorg like setxkbmap use the xorg set directly.
When modifying pkgs.xkeyboard_config with overrideDerivation I end up with the following scenario:

All global packages like display managers or the xserver.nix file use the pkgs.xkeyboard_config derivation and link against that.
All internal xorg packages like setxkbmap use the xorg internal derivation (pre pkgs.xkeyboard_config = xorg.xkeyboardconfig assignment) which cannot be modified by the overrideDerivation thus leading to two separate xkeyboard_config versions being in use at the same time.

**Comment by exi** [comment]
@bjornfor do you have any input for this? Im still unsure on how to start refactoring this.

**Comment by vcunat** [comment]
Well, I assume it is possible to override it, only the code to do so would be rather complex/clumsy. It's a problem shared by all nested attribute sets. We really should improve this somehow.

/cc @nbp (who's done lots of related stuff, I believe).

**Comment by exi** [comment]
@vcunat @nbp  i would appreciate a hint on how to override certain thinks at all.

In my case, i successfully patched pkgs.xkeyboard_config, but still have a reference to the pre-override xkeyboardconfig in x11/xorg/overrides.nix:184 that does not get updated but i need this to be updated as well.

**Comment by peti** [comment]
@exi, the Haskell manual has an example at http://nixos.org/nixpkgs/manual/#how-to-override-package-versions-in-a-compiler-specific-package-set that overrides an attribute of a nested package set.

**Comment by exi** [comment]
@peti after reading around a bit in the haskell and xorg expressions, i think the haskell way does _not_ work in the xorg case.

Haskell basically does this:
```
let
...
in
  fix'
    (extends overrides
      (extends packageSetConfig
        (extends compilerConfig
          (extends commonConfiguration haskellPackages))))
```

which explicitly takes "overrides" from the outside and thus, makes it modifyable.

Xorg however has this at the top:
```
# THIS IS A GENERATED FILE.  DO NOT EDIT!
args @ { clangStdenv, fetchurl, fetchgit, fetchpatch, stdenv, pkgconfig, intltool, freetype, fontconfig
, libxslt, expat, libpng, zlib, perl, mesa_drivers, spice_protocol
, dbus, libuuid, openssl, gperf, m4, libevdev, tradcpp, libinput, mcpp, makeWrapper, autoreconfHook
, autoconf, automake, libtool, xmlto, asciidoc, flex, bison, python, mtdev, pixman, ... }: with args;
let
  mkDerivation = name: attrs:
    let newAttrs = (overrides."${name}" or (x: x)) attrs;
        stdenv = newAttrs.stdenv or args.stdenv;
    in stdenv.mkDerivation (removeAttrs newAttrs [ "stdenv" ]);

  overrides = import ./overrides.nix {inherit args xorg;};
  xorg = rec {
...
}; in xorg
```

Here the overrides are within a locally bound let expression and never go outside of this let expressions, which makes it impossible to extend/override i think.

**Comment by peti** [comment]
@exi, all packages that are created with `callPackage` or `makeOverridable` support overriding; there is nothing package else sets would have to do to support that. The code you quoted from the Haskell package set makes overriding easier, yes, but that's all it does. For example, the following `~/.nixpkgs/config.nix` snippet replaces `xorg.xmessage` with a version that says "Hello, world" at build time and then exits:

    {
      packageOverrides = super: let self = super.pkgs; in {
        xorg = super.xorg // {
          xmessage = self.lib.overrideDerivation super.xorg.xmessage (drv: {
            configurePhase = "echo Hello, world; exit 1";
          });
        };
      };
    }

Now, it's build like this:

    $ nix-build --no-out-link "<nixpkgs>" -A xorg.xmessage
    these derivations will be built:
      /nix/store/0bq2q37cf5bflfx9hj5d8gwy3j2i4m1v-xmessage-1.0.4.drv
    building path(s) ‘/nix/store/zscpm6d46wslkp9ff868dxkd1260b12n-xmessage-1.0.4’
    unpacking sources
    unpacking source archive /nix/store/g18b5g7r7y4rkc6hwbf87ayqjf7lwccp-xmessage-1.0.4.tar.bz2
    source root is xmessage-1.0.4
    patching sources
    configuring
    Hello, world
    builder for ‘/nix/store/0bq2q37cf5bflfx9hj5d8gwy3j2i4m1v-xmessage-1.0.4.drv’ failed with exit code 1

**Comment by dezgeg** [comment]
I suppose overriding nested packages could be made easier / more DWIM if `packageOverrides` would be special cased for attribute sets marked with `recurseIntoAttrs`.

That is, since `xorg` is marked `recurseIntoAttrs`, the following would do a nested update of `xorg.xmessage` instead of assigning `xorg` to a singleton attribute set containing just `xmessage` (like the current implementation does):
````
/* NOTE: hypothetical syntax */
{
  packageOverrides = pkgs: rec {
    xorg.xmessage = pkgs.xorg.xmessage.override {
      /* whatever you want */
    };
  };
}
````

**Comment by exi** [comment]
@peti i did something really similar:
```
    packageOverrides = super: {
      xorg = super.xorg // {
        xkeyboardconfig = super.pkgs.lib.overrideDerivation super.xorg.xkeyboardconfig (old: {
          patches = [
            (builtins.toFile "exi-layout.patch" ''
            diff --git a/symbols/Makefile.in b/symbols/Makefile.in
            index 076f1e9..80a4bcf 100644
            --- a/symbols/Makefile.in
            +++ b/symbols/Makefile.in
            @@ -363,7 +363,7 @@ bt bw by \
             ca cd ch \
             cm cn cz \
             de dk \
            -ee es et epo eu \
            +ee es et epo eu exi \
             fi fo fr \
             gb ge gh gn \
             gr hr hu \
            diff --git a/symbols/exi b/symbols/exi
            new file mode 100644
            index 0000000..746bbb8
            --- /dev/null
            +++ b/symbols/exi
            @@ -0,0 +1,12 @@
            +default
            +partial alphanumeric_keys modifier_keys
            +xkb_symbols "basic" {
            +    include "us(altgr-intl)"
            +    name[Group1]= "English (international AltGr dead keys) exi mod";
            +    replace key <CAPS> {  [ Control_L, Control_L ] };
            +    replace key <LCTL> {
            +        type[Group1]="ONE_LEVEL",
            +        symbols[Group1] = [ ISO_Level3_Shift ]
            +    };
            +    modifier_map Control { <CAPS> };
            +};
            '')
          ];
        });
      };
    };
```

This however does not work as expected. xkeyboard_config is getting patched but setxkbmap which depends on xkeyboard_config is referring to the unpatched version.

The build output on nixos-rebuild switch is:
```
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/pjxwfcjba4hxcmqd93a8zz91a0ghgsn4-xkeyboard-config-2.15.drv
  /nix/store/cynzdkv1yrvbhzh2yrmwj8r1qs0xds92-libxkbcommon-0.5.0.drv
  /nix/store/8bknv9qijvra0qrcdz2kn7z64x1pisdv-gtk+3-3.18.5.drv
  /nix/store/00zwxj5j1sz3k0ai15ni0qbqii076yci-keybinder-0.3.0.drv
  /nix/store/25jpsn78iwda7dcydnp719bn3gw7z7k7-dconf-0.24.0.drv
  /nix/store/0b8fsh8jaxlkgvksbx1cch275x3x0z4f-ibus-1.5.11.drv
  /nix/store/23wznk8pqqzarbr82b4xmh896v8sazi0-gtk-exe-env.drv
  /nix/store/vn8jl91jbznv3yf9kkwgcmqx013khlf4-ibus-qt-1.3.3.drv
  /nix/store/wc19d96ipwml3j434kycv32bd2409qlj-qt-plugin-env.drv
  /nix/store/acdgy720sha8q1hzd5k0a8063zd1wwc6-set-environment.drv
  /nix/store/0jndjl6z68zvbn730pyj92gjmhlb6add-etc-zshenv.drv
  /nix/store/21900qn1b1m35n667mkgv3hyc2zx0m39-NetworkManager-l2tp-gnome-0.9.8.7.drv
  /nix/store/bdnc8pjk4l02q34p4ksgwl2686z5m5q1-gcr-3.16.0.drv
  /nix/store/5g7m5lpsaj7w3xn3dpz3klp34f4ymwq9-gnome-keyring-3.16.0.drv
  /nix/store/hbrx3d0nb111b028w8pybsralxbig06s-network-manager-applet-1.0.6.drv
  /nix/store/54kn4xq9k5ga4b0axprih22xkxma34a4-NetworkManager-openvpn-gnome-1.0.6.drv
  /nix/store/aphlgsb319h48s3r3l9xvkg17c8f3lmg-NetworkManager-openconnect-gnome-1.0.2.drv
  /nix/store/fd8xp1y2w1xww354fikrhk20xis1n28j-NetworkManager-vpnc-gnome-1.0.6.drv
  /nix/store/lfq19d1rp9acgipar9mdgyhifvsx3ynx-NetworkManager-pptp-gnome-1.0.6.drv
  /nix/store/3fpydymv9yzlclyjahy97y4nrcb7c7f5-user-units.drv
  /nix/store/9sibvf6nhmi23bpjffbjj6yggw7dm3wl-xvfb-run.drv
  /nix/store/mkkiq8gp1x2qsd7i1dwvyzxm55y1qqhf-i3-4.11.drv
  /nix/store/sjm5m7d1ri3m9q9km36cxlp57andpikm-xsession.drv
  /nix/store/x9dg7ji60wz36crjs9fwv6hsp1kwvwrb-desktops.drv
  /nix/store/dc933s9ra6hskzh4g90ynd5qzq056rz1-slim.cfg.drv
  /nix/store/2iwlz2xrbkj1l07s1cparvgr3mwzm52j-unit-display-manager.service.drv
  /nix/store/2ga3fmvzm9z57lgg7v4dmqzi3v8mvgxp-transmission-gtk-2.84.drv
  /nix/store/4avvqxmrzp1s9hlp7x1gifvy8r54dj9r-i3lock-2.7.drv
  /nix/store/qgwk7b804klwwy8plkg0rb84qqlxscdn-adwaita-icon-theme-3.16.0.drv
  /nix/store/54wfyx2y32vcvcg9zzjjp8ns3xfsjhnl-evince-3.16.0.drv
  /nix/store/184ambjmmxris5aqc7n2zgl9c1qvv9sx-libcanberra-0.30.drv
  /nix/store/zb1jcxmsdnki3rxcimyg6fvfdkwqvjpa-gtkmm-3.16.0.drv
  /nix/store/6xaqnn1d7gi5gy9sw4qp0gzk53660b7k-pavucontrol-3.0.drv
  /nix/store/vhnaynmci2m9g271lvfiwyc9ick7x6rd-qtbase-5.4.2.drv
  /nix/store/jkgrmjfsdhxvc3bdrppc2m4n3b3aap6f-qttools-5.4.2.drv
  /nix/store/l05pyh66am49gzdr9pps66kz1q2xa2pv-qtsvg-5.4.2.drv
  /nix/store/8jrzcliyhn78z3n1kqszp9rpdq4ci179-cantata-1.5.1.drv
  /nix/store/956gylvh9c68wwq4r0vnlzh958l1n1px-terminator-0.97.drv
  /nix/store/glj5qrh06d6vkyghaa0nkv1a38p7w6dh-gnome-themes-standard-3.16.0.drv
  /nix/store/1fk5l7mqlyvgijxd4a3x954jhs1nb8c3-libgweather-3.16.1.drv
  /nix/store/v064asbdphaj3017gq85k45cl4vw6bkl-webkitgtk-2.10.4.drv
  /nix/store/kvlid5l55ym9mpw78pd549byjgmh61wr-gnome-online-accounts-3.16.0.drv
  /nix/store/hw4hsq93i3s1ysqzm9x4kk4p89kikhcx-libgdata-0.16.1.drv
  /nix/store/lrflicfrky5z9mmjdg323jfal8ldd0ni-evolution-data-server-3.16.3.drv
  /nix/store/mp5ca95g0fhh7iv3hpvaki0snhzpsgqd-tracker-1.4.0.drv
  /nix/store/vig00iajmrh749h6svk7yzr8m3jbqwig-gnome-desktop-3.16.1.drv
  /nix/store/hlfjcjxfb3sm9kvp72lhd7k5k3a6kd30-nautilus-3.16.2.drv
  /nix/store/rfa2yxjzkcjx95fzxwsca19nhwd59vk6-file-roller-3.16.1.drv
  /nix/store/wd7d3cs5jq9sr4bq7rzi30pvr98iimng-baobab-3.16.1.drv
  /nix/store/zi4q72yjwc21gf48x1g26svd07y5hfii-gnome-screenshot-3.16.2.drv
  /nix/store/w12sfxzvja289rp9d78njk86q6nbvwxq-system-path.drv
  /nix/store/i16sp7g56lg7drdcza3h5pi6bmc8dbx7-dbus-conf.drv
  /nix/store/h80mazydw5zd4j0yzmwp6yn4da8760lz-unit-dbus.service.drv
  /nix/store/s4x1s2nfpc68pv6dkxp14njfgd5gqhy9-unit-polkit.service.drv
  /nix/store/ckmq3rs6c0j8slnjrwx2qw10jl9x6ydd-system-units.drv
  /nix/store/kn47zi83iysgrakq7hn50c3b15ks245y-udev-rules.drv
  /nix/store/nqz1khj77faxajlpkbmy62fhh6by3hjy-etc-profile.drv
  /nix/store/0i0xsv5il6dp5wg2zcph0kzd6pi8dh4y-etc.drv
  /nix/store/j4cwrk62vcnvjz775z6rj2z7sc7n16rd-nixos-system-bekki-16.03pre75174.d0e3cca.drv
```

This demonstrates what i am trying to show here:
libxkbcommon for example has a dependency on nixpkgs.xorg.xkeyboardconfig and needs to be rebuild. This is correct and expected as you described.
However, xorg.setxkbmap _also_ has a dependency on xkeyboardconfig in its postInstall phase:

```
  setxkbmap = attrs: attrs // {
    postInstall =
      ''
        mkdir -p $out/share
        ln -sfn ${xorg.xkeyboardconfig}/etc/X11 $out/share/X11
      '';
  };
```

setxkbmap however does not get rebuild because it is not referencing nixpkgs.xorg.xkeyboardconfig but a pre-override version of the xkeyboardconfig derivation which is exactly the problem I am experiencing.

You can easily try this out yourself. Just try to override xkeyboardconfig in any way inside your /etc/nixos/configuration.nix and try to trigger a setxkbmap rebuild. If you succeed in this, please show me how.

**Comment by vcunat** [comment]
Yeah, I don't see a good way how to avoid the fact that references within `xorg` are *directly* bound via a recursive attribute map (without modifying the nixpkgs tree). That will need to change. Perhaps the `haskellPackages` style is currently the best-developed style that we have.

And I also had in mind something like @dezgeg for the default "user interface", because people often want to do such overrides, and I don't remember ever seeing desire to have a different semantics.

**Comment by binarin** [comment]
BTW, I don't think that you actually want to override `xkeyboard_config` - it'll mean no binary cache for a lot of GUI packages. So custom `xkeyboard_config` needs to be supplied only to `xorgserver`, `xkbcomp` and `setxkbmap`. In the end you'll get 2 `xkeyboard_config` versions simultaneously, but in return custom layout and binary cache will be functional simultaneously.

And currently I'm doing it this way - https://gist.github.com/binarin/380eda7b08a1c230abbc186887fc5823

**Comment by grahamc** [comment]
Closing due to age, we can re-open :)

**Comment by ck3d** [comment]
I want to change the maximum number of input devices in xorg-server. All submodules needs to be recompiled, because it is an definition in misc.h, which is included by input plugins.
Currently the only way to make this possible is patching nixpkgs, which I really do not want to do.

I recommend to re-open this issue, to make this situation more visible.
