### ISSUE TITLE
Please update Mozilla TTS/STT

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#119496]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: tts

current version: 0.0.9
desired version: 0.0.11

###### Notify maintainers
@Mic92 @mweinelt 

maintainers:

###### Note for maintainers

mozilla fired the team and they founded a new company to continue their work

new releases can be found here

https://github.com/coqui-ai/TTS/releases/tag/v0.0.11
https://github.com/coqui-ai/STT

**Comment by mweinelt** [comment]
We are aware of the fork, we'll probably get to it before the branch-off.

**Comment by Mic92** [comment]
Same also not a STT user.

**Comment by davidak** [comment]
@rvolosatovs can you update deepspeech to the new repo, call it stt and deprecate deepspeech?

how to deprecate a package is documented here: https://github.com/NixOS/nixpkgs/pull/116475

please add a review. when anything is unclear, i would like to improve it

**Comment by mweinelt** [comment]
How about we call it `stt-bin` instead?

**Comment by davidak** [comment]
@mweinelt i don't think that is very helpful for the end-user. the package name should match the upstream project name

**Comment by davidak** [comment]
@mweinelt do you want to update tts again?

**Comment by MordragT** [comment]
Hello, just wanted to say that there has been a new release https://github.com/coqui-ai/TTS/releases/tag/v0.5.0 , in case someone wants to give it a shot.
