### ISSUE TITLE
DMD Marked Broken

### ISSUE THREAD

**Issue by JonathanILevi** [NixOS/nixpkgs#119548]
@SuperSandro2000 @ThomasMader @lionello

DMD, on Master and Unstable, is marked as broken (88513c0) because hydra was failing to build it.  What is causing this issue? I just successfully built is on my rig.

The commit to update DMD to 2.095.1 (7e05c58) was done since it was marked as broken but not remove it.

**Comment by dotlambda** [comment]
Might this be due to DMD requiring some CPU features? See `lib/systems/architectures.nix`.

**Comment by SuperSandro2000** [comment]
Can't reproduce. Builds locally fine.
