### ISSUE TITLE
pandoc: binary copied to /nix/store and to /bin

### ISSUE THREAD

**Issue by W1M0R** [NixOS/nixpkgs#119597]
**Describe the bug**
When installing pandoc into a nix-shell, two copies of the pandoc binary are stored: one in /nix/store and the other in /bin, thereby using double the disk space it would normally use. This becomes a bigger problem when trying to create Docker images (via dockerTools) that contain pandoc, because the image will now be double the size than it needs to be.

**To Reproduce**
1. nix-shell --pure -p pandoc --run "du -h /bin/pandoc"

This command will print 110M or more.

**Expected behavior**
Other nixpkgs create a symlink in /bin that points to the nix/store entry. I would expect /bin/pandoc to be a symlink, and not a copy of the binary.

**Screenshots**

The `dive` output after building an image using `pkgs.dockerTools`. Notice two pandoc entries of 165MB (in /bin and /nix/store):

![nixpkgs_pandoc_2](https://user-images.githubusercontent.com/618853/114989139-6e237580-9e97-11eb-8ed5-5f06523003ca.png)

**Additional context**

I am using pinned nixpkgs via niv when building my nix-shell and other derivations:

```
    "nixpkgs_unstable": {
        "branch": "nixpkgs-unstable",
        "description": "Nix Packages collection",
        "homepage": "",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "c0e881852006b132236cbf0301bd1939bb50867e",
        "sha256": "0fy7z7yxk5n7yslsvx5cyc6h21qwi4bhxf3awhirniszlbvaazy2",
        "type": "tarball",
        "url": "https://github.com/NixOS/nixpkgs/archive/c0e881852006b132236cbf0301bd1939bb50867e.tar.gz",
        "url_template": "https://github.com/<owner>/<repo>/archive/<rev>.tar.gz"
    }
```

**Notify maintainers**

@peti @jtojnar @Profpatsch Can anyone confirm whether they are also seeing this and whether it is expected or not?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-31-generic, Ubuntu, 20.04 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(vagrant): `"nixpkgs-21.05pre280420.bc0144e5c9b"`
 - nixpkgs: `/home/vagrant/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
**Possibly related**

1. https://github.com/NixOS/nixpkgs/issues/94636
1. https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/pkgs/development/tools/pandoc/default.nix

**Comment by Profpatsch** [comment]
Can you also see `/bin/pandoc` when not in a nix-shell?

**Comment by Profpatsch** [comment]
Nix does not create things is `/bin` usually.

**Comment by W1M0R** [comment]
Thanks for the reply @Profpatsch. I did have a /bin/pandoc, which I then manually removed. 

With a nix-shell:
![nix 1](https://user-images.githubusercontent.com/618853/115014265-64f3d200-9eb2-11eb-9b98-f7d951cb7737.png)

Without a nix-shell:
![nix 2](https://user-images.githubusercontent.com/618853/115014267-6624ff00-9eb2-11eb-87aa-631300200d7d.png)

With a pure nix-shell:
![nix 3](https://user-images.githubusercontent.com/618853/115014271-66bd9580-9eb2-11eb-9f84-bf36bd838a82.png)

I will close this issue, because it looks like it is not related to the pandoc derivation, but more likely with `dockerTools.buildImage` (#94636 ).

**Comment by Profpatsch** [comment]
Hm, I see. Yes, it looks like you had it installed globally (was this inside of a docker image?) by another means.

**Comment by W1M0R** [comment]
No, the nix operations were not executed as part of a docker image, they were executed on a typical setup outside Docker. However, nix was used to create a docker image (via the nix `dockerTools`), and the resulting image contains the duplicate copies of `pandoc`, as seen by the `dive` screenshot in my first message. [This comment](https://github.com/NixOS/nixpkgs/issues/94636#issuecomment-755246646) mentions the following behaviour of `dockerTools.buildImage`:

> The `contents` parameter is hugely misleading and should be renamed to something like copyToRoot.

Initially I thought that the duplicate pandoc occurred even when installing it in a nix-shell, due to the fact that my environment had a /bin/pandoc that came from somewhere else. However, that was a red herring.

**Comment by Profpatsch** [comment]
Ah, yes, then the docker build code must duplicate it instead of symlinking; But it could also be hardlinking so that needs to be inspected.
