### ISSUE TITLE
yubioath-desktop: No module 'ykman.descriptor'

### ISSUE THREAD

**Issue by antifuchs** [NixOS/nixpkgs#119552]
**Describe the bug**

On current nixos-unstable, yubioath-desktop starts up, but does not detect a connected yubikey and spews error messages to the terminal.

I believe this is related to https://github.com/Yubico/yubioath-desktop/issues/693 and might be fixable by updating the package.

**To Reproduce**
1. Connect a yubikey (4 nano); set `services.pcscd.enable = true;` and rebuild (optional, I believe)
1. `nix-shell -p yubioath-desktop`
2. `$ yubioath-desktop`

**Expected behavior**

Would expect the key to be discovered and silence on the terminal.

**Screenshots**

```
$ yubioath-desktop
Got library name:  "/nix/store/00avfy0caylrsxil0ss1zc7gm89s31gd-pyotherside-1.5.9/lib/qt-5.15.2/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey
.py\", line 12, in <module>\n    from ykman.descriptor import (\n\nModuleNotFoundError: No module named 'ykman.descriptor'\n"
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 12, in <module>
    from ykman.descriptor import (

ModuleNotFoundError: No module named 'ykman.descriptor'
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError:
name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError:
name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
```

**Additional context**
(none)

**Notify maintainers**
@Mic92 @rissson 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05.20210409.842f900 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - nixpkgs: `/nix/store/d7bsnyyw1wbmkv197krfd0fbaw1rqcpv-source

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: yubioath-desktop
# a list of nixos modules affected by the problem
module:
```

**Comment by rissson** [comment]
Version 5.0.5 seems to include the fix and will probably be released soon. I'll update the package once it has made it to their release website.

**Comment by antifuchs** [comment]
Thank you! I could work around the issue by using:

``` nix
    (yubioath-desktop.overrideAttrs (old: rec {
      version = "5.0.5";
      src = pkgs.fetchurl {
        url = "https://github.com/Yubico/yubioath-desktop/archive/refs/tags/yubioath-desktop-${version}.tar.gz";
        sha256 = "sha256-Eu0igmXhhgPFac8TZq8Lzx9uopoxT2SWS4/ijEywOYY=";
      };
      patches = [ ];
    }))
```

for now (this may break some of the things fixed in patches)

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/118725#issuecomment-817241830

**Comment by Mic92** [comment]
Looks like 5.0.5 is released: https://github.com/Yubico/yubioath-desktop/pull/701

**Comment by rissson** [comment]
@Mic92 tarballs haven't been published yet.
