### ISSUE TITLE
nixos.tests.hibernate.x86_64-linux times out

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#119567]
**Describe the bug**

`nix-build nixos/release-combined.nix -A nixos.tests.hibernate.x86_64-linux` hangs forever and eventually times out

**To Reproduce**
1. nix-build nixos/release-combined.nix -A nixos.tests.hibernate.x86_64-linux

**Expected behavior**

The test passes.

**Comment by enderger** [comment]
Hey, shouldn’t this be blocking the NixOS unstable channel? It’s currently blocking Nixpkgs, but not NixOS.

**Comment by lukegb** [comment]
This seems flaky, rather than just broken 100% of the time, so I'm actually just going to drop the channel blocker tag.

**Comment by vcunat** [comment]
Should be fixed by PR #120286.
