### ISSUE TITLE
tuxedo-keyboard: 2019-08-26 -> v3.0.4 

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#119658]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: tuxedo-keyboard

current version: 2019-08-26
desired version: v3.0.4 

###### Notify maintainers

maintainers: @blanky0230 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by d4g** [comment]
Also the license seems to have changed. The package states GPL2 the repository says  GPL-3.0 License.

**Comment by blanky0230** [comment]
@d4g  Since opening this Issue they seemed to have released v3.0.5, we've updated to that version :)
