### ISSUE TITLE
tuxedo-control-center

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#119659]
**Project description**
_The TUXEDO Control Center (short: TCC) gives TUXEDO laptop users full control over their hardware like CPU cores, fan speed and more. This is also true for many schenker or XMG laptops. _

**Metadata**

* homepage URL: https://www.tuxedocomputers.com/en/TUXEDO-Control-Center.tuxedo#
* source URL: https://github.com/tuxedocomputers/tuxedo-control-center
* license: GPL-3.0 License 
* platforms: linux

**Comment by d4g** [comment]
Depends on #119658
@blanky0230 is this also relevant for you?

**Comment by blanky0230** [comment]
I don't know really but I might as well have a look :)

**Comment by d4g** [comment]
@blanky0230 : still looking into it? ;)

**Comment by blanky0230** [comment]
@d4g Not me, but @blitz and others are doing good work over at: https://github.com/NixOS/nixpkgs/pull/135841
