### ISSUE TITLE
llvmPackages_12.llvm fails to build on wendy

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#119673]
**Describe the bug**
wendy, one of the big-parallel build hosts used by hydra.nixos.org, cannot successfully build llvmPackages_12.llvm. This blocks advancing nixos-unstable.

**To Reproduce**
1. Use wendy to build llvmPackages_12.llvm. Observe [surprising sadness](https://hydra.nixos.org/build/141548680) :(

or, more realistically:

1. Take the attached CMOV16rm-uops.yaml, and run `llvm-exegesis -mcpu=bdver2 -mode=analysis -benchmarks-file=../../CMOV16rm-uops.yaml -analysis-clusters-output-file=- -analysis-clustering-epsilon=0.1 -analysis-inconsistency-epsilon=0.1 -analysis-numpoints=1 -analysis-clustering=naive`

(a reduced commandline that produces the same assertion failure is `llvm-exegesis -mode=analysis -benchmarks-file=../../CMOV16rm-uops.yaml -analysis-clusters-output-file=- -analysis-numpoints=1`)

**Expected behavior**

**Additional context**

The assertion that's tripped by this YAML file is:

```
llvm-exegesis: /home/lukegb/debugit/llvm-project/llvm/include/llvm/MC/MCSchedule.h:348: const llvm::MCSchedClassDesc* llvm::MCSchedModel::getSchedClassDesc(unsigned int) const: Assertion `hasInstrSchedModel() && "No scheduling machine model"' failed.
```

**Notify maintainers**

@lovek323 @7c6f434c @dtzWill @primeos 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: llvmPackages_12.llvm
# a list of nixos modules affected by the problem
module:
```

**Comment by lukegb** [comment]
https://p.lukegb.com/IdeallyDashingPelican.yaml is the CMOV16rm-uops.yaml (can't upload it here because it's not a supported GitHub filetype, apparently).

To be more precise, the test that is failing is this one: https://github.com/llvm/llvm-project/blob/main/llvm/test/tools/llvm-exegesis/X86/uops-CMOV16rm-noreg.s

**Comment by lukegb** [comment]
This has primarily become apparent because the configuration was changed in NixOS/nixos-org-configurations#146 to make wendy only build big-parallel jobs. Since llvm is big-parallel, this means that wendy will now usually get selected for building llvm, since the load is otherwise pretty low. Previous successful builds of llvmPackages_12.llvm have been using one of the packet builders instead, which are using a newer CPU for which LLVM has a scheduling machine model.

**Comment by lukegb** [comment]
FWIW, this probably affects other LLVM versions as well, but they have current versions in the cache. If wendy rebuilds the other packages (e.g. stdenv bump or something), they'll likely start failing as well.

**Comment by lukegb** [comment]
### Replication notes

If you spin up a VM using the CPU profile that at least virt-manager calls "Opteron_G1", then you can reproduce this using the LLVM tests. That's not quite the same as the CPU reported on wendy (Opteron_G1: k8-sse3; wendy: amdfam10), but it exhibits the same problem.

**Comment by vcunat** [comment]
I don't know why, but wendy [shows](https://hydra.nixos.org/queue-runner-status) as disabled now.

**Comment by vcunat** [comment]
@oconnorr: it's probably late for you (I hope I didn't confuse names), but you [encountered](https://logs.nix.samueldr.com/nixos/2020-11-15#4240569;) this issue some time ago.

**Comment by vcunat** [comment]
@roconnor: ⬆️  uh, same full name but this GitHub name is in `lib.maintainers`.

**Comment by lukegb** [comment]
Filed https://bugs.llvm.org/show_bug.cgi?id=50013 upstream for this.
