### ISSUE TITLE
n8n: fails to start on aarch64

### ISSUE THREAD

**Issue by purcell** [NixOS/nixpkgs#119687]
**Describe the bug**

Wanted to try out n8n on a Raspberry Pi 4 running latest nixos-unstable, so I enabled it with no specific startup configuration, and it exits with the following error:

```
Apr 17 17:34:28 media n8n[447342]: #
Apr 17 17:34:28 media n8n[447342]: # Fatal error in , line 0
Apr 17 17:34:28 media n8n[447342]: # Check failed: reservation_.SetPermissions(protect_start, protect_size, permission).
Apr 17 17:34:28 media n8n[447342]: #
Apr 17 17:34:28 media n8n[447342]: #
Apr 17 17:34:28 media n8n[447342]: #
Apr 17 17:34:28 media n8n[447342]: #FailureMessage Object: 0x7fc9955fd8
Apr 17 17:34:28 media n8n[447342]:  1: 0x9f42d8  [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]:  2: 0x1469b34 V8_Fatal(char const*, ...) [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]:  3: 0xd03d04  [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]:  4: 0xd26cd0 v8::internal::PagedSpace::SetReadAndExecutable() [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]:  5: 0xc55664 v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*) [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14>
Apr 17 17:34:28 media n8n[447342]:  6: 0x105997c  [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]:  7: 0xb2bf3c v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]:  8: 0x9c6e84 node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::__cxx11::basic_string<char, >
Apr 17 17:34:28 media n8n[447342]:  9: 0x955088 node::Start(int, char**) [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media n8n[447342]: 10: 0x7fa2ab97f0 __libc_start_main [/nix/store/al61kv9rp0rriqdfczyby59an2ax7xyz-glibc-2.32-40/lib/libc.so.6]
Apr 17 17:34:28 media n8n[447342]: 11: 0x8ebe78 _start [/nix/store/way40gr84vrk7plfm1kq9zabdjmc0jnm-nodejs-14.16.1/bin/node]
Apr 17 17:34:28 media systemd[1]: n8n.service: Main process exited, code=dumped, status=5/TRAP
```

I don't see any corresponding issues in github.

**To Reproduce**
1. aarch64 machine, nixos-unstable
2. `services.n8n.enable = true`
3. `nixos-rebuild switch`
4. `journalctl -u n8n`

**Expected behavior**

Successful startup and accessible by web interface.

**Screenshots**

**Notify maintainers**

@freezeboy, @arjunv27 

**Metadata**

 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.79, NixOS, 21.05pre282432.311ceed827f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre282432.311ceed827f"`
 - channels(steve): `""`
 - channels(nixos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - n8n
# a list of nixos modules affected by the problem
module:
 - n8n
```

**Comment by freezeboy** [comment]
Hi, I just tried the binary on my machine from master, looks ok, but it is not an aarch64.
I will look into it, but I won't be able to verify the behavior on this arch

**Comment by freezeboy** [comment]
@purcell Can you please check if a basic call to `node` or `npm` on the raspberry is also crashing ?

**Comment by ulrikstrid** [comment]
I can second that enabling the n8n service on raspberry pi 4 fails.

It seems to fail for me on other machines as well but with a slightly different error message. I don't have the errors at hand but can try to post when I have my computer.

**Comment by freezeboy** [comment]
In fact I run the `nixosTests.n8n` locally and it also fails inside virtualization, with an error that looks similar too :/
I'm not sure what counter measures we can take, I also tried to update the software but the behavior is the same

**Comment by ulrikstrid** [comment]
On my non-arm machine I recall that it looks like a permission error when starting node.
I can run node fine when just running it plain.

**Comment by ulrikstrid** [comment]
A guess is that [this folder](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/n8n.nix#L45) is owned by the wrong user.

**Comment by freezeboy** [comment]
I tried the n8n derivation from unstable on my 20.09 system and it looks good, even as a service. This module has some hardening features enabled in the systemd unit file. Maybe the systemd update from 20.09 -> unstable could explain the change? I don't have a running system with unstable kernel/systemd

**Comment by freezeboy** [comment]
> A guess is that [this folder](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/n8n.nix#L45) is owned by the wrong user.

But this folder is generated by systemd on startup

**Comment by purcell** [comment]
> A guess is that [this folder](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/n8n.nix#L45) is owned by the wrong user.

It's owned by `root`. Does that count as the wrong user?

**Comment by purcell** [comment]
Actually, only the symlink is owned by root. Here are the corresponding directories:
```
steve@media> ls -la /var/lib/n8n
lrwxrwxrwx 1 root root 11 Apr 17 17:34 /var/lib/n8n -> private/n8n
steve@media> sudo ls -lad /var/lib/private/n8n
drwxr-xr-x 2 64383 64383 4096 Apr 17 17:34 /var/lib/private/n8n
```
So it looks like `/var/lib/private/n8n` is assigned to the `DynamicUser` created by `systemd`.

But in any case, it looks like the error is related to https://github.com/nodejs/node/issues/37061, supposedly fixed in Node 15.9.0

**Comment by purcell** [comment]
Scratch that, I think the error message for that issue is a bit different. There's talk [here](https://help.dreamhost.com/hc/en-us/articles/360029083351-Installing-a-custom-version-of-NVM-and-Node-js) of fixing this specific error via the attributes of the node executable, e.g. `setfattr -n user.pax.flags -v "mr" $(find $NVM_DIR -type f -iname "node" -o -iname "npm" -o -iname "npx")`.

**Comment by freezeboy** [comment]
> Scratch that, I think the error message for that issue is a bit different. There's talk [here](https://help.dreamhost.com/hc/en-us/articles/360029083351-Installing-a-custom-version-of-NVM-and-Node-js) of fixing this specific error via the attributes of the node executable, e.g. `setfattr -n user.pax.flags -v "mr" $(find $NVM_DIR -type f -iname "node" -o -iname "npm" -o -iname "npx")`.

I am not sure is matches the nix store requirements

**Comment by purcell** [comment]
Yeah, that's definitely not a fix, just noting related info I found.

**Comment by purcell** [comment]
I'll take the liberty of CC-ing the nodejs package maintainers here in case the issue is obvious to them: @goibhniu @gilligan (hi!) @cko @marsam

**Comment by baloo** [comment]
pretty sure it's because of the:
```
MemoryDenyWriteExecute = "yes"
```

in systemd' service configuration. This is incompatible with nodejs afaik, because its JIT relies on the fact it can rewrite the program's code dynamically.

**Comment by purcell** [comment]
> This is incompatible with nodejs afaik, because its JIT relies on the fact it can rewrite the program's code dynamically.

Indeed! I see mentions of this elsewhere, e.g. [here](https://lists.archlinux.org/pipermail/arch-commits/2021-July/1026311.html) and [here](https://github.com/netdata/netdata/issues/773). I'll send a PR.
