### ISSUE TITLE
pulseaudio: Failed to open module module-x11-publish.so: module-x11-publish.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by javins** [NixOS/nixpkgs#11970]
I'm running nixos on channel nixos-unstable with gnome3 as my desktopManager and gdm as my login manager.

Here are the relevant bits of /etc/nixos/configuration.nix:

``` nix
{
  services.xserver = {
    enable = true;
    displayManager.gdm = { 
      enable = true;
      autoLogin.user = "walt";
      autoLogin.enable = false;
    };  
    desktopManager.gnome3.enable = true;
  };
}
```

Using gnome3 enables pulseaudio because of:

https://github.com/NixOS/nixpkgs/blob/db1086f3a17dc73232a11c408ca1c43cdf785dc6/nixos/modules/services/x11/desktop-managers/gnome3.nix#L97

Every time boot/login I see the following errors in systemd's journal:

```
Dec 27 03:33:21 nix pulseaudio[1010]: Failed to open module module-x11-publish.so: module-x11-publish.so: cannot open shared object file: No such file or directory
Dec 27 03:33:21 nix pulseaudio[1010]: Failed to open module "module-x11-publish".
```

Furthermore, if I log out and then back in (without rebooting the entire machine), I will see errors like the following in the journal:

```
Dec 27 03:34:34 nix pulseaudio[1561]: Daemon already running.
Dec 27 03:34:34 nix pulseaudio[1010]: Failed to open module module-x11-publish.so: module-x11-publish.so: cannot open shared object file: No such file or directory
Dec 27 03:34:34 nix pulseaudio[1010]: Failed to open module "module-x11-publish".
Dec 27 03:34:34 nix pulseaudio[1010]: Module "module-device-manager" should be loaded once at most. Refusing to load.
```

You can find these errors with a command like: `sudo journalctl -b -p err | grep pulse`

I have't observed any issues with sound, but I'm suspicious that pulseaudio isn't interacting properly with my x session.

**Comment by javins** [comment]
There is some in depth discussion of a similar problem that is good for framing the issue/context here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593746

I don't believe the debian discussion addresses the exact issue under NixOS, but reading through it helped me understand the landscape surrounding these error messages.

**Comment by jgillich** [comment]
I'm also getting these, but also no sound issues so I didn't investigate.

**Comment by vcunat** [comment]
Me too: these errors and no sound issues.

**Comment by jagajaga** [comment]
+1 I have errors and no sound.

**Comment by jagajaga** [comment]
In `pavucontrol` I can see no devices.

**Comment by Profpatsch** [comment]
Same error here, Sound suddenly stopped working; after some baffled searching and profile switching I found out that my pulse device had been muted somehow. oO

**Comment by CMCDragonkai** [comment]
I got it as well running SDDM and KDE4. But sound does work.

**Comment by zimbatm** [comment]
Got this issue and now my default sink is auto_null, although it might be unrelated.

**Comment by Profpatsch** [comment]
@zimbatm Pulse seems to break a lot when it is updated, so it’s probably an unrelated transient error.

**Comment by Profpatsch** [comment]
Hm, I’m getting this again, and also the streaming seems to break sometimes. But not sure if related?

**Comment by volth** [comment]
Reproducible with current master.

**Comment by stefano-m** [comment]
FWIF, on NixOS 18.03, one has to configure the `pulseaudioFull` package since the default `pulseaudioLight` does not ship with `module-x11-publish.so`.

It's debatable whether that module should be included in `pulseaudioLight`.

#### Working NixOS configuration
```nix
hardware.pulseaudio = {
    enable = true;

    # pulseaudioLight does *not* have module-x11-publish.so
    package = pkgs.pulseaudioFull;
}
```

#### System Info

`nix-info -m`
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.41, NixOS, 18.03.132405.ee80654b526 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.2`
 - channels(user): `"nixpkgs-18.03.132448.33682d9af4c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
