### ISSUE TITLE
Core dump at login when using `services.xserver.extraLayouts`

### ISSUE THREAD

**Issue by attila-lendvai** [NixOS/nixpkgs#119811]
unable to log in after adding my `services.xserver.extraLayouts` customization.

most probably because of this:

```
Apr 18 17:20:34 lelap gnome-shell[3426]: syntax error: line 1 of stdin
Apr 18 17:20:34 lelap gnome-shell[3426]: Errors encountered in stdin; not compiled.
Apr 18 17:20:34 lelap gnome-shell[3428]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Apr 18 17:20:34 lelap gnome-shell[3428]: > Warning:          Unsupported high keycode 372 for name <I372> ignored
Apr 18 17:20:34 lelap gnome-shell[3428]: >                   X11 cannot support keycodes above 255.
Apr 18 17:20:34 lelap gnome-shell[3428]: >                   This warning only shows for the first high keycode.
Apr 18 17:20:34 lelap gnome-shell[3428]: > Error:            Can't find file "hu_attila" for symbols include
Apr 18 17:20:34 lelap gnome-shell[3428]: >                   Exiting
Apr 18 17:20:34 lelap gnome-shell[3428]: >                   Abandoning symbols file "default"
Apr 18 17:20:34 lelap gnome-shell[3428]: Errors from xkbcomp are not fatal to the X server
Apr 18 17:20:34 lelap kernel: .gkbd-keyboard-[3423]: segfault at 40 ip 00007f7921c787fa sp 00007ffc72ea0f70 error 4 in libgnomekbdui.so.8.0.0[7f7921c70000+a000]
Apr 18 17:20:34 lelap kernel: Code: 41 55 49 89 fd 41 54 41 89 f4 55 48 89 cd 53 48 89 d3 48 83 ec 08 e8 95 89 ff ff 4c 89 ef 48 89 c6 e8 0a 86 ff ff 48 8b 40 28 <48> 8b 50 40 0f b7 42 0a 0f b7 4a 08 41 0f af c4 99 f7 f9 89 45 00
Apr 18 17:20:34 lelap systemd[1]: Started Process Core Dump (PID 3429/UID 0).
Apr 18 17:20:35 lelap systemd-coredump[3430]: Process 3423 (.gkbd-keyboard-) of user 1000 dumped core.
Apr 18 17:20:35 lelap systemd[1]: systemd-coredump@1-3429-0.service: Succeeded.
```

**To Reproduce**

1. add this to your config:

```
  services.xserver.extraLayouts.hu_attila = {
    description = "Attila's modified hu layout";
    languages   = [ "hun" ];
    symbolsFile = ./xkb/hu_attila;
  };
```

2. `nixos-rebuild switch` then reboot
3. after successful identification, the login screen blinks and comes back

it kinda works, because once i could select my keymap from the list, but switching to it crashed the GUI.

the `hu_attila` file contains the following (it's untested):
```
hidden partial alphanumeric_keys
xkb_symbols "attila" {
    // map 'insert' to 'iacute'
    // key <INS>   { [       iacute,       Iacute,              less,         greater ] };

    // ü
    key <AB11>  { [        minus,   underscore,          asterisk                  ] };
    key <AB10>  { [   udiaeresis,   Udiaeresis,         diaeresis                  ] };

    // switch 0 and ö
    key <AE10>  { [            0,      section,           notsign                  ] };
    key <TLDE>  { [   odiaeresis,   Odiaeresis,  dead_doubleacute,     doubleacute ] };
};

hidden partial modifier_keys
xkb_symbols "ralt_switch_attila" {
  key <PRSC> {
    type[Group1]="ONE_LEVEL",
    symbols[Group1] = [ ISO_Level3_Shift ]
  };
  include "level3(modifier_mapping)"
};

default partial
xkb_symbols "hu_attila" {
    name[Group1] = "Attila's Hungarian";
    include "latin"
    include "hu(def_102)"
    include "hu(def_qwerty)"
    include "kpdl(comma)"
    include "hu(def_dead)"
    include "hu(def_common)"
    //include "level3(ralt_switch)"
    include "ralt_switch_attila"
    include "attila"
    // include "hu_attila(ralt_switch_attila)"
    // include "hu_attila(attila)"
};
```

i cannot test it, because `xkbcomp` doesn't produce any output: `xkbcomp -R"$(nix-build --no-out-link '<nixpkgs>' -A xorg.xkeyboardconfig)/etc/X11/xkb/" /etc/nixos/xkb/hu_attila /tmp/x` and the file is empty. i don't know how else to test it besides firing an entire `nixos-rebuild`.

it processes the input (`strace` shows), and it does error if i edit issues into the input, yet, it doesn't even create the output file, and returns with exit code 1.

**Expected behavior**
i can log in and my custom keymap is available.

**Notify maintainers**
@rnhmjoj i'm a seasoned developer. if you can help me with the nix part to reproduce the crash in the command line, then i can try to debug the issue. but i lack the required C and Linux debugging fu to debug complex systems like gnome.

@rnhmjoj does your nix code call `xkbcomp` at build-time? maybe something later crashes because of a missing or empty file? maybe you assert for that in the build?

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.13, NixOS, 20.09.3834.c7e905b6a97 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3834.c7e905b6a97"`
 - channels(alendvai): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: services.xserver.extraLayouts
# a list of nixos modules affected by the problem
module: services.xserver
```

**Comment by rnhmjoj** [comment]
If you still experimenting with your layout it may be useful to test it without rebuilding xkb.
It wouldn't surprise me if an invalid layout could crash programs: they're not meant to be edited by users, so there are probably few sanity checks. 

To test the layout on the fly, try something like this:
1. `mkdir -p ~/xkb/symbols`
2. `cp /path/to/hu_attila ~/xkb/symbols/`
3. `setxkbmap -I$HOME/xkb hu_attila -print | xkbcomp -I$HOME/xkb - $DISPLAY`

This should compile the layout and set it as the current one.
It will also print useful warnings and errors.

**Comment by attila-lendvai** [comment]
thank you!

FTR, if i save the file as `/etc/nixos/xkb/symbols/hu_attila`, then i can do the following to test it from the terminal:

```
setxkbmap -I/etc/nixos/xkb hu_attila -print | xkbcomp -I/etc/nixos/xkb - $DISPLAY
```

**and** at the same time i can also add this to my nixos config to use it:

```
  services.xserver.extraLayouts.hu_attila = {
    description = "Attila's modified hu layout";
    languages   = [ "hun" ];
    symbolsFile = ./xkb/symbols/hu_attila;
  };
```

but back to the original issue: if it's easy to add, then it would be nice if the xkb config could be compiled and the output sanity checked at build time. and/or add this hint to the documentation about how to test your config manually. it would have spared me a long compile, and being locked out from the GUI login.

but feel free to close this bug if it's not feasible.

**Comment by rnhmjoj** [comment]
Yes, possibly. The command needs a running X server, though: we need to start a headless one, like Xvfb, set the DISPLAY and run xkbcomp. A good idea, and easier to implement, is to mention that command in the manual for testing.

I don't have time to work on this now, but if you make a PR I'll review it.

**Comment by attila-lendvai** [comment]
@rnhmjoj ok, here's the manual PR: https://github.com/NixOS/nixpkgs/pull/119952

re command to test: i think it would already go a long way to simply test if the xkbcomp's output file is present and not empty.
