### ISSUE TITLE
Screen sharing in Firefox with Wayland Gnome

### ISSUE THREAD

**Issue by tad-lispy** [NixOS/nixpkgs#119810]
**Describe the bug**

A couple of days ago screen sharing stopped working. I primarily use it with JitSi in Firefox and it used to work just fine.

**To Reproduce**

1. Using Gnome with Wayland start Firefox (from a terminal to see error message below)
2. Navigate to a website with screen sharing, e.g. <https://meet.jit.si/screen-sharing-test>
3. Try sharing the screen

**Expected behavior**
After selecting the screen it will be shared with the web application.

**Screenshots**
https://user-images.githubusercontent.com/1684495/115152378-222c2880-a071-11eb-9fae-7d2664a69c0c.mp4

**Additional context**

The `firefox-wayland` package is installed using Home Manager from `nixpkgs`. Current (affected) version is 87.0.

In the terminal where I ran Firefox I see an error: 

```
[E][000000378.275192][context.c:224 pw_context_new()] context 0x7fb26b509400: can't load config client.conf: No such file or directory 
```

It works if I downgrade to Firefox 85.0.1, for example like this:

```
$ nix-shell \
  -p firefox-wayland \
  -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/bed08131cd29a85f19716d9351940bdc34834492.tar.gz
...
[nix-shell:~]$ firefox --version
Mozilla Firefox 85.0.1

[nix-shell:~]$ firefox
...
```

**Notify maintainers**
@edolstra 
@lovesegfault
@mweinelt

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.11, NixOS, 20.09.3793.cce26cd83d2 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210317_8a5203d`
 - channels(root): `"nixos-20.09.3824.dec334fa196"`
 - channels(tad): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/tad/.nix-defexpr/channels/nixpkgs`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mweinelt** [comment]
Can only test this on sway on nixos-unstable, works on Firefox 87.0 for me. Your Firefox version is quite dated. Also the issue could be in the xdg-desktop-portal. What is your config with regard to that?

**Comment by tad-lispy** [comment]
Thanks for getting back to me. I am on version 87.0 too. That's the one with the issue. In version 85.0.1 it works for me. Sorry, it wasn't clear in my original message. I edited it.

Previously I didn't have any XDG Portal specific configuration and it was working. After the problem began I tried setting up xdg portal as described in <https://nixos.wiki/wiki/Firefox> and now I have the following lines in my `/etc/nixos/configuration.nix`:

```nix
{ config, pkgs, ... }:

{ 
# ...

  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.displayManager.gdm.wayland = true;
  services.xserver.displayManager.gdm.enable = true;

  ## This is from https://nixos.wiki/wiki/Firefox
  ## Trying to get https://discourse.nixos.org/t/screen-sharing-with-wayland-gnome/12449
  ## Makes Gnome Shell startup very slow (> 60s) and doesn't fix the sharing problem
  # xdg = {
  #   portal = {
  #     enable = true;
  #     extraPortals = with pkgs; [
  #       xdg-desktop-portal-wlr
  #       xdg-desktop-portal-gtk
  #     ];
  #     gtkUsePortal = true;
  #   };
  # };

# ...
}
```

As you see I've tried to explicitly setup XDG portal (the commented out lines) but it didn't help.

Here are relevant parts of `~/.config/nixpkgs/home.nix`:

``` nix
{ config, pkgs, ... }:

{ 
# ...

  systemd.user.sessionVariables = {
    # firefox screencapture
    MOZ_ENABLE_WAYLAND="1";
    MOZ_USE_XINPUT2="1";

    # SDL
    SDL_VIDEODRIVER="wayland";

    # QT
    QT_QPA_PLATFORM="wayland";
  };

  programs.firefox = {
    enable = true;
    package = pkgs.wrapfirefox pkgs.firefox-unwrapped {
      forcewayland = true;
      extrapolicies = {
        extensionsettings = {};
      };
    };
  };
  ## Previously was:
  # programs.firefox.enable = true;

# ...
}

**Comment by mweinelt** [comment]
Sorry, no idea why it would not work on GNOME.

**Comment by tad-lispy** [comment]
I got the screen sharing to work by installing Firefox globally (i.e. via `/etc/nixos/configuration.nix` and not Home Manager). More details here: <https://discourse.nixos.org/t/screen-sharing-with-wayland-gnome/12449/8>.
