### ISSUE TITLE
Upgrading to Linux Kernel 5.10 destroys performance

### ISSUE THREAD

**Issue by HexF** [NixOS/nixpkgs#119842]
**Describe the bug**

System performance is hurt when kernel 5.10 is used.

**To Reproduce**
1. Run some sort of performance benchmark (in my case, I launched Minecraft and loaded a world, and observed the average fps while running around)
2. Switch to kernel 5.10 and reboot.
3. Run this test again, and observe the average FPS drop (in my case from 60fps capped to ~10fps)

**Expected behavior**

Performance should remain consistent between the 2 kernel versions.

**Additional context**

Minecraft probably isn't the best data-driven test, I'd be happy to try other test between the versions.

I ran a whole bunch of `git bisect` and found that 285301cd1f3ec4521be8a9b816a99a095c34715c caused performance issues.

**Notify maintainers**

@mweinelt 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05.20210331.efd9121 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201205_a5d85d0`
 - channels(thobson): `"home-manager, nixpkgs-21.05pre273941.a2b0ea6865b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by HexF** [comment]
From discussion in the discord, I ran `cat /proc/cpuinfo | grep MHz` on both 5.4 and 5.10:
* 5.4, under load gave roughly 4GHz
* 5.10, under load gave 700MHz

**Comment by HexF** [comment]
More discussion has resulted in a fix, of adding `boot.kernelParams = [ "intel_pstate=active" ];` to my configuration.nix

**Comment by HexF** [comment]
Seems to have something to do with `intel_pstate` defaulting to passive mode on kernel 5.8+

see https://www.reddit.com/r/linux/comments/ihdozd/linux_kernel_58_defaults_to_passive_mode_for/

**Comment by lukegb** [comment]
I _think_ this might be a dupe of #119746?

**Comment by HexF** [comment]
Seems to be
