### ISSUE TITLE
Conda is out of date

### ISSUE THREAD

**Issue by mausch** [NixOS/nixpkgs#119832]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: conda

current version: 4.6.14
desired version: 4.9.2

###### Notify maintainers

maintainers: @jluttine @bhipple 

The current version in nixpkgs 4.6.14 is about 2 years old and has many issues that have been fixed since.

Tried upgrading it in https://github.com/mausch/nixpkgs/commit/e1a43684368c3fc4314e0834e4326fd9dfd5af38 .

However when I run `conda-install` I get:
`/home/mauricio/.conda/conda.exe: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`

As you can see I tried adding zlib to the list of dependencies but still getting the same error.

Workaround: Use the current version and upgrade conda with conda itself: `conda install conda=4.9.2`

###### Note for maintainers

Please tag this issue in your PR.

**Comment by bhipple** [comment]
In general it's pretty out of date because I've found the normal nix packages have much better coverage than they did a few years ago, so I haven't used conda much.  This is particularly true with all of @tbenst's hard work over in https://github.com/nix-community/nix-data-science.

**Comment by hhoeflin** [comment]
Filed PR #170122. @mausch, if you are still interested, would be great if you could have a look that this works for you as well. Thanks

**Comment by bhipple** [comment]
```
conda-shell-chrootenv:bhipple@brh-x1cg6:~/src/nixpkgs$ conda-install
PREFIX=/home/bhipple/.conda
installing: python-3.7.3-h0371630_0 ...
Python 3.7.3
installing: ca-certificates-2019.1.23-0 ...
...
installation finished.
conda-shell-chrootenv:bhipple@brh-x1cg6:~/src/nixpkgs$ 
```
Thanks @hhoeflin for the fix, it seems to be working now!

**Comment by hhoeflin** [comment]
@bhipple Just to make sure - could you please check that you actually have the right version installed now? 

You had:
```
conda-shell-chrootenv:bhipple@brh-x1cg6:~/src/nixpkgs$ conda-install
PREFIX=/home/bhipple/.conda
installing: python-3.7.3-h0371630_0 ...
Python 3.7.3
installing: ca-certificates-2019.1.23-0 ...
...
installation finished.

```

However, conda 4.11.0 should install a version 3.9.7 of python.
