### ISSUE TITLE
postgresql_12: python support missing

### ISSUE THREAD

**Issue by W1M0R** [NixOS/nixpkgs#119931]
**Describe the bug**
Postgres already exists as a nix package (https://github.com/NixOS/nixpkgs/blob/39cce06a6bd8fb70a5bf5d64d2aaea954dab44b8/pkgs/servers/sql/postgresql/default.nix#L56) bundled with some packages (https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sql/postgresql/packages.nix). 

Postgres itself has built-in support for Python, but it needs to be enabled during the build process (https://github.com/postgres/postgres/blob/7136bf34f28892362144ae2e350714836a5c0c0c/configure#L1558) via the `--with-python` configure flag.

The current implementation of postgres in nix does not enable python support, and it also doesn't seem to perform any detection whether python support should be offered. There is already some form of conditional feature support (for example via the `icuEnabled` attribute. It could be possible to add a `pythonEnabled` attribute that enables python. My knowledge of nix is clearly lacking in this regard, but I hope the idea makes sense. 

**To Reproduce**
1. Install `postgresql_12` via `nix-shell` then use `pg_ctl` to initialize and start a server instance
2. Use psql to enter the postgres instance
3. Execute 'create extension plpython3u;'

![plpython3u](https://user-images.githubusercontent.com/618853/115369555-86adcb80-a1c8-11eb-8229-817c9a142667.png)

**Expected behavior**
The ability to enable the plpython3u extension.

**Screenshots**

This is a screenshot of the current configureFlags of postgres (https://github.com/NixOS/nixpkgs/blob/39cce06a6bd8fb70a5bf5d64d2aaea954dab44b8/pkgs/servers/sql/postgresql/default.nix#L56). Somehow it should be possible to get `--with-python` into this list.

![configureFlags](https://user-images.githubusercontent.com/618853/115369841-cb396700-a1c8-11eb-8aa8-4415a86a2450.png)

**Additional context**

I am trying to get a nix-shell working that has a postgresql_12 with python support. I am not trying to get a working configuration in NixOS.

It should be possible to use `packageOverrides` to explicitly add support for plpython. I am still exploring this possibility. Others have done something similar for other postgres extensions (https://github.com/NixOS/nixpkgs/issues/38369). There is a nix pill that describes how to override packages here (https://nixos.org/guides/nix-pills/override-design-pattern.html#idm140737319871088) and here (https://nixos.org/guides/nix-pills/nixpkgs-overriding-packages.html). However, it looks like this can get complicated (https://stackoverflow.com/questions/41980840/how-to-customize-a-nixpkgs-package-configureflags). More examples of overriding can be found here: http://www.bnikolic.co.uk/nix-cheatsheet.html#orgb5bd923. Another approach for overriding packages is via overlays (https://nixos.wiki/wiki/Overlays). By including support for python in the derivation itself, it may be easier for new users to get started.

@bbigras attempted to add support for multicorn (https://github.com/NixOS/nixpkgs/pull/91510/files), which is implemented using python (https://multicorn.org/), but this doesn't use plpython3u, and is thus not directly related to this issue. Just mentioning it here for others that are trying to figure out how to get python in their database backend. 

 The author of the following article shows how to configure postgres using `withPackages`: https://wilspi.com/post/tech/nix-recipes/postgresql/:

```nix
let
 postgresql_12 = pkgs.postgresql_12.withPackages (p: [ p.postgis ]);
```

I can imagine a solution that may look like this: `pkgs.postgresql_12.withPackages (p: [ p.python3 ])`.

Another possibility, is to have something like `postgresql_12Full` (see [python38Full](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=python38Full) etc.).

**Notify maintainers**

@marsam Can you recommend a way to get plpython3u enabled in the nix build of postgres?

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell: 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-31-generic, Ubuntu, 20.04 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(vagrant): `"nixpkgs-21.05pre282880.5268ee2ebac"`
 - nixpkgs: `/home/vagrant/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by W1M0R** [comment]
The following extract seems to work so far:

```nix
...
let
  # https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/overrides.nix
  postgresql_12_plpython38 = pkgs.postgresql_12.overrideAttrs (attrs: {
    buildInputs = attrs.buildInputs or [] ++ [ pkgs.python38 ];
    configureFlags = attrs.configureFlags or [] ++ [ "--with-python" ];
    # https://nixos.org/guides/nix-pills/basic-dependencies-and-hooks.html#idm140737319490896
    propagatedBuildInputs = attrs.propagatedBuildInputs or [] ++ [ pkgs.python38 ];
  });
...
```

**Comment by addict3d** [comment]
I'm interested in using this but not sure when I'd be able to pick it up.

**Comment by W1M0R** [comment]
I had to get this working on an [older nixpkgs](https://github.com/NixOS/nixpkgs/blob/1035e58494c2aa89deab5dce4824cf820be3ec3d/pkgs/servers/sql/postgresql/default.nix) commit, and couldn't make use of the newer [pythonSupport](https://github.com/NixOS/nixpkgs/blob/dfd9fbdc069685c82a1d0171fb5ab2914aa6a16a/pkgs/servers/sql/postgresql/generic.nix) override.

Thanks to comments and commits by @marsam @hrdinka @wolfgangwalther and others, I could successfully introduce `plpython3u` into `postgresql_12` (with extensions), using the following overlay:

```nix
final: prev: rec {

  my_python = prev.python310.withPackages (ps: [ 
    ps.pyjwt 
  ]);

  my_postgres = (prev.postgresql_12.overrideAttrs (attrs: {

    buildInputs = attrs.buildInputs ++ [ my_python ];
    configureFlags = attrs.configureFlags ++ [ "--with-python" ];

    # inform the postgres build step about the location of python
    PYTHON = "${my_python}/bin/python3"; 

    # ensures that postgres prefers the "bundled" python environment
    postFixup = attrs.postFixup + ''
      wrapProgram "$out/bin/postgres" \
        --set PYTHONPATH "${my_python}/${my_python.sitePackages}" \
        --prefix PATH ":" "${my_python}/bin"
    '';

  })).override {
    # a necessary step to ensure that withPackages brings plpython3u along for
    # the ride
    this = final.my_postgres;
  };

  # use this attribute for a postgres with plpython3u support and pgtap
  my_postgres_with_ext = my_postgres.withPackages (ps: [
    ps.pgtap
  ]);

}
```

The following sql will demonstrate that the correct interpreter and PYTHONPATH is used, and that imports work:

```sql
set role postgres;

create extension if not exists plpython3u;

create or replace function test_python() returns text
as $$
  import sys
  import jwt
  encoded = jwt.encode({"some": "payload"}, "secret", algorithm="HS256")
  return f"{encoded} {sys.executable} {sys.path}"
$$ language plpython3u;

select test_python();
```

Related links:

1. https://www.postgresql.org/docs/current/install-make.html#CONFIGURE-ENVVARS-PYTHON
1. https://wiki.nixos.org/wiki/Python#Troubleshooting
1. https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md
1. https://ryantm.github.io/nixpkgs/languages-frameworks/python/#python
1. https://github.com/NixOS/nixpkgs/blob/0a510bcc582a11f2ba1d4f77cbbfc47408018981/pkgs/applications/video/kodi/unwrapped.nix#L222-L225
1. https://github.com/NixOS/nixpkgs/blob/212372f68568d85d4e77b4a7411409ecd8e36e66/pkgs/development/tools/mysql-shell/8.nix#L139
1. https://github.com/NixOS/nixpkgs/commit/6af01120a6e861527d5a8a3e4fc3f875730ac1ea
1. https://github.com/NixOS/nixpkgs/commit/b6773ad79eb3bc735e3a8d6c230240b327d1254c
1. https://github.com/NixOS/nixpkgs/commit/2c7d7d13b61c16f0da9dc6d53cd4ee17004cc31f
1. https://github.com/NixOS/nixpkgs/pull/280959/files
1. https://github.com/NixOS/nixpkgs/commits/master/pkgs/servers/sql/postgresql/default.nix
1. https://github.com/NixOS/nixpkgs/commits/master/pkgs/servers/sql/postgresql/generic.nix
1. https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sql/postgresql/generic.nix
1. https://github.com/NixOS/nixpkgs/blob/005a253cb21061f969b4d2cebffb023e30546303/pkgs/servers/sql/postgresql/default.nix
1. https://github.com/NixOS/nixpkgs/blob/1035e58494c2aa89deab5dce4824cf820be3ec3d/pkgs/servers/sql/postgresql/default.nix
1. https://github.com/NixOS/nixpkgs/blob/dfd9fbdc069685c82a1d0171fb5ab2914aa6a16a/pkgs/servers/sql/postgresql/generic.nix
1. https://github.com/PostgREST/postgrest/pull/3222/files
