### ISSUE TITLE
Expose Linux kernel configuration in pure Nix

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#11994]
Currently, we seem to have a giant string we interpolate values into inside [common-config.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/common-config.nix). We furthermore have ad-hoc `optionalString` in there to expose certain options only for certain kernel versions.

It seems like it wouldn't be hard to generate that giant string automatically with Nix, along with a simple way to define new options scoped to particular kernel versions. It could even use the module system outside of the standard NixOS configuration mechanism!

**Comment by henrytill** [comment]
@aszlig has done something like this [here](https://github.com/openlab-aux/vuizvui/blob/master/modules/user/aszlig/system/kernel.nix)

[Example config](https://github.com/openlab-aux/vuizvui/blob/master/machines/aszlig/dnyarri-kconf.nix), imported [here](https://github.com/openlab-aux/vuizvui/blob/master/machines/aszlig/dnyarri.nix#L70-L84)

**Comment by Profpatsch** [comment]
Will close in favor of #12158.
