### ISSUE TITLE
xfe fails to build

### ISSUE THREAD

**Issue by fowlay** [NixOS/nixpkgs#12001]
Installing 'xfe' failed for me, using a non-root Nix setup and the nixpgs-unstable channel.

The reason is that mesa-10.6.8 is no longer available as
ftp://ftp.freedesktop.org/pub/mesa/10.6.8/mesa-10.6.8.tar.xz
the correct URL is now
ftp://ftp.freedesktop.org/pub/mesa/older-versions/10.x/10.6.8/mesa-10.6.8.tar.xz.

Possibly this can be fixed in nixpkgs/pkgs/development/libraries/mesa/default.nix (I am too much of a Nix newbie to know for sure).

**Comment by domenkozar** [comment]
what channel verision are you using? It might be solved with a channel update

**Comment by fowlay** [comment]
It is nixpkgs-unstable (mistyped in original post).

**Comment by jgillich** [comment]
Fixed by #11942

**Comment by fowlay** [comment]
I tried the #11942 fix (by a quick-and-dirty edit in nixpkgs/pkgs/development/libraries/mesa/default.nix) - it seems to work fine.

The problem is a stopper for other packages as well, for example `nix-env -i emacs' fails in the same way on nixpkgs-unstable.

**Comment by jgillich** [comment]
Yep, unstable has many issues unfortunately since the channel currently isn't updating (#11865)

**Comment by domenkozar** [comment]
Closing as it's fixed
