### ISSUE TITLE
Convert contributing section from Docbook to CommonMark

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixpkgs#120011]
This issue tracks the conversion of `/doc/contributing/*` from Docbook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

If you intend to work on this conversion, please comment below!

## Conversion instructions

1. Comment here that you intend to work on it. (Please also post if you stop working on it.)
1. Checkout a new branch of nixpkgs master.
1. Rename `doc/contributing/*.xml` to `*.section.md`.
1. Convert the contents from Docbook to CommonMark. Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing .md sections for inspiration.
1. Use `nix-build` from the `doc/` folder to build the manual.
1. Preview the manual on your computer at http://0.0.0.0:8000/manual.html after running from doc/ folder:

    `nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixpkgs'`

1. When it looks good, submit a PR and reference this issue.

**Comment by bobby285271** [comment]
> 1. Comment here that you intend to work on it. (Please also post if you stop working on it.)

I would like to work on this :-)

**Comment by bobby285271** [comment]
I opened a PR here: #120298

Thanks in advance for reviewing :-)

**Comment by fricklerhandwerk** [comment]
I'll do the `using` section.

**Comment by blaggacao** [comment]
Nice! I amended the issue title for correctness sake.
