### ISSUE TITLE
Enforce no ":" in "hashedPassword" (perhaps a check)

### ISSUE THREAD

**Issue by KoviRobi** [NixOS/nixpkgs#12008]
NixOS: 16.03pre73316.93d8671 (Emu)
Nix: 1.10

If you put a colon (:) in your hashedPassword entry, such as "Still not giving it away :P" (to show your config to your friend), forget about it, rebuild, you end up corrupting the /etc/shadow file, as apparently NixOS just sets the password field (second field, with field separator ":"), so you end up accumulating ":P"s in /etc/shadow. Now that is just your mistake having a laugh at you....

True story, took me some time to figure it out

**Comment by jgillich** [comment]
It should rather check that the value is a valid hash.

**Comment by copumpkin** [comment]
@jgillich the more the computer knows and can check, the less humans have to read (unless the computer tells them to). I for one would love the computer to catch my dumb mistakes :smile:

**Comment by jgillich** [comment]
Hehe ok, this would result in the user being unable to login so a check is actually a good idea. But there are a million other options that also break stuff if you pass garbage. ;)

**Comment by KoviRobi** [comment]
To be honest, my problem is not that I was unable to log in, but that I was unable to revert by switching back to an earlier configuration

**Comment by Profpatsch** [comment]
Can we label this as good first bug? cc @copumpkin

**Comment by rnhmjoj** [comment]
This command should validate hashes: `python -c 'import crypt; print(crypt.crypt("test", "<hash>") is not None)'`. I'm not sure how to implement it though.

**Comment by rnhmjoj** [comment]
https://github.com/NixOS/nixpkgs/commit/4363ce16cf070239310c56c888311ea14e4f4ecd "works" in the sense the build fails when an hash is invalid but produce no meaningful error.
Also it scatters the hashes in the nix store so it should be changed shomehow but I don't know any other way.

**Comment by rnhmjoj** [comment]
Yes, still an issue. I have an oper PR at #83171 if anyone wants to give it a try.
