### ISSUE TITLE
nixos-unstable channel not advancing

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#120120]
`nixos-unstable` channel is wedged and cannot advance despite successful Hydra tested builds and completed , probably due to some bug in the channel scripts, but it's not clear.

One possibility is that a Nix update caused some of the NAR list files (like https://cache.nixos.org/zqwjsgl3g77h53n6blh0khkz77b9jaaw.ls) to be corrupted, but it's not clear why this is blocking the channel from advancing.

**Comment by lukegb** [comment]
```
<gchristensen> update-nixos-unstable-start[1252]:  $ index-debuginfo /scratch/hydra-mirror/nixos-files.sql
<gchristensen> update-nixos-unstable-start[2007]: error (ignored): error: input compression not recognized
<gchristensen> update-nixos-unstable-start[2007]: error (ignored): error: input compression not recognized
<gchristensen> update-nixos-unstable-start[2007]: error (ignored): error: input compression not recognized
<gchristensen> update-nixos-unstable-start[2007]: error (ignored): error: input compression not recognized
<gchristensen> update-nixos-unstable-start[2007]: error: input compression not recognized
<gchristensen> update-nixos-unstable-start[1252]: Command failed with code (1) errno (0).
```

**Comment by edolstra** [comment]
Closed by https://github.com/NixOS/nixos-org-configurations/commit/43851f20ca6865df297eaf4579d85c166e6619a1.
