### ISSUE TITLE
`fetchFromBitbucket` should strip .hg_archival.txt files before hashing

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12012]
https://github.com/NixOS/nixpkgs/pull/12002 remarks that the hash changed in `fetchFromBitbucket` (even with `fetchzip`), and I think the .hg_archival.txt file contains non-local information about tags.

**Comment by jgillich** [comment]
What is this file even for? The modified timestamp is from 2013.

**Comment by copumpkin** [comment]
@jgillich I don't think the modified timestamp is honest, since we saw it change in the past couple of days. From what I can gather, `changessincelatesttag` is telling you that there have been a few changes in the repo since the most recent tag. And crucially, even if the repo contents for a given hash are completely unchanged, if someone adds another tag, that seems like it would change.

**Comment by jgillich** [comment]
Hm, since this is basically a Bitbucket/mercurial flaw and not a single package other than inflect even uses `fetchFromBitbucket`, I'm not too convinced that this needs an immediate fix. I'll just update #12002 to use `fetchhg` for now.

**Comment by copumpkin** [comment]
Agreed that it isn't super pressing, but given that `fetchFromBitbucket` exists, it should probably work :smile:

**Comment by vcunat** [comment]
Nice investigation :-)
