### ISSUE TITLE
hscolor fails to build

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#12018]
Tried to update my system to master today, failing at hscolor:
```
unpacking source archive /nix/store/3g73vbx3ydfii0a5h7f7nryjf72yljya-hscolour-1.23.tar.gz
source root is hscolour-1.23
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-hscolour-1.23.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-hscolour-1.23.drv-0/Main.o )
Linking Setup ...
/nix/store/bl4bwi2hnscy9xcrivwiwxwphkfc65c6-ghc-7.10.3/lib/ghc-7.10.3/ghcpr_8TmvWUcS1U1IKHT0levwg3/libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3.a: file not recognized: Input/output error
collect2: error: ld returned 1 exit status
builder for ‘/nix/store/c0hybvb0qbw19rfg65vh83hfsjlvx63a-hscolour-1.23.drv’ failed with exit code 1
```

@peti Could this be related to the recent haskell updates?

**Comment by peti** [comment]
This looks like your `/nix/store` is corrupt. I don't believe the recent updates could possibly cause I/O errors while trying to parse GHC core libraries.

**Comment by jgillich** [comment]
Ok, so I now have to rebuild all that stuff again, yay :dancers:

**Comment by copumpkin** [comment]
You might want to check your filesystem and/or drive, too. Check your `dmesg` output, run `fsck` and other tools, and make sure your filesystem and hardware are solid!

**Comment by peti** [comment]
Please re-open if this turns out to be a fault in Nix after all.
