### ISSUE TITLE
package postfix contains broken symlinks

### ISSUE THREAD

**Issue by phunehehe** [NixOS/nixpkgs#12017]
using master at 2c9369dc439ef7e68ed4839b16dad0d2d7628b96

```
$ nix-build pkgs/top-level/all-packages.nix -A postfix          
/nix/store/ws409j26y1831n04nmn21lil75p5mm6p-postfix-3.0.3
$ tree /nix/store/ws409j26y1831n04nmn21lil75p5mm6p-postfix-3.0.3/bin
/nix/store/ws409j26y1831n04nmn21lil75p5mm6p-postfix-3.0.3/bin
├── mailq -> installdir/nix/store/ws409j26y1831n04nmn21lil75p5mm6p-postfix-3.0.3/bin/sendmail
├── newaliases -> installdir/nix/store/ws409j26y1831n04nmn21lil75p5mm6p-postfix-3.0.3/bin/sendmail
├── postalias
├── postcat
├── postconf
├── postdrop
├── postfix
├── postkick
├── postlock
├── postlog
├── postmap
├── postmulti
├── postqueue
├── postsuper
└── sendmail
```

**Comment by wmertens** [comment]
Hmm, I wonder what happens if you set the install dir to $out? Could you play with that?

https://github.com/phunehehe/nixpkgs/blob/d78fc8b21099a66d6719facf6e4f663e599f0bf3/pkgs/servers/mail/postfix/3.0.nix#L65


On phone, sorry for brevity…

**Comment by phunehehe** [comment]
@wmertens Postfix seems to do something weird. As you can see in https://github.com/NixOS/nixpkgs/blob/7ec9ce56f4f0aecab0210a4ba7d3af054c0eb8ed/pkgs/servers/mail/postfix/3.0.nix#L48, it's putting the the full path of `$out` under `installdir`. I guess that was the reason 3.0.nix was written like that. Need to dig more.

**Comment by gebner** [comment]
When updating postfix to 3.0, I just copied this part from the 2.11 derivation.  I think @rickynils originally put this in.  I guess it has something to do with the `/etc/postfix` path being handled correctly--postfix should install to `$out/etc/postfix` and `$out/bin/sendmail`, but use `/etc/postfix` and `$out/bin/sendmail` at runtime--so we prefix everything with `installdir` just during installation and move it to the correct place afterwards.

**Comment by phunehehe** [comment]
see also https://github.com/NixOS/nixpkgs/pull/12033#issuecomment-189803821
