### ISSUE TITLE
current avidemux version fails to build

### ISSUE THREAD

**Issue by exi** [NixOS/nixpkgs#12028]
avidemux changed its build process in version 2.6 so our 2.5.6 build worked, but we bumped the version to 2.6.9 which fails since 2015-10-28 13:31:04.
@jagajaga @viric should we roll back the version until a working PR for a 2.6.9 build comes along?

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/170c8e08d321072eda4f892271085626d56a5493 is the relevant commit, for reference

**Comment by jagajaga** [comment]
Strange, because I've installed it myself those times.. We can rollback or improve.

**Comment by vcunat** [comment]
@jagajaga: so roll back now until a better solution is found?

**Comment by jagajaga** [comment]
@vcunat I will try to fix it today. If I won't succeed I will do a rollback.

**Comment by vcunat** [comment]
OK.

**Comment by exi** [comment]
Would love to see the solution. Tried to fix it for a short time but gave up because the new modular build system of avidemux seemed not really compatible with genericBuild out of the box.
@jagajaga good luck, just for curiosity sakes :)

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/pull/12100
