### ISSUE TITLE
nextcloud: dont set headers in static web-app nix file or make them replaceable

### ISSUE THREAD

**Issue by nivadis** [NixOS/nixpkgs#120223]
**Describe the bug**
headers are set in nextcloud.nix#L704-L711

https://github.com/NixOS/nixpkgs/blob/9abe4174c776625539ffa4c21477e7cf090bb587/nixos/modules/services/web-apps/nextcloud.nix#L704-L711

with appendHttpConfig or extraConfig you only can add the same header again with another value but you can not replace the headers set in nextcloud.nix

**Expected behavior**
have an option to enable default headers and disable them to set them yourself

**Additional context**
specially for cache or content-security-policy headers annoying 

**Notify maintainers**
@Ma27

**Comment by aanderse** [comment]
What about `extraConfig = lib.mkForce ''# entirely replace extraConfig with this'';`?

**Comment by nivadis** [comment]
might work but creates the need to check this options on every update.

**Comment by aanderse** [comment]
What needs to be checked every update? Why?

**Comment by nivadis** [comment]
i mean if there is a need for changes in this section.

**Comment by aanderse** [comment]
Ah sorry, yes I understand.
