### ISSUE TITLE
webkitgtk+ vulnerabilities

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#12023]
Most of our packages currently depend on webkitgtk-2.4 that [seems to suffer](http://webkitgtk.org/security/WSA-2015-0002.html) from many vulnerabilities. We do have webkitgtk-2.10 but it isn't used too much. (Many CVEs claim everything before 2.10.0 is vulnerable &ndash; that came out in September and our latest 2.4.x came out in May.)

GNOME3 is among major dependants /cc @lethalman, and also several standalone web browsers. Migrating from 2.4 might be lots of work (and unsuitable for 15.09 anyway), so I assume we need to find patches to fixup 2.4.

**Comment by vcunat** [comment]
Here's [Fedora report](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/S3VHBCPMPVZ3NBKR7FQZQE6HBUHVEZ3D/) for inspiration.

**Comment by Profpatsch** [comment]
(triage) as far as a all-packages.nix search shows, there’s about half a dozen packages left with 2.4.

**Comment by domenkozar** [comment]
This should be fixed in https://github.com/NixOS/nixpkgs/issues/18312

**Comment by vcunat** [comment]
Let's only keep the other ticket.
