### ISSUE TITLE
element-desktop from nixos-unstable can't open links

### ISSUE THREAD

**Issue by futile** [NixOS/nixpkgs#120228]
**Describe the bug**
When I click any link in, e.g., a chat message in the current `element-desktop` from `nixos-unstable`, the link won't open.
Doing the same in the version from `nixos-20.09` works, and opens the browser as expected.

**To Reproduce**
1. Run `nix run nixpkgs/nixos-unstable#element-desktop`
2. Click any link
3. Nothing happens, i.e., no browser is opened.

**Expected behavior**
The clicked link should open in my webbrowser.

**Screenshots**
Not applicable.

**Additional context**
Running from terminal outputs a crash in `gio` for me:

```console
/run/current-system/sw/bin/xdg-open: line 651: 30683 Segmentation fault      (core dumped) gio open "$1"
```

Debugging this a bit, "$1" seems to just be the url, and `gio open <url>` works fine, so no idea what's going wrong.

**Notify maintainers**
@Ma27 @pacien @fadenb @mguentner @Ekleog @Ralith 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs/nixos-unstable#nix-info -- -m
warning: warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).system
             |         ^
 - system: `0`
 - host os: `Linux 5.4.109, NixOS, 20.09.20210421.5c0e6a8 (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `""`
 - channels(felix): `""`
warning: warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1:

            1| <nixpkgs>
             | ^
 - nixpkgs: `0`

$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-20.09
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: element-desktop
# a list of nixos modules affected by the problem
module:
```

**Comment by hmenke** [comment]
Can you try literally `gio open "$1"`? Maybe that's the problem although it would be weird.

**Comment by futile** [comment]
> Can you try literally `gio open "$1"`? Maybe that's the problem although it would be weird.

I tried `gio open "$1"` and `gio open "\$1"`, both work (i.e., don't crash). This also seems to be the same `gio` that is called through `element-desktop` -> `xdg-open` -> `gio` (`/nix/store/kds86w7lff84iqc73376x7w4v1sbprna-glib-2.64.6-bin/bin/gio`).

**Comment by futile** [comment]
@Kazimazi @hmenke just since you found the issue, are you experiencing the same problem/can you reproduce it? Would be nice to confirm whether this is only a problem on my machine or whether its present for others as well.

**Comment by Kazimazi** [comment]
I have some the same issue, but not sure if it's the same. When I open links in XWayland element-desktop it fails with
```
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
```
and after a short while I get a popup
```
Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.
```
On the other hand running element with wayland native flags seems to open links in the browser.

From firefox side something changed since my last update, because it is not "default browser" anymore, although I haven't changed it.

**Comment by futile** [comment]
Ah ok. Might be useful to know that I'm also running Wayland with Gnome 3 and Vivaldi as my default browser.

**Comment by Kazimazi** [comment]
I see now, when I use XWayland element, it only opens links in XWayland firefox, and when I use native, it opens in native firefox.

**Comment by Kazimazi** [comment]
With chromium, I couldn't reproduce at all.

**Comment by futile** [comment]
Update: This crash also occurs under X11 (without wayland).

**Comment by futile** [comment]
Seems to be fixed. `nix run nixpkgs/nixos-unstable#element-desktop` just gave me a version in which I could open links again. So I  guess some update/dependency update fixed the issue.

**Comment by evils** [comment]
huh, i didn't check for open issues
could this have been revolved by #123777?

**Comment by futile** [comment]
Thanks for checking in! I just tested with the `element-desktop` from master, and sadly the issue is still present. I'm using vivaldi (so  chrome-based) as my browser. Also this happens under X11 without wayland as well.

**Comment by buckley310** [comment]
> could this have been revolved by #123777?

This commit actually breaks opening links for me since I updated this morning. Manually launching element without the MOZ_DBUS_REMOTE variable makes links work again.

**Comment by futile** [comment]
@buckley310 dang! did you already open a new bug? sounds like there at least is a clear reason for it.

**Comment by buckley310** [comment]
Nope, just went looking for existing bugs and commented here.

**Comment by futile** [comment]
Hi @patka-123! I can't try to reproduce it currently, but will probably be able to try in like a ~week or so. I'll let you know then, and thanks a lot for checking in! :)

**Comment by futile** [comment]
> @futile did you manage to have a look? Otherwise it seems acceptable to close this issue for now?

Just tested, and it works again! :) Thanks a lot for checking in, and I'll close the issue then :)
