### ISSUE TITLE
github-runner: outdated runner fails silently

### ISSUE THREAD

**Issue by veehaitch** [NixOS/nixpkgs#120263]
**Describe the bug**

The upstream GitHub Runner has a routine to update itself. As this cannot succeed with Nix, it's patched out.

When trying to run a workflow on an outdated self-hosted runner on NixOS, GitHub seems to send update events and won't schedule any jobs on the runner until it runs the latest version. Our patched Nix runner ignores those events which means that just nothing happens. Also, no error is reported. At the same time, the GitHub UI reports jobs as queued.

**Expected behavior**

1. Instead of ignoring those events entirely, print a warning that the runner is outdated and might not be able to run any jobs
2. At the same time, if possible, try to run workflows anyways. You've been warned.

**Comment by antifuchs** [comment]
Having just run into something like this myself (in an issue that #133698 should fix), I think reworking the gh runner to run in an FHS userenv might be the right choice. Github won't budge on the requirement for the runner to auto-update & the current stance silently breaks people's setups - FHS userenvs seem to be the exact solution for software like that.

**Comment by veehaitch** [comment]
I agree that this leads to unexpected situations which are hard to address even if one identified the outdated runner as the underlying issue. Your proposal would work: package the binary release and run it with `buildFHSUserEnv`.

On the other hand, we'd essentially denixify the derivation which is kinda sad as we already have a package which is built from source and runs all the tests. I still wonder if there's a viable way to have an outdated runner still accept and execute jobs. Of course, this approach might create problems of its own as GitHub obviously assumes that runners are always updated to the latest version before running any jobs. I don't know, however, how likely that is going to cause issues. Having an outdated runner accept jobs isn't a permanent solution; users should still update as soon as they can but it prevents the runner from stopping working for no apparent reason.

We could introduce an additional package `github-runner-bin` and make both derivations work with the NixOS module as a middle ground.

**Comment by antifuchs** [comment]
I think a useful incremental step forward here would be to allow customizing the github-runner package that the nixos module uses: Right now, it hardcodes the one in nixpkgs, which makes it hard to override with an updated version (if that version even works).
