### ISSUE TITLE
GHCJS builds failing

### ISSUE THREAD

**Issue by boothead** [NixOS/nixpkgs#12030]
Looks like ghcjs builds have been failing for a few days:

http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.haskell.compiler.ghcjs.x86_64-linux

I'm getting errors like this:

```
Configuring ghcjs-0.2.0...
Setup: At least the following dependencies are missing:
aeson >=0.7 && <0.10,
haskell-src-exts ==1.16.*,
optparse-applicative ==0.11.*,
syb >=0.4 && <0.6
builder for ‘/nix/store/lqxxispgglfncfa59f2x6kry4vh9sg0f-ghcjs-0.2.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/0qn68lwrf0vffq0c30hkqkqrgqzybg3c-ghcjs-0.2.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/0qn68lwrf0vffq0c30hkqkqrgqzybg3c-ghcjs-0.2.0.drv’ failed
/home/ben/.nix-profile/bin/nix-shell: failed to build all dependencies
```

I think my error might be due to #10215 though.

Does anyone have a working `shell.nix` for GHCJS they can point me to?

**Comment by benmos** [comment]
I've been building stuff on top of Ryan's try-reflex.nix - which you could presumably use even if you're not using Reflex itself.

There are 'develop' and 'improved-base' branches of it depending on whether you want GHCJS old-base or improved-base respectively.

It also includes some weak-reference fixes which Ryan has recently done which haven't yet made it into the main GHCJS (shims) which is another reason to recommend it.

(eg https://github.com/benmos/reflex-dropzone <https://github.com/benmos/reflex-dropzone> master / improved-base branches is an example of a GHCJS project built on top of try-reflex.nix)

--Ben

**Comment by boothead** [comment]
Thanks @benmos! When are you up in London next, it's been ages :-)

**Comment by peti** [comment]
@boothead, ghcjs depends on outdated versions of its build inputs which we no longer have (in the default package set). I suppose the proper way to fix this is to report the issue upstream so that they remedy the problem in the ghcjs repository. Then we can update to a more recent version.

**Comment by boothead** [comment]
@peti related to this one do you think? https://github.com/ghcjs/ghcjs/issues/442

**Comment by peti** [comment]
Kind of. It would help, of course, if the `ghcjs` developers could commit their builds to a particular Stackage LTS package set. If they did, then we could build `ghcjs` using that package set, too, and then those kind of version-mismatch problems would be a thing of the past.

**Comment by domenkozar** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/700e4aebdca96e6e81a5956de59ff16b8347e596
