### ISSUE TITLE
fail2ban cannot find ipset binary

### ISSUE THREAD

**Issue by pennae** [NixOS/nixpkgs#120338]
**Describe the bug**
when configured to use ipset actions fail2ban fails to ban because the action script cannot find the ipset binary.

**To Reproduce**
configure fail2ban to use `iptables-ipset-proto6` actions, then cause a ban (eg invalid ssh logins)

**Expected behavior**
iptables rules and ipsets for the ban are created.

**Screenshots**
```
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.actions [483822]: NOTICE [sshd] Restore Ban 135.181.198.14
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.utils [483822]: ERROR 7fe267a803b0 -- exec: ipset create f2b-sshd hash:ip timeout 600
                                         iptables -w -I INPUT -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.utils [483822]: ERROR 7fe267a803b0 -- stderr: '/nix/store/jdi2v7ir1sr6vp7pc5x0nhb6lpcmg6xg-bash-4.4-p23/bin/sh: ipset: command not found'
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.utils [483822]: ERROR 7fe267a803b0 -- stderr: "iptables v1.8.7 (legacy): Set f2b-sshd doesn't exist."
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.utils [483822]: ERROR 7fe267a803b0 -- stderr: ''
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.utils [483822]: ERROR 7fe267a803b0 -- stderr: "Try `iptables -h' or 'iptables --help' for more information."
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.utils [483822]: ERROR 7fe267a803b0 -- returned 2
Apr 23 14:52:48 .fail2ban-serve[483822]: fail2ban.actions [483822]: ERROR Failed to execute ban jail 'sshd' action 'iptables-ipset-proto6' info 'ActionInfo({'ip': '135.181.198.14', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7fe26761dee0>, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7fe26760c5e0>})': Error starting action Jail('sshd')/iptables-ipset-proto6: 'Script error'
```

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.29, NixOS, 21.05pre282878.652749c4ca7 (Okapi)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre282878.652749c4ca7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by nixinator** [comment]
The fail2ban derivation doesn't bring in ipset, it's also going to need some patching of the fail2ban conf files. Need to research if ipset protocol 6 is availble in nixpkgs, ipset v4 does seem to exist.

**Comment by pennae** [comment]
unstable has ipset 7.11, 20.03 has ipset 7.5, 20.09 has ipset 7.6. all of those should be protocol version 7 and thus work with the v6 actions i think?

**Comment by pennae** [comment]
fwiw adding ipset to the fail2ban service path in configuration.nix seems sufficient to get this to work.

**Comment by nixinator** [comment]
In theory...yes. ! lets see if the practise matches up! :-)

**Comment by pennae** [comment]
we've applied that setting locally and so far haven't seen any problems across quite a few restarts and ban/unban actions. seems good! :)

**Comment by pennae** [comment]
what would be a good way to solve this for the next person? there's two things we could think of:

 1. add ipset to path when using iptables as the firewall backend (like sshguard does)
 2. extend firewallPackage to firewallPackages and let people who want ipset add it there

second one sounds cleaner, not least because using nftables already requires changing firewallPackage. that would require deprecating firewallPackage though, and i don't feel qualified to do that

**Comment by nixinator** [comment]
is extra packages the way to go? ipset is needed by fail2ban, so should it be a dependency by default? I've been flat out working so not had time to look at this. These are just questions not demands!

**Comment by pennae** [comment]
ipset isn't needed by the default configuration of fail2ban, only if you choose a different ban action. if the default action and ipset were the only options i'd totally agree that ipset should be a dependency, but there's quite a few more actions: some send mail, some call into shorewall, or curl something to cloudflare, or even call into BIND to update a dns zone. since we'd need some extraPackages mechanism to support those properly anyway it didn't feel quite right to elevate one action to default-dependency and leaving out all the others (especially since nftables doesn't even need ipset to provide the same functionality).

but i've got no feelings on this. if y'all want ipset to be a default dependency i'm perfectly fine doing that instead. would very much like to keep extraPackages though for the stated reasons.
