### ISSUE TITLE
pythonPackage dask.dataframe cannot be imported in sandboxed tests

### ISSUE THREAD

**Issue by nbren12** [NixOS/nixpkgs#120307]
**Describe the bug**

For sandboxed builds on my mac, any python tests which ultimately import `dask.dataframe` will fail with this error:
```
  File "/nix/store/nv60iri29bia4szhhcvsdxgsci4wxvp6-python3.8-dask-2021.03.0/lib/python3.8/site-packages/dask/dataframe/io/csv.py", line 392, in <module>
    AUTO_BLOCKSIZE = auto_blocksize(TOTAL_MEM, CPU_COUNT)
  File "/nix/store/nv60iri29bia4szhhcvsdxgsci4wxvp6-python3.8-dask-2021.03.0/lib/python3.8/site-packages/dask/dataframe/io/csv.py", line 382, in auto_blocksize
    blocksize = int(total_memory // cpu_count / memory_factor)
TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
```

**To Reproduce**

Somewhat tricky to reproduce since it only affects downstream dependees, and a recent commit disabled the dask tests, hiding this issue.

See #120233 for an example.

**Additional context**

Dask.dataframes infers an optimal chunk size using a package `psutil` to get the amount of available memory and CPUs. This non-determinism breaks the build.

**Notify maintainers**

cc @FRidh 

**Metadata**

This is not valid since I am building from master of nixpkgs.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(noah): `"nixpkgs-20.09.3072.d4c29df154d, home-manager-20.09"`
 - nixpkgs: `/Users/noah/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.dask
# a list of nixos modules affected by the problem
module:
```

**Comment by FRidh** [comment]
That's a clear upstream bug; apparently their `cpu_count` value is not given.
