### ISSUE TITLE
Package Vulnerability Scanner

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#12035]
I wrote a little program to do automatic vulnerability scanning of nixpkgs, based on the NVE CVE database.

It detects a bit over 100 vulnerabilities in all 15.09 packages. This number includes a lot of false positives, the checking is based on version numbers and does not (yet) detect patches.
Here is the list: https://gist.github.com/jgillich/f842c97702d2de61a6eb

Most of the older CVEs have been patched manually, but some haven't. For example XChat, a program with the last upstream release in 2010 and a vulnerability reported in 2011 that allows to "possibly execute arbitrary code". I think we need to remove such unmaintained packages wherever possible, patching them forever is not sustainable.

Code for the program is [here](https://github.com/jgillich/nix-audit), written in Node. Thanks to streams Node works pretty well, but there doesn't seem to be a library to parse anything else than semantic versions, so stuff like `1.0.1q` from OpenSSL just gets ignored. It's just a prototype and doesn't interact with the local nixpkgs, so if another language would be a better fit, I'm open to rewriting it.

**Comment by vcunat** [comment]
Note: we already have http://monitor.nixos.org/vulnerable (written in ruby), but there seems something wrong in there as I haven't got any updates to the [feed](http://monitor.nixos.org/vulnerable?rss=on) for several months &ndash; /cc @phreedom for that.

**Comment by jgillich** [comment]
Seems like my Google-fu is not as good as I thought, hehe.

**Comment by vcunat** [comment]
It seems even the nixpkgs package versions information is very outdated in there.

**Comment by pSub** [comment]
monitor.nixos.org is out of date for quite some time. It blocks repeatedly and someone needs to kick it manually. I usually ping @rbvermaa on IRC when this happens and he usually fixes this quite fast. However it would be good if we could stabilize the monitor somehow and in the meantime give more people the right to kick the monitor.

**Comment by jgillich** [comment]
I'd like to go through the tree and remove stuff that has had obvious problems for a longer period of time. Can we need to establish some rules on how to handle abandoned software with vulnerabilities, like the XChat I mentioned? I think that we should remove such software if no new release with a fix for the vulnerability is made after some time, like 6 months.

**Comment by vcunat** [comment]
I believe it's almost always one of these two cases:
- some people still care for it and thus some security patch(es) soon appear somewhere, e.g. in a large distro, or
- basically noone uses it and thus we can remove it from nixpkgs.

**Comment by jgillich** [comment]
Oh yes, I meant that even if there's a patch for it, we should still remove it after some time. There's always the possibility for more security issues that just aren't getting reported anymore. Anything that is used by enough people is usually forked into a new project, which could then be packaged as a replacement (e.g. XChat -> hexchat).

**Comment by domenkozar** [comment]
https://blog.flyingcircus.io/2016/05/20/introducing-vulnix-a-vulnerability-scanner-for-nixos/

**Comment by jgillich** [comment]
That sounds very promising! I think this can be closed.
