### ISSUE TITLE
wpa_cli does not work out of the box with live CDs

### ISSUE THREAD

**Issue by roconnor** [NixOS/nixpkgs#1204]
Getting the network working when installing NixOS is very important.

However when booting from at least the minimal ISO you cannot configure the wireless network from wpa_cli.  Instead you are greeted with the error:

Could not connect to wpa_supplicant: (null) - re-trying.

One work around is to add the following line to the /etc/wpa_supplicant.conf file:

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel

And then do 

systemctl restart wpa_supplicant.

It would be good if the /etc/wpa_supplicant.conf file on the live CD already contained this stanza, or better yet, if wpa_supplciant was compiled to include ctrl_interface support even without a wpa_supplicant.conf file.

**Comment by domenkozar** [comment]
I tested this a few months ago and it works. Reopen if the problem persists.

**Comment by ajl-ewp** [comment]
I hit this problem with the image I just pulled downloaded from the the official website. Editing the wpa_supplicant.conf hasn't solved this for me yet.

**Comment by ajl-ewp** [comment]
I worked around this problem by using a different wi-fi network. The one I was using has one of those web interface sign-in's after you attach to the network to actually gain access to the internet at large.

**Comment by mmahut** [comment]
@ajl-ewp wpa_supplicant are only used to connect to a wireless network. Any sign-in page is used only once you are connection to the wireless.
