### ISSUE TITLE
command-not-found requirements aren't documented

### ISSUE THREAD

**Issue by akavel** [NixOS/nixpkgs#12044]
```
[root@nixos:/etc/nixos]# command-not-found foobar
DBI connect('dbname=/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite','',...) failed: unable to open database file at /run/current-system/sw/bin/command-not-found line 12.
cannot open database `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite' at /run/current-system/sw/bin/command-not-found line 12.
```
After quick googling I've found [some email from 2013](http://lists.science.uu.nl/pipermail/nix-dev/2013-May/011129.html) suggesting that "you'll need to add the nixos-unstable channel as root". But isn't that so by default? I couldn't find "programs.sqlite" on github in the "nixos-unstable" branch anyway. If that email is correct, what exact steps one has to do to resolve this? As I still couldn't find out from searching the "channel" keyword in NixOS manual, being a NixOS newbie. Could the instructions at least be printed explicitly by the command-not-found Perl script instead of this cryptic message, if not baked in the nix-expression as an explicit dependency?

**Comment by vcunat** [comment]
> "you'll need to add the nixos-unstable channel as root". But isn't that so by default?

I think you need at least `$ sudo nix-channel --update`. The path above certainly does exist when the channels are setup according to the manual.

> I couldn't find "programs.sqlite" on github in the "nixos-unstable" branch anyway.

It's generated from binaries and has no place in source repositories.

> If that email is correct, what exact steps one has to do to resolve this?

Add some channel as root (and call it "nixos") or check it is so already, and update it. IMO `$ man nix-channel` is a good source of how to do it.

**Comment by akavel** [comment]
Maybe this info could be added in the manual then? Kinda "for some [which?] commands, `sudo nix-channel --update` is needed as it rebuilds [some internal stuff]"?

**Comment by vcunat** [comment]
Yes, perhaps.

**Comment by domenkozar** [comment]
Sadly this doesn't work when `nix.nixPath` is declared as channel doesn't exist. Should `command-not-found` evaluate nix to get the path? cc @edolstra

**Comment by nrolland** [comment]
I have no `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite`, adding a channel and  `sudo nix-channel --update` does not generate one.

is there a specific command to recreate it ?

**Comment by vcunat** [comment]
@nrolland: nix-channel adds pairs: URL and name that you choose independently. Currently `command-not-found` searches only for channel that you called `nixos` which is what you get on NixOS by default for the system channel.

**Comment by roman** [comment]
I'm getting this weird behavior where the `programs.sqlite` file is found on an user's profile that is not root (vagrant in my case) how can I fix this scenario?

**Comment by cstrahan** [comment]
As of my last `sudo nix-channel --update`, I no longer have `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite`...

**Comment by cstrahan** [comment]
$ sudo nix-channel --list
    nixos https://nixos.org/channels/nixos-unstable

**Comment by cstrahan** [comment]
It looks like `nix-channel` stopped creating `programs.sqlite` a couple generations ago:

    $ find -L /nix/var/nix/profiles/per-user -name "programs.sqlite"
    /nix/var/nix/profiles/per-user/root/channels-4-link/nixos/programs.sqlite
    /nix/var/nix/profiles/per-user/root/channels-5-link/nixos/programs.sqlite
    /nix/var/nix/profiles/per-user/root/channels-6-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-7-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-7-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-7-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-13-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-13-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-13-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-14-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-14-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-14-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-15-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-15-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-15-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-16-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-16-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-16-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-17-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-17-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-17-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-18-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-18-link/nixos'.
    /nix/var/nix/profiles/per-user/root/channels-18-link/nixos/programs.sqlite
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-19-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-19-link/nixos'.
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels-20-link/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels-20-link/nixos'.
    find: File system loop detected; `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs' is part of the same file system loop as `/nix/var/nix/profiles/per-user/root/channels/nixos'.
    
    ~/src/nixpkgs (bitcasa-old) λ ls /nix/var/nix/profiles/per-user/root/
    channels          channels-11-link  channels-13-link  channels-15-link  channels-17-link  channels-19-link  channels-20-link  channels-3-link  channels-5-link  channels-7-link  channels-9-link
    channels-10-link  channels-12-link  channels-14-link  channels-16-link  channels-18-link  channels-1-link   channels-2-link   channels-4-link  channels-6-link  channels-8-link


It's missing in my generation 19 and 20.

**Comment by cstrahan** [comment]
It doesn't appear `nix-channel` creates `programs.sqlite`. In fact, after greping in `nixpkgs`, `nix` and `hydra`, I don't see where `programs.sqlite` is ever created... I'm pretty stumped.

**Comment by vcunat** [comment]
It can't be created locally. It should be contained in the downloaded `nixexprs.tar.xz`, but I see it isn't anymore. https://github.com/NixOS/nixos-channel-scripts/commit/f7beae78ebde1d984248ff62a160b3f0168948be#diff-682bf482f6dd273f1c3c49afd99b4660R122

**Comment by vcunat** [comment]
Aha, there's an issue about it: https://github.com/NixOS/nixos-channel-scripts/issues/4.

**Comment by domenkozar** [comment]
Closing this as it works again. The requirements aren't documented because Nix wrapps the binary with everything needed, but channels didn't ship programs.sqlite as the generation was disabled. We should probably bail out with a clearer message or just fail silently.

**Comment by sbourdeauducq** [comment]
> Sadly this doesn't work when `nix.nixPath` is declared as channel doesn't exist. Should `command-not-found` evaluate nix to get the path?

Is there a solution now for using `nix.nixPath` in combination with `command-not-found`?

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/issues/39789 for a possible way forward.
