### ISSUE TITLE
Buck built with wrong JDK version

### ISSUE THREAD

**Issue by HolgerPeters** [NixOS/nixpkgs#120557]
Buck build system is packaged with the wrong JDK it seems

```
% buck
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.Error: java.lang.NullPointerException
	at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:133)
	< snip >
	... 34 more
You're using Java 11, but Buck requires Java 8.
```

# Additional context

PR #119247 introduced a bump in JDK version, see (https://github.com/NixOS/nixpkgs/pull/119247#pullrequestreview-642420243).

@jonringer @marsam @jgertm 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by asbachb** [comment]
I guess the most recent version should support java 11: https://github.com/facebook/buck/issues/2037

**Comment by jonringer** [comment]
Until they make a stable release with those changes included, we will just use jdk8
