### ISSUE TITLE
zfs package fails to generate a module and provide zfs filesystem support

### ISSUE THREAD

**Issue by alvatar** [NixOS/nixpkgs#120585]
**zfs package fails to generate a module and provide zfs filesystem support (not NixOS on ZFS, just support for reading ZFS filesystems)**
My intention is to just be able to mount a zfs external drive, not to run NixOS on ZFS as described [here](https://nixos.wiki/wiki/NixOS_on_ZFS).

**To Reproduce**
1. Add "zfs", or "zfsStable" or "zfsUnstable" to configuration.nix

**Expected behavior**
 `zpool create -f mydrive /dev/sda` or  `zfs create poolname/name` should work. Instead, they say that zfs kernel module is not loaded and suggest loading it. After running `modprobe zfs`, I get this error:
`modprobe: FATAL: Module zfs not found in directory /run/current-system/kernel-modules/lib/modules/5.4.111`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.111, NixOS, 20.09.3888.4263ba5e133 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3888.4263ba5e133, nixos-hardware"`
 - channels(alvatar): `"nixos-20.09.1500.edb26126d98"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by lukegb** [comment]
What do you mean by "add 'zfs' to configuration.nix" - do you mean in environment.systemPackages? If so, this is WAI. You'd need to add zfs to boot.supportedFilesystems (or add "zfs" to boot.kernelModules and boot.extraModulePackages) to get the kernel module.

**Comment by alvatar** [comment]
Ah I see. I understood from the docs that those are required only if booting from a zfs partition, which is not my intention. I'll try that, thank you.
