### ISSUE TITLE
Freenet can't find "bash" at runtime

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#12054]
freenet[4549]: /usr/bin/env: bash: No such file or directory

**Comment by vcunat** [comment]
Eh, well, it seems to me that the error message implies the negation of the title.

**Comment by spacekitteh** [comment]
This needs to be updated: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/p2p/freenet/freenetWrapper#L1

**Comment by ArdaXi** [comment]
This should be fixed by #12107.

**Comment by Profpatsch** [comment]
(triage) then we can close @ArdaXi @spacekitteh?
