### ISSUE TITLE
Cannot add printer with GNOME GUI (grayed out)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#12058]
Open ```gnome-control-center``` and select "Printers". The "Add new printer" button is grayed out, making it impossible to add a printer.

This is what the program prints to the terminal:

```
(gnome-control-center:16664): printers-cc-panel-WARNING **: Your system does not have the cups-pk-helper's policy "org.opensuse.cupspkhelper.mechanism.all-edit" installed. Please check your installation
```

Relevant configuration.nix snippet:

```
  services = {
    ...
    printing.enable = true;
    xserver.desktopManager.gnome3.enable = true;
  };
```

(I don't know if this is relevant, but I found ```gnome.libgnomecups``` package in nixpkgs, but it is for GNOME 2.)

**Comment by lethalman** [comment]
Maybe we're missing this: http://www.freedesktop.org/wiki/Software/cups-pk-helper/

**Comment by bjornfor** [comment]
I've packaged cups-pk-helper in my local tree. I got a bit further. I could click on the 'Add new printer' button, it found my network printer (with avahi/DNS-SD I think) but then failed when I tried to add it:

```
(gnome-control-center:18733): printers-cc-panel-WARNING **: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.fedoraproject.Config.Printing was not provided by any .service files
(gnome-control-center:18733): printers-cc-panel-WARNING **: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PackageKit was not provided by any .service files
(gnome-control-center:18733): printers-cc-panel-WARNING **: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.fedoraproject.Config.Printing was not provided by any .service files
(gnome-control-center:18733): printers-cc-panel-WARNING **: Installation of the new printer failed.
```

So there is still some packaging work left.

**Comment by lethalman** [comment]
The org.freedesktop.PackageKit is scary. The org.fedoraproject.Config.Printing should be provided by http://cyberelk.net/tim/software/system-config-printer/ .

What a complex world...

**Comment by bjornfor** [comment]
I added cups-pk-helper to master branch in commit 92a0140ff83d4622861b0cdbfafe0295ae1afcda.

**Comment by bjornfor** [comment]
@lethalman: Right, adding ```system_config_printer``` to the system profile removed this gnome-control-center warning:

```
DBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.fedoraproject.Config.Printing was not provided by any .service files
```

However, it prints he following message repeatedly (~1 sec interval) while scanning my network for printers:

```
GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.fedoraproject.Config.Printing: Success
```

And when I select one printer and click "add", it prints

```
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PackageKit was not provided by any .service files
```

**Comment by lethalman** [comment]
Read the org.fedoraproject.Config.Printing dbus service file, it's probably trying to execute the daemon due to auto activation but cannot find it.

**Comment by bjornfor** [comment]
@lethalman: Spot on!

```
$ cat /nix/store/8p4w7v88winr0zlgqd08qnc4hh8picia-system-config-printer-1.3.12/share/dbus-1/services/org.fedoraproject.Config.Printing.service
[D-BUS Service]
Name=org.fedoraproject.Config.Printing
Exec=/usr/bin/scp-dbus-service
```

**Comment by lethalman** [comment]
Yep... now that `scp-dbus-service`.... endless... :P

**Comment by bjornfor** [comment]
@lethalman: hehe, yeah, I ask myself that from time to time :-D

**Comment by bjornfor** [comment]
Oh, scp-dbus-service is in system_config_printer (s-c-p, doh!):

```
/nix/store/8p4w7v88winr0zlgqd08qnc4hh8picia-system-config-printer-1.3.12/bin/scp-dbus-service
```

If only upstream application developer respected the configure time --prefix flag... grrr..

**Comment by bjornfor** [comment]
Fixed system-config-printer dbus service file in commit 1979034956c44d4d71d38a9dedf10de27a6f2095 (and made upstream issue: https://github.com/twaugh/system-config-printer/issues/28).

**Comment by bjornfor** [comment]
Ok, I guess the original issue is solved. I'll open new issues for remaining printer issues.
