### ISSUE TITLE
python2: Should it get knownVulnerabilities tag like openssl-1.0.2?

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#120693]
Currently there's no knownVulnerabilities tag on python2 and patches are backported.

Still, it might make sense to include a knownVulnerabilities tag warning people of the discontinued support, just [as was done with an old openssl version](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/openssl/default.nix#L183).

Additionally it requires people to specifically "opt-in" to python2 by adding the warning, as it needs to be skipped with a flag. This would notify people that may have not been aware they still have a python2 dependency in their system.

**Comment by Artturin** [comment]
it now does have knownVunlnerabilities
