### ISSUE TITLE
networkmanager tries to execute /sbin/modprobe

### ISSUE THREAD

**Issue by fkz** [NixOS/nixpkgs#12063]
I use network-manager to create a wifi-hotspot.

`journalctl --unit network-manager` gives the following:

>Jan 01 11:38:38 nixos NetworkManager[15086]: <error> [1451648318.618482] [NetworkManagerUtils.c:346] nm_utils_modprobe(): modprobe: '/sbin/modprobe ip_tables' failed: Failed to execute child process "/sbin/modprobe" (No such file or directory)

And the same for `/sbin/modprobe ip_tables`, `/sbin/modprobe iptable_nat`, `/sbin/modprobe nf_nat_ftp`, `/sbin/modprobe nf_nat_irc`, `/sbin/modprobe nf_nat_sip`, `/sbin/modprobe nf_nat_tftp`, `/sbin/modprobe nf_nat_pptp`.

The errors were followed by following with

>Jan 01 11:38:39 nixos NetworkManager[15086]: <error> [1451648319.864292] [rdisc/nm-lndp-rdisc.c:68] send_rs(): (wlp2s0): cannot send router solicitation: -101.

The workaround `ln -s /run/current-system/sw/bin/modprobe /sbin/` worked for me for now; I'll try to look into it a little bit more in the next days.

**Comment by fkz** [comment]
the path `/sbin/modprobe` seems to be hard coded in the networkmanager source. The solution is probably to patch this with `/run/booted-system/sw/bin/modprobe`.

**Comment by bjornfor** [comment]
Or lookup modprobe in $PATH?

Maybe it's just me, but I feel hardcoding NixOS specific /run/... paths is just as ugly as having /sbin/... paths (even though it makes little sense to run nixpkgs networkmanager on non-NixOS).

**Comment by fkz** [comment]
that's also possible, I don't know.
I'm wondering if I should file a bug against networkmanager and what to ask them for. Make the path compile-time configurable (then we still woudn't be able to use $PATH)? Using $PATH always? Make it configurable to use $PATH?
Maybe we should just patch it for now.

**Comment by mogorman** [comment]
i opened a bug in networkmanager as well https://bugzilla.gnome.org/show_bug.cgi?id=760061

**Comment by fkz** [comment]
:+1:

**Comment by lethalman** [comment]
networkmanager is completely broken about finding binaries. It uses the absolute path instead of just looking into `$PATH`, and it does it for every single binary it calls. It's a mess every time we try to upgrade.

**Comment by bjornfor** [comment]
Closing as https://github.com/NixOS/nixpkgs/pull/12076 is merged.
