### ISSUE TITLE
Re-organise firefox

### ISSUE THREAD

**Issue by VShell** [NixOS/nixpkgs#12065]
Firefox, at present, comes in five different packages:

* firefox
* firefox-wrapper
* firefox-bin
* firefox-esr
* firefox-esr-wrapper

The issue is that that firefox package is inevitably not what the user wants, causing issues when they try to enable plugins or configure pulseaudio.

I suggest reorganising Firefox into the following package attributes:

* firefox (current firefox-wrapper, with name "firefox")
* firefox-unwrapped (current firefox, with name "firefox-no-plugins")
* firefox-esr (current firefox-esr-wrapper, with name "firefox-esr")
* firefox-esr-unwrapped (current firefox-esr, with name "firefox-esr-no-plugins")
* firefox-bin

This would match better with what users expect, both through `nix-env -i` and `config.systemPackages`, but would also break backwards compatibility for people who currently have the wrapperless Firefox installed. What do people think?

**Comment by jgillich** [comment]
:+1:

**Comment by gpyh** [comment]
That would have prevented confusion earlier. Thanks for the help by the way.

**Comment by vcunat** [comment]
Do we even need to expose the unwrapped versions as top-level attributes? Maybe `firefox.unwrapped` passthrough instead?

**Comment by VShell** [comment]
@vcunat I was considering that, but went with top-level attributes just in case there's something I'm missing. If nobody can think of a reason to keep them as top-level attributes, I'd be happy with `firefox.unwrapped`.

**Comment by retrry** [comment]
+1 from me. When I started using NixOS this was very confusing.

**Comment by globin** [comment]
:+1:

**Comment by vcunat** [comment]
Another argument for this:
```
$ command-not-found firefox
The program ‘firefox’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.firefox
  nix-env -iA nixos.firefox-esr
```
(i.e. the hook only mentions the attributes with unwrapped FF)

**Comment by vcunat** [comment]
See an implementation: #12299.
