### ISSUE TITLE
Packaging request: libadwaita

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#120728]
**Project description**
Library to help with developing UI for mobile devices using GTK/GNOME

**Metadata**
* homepage URL: https://gnome.pages.gitlab.gnome.org/libadwaita/
* source URL: https://gitlab.gnome.org/GNOME/libadwaita
* license: lgpl21Plus
* platforms: linux

cc @NixOS/gnome 

This is needed for e.g. https://blogs.gnome.org/haeckerfelix/2021/04/09/new-shortwave-release/.

**Comment by jtojnar** [comment]
Added it to GNOME 41 to do list. Currently, there are no releases.
