### ISSUE TITLE
cffi: ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by dasj19** [NixOS/nixpkgs#120718]
**Describe the bug**
When using cffi as dependency to other python projects like bcrypt and homeassistant, it fails to compile as it does not include the _cffi_backend submodule.

**To Reproduce**
One way would be to install home-assistant with python 3.9

**Expected behavior**
To be able to compile and dependency resolution to be solved

**Screenshots**
N/A

**Additional context**
In the documentation it is stated that this is a common packaging error; and there are clues how to solve it. https://cffi.readthedocs.io/en/latest/cdef.html?highlight=backend
I tried to solve it myself but python packaging is beyond my current understanding.

One other solution is posted here: https://github.com/pyinstaller/pyinstaller/issues/1684#issuecomment-590288201 (that would need to be converted to the nix language

**Notify maintainers**

@domenkozar @LnL7 
**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"i686-linux"`
 - host os: `Linux 5.10.29, NixOS, 21.05.git.441f8ef8e4fM (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by dotlambda** [comment]
Can you share your `configuration.nix` or some other way to reproduce this?

**Comment by dotlambda** [comment]
For me, `nix-build -E "with import ./. { }; (home-assistant.override { python3 = python39; }).overridePythonAttrs (_: { doCheck = false; })"` works just fine.

**Comment by dasj19** [comment]
I have a build running right now... I'll post the exact configuration.nix lines as soon as possible.
I noticed that you use `doCheck = false;` ... If I remember correctly there are tests that fail...

**Comment by dotlambda** [comment]
> I noticed that you use `doCheck = false;` ... If I remember correctly there are tests that fail...

That wouldn't have anything to do with your error though.

**Comment by dotlambda** [comment]
@dasj19 Any updates?

**Comment by dasj19** [comment]
@dotlambda I have tried several builds and I can no longer reproduce the issue.
Thanks for assisting... I will close the issue now
