### ISSUE TITLE
Bluetooth headset audio becomes choppy after entering Teams meeting

### ISSUE THREAD

**Issue by umeat** [NixOS/nixpkgs#120807]
**Describe the bug**

Audio through my bluetooth headset sounds great, until I join a meeting in Microsoft Teams meeting. Once I join a meeting the audio becomes extremely choppy for ALL applications. The poor audio persists when I exit the Teams meeting, and doesn't return to normal until I kill the Teams application.

No idea if this is a Teams issue or something else.

**Metadata**
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05pre282015.a73020b2a15 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre282015.a73020b2a15, nightingale-20.09.2016.19db3e5ea27"`
 - channels(brandon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by peterhoeg** [comment]
I do a stupid amount of teams meetings on nixos with various bluetooth headsets and have never seen this problem (both using pulseaudio and recently pipewire). *However*, I run teams in a browser and not through the application. Have you tried that?

**Comment by umeat** [comment]
I don't experience the issue when using the browser. It's a reasonable workaround, but still very strange that my audio is affected the way it is when using the application.

**Comment by umeat** [comment]
Yeah, the reason is because teams was automatically switching the profile of my bluetooth headset to a dual channel mode where the quality of both the output and input are quite poor (as opposed to "sync" mode where the output is good, but there can be no input at all).

I understand that this is a bluetooth driver issue to do with proprietary software.

**Comment by wamserma** [comment]
@umeat As this can not be solved on our end, can we close the issue?

**Comment by umeat** [comment]
Sure thing
