### ISSUE TITLE
programs.bash.enableCompletion = true; causes have: command not found on bash prompt

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#12080]
it looks like the have function isn't accessible to me when I enable bashcompletion on 15.09 on amd4.  any ideas as to the cause?  Disabling bash.enableCompletion makes the have issue go away.

**Comment by jgillich** [comment]
`have` is deprecated. Try running `bash --debug` to see where it is coming from.

**Comment by peti** [comment]
Use `_have` instead.

**Comment by mogorman** [comment]
im happy to fix it anyway that is possible, but this is the behavior with no config file changes. stock nixos.  i believe it should work

**Comment by peti** [comment]
I'm not sure what you mean? Packages that rely on `have` cannot be relied on to work with modern versions of bash completion because it's deprecated. The function is  now called `_have`. This has nothing to do with NixOS, that decision was made by the authors of `bash-completion`.

**Comment by bjornfor** [comment]
@mogorman: I had the same problem. A few packages in nixpkgs still uses deprecated "have" command. You can find them either with the command @jgillich showed, or ```grep -rl "\<have\>" /nix/store/*/etc/bash_completion.d```. Please submit an issue per package you find that use 'have' (beware of false positives in the grep output).

**Comment by mogorman** [comment]
bash --debug just prints same message

**Comment by mogorman** [comment]
@peti i would think it is reasonable to enable bashcompletion and it not error out like that on the cli

**Comment by mogorman** [comment]
@bjornfor thank you, i found it.  it was lxc
