### ISSUE TITLE
isStatic only set on linux

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#120862]
**Describe the bug**
when using `pkgsStatic`, `stdenv.hostPlatform.isStatic` only gets set on linux. This seems to be done very much on purpose, so I don't know if there's some good reason for it:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/stage.nix#L214-L234
```
    pkgsStatic = nixpkgsFun ({
      overlays = [ (self': super': {
        pkgsStatic = super';
      })] ++ overlays;
      crossOverlays = [ (import ./static.nix) ];
    } // lib.optionalAttrs stdenv.hostPlatform.isLinux {
      crossSystem = {
        isStatic = true;
        parsed = stdenv.hostPlatform.parsed // {
          abi = {
            gnu = lib.systems.parse.abis.musl;
            gnueabi = lib.systems.parse.abis.musleabi;
            gnueabihf = lib.systems.parse.abis.musleabihf;
          }.${stdenv.hostPlatform.parsed.abi.name}
            or lib.systems.parse.abis.musl;
        };
      } // lib.optionalAttrs (stdenv.hostPlatform.system == "powerpc64-linux") {
        gcc.abi = "elfv2";
      };
    });
  };
```

This causes problems for instance when cross-compiling to windows and then using pkgsStatic, some packages wrongly think they are not compiling statically. I can't remember what packages I've encountered this in, and right now I'm encountering it in a change that I'm trying to make, not something that already exists.

**To Reproduce**
```
$ nix repl 
> pkgs = import <nixpkgs> { crossSystem = { config = "x86_64-w64-mingw32"; libc = "msvcrt" }; };
> pkgs.pkgsStatic.stdenv.hostPlatform.isStatic
false
```

**Expected behavior**
`isStatic` would be true on all platforms if using `pkgsStatic`

**Notify maintainers**
@matthewbauer seems to have added this code / created `pkgsStatic`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.27, NixOS, 21.05pre281538.9e377a6ce42 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(root): `"nixos-21.05pre281538.9e377a6ce42, nixos-hardware"`
 - channels(qolen): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsStatic
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/commit/42b5817e6b94974614cc9d0f803c14551274d6c5
