### ISSUE TITLE
Owncloud webdav issue

### ISSUE THREAD

**Issue by aborsu** [NixOS/nixpkgs#12087]
webdav is broken in owncloud versions after 7.0 (so 8.0.x, 8.1.x, and 8.2.x).
So until this is fixed we are stuck on owncloud 7.0

**Comment by Mayeu** [comment]
I'm kind of working on trying to make that work. Right now I have a setup with Nginx, Owncloud 8.2 and Let's Encrypt. And the only not working thing is the Webdav part. I won't have any time to continue working on it during the next 2 weeks, but I had some plan to reach to the Owncloud devs to have some idea on how to debug that :)

(Also, can you update the issue name with something that's more a match of the content of the issue?)

**Comment by joachifm** [comment]
Could you elaborate on the breakage?

**Comment by aborsu** [comment]
As I said above webdav is broken. (Not sure why). I checked the owncloud changelogs and nothing is mentionned about it. I had a theory that owncloud uses libcurl to set itself up and since it's packaged for fedora/centos it doesn't list it as a dependency but I have had no time to check if that was it or not.

**Comment by joachifm** [comment]
What I mean is, saying "it's broken" gives no indication about what can be done about it or if it's even a nixpkgs problem.

**Comment by Mayeu** [comment]
@joachifm issue is, it's literally the only info we have from Owncloud. Quoting the error:
> Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.

They seems to have other information in the logs :(

**Comment by joachifm** [comment]
@Mayeu oh, wow, okay. What does upstream say?

**Comment by Mayeu** [comment]
arf, I'm ashamed to say that sadly I had no time to continue working on that :(

**Comment by bjornfor** [comment]
For those not tied to Owncloud+Nginx, you can try this Nextcloud+Lighttpd NixOS module: https://github.com/bjornfor/nixos-config/blob/master/modules/nextcloud.nix. (WebDAV works.)
