### ISSUE TITLE
"unrar" license is not correct

### ISSUE THREAD

**Issue by rekado** [NixOS/nixpkgs#12084]
The license in `unrar/default.nix` is declared as GPL2, but the license certainly is not the GPL, it is not even a free software license as it contains this restriction on use:

~~~
   2. UnRAR source code may be used in any software to handle
      RAR archives without limitations free of charge, but cannot be
      used to develop RAR (WinRAR) compatible archiver and to
      re-create RAR compression algorithm, which is proprietary.
      Distribution of modified UnRAR source code in separate form
      or as a part of other software is permitted, provided that
      full text of this paragraph, starting from "UnRAR source code"
      words, is included in license, or in documentation if license
      is not available, and in source code comments of resulting package.
~~~

The "unrar" package should thus be marked as non-free.

**Comment by vcunat** [comment]
Hmm, the license was changed by 8fbc082d1, /cc @wkennington. I'm rather certain that [it truly is unfree](https://en.wikipedia.org/wiki/RAR_(file_format)). What is worse, I can't see any free alternative except for [what debian packages](https://packages.debian.org/stretch/unrar-free) but that one can't handle newer archive versions. (All other SW I've found is based on the restricted sources of this unrar, including p7zip.)

**Comment by vcunat** [comment]
I forgot to /cc maintainer @ehmry.

**Comment by wkennington** [comment]
Worst case it look like it is unfreeRedistributable.

**Comment by vcunat** [comment]
Yes, I believe that's the best specification from what we have in `lib.licenses`.

**Comment by vcunat** [comment]
And, thanks for reporting this!

**Comment by rekado** [comment]
I have found this one, which might work with newer RAR versions:

   https://bitbucket.org/WAHa_06x36/theunarchiver/overview

It's under LGPL 2.1.

**Comment by vcunat** [comment]
Hmm, yes, in comparison to the one I posted it claims to support RAR 2.9 and 3.0. Not (yet) the 5.0 format of the original unrar, but it's likely free, as it's [approved by FSF](http://www.fsf.org/blogs/licensing/free-rarv3-extraction).

**Comment by nckx** [comment]
> https://bitbucket.org/WAHa_06x36/theunarchiver/overview

That requires an objective C compiler and run-time and sounds like a lot of work.

**Comment by vcunat** [comment]
Well, I personally don't plan to invest much energy into any RAR-connected stuff, but that shouldn't prevent anyone else interested...

IIRC our gcc has flags to enable Objective C, only I'm afraid they may be rotten.

**Comment by nckx** [comment]
> IIRC our gcc has flags to enable Objective C, only I'm afraid they may be rotten.

Oh, I actually spent an hour or so doing just that.

I soon found myself packaging the abomination that is GNUstep, just to get error messages about missing header files that should have been included with the shiny new gc(obj)c.

I noped out of there pretty quickly and regret trying.
