### ISSUE TITLE
okular: build poppler with NSS to enable PDF signing

### ISSUE THREAD

**Issue by schmittlauch** [NixOS/nixpkgs#120928]
**Feature Request**

Once #120514 is merged, we have an *okular* version that finally supports cryptographically signing PDFs – in theory.
The signature stuff requires *poppler* to be built with *nss* support. That is currently only the case for *poppler_utils*, but not for the poppler passed to the okular derivation.
For testing, I've modified poppler to always build against nss and have then built okular from #120514. This resulted in working signature support in okular.

I'd really like to have an *okular* in NixOS 21.05 that comes with signature support enabled by default. So the main question is how to modify poppler and/or okular to do so.
- unconditionally enable nss in poppler: simple, but increases closure size of all packages using poppler
- build okular against *poppler_utils*: reuses existing poppler flavor, but might not make sense from a semantical point of view
- introduce additional `withNss` flag to poppler, override the poppler passed to okular to activate this flag: does not affect non-okular users, but okular users will have 2 almost identical build flavors of poppler in their store

For verifying whether okular has successfully been built with signature support, go to *Settings -> Configure Backends -> PDF* and see whether certificate settings appear in there.

I'd like to hear the ideas of okular and poppler maintainers.

**Notify maintainers**

@ttuegel @jtojnar @turion

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [okular, poppler]
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Do you know how does okular use it? Does it do it through the library or by calling a utility? If the latter, we could try to make utils and main poppler disjoint and then ocular could depend on both without blowing up.

**Comment by schmittlauch** [comment]
Looking at https://invent.kde.org/graphics/okular/-/merge_requests/296/, it seems to utilise library functions. Interestingly, the compile time `check_cxx_source_compiles` CMake check for the flag `HAVE_POPPLER_SIGNING` succeeds even without NSS, as it only checks against poppler features. But without NSS the certificate selection settings are missing.

**Comment by jtojnar** [comment]
Yeah, then building with nss either by default, or for ocular will be necessary. Do you know how much linking againsts NSS increases the closure?

**Comment by schmittlauch** [comment]
on the nss used by poppler then:

```console
$ nix path-info -rhS /nix/store/5a23cac6jfxw4wyrqrz5rs9mi03bd1zr-nss-3.63 
/nix/store/40rrvq8lfx1j9sy3kvvdqvy55qslkjq8-libidn2-2.3.0          1.8M
/nix/store/54kjgrvjl1w8pj8xvrzslxryggk6izi6-glibc-2.32-46         31.4M
/nix/store/5a23cac6jfxw4wyrqrz5rs9mi03bd1zr-nss-3.63              47.5M
/nix/store/5y0pjy4xy8vcricnaypf4bwpsimqhgms-libunistring-0.9.10    1.6M
/nix/store/6z0x3527vkgybnhsw2f797dnp0sbf5lw-p11-kit-0.23.22       36.3M
/nix/store/92l4x1wk8jr3jc6s0bs5a5prrwp3hk4w-sqlite-3.35.2         32.9M
/nix/store/bbrsnfc405d698als7hafy67n20ghzin-libtasn1-4.16.0       31.5M
/nix/store/ca9v5vjzfkcg220bcy77w807sjilkfvm-nspr-4.30             31.7M
/nix/store/gdwlkdiyvp7a9hd36l44r3i64nk7vq2i-bash-4.4-p23          32.7M
/nix/store/jv0xfr84djjkhwyxlq26vf68gid7xin4-libffi-3.3            31.5M
/nix/store/nqshm0fz5ii45d5mnfsgijx2qf2ng2dk-zlib-1.2.11           31.5M
/nix/store/www6jl96517r7pi07q7mjqggrv1lla37-gcc-10.2.0-lib        37.1M
```

**Comment by turion** [comment]
I find `withNss` the best. Why not have this option for `okular` as well? Then people who care about not having another `poppler` in store can switch it off.

**Comment by schmittlauch** [comment]
@turion You mean with `withNSS ? true` as a default, such that it does not need to be explicitly overriden in the callPackage for okular but non-okular users can override it globally?

**Comment by turion** [comment]
What does "override it globally" mean?

**Comment by schmittlauch** [comment]
doing a global `nixpkgs.config.packageOverrides` in your nixpkgs config.nix or redefine it in an overlay, such that the default value for the `withNss` flag is changed.

**Comment by turion** [comment]
Ah ok, yes that sounds like a good way to go forward then.

**Comment by schmittlauch** [comment]
Damn, I totally forgot about this, but would appreciate it if #124294 can still make it into 21.05.
