### ISSUE TITLE
unrar license change added a non-free dependency to calibre

### ISSUE THREAD

**Issue by gebner** [NixOS/nixpkgs#12091]
Since #12084 made unrar nonfree, calibre is now non-free as well as it depends on unrar.

Looking through the source code of calibre, it includes (and builds) its own copy of unrar anyhow, so it is not clear to me why we add unrar to the LD_LIBRARY_PATH (calibre works just fine without the LD_LIBRARY_PATH wrapper).

Should we do something about this?  AFAICT there are two options:
1. Patch out unrar support from calibre, [just like Debian does](http://sources.debian.net/patches/patch/calibre/2.45.0%2Bdfsg-1/dont_build_unrar_plugin.patch/).  This would keep calibre free.
2. Set calibre's license to unfreeRedistributable, just like unrar.

**Comment by nckx** [comment]
> Looking through the source code of calibre, it includes (and builds) its own copy of unrar anyhow

So, just for clarity: it was always unfree but just not correctly marked as such? The wording makes it sound like a regression, when it's more like a fix/correction (albeit an unfortunate one).

> 1. Patch out unrar support from calibre, just like Debian does. This would keep calibre free.
> 2. Set calibre's license to unfreeRedistributable, just like unrar.

Or 3. Both: add an unrarSupport parameter (`false` by default) and set the licence accordingly.

**Comment by gebner** [comment]
> So, just for clarity: it was always unfree but just not correctly marked as such?

Essentially yes.

> The wording makes it sound like a regression, [...]

It *did* break my system configuration because I do not have `allowUnfree` set, but still have calibre in my system packages.

> Or 3. Both: add an unrarSupport parameter (false by default) and set the licence accordingly.

This seems like a good idea. I'll prepare a PR.

**Comment by pSub** [comment]
@gebner This ticket can be closed now, right?

**Comment by gebner** [comment]
Yes, of course.
