### ISSUE TITLE
gnome3.nautilus-python: no module named gi

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#121077]
**Describe the bug**
Trying to run a nautilus-python extension (syncstate-Nextcloud.py) fails with
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

**To Reproduce**
1. enable gnome3 and install nextcloud-client
2. start nautilus from terminal with `NAUTILUS_PYTHON_DEBUG=misc nautilus`
3. see something like 
```
nautilus_python_load_dir: entered dirname=/run/current-system/sw/share/nautilus-python/extensions
nautilus-python:g_module_open /nix/store/d44wd6n98f93hjr6q1d1phhh1hw7a17d-python3-3.8.8/lib/libpython3.8.so.1.0
nautilus-python:Py_Initialize
nautilus-python:PySys_SetArgv
nautilus-python:Sanitize the python search path
nautilus-python:init_pygobject
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

(org.gnome.Nautilus:204242): Nautilus-Python-WARNING **: 22:41:35.311: pygobject initialization failed

(org.gnome.Nautilus:204242): Nautilus-Python-WARNING **: 22:41:35.311: nautilus_python_init_python failed

```

**Expected behavior**
python should find gi.

**Additional context**
 I think it is part of pygobject3 which is in buildInputs therefore I think it is a problem of a wrong NIX_PYTHONPATH

**Notify maintainers**
@NixOS/gnome 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.14, NixOS, 21.05.20210424.93de027 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - nixpkgs: `/nix/store/j9gg42hg61x936ah4a54sy9jrfb99irn-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnome3.nautilus-python
# a list of nixos modules affected by the problem
module: 
```

**Comment by jtojnar** [comment]
I am not sure if it ever worked. The shared module links against pygobject but that still does not have  to mean the gi module will be available on Python side. Maybe we need something like the following:

```patch
--- a/pkgs/desktops/gnome-3/core/nautilus/default.nix
+++ b/pkgs/desktops/gnome-3/core/nautilus/default.nix
@@ -90,6 +90,8 @@ stdenv.mkDerivation rec {
 
   preFixup = ''
     gappsWrapperArgs+=(
+      # Allow nautilus-python to find gi
+      --prefix PYTHONPATH : "${python3.withPackages (pp: [ pp.pygobject3 ])}/${python3.sitePackages}" \
       # Thumbnailers
       --prefix XDG_DATA_DIRS : "${gdk-pixbuf}/share"
       --prefix XDG_DATA_DIRS : "${librsvg}/share"
```

At least until we have `nautilus-with-extensions`.

https://github.com/NixOS/nixpkgs/blob/d600f006643e074c2ef1d72e462e218b647a096c/nixos/modules/services/x11/desktop-managers/gnome3.nix#L447

**Comment by benneti** [comment]
Yes this works, thank you!

**Comment by benneti** [comment]
hmmm I just tried with the new nautilus-python, but the nautilus python extensions still fail due to missing gi. Is there a reason that you tried to load gi in nautilus-python and not add the prefix arg as in your comment?

**Comment by jtojnar** [comment]
Did you make sure `NAUTILUS_EXTENSION_DIR` is updated? It worked for me with gsconnect extension.

I chose that method because pygobject is really nautilus-python dependency, not nautilus one.

**Comment by benneti** [comment]
nevermind it works now (also with nextcloud), I forgot the `gnome.` in the overlay where I overwrote the package from master. Thanks for fixing it!
