### ISSUE TITLE
steam: readonly boostrap.tar.xz

### ISSUE THREAD

**Issue by urlordjames** [NixOS/nixpkgs#121025]
**Describe the bug**
When launching Steam after `bootstrap.tar.xz` is in `~/.local/share/Steam`, it fails to overwrite `bootstrap.tar.xz` which has read only permissions.
```
cp: cannot create regular file '/home/blah/.local/share/Steam/bootstrap.tar.xz': Permission denied
```

**To Reproduce**
1. launch Steam
2. fully exit Steam after `bootstrap.tar.xz` is in `~/.local/share/Steam`
3. relaunch Steam

**Expected behavior**
Steam should not fail to launch.

**Additional context**
This looks like it could be fixed by a backport of 373cb5d41db3a60249dfa2c7481fb46642e11a92.

**Notify maintainers**
@jagajaga
@jonringer

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.14, NixOS, 20.09.3975.17b101e29df (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(james): `""`
 - channels(root): `"nixos-20.09.3975.17b101e29df, unstable-21.05pre284379.93de027ee04"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  steam
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
closed by #121090
