### ISSUE TITLE
black nixos test linting

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nixpkgs#121066]
https://github.com/NixOS/nixpkgs/blob/f93ecc4f6bc60414d8b73dbdf615ceb6a2c604df/nixos/lib/testing-python.nix#L152

This linting is good but it should ignore line length as there might be unpredictable valuables (e.g. nix store paths) rendered into the scripts that break in arbitrary instances.

eg:

```python
      kube.wait_until_succeeds(
          "kubectl apply -f ${config.kubernetes.result}"
      )
```

or

```python
      kube.wait_until_succeeds("kubectl apply -f ${config.kubernetes.result}")
```

depends solely on the length of the actual `config.kubernetes.result` string.

**Comment by dotlambda** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/72964

**Comment by blaggacao** [comment]
Thanks @dotlambda !
