### ISSUE TITLE
VirtualBox hangs system

### ISSUE THREAD

**Issue by geraldus** [NixOS/nixpkgs#12108]
Hi, this is second time I'm facing this issue: VirtualBox often hangs my host NixOS entirely.  First time this happened while running guest Ubuntu, now when installing guest Windows.

Nix channel is set to 15.09.  VirualBox was installed according to wiki:
```nix
{
virtualisation.virtualbox.host.enable = true;
nixpkgs.config.virtualbox.enableExtensionPack = true;
}
```
Extensions were downloaded manually.
What other useful information could I provide?

**Comment by vkleen** [comment]
I had a similar issue running Virtualbox on top of btrfs. The following VirtualBox ticket fixes the issue for me:

**Comment by vkleen** [comment]
Sorry, forgot the ticker:
https://www.virtualbox.org/ticket/11862

**Comment by geraldus** [comment]
@vkleen thank you very much, I've enabled **Use host I/O cache** and it seemed to solve the issue.  However when I launched **Chromium** my system hanged again.  So, it seems the issue somehow related to Chromium, because all past times I had Chromium launched, but this time I decided to exit all apps before running VirtualBox.  I'll try to test VirtualBox with other apps and try to google about possible Chromium impact on VirtualBox.

**Comment by geraldus** [comment]
Well, I've figured out that the real issue is **proprietary nvidia driver**!  I've rebuilt NixOS without nvidia drivers and now VirtualBox works fine!  Also this resolved another issue — now I can even login to any virtual tty 1-6!  So, the question is how to install proprietary driver correctly to make all things work as expected.

**Comment by geraldus** [comment]
Indeed it was already discussed here #9912
