### ISSUE TITLE
Failed to uninstall nixpkgs

### ISSUE THREAD

**Issue by gentcys** [NixOS/nixpkgs#121112]
**Describe the bug**
Try to uninstall `/nix` volume as described:

```
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
Creating volume and mountpoint /nix.

     ------------------------------------------------------------------
    | This installer will create a volume for the nix store and        |
    | configure it to mount at /nix.  Follow these steps to uninstall. |
     ------------------------------------------------------------------

  1. Remove the entry from fstab using 'sudo vifs'
  2. Destroy the data volume using 'diskutil apfs deleteVolume'
  3. Remove the 'nix' line from /etc/synthetic.conf or the file
```

and the error message is:

```
➜  ~ diskutil apfs deleteVolume disk1s7
Started APFS operation
Deleting APFS Volume from its APFS Container
Unmounting disk1s7
The volume "Nix Store" on disk1s7 couldn't be unmounted because it is in use by process 0 (kernel)
Error: -69888: Couldn't unmount disk
```

**To Reproduce**
1. Remove the entry from fstab using 'sudo vifs'
2. Destroy the data volume using 'diskutil apfs deleteVolume disk1s7'

**Expected behavior**
Uninstall /nix as expected

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by alyssais** [comment]
Hi! This is an issue with Nix, not with Nixpkgs. Could you reopen your issue on the [Nix issue tracker](https://github.com/NixOS/nix/issues), please?  (Unfortunately I don't have the permissions required to transfer the issue for you.)
