### ISSUE TITLE
aws-vault: missing xdg-open

### ISSUE THREAD

**Issue by ymatsiuk** [NixOS/nixpkgs#121154]
**Describe the bug**
Due to missing dependency, browser page never opens during `login`

**To Reproduce**
1. `❯ aws-vault login test_profile`

**Expected behavior**
Browser page must open and authentication process finish.

**Screenshots**

**Additional context**
```bash
❯ aws-vault login test_profile
Opening the SSO authorization page in your default browser (use Ctrl-C to abort)
https://<sso_URL>.amazonaws.com/?user_code=<CODE>
```

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.14, NixOS, 21.05pre285574.8e4fe32876c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(ymatsiuk): `""`
 - channels(root): `"nixos-21.05pre285574.8e4fe32876c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: aws-vault
# a list of nixos modules affected by the problem
module:
```

**Comment by joshpearce** [comment]
Could this have broke darwin support. I just tried switching to unstable and got this error:

`       error: Package ‘xdg-user-dirs-0.18’ in /nix/store/8zgn73r04imfsn9sjynvp0nkkwppxngf-source/pkgs/tools/X11/xdg-user-dirs/default.nix:22 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]`

**Comment by SuperSandro2000** [comment]
Fix is already on the way. 

Also please do not necro bump old, closed issues if the actual problem is a different one.
