### ISSUE TITLE
SHA Sum of Ideamaker no longer correct

### ISSUE THREAD

**Issue by madonius** [NixOS/nixpkgs#121185]
**Describe the bug**
Trying to install ideamaker yields:
```
hash mismatch in fixed-output derivation '/nix/store/xvqih5s9b7m5zpclac6zizib4apkv1yl-ideaMaker_4.0.1.4802-ubuntu_amd64.deb':
  wanted: sha256:0a1jcakdglcr4kz0kyq692dbjk6aq2yqcp3i6gzni91k791h49hp
  got:    sha256:1rs8b0l97anz6xhj5nfg4js1npjidyzfiirbdxgggz4mm5lc9qdx
```

**To Reproduce**
1. `nix-shell -I nixpkgs=channel:nixpkgs-unstable -p ideamaker`

**Expected behavior**
Ideamaker is being installed

**Notify maintainers**
@lovesegfault 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.111, NixOS, 20.09.3970.c6f0d282ae4 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(madonius): `"home-manager-20.09, nixpkgs-20.09.3888.4263ba5e133, nixpkgs-unstable-21.05pre283965.665a613811e, sops-nix"`
 - channels(root): `"nixos-20.09.3970.c6f0d282ae4, sops-nix, unstable-21.05pre281538.9e377a6ce42"`
 - nixpkgs: `/home/madonius/.nix-defexpr/channels/nixpkgs`

**Comment by nixinator** [comment]
if this is not a temporary fetch error at your end, then it quite possible that raise3d have re-uploaded a different .deb file with the same name. That's not very good form, rather like force pushing over a github repo. It maybe a simple patch , that didn't warrant a version bump, or they have been hacked. You just don't know. it's probably the former.

**Comment by madonius** [comment]
I don't think it is temporary tbh.

**Comment by nixinator** [comment]
Sign, maybe ping upstream, and ask the nicely to sort out their releases, and perhaps tell them that the finger print of their binary downloads are changing.. either they will say, thanks we know, or thanks, we didn't know... 

the latter being much more serious than the former.

**Comment by tomodachi94** [comment]
...and removed in https://github.com/NixOS/nixpkgs/pull/249582.
