### ISSUE TITLE
Installing skim-vim with vim-addon-manager now fails

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#121137]
**Describe the bug**
I have been building a `vim_configurable` configured to use the plugin `skim-vim`, but now this fails, complaining of a missing attribute `rtp`.

**To Reproduce**
```bash
$ nix-build --expr '(import <nixpkgs> {}).vim_configurable.customize {name = "vim-customized"; vimrcConfig.vam.pluginDictionaries = [{name = "skim-vim";}];}'
error: attribute 'rtp' missing, at /nix/store/8h18v061vqng9bxx20bdpjp3ad65p1j7-nixos-21.05pre285574.8e4fe32876c/nixos/pkgs/misc/vim-plugins/vim-utils.nix:307:62
(use '--show-trace' to show detailed location information)
```

**Notify maintainers**
@jonringer @softinio

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.75-hardened, NixOS, 21.05pre281538.9e377a6ce42 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre285574.8e4fe32876c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [vim_configurable]
# a list of nixos modules affected by the problem
module: []
```

**Comment by teto** [comment]
still relevant ?
