### ISSUE TITLE
security: Wireguard generatePrivateKeyFile NixOS option allows unprivileged private key read

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#121288]
See https://github.com/NixOS/nixpkgs/pull/60138/files#r623971755:

The NixOS option [`networking.wireguard.interfaces.<name>.generatePrivateKeyFile`](https://search.nixos.org/options?channel=20.09&show=networking.wireguard.interfaces.%3Cname%3E.generatePrivateKeyFile&from=0&size=50&sort=relevance&query=networking.wireguard) does:

```sh
touch "${values.privateKeyFile}"
chmod 0600 "${values.privateKeyFile}"
wg genkey > "${values.privateKeyFile}"
```

This is not safe.

The private key can be read by an unprivileged user who opens the file between `touch` and `chmod`.

For example with `python`:

```python
f = open('testfile', 'r')  # run this after `touch`
f.read()  # run this after the key was written; the key will be printed
```

**`touch + chmod 600 + write` are never safe.** This sequence should never be used for writing secrets.

This is why `install --mode` (like `mkdir --mode`) and `umask` exist. See for example the key generation section in [ArchWiki](https://wiki.archlinux.org/index.php/WireGuard#Key_generation) or [NixOS's wiki](https://nixos.wiki/wiki/Wireguard#Generate_keypair).

---

**Edit** for completeness:

The parent directory of the private key file is currently created with

```
mkdir --mode 0644 -p "${dirOf values.privateKeyFile}"
```

So the directory doesn't exist, it is created with permissions `drw-r--r--`; due to lack of `x`, no non-root-user can do things in it at all. However, this protection does not apply when `dirOf privateKeyFile` already exists; then `mkdir -p` is a no-op. There's nothing in docs or code that suggest that; for example, that `dirOf` may be `/etc`.

I think setting `0644` is also not very good; it only works because `root` has implicit `x` access anyway, and the service runs as root. Instead, the private key file should have strict permissions.

**Comment by dotlambda** [comment]
cc @NixOS/security-notifications

**Comment by nh2** [comment]
I'm looking into making an `umask` based fix now.
