### ISSUE TITLE
hadolint-2.3.0 is broken on master and unstable

### ISSUE THREAD

**Issue by melg8** [NixOS/nixpkgs#121258]
**Describe the bug**
hadolint of version 2.3.0 fails to build on current master/nixos-unstable branches,
due to missing dependency of language-docker at least 9.3 version.

**To Reproduce**
1. ```cd /tmp ```
2. ```git clone https://github.com/NixOS/nixpkgs nixpkgs && cd nixpkgs```
3. ```git checkout 16093daaf21153d25d8e7f7f4605adb5d1c13f06 ```
4. ```nix-build -A hadolint```

**Expected behavior**
Success of build.

**Screenshots**
Log:
```
Using Parsec parser
Configuring hadolint-2.3.0...
CallStack (from HasCallStack):
  $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing or private dependencies:
language-docker >=9.3.0 && <10
```
You can also see that on hydra [report](https://hydra.nixos.org/build/142234017/nixlog/2/tail)

**Additional context**
From what i see:
hadolint takes language-docker as an argument.
Default version for it is ```version = "9.2.0"```;
Which i assume is set [here](https://github.com/NixOS/nixpkgs/blob/8f19637a39b50804103016ac1716c20969bba974/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L1425)
But new version of hadolint [needs at least 9.3](https://github.com/hadolint/hadolint/blob/96e61f82c5c66d8be1985863e56b93ae652b832a/package.yaml#L29)

I've encountered that issue while trying to update pinned nixpkgs to newer version in my [project](https://github.com/melg8/cit).
And managed to overcome it by using something like
```
 hadolint = pkgs.hadolint.override {
    language-docker = pkgs.haskellPackages.language-docker_9_3_0;
  };
```

Running bisect:
```
git bisect start 16093daaf21153d25d8e7f7f4605adb5d1c13f06 00fe26700397b46a33ffbcb36e5297cf31b57faa
git bisect run eval "nix-build -A hadolint" 
```
Shoved failure due to shellcheck not building.

Actual breaking [commit](https://github.com/NixOS/nixpkgs/commit/b561a5d99620f41f98df196f73060094925c6012#diff-db620ccbf4b3a2612bf583eadebb88f54f7ed670f5be5eaf804cbcdd51fb2db3R115584).

**Notify maintainers**
@peti  - maybe it will be fixed by last commit to master? [by this mr](https://github.com/NixOS/nixpkgs/pull/120446)
edit: i've checked haskell-updates  branch, it works fine there.

**Metadata**
``` bash
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.106, NixOS, 20.09.3554.f8929dce13e (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(user): `""`
 - channels(root): `"nixpkgs-unstable-21.05pre280338.619953ead47, nixos-20.09.3554.f8929dce13e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  hadolint
```

**Comment by 06kellyjac** [comment]
Yeah it's pretty common for it to break

**Comment by peti** [comment]
This is fixed by today's merge of `haskell-update` (https://github.com/NixOS/nixpkgs/pull/120446).
