### ISSUE TITLE
manual: How to link to a NixOS option with a star / asterisk?

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#121328]
I want to write a release notes entry linking to an option like

```
networking.wireguard.interfaces.<name>.peers.*.publicKey
```

How do I do that?

I kow that `<name>` becomes `_name`, e.g. in

```xml
<link linkend="opt-networking.interfaces._name_.ipv4.addresses">networking.interfaces.eth0.ipv4.addresses</link>
```

but how to do it for `.*.`?

The current manual at https://nixos.org/manual/nixos/stable/ does not seem to have any existing occurrence.

**Comment by andersk** [comment]
If you go to https://nixos.org/manual/nixos/stable/options.html, find the relevant option, and click on it, you’ll see the relevant fragment appear in your browser’s URL bar. In this case: https://nixos.org/manual/nixos/stable/options.html#opt-networking.wireguard.interfaces._name_.peers._.publicKey

**Comment by nh2** [comment]
So `*` translates to `_`.

Thanks!
