### ISSUE TITLE
musescore: Segfault on startup

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#12138]
All I can say:

```bash
$ mscore 
initScoreFonts 0x1e866c0
Segmentation fault
```

**Comment by cillianderoiste** [comment]
FWIW musescore is working fine here: 16.03pre71289.7ae05ed (Emu), using KDE4. Does strace reveal anything interesting?

**Comment by matthiasbeyer** [comment]
I'm on `16.03pre73316.93d8671 (Emu)`, which seems to be latest unstable. I cannot read strace output, so I cannot help here, sorry.

**Comment by cillianderoiste** [comment]
Hrm, what desktop/WM are you using? Maybe you can paste the last 200 lines of strace?

**Comment by matthiasbeyer** [comment]
https://gist.github.com/matthiasbeyer/084d3b8e36471b877387

I'm using i3wm.

**Comment by cillianderoiste** [comment]
I wonder if it is be related to your graphics card (ATI), or maybe xinerama. Are you having any other issues? Does OpenGL work ok? Are you already using the free radeon driver or ati_unfree?

**Comment by matthiasbeyer** [comment]
I'm using `ati_unfree` :cry:  How can I verify whether openGL works?

**Comment by cillianderoiste** [comment]
I tested installing a recent musescore from hydra: http://hydra.nixos.org/build/29957414/nix/pkg/musescore-2.0.2-x86_64-linux.nixpkg ... this also works fine for me.

I've had great fortune with the free ati driver, very stable and fine for 2D on multiple monitors etc. I haven't done much OpenGL with it at all though. For OpenGL you should at least be able to run `glxgears`.

**Comment by matthiasbeyer** [comment]
`glxgears` works for me so far. How can I enable the free ati driver on nixos? I guess I will test it. I'm on kernel `4.1.*` still, if that matters. I guess I will need to update the kernel to use the free driver, right?

**Comment by vcunat** [comment]
@matthiasbeyer: ``services.xserver.videoDriver = "ati";`` (and full reboot will be needed) It shouldn't be required to update the kernel, but it might depend on particular case.

**Comment by heydojo** [comment]
You can try :
https://github.com/heydojo/nixpkgs/commit/d19ffe2f29f2b61d31fba12a4e4fb5156fda6106
the path to libstdc++ is missing in some of the binary files within ati-drivers.
The patch fixes it.

**Comment by matthiasbeyer** [comment]
@heydojo I would need to reboot for this, right? Well... musescore is not that important for me, I just wanted to play around a bit with it, so I'm happy to wait until this is in unstable!

**Comment by vcunat** [comment]
I think it should be enough to restart X (display-manager.service).

**Comment by matthiasbeyer** [comment]
@vcunat still too much :smile:

**Comment by heydojo** [comment]
@matthiasbeyer as @vcunat says a rebuild switch should do it after you apply the patch.
Which card do you have btw @matthiasbeyer? If that patch makes it in to unstable it likely will include the update to the driver itself because the update I have here compiles with gcc5.
The update drops support for HD5000 and HD6000 cards unfortunately.

**Comment by matthiasbeyer** [comment]
I have `AMD Radeon R9 200 Series`

**Comment by heydojo** [comment]
@matthiasbeyer yeah that card is definitely still supported by the radeon crimson update to ati-drivers.

**Comment by Profpatsch** [comment]
(triage) Since it seems to work fine on most systems and we couldn’t find the reason for the segfault I suggest we close @matthiasbeyer.
