### ISSUE TITLE
Bring the Haskell documentation back into nixpkgs

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#121403]
**Suggestion**

This is a suggestion to move the documentation for haskellPackages back into the nixpkgs manual. It is currently maintained in the cabal2nix repo and hosted at https://haskell4nix.readthedocs.io

Pros:
* Unified design and single entry point for users
* Easier to edit and discover
* Documentation and changes to nixpkgs can be done in the same commit/PR.
* No one needs to maintain the extra page.

Cons:
* (Small) parts of it need to be translated to md.
* Right now the nixpkgs manual has a much worse table of content and we don‘t get anchor-links for 4th level headings.

Alternatives:
* Never do this
* Do this only when the nixpkgs manual has been switched to mdbook, which is apparently going to happen.

I am mentioning this because I‘d like our new workflows and scripts to be documented asap.

What do you think @NixOS/haskell?

**Comment by sternenseemann** [comment]
I'm all for it and would also suggest that we use this opportunity to convert some of the knowledge currently only available as youtube videos into written form. People seem to like the videos, but written documentation is easier to link to, more accessible and much easier to update.

**Comment by cdepillabout** [comment]
This also sounds good to me.  

> I am mentioning this because I‘d like our new workflows and scripts to be documented asap.

Yeah, I think this is important as well.  I'd like to have our new workflows written down somewhere, which was part of the reason I had wanted to write https://github.com/NixOS/nixpkgs/issues/121140#issuecomment-830573332.

Having some workflows we point contributors to would be helpful as well.

One bad thing about the nixpkgs manual is that if we made this switch, it would effectively contain three different kinds of content:

- Tutorials / explanations of how to use the Haskell stuff in Nixpkgs.  This would mainly be for new users, or possibly as a reference for more advanced users.
- An explanation of the workflows for contributing to the Haskell stuff in Nixpkgs.  This would mainly be for people sending PRs to Nixpkgs who aren't the three of us.
- An explanation of the workflows for the `haskell-updates` branch.  This would mainly be for the three of us (or potential future maintainers).

It is somewhat unfortunate having these three mostly(?) non-overlapping things in the same document, but I guess it is all we have for now with the Nixpkgs manual.

(Although I am of the opinion that it is more important that we get these things written down _somewhere_.  I guess I don't really care as much exactly _where_ each of these is written down.)

**Comment by domenkozar** [comment]
The biggest benefit I see is that the whole nixpkgs community works together to have better tooling and experience for documentation readers.

That used to stagnate with years, but the recent move to markdown aligns things back on track.

**Comment by cdepillabout** [comment]
I sent a PR for documenting the haskell maintainer workflow in nixpkgs in #122728.

**Comment by cdepillabout** [comment]
@sternenseemann is working on a PR that should close this: https://github.com/NixOS/nixpkgs/pull/126382

**Comment by cdepillabout** [comment]
In our last meeting, we came up with a very rough table of contents for a new set of documentation.  We all volunteered to do different sections:

- need to document contributing process for maintainers
- lucas started PR
  - going over cabal4nix and update it for our new stuff
  - started redoing documentation from scratch
  - done:
    - overview and introduction
    - haskellPackages.mkDerivation (documented all arguments)
  - todo:
    - running cabal2nix and packaging your own packages (this is section in old manual as well?), callHackage (malte)
    - section on overriding (lucas)
    - patch nix-doc to generate documentation from haskell.lib
    - document dev environment stuff shell.nix generation, env passthru, shellFor, developPackage
    - HLS (malte)
    - contributing (dennis zurihac?)
      - fixing a broken package
      - regenerate hackage2nix, as well as how the package set is generated in general
      - what do maintainers do
    - FAQs / How-To
    - reference
      - how does `NIX_GHC` work? (malte)
      - IFD (callCabal2nix, callHackage, callHackageDirect)

**Comment by sternenseemann** [comment]
* [ ] Document how to use GHCJS <https://github.com/NixOS/nixpkgs/issues/140583#issuecomment-934221803>

**Comment by cdepillabout** [comment]
We'd still like to do this.

**Comment by maralorn** [comment]
The documentation has landed in master now and can be iterated on. Some of the points mentioned above are still open. Maybe should create a new tracking issue with a checklist?

**Comment by TristanCacqueray** [comment]
Is there documentation about the extra package versions like `http2_4_0_0` and how they are managed: e.g. what's the process to get `http2_4_1_0`?

**Comment by maralorn** [comment]
There is something about versioned attributes here: https://nixos.org/manual/nixpkgs/unstable/#haskell-available-packages

The issue you are encountering is that you want callCabal2nix use a different cabal2nix then the one from your package set.

Maybe you can use `super.callCabal2nix` and manually pass in all overriden packages to yours. Or you try `(haskellPackages.callCabal2nix ...).overrideScope` to apply your overlay only to the package after cabal2nix was used.

**Comment by maralorn** [comment]
Since this has in principle been accomplished I will close this issue.

**Comment by isomorpheme** [comment]
The current nixpkgs manual still links to this issue from the Haskell section. Since it's closed, does that mean the link can removed, or is there still content to be migrated that's tracker by another issue?

**Comment by maralorn** [comment]
I don't think their is anything still to migrate.

**Comment by sternenseemann** [comment]
I think there is some stuff that's technically not covered still. One big remaining item would be to update the readthedocs page to be placeholder pages that link to the Nixpkgs manual instead. Unfortunately, I don't think it updates automatically, so we'll likely need to coordinate with @peti to achieve that.

https://github.com/NixOS/cabal2nix/issues/592

**Comment by peti** [comment]
Let me know what you need me to do. I'll be happy to help.
