### ISSUE TITLE
gnunet-gtk: logo missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#121435]
**Describe the bug**
When i open the _About_ dialog in any program provided by gnunet-gtk, for example `gnunet-conversation-gtk`, i notice that the logo is missing.

![Screenshot from 2021-05-01 22-32-48](https://user-images.githubusercontent.com/91113/116794527-cda39700-aacd-11eb-9746-d83a133034e6.png)

```
[davidak@gaming:~]$ gnunet-conversation-gtk
May 01 22:32:33-569327 gnunet-conversation-gtk-111220 ERROR Configuration fails to specify option `RECORD_EXPIRATION' in section `CONVERSATION'!

(gnunet-conversation-gtk:111220): Gtk-WARNING **: 22:32:40.763: Could not load image 'gnunet-logo-color.png': Failed to open file “/nix/store/vy1n86p63cgv9z8djwjiyb9k6sfcs4kf-gnunet-gtk-0.14.0/share/gnunet/gnunet-logo-color.png”: No such file or directory
```

**To Reproduce**
1. `nix run -f channel:nixos-unstable gnunet-gtk -c gnunet-statistics-gtk` (wait for #110606 [hit unstable](https://nixpk.gs/pr-tracker.html?pr=110606))
2. click Help -> About

**Expected behavior**
no icons missing

**Notify maintainers**
@pstn @vrthra @fricklerhandwerk (who fixed the build last)

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.13, NixOS, 21.05pre283367.0a5f5bab0e0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager-20.09, nixos-21.05pre283367.0a5f5bab0e0, nixos-hardware, nixos-unstable-21.05pre283367.0a5f5bab0e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FliegendeWurst** [comment]
PR: #264898
