### ISSUE TITLE
rustc in rustStable is outdated

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#12157]
in `nix-repl`:

```
nix-repl> pkgs.rustStable.rustc.version
"1.4.0"
```

though stable is `1.5.0` at the moment. I'd update myself, but I cannot find the appropriate place where the `rustc` package is located.

I'm on:

```
nixos-version
16.03pre73316.93d8671 (Emu)
```

**Comment by FRidh** [comment]
`rustc` has been updated in this repository, but the nixos-unstable channel hasn't updated yet.
See b26aa99d9dbda8ef5e83625d88977aedb63f7443
