### ISSUE TITLE
Add `fetchPijul`

### ISSUE THREAD

**Issue by locallycompact** [NixOS/nixpkgs#121526]
It would be nice to add pijul (https://pijul.com/) to the list of source controls that nix supports.

**Comment by shanesveller** [comment]
What are some motivating examples of software distributed via Pijul that you would like to see available through Nix/Nixpkgs?

**Comment by locallycompact** [comment]
Sort of a chicken and egg problem.

My use case is for libraries. I want to start using pijul exclusively for source control for projects I control, therefore pulling source via say niv would require a fetchpijul to exist somewhere and nixpkgs seemed like the most likely place.

It feels like a common theme that folks would be keen to use it over git if there were less friction and more integration options.

**Comment by matthewess** [comment]
Concrete use case: https://nest.pijul.com/GarettWithOneR/pijul-vscode

**Comment by matthewess** [comment]
Is there a good high level outline on what needs to happen for the fetching process? I might be open to taking a stab at this, but just reading through the fetchgit source unassisted was a tad intimidating, I thought.

Does there also need to be some work done in nix itself to support something like using Pijul for tracking what is included in a flake?

**Comment by 7c6f434c** [comment]
>Is there a good high level outline on what needs to happen for the fetching process? I might be open to taking a stab at this, but just reading through the fetchgit source unassisted was a tad intimidating, I thought.

fetchFossil sounds like a better starting point…
