### ISSUE TITLE
notbit: Error connecting to IPC socket: No such file or directory

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#12163]
After enabling the notbit daemon:
```
> notbit-keygen
Error connecting to IPC socket: No such file or directory
> notbit-sendmail 
Error connecting to IPC socket: No such file or directory
```

**Comment by jgillich** [comment]
It seems like notbit doesn't actually work with the current protocol version (https://github.com/bpeel/notbit/issues/9), so there is little incentive to fix this.

**Comment by mogorman** [comment]
shouldn't notbit be removed as its not compatible anymore and not being worked on?

**Comment by jgillich** [comment]
I'm not sure if it has any use currently, protocol v3 doesn't seem to be optional? @wkennington

**Comment by jgillich** [comment]
https://github.com/NixOS/nixpkgs/pull/12193
