### ISSUE TITLE
BreakTimer

### ISSUE THREAD

**Issue by Eris7090** [NixOS/nixpkgs#121600]
**Project description**
A nice program that will run and tell you when you need to take a break 

**Metadata**
* homepage URL: https://breaktimer.app/
* source URL: https://github.com/tom-james-watson/breaktimer-app
* license: gpl3
* platforms: Linux, Windows, Mac

**Comment by peterhoeg** [comment]
Running an electron app (and therefore a chrome instance) to get a reminder seems like overkill. You can achieve something similar by using ktimer (assuming you're using KDE) for a fraction of the memory.

Quick guide: https://blog.realhe.ro/improvised-pomodoro-technique-timer-on-kde-based-linux/

**Comment by davidak** [comment]
>ktimer

the ui looks very complicated

here are some simple timers we have already packaged

gnome-solanum
pomotroid

i don't think we need another timer app
