### ISSUE TITLE
linux 5.4.114 breaks HDMI output on Raspberry Pi 3

### ISSUE THREAD

**Issue by zseri** [NixOS/nixpkgs#121612]
**Describe the bug**
I updated my `nixpkgs/nixos-20.09´ flake input, which contained a kernel update, which broke HDMI output, e.g. nothing is displayed, uboot boot messages remain on HDMI output when booted, but interaction with the tty is possible, e.g. blind reboot works.

Linux kernel 5.4.114 doesn't work (dc326c78a93862efb30a76216f527a56496e6284), I tested it maybe 5 times and never had an output on HDMI from the kernel. This might be a bit fuzzy and nondeterministic, but I suppose whatever causes this got worse.

5.4.111 works most of the time (b2a189a8618fc1ba61593016fe5699b38971b89f), occasionally the monitor doesn't respond with the correct EDID data, and setting up the correct resolution fails.

see also: https://github.com/zseri/nixos-configs/commit/46f9b8b2426f02f38bd4cfec4de8e8ad13114e3e

**To Reproduce**
dunno. probably checking out the above mentioned commits, installing a system with `kernelPackages` taken at such commit on a RasPi3, then rebooting, should be able to replicate this. 

**Expected behavior**
HDMI output should work.

**Notify maintainers**
@thoughtpolice (according to `pkgs/os-specific/linux/kernel/manual-config.nix`)
@NeQuissimus (latest modifications)

**Metadata**
 - system: `"aarch64-linux"`
 - host os: `Linux 5.4.111, NixOS, 20.09.20210502.dc326c7 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - nixpkgs: `/etc/nix-flake-channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - linuxPackages.kernel
# a list of nixos modules affected by the problem
module:
```

**Comment by samueldr** [comment]
Which hardware variant? 3B or 3B+?

I see you traced it to (potentially) being an update between  5.4.111 and  5.4.114  on mainline.

Does it work better with the new LTS (5.10), or with the latest kernel (5.12 today)? Looks like 5.4.117 has been released, any changes? (Not yet updated in Nixpkgs AFAICT)

There may not be much we can do other than say "it's an upstream issue" or "it's hardware specific".

Though I'll be noting that we previously had people with *really hard to trace* issues with HDMI and Raspberry Pi 3B or 3B+, that ended up being specific to their setup. Even though it was a good working  setup, at some point it stopped working well and they had to change the HDMI cable. Unknown why. So it might also be a "YMMV" depending on the exact setup...

**Comment by bachp** [comment]
@zseri Does this still happen with more recent kernels? 5.10.x or 5.16.x?

**Comment by zseri** [comment]
I don't know, as my RasPi setup broke some time ago and I didn't have time to fix it.
