### ISSUE TITLE
Bubblemail update to 1.4 and adding avatar support [includes proposed nix changes]

### ISSUE THREAD

**Issue by barryfm** [NixOS/nixpkgs#121616]
The current bubblemail entry:
  pkgs/applications/networking/mailreaders/bubblemail/default.nix
is still at version 1.3 and and does not contain support for avatars.  This requires using the vala compiler and fixing some of the builtin paths.   I got everything working for me with the following nix derivation replacement:

[](url)https://gist.github.com/barryfm/b50dc60bdfad48fca5ca75736dc3126b

Although this is usually done through a pull request, it seem like overkill for a simple update, which will probably be updated before applying.

Comments by the maintainer @doronbehar requested.

**Comment by doronbehar** [comment]
I barely have time lately to maintain things. You can open a PR with anything you think is worth merging.

**Comment by JamieMagee** [comment]
Updated in #142556
