### ISSUE TITLE
No documentation for listings latex package

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#12174]
I would like to have documentation for the latex `listings`. Unfortunately, `texdoc` always fails:

```
$ texdoc listings
Sorry, no documentation found for listings.
```

I installed texlive with

```
texlive = texlive.combine {
  inherit (texlive) scheme-full;
};
```

**Comment by vcunat** [comment]
You first need to read the documentation for our `texlive` packaging ;-) https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L9-L18

**Comment by DamienCassou** [comment]
I already read it (several times :-)) and I thought it was inaccurate because `texdoc koma-script` worked and I didn't know `koma-script` was more *core* than `listings`. I also already tried the following and variants without success:

```
texlive = texlive.combine {
  inherit (texlive) scheme-full;
  pkgFilter = pkg: true;
};
```

**Comment by vcunat** [comment]
Does it not include path `/nix/store/2xy5im1j892qk2al1hwpwymzjba5dlx0-texlive-listings.doc-1.5e`? I *am* getting that installed into the TeX env when using just
```nix
{
texlive.combine {
    inherit (texlive) scheme-basic listings;
    pkgFilter = pkg: pkg.pname == "listings" || pkg.tlType != "doc";
  };
}
```

However, I've got no idea how texdoc works.

**Comment by DamienCassou** [comment]
> Does it not include path /nix/store/2xy5im1j892qk2al1hwpwymzjba5dlx0-texlive-listings.doc-1.5e?

I didn't have this path but now I have it with:

```
texlive = texlive.combine {
  inherit (texlive) scheme-full;
  pkgFilter = pkg: pkg.pname == "listings" || (pkg.tlType != "doc" && pkg.tlType != "source");
};
```

Thanks

**Comment by vcunat** [comment]
:-)
