### ISSUE TITLE
Add `osquery` package back

### ISSUE THREAD

**Issue by abvbv** [NixOS/nixpkgs#121745]
**Project description**

> osquery is a SQL powered operating system instrumentation, monitoring, and analytics framework. 
>
> osquery exposes an operating system as a high-performance relational database. This allows you to write SQL-based queries to explore operating system data.
>
> https://github.com/osquery/osquery

The project has been deleted from packages in this MR: https://github.com/NixOS/nixpkgs/pull/74081.

**Metadata**

* homepage URL: https://osquery.io/
* source URL: https://github.com/osquery/osquery
* license: Apache-2.0 and GPL-2.0
* platforms: Linux, macOS, Windows, and FreeBSD

**Comment by teto** [comment]
Looks like there is little interest, you are the first to mention it since 2019 so if you are not ready to maintain it, I wouldn't hold my breth.
