### ISSUE TITLE
nixos-rebuild does not apply UID/GID change when mutableUsers = false

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#12170]
Due to #11317, I changed the UID of nm-openvpn manually and later disabled `mutableUsers`. Now that the bug has been fixed, I'm getting this when I run nixos-rebuild:

```
warning: not applying GID change of group ‘nm-openvpn’
warning: not applying UID change of user ‘nm-openvpn’
```

**Comment by domenkozar** [comment]
That's because Nix doesn't know what files are owned by that user and so changing uid would break filesystem permissions.

**Comment by colemickens** [comment]
@domenkozar Can you advise on what a user should do to properly handle this situation?

**Comment by jgillich** [comment]
@colemickens Removing the entries manually from /etc/passwd and /etc/groups worked for me.

**Comment by colemickens** [comment]
Thanks @jgillich !

**Comment by CMCDragonkai** [comment]
I just got this, but I'm not understanding what the problem is here.

@jgillich Are you saying to remove the nm-openvpn entries in `/etc/passwd` and `/etc/group`?

**Comment by jgillich** [comment]
@CMCDragonkai Yes, nixos-rebuild will then re-add them.

**Comment by sbourdeauducq** [comment]
> @domenkozar Can you advise on what a user should do to properly handle this situation?

Besides the obvious ``chown`` required in ``/home``, ``/nix/var/nix/profiles/per-user`` also needs fixing up. Are there other places?
Handy command: ``for d in *; do chown -R $d $d; done``
It's still too easy to hose your system (https://github.com/NixOS/nixpkgs/issues/60732) so let's document how to recover from this.

**Comment by sbourdeauducq** [comment]
Also ``/nix/var/nix/gcroots/per-user``

**Comment by l0b0** [comment]
So basically this?

```
sudo sed -i -e '/^GROUP:/d' /etc/group
sudo find / -gid OLD_GID -exec chgrp NEW_GID {} +
sudo nixos-rebuild switch
```
