### ISSUE TITLE
I'm walking away from the project

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#121769]
Hello NixOS people (and other possible readers) on GitHub. Recently I have made the decision to walk away from the NixOS project. If you're interested personally you can read about that in length here: https://discourse.nixos.org/t/walking-away-from-the-project/12320. I thought it would be a good idea to say goodbye here as well. As for the reason, I don't think I have the heart to reiterate here. What I had with all of you here was really unique, strange, and unusual. All of my favorite things. I really wish you all the best. I'm realizing that, in my short time with NixOS, I interacted with a lot of people. If I've personally been helpful to you in any way, this would be the place to say your goodbye and thanks ✨ I always watch from the stars (and can read the ones and zeros).

Onto the technical side of leaving the project... Everything I did maintain is now abandoned. It makes sense since I won't be using NixOS anymore. So this is a call for a new maintainer for Pantheon, and anything else that I maintained. Everything I've done here is given freely to you, and anyone who will graciously accept it. To detail the state of Pantheon in NixOS, it's very good in my opinion. I've upstreamed all (I think?) of my downstream patches, and we have the very helpful GNOME maintainers to assist you (if one of them doesn't choose to maintain it).  I collaborated with @jtojnar for its initial packaging, so he'd also be a great help.
And elementary OS 6 comes out soon, so it will be needing updating if everyone decides it should remain a part of nixpkgs.

And also, on that note, bye @jtojnar 👋 . We did a lot of great work together over these years for GNOME&Freedesktop&etc. stuff. I'm very pleased with what was accomplished. Oh, and lastly, which character from Kanon is your avatar! 😁 

👋 Bye @NixOS/nixpkgs-committers. I hope I took good care of everyone.

Warmth 🔥,
WORLDofPEACE

**Comment by worldofpeace** [comment]
Noticing that u saw my goodbye on discourse @jtojnar, so I guess this will be a reminder. But I will say it again here, really thank you. My interest in NixOS was "rocket boosted" by you. Because of your detailed reviews and incredibly helpful advice etc. It was all really valuable to me. Intellectually stimulating, and I guess we could say an essence of playfulness from just being some NixOS hackers. Most of all it was fun ✨

**Comment by arianvp** [comment]
Best of luck of any of your other endeavours in life.My our paths cross
again!

Was a pleasure bumping into you. Always kind and willing to help me with my
obscure gnome problems in #nixos.

**Comment by AndersonTorres** [comment]
Until we meet again later, @worldofpeace ! And thanks for the megabytes!

**Comment by jtojnar** [comment]
I do not think there has been anyone in the community, who has not benefited from your help. If not directly, then at least indirectly through your work or the work you helped other people with. And just your *presence* made the space warmer – something every tech space could have more.

I can confirm that Pantheon in NixOS is in excellent shape and while I do not have the capacity to adopt it, I will do my best to support whoever decides to step up to maintain it.

I will also continue on our shared vision for @NixOS/freedesktop team, adding more packages and writing more documentation so that the desktop core is maintained more consistently. Any help will be appreciated as this initiative is somewhat neglected in favour of other duties.

---

uguu, everyone forgets Ayu, uguu

**Comment by AndersonTorres** [comment]
(And this is the part we take the loot! Yarr!)

**Comment by danieldk** [comment]
Thanks for everything @worldofpeace ! Our paths haven't crossed a lot in nixpkgs, but I have learned a lot from your interactions in the project and of course benefited from everything you contributed. All the best in what life brings you next!

**Comment by wmertens** [comment]
Thanks, @worldofpeace. I am happy to have experienced your presence during NixCon, you really made a world of difference. May you find lots of happiness in life, and maybe one day get a yearning for returning :)

**Comment by mkg20001** [comment]
@worldofpeace Without you I would never have been able to make the cinnamon desktop a thing. Thanks for all the help!

**Comment by vcunat** [comment]
On a more practical not, @worldofpeace you want to be removed from `meta.maintainers` lists so people mention you less in future?

**Comment by worldofpeace** [comment]
> 
> 
> On a more practical note, @worldofpeace you want to be removed from `meta.maintainers` lists so people mention you less in future?

Yeah, I would like to be removed from `meta.maintainers` etc, I think there's other attributes for `teams` as well. Overall, me being @`ed isn't going to be a problem because I can just mute github notifications.

**Comment by NickHu** [comment]
I remember you initiated the mammoth undertaking of updating fontconfig, so thank you for that. All the best for you future endeavours!

**Comment by bryanasdev000** [comment]
Newbie speaking, I saw countless commits of yours and I thank you for the care and time invested in the project.

Good luck in everything.

**Comment by lovesegfault** [comment]
Thanks for everything @worldofpeace! Best of luck in whatever comes next for you!

**Comment by jonringer** [comment]
Thanks for all your work, and my mentor Release Manager :)

**Comment by yegortimoshenko** [comment]
Thank you so much for everything, @worldofpeace! <3

**Comment by ttuegel** [comment]
@worldofpeace Thank you for all your hard work, especially getting the release team organized! I've been here a long time, but your efforts made me feel more like part of a community. You will be missed!

**Comment by benley** [comment]
Thank you @worldofpeace! Your contributions have helped me on many occasions and we've been very fortunate to have you as part of our community.

**Comment by domenkozar** [comment]
Thank you a thousand times @worldofpeace for all your kind words, community help, and contributions.

I hope you will still visit us at IRL NixCon, so that we can thank you in person.

**Comment by Mic92** [comment]
Nothing actionable to do in this matter anymore. Cheers.
