### ISSUE TITLE
Content addressed mailutils fails to build

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#121813]
**Describe the bug**

After switching my NixOS configuration to use `contentAddressedByDefault = true;` the rebuild failed at rebuilding `mailutils`.
Trying to rebuild again (continuing at `mailutils` again) caused the same issue.

Tried `nix-build --experimental-features 'ca-references ca-derivations nix-command' -A mailutils` after setting `__contentAddressed = true;` in my local nixpkgs clone, and that has worked without errors.

I've uploaded the log of `nix-build` to https://gist.github.com/SFrijters/a4feb2f618c1cc4281e77782fb78a293 . ~The `nixos-rebuild` has triggered a rebuild of other packages so I don't have a failing log available (yet).~
EDIT: gist updated with nixos-rebuild log. Looks like there is a difference / error in the `guile-tools` detection.

@regnat has been able to reproduce this (non-deterministically), so I'm curious what his easy reproducer is.

**To Reproduce**
1. Easy reproducer TBD

**Expected behavior**
Package should build.

**Additional context**

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/y2g5n52pljrmi7sy771njs1s8n58fjz3-bash-interactive-4.4-p23-dev
copying path '/nix/store/y2g5n52pljrmi7sy771njs1s8n58fjz3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.14, NixOS, 21.05.20210504.8a249aa (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(frijters): `""`
 - channels(root): `"nixos, nixos-unstable-20.09pre225264.683c68232e9"`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
    - mailutils
# a list of nixos modules affected by the problem
module:
```

**Comment by regnat** [comment]
I’m not sure of why exactly this causes the subsequent errors, but 

> mailutils> ;;; note: source file /nix/store/khmdhnv5yanj18800x3v3lj7psx9bf5s-guile-2.2.7/share/guile/2.2/ice-9/eval.scm
> mailutils> ;;;       newer than compiled /nix/store/khmdhnv5yanj18800x3v3lj7psx9bf5s-guile-2.2.7/lib/guile/2.2/ccache/ice-9/eval.go

is a direct consequence of https://github.com/NixOS/nix/issues/4775 .

> @regnat has been able to reproduce this (non-deterministically), so I'm curious what his easy reproducer is.

My reproducer is simply `nix build github:regnat/nixpkgs/everything-ca#mailutils` (where the `everything-ca` flake is `nixos-unstable` with `contentAddressedByDefault = true;`).

The reason why it wasn’t deterministic for me is that the second machine in which I tried to build it had the first one as a substituter, so the `guile` derivation hadn’t been built locally but had been fetched − and as such wasn’t affected by NixOS/nix#4775 .

**Comment by SFrijters** [comment]
Didn't realize there was a targeted fix in the nix repo yet, but I've attempted to rebuild my system again with `contentAddressedByDefault = true;` and without any substituters. Took about 36h, but rebuilding the world worked this time.
