### ISSUE TITLE
Allow Firefox telemetry

### ISSUE THREAD

**Issue by raptortech-js** [NixOS/nixpkgs#121826]
I would like Firefox to send telemetry to Mozilla, so that my use case is counted in their analysis, but I don't want to make a custom Firefox build. This is currently impossible. Firefox says "Data reporting is disabled for this build configuration." I don't particularly care whether telemetry is on by default or not, but I'm frustrated that I'm forbidden from turning it on.

**Comment by Mindavi** [comment]
It doesn't seem like it's been disabled on purpose. But maybe there's some option, you'd have to look upstream. Not sure how much people _want_ to enable it though, so I'd definitely not make it a default (I don't want it opt-out, I want it opt-in). Maybe there's a way to enable / disable it at runtime though.

**Comment by raptortech-js** [comment]
This does work, thank you! Though it appears Mozilla would prefer that telemetry be turned on even for unofficial builds:
> "You can't complain to us that we broke your use case when you turned off telemetry. How were we supposed to know? I'm talking to you, just about every major Linux distribution." https://twitter.com/MikeKaply/status/1389989011440250887?s=20

**Comment by buckley310** [comment]
After some detective work:
The librewolf browser seems to set `MOZ_TELEMETRY_REPORTING` to `0` at build time. The mozilla docs indicate that if this variable is not defined at build time will disable telemetry. So seems like every distribution needs to specifically enable this option for telemetry to work for their builds. Will test this later...

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=librewolf
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/internals/preferences.html

**Comment by buckley310** [comment]
Looks like this variable alone is not sufficient. Compiling with it doesn't make a difference.

**Comment by buckley310** [comment]
This works though https://github.com/buckley310/nixpkgs/commit/012fb27bc3815f4abb8371bb42c36e9eda242597

I'm not sure what the significance of `MOZILLA_OFFICIAL` is, or if Mozilla wants to sign-off on each distro using it.

**Comment by mkaply** [comment]
Thanks for looking into this. I think MOZILLA_OFFICIAL is poorly named and I'm checking into it.

**Comment by mkaply** [comment]
So you definitely should be setting MOZILLA_OFFICIAL. It basically means "not a developer built build"
Our official builds don't set MOZ_TELEMETRY_REPORTING, but telemetry is still reported. I'm investigating why.

**Comment by buckley310** [comment]
I will test this again with a smaller diff https://github.com/buckley310/nixpkgs/commit/1530672d9f3c580216adb84c9e23e10dddc18857

**Comment by buckley310** [comment]
Yep, that works. All that is needed is the MOZILLA_OFFICIAL variable.

**Comment by mkaply** [comment]
Yes MOZILLA_OFFICIAL sets MOZ_TELEMETRY_REPORTING

We also discovered another one you should set  - MOZ_REQUIRE_SIGNING=1

We're working to make sure that gets set with MOZILLA_OFFICIAL as well

And please don't copy librewolf :)

**Comment by buckley310** [comment]
Hmmm, so which takes priority if MOZ_REQUIRE_SIGNING=1, but policies.json tries to install a local unsigned extension? NixOS has native support for configuring Firefox policies, and it wouldn't surprise me if building extensions from source and applying them was a desired feature.

**Comment by mkaply** [comment]
Unsigned extensions are not supported in official Firefox builds (by policy or any other means)

There should be no reason to install an unsigned extension. You can use AMO to sign the extension and choose not to have it published.

**Comment by Mindavi** [comment]
Pretty sure there is at least some people that want to package extensions in nixpkgs, which may or may not require allowing to load unsigned extensions / addons. Maybe it would be good to sign them then using AMO, but I don't think the workflow of installing unsigned extensions should be broken without giving a (good) alternative.

https://github.com/NixOS/nixpkgs/pull/91724/files

Note that I found this with a quick search, haven't really looked into this deeply -- maybe there actually isn't any requirement to load unsigned extension, but please consider this carefully and don't break other nix users's expectations without discussing.

**Comment by buckley310** [comment]
Yeah, so since the from-source nature of nixpkgs can extend all the way into the browser extensions, it seems like MOZ_REQUIRE_SIGNING is incompatible with that. All the builds run in a sandbox and cannot reach the internet to get signed or anything.

**Comment by mkaply** [comment]
I think I'm fine on punting on MOZ_REQUIRE_SIGNING for now.

MOZILLA_OFFICIAL is the important one.

**Comment by buckley310** [comment]
The above PR should fix this issue.

**Comment by buckley310** [comment]
This fix has been applied and the change has now hit the unstable and 21.05 channels.
