### ISSUE TITLE
GHC 8.6.5 binary source URL has changed

### ISSUE THREAD

**Issue by mode89** [NixOS/nixpkgs#121804]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: ghc

current version:
desired version:

###### Notify maintainers

maintainers: @MarcWeber @peti 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by mode89** [comment]
Today I tried to install `ghc-8.10.4`, but it failed at downloading `ghc-8.6.5-x86_64-fedora27-linux.tar.xz`: complained about hash mismatch. It seems like URL has changed.

**Comment by mode89** [comment]
I used the following overlay as a workaround:
```nix
let
  overlay = self: super:
    let
      ghc865 = super.haskell.compiler.ghc865Binary;
    in {
      haskell = super.haskell // {
        compiler = super.haskell.compiler // {
          ghc865Binary = ghc865.overrideAttrs (old: {
            src = ghc865.src.overrideAttrs (old2: {
              urls = [
                "https://downloads.haskell.org/ghc/8.6.5/ghc-8.6.5-x86_64-fedora27-linux.tar.xz"
              ];
            });
          });
        };
      };
    };
  pkgs = import <nixpkgs> { overlays = [ overlay ]; };
in
  pkgs.ghc
```

**Comment by sternenseemann** [comment]
Should work with #122005.
