### ISSUE TITLE
Update Pantheon to version 6

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#121847]
## Issue description

The elementary OS 6 Beta was released on Fri, Apr 30, 2021.

https://blog.elementary.io/elementary-os-6-odin-beta/

We could update the packages in a branch to test it out.

Alternatively, we can wait until it is released, so we don't have to update everything twice.

cc @NixOS/pantheon

**Comment by bobby285271** [comment]
Will be glad if I can help :-)

I am trying to do some upgrades, shall I target these PR to `master` or another branch?

---

A screenshot of the new `switchboard-plug-about` //  hooray!

![2021-07-16 22-20-52 的屏幕截图](https://user-images.githubusercontent.com/20080233/125962664-a3d03aee-a6ba-4332-8131-148657c50527.png)

**Comment by davidak** [comment]
Awesome!

@bobby285271 if it does not break the desktop for existing users and does not lead to rebuild of thousands of packages, master is fine. If it rebuilds more than 1000 packages, use staging.
