### ISSUE TITLE
Form Pantheon maintainers team

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#121827]
## Issue description

Since @worldofpeace is leaving (https://github.com/NixOS/nixpkgs/issues/121769), the Pantheon desktop in NixOS is now unmaintained.

I was using the Pantheon desktop before NixOS und i wouldn't want to use a computer without the combination of both. So i care a lot that they continue to exist.

I suggest to create a _Pantheon maintainers team_ with at least 2 people who are committed to maintain it.

So if you are a Pantheon user, consider to contribute to this effort!

I don't have the time and knowledge for this commitment, but i can support with updating existing packages.

Please leave a :+1:  if you care about Pantheon in NixOS, so we know how relevant it is!

## Technical details

There is a label with all known issues ([6.topic: pantheon](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%226.topic%3A+pantheon%22)) and a kanban board ([Pantheon](https://github.com/NixOS/nixpkgs/projects/21)).

Since i have the rights, i created the team @NixOS/pantheon. Hope that is OK.

- [X] Create GitHub Team
- [x] Create team in `maintainers/team-list.nix` (https://github.com/NixOS/nixpkgs/pull/121829)
- [x] 1. Maintainer
- [ ] 2. Maintainer

**Comment by dotlambda** [comment]
> I don't have the time and knowledge for this commitment, but i can support with updating existing packages.

You should still consider being part of that team. Having someone to test a change is already worth a lot!

**Comment by worldofpeace** [comment]
There's also specific code in elementary repositories that I maintained. session-settings and default-settings IIRC. @danrabbit just went to mention here that I'm also leaving the elementary org, but the code in elementary and such will be passed down to a new maintainer for NixOS in elementary.

**Comment by danrabbit** [comment]
@worldofpeace I'm sorry to hear that you're stepping down! Your contributions have been greatly appreciated. Good luck in your future endeavors :)
