### ISSUE TITLE
texlive.combined.scheme-full: texlive-aalok-0.2': No such file or directory

### ISSUE THREAD

**Issue by feijoas** [NixOS/nixpkgs#121885]
**Describe the bug**
On unstable, the package `texlive.combined.scheme-full` cannot be installed. If fails with 

`error: getting attributes of path '/nix/store/xd1jx5x3835wz17y8rh6qx2vm92x73i1-texlive-aalok-0.2': No such file or directory`

**To Reproduce**
```
environment.systemPackages = with pkgs; [
    texlive.combined.scheme-full
];
```
`sudo nixos-rebuild --upgrade test`

**Additional context**
I worked before the upgrade.

**Notify maintainers**
@vcunat  @jwiegley

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.107, NixOS, 21.05pre285574.8e4fe32876c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre287001.39e6bf76474"`
 - channels(mschneider): `"home-manager"`

**Comment by veprbl** [comment]
@feijoas Try doing `nix-store --repair-path /nix/store/xd1jx5x3835wz17y8rh6qx2vm92x73i1-texlive-aalok-0.2`

**Comment by feijoas** [comment]
@veprbl Thanks that worked. It was part of a bigger problem as described in https://github.com/NixOS/nix/issues/1281
