### ISSUE TITLE
Recompute all cargoSha256/cargoHash

### ISSUE THREAD

**Issue by danieldk** [NixOS/nixpkgs#121994]
**Describe the bug**

Rust 1.50.0 incorporated a Cargo change (https://github.com/rust-lang/cargo/pull/8937) in which `cargo vendor` erroneously changed permissions of vendored crates. This was fixed in Rust 1.51.0 (https://github.com/rust-lang/cargo/pull/9131). Unfortunately, this means that all `cargoSha256`/`cargoHash`es produced during the Rust 1.50.0 cycle are potentially broken.

The long-term solution for this issue is that we should probably apply our own normalization for permissions (#121259). But first, we should check/update `cargoSha256`/`cargoHash` tree-wide.

**Comment by dotlambda** [comment]
Couldn't we apply the patch from https://github.com/rust-lang/cargo/pull/9131 to our cargo?

**Comment by danieldk** [comment]
> We have 1.51.0, but some hashes were computed with 1.50.0.

Indeed. One of my machines is currently recomputing all the hashes. So hopefully I'll be able to do a PR later today.

**Comment by jonringer** [comment]
#122016 has been merged
