### ISSUE TITLE
`nix-shell -A ocamlPackages.X` doesn't work if `X` contains `createFindlibDestdir = true`

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#121991]
**Describe the bug**

Any package depending on `findlib` and which sets `createFindlibDestdir = true` will trigger the following line of the setup hook:
https://github.com/NixOS/nixpkgs/blob/fc8162a69bafc6d71a53c35c6470ee57ece4c66d/pkgs/development/tools/ocaml/findlib/default.nix#L42

Unfortunately, this setup hook is also called when running `nix-shell -A`. This makes the latter unusable, even though this is one of the essential features of NIx.

If you have already built the derivation for a given package, then the directory will already be there and you won't notice the error.

**To Reproduce**

Take a derivation you have not built locally, which depends on `findlib` and sets `createFindlibDestdir = true` and run `nix-shell -A`. E.g., `nix-shell -A ocamlPackages.process`.

It fails with: `mkdir: cannot create directory ‘/nix/store/wa3qhw038klf5fqnhndgzpchvqj0awn4-ocaml4.10.2-process-0.2.1’: Read-only file system`.

**Additional context**

We initially detected this problem with @CohenCyril when working with the Coq derivation. But we are not the first ones to notice it. For instance, @vbgl mentioned the problem in 2018: https://github.com/coq/coq/pull/8602#discussion_r222996538.

I'm self-assigning because there is an easy "quick fix", which is to allow `mkdir` to fail, and I will open a PR with it.

**Comment by sternenseemann** [comment]
Fixed via a3ab43d3a45338f845a0f8a12ed34e84c8b79dae. Note that running `configurePhase` will be problematic now, though.
