### ISSUE TITLE
Add dgoss

### ISSUE THREAD

**Issue by Hyzual** [NixOS/nixpkgs#121929]
**Project description**
This is a follow-up to issue #121496 goss.

`dgoss` is a bash script wrapper for `goss`. It helps install and run `goss` inside docker containers and together with `goss` it's very handy to run continuous integration tests when building docker images. For example it lets you build a docker image, run a container with it and validate that the image works as expected, that files have the right permission / mode, that some port is open, that some command gives the expected result, etc. `dgoss` is maintained and released from the same Github repo as `goss`.

I have tried packaging it but since it's a bash script and it's only my second contribution to nixpkgs, I'm having a hard time. I've tried using `pkgs.resholvePackage` to replace references to commands, such as `cp`, `chmod` and so on. `dgoss` relies on a `GOSS_PATH` environment variable and falls back on `which goss` to locate the `goss` binary. I imagine in nixpkgs we could replace this line and "hardcode" `goss` as a dependency of `dgoss`. However, I was not able to do so. I need your help :sweat_smile: :pray: 

Here is my attempt so far: https://github.com/Hyzual/nixpkgs/blob/5fab7908d23bde034688ef1331ca21acfcb4ee78/pkgs/tools/misc/dgoss/default.nix

**Metadata**

* homepage URL: https://github.com/aelsabbahy/goss/tree/master/extras/dgoss
* source URL: https://github.com/aelsabbahy/goss/blob/master/extras/dgoss/dgoss
* license: Apache License 2.0 (`asl20`)
* platforms: From the README it looks like it's linux and Darwin

**Comment by abathur** [comment]
In the long run resholve may directly patch things like `which` but for now the best way to handle the GOSS_PATH _with_ resholve would probably be supplying a prologue that sets GOSS_PATH.

As an aside, I wondered a bit about this being a separate package from goss. At least in the source, it looks like install.sh will install both? Are you separating them for some reason directly related to goss/nixpkgs, or just to work around the awkwardness of resholve's package-oriented nix API?

**Comment by Hyzual** [comment]
Hi, thanks for the help, I'll try that out :)
About the package being separate from goss, honestly I don't know :sweat_smile:. It wasn't to work around resholve's nix API, I just figured that since it was a separate binary, it had to be a separate package in nixpkgs.

**Comment by Hyzual** [comment]
I've made [some progress](https://github.com/Hyzual/nixpkgs/tree/add-dgoss), `dgoss` functions but there seems to be a problem with `goss` now. `dgoss` will mount the `goss` binary in the docker container and runs commands on it.

```sh
$ dgoss run docker-koel_koel:latest
INFO: Starting docker container
INFO: Container ID: b3f922af
INFO: Sleeping for 0.2
INFO: Container health
INFO: Running Tests
sh: 1: /goss/goss: not found
INFO: Deleting container
$ echo $?
127
```
I don't really understand the "not found" error but I've read that it can happen when a program is dynamically linked and does not find one of its dependencies
```sh
$ file /nix/store/dfwlbfmiv0gwirgv8fg30q9khgklyj0a-goss-0.3.16/bin/goss
/nix/store/dfwlbfmiv0gwirgv8fg30q9khgklyj0a-goss-0.3.16/bin/goss: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/ld-linux-x86-64.so.2, Go BuildID=aYb05wBua2MWAlvNR52x/TV6N7fhSNIQQnkBNObZX/3iT2WkMy91fJ8iqPNTp-/wTvHO2ox7EijsFLuix5X, stripped
```

**Comment by Hyzual** [comment]
I needed to fix the `goss` packaging (which was building the dynamically linked binary). `dgoss` works, thanks for the help @abathur. I'll wait for the `goss` PR to be merged before pushing one for `dgoss`

**Comment by abathur** [comment]
@Hyzual Can you bring up the question about whether dgoss should be separate or not in the other report? I'm not sure what the razor should be. One thought is to track whatever the other repos are doing. Per https://repology.org/project/goss/versions it looks like they both include dgoss, but one also includes kgoss and dcgoss.

**Comment by 06kellyjac** [comment]
goss is commonly used on its own in containers and other environments where you'd want minimal dependencies so I'm more inclined to package them separately rather than have people use overlays on goss to remove them
