### ISSUE TITLE
r8125 ethernet driver

### ISSUE THREAD

**Issue by trevorriles** [NixOS/nixpkgs#122029]
**Project description**
Package the r8125 ethernet driver.

**Metadata**

* homepage URL: https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software
* source URL: https://github.com/trevorriles/r8125
* license: gpl2
* platforms: linux

**Comment by chrissound** [comment]
This seems to be solved/fixed here: https://github.com/NixOS/nixpkgs/blob/79ea4b7e4911d95bd4ac3a88b5dc47c945dc3086/pkgs/os-specific/linux/r8125/default.nix

However I'm not sure how to include it in my nixos config. According to `lsmod | grep r8125` returning nothing makes me believe it's not there by default?

**Comment by chrissound** [comment]
```
  boot.kernelPackages = pkgs.linuxPackages_5_4;
  boot.extraModulePackages = with config.boot.kernelPackages; [ r8125 ];
```

I had to use 5.4 kernel as it's broken for 5.5 according to https://github.com/NixOS/nixpkgs/pull/85669#issuecomment-621265172
