### ISSUE TITLE
pythonPackages.rich: out of date

### ISSUE THREAD

**Issue by alex-eyre** [NixOS/nixpkgs#122048]
###### Motivation
I would be happy to update this and submit a PR myself, but MacOS has other plans and I'm having some issues getting the tests to work due to some allegedly missing python files.
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: rich

current version: 9.13.0
desired version: 10.1.0

###### Notify maintainers

maintainers: @risicle

**Comment by risicle** [comment]
See #121732.

A bit unfair to expect you to find that tbh.

**Comment by risicle** [comment]
Oh and we'd appreciate a darwin tester in that PR...

**Comment by alex-eyre** [comment]
No problem I'm glad it's been caught, I tried to look I promise, and I'm more than willing to be a Darwin tester!
