### ISSUE TITLE
ZERO Hydra Failures 21.05

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#122042]
## Update
**I have updated the steps to reflect the new backport workflow. Please review, if not familiar with the process.**

## Mission
Every time we branch off a release we stabilize the release branch.
Our goal here is to get as little as possible jobs failing on the trunk/master jobsets.
I'd like to heighten, while it's great to focus on zero as our goal, it's essentially to 
have all deliverables that worked in the previous release work here also.

**NOTE:** ZHF for this release will be significantly different from past ZHFs, with the
changes included in [RFC 85](https://github.com/NixOS/rfcs/blob/master/rfcs/0085-nixos-release-stablization.md).
Most significantly, branch off will occur on May 21st; prior to that date, ZHF will be conducted
on master; after that date, ZHF will be conducted on the release channel using a backport
workflow similar to previous ZHFs.

## Jobsets
[trunk Jobset](https://hydra.nixos.org/jobset/nixpkgs/trunk) (includes linux, darwin, and aarch64-linux builds)
[nixos/combined Jobset](https://hydra.nixos.org/jobset/nixos/trunk-combined) (includes many nixos tests)

## How many failing jobs are there?
At the opening of this issue we have the main `x86_64-linux` jobset at [**643**](https://hydra.nixos.org/eval/1668017?filter=x86_64-linux&compare=1667845&full=#tabs-still-fail) failing jobs, `x86_64-darwin` at [**1251**](https://hydra.nixos.org/eval/1668134?filter=x86_64-darwin&compare=1668069&full=#tabs-still-fail), and `aarch64-linux` at [**1067**](https://hydra.nixos.org/eval/1668134?filter=aarch64-linux&compare=1668069&full=#tabs-still-fail).

Thanks to [nix-review-tools](https://github.com/nix-community/nix-review-tools) we know which dependencies are causing the most jobs to fail in these individual jobsets:

- [nixos/release-21.05](https://shells.darmstadt.ccc.de/~hexa/1673059.html)
- [nixos/release-21.05-aarch64](https://shells.darmstadt.ccc.de/~hexa/1673054.html)
- [nixpkgs:nixpkgs-21.05-darwin](https://shells.darmstadt.ccc.de/~hexa/1673137.html)
- [nixpkgs/staging-next-21.05](https://shells.darmstadt.ccc.de/~hexa/1672799.html)

### Previous releases first evals
[19.09](https://hydra.nixos.org/eval/1541512) had **1654** failing jobs
[20.03](https://hydra.nixos.org/eval/1570712) had **1204** failing jobs
[20.09](https://hydra.nixos.org/eval/1570712) had **1153** failing jobs
[21.05](https://hydra.nixos.org/eval/1668017?filter=linux&compare=1667845&full=#tabs-still-fail) had **789** failing jobs
So we're actually getting better at maintaining a more stable "unstable" channel.

## How to help (textual)
1. Select an evaluation of the [trunk jobset](https://hydra.nixos.org/jobset/nixpkgs/trunk)
![Screenshot](https://user-images.githubusercontent.com/7673602/117478795-701baa00-af14-11eb-8a82-8a846b464cce.png)

2.  Find a failed job ❌️ , you can use the filter field to scope packages to your platform, or search for packages that are relevant to you.
![Screenshot from 2020-02-08 15 26 47](https://user-images.githubusercontent.com/28888242/74192277-3978b600-4c23-11ea-9f35-19a3988dd502.png)

3. Search to see if a PR is not already open for the package. It there is one, please help review it.

4. If there is no open PR, troubleshoot why it's failing and fix it.

5. Create a Pull Request with the fix targeting master, wait for it to be merged. 
If your PR causes around 500+ rebuilds, it's preferred to target `staging` to avoid compute and storage churn.

6. After your PR to master or staging has occured. Please follow [backporting steps](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes) and target the `release-21.05` branch if the original PR landed in `master` or `staging-21.05` if the PR landed in `staging`. Be sure to do `git cherry-pick -x <rev>` on the commits that landed in unstable. I created [a video covering the backport process](https://www.youtube.com/watch?v=4Zb3GpIc6vk&t=520s).

Always reference this issue in the body of your PR:
```
ZHF: #122042
```

Please ping @NixOS/nixos-release-managers on the PR.
If you're unable to because you're not a member of the NixOS org please ping @jonringer

## How can I easily check packages that I maintain?
You're able to check failing packages that you maintain by running:
```
# from root of nixpkgs
nix-build maintainers/scripts/build.nix --argstr maintainer <name>
```

## New to nixpkgs?
I created some videos to help get people started with nixpkgs:
- [Packaging a basic C application](https://www.youtube.com/watch?v=LiEqN8r-BRw)
- [Python nix packaging](https://www.youtube.com/watch?v=jXd-hkP4xnU)
- [Adding a package to nixpkgs](https://www.youtube.com/watch?v=fvj8H5yUKu8)

Also be sure to check out other resources at: https://github.com/nix-community/awesome-nix

## Packages that don't get fixed
The remaining packages will be marked as broken before the release (on the failing platforms).
You can do this like:
```nix
meta = {
  # ref to issue/explanation
  # `true` is for everything
  broken = stdenv.isDarwin; 
};
```

## Closing
This is a great way to help NixOS, and it is a great time for new contributors to start their nixpkgs adventure.  :partying_face: 

cc @NixOS/nixpkgs-committers @NixOS/nixpkgs-maintainers

## Related Issues
- Timeline: [Discourse: 21.05 Release Timeline](https://discourse.nixos.org/t/21-05-release-schedule/12528)
- Feature Freeze Items: ##121972

**Comment by fgaz** [comment]
This was useful in the previous ZHFs, so I'm going to repeat it here too:
To build all packages which have you as maintainer, run `nix-build maintainers/scripts/build.nix --argstr maintainer fgaz` (adjust the maintainer name to yourself)

**Comment by Ma27** [comment]
just figured that it might make sense to pin this for easier discoverability :)

**Comment by jonringer** [comment]
@NixOS/release-engineers would you all be okay with me changing the working to have you all pinged for each ZHF PR. I don't want to overload individuals

**Comment by uri-canva** [comment]
https://github.com/NixOS/nixpkgs/pull/122138 fixes `backblaze-b2` on darwin (commenting here because that's not obvious from the commit message, in case someone is searching the issue to make sure they're not picking up breakages that have already been addressed).

**Comment by roberth** [comment]
You can help out with linting and testing the NixOS tests (replacing the formatter-based "linting"). For instructions and progress tracking, see  https://github.com/NixOS/nixpkgs/pull/122201#issuecomment-835426167

**Comment by polygon** [comment]
How would you filter on hydra for two criteria at once?

Say, I want to search for all failures of Python packages on x86_64-linux. Searching for `python` and `x86_64-linux` separately does work as expected. But I cannot seem to figure out how to search for two keywords at once.

I tried `python x86_64-linux`, `python*x86_64-linux`, `python.*x86_64-linux`, `python and x86_64-linux`, `python AND x86_64-linux`, `python, x86_64-linux`. None of these seemed to yield any results. Is this possible at all, what is the search field capable of?

**Comment by risicle** [comment]
Has anyone done an analysis of which fixed packages would fix the most depending packages? Might help us prioritize..

**Comment by Synthetica9** [comment]
risicle: there is a tool for that, can't find it atm tho

**Comment by mweinelt** [comment]
> Has anyone done an analysis of which fixed packages would fix the most depending packages? Might help us prioritize..

master https://shells.darmstadt.ccc.de/~hexa/eval-1669635.html

**Comment by risicle** [comment]
@mweinelt no darwin? :cry:

**Comment by vcunat** [comment]
Some darwin-specific issues are on staging-next (listed above) 😉

**Comment by mweinelt** [comment]
> @mweinelt no darwin? cry

Added!

**Comment by rmcgibbo** [comment]
> Has anyone done an analysis of which fixed packages would fix the most depending packages? Might help us prioritize..

I use https://github.com/nix-community/nix-review-tools, which produces a list of packages sorted by the number of failed dependent packages.

**Comment by jonringer** [comment]
@mweinelt I think the reports are beneficial enough to have as part of the top-level post. You're free to edit it to include updated reports if you would like.

**Comment by mweinelt** [comment]
> @mweinelt I think the reports are beneficial enough to have as part of the top-level post. You're free to edit it to include updated reports if you would like.

Done!

**Comment by superherointj** [comment]
I have fixed firebird package (for some time now):
https://github.com/NixOS/nixpkgs/pull/121546
I wonder if it fits or not.

**Comment by jonringer** [comment]
@NixOS/release-engineers final round of staging-next has started for ZHF, and 1/3 of the builds have been completed. Please look for any new regressions: https://hydra.nixos.org/jobset/nixpkgs/staging-next

PR: #123279
Hydra Jobset: https://hydra.nixos.org/jobset/nixpkgs/staging-next

**Comment by jonringer** [comment]
Also, the last `staging-next` cycle introduced a few regressions as well.

https://hydra.nixos.org/eval/1670495#tabs-now-fail

**Comment by jonringer** [comment]
`release-21.05` has been created, and branch-off has occurred. ZHF will now transition to a backports workflow.

I have updated the original post with guidance on how to do a backport.

One week til release (assuming nothing catastrophic happens).

**Comment by jonringer** [comment]
Fixes can always be backported. Going to close this for now, as the release has already happened.

Thank you everyone for your hard work! :)
