### ISSUE TITLE
eukleides: (How) is mktexlsr(.pl) in texlive supposed to be invoked?

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#122118]
## Issue description

While looking into the `eukleides` package for ZHF, it looks like the build has started failing after the texlive update from 2019 to 2020.

In its Makefile, `eukleides` calls mktexlsr, which, in texlive-2019, is on the PATH and lives below the `texlive-combined-2019` store directory.
However, in texlive-2020, `mktexlsr.pl` resides in a separate `texlive-texlive-scripts-56579` directory.
Is this script supposed to be called from other derivations, or would that not work with the way Nix handles TeX anyway?
If it should work, how can I access the right path from another derivation?

@veprbl

**Comment by veprbl** [comment]
If you are using `texlive.combine`, the mktexlsr will be called from
https://github.com/NixOS/nixpkgs/blob/c397682663b586529838794c87ce0293cff8eda4/pkgs/tools/typesetting/tex/texlive/combine.nix#L201
https://github.com/NixOS/nixpkgs/blob/c397682663b586529838794c87ce0293cff8eda4/pkgs/tools/typesetting/tex/texlive/combine.nix#L211
For that you would need to add `eukleides.passthru.tlType`.

Regarding the build of the package itself, it should be fine to patch it bypass mktexlsr or let it run by adding `texlive-scripts` to
https://github.com/NixOS/nixpkgs/blob/31c1a6613354ecb774e28f80dfcdbbd1e0eba51c/pkgs/top-level/all-packages.nix#L29534

cc @peti as maintainer

**Comment by xworld21** [comment]
For reference, [auctex](https://github.com/NixOS/nixpkgs/blob/cf395160355536ee699161fded986cfc1b9a585d/pkgs/tools/typesetting/tex/auctex/default.nix) and [noweb](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/literate-programming/noweb/default.nix) are existing packages which provide LaTeX packages on the side. They both divert the TeX files to the `tex` output, and set `passthru.tlType`, `passthru.pkgs` as Dmitry said. Then users will be able to do `texlive.combine { inherit (texlive) scheme-small; inherit eukleides; }` to use it.

See also https://nixos.org/manual/nixpkgs/unstable/#sec-language-texlive-custom-packages

If the LaTeX package is needed at build time, then you probably need to set `TEXINPUTS=$tex/...:$TEXINPUTS` manually.

**Comment by SFrijters** [comment]
Thanks for the pointers.
I think the situation in `eukleides` is somewhat of a hybrid of the two examples - it includes a script for the user that invokes the LaTeX executable, and it has its own style file and template as well. So I guess the proper solution would be to do a `texlive.combine` with its own style, bring that combined `texlive` in scope and rewrite the script to call that particular `latex` executable.

**Comment by vcunat** [comment]
Resolved, I think.
