### ISSUE TITLE
terrascan

### ISSUE THREAD

**Issue by benshaw** [NixOS/nixpkgs#122113]
**Project description**
Terrascan detects security vulnerabilities and compliance violations across your Infrastructure as Code. Mitigate risks before provisioning cloud native infrastructure. Run locally or integrate with your CI\CD.

**Metadata**

* homepage URL: https://github.com/accurics/terrascan
* source URL: https://github.com/accurics/terrascan/releases
* license: Apache License Version 2.0
* platforms: linux, darwin, windows

**Comment by fabaff** [comment]
`terrascan` is [already available](https://search.nixos.org/packages?channel=unstable&show=terrascan&query=terrascan).
