### ISSUE TITLE
Package request: discord-chat-exporter

### ISSUE THREAD

**Issue by barentain** [NixOS/nixpkgs#122143]
**Project description**
CLI interface based Discord Chat Exporter. Puts all of your Discord chats into a .html file that makes it look like an actual Discord chat. 

**Metadata**

* homepage URL:  https://github.com/Tyrrrz/DiscordChatExporter
* source URL: https://github.com/Tyrrrz/DiscordChatExporter
* license: gnu
* platforms: unix, linux

**Comment by barentain** [comment]
Any updates on this?

**Comment by OPNA2608** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/128466.
