### ISSUE TITLE
Package request: pnpm

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#122135]
**Project description**

A package manager for the node ecosystem, like npm or yarn.

`nodePackages.pnpm` already exists, so I am just requesting the top-level package that puts a `pnpm` in `PATH`.

**Metadata**

* homepage URL:  https://github.com/pnpm/pnpm
* source URL: https://github.com/pnpm/pnpm
* license: MIT
* platforms: unix

**Comment by 06kellyjac** [comment]
`nodePackages.pnpm` does put it in `PATH`

```
λ pnpm -v
zsh: command not found: pnpm
λ cat ./shell.nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = with pkgs; [ nodejs-slim-16_x nodePackages.pnpm ];
}
λ nix-shell --pure

[nix-shell:~/sample]$ node -v
v16.0.0

[nix-shell:~/sample]$ npm -v
npm: command not found

[nix-shell:~/sample]$ pnpm -v
6.2.1
```

**Comment by ivan** [comment]
Oh, thank you, I was testing `nix-env -iA nodePackages_latest.pnpm` which does not put in `PATH`, but I see `nix-env -iA nodePackages.pnpm` does.

**Comment by 06kellyjac** [comment]
Hmm, thats interesting I might look into that.

Anyways, if you could close this issue thatd be great :)

**Comment by dbaynard** [comment]
The lack of a `bin` is #145132
