### ISSUE TITLE
git-embed needs git as dependency

### ISSUE THREAD

**Issue by charles-cooper** [NixOS/nixpkgs#12229]
https://hackage.haskell.org/package/git-embed. Using functions from this package can call some template haskell which generates calls to `git` at compile time. Unfortunately unless git is already in the environment this will fail, so pure builds fail unless git is explicitly passed as a dependency. Is there an easy fix for this?

**Comment by copumpkin** [comment]
Yeah, our typical solution is to patch the package source from within the Nix expression to point at the specific git path the library should use. People either bundle patch files or just programmatically patch the source with `sed` or `substituteInPlace`.

Also note that the package claims to be deprecated in favor of `gitrev`.

**Comment by charles-cooper** [comment]
Thank you.

**Comment by Profpatsch** [comment]
(triage) @charles-cooper do you want to close?

**Comment by ryantm** [comment]
Closing because OP didn't respond to triage.
