### ISSUE TITLE
xen dom0 doesn't build with efi

### ISSUE THREAD

**Issue by telent** [NixOS/nixpkgs#12225]
At the time of writing this (4dc7cab40ec9370816bf67b786a35679a1ebf2d1) there is an assertion in 
nixos/modules/virtualizations/xen-dom0.nix which says `Xen currently does not support EFI boot`.  This is certainly true for NixOS but as far as I can tell from Googling is no longer true upstream.

I'm opening this issue to ask if anyone's looking at adding that support (i.e. to boot using gummiboot on annoyingly new hardware that doesn't understand the legacy bios boot process)

I've started work on it and seem to have cajoled it into building a boot.efi but I haven't got as far as running it.  As a relative newbie both to nixpkgs and to Xen I'd welcome any feedback as to whether I'm on the right lines

**Comment by Profpatsch** [comment]
triage: is this fixed?

**Comment by Ninlives** [comment]
Any progress on this topic?
