### ISSUE TITLE
Package request: logiops

### ISSUE THREAD

**Issue by hawkw** [NixOS/nixpkgs#122208]
**Project description**

An unofficial driver for Logitech mice and keyboards.

This allows things like setting keymappings for the additional buttons on Logitech mice,  changing DPI, etc.

**Metadata**

* homepage URL: https://github.com/PixlOne/logiops
* source URL: https://github.com/PixlOne/logiops
* license: GPL-3.0
* platforms: linux

**Comment by hawkw** [comment]
I'm happy to try to package this myself, but I'm relatively new to writing Nix packages, so I might need some guidance.

It would also be nice if there were nixos options for this package --- it has a systemd service and a configuration file.

**Comment by zeorin** [comment]
I'm interested, too. I got a Logitec mouse last week and I've been trying to get this to build:

```
{ pkgs ? import <nixpkgs> {} }:

with pkgs; stdenv.mkDerivation rec {
  pname = "logiops";
  version = "0.2.3";
  src = fetchFromGitHub {
    owner = "PixlOne";
    repo = "logiops";
    rev = "v${version}";
    sha256 = "1wgv6m1kkxl0hppy8vmcj1237mr26ckfkaqznj1n6cy82vrgdznn";
  };
  nativeBuildInputs = [ cmake pkg-config ];
  buildInputs = [ libevdev libudev libconfig ];
}
```
is as far as I've gotten. When I try to build this CMake tries to install the service file in a systemd directory, but it isn't writeable. I don't know enough about how this ought to be handled to solve it myself.

**Comment by zeorin** [comment]
Actually, I've just figured out how to stop CMake from trying to install that file, need to apply this patch:
```diff
diff --git i/src/logid/CMakeLists.txt w/src/logid/CMakeLists.txt
index 00ee796..c8300a5 100644
--- i/src/logid/CMakeLists.txt
+++ w/src/logid/CMakeLists.txt
@@ -96,10 +96,6 @@ if (SYSTEMD_FOUND AND "${SYSTEMD_SERVICES_INSTALL_DIR}" STREQUAL "")
     string(REGEX REPLACE "[ \t\n]+" "" SYSTEMD_SERVICES_INSTALL_DIR
            "${SYSTEMD_SERVICES_INSTALL_DIR}")
     configure_file(logid.service.cmake ${CMAKE_BINARY_DIR}/logid.service)
-    message(STATUS "systemd units will be installed at ${SYSTEMD_SERVICES_INSTALL_DIR}")
-    install(FILES ${CMAKE_BINARY_DIR}/logid.service
-            DESTINATION ${SYSTEMD_SERVICES_INSTALL_DIR}
-            COMPONENT cp)
 elseif(NOT SYSTEMD_FOUND AND SYSTEMD_SERVICES_INSTALL_DIR)
     message(FATAL_ERROR "systemd is not found w/ pkg-config but SYSTEMD_SERVICES_INSTALL_DIR is defined.")
 endif()
```

**Comment by zeorin** [comment]
I actually managed to get everything working, even wrote a NixOS module. But, I'm a noob at writing packages and modules, and I may need some hand-holding to get this to production-quality (e.g. right now all of the config for the `logiops` service I created is all just one big `extraConfig` string).

I'll draft a proper PR for this in the next few days.

**Comment by hawkw** [comment]
I have a mostly working package for logiops on my machine, as well, also including a half-finished NixOS module. If you want to compare notes, let me know --- I'm also pretty new to packaging things for nix.

**Comment by hawkw** [comment]
> (e.g. right now all of the config for the `logiops` service I created is all just one big `extraConfig` string).

FWIW, I started on defining the config in Nix, rather than a big string --- I could probably get it working fairly soon and we could add that to your change.

**Comment by zeorin** [comment]
Draft PR here: #124158

**Comment by anund** [comment]
See #167388, @ckiee has packaged logiops and is working on a module.

**Comment by ckiee** [comment]
The module is basically done and I've been using it for 4 months now. Just need someone to review.
