### ISSUE TITLE
Package request: jellyfin media player

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#122230]
**Project description**
Taken from the README:

> Desktop client using jellyfin-web with embedded MPV player. Supports Windows, Mac OS, and Linux. Media plays within the same window using the jellyfin-web interface unlike Jellyfin Desktop. Supports audio passthrough. Based on Plex Media Player.

As an alternative to the `jellyfin-mpv-shim` package, this is now the official desktop client for Jellyfin. Here's the announcement: https://jellyfin.org/posts/client-jmp/ 

**Metadata**

* homepage URL: https://jellyfin.org/
* source URL: https://github.com/jellyfin/jellyfin-media-player
* license: gpl2
* platforms: all

**Comment by veprbl** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/jellyfin-media-player/default.nix

**Comment by ambroisie** [comment]
Oops, sorry about that, I forgot to check on `unstable` my mistake.

Thank you @veprbl.
