### ISSUE TITLE
Filebrowser (https://github.com/filebrowser/filebrowser)

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#122339]
**Project description**
Lightweight nextcloud/seafile/syncthing/ftp alternative to easily share files with mutiple users via HTTP

**Metadata**

* homepage URL: https://github.com/filebrowser/filebrowser
* source URL: https://github.com/filebrowser/filebrowser
* license: Apache License
* platforms: any

**Comment by Nutr1t07** [comment]
need this too

**Comment by nielsegberts** [comment]
I also have a work in progress for a module that wraps FileBrowser

**Comment by pinpox** [comment]
> I also have a work in progress for a module that wraps FileBrowser

If you submit a PR I can help review or test it

**Comment by nielsegberts** [comment]
I've not quite sure how stacked PR's work on github as the previous one is still pending, but it would be great if you could test and leave feedback on this commit:

https://github.com/nielsegberts/nixpkgs/commit/6d39a0b8c1896e9fae3b40f0732f3585b1d79f71

**Comment by nielsegberts** [comment]
I've opened a new issue to discuss the options: https://github.com/NixOS/nixpkgs/issues/236165
