### ISSUE TITLE
live cd chrashes when trying to install NixOS (live dvd version nixos-graphical-13.10.35450.912f584-x86_64-linux)

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#1224]
When I try to install NixOs with the above dvd I see stage 1 completes then stage 2 I see a lot of text and at one moment the screen becomes green and the last sentence I see is that the udev database is generated. 

After that my computer gives no respons at all. 

Roelof

**Comment by iand675** [comment]
Chiming in as well– I needed to set `modprobe.blacklist=nouveau' for a GTX 960. Subsequent attempts to use 'nouveau' or 'nvidia' graphics drivers after initial installation caused Nix to fail to boot.

**Comment by domenkozar** [comment]
nouveau is now blacklisted by default, closing
