### ISSUE TITLE
Unable to Build Qt5 Project

### ISSUE THREAD

**Issue by cbondurant** [NixOS/nixpkgs#122444]
**Describe the bug**
When attempting to build a basic Qt5 project using CMake as the build environment, CMake fails to properly configure Qt, returning the following error:
```CMake Error at /home/user/.nix-profile/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "GL/gl.h" in
  "/nix/store/s46sr1svmhsygsmp5rzy4ka4gply92nr-mesa-20.1.10-dev/include".
Call Stack (most recent call first):
  /home/user/.nix-profile/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:229 (include)
  /home/user/.nix-profile/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:97 (find_package)
  /home/user/.nix-profile/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:16 (find_package)
```

**To Reproduce**
1. Install the Qt5.full and CMake packages
2. create a CMake file for Qt5 that matches the [Recommended on the Qt documentation](https://doc.qt.io/qt-5/cmake-get-started.html)
3. create a build folder, and enter it
4. run `cmake ..`

**Expected behavior**
cmake should be able to configure all dependancies and begin running build commands. 

**Additional context**
I know I have `GL/gl.h` on my system as I can find it with a `locate GL/gl.h` however it is in libglvnd, not mesa. 
I have also tried multiple times to install mesa driver packages and none of those have successfully added the files that Qt is attempting to find. 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.109, NixOS, 20.09.3786.a7ff7a57c96 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3786.a7ff7a57c96"`
 - channels(conner): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by symphorien** [comment]
> Install the Qt5.full and CMake packages

What do you mean by install? Did you install with `nix-env` or did you use `nix-shell`? Note that using nix-env to install build dependencies is wrong: https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F

**Comment by symphorien** [comment]
Can you:
* uninstall all compilation-related packages from your profile (ie cmake, qt, pkg-config, gcc etc)
* retry compiling inside `nix-shell -p cmake qt5full pkg-config anything_you-might_want`
* provide more concrete reproduction steps by providing example code and actual commands you ran

**Comment by cbondurant** [comment]
Full reproduction steps:

- Create the following `CMakeLists.txt` in an empty folder
```
cmake_minimum_required(VERSION 3.18.0)

project(QTest VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

if(CMAKE_VERISON VERSION_LESS "3.7.0")
	set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()

find_package(Qt5Core REQUIRED)
find_package(Qt5Gui REQUIRED)

add_executable(QTest
	main.cpp
)
target_link_libraries(QTest  Qt::Core Qt::Gui)
```
- Create the following minimal Qt file `main.cpp`
```
#include <QApplication>

int main (int argc, char **argv){
	QApplication a(argc, argv);
	return a.exec();
}
```
- Enter development shell with `nix-shell -p cmake qt5Full cmake gnumake`
- `mkdir build; cmake ..`
At this point, the build should error with the previously mentioned error

**Comment by symphorien** [comment]
I can reproduce on 20.09 but not unstable, it looks like it has already been fixed. Can you confirm this ? You can test with `nix-shell .... -I nixpkgs=channel:nixos-unstable`.

On 20.09, adding libglvnd to the shell works and looks like the correct solution. mesa is only correct with some graphic cargs, whereas libglvnd will automatically dispatch to the correct vendor-dependent implementation.

Finally, something must be missing from your CMakeLists.txt because it does not compile:
```
[1] /tmp/repro 
$  mkdir build; cd build
                                                                                                                                                                                              
[1] /tmp/repro/build 
$  cmake ..
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/zzvq5qwlm2xikawfqxb0q8gl2bw391a9-gcc-wrapper-10.2.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/repro/build
                                                                                                                                                                                              
[1] /tmp/repro/build 
$  make
Scanning dependencies of target QTest_autogen
[ 25%] Automatic MOC and UIC for target QTest
[ 25%] Built target QTest_autogen
Scanning dependencies of target QTest
[ 50%] Building CXX object CMakeFiles/QTest.dir/QTest_autogen/mocs_compilation.cpp.o
[ 75%] Building CXX object CMakeFiles/QTest.dir/main.cpp.o
/tmp/repro/main.cpp:1:10: erreur fatale: QApplication : No such file or directory
    1 | #include <QApplication>
      |          ^~~~~~~~~~~~~~
compilation terminée.
make[2]: *** [CMakeFiles/QTest.dir/build.make:95 : CMakeFiles/QTest.dir/main.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:96 : CMakeFiles/QTest.dir/all] Erreur 2
make: *** [Makefile:103 : all] Erreur 2

```

**Comment by cbondurant** [comment]
With the addition of `-p libglvnd` the issue was resolved with the current channel packages, however using the unstable channel I was not able to without also specifying libglvnd. I also did get the wrong Qt packages for my test, Qt5Core should be Qt5Widgets.

**Comment by symphorien** [comment]
Can we close the issue then?

**Comment by cbondurant** [comment]
Yes, sorry.
