### ISSUE TITLE
Agda and Idris fail to build due to zlib version change

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#12254]
@peti I'm not sure if you were aware of this one, but both Agda and Idris expect an older version of zlib. When I make that change locally, `Agda` builds, but `idris` still fails because one of its transitive dependencies still wants a newer version of `zlib`.

**Comment by jwiegley** [comment]
This started happening maybe 4-5 days ago.

**Comment by peti** [comment]
Both packages seem to build fine:

 - http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.idris.x86_64-linux
 - http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.Agda.x86_64-linux

**Comment by jwiegley** [comment]
@peti Thanks for checking. I'm able to building everything in my package set (> 2000 packages) except for these two, which both failure during `cabal configure` by complaining that the version of `zlib` they depend on is not available. Knowing that it works for you, I'll track it down further here.

And forgive me for asking a question I could have answered myself. I'll setup an Ubuntu VM to answer these questions locally before bothering to create a bug next time.

**Comment by peti** [comment]
BTW, I don't know much about Idris, but Agda has some conditional logic in its Cabal file that selects the appropriate zlib version based on the compiler you're using. So that might be something to look into: are you building these packages with GHC 7.10.3?

**Comment by jwiegley** [comment]
I built them with GHC 7.10.2, I wonder if that's it.
