### ISSUE TITLE
`clojure-lsp` issue with `fish` shell

### ISSUE THREAD

**Issue by yogsototh** [NixOS/nixpkgs#122557]
**Describe the bug**

When running `clojure-lsp` I get the following error message:

```
❯ clojure-lsp
Error: Unable to access jarfile clojure-lsp
```

Looking at the executable the first line is:

```
:;exec /nix/store/rfr68d45yr1k9akrgz1n1ylxcnrkj9n2-zulu1.8.0_202-8.36.0.1/bin/java -Xmx2g -server -Dclojure-lsp.version=release-20200828T065654 -jar $0 "$@"
```

In fish `$0` does not return the name of the current executed file. It appear to work when running this using `bash`.

Also as comparison look at the `clojure-lsp` file generated via `brew` package manager:

```bash
#!/bin/bash
export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home}"
exec "${JAVA_HOME}/bin/java"  -jar "/usr/local/Cellar/clojure-lsp/20210427T201745/libexec/clojure-lsp.jar" "$@"
```

**To Reproduce**
1. install `clojure-lsp`
2. run `clojure-lsp`

**Expected behavior**

`clojure-lsp` should start the server

**Additional context**

So `nix-darwin` with `home-manager`.

**Notify maintainers**

@thiagokokada
@ericdallo

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(yogsototh): `"darwin, home-manager, nixpkgs-21.05pre288366.719ac402b1c"`
 - nixpkgs: `/Users/yogsototh/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ericdallo** [comment]
Also the brew forumla you saw is outdated as well, the updated is [this one](https://clojure-lsp.github.io/clojure-lsp/installation/#homebrew-macos-and-linux)

**Comment by thiagokokada** [comment]
@yogsototh You are probably using the stable channel 20.09 channel, that should explain why you're still using the `clojure-lsp` with JVM instead of GraalVM compiled binary.

Switch to the unstable channel instead. I am not sure if it will work though since this package was never tested with macOS (and the fact that this package is broken in Hydra: https://hydra.nixos.org/build/142849128).

**Comment by thiagokokada** [comment]
I think all GraalVM's packages build with Clojure are broken in macOS simply by the lack of people that has macOS systems to test/fix them.

If you can fix this, a PR would be welcome :slightly_smiling_face: .

**Comment by ericdallo** [comment]
Agreed ☝🏻 
If you have mac, using the homebrew official clojure-lsp formula should work as well: https://clojure-lsp.github.io/clojure-lsp/installation/#homebrew-macos-and-linux
