### ISSUE TITLE
Portaudio doesn't install pkgconfig file on Darwin

### ISSUE THREAD

**Issue by jacereda** [NixOS/nixpkgs#12264]
The current default.nix doesn't perform the `make install` in `installPhase`.

**Comment by Profpatsch** [comment]
(triage) still a problem @jacereda?

**Comment by jacereda** [comment]
Yes, according to https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/portaudio/default.nix the Darwin version isn't performing a `make install`, so it's skipping the pkgconfig file.

**Comment by matthewbauer** [comment]
Fixed in 6c6db7b58b79436a32022e4dcdda4a07051841f4. This issue can be closed.
