### ISSUE TITLE
alacritty: startup fails with `Could not create EGL display object`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#122671]
**Describe the bug**
Alacritty refuses to start:
```
> alacritty
Created log file at "/tmp/Alacritty-21045.log"
[2021-05-11 19:43:37.692188357] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("`glXQueryExtensionsString` found no glX extensions")]`
```

**To Reproduce**
1. Install alacritty
2. Run alacritty

**Expected behavior**
Alacritty to operate normally.

**Screenshots**

**Additional context**
I'm running Ubuntu 20.04.2 LTS with nix installed.
```
> alacritty --version
alacritty 0.7.2
```
Doing a bit of snooping, https://github.com/NixOS/nixpkgs/issues/80702 seems related. However, their fix of just updating packages doesn't work for me.

**Notify maintainers**

@Br1ght0ne @mic92 @cole-h @ma27

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
> nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/rcw3a87m7jycgr6hfbg6zrnr3fj6wg20-nix-info
copying path '/nix/store/rcw3a87m7jycgr6hfbg6zrnr3fj6wg20-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-73-generic, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(skainswo): `"home-manager, nixpkgs-21.05pre287374.1c16013bd6e"`
 - nixpkgs: `/home/skainswo/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: alacritty
# a list of nixos modules affected by the problem
module:
```

**Comment by cole-h** [comment]
Pretty sure this is an issue with all GL apps on non-NixOS systems. Check out https://github.com/guibou/nixGL/ -- it's what I used when I was using Nix on Arch.

**Comment by samuela** [comment]
Sweet, thanks @cole-h ! That did the trick.

I'm especially hoping that we can make some progress on https://github.com/guibou/nixGL/issues/16, and get nixGL integrated into nixpkgs with wrappers so that everything "just works".

**Comment by terlar** [comment]
For whatever it is worth I found that I didn’t need the NixGL wrapper on Ubuntu if I also were running GNOME managed by Nix instead of the one used by Ubuntu by default.

**Comment by samuela** [comment]
Ooh interesting... How did you configure using the Nix provided gnome?

**Comment by terlar** [comment]
The display manager (login manager) at least in terms of GDM will pick up all the session desktop files in:
- `/usr/share/wayland-sessions/` (for wayland ones)
- `/usr/share/xsessions/` (for xorg ones)

So all you have to do is symlink the session handler. For example for GNOME it will be `gnome-session`. Then you could symlink it as such:
```
ln -s /nix/store/nj3vbgyrg20mrbkk3lb0llx4b7ck2psn-gnome-session-3.38.0-sessions/share/wayland-sessions/gnome.desktop /usr/share/wayland-sessions/
```

It seems actually that when you install that package on a system level that it symlinks at the appropriate place, e.g.:
```
 nix-env -i gnome-session
```

**Comment by alexvorobiev** [comment]
I have just started getting this error on NixOS VM with yesterday's update with the unstable channel.

**Comment by jeff-hykin** [comment]
For anyone else reading this the TLDR answer is: 

```shell
# install nixGL
nix-channel --add https://github.com/guibou/nixGL/archive/main.tar.gz nixgl && nix-channel --update
nix-env -iA nixgl.auto.nixGLDefault   # or replace `nixGLDefault` with your desired wrapper

# run alacritty through nixGL
nixGL alacritty
```

**Comment by Kaligule** [comment]
I have alacritty installed via home-manager. For me it was enough to run `home-manager switch`.

**Comment by mediocregopher** [comment]
I have found a way around this which does not require nixGL, which I find preferable because I'd rather use the nvidia package files which are shipped with my operating system (archlinux). It seems it's as simple as setting `__EGL_VENDOR_LIBRARY_DIRS` to point to the directory where the OS installs the EGL vendor files. On arch these files don't include the full name of the `.so` files, and so `LD_LIBRARY_PATH` needs to be set as well so the OS can find them.

From there I have alacritty configured to start my shell, but I don't want those environment variables (especially `LD_LIBRARY_PATH`) to leak into my shell, so I have a small wrapper around my shell to unset the variables within alacritty.

The whole thing looks like this:

```
  shellEntrypoint = pkgs.writeShellScript "alacritty-shell-entrypoint" ''
    unset LD_LIBRARY_PATH
    unset __EGL_VENDOR_LIBRARY_DIRS
    exec "${zsh}/bin/zsh" "$@"
  '';

  alacritty = pkgs.writeShellScriptBin "alacritty" ''
    # the values here are archlinux specific, you'll need to find the correct ones for your OS
    export LD_LIBRARY_PATH=/usr/lib
    export __EGL_VENDOR_LIBRARY_DIRS=/usr/share/glvnd/egl_vendor.d

    exec ${pkgs.alacritty}/bin/alacritty \
      --config-file ${configFile} \
      -e "${shellEntrypoint}"
  '';
```

**Comment by no1melman** [comment]
> I have found a way around this which does not require nixGL, which I find preferable because I'd rather use the nvidia package files which are shipped with my operating system (archlinux). It seems it's as simple as setting `__EGL_VENDOR_LIBRARY_DIRS` to point to the directory where the OS installs the EGL vendor files. On arch these files don't include the full name of the `.so` files, and so `LD_LIBRARY_PATH` needs to be set as well so alacritty can find them.
> 
> From there I have alacritty configured to start my shell, but I don't want those environment variables (especially `LD_LIBRARY_PATH`) to leak in, so I have a small wrapper around my shell to unset the variables within alacritty.
> 
> The whole thing looks like this:
> 
> ```
>   shellEntrypoint = pkgs.writeShellScript "alacritty-shell-entrypoint" ''
>     unset LD_LIBRARY_PATH
>     unset __EGL_VENDOR_LIBRARY_DIRS
>     exec "${zsh}/bin/zsh" "$@"
>   '';
> 
>   alacritty = pkgs.writeShellScriptBin "alacritty" ''
>     # the values here are archlinux specific, you'll need to find the correct ones for your OS
>     export LD_LIBRARY_PATH=/usr/lib
>     export __EGL_VENDOR_LIBRARY_DIRS=/usr/share/glvnd/egl_vendor.d
> 
>     exec ${pkgs.alacritty}/bin/alacritty \
>       --config-file ${configFile} \
>       -e "${shellEntrypoint}"
>   '';
> ```

How does this look in a proper configuration, in my home.nix I got

```nix
{ config, pkgs, userSettings, ... }

{
  home.packages = with pkgs; [
    alacritty
  ];

  imports = [
    ./programs/alacritty.nix
  ];
}
```

How do I incorporate what you've done into the `alacritty.nix`?

I'm using flakes and home manager

**Comment by mediocregopher** [comment]
> a **proper** configuration

Let's not go throwing stones here, my configuration works and yours doesn't, so whose is proper? :)

That said, I have no idea how home manager works, so I don't know the answer. Perhaps if you post what `alacritty.nix` looks like that could help.

**Comment by no1melman** [comment]
Sorry, I was tired, I didn't mean "proper", I meant in a home-manager flakes configuration. 

What's confusing me a little is the assignment of `pkgs.writeShellScriptBin` to alacritty - I guess because of everything being an expression, this is sorta simulating a statement, you're not really using alacritty anywhere.

If I understand this correctly, then all it's doing is overriding the way alacritty gets executedto ensure that it's using the LD stuff

**Comment by mediocregopher** [comment]
Np, just joshing you a bit ;)

You can see the full context of my solution [here](https://dev.mediocregopher.com/loadout/tree/alacritty/default.nix?id=df6e00d2c4096b0de282bd1b2e0f93f1b69ebfe6). I'm creating a new `alacritty` derivation which wraps the one from nixpkgs (actually I create two, one for light mode and one for dark mode). I then add that to my environment [here](https://dev.mediocregopher.com/loadout/tree/default.nix?id=df6e00d2c4096b0de282bd1b2e0f93f1b69ebfe6#n163).

> If I understand this correctly, then all it's doing is overriding the way alacritty gets executedto ensure that it's using the LD stuff

Yes, exactly. What I'm doing is more or less equivalent to sticking a bash script at `~/bin/alacritty` (assuming `~/bin` is in my `PATH`), where that bash script is setting some environment variables and then calling the "real" alacritty.
