### ISSUE TITLE
MangoHud: glxinfo: not found

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#122656]
**Describe the bug**
I see this error in terminal when starting a game in steam:

`sh: 1: glxinfo: not found`

Maybe it's related to MangoHud.

```
>>> Adding process 190115 for game ID 688420
Loading player data from Z:/home/davidak/.local/share/Steam/steamapps/common/BadNorth/BadNorth_Data/data.unity3d
MANGOHUD: Failed to open 32bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
skipping config: /home/davidak/.config/MangoHud/wine-BadNorth.conf [ not found ]
skipping config: /home/davidak/.local/share/Steam/steamapps/common/Proton 6.3/dist/bin/MangoHud.conf [ not found ]
skipping config: /home/davidak/.config/MangoHud/wine-preloader.conf [ not found ]
parsing config: /home/davidak/.config/MangoHud/MangoHud.conf [ ok ]
Unknown option 'output_folder'
Unknown option 'cpu_load_change'
Unknown option 'cpu_mhz'
Unknown option 'legacy_layout'
Unknown option 'gpu_load_value'
Unknown option 'gpu_load_change'
Unknown option 'cpu_power'
Unknown option 'gpu_load_color'
Unknown option 'cpu_load_value'
Unknown option 'cpu_load_color'
Unknown option 'wine_color'
Unknown option 'io_stats'
Fossilize INFO: Overriding serialization path: "/home/davidak/.local/share/Steam/steamapps/shadercache/688420/fozpipelinesv5/steamapprun_pipeline_cache".
sh: 1: glxinfo: not found
Game update: AppID 688420 "", ProcID 190113, IP 0.0.0.0:0
```

**To Reproduce**
1. open steam from terminal
2. start a game
3. look at the terminal output of steam

**Expected behavior**
no errors

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.2, NixOS, 21.05.git.db0294aa60c (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"home-manager, nixos-21.05pre287333.63586475587, nixos-hardware, nixos-unstable-21.05pre287333.63586475587"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

testing pr for 5.12 kernel

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by MetaDark** [comment]
This error does come from MangoHud and should be fixed in the upgrade: https://github.com/NixOS/nixpkgs/pull/122465/files#diff-f987ae9770d7cd02caacd817231e4fa880cd61fa271b901ab053f8aeed1501d5R58.

We weren't previously hardcoding it as a dependency.

**Comment by davidak** [comment]
This is fixed with the MangoHud update.

Also these issues:

```
MANGOHUD: Failed to open 32bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
```
