### ISSUE TITLE
nixos: How to use usb smart cards (yubikey) with GnuPG?

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#12277]
I'd like to get a USB yubikey OpenPGP smart card to work on NixOS (unstable). Out of the box both GnuPG1 and GnuPG21 (e.g. --card-status) simply say that card cannot be found (lsusb does show the device). Any tips?

**Comment by mogorman** [comment]
if lsusb doesnt see anything its wrong at lowest level.  do you see any messages relating to it in dmesg?  maybe do a dmesg -c before hand to be sure.

**Comment by rnhmjoj** [comment]
I don't have one but I found [this](http://forum.yubico.com/viewtopic.php?f=26&t=1878). It could be gpg is looking for it on the wrong port number.

**Comment by datakurre** [comment]
@rnhmjoj Thank you that tip lead to me to figure out that I must enable pcscd in configuration to support smart cards in NixOS.
