### ISSUE TITLE
cyrus-sasl is broken on staging

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12279]
Tested on both Linux and Darwin, and both fail in the same way.

The culprit appears to be https://github.com/NixOS/nixpkgs/commit/a472d836f674fe388018aaee75983e3400a77db4, which added [a patch from LFS](https://github.com/NixOS/nixpkgs/commit/a472d836f674fe388018aaee75983e3400a77db4#diff-5a7815c6959a4fffdad035eebcddf9bbR21) that seems to break the Makefile for sasldb by adding `-ldb` as a make target instead of a flag.

@ysangkok what were you going for with that patch? Perhaps some flags from LFS disable building sasldb and thus don't encounter the issue?

I'll probably just patch that make target out of `cyrus-sasl`, but I'm curious why nobody upstream has noticed.

**Comment by copumpkin** [comment]
Reverting the entire change to `cyrus-sasl` in https://github.com/NixOS/nixpkgs/commit/a472d836f674fe388018aaee75983e3400a77db4#diff-5a7815c6959a4fffdad035eebcddf9bbR1 fixes it. @ysangkok can I revert that? I'm willing to take a hit on FreeBSD if it breaks Linux and Darwin :smile: or do you have a quick fix that will make it better?

**Comment by vcunat** [comment]
Ah, I forgot to push the fix with the branch directly, I'm sorry.

**Comment by ysangkok** [comment]
@copumpkin The patch was necessary for building on FreeBSD, if I recall correctly. As the patch was from LFS, I did not consider the possibility that it could break the package on Linux. I realize now that this was a bad call on my part, future FreeBSD patches will be tested on Linux too. I don't have a Darwin machine available, but I think the possibility that I will accidentally break Darwin, but not Linux, while working on FreeBSD (which has similarities with Darwin) support is small.

The patch itself mentions "parallel build fixes" in the description, it could be that that was the problem while building on FreeBSD. Worryingly, it also mentions "security fixes", but I don't know for sure which changes that refers to (maybe the ones to `pwcheck/pwcheck_getspnam.c`?)...

**Comment by vcunat** [comment]
I tried searching CVEs and the latest I found against cyrus was from 2009, which is years before the release we're using.

**Comment by copumpkin** [comment]
@vcunat pretty much the entire change to the `cyrus-sasl` broke it for me, not just the LFS patch. I had to take out `autoreconfHook` before the problem went away. I can't push right now but can make the change later.

**Comment by vcunat** [comment]
I know. See the patch I had pushed: 513994d; it builds on Linux with that. (I'm sorry I wasn't more explicit.)

**Comment by copumpkin** [comment]
Oh sorry, I only saw the commit topic, didn't look at the contents. Sounds good, thanks!
