### ISSUE TITLE
Service starts before home directory is mounted

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#12281]
I use syncthing and I have been noticing for quite a while my private key and cert are sporadically regenerated while the configuration remains intact. Investigating the logs I think I've found out what really happens:
* system boots, /home is empty, disk still not mounted.
* `syncthing.service` is started, syncthing sees home empty, generates a new key-pair and config
* `home.mount` is started, complains with `Directory /home to mount over is not empty, mounting anyway`
* syncthing updates its config as soon as home is mounted but somehow keeps the new key-pair.

How can I fix this? Is there a way to prevent this from happening again to other services as well?

**Comment by heydojo** [comment]
Do you set file Systems.<name?>.neededForBoot as true for your /home filesystem declaration  in configuration.nix?
https://nixos.org/nixos/options.html

**Comment by rnhmjoj** [comment]
@heydojo No, I didn't know it existed. Thank you.
I guess it's solved with it.

**Comment by heydojo** [comment]
No problem. :+1:

**Comment by jian-lin** [comment]
related https://github.com/NixOS/nixpkgs/pull/203768
