### ISSUE TITLE
imagemagick: configure options not available

### ISSUE THREAD

**Issue by stephank** [NixOS/nixpkgs#122889]
**Describe the bug**

ImageMagick makes available configuration details through a function `GetConfigureOptions`. This is not exposed through one of the CLI tools, but is exposed by php-imagick, for example, and can be a helpful debugging tool.

`GetConfigureOptions` returns some hardcoded fields, but the majority of fields are sourced from `configure.xml`. Because we split outputs, and do so late during `postInstall`, the build is not aware and generates incorrect values in this file for `DOCUMENTATION_PATH` and `SHAREARCH_PATH`. These are internal variables of the configure script derived from other paths, but not directly settable.

In addition to this, `GetConfigureOptions` is not even able to locate `configure.xml`. It lives in `SHAREARCH_PATH`, but even if we patch that in the configure script, configure.ac does not `AC_DEFINE` this variable. Instead, the code derives this path again in `MagickCore/magick-config.h`.

In short, we need to patch:
 - `DOCUMENTATION_PATH` in `configure`
 - `SHAREARCH_PATH` in `configure`
 - `MAGICKCORE_SHAREARCH_PATH` in `MagickCore/magick-config.h` (or `magick-baseconfig.h` post-configure)

I'm not sure what the best approach is here. Do we even want to patch `configure`? Should we use patch files or sed? Or should we instead patch `configure.ac` and rerun autoconf? Or is there some alternate approach?

Possibly also affects `imagemagick6`, did not yet investigate.

**To Reproduce**
1. `nix-shell -p phpExtensions.imagick --run "php -r 'var_dump(Imagick::getConfigureOptions());'"`

**Expected behavior**
Should print lots of configuration detail, including the configure script invocation:

```
  ["CONFIGURE"]=> string(155) "./configure  '--with-quantum-depth=16' ...
```

Instead, the output array contains only 5 elements.

**Additional context**
Upstream issue: https://github.com/Imagick/imagick/issues/399

**Notify maintainers**
@erictapen

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(stephank): `""`
 - channels(root): `"nixpkgs-21.03pre258655.00941cd747e"`
 - nixpkgs: `/nix/store/wr6ydfwv448vw3yxaypl3gn8p4ixd2py-source`

Maintainer information:
```yaml
attribute: [imagemagick7]
```

**Comment by veprbl** [comment]
A work around is to build without multiple outputs:
```
nix-shell -I nixpkgs=channel:nixpkgs-unstable -p 'php.withExtensions ({ enabled, all }: enabled ++ [ (all.imagick.override rec { imagemagick = pkgs.imagemagick.overrideAttrs (old: { outputs = ["out"]; postInstall = builtins.replaceStrings [ "$dev" ] [ "$out" ] old.postInstall; }) // { dev = imagemagick; }; }) ])' --pure --run "php -r 'var_dump(Imagick::getConfigureOptions());'"
```

Wiring libraries to the config file that contains references to the documentation will defeat the purpose of multiple outputs.

**Comment by stephank** [comment]
Hmm, that does make a lot of sense. In that case, I think we can just close this.
