### ISSUE TITLE
plasma/wayland: pasting images does not work

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#122863]
**Describe the bug**
Taking a screenshot to the clipboard and pasting it into an application does not appear to work in plasma wayland sessions.

**To Reproduce**
1. Take a screenshot with spectacle (copy to clipboard, don't save to disk)
2. Try pasting into dolphin/discord/whatever
3. Nothing happens

**Expected behavior**
Application should insert the image from the clipboard to the input line/current directory/etc

**Screenshots**
would add if this worked, but then I wouldn't have to open this issue in the first place :wink: 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.19, NixOS, 21.05.git.03e6c33e523 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre288911.65d6153aec8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
   - unstable channel + #117102

**Comment by rosehuds** [comment]
FWIW it doesn't work on my arch machine either

**Comment by pilppilo** [comment]
What clipboard applications are you using?

**Comment by jansol** [comment]
Whatever I get on wayland plasma out of the box, I haven't really looked into it.

**Comment by clickwir** [comment]
Not sure it's exactly the same problem, but mine sounds nearly identical. I believe the clipboard application is called Klipper.

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-16-generic
OS Type: 64-bit
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon ™ RX 460 Graphics

One thing I've noticed is if I mouse over the clipboard icon down by the time, it shows "0x0 0bpp". If I were to copy the text "machine", it would show "Clipboard contents: machine".

So it seems like it thinks there's an image, but it's size is zero and has zero bits per pixel. Also using Spectacle to get a screenshot.

**Comment by jansol** [comment]
Copying entire images from firefox does appear to work, but pasting screenshots from Spectactle doesn't. So the problem is likely on that side rather than pasting itself. Normally I'd use flameshot but with recent plasma/wayland that isn't able to take screenshots at all. Hopefully it's just a matter of desktop portal support, which the next plasma release should fix.

**Comment by ilya-fedin** [comment]
This is a Qt bug, they're filling all the mimetypes with bmp data, so images copied from Qt applications will be pasted only to other Qt applications that support proprietary application/x-qt-image mime type (that is actually bmp).
https://codereview.qt-project.org/c/qt/qtwayland/+/366769

**Comment by jansol** [comment]
Seems to be fixed on current nixos-unstable. Dolphin now asks which image type to save the pasted image as, Discord drops the image in the input box as expected.
