### ISSUE TITLE
Cannot override systemd user units in NixOS

### ISSUE THREAD

**Issue by MetaDark** [NixOS/nixpkgs#122870]
**Describe the bug**

If you define a systemd user unit with the same name as an installed user unit, `/etc/systemd/user/<unit>.d/overrides.conf` won't be generated like it is for system units, and the upstream unit defined in `/run/current-system/sw/share/systemd/user/<unit>` will be loaded instead.

**To Reproduce**
1. Define a systemd user unit with the same name as an installed user unit. For example:
```nix
{ config, pkgs, ... }:

{
  # NOTE: replay-sorcery isn't currently packaged in nixpkgs
  environment.systemPackages = [ pkgs.replay-sorcery ];
  systemd.packages = [ pkgs.replay-sorcery ];

  # System capabilities required for hardware accelerated video capture
  # https://ffmpeg.org/ffmpeg-devices.html#kmsgrab
  security.wrappers.replay-sorcery = {
    source = "${pkgs.replay-sorcery}/bin/replay-sorcery";
    capabilities = "cap_sys_admin+ep";
  };

  systemd.user.services.replay-sorcery = {
    serviceConfig.ExecStart = [
      "" # Tell systemd to clear the existing ExecStart list, to prevent appending to it.
      "${config.security.wrapperDir}/replay-sorcery"
    ];
  };
}
```
2. Start the unit: `system start --user unit`
3. `systemctl status --user unit` will not show that a `Drop-In` was loaded like it does for an overrided system unit. For example:
```
    Drop-In: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-system-units/bluetooth.service.d
             └─overrides.conf
```

**Expected behavior**
`/etc/systemd/user/<unit>.d/overrides.conf` should be generated for user units & the `Drop-In` should be loaded when the unit is started:
```
    Drop-In: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-user-units/replay-sorcery.service.d
             └─overrides.conf
```

**Additional context**
This bug was introduced by https://github.com/NixOS/nixpkgs/pull/97801 for two reasons. `"/share/systemd"` is now included in `environment.pathsToLink` which causes upstream units to take priority over units defined in `/etc/systemd`. Also, the new [move-systemd-user.sh](https://github.com/NixOS/nixpkgs/pull/97801/files#diff-0abb1634daac482c1a6d7451a8d3b2489dd09dbfa189935f4487a19c991df67d) setup hook changes how upstream units are included in `/etc/systemd`, which causes the NixOS unit to be linked in instead of the upstream unit + an `overrides.conf` file. @rycee

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.19, NixOS, 21.05.git.459822f3484 (Okapi)` (built with modified nixpkgs based on 65d6153aec85c8cb46023f0a7248628f423ca4ee)
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre287596.ae1c8ede09b, nur"`
 - channels(kira): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by MetaDark** [comment]
When I opened this, I thought upstream user units were automatically added to `/etc/systemd/user`, but I found that I needed to explicitly include upstream units from packages with `systemd.packages = [ pkgs.replay-sorcery ];`

Still with that change, upstream units don't get linked into `/etc/systemd/user` because with the [move-systemd-user.sh](https://github.com/NixOS/nixpkgs/pull/97801/files#diff-0abb1634daac482c1a6d7451a8d3b2489dd09dbfa189935f4487a19c991df67d) setup hook introduced in #97801, they're moved from `/lib/systemd/user` into `share/systemd/user`.

The script that generates `/etc/systemd/user` expects the unit to be located in `/etc/systemd/user` or `/lib/systemd/user`: https://github.com/NixOS/nixpkgs/blob/65d6153aec85c8cb46023f0a7248628f423ca4ee/nixos/modules/system/boot/systemd-lib.nix#L158-L177

**Comment by MetaDark** [comment]
Sorry, I realized that this issue was just a packaging problem. I was installing the systemd unit to `share/systemd/user` instead of `lib/systemd/user`. With the setup hook, it still gets moved to `lib/systemd/user`, but a symlink is left in place which gets picked up by the `generateUnits` script.

With that fix, my user unit is now getting correctly overridden:
```
     Loaded: loaded (/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-replay-sorcery-0.5.0/share/systemd/user/replay-sorcery.service; enabled; vendor preset: enabled)
    Drop-In: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-user-units/replay-sorcery.service.d
             └─overrides.conf
```

**Comment by rycee** [comment]
Yeah, systemd wants the units in `lib/systemd/user` but then have difficulties finding them again because it looks for units reachable from `$XDG_DATA_DIRS`. I don't know why its done in that way but the workaround I found was to make them available in both places. In any case, I'm very glad it worked out for you because it would have been a pain to figure out a solution otherwise 😀
