### ISSUE TITLE
plasma/wayland: ssh-add: Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#122865]
**Describe the bug**
After switching to the wayland session of plasma it seems ssh-agent is no longer working.

**To Reproduce**
1. Boot into wayland session
2. Try to unlock ssh keys with ssh-add

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.19, NixOS, 21.05.git.03e6c33e523 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-21.05pre288911.65d6153aec8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
   - nixos-unstable + #117102

**Comment by jansol** [comment]
Not sure if something plasma-specific was fixed along the way but the final part of the problem turned out to be nu-shell. It does not source `/etc/profile`, which would define a number of important environment variables for bash, zsh and other semi-compatible shells. (nu has a completely different syntax so sourcing would not be possible anyway)

Manually defining `SSH_AUTH_SOCK="/run/user/1000/ssh-agent"` in the env section of your nu-shell config (replace 1000 with your local uid) works around the issue.

**Comment by armando-ota** [comment]
same problem here ... plasma 6.x ... works on x11 though

**Comment by jansol** [comment]
Works fine for me on plasma 6 wayland. What shell are you using?

**Comment by armando-ota** [comment]
bash ... 
first day using wayland with plasma 6

**Comment by jansol** [comment]
Hmm, I'm using bash as well and it's all fine. Can you double-check that you 1. have `ssh-agent` in your PATH and 2. `SSH_AUTH_SOCK` in your environment?

**Comment by jansol** [comment]
Oh, and do you have `programs.ssh.startAgent = true;`  in your nixos configuration?

**Comment by armando-ota** [comment]
hey man .. I'm really sorry ... totally failed on spotting the github project :( ... I'm on KDE neon ... I'm really sorry for the inconvenience ... #fml

**Comment by jansol** [comment]
No worries! Unfortunately I can't help with Neon, though. :laughing:
