### ISSUE TITLE
python35Packages.acd_cli not installable

### ISSUE THREAD

**Issue by womfoo** [NixOS/nixpkgs#12294]
`python35Packages.acd_cli` in my `configuration.nix` fails with:
```bash
# nixos-rebuild switch
building Nix...
building the system configuration...
error: SQLAlchemy-0.7.10 not supported for interpreter python3.5m
(use ‘--show-trace’ to show detailed location information)
```

updating this to sqlalchemy8 or sqlalchemy9 in the [propagatedBuildInputs](https://github.com/NixOS/nixpkgs/blob/7c2845128749d1f4a4bf5644695e876193c5932b/pkgs/top-level/python-packages.nix#L236) works.

Leaving it up to the maintainers on what to use.

**Comment by FRidh** [comment]
If you need this version and it is supported, then I recommend you open a PR with the fix.

**Comment by domenkozar** [comment]
@womfoo you're welcome to open the PR with your proposed fix :)

**Comment by womfoo** [comment]
Alright, tried preparing the fix and realized that the wrapper is broken (was testing with acd_cli.py before). I'm not familiar with the python nixisms yet so any clues would be helpful. Thanks!

```
[kranium@silverspark:~]$ acd_cli
Traceback (most recent call last):
  File "/nix/store/fzf9aaqhmlx63c2picvqg4w0ylhcn68r-python3.5-acd_cli-0.3.1/bin/.acd_cli-wrapped", line 8, in <module>
    from acd_cli import main
  File "/nix/store/fzf9aaqhmlx63c2picvqg4w0ylhcn68r-python3.5-acd_cli-0.3.1/bin/acd_cli.py", line 2
    export PYTHONPATH=/nix/store/fzf9aaqhmlx63c2picvqg4w0ylhcn68r-python3.5-acd_cli-0.3.1/lib/python3.5/site-packages:/nix/store/npfgbyijs2hlyrcazqfzycy4mcslb09q-python3.5-appdirs-1.4.0/lib/python3.5/site-packages:/nix/store/8wdrsykzvq9w079yq1h5hwj7n5s5cj1v-python3-3.5.1/lib/python3.5/site-packages:/nix/store/z0rcnj8m2cqg3n7bvsyi5mg16719j45y-python3.5m-setuptools-18.2/lib/python3.5/site-packages:/nix/store/jsh48vl2jfxgzdp9l9qzmhacgcj1d6ma-python3.5-colorama-0.3.3/lib/python3.5/site-packages:/nix/store/nfr8bkxh1irmq2rdicl0hr15zrqm80nn-python3.5-dateutil-2.4.2/lib/python3.5/site-packages:/nix/store/g4g97s5l6cck5464255366dnc56gdfw9-python3.5-six-1.10.0/lib/python3.5/site-packages:/nix/store/jcg52254ibcaw8xqr83maj5yz4w4rhhl-python3.5-requests-2.8.1/lib/python3.5/site-packages:/nix/store/w0idcw6zkpy1gknl1r7xp0zgnl51vgjg-python3.5-requests-toolbelt-0.4.0/lib/python3.5/site-packages:/nix/store/00qakg8i9lf20khwidysd3sa9yrcsw5g-python3.5-SQLAlchemy-0.9.9/lib/python3.5/site-packages${PYTHONPATH:+':'}$PYTHONPATH
                    ^
SyntaxError: invalid syntax
```

**Comment by FRidh** [comment]
Just gave it a quick try. You need to indeed change the `sqlalchemy` version. Furthermore, since `httpretty` is outdated (version in nixpgks doesn't support 3.x) you need to update that package as well. That's were I stopped.

**Comment by FRidh** [comment]
Should work now only with 3.3:  b444fe98a5f48cfc253c1a6799d0d502d0e3d2f7

**Comment by womfoo** [comment]
closing this case since python3.3 now installs OK

as for the remaining wrapper issue, I just raised NixOS/nixpkgs#12386
