### ISSUE TITLE
Disable wg-quick service at startup. 

### ISSUE THREAD

**Issue by Tchekda** [NixOS/nixpkgs#122910]
**Describe the bug**
There is currently no way to disable a `wg-quick` service at startup.
I have even tried manual override but the service is still symlinked to `multi-user.target.wants`
`Failed to disable unit: File /etc/systemd/system/multi-user.target.wants/wg-quick-wg0.service: Read-only file system`
```nix
systemd = {
  services.wg-quick-wg0.wantedBy = [ "" ];
};
``` 

**To Reproduce**
1. Create a `wg-quick` tunnel on NixOS 20.09
2. Try to disable it at startup `sudo systemctl disable wg-quick-wg0.service `

**Expected behavior**
Either have a config option to disable it at boot, or have the ability to disable it through systemd

**Additional context**
The current solution if to override the whole [wq-quick](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/wg-quick.nix) just to disable this option

**Notify maintainers**
@exi @bkchr 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16, NixOS, 20.09.4025.dc326c78a93 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(tchekda): `"home-manager-20.09, nixpkgs-21.05pre286634.9775b39fd45, unstable-21.05pre285574.8e4fe32876c"`
 - channels(root): `"nixos-20.09.4025.dc326c78a93, home-manager-20.09"`
 - nixpkgs: `/home/tchekda/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: `systemd.services.wg-quick-${name}.wantedBy`
# a list of nixos modules affected by the problem
module: `wg-quick`
```

**Comment by mohe2015** [comment]
Without checking I think you need to force the override as lists are merged (union) by default. So: `wantedBy = lib.mkForce [ ];`

**Comment by Tchekda** [comment]
> Without checking I think you need to force the override as lists are merged (union) by default. So: `wantedBy = lib.mkForce [ ];`

Hi, thank you so much for your answer. I still don't know why I haven't thought about forcing the merge.

The `systemctl disable` still throws an error but looks like it will not start at next boot : `Failed to disable unit: File /etc/systemd/system/wg-quick-wg0.service: Read-only file system`

Will close this issue if the service will not start at next boot.

**Comment by mohe2015** [comment]
> > Without checking I think you need to force the override as lists are merged (union) by default. So: `wantedBy = lib.mkForce [ ];`
> 
> Hi, thank you so much for your answer. I still don't know why I haven't thought about forcing the merge.
> 
> The `systemctl disable` still throws an error but looks like it will not start at next boot : `Failed to disable unit: File /etc/systemd/system/wg-quick-wg0.service: Read-only file system`
> 
> Will close this issue if the service will not start at next boot.
> 
> 

As far as I know this is "intentional" because lots of things in NixOS are immutable by design. I don't know if there would be a workaround but I don't think so.

**Comment by hmenke** [comment]
Use `systemctl stop wg-quick.service` to stop the service and use `systemd.services.wg-quick-wg0.wantedBy = lib.mkForce [ ];` to disable it.

The imperative `systemctl disable wg-quick.service` will not work because `/etc/systemd/system` is a symlink into the read-only Nix store.  Essentially you cannot use stateful systemd service configuration on NixOS. Instead you have to configure services in `configuration.nix`. That is a deliberate design decision.

**Comment by Tchekda** [comment]
> Use `systemctl stop wg-quick.service` to stop the service and use `systemd.services.wg-quick-wg0.wantedBy = lib.mkForce [ ];` to disable it.
> 
> The imperative `systemctl disable wg-quick.service` will not work because `/etc/systemd/system` is a symlink into the read-only Nix store. Essentially you cannot use stateful systemd service configuration on NixOS. Instead you have to configure services in `configuration.nix`. That is a deliberate design decision.

Hi, thank you for your answer. 

Effectively the service was stopped at my startup, so it worked. 

Sorry for the dumb question. Closing this issue...

PS : Will maybe do a PR to add an option to the module, but later
