### ISSUE TITLE
mwprocapture: Broken package?

### ISSUE THREAD

**Issue by djahandarie** [NixOS/nixpkgs#122999]
I'm trying to use the mwprocapture nixos module (which uses the mwprocapture kernel package) on 20.09 (linuxPackages_latest), and I get the following:
```
Package ‘mwprocapture-1.2.4177-5.8.18’ in /nix/store/smd91bacvzcqbqldb58j47lqvgjxjwfs-nixos-20.09.1889.58f9c4c7d3a/nixos/pkgs/os-specific/linux/mwprocapture/default.nix:62 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.
```
Is this known and/or already fixed somewhere? (Also, is it safe to use it anyways?)

I'd love to try and fix it further myself, but I don't know how to splice in a local/development nix file into my `boot.kernelPackages` for development purposes :sweat_smile: 

@MP2E (also CC @pwetzel)

**Comment by djahandarie** [comment]
Looks like upgrading the package version resolved things. Will create a PR soon.

**Comment by pwetzel** [comment]
Thanks for the heads up.
