### ISSUE TITLE
gvfs-mount fails

### ISSUE THREAD

**Issue by sephalon** [NixOS/nixpkgs#12302]
I'm having trouble using GVfs on my Gnome 3 system. For example:

```
$ gvfs-mount ftp://ftp.gnu.org/
Error mounting location: volume doesn't implement mount
```

WebDAV fails in the same manner. For device file mounts I get:

```
$ gvfs-mount --device=/dev/sda1
No volume for device file /dev/sda1
```

Device file mounts and `--list` also end up with this error; not sure if this is related:

```
Error creating proxy: The connection is closed (g-io-error-quark, 18)
```

Interestingly enough, local mounts (disks and MTP) in Gnome Files work nicely. However when mounting e.g. a WebDAV share, I get:

```
Unhandled error message: Message did not receive a reply (timeout by message bus)
```

I'm running `16.03.git.93d8671M (Emu)` with `services.xserver.desktopManager.gnome3.enable = true`.

**Comment by Profpatsch** [comment]
(triage) @sephalon can you still reproduce?

**Comment by benrob0329** [comment]
I can.

    System: NixOS: 16.09
    Nix version: 1.11.6
    Nixpkgs version: 16.09.1512.6b28bd0
    Desktop Environment: Xfce4

**Comment by jtojnar** [comment]
`gvfs-mount ftp://ftp.gnu.org/` asks me for password so this is probably fixed. Also gvfs-mount is deprecated, if you can still reproduce with `gio mount`, please re-open.
