### ISSUE TITLE
darwin: nodejs-5_x : no-xcode.patch fails

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#12305]
The build fails because the no-xcode patch against `tools/gyp/pylib/gyp/xcode_emulation.py` cannot be applied. 

I had a short look if it was something easy and straight forward to fix but the function `_AppendPlatformVersionMinFlags` did apparently change quite a bit and I have no idea what is going on in there.

**Comment by copumpkin** [comment]
This commit? https://github.com/NixOS/nixpkgs/commit/36ebae29ce2c1cd3cb401018fccfdf719febbd3a

cc @pikajude

**Comment by skaapgif** [comment]
I just ran into the same problem.

**Comment by manveru** [comment]
Building master still is failing with:

```
applying patch /nix/store/arr44nw7q2pcy1xj6dv4l3v1m4wmfn4v-no-xcode.patch
patching file tools/gyp/pylib/gyp/xcode_emulation.py
Hunk #4 FAILED at 1040.
1 out of 4 hunks FAILED -- saving rejects to file tools/gyp/pylib/gyp/xcode_emulation.py.rej
builder for ‘/nix/store/gyan8xs55dmf5pjgmyhbqnlzmgyqr4m3-nodejs-5.1.1.drv’ failed with exit code 1
```

**Comment by gilligan** [comment]
@copumpkin I reverted that commit but that was not it - the patch still fails to apply

**Comment by pikajude** [comment]
@gilligan Working on this. Hydra does not contain a successful build of node 5 on Darwin. Trying to find a working commit of it, but that can require stdenv rebuilds.

**Comment by pikajude** [comment]
@gilligan @copumpkin works as of 989966b29307ee398b20c48fbf8b2584cd35dec4, was broken with a6982cc. I'm assuming the version was updated but the patch wasn't.

**Comment by gilligan** [comment]
@pikajude - alright. Well i looked at the patch but everything changed quite a bit and I fail at fixing it. 

Do you know what exactly is happening there? Can you fix it?

**Comment by copumpkin** [comment]
I'm about to fix it.
