### ISSUE TITLE
Do we need LLVM 3.3 through 3.7 in nixpkgs?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12310]
We generally try to get rid of old versions of packages unless we have a strong reason to keep them around. But the versions of LLVM seem to only grow. It seems fairly safe to kill 3.3 through 3.5, and possibly even 3.6 unless something is fundamentally using an old version.

**Comment by domenkozar** [comment]
In general we should kill all those not used by other packages

**Comment by ttuegel** [comment]
Julia is using 3.3. I would prefer if we keep 3.6 for personal reasons (Mesa's r600 driver is broken with 3.7). In general, LLVM has 0% API compatibility between versions, so I would vote for keeping any version without a compelling reason to drop it.

**Comment by vcunat** [comment]
Yeah, the need to use mesa drivers with 3.6 was reported by multiple users, so we'd better keep that for now.

**Comment by peti** [comment]
Haskell compilers also work with only one particular version of LLVM, so older compilers do need older versions of LLVM (iff the llvm code generator is used). Not sure whether that's a compelling reason to keep old LLVMs around, but, well, there it is.

**Comment by FRidh** [comment]
3.6 is used by `pythonPackages.llvmlite` which is essential for the JIT compiler `pythonPackages.numba`.

**Comment by copumpkin** [comment]
Assuming all of your examples actually require older versions of LLVM than the most recent one, and can't be easily patched to use newer ones, I'm going to take the answer to my title question as a "yes" :smile:

**Comment by vcunat** [comment]
For the mesa problem, we don't have a clue what's the matter, so 3.6 at least seems clear ATM.

**Comment by domenkozar** [comment]
Can we kill `llvm_33`?

```
$ git grep llvm_33
pkgs/top-level/all-packages.nix:  clang_33 = wrapCC (clangUnwrapped llvm_33 ../development/compilers/llvm/3.3/clang.nix);
pkgs/top-level/all-packages.nix:    llvm = llvm_33;
pkgs/top-level/all-packages.nix:  llvm_33 = callPackage ../development/compilers/llvm/3.3/llvm.nix { };

[ielectric@guava:~/dev/nixpkgs]$ on release-16.03
$ git grep clang_33
pkgs/top-level/all-packages.nix:  clang_33 = wrapCC (clangUnwrapped llvm_33 ../development/compilers/llvm/3.3/clang.nix);
```
