### ISSUE TITLE
river isn't reproducible, and possibly everything that uses zig

### ISSUE THREAD

**Issue by kanashimia** [NixOS/nixpkgs#123187]
**Describe the bug**
Running river on nixos unstable [(link to a derivation)](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/river/default.nix) results in this error:
```
›river
Illegal instruction at address 0xIllegal instruction (core dumped)
```
which is caused by this instruction: `vpbroadcastb ymm0,BYTE PTR [rbx+0x21]`
It is an [AVX2 instruction](https://www.felixcloutier.com/x86/vpbroadcast), and i'm using AMD FX 6350, which only supports regular AVX

It seems that zig basically uses something like `-march=native` by default, which is questionable to say at least.
I couldn't find an easy way to fix it, so i will leave this as an issue.

All other zig packages are possibly affected too, needs verification.

**To Reproduce**
1. ```
   > nix shell n#river -c sh -c 'nix run n#elfx86exts $(which river)'
   MODE64 (pop)
   AVX (vmovups)
   NOVLX (vmovups)
   CMOV (cmovb)
   BMI2 (mulx)
   AVX2 (vpbroadcastq)
   BMI (andn)
   SSE2 (pause)
   CPU Generation: Unknown
   ```
2. ```
   > nix build n#river --no-substitute --rebuild
   error: derivation '/nix/store/xbbhnvr9apag5y979qsihj9d613bac75-river-unstable-2021-05-07.drv' may not be deterministic: 
   output '/nix/store/l9n6na4xly0pbjic4a7sbvvhn78z02cs-river-unstable-2021-05-07' differs
    ```
###### note: Ideally there needs to be a VM test.

**Expected behavior**
Doesn't use AVX2, build is reproducible.

**Notify maintainers**
@branwright1

**Metadata**
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - river
# a list of nixos modules affected by the problem
module:
```

**Comment by branwright1** [comment]
What I have to do with it if it's not just river but Zig itself? You can ask zig maintainer (creator itself) about it. I will also ask community and river developers.

**Comment by MasterQ32** [comment]
> It seems that zig basically uses something like -march=native by default, which is questionable to say at least.
> I couldn't find an easy way to fix it, so i will leave this as an issue.

This is correct, zig builds for the current host by default. If a cross-compile should be performed, a target triple should be given (`x86_64-linux-gnu`) for example, assuming glibc/GNU abi is used. This is usually passed by `zig build -Dtarget=x86_64-linux-gnu` to a build script or via `zig build-exe -target x86_64-linux-gnu` on a normal build command line.


The code here only builds for the local machine, so it might not be shared with other machines:
https://github.com/NixOS/nixpkgs/blob/89f90fda19e1da898703c72e76aa6127d3a4a3d5/pkgs/applications/window-managers/river/default.nix#L28-L32

**Comment by branwright1** [comment]
I will try to update it today and add 3 main targets, amd64, x86 and aarch64

**Comment by branwright1** [comment]
So ome person on NixOS discord server suggested one simple solution. To eleminate problems like this, user will build river on own hardware, this will prevent problems like this to happen as pointed above Zig takes everything from host e.g libc, ABI, cpu architecture so building it on user's hardware will use those attrinutes according to their hardware, ABI amd libc. Building river doesn't take more then 20s at least on my old 2 core CPU and I don't think bulding it locally is big problem

**Comment by arqv** [comment]
> Zig takes everything from host e.g libc, ABI, cpu architecture so building it on user's hardware will use those attributes according to their hardware, ABI and libc.
This is exactly what the creator of the issue is pointing at as a problem, and the only good solution (at least in the Nix way) is to make all programs compiled with Zig target baseline x86_64 (or ultimately whichever features the Nixpkgs pipeline allows in C/C++ derivations)
The idea of packaging with Nix is not just "being able to compile and done" but rather being able to compile deterministically.

**Comment by ifreund** [comment]
> This is exactly what the creator of the issue is pointing at as a problem, and the only good solution (at least in the Nix way) is to make all programs compiled with Zig target baseline x86_64 (or ultimately whichever features the Nixpkgs pipeline allows in C/C++ derivations)
> The idea of packaging with Nix is not just "being able to compile and done" but rather being able to compile deterministically.

Indeed, passing `-Dtarget=x86_64-native` to `zig build` is the correct solution here, and will produce a binary for baseline x86_64. After the next zig release (planned for ~2 weeks from now) passing `-Dcpu=baseline` will be an even better way of doing this, allowing the target to be entirely detected from the host system and allowing specific cpu features to be enabled/disabled.
