### ISSUE TITLE
Proposal to split coq into coqide, coq

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#123105]
`coq` should be split into separate packages `coqide` and `coq`. At the moment, passing `buildIde = false` to `pkgs/applications/science/logic/coq/default.nix` causes a rebuild, which is unnecessary. As a contrast, the situation on OPAM is that `coqide` and `coq` can be built independently.

This would also help reduce unnecessary building of GUI components in Coq libraries.

Pinging @CohenCyril @vbgl @jwiegley

**Comment by CohenCyril** [comment]
Yes I agree. We previously discussed this with @Zimmi48 and @gares.

**Comment by CohenCyril** [comment]
Also, we should split `coq-core` and `coq-lib` and have `coq` be a meta package.

**Comment by Zimmi48** [comment]
Yes, but the latter might actually be hard to do even with Coq 8.14 without sacrificing native compilation support (that the full Dune build doesn't support yet).

**Comment by Alizter** [comment]
@Zimmi48 Is this currently not the case?

**Comment by Zimmi48** [comment]
Indeed, coq and coqide are split now starting with some not so recent version of Coq (8.14 I think). We could still split further coq-core / coq-stdlib, but that would be another issue.
