### ISSUE TITLE
Swappy is broken

### ISSUE THREAD

**Issue by timsofteng** [NixOS/nixpkgs#123153]
**Describe the bug**
I got this error on unstable when I invoke swappy from my terminal:

** (swappy:5998): CRITICAL **: 22:14:39.564: original image not loaded

(swappy:5998): GLib-GObject-CRITICAL **: 22:14:39.564: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**To Reproduce**
1. Invoke "swappy" from terminal.

**Expected behavior**
I guess it should start work:)

**Screenshots**
![image](https://user-images.githubusercontent.com/51912173/118375579-26ddf100-b5cb-11eb-9e1c-8f79c8c81390.png)

**Notify maintainers**

**Comment by superherointj** [comment]
@matthiasbeyer

**Comment by Artturin** [comment]
you need to give it a image with `-f file.png `or `grim -g "$(slurp)" - | swappy -f -`

**Comment by matthiasbeyer** [comment]
> so working as intended

I guess this can be closed then? I cannot test as I'm not using wayland anymore.

**Comment by timsofteng** [comment]
Yep, you are right guys. I'm sorry. I just misunderstand how this tool works.
Thanks!

**Comment by Algram** [comment]
@Artturin  Even with your command I am getting the following error now:
![image](https://user-images.githubusercontent.com/5053729/119165280-9e919d00-ba5d-11eb-9e82-3e8ab5add7e8.png)

It was working a week ago.
