### ISSUE TITLE
plex-media-player is unable to initialize OpenGL

### ISSUE THREAD

**Issue by JamieMagee** [NixOS/nixpkgs#123173]
**Describe the bug**

Unable to open `plex-media-player` due to OpenGL issues.

**To Reproduce**
1. Add `plex-media-player` to `environment.systemPackages`
2. Open `plex-media-player`
3. Errors with "Could not initialize OpenGL"

**Expected behavior**

`plex-media-player` works

**Screenshots**

![Screenshot from 2021-05-15 15-20-31](https://user-images.githubusercontent.com/1358764/118379697-27f22c80-b591-11eb-8a6d-9baa42690bcc.png)

**Additional context**
<details>

<summary>
Output from `glxinfo | grep OpenGL`
</summary>

OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

</details>

**Notify maintainers**

`plex-media-player` has no maintainers.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

- system: `"x86_64-linux"`
- host os: `Linux 5.11.16-hardened1, NixOS, 21.05.20210512.65d6153 (Okapi)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.4pre20210503_6d2553a`
- nixpkgs: `/nix/store/nslsx3573asj0clfyl4l7kgf9v7k53nl-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by superherointj** [comment]
Do you have OpenGL enabled on your system?
```
    hardware.opengl.enable = true;
    hardware.opengl.driSupport = true;
    hardware.opengl.driSupport32Bit = true;
```

**Comment by ecoughlan** [comment]
This has been fixed in upstream master (i believe in plexinc/plex-media-player@5430cd807250a8f7329baad76b15a363f35b53fa), but they haven't made a release in more than a year. With this upgrade it works again: ecoughlan/nixpkgs@f4e500137186f2ec707fe7f298b730b40de41dba

**Comment by JamieMagee** [comment]
Thanks for the debugging help!

I've opened an issue over at the plex-media-player repo. 🤞 they cut a new release that contains the fix. If not, we'll either need to mark the package as broken, or pin to a git commit as you've done in your fork.

**Comment by JamieMagee** [comment]
Upstream have tagged a release https://github.com/plexinc/plex-media-player/releases/tag/v2.58.1-ae73e074

**Comment by solson** [comment]
Is this fixed by https://github.com/NixOS/nixpkgs/pull/126651? It works on my machine, but I haven't gone back to test the version before that PR.

**Comment by jaen** [comment]
I made that PR due to this exact problem, I somehow missed this issue ~~" It used to work after the fix, but then the package broke (https://hydra.nixos.org/build/149092764) so I'm not sure if that's still the case.
