### ISSUE TITLE
Upcoming security update for Go 1.5

### ISSUE THREAD

**Issue by lfam** [NixOS/nixpkgs#12318]
The golang people have announced they will be issuing Go 1.5.3 on Wednesday
January 13 [0] in order to fix a bug in the math/big library. They request that
all programs compiled with vulnerable versions of the library be recompiled [1]:

> We will also announce and request that all Go programs using the math/big
> package that were compiled with version 1.5, 1.5.1, or 1.5.2 be recompiled
> with  1.5.3 (when released) due to the static linking nature of the Go
> toolchain.

[0]
https://groups.google.com/forum/#!topic/golang-nuts/lXeB-v400ZM

[1]
http://www.openwall.com/lists/oss-security/2015/12/21/6

**Comment by vcunat** [comment]
Heh, fixed a month ago and now they'll make a release :-)

**Comment by vcunat** [comment]
Pushed from PR #12384.
