### ISSUE TITLE
kicad contains broken symlink in share/metainfo

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixpkgs#123299]
**Describe the bug**
The kicad package installs a broken symlink to `share/metainfo`. This seems to be both on the commit the symlink was introduced in (b4034ccbc53) and master (0a0d1a5ecbe0c3842db822a46c64f5aa6fa90c10).

It causes problems when installing this package via home-manager (see nix-community/home-manager#2011 and #82685).

**To Reproduce**
```
> nix build -f . kicad
> nix run nixpkgs.symlinks -c symlinks -r result | grep dangling
dangling: /home/kai/Documents/code/nixpkgs/result/share/metainfo -> /nix/store/h0d6zk13m6605jxxr05iramb26ihld7s-kicad-base-5.1.10/share/metainfo
```

**Expected behavior**
I expect the symlink to point to an existing file, or not exist.

**Notify maintainers**
@evils 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.30, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(kai): `"home-manager, nixpkgs-21.05pre289536.c58b97674b1, nixpkgs-stable-20.09.4125.7974217f94c"`
 - channels(root): `"nixos-21.03pre267696.fab6fcdceb2"`
 - nixpkgs: `/home/kai/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: kicad
```

**Comment by evils** [comment]
woeps, sorry, i added that for kicad-unstable thinking it wouldn't affect the stable package to have a dead link there
(at least i think that's the issue, i'll look into it in a few hours)

(how does 0a0d1a5 relate to this issue? it's an erlang related change, which i don't think affects kicad)

**Comment by evils** [comment]
just to make sure you get notified
i opened #123329 to fix this

(i'm assuming you meant to point to b54dfb232e0 rather than the erlang commit)

**Comment by kwohlfahrt** [comment]
Thanks! I tagged 0a0d1a5ecbe0c3842db822a46c64f5aa6fa90c10 because that was the latest commit on `master` when I tested this, just in case it was fixed since.

**Comment by kwohlfahrt** [comment]
Seems to be working now, thanks very much for the quick fix :)
