### ISSUE TITLE
Can't update settings after Gnome 40 update

### ISSUE THREAD

**Issue by kamidon** [NixOS/nixpkgs#123265]
**Describe the bug**

**To Reproduce**
```
[amidon@kea-laptop:~]$ dconf read /org/gnome/shell/enabled-extensions 
['drive-menu@gnome-shell-extensions.gcampax.github.com', 'audio-input-switcher@anduchs', 'audio-output-switcher@anduchs', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'sound-output-device-chooser@kgshank.net', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'paperwm@hedning:matrix.org']

[amidon@kea-laptop:~]$ dconf write /org/gnome/shell/enabled-extensions "['drive-menu@gnome-shell-extensions.gcampax.github.com', 'audio-input-switcher@anduchs', 'audio-output-switcher@anduchs', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'sound-output-device-chooser@kgshank.net', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'paperwm@hedning:matrix.org']"
error: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dconf.service not found.
```
Note that the dconf key can be read fine, just not updated.

This can be reproduced with GUI tools as well. For example `gnome-extensions-app` is unable to change the status of extensions. The `dconf-editor` tool appears to update settings but after exiting and restarting the old value is still in place. 

I'm particularly interesting in the active gnome-shell extensions because I need to disable the `windowsNavigator` extension to work aound the problems with the overview freezing, but this is also more generic. I can't change most settings in `gnome-control-center` or `gnome-tweaks`. I suspect this is also why I keep seeing the Tour dialog every time I log in.

**Expected behavior**
The key should have been updated. 

**Screenshots**
The shell commands illustrate the problem well.

**Additional context**
I can't think of any other context that would be helpful.

**Notify maintainers**
I'm mentioning the Gnome team members since they seem the most likely to be able to help.
@hedning @jtojnar @dasj19 @maxeaubrey 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
[root@kea-laptop:/home/amidon]# nix-shell -p nix-info --run "nix-info -m" 
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/y2g5n52pljrmi7sy771njs1s8n58fjz3-bash-interactive-4.4-p23-dev
copying path '/nix/store/y2g5n52pljrmi7sy771njs1s8n58fjz3-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.05pre289339.83d907fd760 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05pre289339.83d907fd760, nixos-stable-19.09.1282.e6d584f6dd2, nixos-unstable-20.03pre201996.41d921292e9"`
 - channels(amidon): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
That is super weird. Could you try if adding

```nix
  systemd.packages = [ pkgs.dconf ];
```

to your configuration fixes it?

**Comment by jtojnar** [comment]
Also, before that, I would try running `systemctl status --user dconf`.

**Comment by kamidon** [comment]
First, thank you for the quick reply.

> Also, before that, I would try running `systemctl status --user dconf`.

Before making any changes:
```
[amidon@kea-laptop:~]$ systemctl status --user dconf
Unit dconf.service could not be found.
```
 
After adding `systemd.packages = [ pkgs.dconf ];` to `configuration.nix`:
```
[amidon@kea-laptop:~]$ systemctl status --user dconf
● dconf.service - User preferences database
     Loaded: loaded (/nix/store/lgv4q1fv0694xlg59niwas1dd90b2j2w-dconf-0.40.0/s>
     Active: inactive (dead)
       Docs: man:dconf-service(1)

[amidon@kea-laptop:~]$ dconf write /org/gnome/shell/enabled-extensions "['drive-menu@gnome-shell-extensions.gcampax.github.com', 'audio-input-switcher@anduchs', 'audio-output-switcher@anduchs', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'sound-output-device-chooser@kgshank.net', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'paperwm@hedning:matrix.org']"

[amidon@kea-laptop:~]$ 
```

So, that appears to have resolved the problem. I checked and i don't have anything touching `systemd.packages` in my `configuration.nix` or the overlay referred to from it where I maintain some local configuration modifications, I don't think there is something specific to my configuration that tripped this up.

I'm very happy to have the overview working as it was very hard not to trigger it by habit. :-)  I'd be happy to do anything else that can help narrow down why this was a problem in the first place.

**Comment by jtojnar** [comment]
It looks like dconf switched to d-bus activation so we need to add it to `systemd.packages`. But weirdly the activation works for me and the service is found, even though I do not have it in.

https://gitlab.gnome.org/GNOME/dconf/-/commit/2781a8684855e4120c9948d8b40880bafafe1b12
