### ISSUE TITLE
gnomeExtensions: system-monitor settings UI crashed

### ISSUE THREAD

**Issue by iosmanthus** [NixOS/nixpkgs#123260]
**Describe the bug**
`gnomeExtensions.system-monitor`'s upstream has[ fixed the problem ](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/678) that the settings UI doesn't display in GNOME 40. But the UI is still broken in NixOS.

**To Reproduce**
1. checkout `nixpkgs` to commit https://github.com/NixOS/nixpkgs/commit/225b7514d871eebf8a7b97c913111889d6a52c96
2. install `gnomeExtensions.system-monitor`

**Expected behavior**
launch settings from `Extensions` normally.

**Additional context**
Exceptions throws:
```
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/run/current-system/sw/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/compat.js:2:17
  @/run/current-system/sw/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/prefs.js:14:14
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/nix/store/7wp9ji35hklpbpyi7c5jvknwwr769igz-gnome-shell-40.1/share/gnome-shell/.org.gnome.Shell.Extensions-wrapped:7:17
  
```

**Notify maintainers**

@jtojnar 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.05.20210516.9b92a81 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.05pre289532.9b92a817238"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gnomeExtensions.system-monitor
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Right, this is a known bug:

https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/621#issuecomment-656788147

We would need to add Clutter to preferences using this method: https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues-unwrappable-package-gnome-shell-ext

Or preferably change the extension so that it does not depend on Clutter in preferences.

**Comment by jtojnar** [comment]
I opened a PR with a fix upstream: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/693
