### ISSUE TITLE
Package Lens - The Kubernetes IDE

### ISSUE THREAD

**Issue by glottologist** [NixOS/nixpkgs#123356]
**Project description**
A Kubernetes IDE for development and debugging.

**Metadata**

* homepage URL: https://k8slens.dev/
* source URL: https://github.com/lensapp/lens
* license: mit
* platforms:  linux

**Comment by mschuwalow** [comment]
Unless I'm mistaken this is already packaged https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/cluster/lens/default.nix#L35

**Comment by teto** [comment]
It is packaged.
