### ISSUE TITLE
Viber crashes under wayland

### ISSUE THREAD

**Issue by timsofteng** [NixOS/nixpkgs#123352]
**Describe the bug**
Viber doesn't work on sway. I get this error:
viber
qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
qt.qpa.wayland: Available client buffer integrations: ()
failed to acquire GL context to resolve capabilities, using defaults..
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")

**To Reproduce**
1. Install sway.
2. Run viber inside of terminal emulator.

**Expected behavior**
Should work:)

**Screenshots**
![image](https://user-images.githubusercontent.com/51912173/118479301-877b4400-b719-11eb-97db-de09d763e271.png)

**Notify maintainers**
@jagajaga

**Comment by Artturin** [comment]
a workaround `QT_QPA_PLATFORM=xcb viber`

**Comment by timsofteng** [comment]
> QT_QPA_PLATFORM=xcb viber

yep. It works!
Can it this variable be added into package until qt will fix?
