### ISSUE TITLE
LLVM output reorganization makes bfd unable to find LLVMGold.so

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#123361]
**Describe the bug**

Minimal reproducer for the issue is enabling LTO for clang-based builds:

```nix
with import ./. {};

runCommandWith {
  name = "test";
  stdenv = llvmPackages_11.stdenv;
  derivationArgs = {
    test = ''
      #include <stdio.h>
      int main() {
        puts("Hello");
        return 0;
      }
    '';
    passAsFile = [ "test" ];
  };
} ''
  $CC -o $out -flto -x c $testPath
''
```

```console
$ nix-build test.nix
these derivations will be built:
  /nix/store/54i5cxh7d4s3zx7p0kdbvpw14r8iaill-test.drv
building '/nix/store/54i5cxh7d4s3zx7p0kdbvpw14r8iaill-test.drv'...
/nix/store/77i6h1kjpdww9zzpvkmgyym2mz65yff1-binutils-2.35.1/bin/ld: /nix/store/5xn1kwilwh8m8zz8h0g0c4a4p20xib9j-clang-11.1.0/bin/../lib/LLVMgold.so: error loading plugin: /nix/store/5xn1kwilwh8m8zz8h0g0c4a4p20xib9j-clang-11.1.0/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
builder for '/nix/store/54i5cxh7d4s3zx7p0kdbvpw14r8iaill-test.drv' failed with exit code 1
error: build of '/nix/store/54i5cxh7d4s3zx7p0kdbvpw14r8iaill-test.drv' failed
```

Seems to affect all clang versions.

The culprit is likely this snippet: <https://github.com/NixOS/nixpkgs/blob/183350a3e1d7882838fd328538619f99d3ab51f4/pkgs/development/compilers/llvm/11/clang/default.nix#L68-L70>

Most likely the easiest fix is to link `LLVMGold.so` to `$out/lib/LLVMGold.so` for now. If everyone is okay with that, I can implement that fix for the current `staging-next` cycle. In the long term it may be possible to patch this behavior in clang. 

cc @jonringer (release, staging-next) @Ericson2314 @thefloweringash (multiple outputs for LLVM)

**Comment by jonringer** [comment]
just remember that most llvm changes will be a stdenv-rebuild for darwin.

**Comment by sternenseemann** [comment]
> just remember that most llvm changes will be a stdenv-rebuild for darwin.

Indeed, what would you prefer: Fixing this in this staging-next cycle (early, as in merge a PR today), or after branch-off at some point via staging-21.05.

**Comment by jonringer** [comment]
To not overload the builders right now, I would prefer the normal staging cycle. Next week we will have the `staging-21.05` branch and can just backport import fixups

**Comment by sternenseemann** [comment]
Confirmed that this is an issue with all llvm package sets we have. Will submit a PR later today.

**Comment by Ericson2314** [comment]
This fix looks good to me. I suppose this is less a regression from the patch than me being over eager changing `$out` to `$lib`, because if upstream had all the right logic we wouldn't need the symlink in the first place.

**Comment by Ericson2314** [comment]
Maybe just explain in a code comment "Clang looks relative the binary to find plugins, unfortunately"?

**Comment by sternenseemann** [comment]
> This fix looks good to me. I suppose this is less a regression from the patch than me being over eager changing `$out` to `$lib`, because if upstream had all the right logic we wouldn't need the symlink in the first place.

Yeah that's right. My current ambition is actually to patch the path in clang because it is really easy and doesn't require us to have a lib directory in `$out` and `$lib` and we can get rid of the symlink completely. Currently waiting for the 8 clang builds to finish.

**Comment by Ericson2314** [comment]
@sternenseemann Well I am thinking that might be tricky to upstream if there isn't any search path at all. But maybe there is and we just never took advantage of it?

**Comment by sternenseemann** [comment]
> @sternenseemann Well I am thinking that might be tricky to upstream if there isn't any search path at all. But maybe there is and we just never took advantage of it?

Upstreamability is a valid concern, #123551 doesn't have that so we may want to fall back on the old solution. Not sure.
