### ISSUE TITLE
Psitransfer

### ISSUE THREAD

**Issue by hyshka** [NixOS/nixpkgs#123383]
**Project description**
 Simple open-source self-hosted file sharing solution. 

**Metadata**

* homepage URL: https://github.com/psi-4ward/psitransfer
* source URL: https://github.com/psi-4ward/psitransfer
* license: bsd
* platforms: linux

**Comment by hyshka** [comment]
I may have a go at this myself over the next few weeks but figured I'd start by posting it here.

**Comment by abathur** [comment]
Looks like you contributed this in https://github.com/NixOS/nixpkgs/pull/148054 :)
