### ISSUE TITLE
machinectl does not work

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#12347]
```
# machinectl pull-raw --verify=no https://download.fedoraproject.org/pub/fedora/linux/releases/23/Cloud/x86_64/Images/Fedora-Cloud-Base-23-20151030.x86_64.raw.xz
Failed transfer image: The name org.freedesktop.import1 was not provided by any .service files
```

I remember this getting mentioned somewhere recently, but I don't remember where..

**Comment by pSub** [comment]
This looks relevant http://comments.gmane.org/gmane.linux.debian.devel.systemd/6247. However I don't have time to dig into this (I don't even know machinectl).

**Comment by kragniz** [comment]
`systemd-importd` will need to be enabled for this to work. FWIW, debain handles this by having a 'systemd-container' package containing `systemd-nspawn`, `systemd-machined`, `machinectl` and `systemd-importd` to avoid adding the extra dependencies to systems that don't care about containers.

It might be worth doing something similar with our systemd.

**Comment by Profpatsch** [comment]
triage: what’s the status?

**Comment by jgillich** [comment]
Nothing changed.

**Comment by flokli** [comment]
This should be fixed since https://github.com/NixOS/nixpkgs/pull/70352 - `nixosTests.systemd-importd` also contains a test verifying this. Please comment if it doesn't.
