### ISSUE TITLE
steam: paradox launcher needs json-glib (transitive)

### ISSUE THREAD

**Issue by jbalme** [NixOS/nixpkgs#123447]
**Describe the bug**
json-glib seems to be a new transitive dependency of tracker/gtk, which the Paradox launcher needs. Somehow it isn't being pulled into the Steam container.

**To Reproduce**
1. Install Steam
2. Install a Paradox game (eg. Stellaris)
3. Try to start the game

**Expected behavior**
Instead of the launcher working as usual, it doesn't launch at all.

Launching it directly yields the following error:
```
$ ~/.paradoxlauncher/launcher-v2.2021.1/Paradox\ Launcher
/home/user/.paradoxlauncher/launcher-v2.2021.1/Launcher: /steamrt/amd64/usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0: no version information available (required by /nix/store/yv1pq8q93bamcrgddl35ps26n7kd0jzn-tracker-3.1.1/lib/libtracker-sparql-3.0.so.0)
/home/user/.paradoxlauncher/launcher-v2.2021.1/Launcher: symbol lookup error: /nix/store/yv1pq8q93bamcrgddl35ps26n7kd0jzn-tracker-3.1.1/lib/libtracker-sparql-3.0.so.0: undefined symbol: json_generator_to_gstring, version libjson-glib-1.0.so.0
```

**Additional context**
Adding json-glib to steam's fhs wrapper libraries is sufficient to start the launcher, but should it be propagated by gtk implicitly?

**Notify maintainers**

@jagajaga @jonringer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.35, NixOS, 21.05.20210513.d1601a4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.05pre275232.29b0d4d0b60"`
 - channels(user): `"nixos-21.05pre277486.f5e8bdd07d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- steam
- steam-run
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
which game? I tried eu4 and CK3 and both launch fine

**Comment by jbalme** [comment]
Stellaris. Funny that it seems to work with the others, I suppose it could be something specific to my system?

**Comment by mweinelt** [comment]
> I suppose it could be something specific to my system?

Unlikely, steam games run in a bubblewrap sandbox, so your host system doesn't matter much.
