### ISSUE TITLE
Runtime conflict for libpng in ROOT 6.22.08

### ISSUE THREAD

**Issue by yipengsun** [NixOS/nixpkgs#123408]
**Describe the bug**
I'm trying to use latest unstable branch in a flake that contains ROOT 6.22.08. The `root` package contains a program `rootbrowse`. When I try to launch that, I got the following segmentation fault, hinting on build time and runtime conflict for `libpng`:

```libpng warning: Application built with libpng-1.2.23 but running with 1.6.37
TASImage::GetMask:0: RuntimeWarning: No image
libpng warning: Application built with libpng-1.2.23 but running with 1.6.37
TASImage::GetMask:0: RuntimeWarning: No image
Error in <TGVScrollBar::TGVScrollBar>: arrow_*.xpm not found
 *** Break *** segmentation violation
 Generating stack trace...
<omitted here, see attached log>
```

**To Reproduce**
1. Use `flake.nix` from [this repo](https://github.com/umd-lhcb/root-curated)
2. `nix develop --no-update-lock-file`
3. `rootbrowse`

**Expected behavior**
The program should run w/o problem

**Additional context**
[root_6_22_08_segfault_libpng.txt](https://github.com/NixOS/nixpkgs/files/6496738/root_6_22_08_segfault_libpng.txt)

The command line `root` runs OK, provided that no graphical interface is invoked. Same segmentation fault would occur if in a `ROOT` shell, I do the following:
```
TBrowser a
```

**Notify maintainers**

@veprbl 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Not sure if this is useful, as I tried to install `nix-info` as part of my flake yet I still get this:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.9.12, NixOS, 20.09.2205.65c9cc79f1d (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"nixos-20.09.3925.63adedf6319"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
Can you reproduce the crash with
```bash
nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/83d907fd760d9ee4f49b4b7e4b1c6682f137b573.tar.gz -p root --pure --run "root"
```
?

**Comment by yipengsun** [comment]
Yes:

```
root [1] TBrowser a
libpng warning: Application built with libpng-1.2.23 but running with 1.6.37
Warning in <TASImage::GetMask>: No image
libpng warning: Application built with libpng-1.2.23 but running with 1.6.37
Warning in <TASImage::GetMask>: No image
Error in <TGVScrollBar::TGVScrollBar>: arrow_*.xpm not found

 *** Break *** segmentation violation
 Generating stack trace...
 0x00007f5fcdc392c8 in TGListBox::Resize(unsigned int, unsigned int) + 0x38 from /nix/store/qy96xgg4wbl7n38m61bjicisf725mbyx-root-6.22.08/lib/libGui.so
<omitted>
```

**Comment by veprbl** [comment]
@yipengsun I don't have an access to NixOS at the moment to reproduce. Do you think you could git-bisect this?

**Comment by yipengsun** [comment]
Yes. I'll try to do this sometime this week, if I have time.

Just to be sure, everything is OK on macOS?

**Comment by veprbl** [comment]
> Yes. I'll try to do this sometime this week, if I have time.
> 
> Just to be sure, everything is OK on macOS?

Yes, it works great:
```
# nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/83d907fd760d9ee4f49b4b7e4b1c6682f137b573.tar.gz -p root --pure --run "root"
   ------------------------------------------------------------------
  | Welcome to ROOT 6.22/08                        https://root.cern |
  | (c) 1995-2020, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosx64 on Mar 10 2021, 14:20:04                      |
  | From tags/v6-22-08@v6-22-08                                      |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

root [0] TBrowser a
(TBrowser &) Name: Browser Title: ROOT Object Browser
root [1] .q
# 
```

**Comment by yipengsun** [comment]
I did a poorman's bisect with `nix-shell -I nixpkgs=<...> -p root --pure`:

```
Dec 26 2019  0b28198f23fab730a797e865e741d9fd8a50f1a3  Y  root: wrap python executables
Dec 20 2020  bb9b5c5b753e187177e687baded6a6a87a21fb1d  Y  Merge master into staging-next
Dec 20 2020  ce5f25d57e0864596a027655d3d62f1ccb25cbe4  Y  Merge pull request #107236 from marsam/update-postgresql-postgis
Dec 21 2020  7f0b9be7233d6f1dda4a7c21afe4961dfbb0450d  Y  python3Packages.msgpack: 1.0.0 -> 1.0.2
Dec 17 2020  7d6e0d532461eb7bdbddd55df3fdda5fc4dedfb7  N  root: 6.18.04 -> 6.20.08
```

I think the commit that breaks ROOT is the 7d6e0d532461eb7bdbddd55df3fdda5fc4dedfb7. The commit immediately before that still has a working ROOT (6.18).

## 7d6e0d532461eb7bdbddd55df3fdda5fc4dedfb7
```
libpng warning: Application built with libpng-1.2.23 but running with 1.6.37
Warning in <TASImage::GetMask>: No image
libpng warning: Application built with libpng-1.2.23 but running with 1.6.37
Warning in <TASImage::GetMask>: No image
Error in <TGVScrollBar::TGVScrollBar>: arrow_*.xpm not found
```

**Comment by yipengsun** [comment]
On a side, I first tried `nix-bisect` with the following thing:
```
git bisect run bisect-env root -e "TBrowser a" -q
```

But `git` complains:
```
 0x00007f263868eded in __libc_start_main + 0xed from /nix/store/1jn6apz0fa9h9x7rl3v6vwiymwnjznwv-glibc-2.32-40/lib/libc.
 0x000000000040115a in _start + 0x2a from /nix/store/wjwm97rs48ynzi9kcv2hwys6wx8p003h-root-6.22.08/bin/root.exe
Root > bisect run failed:
exit code 129 from 'bisect-env root -e TBrowser a -q' is < 0 or >= 128
```

Do you have any suggestion to make this automated bisect work?

**Comment by veprbl** [comment]
> Do you have any suggestion to make this automated bisect work?

git-bisect expects certain return codes to be returned. Perhaps you could try wrapping it in https://github.com/timokau/nix-bisect

**Comment by veprbl** [comment]
> I think the commit that breaks ROOT is [7d6e0d5](https://github.com/NixOS/nixpkgs/commit/7d6e0d532461eb7bdbddd55df3fdda5fc4dedfb7). The commit immediately before that still has a working ROOT (6.18).

That is helpful. Google says this is an old problem [1], so it has probably to do with incomplete afterimage unvendoring.

[1] https://root-forum.cern.ch/t/tbrowser-is-not-opening/32280

**Comment by veprbl** [comment]
In the end, the problem was this one: https://root-forum.cern.ch/t/root-xpm-error-on-ubuntu-revisited/4552/10

**Comment by yipengsun** [comment]
Wow, this is a very old "problem" then. I guess previously `libAfterImage` was not used as a build input so that we never noticed this.
