### ISSUE TITLE
Refactor GHC expressions

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#123599]
For lack of a better place my attempt at a to do list (feel free to edit and expand):

* [x] Use new `stdenv.targetPlatform.linker` to check for gold
* [ ] Separate wrapper from compiler derivation 
* [x] Generic expression if possible
* [ ] Support same set of features for all expressions as far as possible
* [ ] Always build a cross compiler

cc @NixOS/haskell

**Comment by Ericson2314** [comment]
@hsyl20 and I are making changes upstream to GHC such that we can build the compiler itself and all the libraries separately like we do for LLVM.

My plan is to basically let the status quo limp long until that's done (by 2022 I hope?!) And then rewire using that. I think cabal2nix will be be able to do 95% of the compiler itself, and the only thing that will be more manual is the RTS and settings file.

**Comment by sternenseemann** [comment]
Interesting, that sounds good! Initially I thought it would be quite trivial to have a `common.nix` for all GHCs, but as it turns out quite a bit of things are different for the GHC versions, so this would certainly be quite a bit of work.

I was contemplating having a common expression going forward (starting with 9.0.x?), but haven't had the time yet to look into it. Also one thing I'd like to have would be to move the GHC wrapper script into its own derivation (having felt the pain of recompiling after adding a tiny tweak to it…) like we do for `cabal2nix`.

**Comment by Ericson2314** [comment]
Yeah we should do bog-standard cabal2nix derivations, and everything interestitn will be RTS/wrapper which will include those settings I mentioned.

**Comment by sternenseemann** [comment]
Closing, since we have a common expression for all hadrian GHCs now. I think refactoring the old ones is likely just busywork that wouldn't yield any improvements at this point. Making changes to multiple of the make GHCs at the same time works tolerably well with `patch(1)`.
