### ISSUE TITLE
code-server: please update from 3.8.0 -> 3.12.0

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#123546]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: code-server

current version: 3.8.0
desired version: ~~3.10.1~~ 3.12.0

###### Notify maintainers

maintainers: @offlinehacker

###### Note for maintainers

Please tag this issue in your PR.

Additionally, there is an outdated PR bumping version to 3.9.0: #118317 - it should either be continued or superseded.

**Comment by alexvorobiev** [comment]
The current version is now 3.10.2

**Comment by austinbutler** [comment]
Currently trying to get 3.11.0 to work. The main issue appears to be an SSL error trying to fetch a fork of an NPM package from Git (since it isn't published to NPM).

https://github.com/cdr/code-server/blob/v3.11.0/lib/vscode/extensions/notebook-markdown-extensions/package.json#L49

**Comment by austinbutler** [comment]
Solved by https://github.com/NixOS/nixpkgs/pull/143930.
