### ISSUE TITLE
X server doesn't start since unstable channel update

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#12352]
Since the channel update, X won't start, giving this error message repeatedly

```
(EE) intel(0): [DRI2] DRI2SwapComplete: bad drawable
```

here is the X log in the broken case (newest nixos-unstable)
http://lpaste.net/148905

and here is the X log in the working case (the previous nixos-unstable)
http://lpaste.net/148904

it seems like they are pretty much identical through line 435, and from there on there may be some difference in how the hardware is detected? but I don't see what is causing the problem.

**Comment by anderspapitto** [comment]
in terms of configuration, I have (in both cases) the kernel set to linuxPackages_latest, which is 4.3.0 in both cases.

**Comment by vcunat** [comment]
[Upstream claims that this "error" message is harmless](https://bugs.freedesktop.org/show_bug.cgi?id=92505#c3), but I can't see any other relevant error in this log. I don't know.

**Comment by anderspapitto** [comment]
after more investigation, this was a red herring. somehow display-manager.service file had some garbage in. nix-store --delete and rebuilding again fixed it
