### ISSUE TITLE
tests.trivial is always a changed path

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#123572]
There is an issue in the test added by #123111. This line
https://github.com/NixOS/nixpkgs/blob/cc60f81e69154789ad3e23f0ec60110ed3f7aece/pkgs/build-support/trivial-builders/test.nix#L16
introduces a dependency on the contents of nixpkgs, making every change evaluate with a different hash.

cc @roberth @Profpatsch

**Comment by veprbl** [comment]
Steps to reproduce:
```
# nix-instantiate https://github.com/NixOS/nixpkgs/archive/de8dbb21fbf740927ad2888bac59215a92a64ee0.tar.gz -A tests.trivial
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/3kllg4j6rxjbsd4fdii7cg143wm5x8bq-vm-test-run-nixpkgs-trivial-builders.drv
# nix-instantiate https://github.com/NixOS/nixpkgs/archive/56f0c92fadf0aa839ecc75db738d2e1f3ffb1e14.tar.gz -A tests.trivial
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/3737mgd1drcid4va2df3cs8w0rdqdi73-vm-test-run-nixpkgs-trivial-builders.drv
# nix-diff /nix/store/3kllg4j6rxjbsd4fdii7cg143wm5x8bq-vm-test-run-nixpkgs-trivial-builders.drv /nix/store/3737mgd1drcid4va2df3cs8w0rdqdi73-vm-test-run-nixpkgs-trivial-builders.drv
- /nix/store/3kllg4j6rxjbsd4fdii7cg143wm5x8bq-vm-test-run-nixpkgs-trivial-builders.drv:{out}
+ /nix/store/3737mgd1drcid4va2df3cs8w0rdqdi73-vm-test-run-nixpkgs-trivial-builders.drv:{out}
• The input derivation named `nixos-test-driver-nixpkgs-trivial-builders` differs
  - /nix/store/qwdqd88wrr3irnrihxmn69l4x6m29nfm-nixos-test-driver-nixpkgs-trivial-builders.drv:{out}
  + /nix/store/r81nhqj6rai1m1qs4flw04f54djwj455-nixos-test-driver-nixpkgs-trivial-builders.drv:{out}
  • The input source named `source` differs
  • The environments do not match:
      testScript=''
      machine.succeed("""
        cd /nix/store/qgfcfww929y9s5527xixhlhfs4xxbwxr-source/nix/store/6sr5a0lgaqgp94vava5g6dh85ghjn3h0-source
        ./pkgs/build-support/trivial-builders/test.sh 2>/dev/console
      """)
      
  ''
• Skipping environment comparison
```

**Comment by roberth** [comment]
You're absolutely right, but I don't think I see the impact of this fact.
It's not recursed into (no `recurseIntoAttrs`/`recurseForDerivations`) and it's not even built by ofborg. #123369

The test needs to compare `nix-store -q` results, but perhaps the actual evaluation can be removed from it; injected as store paths by the test runner instead. It won't make the test easier to read :(

**Comment by veprbl** [comment]
@roberth This currently impacts every ofborg evaluation. For example: https://gist.github.com/GrahamcOfBorg/da36c4dce51ab35a635f77a9becf364f

**Comment by Profpatsch** [comment]
I have no idea how to solve this. Why would ofborg have a different hash for multiple evaluations? Cause it puts stuff in the nixpkgs path?

**Comment by roberth** [comment]
@Profpatsch `pkgs.path` is the whole Nixpkgs source tree, which kinda always changes. Here's a solution #123597. Not pretty but still quick to run outside the sandbox and solves this issue.

**Comment by veprbl** [comment]
Still an issue https://gist.github.com/GrahamcOfBorg/e62104c50cacbf1a22b807a05beba770 ?

**Comment by roberth** [comment]
Ofborg doesn't rebase PRs so if the PR is based on a master that's of the wrong age, you'll still see this happen. Please check that the PR includes the improved test.

**Comment by veprbl** [comment]
@roberth I did, and it's been more than 12 hours since the commit landed.

At the same time my original repro doesn't see the issue:
```
# nix-instantiate https://github.com/NixOS/nixpkgs/archive/8e9d803bac9faaa6fcd619ab2131375b7e2be64d.tar.gz -A tests.trivial
unpacking 'https://github.com/NixOS/nixpkgs/archive/8e9d803bac9faaa6fcd619ab2131375b7e2be64d.tar.gz'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/xy4x1frfxfxzbxw3kf5d4zcpn5pr4f4s-vm-test-run-nixpkgs-trivial-builders.drv
# nix-instantiate https://github.com/NixOS/nixpkgs/archive/68c618cba3855568e9a3194823354e049635666d.tar.gz -A tests.trivial
unpacking 'https://github.com/NixOS/nixpkgs/archive/68c618cba3855568e9a3194823354e049635666d.tar.gz'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/xy4x1frfxfxzbxw3kf5d4zcpn5pr4f4s-vm-test-run-nixpkgs-trivial-builders.drv
```

**Comment by roberth** [comment]
It's a broader issue that applies to all NixOS tests, https://github.com/NixOS/nixpkgs/pull/117275, but it went under the radar.

**Comment by veprbl** [comment]
This seems to be fixed now. @roberth Thanks for looking into this!
