### ISSUE TITLE
CLING: `warning: argument unused during compilation: '-nostdinc++'`

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nixpkgs#123534]
cc @thomasjm
I don't remember what the situation is with cling packaging, but I just got cling from unstable.
Per https://github.com/jupyter-xeus/xeus-cling/issues/404 , you can start cling in "c mode" by passing `-x c`.
When I do this the following warning is given:
```
$ cling -x c
warning: argument unused during compilation: '-nostdinc++'

***************** CLING *****************
* Type C code and press enter to run it *
*            Type .q to exit            *
*****************************************
[cling]$ .q
```

The content of the cling wrapper (heh) is as follows: (newlines added)
```
$ echo $(which cling) && cat $(which cling) 
/nix/store/6v52ljq65fmqcv0gz5z49cgavhx5lhdn-cling-0.7/bin/cling
#! /nix/store/68c5b0h2w2ab57sbas1b4m073ik8hlm5-bash-4.4-p23/bin/bash -e
exec "/nix/store/p7pwn7a4kia9zrcxfaywv492cg8ryvzp-cling-unwrapped-0.7/bin/cling" \
 -isystem  /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../include/c++/10.2.0 \
 -isystem  /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-unknown-linux-gnu \
 -isystem  /nix/store/q8rv03yvqsfipnxwyj0sb6lqs50y5b3q-gcc-10.2.0/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../include/c++/10.2.0/backward \
 -nostdinc \
 -nostdinc++ \
 -isystem /nix/store/vr4977307zkjprfkivi4lgbzlvig3y9j-glibc-2.32-40-dev/include \
 -I /nix/store/p7pwn7a4kia9zrcxfaywv492cg8ryvzp-cling-unwrapped-0.7/include \
 -I /nix/store/p7pwn7a4kia9zrcxfaywv492cg8ryvzp-cling-unwrapped-0.7/lib/clang/5.0.2/include \
 "$@"
```

The question comes to mind is do those included headers need to change depending on if cling is in C mode, or otherwise?

cc @Axel-Naumann

**Comment by thomasjm** [comment]
We include both C and C++ standard headers. It doesn't seem harmful to have the C++ ones on the system path when you're in C mode. (When you run on a traditional Linux system, clang will look at normal system paths and usually find them anyway.)

Have you encountered any problems in C mode?

**Comment by deliciouslytyped** [comment]
Related https://github.com/root-project/cling/issues/417 https://github.com/root-project/cling/issues/419

**Comment by thomasjm** [comment]
I'm going to just close this since the issue seems to be innocuous, feel free to add more information if it's causing a problem.
