### ISSUE TITLE
lvm2 blkdeactivate shell script has incorrect hardcoded paths

### ISSUE THREAD

**Issue by lonetech** [NixOS/nixpkgs#123639]
**Describe the bug**
Shell script `blkdeactivate` has hardcoded paths to required tools like `lsblk`, `umount` and `sort`. Those paths (`/bin` in these cases) do not exist on NixOS. 

**To Reproduce**

1. Identify a non-critical drive, e.g. a USB stick. 
2. Run `blkdeactivate /dev/whatever` to unmount and deactivate (from lvm, dm, md, vdo layers) it. 

**Expected behavior**
Device should be unmounted and unmapped, leaving only the block device. It should no longer be mounted or participate in software RAID etc. 

**Screenshots**
```
# blkdeactivate /dev/disk/by-id/usb-IBM-DTLA_-307075_293093F06178-0\:0 
/run/current-system/sw/bin/blkdeactivate: line 47: /bin/umount: No such file or directory
Deactivating block devices:
/run/current-system/sw/bin/blkdeactivate: line 375: /bin/lsblk: No such file or directory
/run/current-system/sw/bin/blkdeactivate: line 375: /bin/sort: No such file or directory
/run/current-system/sw/bin/blkdeactivate: line 436: /bin/lsblk: No such file or directory
/run/current-system/sw/bin/blkdeactivate: line 439: SKIP_DEVICE_LIST: bad array subscript
```

**Additional context**
This script failing could cause problems with e.g. shutdowns on systems with software RAID. 

**Notify maintainers**
@raskin @ajs124 @flokli 

**Metadata**
 - system: `"i686-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.3343.8d82c865b41 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
Sorry, my first bug report and I don't know what to fill in here. 
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - nixpkgs.lvm2
# a list of nixos modules affected by the problem
module:
```

**Comment by ajs124** [comment]
We could just replace them with the proper store paths during the build, but that 

1. could lead to closure bloat
2. leads to a dependency cycle/infinite recursion when pulling in `util-linux` (not `util-linuxMinimal`) or `mdadm`

**Comment by lonetech** [comment]
I'm guessing the purpose of the hardcoded paths is to avoid searching drives it may have already deactivated. Some of them are tested for and optional, including mdadm, vdo, multipathd and lvm. Perhaps they could check the path or use /run/current-system/sw/bin?

mountpoint, umount, findmnt, lsblk and sort aren't tested for. Are those acceptable as dependencies? They appear to be in util-linux and coreutils. 

I am unfamiliar with the intricacies of how a weak dependency or alternatives could be handled in Nix, and not sure when it's critical that this script in particular not use the search path.

**Comment by ajs124** [comment]
It should already find `lvm`, since that's the same store path and it tries to find it in "`@SBINDIR@`".

The problem with just adding `/run/current-system/sw/bin` into the search path is that that's impure. It relies on how NixOS works and while `util-linux` and `coreutils` are most likely in there (on NixOS), they're not guaranteed to be.

**Comment by lonetech** [comment]
It's not clear to me where the loop comes from. It seems to me `lvm2` could depend on `coreutils` and `utillinux` without damage (though if the bloat of pulling in non-minimal packages is too much, one could spin off `blkdeactivate`; Debian has it in the `dmsetup` package, for instance). For the others, I guess it's more complicated and would involve something like a use flag. I didn't find `vdo`, but `multipath-tools` and `mdadm` don't seem to depend on `lvm2`, so they wouldn't loop (at first glance). 

As a side note, I consider it a distinct bug that the script fails to take its failure into account; this would typically be handled by `set -e`. At the moment, it's a tool that doesn't work unless run in an FHS environment, but it appears nothing (except me, planning to make a disk management tool) tried to use it, so perhaps it's not as severe as I first thought.

**Comment by ajs124** [comment]
There's a dependency cycle for `util-linux`, because `util-linux` depends (optionally, but on by default) on `systemd`, `systemd` (opt. but default) on `cryptsetup` and `cryptsetup` depends on `lvm2`.

`mdadm` depends on `util-linux` (because it needs blkid), therefore creating the same dependency cycle.

**Comment by ajs124** [comment]
We could maybe split this script into a separate package or output.

> I didn't find `vdo`

It's not packages yet, AFAIK.

> I consider it a distinct bug that the script fails to take its failure into account

:+1: although I'd say that's an upstream issue.

> but it appears nothing (except me, planning to make a disk management tool) tried to use it

There is a systemd service (`lib/systemd/system/blk-availability.service`) which invokes it, but that's probably not used by anyone.

**Comment by flokli** [comment]
I think it's fine for an ad-hoc script that users run to pick things from $PATH - at least if we're talking about certain tools that should be available in a default system. Similarly, we also invoke `systemctl` from `/run/current-system/systemd/bin` (or `$PATH`) instead of hardcoding it to the systemd package.

**Comment by ajs124** [comment]
Probably. AFAIR the problem is that the script hardcodes `/bin` and `/sbin` though. Feel free to review my attempt at fixing this in #123743 @flokli
