### ISSUE TITLE
redshift: 'vidmode' option disappeared

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#123687]
**Describe the bug**

Since gtk2 switched from mesa to libGL in  cd65dfa14cd2b0e665dd37595ded55b23f1e52cd, `redshift -m list` no longer lists `vidmode` as an option.

I guess we don't use it anymore? I used it to be able to (manually) adjust the brightness of my display independently of redshift (autmatically) adjusting the color balance.

**Comment by raboof** [comment]
never mind I guess

**Comment by CyberShadow** [comment]
> never mind I guess

What do you mean?

Arch Linux's redshift supports `vidmode`, why doesn't NixOS's?

**Comment by raboof** [comment]
> > never mind I guess
> 
> What do you mean?

I meant that I no longer felt strongly about this issue, and since it was 'marked as stale due to inactivity', decided to close my issue.

**Comment by CyberShadow** [comment]
Thanks. I'll reopen this issue because I would like to fix this problem :)

https://github.com/NixOS/nixpkgs/pull/322352

**Comment by CyberShadow** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/322352 (not sure why this issue wasn't auto-closed), thank you @Aleksanaa.

**Comment by raboof** [comment]
> Fixed in #322352 , thank you @Aleksanaa.

awesome

> (not sure why this issue wasn't auto-closed)

(I think GitHub recognizes "Fixes #xyz" as closing the issue, but sees "Fixes issues #xyz" as a 'regular' reference)
