### ISSUE TITLE
15.09 branch wifi failure (regression)

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#12361]
Wifi module doesn't work when using the latest stable 15.04 ISO: https://nixos.org/releases/nixos/15.09/nixos-15.09.911.53286a8/nixos-graphical-15.09.911.53286a8-x86_64-linux.iso

However using the older 15.04 ISO: https://nixos.org/releases/nixos/15.09/nixos-15.09.706.45128de/nixos-graphical-15.09.706.45128de-x86_64-linux.iso the wifi works again. (Also wifi works on Ubuntu)

The problem is the iwlwifi kernel module cannot start.

On the journalctl, I get a message like: `iwlwifi Failed to start init ucode -110`. The radio is not blocked.

Wifi hardware is: `Intel Corporation Wireless 7265 (rev 59)`

**Comment by CMCDragonkai** [comment]
Could someone find a time to bisect between the 2 commits `45128de` (good) to `53286a8` (bad) which has 205 commits between the 2 states. I don't currently have the infrastructure to compile and test nixos builds.

**Comment by lelandmiller** [comment]
I might not have time to look in depth at this, but I can confirm this behavior. It is not just the live CD, but the dist as a whole if that helps at all.

**Comment by CMCDragonkai** [comment]
It has to do with the kernel. Upgrading to 4.1 made it work again. There was some kernel change in 15.09 that caused this problem.

**Comment by lelandmiller** [comment]
Thank you, that kernel worked for me.

**Comment by bruceadams** [comment]
I've seen this problem as well, where running an upgrade for 15.09 breaks WiFi. Before the upgrade (when WiFi was working) I had

    Linux version 3.18.24 (nixbld1@machine) (gcc version 4.9.3 (GCC) ) #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970

After upgrading (no WiFi) I had

    Linux version 3.18.25 (nixbld@localhost) (gcc version 4.9.3 (GCC) ) #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970

`journalctl` for the failure shows

    iwlwifi 0000:02:00.0: Detected Intel(R) Dual Band Wireless AC 7265, REV=0x210
    ...
    iwlwifi 0000:02:00.0: Failed to start INIT ucode: -110
    iwlwifi 0000:02:00.0: Failed to run INIT ucode: -110

The suggestion of using Linux 4.1 avoids the problem for me as well. Thanks @CMCDragonkai! To be precise, I added this to my `/etc/nixos/configuration.nix`:

    boot.kernelPackages = pkgs.linuxPackages_4_1;

**Comment by danbst** [comment]
(triage) we have now 16.09, this issue is outdated
