### ISSUE TITLE
minio: access key is not properly set

### ISSUE THREAD

**Issue by antoinerg** [NixOS/nixpkgs#123759]
**Describe the bug**

The minio service set environment variables
- `MINIO_ACCESS_KEY`
- `MINIO_SECRET_KEY`

which are [both deprecated since RELEASE.2021-04-22T15-44-28Z](https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#envvar.MINIO_ACCESS_KEY). This is the release currently used hence the breakage.

Tested on [nixos-20.09.4125.7974217f94c](https://releases.nixos.org/?prefix=nixos/20.09/nixos-20.09.4125.7974217f94c/)

**To Reproduce**
```nix
  services.minio = {
    enable = true;
    listenAddress = ":9000";
    accessKey = "admin";
    secretKey = "123456789";
  };
```

**Expected behavior**
It should be possible to login with the provided key.

**Comment by 06kellyjac** [comment]
@antoinerg thanks for the report! In future please tag maintainers so they actually see the issue, no one watches all nixpkgs issues :sweat_smile: 

@bachp

**Comment by bachp** [comment]
@antoinerg While the variables are deprecated, they are [still supported](https://github.com/minio/minio/blob/master/cmd/common-main.go#L311) by minio. So I'm not sure this is really the cause of the breakage.

However I will update the module to make use of the new variables and maybe even rename (or alias) the current options to make it consistent.

**Comment by NULLx76** [comment]
Yeah minio (on unstable) seems to be working just fine for me, but updating the variables seems to be the proper thing to do.

**Comment by bachp** [comment]
@antoinerg @NULLx76  I implemented a the change in https://github.com/NixOS/nixpkgs/pull/123834
