### ISSUE TITLE
Phosh does not start g-s-d

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#123735]
Phosh does not have g-s-d available, resulting in the inability to change the screen brightness using the slider in the top bar. The following error is logged:

```
Failed to start org.gnome.SettingsDaemon.Power.service: Operation refused, unit org.gnome.SettingsDaemon.Power.service may be requested by dependency only (it is configured to refuse manual start/stop).
```

It appears that since we use systemd for gnome-session, it does not start g-s-d:

```
May 19 21:30:53 nixos gnome-session-binary[1184]: gnome-session-binary[1184]: DEBUG(+): app /org/gnome/SessionManager/App7 is disabled by X-GNOME-HiddenUnderSystemd
May 19 21:30:53 nixos gnome-session-binary[1184]: gnome-session-binary[1184]: DEBUG(+): GsmManager:	ID: /org/gnome/SessionManager/App7	app-id:org.gnome.SettingsDaemon.Power.desktop	is-disabled:1	is-conditionally-disabled:0
```

Maybe we need to start phosh using systemd too. There is a [service upstream](https://source.puri.sm/Librem5/phosh/-/blob/b2e68d269bb58f53e3b3bb690abe3b803a6c9535/data/phosh.service).

Though for GNOME Shell, g-s-d is started by `gnome-session@gnome.target` and I see no such `Wants` in the upstream `phosh.service`. Perhaps we would need to add `Wants` that mirror the `RequiredComponents` from `phosh.session`.

cc @zhaofengli @dotlambda @samueldr

**Comment by samueldr** [comment]
I've been using the systemd service, which in turn is inspired by that upstream service.

 - https://github.com/NixOS/mobile-nixos/pull/352/files#diff-d54a364f462ceeb609e5441a05525e70355cef100366f30c50b80a70e2dc4827R38-R61

I'm really not familiar with the systemd + user session stuff here, and I tried adding all the `Wants` from `systemctl --user cat graphical-session.target` to that session, but it doesn't start things.


```
systemd.services.phosh = {
  wantedBy = [ "graphical.target" ];
  serviceConfig = {
    ExecStart = "${pkgs.phosh}/bin/phosh";
    User = 1000;
    PAMName = "login";
    WorkingDirectory = "~";

    # XXX
    TTYPath = "/dev/tty7";
    TTYReset = "yes";
    TTYVHangup = "yes";
    TTYVTDisallocate = "yes";

    StandardInput = "tty-fail";
    StandardOutput = "journal";
    StandardError = "journal";

    # XXX
    UtmpIdentifier = "tty7";
    UtmpMode = "user";

    Restart = "always";
  };
  wants = [
    # Workaround for: https://github.com/NixOS/nixpkgs/issues/123735
    # Must be in sync with gnome.session
    # systemctl --user cat gnome-session@gnome.target
    "org.gnome.SettingsDaemon.A11ySettings.target"
    "org.gnome.SettingsDaemon.Color.target"
    "org.gnome.SettingsDaemon.Datetime.target"
    "org.gnome.SettingsDaemon.Housekeeping.target"
    "org.gnome.SettingsDaemon.Keyboard.target"
    "org.gnome.SettingsDaemon.MediaKeys.target"
    "org.gnome.SettingsDaemon.Power.target"
    "org.gnome.SettingsDaemon.PrintNotifications.target"
    "org.gnome.SettingsDaemon.Rfkill.target"
    "org.gnome.SettingsDaemon.ScreensaverProxy.target"
    "org.gnome.SettingsDaemon.Sharing.target"
    "org.gnome.SettingsDaemon.Smartcard.target"
    "org.gnome.SettingsDaemon.Sound.target"
    "org.gnome.SettingsDaemon.UsbProtection.target"
    "org.gnome.SettingsDaemon.Wacom.target"
    "org.gnome.SettingsDaemon.XSettings.target"
  ];
};
```

I assume this is a split from between user and non-user services. As `phosh` is a system service this way.

Is the solution to have this be a user service? Though that wouldn't help with a gdm-started session, right?

**Comment by jtojnar** [comment]
Yeah, it would have to be a user service.

And unless gnome-session is informed that phosh supports systemd, it will continue using the session file. So if you want the service to be used, you will have to start it manually using `systemctl start --user phosh`.

I am not sure what exactly it would take, here is a [blog post describing the transition](https://blogs.gnome.org/benzea/2019/10/01/gnome-3-34-is-now-managed-using-systemd/) and a [MR](https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/13). I also asked at the [Phosh channel](https://matrix.to/#/#phosh:talk.puri.sm).

**Comment by jtojnar** [comment]
Looking at https://gitlab.gnome.org/GNOME/gnome-flashback/-/merge_requests/17/diffs, we would probably “just” need:

- Add `X-GNOME-HiddenUnderSystemd` to `sm.puri.Phosh.desktop`
- Install `phosh.service` (and patch the paths there)
- Create `phosh.target` and ~~`gnome-session@phosh.target`~~ [`gnome-session@phosh.target.d/session.conf` drop-in](https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/489c7c8b2c632c1bb34059ac0814f47fa81b4b75)
- Use `--systemd` instead of `--builtin` gnome-session flag

**Comment by zhaofengli** [comment]
Ok, I gave it a try and systemd session management seems to be working. There are two patches to be upstreamed (waiting for Purism to approve my account creation), and I'm not entirely sure what is the correct way to start phoc (currently it sits outside the session). My branch is [here](https://github.com/zhaofengli/nixpkgs/commits/phosh-systemd), and it can be tested with the following configurations:

```nix
{
  systemd.services.phosh-autostart = {
    wantedBy = [ "graphical.target" ];
    serviceConfig = {
      ExecStart = "${pkgs.phosh}/bin/phosh";
      User = 1000;
      PAMName = "login";
      WorkingDirectory = "~";

      TTYPath = "/dev/tty7";
      TTYReset = "yes";
      TTYVHangup = "yes";
      TTYVTDisallocate = "yes";

      StandardInput = "tty-fail";
      StandardOutput = "journal";
      StandardError = "journal";

      UtmpIdentifier = "tty7";
      UtmpMode = "user";

      Restart = "always";
    };

    environment = {
      ENABLE_SYSTEMD_SESSION = "1";
    };
  };
}
```

**Comment by samueldr** [comment]
I believe those systemd user services should, somehow, be part of the NixOS phosh configuration.

I don't know how this could be handled, but ideally enabling posh should, by default, enable this. Or if not by default enabled, a second option like `phosh.enableUserService = true`.

@jtojnar anything against doing this way? Not sure if this can cause trouble.

**Comment by jtojnar** [comment]
Phosh is already in `systemd.packages` so I would expect it to work.
