### ISSUE TITLE
allow excluding packages from desktopManager.plasma5

### ISSUE THREAD

**Issue by shalva97** [NixOS/nixpkgs#123822]
## Issue description
enabling  `services.xserver.desktopManager.plasma5.enable` installs few packages related to KDE desktop. I can not find a way to exclude some of them from this [list](https://github.com/NixOS/nixpkgs/blob/21ff9308b75d448765f7c3704a1459a3d8e1c844/nixos/modules/services/x11/desktop-managers/plasma5.nix#L214)
I dont want Konsole because already have Alacritty, I dont want Spectacle because Flameshot and so on....

Also asked similar question [here](https://discourse.nixos.org/t/how-to-exclude-packages/13039)... 
few days ago I managed to make a workaround by creating another plasma5 and called it [myplasma5](https://github.com/shalva97/nix-config/blob/master/configs/plasma.nix) with few other packages commented out, and it worked. But im afraid it might break in future because there is lot of other logic for installing, which will not be updated automatically.

### Steps to reproduce
services.xserver/desktopManager.plasma5.enable = true;

**Comment by zmej420** [comment]
As of today
services.xserver.desktopManager.plasma5.excludePackages  
or
environment.plasma5.excludePackages if you are on 23.11 unstable

This should be closed. There was no response but the feature is now in NixOS since https://github.com/NixOS/nixpkgs/commit/6350d8d9b366fd6553dfe2160c4b43c28af97ac4

**Comment by shalva97** [comment]
I guess I can. One thing to note is that I don't have NixOS installation to see if it really works
