### ISSUE TITLE
openmw aborts when running wizard or launcher binaries

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#123875]
**Describe the bug**
It seems the package openmw (morrowind game engine) is missing dependencies, maybe Qt related.

```
openmw-wizard 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**To Reproduce**

Install openmw and run `openmw-wizard` or `openmw-launcher`, you don't need Morrowind asset files to run them.

**Expected behavior**

A window is opened.

**Notify maintainers**

- @abbradar 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05pre289339.83d907fd760 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05pre289339.83d907fd760"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tambysatya** [comment]
I've had the same problem, but it seems that installing **qt5.full** fix this problem.
Sorry for my english, I hope this helps anyway.
