### ISSUE TITLE
GNOME's Archive Manager (file-roller) can't handle zip files by default [missing p7zip dep]

### ISSUE THREAD

**Issue by necessarily-equal** [NixOS/nixpkgs#123956]
**Describe the bug**
When opening a zip file, file-roller can't show the content, and can't extract it

**To Reproduce**
Install GNOME

**Expected behavior**
File-roller can open the most common archive format without people having to go fishing in nixpkgs

**Additional context**
Possible solution: add p7zip in depends

**Notify maintainers**
@hedning
@jtojnar

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.109, NixOS, 20.09.3774.a6847cb5460 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3774.a6847cb5460, nixpkgs-git"`
 - channels(afontain): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

The problem seems to exist on master too.

**Maintainer information:**
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: [ file-roller ]
```

**Comment by jtojnar** [comment]
This is an upstream bug. We have applied a work around in https://github.com/NixOS/nixpkgs/commit/b209b81d7aeea27db4ee94a7588f4a153e74c949.

**Comment by necessarily-equal** [comment]
Hmm, if we have a workaround for the next stable, and there is a manual workaround on current stable, I guess we can close this? Or do we want to backport the workaround? I don't know how long-lived NixOS releases are.

**Comment by jtojnar** [comment]
Usually EOL a month after the release of next one. If someone wants to backport this, feel free but personally, I would not bother.
