### ISSUE TITLE
atd batch command broken

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#12392]
In my configuration.nix I have enabled atd:
`services.atd.enable = true;`
The rebuild works without any errors, "at" works, but using "batch" as a normal user fails. Here is an example:

```
$ at 21:48 
warning: commands will be executed using /bin/sh
at> touch test.123
at> <EOT>
job 2 at Thu Jan 14 21:48:00 2016
$ date
Do 14. Jan 21:47:46 CET 2016
$ ls -l test.123
-rw-r--r-- 1 abcdef users 0 14. Jan 21:48 test.123
$ rm test.123 
$ batch
warning: commands will be executed using /bin/sh
Cannot open lockfile /var/spool/atjobs/.SEQ: Permission denied
$ ls -l /var/spool/
insgesamt 0
drwxrwx--T 1 atd atd 8 14. Jan 21:48 atjobs
drwxrwx--T 1 atd atd 0 14. Jan 21:48 atspool
$ ls -l $(which at)
-r-s--s--x 1 atd atd 12576 14. Jan 21:46 /var/setuid-wrappers/at
$ ls -l $(which batch)
-r-s--s--x 1 atd atd 12576 14. Jan 21:46 /var/setuid-wrappers/batch
$ ls -l /etc/at/
insgesamt 4
-rw-r----- 1 root atd  0 14. Jan 21:42 at.deny
$ nixos-version 
15.09.911.53286a8 (Dingo)
```

**Comment by yesbox** [comment]
Still an issue on NixOS 17.09. As a workaround the "at -b" command can be used instead.
```
$ batch
You do not have permission to use at.
```

"batch" is a shell script that runs "at". But it doesn't run the setuid-wrapped at /run/wrappers/bin/at, it runs the plain "at" binary owned by root with no setuid bit.
```
$ cat /run/current-system/sw/bin/batch
#!/nix/store/qp5fw57d38bd1n07ss4zxh88zg67c3vg-bash-4.4-p12/bin/sh -e
if [ "$#" -gt 0 ]; then
        echo batch accepts no parameters
        exit 1
fi
prefix=/nix/store/ri8bxf6n7h8ycx5mcsjn8p99qfy7s4vw-at-3.1.20
exec_prefix=${prefix}
exec ${exec_prefix}/bin/at -qb now
```

I think that's the key problem but I'm not sure why that breaks it. On Linux the setuid bit is ignored on interpreted programs, but the "batch" script isn't the program with the setuid bit, that's the NixOS setuid-wrapper. Perhaps it has to do with the usage of "exec"? I'm not sure.

**Comment by bjornfor** [comment]
Yep, you're right. Removing "exec " fixes it.

Another way to fix it is to tell batch to run /run/wrappers/bin/at if that path exists and is executable, which I tried first. I like the "s/exec //" patch better, if only I could find some documentation explaining the behaviour.

**Comment by bjornfor** [comment]
From https://stackoverflow.com/questions/20684607/setuid-on-an-executable-doesnt-seem-to-work:

    Avoid system and exec as they drop privileges for security reason.

I skimmed through the references but couldn't find evidence.

**Comment by bjornfor** [comment]
Uhm, I think I messed up a bit when testing. Now I don't think removing "exec " fixed anything. I think the effective UID is dropped when kernel sees that "batch" (the final one) starts with a shebang. Anyway, we can fix that by ensuring that we invoke the setuid at variant. I'll prepare a patch.

**Comment by yesbox** [comment]
I forgot to add this same problem should apply to "atrun" as well, but I doubt anyone uses that. It doesn't make much sense to use with the NixOS module since it runs the atd service, and without the NixOS module the setuid wrapper isn't installed in the first place.
