### ISSUE TITLE
unable to upgrade declarative nixos container.

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#12396]
I have a container defined in my nixos configuration.conf

```
  containers.test = {
    autoStart = true;
    privateNetwork = true;
    hostAddress = "10.137.137.1";
    localAddress = "10.137.137.3";
    config = { configs, pkgs, ... }: {
      system.stateVersion = "unstable";
      system.defaultChannel = "https://nixos.org/channels/unstable";
      boot.isContainer = true;
      networking.hostName = "test";
      networking.useDHCP = false;
      environment.systemPackages = with pkgs; [ bash hello ];
    };
  };
```

I have tried to make the container upgrade from 15.09 to unstable but it does not seem to work.  I also tried adding the channel and upgrading from within the container but this also fails because there is not a configuration.nix in the container.

What is the proper way to do this.  My goal is to run unstable containers inside of my stable nixos installation

**Comment by lethalman** [comment]
Containers are updated with `systemctl reload`, did do this? Also please paste any error "does not seem to work" is not helpful.

**Comment by mogorman** [comment]
sorry if i wasn't clear enough.   my root NixOS environment is 15.09.  I made a container declaratively to run gitlab.  It works great.  I want to take said container and make it follow the unstable branch instead of the stable branch.  My goal is to be able to run nixos-rebuild switch --upgrade and have it upgrade.  I also tried to run the nixos-rebuild switch from with in my container this does not work as there is not a /etc/nix/configuration.nix inside  of the container because i created it declaratively.

**Comment by danbst** [comment]
This should be possible after https://github.com/NixOS/nixpkgs/pull/15967
Also, because of https://github.com/NixOS/nixpkgs/pull/16959 you can `nix-env -iA nixpkgs.nixos-container` and recreate the container.

I guess `system.defaultChannel = "https://nixos.org/channels/unstable";` doesn't work in containers. Also, see https://github.com/NixOS/nixpkgs/pull/3021

**Comment by rue-mogorman** [comment]
That is awesome.  I will try to get that running as soon as i can.  thank you for update

**Comment by mogorman** [comment]
That is awesome. I will try to get that running as soon as i can. thank you for update.

**Comment by mogorman** [comment]
this did fix my issue. sorry didnt close earlier
