### ISSUE TITLE
callHackageDirect  of package leads to infinite recursion

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#123913]
**Describe the bug**

Hi, i just wanted to build the latest Haskell `quickspec` package and at the same time learn how to use `callHackageDirect`.
I ran into an infinite recursion and can't tell if i did something stupid or if this is a genuine bug in nxipkgs's haskell subsystem.

**To Reproduce**

nix-build the following expression:

```nix
let
  # latest master commit from 2021-05-21
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/26b8f68c2de476644b09727746adede89cefe995.tar.gz") {};

  haskell = pkgs.haskellPackages.extend (final: prev: {
    twee-lib = prev.callHackageDirect {
      pkg = "twee-lib";
      ver = "2.3.1";
      sha256 = "1w0f0cvgb9g8pjpm9g9cfa8iy3dri9dsfblp094lvjf44w40h51k";
    } {};
    primitive = prev.callHackageDirect {
      pkg = "primitive";
      ver = "0.7.1.0";
      sha256 = "1mmhfp95wqg6i5gzap4b4g87zgbj46nnpir56hqah97igsbvis7j";
    } {};
    quickspec = prev.callHackageDirect {
      pkg = "quickspec";
      ver = "2.1.5";
      sha256 = "085iqcpy8wwnml26nf459w3cm0vvsm38wq86wxmdkh5ws3l86sys";
    } {};
  });

in
  haskell.quickspec
```

```bash
$ nix-build quickspec.nix --show-trace
error: while evaluating the attribute 'propagatedBuildInputs' of the derivation 'quickspec-2.1.5' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'buildInputs' of the derivation 'constraints-0.13' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'hspec-2.7.10' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'hspec-core-2.7.10' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'tf-random-0.5' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'buildInputs' of the derivation 'primitive-0.7.1.0' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'buildInputs' of the derivation 'base-orphans-0.8.4' at /nix/store/z5add0hm83w2ilka7q9jjjijidzg7zfg-source/pkgs/stdenv/generic/make-derivation.nix:201:11:
infinite recursion encountered, at undefined position
```

**Expected behavior**

I would expect that the expression evaluation finishes and the package build begins.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.20, NixOS, 20.09.4159.a7064e23973 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.09.4159.a7064e23973, home-manager-20.09, nixos-unstable-21.05pre289339.83d907fd760"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by tfc** [comment]
cc @mightybyte @dhess @chreekat @ElvishJerricco any ideas?

**Comment by dhess** [comment]
Looks like this is a known issue:

https://github.com/NixOS/nixpkgs/blob/b76684aff76b2174cfb31aabacf1763b7835cdd7/pkgs/development/haskell-modules/configuration-nix.nix#L614

This expression works (note that `quickspec-2.1.5` pins `twee-lib` at `2.2`, so I fixed that as well):

```
let
  # latest master commit from 2021-05-21
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/26b8f68c2de476644b09727746adede89cefe995.tar.gz") { };

  haskell = pkgs.haskellPackages.extend (final: prev: {
    twee-lib = final.callHackageDirect
      {
        pkg = "twee-lib";
        ver = "2.2";
        sha256 = "sha256-fZ6afRMZVDElHDRegVy7eG6LSpunoXtjgqKDGPQXHlg=";
      }
      { };
    quickspec = final.callHackageDirect
      {
        pkg = "quickspec";
        ver = "2.1.5";
        sha256 = "085iqcpy8wwnml26nf459w3cm0vvsm38wq86wxmdkh5ws3l86sys";
      }
      { };
  });

in
haskell.quickspec
```

**Comment by sternenseemann** [comment]
Such issues are unavoidable: Package authors introduce circular dependencies via tests, but because we run the tests inside the main derivation we have to deal with circular dependencies cabal or stack just can ignore (because they never run tests on the dependencies they install).

Theoretically we could make tests a separate derivation from the main package, but would be a long term goal to work towards and may very well have other downsides.

If you have any suggestions on circular dependencies in the haskell infrastructure and improving the UX for it, please open another issue!

**Comment by tfc** [comment]
> Theoretically we could make tests a separate derivation from the main package, but would be a long term goal to work towards and may very well have other downsides.

One question on that: If someone builds `pkgs.haskellPackages.x` this should by default happen with tests (and hydra building all those packages then tests them implicitly), but if some package references another, this could happen per default without tests. That would fix such problems. Is that a feasible idea?

**Comment by sternenseemann** [comment]
I don't think so because a derivation doesn't know if it is requested as a leaf package or as a dependency of something else — of course we could emulate that, but it would cause many unnecessary builds and also prevent many tests we can run from being executed.

I was thinking about using something like `drvSeqL` (as shown in [this talk](https://www.youtube.com/watch?v=5Z7IckV6gao)) to separate tests and the package into two derivations, but this would have other drawbacks and require some pretty significant changes to `cabal2nix`/`hackage2nix`.
