### ISSUE TITLE
Some CODEOWNDERS entries are broken

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#124085]
See https://github.com/NixOS/nixpkgs/pull/124005#issuecomment-846477202 and 
#124005 in general.

This affects @NixOS/podman, @NixOS/php and @NixOS/darwin-maintainers. Have you ever been notified as code owners?

**Comment by talyz** [comment]
Not that I can recall, no.

**Comment by piegamesde** [comment]
In that case, we need to remove these organizations from CODEOWNERS, replace them with people's names that actually work, and somehow make sure the next person won't repeat the mistake  again.

Alternatively, we could roll our own system by teaching OfBorg to ping the respective persons.
