### ISSUE TITLE
[OpenTTD] Missing assets

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#12400]
```
[sven@nixos:~]$ nixos-version
15.09.911.53286a8 (Dingo)
```

After installing the OpenTTD package, I found that no assets appeared to be included with - OpenGFX, OpenSFX and OpenMSX are all missing. While it asks to download OpenGFX upon startup, the rest doesn't get downloaded automatically, which hampers user experience.

Wouldn't it be a good idea to package along these assets by default, given that they're the de facto standard asset packages for OpenTTD nowadays? I believe other distributions do the same.

**Comment by jgillich** [comment]
I remember not having any assets on some other distro (Fedora?), but I agree, there really should be one of the asset sets preinstalled.

**Comment by joepie91** [comment]
Well, Fedora is not exactly the gold standard of "packaging everything" to begin with ;) But yes, I'd imagine that some distributions might have "only package the application" rules. Even then, though, I'd imagine there'd be a `-data` package in those distributions.

**Comment by fpletz** [comment]
Fixed in master. Also added parameters to explicitly disable assets.

**Comment by jgillich** [comment]
:+1:

**Comment by joepie91** [comment]
That was fast! Excellent :)
