### ISSUE TITLE
Package Request: Runescape (3)

### ISSUE THREAD

**Issue by Ashe** [NixOS/nixpkgs#124069]
**Project description**
Looking for a Runescape 3 package - there was a request but it was closed with no reason why: #30582.

I really don't believe that not a single NixOS user plays RuneScape (or OSRS for that matter, as right now the Runelite package doesn't support the GPU plugin which a lot of users deem to be essential, but that's a separate issue that I also made noted here: #123827). I feel like NixOS is getting a wave of new people and making sure people have access to the things they enjoy will make it easier for people to have fun with this wonderful operating system!

**Metadata**

* homepage URL: https://www.runescape.com/download
* license: mit, bsd, gpl2+ , ...
* platforms: It's already on Windows, Mac, Linux, Steam, iOS and Android so I don't see a reason how it can't work on NixOS?

**Comment by kira-bruneau** [comment]
I don't play RuneScape, but I have it packaged in my [NUR repo](https://github.com/nix-community/nur-combined/blob/master/repos/metadark/pkgs/games/runescape-launcher/default.nix). The problem is that I have to frequently update the hash since it's constantly changing in the debian repo.

**Comment by Ashe** [comment]
>  The problem is that I have to frequently update the hash since it's constantly changing in the debian repo.

Ah that is an issue then. So if the game updates, does what you have downloaded no longer work? Or is it more that people (like myself) won't be able to get an initial download until the hash is up todate, and then when it's working it'll self update?

Thank you for your your reply, I don't quite know how to move forward. I don't claim to be a nix expert, just a user. I just hope that  people don't have to sacrifice small things like runescape when they switch OS :) 

Do you have any ideas on how this might get fixed? Is it just a case of trying to download it and then letting it self-update once I get lucky?

**Comment by kira-bruneau** [comment]
> Ah that is an issue then. So if the game updates, does what you have downloaded no longer work? Or is it more that people (like myself) won't be able to get an initial download until the hash is up todate, and then when it's working it'll self update?

It's more that the initial download of the launcher will fail. The game will continue to self-update using the launcher you have installed. Although, if you want to keep the launcher's dependencies up-to-date you will need to rebuild the launcher, which would also fail after running `nix-collect-garbage`.

> Thank you for your your reply, I don't quite know how to move forward. I don't claim to be a nix expert, just a user. I just hope that people don't have to sacrifice small things like runescape when they switch OS :)
> 
> Do you have any ideas on how this might get fixed? Is it just a case of trying to download it and then letting it self-update once I get lucky?

Maybe we could add the source file to `propagatedUserEnvPkgs`, so it doesn't get garbage collected? I don't think there's any good solution for the initial download though since RuneScape doesn't provide a stable download.

**Comment by Ashe** [comment]
I understand, I guess I should close this issue since unless there's a long-term fix then your NUR repo is the best thing we can do. Closing the issue, with hopes that people wanting to play RS3 use [your repo](https://github.com/nix-community/nur-combined/blob/master/repos/metadark/pkgs/games/runescape-launcher/default.nix). I did this with with:
```bash
nix-shell -p nur.repos.metadark.runescape-launcher
```

Thanks again @kira-bruneau !

**Comment by kira-bruneau** [comment]
No problem :slightly_smiling_face:. I'll try to see if I can put together an updateScript that can be used by [nixpkgs-update](https://github.com/ryantm/nixpkgs-update), but for now the NUR repo is probably the best option.

One thing to note though is that I currently have a PR open to rename my repo from `metadark` -> `kira-bruneau`: https://github.com/nix-community/NUR/pull/361

**Comment by Ashe** [comment]
> One thing to note though is that I currently have a PR open to rename my repo from `metadark` -> `kira-bruneau`: [nix-community/NUR#361](https://github.com/nix-community/NUR/pull/361)

Thanks for letting everyone know. FYI, I just installed RS3 thanks to you, so I hope you can sleep happy knowing that you helped someone :)

**Comment by joepie91** [comment]
> The problem is that I have to frequently update the hash since it's constantly changing in the debian repo. I'm not sure if we want to include this in nixpkgs because it will almost always be broken due to the constant hash changes.

Hmm. Is this still a problem? [This commit](https://github.com/flathub/com.jagex.RuneScape/commit/0fcdf4f65c5921f96c01a525c19b58610f56810c) on flathub suggests that the URL changes with each release, so presumably that means that the old URL should retain the same hash?

Or does the old URL become inaccessible entirely when a new version is released?

**Comment by kira-bruneau** [comment]
I haven't run into the issue in a while, so maybe they're now actually using new versions for new updates? I actually just removed my nur implementation about a week ago after noticing that it's available in nixpkgs.
