### ISSUE TITLE
FreeCAD build fails

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#12401]
And this is the cause:

`fatal error: Eigen/LeastSquares: No such file or directory
 # include <Eigen/LeastSquares>`

see https://hydra.nixos.org/job/nixpkgs/trunk/freecad.x86_64-linux

@viric do you have an idea how to fix that?

**Comment by flosse** [comment]
Here a alpha version was introduced: https://github.com/NixOS/nixpkgs/commit/c8b97538

**Comment by vcunat** [comment]
@7c6f434c alpha version as the default `eigen`?

**Comment by 7c6f434c** [comment]
>@7c6f434c alpha version as the default `eigen`?

Oops, sorry. Will roll back after lunch if you don't roll it back 
earlier.

Was doing a mass update, tested another reverse dependency of eigen and
didn't pay attention to its alpha status

**Comment by vcunat** [comment]
BTW, I see a tag for eigen-3.2.7 but I'm leaving it to some users of it to test/update.
