### ISSUE TITLE
Python: Remove `python setup.py test` where used

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#124050]
This setuptools commands has been officially deprecated. Currently it shows a deprecation warning, but will likely result in errors later.

Breaking up #115272 into individual issues.

cc @FRidh

**Comment by wamserma** [comment]
Those are files that mention `setup.py test` and likely need attention:
```
doc/languages-frameworks/python.section.md
pkgs/applications/graphics/mypaint/default.nix
pkgs/applications/networking/instant-messengers/gajim/default.nix
pkgs/development/python-modules/quantities/default.nix
pkgs/development/python-modules/serpent/default.nix
pkgs/development/python-modules/salmon-mail/default.nix
pkgs/development/python-modules/selectors34/default.nix
pkgs/development/python-modules/openwebifpy/default.nix
pkgs/development/python-modules/coveralls/default.nix
pkgs/development/python-modules/sqlalchemy-migrate/default.nix
pkgs/development/python-modules/django-anymail/default.nix
pkgs/development/python-modules/packet-python/default.nix
pkgs/development/python-modules/fipy/default.nix
pkgs/development/python-modules/pystray/default.nix
pkgs/development/python-modules/preshed/default.nix
pkgs/applications/misc/pytrainer/default.nix
pkgs/tools/backup/duplicity/default.nix
pkgs/tools/misc/ntfy/default.nix
```

**Comment by jonringer** [comment]
The main issue is that by default, the hook gets ran. It just fails silently for most builds.

**Comment by wamserma** [comment]
Yeah, but a few packages have already migrated their test and just need a version bump (e.g. mahotas), are planning to migrate (fido2, which already has a workaround in nixpkgs) or can even be removed (selectors34).
Running it implicitly is also a problem that needs to be adressed, of course.

**Comment by FRidh** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/71897.

**Comment by wamserma** [comment]
> Duplicate of #71897.

I'd rather say complement. #71897 is for the default checkPhase, and we can use this issue to track individual packages that need extra work.

**Comment by dotlambda** [comment]
> Those are files that mention `setup.py test` and likely need attention:

A better way to search for files that need work is `rg --files-without-match "checkPhase|pytestCheckHook|doCheck" --iglob "pkgs/development/python-modules/**/*.nix"`.

**Comment by wamserma** [comment]
> > Those are files that mention `setup.py test` and likely need attention:
> 
> A better way to search for files that need work is `rg --files-without-match "checkPhase|pytestCheckHook|doCheck" --iglob "pkgs/development/python-modules/**/*.nix"`.

These are packages that _might_ fail once the default is changed, but have no indication that they are actually relying on `setup.py test`.

**Comment by jonringer** [comment]
Still some left:
```
[14:27:49] jon@jon-desktop /home/jon/projects/nixpkgs (numba-autoadd)
$ rg "setup.py test" -l
doc/languages-frameworks/python.section.md
pkgs/applications/misc/pytrainer/default.nix
pkgs/tools/misc/ntfy/default.nix
pkgs/applications/graphics/mypaint/default.nix
pkgs/development/python-modules/salmon-mail/default.nix
pkgs/development/python-modules/f90nml/default.nix
pkgs/development/python-modules/fipy/default.nix
pkgs/development/python-modules/pystray/default.nix
pkgs/development/python-modules/coveralls/default.nix
pkgs/development/python-modules/sqlalchemy-migrate/default.nix
pkgs/development/python-modules/apsw/default.nix
pkgs/development/python-modules/cron-descriptor/default.nix
pkgs/development/python-modules/serpent/default.nix
pkgs/development/python-modules/python-nvd3/default.nix
```

**Comment by devurandom** [comment]
Is https://github.com/NixOS/nixpkgs/issues/331159 a newer version / duplicate of this?
