### ISSUE TITLE
make `-l` overridable

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#124166]
**Describe the bug**

The default usage of `-l` set to `cores` makes building on my system slow, as it usually has a load of 2 or 3, so `make` will not start more than one or two builds, despite the fact that there are more than 2 cores idle, as the load probably is due to IO wait.

Therefore it would be nice to be able to deactivate `-l` without individually overriding individual derivations or disabling its usage completely in builds.

**Comment by veprbl** [comment]
Have you seen https://nixos.org/manual/nix/stable/#chap-tuning-cores-and-jobs ?

**Comment by NobbZ** [comment]
I'm aware of `max-jobs`, though that doesn't really help. In general all nix related builds are basically serialized due to the usage of `-l`. Just throwing a bigger `max-jobs` won't help with that, as regardless of number of jobs that nix tries to run in parallel, `make` will now do more, just because the system load is above the threshold that is dictated by `cores`.

**Comment by avnik** [comment]
Upvote.  It will be valuable for systems with lot of cores (20+) but slow spinning disks.

**Comment by veprbl** [comment]
See also #143820

**Comment by Artturin** [comment]
-l's were removed in https://github.com/NixOS/nixpkgs/pull/192447
