### ISSUE TITLE
Add package gxkb

### ISSUE THREAD

**Issue by TheBlackBeans** [NixOS/nixpkgs#124156]
**Project description**
A keyboard layout indicator for X11.

**Metadata**

* source URL: [zen-tools/gxkb](https://github.com/zen-tools/gxkb)
* license: gpl2
* platforms: Linux

**Comment by SCOTT-HAMILTON** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/gxkb/default.nix
