### ISSUE TITLE
Package the Keyboard Layout Editor software

### ISSUE THREAD

**Issue by jthulhu** [NixOS/nixpkgs#124134]
**Project description**

From the package README:

> Keyboard layout editor is a JavaFX application made to help create custom keyboard layouts. The application works with the X Keyboard Extension (XKB).

**Metadata**

* source URL: [vgresak/keyboard-layout-editor](https://github.com/vgresak/keyboard-layout-editor)
* license: MIT
* platform: Linux
* build requirements: `jdk`, `openfjx` (already packaged)

**Comment by FliegendeWurst** [comment]
PR: #353165
