### ISSUE TITLE
kde5 : module org.kde.bluezqt is not installed

### ISSUE THREAD

**Issue by heydojo** [NixOS/nixpkgs#12415]
I have :
```
hardware.bluetooth.enable = true;
```
and a default kde 5 installation from nixos unstable master.

When I click on the bluetooth icon in the task bar a message containing the following appears :
```
Error loading QML file: file:///nix/store/9mh7a19632zxg3g8xl2mq6iaq99qlfbf-bluedevil-5.5.3/share/plasma/plasmoids/org.kde.plasma.bluetooth/contents/ui/BluetoothApplet.qml:25:1: module "org.kde.bluezqt" is not installed
```
So I cannot use the bluetooth applet in kde 5.

**Comment by heydojo** [comment]
Also relate to this issue: the send to bluetooth context menu item does not appear when I right click on a file within dolphin file manager.

**Comment by ttuegel** [comment]
Looks like `bluedevil` isn't propagating its `bluezqt` dependency.

**Comment by heydojo** [comment]
@ttuegel thanks! I got it working!
https://github.com/NixOS/nixpkgs/pull/12683
