### ISSUE TITLE
openblas: broken AVX512 kernels

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#124250]
**Describe the bug**
In https://github.com/NixOS/nixpkgs/pull/97306 the AVX512 support was turned back on in openblas, allowing for the use of dynamic, AVX512 optimized compute kernels. @sheepforce started to discover problems with AVX512 while working on the [NixOS-QChem overlay](https://github.com/markuskowa/NixOS-QChem) and I can confirm that this problem affects multiple packages that are built against openblas.
The problem already manifest itself in that packages fail their unit tests, when build on an AVX512 enabled machine (see https://github.com/markuskowa/NixOS-QChem/issues/52 for a detailed list). The tests either fail due to a wrong result or time out. 
I could indentify 5 different packages which are affected by this bug, leading to the conclusions this very likely affects many more packages.

Affected versions of openblas, which I have tested, are 0.3.13 (master/release-21.05) and 0.3.15 (in staging at the moment).
The problem disappears when:
1. openblas is complied with `NO_AVX512=1` in `makeFlags`
2. `OPENBLAS_CORETYPE=HASWELL` is injected into the test phase or just set at runtime. Note that any core type that does not use AVX512 works fine here (tested: `HASWELL`, `ZEN` or `ATHLON`, but `SKYLAKEX`, which uses AVX512 fails).
3. `DYNAMIC_ARCH` is turned off at openblas build time and `target` is set to a non-AVX512 target (see point 2).

@danieldk you seem to be making use AVX512 optimizations. Did you notice any problems?

I suggest to revert https://github.com/NixOS/nixpkgs/pull/97306 and thus re-introduce the `NO_AVX512` makeFlag in openblas.

**To Reproduce**
1. Run an affected program which is linked against openblas on an Intel CPU that  supports AVX512 instructions (e.g. Xeon Scalable) and check the results. In nixpkgs it is at least `openmolcas` that is affected (delivers wrong results).
2. Build, for example, `octave` on an Intel CPU with AVX512: the self tests/unit tests never finish in this case.
3. Various external packages fail to run their tests on and AVX512 enabled machine: https://github.com/markuskowa/NixOS-QChem/issues/52.

**Notify maintainers**
CC @ttuegel 

**Metadata**
This should affect `nixpkgs-unstable` since https://github.com/NixOS/nixpkgs/pull/97306 (~January 2021) and `nixos-21.05`. The tests I have carried out were run with`nixpgks-unstable` versions from the ~last week.

**Comment by danieldk** [comment]
Sorry to hear that :(. Then we should indeed revert that change again.

**Comment by dotlambda** [comment]
Can this be closed?

**Comment by markuskowa** [comment]
The PR has been merged into staging. Should we wait to close the issue until the fix reaches master?
