### ISSUE TITLE
Package request: BiglyBT, Vuze continuation

### ISSUE THREAD

**Issue by raspher** [NixOS/nixpkgs#124253]
**Project description**
A torrent downloader written in Java, with support for almost all things related to torrent (i2p, tor, dht, mainline dht, etc. _see homepage_)

Vuze development stopped 4 years ago, BiglyBT is continuation of Vuze.

**Metadata**
* homepage URL: https://www.biglybt.com/
* source URL: https://github.com/BiglySoftware/BiglyBT
* license: GPL-2.0
* platforms: it's java - Windows, Linux, MacOS (legacy too), BSD, Android ... _(it should probably work even on haiku)

**Comment by joaquinito2048** [comment]
#129916

**Comment by joaquinito2048** [comment]
This pull request is closed, because i are banned.

**Comment by raspher** [comment]
I've worked on it a little, got working package. There might be problems with autoupdate - shared plugins cannot self-update as they're builded into package. Auto-updating can be disabled in settings, which are saved per user in `~/.biglybt`
