### ISSUE TITLE
plex: Incorrect permissions on initial setup

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#12422]
On a computer which did not previously have Plex installed, after setting services.plex.enable = true, a /var/lib/plex/ subdirectory was created with owner root:root. This made Plex fail to start, necessitating a manual chown.

**Comment by pSub** [comment]
I just had a look into the service definition. Everything seems to be ok there.

        test -d "${cfg.dataDir}" || {
          echo "Creating initial Plex data directory in \"${cfg.dataDir}\"."
          mkdir -p "${cfg.dataDir}"
          chown -R ${cfg.user}:${cfg.group} "${cfg.dataDir}"
        }

I will try to reproduce your error later.

**Comment by pSub** [comment]
The referenced commit should fix your issue. If not, please reopen.
