### ISSUE TITLE
ffmpeg-2.x vulnerabilities

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#12437]
https://www.ffmpeg.org/index.html#pr2.8.5

**Comment by vcunat** [comment]
- [ ] It's likely that kodi/xbmc remains vulnerable.
- [ ] Audacity on 15.09 is older ,so the patch used on master doesn't apply and wouldn't be enough anyway.

**Comment by vcunat** [comment]
Well, the two minor issues above remain, so I'll leave this open ATM.

**Comment by zimbatm** [comment]
Closing as 15.09 has now been superseded and kodi is using ffmpeg 2.8.6 since ad4bfe4dda80815c2d02016623cc48df7a5ed8ca
