### ISSUE TITLE
Steam startup fails on missing `libpipewire-0.3.so.0` library

### ISSUE THREAD

**Issue by matthew-piziak** [NixOS/nixpkgs#124308]
I have `pkgs.steam` installed, and as of 24-05-2021 it fails with the following output:

```
Running Steam on nixos 20.09.4169.ac60476ed94 64-bit
STEAM_RUNTIME has been set by the user to: /steamrt
Error: You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0
Can't find 'steam-runtime-check-requirements', continuing anyway
…
[elided for brevity]
…
Failed to load steamui.so - dlerror(): libpipewire-0.3.so.0: cannot open shared object file: No such file or directory
[2021-05-24 17:47:57] Shutdown
```

**To Reproduce**

1. install `pkgs.steam` on stable channel 21.05
2. execute `steam`

**Notes and findings**

- I do not use pipewire. This bug seems to happen regardless.
- This bug seems fresh. See [a corresponding discussion](https://forum.manjaro.org/t/steam-beta-client-fails-to-start-since-today-32-bit-pipewire-support-missing/67780/2) on the Manjaro forums.
- As far as I can tell, `libpipewire-0.3.so.0` is not available in nixpkgs.
- This may be fixed in the new Steam runtime. 

**Notify maintainers**

@jagajaga. Thank you!

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.119, NixOS, 20.09.4169.ac60476ed94 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixpkgs-20.09.4169.ac60476ed94"`
 - channels(matt): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.steam
```

**Comment by Artturin** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/7807

**Comment by Oro** [comment]
FYI, this seems to only happen on the steam beta, workaround (for now) would be `rm ~/.steam/steam/package/beta` to switch back to steam stable.

**Comment by matthew-piziak** [comment]
@Oro The workaround of deleting `~/.steam/steam/package/beta` works! Having a flag file is great, since it allows you to switch to stable without launching the beleaguered application.

@Artturin Thank you! I use the same tool, but I must have an out of date index. I think it's time to add reindexing to a cron job.

**Comment by matthew-piziak** [comment]
After reindexing, I see the Nix reference:
```
pipewire.lib                                          0 s /nix/store/5aq52sjy6lvjymwjqcjplsx4c7fdcd35-pipewire-0.3.7-lib/lib/libpipewire-0.3.so.0
```

Users who want to use the beta could presumably use the following override, though I have not tested it on my machine:

```
nixpkgs.config.packageOverrides = pkgs: { steam = pkgs.steam.override { extraPkgs = pkgs: [ pipewire.lib ]; }; };
```

**Comment by ras-drive** [comment]
@Oro Deleting ~/.steam/steam/package/beta worked for me too, thanks for the help.

**Comment by berbiche** [comment]
When using the new `programs.steam` module, packages are automatically picked up from `hardware.opengl.extraPackages{,32}`:
``` nix
{
  hardware.opengl.extraPackages32 = with pkgs.pkgsi686Linux;
    [ libva ]
    ++ lib.optionals config.services.pipewire.enable [ pipewire ];
}
```

**Comment by adamlwgriffiths** [comment]
Looks like this beta release just made mainline. Vanilla Steam install is broken.

**Comment by dominikh** [comment]
```
diff --git i/pkgs/games/steam/runtime.nix w/pkgs/games/steam/runtime.nix
index b501df598ef..ab2c19249aa 100644
--- i/pkgs/games/steam/runtime.nix
+++ w/pkgs/games/steam/runtime.nix
@@ -8,11 +8,11 @@ stdenv.mkDerivation rec {
 
   pname = "steam-runtime";
   # from https://repo.steampowered.com/steamrt-images-scout/snapshots/
-  version = "0.20210317.0";
+  version = "0.20210527.0";
 
   src = fetchurl {
     url = "https://repo.steampowered.com/steamrt-images-scout/snapshots/${version}/steam-runtime.tar.xz";
-    sha256 = "061z2r33n2017prmhdxm82cly3qp3bma2q70pqs57adl65yvg7vw";
+    sha256 = "1880d1byn265w0vy5p98d8w8virnbywj707ydybj7rixhid2gzdc";
     name = "scout-runtime-${version}.tar.gz";
   };
 ```

fixes it

**Comment by davidak** [comment]
@dominikh so... could you create a pull request to fix it for everyone? that would be great :)

**Comment by Artturin** [comment]
i can make a pr for it

**Comment by jonringer** [comment]
related: https://github.com/NixOS/nixpkgs/pull/126142

**Comment by jonringer** [comment]
For people that are "stuck", and just want to play games

```
NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz  nix-shell -p steam --run steam
```

**Comment by jonringer** [comment]
Going to pin this until we have another unstable release

**Comment by jbalme** [comment]
Just updated on unstable after 2 weeks to find this and...

`NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz  nix-shell -p steam --run steam`

Steam just segfaults with this. Think that's my cue to go back to stable.

**Comment by Artturin** [comment]
> Just updated on unstable after 2 weeks to find this and...
> 
> `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz nix-shell -p steam --run steam`
> 
> Steam just segfaults with this. Think that's my cue to go back to stable.

works for me, can you give more info about your environment?
this will be backported to 20.09 and 21.05

**Comment by jbalme** [comment]
It still is segfaulting on my 2 week old configuration that worked yesterday, so idk if even going to stable is going to fix it. Guess I'll be without games for a bit.

`nix-shell -p nix-info --run "nix-info -m"` yields

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.11.20210524.ea7d4aa (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.05pre275232.29b0d4d0b60"`
 - channels(user): `"nixos-21.05pre277486.f5e8bdd07d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

CPU: Intel i7 4790k
GPU: AMD RX 5500 XT

Configuration is https://github.com/jbalme/nixos-config

**Comment by Artturin** [comment]
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.16-zen1, NixOS, 21.11pre294109.fbfb79400a0 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre294109.fbfb79400a0"`
 - channels(hm7): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
i have a vega64
updating completely may magically fix it 
have you tried rebooting?

**Comment by jbalme** [comment]
Updating completely (completely as in like 30m ago) resulted in broken vscode as well. Full reboots after each update. No dice.

**Comment by jbalme** [comment]
Logs:
[Running Steam on nixos 21.11.20210524.txt](https://github.com/NixOS/nixpkgs/files/6613271/Running.Steam.on.nixos.21.11.20210524.txt)
[assert_20210607225611_1.txt](https://github.com/NixOS/nixpkgs/files/6613273/assert_20210607225611_1.txt)
[assert_20210607225613_22.txt](https://github.com/NixOS/nixpkgs/files/6613274/assert_20210607225613_22.txt)

**Comment by jbalme** [comment]
Nevermind. Apparently something broke my steam profile. `mv ~/.local/share/Steam{,.bk}` fixed the issue. Time to copy all my games over...

**Comment by Artturin** [comment]
move the games its faster also steam automatically detects the games so you dont have to go through and install them all again so that it detects them

**Comment by jonringer** [comment]
Yea, I think valve just oof'ed on this one

**Comment by jonringer** [comment]
if anyone is still stuck with the `nix-shell` command that I had above, you might be able to use:
```
NIX_PATH=nixpkgs=https://github.com/jonringer/nixpkgs/archive/refs/heads/fix-steam-pipewire.tar.gz nix-shell -p steam --run steam
```
which will add pipewire, and make the steam check happy

**Comment by jbalme** [comment]
So it just corrupts the profile every time I close and re-open Steam. So much for it being fixed.

**Comment by jonringer** [comment]
did you try the one I just  posted?

**Comment by jbalme** [comment]
Yes :(

**Comment by jonringer** [comment]
Interesting, your channels are quite old, if you don't use flakes, it might be worth while to `sudo nix-channel --update && sudo nixos-rebuild switch`

**Comment by jbalme** [comment]
> Interesting, your channels are quite old, if you don't use flakes, it might be worth while to `sudo nix-channel --update && sudo nixos-rebuild switch`

I use flakes :)

**Comment by jonringer** [comment]
that's what I assumed when your installation said something significantly newer

**Comment by Artturin** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/781
same issue right?

**Comment by Artturin** [comment]
> Logs:
> [Running Steam on nixos 21.11.20210524.txt](https://github.com/NixOS/nixpkgs/files/6613271/Running.Steam.on.nixos.21.11.20210524.txt)
> [assert_20210607225611_1.txt](https://github.com/NixOS/nixpkgs/files/6613273/assert_20210607225611_1.txt)
> [assert_20210607225613_22.txt](https://github.com/NixOS/nixpkgs/files/6613274/assert_20210607225613_22.txt)

Same issue right? https://github.com/ValveSoftware/steam-for-linux/issues/7813

**Comment by jbalme** [comment]
> > Logs:
> > [Running Steam on nixos 21.11.20210524.txt](https://github.com/NixOS/nixpkgs/files/6613271/Running.Steam.on.nixos.21.11.20210524.txt)
> > [assert_20210607225611_1.txt](https://github.com/NixOS/nixpkgs/files/6613273/assert_20210607225611_1.txt)
> > [assert_20210607225613_22.txt](https://github.com/NixOS/nixpkgs/files/6613274/assert_20210607225613_22.txt)
> 
> Same issue right? [ValveSoftware/steam-for-linux#7813](https://github.com/ValveSoftware/steam-for-linux/issues/7813)

Looks like it.

**Comment by jbalme** [comment]
Unfortunately, the linked issue doesn't seem to actually have a fix that works, but I think it's still out of scope for this issue, so it can probably stay closed.

I'll just have to use the flatpak until Valve fixes whatever they broke.

**Comment by adamlwgriffiths** [comment]
Ditto previous comment.
Running 20.09
```
sudo nix-channel --update && sudo nixos-rebuild switch && sudo reboot
```
steam still not happy.

**Comment by Kreyren** [comment]
> For people that are "stuck", and just want to play games
> 
> ```
> NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz  nix-shell -p steam --run steam
> ```
> @joachifm 

That also doesn't work for me:

```console
[kreyren@leonid:~]$ NIXPKGS_ALLOW_UNFREE=1 NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz  nix-shell -p steam --run steam
...
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open i965: /run/opengl-driver-32/lib/dri/i965_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver-32/lib/dri
...
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  49
xerror_handler: X failed, continuing
assert_20210608094450_1.dmp[19545]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210608094450_1.dmp
/home/kreyren/.local/share/Steam/steam.sh: line 772: 19535 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"

[kreyren@leonid:~]$ assert_20210608094450_1.dmp[19545]: Finished uploading minidump (out-of-process): success = yes
assert_20210608094450_1.dmp[19545]: response: CrashID=bp-10205527-b031-4385-beb0-73ea32210608
assert_20210608094450_1.dmp[19545]: file ''/tmp/dumps/assert_20210608094450_1.dmp'', upload yes: ''CrashID=bp-10205527-b031-4385-beb0-73ea32210608''
```

Full log: https://gist.github.com/Kreyren/b201831f6dda59c0646254fa2515223f

**Comment by davidak** [comment]
It's not that the issue is not fixed, but the system API (seem to be X11 here or libc) is not compatible.

Try this for 20.09:

`NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/refs/heads/release-20.09.tar.gz nix-shell -p steam --run steam`

**Comment by jonringer** [comment]
I still think we should move forward with #126142 as it's current needed for the beta runtime, and will eventually be needed when the runtime gets bumped

**Comment by adamlwgriffiths** [comment]
`NIXPKGS_ALLOW_UNFREE=1 NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/refs/heads/release-20.09.tar.gz nix-shell -p steam --run steam` works for me.
But I've done 2 channel updates and nixos rebuilds and my vanilla steam install is still broken.

```
# nix-channel --list
nixos https://nixos.org/channels/nixos-20.09
```

https://releases.nixos.org/nixos/20.09/nixos-20.09.4306.1a40a7254ea shows it was last built 08/06 with commit `1a40a7254eaedb560b47096c7b1ae368ad716279`.

That commit is exactly the commit for this issue: https://github.com/NixOS/nixpkgs/commit/1a40a7254eaedb560b47096c7b1ae368ad716279

Forgive my ignorance, but shouldn't a channel update + nixos-rebuild pull this in and 'just work' ?

**Comment by Artturin** [comment]
Run nix-channel with sudo

**Comment by spacekitteh** [comment]
Do games run with Proton anymore for you? I can get Yooka-Laylee to work using the nix-shell command, but not Foxhole, which requires Proton. I'm on unstable, if that changes anything.

**Comment by dukc** [comment]
For those who are like me and install user software with `nix-env -f ~/install.nix -ir ".*" `, this workaround works, at /home/[username]/install.nix:
```
let pkgs = import <nixpkgs> {}; in
{ # possibly other packages...
  steam = pkgs.steam.override { extraLibraries = pkgs: [ pkgs.pipewire ]; };
 # possibly other packages...
}
```

**Comment by channikhabra** [comment]
@dukc Your snippet helped me get steam running in my flakes based setup. Thank you!
Properly learning nix averted for yet another day. Hooray!

**Comment by jbalme** [comment]
My crasher was solved by adding `networkmanager` to `extraLibraries`. It's a different, unrelated bug, so I will create a separate issue tonight probably.

**Comment by yisraeldov** [comment]
I did a `sudo nix-channel --update && sudo nixos-rebuild switch` and steam started working for me again. Thanks for fixing this!

**Comment by jonringer** [comment]
... Ironically, all channels have updated with fixes except unstable...

**Comment by wkral** [comment]
Latest unstable now has this fix and my steam is working again. Thanks folks.

**Comment by owen-d** [comment]
cc @jonringer (Apologies for the ping, please let me know if it's inappropriate)

## Info
I've encountered some strange behavior trying to get this to work. Steam will notably fail with the following error despite running `sudo nixos-rebuild switch --upgrade` to bump the `21.05` and `unstable` channels:
```
Error: You are missing the following 32-bit libraries, and Steam may not run:
libpipewire-0.3.so.0
```

## Alternatives

I've also tried using `unstable` and attempted to add the `pkgs.pipewire` override to both channels, like:
```
(pkgs.steam.override { extraLibraries = pkgs: [ pkgs.pipewire ]; })
```

Unfortunately, none of these approaches worked.

## Unexpected Resolution

In a surprising twist, the following does work, although I can't figure out how it's different :thinking::
```
NIXPKGS_ALLOW_UNFREE=1 NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/refs/heads/release-21.05.tar.gz nix-shell -p steam --run steam
```

## Environment

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.05.2981.1e5c35dfbc8 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(owen): `""`
 - channels(root): `"nixos-21.05.2981.1e5c35dfbc8, nixos-unstable-21.11pre312972.a51aa6523bd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by jbalme** [comment]
@owen-d 

Do you have a stale `steam` installed under your user account, or otherwise have a stale `steam` in your path somewhere?

Try a `which steam` to see where `steam` is coming from.

**Comment by owen-d** [comment]
I don't think so, @jbalme, unless I've done so accidentally.

```
$ which steam
/home/owen/.nix-profile/bin/steam
$ ls -l `which steam`
lrwxrwxrwx 1 root root 59 Dec 31  1969 /home/owen/.nix-profile/bin/steam -> /nix/store/iz036s6i1mc0qxclcgr93harqp5swfy2-steam/bin/steam
```

**Comment by jbalme** [comment]
That `steam` is installed in your user account via `nix-env`. 

`sudo nixos-rebuild switch --upgrade` only upgrades "declarative-style" packages referenced by your `configuration.nix`. It will not update packages installed via `nix-env`.

Do one of the following:

* If you want to manage steam declaratively, enable `steam` in your `configuration.nix`, for example, by setting `programs.steam.enable=true;` and then run `nix-env -e steam` to uninstall older versions installed via `nix-env`
* If you want to manage `steam` via `nix-env`, remember to periodically `nix-env -u` to upgrade those packages.

I recommend picking one strategy or the other exclusively for managing your packages.

**Comment by owen-d** [comment]
@jbalme great eye, thank you for the advice and thorough explanation!

After running `nix-env -e steam`, I can see it now uses the updated path and loads correctly. 
```
$ which steam
/run/current-system/sw/bin/steam
```
