### ISSUE TITLE
Discord can't find shared libraries (on master)

### ISSUE THREAD

**Issue by yokodake** [NixOS/nixpkgs#124368]
**Describe the bug**
If I start Discord, it can't find libffmpeg:
```
$ Discord
/home/user/.nix-profile/bin/Discord: error while loading shared libraries: libffmpeg.so: cannot open shared object file: No such file or directory
```

I found this issue #104340, and tried to set the LD_LIBRARY_PATH like mentioned:
```
$ LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(dirname $(which Discord))/../opt/Discord/ Discord
/home/user/.nix-profile/bin/Discord: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory
```
but it then can't find libdrm.
Not sure what I have to do after that...

`readelf -d /path/to/disord-0.0.15/opt/Discord/.Discord-wrapped`
shows that no RUNPATH is set.

<details>
  <summary>and here is the result of `nix-build . -A discord --check`. not sure if that's useful.</summary>
  <pre><code>
checking outputs of '/nix/store/bb9jl9r08w4fy5wj07d36frhw54rq1vc-discord-0.0.15.drv'...
unpacking sources
unpacking source archive /nix/store/nr94jc8l68k243pf3v1xgkka02m995n2-discord-0.0.15.tar.gz
source root is Discord
setting SOURCE_DATE_EPOCH to timestamp 1621890960 of file Discord/swiftshader/libGLESv2.so
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
gappsWrapperArgsHook
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/chrome-sandbox
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libEGL.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libGLESv2.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libffmpeg.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libvk_swiftshader.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libvulkan.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/swiftshader/libGLESv2.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/swiftshader/libEGL.so
shrinking /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/.Discord-wrapped
rewriting symlink /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/bin/Discord to be relative to /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15
rewriting symlink /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/share/pixmaps/discord.png to be relative to /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15
strip is /nix/store/77i6h1kjpdww9zzpvkmgyym2mz65yff1-binutils-2.35.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/bin 
patching script interpreter paths in /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15
/nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/postinst.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/a4yw1svqqk4d8lhwinn9xp847zz9gfma-bash-4.4-p23/bin/sh"
checking for references to /build/ in /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15...
automatically fixing dependencies for ELF files
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/chrome-sandbox
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libEGL.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libGLESv2.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libffmpeg.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libvk_swiftshader.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/libvulkan.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/swiftshader/libGLESv2.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/swiftshader/libEGL.so
searching for dependencies of /nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15/opt/Discord/.Discord-wrapped
/nix/store/2614f2y7n0ch0p8gdrvri3mchfm80wpn-discord-0.0.15
</pre></code>
</details>

**To Reproduce**
1. nix-env -f . -iA discord
2. Discord

**Expected behavior**
Discord starting.

**Additional context**
I built Discord from master since, it now refuses to run any version < 0.0.15, and the update hasn't landed in `nixpkgs-unstable` yet.

**Notify maintainers**

@MP2E 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.107, NixOS, 21.11pre291991.ea7d4aa9b82 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.11pre291991.ea7d4aa9b82"`
 - channels(ngyj): `"nixpkgs-21.05pre291370.dcd5d9a8e5c"`
 - nixpkgs: `/home/ngyj/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
works for me 
```
nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs/archive/refs/heads/master.tar.gz -p discord

Discord

Discord 0.0.15
(node:519239) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/user/.config/discord/0.0.15/modules
[Modules] Module installed file path: /home/user/.config/discord/0.0.15/modules/installed.json
[Modules] Module download path: /home/user/.config/discord/0.0.15/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
```

`21.11pre291991.ea7d4aa9b82`

**Comment by yokodake** [comment]
So the problem might come from my machine, something unrelated?
Indeed reinstalling discord-0.0.14 from nixpkgs-unstable exhibits the same problem...

I don't really see anything particular I did that might cause this.

**Comment by Artturin** [comment]
try moving or removing `~/.config/discord` removing it will remove your fav gifs so back them up first

```
to save discord fav gifs
ctrl shift i
application tab
local storage > https://discord.com
put GIFF in the filter search
copy the value and put it into a file

to restore
do the same as above but paste the old value
```

**Comment by Artturin** [comment]
your user nixpkgs channel is not at the newest version , update it by running `nix-channel --update` without root

**Comment by mohe2015** [comment]
Does https://github.com/NixOS/nixpkgs/issues/104340#issuecomment-730815509 fix the problem for you because it worked for me. @leo60228 would you like to create a pull request with that change?

**Comment by iagocq** [comment]
had the same problem as this issue, was able to fix it with this patch (based on @leo60228's patch and @yokodake's info)

```patch
diff --git a/pkgs/applications/networking/instant-messengers/discord/base.nix b/pkgs/applications/networking/instant-messengers/discord/base.nix
index 841c979e..ae806c4a 100644
--- a/pkgs/applications/networking/instant-messengers/discord/base.nix
+++ b/pkgs/applications/networking/instant-messengers/discord/base.nix
@@ -31,6 +31,7 @@ in stdenv.mkDerivation rec {
   dontWrapGApps = true;

   libPath = lib.makeLibraryPath [
+    libdrm mesa
     libcxx systemd libpulseaudio
     stdenv.cc.cc alsaLib atk at-spi2-atk at-spi2-core cairo cups dbus expat fontconfig freetype
     gdk-pixbuf glib gtk3 libnotify libX11 libXcomposite libuuid
@@ -50,7 +51,7 @@ in stdenv.mkDerivation rec {
     wrapProgram $out/opt/${binaryName}/${binaryName} \
         "''${gappsWrapperArgs[@]}" \
         --prefix XDG_DATA_DIRS : "${gtk3}/share/gsettings-schemas/${gtk3.name}/" \
-        --prefix LD_LIBRARY_PATH : ${libPath}
+        --prefix LD_LIBRARY_PATH : ${libPath}:$out/opt/${binaryName}

     ln -s $out/opt/${binaryName}/${binaryName} $out/bin/
     ln -s $out/opt/${binaryName}/discord.png $out/share/pixmaps/${pname}.png
```

**Comment by skykanin** [comment]
I was having the same issue as OP and @iagocq's patch worked for me. Here is my machine info:
```
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.05pre291486.900115a4f7f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(skykanin): `""`
 - channels(root): `"nixos-21.11pre291991.ea7d4aa9b82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
