### ISSUE TITLE
glibc should be patched to look for /etc/protocols in /nix/store

### ISSUE THREAD

**Issue by fzakaria** [NixOS/nixpkgs#124401]
**Describe the bug**
Certain functions in glibc look for files present in **/etc** such as [getprotobyname](https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_313.html) which reads `/etc/protocols`.
If you are using Nix over a Linux installation, this file may not be present, and therefore it will cause errors.

Nix should strive to be as reproducible and hermetic as possible.
Rather than looking for the files at **/etc**, _glibc_ should be patched to look for these files in the _/nix/store_; very similar to how Nix does LOCAL_ARCHIVE.

Right now the guidance is to use **libredirect** (https://nixos.wiki/wiki/Packaging/Quirks_and_Caveats#Test_cannot_access_.2Fetc.2Fprotocols.2C_.2Fetc.2Fservices_or_expects_a_special_.2Fetc.2Fpasswd_when_building_in_sandbox) which seems unfortunate and annoying to users.

Useful links:
https://github.com/bminor/glibc/blob/595c22ecd8e87a27fd19270ed30fdbae9ad25426/resolv/netdb.h#L47

**Notify maintainers**
I did not see any explicit maintainers, so tagged a few from the history of the file.

@thefloweringash 
@Mic92 
@vcunat
@edolstra 
@ma27

**Comment by Mic92** [comment]
Is this file not supposed to be configurable? Or do you mean there should be environment variables to redirect it?

**Comment by fzakaria** [comment]
The file in _glibc_ is hardcoded.
For instance on a Debian installation you must have `sudo apt-get install -y netbase`.

Ultimately shouldn't everything be self-contained to the /nix/store ?
Seems like it's less of a problem on NixOS but on Nix on other Linux distributions it should doing to another nixpkg similar to LOCAL_ARCHIVE.

**Comment by vcunat** [comment]
I think that adding such variables should only be done very carefully.  I suspect there are some reasons for restricting some of these (say, LD_LIBRARY_PATH) in setuid binaries, and we might just be adding a security hole this way (a small-ish one if any, I expect, but still).

**Comment by fzakaria** [comment]
I'm not really following your logic @vcunat: reading files outside of the /nix/store and relying on the environment though is antithesis to the concept of Nix and it's versioning.

I think this aligns close to many other similar patches such as that to clang/gcc to not read from default library paths or the locales as mentioned.

**Comment by edolstra** [comment]
`/etc/protocols` is runtime configuration data, just like `/etc/resolv.conf` or `/etc/nsswitch.conf` or `/etc/hosts`. You don't want to rebuild the entire system just to change `protocols`. Now, in practice nobody ever changes `/etc/protocols` so we could get away with hard-coding it, but it would be a bit fishy. The same applies to `/etc/services` BTW.

**Comment by vcunat** [comment]
And the potential risks I know about should be fixable by copy&paste of the usual setuid checks (like for LD_LIBRARY_PATH).  Using setuid for nix-built executables on non-NixOS is probably not common anyway.  Maybe just... the overall design of these customizations could be given some more thought.

**Comment by edolstra** [comment]
See also https://github.com/NixOS/nixpkgs/pull/111194, which proposes adding an environment variable for the NSS search path, and https://gist.github.com/Infinisil/3366e7dfc9a01f6eeb25b5cb475cc585 which proposes a generic environment variable.

**Comment by fzakaria** [comment]
I guess rather than hardcode, I am advocating for something similar to make an environment variable override.
It's just a bummer than out-of-the-box on Debian, Nix can cause failures since glibc does not find these files.
Maybe a fallback to an entry in the /nix/store ?

**Comment by vcunat** [comment]
Uh, I wonder what Debian's glibc does then.  Any package with a binary using these syscalls should declare a dependency on `netbase`?

**Comment by fzakaria** [comment]
That's my understanding; and-or it's brought eventually and the problem stabilizes.
(That non-determinism seems perfect for Nix to solve)

**Comment by vcunat** [comment]
We might also make `nix` depend on `netbase` on Debian :trollface: (say, for the short term)

**Comment by ajs124** [comment]
It might be worth noting that go in nixpkgs actually does hardcode this, since 6039f2effea02c1ee6a716d0487f787293cd081b.

Maybe that has been reverted at some point, but when I looked into this (#101038) it was still the case.

**Comment by fzakaria** [comment]
Interesting; well that's only for golang built binaries in Nixpkgs.
Should I put time on this for a patch or is there a broader discussion here that is more well suited for an RFC?

**Comment by Mic92** [comment]
No. just make a PR.

**Comment by fzakaria** [comment]
@Mic92 PR incoming today.

**Comment by fzakaria** [comment]
Wow; I spent time trying to dig through the glibc code @Mic92 -- intense.
The getproto code is very macro heavy

**Comment by Mic92** [comment]
> Wow; I spent time trying to dig through the glibc code @Mic92 -- intense.
> The getproto code is very macro heavy

The glibc code quality is quite bad. Mainly because of one former long-term maintainer.

**Comment by fzakaria** [comment]
:(
I really wanted to patch it. Maybe I'll give it another shot to walk the macros later ...

**Comment by L-as** [comment]
If it's runtime configuration data, oughtn't we include it in the sandbox?
