### ISSUE TITLE
kernel NULL pointer dereference with 5.11.21+

### ISSUE THREAD

**Issue by seqizz** [NixOS/nixpkgs#124403]
**Describe the bug**
Recently rebooted my laptop (Dell XPS 13 9310) with 5.11.21 kernel, and it seems to stuck on boot. Booting with 5.11.20 kernel shows following error for the failing boot on journalctl logs: [error.txt](https://github.com/NixOS/nixpkgs/files/6541249/error.txt)

**To Reproduce**
1. Use `kernelPackages = pkgs.linuxPackages_latest;` with XPS 9310
2. Boot into new generation

**Additional context**
It's 100% reproducible on my laptop. No other kernel versions had any stability issues. I can run more diagnostics if needed.
cmdline of working system, if related: `initrd=\efi\nixos\jqhv4s486wzamr02frfk2rwpprqv70sh-initrd-linux-5.11.20-initrd.efi systemConfig=/nix/store/g1haws7c408v0xiamni8s8pxm9siynal-nixos-system-innodellix-20.09.4132.52090c613ad init=/nix/store/g1haws7c408v0xiamni8s8pxm9siynal-nixos-system-innodellix-20.09.4132.52090c613ad/init intel_pstate=disable i915.enable_fbc=1 i915.enable_guc=2 i915.modeset=1 video=eDP-1:1920x1200@60 loglevel=4`

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.20, NixOS, 20.09.4132.52090c613ad (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-20.09.4154.33824cdf8e4"`
 - channels(gurkan): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by clushie** [comment]
I have the same issue, switching to `boot.kernelPackages = pkgs.linuxPackages_zen;` (for example) resolved the problem for me on nix unstable.

**Comment by hmenke** [comment]
What chipset do you have? I have a Dell XPS 13 9310 with AX201 chipset and on NixOS 20.09 with Kernel 5.11.21 I have not yet observed any problems.

**Comment by seqizz** [comment]
I have the same:
```
~> lspci | grep -i network
00:14.3 Network controller: Intel Corporation Wi-Fi 6 AX201 (rev 20)
```

**Comment by clushie** [comment]
```
3a:00.0 Network controller: Intel Corporation Wireless-AC 9260 (rev 29)
```


```bash
grep -m1 'model name' /proc/cpuinfo
# model name      : Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
```

**Comment by seqizz** [comment]
Hmm I'd like to make a correction: It's not 100% reproducible for me now. After latest rebuild, I was able to boot 5.11.21 without issues :thinking:

**Comment by seqizz** [comment]
Had the issue with 5.12.4 after switching to 21.05. Still not 100% reproducible. Second attempt booted successfully.

**Comment by hmenke** [comment]
I'm actually also having performance problems with 5.11.21 but no crashes. With 5.11 the udev-settle service takes 15 secs on startup and I have horrible input lag in GNOME on Wayland. Downgrading to 5.10.37 made it better (there is still some laggyness in XWayland windows but that might be unrelated).

**Comment by clushie** [comment]
@hmenke Any valuable information in `dmesg`?

**Comment by seqizz** [comment]
Closing since there were not much activity + I didn't see the issue for a long time because of switching to unstable channel's kernel. Feel free to reopen if you still see this issue.
