### ISSUE TITLE
libclang: No easy way to get correct command line arguments as there is for clang.

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#12453]
libclang is quite tricky to use on nix as there doesn't seem to be an easy way to get the system include directories which are supplied by clang-wrapper for clang.

A little utility program which prints the extra system includes would be very helpful in solving issues such as this: https://github.com/Rip-Rip/clang_complete/issues/469

**Comment by vcunat** [comment]
Why not this?
```
$ clang --print-search-dirs
programs: =/nix/store/xscs9w0zsji4mdxdx9y2q71rschwbig2-clang-3.7.0/bin:/nix/store/rpdv6pi9z5dq7mcfh3rsavx0aixvcgl1-gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../x86_64-unknown-linux-gnu/bin
libraries: =/nix/store/xscs9w0zsji4mdxdx9y2q71rschwbig2-clang-3.7.0/bin/../lib/clang/3.7.0:/nix/store/rpdv6pi9z5dq7mcfh3rsavx0aixvcgl1-gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3:/nix/store/rpdv6pi9z5dq7mcfh3rsavx0aixvcgl1-gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64:/nix/store/rpdv6pi9z5dq7mcfh3rsavx0aixvcgl1-gcc-4.9.3/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3/../../..:/nix/store/xscs9w0zsji4mdxdx9y2q71rschwbig2-clang-3.7.0/bin/../lib
```

**Comment by jgeerds** [comment]
@expipiplus1 Does @vcunat solution helps you?

**Comment by expipiplus1** [comment]
ah yes, that's just what I wanted. Thanks @vcunat

**Comment by vcunat** [comment]
:-)

**Comment by stites** [comment]
Followup for anyone who finds this issue and, like me, is in need of getting the libclang path for something like [chromatica.nvim](https://github.com/arakashic/chromatica.nvim) (a vim theme that asynchrounously validates against libclang). `clang-unwrapped` is what you need and libclang itself can be found in `"${clang-unwrapped.lib}/lib"`.
