### ISSUE TITLE
Caps lock indicator light does not work during stage 1 boot

### ISSUE THREAD

**Issue by IreneKnapp** [NixOS/nixpkgs#12456]
During stage 1 of booting, caps lock itself is fine, but the indicator light on my USB keyboard stays off, always.

This appears to be a known issue in Debian; see [Stack Exchange](http://unix.stackexchange.com/questions/136817/caps-lock-led-not-working-on-linux-console) and [the Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=514464). NixOS is using Debian's git repository for console-setup; see [pkgs/tools/X11/ckbcomp/default.nix](https://github.com/NixOS/nixpkgs/blob/b2f8c7221b4ca3e86e83c160fe5790ca05bc25cb/pkgs/tools/X11/ckbcomp/default.nix#L8). So, I think we've inherited this bug, except that later boot stages fix it.

If you're wondering, this is an inconvenience when typing my LUKS password; I can't accurately type a 60-character mixed-case password without visual feedback using the shift key, so I've gotten in the habit of using caps lock. That's harder now, since I have to carefully track its state mentally instead of relying on the indicator.

This worked until a couple months ago, and I only just decided it was worth filing an issue.

**Comment by dezgeg** [comment]
`pkgs/tools/X11/ckbcomp/default.nix` isn't used in stage-1 in any way - this is probably either kernel or udev regression.

**Comment by vcunat** [comment]
I would hope Debian people solve it, having much more resources than us, but the bug thread has been idle for about half a year...

**Comment by rasendubi** [comment]
(triage) still an issue?

Also, there is workaround proposed in the debian bug:
> Samuel Thibault, le Thu 11 Jun 2015 16:28:03 +0200, a écrit :
> > Samuel Thibault, le Thu 11 Jun 2015 10:08:09 +0200, a écrit :
> > > Putting
> > >
> > > `SUBSYSTEM=="leds", ENV{DEVPATH}=="*/input*::capslock", ATTR{trigger}="kbd-ctrlllock"`
> > >
> > > in /etc/udev/rules.d/50-leds.rules seems to be doing the work.
> > 
> > Except that it makes my system unbootable. For whatever reason, systemd
> > indefinitely waits for the network to become available...

> `ACTION=="add", SUBSYSTEM=="leds", ENV{DEVPATH}=="*/input*::capslock", ATTR{trigger}="kbd-ctrlllock"`

> works, however :)

> Samuel

Has anyone tested it?

**Comment by IreneKnapp** [comment]
I'll try it again at some point within the next few weeks.

**Comment by IreneKnapp** [comment]
The issue still exists in unstable as of ... whenever I last updated it, which was no more than two or three weeks ago. (The reboot I tested it with wasn't a planned one or I'd have updated first. :))

I have now added the following to my config, and will report back after my next reboot as to whether it worked. This should be in a week or two.

```
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="leds", ENV{DEVPATH}=="*/input*::capslock", ATTR{trigger}="kbd-ctrlllock"
  '';
```

**Comment by rasendubi** [comment]
@IreneKnapp do you have any updates?

**Comment by IreneKnapp** [comment]
I have now tested the above config lines. They did not help.

**Comment by Mic92** [comment]
I am not surprised that udev rules do not help in stage 1 boot with an encrypted root partition.
To made this work `kbd-ctrlllock` would have to be included in initramfs.

**Comment by IreneKnapp** [comment]
When I get the chance I'll try to figure out where the stage 1 keyboard config is actually coming from. :)

**Comment by IreneKnapp** [comment]
Update: This is resolved with `boot.initrd.availableKernelModules = [ "input_leds" ];`

In the event that anyone on the planet except me cared, you're welcome. :)

**Comment by IreneKnapp** [comment]
Actually, I'm going to reopen this so that I can have it as a reminder to send a patch. No reason not to have that module added when LUKS is used...

**Comment by n0099** [comment]
Also try
```
boot.initrd.kernelModules = [ "input_leds" ];
```
if it's already in `availableKernelModules`.
