### ISSUE TITLE
displaycal-3.8.9.3 depends on broken python2.7-Pillow-6.2.2

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#124590]
`displaycal` is broken, because its dependency 'python27-Pillow` has been marked as insecure. To fix that, we need to upgrade `displaycal` to use python3 or we have to find some kind of patch for the old `Pillow` version:

~~~
$ nix-build --no-out-link -A displaycal
error: Package ‘python2.7-Pillow-6.2.2’ in /home/simons/src/nixpkgs/pkgs/development/python-modules/pillow/6.nix:19 is marked as insecure, refusing to evaluate.
~~~

**Comment by toastal** [comment]
Obviously this is far from ideal
```nix
# /etc/nixos/configuration.nix
{
  # ...

  nixpkgs.config.permittedInsecurePackages = [
    "python2.7-Pillow-6.2.2"
  ];

  # ...
}
```

**Comment by davidak** [comment]
How does displaycal depend on pillow?

It is not mentioned in https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/displaycal/default.nix and even `nix why-depends` claims 'nixpkgs.displaycal' does not depend on 'nixpkgs.python2.pkgs.pillow'.

A way to fix this would be to update displaycal to python 3, but i'm not sure if they are doing that. The project seem pretty inactive.

**Comment by davidak** [comment]
pyopengl depends on pillow

the linked PR does not fix this issue

cc @SCOTT-HAMILTON

```
[davidak@gaming:~]$ nix run -f channel:nixos-unstable displaycal -c displaycal
[18.8 MiB DL]
error: Package ‘python2.7-Pillow-6.2.2’ in /nix/store/3f8yzwd69i873gcckdmp10jwpq2imlyw-nixexprs.tar.xz/pkgs/development/python-modules/pillow/6.nix:19 is marked as insecure, refusing to evaluate.
```

**Comment by davidak** [comment]
so, displaycal is python2
depends on wxPython 3, which is python2. later versions support python3
depends on python27Packages.pyopengl (update available). later versions support python3
depends on pillow 6 (pillow 7 dropped python2 support), no update available for 6. later versions support python3

so **they** have to update their codebase to support python 3 and later versions of pillow

we can't do much here. we could help them with the migration, but the project looks pretty dead. got no reply to my e-mail to the developer yet

we can leave it at this and wait for upstream. at some point we might have to remove the package. that would make linux unusable for professionals working on visual work. someone could make a fork...

**Comment by davidak** [comment]
Statements from the developer:
- https://discuss.pixls.us/t/rip-displaycal/21775/8
- https://discuss.pixls.us/t/rip-displaycal/21775/75

An inactive fork: https://github.com/RomanHargrave/displaycal

People have created a Flatpak to keep using it: https://flathub.org/apps/details/net.displaycal.DisplayCAL

The best option seem to keep using this insecure package until a new version is available, which could take a long time, since the one maintainer has other priorities and don't accept contributions. A good initiative would be a community fork.

**Comment by Artturin** [comment]
i suggest creating a flake this software is still needed

it was removed from nixpkgs 2022-01-12

**Comment by toastal** [comment]
There is a Python3 fork out there now: https://github.com/eoyilmaz/displaycal-py3
