### ISSUE TITLE
TradingView

### ISSUE THREAD

**Issue by rxf4el** [NixOS/nixpkgs#124687]
**Project description**
Tradingview is a trader platform that helps analyse price actions.

**Metadata**

* homepage URL: https://www.tradingview.com/blog/en/tradingview-desktop-on-linux-24631/
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by sumnerevans** [comment]
Doesn't look like it's open source and it's only available via snap package right now.

If this is not the case, can you please update the source URL and specify the license?
