### ISSUE TITLE
Revamp NixOS VM test machinery to use libvirt

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12460]
After this, we should be able to run most "VM" tests on AWS EC2 and similar VM providers. Currently we rely on `qemu-kvm`, and thus can't without nested virtualization.

In particular, I'm looking for support of libvirt's LXC and Xen providers for our test framework, as well as qemu, obviously. Most of our tests could easily run inside containers, and others could work fine as paravirtual Xen guests.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixpkgs/issues/5241

**Comment by domenkozar** [comment]
Let's close this not to have duplicate discussions.

**Comment by copumpkin** [comment]
Oh whoops, forgot about that, thanks!
