### ISSUE TITLE
Instructions for contributing to nixpkgs docs do not work

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#124743]
**Describe the bug**

To contribute to the nixpkgs documentation I followed the instructions in the nixpkgs manual "Chapter 21. Contributing to this documentation" and I followed the code snippet 

```
$ cd /path/to/nixpkgs/doc
$ nix-shell
[nix-shell]$ make
```

Firstly I was greeted with some warnings:
```
trace: lib.crossLists is deprecated, use lib.cartesianProductOfSets instead
trace: `mkStrict' is obsolete; use `mkOverride 0' instead.
trace: `lib.nixpkgsVersion` is deprecated, use `lib.version` instead!
trace: warning: lib.readPathsFromFile is deprecated, use a list instead
trace: Warning: `showVal` is deprecated and will be removed in the next release, please use `traceSeqN`
trace: lib.zip is deprecated, use lib.zipAttrsWith instead
```

But moving on to `make` I saw a large number of `/diagram-generator.lua: openBinaryFile: does not exist (No such file or directory)` errors. It looks like `makeFlags=PANDOC_LUA_FILTERS_DIR=/nix/store/xyn7np2z62dr711sgxyz2lkxk54pwivx-pandoc-lua-filters-2020-11-30/share/pandoc/filters` is set up inside the nix-shell but it's not picked up by `make`?

Running the `nix-build .` command does work.

**To Reproduce**

```
$ cd /path/to/nixpkgs/doc
$ nix-shell
[nix-shell]$ make
```
**Expected behavior**

No warnings, no errors.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.11.20210527.5658fad (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(frijters): `""`
 - channels(root): `"nixos, nixos-unstable-20.09pre225264.683c68232e9"`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
nix-shell has a specific setup to allow running stdenv phases such as
```
[nix-shell]$ buildPhase
```
https://nixos.org/manual/nix/unstable/command-ref/nix-shell.html

**Comment by SFrijters** [comment]
That also gives me a bunch of errors as well, but different ones:
```
stdenv/stdenv.chapter.xml:1: parser error : Document is empty

^
manual.xml:18: element include: XInclude error : could not load stdenv/stdenv.chapter.xml, and no fallback was found
```

For a bunch of files.

I managed to write some updates to the docs and validated them just using the `nix-build` command, but it's a bit unfortunate that just following the instructions literally doesn't work.

**Comment by jtojnar** [comment]
Sorry about that. https://github.com/NixOS/nixpkgs/pull/125625 should fix it.

**Comment by SFrijters** [comment]
Thanks, that fixes it for me (tested by setting the env variable manually).
Great to see these steps towards making it easier to contribute to the docs.
