### ISSUE TITLE
unbound config emitted with wrong order of keys

### ISSUE THREAD

**Issue by pennae** [NixOS/nixpkgs#124780]
**Describe the bug**
the unbound config is sensitive to key ordering, but nix is not. this breaks when the nix order differes from the order unbound expects, eg for `define-tag`/`access-control-tag`. this may affect other combinations as well.

**To Reproduce**
configure unbound with access control using tags, eg
```
settings = {
  define-tag = ''"local"'';
  access-control-tag = [ ''::1 "local"'' ];
};
```

**Screenshots**
```
May 28 19:27:28 eisn unbound[136995]: [1622222848] unbound[136995:0] error: parse taglist, but no tags defined
May 28 19:27:28 eisn unbound[136995]: /etc/unbound/unbound.conf:14: error: could not parse tags, (define-tag them first)
May 28 19:27:28 eisn unbound[136995]: read /etc/unbound/unbound.conf failed: 1 errors in configuration file
```

**Notify maintainers**
@rissson @andir 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05pre291486.900115a4f7f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05pre281933.7c6aa8400be"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by rissson** [comment]
I'm not sure how we could solve this. How about adding a specific option for `define-tag`?

**Comment by pennae** [comment]
sounds reasonable. had a cursory glance at the config man page and haven't found any dependencies like that listed there (not any others--any!). we might just have to react as things break :(

**Comment by rissson** [comment]
I'll open a PR then.

**Comment by hmenke** [comment]
If should always be possible to do something like this if you need a specific ordering of keys (untested)
```nix
{
  services.unbound.settings = {
    include = builtins.toFile "unbound-extra.cfg" ''
      define-tag = "local";
      access-control-tag = ::1 "local";
    '';
  };
}
```

**Comment by aanderse** [comment]
ping @Infinisil

**Comment by pennae** [comment]
@hmenke that does work, it's what we had before as a quick get-it-running-again after the rfc42 update of the module. tried to turn it into proper settings as was intended by the makers, and stuff promptly broke. :D

**Comment by hmenke** [comment]
It's totally fine that unbound is a freeform module and the benefits outweigh the drawbacks by far. Acutally I think this might even be worth an upstream bugreport, because having the order matter in a config file is almost always bad UX.

**Comment by pennae** [comment]
definitely true, but a look at the unbound config parser suggests that this won't be changing quickly. while their config does look like yaml it definitely isn't. on the flip side, `define-tag` seems to be the only option needing such special treatment in nix.

**Comment by BigValen** [comment]
I ran into an issue where putting a 'forward-zone' before 'server' in settings upsets unbound.

**Comment by jasoncarr0** [comment]
I ran into this issue for domain-insecure, local-zone, and local-data when they appeared before server.

In my previous working config these were after `server` and worked in that position but don't work here where they're placed before `server`. I've confirmed that the lines themselves are character-for-character identical.

**Comment by rissson** [comment]
#124799 would indeed do that.

**Comment by hmenke** [comment]
@BigValen @jasoncarr0 What you are describing is a different issue and stems from wrong configuration on your end. You will have to nest your `forward-zone` within `server` inside the settings.
```nix
{
  services.unbound.settings.server = {
    forward-zone = "...";
  };
}
```
I think the module should run [`unbound-checkconf`](https://www.nlnetlabs.nl/documentation/unbound/unbound-checkconf/) on the generated config to catch these errors at build time.

**Comment by rissson** [comment]
The `forward-zone` is an entirely different clause than the `server` clause, according to `unbound.conf(5)`. As for running `unbound-checkconf` at build time, it has been discussed [here](https://github.com/NixOS/nixpkgs/pull/89572#issuecomment-646015114) and in above comments.

**Comment by jasoncarr0** [comment]
Yeah in my case @hmenke it wasn't forward-zone causing any issues. The other zones were as I said character-for-character identical (including indentation) and the only difference was the ordering.
 
 Great to see that it's getting fixed as well
