### ISSUE TITLE
`emacsWithPackages` loads slowly

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#12478]
`emacsWithPackages` loads slower than `emacs` for users in some configurations. Initially, I thought this was due to the number of paths being set in the custom `site-start.el`. My benchmarks, however, show that this is *not* the cause.

I now suspect the problem is that our custom `site-start.el` loads `package.el` unconditionally. I think this increases load times for users who do not have it as part of their configuration already by triggering their load hooks. I started loading it at the beginning of `site-start.el` because it must be loaded before we set `package-directory-list`, but this could be hidden behind `eval-after-load`.

**Comment by ttuegel** [comment]
Anyone interested in helping to debug this problem should build `emacsWithPackages` from my [branch](https://github.com/ttuegel/nixpkgs/tree/emacsWithPackages).

**Comment by jagajaga** [comment]
cc @oxij

**Comment by ttuegel** [comment]
I could never reproduce the severity of this issue, but I merged some changes which provide small speed improvements anyway. I declare this issue closed by fiat because nobody would come forward with numbers.
