### ISSUE TITLE
Papermc crashes due to an incompatible Java version

### ISSUE THREAD

**Issue by j0hax** [NixOS/nixpkgs#124772]
**Describe the bug**

Papermc crashes due to an incompatible Java version

**To Reproduce**
- Set `services.minecraft-server.package = pkgs.papermc`

**Log Excerpt**

```console
-- Journal begins at Wed 2020-08-05 06:46:56 CEST. --
May 28 18:13:46 shepherd systemd[1]: Started Minecraft Server Service.
May 28 18:13:47 shepherd minecraft-server[191024]: Unsupported Java detected (60.0). Only up to Java 15 is supported.
May 28 18:13:47 shepherd systemd[1]: minecraft-server.service: Succeeded.
May 28 18:13:47 shepherd systemd[1]: minecraft-server.service: Consumed 2.013s CPU time, no IP traffic.
May 28 18:13:48 shepherd systemd[1]: minecraft-server.service: Scheduled restart job, restart counter is at 5.
May 28 18:13:48 shepherd systemd[1]: Stopped Minecraft Server Service.
May 28 18:13:48 shepherd systemd[1]: minecraft-server.service: Consumed 2.013s CPU time, no IP traffic.
May 28 18:13:48 shepherd systemd[1]: minecraft-server.service: Start request repeated too quickly.
May 28 18:13:48 shepherd systemd[1]: minecraft-server.service: Failed with result 'start-limit-hit'.
May 28 18:13:48 shepherd systemd[1]: Failed to start Minecraft Server Service.
```

**Additional context**
The vanilla `minecraft-server` package runs without issues.

**Notify maintainers**

@aaronjanse 
@neonfuz 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.21, NixOS, 21.11pre292520.540dccb2aea (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(johannes): `""`
 - channels(root): `"nixos-21.11pre292520.540dccb2aea, nixos-hardware, nixpkgs-21.03pre256757.cf7475d2061"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:  <nixpkgs/pkgs/games/papermc/default.nix>
# a list of nixos modules affected by the problem
module: <nixpkgs/nixos/modules/services/games/minecraft-server.nix>
```

**Comment by SCOTT-HAMILTON** [comment]
I couldn't reproduce with this test driver : https://gist.github.com/SCOTT-HAMILTON/e45ac40e4ea1d75deca3e5e1196d2f86.

**Comment by ZerataX** [comment]
I also get this. my setup:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.740.aa576357673 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.740.aa576357673, nixos-unstable-21.11pre293089.1c2986bbb80"`
 - channels(kaine): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by legendofmiracles** [comment]
Same thing happens with multimc and the new version
