### ISSUE TITLE
Unable to set GTKLookAndFeel in Java (Swing) applications

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#12472]
When running any Java application not defining its own look and feel, it’s LAF is the default, old blue one.

After explicitly passing `-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel` to the JVM, as suggested by ArchWiki in https://wiki.archlinux.org/index.php/java#GTK_LookAndFeel, I’m getting `An error occurred: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel`.

In other distributions (Arch, Debian) passing the option works correctly → apps look like native GTK apps.

```
% nixos-version
16.03pre75174.d0e3cca (Emu)
```

Reproduce with:

```
% nix-shell -p jmeter -p gnome.gtk --run \
    '_JAVA_OPTIONS=-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel jmeter' 
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=64m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
An error occurred: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
(1)% 
```

**Comment by bennofs** [comment]
The problem here is that Java dynamically loads `libgtk-x11-2.0.so`, which it doesn't find on NixOS systems. Setting LD_LIBRARY_PATH to a directory that contains that file fixes the problem.

We should probably wrap at least the Java executable to set that LD_LIBRARY_PATH.

**Comment by michalrus** [comment]
Works for me, too, thank you for debugging this! :smiley:

**Comment by Profpatsch** [comment]
> We should probably wrap at least the Java executable to set that LD_LIBRARY_PATH.

Java shouldn’t depend on GTK+, though. How to achieve that?

**Comment by bennofs** [comment]
@Profpatsch Java already does depend on GTK+ anyway

**Comment by martijnvermaat** [comment]
I stumbled upon this when launching PyCharm (`nixos.idea.pycharm-community`) from Gnome. Selecting the GTK+ theme raises an error similar to the one above. Also, the default IntelliJ theme does not use the GDK scaling settings (on a HiDPI screen PyCharm will have tiny fonts and UI elements).

Both are fixed by adding the GTK+ lib path to `LD_LIBRARY_PATH`.

@bennofs PyCharm uses OpenJDK 8 and it does not depend on GTK+:

    $ nix-env -iA nixos.idea.pycharm-community
    $ nix-store -qR $(type -p pycharm-community) | grep gtk
    $

Can we wrap OpenJDK 8 Java in a way that will add GTK+ to `LD_LIBRARY_PATH` when it's available, without making it a hard dependency? I guess that's not really how Nix works...

A way to solve this is to add override options to these kind of applications which can be used to pass GTK+ as a dependency. This way it would not be a new dependency for users that don't need it. But on the other hand the default behaviour will be crappy when running in a GTK based desktop environment.

**Comment by bennofs** [comment]
Oh, OpenJDK might not depend on GTK, I was using OracleJDK.

**Comment by martijnvermaat** [comment]
Ping @edwtjo (listed as maintainer of OpenJDK and the IDEA packages).

I'm happy to help but not sure what the best approach is here.

**Comment by abbradar** [comment]
See https://github.com/NixOS/nixpkgs/pull/19167 for an attempt to fix this -- I'm interested in feedback.

**Comment by abbradar** [comment]
Closing this as GTK LaF is the default for a long time.

**Comment by kourindouhime** [comment]
apt install libgtk2.0-0

**Comment by bhagwandassoni1953** [comment]
root@localhost:/LIST/Test1/DEMO25/jaydeepharmaceuticalssystem-code/JayDee/dist# java -jar JayDee.jar                                                              Exception in thread "main" java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel                                                                        at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1406)                                                                                   at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1517)            at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1483)                                                                                        at java.desktop/javax.swing.UIManager.getInstalledLookAndFeels(UIManager.java:422)                                                                                at jaydee.Main.main(Main.java:53)

**Comment by Nebucatnetzer** [comment]
I was able to fix this issue with the following options in a devshell on Ubuntu WSL.
The Java options fix the "Cannot load GTKLookAndFeel" and the FONTCONFIG_FILE option fixes an error that occurred after I fixed the GTK bug.

```
FONTCONFIG_FILE = pkgs.makeFontsConf {
  # required for burpsuite
  fontDirectories = [ pkgs.dejavu_fonts ];
};
_JAVA_OPTIONS = "-Dswing.defaultlaf=com.sun.java.swing.plaf.motif.MotifLookAndFeel";
```
