### ISSUE TITLE
nixos: Booting form LVM/LUKS fails with "failed to alloc_cipher" and "crypt: unknown target type" after upgrade

### ISSUE THREAD

**Issue by azahi** [NixOS/nixpkgs#124902]
**Describe the bug**
NixOS fails to boot from LUKS/LVM with GRUB2 after moving to `release-21.05` branch.

**To Reproduce**
1. Update the system to 21.05.
2. Reboot.

**Expected behavior**
Stage 1 succeeds and goes to stage 2. OS boots afterwards.

**Screenshots**
![](https://i.postimg.cc/Ls9K91gG/IMG-20210529-233349.jpg)

**Additional context**
Here is the [configuration](https://git.sr.ht/~azahi/nixfiles/tree/72cc7f0ef1c92dfd3d11ed70a0126f2ce8485a01/item/configurations/curumo.nix#L33-79) that was used to build the system.

My wild guess would be that the issue here is with device-mapper or/and systemd as the log suggested.

Apart from missing iwlwifi firmware I can boot to the 20.09 configuration without any other problems. Loading from live USB, cleaning `/boot` directory and re-running `nixos-rebuild switch` didn't help.

**Metadata**
_Note: currently booted to the latest available 20.09 configuration._
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.119, NixOS, 20.09.20210528.85960be (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(azahi): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ctem** [comment]
I also ran into this after upgrading a 20.09 system to 21.05. It seems to be a kernel-related issue; using `linuxPackages_5_4` (the 20.09 default) with the same configuration, the upgraded system boots normally, but with `linuxPackages_5_10` (the 21.05 default), `linuxPackages_5_11`, and `linuxPackages_5_12`/`linuxPackages_latest`, it fails at Stage 1.

This is the first time I’ve encountered this on NixOS, but the error has been discussed on the Arch bug tracker since at least kernel 5.8.

**Comment by azahi** [comment]
Using `linuxPackages_5_4` indeed fixes the issue. I also tried including `dm-crypt` into modules loaded by initrd but that didn't work.

Is there anyone who should be CC'd to this? I can't find a maintainer section for the kernel modules or packages.

**Comment by wamserma** [comment]
For completeness: Kernel 5.10.37 (linuxPackages_5_10) works fine with NixOS 20.09 (LVM on LUKS, GRUB 2, no EFI).

**Comment by wamserma** [comment]
I tried the switch to 21.05 and that also went fine:

```
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.git.60cce7e5e1f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
```

I don't have time to fiddle with rebuilds right now, but I have a few more modules in my config. You can try adding some of them and see if that helps. :)

```nix
boot.initrd.availableKernelModules = [ "ohci_pci" "ehci_pci" "pata_amd" "ahci" "usb_storage" "sd_mod" "sr_mod" ] ++ [ "dm_integrity" "dm_mod" "dm_crypt" "cryptd" "input_leds" ];
boot.initrd.luks.cryptoModules = [ "aes" "aes_generic" "cbc" "xts" "sha256" "sha512" "af_alg" "algif_skcipher"  ] ++ [ "chacha20" "chacha20poly1305" "poly1305" "poly1305_x86_64" ]; 
```

**Comment by S-NA** [comment]
This happened to me when upgrading from 5.11 to 5.12. Seeing the reported kernel versions people are hitting this issue on makes me think it is not an issue of a specific kernel version but an issue that occurs when upgrading the kernel on anything after version 5.4.

Regardless, fixing this issue for me was related to setting, `CONFIG_ENCRYPTED_KEYS=y`. I wish I could explain why this works but I do not really understand why. All I know is the error message originates from the module but when checking `zgrep ENCRYPTED_KEYS /proc/config.gz` on 5.11 I discovered, `# CONFIG_ENCRYPTED_KEYS is not set`.

If someone wants to test this, the following should work:
```nix
boot.kernelPatches = [ {
        name = "lvm-luks-workaround-config";
        patch = null;
        extraConfig = ''
                ENCRYPTED_KEYS y
        '';
} ];
```

**Comment by lambdafu** [comment]
The kernelPatches by S-NA worked for me when I encountered this issue.

**Comment by wamserma** [comment]
LUKS2 stores encryption keys in the Kernel keyring. Encrypted keys became available with dm-crypt 1.21.0 and kernel 5.8, see https://gitlab.com/cryptsetup/cryptsetup/-/wikis/DMCrypt
So the issue may appear for any upgrade from kernel < 5.0 to 5.8 or higher.

Having 
```
boot.initrd.availableKernelModules = [ dm_crypt ]
```
in the system config should select the ENCRYPTED_KEYS module as a dependency and have (almost) the same effect as the `boot.kernelPatches` statement above (with hopefully less rebuilding).

**Comment by S-NA** [comment]
According to `luksroot.nix` that seems to already happen:
https://github.com/NixOS/nixpkgs/blob/3a52368bc45611e4bb6631378b326451eb3dce1d/nixos/modules/system/boot/luksroot.nix#L864-L868

I did some digging and it seems, `CONFIG_DM_CRYPT` treats `CONFIG_ENCRYPTED_KEYS` as an optional dependency or at least allows it to be disabled.
https://github.com/torvalds/linux/blob/440462198d9c45e48f2d8d9b18c5702d92282f46/drivers/md/Kconfig#L269-L288

I cannot find anything in nixpkgs that instructs `dm_crypt` to enable `encrypted_keys`. It feels like an upstream bug allowing `CONFIG_DM_CRYPT` without `CONFIG_ENCRYPTED_KEYS` if the functionality is broken without it but I am not sure.

**Comment by wamserma** [comment]
This is definitely _not_ an upstream bug, as there are many scenarios where dm-crypt can be used without encrypted keys (e.g. anything using cryptsetup with LUKS1 only).
Here I have 
```
$ zgrep ENCRYPTED /proc/config.gz 
CONFIG_ENCRYPTED_KEYS=m
```

so something seems to pull in that dependency. Meanwhile it might be a good idea to list `encrypted_keys` in `luksroot.nix`.

**Comment by S-NA** [comment]
Hmm, I am not sure why I am running into this then, since I am using LUKS1. I think everyone that has a full disk encryption setup on NixOS is using LUKS1, since decrypting LUKS2 partitions via GRUB has not been added yet.
```
$ sudo cryptsetup luksDump /dev/sda1 | grep 'Version'
Version:        1
```

I agree about it being a good idea to add `encrypted_keys` to the list, but for me to do that I still need to set `CONFIG_ENCRYPTED_KEYS` to yes or a module. I mentioned before when I checked, the kernel config reported back that it did not have it set, so I wonder if you are perhaps using a custom kernel?

If you are, then I was thinking of making a PR to add `ENCRYPTED_KEYS = whenAtLeast "5.8" module;` in `pkgs/os-specific/linux/kernel/common-config.nix` along side adding your idea.

**Comment by wamserma** [comment]
I am pretty sure I am running an unmodified Kernel and I am definitely using LUKS2 for `/` (not for the boot-partition, so GRUB is not relevant here). Also, the screenshot of the original issue report shows a failure in stage 1.



Here:
```
$ sudo cryptsetup luksDump /dev/sdb2
LUKS header information
Version:       	2

$ ls /boot/kernels
65f9va1ql6x2vy23x4nqw0x18jz3a3x8-linux-5.10.45-bzImage
```

**Comment by S-NA** [comment]
Yeah, you are running an unmodified kernel. I also checked via doing `nix-build -A linuxPackages_5_10.kernel` and `grep encrypted ./result/lib/modules/5.10.47/modules.order`. Which returned, `kernel/security/keys/encrypted-keys/encrypted-keys.ko`. Which means nixpkgs definitely does include the module by default and adding `encrypted_keys` to the list in luksroot.nix should just work. Not sure why it was unset on my system, sorry. Do you want to do the PR for the luksroot.nix changes?

Someone else should also confirm that adding `encrypted_keys` to the list in luksroot.nix works for them, without the kernel config patch. Just so it is known it works for everyone else too.

**Comment by lambdafu** [comment]
I'm willing to test any proposed change given clear instructions what to do. For example, I can add stuff to my configuration.nix. I don't know how to add "encrypted_keys to the list in luksroot.nix", though.

**Comment by S-NA** [comment]
Sorry, I should have been clear.

Effectively, in your `configuration.nix` have `boot.initrd.availableKernelModules = [ "encrypted_keys" ]`.

**Comment by lambdafu** [comment]
Thanks for the explanation. I uncommented the kernelPatches and added the line to configuration.nix, but that did not fix the original problem. I also tried adding encrypted_keys to boot.initrd.luks.cryptoModules, that also did not work. So I am back to the kernelPatches for now!

**Comment by pSub** [comment]
@S-NA Your workaround does not work for me too. It seems other distros hat similar problems https://github.com/clearlinux/distribution/issues/2040.

**Comment by dkjii-g** [comment]
> Sorry, I should have been clear.
> 
> Effectively, in your `configuration.nix` have `boot.initrd.availableKernelModules = [ "encrypted_keys" ]`.

This did not work for me, but adding using `boot.initrd.availableKernelModules = [ "cbc" "hmac" "sha256" "rng" "aes" "encrypted_keys" ]` did. I'm not using CBC cipher so it might be something internal. ENCRYPTED_KEYS selects all of those so this is why setting it to Y fixes it, but not m.

modules-closure uses modprobe --show-depends which doesn't find any of these.

FYI, using luks1 instead of luks2 formatting did not fix the issue either.

**Comment by makefu** [comment]
hey, just wanted to write that i fell over the same issue, updating  `boot.initrd.availableKernelModules = [ "cbc" "hmac" "sha256" "rng" "aes" "encrypted_keys" .... ]` helped. I essentially mounted the operating system via live cd, updated my configuration and performed `nixos-install` with `NIX_PATH` set to the respective channel

**Comment by Artturin** [comment]
which one of those are required to be added?

sha256 and aes are already specified 

CONFIG_CRYPTO_HMAC is set to y so its already builtin

rng is a builtin too

so only the encrypted_keys should need to be added so could someone try just adding that?

**Comment by makefu** [comment]
@Artturin i haven't inspected any further tbh. However If you really want to know i can perform some tests this weekend

**Comment by azahi** [comment]
Closing because I no longer can reproduce this.
