### ISSUE TITLE
Unityhub: no more splashscreen (regression) and no .desktop file

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#124967]
**Describe the bug**
Since my last upgrade (from unstable 5ff6700bb82 to unstable 83d907fd760) unityhub does not display a splashscreen anymore when starting a project, the image is not found:

![image](https://user-images.githubusercontent.com/2164118/120104469-d59a3980-c154-11eb-881e-445aab54025d.png)

Before, a nice picture was displayed. Also, unityhub does not have any .desktop file, meaning that I need to start it from command line directly. Note that unityhub still works even without this.

**To Reproduce**
1. Install unityhub, and run it (via command line since there is no .desktop)
2. Start a project
3. While loading the project no splash screen is displayed

**Notify maintainers**

@tesq0

**Comment by tesq0** [comment]
@tobiasBora 
this one adds a .desktop file #132745
and i think this also fixes the splash #132737
