### ISSUE TITLE
nixos testing framework doesn't produce log.html anymore

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#124988]
**Describe the bug**
nixos testing framework doesn't produce log.html anymore

**To Reproduce**
1. `nix-build ./nixos/tests/login.nix` (on release-21.05 branch).
2. The `./result` is missing the log.html file.

**Expected behavior**
Last time I ran NixOS tests (probably years ago!) there was a log.html file in the output, and the nixos manual also documents the existence of log.html: https://nixos.org/manual/nixos/stable/#sec-running-nixos-tests.

**Notify maintainers**

**Comment by bjornfor** [comment]
Looks like that was removed in may 2020: 3f80fadec412ff6fb9fbe77d893c3156f955703b

**Comment by Synthetica9** [comment]
I think this is a "wontfix"?

**Comment by abathur** [comment]
Closing in agreement with synthetica, but happy to reopen if you think I'm overreaching :)
