### ISSUE TITLE
ImageMagick 6.9.2-0 download missing

### ISSUE THREAD

**Issue by rvl** [NixOS/nixpkgs#12493]
The download for 6.9.2-0 is missing from: ftp://ftp.imagemagick.org/pub/ImageMagick/releases/ It seems like they clear everything but the latest patch release from the download site.

Two options for bumping the version:
- 6.9.2-10
- 6.9.3-1

http://imagemagick.org/script/changelog.php

I suggest using 6.9.2 not 6.9.3 because it's unlikely to get a new patch release, meaning the download link will continue to work for a long time.

Cc maintainers: @the-kenny @wkennington

Cheers

**Comment by vcunat** [comment]
For now fixed up quickly without changing hashes. I consider updating a separate issue. (Feel free to file PRs for such.)

**Comment by vcunat** [comment]
Heh, the version on 15.09 is still on the upstream mirrors but it isn't on the one I added on master.
