### ISSUE TITLE
OpenColorIO is missing many executables

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#125049]
**Describe the bug**
When installing OpenColorIO, I expect to be able to run the 9 executables listed [here](https://opencolorio.readthedocs.io/en/latest/guides/using_ocio/using_ocio.html#overview-ocioconvert) (and that are present [in the repo](https://github.com/AcademySoftwareFoundation/OpenColorIO/tree/master/src/apps)), namely:

- ociobakelut
- ociocheck
- ociochecklut
- ociomakeclf
- ociowrite
- ociolutimage
- ocioconvert
- ociodisplay
- ocioperf

However, when installing opencolorio (from unstable), I only have two executables ociobakelut and ociocheck.

**To Reproduce**
1. Install opencolorio
2. Tab complete `ocio`

**Expected behavior**
I expect all 9 executables to be present.

**Notify maintainers**

@goibhniu

-- EDIT --
In the version 1, there is actually less executables, but some of them are still missing `ociobakelut  ociocheck  ocioconvert  ociodisplay  ociolutimage`. But it may actually be simpler to directly package the v2?

-- EDIT2 --
I tried to add the openimageio dependency (it seems to be the reason why ocioconvert is not compiled. It seems to find the OIIO library/lincludes, but it complains about ILMBASE.
```
-- Found OIIO library /nix/store/0mpk1g58hj92dz9rjfgx91h7lbb1p1cq-openimageio-1.8.17/lib/libOpenImageIO.so
-- Found OIIO includes /nix/store/7dirap8vlqyzcxi39nm50s3xp6q73n2m-openimageio-1.8.17-dev/include
-- Ilmbase not found. Specify ILMBASE_PATH to locate it
-- Not building ocioconvert/ociolutimage. Requirement(s) found: OIIO:FALSE
```

**Comment by tobiasBora** [comment]
Ok, I found the solution: both `openimageio` and `ilmbase` must be added to `buildInputs`. The following derivation seems to work for me. Note also that we may want to move to v2 instead of v1? Also, it would be great if we could package the python version library coming with OpenColorIO.

```
 { stdenv, lib, fetchFromGitHub, cmake, boost, pkg-config, lcms2, tinyxml, git, openimageio, ilmbase }:

with lib;

stdenv.mkDerivation rec {
  pname = "opencolorio";
  version = "1.1.1";

  src = fetchFromGitHub {
    owner = "imageworks";
    repo = "OpenColorIO";
    rev = "v${version}";
    sha256 = "12srvxca51czpfjl0gabpidj9n84mw78ivxy5w75qhq2mmc798sb";
  };

  outputs = [ "bin" "out" "dev" ];

  # TODO: Investigate whether git can be dropped: It's only used to apply patches
  nativeBuildInputs = [ cmake pkg-config git ];

  buildInputs = [ lcms2 tinyxml openimageio ilmbase ] ++ optional stdenv.isDarwin boost;

  postPatch = ''
    substituteInPlace src/core/CMakeLists.txt --replace "-Werror" ""
    substituteInPlace src/pyglue/CMakeLists.txt --replace "-Werror" ""
  '';

  cmakeFlags = [
    "-DUSE_EXTERNAL_LCMS=ON"
    "-DUSE_EXTERNAL_TINYXML=ON"
    # External libyamlcpp 0.6.* not compatible: https://github.com/imageworks/OpenColorIO/issues/517
    "-DUSE_EXTERNAL_YAML=OFF"
    "-DOCIO_BUILD_APPS=ON"
  ] ++ optional stdenv.isDarwin "-DOCIO_USE_BOOST_PTR=ON"
    ++ optional (!stdenv.hostPlatform.isi686 && !stdenv.hostPlatform.isx86_64) "-DOCIO_USE_SSE=OFF";

  postInstall = ''
    mkdir -p $bin/bin; mv $out/bin $bin/
  '';

  meta = with lib; {
    homepage = "https://opencolorio.org";
    description = "A color management framework for visual effects and animation";
    license = licenses.bsd3;
    maintainers = [ maintainers.goibhniu ];
    platforms = platforms.unix;
  };
}
```

**Comment by InternetUnexplorer** [comment]
This seems to have been fixed in https://github.com/NixOS/nixpkgs/pull/127522.

**Comment by FliegendeWurst** [comment]
Can confirm this was fixed by now.
