### ISSUE TITLE
ettercap - Upper right corner buttons icon incorrectly displayed.

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#125077]
**Describe the bug**
ettercap - Upper right corner buttons icon incorrectly displayed.

**To Reproduce**
1. Install `pkgs.ettercap` by adding home.packages = [ pkgs.ettercap ]
2. Exec `home-manager switch` to install ettercap
3. Exec `ettercap -G` to run ettercap with gtk gui

**Screenshots**
Upper right corner buttons seems not loaded, but gtk element (like checkbox) works fine.
![image](https://user-images.githubusercontent.com/25173827/120191659-ca2a3980-c24c-11eb-8fc7-4d3bac57baff.png)

**Additional context**
I setup `XDG_DATA_DIRS ` by following [NixOS/nixpkgs/issues/47094](https://github.com/NixOS/nixpkgs/issues/47094), but no changes.

**Notify maintainers**
@pSub 

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.5.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.11`
 - channels(vanilla): `"home-manager, nixpkgs"`
 - nixpkgs: `/Users/vanilla/.nix-defexpr/channels/nixpkgs`
```

**Comment by FliegendeWurst** [comment]
Works for me on latest unstable. Feel free to reopen if still an issue.
