### ISSUE TITLE
Virtual console font when hidpi is set to true gets reset to small default

### ISSUE THREAD

**Issue by datMaffin** [NixOS/nixpkgs#125109]
**Describe the bug**

A recent update/change seems to have broken the `hardware.video.hidpi.enable = lib.mkDefault true;` setting.
Specifically the change of increasing the font size in the virtual console, seems to reset itself during boot.

**To Reproduce**
1. use `hardware.video.hidpi.enable = lib.mkDefault true;` on current unstable
2. check the font size by looking at a tty

It may be specific to the GPU and driver.
I use a radeon RX 570 (and no integrated graphics).

**Expected behavior**
Font size should be increased in the virtual Linux console (ttys).

**Additional context**
I suspect that the ArchWiki describes the problem https://wiki.archlinux.org/title/Linux_console: 
"If the fonts appear to not change on boot, or change only temporarily, it is most likely that they got reset when graphics driver was initialized and console was switched to framebuffer. To avoid this, load your graphics driver earlier. See for example Kernel mode setting#Early KMS start, [3] or other ways to setup your framebuffer before /etc/vconsole.conf is applied. "

It was possible to fix the issue by setting `boot.initrd.kernelModules = [ "amdgpu" ];` in my `hardware-configuration.nix`.
(This also improved the quality of text during startup significantly.)

**Notify maintainers**
@Mic92 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05pre291103.d42cd445dde (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05pre291103.d42cd445dde"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

same behavior on current unstable:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.11pre292748.6933d068c5d (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.11pre292748.6933d068c5d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mic92** [comment]
We may need suggest amdgpu module in this case:

https://github.com/NixOS/nixos-hardware/blob/b2186d6c3cdc58fb3a8def0f608bcae61138cc6f/common/gpu/amd/default.nix#L4

**Comment by polygon** [comment]
The same happens for me with intel graphics. The console font is nice and big initially when entering the password for disk encryption. Then it continues booting and once the display manager is started, the console font is reset to a tiny size.

**Comment by datMaffin** [comment]
I no longer have this issue / this issue seems resolved.

If I now remove `boot.initrd.kernelModules = [ "amdgpu" ];`, the font size in the linux console (tty) no longer seems to reset itself to the smaller default.
