### ISSUE TITLE
KDE5 FTP URL Has Changed

### ISSUE THREAD

**Issue by adevore** [NixOS/nixpkgs#12514]
I am installing KDE5 from a newly downloaded 15.05 ISO. It is attempting to download plasma files from:

    ${KDE_MIRROR}/stable/plasma/5.3.2/

The target files were moved on January 11 to:

    ${KDE_MIRROR}/Attic/plasma/5.3.2/

**Comment by vcunat** [comment]
All I tried I was getting successfully from tarballs.nixos.org, but it's still good to fix this. Pushed.
