### ISSUE TITLE
Awesome WM does not add a .desktop entry for KDM

### ISSUE THREAD

**Issue by adevore** [NixOS/nixpkgs#12527]
Awesome installs a .desktop file, but KDM's default config files do not include its location. I am on Nixpkgs version 15.09.935.5a4e183.

**Comment by jgillich** [comment]
Did you set `services.xserver.windowManager.awesome.enable = true`?

**Comment by adevore** [comment]
You are correct, I had not added that to configuration.nix. I added a new wiki page at Awesome Window Manager that covers that step and where to get rc.lua.
