### ISSUE TITLE
PHP xsl extension broken

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#125264]
**Describe the bug**
Install php with xsl extension

**To Reproduce**
PHP Warning:  PHP Startup: Unable to load dynamic library '/nix/store/frr0k4dmfd02y4b6nq7shpw3q4gcjb7s-php-xsl-7.4.16/lib/php/extensions/xsl.so' (tried: /nix/store/frr0k4dmfd02y4b6nq7shpw3q4gcjb7s-php-xsl-7.4.16/lib/php/extensions/xsl.so (/nix/store/frr0k4dmfd02y4b6nq7shpw3q4gcjb7s-php-xsl-7.4.16/lib/php/extensions/xsl.so: undefined symbol: dom_node_class_entry), /nix/store/6r68y0fcr9k50lznk493w7iwh6jgna17-php-7.4.16/lib/php/extensions//nix/store/frr0k4dmfd02y4b6nq7shpw3q4gcjb7s-php-xsl-7.4.16/lib/php/extensions/xsl.so.so (/nix/store/6r68y0fcr9k50lznk493w7iwh6jgna17-php-7.4.16/lib/php/extensions//nix/store/frr0k4dmfd02y4b6nq7shpw3q4gcjb7s-php-xsl-7.4.16/lib/php/extensions/xsl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.4.16 (cli) (built: Mar  2 2021 10:35:27) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

**Expected behavior**
The extension is installed without errors

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.0-0.bpo.3-amd64, Ubuntu, 21.04 (Hirsute Hippo)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixpkgs-21.05pre273941.a2b0ea6865b"`
 - channels(dev): `"nixpkgs-21.05pre286880.7cb76200088"`
 - channels(projector-user): `"nixpkgs-21.05pre282843.dcdf30a78a5"`
 - nixpkgs: `/home/dev/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: php
# a list of nixos modules affected by the problem
module:
```

**Comment by ob7** [comment]
Whats your config for installing it?  I got same error when installing using:
(php.withExtensions ({ all, ... }: with all; [ xsl ]))
but it works for me when using:
(php.withExtensions ({ enabled, all }: enabled ++ [ all.xsl ]))

code is from https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/php.section.md

My problem is composer is not finding xsl, and the error message suggests its not loading the same ini files as cmdline php somehow.

**Comment by drupol** [comment]
Status of this issue ?
