### ISSUE TITLE
some firmware packages timestamped with 1980 in iso_minimal

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#125380]
I tried to reproduce building nixos-minimal-21.05.596.3a2e0c36e79-x86_64-linux.iso .

When I mount the `nix-store.squashfs` inside the `iso`, the contents appear to be the same (nix-hash `99d5f8add79590e77015c51bb7101dac`), but the `nix-store.squashfs` files themselves differ. The first difference seems to be near the start of the file:

```
3,6c3,6
< 00000020  91 16 7e 05 0c 00 00 00  ca e0 b9 26 00 00 00 00  |..~........&....|
< 00000030  c2 e0 b9 26 00 00 00 00  ff ff ff ff ff ff ff ff  |...&............|
< 00000040  ba b8 9d 26 00 00 00 00  b6 c4 a9 26 00 00 00 00  |...&.......&....|
< 00000050  9e 07 b8 26 00 00 00 00  74 dd b9 26 00 00 00 00  |...&....t..&....|
---
> 00000020  91 16 da 05 0c 00 00 00  f2 e0 b9 26 00 00 00 00  |...........&....|
> 00000030  ea e0 b9 26 00 00 00 00  ff ff ff ff ff ff ff ff  |...&............|
> 00000040  ba b8 9d 26 00 00 00 00  12 c5 a9 26 00 00 00 00  |...&.......&....|
> 00000050  12 08 b8 26 00 00 00 00  9c dd b9 26 00 00 00 00  |...&.......&....|
```

I think this is using `mksquashfs` from https://github.com/plougher/squashfs-tools as invoked from `nixos/lib/make-squashfs.nix`, so it should have the fix from #114454, but I haven't double-checked yet.

/cc @plougher

**Comment by raboof** [comment]
Looking at https://dr-emann.github.io/squashfs/ the mismatches in the header are:

* root_inode_ref | u64(InodeRef) | A reference to the inode of the root directory of the archive
* bytes_used | u64 | The number of bytes used by the  archive. Because squashfs archives are often padded to 4KiB, this can  often be less than the file size
* id_table_start | u64 | The byte offset at which the id table starts
* xattr_id_table_start | u64 | The byte offset at which the xattr id table starts

**Comment by baloo** [comment]
```
< 00000020  91 16 7e 05 0c 00 00 00  ca e0 b9 26 00 00 00 00  |..~........&....|
            | root_inode          |  | bytes_used          |
< 00000030  c2 e0 b9 26 00 00 00 00  ff ff ff ff ff ff ff ff  |...&............|
            | id_table_start      |  |xattr_id_table_start |
< 00000040  ba b8 9d 26 00 00 00 00  b6 c4 a9 26 00 00 00 00  |...&.......&....|
            | inode_table_start   |  |directory_table_start|
< 00000050  9e 07 b8 26 00 00 00 00  74 dd b9 26 00 00 00 00  |...&....t..&....|
            | fragment_table_start|  | export_table_start  |
---
> 00000020  91 16 da 05 0c 00 00 00  f2 e0 b9 26 00 00 00 00  |...........&....|
> 00000030  ea e0 b9 26 00 00 00 00  ff ff ff ff ff ff ff ff  |...&............|
> 00000040  ba b8 9d 26 00 00 00 00  12 c5 a9 26 00 00 00 00  |...&.......&....|
> 00000050  12 08 b8 26 00 00 00 00  9c dd b9 26 00 00 00 00  |...&.......&....|
```

Am I reading this wrong?
Would be missing:
 - inode_table_start | u64 | The byte offset at which the inode table starts
 - directory_table_start | u64 | The byte offset at which the directory table starts
 - fragment_table_start | u64 | The byte offset at which the fragment table starts
 - export_table_start | u64 | The byte offset at which the export table starts

So we have changes on:
 - root_inode
 - bytes used
 - id_table_start
 - directory_table_start
 - fragment_table_start
 - export_table_start

**Comment by plougher** [comment]
> ```
> < 00000020  91 16 7e 05 0c 00 00 00  ca e0 b9 26 00 00 00 00  |..~........&....|
>             | root_inode          |  | bytes_used          |
> < 00000030  c2 e0 b9 26 00 00 00 00  ff ff ff ff ff ff ff ff  |...&............|
>             | id_table_start      |  |xattr_id_table_start |
> < 00000040  ba b8 9d 26 00 00 00 00  b6 c4 a9 26 00 00 00 00  |...&.......&....|
>             | inode_table_start   |  |directory_table_start|
> < 00000050  9e 07 b8 26 00 00 00 00  74 dd b9 26 00 00 00 00  |...&....t..&....|
>             | fragment_table_start|  | export_table_start  |
> ---
> > 00000020  91 16 da 05 0c 00 00 00  f2 e0 b9 26 00 00 00 00  |...........&....|
> > 00000030  ea e0 b9 26 00 00 00 00  ff ff ff ff ff ff ff ff  |...&............|
> > 00000040  ba b8 9d 26 00 00 00 00  12 c5 a9 26 00 00 00 00  |...&.......&....|
> > 00000050  12 08 b8 26 00 00 00 00  9c dd b9 26 00 00 00 00  |...&.......&....|
> ```
> 
> Am I reading this wrong?
> Would be missing:
> 
> * inode_table_start | u64 | The byte offset at which the inode table starts
> * directory_table_start | u64 | The byte offset at which the directory table starts
> * fragment_table_start | u64 | The byte offset at which the fragment table starts
> * export_table_start | u64 | The byte offset at which the export table starts
> 
> So we have changes on:
> 
> * root_inode
> * bytes used
> * id_table_start
> * directory_table_start
> * fragment_table_start
> * export_table_start

Most of the above changes in value are probably irrelevant, and bogus.  This is because Squashfs is a compressed metadata filesystem where tables are packed on a byte basis.

Basically, when even only one thing changes, it changes the positions of everything else from that point on.  That in turn will cause differences in compression ratio, which will cause differences again, in a cascading knock-on effect.

The things you *can* tell from the hexdump are this:

1. The inode table start values are the same.  This means the data compressed to exactly the same size (you can tell this because the inode table is placed immediately after the data).   This means it is likely there is no data differences.
2. The directory_table_start in the second image is 92 bytes larger than in the first image.  This means the inode table compressed differently.

Everything from the fragment table start onwards will be different simply because of the inode table size difference.

The obvious question now is, why is the inode table size different?  There are lots of possible reasons.

The most likely reason is the inode table compressed differently because the inode contents *are* different.  Assuming the data hasn't changed, then anything related to where data is stored/size will be the same.   So it is probably file attributes which has changed.  Here it helps to think about what hasn't changed, because *that* hasn't changed in the headers

1. The number of inodes are the same.  This means the one filesystem hasn't hardlinked files, and the other stored them as duplicates.  Because then the inode count would be different.
2. The id (uid/gid) count is the same.  You can probably then rule out ownership changes.

This leaves mode and timestamps for regular files, plus symlink contents changing, device major/minor changes etc.

Basically, if the input to Mksquashfs changes, then it won't be reproducible.

**Comment by raboof** [comment]
For reference, I compared the iso from https://channels.nixos.org/nixos-21.05/latest-nixos-minimal-x86_64-linux.iso (which was [21.05.596.3a2e0c36e79](https://arnout.engelen.eu/nixos-minimal-21.05.596.3a2e0c36e79-x86_64-linux.iso)) to a [self-built one](https://arnout.engelen.eu/built5.iso) from the same commit.

**Comment by raboof** [comment]
> This leaves mode and timestamps for regular files, plus symlink contents changing, device major/minor changes etc.

Indeed looking at the mounted squashfs it seems there are inconsistent timestamps in there. Weird that I didn't see them in `meld` earlier - perhaps they got lost in the [sea of `dangling symlink` warnings](https://gitlab.gnome.org/GNOME/meld/-/issues/585).

All those timestamps seem to be in /nix/store/qcpdgqki4y0mi015dkh4ahgsrfbsf3hs-firmware-linux-nonfree-2021-05-11, /nix/store/srjp3lv3qfand8pwsj8np32yw1q4f7ms-intel2200BGFirmware-3.1 and /nix/store/xmp5w9p9jb4r2nq8sa1wyc33s6ymq198-zd1211-firmware-1.5, see [diffoscope.txt](https://github.com/NixOS/nixpkgs/files/6589714/diffoscope.txt).

These corresponds to `firmwareLinuxNonfree`, `intel2200BGFirmware` and `zd1211-firmware` respectively, though `nix-build --check` doesn't indicate any problems. I'll dig more later today, unless somebody beats me to it ;)

**Comment by raboof** [comment]
So, the iso from hydra has `Modified` timestamps at `1980-01-01 00:00:00 +0000`, while my locally built iso has them at `1970-01-01 00:00:01 +0000`.

You would expect 1970, i.e. as per the last bullet of https://nixos.org/manual/nix/stable/index.html#ssec-derivation). When I look at the filesystem on the machine I built my iso, the timestamp is also `1970-01-01 01:00:01 +0000`, just like on my regular machine (where I strongly suspect it came from the hydra cache).

So the question now is: where did hydra get that 1980 date from for these 3 paths? (it indeed seems unlikely that this was introduced by mksquashfs)

**Comment by raboof** [comment]
@tilpner spotted 1980 happens to be the default SOURCE_DATE_EPOCH in stdenv since bc4927a5263aef5f418e81dc97c23bbf57f23d81 - though that doesn't explain yet how it's ending up as the modified date on those files.

**Comment by raboof** [comment]
zd1211 is timestamped 1980 for the nixos-unstable iso as well, but is correctly 1970 in nixos-20.09 iso's - even recently-built ones :thinking:

**Comment by raboof** [comment]
> zd1211 is timestamped 1980 for the nixos-unstable iso as well, but is correctly 1970 in nixos-20.09 iso's - even recently-built ones thinking

Hmm:

20.09.4244.47e580e291f has 1970, https://hydra.nixos.org/build/126794772 cached from https://hydra.nixos.org/build/79087510
20.09.4351.1fbbf2eda31 has 1980, https://hydra.nixos.org/build/143505001 cached from https://hydra.nixos.org/build/79087510
21.05.1205.b72bde7c4a1 has 1980, https://hydra.nixos.org/build/126794772 cached from https://hydra.nixos.org/build/79087510

so.. cached from the same build, but different date?

**Comment by raboof** [comment]
So, one theory I had was that this might be a problem related to the hydra machine building the squashfs. That doesn't *seem* to be the case, though:

* for 20.09 on 17a455c, 25fe709c.packethost.net [produced](https://hydra.nixos.org/build/144950698/nixlog/18) 1980
* for 20.09 on 6867200, 25fe709c.packethost.net [produced](https://hydra.nixos.org/build/145497290/nixlog/22) 1970
* for 20.09 on 1fbbf2e, a1034eb9.packethost.net [produced](https://hydra.nixos.org/build/146543600/nixlog/22) 1980
* for 20.09 on 59b8d9c, ike.ewi.tudelft.nl [produced](https://hydra.nixos.org/build/146574085/nixlog/92) 1970

**Comment by raboof** [comment]
Even for the GNOME ISO (1205) it's specifically these 3 fixed-output derivations (`firmwareLinuxNonfree`, `intel2200BGFirmware` and `zd1211fw`) that are stuck on 1980 :exploding_head:

**Comment by raboof** [comment]
This hasn't been fully explained, but got fixed due to other changes to those derivations.
