### ISSUE TITLE
flutter: 2.0.3 -> 2.2.1

### ISSUE THREAD

**Issue by NANASHI0X74** [NixOS/nixpkgs#125365]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: flutter
current version: 2.0.3
desired version: 2.2.1

###### Notify maintainers

maintainers: @thiagokokada @ericdallo @babariviere

###### Note for maintainers

Personally I need to upgrade because this release contains a fix for a bug in the localisation codegen that I've run into.

**Comment by NANASHI0X74** [comment]
I've decided I wanna have a go at this myself, but this would be my first major contribution to nixpkgs and I'm not exactly sure how to go about everything, maybe you can help me?
So, I updated the version string and sha256, but a patch fails to apply. So next I tried to do nix-shell -A flutter at the root of my nixpkgs clone. As far as I understand that should drop me into an environment that's supposed to build the package so I can debug it, but instead it just tries to build the package and fails. What do I do next? 😅

**Comment by SCOTT-HAMILTON** [comment]
`nix-shell -A flutter` isn't going to drop you in the build env of flutter. It's going to build flutter and drop you in a shell with flutter available, as if you would have installed it with `nix-env -iA nixpkgs.flutter`. To enter the build env, you probably would use the breakpointHook cf https://discourse.nixos.org/t/debug-a-failed-derivation-with-breakpointhook-and-cntr/8669.

That said, I wouldn't use it to fix the patch. First I would see what the patch does, then I'd check wether it's needed or not. And if needed, I would copy the sources, patch them manually by looking at the broken patch and remake the new patch.

**Comment by NANASHI0X74** [comment]
huh strange, the next comment by jonringer mentions the nix-shell method as
well 😅🤔
but I'll look into that breakpointhook thing

**Comment by ericdallo** [comment]
The patch failed because you need to re apply a patch as the lines or code have changed probably

**Comment by NANASHI0X74** [comment]
yeah sure, I know that's why the patch must have failed. It's just that to fix it, I just naively wanted to mimic how that sort of thing is debugged in this video:
https://youtu.be/5K_2RSjbdXc
which didn't work.
How did you yourself debug the nix expression, @ericdallo? Just manually do the same steps the builder would do?
I guess I'll do that as well, but I just got a new task today that takes priority so will continue in a few days maybe

**Comment by NANASHI0X74** [comment]
what my intuition would tell me is that either I'm not understanding and using nix-shell wrong somehow or the flutter attribute of nixpkgs is a distinct derivation that takes the already built flutter as an input. Might that be  because of the FHSEnv stuff?

**Comment by NANASHI0X74** [comment]
Hey I just figured I could look at the derivation with `nix show-derivation` and confirm what I suspected. So in my case, if I evaluate the pkgs.flutter attribute of my nixpkgs fork in the nix repl, I get this drv: `$DRV=/nix/store/kr5m6l5apvrq7j9igra55wflcayfqvkm-flutter-2.2.1.drv` and if I do `nix show-derivation $DRV` I see that it gets another drv `/nix/store/1wdsrfa2gy74w6wqy8xgknky7aph3fcb-flutter-2.2.1-unwrapped.drv` in its inputDrvs and if I do nix-shell with the latter drv, then I get dropped into the build environment for flutter with unpackPhase and patchPhase etc defined.

Yay, I'm learning stuff ^^

**Comment by NANASHI0X74** [comment]
I actually went and fixed the patches, but now the build fails... apparently dart 2.13 is needed to build flutter now. I'll have to come back to that later, but I opened a draft PR: #125488

**Comment by ericdallo** [comment]
Yes @NANASHI0X74, unfortunately we need to migrate the dart derivation to something similar to how flutter derivation works ATM, using an `mkFlutter` where you can easily build flutter specifying a version. So for now, you need to bump the dart derivation as well

**Comment by ericdallo** [comment]
Actually @NANASHI0X74 it's already possible to override the dart version, you just need to override the version and source params:
```nix
{ callPackage, fetchurl, dart }:
let
  mkFlutter = opts: callPackage (import ./flutter.nix opts) { };
  getPatches = dir:
    let files = builtins.attrNames (builtins.readDir dir);
    in map (f: dir + ("/" + f)) files;
  flutterVersion = "2.2.1";
  dartVersion = "2.13.1";
  channel = "stable";
  filename = "flutter_linux_${flutterVersion}-${channel}.tar.xz";
  dartStable = dart.override {
    version = dartVersion;
    sources = {
      "${dartVersion}-x86_64-darwin" = fetchurl {
        url = "https://storage.googleapis.com/dart-archive/channels/stable/release/${dartVersion}/sdk/dartsdk-macos-x64-release.zip";
        sha256 = "0kb6r2rmp5d0shvgyy37fmykbgww8qaj4f8k79rmqfv5lwa3izya";
      };
      "${dartVersion}-x86_64-linux" = fetchurl {
        url = "https://storage.googleapis.com/dart-archive/channels/stable/release/${dartVersion}/sdk/dartsdk-linux-x64-release.zip";
        sha256 = "0zq8wngyrw01wjc5s6w1vz2jndms09ifiymjjixxby9k41mr6jrq";
      };
      "${dartVersion}-i686-linux" = fetchurl {
        url = "https://storage.googleapis.com/dart-archive/channels/stable/release/${dartVersion}/sdk/dartsdk-linux-ia32-release.zip";
        sha256 = "0zv4q8xv2i08a6izpyhhnil75qhs40m5mgyvjqjsswqkwqdf7lkj";
      };
      "${dartVersion}-aarch64-linux" = fetchurl {
        url = "https://storage.googleapis.com/dart-archive/channels/stable/release/${dartVersion}/sdk/dartsdk-linux-arm64-release.zip";
        sha256 = "0bb9jdmg5p608jmmiqibp13ydiw9avgysxlmljvgsl7wl93j6rgc";
      };
    };
  };
in {
  mkFlutter = mkFlutter;
  stable = mkFlutter {
    version = flutterVersion;
    dart = dartStable;
    pname = "flutter";
    src = fetchurl {
      url =
        "https://storage.googleapis.com/flutter_infra/releases/${channel}/linux/${filename}";
      sha256 = "14a63cpkp78rgymmlrppds69jsrdarg33dr43nb7s61r0xfh9icm";
    };
    patches = getPatches ./patches;
  };
}
```

That should work and remove the need to bump dart derivation everytime we need to bump flutter :)

**Comment by NANASHI0X74** [comment]
Seems to work. why not bump dart though anyway? seems like we might as well

**Comment by ericdallo** [comment]
I'd suggest do that in another PR
