### ISSUE TITLE
Package naming guidelines contradiction

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#12539]
As I was working on #12538 I noticed in the the package naming guidelines:
> - The version part of the name attribute must start with a digit (following a dash) — e.g., "hello-0.3-pre-r3910" instead of "hello-svn-r3910", as the latter would be seen as a package named hello-svn by nix-env.
- If package is fetched from git's commit then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also add "git" to the name - e.g., "pkgname-git-2014-09-23".

**Comment by FRidh** [comment]
cc @jagajaga

**Comment by peti** [comment]
I don't see a contradiction. "The version part of the name attribute must start with a digit" and "the version part of the name must be the date of that (fetched) commit" seems consistent to me.

**Comment by jgillich** [comment]
I think what he means is 

> as the latter would be seen as a package named hello-svn by nix-env

and

> Also add "git" to the name

-> package name `hello-git`

**Comment by FRidh** [comment]
exactly

**Comment by jagajaga** [comment]
There was an idea of git named pkgs, but it seems to be useless until nix
supports git as suffix.

**Comment by peti** [comment]
I still see no contradiction. The second paragraph says to append the string "git" to the *name*. It's not supposed to be part of the version. IMHO, those two paragraphs align perfectly. It's probably misleading, though, that the first paragraph uses the "svn" example in in a way that shouldn't be used, according to the second paragraph. Still, the example is used to illustrate a point about the structure of our package names and version strings; the first paragraph does *not* say "append an svn suffix at the and", which would be a contradiction, indeed.

**Comment by FRidh** [comment]
@peti yes, you are right. `git` would be part of the name instead of the version.

It could be clearer that, in the case of checkouts, we want to have added to the name the type of checkout (git/svn/...) and the version would be a date.

Proposal:

> - The version part of the name attribute must start with a digit (following a dash) — e.g., "hello-0.3.1rc2".
- If a package is fetched from a repository, then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format.  Furthermore, the name part should be appended with the name of the repository type. E.g., "pkgname-git-2014-09-23".

**Comment by FRidh** [comment]
And so the package in #12538 should be named `yakuake-git-2016-01-17`?

**Comment by jagajaga** [comment]
Yes, it should.

**Comment by vcunat** [comment]
I personally believe that it's best to name it `3.0-pre-2016-01-17`, especially in cases where only a single version is provided and/or if you expect to use a released version later (or have used it before).

**Comment by jagajaga** [comment]
Vladimir is right indeed.

**Comment by peti** [comment]
Does anyone want to provide a PR that addresses this issue?

**Comment by FRidh** [comment]
> I personally believe that it's best to name it 3.0-pre-2016-01-17, 

It's not always clear what the next version is going to be. If it is indeed clear what the next version is going to be (e.g. because we use the branch corresponding to that version), then it makes sense to include the version I think.

**Comment by grahamc** [comment]
I think the contradiction is the first bullet indicates it is undesirable to have a packaged named `hello-svn-...` and the second one indicates it is desirable. Am I reading that right?

**Comment by peti** [comment]
The first bullet point doesn't say anything about package names. It talks about version numbers.

**Comment by FRidh** [comment]
> I think the contradiction is the first bullet indicates it is undesirable to have a packaged named hello-svn-... and the second one indicates it is desirable. Am I reading that right?

That is indeed how I read it. Anyway, what is written there is correct, its just in my opinion confusing.

**Comment by grahamc** [comment]
It does, @peti:

> the latter would be seen as a package named hello-svn by nix-env

which in context implies it is unwanted, because the structure of the sentence is giving `the latter would be seen as a package named hello-svn by nix-env` as the reason to not put `svn-` in the version.

**Comment by joachifm** [comment]
@grahamc that's not how I read it: the first stanza clarifies that the `-svn` part is semantically unrelated to the version. That is, you *can't* "put -svn in the version". The second stanza is a recommendation to use the `-git` tag as a method of putting packages built from arbitrary checkouts in a separate namespace.

**Comment by edolstra** [comment]
The second bullet is wrong. A package should never named `foo-git` or `foo-svn` because the version control system used by upstream is an implementation detail irrelevant to downstream users. If the intent is to express that the package is an unstable variant, it should be called `foo-unstable` or something like that.

**Comment by FRidh** [comment]
> The second bullet is wrong. A package should never named foo-git or foo-svn because the version control system used by upstream is an implementation detail irrelevant to downstream users. If the intent is to express that the package is an unstable variant, it should be called foo-unstable or something like that.

I agree. See PR #17331.

**Comment by FRidh** [comment]
`unstable` suffix is used from 25980ed01e505ff20d8678b3dc21682fdff79b52 on.
