### ISSUE TITLE
add terminfo output to foot

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#125390]
**Project description**
The `foot` terminal is already packaged in nixpkgs. As foot uses its own terminfo, this terminfo is needed on any remote servers you connect to using foot. It would be useful to have this terminfo packaged as its own output as with other terminals: alacritty, kitty, rxvt-unicode to name a few.

ping foot maintainer @sternenseemann for feedback 

**Metadata**

* homepage URL: https://codeberg.org/dnkl/foot
* source URL: https://codeberg.org/dnkl/foot
* license: mit
* platforms: linux

**Comment by sternenseemann** [comment]
That is a very good idea! Unfortunately it doesn't seem to be possible to specify a *separate* install directory for foot's terminfo so far (it is installed to `datadir` along with the license etc.). I'll open an upstream ticket, they are usually very helpful, and then we'll be hopefully be able to set this pretty soon.

**Comment by sternenseemann** [comment]
<https://codeberg.org/dnkl/foot/issues/569>
