### ISSUE TITLE
Noisy user profile changes, Use of uninitialized value $prevPriority

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#12541]
Every time my user profile is changing I get these noisy outputs:
```
$ nix-env -e wget
uninstalling ‘wget-1.17.1’
building path(s) ‘/nix/store/lym3m4paws2bk4ljjyzqvmkz1cbl6gv2-user-environment’
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
Use of uninitialized value $prevPriority in numeric eq (==) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 79.
Use of uninitialized value $prevPriority in numeric lt (<) at /nix/store/jjgyvh88yw37gg5ad5lj1z0qdv31d7jy-buildenv.pl line 83.
created 4674 symlinks in user environment
```

This has been going on for a couple of months now, upgrading trough versions. I remember that at some point I set some priorities because of conflicting Gemfile.lock files between packages.

My theory is that I set a priority on a package that doesn't exist anymore. I couldn't find where the list of priorities is stored so that I could flush it.

* Platform: Darwin
* Nix channel: nixpkgs-unstable, nixpkgs-16.03pre75757.4ac1987
* Nix version: "nix-env (Nix) 1.10"

**Comment by zimbatm** [comment]
Am I right to assume that buildenv.pl comes from https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/buildenv/builder.pl ?
If that's the case then my buildenv.pl looks like an old version that's not recognizable. I did `nix-env -u` though.

**Comment by zimbatm** [comment]
It's pretty close to a super old version: https://github.com/NixOS/nixpkgs/blob/349de9bafe2cc3f28b89fe063deedcfd30042266/pkgs/build-support/buildenv/builder.pl
Couldn't find the exact version but it doesn't really matter.

Any ideas how this buildenv.pl got stuck and how to upgrade it ?

**Comment by vcunat** [comment]
> Am I right to assume that buildenv.pl comes from https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/buildenv/builder.pl ?

No, `nix-env` uses its own buildenv.pl (in nix tree). They're forked, or more precisely not much synced but not much different, probably.

**Comment by zimbatm** [comment]
My bad, I didn't know about nix's buildenv.pl.

I just made a diff between nix@1.11.1 buildenv.pl and nixpkgs@nixpkgs-unstable and it's pretty huge actually: https://gist.github.com/zimbatm/19439188a622bf04ab72

**Comment by jraygauthier** [comment]
Looks like #12635

**Comment by zimbatm** [comment]
Thanks
