### ISSUE TITLE
21.05 haskellPackages.range-set-list is broken and breaks proto3-suite and grpc-haskell

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#125484]
On 21.05, the `range-set-list` has this problem:

```
nix-repl> :b pkgs.haskellPackages.range-set-list    
builder for '/nix/store/bxn7kxpqc1s7bd7qm0fpiwvcv68g2d0d-range-set-list-0.1.3.1.drv' failed with exit code 1; last 10 log lines:
    $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.1.0:Distribution.Simple.Configure
    configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.1.0:Distribution.Simple.Configure
    configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.1.0:Distribution.Simple
    confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.1.0:Distribution.Simple.UserHooks
    configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.1.0:Distribution.Simple
    defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.1.0:Distribution.Simple
    defaultMain, called at Setup.hs:2:8 in main:Main
  Setup: Encountered missing or private dependencies:
  tasty >=0.8 && <1.4
[0 built (1 failed), 12 copied (15.9 MiB), 1.3 MiB DL]
error: build of '/nix/store/bxn7kxpqc1s7bd7qm0fpiwvcv68g2d0d-range-set-list-0.1.3.1.drv' failed

nix-repl> pkgs.haskellPackages.tasty.version
"1.4.1"
```

This is just a dependency constraint problem: https://github.com/phadej/range-set-list/issues/21

Can someone show me how to quickly override the cabal file in the derivation so that way we can loosen the dependency requriements? I find this happening often with haskell packages.

**Comment by sternenseemann** [comment]
We have a hack for this in nixpkgs: `haskell.lib.doJailbreak drv` removes all version constraints for a given package. You can also add such calls to our configuration overlays for `haskellPackages` (e. g. `pkgs/development/haskell-modules/configuration-common.nix`) via a PR if you want to fix it upstream.

One caveat is that this doesn't work for conditional dependencies which are hidden behind a cabal flag.

**Comment by sternenseemann** [comment]
21.05 is EOL. The package (`range-set-list`) is working in current nixpkgs `master` at the very least (and will probably be working in the upcoming release 22.05).
