### ISSUE TITLE
Suggestion: tag all channel releases in nixpkgs-channels repo (example: nixos-unstable-20160122-1505)

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#12548]
It would be great if hydra could `git tag` channel releases in the `nixpkgs-channels` repo as `nixos-unstable-YYYYMMDD-HHMM`.

Pros:
- Would make it possible to check out old channel releases (maybe while bisecting for a bug) without having to rebuild the world when, just a few commits away, all the binaries are in the cache. As far as I'm aware there is no way to find old commit ids for which channels were released

Cons:
- Can't see any other than it requires a little bit of work?

I'm happy to do the work if someone who understands what needs to be done provides guidance. 

Also it would be great if we backpopulate said tags for past channel releases provided the required information still exists (maybe with some log grepping?)

Thoughts/comments?

cc // @FRidh @domenkozar @cillianderoiste @matthiasbeyer

**_EDITED:**_ originally suggested tagging directly in `nixpkgs` rather than `nixpkgs-channels`

**Comment by vcunat** [comment]
It would be more suitable in the nixpkgs-channels repo. That one also already does make it easy to work with the latest channel releases.

**Comment by obadz** [comment]
@vcunat, what's the advantage of having a separate repo for `nixpkgs-channels`?

**Comment by vcunat** [comment]
We've discussed it somewhere already about the time it was created. IIRC mainly: various noise-reduction side effects and making it read-only.

**Comment by vcunat** [comment]
With tags on every channel update it would be vital &ndash; I really wouldn't want to have thousands of tags in the usual work repo.

**Comment by matthiasbeyer** [comment]
:+1:

**Comment by obadz** [comment]
Not sure I see why having 1000s of tags is an issue but I get the readonly part. Using `nixpkgs-channels` seems reasonable. Will edit the original post.

(It follows that there's no point having a `nixos-unstable-latest` tag since that's what the `nixos-unstable` branch is already doing)

**Comment by vcunat** [comment]
> (It follows that there's no point having a nixos-unstable-latest tag since that's what the nixos-unstable branch is already doing)

BTW note that git (command behavior) half-assumes that tags never move.

**Comment by edolstra** [comment]
Note that old channel releases do get deleted, and cache.nixos.org does get GC'ed every once in a while, so it's not the case that all these tags would have binaries in the cache.

The Git revisions for channel releases are available in the git-revision directory of each release, e.g. https://nixos.org/releases/nixos/15.09/nixos-15.09.660.ca8f159/git-revision. And of course the short rev is part of the release name.

**Comment by obadz** [comment]
@vcunat,

> BTW note that git (command behavior) half-assumes that tags never move.

Right, that's why it makes sense to have `nixos-unstable` be a branch and `nixos-unstable-YYYYMMDD-HHMM` be an immutable tag.

**Comment by obadz** [comment]
@edolstra,

> .. and cache.nixos.org does get GC'ed

I heard somewhere that so far this had not happened so old versions are still available?

> The Git revisions for channel releases are available in the git-revision directory of each release

For unstable (https://nixos.org/releases/nixos/unstable/) it seems to go back a handful of releases (and then there are older releases in there but I'm not sure how they were selected?)

For releases that have been garbage collected, would it be useful to rename the tag from `nixos-unstable-XYZ` to `nixos-unstable-XYZ-deleted` this way we still have a record of the commit id but it's clear that it's not longer in the cache?

**Comment by obadz** [comment]
So do you guys think we should move forward with this?

**Comment by vcunat** [comment]
I would prefer a different solution than tags. The branches could be created like one merge commit per channel release (--no-ff).  The date of the merge would be the date of the channel release, so we could use references like `nixos-unstable@{1 month 2 weeks 3 days 1 hour 1 second ago}` (see `man gitrevisions`).

**Comment by obadz** [comment]
@vcunat, would you be able to git log and only see the channel releases?

**Comment by matthiasbeyer** [comment]
@obadz As far as I can understand this this would be as easy as `git log nixos-unstable --merges`. @vcunat am I right?

**Comment by obadz** [comment]
@matthiasbeyer / @vcunat, wouldn't you see all merges into `master` as well?

**Comment by vcunat** [comment]
`git log --first-parent` I personally use that option very often anyway (inside an alias).

**Comment by obadz** [comment]
@vcunat, I learned something today. I think this would be fine.

Any ideas where the best place to start implementation is?

**Comment by vcunat** [comment]
In your place I would first wait for agreement that [such a change](https://github.com/NixOS/nixpkgs/issues/12548#issuecomment-177835508) would get deployed, at least in principle. IIRC there are only a couple of people with access to this, maybe just @edolstra and @rbvermaa.

**Comment by edolstra** [comment]
I wonder if `git notes` could be used for this. It allows attaching arbitrary metadata to a commit (like "this commit is a channel release") without changing the commit itself. Then you could enumerate the channel releases by doing something like `git log --grep is-channel-release`.

The downside to @vcunat's idea (if I understand it correctly) is that the channel branches wouldn't correspond exactly to their source branches in the `nixpkgs` repo anymore, since they would have a bunch of merge commits for every channel update. Not sure if that might cause problems (e.g. with rebasing).

Updating the `nixos-channels` repo is done from this script: https://github.com/NixOS/nixos-channel-scripts/blob/master/mirror-nixos-branch.sh#L123

**Comment by vcunat** [comment]
> The downside...

I see. Just checking `git co some-channel-commit` would no longer work as an alias. I can't see any potential with problems, even with rebasing against the channel branches, but it's possible there is some hidden catch.

**Comment by matthiasbeyer** [comment]
I'd vote for non-annotated tags over notes.

**Comment by obadz** [comment]
I think all three solutions (tags/notes/merges) are acceptable. I vote for tags because it's simplest and most commonly used for this kind of purpose. We could also do tags + notes?

**Comment by obadz** [comment]
bump

**Comment by Profpatsch** [comment]
I’m closing because the issue stalled; feel free to reopen.

**Comment by Profpatsch** [comment]
I’m closing because the issue stalled; feel free to reopen.

**Comment by xaverdh** [comment]
This looks like a useful feature, just had some trouble finding the nixpkgs-channels commit from which my system was built..

**Comment by Profpatsch** [comment]
@xaverdh somebody mentioned that `nixpkgs-channels` has been merged into `nixpkgs`, so maybe there’s a solution now.
