### ISSUE TITLE
My build expression for pandoc 1.16.0.2 doesn't work on release-15.09

### ISSUE THREAD

**Issue by vmandela** [NixOS/nixpkgs#12547]
Hi,

I am trying to install pandoc 1.16.0.2 from nixpkgs on ubuntu 12.04 and faced build failures. Below are the channels I have setup

stable https://nixos.org/channels/nixos-15.09
nixpkgs https://nixos.org/channels/nixpkgs-unstable

After overriding the  version numbers used for pandoc-types and cmark, I was able to get the compilation done but the tests fail with the below error. 

~~~
$ nix-shell '<nixpkgs>' -A haskellPackages.pandoc
[nix-shell:/tmp]$ genericBuild
...
/tmp/pandoc/dist/build/pandoc/pandoc: error while loading shared libraries: libHSpandoc-1.16.0.2-EINNBloJvOm7LsGav5qaxx-ghc7.10.3.so: cannot open shared object file: No such file or directory
~~~
 
My configuration files are below. Could you please provide pointers on solving this issue?
Thanks and Regards,
Venkat

`.nixpkgs/config.nix`
~~~
{
  packageOverrides = super: let self = super.pkgs; in
  {
     haskellPackages = super.recurseIntoAttrs(super.haskellPackages.override{
        overrides = self: super:
        let callPackage = self.callPackage; in {
            diagrams-pandoc = callPackage ./local/diagrams-pandoc.nix {};
            hakyll-diagrams = callPackage ./local/hakyll-diagrams.nix {};
            pandoc-csv2table = callPackage ./local/pandoc-csv2table.nix {};
	    pandoc-types = self.pandoc-types_1_16;
	    cmark = self.cmark_0_5_0;
	    pandoc = (callPackage ./local/pandoc.nix {}).overrideDerivation (
		oldAttrs: {
		postUnPack = ''git submodule update --init'';
		}
	    );
        };
       });
  };

 allowUnfree = true;
}
~~~

`.nixpkgs/local/pandoc.nix`

~~~
{ mkDerivation, aeson, ansi-terminal, array, base
, base64-bytestring, binary, blaze-html, blaze-markup, bytestring
, cmark, containers, data-default, deepseq, Diff, directory
, executable-path, extensible-exceptions, filemanip, filepath
, ghc-prim, haddock-library, highlighting-kate, hslua, HTTP
, http-client, http-client-tls, http-types, HUnit, JuicyPixels, mtl
, network, network-uri, old-time, pandoc-types, parsec, process
, QuickCheck, random, scientific, SHA, stdenv, syb, tagsoup
, temporary, test-framework, test-framework-hunit
, test-framework-quickcheck2, texmath, text, time
, unordered-containers, vector, xml, yaml, zip-archive, zlib
}:
mkDerivation {
  pname = "pandoc";
  version = "1.16.0.2";
  src = /home/vmandela/p-code/pandoc;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson array base base64-bytestring binary blaze-html blaze-markup
    bytestring cmark containers data-default deepseq directory
    extensible-exceptions filemanip filepath ghc-prim haddock-library
    highlighting-kate hslua HTTP http-client http-client-tls http-types
    JuicyPixels mtl network network-uri old-time pandoc-types parsec
    process random scientific SHA syb tagsoup temporary texmath text
    time unordered-containers vector xml yaml zip-archive zlib
  ];
  executableHaskellDepends = [
    aeson base bytestring containers directory extensible-exceptions
    filepath highlighting-kate HTTP network network-uri pandoc-types
    text yaml
  ];
  testHaskellDepends = [
    ansi-terminal base bytestring containers Diff directory
    executable-path filepath highlighting-kate HUnit pandoc-types
    process QuickCheck syb test-framework test-framework-hunit
    test-framework-quickcheck2 text zip-archive
  ];
  homepage = "http://pandoc.org";
  description = "Conversion between markup formats";
  license = "GPL";
}
~~~

**Comment by peti** [comment]
This bug report is somewhat misleading. When you say that you are

> trying to install pandoc 1.16.0.2 from nixpkgs

you really mean that you have create a build yourself for a package that is, in fact, *not* part of Nixpkgs.

**Comment by vmandela** [comment]
I did start with pandoc 1.16 from nixpkgs. The compilation fails as incorrect versions of pandoc-types and cmark are picked up.

nix-env -iA nixpkgs.haskellPackages.pandoc_1_16

~~~
src/Text/Pandoc/Shared.hs:385:22:
    Not in scope: data constructor SoftBreak
~~~

regards,
Venkat

embed_data_files=False
Dependency Diff -any: using Diff-0.3.2
Dependency HTTP -any: using HTTP-4000.2.23
Dependency HUnit -any: using HUnit-1.3.0.0
Dependency JuicyPixels -any: using JuicyPixels-3.2.6.4
Dependency QuickCheck -any: using QuickCheck-2.8.1
Dependency SHA -any: using SHA-1.6.4.2
Dependency aeson -any: using aeson-0.10.0.0
Dependency ansi-terminal -any: using ansi-terminal-0.6.2.3
Dependency array -any: using array-0.5.1.0
Dependency base -any: using base-4.8.2.0
Dependency base64-bytestring -any: using base64-bytestring-1.0.0.1
Dependency binary -any: using binary-0.7.5.0
Dependency blaze-html -any: using blaze-html-0.8.1.1
Dependency blaze-markup -any: using blaze-markup-0.7.0.3
Dependency bytestring -any: using bytestring-0.10.6.0
Dependency cmark -any: using cmark-0.4.1
Dependency containers -any: using containers-0.5.6.2
Dependency data-default -any: using data-default-0.5.3
Dependency deepseq-generics -any: using deepseq-generics-0.1.1.2
Dependency directory -any: using directory-1.2.2.0
Dependency executable-path -any: using executable-path-0.0.3
Dependency extensible-exceptions -any: using extensible-exceptions-0.1.1.4
Dependency filemanip -any: using filemanip-0.3.6.3
Dependency filepath -any: using filepath-1.4.0.0
Dependency ghc-prim -any: using ghc-prim-0.4.0.0
Dependency haddock-library -any: using haddock-library-1.2.1
Dependency highlighting-kate -any: using highlighting-kate-0.6.1
Dependency hslua -any: using hslua-0.4.1
Dependency http-client >=0.3.2 && <0.5: using http-client-0.4.26.2
Dependency http-client-tls ==0.2.*: using http-client-tls-0.2.2
Dependency http-types >=0.8 && <0.10: using http-types-0.9
Dependency mtl -any: using mtl-2.2.1
Dependency network >=2.6: using network-2.6.2.1
Dependency network-uri ==2.6.*: using network-uri-2.6.0.3
Dependency old-time -any: using old-time-1.1.0.3
Dependency pandoc -any: using pandoc-1.16
Dependency pandoc-types -any: using pandoc-types-1.12.4.7
Dependency parsec -any: using parsec-3.1.9
Dependency process -any: using process-1.2.3.0
Dependency random -any: using random-1.1
Dependency scientific -any: using scientific-0.3.4.4
Dependency syb -any: using syb-0.6
Dependency tagsoup -any: using tagsoup-0.13.6
Dependency temporary -any: using temporary-1.2.0.3
Dependency test-framework -any: using test-framework-0.8.1.1
Dependency test-framework-hunit -any: using test-framework-hunit-0.3.0.2
Dependency test-framework-quickcheck2 -any: using
test-framework-quickcheck2-0.3.0.3
Dependency texmath -any: using texmath-0.8.4.1
Dependency text -any: using text-1.2.2.0
Dependency time ==1.5.*: using time-1.5.0.1
Dependency unordered-containers -any: using unordered-containers-0.2.5.1
Dependency vector -any: using vector-0.11.0.0
Dependency xml -any: using xml-1.3.14
Dependency yaml -any: using yaml-0.8.15.2
Dependency zip-archive -any: using zip-archive-0.2.3.7
Dependency zlib -any: using zlib-0.6.1.1

**Comment by vmandela** [comment]
I am able to compile pandoc_1_16_0_2 after calling overrideCabal on the package as is done for the default pandoc package. Below is the build expression I ended up with. Please close this issue.

Thanks and regards,
Venkat

`shell.nix`
~~~
{ nixpkgs ? import <nixpkgs> {}, compiler ? "default" }:
let
  inherit (nixpkgs) pkgs;
  haskellPackages = pkgs.recurseIntoAttrs(pkgs.haskellPackages.override {
    overrides = self: super:
	let callPackage = self.callPackage; in {
	    thisPackage = callPackage  ./default.nix {};
	    pandoc = pkgs.haskell.lib.overrideCabal (pkgs.haskellPackages.pandoc_1_16_0_2.override {
          pandoc-types = haskellPackages.pandoc-types_1_16_0_1;
          cmark = haskellPackages.cmark_0_5_0;
	  texmath = haskellPackages.texmath;
      }) (drv: {
          configureFlags = drv.configureFlags or [] ++ ["-fembed_data_files"];
          buildTools = drv.buildTools or [] ++ [self.hsb2hs];
          enableSharedExecutables = false;
          enableSharedLibraries = false;
          isLibrary = false;
          doHaddock = false;
          postFixup = "rm -rf $out/lib $out/nix-support $out/share";
      });
      texmath = pkgs.haskellPackages.texmath.override {
          pandoc-types = haskellPackages.pandoc-types_1_16_0_1;
	};
	};
});
in haskellPackages.thisPackage.env
~~~

`default.nix`
~~~
{ mkDerivation, base, pandoc, stdenv, texmath }:
mkDerivation {
  pname = "pandoc-compile";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [ base pandoc texmath ];
  license = stdenv.lib.licenses.unfree;
}
~~~
