### ISSUE TITLE
nixos: create `doc` option-set

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#12542]
I propose to create nixos option-set `doc` or `documentation` if you want it longer. What I think should be put there:
- `doc.nixosManual`, moved from `services.`. I don't consider the tty service to be the primary function, moreover it's disabled by default. The option provides the manual in `systemPackages`, `nixos-help` command, etc.
- `doc.man`, moved from `programs.*`. The option also affects linking manual pages into the system path.
- `doc.info` could be created, analogical to `doc.man`. Also some option(s) to link the other kinds of docs could be created.
- Maybe I've missed something?

Of course, there would be corresponding shuffle of `<nixpkgs/nixos/**.nix>` files to `<nixpkgs/nixos/modules/doc/*>`, perhaps also including `misc/meta.nix`. Any thoughts? Related: #11499 and linked issues.

I planned to implement this myself, but first I'd like to have some confidence that such a change would be accepted in principle.

**Comment by globin** [comment]
:+1:

**Comment by gleber** [comment]
There seem to have been very little uptake for this proposal so far. Do you think it should be closed or the question should be asked again?

**Comment by vcunat** [comment]
Well, just us mentioning it now makes it appear on top again, similarly to asking again.  In close future, I expect to still be quite busy with nixpkgs stuff that get more interest...

**Comment by oxij** [comment]
#38114 does most of this.

**Comment by oxij** [comment]
And #46193 does the rest.

**Comment by samueldr** [comment]
@vcunat please check both PRs fully implemented your idea.

**Comment by vcunat** [comment]
Yes, it seems so.
