### ISSUE TITLE
Can't use `init.vim` with neovim

### ISSUE THREAD

**Issue by ursi** [NixOS/nixpkgs#125423]
@teto With this change, I am no longer able to configure my neovim with my `init.vim`. I tried using `nevom.override { wrapRc = false; }` but it doesn't work because, well, when you look at `all-packages.nix`, `neovim` actually doesn't use the wrapper in this file - or so it seems. But somehow it does use it. If I build neovim changing that default to `false`, then I can use my normal `init.vim` config again. I tried using `wrapNeovimUnstable` manually but it kept breaking so I gave up and just built my system on the commit before the one that introduced this argument. Can you help me figure out what's going on? thanks
https://github.com/NixOS/nixpkgs/blob/6933d068c5d2fcff398e802f7c4e271bbdab6705/pkgs/applications/editors/neovim/wrapper.nix#L29

**Comment by austinbutler** [comment]
Does it work if you use this commit? https://github.com/NixOS/nixpkgs/pull/124785

**Comment by ursi** [comment]
@austinbutler yes, thanks!
