### ISSUE TITLE
earthly is missing some compile time flags

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#125463]
**Describe the bug**

1. `earthly --verrsion` prints some information that misses the actual version
2. `earhly +$target` can't do anything as it doesn't know what buildkit image to use

**Expected behavior**

1. The version is properly printed
2. `earthly` knows the default image

**Additional context**

earthly/earthly#1025

**Notify maintainers**

@Mdsp9070
@kalbasit

**Metadata**

```plain
$ nix-shell -p nix-info --run "nix-info -m" -I nixpkgs=channel:nixos-unstable
 - system: `0`
 - host os: `Linux 5.4.119, NixOS, 20.09.20210530.eae0cab (Nightingale)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210531_e8f585b`
 - channels(root): `""`
 - channels(aroemer): `"nixpkgs-20.09.4025.dc326c78a93"`
 - channels(nmelzer): `""`
 - nixpkgs: `0`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- earthly
```

**Comment by Artturin** [comment]
trying to add them now :)

**Comment by NobbZ** [comment]
Do you mind mentioning me in the PR? Sadly GitHub doesn't notify me about mentions of my tickets :(

**Comment by Artturin** [comment]
okay i will when i make it
