### ISSUE TITLE
nix-collect-garbage -d -> No space left on device

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#12559]
how can we help users in this case?

```
$ nix-collect-garbage -d
removing old generations of profile /nix/var/nix/profiles/per-user/davidak/channels
terminate called after throwing an instance of 'nix::SysError'
  what():  writing to file: No space left on device
Aborted
```

- catch this error and output a more helpful message, suggest to delete files manually (for example from /tmp)
- reduce file size that `nix-collect-garbage -d` has to write (i had 2,5 MB free and still got this)
- reserve some free space in NixOS for critical tasks like this?

**Comment by heydojo** [comment]
```
catch this error and output a more helpful message, suggest to delete files manually (for example from /tmp)
```
https://nixos.org/nixos/options.html
boot.tmpOnTmpfs
It should really be a default. I think most people are using that option and it also creates a positive side effect in that you do not have to clean /tmp. A shutdown or reboot will do it for you.

```
reduce file size that nix-collect-garbage -d has to write (i had 2,5 MB free and still got this)
```
If you mean 2.5MB, you really need a bigger disc more than you need this fixed.

```
catch this error and output a more helpful message, suggest to delete files manually (for example from /tmp)
```
I think the message is pretty clear.

```
reserve some free space in NixOS for critical tasks like this?
```
The expectation is that you install onto a partition of a sensible size. With 500GB drives being the minimum size shipped with personal computers since quite a while, having enough space to install NixOS is a non-issue. Unless of course you are installing as many operating systems as you can on to a physical hard disc. In which case; try hardware virtualisation instead.

Once NixOS is installed, the tendency is to use nix.gc.automatic and forget about garbage collection unless you have a reason not to, such as testing your changes against the unstable branch.

**Comment by davidak** [comment]
yes, desktop users should have a big hard drive and servers should have monitoring.

i have a 20 GB test vm completely full with nix store, generations and nox-review builds... and about 200MB test files.
the problem here is that i can't clean up the NixOS system if `nix-collect-garbage` don't work anymore.
in that case it would be good if it can delete things without needing to write anything.

**Comment by vcunat** [comment]
On some filesystems even deleting often requires allocating additional space (COW). I've had such a story with btrfs.

**Comment by heydojo** [comment]
20GB is far too small for a modern OS with full xorg stack imho.
Considering the fact that Nixos can create a huge amount of generations over time if auto garbage collection is not run, at least double 20GB is the minimum I would recommend by default.
Probably 100GB is a safer number.

Your comment does raise the issue that the minimum recommended specs for NixOS are not on the download page of the main website though.

**Comment by vcunat** [comment]
The disk usage is rather case-by-case. Unlike other distros, we don't really have a "default desktop configuration.nix" or something like that. We could post some examples of disk requirements, though. We do have the up-to-date data on Hydra:
- KDE: http://hydra.nixos.org/job/nixos/release-15.09/nixos.closures.kde.x86_64-linux/latest#tabs-details
- Xfce: http://hydra.nixos.org/job/nixos/release-15.09/nixos.closures.xfce.x86_64-linux/latest#tabs-details

IMO 20 GB *is* enough if one doesn't keep many generations but that depends on personal preference. (I personally use ~115 GB partition for /nix even while I test mass-rebuild changes and keep some old generations.)

**Comment by wmertens** [comment]
I use NixOS for servers and 20GB is plenty. I don't install Xorg of course,
and I do run nix-collect-garbage often :)

On Sat, Jan 23, 2016 at 11:23 AM Vladimír Čunát <notifications@github.com>
wrote:

> The disk usage is rather case-by-case. Unlike other distros, we don't
> really have a "default desktop configuration.nix" or something like that.
> We could post some examples of disk requirements, though. We do have the
> up-to-date data on Hydra:
>
>    - KDE:
>    http://hydra.nixos.org/job/nixos/release-15.09/nixos.closures.kde.x86_64-linux/latest#tabs-details
>    - Xfce:
>    http://hydra.nixos.org/job/nixos/release-15.09/nixos.closures.xfce.x86_64-linux/latest#tabs-details
>
> IMO 20 GB *is* enough if one doesn't keep many generations but that
> depends on personal preference. (I personally use ~115 GB partition for
> /nix even while I test mass-rebuild changes and keep some old generations.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixpkgs/issues/12559#issuecomment-174168696>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nix/issues/564
