### ISSUE TITLE
[21.05] tdesktop: 2.7.4 -> 2.7.6 required to remove a segfault on voice message recording

### ISSUE THREAD

**Issue by Keij0** [NixOS/nixpkgs#125533]
**Describe the bug**
After updating from 20.09 to 21.05, tdesktop got bumped from 2.4.4 to 2.7.4, which segfaults while trying to record voice messages, currently unstable only has 2.7.4 as well, I guess a bump to 2.7.6 is required to fix the issue as per [https://github.com/telegramdesktop/tdesktop/issues/16365](https://github.com/telegramdesktop/tdesktop/issues/16365)

**To Reproduce**
1. Try to record a voice message
2. the application will hang
3. and segfault afterwards, generating a coredump visible from coredumpctl

**Expected behavior**
A voice message should start recording

**Screenshots**
![photo_2021-06-03_18-49-46](https://user-images.githubusercontent.com/20029608/120682283-93e2f900-c49c-11eb-87da-b87865ced0f4.jpg)

**Additional context**

**Notify maintainers**
@udf 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.641.5237039cc1e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.641.5237039cc1e"`
 - channels(patjaw): `"nixos-unstable-21.05pre288911.65d6153aec8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: tdesktop
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
the linked issue doesn't make any sense to me:
> distribution package only bug, they need to update to telegram desktop 2.7.6 source

How is a distribution issue, when the fix is in the source ?

**Comment by jonringer** [comment]
Also, there is no 2.7.6 https://github.com/telegramdesktop/tdesktop/releases

**Comment by Keij0** [comment]
Sorry, the issue from telegram's bug tracker mentioned 2.7.6, I didn't check versioning properly, also 2.7.5 is marked as pre-release at this point on their releases page, this bug just didn't exist with 2.4.4 and the original bug tracker seems to ignore bugs coming from things packaged by distros

**Comment by jonringer** [comment]
according to the 2.7.5 release notes, they fixed several crashes. Probably still in a better state than 2.7.4
