### ISSUE TITLE
networking.nameservers should specify exactly what goes into resolve.conf

### ISSUE THREAD

**Issue by nfjinjing** [NixOS/nixpkgs#12550]
Current implementation appends name servers into resolve.conf, this leaves a machine vulnerable to DNS poisoning as servers pushed from an ISP are also being consulted.

**Comment by wkennington** [comment]
You might want both though. You can disable this in your dhcp client

**Comment by nfjinjing** [comment]
I found an `overrideNameservers` option in network-manager service, but strangely can't not set it. No comparable configuration in wpa_supplicant. Not quite sure how to do it with DHCP client :)

As the name suggests, I would still suggest that the default behavior should be to overwrite the name servers as users who actually care about specifying their own name servers probably don't want the ones from the DHCP server.

**Comment by edolstra** [comment]
I'm horrified to see the existence of `overrideNameserversScript`, another piece of code that clobbers `/etc/resolv.conf` directly instead of going through `resolvconf`...

**Comment by nfjinjing** [comment]
Specifying the name server in dhcpcd statically seems to fix it:

    networking.dhcpcd.extraConfig = "static domain_name_servers=127.0.0.1"

I'm not sure if this is the right way, should this be documented in the manual?

**Comment by nfjinjing** [comment]
This also works:

    networking.dhcpcd.extraConfig = "nooption domain_name_servers";

**Comment by nfjinjing** [comment]
I just found the same effect can be had by using `dnsmasq` :D

    services.dnsmasq.enable = true;
    services.dnsmasq.servers = [ " ... " ]
