### ISSUE TITLE
KDE Shortcuts failed to find desktop file due to wrong letter cases

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#125592]
**Describe the bug**

I have `alacritty` installed through [home-manager](https://github.com/nix-community/home-manager). It works well in KDE application launcher.
But when adding keyboard shortcuts in `System Settings - Shortcuts - Add Application` and select `Alacritty`, it shows no desktop actions (A `New Terminal` action is defined in desktop file) in the right-hand-side panel, only a `_launch` is shown. Shortcut can be set, but doesn't work at all.

When selected `Alacritty` from `Add Application` popup window and press `OK` button. An error is produced in `journalctl`.
```
Jun 04 07:49:35 invar kglobalaccel5[2299]: kf.globalaccel.kglobalacceld: No desktop file found for service "alacritty.desktop"
```
Note that it is lowercase `alacritty.desktop` instead of the real file `Alacritty.desktop`. But in Shortcut Settings, it is shown as `Alacritty` everywhere. It seems something went wrong.

When hitting the shortcut. It produces some errors, and does nothing.
```
Jun 04 08:19:11 invar org.kde.ksystemstats[91501]: Could not open library 'libkdeinit5_'.
Jun 04 08:19:11 invar org.kde.ksystemstats[91501]: Cannot load library /run/current-system/sw/lib/libkdeinit5_: (/run/current-system/sw/lib/haswell/liblibkdeinit5_.so: cannot open shared object file: No such file or directory)
```

The issue can be workaround-ed by creating a lowercase desktop file with (almost) the same content.
```nix
pkgs.runCommand "alacritty-desktop" {} ''
    mkdir -p $out/share/applications
    cp ${pkgs.alacritty}/share/applications/Alacritty.desktop $out/share/applications/alacritty.desktop
    sed 's/Name=Alacritty/Name=alacritty/g' --in-place $out/share/applications/alacritty.desktop
''
```

**To Reproduce**
1. In `home-manager`, set `programs.alacritty.enable = true;`.
2. `System Settings - Shortcuts - Add Application`, click `Alacritty` to add.
3. Desktop actions are missing. Setting shortcut doesn't work.

**Expected behavior**
Shortcuts work like the workaround above.

**Screenshots**

Current behavior: desktop actions are missing. Shortcut can be set but never works.
![image](https://user-images.githubusercontent.com/14816024/120727318-cdebe380-c50c-11eb-8c98-7276da2da32d.png)

With workaround above: desktop actions are available. Shortcut works.

![image](https://user-images.githubusercontent.com/14816024/120727883-3ab3ad80-c50e-11eb-9b68-ddaf68133524.png)

**Additional context**

**Notify maintainers**

@ttuegel  @turion @NixOS/qt-kde

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.11.20210601.1c2986b (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(root): `"nixos-21.03pre257339.83cbad92d73"`
 - channels(oxa): `"home-manager"`
 - nixpkgs: `/nix/store/ypgnj9x286v31wf3061j60vqmyq7pc45-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by turion** [comment]
Maybe you meant to ping the alacritty maintainers? I've barely ever used this program.

**Comment by oxalica** [comment]
Ping alacritty maintainers: @Br1ght0ne @mic92 @cole-h @ma27

@turion 
Well, I checked the desktop file using `desktop-file-validate` and took a glance manually. It is quite valid. I think the issue is on KDE side.

**Comment by turion** [comment]
Isn't the bug then that the file `Alacritty.desktop` is packaged incorrectly? I.e. it should be renamed to lower case before copying to `$out/share/applications`? See https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/terminal-emulators/alacritty/default.nix#L101

Or where exactly do you see the bug?

**Comment by oxalica** [comment]
@turion 

I checked https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys, section `File naming`, the only content related to letter cases is this:

> The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. 

Note that it is `SHOULD` but not `MUST`. Seems file name starting with upper case is not encouraged, but not quite an error.
I'll submit a PR to rename it. But I still don't think KDE's current behavior is "correct".

**Comment by turion** [comment]
Is it then actually an upstream bug because KDE doesn't correctly recognise the file?

**Comment by oxalica** [comment]
> Is it then actually an upstream bug because KDE doesn't correctly recognise the file?

I asked a friend on Arch Linux, and the same issue exists. So I think, yes.

BTW: The desktop file is initially in lowercase, and capitalized after the discussion https://github.com/alacritty/alacritty/pull/3425
So I assume that renaming it will run into some wayland issues.

**Comment by turion** [comment]
Ok, then probably the best course of actions is to report upstream, link that issue here, and close this issue here until we know more. If they won't fix it, we could maybe add a workaround, but it's better if it's fixed upstream and we don't have to burden nixpkgs with workarounds.

**Comment by oxalica** [comment]
Upstream issue: https://bugs.kde.org/show_bug.cgi?id=438204
Close since it's not a packaging issue.
