### ISSUE TITLE
Can not gpg-sign git commits as git doesn't find `gpg`

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#12551]
Whenever I use GPG, I use `gpg2` on the commandline. I have to do this with `gpg21` _and_ `gpg` installed. git does not find the `gpg` command and therefor I cannot sign my commits.

```bash
$ git commit a -S<my GPG signing-key ID>
error: cannot run gpg: No such file or directory
error: konnte gpg nicht ausführen
fatal: Fehler beim Schreiben des Commit-Objektes.
```

**Comment by fpletz** [comment]
There is a package called `gnupg1compat` that adds backwards-compatible symlinks for the regular `gnupg` package which is currently `gnupg20`.

**Comment by matthiasbeyer** [comment]
And it does not work:

```bash
$gpg --list-keys mail@beyermatthias.de
gpg: error reading key: No public key
```

**Comment by globin** [comment]
Cannot reproduce this, can you paste the output of:
```
gpg --list-keys mail@beyermatthias.de
```

**Comment by matthiasbeyer** [comment]
I did that exactly one comment above yours, but well, here we go again:

```bash
$ nix-shell -p gnupg1compat
$ gpg --list-keys mail@beyermatthias.de
gpg: error reading key: Kein öffentlicher Schlüssel
```

With english locale:

```bash
$ gpg --list-keys mail@beyermatthias.de
gpg: error reading key: No public key
```

---

Without `gnupg1compat`:

```bash
$ gpg --list-keys mail@beyermatthias.de
The program ‘gpg’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.gnupg1
  nix-env -iA nixos.gnupg1orig
```

**Comment by globin** [comment]
Sorry I meant `gpg2`

**Comment by matthiasbeyer** [comment]
```bash
$ gpg2 --list-keys mail@beyermatthias.de
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
pub   rsa4096/20CA0F94 2013-07-11
uid      [  ultimativ] Matthias Beyer (Key für mail@beyermatthias.de) <mail@beyermatthias.de>
sub   rsa4096/8BD3FCD1 2013-07-11
sub   rsa4096/7ED56B25 2016-01-22
```

**Comment by globin** [comment]
robin@graffel [07:18:10] [~/dev/nixpkgs] [version-add *]
-> % gpg --list-keys robin.gloster@mayflower.de
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
pub   rsa4096/6E5C5807 2014-06-25 [expires: 2016-06-15]
uid         [ unknown] Robin Gloster <robin.gloster@mayflower.de>
sub   rsa4096/D3EDEC58 2015-06-16 [expires: 2016-06-15]

robin@graffel [07:18:48] [~/dev/nixpkgs] [version-add *]
-> % gpg2 --list-keys robin.gloster@mayflower.de
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
pub   rsa4096/6E5C5807 2014-06-25 [expires: 2016-06-15]
uid         [ unknown] Robin Gloster <robin.gloster@mayflower.de>
sub   rsa4096/D3EDEC58 2015-06-16 [expires: 2016-06-15]

robin@graffel [07:18:55] [~/dev/nixpkgs] [version-add *]
-> % ll `which gpg`
lrwxrwxrwx 1 root nixbld 66 Jan  1  1970 /home/robin/.nix-profile/bin/gpg -> /nix/store/s4xypm6d6gy55q9d043046wykfg7p3bk-gnupg1compat-0/bin/gpg

robin@graffel [07:19:21] [~/dev/nixpkgs] [version-add *]
-> % ll `which gpg2`
lrwxrwxrwx 1 root nixbld 64 Jan  1  1970 /home/robin/.nix-profile/bin/gpg2 -> /nix/store/zax54cybcsxv4kyrjqfvnq5ards63jsn-gnupg-2.1.9/bin/gpg2

**Comment by globin** [comment]
Could you run:
```
ls -l `which gpg` `which gpg2`
```

**Comment by matthiasbeyer** [comment]
```bash
$ ls -l `which gpg` `which gpg2`                                                                                                                                                                       │ <<~ [0] [20:18]
which: no gpg in (/home/m/bin:/var/setuid-wrappers:/home/m/.nix-profile/bin:/home/m/.nix-profile/sbin:/home/m/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec:/home/m/archive/bin)
lrwxrwxrwx 1 root nixbld 65  1. Jan 1970  /run/current-system/sw/bin/gpg2 -> /nix/store/6g0l061fryn7gkyyjf7wx58x7427d2w3-gnupg-2.1.10/bin/gpg2
```

with `gnupg1compat`:

```bash
$ ls -l `which gpg` `which gpg2` 
lrwxrwxrwx 1 root root  4  1. Jan 1970  /nix/store/db1dfv1v1scdsvwdlxq69wxwflpa5586-gnupg1compat-0/bin/gpg -> gpg2
lrwxrwxrwx 1 root root 65  1. Jan 1970  /nix/store/db1dfv1v1scdsvwdlxq69wxwflpa5586-gnupg1compat-0/bin/gpg2 -> /nix/store/662jlwbd50dn5nc6p0yiz6lyqx0dkys7-gnupg-2.0.29/bin/gpg2
```

**Comment by globin** [comment]
Have you got gnupg installed in your user or in your system environment?

**Comment by matthiasbeyer** [comment]
System env, as `pkgs.gnupg21`.

**Comment by matthiasbeyer** [comment]
@globin Is there still progress here? I don't know what else to do. Putting `gnupg1compat` into scope does not help either.

I guess git itself has to be build with the appropriate gnupg version...

**Comment by vcunat** [comment]
> I guess git itself has to be build with the appropriate gnupg version...

It isn't built with gnupg. I assume git only uses the command-line interface of gnupg, and most commands (and people) don't need gnupg support in git anyway, so that seems fine to me.

**Comment by matthiasbeyer** [comment]
So there should be at least an option to override the CLI call, so I can override it to use gnupg2 instead of the gnupg1compat version, because this is actually blocking me from signing commits!

The git build infrastructure is a bit huge, so I don't know what I have to look at for doing this, so guidance would be appreciated!

**Comment by peti** [comment]
I cannot reproduce this error:

    /tmp$ nix-shell --pure -p gnupg1 -p git

    [nix-shell:/tmp]$ mkdir test

    [nix-shell:/tmp]$ cd test

    [nix-shell:/tmp/test]$ git init .
    Initialized empty Git repository in /tmp/test/.git/

    [nix-shell:/tmp/test]$ echo Hello, World. >README

    [nix-shell:/tmp/test]$ git add .

    [nix-shell:/tmp/test]$ git commit -S -m "test"

    ... gpg-agent pops up a Window and asks for my pass phrase ...

    [master (root-commit) db8feb6] test
     1 file changed, 1 insertion(+)
     create mode 100644 README

    [nix-shell:/tmp/test]$ git log --show-signature
    commit db8feb6c1d246e536681c2fee304a476bb3fa44c
    gpg: Signature made Fri 18 Mar 2016 10:48:36 AM CET using RSA key ID 99089D72
    gpg: Good signature from "Peter Simons <simons@cryp.to>" [ultimate]
    Author: Peter Simons <simons@cryp.to>
    Date:   Fri Mar 18 10:48:36 2016 +0100

        test

I believe that you're mixing up GnuPG 2.0 and 2.1 somehow. I.e. note that `gnupg1` wraps the 2.0.x version by default, and in your initial message you said that you're using 2.1.x. Maybe that's part of the problem. Anyway, I'm pretty sure that the issue is caused by your *configuration*, and not by a bug in Nixpkgs.

**Comment by matthiasbeyer** [comment]
@peti:

```
$ nix-shell --pure -p gnupg1 -p git
$ mkdir /tmp/test && cd /tmp/test
$ git init .
$ echo hallo > hallo
$ git add .
$ git commit -S -m test
gpg: skipped "20CA0F94": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by peti** [comment]
I suppose you should look into why gpg believes that there is no secret key.

**Comment by matthiasbeyer** [comment]
All I know is that `gpg` does not find the key:

```
$ nix-shell --pure -p gnupg1 --run "gpg --list-keys '<my email address>'"
gpg: error reading key: No public key
```

**Comment by peti** [comment]
Do you realize that `gpg` is not gpg 2.1.x by default?

**Comment by matthiasbeyer** [comment]
Yes, sure, but how does this belong to my issue? I used `gnupg1` to `gpg --list-keys` and it failed... not `gpg2` or something? :confused:

**Comment by peti** [comment]
You said that `gpg2` can use your key correctly, but `gpg` can not. Now, the difference between the two is that your `gpg2` binary comes from GnuPG 2.1.x, but the `gpg` binary comes from GnuPG 2.0.x. So I reckon that this on variable worth exploring, i.e. what happens when you create `gnupg1compat` with `gnupg21` and try using that?

**Comment by matthiasbeyer** [comment]
Wow.

I did:

```nix
 gnupg1compat = super.gnupg1compat.override { gnupg = self.gnupg21; };
```

In my overrides, tried it and it works now. Thank you for your support!

**Comment by peti** [comment]
Well, make sure then that you vote in favor of https://github.com/NixOS/nixpkgs/pull/14012. :smile:
