### ISSUE TITLE
idea.*: should not hardcode oraclejdk8

### ISSUE THREAD

**Issue by gebner** [NixOS/nixpkgs#12555]
Right now the IntelliJ derivation hardcodes oraclejdk8, and AFAICT the only way to override this choice is by overriding oraclejdk8 itself:

``` nix
{ nixpkgs.config.packageOverrides = pkgs: { oraclejdk8 = pkgs.openjdk8; }; }
```

(I have tried `idea.idea-community.override { jdk = openjdk8; }` and `idea.idea-community.overrideDerivation (oldAttrs: { jdk = openjdk8; })` with no effect.)

Can we make this overridable somehow?
(FWIW, I've had no problems with 15 and 15 EAP under openjdk8, although I'm getting redraw artifacts with 16 EAP.)

cc @edwtjo

**Comment by copumpkin** [comment]
It was just recently changed away from that due to Idea having some bug with `openjdk` and not seeming very open to dealing with it. I can't find the ticket right now...

**Comment by copumpkin** [comment]
Oh https://github.com/NixOS/nixpkgs/commit/56fdc710139a6072d7593f8d0f7b897dbf9ab0e9

**Comment by gebner** [comment]
Okay, found the root cause of this bug.  The crucial line is the following in `ICC_Profile.java` (in openjdk):
```java
return (f.isFile() && isChildOf(f, dir)) ? f : null;
```
This checks that `GRAY.pf` is indeed in `jre/lib/cmm/`, and guess what this returns with our symlink maze...

As a temporary workaround you can set `IDEA_CLASSPATH=/nix/store/...-openjdk-.../lib/openjdk/jre/lib/cmm` as an extra environment variable.  This manages to hit the only special case in `ICC_Profile` which doesn't have this check, and then intellij works fine with openjdk.

Maybe I can draft a PR to fix this tomorrow.

**Comment by Profpatsch** [comment]
Since the PR is merged, I assume this issue was just forgotten.
