### ISSUE TITLE
nixos-rebuild fails on 21.05: anonymous function called with unexpected argument 'gestures'

### ISSUE THREAD

**Issue by k-u-bux** [NixOS/nixpkgs#125620]
After switching to 21.05, nixos-rebuild switch --upgrade fails:
unpacking channels...
building Nix...
building the system configuration...
error: anonymous function at /nix/store/nkr5k3g0ki69d7c2yn19lxd0fyfpnpsa-nixos-21.05.650.eaba7870ffc/nixos/pkgs/applications/window-managers/fvwm/default.nix:1:1 called with unexpected argument 'gestures', at /nix/store/nkr5k3g0ki69d7c2yn19lxd0fyfpnpsa-nixos-21.05.650.eaba7870ffc/nixos/lib/customisation.nix:69:16
(use '--show-trace' to show detailed location information)

The error seems to be triggered by fvwm in my configuration.nix. Here is a stripped down version that still triggers the error on a virtual machine:

{ config, pkgs, lib, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Boot and Kernel
  # ===============
  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.copyKernels = true;
  boot.loader.grub.device = "/dev/disk/by-id/ata-VBOX_HARDDISK_VB576b20e2-291c50e3"; # or "nodev" for efi only
  boot.supportedFilesystems = [ "zfs" ];
  boot.extraModprobeConfig = ''
    options zfs zfs_arc_max=1073741824
  '';
  networking.hostId = "0a0a0a0a";

  # Localization
  # ============
  # Select internationalisation properties.
  console.font = "Lat2-Termnus16";
  console.keyMap = "de";
  i18n = {
     	defaultLocale = "en_US.UTF-8";
  };
  # Set your time zone.
  time.timeZone = "Europe/Berlin";

  # Enable the X11 windowing system.
  services.xserver = {
	enable = true;
	layout = "de";
	xkbModel = "pc105";
	xkbVariant = "nodeadkeys";
	

	windowManager.fvwm.enable = true;
  };

  # Packages
  # ========
  environment.systemPackages = with pkgs; [
    # should be present when init scripts for users run
    zsh
    screen
    home-manager	
  ];

  # User management
  # ===============
  users.mutableUsers = true;

  # Version
  # =======
  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "20.03"; # Did you read the comment?
}

**To Reproduce**
1. Switch to the channel nixos-21.05
2. call nixos-rebuild switch --upgrade

**Expected behavior**
The system should upgrade.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/lp90qhw19dcp79cnlicjg09llgh7dzsz-bash-interactive-4.4-p23-dev
copying path '/nix/store/lp90qhw19dcp79cnlicjg09llgh7dzsz-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.119, NixOS, 21.05.650.eaba7870ffc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.650.eaba7870ffc, nixos-unstable-21.11pre293089.1c2986bbb80, nixpkgs-unstable-21.11pre292345.058b981b5bd"`
 - channels(bux): `"home-manager, nixos-20.09-20.09.4215.85960bea533, nixpkgs-unstable-21.11pre292293.84aa23742f6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by collares** [comment]
#118256 changed the argument name but forgot to update the nixos module at https://github.com/NixOS/nixpkgs/blob/8284fc30c84ea47e63209d1a892aca1dfcd6bdf3/nixos/modules/services/x11/window-managers/fvwm.nix#L7

**Comment by ztmr** [comment]
I have exactly the same problem, is there any workaround? Is it safe to change this manually?
