### ISSUE TITLE
VSCode on the Plasma Wayland session does not know how to use a secret agent (gnome-keyring or kwallet)

### ISSUE THREAD

**Issue by why-not-try-calmer** [NixOS/nixpkgs#125642]
VSCode on Plasma 5.21.5 (X11) has no issue storing user credentials (user typically by the Sync feature built in VSCode) with the native secret agent (kwallet). On Plasma Wayland by contrast, the program fails to access any secret agent (either kwallet or gnome-keyring). It ask the user for their credentials whenever the user runs the program.

Part of my `configuration.nix` pertaining to this Issue:
```
# xserver set up for Plasma
services.xserver.enable = true;
services.xserver.videoDrivers = [ "intel" ];
services.xserver.useGlamor = true;
services.xserver.displayManager.sddm.enable = true;
services.xserver.desktopManager.plasma5.enable = true;

# gnome keyring just in case kwallet woulnd't suffice
services.gnome.gnome-keyring.enable = true;

# vscode
environment.systemPackages = with pkgs; [ vscode ];
```
More details about my system:
```
Operating System: NixOS 21.11pre293089.1c2986bbb80
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.12.7
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.5 Gio of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
```

**Comment by SuperSamus** [comment]
Testing right now, it seems it has been fixed: VSCodium (XWayland) can access `kwallet` on Plasma Wayland (I didn't enable `gnome-keyring`).
