### ISSUE TITLE
Add mysql-shell

### ISSUE THREAD

**Issue by aszenz** [NixOS/nixpkgs#125636]
**MySQL Shell is an advanced client and code editor for MySQL created by the mysql team**

**Metadata**

* homepage URL: https://dev.mysql.com/doc/mysql-shell/8.0/en/
* source URL: https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.0.25-src.tar.gz
* license: gpl2
* platforms: unix, linux, darwin (available at https://dev.mysql.com/downloads/shell/, select operating system, sources are also available per os it seems)

**Comment by aaronjheng** [comment]
MySQL Shell has been added to nixpkgs. See https://search.nixos.org/packages?channel=unstable&show=mysql-shell&from=0&size=50&sort=relevance&type=packages&query=mysql-shell.
