### ISSUE TITLE
cannot run stack setup on fresh install

### ISSUE THREAD

**Issue by AlleaRizary** [NixOS/nixpkgs#12564]
Hi, I install NixOs in my virtualbox (i am using mac osx).

I install stack and gnumake then try to run stack setup until i got the following error:

Configuring GHC ...Running /tmp/stack-setup6107/ghc-7.10.3/configure --prefix=/home/rizimain/.stack/programs/x86_64-linux/ghc-7.10.3/ exited with ExitFailure 1
checking for path to top of build tree... 
/tmp/stack-setup6107/ghc-7.10.3/configure: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: /bin/bash: bad interpreter: No such file or directory
configure: error: cannot determine current directory

**Comment by vcunat** [comment]
I assume you know about the corresponding docs? http://nixos.org/nixpkgs/manual/#using-stack-together-with-nix

**Comment by peti** [comment]
`stack setup` does not work on NixOS, because `stack` doesn't know how to compiler properly on that system. Instead, use Nix to install the appropriate compiler and let `stack` use that one. You can also use the `stack --nix` option to simplify the procedure even further.
