### ISSUE TITLE
Raspberry Pi 4B secondary monitor not working

### ISSUE THREAD

**Issue by carlosneves0** [NixOS/nixpkgs#125714]
## Issue description

xserver + dmesg + udev -> no one logs anything as I plug/unplug the secondary HDMI cable; but the secondary monitor shows some gradient image.

## Technical details

 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.17, NixOS, 21.11pre292520.540dccb2aea (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by nagy** [comment]
Maybe this can help you https://github.com/NixOS/nixpkgs/issues/63720#issuecomment-657026529

**Comment by carlosneves0** [comment]
Thanks for the tip! After searching, I came up with this configuration:

```nix
boot.loader = {
    grub.enable = false;
    generic-extlinux-compatible.enable = true;
    raspberryPi = {
      enable = true;
      uboot.enable = true;
      version = 4;
      firmwareConfig = ''
        max_framebuffers=2
      '';
    };
  };
```
```
# nixos-rebuild switch && reboot
```

It **did not work**.

---

This worked:

```
# mount /dev/disk/by-label/FIRMWARE /mnt
# printf '\nmax_framebuffers=2' >> /mnt/config.txt
# umount /mnt && reboot
```

Is there a way to make the declarative config work?

**Comment by carlosneves0** [comment]
I can't validate whether it has been solved for good as I went with alpine for the raspberry-pi.

If I come back to try nixos again I'll check, and if I find any issues I'll come back here.

Let's close this issue.
