### ISSUE TITLE
Document conventions around environment.systemPackages

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12575]
I've noticed many services automatically adding packages to `environment.systemPackages` and it feels kind of weird to me. I don't know if there's an intentional convention here (couldn't find any guidelines in document), but it seems strange to me to do that.

So basically, is it sensible for us to keep doing that? If so, let's document it and why. If not, let's document that and remove all the undesired `systemPackages` from current services.

**Comment by globin** [comment]
Some services probably need some interaction with users to be usable, having to add `pkgs.lxc` to systemPackages by hand is an unnecessary bloat as to use lxc containers you will always want to enable the module and then also have the commands available.

**Comment by copumpkin** [comment]
Eh, I don't usually want things implicitly in scope, and I can't easily take things out of it. Take a multi-user system. Just because the system has a service turned on doesn't mean that all users should get their scope polluted with it. I usually use `nix-shell` to get environments.

**Comment by globin** [comment]
Generally yes!

I'm not really sure about this.. I kind of expect to have a working lxc including control commands when turning on `virtualisation.lxc.enable`, don't know how other people feel about this.

But there definitely are services where I adding the binaries to the environment is unnecessary, don't have one at hand at the moment which does that, but nginx were such a case.

**Comment by FRidh** [comment]
I suppose many services should add their packages to `system.extraDependencies` instead of `environment.systemPackages`?

**Comment by globin** [comment]
Ij most cases using the specific command in the service script should be enough.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/5c20877d40726b6973d222f71fa6e306428c19cf

**Comment by Profpatsch** [comment]
triage: what’s the status? Maybe a linter could be added.
