### ISSUE TITLE
Python: extension types are not available during checkPhase

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#12574]
Several times now I've encountered extension types not to be available during testing. The modules do load fine afterwards.

Examples:
- bottleneck
- numba

**Comment by FRidh** [comment]
cc @domenkozar

**Comment by domenkozar** [comment]
@FRidh you mean when you run tests, C extensions are not compiled?

**Comment by FRidh** [comment]
The checkPhase runs after installation right, so the C extensions should be available. However, they cannot be imported.

**Comment by domenkozar** [comment]
that's because the module/package is imported from $sourceRoot instead of $out, I think.

**Comment by FRidh** [comment]
ahh yes, that could be. So for example with nosetests, I should invoke nosetests $out or something like that.

**Comment by domenkozar** [comment]
indeed, that's why we even run tests after the installation phase

**Comment by FRidh** [comment]
Great, this works.
``` 
checkPhase = ''
  nosetests -v $out/${python.sitePackages}/${name}
'';
```
Using ${name} might not always work if the package name is different from the Nix name.
Anyway, will need to document this.

**Comment by domenkozar** [comment]
even just skipiing `${name}` should work
