### ISSUE TITLE
SDL2 pkg-config requires x11.

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#12585]
SDL2 built with X11 must have the X11 pkg-config as a require. This is the simplest reproduction:

test.c:

    #include <SDL_syswm.h>
    int main() {}

gcc test.c $(pkg-config --cflags --libs sdl2):
    
    In file included from test.c:1:0:
    /nix/store/jq3c1i7aqs22l8pycvbmqczv8w9vmghr-SDL2-2.0.3/include/SDL2/SDL_syswm.h:70:22: fatal error: X11/Xlib.h: No such file or directory
    #include <X11/Xlib.h>
                      ^
Versions:

nixos-version: 15.09.947.6783594 (Dingo)
reproduced against nixpkgs branch master / revision 7ccda42 via nix-shell.

Status: PR incoming

**Comment by sheenobu** [comment]
I've been trying to work around this but prefix modifications don't behave well:

https://gist.github.com/sheenobu/eff918e9a63f60fcfcfa

**Comment by vcunat** [comment]
You (typically) don't need both in the same folder (and if so, there's `buildEnv` for that). It's typically sufficient to add both into build inputs.

**Comment by sheenobu** [comment]
@vcunat 

> It's typically sufficient to add both into build inputs.

This is the atypical case. The buildEnv still links everything together. sdl2 and x11 are stored separately and linked, but the pkg-config still references them by their separate stores.

As shown above, an sdl2 application using the SDL_syswm.h depends on the x11 headers being somewhere. The sdl2 pkg-config can't depend on x11 (since it's optional), but prefixing both packages into the same location will work (but clearly isn't ideal).

Other distros do fine because the X11 headers are filed away in the same location as the SDL2 headers.

**Comment by vcunat** [comment]
I meant that when you have both `SDL2` and `libX11` in `buildInputs`, then all headers will be found by gcc, regardless of what is in *.pc files.

**Comment by sheenobu** [comment]
Gotcha. Just had to set C_INCLUDE_PATH to the environment where everything is linked up for standard gcc to see it (and cgo in this case). Thanks, closing issue.
