### ISSUE TITLE
Neovide fails to run

### ISSUE THREAD

**Issue by Creator54** [NixOS/nixpkgs#125818]
**Describe the bug**
neovide fails to run

**To Reproduce**
1. nix-env -iA nixos.neovide
2. neovide

**Expected behavior**
should run 

**Screenshots**
![share](https://user-images.githubusercontent.com/34543609/120898356-2378db00-c648-11eb-84b0-ae441f41fdc3.png)

**Additional context**
neovim is installed

**Notify maintainers**
@ck3d

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.641.5237039cc1e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.641.5237039cc1e"`
 - channels(creator54): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
https://github.com/Kethku/neovide/issues/459
https://github.com/Kethku/neovide/issues/491
known issue, the opengl branch should work

**Comment by figsoda** [comment]
Also related: https://github.com/NixOS/nixpkgs/issues/123262

**Comment by teto** [comment]
closing as a non-nix bug. Neovide has some known quirks, these will hopefully be solved with the opengl release. For instance opengl starts for me but refuses to input `:` or `_` which is troublesome in a vim based editor.
