### ISSUE TITLE
Add avif support to KDE

### ISSUE THREAD

**Issue by est31** [NixOS/nixpkgs#125920]
The [kimageformats](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/kde-frameworks/kimageformats.nix) library has support for AVIF since the [release of KDE frameworks 5.78.0](https://kde.org/announcements/frameworks/5/5.78.0/). [Link to the commit](https://invent.kde.org/frameworks/kimageformats/-/commit/34a9ec1b06844a4caca1362ee15fc8a4143931e6) that added AVIF support. The support is optional however, and requires the libavif library to be present. I imagine one needs to package [libavif](https://github.com/AOMediaCodec/libavif) for nixos, then add it to the `buildInputs`/`CXXFLAGS` similarly to how it's done for openexr already.

**Comment by prusnak** [comment]
libavif is already packaged in `pkgs/development/libraries/libavif`. So maybe just adding `libavif` to `buildInputs` in `pkgs/development/libraries/kde-frameworks/kimageformats.nix` is enough?

@est31 Can you try if that works for you and if it did send a pull request?

**Comment by est31** [comment]
@prusnak interesting. I'll give it a try.

**Comment by est31** [comment]
So I've done some experimenting locally, and apparently if I only add libavif it still doesn't recognize avif files. It does create a `kimg_avif.so` file meaning that it successfully created a plugin, but when I try to open avif files using gwenview, it gives an error that it can't open `application/octet-stream` files. If I try to open an heif file however, it shows a different error: it complains that it can't open `image/heif` files. So maybe it has the module, but no clue it can use the module because it doesn't know the mime type.

Also, running `xdg-mime query filetype` returns the correct mime type for jpg and heif files, but does not return the correct mime type for avif files. I've checked and apparently the shared-mime-info package points to the 1.13.1 release from September 2019, but the [patch to add avif was only merged in April 2020](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/merge_requests/72). The most recent release is 2.1 from Dec 31 2020. I suspect that an update of the shared-mime-info package should fix this, but need to test it. cc @mimame maintainer of shared-mime-info.

**Comment by est31** [comment]
I've looked a bit into the question of updating shared-mime-info. An update to 2.1 needed some adjustments to accommodate for the meson migration and a backport of a patch to not hit the internet during build. After that the package built but there was a test failure in one of the dependents... When I backported the AVIF patch for 1.13.1, I realized that basically everything depends on shared-mime-info. I eventually ran out of disk space during the build. I think that waiting for a regular update of shared-mime-info would be best.

**Comment by est31** [comment]
Also, it seems that the CXXFLAGS thing isn't needed.

**Comment by est31** [comment]
@prusnak I've tested the patch locally and it works (needed to wait until there were sufficient hydra cache results for #126050). I've made a PR: #127862

**Comment by datMaffin** [comment]
KImageFromat does currently not seem build:

See comments in PR of libavif upgrade: https://github.com/NixOS/nixpkgs/pull/128064

The following fix, which looks to be included in `v5.83.0-rc1`  seems relevant: 
https://invent.kde.org/frameworks/kimageformats/-/commit/bf3f94da766d66a0470ab744dbe1ced4697b572d
