### ISSUE TITLE
Python: tests that create temporary directories fail with PermissionError

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#12591]
```
PermissionError: [Errno 13] Permission denied: '/homeless-shelter'
```

**Comment by domenkozar** [comment]
This is the value of `$HOME` in Nix

**Comment by FRidh** [comment]
How could this be made working? I would expect $HOME to be pointing to a temporary directory.

**Comment by domenkozar** [comment]
@FRidh some of python packages point `$HOME` to `$TMPDIR` or similar
