### ISSUE TITLE
broadcom driver doesn't build with generated config

### ISSUE THREAD

**Issue by georgewhewell** [NixOS/nixpkgs#12595]
In the configuration generated by nixos-generate-config, the following line enabled the broadcom driver:

    boot.extraModulePackages = [ "${config.boot.kernelPackages.broadcom_sta}" ];

nixos-rebuild fails with:

    error: path ‘/nix/store/4s1fc4sqbl41wpz3lfx894aamh1k8znl-broadcom-sta-6.30.223.248-4.4’ does not exist and cannot be created

If I replace the line in my config with

    boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

the driver is built correctly. This behaviour started happening fairly recently (~1 week). Prior to this, the first variant worked fine.

**Comment by copumpkin** [comment]
This sounds more like a Nix issue than a nixpkgs one, but let's leave it here and highlight @edolstra.

**Comment by thall** [comment]
nixos/modules/installer/tools/nixos-generate-config.pl:151 was changed in commit b11f6626

**Comment by henrytill** [comment]
@copumpkin: I suggested posting the issue here  based on https://github.com/NixOS/nixpkgs/issues/3560#issuecomment-52161477 and https://github.com/NixOS/nix/issues/299#issuecomment-49590237

**Comment by vcunat** [comment]
I don't know why it has stopped working, but anyway, passing this as a string wasn't a good idea. Hacked a fix and pushed to master and 15.09.
