### ISSUE TITLE
nautilus-python not loading python-extension

### ISSUE THREAD

**Issue by Stunkymonkey** [NixOS/nixpkgs#126074]
**Describe the bug**
`nautilus-python` does not load python-extension of nautilus to display a context menu entry.

**To Reproduce**
1. install `gnomeExtensions.nautilus-open-any-terminal` from https://github.com/Stunkymonkey/nixpkgs/commit/da1610bc483fab3ba79e47b91746b5013a4d858c
2. restart nautilus
3. no context menu is shown

**Expected behavior**
a new context menu entry, that could open e.g. `alacritty`

**Additional context**
Maybe I am doing something wrong. I am pretty new to `nix`. Maybe you could help 

**Notify maintainers**
i guess @hedning, @dasj19, @maxeaubrey

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.4, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(user): `""`
 - channels(root): `"nixos-21.05.804.5de44c15758, nixos-unstable-21.05pre277486.f5e8bdd07d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: gnomeExtensions.nautilus-open-any-terminal
```

**Comment by dasj19** [comment]
Idk how much help this is but have you tried looking at how `nautilus-python` is defined: https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/misc/nautilus-python/default.nix

I think that the following line specifically says that only extensions in `$out/lib/nautilus/extensions-3.0` are loaded.
`
PKG_CONFIG_LIBNAUTILUS_EXTENSION_EXTENSIONDIR = "${placeholder "out"}/lib/nautilus/extensions-3.0";`

**Comment by Stunkymonkey** [comment]
tried it, but does not work.
additionally i found `mat2` which tries to do the [same thing](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/mat2/default.nix#L78). unfortunately it does not work as well.

**Comment by jtojnar** [comment]
`nautilus-python` did not work properly before https://github.com/NixOS/nixpkgs/pull/142824.

----

We rely on GNOME NixOS module [setting  `NAUTILUS_EXTENSION_DIR` environment variable](https://github.com/NixOS/nixpkgs/blob/bc97152537801d20561749f5cfa033de4632d80e/nixos/modules/services/x11/desktop-managers/gnome.nix#L556) for Nautilus to be find `nautilus-python`. That means `nautilus-python` needs to be installed via `environment.systemPackages`.

`nautilus-python` then needs its extensions to be available on `XDG_DATA_DIRS` path (in `nautilus-python/extensions` subdirectory). And it might fail if the extension depends on anything other than Nautilus and its dependencies.

**Comment by Stunkymonkey** [comment]
thanks for the expanation :+1: .
can you confirm, that `mat2` is working? (right-clicking on jpegs, mp3s, ... should have an extra entry about removing metadata)
I have `gnome.nautilus-python` installed system-wide. But still do not see the context-menu.

If you have a second please look over my last commit: https://github.com/Stunkymonkey/nixpkgs/tree/nautilus-open-any-terminal

**Comment by jtojnar** [comment]
Running nautilus in the console show the following with `mat2` installed:

```python-traceback
Traceback (most recent call last):
  File "/home/jtojnar/.nix-profile/share/nautilus-python/extensions/mat2.py", line 28, in <module>
    from libmat2 import parser_factory
  File "/nix/store/x7rfd5lxym1zx7m15yhk0i6hlbfr4cwd-python3.9-mat2-0.12.3/lib/python3.9/site-packages/libmat2/parser_factory.py", line 30, in <module>
    __load_all_parsers()
  File "/nix/store/x7rfd5lxym1zx7m15yhk0i6hlbfr4cwd-python3.9-mat2-0.12.3/lib/python3.9/site-packages/libmat2/parser_factory.py", line 27, in __load_all_parsers
    importlib.import_module('.' + name, package='libmat2')
  File "/nix/store/gras7a25yy9f7djmzrgh1bsiiacg0s9c-python3-3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/nix/store/x7rfd5lxym1zx7m15yhk0i6hlbfr4cwd-python3.9-mat2-0.12.3/lib/python3.9/site-packages/libmat2/images.py", line 6, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
```

so that is an issue with extra dependencies (`python3.pkgs.pycairo`). I guess the best solution would be manipulating python path in mat2 like python wrappers do.

**Comment by Stunkymonkey** [comment]
my first goal will be to get the same error for `mat2` as you do. Because i never managed to get `nautilus-python` source any files.

i have `nautilus-python` and `mat2` both installed.

Do I have to set `NAUTILUS_EXTENSION_DIR` like this?
```
NAUTILUS_EXTENSION_DIR=$(nix-store --query --requisites /run/current-system | grep "nautilus-python-1.2.3$")/lib/nautilus/extensions-3.0 nautilus
```
or is like this?
```
XDG_DATA_DIRS=$(nix-store --query --requisites /run/current-system | grep "mat2")/share/nautilus-python/extensions:$XDG_DATA_DIRS nautilus
```

sorry I am a bit lost here :see_no_evil:

**Comment by jtojnar** [comment]
`NAUTILUS_EXTENSION_DIR` can only contain a single directory. And that should be `/run/current-system/sw/lib/nautilus/extensions-3.0`, where all the Nautilus extensions are symlinked thanks to `environment.systemPackages`:

https://github.com/NixOS/nixpkgs/blob/bc97152537801d20561749f5cfa033de4632d80e/nixos/modules/services/x11/desktop-managers/gnome.nix#L556

`XDG_DATA_DIRS` should contain `/run/current-system/sw/share` on NixOS by default (note that it only contains the `share/` directory. If you do not use GNOME, you might also need [`environment.pathsToLink`](https://github.com/NixOS/nixpkgs/blob/bc97152537801d20561749f5cfa033de4632d80e/nixos/modules/services/x11/desktop-managers/gnome.nix#L561-L563) so that `environment.systemPackages` creates a symlink.

But yeah, something like the following should work:

```bash
env "NAUTILUS_EXTENSION_DIR=$(nix-build -A gnome.nautilus-python --no-out-link)/lib/nautilus/extensions-3.0" "XDG_DATA_DIRS=$(nix-build -A mat2 --no-out-link)/share:$XDG_DATA_DIRS" nautilus
```

**Comment by Stunkymonkey** [comment]
> If you do not use GNOME, you might also need environment.pathsToLink so that environment.systemPackages creates a symlink.

this was exactly my problem. by adding this the extensions will get loaded. Thanks for your help.

**Comment by BerriJ** [comment]
For some reason I had to add:

```
environment = {
  sessionVariables.NAUTILUS_4_EXTENSION_DIR = "${pkgs.nautilus-python}/lib/nautilus/extensions-4";];
};
```

to my settings although it should be set by gnome? https://github.com/NixOS/nixpkgs/blob/7eed5cda8d45e1a0def0db553e6b76311f9961bf/nixos/modules/services/x11/desktop-managers/gnome.nix#L468

But with that, it works. Maybe this helps others :)
