### ISSUE TITLE
Python: hardcode abs path to library in ffi.dlopen('library') in case of CFFI module

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#12608]
More packages are starting to use cffi in ABI-mode to load libraries. Setting LD_LIBRARY_PATH helps finding the needed libraries and allows a package to be build, installed and tested. However, afterwards the package becomes unusable because the library cannot be found anymore.

So far I used sed to replace the argument to dlopen with an absolute path. Maybe we can do it a bit nicer?

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixpkgs/issues/7307
