### ISSUE TITLE
Postfix broken in https://nixos.org/channels/nixos-unstable

### ISSUE THREAD

**Issue by otwieracz** [NixOS/nixpkgs#12605]
``sendmail`` does not have permissions to access ``/etc/postfix/main.cf``:

```
[otwieracz@odyssey:~]$ sendmail
sendmail: fatal: open /etc/postfix/main.cf: Permission denied
```

```
[otwieracz@odyssey:~]$ ls -la /etc/postfix 
lrwxrwxrwx 1 root root 19 Jan 25 08:49 /etc/postfix -> /etc/static/postfix

[otwieracz@odyssey:~]$ ls -la /etc/static/postfix
lrwxrwxrwx 1 root nixbld 21 Jan  1  1970 /etc/static/postfix -> /var/lib/postfix/conf

[otwieracz@odyssey:~]$ ls -la /var/lib/
...
drwx------  5 postfix postfix  7 Jan 24 19:07 postfix
...

[otwieracz@odyssey:~]$ ls -la /var/lib/postfix/
ls: cannot open directory /var/lib/postfix/: Permission denied
```

**Comment by FRidh** [comment]
Might be relevant: https://github.com/NixOS/nixpkgs/pull/12459

**Comment by vcunat** [comment]
Perhaps this changelog entry:
> Data directory for Postfix MTA server is moved from /var/postfix to /var/lib/postfix. Old configurations are migrated automatically. service.postfix module has also received many improvements, such as correct directories' access rights, new aliasFiles and mapFiles options and more.

**Comment by abbradar** [comment]
This should be fixed in https://github.com/NixOS/nixpkgs/pull/12459, I think.

**Comment by peti** [comment]
Yes, https://github.com/NixOS/nixpkgs/pull/12459 fixed this issue.

**Comment by otwieracz** [comment]
```
[root@odyssey:~]# nix-channel --list
nixos https://nixos.org/channels/nixos-unstable

[root@odyssey:~]# nixos-rebuild switch --upgrade
...
[root@odyssey:~]#
```

```
[otwieracz@odyssey:~]$ which sendmail
/var/setuid-wrappers/sendmail

[otwieracz@odyssey:~]$ sendmail
sendmail: fatal: open /etc/postfix/main.cf: Permission denied
````

**Comment by peti** [comment]
The fix isn't available in the channel yet.

**Comment by otwieracz** [comment]
How is this possible? Fix was merged 3 days ago, nixos-unstable is 2 days old (according to http://howoldis.herokuapp.com/nixos-unstable)

**Comment by domenkozar** [comment]
There is a delay between a commit and channel update, sometimes bigger than a day.

**Comment by otwieracz** [comment]
Still affecting https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/pkgs/servers/mail/postfix/default.nix

**Comment by peti** [comment]
I've opened issue https://github.com/NixOS/nixpkgs/issues/12885 to track progress on that front.
