### ISSUE TITLE
nix-env -i python3 is different than nix-env -iA nixpkgs.python3

### ISSUE THREAD

**Issue by ianthehenry** [NixOS/nixpkgs#126036]
**Describe the bug**
There are multiple derivations named `python3`, and none of them specify an explicit priority.

**To Reproduce**
1. Run `nix-env -i python3`
2. Observe Nix trying to install `python3-3.10.0a5`

**Expected behavior**
Nix should install `python3-3.8.9`, the current version specified by `nixpkgs.python3`.

**Additional context**
This is sort of *subjectively* a bug. This is a weird gotcha for new Nix users, who could also hit this issue by running `nix-env -u` after running `nix-env -iA nixpkgs.python3`.

It is currently the case that `python3-3.10.0a5` does not build. This is sort of fortunate, because it makes it obvious that something is wrong here, and otherwise people could silently install the "wrong" version of Python.

**Notify maintainers**
@FRidh 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.5.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(ian): `"nixpkgs-21.11pre294098.4df31757808"`
 - nixpkgs: `/Users/ian/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3
```

**Comment by FRidh** [comment]
Nothing that can be done here. This is `nix-env` behavior and the advice is to never use `nix-env -i`.

**Comment by birlorg** [comment]
> Nothing that can be done here. This is `nix-env` behavior and the advice is to never use `nix-env -i`.

The manual still teaches `nix-env -i` the stable manual here: https://nixos.org/manual/nix/stable/

from the manual: 
```
You can install a package using nix-env -i. For instance, 
`$ nix-env -i subversion`
 will install the package called subversion (which is, of course, the Subversion version management system).
 ```

So we should probably fix that.  I don't know where the manual sources are or the replacement for `nix-env -i`

**Comment by ianthehenry** [comment]
@FRidh is there a well-known alternative to `nix-env -u`? I think that's the more-likely place that the lack of an explicit priority is going to bite people.

**Comment by FRidh** [comment]
The only alternative as far as I know is the experimental `nix profile` command.
