### ISSUE TITLE
Firefox shows public certificate authorities as “not recognized by Mozilla”

### ISSUE THREAD

**Issue by sigprof** [NixOS/nixpkgs#126065]
**Describe the bug**
Firefox (from `pkgs.firefox`) shows “Connection verified by a certificate issuer that is not recognized by Mozilla” even for well-known public certificate authorities (DigiCert, Let's Encrypt, …).

**To Reproduce**
1. Install Firefox on NixOS 21.05 from the unmodified `pkgs.firefox` package.
2. Start Firefox with an empty profile; it helpfully opens the “Firefox Privacy Notice” page from https://www.mozilla.org/en-US/privacy/firefox/ (you can also open https://addons.mozilla.org, https://www.nixos.org/, …)
3. Click the padlock icon to the left of the URL bar to open the site information popup.
4. Observe the warning: “Connection verified by a certificate issuer that is not recognized by Mozilla”.

**Expected behavior**
Firefox should not show warnings about not recognized certificate issuers when the site certificate was issued by a well-known public certificate authority (not by some local CA added via policy).

**Screenshots**
![Firefox 89.0](https://user-images.githubusercontent.com/616082/121011476-541f5880-c79f-11eb-90c8-7ab117a7c0ed.png)

**Additional context**
Tested Firefox 89.0 at the most recent `nixos-21.05` commit at the moment (5de44c15758465f8ddf84d541ba300b48e56eda4), 88.0.1 @ d6229c7f5fd2800550697f6ff3d46361e056bb38, 87.0 @ 29058f9a43064ab0fbd2222420ddc1f3339e2a69 — they are all affected; not sure whether it is possible to test some older versions without the need to build them from source. Firefox 78.11.0esr (`pkgs.firefox-esr`) does not have the problem, but I'm not sure whether that older version is actually able to show that warning. 

Apparently this is caused by the `nss` change to use p11-kit (#96763). Just for testing I tried to build `nss` without that option:
```sh
nix profile install --impure --expr '(import <nixpkgs> {}).nss.override { useP11kit = false; }'
```
When I inject that library version into Firefox using `LD_PRELOAD=$HOME/.nix-profile/lib/libnss3.so`, the warning about “certificate issuer that is not recognized by Mozilla” disappears.

Note that the problems in Firefox are apparently not limited to that warning — extension installation using `extraPolicies.ExtensionSettings` with `install_url` pointing to `https://addons.mozilla.org/` also does not work, showing messages complaining about unrecognized certificates. The addon manager, however, still works even in this configuration.

**Notify maintainers**
@rnhmjoj
@ajs124
@mweinelt
@lovesegfault

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.20210604.aa57635 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/store/zjmnwn76xzxw3j7v1p98fd0aywpvyylf-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mweinelt** [comment]
Right, so nss uses p11kit since #96763 to make every nss consumer rely on the system certificate store. We could rebuild firefox with the nss override you mentioned, that would then decouple firefox from the central certificate store, but the kicker is, that our cacert package is extracted from nss itself, so it is in fact the same IIUC. So it might make sense to look into how they certify those, that makes Firefox see them as recognized.

**Comment by mweinelt** [comment]
```js
  /**
   * Returns whether the issuer of the current certificate chain is
   * built-in (returns false) or imported (returns true).
   */
  _hasCustomRoot() {
    let issuerCert = null;
    issuerCert = this._secInfo.succeededCertChain[
      this._secInfo.succeededCertChain.length - 1
    ];

    return !issuerCert.isBuiltInRoot;
  },
```
browser/base/content/browser-siteIdentity.js

Looks to be this `isBuiltInRoot` attribute.

**Comment by ajs124** [comment]
The reason why this doesn't happen with firefox esr 78 is that that uses an older version of nss, in which we didn't have p11-kit support yet.

**Comment by sigprof** [comment]
> So maybe it is a problem in our p11-kit packaging.

Looks like it. In nixpkgs p11-kit uses `--with-trust-paths=/etc/ssl/certs/ca-certificates.crt` — this is apparently a plain OpenSSL-compatible certificate bundle which does not contain any certificate attributes. But in Fedora p11-kit is configured [like this](https://src.fedoraproject.org/rpms/p11-kit/blob/rawhide/f/p11-kit.spec#_84) (they build it with meson):
```
# These paths are the source paths that  come from the plan here:
# https://fedoraproject.org/wiki/Features/SharedSystemCertificates:SubTasks
%meson -Dgtk_doc=true -Dman=true -Dtrust_paths=%{_sysconfdir}/pki/ca-trust/source:%{_datadir}/pki/ca-trust-source
```
`/usr/share/pki/ca-trust-source` comes from [the `ca-certificates` package](https://src.fedoraproject.org/rpms/ca-certificates/tree/rawhide), and contains `ca-bundle.trust.p11-kit`, which looks like this:
```
# This is a bundle of X.509 certificates of public Certificate
# Authorities.  It was generated from the Mozilla root CA list.
# These certificates and trust/distrust attributes use the file format accepted
# by the p11-kit-trust module.
#
# Source: nss/lib/ckfw/builtins/certdata.txt
# Source: nss/lib/ckfw/builtins/nssckbi.h
#
# Generated from:
# NSS_BUILTINS_LIBRARY_VERSION "2.48"
#
[p11-kit-object-v1]
label: "ACCVRAIZ1"
class: x-certificate-extension
object-id: 2.5.29.37
value: "0 %06%03U%1d%25%01%01%ff%04%160%14%06%08%2b%06%01%05%05%07%03%04%06%08%2b%06%01%05%05%07%03%01"
modifiable: false
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAm6mrv2FKl68vl2aadF/Q
...
-----END PUBLIC KEY-----

[p11-kit-object-v1]
label: "ACCVRAIZ1"
trusted: true
nss-mozilla-ca-policy: true
modifiable: false
nss-server-distrust-after: "%00"
nss-email-distrust-after: "%00"
-----BEGIN CERTIFICATE-----
MIIH0zCCBbugAwIBAgIIXsO3pkN/pOAwDQYJKoZIhvcNAQEFBQAwQjESMBAGA1UE
...
```
Note `nss-mozilla-ca-policy: true` — this format supports such certificate attributes. Fedora also has some scripts in their packages that can extract the certificate information from that format and write it out in various other formats, such as OpenSSL-compatible certificate bundle, Java key store, …

**Comment by ajs124** [comment]
> (they build it with meson):

There was an attempt to build p11-kit with meson before, in #73341, although that seems to have stalled.

> `/usr/share/pki/ca-trust-source` comes from [the `ca-certificates` package](https://src.fedoraproject.org/rpms/ca-certificates/tree/rawhide), and contains `ca-bundle.trust.p11-kit`

So maybe we should also modify our `cacert` package to include this?

On a side-note, Arch Linux also seems to use a different [cacertdata2pem.py](https://github.com/archlinux/svntogit-packages/blob/master/nss/trunk/certdata2pem.py) script from us, which looks like it generates a file like this.

**Comment by sigprof** [comment]
> On a side-note, Arch Linux also seems to use a different [cacertdata2pem.py](https://github.com/archlinux/svntogit-packages/blob/master/nss/trunk/certdata2pem.py) script from us, which looks like it generates a file like this.

Yes, and apparently it's even the same script as [the one used in Fedora](https://src.fedoraproject.org/rpms/ca-certificates/blob/rawhide/f/certdata2pem.py).

> So maybe we should also modify our `cacert` package to include this?

Yes, this would make sense. Fedora treats the p11-kit format as the master one, and [generates all other formats from it](https://src.fedoraproject.org/rpms/ca-certificates/blob/rawhide/f/update-ca-trust):
```sh
/usr/bin/p11-kit extract --format=openssl-bundle --filter=certificates --overwrite --comment $DEST/openssl/ca-bundle.trust.crt
/usr/bin/p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --comment --purpose server-auth $DEST/pem/tls-ca-bundle.pem
/usr/bin/p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --comment --purpose email $DEST/pem/email-ca-bundle.pem
/usr/bin/p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --comment --purpose code-signing $DEST/pem/objsign-ca-bundle.pem
/usr/bin/p11-kit extract --format=java-cacerts --filter=ca-anchors --overwrite --purpose server-auth $DEST/java/cacerts
/usr/bin/p11-kit extract --format=edk2-cacerts --filter=ca-anchors --overwrite --purpose=server-auth $DEST/edk2/cacerts.bin
```
Doing it like this, however, would bring `p11-kit` into the dependency chain of `cacerts`, which might not be desired.

And we will need to do something with [`nixos/modules/security/ca.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/ca.nix) — these options should also affect the contents of `ca-bundle.trust.p11-kit` somehow.

**Comment by mweinelt** [comment]
Agreed, let's try that route (the fedora one), we are also leaning on them for firefox sometimes and they have dedicated people for this stuff.

**Comment by ajs124** [comment]
I'm not sure if and when I'll have some time to further look into this. Do any of you think you'll get around to working on this in the foreseeable future?

Also, we should probably get the cacert maintainers in here cc @andir @lukegb

**Comment by lukegb** [comment]
I'll try to look at this this evening.

**Comment by dasJ** [comment]
I don't see this mentioned here but it's currently not possible to install add-ons or to update them. This also includes the automatic update functionality.

Installing an add-on from AMO:
![image](https://user-images.githubusercontent.com/4971975/121259422-63da9200-c8b0-11eb-8560-d08d2f4f7811.png)

Running the auto-updater from about:addons top-right cogwheel tells me there are no updates.
However opening the browser console from the developer menu shows something like:
> 1623187372132	addons.update-checker	WARN	Request failed: https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=debug@ninja-cookie.com&version=0.6.3&maxAppVersion=*&status=userDisabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=88.0.1&appOS=Linux&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=88.0.1&updateType=97&compatMode=normal - [Exception... "Certificate issuer is not built-in."  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 183"  data: no]

This is a critical security problem since plugins with vulnerabilities are not updateable without manual work to disable certificate verification. cc @NixOS/security-notifications 

@ajs124 committed a downstream fix for this in our overlay (hope it's okay to share ;):
```nix
self: super: {
  firefox = super.firefox.override {
    nss = unstable.nss.override { useP11kit = false; };
  };
}
```

**Comment by sigprof** [comment]
So at least the emergency fix is in `nixos-21.05` now, and seems to work — there is no scary warning about unrecognized certificate issuer, and addon installation and updating seems to work (I did not immediately notice this part of the problem, because I was using an existing profile with the needed addons already installed). Did not test the `extraPolicies.ExtensionSettings` part yet, but I guess that the addon installation would work too.

Should I just close this issue now (because the Firefox part has been handled), or would you prefer to keep it open, even though the problem in the form described at the first message does not exist anymore?

Also I just found #8247, where this change should probably be noted too.

**Comment by rnhmjoj** [comment]
The issue with Firefox is solved by simply turning off p11-kit integration, it 100% undoes the change in https://github.com/NixOS/nixpkgs/pull/96763. So, yeah le'ts close this.

**Comment by mweinelt** [comment]
AFAIU andir and lukgeb are working on updating the cacert/p11-kit packaging so that we can eventually reenable the integration.

**Comment by felixsinger** [comment]
Why is the issue closed? In my opinion, disabling p11-kit is not a good long-term solution. What is the status of the cacert / p11-kit packaging? Any updates?

**Comment by mweinelt** [comment]
It isn't the chosen long-term solution, but the issue itself is resolved.

The long-term solution will be https://github.com/NixOS/nixpkgs/pull/136777.

**Comment by felixsinger** [comment]
Thanks!
