### ISSUE TITLE
Sourcehut secrets

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixpkgs#126090]
Is there an option to read keys from a file so that they don't end up in the nix store? Something similar to what wireguard has:
`networking.wireguard.interfaces.<name>.privateKeyFile` instead of `networking.wireguard.interfaces.<name>.privateKey`?

_Originally posted by @pinpox in https://github.com/NixOS/nixpkgs/issues/113244#issuecomment-855977208_

What's the best way to do this? TOML nor sourcehut allow a "from file" ability. So next best option is to have a `config.ini.template` in `/etc/sr.ht` and a service that fills in the details imperatively into the actual `config.ini` from non-nix-store'd files prior to services starting?

**Comment by Artturin** [comment]
fix it upstream?

**Comment by pinpox** [comment]
@tomberek Are you planning on implementing this? I can't really use the current module without giving all users on my system access to the keys (they can obviously read the nix store) and also I keep my [nixos configs](github.com/pinpox/nixos) in public repository, which currently would expose the secret to the world.

>  So next best option is to have a config.ini.template in /etc/sr.ht and a service that fills in the details imperatively into the actual config.ini from non-nix-store'd files prior to services starting?

I think this is the way to go, there are other examples of modules doing this in nixpgks, I think [the mattermost module](https://github.com/NixOS/nixpkgs/blob/e9148dc1c30e02aae80cc52f68ceb37b772066f3/nixos/modules/services/web-apps/mattermost.nix#L178) does something similar.

**Comment by pinpox** [comment]
@tomberek Another option that would be possible without too much rework: 

We could just add an option to use a predefined settings file. In addition to to `services.sourcehut.settings` there could be a `services.sourcehut.configFilePath` or similar that just allows to use a static file as configuration. The `settings` and `configFilePath` options would be mutually exclusive.

**Comment by tomberek** [comment]
Being worked on in 133984.
