### ISSUE TITLE
Linker failures when building Haskell libraries on macos

### ISSUE THREAD

**Issue by d12frosted** [NixOS/nixpkgs#126042]
**Describe the bug**
Whenever I use `nix-build` to build Haskell project with a library I get the following linker failures:

```
impure path `/private/tmp/nix-build-haskell-nix-test-0.1.0.0.drv-0/ghc38817_0/ghc_8.filelist' used in link

<no location info>: error:
    `ld' failed in phase `Merge objects'. (Exit code: 1)
```

[Full build.log](https://github.com/NixOS/nixpkgs/files/6606175/build.log)

**To Reproduce**
1. clone https://github.com/d12frosted/haskell-nix-test 
2. `nix-build release.nix`

**Expected behavior**
Everything builds fine.

**Additional context**

Labels: macos, haskell

I noticed that everything is fine when I build an application produced by `cabal init`, e.g. there is no library. And it works on Ubuntu and Arch Linux. I have this problem on a fresh macos install (untouched by brew). 

**Notify maintainers**

**Metadata**
```
$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/8lhb79fg4n70ixlll090wqlnzd2ahbd8-nix-info
  /nix/store/s9r8s3zidsjgsb63l05453g0wsjgqn89-DarwinTools-1
copying path '/nix/store/s9r8s3zidsjgsb63l05453g0wsjgqn89-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/8lhb79fg4n70ixlll090wqlnzd2ahbd8-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(d12frosted): `"unstable-21.11pre294098.4df31757808"`
 - channels(root): `"nixpkgs-21.11pre293858.141b2b111d7"`
 - nixpkgs: `/Users/d12frosted/.nix-defexpr/channels_root/nixpkgs`
```

**Invalid OS version detected**. Output says that I am on macOS 10.16, but in reality I am on 11.4.

<img width="586" alt="Screenshot 2021-06-07 at 08 55 23" src="https://user-images.githubusercontent.com/6507913/120965965-35ed3480-c76e-11eb-85b4-1d1a8b130a5c.png">

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by madjar** [comment]
I have the same problem, possibly after upgrading to Big Sur.

I had an instinct that this might be due to having a stdenv or a ghc built in a previous version, so I went ahead and recompiled everything from scratch. Result: Building ghc fails (`'clang' failed in phase 'Linker'. (Exit code: 1)`, `ld: library not found for -lHSterminfo-0.4.1.4`). I don't really know what to do with that information, but it's likely related.

**Comment by madjar** [comment]
@d12frosted I just tried with stable nix (2.3.12), and it works. Can you confirm that it's the case for you as well? If so, then it might be a nixUnstable problem.

**Comment by d12frosted** [comment]
I was on `nix-env (Nix) 2.4pre20210601_5985b8b`, let me upgrade to latest unstable and see if it's still the case.

**Comment by d12frosted** [comment]
> If so, then it might be a nixUnstable problem.

Sorry missed this part. Might be the issue with nixUnstable, but not sure how to downgrade - I am managing my env using flakes and once I try to go down, I can't build my env. Will try again later.

**Comment by sternenseemann** [comment]
cc @siraben who ran into this before, iirc that was an impurity problem.

**Comment by d12frosted** [comment]
Hey @siraben, apologies for late reply, I was in travel mode.

So my `PATH` is:

```
/Users/d12frosted/.config/bin /Users/d12frosted/.local/bin /Users/d12frosted/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Users/d12frosted/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin
```

I specifically append few things to the `PATH` to make sure that my scripts are available :) But for sanity of the experiment, I tried building with the following `PATH`:

```
/Users/d12frosted/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Users/d12frosted/.nix-profile/bin /run/current-system/sw/bin /nix/var/nix/profiles/default/bin
```

And it worked 🤔

**Comment by d12frosted** [comment]
Disregard, it works even with original `PATH`. Not sure if I have changed anything, I think I have updated everything somewhere during the last month and maybe that fixed. 🤷 Alright, in any case now everything works with real world application and I am very happy about it. So let me close this issue.

Thanks everyone for inputs and help! Really appreciate 🙏

**Comment by siraben** [comment]
In my case I fixed the issue by reinstalling macOS 😂

**Comment by d12frosted** [comment]
Funnily, I tried that method and it didn't work for me. At least now I have a very clean system. 😅
