### ISSUE TITLE
Protonmail bridge

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#126167]
### Project description

Thing used to get protonmail SMTP and IMAP ports for thunderbird

### Metadata

* homepage URL: https://protonmail.com/bridge
* source URL: https://github.com/ProtonMail/proton-bridge
* license: GPLv3
* platforms: UNIX, Windows

**Comment by OPNA2608** [comment]
Already packaged, [pkgs/applications/networking/protonmail-bridge](https://github.com/NixOS/nixpkgs/blob/c5bff358e90389c33ce3cfb23facc5e660fe82b8/pkgs/applications/networking/protonmail-bridge/default.nix).
