### ISSUE TITLE
git-cola: cannot invoke rebase editor from within git-cola

### ISSUE THREAD

**Issue by DeeUnderscore** [NixOS/nixpkgs#126131]
**Describe the bug**
Attempting to start a rebase from within the main Git Cola window fails as it tries to invoke the rebase editor.  

**To Reproduce**
1. Open a git repo in git cola (do `git cola` from inside the repo in a terminal)
2. From the "Rebase" menu, pick "Start Interactive Rebase"
3. Put in some commit in the dialog that comes up and hit "Interactive Rebase"

**Expected behavior**
The interactive rebase editor should come up.

**Screenshots**
A dialog with an error comes up. Sample output:

```
  File "/nix/store/gxcpzn8cxkb7wp2qfai82fxmgm6rz0p8-git-cola-3.9/bin/git-cola-sequence-editor", line 2
    export PATH='/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/bin:/nix/store/gxcpzn8cxkb7wp2qfai82fxmgm6rz0p8-git-cola-3.9/bin:/nix/store/d744nl0pgfbn7js67m05khw8s37b19kg-qtdeclarative-5.15.2-bin/bin:/nix/store/yjqhiza14nxf483x9w9i1szigq88qil2-python3.8-PyQt5-5.15.2/bin:/nix/store/v2hnf19gkrjr0z4gxkii1bzcczd5insa-python3.8-sip-4.19.25/bin'${PATH:+':'}$PATH
           ^
SyntaxError: invalid syntax
error: There was a problem with the editor '/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/bin/python3.8 /nix/store/gxcpzn8cxkb7wp2qfai82fxmgm6rz0p8-git-cola-3.9/bin/git-cola-sequence-editor'.
```

**Additional context**
As of [v3.8](https://github.com/git-cola/git-cola/blob/main/CHANGES.rst#packaging-1), Git Cola now ships `git-cola-sequence-editor` as a script in its `bin/` output. This makes it easy to use the interactive editor without the main Git Cola app; you can do `GIT_SEQUENCE_EDITOR='git-cola-sequence-editor' git rebase --interactive …` from the command line and use the editor this way (this currently works with NixOS).

Seems like the `git-cola-sequence-editor` is getting wrapped, though, and Git Cola expects it to be a bare Python script. 

**Notify maintainers**
@bobvanderlinden

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.650.eaba7870ffc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixos-21.05.650.eaba7870ffc"`
 - channels(d): `"home-manager-21.05, nixos-21.05.650.eaba7870ffc, nixos-unstable-21.11pre293089.1c2986bbb80"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bobvanderlinden** [comment]
@DeeUnderscore I also used the patch in https://github.com/NixOS/nixpkgs/pull/126170, can you give that a try and see whether it fixes your issue?

**Comment by bobvanderlinden** [comment]
https://github.com/git-cola/git-cola/pull/1143 fixes the problem and is merged. The latest version is available in Nix due to https://github.com/NixOS/nixpkgs/pull/129987.

The problem seems solved on my machine.

**Comment by DeeUnderscore** [comment]
Yep, that seems to have solved it. Thanks!
