### ISSUE TITLE
[BOUNTY] Mesa 21.X breaks steam and 3D rendering in wine (native works) on nix-latest

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#126189]
```console
[kreyren@leonid:~]$ DRI_PRIME=1 wine /usr/games/SuperTuxKart\ 1.2.0/supertuxkart.exe   
 wine: created the configuration directory '/home/kreyren/.wine'
 ...
 wine: configuration in L"/home/kreyren/.wine" has been updated.
 ...
 ..:: Antarctica Rendering Engine 2.0 ::..
 016c:fixme:win:RegisterTouchWindow (0000000000090062 00000003): stub
 X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  263
  Current serial number in output stream:  263
```

Full log: https://gist.github.com/Kreyren/27c645d54dd5728640fb3c43fb3f81bb

### Steps To Reproduce
0. Install `wine` and install any 3D-capable windows application e.g. SuperTuxKart (https://github.com/supertuxkart) 
1. Try to open that application in nixOS's wine and expect failure

### Expected behavior
WineD3D should work out of the box using the pre-compiled binary

### Metadata
_Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result._

```console
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.804.5de44c15758"`
 - channels(kreyren): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

![image](https://user-images.githubusercontent.com/11302521/121165977-f8150c80-c850-11eb-98a7-70fb2a102f2c.png)

**Comment by Kreyren** [comment]
CC @avnik @raskin @bendlas 

https://github.com/NixOS/nixpkgs/blob/8284fc30c84ea47e63209d1a892aca1dfcd6bdf3/pkgs/misc/emulators/wine/base.nix#L153

**Comment by avnik** [comment]
That actually not wine, but opengl problem.
```
   export MESA_GL_VERSION_OVERRIDE=4.5
```
should workaround this. (see https://bugs.winehq.org/show_bug.cgi?id=50859, and https://gitlab.freedesktop.org/mesa/mesa/-/issues/3969 if you like to know details).

Is fixed in next mesa release.
Integrate following snippet to your config to fix it permanently (keep it until nixpkgs not get 21.1 mesa or newer, which has fix merged)
(this upgrade mesa (only drivers part))
```
let
   mesa_version = "21.1.0";
   mesa_src = pkgs.fetchurl {
     url = "https://mesa.freedesktop.org/archive/mesa-${mesa_version}.tar.xz";
     sha256 = "1y0z3ff685ql2l3pqyfrbh0j6ipr64vh0d0h7pnkl3cp487g2a01";
   };
   mesa_21_1 = pkgs.mesa.overrideAttrs (a: { src = mesa_src; version = mesa_version; patches = sublist 1 2 a.patches; });
   mesa_21_1_32 = pkgs.pkgsi686Linux.mesa.overrideAttrs (a: { src = mesa_src; version = mesa_version; patches = sublist 1 2 a.patches; });
 in
{
    hardware = {
        opengl = {
           driSupport32Bit = true;
           package = mkForce mesa_21_1.drivers;
           package32 = mkForce mesa_21_1_32.drivers;
        };
   };
}

**Comment by Kreyren** [comment]
The `export MESA_GL_VERSION_OVERRIDE=4.5` is giving me a window, but the 
3D rendering is still broken.

```console
[kreyren@leonid:~]$ export MESA_GL_VERSION_OVERRIDE=4.5

[kreyren@leonid:~]$ DRI_PRIME=1 wine /usr/games/SuperTuxKart\ 1.2.0/supertuxkart.exe
...
[info   ] SharedGPUObjects: Hardware Skinning enabled, method: TBO, max bones: 1024
[info   ] ShaderFilesManager: Compiling shader: Z:/usr/games/SuperTuxKart 1.2.0/data/sta
[error  ] ShaderFilesManager: Error in shader Z:/usr/games/SuperTuxKart 1.2.0/data/shate
[error  ] ShaderFilesManager: 0:1(10): error: GLSL 4.50 is not supported. Supported veSs

[info   ] ShaderFilesManager: Compiling shader: Z:/usr/games/SuperTuxKart 1.2.0/data/sga
[error  ] ShaderFilesManager: Error in shader Z:/usr/games/SuperTuxKart 1.2.0/data/shage
[error  ] ShaderFilesManager: 0:1(10): error: GLSL 4.50 is not supported. Supported veSs

[error  ] Shader: Error when linking these shaders :
[error  ] shader: screenquad.vert
[error  ] shader: motion_blur.frag
[error  ] Shader: error: no shaders attached to the program

[info   ] ShaderFilesManager: Compiling shader: Z:/usr/games/SuperTuxKart 1.2.0/data/sga
[error  ] ShaderFilesManager: Error in shader Z:/usr/games/SuperTuxKart 1.2.0/data/shage
[error  ] ShaderFilesManager: 0:1(10): error: GLSL 4.50 is not supported. Supported veSs
...
```

Full log: https://gist.githubusercontent.com/Kreyren/ad5eecb1fba0aba83d72deb903fcb25c/raw/a0264855be98449d3d9bda87136c7e0bbb57d024/gistfile1.txt

Details noted

Didn't update the `configuration.nix` since the export doesn't workaround it?

**Comment by avnik** [comment]
Well, IDK about nvidia/non-free drivers. For AMD it was fixed by environment or driver update. 

PS But I can explain what happens on log above -- wine try to open GL context with each version. Exporting variable bypass this check, but  it doesn't help if your GLSL only 4.30 for example.  (exporting 4.30 not helps, because it still try versions above)

**Comment by Kreyren** [comment]
I have AMD Radeon HD 6550M and i am not aware of running non-free drivers:

```console
[kreyren@leonid:~]$ DRI_PRIME=1 glxinfo | grep OpenGL\ ren
OpenGL renderer string: AMD TURKS (DRM 2.50.0 / 5.10.40, LLVM 11.1.0)
[kreyren@leonid:~]$ lsmod | grep radeon
radeon               1609728  1
ttm                    98304  1 radeon
drm_kms_helper        212992  2 radeon,i915
i2c_algo_bit           16384  2 radeon,i915
drm                   507904  13 drm_kms_helper,radeon,i915,ttm
backlight              20480  5 video,radeon,ideapad_laptop,i915,drm
i2c_core               86016  11 videodev,drm_kms_helper,i2c_algo_bit,at24,i2c_smbus,radeon,i2c_i801,i915,psmouse,regmap_i2c,drm
```

Noted the cause will try the driver update

**Comment by Kreyren** [comment]
```nix
# HOTFIX(Krey): https://github.com/NixOS/nixpkgs/issues/126189#issuecomment-856686989

{ config, pkgs, lib, ... }:

let
   mesa_version = "21.1.0";
   mesa_src = pkgs.fetchurl {
     url = "https://mesa.freedesktop.org/archive/mesa-${mesa_version}.tar.xz";
     sha256 = "1y0z3ff685ql2l3pqyfrbh0j6ipr64vh0d0h7pnkl3cp487g2a01";
   };
   mesa_21_1 = pkgs.mesa.overrideAttrs (a: { src = mesa_src; version = mesa_version; patches = lib.sublist 1 2 a.patches; });
   mesa_21_1_32 = pkgs.pkgsi686Linux.mesa.overrideAttrs (a: { src = mesa_src; version = mesa_version; patches = lib.sublist 1 2 a.patches; });
 in
{
    hardware = {
        opengl = {
           driSupport32Bit = true;
           package = lib.mkForce mesa_21_1.drivers;
           package32 = lib.mkForce mesa_21_1_32.drivers;
        };
   };
}
```

FWIW Updated the nix config as it was failing to build

**Comment by Kreyren** [comment]
Finished building mesa, it works now! ^-^

**Comment by avnik** [comment]
Good to hear (I just was sure that DRI_PRIME is nvidia stuff).
I have same AMD TURKS 
Probably we need to ask maintainers of mesa to update to 21.1

**Comment by Kreyren** [comment]
CC @primeos @vcunat

**Comment by vcunat** [comment]
`staging-next` branch has already switched to mesa-21.1.2.  I'd expect it will land in the unstable channel in about a week.

**Comment by vcunat** [comment]
I see you are using 21.05 (which is only stable now).  We already do consider backporting the change to 21.05 some time afterwards, due to the current version causing relatively lots of problems (apparently).

**Comment by Kreyren** [comment]
FWIW i am not comfortable on unstable with this setup so sooner the stable is stable the better for me.

**Comment by Kreyren** [comment]
Using the provided patch in https://github.com/NixOS/nixpkgs/issues/126189#issuecomment-857517576 breaks radeon drivers on my system, see https://github.com/NixOS/nixpkgs/issues/126482

CC @avnik @vcunat

**Comment by Kreyren** [comment]
Also breaks steam

```
libGL error: MESA-LOADER: failed to open i965: /run/opengl-driver-32/lib/dri/i965_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver-32/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open i965: /run/opengl-driver-32/lib/dri/i965_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver-32/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast: /run/opengl-driver-32/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver-32/lib/dri)
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  152
Serial number of failed request:  49
xerror_handler: X failed, continuing
assert_20210611201132_1.dmp[8145]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210611201132_1.dmp
/home/kreyren/.local/share/Steam/steam.sh: line 772:  8139 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
assert_20210611201132_1.dmp[8145]: Finished uploading minidump (out-of-process): success = yes
assert_20210611201132_1.dmp[8145]: response: CrashID=bp-328ac7f1-d854-41ce-bcac-c71c02210611
assert_20210611201132_1.dmp[8145]: file ''/tmp/dumps/assert_20210611201132_1.dmp'', upload yes: ''CrashID=bp-328ac7f1-d854-41ce-bcac-c71c02210611''
```

Full log: http://ix.io/3pBh

**Comment by Kreyren** [comment]
Submitted a bug bounty on 7.99 USD

https://www.bountysource.com/issues/99123727-mesa-21-x-breaks-steam-and-3d-rendering-in-wine-native-works-on-nix-latest

**Comment by vcunat** [comment]
`@primeos` encountered some issues when overriding mesa, I think (i.e. using different version during run-time than during build-time), but maybe you're running into something else.  You might want to try the current staging-next branch; it's not missing that many binaries on cache.nixos.org now (for linux).

**Comment by vcunat** [comment]
For example:
```bash
sudo nixos-rebuild -I nixpkgs=https://github.com/nixos/nixpkgs/archive/staging-next.tar.gz boot -Q
```
(suggesting `boot` instead of `switch`, as you probably want to reboot for this anyway)

**Comment by avnik** [comment]
Overriden works for me (21.1.2 ATM), but I have master as base version (~week ago)

**Comment by Kreyren** [comment]
```console
[kreyren@leonid:~]$ DRI_PRIME=1 glxinfo | grep OpenGL\ ren
OpenGL renderer string: llvmpipe (LLVM 11.1.0, 256 bits)
```

Doesn't seem to work with the mesa deployed using:

```nix
{ pkgs, ... }: {
  hardware.opengl = let
    new-nixpkgs = builtins.fetchGit { url = "https://github.com/nixos/nixpkgs"; ref = "staging-next"; };
    new-pkgs = import new-nixpkgs {};
  in {
    package = new-pkgs.mesa.drivers;
    package32 = new-pkgs.pkgsi686Linux.mesa.drivers;
  };
}
```

**Comment by avnik** [comment]
IDK, if DRI_PRIME is a source of problem (I have similar TURKS video chip, but is a primary VGA for my computer)

**Comment by Kreyren** [comment]
> IDK, if DRI_PRIME is a source of problem (I have similar TURKS video chip, but is a primary VGA for my computer) @avnik 

FWIW this system always required `DRI_PRIME` to use the dedicated GPU and it works without patches in linux version of supertuxkart (wine and steam broken)

**Comment by primeos** [comment]
Regarding https://github.com/NixOS/nixpkgs/issues/126189#issuecomment-859791667: I've recently started documenting this in the NixOS wiki: https://nixos.wiki/wiki/OpenGL. If these issues are caused by `hardware.opengl.package` then switching to the other approach using `system.replaceRuntimeDependencies` should help.

@Kreyren using `LIBGL_DEBUG=verbose` should give you a more meaningful output regarding the `MESA-LOADER` errors (s. https://github.com/NixOS/nixpkgs/issues/94315#issuecomment-667942575 for an example).

**Comment by Kreyren** [comment]
> @Kreyren using LIBGL_DEBUG=verbose should give you a more meaningful output regarding the MESA-LOADER errors (s. #94315 (comment) for an example). @primeos

```console
[kreyren@leonid:~/Desktop]$ LIBGL_DEBUG=verbose steam |& ix
http://ix.io/3pHs
```

**Comment by Kreyren** [comment]
```console
[kreyren@leonid:/etc/nixos/bugs/nixos/nixpkgs]$ ls -la /run/opengl-driver*
lrwxrwxrwx 1 root root 58 Jun 12 17:20 /run/opengl-driver -> /nix/store/jksm5hd5xr4fvzds5s3hwk6lvjhhdymq-opengl-drive
```

Seems that way?

**Comment by Kreyren** [comment]
```nix
# HOTFIX(Krey): https://github.com/NixOS/nixpkgs/issues/126189#issuecomment-860030365

{ pkgs, ... }: {
	hardware.opengl.package = (import /opt/nixpkgs-mesa { }).pkgs.mesa.drivers;

	system.replaceRuntimeDependencies = [
		({ original = pkgs.mesa; replacement = (import /opt/nixpkgs-mesa { }).pkgs.mesa; })
		({ original = pkgs.mesa.drivers; replacement = (import /opt/nixpkgs-mesa { }).pkgs.mesa.drivers; })
	];
}
```

> Regarding #126189 (comment): I've recently started documenting this in the NixOS wiki: https://nixos.wiki/wiki/OpenGL. If these issues are caused by hardware.opengl.package then switching to the other approach using system.replaceRuntimeDependencies should help. @primeos 

Can you elaborate? I am not sure how to integrate that

**Comment by primeos** [comment]
> error: getting status of '/opt/nixpkgs-mesa': No such file or directory

There you have your issue ;)
Also: Please don't make edits in the NixOS wiki if you don't understand how this works (and Nix isn't FHS compliant too btw...).

In your case you might want to use something like the following instead of the local path:
```
    new-nixpkgs = builtins.fetchGit { url = "https://github.com/nixos/nixpkgs"; ref = "staging-next"; };
    new-pkgs = import new-nixpkgs {};
```

**Comment by avnik** [comment]
@Kreyren  on my system:
```
[avn@bulldozer:pts/2]~/nixos/configs% ls -la /run/opengl-driver*                                                                                                               0 lrwxrwxrwx 1 root root 58 Jun  9 14:23 /run/opengl-driver -> /nix/store/rw4xjh1jldm3ai2yrbk2bds9x9xi4i9a-opengl-drivers
0 lrwxrwxrwx 1 root root 64 Jun  9 14:23 /run/opengl-driver-32 -> /nix/store/kjh7dnly91m8p2czlmdx5c5i1pv0n4ms-opengl-drivers-32bit
```

So looks like you miss 32bit drivers, and steam requires them

**Comment by Kreyren** [comment]
> There you have your issue ;)
Also: Please don't make edits in the NixOS wiki if you don't understand how this works (and Nix isn't FHS compliant too btw...). @primeos

Oh sorry!

created:

```nix
{ pkgs, ... }: {
	hardware.opengl = let
		new-nixpkgs = builtins.fetchGit { url = "https://github.com/nixos/nixpkgs"; ref = "staging-next"; };
		new-pkgs = import new-nixpkgs {};
	in {
		package = (import /srv/nixpkgs-mesa { }).pkgs.mesa.driversv;
		package32 = new-pkgs.pkgsi686Linux.mesa.drivers;
	};
	system.replaceRuntimeDependencies = [
		({ original = pkgs.mesa; replacement = (import /srv/nixpkgs-mesa { }).pkgs.mesa; })
		({ original = pkgs.mesa.drivers; replacement = (import /srv/nixpkgs-mesa { }).pkgs.mesa.drivers; })
	];
}
```

but still getting

```console
[kreyren@leonid:~]$ sudo nixos-rebuild switch
building Nix...
building the system configuration...
error: getting status of '/srv/nixpkgs-mesa': No such file or directory
(use '--show-trace' to show detailed location information)
```

**Comment by Kreyren** [comment]
> So looks like you miss 32bit drivers, and steam requires them @avnik 

I don't know how to get 32-bit packages, can you elaborate?

**Comment by primeos** [comment]
Something like this (might have to fix evaluation errors / typos):
```nix
{ pkgs, ... }: 
let
  new-nixpkgs = builtins.fetchGit { url = "https://github.com/nixos/nixpkgs"; ref = "staging-next"; };
  new-pkgs = import new-nixpkgs {};
in {
	system.replaceRuntimeDependencies = [
		({ original = pkgs.mesa; replacement = new-pkgs.pkgs.mesa; })
		({ original = pkgs.mesa.drivers; replacement = new-pkgs.pkgs.mesa.drivers; })
	];
}
```

For the 32 bit drivers (AFAIK): `hardware.opengl.driSupport32Bit = true;` (see `man configuration.nix`)

Due to time constrains / other tasks I likely won't be able to reply again, sorry.

**Comment by Kreyren** [comment]
That seems to fix the rendering in wine: http://ix.io/3pIz and steam also works now http://ix.io/3pIA

**Comment by Kreyren** [comment]
I've removed the provided patch and only kept the `hardware.opengl.driSupport32Bit = true;` which fixed steam http://ix.io/3pID

CC @jagajaga @jonringer : Steam should probably be packaged with 32-bit libs

**Comment by Kreyren** [comment]
FWIW i tried `Batman: Arkham City` downloaded from torrent (steam version also doesn't work) which gives me:

```console
[kreyren@leonid:~]$ DRI_PRIME=1 GALLIUM_HUD="simple,fps" wine /usr/games/batman-arkham-city/Binaries/Win32/BatmanAC.exe
0054:err:system:ChangeDisplaySettingsExW Changing L"\\\\.\\DISPLAY1" display settings returned -2.
0054:err:explorer:initialize_display_settings Failed to initialize registry display settings for L"\\\\.\\DISPLAY1".
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:gameux:GameExplorerImpl_VerifyAccess (001592E8, L"Z:\\usr\\games\\batman-arkham-city\\Binaries\\Win32\\BatmanAC.exe", 0031F538)
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  224
  Current serial number in output stream:  224
  ```

**Comment by jonringer** [comment]
> I've removed the provided patch and only kept the `hardware.opengl.driSupport32Bit = true;` which fixed steam http://ix.io/3pID, wine http://ix.io/3pIF is broken without it.
> 
> CC @jagajaga @jonringer : Steam should probably be packaged with 32-bit libs

It is:
```
      # nixos/modules/programs/steam.nix
      hardware.opengl = { # this fixes the "glXChooseVisual failed" bug, context: https://github.com/NixOS/nixpkgs/issues/    47932
        enable = true;
        driSupport = true;
        driSupport32Bit = true;
      };
 ```

**Comment by Kreyren** [comment]
@jonringer I meant that it allows to install it without the 32-bit libs that results in:

```
/home/kreyren/.local/share/Steam/steam.sh: line 772:  8139 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
```

So i think that making it to fail if 32-bit is not enabled is sane?

**Comment by Artturin** [comment]
> @jonringer I meant that it allows to install it without the 32-bit libs that results in:
> 
> ```
> /home/kreyren/.local/share/Steam/steam.sh: line 772:  8139 Segmentation fault      (core dumped) $STEAM_DEBUGGER $DEBUGGER_ARGS "$STEAMROOT/$STEAMEXEPATH" "$@"
> ```
> 
> So i think that making it to fail if 32-bit is not enabled is sane?

There is already a steam module that needs to be enabled to be able to use steam.

**Comment by Kreyren** [comment]
See https://github.com/NixOS/nixpkgs/issues/129915#issuecomment-877867240 assuming solved as the patches are no longer needed
