### ISSUE TITLE
Request: jobber

### ISSUE THREAD

**Issue by amacfie** [NixOS/nixpkgs#126268]
**Project description**
Jobber is a "modern" replacement for cron, with sophisticated status-reporting and error-handling, and simpler configuration.

**Metadata**

* homepage URL: https://dshearer.github.io/jobber/
* source URL: https://github.com/dshearer/jobber
* license: mit
* platforms: "Unix-like systems"

**Comment by ethancedwards8** [comment]
So this would also require a module I assume.

**Comment by AndersonTorres** [comment]
In a certain sense the module can be delegated for later.

**Comment by bensleveritt** [comment]
I'd like this! I've never contributed to Nixpkgs before... so I might be able to do this

**Comment by AndersonTorres** [comment]
Go for it, man!
