### ISSUE TITLE
nixos-rebuild switch fails

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#12629]
I'm on `nixos-unstable-small`. I've updated channel and run `nixos-rebuild switch`:

```
[root@nixos-master:~]# nixos-rebuild switch
building Nix...
error: getting status of вЂ/nix/store/x65bfds89675b1sgy6zn7k9msjbh19zc-modules/virtualisation/amazon-config.nixвЂ™: No such file or directory
(use вЂ--show-traceвЂ™ to show detailed location information)
error: getting status of вЂ/nix/store/x65bfds89675b1sgy6zn7k9msjbh19zc-modules/virtualisation/amazon-config.nixвЂ™: No such file or directory
(use вЂ--show-traceвЂ™ to show detailed location information)
error: evaluation aborted with the following error message: вЂThis version of Nixpkgs requires Nix >= 1.10, please upgrade! See https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_NixpkgsвЂ™
/nix/store/pv978avci7km39zb4hi1p9gin3ys03r4-nixos-16.03pre75763.bf605c1/nixos/nixpkgs/nixos/modules/installer/tools/nixos-rebuild.sh: line 259: return: /nix/store/xryr9g56h8yjddp89d6dw12anyb4ch7c-nix-1.10: numeric argument required
```

1. Seems like it cannot build `nix`. 
2. The help message is wrong: `nixos-rebuild` doesn't use `nix` from environment, so installing it won't help in this case (`nixos-rebuild` uses hardcoded nix-1.9)
3. Any way to upgrade the system?

**Comment by pSub** [comment]
Have you followed the advice in the error message and looked at https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_Nixpkgs ?

**Comment by danbst** [comment]
Yes.
1. Evaluating `curl -L https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.nix.x86_64-linux/latest-finished/nix/pkg/nix-1.10-x86_64-linux.nixpkg \
   | nix-install-package --non-interactive -` installed nix-1.10 into root environment, but `nixos-rebuild` doesn't use nix from environment, it uses hardcoded `nix-1.9`.
2. It halts during building newer nix, but shouldn't. I think, this is a backward-incompatible regression
3. As for `_NIXOS_REBUILD_REEXEC `, I do not quite understand what does it do (has no manual)

**Comment by heydojo** [comment]
what does
```
system.stateVersion
```
in configuration.nix equal?
Thanks

**Comment by danbst** [comment]
> what does
>  system.stateVersion
> in configuration.nix equal?

It is not set in configuration.nix:
```
{ config, pkgs, ...}:
{
  imports = [
    ./amazon-base-config.nix
  ];
  ec2.hvm = true;
}
```

`/etc/nixos/amazon-base-config.nix` contains:
```
{ modulesPath, ...}:
{
  imports = [ "${modulesPath}/virtualisation/amazon-config.nix" ];
  services.journald.rateLimitBurst = 0;
}
```
When I remove the import of disappeared amazon-config.nix, I have the following output:
```
[root@nixos-master:~]# nixos-rebuild switch
building Nix...
error: evaluation aborted with the following error message: вЂThis version of Nixpkgs requires Nix >= 1.10, please upgrade! See https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_NixpkgsвЂ™
(use вЂ--show-traceвЂ™ to show detailed location information)
error: evaluation aborted with the following error message: вЂThis version of Nixpkgs requires Nix >= 1.10, please upgrade! See https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_NixpkgsвЂ™
(use вЂ--show-traceвЂ™ to show detailed location information)
error: evaluation aborted with the following error message: вЂThis version of Nixpkgs requires Nix >= 1.10, please upgrade! See https://nixos.org/wiki/How_to_update_when_Nix_is_too_old_to_evaluate_NixpkgsвЂ™
/nix/store/pv978avci7km39zb4hi1p9gin3ys03r4-nixos-16.03pre75763.bf605c1/nixos/nixpkgs/nixos/modules/installer/tools/nixos-rebuild.sh: line 259: return: /nix/store/xryr9g56h8yjddp89d6dw12anyb4ch7c-nix-1.10: numeric argument required
```

My $NIX_PATH is `/nix/var/nix/profiles/per-user/root/channels/nixos:nixpkgs=/etc/nixos/nixpkgs:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels`
and channels are 
```
[root@nixos-master:~]# nix-channel --list
nixos https://nixos.org/channels/nixos-unstable-small
```

I've used `nix-collect-garbage -d` often before that and several times hit https://github.com/NixOS/nix/issues/575

**Comment by danbst** [comment]
I've found a way to rebuild the system. Added 

```
/nix/store/aibd0vvcjmi1mvvccnibpaccxkf5ls63-nixos-15.07pre67133.23257cb/nixos/nixos/modules/virtualisation/amazon-config.nix
```
to import list and run
```
_NIXOS_REBUILD_REEXEC=1 nixos-rebuild switch
```
Note, that my `${modulesPath}` refers to `/etc/nixos/x65bfds89675b1sgy6zn7k9msjbh19zc-modules`

Should I close this github issue, or this is definitely a bug?

**Comment by danbst** [comment]
closing this, as nobody seem to be interested and I have no time to reproduce this again
