### ISSUE TITLE
StumpVM does not have a documentation on the wiki

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#126240]

**Comment by evils** [comment]
the wiki is unofficial (not directly associated with this repository)

**Comment by Kreyren** [comment]
Is there any official documentation for packages then? Would like to contrib

**Comment by evils** [comment]
the official nixpkgs and nixos manuals have their source in this repo at `/doc` and `/nixos/doc`
if that is the right place for the documentation you'd contribute depends on that documentation

the wiki seems likely the more appropriate place, there shouldn't be anything stopping you from contributing there directly
