### ISSUE TITLE
Firefox 90 Dev Edition out-of-date for video-content websites

### ISSUE THREAD

**Issue by Tchekda** [NixOS/nixpkgs#126278]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: firefox-devedition-bin

current version: `85.0b6`
desired version: `90.0b4`

###### Notify maintainers

maintainers: @taku0 and @lovesegfault 

###### Note for maintainers

Please tag this issue in your PR.

## Request 

Netflix isn't working anymore with this version and is asking to be upgraded. The only way to update it is through nix but there is no update in `unstable` nor in current PRs.

If you need anything, I will do my best to help.

Best regards

**Comment by FliegendeWurst** [comment]
Current packaged version is 96.0b3.
