### ISSUE TITLE
Links does not support SSL

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#12623]
```This version of links does not contains SSL/TLS support. ```
I would like links to be compiled with SSL/TLS support on MacOSX.

**Comment by heydojo** [comment]
@aragnon you should install links2.
I just tried it and visited wikipedia using

```
links https://wikipedia.com/
```

The links package is really old and should really be removed. I think it might be there for historic reasons but I do not know exactly.

**Comment by fpletz** [comment]
@hydojo You're absolutely right. Debian removed links back in 2008: https://packages.qa.debian.org/l/links.html

**Comment by heydojo** [comment]
Looking at the format of default.nix it looks like it might have been the very first web browser built on NixOS.
History right there.

Thanks for cleaning this one up @fpletz!
