### ISSUE TITLE
uninitialized values $priority & $oldPriority

### ISSUE THREAD

**Issue by heydojo** [NixOS/nixpkgs#12635]
Since round about last week I have started to see a flood of :
```
Use of uninitialized value $priority in numeric lt (<) at /nix/store/1159mlcbp9wk2r9jvkq7z7gvz10wlbig-builder.pl line 87.
Use of uninitialized value $oldPriority in numeric gt (>) at /nix/store/1159mlcbp9wk2r9jvkq7z7gvz10wlbig-builder.pl line 94.
```
when ever I do a nixos-rebuild boot.
Is this a bug or is priority depreciated?

**Comment by abbradar** [comment]
I've seen it too today while building `steam` to test something. I haven't attempted to trace source of the problem yet.

**Comment by heydojo** [comment]
@abbradar Thanks

**Comment by vcunat** [comment]
That's some bug in `buildEnv`, I presume.

**Comment by abbradar** [comment]
Yes, this is buildEnv's builder. I tried to look inside it briefly, but Perl is not the language I'm fluent with. 

Offtop: if someone will take fixing this and have some time to spare then, please look at #4621. I have been forced to do manual partial re-creating of symlinks tree enough times it became pretty annoying. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by peti** [comment]
I have the same problem on my machine: `nix-env -u` spews lots of warnings about uninitialized priority variables. A fix would be very much appreciated.

**Comment by vcunat** [comment]
I think it must've been caused by merging PR #5096. /cc @aszlig & @domenkozar.

**Comment by aszlig** [comment]
@vcunat: I've messed that up during the rebase of #5096, fixing...
