### ISSUE TITLE
Investigate replacing makeWrapper shell script with an executable

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#1263]
Just capturing a discussion from #nixos IRC:

```
<shlevy> replace makeWrapper with a c program  [15:52]
<phreedom_> shlevy: now that may be more interesting  [15:53]
<shlevy> phreedom_: It would be really easy
<shlevy> But I suspect people will complain about the opacity of it all
<shlevy> Want to be able to cat the wrapper and see what it's doing to the env
<phreedom_> shlevy: you can always just replace the #!/bin/bash with
            #!/faster/wrapper  [15:54]
<phreedom_> i don't know how much you are going to save over sh
<phreedom_> it needs benchmarking
<shlevy> True
```

Before starting anywork, we should:

```
<phreedom_> ocharles: for example try benchmarking wrapped and non-wrapped app
            first
```

**Comment by domenkozar** [comment]
I would mostly need this for wrappers to preserve shell environment. Currently if I run `tox`, it wraps the tox executable in a bash script and it doesn't include current shell environment.

Current workaround is to use `source $(which tox)`

**Comment by wmertens** [comment]
See also the previous discussion at
http://lists.science.uu.nl/pipermail/nix-dev/2014-November/014984.html
where execline was proposed as an option...

**Comment by domenkozar** [comment]
Could we *somehow* include debugging info? Maybe in a separate file suffixed with `-info`

**Comment by wmertens** [comment]
Hmmm, I suppose we could make the bash script as well to aid in debugging...

**Comment by bjornfor** [comment]
-1. I don't think we should replace shell wrappers with C. We should make wrappers that match the language of the program they're wrapping (wrapper language == real prog language). I don't have any refs now, but there are problems with the current approach, and this is not solved by switching to C.

**Comment by ocharles** [comment]
I don't think a Github issue is the right place to capture this discussion - the mailing list would be better. I don't feel strongly about this, and would like to close the issue. Any objections?

**Comment by ocharles** [comment]
In fact, if you have objections let me know, but otherwise I will close this. Shoot first, ask questions later ;)

**Comment by Rizary** [comment]
Nfŕt


Sent from my Samsung device

-------- Original message --------
