### ISSUE TITLE
libsixel fork could act as the new upstream

### ISSUE THREAD

**Issue by danieldk** [NixOS/nixpkgs#126388]
**Describe the bug**
`libsixel` has been marked as insecure because it has two known CVEs and upstream has gone inactive (#111579). The project is forked by a new maintainer:

https://github.com/saitoha/libsixel/issues/154

If anyone is interested in this library, please consider switching the derivation to this new upstream (after vetting), and taking over maintainership of the derivation (since the original maintainer of the derivation is inactive).

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libsixel
```

**Comment by timsofteng** [comment]
+1

**Comment by Artturin** [comment]
done in 86682241081f7e291b8df454f60c0200b7f26050
