### ISSUE TITLE
termpdfpy is broken

### ISSUE THREAD

**Issue by pca006132** [NixOS/nixpkgs#126384]
**Describe the bug**

termpdfpy unable to run due to missing symbol:
```
$ termpdf.py test.pdf 
Traceback (most recent call last):
  File "/nix/store/72fs82gv91m6d0119233lby6phms0bna-termpdf.py-2019-10-03/bin/.termpdf.py-wrapped", line 55, in <module>
    import fitz
  File "/nix/store/vys3h1vxw2ha9a7345w33q1p1rlslasv-python3.8-pymupdf-1.18.0/lib/python3.8/site-packages/fitz/__init__.py", line 3, in <module>
    from fitz.fitz import *
  File "/nix/store/vys3h1vxw2ha9a7345w33q1p1rlslasv-python3.8-pymupdf-1.18.0/lib/python3.8/site-packages/fitz/fitz.py", line 18, in <module>
    from . import _fitz
ImportError: /nix/store/vys3h1vxw2ha9a7345w33q1p1rlslasv-python3.8-pymupdf-1.18.0/lib/python3.8/site-packages/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol: jpeg_resync_to_restart
```

It seems that others also faced this problem: [PyMuPDF#609](https://github.com/pymupdf/PyMuPDF/issues/609) but managed to fix it via running the [installation script](https://github.com/pymupdf/PyMuPDF/blob/master/installation/ubuntu/ubuntu_pymupdf.sh) which contains a specific line patching the MuPDF source before compilation:
```
# replace files in mupdf source
cp ../PyMuPDF/fitz/_config.h include/mupdf/fitz/config.h
``` 
and it seems that there is no such modification here in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pymupdf/default.nix

I did not test this so I'm not sure if this is the cause of the problem, just trying to bring some relevant information.

**To Reproduce**
1. Install termpdfpy by `nix-env -iA termpdfpy`
2. Run it with any pdf: `termpdf.py test.pdf`
3. Check the error message

**Expected behavior**
Run successfully.

**Additional context**

**Notify maintainers**

@teto 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.119, NixOS, 20.09.4242.cee3ca37c68 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(pca): `"home-manager-20.09, nixpkgs-20.09.4316.85ed11208f8, nixpkgs-unstable-21.11pre294396.3bc8e5cd23b"`
 - channels(root): `"nixos-20.09.4242.cee3ca37c68, nixpkgs-21.03pre243353.6d4b93323e7"`
 - nixpkgs: `/home/pca/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by teto** [comment]
@pca006132  you seem to have a good grasp of the situation and I dont think I can fix this anytime soon so feel free to submit a patch and assign it to me.

**Comment by pca006132** [comment]
> @pca006132 you seem to have a good grasp of the situation and I dont think I can fix this anytime soon so feel free to submit a patch and assign it to me.

I tried fixing it this afternoon but I cannot fix it. Things I tried:
1. Patching the `config.h` file via adding command to `postPatch`: Same error message.
2. Adding `HAVE_GLFW=no` to `makeFlags`: Same error message.
3. Modifying `makeFlags` to flags used in the shell script mentioned above: Compilation error, cannot find some header files from third-party libraries.

No idea now.

**Comment by RamKromberg** [comment]
a more minimal example:
`nix-shell -p python39Packages.pymupdf --run 'python -c "import fitz"'`

btw, be sure to try a more recent minor version. the current one is 1.18.14 and fixed a few bugs that might or might not be related.

**Comment by luhuaei** [comment]
Hi, I found the nixpkgs installed  `.so` file lost some library.
```
ldd result/lib/python3.9/site-packages/fitz/_fitz.cpython-39-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffff597e000)
        libc.so.6 => /nix/store/cvr0kjg2q7z2wwhjblx6c73rv422k8cm-glibc-2.33-47/lib/libc.so.6 (0x00007fc9c8cf0000)
        /nix/store/j5p0j1w27aqdzncpw73k95byvhh5prw2-glibc-2.33-47/lib64/ld-linux-x86-64.so.2 (0x00007fc9cb1ed000)
```

Same time, I download a pymupdf package from [archlinux repo](https://archlinux.org/packages/community/x86_64/python-pymupdf/) found
```
ldd _fitz.cpython-39-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffd673ea000)
        libjbig2dec.so.0 => not found
        libopenjp2.so.7 => not found
        libjpeg.so.8 => not found
        libfreetype.so.6 => not found
        libgumbo.so.1 => not found
        libpthread.so.0 => /nix/store/j5p0j1w27aqdzncpw73k95byvhh5prw2-glibc-2.33-47/lib/libpthread.so.0 (0x00007fcd96856000)
        libc.so.6 => /nix/store/j5p0j1w27aqdzncpw73k95byvhh5prw2-glibc-2.33-47/lib/libc.so.6 (0x00007fcd96691000)
        /nix/store/j5p0j1w27aqdzncpw73k95byvhh5prw2-glibc-2.33-47/lib64/ld-linux-x86-64.so.2 (0x00007fcd98ba8000)
```

Maybe our missing some dependencies linker.

**Comment by luhuaei** [comment]
the root reason is `setup.py` don't include nix support, so that swig don't add relativate libraries.

**Comment by luhuaei** [comment]
Now, this problem is solved.

**Comment by ihgann** [comment]
I'm getting this same error in both unstable and 22.05. Are we sure this was fixed?

**Comment by teto** [comment]
you would have to give better reproduction nstructions ` nix run nixpkgs/nixos-unstable#termpdfpy` runs fine. Have you checked `nix-env -q` ?
