### ISSUE TITLE
steam: needs networkmanager to avoid crash for some users

### ISSUE THREAD

**Issue by jbalme** [NixOS/nixpkgs#126381]
**Describe the bug**
Upstream bug https://github.com/ValveSoftware/steam-for-linux/issues/7813 which I've been hit with has been isolated to a dependency on 32-bit libnm (in `networkmanager`). Adding it to `extraLibraries` solves the problem for me.

Another workaround is to disable the "remember password" option, but this is rather undesirable :)

**Additional context**
Logs and other info are in the upstream bug report.

**Notify maintainers**

@jonringer 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.11.20210606.fbfb794 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05pre275232.29b0d4d0b60"`
 - channels(user): `"nixos-21.05pre277486.f5e8bdd07d1"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

(I use Flakes, so the old channels are not used.)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jonringer** [comment]
I use network manager by default, so I guess that was why this was working for me.

**Comment by jonringer** [comment]
This would have also fixed your issue: https://github.com/NixOS/nixpkgs/pull/120829/files

**Comment by jbalme** [comment]
> I use network manager by default, so I guess that was why this was working for me.

I use it as well so I have no idea why it didn't work before

~~Supposedly, according to  libnm is in the steam runtime but for some users it isn't being picked up (same with pipewire in #124308)~~

Nevermind, you seem to have found that out

**Comment by jonringer** [comment]
do you mind testing? 
```
nixpkgs-review pr 120829 --package steam
./results/steam/bin/steam
```

**Comment by RohanHart** [comment]
Confirming that my crash was fixed with ```(pkgs.steam.override { extraLibraries = pkgs: [ pkgs.networkmanager ]; })``` but not when merging https://github.com/NixOS/nixpkgs/pull/120829 with the libpipewire fix.

**Comment by jbalme** [comment]
According to https://github.com/ValveSoftware/steam-for-linux/issues/7832 this is due to a compatibility problem between Steam's bundled libnm and the host's networkmanager. Network configurations which the host's networkmanager understands, but not Steam's, causes a crash.

Steam's runtime is being updated to fix the problem upstream.

**Comment by jonringer** [comment]
> Steam's runtime is being updated to fix the problem upstream.

fun :), and thanks  for following up

**Comment by jonringer** [comment]
Assuming this is no longer an issue
