### ISSUE TITLE
writeShellScript rejects valid scripts that use extglob

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#126344]
**Describe the bug**

`writeShellScript` and `writeShellScriptBin`'s check phase runs the script with `${stdenv.shell} -n` which ignores all commands, including `shopt`, so any script that sets and uses extglob (an option that alters bash's syntax) is rejected, even if valid.

**To Reproduce**

1. Try to build the following derivation:

```nix
pkgs.writeShellScript "foo" ''
  shopt -s extglob
  echo @(foo|bar)
''
```

2. Get this error:

```
error: builder for '/nix/store/gqpa7fk8v7fr5zzl44l1brc0gc408ks0-foo.drv' failed with exit code 2;
       last 2 log lines:
       > /nix/store/d6yjx34nqr4x970dcy9rrnajsdvy9mp3-foo: line 3: syntax error near unexpected token `('
       > /nix/store/d6yjx34nqr4x970dcy9rrnajsdvy9mp3-foo: line 3: `echo @(foo|bar)'
```

**Expected behavior**

This is a valid bash script, so it probably shouldn't be rejected.

**Additional context**

I'm running into this problem because Home Manager's [bash module](https://github.com/nix-community/home-manager/blob/aa36e2d6b481a54b95fbddbecb76076e0f38eb89/modules/programs/bash.nix#L171) uses `writeShellScript` to write the user's initialisation files, and I happen to set and use extglob in my `.bashrc`.

Of course, an immediate solution would be to stop using `writeShellScript` there, but I'm wondering if this problem could arise in other situations.

**Notify maintainers**

It seems like @grwlf added `writeShellScriptBin` and then @deliciouslytyped added `writeShellScript`.
Also pinging @rycee

**Comment by deliciouslytyped** [comment]
Oh. It doesn't seem to be overridable.

**Comment by ncfavier** [comment]
Yeah, I'm not suggesting we change the interface.

Possible solutions I see:

- use `${stdenv.shell} -O extglob -n`. This makes the assumption that `stdenv.shell` is bash (by the way, why isn't this `runtimeShell`?), and might accept invalid scripts (but this is already the case anyway; `-n` is only a very primitive form of validation).
- remove the `checkPhase` altogether (I'm guessing people don't want this).
- make `writeTextFile` overridable.

**Comment by deliciouslytyped** [comment]
The reason changing the interface came to mind, is that the problem is that you need to parametrize over another thing. 
Overrides are another way to do this, but then the thing you want to parametrize should be reasonably accessible.

I don't know enough about internals to judge whether wrapping it in `makeOverridable` makes sense, but there doesn't seem to be a `.override` hanging off the result, so it wouldn't shadow anything. I think it could make sense to make writeTextFile overridable since that's the lynchpin and a lot of things are just wrappers around that.

Then, if I'm thinking about this correctly, you could override the `checkPhase` argument in an appropriate way.

**Comment by deliciouslytyped** [comment]
I forgot to finish this, this snippet proves override should work, note that I'm not a bash expert, but this seems to do the right thing:
```nix
with import <nixpkgs> {};
let
  wto = makeOverridable writeTextFile;

  writeShellScript = name: text:
    wto {
      inherit name;
      executable = true;
      text = ''
        #!${runtimeShell}
        ${text}
        '';
      checkPhase = ''
        ${stdenv.shell} -n $out
      '';
    };
in
  (writeShellScript "foo" ''
    shopt -s extglob
    echo @(foo|bar)
    '').override (old: builtins.trace old {
      checkPhase = ''
        export BASHOPTS
        shopt -s extglob
        ${old.checkPhase}     
        #shopt -u extglob\n
        '';
      })
```
