### ISSUE TITLE
Kernel rfkill interface changes in 5.11 requiring userspace fixes

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#126486]
As reported on https://mail.gnome.org/archives/distributor-list/2021-June/msg00000.html we need some patches:

In particular:

 * gnome-settings-daemon needs https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/232
 * bluetoothd needs https://patchwork.kernel.org/project/bluetooth/patch/20210503131210.90066-1-benjamin@sipsolutions.net/

cc @NixOS/gnome

**Comment by maxeaubrey** [comment]
At least for g-s-d we're already on 40.0.1, which seems to have the fix? Both commits referenced (!232, !234) are there, but maybe I'm misreading.

Not sure if we want to address bluetoothd with #127183, but regardless I have a commit ready.
dd168f3e848aec3fb5f02194efade1be23654561

**Comment by maxeaubrey** [comment]
Above is no longer necessary with 5.60. I'll open a bump for that instead.
