### ISSUE TITLE
Whatsapp for linux missing glib-networking

### ISSUE THREAD

**Issue by hqurve** [NixOS/nixpkgs#126485]
**Describe the bug**
Whatsapp for linux shows a blank page stating "TLS/SSL support not available; install glib-networking"

**To Reproduce**
1. Install whatsapp for linux
2. Launch it

**Screenshots**
![Screenshot from 2021-06-10 10-04-44](https://user-images.githubusercontent.com/53281855/121539037-4baf6380-c9d3-11eb-9ed5-fedf51fa59b5.png)

**Additional context**
I installed the package using `nox` however, I doubt that has anything to do with the problem

**Notify maintainers**
@wandersoncferreira 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.876.60cce7e5e1f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.876.60cce7e5e1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Kranzes** [comment]
have you tried enabling glib-networking like it asked you? like so `services.gnome.glib-networking.enable = true;`

**Comment by hqurve** [comment]
Just tried it (by adding it to my configuration file), same result.

**Comment by Kranzes** [comment]
> Just tried it (by adding it to my configuration file), same result.

a reboot or quitting x11/wayland might be needed...

**Comment by hqurve** [comment]
Thanks very much. Also, is there a location where solutions to problems like this can be found (beyond github's issue page)? I initally thought that it was a packaging issue since glib-networking was not a arguement for the package.

**Comment by hqurve** [comment]
Update: upon starting the application, it produces two errors
```
Settings: Key file does not have key “allow_permissions” in group “Network”
Settings: Key file does not have key “header_bar” in group “General”
```
And upon scanning the qr code,
```
Settings: Key file does not have key “allow_permissions” in group “Network”
```
get produced (again) and the interface freezes.

**Comment by hqurve** [comment]
Update update: I added the necessary keys to `~/.config/whatsapp-for-linux/settings.conf`and all the errors have disappeared, but the application still freezes upon scanning the qr code

**Comment by Kranzes** [comment]
i could try doing more testing but i cant even get anything to show up...
![image](https://user-images.githubusercontent.com/56614642/121608957-8b219280-ca5b-11eb-90fb-1de77bcbafaa.png)

**Comment by hqurve** [comment]
yes, thats exactly what happens after I scan the qrcode and resize the window (hence forcing a redraw)

**Comment by hqurve** [comment]
Okay, after downloading the source and modifying the uri to another website, the application works well. I believe that it is not a packaging issue and ill report the issue on the upstream repo

**Comment by jtojnar** [comment]
> I initally thought that it was a packaging issue since glib-networking was not a arguement for the package.

It is a packaging issue, see also https://github.com/NixOS/nixpkgs/pull/126591.

**Comment by hqurve** [comment]
> see also #126591.

Does the application work under with this PR?

Also, the application works when recompiled with a different URL, however, when navigating to web.whatsapp.com, the same issue persists.

**Comment by jtojnar** [comment]
That is just documentation PR.

**Comment by dmedinag** [comment]
I'm also experiencing this. This was not an issue when I was using Gnome, but now that I'm on lightdm+i3 this happens to me as well. My metadata:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.05.20210916.ebf419e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
The linked pr was merged
