### ISSUE TITLE
Requesting: CherryTree by Giuspen the latest version 99.37

### ISSUE THREAD

**Issue by cicildihar** [NixOS/nixpkgs#126457]
**Project description**
CherryTree by Giuspen, currently, we are using version 0.39.4, meanwhile the latest application is on 0.99.37. There's a weird jump of version from 0.39.4 to 0.99.13. I don't know why this happens.

**Metadata**

* homepage URL: https://www.giuspen.com/cherrytree/
* source URL: https://github.com/giuspen/cherrytree
* license: GPL3 +
* platforms: Linux

**Comment by OPNA2608** [comment]
Package request is the wrong issue type for this, Out-of-date package report would've been better.
![grafik](https://user-images.githubusercontent.com/23431373/121499661-e1e88700-c9dd-11eb-9f69-b3320f8692b9.png)

The package is sadly orphaned so there's no maintainer to ping for this.
