### ISSUE TITLE
Steam incorrectly inherits VK_ICD_FILENAMES

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#126428]
The default VK_ICD_FILENAMES ordering is mesa drivers, then nvidia, then amd.

The issue is that this causes issues for some users who have dedicated GPUs, and the wrong icd will be picked up. This can cause terrible performance, as it's likely that the wrong graphics device 

NixOS modules should have enough information to order the VK_ICD_FILENAMES in an order which makes sense for users. 

topic split from #108598

**Comment by critbase** [comment]
i've made a pr (https://github.com/NixOS/nixpkgs/pull/126435) that does two things: 1) naively reorder VK_ICD_FILENAMES, and  2) makes it so whatever the user defined as config.hardware.nvidia.package is used for vulkan. (1) should solve this issue, and (2) is tangentially related.

**Comment by jonringer** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/161576
