### ISSUE TITLE
Q: How to export variable to all imports?

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#126496]
I am trying to export variables from `configuration.nix` to imported files

https://git.dotya.ml/RiXotStudio/system-management/src/commit/d43eb3255894b99e8e8b2f64a9e1144cf9486e3a/configuration.nix#L11

error: undefined variable 'sysNixDir' at /etc/nixos//machines/leonid/default.nix:3:6
(use '--show-trace' to show detailed location information)

How can i make it work?

Tracked directory: https://git.dotya.ml/RiXotStudio/system-management/src/commit/d43eb3255894b99e8e8b2f64a9e1144cf9486e3a

**Comment by Kreyren** [comment]
I though i solved it with:

```nix
{ config, lib, pkgs, ... }:
let
	# DND(Krey): Fatal here if HOSTNAME is not available
	## `builtins.getEnv "HOSTNAME"` doesn't work
	hostName = "leonid";
	domain = "rixotstudio.cz";
	sysNixDir = "/etc/nixos/";
in {
                    options.sysNixDir = lib.mkOption { type = lib.types.path; };
                    config.sysNixDir = sysNixDir;
	imports = [
		"${sysNixDir}/machines/${hostName}/default.nix"
	];
}
```

But that gives me:

```
[kreyren@leonid:~]$ sudo nixos-rebuild test
error: infinite recursion encountered, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:131:21
(use '--show-trace' to show detailed location information)
building Nix...
error: infinite recursion encountered, at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:131:21
(use '--show-trace' to show detailed location information)
^Cerror: interrupted by the user
```

I got suggested flakes, but those also doesn't seem to fit the usecase?

Usecase: Provide `/etc/nixos` as a git repository on https://git.dotya.ml with a handling to update X amount of systems using that repository though triggering build on new commit that triggers logic based on system hostname.

**Comment by jonringer** [comment]
```
   config.sysNixDir = sysNixDir;
```

is the problem. You shouldn't be assigning to anything on `config`, but only reading it. `config` should already contain all of the  final options.

you'll want to do:
```
sysNixDir = sysNixDir; # or `inherit sysNixDir;`
```
to set it

```
  "/some/command ${config.sysNixDir}"
```
to consume it in other modules

**Comment by Kreyren** [comment]
![image](https://user-images.githubusercontent.com/11302521/121579510-11be7b80-ca2c-11eb-9c21-6cb701e28829.png)

ehh O.o that code gives me the `infinite recursion ` err

**Comment by jonringer** [comment]
please pass `--show-trace` to `nixos-rebuild`

**Comment by Kreyren** [comment]
Pushed https://git.dotya.ml/RiXotStudio/system-management/src/commit/c307d1ee2977521ce02b101771b95c32e8f277ab

Output:

```console
[kreyren@leonid:~]$ { sudo rm -r /etc/nixos; sudo cp -r ~/system-management/ /etc/nixos && sudo nixos-rebuild test --show-trace ;} |& ix
http://ix.io/3pyP
```

i was able to somewhat integrate the `sysNixDir` as per your info, but i can't use it in:

https://git.dotya.ml/RiXotStudio/system-management/src/commit/c307d1ee2977521ce02b101771b95c32e8f277ab/configuration.nix#L22

But i am failing to integrate it in 

https://git.dotya.ml/RiXotStudio/system-management/src/commit/c307d1ee2977521ce02b101771b95c32e8f277ab/configuration.nix#L20

https://git.dotya.ml/RiXotStudio/system-management/src/commit/c307d1ee2977521ce02b101771b95c32e8f277ab/configuration.nix#L18

since it gives me:

![image](https://user-images.githubusercontent.com/11302521/121683874-42e78c00-cabe-11eb-9bb6-82b8ab6da873.png)

![image](https://user-images.githubusercontent.com/11302521/121683907-4d098a80-cabe-11eb-94bc-2f50bb512b67.png)

![image](https://user-images.githubusercontent.com/11302521/121683946-57c41f80-cabe-11eb-8b28-2bae39a5172b.png)


--

I am also unable to get the other variables (`hostName` and `domain`) in 

https://git.dotya.ml/RiXotStudio/system-management/src/commit/c307d1ee2977521ce02b101771b95c32e8f277ab/configuration.nix#L8

To other files, currently needed in:

https://git.dotya.ml/RiXotStudio/system-management/src/commit/c307d1ee2977521ce02b101771b95c32e8f277ab/administration/networking.nix#L3

**Comment by abathur** [comment]
@Kreyren Closing since "EDIT: SOLVED" in the previous comment suggests the question was answered, but I'm happy to reopen if I'm mistaken.
