### ISSUE TITLE
Getting `error: The option 'programs.neovim' defined in '/etc/nixos/configuration.nix' does not exist.`

### ISSUE THREAD

**Issue by maratbn** [NixOS/nixpkgs#126443]
**Describe the bug**
I tried to install neovim by inserting `programs.neovim.enable = true;` into my `/etc/nixos/configuration.nix` as described at [https://nixos.wiki/wiki/Neovim](https://nixos.wiki/wiki/Neovim) but getting this error from `nixos-rebuild switch`.

**To Reproduce**
1. Become `root` user.
2. Open `/etc/nixos/configuration.nix`
2. Scroll down to the end of file.
3. Scroll up just above the last `}` and just below the line `system.stateVersion = ...` or insert a new line between these lines.
4. Insert: `programs.neovim.enable = true;`
5. Save the modified `/etc/nixos/configuration.nix` and exit.
6. Execute `nixos-rebuild switch`.  Observe the following output with errors:

        error: The option `programs.neovim' defined in `/etc/nixos/configuration.nix' does not exist.
        (use '--show-trace' to show detailed location information)
        building Nix...
        error: The option `programs.neovim' defined in `/etc/nixos/configuration.nix' does not exist.
        (use '--show-trace' to show detailed location information)
        building the system configuration...
        error: The option `programs.neovim' defined in `/etc/nixos/configuration.nix' does not exist.
        (use '--show-trace' to show detailed location information)

**Expected behavior**
According to  [https://nixos.wiki/wiki/Neovim](https://nixos.wiki/wiki/Neovim) (right where it currently says _Alternatively you can use the neovim module (merged in september 2020)._) unless I'm misunderstanding the instructions this should install Neovim and configure aliases to start it with `vi` and `vim`.

**Notify maintainers**
@teto 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.114, NixOS, 20.09.4064.1b688ca59ba (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.4064.1b688ca59ba"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  programs/neovim.nix
```

**Comment by teto** [comment]
the module doesnt seem to exist for 1b688ca59ba, try updating

**Comment by maratbn** [comment]
Turns out I was in the wrong channel.  I was in `20.09` but needed to switch to `21.05`.  I did so and now the neovim configuration works.

Output of `nix-shell -p nix-info --run "nix-info -m"` now:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.114, NixOS, 21.05.876.60cce7e5e1f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.876.60cce7e5e1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

The commit 60cce7e5e1f is a descendant of 1e510a65a3596bc052167fe05a662cbcbc488989 which adds the module.
