### ISSUE TITLE
acme: nginx is required to serve challenge, but does not start without certs

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#12655]
I've enabled the acme service and configured nginx to serve the challenges. I also have a few virtualhosts that use the certificates that will be written by acme. Now, I've ran into a chicken-and-egg-problem: acme will create the certs only if nginx serves the challenges, but nginx does not start because the certs do not exist.
```
Jan 28 18:50:53 apu systemd[1]: Started Nginx Web Server.
Jan 28 18:50:53 apu polkitd[18970]: Unregistered Authentication Agent for unix-process:32425:32271023 (system bus name :1.32, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (dis
Jan 28 18:50:53 apu nginx[32436]: nginx: [emerg] BIO_new_file("/var/lib/acme/gillich.me/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/lib/acme/gillich.me/
Jan 28 18:50:53 apu systemd[1]: nginx.service: Main process exited, code=exited, status=1/FAILURE
```
I am undecided about how to solve this. Some options:

* Create self-signed certificates (requires reload)
* Stop running webserver and start a new one to serve challenges (requires stopping and starting)

Both would require knowledge of the webserver that is actually used on port 80.

@fpletz

**Comment by globin** [comment]
We currently deploy in 2 stages, once with http only then with https, deploying a snakeoil cert might work, too.

Also we are working nginx improvements:
https://github.com/mayflower/nixpkgs/commit/f9002c9011383594cd4a8cb968aaa8ab53fdf058
https://github.com/mayflower/nixpkgs/commit/e12b6fe880b006b56f4d4faf86fc63da7fbfdab7
https://github.com/mayflower/nixpkgs/commit/b42e7d2d067da74d0316401b6d44e2f0d70d73dc
https://github.com/mayflower/nixpkgs/commit/d8c159b7576d0cbec362fe2970d29219633afaba

nixops:
https://github.com/mayflower/mf-nixops/commit/f0ef0e9b8c18b65bb490aaa7c7da9bbee11f404b
https://github.com/mayflower/mf-nixops/commit/b7fec30f53f6d4a976282653580ab40a33a33f76
https://github.com/mayflower/mf-nixops/commit/50643e0d2ad07580972c5303e446ab03037dab0d

First deployed with forceSSL = false, then with above.

**Comment by jgillich** [comment]
Awesome stuff! Assuming that one reloads the webserver in `acme.postRun` anyway, creating a self-signed cert would be a ok-ish solution, right?

**Comment by globin** [comment]
AFAIR restarting is needed not reloading but no guarantee :wink:

**Comment by fpletz** [comment]
We could also use `system.activationScripts` to fetch certificates before reloading the dependent services like the webserver, where we the chicken-egg problem is the biggest problem. However, you still need to have a webserver running and configured with a default vhost for serving the acme challenges.

I will try to fix this soonish.

**Comment by domenkozar** [comment]
Just for reference: upstream uses snakeoil certs: https://github.com/letsencrypt/letsencrypt/commit/be889d379437be18ce1c0518b2cfec15f6b8dd6a

**Comment by abbradar** [comment]
FWIW I use a custom activation script which generates a self-signed certificate if one is not yet available and symlinks it to a place where nginx picks it from. Then I have a post-process step for acme service where I force this symlink to a new value.

**Comment by domenkozar** [comment]
@abbradar yeah I'm working on something similar.

**Comment by domenkozar** [comment]
I have a prototype but acme complaints:

```
Mar 11 22:01:47 eiger acme-hydra.snabb.co-start[27185]: 2016-03-11 22:01:47,682:DEBUG:simp_le:1198: Existing SANs: []
Mar 11 22:01:47 eiger acme-hydra.snabb.co-start[27185]: 2016-03-11 22:01:47,682:ERROR:simp_le:257: Existing () and requested (hydra.snabb.co) SANs mismatch
Mar 11 22:01:47 eiger acme-hydra.snabb.co-start[27185]: Backup and remove existing cert if you want to proceed
```

**Comment by domenkozar** [comment]
We'll have to symlink the certs and unlink when simp_le runs :(

**Comment by jgillich** [comment]
Unfortunately yes, I worked around it by changing the path to some temporary location.

**Comment by fpletz** [comment]
@domenkozar Are you using the version from this PR? https://github.com/NixOS/nixpkgs/pull/13451

This should have support to change SANs.

**Comment by domenkozar** [comment]
Nope, older version. I'll check with that PR.

**Comment by jgillich** [comment]
That is good news. So all that needs to be done now is create a snake oil cert at `/var/lib/acme/...` when the cert doesn't exist?

**Comment by domenkozar** [comment]
I'm not using very ugly hack with activationscripts (which should just be a systemd oneshot), see https://github.com/domenkozar/nixpkgs/commit/4e256ca59966fba8e63e2d6c7d6898a6f2abcd3c

**Comment by grahamc** [comment]
I've been asked to setup TLS on http://search.nix.gsc.io/. I'd like to, but have been holding out on doing so until this issue is resolved.

@domenkozar your definitely ugly script looks like it should work. I think that would be an improvement over what we have now. What would you think about putting in a PR for review?

**Comment by bobvanderlinden** [comment]
I'm using the changes from @domenkozar on my server. Seems to be working nicely. I agree with @grahamc , it seems more people are looking for such a solution, as there isn't a better one at the moment why not get some more eyes on it with a PR?

**Comment by domenkozar** [comment]
I think if someone converts it to a systemd oneshot job and makes nginx/apache depend on it, we're likely to merge it.

nixos hydra uses a variation of this: https://github.com/NixOS/nixos-org-configurations/commit/19b956005ab850dcfc0112288e5a0c3f808c05f0#diff-73514aaa2e0242ed442a1a714999fb45R371

**Comment by bobvanderlinden** [comment]
@domenkozar Done: #15562

**Comment by bobvanderlinden** [comment]
#15562 has changed quite a bit, but it is now usable for any webserver. It adds the option `security.acme.preliminarySelfsigned`, which will automatically generate self-signed certificates for any of the ACME certs that isn't created yet. The documentation includes an example for Nginx.

It isn't merged yet, so more eyes are very welcome.

**Comment by domenkozar** [comment]
This was merged and it works now.
