### ISSUE TITLE
Aliza 

### ISSUE THREAD

**Issue by mrbitt** [NixOS/nixpkgs#126508]
Hi , please update medical-applications Aliza --> default.nix
  
version = "1.98.57-2";
  src = fetchurl {
    # See https://www.aliza-dicom-viewer.com/download
    urls = [
	  "https://www.dropbox.com/s/py0w8kqg3xjvmac/aliza-1.98.57-2.x86_64.rpm"
    ];
    sha256 = "01qk2gadmc24pmfdnmpiz7vgfiqkvhznyq9rsr153frscg76gc9b";

**Comment by samueldr** [comment]
Transferred the issue, not that it guarantees anything.

cc @Mounium (package maintainer)
cc @LeSuisse (who recently upgraded the package)

**Comment by LeSuisse** [comment]
Closing, `aliza` was removed in fd9213cf753a19cc371b215d29edabf31e1ac4cb.
