### ISSUE TITLE
NixOS-rebuild now copies entire build closure when targeting remote hosts

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#126525]
Even if the target host gets the toplevel closure, later steps in the nixos-rebuild will always `nix-copy-closure` the `.drv` build closure over to the targetHost (which can thousands of packages larger) and is potentially unnecessary.

PR which introduced `nix-copy-closure` of the .drv: https://github.com/NixOS/nixpkgs/pull/119540

Additional Context:

For our scenario, we would `nix-copy-closure` to the machine, as the machines are usually underpowered compared our dev boxes, and our dev boxes would likely have the configurations in the store as we were iterating on the configurations. Thus it was odd that we copied the closure over and still have to copy an additional 2200 - 4000 paths, when the runtime closure already existed.

**Comment by chvp** [comment]
I'm not entirely sure how #119540 introduced this behaviour. The only thing I added there was a function allowing flakes to be built remotely. Copying results to the target host was not touched in that PR.

**Comment by jonringer** [comment]
> I'm not entirely sure how #119540 introduced this behaviour. The only thing I added there was a function allowing flakes to be built remotely. Copying results to the target host was not touched in that PR.

Previous behavior created a realised outpath:
```
           outLink=$tmpDir/result
            nix "${flakeFlags[@]}" build "$flake#$flakeAttr.config.system.build.toplevel" \
              "${extraBuildFlags[@]}" "${lockFlags[@]}" --out-link $outLink
            pathToConfig="$(readlink -f $outLink)"
```

new behavior creates a derivation, then `nix copy`'s it:
```
       local drv="$(nix "${flakeFlags[@]}" eval --raw "${attr}.drvPath" "${evalArgs[@]}" "${extraBuildArgs[@]}")"
        if [ -a "$drv" ]; then
            NIX_SSHOPTS=$SSHOPTS nix "${flakeFlags[@]}" copy --derivation --to "ssh://$buildHost" "$drv"
            buildHostCmd nix-store -r "$drv" "${buildArgs[@]}"
```

for a `.drv` to be valid, it needs every single .drv dependency. For me, this is 2000-5000 `.drv` and FOD paths which need to be instantiated and copied; as opposed to ~120 new outpaths

**Comment by chvp** [comment]
I guess I'm missing something. With the previous behaviour, it was not possible to build remotely, so you had to do `--build-host localhost --target-host remote.host`. If you give the same params now, it will only copy the out paths, not the derivations. 

(And to clarify: it's not that important to me, but I always like to know what I could have done better.)

**Comment by jonringer** [comment]
I guess the previous `nixos-rebuild .#nixosConfigurations.xxx --target-host remote.host` built the toplevel locally, then pushed it. Now this behavior pushes the .drv closure over, then realises it. Probably not that bad if the target host has a small configuration, but hosts which have 2-3 dozen services, and several dozen packages start to get .drv closures in the thousands, and it does become quite painful.

I guess I would have prefered `--build-host localhost` to be the default (which also would have retained previous behavior). And realisation on the target host should be done with `--build-host remote.host --target-host remote.host`
