### ISSUE TITLE
CEF needs an automatic update script

### ISSUE THREAD

**Issue by deviant** [NixOS/nixpkgs#126510]
I just filed a [pull request](https://github.com/NixOS/nixpkgs/pull/126505) to update our version of CEF to fix a [crash in OBS](https://github.com/NixOS/nixpkgs/issues/126410). The previous version was released on 2019-07-27— that's almost 2 years! For a piece of software that's functionally a web browser, we certainly shouldn't be using an out-of-date version: web browsers have a massive attack surface and it's very important to keep them updated at all times. I don't have the time to work on this right at the moment, but it shouldn't be too difficult. There's a [JSON file](https://cef-builds.spotifycdn.com/index.json) containing metadata for every CEF release. All that should be necessary is to grab the latest stable version for the right platform. While we're at it, we could also consider building for i686 and AArch64.

Tagging @puffnfresh, the maintainer

**Comment by bryanasdev000** [comment]
IDK how it works, but it sounds like a job for the @ryantm bot (https://github.com/ryantm/nixpkgs-update).
