### ISSUE TITLE
LLVM: Invalid value for `LLVM_INSTALL_PREFIX` due to incorrect number of `get_filename_component` lines in `LLVMConfig.cmake`

### ISSUE THREAD

**Issue by seylerius** [NixOS/nixpkgs#126583]
**Describe the bug**
Since the LLVM split into multiple outputs, `${llvmPackages.llvm.dev}/lib/cmake/llvm/LLVMConfig.cmake` is being produced with too many `get_filename_component` lines at the top. This results in ascending a level of the path too many times, producing a value of `/` or `/nix` in `LLVM_INSTALL_PREFIX`, instead of the correct value of `/nix/store/somehash-llvm-etc`. This has significant consequences for static-linked builds of other things (such as Terra, which is a professional concern of mine).

**To Reproduce**
1. Build `llvmPackages_<n>.llvm.dev` (I did `llvmPackages_10.llvm.dev`, as that's what I'm using for Terra) in any commit from 7869d165451 on. 
2. Open `/lib/cmake/llvm/LLVMConfig.cmake` within that, and observe that you have six or seven `get_filename_component` lines instead of the correct four.
3. Optionally build something that uses the value of `LLVM_INSTALL_PREFIX` and stuff a print into it, noting that it outputs as `/` or `/nix`.

**Expected behavior**
- `/lib/cmake/llvm/LLVMConfig.cmake` should contain exactly four `get_filename_component` lines near the top of the file.
- `LLVM_INSTALL_PREFIX` should resolve to the derivation's output directory (`/nix/store/whatever`).

**Notify maintainers**
@lovek323 @7c6f434c @dtzWill @thefloweringash

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.11pre294109.fbfb79400a0 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre294109.fbfb79400a0, nixos-20.09-20.09.4306.1a40a7254ea"`
 - channels(seylerius): `"home-manager, nixos-20.09-20.09.4306.1a40a7254ea, nixpkgs-master, nur"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - llvmPackages
  - llvmPackages_10.llvm
  - llvmPackages.llvm
```

**Comment by seylerius** [comment]
Bisection identified 7869d16 as the commit that introduces the problem. My current best guess as to the specific change in the commit is that it likely has to do with `gnu_install_dirs.patch`.

**Comment by sternenseemann** [comment]
cc @Ericson2314

**Comment by Ericson2314** [comment]
I'm not sure this is a bug. The install prefix is calculated correctly to be the deapest common ancestor directory of our multiple outputs, which is something like that.

Can you not use the LLVM subdirs from that file for Terra?

**Comment by ErikMcClure** [comment]
That is not what the `LLVM_INSTALL_PREFIX` means in a traditional LLVM install. I'm not sure what you mean by "LLVM subdirs", are there other cmake variables that terra could use instead?

**Comment by Ericson2314** [comment]
@ErikMcClure See https://reviews.llvm.org/D99484 for some background. The surprising behavior comes up because these "GNU install dirs" can be absolute paths and outside the nominal prefix. (That is true of autoconf and cmake.)

The variables i am thinking of are https://github.com/llvm/llvm-project/blob/31b9acaec5797e409afb83d665fc8816d8a37940/llvm/cmake/modules/LLVMConfig.cmake.in#L87-L106

**Comment by ErikMcClure** [comment]
So it appears that the way terra was relying on LLVM_INSTALL_PREFIX either isn't valid anymore, or was never valid. As a result I simply fixed this with an override to terra's internal CLANG_RESOURCE_DIR because I'm not sure any of those variables expose the specific clang include directories that it needs.

**Comment by seylerius** [comment]
Yeah, I think Terra's going to stick with working around this. I looked a lot closer at that code and Nixpkgs' `gnu-install-dirs.patch`, and now I see what's going on here. Although we could possibly get what we need by ascending a few levels in the directory tree from `LLVM_LIBRARY_DIR`, that's still iffy and leans unpleasantly on the assumption of Clang being bundled with LLVM directly. Thank y'all for all the clarification and assistance.

**Comment by Ericson2314** [comment]
Thanks for finding another ways, both of you, I really appreciate it!

Now I just need to get those patches over the finish line.
