### ISSUE TITLE
nixos-rebuild pollutes current directory with "result" symlink

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#12665]
`nixos-rebuild boot` creates a symlink like

     lrwxrwxrwx 1 root   root    85 Jan 29 10:53 result -> /nix/store/afv0nbqkx5iii9i4k278a0bsdrhbz7m3-nixos-system-mobile-16.03pre75806.77f8f35

in the current directory. The NixOS version is 16.03pre75806.77f8f35 (current `unstable` channel).

**Comment by domenkozar** [comment]
Most probably a regression in https://github.com/NixOS/nixpkgs/pull/12324.

I suspect it broke tests http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents but I haven't verified that yet.

**Comment by domenkozar** [comment]
cc @rickynils

**Comment by rickynils** [comment]
I look into it.

@domenkozar Does the fact that symlinks are created break tests?

**Comment by dezgeg** [comment]
Test breakage is not related to this but rather (just got fixed): https://github.com/NixOS/nixpkgs/commit/a581f72f222043936e78d1fe8ad09380c46bfa53

**Comment by colemickens** [comment]
`switch` is doing the same.

**Comment by Baughn** [comment]
For cleanup purposes, this should be relatively safe -- though, probably run it once with echo instead of rm, just to be sure.

```
nix-store --gc --print-roots | awk '{print $1}' | grep result | xargs rm
```

**Comment by andjscott** [comment]
`nixos-rebuild` is making result symlinks on nixos-unstable.

**Comment by goodwillcoding** [comment]
@abbradar @rickynils 
In a related "issue" `nixos-rebuild`  `test`, `build`, `dry-build`, `dry-activate` also generate the `results` symlink. To me it seems like the `--no-out` should be applied there as well so it does not polute the system. I'll issue a PR unless this is somehow a desired behavior.

**Comment by wucke13** [comment]
There is no such option to `nixos-rebuild` as `--no-out`
```
$ nixos-rebuild --no-out
/run/current-system/sw/bin/nixos-rebuild: unknown option `--no-output'
```
How shall one prevent `nixos-rebuild` to create those symlinks?

**Comment by Baughn** [comment]
That's peculiar. It spell-checked the option... so --no-out exists as an alias for --no-output, but --no-output itself doesn't exist?

**Comment by colemickens** [comment]
It's another place in general where the Nix tooling just feels inconsistent... It looks like boot/switch were special cased to not drop the out link, rather than making it a proper flag to `nixos-rebuild`...

**Comment by goodwillcoding** [comment]
@wucke13 why are you asking me the same question I posed in this issue ... did your read the comments at all?

**Comment by NonVideri** [comment]
This is still around AFAIK. Just got a "result" symlink in my home directory.

**Comment by eclairevoyant** [comment]
@NonVideri with which subcommand?

**Comment by NonVideri** [comment]
@eclairevoyant Hard to tell, but probably `nixos-rebuild switch`, as I mainly use that one.

**Comment by eclairevoyant** [comment]
If you are able to reproduce on an up-to-date nix install then please create a new issue for it. Also keep in mind the build and build-vm subcommands will create the symlink and _that_ is expcted.
