### ISSUE TITLE
firefox on nixos-21-05: Tabs immediatly crash

### ISSUE THREAD

**Issue by neumantm** [NixOS/nixpkgs#126602]
**Describe the bug**
After upgrading to nixos-21-05 I have the following problem:
When I start firefox it starts but each tab I open immediately crashes.
I tried with a completely fresh profile, so no plugins or custom settings interfere: Same problem
The only thing I found to work is the Troubleshoot Mode of firefox.

**To Reproduce**
1. Update to current nixos-21-05
2. Install firefox:
```
environment.systemPackages = with pkgs; [
    # Browsers
    chromium
    firefox
    ...
]
 ```
3. Start firefox
4. Open a tab with any URL/searchterm/even an empty tab

**Expected behavior**
The tab should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/27770422/121701373-1e48df80-cad1-11eb-83fb-3f7d5f3c95e6.png)

**Additional context**
Output when starting firefox from terminal:
```
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
IPDL protocol error: Error deserializing 'SharedMemoryHandle[]'
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
IPDL protocol error: Error deserializing 'SharedMemoryHandle[]'
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
IPDL protocol error: Error deserializing 'SharedMemoryHandle[]'
JavaScript warning: resource://gre/modules/Troubleshoot.jsm, line 692: WebGL context was lost.
JavaScript warning: resource://gre/modules/Troubleshoot.jsm, line 692: WebGL context was lost.
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
[Parent 5897, Main Thread] WARNING: Too many file descriptors for one message!: file /build/firefox-89.0/ipc/chromium/src/chrome/common/ipc_message_utils.h:414
IPDL protocol error: Error deserializing 'SharedMemoryHandle[]'
...
```

**Notify maintainers**
@lovesegfault 
@mweinelt 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.42, NixOS, 21.05.906.cedcf2565c6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.906.cedcf2565c6, nixos-unstable-21.11pre294109.fbfb79400a0"`
 - channels(tim): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by neumantm** [comment]
One major difference in about:support between running normally and with troubleshooting mode is the
`windowLayerManagerType`. In troubleshooting mode it is `Basic` and otherwise it is `WebRender`.
I attached exports of about:support
[about_support_troubleshooting.json.txt](https://github.com/NixOS/nixpkgs/files/6639200/about_support_troubleshooting.json.txt)
[about_support_normal.json.txt](https://github.com/NixOS/nixpkgs/files/6639201/about_support_normal.json.txt)

**Comment by neumantm** [comment]
I have the same problem on the current unstable.

**Comment by neumantm** [comment]
I can even reproduce it with a seperate user I just created, so pretty sure it is not caused by any stray config in my home directory.

**Comment by mweinelt** [comment]
If switching away from WebRender fixes this for you I'd assume the issue is with your GPU or its driver. I don't see any issue on amdgpu (RX5700) on sway (Wayland).

**Comment by neumantm** [comment]
I see.
Will look into that.
Ty

**Comment by neumantm** [comment]
Is there a way to manually switch the Renderer, without completely going into Troubleshooting mode?
And: Does anyone have an idea on how to debug what the problem with my drivers is?

**Comment by mweinelt** [comment]
Navigate to `about:config` and set `gfx.webrender.all` to false. If it crashes you might have to modify `prefs.js` in your profile directory.

**Comment by neumantm** [comment]
No `about:config` does not crash. But `gfx.webrender.all` is already `false` (it is not bold, so I assume `false` is the default)

**Comment by neumantm** [comment]
With `firefox-esr` it works. So seems to have something todo with the new version of ff

**Comment by sigprof** [comment]
Looks like setting `gfx.webrender.all` to false does not disable WebRender — see https://bugzilla.mozilla.org/show_bug.cgi?id=1585091:

> `gfx.webrender.all` == set all required prefs: enable WR and on Linux also force-enable OpenGL layers
> `gfx.webrender.all.qualified` (hidden pref) == enable WR by default on qualified systems
> `gfx.webrender.enabled` == enable WR (won't work on Linux unless `layers.acceleration.force-enabled` is set to true)
> `gfx.webrender.force-disabled` == force-disable
>
> So you can either set `gfx.webrender.all.qualified`=false (hidden pref) or `gfx.webrender.force-disabled`=true.

**Comment by mweinelt** [comment]
ESR likely does not have WebRender support. And disabling it works for you? If so please look for an issue upstream. https://bugzilla.mozilla.org

**Comment by neumantm** [comment]
> Looks like setting `gfx.webrender.all` to false does not disable WebRender — see https://bugzilla.mozilla.org/show_bug.cgi?id=1585091:

ok.

> So you can either set `gfx.webrender.all.qualified`=false (hidden pref) or `gfx.webrender.force-disabled`=true.

Yes, with `gfx.webrender.force-disabled=true` i saw that it worked in `about:support`
However it did not fix the bug with crashing tabs for me.
So it looks like WebRender is not the (only) cause.

> ESR likely does not have WebRender support. And disabling it works for you? If so please look for an issue upstream. https://bugzilla.mozilla.org
Yes, ESR shows `Compositing	Basic`. 
As diesabling didn't fix it. I will investigate further and open an issue upstream.

**Comment by zeorin** [comment]
I also have this issue. Here is a relevant crash report: https://crash-stats.mozilla.org/report/index/530c0129-ee63-4e73-817c-4700e0210603

I have a Nvidia GTX 970. On my Intel graphics laptop there's no problem.

**Comment by zeorin** [comment]
@neumantm Do you have a lot of fonts installed? That was part of why it happened for me, apparently:

I have a workaround ([from a chat on the Mozilla Matrix](https://matrix.to/#/!gTeEstkMlPUdxvIdCE:mozilla.org/$ypZE5gfT6-qkm8zEe2Jnu5oOQY3KC3aUt0fYYlv_7jg?via=mozilla.org&via=matrix.org&via=privacytools.io))

As a workaround, change `gfx.e10s.font-list.shared` to `false` in `about:config`. Or you can use Firefox Beta, Developer Edition, or Nightly, since they have the bug fixed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1664151

**Comment by neumantm** [comment]
@zeorin Thank you a lot!
Yes, I may have quite a few fonts.
And changing `gfx.e10s.font-list.shared` to `false` did the trick.

**Comment by neumantm** [comment]
> I have a Nvidia GTX 970. On my Intel graphics laptop there's no problem.

Interestingly it happens on my laptop with Intel graphics  (Intel HD Graphics 520)
