### ISSUE TITLE
stdenv unpacking: Preserve timestamps when copying files breaks zipfiles

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#12663]
Eelco reverted a fix for <1980 dates issue in zip files. See https://github.com/NixOS/nixpkgs/commit/f4553d721972e6a437c9f367af2bb0967b773998

Example package: pythonPackages.gyp

Possible fix: https://github.com/triton/triton/commit/52f9121ffbe37f405d9f41a9d5dc4ae884fc652a

**Comment by edolstra** [comment]
Maybe we can fix zip?

**Comment by edolstra** [comment]
Canonicalising to 2000 seems confusing to me since we're already canonicalising to 1970 in other places.

**Comment by vcunat** [comment]
The supported range seems from 1980 for 128 years. Theoretically, we could change the semantics, e.g. "wrap" the last 10 years into the 1970-80 period, preserving compatibility on the overlapping 118 years.

**Comment by vcunat** [comment]
This seems to cause thousands of broken builds [on staging](http://hydra.nixos.org/eval/1237038), mainly because of python tests failing. @domenkozar: do you know what the tests are trying to achieve? Zipping up the build directory?

**Comment by domenkozar** [comment]
@vcunat tests are due to `setuptools` bump, which forces tests to be ran even if they don't exist. This is an issue on Python 3.x.

The failures with this change are related to our installation method using wheels. Basically we create a wheel (zip file) and then install it. That's the preferred Python way of doing binary installs. As an example see http://hydra.nixos.org/build/31373731/nixlog/1/raw

**Comment by domenkozar** [comment]
I really wouldn't go and fix zip. Guix folks are doing a very similar thing: https://lists.gnu.org/archive/html/guix-commits/2015-07/msg00462.html

**Comment by vcunat** [comment]
Yeah, probably some similar solution.

**Comment by vcunat** [comment]
Any arguments against this solution: d7b59519f6? (@edolstra mainly, I suppose)
