### ISSUE TITLE
Vivaldi: Enable wayland support

### ISSUE THREAD

**Issue by buehlefs** [NixOS/nixpkgs#126652]
**Describe the bug**
Vivaldi under wayland does not support screen sharing (and runs as x11 window).

**To Reproduce**
1. start vivaldi in a wayland session with pipewire and correctly configured desktop portals
2. enable pipewire support in the flags (<vivaldi://flags/#enable-webrtc-pipewire-capturer>)
3. try screen sharing here <https://mozilla.github.io/webrtc-landing/gum_test.html>
4. Optionally test screen sharing with firefox-wayland package to make sure wayland screensharing is configured correctly (see also #91218)

**Expected behavior**
Screen sharing should work if pipewire and the correct desktop portals are configured correctly.

**Additional context**
Tracking issue for chrome screen sharing support under wayland: #91218

A possible fix tested in a local nix shell is to add `pipewire` to the build inputs for screen sharing support. Additionally adding `libglvnd` allowed starting vivaldi with the flags `--enable-features=UseOzonePlatform,UseSkiaRenderer,Vulkan --ozone-platform=wayland` to run as a native wayland window.

Suggested changes to the package:

```
# line 11
, enablePipewire ? false , pipewire ? null
, waylandSupport ? false, libglvnd ? null 

# line 42
  ] ++ lib.optional proprietaryCodecs vivaldi-ffmpeg-codecs ++ lib.optional waylandSupport libglvnd ++ lib.optional enablePipewire pipewire;
```

**Notify maintainers**

@badmutex 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.876.60cce7e5e1f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.906.cedcf2565c6, nixos-unstable-21.11pre294801.432fc2d9a67"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: vivaldi
# a list of nixos modules affected by the problem
module:
```

**Comment by badmutex** [comment]
ACK-ing this. I'm away for a couple weeks so I'll dig in when I get home.

**Comment by edrex** [comment]
suggest changing title to "Vivaldi: Enable screen sharing under wayland" since basic wayland client enablement is also needed.

**Comment by edrex** [comment]
I'm wondering if it wouldn't make sense to roll vivaldi into the chromium file, as brave is, since it would maybe reduce maintenance costs. Thoughts?

**Comment by edrex** [comment]
I have screensharing working under chromium so I will try adding the pipewire libs to #160234

**Comment by edrex** [comment]
Adding `pipewire` to `buildInputs` doesn't seem to be enough, and vivaldi is still trying to do X11-based screen sharing. Vivaldi lacks an open issue tracker, so I think this is where I stop using it. :beers:

**Comment by buehlefs** [comment]
@edrex You have to enable the pipewire support under vivaldi://flags or with some command line flags (that I don't know). I did get pipewire streaming to work with my experimentation so I would not give up before testing again with the flag enabled.

**Comment by edrex** [comment]
You're right, I didn't have the pipewire experiment enabled under chrome:flags. Care to look at the PR?

**Comment by Mikilio** [comment]
A related issue was mentioned on [NixOS Discourse](https://discourse.nixos.org/t/vivaldi-in-wayland-mode/23442?u=mikilio)

**Comment by buehlefs** [comment]
Closing this issue. Screensharing now works properly under wayland.
