### ISSUE TITLE
gnome-todo evolution data server backend does not seem to work

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#126701]
**Describe the bug**
gnome-todo cannot create caldav based lists and cannot see caldav-based lists created in evolution

**To Reproduce**
1. click on add new list
2. type a name
2. clik on the button to change storage backend
3. only local is proposed

I can't screenshot because it's a popup...

1. create a caldav list in evolution
2. don't see it in gnome-todo

**Additional context**
I thought it was because we don't build the ews plugin but it seems we do.

**Notify maintainers**
@NixOS/gnome 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.42, NixOS, 21.05.906.cedcf2565c6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.906.cedcf2565c6, nixos-unstable-21.11pre294801.432fc2d9a67, nixos-hardware"`
 - channels(symphorien): `"home-manager-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
Looks like only Google and local are currently supported: https://gitlab.gnome.org/GNOME/gnome-todo/-/issues/45

**Comment by symphorien** [comment]
Weird. I asked on #gnome-todo:gnome.org and someone told me that it was supposed to work. But of course matrix ate my history, so I can't tell who...
