### ISSUE TITLE
tiger-/tightvnc depend on unfree font

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#126754]
`fontbhlucidatypewriter75dpi` is unfree (though mistakenly not marked as redistributable) and tiger- and tightvnc explicitly depend on it.

Does it *have* to be that font or can it be substituted with a free alternative @viric? I don't use the server part of those tools, so I can't test their functionality.

**Comment by Atemu** [comment]
See also https://github.com/NixOS/nixpkgs/pull/126756

**Comment by rnhmjoj** [comment]
Closing since #126756 has been merged.

**Comment by Atemu** [comment]
The font is now redistributable but still unfree.

**Comment by qzle** [comment]
The tigervnc client works perfectly without any font paths baked in. I wonder if this is still required for the server or if it is an artifact from years ago that is no longer necessary? The fontPath-code is [11 years](https://github.com/NixOS/nixpkgs/blame/805e945e82cd7f21830436b11a504d6210ed83fa/pkgs/tools/admin/tigervnc/default.nix#L29) old.

As a workaround `tigervnc.override{fontDirectories=[];}` can be used where unfree is problematic.

**Comment by Atemu** [comment]
I guess we could make a free version without the font for the people who just want the client.

**Comment by Atemu** [comment]
Fixed in cfb935c54940115751270011a569ba3214984f5a
