### ISSUE TITLE
Cross-compiling SD card image for Rasperry Pi (armv6l) on `nixos-unstable` branch fails

### ISSUE THREAD

**Issue by rajivr** [NixOS/nixpkgs#126755]
**Describe the bug**

This [gist](https://gist.github.com/rajivr/706833c1a0e6b931b6e81333215f855a) has `cross-hacks.nix`, `flake.lock` and `flake.nix` to reproduce the issue.

**To Reproduce**
1. Run `nix build`, with the above files in a temporary directory.

**Expected behavior**

Was expecting an sdcard image file. But, the build fails with the following error.

```
[nixos-user@instance-01-nixos-85e8aa6e20:~/zfs/rajivr-github/cross-system-wip-armv6l]$ nix build
error: --- Error --- nix-daemon
builder for '/nix/store/gxjkh97x11sdlqj8cz19bjk2l96mw4qq-linux-armv6l-unknown-linux-gnueabihf-5.10.17-1.20210303-modules-shrunk.drv' failed with exit code 1; last 3 log lines:
  kernel version is 5.10.17
  root module: ahci
  modprobe: FATAL: Module ahci not found in directory /nix/store/2d313qrgc7pchhnj1j22wcn6a3fns6ra-linux-armv6l-unknown-linux-gnueabihf-5.10.17-1.20210303-modules/lib/modules/5.10.17
error: --- Error --- nix-daemon
```

**Notify maintainers**

CC: @samueldr

**Comment by samueldr** [comment]
Unrelated to cross-compiling AFAICT.

See https://github.com/NixOS/nixpkgs/pull/78430

Since this change, the behaviour for kernel modules in initrd changed in a hugely breaking way, without any kind of strategy to work around the issue.

**Comment by rajivr** [comment]
Thanks @samueldr.

Based on @cleverca22 suggestion (Thanks for the suggestion!), I was able to get this to work, with the following overlay to `nixpkgs`.

```
overlays = [
  (final: super: {
    makeModulesClosure = x:
      super.makeModulesClosure (x // { allowMissing = true; });
  })
];
```
