### ISSUE TITLE
Update MLT

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#126746]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: mlt

current version: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/mlt/default.nix#L9
desired version: https://github.com/mltframework/mlt/releases

###### Notify maintainers

maintainers: @peti @tohl

###### Note for maintainers

Please tag this issue in your PR.

**Comment by turion** [comment]
The weird state is now that we have `nixpkgs/pkgs/development/libraries/mlt/default.nix` on version 6.26 (not very up to date), and a (cleaner?) `nixpkgs/pkgs/development/libraries/mlt/qt-5.nix` which was more recently updated to 7.0 by @ttuegel . Latest released version is 7.2.

Where do we go from there? Can we drop the 6.* versions?

**Comment by turion** [comment]
CC @goibhniu (maintainer of `mlt-qt5`)

**Comment by scvalex** [comment]
I see both `mlt` and `libsForQt5.mlt` are on 7.20 in stable and 7.22 in unstable, so this issue looks like it can be closed.

**Comment by applePrincess** [comment]
Close this  as mlt package is updated.
