### ISSUE TITLE
wine 1.9.2 released

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#12687]
[Wine 1.9.2 has been released](https://www.winehq.org/news/2016012201). Can we have the package updated?

Pinging @bendlas

**Comment by heydojo** [comment]
@a1russell You have a fork. Is there anything stopping you from bumping, testing and proposing a merge? It makes it much easier for you to get bumps for software that you use.

I don't think we need issues creating for new versions of software x when it is released.
Only security vulnerabilities which need to be patched with some balanced amount of urgency should really be flagged as issues.
Please see http://monitor.nixos.org/ for the scale of the number of bumps possible in NixOS for a reason why flagging new versions in the issue tracker is not ideal.

**Comment by a1russell** [comment]
I didn't mean to offend anyone, @heydojo. This is a collaborative project, I haven't worked on the wine package yet, and I was trying to initiate a dialogue.

If the person currently maintaining the package is already working on it, I don't want to waste my time, as well.

**Comment by heydojo** [comment]
I don't think anyone was offended.
We have a mailing list http://lists.science.uu.nl/mailman/listinfo/nix-dev
:)

**Comment by pSub** [comment]
FYI: monitor.nixos.org is outdated for quite some time now.
