### ISSUE TITLE
Can't install chicken scheme on darwin

### ISSUE THREAD

**Issue by blakesweeney** [NixOS/nixpkgs#12686]
Not sure how to work around this because I don't want to allow broken. 

```
$ nix-env -i --dry-run chicken-egg2nix
(dry run; not doing anything)
installing ‘chicken-egg2nix-0.5’
error: Package ‘chicken-4.10.0’ in ‘/nix/store/bq67byr5wp5ww84lgli37icfc9aldgf7-nixpkgs-16.03pre75806.77f8f35/nixpkgs/pkgs/development/compilers/chicken/default.nix:67’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

Also, from the error message I would not expect this error:

```
$ nix-env -i chicken-4.10.0
error: selector ‘chicken-4.10.0’ matches no derivations
```

**Comment by joachifm** [comment]
Marked as broken on darwin at 9300470b5ec507806a30e3de8edd3a695ac585fa

**Comment by blakesweeney** [comment]
I've run into other similar issues where something is broken due to a broken dependency (qutebrowser for example). Brokenness should probably propagate to packages that use a broken package. Either way I'm fine with closing this until a fix is available.

**Comment by joachifm** [comment]
You can do one-off builds with broken packages by `NIXPKGS_ALLOW_BROKEN=1 nix-build`. For all I know, it could work fine on darwin now (it's been a while since it was disabled); it appears to be supported upstream, at any rate.

**Comment by blakesweeney** [comment]
Yeah I have a working install outside of nix. I haven't made time to try and fix what ever issues happens when installing with nix.

**Comment by shmish111** [comment]
Is there a reason why chicken is still marked as not supported on mac? It seemed to work fine for me

**Comment by joachifm** [comment]
@shmish111 could be because nobody found the time to test or noticed. If it works for you, please consider opening a PR.
