### ISSUE TITLE
lightdm background config broken

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#12684]
https://github.com/NixOS/nixpkgs/commit/a04a7272aa38ada45e694281071b720d4abbd0df set the services.xserver.displayManager.lightdm type to path, but it doesn't have to be a path. Before that commit, I was able to set it to a color, and it worked just fine. Please change this back!

**Comment by heydojo** [comment]
So are you saying that :
```
services.xserver.displayManager.lightdm.background
```
does not work for you?

**Comment by a1russell** [comment]
Correct, when I set it to "#222222".

**Comment by heydojo** [comment]
Pinging @ocharles & @wkennington
services.xserver.displayManager.lightdm.background fails to set background colour.

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/lightdm.nix#L89

I believe :
```
type = types.string;
```
may resolve?

**Comment by ocharles** [comment]
Yep, I'll make that change now.

**Comment by heydojo** [comment]
Thanks @ocharles
