### ISSUE TITLE
gitlint

### ISSUE THREAD

**Issue by kirinnee** [NixOS/nixpkgs#126806]
**Gitlint**
_CLI tool and pre-commit hook plugin to lint commit messages with presets_

**Metadata**

* homepage URL: https://jorisroovers.com/gitlint/
* source URL: https://github.com/jorisroovers/gitlint
* license: MIT
* platforms: linux, unix, darwin (python3)

**Comment by hmenke** [comment]
```nix
{ lib
, buildPythonPackage
, fetchFromGitHub
, gitMinimal
, arrow
, click
, sh
, wheel
}:

buildPythonPackage rec {
  pname = "gitlint";
  version = "0.15.1";

  src = fetchFromGitHub {
    owner = "jorisroovers";
    repo = "gitlint";
    rev = "v${version}";
    sha256 = "sha256-CqmE4V+svSuQAsoX0I3NpUqPU5CQf3fyCHJPrjUjHF4=";
  };

  nativeBuildInputs = [ wheel ];

  propagatedBuildInputs = [
    arrow
    click
    sh
  ];

  preCheck = ''
    export PATH="$out/bin:$PATH"
  '';

  checkInputs = [
    gitMinimal
  ];

  meta = {
    description = "Linting for your git commit messages";
    homepage = "http://jorisroovers.github.io/gitlint";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ kirinnee ];
  };
}
```

**Comment by kirinnee** [comment]
This isn't my library, I simply requested for this package. should i still be included as maintainer?

**Comment by kirinnee** [comment]
Also, do I make a PR with the code above? Or is there already a PR @hmenke

**Comment by hmenke** [comment]
There is no PR yet. New packages need a maintainer and I don't want to maintain this.

**Comment by ethancedwards8** [comment]
> There is no PR yet. New packages need a maintainer and I don't want to maintain this.

I'll do it. I'll send in a PR now.
