### ISSUE TITLE
document makeWrapper

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#12693]
There is no documentation whatsoever about one of the most basic utilities in nixpkgs.

There is exactly one very short source code comment about usage.

**Comment by domenkozar** [comment]
I very much endorse such efforts :)

**Comment by FRidh** [comment]
This was done by @Profpatsch in dd58d24fa612df73264bb69f82517e1c2bc6999a

**Comment by Profpatsch** [comment]
Watch me roll (aka not close my own issues after I implement stuff months later) :octocat:

**Comment by domenkozar** [comment]
You did the important part of the job :)
