### ISSUE TITLE
ccls can't find standard headers

### ISSUE THREAD

**Issue by liketechnik** [NixOS/nixpkgs#126936]
**Describe the bug**
ccls complains about not found header files that I'd expect to be found.

**To Reproduce**
1. Create a `.c`-file including `stddef.h` or `stdbool.h`: `echo '#include <stddef.h>' > test.c`
2. Setup `ccls`: `touch .ccls`
3. Run `ccls`: `ccls --index=. -v=2`
<details>
<summary>Full output</summary>

```
13:25:44 .ccls-wrapped  initialize.cc:274 I initialize in directory /tmp/test with uri file:///tmp/test/.
13:25:44 .ccls-wrapped  initialize.cc:297 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":".ccls-cache","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":["-idirafter","/nix/store/niplk2w8g0ri0n8h07zyp1l3cbnzv7a2-glibc-2.32-46-dev/include","-isystem","/nix/store/cfkfpca5ymx2rf66k6f16sa3lb6ndgc2-gcc-10.3.0/include/c++/10.3.0","-isystem","/nix/store/cfkfpca5ymx2rf66k6f16sa3lb6ndgc2-gcc-10.3.0/include/c++/10.3.0/x86_64-unknown-linux-gnu"],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100,"placeholder":true},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
13:25:44 .ccls-wrapped  initialize.cc:329 I use -resource-dir=/nix/store/8ksw8lwn10vmiz5nzhmkpa6i7l05al68-clang-11.1.0/lib/clang/11.1.0
13:25:44 .ccls-wrapped  initialize.cc:361 I workspace folder: /tmp/test/
13:25:44 .ccls-wrapped     project.cc:284 I use /tmp/test/.ccls:
13:25:44 .ccls-wrapped  initialize.cc:386 I start 12 indexers
13:25:44 .ccls-wrapped  initialize.cc:394 I dispatch initial index requests
entries:      1
completed:    0/113:25:44 indexer11        pipeline.cc:386 I parse /tmp/test/test.c error:1 'stddef.h' file not found
  clang /tmp/test/test.c -idirafter /nix/store/niplk2w8g0ri0n8h07zyp1l3cbnzv7a2-glibc-2.32-46-dev/include -isystem /nix/store/cfkfpca5ymx2rf66k6f16sa3lb6ndgc2-gcc-10.3.0/include/c++/10.3.0 -isystem /nix/store/cfkfpca5ymx2rf66k6f16sa3lb6ndgc2-gcc-10.3.0/include/c++/10.3.0/x86_64-unknown-linux-gnu -working-directory=/tmp/test/
13:25:44 indexer11        pipeline.cc:397 I store index for /tmp/test/test.c (delta: 0)
completed:    1/1
```
</details>

ccls shows the following error: `completed:    0/113:25:44 indexer11        pipeline.cc:386 I parse /tmp/test/test.c error:1 'stddef.h' file not found`

**Expected behavior**
`ccls` successfully parses the file.

**Screenshots**

**Additional context**
I'm afraid that I don't have the exact version numbers, but it worked correctly before I updated to 21.05.

*Edit*: the `resource-dir` used by ccls (`13:25:44 .ccls-wrapped  initialize.cc:329 I use -resource-dir=/nix/store/8ksw8lwn10vmiz5nzhmkpa6i7l05al68-clang-11.1.0/lib/clang/11.1.0` from the output above) does not exist on my system: 
```
$ ls /nix/store/8ksw8lwn10vmiz5nzhmkpa6i7l05al68-clang-11.1.0/lib/clang/11.1.0
ls: cannot access '/nix/store/8ksw8lwn10vmiz5nzhmkpa6i7l05al68-clang-11.1.0/lib/clang/11.1.0': No such file or directory
```

**Notify maintainers**

@Mic92 @tobim 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.05.20210613.1f91fd1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210326_dd77f71`
 - channels(florian): `"nixpkgs-21.05pre282548.4c87cb87a2d"`
 - nixpkgs: `/home/florian/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by liketechnik** [comment]
I did some more investigation into this issue:

The current version of ccls in the 21.05 tree reports the following version info and uses the following [resource dir](https://github.com/MaskRay/ccls/wiki/Install#clang-resource-directory):

```
$ ccls --version
ccls version 0.20210330
clang version 11.1.0

$ ls /nix/store/8ksw8lwn10vmiz5nzhmkpa6i7l05al68-clang-11.1.0/lib/clang/11.1.0
ls: cannot access '/nix/store/8ksw8lwn10vmiz5nzhmkpa6i7l05al68-clang-11.1.0/lib/clang/11.1.0': No such file or directory
```

In contrast this is what the ccls in the 20.09 tree reports:

```
$ ccls --version
ccls version 0.20190823.6
clang version 8.0.1 (tags/RELEASE_801/final)

$ ls /nix/store/xzjgfyaaiz6g2cw69f10xafjpyxfk86q-clang-wrapper-8.0.1/resource-root
include  lib
```

I'm absolutely not experienced with nix or this kind of issues, but this looks related to #126873 to me.

**Comment by tobim** [comment]
It looks like the detection of the resource dir at build time is incorrect. I tried to insert the correct path in the wrapper manually and that seems to work. The correct fix is should probably be in the configure phase instead.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/124246
@gebner

**Comment by gebner** [comment]
> The path is derived from `clang -print-resource-dir` at CMake configure time.

Ah, this won't work, of course.

Our ccls wrapper needs to add an additional option, namely `--init='{"clang": {"resourceDir": "/usr/local/clang/7.0.0"}}'` (with the right directory).

**Comment by cmm** [comment]
can this perhaps be back-ported to release-21.05?

**Comment by Artturin** [comment]
> can this perhaps be back-ported to release-21.05?

https://github.com/NixOS/nixpkgs/pull/129944
