### ISSUE TITLE
Sway doesn't run dbus. Slowdowns and errors.

### ISSUE THREAD

**Issue by alsoijw** [NixOS/nixpkgs#126970]
**Describe the bug**
If dbus is required for the application to work, then this causes either an error when starting them(gnome-terminal), or a long wait for connection (waybar). Adding the line `exec dbus-update-activation-environment --all` to the config solves this problem.

**To Reproduce**
1. Select sway session in GDM
2. Run waybar from config
```
bar {
    swaybar_command waybar
```
3. Run gnome-terminal
```
$ gnome-terminal 
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
$
```

**Notify maintainers**
@primeos 
@Synthetica9 
@ma27

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.10, NixOS, 21.05.git.574173bb561 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.961.1f91fd10406"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
- sway
```

**Comment by Artturin** [comment]
https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start

**Comment by Artturin** [comment]
we should add something like `If you are using an already existing config file, add include /etc/sway/config.d/* to your sway config` to https://github.com/NixOS/nixpkgs/blob/fa0326ce5233f7d592271df52c9d0812bec47b84/nixos/modules/programs/sway.nix#L38

**Comment by primeos** [comment]
Not sure if that would help, IMO it's unlikely that users who already use Sway would have another look at the documentation for the `enable` option. We probably should've added this to the NixOS release notes though. Alternatively we could consider adding a "changelog" to the wiki page: https://nixos.wiki/wiki/Sway
