### ISSUE TITLE
Remmina won't start

### ISSUE THREAD

**Issue by alsvartr** [NixOS/nixpkgs#126964]
**Describe the bug**
nixos.remmina hangs at startup on a clean profile:

~> remmina
Load modules from /nix/store/11rf5xqclqwd2snr7b0fixmiifvcr26x-remmina-1.4.13/lib/remmina/plugins
Remmina plugin glibsecret (type=Secret) has been registered, but is not yet initialized/activated. The initialization order is 2000.
^C

**To Reproduce**
1. install nixos.remmina
2. start remmina

**Expected behavior**
remmina starts up

**Notify maintainers**
@melsigl @ryantm 

**Metadata**
~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.10, NixOS, 21.05.961.1f91fd10406 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"home-manager-20.09, nixos-21.05.961.1f91fd10406, nixos-hardware, nixos-unstable-21.11pre294801.432fc2d9a67"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ryantm** [comment]
Hi, @alsvartr. Sorry you are having trouble, and thanks for the report!

I was not able to reproduce this issue.
1. I moved all my remmina directories `~/.remmina` `~/.config/remmina` and `~/.local/remmina` away
2. Did this:
```
[ryantm@home2:~]$ nix-shell -p remmina

[nix-shell:~]$ remmina
Load modules from /nix/store/z222gxy7501kscxpl6qrnahznz7v504g-remmina-1.4.13/lib/remmina/plugins
Remmina plugin glibsecret (type=Secret) has been registered, but is not yet initialized/activated. The initialization order is 2000.
The glibsecret secret plugin  has been initialized and it will be your default secret plugin
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
Running under GNOME Shell version 40.1

(org.remmina.Remmina:70421): Gtk-WARNING **: 16:05:12.434: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem


^C

[nix-shell:~]$ which remmina
/nix/store/z222gxy7501kscxpl6qrnahznz7v504g-remmina-1.4.13/bin/remmina
```

And remmina started fine for me.

1. Which desktop manager are you using?
2. Maybe try clearing out all those state directories in case something bad is there?

**Comment by alsvartr** [comment]
@ryantm suddenly it starts working after reboot. Maybe because I enabled gnome-keyring daemon, so I assume this was my local issue. I'm using gdm/gnome3.
Anyway thanks for your reply.
