### ISSUE TITLE
monitor.nixos.org is outdated since quite some time

### ISSUE THREAD

**Issue by pSub** [NixOS/nixpkgs#12703]
monitor.nixos.org is outdated since quite some time now. Even some months if I am not mistaken. This time it doesn't seem to be some issue with nixpkgs-monitor but rather with the server. I tried to bring attention to this on the irc channel by pinging e.g. @rbvermaa. However it seems the people that are maintaining those servers are currently really busy. I would be happy to step up as a maintainer for the monitor server, but at least we should make explicit that monitor.nixos.org is out of date.

**Comment by Phreedom** [comment]
I will have some time the next week 
to work on monitor as I'm about to 
finish my current project. And it 
would be nice indeed if we had a 
backup maintainer, because the 
current maintainers(including me) 
aren't available even 90% of the time.

**Comment by vcunat** [comment]
I really liked the service and it made me sad that it wasn't updating info for many months (I think).

**Comment by pSub** [comment]
@rbvermaa @edolstra What are the barriers to introduce a backup maintainer for monitor.nixos.org?

**Comment by zimbatm** [comment]
where is the code and how do you deploy it ?

**Comment by vcunat** [comment]
The code should be on https://github.com/phreedom/nixpkgs-monitor/

**Comment by edolstra** [comment]
Would it be feasible to run monitor on the nixos.org server?

**Comment by zimbatm** [comment]
Can we move this code to the nixos org ? It seems really useful and would be better community-supported.

**Comment by pSub** [comment]
:+1:  for moving the repository to the NixOS organization. I am not sure if it makes sense to run it on the nixos.org server. If we don't test-build updates (which isn't that useful anyways, at least for me) it could be feasible. A monitor instance would help a lot to give everyone a good feeling of the state of nixpkgs.

**Comment by Phreedom** [comment]
The biggest problem for monitor is 
that it needs admin attention: 
updated frequently, sometimes nix-
prefetch-url hangs and such stuff. 
It's very similar to hydra for obvious 
reasons. I run the dev instance on a 
6-core machine at home.

**Comment by Phreedom** [comment]
btw the test-building of updates is in 
fact very useful because it produces 
diff logs. Although for some reasons 
the format of logs on hydra is 
different atm, when it was the same, 
it was very easy to spot new or 
missing dependencies.

**Comment by zimbatm** [comment]
Would it be possible to augment derivations metadata with an update checker ? It would be nice if each project could say: hey, look at this location with this heuristic to find if a new version has been released.

**Comment by vcunat** [comment]
The monitor seems to manage that automatically for most packages already.

**Comment by Phreedom** [comment]
There's a set of algos which work 
automatically somewhat well. Doing it by 
hand ends up with update checkers 
going stale in practice. I wrote about it in 
the nix-dev ML long time ago. Probably 
the only way you can help the monitor is 
by setting meta.repositories.git and 
hoping the tags have a sane naming 
scheme.

**Comment by zimbatm** [comment]
Yeah makes sense, we don't want too much churn.
In a lot of cases we could deduce the meta.repositories.git from the source. What about something like this: https://github.com/zimbatm/nixpkgs/commit/f28f0132d0428b7461ec25c1bb01a215e56665e2 and then tweak mkDerivation so that the meta field is `src.meta // meta` ?

**Comment by Phreedom** [comment]
nixpkgs-monitor uses derivation's meta 
attrs, nor derivation's src meta attrs. 
either way it catches github urls already, 
parses them and grabs tags to analyze 
:) Personally I liked fetchgit days a bit 
more because you could do src = 
fetchgit {url = meta.repositories.git;}

**Comment by ttuegel** [comment]
This appears to be resolved now.

**Comment by pSub** [comment]
monitor.nixos.org is out of date since some time again.

**Comment by Phreedom** [comment]
builds phase seems to either 
fail or hang
@rbvermaa

**Comment by bobvanderlinden** [comment]
I guess this is still a problem. What is needed to get this going again?

**Comment by mogorman** [comment]
monitor.nixos.org doesnt seem to exist any more can we close this issue? @pSub

**Comment by vcunat** [comment]
"The service is looking for admin, I'd say."
