### ISSUE TITLE
External usb mounted only in ro

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#12705]
When I want to mount a my usb drive,it is mounted in ro mode ,even if I mount with mount -o rw,bypassing udisks.

**Comment by heydojo** [comment]
Would you mind
```
cat /etc/os-release
```
and describing the desktop you are using if any.
Cheers :+1:

**Comment by abbradar** [comment]
Check `dmesg` just in case, you may have corrupted filesystem, in which case it's sometimes mounted RO automatically (varies for different filesystems).

**Comment by vcunat** [comment]
Could it be NTFS? I had similar experience due to not having ntfs-3g and in-kernel driver only supporting reading.

**Comment by andsild** [comment]
Can confirm that it worked for me after installing ntfs3g (i.e. I could mount ntfs drives as read/write using mount)

**Comment by pasqui23** [comment]
Yeah it was ntfs3g.
Still would be nice to put some hint in the documentation.

**Comment by concatime** [comment]
My two cents: `ntfs3g` should be added inside `environment.systemPackages` and not within the packages of the user.
