### ISSUE TITLE
Neither of proton games on steam work

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#127068]
Log: https://gist.githubusercontent.com/Kreyren/a194dd5fae0d928b4b105f5117276120/raw/93e4606144deb72dbd89d7c858cd88f12a6ef6b7/gistfile1.txt

### Steps To Reproduce
0. get `steam`
1. Try to play any proton game and expect a failure

### Expected behavior
Being able to play Batman Arkham City and other games

### Additional context
Might be relevant to https://github.com/NixOS/nixpkgs/issues/126189

### Metadata

```console
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.42, NixOS, 21.05.906.cedcf2565c6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.961.1f91fd10406"`
 - channels(kreyren): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

![image](https://user-images.githubusercontent.com/11302521/122205793-eb239900-cea0-11eb-9092-02a308061620.png)

**Comment by Kreyren** [comment]
CC @jagajaga @jonringer

**Comment by jonringer** [comment]
looks like an uninitialized value:
```
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x00000000).
```

**Comment by jansol** [comment]
FWIW a lot of games that have a video intro crash silently with recent proton versions (apparently they started working on a decoder for wmv and maybe others), forcing steam to use proton 5.0-10 works around that by skipping said videos entirely.

**Comment by Kreyren** [comment]
@jansol This is for all games including those that worked without issue on Devuan GNU/Linux before.

**Comment by Kreyren** [comment]
FWIW this is a log from The Binding of Issac: http://ix.io/3qkD

**Comment by jansol** [comment]
After finally updating to a more recent nixos-unstable I'm running into this issue as well. Games relying on DXVK kindly inform me that my graphics card does not support DirectX 11 or simply crash with no useful message. Native games work fine though, and other native applications don't have issues either.

Some relevant-looking lines from log output of a game that uses OpenGL via proton:
```
plasmashell[34610]: pressure-vessel-wrap[34610]: W: Found more than one possible libdrm data directory from provider
[...]
plasmashell[35048]: libGL error: MESA-LOADER: failed to open radeonsi: /overrides/lib/i386-linux-gnu/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /overrides/lib/x86_64-linux-gnu/dri:/overrides/lib/i386-linux-gnu/dri)
plasmashell[35048]: libGL error: failed to load driver: radeonsi
plasmashell[35048]: libGL error: MESA-LOADER: failed to open swrast: /overrides/lib/i386-linux-gnu/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /overrides/lib/x86_64-linux-gnu/dri:/overrides/lib/i386-linux-gnu/dri)
plasmashell[35048]: libGL error: failed to load driver: swrast
plasmashell[35048]: xcb_io.c:617: _XAllocID: Assertion `ret != inval_id' failed.
plasmashell[34982]: pid 34982 != 34981, skipping destruction (fork without exec?)
plasmashell[15438]: Game removed: AppID 262390 "", ProcID 34980
```

**Comment by jonringer** [comment]
Probably related to: https://github.com/NixOS/nixpkgs/issues/126428

**Comment by jansol** [comment]
Maybe, but that does not explain OpenGL also being broken.

**Comment by Kreyren** [comment]
FWIW on non-vulkan systems i have to set `PROTON_USE_WINED3D=1` to avoid using DXVK.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/116646 is what breaks this.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/129805

**Comment by Kreyren** [comment]
Resolved by upgrading on `nixos-unstable` (Porcupine 21.11)

**Comment by TredwellGit** [comment]
Maybe there are multiple issues because DXVK does not work on nixos-unstable for me without https://github.com/NixOS/nixpkgs/pull/129805.
