### ISSUE TITLE
hashes broken for all patches from `hg.libsdl.org`

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#127114]
**Describe the bug**
hashes broken for all patches from `hg.libsdl.org`

For example, evaluating of 
https://github.com/NixOS/nixpkgs/blob/d86f21194aed2b84256509d05f0a527a8c063229/pkgs/development/libraries/SDL/default.nix#L74-L78

results in
```
hash mismatch in fixed-output derivation '/nix/store/4f1idknj4p6rnsbx5rlw2shjzv10kik7-0aade9c0203f':
  wanted: sha256:1y9izncjlqvk1mkz1pkl9lrk9s452cmg2izjjlqqrhbn8279xy50                               
  got:    sha256:0g458iv6pp9sikdch6ms8svz60lf5ks2q5wgid8s9rydhk98lpp5                               
```

Affected versions: at least from `20.03` to `master`

The files are not uploaded to `tarballs.nixos.org`, so I do not know where to get them

Updating hashes is a weird option because it causes mass rebuild

**Comment by kvtb** [comment]
it is caused by mercurial->git migration so unlikely will be fixed in upstream.

**Comment by Artturin** [comment]
#127278
