### ISSUE TITLE
Chromium + enablePepperFlash is now giving me chromium-binary-plugins-flashVersion.2.999.999

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#12710]
This breaks a number of sites because they expect a Flash version of 10,1.

|  |  |
| --- | --- |
| Name: | Shockwave Flash |
| Description: | Shockwave Flash /nix/store/5bz75h4hk1nxbzak1rf7s207gipd6cgq-chromium-binary-plugins-flashVersion.2 r999 |
| Version: | /nix/store/5bz75h4hk1nxbzak1rf7s207gipd6cgq-chromium-binary-plugins-flashVersion.2.999.999 |
| Location: | /nix/store/5bz75h4hk1nxbzak1rf7s207gipd6cgq-chromium-binary-plugins-flash/lib/libpepflashplayer.so |
| Type: | PPAPI (out-of-process) |

**Comment by vcunat** [comment]
What version of nixpkgs?

**Comment by colemickens** [comment]
nixos-unstable @ https://github.com/NixOS/nixpkgs/commit/77f8f35d57618c1ba456d968524f2fb2c3448295

https://github.com/NixOS/nixpkgs-channels/commit/77f8f35d57618c1ba456d968524f2fb2c3448295

**Comment by vcunat** [comment]
Confirmed! @aszlig: I suspect your change.

**Comment by vcunat** [comment]
Confirmed. Fixed for now by reverting that change on both master and 15.09, but in the long term we rather need a bug-free version of that change.

**Comment by colemickens** [comment]
The file referenced here doesn't exist on my machine, as far as I can tell: https://github.com/NixOS/nixpkgs/commit/38c77bb72c9aec6f9e8ecb06a56032692de42e0c#diff-2a0af65f37b0a602f7f0b20263c50ed2R98

**Comment by colemickens** [comment]
Looking at the output in the chromium-binary-plugin-flash directory in the store... Previously it was just a string `20.0.0.228`. Now it was a path to a file that didn't exist: `/nix/store/5bz75h4hk1nxbzak1rf7s207gipd6cgq-chromium-binary-plugins-flashVersion`

Actually, it looks like `$flashVersion` is empty and is getting populated with `${flash}Version`.

**Comment by aszlig** [comment]
@vcunat: Going to look into that when I get home...

**Comment by colemickens** [comment]
@aszlig don't know if you saw, but I have a PR that fixes it.

**Comment by aszlig** [comment]
@colemickens: Ah thanks, will have a look at it.
