### ISSUE TITLE
Remove `node_` prefix in buildNodePackage

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#127137]
Here's the offending line: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-env.nix#L400

This results in all packages built with NodeJS to have a `node_` prefix in their name. One of the consequences is that it totally breaks repology: <https://repology.org/projects/?search=node_&inrepo=nix_unstable>. (Of course they could add a normalization script for this, but I think it's really on us here). A few packages override the `name` in the resulting derivation, but this isn't a good solution either IMO.

The file apparently is generated by node2nix. I don't know if this is an upstream issue, or if that change should be made only for nixpkgs.

CC @svanderburg

**Comment by kidonng** [comment]
Perhaps there should be a note somewhere, or else people following this line

> [Add and commit all modified and generated files.](https://github.com/NixOS/nixpkgs/blob/e195c3cf6ffa0f4e74633cf269367702fdaf3f96/doc/languages-frameworks/node.section.md?plain=1#L47)

May accidentally submit the `node-env.nix` generated by `node2nix`, before svanderburg/node2nix#243 is resolved.

(Or perhaps reviewers will handle this, not sure 🤷‍♀️)

**Comment by SuperSandro2000** [comment]
We pulled in a patch so this shouldn't be a problem.
