### ISSUE TITLE
ghc801: circle-packing needs bump to 0.1.0.5, because of upper bounds

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#12727]
I have a commit, is that desired?

**Comment by peti** [comment]
Sure, if you have a patch that fixes the issue, please open a PR! The same is true for https://github.com/NixOS/nixpkgs/issues/12728 and https://github.com/NixOS/nixpkgs/issues/12726.

**Comment by deepfire** [comment]
Closing, since it's considered an externality to the project.
