### ISSUE TITLE
Firefox: installing too many fonts crashes the content process

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#127224]
**To Reproduce**
1. install `firefox` and `google-fonts`
2. attempt to load any webpage in firefox
3. observe "tab has crashed" message in the GUI and a lot of "too many file handles for one message" errors in stdout
4. after removing `google-fonts` everything is fine again

**Expected behavior**
webpages load normally

**Notify maintainers**
@edolstra @mweinelt 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.11.git.c02751f4069M (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre295280.fa0326ce523"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: firefox
```

**Comment by mweinelt** [comment]
I have google-fonts installed and my content panes do not crash. I use fission and webrender, maybe that changes things? Also I've never witnessed this even with fresh profiles, which I regularly rely on to test updates.

**Comment by jansol** [comment]
I have gfx.webrender.all on but everything else is on the default values.

**Comment by jansol** [comment]
I also don't use fission. Could this be amplified by the number of CPU cores somehow? I have 32 logical cores and `about:support` shows 8 content processes and two others.

**Comment by mweinelt** [comment]
Fission enabled, ~20 processes, 6C/12T

**Comment by Obikawa** [comment]
youtube.com has started to crash after applying the today's batch of updates on unstable-small. Any other website I opened so far has been fine, however. Of those GitHub is definitely the most complex one. On the other hand, youtube crashes so reliably and quickly, that watching anything is close to impossible.

I do have the full Noto Fonts collection installed.

**Comment by jansol** [comment]
Whatever was the problem, installing google-fonts seems to no longer crash firefox so I'll just close this for now.
