### ISSUE TITLE
mdadm udev rules have references to /usr/bin

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#12722]
I got this on udev rules build:
```
Consider fixing the following udev rules:
/nix/store/pkam1pax1b46n2bzn3axkd3zi158a7fn-mdadm-3.3.4/lib/udev/rules.d/63-md-raid-arrays.rules
/nix/store/pkam1pax1b46n2bzn3axkd3zi158a7fn-mdadm-3.3.4/lib/udev/rules.d/64-md-raid-assembly.rules
```

I'm wary of touching these because I don't have an mdraid system to test.

cc @aszlig @wkennington (people who updated the package recently)

**Comment by aszlig** [comment]
Probably caused by 5e227e6f1d047822972fa75c1b913aaa82e5de1f, will fix it once I get home.
