### ISSUE TITLE
The URL to the Nix expression linked from the package list is broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12729]
I'm not sure what generates the package list, but if you go to http://nixos.org/nixos/packages.html and search for something, then look at the linked "Nix expression" that should take you to github, the URLs it gives us are all broken.

**Comment by vcunat** [comment]
Could you be more specific? I just tried several of those links and none of them were broken. Note that the links are to 15.09, in case you tried some new stuff that isn't on that branch.

**Comment by copumpkin** [comment]
Sorry, I assumed they were all broken. Try searching for `lapack`. You'll get some `atlas` and `lapack` results. If you click on any of them, there's stuff like

```
Nix expression:	pkgs/development/libraries/science/math/atlas/default.nix
```

And although the path displayed to the user is correct, the underlying hyperlink takes us to a broken GitHub URL.

**Comment by vcunat** [comment]
This seems to be some edge case in https://github.com/NixOS/nixos-homepage/issues/48.

**Comment by copumpkin** [comment]
Ah, makes sense. I'll just close this then, but we should get @davidak or @edolstra to reopen that one.
