### ISSUE TITLE
[Hydra failure] attribute 'elkPackages' missing, at /build/source/pkgs/tools/misc/logstash/6.x.nix:58:30

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#127274]
Hydra is failing
from the [logs](https://hydra.nixos.org/build/145812125/nixlog/1), I can only point to this [commit](https://github.com/NixOS/nixpkgs/commit/9011d5975855649ca68423ac33e97bdf8a4bd1ef#)
cc @roberth 
Since this commit is from the 23rd of march, I might be wrong on this. Don't take this as a blame, but more as a, let's figure out what is happening together. It seems you might be the most knowledgeable person.

**Comment by collares** [comment]
`nixosTests.elk` is only non-`{}` for `x86_64-linux`...

https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/all-tests.nix#L115

...while logstash supports all Unix platforms:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/logstash/6.x.nix#L53

But if that's the cause, why would `find-tarball.nix` suddenly start caring about other platforms?

**Comment by roberth** [comment]
This job has been robust against this inconsistency in `tests` until a change in the last 2 days.
I hope we can repair this recent change, because that will save complexity in the packages. I'll attempt to git bisect.

**Comment by vcunat** [comment]
Bisected to PR #125973, though I'm not sure that really helps.

_I misread your post and didn't think you were bisecting already._

**Comment by roberth** [comment]
No problem! My bisect completed just now and returned d1d37feb6d21180b7f7b47cf681613a09228da0a, which is a master->staging-next merge.

<details><summary>bisect log</summary>

I still consider myself somewhat of a novice when it comes to bisecting, so I might have made a mistake.

bisect run command

```
git bisect run nix-build pkgs/top-level/release.nix -A tarball
```

log

```
git bisect start
# bad: [c06cb69ca0dc02b37e27104ac8415c3cab173328] networkmanager: fix updateScript
git bisect bad c06cb69ca0dc02b37e27104ac8415c3cab173328
# good: [0747387223edf1aa5beaedf48983471315d95e16] Merge pull request #126998 from Artturin/update-discord
git bisect good 0747387223edf1aa5beaedf48983471315d95e16
# bad: [2d104c99a7d99ead0a9eeb74f1f523aa77aae743] Merge master into staging-next
git bisect bad 2d104c99a7d99ead0a9eeb74f1f523aa77aae743
# good: [39f8014bf704011154a2b5858f50ca5d42788f9b] Merge master into staging-next
git bisect good 39f8014bf704011154a2b5858f50ca5d42788f9b
# good: [f36f78c8034efd05eb5f47bdd51ed1375faf70fb] Merge master into staging-next
git bisect good f36f78c8034efd05eb5f47bdd51ed1375faf70fb
# good: [212846c302a1e805d325b256111e6833f2ae30ba] Merge master into staging-next
git bisect good 212846c302a1e805d325b256111e6833f2ae30ba
# bad: [d1d37feb6d21180b7f7b47cf681613a09228da0a] Merge branch 'master' into staging-next
git bisect bad d1d37feb6d21180b7f7b47cf681613a09228da0a
# good: [ec4b7ebf8686e1162e2e7406996a2650a34870d4] Merge master into staging-next
git bisect good ec4b7ebf8686e1162e2e7406996a2650a34870d4
# good: [13f31f60bf933de43c4b4f5c6601a7a2376cd334] Merge master into staging-next
git bisect good 13f31f60bf933de43c4b4f5c6601a7a2376cd334
# good: [f2ba460019c8ceb7af3967520f98a6836e759217] Merge master into staging-next
git bisect good f2ba460019c8ceb7af3967520f98a6836e759217
# good: [91171e295574bd7721cafeaf4200c807952275a7] Merge branch 'master' into staging-next
git bisect good 91171e295574bd7721cafeaf4200c807952275a7
# first bad commit: [d1d37feb6d21180b7f7b47cf681613a09228da0a] Merge branch 'master' into staging-next
```

</details>

Note the the tarball function removes `meta` and `passthru`. Perhaps an easy solution is to remove `tests` as well. I don't suppose we have many tarballs that are only ever referenced through `passthru.tests`?

**Comment by vcunat** [comment]
The commit you found shows a different error for me:
```
$ nix build -f pkgs/top-level/release.nix tarball
error: syntax error, unexpected OR, at /home/admin/nix/nixpkgs-x/pkgs/servers/x11/xorg/default.nix:3135:1
```

**Comment by vcunat** [comment]
As you say, it would be easy enough way to work around this particular issue and down-sides seem very low, so perhaps 🤷🏽

BTW, even if a couple tarballs would get missed, we apparently had much larger issues unnoticed: https://discourse.nixos.org/t/is-tarballs-nixos-org-stuck-at-19-09/13647

**Comment by aszlig** [comment]
Note that the actual commit that introduces this is 3884ff70badca0c93c717e6190946a9a2846e948.

**Comment by happysalada** [comment]
@blaggacao maybe you have some insight?

**Comment by aszlig** [comment]
The issue is that the `passthru` attribute from [here](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/nixos/lib/testing-python.nix#L192) didn't get passed to the [actual functions](https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/nixos/lib/testing-python.nix#L219-L230) generating the runner, as it was prior to this commit.

**Comment by blaggacao** [comment]
I'll be on it in a minute.

**Comment by aszlig** [comment]
@blaggacao: See #127346

**Comment by blaggacao** [comment]
@aszlig thanks a lot for covering my **"! :smile:
