### ISSUE TITLE
netdata: cloud connection issues

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#127375]
Notes on making netdata cloud work. /cc @leotaku @Izorkin (others?)

- to register the node with the script, I had to run have the netdata package in my path. I suppose that's to be expected :)
- the script didn't have access to `openssl` so I had to run it under a nix-shell that provided it
- after claiming, the script tried to run netdatacli to restart it but it was looking for it under sbin
- after restarting netdata, CPU spiked to 100%. After some searching, it turns out that netdata logs to /var/log/netdata and the permissions on the cloud private key were incorrect.
- netdatacli can't connect to the service, it seems to not know where to connect

action items, I think:
- [ ] patch claim script so that it finds openssl and netdatacli
- [ ] patch netdatacli so it uses the right socket
- [ ] make sure `/var/lib/netdata/cloud.d/private.pem` is readable by netdata
- [ ] make netdata log to journalctl via stdout/stderr instead of /var/log

**Comment by leotaku** [comment]
Yeah, I've got those patches on a local checkout, just never got to integrating them upstream.

>  patch claim script so that it finds openssl and netdatacli

Yeah, I have that patch, will create a PR soon.

>  patch netdatacli so it uses the right socket

I've managed to fix this issue by unsetting the `PrivateTmp` option of the Netdata systemd service. Should be an easy fix as long as nobody insists on Netdata having to use a private temp folder.

>  make sure /var/lib/netdata/cloud.d/private.pem is readable by netdata

I am pretty sure the `netdata-claim.sh` script ensures this is the case anyways.

>  make netdata log to journalctl via stdout/stderr instead of /var/log

This already seems to be the case on all of my machines. Could you maybe check if your Netdata configuration contains the following lines? You should be able to access your current configuration at `http://your-netdata-endpoint.example.com/netdata.conf`.

```
access log = syslog
debug log = syslog
error log = syslog
```

**Comment by wmertens** [comment]
- claim patch: I think you don't patch the path to netdatacli? Of course as long as it's not working it doesn't really matter :)
- pem permissions: no, I had to that manually. I think it's because I ran it as root and it couldn't detect the correct user because `get_config_value` has the wrong paths etc
- journald: Odd - I used pkgs.override to get the unstable netdata pkg into 21.05 and the module definition is the same as on master so I don't understand where the syslog config comes from. For me this returns

  ```
	# debug log = /var/log/netdata/debug.log
	# error log = /var/log/netdata/error.log
	# access log = /var/log/netdata/access.log
  ```

  Do you have an override somewhere?

Thanks for your PRs!

**Comment by leotaku** [comment]
> claim patch: I think you don't patch the path to netdatacli

Instead of patching that path, my PR removes the line that removes the `sbin` directory that contains the `netdatacli` command.

> pem permissions: no, I had to that manually

Weird, I just copied the default claim command from the Web UI and all the generated files seem to have the correct owners and permissions.

> journald: Odd - I used pkgs.override to get the unstable netdata pkg into 21.05 and the module definition...

Sorry about that, you are correct. I had a local config change that set the logs to all go into syslog and just forgot about it. Interestingly enough, the example Netdata configuration shown in the `configuration.nix` manual also contains these settings, so maybe they should be made the default.

**Comment by wmertens** [comment]
> Instead of patching that path, my PR removes the line that removes the sbin directory that contains the netdatacli command.

ah right - that's not really standard nixpkgs behavior I think, but your PR got approved so maybe not :)

> pem permissions

I tried and if the cli tool is working it reads the config and knows the user. In my case it was not working yet so you have to run it as root and then fix the permissions

> manual also contains these settings, so maybe they should be made the default.

yes I agree, we're a journald distro. The manual could show the reverse setting.
Ideally the 3 log types are tagged differently in journald but I think that would require support from netdata

**Comment by wmertens** [comment]
So, current status with the /run patch merged yesterday, everything is working! The claim command correctly detects the user and restarts the service.

**Comment by gerhard** [comment]
@wmertens Do you know how to claim a netdata agent on NixOS 22.05?

I couldn't figure out how to connect to Netdata Cloud, and this is the only issue that is somewhat related to my issue.

Thank you!

**Comment by wmertens** [comment]
I made this module I'm calling our-netdata.nix and just adding to `imports`:

```nix
# Module to prototype what should go in the official module
{ config, pkgs, lib, ... }:
let
  cfg = config.services.our-netdata;
  goConf = metrics: pkgs.runCommand "goConf" { }
    ''
      mkdir -p $out
      cp ${pkgs.netdata}/lib/netdata/conf.d/go.d.conf $out
      cp ${pkgs.netdata}/lib/netdata/conf.d/go.d/* $out
      chmod +w $out/*
      ${pkgs.yq-go}/bin/yq -Pi e '.jobs += ${builtins.toJSON metrics}' $out/prometheus.conf
    '';

in

{
  options.services.our-netdata = {
    prometheusMetrics = lib.mkOption {
      type = with lib.types; listOf attrs;
      default = [ ];
    };
    register = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to register the node with Netdata Cloud";
    };
    token = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Claim token, copy this from the --claim-token= argument in the Netdata UI";
    };
    rooms = lib.mkOption {
      type = lib.types.str;
      default = "";
      description = "Claim room IDs, copy this from the --claim-rooms= argument in the Netdata UI";
    };
    url = lib.mkOption { type = lib.types.str; default = "https://app.netdata.cloud"; };
  };
  config = {
    services.netdata.enableAnalyticsReporting = true;
    services.netdata.config = {
      global = {
        "debug log" = "/dev/null";
        "access log" = "syslog";
        "error log" = "syslog";
        # Limit memory usage
        "memory mode" = "dbengine";
        "page cache size" = 16;
        "dbengine multihost disk space" = 512;
      };
      "plugin:go.d" = lib.mkIf (cfg.prometheusMetrics != [ ]) {
        # To configure go.d we must create an entire config directory
        "command options" = "-c ${goConf cfg.prometheusMetrics}";
      };
    };

    # It's ok to keep running during system activation    
    systemd.services.netdata.stopIfChanged = false;
    systemd.services.netdata.serviceConfig.ExecPostStart = ''
      while [ "$(netdatacli ping)" != pong ]; do sleep 0.5; done
    '';

    systemd.services.registerNetdata =
      assert !cfg.register || (cfg.token != "" && cfg.rooms != "");
      lib.mkIf cfg.register {
        description = "Netdata Cloud Registration";
        requires = [ "netdata.service" ];
        after = [ "netdata.service" ];
        wantedBy = [ "multi-user.target" ];
        path = with pkgs; [ curl openssl gawk netdata ];
        serviceConfig = {
          Type = "oneshot";
          TimeoutSec = 60;
        };
        script = ''
          if [ "$(netdatacli ping)" != pong ]; then
            sleep 10
            if [ "$(netdatacli ping)" != pong ]; then
              echo netdata not running >&2
              exit 200
            fi
          fi
          if ! netdata-claim.sh -url=${cfg.url} -token=${cfg.token} -rooms=${cfg.rooms}; then
            code=$?
            # handle already-registered response
            if [ $code -ne 13 ]; then
              exit $code
            fi
            exit 0
          fi
        '';
      };
  };
}
```

**Comment by gerhard** [comment]
Thank you @wmertens!

This felt wrong, but it did the job:

```console
systemctl status netdata
● netdata.service - Real time performance monitoring
     Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-06-12 10:19:12 BST; 23h ago
   Main PID: 16766 (netdata)
         IP: 12.9G in, 110.8M out
         IO: 92.0K read, 448.4M written
      Tasks: 65 (limit: 77049)
     Memory: 210.2M
        CPU: 1h 12min 6.171s
     CGroup: /system.slice/netdata.service
             ├─16766 /nix/store/fmfk43ngn4bwjzzdl7zw8lcbjd7b7b9w-netdata-1.34.1/bin/netdata -P /run/netdata/netdata.pid -D -c /etc/netdata/netdata.conf
             ├─16772 /nix/store/fmfk43ngn4bwjzzdl7zw8lcbjd7b7b9w-netdata-1.34.1/bin/netdata --special-spawn-server
             ├─16825 /nix/store/fmfk43ngn4bwjzzdl7zw8lcbjd7b7b9w-netdata-1.34.1/libexec/netdata/plugins.d/go.d.plugin 1
             ├─16826 /nix/store/w2g0a9qxxhvajnbgblngi1cg3a6xdp5g-wrapped-plugins/libexec/netdata/plugins.d/apps.plugin 1
             └─65410 /nix/store/fmfk43ngn4bwjzzdl7zw8lcbjd7b7b9w-netdata-1.34.1/libexec/netdata/plugins.d/nfacct.plugin 1

Jun 12 10:19:12 x22 systemd[1]: Started Real time performance monitoring.
Jun 12 10:19:12 x22 netdata[16766]: Found 0 legacy dbengines, setting multidb diskspace to 256MB
Jun 12 10:19:12 x22 netdata[16766]: Created file '/var/lib/netdata/dbengine_multihost_size' to store the computed value
Jun 12 10:19:12 x22 netdata[16766]: 2022-06-12 10:19:12: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
Jun 12 10:19:12 x22 netdata[16766]: 2022-06-12 10:19:12: netdata INFO  : MAIN : Created file '/var/lib/netdata/dbengine_multihost_size' to store the computed value

PATH=nix/store/fmfk43ngn4bwjzzdl7zw8lcbjd7b7b9w-netdata-1.34.1/bin/:$PATH netdata-claim.sh -url=https://app.netdata.cloud -token=xxx
```

I will use your example above to do it properly and add a oneshot systemd service.
