### ISSUE TITLE
librealsense (and related python packages) unsupported on aarch64

### ISSUE THREAD

**Issue by IndianBoy42** [NixOS/nixpkgs#127363]
**Describe the bug**
librealsense cannot be built on/for aarch64-linux. I see that the derivation says it is not supported on aarch64-linux but I also know it is possible to compile the library normally on that platform as I have done it before. So I think its just a problem with the derivation for now.

I am willing to help in the work to fix the recipe, and test the fixes, but I am relatively new to the nix language and build system. I have attached the error message I get, could someone point me in the direction I should be looking to fix it?

**To Reproduce**
1. `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix-build '<nixpkgs>' -A pkgsCross.aarch64-multiplatform.python38Packages.pyrealsense2WithCuda`

**Screenshots**
```
# Lots of Build Output, and then
atk/meson.build:161: WARNING: Keyword argument "requires" defined multiple times.
WARNING: This will be an error in future Meson releases.
Configuring atkversion.h using configuration
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
WARNING: Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.
Program glib-genmarshal found: YES (/nix/store/d9zs9xg86lhqjqni0v8h2ibdrjb57fn4-glib-2.68.2-dev/bin/glib-genmarshal)
Program glib-mkenums found: YES (/nix/store/d9zs9xg86lhqjqni0v8h2ibdrjb57fn4-glib-2.68.2-dev/bin/glib-mkenums)
Did not find CMake 'cmake'
Found CMake: NO
Build-time dependency gobject-introspection-1.0 found: NO

atk/meson.build:138:2: ERROR: Pkg-config binary for machine MachineChoice.BUILD not found. Giving up.
```

**Additional context**

**Notify maintainers**

@brian-dawn 

**Metadata**
```
  /nix/store/rmhwi0jcya8f87gzk2jjdwv4hifmmbb4-nix-info
copying path '/nix/store/rmhwi0jcya8f87gzk2jjdwv4hifmmbb4-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-7614-generic, Pop!_OS, 20.10`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels($USER): `"nixpkgs-21.11pre295576.4b7c8d538e1"`
 - nixpkgs: `/home/$USER/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by brian-dawn** [comment]
Hello!

I tried it and got similar errors building graphite, though I can get it to build when I use the `withoutCuda` versions of the libraries so maybe that's a good place to start? I'm not sure what the issue is unfortunately.

**Comment by prusnak** [comment]
I fixed the build of `librealsense` on aarch64-darwin and aarch64-linux in PR https://github.com/NixOS/nixpkgs/pull/127547

* `pyrealsense2WithCuda` will not work on aarch64 unless somebody fixes the build of `cudatoolkit` package on aarch64
* `pyrealsense2WithoutCuda` theoretically should work, but in reality the build of `scipy` which is a dependency fails on aarch64

Will you please open two new issues for `cudatoolkit` and `scipy` not available for aarch64? The build failures you see have nothing to do with librealsense.
