### ISSUE TITLE
python3Packages.ortools cannot be found in PYTHONPATH

### ISSUE THREAD

**Issue by sephii** [NixOS/nixpkgs#127349]
**Describe the bug**
The Nixpkgs manual contains [a section explaining how to use a virtualenv with Python packages from nixpkgs](https://nixos.org/manual/nixpkgs/stable/#how-to-consume-python-modules-using-pip-in-a-virtual-environment-like-i-am-used-to-on-other-operating-systems). This method doesn’t work with `python3Packages.ortools`.

**To Reproduce**
Create a `shell.nix` file with the following contents (this is copied directly from the manual):

```nix
let
  pkgs = import (builtins.fetchGit {
    url = "https://github.com/NixOS/nixpkgs";
    ref = "release-21.05";
    rev = "dbfaab83a8b0ed29d54fd50b187ebd551f58aa26";
  }) { };
  pythonPackages = pkgs.python37Packages;
in pkgs.mkShell {
  name = "impurePythonEnv";
  buildInputs = [
    pythonPackages.python
    pythonPackages.venvShellHook
    pythonPackages.ortools
  ];
  venvDir = "./.venv";
  postVenvCreation = ''
    unset SOURCE_DATE_EPOCH
  '';

  postShellHook = ''
    unset SOURCE_DATE_EPOCH
  '';
}
```

Running `nix-shell --run "python -c 'import ortools'"` results in `ModuleNotFoundError: No module named 'ortools'`.

**Expected behavior**
The module should be found.

**Additional context**
Checking the `PYTHONPATH` environment variable shows that the or-tools package is installed:

```
$ echo $PYTHONPATH
/nix/store/jbysjlvvh9cnvs8d8ls1x2y11q8pjjqh-python3-3.7.10/lib/python3.7/site-packages:/nix/store/7pslh3gg07wz495vv5cfldv9dmq0k8dq-or-tools-9.0-python/lib/python3.7/site-packages
```

However the directory contains an additional level that prevents Python from finding the module:

```
$ ls -l /nix/store/7pslh3gg07wz495vv5cfldv9dmq0k8dq-or-tools-9.0-python/lib/python3.7/site-packages
total 8
-r--r--r-- 1 root root   42 Jan  1  1970 easy-install.pth
dr-xr-xr-x 4 root root 4096 Jan  1  1970 ortools-9.0.9999-py3.7-linux-x86_64.egg
```

Adding the following hack to `postShellHook` fixes it:

```
postShellHook = ''
    ...
    export PYTHONPATH=$PYTHONPATH:${pythonPackages.ortools}/lib/${pythonPackages.python.libPrefix}/site-packages/ortools-9.0.9999-py3.7-linux-x86_64.egg
'';
```

Also the following works, but it cannot be used in conjunction with a virtualenv:

```
$ nix-shell -E "let pkgs = import <nixpkgs> {}; in (pkgs.python3.withPackages (ps: [ ps.ortools ])).env" --run "python -c 'import ortools'"
```

I have no idea how eggs work in Python so I can’t really say how this problem should be fixed. But I guess the `PYTHONPATH` should be fixed to expose the ortools module.

**Notify maintainers**
@andersk 

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.1075.246502ae2d5 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(sephi): `"home-manager-21.05"`
 - channels(root): `"nixos-21.05.1075.246502ae2d5, nixos-hardware, nixos-unstable-21.11pre295280.fa0326ce523, taxi"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FliegendeWurst** [comment]
This was fixed. Likely by #194337
