### ISSUE TITLE
Contributing packages with missing dependencies 

### ISSUE THREAD

**Issue by ulrikstrid** [NixOS/nixpkgs#127372]
What is the best/proper way to contribute new packages with a lot of missing dependencies?
Can I create a big PR with many commits (one for each dependency)?
Or is it better to create many PRs?

If this is better asked somewhere else please point me in that direction

**Comment by Atemu** [comment]
Adding or updating dependencies of the actual package the PR intends to add is fine. Just make sure you split them into commits and follow the contributing guidelines (i.e. "foo: init at 4.2.0", "bar: init at 13.37" etc.). A PR should be a package that accomplishes a certain goal and every commit inside it should be one step towards that goal.

Probably better to ask things like these in Discourse or Matrix.
