### ISSUE TITLE
Security backports should be marked as such

### ISSUE THREAD

**Issue by Ma27** [NixOS/nixpkgs#127463]
**Describe the bug**

If a security fix gets backported by our new GH action, I'd expect the bot to add the [`1. severity: security`](https://github.com/NixOS/nixpkgs/labels/1.severity%3A%20security)-label to the backport PR automatically.

Currently this has to be done manually (see for instance https://github.com/NixOS/nixpkgs/pull/127131), but it would IMHO be a nice addition to let the backport-action do this.

**Notify maintainers**
@domenkozar

**Comment by lheckemann** [comment]
Still relevant.

**Comment by lheckemann** [comment]
Depends on https://github.com/zeebe-io/backport-action/issues/87

**Comment by lheckemann** [comment]
Fixed in https://github.com/zeebe-io/backport-action/pull/303 but I don't want to deal with CLA crap :(

**Comment by Ma27** [comment]
@lheckemann since it's MIT licensed, can't we just use your patch in a fork in the nixos org? %)

**Comment by Ma27** [comment]
This seems to be happening nowadays: https://github.com/NixOS/nixpkgs/pull/300527, https://github.com/NixOS/nixpkgs/pull/300115, https://github.com/NixOS/nixpkgs/pull/299815, https://github.com/NixOS/nixpkgs/pull/299541
