### ISSUE TITLE
`nixos-rebuild build --flake` no longer leaves `result`

### ISSUE THREAD

**Issue by chkno** [NixOS/nixpkgs#127447]
**Describe the bug**
Since 456aa2db499409ab500d98c464b3321d4b7cecc3, `nixos-rebuild build --flake` no longer leaves `result` -- there's no way to get the nix store path of the toplevel that it builds.

**To Reproduce**
```
cd "$(mktemp -d)"
nix-shell -p nixUnstable --run 'nix --experimental-features "nix-command flakes" flake init --template templates#simpleContainer'
nixos-rebuild build --flake .#container || "$(nix-build --no-out-link --expr 'with import <nixpkgs> {}; nixos-rebuild.override { nix = nixUnstable; }')/bin/nixos-rebuild" build --flake .#container
ls -l result
```

**Expected behavior**
`ls` displays `result -> /nix/store/...`.  This is what happens in 20.09.

**Actual behavior**
`ls` displays `ls: cannot access 'result': No such file or directory` in 21.05.

**Additional context**
Since 456aa2db499409ab500d98c464b3321d4b7cecc3, the `result` link is written to `tmpDir` and deleted as `nixos-rebuild` finishes.

**Notify maintainers**
@chvp @domenkozar

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.40, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-19.09.2520.289466dd6a1, nixos-20.03.2790.b4dac6714d7, nixos-20.09.3662.d88cdc7bc1a, nixos-21.05.804.5de44c15758, nixos-21.05.804.5de44c15758, nixos-21.05pre284548.1fe6ed37fd9"` (some private channels omitted)
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by chvp** [comment]
Should already be fixed: https://github.com/NixOS/nixpkgs/pull/123720

**Comment by asymmetric** [comment]
@chkno could you confirm if this fixed?

**Comment by chkno** [comment]
Yes, this is fixed.
