### ISSUE TITLE
nixops-1.7: no longer builds on master and 21.05

### ISSUE THREAD

**Issue by tollb** [NixOS/nixpkgs#127423]
**Describe the bug**
The nixops-1.7 package is failing to build on NixOS 21.05 after a recent upgrade to the python certifi package (PR #125996) enabled a test that fails with python2. The certifi package is an indirect dependency of nixops-1.7.

**To Reproduce**
The failing build can be viewed on hydra: https://hydra.nixos.org/build/145417618

**Expected behavior**
Ideally, the nixops-1.7 package will continue to build and remain available until a newer release of nixops is available.

**Notify maintainers**

@AmineChikhaoui @edolstra @rbvermaa

CC: @fabaff @dotlambda @adisbladis 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.git.729e236f7a0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `""`
 - nixpkgs: `/etc/nixos/nixpkgs`
 
NOTE: nixops-1.7 is still available when running with the system configuration above. The failing build is visible on hydra, as described in the "To Reproduce" section above.

I plan to file a PR that will disable the python certifi tests for python2 in pkgs/development/python-modules/certifi/default.nix. The PR will probably need to be filed against staging and require a backport to 21.05, if accepted.

As the certifi tests were just enabled, removing them for python2 is unlikely to introduce new issues. The certifi library provides two functions: where() and contents(). The contents() function fails in python2. However, the where() function still seems to work and appears to be the function used by the python requests library (used by boto).

As a note, the underlying issue with python2 compatibility seems to predate the certifi version bump in PR #125996. The newer certifi is primarily an update to the certificate file:

```
$ git diff --numstat 2020.12.05 2021.05.30
1       1       LICENSE
1       1       certifi/__init__.py
230     298     certifi/cacert.pem
```
See comparison here: https://github.com/certifi/python-certifi/compare/2020.12.05...2021.05.30

Thanks to @dotlambda for helping me to better understand this issue on the NixOS Dev matrix yesterday.

Maintainer information:
```yaml
attribute: nixops
# a list of nixos modules affected by the problem
module:
```

**Comment by tollb** [comment]
Thanks for following-up and taking the time to provide a PR, @dotlambda.

**Comment by aanderse** [comment]
I'm sad that the choices I have in `21.05` are a `nixops` package with `knownVulnerabilties` **or** a package called `nixopsUnstable` :disappointed:

**Comment by codygman** [comment]
This also just now broke my update, luckily I can do without nixops for a bit. Or maybe since this isn't the first time its dependency chain broke that justifies me moving to deploy-rs :mag:

**Comment by SebTM** [comment]
I thought about making PR to unstable/21.05 reverting change to exclude Phython 2 until this is fixed? Is this an option? (Worked locally for me but switched to nixopsUnstable for now)

**Comment by wamserma** [comment]
FWIW the last version of certifi that seems to support Python 2 is 2020.04.05.1 
Pinning that one for nixops-1.7 would be ugly, as it is an indirect dependency through boto and requests.
This might be a reasonable solution for 21.05, though.
Until then, the best advice might be to either use  nixops-1.7 from an older channel or switch to nixops-unstable/2.0.0-pre

**Comment by clefru** [comment]
I asked for a revert on the Python 2 support drop on the "certifi" package. That package has almost no code and I speculate that Python 2 support was dropped to be a "good citizen". I argued that this sets up older code to have holes in their certificate checking. Not sure if I will get any traction with the maintainer though.

See https://github.com/certifi/python-certifi/commit/5efdd48f719d9c3c7c8f9a812da2256d088eab78

**Comment by domenkozar** [comment]
If anyone else hits this and can't upgrade yet, I've written an overlay that applies the new package:

```nix

self: super:

let
  # this is needed until haskell.nix bumps 21.05 channel
  python = super.python.override {
    packageOverrides = self: super: {
      certifi = self.callPackage ./certifi.nix {};
    };
  };
in
{
  python2Packages = python.pkgs;

  datadog-integrations-core = extras:
    super.callPackage (super.path + "/pkgs/tools/networking/dd-agent/integrations-core.nix")
      {
        python = python;
        extraIntegrations = extras;
      };
}
```
