### ISSUE TITLE
faust2 won't build anymore

### ISSUE THREAD

**Issue by bburdette** [NixOS/nixpkgs#12749]
a few weeks ago I was able to successfully install faust2 (nixos.faust), but today it looks like its broken.  I'm on the unstable channel.  

```
[bburdette@nixosthe1:~/code/faustthings/faust-2.0.a41]$ nix-env -iA nixos.faust
installing ‘faust-2.0-a41’
these derivations will be built:
  /nix/store/fwy9lfqhfq6b7kcyp26pf93b4xi12552-faust-2.0-a41.drv
building path(s) ‘/nix/store/5rsqv2c2a3nsrff1c1lgw69bcd30v6d0-faust-2.0-a41’
unpacking sources
unpacking source archive /nix/store/3zf5h1w7kxlrlh3dkwxnbyiglw4cicg7-faust-2.0.a41.tgz
source root is faust-2.0.a41
setting SOURCE_DATE_EPOCH to timestamp 1444409208 of file faust-2.0.a41/windows/template.props
patching sources
configuring
no configure script, doing nothing
building
make flags: SHELL=/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash  prefix=/nix/store/5rsqv2c2a3nsrff1c1lgw69bcd30v6d0-faust-2.0-a41 LLVM_CONFIG='/nix/store/m5b0r6lznlqmv9dzbc2vhyw1v3n8vvk5-llvm-3.7.1/bin/llvm-config' world   
/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash: git: command not found
/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash: git: command not found
/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash: git: command not found
/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash: git: command not found
/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash: git: command not found
/nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash: git: command not found
make -C compiler -f Makefile.unix prefix=/nix/store/5rsqv2c2a3nsrff1c1lgw69bcd30v6d0-faust-2.0-a41
make[1]: Entering directory '/tmp/nix-build-faust-2.0-a41.drv-0/faust-2.0.a41/compiler'
g++ -g -Wall -Wuninitialized  -Wno-parentheses -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -DINSTALL_PREFIX='"/nix/store/5rsqv2c2a3nsrff1c1lgw69bcd30v6d0-faust-2.0-a41"' -O1 -fPIC -Wall -Wuninitialized -fvisibility=hidden -Wno-overloaded-virtual -Wno-parentheses -I. -Iboxes -Ierrors -Ievaluate -Inormalize -Iparser -Ipropagate -Iparallelize -Isignals -Itlib -Idraw -Idraw/device -Idraw/schema -Iextended -Ipatternmatcher -Idocumentator -Iutils -I../libraries -Igenerator -Igenerator/asmjs -Igenerator/c -Igenerator/cpp -Igenerator/java -Igenerator/js -Igenerator/llvm -Igenerator/fir -Igenerator/wasm -DINSTALL_PREFIX='"/nix/store/5rsqv2c2a3nsrff1c1lgw69bcd30v6d0-faust-2.0-a41"'  -I`'/nix/store/m5b0r6lznlqmv9dzbc2vhyw1v3n8vvk5-llvm-3.7.1/bin/llvm-config' --includedir` -I../architecture -D3.7.1 -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS    -c -o documentator/doc_sharing.o documentator/doc_sharing.cpp
<command-line>:0:1: error: macro names must be identifiers
<builtin>: recipe for target 'documentator/doc_sharing.o' failed
make[1]: *** [documentator/doc_sharing.o] Error 1
make[1]: Leaving directory '/tmp/nix-build-faust-2.0-a41.drv-0/faust-2.0.a41/compiler'
Makefile:44: recipe for target 'all' failed
make: *** [all] Error 2
builder for ‘/nix/store/fwy9lfqhfq6b7kcyp26pf93b4xi12552-faust-2.0-a41.drv’ failed with exit code 2
error: build of ‘/nix/store/fwy9lfqhfq6b7kcyp26pf93b4xi12552-faust-2.0-a41.drv’ failed
```

**Comment by henrytill** [comment]
cc @magnetophon

**Comment by magnetophon** [comment]
@bburdette Thanks for noticing. Good to know there are more faust users on NixOS.
I don't know what the problem is, and unfortunately atm I don't have time to debug either. 

Maybe @pmahoney can help.

**Comment by magnetophon** [comment]
@bburdette Thanks for noticing. Good to know there are more faust users on NixOS.
I don't know what the problem is, and unfortunately atm I don't have time to debug either. 

Maybe @pmahoney can help.

**Comment by magnetophon** [comment]
@bburdette Thanks for noticing. Good to know there are more faust users on NixOS.
I don't know what the problem is, and unfortunately atm I don't have time to debug either. 

Maybe @pmahoney can help.

**Comment by magnetophon** [comment]
@bburdette Thanks for noticing. Good to know there are more faust users on NixOS.
I don't know what the problem is, and unfortunately atm I don't have time to debug either. 

Maybe @pmahoney can help.

**Comment by bburdette** [comment]
I was pleasantly surprised to find faust2 already on nixpkgs!  If I get time I'll look at it too, but not sure where to start re debugging the package.

**Comment by bburdette** [comment]
FWIW, I was able to install the working version of the package from hydra!  Took me a while to think of doing that.  Package is here:  http://hydra.nixos.org/build/28945388

**Comment by vcunat** [comment]
Hehe, closure-size version of it, but the fact remains that some changes have broken the build later. The ability to easily use older builds in the meantime is a hallmark of nix...

**Comment by magnetophon** [comment]
@bburdette
FWIW: I just built faust 2 on 15.09

**Comment by joachifm** [comment]
I think the problem is that the makefile passes `-D$(llvm-config --version)` to gcc, which ends up being an invalid macro name (cannot start with a digit), resulting in the `macro names must be identifiers` error.Patching out `-D$(LLVM_VERSION)` from `Makefile.unix` makes the problem go away.

Beyond that hurdle is another issue with undefined references. There are some conditonals in a header file that depend on maro symbols that are never defined; I manually patched the makefile to pass these as appropriate for the detected llvm version. Feels like a terrible hack, but it fixes the build (on my system, anyway).

Does this sound crazy or should I create a PR for this?
