### ISSUE TITLE
vscode-extensions.matklad.rust-analyzer broken

### ISSUE THREAD

**Issue by tcmal** [NixOS/nixpkgs#127577]
**Describe the bug**

rust-analyzer extension will not load, due to folder(s) missing from recent builds

**To Reproduce**

1. Install VSCode with above extension
2. Start VSCode
3. Dev console shows:

```
Activating extension 'matklad.rust-analyzer' failed: Cannot find module '/nix/store/b005fza53z2qapyjdxgzbn5kgcivk6rd-vscode-extensions/share/vscode/extensions/matklad.rust-analyzer/out/src/main'
Require stack:
- /nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/vs/loader.js
- /nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/bootstrap-amd.js
- /nix/store/gdzyg1lc5rxvm3rghnc3anjip5h5bn2q-vscode-1.57.1/lib/vscode/resources/app/out/bootstrap-fork.js.
$onExtensionActivationError @ mainThreadExtensionService.ts:95
```

4. Commands, autocomplete, etc, not available

**Expected behavior**

Extension loads and functions normally

**Additional context**

The `out` folder & `src` folder are missing from the package:

```
$ ls /nix/store/jnd0px3hv51k07w5hr2jz35s1sf1fb0f-vscode-extension-rust-analyzer-2021-06-07/share/vscode/extensions/matklad.rust-analyzer
icon.png  language-configuration.json  package.json  package-lock.json  ra_syntax_tree.tmGrammar.json  README.md
```

[Relevant package build](https://hydra.nixos.org/build/145467738). It seems like this is a problem from 2021-06-07 onwards.

**Notify maintainers**

@oxalica

**Metadata**

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.11pre296557.33d42ad7cf2 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre296557.33d42ad7cf2, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: vscode-extensions.matklad.rust-analyzer
# a list of nixos modules affected by the problem
module:
```

**Comment by oxalica** [comment]
Bisected to 1dc8d8f0c443df7c477dd44c3c914085d8c40347, a node-package update, which updates vsce. Upstream also tried to upgrade vsce but [reverted due to "break things"](https://github.com/rust-analyzer/rust-analyzer/commit/16e142cd395f264ba5c6c3814ece92431415c089#diff-5327de443060217a48dced224bfca8b87dc60e5f9b3f8550c4782776295121f0L3257-R3270)
I assume the issue is from vsce and need to lock down its version.
I'll wait for the 2021-06-21 release and check it again.
