### ISSUE TITLE
Gnome mouse settings dont affect trackpad speed

### ISSUE THREAD

**Issue by jonocodes** [NixOS/nixpkgs#12758]
I'm using a thinkpad in gnome 3 and would like to see the Trackpad sensativity via's gnome's mouse settings. However the slider for mouse speed has no affect on my mouse.

I am able to adjust this in my config with something like:

```
services.xserver.synaptics.minSpeed = "2.5";
```

And a restart. Or I can set live in the terminal with 

```
synclient MinSpeed=2.5
```

So I clealy have the drivers working. Its just the gnome settings that are not adjusting it. No messages in dmesg or journalctl.

**Comment by jgillich** [comment]
The module writes a static configuration file that can not be changed by GNOME. Unfortunately, nothing can really be done about that.

**Comment by jonocodes** [comment]
I wonder how other distros handle this? And how synclient can modify this at run time.

**Comment by colemickens** [comment]
I have problems with GNOME and my touchpad. I've configured X correctly, and GNOME's settings look identical to what I've always seen in Arch, yet I absolutely can not get xf86-input-libinput to work right.

It works correctly under i3 under X of course, so I'm sure that there is something up with GNOME's handling of this config under NixOS.

**Comment by DamienCassou** [comment]
Gnome's settings goes against the NixOS philosophy stating that your system is fully described in one place (`configuration.nix`). Is it possible that Gnome's settings try to override a file that is generated by NixOS (which is normally impossible)?

**Comment by DamienCassou** [comment]
Related to https://github.com/NixOS/nixpkgs/issues/10025#issuecomment-142862144

**Comment by Profpatsch** [comment]
triage: what’s the status?

**Comment by jtojnar** [comment]
Seems to work now. Possibly thanks to libinput being used.
