### ISSUE TITLE
Cobalt

### ISSUE THREAD

**Issue by papojari** [NixOS/nixpkgs#127574]
**Project description**
Cobalt is a static site generator written in Rust. It is fast and command line centric.

**Metadata**

* homepage URL: https://cobalt-org.github.io/
* source URL: https://github.com/cobalt-org/cobalt.rs/
* license: mit
* platforms: linux, darwin, windows

**Comment by ethancedwards8** [comment]
Packaged!

**Comment by papojari** [comment]
Thanks you! That was very quick.

**Comment by ethancedwards8** [comment]
Yup, it happened to be an easy one :)
