### ISSUE TITLE
NVIDIA 465 beta driver breaks suspend, due to lacking `nvidia-sleep.sh` script

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#127693]
In

https://github.com/NixOS/nixpkgs/pull/73530/files#diff-98b29c6e49617265eccb2562afa3a70ba277e6af9508d908c001a4ed398b5e48R49

`nvidia-sleep.sh` is installed if it exists, and the install siliently continues if it doesn't exist.

```sh
    # Install systemd power management executables
    if [ -e nvidia-sleep.sh ]; then
        sed -E 's#(PATH=).*#\1"$PATH"#' nvidia-sleep.sh > nvidia-sleep.sh.fixed
        install -Dm755 nvidia-sleep.sh.fixed $out/bin/nvidia-sleep.sh
    fi
```

In the service

https://github.com/NixOS/nixpkgs/pull/73530/files#diff-28ea4da3a9a595f8bd1a37a555c229f998f3a11b0715ebc5842ba266384eba73R247

```
          ExecStart = "${nvidia_x11.out}/bin/nvidia-sleep.sh '${state}'";
```

the script is executed unconditionally, even if the script doesn't exist.

That breaks suspend with the 465 beta driver, because there the script does not exist.

I think we should

* [ ] fail loudly if it doesn't exist (so that if you close the laptop and put it in a bag, it doesn't catch fire)
* [ ] figure out where the script went / what the replacement is.

---

CC @lovesegfault @eadwu

**Comment by eadwu** [comment]
I will look into this in an hour or two, have a thing to do soon.
