### ISSUE TITLE
a typesetting program better than LaTeX

### ISSUE THREAD

**Issue by vigilancetech-com** [NixOS/nixpkgs#127671]
**Project description**
package Basser Lout for NixOS

**Metadata**

* homepage URL: http://savannah.nongnu.org/projects/lout/
* source URL: http://svn.savannah.nongnu.org/viewcvs/?root=lout
* license: Gnu General Public License V. 3+
* platforms: unix, linux, darwin

**Comment by AndersonTorres** [comment]
Is this OK?

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/lout/default.nix
