### ISSUE TITLE
bundler-head is older than bundler

### ISSUE THREAD

**Issue by phunehehe** [NixOS/nixpkgs#12785]
Digging into https://github.com/NixOS/nixpkgs/commit/10054a676a2e8cb21c1f5eee89a9d73166be8fb1 I was surprised to find that in both master and release-15.09, `bundler` is much newer than `bundler-head`. From https://github.com/bundler/bundler/commit/a2343c9eabf5403d8ffcbca4dea33d18a60fc157, you can see that the commit (which is used by `bundler-head` in both master and release-15.09) is included in releases since v1.8.0pre, where as `bundler` uses v1.10.6 and v1.10.5 in master and release-15.09, respectively.

In master, `bundler-head.nix` is not used at all. I'll follow with a PR that removes the file.

In release-15.09, `bundler-head.nix` is used by [`bundler-env`](https://github.com/NixOS/nixpkgs/blob/17b940568571ebc81344cf22740e8452157556eb/pkgs/development/interpreters/ruby/bundler-env/default.nix#L21), which I guess is for backward compatibility. To fight the non-deterministic fetchgit, I propose replacing https://github.com/bundler/bundler/commit/a2343c9eabf5403d8ffcbca4dea33d18a60fc157 with the latest minor release of the oldest major release containing the commit, which is v1.8.9. I'll also follow with a PR that does this.

**Comment by manveru** [comment]
Also see https://github.com/NixOS/nixpkgs/issues/9005 and https://github.com/NixOS/nixpkgs/issues/12370

We shouldn't depend on the git repository if at all possible and use the gem instead.

**Comment by jagajaga** [comment]
Was that fixed by https://github.com/NixOS/nixpkgs/pull/12786?

**Comment by phunehehe** [comment]
@jagajaga I'm still waiting for https://github.com/NixOS/nixpkgs/pull/12787 (release-15.09), not sure it makes sense to wait for that before closing this.

**Comment by fpletz** [comment]
Fixed by #12787.
