### ISSUE TITLE
We must renable nested configurations for grub

### ISSUE THREAD

**Issue by MarcWeber** [NixOS/nixpkgs#1278]
Blacklisting some modules as alternative boot option is one reason:
https://github.com/NixOS/nixpkgs/issues/1224

Unfortunately this feature was dropped when the grub builder scripts were updated from .sh to .pl. Its' on my TODO list for a while, but I haven't had time yet.

**Comment by domenkozar** [comment]
Is this still relevant?

**Comment by grahamc** [comment]
~2 years later, let's close this until there is renewed interest.
