### ISSUE TITLE
Packaging requests: retroshare

### ISSUE THREAD

**Issue by mnajib** [NixOS/nixpkgs#127815]
**Project description**
Retroshare is a free and open-source peer-to-peer communication and file sharing app based on a friend-to-friend network built on GNU Privacy Guard (GPG). Optionally, peers may communicate certificates and IP addresses to and from their friends.

![image](https://user-images.githubusercontent.com/2047490/122971310-7f21c300-d3c1-11eb-84b6-af4d409b0cc1.png)

Connect with Friends and Family

**Metadata**

* homepage URL: https://retroshare.cc/
* source URL: https://github.com/RetroShare/RetroShare
* license: agpl-3, apache, mit, gpl-3, lgpl-3 , ...
* platforms: linux, macOS, Windows, ...

**Comment by abathur** [comment]
Retroshare was briefly removed around the time you submitted this, but it was re-added in:
- https://github.com/NixOS/nixpkgs/pull/124177
