### ISSUE TITLE
Pop Shell (twm GNOME extension)

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#127952]
**Project description**
Pop Shell is a tiling window manager GNOME extension, that adds twm window layouts to GNOME and changes GNOME's default keybinds to ones similar to i3.  The rationale for Pop Shell is explained on their homepage, but the TLDR is they 1) want to gain the workflow efficiency of a twm while, 2) maintaining access to GNOME's many useful desktop integration features, like application overview, GNOME panel, GNOME extensions, etc., 3) all as a GNOME Shell extension and thus without requiring a custom GNOME fork.

I don't see this in [nixpkgs or options](https://search.nixos.org/packages?channel=21.05&from=0&size=50&sort=relevance&query=pop-shell), but if I missed it or used the wrong search terms, let me know.

**Metadata**

* homepage URL: https://github.com/pop-os/shell
* source URL: https://github.com/pop-os/shell
* license: gpl3
* platforms: linux

**Comment by Icy-Thought** [comment]
There are currently two attempts at packaging pop-shell for the Gnome desktop, #104160 and #102150, but both are having their own troubles. 

Hopefully that will be resolved in the near future!

**Comment by byrongibson** [comment]
Thx, just discovered those and came back to reference them.  Since they're still open I'll close this one.
