### ISSUE TITLE
in all packages llvm_latest is set to 11, when  12 is out and in nixpkgs

### ISSUE THREAD

**Issue by jascase901** [NixOS/nixpkgs#127957]
in all packages llvm_latest is set to 11, when  12 is out and in nixpkgs

@primeos 
I made a pull request myself, but it was closed, automatically. 

https://github.com/NixOS/nixpkgs/pull/127828#event-4931183640

cheers.

**Comment by TredwellGit** [comment]
I closed it because it is already merged on staging and staging-next. https://github.com/NixOS/nixpkgs/commit/3045b009def9f9eb7ebaa7620419df9420bf7736

**Comment by jascase901** [comment]
Thanks!
