### ISSUE TITLE
Calibre: Missing Qt plugin "headless"

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#12793]
When conversion of any format epub to mobi format in calibre fails with
```
This application failed to start because it could not find or load the Qt platform plugin "headless".
```
[Full log](https://gist.github.com/pstn/49b690d5e0a7afff6305)
I played around with the ```qtPlugins``` option in nixos but I couldn't get it to load this specific plugin since the option is pretty undocumented and I also don't believe that this would be a proper fix.

**Comment by cleverca22** [comment]
this is what i've seen used on another project to get the gui libs to load without X

https://github.com/taktoa/pianoman/blob/master/headless-teamspeak/qt5.nix#L52

that then allows loading the full teamspeak gui, without any X server
