### ISSUE TITLE
systemd: Move lib/udev/hwdb.d to a separate output

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#12799]
Now that the `hwdb.bin` file generated  from the source files in `hwdb.d` is part of the system closure (#12724), it would be nice to put `hwdb.d` in a separate systemd output to reduce closure size.

Probably we should drop `allowSubstitutes = false;` on the `hwdbBin` derivation to prevent the `hwdb.d` output from being downloaded in the common case.

**Comment by Profpatsch** [comment]
triage: status?

**Comment by Profpatsch** [comment]
Closing since systemd has progressed quite a bit, I assume this won’t be extremely relevant to the current setup anymore.
