### ISSUE TITLE
Get rid of chromium-source

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#12794]
Currently, we first build a `chromium-source` derivation containing the unpacked Chromium source code, which is then passed to the actual Chrome build. This is very inefficient: the unpacked source tree is 1.8 GB and ~85K files. Copying these between build machines can take a very long time: for instance, the `nixos:release-15.09:tested` is currently showing two `chromium-source` builds (in the copying state) which have already taken > 22 hours. So it would be better to do whatever `chromium-source` does in the `chromium` derivation.

**Comment by domenkozar** [comment]
@aszlig didn't we do this because IO was too slow for unpacking in NixOS tests?

**Comment by edolstra** [comment]
I don't think the tests need the source code.

**Comment by joelmo** [comment]
Is there another way to avoid copying source derivations between machines? I think the source derivation is good to keep, I want to have QtWebEngine which uses chromium, would be nice to use chromium source and all patches that is used. Would this still be possible (in a easy way) if chromium-source is removed?

**Comment by edolstra** [comment]
The `chromium-source` derivation could create a (compressed) tarball. That would help a lot since then Hydra won't have to do a huge amount of random access I/O reading/writing lots of small files.

**Comment by aszlig** [comment]
The reason I've done it that way was to separate bundled dependencies and the sandbox from the main source, so for example if we want to build just the sandbox, we don't need to extract the full Chromium source.

But I'll look into it so we can find a better solution, right now it's not working as I had in mind back then, because the source is copied into the temporary build directory, but a better solution would be to not copy anything at all.

**Comment by ttuegel** [comment]
> I want to have QtWebEngine which uses chromium

I don't think you can re-use `chromium-source` for this, as Qt uses a rather heavily modified version of the source.

**Comment by heydojo** [comment]
```
I don't think you can re-use chromium-source for this, as Qt uses a rather heavily modified version of the source.
```
Great point.
I will add too that even if it was vanilla, chrome source moves far too quickly to be a dependency of a qt component.
QtWebEngine is; I suspect using their own fork of the blink fork of webcore (webkit) https://en.wikipedia.org/wiki/Blink_(web_engine)
If we look at the chromium release schedule https://www.chromium.org/developers/calendar they are trying to hit a release almost every month.
If someone is _quick_ (Before 19th of this month) we could apply for a gsoc https://summerofcode.withgoogle.com/ to possibly get this chromium work done (worth a try?)

**Comment by domenkozar** [comment]
With S3 and decentralized hydra, we should really combine the source back. Currently this is blocking a channel update: http://hydra.nixos.org/build/33301631

**Comment by aszlig** [comment]
Working on this right now.

**Comment by aszlig** [comment]
I've also [cherry-picked and backported](https://github.com/NixOS/nixpkgs/compare/d10be236f191349773b199d30c4382e31715d60d...da4a26dbce2b3a256afb2939947a16d32d78ad31) the relevant changes to `release-15.09`.

**Comment by seanstrom** [comment]
@aszlig There's reference to the old path of the update.nix file on line 33 of this file:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/google-chrome/default.nix
