### ISSUE TITLE
A way to build updated VMs for other distros

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#12807]
If you look in https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/vm/default.nix, we have some lovely code to build deterministic VMs against the initial releases of a bunch of major distros.

Unfortunately, a lot of them go and update packages in e.g., http://vault.centos.org/6.5/updates/x86_64/repodata/ which changes in place. Short of mirroring their entire repositories, I don't know how best to address the question of getting a reasonably up-to-date version of a distro in a deterministic manner, but I'm hoping that someone else will have ideas.

The context for this is using Nix to build VM (and container) images for purposes other than testing the Nix installers.

**Comment by heydojo** [comment]
rpm supports chroot installs - I guess debian (dpkg?) does too. Mount the image rw, chroot into it, run a software update, unmount the image and rename it. Maybe...

**Comment by copumpkin** [comment]
But then it isn't deterministic, and won't work inside chroot builds

**Comment by heydojo** [comment]
Ah, I misunderstood what is going on here. filelists.xml.gz in http://vault.centos.org/6.5/updates/x86_64/repodata/ could be fetched, compared and merged into primary.xml.gz I think; before building, if it exists.
Fedora offer a cloud version now https://getfedora.org/en/cloud/download/ I guess cloud images should be used for vms. That is their purpose. Same goes for cent. No idea what debian offer if anything.

**Comment by domenkozar** [comment]
We should get Hydra to build the packages xml files, then mirroring scirpt will take care of it.

**Comment by Profpatsch** [comment]
triage: was there any progress?
