### ISSUE TITLE
Add `dnd-tools` package

### ISSUE THREAD

**Issue by TheBlackBeans** [NixOS/nixpkgs#128076]
**Project description**
DnD tools is a set of interactive CLI tools for DnD, a RPG.

**Metadata**
* source URL: [savagezen/dnd-tools](https://github.com/savagezen/dnd-tools)
* license: AGPL-3.0
* platforms: cross-platform
* dependencies: python (runtime)

**Comment by urlordjames** [comment]
I'll give it a shot.
