### ISSUE TITLE
Vlang package update

### ISSUE THREAD

**Issue by remimimimi** [NixOS/nixpkgs#128063]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vlang

current version: 0.1.21
desired version: 0.2.2

###### Notify maintainers

maintainers: @Chiiruno 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by remimimimi** [comment]
Also maintainer inactive since january, maybe something happened with him?

**Comment by nagy** [comment]
I think this can be closed
