### ISSUE TITLE
Curl sources cannot be downloaded

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#12816]
Downloading the curl sources currently fails on staging (maybe also elsewhere):
```
$ nix-build -A curl.src $hc -j1
these derivations will be built:
  /nix/store/cb4a7fcxh6jxrw40ibjw3i0x4hl3jf76-curl-7.47.0.tar.bz2.drv
building path(s) ‘/nix/store/myx56s2m67dnrb025kkj4r6yqkqhvz5p-curl-7.47.0.tar.bz2’

trying http://curl.haxx.se/download/curl-7.47.0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   319  100   319    0     0   3198      0 --:--:-- --:--:-- --:--:--  4984
curl: (1) Protocol "https" not supported or disabled in libcurl
error: cannot download curl-7.47.0.tar.bz2 from any mirror
```

This is because http://curl.haxx.se redirects to https://curl.haxx.se, and our bootstrap curl doesn't have https support.

Possible fixes:
* Use Nix's builtin fetchurl. Then we can even get rid of curl in the bootstrap tools. (The only downside is that it doesn't have mirror:// support.)
* Switch to a http mirror.
* Update the bootstrap tools to include a https-capable curl.

**Comment by vcunat** [comment]
It's probably everywhere, unfortunately. I noticed when trying a very old branch. Affected people can `nix-prefetch-url` as an immediate work-around.

**Comment by vcunat** [comment]
What about putting some versions into tarballs.nixos.org? I think that would work retrospectively, without anyone needing to change nix expressions.

**Comment by knedlsepp** [comment]
@vcunat: Thanks for the temporary workaround. Using `nix-prefetch-url http://SOME_MIRROR_I_FOUND_WITH_GOOGLE/curl-7.45.0.tar.bz2` did it for me.

**Comment by vcunat** [comment]
@knedlsepp: you can actually use the exact URL at which it's failing, as our `nix-prefetch-url` does support https.

**Comment by knedlsepp** [comment]
@vcunat: Oh. I was having problems trying that. I guess this was due to a simultaneous problem with ca-bundle.crt and I couldn't install neither ca-certs nor curl.

**Comment by heydojo** [comment]
```
  name = "curl-7.45.0";

  src = fetchurl {
    url = "http://ngcobalt13.uxnr.de/mirror/curl/${name}.tar.bz2";
    sha256 = "1slq5c0v9wa8hajgimhkxhvsrd07jmih8sa3gjsl597qp5k4w5b5";
  };
```
From : https://curl.haxx.se/latest.cgi?curl=tar.bz2
They have github too and they are tagging releases if that helps at all https://github.com/curl/curl/releases

**Comment by MindTooth** [comment]
I used Github for i3blocks releases:
```
src = fetchurl {
    url = "https://github.com/vivien/i3blocks/releases/download/${version}/${name}.tar.gz";
    sha256 = "c64720057e22cc7cac5e8fcd58fd37e75be3a7d5a3cb8995841a7f18d30c0536";
};
```
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/window-managers/i3/blocks.nix#L7-L10

**Comment by vcunat** [comment]
It downloads now on master and 15.09, but perhaps we can still find a better long-term solution.

**Comment by heydojo** [comment]
```
curl: (1) Protocol "https" not supported or disabled in libcurl
error: cannot download pkg-config-0.29.tar.gz from any mirror
```
This bug is affecting pkgconfig also as of today 17/02/2016.
Is there a fix for https curl bootstrap in staging yet? Because if not I will look into it. I would say this is high priority now with it happening twice in two weeks and it blocking building unstable.
Thanks.

**Comment by vcunat** [comment]
Hmm, strange. ATM it seems `pkgconfig` does not need to use `fetchurlBoot` and suffer from this problem. This was changed in d7490117, maybe in preparation for supporting https in `fetchurlBoot`, but ATM `curl` doesn't use `pkgconfig`.

BTW, I don't consider these issues any hard blockers, as they can be easily worked around. Still, we should solve them. Let me add a http-only mirror for now.

**Comment by dezgeg** [comment]
e6f61b4cf33887a9231a12e8c766404139a277d8 is in master now which sounds like solves the https bootstrap problem - anything else left here?

**Comment by vcunat** [comment]
I don't think so.
