### ISSUE TITLE
buttersink recently fails to build on nixos-21.05

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#128151]
**Describe the bug**
buttersink built on 21.05 at the time of release, but https://github.com/NixOS/nixpkgs/pull/127563 triggered the build to no longer succeed: https://hydra.nixos.org/eval/1681446#tabs-errors

```
in job ‘nixpkgs.buttersink.x86_64-linux’:
error: certifi-2021.05.30 not supported for interpreter python2.7
```

### Migrate buttersink to python3
https://github.com/NixOS/nixpkgs/issues/101964 tracks the migration of Python applications to Python 3 and notes buttersink doesn't build on Python 3.

### Build certifi for python2.7
https://github.com/NixOS/nixpkgs/pull/127453

### Find an alternative to buttersink that only depends on supported software
?

**Comment by FliegendeWurst** [comment]
PR #127453 fixed the issue, buttersink can now be built.
