### ISSUE TITLE
Cryptpad version 4.7.0 is out, but nixpkgs' is at 3.20.1

### ISSUE THREAD

**Issue by Pamplemousse** [NixOS/nixpkgs#128154]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

`nix search` name:

current version: 3.20.1
desired version: 4.7.0

###### Notify maintainers

maintainers: None :cry:

cc @xeji @zimbatm @blitz (from GH history)

###### Note for maintainers

Please tag this issue in your PR.

Also, I have tried to use `generate.sh`, then apply `bower2nix`.
Sadly, I encountered this bug https://github.com/rvl/bower2nix/issues/20 (but it seems that I wasn't using Node12)...
How does one need to proceed to update this package??

**Comment by zimbatm** [comment]
As long as they keep using bower, it will be difficult for us to keep that package up to date. The last time I touched this package I had to fight with it a lot.

I don't understand why they keep using that tool. If I remember correctly, it's EOL and has known vulnerabilities. This is kinda worrisome since Cryptpad is a security tool.

**Comment by blitz** [comment]
From conversations with the cryptpad developers I remember that's on their agenda to get rid of bower, but as long as it still works, the urgency to get it done is not high enough.

I suggest pinging them again and/or finding someone with JS experience to help them out.

**Comment by happysalada** [comment]
Just a quick update here with the fact that there is a draft PR about updating this.
#133202 
There are some minor changes still to be made, but it's almost ready for merge.
What was done with the bower thing is that in a nix-shell, you get nixpkgs 18.03 to get node_4 and then it seems to work.
If anybody has time to test this of course, it would be nice.
The fixes already mentioned in the PR should be done today. I'm thinking of merging it soon, unless somebody wants more time to test.

**Comment by happysalada** [comment]
The PR was just merged, when you have a moment to test, please open an issue if there is anything.

**Comment by Pamplemousse** [comment]
@happysalada The PR has broken my cryptpad install :confused: 

The landing page looks alright, but when I try to load any document, the page gets stuck, ang here is what I see in the console:
```
Require.js threw a Script Error. This probably means you're missing a dependency for CryptPad.
It is recommended that the admin of this server runs `bower install && bower update` to get the latest code, then modify their cache version.
Best of luck,
The CryptPad Developers
```

**Comment by DavHau** [comment]
Thanks. I just tested it again. With chromium it loads fine for me (creating a new sheet), but with firefox the page gets stuck while loading. Though I'm not sure if I'm experiencing the same error as you @Pamplemousse . I assume the message you posted is in the browser console? It doesn't show this message on my system. If you could give some more details about your configuration etc, that would be helpful. Thank you.

**Comment by DavHau** [comment]
I did not use nginx. I just tested cryptpad via simple `services.cryptpad.enable = true`.
Can you provide a config snipped that reproduces your issue?

**Comment by happysalada** [comment]
I only had a quick look, but would you mind testing with something else than nginx ? (just to see if the problem would come from there).

I use caddy a lot, could you test with a simple config ?
```
  services.caddy = {
    enable = true;
    email = "your_email@example.com";
    config = ''
      example.com www.example.com {
        reverse_proxy 127.0.0.1:REPLACE_WITH_CORRECT_PORT
      }
```
(you just need to replace the port, domain name and email address.)
Caddy should be a fairly transparent exposure of the local service.
I would completely understand if you don't want to try something different to what you already know.

**Comment by Pamplemousse** [comment]
@happysalada the webserver configuration for cryptpad is quite more involved than a single proxy forward: https://github.com/xwiki-labs/cryptpad/blob/cb0c4363e0d22265835684ab38ba66f61190be5e/docs/example.nginx.conf .

**Comment by happysalada** [comment]
I think you're right, I'm going to have a go at it on monday and try to update if I find anything else
Perhaps there is something in the changelog as well https://github.com/xwiki-labs/cryptpad/blob/main/CHANGELOG.md
I'll update if I find what could have changed in between.

**Comment by symphorien** [comment]
I reviewed release notes:

https://github.com/xwiki-labs/cryptpad/blob/main/CHANGELOG.md#update-notes-2 talks about missing trailing slashes:
> As this release includes a new app you'll want to compare your current NGINX config against our example (cryptpad/docs/example.nginx.conf) and update yours to match the updated sections which rewrites URLs to include trailing slashes. 

https://github.com/xwiki-labs/cryptpad/blob/main/CHANGELOG.md#nginx-configuration-update talks about some firefox specific configuration:
> After some testing on our part we've included an update to the example NGINX config file available in cryptpad/docs/example.nginx.conf which will enable a relatively new browser API which is required for XLSX export from our sheet editor. The relevant lines can be found beneath the comment # Enable SharedArrayBuffer in Firefox (for .xlsx export).

**Comment by Pamplemousse** [comment]
I updated my `nginx` configuration, and got cryptpad to work!
Thanks @DavHau @happysalada for the PR and the follow-up support.

On a side note, having to manually go through the changelog and edit the default configuration puts the burden on the users; Feels like this should be handled by the package maintainer...
Couldn't (shouldn't) we provide a toggle option `services.cryptpad.withNginxConfig` (or alike) that reflects the configuration (more or less, see note below) given upstream?

*Note*: the configuration they give cannot be used straightforwardly in `services.nginx.virtualhosts.<name>.extraConfig` because it fails `gixy` validation (see xwiki-labs/cryptpad#604 upstream); So one needs to duplicate several `add_header` under each location setting `add_header`.

**Comment by happysalada** [comment]
I was thinking about exactly the same thing.
I'm checking how easy it would be to merge those reverse-proxy configurations.
If you enable the flag then it just adds to your configuration instead of overwritting it.

**Comment by happysalada** [comment]
@Pamplemousse there is another package that enables nginx for you if you need it
https://github.com/NixOS/nixpkgs/blob/8284fc30c84ea47e63209d1a892aca1dfcd6bdf3/nixos/modules/services/web-apps/discourse.nix#L772

If you are interested in making a PR, I'm happy to review it and test it.
Otherwise, If you can share your nginx conf, I can make a PR and you can test it.
Whatever works best for you.

**Comment by Pamplemousse** [comment]
> I was thinking about exactly the same thing.
> I'm checking how easy it would be to merge those reverse-proxy configurations.
> If you enable the flag then it just adds to your configuration instead of overwritting it.
> 
> I've added a discussion about it. [ngi-nix/summer-of-nix/discussions/42](https://github.com/ngi-nix/summer-of-nix/discussions/42)
> I couldn't find it anywhere else in the nixpkgs repo, but there might be some prior art on this.

I can't access this discussion. And I guess it is the same for any non-"summer-of-nix participant"...
I remember reading a couple of comments about the necessity of having an nginx configuration, and the fact that it could be added to `nixpkgs` (see threads mentionned in https://github.com/NixOS/nixpkgs/issues/128154#issuecomment-897862585, and https://discourse.nixos.org/t/cryptpad-is-this-a-bug-or-must-i-configure-something/9100/4).

Eventually, I will have time to check and clean the configuration I have...
You might be able to find very similar configurations through one of the links I mentionned here; After all, this is where I copied the configuration I am currently using ^^

**Comment by symphorien** [comment]
@Pamplemousse So to be clear you solved the problem by apply the equivalent of `git diff 3.20.1..4.9.0 -- docs/example.nginx.conf` to your nginx config?

For reference, here is the diff:
```diff
diff --git a/docs/example.nginx.conf b/docs/example.nginx.conf
index 93be85083..8bc47d9f8 100644
--- a/docs/example.nginx.conf
+++ b/docs/example.nginx.conf
@@ -32,6 +32,9 @@ server {
     server_name your-main-domain.com your-sandbox-domain.com;
 
     # You'll need to Set the path to your certificates and keys here
+    # IMPORTANT: this config is intended to serve assets for at least two domains
+    # (your main domain and your sandbox domain). As such, you'll need to generate a single SSL certificate
+    # that includes both domains in order for things to work as expected.
     ssl_certificate         /home/cryptpad/.acme.sh/your-main-domain.com/fullchain.cer;
     ssl_certificate_key     /home/cryptpad/.acme.sh/your-main-domain.com/your-main-domain.com.key;
     ssl_trusted_certificate /home/cryptpad/.acme.sh/your-main-domain.com/ca.cer;
@@ -57,6 +60,17 @@ server {
     add_header Access-Control-Allow-Origin "*";
     # add_header X-Frame-Options "SAMEORIGIN";
 
+    # Opt out of Google's FLoC Network
+    add_header Permissions-Policy interest-cohort=();
+
+    set $coop '';
+    if ($uri ~ ^\/(sheet|presentation|doc|convert)\/.*$) { set $coop 'same-origin'; }
+
+    # Enable SharedArrayBuffer in Firefox (for .xlsx export)
+    add_header Cross-Origin-Resource-Policy cross-origin;
+    add_header Cross-Origin-Opener-Policy $coop;
+    add_header Cross-Origin-Embedder-Policy require-corp;
+
     # Insert the path to your CryptPad repository root here
     root /home/cryptpad/cryptpad;
     index index.html;
@@ -66,6 +80,9 @@ server {
     if ($args ~ ver=) {
         set $cacheControl max-age=31536000;
     }
+    if ($uri ~ ^/.*(\/|\.html)$) {
+        set $cacheControl no-cache;
+    }
     # Will not set any header if it is emptystring
     add_header Cache-Control $cacheControl;
 
@@ -102,7 +119,7 @@ server {
     set $unsafe 0;
     # the following assets are loaded via the sandbox domain
     # they unfortunately still require exceptions to the sandboxing to work correctly.
-    if ($uri = "/sheet/inner.html") { set $unsafe 1; }
+    if ($uri ~ ^\/(sheet|doc|presentation)\/inner.html.*$) { set $unsafe 1; }
     if ($uri ~ ^\/common\/onlyoffice\/.*\/index\.html.*$) { set $unsafe 1; }
 
     # everything except the sandbox domain is a privileged scope, as they might be used to handle keys
@@ -145,11 +162,18 @@ server {
     # /api/config is loaded once per page load and is used to retrieve
     # the caching variable which is applied to every other resource
     # which is loaded during that session.
-    location = /api/config {
+    location ~ ^/api/(config|broadcast).*$ {
         proxy_pass http://localhost:3000;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header Host $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+
+        # These settings prevent both NGINX and the API server
+        # from setting the same headers and creating duplicates
+        proxy_hide_header Cross-Origin-Resource-Policy;
+        add_header Cross-Origin-Resource-Policy cross-origin;
+        proxy_hide_header Cross-Origin-Embedder-Policy;
+        add_header Cross-Origin-Embedder-Policy require-corp;
     }
 
     # encrypted blobs are immutable and are thus cached for a year
@@ -166,8 +190,8 @@ server {
         add_header Cache-Control max-age=31536000;
         add_header 'Access-Control-Allow-Origin' '*';
         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
-        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
-        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
+        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Content-Length';
+        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Content-Length';
         try_files $uri =404;
     }
 
@@ -190,7 +214,7 @@ server {
     # The nodejs server has some built-in forwarding rules to prevent
     # URLs like /pad from resulting in a 404. This simply adds a trailing slash
     # to a variety of applications.
-    location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban|sheet|support|admin|notifications|teams)$ {
+    location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban|sheet|support|admin|notifications|teams|calendar|presentation|doc|form|report|convert)$ {
         rewrite ^(.*)$ $1/ redirect;
     }
 
```

**Comment by Pamplemousse** [comment]
@symphorien Almost!

There is a missing step to pass `gixy` validation (and accessorily to make the `nginx` configuration do what it say it does):

Take `location ~ ^/api/(config|broadcast).*$` for example: `add_header` rules have been added under it.
[**This voids headers that were defined in the outer scope!**](https://github.com/yandex/gixy/blob/master/docs/en/plugins/addheaderredefinition.md)
Thus, you need to also `add_header` for the ones you want to see for this location.
i.e.
  * Outermost `add_header` rules will only apply to locations that do not have a `add_header`;
  * Every location that has a `add_header` need to also duplicate the parent scope `add_header` rules.

**Comment by Pamplemousse** [comment]
Note that the configuration that they provide is actually broken (will drop headers for certain locations) because of this `nginx` behavior; See https://github.com/xwiki-labs/cryptpad/issues/604 .
