### ISSUE TITLE
Freezer, music player, package

### ISSUE THREAD

**Issue by alanxyz** [NixOS/nixpkgs#128258]
> Free music streaming client for Deezer based on the Deezloader/Deemix "bug".

* homepage URL: https://freezer.life
* source URL: https://git.freezer.life/exttex/freezerpc
* license: gpl3
* platforms: android, linux, windows (as far as i know)

**Comment by Kranzes** [comment]
Already have a default.nix for it, for the appimage and the .deb. I am willing to make a PR for it tomorrow.

**Comment by Kranzes** [comment]
i was sadly unabunable to build it from source.

**Comment by WolfangAukang** [comment]
Package is not maintained anymore as Deezer has patched up. Closing.
