### ISSUE TITLE
nixos/doc/configuration/profiles/all-hardware.xml to CommonMark

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#128226]
This tracks the conversion of `nixos/doc/manual/configuration/profiles/all-hardware.xml` from DocBook to CommonMark per [RFC 72](https://github.com/NixOS/rfcs/blob/master/rfcs/0072-commonmark-docs.md).

## Conversion instructions

1. Comment here that you intend to work on this. (Please also post if you stop working on this.)
2. Checkout a new branch of nixpkgs master.
3. Edit `nixos/doc/manual/configuration/profiles.xml`: change `profiles/all-hardware.xml` to `../from_md/configuration/profiles/all-hardware.section.xml`.
4. Rename `nixos/doc/manual/configuration/profiles/all-hardware.xml` to `configuration/profiles/all-hardware.section.md`.
5. Convert the contents from Docbook to [CommonMark](https://commonmark.org/). Follow [conversion best practices](https://github.com/NixOS/nixpkgs/issues/105243). Use existing `.md` sections in the NixOS and Nixpkgs manual for inspiration.
6. Convert the CommonMark back to DocBook xml with:
    ```
    nixos/doc/manual/md-to-db.sh
    ```
7. Build from nixpkgs root dir with:
    ```
    nix-build nixos/release.nix -A manual.x86_64-linux
    ```
8. Start a preview server with:
    ```
    nix-shell -p python3 --run 'python3 -m http.server --directory ./result/share/doc/nixos'
    ```
9. Preview your work at `http://0.0.0.0:8000/`
10. Iterate on steps 5-9.
11. When it looks good, commit both the new `.md` file and the generated `from_md` `.xml` file, submit a PR and reference this issue.

**Comment by bobby285271** [comment]
I opened a PR for all `nixos/doc/configuration/profiles/*.xml` pages:

#128760

PTAL, thanks in advance for reviewing :-)
