### ISSUE TITLE
Invidious

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#128274]
### Project description
Alternative frontend for YouTube.

### Metadata

* homepage URL: *decentralized*
* source URL: https://github.com/iv-org/invidious
* license: agpl3
* platforms: unix

**Comment by rnhmjoj** [comment]
There is a PR already (https://github.com/NixOS/nixpkgs/pull/67664), but it's stuck due to an unresolved issue upstream (https://github.com/iv-org/invidious/issues/923).

**Comment by Kreyren** [comment]
@rnhmjoj That claims that nix's crystal builder has to be adjusted?

**Comment by rnhmjoj** [comment]
Apparently, but I know as much as you do. The original reporter is probably not using Nix, though, so it may not be limited to Nixpkgs.

**Comment by FliegendeWurst** [comment]
This was done in #136993.
