### ISSUE TITLE
smbprotocol tests fail on macOS

### ISSUE THREAD

**Issue by tscholak** [NixOS/nixpkgs#128312]
**Describe the bug**
smbprotocol doesn't build on macOS due to numerous test failures:
```
=========================== short test summary info ============================
FAILED tests/test_smbclient_shutil.py::test_copymode_local_to_local_symlink_dont_follow
FAILED tests/test_smbclient_shutil.py::test_copystat_local_to_local_symlink_dont_follow_fail
FAILED tests/test_transport.py::test_recv_closed - OSError: [Errno 57] Socket...
============ 3 failed, 505 passed, 495 skipped, 1 warning in 6.48s =============
builder for '/nix/store/1bspkg9j4a4v8sq0ii7zcd1j0q0ki2b8-python3.8-smbprotocol-1.5.1.drv' failed with exit code 1
cannot build derivation '/nix/store/lqn592bga41j80pjinsz57mv77bnx12s-python3-3.8.9-env.drv': 1 dependencies couldn't be built
```

**To Reproduce**
1. By on macOS.
2. Get a nixpkgs rev that includes https://github.com/NixOS/nixpkgs/commit/52b3e47413be15d9798e78ef44d71e126f85c209
3. Run `nix-shell -p 'python3.withPackages (ps: with ps; [ smbprotocol ])' -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e85975942742a3728226ac22a3415f2355bfc897.tar.gz`

**Expected behavior**
shell should build.

**Notify maintainers**
@fabaff

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(torsten.scholak): `"darwin, home-manager, nixpkgs-21.05pre291295.efee454783c"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/torsten.scholak/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by smancill** [comment]
This was fixed by 861f36d871ce0354b0e26ee02d2fbda54a787062.

smbprotocol 1.6.1 builds fine on Darwin.
