### ISSUE TITLE
aseprite-unfree: package outdated

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#128308]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: aseprite-unfree

current version: 1.2.16.3 (3 Dec 2019)
~desired version: 1.2.27 (19 Apr 2021)~
desired version: 1.2.30 (26 Oct 2021)

###### Notify maintainers

maintainers: @orivej 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by OPNA2608** [comment]
Still outdated. Latest version: 1.2.30

**Comment by OPNA2608** [comment]
Still outdated. Latest version is now [1.2.40](https://github.com/aseprite/aseprite/releases/tag/v1.2.40)

**Comment by kyren** [comment]
I opened PR #200202 that will fix this
