### ISSUE TITLE
services.gitlab.enable causes `PostgreSQL >=12 is required to run GitLab 14.`

### ISSUE THREAD

**Issue by nielsegberts** [NixOS/nixpkgs#128304]
**Bug description**
Using the configuration provided by the manual (https://nixos.org/manual/nixos/stable/index.html#module-services-gitlab), `nixos-rebuild switch --upgrade` fails an assertion:

```
error: 
Failed assertions:
- PostgreSQL >=12 is required to run GitLab 14.
(use '--show-trace' to show detailed location information)
```

I believe this is the case since this commit:
https://github.com/NixOS/nixpkgs/commit/2297eb35e5b92f657b85dfe4ee535e2323e360c1#diff-1bad593adeddc511525070bb59181faed3399d0b8196ceef26a179f8205814b2

Is it because the branch on line 13 is never taken so `config.services.postgresql.package` is used instead of `pkgs.postgresql_12` because `config.services.prostgresql.enable` is set to true on line 862?. I don't have other services enabled that rely on postgresql.

I'm new to Nix so this hypothesis may be incorrect.

**Expected behavior**
Setting `gitlab.enable` to true should pull in `pkgs.postgresql_12` instead of using the default 11.

**Notify maintainers**
@yu-re-ka 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: nixpkgs.gitlab
```

**Comment by yu-re-ka** [comment]
Nope, this is on purpose. The default postgres version depends on your `system.stateVersion`. If your postgres version is too old, you need to update it manually by migrating state to the new version (see [here](https://nixos.org/manual/nixos/stable/index.html#module-services-postgres-upgrading)).
Changing the postgres version automatically would break other applications that had their state saved in postgres prior to enabling GitLab.

**Comment by nielsegberts** [comment]
Thanks for your response. I was not aware of system.stateVersion. I'll close this issue.

After the commit hit unstable, `nixos-rebuild switch --upgrade` now fails with an assertion failure, and I no longer get (security) updates for my other packages until I migrate postgresql, is that just the risk of using unstable, or should it not hit a failed assertion when the config used to build fine?

I see that postgres uses different packages for different versions so new versions of postgres don't break updates, I'm not saying it's worth the effort, but in an ideal world should the same hold for gitlab?

**Comment by yu-re-ka** [comment]
Of course we would like to prevent things like this being necessary, but an upstream project changed its requirements and we needed you to do the migration, since state management can only be automated to some degree.
Maintaining different versions of GitLab would be possible if GitLab delivered security updates for old major versions, but as far as I'm aware they don't deliver any security updates 2-3 months after the new version was released.
This means there is no way around this manual migration in order to keep you supplied with security upgrades for all your services.

**Comment by nielsegberts** [comment]
Thanks for that explanation! That makes a lot of sense.
