### ISSUE TITLE
udev path rules not working?

### ISSUE THREAD

**Issue by ctheune** [NixOS/nixpkgs#12833]
When adding a package to services.udev.packages (to enable its rules) and services.udev.path (to get is binaries into the search path) I found that the path in 00-path.rules is properly constructed (I find the binaries from my package added to bin/) but when referencing the binary it's not found. (at least that's what I guess - I'm not getting any useful debugging output)

Instead of referring to my binary this way:

```
SUBSYSTEM=="block", PROGRAM="fc-get-disk-alias %k", SYMLINK+="%c"
```

(fc-get-disk-alias is in the path from 00-path.rules)

I have to explicitly construct a path when building the rule:

```
SUBSYSTEM=="block", PROGRAM="/nix/store/5dr5hyb5mimninry2wy413srb5q9pl2i-fc-manage-0.1/bin/fc-get-disk-alias %k", SYMLINK+="%c"
```

**Comment by Profpatsch** [comment]
triage: Sorry that there was no reply, does this still happen after #13059?

**Comment by ctheune** [comment]
I think the issue about absolute/relative paths in #13059 also explains the behaviour I'm seeing. Let's put this away.
