### ISSUE TITLE
onlyoffice-bin: Fail to start on Wayland, could not load plugin "wayland-egl"

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#128485]
**Describe the bug**
Trying to launch ``onlyoffice-bin`` on ``sway`` fails with the message:
```
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
fish: Job 1, 'onlyoffice-desktopeditors' terminated by signal SIGABRT (Abort)
```

**To Reproduce**
1. Install: ``nix-env -iA nixos.onlyoffice-bin``
2. Run: ``onlyoffice-desktopeditors``

**Expected behavior**
Onlyoffice should be able to run on Wayland

**Notify maintainers**
@nh2 @GTrunSec 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1205.b72bde7c4a1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1205.b72bde7c4a1, nixos-unstable-21.11pre297796.e1f8852faac"`
 - channels(onny): `"nixos-20.09.4159.a7064e23973, nixos-unstable-21.05pre290427.673aea9f84c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by hmenke** [comment]
Could you try with
```bash
QT_QPA_PLATFORM=wayland onlyoffice-desktopeditors
```
and
```bash
QT_QPA_PLATFORM=xcb onlyoffice-desktopeditors
```

**Comment by onny** [comment]
``QT_QPA_PLATFORM=wayland onlyoffice-desktopeditors``:
```
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
fish: Job 1, 'QT_QPA_PLATFORM=wayland onlyoff…' terminated by signal SIGABRT (Abort)
```
Onlyoffice does not start.

 ``QT_QPA_PLATFORM=xcb onlyoffice-desktopeditors``
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Qt: Failed to create XKB context!
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```
Onlyoffice starts and is working fine but ``xprop`` tells me that it is running through ``xwayland`` :(

**Comment by onny** [comment]
Found the upstream issue https://github.com/ONLYOFFICE/DesktopEditors/issues/382
Maybe we'll leave this issue open until it's fixed upstream?

**Comment by hmenke** [comment]
As already suspected, OnlyOffice does not support Wayland at this point. Here is the upstream bug: https://github.com/ONLYOFFICE/DesktopEditors/issues/382

**Comment by frigaut** [comment]
it works with 
`QT_QPA_PLATFORM=xcb onlyoffice-desktopeditors`
