### ISSUE TITLE
WideVine is missing even though it's enabled 

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#12840]
Possibly related to the fix for https://github.com/NixOS/nixpkgs/issues/12710

**Comment by colemickens** [comment]
```
$ pwd
/n/s/5fq7lp2jvqpmjfnk151ldx0k7vh03mgb-chromium-binary-plugins-widevine
$ cat nix-support/wrapper-flags
'--add-flags' ''\''--register-pepper-plugins=$widevine/lib/libwidevinecdmadapter.so#Widevine Content Decryption Module#Playback of encrypted HTML audio/video content;application/x-ppapi-widevine-cdm'\''' '--set' ''\''NIX_CHROMIUM_PLUGIN_PATH_WIDEVINE'\''' ''\''/nix/store/5fq7lp2jvqpmjfnk151ldx0k7vh03mgb-chromium-binary-plugins-widevine/lib'\'''
```

Particularly:

''\''--register-pepper-plugins=$widevine/lib/libwidevinecdmadapter.so#Widevine Content Decryption Module#Playback of encrypted HTML audio/video content;application/x-ppapi-widevine-cdm'\'''

**Comment by colemickens** [comment]
I've looked at this a couple times for an hour and am not really sure how to go about resolving it.

Any suggestions, @aszlig ?

**Comment by aszlig** [comment]
Even though the shell quotes are looking weird, what do you get in the actual wrapper? (`cat "$(command -v chromium)"`)

Also, which version of `<nixpkgs>` are you running?

**Comment by colemickens** [comment]
```
$ cat "$(command -v chromium)"
#! /nix/store/pnc8xc1dh3cy4migfipfmzy3ad7snz99-bash-4.3-p42/bin/bash -e
export 'NIX_CHROMIUM_PLUGIN_PATH_WIDEVINE'='/nix/store/ylhal8gkzq8lfr9p2z3m5xw50wpbbjm7-chromium-binary-plugins-widevine/lib'
exec /nix/store/vylz20c7ifg27pvkdrcprv8yrn6dgsm9-chromium-49.0.2593.0/libexec/chromium/chromium '--ppapi-flash-path=/nix/store/5bz75h4hk1nxbzak1rf7s207gipd6cgq-chromium-binary-plugins-flash/lib/libpepflashplayer.so' '--ppapi-flash-version=/nix/store/5bz75h4hk1nxbzak1rf7s207gipd6cgq-chromium-binary-plugins-flashVersion' '--register-pepper-plugins=/nix/store/ylhal8gkzq8lfr9p2z3m5xw50wpbbjm7-chromium-binary-plugins-widevine/lib/libwidevinecdmadapter.so#Widevine Content Decryption Module#Playback of encrypted HTML audio/video content;application/x-ppapi-widevine-cdm' "${extraFlagsArray[@]}" "$@"
```

Relevant line, I believe:

--register-pepper-plugins=/nix/store/ylhal8gkzq8lfr9p2z3m5xw50wpbbjm7-chromium-binary-plugins-widevine/lib/libwidevinecdmadapter.so#Widevine Content Decryption Module#Playback of encrypted HTML audio/video content;application/x-ppapi-widevine-cdm'

**Comment by colemickens** [comment]
I'm on 77f8f35 (current nixos-unstable) with some personal additions that shouldn't impact chromium.

**Comment by colemickens** [comment]
Actually, no, I'm not. I'm on `77f8f35` with a cherry-pick for your fix for the Flash plugin.

**Comment by colemickens** [comment]
Sorry for the spam. I'm on 77f8f35 with your cherry-pick when I reported this initially. The line I just copied above is actually from a different branch that has my fix applied instead of yours.

I'll revert back to your fix and paste the relevant line here so that we can compare. Obviously the one 3 posts up looks correct and is working, but again, that's without your fix.

Apologies for the confusion. I'll gather more data and be more thorough about it so that I give you better information.

**Comment by colemickens** [comment]
I believe it is related to the lack of expansion of `$widevine`.

Here are the flags under three conditions:

1. `nixos-unstable` + your fixes: https://gist.githubusercontent.com/anonymous/b2d726fd9450cc943d50/raw/a376614af92ee87308438672ed81c623894bc93c/master-flash-nowidevine.flags (note that `$widevine` isn't expanded)

2. `nixos-unstable` + my hacked fix (with your original change but w/o your fix): https://gist.githubusercontent.com/anonymous/b2d726fd9450cc943d50/raw/a376614af92ee87308438672ed81c623894bc93c/nixos-unstable-myfix-flash-widevine.flags (note that `$widevine` IS expanded)

3. `nixos-unstable` (same as the original #12710): https://gist.githubusercontent.com/anonymous/b2d726fd9450cc943d50/raw/a376614af92ee87308438672ed81c623894bc93c/nixos-unstable-noflash-netflix.flags (`$widevine` is expanded, but flashVersion is wrong)

This leads me to think that something about the expansion of `$widevine` broke when you fixed it, since my hacked version on top of your initial implementation works for WideVine...
