### ISSUE TITLE
sway does not start with EGL_NOT_INITIALIZED error

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#128469]
**Describe the bug**

When trying to launch sway (from tty) I get the error

```
libEGL warning: MESA-LOADER: failed to open : /run/opengl-driver/lib/dri/_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri)

00:00:00.276 [ERROR] [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
libEGL warning: MESA-LOADER: failed to open : /run/opengl-driver/lib/dri/_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri)

00:00:00.276 [ERROR] [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed to load driver"
00:00:00.276 [ERROR] [wlr] [EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize"
00:00:00.276 [ERROR] [wlr] [render/egl.c:217] Failed to initialize EGL
00:00:00.276 [ERROR] [wlr] [EGL] command: eglMakeCurrent, error: EGL_BAD_DISPLAY (0x3008), message: "Invalid display (nil)"
00:00:00.276 [ERROR] [wlr] [render/wlr_renderer.c:263] Could not initialize EGL
00:00:00.283 [ERROR] [wlr] [backend/drm/renderer.c:34] Failed to create EGL/WLR renderer
00:00:00.291 [ERROR] [wlr] [backend/drm/backend.c:201] Failed to initialize renderer
00:00:00.293 [ERROR] [wlr] [backend/backend.c:174] Failed to create DRM backend
00:00:00.293 [ERROR] [wlr] [backend/backend.c:312] Failed to open any DRM device
00:00:00.371 [ERROR] [sway/server.c:55] Unable to create backend
```

(It seems strange that sway is trying to use `_dri.so`)

I'm not completely sure whether this is nixpkgs or home-manager's issue, but it seems to have occurred when bumping nixpkgs from 51bb9f3e9ab6161a3bf7746e20b955712cef618b to b27eaa18b47b77fbbf9f3bd7a17046b2d64b637b. If I pin nixpkgs at b27eaa18b47b77fbbf9f3bd7a17046b2d64b637b and just update home-manager sway still runs. I am working on finding the specific commit with the breakage.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to launch sway from tty

**Expected behavior**
Sway should launch

**Additional context**
I am using `home-manager` to manage sway, tracking nixpkgs-unstable but my system configuration tracks 21.05. My flake-based config can be found [here](https://gitlab.com/lunik1/nix-config).

**Notify maintainers**

@primeos @synthetica @ma27

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.9-zen1, NixOS, 21.05.20210623.0ccd0d9 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-20.09.3332.d303eee16ce, nixos-unstable-21.05pre272380.f6b5bfdb470"`
 - channels(corin): `"nixpkgs-21.05pre286925.3e62e383f4b"`
 - nixpkgs: `/home/corin/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: sway
# a list of nixos modules affected by the problem
module:
```

**Comment by primeos** [comment]
Seems like you're hitting the issues described in https://github.com/NixOS/nixpkgs/pull/119558 and https://github.com/NixOS/nixpkgs/pull/120325. Try to make sure to use the same Nixpkgs revisions for NixOS and home-manager, that should fix it. This new limitation should likely also be mentioned in the home-manager documentation for Sway.

**Comment by lunik1** [comment]
Another fix (for sway at least) is to set `wayland.windowManager.sway.package` to null and then enable the sway module in NixOS. Although form what I understand while this allows sway to work other programs depending on mesa can also break?

**Comment by primeos** [comment]
> Another fix (for sway at least) is to set wayland.windowManager.sway.package to null and then enable the sway module in NixOS.

Good idea. IMO that's preferable anyway. I once suggested that in https://github.com/nix-community/home-manager/issues/1288#issuecomment-636352427 but I'm not sure if it was ever documented.

> Although form what I understand while this allows sway to work other programs depending on mesa can also break?

Yes, unfortunately (IIRC I also observed this issue with XWayland).

**Comment by tuxinaut** [comment]
> Seems like you're hitting the issues described in #119558 and #120325. Try to make sure to use the same Nixpkgs revisions for NixOS and home-manager, that should fix it. This new limitation should likely also be mentioned in the home-manager documentation for Sway.

First, thank you very much for spending time on this issue. Second I don't get what you exactly mean :cry: 

To use e.g 21.05 version for both nixos and home-manage :thinking: ?

**Comment by primeos** [comment]
Seems like this issue can be closed.
