### ISSUE TITLE
ROOT doesn't compile on Big Sur but the binary cache works

### ISSUE THREAD

**Issue by yipengsun** [NixOS/nixpkgs#128576]
**Describe the bug**
I'm trying to get my colleagues (bosses, really) to start using `nix`. Both are on macOS; one on Big Sur, the other Catalina.

Because we need to apply patches to `root`, we need to compile it on both platforms. On Big Sur, I got the following error message when trying to compile `root` that comes straight from `nixpkgs`:

```
Scanning dependencies of target Cling
[ 79%] Linking CXX shared library ../../../lib/libCling.so
[ 79%] Built target Cling
[ 79%] Built target G__Core
Scanning dependencies of target Core
[ 79%] Linking CXX shared library ../lib/libCore.so
ld: framework not found CoreSymbolication
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [core/CMakeFiles/Core.dir/build.make:502: lib/libCore.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:24441: core/CMakeFiles/Core.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
error: builder for '/nix/store/qvh9x3wys8lvw6lp02agr8qbcppd3bgw-root-6.24.00.drv' failed with exit code 2;
       last 10 log lines:
       > [ 79%] Linking CXX shared library ../../../lib/libCling.so
       > [ 79%] Built target Cling
       > [ 79%] Built target G__Core
       > Scanning dependencies of target Core
       > [ 79%] Linking CXX shared library ../lib/libCore.so
       > ld: framework not found CoreSymbolication
       > clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
       > make[2]: *** [core/CMakeFiles/Core.dir/build.make:502: lib/libCore.so] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:24441: core/CMakeFiles/Core.dir/all] Error 2
       > make: *** [Makefile:171: all] Error 2
       For full logs, run 'nix log /nix/store/qvh9x3wys8lvw6lp02agr8qbcppd3bgw-root-6.24.00.drv'.
```

But the binary cache works on Big Sur. On Catalina, both compilation and binary cache work fine.

**To Reproduce**
1. `nix-build --check -A root '<nixpkgs>'`

**Expected behavior**
`root` should build and link w/o problem.

**Notify maintainers**

@veprbl 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

This is on macOS Big Sur.
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210604_8e6ee1b`
 - channels(root): `"nixpkgs-21.11pre295670.189a1368878"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
Seems like it is coming from
https://github.com/root-project/root/blob/a89eb12f83228833842813c4b690a2033778316b/core/CMakeLists.txt#L150
I suppose you should also have /System/Library/PrivateFrameworks/CoreSymbolication.framework
Would be nice to see compilation logs of `root.overrideAttrs (_: { NIX_DEBUG=1; })`

**Comment by veprbl** [comment]
cc @NixOS/darwin-maintainers for suggestions

**Comment by thefloweringash** [comment]
It looks like it should be an easy fix: use the framework stub for CoreSymbolication. I've opened a PR (https://github.com/NixOS/nixpkgs/pull/128581) but have run out of time to test it right now.

**Comment by yipengsun** [comment]
I put some of your changes to [an overlay](https://github.com/umd-lhcb/root-curated/blob/master/nix/overlay.nix) and it now is compiling fine on Big Sur. Many Thanks!

BTW, how'd I override the `apple_sdk` attribute for the `darwin` package? I tried the following:
```nix
final: prev:

{
  darwin = prev.darwin // { 
    apple_sdk_10_12 = prev.callPackage ./apple-sdk {
      inherit (prev.buildPackages.darwin) print-reexports;
      inherit (prev.darwin) darwin-stubs;
    };
  };
  root = prev.callPackage ./root {
    python = final.python3;
    inherit (final.darwin.apple_sdk.frameworks) Cocoa CoreSymbolication OpenGL;
    noSplash = true;
  };
}

```

But `nix` still complains about `CoreSymbolication` not found.

**Comment by yipengsun** [comment]
Just want to report back that with latest unstable branch, ROOT compiles fine on Big Sur.
