### ISSUE TITLE
ekiga doesn't work

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#12854]
it's missing icons in the toolbar, also it needs that dconf thing to wire it up to gsettings i guess

```
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

Biggest problem is probably that it doesn't emit sound, though. Update: It emits sound when using pulseaudio, but not with alsa.

**Comment by ibrahimsag** [comment]
@ben0x539 any updates?

**Comment by ben0x539** [comment]
Ah, I don't have the opportunity to use ekiga anymore unfortunately. Toolbar still looks broken though.

**Comment by tomberek** [comment]
close as old?
