### ISSUE TITLE
acme-fixperms fails if `/var/lib/acme` is a symlink

### ISSUE THREAD

**Issue by chvp** [NixOS/nixpkgs#128510]
**Describe the bug**
Like some other NixOS users, I clear my root filesystem on boot. To prevent my certificates being removed, I symlink `/var/lib/acme` to a safe location. This makes `acme-fixperms.service` fail (and I'm not sure how to fix this).

```
systemd[1]: Starting Fix owner and group of all ACME certificates...
systemd[4786]: acme-fixperms.service: Failed to set up special execution directory in /var/lib: Not a directory
systemd[4786]: acme-fixperms.service: Failed at step STATE_DIRECTORY spawning /nix/store/rq5rsxw7zkhhdylvxc8g8j4d8zmm14vz-acme-fixperms: Not a directory
systemd[1]: acme-fixperms.service: Main process exited, code=exited, status=238/STATE_DIRECTORY
systemd[1]: acme-fixperms.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Fix owner and group of all ACME certificates.
```

**To Reproduce**
1. Make `/var/lib/acme` a symlink.
2. Start acme-fixperms
3. Watch it fail

**Expected behavior**
It should not fail.

**Notify maintainers**

@NixOS/acme 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.11.20210628.4f3bc6a (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/etc/channels/nixpkgs`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: 
 - acme
```

**Comment by hmenke** [comment]
That holds for any systemd service. `StateDirectory` must not be a symlink. Can you use a bind mount instead?

**Comment by chvp** [comment]
I'll give that a try, thanks. I guess it is true that this would be a problem for any systemd service, but acme-fixperms is the only one actually having problems on any of my systems.

**Comment by hmenke** [comment]
Sounds like you followed https://grahamc.com/blog/erase-your-darlings. I was using the symlink approach as well, but it stopped working in NixOS 20.09 already, so now I just have `/var/lib/acme` on an extra ZFS dataset.

**Comment by chvp** [comment]
I switch my setup to use bindmounts instead of symlinks and everything seems to work well. Thanks!
