### ISSUE TITLE
duplicity needs to be updated to >= 0.8.19

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#128650]
In https://github.com/NixOS/nixpkgs/pull/128634, `python3` is updated to version 3.9 which is not supported by `pythonPackages.boto`. According to http://duplicity.nongnu.org/vers8/CHANGELOG.md, duplicity version 0.8.19 moved from boto to boto3.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: duplicity

current version: 0.8.17
desired version: 0.8.20

###### Notify maintainers

maintainers: @peti @gebner @StephenWithPH @enolan 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by gebner** [comment]
duplicity is now at 0.8.20 in master.
