### ISSUE TITLE
fntsample/pdfoutline

### ISSUE THREAD

**Issue by wildthyme** [NixOS/nixpkgs#128644]
**Project description**
tool for making font sample charts which also includes another tool, `pdfoutline`, for adding a table of contents to a pdf. (the latter is a dependency of the emacs toc-mode package)

**Metadata**

* homepage/source URL: https://github.com/eugmes/fntsample
* license: GPL v3
* platforms: unix

**Comment by tomodachi94** [comment]
Added in https://github.com/NixOS/nixpkgs/pull/142683.
