### ISSUE TITLE
fetchdarcs: Host resolving seems to fail in some cases

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#12868]
e.g. for screen-message (https://github.com/NixOS/nixpkgs/commit/6265123f7a687143a9ee20888cae5e07fb08c087) the following error occurs on hydra:

```
building path(s) ‘/nix/store/d2rwy7n9zjhhd3195qwx95ymxdci4dyr-fetchdarcs’
getting http://darcs.nomeata.de/screen-message.debian  (tag 0.23-1)  into /nix/store/d2rwy7n9zjhhd3195qwx95ymxdci4dyr-fetchdarcs

darcs failed:  Not a repository: http://darcs.nomeata.de/screen-message.debian (CouldNotResolveHost)

HINT: Do you have the right URI for the repository?

builder for ‘/nix/store/06ls4az5kyhrh2g95gs2rbbimfg40c9g-fetchdarcs.drv’ failed with exit code 2
```

A local build fetches the source just fine.

cc @aszlig

**Comment by womfoo** [comment]
This seems to have fixed itself if it was down. The darcs repo no longer fails atleast on my side.

**Comment by Profpatsch** [comment]
@womfoo As I said, locally it’s perfectly fine, but from the hydra it doesn’t work.

**Comment by womfoo** [comment]
Hey @Profpatsch sorry I misread. This seems reasonable until we figure out the hydra issue.

**Comment by aszlig** [comment]
@womfoo, @Profpatsch: This is/was **not** a Hydra-issue, `nix-store -r /nix/store/06ls4az5kyhrh2g95gs2rbbimfg40c9g-fetchdarcs.drv` results in exactly the same.

**Comment by Profpatsch** [comment]
Can someone reproduce this anywhere?
