### ISSUE TITLE
Situation of gnuradio 3.7

### ISSUE THREAD

**Issue by eduardosm** [NixOS/nixpkgs#128620]
While `gnuradio3_7Minimal` builds fine, full gnuradio 3.7 cannot be built on master or release-21.05:
```
error: certifi-2021.05.30 not supported for interpreter python2.7
```

Additionally, dependency `python2.7-Pillow-6.2.2` is marked as insecure.

cc @doronbehar

**Comment by prusnak** [comment]
This PR reintroduces python2Packages.certifi: https://github.com/NixOS/nixpkgs/pull/127453

**Comment by FliegendeWurst** [comment]
Build was fixed by the linked PR.
