### ISSUE TITLE
Yandex Browser

### ISSUE THREAD

**Issue by Flygrounder** [NixOS/nixpkgs#128761]
**Project description**
Web browser, made by a russian company Yandex. Based on Chromium, integrates well with Yandex services. There are deb and RPM packages. Also it is [packaged](https://aur.archlinux.org/packages/yandex-browser-beta) in AUR, might be helpful for packaging.

**Metadata**

* homepage URL: https://browser.yandex.com/
* license: proprietary
* platforms: linux, darwin

**Comment by WolfangAukang** [comment]
[This has been packaged already](https://github.com/NixOS/nixpkgs/commit/4b04945c6386bc95db705c12d83a310985236d61#diff-8dce00bcb50e42060f38f35426e550c1288207ca432cfadebc25c670ae5dde77)
