### ISSUE TITLE
zabbix.agent2: Collecting custom metrics with using 'UserParameter' does not work

### ISSUE THREAD

**Issue by htower** [NixOS/nixpkgs#128734]
**Describe the bug**
Collecting custom metrics with using `UserParameter` does not work for zabbix.agent2.

**To Reproduce**
1. Add some custom `UserParameter` to agent's config:
```
services.zabbixAgent = {
  enable = true;
  server = "example.com";
  package = pkgs.zabbix.agent2;
  openFirewall = true;
  settings = {
    UserParameter = "test,uname"; 
  };
}
```
3. In the Zabbix web interface, add the corresponding data item (or dicovery rule) to the template used by our node.
3. Try to execute it (in the Zabbix web interface): "Test" button -> "Get value and test" button.
4. We get an error (in the Zabbix web interface): `Cannot execute command: exec: "sh": executable file not found in $PATH`.

**Expected behavior**
Normal execution of commands specified with `UserParameter`.

**Additional context**
`UserParameter` values are processed here:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/src/go/internal/agent/plugin_userparameter.go#117

And the actual command call is performed here:
https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/src/go/pkg/zbxcmd/zbxcmd_nix.go#36

**Notify maintainers**
@aanderse 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1240.71326cd12dd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1240.71326cd12dd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by aanderse** [comment]
We could backport https://github.com/NixOS/nixpkgs/pull/126284 or you could add `systemd.services.zabbix-agent.path = [ pkgs.bash ];` to your configuration until `21.11` comes out.

Do you mind opening a backport PR where you cherry-pick the commit?

**Comment by aanderse** [comment]
Backport has been merged into current release so should be available in channels shortly.
