### ISSUE TITLE
netcdf4: build fails on aarch64-darwin

### ISSUE THREAD

**Issue by purcell** [NixOS/nixpkgs#128717]
**Describe the bug**

The package builds but its tests fail, details below. This package is a prerequisite for `gdal`, `postgis` etc., which I'm trying to work towards building on M1.

**To Reproduce**
1. Start with `nixpkgs` `master` (currently 431ca399425b602de01c552efe29095dd138990d)
2. `nix-build --argstr localSystem aarch64-darwin -A python3Packages.netcdf4`

**Additional context**

Various test failures are reported, e.g.
```
*** testing nc_inq_varnatts ... ok
*** testing nc_inq_varndims ... ok
*** testing nc_inq_vartype ... ok
*** testing nc_get_var_text ...
        FAILURE at line 1393 of test_get.c: value read not that expected
        FAILURE at line 1393 of test_get.c: value read not that expected
        FAILURE at line 1393 of test_get.c: value read not that expected
        FAILURE at line 1393 of test_get.c: value read not that expected
        ### 4 FAILURES TESTING nc_get_var_text! ###
*** testing nc_get_var_uchar ... ok
*** testing nc_get_var_schar ... ok
```
```
*** testing nc_put_var_longlong ... ok
*** testing nc_put_var_ulonglong ... ok
*** testing nc_put_var1_text ...
        FAILURE at line 311 of test_put.c: Var value read not that expected
        FAILURE at line 311 of test_put.c: Var value read not that expected
        FAILURE at line 311 of test_put.c: Var value read not that expected
        FAILURE at line 311 of test_put.c: Var value read not that expected
        ### 4 FAILURES TESTING nc_put_var1_text! ###
```
```
*** testing nc_get_varm_longlong ... ok
*** testing nc_get_varm_ulonglong ... ok
*** testing nc_get_varm ...
        FAILURE at line 1605 of test_read.c: buf read not that expected
        FAILURE at line 1605 of test_read.c: buf read not that expected
        FAILURE at line 1605 of test_read.c: buf read not that expected
        FAILURE at line 1605 of test_read.c: buf read not that expected
        ### 4 FAILURES TESTING nc_get_varm! ###
*** testing nc_get_att_text ...
        FAILURE at line 10674 of test_get.c: value read not that expected
        ### 1 FAILURES TESTING nc_get_att_text! ###
```

**Notify maintainers**

**Metadata**
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(steve): `"darwin, nixpkgs-21.11pre297902.e8597594274"`
 - nixpkgs: `/Users/steve/.nix-defexpr/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - "python3Packages.netcdf4"
# a list of nixos modules affected by the problem
module:
```

**Comment by knedlsepp** [comment]
🤔 I don't see homebrew applying anything aarch-specific: https://github.com/Homebrew/homebrew-core/blob/52ad4319821c5c8244614842ebb900c9d7b98370/Formula/netcdf.rb

**Comment by purcell** [comment]
The one thing that Homebrew _does_ do is disable the tests...

**Comment by robcowie** [comment]
I concur. This prevents `gdal` installation.

**Comment by purcell** [comment]
Googling turned up an (old) result from the GDAL devs saying that such test failures could be ignored, and since all the other tests are passing and the homebrew folks are disabling tests wholesale, perhaps an acceptable workaround is to disable tests on this platform+arch.

**Comment by knedlsepp** [comment]
> Googling turned up an (old) result from the GDAL devs saying that such test failures could be ignored, and since all the other tests are passing and the homebrew folks are disabling tests wholesale, perhaps an acceptable workaround is to disable tests on this platform+arch.

Sounds good to me. Could you submit a PR? Maybe referencing the links you're referring to?

**Comment by purcell** [comment]
Yes, I'll take a look if get chance. It's probably somewhat fiddly because `doCheck` is already `false` here: the homebrew formula (linked above) passes a bunch of different build flags to cmake to disable tests for various things, it doesn't look like an easy fix relative to my personal nix skill level.

Btw, that link I mentioned:

> "Don't be too concerned about this. 90% of the problems we have
> with nc_test and nf_test are with the tests themselves. (Arrgh.)"

But that's [from '97](https://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg02113.html), lol.

**Comment by purcell** [comment]
Seems resolved now, closing.
