### ISSUE TITLE
Unstable channel hasn't updated in 2+ weeks

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#12885]
https://github.com/NixOS/nixpkgs-channels is lagging behind `master` for 18 days (at the time of this writing). https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents suggests that the installer tests are broken.

**Comment by domenkozar** [comment]
They're fixed now, let's see if all tests pass.

**Comment by vcunat** [comment]
Now it seems there are only abortions due to *no space left on device*.

**Comment by vcunat** [comment]
@edolstra, @rbvermaa: the out-of-space situation seems to be permanent, still causing failures even a few minutes ago.

**Comment by vcunat** [comment]
Tests passed now: http://hydra.nixos.org/build/32006252#tabs-summary

**Comment by domenkozar** [comment]
And we have an update

**Comment by vcunat** [comment]
The next one: https://github.com/NixOS/nixpkgs/issues/13439
