### ISSUE TITLE
All audio output devices gone after recent update

### ISSUE THREAD

**Issue by oxalica** [NixOS/nixpkgs#128893]
**Describe the bug**
I just updated my nixpkgs from 33d42ad7cf2769ce6364ed4e52afa8e9d1439d58 to 3a8d7958a610cd3fec3a6f424480f91a1b259185, and found all audio output devices (open the list from KDE tray icon) are gone and of course no sound can be played.

I tried `pulseaudio` and `pipewire`, both of which work for me and now show same empty list after the update.

For `pulseaudio`:
```nix
{
  hardware.pulseaudio.enable = true;
  sound.enable = true;
  users.groups."audio".members = [ "my-user-name" ];
}
```
And user systemd service `pulseaudio.service` reported some errors: (There's no errors before updating nixpkgs)
```
Jul 01 22:28:27 invar systemd[2167]: Started Sound Service.
Jul 01 22:29:12 invar systemd[2167]: pulseaudio.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Jul 01 22:29:24 invar pulseaudio[12343]: Failed to find a working profile.
Jul 01 22:29:24 invar pulseaudio[12343]: Failed to load module "module-alsa-card" (argument: "device_id="0" name="pci-0000_0c_00.1" card_name="alsa_card.pci-0000_0c_00.1" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred>
Jul 01 22:29:27 invar systemd[2167]: Stopping pulseaudio.service...
```

For `pipewire`:
```nix
{
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
}
```
All user systemd services of `pipewire` are running without errors, but still result in empty audio output device list.

**To Reproduce**
1. Choose either `pulseaudio` or `pipewire` configuration above.
2. Login KDE.
3. See a slash on the audio tray icon. Clicking it shows that there is no audio output device.

**Expected behavior**
Should show my audio devices and play sounds.

**Additional context**

Maybe related: #126415 #126416

**Notify maintainers**

@AndersonTorres @petabyteboy @r-burns @lovek323 @jtobin 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.11.20210618.33d42ad (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/store/jc7qnirghr97cvwv84nyxi7iqil0jj8a-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- alsa-utils
- pulseaudio
- pipewire
# a list of nixos modules affected by the problem
module:
- sound
- pulseaudio
- pipewire
```

**Comment by matdsoupe** [comment]
same problem here!

`pulseaudio` and `pipewire` tested!

- system: `"x86_64-linux"`
 - host os: `Linux 5.13.0, NixOS, 21.11pre300226.20887e4bbfd (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre300226.20887e4bbfd"`
 - channels(matthew): `"home-manager, nixos-21.11pre300226.20887e4bbfd, nixpkgs-21.11pre300283.f930ea227ce"`
 - nixpkgs: `/home/matthew/.nix-defexpr/channels/nixpkgs`

**Comment by oxalica** [comment]
https://github.com/NixOS/nixpkgs/issues/128925#issuecomment-873632394 said this issue would be fixed by #128746 . But it's still in `staging` and requires a mass rebuild making it hard to test.

**Comment by aszlig** [comment]
@oxalica: In the meantime you could use `system.replaceRuntimeDependencies` like this:

```nix
{ pkgs, lib, ... }:

{
  system.replaceRuntimeDependencies = lib.singleton {
    original = pkgs.alsa-lib;
    replacement = pkgs.alsa-lib.overrideAttrs (drv: rec {
      # NOTES:
      #
      # Since the store paths are replaced in the system closure, we can't use
      # "1.2.5.1" here because it would result in a different length.
      #
      # Additionally, the assertion here is to make sure that once version
      # 1.2.5.1 hits the system we get an error and can remove this altogether.
      version = assert pkgs.alsa-lib.version == "1.2.5"; "1.2.X";
      src = pkgs.fetchurl {
        url = "mirror://alsa/lib/${drv.pname}-1.2.5.1.tar.bz2";
        hash = "sha256-YoQh2VDOyvI03j+JnVIMCmkjMTyWStdR/6wIHfMxQ44=";
      };
    });
  };
}
```

**Comment by dtzWill** [comment]
I'm also encountering this issue when bumping to latest master (unstable)... Just gave @aszlig's snippet a try and I can confirm it does the trick for me!  Thanks this'll get things by until staging is merged, appreciate it!

**Comment by matdsoupe** [comment]
unfortunely this workaround didn't work for me :/

**Comment by aszlig** [comment]
@matdsoupe: `replaceRuntimeDependencies` does come with its own drawnbacks and for example it doesn't work if the referenced path can't be found in plain text (eg. if the file is compressed or using some multibyte encoding).

You can also directly override the dependency on the corresponding package, for example if you use PulseAudio:

```nix
{ pkgs, lib, ... }:

{
  hardware.pulseaudio.package = pkgs.pulseaudio.override {
    alsa-lib = pkgs.alsa-lib.overrideAttrs (drv: rec {
      version = assert pkgs.alsa-lib.version == "1.2.5"; "1.2.5.1";
      src = pkgs.fetchurl {
        url = "mirror://alsa/lib/${drv.pname}-${version}.tar.bz2";
        hash = "sha256-YoQh2VDOyvI03j+JnVIMCmkjMTyWStdR/6wIHfMxQ44=";
      };
    });
  };
}
```

Note however that if an application is bypassing PulseAudio, it will use the old version of `alsa-lib`.

**Comment by oxalica** [comment]
@aszlig 
> In the meantime you could use system.replaceRuntimeDependencies like this

It works for me with pipewire! Thanks.

**Comment by matdsoupe** [comment]
> @matdsoupe: `replaceRuntimeDependencies` does come with its own drawnbacks and for example it doesn't work if the referenced path can't be found in plain text (eg. if the file is compressed or using some multibyte encoding).
> 
> You can also directly override the dependency on the corresponding package, for example if you use PulseAudio:
> 
> Note however that if an application is bypassing PulseAudio, it will use the old version of `alsa-lib`.

Thank you! Now I better understand! That worked for me!

**Comment by Artturin** [comment]
i assume this has been fixed now that 128746 is in nixos-unstable
