### ISSUE TITLE
Problem when creating a user in MariaDB

### ISSUE THREAD

**Issue by jonocodes** [NixOS/nixpkgs#12882]
I have installed maria via my config:

```
  services.mysql = {
    enable = true;
    package = pkgs.mysql;
  };
```

But I am not able to create a user in it. First try the following in Docker to see how it should work.

``` bash
> docker run --name mymaria -d -e MYSQL_ROOT_PASSWORD=root mariadb
> docker exec -it mymaria bash
> export TERM=dump
> mysql -u root -p -e "create database foo; create user 'bar' identified by 'password'; grant all privileges on foo.* to 'bar'@'%'; flush privileges;"
> mysql -u bar foo -p -e "show databases;"
```

Successfully prints:

```
+--------------------+
| Database           |
+--------------------+
| foo                |
| information_schema |
+--------------------+
```

but in NixOS, instead of printing the databases, it prints the following:

```
Error 1044: (42000): Access denied for user 'bar'@'localhost'
```

**Comment by heydojo** [comment]
Should :
```
mysql -u bar foo -p -e "show databases;"
```
not be?
```
mysql -u bar -p -e "show databases;"
```

**Comment by jonocodes** [comment]
@heydojo Either way. The database listing is not important. All I am trying to do is see if the created user can access the database.

**Comment by zimbatm** [comment]
/cc @thoughtpolice @wkennington 

I can reproduce the issue but don't know how to debug further. Is it possible that mariadb changed their auth ? Running 10.1.9-MariaDB here.

**Comment by jonocodes** [comment]
I'm no longer using nix so dont know.

**Comment by Profpatsch** [comment]
Then I’ll close this, if someone else stumbles over this they can create a new issue or we re-open.
