### ISSUE TITLE
Python: build wheel in separate function

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#12887]
Currently `buildPythonPackage` builds the wheel, installs it, tests the Python package and then discards the wheel. How about we keep the wheel and add it as `buildInput` to the function that installs and tests the Python package? 

For users this wouldn't make any difference, however, for Python developers it would; they wouldn't have to rebuild the wheels when just updating the `checkPhase` (which is often the case when "fixing" tests).
One disadvantage is that we have more garbage.

Furthermore, I think we also have to make a distinction at this point between `buildInputs` for actually building the wheel, and inputs for testing the installation of the package. Would `checkInputs` make sense to have?

**Comment by copumpkin** [comment]
I've always wondered about this more broadly than just Python, whether it was worth splitting out tests and builds. Still not leaning strongly either way, but I wouldn't mind seeing it happen.

**Comment by joelmo** [comment]
Maybe it's better to make enhancements when building from a nix-shell, it's possible to check if $IN_NIX_SHELL is set and then apply enhancements for developers. And this would avoid the more garbage issue.

**Comment by FRidh** [comment]
@copumpkin I can understand that at some point you have to say, this is the smallest component that we consider for in the store. Otherwise you could go as far as making a store entry for the result after each phase. I think it makes sense to combine the build with the testing, and consider the result of that the product that ends up in the store. 

In practice I find, at least with Python packages, that sometimes some tests fail which can be disabled. Unfortunately I would have to recompile the package again then. With most Python packages that is not an issue, but with packages like numpy or scipy it is.

As @joelmo mentions this is exactly what `nix-shell` is good for. Currently it doesn't work so well with Python packages. Maybe that should indeed be improved first.

**Comment by joelmo** [comment]
A more generic solution would maybe be to enable some compilation cache in these cases. I would really want this and have seen that one can replace stdenv but if that is done a huge rebuild has to be done (last time I tried) https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L5695. If ccache support is enabled in the build script I think that rebuild can be avoided.

**Comment by FRidh** [comment]
There is a new format that we need to take into account, Flit
https://github.com/NixOS/nixpkgs/issues/14945

The amount of packages that use Flit is still small, but if Flit becomes more popular, we definitely need a straightforward way to build such packages.

I'm thinking of the following:
- `builldSetuptoolsWheel` to build wheels like we do now.
- `buildFlitWheel` to build wheels based on the Flit format.
- `buildPythonPackage` that gets a `format ? "setuptools"` parameter for choosing the method for building the wheel. The wheel is the `buildInput` to the Python package.
- Split `buildInputs`. The new `buildInputs` is for actually building the wheel, and `checkInputs` for testing the final package.

**Comment by FRidh** [comment]
This could be a nice enhancement but doesn't necessarily need to be done, so I am closing this.
