### ISSUE TITLE
unifi: embedded libsnappyjava.so has unresolvable dynamic link to libstdc++.so

### ISSUE THREAD

**Issue by elitak** [NixOS/nixpkgs#12897]
Version: 16.03pre75740.f727f81 (Emu)

To reproduce:

1. Try to run set-inform on a gateway device to point it to the nixos host running unifi.
2. The device will fail to be adopted, repeatedly.
3. systemctl status -l unifi will show:

        Feb 09 19:07:29 unifi java[10815]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        Feb 09 19:07:29 unifi java[10815]: at java.lang.Thread.run(Thread.java:745)
        Feb 09 19:07:29 unifi java[10815]: Caused by: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.0.5-libsnappyjava.so: libstdc++.so.6: cannot open shared object file: No such file or directory
        Feb 09 19:07:29 unifi java[10815]: at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        Feb 09 19:07:29 unifi java[10815]: at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        Feb 09 19:07:29 unifi java[10815]: at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        Feb 09 19:07:29 unifi java[10815]: at java.lang.Runtime.load0(Runtime.java:809)
        Feb 09 19:07:29 unifi java[10815]: at java.lang.System.load(System.java:1086)
        Feb 09 19:07:29 unifi java[10815]: at org.xerial.snappy.SnappyNativeLoader.load(SnappyNativeLoader.java:39)
        Feb 09 19:07:29 unifi java[10815]: ... 31 more

This is because the java service extracts an embedded snappy-1.0.5-libsnappyjava.so to /tmp and tries to use it. It fails, since this is a binary compiled without nixos. Since this package is built from a tarball of binaries, I don't know if it's even possible to remedy this cleanly. My workaround is adding the following to configuration.nix:

    # HACK to fix /tmp/snappy-1.0.5-libsnappyjava.so (extracted by service from jar) not having link to any libstdc++.so.6
    environment.systemPackages = with pkgs; [ gcc ];
    systemd.services.unifi.environment= { LD_LIBRARY_PATH = "/run/current-system/sw/lib"; };

This allows the java parent process to find libstdc++.so.6 at runtime. I don't know any better way to handle this requirement; hopefully a more experienced contributor knows a better solution.

**Comment by copumpkin** [comment]
I'd imagine we'd either have to extract the tarball, `patchelf` the contents, and then tar it up again, or perhaps just use a wrapper around the main `unifi` binaries, so that you don't need to modify the environment in the service.

**Comment by wkennington** [comment]
Feel free to cherry-pick https://github.com/triton/triton/commit/a680e7584402a7dbc308046e44b7f481e67641ed

**Comment by elitak** [comment]
Unfortunately, that fix doesn't address the problem, since the .so in question is inside a .jar and extracted conditionally(?) at runtime:

   ./UniFi/lib/snappy-java-1.0.5.jar: org/xerial/snappy/native/Linux/amd64/libsnappyjava.so
   ./UniFi/lib/snappy-java-1.0.5.jar: org/xerial/snappy/native/Linux/arm/libsnappyjava.so
   ./UniFi/lib/snappy-java-1.0.5.jar: org/xerial/snappy/native/Linux/armhf/libsnappyjava.so
   ./UniFi/lib/snappy-java-1.0.5.jar: org/xerial/snappy/native/Linux/i386/libsnappyjava.so
   ./UniFi/lib/snappy-java-1.0.5.jar: org/xerial/snappy/native/OpenBSD/amd64/libsnappyjava.so
   ./UniFi/lib/snappy-java-1.0.5.jar: org/xerial/snappy/native/OpenBSD/i386/libsnappyjava.so

Reconstructing the jar files seems tedious and error-prone. It's also impossible in cases where a signed jar is used (not here, but possibly in the future), I think?

Probably wrapping the java invocation in the service file is the way to go, as it should accommodate more unpleasant surprises possibly to come in the future. I'm not familiar enough to work out the exact way to do it. LD_LIBRARY_PATH may be appropriate, but I don't know how, at runtime, to get the nix-store path that contains the proper libstdc++.so.6 (hence my use of the system-wide lib dir). Is that even possible and safe? Seems like libstdc++ must be part of the unifi's buildInputs since the manager will need to track the store path as a dependency.

**Comment by wkennington** [comment]
It seems reasonable to add stdenv.cc.cc/lib and stdenv.libc to ld library
path of the service in that case.

**Comment by elitak** [comment]
Okay. Would you like me to pull request a patch for the nixos module or do you want to do it?

**Comment by wkennington** [comment]
Go ahead

**Comment by elitak** [comment]
Okay, sorry it took me so long, but I had to first figure out how to replace the "nixos" channel system-wide,--which is notably absent from nixos manual, btw--then rebuild a lot of packages from source as a result. Here's the pull request:

https://github.com/NixOS/nixpkgs/pull/12941

Please advise on whether it's safer/better to include the libc path as well (they seem to be already handeld) or if just the gcc libs will suffice.
