### ISSUE TITLE
gitlint: Broken Package

### ISSUE THREAD

**Issue by houstdav000** [NixOS/nixpkgs#128998]
**Describe the bug**
Gitlint fails to build due to a dependency on click v7.1.2

**To Reproduce**
1. `nix-shell -p gitlint`

**Expected behavior**
Successful build of gitlint

**Screenshots**
![image](https://user-images.githubusercontent.com/17628961/124287911-8f9f0f80-db1e-11eb-86b7-e145011eca58.png)

**Additional context**
Looks like click got separated into two packages, one where it updated to 8.0.1 and is present in `python3Packages` and one where it was kept back for `python2Packages`.

**Notify maintainers**
@ethancedwards8 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.16.3-microsoft-standard-WSL2, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(david): `"home-manager, nixpkgs-21.11pre299378.db6e089456c"`
 - nixpkgs: `/home/david/.nix-defexpr/channels/nixpkgs`
 - 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: gitlint
```

**Comment by ethancedwards8** [comment]
Yeah this is interesting. As far as I know, things shouldn't just *break* like this. I assume this is a regression, as it used to build, it seems a LOT of stuff has started breaking. https://github.com/NixOS/nixpkgs/pull/128727

**Comment by fabaff** [comment]
`gitlint` doesn't work with later `click` releases. We have 8.0.1 and `gitlint` is pinning all releases (affects also `arrow`, I guess). It would requires that `gitlint` is overriding the releases.

**Comment by fabaff** [comment]
@houstdav000, could you please give #129169 a try?

**Comment by houstdav000** [comment]
> @houstdav000, could you please give #129169 a try?

Looks to be good on my system. Runs as intended with #129169
