### ISSUE TITLE
Mindustry: Fails to build on NixOS 21.05

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#128929]
```console
[kreyren@leonid:~]$ NIXPKGS_ALLOW_BROKEN=1 nix-env -iA nixos.mindustry
...
configuring
no configure script, doing nothing
building
/build/Mindustry /build

Welcome to Gradle 6.8.3!

...

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/build/Mindustry/settings.gradle' (/build/tmp.wfALjkNars/caches/6.8.3/scripts/cjjnld3d55pgftpmv7wz6xg61).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

...

BUILD FAILED in 4s
builder for '/nix/store/yi4bxzs4126kx93x8ylp33niln7mfzjz-mindustry-126.1.drv' failed with exit code 1
error: build of '/nix/store/yi4bxzs4126kx93x8ylp33niln7mfzjz-mindustry-126.1.drv' failed
```

Full log: https://gist.github.com/Kreyren/7e5a80fd56ce1de7949f47c59f090ecd

## Steps to reproduce
0. Get updated nixOS 21.05
1. As non-root user invoke `NIXPKGS_ALLOW_BROKEN=1 nix-env -iA nixos.mindustry` and expect build failure

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.05.961.1f91fd10406 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.961.1f91fd10406"`
 - channels(kreyren): `"home-manager-21.05, master, nixos-21.05.1226.f77036342e2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
 
 ![image](https://user-images.githubusercontent.com/11302521/124204079-842bf400-dade-11eb-9369-ae250841b696.png)

**Comment by Kreyren** [comment]
CC @fgaz @petabyteboy

**Comment by fgaz** [comment]
Well... that's why it's marked as broken ;-)

https://github.com/NixOS/nixpkgs/blob/43b257365c2c73fc31421e9b28dde1166d75506a/pkgs/games/mindustry/default.nix#L195-L196

It looks like [this was fixed in build 127](https://github.com/Anuken/Mindustry/issues/5114#issuecomment-868737771), but that's a pre-alpha, so I think we should wait for an actual release

**Comment by fgaz** [comment]
Hmm... I just tried updating the package to the pre-alpha, kotlin makes it even more complex than it is now

**Comment by tutacat** [comment]
> Well... that's why it's marked as broken ;-)
> 
> https://github.com/NixOS/nixpkgs/blob/43b257365c2c73fc31421e9b28dde1166d75506a/pkgs/games/mindustry/default.nix#L195-L196
> 
> It looks like [this was fixed in build 127](https://github.com/Anuken/Mindustry/issues/5114#issuecomment-868737771), but that's a pre-alpha, so I think we should wait for an actual release

As version after 126 is marked alpha, it makes sense to just use alphas

**Comment by fgaz** [comment]
> As version after 126 is marked alpha, it makes sense to just use alphas

[it isn't](https://github.com/Anuken/Mindustry/releases/tag/v126.2).

If someone wants to put in the work, I'd approve a pr that updates to pre-alpha, but I won't put in the work myself until there's a stable release, since it's pretty difficult to package it.

**Comment by Mindavi** [comment]
We can consider pointing to jdk15 (if still available) to unbreak it for now. I'll look into it (hopefully I find some time today).
