### ISSUE TITLE
neovim compiles against Lua 5.1 instead of luajit on aarch64-darwin

### ISSUE THREAD

**Issue by dbarrosop** [NixOS/nixpkgs#128959]
**Describe the bug**

I have an overlay to install neovim from a recent commit. When you use that overlay on a intel macbook neovim is compiled against luajit 2.1.0-beta3 while the same derivation on an M1 macbook compiles against Lua 5.1. I tried checking why that might be given it's the same exact overlay and luajit seems to compile just fine on aarch64 but I am afraid my nix skills weren't good enough.

**To Reproduce**

1. Install neovim with the following overlay:
```
self: super: {
  neovim-unwrapped = super.neovim-unwrapped.overrideAttrs (oldAttrs: {
    version = "master";
    src = super.fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "5aaa1a1c0473d9e9ac824201f92ec65e190beeb7";
      sha256 = "0nnw1gmfligzfkwlnbi1psz945ifqs2rpvf9ciq082l4y9abcp8m";
    };
    buildInputs = oldAttrs.buildInputs ++ [ super.tree-sitter ];
  });
}
```

2. Start neovim
3. Issue the command `:version`

On intel you will see:

```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by dbarroso
```

While on arm:

```
NVIM v0.5.0-dev
Build type: Release
Lua 5.1
Compilation:
Compiled by dbarroso
```

Main issue is that lots of nvim plugins require luajit and don't work with lua 5.1

**Expected behavior**

neovim should be compiled against luajit.

**Screenshots**

N/A

**Additional context**

**Notify maintainers**

@manveru @rvolosatovs @ma27

**Metadata**

Intel:

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.13`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs-21.11pre299378.db6e089456c"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs`
 ```

Arm:

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs-21.11pre299378.db6e089456c"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by rvolosatovs** [comment]
This is alredy done in https://github.com/NixOS/nixpkgs/issues/128959

**Comment by dbarrosop** [comment]
Oh, thanks for the quick response and for the great work. Closing this :)

**Comment by rvolosatovs** [comment]
Reopening, since this will again be the case once #129543 is merged.
By some reason builds with luajit on aarch64 still fail and I do not know why.
Refs https://github.com/NixOS/nixpkgs/issues/129099#issuecomment-875662966

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/129543

**Comment by rvolosatovs** [comment]
> fixed in #129543

#129543 switched back to using Lua 5.1 due to #129099 
I think this issue should be reopened. @Mic92 

Also see my comment above https://github.com/NixOS/nixpkgs/issues/128959#issuecomment-875664186

**Comment by gpanders** [comment]
I've been messing around with this for a few days without much success, but I do think that compiling with openresty-luajit does work (at least, luarocks builds successfully and the error in question with `luarocks.core.hardcoded` goes away). I am utterly lost in the maze of Nix abstractions though and don't know the best way to do this. I've tried using overlays to set LuaJIT to be the openresty version which seems to half work, but when I try and build neovim it's still using the version of luarocks built with LuaJIT 2.1.

Can someone who knows their way around Nix a little better take a deeper look into this?

**Comment by Mic92** [comment]
@gpanders Maybe make a pr for that so nixpkgs will use this version of luajit by default on macOS aarch64.

**Comment by gpanders** [comment]
Done

**Comment by Mic92** [comment]
merged.

**Comment by goldyard** [comment]
This problem appear again, I used on ubuntu22.04 aarch64 (m1 Docker), and got same error with the NVIM 0.7.2:

```
NVIM v0.7.2
Build type: Release
Lua 5.1
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by acarl005** [comment]
I'm also hitting this issue again on ubuntu 22.04 aarch64 (m1 Docker)

**Comment by naveepr** [comment]
I am also seeing the same error in ubuntu 22.04 VM running on M1 MAC. This is based on aarch64.
