### ISSUE TITLE
java-language-server: Package Request

### ISSUE THREAD

**Issue by houstdav000** [NixOS/nixpkgs#128999]
**Project description**
A Java language server based on v3.0 of the protocol and implemented using the Java compiler API.

**Metadata**

* homepage URL: https://github.com/georgewfraser/java-language-server
* source URL: https://github.com/georgewfraser/java-language-server
* license: mit
* platforms: unix, linux, darwin

**Comment by winston0410** [comment]
+1. It will be great to have this
