### ISSUE TITLE
matterhorn missing custom emojis file

### ISSUE THREAD

**Issue by jasom** [NixOS/nixpkgs#129048]
**Describe the bug**
Builtin Emojis are missing; only custom emojis show up for e.g. reacting to a message or tab-completing when typing an emoji

**To Reproduce**
1. ensure that `~/.config/matterhorn/emoji.json` does not exist
2. nix-shell -p matterhorn
3. run matterhorn and connect to any server (e.g. https://community.mattermost.com/)
4. type `:smile` followed by the TAB key

**Expected behavior**
See a list of emoji including `:smile:` `:smiley:`

**Observed behavior**

On the Mattermost community server there is a custom emoji `:test-smile:` that shows up in the list, but the builtins do not appear.

**Additional context**
Matterhorn searches two paths:
`~/.config/matterhorn/emoji.json` and `MHBIN/emoji/emoji.json` where MHBIN is the path containing the matterhorn binary.  The easiest way to fix this is to copy the emoji directory from the upstream source to `$out/bin`.  I'm insufficiently familiar with how the hackage packages are generated to know how to do this.

**Notify maintainers**
@Kiwi 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.108, NixOS, 21.05.804.5de44c15758 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(aidenn): `""`
 - channels(root): `"nixos-21.05.804.5de44c15758, nixos-unstable-21.11pre291991.ea7d4aa9b82"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by sternenseemann** [comment]
Seems like this will require something like <https://github.com/matterhorn-chat/matterhorn/pull/724>, I'd be happy to patch this in in nixpkgs after verifying with upstream this isn't too terrible.

Hopefully this gets merged as well.

**Comment by sternenseemann** [comment]
Has been fixed a while back, feel free to reopen if the problem persists.
