### ISSUE TITLE
isso: javascript files not generated during packaging

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#129277]
**Describe the bug**
The packaging of `isso` seems not generating the javascript files to run the commenting server.

**To Reproduce**
1. `nix-shell -p isso`
2. create a config file `isso.cfg`
```
[general]
; database location, check permissions, automatically created if not exists
dbpath = /home/asbachb/dev/tmp/isso/comments.db
; your website or blog (not the location of Isso!)
host = http://localhost:8080
```
3. `isso -c isso.cfg`
4. check for missing generated files
```
curl http://localhost:8080/js/config.js
curl http://localhost:8080/js/embed.min.js
```

**Expected behavior**
Be able to retrieve javascript files.

**Additional context**
see https://posativ.org/isso/docs/install/#install-from-source which indicates that `make init` is used to generate these files and/or `make js` for optimization.

**Notify maintainers**
@fgaz @Enteee 

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.12, NixOS, 21.11pre299299.3a8d7958a61 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(asbachb): `"nixos-21.05pre286647.4518794ee53, nixos-20.09-20.09.4025.dc326c78a93"`
 - channels(root): `"nixos-21.11pre299299.3a8d7958a61, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
* isso
module:
```

**Comment by RaitoBezarius** [comment]
I confirm I can hit this bug.

**Comment by RaitoBezarius** [comment]
I have implemented a quick'n'dirty fix here: https://github.com/RaitoBezarius/nixexprs/commit/46e39453806a9f5eac6f75a2c0402d1b817dc61d consisting into using `node2nix` on the upstream `package.json` to generate the proper environment so that `make js` can execute itself.

Feel free to use it or open a PR to nixpkgs with it, if it makes sense. :)

**Comment by asbachb** [comment]
I'm working on it, but I'm a little bit stuck since I'm not that into the nod stuff: https://github.com/NixOS/nixpkgs/commit/866f9c29b6e5830a1efab90fd5b82e26eb7fd4e4

**Comment by RaitoBezarius** [comment]
@asbachb I was not able to read the contents of `node-composition.nix` but basically, you copy the `package.json` of the project, and you run `node2nix` in a folder with it, so it produces some Nix files which will create the dependency environment for this project.
Then, you link the resulting `node_modules` like I have done.

Another approach would be to have proper lockfiles and use yarn2nix, but that requires `yarn` to be used by the project, or you would have to convert the project to `yarn` yourself.

**Comment by fgaz** [comment]
I'm also not familiar with packaging js stuff so thanks for the effort! If all else fails we could also just fetch the prebuilt .js files

**Comment by RaitoBezarius** [comment]
> I'm also not familiar with packaging js stuff so thanks for the effort! If all else fails we could also just fetch the prebuilt .js files

We should be able to make it work :-) as <comments.lahfa.xyz> is running `isso` on NixOS without any issue regarding the generated JS files :P

**Comment by asbachb** [comment]
> > I'm also not familiar with packaging js stuff so thanks for the effort! If all else fails we could also just fetch the prebuilt .js files
> 
> We should be able to make it work :-) as comments.lahfa.xyz is running `isso` on NixOS without any issue regarding the generated JS files :P

I don't know where they include isso. But I think they need to get these javascript files from somewhere else.

**Comment by RaitoBezarius** [comment]
I didn't understand your remark.
They're getting these files from 'make js' :)

Le ven. 6 août 2021 à 19:36, Benjamin Asbach ***@***.***> a
écrit :
