### ISSUE TITLE
Keep building non-dependent derivations even if one fails. 

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#12925]

**Comment by colemickens** [comment]
I have no idea if this is a feasible thing to even bring up for discussion. When trying to build master, I was running into #12924. When I fixed `pijul`, a bunch of other unrelated stuff had to build. Nothing depends on `pijul` right now, so there's not a technical reason that I see that would prevent nix from building the other derivations. That way when I fix `pijul`, I'm ready to go, instead of waiting for `qtwebkit` to build, for example.

**Comment by domenkozar** [comment]
This should be migrated to https://github.com/NixOS/nix

**Comment by colemickens** [comment]
Will do.
