### ISSUE TITLE
mariadb has gcc in runtime closure

### ISSUE THREAD

**Issue by Uthar** [NixOS/nixpkgs#129236]
Hello everyone! This is maybe a bug, but more of a plea for help from someone with knowledge of **GCC libs** and the **pam_*** stuff.

**Describe the bug**

GCC is present in the runtime closure of mariadb, which makes it >200MiB larger.

**Additional context**

Files containing GCC's hash:
- `${mariadb}/share/pam/lib/security/pam_mariadb_mtr.so`
- `${mariadb}/share/pam/lib/security/pam_user_map.so`

Those files, in turn, refer to the paths:
- `${gcc}/lib/gcc/x86_64-unknown-linux-gnu/10.3.0/crtbeginS.o`
- `${gcc}/lib/gcc/x86_64-unknown-linux-gnu/10.3.0/crtendS.o`

I don't know what these object files or the pam libs are, so I'm asking here for help with identifying and removing them.

One reason why it would be nice to remove GCC from the closure is for building container images. Currently an image built with `dockerTools.buildImage` containing only `mariadb` has ~850MB which is twice the size of `docker.io/library/mariadb`. 

**Notify maintainers**
@thoughtpolice 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(kpg): `""`
 - channels(root): `"nixos-21.05.1268.21b696caf39"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mariadb
# a list of nixos modules affected by the problem
module:
```

**Comment by KAction** [comment]
For what it worth, it is still true. It actually also depends on `less(1)`, which also looks out-of-place.

**Comment by Artturin** [comment]
only a gcc.lib dependency remains which is ok

`/nix/store/dg8rnzij70blnn9cqxdvan1wwmqg167b-mariadb-server-10.6.12            	206.8M	453.6M`

the less dependency is intentional and added in wrapProgram
