### ISSUE TITLE
Add `Ventoy` package

### ISSUE THREAD

**Issue by TheBlackBeans** [NixOS/nixpkgs#129342]
**Project description**
Ventoy is a tool that allows to easily create bootable usb drives with multiple booting options.

**Metadata**

* homepage URL: ventoy.net
* source URL: [ventoy/Ventoy](https://github.com/ventoy/Ventoy)
* license: GPL-3.0
* platforms: cross-platform
* dependencies: none

**Comment by Luflosi** [comment]
Closing, since #130824 has been merged.
