### ISSUE TITLE
nixos-install fails with tarball channel

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#129331]
From the minimal iso (custom build with ssh enabled and ssh keys), the install build fails because it's looking in the wrong nix store:

```
[root@stratokit-nixos-iso:~]# nixos-install --root /mnt --channel nixpkgs=https://releases.nixos.org/nixos/21.05/nixos-21.05.1240.71326cd12dd/nixexprs.tar.xz --no-channel-copy --show-trace
building the configuration in /mnt/etc/nixos/configuration.nix...
error: opening file '/nix/store/gfzhl0r80gnii61fhxqy7vfwzhrymx5g-nixexprs.tar.xz': No such file or directory
```

**Additional context**

This same command used to work just fine in 20.05 with a 20.05 iso and url. Something seems to have changed with how nix-build finds the store to use?

The file that it wants is in `/mnt/nix/store`. Perhaps the channel downloader listens to `--store` but the channel expander doesn't?

**Notify maintainers**

@Mic92 @edolstra 

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1240.71326cd12dd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1240.71326cd12dd"`
 - nixpkgs: `/nix/store/4izm1bncfm4ya84cvv6mwzkahxsjpvig-nixexprs.tar.xz`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: config.system.build.isoImage
```

**Comment by wmertens** [comment]
I must add that I'm trying to repro this on a fresh VM and it's working fine... so weird.

Any ideas what could be going on? How could nix-build not download the nixexprs because they are in /mnt/nix/store but then fail because it's not in /nix/store?

**Comment by Mic92** [comment]
Is this still an issue with 21.11?

Please test and than I re-open the issue if it is the case.
