### ISSUE TITLE
Grub config corrupted rendering system unbootable

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#12949]
b861bf8ddff677031e93a8e1c55311be63e0eb63 did some bad substitutions on my grub.cfg, substituting in undefined values for $kernel and $initrd.

That change needs to be reverted---I booted off a rescue system, hand-hacked the grub.cfg, then reverted that change and everything built fine again.

And then, some actual error-handling needs to be build into the script, so that it doesn't create a bogus file like that in the future, and I would recommend having it maintain some number of versions of grub.cfg, since that is otherwise unversioned, which kind of tanks the "you can rollback from anything" assertion. :)

**Comment by mdorman** [comment]
I should also be clear: there was an element of pilot error here, in that it does spew a bunch of complaints about concatenating an undefined variable, which should have given me pause (which should be easy for anyone to verify).  While that means that the hour I spent recovering is clearly on me, the change still needs to be reverted.

**Comment by edolstra** [comment]
@peti reverted this in a1fa485378f3c17946c138935fd46be2178da389. The original patch very wrong to me, since paths in grub.cfg are generally not absolute but relative to the boot disk.

**Comment by copumpkin** [comment]
cc @benwbooth who might not have noticed the revert

**Comment by benwbooth** [comment]
Hey guys,

@mdorman, I'm really sorry that my changes messed up your boot! I didn't realize grub paths can be relative. 

I did some testing and found that File::Spec->canonpath() seems to have the correct behavior; it keeps relative paths relative but removes double backslashes:

```
$ perl -MFile::Spec -le 'print File::Spec->canonpath("//")' 
/
$ perl -MFile::Spec -le 'print File::Spec->canonpath("./test")' 
test
$ perl -MFile::Spec -le 'print File::Spec->canonpath("a/b/c")' 
a/b/c
$ perl -MFile::Spec -le 'print File::Spec->canonpath("//test")'
/test
```

I made a new pull request #12956 using File::Spec->canonpath() instead of Cwd::abs_path(). Can you guys check it out to see if it will work without breaking people's grub config? Thanks again and sorry for my mistake!

**Comment by mdorman** [comment]
@benwbooth Ehh, if you don't break something now and again...:)

**Comment by vcunat** [comment]
We should be extra careful with grub changes, as problems in there can't be rolled back so easily.

**Comment by mdorman** [comment]
Saving off a prior copy of the grub.cfg would at least make recovery more trivial.

**Comment by abbradar** [comment]
I haven't witnessed the issue first-hand, but @mdorman mentioned [here](https://github.com/NixOS/nixpkgs/issues/12949#issuecomment-183301807) about a bunch of Perl warnings shown. I think warnings in scripts like this should be treated seriously -- do we have something like `-Werror` for Perl?

**Comment by mdorman** [comment]
`use warnings FATAL => 'all';` is kind of like that, though, of course, it is run-time rather than compile-time.

Community sentiment on setting it is, at best, divided.

**Comment by abbradar** [comment]
Well, I don't really know Perl so I have no knowledge of its idioms but it seems to me it's an example of script where this can be useful. It will be run-time of course, `-Werror` was for an analogy ~_^. But if we replace new `grub.cfg` atomically (and I think we do) then panicking mid-way would do the necessary job (worst case we would have `grub.cfg.tmp` left somewhere).

**Comment by ocharles** [comment]
Is this currently in the unstable channel? I also now have an unbootable system, and I don't think I built from `master`. If so we really should be manually updating the channel to at least have an older set of `nixpkgs` that doesn't include this :(

**Comment by domenkozar** [comment]
In general, use `nixos-unstable` channel as it goes through all the testing. With `nixpkgs` you skip all our effort to prevent you from mistakes like this. 

I know `nixos-unstable` hasn't been updating regulary lately, hopefully that will get better very soon.

**Comment by mdorman** [comment]
@ocharles I'm assuming that you've been able to reboot into a rescue instance or something and recover, but if not, let me know and I'm happy to try and help.

**Comment by ocharles** [comment]
We literally have a nixpkgs that can practically brick a system - I don't think "don't worry, it will get fixed eventually" is good enough here. I'm willing to take a breakage that lets me use a previous generation, but this goes beyond even that.

@mdorman thanks for the offer, I managed to eventually get it to boot with the GRUB REPL.

**Comment by ocharles** [comment]
I may be wrong with that claim actually, as https://github.com/NixOS/nixpkgs/commit/a1fa485378f3c17946c138935fd46be2178da389 looks like it doesn't have this problem. If that's the case the disregard the above comment, sounds like I was reckless.

**Comment by cleverca22** [comment]
but https://github.com/NixOS/nixpkgs-channels/blob/nixpkgs-unstable/nixos/modules/system/boot/loader/grub/install-grub.pl does have the problem

and i have run into atleast one user running nixpkgs-unstable on nixos

**Comment by ocharles** [comment]
Thanks @cleverca22, I thought that was the case.

**Comment by peti** [comment]
I guess this issue can be considered fixed by now. Please re-open if I've missed anything.
