### ISSUE TITLE
Document PR "9.needs" labels

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#12946]
The PR labels starting with "9.needs" require some action from PR issuer that is not clearly defined. 

For example one PR I have submitted has "needs changelog" and "needs documentation". 
`grep "changelog" ./doc/ -r` give no hit, and some directions about where to put and an example of "good" documentation would be helpful.

There should be directions in the [contributor manual](https://nixos.org/nixpkgs/manual/) about how these labels should be addressed.

**Comment by globin** [comment]
Well needs documentation \o/ :joy:

**Comment by vcunat** [comment]
We need to document where documentation should go :-D

By changelog it's clearly meant the nixos release notes: `<nixpkgs/nixos/doc/manual/release-notes/>`. The other label seems rather generic.

**Comment by ericsagnes** [comment]
> By changelog it's clearly meant the nixos release notes: <nixpkgs/nixos/doc/manual/release-notes/>. The other label seems rather generic.

So release notes for a PR on master should added to `nixos/doc/manual/release-notes/rl-unstable.xml`, right?

Please correct if wrong, in release notes the following should be added:

- new services
- breaking changes, aka renamed/removed services
- improvements: new services description

Also there is a  [doc/release-notes.xml](https://github.com/NixOS/nixpkgs/blob/master/doc/release-notes.xml) which last entry was in 2012 that better be removed if not used anymore.

**Comment by vcunat** [comment]
Yes, correct file. Anything with larger impact on using NixOS should go there.

Those other release notes are from the days when there were nixpkgs "releases" announced. @edolstra: OK to remove this file? I suppose that even if we do *nixpkgs* releases again, they will be different (e.g. we might consider darwin in release-*).

**Comment by ericsagnes** [comment]
Closing as it is part of a new proposal #16635
