### ISSUE TITLE
Audiocity: init at alpha

### ISSUE THREAD

**Issue by papojari** [NixOS/nixpkgs#129484]
**Project description**
Audacity Fork without any Sentry Telemetry or Crash Reporting.

**Metadata**

* homepage URL: https://audiocity.studio/
* source URL: https://github.com/AudioCity-Studio/AudioCity
* license: gpl2+, gpl-compatiple
* platforms: windows, linux, macos

**Comment by urlordjames** [comment]
I'm not sure the NixOS team would accept a contribution like this currently.
https://github.com/NixOS/nixpkgs/blob/176b8cce2360c107b9310d3aa8d4c13a1b745d0a/pkgs/applications/audio/audacity/default.nix#L68-L71

**Comment by schmittlauch** [comment]
I propose to abandon this in favor of https://tenacityaudio.org/, judging by the contribution activity of both forks.
