### ISSUE TITLE
Roc Toolkit

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#129567]
**Project description**
Roc is a toolkit for real-time audio streaming over the network.

Basically, Roc is a network transport, highly specialized for the real-time streaming use case. The user writes the stream to the one end and reads it from another end, and Roc deals with all the complexity of the task of delivering data in time and with no loss. Encoding, decoding, adjusting rates, restoring losses -- all these are performed transparently under the hood.

The project is conceived as a swiss army knife for real-time streaming. It is designed to support a variety of network protocols, encodings, FEC schemes, and related features. The user can build custom configurations dedicated for specific use cases and choose an appropriate compromise between the quality, robustness, bandwidth, and compatibility issues.[1]

**Metadata**

* homepage URL: https://awesomeopensource.com/project/roc-streaming/roc-toolkit
* source URL: https://github.com/roc-streaming/roc-toolkit
* license: MPL-2.0
* platforms: any?

[1]: https://roc-streaming.org/toolkit/docs/about_project/overview.html

**Comment by jansol** [comment]
This appears to be particularly for ethernet-based audio streaming in studios, much like AES67 and Dante.

I don't have an acute need for this but it is an optional dependency for pipewire since 0.3.31: #128540.

**Comment by iclanzan** [comment]
I’ve been meaning to play with pipewire’s roc module, but sounds like I can’t yet. Is there another way to send audio over the network using pipewire?

**Comment by jansol** [comment]
Pipewire supports pulseaudio tunnels and "simple" network tunnels (AFAIK just PCM samples in a socket using a predetermined format).

But if you would be interested in packaging Roc for NixOS that'd be much appreciated. I can help with the overall packaging stuff and the pipewire side (although pipewire shouldn't require anything beyond adding the roc package as a build input and maybe enabling the roc module with a build flag).

**Comment by iclanzan** [comment]
I managed to package `roc-toolkit` in https://github.com/NixOS/nixpkgs/pull/139054 but am not yet successful at using it with pipewire’s module. After adding the build input, adjusting the flag and recompiling pipewire I can confirm the presence of the `libpipewire-module-roc-*` modules but I am getting the following error when configuring the [sink](https://docs.pipewire.org/page_module_roc_sink.html) and [source](https://docs.pipewire.org/page_module_roc_source.html) as per the docs:
```
core 0x559f843cba70: can't find protocol 'PipeWire:Protocol:Native': Operation not supported
pipewire[2554]: can't connect: Operation not supported
```

Using roc-toolkit’s builtin pulseaudio support works great through pipewire however, and performs much better (lower latency and more stable sound) than the pulseaudio tunnel module.

**Comment by wedens** [comment]
> Using roc-toolkit’s builtin pulseaudio support works great through pipewire however, and performs much better (lower latency and more stable sound) than the pulseaudio tunnel module.

Could you provide an example please? roc-toolkit doesn't seem to contain pulseaudio modules

**Comment by jansol** [comment]
@iclanzan AFAIK pipewire still relies on all the dependency modules being listed first in the config file so the roc module should be listed near the end, definitely after `libpipewire-module-protocol-native`.

Also if you only add the roc module to your nixos config it won't work as that replaces the entire array from the config file. You'll have to check the modules that are loaded in the default config from the pipewire module or from upstream git and replicate them in the same order in your nixos configuration if that is the case.

I think there was some talk about letting modules request their dependencies to be loaded on demand but I don't know how far that plan went.

**Comment by iclanzan** [comment]
> Could you provide an example please? roc-toolkit doesn't seem to contain pulseaudio modules

I used `roc-send -d pulseaudio` and `roc-recv -d pulseaudio` as per the examples at [roc-send](https://roc-streaming.org/toolkit/docs/manuals/roc_send.html) and [roc-recv](https://roc-streaming.org/toolkit/docs/manuals/roc_recv.html).

> pipewire still relies on all the dependency modules being listed first in the config file so the roc module should be listed near the end, definitely after libpipewire-module-protocol-native.

I didn’t realize the order mattered. I’ll experiment some more and report back.

> if you only add the roc module to your nixos config it won't work as that replaces the entire array from the config file.

Yup, I had included all modules as they appeared in the original derivation.

**Comment by iclanzan** [comment]
Ok, so I was able to successfully use the `roc-sink` and `roc-source` modules. I will follow up with a PR for enabling roc in pipewire as soon as https://github.com/NixOS/nixpkgs/pull/139054 lands.

One annoyance I am running into is the fact that the modules are constantly using network bandwidth even when I’m not sending any sound, but there’s probably some settings I can tweak. So far I’ve only used the config example from the [docs](https://docs.pipewire.org/page_module_roc_sink.html).

**Comment by jansol** [comment]
> the modules are constantly using network bandwidth even when I’m not sending any sound

That might be because Roc is meant to match things like AES68 and S/PDIF and as such has to carry a clock sync signal at all times

**Comment by jansol** [comment]
Roc-toolkit has been nixpkgs for a while now and pipewire is built with roc support enabled by default.
