### ISSUE TITLE
Packaging Request: Buttercup Password Manager

### ISSUE THREAD

**Issue by slightknack** [NixOS/nixpkgs#129523]
**Project description**

From [their repo](https://github.com/buttercup/buttercup-desktop):
> _Buttercup is a free, open-source and cross-platform password manager, built on NodeJS with Typescript._

They currently provide an AppImage, but I'm having trouble getting it to run with `appimage-run`. I think packaging this separately (i.e. build from source) would be best, but I'm not sure how to proceed. I'm new to Nix and NixOS, so help wrt this issue is appreciated!

**Metadata**

* homepage URL: https://buttercup.pw
* source URL: https://github.com/buttercup/buttercup-desktop
* license: GPL3
* platforms: linux, darwin, windows

**Comment by slightknack** [comment]
Update: got it to run with `appimage-run` by overriding the `extraPkgs` to include `libsecret`.

**Comment by Artturin** [comment]
try packaging it yourself 
use ripgrep to search nixpkgs for npm commands that are run in the aur pkgbuild
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=buttercup-desktop

for example
`rg -Sp -C 10 'npm run build' | less -RF`

to the default.nix use `nix-build -E "with import <nixpkgs> {}; callPackage ./default.nix {}"`
