### ISSUE TITLE
turbovnc: vncviewer fails to start when JAVA_HOME is set in the environment

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#129582]
**Describe the bug**
```
$ vncviewer
libjawt.so path: /nix/store/wp4y3mpdvislqcs3g3hq3s2izix4gjrg-openjdk-16+36/lib/openjdk/lib
/nix/store/28yk7g3klcf3y5h8sf8a7a740y2d46c9-turbovnc-2.2.6/bin/.vncviewer-wrapped: line 65: /nix/store/wp4y3mpdvislqcs3g3hq3s2izix4gjrg-openjdk-16+36/lib/openjdk:/nix/store/wp4y3mpdvislqcs3g3hq3s2izix4gjrg-openjdk-16+36/lib/openjdk/bin/java: No such file or directory
```

**To Reproduce**
1. make sure JAVA_HOME is set to something
2. start `vncviewer`
3. observe

**Expected behavior**
`vncviewer` should proceed regardless of the environment.

**Additional context**
`makeWrapper`'s `--prefix` seems to be used inappropriately given that `JAVA_HOME` is not a path-like variable. Should be `--set` or `--set-default`.

https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/tools/admin/turbovnc/default.nix#L101

**Notify maintainers**
@nh2 

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.20210706.9d1350d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `""`
 - channels(louis): `""`
 - nixpkgs: `/nix/store/r9gjdy2l63jibbqmlzn56p34ajkd4q2l-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by nh2** [comment]
> `JAVA_HOME` is not a path-like variable. Should be `--set` or `--set-default`.

Ah, that makes sense, I didn't know that.

PR to fix it: #129590
