### ISSUE TITLE
flask-appbuilder crashes on initialisation

### ISSUE THREAD

**Issue by mixmixmix** [NixOS/nixpkgs#129557]
**Describe the bug**
While trying to run [flask-appbuilder ](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/development/python-modules/flask-appbuilder/default.nix) examples (or any other project I have) flask crashes with an error on Nixos 21.05. On 20.09 everything worked fine.

**To Reproduce**
Using the minimal shell for python3.9 (or 3.8):
```
nix-shell -p python39Packages.flask-appbuilder
```

```
[nix-shell:~/repos/Flask-AppBuilder/examples/quickhowto/app]$ flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
/nix/store/g54zdl24iwiamx023nvaal9jxbhaaf58-python3.9-Flask-SQLAlchemy-2.5.1/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  warnings.warn(FSADeprecationWarning(
Usage: flask run [OPTIONS]

Error: While importing "app.wsgi", an ImportError was raised:

Traceback (most recent call last):
  File "/nix/store/2ll36s9hz8zaj915gv1sj4qxji0vpf90-python3.9-Flask-1.1.2/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/mix/repos/Flask-AppBuilder/examples/quickhowto/app/__init__.py", line 12, in <module>
    appbuilder = AppBuilder(app, db.session)
  File "/nix/store/fyljd6a98lp5rwrc0697zsn0q10q8dpz-python3.9-flask-appbuilder-3.3.0/lib/python3.9/site-packages/flask_appbuilder/base.py", line 148, in __init__
    self.init_app(app, session)
  File "/nix/store/fyljd6a98lp5rwrc0697zsn0q10q8dpz-python3.9-flask-appbuilder-3.3.0/lib/python3.9/site-packages/flask_appbuilder/base.py", line 196, in init_app
    from flask_appbuilder.security.sqla.manager import SecurityManager
  File "/nix/store/fyljd6a98lp5rwrc0697zsn0q10q8dpz-python3.9-flask-appbuilder-3.3.0/lib/python3.9/site-packages/flask_appbuilder/security/sqla/manager.py", line 20, in <module>
    from ..manager import BaseSecurityManager
  File "/nix/store/fyljd6a98lp5rwrc0697zsn0q10q8dpz-python3.9-flask-appbuilder-3.3.0/lib/python3.9/site-packages/flask_appbuilder/security/manager.py", line 15, in <module>
    from .api import SecurityApi
  File "/nix/store/fyljd6a98lp5rwrc0697zsn0q10q8dpz-python3.9-flask-appbuilder-3.3.0/lib/python3.9/site-packages/flask_appbuilder/security/api.py", line 2, in <module>
    from flask_jwt_extended import (
ImportError: cannot import name 'jwt_refresh_token_required' from 'flask_jwt_extended' (/nix/store/pg8d9b578acf39s45h77fqg0y334p1lc-python3.9-Flask-JWT-Extended-4.1.0/lib/python3.9/site-packages/flask_jwt_extended/__init__.py)
```

**Expected behavior**
Flask should run its server

**Notify maintainers**
@fabaff?

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.45, NixOS, 21.05.1268.21b696caf39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(mix): `"nixos-20.03.3191.504f993df9a"`
 - channels(root): `"nixos-21.05.1345.9d1350d9d56, nixos-hardware, nixos-unstable-21.11pre300783.036dc0c7096"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mixmixmix** [comment]
This problem is resolved by using flask-appbulder from unstable (upgraded to 3.3.1, this commit: https://github.com/NixOS/nixpkgs/commit/a3510b8eb61e47b4162caef64b84c0bba9c19e51)
However it seems to still cause another issue when trying to run the server due to conflicting sqlalchemy version 
https://github.com/dpgaspar/Flask-AppBuilder/issues/1648

**Comment by mixmixmix** [comment]
@fabaff @DavHau @dotlambda @SCOTT-HAMILTON:  You've been fixing this package before. Is it possible for us to avoid getting versions that are broken? Do we perform any user testing when updating python packages? I'd be happy to help with that.

**Comment by mixmixmix** [comment]
In case anyone else stumbles upon this issue, my workaround is to use the version from 20.09 in a nix-shell:

```
# add old nixos channel: sudo nix-channel --add https://nixos.org/channels/nixos-20.09 nixos-old
#sudo nix-channel --update
with (import <nixos-old> {});
let
  my-python-packages = python-packages: with python-packages; [
    pandas
    flask-appbuilder
    email_validator
    xlrd
  ];
  python-with-my-packages = python3.withPackages my-python-packages;
in
mkShell {
  buildInputs = [
    python-with-my-packages
  ];
}
```

**Comment by dotlambda** [comment]
> Do we perform any user testing when updating python packages?

Can you contribute a script that we could run to perform such tests? I don't use flask-appbuilder and I'm not sure any other maintainer does. Thus having an automated test is the only way to ensure we don't ship a broken package.

**Comment by mixmixmix** [comment]
> Hello @mixmixmix 👋
> 
> Since this doesn't seem to be a problem anymore in new versions, would you be able to close this issue? (I'm just going based on the conversation here).
> 
> (I'm going through issues marked as stale to see what can be resolved. If this issue still exists then don't mind me)

Sure!

> Can you contribute a script that we could run to perform such tests? I don't use flask-appbuilder and I'm not sure any other maintainer does. Thus having an automated test is the only way to ensure we don't ship a broken package.

I'm not using flask-appbuilder anymore, thanks for clarifiying the procedure though.
