### ISSUE TITLE
bbdb missing from stable MELPA packages?

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#12953]
We have `bbdb` in melpaPackages, but not on melpaStablePackages. Is that correct? It baffles me that this popular package (which has existed for aeons) has no "stable" release. Am I missing something?

Cc: @ttuegel

**Comment by ttuegel** [comment]
According http://stable.melpa.org, there are no stable versions of `bbdb` available. This should be fixed upstream by adding appropriate tags to the source repository. (That's how Melpa determines stable versions.)

**Comment by peti** [comment]
OK. Thank you for the quick response!
