### ISSUE TITLE
Q: How can i make a module that creates a file without depending on systemd?

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#129646]
**Context:** I am trying to make a module to manage a zonefiles for https://git.dotya.ml/RiXotStudio/system-management/, i don't have experience with nix so doing babysteps to get there.

So far i've made: http://ix.io/3sih

**Comment by nh2** [comment]
The question is vague an I am not sure if this is exactly what you are asking, but perhaps you would like to:

* Create a file using e.g. `environment.etc.<name>.text` (see [here](https://search.nixos.org/options?channel=21.05&from=0&size=50&sort=relevance&query=environment.etc) in NixOS module option search)
* Define its contents using the `writeText` function, see: https://github.com/NixOS/nixpkgs/blob/2d9425cae4054f7aace0025ac4ba76362848f027/pkgs/build-support/trivial-builders.nix#L140-L151
* Use functions like `map`, `concatStringsSep` (from [`strings.nix`](https://github.com/NixOS/nixpkgs/blob/2d9425cae4054f7aace0025ac4ba76362848f027/lib/strings.nix)) and so on to render out the contents of your zonefile (I'm assuming this is referring to a file as used like in the `bind` DNS server).

It's unclear to me whether that'll satisfy your requirement of "without depending on systemd", as I don't really know what that means. NixOS modules typically require running on NixOS, and NixOS uses systemd to boot. So while defining a file on the file system using `environment.etc.<name>.text` doesn't have a direct involvement of system, the fact that you're running NixOS will currently incur you a dependency on systemd running on that.

**Comment by Kreyren** [comment]
> It's unclear to me whether that'll satisfy your requirement of "without depending on systemd", as I don't really know what that means. -- @nh2

I was given an example using `systemd.tmpfiles.rules` to make said file so i was looking for alternative that doesn't use systemd as i like to make my code init-independent where possible

> (I'm assuming this is referring to a file as used like in the bind DNS server). -- @nh2

Yes, the end-goal is for bind, but i would like it flexible for other DNS servers in case e.g. unbound becames usable. (so with no hard dependency on bind)

> Create a file using e.g. environment.etc.<name>.text (see here in NixOS module option search) -- @nh2

That seems to only create files in `/etc` ? I would like to make the file in `/var/dns/thing.zone` ideally

> NixOS modules typically require running on NixOS, and NixOS uses systemd to boot. @nh2

Would like to make it flexible so that it could be used on NixOS forks e.g. NixN**G** which attempts to use OpenRC thus me wanting to use something else then `systemd.tmpfiles`

--

`writeText` and `concatStringsSep` are relevant, thank you! ^-^

--

**Comment by nh2** [comment]
> Would like to make it flexible so that it could be used on NixOS forks e.g. NixN**G** which attempts to use OpenRC thus me wanting to use something else then `systemd.tmpfiles`

I am not familar myself with OpenRC or NixNG, but I would imagine that it would probably be in NixNG's domain then to suggest some functionality how to procedurally generate files in not-immutable locations, like `systemd.tmpfiles` does for `/var`.

Given that Nix projects around integrating alternative init systems are reasonably young and new, I think there won't be an obvious generic way that's best for all of them yet.

However, I think you'll be on a good path of generating your desired zonefile content with `writeText`; it'll be easy to pass that generated text file to `systemd.tempfiles`, or some other mechanism provided by a different init system.

Also consider whether `/var` is really what you want. If you plan to decide to manage the zone file completely declaratively with nix, so that running programs would not mutate it, and it could be read-only, then `environment.etc` might actually be the cleaner approach.

**Comment by Kreyren** [comment]
Ideally i want it imutable by default stored in the nix-store and with mutable on demand stored in some mutable location. O.o

CC the maintainer of NixNG @MagicRB for opinion on the systemd-independendence

**Comment by MagicRB** [comment]
First off, if you're writing a module for NixOS, unless you basically want to stuff NixNG into NixOS, you'll have to depend on systemd. NixOS stands and falls on systemd. Also, yes you want to put it in `/etc` its not state, its generated with Nix and therefore should be either in `/nix/store` or `/etc`

**Comment by Kreyren** [comment]
@MagicRB i was thinking more like using `writeText` instead of `systemd.tmpfiles.rules` thinking that `writeText` is more friendly to other Inits or some handling to achive the file creation in a way that can be made compatible on NixNG and alike without changing my code

**Comment by roberth** [comment]
For a purely declarative file, the store or `/etc` is the way to do it.

If you want something imperative, you'll have to answer the question of "when" and that answer will very likely involve the init system. We don't have an abstraction for init systems at this time.

> unless you basically want to stuff NixNG into NixOS

@MagicRB The module system supports patterns that would allow common modules to be shared between the two. Something along the lines of https://github.com/NixOS/rfcs/pull/78#issuecomment-753487600, where `pureModule` is the shared module.

##### service abstraction

So splitting services into common and systemd modules _is_ already a possibility and I have already done so to simplify maintenance between NixOS and nix-darwin, which is mostly just another init system too.
Similar logic can be applied to a module that declares a generic service, so you'll have the mystical but entirely feasible [service abstraction layer](https://github.com/NixOS/nixpkgs/issues/26067).
When doing this, some experience writing modules is helpful, but I encourage anyone to play around with these ideas and tools.

**Comment by abathur** [comment]
Closing since it sounds like the question was answered and this doesn't seem to be actionable, but I'm happy to reopen if I'm mistaken.
