### ISSUE TITLE
emacsWithPackages dependency resolution is broken

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#12962]
Does anyone else have trouble with the magit package installed from melpaPackages or melpaStablePackages? When I hit `r`, the menu that pops up is incomplete: there are options, alright, but the keystrokes to choose the actual command to execute are missing.

The pull and push menus have an entry "lambda" that I've never seen before and that looks like a bug:

~~~~
Actions
 <lambda> nil
 p magit-get-push-branch
 u magit-get-upstream-branch
 e elsewhere
~~~~

**Comment by mdorman** [comment]
I don't see this in the melpaStable package from 12 hours ago or so.

**Comment by peti** [comment]
I can reproduce this error on NixOS running `master` at 1b1379a68d0abc60b61c751417dce516866247a3. Check this out:

~~~~
$ emacs
bash: emacs: command not found

$ nix-shell -p "emacsWithPackages (p: [p.melpaPackages.magit])" --run "emacs -Q"
<emacs starts up>
~~~

Now run `M-x load-library RET magit RET` and `C-u M-x magit-status`. Choose a Git repository. Now hit `F` to start `magit-pull-popup`:

~~~~
Actions
 <lambda> nil
 p magit-get-push-branch
 u magit-get-upstream-branch
 e elsewhere

Common Commands
 C-c C-c Set defaults       C-h i View popup manual    C-t Toggle this section
 C-x C-s Save defaults      ?     Popup help prefix    C-g Abort
~~~~~

Note the strange "lambda" in the menu. That doesn't look right? I don't have that error when installing magit through the normal MELPA interface; this happens only on Nix.

Cc: @ttuegel

**Comment by ttuegel** [comment]
@peti Can you confirm that you are using exactly the same version of magit installed from `emacsPackagesNg.melpaPackages` and MELPA directly? It's possible this is some upstream bug.

**Comment by mdorman** [comment]
Just an off-the-wall suggestion---could this be a version mismatch?  That is, could he be picking up the melpa version of magit, but the emacs-packages version of one of its subpackages?

@peti, if you `M-x package-list-packages`, do all the magit-related packages seem to have consistent versions?

**Comment by peti** [comment]
@mdorman, yes, I believe the installation *is* inconsistent. Nix installs magit 20160219.1702, but magit-popup 2.3.1. These two versions don't fit.

**Comment by peti** [comment]
@ttuegel, it strikes me as highly unlikely that this is an upstream bug since I have consistently managed to install magit fine with ELPA for the last 4 weeks, while the Nix installed version is consistently broken on all machines I try.

**Comment by mdorman** [comment]
@peti So clearly you're getting the melpa magit, but the magit-popup out of pkgs/applications/editors/emacs-modes/magit/default.nix.

My first solution to this problem was to simply go nuts with creating a package set that pinned the packages I wanted plus their dependencies to the repos I wanted them from.  That did start to get tedious to manage---but it had been tedious to manage within emacs itself, too.

My second solution was to delete all the cruft and submit it as #13376.  Then the melpaStable versions started to take precedence in almost all cases---which is what I wanted---and now I just override four packages.

**Comment by peti** [comment]
> you're getting the melpa magit, but the magit-popup out of pkgs/applications/editors/emacs-modes/magit/default.nix

No, that's not what is happening. It looks more like the generated MELPA package set is inconsistent. Magit pulls in the following dependencies:

    $ nix-shell -p "emacsWithPackages (p: with p.melpaPackages; [magit])" --run "emacs -Q"
    these derivations will be built:
      /nix/store/0si6w80rlj9xxcgcf1h5a9xbaaj690l2-emacs-cl-lib-0.5.drv
      /nix/store/4kbc7s8fni1ddzh88a1i0mr8q9sg5b33-emacs-dash-2.12.1.drv
      /nix/store/xxqdsw48kqx46p5wb7nfdvh125k968qj-emacs-async-1.6.drv
      /nix/store/nyap09d8y1ixwrm8dvsaiyvzva3nyxgc-emacs-with-editor-2.3.1.drv
      /nix/store/9wkxhv54rslk0a7brxkj4j2spj1658dn-emacs-git-commit-2.3.1.drv
      /nix/store/jcz53d4qf2jwaf3mjq86cz391f558x3q-emacs-magit-popup-2.3.1.drv
      /nix/store/7cvx5vn60x1803bgm6nlknkqwysh8i89-emacs-magit-20160219.1702.drv
      /nix/store/zx9r6p3k851sclhzlcmrkib6j41hz8xh-emacs-with-packages-24.5.drv
    [...]

So clearly there is a separate package `magit-popup-2.3.1` somewhere, but it's not in `pkgs/applications/editors/emacs-modes/magit`.

**Comment by peti** [comment]
This is definitely a bug in Nixpkgs. The dependencies from `melpaPackages.magit` are *not* resolved within that package set.

I've removed `magit-popup` from `pkgs/top-level/emacs-packages.nix`, and it tries to build

~~~~
  /nix/store/0ngdhl7g9wfna83dgl1qgq3dfwkd1i2j-emacs-with-editor-2.5.0.drv
  /nix/store/f5x95najzw4c5rlifa8r99z4rizv5nsg-emacs-git-commit-2.5.0.drv
  /nix/store/rc251qhqhk5s2ihsix659bmvmavg3i00-emacs-magit-popup-2.5.0.drv
  /nix/store/6lrz5glnd1q8d1j8d4m226ayvrnis26d-emacs-magit-20160219.1702.drv
  /nix/store/sa2b0z5czlxl85rznbb7mjvckavdjv6s-emacs-with-packages-24.5.drv
~~~~

which is a lot better than before but it's still not correct, because now `magit-popup` comes from `melpaStablePackages` rather than `melpaPackages`, like it should.

**Comment by ttuegel** [comment]
> it's still not correct, because now magit-popup comes from melpaStablePackages rather than melpaPackages, like it should.

That is not how dependency resolution is supposed to work. We can only have one version of every package in the dependency set, so all dependencies are resolved in the top level set. It's true that sometimes packages from `melpaPackages` will have outdated dependencies, but that's a necessary evil of working with an interpreted language (Emacs Lisp). The solution is to do this:
```
let
  customEmacsPackages = emacsPackagesNg.override (super: self: {
    inherit (self.melpaPackages) magit magit-popup;
  });
in
  customEmacsPackages.emacsWithPackages (...)
```

**Comment by peti** [comment]
I am sorry, but I disagree. When I access `magit` from `melpa-generated.nix` and that packages depends on `magit-popup` -- which exists in `melpa-generated.nix`, too -- then *that* version should be used to resolve the dependency, not a version from some other package set.

**Comment by ttuegel** [comment]
> When someone accesses magit from melpa-generated.nix and that package depends on magit-popup -- which exists in melpa-generated.nix, too -- then that version should be used to resolve the dependency

I have already explained why dependency resolution cannot work that way. I cannot do anything about Emacs' limitations.

You are right about one thing:

> not a version from some other package set

However, that is not what is going on here. There is no other package set. There is only one package set: `emacsPackagesNg`. It's true that this set is the union of packages from many sources, an evil necessitated by the fact that Emacs packages authors have no dependency discipline whatsoever. I see now it was a grave mistake to expose the hierarchical _origin_ of a set whose _nature_ is flat.

It sounds to me like you want multiple, distinct sets for MELPA, MELPA Stable, etc. Would that solve this issue for you?

**Comment by peti** [comment]
> It sounds to me like you want multiple, distinct sets for MELPA, MELPA Stable, etc. Would that solve this issue for you?

I would like to use the latest unstable version of everything, and stable versions provide merely a fallback for those attributes that don't exist in the unstable package set (assume such a case exists), i.e. the callPackage scope should be `melpaStable // melpa`.

Then it would also be nice to have a "stable" package set where unstable packages are used only if they don't have a corresponding release in stable, i.e. the callPackage scope should be `melpa // melpaStable`.

**Comment by peti** [comment]
OK, I figured it out. What I want is:

    (emacsPackagesNg.override (super: self: super.melpaPackages)).emacsWithPackages (p: with p; [magit]);

That was easy! :smile:

**Comment by ttuegel** [comment]
> I would like to use the latest unstable version of everything, and stable versions provide merely a fallback for those attributes that don't exist in the unstable package set (assume such a case exists)

The stable packages are a proper subset of the unstable packages by definition. We should probably just have an "unstable" set so that this is easier in the future.

> Then it would also be nice to have a "stable" package set where unstable packages are used only if they don't have a corresponding release in stable

That's what the default set is.
