### ISSUE TITLE
Rethink CI

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#12968]
This was spawned in response to http://lists.science.uu.nl/pipermail/nix-dev/2016-February/019494.html

**Comment by kevincox** [comment]
For an example see https://github.com/NixOS/nixpkgs/pull/12572 and https://travis-ci.org/NixOS/nixpkgs/builds/108796758. I changed three packages (marathon mesos and spark) but had to build:

```
  /nix/store/av8qaha21nmdlhri0qk7ri898iymmq62-systemd-229.drv
  /nix/store/s446q13pkzghvkxrg01mmavzd3mnsa2x-dbus-libs-1.8.20.drv
  /nix/store/c5vdra03ypx262nqw467zhzrql3plbr7-avahi-0.6.31.drv
  /nix/store/m4gy4zsm1z5h8rh93cb8s0zxl2m98j1n-libusb-1.0.19.drv
  /nix/store/8x9xv7m7hlayrfyrm03h9r8s84gv24sf-cups-2.0.4.drv
  /nix/store/527qzkrham0cz4pjbhk8fgrrni1vzx23-nss-3.22.tar.gz.drv
  /nix/store/9jy20hjrl5dyl6a1w8dpvad9pf8a1n8z-nss-cacert-3.22.drv
  /nix/store/9h1wdmi5q18k44fdbc3ixdr08rywm07i-openjdk-8u76b00.drv
  /nix/store/b9xwwi2yhr6qg07xqlmmr749l3dwdnrc-mesos-0.26.0.tar.gz.drv
 /nix/store/gxrjlxnxvdnib57r427a2sj0fn8j0gdy-apache-maven-3.3.9.drv
 /nix/store/8sq6rj59f73wspc21qylbap4hfb6mw0a-mesos-0.26.0.drv
 /nix/store/4ly39pnracrkq3hn2sybqpqar13pv4j9-marathon-0.14.1.drv
 /nix/store/am1q7jpfcws9wj2687mybvcahjlmqfdg-spark-1.4.0.drv
```

This build actually got to Mesos before being killed but most of the time was spent compiling dependencies that have already been tested.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixpkgs/pull/13006, I'll give this a try there.

**Comment by domenkozar** [comment]
We can give this a try, but I'm afraid conflicts will happen quite often. Especially if Hydra will lag behind.

**Comment by kevincox** [comment]
Why do you think conflicts will happen often? As I see it there is usually a significant delay (about a day) between my CI finishing and my PR getting merged. I doubt the couple of hours that hydra is behind will make much of a difference.

**Comment by domenkozar** [comment]
As an example, currently nixos channel is 18 days out of date. http://howoldis.herokuapp.com/

**Comment by kevincox** [comment]
Oh so you are basing off of the channel. Yeah, that could slow down and create conflicts. Is there a way to base off something else? Because IIUC all of the packages are still built, they just aren't passing other tests. Although I guess that is kinda what we want. Yeah, I don't know if there is an idea answer here.

**Comment by domenkozar** [comment]
I've posted my findings to https://github.com/NixOS/nixpkgs/issues/6652#issuecomment-184202152

**Comment by Mayeu** [comment]
About this Rethinking CI, did you all see that Travis now allow to use their [https://docs.travis-ci.com/user/migrating-from-legacy/#Caching-available-for-open-source-projects cache feature] for open source project? (I looked at the ml and related ticket but did not find anyone mentioning this).

I remember an issue or email were someone was lamenting that this feature was pay only because it could be used to store the store.

**Comment by domenkozar** [comment]
Nice!

**Comment by kevincox** [comment]
I doubt caching will help much since it is simply uploading to s3. So it should be roughly the same speed as downloading from the binary cache. The one benefit is that you might have more packages cached. 

On another note male sure that you run a gc before the cache is saves to keep it lean and effective.

**Comment by c0bw3b** [comment]
Let's close this issue now that we have disabled Travis in #31605
