### ISSUE TITLE
idutils: is marked broken but just needs gnulib update

### ISSUE THREAD

**Issue by gfrascadorio** [NixOS/nixpkgs#129658]
Package idutils is broken (and marked broken). It doesn't build because:
*  The code being fetched from savanah requires a newer version of gnulib:
** the gnulib version dated 20210702 works
* An update to gnulib requires updating idutils configure.ac to using autoconf 2.64
** fixable via substituteInPlace
* Parts of gnulib that ship inside idutils are obsolete and interfere with the latest gnulib (they need to be removing before build)
** Everything under gnulib-tests needs removal except Makefile.am

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: idutils
current version: 4.6   
desired version: 4.6   (using gnulib 20210702)

###### Notify maintainers
maintainers: no maintainers

###### Note for maintainers
Please tag this issue in your PR.

**Comment by c0bw3b** [comment]
Closing since #129904 is merged
