### ISSUE TITLE
LanguageClient-neovim languageclient binary not built

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#129629]
**Describe the bug**
`LanguageClient-neovim` (https://github.com/NixOS/nixpkgs/blob/66aa4f2d4f6c3a9b025856a4aa688ed82ff9dd54/pkgs/misc/vim-plugins/generated.nix#L2365) isn't built.

**To Reproduce**
1. Add vim and `LanguageClient-neovim` i. e. to home.nix, configure in vimrc as given in https://github.com/autozimu/LanguageClient-neovim/blob/3fb3eac6c0eeb09ddf97512f67a05c55159240f7/tests/data/vimrc
2. Build new generation of config.
3. Start vim observing messages such as `[LC] LanguageClient caught exception: 'Vim(return):E121: Undefined variable: s:job'`
4. In vim run `:echo LanguageClient#binaryPath()`
5. With path from no. 4 above run `find /nix/store/<hash>-vimplugin-LanguageClient-neovim-2021-07-08/share/vim-plugins/LanguageClient-neovim/ -name languageclient` to see there is indeed no `languageclient` binary

**Expected behavior**
No errors with config as in https://github.com/autozimu/LanguageClient-neovim/blob/3fb3eac6c0eeb09ddf97512f67a05c55159240f7/tests/data/vimrc.
Also the languageclient should signal errors in files according to filetypes added, i. e. using `rnix-lsp`.

**Screenshots**

**Additional context**
When I build LanguageClient-neovim manually (WSL 1) I get

>/nix/store/ds7r5c4z1vzrm0jw7ay712zs59p64hf7-stdenv-linux/setup: line 1312: /nix/store/02g36as1231yahcz1i9gdqfr8ynwlk05-rust-1.47.0-nightly-2020-08-26-2d8a3b918/bin/cargo: cannot execute binary file: Exec format error

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```log
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-19041-Microsoft, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(dkahlenberg): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/9ch78zqx6bwlm26ic69dpwshbjbf4jzq-nixexprs.tar.xz`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by 573** [comment]
Closing this as not-an-error.
The cause of the described was that I had a typo in my config regarding `rnix-lsp`. With that removed and using the latest rev. of nixpkgs (7c9470a0612d0e8f4988206794d1e66f1c6bf680) `/nix/store/8908m30d0y0lj9w6gfhwbxkw764n00c3-LanguageClient-neovim-bin-0.1.161/bin/languageclient` is built.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-19041-Microsoft, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 - channels(dkahlenberg): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/hgpq4rk8nlp2bvygy54vn2gyh9gn7svx-nixexprs.tar.xz`
```

**Comment by 573** [comment]
Sorry too fast, the error persists after I also added the config as in https://github.com/autozimu/LanguageClient-neovim/blob/3fb3eac6c0eeb09ddf97512f67a05c55159240f7/tests/data/vimrc to my vim config again.

**Comment by teto** [comment]
feel free to reopen
