### ISSUE TITLE
patchShebangs docs

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#129741]
**Project description**

 - [ ] A new section about the `patchShebangs` bash function.

 - [x] `dontPatchShebangs` is only partly documented. It's unclear when it runs and it should link to the new section. - [documented in fixupPhase](https://nixos.org/manual/nixpkgs/unstable/#var-stdenv-dontPatchShebangs)

**Comment by roberth** [comment]
`dontPatchShebangs` has been [documented](https://nixos.org/manual/nixpkgs/unstable/#var-stdenv-dontPatchShebangs)

The `patchShebangs` command still does not have documentation in the Nixpkgs manual.

**Comment by fricklerhandwerk** [comment]
https://github.com/NixOS/nixpkgs/pull/121015 needs approval.

**Comment by roberth** [comment]
It's a good step, but it doesn't (yet?) tell me what the options are.

**Comment by fricklerhandwerk** [comment]
Now it does.
