### ISSUE TITLE
Grafana service broken on NixOS 15.09

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#12970]
It won't start because of wrong attrpath being used in the NixOS module.

I tried untangling relevant changes from master, but failed (too complex, goPackages changes).

If we drop cherry-picking, this simple patch will do:

```patch
diff --git a/nixos/modules/services/monitoring/grafana.nix b/nixos/modules/services/monitoring/grafana.nix
index 1ab1869..08cd451 100644
--- a/nixos/modules/services/monitoring/grafana.nix
+++ b/nixos/modules/services/monitoring/grafana.nix
@@ -205,7 +205,7 @@ in {

     package = mkOption {
       description = "Package to use.";
-      default = pkgs.goPackages.grafana;
+      default = pkgs.goPackages.grafana.bin;
       type = types.package;
     };
```

The reason I'm making this issue, instead of just pushing the above patch, is that I guess we'd also like to update grafana to a stable version. NixOS 15.09 currently runs grafana-2.0.0-beta1, whereas latest is 2.6 (already on master). So I'd rather not commit directly to release-15.09 and make the branches diverge even more, unless necessary.

CC @offlinehacker for input.

**Comment by bjornfor** [comment]
I tried one more time. Now I found the right commits to cherry-pick with minimal conflicts.

**Comment by garbas** [comment]
fixed
