### ISSUE TITLE
fontconfig no longer treats system-ui as an alias of sans-serif after recent updates

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#129724]
**Describe the bug**
fontconfig does not treat system-ui as an alias of sans-serif anymore after recent updates. Previously `fc-match -s system-ui` produced the same result as `fc-match -s sans` but after recent updates, the result differed. This bug was introduced somewhere between commit 20887e4bbfdae3aed6bfa1f53ddf138ee325515e and commit 036dc0c709650e0c833822307af801f576d67273 (I tried to bisect to find the precise commit where the bug was introduced but a lot of intermediate commits were not cached so it was taking a lot of time to rebuild so I gave up). Interestingly, `fc-match -s "system ui"` (without the dash) still produces the same result as `fc-match -s sans` even though it is aliased to `system-ui`: (from the file `/etc/fonts/fonts.conf`)

```
<!--
  Accept alternate 'system ui' spelling, replacing it with 'system-ui'
-->
	<match target="pattern">
		<test qual="any" name="family" target="default" ignore-blanks="false" compare="eq">
			<string>system ui</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>system-ui</string>
		</edit>
	</match>
```

Also, I feel like https://github.com/NixOS/nixpkgs/issues/129711 is caused by this bug.

**To Reproduce**
1. Install some fonts
2. Rebuild your system against 20887e4bbfdae3aed6bfa1f53ddf138ee325515e
3. Run `fc-match -s system-ui`
4. Rebuild your system against 036dc0c709650e0c833822307af801f576d67273
5. Run `fc-match -s system-ui`

**Expected behavior**
`fc-match -s system-ui` should product the same result as `fc-match -s sans`

**Additional context**
This is the fontconfig settings I used:
```nix
  {
    fonts = {
      enableDefaultFonts = lib.mkForce false;
      fontconfig = {
        defaultFonts = {
          sansSerif = lib.mkBefore [ "Roboto" "Noto Sans CJK SC" ];
          serif = lib.mkBefore [ "Noto Serif" ];
          monospace = lib.mkBefore [ "Consolas" ];
          emoji = lib.mkBefore [ "Blobmoji" "Noto Color Emoji" ];
        };
      };
      fonts = with pkgs; [
        emacs-all-the-icons-fonts
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji-blob-bin
        noto-fonts-extra
        iosevka
        sarasa-gothic
        roboto
      ];
    };
  }
```

**Notify maintainers**
@NixOS/freedesktop

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.14, NixOS, 21.11.20210704.20887e4 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `""`
 - nixpkgs: `/nix/store/rplqpacaa11i2wlpjbjz71g8vfynnvb3-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by andresilva** [comment]
Fixed with #129675.

**Comment by das-g** [comment]
> **Expected behavior**
> `fc-match -s system-ui` should product the same result as `fc-match -s sans`

That seems like something that could be automatically tested.

**Comment by Artturin** [comment]
https://nixpk.gs/pr-tracker.html?pr=129675
is now in nixos-unstable
