### ISSUE TITLE
fwup needs update to version 1.8.4

### ISSUE THREAD

**Issue by erauer** [NixOS/nixpkgs#129709]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: fwup

current version: 1.8.3
desired version: 1.8.4

###### Notify maintainers

maintainers: @georgewhewell

###### Note for maintainers

Please tag this issue in your PR.

**Comment by fabaff** [comment]
@erauer, could you please give #129752 a try?

**Comment by erauer** [comment]
@fabaff  I'm new to nix but I was able to get the following to work on Ubuntu 20.04

```
$ nix-channel --add https://github.com/fabaff/nixpkgs/archive/bump-fwup.tar.gz fwup
$ nix-channel --update
$ nix-env --install fwup-1.8.4`
`

Thanks for the quick turnaround
