### ISSUE TITLE
buildGoModule might produce different checksum depending on the platform (linux <> darwin)

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#129730]
**Describe the bug**

Discovered in https://github.com/NixOS/nixpkgs/pull/129649/files#r666294752

To investigate this we would need someone with both Linux and macOS to provide the module derivations for both.

**Comment by zowoq** [comment]
```
diff -rq /nix/store/9d1rp6pmfaa1sxj5ni40jd5xwwzwdhfc-telegraf-1.19.1-go-modules /nix/store/izq65v2jbqjfb29289hcpkwfkwb8yfqc-telegraf-1.19.1-go-modules
Only in /nix/store/izq65v2jbqjfb29289hcpkwfkwb8yfqc-telegraf-1.19.1-go-modules/github.com/Microsoft: ApplicationInsights-Go
Only in /nix/store/9d1rp6pmfaa1sxj5ni40jd5xwwzwdhfc-telegraf-1.19.1-go-modules/github.com: microsoft~nix~case~hack~1
```
___
https://github.com/NixOS/nixpkgs/blob/3f92843767e8e1b83b2401a9ccc44f8debc6919d/pkgs/tools/misc/opentelemetry-collector/default.nix#L18-L20
```
diff -rq /nix/store/x3mqwlqzrpgbnczsy8ca02ynnc1nsijv-opentelemetry-collector-0.26.0-go-modules /nix/store/naii9fxpfcr2kcj845g3b7hp9ghh6xbm-opentelemetry-collector-0.26.0-go-modules
Only in /nix/store/x3mqwlqzrpgbnczsy8ca02ynnc1nsijv-opentelemetry-collector-0.26.0-go-modules/github.com/Microsoft: ApplicationInsights-Go
Only in /nix/store/naii9fxpfcr2kcj845g3b7hp9ghh6xbm-opentelemetry-collector-0.26.0-go-modules/github.com: microsoft~nix~case~hack~1
```

**Comment by Mic92** [comment]
> ```
> diff -rq /nix/store/9d1rp6pmfaa1sxj5ni40jd5xwwzwdhfc-telegraf-1.19.1-go-modules /nix/store/izq65v2jbqjfb29289hcpkwfkwb8yfqc-telegraf-1.19.1-go-modules
> Only in /nix/store/izq65v2jbqjfb29289hcpkwfkwb8yfqc-telegraf-1.19.1-go-modules/github.com/Microsoft: ApplicationInsights-Go
> Only in /nix/store/9d1rp6pmfaa1sxj5ni40jd5xwwzwdhfc-telegraf-1.19.1-go-modules/github.com: microsoft~nix~case~hack~1
> ```
> 
> https://github.com/NixOS/nixpkgs/blob/3f92843767e8e1b83b2401a9ccc44f8debc6919d/pkgs/tools/misc/opentelemetry-collector/default.nix#L18-L20
> 
> ```
> diff -rq /nix/store/x3mqwlqzrpgbnczsy8ca02ynnc1nsijv-opentelemetry-collector-0.26.0-go-modules /nix/store/naii9fxpfcr2kcj845g3b7hp9ghh6xbm-opentelemetry-collector-0.26.0-go-modules
> Only in /nix/store/x3mqwlqzrpgbnczsy8ca02ynnc1nsijv-opentelemetry-collector-0.26.0-go-modules/github.com/Microsoft: ApplicationInsights-Go
> Only in /nix/store/naii9fxpfcr2kcj845g3b7hp9ghh6xbm-opentelemetry-collector-0.26.0-go-modules/github.com: microsoft~nix~case~hack~1
> ```

I don't really understand the diff. Are there different files in both?

**Comment by zowoq** [comment]
Seems to be a case-insensitive conflict with `github.com/Microsoft` and `github.com/microsoft`.

**Comment by Mic92** [comment]
Could we normalize this in our code for buildGoModule?

**Comment by zowoq** [comment]
I'd be a bit concerned that any normalization we do ourselves may end up causing more problems with other workarounds or the `go` 1.17 vendor changes, especially if we end up with 1.17 as default on linux and keeping 1.16 for darwin.

I think I've got a fix that just uses `go` itself, I'll open a PR in the next couple of days.

**Comment by zowoq** [comment]
Draft fix: https://github.com/NixOS/nixpkgs/pull/131452

**Comment by zowoq** [comment]
Should be resolved by https://github.com/NixOS/nixpkgs/pull/131452
