### ISSUE TITLE
kodi 19.1 breaks HDMI audio output

### ISSUE THREAD

**Issue by etu** [NixOS/nixpkgs#129794]
**Describe the bug**
When my media computer got the upgrade of kodi to 19.1 it broke the HDMI audio output which was available before this update.

I have considered if it was any kernel upgrade because I went from 5.11 to 5.12 at the same time. I tried to downgrade to 5.10 and it still didn't work. Then I upgraded to 5.13 which still didn't work. Then I pulled in 5.11 from an old channel which still didn't work.

I do not run pulseaudio or pipewire on this machine, and it's in X11 (at least while on 19.0, maybe that's a difference I haven't spotted).

Currently the system is running on an up-to-date nixos-unstable channel with a pinned channel that provides a kodi 19.0 version to just have it working for now.

Any ideas on what to look into?

My system is on 87807e64a5e, but I pin it to an older commit in my config file: https://github.com/etu/nixconfig/commit/c33a85429e81cdaaf2f505c7ace9b8b9a7024dde

**Expected behavior**
I expect to be able to select HDMI outputs from the settings > system > audio settings

**Notify maintainers**
ping @NixOS/kodi 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result. - system: `"x86_64-linux"`

 - host os: `Linux 5.13.0, NixOS, 21.11pre301044.87807e64a5e (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301044.87807e64a5e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
Do you have multiple audio outputs? Long ago on my HTPC I disabled the non HDMI audio (because steam games always choose the wrong output) and 19.1 is working fine over HDMI with that. Maybe `kodi` has selected the wrong audio output?

What do the settings in `kodi` show for selected audio device and what are all the options available?

**Comment by peterhoeg** [comment]
I'm using 19.1 on 21.05 over HDMI without problems. No pipewire/pulse - boots straight to kodi.

**Comment by etu** [comment]
This issue seems to have gone away for me with another channel update...
