### ISSUE TITLE
 Ability to change permissions of user home directory

### ISSUE THREAD

**Issue by Armoken** [NixOS/nixpkgs#129885]
I am trying to setup minidlna server which run from minidlna user and can't read directories with media content from my user's home directory due to 700 permissions on it.

I think that option **users.user.homeDirectoryPermissions** wich require integer or string chmod value will be enough comfortable.

**Comment by aanderse** [comment]
If you set `createHome = false;` and permissions won't be changed anymore.

**Comment by Armoken** [comment]
@aanderse But will not that stop home-manager from creating configuration files of my user in right places?

**Comment by aanderse** [comment]
@Armoken I haven't ever used `home-manager`, but I can't see any reason why it would prevent that. If your home directory already exists you shouldn't **need** `createHome = true` anymore. Please let me know if this workaround helps you or not.

**Comment by Armoken** [comment]
@aanderse It works, but I am trying to understand what will happens, when I will install my configuration on the clean disk. Because **createHome = false** is looks like a hack.

**Comment by aanderse** [comment]
Yes, as mentioned this is a workaround to solve your problem immediately.

To permanently solve your problem we could create a new option as you mentioned, or you could add something like this to your configuration:
```
# create directory and ensure ownership+permissions on every system activation
systemd.tmpfiles.rules = [
  "/home/armoken 0755 armoken users"
];
```
Or add `mkdir` to the system activation scripts... Several options here.

**Comment by Armoken** [comment]
@aanderse thank you. I will use your solution that used systemd.tmpfiles, and will wait for a new option, which I think will be more obvious and comfortable for a new users;)

**Comment by bb2020** [comment]
Exposing home directory is dangerous and I think there shouldn't be an easy way to change permissions. By the way you can use `bindfs` to mount your media directory to somewhere else.

```
fileSystems."/opt/dlna" = {
  device = "/home/user/Desktop/media";
  fsType = "fuse.bindfs";
  options = [ "ro" "perms=0000:a+rX" ];
};
```

**Comment by ptman** [comment]
systemd.tmpfiles.rules works

**Comment by SuperSamus** [comment]
Doesn't [users.users.\<name\>.homeMode](https://search.nixos.org/options?show=users.users.%3Cname%3E.homeMode) do that?

**Comment by aanderse** [comment]
@SuperSamus yes, this issue was created before that option existed. We can close this now. Thanks.

**Comment by SuperSamus** [comment]
@aanderse #148013 should be closed too.
