### ISSUE TITLE
linux-firmware-nonfree does not contain the ipw2200-firmware

### ISSUE THREAD

**Issue by lukasepple** [NixOS/nixpkgs#12980]
I tried to `networking.enableIntel2200BGFirmware = true;` in order to make my Intel 2200BG work. However that does not work:

```
[  747.881937] libipw: 802.11 data/management/control stack, git-1.1.13
[  747.881940] libipw: Copyright (C) 2004-2005 Intel Corporation <jketreno@linux.intel.com>
[  747.886899] ipw2200: Intel(R) PRO/Wireless 2200/2915 Network Driver, 1.2.2km
[  747.886905] ipw2200: Copyright(c) 2003-2006 Intel Corporation
[  747.887316] ipw2200: Detected Intel PRO/Wireless 2200BG Network Connection
[  747.887400] ipw2200 0000:04:02.0: Direct firmware load for ipw2200-bss.fw failed with error -2
[  747.887405] ipw2200: ipw2200-bss.fw request_firmware failed: Reason -2
[  747.887408] ipw2200: Unable to load firmware: -2
[  747.887507] ipw2200: probe of 0000:04:02.0 failed with error -5
```

So this means that the file `ipw2200-bss.fw` is missing. However `enableIntel2200BGFirmware` just sets `hardware.enableAllFirmware` to true which just adds the package `firmware-linux-nonfree` to `hardware.firmware`. However this package is not containing the file in question.

My first theory was that the firmware-package was too old but this code did not fix it:

```
  hardware.firmware = let myfirmware = pkgs.firmwareLinuxNonfree.overrideDerivation
     (old: {
       name = "myfirmware";
       src = pkgs.fetchFromGitHub {
         owner = "wkennington";
         repo = "linux-firmware";
         rev = "2016-01-26";
         sha256="07hv4kgbsxndhm1va6k6scy083886aap3naq1l4jdz7dnph4ir02";
       };
     }); in [ myfirmware ];
```

Am I missing something or is this a bug? If the latter is true, a equivalent of [firmware-ipw2x00](https://packages.debian.org/sid/firmware-ipw2x00) should be added.

`lspci` shows that I have a working card and I could connect to the network using an archlinux live system.

```
[…]
04:02.0 Network controller: Intel Corporation PRO/Wireless 2200BG [Calexico2] Network Connection (rev 05)
```

**Comment by heydojo** [comment]
I think you want http://ipw2200.sourceforge.net/firmware.php firmware v3.1.

It looks like the firmware was depreciated or never made it into the firmware tree and/or no one has used enableIntel2200BGFirmware for a very long time.
https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/tree/

Do you mind me asking the date of manufacturer of your machine? I'm guessing it's from last century?

**Comment by lukasepple** [comment]
Well the IBM T43 was released in 2005. I guess that it is not unlikely that people will try to install NixOS on older ThinkPads :)

So I guess we'd need to add an nixexpr for the ipw2200 firmware package?

**Comment by heydojo** [comment]
>
Well the IBM T43 was released in 2005.

You sir have an antique on your hands. They don't build them like that any more. :)

>
So I guess we'd need to add an nixexpr for the ipw2200 firmware package?

Yes. That is correct.

Changing :
https://gist.github.com/heydojo/89526c6dacca6ed61236
then creating os-specific/linux/firmware/intel2200BGFirmware/default.nix
https://gist.github.com/heydojo/942a4790ac6baaf79422
and adding:
```
intel2200BGFirmware = callPackage ../os-specific/linux/firmware/intel2200BGFirmware { };
```
to pkgs/top-level/all-packages.nix in the ### OS-SPECIFIC section may do it.
Let me know how you get on :+1:

**Comment by lukasepple** [comment]
Thank you for your suggestions, I will look into it!

**Comment by lukasepple** [comment]
One Question: Should I change `enableAllFirmware` as well to include the intel2200BG Firmware?

**Comment by lukasepple** [comment]
I opened a PR: https://github.com/NixOS/nixpkgs/pull/12992

**Comment by vcunat** [comment]
Perhaps /cc @wkennington to know there isn't really all firmware in his repo.

**Comment by lukasepple** [comment]
Does it make sense to add the driver to firmware-linux-nonfree, @wkennington?

**Comment by vcunat** [comment]
I consider this issue resolved, as the PR was merged.

**Comment by kvtb** [comment]
`ipw2100-1.3.fw` is also missing (Thinkpad T41)

It was packages once https://github.com/NixOS/nixpkgs/commit/66e7ed0a89902b0d0614c1e687cc4bf0fd366f75 but then disappear from nixpkgs during some refactoring.
