### ISSUE TITLE
ddccontrol service not created

### ISSUE THREAD

**Issue by jyp** [NixOS/nixpkgs#129966]
**Describe the bug**

Recent versions of ddccontrol require a service to be started. This service is not implemented in nixos. 

**To Reproduce**

```
$sudo ddccontrol -p
ddccontrol version 0.5.2
Copyright 2004-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
Copyright 2004-2006 Nicolas Boichat (nicolas@boichat.ch)
This program comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of this program under the terms of the GNU General Public License.

D-Bus connection failed with error: Error calling StartServiceByName for ddccontrol.DDCControl: Unit ddccontrol.service not found..
Failed to open D-Bus proxy, try with DDCCONTROL_NO_DBUS=1.
```

**Expected behavior**

ddccontrol should probe i2c devices for known devices.

**Additional context**

The same bug was reported and fixed in fedora: 

https://bugzilla.redhat.com/show_bug.cgi?id=1917264

More info:

https://github.com/ddccontrol/ddccontrol/issues/36

**Notify maintainers**

@pakhfn [maintainer]

@jtojnar [upgraded from 0.4.4 to 0.5.1]

@r-ryantm [upgraded to 0.5.2]

**Metadata**

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.43, NixOS, 21.05.1076.bad3ccd099e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(jyp): `"stable-21.05.1353.c06613c25df"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
This was fixed in #129684.

**Comment by veprbl** [comment]
I guess, this still needs a backport to 21.05

**Comment by Artturin** [comment]
#130891

**Comment by veprbl** [comment]
> #130891

Merged
