### ISSUE TITLE
qtile: version bump attempt to 0.10.4 failed

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#12994]
qtile had a release about a month and it contains some bugfixes regarding full-screen that I'm interested in.

I had no luck to simply up the version as the in-tree patches fail like so:

```
applying patch /nix/store/rxcrdn5i5kb90kndwmfzx5kxb55879lc-0002-Restore-PATH-and-PYTHONPATH.patch
patching file bin/qtile
Hunk #1 succeeded at 123 (offset -8 lines).
patching file bin/qtile-run
patching file bin/qtile-session
patching file libqtile/utils.py
Hunk #1 FAILED at 208.
1 out of 1 hunk FAILED -- saving rejects to file libqtile/utils.py.rej
builder for ‘/nix/store/4w2bpgymxi36q1g1f1zri7kpavp7pr64-python2.7-qtile-0.10.4.drv’ failed with exit code 1
```

A quick glimpse at the patch makes we think we still need it, so I'd like to give this one to the maintainer.

/cc @kamilchm

**Comment by kamilchm** [comment]
I will look on it tommorow.

/cc @avnik

**Comment by kamilchm** [comment]
PR https://github.com/NixOS/nixpkgs/pull/13005

**Comment by kamilchm** [comment]
I'm waiting for travis build for https://github.com/NixOS/nixpkgs/pull/13007
But I use it for 3 hours without issues.

**Comment by zimbatm** [comment]
merged
