### ISSUE TITLE
vscodium icon

### ISSUE THREAD

**Issue by John-Rodriguez-Git** [NixOS/nixpkgs#129955]
**Describe the bug**
No Icon is shown for VsCodium in Cinnamon. In KDE Plasma there is only the correct Icon in the Task bar.

**To Reproduce**
In my bash history I have both:
1. nix-env -iA nixos.vscodium-fhs
2. sudo nix-env -iA nixos.vscodium-fhs
3. ...

**Expected behavior**
I expect that the Icon, that is shown in the KDE Panel, is shown everywhere, at the appropiate places, instead of a placeholder or nothing. The icon shown in the Plasma Panel is the correct one that is also used here: https://github.com/VSCodium 

**Screenshots**
KDE Plasma:
![Screenshot_20210711_190519](https://user-images.githubusercontent.com/87267596/125204106-c8a45600-e27b-11eb-957a-acdcc35b629e.png)

In the Open with dialog:
![Screenshot_20210711_191301](https://user-images.githubusercontent.com/87267596/125204152-15882c80-e27c-11eb-9801-5b4415b254cc.png)
![Screenshot_20210711_191400](https://user-images.githubusercontent.com/87267596/125204171-305aa100-e27c-11eb-8290-86491b7e6675.png)
Hmm, it appears multiple times in this dialog.

Cinnamon:
![2021-07-11_20-21](https://user-images.githubusercontent.com/87267596/125206115-c515cc80-e285-11eb-8101-b83920ef374a.png)

**Additional context**
Here is the Icon for the .desktop file defined: https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/applications/editors/vscode/generic.nix#L33

**Notify maintainers**
@Synthetica9 
@turion 
Thanks for packaging vscodium!

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1408.9376bf7b342 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05.1408.9376bf7b342"`
 - channels(linux): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: vscodium-fhs
```

**Comment by turion** [comment]
Can you reproduce with `vscodium` instead of `vscodium-fhs`? (See https://search.nixos.org/packages?channel=21.05&show=vscodium&from=0&size=50&sort=relevance&query=codium)

I have `vscodium` installed on KDE and cannot reproduce the bug.

**Comment by John-Rodriguez-Git** [comment]
I tried vscodium on the Live Installer system. The Icon was there, also in the menu. I tried to remove vscodium to try out vscodium-fhs. But I didnt managed to remove the package and I couldnt install both versions, since both wanted to place a codium.desktop file in some directory. I will test out vscodium-fhs on the live system tomorrow.

**Comment by John-Rodriguez-Git** [comment]
In KDE 5 Plasma there is also the correct icon shown on alt tab for both codium and codium-fhs. On my Machine, aswell as on the Live System. 
Installing codium-fhs in a Live-system:
- also no icon shown in the menu in cinnamon & KDE
- in cinnamon:
     - no icon in Taskbar and on the alt tab overview of the open applications

**Comment by John-Rodriguez-Git** [comment]
still - after many updates there is no icon shown.

**Comment by John-Rodriguez-Git** [comment]
Thanks, it works :D
