### ISSUE TITLE
bash_kernel 0.7.2: Jupyter kernel fails to run.

### ISSUE THREAD

**Issue by lambda-11235** [NixOS/nixpkgs#129906]
**Describe the bug**
When running a Jupyter bash notebook the kernel fails with
```
[I 20:37:18.473 NotebookApp] Kernel started: 1403ac24-1d89-49c8-bb6b-8a77ff21e0ee, name: bash
/nix/store/zv167zw7gwr9h0gpkfcikdfqnscrd0q6-python3-3.8.9/bin/python3.8: No module named bash_kernel
```

Note that when using the `python3.8` interpreter `import bash_kernel` work without error.

**To Reproduce**
1. Install python3 packages notebook and bash_kernel.
2. Run `jupyter-notebook` and try to launch a bash notebook.

**Expected behavior**
Jupyter should be able to import the bash_kernel module.

**Notify maintainers**
@zimbatm

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.37, NixOS, 21.05.1408.9376bf7b342 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1408.9376bf7b342"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by Artturin** [comment]
you need to do overrides and stuff if you search `jupyter nixos` you can find info

**Comment by lambda-11235** [comment]
@Artturin Thanks! Unfortunately DuckDuckGo hasn't indexed that page, so I completely missed it when searching the documentation.

**Comment by Artturin** [comment]
https://github.com/tweag/jupyterWith

**Comment by lambda-11235** [comment]
https://discourse.nixos.org/t/jupyter-notebook-with-batteries/1839/17
