### ISSUE TITLE
Rebar3 not bulding on mac M1 due to failed checks

### ISSUE THREAD

**Issue by jaen** [NixOS/nixpkgs#130012]
**Describe the bug**
Trying to install `beam.packages.erlangR23.rebar3` tries to compile the package (instead of fetching from binary cache) and the compilation fails on some tests from `rebar_file_utils_SUITE`.

For comparison:
  * on an M1 machine `nix-build -A beam.packages.erlangR24.rebar3` works, pulling from the binary cache,
  * on a NixOS machine `nix-build -A beam.packages.erlangR23.rebar3` works, even though it also compiles from source.
  * on a NixOS machine `nix-build -A beam.packages.erlangR24.rebar3` works, pulling from the binary cache.

**To Reproduce**
1. checkout nixpkgs @ `a164e1d0a17549cc4c238cfe9c32a0bac97b24e1` on an M1 machine,
2. try to build rebar3 with `nix-build -A beam.packages.erlangR23.rebar3`,
3. fail. The exact failures are:
	  ```
	  %%% rebar_file_utils_SUITE: ....
	  %%% rebar_file_utils_SUITE ==> reset_dir.reset_nonexistent_dir: FAILED
	  %%% rebar_file_utils_SUITE ==> {{badmatch,{error,eacces}},
	   [{rebar_file_utils_SUITE,reset_nonexistent_dir,1,
	                            [{file,"/private/tmp/nix-build-rebar3-3.16.1.drv-7/source/test/rebar_file_utils_SUITE.erl"},
	                             {line,101}]},
	    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1784}]},
	    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1293}]},
	    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1225}]}]}
	  
	  %%% rebar_file_utils_SUITE ==> reset_dir.reset_empty_dir: FAILED
	  %%% rebar_file_utils_SUITE ==>
	  Failure/Error: ?assert(filelib : is_dir ( TmpDir ))
	    expected: true
	         got: false
	        line: 109
	  
	  %%% rebar_file_utils_SUITE ==> reset_dir.reset_dir: FAILED
	  %%% rebar_file_utils_SUITE ==>
	  Failure/Error: ?assert(filelib : is_dir ( TmpDir ))
	    expected: true
	         got: false
	        line: 118
	  ..........
	  %%% rebar_file_utils_SUITE ==> resolve_link: FAILED
	  %%% rebar_file_utils_SUITE ==> {{badmatch,{error,eacces}},
	   [{rebar_file_utils_SUITE,resolve_link,1,
	                            [{file,"/private/tmp/nix-build-rebar3-3.16.1.drv-7/source/test/rebar_file_utils_SUITE.erl"},
	                             {line,193}]},
	    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1784}]},
	    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1293}]},
	    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1225}]}]}
	  ..
	  ```

**Expected behaviour**
The `beam.packages.erlangR23.rebar3` package should compile and preferably just fetch itself from the binary cache.

**Additional context**
As a background – I was trying to open a nix shell in a flakeified project that used to work on an M1 machine, but for some reason, it wanted to compile the world – gcc and all (and failed on some package). While writing this bug report it turned out that `awscli2` was the cause, which was added and apparently doesn't work on that commit on M1.

Anyway, while trying to fix this, at some point I tried to update nipkxgs to see if it will work with newer packages. When nix tried to compile `beam.packages.erlangR23.rebar3` (does it not have binary cache as well? If so, why?), it failed on some checks. I tried to disable them with overrides but was unable to for some reason (the tests built anyway). So at this point, I'm kinda stumped on what to to do to get this to work, other than reporting a bug.

**Notify maintainers**
FYI BEAM maintainers: @ankhers, @Br1ght0ne, @DianaOlympos,@gleber, @happysalada, @yurrriq 
(sorry if that's too much of a noise, was just following the template)

**Metadata**
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(jaen): `"darwin"`
 - channels(root): `"nixpkgs-21.11pre293818.afdb5675a18"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - beam.packages.erlangR23.rebar3
# a list of nixos modules affected by the problem
module:
```

**Comment by happysalada** [comment]
Thank you for filing the bug!

Given the limited resources of the machines that build the binary cache, I don't think we can expect at this point to have different versions of packages in the binary cache. In this case the "default" version of erlang is 24 that is why rebar3 is available in the cache for that version.
I think in a perfect world, we can have both major versions of erlang building packages when there was a recent transition.

Having had a quick look at the tests, it looks to be some file access problem
https://github.com/erlang/rebar3/blob/master/test/rebar_file_utils_SUITE.erl#L101

I'm sure there could be a way to fix those tests by overriding some of the test phase attributes. We can also potentially disable the tests completely for darwin Aarch64.

Out of curiosity, are you using this on a project that has not done the transition to R24 yet? Is that planned in the future or the project is too big and it won't happen? (just out of curiosity, feel free to ignore those questions if you feel they are too much).

**Comment by jaen** [comment]
@happysalada thanks for the quick response!

I can understand the resource constraints issue, but doesn't that mean we can't be sure that anything other than the current OTP version works?

I actually tried just disabling the checks, but neither trying to install `beam.packages.erlangR23.rebar3.overrideAttrs (old: { doCheck = false; })`, nor trying to make an overlay like:
```nix
(final: prev: { beam = (prev.beam // { packages = (prev.beam.packages // { erlangR23 = (prev.beam.packages.erlangR23 // { rebar3 = (prev.beam.packages.erlangR23.rebar3.overrideAttrs (old: { doCheck = false; })); }); }); }); })
```
seemed to work (I also tried overriding the `checkPhase` with an empty script, also to no effect). I'm certainly not a nix pro, so I might've done something incorrectly – I remember QT requiring some scoped package shenanigans, maybe Erlang-based packages also need some specific way of overriding I'm not aware of? I'm also not sure what other attributes you could mean with:
> overriding some of the test phase attributes
I could try and see what makes it work on M1 if I get some pointers.

As for satisfying your curiosity – yeah, I'm trying to see if nix could be a useful tool for providing reproducible dev environments where I work. As far as I know, migrating from 23 -> 24 on applications that are behind is not on the radar. Probably not that surprising given one of them has almost 600k lines of actual Elixir code. Not being able to easily pin a certain version of a language/tool is kind of unfortunate if you are trying to bolt nix onto some project (and not Erlang-specific either, I have the same issue with Ruby suddenly bumping from 2.7.3 to 2.7.4).

**Comment by happysalada** [comment]
Out of curiosity I tried to build R23.rebar3 with my darwin non M1 system, and the tests all passed. So I guess it is an M1 specific issue.

Regarding overriding the test attribute, I was thinking of something more "radical" like
inside the derivation itself have something like
`doCheck = ! ( stdenv.isDarwin && stdenv.isAarch64);`
If you are interested in making a PR like that, I think we can merge it relatively fast.

Regarding overriding particular attributes, I meant something a little complicated that would potentially require some work.
- Try to get a nix-shell like suggested here by jonringer https://discourse.nixos.org/t/debug-a-failed-derivation-with-breakpointhook-and-cntr/8669/2, add strace to it
- Build and install the binary.
- Check what files exactly are being "deleted" and failing. My hunch here is that in a lot of derivations you need to define specific temp directories or environment variable that the system relies on to know which file to delete when it talks about tmp. It might be just a matter of `tmpfile=$(mktemp)` or something like that before the checkPhase runs.

I'm not advising one way or another. 2 will take more time but can potentially result in more fixes related to M1.
1 will definitely be quicker, assuming that if it builds it's probably okay.

**Comment by jaen** [comment]
How about disabling just the failing tests, it would probably by useful to tell if something more starts breaking? While Hydra apparently doesn't run that, we could at least tell if something more broke when installing the package.
If that is acceptable, I can send a PR in a moment. If not, then I can send one for disabling all the tests.

I could look into fixing that properly later, if I have some time, since I usually work on Linux it's not that pressing of an issue.

**Comment by jaen** [comment]
The change looks like this – https://github.com/jaen/nixpkgs/commit/35dbc1761b740e36ce442bc18306d07038801aa2. If you're happy with, I'll open a PR.

**Comment by DianaOlympos** [comment]
could someone with a M1 try to build rebar from source without nix also ? So that we can fill a bug upstream if there is one ?

**Comment by jaen** [comment]
@happysalada – here's the PR: https://github.com/NixOS/nixpkgs/pull/130074. I have ran the build a couple of times already and no other tests failed, so at the very least they are not _that_ flaky.

@DianaOlympos – if that's not much of an effort, then I can try (at least rebar3 doesn't make it sound like a big deal). I assume this means I would have to install Erlang via some other means than Nix (homebrew, asdf), right?

**Comment by DianaOlympos** [comment]
No erlang installed via nix should be ok, but just build rebar from source in its git repo. You can use nix for the setup, just not build rebar3 by using a nix formula, like most people would outside the nix ecosystem

**Comment by jaen** [comment]
Ok, so running `./bootstrap && ./rebar3 ct` seems to fail the same way when ran in `nix shell nixpkgs#beam.packages.erlangR23.erlang`. I guess that can be reported to the upstream then?

**Comment by DianaOlympos** [comment]
yep seems like it :) enjoy your issue :D

**Comment by jaen** [comment]
Turns out it was actually a bit of a PEBKAC – the tests were failing because some temporary files they created escaped the designated temporary directory (rebar3 doesn't seem to recognise `TMPDIR` envvar) and I didn't realise that was the case. 

Upstream seems conducive to teaching `rebar_file_utils:system_tmpdir/1` about `TMPDIR`, so I'm not sure how much of value this PR brings.

**Comment by jaen** [comment]
Okay, the fix is merged upstream – https://github.com/erlang/rebar3/commit/11055384dbd5bf7d181bca83a33b0e100275ff21. When I'm building rebar3 with this commit, it no longer leaks files into `/tmp`. Now we just have to wait for a release.

Not sure what to do about the PR in that regard, though. Depending on the release cadence it could be still useful to skip those tests in mean time, maybe?

**Comment by happysalada** [comment]
I would say yes! Let's just add a comment that references that the issue is fixed
something like
`# remove when https://github.com/erlang/rebar3/commit/11055384dbd5bf7d181bca83a33b0e100275ff21 is released`
(feel free to edit the comment as you see fit. I would like a reference so that we don't forget to remove the patch.
But yes, I think it's valuable until the fixe lands.

**Comment by jaen** [comment]
Rebar was since updated to a version with the fix:
https://github.com/NixOS/nixpkgs/pull/137306
