### ISSUE TITLE
Package Request: nanodbc

### ISSUE THREAD

**Issue by nagy** [NixOS/nixpkgs#130134]
**Project description**
A small C++ wrapper for the native C ODBC API.
This is needed for `irods` version bump to 4.2.9 in the context of #129416 .

**Metadata**

* homepage URL: https://github.com/nanodbc/nanodbc
* source URL: https://github.com/nanodbc/nanodbc
* license: mit
* platforms: unix

**Comment by bzizou** [comment]
Checking that right now
