### ISSUE TITLE
Neovim missing libstdc++.so.6

### ISSUE THREAD

**Issue by yourfavouriteuncle** [NixOS/nixpkgs#130152]
**Describe the bug**
I'm on nixos unstable and I installed neovim 0.5 from the repository

**To Reproduce**
1. install neovim 0.5
2. create a profile with telescope in it
3. start a telescope function

**Expected behavior**
No error message

**Additional context**
```
Error executing vim.schedule lua callback: Failed to load parser: uv_dlopen: libstdc++.so.6: cannot open shared object f
ile: No such file or directory
```

Something similar happens when I edit a file:

```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua Failed to load parser: uv_dlopen: libstdc++.so.6: cannot open shared object file: No such fil
e or directory
```

**Notify maintainers**
@Ma27 @rvolosatovs @manveru  

**Metadata**
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.47, NixOS, 21.11pre301044.87807e64a5e (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301044.87807e64a5e, home-manager"`
 - channels(asdf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: neovim
# a list of nixos modules affected by the problem
module: 
```

**Comment by yourfavouriteuncle** [comment]
I guess something has to have had happened during compilation of the treesitter parsers because after cleaning out the packer folder and recompiling everything, all works well

**Comment by jmederosalvarado** [comment]
Hi @yourfavouriteuncle. I'm facing the same problem here. I've tried removing the contents of `.local/share/nvim` but the issue persists. Could you share a more detailed explanation of what you did to get it fixed. Thanks in advance.

**Comment by NomisIV** [comment]
I have found a horrible workaround for this:

`LD_LIBRARY_PATH=$(ls -d /nix/store/*gcc-10.3.0-lib)/lib nvim`

**Comment by lobre** [comment]
I am also facing this issue. Can we please reopen?

**Comment by NomisIV** [comment]
Before, I only tried removing some of the directories from `~/.local/share/nvim`, which didn't work. But now when I did like @lobre suggested and deleted (or moved, in my case) the entire folder, everything seems to work like it should after reinstalling packer.nvim and all the plugins and language servers again.

**Comment by duckpuppy** [comment]
I'm seeing this problem, and removing `~/.local/share/nvim` and re-installing treesitter parsers does not fix the problem. I'm not on NixOS, but using nixpkgs unstable on Ubuntu 11. Does anybody have any other fixes? Testing a compiled parser with ex. `ldd ~/.local/share/nvim/site/parser/markdown.so` shows:

```
        linux-vdso.so.1 (0x00007ffe107f1000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4a91a6a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a918a5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a91761000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4a91d04000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4a91747000)
```

All those paths are valid, but I still see issues with using any parser linked against `libstdc++.so.6` and ONLY parsers linked with `libstdc++.so.6`.

I tried just using `nvim-treesitter.withPlugins (plugins: pkgs.tree-sitter.allGrammars)`, but there's query incompatibilities with vim.treesitter right now, specifically with markdown.

**Comment by ABitMoreDepth** [comment]
I'm in a similar position to @duckpuppy , running neovim via home-manager on Ubuntu 20.04.

**Comment by joaomsa** [comment]
Seeing this problem since updating to neovim 7.0

**Comment by mraxilus** [comment]
> Seeing this problem since updating to neovim 7.0

Same here, did you find any workaround?
