### ISSUE TITLE
[SOLVED] mirroredBoots with / on tmpfs build error:  Failed to get blkid info (returned 512) for / on tmpfs at /nix/store/<hash>-install-grub.pl line 202

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#130125]
**Describe the bug**
When using [mirroredBoots](https://search.nixos.org/options?channel=21.05&show=boot.loader.grub.mirroredBoots&query=mirroredBoots) with / on tmpfs, the following error occurs when building or rebuilding nixos:

````
...
evaluating file '/nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/tools/misc/grub/2.0x.nix'
evaluating file '/nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/development/tools/gnulib/default.nix'
updating GRUB 2 menu...
updating GRUB 2 menu...
updating GRUB 2 menu...
Failed to get blkid info (returned 512) for / on tmpfs at /nix/store/nvycxmg4g2q5jyqdxfvkgi95sqs48iw3-install-grub.pl line 202.
warning: error(s) occurred while switching to the new configuration
````

The build stops there.  However, the build is actually completed and Grub updated, so I can reboot into the new derivation.

This doesn't occur with a normal / on tmpfs installation, only / on tmpfs using mirroredBoots.

**To Reproduce**
1. Configure `hardware-configuration.nix` with [/ on tmpfs](https://elis.nu/blog/2020/05/nixos-tmpfs-as-root/).
2. Configure `configuration.nix` and `hardware-configuration.nix` for mirroredBoots with two EFI boot partitions on different drives [[1]](https://elis.nu/blog/2019/08/encrypted-zfs-mirror-with-mirrored-boot-on-nixos/), [[2]](https://discourse.nixos.org/t/nixos-on-mirrored-ssd-boot-swap-native-encrypted-zfs/9215/5)
3. `nix-build` or `nix-rebuild` (dry-build and dry-activate succeed with no error, only boot/switch/etc cause this error)

**Expected behavior**
Re/Build should complete as normal. 

**Additional context**

It seems the problem is that `blkid /` returns nothing when / is on tmpfs.  Can verify this by calling blkid on the commandline.  However, this error does not occur on a normal, single-boot-partition / on tmpfs configuration, only when using mirroredBoots simultaneously with / on tmpfs.

`configuration.nix` (boot properties subset) and `hardware-configuration.nix` in this gist:  https://gist.github.com/byrongibson/ff2a6befdf53b94d9ea50fc8441fd35d

Full `configuration.nix` here:  https://github.com/byrongibson/nixos-setup/blob/main/config/configuration.tmpfsroot.zfscrypt.full.z11pa-d8.nix

**Notify maintainers**

@domenkozar 
@teto 
@xaverdh 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1408.9376bf7b342 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by byrongibson** [comment]
Update:  adding the following line to configuration.nix made no difference:

`boot.extraModulePackages = [ config.boot.kernelPackages.nvidia_x11 ];`

**Comment by byrongibson** [comment]
There's a slightly updated build error now, says the same thing but with a bit more info:

````
...
evaluating file '/nix/store/xkjafds79w6s17nf0jkzdcfw09b1s2zj-nixos-21.05.3248.6120ac5cd20/nixos/pkgs/tools/misc/grub/2.0x.nix'
evaluating file '/nix/store/xkjafds79w6s17nf0jkzdcfw09b1s2zj-nixos-21.05.3248.6120ac5cd20/nixos/pkgs/development/tools/gnulib/default.nix'
updating GRUB 2 menu...
installing the GRUB 2 EFI boot loader into /boot1...
Installing for x86_64-efi platform.
/nix/store/8dkfnl4k7vjr5f88kbh389i61ympvrnd-grub-2.06/sbin/grub-install: warning: cannot open directory `/nix/store/8dkfnl4k7vjr5f88kbh389i61ympvrnd-grub-2.06/share/locale': No such file or directory.
Installation finished. No error reported.
updating GRUB 2 menu...
installing the GRUB 2 EFI boot loader into /boot2...
Installing for x86_64-efi platform.
/nix/store/8dkfnl4k7vjr5f88kbh389i61ympvrnd-grub-2.06/sbin/grub-install: warning: cannot open directory `/nix/store/8dkfnl4k7vjr5f88kbh389i61ympvrnd-grub-2.06/share/locale': No such file or directory.
Installation finished. No error reported.
updating GRUB 2 menu...
Failed to get blkid info (returned 512) for / on tmpfs at /nix/store/xh1sd9ms5b2ixhz61qqiz07j2b9xv4z9-install-grub.pl line 202.
warning: error(s) occurred while switching to the new configuration
````

**Comment by JanKaifer** [comment]
It just happened to me with `tmpfs` on `/` but without `mirroredBoots`.

**Comment by byrongibson** [comment]
Thx, good to know it's a not a problem with mirroredboots then.  Fwiw I'm still getting this error on every rebuild, but it doesn't seem cause any actual problems in building or running the system, so I've just been ignoring it.

**Comment by JanKaifer** [comment]
Oh, It's not happening anymore.
I'm installing NixOS from Debian recovery OS provided by my VPS provider.
So It's bit wonky anyway.

All `nixos-install` invocations have thrown that error but after rebooting the recovery it was working again. I might have mounted the partitions incorrectly <picture data-single-emoji=":wizard-shrug:" title=":wizard-shrug:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..n8KXmQ8fMERsnW7Z.LMIRZLhyfOpe-YmJYhXBhqh1o3GlBpuyYd27q_2XVqsNwhtLYHQsPZZIOT7uMFgnmEz0T_0J0fmW9BiiuP3GgETxOge_QZCrBpIppPmLbEGZJXDNJw74T9itq1hbhQ.sTaCol5_YxUIZNLE4c7vHg" alt=":wizard-shrug:" align="absmiddle"></picture> .

**Comment by byrongibson** [comment]
Related:  https://github.com/NixOS/nixpkgs/issues/94210#issue-668331547

**Comment by buckley310** [comment]
This might have to do with the fact that you are specifying both `boot.grub.device` and `boot.grub.mirroredBoots.*.devices`. Remove the former.

Here is an excerpt from a nice well-behaved config I used just yesterday:
```
  boot = {
    loader.grub.enable = true;
    loader.grub.mirroredBoots = [{
      path = "/nix/boot";
      devices = [ "/dev/vda" ];
    }];
  };
```

**Comment by buckley310** [comment]
Hold up, I just also noticed that you have both `systemd-boot.enable = true;` and `grub.enable = true;`. I don't think that's supposed happen.

**Comment by byrongibson** [comment]
> Hold up, I just also noticed that you have both `systemd-boot.enable = true;` and `grub.enable = true;`. I don't think that's supposed happen.

Thanks, I do indeed have both those enabled in the example docs I linked.  However, I checked the ones I'm actually using to build the system and they have `#systemd-boot.enable = true` commented out.  Still same problem.  Need to update my examples.

From digging around on the internet, it seems this error occurs on other Linux's sometimes too, it's not just a NixOS thing.  Will keep digging and see what I can figure out.

**Comment by byrongibson** [comment]
> This might have to do with the fact that you are specifying both `boot.grub.device` and `boot.grub.mirroredBoots.*.devices`. Remove the former.
> 
> Here is an excerpt from a nice well-behaved config I used just yesterday:
> 
> ```
>   boot = {
>     loader.grub.enable = true;
>     loader.grub.mirroredBoots = [{
>       path = "/nix/boot";
>       devices = [ "/dev/vda" ];
>     }];
>   };
> ```

Thanks for the example, but a question - how does mirroredBoots work with only one boot device specified?  For comprison, my mirroredBoots section is:

````
        mirroredBoots = [
          {
            devices = [ "nodev" ];
            path = "/boot1";
          }
          {
            devices = [ "nodev" ];
            path = "/boot2";
          }
        ];
````

**Comment by buckley310** [comment]
mirroredBoots works with any number of devices. In the case of my config above, I just wanted to move the boot folder, and the mirroredBoots trick is cheaper than a bind mount.

So right, in your config you should not have `boot.loader.device` specified. mirroredBoots sort of makes that unnessecary. My suspicion is that it is trying to install in /boot1 and /boot2 because of mirroredBoots, and then also install in /boot dur to the extra `device=`, and since /boot is tmpfs, that breaks.

**Comment by byrongibson** [comment]
Oh man, you're exactly right.  I commented out `boot.loader.device` and it built perfectly with no errors.  Phew, thank you!  It's taken two years to solve this one, and solution was so simple.  Much appreciated!

**Comment by byrongibson** [comment]
> So right, in your config you should not have `boot.loader.device` specified. mirroredBoots sort of makes that unnessecary. My suspicion is that it is trying to install in /boot1 and /boot2 because of mirroredBoots, and then also install in /boot dur to the extra `device=`, and since /boot is tmpfs, that breaks.

Oh man, you're exactly right.  I commented out `boot.loader.device` and it built perfectly with no errors.  Phew, thank you!  It's taken two years to solve this one, and solution was so simple.  Much appreciated!

**Comment by dzmitry-lahoda** [comment]
I see this code 

https://github.com/NixOS/nixpkgs/blob/f60a759ae7003b321e7ff0c835fc03fa685b91e1/nixos/modules/system/boot/loader/grub/grub.nix#L715

so if I specify `device` it will specify `devices` it will specify `mirroredBoots`, and indeed I got `Failed to get blkid info (returned 512)`?

**Comment by 3tieto** [comment]
> mirroredBoots works with any number of devices. In the case of my config above, I just wanted to move the boot folder, and the mirroredBoots trick is cheaper than a bind mount.
> 
> So right, in your config you should not have `boot.loader.device` specified. mirroredBoots sort of makes that unnessecary. My suspicion is that it is trying to install in /boot1 and /boot2 because of mirroredBoots, and then also install in /boot dur to the extra `device=`, and since /boot is tmpfs, that breaks.


how to fix this ?
 
```

### Gathering machine facts ###
Pseudo-terminal will not be allocated because stdin is not a terminal.
error:
       … while calling the 'head' builtin
         at /nix/store/xjjq52iwslhz6lbc621a31v0nfdhr5ks-source/lib/attrsets.nix:1696:13:
         1695|           if length values == 1 || pred here (elemAt values 1) (head values) then
         1696|             head values
             |             ^
         1697|           else

       … while evaluating the attribute 'value'
         at /nix/store/xjjq52iwslhz6lbc621a31v0nfdhr5ks-source/lib/modules.nix:1118:7:
         1117|     // {
         1118|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
         1119|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/xjjq52iwslhz6lbc621a31v0nfdhr5ks-source/nixos/modules/system/activation/top-level.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error:
       Failed assertions:
       - You cannot have duplicated devices in mirroredBoots
```

my config 

```
{ config, lib, pkgs, vars, postBootScript, ... }:
{
  imports = [ ./persistence.nix ];

  boot.initrd.supportedFilesystems = [ "btrfs" ];

  # Script to handle Btrfs snapshots on boot for impermanence
  boot.initrd.postDeviceCommands = pkgs.lib.mkAfter (builtins.readFile postBootScript);

  boot.loader.grub.enable = true;
  boot.loader.grub.mirroredBoots = [{
    path = "/nix/boot";
    devices = [ vars.diskDevice ];
  }];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@root" "compress=zstd" "noatime" ];
  };

  networking.useDHCP = true;
  networking.hostName = vars.srvName;

  # Enable IPv6
  networking.enableIPv6 = true;

  # DNS configuration - Google and Cloudflare
  networking.nameservers = [
    "8.8.8.8"          # Google DNS IPv4
    "8.8.4.4"          # Google DNS IPv4 secondary
    "1.1.1.1"          # Cloudflare DNS IPv4
    "1.0.0.1"          # Cloudflare DNS IPv4 secondary
    "2001:4860:4860::8888"  # Google DNS IPv6
    "2001:4860:4860::8844"  # Google DNS IPv6 secondary
    "2606:4700:4700::1111"  # Cloudflare DNS IPv6
    "2606:4700:4700::1001"  # Cloudflare DNS IPv6 secondary
  ];

  time.timeZone = vars.timezone; # Use timezone from nix-variables.nix
  i18n.defaultLocale = vars.language;
  hardware.enableRedistributableFirmware = true;

  # Disable the default systemd-timesyncd service
  services.timesyncd.enable = lib.mkForce false;

  # Enable ntpd-rs for time synchronization
  services.ntpd-rs = {
    enable = true;
    settings = {
      source = [
        {
          address = "0.pool.ntp.org";
          mode = "pool";
        }
        {
          address = "1.pool.ntp.org";
          mode = "pool";
        }
        {
          address = "2.pool.ntp.org";
          mode = "pool";
        }
      ];
    };
  };

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      # Enable IPv6 for SSH
      AddressFamily = "any";  # Listen on both IPv4 and IPv6
    };
  };

  # Your SSH public key for root login
  users.users.root.openssh.authorizedKeys.keys = [
    vars.sshPublicKey
  ];

  environment.systemPackages = with pkgs; [ vim git wget mosh ];

  # Configure SSH client to automatically accept new server fingerprints (not recommended for security)
  programs.ssh = {
    extraConfig = ''
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
    '';
  };

  system.stateVersion = vars.nixosVersion;
}

```
