### ISSUE TITLE
systemctl --user not working

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#13022]
This is the same issue as #11480, but for KDE 4.

```
$ systemctl --user
Failed to list units: Process org.freedesktop.systemd1 exited with status 1
```

Tested in 15.09 and unstable.

**Comment by chris-martin** [comment]
Actually, I'm seeing this in Gnome 3 as well.

**Comment by joelmo** [comment]
This works in KDE 5

**Comment by chris-martin** [comment]
This problem has been intermittent, and I'm starting to think it may be due to a bad service I'm working on.

**Comment by grahamc** [comment]
@chris-martin can this be closed?

**Comment by chris-martin** [comment]
I no longer really remember what it was about, so I suppose so.

**Comment by petronny** [comment]
Yeah, it is due to a bad service on boot.
After removing all files in `.config/systemd/user/default.target.wants`, `systemctl --user` works again.
