### ISSUE TITLE
Bringing up aarch64 target

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nixpkgs#13042]
I'm starting with stdenvNative. This line is causing me headaches

```
-          then "-isystem $(echo -n ${cc.gcc}/include/c++/*) -isystem $(echo -n ${cc.gcc}/include/c++/*)/$(${cc.gcc}/bin/gcc -dumpm
```

It is in

```
pkgs/build-support/cc-wrapper/default.nix
```

I don't quite understand what it's for and deleting it doesn't seem to cause problems.

**Comment by gitfoxi** [comment]
Question: Once I get `hello` built I'll probably want to build the bootstrap files for this platform. I don't see a bootstrap package. How to do it?

**Comment by dezgeg** [comment]
I've started this as well and what's currently blocking me is that binutils is too old, and if I try to update it to the latest version, x86_64 breaks somehow.

**Comment by gitfoxi** [comment]
Sounds fun. I’m still fighting Perl. One thing you can do is just build binutils from source and install over your system. Doesn’t seem to mind. Maybe we should start working together somewhere?

**Comment by dezgeg** [comment]
https://github.com/dezgeg/nixpkgs/tree/pr-bootstrap-tools-cross is as far as I got, there's a bootstrap tarball checked in at some commit.

**Comment by dezgeg** [comment]
IIRC this is the commit that our binutils is missing: https://sourceware.org/ml/libc-ports/2013-06/msg00063.html

**Comment by gitfoxi** [comment]
Oh, you’re working on a cross build. That’s ambitious. I’m just trying to build natively.

**Comment by dezgeg** [comment]
No, only the bootstrap tarball is cross-built.

**Comment by gitfoxi** [comment]
So if you bump binutils to latest in nixpkgs does it help or cause more problems?

**Comment by dezgeg** [comment]
When I tried it that broke x64_64 totally so I did not try on Aarch64 yet.

**Comment by gitfoxi** [comment]
This is maybe caused by what you’re talking about?

    strip:/nix/store/wpqz799g177jjk1ikb8993j3vkara9fh-perl-5.20.3/bin/cpan: File format not recognized

**Comment by dezgeg** [comment]
No, it was test programs being compiled & run by autoconf segfaulting. The `strip: ...: File format not recognized` is not even a (fatal) error and happens always when there's shell scripts in bin/.

**Comment by gitfoxi** [comment]
With any luck I will get the bootstrap files hosted for you today so you can get back to it. Perl is built. What could go wrong?

**Comment by codyopel** [comment]
related issue https://github.com/NixOS/nixpkgs/issues/909

**Comment by dezgeg** [comment]
I rebased my work on Eelco's binutils-2.26 branch and now I was able to build `hello`: https://github.com/dezgeg/nixpkgs/tree/pr-bootstrap-tools-cross. Still needs a lots of cleanup from all the hacks.

**Comment by gitfoxi** [comment]
@dezgeg Would you be able to make a regular bootstrap-tools? I still haven't made it to that level.

**Comment by dezgeg** [comment]
What do you mean by "regular" bootstrap-tools?

**Comment by gitfoxi** [comment]
I mean non-cross bootstrap-tools. I'm trying to build nixpkgs on an aarch64 server natively using stdenv-linux.

**Comment by dezgeg** [comment]
What's the benefit of building that? The result functions in exactly the same way as the cross-built bootstrap tools except it has a downside of not being buildable in Hydra.

**Comment by gitfoxi** [comment]
I see. I didn't understand that. I thought it was bootstrap tools that run on amd64 and build aarch64. Thank you and I will definitely try it out.

Eventually I may try to setup an aarch64 hydra. 96-cores makes for one heck of a build machine.

**Comment by bobvanderlinden** [comment]
I've been trying to figure this out as well, partly with the help of @cleverca22. However I haven't used cross-build-tools in NixOS before and keep hitting walls. From the commits on https://github.com/dezgeg/nixpkgs/commits/pr-bootstrap-tools-cross it seems you solved quite a few issues already.

At the moment I have Nix on Debian on a rpi3, but since it is running Debian armv7l it is unfortunately not yet aarch64. Building a system (`nix-build -A system nixos/default.nix`) on rpi3 also results in a internal compiler error when it is building gettext.

To get up to speed, what exact command-line did you use to build and on what machine?

Also, what are the steps to get things up and running on an aarch64 system?

**Comment by dezgeg** [comment]
I was building on some Android phone running a Fedora chroot. Once the bootstrap tools are in place, there shouldn't be much else to that than compling Nix the old-fashioned (`./configure`, `make` etc.) way to `/usr/local`, and then using e.g. `nix-build -A hello`.

Cross building the bootstrap tarball is just `nix-build pkgs/stdenv/linux/make-bootstrap-tools-cross.nix -A aarch64`, that needs to be either on NixOS or with chroot builds enabled, or it will pick up some impurities from `/lib` etc.

**Comment by cleverca22** [comment]
only other hard requirement, is that the kernel allow aarch64 binaries, but nix and the rest of the userland could be 32bit, "--argstr system aarch64-linux" will force nix-build to do everything in 64bit mode

**Comment by bobvanderlinden** [comment]
Thanks for all the info. I managed to build `pr-bootstrap-tools-cross` on x86_64 for aarch64. That said, I did need to apply the following hack: https://github.com/bobvanderlinden/nixpkgs/commit/99e949d912eda47b5cc9937f0bc0ad8bc5690e66
I'm still unsure why this is needed.

First I tried building the original `pr-bootstrap-tools-cross` (https://github.com/dezgeg/nixpkgs/commit/150ccd25e9b4d88292a39d3e527a805699ec5ce4) using `nix-build pkgs/stdenv/linux/make-bootstrap-tools-cross.nix -A aarch64 -K`, it results in:
```
...
checking build system type... checking for stdlib.h... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `aarch64-linux-gnu': machine `aarch64' not recognized
configure: error: /nix/store/avv2bszr13nq7yfbw0434hlxrwlfg9mp-bash-4.3-p42/bin/bash build-aux/config.sub aarch64-linux-gnu failed
yes
checking for string.h... note: keeping build directory ‘/tmp/nix-build-libsigsegv-2.10-aarch64-linux-gnu.drv-1’
builder for ‘/nix/store/a9kz6yh2akjxafb39wpdyx54bmniw9rs-libsigsegv-2.10-aarch64-linux-gnu.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/qp2ib732zz331205f14hj27k3adcy2v3-gawk-4.1.3-aarch64-linux-gnu.drv’: 1 dependencies couldn't be built
note: keeping build directory ‘/tmp/nix-build-gnutar-1.28-aarch64-linux-gnu.drv-1’
note: keeping build directory ‘/tmp/nix-build-binutils-2.26-aarch64-linux-gnu.drv-1’
cannot build derivation ‘/nix/store/m7zvya09jg6pln1pv8ql2bkq10f7n68n-build.drv’: 1 dependencies couldn't be built
note: keeping build directory ‘/tmp/nix-build-gmp-5.1.3-aarch64-linux-gnu.drv-1’
error: build of ‘/nix/store/m7zvya09jg6pln1pv8ql2bkq10f7n68n-build.drv’ failed
```

Then I tried `nix-build pkgs/stdenv/linux/make-bootstrap-tools-cross.nix -A aarch64 --argstr system aarch64-linux -K`, but that results in:
```
...
/nix/store/yr6f787q2frdc15kxxy979yp2ravqpwz-nuke-references.drv
  /nix/store/0v4i74qc03c68fcbfksz0sr7fz80mhx6-build.drv
building path(s) ‘/nix/store/j0v0p2q40741jvmlrbb8vh77n3dcmjc3-bootstrap-tools’
error: a ‘aarch64-linux’ is required to build ‘/nix/store/4j9gyyhncslfk96w0w020l0b8k67q1nr-bootstrap-tools.drv’, but I am a ‘x86_64-linux’
```

What was I doing wrong here?

**Comment by dezgeg** [comment]
Most likely I broke the bootstrap tools cross compilation when adding fixes for native building.

**Comment by dezgeg** [comment]
I made some progress on this; now at https://github.com/dezgeg/nixpkgs/tree/pr-aarch64. The one big problem that I've run into is that many packages that come with pre-generated autotools files have been built with such obsolete versions that their `config.sub` and `config.guess` don't know how to deal with Aarch64. I've now added a stdenv hook to update all such files with new upstream ones, which so far seems to work well.

**Comment by bjornfor** [comment]
I believe Buildroot also does that (inject known/recent config.* files).

**Comment by vcunat** [comment]
@bobvanderlinden: that hack is most likely needed because of the fact that `stdenv.system` refers to the build system, not to the host. More on "unexpected meanings" during cross-compilation: https://github.com/NixOS/nixpkgs/issues/14965.

**Comment by bobvanderlinden** [comment]
@vcunat Good to see that's being addressed. Cross-compiling on Nix is still somewhat confusing to me.

@bjornfor I recently heard that Fedora/RedHat also replaces all config.* files for all packages: https://git.fedorahosted.org/cgit/redhat-rpm-config/commit/?id=0a68ef9360bc52f57cabbd90bc5deb8fd502b37e
It might be an option (in the future) to have it enabled for all architectures, not just for aarch64. I'm guessing it affects enough packages to require a massive rebuild.

**Comment by Ericson2314** [comment]
I think this can be closed?

**Comment by vcunat** [comment]
Yes, I think so.  If there are problems, better reopen in a new issue.
