### ISSUE TITLE
libreoffice spellcheck gb uk

### ISSUE THREAD

**Issue by tomjridge** [NixOS/nixpkgs#13046]
I'm in the UK. Installing libreoffice, spellcheck is not working. If I switch to USA language, spellcheck works. Possibly something to do with hunspell missing dictionaries? Any advice?

I tried all the usual things: installing hunspell into my profile; installing hunspell dictionaries into my profile etc. Couldn't get anything to work.

Uninstalled, installed ubuntu libreoffice via apt. Same problem. Finally, installed myspell-en-gb via apt, and spellcheck works.

**Comment by wmertens** [comment]
(triage) not sure if this belongs here, looks like it is an issue with libreoffice not working well with hunspell?

Can you try libreoffice with myspell from nixpkgs?

**Comment by wmertens** [comment]
@tomjridge ping

**Comment by tomjridge** [comment]
nix-env -qa '*' |grep myspell
myspell-dict-he-1.1
myspell-dict-he-1.1

I don't know hebrew :(

On ubuntu, installing libreoffice and myspell-en-gb and possibly libreoffice-l10n-uk worked.

Removing libreoffice and installing nix libreoffice, spell check also worked (presumably picking up myspell from ubuntu).

HTH

**Comment by Profpatsch** [comment]
triage: is this still a problem?

**Comment by mmilata** [comment]
Tried to fix this in #80353, testing appreciated.

**Comment by abathur** [comment]
Closing since mmilata claims to have fixed the underlying problem. Happy to reopen if that's not actually the case.
