### ISSUE TITLE
pythonPackages.protobuf doesn't install native libraries

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#13043]
I've noticed this accidentially while working on https://github.com/NixOS/nixpkgs/pull/13035 -- `installFlags` on [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L15242) doesn't actually do anything. I don't know how to fix this because the flag needs to be used for `setup.py` and I don't know how to propagate it.

cc @domenkozar

**Comment by FRidh** [comment]
I think it's supposed to be `--install-option="--cpp_implementation"` since we're using pip to install the wheel. https://github.com/google/protobuf/issues/539

**Comment by FRidh** [comment]
Fixed in #13165
