### ISSUE TITLE
Rewriting Hashes in replaceDependency should prefer to run locally.

### ISSUE THREAD

**Issue by roconnor** [NixOS/nixpkgs#13056]
Currently when distributed builds enabled each derivation is uploaded to the remote server to have their hashes rewritten.

Within pkgs/build-support/replace-dependency.nix the 'replaceHashes; derivation should be marked in such a way so that the replacement is done locally for those people who have enabled distributed builds.  I believe there is a simple way to do this, but I need to look up how it is done.

@shlevy I've assigned myself this issue, but you might also be interested in fixing it.

**Comment by vcunat** [comment]
`preferLocalBuild = true`, I suppose.

**Comment by regnat** [comment]
(triage) @roconnor , any update on this ? Have you fixed it ?

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/218984
