### ISSUE TITLE
Mixxx: udev rules not installed properly

### ISSUE THREAD

**Issue by leifhelm** [NixOS/nixpkgs#130544]
**Describe the bug**
When adding `services.udev.packages = [ pkgs.mixxx ];` to the NixOS configuration the udev rules do not get installed.

**To Reproduce**
1. Open mixxx with a DJ controller plugged in.
2. The controller is not recognized by mixxx

**Expected behavior**
The udev rules are in the correct folder i.e. `$out/lib/udev/rules.d` or `$out/etc/udev/rules.d` and therefore the udev service does not recognizes them. 

**Additional context**
The fix in #92854 worked for me after a little modification (the rules file got renamed). 

**Notify maintainers**
@prusnak @goibhniu @bfortz

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.4-rt11, NixOS, 21.11.20210717.bdc0044 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05pre278406.d3f7e969b98, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by prusnak** [comment]
Originally, mixxx did the right thing = install udev files to `"${CMAKE_INSTALL_SYSCONFDIR}/udev/rules.d"` - see https://github.com/mixxxdj/mixxx/blob/e0bca241793926e4d57ad9e8c817fd5d7e0e5c54/CMakeLists.txt#L1146-L1151

Later they changed the behaviour and they install to `"${MIXXX_INSTALL_DATADIR}/udev/rules.d"` - see https://github.com/mixxxdj/mixxx/blob/2.3.0/CMakeLists.txt#L1378

Sigh.
