### ISSUE TITLE
services.uwsgi: python{2,3}Packages ignore PropagatedBuildInputs of inputs

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#13060]
The current module implementation of uwsgi does not resolve implicit dependencies from python packages.

For example for a simple flask app this is not enough:
```
  services.uwsgi = {
    enable = true;
    user = "nginx";
    plugins = [ "python2" ];
    instance = {
      my-flask-app = {
        type = "normal";
        python2Packages = self: with self; [ pkgs.my-flask-app flask  ];
      };
    };
  };
```
The whole dependency chain must be added to the packages in order to make the app work:
```
python2Packages = self: with self; [ pkgs.mycube-flask flask redis werkzeug jinja2 markupsafe itsdangerous ];
```
The bad thing really is that the problem only shows itself at runtime with the initial import of the dependency inside the python code.

Some minor nitpicks:
* the current documentation for uwsgi is extremely slim  - e.g. `plugins` is empty by default which results in `-- unavailable modifier requested: 0 --` .
* Mistakenly adding `python` to plugins list instead of `python2` results in a f*ck-you stacktrace generated by nix without any hint what went went wrong - the `pkgs.python` reference should be used instead.

**Comment by abbradar** [comment]
I'll look into this, thanks.

**Comment by FRidh** [comment]
Let me start with saying I am not familiar with uwsgi at all. Even so this looks somewhat similar to https://github.com/NixOS/nixpkgs/pull/13050 (check the outdated comments).

A general solution to such import problems is to make sure `pkgs.my-flask-app` goes via `python-packages.nix`. There have been many issues with packages when that wasn't the case. Maybe this helps...

**Comment by makefu** [comment]
@FRidh The dependencies are coming from flask itself which is coming from upstream pythonPackages . `pkgs.my-flask-app` is actually a derivation i built via `buildPythonPackage` and added it to the pkgs namespace via `nixpkgs.config.packageOverrides`.

**Comment by knedlsepp** [comment]
@makefu: does this work now? I can't make a minimal uwsgi + python setup work.

**Comment by makefu** [comment]
@knedlsepp this is the setup i am running for my custom python application:

* configuration: http://cgit.euer.krebsco.de/stockholm/tree/makefu/2configs/deployment/mycube.connector.one.nix
* application package: http://cgit.euer.krebsco.de/stockholm/tree/makefu/5pkgs/mycube-flask/default.nix

**Comment by knedlsepp** [comment]
Thanks for the examples. I'll see what I can make work and maybe contribute something to the docs: https://github.com/NixOS/nixpkgs/issues/26861

**Comment by makefu** [comment]
@knedlsepp That would be awesome!
You could use the nixos-users wiki ( https://github.com/nixos-users/wiki/wiki ) to write a first draft before going "official".
