### ISSUE TITLE
passwd root - installs password hash into world-readable /etc/passwd

### ISSUE THREAD

**Issue by tera-torn** [NixOS/nixpkgs#13079]
Just installed a fresh nixos in a VM - however at the final step of setting the root password i mis-typed the passwords and was dumped back to a shell with no passwd set for root.

OK - so I figured I would just remove the passwd field for root from /etc/{passwd,shadow} as per the usual trick to allow passwordless login. I first tried to chroot to /mnt in order to run passwd root properly but chroot does not work from the live cd :(

After logging in after reboot, I added a user account and messed around a bit, then logged in to root via VT 1 and ran passwd root to set a passwd.

This resulted in an insecure hash being stored in /etc/passwd which of course is world-readable.

Im attaching my unedited /root/.bash_history file to prove I didn't do anything too stupid. I did not mess up the editing of /etc/passwd or /etc/shadow, though I fail to see how even the biggest screw up should result in an insecure hash being stored in /etc/passwd

So I believe this is a real security bug, and I hope others can reproduce it. Please let me know if I can be of further assistance.

**Comment by jgillich** [comment]
"Insecure hash" means what exactly?

**Comment by tera-torn** [comment]
A hash stored in a world-readable file, /etc/passwd

Ive since been corrected, and I understand that this is just how linux works, in that if you remove the 'x' from the password file in /etc/passwd you get this behvaior. I think it's horribly wrong and an easy mistake to make. I would like to request this behavior be deprecated (nobody actually cares about this backward-compatibility functionality anymore do they?)

/etc/passwd should not be this easy to screw up.

**Comment by jgillich** [comment]
Ah, at first I thought it was about the hash itself. I agree that this behavior is a bit unfortunate.

**Comment by spacefrogg** [comment]
@tera-torn as you found out yourself, this is not a bug but a feature. This only did happen because you edited /etc/passwd in the first place. The default was, that /etc/passwd contained 'x' in the password field and the password's hash was stored in /etc/shadow. This behaviour is properly documented in the applicable man pages, as is the one you've just found. Having said this, I really don't know what your are getting at. You accurately described intended behaviour. The 'screw up', as you call it, took you to have root access to file you knew was privileged and sensitive. Well, you can do any sorts of 'screw ups' with a working root account, try 'rm -rf /' for starters. I'm really sorry for your confusion, but there is no bug here to fix.

As a side note, a hash value is secure by nature (the ones we are talking about in /etc/passwd). It is meant to be easily seen by third parties such that they can verify your authenticity. A hash value in /etc/passwd does not reveal the password of your account. It is feared to be less secure though, as an attacker could run brute-force attacks against the hash to find possible "cleartext passwords" for the public hash. Although it is very unlikely to find it, it is seen as a good security practice to not store the hashes publicly nowadays.

**Comment by zimbatm** [comment]
Removed "bug" label because it's standard Linux behavior. We can discuss if we want to diverge from every other distro out there but it needs more research. Unless someone wants to champion that change I would be tempted to close the issue.

**Comment by tera-torn** [comment]
unix is stupid what else can I say, if a user with decades of administrative experience is making this kind of mistake and leaving world-readable hashes around. It's just too easy to screw up - security features should not be this easy to screw up, and linux and every other unix should fix it, because there isn't any real reason not to. nobody in their right mind on a modern unix EVER expects a hash to be stored in /etc/password, mis-edited fields be damned.

Also, this only occurred, as noted, because chroot from the livecd failed to chroot me to /mnt so that I *could* run the appropriate administrative commands and not edit files manually. But that is fodder for another bug.

**Comment by vcunat** [comment]
IMO this would better be discussed upstream or in some large distro (measured by the amount of maintainers).

**Comment by zimbatm** [comment]
I would also be interested in hearing what upstream has to say.

@tera-torn next time you install nixos, use `nixos-install --chroot`. Nowadays chroots are more complicated that they used to unfortunately.

**Comment by spacefrogg** [comment]
Really, there is no wrong or inconsistent system behaviour here. There is, sorry to be so blatant @tera-torn, user error. The passwd(5) man page clearly describes what will happen, when you edit the password field. @tera-torn, you told your tools to put the password in `/etc/passwd`, you should not complain afterwards. And again, a hash value in `/etc/passwd` is by no means a security nightmare as you want people to believe, using full-caps, italics or strong language won't change that.

There is nothing to be done, here. I'd suggest to close the issue.

**Comment by tera-torn** [comment]
Documentation is no excuse for bad security features that are too easy to screw up. I'm not the first person to have done this nor will I be the last.

Excuse me, I did not characterize it as a nightmare. I said it was a bug (which it is or isn't depending on your perspective); and I said it was a security feature that is too easy to screw up.

It's very bad to have hashes stored in /etc/passwd on a multi-user system; the fact that /etc/shadow exists and is universally recommended in strong terms is indicative of this. Also, most user passwords are weak and most KDFs are also weak by modern standards. I haven't bothered investigating which KDF nixos is using by default since it is neither here nor there - if you have the feature, then support it, and support making it difficult to screw up. That's my opinion - and no I won't close the bug, I'll file it again against other linux distros and other unix distros. If nixos people want to close it that is their prerogative.

**Comment by zimbatm** [comment]
@tera-torn it's great that you feel passionate about security, do let us know how your crusade is going. Are you going to try to produce a patch against `nixos.su` and `nixos.busybox` ?

**Comment by tera-torn** [comment]
I'm sorry I simply fail to see how your commend and question are relevant to this bug report. Apologies if I'm just an a-hole.

**Comment by zimbatm** [comment]
Okay, I want to know if you are going to produce anything. If all you're going to do is rant it's fine but there is no need for us to keep following this issue. At the moment there are 931 other open issues that needs to be taken care of.

**Comment by tera-torn** [comment]
Considering the level of enthusiasm for "fixing" this I am getting here, no, I have no plans on producing anything - and of course you have a lot of better things to do.

**Comment by zimbatm** [comment]
Alright. Hopefully we'll be able to show more enthusiasm in the future but I agree that you are alone on this-one. If you're not going to do it then I'll close the issue.

**Comment by vcunat** [comment]
It's certainly better to bring such questions/enhancements upstream.
