### ISSUE TITLE
jabref: 5.1 -> 5.3

### ISSUE THREAD

**Issue by Coda-Coda** [NixOS/nixpkgs#130717]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: jabref

current version: 5.1
desired version: 5.3

###### Notify maintainers

maintainers: @gebner @wamserma 

###### Note for maintainers

This is not a trivial change, both 5.2 and 5.3 give [an error](https://github.com/NixOS/nixpkgs/pull/109870#issuecomment-763287877) when run (after building 'successfully'). See also: https://github.com/NixOS/nixpkgs/pull/109870, https://github.com/NixOS/nixpkgs/pull/112028, https://github.com/NixOS/nixpkgs/issues/86331#issuecomment-636693631, and https://github.com/NixOS/nixpkgs/pull/101287#issuecomment-773768741

This appears to be an issue which needs to be resolved otherwise jabref may end up stuck on 5.1 on NixOS. Jabref continues to have incremental fixes and new features: https://github.com/JabRef/jabref/blob/main/CHANGELOG.md#53--2021-07-05 Thanks for your efforts so far with jabref on NixOS.

Please tag this issue in your PR.

**Comment by Artturin** [comment]
perhaps try changing it to build from the source with gradle
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jabref
