### ISSUE TITLE
nix-shell: #!-scripts failing

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#13073]
Example script: http://sprunge.us/DDJX

But no matter what I try to run, I get the same error.
```
Use of uninitialized value $line in substitution (s///) at /nix/store/kh16fv1c81f64b3bz5cdqrjxnrkrpx4p-perl-5.20.2/lib/perl5/5.20.2/Text/ParseWords.pm line 20, <SCRIPT> line 2.
error: getting status of ‘/home/svein/bin/1’: No such file or directory
```

**Comment by dezgeg** [comment]
Seems like a dupe of https://github.com/NixOS/nix/issues/790. This is occuring on a version older than 1.11.2, right?

**Comment by Baughn** [comment]
It's a dupe. OTOH, the release hasn't happened yet; I'm running the newest nixpkgs-unstable.
