### ISSUE TITLE
Audio Support for Dell XPS 17 9700

### ISSUE THREAD

**Issue by IvanMalison** [NixOS/nixpkgs#130882]
Audio does not seem to work out of the box for the Dell XPS 17 9700 NixOS (this also applies to most linux distros).

https://github.com/maaarghk/soundwire-dkms/commits/master seems to offer some sort of support for this, but I'm not entirely sure how to integrate this support into nixos.

**Comment by IvanMalison** [comment]
Here is another resource describing how to do this in Ubuntu: https://stukev.com/fixing-the-sound-on-dells-xps-17-9700/

**Comment by IvanMalison** [comment]
https://blog.fts.scot/2020/07/04/dell-xps-2020-how-to-get-audio-working-on-linux/ may also be relevant

**Comment by Mic92** [comment]
Just ignore the fact that it is dkms, we just build all kernel modules upfront. Also ignore their makefile since it hard code paths to linux: https://github.com/maaarghk/soundwire-dkms/blob/master/Makefile#L10

You can build this kernel module similar to https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/mbp-modules/mbp2018-bridge-drv/default.nix and thttps://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/mbp-modules/mbp2018-bridge-drv/default.nix

And make it available in `linuxPackages`.

**Comment by IvanMalison** [comment]
Thanks @Mic92 but I'm still a little lost at what exactly I'm supposed to be doing here. The two examples you posted seems quite different to me.

I'm not super familiar with how how linux kernel modules work to be honest.

I guess what is confusing to me is that it is not totally clear what the build outputs of this soundwire-dkms package should be, or how exactly to produce them, especially without using the provided makefile. Should I be recursing in to the individual directories and running the makefiles there?

arch linux also seems to have a PKGBUILD for this exact package, and all they seem to do is:

```
 install -dm755 "$pkgdir/usr/src"
 cp -r "$srcdir/$_pkgname" "$pkgdir/usr/src/soundwire-$pkgver"
```

can this be used as a template?

**Comment by Mic92** [comment]
Archlinux uses dkms to build linux kernel modules. In NixOS we don't need that, we build kernel modules not on the target machine but in our CI, which is faster and less brittle. If you run `make -C ${kernel.dev}/lib/modules/${kernel.modDirVersion}/build  \
      INSTALL_MOD_PATH=$out M=$(pwd) modules_install` like in the macbook driver example it will automatically create the right installation directory.

**Comment by workflow** [comment]
FWIW the [following patch](https://github.com/workflow/nixos-config/commit/0548a8f26b2abcbb850c92000378cbc6d2fbef5b#diff-2012741984b7b6adbf53dffb89074491c88bd566044996e7163dff885a9c5a4a) should fix audio on the XPS9700 on all Kernels 5.11 and above

(tested on `5.13.9`)

and in this case there's no need to build the module linked above.
Of course this doesn't help if you want to remain on the LTS kernel. (`5.10.x`)

**Comment by IvanMalison** [comment]
@workflow Amazing! Where did you discover that those kernel flags were what is necessary to get things working for the  rt1308?

**Comment by workflow** [comment]
@IvanMalison It was well hidden in [this discussion](https://github.com/maaarghk/soundwire-dkms/issues/4#issuecomment-746217735) :)

**Comment by IvanMalison** [comment]
@workflow Ah nice! Thanks so much for finding this. Might be worth contributing something to nixos-hardware with this tweak: https://github.com/NixOS/nixos-hardware/pull/291

Unfortunate that this does require an entire rebuild of the kernel... I wonder if they will allow a default setting that will do that.

**Comment by IvanMalison** [comment]
I think if we merge something into nixos-hardware we can maybe consider this closed?

**Comment by workflow** [comment]
Ah, neat! https://github.com/NixOS/nixos-hardware/pull/291 sounds great :+1: 

The problem still remains on the current LTS kernel though (`5.10.x`), which does require the module you linked to. I tried building it quickly but failed (probably just missing some dependencies).

Not sure if it's good practice to force XPS 9700 users off the LTS kernel by default. :thinking: 
@Mic92 We might need some guidance here.

**Comment by IvanMalison** [comment]
> The problem still remains on the current LTS kernel though (`5.10.x`), which does require the module you linked to. I tried building it quickly but failed (probably just missing some dependencies)

Ah, I actually do have it building. Let me see if I can dig it up.

**Comment by IvanMalison** [comment]
Yep, here is my working build: https://github.com/IvanMalison/nixpkgs/tree/soundwire

IIRC, it might be a little sloppy right now but it does build. Thanks for all the advice in helping me figure out how to make that work @Mic92 . Looks like the reason it ultimately didn't work is that the additional kernel flags that @workflow found were ALSO needed.

**Comment by IvanMalison** [comment]
https://github.com/NixOS/nixos-hardware/pull/291 is ready to go and fully tested. I consider this issue resolved.

**Comment by workflow** [comment]
There's still a huge problem with the microphone quality, I'm currently looking into that @IvanMalison

**Comment by workflow** [comment]
Hmm looked into it briefly but found no solution yet. Working around this by connecting a headset with a simple USB-C to Audiojack in, which has its own "sound card"

```
$> record --list-devices
card 2: A [USB-C to 3.5mm Headphone Jack A], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
  ```

**Comment by IvanMalison** [comment]
> Hmm looked into it briefly but found no solution yet. Working around this by connecting a headset with a simple USB-C to Audiojack in, which has its own "sound card"

huh the built in microphone seems to work somewhat okay for me.

**Comment by workflow** [comment]
Lucky you :) some folks [here](https://askubuntu.com/questions/1333624/no-audio-dell-xps-9700-kernel-5-12) report that it might depend on the exact hardware used.

I'm seeing the following in `dmesg` and internal mic input doesn't work, although sound output is fine with our patches.

```
[   14.959044] sof-audio-pci-intel-cnl 0000:00:1f.3: use msi interrupt mode
[   14.969847] sof-audio-pci-intel-cnl 0000:00:1f.3: hda codecs found, mask 4
[   14.973853] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware info: version 1:7:0-47d07
[   14.973855] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[   14.973858] sof-audio-pci-intel-cnl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[   15.002138] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.PEG0.PEGP.GPS.PCGP], AE_NOT_FOUND (20210331/psargs-330)
[   15.002143] ACPI Error: Aborting method \_SB.PCI0.PEG0.PEGP.GPS due to previous error (AE_NOT_FOUND) (20210331/psparse-529)
[   15.002147] ACPI Error: Aborting method \_SB.PCI0.PEG0.PEGP._DSM due to previous error (AE_NOT_FOUND) (20210331/psparse-529)
[   15.002195] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.PEG0.PEGP.GPS.PCGP], AE_NOT_FOUND (20210331/psargs-330)
[   15.002197] ACPI Error: Aborting method \_SB.PCI0.PEG0.PEGP.GPS due to previous error (AE_NOT_FOUND) (20210331/psparse-529)
[   15.002199] ACPI Error: Aborting method \_SB.PCI0.PEG0.PEGP._DSM due to previous error (AE_NOT_FOUND) (20210331/psparse-529)
[   15.110935] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware info: version 1:7:0-47d07
[   15.110938] sof-audio-pci-intel-cnl 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[   15.196865] sof-audio-pci-intel-cnl 0000:00:1f.3: Topology: ABI 3:18:1 Kernel ABI 3:18:0
[   15.204761] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.PEG0.PEGP.GPS.PCGP], AE_NOT_FOUND (20210331/psargs-330)
[   15.204768] ACPI Error: Aborting method \_SB.PCI0.PEG0.PEGP.GPS due to previous error (AE_NOT_FOUND) (20210331/psparse-529)
[   15.204868] ACPI Error: Aborting method \_SB.PCI0.PEG0.PEGP._DSM due to previous error (AE_NOT_FOUND) (20210331/psparse-529)
[   15.213115] sof-audio-pci-intel-cnl 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[   15.616226] input: sof-soundwire Headset Jack as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card2/input36
[   15.616266] input: sof-soundwire HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card2/input37
[   15.616299] input: sof-soundwire HDMI/DP,pcm=6 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card2/input38
[   15.616330] input: sof-soundwire HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1f.3/sof_sdw/sound/card2/input39
[   15.894115] ucsi_acpi USBC000:00: unknown error 0
```

**Comment by IvanMalison** [comment]
@workflow Just to clarify, are you saying that analogue microphone input does not work, or that the built in microphone does not work, or both?

**Comment by IvanMalison** [comment]
@workflow curious what your lspci output looks like.

Here's mine:
```
00:00.0 Host bridge: Intel Corporation 10th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 02)
00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 02)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Comet Lake PCH Thermal Controller
00:13.0 Serial controller: Intel Corporation Device 06fc
00:14.0 USB controller: Intel Corporation Comet Lake USB 3.1 xHCI Host Controller
00:14.2 RAM memory: Intel Corporation Comet Lake PCH Shared SRAM
00:14.3 Network controller: Intel Corporation Comet Lake PCH CNVi WiFi
00:15.0 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH Serial IO I2C Controller #0
00:15.1 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH Serial IO I2C Controller #1
00:16.0 Communication controller: Intel Corporation Comet Lake HECI Controller
00:1b.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #17 (rev f0)
00:1c.0 PCI bridge: Intel Corporation Device 06b8 (rev f0)
00:1c.4 PCI bridge: Intel Corporation Device 06bc (rev f0)
00:1d.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #9 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Device 068e
00:1f.3 Multimedia audio controller: Intel Corporation Comet Lake PCH cAVS
00:1f.4 SMBus: Intel Corporation Comet Lake PCH SMBus Controller
00:1f.5 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH SPI Controller
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2060 Max-Q] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU106 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU106 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU106 USB Type-C UCSI Controller (rev a1)
02:00.0 Non-Volatile memory controller: Micron Technology Inc Device 5405
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5260 PCI Express Card Reader (rev 01)
04:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:04.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
06:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 4C 2018] (rev 06)
3a:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 4C 2018] (rev 06)
6e:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:04.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
70:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 4C 2018] (rev 06)
a4:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 4C 2018] (rev 06)
```

**Comment by workflow** [comment]
> @workflow Just to clarify, are you saying that analogue microphone input does not work, or that the built in microphone does not work, or both?

Analogue microphone input works with strong distortions that I wasn't able to fix so far.
Built-in microphone doesn't work at all.

Here's my `lspci`

```
00:00.0 Host bridge: Intel Corporation 10th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 02)
00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 02)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Comet Lake PCH Thermal Controller
00:13.0 Serial controller: Intel Corporation Device 06fc
00:14.0 USB controller: Intel Corporation Comet Lake USB 3.1 xHCI Host Controller
00:14.2 RAM memory: Intel Corporation Comet Lake PCH Shared SRAM
00:14.3 Network controller: Intel Corporation Comet Lake PCH CNVi WiFi
00:15.0 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH Serial IO I2C Controller #0
00:15.1 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH Serial IO I2C Controller #1
00:16.0 Communication controller: Intel Corporation Comet Lake HECI Controller
00:1b.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #17 (rev f0)
00:1c.0 PCI bridge: Intel Corporation Device 06b8 (rev f0)
00:1c.4 PCI bridge: Intel Corporation Device 06bc (rev f0)
00:1d.0 PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #9 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Device 068e
00:1f.3 Multimedia audio controller: Intel Corporation Comet Lake PCH cAVS
00:1f.4 SMBus: Intel Corporation Comet Lake PCH SMBus Controller
00:1f.5 Serial bus controller [0c80]: Intel Corporation Comet Lake PCH SPI Controller
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2060 Max-Q] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU106 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU106 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU106 USB Type-C UCSI Controller (rev a1)
02:00.0 Non-Volatile memory controller: SK hynix Device 1639
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5260 PCI Express Card Reader (rev 01)
04:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:04.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
06:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 4C 2018] (rev 06)
3a:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 4C 2018] (rev 06)
6e:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
6f:04.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
70:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 4C 2018] (rev 06)
a4:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 4C 2018] (rev 06)
```

Interesting, the only diff I see is

`02:00.0 Non-Volatile memory controller: Micron Technology Inc Device 5405`
`02:00.0 Non-Volatile memory controller: SK hynix Device 1639`

I'm currently on `5.13.15` kernel.

**Comment by tobiasBora** [comment]
@workflow did you finally solved your microphone issue? I have exactly the same issue (but what do you mean by analogue vs built-in microphone?). I asked some questions in https://discourse.nixos.org/t/dell-xps-13-9320-microphone-not-working/40932

**Comment by workflow** [comment]
> @workflow did you finally solved your microphone issue? I have exactly the same issue (but what do you mean by analogue vs built-in microphone?). I asked some questions in https://discourse.nixos.org/t/dell-xps-13-9320-microphone-not-working/40932

@tobiasBora Hey, it has been working now for a while yes, though I can't remember exactly what fixed it!
I'm still using the following kernel patches: https://github.com/workflow/dotfiles/blob/fe458ebe54c659baadc9ee0a503edd4b971864a1/machines/flexbox/system.nix#L22

Here's what I meant:

Internal: Built-in Microphone (working now :heavy_check_mark: )
Analogue: External mic connected via AUX out (audio jack) (:grey_question: not sure since I switched to using a USB-C adapter, then it works)

**Comment by tobiasBora** [comment]
Thanks! I actually fixed my issue using `sudo alsactl init` the first tine and enabling `sound.enable = true;` to persist it accross boot. Cf https://github.com/NixOS/nixpkgs/issues/294048 for webcam support.

**Comment by workflow** [comment]
> Thanks! I actually fixed my issue using `sudo alsactl init` the first tine and enabling `sound.enable = true;` to persist it accross boot. Cf #294048 for webcam support.

Without my [kernel overrides](https://github.com/workflow/dotfiles/blob/fe458ebe54c659baadc9ee0a503edd4b971864a1/machines/flexbox/system.nix#L22) the internal mic is still not working on `6.1.76`.

Running `sudo alsactl init` gives the following error:
```
Found hardware: "HDA-Intel" "Nvidia GPU 93 HDMI/DP" "HDA:10de0093,1028098f,00100100" "0x1028" "0x098f"
Hardware is initialized using a generic method
alsa-lib main.c:846:(execute_sequence) exec '/bin/rm -rf /var/lib/alsa/card1.conf.d' failed (exit code 1)
```

likely because it's already enabled,

and `sound.enable` seems to be true by default.

**Comment by tobiasBora** [comment]
No, this error is due to the fact that `/bin/rm` is not existent in NixOs. I created a true issue there https://github.com/NixOS/nixpkgs/issues/294170 but in the meantime I used a dirty workaround I should have listed, which is to run:
```
$ sudo mkdir /bin
$ sudo ln -s /run/current-system/sw/bin/rm /bin
$ sudo ln -s /run/current-system/sw/bin/mkdir /bin
```
This is quite dirty, but does the job until the above issue is fixed.

**Comment by workflow** [comment]
@tobiasBora Both the options and having `sound.enable = true` are required on my machine, but no manual running of `alsactl init`.

On a separate note, apparently the option for `SND_SOC_RT1308` was removed again between `6.1.76` and `6.1.82` (or I overlooked something in the first place), so I'm upstreaming it here:

**Comment by workflow** [comment]
Another note in the long list of strange audio adventures on this Laptop:

After switching to `pipewire`, I now have to enable the following Alsa channel capture:

![image](https://github.com/NixOS/nixpkgs/assets/1276854/e6a58de9-7684-46a0-8c65-048a500418a9)

...after every reboot for the internal microphone to work.

**Comment by tobiasBora** [comment]
Even with `sound.enable = true;`?

**Comment by workflow** [comment]
> Even with `sound.enable = true;`?

`sound.enable = true` [isn't recommended anymore with a PipeWire setup](https://nixos.wiki/wiki/PipeWire).

Enabling it anyways, the only effect seems to be to add an `alsa-store` systemd service:

```
● alsa-store.service - Store Sound Card State
     Loaded: loaded (/etc/systemd/system/alsa-store.service; enabled; preset: enabled)
     Active: active (exited) since Wed 2024-05-29 13:47:38 WEST; 10s ago
    Process: 52557 ExecStart=/nix/store/204ak4443zipfr2yi6y5wal05bck1qqg-coreutils-9.3/bin/mkdir -p /var/lib/alsa (code=exited, status=0/SUCCESS)
```

...that creates the `/var/lib/alsa` directly, which at least leads to the ALSA settings to be persisted once changed, so slight improvement in the sense that I no longer have to change the ALSA state on reboot.

Not sure if that interferes with Pipewire though.

**Comment by workflow** [comment]
Note that kernels `6.6.37` seem to break audio again.

This seems closely related to https://github.com/NixOS/nixpkgs/issues/330685, but none of the presented patches seem to work on this machine.

Relevant logs on bad kernel versions:
```
Aug 20 11:18:41 flexbox kernel: sof_sdw sof_sdw: ASoC: topology: add_route failed: -22
Aug 20 11:18:41 flexbox kernel: sof_sdw sof_sdw: ASoC: topology: could not load header: -22
Aug 20 11:18:41 flexbox kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: tplg component load failed -22
Aug 20 11:18:41 flexbox kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to load DSP topology -22
Aug 20 11:18:41 flexbox kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
Aug 20 11:18:41 flexbox kernel: sof_sdw sof_sdw: ASoC: failed to instantiate card -22
Aug 20 11:18:41 flexbox kernel: sof_sdw sof_sdw: snd_soc_register_card failed -22
Aug 20 11:18:41 flexbox kernel: sof_sdw: probe of sof_sdw failed with error -22
```

**Comment by alyssais** [comment]
This should be reported upstream.

**Comment by workflow** [comment]
Updating Firmware to the latest released by Dell seems to fix this on kernels `6.6.48+` 🎉

**Comment by workflow** [comment]
This was required to fix the internal mic: https://askubuntu.com/a/1376570/203326

**Comment by workflow** [comment]
This currently affects the card coming out of standby mode: https://bugs.launchpad.net/ubuntu/+source/firmware-sof/+bug/2056125

**Comment by workflow** [comment]
On recent kernels, I had to do the following tweaks to get the internal mic back into a usable working state: https://github.com/workflow/dotfiles/commit/ea4ab842d5a722a7f33d000632e5898f9b30a5b6
