### ISSUE TITLE
Package Request: mnamer (Python)

### ISSUE THREAD

**Issue by devhell** [NixOS/nixpkgs#130839]
**Project description**
mnamer (media renamer) is an intelligent and highly configurable media organization utility. It parses media filenames for metadata, searches the web to fill in the blanks, and then renames and moves them.

**Metadata**

* homepage URL: https://github.com/jkwill87/mnamer
* source URL: https://github.com/jkwill87/mnamer
* license: mit
* platforms: unix

**Comment by urlordjames** [comment]
I'll give it a try.
