### ISSUE TITLE
clang 12 fails to link C++ programs on Darwin

### ISSUE THREAD

**Issue by Kha** [NixOS/nixpkgs#130963]
**Describe the bug**
When using `llvmPackages_12.clang`, `clang++` fails to link (any) C++ programs due to missing stdlib symbols:
```
Undefined symbols for architecture x86_64:
  "___cxa_allocate_exception", referenced from:
      _main in test.o
  "___cxa_throw", referenced from:
      _main in test.o
ld: symbol(s) not found for architecture x86_64
```
Manually specifying `-lc++abi` fixes the issue.

**To Reproduce**
See https://github.com/Kha/nix-test/runs/3126436025:
```bash
$ cat test.cpp
#include <exception>

int main () { throw std::exception(); }
$ nix-shell -p llvmPackages_12.clang --command "clang++ test.cpp"
```

**Expected behavior**
Compiling and linking a C++ program should succeed without further linker flags, like on other platforms and LLVM versions

**Additional context**
The only possibly relevant change I found in the libc++ 12 release notes is https://reviews.llvm.org/D68269?id=295642. That one only talks about new/delete and Darwin not being affected, though that might not be applicable to the particular way it is built in Nixpkgs.

**Notify maintainers**
@lovek323 @7c6f434c @dtzWill @primeos

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.14`
 - nixpkgs: `/nix/store/mz5n0jj0dfvdxp3kmprrxyc5p479mkny-nixexprs.tar.xz`
```
(from GitHub Actions above)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: llvmPackages_12.clang
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
Let's close this in favour of a more complete description in #166205
