### ISSUE TITLE
NixOS 21.11/20.05 is causing GIGABYTE M1022 to suspend randomly

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#130947]
### Describe the bug
When powered on it on random intervals turns off with blinking light indicating suspended.

### To Reproduce
0. Get GIGABYTE M1022 
1. Install NixOS on it, expect it to suspend randomly

### Additional context
Journalctl -b: https://gist.githubusercontent.com/Kreyren/7525d1595540562f22b06be4f3342828/raw/e20b6954b0e603dc6fc2c8512dcdb37e0f3a7bcc/gistfile1.txt

dmesg: https://gist.githubusercontent.com/Kreyren/353b489c8e9ab85f9322375431b0b6db/raw/2434789498e7fe406bd05b2f3d2e520b6ba91217/gistfile1.txt

Disabling `powerManagement.enable` does not affect the issue

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

[Connection to daemon refused]

**Comment by Kreyren** [comment]
CC @edolstra

**Comment by Kreyren** [comment]
Setting `services.logind.lidSwitch = "ignore";` prevents the random suspensions

**Comment by Artturin** [comment]
This shouldn't be our bug 
check systemd,kernel,debian,arch,ubuntu bug trackers
stop pinging unrelated people

**Comment by xfix** [comment]
Make sure you aren't wearing a magnetic bracelet or a watch, as it may make your laptop think its lid was closed.

**Comment by dasJ** [comment]
This was identified to be a hardware issue on Matrix, supported by the fact disabling lid switch handling fixes it.

**Comment by Kreyren** [comment]
Can you clarify who's bug is this then? I never had this issue on this system using other distribution mainly gentoo, debian, devuan and on Windows.

> check systemd,kernel,debian,arch,ubuntu bug trackers  @Artturin

How is debian, arch and ubuntu relevant?

Kernel? So is this driver or firmware issue?

systemd.. no idea what is relevant to it
