### ISSUE TITLE
Nexus not working in NixOS 21.05

### ISSUE THREAD

**Issue by Dehumanizer77** [NixOS/nixpkgs#130926]
**Describe the bug**
Nexus won't start and is complaining that no suitable java virtual machine could be found in the system

**To Reproduce**
1. enable nexus with services.nexus.enable = true;
2. the service won't start:
Jul 21 11:23:16 proxy1 systemd[1]: Starting Sonatype Nexus3...
Jul 21 11:23:16 proxy1 systemd[1]: Started Sonatype Nexus3.
Jul 21 11:23:16 proxy1 nexus-start[2267]: No suitable Java Virtual Machine could be found on your system.
Jul 21 11:23:16 proxy1 nexus-start[2267]: The version of the JVM must be 1.8.
Jul 21 11:23:16 proxy1 nexus-start[2267]: Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.

**Notify maintainers**
@aespinosa @ironpinguin @zaninime 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.72, NixOS, 21.05pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-19.03.173144.973a2705351"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by OPNA2608** [comment]
Duplicate of #130754

**Comment by Dehumanizer77** [comment]
Sorry, I have overlooked that issue. Closing.
