### ISSUE TITLE
liferea hash error

### ISSUE THREAD

**Issue by anjefu** [NixOS/nixpkgs#13107]
Liferea 1.10.18 fails to install, possibly due to upstream changes to the binary (https://github.com/lwindolf/liferea/issues/310):

    output path ‘/nix/store/2c8x8dkxsfisahy447mcggj335h6n6cg-liferea-1.10.18.tar.bz2’ has sha256 hash ‘0xyy0qm3h22b69if2hmg36jzvvljxb1w0zy2m2a28kdqfzpa6m8g’ when ‘0wpinar2cxyzq2j7ff7lznc08f0n6qjdm9aavsarbgdpaf2s1xvq’ was expected

My nixos-version is 16.03pre76756.885acea (Emu)

**Comment by zimbatm** [comment]
thanks, PRed

**Comment by copumpkin** [comment]
Context: https://github.com/NixOS/nixpkgs/commit/7fd2cc1ea8687568901e7f8efec940ccb9e06657

**Comment by zimbatm** [comment]
Closing as it's fixed in master

**Comment by vcunat** [comment]
And I though noone was using the package around here...
