### ISSUE TITLE
Cannot install nixos (minimal image) in qemu VM

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#13106]
I'm getting:

![2016-02-18-222446_1366x768_scrot](https://cloud.githubusercontent.com/assets/427866/13158712/796be94e-d68e-11e5-88e1-bb456b41ea72.png)

(the first call you see is from the history) I clearly have an ext4 system in my qemu, though it complains about ext2 ... ?

The qemu was build like this:

```bash
$  qemu-img create -f qcow2 ./nixos-disk 10G 
$  qemu-system-x86_64 -enable-kvm -m 4G -cdrom ~/dlds/nixos-minimal-15.09.1076.9220f03-x86_64-linux.iso -boot order=d ./nixos-disk
```

**Comment by dezgeg** [comment]
You need a partition table on the drive to install GRUB on it.

**Comment by matthiasbeyer** [comment]
That fixed it.
