### ISSUE TITLE
php: include opcache module

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#13105]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/default.nix

./configure --enable-opcache

maybe include APCu to be compatible with APC like

```
# https://pecl.php.net/package/APCu
yes '' | /usr/local/php56/bin/pecl -C /etc/php56/pear.conf install APCu-4.0.10
echo "extension=apcu.so" >> /etc/php56/conf.d/apcu.ini
```

should be easy, i will do that if no one is faster :D

**Comment by danbst** [comment]
what's the progress on this? in my experiments with php56 opcache is builtin, just have to
```
      zend_extension=${php}/lib/php/extensions/opcache.so
      opcache.validate_timestamps = 0
```

**Comment by fpletz** [comment]
Also enabled in php70. Closing.
