### ISSUE TITLE
tdesktop 2.8.11 has some bugs in KDE

### ISSUE THREAD

**Issue by Hentioe** [NixOS/nixpkgs#131022]
**Describe the bug**

The window shadow of tdesktop `2.8.11` overflows and appears as a blur effect.   
The same phenomenon exists in the right-click menu.

**To Reproduce**

1. Use KDE as DE
2. Use Brezze or kvantum as application style
3. Install tdesktop 2.8.11

**Expected behavior**

The window border is displayed normally, including shadow and blur effects.

**Screenshots**

![image](https://user-images.githubusercontent.com/13946976/126592191-86291f28-bee0-403e-9074-fd291a17beec.png)
![image](https://user-images.githubusercontent.com/13946976/126590819-489438c5-1ff5-4e05-91e9-ea252096850d.png)

**Additional context**

In the previous version, this problem did not occur.  
Please pay attention to the right and bottom borders of the window in the first screenshot, and around the right-click menu in the second screenshot.

**Notify maintainers**

@primeos @abbradar

**Metadata**

Output of `nix-shell -p nix-info --run "nix-info -m"` command":
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.51, NixOS, 21.11pre303315.16105403bdd (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.11pre303315.16105403bdd"`
 - channels(hentioe): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:

```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- tdesktop
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
Check upstream

**Comment by Hentioe** [comment]
> Check upstream

Yes, I will report this issue to the tdesktop project.

**Comment by Hentioe** [comment]
To my surprise, this bug seems to come from the global theme of the Plasma desktop. When I changed some global themes, it disappeared.

I will continue to communicate this issue to the theme developers, and if I find it has nothing to do with NixOS, I will close this issue.

**Comment by oxalica** [comment]
Is this still relevant? It's 3.1.11 now. I'm using the default breeze theme all the time and cannot reproduce this.

**Comment by VergeDX** [comment]
Ping @Hentioe

**Comment by Hentioe** [comment]
This phenomenon exists today.  But it may be a theme or KDE problem, or a common problem.  I will test it with more themes soon.

**Comment by Hentioe** [comment]
The phenomenon has disappeared, and there are some stylesheet issues in my environment. After I solved them, the TG window was normal.
