### ISSUE TITLE
FreeCAD 0.19 fails to install Cfd workbench on NixOS 21.11

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#131155]
![image](https://user-images.githubusercontent.com/11302521/126728651-80d1789a-dfa9-44f8-93a8-f3410aeb9013.png)

### Steps To Reproduce
0. Install FreeCAD
1. Open random project
2. Try to install `Cfd` addon and expect mentioned failure

### Expected behavior

Just work(TM)

### Additional info

Log: https://gist.githubusercontent.com/Kreyren/66aaa1b3e2f9e784b489830baf81c833/raw/77d84d6760aad09dc23df411a6ca7cd17bd7cc05/gistfile1.txt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.11pre301985.23cd13167a1 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre301985.23cd13167a1"`
 - channels(kreyren): `"home-manager-21.05, master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

![image](https://user-images.githubusercontent.com/11302521/126728785-3af8a2eb-23f2-4dfb-a5d2-bb5a32eb863e.png)

**Comment by Kreyren** [comment]
CC package maintainers @viric @gebner @AndersonTorres

**Comment by FRidh** [comment]
Thus far the way of working has been with FreeCAD in Nix that you need to add additional dependencies impurely. E.g., also if you want to use the FEM workbench, you need additional tools which you need to make available on `PATH`. I suppose it's the same with this workbench. Check the docs to see what tools are needed.

**Comment by Kreyren** [comment]
@FredeEB Elaborate on adding those impurely? Like making a repo with `nix.shell` ?

**Comment by FredeEB** [comment]
I think you got the wrong mention here @Kreyren :)

**Comment by Kreyren** [comment]
Ooops sorry! x.x @FRidh

**Comment by AndersonTorres** [comment]
Still relevant?
