### ISSUE TITLE
kde5 depends on qt4

### ISSUE THREAD

**Issue by heydojo** [NixOS/nixpkgs#13113]
environment.systemPackages in
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/desktop-managers/kde5.nix
contains
```
pkgs.qt4 # qtconfig is the only way to set Qt 4 theme
```
Is there anyway to remove this dependency? Does it not stand to reason that if you install a qt4 application in kde5 that pkgs.qt4 is pulled in and so it is unnecessary to specify it here?

I am just tired of seeing qt4 being built here when I have no applications using it.

**Comment by vcunat** [comment]
Are you sure you have no applications using it? AFAIK it's comment for todays KDE5 apps to still use Qt4, unfortunately. /cc @ttuegel

**Comment by ttuegel** [comment]
> Does it not stand to reason that if you install a qt4 application in kde5 that pkgs.qt4 is pulled in and so it is unnecessary to specify it here?

Unfortunately, no, Nix doesn't install dependencies into the environment, just the store.

> AFAIK it's common for today's KDE5 apps to still use Qt4, unfortunately.

The default package set installs Qt 4 applications, so you have Qt 4 applications installed.
