### ISSUE TITLE
Problem with fonts in browsers

### ISSUE THREAD

**Issue by dan4ik605743** [NixOS/nixpkgs#131168]
**Describe the bug**

After update. Tied with GLIBC-2.33, it happened in the browser. On some sites. Type (github.com google.com nixos.org and so on). There are sites on which everything is fine (translate.google.com vk.com and so on). I do not even know what to do. I put qutebrowser out of 20.09 everything is fine. And this problem is observed in Chromium. She spent Firefox there, too, everything in the port. I am sure that I am not like this with the same problem. How to be?

**Screenshots**
![image](https://user-images.githubusercontent.com/86075850/126736754-6da67885-51c9-4773-89f3-2516b08e906d.png)

**Metadata**
λ ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.133, NixOS, 21.11.20210721.1610540 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre299299.3a8d7958a61"`
 - nixpkgs: `/nix/store/g2g13rv513i8z8rav2imcfk49fm8bac1-source`

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/131074

**Comment by dan4ik605743** [comment]
> Dupe of https://github.com/NixOS/nixpkgs/issues/131074

Thx
