### ISSUE TITLE
R should not depend on TexLive by default

### ISSUE THREAD

**Issue by aristidb** [NixOS/nixpkgs#1311]
... it's too bloated

@peti @edolstra

**Comment by peti** [comment]
This issue appears to be dead in the water. Everyone seems to agree that the current state of affairs sub-optimal and a PR that improves on it would be highly welcome.

**Comment by shlevy** [comment]
I don't understand why this is closed. The issue isn't fixed.

**Comment by shlevy** [comment]
Perhaps we should have some issue tag for "backlog" or some such?

**Comment by garbas** [comment]
i like the idea of closing tickets if they dont get attention in some time.
this only means that we will end up with bunch of tickets that nobody wants to
work on.

**Comment by vcunat** [comment]
You can easily sort tickets by date of last change, so personally I'd prefer to leave similar issues open as long as they're still meaningful (though enhancement-only "issues" don't seem so important).
