### ISSUE TITLE
nixos-option shows _module attributes

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#13120]
```
$ nixos-option foo -I `pwd`
Value:
{ _module = { args = { name = "foo"; }; check = true; }; bar = "baz"; }
```

We should probably ignore it. cc @nbp

**Comment by nbp** [comment]
@domenkozar 
What is your configuration.nix used to reproduce this issue?

**Comment by domenkozar** [comment]
Hmm, good point. I've deleted the test module  so I can't find an example now. I'll close until I hit this again.
