### ISSUE TITLE
nixos-option trips upon types.submodule

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#13121]
```
$ nixos-option services.mwlib.nslave.http.port
An error occurred while looking for attribute names.
8898
```

cc @nbp

**Comment by Profpatsch** [comment]
(triage) still occurs

**Comment by Ma27** [comment]
Indeed, I stumbled upon this several times. As I'm already trying to improve `nixos-option` (see #43147) I might give it a try as well %)

**Comment by Ma27** [comment]
ok, don't know enough about the module system. However I think that we might want to use another data format (e.g. something like this https://nixos.org/nixos/options.json ?)
