### ISSUE TITLE
Pomotroid - Simple and visually-pleasing Pomodoro timer.

### ISSUE THREAD

**Issue by NiharKod** [NixOS/nixpkgs#131264]
**Project description**
Pomotroid is a simple and configurable Pomodoro timer. It aims to provide a visually-pleasing and reliable way to track productivity using the Pomodoro Technique.

**Metadata**

* homepage URL: https://github.com/Splode/pomotroid
* source URL: https://github.com/Splode/pomotroid/releases/tag/v0.13.0
* license: mit
* platforms: linux, windows, mac

**Comment by WolfangAukang** [comment]
Merged
