### ISSUE TITLE
protonmail-bridge: Unable to log-in

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#131243]
The proposed in https://github.com/NixOS/nixpkgs/issues/126174#issuecomment-879385133 results in:

```
...
error: The option `systemd.user.services.protonmail-bridge.Install' does not exist. Definition values:
- In `/home/kreyren/Repositories/system-management/domains/rixotstudio.cz/machines/leonid':
    {
      WantedBy = [
        "default.target"
      ];
    }
...
```

I revisited the solution in https://github.com/NixOS/nixpkgs/issues/126174#issuecomment-864425888 which seems to get past the issue (using values from the systemd service with the service stopped):

```
[kreyren@leonid:~]$ PATH=/nix/store/sr99h0qwcr9dr8azfp1aaibypvf21433-gnome-keyring-40.0/bin /nix/store/9v91s1d6k4wwa7kxh1d15j0n2w5fqfvm-protonmail-bridge-1.6.9/bin/protonmail-bridge --log-level debug
time="Jul 23 16:42:54.286" level=info msg="Run app" appName="ProtonMail Bridge" args="[/nix/store/9v91s1d6k4wwa7kxh1d15j0n2w5fqfvm-protonmail-bridge-1.6.9/bin/protonmail-bridge --log-level debug]" build= revision= runtime=linux version=1.6.9+git
time="Jul 23 16:42:54.288" level=info msg="Check status on localhost:8081" pkg=frontend-nogui
time="Jul 23 16:42:54.288" level=info msg="IMAP server listening at 127.0.0.1:1143" pkg=imap
time="Jul 23 16:42:54.288" level=info msg="Checking for updates"
time="Jul 23 16:42:54.288" level=info msg="API listening at 127.0.0.1:1042" pkg=api
time="Jul 23 16:42:54.288" level=info msg="SMTP server is starting" address="127.0.0.1:1025" pkg=smtp useSSL=false
time="Jul 23 16:42:54.484" level=info msg="An update is available" pkg=app/bridge version=1.8.7
time="Jul 23 16:42:54.484" level=info msg="Installing update package" package="https://protonmail.com/download/bridge/bridge_1.8.7_linux_update.tgz"
time="Jul 23 16:42:54.484" level=debug msg="Clearing token" userID=anonymous-1
time="Jul 23 16:43:16.291" level=debug msg="Clearing token" userID=anonymous-2
```

But still does not allow me to log-in and use the port.

_Originally posted by @Kreyren in https://github.com/NixOS/nixpkgs/issues/126174#issuecomment-885690511_

**Comment by Kreyren** [comment]
I am unable to get the GUI to log-in so i assume that this has to be handled through a home-manager to fill the content in `~/.config/protonmail/bridge/prefs.json` ?

**Comment by Kreyren** [comment]
I was able to login using `protonmail-bridge --cli` using the paths from the systemd unit e.g.
`PATH=/nix/store/sr99h0qwcr9dr8azfp1aaibypvf21433-gnome-keyring-40.0/bin /nix/store/9v91s1d6k4wwa7kxh1d15j0n2w5fqfvm-protonmail-bridge-1.6.9/bin/protonmail-bridge --cli` 

CC @lightdiscord @kalbasit

**Comment by BalooRJ1** [comment]
Were you able to solve this issue? I've also run into this problem using Q4OS with TDE. Installed and activate GNOME keyring, but I am still unable to login, getting "incorrect login credentials" from Protonmail Bridge.
