### ISSUE TITLE
Idea: option to make pure wrappers

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#13130]
When building packages it's easy to test something and only realize later that actually the program depends on XYZ that was in your path. I think this happens quite a lot. Same with environment variables, people install things in services and suddenly SSL don't work anymore.

What if we were to build little wrapper scripts for all of our programs that filter-out any capabilities that  aren't needed by the program ? Maybe add an option in mkDerivation like: 

```
allow = {
  network = true;
  syscalls = [ ];
  env = [ "PATH" "SSL_CERT_FILE" ];
}
```

The wrapper script would work similarly to makeWrapper and maybe also integrate seccomp on Linux.

**Comment by vcunat** [comment]
When I see restrictions on network and syscalls, it seems more like some heavier sandbox than just a little wrapper similar to our `makeWrapper`.

**Comment by zimbatm** [comment]
Maybe I got a bit carried away :)

Do you agree that as a packager it's easy to miss run-time dependencies and that it would be nice if most programs didn't look outside of their derivation path ? Obviously it doesn't work for all programs.

Is it crazy to wrap all executables in an environment-stripping script ?

**Comment by vcunat** [comment]
If we don't want some variables passed, then why even define them? (I assume NixOS.)

I would think that the purpose of the default environment variables is for all programs to see them; or at least the programs that change their action based on them, but for others it doesn't matter, does it? It's certainly good to reduce their number, but it seems often one does implicitly assume they get passed.

**Comment by zimbatm** [comment]
I was thinking more for nix-env installs where the program inherits from the user's environment.

How hard would it be to augment derivations with the metadata and have nix-env produce these wrapper scripts ?

**Comment by vcunat** [comment]
The wrapping itself is relatively easy, I believe, but it seems hard to decide what variables to leave by default and it's per-package work. It may cause confusion, too, IMHO.
