### ISSUE TITLE
buildEnv silently ignore the mime files of packages

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#13134]
The Thunar file manager doesn't recognize the type of any file be default. All files are treated as having the `text/plain` mime type. [LinuxQuestions suggests to install shared-mime-info](http://www.linuxquestions.org/questions/linux-from-scratch-13/all-file-types-shown-with-same-icon-in-thunar-4175452990/) in order to solve this. This does work when the package is installed into the user profile, but it _doesn't_ work when it's installed as a system package for some reason (even if Thunar is a system package). Also, shouldn't the derivation make this work without any extra work?

Similar issues seem to be #12280 and #9678. Not sure if they might need similar fixes to what we conclude here.

**Comment by iyzsong** [comment]
What's the value of ``XDG_DATA_DIRS`` environment variable?
It should contain the shared-mime-info's ``share/mime`` directory.

**Comment by a1russell** [comment]
```
$ echo $XDG_DATA_DIRS
/home/adam/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
```

I'm not sure what the `share/mime` directory is that you're talking about, @iyzsong, but it looks like it's not there. Should the `shared-mime-info` package be responsible for updating that environment variable?

Also I should mention that `shared-mime-info` doesn't work if it's installed via the [method documented to keep multiple packages up to date at once](https://nixos.org/wiki/Howto_keep_multiple_packages_up_to_date_at_once). So it only works if explicitly installed via `nix-env -i`.

**Comment by iyzsong** [comment]
This look correctly, the environment variable is set by some NixOS modules.

Sorry,  for ``share/mime`` I don't mean the path but the contents.
if you install it as a system package (by using ``environment.systemPackages``),
then under ``/run/current-system/sw/share/mime`` there should be some
directories (aliases, audio, etc.) from ``shared-mime-info``, and also a ``mime.cache`` file.
 And I think if any directory in the XDG_DATA_DIRS has those contents, it should work fine.

Could you have a look what contents are under ``~/.nix-profile/share/mime, /nix/var/nix/profiles/default/share/mime and /run/current-system/sw/share/mime``?
particularly if ``mime.cache``is a symlink to the ``shared-mime-info``?

**Comment by a1russell** [comment]
In `~/.nix-profile/share/mime`, there's only a directory called `packages`, which I believe belongs to the `keepassx` package I have installed, since `~/.nix-profile/share/mime` -> `/nix/store/2lrcfbrcf84smriiavh6aq7c47j0dwz7-all/share/mime` -> `/nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/share/mime`.

Secondly, `/nix/var/nix/profiles/default/share/mime` doesn't exist. This is because `/nix/var/nix/profiles/default/share` points to `/nix/store/hjmr907md69xyr862wq2nw2k25yn412p-git-2.1.4/share` and contains `emacs`, `git`, `git-core`, `git-gui`, `gitk`, `gitweb`, `info`, `locale`, and `man`.

Finally, `/run/current-system/sw/share/mime` is empty.

**Comment by iyzsong** [comment]
Assume you did add it to ``systemPackages``,
then it look like the bug which got fixed in #9622.

Make sure upgrade your NixOS first (it's in the release-15.09 too).

**Comment by a1russell** [comment]
@iyzsong When was #9622 supposedly fixed? It looks like last year, and I've definitely updated since then. I don't think this is that, though. And besides, my package is installed with the [method documented to keep multiple packages up to date at once](https://nixos.org/wiki/Howto_keep_multiple_packages_up_to_date_at_once) rather than systemPackages, at least at the moment.

It looks to me like the symlinks are created in a determinant manner. Like, when there is more than one package that supplies a path, which gets precedence? For instance, why does keepassx get `~/.nix-profile/share/mime` for me?

**Comment by iyzsong** [comment]
Oops, you're right the commit is 2015-09-07 and is unrelated to the case.

For ``buildEnv``, those mime directories should be merged, if some files collisions, by default it should abort.

If you have set ``ignoreCollisions``, maybe it's #4621?

**Comment by iyzsong** [comment]
So, with:
```
buildEnv = {
  name = "e";
  paths = [ keepassx shared_mime_info ];
};
```
I get:
```
$ tree result
result
├── bin
│   ├── keepassx -> /nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/bin/keepassx
│   └── update-mime-database -> /nix/store/w34qvvhbmkmlcsd80n8axp6dg2dpyvci-shared-mime-info-1.5/bin/update-mime-database
└── share
    ├── applications -> /nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/share/applications
    ├── keepassx -> /nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/share/keepassx
    ├── locale -> /nix/store/w34qvvhbmkmlcsd80n8axp6dg2dpyvci-shared-mime-info-1.5/share/locale
    ├── man -> /nix/store/w34qvvhbmkmlcsd80n8axp6dg2dpyvci-shared-mime-info-1.5/share/man
    ├── mime
    │   └── packages
    │       ├── freedesktop.org.xml -> /nix/store/w34qvvhbmkmlcsd80n8axp6dg2dpyvci-shared-mime-info-1.5/share/mime/packages/freedesktop.org.xml
    │       └── keepassx.xml -> /nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/share/mime/packages/keepassx.xml
    ├── mimelnk -> /nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/share/mimelnk
    ├── pixmaps -> /nix/store/inivr58sb8ayr4bib0a857h94rxcryvh-keepassx-0.4.4/share/pixmaps
    └── pkgconfig -> /nix/store/w34qvvhbmkmlcsd80n8axp6dg2dpyvci-shared-mime-info-1.5/share/pkgconfig

```

Other files under the mime directory of ``shared-mime-info`` are missing.

**Comment by iyzsong** [comment]
For buildEnv,
commit 99e825a ignore mime databases from packages, and add a hook to build them.
commit 3c82466 remove the hook and suggest to do it in ``postBuild``.

Hi @a1russell, for now I think you can update the mime database manually, like:
```
    x = buildEnv {
      name = "a";
      paths = [ keepassx shared_mime_info ];
      postBuild = ''
        $out/bin/update-mime-database $out/share/mime
      '';
    };


```

**Comment by vcunat** [comment]
I believe just adding `shared_mime_info` into your `systemPackages` should resolve the problem (many desktops also cause it to be included by default IIRC). There are hooks in system env generation to update the mime database.

**Comment by a1russell** [comment]
@iyzsong Thanks for the investigative work. #4621 does look relevant, although I haven't set `ignoreCollisions` anywhere (and I think it defaults to `false`). Where should I place the workaround you suggested? It looks like a package derivation. Also, we should still look to fix this appropriately, for everyone, right?

@vcunat Sorry, but it doesn't. I've tried that and explicitly said as much in my original post.

**Comment by vcunat** [comment]
That's strange, as this all does work for me and I didn't even have to put `shared_mime_info` into there. Was this always broken for you? BTW, I've missed: what nixos version do you use?

**Comment by iyzsong** [comment]
You can use ``systemPackages`` or add the ``postBuild`` to your buildEnv.

This only happend when you use buildEnv manually (as described in the mutiple packages wiki), for ``systemPackages`` (the prefer way IMO) the hooks does exist in system-path.nix.

Hardcode the hooks in buildEnv is not a good idea because a profile can install many buildEnv , if we build the cache for every buildEnv, then collision occur.

**Comment by vcunat** [comment]
Except for `systemPackages` it's nix-env's own buildEnv that matters, and that one isn't in the nixpkgs repo.

**Comment by a1russell** [comment]
@vcunat Yes, I've always had this problem, and I'm just now getting the time to troubleshoot it. I use the unstable channel at home, and the stable channel at work.

@iyzsong Ok, I think I understand now that I can add the `postBuild` to my package collection (called `all` in the documentation and `x` in your comment), if `shared_mime_info` is installed via that method. However, I don't understand the `systemPackages` version.

Let's say I have Thunar installed via `systemPackages`. Theoretically this should work already, since it depends on shared-mime-info. Since it doesn't, are you saying I should add `shared_mime_info` to `systemPackages` and the `postBuild` to `/etc/nixos/configuration.nix` in a similar manner to the `buildEnv`? I ask because I can find no documentation on `postBuild` being added alongside `systemPackages`...

**Comment by vcunat** [comment]
`systemPackages` already does have a `postBuild` that regenerates shared mime info.

**Comment by a1russell** [comment]
@vcunat I've already stated that it's not working for me. What information can I provide you that proves it to your satisfaction?

**Comment by vcunat** [comment]
I'm sorry. I shouldn't have repeated myself (and force you). I do believe it doesn't work in your case.

**Comment by iyzsong** [comment]
hi, a1russell.  I think this is a document issue,
and can be fixed by adding information about postBuild to
the keep-mutiple-packages-update wiki page.

What do you think?

The page: #13187

**Comment by a1russell** [comment]
Long term, @iyzsong, I think any Nix user could reasonably expect that, when they install something, it should work. That's not the case with this package right now. I imagine that other packages could be affected by this, as well.

So I think that documentation is great in the meantime, but we should also think of a better solution.

I haven't had time to switch my system config around in the past couple of days, but when I do, I'll try and provide some details about what this look like when I install shared-mime-info via system package rather than build env. Maybe that will help show why the current postBuild isn't working.

**Comment by a1russell** [comment]
I haven't tried it again on my 15.09 system (where I know I had the problem), but I want to report that on my "unstable"-channel system, installing `shared_mime_info` as a system package does populate `/run/current-system/sw/share/mime/`.

Even still, this seems odd to me, since this package should be a dependency of Thunar, which I have installed. Dependencies shouldn't have to be explicitly installed in order to work, in my opinion.

I'll try this on my 15.09 system soon to get some more information.

**Comment by a1russell** [comment]
Alright, installing `shared_mime_info` explicitly in `systemPackages` on my 15.09 system does create `/run/current-system/sw/share/mime/packages/freedesktop.org.xml`, although nothing else exists in `/run/current-system/sw/share/mime` besides that.

I still am not aware of how to manually add a `postBuild` for `systemPackages`.

**Comment by regnat** [comment]
(triage) status of this ?

**Comment by layus** [comment]
This is not yet fixed. I have stumbled on this recently.

@a1russell There is a lot to learn from https://github.com/NixOS/nixpkgs/blob/f66d7823ece6fa4bf99e56fa4b4cb0ab16522839/nixos/modules/config/system-path.nix#L129-L155

1. > I still am not aware of how to manually add a postBuild for systemPackages.

   Well, you cannot do that yet. It is not modular. See the `# !!! Hacky, should modularise.` ? Good news is that custom postBuilds are not needed for this issue. See below.

2. > Alright, installing `shared_mime_info` explicitly [...] does create [...], although nothing else exists in /run/current-system/sw/share/mime besides that.

   I had better luck by adding `desktop_file_utils` which contains `update-desktop-database`. This created the required `$out/share/applications/mimeinfo.cache`. Now applications are picked by default.
   See the `# outputs TODO: note that the tools will often not be linked by default` ?

This situation needs to be improved. Asking to manually install `shared_mime_info` and `desktop_file_utils` is unfriendly. Also, only /nixos/modules/config/system-path.nix has this postBuild. I am not quite sure how it is supposed to work for user-installed packages, but I had to copy that postBuild to my buildEnv (my setup is like #13187).

@vcunat You added the remark 2. at https://github.com/NixOS/nixpkgs/commit/ab8a691d059b364c435a1871ae2ef70a578685d8#diff-dcba170e079cd72958889058d01a4a02R133. Do you think that it would be a good idea to make buildEnv depend on `shared_mime_info` and `desktop_file_utils` directly ?

**Comment by vcunat** [comment]
Yes, I think it would be a passable workaround, e.g. conditioned on `environment.noXlibs` or something, so it doesn't encumber truly minimal configs.

**Comment by a1russell** [comment]
Closing this since there doesn't seem to be any interest in fixing it, and I've moved on to another distro.

**Comment by fdietze** [comment]
I stumbled across the same problem and after a long search was able to fix it by installing these two packages:
```
xdg_utils
shared_mime_info
```

Would be nice if this was a sane default.

**Comment by danbst** [comment]
I went ahead and added `nix-env` postInstall hook support. This is horribly hacky, but it works for me - I can update whatever home cache files I want after `nix-env -i/-e/-u`.

It works like this:
- first, we wrap `nix-env` command and install the package as `hiPrio` (so it overrides original `nix-env` from Nix)
- there we run `nix-env` as usual
- then we test if `~/.nix-profile/manifest.nix` was changed after the command. If it was changed, we launch mimeinfo.cache hook
  - which creates a temp directory, copies all the `share/applications` stuff and builds there a `mimeinfo.cache` file
  - and installs to current profile
  - this creates an extra profile generation, which is bad, but not THAT bad
```
with import <nixpkgs> {};
let
  mimeinfo = builtins.toFile "mimeinfo.nix" ''
    with import <nixpkgs> {};
    pkgs.runCommand "mimeinfo.cache" {} '''
      mkdir -p $out/share/applications
      echo "--------"
      echo "Regenerating ~/.nix-profile/share/applications/mimeinfo.cache..."
      echo "--------"
      cp ''${./mimeinfo.cache} $out/share/applications/mimeinfo.cache
    '''
  '';
in lib.hiPrio (writeScriptBin "nix-env" ''
  set -e
  NIX="$(${coreutils}/bin/readlink -f $(which nix-build))"
  NIX="$(${coreutils}/bin/dirname "$NIX")"
  "$NIX/nix-env" "$@"
  [ -z "$NIX_ENV_NO_HOOKS" ] || exit 0

   >&2 echo "Running nix-env postHook..."

  mimeinfo_cache_hook() {
    lastHash=$(cat ~/.cache/nix/manifest.sha256 || echo -en)
    newHash=($(sha256sum ~/.nix-profile/manifest.nix))
    if [[ "$lastHash" != "$newHash" ]]; then
      WORK_DIR=$(mktemp -d)
      function cleanup {
        rm -rf "$WORK_DIR"
      }
      trap cleanup EXIT INT
      ${xorg.lndir}/bin/lndir -silent ~/.nix-profile/share/applications $WORK_DIR
      ${xorg.lndir}/bin/lndir -silent ~/.local/share/applications $WORK_DIR

      ${desktop-file-utils}/bin/update-desktop-database $WORK_DIR
      cp ${mimeinfo} $WORK_DIR/mimeinfo.nix
      "$NIX/nix-env" -if $WORK_DIR/mimeinfo.nix
      echo "$newHash" > ~/.cache/nix/manifest.sha256
    fi
  }

  mimeinfo_cache_hook
'')
```
Install this with `nix-env -if path/to/nix-env-with-hooks.nix`
