### ISSUE TITLE
Alacritty has a blank title

### ISSUE THREAD

**Issue by notfed** [NixOS/nixpkgs#131380]
### Describe the bug
Alacritty works, but it has a blank window title.

![alacritty-no-title](https://user-images.githubusercontent.com/28705/126908548-de64bfde-71c8-4668-943e-362a2d452085.png)

### Steps To Reproduce

I'm using NixOS 21.05 with GNOME+Wayland (the defaults) and installed Alacritty with Home Manager like this:

```
home.packages = with pkgs; [
   ... alacritty ...
];
```

Alacritty works, but there is no window title, even when I launch alacritty with `alacritty --title "Alacritty"`. According to `man alacritty`, the default window title is "Alacritty".

### Expected behavior

I need there to be a title, because I use a hotkey to open Alacritty, and it detects whether it's already open by looking for a window titled "Alacritty". 

On other Linux distributions, I haven't run into this issue. (I've tried Fedora and Debian.)

### Notify maintainers
@Br1ght0ne
@mic92
@cole-h
@ma27

### Metadata
 - host os: `Linux 5.10.50, NixOS, 21.05.1590.63ee5cd99a2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(jay): `"home-manager, nixpkgs-21.11pre303315.16105403bdd"`
 - nixpkgs: `/home/jay/.nix-defexpr/channels/nixpkgs`

**Comment by Artturin** [comment]
works for me 

Does `print -Pn "\e]2;TEST\a"` work?

**Comment by Mic92** [comment]
Also works for me.

Does this version works?

```console
$ nix-store -r /nix/store/rkp5f6krr8zmgip97cqvz7ihvkygjafl-alacritty-0.8.0/bin/alacritty 
$ /nix/store/rkp5f6krr8zmgip97cqvz7ihvkygjafl-alacritty-0.8.0/bin/alacritty --title "Foobar"
```

**Comment by notfed** [comment]
Thanks for the quick responses.

> Does print -Pn "\e]2;TEST\a" work?

Nothing changed.

> Does this version works?

Same symptom.

**Comment by Artturin** [comment]
What if you install it with systemPackages

**Comment by Mic92** [comment]
I tested this on i3. Maybe test this in gnome/x11.

**Comment by Artturin** [comment]
I'm on sway

**Comment by figsoda** [comment]
Seems like an upstream problem with alacritty and gnome on wayland
https://github.com/alacritty/alacritty/issues/4034
https://github.com/alacritty/alacritty/issues/4739

**Comment by notfed** [comment]
Thanks figsoda, looks like you're right. I'll close this, then.
