### ISSUE TITLE
$language.withoutPackages

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#131334]
It would be interesting to have `python.withoutPackages [ ... ]`, `perl.withoutPackages [ ... ]`

Similar to `.withPackages` in some sense, but removing the packages bundled into `python` and `perl` by default.

There are really tons of garbage: support for far-east languages (tens of megabytes), ...

**Comment by SuperSandro2000** [comment]
the package that are bundled into python itself are expected by many packages to just exist and are almost never checked if they don't exist.
