### ISSUE TITLE
chromium: Missing fonts

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#131364]
### Describe the bug
Chromium on unstable does not render fonts.

### Steps To Reproduce
1. `nix-shell -p chromium`

### Expected behavior
Fonts should be displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/1482768/126875800-e41c6248-b36c-40ba-b261-e26f5a4c4404.png)

### Additional context
see https://discourse.nixos.org/t/qutebrowser-rendering-is-failing/14202

### Notify maintainers
@squalus @primeos @thefloweringash @bendlas 

/cc @nrdxp 

### Metadata
```console
asbachb@nixo-t14s  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.3, NixOS, 21.11pre303315.16105403bdd (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(asbachb): `"nixos-21.05pre286647.4518794ee53, nixos-20.09-20.09.4025.dc326c78a93"`
 - channels(root): `"nixos-21.11pre303315.16105403bdd, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
* chromium
# a list of nixos modules affected by the problem
module:
* programs.chromium.enable
```

**Comment by nrdxp** [comment]
As stated in the referenced discourse, this is also affected qutebrowser on unstable, so it must be something in the underlying font engine they are using

**Comment by primeos** [comment]
See #131074, already fixed in `master` (and Hydra: https://hydra.nixos.org/build/148449692) and will be available with the next channel update.
