### ISSUE TITLE
oci-containers: systemd unit early logs lost

### ISSUE THREAD

**Issue by cptMikky** [NixOS/nixpkgs#131469]
When using `virtualisation.oci-containers` to manage containers, early logs (i.e. logs that come from the systemd unit itself rather than from the container) are inherently lost beause of https://github.com/NixOS/nixpkgs/blob/973910f5c31b9ba6c171c33a8bd7199990b14c72/nixos/modules/virtualisation/oci-containers.nix#L265.

This causes problems with debugging issues that prevent the container from starting in the first place.

I suggest leaving `StandardOutput` and `StandardError` unset by default (effectively making them `journal`) and / or expose those parameters in the `oci-containers` module.

**Comment by zowoq** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/commit/14d21926235194ba5332b98437d868f65743b326.
