### ISSUE TITLE
Package Request: Morgen (calendar)

### ISSUE THREAD

**Issue by Ashe** [NixOS/nixpkgs#131496]
**Project description**
Morgen is a premium, cross-platform calendar application. We don't have many pretty calendar applications. I don't know how easy it is to package something that uses snap, or whether there's a way

**Metadata**

* homepage URL:https://morgen.so/
* source URL: https://morgen.so/download
* license: Premium
* platforms: Windows, Linux, Mac

**Comment by peterhoeg** [comment]
They provide `.deb`s too, so that's probably the easiest.

**Comment by WolfangAukang** [comment]
Had to close the previous PR because I suscribed to a bot and it was spamming the ticket.

On this new PR, I fixed some issues like the startup script pointing to the correct binary path and an error at the beginning of the script.

**Comment by Ashe** [comment]
Thank you for your hard work! :)

**Comment by WolfangAukang** [comment]
Merged!
