### ISSUE TITLE
Recent changes in gettext break git (at least git-rebase)

### ISSUE THREAD

**Issue by avnik** [NixOS/nixpkgs#13150]
Example of buggy output:
```
/nix/store/0mj281929f2zxm8jcl2143vhbrywjj1n-git-2.7.0/libexec/git-core/git-rebase: line 62:  gettext: command not found
```

Temporary workaround -- put `pkgs.gettext` to systemEnvironment

/cc @vcunat bug possible come with 74bda15a94490feef13dd7313f64255acc3d6af3

**Comment by zimbatm** [comment]
Yes that's the fix in master. What channel are you using ?

**Comment by avnik** [comment]
@zimbatm master, was  built yesterday.   Added `gettext` to system env

**Comment by avnik** [comment]
So may be commit I referenced above not fix all problems,  At least `git rebase -i` affected

**Comment by vcunat** [comment]
The commit above doesn't affect the git -> gettext.sh link; it affects gettext.sh -> (n)gettext.

**Comment by zimbatm** [comment]
I can reproduce the issue with master. 
The original culprit is from me: https://github.com/zimbatm/nixpkgs/commit/c38eb526d59e2fcc985a0459e94a6ad30b1d3706
I am starting to think that we should maybe revert that change until the whole chain is fixed.

**Comment by zimbatm** [comment]
Ok I think that I have found the issue. Sorry I haven't been careful enough, working on a fix.

**Comment by avnik** [comment]
Possible adding
```
gettext() {
   @out@/bin/gettext "$1"
}
```
to gettext.sh can help

**Comment by zimbatm** [comment]
Yep. What do you think of https://github.com/zimbatm/nixpkgs/commit/b15c6f2e40a7aefd1969a51c14ac42c3a3b2b9c8 ? Still testing as we speak

**Comment by zimbatm** [comment]
Okay envsubst also hasn't been properly wrapped in gettext.sh

**Comment by matthiasbeyer** [comment]
I experienced this issue just one minute ago.

I'm on 

```
$  nixos-version 
16.03pre77568.40c586b (Emu)
```

@zimbatm , @DamienCassou maybe this issue is not yet resolved completely?

**Comment by vcunat** [comment]
Commit 11733b3 is *not* contained in 40c586b.
