### ISSUE TITLE
pgadmin -> PostgreSQL administration GUI tool

### ISSUE THREAD

**Issue by bavramor** [NixOS/nixpkgs#131571]
https://search.nixos.org/packages?channel=21.05&show=pgadmin&from=0&size=50&sort=relevance&query=pgadmin
Very old version: Name: pgadmin3Version: 1.22.2

Current version is 
2021-07-15 - pgAdmin 4 v5.5 Released

I also get the following error message during installation:
uilder for '/nix/store/174n3aap38677m5l7jzh32nbcrwchrip-pgadmin3-1.22.2.drv' failed with exit code 2

**Comment by mausch** [comment]
I know it's not the same etc but as a workaround have a look at DBeaver.

**Comment by jtojnar** [comment]
Duplicate of #33103
