### ISSUE TITLE
Minitube's play control icons are missing

### ISSUE THREAD

**Issue by volhovm** [NixOS/nixpkgs#13159]
I'm on nixos `16.03pre76756.885acea` with `xmonad` dm. For some reason, button icons in `minitube 2.4` are not working. Here's how it looks like:

http://i.imgur.com/jjL7UVB.png

There are play/stop/forward buttons over there.

I'm also experiencing something similar with `thunderbird`:

http://i.imgur.com/yqGrCr2.png

As you can see, there are some artifacts on button images and they change if i press the button. I don't know if these issues are related, but, who knows.

**Comment by volhovM** [comment]
Now having the same problem with `DeadBeef-0.7.0`:
http://i.imgur.com/n5YwFFd.png

**Comment by Profpatsch** [comment]
triage: Can you check whether this is still a problem?
