### ISSUE TITLE
`gist` package dies looking for `bundler/setup`

### ISSUE THREAD

**Issue by tsion** [NixOS/nixpkgs#13158]
`nix-shell -p gist --run gist` get me this error:

```
/nix/store/h4sibipp5fp83nk100mrp8qhypvd8lr9-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /nix/store/h4sibipp5fp83nk100mrp8qhypvd8lr9-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /run/current-system/sw/bin/gist:16:in `<main>'
```

`nix-shell -p gist bundler --run gist`, on the other hand, works flawlessly. But I'm not sure if adding the bundler package as a dependency would be the right way to fix this.

**Comment by zimbatm** [comment]
Hi @tsion, can you give me what channel / OS you are encountering the issue on ?

**Comment by tsion** [comment]
@zimbatm I have reproduce it on NixOS with `nixos-unstable` and on Ubuntu with `nixpkgs-unstable`.

**Comment by zimbatm** [comment]
@tsion okay, I just simplified the install and it should also fix your issue. Do you want to try my branch out ?

**Comment by tsion** [comment]
@zimbatm I can confirm, your branch works for me. Thanks a lot!
