### ISSUE TITLE
numpy fails to build on newer CPUs (due to current openblas 0.2.14 dependency)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#13163]
But we cannot upgrade to openblas 0.2.15 either, due to runtime issues (segfault?). Possible fix is to package the openblas 'develop' branch.

See discussions:

https://github.com/NixOS/nixpkgs/commit/73e9cb9748bdd5e3343972aafd094669d629ff3a#commitcomment-16220474

https://github.com/xianyi/OpenBLAS/issues/583#issuecomment-186578789

CC @FRidh.

**Comment by FRidh** [comment]
Did you try with 2.15 yourself?

We could also go back to Atlast + Lapack. It would mean changing 
https://github.com/NixOS/nixpkgs/blob/dc3a1bff576cd73ff7043c113d722842ec360f40/pkgs/development/python-modules/numpy.nix#L22
and the same line in `scipy.nix`. And of course 
https://github.com/NixOS/nixpkgs/blob/dc3a1bff576cd73ff7043c113d722842ec360f40/pkgs/top-level/python-packages.nix#L12805

**Comment by bjornfor** [comment]
@FRidh: I just built numpy with openblas 0.2.15 and did ```python -c "import numpy```. Nothing more. (numpy is just being pulled in as a dependency on my system, I don't really have any specific use for it at the moment.)

If upstream makes a new release in a week, I can wait for that.

**Comment by FRidh** [comment]
Good. I think we do need to have a solution for the new stable.

**Comment by grahamc** [comment]
They put out an RC: https://github.com/xianyi/OpenBLAS/releases/tag/v0.2.16.rc1

**Comment by FRidh** [comment]
I'm now testing the RC.
@bjornfor , do you know whether `nix.useChroot = true;` would hide processor information?

**Comment by bjornfor** [comment]
I'm pretty sure it doesn't.

**Comment by FRidh** [comment]
Evaluation with openblas 0.2.15: https://headcounter.org/hydra/eval/312337
Evaluation with openblas 0.2.16.rc1: https://headcounter.org/hydra/eval/312284

We get a segfault with scikitlearn when using 0.2.15, but not anymore with 0.2.16.rc1.
@bjornfor , could you try building the current PR?

**Comment by FRidh** [comment]
That is, this one #13870

**Comment by FRidh** [comment]
I've evaluated numpy/scipy/scikitlearn without issues using openblas 0.2.17. See https://github.com/NixOS/nixpkgs/pull/14267

**Comment by FRidh** [comment]
Because we use openblas 0.2.17 now I am closing this.
