### ISSUE TITLE
Heroic Games Launcher init at 1.8.2

### ISSUE THREAD

**Issue by papojari** [NixOS/nixpkgs#131620]
**Project description**
A Native GUI Epic Games Launcher for Linux, Windows and Mac. 

**Metadata**

* homepage URL: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
* source URL: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher.git
* license: gpl3
* platforms: windows, linux, darwin, ...

**Comment by WolfangAukang** [comment]
Merged
