### ISSUE TITLE
buku is broken on 756962e87f4b1fa6c954543abcca50051b38309a

### ISSUE THREAD

**Issue by GoldsteinE** [NixOS/nixpkgs#131607]
### Describe the bug
Update in SQLAlchemy has broken flask-admin, which in turn breaks build of buku due to failing flask-admin test. Relevant issue:
https://github.com/sqlalchemy/sqlalchemy/issues/6065

### Steps To Reproduce
1. Pin nixpkgs to 756962e87f4b1fa6c954543abcca50051b38309a
2. Try to install buku

### Expected behavior
Buku is successfully installed

### Notify maintainers
@matthiasbeyer @Infinisil @Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
; nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0, NixOS, 21.11.20210706.036dc0c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - channels(root): `"nixos-21.05pre291486.900115a4f7f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ma27** [comment]
Should be fixed in https://github.com/NixOS/nixpkgs/pull/131140.

**Comment by FliegendeWurst** [comment]
Can confirm that the build failure is fixed.
