### ISSUE TITLE
haskell-updates: package cryptonite breaks with static RTS

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#131652]
### Describe the bug
When building cryptonite (used by neuron) with ghc884 the build breaks saying *Encountered missing or private dependencies: integer-gmp -any*:
>building '/nix/store/71mady9rljq46mjh281hacvyg9gzb381-cryptonite-0.29.drv' on 'ssh-ng://nixos-shell'...
building '/nix/store/71mady9rljq46mjh281hacvyg9gzb381-cryptonite-0.29.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/m1gr87h66gan6192jkipbhipsnvfbdhs-ghc-8.8.4.
unpacking sources
unpacking source archive /nix/store/apvg23ilfgyksdf6ycmgsva9gh433kn4-cryptonite-0.29.tar.gz
source root is cryptonite-0.29
setting SOURCE_DATE_EPOCH to timestamp 1620486029 of file cryptonite-0.29/cryptonite.cabal
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-cryptonite-0.29.drv-0/setup-package.conf.d -j1 +RTS -A64M -RTS -threaded -rtsopts
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-cryptonite-0.29.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/5n9vy6nlb0qm5qxgnag0caa68wrp6pn9-cryptonite-0.29 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --with-gcc=gcc --package-db=/tmp/nix-build-cryptonite-0.29.drv-0/package.conf.d --ghc-options=-j1 +RTS -A64M -RTS --disable-split-objs --disable-library-profiling --disable-profiling --disable-shared --disable-coverage --enable-static --disable-executable-dynamic --disable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --extra-lib-dirs=/nix/store/m4x0hqp8amgh987v1862x9hpxpi5rsgj-ncurses-6.2/lib --extra-lib-dirs=/nix/store/5kk54jcy2pwsns57d4iganj8k53hhvq5-libffi-3.3/lib
Using Parsec parser
Configuring cryptonite-0.29...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1022:20 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:475:12 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.0.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.0.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.0.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.0.1.0:Distribution.Simple
  defaultMain, called at Setup.hs:2:8 in main:Main
Setup: Encountered missing or private dependencies:
integer-gmp -any
>
>builder for '/nix/store/71mady9rljq46mjh281hacvyg9gzb381-cryptonite-0.29.drv' failed with exit code 1
error: build of '/nix/store/71mady9rljq46mjh281hacvyg9gzb381-cryptonite-0.29.drv' on 'ssh-ng://nixos-shell' failed: builder for '/nix/store/71mady9rljq46mjh281hacvyg9gzb381-cryptonite-0.29.drv' failed with exit code 1
builder for '/nix/store/71mady9rljq46mjh281hacvyg9gzb381-cryptonite-0.29.drv' failed with exit code 1
cannot build derivation '/nix/store/7gb9wk0l42p2q2wnjdxjxkv8mnq5hrkn-dhall-1.39.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jh5h7msj8h32jwjhbzqqdfj2xwdfi43v-http-client-tls-0.3.5.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hphwzm672g1j8ddz7wv58ammjq2rfn03-tls-1.5.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1svsaqypr0qmjkyy440s38vn942fs2jy-wai-app-static-3.1.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/arch1bglq5xilb9m1dq8sjhddagv24ks-x509-1.7.5.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4s05qw4xjp2j6hxn858d0rmk92xjxc1k-x509-store-1.6.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p218r0dhdzv9xcbpb8f5h622k6kvh9br-x509-validation-1.6.11.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/v4h91cl6sm15vnjiya96g14gyzmwpi5r-neuron-1.0.0.0.drv': 1 dependencies couldn't be built

### Steps To Reproduce
1. build `with pkgs.haskell.packages.ghc884; with pkgs.haskell.compiler.ghc884;`

### Expected behavior
cryptonite builds

### Additional context
Also I am using the following in an overlay:
>@nh2 I just built a fairly complex program with TH using the static RTS trick and it worked smoothly.
This is the overlay I used:
```nix
  self: super:
  { haskell = self.lib.recursiveUpdate super.haskell
    { compiler.ghc8104 =
      (super.haskell.compiler.ghc8104.override
        { enableRelocatedStaticLibs = true;
          enableIntegerSimple = true;
          enableShared = false;
        }).overrideAttrs (old:
        { preConfigure = ''
            ${old.preConfigure or ""}
            echo "GhcLibHcOpts += -fPIC -fexternal-dynamic-refs" >> mk/build.mk
            echo "GhcRtsHcOpts += -fPIC -fexternal-dynamic-refs" >> mk/build.mk
          '';
        });
    };
  }
```
>Are there any downsides with a static RTS or can we just do that by default in `pkgsStatic`? 
Btw, it seems to work only in recent GHC versions, so it's not possible to apply it to all `haskell.compiler`s.

_Originally posted by @rnhmjoj in https://github.com/NixOS/nixpkgs/issues/61575#issuecomment-879403341_

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
unpacking 'http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz'...
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/spvp6hbgk3sn4xpjahvcd94xccnxp98i-bash-interactive-4.4-p23-dev
copying path '/nix/store/spvp6hbgk3sn4xpjahvcd94xccnxp98i-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.4, NixOS, 21.11pre304227.ecaf3da9340 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - nixpkgs: `/nix/store/wnsz270kl9aw3lah3cndhxssxnsv66i8-nixexprs.tar.xz`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by 573** [comment]
https://www.reddit.com/r/haskell/comments/g80zuu/comment/foqkvi8/

**Comment by rnhmjoj** [comment]
> When building cryptonite (used by neuron) with ghc884

Note that my overlay is overriding GHC 8.10, so it won't have any effect here.

I've tried to build it using GHC 8.8.4 on both on NixOS 21.05 and unstable and see no error:

$ nix build -f channel:nixos-unstable haskell.packages.ghc884.cryptonite
result → /nix/store/saxm51gx0vqjmzx1rk1xdmvqs9zqmwcg-cryptonite-0.28

$ nix build -f channel:nixos-21.05 haskell.packages.ghc884.cryptonite
result → /nix/store/r8sk1m71b5g3jgvglp3x8pdgc0w21bw0-cryptonite-0.29

**Comment by 573** [comment]
To be precise this is the overlay I'm using:

```nix
self: super: {
    haskell = self.lib.recursiveUpdate super.haskell
     { compiler.ghc884 =
       (super.haskell.compiler.ghc884.override
         { enableRelocatedStaticLibs = true;
           enableIntegerSimple = true;
           enableShared = false;
         }).overrideAttrs (old:
         { preConfigure = ''
             ${old.preConfigure or ""}
             echo "GhcLibHcOpts += -fPIC -fexternal-dynamic-refs" >> mk/build.mk
             echo "GhcRtsHcOpts += -fPIC -fexternal-dynamic-refs" >> mk/build.mk
           '';
         });

      packages.ghc884 =
       (super.haskell.packages.ghc884.override
         (old: { overrides = super.lib.composeExtensions (old.overrides or (_: _: {})) (hself: hsuper: rec {
          mkDerivation = args: hsuper.mkDerivation (args // {
            doCheck = false;
            doHaddock = false;
           enableLibraryProfiling = false;
        });
          });
       }));
      };
  }
```

> 
> When building cryptonite (used by neuron) with ghc884
> Note that my overlay is overriding GHC 8.10, so it won't have any effect here. I've tried to build it using GHC 8.8.4 on both on NixOS 21.05 and unstable and see no error: $ nix build -f channel:nixos-unstable haskell.packages.ghc884.cryptonite result → /nix/store/saxm51gx0vqjmzx1rk1xdmvqs9zqmwcg-cryptonite-0.28 $ nix build -f channel:nixos-21.05 haskell.packages.ghc884.cryptonite result → /nix/store/r8sk1m71b5g3jgvglp3x8pdgc0w21bw0-cryptonite-0.29

The issue is on a different end then so I'm preparing a minimal example of my environment. Thanks so far.

**Comment by 573** [comment]
This is what I'm using to reproduce the error:
```nix
# file shell.nix
{  sources ? import ./../../nix/sources.nix }:
with { overlay = _: pkgs:
    { niv = (import sources.niv {}).niv;
    };
  };
let
   nixpkgs = sources."nixpkgs-haskell-updates";

   pkgs = import nixpkgs {
     overlays = [
  (self: super: {
   haskell = self.lib.recursiveUpdate super.haskell
    { compiler.ghc884 =
      (super.haskell.compiler.ghc884.override
        { enableRelocatedStaticLibs = true;
          enableIntegerSimple = true;
          enableShared = false;
        }).overrideAttrs (old:
        { preConfigure = ''
            ${old.preConfigure or ""}
            echo "GhcLibHcOpts += -fPIC -fexternal-dynamic-refs" >> mk/build.mk
            echo "GhcRtsHcOpts += -fPIC -fexternal-dynamic-refs" >> mk/build.mk
          '';
        });
      packages.ghc884 =
      (super.haskell.packages.ghc884.override
        (old: { overrides = super.lib.composeExtensions (old.overrides or (_: _: {})) (hself: hsuper: rec {
        mkDerivation = args: hsuper.mkDerivation (args // {
          doCheck = false;
          doHaddock = false;
          enableLibraryProfiling = false;
        });
        });
      }));
    };
  })
    ]; config = {};
  };
in pkgs.mkShell {
  buildInputs = with pkgs.haskell.packages.ghc884; with pkgs.haskell.compiler.ghc884; [
    cryptonite
  ];
}
```
Calling
```console
NIX_PATH=nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz nix-shell --builders 'ssh-ng://nixos-shell' --argstr system x86_64-linux --show-trace --max-jobs 0
```
leads to
>Setup: Encountered missing or private dependencies:
integer-gmp -any
>
>builder for '/nix/store/7xvmdd1i7ck8knk0i74hjk7q6jjj545c-cryptonite-0.29.drv' failed with exit code 1
error: build of '/nix/store/7xvmdd1i7ck8knk0i74hjk7q6jjj545c-cryptonite-0.29.drv' on 'ssh-ng://nixos-shell' failed: builder for '/nix/store/7xvmdd1i7ck8knk0i74hjk7q6jjj545c-cryptonite-0.29.drv' failed with exit code 1
builder for '/nix/store/7xvmdd1i7ck8knk0i74hjk7q6jjj545c-cryptonite-0.29.drv' failed with exit code 1
error: build of '/nix/store/7xvmdd1i7ck8knk0i74hjk7q6jjj545c-cryptonite-0.29.drv' failed

**Comment by rnhmjoj** [comment]
With the recent changes I made cryptonite seems to build. On the unstable channel you just have to build: `pkgsStatic.haskellPackages.cryptonite`
