### ISSUE TITLE
wiki: ASUS M60J-JX041V

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13166]
https://nixos.org/wiki/ASUS_M60J-JX041V

Above configuration for "ASUS M60J-JX041V" should be moved into ``nixos-hardware`` repo.

ping @ehmry

**Comment by ehmry** [comment]
@garbas I can transfer ownership of nixos-hardware to the nixos group to make things easier.

**Comment by garbas** [comment]
@ehmry would be good yes. let me check if i have the permission to accept the transfer

**Comment by garbas** [comment]
@rbvermaa could you sync with @ehmry to tranfer [nixos-hardware](https://github.com/ehmry/nixos-hardware) repo to NixOS github organization?

**Comment by ehmry** [comment]
I have some rights in the nixos group but not enough to transfer the repo, someone could just create a new repo then clone and push, I don't think that would be too disruptive.

https://help.github.com/articles/transferring-a-repository/
