### ISSUE TITLE
nvidia-docker fails when intel-driver is used for xserver because libnvidia-ml.so.1 is not found

### ISSUE THREAD

**Issue by moritzschaefer** [NixOS/nixpkgs#131608]
### Describe the bug

I prefer to run linux/xserver with my integrated Intel GPU and only activate the Nvidia GPU for GPGPU computation tasks. This works fine, except when I try to run within docker:

Running `nvidia-docker run --gpus all <image> ` fails with error message.

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ERRO[0000] error waiting for container: context canceled
```

### Steps To Reproduce
1. Install nvidia drivers and nvidia-docker and use intel driver for graphical stuff
  ```
  services.xserver.videoDrivers = [ "intel" ];  # modesetting didn't help
  hardware.nvidiaOptimus.disable = true;
  boot.blacklistedKernelModules = [ "nouveau" "nvidia" ];  # bbswitch
  environment.systemPackages = [ pkgs.linuxPackages.nvidia_x11 ];
  virtualisation.docker.enable = true;
  virtualisation.docker.enableNvidia = true;
  hardware.opengl.driSupport32Bit = true;
  ```
2. Verify `nvidia-smi` works on the host
3. Run nvidia-docker run --gpus all hello-world

### Expected behavior

Docker container executes without errors.

### Additional context

- When running `nvidia-container-cli -k -d /dev/tty info` to get debugging information, the following error appears: **could not start driver service: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory**
- I enabled debugging in nvidia-docker by editiong config.toml (as described for example here https://github.com/NVIDIA/nvidia-container-toolkit/issues/183). The same error (missing libnvidia-ml.so.1) appears in the debug-log-file.
  - This error persists, even when manually adding the library like so `LD_LIBRARY_PATH=/nix/store/1xc59wwa5l3sqhwm0399f0dax1csgmma-nvidia-x11-460.73.01-5.10.50/lib/ nvidia-docker run --gpus all hello-world`
  - In contrast, adding the library manually to the nvidia-container-cli command, **does** rescue the call: `LD_LIBRARY_PATH=/nix/store/1xc59wwa5l3sqhwm0399f0dax1csgmma-nvidia-x11-460.73.01-5.10.50/lib/ nvidia-container-cli -k -d /dev/tty info` runs without errors.
- nvidia-smi works well on the host, listing my GPU and the following versions: `| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |`
- `nixpkgs/pkgs/applications/virtualization/libnvidia-container/default.nix` uses version 450.57 for nvidia-modprobe, however my nvidia-driver (nvidia-smi) shows version 460.73.01. Might this be an issue?
- A comment in `nixpkgs/pkgs/applications/virtualization/libnvidia-container/default.nix` states the following: 
>     # locations of nvidia-driver libraries are not resolved via ldconfig which
>     # doesn't get used on NixOS. Additional support binaries like nvidia-smi
>     # are not resolved via the environment PATH but via the derivation output
>     # path.
  which seems to be related to my issue. The patch-script (`Projects/nixpkgs/pkgs/applications/virtualization/libnvidia-container/libnvc-ldconfig-and-path-fixes.patch`) associated with the comment changes some paths to look for libraries, however these paths do not contain nvidia libraries on my system. 

### Notify maintainers

@cpcloud might have more insights?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[I] moritz@moxps ~> nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.50, NixOS, 21.05.20210721.63ee5cd (Okapi)`
 - multi-user?: `yes`
```
Note: nix-info does not terminate after printing these three lines. It is frozen..

**Comment by cpcloud** [comment]
@moritzschaefer Thanks for the report.

Couple of things:

1. I don't think the `hello-world` image (which is a `scratch` image with a single binary) has enough structure for `nvidia-docker` to work.
2. Setting `LD_LIBRARY_PATH=... nvidia-docker run ...` doesn't set `LD_LIBRARY_PATH` in the container. You need to run `nvidia-docker run -e LD_LIBRARY_PATH=...` for that.

Can you try running:

```
nvidia-docker run --gpus all nvidia/cuda:11.2.1-base-ubi7 nvidia-smi --list-gpus
```?

**Comment by cpcloud** [comment]
I think you're getting the error about `libnvidia-ml.so` because that's the library used to get information about available GPUs, so it's one of the first in the chain to be accessed.

**Comment by cpcloud** [comment]
In the meantime, I'm going to hunt around for documentation regarding the minimum image structure necessary for `nvidia-docker` to work.

**Comment by cpcloud** [comment]
FWIW the specific modprobe version is used because that's the version that `libnvidia-container` requires.

**Comment by moritzschaefer** [comment]
Hey @cpcloud. Thank you for the fast response. I think I just found the underlying problem: 

I was using intel driver for xserver, so nvidia-libraries were not linked to /run/opengl-driver/lib. However, the patch-script (`nixpkgs/pkgs/applications/virtualization/libnvidia-container/libnvc-ldconfig-and-path-fixes.patch`) makes nvidia-container to search for the libraries in /run/opengl-driver/lib...

Do you have an idea what would be the right way to fix this? 


Unfortunately, now that I found a workaround (which is using the nvidia driver for xserver instead of intel), the problem is still not resolved. Since it is another issue, I will open another GH issue for it though.

**Comment by cpcloud** [comment]
@moritzschaefer Have you enabled `opengl`? E.g.:

```
{ config, ... }:
let
  nvidia_x11 = config.boot.kernelPackages.nvidia_x11;
  nvidia_gl = nvidia_x11.out;
  nvidia_gl_32 = nvidia_x11.lib32;
in
{
  boot.extraModulePackages = [ nvidia_x11 ];
  environment.systemPackages = [ nvidia_x11 ];

  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = [ nvidia_gl ];
    extraPackages32 = [ nvidia_gl_32 ];
  };
}
```

**Comment by cpcloud** [comment]
Without enabling `opengl` the `/run/opengl-driver{,-32}/lib` directories won't get created.

**Comment by cpcloud** [comment]
@moritzschaefer FWIW, `hello-world` does not work for me, but basically anything with an FHS setup (or some equivalent mapping of symlinks from FHS into the nix store) works for me. Such images are the `cuda` images, and `busybox`.

**Comment by moritzschaefer** [comment]
Awesome! Adding the extraPackages solved the issue! Thank you so much. I had to workaround one additional [bug](https://github.com/NixOS/nixpkgs/issues/127146) and am now facing one final small issue:

`nvidia-smi `does not appear in the PATH of the "nvidia/cuda:11.2.1-base" image. Running 

```
[I] moritz@moxps ~> docker run -ti --gpus all -v '/run/current-system/sw/bin:/tmpbin/cuda:ro'  nvidia/cuda:11.2.1-base bash
root@b8e248d41320:/# find / | grep nvidia-smi
<no results
```

I'll quickly reboot with nvidia-drivers enabled for xserver to see if this works around the issue

**Comment by cpcloud** [comment]
Hm, I'm not sure. By what are those nvidia-docker paths created?

**Comment by moritzschaefer** [comment]
On the host it seems that the nvidia driver somehow exposes these nvidia tools on the folder /run/nvidia-docker/bin/. They are only found there if the xserver is run by nvidia.
They are also accessible from within /run/current-system/sw/bin and link to the nvidia-x11 package:

```
[I] moritz@moxps ~> ls -lh (which nvidia-smi)
lrwxrwxrwx 1 root root 91 Jan  1  1970 /run/current-system/sw/bin/nvidia-smi -> /nix/store/4c30y48knq77ns72312p8vvp59nvn0m0-nvidia-x11-460.73.01-5.10.50-bin/bin/nvidia-smi
```

The mechanism by which libnvidia-container loads these binaries (i.e. nvidia-smi and 4 others) into the running container, can be inferred from here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/libnvidia-container/libnvc-ldconfig-and-path-fixes.patch (note the use of the path /run/nvidia-docker/bin/)

That's all I understood as of now.

**Comment by moritzschaefer** [comment]
@cpcloud a fix could be as simple as this: https://github.com/moritzschaefer/nixpkgs/commit/1a66ed7605ccc98a1e2e487f41702fd3fe8eeac5
But I struggle to use it in my configuration.nix, because libnvidia-container is not used as package but via a `callPackage` call with a path to the libnvidia-container package (../applications/virtualization/libnvidia-container). 
There is no way to "overwrite files" in an overlay right?

The only way I see is to overwrite the function that uses libnvidia-container (it's the only place in nixpkgs where it is used):

```
    mkNvidiaContainerPkg = { name, containerRuntimePath, configTemplate, additionalPaths ? [] }:
      let
        nvidia-container-runtime = pkgs.callPackage "${inputs.nixpkgs}/pkgs/applications/virtualization/nvidia-container-runtime" {
          inherit containerRuntimePath configTemplate;
        };
      in pkgs.symlinkJoin {
        inherit name;
        paths = [
          # (callPackage ../applications/virtualization/libnvidia-container { })
          (pkgs.callPackage "${inputs.nixpkgs-local}pkgs/applications/virtualization/libnvidia-container" { })
          nvidia-container-runtime
          (pkgs.callPackage "${inputs.nixpkgs}/pkgs/applications/virtualization/nvidia-container-toolkit" {
            inherit nvidia-container-runtime;
          })
        ] ++ additionalPaths;
      };
```
However this leads to the following error: 

```
error: access to path '/nix/store/bj1nzaqccfrz917jb39bb1v472zmxspc-sourcepkgs/applications/virtualization/libnvidia-container' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)
```

**Comment by SuperSandro2000** [comment]
Please see the this comment for a fix https://github.com/NixOS/nixpkgs/pull/132655#issuecomment-1024491352
