### ISSUE TITLE
wiki: Lenovo Thinkpad Helix

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13172]
https://nixos.org/wiki/Lenovo_Thinkpad_Helix

Above configuration should be moved to [nixos-hardware](https://github.com/ehmry/nixos-hardware) repo.

ping @ehmry

**Comment by Profpatsch** [comment]
If I were to convert this into nixos-hardware, how would I encode the “Preparing to boot nixos” and “Hardware support” sections?

**Comment by ehmry** [comment]
This page I think we can just loose.

**Comment by garbas** [comment]
+1 there are not really valuable info i think.

@ehmry maybe we could have a list of tips and tricks in main readme? like the one in this document to turn off speaker kernel module. wouldn't be bad right?

**Comment by ehmry** [comment]
@garbas Done.

**Comment by ehmry** [comment]
I close now.
