### ISSUE TITLE
win-virtio out of date (0.1.141-1 -> 0.1.204-1)

### ISSUE THREAD

**Issue by eliasvasylenko** [NixOS/nixpkgs#131797]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: win-virtio

current version: 0.1.141-1
desired version: 0.1.204-1

###### Notify maintainers

maintainers: @lheckemann

###### Note for maintainers

Hi Linus, the original maintainer---Thomas Strobel---appears to be unavailable on GH, so I just tagged you since you made the last version update a few years ago. I'll submit a PR for this myself though.

**Comment by lheckemann** [comment]
Good catch :)

I think 0.1.141-1 was the stable version at the time, not sure if we want stable or latest? I don't really mind either way though.

**Comment by mikroskeem** [comment]
Why not package both?

**Comment by eliasvasylenko** [comment]
Good point. Using stable seems sensible in this case, it looks like very little time has elapsed between them anyway so I doubt there's much value in bumping to latest. I'll stick wit
