### ISSUE TITLE
wiki: Obsolete pages on wiki

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13180]
a checklist of pages that needs a second look if are really obsolete (mostly due to being landing pages or duplicated of already existing pages we are migrating):
- [ ] [Rough ideas](https://nixos.org/wiki/Rough_ideas)
- [ ] [Samba on nix](https://nixos.org/wiki/Samba_on_nix)
- [ ] [Nix(OS) Embedded](https://nixos.org/wiki/Nix%28OS%29_Embedded)
- [x] [Mercurial and nixos/nixpkgs](https://nixos.org/wiki/Mercurial_and_nixos/nixpkgs)
- [x] [Mercurial and Nix repositories](https://nixos.org/wiki/Mercurial_and_Nix_repositories)
- [x] [Die IRC Channels](https://nixos.org/wiki/Die_IRC_Channels)
- [x] [Main Page](https://nixos.org/wiki/Main_Page)
- [x] [Main Page Package Manager](https://nixos.org/wiki/Main_Page_Package_Manager)
- [x] [Main Page Contributing](https://nixos.org/wiki/Main_Page_Contributing)
- [x] [Main Page B](https://nixos.org/wiki/Main_Page_B)
- [x] [Main Page NixOS Desktop](https://nixos.org/wiki/Main_Page_NixOS_Desktop)
- [ ] [Fix gawk segfault on OSX 10.10](https://nixos.org/wiki/Fix_gawk_segfault_on_OSX_10.10)
- [x] [Gitit](https://nixos.org/wiki/Gitit)
- [ ] [Scanners](https://nixos.org/wiki/Scanners)
- [x] [Melanoma Treatment](https://nixos.org/wiki/Melanoma_Treatment)
- [x] [Step-By-Step Critical Elements Of free ads uk](https://nixos.org/wiki/Step-By-Step_Critical_Elements_Of_free_ads_uk)
- [x] [Test](https://nixos.org/wiki/Test)
- [x] [For The Uninitiated](https://nixos.org/wiki/For_The_Uninitiated)
- [ ] [HOWTO:idutils](https://nixos.org/wiki/HOWTO:idutils)
- [x] [Hauptseite](https://nixos.org/wiki/Hauptseite)
- [ ] [Help, I locked myself out!](https://nixos.org/wiki/Help,_I_locked_myself_out!)
- [x] [Sandbox](https://nixos.org/wiki/Sandbox)
- [ ] [How to add large files to the nix-store](https://nixos.org/wiki/How_to_add_large_files_to_the_nix-store)
- [x] [How to enable subpixel rendering in freetype](https://nixos.org/wiki/How_to_enable_subpixel_rendering_in_freetype)
- [x] [Nix Wiki](https://nixos.org/wiki/Nix_Wiki)
- [x] [Zh-CN:首页](https://nixos.org/wiki/Zh-CN:%E9%A6%96%E9%A1%B5)
- [x] [Programmieren mit NixOS](https://nixos.org/wiki/Programmieren_mit_NixOS)
- [x] [Using Profiles for Development Environments](https://nixos.org/wiki/Using_Profiles_for_Development_Environments)
- [x] [UDX Initiative](https://nixos.org/wiki/UDX_Initiative)
- [ ] [Ein Paket zu nixpkgs hinzufügen oder ändern](https://nixos.org/wiki/Ein_Paket_zu_nixpkgs_hinzuf%C3%BCgen_oder_%C3%A4ndern)

**Comment by garbas** [comment]
@zimbatm would you be able to look at the above pages to make sure i'm not removing to much

**Comment by zimbatm** [comment]
### Rough ideas
do we have a branding page with all the logos ? Could be nice to add the laser cutting template but no biggie:
```
Laser cutting template, can be used with formulor.de, ponoko.com or on any laser cutter: [p2-nix-snowflake.svg](http://dodoburgers.com/nixos/p2-nix-snowflake.svg) Two sheets can be used, one with dark blue transparent acrylic and another with blue fluorescent acrylic. The parts can then be assembled using an an acrylic adhesive such as Acrifix 192.
```

**Comment by zimbatm** [comment]
### Samba on Nix
Clarified our doc from the example: https://github.com/zimbatm/nixpkgs/commit/ac1e8819f67f89d3c20901b4cdbf11b25da573b5

**Comment by garbas** [comment]
@zimbatm https://github.com/NixOS/nixos-artwork

**Comment by vcunat** [comment]
I checked three spam pages; they're now empty and marked for deletion anyway.

**Comment by vcunat** [comment]
- There's no (useful) content in *sandbox*.
- *subpixel rendering*: it is enabled by default for quite a long time. We have `fonts.fontconfig.subpixel.*` options. The only still valid part of the content is that the technology might be patented, but I'm not sure if we should document that. Maybe a section listing patent risks... but personally I'm comfortable with EU not allowing SW patents.

**Comment by zimbatm** [comment]
@vcunat I already checked all the other pages in case you missed it. triple-checking is good obv.

**Comment by 7c6f434c** [comment]
I am not sure «Help, I locked myself out!» is obsolete

**Comment by garbas** [comment]
@7c6f434c good catch ... we should definitely mention this how to "unlock your nixos setup", any takers?

**Comment by vcunat** [comment]
@zimbatm: I didn't realize what you meant by *All the rest is good to go.*

**Comment by siddharthist** [comment]
"Using Profiles for Development Environments" is a link to "Develop software with unique profiles using Nix" which links to "Development Environments" which is covered by #13204.

**Comment by siddharthist** [comment]
I think the page "Nix Wiki" doesn't need to be migrated.

**Comment by garbas** [comment]
@siddhanathan tnx, marked them as done
