### ISSUE TITLE
intel-compute-runtime and intel-ocl are broken

### ISSUE THREAD

**Issue by Munksgaard** [NixOS/nixpkgs#131817]
### Describe the bug

After updating to the latest unstable, I can no longer run OpenCL programs on my Intel processor.

### Steps To Reproduce
1. Save the following program as `cl.c`:

```
#include <CL/cl.h>
#include <stdio.h>

int main() {
  // Find the number of platforms.
  cl_uint num_platforms = 0;
  clGetPlatformIDs(0, NULL, &num_platforms);

  printf("Got: %d\n", num_platforms);
  return 0;
}
```

2. Compile with `gcc -std=c99 -lm -lOpenCL cl.c -o cl` (requires opencl-headers)
3. Run with `./cl`

### Expected behavior

Before upgrading `cl` reported two devices. After upgrading it reports 0.

My `configuration.nix` contains the following:

```
  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-media-driver
      intel-ocl
      intel-compute-runtime
    ];
    driSupport32Bit = true;
  };
```

By using versions of `intel-ocl` and `intel-compute-runtime` from nixos-21.05 instead of nixos-unstable, I get the expected result.

### Notify maintainers

@gloaming @kierdavis 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11pre304626.8ecc61c91a5 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nix2105-21.05.1777.82151321eea, nixos-21.11pre304626.8ecc61c91a5, nixos-unstable"`
 - channels(munksgaard): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by r-burns** [comment]
The linked PR has hit master - can you confirm this is no longer an issue?

**Comment by Munksgaard** [comment]
It looks like it works, thanks @r-burns !
