### ISSUE TITLE
Asusctl

### ISSUE THREAD

**Issue by s4ptarshi** [NixOS/nixpkgs#131811]
**Project description**
It is a command line utility which adds features for asus laptops. For example graphics card switching, anime matrix control (for g14). fan control, keyboard backlight control, cpu boost control, profiles, fan curves and other stuff. It basically unlocks a lot of functionality for laptops and can be used for non asus laptops as well contrary to the name.

**Metadata**

* homepage URL:https://asus-linux.org/asusctl/
* source URL:https://gitlab.com/asus-linux/asusctl
* license: Mozilla Public License 2.0
* platforms: Linux

**Comment by bobvanderlinden** [comment]
I've made an PR to introduce the asusctl package as well as a NixOS module to run asusd. Can someone give this a try, I personally do not have Asus hardware to test it properly. You can find the PR here: https://github.com/NixOS/nixpkgs/pull/146751
