### ISSUE TITLE
wiki: Install/remove software

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13188]
https://nixos.org/wiki/Install/remove_software

**Comment by ericsagnes** [comment]
covered by http://nixos.org/nixos/manual/index.html#sec-package-management.

**Comment by spacefrogg** [comment]
A lot of details are missing from the manual compared to the wiki entry. Is there any attempt to cover the finer aspects of nix store mangling and information gathering in another section or different kind of manual? It would be a shame if these bits and pieces would be lost again. Especially a detailed overall picture is missing that connects the dots. E.g. what the special `/run/current-system/sw` garbage collector root has to do with finding out which software is currently installed on a nixos system.
