### ISSUE TITLE
wiki: Tips for learning the Nix expression language and debugging nix expressions

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13198]
https://nixos.org/wiki/Tips_for_learning_the_Nix_expression_language_and_debugging_nix_expressions

**Comment by siddharthist** [comment]
This wiki page just links to the [nixpill](http://lethalman.blogspot.it/search/label/nixpills) series of blog posts. Do we want a link to those in the nix manual? If so, should it go under [the section on the nix expression language](https://nixos.org/nix/manual/#ch-expression-language)?

**Comment by garbas** [comment]
@siddharthist we can look into nixpills once we migrated the wiki. especially to have some more tutorial-style documentation. closing this one
