### ISSUE TITLE
clojure out-of-date (1.10.3.855 -> 1.10.3.933)

### ISSUE THREAD

**Issue by puredanger** [NixOS/nixpkgs#131959]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: clojure

current version: 1.10.3.855
desired version: 1.10.3.933

###### Notify maintainers

maintainers: @jlesquembre @thiagokokada

###### Note for maintainers

Please tag this issue in your PR.

**Comment by thiagokokada** [comment]
Opened a PR: https://github.com/NixOS/nixpkgs/pull/131960
