### ISSUE TITLE
Packaging Request: DeepL Translator CLI (deepl-translator-cli)

### ISSUE THREAD

**Issue by jtrees** [NixOS/nixpkgs#131978]
**Project description**
deepl-translator-cli delivers text translation capabilities to your console, powered by DeepL.

**Metadata**

* homepage URL: https://www.deepl.com/translator
* source URL: https://github.com/vsetka/deepl-translator-cli
* license: mit
* platforms: linux*

\* It (most likely) runs on many platforms, but I am specifically interested in linux support.

**Comment by legendofmiracles** [comment]
It doesn't seem like the program works: https://github.com/vsetka/deepl-translator-cli/issues/3

**Comment by jtrees** [comment]
Oh. Thanks for pointing me to that. I did actually try packaging this with node2nix but I ran into precisely that bug. Being new to nix I presumed I made a mistake somewhere in the process.
