### ISSUE TITLE
pkgsCross.aarch64-multiplatform.containerd: fails with Exec format error 

### ISSUE THREAD

**Issue by TheDelus** [NixOS/nixpkgs#131964]
### Describe the bug
When trying to cross compile containerd for aarch64 the build process fails with: 

```
/nix/store/b45zavallnsvqwjs9wg9xw167jcs0935-bash-4.4-p23/bin/bash: ./gen_html: cannot execute binary file: Exec format error
```

### Steps To Reproduce
`nix-build https://github.com/NixOS/nixpkgs/archive/8ecc61c91a596df7d3293603a9c2384190c1b89a.tar.gz -A pkgsCross.aarch64-multiplatform.containerd`
or 
`nix-shell -p pkgsCross.aarch64-multiplatform.containerd`

### Notify maintainers
@offlinehacker
@vdemeester

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11pre304626.8ecc61c91a5 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(fabian): `""`
 - channels(root): `"nixos-21.11pre304626.8ecc61c91a5, nixpkgs-20.09pre240338.13209156c19"`
 - nixpkgs: `/nix/store/q866kxz71g9h1wjjfa1cb2xmapxhsnbm-nixpkgs-nixos-21.05-91903ceb294dbe63a696759bfba3d23ee667f2dc
 ```

**Comment by TheDelus** [comment]
So here are some more observations:

We can workaround this error by removing the build of man-pages with something like this

```diff
diff --git a/pkgs/applications/virtualization/containerd/default.nix b/pkgs/applications/virtualization/containerd/default.nix
index 0c44805bedd..c3a8f47355c 100644
--- a/pkgs/applications/virtualization/containerd/default.nix
+++ b/pkgs/applications/virtualization/containerd/default.nix
@@ -12,7 +12,7 @@ buildGoModule rec {
   pname = "containerd";
   version = "1.5.4";

-  outputs = [ "out" "man" ];
+  outputs = [ "out" ];

   src = fetchFromGitHub {
     owner = "containerd";
@@ -33,12 +33,11 @@ buildGoModule rec {

   buildPhase = ''
     patchShebangs .
-    make binaries man $buildFlags
+    make binaries $buildFlags
   '';

   installPhase = ''
     install -Dm555 bin/* -t $out/bin
-    installManPage man/*.[1-9]
     installShellCompletion --bash contrib/autocomplete/ctr
     installShellCompletion --zsh --name _ctr contrib/autocomplete/zsh_autocomplete
   '';
```
By removing the `man` target, this pacakge is cross compiling fine for aarch64. But there are still some more issues. When we inspect the executable of `pkgsCross.aarch64-multiplatform.containerd` with `file` the interpreter part looks strange.
```console
$ nix-shell -p pkgsCross.aarch64-multiplatform.containerd file
...
[nix-shell:~]$ file /nix/store/6grmgamc12498z93bdswlm53m2jkdph6-containerd-aarch64-unknown-linux-gnu-1.5.4/bin/containerd
/nix/store/6grmgamc12498z93bdswlm53m2jkdph6-containerd-aarch64-unknown-linux-gnu-1.5.4/bin/containerd: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=jagW-0GBmNbuoYkX0KKK/lScXLhvO6ukQZXdxrf-r/QxnTRjh8eD0ab-dh8A1p/bQEU2pDbwNZcJuzRGjp9, stripped
```

`interpreter /lib/ld-linux-aarch64.so.1` is definitely not correct. Executing the file on an aarch64 NixOS Linux results in `No such file or directory`.
We tracked that issue down to this commit: ccd81fc0b9044756379222a358d0ac1d5b1d9b7a
When we use an `nixpkgs` checkout earilier than this commit, the strange behavior is gone and the interpreter is set correctly.
We suspect that `buildGoModule` has problems when cross-compiling for aarch64 and linking dynamically.

Our suspicion is supported by that fact that cross-compiling `runc` for aarch64 has the same behavior with the faulty interpreter
```console
$ nix-shell -p pkgsCross.aarch64-multiplatform.runc file
...
[nix-shell:~]$ file /nix/store/j1m1bbb74rcripdhrr7lr70ls2sxwg3k-runc-aarch64-unknown-linux-gnu-1.0.1/bin/.runc-wrapped
/nix/store/j1m1bbb74rcripdhrr7lr70ls2sxwg3k-runc-aarch64-unknown-linux-gnu-1.0.1/bin/.runc-wrapped: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=eH8KkSw628xbsWkupdw_/AMc-DC8Gk26ZBLqP2cL8/cuiyDGSWbq0P3qQGuAEo/BvCsrMnP32PDIulcRZqq, not stripped
```
Using a checkout earlier than 3326c4bbec9a0e15dac36c0719f0fddfb559cb9a where the `runc` derivation switched to `buildGoModule` resolves the problem as well.

We digged around in [buildGoPackage](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-packages/generic/default.nix) and [buildGoModule](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-modules/generic/default.nix) and stumbled upon the fact, that in buildGoPackage the `GOARM` variable is set and in buildGoModule the variable is not present. But our knowledge of go is far to limited to come to any conclusions here. However the [documentation of Go for arm ](https://github.com/golang/go/wiki/GoArm) states:
`In cross compilation situations, it is recommended that you always set an appropriate GOARM value along with GOARCH.` 

Maybe @kalbasit or @flokli have some insights here.

**Comment by Artturin** [comment]
```
$ file ./result/bin/containerd
./result/bin/containerd: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /nix/store/4qp8ajjwcz5sf9hpqpccy12pc63kdi1j-glibc-aarch64-unknown-linux-gnu-2.37-8/lib/ld-linux-aarch64.so.1, for GNU/Linux 3.10.0, Go BuildID=aw9Xk2HVx-5WbLymPaot/1AwISf3v3zx2DIoi-Qp7/I73SKKHO8XYBgK38mi0c/WWh4W4itjzgOwyDRI7mW, stripped
```
looks fixed
