### ISSUE TITLE
wiki: Create and debug nix packages

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13202]
https://nixos.org/wiki/Create_and_debug_nix_packages

**Comment by mucaho** [comment]
I would also like to add this as an introductory paragraph:

---

If you quickly want to experiment on a new package, consider using `nix-shell default.nix --pure` to create an isolated environment. If you get errors for missing dependencies, extend your `default.nix` with those packages.
```nix
# example default.nix
{ pkgs ? import /path/to/your/nixpkgs/fork/root {}}:

let
  stdenv = pkgs.stdenv;
  libX11 = pkgs.xlibs.libX11;
  xproto = pkgs.xlibs.xproto;
  electron = pkgs.electron;
in
  stdenv.mkDerivation {
    name = "NAME-0.1";
    src = ./.;
    buildInputs = [ libX11 xproto electron ];
    inherit libX11;
  }
```
The isolated environment adds the `buildInput`'s executables to the `$PATH` environment variable:
```sh
electron --version
```

Additionally, this isolated environment propagates paths to other derivations, e.g. paths to shared libraries:
```sh
ls "$libX11/lib"
```

**Comment by siddharthist** [comment]
I don't think we need to migrate this wiki page, as we've already got the [Nixpkgs Contributor's Guide](https://nixos.org/wiki/Create_and_debug_nix_packages). We can open separate issues if we can think of improvements to that.
