### ISSUE TITLE
wiki: Docker

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13207]
https://nixos.org/wiki/Docker

@lethalman could you review if documentation from wiki is included in nixpkgs manual?

**Comment by adevore** [comment]
Note that the "Docker on NixOS" section should use users.extraUsers.<user>.extraGroups, not gpasswd.

**Comment by ericsagnes** [comment]
If moved, this probably should go in [docker module](https://github.com/NixOS/nixpkgs/blob/7475728593a49f09c4b7b959b15513aee38ab4b4/nixos/modules/virtualisation/docker.nix) `meta.doc`.

**Comment by garbas** [comment]
hmm ... i'm not sure there is something to migrate from here... i guess docker+btrfs might be interesting, but i don't see this being something for the manual.
