### ISSUE TITLE
Python application spends 5s on importing modules: it doesn't attempt to load pyc files

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#132023]
### Describe the bug
`numberstation` on my Pinephone takes ~7 seconds to load. Profiling shows ~5s of this is importing modules.

### Steps To Reproduce
1. Modify the wrapped numberstation script to run with `python -X importtime [...]`, and name the script `prof.sh`: https://paste.debian.net/1206021/
2. Execute:

```
$ ./prof.sh 2> importtimes.log
$ cat importtimes.log  | awk '{print $3}' | grep -E '^[0-9]+$' | awk '{sum += $1} END {print sum }'

5224074
```

i.e. this application spends 5s on imports.

https://pastebin.ubuntu.com/p/t9z6cXyXrD/ is my importtimes.log

### Expected behavior
I expected this importtimes to take <1-2s.

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
 - system: `"aarch64-linux"`
 - host os: `Linux 5.13.0, NixOS, 21.11pre-git (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixpkgs-21.11pre302356.2489eb5e451"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by tomfitzhenry** [comment]
I executed this via strace, and observed that the program:
* looks for pyc files
* doesn't use the pyc file that exists
* attempts to write a pyc file (which fails, since /nix/store is read-only)

Here's a smaller demo:

```
$ strace python3 -m datetime
[...]
newfstatat(AT_FDCWD, "/nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/datetime.py", {st_mode=S_IFREG|0444, st_size=89150, ...}, 0) = 0
newfstatat(AT_FDCWD, "/nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/datetime.py", {st_mode=S_IFREG|0444, st_size=89150, ...}, 0) = 0
openat(AT_FDCWD, "/nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/__pycache__/datetime.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/datetime.py", O_RDONLY|O_CLOEXEC) = 3
[...]

$ ls -lh /nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/__pycache__/*datetime*
-r--r--r-- 1 root root 56K Jan  1  1970 /nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/__pycache__/datetime.cpython-39.opt-1.pyc
-r--r--r-- 1 root root 48K Jan  1  1970 /nix/store/irfgaf0cnavd1j1g3l3w37ykd7nwp2r4-python3-3.9.5/lib/python3.9/__pycache__/datetime.cpython-39.opt-2.pyc
```

It looks like Python is unaware of the pyc files in `/nix/store`.

**Comment by FRidh** [comment]
Correct, see https://github.com/NixOS/nixpkgs/pull/120858.

**Comment by tomfitzhenry** [comment]
These look related:

* https://github.com/NixOS/nixpkgs/issues/118810
* https://github.com/NixOS/nixpkgs/commit/9d03ff52229f36ff4b4e9d0ee2db4a46b90512bb

**Comment by tomfitzhenry** [comment]
I have applied https://github.com/NixOS/nixpkgs/pull/120858 locally and observe loading python/datetime is 4x faster:

```
$ time python -m datetime

real	0m1.355s
user	0m1.218s
sys	0m0.072s

$ time python -m datetime

real	0m1.360s
user	0m1.256s
sys	0m0.064s

$ time /nix/store/fh9ryynx60szqb5ws8rl2hsq6q040i53-python3-3.9.5/bin/python3.9 -m datetime

real	0m0.352s
user	0m0.299s
sys	0m0.036s

$ time /nix/store/fh9ryynx60szqb5ws8rl2hsq6q040i53-python3-3.9.5/bin/python3.9 -m datetime

real	0m0.356s
user	0m0.287s
sys	0m0.053s
```

The absolute path python is the one that uses optimisations.

**Comment by tomfitzhenry** [comment]
With https://github.com/NixOS/nixpkgs/pull/120858, numberstation loads in ~4s, of which ~2.5s is import times: https://paste.ubuntu.com/p/4GpGf7Wj49/

```
$ cat importtime2.log  | awk '{print $3}' | grep -E '^[0-9]+$' | awk '{sum += $1} END {print sum }'
2551177
```

This is a good speed up: 5.2s on importing to 2.5s on importing.

**Comment by tomfitzhenry** [comment]
This is awaiting the promotion of https://github.com/NixOS/nixpkgs/pull/120858 to `master` per https://nixos.org/manual/nixpkgs/stable/#idm140737315846416 . It should be in the staging-next after https://github.com/NixOS/nixpkgs/pull/131928 .

**Comment by jonringer** [comment]
> numberstation on my Pinephone

running NixOS on a pinephone? awesome! :)

**Comment by tomfitzhenry** [comment]
> running NixOS on a pinephone? awesome! :)

There are dozens of us! https://nixos.wiki/wiki/PinePhone

Thanks @samueldr for https://mobile.nixos.org/ !

**Comment by tomfitzhenry** [comment]
> This is awaiting the promotion of #120858 to master

I just found this site, for tracking progress of PRs: https://nixpk.gs/pr-tracker.html?pr=120858

**Comment by tomfitzhenry** [comment]
https://github.com/NixOS/nixpkgs/pull/120858 has been merged to master, and I can confirm `numberstation` on my Pinephone is now starting in 4s rather than 7s.
