### ISSUE TITLE
wiki: Fish

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13223]
https://nixos.org/wiki/Fish

**Comment by jgillich** [comment]
Dibs.

**Comment by andrewrk** [comment]
Heads up, the wiki is wrong. Fish works out of the box like this:

```
programs.fish.enable = true;
users.defaultUserShell = "/run/current-system/sw/bin/fish";
```

**Comment by garbas** [comment]
i guess we can close this then. thx @andrewrk

**Comment by Pszek** [comment]
PATH="$PATH:$HOME/.nix-profile/etc/profile.d/*
^^ This is a bash version. What is the transpiled, correct fish version?

**Comment by RubenSandwich** [comment]
@andrewrk I'm new to Nix can you tell me where those changes need to be made? I use fish as my default shell and cannot get Nix to work. However, I can get it to work in bash perfectly fine.
