### ISSUE TITLE
Qtwebkit 5.12 is broken

### ISSUE THREAD

**Issue by jaen** [NixOS/nixpkgs#132208]
The `plex-media-player` build is failing due to failure in `libsForQt512.qt5.qtwebengine.x86_64-linux` build, it appears to be some kind of linking failure (see [here](https://hydra.nixos.org/build/149084164/nixlog/1/tail)) but I'm not sure what to do about it offhand.

I've found a bug report for a similar failure to Fedora, if it helps: https://bugzilla.redhat.com/show_bug.cgi?id=1916925

Also the first failing build (see [here](https://hydra.nixos.org/build/147394808)) seems to have glibc bump in it's diff, could be potentially related.

### Steps To Reproduce
1. try to install `plex-media-player`
2. fail to hit the cache
3. fail to compile the package

### Expected behavior
Have a working `plex-media-player` package installed.

### Notify maintainers
@qknight
@ttuegel
@periklis
@bkchr

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/3h27w2frml5vyim2sgadgc6z3bas19gv-nix-info
copying path '/nix/store/3h27w2frml5vyim2sgadgc6z3bas19gv-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.3, NixOS, 21.11.20210727.8ecc61c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ttuegel** [comment]
It looks like we need [this patch](https://src.fedoraproject.org/rpms/binutils/c/b6ef4610525f26edea77034d75844389a20aadbc?branch=f33) for `binutils`, or to update that package.

**Comment by jaen** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/134195
