### ISSUE TITLE
wiki: How to get a chroot close enough to LSB for impure binary packages to work

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13227]
https://nixos.org/wiki/How_to_get_a_chroot_close_enough_to_LSB_for_impure_binary_packages_to_work

**Comment by 7c6f434c** [comment]
Hopefully completely obsoleted by `buildFHSEnv`

**Comment by garbas** [comment]
@7c6f434 would you be able to read the wiki page and move it to documentation or if is obsolete close it. basically i'm asking if you have time to work on this ticket. if you stop halfway just write in a comment what you discovered.

**Comment by 7c6f434c** [comment]
Obsolete, so closing the issue.
