### ISSUE TITLE
wiki: Fonts

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13225]
https://nixos.org/wiki/Fonts

**Comment by siddharthist** [comment]
Where would be a good place for this information in the manual?

**Comment by garbas** [comment]
i'm not 100% myself but i see 2 options:

- create new section between **8. File Systems** and **9. X Window System** called **Fonts**
- or add documentation to nixos options via ``meta.doc``

in any case it would be wise to look into what fonts options we currently support -> https://github.com/NixOS/nixpkgs/tree/master/nixos/modules/config/fonts

i'm leaning more towards second option since i don't seem to see enough documentation being needed and i found documentation that we put into nixos options actually really gets read by ppl looking for specific stuff.

@siddharthist what is your opinion?

**Comment by masaeedu** [comment]
Is there a place I can find the old fonts article? The [current fonts article](https://nixos.wiki/wiki/Fonts) consists of the following:

> **What font names can be used in `fonts.fontconfig.defaultFonts.monospace`?**
> Those that fontconfig will understand. This can be queried from a font file using `fc-query`.
> ```bash
> cd /nix/var/nix/profiles/system/sw/share/X11-fonts
> fc-query DejaVuSans.ttf | grep '^\s\+family:' | cut -d'"' -f2
> ```

Which doesn't make any sense to me as n00b.
