### ISSUE TITLE
wiki: Using the ZSH SHELL

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13224]
https://nixos.org/wiki/Using_the_ZSH_SHELL

**Comment by siddharthist** [comment]
How can I contribute to this issue? Where should this documentation go?

**Comment by garbas** [comment]
@siddhanathan thank for looking at this documentation tickets.

 it should go under [chapter 8 of nixpkgs manual](http://nixos.org/nixpkgs/manual/#chap-package-notes)

**Comment by siddharthist** [comment]
@garbas Ofc, my pleasure!

This isn't the right place for this question (so please redirect me), but does everything really belong in the manual? It seems like the manual is already too big to load as one webpage.

**Comment by garbas** [comment]
@siddharthist you are right, not everything belongs to a manual. for now this is the only place we have. and we would like to migrate away from wiki, but there are many things that are useful there. for this purpose we will first migrate everything to manual's and then see how we can re-arrange manuals to be more approachable. makes sense?

**Comment by siddharthist** [comment]
@garbas It seems that this approach will make two migrations out of one, but if that's the way it's being done, so be it. I'm happy to help where I can!

**Comment by garbas** [comment]
@siddharthist that second "migration" you are talking about is going to be more of reorganization of existing documentation.

**Comment by siddharthist** [comment]
@garbas Actually, Chapter 8 looks to be more about the details of compiling/packaging certain pkgs, whereas this wiki page covers usage in nixos. Maybe somewhere under `nixos/doc` would make more sense?

**Comment by ericsagnes** [comment]
This wiki page content is pretty thin. 
IMHO, all of it says says is already in the option descriptions for `programs.zsh.enable`, `users.users.<name?>.shell` and `users.defaultUserShell`.

Maybe adding references to `users.users.<name?>.shell` and `users.defaultUserShell` to `programs.zsh.enable` could be useful for newcomers, eg:

> Whether to configure zsh as an interactive shell. To enable zsh for a particular user, use the `users.users.<name?>.shell` option for that user. To enable zsh system-wide use the `users.defaultUserShell` option.

**Comment by P-E-Meunier** [comment]
Wait, a possible source of confusion here is when you want to `nix-shell`. It would save people a lot of time if beginners were warned that they can't use `zsh` in `nix-shell`, right in the zsh page.

**Comment by siddharthist** [comment]
@P-E-Meunier `nix-shell --run "exec zsh"`

**Comment by siddhanathan** [comment]
@siddharthist Maybe that should be documented somewhere?
