### ISSUE TITLE
wiki: Firefox and Java in Firefox

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13221]
https://nixos.org/wiki/Firefox
https://nixos.org/wiki/Java_in_Firefox

**Comment by siddharthist** [comment]
So for the NixOS manual, we have Appendix A, which lists and documents each configuration option. Is there no such documentation for `nixpkgs.config`?

**Comment by vcunat** [comment]
No. Note that for nixos options it's automatically generated, but that's not possible for nixpkgs options as they're now.

I'd personally like to see some convergence on these, over the long term, perhaps in spirit of https://github.com/NixOS/nixpkgs/pull/9250.
