### ISSUE TITLE
darwin: gtk3-x11 is built without X11 support

### ISSUE THREAD

**Issue by smancill** [NixOS/nixpkgs#132259]
### Describe the bug

`gtk3-x11` is built without X11 support on darwin because the Meson build file disables it.

### Steps To Reproduce

The GTK build system was changed to Meson by 638c39e65bce5adcea7b7bebf3586c7ee371563f, and it removed the configure flags that enabled X11 on darwin:

``` diff
-  configureFlags = optional stdenv.isDarwin [
-    "--disable-debug"
-    "--disable-dependency-tracking"
-    "--disable-glibtest"
-  ] ++ optional (stdenv.isDarwin && !x11Support)
-    "--enable-quartz-backend"
-    ++ optional x11Support [
-    "--enable-x11-backend"
-  ] ++ optional waylandSupport [
-    "--enable-wayland-backend"
-  ];
```

But the `meson.build` file of GTK3 disables X11 support on darwin, and [it is harcoded](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/meson.build#L155-160):

``` meson
if os_darwin
  wayland_enabled = false
  x11_enabled = false
else
  quartz_enabled = false
endif 
```

### Expected behavior

`gtk3-x11` should provide X11 support on darwin.

### Additional context

I was trying to fix `pympress` on darwin and I found that `libcanberra-gtk3` is marked as broken (806d814516c14853e7dae37eb9a59c96db557786) because of a missing GKT/X11 header.

It seems that it is the same problem that motivated #82097 to change Vim to use "gtk2" (same missing header `gdk/gdkx.h`).

### Notify maintainers

@hedning @jtojnar @dasj19 @maxeaubrey

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(smancill): `"nixpkgs-21.05pre293250.c8569c32bac, unstable-21.11pre304227.ecaf3da9340"`
 - nixpkgs: `/Users/smancill/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- gtk3-x11
- libcanberra-gtk3
- vim_configurable
# a list of nixos modules affected by the problem
module:
```

**Comment by vcunat** [comment]
> But the meson.build file of GTK3 disables X11 support on darwin, and it is harcoded:

In that case I'd probably take the discussion upstream.

**Comment by smancill** [comment]
It was reenabled by this commit: https://gitlab.gnome.org/GNOME/gtk/-/commit/f922109a9c684d1fb852b041eccbeb4781b7039a

Maybe it can be patched.

**Comment by smancill** [comment]
It was disabled in 3.24.9 by commit https://gitlab.gnome.org/GNOME/gtk/-/commit/9109efb19e4bc92a81ad972f938856c6d6bf01f8, but that commit never landed into master and GTK 4.x does build with X11 support as I understand (https://gitlab.gnome.org/GNOME/gtk/-/blob/master/meson.build#L96-124 and https://gitlab.gnome.org/GNOME/gtk/-/blob/master/meson_options.txt#L3-6).

**Comment by Artturin** [comment]
#132239
