### ISSUE TITLE
wiki: Vim configuration and Vim plugins

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13234]
https://nixos.org/wiki/Vim_configuration
https://nixos.org/wiki/Vim_plugins

**Comment by ericsagnes** [comment]
Documented in https://github.com/NixOS/nixpkgs/blob/7475728593a49f09c4b7b959b15513aee38ab4b4/pkgs/misc/vim-plugins/vim-utils.nix#L6-L136, should be moved to an easier to find place.

**Comment by jagajaga** [comment]
It's here : https://nixos.org/wiki/Vim_plugins

**Comment by ericsagnes** [comment]
Isn't the whole point of this issue to move that *out* of the wiki? :)

**Comment by jagajaga** [comment]
@ericsagnes yes, but the thing is that the initial moving out of vim pages wasn't done yet :(

**Comment by nicknovitski** [comment]
Was this addressed by #16501?

**Comment by garbas** [comment]
@nicknovitski 👍 tnx for pointing out.

**Comment by nicknovitski** [comment]
To be honest, I'm not sure if it was.  Where does that `vim.md` file get published?  It's not visible in https://nixos.org/nixpkgs/manual/.

**Comment by vcunat** [comment]
@nicknovitski: that URL follows 16.09 but most changes are only merged to master.
