### ISSUE TITLE
Form Xfce maintainer team

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#132370]
## Issue description

worldofpeace was previously maintainer of xfce und now there is no maintainer for most parts

https://github.com/NixOS/nixpkgs/pull/121780

if you care about xfce on nixos, you should form a maintainer team like i do with https://github.com/NixOS/nixpkgs/issues/121827 for pantheon

## Technical details

- [x] Create GitHub Team ([Xfce](https://github.com/orgs/NixOS/teams/xfce))
- [x] Create a Label for all known issues ([6.topic: xfce](https://github.com/NixOS/nixpkgs/labels/6.topic%3A%20xfce))
- [x] Create a GitHub Project (kanban board) ([Xfce](https://github.com/NixOS/nixpkgs/projects/47))
- [x] Create team in `maintainers/team-list.nix` (https://github.com/NixOS/nixpkgs/pull/147797)
- [ ]  Add more maintainers

_Edited to include details_

**Comment by romildo** [comment]
Can we go ahead and form the Xfce team?

**Comment by romildo** [comment]
@davidak @jtojnar
I am creating a Project for Xfce in the nixpkgs repository. Which Project Template should be used: _None_, _Basic kanban_, _Automated kanban_, _Automated kanban with reviews_, or _Bug triage_ ?

**Comment by jtojnar** [comment]
For [the main project](https://github.com/NixOS/nixpkgs/projects/12), we use _Automated kanban_ + extra “Ready to review” column. For versions, we use _Automated kanban_ + extra “Nice to have” column (To-do but not a merge blocker).

What project organization you want to choose depends on your workflow.

**Comment by bobby285271** [comment]
>  Add more maintainers

There are 3 members now and xfce is [very up to date](https://repology.org/projects/?search=&maintainer=&category=xfce&inrepo=nix_unstable&notinrepo=&repos=&families=&repos_newest=&families_newest=&outdated=on), assuming this is done
