### ISSUE TITLE
Shutter fails to build.

### ISSUE THREAD

**Issue by yisraeldov** [NixOS/nixpkgs#132324]
### Describe the bug
Shutter fails to build, looks like an issue with Imagemagick.

### Steps To Reproduce
1. `nix-shell -p shutter`

### Expected behavior
Expect that it should build, it was working on my last generation.

### Notify maintainers

@bjornfor
### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.4, NixOS, 21.05.1970.11c662074e2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.1970.11c662074e2, home-manager-21.05, nixos-unstable-21.11pre304061.dd14e5d78e9"`
 - channels(yisraeldov): `"nixos-21.05.1669.973910f5c31"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```
Probably related to #132237

**Comment by bjornfor** [comment]
'shutter' is outdated in nixpkgs, perhaps we should start with a package update.

**Comment by yisraeldov** [comment]
That would be nice but I think the problem is due to changes in perl packages

*From: *Bjørn Forsman ***@***.***>
*To: *NixOS/nixpkgs ***@***.***>
*CC: *Yisrael Dov Lebow ***@***.***>; Author ***@***.***>
*Received: *Aug 1, 2021 20:58:43
*Subject: *Re: [NixOS/nixpkgs] Shutter fails to build. (#132324)

**Comment by Artturin** [comment]
i tested and #132237 fixes this

**Comment by Artturin** [comment]
> 'shutter' is outdated in nixpkgs, perhaps we should start with a package update.

I'll update shutter but will make the pr after the above pr has been merged

**Comment by Artturin** [comment]
#132565
