### ISSUE TITLE
Deprecate FeedReader

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#132371]
### Describe the bug

>This project is no longer activily maintained!

https://github.com/jangernert/FeedReader/#readme

there is a spiritual successor, so maybe package that instead

https://gitlab.com/news-flash/news_flash_gtk

cc maintainer @edwtjo

**Comment by BentonEdmondson** [comment]
> there is a spiritual successor, so maybe package that instead

https://search.nixos.org/packages?channel=unstable&show=newsflash&from=0&size=50&sort=relevance&query=newsflash
