### ISSUE TITLE
Packaging request: Autosuspend

### ISSUE THREAD

**Issue by maggicl** [NixOS/nixpkgs#132392]
**Project description**
`autosuspend` is a python daemon that suspends a system if certain conditions are met, or not met. This enables a server to sleep in case of inactivity without depending on the X infrastructure usually used by normal desktop environments.

**Metadata**

* homepage URL: https://autosuspend.readthedocs.io/en/latest/
* source URL: https://github.com/languitar/autosuspend
* license: gpl2
* platforms: linux

**Comment by maggicl** [comment]
I already have wrote a derivation and a module for this service, and I will soon open a pull request

**Comment by abathur** [comment]
It looks like this was added in:
- https://github.com/NixOS/nixpkgs/pull/140532
