### ISSUE TITLE
neovim's checkhealth returns an error for perl

### ISSUE THREAD

**Issue by wizardwatch** [NixOS/nixpkgs#132368]
### Describe the bug
When you run checkhealth inside neovim it returns an error, "Neovim::Ext" cpan module is not installed, for the perl provider. While that particular perl module is not packaged given there is no previously reported issue I would assume this is a regression, many packaged vim extensions applications rely on perl support. 

### Steps To Reproduce
1. Install neovim (I am using home-manager but it seems to be reproducible no matter the method of install.)
2. run :checkhealth

### Expected behavior
Test passes

### Notify maintainers
@manveru
@rvolosatovs 
@ma27

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11.20210727.8ecc61c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(wyatt): `"nixos-21.05pre281538.9e377a6ce42"`
 - channels(root): `"nixos-21.05pre290427.673aea9f84c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by rvolosatovs** [comment]
For context, this is the exact error, which I can reproduce locally with `:checkhealth`
```
## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
```

I don't think it was ever there, but I may be wrong.

It seems that to make this work we'd need to make a `perl` environment with `Neovim::Ext` package available to the executable at runtime.

I believe that would mean we should package https://github.com/jacquesg/p5-Neovim-Ext, which has not been updated in almost a year (last commit in `master` is dated Sep 6, 2020 https://github.com/jacquesg/p5-Neovim-Ext/commit/44e0b15b65a32397d2e77cbd59f2591935787f0f), which may or may not mean it is abandoned.

There are also quite a few issues upstream about this particular warning https://github.com/neovim/neovim/issues/15130 https://github.com/neovim/neovim/issues/15006 (more in history)

Given the above and the fact that there indeed were no complains about this I lean towards saying that the this is not worth doing at this point of time, especially given that modern neovim plugins are encouraged to use lua or other scripting languages, which are already there.

If you insist that we indeed need it, probably we should implement it in the same way as python or node is handled already in the derivation, so this would be an opt-in `withPerl` with a possible `perlPackages`. 

@teto you probably have the most context here, maybe you could give some insights here?

**Comment by teto** [comment]
You are on point :) I will try to change the Error to a warning upstream so that it's less stressful. As for nixpkgs, if no one is using a perl plugin, there is no reason ti implement this. I dont know of any perl plugin but if there is a provider there must be one ?! maybe check the other repos of the provider author. But right now the lua plugins are the hot stuff indeed.

**Comment by teto** [comment]
looks good now, feel free to reopen
