### ISSUE TITLE
evaluation error blocking nixos-unstable

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#132328]
> error: [json.exception.type_error.302] type must be string, but is null

https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

It's not the first time we had a similar one.  I consider them hard to track to their cause.

The channel has been blocked for a different reason for several days already (~5 days old now), so this is quite unpleasant.

**Comment by lukegb** [comment]
Tracked it down using

`git bisect run env HYDRA_CONFIG=/home/lukegb/hydra.conf /nix/store/9j98yw8hjyd86pkdi25radxbbz2im7g9-hydra-0.1.19700101.4e94551/bin/hydra-eval-jobs --gc-roots-dir /home/lukegb/gcroots ./nixos/release-combined.nix -I nixpkgs=/home/lukegb/nixpkgs --arg stableBranch false`

```
...
error: [json.exception.type_error.302] type must be string, but is null
a6700d75f38cda83367a8af84651a2a72ce0f3ef is the first bad commit
commit a6700d75f38cda83367a8af84651a2a72ce0f3ef
Author: lassulus <lassulus@lassul.us>
Date:   Sat Jul 24 09:33:10 2021 +0200

    vbox-image: add new option to set free space in image

 nixos/modules/virtualisation/virtualbox-image.nix | 8 ++++++++
 1 file changed, 8 insertions(+)
bisect run success
```
