### ISSUE TITLE
wiki: Steam

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13237]
https://nixos.org/wiki/Steam

**Comment by rdesfo** [comment]
Would it be possible to add a steam controller section to the steam wiki page?  I was able to get the controller to work with nixos by adding the following lines to **/etc/nixos/configuration.nix**

``` nix
  services.udev.extraRules = ''
    SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
    KERNEL=="uinput", MODE="0660", GROUP="users", OPTIONS+="static_node=uinput"
  '';
```

**Comment by vcunat** [comment]
Probably not to the wiki, as it's read-only and being phased out to "official" documentation. This ticket is meant to track doing so for this particular page, so it's a good temporary location for your piece of information.

**Comment by xvapx** [comment]
I would like to point anybody with the steam radeon problem: 

    libGL error: unable to load driver: radeonsi_dri.so
    libGL error: driver pointer missing
    libGL error: failed to load driver: radeonsi
    libGL error: unable to load driver: swrast_dri.so
    libGL error: failed to load driver: swrast
to [this comment](https://github.com/NixOS/nixpkgs/issues/10950#issuecomment-239501421), as it has current info on how to solve it, while the info on the wiki is outdated.

**Comment by garbas** [comment]
@xvapx would you have time to add some documentation about steam (and how to troubleshoot) to nixpkgs manual?

**Comment by xvapx** [comment]
Yes, i will gladly do it.

**Comment by vcunat** [comment]
Yes, either another section or overload the [languages/frameworks](http://nixos.org/nixpkgs/manual/#chap-language-support) section.

**Comment by xvapx** [comment]
Ok, well i was speaking about the wrong manual, just noticed there is a NixOS manual and a Nixpkgs one, so i'm making progress...
I suppose i can use the 'package notes' chapter provisionally and when i have something to share i can ask about a definitive place before making the pull request.
Thanks a lot!

**Comment by corngood** [comment]
Anyone getting something like:

```
steam.sh: line 713: 7842 Segmentation fault (core dumped) 
```

with the radeon open source drivers, there's a potential fix in #20269.

**Comment by siddharthist** [comment]
Looks like a PR was merged for this (actually, maybe even a few). Any reason to keep it open?

**Comment by xvapx** [comment]
I don't think so.
