### ISSUE TITLE
Option programs.neovim.enable is broken by hardcoded script path

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#132389]
### Describe the bug
`programs.neovim.enable = true;` in `configuration.nix` will cause an error:
```nix
error: getting status of '/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/make-etc.sh': No such file or directory
```

After digging in trace message, I found the [hardcoded](https://github.com/NixOS/nixpkgs/blob/nixos-unstable-small/nixos/modules/programs/neovim.nix#L14) `make-etc.sh` script is modified 2 days ago: https://github.com/NixOS/nixpkgs/pull/131102

So this issue is just a notification to the module maintainer,
because I'm not found another personal contract.

### Steps To Reproduce
1. Adding `programs.neovim.enable = true;` to NixOS system configuration file. (The only option neovim related)
2. Do `nixos-rebuild switch` or something else to activate the configuration.

### Notify maintainers
@teto 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.7-zen1, NixOS, 21.11pre305784.151c2f5a20c (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre305784.151c2f5a20c"`
 - channels(vanilla): `"home-manager, nixpkgs-21.11pre304626.8ecc61c91a5"`
 - nixpkgs: `/home/vanilla/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Infinisil** [comment]
Ping @dasJ @Mic92

**Comment by dasJ** [comment]
Wow that's a regression I surely didn't see coming…

Looking at this, can't we just replace this with a [linkFarm](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/trivial-builders.nix#L341)?
That way we wouldn't have a random module depending on the internals of make-etc

**Comment by dasJ** [comment]
Draft PR that does this: https://github.com/NixOS/nixpkgs/pull/132522
