### ISSUE TITLE
Modprobe completion doesn't work in zsh

### ISSUE THREAD

**Issue by kurnevsky** [NixOS/nixpkgs#132387]
### Describe the bug
`modprobe` completion is broken in zsh.

### Steps To Reproduce
Type `modprobe ` and then press TAB (or whatever triggers completion). You will see:
```
➜ modprobe
_modutils:102: no such file or directory: /lib/modules/5.13.5-zen1/modules.alias
_modutils:102: no such file or directory: /lib/modules/5.13.5-zen1/modules.alias
_modutils:102: no such file or directory: /lib/modules/5.13.5-zen1/modules.alias
```

### Expected behavior
Completion shows list of available modules.

### Notify maintainers
@pSub

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.5-zen1, NixOS, 21.05.20210731.11c6620 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.05.1970.11c662074e2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
this is fixed in zsh master :D 
https://github.com/zsh-users/zsh/commit/02f62e5d21e09d4936e18147119b1f0c85b93d79

**Comment by kurnevsky** [comment]
Thanks! No releases since then unfortunately. Closing this, but feel free to reopen if you think it should be backported to nix :)
