### ISSUE TITLE
wiki: Pidgin with OTR

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13248]
https://nixos.org/wiki/Pidgin_with_OTR

**Comment by castilma** [comment]
this link is dead

**Comment by disassembler** [comment]
Yes, this is a move the wiki issue. Can you please document what you did to get this working on nixos.wiki (the new wiki)? It would help others experiencing similar issues.

**Comment by castilma** [comment]
[done](https://nixos.wiki/wiki/Pidgin_with_OTR)

**Comment by vcunat** [comment]
@globin: so (most in) this milestone can be closed when the content was just moved and we carry on with wiki instead of the original plan?
