### ISSUE TITLE
docs: add TeX Live howto into nixpkgs manual

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13240]
https://nixos.org/wiki/TexLive_HOWTO

**Comment by 7c6f434c** [comment]
Most of the article is about an obsolete TeXLive packaging, the bottom section about the new TeXLive infrastructure could be merged into `8. Package Notes` Nixpkgs manual chapter.

**Comment by garbas** [comment]
@vcunat i see you're the author of ``texlive-new`` (please correct me if i'm wrong) ... would you be able to document it? and also what is the relationg to ``texlive``

**Comment by 7c6f434c** [comment]
New TeXLive infrastructure (as described in the last section) is currently just `texlive` (all-lowercase).

I would vote for copy-pasting the bottom section from the Wiki page to the manual and improving it later, but maybe there are some objections.

**Comment by vcunat** [comment]
There's a simple user doc in https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L1 but I think it should be polished and moved to the nixpkgs manual, preferably before release. I should be able to do it, but feel free to start before me.

**Comment by domenkozar** [comment]
Who's going to fix this for 16.03?
