### ISSUE TITLE
Glimpse fails to launch: "GEGL operation missing"

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#132405]
### Describe the bug
Installing `glimpse` results in a broken application that exits on startup with the message "GEGL operation missing! Glimpse requires the GEGL operation "gegl:introspect". This operation cannot be found. Check your GEGL install and ensure it has been compiled with any dependencies required for Glimpse."

### Steps To Reproduce
1. Add `pkgs.glimpse` to `environment.systemPackages`
2. `sudo nixos-rebuild switch`
3. Run Glimpse

### Expected behavior
Glimpse should work!

### Additional context
`gimp` works fine for me.

### Notify maintainers

@ashkitten @erictapen

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.1970.11c662074e2 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(ash): `"home-manager-21.05"`
 - channels(root): `"nixos-21.05.1970.11c662074e2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by erictapen** [comment]
Thanks for the report, @sersorrel. Unfortunately I cannot reproduce your issue. Neither on `11c662074e2ae3dddd7e157918b6981de4ce7857` as you reported nor on current `nixos-unstable`.

Could you elaborate on your setup a bit? Which window manager/desktop environment are you using? Is it possible that you modified glimpse in an overlay?

I'm running Sway (Wayland) and deleted `~/.config/Glimpse` and `~/.cache/glimpse` before testing to make sure I didn't have any leftover state in my home directory.

**Comment by sersorrel** [comment]
I'm using i3wm (with no separate desktop manager); I installed Glimpse by adding it to environment.systemPackages in `/etc/nixos/configuration.nix`, I don't think there's any chance I did anything special with overlays there. I can't think of anything else I've done that might have affected this – I only installed NixOS a few days ago. I do have Home Manager installed, so I guess is it possible that something I've installed via that is causing a problem? (I don't have that much stuff installed, though, I don't think.) `/` on my system is a tmpfs, so if something put a file outside of /nix or /home on install and is expecting it to still be there then it'll be unhappy, but I think I tried running Glimpse immediately after installing it with `nixos-rebuild switch` and it didn't work even then, so it shouldn't be anything related to that.

Deleting `~/.config/Glimpse` changes the icon in the popup, which is weird, it looks like this if that directory isn't present at statup:

![image](https://user-images.githubusercontent.com/9433472/128081643-003140e0-d1f3-4ec2-9530-ee1d24cbb6d8.png)

and like this if I leave the directory there:

![image](https://user-images.githubusercontent.com/9433472/128081729-0e81a9b0-5a7d-4e4c-bb24-91f4b421a6a3.png)

but nothing else seems to change. (I noticed there's a `gegl-0.4` directory in `~/.cache` and `~/.local/share`, but removing it doesn't seem to do anything.)

**Comment by sersorrel** [comment]
aha, I found the problem: `nix-shell -p graphviz --run glimpse` works just fine, and adding graphviz to environment.systemPackages fixes it permanently. see e.g. https://dev.getsol.us/T9486

**Comment by erictapen** [comment]
Ooh nice, didn't think about using a pure nix-shell to circumvent already installed packages clouding the issue. Now I'm able to reproduce the issue. Will add graphviz as runtime dependency then.

**Comment by erictapen** [comment]
Looks like Gimp is not affected, as they got it [fixed](https://gitlab.gnome.org/GNOME/gimp/-/commit/f83fd22c4b8701ffc4ce14383e5e22756a4bce04). Glimpse didn't receive that fix, and it won't in the foreseeable future as the project [seems to be on hold](https://glimpse-editor.org/posts/a-project-on-hiatus/).
