### ISSUE TITLE
patool: build fails due to failing tests

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#132476]
### Describe the bug
```
=========================== short test summary info ============================
FAILED tests/test_mime.py::TestMime::test_mime_file - AssertionError: None !=...
FAILED tests/test_mime.py::TestMime::test_mime_file_xzip - AssertionError: No...
FAILED tests/archives/test_7z.py::Test7z::test_7z_file - patoolib.util.Patool...
FAILED tests/archives/test_pylzma.py::TestPylzma::test_py_lzma_file - patooli...
FAILED tests/archives/test_tar.py::TestTar::test_tar_xz_file - patoolib.util....
FAILED tests/archives/test_xz.py::TestXz::test_xz_file - patoolib.util.Patool...
=========== 6 failed, 68 passed, 96 skipped, 4 deselected in 13.59s ============
```

### Steps To Reproduce
1. checkout revision c464dc811ba
2. `nix-build . -A patool`

### Expected behavior
Should build without problems.

### Notify maintainers
@marius851000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
* patool
* python39Packages.patool
# a list of nixos modules affected by the problem
module:
```

**Comment by marius851000** [comment]
Thank. Will be on vacation for about 3 more days, and I'll fix it then (or maybe try to use nix-on-droid...)

**Comment by marius851000** [comment]
I'm back. Hope it is quickly fixed...

**Comment by marius851000** [comment]
Check error seems to be an issue with the "file" depencies update to 5.40

**Comment by marius851000** [comment]
This patch should fix this issue : https://github.com/file/file/commit/9b0459afab309a82aa4e46f73a4e50dd641f3d39

**Comment by marius851000** [comment]
Applying this patch fixed the issue. Will open a PR.

**Comment by marius851000** [comment]
Merged in staging.

**Comment by asbachb** [comment]
@marius851000 thanks mate
