### ISSUE TITLE
Simpler ZFS/ZED enableMail setup 

### ISSUE THREAD

**Issue by t1lde** [NixOS/nixpkgs#132464]
### Describe the bug

The setup to enable ZED email alerts for ZFS is pretty annoying with non-obvious steps.

How the current config went for me:

- set `services.zfs.zed.enableMail = true`
- get error message from nixos-rebuild: `to allow zed to send emails, zfs needs to be configured to email this...`
- try and find whether there is a `services.zfs.package` option, or similar - `boot.zfs.package` was a red herring
- finally realizing I needed to set an overlay due to implicit usage of `pkgs.zfs`  by `supportedFilesystems = [ "zfs" ]`

### An alternative I'd prefer

Could we not have a `services.zfs.package` option or something, with a more directly configurable zfs package? 

I respect that there may be complicated parts, especially given tight coupling with boot/kernel/other things so it may not be so easy - but this honestly had me scratching my head for a while this evening, so I thought I'd raise an issue. 
Documentation or more clarity in the error message may have helped me out here.

Thanks :)

**Comment by cyounkins** [comment]
There's an example configuration here which uses an override: https://gist.github.com/bitonic/78529d3dd007d779d60651db076a321a

**Comment by cyounkins** [comment]
I have updated the wiki page (https://nixos.wiki/wiki/ZFS) in the section for ZED email alerts to include an example override. While I too would like the `enableMail` to be automatic, the current situation isn't bad with the improved documentation. I'd vote to close this issue.

The ZFS package was changed to not include mail support by default to limit it's size: https://github.com/NixOS/nixpkgs/pull/109345

**Comment by t1lde** [comment]
thanks for the config example, & for updating the wiki. 

I do think it could still be hard to discover this solution. Ideally, available override variables/package configurations would be represented in the options, *especially* if other options rely on them.
