### ISSUE TITLE
nix-shell failing to parse nix that nix repl doesn't fail

### ISSUE THREAD

**Issue by InfinityGhost** [NixOS/nixpkgs#132484]
### Describe the bug
A nix-shell derivation I use daily broke after a system upgrade. `nix-shell` complains with syntax errors, however when loading it in `nix repl` it has no problems.

### Steps To Reproduce
1. Download [this file](https://gist.github.com/InfinityGhost/acbcdafb2d1f04cb1f2fd03ee12fda21)
2. Run `nix-shell -p shell.nix` (assuming shell.nix is in $PWD)
3. It complains that line 29 (the `in` statement) is an unexpected token despite `nix repl` having no issue parsing the same file.

### Expected behavior
`nix-shell` derivation should work as intended and the environment should be created.

### Screenshots
![image](https://user-images.githubusercontent.com/39218853/127949349-8a4d84f2-a316-4f38-89c5-ea5a38ca731c.png)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.132, NixOS, 21.11pre302615.967d40bec14 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre304626.8ecc61c91a5"`
 - channels(infinity): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by veprbl** [comment]
`nix-shell -p foo` is roughly equivalent to `with import <nixpkgs> {}; runCommand { buildInputs = [ foo ]; }`
https://github.com/NixOS/nix/blob/47e96bb533f8cacc171bec9b688b134de31a48a9/src/nix-build/nix-build.cc#L272-L275

There is also a feature of stdenv where standalone files in `buildInputs` are interpreted as shell hooks, so in your case you are making it parse shell.nix with bash.

**Comment by InfinityGhost** [comment]
> `nix-shell -p foo` is roughly equivalent to `with import <nixpkgs> {}; runCommand { buildInputs = [ foo ]; }`
> https://github.com/NixOS/nix/blob/47e96bb533f8cacc171bec9b688b134de31a48a9/src/nix-build/nix-build.cc#L272-L275

I'm exhausted, I just realized I was adding the `-p` option the entire time when I didn't mean to, thanks for pointing that one out.

> There is also a feature of stdenv where standalone files in buildInputs are interpreted as shell hooks, so in your case you are making it parse shell.nix with bash.

That's actually pretty nice to know, thanks for that one.

Closing this as it was user error.
