### ISSUE TITLE
wiki: Rust

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13242]
https://nixos.org/wiki/Rust

ping @ehegnes @wizeman @globin  we need to move above Rust wiki page to manual.

### Additional Topics for the Manual

- How to package using `buildRustPackage` 
  - As we package a specific snapshot of `rustRegistry` you can't use newer (or `"*"`) versions in your `Cargo.toml`. Workaround: Check nixpkgs' `rustRegistry` and only use versions lower-or-equal-to the packages there. 
   - `depsSha256` sometimes needs to be bumped when we bump `rustRegistry`

**Comment by ericsagnes** [comment]
`rustStable`, `rustUnstable` and `rustBeta` sets of packages should cover this and are pretty self-explanitory.
Having a rust section in http://nixos.org/nixpkgs/manual/#chap-language-support could be a plus.

**Comment by garbas** [comment]
do we have anywhere a writing (blog post, mailing list thread) that describes rust+nix?

**Comment by Ericson2314** [comment]
N.B. my derivation for Rust nightlies has been given a proper home with https://github.com/solson/rust-nightly-nix. [Thanks again @solson!] I am about to remove it from where the wiki links it.

**Comment by the-kenny** [comment]
Pulling this up: We should get on this. Our `rustUnstable` is very outdated and I'd like to remove it from nixpkgs. Instead users should use the `nightly-nix` stuff by @Ericson2314 above (which I have a few additions in the queue for too).

I try to get on this soon, but I can't say when yet :/

**Comment by the-kenny** [comment]
Addendum: Common thought is that we shouldn't remove unstable just yet.

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/23510
