### ISSUE TITLE
hasura-cli is out of date (1.3.1 -> 2.0.3)

### ISSUE THREAD

**Issue by Narice** [NixOS/nixpkgs#132435]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: hasura-cli

current version: 1.3.1-beta1
desired version: 2.0.3

###### Notify maintainers

maintainers: @ingenieroariel 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ingenieroariel** [comment]
Is the hasura-cli out of date with respect to the graphic server built in?

**Comment by samuela** [comment]
> Is the hasura-cli out of date with respect to the graphic server built in?

No they appear to be the same version: https://search.nixos.org/packages?channel=21.05&from=0&size=50&sort=relevance&query=hasura

**Comment by Narice** [comment]
so the two should be upgraded @ingenieroariel? should I ping the maintainers of the server part?

**Comment by Lassulus** [comment]
https://github.com/NixOS/nixpkgs/pull/134404

**Comment by Narice** [comment]
so that would also update the cli to 2.0.7 @Lassulus?

**Comment by Lassulus** [comment]
as soon as haskell-updates is merged into master and the channel progresses, nixos-unstable should have the 2.0.7 version

**Comment by Narice** [comment]
ok cool! thanks @Lassulus! I'll close this issue then ;)
