### ISSUE TITLE
iosevka-bin does not allow to install the term variant

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#132562]
Though https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/iosevka/variants.nix contains `sgr-iosevka-term`, trying to use it results in an error:

```
error: No such variant "sgr-iosevka-term" for package iosevka-bin.
       Valid variants are: aile, curly, curly-slab, etoile, slab, ss01, ss02, ss03, ss04, ss05, ss06, ss07, ss08, ss09, ss10, ss11, ss12, ss13, ss14, ss15, ss16, ss17, ss18.
```

@cstrahan

**Comment by Artturin** [comment]
That variant was added after nixos-21.05 was released

**Comment by suhr** [comment]
I'm using the unstable channel, and this variant is not available to me.

**Comment by suhr** [comment]
The reason why this does not work is because in https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/fonts/iosevka/bin.nix#L6, `"iosevka"` is appended to the variant name, resulting in incorrect full variant name.

In my personal NUR repository, I just remove this appending completely and just use the full variant name (`"sgr-iosevka-term"`): https://github.com/suhr/nur-packages/blob/master/pkgs/iosevka/term.nix. And it works pretty well.

**Comment by Artturin** [comment]
oops i tried the non-bin package
i'll fix the iosevka prepending

**Comment by Artturin** [comment]
#137024
