### ISSUE TITLE
wiki: Long-term open issues:build determinism

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13258]
https://nixos.org/wiki/Long-term_open_issues:build_determinism

**Comment by joachifm** [comment]
I think this wiki page is too incomplete to be worth migrating. We might want a chapter on build determinism in the manual, but seems like we might as well start from scratch.

**Comment by vcunat** [comment]
Most of the problems are general. Perhaps it would be worth to link e.g. https://reproducible-builds.org/docs/ and only highlight the differences with nix(os).
