### ISSUE TITLE
wiki: Package Requests

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13250]
https://nixos.org/wiki/Package_Requests

**Comment by 7c6f434c** [comment]
I think we also have some issues like that. What is the policy? Close if nobody volunteers, but add a label for easy search?

**Comment by garbas** [comment]
@7c6f434c i think we should document the policy and place where to ask for help to packages something. not sure yet where this would fit in current documentation.

**Comment by 7c6f434c** [comment]
I am additionally not sure _what_ the policy is.
