### ISSUE TITLE
Missing erlang native interface

### ISSUE THREAD

**Issue by hissssst** [NixOS/nixpkgs#132572]
### Describe the bug
All erlang packages (except `erlangR22` and `erlangR21`) are missing `erl_interface.h` which is crucial for building native dependencies for erlang

### Expected behavior
`erlang`, `erlangR23`, `erlangR24` should have `erl_interface.h`

### Notify maintainers
@ankhers @Br1ght0ne @DianaOlympos @gleber @happysalada @yurrriq

**Comment by Artturin** [comment]
the arch package doesn't contain it and neither does our erlang.src

https://archlinux.org/packages/community/x86_64/erlang/files/

**Comment by happysalada** [comment]
I am not an erlang expert by any stretch.
Looking at this hacker news thread it says that erl_interface was deprecated with otp 23
https://news.ycombinator.com/item?id=23166554
it says that things have moved to a newer `ei_` interface.

On the nixpkgs side of things, we are not doing anything different for compilation of 21 to 24. So if it is missing it is probably a deprecation upstream.

@dlesl sorry to bother you with this, but you might know more about this issue.

**Comment by DianaOlympos** [comment]
Oh goddess not erl_interface. I can have a look later too, it is a bit complex because it is a header that we need to provide for the dependencies to build. So may need to think a bit on how we could do it.

**Comment by dlesl** [comment]
I found this:
http://erlang.org/doc/apps/erl_interface/notes.html#erl_interface-3.13.2.1
> The old legacy erl_interface library (functions with prefix erl_) is deprecated as of OTP 22, and will be removed in OTP 23. This does not apply to the ei library. Reasonably new gcc compilers will issue deprecation warnings. In order to disable these warnings, define the macro EI_NO_DEPR_WARN.

As @happysalada mentioned it has been removed so I think the only solution is to update these dependencies. I'll close this since it doesn't seem to be a nixpkgs issue.

**Comment by hissssst** [comment]
@dlesl , oh, I see
Thanks!
