### ISSUE TITLE
openscad fails to build on Darwin

### ISSUE THREAD

**Issue by treed** [NixOS/nixpkgs#132500]
### Describe the bug

Attempting to install (build, because not cached) openscad on Darwin fail with an error

### Steps To Reproduce
1. `nix-env -iA nixpkgs.openscad`

### Expected behavior

OpenSCAD is installed

### Screenshots

Probably not worth a screenshot, but the operative text is:

rmdir: failed to remove '/nix/store/c0a565jpr314gq6imw2ldrn98d3h6vzj-openscad-2021.01/share/openscad': Directory not empty

### Additional context

This appears to be extra commands run as post-install specifically for Darwin.

### Notify maintainers

@bjornfor @gebner 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(treed): `"home-manager, nixpkgs-21.11pre304227.ecaf3da9340, unstable-21.11pre304227.ecaf3da9340"`
 - nixpkgs: `/Users/treed/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: openscad
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
#132552
