### ISSUE TITLE
gajim broken since 21.05

### ISSUE THREAD

**Issue by poelzi** [NixOS/nixpkgs#132632]
### Describe the bug
gajim does not start since the librsvg-2.50.5 is linked against glibc-2.32 while the python runtime is linked against glibc-2.31

### Steps To Reproduce
1. nix-env -iA gajim
2. gajim

### Expected behavior
gajim works

### Screenshots
```
...
08/04/21 10:05:35 (W) gajim.c.logger             Execution time for _get_jid_ids_from_db: 168 ms
08/04/21 10:05:35 (W) gajim.c.logger             Execution time for _load_caps_data: 90 ms

(org.gajim.Gajim:106721): Gtk-WARNING **: 10:05:36.373: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /nix/store/hwk5wmw2hi2v6k6kkgwiychncbig16bp-librsvg-2.50.5/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/hwk5wmw2hi2v6k6kkgwiychncbig16bp-librsvg-2.50.5/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /nix/store/hwk5wmw2hi2v6k6kkgwiychncbig16bp-librsvg-2.50.5/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /nix/store/0c7c96gikmzv87i7lv3vq5s1cmfjd6zf-glibc-2.31-74/lib/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/hwk5wmw2hi2v6k6kkgwiychncbig16bp-librsvg-2.50.5/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
fish: Job 1, 'gajim' terminated by signal SIGABRT (Abort)
```

### Notify maintainers

@raskin
@abbradar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.2001.d4590d21006 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2001.d4590d21006"`
 - channels(poelzi): `"home-manager-21.05, nixos-21.05.2001.d4590d21006"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by veprbl** [comment]
This is an impurity bug occurring when mixing different glibc's in the same environment
#84043 #95808

**Comment by poelzi** [comment]
I think the problem is that python3.8 is linked against glibc 2.31 while the desktop environment is linked against 2.32 and loading the qt rendering modules fail.
To be honest, this happens every time on a nixos upgrade that some of my programs fail due glibc problems. It is so annoying that NixOS for reason beyond my logical understanding, does not simple compile everything against the same glibc. It is so frustrating that I start to question my OS choice :(
If you update libc, then you do it everywhere at the beginning of the OS cycle, not somewhere in between....

**Comment by veprbl** [comment]
If you've installed everything from the same version of nixpkgs it can't have different glibc versions. However user needs to keep the independent nixos/nix-env/home-manager installations in sync as needed.

**Comment by poelzi** [comment]
$something fixed it
