### ISSUE TITLE
wiki: Installing VirtualBox on NixOS

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13267]
https://nixos.org/wiki/Installing_VirtualBox_on_NixOS

**Comment by P-E-Meunier** [comment]
On the stable channel, I just did the following to get `VBoxManage` to work. It was not on the wiki, nor on any github issue:

```nix
environment.systemPackages = [ virtualboxHardened ];
services.virtualbox.host = { enable = true; enableHardening = false; };
```

I guess another way would be to install `virtualBox`, and set `enableHardening = false`, but this is really documented nowhere.

Another undocumented thing is that one needs both `services.virtualbox.host.…` set, and a package installed: the current wiki page makes it look like the `services.virtualbox` option is enough, but it wasn't in my case.

**Comment by p-alik** [comment]
meanwhile https://nixos.org/wiki/Installing_VirtualBox_on_NixOS disappeared 

> The community-maintained NixOS wiki now can be found at https://nixos.wiki

I couldn't find "Installing VirtualBox on NixOS" instruction on https://nixos.wiki

But on github https://github.com/deepfire/nixos-wiki/blob/master/Installing%20VirtualBox%20on%20NixOS.page

**Comment by p-alik** [comment]
`setuidPrograms` is obsolete
`trace: warning: The option definition `security.setuidPrograms' in `/etc/nixos/configuration.nix' no longer has any effect`

**Comment by flokli** [comment]
Shouldn't it be simply
```nix
virtualisation.virtualbox.host.enable = true;
users.extraUsers.myuser.extraGroups = ["vboxusers"];
```

as described in the [options](https://nixos.org/nixos/options.html#virtualbox.host.enable)?

**Comment by p-alik** [comment]
works fine on
```
nixos-version 
18.03.132750.91b286c8935
```
