### ISSUE TITLE
darwin: binaries produced by writeHaskell are killed on startup

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#132660]
```console
$ nix-build -A tests.writers.simple.haskell
$ ./result 
Killed: 9
```

`log stream` shows:

```
2021-08-04 15:26:27.237786+0200 0x431a     Default     0x0                  746    taskgated: (Security) [com.apple.securityd:security_exception] UNIX error exception: 3
2021-08-04 15:26:27.238090+0200 0x431a     Default     0x0                  746    taskgated: no signature for pid=97538 (cannot make code: UNIX[No such process])
```

I suspected code signing at first, but this is `x86_64-darwin` and thus shouldn't be an issue. In the Nix on macOS channel on Matrix, someone suggested it may be a malformed Mach-O binary, Is there maybe something happening in `fixupPhase` by default we are missing here in the writer derivation?

I'd appreciate help from @NixOS/darwin-maintainers here since I can't figure this out.

```yaml
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.7.0, macOS 10.13.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.10`
 ```

**Comment by mikroskeem** [comment]
Can confirm.

```yaml
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
```

Note: used `--argstr system x86_64-darwin` for that.

**Comment by jpraczyk** [comment]
I'm getting the following error message when running tests.writers.simple.haskell

```
taskgated	MacOS error: -67062
taskgated	cannot open file at line 44595 of [02c344acea]
taskgated	os_unix.c:44595: (2) open(/var/db/DetachedSignatures) - No such file or directory
```
Which means
```
❯ security error -67062                                                                                                                                                                                       
Error: 0xFFFEFA0A -67062 code object is not signed at all
```

**Comment by sternenseemann** [comment]
What architecture and macOS version is that?

**Comment by domenkozar** [comment]
The problem is that writers use `runCommand`, which uses `buildCommand`, which doesn't use the phases so signing doesn't happen.

**Comment by sternenseemann** [comment]
The problem is unrelated to signing, but I do get the impression that we are missing some darwin specific fixupPhase hook.
