### ISSUE TITLE
keycloak service cannot enable/install

### ISSUE THREAD

**Issue by bernadinm** [NixOS/nixpkgs#132621]
### Describe the bug
I cannot install keycloak on Nixos regardless if I use unstable or stable.

### Steps To Reproduce
```
  services.keycloak = {
    enable = true;
    frontendUrl = "keycloak.example.com/auth";
    database.passwordFile = "/run/keys/db_password";
  };
```
### Expected behavior

There should not be any errors after running `sudo nixos-rebuild switch`

### Screenshots

![keycloak-screenshot](https://user-images.githubusercontent.com/8700946/128125183-76df829f-fc8b-46b0-bee6-15f066907a51.png)

### Additional context

I've tested this on unstable as well and its the exact same issue, the only difference is the version for keycloak is `15.0.0` instead of `14.0.0` on stable..

### Notify maintainers

@talyz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.2001.d4590d21006 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(miguel): `""`
 - channels(root): `"nixos-21.05.2001.d4590d21006, nixos-unstable-21.11pre305786.aaf9676fbb7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: keycloak
```

**Comment by talyz** [comment]
The only thing I can think of causing this issue is the password. If it contains special characters, can you try generating a new one without any in it?

**Comment by bernadinm** [comment]
Well said. It looks like I thought the password file was there this whole time but it wasn't. After creating the file and setting it, it started. Thanks for the hint! I'll close this out.
