### ISSUE TITLE
Packaging requests: Jupyter Book

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#132686]
**Project description**
"Jupyter Book is an open source project for building beautiful, publication-quality books and documents from computational material." 

**Metadata**

* homepage URL: https://jupyterbook.org/intro.html
* source URL: https://github.com/executablebooks/jupyter-book/
* license: bsd
* platforms: unix, linux, darwin

I've tried to package this myself, just to get a development shell working, but I think this is beyond me, in terms of complexity. [Here's my broken attempt at packaging it,](https://github.com/JonathanReeve/book-computational-literary-analysis/blob/57fa69938a2a0bfd55fdb7c03d0bd6e93973f290/jupyter-book.nix) and [here's a post on Discourse where I describe the errors I was getting](https://discourse.nixos.org/t/error-could-not-install-packages-due-to-an-oserror-errno-13-permission-denied-cmp-pyi/14316), and [here's a post on StackOverflow where I try to get help with packaging it](https://stackoverflow.com/questions/68515409/how-can-i-make-a-python-package-in-nixos?noredirect=1#comment121326466_68515409).

**Comment by doronbehar** [comment]
I too tried to package jupyter-book, and I realized after a while that there are tons of new python packages to add as dependencies. Plus, I stumbled some issues upstream, example: 

- https://github.com/executablebooks/MyST-NB/blob/52f7fb7f4b36ad5ac12a6625a78403b8b2dfd36b/setup.cfg#L47
- https://github.com/jupyter/nbclient/issues/201

And I stopped with packaging the dependency `myst-nb`. If anyone is interested, all my work is at:

https://github.com/doronbehar/nixpkgs/tree/pkg/jupyter-book

I won't continue working on this. The work left to be done, besides waiting for upstream to release a new version of myst-nb and fix the `nbclient` tests failing, is to package the commented out packages in `jupyter-book/default.nix`.
