### ISSUE TITLE
unityhub: why not use web.archive.org in src.url?

### ISSUE THREAD

**Issue by tesq0** [NixOS/nixpkgs#132781]
web.archive.org can very easily archive web urls and updating them is super easy. To get something on archive.org you need to manually upload it.

_Originally posted by @SuperSandro2000 in https://github.com/NixOS/nixpkgs/pull/132745#discussion_r683390919_

**Comment by huantianad** [comment]
No longer relevant with latest UnityHub which fetches from their debian repository.
