### ISSUE TITLE
wiki: Luks-based FDE with Yubikey PBA and btrfs on UEFI NixOS

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13275]
https://nixos.org/wiki/Luks-based_FDE_with_Yubikey_PBA_and_btrfs_on_UEFI_NixOS

**Comment by ttuegel** [comment]
The NixOS manual actually refers *specifically* to this article, so this should be a high priority for migration.

**Comment by datakurre** [comment]
So, where can this be found now?

**Comment by datakurre** [comment]
https://web.archive.org/web/20160911070220/https://nixos.org/wiki/Luks-based_FDE_with_Yubikey_PBA_and_btrfs_on_UEFI_NixOS

**Comment by Profpatsch** [comment]
There is a new (unofficial) wiki: https://nixos.wiki/
We are going to try to add a link to the archive page(s) from there. Articles can be migrated.

**Comment by oxij** [comment]
Some yubikey-related open PRs and issues: #29441 (by me, ready to be merged), #40805 (probably ready), #11886 (no idea), #34747 (should be fixed, but needs confirmation).

Could please someone with a yubikey test whenever https://github.com/oxij/nixpkgs/tree/pull/40805-yubikey-linking (rebase of #40805 onto #29441) works?

**Comment by ryanorendorff** [comment]
Is it possible to restore the wiki page onto the new wiki? I may have missed the documentation, but there does not seem to be any documentation for how to set this up besides reading through the `luksroot.nix` source or by using the wayback backup.

Or does anyone have a more recent write up of how to set up this configuration?

**Comment by ryanorendorff** [comment]
I migrated it. I am going to be trying this installation (without Brtfs) next week.

https://nixos.wiki/wiki/Luks-based_FDE_with_Yubikey_PBA_and_btrfs_on_UEFI_NixOS
