### ISSUE TITLE
/etc/zinputrc points to non-existant store path

### ISSUE THREAD

**Issue by Emantor** [NixOS/nixpkgs#132732]
### Describe the bug
My /etc/zinputrc points to a non-existant store path.
```bash
/etc/zshrc:.:36: no such file or directory: /etc/zinputrc
 ~  ls -la /etc/zinputrc
lrwxrwxrwx 1 root root 20  5. Aug 06:27 /etc/zinputrc -> /etc/static/zinputrc
 ~  ls -la /etc/static/zinputrc
lrwxrwxrwx 1 root root 86  1. Jan 1970  /etc/static/zinputrc -> /nix/store/4l9d555va23q26p985kwr2rzfn01n6vw-source/nixos/modules/programs/zsh/zinputrc
 ~  ls -la /nix/store/4l9d555va23q26p985kwr2rzfn01n6vw-source/nixos/modules/programs/zsh/zinputrc
ls: cannot access '/nix/store/4l9d555va23q26p985kwr2rzfn01n6vw-source/nixos/modules/programs/zsh/zinputrc': No such file or directory
 ~    
```
`zinputrc` is contained in my nix store, however not within `source`, but rather nixos:
```
 /nix/store    find . -iname  "*zinputrc*"
./gczx49730qfzz925ic7fvcbha1dwi86c-nixos-21.11pre294109.fbfb79400a0/nixos/nixos/modules/programs/zsh/zinputrc
./44aqds9n45x0qnc1s7kcf361kkgffjpg-etc/etc/zinputrc
./ychirbiy3rrh4s6y7xyfghpdvv5vrxpw-nixos-21.11pre306003.c464dc811ba/nixos/nixos/modules/programs/zsh/zinputrc
```

### Steps To Reproduce
1. enable `programs.zsh`
2. Rebuild with latest nixos-unstable
3. start zsh

### Expected behavior
No error on opening a terminal

### Additional context
This is probably related to https://github.com/NixOS/nixpkgs/pull/131102.

### Notify maintainers
Not a maintainer but author of the make-etc change:
@dasJ

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.6, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre306003.c464dc811ba"`
 - channels(phoenix): `"ptxpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: programs/zsh
```

**Comment by dasJ** [comment]
This is pointing to the file directly instead of into a nixpkgs checkout in my 21.05 system:
```
$ ls -la /etc/static/zinputrc
lrwxrwxrwx 1 root root 52 Jan  1  1970 /etc/static/zinputrc -> /nix/store/shng94n86rrp8135zlh95yz2bs4n9rkn-zinputrc
```

**Comment by Emantor** [comment]
Hm, I'm using flakes, does that make a difference here?

**Comment by Emantor** [comment]
> This is pointing to the file directly instead of into a nixpkgs checkout in my 21.05 system:

AFAICS this commit was not backported to 21.05. Reverting eb7120dc79966d5ed168321fd213de38de13a2b1 fixed my issue.

**Comment by dasJ** [comment]
Yeah sorry that was why I was testing with 21.05. It is not planned to backport the commit at any time.

I checked the code and I don't see how that would happen, apart from having something to do with flakes.
Since my knowledge about flakes is rather limited, I'll have to research that and ask other people who are more experienced.

**Comment by dasJ** [comment]
I'm assuming this is a nix problem with flakes so I opened https://github.com/NixOS/nix/issues/5097

**Comment by Emantor** [comment]
I can't reproduce any longer on current nixos-unstable:
```
~/wo…/git/nixos-config  ls -la /etc/static/zinputrc
lrwxrwxrwx 1 root root 56  1. Jan 1970  /etc/static/zinputrc -> /nix/store/g2lymh7i1i5ypandcnzb2yv70yakq1a1-etc-zinputrc
```
Closing.
