### ISSUE TITLE
wiki: Network Manager

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13273]
https://nixos.org/wiki/Network_Manager

**Comment by siddharthist** [comment]
Note that [there is already currently documentation on NetworkManager in the manual](https://github.com/NixOS/nixpkgs/blob/02e9e67fd4d48ca5d6d358e94ad834f38b0af6f7/nixos/doc/manual/configuration/network-manager.xml), so we should decide what's worth migrating from that wiki page. 

My suggestions for migration are: 
 * mention nmcli and nmtui, but do not provide command examples
 * mention gtk and kde applets

I'm happy to provide a PR of the above!

**Comment by garbas** [comment]
:+1: that would be awesome!

**Comment by cryptix** [comment]
The section in the wiki about i3 + nm-applet is not working for me.
