### ISSUE TITLE
wiki: NFS

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13278]
https://nixos.org/wiki/NFS

**Comment by aragnon** [comment]
@garbas  This wiki entry contains a manual command `mkdir /export`. While the content is useful otherwise, it doesn't solve the NFS problem declaratively. Do you know how such a simple command should be turned into a Nix module? To me, it appears that all that needs to happen is that all the mount points need to be created by the NFS module via something like `mkdir -p`.

**Comment by DerTim1** [comment]
`mkdir /export` isn't necessacry. `mount` creates this directory. 

`fileSystems.NAME.options` is now a list of strings, not a single string. 

Firewall-Config is useful, if `networking.firewall.enable = true` is set:
`services.nfs.statdPort = 4000;
  services.nfs.lockdPort = 4001;
  networking.firewall.allowedTCPPorts = [ 2049 111 4000 4001 ];
  networking.firewall.allowedUDPPorts = [ 2049 111 4000 4001 ];`

Sample Configuration: 
`{ config, pkgs, ... }:

{
  fileSystems."/nfs4exports/storage" = { 
    device = "/storage";
    options = [ "bind" ];
  };
  fileSystems."/nfs4exports/storage2" = { 
    device = "/storage2";
    options = [ "bind" ];
  };
    fileSystems."/nfs4exports/demoreadonly" = { 
    device = "/storage/demoreadonly";
    options = [ "bind" ];
  };
  
  services.nfs.server.enable = true;
  services.nfs.statdPort = 4000;
  services.nfs.lockdPort = 4001;
  services.nfs.server.exports = ''
  /nfs4exports			192.168.0.0/24(rw,fsid=0,no_subtree_check) 
  /nfs4exports/storage		192.168.0.0/24(rw,nohide,insecure,no_subtree_check) 
  /nfs4exports/storage2	192.168.0.0/24(rw,nohide,insecure,no_subtree_check) 
  /nfs4exports/demoreadonly		192.168.0.133(ro,nohide,insecure,no_subtree_check)
  '';
   
  networking.firewall.allowedTCPPorts = [ 2049 111 4000 4001 ];
  networking.firewall.allowedUDPPorts = [ 2049 111 4000 4001 ];
}`

**Comment by garbas** [comment]
@DerTim1 you think this would be a nice addition to the ``services.nfs``? to have an additional example there.

**Comment by DerTim1** [comment]
@garbas Yes, the current example (old wiki) is good enough with the fileSystems.NAME.options fix (list instead of single string) and an additonal hint to firewall-config. The pasted example works on my test machine (successfully imported the nfs mount with Ubuntu).
