### ISSUE TITLE
Packaging request: onlyoffice-documentserver 

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#132815]
**Project description**
Onlyoffice-documentserver is a web application which offers an online, collaborative office suite for documents, spreadsheets and presentations. Like Google Docs etc.

**Metadata**

* homepage URL: https://github.com/ONLYOFFICE/DocumentServer
* source URL: https://github.com/ONLYOFFICE/DocumentServer
* license: agpl3
* platforms: linux

**Comment by applePrincess** [comment]
I will close this issue since the package requested has been added by #181258
