### ISSUE TITLE
wiki: Solve GConf errors when running GNOME applications

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13287]
https://web.archive.org/web/20160911020058/https://nixos.org/wiki/Solve_GConf_errors_when_running_GNOME_applications

**Comment by grahamc** [comment]
This solved my problem with i3.

**Comment by Mic92** [comment]
The updated configuration is:

```nix
{
  services.dbus.packages = [ pkgs.gnome2.GConf ];
}
```

**Comment by jerith666** [comment]
@Mic92 do you have a nixpkgs commit that necessitated that change?
