### ISSUE TITLE
Packaging request: Python package btrfsutil 

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#132987]
**Project description**
Python 3 bindings of the `libbtrfsutil`, library for managing BTRFS file systems.
This binding is part of the [btrfs-progs](https://github.com/kdave/btrfs-progs) project.

**Metadata**

* homepage URL: https://github.com/kdave/btrfs-progs/tree/master/libbtrfsutil
* source URL: https://github.com/kdave/btrfs-progs/tree/master/libbtrfsutil/python
* license: lgpl2Only
* platforms: linux (I'm not sure if it works on BSD or Mac)

**Comment by lopsided98** [comment]
See #173436
