### ISSUE TITLE
yq-go is out of date (4.6.3 -> 4.11.2)

### ISSUE THREAD

**Issue by ryuheechul** [NixOS/nixpkgs#132925]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `yq-go`

current version: 4.6.3
desired version: 4.11.2

###### Notify maintainers

maintainers: @kalbasit 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by Artturin** [comment]
#132926
