### ISSUE TITLE
ethminer: does not build on master

### ISSUE THREAD

**Issue by noneucat** [NixOS/nixpkgs#132941]
### Describe the bug
Looks like the recent `ethash` version bump is not compatible with the `ethminer` build.  Workaround is to build off an older version of `ethash` (last worked with `v0.6.0`).

### Steps To Reproduce
1. `nix-build -A ethminer` in current nixpkgs

### Expected behavior
The derivation for `ethminer` builds on Linux. 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.134, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre306003.c464dc811ba, nixos-stable-21.05.2075.ff1ea3a36c1"`
 - channels(noneucat): `"nixos-stable-21.05.1817.2262d7863a6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgs.ethminer
# a list of nixos modules affected by the problem
module: services.ethminer
```

**Comment by applePrincess** [comment]
Fixed by #133274
