### ISSUE TITLE
yabridge 32-bit bitbridge support

### ISSUE THREAD

**Issue by critbase** [NixOS/nixpkgs#132935]
The current version of [yabridge packaged](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/audio/yabridge/default.nix) doesn't build support for the bitbridge that allows for running 32 bit VST plugins. Information on building that is on the [project README](https://github.com/robbert-vdh/yabridge#32-bit-bitbridge).
Basically, what's necessary is to make sure that the 32 bit versions of `boost` and `libxcb` are installed, and adding a meson flag.
It didn't end up being that simple when I tried adding it myself by just adding the 32 bit dependencies to buildInputs and the meson flag; I got a vague error about meson being unable to find boost_filesystem.

paging the maintainer of the package: @kira-bruneau

**Comment by critbase** [comment]
Attached are my modifications to the current yabridge definition.
It is *very* hacky, but it seems to build... all up until it gets to the part where it links stuff. There, ld fails (see attached error log).
[yabridge.txt](https://github.com/NixOS/nixpkgs/files/6948017/yabridge.txt)
[yabridge-build-log.txt](https://github.com/NixOS/nixpkgs/files/6948025/yabridge-build-log.txt)

**Comment by kira-bruneau** [comment]
I spent a lot of time trying to get this to work, but I couldn't find any way to specify both the 32bit and 64bit version of boost in a `multiStdenv` build because of https://github.com/NixOS/nixpkgs/issues/86131. There probably is a hacky way to work around it, but I couldn't find how. I decided to give up on it until #86131 is fixed, but I would be happy to accept a workaround if you find one.

**Comment by kira-bruneau** [comment]
It looks like that linking error is the same problem I was running into. The build would only ever pick up either the 32bit boost or the 64bit one, but I couldn't find a way to specify the right one for bitbridge support.

I tried splitting up the 32bit & 64bit builds, but the project fails to compile as 32bit, because it makes the assumption that the default build will be 64bit.

**Comment by critbase** [comment]
Hmm. An idea i haven't tried yet is trying to patch one of the release binaries. Might be a little easier than trying to wrangle meson, at least until that issue gets fixed.

**Comment by critbase** [comment]
Complete crackpot idea; since the 32 bit stuff that gets built are just binaries that yabridgectl looks for in $PATH (i think), maybe it's possible to just take them from the prebuilt binaries and patch them?

**Comment by critbase** [comment]
Sorry to leave so many comments in a row, but I got it working and pretty much no ugly hacks too. I'll just paste my definition verbatim; pretty much all i did was replace `stdenv` with `multiStdenv`, add the bitbridge flag, and replace all references to `wine` with `wineWowPackages.stable` (this was the reason for the linking issues at the end).
There are a few lines where I don't know if they're actually necessary; once it worked pretty much perfectly i stopped testing.
I also am unsure of how to handle referring to pkgsi686Linux, or if there's even a better/more specific way rather than just including pkgsi686Linux as an input.

``` nix
{ lib, multiStdenv, fetchFromGitHub, substituteAll, meson, ninja, pkg-config
, wineWowPackages, boost, libxcb, pkgsi686Linux }:

let
  # Derived from subprojects/bitsery.wrap
  bitsery = rec {
    version = "5.2.0";
    src = fetchFromGitHub {
      owner = "fraillt";
      repo = "bitsery";
      rev = "v${version}";
      hash = "sha256-Bxdtjn2v2lP2lCnvjzmct6QHT7FpwmXoSZtd2oEFS4w=";
    };
  };

  # Derived from subprojects/function2.wrap
  function2 = rec {
    version = "4.1.0";
    src = fetchFromGitHub {
      owner = "Naios";
      repo = "function2";
      rev = version;
      hash = "sha256-JceZU8ZvtYhFheh8BjMvjjZty4hcYxHEK+IIo5X4eSk=";
    };
  };

  # Derived from subprojects/tomlplusplus.wrap
  tomlplusplus = rec {
    version = "2.1.0";
    src = fetchFromGitHub {
      owner = "marzer";
      repo = "tomlplusplus";
      rev = "v${version}";
      hash = "sha256-i6yAEqwkinkPEzzb6ynXytS1SEOUDwi8SixMf62NVzs=";
    };
  };

  # Derived from vst3.wrap
  vst3 = rec {
    version = "3.7.2_build_28-patched";
    src = fetchFromGitHub {
      owner = "robbert-vdh";
      repo = "vst3sdk";
      rev = "v${version}";
      fetchSubmodules = true;
      sha256 = "sha256-39pvfcg4fvf7DAbAPzEHA1ja1LFL6r88nEwNYwaDC8w=";
    };
  };
in multiStdenv.mkDerivation rec {
  pname = "yabridge";
  version = "3.3.1";

  # NOTE: Also update yabridgectl's cargoHash when this is updated
  src = fetchFromGitHub {
    owner = "robbert-vdh";
    repo = pname;
    rev = version;
    hash = "sha256-3B+6YuCWVJljqdyGpePjPf5JDwLSWFNgOCeLt8e4mO8=";
  };

  # Unpack subproject sources
  postUnpack = ''
    (
        cd "$sourceRoot/subprojects"
        cp -R --no-preserve=mode,ownership ${bitsery.src} bitsery-${bitsery.version}
        tar -xf bitsery-patch-${bitsery.version}.tar.xz
        cp -R --no-preserve=mode,ownership ${function2.src} function2-${function2.version}
        tar -xf function2-patch-${function2.version}.tar.xz
        cp -R --no-preserve=mode,ownership ${tomlplusplus.src} tomlplusplus
        cp -R --no-preserve=mode,ownership ${vst3.src} vst3
      )'';

  patches = [
    # Hard code wine path so wine version is correct in logs
    (substituteAll {
      src = ./hardcode-wine.patch;
      inherit (wineWowPackages.stable)
      ;
    })
  ];

  postPatch = ''
    patchShebangs .
  '';

  nativeBuildInputs = [ meson ninja pkg-config wineWowPackages.stable ];

  buildInputs = [ boost libxcb ];

  # Meson is no longer able to pick up Boost automatically.
  # https://github.com/NixOS/nixpkgs/issues/86131
  BOOST_INCLUDEDIR = "${lib.getDev boost}/include";
  BOOST_LIBRARYDIR = "${lib.getLib boost}/lib";

  mesonFlags = [
    "--cross-file"
    "cross-wine.conf"
    "-Dwith-bitbridge=true"
    # not sure if these 4 lines below are necessary
    "-Dbuild.cpp_link_args='-I${lib.getLib boost}/lib'"
    "-Dbuild.cpp_link_args='-I${lib.getLib pkgsi686Linux.boost}/lib'"
    "-Dbuild.cpp_link_args='-I${lib.getLib libxcb}/lib'"
    "-Dbuild.cpp_link_args='-I${lib.getLib pkgsi686Linux.xorg.libxcb}/lib'"

    # Requires CMake and is unnecessary
    "-Dtomlplusplus:GENERATE_CMAKE_CONFIG=disabled"

    # tomlplusplus examples and tests don't build with winegcc
    "-Dtomlplusplus:BUILD_EXAMPLES=disabled"
    "-Dtomlplusplus:BUILD_TESTS=disabled"
  ];

  preConfigure = ''
    sed -i "601s|xcb.*|xcb_32bit_dep = winegcc.find_library('xcb', dirs: [ '${
      lib.getLib pkgsi686Linux.xorg.libxcb
    }/lib', ])|" meson.build
    sed -i "589 i '${lib.getLib pkgsi686Linux.boost}/lib'," meson.build
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p "$out/bin" "$out/lib"
    cp yabridge-group*.exe{,.so} "$out/bin"
    cp yabridge-host*.exe{,.so} "$out/bin"
    cp libyabridge-vst2.so "$out/lib"
    cp libyabridge-vst3.so "$out/lib"
    runHook postInstall
  '';

  # Hard code wine path in wrapper scripts generated by winegcc
  postFixup = ''
    for exe in "$out"/bin/*.exe; do
      substituteInPlace "$exe" \
        --replace 'WINELOADER="wine"' 'WINELOADER="${wineWowPackages.stable}/bin/wine"'
    done
  '';

  meta = with lib; {
    description =
      "Yet Another VST bridge, run Windows VST2 plugins under Linux";
    homepage = "https://github.com/robbert-vdh/yabridge";
    license = licenses.gpl3Plus;
    maintainers = with maintainers; [ kira-bruneau ];
    platforms = [ "x86_64-linux" ];
  };
}
```
