### ISSUE TITLE
wiki: Bootstrapping NixOS on ARM

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13290]
https://nixos.org/wiki/Bootstrapping_NixOS_on_ARM
https://nixos.org/wiki/NixOS_on_ARM/multi_v7_defconfig
https://nixos.org/wiki/NixOS_on_ARM

**Comment by zimbatm** [comment]
@dezgeg does any of https://nixos.org/wiki/Nix(OS)_Embedded apply to you ?

**Comment by dezgeg** [comment]
Not me. I might look into cross-compilation wiki pages though.

**Comment by grahamc** [comment]
re: the bootstrapping page, I also needed libssl-dev and liblzma-dev.

**Comment by vcunat** [comment]
Note: ATM any wiki content is not directly accessible, but you can use e.g. links like https://web.archive.org/web/20160911022116/https://nixos.org/wiki/NixOS_on_ARM

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/issues/26883 fixes cross-compiled stdenvs, and @bgmari is working on making a basic NixOS itself cross-compilable. I hope one will be able to completely automaticallymake an image, obviating all the manual steps in those pages.

**Comment by bgamari** [comment]
For what it's worth, I have a tree which can build fully-functional NixOS SD card images for ARM. I'm working on rebasing this work and will hopefully have a PR in the next few weeks.

**Comment by tomberek** [comment]
@bgamari push changes?
