### ISSUE TITLE
phpPackages.composer does not pick up php.withExtensions

### ISSUE THREAD

**Issue by ob7** [NixOS/nixpkgs#132972]
The php composer package will not take into account a custom php version created using php.withExtensions etc.
The default.nix for composer takes php as an input, which will default to default php and not take into account any custom php extensions.

In order to get composer to use a php version that included extra extensions, I had to modify the default.nix file to specifically use php.withExtensions and include my extensions.

Possibly there's a different way to go about it that someone could share.

**Comment by aanderse** [comment]
Example?

This is what I do:
```
php' = pkgs.php.withExtensions ...
composer' = php'.packages.composer;
```

Are you doing this in a `nix-shell`?

**Comment by ob7** [comment]
I'm doing this in configuration.nix on nixOS.
nixpkgs.config.packageOverrides = pkgs: {
  php = pkgs.php.buildEnv {
    extensions = { enabled, all }: enabled ++ [ all.xsl ];
    extraConfig = ''
      memory_limit = 64G
    '';
  };
};
environment.systemPackages = with pkgs; [
  composer
]

To get composer to use custom php I had to alter its default.nix in nixpkgs:

{ mkDerivation, fetchurl, makeWrapper, unzip, lib, php, pkgs }:
let
  pname = "composer";
  version = "2.1.5";
  php = pkgs.php.withExtensions ({ enabled, all }: enabled ++ [ all.xsl ]);   <---- HAD TO ADD THIS

in
mkDerivation {
  inherit pname version;

  src = fetchurl {
    url = "https://getcomposer.org/download/${version}/composer.phar";
    sha256 = "1v4hjwbv1y5jvj91i2fj8bvmfsymp9ls8h231zd85svfqdy5b5dy";
  };

  dontUnpack = true;

  nativeBuildInputs = [ makeWrapper ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    install -D $src $out/libexec/composer/composer.phar
    makeWrapper ${php}/bin/php $out/bin/composer \
      --add-flags "$out/libexec/composer/composer.phar" \
      --prefix PATH : ${lib.makeBinPath [ unzip ]}
    runHook postInstall
  '';

  meta = with lib; {
    description = "Dependency Manager for PHP";
    license = licenses.mit;
    homepage = "https://getcomposer.org/";
    maintainers = with maintainers; [ offline ] ++ teams.php.members;
  };
}

**Comment by aanderse** [comment]
OK, do this instead:

```
environment.systemPackages =
let
  php' = pkgs.php.buildEnv {
    extensions = { enabled, all }: enabled ++ [ all.xsl ];
    extraConfig = ''
      memory_limit = 64G
    '';
  };
in
[
  php'.packages.composer
];
```

**Comment by ob7** [comment]
If you don't mind me asking, what is the comma for after php?  
`php'`

**Comment by aanderse** [comment]
Personally, I think it is a nice way to distinguish that the package isn't `php`, but a custom variant of it. You'll see it here and there in the nix community.

You'd have to ask a **real** functional programmer why they use it, though. I suspect it has to do with their fondness of [mathematics](https://en.wikipedia.org/wiki/Prime_(symbol)) :smile:

**Comment by drupol** [comment]
What's the status of this ?

**Comment by aanderse** [comment]
Hmm... I feel like this is resolved. @ob7 please feel free open this again if not resolved.
