### ISSUE TITLE
wiki: Disabling IPv6

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13293]
https://nixos.org/wiki/Disabling_IPv6

**Comment by siddharthist** [comment]
This information is already in the manual: https://github.com/NixOS/nixpkgs/blob/4876c7362baa7fa0ed4afcbbdb9e5f8534cce239/nixos/doc/manual/configuration/ipv6-config.xml

**Comment by tohl** [comment]
> This information is already in the manual:
> https://github.com/NixOS/nixpkgs/blob/4876c7362baa7fa0ed4afcbbdb9e5f8534cce239/nixos/doc/manual/configuration/ipv6-config.xml

is it possible to disable/enable ipv6 per interface?

Tomas

**Comment by fpletz** [comment]
@tohl You can always use regular sysctls for that:

    boot.kernel.sysctl."net.ipv6.conf.eth0.disable_ipv6" = true;

Closing as the wiki content is in the manual. Thanks!

**Comment by tohl** [comment]
Franz Pletz <notifications@github.com> writes:
> @tohl You can always use regular sysctls for that:
> boot.kernel.sysctl."net.ipv6.conf.eth0.disable_ipv6" = true;

great, thanks!
