### ISSUE TITLE
ungoogled-chromium crashes when opening file dialog

### ISSUE THREAD

**Issue by nothingmuch** [NixOS/nixpkgs#132934]
### Describe the bug

When ungoogled chromium 91.0.4472.114 attempts to open the file picker, it crashes with the following error:

```
**
Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /nix/store/5rrphirkv7pcp06q4pf76y6qynbc8jbr-adwaita-icon-theme-3.36.1/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /nix/store/5rrphirkv7pcp06q4pf76y6qynbc8jbr-adwaita-icon-theme-3.36.1/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
zsh: IOT instruction (core dumped)  chromium
```

This replicates reliably with my normal user data dir as well as with a fresh `--user-data-dir`.

Does not replicate when using `--incognito` flag.

Also does not replicate with the regular `chromium` package (version 92.0.4515.107) on my normal user data dir.

### Steps To Reproduce

Trigger any file picker dialog. For example, ctrl+s, opening a resource with an attachment content disposition header or choosing a file in a form.

### Additional Context

The `image-missing.png` file exists and is a valid PNG.

### Notify maintainers

@squalus, @primeos 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.6, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre306003.c464dc811ba, nixos-20.09-20.09.4393.068984c00e0"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
> Also does not replicate with the regular chromium package (version 92.0.4515.107) on my normal user data dir.

Maybe #132695 fixes is then for ungoogled-chromium as well? If not some ungoogled-chromium user would have to take a look.

**Comment by nothingmuch** [comment]
Yes, thank you! With 21.11-pre-15262-g112554f3a1e I can no longer reproduce using `nix-shell -I . -p ungoogled-chromium`.
