### ISSUE TITLE
Unable to install extensions on Vieb

### ISSUE THREAD

**Issue by j-hui** [NixOS/nixpkgs#133077]
### Describe the bug
The Vieb web browser is supposed to have ([limited](https://github.com/Jelmerro/Vieb/issues/130)) support for installing Chrome extensions (such as Dark Reader). When I try to do this, it gives me an `ENOENT` error.

### Steps To Reproduce
1. Install Vieb via nixpkgs.
2. `vieb 'https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh'` to open Dark Reader extension.
3. Type `:extensions install` to try to install extension.

This leads to an `ENOENT` error.

### Expected behavior
It should install the extension.

### Notify maintainers
@gebner @fortuneteller2k 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.1669.973910f5c31 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.05.1669.973910f5c31, nixpkgs-unstable-21.11pre304227.ecaf3da9340"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by j-hui** [comment]
I did some digging around and found that problem happens when Vieb tries to unzip the extension. One of Vieb's extensions is the `7z-bin` package, which comes with precompiled `7z` binaries that aren't patched:

```
$ ldd $(nix-store -r $(which vieb))/libexec/vieb/node_modules/7zip-bin/linux/x64/7za
	linux-vdso.so.1 (0x00007ffe387c3000)
	libpthread.so.0 => /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libpthread.so.0 (0x00007fabdcb61000)
	libstdc++.so.6 => not found
	libm.so.6 => /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libm.so.6 (0x00007fabdca1e000)
	libgcc_s.so.1 => /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libgcc_s.so.1 (0x00007fabdca04000)
	libc.so.6 => /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6 (0x00007fabdc843000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib64/ld-linux-x86-64.so.2 (0x00007fabdcb84000)
```

Directly executing this executable leads to an error.

I tried patching the nix file myself:

```
diff --git i/pkgs/applications/networking/browsers/vieb/default.nix w/pkgs/applications/networking/browsers/vieb/default.nix
index f97e8d8250e..606253b1e0f 100644
--- i/pkgs/applications/networking/browsers/vieb/default.nix
+++ w/pkgs/applications/networking/browsers/vieb/default.nix
@@ -1,4 +1,4 @@
-{ mkYarnPackage, fetchFromGitHub, electron, makeWrapper, makeDesktopItem, lib }:
+{ mkYarnPackage, fetchFromGitHub, electron, makeWrapper, makeDesktopItem, lib, autoPatchelfHook, stdenv }:
 
 mkYarnPackage rec {
   pname = "vieb";
@@ -16,7 +16,7 @@ mkYarnPackage rec {
   yarnNix = ./yarn.nix;
   yarnFlags = [ "--production" "--offline" ];
 
-  nativeBuildInputs = [ makeWrapper ];
+  nativeBuildInputs = [ makeWrapper autoPatchelfHook stdenv.cc.cc.lib ];
 
   desktopItem = makeDesktopItem {
     name = "vieb";
```

After this, the 7z binary build by the patched derivation was able to execute without problems, but I was still unable to install any extensions in Vieb.

**Comment by veprbl** [comment]
@j-hui Please submit a PR.

**Comment by j-hui** [comment]
@veprbl to be clear, this still does not work even after that patch. But I will submit a PR and go from there.
