### ISSUE TITLE
wiki: How to install NixOS from linux

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13305]
https://nixos.org/wiki/How_to_install_NixOS_from_linux

**Comment by thisismiller** [comment]
If one sees the error `unshare: cannot change root filesystem propagation: Invalid argument`, then the recommended solution is to upgrade the kernel of the bootstrapping linux install, and then try again.  If this is infeasible, then one may bypass the unshare call by `env NIXOS_INSTALL_REEXEC=1 nixos-install`, but this disables `nixos-install` from cleaning up after itself, and will only work for one invocation.
