### ISSUE TITLE
wiki: Install NixOS as OpenVZ guest

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13308]
https://nixos.org/wiki/Install_NixOS_as_OpenVZ_guest

**Comment by sorki** [comment]
I've managed to make most of the stuff working using external network configuration (combination of vzctl distro scripts / systemd unit).

https://github.com/vpsfreecz/build-vpsfree-templates/blob/master/files/configuration.nix
https://github.com/vpsfreecz/vzctl/commit/870116d16abd201ce4fc2fcf7f1a23cc098211bd

To get vzctl exec working it also needs altering PATH, see

https://github.com/vpsfreecz/vzctl/commit/a4e9efee9826f78e9c94fb23df42ebaa4450d4c2
