### ISSUE TITLE
NetworkManager-wait-online is not waiting for a connection to be ready

### ISSUE THREAD

**Issue by xinyifly** [NixOS/nixpkgs#133063]
### Describe the bug

`NetworkManager-wait-online.service` is executing `nm-online -s -q` 

From the description `-s, --wait-for-startup      Wait for NetworkManager startup instead of a connection`

So `network-online.target` always report `Reached target Network is Online.` even no network cable is plugged in.

### Expected behavior

`network-online.target` is reached after a network-manager connection is setup

### Additional context

`networkmanager.nix` may need to add an option to remove the `-s` parameter from `nm-online` provided by `NetworkManager-wait-online.service` or remove it by default.
### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.2132.733682c3292 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kvtb** [comment]
Yes, but that `nm-online -s -q` is not in nixpkgs, it is in the example script from Network Manager's.
Does  all the other Linux distros use `-s` too ?

**Comment by kvtb** [comment]
Arch does fix this:
https://wiki.archlinux.org/title/NetworkManager#NetworkManager-wait-online

**Comment by Artturin** [comment]
> Arch does fix this: [wiki.archlinux.org/title/NetworkManager#NetworkManager-wait-online](https://wiki.archlinux.org/title/NetworkManager#NetworkManager-wait-online)

its in the wiki so they dont do it by default


if someones wants to do this they can do 
```nix
systemd.services.NetworkManager-wait-online = {
  serviceConfig.ExecStart = [ "" "${pkgs.networkmanager}/bin/nm-online -q" ];
};
```

**Comment by xinyifly** [comment]
@kvtb @Artturin I end up add this configuration:

```nix
{
  networking.networkmanager.extraConfig = ''
    [connectivity]
    uri=http://google.com/generate_204
    response=
    interval=30
  '';
}
```

For a continuously connectivity check, rather than let it block my `network-online.target` . In case I want to start `docker.service` when I'm offline.

**Comment by kvtb** [comment]
I paid attention to this ticket encountering the opposite problem: on my laptop, the default `nm-online -s` hangs for 30 seconds on `nixos-rebuild switch`.

Although, following the docs, it must return immediately if NetworkManager is up and running. Irregardless of the current connectivity status. 

Removing `-s` solved it too.
