### ISSUE TITLE
wiki: Installing NixOS from a USB stick

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13310]
https://nixos.org/wiki/Installing_NixOS_from_a_USB_stick

**Comment by dezgeg** [comment]
We seem to have https://nixos.org/nixos/manual/index.html#sec-booting-from-usb nowadays. Should we close this?

**Comment by AndersonTorres** [comment]
Maybe merge the corresponding wiki info too.

2016-04-09 15:39 GMT-03:00 Tuomas Tynkkynen <notifications@github.com>:

**Comment by joepie91** [comment]
Did this merge ever occur in full?

**Comment by AndersonTorres** [comment]
Dunno. After all the wiki is officially dead.
