### ISSUE TITLE
wiki: NixOS Modifying Modules

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13314]
https://nixos.org/wiki/NixOS_Modifying_Modules

ping @nbp could you review above wiki page and make sure everything is documented in nixos manual?

**Comment by nbp** [comment]
We should already have these chapters on the subject:
  http://nixos.org/nixos/manual/index.html#sec-configuration-syntax
  http://nixos.org/nixos/manual/index.html#sec-writing-modules

So I think we can close this issue.
