### ISSUE TITLE
wiki: NixOS VM tests

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13315]
https://nixos.org/wiki/NixOS_VM_tests

**Comment by moretea** [comment]
@garbas, I could add a section about how to use this infrastructure during application development, basically documenting what I did in https://github.com/moretea/rust-zfs.

**Comment by garbas** [comment]
@moretea i think current http://nixos.org/nixos/manual/index.html#sec-nixos-tests explains ok.
