### ISSUE TITLE
wiki: NixOS install fest

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13322]
https://nixos.org/wiki/NixOS_install_fest

**Comment by 7c6f434c** [comment]
Seems to be an announcement for an old event. Do we have a generally accepted way for such announcements now?

**Comment by garbas** [comment]
@7c6f434c once documentation is migrated to wiki, we also need to fix discoverability of nixos project through the main page. having content from history is important indicator how "live" the project is.

**Comment by ericsagnes** [comment]
https://github.com/NixOS/nixos-weekly look like a good candidate for future events.

**Comment by garbas** [comment]
i guess we can close this ticket. and yes nixos-weekly will be channel where community can make announcements.
