### ISSUE TITLE
tpm2-tss is unable to access the tabrmd loader

### ISSUE THREAD

**Issue by m4tsa** [NixOS/nixpkgs#133248]
### Describe the bug
tpm2-tss is unable to resolve the tabrmd loader located in the tpm2-abrmd package throwing this error when `TPM2TOOLS_TCTI=tabrmd:bus_name=com.intel.tss2.Tabrmd`
```
ERROR:tcti:src/tss2-tcti/tctildr.c:416:Tss2_TctiLdr_Initialize_Ex() Failed to instantiate TCTI 
ERROR: Could not load tcti, got: "tabrmd:bus_name=com.intel.tss2.Tabrmd"
```

### Steps To Reproduce
1. Enable the abrmd daemon and set the tcti environment interface to tabrmd
```nix
{
  security.tpm2 = {
    enable = true;
    abrmd.enable = true;
    tctiEnvironment = {
      enable = true;
      interface = "tabrmd";
    };
  };
}
```
2. Use tool or package using the tpm2-tss library

### Expected behavior
It resolves the loader dynamically and works.

### Additional context
I have narrowed down the cause to this commit https://github.com/NixOS/nixpkgs/commit/eea5575bd364d6327f46e02d0301e62a68d3ca5a making the dynamic loader only resolve locally from the library output. Reverting this in an overlay seems to have fixed the issue, but I am unsure if this would cause regressions as I am unsure why the dynamic loading got patched in the first place.

### Notify maintainers
@delroth @baloo 

### Metadata
```console
mats@sauron ~/ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.7-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre303315.16105403bdd"`
 - channels(mats): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by baloo** [comment]
I patched the tpm2-tss because when using tpm2 as a library, the modules would not be added up in the dlopen load path which would break modules loading.

**Comment by m4tsa** [comment]
This was a bit more tricky than I expected, while other python packages gets the dlopen library name patched with the exact path this is not possible in this case due to tpm2-tss doing the loading as far I understand.

Unless I remember wrong I think it might be possible to dlopen with the exact path in python before calling tpm2-tss init and ld *might* be able to resolve the already library loaded library, but I might remember wrong.

But this would also be undesirable since you cannot dynamically resolve loaders this way I assume.

**Comment by baloo** [comment]
Ha!

So the issue would be that tabmd tries to look up libtss2-tcti-tabrmd and this is provided by tpm2-abrmd. I completely missed that.
