### ISSUE TITLE
Re-add ghcjs

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#133271]
**Project description**
`ghcjs` was removed in https://github.com/NixOS/nixpkgs/commit/cb4346597f033750a432f0161eb5d2c426776960 . At https://github.com/NixOS/nixpkgs/issues/130584 @peti explains it was already broken at that time.

I'm going to try to get it working again.

Here's what I've found so far:
* The "broken" comment cited [this hydra page](https://hydra.nixos.org/build/129701778). The [build log](https://hydra.nixos.org/build/129701778/nixlog/3) ends with the error `Unsupported cabal-version 2.1.`. (Generally, this means a project's `.cabal` file needs to be updated to list a newer cabal-version.)
* I think (haven't verified) that the error was in reference to [`ghcjs.cabal` at revision e87195eaa2bc7e320e18cf10386802bc90b7c874 of the ghcjs project](https://github.com/ghcjs/ghcjs/blob/e87195eaa2bc7e320e18cf10386802bc90b7c874/ghcjs.cabal).
* Since then, `ghcjs.cabal` has been changed to say `Cabal-Version: 2.4`, which should solve that problem.

So, my next step will simply be to try putting back `ghcjs` at a newer version and see if it works.

**Metadata**

* homepage URL: https://github.com/ghcjs/ghcjs
* source URL: https://github.com/ghcjs/ghcjs
* license: mit
* platforms: unix

**Comment by lierdakil** [comment]
FWIW, [iohk/haskell.nix](https://github.com/input-output-hk/haskell.nix) has GHCJS based off GHC 8.10.5, you may want to give it a look. Also, see [hkm/nix-ghc-8.10 branch on ghcjs repo](https://github.com/ghcjs/ghcjs/commits/hkm/nix-ghc-8.10)

**Comment by falsifian** [comment]
Thinks @lierdakil. The problem I'm currently stuck on (see below) seems specific to how nixpkgs works, but I will keep those links in mind. Do you have any context behind the hkm/nix-ghc-8.10 branch? Do you know what problem it's solving?

Current status: I'm trying to figure out how to pass the right version of `optparse-applicative` to ghcjs. My WIP is at https://github.com/falsifian/nixpkgs/commit/d1f0f0a605aba0c0ed991a06f2e7fe32443d1f2d , and I am getting the following error when I run `nix-build -A haskell.compiler.ghcjs`:

```
building
Preprocessing executable 'private-ghcjs-unlit' for ghcjs-8.10.5..
Building executable 'private-ghcjs-unlit' for ghcjs-8.10.5..
/nix/store/hy3lz2vfv9qq2v5jz9nzlx6mmiaq79rj-binutils-2.35.1/bin/ld.gold: warning
: /nix/store/cvr0kjg2q7z2wwhjblx6c73rv422k8cm-glibc-2.33-47/lib/crt1.o: unknown program property type 0xc0008002 in .note.gnu.property section
Preprocessing test suite 'test' for ghcjs-8.10.5..
Building test suite 'test' for ghcjs-8.10.5..
[1 of 4] Compiling Server           ( test/Server.hs, dist/build/test/test-tmp/Server.o )
[2 of 4] Compiling Types            ( test/Types.hs, dist/build/test/test-tmp/Ty
pes.o )
[3 of 4] Compiling Client           ( test/Client.hs, dist/build/test/test-tmp/C
lient.o )
[4 of 4] Compiling Main             ( test/TestRunner.hs, dist/build/test/test-t
mp/Main.o )

test/TestRunner.hs:88:16: error:
    • The constructor ‘ShowHelpText’ should have 1 argument, but has been given 
none
    • In the pattern: ShowHelpText
      In an equation for ‘showParseError’:
          showParseError ShowHelpText = "help!"
   |
88 | showParseError ShowHelpText           = "help!"
   |                ^^^^^^^^^^^^

builder for '/nix/store/kd0s5akm6w6sn3x4f6g79imy2dqck0jd-ghcjs-8.10.5.drv' faile
d with exit code 1
cannot build derivation '/nix/store/61chv2xyfslca66770clrpfc953mgzlq-ghcjs-8.10.
5.drv': 1 dependencies couldn't be built 
error: build of '/nix/store/61chv2xyfslca66770clrpfc953mgzlq-ghcjs-8.10.5.drv' f
ailed
```

(Full output is at https://clbin.com/hTkAy.) Looking at the `optparse-applicative` docs, it looks like the `ShowHelpText` gained an argument at version `0.16`, which explains the `< 0.16` requirement in `ghcjs.cabal`.

I tried overriding the `optparse-applicative` version by adding

```
  ghcjs = super.ghcjs.override {
    base16-bytestring = super.base16-bytestring_0_1_1_7;
    optparse-applicative = super.optparse-applicative_0_15_1_0;
  };
```

in `dep-overrides.nix` (as seen in my WIP commit), but the error still appears. Honestly the above syntax is mostly guess-work: I don't really understand the bootstrap process for building ghcjs. One thing I noticed, though, is that if I remove the `doJailbreak` around `ghcjs` in `common-overrides.nix`, I get errors saying various packages like `optparse-applicative` don't have the right version. Inserting the above snippet silences the error about `optparse-applicative`, so it's doing *something*.

Maybe someone who understands how all this works can point out how to properly override optparse-applicative.

**Comment by lierdakil** [comment]
> Do you have any context behind the hkm/nix-ghc-8.10 branch?

Apparently, this branch got merged into the default ghc-8.10 branch while I wasn't looking, so feel free to disregard that.

**Comment by falsifian** [comment]
Progress: I think I managed to force the correct version of `optparse-applicative` to be used: https://github.com/falsifian/nixpkgs/commit/f164d49929d60e5d2041b6a83f4ca7e69d7a67f4 . Now the problem is `wai-app-static` isn't happy with `optparse-applicative < 0.16`, so no version can satisfy everyone.

**Comment by falsifian** [comment]
Status: I'm making progress getting it to build, but not done yet. Latest is https://github.com/falsifian/nixpkgs/commit/e433ce926a3c3c2ff663c52d412d71b0cf33c5e5.

* I updated ghcjs to use some newer package versions: https://github.com/falsifian/ghcjs/commit/4a3ae0f2c1314e40bf280301a8b0880e30745687. This seems to fix the version mismatch issues, except...
* There was a mismatch betwen the `ghc-boot` version used vs. expected, due to a change after the ghc 8.10.4 release. I worked around this by replacing `ArchAArch64` with `ArchARM64` everywhere in the ghcjs source, to be compatible with the older `ghc-boot`.
* A couple of manual tweaks: add `alex` as a stage0 dependency, and create (empty) `ghc/utils/unlit/fs.h`. Not sure why manual intervention was needed in either case.

Pinging @ElvishJerricco (maintainer) as FYI that I'm working on this.

**Comment by falsifian** [comment]
Some more progress. As of my previous comment, `${bootGhcjs}` builds; now I'm working on getting `buildPhase` in `development/compilers/ghcjs-ng/default.nix` to work.

Currently, I'm stuck on a confusing problem: when `ghcjs-boot` is running, the first package's `Setup` script complains that `ghcjs` and `ghcjs-pkg` were built with different ghc versions:
```
...
jodid25519@1.0.2 /nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/lib/ghcjs-node/node_modules/jodid25519
source-map@0.2.0 /nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/lib/ghcjs-node/node_modules/source-map
/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/lib$ current directory: /nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/lib
/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/lib$ [ghc]: /nix/store/kp4hnhfkd7c6gf3fnb8z897nwnpvg5w7-ghc-8.10.4/bin/ghc "-c" "empty.c"
RTS prepared
configuring package: ghc-prim
/build/configured-ghcjs-src/lib/boot/pkg/ghc-prim$ /nix/store/kp4hnhfkd7c6gf3fnb8z897nwnpvg5w7-ghc-8.10.4/bin/ghc "Setup.hs"
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )

Setup.hs:18:1: warning: [-Wdeprecations]
    Module `System.Cmd' is deprecated: Use "System.Process" instead
   |
18 | import System.Cmd
   | ^^^^^^^^^^^^^^^^^
Linking Setup ...
/nix/store/hy3lz2vfv9qq2v5jz9nzlx6mmiaq79rj-binutils-2.35.1/bin/ld.gold: warning: /nix/store/cvr0kjg2q7z2wwhjblx6c73rv422k8cm-glibc-2.33-47/lib/crt1.o: unknown program property type 0xc0008002 in .note.gnu.property section
/build/configured-ghcjs-src/lib/boot/pkg/ghc-prim$ ./Setup "configure" "--global" "--ghcjs" "--builddir" "dist" "--with-compiler" "/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/bin/ghcjs" "--with-hc-pkg" "/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/bin/ghcjs-pkg" "--with-haddock" "/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/bin/haddock" "--with-gcc" "/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/lib/bin/emcc" "--prefix" "/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5" "--configure-option" "--host=js-unknown-ghcjs" "--ghcjs-options=-fwrite-ide-info" "--enable-debug-info" "--disable-library-stripping" "--disable-executable-stripping" "-fghci" "--enable-profiling" "--enable-shared"
Configuring ghc-prim-0.6.1...
Setup: Version mismatch between ghcjs and ghcjs-pkg:
/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/bin/ghcjs was built
with GHC version 8.10.4
/nix/store/pwf36mvrl8hqqq0vkfksg0ikk430jbbs-ghcjs-8.10.5/bin/ghcjs-pkg was
built with GHC version 8.10.5

fatal: program ./Setup returned a nonzero exit code
```

I don't understand how they could end up being built with different ghc versions. As far as I understand, both are built by `8.10/stage0.nix`, which I'm guessing simply asks `cabal` to build everything. I don't see any magic in `ghcjs.cabal` that indicates the `Executable ghcjs` and `Executable ghcjs-pkg` binaries should be built with different ghc versions. As far as I know, the only ghc 8.10.5 that's getting built is ghcjs itself.

The above output is from commit https://github.com/falsifian/nixpkgs/commit/492400ab28dac6f7ed97db4ba989500c6e647b9e, which fixes some other issues with running `boot-ghcjs`.

**Comment by falsifian** [comment]
Well, I can work around the `Version mismatch` error in my previous comment with an awful hack: `sed -i 's/Version:        8.10.5/Version: 8.10.4/' ghcjs.cabal` in `configured-ghcjs-src.nix`. Now both versions are 8.10.4.

Next error I run into:
```
configuring package: ghc-prim
/build/configured-ghcjs-src/lib/boot/pkg/ghc-prim$ /nix/store/kp4hnhfkd7c6gf3fnb8z897nwnpvg5w7-ghc-8.10.4/bin/ghc "Setup.hs"
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )

Setup.hs:18:1: warning: [-Wdeprecations]
    Module `System.Cmd' is deprecated: Use "System.Process" instead
   |
18 | import System.Cmd
   | ^^^^^^^^^^^^^^^^^
Linking Setup ...
/nix/store/hy3lz2vfv9qq2v5jz9nzlx6mmiaq79rj-binutils-2.35.1/bin/ld.gold: warning: /nix/store/cvr0kjg2q7z2wwhjblx6c73rv422k8cm-glibc-2.33-47/lib/crt1.o: unknown program property type 0xc0008002 in .note.gnu.property section
/build/configured-ghcjs-src/lib/boot/pkg/ghc-prim$ ./Setup "configure" "--global" "--ghcjs" "--builddir" "dist" "--with-compiler" "/nix/store/zsvkx2hvl731ahyskxas94bf1b25gg8f-ghcjs-8.10.5/bin/ghcjs" "--with-hc-pkg" "/nix/store/zsvkx2hvl731ahyskxas94bf1b25gg8f-ghcjs-8.10.5/bin/ghcjs-pkg" "--with-haddock" "/nix/store/zsvkx2hvl731ahyskxas94bf1b25gg8f-ghcjs-8.10.5/bin/haddock" "--with-gcc" "/nix/store/zsvkx2hvl731ahyskxas94bf1b25gg8f-ghcjs-8.10.5/lib/bin/emcc" "--prefix" "/nix/store/zsvkx2hvl731ahyskxas94bf1b25gg8f-ghcjs-8.10.5" "--configure-option" "--host=js-unknown-ghcjs" "--ghcjs-options=-fwrite-ide-info" "--enable-debug-info" "--disable-library-stripping" "--disable-executable-stripping" "-fghci" "--enable-profiling" "--enable-shared"
Configuring ghc-prim-0.6.1...
/build/configured-ghcjs-src/lib/boot/pkg/ghc-prim$ ./Setup "build"
Preprocessing library for ghc-prim-0.6.1..
Building library for ghc-prim-0.6.1..
ghcjs: could not execute: /nix/store/bmq11559lj1mzfb6i0yvqdvw7sl9sgsm-emscripten-2.0.10/upstream/bin/clang
fatal: program ./Setup returned a nonzero exit code
note: keeping build directory '/tmp/nix-build-ghcjs-8.10.5.drv-31'
builder for '/nix/store/vj2syrraxfjpynzhbj88jcfj4scv2815-ghcjs-8.10.5.drv' failed with exit code 1
error: build of '/nix/store/vj2syrraxfjpynzhbj88jcfj4scv2815-ghcjs-8.10.5.drv' failed
```

At this point I don't think I have time to get it working; I'll just find some other way to run ghcjs. I will close this issue, but if anyone else feels like taking over, feel free to re-open!

**Comment by amesgen** [comment]
Just FTR: With [haskell.nix](https://input-output-hk.github.io/haskell.nix/), one can use GHCJS 8.10.5 via

```
nix-build -A projectCross.ghcjs.hsPkgs.your-package-name.components.exes.your-exe-name
```

**Comment by turion** [comment]
I'll reopen this issue because I think that it is immensely important that we support GHCJS! I don't have a concrete solution to these technical problems, but we should try working out a solution should be done in a PR.

**Comment by falsifian** [comment]
FYI, @dfordivam mentioned they have made some progress: https://github.com/ghcjs/ghcjs/issues/810#issuecomment-900769706

**Comment by cdepillabout** [comment]
GHCJS has been re-added in #137066 and is now available in `master`, although it is not being built by Hydra.
