### ISSUE TITLE
wiki: NixOS on Hetzner

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13327]
https://nixos.org/wiki/NixOS_on_Hetzner

**Comment by siddharthist** [comment]
Since this just consists of a link to a Google search, I don't think it needs to be migrated.

**Comment by garbas** [comment]
i think it wants to link to this https://invalidmagic.wordpress.com/2011/05/10/nix-os-on-a-hetzner-root-server/

**Comment by sgso** [comment]
The easiest way to install NixOS on Hetzner is to make NixOps do the hard work. Once it's finished, do a root login through NixOps, generate a local configuration and take over the system.
