### ISSUE TITLE
wiki: NixOS:obsolete and renamed

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13338]
https://nixos.org/wiki/NixOS:obsolete_and_renamed

**Comment by siddharthist** [comment]
Do we need to migrate this page? Obsolete options are always documented in the release notes. 

I'm also happy to migrate this (and talk specifically about release notes in that documentation). If we prefer that route, where should this go?

**Comment by garbas** [comment]
:+1:
