### ISSUE TITLE
Virtualbox can't launch any VMs

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#133341]
### Describe the bug
When trying to start any VM in VirtualBox it always crashes. VirtualBox stays open but VM can't be started.

### Steps To Reproduce
1. Enable `virtualisation.virtualbox.host.enable` and `virtualisation.virtualbox.host.enableExtensionPack`
2. Open VirtualBox
3. Start any VM

### Expected behavior
VM should start and be useable.

#### VirtualBox popup error

```console
Failed to open a session for the virtual machine someProject.

The VM session was aborted.

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: SessionMachine
Interface: ISession {c0447716-ff5a-4795-b57a-ecd5fffa18a4}
```

#### VirtualBox Log

```console
...
00:00:01.224169 AC97: Using codec 'AD1980'
00:00:01.224246 Audio: Initializing PulseAudio driver
00:00:01.224258 drvHostAudioPulseLibInitOnce: Failed to load library /nix/store/p7984nz4h8nw2wgzbh9ywln5abfbqf27-libpulseaudio-14.2/lib/libpulse.so.0: VERR_INVALID_PARAMETER
00:00:01.224264 PulseAudio: Failed to load the PulseAudio shared library! Error VERR_INVALID_PARAMETER
00:00:01.224285 AssertLogRel /build/VirtualBox-6.1.26/src/VBox/Devices/Audio/DevIchAc97.cpp(4544) int ichac97R3Construct(PPDMDEVINS, int, PCFGMNODE): RT_SUCCESS(rc)
00:00:01.224296 LUN#0: rc=VERR_INVALID_PARAMETER
00:00:01.224301 PDM: Failed to construct 'ichac97'/0! VERR_INVALID_PARAMETER (-2) - Invalid parameter.
00:00:01.224318 VMSetError: /build/VirtualBox-6.1.26/src/VBox/VMM/VMMR3/PDMDevice.cpp(474) int pdmR3DevInit(PVM); rc=VERR_INVALID_PARAMETER
00:00:01.224319 VMSetError: Failed to construct device 'ichac97' instance #0
```

#### Audio settings of VM

![image](https://user-images.githubusercontent.com/6047658/128863332-12375608-d7f1-4757-8c69-b3938578d5a3.png)

### Notify maintainers
@svanderburg

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.134, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(rhoriguchi): `""`
 - channels(root): `"nixos-21.11pre306790.0dde1033180"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
attribute:
- virtualbox
- virtualboxWithExtpack
module:
- virtualisation.virtualbox.host.enable
- virtualisation.virtualbox.host.enableExtensionPack
```

**Comment by casept** [comment]
I believe this is the same issue as https://github.com/NixOS/nixpkgs/issues/123851. The only workaround I've found so far is disabling audio completely for the VM.

**Comment by rhoriguchi** [comment]
> I believe this is the same issue as #123851. The only workaround I've found so far is disabling audio completely for the VM.

Yes, duplicate of #123851. Only solution that works for me is disabling audio.
