### ISSUE TITLE
wiki: NixOS:Properties

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13334]
https://nixos.org/wiki/NixOS:Properties

**Comment by ericsagnes** [comment]
Partially covered by http://nixos.org/nixos/manual/index.html#sec-option-definitions.

**Comment by garbas** [comment]
what we would need to add are:
- mkNotdef: Invalidate a definition. Any attribute which has this value is considered as not defined in the current module.
- mkThenElse { thenPart = definitions; elsePart = definitions; }: Create two different evaluations based on the result of all previous mkIf conditions.
- mkAlways: Ignore all previous mkIf conditions.
- mkOverrideTemplate priority template definitions: Set a priority level to all definitions which are enumerated inside the template. Only definitions with the lower priority level are kept. The default priority level is 100. An empty template is considered as all definitions.
- mkDefaultValue definitions: A shortcut notation to define default values (priority level of 1000) inside the configuration. This is extremely useful to avoid references to properties inside the user configuration while overriding the default value of the option. Any option define without this property will take precedence over it.
- mkOrder rank definitions: Add a rank value to definitions. This is useful for options where some dependences between definitions exist. A lower rank will add the definitions among the first definitions. The default rank is 100.
- mkHeader definitions: A shortcut notation to define a rank of 10 with mkOrder.
- mkFooter definitions: A shortcut notation to define a rank of 1000 with mkOrder.

**Comment by ericsagnes** [comment]
Note, the following are not present in lib so should be ignored:
- mkNotdef
- mkThenElse
- mkAlways
- mkHeader
- mkFooter

Not in that list but present in lib, so should be be documented:
- mkOptionDefault: priority 1001
- mkAssert: no trace of usage, to be deprecated?
- mkBefore: priority 500
- mkAfter: priority 1500
