### ISSUE TITLE
wiki: WICD

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13345]
https://nixos.org/wiki/WICD

**Comment by siddharthist** [comment]
I'm happy to migrate/enhance this. Where should it go?

**Comment by garbas** [comment]
- only move "Enable wicd, disable other networking" to ``networking.wicd.enable`` option
- find somebody that uses ``wicd`` that can verify that documentation is actually correct

i don't see a value to actually document how to debug wireless adapters.

@siddhanathan does it makes sense?

**Comment by siddharthist** [comment]
@garbas Could you direct me to a place in the manual where this information should go?
