### ISSUE TITLE
wiki: Wpa supplicant

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13342]
https://nixos.org/wiki/Wpa_supplicant

**Comment by Zimmi48** [comment]
There is already a section in the manual on that http://nixos.org/nixos/manual/index.html#sec-wireless and it mostly contains the same information.

The "User configuration" and "I'm on a LiveCD and I can't manually connect to any wireless network" sections are not reproduced in the manual but I am not sure they bring any significant value.

More specifically, the first of this two sections is not specific to NixOS I think. People can find more information on how to configure wpa_supplicant via other sources. The wiki page was far from complete in that respect.

The LiveCD troubleshooting section is not really relevant for most users, who are encouraged to use the graphical LiveCD. The graphical LiveCD comes with NetworkManager and a graphical tool to connect to a wifi network. As for people who are crazy enough to boot from the non-graphical LiveCD while not having access to an Ethernet connection, they should probably be experimented enough to figure out what to do by themselves.

So I'd say we can close this issue, but other people may want to voice disagreeing opinions...

**Comment by grahamc** [comment]
Exists at: https://web.archive.org/web/20160829175608/https://nixos.org/wiki/Wpa_supplicant
