### ISSUE TITLE
wiki: Setup Mesos

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13341]
https://nixos.org/wiki/Setup_Mesos

**Comment by kamilchm** [comment]
@kevincox could you write something about your cluster setup?

**Comment by kevincox** [comment]
Yeah, I'll do that when I get some time. Feel free to assign me to this.

**Comment by kevincox** [comment]
I don't appear to have permission to edit pages. I don't know if this is because I haven't confirmed my email address (sending mail is failing) but if it is a permissions issue could you give write permission to `kevincox`. Thanks.
