### ISSUE TITLE
Neovide: Build fails in Flake

### ISSUE THREAD

**Issue by enderger** [NixOS/nixpkgs#133409]
### Describe the bug
When building using Flakes, Neovide fails to build.

### Steps To Reproduce
1. Enable [Flakes](https://nixos.wiki/wiki/flakes)
2. Run the command `nix build nixpkgs#neovide`
3. See build failure

### Expected behavior
A successful build of Neovide

### Screenshots
![Screenshot_20210810_115153](https://user-images.githubusercontent.com/36283171/128918226-fbe8e1b9-31c3-4f2e-95d4-9f11f463bcd6.png)
![image](https://user-images.githubusercontent.com/36283171/128918382-f82abb22-8ce1-4c0f-9fdb-7bf8a68f4aea.png)

### Additional context
I suspect this is caused by running in pure evaluation mode, as it builds fine using the legacy commands.

### Notify maintainers
@ck3d 

### Metadata
```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11pre304909.d0044b0e7d5 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"home-manager, nixos-21.11pre304909.d0044b0e7d5"`
 - channels(enderger): `"home-manager, nixos-21.11pre307874.740ecbc1627"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
 - neovide
# a list of nixos modules affected by the problem
module:
```

**Comment by ck3d** [comment]
Thanks for raising this issue. I created a PR to fix it.

Side note, the same compilation error happens also with nix-build.
