### ISSUE TITLE
KDE5 Cannot download kde-l10n-ca-15.04.3.tar.xz from any mirror

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#13359]
On the latest 15.09, running this:

```
environment.systemPackages = with pkgs; [...] ++ builtins.filter lib.isDerivation (builtins.attrValues kdeApps_stable);
```

Doesn't work because of kde-l10n-ca-15.04.3.tar.xz.

No mirrors work. Tried it several times over different days, I think the source urls might need to be updated.

@ttuegel

**Comment by vcunat** [comment]
Apparently they removed 15.04.3 from their official mirrors, not just moved like dealt with in 85f5c12468a50, as I can't find the files in http://download.kde.org/ls-lR :-/

**Comment by vcunat** [comment]
Some of the tarballs are on tarballs.nixos.org but not all of them.

**Comment by vcunat** [comment]
Oh, I've made a typo and missed the moved files.

**Comment by vcunat** [comment]
Fixed.

**Comment by CMCDragonkai** [comment]
Awesome. By the way, how did you fix it?

**Comment by vcunat** [comment]
I just replaced the URLs. `%s:stable/applications/15.04.3:Attic/applications/15.04.3:g`
