### ISSUE TITLE
wiki: Zero Hydra Failures

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13354]
https://nixos.org/wiki/Zero_Hydra_Failures

**Comment by 7c6f434c** [comment]
Is it a good idea to create an issue for every failing build and assign them to a `ZHF` (or `ZHF-16.10`) milestone? I think this wiki page was used mostly as a progress tracker.

**Comment by garbas** [comment]
@domenkozar would you be able to tackle this documentation. i think this should be part of release process, right?

**Comment by domenkozar** [comment]
This is now documented under release process
