### ISSUE TITLE
Package request: Indigenous-desktop : an IndieWeb sites reader

### ISSUE THREAD

**Issue by marek-lach** [NixOS/nixpkgs#133505]
**Project description**
A desktop reader client for [IndieWeb](https://indieweb.org) compliant sites.

**Metadata**

* homepage URL: https://indigenous.realize.be/indigenous-desktop
* source URL: https://github.com/swentel/indigenous-desktop (https://github.com/swentel/indigenous-desktop/releases)
* license: gpl3
* platforms: unix, linux

**Comment by WolfangAukang** [comment]
Merged
