### ISSUE TITLE
wiki: Installing Hydra on Ubuntu

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13353]
https://nixos.org/wiki/Installing_Hydra_on_Ubuntu

**Comment by garbas** [comment]
@ctheune i will assign all the hydra related wiki tickets to you. if you get a chance to move documentation to hydra manual yourself great, if not I (or somebody else) will.

**Comment by gilligan** [comment]
This description is inaccurate. Starting with the `nix-env -i hydra`  - and even if you install hydra otherwise it will fail because there is no `.nix-profile/share/hydra` directory after successful installation. The postgres configuration is also not correct anymore.
