### ISSUE TITLE
wiki: Hydra.nixos.org

### ISSUE THREAD

**Issue by garbas** [NixOS/nixpkgs#13352]
https://nixos.org/wiki/Hydra.nixos.org
https://nixos.org/wiki/Hydra

**Comment by zimbatm** [comment]
Is the machine list still accurate ? I'm tempted to close this-one unless we want to import the machine list in https://github.com/NixOS/nixos-org-configurations ?

**Comment by garbas** [comment]
i think this is a question for @rbvermaa

**Comment by garbas** [comment]
also pinging @ctheune as next hydra release manager
