### ISSUE TITLE
After upgrading environment, `gist` command fails

### ISSUE THREAD

**Issue by maurer** [NixOS/nixpkgs#13374]
After running `nix-env -u --always` to update my environment, the `gist` command fails. I suspect this is due to a dependency that is failing to be capured in a build product, since the error seems to suggest a ru by module required by gist disappeared.

```
[maurer@fragarach:~]$ gist
/nix/store/ffa9fzypzwxw8gggwsgw60c1wmymh1ar-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /nix/store/ffa9fzypzwxw8gggwsgw60c1wmymh1ar-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/maurer/.nix-profile/bin/gist:16:in `<main>'

[maurer@fragarach:~]$ which gist
/home/maurer/.nix-profile/bin/gist
```

**Comment by maurer** [comment]
@cstrahan You were the last one to edit the file, so I figured I'd bring it to your attention.

**Comment by colemickens** [comment]
+1

**Comment by zimbatm** [comment]
Which version of gist is that ? 4.5.0 from master should work fine.

**Comment by colemickens** [comment]
I'm on nixos-unstable plus a few local changes that shouldn't affect gist or anything ruby related.

`t` (twitter client) was broken too, but I just removed it since I wasn't using it.

```
$ gist --version

/nix/store/h4sibipp5fp83nk100mrp8qhypvd8lr9-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /nix/store/h4sibipp5fp83nk100mrp8qhypvd8lr9-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /run/current-system/sw/bin/gist:16:in `<main>'

```

**Comment by zimbatm** [comment]
Okay, it's not working on unstable but it's fixed in master. Any days now :)

**Comment by fpletz** [comment]
As we're already having so many open tickets that won't get closed because people forget about them after they're fixed and it is indeed also working fine for me on master, I'm closing this for now. If you have problems after the next channel release, please feel free to reopen. Thanks!
