### ISSUE TITLE
proj: Not supported on darwin (Even though it is)

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#13370]
Currently the ["proj" nix-expression](https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/pkgs/development/libraries/proj/default.nix) only lists 
`platforms = platforms.linux;` as supported.
It however also compiles fine on OS X. I don't have a way to check if the package will work for `platforms.all` or `platforms.unix`, so I'm unsure if I should add a pull request which adds only `platforms.darwin` to the supported list or something different.

**Comment by dezgeg** [comment]
It's fine to change it to `platforms.linux ++ platforms.darwin`.
