### ISSUE TITLE
unable to install jdk in nixos/nix docker, selector 'jdk*' matches not derivations

### ISSUE THREAD

**Issue by scalavision** [NixOS/nixpkgs#133786]
### Describe the bug

Not able to install any jdk* version when using docker nixos 

### Steps To Reproduce

Create a docker file:

```dockerfile
FROM nixos/nix

RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update

RUN nix-env --install nixpkgs.jdk8 || nix-env --install nixos.jdk8 || nix-env --install jdk8 || \
  nix-env --install nixpkgs.jdk11 || nix-env --install nixos.jdk11 || nix-env --install jdk11 || \
  nix-env --install nixpkgs.jdk16 || nix-env --install nixos.jdk16 || nix-env --install jdk16
```

I also tried using openjdk instead of jdk, but that did also not work.

bash:

```bash
docker build -t .
```

### Expected behavior

jdk should install, I tried using other packages in the same way and they
install flawlessly.

### Additional context

I now you can now do program.java=enable, but that only works in NixOS right?
The use of prefix like nixpkgs, nixos has always been confusing to me, so maybe I
did something wrong in this regard?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, Alpine Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixpkgs-21.11pre309233.70dc433f2eb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, Alpine Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixpkgs-21.11pre309233.70dc433f2eb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by GuillaumeDesforges** [comment]
Could you provide the error message as well please?

**Comment by GuillaumeDesforges** [comment]
> error: selector 'jdk8' matches no derivations

Means it can't find a package you called `jdk8`.

I'd recommend having a look at https://nixos.org/manual/nix/stable/#ch-basic-package-mgmt

On NixOS:
```
$ nix-env -iA nixos.jdk8
```

on non-NixOS:
```
$ nix-env -iA nixpkgs.jdk8
```

This is not an issue with nixpkgs. You can ask for more help on any Nix beginner channel. 😉

**Comment by scalavision** [comment]
yes, but jdk should be available both in `nixpkgs` and `nixos` channel i think, so there must be something wrong with the way that names resolution works. I can't see why some of the packages are found and not this one. I'll try to install it directly from the git archive in the evening and see if that works :-) I'll also post a follow up on Discourse when I have time.

**Comment by scalavision** [comment]
Thanks a lot for looking into this @GuillaumeDesforges , it seems that:

```bash
nix-env -iA nixos.jdk8`
```

is not working for me inside the Docker container. Maybe after `channel --update`, the name resolution isn't properly propagated in Docker.

So I've found out that to get this to work inside `Dockerfile`, you need to use the `-f` flag, hence this works:

```bash
RUN nix-env -f '<nixpkgs>' -iA jdk8
```

Sadly I do nix things more occasionally these days, so a bit rusty, should of course have thought to try this as well.

**Comment by scalavision** [comment]
I was sure I tested this approach earlier as well, nevertheless it works now:

```bash
nix-env -iA nixpkgs.jdk8
```

**Comment by GuillaumeDesforges** [comment]
On a note: I had not seen you were not on NixOS. Maybe just `nix-env -iA nixpkgs.jdk8` would do the trick

Btw if you are using dockerfile you can probably copy a Nix file with the proper package (or nix flake) and install from it, it'll relieve you of over complicated code in Dockerfile. Though this is an opinionated choice.
