### ISSUE TITLE
HiDPI support in Steam

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#133715]
### Describe the bug
It would be good if Steam automatically would take into account either the `hardware.video.hidpi.enable` or `services.xserver.dpi` setting to scale the UI, or if there was a separate setting to scale it. The default UI on a 13 inch 4k screen is pretty much impossible to read.

### Steps To Reproduce
1. Acquire a HiDPI monitor
2. Install GNOME, Wayland and Steam
3. Run Steam in GNOME/Wayland

### Expected behavior

The text should be similar in size to the default GNOME UI text

### Screenshots
Compare the window decoration to the Steam menu:

![Screenshot from 2021-08-13 19-38-10](https://user-images.githubusercontent.com/168301/129321781-3d74aadb-c71b-4634-b006-a6f8f8dd00b1.png)

### Metadata 

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.2001.d4590d21006 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2455.ad6e733d633"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FossPrime** [comment]
This issue is specially problematic in NixOS

Normally we could edit the .desktop file and call it a day. In NIxOS those are mounted read-only, so `/run/current-system/sw/share/applications/steam.desktop` cannot be modified or removed.

All the suggestions in https://github.com/ValveSoftware/steam-for-linux/issues/5460 will not work on steam OS.

Setting GDK_SCALE=2 globally makes some apps like Chrome, 4X size.

**Comment by l0b0** [comment]
I'm not in the beta client program, but scaling seems to be much better now, both in terms of scaling and contrast:

![Screenshot from 2023-05-17 16-37-15](https://github.com/NixOS/nixpkgs/assets/168301/e5a59f4e-4aae-4ea4-b298-09132fe5da1f)

**Comment by l0b0** [comment]
It's broken again. Compare the GitHub UI with Steam:
![Screenshot from 2023-06-16 17-30-53](https://github.com/NixOS/nixpkgs/assets/168301/9577047c-4741-4224-adee-64a066fdeb3b)

**Comment by l0b0** [comment]
And fixed again with the latest update! :grin:

**Comment by FossPrime** [comment]
For some reason I still get a 1x scale client... but at least now the client gives us more options.

I'm using a HiDPI laptop and all external displays would be large enough to be comfortable at 2x scale even if they are not HiDPI... so I'm just going to force steam into 2x scale all the time... this works after a restart... in hindsight a relogin should also work.

```
  environment.sessionVariables = {
    STEAM_FORCE_DESKTOPUI_SCALING = "2";
  };
```

Then `nixos-rebuild switch`
