### ISSUE TITLE
Spurious syntax error in config.nix

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#13384]
If I execute nix-env it stops with the following error:
`error: syntax error, unexpected $end, at /home/username/.nixpkgs/config.nix:1:1`
and this is my ~/.nixpkgs/config.nix 

`{pkgs}: {allowUnfree=true;}`

the strange thing is the error disappear only if I delete config.nix,if I  comment those lines the error remain the same

**Comment by fkz** [comment]
an empty file (or file only consisting of comments) is not a valid nix file, e. g.

    $ echo "" > test.nix
    $ nix-instantiate  --parse test.nix
    error: syntax error, unexpected $end, at test.nix:1:1

A default config.nix would be just the empty set `{}`

Don't see a problem with your line `{pkgs}: {allowUnfree=true;}`

**Comment by zimbatm** [comment]
Try just declaring your config instead of wrapping it in a function. If you replace it with `{allowUnfree=true;}` it will work. The error message is not really helpful.

**Comment by joachifm** [comment]
@pasqui23 I'm closing this issue as I belive the problem has been resolved. Please reopen if that is not the case.
