### ISSUE TITLE
pkgs.formats.yaml does not generate the well known YAML although JSON is a subset of YAML

### ISSUE THREAD

**Issue by lucasew** [NixOS/nixpkgs#133802]
### Describe the bug
`pkgs.formats.yaml` is using the same generation function as the JSON one

I am without time to focus on this but I want to let you know about.

### Steps To Reproduce

```nix
# on nix repl assuming pkgs as import <nixpkgs> {}

yaml = pkgs.formats.yaml {}
:b yaml.generate "test.yaml" {test = 2;}
```

### Expected behavior
It will derivate a JSON file instead of a YAML one

The test is also broken: https://github.com/NixOS/nixpkgs/blob/9bd0578528cb8873732d1400133e120ed6ede73f/pkgs/pkgs-lib/tests/formats.nix

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
lucasew@acer-nix ~ 0$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.20210710.cf59fbd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210601_5985b8b`
 - nixpkgs: `/nix/store/yh05k932arpkhblqrxnjcp28fpqh7nia-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  formats.yaml
# a list of nixos modules affected by the problem
module:
```

**Comment by hmenke** [comment]
YAML 1.2 is a strict superset of JSON, hence any valid JSON is valid YAML 1.2

**Comment by lucasew** [comment]
But some software like `espanso` doesn't support this.

It doesn't work at all and people are not using this function to generate YAML files in package definitions.

In this case of the superset they can just use the JSON generate function.

**Comment by mohe2015** [comment]
If you mean https://github.com/federico-terzi/espanso it should work because it uses https://github.com/federico-terzi/espanso/search?q=yaml https://github.com/dtolnay/serde-yaml which uses https://github.com/chyh1990/yaml-rust which claims to support YAML 1.2.

Is there an error message that indicates this is not the case or may there be an other issue?

**Comment by hmenke** [comment]
Then `espanso` (whatever that is) should upgrade their YAML parser to understand YAML 1.2 which by now is almost 12 years old.

**Comment by lucasew** [comment]
That was a schema error :facepalm: 

BTW why is there a YAML format exporter if it's the same as JSON?

**Comment by mohe2015** [comment]
> BTW why is there a YAML format exporter if it's the same as JSON?

Probably for people who don't know this and so you know you could use extended features of yaml. Maybe also so the implementation could be changed later.

**Comment by lucasew** [comment]
I can't reopen it xD

**Comment by mohe2015** [comment]
Funny.
I assume you would like that pkgs.format.yaml generates what most people understand as YAML. I think this may be a good idea as I have seen people being irritated by that in the past.

@lucasew Maybe change the title accordingly?

**Comment by rnhmjoj** [comment]
I too would support `formats.yaml` producing proper YAML. The current way is perfectly valid, but as exemplified by this issue, counterintuitive.

**Comment by lucasew** [comment]
I've already sent a PR, I basically just need to rename the commit xD

**Comment by mohe2015** [comment]
Ref https://github.com/NixOS/nixpkgs/pull/133807
