### ISSUE TITLE
liferea 1.10.18 (downloaded 22-02-2016) fails to compile

### ISSUE THREAD

**Issue by paulgevers** [NixOS/nixpkgs#13380]
For Debian, I just downloaded 1.10.18, but it fails to build due to the relocation of the notifications. The patch below fixes the issue.

Description: the location of the notification.(c|h) files changed
Author: Paul Gevers <elbrus@debian.org>

Index: liferea/src/notification/libnotify.c
===================================================================
--- liferea.orig/src/notification/libnotify.c
+++ liferea/src/notification/libnotify.c
@@ -40,7 +40,7 @@
 #include "ui/feed_list_view.h"
 #include "ui/ui_tray.h"
 
-#include "notification/notification.h"
+#include "notification.h"
 
 static gboolean supports_actions = FALSE;
 static gboolean supports_append  = FALSE;
Index: liferea/po/POTFILES.in
===================================================================
--- liferea.orig/po/POTFILES.in
+++ liferea/po/POTFILES.in
@@ -185,8 +185,8 @@ src/fl_sources/theoldreader_source_feed.
 src/fl_sources/theoldreader_source_feed_list.c
 src/fl_sources/theoldreader_source_feed_list.h
 src/notification/libnotify.c
-src/notification/notification.c
-src/notification/notification.h
+src/notification.c
+src/notification.h
 src/webkit/webkit.c
 [type: gettext/glade]glade/auth.ui
 [type: gettext/glade]glade/google_source.ui

**Comment by vcunat** [comment]
I assume you're using an older channel? It builds fine for me on master (and 15.09).

**Comment by paulgevers** [comment]
What is a channel in this respect? I just downloaded the file here: https://github.com/lwindolf/liferea/archive/v1.10.18.tar.gz yesterday. Don't know if that is the older channel?

**Comment by paulgevers** [comment]
Hmm, I am not sure how I ended up here. I wanted to be somewhere else (on the liferea bug tracker).

**Comment by vcunat** [comment]
@paulgevers: the upstream (liferea itself) had this reported and fixed already, too.
