### ISSUE TITLE
Bump Kernel to latest longterm 4.4 for 16.03 release

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#13394]
According to https://www.kernel.org/category/releases.html, `4.4` will be supported until 2018. Let's bump this before the branch-off.

**Comment by domenkozar** [comment]
I'll push a commit as soon as we have a channel update.

**Comment by vcunat** [comment]
4.4 is relatively new, but I guess it will be fine enough before the release happens.

**Comment by edolstra** [comment]
:+1:

**Comment by fpletz** [comment]
I'm running 4.4 on my laptop and some VMs without any problems since it was released, so :beers: from me.

**Comment by NeQuissimus** [comment]
+1 from me, 4.4 has been very stable for me, too.

**Comment by heydojo** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/ati-drivers/default.nix#L18
I have a solution, it needs review, maybe some discussion and maybe some help testing would be useful (although it is very well tested and works for me.)

What would be the cut off point for proposing it because I am very busy at the moment.
Thanks.

**Comment by vcunat** [comment]
> What would be the cut off point for proposing it

Patches to make the drivers work on other kernel versions should be accepted even after releasing, but the sooner the better.

**Comment by heydojo** [comment]
> Patches to make the drivers work on other kernel versions should be accepted even after releasing, but the sooner the better.

It is not that trivial. I really have next to zero free time until the weekend also.

**Comment by vcunat** [comment]
I still don't think it should be a problem in this case. But anyway, the work should go to master first, regardless of 16.03.

**Comment by domenkozar** [comment]
@heydojo thanks for pointing that out. If you're confident it's possible to fix ati drivers to work with kernel 4.4, it's also fine if we fix that later in March. We've done the same for 15.09 release.

**Comment by domenkozar** [comment]
Pushed as all tests now pass for NixOS.

**Comment by heydojo** [comment]
Some really great reasons for 4.4 to be the default can be found here: http://kernelnewbies.org/LinuxChanges

By the looks of it 

> Faster and leaner loop device with Direct I/O and Asynchronous I/O support

and

> 3D support in virtual GPU driver

are really nice improvements.
