### ISSUE TITLE
openssl broken on darwin

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#13401]
## Basic info

* Kernel: Darwin yoneda.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
* Nix version: 1.10
* Nixpkgs version: 16.03pre-git

## openssl is broken on darwin
```
% nix-env -i openssl                                                                                                                                                            ✭
installing ‘openssl-1.0.2f’
these derivations will be built:
  /nix/store/bsr4hs13qnywhn03zcnfhybwyll53jn0-openssl-1.0.2f.drv
building path(s) ‘/nix/store/ljlwsz12xzychazgvrk0b6jj4vnxv9kq-openssl-1.0.2f-man’, ‘/nix/store/ryqsi5hxbdpkh8mn7mzzl1rn8cl6kas3-openssl-1.0.2f’
unpacking sources
unpacking source archive /nix/store/3sni74rpjihw3scr68q1267s4iyn06m6-openssl-1.0.2f.tar.gz
source root is openssl-1.0.2f
setting SOURCE_DATE_EPOCH to timestamp 1453989443 of file openssl-1.0.2f/tools/c_rehash
patching sources
applying patch /nix/store/k8vd1ipx16i7biim8h1hq6n4w53ih1xm-use-etc-ssl-certs.patch
patching file crypto/cryptlib.h
Hunk #1 succeeded at 81 with fuzz 1.
applying patch /nix/store/gsh35p2jcp7nvgmk8zskm2vw06hlzjrc-darwin-arch.patch
patching file Configure
Hunk #1 FAILED at 579.
1 out of 1 hunk FAILED -- saving rejects to file Configure.rej
builder for ‘/nix/store/bsr4hs13qnywhn03zcnfhybwyll53jn0-openssl-1.0.2f.drv’ failed with exit code 1
error: build of ‘/nix/store/bsr4hs13qnywhn03zcnfhybwyll53jn0-openssl-1.0.2f.drv’ failed
```
This problem is apparently introduced by  917ca8920da46b94867a01590423f66390a152c0 and cc2cec63007f6974130a7ba8a491761be5887528

**Comment by gilligan** [comment]
@edolstra can you have a look at those ?

**Comment by knedlsepp** [comment]
Doing a `nix-channel --update` and a `nix-env -i openssl` on OS X did simply download the openssl-1.0.2f binary and install fine for me.

**Comment by gilligan** [comment]
@knedlsepp  uuhm.. well I happened to do a `nix-shell -p nodejs-5_x` which tries to build openssl and fails with the output I pasted above. I'm the newbie here so if I am doing something silly which is entirely possible I am all ears ;)

**Comment by gilligan** [comment]
@knedlsepp  uuhm.. well I happened to do a `nix-shell -p nodejs-5_x` which tries to build openssl and fails with the output I pasted above. I'm the newbie here so if I am doing something silly which is entirely possible I am all ears ;)

**Comment by vcunat** [comment]
@knedlsepp: that's a different openssl version. We have 1.0.1* as the default and 1.0.2* for a few cases including nodejs.

**Comment by vcunat** [comment]
Ah, I'm sorry, I looked wrong and got confused about our defaults by attribute and nix-env names aren't always consistent.

**Comment by gilligan** [comment]
Added the full build output for `openssl` above

**Comment by vcunat** [comment]
I can't see the full log. (Note: I won't really debug this myself, as I don't even have any darwin machine.)

**Comment by gilligan** [comment]
@vcunat what other info can I provide?

**Comment by knedlsepp** [comment]
@gilligan I also only started using nix recently. What was really helpful in finding problems was to follow these instructions: https://nixos.org/wiki/Debugging_a_Nix_Package "Step Through Build Phases" and then view the step by step output. You should try to find out why "patching file Configure
Hunk #1 FAILED at 579."

**Comment by vcunat** [comment]
No use stepping here. The patch doesn't apply. It probably did before some version bump but no longer does. Someone has to decide if it's still needed and either drop it or port it to the new version.

**Comment by gilligan** [comment]
@knedlsepp @vcunat yes the actual error is obvious: the patch fails. I am just not able to judge this. Since @edolstra made the last changes I hope he could shed some light on this.

**Comment by domenkozar** [comment]
cc @copumpkin

**Comment by gilligan** [comment]
@domenkozar will try your fix. Building will just take some time ...

**Comment by gilligan** [comment]
@domenkozar openssl builds just fine now. I did the silly mistake of wanting to try this via `nix-env -i nodejs_5-x` which is how I initially noticed the problem but that lead to compilation that went on through the whole night and still has not fnished ..

Anyway .. `nix-shell -p openssl` just finished without any issue and installed `openssl-1.0.1-r`

**Comment by vcunat** [comment]
> Anyway .. nix-shell -p openssl just finished without any issue and installed openssl-1.0.1-r

That's a different openssl version. The one with problems would be tested by `nix-shell -p openssl_1_0_2`.

**Comment by gilligan** [comment]
Sorry, my bad. Tried again now building the correct version. Works
```
[nix-shell:~/nixpkgs]$ openssl
OpenSSL> version
OpenSSL 1.0.2f  28 Jan 2016
OpenSSL>
───────────
```
