### ISSUE TITLE
rkt should be complied with the "kvm" stage1

### ISSUE THREAD

**Issue by mbsulliv** [NixOS/nixpkgs#13413]
## Basic info
- Kernel: Linux pc-mbsulliv2 3.18.25 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
- System: 15.09.git.c734df8 (Dingo)
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: "15.09.911.53286a8"
## Describe your issue here

I tried adding the "kvm" stage1 option to stage1Flavours in "pkgs/applications/virtualization/rkt/default.nix" and I got two errors.  I fixed the missing dependency on "bc" but then hit a problem where wget was used to download linux resources at https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.1.3.tar.xz.  I suspect that wget isn't a sanctioned action during a build script, but I don't know how to fix the problem.
### Expected result

"kvm" should be included in the stage1Flavours by default.
### Actual result

...
  WGET         https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.1.3.tar.xz => build-rkt-1.0.0/tmp/usr_from_kvm/kernel/linux-4.1.3.tar.xz
stage1/usr_from_kvm/kernel.mk:92: recipe for target '/tmp/nix-build-rkt-1.0.0.drv-0/rkt-v1.0.0-src/build-rkt-1.0.0/tmp/usr_from_kvm/kernel/linux-4.1.3.tar.xz' failed
make: **\* [/tmp/nix-build-rkt-1.0.0.drv-0/rkt-v1.0.0-src/build-rkt-1.0.0/tmp/usr_from_kvm/kernel/linux-4.1.3.tar.xz] Error 5
builder for ‘/nix/store/yyvvdvdiiysikw2ckfgrr8wxjl2ygr41-rkt-1.0.0.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/xxxwzg61gr9k3haqwy9k9azc40mqghm4-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jbs5nr4hb5r7cn1x3cmhxlhj3z06d0yw-nixos-15.09.git.d5f3723M.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jbs5nr4hb5r7cn1x3cmhxlhj3z06d0yw-nixos-15.09.git.d5f3723M.drv’ failed
### Steps to reproduce

1) In "pkgs/applications/virtualization/rkt/default.nix", set: stage1Flavours = [ "coreos" "fly" "host" "kvm" ];
2) Rebuild

**Comment by mbsulliv** [comment]
I don't think I've characterized this correctly.  Closing for now until I've had more time to debug the problem.

**Comment by andrewchambers** [comment]
would be neat to have.
