### ISSUE TITLE
Creating, Wrapping postgres extensions and playing nicely 

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nixpkgs#13410]
I am trying to wrap this postgres extension for nixpkgs https://github.com/eulerto/pg_similarity

my nix expression is: 

``` nix
{ stdenv, fetchFromGitHub, gcc, postgresql } :

stdenv.mkDerivation rec {
  name = "pg_similarity";
  src = fetchFromGitHub {
    owner = "eulerto";
    repo = "pg_similarity";
    rev = "adacf8ab8f6ed8304ff4c5dcffbf0378656091e1";
    sha256 = "1a40n405d37ichwmnz57wasb03jp7jiygac98zxdqr1zlkmjy4rd";
  };
  builder = ./builder.sh;
  buildInputs = [ postgresql gcc ];
  meta = {
    description = "Some functions";
    platforms = stdenv.lib.platforms.linux;
    license = stdenv.lib.licenses.gpl2;
  };
}
```

and my builder is: 

``` shell
# -*- shell-script -*-
source $stdenv/setup

chmod -R 755 $src

chmod -R 755 $(pg_config --libdir)
chmod -R 755 $(pg_config --sharedir)

cd $src

USE_PGXS=1 make
USE_PGXS=1 make install

mkdir -p $out
```

And this is crapping out at runtime when I try to use the extension with 
`create extension pg_similarity` in psql. 

I found some old threads with mentioning this but no real resolution and I see postgis in nixpkgs but it looks like its specialized for postgis, not a generic solution. 

What is the right way to install postgres extensions via nix? 

EDIT: Apparently there is a `postgresqlWithPlugins` but doesn't make much sense to me and the only example usages are like `postgis` which has a rather complicated build process.

**Comment by danbst** [comment]
As author says, there is postgresqlWithPlugins for such things. Ive showed in #21220 how to do this with nixos postgresql service.

@7c6f434c can you close this?
