### ISSUE TITLE
cargo searches specific system directories for SSL certs

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#13414]
See https://github.com/sfackler/rust-openssl/blob/3ca5ecac7427cd37947352552cc517c7db8fd4fd/openssl-sys/src/probe.rs#L14

This should be patched out (or env var support patched in), but I'm not familiar enough with the rust builders to figure out where to start.

**Comment by domenkozar** [comment]
This is fixed now right?

**Comment by pikajude** [comment]
Not as far as I know. What would have fixed it?

**Comment by abbradar** [comment]
I think I've fixed it in https://github.com/abbradar/nixpkgs/commit/57d074525b2dc16001b20ef1501fef845cc474be. I'll merge this along with Rust/Cargo unstable updates if I succeed building all of them.

**Comment by abbradar** [comment]
Oh, sorry -- I misunderstood this for another bug where SSL certs are not found for `fetchcargo`. I don't think this should be fixed -- `rust-openssl` honors usual `SSL_CERT_FILE` environment variable, so this would work on both NixOS and non-NixOS now.

**Comment by matthiasbeyer** [comment]
Can confirm. Calling cargo with `SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt cargo build` works.

**Comment by jagajaga** [comment]
Works for me nowadays.

**Comment by matthiasbeyer** [comment]
not for me as unstable wasn't updated yet.
