### ISSUE TITLE
The bluedevil shows no adapters when using KDE5 on 15.09 branch 

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#13417]
My bluetooth is definitely working as:

```
>  hcitool dev                                                                                                                    ~
Devices:
        hci0    34:02:86:68:D5:1B
> rfkill list                                                                                                                    ~
0: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
```

Also I was able to scan my phone from the console.

However inside KDE5's bluedevil GUI app, there's no bluetooth adapters shown. This I guess might have something to do with bluez4 vs bluez5 (as bluez4 is still the default for both KDE4 and KDE5 on 15.09, but on master, bluez5 is now used if you don't use KDE4). I wasn't able to test whether bluez5 would make it work, because the 15.09 branch bluez5 has a bad upstream URL.

i.e. this doesn't work on 15.09:

```
        nixpkgs.config = {
            packageOverrides = pkgs: {
                bluez = pkgs.bluez5; # bluez by default is still bluez4, here we use bluez5 for kde5
            };
        };
```

Rebuilds was stuck trying to install:

```
trying http://www.freedesktop.org/software/media-player-info/media-player-info-22.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:44 --:--:--     0
```

**Comment by CMCDragonkai** [comment]
@ttuegel

**Comment by ttuegel** [comment]
I'm afraid I can't help here because I don't have any Bluetooth-capable hardware.

**Comment by heydojo** [comment]
We fixed this in unstable about a few weeks ago @abbradar made the final changes needed to switch to bluez5 by default unless you use kde4 and I have working bluetooth here in kde5.
Please look to the next release for this as an added feature.
https://github.com/NixOS/nixpkgs/commit/ddfb660f7bb2dfc203f9d25be381211271f33238

**Comment by CMCDragonkai** [comment]
I see. Why not backport the conditional of switching to bluez5 when using
kde5.

**Comment by CMCDragonkai** [comment]
Specifically referring to this line:

```
    bluez-bluetooth = if config.services.xserver.desktopManager.kde4.enable then pkgs.bluez else pkgs.bluez5;
```

At https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/hardware/bluetooth.nix#L5

**Comment by heydojo** [comment]
> Why not backport the conditional of switching to bluez5 when using
kde5.

Please feel free to do so. It is however, not that trivial. @ttuegel has done a huge amount of work on kde 5 between what is in 15.09 and what is in unstable now. There is talk on the mailing list of preparing for the next release. I cannot see any urgent need to back port this as it does not affect security. I do not run 15.09 and so have no way to test, or the time to confirm that it would even work.
