### ISSUE TITLE
Remnote

### ISSUE THREAD

**Issue by faldor20** [NixOS/nixpkgs#134279]
**Project description**
Remnote is a linked note taking, outliner similar to roam research or logseq. It has a strong focus on spaced repetition and making flash cards.
It is based on electron.
**Metadata**

* homepage URL:https://www.remnote.io
* source URL:N/A
* license: Proprietary 
* platforms: unix, linux, darwin, windows

**Comment by figsoda** [comment]
packaged in #170711
