### ISSUE TITLE
qview: opening webp images does not work (but should)

### ISSUE THREAD

**Issue by Jiehong** [NixOS/nixpkgs#134210]
### Describe the bug
qview support a list of images format, including webp:

https://interversehq.com/qview/formats/

However, if you try opening a webp image in nixos, you get "unsupported image format".

This format is listed as "optional", so it might just be a matter of activating it somehow.

### Steps To Reproduce
1. install qview with nex
2. run "qview image.webp"
3. see error message

### Expected behavior
Image should be opened.

### Screenshots
Not needed

### Notify maintainers
@acowley 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19, NixOS, 21.05.2428.2d6ab6c6b92 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2478.a445f582988"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by acowley** [comment]
I wonder if this is something we’d need to add in the nix Qt build itself.
