### ISSUE TITLE
Building (and packaging) Rumprun Unikernel

### ISSUE THREAD

**Issue by paspanag** [NixOS/nixpkgs#13432]
- Kernel: 4.3.4 x86_64
- System: Nixos 16.03pre76756.885acea
- Nix version: 1.11.1
- Nixpkgs version: 16.03pre76756.885acea

Hi guys, I'm having a hard time building the rumprun unikernel. Specifically it's having troubles resolving the machine/cdefs.h header.

I'm using a nix-shell with stdenv, which 

Here's the error log:

CC=/home/peter/experiments/unikernels/rumprun/rumprun/obj-amd64-hw/rumptools/bin/x86_64--netbsd-gcc /home/peter/experiments/unikernels/rumprun/rumprun/obj-amd64-hw/rumptools/bin/nbmkdep -f InstrProfilingFile.d.tmp  --   -std=gnu99    -D__NetBSD__ -Ulinux -U__linux -U__linux__ -U__gnu_linux__ --sysroot=/home/peter/experiments/unikernels/rumprun/rumprun/obj-amd64-hw/rumptools/dest  -D_LIBC -DLIBC_SCCS -DSYSLIBC_SCCS -D_REENTRANT -D_DIAGNOSTIC -DHESIOD -DINET6 -DNLS -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/include -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/sys -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/compat/../locale -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/compat/stdlib -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/compat/../stdlib -D__BUILD_LEGACY -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/../../common/lib/libc/quad -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/../../common/lib/libc/string -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/../../common/lib/libc/arch/x86_64/string -D__DBINTERFACE_PRIVATE -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/libexec/ld.elf_so -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/dlfcn -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/gdtoa -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/locale -DNO_FENV_H -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc/arch/x86_64/gdtoa -DWITH_RUNE -I/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/lib/libc -DPOSIX_MISTAKE -DCOMPAT__RES -DUSE_POLL -DPORTMAP -DWIDE_DOUBLE -DALL_STATE -DUSG_COMPAT  -Wno-missing-prototypes  -Wno-old-style-definition  -Wno-strict-prototypes  -Wno-uninitialized  -Wno-cast-qual    /home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/sys/external/bsd/compiler_rt/dist/lib/profile/InstrProfilingFile.c > error.txt
In file included from /nix/store/n2wxp513rr00f6hr2dy0waqahns49dch-glibc-2.21/include/features.h:365:0,
                 from /nix/store/n2wxp513rr00f6hr2dy0waqahns49dch-glibc-2.21/include/inttypes.h:25,
                 from /home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/sys/external/bsd/compiler_rt/dist/lib/profile/InstrProfiling.h:25,
                 from /home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/sys/external/bsd/compiler_rt/dist/lib/profile/InstrProfilingFile.c:10:
/home/peter/experiments/unikernels/rumprun/rumprun/src-netbsd/sys/sys/cdefs.h:62:27: fatal error: machine/cdefs.h: No such file or directory
 #include <machine/cdefs.h>
                           ^
compilation terminated.
nbmkdep: compile failed.

**Comment by ehmry** [comment]
I've tried doing this before, and its really not fun. BSD and the Rump build stuff has this /usr/src concept that really does not play will with Nix.

**Comment by paspanag** [comment]
Ha! It's painful.

So, I'm looking into it more and in Ubuntu, the netbsd-gcc resolves inttypes.h from within the rumpctrl/rump/include/ headers, in Nixos the netbsd-gcc resolves the inttypes.h from the /nix/store/

Any idea how to correct this?

**Comment by Profpatsch** [comment]
@paspanag was your question answered in the meantime?
