### ISSUE TITLE
ranger: can't open tar files (less -R: command not found)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#13436]
## Basic info

To make sure that we are on the same page:
- Kernel: Linux chimera 4.4.1 #1-NixOS SMP Sun Jan 31 19:29:37 UTC 2016 x86_64 GNU/Linux
- System: 16.03.git.8e784ea (Emu)
- Nix version: nix-env (Nix) 1.11.1
- Nixpkgs version: 16.03.git.8e784ea
## Describe your issue here

Opening tars with ranger doesn't work
### Expected result
- tar is opened
### Actual result
- screen flashes
- upon exiting, you see the error:

```
/bin/sh: less -R: command not found
tar: write error
```
### Steps to reproduce
- Open ranger in a directroy with a tar file.
- Attempt to open tar file in ranger

**Comment by ericsagnes** [comment]
Are you using zsh?
It seems zsh fails to execute a command with flags in an environment variable.

bash:
```
$ $PAGER test.txt
-> working
```

zsh:

```
$ $PAGER test.txt
less -R: command not found

$ PAGER="less"; $PAGER test.txt
-> working
```

And it happens with other commands too:

```
$ LS="ls"; $LS
-> working

$ MYLS="ls -lisha"; $MYLS
ls -lisha: command not found
```

**Comment by colemickens** [comment]
Yup, I'm using ZSH. Looks like that's it. Suggested workaround/fixes? Or is there an upstream bug for ZSH?

**Comment by iyzsong** [comment]
workaround is set ``PAGER`` to ``less``, and set ``LESS`` to ``-R``.

**Comment by zimbatm** [comment]
There ^

**Comment by iyzsong** [comment]
Or set ``SH_WORD_SPLIT`` for zsh.
http://stackoverflow.com/questions/6715388/variable-expansion-is-different-in-zsh-from-that-in-bash

**Comment by zimbatm** [comment]
Why are we setting these environment variables in the first place again ? It feels like it should be something that user can decide instead.

**Comment by dezgeg** [comment]
Agreed, I have a feeling we're papering over some other problem by setting these in the default environment.

**Comment by zimbatm** [comment]
There is also this related issue where the man page doesn't escape properly unless `PAGER=less -R`: https://github.com/NixOS/nixpkgs/issues/7269

**Comment by Profpatsch** [comment]
This is an upstream bug.

**Comment by Profpatsch** [comment]
https://github.com/ranger/ranger/pull/676 will fix this.

**Comment by jonafato** [comment]
ranger/ranger#676 has been merged. Is this still an issue?

**Comment by zimbatm** [comment]
only when 1.9.0 will be released and packages. we are currently on 1.8.1
