### ISSUE TITLE
Unstable channel hasn't updated in a week

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#13439]
... and it's still vulnerable.

There's a problem that I can't reproduce but Hydra reproduces it repeatedly http://hydra.nixos.org/build/32267159. It's seems as if `passAsFile` doesn't work well on Hydra.

**Comment by vcunat** [comment]
BTW, in the meantime I fixed the tarball job (as of e053971d81).

**Comment by ocharles** [comment]
I already requested that we manually push a not-fucked version of nixpkgs to unstable, and I still believe we should do that. We are making it *far* too easy to end up in an unbootable and un-rollbackable state, and I think we should be considering this an exceptional situation that requires exceptional intervention.

**Comment by vcunat** [comment]
Yes, that seems a good thing to do in notable security cases.

**Comment by dezgeg** [comment]
The `fc-cache` seems to fail in `rackspace-*` machines, maybe they have too old nix to support `passAsFile`.

**Comment by vcunat** [comment]
@dezgeg: thanks for the idea. I managed to work around it for now by a restart-job roulette.

**Comment by domenkozar** [comment]
`nixos-unstable` should update as part of http://hydra.nixos.org/eval/1237419
`nixpkgs-unstable` seems broken due on darwin due to curl update http://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents

**Comment by domenkozar** [comment]
I've merged https://github.com/NixOS/nixpkgs/pull/13425 so `nixpkgs-unstable` should update very soon.

**Comment by vcunat** [comment]
nixos:tested job succeeded now: http://hydra.nixos.org/build/32268924#tabs-summary

**Comment by vcunat** [comment]
nixpkgs:unstable as well.

I really hate how often we have to restart tests; they seem to just time out, presumably because there is too high load on the build slave at that moment.

**Comment by vcunat** [comment]
nixos-unstable channel updated.

**Comment by grahamc** [comment]
I think this can be closed now.

**Comment by jagajaga** [comment]
Can't perform an upgrade, getting this error:
```
*** Downloading ‘https://hydra.nixos.org/nar/g9lzz73ksnfxahyrv1gb9yqm229lb1mw-nuke-references’ (signed by ‘hydra.nixos.org-1’) to ‘/nix/store/g9lzz73ksnfxahyrv1gb9yqm229lb1mw-nuke-references’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 
curl: (22) The requested URL returned error: 404 Not Found

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

error: unexpected end-of-file
download of ‘https://hydra.nixos.org/nar/g9lzz73ksnfxahyrv1gb9yqm229lb1mw-nuke-references’ failed: No such file or directory
could not download ‘/nix/store/g9lzz73ksnfxahyrv1gb9yqm229lb1mw-nuke-references’ from any binary cache
fetching path ‘/nix/store/g9lzz73ksnfxahyrv1gb9yqm229lb1mw-nuke-references’ failed with exit code 1
error: some substitutes for the outputs of derivation ‘/nix/store/xhv50yf7rrdsq59sn2pjafyklfh6v4qv-nuke-references.drv’ failed (usually happens due to networking issues); try ‘--fallback’ to build derivation from source 
```
`--fallback` doesn't help.

**Comment by ocharles** [comment]
But this issue is nothing about Hydra. What happens if you just use the
official cache?

**Comment by jagajaga** [comment]
hydra.NixOS.org is not official? :(

-- 
Sincerely,
Arseniy Seroka

**Comment by vcunat** [comment]
It's not officially recommended, though for fear of overloading it AFAIK. The error has a ticket: https://github.com/NixOS/nix/issues/396.

**Comment by jagajaga** [comment]
`cache.nixos.org` worked!
