### ISSUE TITLE
monotone-1.1-unstable-2021-05-01 genkey fatal error

### ISSUE THREAD

**Issue by Ovsyanka** [NixOS/nixpkgs#134469]
### Describe the bug

`mtn genkey mail@example.com` produces error

> mtn: fatal: Botan::Encoding_Error: Encoding error: PBE-PKCS5 v2.0: Invalid cipher spec SHA-160

```
enter passphrase for key ID [mail@example.com] (...): 
confirm passphrase for key ID [mail@example.com] (...): 
mtn: generating key-pair 'mail@example.com'
mtn: fatal: Botan::Encoding_Error: Encoding error: PBE-PKCS5 v2.0: Invalid cipher spec SHA-160
mtn: This is almost certainly a bug in monotone.
mtn: Please report this error message, the output of 'mtn version --full',
mtn: and a description of what you were doing to 'https://code.monotone.ca/p/monotone/issues/'.
mtn: wrote debugging log to /home/user/.monotone/dump
mtn: if reporting a bug, please include this file
```

```sh
$ cat /home/user/.monotone/dump   
...                                                                                                                                                                                
generating key-pair 'mail@example.com'
```

### Steps To Reproduce

I am on Arch linux and I use this commands to run monotone:

```sh
nix-channel --add https://nixos.org/channels/nixos-unstable unstable
nix-channel --update
nix run unstable.monotone -c mtn genkey mail@example.com
```

### Expected behavior

Succesful creating of the keys, like in monotone-1.1

```
nix-channel --add https://nixos.org/channels/nixos-20.09 nixpkgs
nix-channel --update
nix run nixpkgs.monotone -c mtn genkey mail@example.com                                                                                                                                                           ...
enter passphrase for key ID [mail@example.com] (...): 
confirm passphrase for key ID [mail@example.com] (...): 
mtn: generating key-pair 'mail@example.com'
mtn: storing key-pair mail@example.com in '/home/user/.monotone/keys/'
mtn: storing public key mail@example.com in ''
mtn: key 'mail@example.com' has hash 'c2506fe65cf93f68546944a215a35525f3ebb032'
```

### Notify maintainers

@7c6f434c 

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                                               or@or-dsktp-arch
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.56-1-lts, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixpkgs-20.09.4393.068984c00e0"`
 - channels(or): `"nixpkgs-20.09.4393.068984c00e0, unstable-21.11pre309163.23485f23ff8, nixos-20.09-20.09.4393.068984c00e0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by 7c6f434c** [comment]
Thanks for catching, feel free to try the linked PR before it lands (I myself do not use passphrased keys, so I guess it would be nice to have some real-life usage before reporting the patch upstream)

**Comment by Ovsyanka** [comment]
> feel free to try the linked PR before it lands

Sorry, I am not skilled enough yet to install from repository.

> I myself do not use passphrased keys

Yeah, I didn't even think that I can create the key without passphrase =) With empty passphrase key generation works indeed.

**Comment by 7c6f434c** [comment]
Hm, looks like channel update lag is a few hours, so might be there not too long from now…

**Comment by Ovsyanka** [comment]
I can't understand if the package is updated already.
I looked at your changelog and don't see the version change. Is it like it should be? How can I know that package is updated?

I ran these commands and the error still there.
```console
$ nix-channel --update unstable                                                                                                                                                3 ↵ 
unpacking channels...
created 3 symlinks in user environment

$ nix run unstable.monotone -c mtn genkey mail@example.com                                                                                                                         
enter passphrase for key ID [mail@example.com] (...): 
confirm passphrase for key ID [mail@example.com] (...): 
mtn: generating key-pair 'mail@example.com'
mtn: fatal: Botan::Encoding_Error: Encoding error: PBE-PKCS5 v2.0: Invalid cipher spec SHA-160
...
```

I tried to install it with nix-env and there is the same situation and version still is `monotone-1.1-unstable-2021-05-01`

**Comment by 7c6f434c** [comment]
>I can't understand if the package is updated already.
>I looked at your changelog and don't see the version change. Is it like it should be? How can I know that package is updated?

https://status.nixos.org/ should show as latest commit included in the channel a commit fresher than the merge. It's not yet there.

(the version should not change, though)

Alternatively, you could say that https://hydra.nixos.org/build/150117840  has to happen…

(then you can nix-store -r its output path — it will be substituted from the binary cache, and just run mtn invoked with the full path…)

**Comment by Ovsyanka** [comment]
Okay, I got the new version from unstable repo and it works. I suppose it is backported to the 21.05 too, but I didn't check. Closing the issue, thank you =)

**Comment by 7c6f434c** [comment]
>Okay, I got the new version from unstable repo and it works. I suppose it is backported to the 21.05 too, but I didn't check. Closing the issue, thank you =)

Yes, backported but not tested much but should not depend on the branch difference.
