### ISSUE TITLE
Packaging request: Psst

### ISSUE THREAD

**Issue by nerosnm** [NixOS/nixpkgs#134446]
**Project description**
Psst is a Spotify client with a native GUI, without Electron, built in Rust.

**Metadata**

* homepage URL: https://github.com/jpochyla/psst
* source URL: https://github.com/jpochyla/psst
* license: mit
* platforms: linux, darwin

It's still early in development but looks promising, and does implement a base feature set already.

**Comment by figsoda** [comment]
duplicate of https://github.com/NixOS/nixpkgs/issues/115155
