### ISSUE TITLE
steam/proton: missing icd files for nvidia

### ISSUE THREAD

**Issue by babbaj** [NixOS/nixpkgs#134556]
### Describe the bug
The vulkan icd files for nvidia are missing in steam and causes Black Ops III to not be able to launch properly

### Steps To Reproduce
1. run `steam-run ls /usr/share/vulkan/icd.d/`

on my machine I get:

```console
[babbaj@nixos:~]$ steam-run ls /usr/share/vulkan/icd.d/
intel_icd.i686.json    lvp_icd.i686.json    radeon_icd.i686.json
intel_icd.x86_64.json  lvp_icd.x86_64.json  radeon_icd.x86_64.json
```

### Expected behavior
`nvidia_icd32.json` and `nvidia_icd.json` should be present

### Additional context
Running nvidia driver 470.57.02 on a gtx 970, running the nixos-unstable branch and I do not have an intel or amd gpu
@starcraft66 has a similar but working setup with a 1080 ti

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre309163.23485f23ff8, home-manager-21.05, master, nixos-stable-20.09, nixos-unstable-21.11pre309163.23485f23ff8"`
 - channels(babbaj): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - steam
# a list of nixos modules affected by the problem
module:
```

**Comment by babbaj** [comment]
looks like I misidentified the cause. This isn't a new problem https://github.com/NixOS/nixpkgs/issues/108598#issuecomment-853473098
adding this to my config completely fixed it but I think a more general fix can be done with /run/opengl-driver/
https://github.com/NixOS/nixpkgs/issues/108598#issuecomment-858095726

**Comment by jonringer** [comment]
It's not a complete duplicate, because the nvidia icd's only exist under `/run/opengl-driver/share/vulkan/icd.d`, so it's of no benefit that the mesa drivers are the ones that are listed

**Comment by jonringer** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/161576
