### ISSUE TITLE
[Security concern] display-managers/sddm uses some fork instead of main repo as source

### ISSUE THREAD

**Issue by diimpp** [NixOS/nixpkgs#13459]
Hey guys,

I was browsing this repo and noticed, that
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/display-managers/sddm/default.nix
uses https://github.com/benjarobin/sddm/ repo instead of https://github.com/sddm/sddm

This seems to me as malicious activity attempt or just a purely handled patching process.

Regards.

**Comment by edolstra** [comment]
It only downloads the patch https://github.com/benjarobin/sddm/commit/7d05362e3c7c5945ad85b0176771bc1c5a370598 from that repo (which is upstream PR https://github.com/sddm/sddm/pull/573). Do you think there is a problem with that patch?

Ping @ttuegel, @abbradar.

**Comment by abbradar** [comment]
This patch fixes the focus on the password field in SDDM on start. Should be harmless (I've reviewed it before adding) -- should I add a comment?

**Comment by diimpp** [comment]
Indeed it looks like I've overreacted.
It looked to me yesterday as it was installable from fork, not a just using a specific patch.

Sorry.
