### ISSUE TITLE
omegaconf out of date 1.4.1 <= 2.1

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#134552]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `omegaconf`
current version: 1.4.1
desired version: 2.1

###### Notify maintainers

maintainers: @bcdarwin

###### Note for maintainers

Major bump; may require a package split.

**Comment by bcdarwin** [comment]
Fixed in #134745.
