### ISSUE TITLE
programs.neovim.enable makes neovim unable to read configurations.

### ISSUE THREAD

**Issue by quantmint** [NixOS/nixpkgs#134617]
### Describe the bug
When i enable neovim through  programs.neovim.enable neovim is unable to load any config, when i install it with environment.systemPackages = pkgs.neovim everything works.
### Steps To Reproduce
Add programs.neovim.enable = true; to you config.nix.

### Expected behavior
Neovim should be able to read ~/.config/nvim/init.vim

### Notify maintainers
@teto @dasJ 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.10-xanmod1-cacule, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre309163.23485f23ff8"`
 - channels(quantmint): `"nixos-21.11pre306790.0dde1033180"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```console

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: programs.neovim.enable
```

**Comment by turion** [comment]
Can you fix the issue title?

**Comment by Alexnortung** [comment]
Shouldn't the vim configuration be part of `configuation.nix`? Having programs read .config files in the home directory doesn't really feel like a nix way. I am not 100% sure this is the case, but that is my guess. Check out this page https://nixos.wiki/wiki/Vim

**Comment by teto** [comment]
Look at your `nvim` executable, it wraps the call to neovim passing it a config from the nix store, like `nvim -u /nix/store/xxx-init.vim`. Neovim called with `-u` wont read the file in ~/.config/nvim . You should source that file yourself. Note that home-manager generates ~/.config/nvim/init.vim . 
Basically once you start to manage the config via nix, nix tries to be pure and not load something it has no control over. In practice it's possible to bypass by sourcing ~/.config/nvim/init.vim yourself. Check the tracker, there are several issues/pull requests about this.
