### ISSUE TITLE
Mangohud not worked

### ISSUE THREAD

**Issue by dan4ik605743** [NixOS/nixpkgs#134679]
### Describe the bug
Mangohud does not work in Intel + NVIDIA configuration.

### Steps To Reproduce
1. environment.systemPackages = with pkgs; [ mangohud ];
2. mangohud {glxgears,vkcube}

### Expected behavior
MANGOHUD: Failed to open 64bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
MANGOHUD: XNVCtrl loader failed to load

### Screenshots
![image](https://user-images.githubusercontent.com/86075850/129941532-26035002-b7c1-4956-8258-fc5d70cc5455.png)
![image](https://user-images.githubusercontent.com/86075850/129943224-2751780e-df66-45dc-85b3-7291bfe66cad.png)
![image](https://user-images.githubusercontent.com/86075850/129943496-4ff58956-f8d6-4fc9-a620-3f09731c3aa6.png)

### Additional context
I think this is due to my iron laptop Intel + Nvidia

### Notify maintainers
@ZerataX 

### Metadata
```console
λ ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.10-xanmod1-cacule, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - nixpkgs: `/nix/store/1inzjq0zh5qrl0196qxicl0j83fia916-source`
```

Maintainer information:
```yaml
attribute: mangohud
```

**Comment by dan4ik605743** [comment]
My notebook
![image](https://user-images.githubusercontent.com/86075850/129942092-3dcc95a8-4710-4998-9a9d-0ff3b8b3b933.png)
xsever.videoDrivers = [ "nvidia" ];

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
	Subsystem: ASUSTeK Computer Inc. Device 10d0
	Kernel driver in use: i915
	Kernel modules: i915
	
04:00.0 3D controller: NVIDIA Corporation GK208BM [GeForce 920M] (rev a1)
	Subsystem: ASUSTeK Computer Inc. Device 105e
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

**Comment by kira-bruneau** [comment]
Hmm, that's strange. I added `addOpenGLRunpath.driverLink` to `LD_LIBRARY_PATH` in [#127469](https://github.com/NixOS/nixpkgs/pull/127469/commits/0bf03aee8985c2c56a8a61ed790790246a43b920) to support Nvidia cards. The way this library is loaded is impure though, and depends on how your system is set up.

Do you see `libXNVCtrl.so.0` under `/run/opengl-driver/lib`?

@ZerataX Is MangoHud still working on your computer with the Nvidia card?

**Comment by kira-bruneau** [comment]
Oh, I also noticed, you might be using a channel that doesn't have the latest version. This was fixed in v0.6.3. Maybe this fix should be backported.

**Comment by dan4ik605743** [comment]
> libXNVCtrl.so.0

ls: cannot access '/run/opengl-driver-32/lib/libXNVCtrl.so.0': No such file or directory
λ ~ ls /run/opengl-driver/lib/libXNVCtrl.so.0
ls: cannot access '/run/opengl-driver/lib/libXNVCtrl.so.0': No such file or directory
λ ~

**Comment by dan4ik605743** [comment]
@kira-bruneau What does it mean?

**Comment by dan4ik605743** [comment]
![image](https://user-images.githubusercontent.com/86075850/130110372-e2490a35-fd24-43bd-a22b-c7e6c8bb551a.png)
Well, then now I understand this error. But I do not understand why there is no biblet

**Comment by ZerataX** [comment]
@kira-bruneau
<details>
  <summary> mhmm on nixos 21.05 with mangohud from unstable i get:</summary>
  
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.05.2521.7bbca9877ca (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2521.7bbca9877ca, nixos-hardware, nixos-unstable-21.11pre309670.253aecf69ed"`
 - channels(kaine): `"home-manager-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
</details>

```
vkcube: /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/ag4r80ffsdmq08ngvsbw4kz18kzxbvr4-mangohud-0.6.5/lib/mangohud/libMangoHud.so)
vkcube: /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/lg104nh0szci8slz5z6494m457jm5y3p-gcc-10.3.0-lib/lib/libstdc++.so.6)
```

and I can't get a display manager to run on nixos-unstable :/

also `libXNVCtrl.so.0` is for me also not on `/run/opengl-driver/lib`


@dan4ik605743 what does your mangohud config look like? i am a little bit surprised to see the mangohud window anyways, even if it is empty

**Comment by legendofmiracles** [comment]
> @ZerataX Is MangoHud still working on your computer with the Nvidia card?
It works for me, on a nvidia-intel `prime` setup, although the library is also not in `/run/opengl-drivers/lib` 🤔 
![image](https://user-images.githubusercontent.com/30902201/130165865-e9292a81-c129-449d-b4a9-d1698ff4470f.png)

**Comment by dan4ik605743** [comment]
> > @ZerataX Is MangoHud still working on your computer with the Nvidia card?
> 
> It works for me, on a nvidia-intel `prime` setup, although the library is also not in `/run/opengl-drivers/lib` 
> ![image](https://user-images.githubusercontent.com/30902201/130165865-e9292a81-c129-449d-b4a9-d1698ff4470f.png)

################### File Generated by GOverlay ###################
#fps_limit=
toggle_fps_limit=F1
vsync=1
gl_vsync=0
legacy_layout=false
gpu_stats
gpu_temp
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FF7800,CC0000
gpu_text=GPU
cpu_stats
cpu_temp
cpu_load_change
core_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FF7800,CC0000
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
swap
vram
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_color=eb5b5b
gpu_color=2e9762
wine_color=eb5b5b
frame_timing=1
frametime_color=00ff00
media_player_color=ffffff
background_alpha=0.4
font_size=24
background_color=020202
position=top-left
text_color=ffffff
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
output_folder=/home/uncouteau
media_player_name=spotify

**Comment by dan4ik605743** [comment]
> > @ZerataX Is MangoHud still working on your computer with the Nvidia card?
> 
> It works for me, on a nvidia-intel `prime` setup, although the library is also not in `/run/opengl-drivers/lib` 
> ![image](https://user-images.githubusercontent.com/30902201/130165865-e9292a81-c129-449d-b4a9-d1698ff4470f.png)

![image](https://user-images.githubusercontent.com/86075850/130184045-ce357330-c04b-4e82-990f-6aa1b44530c2.png)

**Comment by dan4ik605743** [comment]
And how can I be ... okay now I will try to lower the package version.

**Comment by dan4ik605743** [comment]
@ZerataX You can throw off your configuration.nix?

**Comment by dan4ik605743** [comment]
I don't even know what to think and what to five.

**Comment by dan4ik605743** [comment]
I don't even know what to think and what to five.

**Comment by dan4ik605743** [comment]
Apparently Mangohud is not where it does not work with my laptop characteristic
