### ISSUE TITLE
kotatogram-desktop segfault on voice message recording start

### ISSUE THREAD

**Issue by TheK0tYaRa** [NixOS/nixpkgs#134740]
### Describe the bug
On voice message recording start within first ~0.2 seconds the application crashes with a segfault.

### Steps To Reproduce
1. run kotatogram-desktop
2. try recording an audio message
3. segfault

### Expected behavior
Voice message being recorded and then sent if the button was left unpressed with a cursor on it

### Screenshots
![image](https://user-images.githubusercontent.com/27967034/129987426-eb52d91e-3cdf-4abc-b28b-82a555b32b90.png)

### Additional context
None

### Notify maintainers
@ilya-fedin 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/wv1mbc34jaws00lyhgqr6aix5ql0c1r6-bash-interactive-4.4-p23-dev
copying path '/nix/store/wv1mbc34jaws00lyhgqr6aix5ql0c1r6-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(thek0tyara): `"home-manager"`
 - channels(root): `"nixos-21.11pre308304.4138cbd913f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: unknown
# a list of nixos modules affected by the problem
module: unknown
```

**Comment by ilya-fedin** [comment]
It's incompatible with ffmpeg 4.4 and I don't see ffmpeg 4.3 in the list of packages... Apparently, it's unfixable.

**Comment by Artturin** [comment]
Create an issue in their repo if its a problem with them not supporting 4.4

**Comment by ilya-fedin** [comment]
I don't think there's any sense, the support should be picked up when they merge new tdesktop commits. Kotatogram is developed in free time, so new release won't be soon, apparently.

**Comment by Artturin** [comment]
oh its a fork of telegram, alright

**Comment by ilya-fedin** [comment]
I believe this is not a problem in 1.4.9 anymore. Can I close the issue or should I wait until NixOS versions with old kotatogram versions reach EOL?

**Comment by Artturin** [comment]
The updates can be backported
