### ISSUE TITLE
libinput missing libwacom dep

### ISSUE THREAD

**Issue by heydojo** [NixOS/nixpkgs#13476]
```
checking for LIBWACOM... no
configure: error: Package requirements (libwacom >= 0.12) were not met:

No package 'libwacom' found
```

In the unstable tree. Fixed here by using :
https://gist.github.com/heydojo/60a24f8944eef01935a0

@wkennington

**Comment by fpletz** [comment]
@heydojo Why don't you just create a PR? I can't see your changes without downloading that file from the gist to do a diff…

**Comment by heydojo** [comment]
@fpletz with all due respect, I would have if I had the time.
I created this report 10 minutes before I had to get ready for work this morning. Cheers. :+1:
