### ISSUE TITLE
Mention Bot not working

### ISSUE THREAD

**Issue by fpletz** [NixOS/nixpkgs#13481]
The Mention Bot introduced in #11160 is not working anymore. Was it disabled on purpose or is the service itself broken?

I think it was very beneficial to get feedback from previous authors of the code. Contributors doing PRs don't generally mention the maintainers. This is why most of the new PRs lack feedback from their respective maintainers.

cc @edolstra @rbvermaa

**Comment by fpletz** [comment]
I can see the Mention Bot as participant on PRs on the Github notifications page at https://github.com/notifications even though it hasn't commented and isn't listed as participant on the page itself. Maybe Github blocked the account?

**Comment by domenkozar** [comment]
I pinged https://github.com/facebook/mention-bot/issues/87

**Comment by fpletz** [comment]
Ah, I see. Maybe we should run our own instance? I could sponsor a VM and take care of maintenance if needed.

**Comment by domenkozar** [comment]
I'd rather see we talk to upstream, joining forces should help us all :) I think Heroku costs $7/month for a single dyno

**Comment by domenkozar** [comment]
It's back. The maintainer paid for the plan and asked github to unblock the bot. Thanks! https://github.com/facebook/mention-bot/issues/87
