### ISSUE TITLE
`giomodule.cache` conflict / collision

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixpkgs#13488]
## Basic info
- Kernel: 3.18.25
- System: 15.09.git.e83aed4 (Dingo)
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: "16.03.git.c6fcf44"
## Describe your issue here

There is the following collision when I install my profile:

```
collision between `/nix/store/vfqb0prz2ilfksl65k1w3wyp8bsa7zxl-gvfs-1.22.2/lib/gio/modules/giomodule.cache' and `/nix/store/qykzxrzhaj9g5j9nvkcyraqnmr4fdvbp-dconf-0.24.0/lib/gio/modules/giomodule.cache'
```

there seem to be these `giomodule.cache` files created for gnome3 packages. I'm
not sure how this should be handled. Should we use similar solution as for the
`hicolor/icon-theme.cache` issue (See #10370) and delete these cache files?
### Expected result

No collision.
### Actual result

Described collision.
### Steps to reproduce

Install both `dconf` and any package that depends on `gvfs` (I believe
`gnome3.file-roller` in my case) in the same profile.

**Comment by vcunat** [comment]
@lethalman: do you know if `giomodule.cache` is of any use in our model?

I think we always compose by setting `$GIO_EXTRA_MODULES`,  either by hand or by `wrapGAppsHook`.

**Comment by lethalman** [comment]
@vcunat that I know, it has never been useful. Most of apps already use stuff like glib networking and dconf module, without the need of any cache.

**Comment by vcunat** [comment]
So it should be OK to add a hook to remove those caches, right?

**Comment by lethalman** [comment]
@vcunat it should, but I haven't tried.

**Comment by Profpatsch** [comment]
triage: still a problem?
