### ISSUE TITLE
build-support ld-wrapper.sh uses wrong readlink on darwin

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#13492]
## Basic info

* Kernel: Darwin knedlbook.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
* System: Mac OS 10.9.5
* Nix version: 1.10
* Nixpkgs version: "16.03pre76763.be0abb3"

## Issue:

Interactively using the gcc-wrapper-4.9.3 to compile some C++ on darwin outputs the following error during linking:
```
~/.nix-profile/bin/c++   ...<some_stuff>...
...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

## Possible culprit:
One of the following three ld-wrapper.sh files seems to be the culprit, due to the line `path2=$(readlink -f "$path")`.
https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/pkgs/build-support/gcc-wrapper-old/ld-wrapper.sh
https://github.com/NixOS/nixpkgs/blob/b8c489e781a8690c39fb9e967dfafb9ad6a65fa1/pkgs/build-support/cc-wrapper/ld-wrapper.sh
https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/pkgs/build-support/gcc-cross-wrapper/ld-wrapper.sh

## Related pull request:
This merge seems to be of a similar topic:
https://github.com/NixOS/nixpkgs/pull/11798

**Comment by acowley** [comment]
Can you try a checkout from `staging`? The PR was merged a while ago, but it's taking a very long time to make it to `nixpkgs-unstable`. I've been using it for a couple months now without issue.

**Comment by knedlsepp** [comment]
After a few hours of compiling the `staging` branch, I can now say that the problem is probably solved.

**Comment by vcunat** [comment]
That PR #11798 should have fixed this.

**Comment by knedlsepp** [comment]
@vcunat: I did find this PR while searching for a solution, but since this was merged about a month ago, I didn't think that it would take so long for the channel to provide binaries.

**Comment by vcunat** [comment]
That's because it was a mass rebuild, so it went through the staging branch. There are lots of hurdles slowing delaying changes to get to channels.
