### ISSUE TITLE
Adding wlay

### ISSUE THREAD

**Issue by timsofteng** [NixOS/nixpkgs#134944]
**Project description**
Wlay helps to configure multiple monitors on wayland.

**Metadata**

* homepage https://github.com/atx/wlay:
* source https://github.com/atx/wlay:
* license: mit
* platforms: linux

**Comment by PanAeon** [comment]
@timsofteng Wlay is available in  [nixpkgs-wayland](https://github.com/nix-community/nixpkgs-wayland). Should be relatively easy to port to nixpkgs

**Comment by bossley9** [comment]
This issue can be closed: https://github.com/NixOS/nixpkgs/pull/242356
