### ISSUE TITLE
joseki: dead source, codehaus.org and wrong url sourceforge.net

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#13508]
## Basic info

* Kernel: (run `uname -a`)
Linux desktop-ole 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
Arch linux
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.1
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"15.09.952.55b0326"

## Describe your issue here / Expected result
Can't install joseki[1]

### Actual result
    building path(s) ‘/nix/store/lmpadpxgd0nah8fm6yfsywcpivp50m11-jena-2.6.4.zip’  
    trying http://prdowloads.dl.sourceforge.net/project/jena/Jena/Jena-2.6.4/jena-2.6.4.zip
    curl: (22) The requested URL returned error: 404 Not Found

After prefetching jena*.zip, jetty[2] fails:

    trying http://dist.codehaus.org/jetty/jetty-6.1.26/jetty-6.1.26.zip
    curl: (22) The requested URL returned error: 404 Not Found
    error: cannot download jetty-6.1.26.zip from any mirror
    builder for ‘/nix/store/z2k00w2z9l48r2jvnm0sa2y9kl73wkfy-jetty-6.1.26.zip.drv’ failed with exit code 1

### Steps to reproduce
`nix-env -iA nixos.joseki`

### Discussion

Checking dist.codehaus.org leads to codehaus.org stating that 
> All Codehaus services have now been terminated.

From a quick search it seems it's only jetty-6.1 and joseki that refers to codehaus.

 I also get issues with sourceforge downloads since jena is "archived" and the files are moved to `*/project/jena/Archive/*`

But I guess the real issue is that "Joseki" is deprecated and replaced by "Apache Jena Fuseki".

[1] https://github.com/NixOS/nixpkgs/blob/9220f03d08e4ba914605256aa22ef2a67a9a21ac/pkgs/servers/http/joseki/default.nix#L103
[2] https://github.com/NixOS/nixpkgs/blob/9220f03d08e4ba914605256aa22ef2a67a9a21ac/pkgs/servers/http/jetty/6.1/default.nix#L4

**Comment by 7c6f434c** [comment]
OK, added Fuseki, seems to work no worse than Joseki worked. Could someone check that this is what was needed?

**Comment by olejorgenb** [comment]
@7c6f434c Yup, that's it. Seems to work great (with the disclaimer that I haven't really used fuseki much in the past)


Jetty https://github.com/NixOS/nixpkgs/blob/9220f03d08e4ba914605256aa22ef2a67a9a21ac/pkgs/servers/http/jetty/6.1/default.nix#L4 will still have trouble though, but maybe that should have a separate ticket. 6.1 seems to be a very old version too.


Is there a policy on who close the issue?

**Comment by joachifm** [comment]
@olejorgenb if you are satisfied, feel free to close the issue.
