### ISSUE TITLE
nix-rebuild switch silently fails when out of RAM

### ISSUE THREAD

**Issue by 0xACE** [NixOS/nixpkgs#135033]
When running on a low RAM machine (e.g. 1GB RAM)
```
# nix-rebuild switch
```
The program may silently die leaving the user to believe the operation finished correctly.

This problem was difficult to debug as I believed the `nix-rebuild switch` was running as expected.

I would recommend there is a message or something that indicates failure. As the current method of detection is `sudo dmesg`

It seems like RAM usage is a problem in more than one place:

```
$ command time -v nix-instantiate '<nixpkgs/nixos>' -A system
...
Maximum resident set size (kbytes): 1126000
...
```

**Comment by CameronNemo** [comment]
One challenge is that the process is going to be SIGKILL'd if it dies due to OOM. No way to catch that. But! The return code will be non-zero. Perhaps you should ensure that you are checking the return code when you do a rebuild.

**Comment by puffnfresh** [comment]
Since this is a Nix problem and not a NixOS/nixpkgs specific problem, we should probably track this issue over there:

https://github.com/NixOS/nix/issues/2664
