### ISSUE TITLE
openssl: it's vulnerable

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#13506]
Up to high severity. Fixed releases are announced to be made public in about three days. 

https://mta.openssl.org/pipermail/openssl-announce/2016-February/000063.html

**Comment by NeQuissimus** [comment]
1.0.1s and 1.0.2g are out now.
Are you going to update OpenSSL? Otherwise, I can send a PR later in the day. We should do this ASAP considering the severity of the CVEs.

**Comment by edolstra** [comment]
The staging and release-15.09 branches already have the fix (and the nixos-15.09-small channel is already updated: https://nixos.org/releases/nixos/15.09-small/nixos-15.09.1109.19de563/).

**Comment by vcunat** [comment]
I picked it to 16.03 as well. We might forget it otherwise.

**Comment by vcunat** [comment]
Oh, I didn't notice e0d17fdf105. That would be another rebuild of openssl-depending stuff on 16.03.

BTW, I don't understand the reason for the current state of Hydra jobsets. Staging builds with these security patches seems to have been [cancelled](http://hydra.nixos.org/eval/1238922) and "trunk" without the patches [is building](http://hydra.nixos.org/jobset/nixpkgs/trunk). Perhaps there's some intention that I didn't notice?
