### ISSUE TITLE
gitea ssh with a custom domain

### ISSUE THREAD

**Issue by happysalada** [NixOS/nixpkgs#135034]
### Describe the bug
Setting up gitea, perhaps we should add instructions on how to make ssh work with a custom domain ?
I've got `services.gitea.ssh.enable = true;`
and I've verified that I can clone a repo by using the IP address of the instance.
I can `git clone ssh://gitea@144.76.153.92:/happysalada/union.git`
however i've got it setup on a custom domain at git.union.rocks
for the love of me I can't figure out how to make `git clone ssh://gitea@git.union.rocks/happysalada/union.git`
Could it be a setting in the reverse proxy ?
I have to say I really don't know here.
I've also got
```
    domain = "git.union.rocks";
    rootUrl = "https://git.union.rocks";
    httpPort = 3030;
    httpAddress = "127.0.0.1";
    cookieSecure = true;
```
I'm happy to make a PR to add a section in the manual on gitea.

@disassembler @kolaente @ma27

(this is in no rush, I can continue using https)

**Comment by Ma27** [comment]
I have the following config:

``` nix
{
  services.gitea.extraConfig = ''
    [server]
    SSH_DOMAIN=git.mbosch.me
    SSH_PORT=2323
    START_SSH_SERVER=true
  '';
}
```

And I can clone repos via e.g. `ssh://gitea@git.mbosch.me:2323/ma27/coredump-exporter.git`

**Comment by kolaente** [comment]
ssh doesn't have knowledge of a domain (it's a lower level protocol) - if your DNS records are properly set up and you still can't clone from the domain that might be an issue with the port or firewall settings.

Gitea's `SSH_DOMAIN` only has the purpose of showing the domain in the frontend.

**Comment by Ma27** [comment]
Yeah, I'm aware of that, I should've pointed out more clearly that I just used a different port, sorry for that :)

**Comment by happysalada** [comment]
My bad, I was using cloudflare proxy on that subdomain. Problem lies between keyboard and chair.
Thank you both for the help!
