### ISSUE TITLE
Package Request: Spectacle (a Haskell DSL for formal specifications)

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#135145]
**Project description**

Spectacle is an open source, domain-specific language for writing and checking formal specifications in Haskell, by Awake Security.  It is designed to replace TLA+ for formally specifying Haskell software, to achieve feature parity with TLA+ while improving on several aspects of TLA+ and TLC.

**Metadata**

* homepage URL:  https://awakesecurity.com/blog/spectacle-a-language-for-writing-and-checking-formal-specifications-in-haskell/
* source URL:  https://github.com/awakesecurity/spectacle
* license:  Apache 2.0
* platforms:  linux, darwin

**Comment by sternenseemann** [comment]
Can you ask upstream to upload their releases to Hackage? While it's not a requirement, it makes packaging a haskell package a lot less effort for us in general.

**Comment by cdepillabout** [comment]
Spectacle now appears to be available on Hackage: https://hackage.haskell.org/package/spectacle

**Comment by sternenseemann** [comment]
Working with GHC 8.10.7 in `haskell-updates`, issue for 9.0 support here: https://github.com/awakesecurity/spectacle/issues/49
