### ISSUE TITLE
Private Channels?

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#13517]
Is it currently possible to add channels to Nix which require credentials to access?

The use case I have in mind is the deployment of internal applications via Nix and Hydra. Consider a web application written to be used by a company in the performance of its business. It would be stellar to be able to use nix-shell to develop the application, hydra to do CI on the application, and then the hydra-produced channel and binary cache to distribute the application to servers.

However, these applications tend to be proprietary in some aspect, and thus deploying them via publicly accessible (even if not-advertised) web server would be a deal-breaker.

From what I can tell, hydra would need to be able to pull the nix expressions from a private repository (and so would need to be able to accept and use credentials with git - ideally a ssh pubkey), and the build products would need to be protected somehow - maybe nginx could be configured to require client TLS authentication for the appropriate paths?

Finally, `nix-channel --update` would need to be able to accept and use credentials to retrieve the channel tarball, and other nix tools (`nix-env` chief among them, but not sure about others) would need to be able to also use credentials to retrieve from binary caches.

While `nix-copy-closure` might work for one-offs in terms of security, I'm looking for an unattended solution as much as possible here - something that might work in a `configuration.nix` in other words.

**Comment by domenkozar** [comment]
You should be able to use http basic auth in the url in form of `http://username:password@url

**Comment by nyarly** [comment]
For which of those uses? Hydra pulling from git? Serving the channel tarball? Or the binary cache? Or all three?

**Comment by domenkozar** [comment]
All of them.

**Comment by nyarly** [comment]
Okay. Let me try that.

**Comment by colemickens** [comment]
I'd like this as well. nix-serve can serve over ssh, but it seems that the logic to look in binary caches only works via http.

**Comment by grahamc** [comment]
Can this be closed?

**Comment by domenkozar** [comment]
FYI: https://github.com/Profpatsch/nix-http-serve/
