### ISSUE TITLE
Package MobileCoin Wallet

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#135210]
**Project description**
Wallet application for the crypto currency MobileCoin

**Metadata**

* homepage URL: https://github.com/mobilecoinofficial/desktop-wallet
* source URL: https://github.com/mobilecoinofficial/desktop-wallet
* license: gpl3
* platforms: linux

**Comment by WolfangAukang** [comment]
Was able to package it from the AppImage. Tried from the tarball, but the application is too dependent of AppImage mechanisms that it was impossible to execute.

**Comment by WolfangAukang** [comment]
Merged
