### ISSUE TITLE
Improvements to the `./github` templates

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#13529]
Just some thoughts I've been considering the past few days.

### Commit formatting
To learn the project's commit format, you must take a good bit of initiative and link-following. I suspect this ends up with a good bit of needless PR commentary to ensure the commits follow the rules:

1. commits should say `package: improvement description` in the general case
2. commits should say `package: oldversion -> newversion` if it is a package upgrade
3. commits with a rebase should be done with `git rebase -xe`

I'd propose these common rules be put in the PULL_REQUEST template directly, with a link to the full manual page on submitting patches.

### Unclear how to follow the templated steps

I've seen a few people ask about this on IRC in the past few days.

 - [x] A total newbie might not sure how to set chroot to true, and having a how-to link or a small example here could be helpful.
 - [x] I think placing an example on how to build all the dependent builds like `nix-shell -p nox --run "nox-review pr THIS_PR_NUMBER"` in the document would also make that easier (we have nix-shell, might as well use it :))

### Issue Submission

We could simplify the information gathering by providing a simple tool in nix for it, or even just putting this in the issue template:

```sh
echo '##### Basic Info'

echo " - Kernel: \`$(uname -a)\`"
echo " - System: \`$(nixos-version || lsb_release -a)\`"
echo " - Nix Version: \`$(nix-env --version)\`"
echo " - Nixpkgs Version: \`$(nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion)\`"

```

**Comment by domenkozar** [comment]
Thanks, I've addressed some of these in https://github.com/NixOS/nixpkgs/commit/3c84ae406d80ba01f96a6da27de954b61f0e735b

**Comment by grahamc** [comment]
Whoa, cool! I see nox-review has a wip subcommand now, which means I don't have to open PRs like https://github.com/NixOS/nixpkgs/pull/13550 to run nox against it ... thank you.

**Comment by grahamc** [comment]
I'm closing this because I think things are improved, and if someone wants they can open a new one :)

Thank you!
