### ISSUE TITLE
15.09 firefox.desktop doesn't exist in /run/current-system/sw/share/applications, hence no application link in KDE

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#13534]
## Basic info

To make sure that we are on the same page:

* Kernel: Linux 4.1.17
* System: 15.09
* nix-env (Nix) 1.10
* 15.09.1076.9220f03

## Describe your issue here

Usually desktop GUI applications are meant to have a `*.desktop` file inside `*/share/applications`.

I installed both chrome and firefox:

```
        nixpkgs.config = {
            allowUnfree = true; 
            pulseaudio = true; # allow pulseaudio support to be built into packages
            firefox = {
                enableGeckoMediaPlayer = true; # enables a media player plugin
                enableAdobeFlash = true; # enable flash
                icedtea = true; # opensource JRE
                enableAdobeReader = true; # enable reading PDFs
            };  
            chromium = {
                enablePepperFlash = true;
                enablePepperPDF = true;
                icedtea = true;
                pulseSupport = true;
                enableNaCl = true;
            };
        };
```

And when I launched KDE5, there was a link to Chrome, but no Firefox.

So I checked `/run/current-system/sw/share/applications` and I found `chromium.desktop` but not `firefox.desktop`.

I checked the package directory in `/nix/store`. Inside it has a `share/applications/chromium.desktop`. While the firefox directory doesn't, it only has `bin` and `lib`.

This was strange because I checked both nix expressions building firefox and chromium. The `wrapper.nix` mentions the `share/applications`, but not the `default.nix`. See:

https://github.com/NixOS/nixpkgs/blob/release-15.09/pkgs/applications/networking/browsers/firefox/wrapper.nix#L70

**Comment by vcunat** [comment]
This is basically duplicate of #11588 for 15.09. On unstable/master this was solved by `wrapFirefox` renames #12299, but that's a relatively disruptive change to just pick into 15.09, I think.

**Comment by CMCDragonkai** [comment]
Oh great. Well 16.03 should be coming out anytime soon now.

**Comment by vcunat** [comment]
Yes, branching from master is planned for today.
