### ISSUE TITLE
Package Pantheon Tweaks

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#135376]
**Project description**
A system settings panel for the Pantheon Desktop that lets you easily and safely customise your desktop's appearance.

Only useful with #130380 

cc @bobby285271 

**Metadata**

* homepage URL: https://github.com/pantheon-tweaks/pantheon-tweaks
* source URL: https://github.com/pantheon-tweaks/pantheon-tweaks
* license: GPL-3.0+ (Source https://github.com/pantheon-tweaks/pantheon-tweaks/blob/b49cd28968dace5d2dbab2da09a3685ee772c0e7/data/pantheon-tweaks.appdata.xml.in#L48 )
* platforms: linux

**Comment by bobby285271** [comment]
Just managed to build this, will test it a little bit and submit a PR when #130380 is merged.

![](https://user-images.githubusercontent.com/20080233/130432943-069d06f5-5dc5-4f3d-bcbd-4ed01441567f.png)

**Comment by OPNA2608** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/115222.

**Comment by davidak** [comment]
@OPNA2608 i haven't found it. thanks!
