### ISSUE TITLE
NIX_ENFORCE_PURITY breaks `ekam` in hard to diagnose ways

### ISSUE THREAD

**Issue by timbertson** [NixOS/nixpkgs#13532]
- Kernel: `Linux meep 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- System: Fedora release 23
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: 16.03pre76763.be0abb3

I had a lot of trouble trying to build [ekam](https://github.com/sandstorm-io/ekam) in a nix expression recently. In a `nix-build` it would fail, but everything I did to reproduce that outside of a `nix-build` worked:
- copy the `src` directory from the store and build with my system compiler
- copy the `src` directory from the store and compile inside `nix-shell --pure`

The `nix-shell` step was the best I could do to reproduce the nix build environment, but I was _still_ unable to reproduce the failure.

I suspected the problem boiled down to include paths being missing, because ekam is rather novel in its use of virtual paths like `/ekam-provider/c++header/capnp/generated-header-support.h` (which is resolved to a real path by ekam's injected LD_PRELOAD library)

So on a hunch I dug into the `g++` wrapper script. The NIX_ENFORCE_PURITY logic jumped out as something that could be skipping non-nix paths. So I tried adding `NIX_ENFORCE_PURITY = "0";
` to my derivation. This still didn't work. I had to grep nixpkgs to see how to turn this off, and it's apparently done with `preHook = "unset NIX_ENFORCE_PURITY";`.

So to summarize:
- `nix-shell --pure` didn't set NIX_ENFORCE_PURITY, which seems like a bug to me. This would have made debugging much easier.
- setting `NIX_ENFORCE_PURITY="0"` in my derivation did nothing, I had to override the `preHook`. This doesn't seem like it needs to be special (but maybe there's a good reason for it?)
- I didn't get any indication that my include paths were being skipped. This would have been printed if I'd enabled `$NIX_DEBUG` but I didn't know about that flag. I'm not sure what could be improved here, since presumably this causes a _lot_ of noise given how often the compiler is invoked.
- Would it be OK to allow include paths outside the nix store, _as long as they don't exist_ at build time? This is admittedly a pretty weird thing to do on ekim's part, but I don't think it would lead to impurity.

**Comment by vcunat** [comment]
> setting NIX_ENFORCE_PURITY="0" in my derivation did nothing, I had to override the preHook. This doesn't seem like it needs to be special (but maybe there's a good reason for it?)

In any case, "0" is a wrong value. For "booleans" in bash test by `test -n` and `test -z`, so "0" would mean true, as only empty or unset value is considered false.

That doesn't change the fact that we might allow configuring this more easily, e.g. only set `$NIX_ENFORCE_PURITY` if it's unset. Then just putting `NIX_ENFORCE_PURITY = false;` into `mkDerivation` would override it.

> Would it be OK to allow include paths outside the nix store, as long as they don't exist at build time?

I don't think we should make the heuristic even wilder than it is now. Better override such things for `ekam` specifically.

**Comment by timbertson** [comment]
> I don't think we should make the heuristic even wilder than it is now

Fair point :)

> For checking "booleans" in bash we use test -n and test -z

That doesn't seem to be the case consistently (all checks for `NIX_ENFORCE_PURITY` are comparing to "1", not `-n`. But you're right, empty string is a much more falsy value ;)

Anyway, I've had a crack at only exporting $NIX_ENFORCE_PURITY when it's not yet set, see #13570

**Comment by Profpatsch** [comment]
@timbertson still a problem?

**Comment by timbertson** [comment]
There's still one part of this which isn't solved, and which I can't explain. Why doesn't `NIX_ENFORCE_PURITY` get set in a `nix-shell`, with or without `--pure`?

**Comment by timbertson** [comment]
Actually, upon re-trying `ekam` in a nix-shell, this doesn't appear to be an issue any more. Also, https://github.com/NixOS/nix/commit/48858ad5cabd03976330dff3d7aaa3d949ca09d6 implies it's not necessary to set `NIX_ENFORCE_PURITY` from `nix-shell`, so I'll believe it.
