### ISSUE TITLE
pytorch: RuntimeError: fft: ATen not compiled with MKL support

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#135488]
### Describe the bug
The `torch.fft` module seems to be missing in the pytorch derivation.

### Steps To Reproduce
```python
#! /usr/bin/env nix-shell
#! nix-shell -i python -p python3 python3Packages.pytorch
import torch
from torch.fft import fft
fft(torch.arange(4))
```
```
❯ ./mkl_bug.py
Traceback (most recent call last):
  File "./mkl_bug.py", line 5, in <module>
    from torch.fft import fft
ModuleNotFoundError: No module named 'torch.fft'
```

### Expected behavior
The torch.fft module to be available.

### Screenshots
n/a

### Notify maintainers

@danieldk @teh @thoughtpolice @tscholak

### Metadata
```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.100, NixOS, 20.09.3301.42809feaa9f (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.09.3301.42809feaa9f, nix-ld"`
 - channels(skainswo): `"home-manager-20.09, nixpkgs-unstable-21.11pre292293.84aa23742f6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

~Although I'm checked out and building on 99967a54d893b9742b38809ccfe3172b6918bdef.~

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python3Packages.pytorch
# a list of nixos modules affected by the problem
module:
```

**Comment by samuela** [comment]
As of https://github.com/NixOS/nixpkgs/commit/99967a54d893b9742b38809ccfe3172b6918bdef, I get the following error instead:
```
❯ NIX_PATH=.. ns -p python3 python3Packages.pytorch

[nix-shell:~/dev/nixpkgs]$ python
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch.fft import fft
>>> fft(torch.arange(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: fft: ATen not compiled with MKL support
>>> 
```

**Comment by yl3dy** [comment]
Seems that pytorch requires MKL for `torch.fft` package to work: https://github.com/pytorch/pytorch/issues/29796. By default, LAPACK/BLAS is provided by OpenBLAS. When selecting MKL as the provider:

`shell.nix`:
```
{ nixpkgs ? (fetchTarball "https://github.com/NixOS/nixpkgs/archive/934622990298da37d08e89f62094e4c747cb1037.tar.gz") }:

let
  mklOverlay = self: super: {
    blas = super.blas.override {
      blasProvider = super.mkl;
    };
    lapack = super.lapack.override {
      lapackProvider = super.mkl;
    };
  };
  pkgs = import nixpkgs { overlays = [ mklOverlay ]; };
in pkgs.mkShell {
  buildInputs = with pkgs; [ python3 python3Packages.pytorch ];
}
```
```
% nix-shell

[nix-shell:~]$ python
Python 3.9.6 (default, Jun 28 2021, 08:57:49) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch.fft import fft
>>> torch.__version__
'1.9.0'
>>> fft(torch.arange(4))
tensor([ 6.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])
```

Seems like in PyTorch 1.9.0 the error message just became more informative.

**Comment by samuela** [comment]
Thanks @yl3dy ! Dealing with overlays is kind of a pain. Is there any way we could get a feature flag on pytorch for this? I'm not familiar with the details but it seems like it could be done similar to the cuda/non-cuda situation.

**Comment by samuela** [comment]
As an example, I have a pypi package that I'd like to nix-ify but it and its test suite rely extensively in torch.fft. My understanding is that overlays would not be appropriate for a derivation inside nixpkgs.

**Comment by yl3dy** [comment]
From my experience it's a really good idea to get acquaintained better with overlays! This mechanism is very much in the spirit of functional programming and Nix (composability!). The only major gotcha is that `packageOverrides` for Python do not compose (see https://github.com/NixOS/nixpkgs/issues/44426), but it can be overcome by keeping an attrset of customized Python packages until the "last moment" to override Python itself.

I'll draft a PR to add a passthru attribute to `pytorch` derivation, otherwise it would be quite messy to extract the actual `blas` derivation used. This way you'd be able to use an assert in your expression.

**Comment by danieldk** [comment]
> As an example, I have a pypi package that I'd like to nix-ify but it and its test suite rely extensively in torch.fft. My understanding is that overlays would not be appropriate for a derivation inside nixpkgs.

The `pytorch-bin` derivation provides upstream PyTorch rewrapped for Nix and includes MKL.

There are other good reasons to use PyTorch with MKL (e.g. supported for batched GEMM).
