### ISSUE TITLE
NixOS channel updates stuck

### ISSUE THREAD

**Issue by lukegb** [NixOS/nixpkgs#135484]
See NixOS/nixos-org-configurations#159. Channel updates have been stuck for a few days.

**Comment by lukegb** [comment]
cc @NixOS/infra

**Comment by vcunat** [comment]
Looks fixed, all channels updated.  Thanks [Graham](https://matrix.to/#/!RROtHmAaQIkiJzJZZE:nixos.org/$_X9WBXeEb9u7fbaOrTLllEmajCCt8Qgy1_4jB1MQlys)!
