### ISSUE TITLE
NixOS's systemd abstraction doesn't work with systemd template units

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#135557]
### Steps To Reproduce

Create a template unit, like:

```nix
{
  systemd.services."foo@" = {
    scriptArgs = "%i";
    script = ''
      echo "$1"
    '';
  };

  systemd.services."foo@example" = {};
}
```

### Expected behavior

Starting `foo@example` should run the `foo@example` template service.

### Actual behavior

Starting a template unit which is not defined by NixOS works fine:

```console
# systemctl start foo@bar
# journalctl -fu foo@bar
-- Journal begins at Wed 2021-08-11 22:25:17 EDT. --
Aug 24 10:01:35 scruffy systemd[1]: Started foo@bar.service.
Aug 24 10:01:35 scruffy foo_-start[3297689]: bar
Aug 24 10:01:35 scruffy systemd[1]: foo@bar.service: Succeeded.
```

However, starting the `foo@example` service, defined by NixOS fails:

```console
# systemctl status foo@example
● foo@example.service
     Loaded: bad-setting (Reason: Unit foo@example.service has a bad unit file setting.)
     Active: inactive (dead)

Aug 24 10:01:41 scruffy systemd[1]: foo@example.service: Service has no ExecStart=, ExecStop=, or SuccessAction=. Refusing.
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11.20210810.6f6ade6 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210813_d581129`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by grahamc** [comment]
Further, I added another service like:

```nix
{
  systemd.services."several-foos" = {
      requires = [ "foo@fizz" "foo@buzz" ]; 
      wantedBy = [ "default.target" ];
      script = ''
      
      '';
 }
```

and `several-foos` starts but `foo@fizz` and `foo@buzz` do not get started.

**Comment by vcunat** [comment]
I've been successfully generating a target.  Re-tested now on 21.05:
```nix
{
    systemd.targets.kresd = { # configure units started by default
      wantedBy = [ "multi-user.target" ];
      wants = [ "kres-cache-gc.service" ]
        ++ map (i: "kresd@${toString i}.service") (range 1 cfg.instances);
    };
 }
```

**Comment by grahamc** [comment]
Is the `kresd@.service` unit file provided by kresd the package, or by a NixOS service?

**Comment by vcunat** [comment]
Provided by package and modified by service.

**Comment by grahamc** [comment]
I _think_ the issue is unique to units which are created totally by the module system.

**Comment by vcunat** [comment]
As a workaround you should be able to define a pseudo-package that defines the service.

**Comment by rnhmjoj** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/80933?

**Comment by pennae** [comment]
using instances of systemd services create by the module system in `OnFailure=` clauses *does* work on recent nixos-unstable (c21ba4f7bb4a3d621eb1d187e6b5e816bb85380c), as does the snippet from https://github.com/NixOS/nixpkgs/issues/135557#issuecomment-904680065 after suffixing `.service` to each required unit.

**Comment by roberth** [comment]
I think we should first model Exec* correctly before we revise are replace `.script`. https://github.com/NixOS/nixpkgs/issues/154123

**Comment by ck3d** [comment]
PR #186314 is now merged into master, which fixes this issue. A working example:
```
{
  systemd.services."foo@" = {
    scriptArgs = "%i";
    script = ''
      echo "$1"
    '';
  };

  systemd.services."foo@example" = {
    overrideStrategy = "asDropin";
  };
}
```

**Comment by con-f-use** [comment]
I don't think that example works anymore. As in if I copy&paste this the `foo@example` job is not started on system boot but rather displayed in `systemctl status foo@example.service` as `dead`.

**Comment by ck3d** [comment]
The override.conf should not have an exec setting, the the template service defines exec. Also the status dead looks as expected.
I see no degradation.
