### ISSUE TITLE
failing upgrade from 22.0.0.11 to 22.1.0.1: Updates between multiple major versions and downgrades are unsupported

### ISSUE THREAD

**Issue by gbiscuolo** [NixOS/nixpkgs#135544]
### Describe the bug

When upgrading NixOS via `nixos-rebuild switch --upgrade` I got this error on one of my containers with nextcloud22 installad: `Updates between multiple major versions and downgrades are unsupported`

I had previously upgraded from nextcloud21 to nextcloud22 and this upgrade is not a major version upgrade (nor a downgrade).

### Steps To Reproduce
1. `nixos-rebuild switch --upgrade`

### Expected behavior
Nextcloud upgrade

### Additional context

I've also opened a similar bug report upstream: https://github.com/nextcloud/server/issues/28581

I'm using nextcloud since nextcloud18 package version and always upgraded (sometimes with issues connected to app failing to upgrade and interfering with the core upgrade) with the `nextcloud-occ upgrade` command.

I've other containers with the very same setting of this one and the upgrade in all other containers have worked with no issue: **could it be an issue connected with the status of the config/filesystem?**.  I've compared the result of `nixos-container run SWcloud -- nextcloud-occ config:list system` with that of other containers but they are equivalent.

This is the output of the upgrade command:

```
/sudo:root@softwareworkers.node001:/etc/ #$ nixos-container run SWcloud -- nextcloud-occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
Maintenance mode is kept active
Resetting log level
```

This is the log (via `nixos-container run SWcloud -- journalctl -f` in during the upgrade):

```
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":1,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::setDebugLogLevel: Set log level to debug","userAgent":"--","version":"22.0.0.11"}
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":0,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"starting upgrade from 22.0.0.11 to 22.1.0.1","userAgent":"--","version":"22.0.0.11"}
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":3,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"{\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":[{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/lib/private/Updater.php\",\"line\":130,\"function\":\"doUpgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\",\"args\":[\"22.1.0.1\",\"22.0.0.11\"]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/core/Command/Upgrade.php\",\"line\":241,\"function\":\"upgrade\",\"class\":\"OC\\\\Updater\",\"type\":\"->\",\"args\":[]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/3rdparty/symfony/console/Command/Command.php\",\"line\":255,\"function\":\"execute\",\"class\":\"OC\\\\Core\\\\Command\\\\Upgrade\",\"type\":\"->\",\"args\":[{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput\"},{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput\"}]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/3rdparty/symfony/console/Application.php\",\"line\":1009,\"function\":\"run\",\"class\":\"Symfony\\\\Component\\\\Console\\\\Command\\\\Command\",\"type\":\"->\",\"args\":[{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput\"},{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput\"}]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/3rdparty/symfony/console/Application.php\",\"line\":273,\"function\":\"doRunCommand\",\"class\":\"Symfony\\\\Component\\\\Console\\\\Application\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Core\\\\Command\\\\Upgrade\"},{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput\"},{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput\"}]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/3rdparty/symfony/console/Application.php\",\"line\":149,\"function\":\"doRun\",\"class\":\"Symfony\\\\Component\\\\Console\\\\Application\",\"type\":\"->\",\"args\":[{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput\"},{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput\"}]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/lib/private/Console/Application.php\",\"line\":209,\"function\":\"run\",\"class\":\"Symfony\\\\Component\\\\Console\\\\Application\",\"type\":\"->\",\"args\":[{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput\"},{\"__class__\":\"Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput\"}]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/console.php\",\"line\":99,\"function\":\"run\",\"class\":\"OC\\\\Console\\\\Application\",\"type\":\"->\",\"args\":[]},{\"file\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/occ\",\"line\":11,\"args\":[\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/console.php\"],\"function\":\"require_once\"}],\"File\":\"/nix/store/6bqjr2cs4nidr26ld1hka3sky1dnlh4g-nextcloud-22.1.0/lib/private/Updater.php\",\"Line\":231,\"CustomMessage\":\"Updates between multiple major versions and downgrades are unsupported.\"}","userAgent":"--","version":"22.0.0.11"}
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":3,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::failure: Exception: Updates between multiple major versions and downgrades are unsupported.","userAgent":"--","version":"22.0.0.11"}
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":3,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"--","version":"22.0.0.11"}
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":1,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"22.0.0.11"}
Aug 24 11:43:15 SWcloud Nextcloud[1057]: {"reqId":"1pbB84KSUjoX9lBEBKPJ","level":1,"time":"2021-08-24T09:43:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Debug(0)","userAgent":"--","version":"22.0.0.11"}

```

### Notify maintainers

@schneefux @bachp @globin @fpletz @Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 21.05.2549.a1007637cea (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2549.a1007637cea"`
 - channels(gbiscuolo): `"nixos-19.03.172764.50d5d73e22b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`



```

Any hint how to solve this issue please?

Thanks! Giovanni.

**Comment by Ma27** [comment]
Have you checked whether the previous upgrades were all successful? (You may be able to do that now by looking at the logs of `nextcloud-setup.service`).

**Comment by Ma27** [comment]
> I must add that I tried stopping/starting the container with the problematic instance of nextcloud via systemctl [stop|start] container@SWcloud.service and I got an error related to the database connection (no route to host):

That's a bug in the nixos-container implementation, the networking uplink doesn't work until it's fully booted (i.e. `multi-user.target` is reached, because *after that* the host-side veth interface will be configured).

> If I try to restart the nextcloud-setup afterwards, I get the error reported in my first report (Exception: Updates between multiple major versions and downgrades are unsupported.): is it possible that the second error is connected to the route not found error?

Yes, perhaps some inconsistent state was somehow reached.

After skimming through the updater code: which `version` is in your `/var/lib/nextcloud/config/config.php`? Because that one has to be "compatible" with the hard-coded version from the source AFAIU.

**Comment by gbiscuolo** [comment]
Hi Maximilian @Ma27 and all other maintainers,

> > I must add that I tried stopping/starting the container with the problematic instance of nextcloud via systemctl [stop|start] [container@SWcloud.service](mailto:container@SWcloud.service) and I got an error related to the database connection (no route to host):
> 
> That's a bug in the nixos-container implementation,

Please is there a bug report opened so I can follow it?

> the networking uplink doesn't work until it's fully booted (i.e. `multi-user.target` is reached, because _after that_ the host-side veth interface will be configured).

Please is there any workaround?

> > If I try to restart the nextcloud-setup afterwards, I get the error reported in my first report (Exception: Updates between multiple major versions and downgrades are unsupported.): is it possible that the second error is connected to the route not found error?
> 
> Yes, perhaps some inconsistent state was somehow reached.

This is the same suspect I have /but/ I'm not able to find the inconsistent state value :-(
 
> After skimming through the updater code: which `version` is in your `/var/lib/nextcloud/config/config.php`? Because that one has to be "compatible" with the hard-coded version from the source AFAIU.

Well, actually the config is in `/var/lib/nextcloud/xtcloud.softwareworkers.it/config/config.php`:

```
  'version' => '22.0.0.11',
```

For completeness, this is what I get from the `occ config:list system` command:

```
/sudo:root@softwareworkers.node001:/etc/ #$ nixos-container run SWcloud -- nextcloud-occ config:list system
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/lib\/nextcloud\/xtcloud.softwareworkers.it\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/xtcloud.softwareworkers.it\/store-apps",
                "url": "\/store-apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.0.0.11",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "xtcloud_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "log_level": "0",
        "loglevel": 0,
        "maintenance": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "data-fingerprint": "f2b6b735584b1b55eabf3ce0c0f225f5",
        "trusted_domains": [
            "xtcloud.softwareworkers.it"
        ],
        "dbpassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```

I already checked the config and AFAIU there is nothing "suspect" in it.

I'm lost :-(

Thanks! Giovanni.

**Comment by gbiscuolo** [comment]
Hi @Ma27,

OK, it's almost for sure a **state-corruption** issue **in the database** :-(
(I really wish it could be fixable... but I can't find **where** is the issue)

> So, first of all, I tried to reproduce the problem with your config (by using it and setting `maintenance` to `false` before applying it to a freshly deployed Nextcloud 22.0 in a nixos-container) and I **cannot** reproduce the issue.

Thank you for your support Maximilian, as I said (https://github.com/NixOS/nixpkgs/issues/135544#issue-977966906) I have other instances configured in the same way and I was able to upgrade with no issues... so I was almost sure it was a state-corruption issue.  Now thanks to your help I'm absolutely sure.

> Also, another thing, what was the initial version of Nextcloud you deployed?

In the new instance (in the SW2cloud container, connecting to the cloned databse) I've deployed ver. `22.0.0.11` and it does not start.

In the "old" instance (SWcloud container), the very first NC I deployed was NC18, upgrdaded version-by-versioni until 22.0.0, now 22.1.0 in NixOS.

> And do you have any "exotic" apps (or plugins or whatever) installed?

This is the list of installed plugins in the new instance (in SW2cloud clontainer):

```
#$ nixos-container run SW2cloud -- nextcloud-occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - circles: 22.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - nextcloud_announcements
  - user_ldap
```

I'll try disabling them one by one.

> And, can you please stop quoting entire code-parts, I have to admit that this makes reading your comments way harder :)

OK, sorry for the noise.

> > I made a copy of the original database (pgsql) via CREATE DATABASE cloudswcloud2 WITH TEMPLATE cloudswcloud OWNER cloudswcloud;
> 
> Please retry with **fresh** database as well. We want to rule out state corruptions and this is another source for it. I mean, I won't be able to reproduce this with a problematic, existing database :)

OK, I'll try later and will report the results back, but please consider I'm **almost sure that this is NOT a nixos deployment related issue**, it's a status-corruption issue.

So please do not wait for this test (a new instance with a fresh database) to close this issue report.

> If you cannot trigger the issue then, I guess this is some state-corruption and thus an upstream issue.

I guess too.

I hope upstream will reply sooner or later, until now I received no comments to the upstream bug report https://github.com/nextcloud/server/issues/28581

> We can still try the following things on affected instances though:
> 
> * the `var_dump`-approach I suggested

OK, I'll try that.

> * e.g. `nextcloud-occ maintenance:repair -vvv` (perhaps with even more options that may seem helpful to you)

I've tried `maintenance:repair`, `db:add-missing-columns` (and other add-missing db subcommands) but nothing is working.

> If none of the above helps, I'd advice to set up a new instance (I mean, Nextcloud heavily relies on state and even though we've worked hard on making updates as smooth as possible, these kind of issues won't be really solvable on a distro-level then)

I know (and I'm experiencing) how much NC is status-dependant... what a pity.

...this also means that I should set up a status-corruption resistant procedure for upgrades, with backups of the filesystem **and** databases before *every* `nixos-rebuild switch --upgrade` (I was doing them only on *major* NC upgrades, but as it seems corruptions can happen also during *minor* NC upgrades).

> instructions on how to do this can be found at e.g. https://docs.nextcloud.com/server/latest/admin_manual/maintenance/migrating.html

Thank you very much @Ma27 for all you support and precious suggestions!

Happy hacking! Gio'

**Comment by gbiscuolo** [comment]
Hello @Ma27 and maintainers,

I just want to let you know that I was able to start my instance with NC version 20.0.0.11 installed in the SWcloud container (the one failing when I opened this issue, with the very same database) by disabling **all** the installed apps (I'll report the details in the upstream issue https://github.com/nextcloud/server/issues/28581).

After that the instance was running again:
```
#$ nixos-container run SWcloud -- nextcloud-occ maintenance:mode --off

#$ nixos-container run SWcloud -- nextcloud-occ upgrade
Nextcloud is already latest version

#$ nixos-container run SWcloud -- nextcloud-occ status
  - installed: true
  - version: 22.0.0.11
  - versionstring: 22.0.0
  - edition: 
```

After that I tried again to upgrade to NC 22.1 (via the updated nixpkg) but the upgrade failed the same way I reported in the first message of this thread.

Now I'm going to do further testing and debugging using the cloned NC 22.0 instance (database included).

Anyone interested can find further details and messages in the upstream issue https://github.com/nextcloud/server/issues/28581

I'm closing this issue since does not depend on the nextcloud22 NixOS package one

Thank you again and happy hacking! Gio'
