### ISSUE TITLE
buildRustPackage fails with `nix.useChroot = true`

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#13556]
## Basic info

To make sure that we are on the same page:
* Nixos version: 16.03pre77568.40c586b (Emu)

## Describe your issue here
Perhaps you have
``` nix
{ rustPlatform }:
with rustPlatform;

buildRustPackage rec {
  name = "foobar";
  src  = ./.;
  buildInputs = [ ];
  depsSha256 = "";
}
```
### Actual result
You tries to build it and if you have `nix.useChroot = true;` in your configuration.nix you will fail:
```
...
Fetching /tmp/nix-build-holmes-fetch.drv-0/compiler to /nix/store/59h4lbag5zxhz99d6wxilsp088s69bz4-holmes-fetch
Using rust registry from /nix/store/1habkfr79gsa8pgwb2qrs57nsdy14z6n-rustRegistry-2016-02-25-a43392d
    Updating git repository `https://github.com/goffrie/plex.git`
Unable to update https://github.com/goffrie/plex.git#0956a71b

Caused by:
  failed to clone into: /nix/store/59h4lbag5zxhz99d6wxilsp088s69bz4-holmes-fetch/git/db/plex-9de35c0f1efd4eaa

Caused by:
  [12/-1] Failed to resolve address for github.com: Name or service not known
...
```
Or you will get another network related error (`Couldn't resolve host name`).

### Expected result
With no `nix.useChroot = true;` everything builds fine.

cc @wizeman @abbradar @globin @maurer

**Comment by globin** [comment]
Normally the rustRegistry needs a bump if this happens

**Comment by jgillich** [comment]
Do you still get this? I use `nix.useChroot` as well and it works fine for me.

**Comment by the-kenny** [comment]
To reproduce we need the actual project directory used as this depends on multiple factors (`Cargo.toml`, `Cargo.lock`, etc.). If this is issue still relevant, please re-open this issue.
