### ISSUE TITLE
fluxcd 0.16.2 broken

### ISSUE THREAD

**Issue by shmish111** [NixOS/nixpkgs#135539]
### Describe the bug
Bootstrap does not create the correct versions of imagerepositories. See https://github.com/fluxcd/flux2/issues/759 for more detail.

### Steps To Reproduce
1. run flux bootstrap with `--components-extra=image-reflector-controller,image-automation-controller`
2. run `kubectl get crd imagerepositories.image.toolkit.fluxcd.io -oyaml`

### Expected behavior
`storedVersion` should be `v1beta1` but is `v1alpha2`

### Additional context
https://github.com/fluxcd/flux2/issues/759

### Notify maintainers
@jlesquembre 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(davidsmith): `"nixos-20.09.4393.068984c00e0, nixpkgs-20.09.4393.068984c00e0, unstable-21.11pre310022.14b0f20fa1f"`
 - nixpkgs: `/Users/davidsmith/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by shmish111** [comment]
One thing I should note is that when I ran into problems I had flux 0.11.0 installed by homebrew in `/usr/local/bin/flux` so I thought perhaps flux is somehow using that old version underneath.

**Comment by shmish111** [comment]
that doesn't seem to be the issue since I upgraded my homebrew version of flux, bootstrapped using this version, successfully, uninstalled flux and then tried to bootstrap using the nix build of flux and bootstrapping failed. I'm not sure what else to do.

**Comment by jlesquembre** [comment]
@shmish111  I think that the updater bot didn't update the hash for the manifests, and we are using the cached old version:
https://github.com/NixOS/nixpkgs/blob/4ed3374da7216de997078869c695858846f3bc61/pkgs/applications/networking/cluster/fluxcd/default.nix#L6-L10

I'll try to take a look later

**Comment by superherointj** [comment]
https://github.com/NixOS/nixpkgs/pull/135585

**Comment by jlesquembre** [comment]
@shmish111 did #135585 solved the issue?
