### ISSUE TITLE
Xow: libusb buggy

### ISSUE THREAD

**Issue by Steav005** [NixOS/nixpkgs#135678]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: xow

###### Notify maintainers

maintainers: @jansol

###### Note for maintainers

Xow itself is not out-of-date, but the used libusb is known to be buggy.  
There are multiple reports of high cpu usage which can be fixed by using the latest libusb:  
- https://github.com/medusalix/xow/issues/141
- https://github.com/medusalix/xow/issues/159
- https://github.com/medusalix/xow/issues/169
- https://github.com/medusalix/xow/issues/181

I was able to use the official [libusb](https://github.com/libusb/libusb) repo within a flake for circumventing the CPU issue 
https://github.com/Steav005/xow/commit/5e469a3269f06718a8b0cf172ceebea814df28ff

**Comment by Mindavi** [comment]
They are getting close to a release: https://github.com/libusb/libusb/issues/777

**Comment by ttrei** [comment]
libusb-1.0.25 was released

https://github.com/libusb/libusb/releases/tag/v1.0.25

**Comment by Mindavi** [comment]
I made a PR, but haven't done any testing yet. If anyone has some spare time, testing would be appreciated.
