### ISSUE TITLE
yabridge is incompatible with wine 6.15

### ISSUE THREAD

**Issue by landorg** [NixOS/nixpkgs#135603]
### Describe the bug
The readme of yabridge says:
> Wine 6.15 will not work with yabridge because of Wine bug #51596. See below for downgrading instructions.
And my plugins are not loading anymore.

I tried this:
```nix
let
  nixpkgs_wine614 = import (builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/000973d1a1fbfed6828a56d9893fb4eeed135e33.tar.gz";
        sha256 = "17qqbickkrm13r2kdzm3y9n0na14zv4nmzzfrdgbsj60fgqmabhi";
    }) {};

in {
  home.packages = with pkgs; [
    nixpkgs_wine614.wineWowPackages.staging


    (winetricks.override { wine = nixpkgs_wine614.wineWowPackages.staging; })


    (unstable.yabridge.override { wine = nixpkgs_wine614.wineWowPackages.staging; })
    (unstable.yabridgectl.override { wine = nixpkgs_wine614.wineWowPackages.staging; })
  ];
}
```
but that gives me `/nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/Bitwig Studio/Extensions/vst64/Serum_x64.so)`

### Expected behavior
plugins loading

### Notify maintainers
@kira-bruneau 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.84-rt47, NixOS, 21.05.2693.d5aadbefd65 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2693.d5aadbefd65, nixos-unstable-21.11pre309670.253aecf69ed"`
 - channels(roland): `"home-manager-21.05, nixos-unstable-21.11pre310725.870959c7fb3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kira-bruneau** [comment]
Unfortunately we don't maintain old versions of the staging build, so to get this working you'd have to override wine from an older nixpkgs revision.

Although, with #137511 this shouldn't be a problem anymore!
