### ISSUE TITLE
modules: How to specify an option is not optional?

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#13560]
I want to create a module for the [isso](https://posativ.org/isso) discussion system.

When the user enables it, he has to set the config via a `config` option, otherwise isso won’t do anything sensible.

The way I do it now is not set any default and simply use it when enabled, so the module system throws the following error:

```
error: The option `services.isso.config' is used but not defined.
(use ‘--show-trace’ to show detailed location information)
```

I think that could be a bit misleading maybe, is it supposed to be done this way?

**Comment by domenkozar** [comment]
See `nixos/modules/misc/assertions.nix`

**Comment by Profpatsch** [comment]
Sweeeet!

Now, how to document that? It might be sensible to add a writeup of `nixos/modules/misc` to Chapter 22 of the nixos manual.

**Comment by edolstra** [comment]
Doesn't the error message say exactly what the problem is? I.e. that the user needs to define `services.isso.config`.

**Comment by Profpatsch** [comment]
But the user never used the option anywhere, and if one doesn’t know how the module system works (aka that it eats its own dogfood), it might lead to serious self-doubt (“but I didn’t use it *anywhere*. I checked *everything*”).

On the other hand that would be trivially resolved by an error message structured like this:

    error: The option `services.isso.config' is used at `…/nixpkgs/nixos/modules/…/isso.nix:49 but not defined.

**Comment by domenkozar** [comment]
@Profpatsch 22.3 sections sounds good
