### ISSUE TITLE
Setting `services.plex.package` has no effect on the version run

### ISSUE THREAD

**Issue by peperunas** [NixOS/nixpkgs#135724]
### Describe the bug
Setting `services.plex.package` does not result in the correct version being executed. The package is downloaded correctly and the services are written with the right paths. Somehow, the *actual* version that is run by the system is a previous version.

### Steps To Reproduce
1. Set `services.plex.package` to an arbitrary version

### Expected behavior
The system executes the right package.

### Additional context

*plex.nix*:
```
    package = pkgs.plex.overrideAttrs (x: let
        version = "1.24.1.4931-1a38e63c6";
        sha1 = "7d0751f7efaa7b5fc9ac2a3cdb130712db6b6d89";
      in {
        src = pkgs.fetchurl {
          url = "https://downloads.plex.tv/plex-media-server-new/${version}/debian/plexmediaserver_${version}_amd64.deb";
          inherit sha1;
        };
      }
    );
  };
```

*`systemctl status plex` (note the version being executed)*:
```
● plex.service - Plex Media Server
     Loaded: loaded (/nix/store/658akg3f0mmv9ihnqyfgglkrjz9syysi-unit-plex.service/plex.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-08-26 02:12:49 CEST; 6min ago
    Process: 3976490 ExecStartPre=/nix/store/lh6wxvjvwq0pvk2yi6w8hw6687212mfn-plex-run-prestart (code=exited, status=0/SUCCESS)
   Main PID: 3976493 (chrootenv)
         IP: 507.2K in, 357.6K out
         IO: 0B read, 0B written
      Tasks: 58 (limit: 38410)
     Memory: 95.9M
        CPU: 6.622s
     CGroup: /system.slice/plex.service
             ├─3976493 /nix/store/pakqylpxaspsh7l5hm9xisy6pbw2rlnw-chrootenv/bin/chrootenv /nix/store/hw943lpnn2dvffps900rxxwq6b7la7y6-plexmediaserver-init /
             ├─3976501 /nix/store/whcizl7j33carha01081qi704xcz95i5-plexmediaserver-1.23.1.4602-280ab6053/lib/plexmediaserver/Plex Media Server
             ├─3976743 Plex Plug-in [com.plexapp.system] /nix/store/whcizl7j33carha01081qi704xcz95i5-plexmediaserver-1.23.1.4602-280ab6053/lib/plexmediaserver/Resources/Plu>
             ├─3977103 /nix/store/whcizl7j33carha01081qi704xcz95i5-plexmediaserver-1.23.1.4602-280ab6053/lib/plexmediaserver/Plex Tuner Service /nix/store/whcizl7j33carha01>
             └─3977136 Plex Plug-in [com.plexapp.agents.imdb] /nix/store/whcizl7j33carha01081qi704xcz95i5-plexmediaserver-1.23.1.4602-280ab6053/lib/plexmediaserver/Resource>
```

*plex.service (`cat /nix/store/658akg3f0mmv9ihnqyfgglkrjz9syysi-unit-plex.service/plex.service`)*:
```
[Unit]
After=network.target
Description=Plex Media Server

[Service]
Environment="LANG=en_US.UTF-8"
Environment="LC_ALL=en_US.UTF-8"
Environment="LD_LIBRARY_PATH=/run/opengl-driver/lib"
Environment="LOCALE_ARCHIVE=/nix/store/8y24k2dqb62nrv9m8j8jkc2134c7qxka-glibc-locales-2.32-48/lib/locale/locale-archive"
Environment="PATH=/nix/store/xs38mci2dj4isxayifazwdma1dk9w9bl-coreutils-8.32/bin:/nix/store/ccb8104ais1q6mbzq98vsn5lmj2wp88f-findutils-4.7.0/bin:/nix/store/32k710p5xmv4x4lvv5gkqynnw1hixyad-gnugrep-3.6/bin:/nix/store/nhf3114vx6v0gih1gpm3cg3fkyhnclac-gnused-4.8/bin:/nix/store/71lqc2a8cslg4wxj6ypla7gvflphjhn0-systemd-247.6/bin:/nix/store/xs38mci2dj4isxayifazwdma1dk9w9bl-coreutils-8.32/sbin:/nix/store/ccb8104ais1q6mbzq98vsn5lmj2wp88f-findutils-4.7.0/sbin:/nix/store/32k710p5xmv4x4lvv5gkqynnw1hixyad-gnugrep-3.6/sbin:/nix/store/nhf3114vx6v0gih1gpm3cg3fkyhnclac-gnused-4.8/sbin:/nix/store/71lqc2a8cslg4wxj6ypla7gvflphjhn0-systemd-247.6/sbin"
Environment="PLEX_DATADIR=/var/lib/plex"
Environment="PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6"
Environment="PLEX_MEDIA_SERVER_TMPDIR=/tmp"
Environment="PLEX_MEDIA_SERVER_USE_SYSLOG=true"
Environment="PLEX_PLUGINS="
Environment="TZDIR=/nix/store/0fgr90x0rsbl9j2rv3935mrm9mfy0zls-tzdata-2020f/share/zoneinfo"



ExecStart=/nix/store/kk6hrv8zni38jn971aabil9ipzj8lx46-plexmediaserver/bin/plexmediaserver
ExecStartPre=!/nix/store/lh6wxvjvwq0pvk2yi6w8hw6687212mfn-plex-run-prestart
Group=plex
KillSignal=SIGQUIT
Restart=on-failure
Type=simple
User=plex
```

### Notify maintainers
 @badmutex
      @forkk
      @lnl7
      @pjones
      @thoughtpolice

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"                                                                                                                          130 ↵
these 3 paths will be fetched (0.07 MiB download, 0.36 MiB unpacked):
  /nix/store/74kv08wjf06ifgk4dxrnra4qhzr5s1w4-gcc-wrapper-10.3.0
  /nix/store/7gdji02y6rbnzv5mcxcf3mwksk785y8j-stdenv-linux
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/74kv08wjf06ifgk4dxrnra4qhzr5s1w4-gcc-wrapper-10.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7gdji02y6rbnzv5mcxcf3mwksk785y8j-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.05.20210825.bc1a0f5 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.05.2549.a1007637cea, home-manager-21.05, nixos-unstable-21.11pre304920.dd98b100651"`
 - channels(giulio): `""`
 - nixpkgs: `/nix/store/qn3ccbpy48qa2wimxg3awpbfz0v87521-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by MayNiklas** [comment]
Have you tried overwriting plexRaw as well?
It took myself a long time, until I was able to overwrite the plex package.

What has worked for me:
There are two packages.
- pkgs.plex
- pkgs.plexRaw

The plex package inherits plexRaw -> you need to define the package version within plexRaw.
Overwriting the plex package did nothing in my case.

In case you want to look at a example: look into my repository! I'm overwriting plexRaw.
I'm always running the latest plex version to test it, before creating a version bump PR into nixpkgs.

**Comment by peperunas** [comment]
Awesome, thank you @MayNiklas!

One question, though: why the package is not updated with the latest version? I think that a flag `usePlexPass` would be useful if a user has Plex Pass.

**Comment by MayNiklas** [comment]
@peperunas I can't speak for the Nix project as a whole, but I can speak for myself and my own experience regulary updating the plex package. This comment is going to describe the process of a version update in nixpkgs. It should explain, why I personally think there is a good reason not to add another plex Version to NixPkgs.

I'm tracking all the version updates, plex publishes.
There are a lot!

Package maintianers manually have to commit every version bump into the repositories.
nixpkgs has a lot of open PR's - it's a lot of work for the maintainers to go through them.

As soon as plex has a new public (stable) release, I create a PR. Most of the time, I create the PR within a few hours after plex publishes the version to their custom Debian repository. Most of the time, we need 12-72 hours untill the update gets merged into the master branch. After that, the nixos-unstable branch needs to get updated... That causes a small delay as well.
Are you using plex from the nixos-unstable branch or are you using 21.05? I would say, that with the unstable branch, the updates are ~ 5 days behind the release. As it seems, we are currently not backporting plex updates into 21.05. You need to use plex from the unstable branch to get regular updates.

Plex publishes a lot of updates.
Take a look at: https://forums.plex.tv/t/plex-media-server/30447/
Sometimes, we still have an open PR while plex releases the next version.

Talking about the "plex pass version":
Plex pass users are getting beta versions early. It's very usual, to exclude beta packages from package repositories.
Including such a "plex-pass.nix" package, would at least double the number of plex version update PR's (not every beta release gets released as a stable version).
Also: chances are high, that the version is allready outdated, the moment it get's merged into nixos-unstable.
I get it: you are a PlexPass user (I have one too). You would like to receive the newest beta versions. But I personally don't think, it's pracical for a project like nixpkgs.
PR's need to get cretated,  tested & merged. That takes time and ressources!

Also: we are using NixOS: it's pretty easy to use your own custom plex package with the newest releases ;)

Did I helped you solving your problem with plexRaw?
In this case: could you please close the issue?

In case you need additional help with plex & nixos: feel free to contact me.
Depending on your setup, it should help to pin pkgs.plex to the unstable branch.

**Comment by peperunas** [comment]
Thanks again @MayNiklas, incredibly detailed and useful response.

I will just switch to the unstable branch, as you said, it makes more sense.

**Comment by MayNiklas** [comment]
@peperunas You're welcome!
Keep in mind: you don't have to use the unstable branch for your whole system (only if you want to have a rolling release experience). You are able to use the unstable branch just for a few packages.
Of course: switching your whole system is usually easier - imo it's very reliable too!
