### ISSUE TITLE
gvfs/gio modules, e.g. in Xfce + LibreOffice

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#1357]
I'm getting _/nix/store/ybnvr2kfcshxmzrxnlap0mkggcljd6ha-libreoffice-4.0.5.2/lib/libreoffice/program/soffice.bin: symbol lookup error: /nix/store/s6h5058hmjphcdr5nn4jlrh12vc9krgb-gvfs-1.18.3/lib/libgvfscommon.so.0: undefined symbol: g_type_add_instance_private_

That's for master and other versions that used to work. The reference can only come from the system environment setting `GIO_EXTRA_MODULES=/nix/store/s6h5058hmjphcdr5nn4jlrh12vc9krgb-gvfs-1.18.3/lib/gio/modules/` which contains so-files linking to that mentioned libgvfscommon.

There might appear more such errors for people running Xfce (1.16 -> 1.18 update is staged in x-updates), but passing system-wide modules to all executables seems a bad thing in the first place (you can't hope the whole nix store should conform to the same ABI).
CC @edolstra 8d8c250

I would personally not set this variable globally, just perhaps create a configurable package with separately built modules that could be supplied individually via standard wrappers. Any thoughts? (Yes, many similar problems recur a lot, but so far I don't know any better solution.)

**Comment by Profpatsch** [comment]
(triage) @vcunat Probably not broken anymore, right?

**Comment by vcunat** [comment]
Probably still the same, but I'm not certain. I think people mostly use relatively consistent systems, so such problems aren't common.

Two years from this and we still don't have a good plugin system that would solve this kind of stuff comfortably. There's been too many other things that I considered a higher priority...

**Comment by Profpatsch** [comment]
(triage) I suppose no update yet?

**Comment by Profpatsch** [comment]
(triage) what about now
