### ISSUE TITLE
Firebird cp1251 error

### ISSUE THREAD

**Issue by uralbash** [NixOS/nixpkgs#13589]
## Basic info
- Kernel: `Linux nixos 3.18.26 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`
- System: `15.09.1076.9220f03 (Dingo)`
- Nix version: `nix-env (Nix) 1.10`
- Nixpkgs version: `15.09.1076.9220f03`
## Describe your issue here

Unable to connect to database with encoding cp1251

``` bash
[root@nixos:~]# isql /var/db/firebird/data/fortest.fdb -u sysdba -p masterkey
Statement failed, SQLSTATE = 2C000
CHARACTER SET WIN1251 is not installed
-At trigger 'TRIGGER_ON_CONNECT' line: 19, col: 1
Use CONNECT or CREATE DATABASE to specify a database
```

``` bash
[root@nixos:~]# nix-env -q
firebird-2.5.2.26540-0
```

**Comment by Profpatsch** [comment]
triage: can you still reproduce this?

**Comment by uralbash** [comment]
@Profpatsch Yes, I confirm that now it works
