### ISSUE TITLE
DNS responses are cached

### ISSUE THREAD

**Issue by zhenyavinogradov** [NixOS/nixpkgs#135888]
According to https://github.com/NixOS/nixpkgs/pull/89274, NixOS uses nscd only for dispatching nss modules, and caching functionality of nscd is disabled by default. But when I run any application that resolves the same DNS name in a loop on a clean NixOS system, I observe that DNS packets are not sent on each request, they are only sent after ttl elapses. It means that other requests are served from some local cache. Only if I stop nscd service I see the packets being sent on each request.

A simple script to reproduce this: `while true; do getent ahosts github.com; sleep 1; done`

Is there some component other than nscd that does this caching, or does nscd itself needs some extra configuration to actually disable caching?

cc @flokli

**Comment by 3nprob** [comment]
Confirmed.  

When changing nameserver in /etc/resolv.conf, nslookup and dig resolve through new server but other applications return a  cached result. No systemd-resolved/local DNS services

I think this is somewhat new behavior.

```
# echo "nameserver $NS1" > /etc/resolv.conf
# nslookup $HOST
Server:         $NS1
Address:        $NS1#53

Name:   $HOST
Address: $IP1

# ping $HOST
PING $HOST ($IP1) 56(84) bytes of data.
^C

# echo "nameserver $NS2" > /etc/resolv.conf
# nslookup $HOST
Server:         $NS2
Address:        $NS2#53

Name:   $HOST
Address: $IP2

# ping $HOST
PING $HOST ($IP1) 56(84) bytes of data.
^C
```

**Comment by flokli** [comment]
Thanks for the digging! In that case, one more reason to work on https://github.com/NixOS/nixpkgs/issues/55276 :-)

**Comment by ctheune** [comment]
A quick note as we have a similar issue: the caching is so bad that we're affected by negative caches with an unknown but longish (at least multiple minutes) TTL and have to restart nscd. For us, we're debugging some annoyance where one upstream DNS server sometimes (but rarely) does something bad and responds either with a negative answer or times out and I'm a bit suspicious that nscd is caching that timeout as a negative entry (although that doesn't correspond with the timeout glibc fallback behaviour).

**Comment by ctheune** [comment]
I spent some time reading the glibc/nscd code. There was a "recent" change (5e74e6f85842892bc25da8e8c70d8dadd485941a) where the shared cache made a problem. I'm going to try running with a disabled shared cache...

**Comment by ctheune** [comment]
Enabling and disabling the shared flag did not change anything. However, I noticed that doing a negative lookup actually is not cached, but positive values are (based on our current nscd.conf). I wonder what value it is assuming. The code internally has some defaults like 3600 for positive values. Digging deeper.

**Comment by flokli** [comment]
Check `nixos/modules/services/system/nscd.conf` and the git history around it.

**Comment by ctheune** [comment]
Yeah, I'm aware of that. Any specific thing that you think I'm missing?

I'm a bit worried that we do not have tests for this behaviour and that either the previous change was bogus or glibc changed its behaviour without us noticing.

**Comment by flokli** [comment]
> I'm a bit worried that we do not have tests for this behaviour and that either the previous change was bogus or glibc changed its behaviour without us noticing.

Yes, that.

**Comment by ctheune** [comment]
Alright. I set up a test case that shows how to reproduce this and I based it on the original commit where nscd caching was supposedly disabled. It doesn't work even back then: [f9a5a65801889df5848eff0d90b2edeee0fe390a](https://github.com/flyingcircusio/nixpkgs/commit/f9a5a65801889df5848eff0d90b2edeee0fe390a)

I guess next step would be debugging nscd?!? Le sigh.

Anyone got a better idea?

**Comment by flokli** [comment]
I've been iterating a bit with @erikarvstedt on how to accomplish https://github.com/NixOS/nixpkgs/issues/55276 in a non-breaking fashion, which would put nscd out of the loop for most of the requests. This is still WIP though.

**Comment by ctheune** [comment]
Yeah, I've seen that. We're seeing some relevant breakage and I need to come up with a short term fix, though.

**Comment by flokli** [comment]
If you don't need any custom NSS modules (not even nss-systemd for dynamic user resolution), you should be able to disable it already today - with the caveats mentioned in the docs.

**Comment by ctheune** [comment]
Yeah, unfortunately we just started using the container integration with mymachines ... perfect timing ;)

**Comment by ctheune** [comment]
I did some more digging and the whole dance of how nscd works with timeouts and pruning the cache just seems off. I found a piece of code in the `cache_add` method that handles the case of running out of memory and just ignores things added to the cache. I'm currently running a test (waiting for a large system rebuild) that patches this method to always choose the 'ignore the new cache entry' path so nothing will ever be added to the cache. That should solve this reasonably well for now.

**Comment by ctheune** [comment]
Ok, so here's a patch to glibc to just simply deactivate the cache function in NSCD completely. We likely would not want to ship it this way to the general userbase, but I could run it this way on our platform and if we're interested to use this upstream until you r work for ripping nscd out is done then we could add this as a configuration option to nscd or so.

**Comment by tomfitzhenry** [comment]
https://udrepper.livejournal.com/16362.html suggests:

> For all getaddrinfo lookups the TTL value from DNS replies takes precedence over the TTL value from /etc/nscd.conf. The latter is used for services which do not provide a TTL themselves (today all other services). 

i.e. perhaps modifying the `positive-time-to-live` has had no impact because that value is overridden by the DNS TTL.

As an aside, the default `reload-count` of 5 means each DNS query will be re-queried 4 times.

**Comment by ctheune** [comment]
From my perspective (I'm interested in the `negative-time-to-live` case) this looks like it doesn't differentiate between SERVFAIL and NXDOMAIN.

**Comment by 3nprob** [comment]
@stale not stale

**Comment by NinjaTrappeur** [comment]
I've been running this patch today. So far I did not hit any bug. I don't use any dodgy/segfaulting NSS module that being said.

The post-boot/resume firefox name resolution issues I was experiencing are gone.

**Comment by flokli** [comment]
I sent a proper PR to nixpkgs, see https://github.com/NixOS/nixpkgs/pull/196917.

**Comment by fgaz** [comment]
> The post-boot/resume firefox name resolution issues I was experiencing are gone.

Enabling nsncd through the new option fixed it for me too! I hated that issue...

**Comment by flokli** [comment]
Good to hear! Let's see if we here any negative reports, otherwise we should probably default to this after some more testing…

**Comment by QuantMint** [comment]
I think that this issue can be closed, nsncd is now used by default: https://github.com/NixOS/nixpkgs/pull/214153

**Comment by flokli** [comment]
Yes, thanks for the ping.
