### ISSUE TITLE
Stellarium broken?

### ISSUE THREAD

**Issue by anojo** [NixOS/nixpkgs#13582]
## Basic info

To make sure that we are on the same page:

* Kernel: Linux rui-pc 4.1.17 #1-NixOS SMP Sun Jan 31 19:23:48 UTC 2016 x86_64 GNU/Linux
* System: 16.03.git.2e5ca9a (Emu)
* Nix version: nix-env (Nix) 1.11.1
* Nixpkgs version: 16.09.git.2e5ca9a

## Describe your issue here

Stellarium builds but doesn't open. Only shows the splash screen for a second and then it closes. 

> Intializing basic GL shaders... 
> qrc:/qml/main.qml:3:1: plugin cannot be loaded for module "Qt.labs.shaders": The plugin '/nix/store/akr4y271r7r8fakz1jp6q9a83gzwm8nj-qtquick1-5.5.1/lib/qt5/imports/Qt/labs/shaders/libqmlshadersplugin.so' uses incompatible Qt library. (5.5.1) [release]
> [1]    32765 segmentation fault  stellarium

**Comment by vcunat** [comment]
On current nixos-unstable I'm getting a different error:

> QProcess: Destroyed while process ("lspci") is still running.

and it ends with sigabrt instead of segfault. /cc maintainer @peti.

**Comment by peti** [comment]
Unfortunately, all that qt stuff is like black magic for me. I have no clue what is causing those errors. :disappointed:

**Comment by vcunat** [comment]
Well, the reported qml errors above are pretty standard, I guess. @ttuegel should know how to fix these by wrapping. The issue I'm getting seems more opaque, but perhaps it's a different manifestation of the same.

**Comment by ttuegel** [comment]
Stellarium should use `qt5.callPackage` rather than depending on `qt5Full`. All executables should be wrapped with `wrapQtProgram` from `makeQtWrapper`.

**Comment by peti** [comment]
I couldn't test the new version because I don't access to a NixOS machine right now. Please let me know if the issue persists.

**Comment by cleverca22** [comment]
http://nixpaste.lbr.uno/VPNGH-KW?nix
http://nixpaste.lbr.uno/xN65cLUL?nix
still crashes on nixos-unstable (when building the new version from master)

**Comment by vcunat** [comment]
Yes, on 288d01f I'm still getting the same crash as before.
