### ISSUE TITLE
Enable bear installation on macOS >10.15

### ISSUE THREAD

**Issue by byte1234** [NixOS/nixpkgs#135873]
### Describe the bug
bear is marked as broken on macOS x86_64 now
https://github.com/NixOS/nixpkgs/blob/e87001bbc0afec6561212473c7b2466fb74ad848/pkgs/development/tools/build-managers/bear/default.nix#L63
but it can be built on macOS>10.15 as the pkg repo says: https://github.com/rizsotto/Bear/blob/master/INSTALL.md#platform-macos

**Comment by byte1234** [comment]
@prusnak I was trying to install on **x86_64-darwin**(macOS 11.2), but it kept to trying to compile with clang-7.0 from nixpkgs, how can I force nix-env to compile with the clang-12 from OS or the newest llvm-13.rc from nixpkgs.
sorry for bothering you with this, I new to nix-env.

**Comment by veprbl** [comment]
You need nixpkgs new enough to include  #135989
