### ISSUE TITLE
Setting xdg.portal.gtkUsePortal=true causes a significant delay when starting a GNOME session

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#135898]
### Describe the bug
After setting `xdg.portal.gtkUsePortal = true`, logging into a GNOME session (with GDM) until the desktop is shown takes about 70 seconds on my system, while with `xdg.portal.gtkUsePortal = false` it takes about 20 seconds.

### Steps To Reproduce
1. Try logging in when `xdg.portal.gtkUsePortal = false`.
2. Try logging in when `xdg.portal.gtkUsePortal = true`.

### Expected behavior
I would not expect a 3x slowdown.

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60-hardened1, NixOS, 21.05.2729.9d6766c0f0b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(alexey): `""`
 - channels(root): `"nixos-21.05.2729.9d6766c0f0b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by maydayv7** [comment]
Facing the same issue

**Comment by ivankovnatsky** [comment]
I had similar issue on sway: https://github.com/swaywm/sway/issues/6587

added overlay for git xdg-desktop-portal: https://github.com/ivankovnatsky/nixos-config/blob/main/overlays/xdg-desktop-portal.nix

**Comment by SuperSamus** [comment]
Is there any reason why this isn't closed yet?

**Comment by alexeymuranov** [comment]
> Is there any reason why this isn't closed yet?

It is not resolved.

**Comment by Lyndeno** [comment]
Seems to still not be resolved. I have not tried setting ```gtkUsePortal = false``` yet to confirm however.

> Facing the same issue, X11 GNOME 40.1, even `gdm` seems to be affected No related logs found

What issues were you experiencing with gdm? I am experiencing this thing on unstable where when the screen times out while in gnome, I'll wake the screen to find the tty is switched to the gdm lock screen. I have to switch the tty back to my current gnome session.

**Comment by maydayv7** [comment]
> What issues were you experiencing with gdm?.
GDM takes almost 3x the amount of time to load in, as well as about 5x the amount of time to start `gnome-shell` after login. Memory usage shoots up from about 600MB on idle to 2.4GB. Suspension sometimes crashes the system, TTY switching sometimes logs out session. None of these problems occur when `gtkUsePortal = false`

On GNOME 42, NixOS 22.05

**Comment by SuperSamus** [comment]
I think that this can now be closed, since `xdg.portal.gtkUsePortal` has been removed.

**Comment by jtojnar** [comment]
We still have it in 22.05 so unless we backport https://github.com/NixOS/nixpkgs/pull/179204, it might be better to keep it open for visibility.

**Comment by SuperSamus** [comment]
With NixOS 22.11 coming soon, I guess that this can now be closed.
