### ISSUE TITLE
Usage of nix.useChroot by default

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#13596]
Why don't we use `nix.useChroot` in NixOS by default? I cannot see any immediate disadvantages of doing this, but I may be missing something. Right now we often advice people to enable it themselves -- I've yet to see one case when someone recommended to disable it.

**Comment by NeQuissimus** [comment]
I would suggest this very old issue:

https://github.com/NixOS/nix/issues/179

TL;DR: Quite a bit of overhead by using a chroot.

**Comment by abbradar** [comment]
Hm, that's a point. However this is _de facto_ required to be sure that nothing is broken during packaging new things, so disabling it may be useful only if user has made some patch that is both (a) local for him, so he doesn't need to test it extensively and (b) mass rebuild-y. In other cases (typical PRs or just regular use) either number of built (not fetched) derivations would be too small to notice or the user would need to enable chroot for testing prior to submitting a PR anyway.

**Comment by edolstra** [comment]
Closing as a dup of https://github.com/NixOS/nix/issues/179, let's keep the discussion in one place.
