### ISSUE TITLE
xen fails to build on master

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#13590]
I tried updating it, but no luck. I think the new glibc 2.23 is the reason for configure fail: http://hydra.nixos.org/build/32552024/log/tail-reload

I've only been able to find arch having the same issue, no patch yet.

cc @vcunat

**Comment by vcunat** [comment]
This is strange. I do reproduce the build problem, but when I compile the configure test and run it myself, it succeeds (and measures `2` bytes). (Of course I do compile it with the stdenv from 16.03.)

**Comment by domenkozar** [comment]
Comments on https://aur.archlinux.org/packages/xen/ note a workaround.

**Comment by domenkozar** [comment]
Temporary workaround on arch: https://gitlab.com/johnth/aur-xen/commit/980a43d96ac1aa8796d16956a2b244010a24a378

**Comment by vcunat** [comment]
Fixed then?

**Comment by liuw** [comment]
FYI the fix to Xen build system is committed.

See

https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=668e4edf92fcf7cb929eed221059a3eeb02722c3
