### ISSUE TITLE
ffmpeg checks broken on x86_64-darwin

### ISSUE THREAD

**Issue by ggPeti** [NixOS/nixpkgs#136070]
### Describe the bug
nixpkgs/nixpkgs-21.05-darwin#ffmpeg fails to build on x86_64-darwin since https://github.com/NixOS/nixpkgs/commit/7361aaeb5ed2e301018ec33a3a18f0865cd384b2.

```console
GEN     tests/data/hls-list.m3u8
/bin/sh: line 2: 64656 Abort trap: 6           /private/tmp/nix-build-ffmpeg-4.4.drv-1/ffmpeg-4.4/ffmpeg -f lavfi -i "aevalsrc=cos(2*PI*t)*sin(2*PI*(440+4*t)*t):d=20" -f segment -segment_time 10 -map 0 -fl
make: *** [tests/fate/filter-audio.mak:205: tests/data/hls-list.m3u8] Error 134
```

### Steps To Reproduce
1. `nix build nixpkgs/nixpkgs-21.05-darwin#ffmpeg` on x86_64-darwin

### Expected behavior
The package builds.

### Screenshots
N/A

### Additional context
The error is in checkPhase.

### Notify maintainers
@risicle committed the change
@lukegb merged it in https://github.com/NixOS/nixpkgs/pull/135025
@codyopel is the maintainer

### Metadata

```console
 - system: `0`
 - host os: `Darwin 20.5.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210823_af94b54`
```

**Comment by risicle** [comment]
Might this be down to the sandbox? I tested it on macos 10.15 without the sandbox.

**Comment by ggPeti** [comment]
Can you try it with the sandbox?
