### ISSUE TITLE
Request: vimPlugins.neon

### ISSUE THREAD

**Issue by sestrella** [NixOS/nixpkgs#136041]
**Project description**
> Customizable coloscheme with dark and light options, vivid colors and easy on the eye.

**Metadata**

* homepage URL: https://github.com/rafamadriz/neon
* source URL: https://github.com/rafamadriz/neon
* license: gpl3
* platforms: unix, linux, darwin

**Comment by sestrella** [comment]
I'm working on PR for this, but I'm just having a hard time running `GITHUB_API_TOKEN=my_token ./pkgs/misc/vim-plugins/update.py --add "rafamadriz/neon" --proc 2` locally

**Comment by figsoda** [comment]
you need to do this because the update script defaults to master branch
```diff
- [...] "rafamadriz/neon" [...]
+ [...] "rafamadriz/neon@main" [...]
```

**Comment by sestrella** [comment]
@figsoda good catch, switching the branch to `main` made it work. Thanks!
