### ISSUE TITLE
Add a command_not_found_handler for zsh

### ISSUE THREAD

**Issue by fare** [NixOS/nixpkgs#13608]
## Basic info

To make sure that we are on the same page:

* Kernel: 4.5.0-rc3
* System: NixOS 16.03pre76756.885acea (Emu)
* Nix version: nix-env (Nix) 1.11.1
* Nixpkgs version: 16.03pre77568.40c586b

## Describe your issue here
The default /etc/bashrc has a cool function command_not_found_handle().
The equivalent for zshrc should have a function command_not_found_handler().
Note the final letter "r" in the name of the function under zsh, unlike in bash.
See http://zsh.sourceforge.net/Doc/Release/Command-Execution.html for zsh information.
The body of the function could probably be the same as for bash.

Example:
$ sox

### Expected result
The program ‘sox’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.sox
zsh: command not found: sox

### Actual result
zsh: command not found: sox

### Steps to reproduce
Be sure not to have sox installed, or use another uninstalled command instead.

**Comment by puffnfresh** [comment]
I'm pretty sure this feature was added a while ago. It works for me:

![2016-03-02-153834_863x373_scrot](https://cloud.githubusercontent.com/assets/37715/13450764/d7471a68-e08c-11e5-87c4-e8a72e47de2a.png)

**Comment by NeQuissimus** [comment]
I have a `command_not_found_handler` but my shell does not seem to run it(?)

This is what happens for me:

```
~> echo $SHELL
/nix/store/jpwva2ny7n7pl8ffbzcqv5w97318r0w3-zsh-5.2/bin/zsh
~> sox
sox: command not found
~> which command_not_found_handler
command_not_found_handler () {
        local p=/run/current-system/sw/bin/command-not-found 
        if [ -x $p -a -f /nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite ]
        then
                $p "$@"
                if [ $? = 126 ]
                then
                        "$@"
                fi
        else
                return 127
        fi
}
~> 
```

**Comment by NeQuissimus** [comment]
What fills this `programs.sqlite`?
I simply have no entry for `sox`, when I look into it.

```
sqlite> select package from Programs where name = 'sox';
```

**Comment by puffnfresh** [comment]
@NeQuissimus interesting, mine is populated:

```
sqlite> select * from Programs where name = 'sox';          
sox|i686-linux|sox
sox|x86_64-linux|sox
```

**Comment by puffnfresh** [comment]
The `programs.sqlite` comes from the NixOS channel:

```
$ realpath /nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite 
/nix/store/s3bg8v39p5fmw7axgqp6dva5zh3rpryr-nixos-15.09.1076.9220f03/nixos/programs.sqlite
```

**Comment by NeQuissimus** [comment]
So now the difference is that @fare and I are on 16.03, you are using 15.09.

```
zsh 464 # nix-channel --list
nixos https://nixos.org/channels/nixos-unstable-small
```

`sox` does exist when I search for it with `nix-env -qaP sox`.

**Comment by puffnfresh** [comment]
I just did an update on the channel and now I don't have a `programs.sqlite`. Looks like this was recently broken.

**Comment by NeQuissimus** [comment]
```
zsh 467 # nix-channel --update
downloading Nix expressions from ‘https://nixos.org/releases/nixos/unstable-small/nixos-16.09pre77948.c23874d//nixexprs.tar.xz’...
downloading ‘https://nixos.org/releases/nixos/unstable-small/nixos-16.09pre77948.c23874d//nixexprs.tar.xz’... [6688/7018 KiB, 2146.4 KiB/s]
unpacking channels...
created 2 symlinks in user environment
[Thu 16/03/03 23:33 UTC][pts/0][x86_64/linux-gnu/4.5.0-rc5][5.2]
<root@nixus:~>
zsh 468 # realpath /nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite
/nix/store/nfslyznq09jpyhk86ldaq1437fss50xc-nixos-16.09pre77948.c23874d/nixos/programs.sqlite
```

Not sure whom to ping for this for more insight... @edolstra ?

**Comment by edolstra** [comment]
`programs.sqlite` generation is currently disabled, see https://github.com/NixOS/nixos-channel-scripts/issues/4.

**Comment by layus** [comment]
@fare: This should really be closed, as the issue is not relevant (there already exists a command_not_found_handler for zsh) and other issues already address the missing programs.sqlite database.

**Comment by vcunat** [comment]
I agree.
