### ISSUE TITLE
GNOME Tweaks “Suspend when lid is closed” broken

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#136066]
### Describe the bug
When the option is toggled, Tweaks log the following error on startup:

```Python traceback
Traceback (most recent call last):
  File "/nix/store/mf2vgpvgylvhy1jiz8rw56bz7b6dy4kg-gnome-tweaks-40.0/libexec/.gnome-tweak-tool-lid-inhibitor-wrapped", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

### Steps To Reproduce
1. Open _GNOME Tweaks_
2. In _General_ tab, toggle _Suspend when lid is closed_

### Expected behaviour
It should prevent laptop suspension.

### Additional context
The binary needs a python wrapper.

Additionally, the setting creates `~/.config/autostart/ignore-lid-switch-tweak.desktop` which contains a store path, which might break on garbage collection.

### Notify maintainers
cc @NixOS/gnome

**Comment by alex-robbins** [comment]
For me the error is 
```
Traceback (most recent call last):
  File "/nix/store/5lhwrxwsrw3q7r3sp388i6knwi498z97-gnome-tweaks-40.0/libexec/.gnome-tweak-tool-lid-inhibitor-wrapped", line 6, in <module>
    gi.require_version("GLib", "2.0")
AttributeError: module 'gi' has no attribute 'require_version'
```

because I have a file `/run/current-system/sw/lib/python3.9/site-packages/gi/overrides/Gedit.py` which causes the `gi` module to exist but not have anything in it. 

> The binary needs a python wrapper.

Doesn't it have one? My take was that `gnome-tweaks` needs a dependency on the `PyGObject` python package.

**Comment by jtojnar** [comment]
> because I have a file `/run/current-system/sw/lib/python3.9/site-packages/gi/overrides/Gedit.py` which causes the `gi` module to exist but not have anything in it.

Even if you have python modules linked to your system profile, Python still should not pick them up. Unless something is contaminating the `PYTHONPATH` environment variable.

> > The binary needs a python wrapper.
> 
> Doesn't it have one?

By default, only executables in package’s `bin/` directory are wrapped:

https://github.com/NixOS/nixpkgs/blob/b929b0084f6052babd6c177ffa52aefe54da315e/pkgs/development/interpreters/python/wrap.sh#L3-L4

**Comment by alex-robbins** [comment]
> Even if you have python modules linked to your system profile, Python still should not pick them up. Unless something is contaminating the PYTHONPATH environment variable.

Oh yeah, I forgot. It's me. I'm the one contaminating the `PYTHONPATH`. I did it on purpose a while ago and it didn't occur to me that that's why my exception was different than yours, or I wouldn't have left my previous comment in the first place.

> By default, only executables in package’s `bin/` directory are wrapped:

Oh, I see. Thanks.

**Comment by Artturin** [comment]
Please test #140236

**Comment by Artturin** [comment]
> Additionally, the setting creates `~/.config/autostart/ignore-lid-switch-tweak.desktop` which contains a store path, which might break on garbage collection.

in the built package this is in `lib/python3.9/site-packages/gtweak/tweaks/tweak_group_general.py`

```
        self._dfile = AutostartFile(None,
                                    autostart_desktop_filename = "ignore-lid-switch-tweak.desktop",
                                    exec_cmd = self._inhibitor_path)
```

**Comment by alex-robbins** [comment]
I opened #140336 for this:
> Additionally, the setting creates ~/.config/autostart/ignore-lid-switch-tweak.desktop which contains a store path, which might break on garbage collection.
