### ISSUE TITLE
Gnome Screenshot Tool doesn't work without `gjs` installed

### ISSUE THREAD

**Issue by chrisportela** [NixOS/nixpkgs#136112]
### Describe the bug
Simply installing `gnomeExtensions.screenshot-tool` does not work because it requires `gjs` as well, but this is not included when installed nor is it said anywhere it's needed. Most extensions do not need `gjs` from my limited experience.

Probably should be patched to use gjs automatically or suggest adding gjs as well.

### Steps To Reproduce
1. New install with Gnome
2. Add `gnomeExtensions.screenshot-tool` to packages
3. Enable on Gnome
4. Try to take a screenshot
5. Error about missing `gjs`

### Expected behavior
Take expected screenshot and allow user to copy/save it.

### Notify maintainers
@piegamesde 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[cmp@cp-hermes:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.05.2717.bc1a0f56812 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(cmp): `"home-manager-21.05, nixpkgs-unstable-21.11pre311289.503209808cd"`
 - channels(root): `"nixos-21.05.2717.bc1a0f56812"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gnomeExtensions.screenshot-tool
# a list of nixos modules affected by the problem
module:
  - gnomeExtensions.screenshot-tool
```

**Comment by piegamesde** [comment]
Can you please check if the underlying error is the same as in #125363?

**Comment by jtojnar** [comment]
This is either a shebang thing or an explicit `exec` call. The former should be trivial to resolve with `chmod +x`, `gjs` in `buildInputs` and `patchShebangs`; the latter would require a patch.

**Comment by chrisportela** [comment]
@piegamesde Unlike what they report in that issue, for me installing `gjs` in system packages made it work immediately. The error does look very similar except it shows as a notification instead of needing to look in the journal.

**Comment by piegamesde** [comment]
> for me installing gjs in system packages made it work immediately.

Just looked at the code, and they are doing something like `spawn("gjs …")`. Thus, it will be found if on your path.
