### ISSUE TITLE
ddcutil gnome extension hard codes ddcutil path

### ISSUE THREAD

**Issue by chrisportela** [NixOS/nixpkgs#136111]
### Describe the bug
`ddcutil` has a gnome extension which uses `/usr/bin/ddcutil` instead of the path of the `ddcutil` package.

Because it can't find the binary it simply says "Initializing" forever. And there is no built-in way to tell it to use another path.

### Steps To Reproduce
1. Install `ddcutil` and `gnomeExtensions.brightness-control-using-ddcutil`
2. Restart Gnome 3; Enable the ddcutil extenstion in Gnome

### Expected behavior
Ability to control monitor brightness and etc.

### Screenshots
![image](https://user-images.githubusercontent.com/505649/131261577-c1ec0298-91e1-4082-8357-16c15c7af851.png)

### Additional context
- [This is the line where they made the const variable](https://github.com/daitj/gnome-display-brightness-ddcutil/blob/74dcec567969088a67752d244a4d2aa32946f35f/display-brightness-ddcutil%40themightydeity.github.com/extension.js#L64)

### Notify maintainers
@piegamesde 

### Metadata

```console
[cmp@cp-hermes:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.05.2717.bc1a0f56812 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(cmp): `"home-manager-21.05, nixpkgs-unstable-21.11pre311289.503209808cd"`
 - channels(root): `"nixos-21.05.2717.bc1a0f56812"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gnomeExtensions.brightness-control-using-ddcutil
# a list of nixos modules affected by the problem
module:
  - gnomeExtensions.brightness-control-using-ddcutil
```

**Comment by piegamesde** [comment]
Can this be fixed upstream? We could ask them to use `/usr/bin/env`, but that would require the package in the system environment, wouldn't it?

**Comment by chrisportela** [comment]
For my situation that would work since I have `ddcutil` installed for me to use as well in the terminal. But if we wanted to make it so this would work installed on it's own then yea I think it would require putting `ddcutil` in env if we don't patch it to use the binary directly.
