### ISSUE TITLE
Alacritty crashes on start

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#136123]
### Describe the bug

I'm unable to start Alacritty, it just crashes. It used to work fine.

### Steps To Reproduce

Try to start Alacritty from some other terminal:

```
$ alacritty 
Created log file at "/tmp/Alacritty-14935.log"
[2021-08-29 23:29:28.692651927] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                        Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("`glXQueryExtensionsString` found no glX extensions")]`
```

### Expected behavior

I expected Alacritty to start, not crash.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - nixpkgs: `/etc/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: alacritty
# a list of nixos modules affected by the problem
module:
```

**Comment by boppyt** [comment]
Have you perhaps updated your graphics driver / opengl recently?
If so, have you tried rebooting it?
Seems like alacritty wasn't able to find usable OpenGL driver.

You might have to check if there's an update for your GPU driver, if you haven't.

p.s have you checked the issues on alacritty repo? There's few issues that might help you, search for `Error creating GL context`.

**Comment by kaiju** [comment]
Same problem, a lot of GL related things seem to have broken recently in unstable. Had to switch back to the 21.05 channel to get anything done.

**Comment by ThreshMain** [comment]
Same problem on 21.05 after upgrade

**Comment by dimas-cyriaco** [comment]
Got the same problem on a fresh install of PopOS:

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.5-76051505-generic, Pop!_OS, 21.10`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixpkgs-22.05pre338661.3c52ea8c921"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

It works fine when installed via the normal package manager.

**Comment by PAI5REECHO** [comment]
For me running with `env WAYLAND_DISPLAY= alacritty` allows it to run avoiding the OpenGL error on Intel integrated graphics. I'm sure what the correct fix to avoid this is though. `WAYLAND_DISPLAY` is `wayland-1` for me by default after starting SwayWM, which must be wrong.

**Comment by jluttine** [comment]
This is now happening again on nixos-unstable. (It worked at some point..)

**Comment by jluttine** [comment]
Actually, never mind. It works for me. I just accidentally had alacritty installed from different nixpkgs commit than my system stuff.
