### ISSUE TITLE
No packages in node_modules folder after successful mkYarnModules

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#136132]
### Describe the bug

After building a nix-shell which includes `mkYarnModules` there's an almost empty `node_modules` folder in the Nix store, and no `node_modules` folder in the project directory.

### Steps To Reproduce
1. `cd "$(mktemp --directory)"`
2. `tar -zxf` [example.tar.gz](https://github.com/NixOS/nixpkgs/files/7073422/example.tar.gz)
3. `nix-shell`

### Expected behavior

All the packages mentioned in `yarn.lock` should be installed in the Nix store output directory, `/nix/store/yvvdrwybqmar6634w3qwxz8i9p5p9dbk-lds-data-redactor-yarn-deps-0.0.1/node_modules`.

### Actual behavior

The only file in the above directory is a `.yarn-integrity`. No files were created in the project directory (that is, where `shell.nix` resides).

### Additional context
Running on Arch Linux.

Another way to reproduce from scratch:

```
cd "$(mktemp --directory)"
yarn add noop # Or any other package, like aws-cdk
rm -r node_modules
cat > shell.nix <<'EOF'
let
  pkgs = import <nixpkgs> { };

  nodeModules = pkgs.mkYarnModules {
    pname = "example-yarn-deps";
    version = "0.0.1";
    packageJSON = ./package.json;
    yarnLock = ./yarn.lock;
  };
in
pkgs.mkShell {
  buildInputs = [
    nodeModules
  ];
  shellHook = ''
    export PATH="${nodeModules}/node_modules/.bin:$PATH"
  '';
}
EOF
nix-shell
```

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60-1-lts, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(victor): `"nixpkgs-21.11pre311289.503209808cd"`
 - channels(root): `"nixpkgs-21.11pre310022.14b0f20fa1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: mkYarnModules
# a list of nixos modules affected by the problem
module:
```

**Comment by vincentbernat** [comment]
I get the same result. This is a bit puzzling.

**Comment by vincentbernat** [comment]
I got it working by adding `name` and `version` to package.json. It seems it is mandatory to have them to make it work. You can check with `nix log result/` if this is also your case. I got something like this:

```
warning Missing name in workspace at "/build/deps/www-yarn-modules", ignoring.
```
