### ISSUE TITLE
OBS Browser source is transparent on wayland

### ISSUE THREAD

**Issue by NilsIrl** [NixOS/nixpkgs#136184]
### Describe the bug

The browser source doesn't work on wayland (I don't know about X11).

### Steps To Reproduce
1. Add browser source
2. The obs page doesn't appear (the default URL)

![image](https://user-images.githubusercontent.com/26231126/131348194-5a3821b8-dc76-44cb-a383-3747ed427893.png)

### Expected behavior

Something like this:

![image](https://user-images.githubusercontent.com/26231126/131348153-17089892-28dc-4035-abb9-ee5d510ccf6d.png)

### Additional context

I asked to discord people in discord and here's what they had to to say: recent versions of libcef have problems and they recommended to use 4280. However, this version failed to build with a compilation error.

### Notify maintainers

@Munksgaard @jb55 @MP2E @V 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.57, NixOS, 21.05.2549.a1007637cea (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(nils): `""`
 - channels(root): `"nixos-21.05.2549.a1007637cea, nixos-unstable-21.11pre306003.c464dc811ba"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

**Comment by hmenke** [comment]
Probably duplicate of https://github.com/NixOS/nixpkgs/issues/62244

**Comment by fpletz** [comment]
Closing since #62244 was closed as well. Not a NixOS issue.
