### ISSUE TITLE
ausweisapp2 does not see smartphone as network-device

### ISSUE THREAD

**Issue by schlichtanders** [NixOS/nixpkgs#136269]
### Describe the bug
The ausweisapp2 has the feature that you can use a smartphone in the same wifi network as a authorization device. This does not work on nixos for me right now.

My smartphone successfully connected to AusweisApp2 on Windows, however nixos ausweisapp2 fails to see the smartphone altogether.

### Steps To Reproduce
1. install nixos 21.05
2. install ausweisapp2 on nixos
3. install ausweisapp2 on android smartphone
4. follow the instructions of ausweisapp2 for pairing the desktop app with the smartphone https://www.ausweisapp.bund.de/ausweisapp2/help/1.22/en/Windows/settings-remote-reader.html
5. The step "Your smartphone should now show up in the list of available remote devices." unfortunately does not work - nothing pops up 

instead of the desired result
![image](https://user-images.githubusercontent.com/4255480/131464883-1e0abefb-5bdf-4f5d-9361-8e7b52b265b8.png)

it stays like this for me
![Screenshot_20210831_095627](https://user-images.githubusercontent.com/4255480/131465132-8aee0ecc-543d-422d-89fb-0d9586abde88.png)

### Notify maintainers
@B4dM4n  can you help?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
- system: `"x86_64-linux"`
- host os: `Linux 5.13.12, NixOS, 21.05.2693.d5aadbefd65 (Okapi)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.3.15`
- channels(root): `"nixos-21.05.2693.d5aadbefd65"`
- channels(ssahm): `"nixos-21.05.1226.f77036342e2"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wnklmnn** [comment]
Hi,  it seems to be necessary to open port 24727 to be able to use a smartphone as a reader.
https://github.com/Governikus/AusweisApp2/blob/08d15199489e13b084fa515a6490787bcf3414fb/docs/installation/README.en.rst#used-network-ports

**Comment by schlichtanders** [comment]
worked immediately! thank you very much for your help

**Comment by wnklmnn** [comment]
Is there any place where this could be documented? So future users do not have to search for the solution again?

**Comment by schlichtanders** [comment]
would be nice if it could appear hear: https://search.nixos.org/packages?channel=21.05&from=0&size=50&sort=relevance&type=packages&query=ausweisapp2

I guess this just grabs the meta information of the derivation

**Comment by wamserma** [comment]
@schlichtanders @wnklmnn In case https://github.com/NixOS/nixpkgs/pull/136726 gets merged, this should be documented at
https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=ausweisapp
Feel free to test/review the PR.
