### ISSUE TITLE
Scala packages are not versioned deterministically

### ISSUE THREAD

**Issue by trane** [NixOS/nixpkgs#13620]
## Basic info

To make sure that we are on the same page:

* Nix version: https://github.com/NixOS/nixpkgs/commit/ba0582670796acdeeb9ab0001a7edd0b08290d4f
* Nixpkgs version: https://github.com/NixOS/nixpkgs/commit/ba0582670796acdeeb9ab0001a7edd0b08290d4f

## Describe your issue here

I can't compile code using specific versions of Scala.

### Expected result

I can specify buildInputs or package dependencies for specific versions of Scala

### Actual result

I can only reference the current stable release

**Comment by joachifm** [comment]
I think this issue can be closed, per the discussion in the linked PR?

**Comment by puffnfresh** [comment]
@joachifm I agree!
