### ISSUE TITLE
Restrict nixpkgs

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#13625]
1. Document types of derivations that won't make it into nixpkgs
2. Create a repo where such packages are allowed? (may be legally hard)

Requests that have been rejected are: #10006 #7597 #10981

**Comment by skrzyp** [comment]
That might be named `nixpkgs-tooUnfreeToBeInNixpkgsEvenAsUnfre` if we look into mentioned requests :)

**Comment by edolstra** [comment]
I don't think it's a problem to have a repo with Nix expressions for unfree packages, as long as they don't try to download packages in dubious ways (e.g. use Bittorrent rather than `requireFile`).

**Comment by vcunat** [comment]
I believe this issue was meant primarily for packages for which sources can *not* be normally downloaded, because the companies will only allow it when you pay.

**Comment by joachifm** [comment]
There's also the issue of were to draw the line wrt. proprietary software. A separate repository would serve as of a free-for-all place of sin, limiting the taint of software bondage in the main nixpkgs. A clear policy would also reduce frustration for would-be contributors, I think.

**Comment by spacefrogg** [comment]
As the structure of nixpkgs is open, everybody is free to make their own repositories of packages they want to maintain for their own use. Maybe we could add some infrastructure to easily add repositories from the outside to a user's package universe (like layman for gentoo).

In any way, we should not add packages to official repositories that cannot be legally (or morally?) supported.

**Comment by joachifm** [comment]
@spacefrogg adding repositories is as easy as adding it to the nixpkgs path, so that part is already supported.

**Comment by joelmo** [comment]
Yes I'm mostly interested in having a guideline of what can be accepted in nixpkgs/nixos. oraclejdk was accepted while another was not when the expressions are similar.

Some examples of rules describing what can't be allowed:
- Fetching unfree binaries without using requireFile from file hosts such as dropbox
- Using sources only targeted for unsupported platforms (Windows?)

And some obvious:
- Packages containing malicious code
- Bad code standard

Yes adding user repositories is already supported, one can use nix-channel or ~/.nixpgs/config.nix. But the way is set up now is that a top-level attr needs to call the packages. This makes it less convenient to move some expressions to another repository. Another issue suggested that the directory structure can be flattened, this would help a bit.

**Comment by vcunat** [comment]
IMHO Oracle's JDK/JRE is an exception because it is relatively popular. Or it used to be, at least; it's possible we already do have good-enough alternatives for its most common use cases.

**Comment by vcunat** [comment]
BTW, note that some packages do work on windows, both native cygwin and cross-compiled mingw, although it's not too well maintained ATM.

**Comment by matthewbauer** [comment]
also see #10213 for another issue

libfmodex requires you to be logged in to download unfree binaries.

**Comment by zimbatm** [comment]
> I don't think it's a problem to have a repo with Nix expressions for unfree packages, as long as they don't try to download packages in dubious ways (e.g. use Bittorrent rather than requireFile).

Actually... bittorrent downloads would be more stable in regards to the hash ^_^

**Comment by joachifm** [comment]
I propose that the people who want/need proprietary software get together and create a fork for that purpose. Announce it on the ML or something, provide simple step-by-step instructions for end-users.I don't think it needs to be managed by or endorsed by the NixOS org, as long as it is known in the community.

**Comment by skrzyp** [comment]
Steam is also the good example of "unftree but popular" so guidelines must be written with special care.

**Comment by vcunat** [comment]
Note that purging *all/most* unfree SW from nixpkgs would be a major change, as there's some rather popular stuff, firmware and drivers (e.g. flash, nvidia, skype). Unfree packages are hidden by default and not built by Hydra, but they *are* there and they're easy to enable. IMHO that's a good compromise.

Then there are stronger kinds of restrictions that are less common and make life harder:
- Non-redistributability. (Even `nix-copy-closure` becomes dangerous.)
- Some parts can't be downloaded automatically (or doing so is legally dubious). Currently we have ~30 such packages in nixpkgs: `git grep -l requireFile | wc -l`.
- It can't be used without charge.

##### I suggest:
1. Agree on where to draw the line, and document that.
2. Setup a separate nixpkgs-restricted repo. If there's consensus it doesn't belong into official http://github.com/NixOS, I'm willing to accomodate it on http://github.com/vcunat.
3. Agree on a way how to plug them together smoothly.

**Comment by zimbatm** [comment]
The tricky bit is going to be to be able to depend on a stable nixpkgs. Moving two repos at the same time is going to be a lot of work IMO.

**Comment by spacefrogg** [comment]
I am with @vcunat on 1. and 3.
For 2. I propose to use 3. (an 'official' way to plug repos together) and make non-official but public repositories discoverable by machine. The paludis package manager from exherbo has a special repository-containing type of repository. This way a user can 'install'/'remove'/'manage'/'query' all sorts of repositories on her own. The paludis people go as far as they also collect package names and dependencies for foreign repositories, such that the user has a global view of possibly available software. This, e.g., allows for easy in-house software repositories (special versions, patches).

To emphasize my proposal, the most important part would be a clearly defined and clean interface that allows people to manage foreign repositories (especially packages from there) and let foreign packages interact with / depend on official ones in a consistent manner. By that, we would reduce the pressure on people to get their packages into the official repository in cases of doubt. And it would reduce the maintenance burden from the official package tree (e.g. for esoteric packages, which could easily be outsourced).

**Comment by vcunat** [comment]
Creating and using (private) repositories depending on nixpkgs is easy and often used, IMHO. You just `import <nixpkgs>` and use it or transform in any way you like. The nix language is well-equipped for such things. Then it's enough to add multiple channels or extend your NIX_PATH by extra URLs.

We could go and decentralize the purged packages, i.e. only maintain a list of extra repositories that the user might include, but it would seem an overkill to me ATM.

**Comment by 7c6f434c** [comment]
>Creating and using (private) repositories depending on nixpkgs is easy and often used, IMHO. You just `import <nixpkgs>` and use it or transform in any way you like. The nix language is well-equipped for such things. Then it's enough to add multiple channels or extend your NIX_PATH by extra URLs.
>
>We could go and decentralize the purged packages, i.e. only maintain a list of extra repositories that the user might include, but it would seem an overkill to me ATM.

I think it could be a good idea to have a recommended way of structuring
a set of repos that all depend on nixpkgs and sometimes also on each
other (maybe even with circular repository dependencies).

Actually, this could later be useful if we actually decide to split 
nixpkgs…

**Comment by spacefrogg** [comment]
I know, but just by your description I see, that this approach does not follow the same declarative mechanisms, it is not used from 'inside' nix. E.g. `nix-env` does not 'see' this, I cannot search for packages from foreign repositories. It is not part of the system configuration that I save in /etc/nixos/* files but magic environment variables. Currently this is a bunch of possibilities and open ends but not consistent tooling. And there is a lack of documentation.

Second, I imagine repositories being installable just like 'normal' packages. They really should be the same thing. They should be manageable, updatable and much more important, searchable.

**Comment by joachifm** [comment]
@spacefrogg installing a repo is just `git clone`, search is `git grep`, update is `git pull`, using a specific repo is `nix-env -f /path/to/repo`. Sure the UI could be improved, but I think you're making this more complicated than is necessary. There really are no technical impediments to what we're talking about here, as far as I'm aware.

**Comment by Ericson2314** [comment]
Practically, separate repositories is a *huge* pain because either they need to kept firmly in sync, and/or abstractions and refactors won't take both into account. Just using the unfree flag, or something to indicate missing files, is *much* better IMO.

**Comment by Ericson2314** [comment]
I also question we why need to steer people towards free alternatives. IMO any software running with wine will be inherently more clunky. The experience of using such software should change more "hearts and minds" than a blanket prohibition of "redundant" proprietary software.

I do agree however that packages that rely on files that cannot be downloaded are really not true packages. Just as one might not want to accidentally install unfree software, one might not want to accidentally install packages that require extra manual setup. With enough mind tricks :), these are orthogonal concerns, and thus I think should be handled with orthogonal package metadata.

**Comment by canndrew** [comment]
What's the current policy here? I just finished packaging [Houdini](https://www.sidefx.com/), which is closed source and proprietary. It was a huge pain in the ass to get working and I don't want anyone else to have to go through that. Is it worth PR-ing the build script though?

**Comment by bjornfor** [comment]
>  It was a huge pain in the ass to get working and I don't want anyone else to have to go through that. Is it worth PR-ing the build script though?

The way you describe it, I think a PR would be nice :-)

**Comment by canndrew** [comment]
@bjornfor I guess we'll see. I've PR-ed it [here](https://github.com/NixOS/nixpkgs/pull/27326), so any debate can happen on that thread.

**Comment by CMCDragonkai** [comment]
I wonder if being a separate repository then added as a git submodule into nixpkgs repository would be a good compromise?

**Comment by vcunat** [comment]
I suppose that [overlays](https://nixos.org/nixpkgs/manual/#chap-overlays) would be the way of choice nowadays, but it would still be good to organize either some one catch-all overlay for these or some kind of "directory" with links to user overlays.
