### ISSUE TITLE
request: nvui " A modern frontend for Neovim. "

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#136229]
**Project description**
" A modern frontend for Neovim. "

homepage: https://github.com/rohit-px2/nvui
discussion: https://news.ycombinator.com/item?id=28351721

**Metadata**

* homepage URL: https://github.com/rohit-px2/nvui
* source URL: https://github.com/rohit-px2/nvui
* license: MIT
* platforms:  linux, unix?

**Comment by teto** [comment]
sadly these UIs come and go, last commit is 2 years old.
 I like neovide personally https://github.com/neovide/neovide/, alrady packaged. Shall we close this ?
