### ISSUE TITLE
Chromium headless / chromedriver (Selenium) does not work inside nix sandbox

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#136207]
**Edit:** Workaround in https://github.com/NixOS/nixpkgs/issues/136207#issuecomment-908637738.

---

Running

```sh
chromium-browser --headless --no-sandbox --disable-gpu --screenshot "https://github.com"
```

(or any other use of headless Chromium for the purpose of Selenium / `chromedriver` headless testing) *does not work in the Nix build sandbox*.

This makes it impossible to package software that does Selenium or similar tests in their test suites.

This is even though Chromium's sandbox is disabled with `--no-sandbox`. It works fine when run outside the Nix build sandbox.

This issue is to figure out how that can be fixed.

---

@NorfairKing and I have tested it only on top of NixOS 20.09 and 21.05. Minimal repro `test.nix`:

```nix
let
  pkgs = import <nixpkgs> {};
in
  pkgs.runCommand "chromium-headless-invocation" {} ''
    ${pkgs.chromium}/bin/chromium-browser --headless --no-sandbox --disable-gpu --screenshot "https://github.com"
  ''
```

(Obvious from the sandbox `https://github.com` cannot be reached, but this URL is just an arbitrary example, it fails also for localhost.)

It always errors, but the error message output is nondeterministic: sometimes the error

```
[0100/000000.301456:ERROR:zygote_linux.cc(608)] Zygote could not fork: process_type gpu-process numfds 3 child_pid -1
```

(which we believe to be the key error) is there, sometimes not:

```
$ nix-build test.nix
these derivations will be built:
  /nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv
building '/nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv'...
Fontconfig error: Cannot load default config file: No such file: (null)
[0830/171215.175304:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0830/171215.175789:WARNING:headless_browser_main_parts.cc(106)] Cannot create Pref Service with no user data dir.
/build/.attr-0: line 1:     6 Trace/breakpoint trap   (core dumped) /nix/store/73q3z4039cqip8zsrsi43inaw56fvk8f-chromium-91.0.4472.164/bin/chromium-browser --headless --no-sandbox --disable-gpu --screenshot "https://github.com"
builder for '/nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv' failed with exit code 133
error: build of '/nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv' failed
```
```
$ nix-build test.nix
these derivations will be built:
  /nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv
building '/nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv'...
Fontconfig error: Cannot load default config file: No such file: (null)
[0830/171218.212738:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0830/171218.213202:WARNING:headless_browser_main_parts.cc(106)] Cannot create Pref Service with no user data dir.
[0100/000000.301456:ERROR:zygote_linux.cc(608)] Zygote could not fork: process_type gpu-process numfds 3 child_pid -1
[0100/000000.301627:ERROR:zygote_linux.cc(640)] write: Broken pipe (32)
/build/.attr-0: line 1:     6 Trace/breakpoint trap   (core dumped) /nix/store/73q3z4039cqip8zsrsi43inaw56fvk8f-chromium-91.0.4472.164/bin/chromium-browser --headless --no-sandbox --disable-gpu --screenshot "https://github.com"
builder for '/nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv' failed with exit code 133
error: build of '/nix/store/1rzah3a68akgwcw0k9irr8nbgf9rhxyr-chromium-headless-invocation.drv' failed
```

---

CC @primeos @vcunat who helped a bit on Matrix with this issue.

**Comment by TeofilC** [comment]
I've successfully used the chrome from nixpkgs in docker containers made with dockerTools recently. I had to take the following two things into account to make it work. I'm not sure how well this will transfer to build sandboxes but it should be similar.

Chrome/chromium will crash if you don't specify `FONTCONFIG_FILE`. Even setting an an empty fontconfig avoids it. See here https://discourse.nixos.org/t/chromedriver-chromium-headless-in-a-docker-container-what-am-i-missing/5439
```
let
  pkgs = import <nixpkgs> {};
in
  pkgs.runCommand "chromium-headless-invocation" {} ''
    export FONTCONFIG_FILE=${pkgs.makeFontsConf { fontDirectories = [];}}
    ${pkgs.chromium}/bin/chromium-browser --headless --no-sandbox --disable-gpu --screenshot "https://github.com"
  ''
```



Another thing, iirc, is that recent chrome uses p11-kit via nss for ssl certs, which means you need to have ssl certs in `/etc/ssl/certs/ca-certificates.crt` . https://github.com/NixOS/nixpkgs/blob/7c38b03f742a657bf38e9579adeb608fc7cc5f1a/pkgs/development/libraries/p11-kit/default.nix#L34

Hope that helps

**Comment by NorfairKing** [comment]
Holy :hankey: ! The FONTCONFIG_FILE thing works!

**Comment by L-as** [comment]
I suppose this issue can be closed?

**Comment by NorfairKing** [comment]
@L-as It should probably be documented somewhere (but no idea where), and I should open an issue in the chromium tracker.

**Comment by L-as** [comment]
What would the Chromium bug be? That it doesn't work without fonts?

**Comment by nh2** [comment]
> What would the Chromium bug be?

That the error message is `Zygote could not fork: process_type gpu-process` without detail (not making clear that lack of fontconfig is a problem).

**Comment by TeofilC** [comment]
You do get an error about fontconfig, but chromium doesn't make it at all clear that it's fatal.
The error is:
```
Fontconfig error: Cannot load default config file: No such file: (null)
```

Full output:
```
building '/nix/store/20rf4z3mgzx686pqbd92h8iizln5iy3j-chromium-headless-invocation.drv'...
Fontconfig error: Cannot load default config file: No such file: (null)
[0831/115840.025440:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0100/000000.034084:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
/build/.attr-0: line 1:     3 Trace/breakpoint trap   /nix/store/bmxdc9h4p6sj57s34s27rhl0p9xq85l2-chromium-92.0.4515.159/bin/chromium-browser --headless --no-sandbox --disable-gpu --screenshot "https://github.com"
[0100/000000.034911:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0100/000000.035713:ERROR:zygote_linux.cc(608)] Zygote could not fork: process_type renderer numfds 4 child_pid -1
[0100/000000.035808:ERROR:zygote_linux.cc(640)] write: Broken pipe (32)
builder for '/nix/store/20rf4z3mgzx686pqbd92h8iizln5iy3j-chromium-headless-invocation.drv' failed with exit code 133
error: build of '/nix/store/20rf4z3mgzx686pqbd92h8iizln5iy3j-chromium-headless-invocation.drv' failed
```

**Comment by NorfairKing** [comment]
> You do get an error about fontconfig, but chromium doesn't make it at all clear that it's fatal.

Aha, I also missed that to be honest :p

**Comment by NorfairKing** [comment]
I opened a chromium bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1245258
