### ISSUE TITLE
Official AWS 15.09 AMIs need to be updated with user-data fix

### ISSUE THREAD

**Issue by paul-e-cooley** [NixOS/nixpkgs#13628]
## Basic info

To make sure that we are on the same page:

* Kernel: N/A
* System: (NixOS: `15.09`, AMI: ami-8fea91ea [nixos-15.09.git.87b377dM-x86_64-hvm-ebs])
* Nix version: N/A
* Nixpkgs version: N/A

## Describe your issue here
Need to upgrade the stock AWS EC2 AMI's for 15.09x with the fix to use "user-data" as described here: https://github.com/NixOS/nixpkgs/pull/7370
### Expected result
System configures itself using the user-data information and correctly rebuilds nix-os
### Actual result
user-data is ignored.
### Steps to reproduce
Launch instance.
Add template to user-data (as discussed in https://github.com/NixOS/nixpkgs/pull/7370)
Log into instance and verify user-data settings have been ignored.

**Comment by copumpkin** [comment]
Sorry :( I've been meaning to get around to backporting this to 15.09 and have just been swamped for ages now. If someone else wants to take this up, I'd really appreciate it.

**Comment by cstrahan** [comment]
@copumpkin The user-data stuff should be available in the next release, right?

**Comment by paul-e-cooley** [comment]
We are trying to switch from Amazon Linux AMI's to NixOS and move our entire company that way. But I either need new AMIs with the fix, or detailed instructions on how to make it happen myself. I've tried backporting onto the existing 15.09 AMIs, but to no avail. So if there's way to make that happen, I could get past this issues that I've been stuck on for two months.

**Comment by paul-e-cooley** [comment]
@copumpkin Is there a writeup on how I can change those AMIs myself? Or do they absolutely require a build from hydra?

**Comment by copumpkin** [comment]
I don't know of a writeup, but I definitely built them outside of hydra. I don't recall how I did it, but it had something to do with https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/ec2/create-amis.sh and https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/ec2/amazon-image.nix.

Also, there are beta 16.03 AMIs up somewhere. Someone posted them to the mailing list yesterday as I recall. Rather than backport, perhaps it's easier to just wait for 16.03 to be released at this point?

**Comment by paul-e-cooley** [comment]
If there are beta AMIs, I can definitely give those a try. I haven't seen a date for the 16.x release. Guess I should go look at the roadmap. Bazaarvoice is very interested in using NixOS to replace all of our amazon linux images and this is pretty much the last thing holding us back from streamlining our deployment strategies and moving to something we can better control.

**Comment by copumpkin** [comment]
That's very exciting! 

Looks like I was wrong about the AMIs, but they'll likely be fixed, and also included a link to how they were made: http://lists.science.uu.nl/pipermail/nix-dev/2016-March/019951.html

**Comment by paul-e-cooley** [comment]
Thanks, @copumpkin. I'll spend some time this week trying to get the images rolled. Without the user-data fix, we can't really use Nix for our deployments. So I need to get on the ball here. Cheers.

**Comment by edolstra** [comment]
I can generate new 15.09 AMIs, which are needed anyway to fix #12613. Don't know if that will fix this issue though.

It's best not to mess with 16.03 at this point.

**Comment by cstrahan** [comment]
@paul-e-cooley Looks like the 16.03 images were created: https://github.com/NixOS/nixpkgs/commit/ab2855b97556051aac466547fbe56bd66c041f50

Aside from the possibility of bugs, I think it should work for your purposes.

**Comment by paul-e-cooley** [comment]
Thank you, @cstrahan. Cheers.
