### ISSUE TITLE
Sound Switcher Indicator

### ISSUE THREAD

**Issue by ananthakumaran** [NixOS/nixpkgs#136303]
**Project description**
Sound input/output selector application for Linux.

**Metadata**

* homepage URL:  https://yktoo.com/en/software/sound-switcher-indicator/
* source URL: https://github.com/yktoo/indicator-sound-switcher
* license: gpl3+
* platforms: linux

**Comment by Alexnortung** [comment]
Closing as this has now been merged at #147413
