### ISSUE TITLE
Steam: Half-Life: Seg-fault

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#136352]
### Describe the bug!

Probably need a extraLibraries32/extraPkgs32 option to specify 32bit packages. Or I need to report this upstream.

[image](https://user-images.githubusercontent.com/364160/131621064-034db8c2-b172-4860-a8c4-f7097db33ec3.png)

### Steps To Reproduce
1. ... Install Half-Life
2. ... Use steam-runtime 
3. ... launch game.
### Notify maintainers

@jagajaga @jonringer
### Metadata
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.13.12, NixOS, 21.05.2734.74d017edb67 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(daniel): `""`
 - channels(root): `"nixos-21.05.2734.74d017edb67, nixos-unstable-21.11pre312335.8d8a28b47b7, nixpkgs-master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by YellowOnion** [comment]
I added `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/run/host/usr/lib32/:/run/host/usr/lib32/steam-runtime/lib/i386-linux-gnu/:/run/host/usr/lib32/steam-runtime/usr/lib/i386-linux-gnu/"` to `hl.sh` and solved the dll issues, but the game still crashes.

so I suspect that was a red herring...

```
assert_20210901210442_1.dmp[363387]: Uploading dump (out-of-process)
/tmp/dumps/assert_20210901210442_1.dmp
>>> Adding process 363386 for game ID 70
assert_20210901210442_1.dmp[363387]: Finished uploading minidump (out-of-process): success = yes
assert_20210901210442_1.dmp[363387]: response: Discarded=1
assert_20210901210442_1.dmp[363387]: file ''/tmp/dumps/assert_20210901210442_1.dmp'', upload yes: ''Discarded=1''
```

and I'm not sure how to keep core-dumps around to debug them locally...

**Comment by davidak** [comment]
I can't reproduce this issue. I can just install Half-Life in steam and start it.

Use `programs.steam.enable = true;` to have 32-bit libraries installed.

I'm running NixOS built from master.

**Comment by SuperSamus** [comment]
Just tried the game, it works fine.
