### ISSUE TITLE
Spotify cannot start in Wayland mode

### ISSUE THREAD

**Issue by pimeys** [NixOS/nixpkgs#136362]
### Describe the bug

When starting Spotify using the Ozone platform, on Wayland mode, it crashes to a segmentation fault.

### Steps To Reproduce
1. Start spotify on a Sway (or other Wayland) session with: `spotify --enable-features=UseOzonePlatform --ozone-platform=wayland`
2. Witness a SIGSEGV:

```
/nix/store/g6ckv8vqb8zh395zaapr19dsdilvd37m-spotify-1.1.55.498.gf9a83c60/bin/.spotify-wrapped: /nix/store/mwkin7s6cnc52c6ik9b16xkngpkzq5fn-curl-7.76.1/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/g6ckv8vqb8zh395zaapr19dsdilvd37m-spotify-1.1.55.498.gf9a83c60/bin/.spotify-wrapped)
/nix/store/p6b9qzkp4inda1cqihsh7jpw5ybjlngl-spotify-unwrapped-1.1.55.498.gf9a83c60/share/spotify/.spotify-wrapped: /nix/store/mwkin7s6cnc52c6ik9b16xkngpkzq5fn-curl-7.76.1/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/p6b9qzkp4inda1cqihsh7jpw5ybjlngl-spotify-unwrapped-1.1.55.498.gf9a83c60/share/spotify/.spotify-wrapped)
/nix/store/p6b9qzkp4inda1cqihsh7jpw5ybjlngl-spotify-unwrapped-1.1.55.498.gf9a83c60/share/spotify/.spotify-wrapped: /nix/store/mwkin7s6cnc52c6ik9b16xkngpkzq5fn-curl-7.76.1/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/p6b9qzkp4inda1cqihsh7jpw5ybjlngl-spotify-unwrapped-1.1.55.498.gf9a83c60/share/spotify/.spotify-wrapped)
/proc/self/exe: /nix/store/mwkin7s6cnc52c6ik9b16xkngpkzq5fn-curl-7.76.1/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
fish: Job 1, 'spotify --enable-features=UseOz…' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior

Spotify should start normally.

### Notify maintainers

@eelco @ftrvxmtrx @sheenobu @mudri @timokau @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre299299.3a8d7958a61"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jmc-figueira** [comment]
From what I can gather, [this is often the result as of now](https://community.spotify.com/t5/Desktop-Linux/Wayland-support/m-p/5232627/highlight/true#M20557). I get the same result. Something might need to be done by the Spotify devs to properly support Wayland, as using the Ozone Wayland platform is an experimental sort of workaround that doesn't always work out perfectly if the original developers have not added proper support.

**Comment by pimeys** [comment]
Oh. Good to know. I'll move this discussion to their side. It definitely doesn't look like it's an issue in nix.

**Comment by danielphan2003** [comment]
Spotify 1.1.67.586 seems to work with Ozone. Waiting https://github.com/NixOS/nixpkgs/pull/136374 to merge.

**Comment by danielphan2003** [comment]
When launching it with those flags, it showed 2 windows, one of which is just a black screen running on X11, and the other is the main program running on Wayland.
