### ISSUE TITLE
pkgsStatic.ocamlPackages is broken

### ISSUE THREAD

**Issue by hmenke** [NixOS/nixpkgs#136397]
### Describe the bug

Static OCaml packages are completely broken.

### Steps To Reproduce

```console
$ nix-build -A pkgsStatic.ocamlPackages.ocaml
these derivations will be built:
  /nix/store/9n5pfjqy6hvknhc1q5w21wg4x3aw50dg-ocaml-4.12.0-x86_64-unknown-linux-musl.drv
building '/nix/store/9n5pfjqy6hvknhc1q5w21wg4x3aw50dg-ocaml-4.12.0-x86_64-unknown-linux-musl.drv'...
unpacking sources
unpacking source archive /nix/store/bnnwb8fz99lhblvbb1gi7jwgb0s89vbc-ocaml-4.12.0.tar.xz
source root is ocaml-4.12.0
setting SOURCE_DATE_EPOCH to timestamp 1614174569 of file ocaml-4.12.0/yacc/wstr.c
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
fixing libtool script ./build-aux/ltmain.sh
configure flags: -prefix /nix/store/kx3am2ld1hznk3c0vmqjvina9xdnsiyy-ocaml-4.12.0-x86_64-unknown-linux-musl --no-shared-libs -host x86_64-unknown-linux-musl -target x86_64-unknown-linux-musl -cc x86_64-unknown-linux-musl-gcc -as x86_64-unknown-linux-musl-as -partialld x86_64-unknown-linux-musl-ld\ -r
configure: error: unrecognized option: `--no-shared-libs'
Try `./configure --help' for more information
builder for '/nix/store/9n5pfjqy6hvknhc1q5w21wg4x3aw50dg-ocaml-4.12.0-x86_64-unknown-linux-musl.drv' failed with exit code 1
error: build of '/nix/store/9n5pfjqy6hvknhc1q5w21wg4x3aw50dg-ocaml-4.12.0-x86_64-unknown-linux-musl.drv' failed
```

### Expected behavior

Build without error.

### Screenshots

N/A

### Additional context

Both on `nixos-21.05` and  today's`master`

### Notify maintainers

@balsoft 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-81-generic, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixpkgs-21.11pre312229.08ef0f28e3a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: pkgsStatic.ocamlPackages
# a list of nixos modules affected by the problem
module:
```

**Comment by balsoft** [comment]
Yep. Static support in ocaml was reworked and it needs to be fixed. I'm no longer particularly interested in fixing this myself, but would be willing to help someone who is.

**Comment by symphorien** [comment]
I think fixes are on staging

**Comment by hmenke** [comment]
Right, fixed in https://github.com/NixOS/nixpkgs/pull/135477/commits/061f70f8f76249394cff90019ce36593d42a1bb8
