### ISSUE TITLE
nixos-generate-config: enable networkmanager by default when wifi cards are found

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#136360]
It seems to be a common problem to forget to enable wifi on a new installation, even now that we call it out in the docs (#74839).

It would probably be a nicer experience if we enabled `networking.networkmanager.enable` default when a wifi card is detected.

**Comment by rnhmjoj** [comment]
There are many way to configure wireless networking: NetworkManager, connman, `networking.wireless` (iwd, wpa_supplicant) and probably more.
I think it would be a better idea to generate a few commented out choices with a small explanation.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/146642
