### ISSUE TITLE
Login with installed kcachegrind makes kde fail on openSUSE.

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#13635]
## Basic info
- Kernel: Linux  3.16.7-32-desktop #1 SMP PREEMPT Wed Jan 20 14:05:33 UTC 2016 (d4df98a) x86_64 x86_64 x86_64 GNU/Linux
- System: openSUSE 13.2 (Harlequin) (x86_64)
- Nix version: 1.11.1
- Nixpkgs version: "16.03pre76763.be0abb3"
## Problem

I install kcachegrind on openSUSE via `nix-env -i kcachegrind`. The program works properly, but when I log out of the system and log back in, only the error message **Could not find requested component: folderview** pops up and the kde environment is unusable.
## Possible root cause:

It seems that installing kcachegrind also places `kde4-config`, `kde4`, `kdeinit4`, .. into the `user-profile/bin` and thus leads to the non-system kde binaries being loaded on startup.

**Comment by dezgeg** [comment]
Summoning @ttuegel.

**Comment by ttuegel** [comment]
I am the KDE 5 maintainer, but kcachegrind is a KDE 4 package. There is no global KDE 4 maintainer and AFAIK there is no maintainer for kcachegrind in particular.

**Comment by knedlsepp** [comment]
@ttuegel At the moment I'm unsure if the kde packages are even meant to work with non-nixos operating systems. What is the status with KDE5 in this regard? Also: Do KDE5 applications place `kde5-config`, `kde5`, `kdeinit5`,... into `user-profile/bin` upon ad-hoc installation?

**Comment by vcunat** [comment]
Yes, that's a significant difference of our current KDE5 from KDE4. The apps should be wrapped to use the correct KDE daemons etc.
