### ISSUE TITLE
replaceDependency should be recursive

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#13648]
According to http://linux.slashdot.org/story/16/03/03/0435200/guix-gets-grafts-timely-delivery-of-security-updates, Guix uses a port of `replaceDependency`. They say it doesn't work recursively. We better check if that's the case also in Nix.

cc @shlevy @edolstra 

Fix for Guix: http://git.savannah.gnu.org/cgit/guix.git/commit/?id=c22a1324e64d6906be5e9a8e64b8716ad763434a

**Comment by shlevy** [comment]
I'm not sure what you mean by "recursively" here.

**Comment by domenkozar** [comment]
If vulnerability is in openssl, and it's reverse dependencies are replaced, is Package B that depends on A that depends on openssl also replaced?

**Comment by shlevy** [comment]
Yes.
