### ISSUE TITLE
ddcci-driver: Module ddcci not found

### ISSUE THREAD

**Issue by alex-robbins** [NixOS/nixpkgs#136425]
### Describe the bug
After installing `linuxPackages.ddcci-driver`, the `ddcci` module cannot be loaded.

### Steps To Reproduce
1. Install `linuxPackages.ddcci-driver`
2. Run `modprobe ddcci` with appropriate privileges
3. Output: 
```
modprobe: FATAL: Module ddcci not found in directory /run/current-system/kernel-modules/lib/modules/5.10.60
```

### Expected behavior
Module should be loadable.

### Additional context
After installing, I have these paths:
```
/nix/store/ni54gw7vhlz56jqzjjhpj8j79a9vp7by-ddcci-driver-5.10.60-0.3.3
├── include
│   └── linux
│       └── ddcci.h
└── lib
    └── modules
        └── 5.10.60
            └── extra
                ├── ddcci-backlight.ko
                └── ddcci.ko
```

Both of those .ko files appear to end up at `/run/current-system/sw/lib/modules/5.10.60/extra/`. This seems to be the wrong place though; my other modules seem to be in `/run/current-system/kernel-modules/lib/modules/5.10.60/kernel/`, which has modules in subdirectories, like `arch/x86/crypto/des3_ede-x86_64.ko.xz` and `drivers/vdpa/vdpa.ko.xz`. They're all xz-compressed like that.

As an aside, this package appears to be out of date; upstream released 0.4.1 a couple weeks ago.

### Notify maintainers
@bricewge 

### Metadata
```console
[arob@icarus:/run/current-system]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre311431.88226ea038e, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
kernel module packages should be put in extraModulePackages
```
boot.extraModulePackages = with config.boot.kernelPackages; [ ddcci-driver ];
```

**Comment by alex-robbins** [comment]
Oh, you're right. I had no idea that kernel module packages needed to be installed differently, so I didn't even search for that.

Thanks
