### ISSUE TITLE
Libreoffice depends on kdelibs by default.

### ISSUE THREAD

**Issue by skrzyp** [NixOS/nixpkgs#13651]
I think it's a bit too intrusive dependency for people who doesn't use KDE (I use XFCE, for example) and they don't want whole `kdelibs` (which also pulls a long tail of dependencies into my environment) just for so called "KDE integration" in Libreoffice which is actually useless here.

But it might be good to implement something like this into `libreoffice` or any other package expression which deserves it:
```py
# pseudocode, it might be too shameful to post my poorly written nix code, while I'm still learning it
if ( services.xserver.kde.enabled == true ) {
  buildInputs =+ [ kdelibs ];
  confgureFlags =+ [ "--enable-kde4" ];
} else {
  configureFlags =+ [ "--disable-kde4" ];
}
```
That can be opened as second issue (for general talk about configuration-aware dependencies) if you wish.

**Comment by 7c6f434c** [comment]
>I think it's a bit too intrusive dependency for people who doesn't use KDE (I use XFCE, for example) and they don't want whole `kdelibs` (which also pulls a long tail of dependencies into my environment) just for so called "KDE integration" in Libreoffice which is actually useless here.
>
>But it might be good to implement something like this into `libreoffice` or any other package expression which deserves it:
>```py
># pseudocode, it might be too shameful to post my poorly written nix code, while I'm still learning it
>if ( services.xserver.kde.enabled == true ) {

Well, technically you could build things from NixPkgs independently on 
how (and whether) you use NixOS. It is possible to add an option as an
extra argument, though.

On the other hand, this would mean that Hydra would need to build
2 versions of LibreOffice. @edolstra, is it a good idea?

Is there anyone actually using the KDE integration, by the way?

**Comment by Profpatsch** [comment]
That should do the trick: https://gist.github.com/Profpatsch/92342764dc3c3d667ec1

**Comment by edolstra** [comment]
IIRC, the "KDE integration" consists mainly in providing a Qt/KDE "File open" dialog, which we can probably live without. In fact, it has been known to malfunction if Libreoffice's KDE version is different from the system KDE version.

So disabling this sounds like a good idea.
