### ISSUE TITLE
unable to enable `CONFIG_DEBUG_INFO=y` `CONFIG_DEBUG_INFO_BTF=y` in the kernel

### ISSUE THREAD

**Issue by humancalico** [NixOS/nixpkgs#136515]
I'm unable to enable the `CONFIG_DEBUG_INFO=y` & `CONFIG_DEBUG_INFO_BTF=y` flags using `boot.kernelPatches.extraConfig` since they require the `zlib` and `pahole` dependencies which are not provided here https://github.com/NixOS/nixpkgs/blob/126362784184c0b341a5297c7cddffb1d2873d9d/pkgs/os-specific/linux/kernel/manual-config.nix#L314-L320 So adding a check there for these flags and adding those dependencies optionally would make it work. It would also be great if we could specify additional dependencies since I imagine there might be more flags that would require additional dependencies upon enabling them. ~~Alternatively it would be great if these flags are enabled by default since they are enabled by default in the Arch Kernel as well~~ Already done
https://github.com/archlinux/svntogit-packages/blob/c6e7f62c944fafb51594a94a2b30de5adc60a119/trunk/config#L10226
https://github.com/archlinux/svntogit-packages/blob/c6e7f62c944fafb51594a94a2b30de5adc60a119/trunk/config#L10232

**Comment by Artturin** [comment]
creating a option called `boot.kernelPatches.extraNativeBuildInputs` or something like that would probably be a good choice

**Comment by eduarrrd** [comment]
(FYI: I've filed an explicit request to enable this in #139152.)

**Comment by humancalico** [comment]
@eduarrrd I always wanted to have a discussion about what to do in case of an application which require those certain options to be enabled in the kernel? Is that something that can be done as of today?
