### ISSUE TITLE
package-request: nodePackages.tap (node-tap)

### ISSUE THREAD

**Issue by humancalico** [NixOS/nixpkgs#136573]
**Project description**
A TAP test framework for Node.js.

**Metadata**

* homepage URL: http://www.node-tap.org/
* source URL: https://github.com/tapjs/node-tap
* npm URL: https://www.npmjs.com/package/tap
* license: isc
* platforms: unix, linux, darwin, ...

I would do it myself but the https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/generate.sh script took hours to run and finally finished with an ENOENT error :(

**Comment by Pamplemousse** [comment]
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/generate.sh script took hours to run and finally finished with an ENOENT error :(

I am seeing the same error when working on #135934.
Given that `generate.sh` worked fine when I did the original PR, there might be a regression in `nodePackages`...

**Comment by Pamplemousse** [comment]
@humancalico FYI, The error seems to be gone in `master` now.

**Comment by humancalico** [comment]
Thanks @Pamplemousse. btw is there any easier way to add node packages? The `generate.sh` script takes hours to run.
