### ISSUE TITLE
zita-resampler: compilation not deterministic

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#13662]
Hi @magnetophon,
I tried rebuilding zita-resampler with nix-build --check -A zita-resampler and I got
` error: derivation '...' may not be deterministic: output '...' differs`

I tried recompiling because both guitarix and drumgizmo (depending both on zita-resampler) are crashing on one of my systems (because of this: https://bugs.archlinux.org/task/36248) (`Illegal instruction`. I fear zita resampler is doing some kind of optimization on the system is built on).
Maybe we need to add a flag that prevents this.
Thanks, Nicolò

**Comment by nico202** [comment]
I can confirm that rebuilding zita-resampler and rebuilding then fixed guitarix fixed it.
Is the `CXXFLAGS += -march=native` Makefile line the "problem"?

**Comment by joachifm** [comment]
`march=native` should be removed, for sure.

**Comment by nico202** [comment]
The same is true for zita-convolver, breaks guitarix too

**Comment by joachifm** [comment]
From grepping nixpkgs, it seems the common approach is to just strip `march=native` outright, but there's also the possibility of setting a generic march/mtune depending on the target architecture.

**Comment by abbradar** [comment]
Closed by #13941
