### ISSUE TITLE
aarch64-darwin boost159 - fail to build

### ISSUE THREAD

**Issue by damien-biasotto** [NixOS/nixpkgs#136643]
Trying to install mysql5.7 on a MacBook M1, but it fails complaining about the C compiler (clang) being too recent

### Steps to reproduce
On a machine with Apple M1 chipset, simply run: 
```
nix-env -iA nixpkgs.mysql57
```

and the output of this command will be: 

```
→ nix-env -iA nixpkgs.mysql57                                                                                                                                                                     
installing 'mysql-5.7.27'
error: assertion (with lib; (((toolset == "clang") && (! ((versionOlder  (stdenv).cc.version)  "8.0.0"))) -> (! ((versionOlder  version)  "1.69")))) failed at /nix/store/sf3lb1jxaj8gid7lyavcdn1jyp6r0bph-nixpkgs-21.11pre312229.08ef0f28e3a/nixpkgs/pkgs/development/libraries/boost/generic.nix:34:1
(use '--show-trace' to show detailed location information)
```

## Technical details

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.6.0, macOS 11.5.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(damien): `"darwin, home-manager, nixpkgs-21.11pre312229.08ef0f28e3a"`
 - nixpkgs: `/Users/damien/.nix-defexpr/channels/nixpkgs`


```

**Comment by prusnak** [comment]
Changed the description - boost builds fine (boost169), it's the older version that is affected (boost159).

**Comment by prusnak** [comment]
@damien-biasotto I don't see a quick way out of this, atm. Can you use `mysql80` or `mariadb` instead in the meanwhile?

**Comment by damien-biasotto** [comment]
@prusnak I actually went the MariaDB way, but faced other pitfalls, that's what you get for using outdated software :P
Thanks for updating the title.

Feel free to close the issue.

**Comment by mradke** [comment]
@prusnak would it be possible to pin an older version of nixpkgs? I have two devices here: one with an old, patched version of nixpkgs where everything builds fine and an up to date version where it fails to build with the provided error.

**Comment by prusnak** [comment]
> I have two devices here

Are you sure these two devices are aarch64-darwin (macOS running on Apple Silicon)?

**Comment by prusnak** [comment]
> Is there any way to check this?

For example:

```
nix-shell -p bash --run "uname -m"
```

If it prints `arm64` you are on aarch64-darwin, if it prints `x86_64` you are on x86_64-darwin.
