### ISSUE TITLE
chromium stable update (48 -> 49)

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#13665]
Chromium stable has just been released as `49.0.2623.75`, with 26 security fixes: http://googlechromereleases.blogspot.co.at/2016/03/stable-channel-update.html

Sorry to bump this, just as we got `48.0.2564.116`, but as a matter of security, we really need to track chromium stable. I just built it, and it works fine on x86_64. Currently, the updater doesn't see binary plugins, but that might be due to the previous updater from nixos-unstable.

cc @aszlig

**Comment by aszlig** [comment]
Added a Hydra jobset for building/testing the updates: https://headcounter.org/hydra/eval/311459

**Comment by aszlig** [comment]
Will get to sleep and check back in a few hours.
