### ISSUE TITLE
gnome.gnome-boxes: cannot find QEMU binary on VM creation

### ISSUE THREAD

**Issue by yl3dy** [NixOS/nixpkgs#136636]
### Describe the bug
When creating a new VM and reaching "Review and create" step buttons "Create" and "Customize" do nothing (i.e. VM cannot be created). Judging from console logs, it tries to find QEMU binary at `/usr/libexec/qemu-kvm` and predictably fails.

### Steps To Reproduce
1. Install gnome.gnome-boxes on stable
2. Click on "+" and run "Create a Virtual Machine" wizard.
3. Select any OS source.
4. On the step "Express Installation" select whatever settings.
5. On the step "Review and Create" no actual properties are displayed, buttons "Customize" and "Create" do nothing.

### Expected behavior
VM can be created, VM properties can be viewed and customized.

### Screenshots
![gnome-boxes-bug](https://user-images.githubusercontent.com/1311192/132068266-ab90a85c-5997-48d2-aad9-9e130a082993.png)

### Additional context
Console log:
```
(gnome-boxes:15785): Gtk-WARNING **: 00:38:48.566: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:15785): Gtk-WARNING **: 00:38:48.568: GtkListBox with a model will ignore sort and filter functions

(gnome-boxes:15785): Boxes-WARNING **: 00:38:54.263: review-page.vala:32: Box setup failed: Unable to get domain capabilities: Cannot check QEMU binary /usr/libexec/qemu-kvm: No such file or directory

(gnome-boxes:15785): Boxes-CRITICAL **: 00:38:54.263: boxes_assistant_review_page_populate: assertion 'machine != NULL' failed
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.61, NixOS, 21.05.2796.110a2c9ebbf (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(user): `""`
 - channels(root): `"nixos-21.05.2796.110a2c9ebbf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
Try #136789
