### ISSUE TITLE
Host OpenJDK bootstrap somewhere more official than a random dropbox

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#13663]
## Describe your issue here

If you check https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/bootstrap.nix#L11, you'll see that it's hosted on a dropbox, presumably @wkennington's. It would be nice if we could host those on tarballs.nixos.org and have a trusted process build them.
### Expected result

A tarballs.nixos.org URL
### Actual result

A dropbox.com URL
### Steps to reproduce

Read the .nix file.

**Comment by dezgeg** [comment]
Same for the ARM bootstrap tarballs.

**Comment by Profpatsch** [comment]
triage: still an issue?

**Comment by AtnNn** [comment]
Has been fixed by
> bffc8c0481b openjdk: move bootstrap tarballs to tarballs.nixos.org
