### ISSUE TITLE
package/module request: frigate

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#136706]
**Project description**
> A complete and local NVR designed for Home Assistant with AI object detection. Uses OpenCV and Tensorflow to perform realtime object detection locally for IP cameras.

**Metadata**

* homepage URL: https://blakeblackshear.github.io/frigate/
* source URL: https://github.com/blakeblackshear/frigate
* license: **MIT**
* platforms: **linux**

**Comment by colemickens** [comment]
source url should be:  https://github.com/blakeblackshear/frigate

**Comment by wmertens** [comment]
Had a quick look at the [dockerfiles](https://github.com/blakeblackshear/frigate/tree/master/docker). Here's what seems to be needed:

- It wants [nginx](https://github.com/blakeblackshear/frigate/blob/08f573aaa5ec0b9bf3d4b40388942254448b902a/docker/Dockerfile.nginx#L36-L44) somewhere (separate docker file), with support for file-aio, http_sub_module, http_ssl_module, threads, and custom modules nginx-vod-module nginx-secure-token-module nginx-rtmp-module
- It wants [ffmpeg with a bunch of codecs including nonfree](https://github.com/blakeblackshear/frigate/blob/08f573aaa5ec0b9bf3d4b40388942254448b902a/docker/Dockerfile.ffmpeg.amd64#L398-L432)
- It wants [a bunch of python modules](https://github.com/blakeblackshear/frigate/blob/08f573aaa5ec0b9bf3d4b40388942254448b902a/docker/Dockerfile.wheels#L25-L37)
- It wants [coral-edgetpu support](https://github.com/blakeblackshear/frigate/blob/08f573aaa5ec0b9bf3d4b40388942254448b902a/docker/Dockerfile.base#L27)
- It wants [vaapi support](https://github.com/blakeblackshear/frigate/blob/08f573aaa5ec0b9bf3d4b40388942254448b902a/docker/Dockerfile.amd64#L18)
- The [web frontend](https://github.com/blakeblackshear/frigate/tree/master/web) sems to be a nodejs app but there's also a separate [daemon in python](https://github.com/blakeblackshear/frigate/tree/master/frigate)

All in all, it seems non-trivial to package and support, but no doubt once packaged it would be superior to their current set of Docker overlays, possibly they'd switch.

I suppose the easier option is to just run the docker image... Not sure how easy that is in NixOS.

**Comment by colemickens** [comment]
I'm keeping an eye on https://github.com/scottlamb/moonfire-nvr personally.

**Comment by wmertens** [comment]
Hmm moonfire seems like a very long way away from the featureset of frigate. Frigate also stores camera streams unchanged, so not sure what the appeal is? The fact that it's written in Rust? It will be for sure easier to package :)

**Comment by mweinelt** [comment]
Frigate packaging happened in https://github.com/NixOS/nixpkgs/pull/214428, but it still has some issues to iron out. For example recordings of the camera stream don't work.

There is a separate ticket for libedgetpu/coral support (#188719), but we do have openvino, though there are still open TODOs with downloading the models for that.

**Comment by mweinelt** [comment]
I think frigate works reasonably well, so I'm closing this issue now.
