### ISSUE TITLE
freeciv_qt installs the GTK version

### ISSUE THREAD

**Issue by greghab** [NixOS/nixpkgs#136749]
### Describe the bug
`freeciv_qt` should provide a QT client to freeciv, which is probably named `freeciv-qt` if I had to guess.

### Steps To Reproduce
1. Install `freeciv_qt`
2. Notice only gtk client installed (see below)

### Expected behavior
A `freeciv-qt` executable.

### Screenshots
![image](https://user-images.githubusercontent.com/7407672/132115657-f816a702-0453-462a-82e7-23213751b8c8.png)
-(`freeciv-qt` does not exist)

![image](https://user-images.githubusercontent.com/7407672/132115721-55cb871b-a481-47a8-9714-e2d22e6aa830.png)
- The installed `freeciv-gtk` is indeed a gtk client.

### Notify maintainers

@SuperSandro2000  
- (You were the last person to commit, so I choose you :)  )
- (I don't believe the listed maintainer exists).
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.13, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(greghab): `"nixos-20.09-20.09.4244.47e580e291f"`
 - channels(root): `"nixos-21.11pre312407.8a2ec31e224"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
#136905
