### ISSUE TITLE
Package Request - Wails

### ISSUE THREAD

**Issue by diogox** [NixOS/nixpkgs#136707]
Please see [this reddit post](https://www.reddit.com/r/NixOS/comments/ph9cpy/help_needed_packaging_wails/) I made. It should contain all necessary information. 

I tried to package this myself, but I've run out of ideas on how to make this work. I'm pretty new to Nix.

**Comment by ianmjones** [comment]
I've just submitted PR #162947 to add Wails to nixpkgs if you fancy giving it a test. :smile:

**Comment by diogox** [comment]
Works great for me! Let's go ahead and close this ticket. Thanks for your work @ianmjones :pray:
