### ISSUE TITLE
Formula request: fheroes2

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#136781]
**fheroes2**
_Free Heroes of Might and Magic II (fheroes2) is a recreation of HoMM2 game engine._

**Metadata**

* homepage URL: https://github.com/ihhub/fheroes2
* source URL: https://github.com/ihhub/fheroes2/i
* license: gpl2
* platforms: linux, darwin

Relevant ticket: https://github.com/ihhub/fheroes2/issues/4169

**Comment by trofi** [comment]
Does existing package work for you as is?

https://github.com/NixOS/nixpkgs/blob/d7751c76153501c8b752be25e2f942d60fe24180/pkgs/games/fheroes2/default.nix

**Comment by pshirshov** [comment]
Actually it does. Thanks for the hint, I didn't know it's already available in unstable channel.
