### ISSUE TITLE
Brother 9020CDW support

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#136782]
**CUPSwrapper printer driver for Brother 9020CDW**

**Metadata**

* homepage URL: https://support.brother.com/g/b/downloadend.aspx?c=eu_ot&lang=en&prod=dcp9020cdw_eu&os=128&dlid=dlf100443_000&flang=4&type3=561
* source URL: https://support.brother.com/g/b/downloadend.aspx?c=eu_ot&lang=en&prod=dcp9020cdw_eu&os=128&dlid=dlf100443_000&flang=4&type3=561
* license: gpl2
* platforms: linux

**Comment by pshirshov** [comment]
Well, I've managed to do it on my own, but it would be very nice to have it in the tree.

Formula:

```nix
{ lib, stdenv, fetchurl, cups, dpkg, gnused, makeWrapper, ghostscript, file
, a2ps, coreutils, perl, gnugrep, which, gawk
}:

let
version = "1.1.2-1";
lprdeb = fetchurl {
url = "https://download.brother.com/welcome/dlf100441/dcp9020cdwlpr-${version}.i386.deb";
sha256 = "1z6nma489s0a0b0a8wyg38yxanz4k99dg29fyjs4jlprsvmwk56y";
};

cupsdeb = fetchurl {
url = "https://download.brother.com/welcome/dlf100443/dcp9020cdwcupswrapper-${version}.i386.deb";
sha256 = "04yqm1qv9p4hgp1p6mqq4siygl4056s6flv6kqln8mvmcr8zaq1s";
};

in
stdenv.mkDerivation {
name = "cups-brother-dcp9020cdw";

nativeBuildInputs = [ makeWrapper ];
buildInputs = [ cups ghostscript dpkg a2ps gawk ];

dontUnpack = true;

installPhase = ''
mkdir -p $out
dpkg-deb -x ${cupsdeb} $out
dpkg-deb -x ${lprdeb} $out

substituteInPlace $out/opt/brother/Printers/dcp9020cdw/lpd/filterdcp9020cdw \
--replace /opt "$out/opt" \
--replace /usr/bin/perl ${perl}/bin/perl \
--replace "BR_CFG_PATH =~" "BR_CFG_PATH = \"$out/opt/brother/Printers/dcp9020cdw/\"; #" \
--replace "BR_PRT_PATH =~" "BR_PRT_PATH = \"$out/opt/brother/Printers/dcp9020cdw/\"; #" \
--replace "PRINTER =~" "PRINTER = \"DCP9020CDW\"; #"

patchelf --set-interpreter $(cat $NIX_CC/nix-support/dynamic-linker) \
$out/opt/brother/Printers/dcp9020cdw/lpd/brdcp9020cdwfilter
#patchelf --set-interpreter $(cat $NIX_CC/nix-support/dynamic-linker) \
#  $out/opt/brother/Printers/dcp9020cdw/cupswrapper/brcupsconfpt1

for f in \
$out/opt/brother/Printers/dcp9020cdw/cupswrapper/cupswrapperdcp9020cdw \
; do
wrapProgram $f \
--prefix PATH : ${lib.makeBinPath [
coreutils ghostscript gnugrep gnused
]}
done

mkdir -p $out/lib/cups/filter/
ln -s $out/opt/brother/Printers/dcp9020cdw/lpd/filterdcp9020cdw $out/lib/cups/filter/brother_lpdwrapper_dcp9020cdw

mkdir -p $out/share/cups/model
ln -s $out/opt/brother/Printers/dcp9020cdw/cupswrapper/brother_dcp9020cdw_printer_en.ppd $out/share/cups/model/

wrapProgram $out/opt/brother/Printers/dcp9020cdw/lpd/filterdcp9020cdw \
--prefix PATH ":" ${ lib.makeBinPath [ gawk ghostscript a2ps file gnused gnugrep coreutils which ] }
'';

meta = with lib; {
homepage = "http://www.brother.com/";
description = "Brother dcp9020cdw printer driver";
license = licenses.unfree;
platforms = platforms.linux;
downloadPage = "https://support.brother.com/g/b/downloadlist.aspx?c=gb&lang=en&prod=dcp9020cdw_eu&os=128";
maintainers = [ maintainers.qknight ];
};
}
```

Put it into `/etc/nixos/packages/brother` and then 

```nix
nixpkgs.config.packageOverrides = pkgs: rec {
brother9020cdw = pkgs.callPackage_i686 /etc/nixos/packages/brother { };
};
```

then  add it into `environment.systemPackages`

**Comment by Artturin** [comment]
Make a PR?

**Comment by pshirshov** [comment]
Have no idea how/where to do it properly

**Comment by pshirshov** [comment]
Not sure if I did it right but whatever.

**Comment by pshirshov** [comment]
I'm not sure what is wrong with you, though I don't think you have use such rude language.

This is my first time when I try to deliver a patch and developers speak with me using imperative-command language.

Not sure why you want to be hostile to your users/contributors but good luck with that.

**Comment by Artturin** [comment]
> I'm not sure what is wrong with you, though I don't think you have use such rude language.
> 
> This is my first time when I try to deliver a patch and developers speak with me using imperative-command language.
> 
> Not sure why you want to be hostile to your users/contributors but good luck with that.

I wasnt being hostile, I just suggested that you could make a pr since youve already packaged it?

**Comment by pshirshov** [comment]
I'm talking about your imperative language in the comment to my PR. That doesn't sound nice, sorry.

**Comment by Artturin** [comment]
I don't understand I just told you stuff you needed to know

**Comment by Artturin** [comment]
Of cours feedback is needed to improve your PR and get it merged

**Comment by Artturin** [comment]
I didn't mean to be offensive sorry

**Comment by pshirshov** [comment]
https://github.com/NixOS/nixpkgs/pull/136897

**Comment by pshirshov** [comment]
Okay, will try.
