### ISSUE TITLE
add rust-gdbgui to rustup

### ISSUE THREAD

**Issue by willbush** [NixOS/nixpkgs#136732]
Please add rust-gdbgui to `binlinks` in the post install script of rustup.

rust-gdbgui was recently added to the list of proxied tools in rustup.

https://github.com/rust-lang/rustup/pull/2811

However, the change that's now present in latest master of rustup is not yet part of a tagged release. I'm assuming that updates to a package are only done to tagged releases? I'm also not sure how disruptive updating the `cargoSha256` is.

So, I think this issue cannot be resolved until the next release of rustup.

###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

`nix search` name: rustup
current version: 1.24.2
desired version: > 1.24.3 (not yet released)

###### Notify maintainers

maintainers: @Mic92

###### Note for maintainers

Please tag this issue in your PR.

**Comment by Mic92** [comment]
Can you make a pull request?

**Comment by willbush** [comment]
Sure. I'll make a PR on the next rustup release.

**Comment by jiegec** [comment]
See pr #181686
