### ISSUE TITLE
Remove Pillow 6

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#136817]
## Issue description

It has many known vulnerabilities and the 6 branch seem not to be supported.

https://github.com/python-pillow/Pillow/milestones
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pillow/6.nix

Causing issues like https://github.com/NixOS/nixpkgs/issues/124590.

Reference: https://github.com/NixOS/nixpkgs/pull/125352

We should remove it when all packages that need it are updated.

cc maintainers @goibhniu @prikhi @SuperSandro2000

**Comment by lucasew** [comment]
What about mark it as broken or insecure?

Like OpenSSL 1.2 already is.

**Comment by davidak** [comment]
@lucasew it is

https://github.com/NixOS/nixpkgs/commit/ce097085f779e7f7c0c6743409eebd9934bab8c6#diff-913b6cad1e8f37f91adfa7c0ea8c45602f3aad2ee60dc4c44dc426fa6a01b353
