### ISSUE TITLE
CMakeFiles/freeglut.dir/build.make:62: recipe for target 'CMakeFiles/freeglut.dir/src/fg_callbacks.c.o' failed

### ISSUE THREAD

**Issue by daljeetv** [NixOS/nixpkgs#13684]
## Basic info

To make sure that we are on the same page:
- Kernel: Darwin Daljeets-MacBook-Air.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
- Nix version: nix-env (Nix) 1.11.2
## Describe your issue here

I'm unsure, but possible issue/solution: 
http://stackoverflow.com/questions/23031740/how-to-use-opengl-with-gcc-on-mac
### Expected result

Everything should install correctly.
### Actual result

Scanning dependencies of target freeglut
[  1%] Building C object CMakeFiles/freeglut.dir/src/fg_callbacks.c.o
In file included from /private/var/folders/22/w85z8wpd4fq5tl_35by02zj40000gn/T/nix-build-freeglut-3.0.0.drv-0/freeglut-3.0.0/src/fg_callbacks.c:28:
In file included from /private/var/folders/22/w85z8wpd4fq5tl_35by02zj40000gn/T/nix-build-freeglut-3.0.0.drv-0/freeglut-3.0.0/include/GL/freeglut.h:17:
/private/var/folders/22/w85z8wpd4fq5tl_35by02zj40000gn/T/nix-build-freeglut-3.0.0.drv-0/freeglut-3.0.0/include/GL/freeglut_std.h:140:13: fatal error: 'OpenGL/gl.h' file not found
include <OpenGL/gl.h>
1 error generated.
CMakeFiles/freeglut.dir/build.make:62: recipe for target 'CMakeFiles/freeglut.dir/src/fg_callbacks.c.o' failed
make[2]: **\* [CMakeFiles/freeglut.dir/src/fg_callbacks.c.o] Error 1
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/freeglut.dir/all' failed
make[1]: **\* [CMakeFiles/freeglut.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
builder for ‘/nix/store/2bxx9a74xzgivgbwpbc36k1qg1j2xqyd-freeglut-3.0.0.drv’ failed with exit code 2
building path(s) ‘/nix/store/j8z02zgwbsp8acnrny4lbn6dfgnzrhv2-pyrr-0.7.2.tar.gz’
cannot build derivation ‘/nix/store/g2q5cs62ccjawxy8gsdny3511f0dasmx-python2.7-pyopengl-3.1.0.drv’: 1 dependencies couldn't be built
killing process 22231
error: build of ‘/nix/store/g2q5cs62ccjawxy8gsdny3511f0dasmx-python2.7-pyopengl-3.1.0.drv’ failed
### Steps to reproduce

git clone https://github.com/mkovacs/sphaira
cd sphaira
nix-shell .

**Comment by daljeetv** [comment]
### You can also recreate by
::
nix-shell -p pythonPackages.pyopengl

**Comment by matthewbauer** [comment]
freeglut is now in Hydra, so I think this issue can be closed.

**Comment by prusnak** [comment]
Closing as per comment above.
