### ISSUE TITLE
obsidian: blank window

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#136992]
### Describe the bug

obsidian starts but the window is blank.

It was working days ago.

### Steps To Reproduce
1. start obsidian

### Screenshots

![image](https://user-images.githubusercontent.com/24027/132367711-3712c1e3-b177-4056-8988-5c827be12858.png)

### Additional context

```
❯ obsidian
2021-09-07 15:07:55 Loading updated app package /home/bbigras/.config/obsidian/obsidian-0.12.15.asar
2021-09-07 15:07:55 Checking for update using Github
(node:6399) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
2021-09-07 15:07:55 Success.
2021-09-07 15:07:55 Latest version is 0.12.15
2021-09-07 15:07:55 App is up to date.
```

maybe related to recent https://github.com/NixOS/nixpkgs/pull/136531 or https://github.com/NixOS/nixpkgs/pull/136051

### Notify maintainers

@conradmearns @zaninime

cc @travisbhartwell @manveru @prusnak @lovesegfault  @TredwellGit

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.1-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre299825.d8079260a30"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by prusnak** [comment]
@bbigras can you try changing `${electron}` to `${electron_13}` here:

https://github.com/NixOS/nixpkgs/blob/bc06c93905f60a82d6ebbb78f78cf289257860cc/pkgs/applications/misc/obsidian/default.nix#L47

and also on line 1 of the same file?

If that does not help, can you try electron_12, etc? 

We need to pin the correct version number because now we are always on the latest electron, which is not good for binary builds like this one.

**Comment by bbigras** [comment]
@prusnak `electron_13` works. PR sent.
