### ISSUE TITLE
Q: How can i write an output of a command to file using nixlang?

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#136972]
I want to create a file with the content from stdout of command `openssl rand -hex 64` to be provided to `services.discourse.secretKeyBaseFile`

How can i do that in a reproducible way assuming that the current way is do a build with `services.discourse.secretKeyBaseFile = "/run/keys/secret_key_base"` and after build do manually `openssl rand -hex 64 > /run/keys/secret_key_base && chown discourse:discourse /run/keys/secret_key_base && chmod 440 /run/keys/secret_key_base` ?

**Comment by bjornfor** [comment]
If you use nixlang I think the secret will end up in the nix store (not so secret). I would write a systemd service for your openssl commands that creates the /run/keys/secret_key_base file at runtime, and makes the discourse service wait for that file.

**Comment by Kreyren** [comment]
@bjornfor I rather want to handle it through nixlang where the theory is:

```nix
services.discourse.secretKeyBaseFile = pkgs.writeFile "/run/keys/secret_key_base" ''
	${generateTheString}
'';
```

Where i don't know how could i do the `${generateTheString}`

**Comment by Kreyren** [comment]
Probably something like reading `/dev/random` ?

```console
[kreyren@leonid:~]$ head -n1 /dev/random
:#0��Ǟ0�PXn�����t�����gn�p(o�V�+�>g�<̻�Jсo�ԟ�ڀ4 {�I��_f���<�{
```

**Comment by legendofmiracles** [comment]
`runCommand` and friends can write data to the nix store, from a shell script. See here: https://nixos.org/manual/nixpkgs/stable/#trivial-builder-runCommand

**Comment by Kreyren** [comment]
@legendofmiracles I want that outside of nix store, because it's a secret.. Which i assume is not possible?

**Comment by roberth** [comment]
You could use `nix-instantiate --eval --strict` to get Nix values without necessarily writing them to the store. It's what NixOps uses for its keys (secrets) feature. It even has a resources to generate an ssh key and store it in the NixOps state, or do the same for an arbitrary command on the deployer's machine. Sadly, we don't have generated docs for NixOps 2 at the moment, but you can find the option descriptions for these resources here: https://github.com/NixOS/nixops/tree/master/nix
