### ISSUE TITLE
Add a way to get the main program of a derivation.

### ISSUE THREAD

**Issue by tomprince** [NixOS/nixpkgs#137032]
There are a couple of different ways this is determined:
- `nix run` use `meta.mainProgram` or splits the derivation name
- [`pkgs.testVersion`](https://github.com/NixOS/nixpkgs/blob/a83b9d3a5896d166d8372017f194880ffcd42fd1/pkgs/build-support/trivial-builders.nix#L613) uses `package.meta.mainProgram or package.pname or package.name`

It would be nice if there were a helper to get this value in a consistent way, and perhaps also a way to directly get an absolute path to it.

**Comment by roberth** [comment]
The absolute path can be as simple as `pkg.mainProgram` after https://github.com/NixOS/nixpkgs/pull/119942 or similar.
