### ISSUE TITLE
mkvtoolnix: GUI is not being built

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#13714]
I'm trying (unsuccesfully) to build mkvtoolnix-gui. `legacyGUI` option should be on by default but seems to do nothing (there is no GUI binary in the build output) and if I set `withGUI` to true nix gives this error:

    error: cannot coerce a set to a string, at nixpkgs/pkgs/applications/video/mkvtoolnix/default.nix:20:3

Also in the `./configure` log I noticed this:

    configure: WARNING: unrecognized options: --with-mkvtoolnix-gui, --enable-gui, --enable-wxwidgets

So something is definitely not right. Is anybody using this package? @Fuuzetsu?

**Comment by codyopel** [comment]
wxwidgets was dropped completely as of 8.2.0.

qt5 packaging has changed since this build was rewritten, it should now use `qt5.qtbase` (not `qt5`, hence it casting a set to a string )

For reference:
https://github.com/triton/triton/blob/master/pkgs/all-pkgs/mkvtoolnix/default.nix

**Comment by rnhmjoj** [comment]
Thank you.
