### ISSUE TITLE
oraclejdk8 patchelf reports errors

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nixpkgs#137135]
### Describe the bug
I need oraclejdk8 (unfortunately). I've gone through the process of installing it but there are a lot of patchelf errors.

### Steps To Reproduce
1. Get the jdk8 binary
2. nix-shell -p oraclejdk8

### Expected behavior
Should not see any errors. libpjp2.so should be found.

### Additional context

Log:

> this derivation will be built:
  /nix/store/bj8x8h4i7cjc4fz7ms65c2z6dpks432n-oraclejdk-8u281.drv
building '/nix/store/bj8x8h4i7cjc4fz7ms65c2z6dpks432n-oraclejdk-8u281.drv'...
unpacking sources
unpacking source archive /nix/store/f0ag49f143rw8h6yb9jgw6q95s8vgl2x-jdk-8u281-linux-x64.tar.gz
source root is jdk1.8.0_281
setting SOURCE_DATE_EPOCH to timestamp 1607518067 of file jdk1.8.0_281/jmc.txt
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
moving /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/man to /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/share/man
shrinking RPATHs of ELF executables and libraries in /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jdeps
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jrunscript
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/java
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/xjc
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/javah
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jmap
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/servertool
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/schemagen
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/serialver
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/rmid
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jhat
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jjs
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jcmd
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/orbd
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/rmiregistry
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/extcheck
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/idlj
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jstatd
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/javadoc
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jarsigner
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jstat
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/appletviewer
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/wsimport
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/keytool
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/native2ascii
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jar
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jdb
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jstack
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/javap
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/unpack200
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/policytool
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/rmic
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/javac
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/wsgen
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/pack200
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jconsole
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jsadebugd
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jps
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/tnameserv
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jinfo
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/lib/amd64/libjawt.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/lib/amd64/jli/libjli.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/lib/jexec
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/lib/visualvm/profiler/lib/deployed/jdk16/linux-amd64/libprofilerinterface.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/lib/visualvm/profiler/lib/deployed/jdk15/linux-amd64/libprofilerinterface.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/java
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/servertool
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/rmid
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/jjs
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/orbd
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/rmiregistry
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/keytool
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/unpack200
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/policytool
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/pack200
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/tnameserv
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libawt_headless.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjava.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libsctp.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-55.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libsaproc.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjdwp.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libzip.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjsoundalsa.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/liblcms.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libunpack.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libnet.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libprism_sw.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libresource.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libhprof.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libj2gss.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjavafx_font_pango.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libverify.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjawt.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-57.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libdt_socket.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-56.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libprism_es2.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libmanagement.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libdeploy.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libinstrument.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libbci.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjsound.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjsig.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libglib-lite.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libfontmanager.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/jli/libjli.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libprism_common.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-53.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libj2pkcs11.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libnio.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libnpt.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-ffmpeg-57.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjfxwebkit.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-ffmpeg-58.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libawt_xawt.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjavafx_font.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libattach.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjfr.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjavafx_iio.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libdcpr.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libsplashscreen.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjfxmedia.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libfxplugins.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libgstreamer-lite.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjavafx_font_freetype.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libmlib_image.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/server/libjvm.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjava_crw_demo.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libsunec.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-ffmpeg-56.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjsdt.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libavplugin-54.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjaas_unix.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libglassgtk3.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libglassgtk2.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libawt.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libj2pcsc.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libglass.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libdecora_sse.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libt2k.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libjpeg.so
shrinking /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/jexec
the symlink /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/plugins/libnpjp2.so is broken, it points to /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/libnpjp2.so (which is missing)
rewriting symlink /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/plugins/libnpjp2.so to be relative to /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281
gzipping man pages under /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/share/man/
patching script interpreter paths in /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/javapackager: interpreter directive changed from "#!/bin/sh" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/sh"
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jvisualvm: interpreter directive changed from "#!/bin/sh" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/sh"
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/javafxpackager: interpreter directive changed from "#!/bin/sh" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/sh"
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/java-rmi.cgi: interpreter directive changed from "#!/bin/sh" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/sh"
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/bin/jcontrol: interpreter directive changed from "#!/bin/bash" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/bash"
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/lib/visualvm/platform/lib/nbexec: interpreter directive changed from "#!/bin/sh" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/sh"
/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/bin/jcontrol: interpreter directive changed from "#!/bin/bash" to "/nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/bash"
checking for references to /build/ in /nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281...
patchelf: not an ELF executable
patchelf: not an ELF executable
patchelf: not an ELF executable
patchelf: not an ELF executable
patchelf: not an ELF executable
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: not an ELF executable
patchelf: not an ELF executable
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: cannot find section '.interp'. The input file is most likely statically linked
patchelf: getting info about '/nix/store/8ybgj8417aj7yz4bc77j00khfs0myyxd-oraclejdk-8u281/jre/lib/amd64/plugins/libnpjp2.so': No such file or directory

### Notify maintainers

@AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre313120.23d5823337f"`
 - channels(jkolb): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by tomodachi94** [comment]
All of the Oracle JDKs were removed in #353043.
