### ISSUE TITLE
Steam: embeddedd browser not working with latest update

### ISSUE THREAD

**Issue by tgharib** [NixOS/nixpkgs#137279]
### Describe the bug
Steam's in-app web browser no longer works with the latest [Steam update (September 10)](https://steamcommunity.com/games/593110/announcements/detail/2941402621044012222).

### Steps To Reproduce
1. Enable steam using the option `programs.steam.enable = true;`
2. Launch steam

Note: you might have to manually force Steam to check for updates, to get the latest build.

Potentially related issue: https://github.com/ValveSoftware/steam-for-linux/issues/7935

### Expected behavior
To be able to use the in-app web browser.

### Screenshots
https://i.imgur.com/nOXpR21.png

### Notify maintainers
@jagajaga @jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre308541.6fc5211eddd"`
 - channels(owner): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by danyeet** [comment]
Can replicate it, this issue was present before with the beta. I thought it was going to be fixed (thought this was a bug on steam end, there is even a nixos mention in the changelog though it's for something else).

**Comment by benneti** [comment]
just wanted to also link this bug report here as I think it is the same problem: https://github.com/ValveSoftware/steam-runtime/issues/462

**Comment by smcv** [comment]
Yes, this is the same as ValveSoftware/steam-runtime#462. https://github.com/ValveSoftware/steam-runtime/issues/462#issuecomment-916928320 has some suggestions for things the NixOS packaging can do to resolve this.

As with the SteamLinuxRuntime compatibility saga, we are not deliberately breaking NixOS, but NixOS is so unusual that changes made to fix other distributions are relatively likely to break it.

**Comment by YellowOnion** [comment]
```nix
(steam.override {
      extraPkgs = pkgs: with pkgs; [ pango harfbuzz libthai ];
    })
```
Put this in your environment to work around the issue.

**Comment by uniquepointer** [comment]
@YellowOnion thank you so much, was about to ask for a workaround!

**Comment by smcv** [comment]
If a workaround is as simple as that, then that hopefully points the maintainers of the NixOS package for Steam towards a real solution.

**Comment by pinkisemils** [comment]
> ```nix
> (steam.override {
>       extraPkgs = pkgs: with pkgs; [ pango harfbuzz libthai ];
>     })
> ```
> 
> Put this in your environment to work around the issue.

This doesn't fix it for me with or without the Steam client beta. I'm on unstable/gnome/wayland.

**Comment by noneucat** [comment]
> This doesn't fix it for me with or without the Steam client beta. I'm on unstable/gnome/wayland.

This fixes it for me; are you using `programs.steam.enable` ? You'll have to override the package with `nixpkgs.config.packageOverrides` I think.

**Comment by pinkisemils** [comment]
Oh, it was just a snafoo on my end.  The fix does just work!

**Comment by jonringer** [comment]
likely what is going on is that it's picking up the nixpkgs's libpango, which is linked against libthai and harfbuzz.
