### ISSUE TITLE
dbt CLI (data build tool)

### ISSUE THREAD

**Issue by dasistkeintest** [NixOS/nixpkgs#137292]
**Project description**
Open-source CLI core of widely-used data transformation tool, written in Python.

**Metadata**

* homepage URL: [getdbt.com/docs]()
* source URL: [github.com/dbt-labs/dbt]()
* license: Apache 2.0
* platforms: unix

**Comment by mausch** [comment]
To everyone subscribed here:

I've packaged dbt-core in https://github.com/NixOS/nixpkgs/pull/220305 .
I want to evaluate it for a new project but I'm new to dbt so it would be great if someone could help with testing and improving that PR.
For example I think the built-in Postgres plugin is currently missing. Not sure if anything else is missing.
Tests currently cannot be run (see comment in the nix file).
