### ISSUE TITLE
Podman: Add support for rootless sockets

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#137212]
Currently the podman package doesn't install a user podman systemd socket. Adding support for user this would make it possible to use docker-compose with rootless podman containers

**Comment by pio2398** [comment]
Still important

**Comment by chesedo** [comment]
I'm willing to work on this, but will just need some guidance. It seems I'll need to:
-  Add a `rootlessSocket.enable` [option](https://github.com/NixOS/nixpkgs/blob/e42f06f93fa5ffda66250d2a3a2d993ba78b32c2/nixos/modules/virtualisation/podman/default.nix#L54)
- Conditionally create a [systemd](https://github.com/NixOS/nixpkgs/blob/e42f06f93fa5ffda66250d2a3a2d993ba78b32c2/nixos/modules/virtualisation/podman/default.nix#L149-L154) which will need run as the user 

Not sure if I missed anything?

It is possible to manually create a user socket by running the following command as the user:
```
podman system service --time=0 unix:///tmp/podman.sock
```

**Comment by koalp** [comment]
> I'm willing to work on this, but will just need some guidance. It seems I'll need to:
> 
>     * Add a `rootlessSocket.enable` [option](https://github.com/NixOS/nixpkgs/blob/e42f06f93fa5ffda66250d2a3a2d993ba78b32c2/nixos/modules/virtualisation/podman/default.nix#L54)
> 
>     * Conditionally create a [systemd](https://github.com/NixOS/nixpkgs/blob/e42f06f93fa5ffda66250d2a3a2d993ba78b32c2/nixos/modules/virtualisation/podman/default.nix#L149-L154) which will need run as the user

It seems that the user service already exists but don’t uses the podman executable path.

> 
> Not sure if I missed anything?
> 
> It is possible to manually create a user socket by running the following command as the user:
> 
> ```
> podman system service --time=0 unix:///tmp/podman.sock
> ```

The `podman.socket` user target creates a socket in `$XDG_RUNTIME_DIR/podman/podman.socket`. (`systemctl --user cat podman.socket`)

--- 

I got it to work by adding the following in my `configuration.nix`:

```
  systemd.user.services.podman.serviceConfig = {
    ExecStart = [
      ""
      "${config.virtualisation.podman.package}/bin/podman $LOGING system service"
    ];
  };
  systemd.user.sockets.podman = {
      enable= true;
      wantedBy = ["sockets.target"];
  };
```

I’m not using nixos for very long. Therefore, I don’t know if this is the best way to activate it and if all options are needed.

**Comment by zowoq** [comment]
I've opened a PR for this: https://github.com/NixOS/nixpkgs/pull/176809
