### ISSUE TITLE
brave: gpu rasterization and hardware acceleration broken

### ISSUE THREAD

**Issue by danyeet** [NixOS/nixpkgs#137232]
### Describe the bug
GPU rasterization and all other features concerning the hardware accelerated part of the browser are disabled and unable to be turned on.The brave://gpu page shows that no graphics processor is detected. This behaviour started with 1.29 version
### Steps To Reproduce
1. Install the latest version of brave
2. Turn on the required flags (though on the other browsers this was not needed, except for video acceleration)
3. Check the gpu report in chrome://gpu

### Expected behavior
GPU rasterization and hardware acceleration should work as expected.

### Screenshots
![image](https://user-images.githubusercontent.com/20648137/132766486-ba77a708-2f13-4e8f-bba5-96c7c55269f8.png)

### Additional context
This issue only appears on brave. I tested chromium and vivaldi, both work as expected
### Notify maintainers

@uskudnik  @rht  @JeffLabonte  @nasirhm 
### Metadata
Please run nix-shell -p nix-info --run "nix-info -m" and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.1-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre313466.bc06c93905f, nixos-hardware"`
 - channels(danyeet): `"home-manager, nixos-21.11pre311431.88226ea038e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by samuelgrf** [comment]
Did you also pass `--ignore-gpu-blocklist`?

**Comment by danyeet** [comment]
Yes, it doesn't fix the issue.

**Comment by mixedCase** [comment]
I can reproduce this. Using Sway with Brave running on XWayland, amdgpu, kernel 5.10.62.

For whatever reason, I don't even get to see anything but a black screen when launching the browser by name or when restarting it from the button offered when changing a flag, but opening a link with `xdg-open http://google.com` allows me to start the browser in the same status as OP.

**Comment by danyeet** [comment]
I also had the black screen issue, but removing my profile fixed it. Though that is a workaround, and it doesn't fix the main issue.

**Comment by danyeet** [comment]
So now with the latest update on 1.30.86 gpu rasterization works just fine, but at least on my end video acceleration is still broken. I also tested chromium, it worked fine.

**Comment by danyeet** [comment]
> I can reproduce this. Using Sway with Brave running on XWayland, amdgpu, kernel 5.10.62.
> 
> For whatever reason, I don't even get to see anything but a black screen when launching the browser by name or when restarting it from the button offered when changing a flag, but opening a link with `xdg-open http://google.com` allows me to start the browser in the same status as OP.

Could you try running brave in native wayland and tell if you have gpu acceleration?
I am running it now native and everything is software rendered, unlike chromium

**Comment by mixedCase** [comment]
> Could you try running brave in native wayland and tell if you have gpu acceleration? I am running it now native and everything is software rendered, unlike chromium

Same as you, I do not have gpu acceleration when selecting Wayland as my Ozone platform.

The original comment I posted is no longer valid however, I do not get a black screen anymore, but I am running kernel 5.17. I don't remember if that was a kernel (read: amdgpu) or a browser thing.

**Comment by danyeet** [comment]
That seems more like a browser issue, I suspect it might be searching for some libraries
```
[225968:225968:0426/221402.534954:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory

```

**Comment by jaen** [comment]
I know this is old, but see if this will help: https://github.com/NixOS/nixpkgs/pull/170655. At least for me everything seems to work correctly. I have `brave` overridden thus (for cmdline args):
```nix
brave.override {
  commandLineArgs = ''
    --use-gl=desktop \
    --ignore-gpu-blocklist \
    --enable-gpu-rasterization \
    --enable-zero-copy
  '';
}
```

**Comment by alexjp** [comment]
I have been able to use gpu accel on brave, doing some changes to pkgs/applications/networking/browsers/brave/default.nix:

```
diff --git a/pkgs/applications/networking/browsers/brave/default.nix b/pkgs/applications/networking/browsers/brave/default.nix
index ed9f16066b0..7988d5b5957 100644
--- a/pkgs/applications/networking/browsers/brave/default.nix
+++ b/pkgs/applications/networking/browsers/brave/default.nix
@@ -17,6 +17,7 @@
 , gtk3
 , libuuid
 , libdrm
+, libGL
 , libX11
 , libXcomposite
 , libXcursor
@@ -66,7 +67,7 @@ let
 
   deps = [
     alsa-lib at-spi2-atk at-spi2-core atk cairo cups dbus expat
-    fontconfig freetype gdk-pixbuf glib gtk3 libdrm libX11
+    fontconfig freetype gdk-pixbuf glib gtk3 libdrm libGL libX11
     libxkbcommon libXScrnSaver libXcomposite libXcursor libXdamage
     libXext libXfixes libXi libXrandr libXrender libxshmfence
     libXtst libuuid mesa nspr nss pango pipewire udev wayland
```


this seems to fix it for the latest version of brave/default.nix.

**Comment by jaen** [comment]
@alexjp interesting, for me it works without that `libGL` – I've just ran some shaders from shadertoy and they are accelerated by the GPU. Is the difference in your case the `Direct Rendering Display Compositor` in `about://gpu` being enabled? Because I've just noticed it's `Disabled` for me, I must've mistaken it for raw draw ~~"

**Comment by alexjp** [comment]
I am using wayland, I think on x11 I also get gpu accel. But on wayland, it only works with that change.

On wayland, this is what happens with that change:

with lib change:

![with_libGL](https://user-images.githubusercontent.com/85806/166686936-c7c85524-0a07-4ca6-bb5a-bf01d65c8d6f.png)


without it (as it is on nixos-unstable ):

![without_libGL](https://user-images.githubusercontent.com/85806/166687004-7e607023-b648-492d-87da-8140b41d12dd.png)

**Comment by jaen** [comment]
@alexjp can you check if this also fixes your issue? Seems a bit more correct than just passing `libGL` only

```
@@ -99,7 +101,7 @@ stdenv.mkDerivation rec {
   dontPatchELF = true;
   doInstallCheck = true;

-  nativeBuildInputs = [ dpkg wrapGAppsHook ];
+  nativeBuildInputs = [ dpkg wrapGAppsHook addOpenGLRunpath  ];

   buildInputs = [
     # needed for GSETTINGS_SCHEMAS_PATH
@@ -128,9 +130,11 @@ stdenv.mkDerivation rec {
       ln -sf $BINARYWRAPPER $out/bin/brave

       for exe in $out/opt/brave.com/brave/{brave,chrome_crashpad_handler}; do
-      patchelf \
-          --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
-          --set-rpath "${rpath}" $exe
+          patchelf \
+              --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
+              --set-rpath "${rpath}" $exe
+
+          addOpenGLRunpath $exe
       done

       # Fix paths
```

**Comment by danyeet** [comment]
> I know this is old, but see if this will help: https://github.com/NixOS/nixpkgs/pull/170655. At least for me everything seems to work correctly. I have `brave` overridden thus (for cmdline args):
> ```nix
> brave.override {
>   commandLineArgs = ''
>     --use-gl=desktop \
>     --ignore-gpu-blocklist \
>     --enable-gpu-rasterization \
>     --enable-zero-copy
>   '';
> }
> ```
> It _might_ also help for Vulkan (just override `vulkanSupport` to `true`), but it seems to break video acceleration then (maybe there's another magic incantation to fix it, but didn't yet find it).

The original issue might be a bit dated, but the issue is now still prevalent :).

**Comment by jaen** [comment]
@danyeet well, if you're on X, then you should be able to try the latest `nixos-unstable` with overrides like above to get it to work. At least it works for me with this fix. If you're on Wayland, then a bit more work is needed.

**Comment by danyeet** [comment]
I do use wayland yes, thats why I commented again a few days ago.

**Comment by alexjp** [comment]
@jaen 

sorry.... i will test in a minute !! didn't had time yet, but will do right away!

**Comment by alexjp** [comment]
@jaen 

I tested your diff from here directly and the new brave-1.38.111 branch. both did not work :(


as more info, in the terminal, brave also complains:
```
[10445:10445:0504/185538.960769:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[10445:10445:0504/185538.961822:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
[10406:10406:0504/185538.974423:ERROR:profile_attributes_storage.cc(848)] Failed to PNG encode the image.
[10406:10406:0504/185538.974450:ERROR:profile_attributes_storage.cc(848)] Failed to PNG encode the image.
[10406:10406:0504/185538.974459:ERROR:profile_attributes_storage.cc(848)] Failed to PNG encode the image.
[10462:10462:0504/185538.979591:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[10462:10462:0504/185538.980913:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
[10520:10520:0504/185539.038538:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[10520:10520:0504/185539.039535:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
[10528:10528:0504/185539.051423:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[10528:10528:0504/185539.052313:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
[10536:10536:0504/185539.056579:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
[10536:10536:0504/185539.057413:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization
```

**Comment by jaen** [comment]
Okay, I guess adding `libGL` it is. I don't quite understand what is different about it and since I don't really use Wayland at this time, I can't really check what's the problem here. I'll try to look at it later, for now it's important to have it fixed for the release.

@alexjp sorry to pester you again, I made a PR (https://github.com/NixOS/nixpkgs/pull/171561) out of it, can you double check the fix on the branch works the same for you?

**Comment by jaen** [comment]
Made a PR with just the `libGL` change instead, as there's apparently already a PR to update to 111: https://github.com/NixOS/nixpkgs/pull/171568

**Comment by alexjp** [comment]
@jaen So sorry to keep you waiting!

Just tested the PR 171568, and its good!

**Comment by jaen** [comment]
@alexjp no problem, I use X anyway so I'm not kept waiting, but it's good to know this will fix issues for Wayland people to. Thanks for verifying the fix!

**Comment by jaen** [comment]
@alexjp  @danyeet it seems that this is now available in the unstable channel – http://nixpk.gs/pr-tracker.html?pr=171568 (alongside the 1.38.111 bump). Feel free to verify that your issue is still fixed there and we should be able to close this issue as fixed after close to a year ;' )

**Comment by danyeet** [comment]
Yes, I think it's now fine on wayland (video acceleration doesn't seem to work but that seems like a chromium wayland issue and not nixos specific one).
