### ISSUE TITLE
Compiz is broken

### ISSUE THREAD

**Issue by xtendo-org** [NixOS/nixpkgs#13735]
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux system 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux`
- System: `16.03pre77568.40c586b (Emu)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `16.09pre78286.0bf8a1a`
## Describe your issue here

The commit 7333c01dbab997ba1fbedcf48e394e597383e64d might have broken Compiz. Apparently the intention was to roll multiple packages into one.
### Expected result
- Adding `services.xserver.windowManager.compiz.enable = true;` then running `nixos-rebuild switch` does not cause any error.
- Running `ccsm` launches the compizconfig-settings-manager.
### Actual result

Adding `services.xserver.windowManager.compiz.enable = true;` causes error:

```
error: attribute ‘compiz_ccsm’ missing, at /nix/store/m1lk9ah7vah5rdya0v5zxh0x65rnvfp4-nixos-16.09pre78286.0bf8a1a/nixos/nixpkgs/nixos/modules/services/x11/window-managers/compiz.nix:50:9
(use ‘--show-trace’ to show detailed location information)
```

Running `ccsm` is an error:

``` python
Traceback (most recent call last):
  File "/nix/store/pb4fy8lpv7w06llq559l61gnl9nrwy8j-compiz-0.9.12.2/bin/.ccsm-wrapped", line 120, in <module>
    mainWin = ccm.MainWin(context, plugin, category)
  File "/nix/store/pb4fy8lpv7w06llq559l61gnl9nrwy8j-compiz-0.9.12.2/lib/python2.7/site-packages/ccm/Window.py", line 59, in __init__
    self.MainPage = MainPage(self, self.Context)
  File "/nix/store/pb4fy8lpv7w06llq559l61gnl9nrwy8j-compiz-0.9.12.2/lib/python2.7/site-packages/ccm/Pages.py", line 1180, in __init__
    pluginWindow = PluginWindow(self.Context)
  File "/nix/store/pb4fy8lpv7w06llq559l61gnl9nrwy8j-compiz-0.9.12.2/lib/python2.7/site-packages/ccm/Widgets.py", line 1604, in __init__
    pool = plugins or list(self._context.Plugins.values())
AttributeError: 'NoneType' object has no attribute 'values'
```
### Steps to reproduce

Compiz as the window manager:
1. Get a fresh install of the latest NixOS.
2. Add `services.xserver.windowManager.compiz.enable = true;` in `/etc/nixos/configuration.nix`.

CCSM:
1. `nix-env -i compiz`
2. `ccsm`
## Comment

I suspect that both issues come from the same origin: The additional packages to Compiz, e.g. ccsm, compiz-plugins-extra, etc. might have been mistakenly erased.

**Comment by 7c6f434c** [comment]
`ccsm` is now inside `compiz` package (an upstream change).

I have no idea about the NixOS module — I have stopped using NixOS (but not NixPkgs) precisely because systemd conflicts with how I use Xorg.
