### ISSUE TITLE
Document updating the packages in TeXLive

### ISSUE THREAD

**Issue by barrucadu** [NixOS/nixpkgs#13736]
Both moderncv and fontawesome in the new texlive set-up are from 2013, but they both had updates last year. I tried to fix this myself, but I'm not sure how to generate the files in `pkgs/tools/typesetting/tex/texlive-new` correctly.

I was able to produce a `pkgs.nix` (although `tl2nix.sed` wasn't enough, I then had to use `grep` to filter out a load of lines it didn't handle), but I'm at a loss for how to use `fixHashes.sh`.

Could the process be documented somewhere? It would make it easier for the packages to be kept up-to-date.

**Comment by vcunat** [comment]
- All versions are exactly from TeX Live 2015, as released upstream.
- The generation commands are written at the inclusion point of the generated files. (It's possible there are some small bugs in there.)
  * https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L46
  * https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L57

I assumed we would mostly wait for upstream to release the 2016 version and jump to that, as NixOS.org seems to have too few users to test our own collection thoroughly.

**Comment by 7c6f434c** [comment]
1. It looks like `tug.ctan.org` (re: update instructions) doesn't work for ftp, but `tug.org` does

2. It looks like most of the hashes have recently changed, and regenerating the same release-2015 pkgs.nix gives new hashes and sometimes even new versions (hashes for old versions have also changed)

The modification date on `texlive.tlpdb` online is `05 April 2016`

Does anyone have any idea what is going on?

@vcunat should I just regenerate everything?

**Comment by 7c6f434c** [comment]
Hm, looking at `metafont` as an example, there are some cosmetic changes to the tarball… And I am not sure there is any stable link…

**Comment by 7c6f434c** [comment]
Or is the second point just yet another illustration of #10026 ?

**Comment by vcunat** [comment]
What's wrong with metafont? It *was* illustration of the later part of that issue, but I hoped it should be OK now for the basic packages, e.g.:
```
$ nix-build -E 'with import ./. {}; lib.head texlive.metafont.pkgs'
these derivations will be built:
  /nix/store/2bkbbkfn3xarlzswmngw1r0bxjinckbq-texlive-metafont-2.7182818.drv
these paths will be fetched (0.03 MiB download, 0.03 MiB unpacked):
  /nix/store/z641fmfs4q0vym2av7p9dbfnawd4yhal-metafont.tar.xz
fetching path ‘/nix/store/z641fmfs4q0vym2av7p9dbfnawd4yhal-metafont.tar.xz’...

*** Downloading ‘http://cache.nixos.org/nar/1dvb54lqc8hxfwf819lql8qg7srgs8zc0dp3003qfxivgr8wbwlb.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/z641fmfs4q0vym2av7p9dbfnawd4yhal-metafont.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33668  100 33668    0     0  76877      0 --:--:-- --:--:-- --:--:-- 77043

building path(s) ‘/nix/store/qgb63jpxizvajyzng0c79adfbh9ljjiv-texlive-metafont-2.7182818’
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
/nix/store/qgb63jpxizvajyzng0c79adfbh9ljjiv-texlive-metafont-2.7182818
```

**Comment by 7c6f434c** [comment]
>What's wrong with metafont? It *was* illustration of the later part of that issue, but I hoped it should be OK now for the basic packages, e.g.:

I had a local metafont tarball in store, so I didn't check cache 
availability and just started comparing the old and the new tarballs
after fetching from upstream.

Sorry for being unclear.

**Comment by vcunat** [comment]
If you still have some of the old tarballs that aren't yet served by tarballs.nixos.org, it would be nice if you arranged it so that Eelco could pull them.

**Comment by 7c6f434c** [comment]
>If you still have some of the old tarballs that aren't yet served by tarballs.nixos.org, it would be nice if you arranged it so that Eelco could pull them.

I have a gig of tar.xz's on my laptop, some of them TeXLive-related, and
hopefully some more on my brix. What is the correct expression to
quickly get a list of all src's for all of texlive.*.pkgs ?

**Comment by vcunat** [comment]
It's not easy with current code, but see lists I posted on https://github.com/NixOS/nixpkgs/issues/10026#issuecomment-207440320

**Comment by 7c6f434c** [comment]
So I have these: https://gist.github.com/216991722ebef16d7cd349f016590e81 apparently

**Comment by 7c6f434c** [comment]
Just in case:

https://mega.nz/#!ap8XgKQI!1aVkGqFIsJQz2HQ946-Ksb9LWIaxJbzeH6f7Pus3AlM

**Comment by vcunat** [comment]
@edolstra: can you upload these texlive tarballs as well?

**Comment by 7c6f434c** [comment]
I can share them in some more sensible way, if there is a preferred one.

**Comment by utdemir** [comment]
If it helps, I have these tarballs in my /nix/store too (about 14k): http://lpaste.net/160399

Does anyone need any of them?

**Comment by vcunat** [comment]
I think we've exhausted this issue.
