### ISSUE TITLE
Latest Splix version breaks printing on Samsung ML-2510

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#13734]
On the current `master` branch`, printing with Splix + Cups is broken, apparently because of a version (string?) mismatch:

~~~
Samsung_ML-2510_Series-288  	Unknown  	Withheld  	83k  	Unknown  	stopped 
"SpliX Invalid PPD file version: 2.0.0 but the PPD file is designed for SpliX V. SpliX V. 2.0.0" 	
 ~~~

**Comment by peti** [comment]
Fixed temporarily by reverting the recent version update in e338d6a0fc1293c1d5b63d9e38e690526fc7d1b1.

**Comment by peti** [comment]
Cc: @bendlas

**Comment by bendlas** [comment]
Dang, I had hoped they wouldn't break older printers ... *sigh*. There are newer models, like the SCX-4500, only supported by current svn.
I guess neither of us is interested in diving into the code base to fix the ML-2510, so I propose reintroducing the svn version separately for the time being.

**Comment by peti** [comment]
I suppose we could report this issue upstream and ask for help. In the mean time, I don't think we should keep this issue open here.

**Comment by bendlas** [comment]
Created an upstream ticket: https://sourceforge.net/p/splix/bugs/93/

**Comment by peti** [comment]
Very cool. I'd like to thank you for the time and effort you've put into updating Splix!

**Comment by bendlas** [comment]
@peti could you try something for me: With the newer version **recreate** your printer, please?

I was just about to dig deeper and I noticed, that the file version changed indeed, from your version `SpliX V. 2.0.0` -> `2.0.0` in the newer version. In the update notes for splix, it says

```
Installation:
-------------

  +=======================================================================+
  |                  !!!      IMPORTANT NOTICE      !!!                   |
  +=======================================================================+
  |      If you are upgrading your current version, you MUST delete       |
  |     your printer in the CUPS interface and install it again. This     |
  |   operation MUST be done since CUPS make a copy of the PPD file and   |
  |                this file is modified between versions.                |
  +=======================================================================+
```

**Comment by bendlas** [comment]
@peti in case this works, that part of cups really should be managed by nixos. I think that would boil down to generating `/etc/cups/ppd`. See https://bugs.launchpad.net/ubuntu/+source/cups/+bug/932882 http://linux.die.net/man/8/cups-genppdupdate

**Comment by bendlas** [comment]
@peti btw, if you could verify, that gutenprint's `cups-genppdupdates` can fix this case (and then presumably others as well) without recreating the printer, then we could use that as a nixos activation hook for cups, to save others the trouble.

**Comment by bendlas** [comment]
thanks!
