### ISSUE TITLE
ffado: should install .ffado/configuration

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#13738]
Hi, I'd faced the same issue described here:
https://sourceforge.net/p/ffado/mailman/ffado-user/thread/20110205154307.385b9202@stein/

I needed to download and copy the configuration file to the ~/.ffado dir. Could we patch it to point to $out/share/libffado/configuration or something? it's just not obvious
cc: @goibhniu @wkennington

**Comment by Profpatsch** [comment]
Sorry there was no reply. Is this still an issue?

**Comment by nico202** [comment]
I've not used my firewire card for so long, I might reopen this if I face it next time I'll try
