### ISSUE TITLE
16.03-beta tag isn't picked up by git describe

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#13737]
This happens when run on `master`:

~~~~
$ git describe 
15.09-beta-10402-gf39e159
~~~~

**Comment by vcunat** [comment]
Oh no, I probably tagged a bad commit. It isn't explicitly said in #4442 which one should be tagged &ndash; I did the first commit not reachable from master, but now I see we probably wanted to tag the last common commit instead.

**Comment by peti** [comment]
Can we just force push a new tag?

**Comment by vcunat** [comment]
We can, but you know... people who already have the old tag won't get it updated unless they specify `-f`, which isn't very nice.

**Comment by peti** [comment]
> People who already have the old tag won't get it updated unless they specify -f, which isn't very nice.

Really? I thought fetching would overwrite the old tag without needing any special flags?

**Comment by vcunat** [comment]
No, and it's considered a bad practice to update tags. See: https://git-scm.com/docs/git-tag, section *On Re-tagging*. I also remember how I dislike when `fetchFromGitHub` changes hash because upstream chose to force-push the tag we're fetching from.

What do we use these \*-beta tags for, apart from `git describe`?

**Comment by vcunat** [comment]
Well, if I merge that tag to recent master (without letting files change), I get:
```
$ git describe
16.03-beta-417-g53b96a9
```

I just wonder if it might have some unexpected consequence for some other use case for these tags.

**Comment by peti** [comment]
I don't think these tags are used for anything except `git describe`. Still, it would be nice if the tag is accurate, i.e. consistent with the 15.09-beta tag, and personally I'd  be willing to live with the inconvenience of having to run `git fetch --tags --force`.

**Comment by vcunat** [comment]
Hmm, well, this case doesn't seem so bad as re-tagging releases. The main "danger" is that different people will get different `git describe` behavior due to one of them not force-updating it. I forgot to /cc @domenkozar.

**Comment by vcunat** [comment]
Actually, why should current master be described as 16.03-beta? It will *not* be contained in any 16.03 version.

**Comment by peti** [comment]
> Actually, why should current master be described as 16.03-beta?

Because we chose to do things this way when 15.09-beta was tagged, and
we should have consistent behavior.

**Comment by edolstra** [comment]
What do we need that tag for anyway? Given that we have rolling releases it's not really clear what the meaning of a "16.03-beta" tag is.

**Comment by vcunat** [comment]
When I checkout some random commit, it seems useful to me to have a way to determine the number of commits since the last release branching point and which release was last branched.

**Comment by edolstra** [comment]
`git merge-base` can be used to find the branch point as well.

**Comment by vcunat** [comment]
Yes, but the main point is to have `git describe` or something similar.

**Comment by domenkozar** [comment]
So the bottom line is, we should tag the commit before branching off instead of afterwards. Right?

**Comment by peti** [comment]
How about we add this tag: https://github.com/peti/nixpkgs/releases/tag/16.03-branch-off ?

**Comment by domenkozar** [comment]
But still, master will show as it's `16.03-branch-off`. `16.03` release won't be seen as really it will be tagged in another branch. So then we tag master with `something-alpha`? It all becomes a mess, where you can just check the branch.

**Comment by domenkozar** [comment]
`master` == rolling, alpha
`release-X` == X beta or final

**Comment by domenkozar** [comment]
I was at first all for tagging, but now it's becoming a bikeshedding waste of time - we have so much better things to fix.

**Comment by peti** [comment]
> But still, master will show as it's `16.03-branch-off`.

Huh? I'm not sure what you mean. `master` says: `16.03-branch-off-1424-g1f8ffdd`, which means it's 1424 commits beyond the point where 16.03 has been branched off. What's wrong with that?

> `16.03` release won't be seen as really it will be tagged in another branch.

I don't think a tag of that name exists -- and arguably it shouldn't, because there is no such thing as a "16.03 release" because we're continuously developing it. Am I missing something? Anyhow, if `git describe` is run in the release branch, then the result is `16.03-beta-302-gb314616`.

> So then we tag master with `something-alpha`?

No, I don't think we should. What would that accomplish?

> I was at first all for tagging, but now it's becoming a bikeshedding waste of time - we have so much better things to fix.

Well, if you don't care about discussing this issue, then why don't you just ignore it? It's not like those tags will be visible and/or of any interest to anyone except a small fraction of the core developers.

**Comment by edolstra** [comment]
Another problem with the current tags is that the version number they report is different from the NixOS version. For instance, for NixOS 15.09.1172.8f56c38, doing `git describe` gives:
```
15.09-631-g8f56c38
```
Deleting the `15.09` tag does give the right commit count:
```
15.09-beta-1172-g8f56c38
```

For 16.03, the `16.03-beta` tag gives the wrong result, e.g. for 16.03.280.531baf8:
```
16.03-beta-272-g531baf8
```
I've just fixed that (4be705574a36e4117588fbe8451d35f7a55a96c5).

IMHO we should:
* Get rid of the -beta tags, they're not really useful.
* Make the 16.03 tag point to the first commit on the 16.03 branch. Possibly name it `release-16.03-start`. (I have some tags named `release-13.10-start` and `release-14.04-start` locally, but apparently I never pushed them.)

Alternatively, get rid of all tags since our release process doesn't use them and thus they're only likely to confuse people.

**Comment by vcunat** [comment]
> Make the 16.03 tag point to the first commit on the 16.03 branch.

That's exactly the location of `16.03-beta` now.

**Comment by peti** [comment]
>> Make the 16.03 tag point to the first commit on the 16.03 branch.
>
> That's exactly the location of 16.03-beta now.

Isn't the first commit of `release-16.03` the last shared commit between `release-16.03` and `master`?

**Comment by vcunat** [comment]
I understood Eelco's formulation rather as the first commit that isn't shared.

**Comment by vcunat** [comment]
Well, anyway, personally I don't much care about how we do this tagging. I've probably spent more energy on it than I wanted already.

**Comment by grahamc** [comment]
This looks fixed:

```
$ git describe
16.03-185-g9413753
```

**Comment by peti** [comment]
@grahamc, you probably ran this command in the release branch, not on master.

**Comment by peti** [comment]
Solved: https://github.com/NixOS/nixpkgs/releases/tag/release-16.03-start.
