### ISSUE TITLE
element-desktop Wayland window doesn't show anymore

### ISSUE THREAD

**Issue by hmenke** [NixOS/nixpkgs#137377]
### Describe the bug
Since 796e82308363e1adc68d0982c02de8a705376c75 or a75daa8c05eec495fa48ba794f6f513916eece27 (not sure) the native Wayland window of element-desktop doesn't show anymore.

### Steps To Reproduce
When I launch element-desktop it shows a bunch of log messages but then just sits there without showing the window.

```console
$ rm -rf ~/.config/Element/
$ element-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland
Keytar isn't installed; secure key storage is disabled.
Seshat isn't installed, event indexing is disabled.
/home/henri/.config/Element exists: no
/home/henri/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
Changing application language to en-us,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
Require stack:
- /nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/language-helper.js
- /nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/tray.js
- /nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/electron-main.js
- /nix/store/qvnn6d6rb26z6n2bkl8m8gnlfcyp7bhz-electron-12.0.18/lib/electron/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/language-helper.js:76:20)
    at /nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/language-helper.js',
    '/nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/tray.js',
    '/nix/store/nnv8sph0a16kzh2ds8qcxn4nji9v2x0w-element-desktop-1.8.2/share/element/electron/lib/electron-main.js',
    '/nix/store/qvnn6d6rb26z6n2bkl8m8gnlfcyp7bhz-electron-12.0.18/lib/electron/resources/default_app.asar/main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

The `Error: Cannot find module` is actually irrelevant here. That has been there for a long time, but I didn't notice any problems regarding i18n.

### Expected behavior
The window should show up.

### Screenshots
N/A

### Additional context
This could also be related to an Electron update.

### Notify maintainers

@ma27 @fadenb @mguentner @Ekleog @Ralith @mjlbach @dali99 @sumnerevans

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.05.20210908.12eb1d1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - nixpkgs: `/etc/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: element-desktop
# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
Both this and #137530 appear to be because of https://github.com/vector-im/element-desktop/pull/256#issuecomment-913676319.

Since I expect a new element-desktop release tomorrow (because of https://matrix.org/blog/2021/09/10/pre-disclosure-upcoming-critical-fix-for-several-popular-matrix-clients/), I'd say that we wait and the affected users run `element-desktop` temporarily in X11 mode or apply https://github.com/vector-im/element-desktop/pull/261 to `pkgs.element-desktop` via `overrideAttrs`.

**Comment by Ma27** [comment]
Unfortunately it seems as if the patch (https://github.com/vector-im/element-desktop/commit/96e5389779f60c91b8fe80d7bd9af413d72ec61f) isn't part of 1.8.4: https://github.com/vector-im/element-desktop/compare/v1.8.2...v1.8.4

I think it's more important currently to get the element changes out to fix their security issue, but after that I'd just try to apply the patch to get this fixed :)
