### ISSUE TITLE
texFunctions.runLatex {} fails to invoke pdflatex

### ISSUE THREAD

**Issue by svanderburg** [NixOS/nixpkgs#13732]
## Basic info

To make sure that we are on the same page:

* Kernel: Linux nixos 4.1.13 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
* System: 16.03pre75174.d0e3cca (Emu)
* Nix version: nix-env (Nix) 1.10
* Nixpkgs version: 16.03pre75806.77f8f35

## Describe your issue here

When trying to build a PDF document from LaTeX sources through the texFunctions.runLatex {} function, I get the following error:

these derivations will be built:
  /nix/store/0a4ywyq95lnsm87r0n8i3kl1vhxl3cvz-texlive-combined-2015.drv
  /nix/store/j49p6byrw68rghy8yx30jskwq2hgp2p6-pgf-2.00.drv
  /nix/store/zsly4b4fkgqcr1yck2vcfi4scz1zpa82-doc.drv
building path(s) ‘/nix/store/ljvrb73s3l5d4n9ic9x2pgsv7606868h-pgf-2.00’
building path(s) ‘/nix/store/3bh7z4yjn130w0gjd3h2373hm8cdvnpn-texlive-combined-2015’
unpacking sources
unpacking source archive /nix/store/pb40xb96ns2wrngzxvw80x080zhzzvq6-pgf-2.00.tar.gz
created 1 symlinks in user environment
source root is pgf-2.00
/nix/store/x4pl766z2xfzvdcagiq0fb5hxl9z8b61-stdenv/setup: line 829: cd: ./share/texmf/web2c/: No such file or directory
builder for ‘/nix/store/0a4ywyq95lnsm87r0n8i3kl1vhxl3cvz-texlive-combined-2015.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/zsly4b4fkgqcr1yck2vcfi4scz1zpa82-doc.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/zsly4b4fkgqcr1yck2vcfi4scz1zpa82-doc.drv’ failed

I have checked the same function in the last stable Nixpkgs (release 15.09), which still seems to work fine.

### Expected result

A PDF file

### Actual result

Nothing

### Steps to reproduce

Create a simple doc.ltx:

\documentclass{article}
\usepackage{graphicx}

\begin{document}

\title{Introduction to \LaTeX{}}
\author{Author's Name}

\maketitle

\begin{abstract}
The abstract text goes here.
\end{abstract}

\section{Introduction}
Here is the text of your introduction.

\begin{equation}
    \label{simple_equation}
    \alpha = \sqrt{ \beta }
\end{equation}

\subsection{Subsection Heading Here}
Write your subsection text here.

\begin{figure}
    \centering
    \includegraphics[width=3.0in]{myfigure}
    \caption{Simulation Results}
    \label{simulationfigure}
\end{figure}

\section{Conclusion}
Write your conclusion here.

\end{document}

and the following Nix expression:

let {
  pkgs = import <nixpkgs> {};
  
  body = pkgs.texFunctions.runLaTeX {
    rootFile = ./doc.ltx;
    extraFiles = [
    ];
    packages = [];
  };
}

Then run:

nix-build

**Comment by vcunat** [comment]
Ah, yes, it isn't very user-friendly ATM. I would commit this:
```diff
diff --git a/pkgs/tools/typesetting/tex/nix/default.nix b/pkgs/tools/typesetting/tex/nix/default.nix
index 5cd5515..ce5c025 100644
--- a/pkgs/tools/typesetting/tex/nix/default.nix
+++ b/pkgs/tools/typesetting/tex/nix/default.nix
@@ -17,7 +17,9 @@ rec {
     assert generatePDF -> !generatePS;
 
     let
-      tex = pkgs.texlive.combine texPackages;
+      tex = pkgs.texlive.combine
+        # always include basic stuff you need for LaTeX
+        ({inherit (pkgs.texlive) scheme-basic;} // texPackages);
     in
 
     pkgs.stdenv.mkDerivation {
```

Will it fully cover the usual use cases?

**Comment by svanderburg** [comment]
It partially works, but now it cannot find beamer.cls :-)

I'm now trying to figure out how I can include the texLive package that
provides it, but it seems that the runLatex{} function has no interface yet
allowing you to include stuff from the giant texLive distribution?

**Comment by vcunat** [comment]
Well, the new `texlive` is relatively granular &ndash; `scheme-basic` doesn't contain stuff like beamer. You can pass more packages like this:
```nix
runLaTeX {
  texPackages = { inherit (texlive) beamer; };
  # ...
}
```

**Comment by svanderburg** [comment]
That did the trick! Thanks!

**Comment by vcunat** [comment]
Hehe, I wanted to commit it and I see you've done it already.

**Comment by svanderburg** [comment]
Haha indeed! You seem to work quite fast!

**Comment by vcunat** [comment]
Sometimes I get fast and sometimes I can't move from the spot for days...
