### ISSUE TITLE
Packaging request: LinuxGSM

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#137459]
**Project description**
The command-line tool for quick, simple deployment and management of Linux dedicated game servers.

**Metadata**

* homepage URL:  https://linuxgsm.com/
* source URL:  https://github.com/GameServerManagers/LinuxGSM
* license: mit
* platforms: linux

**Comment by wamserma** [comment]
I don't think this needs packaging here.
Usage instructions say one should simply download the latest linuxgsm-script, then run it from the CLI.
Aside from that, it is very likely that the script will not work on NixOS: Its sole purpose is to download and install Game-Servers in an imperative manner, which conflicts with the declarative approach of Nix. (It would make more sense if LinuxGSM was able to generate Nix-snippet to include in a system configuration.)
Just compare:
For LinuxGSM you first to get the dependencies right (manually), then download the installer, then install the server. Then manually take care about updating the server, fixing issues when dependencies break etc.
https://linuxgsm.com/lgsm/mcserver/
The real fun starts, when you have two servers with conflicting requirements (e.g. two different OpenSSL versions).
In NixOS, you just set a few config options and issue one command to rebuild your system:
https://search.nixos.org/options?channel=21.05&from=0&size=50&sort=relevance&type=packages&query=minecraft-server

So, thanks for taking the time to open this request, but users of LinuxGSM should stick to one of the officially supported Linux Distros (Ubuntu, Debian, CentOS).
That said, you can still use the powers of NixOS to declaratively create a container/VM with one of the mentioned Distros and run LinuxGSM there.

If you were rather interested in running one particular server, please open a new issue!
