### ISSUE TITLE
nvidia driver build failure on 5.14.1

### ISSUE THREAD

**Issue by alsvartr** [NixOS/nixpkgs#137507]
Nvidia build failure on 5.14.1 kernel using pkgs.linuxPackages_latest.nvidia_x11
Numerous compiler errors while building:

```
make[3]: *** [/nix/store/ld479n8nmwsr7x3p2ayg70r527aaqhpc-linux-5.14.1-dev/lib/modules/5.14.1/source/scripts/Makefile.build:271: /build/kernel/nvidia/nv-dma.o] Error 1
In file included from /build/kernel/common/inc/nv-linux.h:25,
                 from /build/kernel/nvidia/nv-vm.c:13:
/build/kernel/common/inc/nv-time.h: In function 'nv_sleep_ms':
/build/kernel/common/inc/nv-time.h:217:18: error: 'struct task_struct' has no member named 'state'; did you mean '__state'?
  217 |         current->state = TASK_INTERRUPTIBLE;
      |                  ^~~~~
      |                  __state
make[3]: *** [/nix/store/ld479n8nmwsr7x3p2ayg70r527aaqhpc-linux-5.14.1-dev/lib/modules/5.14.1/source/scripts/Makefile.build:271: /build/kernel/nvidia/nv.o] Error 1
make[3]: *** [/nix/store/ld479n8nmwsr7x3p2ayg70r527aaqhpc-linux-5.14.1-dev/lib/modules/5.14.1/source/scripts/Makefile.build:271: /build/kernel/nvidia/nv-vm.o] Error 1
make[2]: *** [/nix/store/ld479n8nmwsr7x3p2ayg70r527aaqhpc-linux-5.14.1-dev/lib/modules/5.14.1/source/Makefile:1851: /build/kernel] Error 2

```

### Metadata
```nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.12, NixOS, 21.05.2734.74d017edb67 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3021.8b0b81dab17, home-manager-20.09, nixos-hardware, nixos-unstable-21.11pre313915.bbbe2b35f73"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by InternetUnexplorer** [comment]
This is usually the case when a new kernel release happens (for example, see https://github.com/NixOS/nixpkgs/issues/130130). You can either use an older kernel for a bit until it's fixed, e.g.
```
boot.kernelPackages = pkgs.linuxPackages_5_13;
```
…or you could try patching it. There seems to be a patch for 5.14 [here](https://github.com/Frogging-Family/nvidia-all/blob/master/patches/kernel-5.14.patch) if you're interested.

**Comment by alsvartr** [comment]
> This is usually the case when a new kernel release happens (for example, see #130130). You can either use an older kernel for a bit until it's fixed, e.g.
> 
> ```
> boot.kernelPackages = pkgs.linuxPackages_5_13;
> ```
I don't like idea of version pinning (especially for kernel) - I'm stuck with old software and forced to maintain it (check newer version for build errors, etc) by myself. There is a bug and it should be fixed by a maintainer of derivative.
And as far as I know I can't choose different kernel derivative - e.g. linuxPackages_lte.
 
> …or you could try patching it. There seems to be a patch for 5.14 [here](https://github.com/Frogging-Family/nvidia-all/blob/master/patches/kernel-5.14.patch) if you're interested.

...Or this could be done by a maintainer ;)

**Comment by rycee** [comment]
I've tried the patch on my NixOS 21.05 system and it seems to work OK. I used the following change:

```patch
diff --git a/pkgs/os-specific/linux/nvidia-x11/default.nix b/pkgs/os-specific/linux/nvidia-x11/default.nix
index 059fef24d83..15876636dc5 100644
--- a/pkgs/os-specific/linux/nvidia-x11/default.nix
+++ b/pkgs/os-specific/linux/nvidia-x11/default.nix
@@ -23,6 +23,14 @@ rec {
       sha256_64bit = "sha256-VdeuEEgn+qeel1Mh/itg+d1C+/9lZCBTRDwOVv20xH0=";
       settingsSha256 = "sha256-DJg5QbyuKJmPpLQVYgTLvucI1e9YgQOO16690VXIWvk=";
       persistencedSha256 = "sha256-Cqv6oUFnsSi3S1sjplJKeq9bI2pqgBXPPb11HOJSlDo=";
+      patches = [
+        (fetchpatch {
+          url = "https://raw.githubusercontent.com/Frogging-Family/nvidia-all/master/patches/kernel-5.14.patch";
+          sha256 = "042zyspddka1acmli9l4h4cbzpfgq8a9lcdwjgwjr0npdgqk3j3f";
+          stripLen = 2;
+          extraPrefix = "kernel/";
+        })
+        ];
     }
     else legacy_390;
```

**Comment by adamlwgriffiths** [comment]
Is there any way to apply this without having to use a custom nixpkgs checkout?

**Comment by InternetUnexplorer** [comment]
You might be able to do
```nix
{
  hardware.nvidia.package = pkgs.linuxPackages_latest.nvidia_x11.overrideAttrs (_: { patches = ...; });
}
```

Or maybe you'd need to use `boot.kernelPatches` /  `pkgs.linuxPackages_latest.extend`?

I realize the above isn't super detailed (sorry), and I unfortunately can't test any of it right now but I feel like one of those should work.

**Comment by alsvartr** [comment]
I don't understand why it can't be patched by a maintainer?
@baracoder

**Comment by baracoder** [comment]
@alsvartr sorry, I am not up to standards being a maintainer lacking time and motivation. I will remove myself as maintainer from the package.

**Comment by rycee** [comment]
Should be sorted with the merge of fd8a7fd07da0f3fc0e27575891f45c2f88e5dd44. Please check and reopen if the problem remains.

**Comment by alsvartr** [comment]
> Should be sorted with the merge of [fd8a7fd](https://github.com/NixOS/nixpkgs/commit/fd8a7fd07da0f3fc0e27575891f45c2f88e5dd44). Please check and reopen if the problem remains.

Wait, it's fixed on that specific issue, right? So this problem isn't fixed globally and will occur on future releases.
