### ISSUE TITLE
`jq.out` is empty

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#137594]
### Describe the bug

`pkgs.jq` has 6 outputs, the main of whose (`.out`) produces an empty directory

### Steps To Reproduce
`nix-build -E '(import <nixpkgs> {}).jq.all'`

**Comment by gebner** [comment]
The out output is still empty.

**Comment by ModdedGamers** [comment]
Working on fixing this now.

**Comment by SuperSandro2000** [comment]
out is empty because jq has so many outputs that no files are left.
