### ISSUE TITLE
element-desktop crashes on native wayland

### ISSUE THREAD

**Issue by MalteT** [NixOS/nixpkgs#137530]
### Describe the bug
element-desktop crashes on native Wayland (wlroots/Sway) on latest nixos-unstable.

### Steps To Reproduce
1. Run Sway version 1.6
2. Run `nix run nixpkgs#element-desktop -- --enable-features=UseOzonePlatform --ozone-platform=wayland`
3. Observe SIGTRAP signal.

The same happens when using `pkgs.element-desktop.override { useWayland = true; }`

### Expected behavior
`element-desktop` should run fine with the Wayland flags (as it did before iirc)

### Notify maintainers
@ma27 @pacien @fadenb @mguentner @ekleog @ralith @mjlbach

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.11pre291991.ea7d4aa9b82"`
 - channels(malte): `"nixos-21.11pre313915.bbbe2b35f73"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: element-desktop
# a list of nixos modules affected by the problem
module:
```

**Comment by kittywitch** [comment]
Possibly related to #137377?

**Comment by MalteT** [comment]
Ah, yes, I planned to reference that one. I wondered myself, but I'm getting far less output and element-desktop actually crashes
```console
$ nix run nixpkgs#element-desktop -- --enable-features=UseOzonePlatform --ozone-platform=wayland
/home/malte/.config/Element exists: yes
/home/malte/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
fish: Job 1, 'nix run nixpkgs#element-desktop…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by Ma27** [comment]
I'm pretty sure that both have the same cause (`enable-features` being discarded, so Wayland mode is started without `UseOzonePlatform`), so I'm going to close this and leave the other one open until we have a fix (which I expect tomorrow since there's a new patch-level release scheduled anyways).
