### ISSUE TITLE
vimPlugins.fzf-vim is broken 

### ISSUE THREAD

**Issue by arcticlimer** [NixOS/nixpkgs#137652]
### Describe the bug
Fzf.vim's commands are not working.

### Steps To Reproduce
1. Use the latest nixpkgs `vimPlugins.fzf-vim` plugin
2. Open neovim and use the command `:Files` or any other fzf Ex commands

### Expected behavior
Fzf commands should work

### Additional context
Error message inside neovim 
```
Error detected while processing function fzf#vim#files[15]..<SNR>55_fzf[21]..fzf#run[63]..<SNR>27_execute_term[93]..<SNR>27_d
opopd:
line   20:
E716: Key not present in Dictionary: "dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))"
E15: Invalid expression: s:fzf_getcwd() ==# w:fzf_pushd.dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ at 10:53:47
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
I've seen that one and it disappeared after updating the vim plugins, could you try ?

**Comment by arcticlimer** [comment]
I've tried updating them 4-5 hours ago, and the issue was still here, right now I'm using telescope, gonna try updating them again tomorrow.

**Comment by arcticlimer** [comment]
Also, by updating the plugins you mean running the vim plugins update script on an alternative nixpkgs repo or just syncing with upstream nixpkgs?

**Comment by teto** [comment]
was thinking of running the update.py script but updating to latest nixos-unstable is worth a try too. I am on my fork of 364b5555ee04bf61ee0075a3adab4c9351a8d38c for instance.

**Comment by arcticlimer** [comment]
Yes, updating nixpkgs worked. I was updating the flake nixpkgs but home-manager was using a different nixpkgs, now it works atleast with upstream nixpkgs. Shall I close?

**Comment by teto** [comment]
you could submit a PR to update the plugins. As long as the fix is not merged in nixpkgs, this should stay open IMO

**Comment by teto** [comment]
there was an update of plugins here so it should be fine now https://github.com/NixOS/nixpkgs/pull/138265
