### ISSUE TITLE
GNOME Extension X11 Gestures hardcodes Touchegg path

### ISSUE THREAD

**Issue by maydayv7** [NixOS/nixpkgs#137621]
### Describe the bug
`gnomeExtensions.x11-gestures` (from [nixpkgs](https://search.nixos.org/packages?channel=21.05&show=gnomeExtensions.x11-gestures&from=0&size=50&sort=relevance&type=packages&query=x11+gestures)) is a GNOME extension which searches for the package `touchegg` in `/usr`

Because it can't detect the installed package it sends a notification that the `touchegg` package must be installed, and subsequently does not inhibit the default gestures provided by the package. Also, there is no built-in way to tell it to use another path.

### Steps To Reproduce
1. Install the `gnomeExtensions.x11-gestures` and `touchegg` (Please see additional context) packages
2. Enable the X11 Gestures extension

### Expected behavior
The extension must recognize the actual path for `touchegg` in `/nix/store` and work properly

### Additional context
Since the `touchegg` package in the repos is extremely outdated (v1.1.1), I am using an [overlay](https://github.com/maydayv7/nixos-config/blob/master/overlays/touchegg.nix) to install the latest version v2.0.11 (see [#116393](https://github.com/NixOS/nixpkgs/pull/116393) for updating the package in the repos).

Also, [#137131](https://github.com/NixOS/nixpkgs/pull/137131) may be relevant

### Maintainers
@piegamesde Extensions maintainer
@JoseExposito Creator of the extension and `touchegg`

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.05.3021.8b0b81dab17 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(v7): `"home-manager-21.05"`
 - channels(root): `"nixos-21.05.3021.8b0b81dab17"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by piegamesde** [comment]
I'll see how difficult it is to fix the path. However, I am reluctant to do custom dependencies patches, so I'd block this on #116393.

**Comment by maydayv7** [comment]
I don't think there are any custom dependency patches required (it is just an extension, and apart from inhibiting the default gestures, works properly as is).

**Comment by maydayv7** [comment]
I think [this](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/cf5376ca9489ae5ee49757d7c055e1112c56e2b1/src/touchegg/ToucheggConfig.js#L160) is where it searches for the package

**Comment by AdsonCicilioti** [comment]
> I think [this](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/cf5376ca9489ae5ee49757d7c055e1112c56e2b1/src/touchegg/ToucheggConfig.js#L160) is where it searches for the system `touchegg` config, to determine if the package is installed
> 
> EDIT: Confirmed that editing `src/touchegg/ToucheggConfig.js` and replacing `usr` with path in `/nix/store` fixes the issue

Why `/nix/store`? Wouldn't it be better on `/run/current-system/sw`?

**Comment by maydayv7** [comment]
That should be the best thing to do. I've tried to patch the extension using `postPatch`, but for some reason it doesn't seem to work, and I'm pretty new to Nix, so I've just left it for the time-being

**Comment by JoseExposito** [comment]
Ops, forgot to notify it here. I fixed this by following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

Both the GNOME extension and Touchégg use the `$XDG_CONFIG_DIRS` env var to find the system configuration:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/src/touchegg/ToucheggConfig.js#L165

The same applies for the user config with `$XDG_CONFIG_HOME`:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/src/touchegg/ToucheggConfig.js#L146

A NixOS maintainer suggested this fix.

**Comment by maydayv7** [comment]
Thanks a lot! #145382 seems to have updated the extension to the version which has the fixes, so I'll close this issue

**Comment by JoseExposito** [comment]
I think that the `$XDG_CONFIG_DIRS` needs to be set in the package to point to the right path. Not sure if that work is done though, since I'm not a NixOS user...

**Comment by AdsonCicilioti** [comment]
Still i get it
![image](https://user-images.githubusercontent.com/6278398/144600084-6c5d2a2b-0bc2-466a-810f-a0925f163ef7.png)

The gestures works with default touchegg gestures on the same time.
![image](https://user-images.githubusercontent.com/6278398/144600402-53411ddc-90a7-44dd-9fcf-f445b42c0c26.png)

**Comment by AdsonCicilioti** [comment]
I made a workaround. I created a blank `.config/touchegg/touchegg.conf`. Now I only have the extension gestures. But the "Not installed" alert still.

**Comment by AdsonCicilioti** [comment]
@JoseExposito 

My conf dirs:

```
$ echo $XDG_CONFIG_DIRS
/etc/xdg:/home/balllazo/.local/share/flatpak/exports/etc/xdg:/var/lib/flatpak/exports/etc/xdg:/home/balllazo/.nix-profile/etc/xdg:/etc/profiles/per-user/balllazo/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg:/nix/store/5h67rdlif30b5q000gx2kdw3wkjv8v4c-gnome-settings-daemon-41.0/etc/xdg:/nix/store/5h67rdlif30b5q000gx2kdw3wkjv8v4c-gnome-settings-daemon-41.0/etc/xdg
```
`touchegg/touchegg.conf` It's not in any of these places.

**Comment by JoseExposito** [comment]
In that case you'd need to add `:/run/current-system/sw/share` at the end of `$XDG_CONFIG_DIRS`. However, I'm not sure what's the NixOS way of doing it. I'm sure there is a way to fix this in the package.

**Comment by AdsonCicilioti** [comment]
Ok. Thanks!

**Comment by AdsonCicilioti** [comment]
@JoseExposito help us with your review on #148457
