### ISSUE TITLE
texlive-new: build of trivial packageset fails

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#13764]
```
> nix-build -E 'with import <nixpkgs> {}; with texlive; combine {} '
these derivations will be built:
  /nix/store/si8lxq99l9kmrd631fmi4ldjw91l62ld-hyphens.sed.drv
  /nix/store/0syl7by3hxvrk3n04hxdd27ypija251j-texlive-combined-2015.drv
building path(s) ‘/nix/store/bymh855b6bz3ab79di4dxlk5n7kaf7gb-hyphens.sed’
building path(s) ‘/nix/store/rmsz6f1kvai0iwda6hfl55w97148xs4l-texlive-combined-2015’
created 1 symlinks in user environment
/nix/store/xqlf0dmmzi79mhn7b51shmfqw6lq59y3-stdenv/setup: line 849: cd: ./share/texmf/web2c/: No such file or directory
builder for ‘/nix/store/0syl7by3hxvrk3n04hxdd27ypija251j-texlive-combined-2015.drv’ failed with exit code 1
error: build of ‘/nix/store/0syl7by3hxvrk3n04hxdd27ypija251j-texlive-combined-2015.drv’ failed
```

(it also fails with a package in the `combine` attrset)

cc @vcunat

**Comment by vcunat** [comment]
Yes, that's known. See the preliminary user docs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive-new/default.nix#L1

**Comment by Profpatsch** [comment]
Are you sure that’s how it should work? I used exactly the same statement around half a year ago and it worked fine.

Especially those two lines weren’t there the last time I checked:
```
/nix/store/xqlf0dmmzi79mhn7b51shmfqw6lq59y3-stdenv/setup: line 849: cd: ./share/texmf/web2c/: No such file or directory
builder for ‘/nix/store/q7jhlcqn9cmbdqjkgnax67qk1qwxd2hf-texlive-combined-2015.drv’ failed with exit code 
```

**Comment by vcunat** [comment]
Some things were changed probably, but the TeX stuff is probably useless if you don't plug any packages at all into it. Better fail early.

**Comment by Profpatsch** [comment]
As I said, `nix-build -E 'with import <nixpkgs> {}; with texlive; combine { inherit minted; } ' fails with the same error.

**Comment by vcunat** [comment]
Yes, as that one wouldn't even contain the TeX binaries. (Upstream TeX Live has very holey dependencies among the packages.)

**Comment by vcunat** [comment]
To explain better... the current `texlive` is a rather thin layer around the upstream packaging. Yes, we could improve it a lot, but I "only" invested a few full weeks of time into this and ATM I'm not inclined into more such TeX endeavors. That certainly doesn't prevent others from improving it.

**Comment by Profpatsch** [comment]
You mean it’s missing a few dependencies and so the build fails? Can we include those dependencies manually if CTAN doesn’t provide them?

**Comment by vcunat** [comment]
It is possible to override the dependency information manually, and we have a couple of adjustments in there already. CTAN doesn't provide any dependency information, I think. It's TeX Live where I took the information and the packages themselves. (And IIRC Fedora's srpm has some magic code that tries to detect the dependencies.)

To kill the problem that most packages depend on some of the core ones, I recommend in the user docs to always include one of the schemes, e.g. `scheme-basic`; that's what upstream TeX Live does anyway.
