### ISSUE TITLE
15.09 → 16.03 update breaks syncthing service with custom dataDir

### ISSUE THREAD

**Issue by rycee** [NixOS/nixpkgs#13768]
When upgrading my system from 15.09 to 16.03-beta the `syncthing` service failed, it was working fine under 15.09 with the following configuration
```
  services.syncthing = {
    enable = true;
    dataDir = "/home/rycee";
    user = "rycee";
  };
```
Turns out that 44788bb2ce5ecb025b63c71226ab613a05a334d3 changed the way the `dataDir` attribute works and changing the configuration to
```
  services.syncthing = {
    enable = true;
    dataDir = "/home/rycee/.syncthing";
    user = "rycee";
  };
```
fixed the issue. I didn't find any mention of this backwards incompatible change in the corresponding [release log](https://nixos.org/releases/nixos/16.03-beta/nixos-16.03.30.2068621/manual/release-notes.html#sec-releasel/release-notes.html#sec-release-16.03-16.03). It would be nice with an entry for this in the release log.

CC: @garbas, @fazo96

**Comment by garbas** [comment]
@rycee: tnx ... looks like we missed to add this

**Comment by garbas** [comment]
[fixed](https://github.com/NixOS/nixpkgs/commit/d014088c95dc65a1cfa6f4f4ef4384c7876d5970)

**Comment by rycee** [comment]
Thanks for the quick fix!

**Comment by fazo96** [comment]
Sorry for missing the notification!
