### ISSUE TITLE
ungoogled-chromium 92.0.4515.159 crashes with wayland flags

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#137688]
### Describe the bug

```
~
❯ chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
[281477:281477:0913/134642.439438:ERROR:cursor_loader.cc(115)] Failed to load a platform cursor of type kNull

(chromium:281477): Gtk-WARNING **: 13:46:42.481: Theme file for capitaine-cursors-white has no directories
[281513:281513:0913/134642.514926:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is egl
[281513:281513:0913/134642.519897:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[281477:281477:0913/134642.591404:ERROR:platform_shared_memory_region_posix.cc(47)] Descriptor access mode (0) differs from expected (2)
zsh: trace trap (core dumped)  chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

~
❯ which chromium
/etc/profiles/per-user/cole/bin/chromium

~
❯ readlink -f $(which chromium)
/nix/store/ilhrxff0xz1dfh3jlr8hr7yvngyj4l0w-ungoogled-chromium-92.0.4515.159/bin/chromium
```

cc: @primeos

**Comment by colemickens** [comment]
seems like this might just be upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1246834

**Comment by berbiche** [comment]
Looks like the fix is available in Chromium beta (tested 41dbc0a9954d852ef1d33ec5c79d64fe3cc84b8c)

**Comment by ja0nz** [comment]
Aaaand in the stable https://github.com/NixOS/nixpkgs/commit/a39908a7cb0e01c7d3c2f8a9199b14de6209f687

**Comment by danielphan2003** [comment]
Does this also apply to electron? I hit the same thing and have to use Xwayland instead.

**Comment by teutat3s** [comment]
It seems it does, at least I'm in the same boat. But for `electron_17` with [version 17.3.1](https://github.com/electron/electron/releases/tag/v17.3.1) a fix is in sight: https://github.com/NixOS/nixpkgs/pull/166587 and upstream: https://github.com/electron/electron/pull/33499

**Comment by primeos** [comment]
> I guess we can close this one

Yes, seems like it :)

> Does this also apply to electron?

https://github.com/NixOS/nixpkgs/issues/158175 ;)
