### ISSUE TITLE
dnsutils not packaged?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#13760]
Just to be sure: The dnsutils are not packaged with nixpkgs yet? I'm on latest unstable and I cannot find them (also not via the github search).

Am I dumb or are they really not available with nixpkgs yet?

**Comment by joachifm** [comment]
You probably want the `bind` package (for `dig` &c)

**Comment by matthiasbeyer** [comment]
And for `dnslookup`?

**Comment by joachifm** [comment]
Do you mean `nslookup` (interactive internet name service lookup)?

**Comment by matthiasbeyer** [comment]
Ah, yes.

**Comment by joachifm** [comment]
I guess it would be nice to have a `dnsutils` work-alike, though, for people who just want the client apps.

**Comment by peti** [comment]
IMHO, discoverability of those tools is pretty good:

~~~~
$ command-not-found nslookup
The program ‘nslookup’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.bind
  nix-env -iA nixos.busybox

$ command-not-found dig
The program ‘dig’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.bind
~~~

I suppose that we could create a special packet for the client side tools by means of multiple outputs, etc. I might get around to making that change in BIND, but I won't complain if someone beats me to it.

**Comment by matthiasbeyer** [comment]
Oh. Well, I guess we should document `command-not-found` better, as I didn't knew about this possibility...

**Comment by matthiasbeyer** [comment]
`command-not-found` fails for me :cry:

**Comment by peti** [comment]
It's a feature of NixOS. Not sure how to install that on other host systems.

**Comment by matthiasbeyer** [comment]
I'm on nixos.

**Comment by despairblue** [comment]
@matthiasbeyer @peti command-not-found is broken atm: https://github.com/NixOS/nixos-channel-scripts/issues/4
