### ISSUE TITLE
Firefox 92 on Sway - Menus are invisible and freeze the whole UI

### ISSUE THREAD

**Issue by jmc-figueira** [NixOS/nixpkgs#137649]
### Describe the bug
After upgrading to Firefox 92 on NixOS unstable, anything that requires a menu or a tooltip in the browser (hamburger menu, right click context menus, tooltips on tabs, etc.) stopped working. The menu itself isn't rendered, the whole UI freezes and sometimes the cursor changes to a hand, indicating a clickable button, but nothing happens when clicking where the button should be. Clicking outside the area where the menu should appear restores Firefox to a usable state, until another menu button is pressed.

### Steps To Reproduce
1. Open Firefox
2. Click the hamburger menu button on the top right corner

### Expected behavior
The main settings menu for Firefox should appear.

### Screenshots
The hamburger button remains in a "clicked" state and the entire UI freezes, the mouse cursor might change to a hand, but no menu is rendered.

### Additional context
Running Firefox on Sway with `MOZ_ENABLE_WAYLAND=1` and `"gfx.webrender.all" = true;`

### Notify maintainers
@lovesegfault @mweinelt @edolstra @NeQuissimus @vcunat 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/xq77wmzk8d306anyk9rsvl4i4h7ihchw-bash-interactive-4.4-p23-dev
copying path '/nix/store/xq77wmzk8d306anyk9rsvl4i4h7ihchw-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.11pre314199.f6e9e908ccb, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- firefox
# a list of nixos modules affected by the problem
module:
```

**Comment by lovesegfault** [comment]
I can reproduce this too, but I don't think it's NixOS' fault; we ought to report this upstream to sway and Firefox.

**Comment by lovesegfault** [comment]
https://github.com/swaywm/sway/issues/6426

https://github.com/swaywm/sway/issues/6147

**Comment by lovesegfault** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1730476

**Comment by lovesegfault** [comment]
You can manually apply this patch to firefox to fix the issue: https://hg.mozilla.org/integration/autoland/rev/3b856ecc00e4

I'm testing that now.

**Comment by lovesegfault** [comment]
You should be able to use this overlay to work around the issue for now:

```Nix
self: super: {
  firefox-unwrapped = super.firefox-unwrapped.overrideAttrs (old: {
    patches = (old.patches or [ ]) ++ [
      (self.fetchpatch {
        url = "https://hg.mozilla.org/integration/autoland/raw-rev/3b856ecc00e4";
        sha256 = "sha256-d8IRJD6ELC3ZgEs1ES/gy2kTNu/ivoUkUNGMEUoq8r8=";
      })
    ];
  });
}
```

**Comment by lovesegfault** [comment]
Alright, this overlay fully fixes the issues while we wait on a new release:

```Nix
self: super: {
  firefox-unwrapped = super.firefox-unwrapped.overrideAttrs (old: {
    patches = (old.patches or [ ]) ++ [
      (self.fetchpatch {
        url = "https://hg.mozilla.org/integration/autoland/raw-rev/3b856ecc00e4";
        sha256 = "sha256-d8IRJD6ELC3ZgEs1ES/gy2kTNu/ivoUkUNGMEUoq8r8=";
      })
      (self.fetchpatch {
        url = "https://hg.mozilla.org/mozilla-central/raw-rev/51c13987d1b8";
        sha256 = "sha256-C2jcoWLuxW0Ic+Mbh3UpEzxTKZInljqVdcuA9WjspoA=";
      })
    ];
  });
}
```

I'm going to make a PR adding this to our pkg for now.

**Comment by calbrecht** [comment]
The two patches applied, menus and form overlays are visible again and the freezing is gone. Thank you @lovesegfault

**Comment by jmc-figueira** [comment]
Unfortunately, it seems the fix has not worked for me. It _may_ be due to using the home-manager module; however, I have overriden its `firefox.package` to use the patched version and the only noticeable difference is that now a tiny vertical line appears where the context menus should be. The freezing caused by it and the fact that the menu itself is still unusable are still present, though.

**Comment by vcunat** [comment]
There were multiple similar bugs, perhaps?

**Comment by mweinelt** [comment]
As a data point: I'm running Firefox 92.0 with the above mentioned patches on Sway on NixOS unstable and everything works great.

**Comment by jmc-figueira** [comment]
Do you happen to use the home-manager module or do you run firefox as a regular system package? That may be a differentiating factor and may point towards an issue with my home-manager configuration instead.

**Comment by jmc-figueira** [comment]
I have tried to add your method of explicitly wrapping the package and yet, the same behavior remains, unfortunately:

```Nix
firefox = {
  enable = true;

  package = pkgs.wrapFirefox pkgs.firefox-unwrapped {
    forceWayland = true;
  };

  extensions = with pkgs.nur.repos.rycee.firefox-addons; [
    ublock-origin
    reddit-enhancement-suite
    facebook-container
    multi-account-containers
  ];
  profiles = {
    jmc-figueira = {
      settings = {
        "browser.disableResetPrompt" = true;
        "browser.search.region" = "PT";
        "browser.download.useDownloadDir" = false;
        "browser.download.panel.shown" = true;
        "browser.newtabpage.activity-stream.topSitesRows" = 2;
        "browser.startup.page" = 3;
        "browser.toolbars.bookmarks.visibility" = "never";
        "browser.urlbar.matchBuckets" = "general:5,suggestion:infinity";
        "browser.uidensity" = 0;
        "browser.contentblocking.category" = "custom";
        "devtools.theme" = "dark";
        "dom.security.https_only_mode" = true;
        "dom.security.https_only_mode_ever_enabled" = true;
        "extensions.activeThemeID" = "firefox-dark@mozilla.org";
        "font.default.x-western" = "sans-serif";
        "fission.autostart" = true;
        "intl.accept_languages" = "pt-pt,pt,eo,en,en-us";
        "intl.locale.requested" = "pt-PT";
        "network.IDN_show_punycode" = true;
        "network.dns.disablePrefetch" = true;
        "network.http.speculative-parallel-limit" = 0;
        "network.http.http3.enabled" = true;
        "network.predictor.enabled" = false;
        "network.prefetch-next" = false;
        "network.trr.mode" = 3;
        "privacy.trackingprotection.enabled" = true;
        "privacy.trackingprotection.socialtracking.enabled" = true;
        "privacy.webrtc.legacyGlobalIndicator" = false;
        "signon.rememberSignons" = false;
        "gfx.webrender.all" = true;
        "media.ffmpeg.vaapi.enabled" = true;
        "media.ffvpx.enabled" = false;
        "media.rdd-vpx.enabled" = false;
      };
    };
  };
};
```

**Comment by vcunat** [comment]
I wonder if this could differ based on GPU model.  (different rendering code paths on driver side)

**Comment by mweinelt** [comment]
Interesting. It is working for me on amdgpu, but I saw the issue yesterday on an i915 gpu, didn't investigate much, whether the patch already made it onto the unstable channel.

**Comment by vcunat** [comment]
Yes, it is in `nixos-unstable` already but not in `nixos-21.05` yet.

**Comment by lovesegfault** [comment]
I have tested this on amdgpu, nouveau, and i915 without problems.

I'm wondering whether @jmc-figueira  is actually using the patched version? Try to clone the `nixpkgs` repo, do `nix-build -A firefox` and see if it works correctly.

Alternatively, this should give you a firefox with the patch so you can make sure:
```
nix build /nix/store/by39zm9i4vhwd0i5pjnf4apf7lhqmpv9-firefox-unwrapped-92.0 --option binary-caches https://cache.nixos.org
```

**Comment by lovesegfault** [comment]
Ah, I managed to reproduce it on i915 now. It's not immediate for me, after a bit the menus seem to break. Amazing.

**Comment by lovesegfault** [comment]
Maybe we also need this GTK patch: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3941

**Comment by lovesegfault** [comment]
Also worth trying: https://github.com/swaywm/sway/pull/6479

**Comment by jmc-figueira** [comment]
Interestingly, the firefox-unwrapped package in my system has a different hash, namely `9lnp260dpxxpw8vl6psx57adv20i10km-firefox-unwrapped-92.0`. Compiling from the nixpkgs repo as you suggested does give me the version with the hash `by39zm9i4vhwd0i5pjnf4apf7lhqmpv9-firefox-unwrapped-92.0` as you stated, and this version does behave correctly in regards to the menus. Something really strange is happening with my system updates then. Adding to this, I only got the version with the "black vertical line" as I described above (I attached a screenshot for reference) after I garbage collected a few generations of testing, which really shouldn't happen if I'm understanding the way nix works correctly. In any case, this is not an issue related to the Firefox package itself.

![Screenshot](https://user-images.githubusercontent.com/6634716/133514116-96deaf22-15f1-42d2-917d-e3964576f292.png)

**Comment by Synthetica9** [comment]
> Also worth trying: [swaywm/sway#6479](https://github.com/swaywm/sway/pull/6479)

I successfully have this working with firefox from mozilla's pkgs.

**Comment by Slabity** [comment]
So I was able to fix this by removing the `firefox-wayland` package from my home-manager config and adding it to my nixos-config.

Not sure if this helps anyone here debug the issue, but it's worth a look.

**Comment by jmc-figueira** [comment]
I've been running Firefox out of a local nixpkgs build but I haven't tried messing around with the system config yet since then, I'll try your suggestion.

One thing of note is that some sites' dropdown boxes are still broken, even with the patches, while everything else has been working fine.

**Comment by dit7ya** [comment]
I don't know what exactly is wrong but I am getting the random flickers on Firefox 93 as well. Has anybody found a solution?

**Comment by jmc-figueira** [comment]
I still get this issue sometimes. It's odd because it's very hit-or-miss for me; restarting Firefox often fixes it, and restarting it again results in it being "broken" again. The same thing happened for a long time with the screenshot tool in Firefox: sometimes it works, sometimes it doesn't, and restarting Firefox sometimes "toggles" if it does or doesn't work. I haven't been able to debug any further, though.

**Comment by dit7ya** [comment]
I think this can be closed as it has been fixed for me since 94 or something.
