### ISSUE TITLE
Update openssl before release

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#13770]
I've recently read this blog post https://www.openssl.org/blog/blog/2016/03/01/an-openssl-users-guide-to-drown/ . Apparently nixos openssl allows SSLv2 (debian has removed it since 2011: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=589706) . 

Release notes from 1.0.1r to 1.0.1s: https://www.openssl.org/news/openssl-1.0.1-notes.html

I hope nobody in this world has SSLv2 enabled in its servers, but perhaps we should consider upgrading to the new openssl.

cc @domenkozar @vcunat

**Comment by peti** [comment]
cdbd14a1a8c40b6ee9d25df8dc65c4e5e6bd9ff7 is in `staging`.

**Comment by lethalman** [comment]
Oh ok sorry... leaving this open until it hits master in case someone else looks it up again.

**Comment by edolstra** [comment]
Staging also bumps the default openssl to 1.0.2, which we still need to cherry-pick to 16.03.

**Comment by edolstra** [comment]
Done in 15db5f4353ee882ab41770f4d61a0bc775824ee7.
