### ISSUE TITLE
fatal error: 'CoreFoundation/CFAttributedString.h' file not found

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#13778]
## Basic info

I was hoping to fix this myself but I haven't come up with anything.

To make sure that we are on the same page:
- Kernel: (run `uname -a`)
  Darwin arda 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.1
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  16.09pre78318.e82dcd7
## Describe your issue here

I think it's related to different versions of the OS X app sources from 10.9 and 10.10 but I'm not 100 on that. I can't figure much out on why it can't find CoreFoundation/CFAttributedString.h which looks like it should be available in 10.9.
### Expected result

No error
### Actual result

This error:

```
In file included from /nix/store/r6mrjh88ycf1b4r4r5bfrb37dr9hz5yl-apple-framework-AppKit/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:
In file included from /nix/store/sap31sxm00cm32xpvb30qbwfgqy3shjc-apple-framework-Foundation/Library/Frameworks/Foundation.framework/Headers/Foundation.h:141:
In file included from /nix/store/sap31sxm00cm32xpvb30qbwfgqy3shjc-apple-framework-Foundation/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:7:
In file included from /nix/store/12fscpjw56h6wljpfmkqaxzi3lgx4ylk-apple-framework-ApplicationServices/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
In file included from /nix/store/fy2xdj37m96kgv2mg6wlf0ycs98b50qq-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CoreText.h:27:
In file included from /nix/store/fy2xdj37m96kgv2mg6wlf0ycs98b50qq-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:22:
In file included from /nix/store/fy2xdj37m96kgv2mg6wlf0ycs98b50qq-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:21:
/nix/store/fy2xdj37m96kgv2mg6wlf0ycs98b50qq-apple-framework-CoreText/Library/Frameworks/CoreText.framework/Headers/CTLine.h:22:10: fatal error: 'CoreFoundation/CFAttributedString.h' file not found
#include <CoreFoundation/CFAttributedString.h>
         ^
1 error generated.
```
### Steps to reproduce

``` sh
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs
git fetch https://github.com/matthewbauer/nixpkgs.git darwin-fixes
git checkout 76748c3aa6d9cf4c4911186e647505f50746f840
nix-build -A allegro
```

**Comment by copumpkin** [comment]
I think we'll need to switch from using the CF (light) up on opensource.apple.com to the CF from [here](https://github.com/apple/swift-corelibs-foundation/blob/master/CoreFoundation/String.subproj/CFAttributedString.c), which seems to have the additional stuff.

cc @pikajude who's also interested in this sort of stuff.

**Comment by aflatter** [comment]
I'm not familiar with the OS X frameworks, but is there anything I can do to help?

**Comment by Mic92** [comment]
is this problem resolved now?

**Comment by matthewbauer** [comment]
I've started to get this issue again.

**Comment by copumpkin** [comment]
I'm at a conference now but still plan to finish my work on the swift-corelibs-foundation thing as soon as I get some downtime.

**Comment by johbo** [comment]
I've seen this issue when trying to build pygtk against a gtk2 with the quartz backend enabled. Was able to workaround it by settings the following preBuild for pygtk:

```
 preBuild = ''
   export NIX_CFLAGS_COMPILE=" -ObjC -F${darwin.cf-private}/Library/Frameworks $NIX_CFLAGS_COMPILE"
 '';
```
The path was already in NIX_CFLAGS_COMPILE when I checked in nix-shell, it seems to me as if the position does matter and makes it work. I first tried out appending to NIX_CFLAGS_COMPILE and that did not change anything.

Thought it might be helpful, since this error looks very similar to what I saw.

**Comment by matthewbauer** [comment]
@johbo I think the issue is that we are providing two versions of CoreFramework.framework. I think we always want cf-private to be after cf.

Do you know if that -ObjC is needed? It seems like it shouldn't be there especially when you're compiling .c files.

**Comment by johbo** [comment]
Oh, the "-ObjC" is specific to my pygtk issue I assume. It's the position of the framework within the list of arguments which seems to matter.

**Comment by johbo** [comment]
Hmm, could it be exact the opposite: That cf-private has to be before CF ?

**Comment by matthewbauer** [comment]
Yeah, so putting cf-private first in the list of inputs does seem to fix the problem. What you have to make sure though is that CoreText is inserted before all other frameworks (that depend on CF).

see: f85fc4bbbff22db848ecc1cf0834c20d6c57cf57
