### ISSUE TITLE
packaging request: hobbits

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#137790]
**Project description**

A multi-platform GUI for bit-based analysis, processing, and visualization.

**Metadata**

* homepage URL: https://mahlet-inc.github.io/
* source URL: https://github.com/Mahlet-Inc/hobbits/
* license: MIT, GPL-3.0 (if building with FFTW3)
* platforms: Linux

**Comment by WolfangAukang** [comment]
[This has been already packaged](https://github.com/NixOS/nixpkgs/commit/6db220afca0e9b085432ce32cbcdc1b96c763c07)
