### ISSUE TITLE
thttpd: update from 2.26 to 2.27

### ISSUE THREAD

**Issue by fsteinel** [NixOS/nixpkgs#13776]
## Basic info

`Linux nixos 3.18.26 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`
`15.09.1119.f6d1666 (Dingo)`
`nix-env (Nix) 1.10`
"15.09.1119.f6d1666"

## Issue

from http://www.acme.com/software/thttpd/#releasenotes
New in version 2.27:

    Stats syslogs changed from LOG_INFO to LOG_NOTICE.
    Use memmove() for self-overlapping string copies instead of strcpy().
    Couple of subroutine name changes for consistency.

**Comment by hrdinka** [comment]
Can we close this in favor of https://github.com/NixOS/nixpkgs/pull/13775?

**Comment by jgillich** [comment]
@hrdinka This is just an issue to accompany the PR I suppose, not that it would've been necessary.

**Comment by joachifm** [comment]
The PR has been merged, closing
