### ISSUE TITLE
Python selinux not in Python path

### ISSUE THREAD

**Issue by mz-pdm** [NixOS/nixpkgs#13787]
## Basic info

To make sure that we are on the same page:

* System: 15.09.1113.23395c4 (Dingo) (applies to nixos-unstable as well)
* Nix version: nix-env (Nix) 1.10 (applies to nixos-unstable as well)
* Nixpkgs version: "15.09.1113.23395c4" (applies to nixos-unstable as well)

## Describe your issue here

While `libselinux' builds working Python bindings for Python, they are not
accessible in Python interpreters.

### Expected result

When I try to `import selinux' in Python interpreters, it imports the module.

### Actual result

When I try to `import selinux' in a Python interpreter, I get
"ImportError: No module named selinux".

### Steps to reproduce

- Run `python'.
- Type `import selinux' and press Enter.

**Comment by FRidh** [comment]
I can import `selinux` just fine.
```
$ nix-shell -p python27Packages.python libselinux -I nixpkgs=https://nixos.org/releases/nixos/15.09/nixos-15.09.1119.f6d1666/nixexprs.tar.xz --run "python -c 'import selinux; print(selinux)'"
<module 'selinux' from '/nix/store/d8m1s1ldyijwz5wid3s96017vz5h0d2n-libselinux-2.4/lib/python2.7/site-packages/selinux/__init__.py'>
```
How did you install `libselinux` and `python`? You will have to use `nix-shell` to get this working. Just installing with `nix-env` or through `environment.systemPackages` won't work with Python.

**Comment by mz-pdm** [comment]
I see. I installed the package by putting it into configuration.nix. Using nix-shell works for me.
Where is the nix-shell workaround documented? I haven't seen it anywhere.

**Comment by FRidh** [comment]
It wasn't clearly in the manual but should be once #13700 is included.

**Comment by FRidh** [comment]
Because this solved your issue I will close this ticket.
