### ISSUE TITLE
neovim 0.5.0 fails to build

### ISSUE THREAD

**Issue by peperunas** [NixOS/nixpkgs#137829]
### Describe the bug
Neovim 0.5.0 fails to build due to incorrect permissions.

### Steps To Reproduce
1. Install `neovim` from `unstable`

### Additional context

```
substituteStream(): WARNING: pattern 'Name=Neovim' doesn't match anything in file '/nix/store/0a1ybbq252b46dzi5g644rfmmkbbblz8-neovim-0.5.0/share/applications/nvim.desktop'
/nix/store/7xdjqpzv0w4pkz8z2hbv8sj98zhy6g7n-hook/nix-support/setup-hook: line 40: /nix/store/s50aclcycg186nigchin5mnlsdfr3lzl-neovim-0.5.0/bin/nvim-python3: Permission denied
```

### Notify maintainers
@Ma27 @manveru @rvolosatovs 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.05.20210906.fd6dba4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210802_47e96bb`
 - channels(root): `"nixos-21.11pre309670.253aecf69ed, home-manager"`
 - channels(giulio): `""`
 - nixpkgs: `/nix/store/gk0xwmhhxb48i2kxlyrsm0vrczjjf6ja-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by rvolosatovs** [comment]
> substituteStream(): WARNING: pattern 'Name=Neovim' doesn't match anything in file '/nix/store/0a1ybbq252b46dzi5g644rfmmkbbblz8-neovim-0.5.0/share/applications/nvim.desktop'
Is very concerning, I don't see how it can fail https://github.com/NixOS/nixpkgs/blob/c50a3bfc4d2d59f2ed5fe55f6c682893599e78f0/pkgs/applications/editors/neovim/wrapper.nix#L58-L59

I cannot reproduce this on 253aecf69ed corresponding to your root channel:
```
git checkout 253aecf69ed && nix run -f . neovim -c nvim -u NONE -c :checkhealth
```

Also not on latest `nixos-unstable`:
```
git checkout upstream/nixpkgs-unstable && git rev-parse HEAD && nix run -f . neovim -c nvim -u NONE -c :checkhealth 
```

My initial feeling was to blame https://github.com/NixOS/nixpkgs/pull/136429, but it does not look like it changed anything that could cause the error and I cannot reproduce the error even with the PR in the tree

So it looks like something is wrong in your environment? Perhaps you have an overlay active?

Did it work before? Is it feasible for you to bisect and figure out which commit broke it?

**Comment by peperunas** [comment]
I am using `neovim` unstable from the `home-manager` module. Could this be the breaker?

**Comment by rvolosatovs** [comment]
I would start with trying `nix run nixpkgs.neovim -c nvim -u NONE -c :checkhealth` (assuming you are on "legacy" `nix`)

**Comment by rvolosatovs** [comment]
Could it be that you specified a custom neovim `package` in `home-manager`? If so, the package is probably invalid.

It looks like something other than unwrapped `neovim` is passed to the wrapper

**Comment by teto** [comment]
`nix build -f channel:nixos-unstable neovim neovim-unwrapped` work fine so it's probably sthg wrong in your config

**Comment by figsoda** [comment]
error message looks like it is trying to wrap a wrapped neovim, what is your config?

**Comment by peperunas** [comment]
I am using `neovim` from `home-manager`, this might be the culprit.

I am modifying the `neovim` package by using the following snippet, nothing more:

```
programs.neovim = {
  enable      = true;
  package = pkgs.unstable.neovim;
}
```

**Comment by figsoda** [comment]
what is `pkgs.unstable`?
if it is nixpkgs, it should probably be `pkgs.unstable.neovim-unwrapped` instead
https://github.com/nix-community/home-manager/blob/959217e51dbd07d0de6dcbddfbfcb4f2efdc0c1e/modules/programs/neovim.nix#L146
setting it to a wrapped neovim will cause double wrapping

**Comment by peperunas** [comment]
Absolutely, that was the issue!

I solved it by setting `package = neovim-unwrapped`.

As a side note, why does neovim need wrapping?

**Comment by figsoda** [comment]
the wrapper allows you to set your init file, adds support for python, node and other languages, and some other stuff
see https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/neovim/wrapper.nix

**Comment by peperunas** [comment]
Awesome, thanks!

**Comment by teto** [comment]
I would prefer if we adopted neovim / neovim-wrapped rather neovim-unwrapped / neovim to avoid that (but unlikely to happen due to backwards compatibility and all). Also the module could check whether package is wrapped or not.
