### ISSUE TITLE
Update pyradio 0.8.7.2 --> 0.8.9.9

### ISSUE THREAD

**Issue by j-steinbach** [NixOS/nixpkgs#137898]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
- [x] I am a noob and tried to fulfill the above requirements to the best of my abilities and understanding of github

###### Project name
`nix search` name: pyradio

current version: 0.8.7.2
desired version: 0.8.9.9
at least 0.8.8.5 (last of 0.8.8 chain)

###### Notify maintainers

maintainers: @contrun 

###### Note for maintainers

Please tag this issue in your PR.

-----

The current version (0.8.7.2) is crashing for me when increasing/decreasing the volume. (Fixed in 0.8.8)

The newest 0.8.9 versions feature a radio-browser-overlay, which would be very nice.

**Comment by prusnak** [comment]
PR in https://github.com/NixOS/nixpkgs/pull/137907
