### ISSUE TITLE
(Organisation) Separate/clean the pkgs/application/radio section

### ISSUE THREAD

**Issue by j-steinbach** [NixOS/nixpkgs#137905]
The [radio-section](https://github.com/NixOS/nixpkgs/tree/nixos-21.05/pkgs/applications/radio) contains both radio communication software (for signal processing / software radio, e.g [GNU radio](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/applications/radio/gnuradio/default.nix) [website](https://www.gnuradio.org/about/)) and internet music radio-players (e.g. [pyradio)](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/applications/radio/pyradio/default.nix).

These belong to separate domains (hobbyist vs. end-user) and should therefore be separated. I believe it would make sense to put all the music radio players into the *audio* folder, as it already contains a few radio-players (e.g. [shortwave](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/applications/audio/shortwave/default.nix), which --confusingly-- is also the name of a commonly used radio communication frequency)

----

I would be willing to sift through the section and find all misplaced packages, but I don't know how to work with github and create pull requests.. :innocent:

**Comment by Artturin** [comment]
> I would be willing to sift through the section and find all misplaced packages, but I don't know how to work with github and create pull requests.. 😇


http://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/

**Comment by j-steinbach** [comment]
Thank you! That looks like a good explanatory guide. I guess that leaves me with no choice to get my hands dirty then.

(Might take me a while to get started, so only ping me if you didn't hear from in a week.)
----

As for why I couldn't search for this guide myself?.. I guess there simply is a difference between being lost  and having to find guidance yourself and getting a peer-reviewed recommendation.

**Comment by j-steinbach** [comment]
Hey @Artturin, I created a pull request -- would you be willing to take a look? https://github.com/NixOS/nixpkgs/pull/138414
