### ISSUE TITLE
mitscheme doesn't work (probably FHS problems)

### ISSUE THREAD

**Issue by arcticlimer** [NixOS/nixpkgs#137916]
### Describe the bug
mit-scheme errors out when trying to invoking its binary.

### Steps To Reproduce
1. Install pkgs.mitscheme from nixpkgs master
2. Run it with `scheme` or `mit-scheme`

### Additional context
Error log
```
❯ mit-scheme
mit-scheme: can't find a readable default for option --band.
        searched for file all.com in these directories:
        /usr/local/lib/mit-scheme-x86-64-11.2

Inconsistency detected.
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.63, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
mitscheme has no maintaner :(

**Comment by Artturin** [comment]
#137950
