### ISSUE TITLE
Haskell support '--profiling-detail` and `--library-profiling-detail'

### ISSUE THREAD

**Issue by NerdGGuy** [NixOS/nixpkgs#13798]
Cabal looks to have some new options in 1.24 that would be nice to support. Maybe we could even provide backwards comparability?

https://github.com/haskell/cabal/commit/b778e5f925ac9e3a88ac44610c88ca343f23ccce

Do we have options around setting the profiling details already?

**Comment by Profpatsch** [comment]
ping @peti, maybe this has been implemented since?

**Comment by peti** [comment]
The `profilingDetail` attribute controls this setting. If unset, the default is `profilingDetail = "all-functions"`.
