### ISSUE TITLE
openjdk 17

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#137956]
**Project description**
Next LTS release of openjdk / java.

(I think it would be nice to have a new package alias `jdk-lts`.)

**Metadata**

* homepage URL: https://openjdk.java.net/
* source URL: https://github.com/openjdk/jdk17u
* license: gpl2 with classpath exception
* platforms: unix, linux, darwin

**Comment by asbachb** [comment]
I've some work in progress of packaging `jtreg` in order to test the jdk build: https://github.com/asbachb/nixpkgs/tree/jtreg

**Comment by tadfisher** [comment]
Aliases aren't great, as updating nixpkgs would mean (in this case) going from JDK 11 to JDK 17, which is likely to break something. We already have `openjdk${version}` attrs which can be used to "pin" to a specific JDK release.

**Comment by asbachb** [comment]
We already had some discussion about that: https://discourse.nixos.org/t/retirement-of-old-openjdk-releases/9929

I still think that the best approach would be that the default jdk should point to the lts release or have a dedicated alias for that.

**Comment by Uthar** [comment]
To start off, this builds and works fine https://github.com/Uthar/nixpkgs/commit/f9bd12e59cccdbfac95096ca61697252c07e017b, some notes:
- Can't run tests because jtreg isn't packaged (https://github.com/asbachb/nixpkgs/tree/jtreg
- Can't build docs because it fails with `error: unknown tag: textarea`
- Haven't built the case with no adoptopenjdk as bootstrap, but the derivation itself compiles just fine with the `if` removed.
- Worked around bizarre error in `LegalNoticeFilePlugin` by patching out the failing check

**Comment by asbachb** [comment]
Just fyi: I did not package `jtrg` yet as I'm currently unable to validate any jdk build due to any errors. I think in this state it won't provide any benefit.

**Comment by Uthar** [comment]
Hmm... I'm not sure if older jdks in nixpkgs run tests either. E.g. this [openjdk16 build](https://hydra.nixos.org/log/8w4mq3cywn4gbv7qapdfw5agh7krdl6c-openjdk-16+36.drv) looks like it builds the testst but doesn't run them - there's not "X tests passed" or anything like that.

Same for javadoc - older jdks dont include them as well

**Comment by asbachb** [comment]
Normally other distros package javadoc separately. Yeah currently there are no tests. That was the reason I tried to package `jtreg`.

**Comment by Uthar** [comment]
Also, the`docs` target fails only during building javadoc for JavaFX, I tried also with JavaFX 17.0.0.1, but no change. Weird. (Works with enableJavaFx = false)

Also, to build JavaFX 17 i had to set COMPILE_WEBKIT=false in gradle, if someone ever has this problem

I guess this isnt so important now and just building the `images` target is good enough, so I started the PR

**Comment by tadfisher** [comment]
This can be closed, correct?

**Comment by xfix** [comment]
Closed by #140257.
