### ISSUE TITLE
semgrep

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#138018]
**Project description**

Semgrep is a fast, open-source, static analysis tool for finding bugs and enforcing code standards at editor, commit, and CI time.

**Metadata**

* homepage URL: https://semgrep.dev/
* source URL: https://github.com/returntocorp/semgrep
* license: lgpl-2.1
* platforms: Linux (but possibly others as well, because it is mostly Python code)

**Comment by jmgilman** [comment]
I started attempting this package, however, I'm not at all familiar with OCaml or Dune. Would love some help getting the [semgrep_core](https://github.com/returntocorp/semgrep/tree/v0.92.1/semgrep-core) binary packaged.

**Comment by 06kellyjac** [comment]
I tried building semgrep_core from src and the first level works ok with the dune builder but pfff needed opam packgemanager and also there's copious amounts of git submodules that cause issues with purity
