### ISSUE TITLE
coc-nvim (and other plugins in NeoVim) not working after latest update on unstable

### ISSUE THREAD

**Issue by rollschild** [NixOS/nixpkgs#138084]
## Issue description

i just did a latest upgrade on unstable channel using `nixos-rebuild switch --upgrade`, however after the upgrade looks like all plugins in NeoVim stopped working, especially coc-nvim. Now when I open up a file using `nvim`, I would just get a bare bones nvim setup without the effect of any plugins and below is the error messages I got by looking at `:messages`

```
E117: Unknown function: SyntasticStatuslineFlag
E15: Invalid expression: SyntasticStatuslineFlag()                                                                                                                              
E117: Unknown function: coc#status
Press ENTER or type command to continue
E15: Invalid expression: coc#status()
:messages
E117: Unknown function: SyntasticStatuslineFlag
E15: Invalid expression: SyntasticStatuslineFlag()
E117: Unknown function: coc#status
E15: Invalid expression: coc#status()
```

Anyone experiencing the same issue? Thank you so much in advance!
## Technical details
NixOS:
```
nix-shell -p nix-info --run "nix-info -m"                                                                                                               INT ✘ 
these paths will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/xq77wmzk8d306anyk9rsvl4i4h7ihchw-bash-interactive-4.4-p23-dev
copying path '/nix/store/xq77wmzk8d306anyk9rsvl4i4h7ihchw-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.63, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(rollschild): `""`
 - channels(root): `"nixos-21.11pre314557.364b5555ee0, nixpkgs-21.11pre293858.141b2b111d7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

neovim:
```
nvim --version                                                                                                                                              ✔ 
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/fnm4s9zf4g3mdb3cdhipcf7a2rrakv9x-neovim-unwrapped-0.5.0/share/nvim
"
```

**Comment by teto** [comment]
probably linked to https://github.com/NixOS/nixpkgs/pull/136429 . Could you share your nix config ? exact commit version ? and ideally a working example in neovim/tests.nix . Do you use nix plug interface ?

**Comment by rollschild** [comment]
Hi, thanks for your reply. I use a single `configuration.nix` which is pretty nasty and long, but I will try to post something here. 

I did simplify the neovim portion of the `configuration.nix` and try to generate some examples. Interestingly/weirdly, I found out that `coc-nvim` cannot co-exist with any other plugins.

This works - meaning there are actions such as `:CocConfig`, which means at least Coc is working
```
with import <nixpkgs> {};
 
neovim.override {
    configure = {
            # Use the default plugin list shipped with nixpkgs
            plug.plugins = with pkgs.vimPlugins; [
               coc-nvim
            ];
    };
}
```

However, coc-nvim would stop working even if there's only one other plugin (actions like `:CocConfig` not found):
```
with import <nixpkgs> {};
 
neovim.override {
    configure = {
            # Use the default plugin list shipped with nixpkgs
            plug.plugins = with pkgs.vimPlugins; [
               coc-nvim
               gruvbox
            ];
    };
}
```

Plus, when doing `:PlugUpdate` it said no plugins found. I don't know if it's normal though because I never updated plugins this way. I always update everything using the `nixos-rebuild` command. So I suspect that there are issues either with `coc-nvim` or with `vim-plug` itself. 

Hopefully this makes some sense. Thanks!

**Comment by rollschild** [comment]
@teto And I'm not using home manager, just a single configuration file. The example above I made a separate `vim.nix` file and did this:
```
(import ./vim.nix)
```
for demo purposes.

**Comment by rollschild** [comment]
As for the commit version, since I'm using the unstable channel, is it safe to assume it's the latest commit? Please correct me if I'm wrong.

**Comment by SenchoPens** [comment]
Hi, have the same issue. I use nixpkgs and home-manager following the 21.05 branches, also I have nixpkgs-unstable as an overlay, which I use as a source of all vim plugins I use in my NeoVim config, except `jabs` and `lualine`, which I build with `vimUtils.buildVimPlugin`. 3 hours ago I updated all of the inputs of my flake config. After the update, all of the plugins, except `jabs` and `lualine`, disappeard from NeoVim runtime path. Then I switched to stable nixpkgs as the plugin source, and they appeared again.

**Comment by teto** [comment]
there seems to be an issue with vim-plug  but for instance when I run `nix-build -A neovim.tests.run_nvim_with_plug` on https://github.com/NixOS/nixpkgs/pull/137885 , it seems to work fine and the generated vimrc looks ok. I will try with coc-nvim to see if there is a difference.

Until then, you can use vim's native "plugin manager" aka packpath with:
```
neovim.override {
    configure = {
            # Use the default plugin list shipped with nixpkgs
            packages.myPackageDir.plugins = with pkgs.vimPlugins; [
               coc-nvim
               gruvbox
            ];
    };
}
```

**Comment by SenchoPens** [comment]
Oh, sorry, turns out I do not have the exact problem - I do not use plug, I list my plugins in a home-manager neovim option `plugins`. I updated nixpkgs to master and the issue persists.

**Comment by SenchoPens** [comment]
I didn't notice that the fix-vim-plug wasn't merged into master, so I updated nixpkgs to teto/fix-vim-plug and the issue persists.

**Comment by teto** [comment]
I merged that MR but indeed it does not fix the vim-plug issue. I've tried starting the binary built with
```
neovim.override {
    configure = {
            # Use the default plugin list shipped with nixpkgs
            plug.plugins = with pkgs.vimPlugins; [
               coc-nvim
               gruvbox
            ];
    };
}
```
and I see `[coc.nvim] "node" is not executable, checkout https://nodejs.org/en/download/(B` which looks correct since the wrapper has `withNodeJs ? false` as default and there doesn't seem to be any override to provide node when installing coc-nvim anyway.

**Comment by teto** [comment]
@SenchoPens if you use unstable just to build the vimPlugins, but home-manager uses another nixpkgs, there is a mismatch to generate the packdir that could explain the issue.
