### ISSUE TITLE
RStudio is missing most of the text in the main interface

### ISSUE THREAD

**Issue by Dettorer** [NixOS/nixpkgs#138134]
### Describe the bug
RStudio is missing most of the text from its UI (see screenshots), the text one being displayed is in the top menu bar. Icons are displayed correctly though.

### Steps To Reproduce
1. bring `rstudio` or `rstudioWrapper` to the environment (for example `nix-shell -p rstudio`)
2. start `rstudio`

### Expected behavior
The main interface starts in a new window with version information in the left pane, environment information in the top-right pane, and filesystem overview (with file and folder names and not only a logo to represent them)

### Screenshots
What I observe: ![nixpkgs' RStudio with almost no text displaying](https://user-images.githubusercontent.com/2761682/133613583-3932e065-f8b0-48de-97a3-5f0bbfc735cb.png)

Expected (here taken from archlinux's rstudio package) : ![archlinux's RStudio with expected UI](https://user-images.githubusercontent.com/2761682/133613658-ff5d4786-3bcc-4f21-a936-e38fff158d49.png)

### Notify maintainers
@ehmry @changlinli @ciil 

### Metadata
```console
[dettorer@rivamar:~]$ nix-shell -p nix-info --run "nix-info -m"                                                                                              ─╯
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(dettorer): `"nixos-21.11pre314557.364b5555ee0"`
 - channels(root): `"nixos-21.11pre314557.364b5555ee0, nixpkgs-21.11pre314682.65b70fbe4c3"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Dettorer** [comment]
Confirmed, fixed on my side, thank you!

**Comment by TheSirC** [comment]
I also have this issue and the PR does *not* solve it... Please let me know what information I can provide to help you in debugging.

# Output of `rstudio`
```
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.
```

# Output of `nix-info -m`
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.142, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre318500.51bcdc4cdaa, home-manager, nix-ld"`
 - channels(sirc): `"home-manager, nixpkgs-21.11pre308613.fd9984fd9a9"`
 - nixpkgs: `/home/sirc/.nix-defexpr/channels/nixpkgs`
```

**Comment by Artturin** [comment]
```grep qtbase $(which rstudio)```

**Comment by TheSirC** [comment]
Please just forget about it  : my pinned version was not building the new version that you packaged. Thank you for your help !
