### ISSUE TITLE
python3Packages.pyscf is broken

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nixpkgs#138127]
### Describe the bug
PySCF fails to build (https://hydra.nixos.org/build/153122618). I am suspecting the h5py update (7c1310f206f22a73434d0407ce4e0722f260a9e7)

### Notify maintainers
CC @sheepforce

**Comment by sheepforce** [comment]
I am afraid this a known problem on PySCF side https://github.com/pyscf/pyscf/issues/1003. It is fixed in the alpha releases of PySCF. I will have a look if a backport of the h5py fix is doable.
