### ISSUE TITLE
add kde5.kdenlive again

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#13820]
it was present in NixOS 15.09 in Version 15.04, now it's gone completely

added in  https://github.com/NixOS/nixpkgs/commit/5b640cd1a58e336073258162ada9f793519c2e4e#diff-38d7d08a4bd041e60696a477481afa3d

@ttuegel @viric
### Expected result

be able to install Kdenlive 15.12
source is already there: https://github.com/NixOS/nixpkgs/blob/6a4c8b0a12e9a2508f049434a9b302c108a62a40/pkgs/desktops/kde-5/applications-15.12/srcs.nix#L925
### Actual result

```
$ nix-env -iA nixos.kde5.kdenlive
error: attribute ‘kdenlive’ in selection path ‘nixos.kde5.kdenlive’ not found
```

**Comment by ttuegel** [comment]
@cillianderoiste @viric Will you be able to update Kdenlive for the 16.03 release?

**Comment by domenkozar** [comment]
I'll leave this for 16.03, hopefully someone picks it up.

**Comment by viric** [comment]
I have no idea how the kde5 stuff works

**Comment by viric** [comment]
I'm working on it, but I cannot make file dialogs work. It complains about not being able to communicate with klauncher5

**Comment by viric** [comment]
Sorry, the problem appears in the "Add clip" file dialog, instead of just "Open":

couldn't create slave: "No s'ha pogut comunicar amb el klauncher: The name org.kde.klauncher5 was not provided by any .service files"

**Comment by viric** [comment]
I guess the next lines are more relevant:

KServiceTypeTrader: serviceType "ThumbCreator" not found

So I have to find the thumbcreator service.

**Comment by viric** [comment]
If I add kinit/bin to PATH, it works. Shouldn't this be handled by some wrapper?

**Comment by viric** [comment]
I pushed kdenlive for kde5 (15.12) to release-16.03.

**Comment by vcunat** [comment]
Heh, a paradoxical situation where we have newer stuff only in older release :-) Ref: 1ec1a7c71f.

**Comment by viric** [comment]
Thank you for the ref! Definitely I tried to make master work, but I failed. The program crashes there. So here it goes for 16.03.

**Comment by viric** [comment]
I managed to get it starting fine, but I'm stopped again at "Add clip", that triggers:

couldn't create slave: "Unable to create io-slave:\nklauncher said: Protocol desconegut ?file?.\n"

------

AH!!! It's the kinit-libpath.patch !! It picks NIX_PROFILES env var to find libs. grrrrr

**Comment by viric** [comment]
Ah, right, NIX_PROFILES seems to solve all for me.

I can run it in master this way:
NIX_PROFILES=/nix/store/hrc9l5pj2p7xfqilslpaxy4a2gp6q7rs-kde-env-kdenlive-16.04.3 result/bin/kdenlive

Not very nice. I guess the kde pieces are meant only for nixos kde users, not non-kde users that want to run kde programs.

**Comment by viric** [comment]
I pushed it in 2045b40b1061f24e9a51e1f312c9d9e131b8b43b . I guess that normal kde desktop users will be able to run it without NIX_PROFILES tricks.

**Comment by domenkozar** [comment]
What's the status of this?

**Comment by vcunat** [comment]
Hydra only builds it for 16.03 (which is likely to die in a couple months).
