### ISSUE TITLE
python: vivisect not working for python3

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#138272]
### Describe the bug

The vivisect python module is currently disabled for Python 3:

```
  disabled = isPy3k;
```

while the website indicates that the latest version should be fine for Python 3:

```
 As of v1.0.0, vivisect/vdb/vstruct are all python3 compatible.
```
vivisect is a dependency for other packages like flare-floss.

### Additional context
i found that one of the dependencies of vivisect is cxxfilt (another python module). Currently that is in nixpkgs as 0.3.0, even though this is not an official release (the cxxfilt changelog in README.rst mentions it, but the python setup.py scripts and other scripts do not). vivisect has an explicit check for the cxxfilt version number.

### Notify maintainers
@cole-h @grahamc @mweinelt

**Comment by mweinelt** [comment]
Looks like I could just relax the cxxfilt constraint on the package and it started building again. Needs some testing still.
