### ISSUE TITLE
Package request: jdk17

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#138273]
**Project description**
openjdk 17 is General Availability now.

**Metadata**

* homepage URL: https://openjdk.java.net/projects/jdk/17/
* source URL: https://github.com/openjdk/jdk
* license: gpl2
* platforms: unix, linux, darwin, ...

**Comment by wamserma** [comment]
Closing as duplicate of https://github.com/NixOS/nixpkgs/issues/137956
