### ISSUE TITLE
Failures to build with remote builders (aborted)

### ISSUE THREAD

**Issue by jasoncarr0** [NixOS/nixpkgs#138369]
### Describe the bug
This is very tough to pin down, so it may be caused by other components: When trying to build steam using the most recent version of NixOS, it would run on a remote builder. At a seemingly arbitrary time during the build, it would fail with the following line:

builder for '/nix/store/njf5cp889cvbh56y6fr9zcdsk3cr3v0k-steam-original-1.0.0.70.drv' failed due to signal 6 (Aborted)

This was always the best granularity of the error, but it would happen at a random time during the build. I was able to get it to build successfully via blocking access to remote builders. It's possible that it is nvidia-related: I have a remote builder without nvidia, for a machine that is using nvidia.

### Steps To Reproduce
1. Set up a remote builder, possibly one with different hardware ()
2. Build steam on a recent version of nixpkgs
3. Observe failure

### Expected behavior
The build succeeded just as it would locally

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.19-zen2, NixOS, 21.11pre304626.8ecc61c91a5 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.14`
 - channels(root): `"nixos-21.11pre316472.47eaf6727bd, unstable"`
 - channels(jason): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

 Also, remote builder:
```console
$ nix-shell -p nix-info --run "nix-info -m"
  - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.11pre305786.aaf9676fbb7 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - channels(root): `"nixos-21.11pre305786.aaf9676fbb7, nixpkgs-21.05.1987.16bf3980bfa, unstable-21.11pre304626.8ecc61c91a5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: steam
# a list of nixos modules affected by the problem
module:
```

**Comment by jasoncarr0** [comment]
I was able to run into this on a seemingly unrelated package, so this is likely a bug somewhere else

**Comment by veprbl** [comment]
You might want to file this to https://github.com/NixOS/Nix/issues instead

**Comment by jasoncarr0** [comment]
Fair point @veprbl and remarkably pointed timing as I was just looking at this and the same

**Comment by jasoncarr0** [comment]
In this case at first I thought it was a steam issue but it turned out to affect multiple packages so it's pointing to being nix then
