### ISSUE TITLE
Update nodePackages.vscode-*-languageserver

### ISSUE THREAD

**Issue by jlesquembre** [NixOS/nixpkgs#138301]
Currently, we don't have any up-to-date language server for CSS, HTML nor json. We have the following on nixpkgs:
- nodePackages.vscode-json-languageserver
- nodePackages.vscode-json-languageserver-bin
- nodePackages.vscode-html-languageserver-bin
- nodePackages.vscode-css-languageserver-bin

But those are unmaintained old versions. Unfortunately, Microsoft distributes those as part of vscode, as far as I know, there is no standalone version. I propose to remove the previously mentioned packages and create new ones extracting the source directly from vscode.

As a starting point, anyone interested can use this derivation from my dotfiles:
https://github.com/jlesquembre/dotfiles/blob/16577a7afa17c090eeef6c9b2ce99e1e763bd1ca/overlays/pkgs/vscode-ls/default.nix

I don't plan to work on this any time soon, but I thought it'd be nice to put the information here for other people.

**Comment by Lord-Valen** [comment]
`vscode-langservers-extracted` does this.
