### ISSUE TITLE
Popups are broken in Jetbrains applications

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#138310]
Currently all the IDE popups are broken in unstable, here is the relevant JB ticket: https://youtrack.jetbrains.com/issue/IDEA-277041

Seems like something is wrong with JCEF in current jetbrains-jdk version.

I'll try to bump it and check if it helps.

**Comment by pshirshov** [comment]
This does NOT help:

```
  version = "11_0_12-b1504.28";
  src = fetchFromGitHub {
    owner = "JetBrains";
    repo = "JetBrainsRuntime";
    rev = "jb${version}";
    sha256 = "ZscfPzhbjCY/veXP4e7ICd043Lsqs3FSdvFHWXSJgg8=";
  };
```

**Comment by pshirshov** [comment]
This doesn't help either:

```
  version = "11_0_12-b1504.27";
  src = fetchFromGitHub {
    owner = "JetBrains";
    repo = "JetBrainsRuntime";
    rev = "jb${version}";
    sha256 = "+0AYGMoXQux+vqD/hZ9SDargOK2yM99G4YAdupQGBT8=";
  };
```

**Comment by pshirshov** [comment]
Same for this:

```
  version = "11_0_12-b1661";
  src = fetchFromGitHub {
    owner = "JetBrains";
    repo = "JetBrainsRuntime";
    rev = "jb${version}";
    sha256 = "9xrqzTYVHcQpdhTqkDVZCPmObp917/soiC4uFigaGu0=";
  };
```

I'm kinda out of ideas.

**Comment by pshirshov** [comment]
Neither it helps to downgrade JDK to the version from 21.05:

```
  version = "11.0.10-b1427";
  src = fetchFromGitHub {
    owner = "JetBrains";
    repo = "JetBrainsRuntime";
    rev = "jb${version}";
    sha256 = "sha256-2cn+FiFfGpp7CBeQMAASVZwTm6DOFaXaWxAL/nVC2Nk=";
  };
```

**Comment by pshirshov** [comment]
It helps to downgrade IDEA. I can't get `2021.2.1` version working.

**Comment by SebTM** [comment]
> It helps to downgrade IDEA. I can't get `2021.2.1` version working. `2021.2.2` doesn't work too.
> 
> Maybe we should downgrade to `2021.2` until JB fixes their stuff?..

Hey, I've tested it and can confirm that it's also occurring on my system. I didn't noticed it while the upgrade and think we should go back as you suggested until Jetbrains get's their things back to working :)

**Comment by pshirshov** [comment]
For now I've solved my problem by manual downgrade:

```
  nixpkgs = {
    overlays = [
      (self: super: {
        old-idea = pkgs.jetbrains.idea-ultimate.overrideDerivation
          (old: {
            name = "idea-ultimate-2021.2";
            src = pkgs.fetchurl {
              url = "https://download.jetbrains.com/idea/ideaIU-2021.2-no-jbr.tar.gz";
              sha256 = "0gbx1ngf8i2a0dvysw5g0ikakq4a7gghb4rjk7c99jwzwq9hckjm"; 
            };
          });
      })
    ];
```

Though, probably, it should be done in nixpkgs for all the `jetbrains.*` packages.

**Comment by SebTM** [comment]
If you were affected by the issue, could you please test #170936 ? This should update all editors and the jdk. Tested with phpstorm.

**Comment by pshirshov** [comment]
At this point everything seems to be alright with jetbrains IDEs in master/unstable branches
