### ISSUE TITLE
python39Packages.nbval fails build/test: 

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#138338]
`python39Packages.nbval` fails build as: https://hydra.nixos.org/build/153067249

```
__________________________ test_ignore.ipynb::Cell 1 ___________________________
Notebook cell execution failed
Cell 1: Cell outputs differ

Input:
sys.stdout.write('test\n')

Traceback:
Unexpected output fields from running code: {'text/plain'}
```

### Notify maintainers

@costrouc 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python39Packages.nbval
```

**Comment by trofi** [comment]
Closing as INVALID

**Comment by VergeDX** [comment]
@trofi Still broken, why INVALID...?

**Comment by trofi** [comment]
From what I understood (from other issues) the issues related to regressions need to be reported as comments to the PRs that introduce regressions. And maintainers are not normally expected to deal with them. Thus most of my reports against already failing packages are not acted on.

I don't have the time to debug or fix each of them myself. Hence the INVALID (as in invalid process of getting it fixed).

**Comment by VergeDX** [comment]
Thanks for replay, I'm trying to fix this : )
