### ISSUE TITLE
python39Packages.ansible-runner fails build/test: === 91 failed, 1837 passed

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#138381]
`python39Packages.ansible-runner` fails build as: https://hydra.nixos.org/build/153550048

```
...
=== 91 failed, 1837 passed, 18 skipped, 52 deselected, 2 warnings in 12.38s ====
```

### Notify maintainers

@costrouc 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: python39Packages.ansible-runner
```

**Comment by trofi** [comment]
Closing as INVALID

**Comment by contrun** [comment]
I tried to build `python39Packages.ansible-runner` with the latest master commit. The tests still fail. Why is this issue closed as invalid?

**Comment by trofi** [comment]
From what I understood (from other issues) the issues related to regressions need to be reported as comments to the PRs that introduce regressions. And maintainers are not normally expected to deal with them. Thus most of my reports against already failing packages are not acted on.

I don't have the time to debug or fix each of them myself. Hence the INVALID (as in invalid process of getting it fixed).
