### ISSUE TITLE
Typora

### ISSUE THREAD

**Issue by timothee-haudebourg** [NixOS/nixpkgs#138329]
Typora has been removed by #137425 with the message "Newer versions of typora use anti-user encryption and refuse to start. As such it has been removed.". @SuperSandro2000 can we have a bit more details/motivation about why it has been removed? What do you mean by "anti-user encryption"? Why does it refuses to start? I don't see any issue discussing that.

**Comment by SuperSandro2000** [comment]
> Why does it refuses to start?

Because they encrypt the node.asar file and put an anti tamper protection into it. If you can circumvent it feel free to re-add it.

**Comment by oxalica** [comment]
Note that [typora 1.0](https://support.typora.io/What's-New-1.0/) is released and it now need to buy a license to use.

**Comment by abathur** [comment]
Closing since it seems like the question was answered and this doesn't seem to be actionable, but I'm happy to reopen if I'm mistaken.
