### ISSUE TITLE
writeResholve and writeResholveBin

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#138442]
I often end up using [`writeShellScript` and `writeShellScriptBin`](https://github.com/NixOS/nixpkgs/blob/325b91c372a5984fd783e443b2b01ce7409c7ad4/pkgs/build-support/trivial-builders.nix#L200-L250) for adhoc scripts in my NixOS config or even for quick tools in packages. I thought it would be useful to have `writeResholve` and `writeResholveBin`. I started writing these out but ran into a couple of problems with reusing the current `resholvePackage` framework.

- Requires a `version` which is annoying for this kind of thing.
- Doesn't support a top-level output.

I got the following very quick prototype working, but it would be hard to extend this to `writeResholve` due to the second point above.

```nix
writeResholveBin =
	pname:
	{
		version ? "none",

		fake ? { external = []; },
		inputs ? [],
		interpreter ? "${pkgs.zsh}/bin/zsh",
	}:
	script: pkgs.resholvePackage {
		inherit pname version;

		src = null;
		dontUnpack = true;

		solutions = {
			default = {
				scripts = [ "bin/${pname}" ];
				inherit fake inputs interpreter;
			};
		};

		installPhase = ''
			install -D ${
				pkgs.writeText
					"${pname}-pre-resholve"
					"#!${interpreter}\n${script}"
			} $out/bin/${pname}
		'';
	};
```

I wonder if it would be possible to extract a simple function that takes a derivation and applies resholve solutions to the specified paths. This would allow easily mapping to either the top-level or bin directory case.

cc @abathur

**Comment by abathur** [comment]
Thanks for poking at this. I know there's demand for them but haven't had the bandwidth + a good use-case to drive decisions.

I've assumed we'd need to extract the input-validation and invocation-building functions from resholvePackage, so that it's easier to re-combine them to support other uses.

I'll take a look at that shortly, and hopefully be able to report back with a new branch in the resholve repo.

**Comment by kevincox** [comment]
Thanks. I understand that your are busy but I figured that starting the discussion to collect the use cases would be useful. In my case the most common use case is. `systemd.services.foo.serviceConfig.ExecStart = pkgs.writeResholveBin "foo" { ... } '' echo "Hello" ''`

**Comment by abathur** [comment]
No worries. This is pretty good timing. I finally finished the next resholve release and PRed it to nixpkgs this week (#138080), so I've got a few more brain cells to rub together.

I've pushed a stub/draft of this behavior up at https://github.com/abathur/resholve/compare/extract_nix_support_funcs and left comments on the parts that I'm not sure about on the commit: https://github.com/abathur/resholve/commit/1e98669761ecb0d0741a6da0f73c8988b3b5497d 

If you see reasons to hack on it, you can clone it and (hopefully) re-run the tests with `make ci` from the root. If you don't, you should be able to overlay it in to test with something along these lines:

```nix
# pkgs/resholve/default.nix
{ callPackage, lib, fetchFromGitHub }:
let
  src = fetchFromGitHub {
    owner = "abathur";
    repo = "resholve";
    rev = "3a69605d59ad621439c6b058d7b7ac3c0f60f9de";
    hash = "sha256-ptl5MJL7jk8jaOGB6SKBVFm3mypUUsL9T9y9nua0Zn0=";
  };
in callPackage src {}
```

```nix
# packages.nix
inherit (self.callPackage ../pkgs/resholve { })
    resholve resholvePackage resholveScript resholveScriptBin;
```

**Comment by kevincox** [comment]
Thanks, that looks exactly like what I was thinking. I had some nits on the implementation itself but the functionality looked good. One missing feature is allowing to specify our own shell. Since users of resholve are likely writing "real" scripts it would be nice if they could pick the shell that they want to do it in.

**Comment by abathur** [comment]
> Since users of resholve are likely writing "real" scripts it would be nice if they could pick the shell that they want to do it in.

This kind of thing is why I was waiting for real use-cases! :)

I've pushed another commit to that branch with tweaks addressing most of the nits.

**Comment by kevincox** [comment]
Thanks, the new version looks really good. The only think I would change is merge the name into the second argument but I do see that is now mixing random values into the "solution" object and it is more of an stylistic preference anyways.

**Comment by abathur** [comment]
I'm a goober and missed the all-packages inherits for these; they should *actually* be present after #140099
