### ISSUE TITLE
Package Request:  sysz - an fzf terminal UI for systemctl

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#138472]
**Project description**

A terminal UI utility for using systemctl interactively via fzf.

**Metadata**

* homepage URL: https://github.com/joehillen/sysz
* source URL: https://github.com/joehillen/sysz
* license: Unlicense
* platforms: linux, darwin

**Comment by thbkrshw** [comment]
Submitted a PR #138507
