### ISSUE TITLE
nixops doesn't build

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#138584]
### Describe the bug

nixops doesn't build.

### Steps To Reproduce
`nix-build -A nixops`

```
error: brotlicffi-1.0.9.2 not supported for interpreter python2.7
(use '--show-trace' to show detailed location information)
```

### Notify maintainers

@adisbladis @AmineChikhaoui @edolstra @rob @domenkozar

**Comment by roberth** [comment]
@ryantm wrong eelco. Use @edolstra

**Comment by roberth** [comment]
@FRidh is it feasible to keep nixops 1.x buildable, which requires python 2.7?

**Comment by FRidh** [comment]
I'm not very active anymore in Nixpkgs so best ask some other Python maintainers. It is labor intensive to keep these packages available, frustrating contributors.

**Comment by roberth** [comment]
Thanks @FRidh, that answers it for me.
Effort is better spent on making NixOps 2 release worthy. NixOps 1 is not sustainable.

**Comment by roberth** [comment]
I've started a fund for NixOps maintenance on OpenCollective, because NixOps 1 is not sustainable. Please contribute if you or your company can, and spread the word. Especially recurring contributions are highly appreciated. A NixOps 2 release is the main priority, but the fund can cover other deployment tech as well.
Let's do this!

https://opencollective.com/nix-deployments

**Comment by jerith666** [comment]
Thanks for setting that up!  FWIW I did just open #139986 to fix this particular rebuild issue though.  (Posting explicitly b/c I'm pretty sure GH doesn't automatically notify participants when a PR fixing an issue is opened.)

**Comment by JanCVanB** [comment]
@roberth @jerith666 On a fresh installation of Nix on MacOS, when I run `nix-shell -p nixops` I get `error: brotlicffi-1.0.9.2 not supported for interpreter python2.7`. Is there something I need to do to get the fix from #139986? I'm new to Nix & NixOps, so any help is appreciated! :)

**Comment by jerith666** [comment]
The fix from #139986 is 44c267f9542df775af23836b881ee0e6697467f4.  So you can ask `nix-shell` to use that exact revision of nixpkgs to provide the instructions for building the `nixops` package that you've asked it for, like so:

```
nix-shell -p nixops -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/44c267f9542df775af23836b881ee0e6697467f4.tar.gz
```

Fair warning that, depending on how much of nixops's pre-requisites from that exact commit have been built & cached by hydra, you may have to wait for quite a lot of local builds before that command completes.  But of course they'll be cached in your `/nix/store` after that first run.

**Comment by JanCVanB** [comment]
@jerith666 Thank you! Unfortunately, I get this error when I run that (even after running `nix-collect-garbage`):

`error: executing SQLite statement 'insert or replace into Cache(input, info, path, immutable, timestamp) values ('{"name":"source","type":"file","url":"https://github.com/NixOS/nixpkgs/archive/44c267f9542df775af23836b881ee0e6697467f4.tar.gz"}', '{"etag":"\"8a5a976a61b5d4b8cc460c95437f1a8f80fad6eefb33db5e420ba4e4bb2f60eb\"","url":"https://codeload.github.com/NixOS/nixpkgs/tar.gz/44c267f9542df775af23836b881ee0e6697467f4"}', '/nix/store/ggzflbykwq4ypawyrlr23fb885ndxfwx-source', 0, 1636062556)': attempt to write a readonly database (in '/Users/jan/.cache/nix/fetcher-cache-v1.sqlite')`

This is probably a Nix noob problem, but do you have any tips?

**Comment by JanCVanB** [comment]
I tried these:
- adding the `--pure` flag to the `nix-shell` command... no effect.
- clearing some cache(s) with `sudo rm $HOME/.cache/nix/binary-cache-v*.sqlite*`... which changed the error to `error: cannot open SQLite database '/Users/jan/.cache/nix/fetcher-cache-v1.sqlite'`. This new error persisted even after uninstalling & reinstalling Nix. :(

**Comment by roberth** [comment]
@JanCVanB The NixOps packages don't bundle their own Nix, so these Nix errors seem to pertain to the Nix you've installed.
Maybe the [Nix on macOS matrix room](https://matrix.to/#/#macos:nixos.org) can help?

**Comment by JanCVanB** [comment]
@roberth Thank you, they helped me solve my problem - somehow my `~/.cache/nix` was owned by `root:staff` instead of `jan:staff`.

**Comment by HenkKalkwater** [comment]
For me, at commit b67e752c29f18a0ca5534a07661366d6a2c2e649 (latest `nixos-unstable` release) and at commit 89ec09c85893fa1c9169aa14509e19e697871f20 (latest in the `staging-next` branch), nixops is still broken, but this time because `filelock-3.3.0` is not supported for interpreter `python2.7`. It once again seems to be a problem 

```
error: while evaluating the attribute 'buildInputs' of the derivation 'nixops-env' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'out.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'buildInputs' of the derivation 'nixops-1.7' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'out.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'python2.7-boto-2.49.0' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'out.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'python2.7-requests-2.26.0' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'out.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'propagatedBuildInputs' of the derivation 'python2.7-urllib3-1.26.2' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'dev.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'python2.7-cryptography-3.3.2' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'out.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'python2.7-hypothesis-4.57.1' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating the attribute 'out.outPath' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:157:13:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'python2.7-pytest-xdist-1.34.0' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/stdenv/generic/make-derivation.nix:205:7:
while evaluating 'getOutput' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/attrsets.nix:489:23, called from undefined position:
while evaluating 'callPackageWith' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:117:35, called from /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/top-level/python-packages.nix:2666:14:
while evaluating 'makeOverridable' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:67:24, called from /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/development/python-modules/filelock/default.nix:1:1, called from /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:69:16:
while evaluating 'makeOverridablePythonPackage' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/top-level/python-packages.nix:32:37, called from /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/development/python-modules/filelock/default.nix:9:1:
while evaluating 'makeOverridable' at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:67:24, called from /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/top-level/python-packages.nix:34:12:
while evaluating anonymous function at /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/pkgs/development/interpreters/python/mk-python-derivation.nix:30:1, called from /nix/store/gw5fin8kbdn165ybp0ywkqi5jnxi0kr3-source/lib/customisation.nix:69:16:
filelock-3.3.0 not supported for interpreter python2.7
```

As far as I can see, `filelock` dropped Python 2 support since release 3.3.0 (nixpkgs commit e7c94d7f48c2b30c284b11e780bf4b7d196087d0) and later this has been enforced within nixpkgs at commit 877cca04d1f8fb6081808fff16b2d50352a4f6fe. And `filelock` is an indirect dependency of `requests`.

I'm not sure if I should create a separate issue for this or if this issue can be reused.

**Comment by jerith666** [comment]
@HenkKalkwater please open a new issue for that and comment here once you have.

**Comment by HenkKalkwater** [comment]
#145109
