### ISSUE TITLE
Chromium initial_preferences is not read

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#138570]
### Describe the bug

Some preferences can not be set via a enterprise policy. These can only be changed for newly created profiles by creating an `initial_preferences` file.

I was expecting it to read `/etc/chromium/initial_preferences`, but strace told me it only looks at `/nix/store/ys7kd25ibqy3vf1rzsc0bh3xlaw12v2g-chromium-unwrapped-95.0.4638.10/libexec/chromium/initial_preferences`.

One should be able to add an initial_preferences file without recompiling chromium.

We should probably patch this function: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/first_run/first_run_internal_linux.cc;l=21?q=kinitialpref

**Comment by yu-re-ka** [comment]
CC @primeos

**Comment by primeos** [comment]
It'd be great if we could avoid a custom patch but if there are not alternatives it would probably be acceptable.
I'm also surprised that "The standard location of the initial prefs is next to the chrome binary." If no other paths are searched it would seem like this isn't meant to be configurable. Another alternative would be to wrap `chromium.browser`.

**Comment by emilylange** [comment]
#293251 added support for `programs.chromium.initialPrefs` (`/etc/chromium/initial_preferences`) earlier this year (`23.11`/`24.05`).
