### ISSUE TITLE
Pixeluvo

### ISSUE THREAD

**Issue by TheOddler** [NixOS/nixpkgs#138709]
**Project description**
(According to the Pixeluvo devs themselves:) Powerful Layer-Based Image Editing. Pixeluvo is a beautifully designed image and photo editor for Windows and Linux.

**Metadata**

* homepage URL: http://www.pixeluvo.com/
* source URL: not open source
* license: closed source
* platforms: linux, windows

**Comment by WolfangAukang** [comment]
Merged
