### ISSUE TITLE
sleuthkit package is not building JNI libraries needed by clients like autopsy

### ISSUE THREAD

**Issue by gfrascadorio** [NixOS/nixpkgs#138724]
## Issue description
While trying to build a package for autopsy to help with issue #81418, I found that the sleuthkit package is failing to build the necessary JNI libraries.  I'll submit a fix.

### Steps to reproduce
nix-env -i sleuthkit

#### Expected
ls /nix/store/bdqd9aqs1i9d9m54hjj92b6lnjgf9r9c-sleuthkit-4.11.0/lib
libtsk_jni.la  libtsk_jni.so  libtsk_jni.so.0  libtsk_jni.so.0.0.0  libtsk.la  libtsk.so  libtsk.so.19	libtsk.so.19.1.6

#### Actual
ls /nix/store/xqmdx648jg6hg0r9zhwax5302ww0knk9-sleuthkit-4.11.0/lib:
libtsk.la  libtsk.so  libtsk.so.19  libtsk.so.19.1.6

## Technical details
The sleuthkit 'Makefile' skips building JNI libs when 'ant' is missing from buildInputs, but adding ant causes it to download libraries from repo1.maven.org that requires something like a fixed output derivation.

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.8.0-63-generic, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(gf): `"home-manager, nixos-19.09-19.09.2522.75f4ba05c63, nixos-20.09-20.09.4393.068984c00e0, nixpkgs-21.11pre310022.14b0f20fa1f"`
 - channels(root): `""`
 - nixpkgs: `/home/gf/.nix-defexpr/channels/nixpkgs`

**Comment by devhell** [comment]
Wasn't this closed by https://github.com/NixOS/nixpkgs/pull/138894?

**Comment by realsnick** [comment]
https://github.com/juliosueiras-nix/nix-security
