### ISSUE TITLE
bisq-desktop: BUG: Could not connect to running Tor: Error reply: Invalid key type

### ISSUE THREAD

**Issue by uningan** [NixOS/nixpkgs#138786]
### Description
I update bisq 1.7.0 to 1.7.3 then launch fail with error `Sep-21 09:58:12.763 [NetworkNode-9999] ERROR b.n.p2p.network.TorNetworkNode: Could not connect to running Tor: Error reply: Invalid key type`

I check processes list and tor is launched fine by bisq. Also tried to clear `.tor` home directory.

Im running NixOS 21.05 with bisq from master branch or specific commit.

### Notify maintainers
@emmanuelrosa

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.05.3021.8b0b81dab17 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3021.8b0b81dab17, unstable-21.11pre299378.db6e089456c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by emmanuelrosa** [comment]
What is the Nix expression you're using to install bisq?

**Comment by uningan** [comment]
> What is the Nix expression you're using to install bisq?

I'm installing from `configuration.nix` using Home manager module:
```
home.packages = with pkgs; [
      hledger
      tdesktop
      unstable.bisq-desktop
]
```

**Comment by emmanuelrosa** [comment]
The error comes from here: https://github.com/bisq-network/bisq/blob/b6f9231af968811e19b96c3d3137e37499b555d7/p2p/src/main/java/bisq/network/p2p/network/TorNetworkNode.java#L302

Do you have a stacktrace? Also, is your Bisq client already set to use Tor onion v3? The Tor package on Nixpkgs master/unstable doesn't support Tor onion v2.

**Comment by uningan** [comment]
I resolve it.

I delete `~/.local/share/Bisq/btc_mainnet/tor` directory.
