### ISSUE TITLE
libstdc++.so.6 from GCC requires GLIBC_2.33 but gets linked with glibc-2.32

### ISSUE THREAD

**Issue by pshirshov** [NixOS/nixpkgs#138821]
JNI libraries which need `libstdc++.so.6` fail to load under IntelliJ IDEA. 
Seems like something is wrong with gcc package or the way LD_LIBRARY_PATH is defined in the jetbrains formula.

Error messages look like

```
 java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni18325293990181609010.so: 
/nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found 
(required by /nix/store/vyqnqbp3yczrzjx2byk6p680q3mzanyw-gcc-10.3.0-lib/lib/libstdc++.so.6)
```

A quick search over the issues shows that other people experience similar linking issues with other software: 

1. https://github.com/NixOS/nixpkgs/issues/85921#issuecomment-901099981
2. https://github.com/NixOS/nixpkgs/issues/134679#issuecomment-902321206

etc

At the same time everything works in FHS environments, for some reason glibc version is correct there:

```
❯ ls -la /usr/lib|grep libc
lrwxrwxrwx    79 nobody nogroup  1 Jan  1970  libc-2.33.so -> /nix/store/4ikqdj43z39bchjfr462izwbh2w3nbnm-javaenv-usr-target/lib/libc-2.33.so
```

I'm not sure if this problem is related to IDEA or stdenv/gcc, but I noticed that the formula for Android Studio uses FHS env, maybe IDEA should do that as well?

**Comment by Artturin** [comment]
How to repro?

**Comment by veprbl** [comment]
Likely a duplicate of #84043

**Comment by pshirshov** [comment]
> How to repro?

Install intellij idea, create a simple java/kotlin/scala project trying to initialize rocksdb and run it. I may provide a test project if necessary.

**Comment by Ma27** [comment]
I'm not really sure if that'll trigger the problem. There is an [issue template](https://github.com/NixOS/nixpkgs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) for a reason though. Please provide the information that's requested in there.

**Comment by pshirshov** [comment]
Oh, don't worry, it definitely will.

`nix-info` output:

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.16, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.11pre317242.bc9b956714e, home-manager"`
 - channels(pavel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I'm not sure if it would help anyone if I re-format the issue report according to the template, so I would probably leave it as is.

**Comment by Ma27** [comment]
OK, I see :) Would you mind creating such a simple project if possible? That'd speed up the reproduction significantly :)

**Comment by pshirshov** [comment]
I'm unable to reproduce the problem directly in the shell:

```
~ on ☁️  (eu-west-1) took 1m47s
❯ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nix/store/0kiykyrnrpfhmjwxwx89kxr20hmf5304-gcc-10.3.0-lib/lib/

~ on ☁️  (eu-west-1)
❯ export _JAVA_OPTIONS="-Djava.library.path=`pwd`"

~ on ☁️  (eu-west-1)
❯ jshell
Picked up _JAVA_OPTIONS: -Djava.library.path=/home/pavel
|  Welcome to JShell -- Version 11.0.12
|  For an introduction type: /help intro

jshell> System.loadLibrary("rocksdbjni-linux64");

jshell>
```

But a project under IDEA, doing exactly the same thing, fails. Possibly the issue is not related to IDEA itself but something is wrong with graalvm formula.

I'll make a repro.

**Comment by pshirshov** [comment]
Actually I guess the most interesting question is why do I have two glibc versions in my system? I believe that shouldn't be possible with nix versioning model?..

**Comment by pshirshov** [comment]
Well, the problem is solved. Wrong glibc version had been pulled by home-manager.

**Comment by tchabaud** [comment]
@Artturin : I don't have any nixos root channel. I'm currently using Nix installed on an Ubuntu 20.04 LTS

![image](https://user-images.githubusercontent.com/2120966/138354076-69e0bdb5-5910-40f7-a796-651b8d77f55f.png)

**Comment by Artturin** [comment]
do you have packages installed with nix-env?(other than home-manager)  if so remove them
`nix-env -q` to list them
`nix-env -e name`

**Comment by tchabaud** [comment]
Only two : 
![image](https://user-images.githubusercontent.com/2120966/138365101-b5c07b1f-1997-4647-8b2e-c03d0ec1187c.png)

Should I remove nix ?

**Comment by Artturin** [comment]
not sure but probably not.

try garbage collecting `nix-collect-garbage --delete-older-than 1m`

**Comment by coderfromhere** [comment]
How was this fixed? I don't use home-manager and I hven't installed anything with nix-env, still I'm getting the same `GLIBC_2.33 not found` error on my pure nix builds
