### ISSUE TITLE
Add "cabal clean" invocation to Haskell's generic builder

### ISSUE THREAD

**Issue by teh** [NixOS/nixpkgs#13893]
@peti 

If I run e.g. `cabal2nix . > default.nix` then the source will be `src = ./.` - i.e. it can include `dist` output. This caused me a fair amount of headaches recently because it resulted in weird linker errors.

I was wondering what you think about including a `cabal clean` in `./pkgs/development/haskell-modules/generic-builder.nix`, maybe only if `dist` exists?

**Comment by peti** [comment]
I don't think the general purpose builder is the right place to implement this functionality. Instead, `cabal2nix`-generated local-source builds should probably use `filterSource` (or something similar), as it was discussed in https://github.com/NixOS/cabal2nix/issues/112. This would have the added benefit that Nix doesn't even copy the undesirable files into the build sandbox (which can save significant amounts of RAM and time for large projects).
