### ISSUE TITLE
SPARK 2014

### ISSUE THREAD

**Issue by Xmgplays** [NixOS/nixpkgs#138932]
**Project description**
 SPARK 2014 is the new version of SPARK, a software development technology specifically designed for engineering high-reliability applications.

SPARK is an extension to / subset of the Ada programming language and provides formal verification among other things

**Metadata**

* homepage URL: https://github.com/AdaCore/spark2014/
* source URL: https://github.com/AdaCore/spark2014/
* license: gpl3
* platforms: linux, darwin

**Comment by Xmgplays** [comment]
I currently have a fork of [fluffynukeit/adaspark](https://github.com/fluffynukeit/adaspark) where I mostly updated the sources: [here](https://github.com/Xmgplays/adaspark)

It does not build (currently), probably due to the source/inputs/dependencies not being in sync.

**Comment by AleXoundOS** [comment]
@Xmgplays, I suspect you suggest to include SPARK 2014 as a package in nixpkgs? If so, you can try writing default.nix which will help you in systematizing the dependencies. You can use existing nixpkgs packages as a reference and read [nixpkgs manual](https://nixos.org/nixpkgs/manual/).

_It would be better to describe what the intention really is in the issue description._
