### ISSUE TITLE
apulse doesnt work w/ skype

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#13895]
## Basic info

```
$ uname -a
Linux $hostname 4.4.4 #1-NixOS SMP Thu Mar 3 23:10:04 UTC 20
$ nixos-version
16.09pre78286.0bf8a1a (Emu)
$ nix-env --version
nix-env (Nix) 1.11.2
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre78286.0bf8a1a"
```
## Describe your issue here

Skype started with `apulse skype` with pulseaudio disabled doesn't output sound.
### Expected result

Skype plays sounds, eg. notification sounds and voice calls, or the test sound in the configuration window.
### Actual result

Skype is entirely silent.
### Steps to reproduce
1. Install nixos without pulseaudio, maybe just with openbox or something.
2. Install apulse and skype
3. Run `apulse skype`

**Comment by jagajaga** [comment]
Let's just try to update pkg first?

**Comment by Axiomatic-** [comment]
I do not use the Skype client directly, but since it is 32-bit, do you have the 32-bit version of apulse installed? (i.e. `nix-env -iA nixos.pkgsi686Linux.apulse`) When that does not solve the issue, have you tried setting APULSE_PLAYBACK_DEVICE to set the playback device?

**Comment by ben0x539** [comment]
> `nix-env -iA nixos.pkgsi686Linux.apulse`

That seems to make the difference.

Would it be possible for skype to pull in the correct apulse on its own?

**Comment by Axiomatic-** [comment]
> Would it be possible for Skype to pull in the correct apulse on its own?

I would assume so, possibly detect when `hardware.pulseaudio.enable` is set to `true`, do not pull apulse, when it is not set then pull apulse. This has a downside though, it will add the 32-bit version of apulse, when some people may not want this (as they use apulse with other programs). On Arch Linux the AUR package moves apulse to apulse32 when installing it for the 32-bit version.<sup>[1]</sup>  So I suppose one could create a apulse32 alias?

It would be simpler if someone just added that when you want to use apulse in conjunction with Skype, you need the 32-bit version of apulse, to the Nix Wiki though.

<sup>[1]</sup>https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lib32-apulse

**Comment by ben0x539** [comment]
Could Skype depend on 32bit apulse and have a wrapper invoke it directly without having it in the user environment, or does that still conflict with 64bit apulse anyway?

I think a non-functioning Skype being shipped on non-pulseaudio systems is not a great state of affairs even if a solution is in the wiki.

**Comment by vcunat** [comment]
> Could Skype depend on 32bit apulse and have a wrapper invoke it directly without having it in the user environment

Yes, I believe that's the way. Though, I don't see an easy way to detect automatically whether the user has pulseaudio or not.

**Comment by puffnfresh** [comment]
For reference, I tried adding an attribute as part of #5841 but decided against the idea. I think a Skype-specific wrapper would be a good idea!

**Comment by mogorman** [comment]
I believe this is solved in the modern version @ben0x539 can you close or confirm problem persists

**Comment by ben0x539** [comment]
I don't use skype anymore
