### ISSUE TITLE
Flatpaks with `DBusActivatable=true` fail to start through menu

### ISSUE THREAD

**Issue by mrckndt** [NixOS/nixpkgs#138956]
### Describe the bug
When trying to start a flatpak which contains `DBusActivatable=true` in its .desktop file it refuses to start (tested in GNOME shell). Commenting out `DBusActivatable=true` (tested in copied .desktop to home dir) or just `flatpak run ....` seems to work fine.

### Steps To Reproduce
1. Install e.g. org.gnome.Geary
2. Run it from GNOME shell

### Expected behavior
Flatpak should open.

### Notify maintainers
@jtojnar

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.12.13-xanmod1-cacule, NixOS, 21.05.3294.3397f0ede9e (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3294.3397f0ede9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Try this, maybe it'll give a error or something
`nix run nixos.gnome.gtk -c gtk-launch foot`
foot terminal used as a example desktop file in share/applications

**Comment by jtojnar** [comment]
Pre-requisite would be Flatpak linking d-bus service files to a well-known location. Not sure if it currently does that.

https://developer.gnome.org/documentation/guidelines/maintainer/integrating.html#d-bus-activation

**Comment by mrckndt** [comment]
> Try this, maybe it'll give a error or something
> `nix run nixos.gnome.gtk -c gtk-launch foot`
> foot terminal used as a example desktop file in share/applications

@Artturin there is nothing. Tbh i don't get how this helps. FWIW gnome-maps (also with dbus actication) installed with nix works; the gnome-maps flatpak not.

**Comment by mrckndt** [comment]
@jtojnar on both my Fedora Silverblue machine and NixOS machine the services are symlinked to the same location if that's what you mean.
```
(chapek9) ~ $ ls -l /var/lib/flatpak/exports/share/dbus-1/services/org.gnome.Geary.service
lrwxrwxrwx. 1 root root 99 21. Sep 02:30 /var/lib/flatpak/exports/share/dbus-1/services/org.gnome.Geary.service -> ../../../../app/org.gnome.Geary/current/active/export/share/dbus-1/services/org.gnome.Geary.service
```

**Comment by jtojnar** [comment]
Maybe we need to add `/var/lib/flatpak/exports` to `services.dbus.packages`:

https://github.com/NixOS/nixpkgs/blob/63ec2613bd109c36d29aaf015152da92a7984f7f/nixos/modules/services/system/dbus.nix#L16

**Comment by Artturin** [comment]
![screenshot_2021-09-22_22-10-35_735147180](https://user-images.githubusercontent.com/56650223/134406861-dc00588e-a942-4ff9-9a2b-a30ae6e60825.png)

![screenshot_2021-09-22_22-11-27_282383802](https://user-images.githubusercontent.com/56650223/134406881-894b37a8-f83d-4690-b3a6-b6a24802800e.png)

**Comment by jtojnar** [comment]
Did you try adding the path to `services.dbus.packages`?

**Comment by Artturin** [comment]
> Did you try adding the path to `services.dbus.packages`?

yes 
`/var/lib/flatpak/exports` 

`/var/lib/flatpak/exports/share/dbus-1/services`
got added to /etc/dbus-1/session.conf
doesn't work

**Comment by Artturin** [comment]
this is what i have for now 
i switched to dbus-broker since fedora is using that and it has better logs

it does find the geany service file but it `Failed at step EXEC spawning flatpak: No such file or directory`


if someone wants to try: 

this patch applied to nixos-unstable branch
very rough for now
```diff
diff --git a/nixos/modules/services/desktops/flatpak.nix b/nixos/modules/services/desktops/flatpak.nix
index 7da92cc9f26..868714ce603 100644
--- a/nixos/modules/services/desktops/flatpak.nix
+++ b/nixos/modules/services/desktops/flatpak.nix
@@ -28,11 +28,59 @@ in {
       }
     ];
 
-    environment.systemPackages = [ pkgs.flatpak ];
+    environment.systemPackages = [ pkgs.flatpak pkgs.xdg-dbus-proxy pkgs.dbus-broker ];
 
-    services.dbus.packages = [ pkgs.flatpak ];
+    services.dbus.packages = [ pkgs.flatpak /*"/var/lib/flatpak/exports"*/ ];
 
-    systemd.packages = [ pkgs.flatpak ];
+    systemd.services.dbus-broker = {
+      path = [ pkgs.flatpak ];
+      enable = true;
+      aliases = [ "dbus.service" ];
+      # Don't restart dbus-daemon. Bad things tend to happen if we do.
+      reloadIfChanged = true;
+      restartTriggers = [ "/etc/dbus-1" ];
+      environment = { LD_LIBRARY_PATH = config.system.nssModules.path; };
+    };
+    systemd.user.services.dbus-broker = {
+      path = [ pkgs.flatpak ];
+      enable = true;
+      wantedBy = [ "default.target" ];
+      aliases = [ "dbus.service" ];
+      # Don't restart dbus-daemon. Bad things tend to happen if we do.
+      reloadIfChanged = true;
+      restartTriggers = [ "/etc/dbus-1" ];
+      environment = { LD_LIBRARY_PATH = config.system.nssModules.path; };
+    };
+
+    #systemd.services.dbus = {
+    #  enable = true;
+    #  aliases = [ "dbus.service" ];
+    #};
+    #systemd.user.services.dbus = {
+    #  enable = true;
+    #  aliases = [ "dbus.service" ];
+    #};
+
+    systemd.sockets.dbus = {
+      description = "D-Bus System Message Bus Socket";
+      wantedBy = [ "sockets.target" ];
+      socketConfig = { 
+        ListenStream = "/run/dbus/system_bus_socket";
+      };
+    };
+
+    systemd.user.sockets.dbus = {
+      description = "D-Bus System Message Bus Socket";
+      wantedBy = [ "sockets.target" ];
+      socketConfig = { 
+        ListenStream = "%t/bus";
+        ExecStartPost = "-/run/current-system/systemd/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS=unix:path=%t/bus";
+      };
+    };
+    #systemd.services.dbus.enable = false;
+    #systemd.user.services.dbus.enable = false;
+
+    systemd.packages = [ pkgs.flatpak pkgs.dbus-broker ];
 
     environment.profiles = [
       "$HOME/.local/share/flatpak/exports"
diff --git a/nixos/modules/services/system/dbus.nix b/nixos/modules/services/system/dbus.nix
index d4cacb85694..85eb4350f73 100644
--- a/nixos/modules/services/system/dbus.nix
+++ b/nixos/modules/services/system/dbus.nix
@@ -102,7 +102,7 @@ in
 
     users.groups.messagebus.gid = config.ids.gids.messagebus;
 
-    systemd.packages = [ pkgs.dbus.daemon ];
+    #systemd.packages = [ pkgs.dbus.daemon ];
 
     security.wrappers.dbus-daemon-launch-helper = {
       source = "${pkgs.dbus.daemon}/libexec/dbus-daemon-launch-helper";
diff --git a/pkgs/os-specific/linux/dbus-broker/default.nix b/pkgs/os-specific/linux/dbus-broker/default.nix
index b7e0a6b6158..631c173e1ed 100644
--- a/pkgs/os-specific/linux/dbus-broker/default.nix
+++ b/pkgs/os-specific/linux/dbus-broker/default.nix
@@ -23,6 +23,11 @@ stdenv.mkDerivation rec {
   PKG_CONFIG_SYSTEMD_SYSTEMDUSERUNITDIR = "${placeholder "out"}/lib/systemd/user";
   PKG_CONFIG_SYSTEMD_CATALOGDIR = "${placeholder "out"}/lib/systemd/catalog";
 
+  postPatch = ''
+    substituteInPlace src/launch/launcher.c \
+      --replace "/usr/share/dbus-1" "${dbus.daemon}/share/dbus-1"
+  '';
+
   postInstall = ''
     install -Dm644 $src/README.md $out/share/doc/dbus-broker/README
 
```

```nix
{
  inputs = {
    #nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixpkgs.url = "/home/artturin/nixgits/my-nixpkgs";
    #nixpkgs.url = "path:../nixgits/nixpkgs1";
    #pkgsReview.url = "github:Artturin/nixpkgs/pipewirejackldpath";
    #pkgsReview.url = "path:../nixgits/my-nixpkgs";
  };

  outputs = inputs@{ self, nixpkgs, /*pkgsReview*/ }: {

    nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      specialArgs = { inherit inputs; };
      modules = [
        ({ pkgs, ... }: {
          #hardware.video.hidpi.enable = true;
        })
        ({ pkgs, ... }: {
          #disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];
          imports = [
            #"${inputs.pkgsReview}/nixos/modules/services/desktops/pipewire/pipewire.nix"

            #"${inputs.nixpkgs}/nixos/modules/installer/cd-dvd/iso-image.nix"
            #"${inputs.nixpkgs}/nixos/modules/virtualisation/qemu-vm.nix"
            ## For virtualisation settings
            "${inputs.nixpkgs}/nixos/modules/virtualisation/qemu-vm.nix"
            "${inputs.nixpkgs}/nixos/modules/profiles/clone-config.nix"
            "${inputs.nixpkgs}/nixos/modules/installer/cd-dvd/channel.nix"
          ];
          environment.systemPackages = with pkgs; [
            (neovim.override { viAlias = true; vimAlias = true;})
            ranger
            ripgrep
            tree
            #firefox
          ];

          #hardware.pulseaudio.enable = true;

          services.xserver = {
            enable = true;
            #displayManager.lightdm = {
            #  enable = true;
            #};
            displayManager.autoLogin = {
              user = "user";
              enable = true;
            };
            desktopManager.gnome = {
              enable = true;
            };
          };

          environment.gnome.excludePackages = with pkgs.gnome; [
            gnome-weather
            gnome-calendar
            gnome-maps
            gnome-contacts
            gnome-software
            gnome-calculator
            gnome-calendar
            gnome-characters
            gnome-clocks
            gnome-font-viewer
            gnome-logs
            gnome-maps
            gnome-music
            pkgs.gnome-photos
            totem
            epiphany
            geary
            gnome-disk-utility
            seahorse
            sushi
            evince
            cheese
            eog
            baobab
            pkgs.evolution
            gnome-backgrounds
          ];

          services.flatpak.enable = true;
          # Documentation for these is in nixos/modules/virtualisation/qemu-vm.nix
          virtualisation = {
            memorySize = 1024 * 3;
            diskSize = 1024 * 4;
            cores = 8;
          };

          programs = {
            zsh.enable = true;
          };
          environment.etc."zshrc.local" = { source = "${pkgs.grml-zsh-config}/etc/zsh/zshrc"; };

          boot.tmpOnTmpfs = true;
          #boot.tmpOnTmpfsSize = "80%";

          documentation.enable = false;
          users.mutableUsers = false;
          users.defaultUserShell = pkgs.zsh;
          users.users.root = {
            password = "root";
          };
          users.users.user = {
            password = "user";
            isNormalUser = true;
            extraGroups = [ "wheel" ];
          };
        })
      ];
    };
    # So that we can just run 'nix run' instead of
    # 'nix build ".#nixosConfigurations.vm.config.system.build.vm" && ./result/bin/run-nixos-vm'
    defaultPackage.x86_64-linux = self.nixosConfigurations.vm.config.system.build.vm;
    defaultApp.x86_64-linux = {
      type = "app";
      program = "${self.defaultPackage.x86_64-linux}/bin/run-nixos-vm";
    };
  };
}
```
`nix run` to run this vm

**Comment by keanuk** [comment]
I am still having this issue in 22.05 and the 22.11 unstable channel. I get the following log output when trying to launch one of the Flatpaks in question:
`Activated service 'org.gnome.Boxes' failed: Failed to execute program org.gnome.Boxes: No such file or directory`

**Comment by kutzlect** [comment]
> this is what i have for now i switched to dbus-broker since fedora is using that and it has better logs
> 
> it does find the geany service file but it `Failed at step EXEC spawning flatpak: No such file or directory`
> 
> if someone wants to try:
> 
> this patch applied to nixos-unstable branch very rough for now
> 
> ```diff
> diff --git a/nixos/modules/services/desktops/flatpak.nix b/nixos/modules/services/desktops/flatpak.nix
> index 7da92cc9f26..868714ce603 100644
> --- a/nixos/modules/services/desktops/flatpak.nix
> +++ b/nixos/modules/services/desktops/flatpak.nix
> @@ -28,11 +28,59 @@ in {
>        }
>      ];
>  
> -    environment.systemPackages = [ pkgs.flatpak ];
> +    environment.systemPackages = [ pkgs.flatpak pkgs.xdg-dbus-proxy pkgs.dbus-broker ];
>  
> -    services.dbus.packages = [ pkgs.flatpak ];
> +    services.dbus.packages = [ pkgs.flatpak /*"/var/lib/flatpak/exports"*/ ];
>  
> -    systemd.packages = [ pkgs.flatpak ];
> +    systemd.services.dbus-broker = {
> +      path = [ pkgs.flatpak ];
> +      enable = true;
> +      aliases = [ "dbus.service" ];
> +      # Don't restart dbus-daemon. Bad things tend to happen if we do.
> +      reloadIfChanged = true;
> +      restartTriggers = [ "/etc/dbus-1" ];
> +      environment = { LD_LIBRARY_PATH = config.system.nssModules.path; };
> +    };
> +    systemd.user.services.dbus-broker = {
> +      path = [ pkgs.flatpak ];
> +      enable = true;
> +      wantedBy = [ "default.target" ];
> +      aliases = [ "dbus.service" ];
> +      # Don't restart dbus-daemon. Bad things tend to happen if we do.
> +      reloadIfChanged = true;
> +      restartTriggers = [ "/etc/dbus-1" ];
> +      environment = { LD_LIBRARY_PATH = config.system.nssModules.path; };
> +    };
> +
> +    #systemd.services.dbus = {
> +    #  enable = true;
> +    #  aliases = [ "dbus.service" ];
> +    #};
> +    #systemd.user.services.dbus = {
> +    #  enable = true;
> +    #  aliases = [ "dbus.service" ];
> +    #};
> +
> +    systemd.sockets.dbus = {
> +      description = "D-Bus System Message Bus Socket";
> +      wantedBy = [ "sockets.target" ];
> +      socketConfig = { 
> +        ListenStream = "/run/dbus/system_bus_socket";
> +      };
> +    };
> +
> +    systemd.user.sockets.dbus = {
> +      description = "D-Bus System Message Bus Socket";
> +      wantedBy = [ "sockets.target" ];
> +      socketConfig = { 
> +        ListenStream = "%t/bus";
> +        ExecStartPost = "-/run/current-system/systemd/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS=unix:path=%t/bus";
> +      };
> +    };
> +    #systemd.services.dbus.enable = false;
> +    #systemd.user.services.dbus.enable = false;
> +
> +    systemd.packages = [ pkgs.flatpak pkgs.dbus-broker ];
>  
>      environment.profiles = [
>        "$HOME/.local/share/flatpak/exports"
> diff --git a/nixos/modules/services/system/dbus.nix b/nixos/modules/services/system/dbus.nix
> index d4cacb85694..85eb4350f73 100644
> --- a/nixos/modules/services/system/dbus.nix
> +++ b/nixos/modules/services/system/dbus.nix
> @@ -102,7 +102,7 @@ in
>  
>      users.groups.messagebus.gid = config.ids.gids.messagebus;
>  
> -    systemd.packages = [ pkgs.dbus.daemon ];
> +    #systemd.packages = [ pkgs.dbus.daemon ];
>  
>      security.wrappers.dbus-daemon-launch-helper = {
>        source = "${pkgs.dbus.daemon}/libexec/dbus-daemon-launch-helper";
> diff --git a/pkgs/os-specific/linux/dbus-broker/default.nix b/pkgs/os-specific/linux/dbus-broker/default.nix
> index b7e0a6b6158..631c173e1ed 100644
> --- a/pkgs/os-specific/linux/dbus-broker/default.nix
> +++ b/pkgs/os-specific/linux/dbus-broker/default.nix
> @@ -23,6 +23,11 @@ stdenv.mkDerivation rec {
>    PKG_CONFIG_SYSTEMD_SYSTEMDUSERUNITDIR = "${placeholder "out"}/lib/systemd/user";
>    PKG_CONFIG_SYSTEMD_CATALOGDIR = "${placeholder "out"}/lib/systemd/catalog";
>  
> +  postPatch = ''
> +    substituteInPlace src/launch/launcher.c \
> +      --replace "/usr/share/dbus-1" "${dbus.daemon}/share/dbus-1"
> +  '';
> +
>    postInstall = ''
>      install -Dm644 $src/README.md $out/share/doc/dbus-broker/README
>  
> ```
> 
> ```nix
> {
>   inputs = {
>     #nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
>     nixpkgs.url = "/home/artturin/nixgits/my-nixpkgs";
>     #nixpkgs.url = "path:../nixgits/nixpkgs1";
>     #pkgsReview.url = "github:Artturin/nixpkgs/pipewirejackldpath";
>     #pkgsReview.url = "path:../nixgits/my-nixpkgs";
>   };
> 
>   outputs = inputs@{ self, nixpkgs, /*pkgsReview*/ }: {
> 
>     nixosConfigurations.vm = nixpkgs.lib.nixosSystem {
>       system = "x86_64-linux";
>       specialArgs = { inherit inputs; };
>       modules = [
>         ({ pkgs, ... }: {
>           #hardware.video.hidpi.enable = true;
>         })
>         ({ pkgs, ... }: {
>           #disabledModules = [ "services/desktops/pipewire/pipewire.nix" ];
>           imports = [
>             #"${inputs.pkgsReview}/nixos/modules/services/desktops/pipewire/pipewire.nix"
> 
>             #"${inputs.nixpkgs}/nixos/modules/installer/cd-dvd/iso-image.nix"
>             #"${inputs.nixpkgs}/nixos/modules/virtualisation/qemu-vm.nix"
>             ## For virtualisation settings
>             "${inputs.nixpkgs}/nixos/modules/virtualisation/qemu-vm.nix"
>             "${inputs.nixpkgs}/nixos/modules/profiles/clone-config.nix"
>             "${inputs.nixpkgs}/nixos/modules/installer/cd-dvd/channel.nix"
>           ];
>           environment.systemPackages = with pkgs; [
>             (neovim.override { viAlias = true; vimAlias = true;})
>             ranger
>             ripgrep
>             tree
>             #firefox
>           ];
> 
>           #hardware.pulseaudio.enable = true;
> 
>           services.xserver = {
>             enable = true;
>             #displayManager.lightdm = {
>             #  enable = true;
>             #};
>             displayManager.autoLogin = {
>               user = "user";
>               enable = true;
>             };
>             desktopManager.gnome = {
>               enable = true;
>             };
>           };
> 
>           environment.gnome.excludePackages = with pkgs.gnome; [
>             gnome-weather
>             gnome-calendar
>             gnome-maps
>             gnome-contacts
>             gnome-software
>             gnome-calculator
>             gnome-calendar
>             gnome-characters
>             gnome-clocks
>             gnome-font-viewer
>             gnome-logs
>             gnome-maps
>             gnome-music
>             pkgs.gnome-photos
>             totem
>             epiphany
>             geary
>             gnome-disk-utility
>             seahorse
>             sushi
>             evince
>             cheese
>             eog
>             baobab
>             pkgs.evolution
>             gnome-backgrounds
>           ];
> 
>           services.flatpak.enable = true;
>           # Documentation for these is in nixos/modules/virtualisation/qemu-vm.nix
>           virtualisation = {
>             memorySize = 1024 * 3;
>             diskSize = 1024 * 4;
>             cores = 8;
>           };
> 
>           programs = {
>             zsh.enable = true;
>           };
>           environment.etc."zshrc.local" = { source = "${pkgs.grml-zsh-config}/etc/zsh/zshrc"; };
> 
>           boot.tmpOnTmpfs = true;
>           #boot.tmpOnTmpfsSize = "80%";
> 
>           documentation.enable = false;
>           users.mutableUsers = false;
>           users.defaultUserShell = pkgs.zsh;
>           users.users.root = {
>             password = "root";
>           };
>           users.users.user = {
>             password = "user";
>             isNormalUser = true;
>             extraGroups = [ "wheel" ];
>           };
>         })
>       ];
>     };
>     # So that we can just run 'nix run' instead of
>     # 'nix build ".#nixosConfigurations.vm.config.system.build.vm" && ./result/bin/run-nixos-vm'
>     defaultPackage.x86_64-linux = self.nixosConfigurations.vm.config.system.build.vm;
>     defaultApp.x86_64-linux = {
>       type = "app";
>       program = "${self.defaultPackage.x86_64-linux}/bin/run-nixos-vm";
>     };
>   };
> }
> ```
> 
> `nix run` to run this vm

This patch hasn't been applied to unstable. The issue still persists...

**Comment by alaviss** [comment]
Here's my fix for the issue if you use `dbus-broker`:

```nix
{
  systemd.user.services.dbus- = {
    serviceConfig.ExecSearchPath="${cfg.package}/bin";
    overrideStrategy = "asDropin";
  };
}
```

This "solution" is based on the fact `dbus-broker` launch services via systemd using transient units with prefix `dbus-`.

`systemd` however does not have `flatpak` in its `PATH` and these transient units do not have them specified either.

The drop-in is used to point systemd to where it could find flatpak.

**Comment by meisme-dev** [comment]
Same issue on unstable

**Comment by uricot** [comment]
Having the same issue on nixos unstable channel

**Comment by jasons393** [comment]
Same issue on 23.05

**Comment by Irate-Walrus** [comment]
I'm experiencing the same behaviour in sway with gnome.nautilus and flatpaks. However, the error I receive from .nautilus-wrapp gives `no owner for PackageKit` errors, so may be unrelated.

**Comment by Xyphyn** [comment]
This seems like quite a critical issue, any updates?
