### ISSUE TITLE
xdg-XYZ --manual contains incorrect sed subsitution

### ISSUE THREAD

**Issue by badi** [NixOS/nixpkgs#13904]
I'll be happy to take this on, but am filing this for the record.
## Basic info

To make sure that we are on the same page:
- Kernel: (run `uname -a`): `Linux irmo 4.4.3 #1-NixOS SMP Thu Feb 25 20:01:36 UTC 2016 x86_64 GNU/Linux`
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...): `Linux irmo 4.4.3 #1-NixOS SMP Thu Feb 25 20:01:36 UTC 2016 x86_64 GNU/Linux`
- Nix version: (run `nix-env --version`): `nix-env (Nix) 1.11.2`
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`): `"16.03.30.2068621"`
## Describe your issue here

Reading the manual output for `xdg-open` indicates that the `substituteInPlace` of `sed` was a bit too eager: the `sed` in `passed` was replaced.
This is in the section on Exit Codes, item 2.
### Expected result

The sentence should read:

> One of the files passed on the command line did not exist.
### Actual result

> One of the files pas/nix/store/19v1hw11lsipbf79gvrhfg8ix0bjkyr3-gnused-4.2.2/bin/sed on the command line did not exist.
### Steps to reproduce
1. `xdg-XYZ --manual`

where XYZ is one of the xdg utilities
### Relevant links:
- [xdg-utils/default.nix](https://github.com/NixOS/nixpkgs/blob/34721289d95549d9d30fdc3d96abbcd9a5e33daf/pkgs/tools/X11/xdg-utils/default.nix#L37) on 3472128

Edit: fixed steps to reproduce
Edit: realized this is affects all xdg tools

**Comment by obadz** [comment]
There are still some problematic substitutions:

```
$ xdg-open --help
xdg-open - opens a /nix/store/dsq5q00ais2y9pfrn72zd2p6pyp3xk8a-file-5.25/bin/file or URL in the user's preferred application

Synopsis
xdg-open { /nix/store/dsq5q00ais2y9pfrn72zd2p6pyp3xk8a-file-5.25/bin/file | URL }
```

```bash
        for /nix/store/qrwh7kib1wcq4ps7cbsr56jc5yw6bvj5-file-5.25/bin/file in "$dir"/applications/*.desktop "$dir"/applications/*/*.desktop "$dir"/applnk/*.desktop "$dir"/applnk/*/*.desktop; do
```

```bash
    if [ ! -r "$1" ]; then
        exit_failure_file_permission_read "no permission to read /nix/store/qrwh7kib1wcq4ps7cbsr56jc5yw6bvj5-file-5.25/bin/file '$1'"
    fi
```

cc // @zimbatm

**Comment by zimbatm** [comment]
I think that the only way to make this substitution reliable is to use a patch.

**Comment by dezgeg** [comment]
Also https://github.com/NixOS/nixpkgs/commit/1df2a6431fa1b51b9779070ce2a0171208985bf1#commitcomment-16676247 might be an option. If that actually works, it could be used more generically in shell packages that are in Nixpkgs.

**Comment by Profpatsch** [comment]
triage: has this been tackled?

**Comment by badi** [comment]
Yep, closing
