### ISSUE TITLE
How to properly setup a shared (home) printer?

### ISSUE THREAD

**Issue by datakurre** [NixOS/nixpkgs#13901]
## Basic info

* Kernel: Linux ... 4.4.4 #1-NixOS SMP Thu Mar 3 23:10:04 UTC 2016 x86_64 GNU/Linux
* System: 16.09pre78286.0bf8a1a (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre78286.0bf8a1a"

## Describe your issue here

I'm unable to set up a working shared printer on a NixOS server by following existing docs.

What I'd like to have is a shared home printer, which would allow anyone within the same LAN to print.

Related parts of my configuration.nix looks like:

```
    services.printing.enable = true;
    services.printing.gutenprint = true;
    services.printing.browsing = true;
    services.printing.defaultShared = true;

    avahi.enable = true;
    avahi.publish.enable = true;
    avahi.publish.domain = true;
    avahi.publish.userServices = true;

    services.firewall.enable = true;
    services.firewall.allowedTCPPorts = [ 631 ];
    services.firewall.allowedUDPPorts = [ 631 ];
    services.firewall.extraCommands = ''
        iptables -I INPUT -p udp --dport mdns -d 224.0.0.251 -j ACCEPT   # zeroconf
        iptables -I OUTPUT -p udp --dport mdns -d 224.0.0.251 -j ACCEPT  # zeroconf
    '';
```

I can add a printer through CUPS web UI, enable CUPS printer sharing from there, and see and add the printer on OSX client (as a bonjour printer). But printing from OSX fails. Journal shows the following error from CUPS:

```
Unable to encrypt connection: Unable to create server credentials.
```

Only Google results for that message are from cups code, so this sounds like a rare issue.

I tried to customize cupsd.conf to allow printing without authentication, but without any success.

A bonus would be to make the printer work as "AirPrint-printer" on iOS devices. I've managed to created AirPrint...service -file using https://github.com/tjfontaine/airprint-generate and get that loaded by avahi (by adding it ${avahi}/etc/avahi/services in a custom avahi.postInstall), but it still didn't work event without firewall disabled.

**Comment by joelmo** [comment]
See the listenAddresses option, the default is to listen on localhost. But this looks unreleated to the error message you have: unable enable to create server credentials. Maybe there is some permission issue, try enable polkit?

Also I think some more options need to be enabled for avahi, like publish.addresses.

**Comment by datakurre** [comment]
Thanks. I'll try these later today.

Although, listenAddresses probably has working default, because printer is found and configured probably, and avahi.publish.userServices says that it includes avahi.publish.addresses, and according to manual polkit should be enabled by default.

**Comment by joelmo** [comment]
See http://www.cups.org/documentation.php/doc-2.1/man-cups-files.conf.html, and the directive ServerKeychain. Maybe it can be set to /etc/ssl/certs.

**Comment by datakurre** [comment]
@joelmo Thanks for that tip about ServerKeychain. I needed to create a .crt .key -pair into /etc/cups/ssl to make it work. Now CUPS works and also Airprint discovery started working.

Now, only thing not working is the printer itself. CUPS gets it to make some noise, but eventually CUPS reports printing success without anything coming out of the printer. But this is probably a more usual issue with old USB-printers, and I expect to resolve it with some googling...

Probably I should now write down somewhere all the steps required for zeroconf and airprint...

**Comment by datakurre** [comment]
The final issue was just that the default Gutenprint driver (PPD) really work for my printer. After finding an alternative PPD, everything started working. So, here's everything I had to do to share printer with bonjour/zeroconf (for mac) and airprint (for ipad). Maybe @garbas would like to merge this to docs while moving printing docs from Wiki:

1. Enable CUPS with sharing and Avahi with published user services in ``/etc/nixos/configuration.nix``:

   ```
   services = {
     printing.enable = true;
     printing.browsing = true;
     printing.defaultShared = true;
    
     avahi.enable = true;
     avahi.publish.enable = true;
     avahi.publish.userServices = true;
   }
   ```

2. Open CUPS ports in firewall:

   ```
   networking = {
     firewall = {
       enable = true;
       allowedTCPPorts = [ 631 ];
       allowedUDPPorts = [ 631 ];
     };
   };
   ```

3. Rebuild system and install printer either through CUPS web frontend or lpadmin.

4. Check that CUPS has some [hostname].cert and [hostname].key files in ``/etc/cups/ssl`` and, if not, generate them, e.g., with openssl.

5. Generate Airprint Avahi-service file for the installed printer using https://github.com/tjfontaine/airprint-generate.

6. Customize Avahi with the service file created in 4.:

   ```
   nixpkgs.config.packageOverrides = pkgs: rec {
     avahi = pkgs.avahi.overrideDerivation(args: rec {
       airprint = ./AirPrint-Brother_HL-2030_series.service;
       postInstall = ''
        ln -s $airprint $out/etc/avahi/services/AirPrint-Brother_HL-2030_series.service
       '';
     });
   };
   ```

Done.

**Comment by abbradar** [comment]
To add more experience: I've suceeded sharing a printer through CUPS to Linux clients recently. I've needed points 1-3 (without a certificate) and then opened CUPS administration on a client. It found the printer automagically through Avahi. Notice that I haven't found how to ask CUPS on Linux to get PPD from the server, so I set the server's printer type to raw queue. Maybe someone knows a solution or if it's possible at all?

**Comment by datakurre** [comment]
@abbradar Do you mean somethin like

```
lpinfo -v
```

To get the printer address, and

```
lpadmin -p Brother_HL-2030_series -E -v usb://Brother/HL-2030%20series?serial=L7J236015 -P /path/to/Brother-HL-2030-hl1250.ppd 
```

to configure the printer with custom PPD?

**Comment by abbradar** [comment]
Nah, I thought that I can set PPD on the server and then all clients would just get it from there automatically. Instead what I found is:
1. There is no way (from what I've seen) to have CUPS clients get PPDs from the server automatically.
2. One can't setup same printer PPD on both a client and a server -- it garbles output (but I haven't tried to do so -- read it on ArchWiki).

**Comment by datakurre** [comment]
@abbradar Strange. My mac did download the PPD.

About certs. Possibly those /etc/cups/ssl certificates should be created automatically, and somehow I managed to miss them.

**Comment by abbradar** [comment]
@datakurre I suppose that maybe it's a Mac feature, not CUPS one, but I'm not sure.

**Comment by abbradar** [comment]
Maybe it's a Mac-specific requirement, too?

**Comment by datakurre** [comment]
@abbradar Good point. /etc/cups/ssl requirement might be mac specific (maybe CUPS on mac is configured to require encryption by default). On PPD issue I can only say that my mac's CUPS client and NixOS server both have the same PPD and it works.

**Comment by abbradar** [comment]
Hm, I've tried just now to set proper PPD on both the server and client, and it works! Looks like ArchWiki note at https://wiki.archlinux.org/index.php/CUPS#Local_CUPS_server might be invalid.

**Comment by OlivierNicole** [comment]
As for me, I just had to do 1-2-3, except I added the following option:
```
services.avahi.nssmdns
```
And it worked.

**Comment by juanibiapina** [comment]
You also need to install the package `nssmdns`. Also CUPS needs to be restarted after every boot.
