### ISSUE TITLE
libnatpmp.so.1 not executable

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#139197]
### Describe the bug

Recently, #134007 introduced libnatpmp as a dependency for Transmission. But for some reason the file `libnatpmp.so.1` is not executable (not on unstable, nor on nixos-21.05). This makes transmission-daemon fail to load the library at startup on my server with the "hardened" profile.

### Steps To Reproduce

1. `nix build -f default.nix` with `default.nix` being:

```nix
let
  nixpkgs = builtins.getFlake "nixpkgs/nixos-unstable";

  module = { pkgs, modulesPath, ... }:
  {
    imports = [ (modulesPath + "/profiles/hardened.nix") ];

    # Apparently, "linuxPackages_hardened" is broken
    boot.kernelPackages = pkgs.linuxPackages;

    services.transmission.enable = true;

    users.users.root.initialHashedPassword = "";
  };
in
  (nixpkgs.lib.nixosSystem { modules = [ module ]; system = "x86_64-linux"; }).config.system.build.vm
```

2. Connect as root, and observe `transmission-daemon` failing to start due to libnatpmp

### Expected behavior

`libnatpmp.so.1` is executable and `transmission-daemon` can start without issues.

### Notify maintainers

For #134007

@angustrau 

For libnatpmp:

@orivej

For transmission-daemon:

@astsmtl @vcunat @wizeman

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.142, NixOS, 21.05.20210922.83413f4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-20.09.4242.cee3ca37c68, home-manager-20.09, nixpkgs-unstable-21.05pre291116.22c86a04669"`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- libnatpmp
- transmission
# a list of nixos modules affected by the problem
module:
- profiles/hardened.nix
```

**Comment by vcunat** [comment]
NixOS tests also broke with the same error: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.transmission.x86_64-linux

**Comment by Artturin** [comment]
fedora does this https://src.fedoraproject.org/rpms/libnatpmp/blob/f34/f/libnatpmp.spec#_38
