### ISSUE TITLE
imagej crashes on startup

### ISSUE THREAD

**Issue by gabysbrain** [NixOS/nixpkgs#139166]
### Steps To Reproduce
1. install imagej: `nix-env -iA nixos.imagej`
2. run imagej: `imagej`

### Expected behavior
The application should start

### Screenshots
```
> imagej
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.substring(String.java:1907)
	at ij.ImageJ.main(ImageJ.java:659)
```

### Notify maintainers
@yuriaisaka

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.05.3248.6120ac5cd20 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"agenix, home-manager-21.05, nixos-21.05.3248.6120ac5cd20"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hrhino** [comment]
Doesn't seem to happen on unstable, but does happen on 21.05.

**Comment by doronbehar** [comment]
Thanks @hrhino for taking care of this. @gabysbrain please reopen if you update your channels with `imagej` updated and you still experience an issue.
