### ISSUE TITLE
Zola doesn't build on my M1 Darwin

### ISSUE THREAD

**Issue by cideM** [NixOS/nixpkgs#139208]
### Describe the bug
It doesn't work with `nix-shell` nor with a flake. Works fine on my NixOS machine.

```shell
$ nix-shell -p zola
error: missing bootstrap url for platform aarch64-apple-darwin
(use '--show-trace' to show detailed location information)
```

I don't even know what `missing bootstrap url` means.

With a flake

```nix
{
  description = "bug";

  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system}; in
      rec {
        devShell = pkgs.mkShell
          {
            buildInputs = with pkgs; [
              zola
            ];
          };
      }
    );
}
```

```shell
$ nix develop
building '/nix/store/hns9j3acvi0q2y7v2xyn7rfdff4vcjdi-zola-0.14.1.drv'...
[1/0/2 built, 0.0 MiB DL] building zola-0.14.1 (buildPhase): ++ env CC_aarch64-apple-darwin=/nix/store/jgaarpq3rdfk7gbm0gm3xlh8hhbw15ay-clang-wrapper-11.1.0/bin/cc CXX_aarch64-apple-darwin=/nix/s
builder for '/nix/store/hns9j3acvi0q2y7v2xyn7rfdff4vcjdi-zola-0.14.1.drv' failed with exit code 101; last 10 log lines:
    cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
    cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
    cargo:rustc-link-search=native=/private/tmp/nix-build-zola-0.14.1.drv-0/source/target/aarch64-apple-darwin/release/build/sass-sys-a816717d3800a6e4/out/build/lib
    cargo:rustc-link-lib=static=sass

    --- stderr
    thread 'main' panicked at 'no c++ library found', /private/tmp/nix-build-zola-0.14.1.drv-0/zola-0.14.1-vendor.tar.gz/sass-sys/build.rs:80:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  error: build failed
cannot build derivation '/nix/store/vzipi2cj70kgz00509b9g806az2v7n9q-nix-shell-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/vzipi2cj70kgz00509b9g806az2v7n9q-nix-shell-env.drv' failed
```

I suspect that this is related to `libsass`. I've had so many dynamic linking errors in the past week, especially from Rust stuff, that I no longer have the energy to look into this myself, hence the bug report.

### Notify maintainers
@dywedir @0x4A6F @dali99 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.5.0, macOS 11.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixpkgs-21.11pre304227.ecaf3da9340"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by 0x4A6F** [comment]
Could you (or anyone with access to aarch64-darwin) try another run against my branch?

```
{
  description = "issue-139208";

  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.nixpkgs.url = "github:0x4A6F/nixpkgs/master-139208";

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system}; in
      rec {
        devShell = pkgs.mkShell
          {
            buildInputs = with pkgs; [
              zola
            ];
          };
      }
    );
}
```

**Comment by Artturin** [comment]
>>> $ nix-shell -p zola
error: missing bootstrap url for platform aarch64-apple-darwin
(use '--show-trace' to show detailed location information)

is coming from https://github.com/NixOS/nixpkgs/blob/2491eb3bdcaf23a2af625d8698470f2a0eac6e72/pkgs/development/compilers/rust/bootstrap.nix#L8

and since the flake works you should update your channels

**Comment by cideM** [comment]
@0x4A6F I'm trying your commit but it might take a while for things to compile.
@Artturin I'll probably ask about this on Discourse since it's unrelated to this issue but I was hoping that my Darwin machine would run the `nixUnstable` I install through the flake that makes up my dotfiles. So hopefully taking channels out of the equation, but I think that's not how it works, so I'll look into this, thanks.

**Comment by Artturin** [comment]
> @Artturin I'll probably ask about this on Discourse since it's unrelated to this issue but I was hoping that my Darwin machine would run the `nixUnstable` I install through the flake that makes up my dotfiles. So hopefully taking channels out of the equation, but I think that's not how it works, so I'll look into this, thanks.



that should be possible but `nix-shell` uses channels while `nix shell` uses flakes. remove your channels to be sure that you're using flakes instead of channels

**Comment by cideM** [comment]
@0x4A6F works, thanks!

**Comment by winterqt** [comment]
Thanks @0x4A6F.

Here's another way of applying the fix that doesn't require a overlay, which works for my use case:
```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { self, nixpkgs, flake-utils }: flake-utils.lib.eachDefaultSystem (system:
    let
      pkgs = nixpkgs.legacyPackages.${system};
    in
    {
      devShell = pkgs.mkShell {
        nativeBuildInputs = with pkgs; [ (zola.overrideAttrs (old: { buildInputs = old.buildInputs ++ [ libsass ]; })) ];
      };
    }
  );
}
```
