### ISSUE TITLE
Changing KDE -> XFCE bricks installation

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#13927]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`)

Linux nixos 3.18.26 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

15.09.1113.23395c4 (Dingo)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.10

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"15.09.1113.23395c4"

## Describe your issue here

Attempted to install XFCE as the default desktop environment according to the instructions given here: https://nixos.org/wiki/Xfce.

### Expected result

XFCE would be properly installed and launched on next login.

### Actual result

Machine spontaneously restarts and deletes the demo user.

### Steps to reproduce

Download and install the 64-bit VirtualBox appliance. Launch. Add `services.xserver.desktopManager.xfce.enable = true;` to `/etc/nixos/configuration.nix`. Run `sudo nixos-rebuild switch`.

Then everything breaks. Reboots without a desktop manager. The demo/demo login no longer works.

**Comment by domenkozar** [comment]
How did you create the demo user?

**Comment by samuela** [comment]
It comes as the default with the VirtualBox appliance.

**Comment by samuela** [comment]
Any ideas?

**Comment by bjornfor** [comment]
@obadz: wrong issue ref? The above commit seem unrelated.

**Comment by obadz** [comment]
@bjornfor, nope, I was deliberately trying to fix this issue.

I'm the problem was that the `/etc/nixos/configuration.nix` that was inside the image wasn't the same as the one that was used to generate the image. For instance the one in the image didn't have a `demo` user…

Feel free to reopen if you can reproduce the issue but I think it's fixed.
