### ISSUE TITLE
pythonPackages.mypy: 0.812 -> 0.910

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#139319]
**Project description**
pythonPackages.mypy: *0.812 -> 0.910*

There's a dependency that is depending on this newest version.
I failed to upgrade `mypy` on my own.

**Metadata**
* Nix package: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/mypy/default.nix
* homepage URL: http://www.mypy-lang.org
* source URL: https://github.com/python/mypy
* license: mit

**Comment by yrd** [comment]
@superherointj Why was this closed? There doesn't seem to be a patch yet, right?
