### ISSUE TITLE
Flutter is out of date. Latest version is 2.5.1

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nixpkgs#139332]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: legacyPackages.x86_64-linux.flutter

current version: 2.2.1
desired version: 2.5.1

###### Notify maintainers

maintainers:
@babariviere 
@ericdallo 
@thiagokokada 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ericdallo** [comment]
Besides updating it we could setup a `updateScript` to easily auto update it

**Comment by ericdallo** [comment]
I opened https://github.com/NixOS/nixpkgs/pull/139374, it's not easy to create the updateScript though, I can try adding later in another PR
