### ISSUE TITLE
[meta] The perfect ruby development platforms

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixpkgs#13945]
This is a collection of notes that describe some of the current issues and possible improvement that could happen when doing ruby development with nix. I will update the description as I get feedback and once there is a clear idea of the path to follow I will split it into different issues and close this ticket.
## Current setup
- direnv to manage per-project environment
- each ruby project has an .envrc that looks a bit like:

``` bash
# This imports a couple of things from the nix-shell
# nokogiri always needs zlib and some times libiconv to install
# the ruby version varies as needed
use nix -p ruby_2_2 zlib libiconv mysql.lib
# this setups a GEM_HOME inside of $PWD/.direnv/ruby
layout ruby
```
- I need to `gem install bundler` in each project because `nixos.bundler` is tied to a specific ruby version
## Development issues

Bundix is perfect to derive a nix expressions from a Gemfile.lock during packaging but not super useful during development right now.

`bundle update` is a mechanism to find new gems based on the Gemfile, the rubygems index and a constraint solver on the published versions. Unfortunately it is not able to update the Gemfile.lock without installing the gems, so I end up installing the gems locally anyways (because changing the set of dependencies is quite a regular operation).

Bundler doesn't use nix to build packages so I don't benefit from the cache between projects (especially nokogiri). I also have to inject all the build dependencies manually instead of benefiting from the defaultGemConfig.

Maintaining a gemset.nix along-side the Gemfile.lock just adds more churn to the repo and it not always welcome when other people aren't using nix.
## Packaging issues

Ruby projects often have private git repos listed as dependencies. Right now the only way for nix to find these is if they are pre-loaded in the store with nix-prefetch-git (because of sandboxing, nix-daemon doesn't have access to the SSH_AUTH_SOCK). It's possible to use `bundix` to do that but I am not sure how to just to the pre-fetching step. Also, hydra..

Gemfile often have local paths are dependencies, either with the `gemspec` declaration or some time by pointing to sub-directories. bundlerEnv and bundix don't handle that at the moment. I think it could be fixed by copying ./. into the same derivation as the Gemfile and Gemfile.lock so not too hard to fix.

`cide` is a standalone ruby program but when I use it in other ruby projects the `GEM_HOME` environment variables seem to affect the behaviour of it. I also had to wrap the bundlerEnv in a standard mkDerivation because it was exposing other programs in the bin/ folder like "bundler". There must be a better way to create a derivation from a program and only expose it's binaries.

Rubygems is very well ingrained with ruby nowadays but I can't keep thinking that ruby packaging could be made much more lite-weight if the nix hook would just expand the ruby $LOAD_PATH with all the dependencies instead.

nitpick but it would be nice to convert the NIX_POST_EXTRACT_FILES_HOOK to a standard postUnpack hook.

A lot of other programming languages have a `pkgs/development/<lang>-modules` folder and a package set in pkgs/top-level/<lang>-packages.nix. For now I can only think of bundix and bundler to be useful in that set since we tend to manage project dependencies with the Gemfile.lock instead. Should we use that space for the gemconfig.nix instead ?
## Gimpse into the ideal ruby development
- `use nix -p ruby_2_2.dev` for the `.envrc` automatically loads the right ruby and bundler (or even better derived from the Gemfile `ruby "2.2.3"` directive or a `.ruby-version` file)
- `bundle install` and `bundle update` would use nix to build each gem as a derivation, and infer the dependencies based on the gemConfig

I think the way forward is to have some sort of integration between bundler and nix. It's going to be hard given how complex bundler already is.

I would also like to propose a way for the nix sandbox to import a user's SSH_AUTH_SOCK for seamless building of ssh dependencies. After all, it doesn't matter to the result how the derivation was fetched.
## Split tickets
- #13601 implements the ruby.dev idea
- #14027 implements moving the dev packages to ruby-modules

**Comment by zimbatm** [comment]
Inviting @manveru and @cstrahan to the discussion

**Comment by cstrahan** [comment]
I'll need to continue reading the rest of your post, but this bit:

> I need to gem install bundler in each project because nixos.bundler is tied to a specific ruby version

I believe that, at some point, I had `bundler` set up so that it wasn't tied to a particular Ruby, and then someone complained that it ought to work without a Ruby on `$PATH`, and then it was subsequently changed. I'm kind of 50/50 on that decision...

**Comment by cstrahan** [comment]
> Ruby projects often have private git repos listed as dependencies. Right now the only way for nix to find these is if they are pre-loaded in the store with nix-prefetch-git (because of sandboxing, nix-daemon doesn't have access to the SSH_AUTH_SOCK). It's possible to use bundix to do that but I am not sure how to just to the pre-fetching step. Also, hydra..

`fetchgitPrivate` (defined in [`pkgs/build-support/fetchgit/private.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/private.nix)) should work (though I haven't used it yet).

**Comment by cstrahan** [comment]
> I think the way forward is to have some sort of integration between bundler and nix. It's going to be hard given how complex bundler already is.

I think a lot of this will become easier if we can increase adoption of Nix for Ruby development. Getting a couple influential personalities to use and blog about Nix+Ruby would be huge. Hopefully, it would follow that the design of Bundler/Rubygems/etc would become more amenable to use under Nix.

**Comment by matthiasbeyer** [comment]
@zimbatm The PR you referred to was already merged. For me all these things sound nice and awesome, though I'd love to see some documentation on how this works and how this can be configured (if required) right inside the docs. Do you mind adding some documentation?

**Comment by zimbatm** [comment]
@cstrahan thanks for your ideas

@matthiasbeyer yes I will add some docs as part of this work. I'm not sure to keep ruby.dev or move it to rubyPackages yet.

**Comment by PierreR** [comment]
@zimbatm  Are you planning to add the doc at https://nixos.org/wiki/Ruby or is this page completely out-of-dated ? For the record, links are broken on that page and `bundler lock` has been working for me while  `bundler package --no-install` hasn't.

**Comment by gavinrogers** [comment]
@PierreR the wiki isn't maintained anymore? Arg that's why I've been running in circles for an hour

**Comment by peterhoeg** [comment]
I will gladly take it upon myself to update the Ruby article on the wiki as I too wasted a few hours trying to be able to work on my ruby projects. I'll whip something up over the weekend and let you guys know.

**Comment by gpyh** [comment]
Is there any updates on this? How is Ruby development now?

**Comment by peterhoeg** [comment]
I've been on vacation and it turns out that my wife doesn't think that doing Nix documentation on the laptop is "quality time together" even if I'm sitting right next to her, hence no progress yet. I take a stab at it this weekend.

**Comment by moretea** [comment]
@peterhoeg ping me if you want some feedback! I've got some ruby experience, and offer to be your guinea pig for this.

**Comment by manveru** [comment]
@peterhoeg @moretea if you need anything related to bundix or have suggestions for improvement, please let me know.

**Comment by peterhoeg** [comment]
@moretea and @manveru - I haven't had the time to do anything on this. Hopefully next weekend.

**Comment by grahamc** [comment]
> Gemfile often have local paths are dependencies, either with the gemspec declaration or some time by pointing to sub-directories.

this bit me today. Is there interest in having this work?

**Comment by myguidingstar** [comment]
Packages like `gollum` and `sup` also expose bundler to PATH (besides each package's desired executable). Those bundler versions cause "collision" error. I think `bundler` should be made build dependency, not run-time dependency.

**Comment by PierreR** [comment]
By the way, if I want to submit a PR for a ruby gem such as `puppet-lint` or `librarian`, how do I know where to put the `bundlerEnv` derivation in `nixpkgs` ? All these gems seems to be spread over (misc, tools, ...)

**Comment by AshtonKem** [comment]
Any progress on this? Having to redo the work that others have already done because I can't find the docs is frustrating.

**Comment by peterhoeg** [comment]
Hi @AshtonKem, no, no progress from this side on the writeup. 

You are absolutely right, the documentation is not great and there are a number of gotchas. I'll put it to the top of my list.

**Comment by mkaito** [comment]
I've spent the last few days trudging through outdated information about Ruby on Nix. I have yet to get things working quite the way I want. I'm fairly new to Nix, but experienced with Ruby. I'd like to help the situation, but I don't know how.

Some short notes on what I've found (and not found):

* Bundix seems to work, even though the last commit was 3 years ago.
* Gitlab is holding `bundler` to an outdated version. I think this is unacceptable.
* Writing a Nix expression that packages a Ruby web app (non-rails) has been non-trivial and previous art is scant even for Rails.
* I have yet to figure out how to *run* such an app, after packaging.

**Comment by zimbatm** [comment]
Just want to add that @nyarly has done a lot of good work on bundix, all the new features are thanks to him.

One of the next thing that I would like to see happening is to find a way to simplify the bundlerEnv / bundlerApp code if that's possible. Right now it's really too hairy for drive-by understanding. And nix in general is still better understood by reading what the code does.

**Comment by zimbatm** [comment]
I think the main reason is that there is too much complexity in the nix code and it's hard to know if it's incidental or not

**Comment by nyarly** [comment]
For what it's worth, I think there remains *some* incidental complexity in the `bundlerEnv` and `bundlerApp` expressions, but there are some assumptions made by the Ruby ecosystem that are being compensated for. I'd be interested in reviewing those to try to simplify, but I wouldn't expect more than a 10-20% improvement.
