### ISSUE TITLE
Package Request: verible

### ISSUE THREAD

**Issue by newAM** [NixOS/nixpkgs#139450]
**Project description**
Verible is a suite of SystemVerilog developer tools, including a parser, style-linter, and formatter.

**Metadata**

* homepage URL: https://github.com/chipsalliance/verible
* source URL: https://github.com/chipsalliance/verible
* license: asl20
* platforms: linux, darwin

**Notes**

I attempted this myself, and I cannot find a way to make the build behave.
I would be very grateful if someone could figure out a solution to this problem :)

* Attempt 1: Building from source: https://github.com/newAM/nixpkgs/blob/f9f2ccdd6b2545bfb66db480fe0c3c6ee43dfd36/pkgs/development/tools/misc/verible/default.nix
    * Not reproducible because markers are in the fetched packages.
        * https://discourse.nixos.org/t/bazel-enablenixhacks/15203
        * https://github.com/NixOS/nixpkgs/blob/12148886556c8a8b99e15af3cd27babd4e86f3b9/pkgs/development/tools/build-managers/bazel/bazel_4/default.nix
        * https://github.com/NixOS/nixpkgs/commit/a956694abac2dc81d6b148592ef6c993199f5cd3
* Attempt 2: Patching the pre-built elf: https://github.com/newAM/nixpkgs/blob/80f273bbb45860198f4b8ae43dafdb2d0e1aca4a/pkgs/development/tools/misc/verible/default.nix
    * Not ideal because it is not building from source.
    * Not ideal because the ubuntu docker images that supply these ELF files are not deterministic.

**Comment by chuangzhu** [comment]
Solved in #186224.
