### ISSUE TITLE
go_1_17 cannot build with -race

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#139496]
### Describe the bug

The Go 1.17 derivation in unstable cannot build binaries with the race detector enabled. Invocations of `go test -race <anything>` fail with linker errors.

### Steps To Reproduce
1. `git clone https://github.com/danderson/go-kdl` (any Go code will do, this is just a trivial project with some tests)
2. `nix-shell -p go_1_16`
3. `go test -race .` (note, this works)
4. `nix-shell -p go_1_17`
5. `go test -race .`

The build w/ race detector in 1.17 fails with:

```
# github.com/danderson/go-kdl.test
runtime/race(.text): relocation target getuid not defined
runtime/race(.text): relocation target pthread_self not defined
runtime/race(.text): relocation target sleep not defined
runtime/race(.text): relocation target usleep not defined
runtime/race(.text): relocation target abort not defined
runtime/race(.text): relocation target isatty not defined
runtime/race(.text): relocation target pthread_attr_getstack not defined
runtime/race(.text): relocation target sigaction not defined
runtime/race(.text): relocation target getrusage not defined
runtime/race(.text): relocation target syslog not defined
runtime/race(.text): relocation target confstr not defined
runtime/race(.text): relocation target getrlimit not defined
runtime/race(.text): relocation target pipe not defined
runtime/race(.text): relocation target sched_getaffinity not defined
runtime/race(.text): relocation target __sched_cpucount not defined
runtime/race(.text): relocation target pthread_attr_init not defined
runtime/race(.text): relocation target pthread_getattr_np not defined
runtime/race(.text): relocation target pthread_attr_destroy not defined
runtime/race(.text): relocation target exit not defined
runtime/race(.text): relocation target sysconf not defined
runtime/race(.text): relocation target setrlimit not defined
/nix/store/rcqw01kb9cm03bflmh4wacdq34vz8pbv-go-1.17.1/share/go/pkg/tool/linux_amd64/link: too many errors
unexpected fault address 0x7fd8044b8000
fatal error: fault
FAIL	github.com/danderson/go-kdl [build failed]
FAIL
```

This failure is the same regardless of the Go code being built. AFAICT, go_1_17 always fails to link runtime/race, which is included whenever `-race` is passed in.

### Expected behavior

`go test -race` should work.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.16, NixOS, 21.05.20210923.056a3c1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by danderson** [comment]
cc @NixOS/golang , hopefully that's the right way to ping the Nix Go maintainers?...

**Comment by danderson** [comment]
A clue: run `go test -race -x -work .`, which outputs the internal command invocations and doesn't clean up the build working directory. The failing subcommand is:

```
/nix/store/rcqw01kb9cm03bflmh4wacdq34vz8pbv-go-1.17.1/share/go/pkg/tool/linux_amd64/link -o $WORK/b001/go-kdl.test -importcfg $WORK/b001/importcfg.link -installsuffix race -s -w -buildmode=exe -buildid=kUbqCt6d4buqqcMNYSej/RZ5bSWwYAsfH9tMeFZJz/Ac876vAg_vk7sCXnghdE/kUbqCt6d4buqqcMNYSej -race -extld=gcc /home/dave/.cache/go-build/45/4524c6d13a757e61e0dfc2f788bc3409a2c0a9df5310cb0a1f392e05dfbd4b81-d
```

Adding `-linkmode=external` (to force delegating the linking step to gcc) makes the link succeed. My suspicion is that a refactor in 1.17 either broke locating glibc in -linkmode=internal, or the linker is hardcoding LSB-ish search paths somewhere new that the 1.17 derivation isn't patching out.

**Comment by Mic92** [comment]
Pure go packages seems to work:

```
$ nix-shell -p go_1_17
this path will be fetched (96.62 MiB download, 428.48 MiB unpacked):
  /nix/store/lkwdz4w2nj67fgld7blna578hakr049b-go-1.17.1
copying path '/nix/store/lkwdz4w2nj67fgld7blna578hakr049b-go-1.17.1' from 'https://cache.nixos.org'...

[nix-shell:~/git/ssh-to-age/cmd/ssh-to-age]$  go test -race .
ok      github.com/Mic92/ssh-to-age/cmd/ssh-to-age      0.031s

[nix-shell:~/git/ssh-to-age/cmd/ssh-to-age]$ which go
/nix/store/lkwdz4w2nj67fgld7blna578hakr049b-go-1.17.1/bin/go
```

**Comment by Mic92** [comment]
Actually your example (go-kdl) also seems to work for me:

```
[nix-shell:~/git/ssh-to-age/cmd/ssh-to-age/go-kdl]$ go test -race .
ok      github.com/danderson/go-kdl     (cached)
```

This is my go binary:

```
$ nix-store -r /nix/store/lkwdz4w2nj67fgld7blna578hakr049b-go-1.17.1/bin/go
```

**Comment by danderson** [comment]
Well that's confusing. I'm also pulling from nix unstable, and refreshed my sources just a few hours ago.

I'm on the same version, but a different derivation hash: `/nix/store/rcqw01kb9cm03bflmh4wacdq34vz8pbv-go-1.17.1`.

So, not sure where to go from here... It seems clearly something wrong with my system, but I don't know how to dig further.

**Comment by danderson** [comment]
Welp, deleted `~/.cache/go-build`, and now everything's fine. So, this sounds like some kind of upstream Go issue, nothing to do with Nix. Sorry for the noise.
