### ISSUE TITLE
services.nextcloud.home on different drive than nix store

### ISSUE THREAD

**Issue by benneti** [NixOS/nixpkgs#139469]
### Describe the bug
When I set services.nextcloud.home = "/home/nextcloud" nextcloud does not show the login screen but an error screen.
From the logs I conclude that it cannot read the configuration file.

The error message is
```
Sep 25 21:43:59 HOSTNAME nginx[30008]: 2021/09/25 21:43:59 [error] 30008#30008: *1 FastCGI sent in stderr: "PHP message: {"reqId":"EmhvBr5EaiJZ6oWE04H8","level":3,"time":"2021-09-25T19:43:59+00:00","remoteAddr":"192.168.178.184","user":"--","app":"PHP","method":"GET","url":"/","message":"touch(): Unable to create file /home/nextcloud/config/config.php because Permission denied at /nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php#246","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"","exception":{"Exception":"Error","Message":"touch(): Unable to create file /home/nextcloud/config/config.php because Permission denied at /nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php#246","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php","line":246,"function":"touch"},{"file":"/nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php","line":136,"function"...PHP message: {"reqId":"EmhvBr5EaiJZ6oWE04H8","level":3,"time":"2021-09-25T19:43:59+00:00","remoteAddr":"192.168.178.184","user":"--","app":"PHP","method":"GET","url":"/","message":"fopen(/home/nextcloud/config/config.php): failed to open stream: Permission denied at /nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php#247","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"","exception":{"Exception":"Error","Message":"fopen(/home/nextcloud/config/config.php): failed to open stream: Permission denied at /nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php#247","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Config.php","line":247,"function":"fopen"},{"file":"/nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/
Sep 25 21:43:59 HOSTNAME nginx[30008]: 2021/09/25 21:43:59 [error] 30008#30008: *1 FastCGI sent in stderr: "PHP message: {"reqId":"EmhvBr5EaiJZ6oWE04H8","level":3,"time":"2021-09-25T19:43:59+00:00","remoteAddr":"192.168.178.184","user":"--","app":"PHP","method":"GET","url":"/","message":"fopen(/nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/data/nextcloud.log): failed to open stream: No such file or directory at /nix/store/bc4fil96r3yllhpggk423p9c8s4s7hvg-nextcloud-22.1.1/lib/private/Log/File.php#84","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":""}" while reading upstream, client: 192.168.178.184, server: HOSTNAME, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/phpfpm/nextcloud.sock:", host: "HOSTNAME"
```
But the file exists and is also rw for nextcloud:
```
.rw-r----- 980 nextcloud 25 Sep 21:43 config.php
lrwxrwxrwx  64 nextcloud 25 Sep 21:43 override.config.php -> /nix/store/3blrgywpiv6bldf102rsjsmk9fz8fj22-nextcloud-config.php
```

Therefore I thought the problem might be that the directory is on another drive, i.e. the setup is
```
NAME  FSTYPE FSVER LABEL FSAVAIL FSUSE% MOUNTPOINT
sda
├─sda1
│     vfat   FAT32 boot  1.8G    22% /boot
└─sda2
      ext4   1.0   root    36.5G    61% /
sdb   btrfs        home  
sdc   btrfs        home    988.5G    65% /home
```

### Steps To Reproduce
1. Partition system as above
2. enable nextcloud
3. `nextcloud.home = "/home/nextcloud"`

### Expected behavior
It should work, even when home is on a different partition

### Additional context
The exact same configuration works when using the default nextcloud location `/var/lib/nextcloud` (in this case on the same partition as the store).

### Notify maintainers
@schneefux @bachp @globin @fpletz @ma27

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.6, NixOS, 21.05.20210923.d22c3a6 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210830_50a3586`
 - nixpkgs: `/nix/store/05w190gfgrvid91gqs68wj8arnbyxqd0-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aanderse** [comment]
I'm pretty sure the issue is that `phpfpm` has `ProtectHome = true;`. If you add this to your configuration does it work?
```
systemd.services.phpfpm-nextcloud.seeviceConfig.ProtectHome = pkgs.lib.mkForce false;
```

**Comment by benneti** [comment]
Indeed, thank you. 
I guess this is more a problem on my end then, and if you think it is appropriate feel free to close the issue.
after some digging it is probably a more elegant solution to bindmount /home/nextcloud to somewhere else and leave this setting as is.

**Comment by benneti** [comment]
Incase someone stumbles over this:
```
systemd.services = {
  phpfpm-nextcloud.serviceConfig.ProtectHome = pkgs.lib.mkForce "tmpfs";
  phpfpm-nextcloud.serviceConfig.BindPaths = [ "/home/nextcloud" ];
};
```
makes only the "nextcloud" directory accessible to the service not all directories in home

**Comment by aanderse** [comment]
Generally they don't recommend storing state in `/home`. Was there specific requirements that make this an ideal spot for you?

**Comment by benneti** [comment]
Just convenience, as you can see from my partition layout, my big data drive with raid is mounted as /home .
For some reason bind mounting did not work, but the tempfs solution did, as far as I understand like this the service cannot access /home too but sees a tempfs mounted /home with only /home/nextcloud which is rw .
https://github.com/systemd/systemd/issues/7153
I think this is good enough but if you have a better suggestion, please let me know.

**Comment by aanderse** [comment]
I was just curious. I'll mention that NixOS has excellent zfs support and if you thought there was value in it you should consider trying it out. It eliminates positioning headaches like the one you mention. I rub about 6 NixOS systemd with zfs and find it hard to imagine ever going back!

**Comment by benneti** [comment]
Oh thats actually a great idea. Maybe for the next setup but here I think I could also use btrfs subvolumes.
