### ISSUE TITLE
Add documentation for xorg override behavior

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixpkgs#13946]
``` nix
{
  nixpkgs.config = {
    packageOverrides = pkgs: {
      inherit (pkgs) xorg;
    };
  };
}
```

Adding this snippet to my NixOS `configuration.nix` causes everything that depends on xorg libs to be rebuilt. I would appreciate a mention of this in the docs since it severely slows down `nixos-rebuild` if the user has GUI apps in their systemPackages. It would also be cool to get an explanation of why it causes a rebuild.

**Comment by vcunat** [comment]
I think that might be because of self vs. super. Probably closely related: https://github.com/NixOS/nixpkgs/issues/13625.

**Comment by pikajude** [comment]
What does that issue have to do with this one?

**Comment by garbas** [comment]
it looks to me also that #13625 is unrelated. @vcunat you mean some other issue?

**Comment by Profpatsch** [comment]
This is outdated with the new overlay functionality, closing.
