### ISSUE TITLE
`xserver.enable` needs to be true for `programs.ssh.askPassword` to have an effect

### ISSUE THREAD

**Issue by papojari** [NixOS/nixpkgs#139546]
### Describe the bug
`xserver.enable` needs to be true for `programs.ssh.askPassword` to have an effect. I don't need an x server because I use Wayland.

### Steps To Reproduce
1. Set `xserver.enable` to false
2. Set `programs.ssh.askPassword` to `"${pkgs.x11_ssh_askpass}/libexec/ssh-askpass"` for example
3. Rebuild

### Expected behavior
`programs.ssh.askPassword` gets respected and therefore `$SSH_ASKPASS` is set

### Notify maintainers
@edolstra

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.66, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.11pre304626.8ecc61c91a5, home-manager, nixpkgs-21.05-darwin-21.05pre292686.c83cd13ac28"`
 - channels(papojari): `"nixos-21.05-21.05.3021.8b0b81dab17"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: programs.ssh.askPassword services.xserver.enable
```

**Comment by Flakebi** [comment]
#150270 added a `services.ssh.enableAskPassword` flag. Maybe that solves this issue?

**Comment by Artturin** [comment]
yep thanks
