### ISSUE TITLE
wxPython fails to run due to libraries not found

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#13956]
This is happening for me with nixpkgs/release-16.03, programs using wxPython 3 fail to load the wx module. Test case:

```
$ nix-shell --run python -p python27Packages.python python27Packages.wxPython30 python27Packages.setuptools
Python 2.7.11 (default, Dec  5 2015, 19:47:20) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/0kgakwdpr962qq4w0ak9cw8wcq00p4li-wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/nix/store/0kgakwdpr962qq4w0ak9cw8wcq00p4li-wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

Note, the setuptools dependency is a workaround for another issue.

Using ldd and `readelf -d` on `_core_.so` (in the same directory as `_core.py`) shows that it is linked against `libX11.so.6` and `libgdk-x11-2.0.so.0` but these are not accomodated in the `RUNPATH`. If one looks at the build output you can see that the library was not explicitly linked against these libraries (no `-lX11 -lgdk-x11-2.0`).

**Comment by FRidh** [comment]
@ambrop72 seeing #13958 is merged I assume this can be closed?

**Comment by ambrop72** [comment]
Hey, I suppose you can, just please don't forget about release-16.03.

**Comment by FRidh** [comment]
Done
