### ISSUE TITLE
Chromedriver can’t find libdbus and crashes

### ISSUE THREAD

**Issue by ivan-timokhin** [NixOS/nixpkgs#139547]
### Describe the bug
`chromedriver --version` crashes with the following message
```
/nix/store/akd5fl2a2xz4rvmhvs347w93yhj2gg1h-chromedriver-94.0.4606.41/bin/chromedriver: error while loading shared libraries: libdbus-1.so.3: cannot open shared object file: No such file or directory
```
(on master, nixpkgs-unstable, nixos-unstable and nixos-21.05)

### Steps To Reproduce
1. `nix-shell --pure -p chromedriver --command 'chromedriver --version'`

### Expected behavior
Chromedriver should report its version.

### Additional context
`git bisect` points towards commit 8d8b451f725b63edec06b033ff2bdaa2f0885b4e (so I guess new version added dependency on dbus)

### Notify maintainers

@cillianderoiste @marsam @primeos   

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.05.3216.ebf419e737b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3339.056a3c1fae3"`
 - channels(ivan): `"nixpkgs-unstable-21.11pre317666.1a56d76d718"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- chromedriver
# a list of nixos modules affected by the problem
module:
```

**Comment by compactcode** [comment]
I also encountered this issue. I couldn't come up with a workaround so switched my nix-shell from unstable back to 21.05.

**Comment by ivan-timokhin** [comment]
> I also encountered this issue. I couldn't come up with a workaround so switched my nix-shell from unstable back to 21.05.

The workaround I’ve settled on is to manually set `LD_LIBRARY_PATH`, like this:

```sh
LD_LIBRARY_PATH="$(nix-build '<nixos>' -A dbus.lib --no-out-link)/lib" chromedriver --version
```
