### ISSUE TITLE
VSCode language packs

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#139560]
**Project description**
It seems that language packs can't be installed using `programs.vscode.extensions`. There are 14 languages in total available.

I've tried to pack them myself but I am _really_ new to NixOS and failed :)

**Metadata**

* homepage URL: https://github.com/Microsoft/vscode-loc
* source URL: https://github.com/Microsoft/vscode-loc
* license: mit
* platforms: unix, linux, darwin

**Comment by cameronfyfe** [comment]
I have these added on my fork and will cleanup/submit a PR soon.
