### ISSUE TITLE
wg-quick doesn't work with systemd-resolved

### ISSUE THREAD

**Issue by g00pix** [NixOS/nixpkgs#139526]
### Describe the bug
If using systemd-resolved and using DNS in a Wireguard config, wg-quick will fail to add the DNS server because it uses the ``resolvconf`` command to do so. Because systemd-resolved overrides the ``resolvconf`` command with its own implementation and wg-quick calls the openresolv version of ``resolvconf``, applying a Wireguard config fails.

### Steps To Reproduce
1. Enable systemd-resolved with ``services.resolved.enable = true;``
2. Run ``wg-quick up {path to config}`` with a Wireguard config file with a DNS entry

### Expected behavior
wg-quick is supposed to call systemd-resolved's ``resolvconf`` command instead of openresolv's when systemd-resolved is enabled.

### Notify maintainers

@elseym @ericsagnes @mic92 @zx2c4 @globin @ma27 @d-xo

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.66, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Ma27** [comment]
Since `wg-quick` itself uses `resolvconf` and has problems with systemd-resolved, this doesn't seem like a NixOS bug to me.

**Comment by g00pix** [comment]
I'm sorry, maybe I wasn't clear enough. systemd-resolved has its own ``resolvconf`` implementation, it's just not in the path of ``wg-quick``. I tried locally by removing openresolv and adding systemd to the PATH of wg-tools and it works fine.

**Comment by Mic92** [comment]
Maybe we should not hard-code `resolveconf` at all or only add `openresolve` as a fall back path after the global path?

**Comment by zx2c4** [comment]
> Since wg-quick itself uses resolvconf and has problems with systemd-resolved, this doesn't seem like a NixOS bug to me.

wg-quick works with both openresolv's resolvconf and systemd's resolvconf, depending on what's in PATH. This is a Nix bug.

**Comment by Mic92** [comment]
> > Since wg-quick itself uses resolvconf and has problems with systemd-resolved, this doesn't seem like a NixOS bug to me.
> 
> wg-quick works with both openresolv's resolvconf and systemd's resolvconf, depending on what's in PATH. This is a Nix bug.

That's not the point if the system is configured to use systemd-resolved than we need to use systemd's resolvconf as it will use it's dbus api to set the nameserver. If wg-quick use the openresolv version it will attempt to update `/etc/resolv.conf`, which is incorrect.

**Comment by zx2c4** [comment]
Right, I think we're making the same point. Not an upstream bug. This about how Nix is configured. I'll let you all handle it.

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/139530 was reverted.

**Comment by ncfavier** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/166308 to finally fix this
