### ISSUE TITLE
qtile doesn't restart because the patch was removed

### ISSUE THREAD

**Issue by flexagoon** [NixOS/nixpkgs#139568]
### Describe the bug
In #134836, the patch `0003-Restart-executable.patch` was removed. Without this patch, trying to restart qtile just kills it and goes to the display manager, closing all of your apps.

### Steps To Reproduce
1. Log into qtile
2. Bind any key combination to `lazy.restart()`
3. Try to press this combination

### Expected behavior
Qtile restarts without closing any apps

### Screenshots
Qtile just quits and goes to the DM

### Notify maintainers
@jonringer @kamilchm 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.19, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre318500.51bcdc4cdaa"`
 - channels(flexagoon): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
module:
    services.xserver.windowManager.qtile
```

**Comment by flexagoon** [comment]
This patch can fix the issue

**Comment by jonringer** [comment]
I think most of this can be done in the wrapper. I was hoping that buildenv would solve the issue as the python interpreter would have all of the dependencies it would need.
