### ISSUE TITLE
ardour_5 fails to build: error: invalid conversion from 'volatile void*' to 'void*'

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#139549]
`ardour_5` fails to build as https://hydra.nixos.org/build/154269027

```
/build/ardour-ae0dcdc/libs/pbd/pbd/rcu.h:155:7:   required from here
/nix/store/4flv6b6bj6wc4jqbw74xp83ywpkc8mwp-glib-2.68.4-dev/include/glib-2.0/glib/gatomic.h:206:45: error: invalid conversion from 'volatile void*' to 'void*' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-fpermissive-fpermissive8;;]
  206 |     __atomic_compare_exchange_n ((atomic), &gapcae_oldval, (newval), FALSE, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST) ? TRUE : FALSE; \
      |                                             ^~~~~~~~~~~~~
      |                                             |
      |                                             volatile void*
/build/ardour-ae0dcdc/libs/pbd/pbd/rcu.h:167:14: note: in expansion of macro 'g_atomic_pointer_compare_and_exchange'
  167 |   bool ret = g_atomic_pointer_compare_and_exchange (&RCUManager<T>::x.gptr,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

There is an invasive change that fixed it in newer version: https://github.com/Ardour/ardour/commits/master/libs/pbd/pbd/g_atomic_compat.h . But maybe it's a good time to remove old `5` version?

### Notify maintainers

@cillianderoiste @fps 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ardour_5
```

**Comment by trofi** [comment]
Started with commit ce2beae8463776c381d823d397351619da284e1c `glib: 2.66.8 -> 2.68.1`

**Comment by prusnak** [comment]
@cillianderoiste @fps @mitchmindtree @magnetophon Is there a reason to still keep Ardour 5.x in nixpkgs?

**Comment by magnetophon** [comment]
> Is that still the case @magnetophon ?

Yes it is, but I'm not sure it's worth the effort to fix Ardour 5.

**Comment by prusnak** [comment]
I prepared a PR which drops ardour_5 if we decide to go this way: https://github.com/NixOS/nixpkgs/pull/139670
