### ISSUE TITLE
prometheus: 2.30.x

### ISSUE THREAD

**Issue by K900** [NixOS/nixpkgs#139619]
###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:
current version: 2.27.1
desired version: 2.30.3

###### Notify maintainers
maintainers: @benley @fpletz @globin @WilliButz @Frostman @kalbasit 

###### Note for maintainers

Please tag this issue in your PR.

I'd be happy to contribute somehow, but the build process is kind of weird, so it's probably better for an experienced person to handle this.

**Comment by K900** [comment]
Related: #141477

**Comment by FliegendeWurst** [comment]
Update was done in the linked PR.
