### ISSUE TITLE
`hardware.nvidia.powerManagement.enable` doesn't need `hardware.nvidia.prime.offload.enable`

### ISSUE THREAD

**Issue by jian-lin** [NixOS/nixpkgs#139630]
### Describe the bug
`hardware.nvidia.powerManagement.enable` doesn't need `hardware.nvidia.prime.offload.enable`.

According to the message of the assertion: "Fine-grained power management requires offload to be enabled", it may be a typo: `hardware.nvidia.powerManagement.finegrained` instead of `hardware.nvidia.powerManagement.enable`.

I have disable this assertion and used my laptop a few days, there's no problem.

### Expected behavior
`hardware.nvidia.powerManagement.enable` can be enabled when `hardware.nvidia.prime.offload.enable` is not enabled.

### Notify maintainers
@Baughn authored and @veprbl committed

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module: hardware/video/nvidia.nix
```

**Comment by Dulanjala007** [comment]
just now. I ran into this... trying to fix mpv player freeze on resume.
what should i do, custom derivation and setup nvidia kernel flags and copy systemd units?

**Comment by jian-lin** [comment]
This issue is fixed by https://github.com/NixOS/nixpkgs/commit/305ea3e9ede5429f2902c1543397cfb60db03e28#diff-28ea4da3a9a595f8bd1a37a555c229f998f3a11b0715ebc5842ba266384eba73
