### ISSUE TITLE
icedtea not working in chromium

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#13966]
At least on my 15.09 stable system, the Java plugin in Chromium does not seem to work. I've followed the documentation to [enable the java plugin in Chromium](https://nixos.org/wiki/Enable_Browser_Plugins#Java) specifically by adding configuration to my `configuration.nix` like:

```
  nixpkgs.config = {
    allowUnfree = true;

    chromium = {
      enablePepperFlash = true;
      icedtea = true;
    };
  };
```

However, visiting http://www.java.com/en/download/installed.jsp shows that it's not installed. Looking at the derivation, it doesn't seem like the `icedtea` option even exists. Is there some reason for this?

**Comment by zimbatm** [comment]
Looking in the git history of the chromium package I don't even see a mention to Java. The plugin is not supported and the wiki is wrong unfortunately.
