### ISSUE TITLE
nix-env not finding package phpfpm 

### ISSUE THREAD

**Issue by vyscond** [NixOS/nixpkgs#13961]
## Basic info

To make sure that we are on the same page:

* Kernel: `Linux nixos 3.18.26 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 i686 GNU/Linux`
* System: NixOS: `15.09.1113.23395c4 (Dingo)`
* Nix version: `nix-env (Nix) 1.10`
* Nixpkgs version: `"15.09.1113.23395c4"`

## Describe your issue here

I want to install __phpfpm__ package with `nix-env -i` or `nox`. _(I've checked too that the 15.09 release contains the phpfpm.nix file.)_

### Expected result

Get php-fpm running

### Actual result

Both commands (nix-env and nox) are not finding the phpfpm.nix file merged on the repo.

1 - `nix-env -i phpfpm` results in `error: selector ‘phpfpm’ matches no derivations`
2 - `nox phpfpm` results in empty output

### Steps to reproduce

1 - `nix-env -i phpfpm`
2 - `nox phpfpm`

**Comment by jgillich** [comment]
php-fpm is actually part of the `php` package, so `nix-env -i php`. To find packages, there is http://nixos.org/nixos/packages.html

**Comment by vyscond** [comment]
Hum. So i don't even need to install manually. Thanks for the answer and sorry about the silly question :/

**Comment by jgillich** [comment]
No worries, I remember having similar issues when I got started with Nix. :)
