### ISSUE TITLE
The screen backlight of my laptop cannot be changed using nvidia and gnome wayland

### ISSUE THREAD

**Issue by jian-lin** [NixOS/nixpkgs#139627]
### Describe the bug

My laptop (thinkpad x1 extreme gen2) has an intel gpu and an nvidia gpu. I disable the intel gpu in BIOS and use the nvidia gpu alone because in this case, it is much easier for me to use external display.

On nixos, I cannot change the backlight using gnome wayland session. I can if I switch to x11 session.

I also have gentoo installed on my laptop, and using gentoo I can change the backlight.

I find that on nixos, `/sys/class/backlight` is empty, both on wayland and x11 session. However, on gentoo, it has a item and I can write to one file to change my screen backlight.

### Steps To Reproduce
1. set a laptop to only use an nvidia card
2. install nixos
3. login to gnome wayland session

### Expected behavior
I can change the screen backlight using gnome's icon.

### Screenshots
the icon to change screen backlight doesn't show up.
![cannot_change_screen_backlight](https://user-images.githubusercontent.com/75130626/134912918-f5d80524-7e0c-4f64-a027-1241f84167ed.png)

### Notify maintainers
no maintainer for now. @baracoder drops the maintainership a few days ago

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
send the output of `nix-shell -E 'with (import <nixpkgs>{}); inxi.override { withRecommends = true; }' --run 'inxi -Gxx'` on both distros

**Comment by jian-lin** [comment]
# on nixos

```
Graphics:  Device-1: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] vendor: Lenovo driver: nvidia v: 470.74 bus-ID: 01:00.0 
           chip-ID: 10de:1f91 
           Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:2 chip-ID: 13d3:56ba 
           Display: wayland server: X.Org 1.21.1.2 compositor: gnome-shell driver: loaded: nvidia 
           note: n/a (using device driver) resolution: 3840x2160~60Hz s-dpi: 96 
           OpenGL: renderer: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 v: 4.6.0 NVIDIA 470.74 direct render: Yes 
```

# on gentoo

```
Graphics:  Device-1: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] vendor: Lenovo driver: nvidia v: 470.74 bus-ID: 01:00.0 
           chip-ID: 10de:1f91 
           Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo bus-ID: 1-8:2 chip-ID: 13d3:56ba 
           Display: wayland server: X.Org 1.21.1.2 compositor: gnome-shell driver: loaded: nvidia unloaded: modesetting 
           alternate: fbdev,nouveau,nv,vesa resolution: 3840x2160~60Hz s-dpi: 96 
           OpenGL: renderer: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 v: 4.6.0 NVIDIA 470.74 direct render: Yes 
```

**Comment by Artturin** [comment]
try
```
boot.kernelParams = [ "nvidia.NVreg_EnableBacklightHandler=1" ];
```

**Comment by jian-lin** [comment]
`nvidia.NVreg_EnableBacklightHandler=1` doesn't work. Also, I find a random [post](https://forums.developer.nvidia.com/t/nvreg-enablebacklighthandler-removed/176213/2) says this option has been removed.

On gentoo, it works without any kernel options related to nvidia.

**Comment by Artturin** [comment]
how about `nvidia.NVreg_RegistryDwords=EnableBrightnessControl=1`

**Comment by jian-lin** [comment]
It doesn't work.

**Comment by Artturin** [comment]
send the output of this command on both distros
```
#!/usr/bin/env bash
cat /proc/modules | cut -f 1 -d " " | while read module; do \
 echo "Module: $module"; \
 if [ -d "/sys/module/$module/parameters" ]; then \
  ls /sys/module/$module/parameters/ | while read parameter; do \
   echo -n "Parameter: $parameter --> "; \
   cat /sys/module/$module/parameters/$parameter; \
  done; \
 fi; \
 echo; \
done
```

**Comment by jian-lin** [comment]
[nixos_module.txt](https://github.com/NixOS/nixpkgs/files/7253877/nixos_module.txt)
[gentoo_module.txt](https://github.com/NixOS/nixpkgs/files/7253878/gentoo_module.txt)

**Comment by Artturin** [comment]
on gentoo
```
ls -l /sys/class/backlight/
dmesg | grep -i backlight
```
and could you send your kernel config?

**Comment by jian-lin** [comment]
[kernel_config_gentoo.txt](https://github.com/NixOS/nixpkgs/files/7254057/kernel_config_gentoo.txt)
[kernel_config_nixos.txt](https://github.com/NixOS/nixpkgs/files/7254058/kernel_config_nixos.txt)

**Comment by Dulanjala007** [comment]
I also have this problem with my Asus Rog GL502vmk with Nvidia GTX 1060 (it's the only gpu in the laptop).
with kernel param  "acpi_backlight=vendor" somehow gnome gets the ability to control the backlight via it's controls.
but it didn't create any backlight devices in "/sys/class/backlight". so brightness at 100% at every boot..
i am trying to fix it but no progress, can't find any info on what creates the nvidia_0 device in backlight sys dir..

**Comment by jian-lin** [comment]
I find that this issue doesn't exist on 495b19d5b3e62b4ec7e846bdfb6ef3d9c3b83492. My Nvidia driver version is 515.65.01 and kernel version is 5.15.61.
