### ISSUE TITLE
why does got not contain the send-email subcmd?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#13973]
The got distribution does normally contain the subcommand 'send-email' ... But it does not on my nixos machines.

Why is that?

**Comment by matthiasbeyer** [comment]
Maaan autocorrect on my mobile device. I meant GIT!

**Comment by joelmo** [comment]
gitFull has it

**Comment by matthiasbeyer** [comment]
ACK.
