### ISSUE TITLE
Installing oraclejdk is worse than on Debian

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#13978]
Since I believe the objective is to be better than Debian, I am filing this as a bug. 

```
***
Unfortunately, we may not download file jdk-8u65-linux-x64.tar.gz automatically.
Please, go to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html, download it yourself, and add it to the Nix store
using either
  nix-store --add-fixed sha256 jdk-8u65-linux-x64.tar.gz
or
  nix-prefetch-url --type sha256 file://path/to/jdk-8u65-linux-x64.tar.gz

***
```

In Debian there is some flag you can set to automatically accept the agreement, which is used by all other configuration management solutions. A comparable solution should also be present in Nix. 

One such a solution would be adding an additional package named `oracle_yes_I_agree_to_the_terms` or something which is similar to what Debian is doing.

**Comment by copumpkin** [comment]
We talked about doing something like that but I think people voted against it due it being slightly legally iffy. I'd be all for adding it, but I see it more as a community issue than a technical one.

**Comment by gmarmstrong** [comment]
Relevant: https://github.com/NixOS/nixpkgs/pull/9234

**Comment by tomodachi94** [comment]
Oracle JDKs were removed in #353043.
