### ISSUE TITLE
Package request: sqlx-cli

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#139767]
**Project description**
The [sqlx-cli](https://github.com/launchbadge/sqlx/tree/master/sqlx-cli) is used to generate the database and migrations when working with the `sqlx` Rust crate.

**Metadata**

* homepage URL: https://github.com/launchbadge/sqlx/tree/master/sqlx-cli
* source URL: https://github.com/launchbadge/sqlx/tree/master/sqlx-cli
* license: mit | apache2
* platforms: all

**Comment by fabaff** [comment]
Is [available](https://search.nixos.org/packages?channel=unstable&show=sqlx-cli&from=0&size=50&sort=relevance&type=packages&query=sqlx-cli) in `unstable`.

**Comment by mainrs** [comment]
I’ve missed that, I’ve only looked at the top level of the tools folder (where diesel was located). Is there a way to overwrite the features that the crate uses during compilation? The crate uses feature flags to add/remove support for database backends.

**Comment by legendofmiracles** [comment]
You can do that via an overlay:
```nix
sqlx-cli.overrideAttrs (old: { cargoBuildFlags = (old.cargoBuildFlags or []) ++ ["--feature=test"]; })
```
Unfortunately, you will have to recompile sqlx-cli after that.

**Comment by mainrs** [comment]
Thanks for helping me out!
