### ISSUE TITLE
[package request] beekeeper studio

### ISSUE THREAD

**Issue by er-jpg** [NixOS/nixpkgs#139899]
**Project description**
Open Source SQL Editor and Database Manager for MySQL, Postgres, SQLite, SQL Server, and more.

**Metadata**

* homepage URL: https://www.beekeeperstudio.io/
* source URL: https://github.com/beekeeper-studio/beekeeper-studio
* license: mit
* platforms: unix

**Comment by Alexnortung** [comment]
I think this issue can be closed, since it has been merged?
