### ISSUE TITLE
[PACKAGE REQUEST] Sharenix

### ISSUE THREAD

**Issue by alx-alexpark** [NixOS/nixpkgs#139894]
**Project description**
Sharex but ported to linux. Its a great screenshot tool which lets you upload your screenshots to custom servers.

**Metadata**

* homepage URL: N/A
* source URL: https://github.com/Francesco149/sharenix
* license: gpl3.0
* platforms: im not sure, i just know it works with linux

**Comment by Kranzes** [comment]
Hey i tried packaging this but the author of sharenix isn't providing much information and i cant figure out why its not building, if you want to keep debugging this, here is the expression i wrote: https://gist.github.com/Kranzes/f1a9825ab641675a821d81c3924ae2f1

**Comment by l3gacyb3ta** [comment]
I might be able to take a look at this soon!

**Comment by Kranzes** [comment]
Also @alx-alexpark you should take a look at [flameshot](https://github.com/flameshot-org/flameshot), it has native linux support and even has a home-manger module already.

**Comment by alx-alexpark** [comment]
@Kranzes I already use flameshot, its just that I got a https://upload.systems account and want to be able to upload there

**Comment by alx-alexpark** [comment]
@Kranzes Try fetchtarbal, fetching the latest tarball from releases

**Comment by Kranzes** [comment]
> @Kranzes Try fetchtarbal, fetching the latest tarball from releases

I tried using the released first and they are pretty outdated and dont include go modules so i did not bother.

**Comment by alx-alexpark** [comment]
Oh rip

**Comment by Kranzes** [comment]
> @Kranzes I already use flameshot, its just that I got a https://upload.systems account and want to be able to upload there

I'd suggest requesting a feature with the ability to use upload.systems as the hoster to flameshot, the end result of that will be much better than on sharenix.

**Comment by alx-alexpark** [comment]
@l3gacyb3ta Try looking at the gist, I personally can't really write nix expressions

**Comment by alx-alexpark** [comment]
> I'd suggest requesting a feature with the ability to use upload.systems as the hoster to flameshot, the end result of that will be much better than on sharenix.
Good idea

**Comment by Kranzes** [comment]
I didn't look much through the flameshot code-base (mostly because i don't use it) but maybe you could make something like this: https://github.com/flameshot-org/flameshot/tree/master/scripts/upload_services ?

**Comment by alx-alexpark** [comment]
@Kranzes Il try

**Comment by alx-alexpark** [comment]
@Kranzes Try writing a derivative, instead of building use the binary

**Comment by Kranzes** [comment]
That's not preferred but sure, I will give it a try tomorrow!

**Comment by alx-alexpark** [comment]
Thanks :), im very excited to start using upload.systems because funi domains haha

**Comment by alx-alexpark** [comment]
@Kranzes I actually wanna try to write the derivation, do you  know how it would be done? and how would i test it

**Comment by Kranzes** [comment]
Writing an expression for a precompiled library can get a bit of a tricky thing, there are some docs about it on the not so good unofficial wiki and a hint is to use autopatchelf.

**Comment by alx-alexpark** [comment]
Ok, Its only 3 binaries. Also why can't i just run binaries on nix

**Comment by Kranzes** [comment]
Because nix does not follow the FHS so some things are missing.

**Comment by alx-alexpark** [comment]
Easy way to run binaries (workaround) for nix? without needing to write a derivation for everything?

**Comment by Kranzes** [comment]
Steam-run

**Comment by alx-alexpark** [comment]
It doesent work :(
```❯ steam-run /usr/bin/sharenix                                    
/nix/store/rr386h5i75k3gxg9qry1v9j18z9z4cg5-steam-run: line 15: /usr/bin/sharenix: No such file or directory```

**Comment by alx-alexpark** [comment]
@Kranzes Progress on that deviration? Im bored lol and waiting to use the funny screenshot thingy

**Comment by alx-alexpark** [comment]
What i got so far
```
{ stdenv, fetchurl }:

stdenv.mkDerivation {
  name = "sharenix";
  src = fetchurl {
    url = "https://github.com/Francesco149/sharenix/releases/download/0.12.0a/sharenix-x86_64.tar.xz";
    sha256 = "c238bc06cd85d174b57c00c02f574902aead98a162fafb24bfbaaaac3058fd13";
  };
}

```

**Comment by Kranzes** [comment]
That's not much, this just fetches the src (through fetchurl which isnt preferred when fetchFromGitHub is possible) and look for a makefile, which does not exist for this project. Please read the nixpkgs manual.

**Comment by alx-alexpark** [comment]
@Kranzes 
```
{ stdenv
, fetchurl
, autoPatchelfHook
# , libgtk-x11                 
# , libgdk-x11                          
# , libpangocairo                
# , libatk                            
# , libcairo                         
# , libgdk_pixbuf                    
# , libgio                          
# , libpangoft                      
# , libpango                         
# , libgobject                       
# , libglib   
# , libfontconfig
# , libfreetype  
# , libgthread  
}:

stdenv.mkDerivation {
  name = "sharenix";
  src = fetchurl {
    url = "https://github.com/Francesco149/sharenix/releases/download/0.12.0a/sharenix-x86_64.tar.xz";
    sha256 = "c238bc06cd85d174b57c00c02f574902aead98a162fafb24bfbaaaac3058fd13";
  };

  nativeBuildInputs = [
    autoPatchelfHook
  ];

  autoPatchelfIgnoreMissingDeps = true;

  buildInputs = [
    # libgtk-x11
    # libgdk-x11
    # libpangocairo  
    # libatk
    # libcairo
    # libgdk_pixbuf
    # libgio
    # libpangoft
    # libpango
    # libgobject
    # libglib
    # libfontconfig
    # libfreetype
    # libgthread
  ];

  sourceRoot = "sharenix-x86_64";

  installPhase = ''
    install -m755 -D sharenix $out/bin/sharenix
    install -m755 -D src/sharenix-section $out/bin/sharenix-section
    install -m755 -D src/sharenix-window $out/bin/sharenix-window
  '';



}
```

Made some changes, but whenever i uncomment those dependencies at the top this happens
![image](https://user-images.githubusercontent.com/63802868/135726648-6353e5cf-b913-4bdb-a69a-ba49af3655d1.png)

**Comment by alx-alexpark** [comment]
@Kranzes Progress on the deriv?

**Comment by alx-alexpark** [comment]
I manually set it up using patchelf
