### ISSUE TITLE
BOINC client package: please add to client the UI manager

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#13987]
To the my disappointment I found that BOINC client package does't contains UI manager.
Could you please add.

**Comment by jgillich** [comment]
Probably because nobody wanted/needed it so far. If you do, why don't you package it yourself? :)

**Comment by siddhanathan** [comment]
Seems like an update caused boincmgr to not be compiling successfully. The newer boinc releases require wxGTK-3 to be compiled with webkit and webview support. Without it, boincmgr won't be built.

**Comment by olejorgenb** [comment]
diff --git a/pkgs/applications/science/misc/boinc/default.nix b/pkgs/applications/science/misc/boinc/default.nix
    index 716d6d9687..2b114d3139 100644
    --- a/pkgs/applications/science/misc/boinc/default.nix
    +++ b/pkgs/applications/science/misc/boinc/default.nix
    @@ -1,6 +1,7 @@
     { fetchFromGitHub, stdenv, autoconf, automake, pkgconfig, m4, curl,
    -mesa, libXmu, libXi, freeglut, libjpeg, libtool, wxGTK, xcbutil,
    -sqlite, gtk2, patchelf, libXScrnSaver, libnotify, libX11, libxcb }:
    +mesa, libXmu, libXi, freeglut, libjpeg, libtool, wxGTK30, xcbutil,
    +sqlite, gtk3, patchelf, libXScrnSaver, libnotify, libX11, libxcb, 
    +zlib, webkitgtk216x }:
     
     let
       majorVersion = "7.8";
    @@ -22,8 +23,9 @@ stdenv.mkDerivation rec {
       nativeBuildInputs = [ libtool automake autoconf m4 pkgconfig ];
     
       buildInputs = [
    -    curl mesa libXmu libXi freeglut libjpeg wxGTK sqlite gtk2 libXScrnSaver
    -    libnotify patchelf libX11 libxcb xcbutil
    +    curl mesa libXmu libXi freeglut libjpeg sqlite gtk3 libXScrnSaver
    +    libnotify patchelf libX11 libxcb xcbutil zlib
    +    (wxGTK30.override { withWebKit = true; withGtk2 = false; })
       ];
     
       NIX_LDFLAGS = "-lX11";

Builds on 96457d26dded05bcba8e9fbb9bf0255596654aab but I haven't managed to use the gui manager to contorl to the boinc _system service_ (haven't tried running the service as myself)
