### ISSUE TITLE
The interface of the Dokuwiki module has been updated without providing any migration hints

### ISSUE THREAD

**Issue by NinjaTrappeur** [NixOS/nixpkgs#139853]
### Describe the bug

https://github.com/NixOS/nixpkgs/pull/132551 heavily changes the interface of the Dokuwiki NixOS module without providing any hints about which actions should be taken to properly migrate.

All you get after bumping your nixpkgs pin is

```
error: The option `services.dokuwiki.REDACTED.enable' does not exist. Definition values:
       - In `<unknown-file>': true
(use '--show-trace' to show detailed location information)
```

This is not a helpful error message.

We should provide some indication about how to migrate from the 21.05-compliant conf to this new webserever-independent interface through a eval-time warning message. Worst case scenario, we should at least point to the release notes. See https://nixos.org/manual/nixos/stable/index.html#sec-assertions for more information about how to emit such a warning. We should list all the deleted/moved options and trigger a helpful warning for each of them.

We should address this before the ~21.09~ 21.11 branchoff.

Edit: I indeed meant 21.11 branchoff here.

cc @happysalada @onny @1000101.

**Comment by happysalada** [comment]
You're right, I was looking for somebody with a different config to test that PR. I didn't know about the warnings option.

I think you are talking about the 21.11 branchoff right ?

@onny how are you for time ? I'm available for review/ hints if you need.

**Comment by onny** [comment]
@NinjaTrappeur I took the concept with support of multiple sites and webservers from here https://github.com/NixOS/nixpkgs/pull/84446 and it already includes a migration warning:

```
{ pkgs, ... }: {
  services.dokuwiki = {
    "wiki.example.org" = {
      aclUse = false;
      superUser = "onny";
    };
  };
}
``` 
will result in:
```
warning: services.dokuwiki."wiki.project-insanity.org" is deprecated use services.dokuwiki.sites."wiki.project-insanity.org"
```
which is fine. I see that you're using `services.dokuwiki.<NAME>.enable` which somehow got lost. I'll have to add it again and that the deprecation warning should work as expected.

Thank you for noticing!

**Comment by onny** [comment]
@NinjaTrappeur Maybe you can give it a try :) https://github.com/NixOS/nixpkgs/pull/140060
