### ISSUE TITLE
attribute ‘dfVersion’ missing while evaluating dwarf_fortress

### ISSUE THREAD

**Issue by regnat** [NixOS/nixpkgs#13985]
## Basic info

To make sure that we are on the same page:

* Kernel: Linux ansegisel 4.4.2 #1-NixOS SMP Wed Feb 17 20:31:25 UTC 2016 x86_64 GNU/Linux
* System: NixOS 16.09pre-git
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre-git (or any checkout from d3b62c)

## Describe your issue here

When nix tries to evaluate the `dwarf_fortress` derivation (ie when trying to install it, to use nox, to run nix-env -i foo, ...), it fails with the error
```
attribute ‘dfVersion’ missing, at /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/wrapper/default.nix:39:20
```

### Expected result

Anything not failing

### Actual result

Full backtrace : 

```
error: while evaluating the attribute ‘dwarf-fortress.override’ at /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/default.nix:16:5:
while evaluating ‘callPackageWith’ at /home/regnat/.nix-defexpr/local/lib/customisation.nix:93:35, called from /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/default.nix:16:22:
while evaluating ‘makeOverridable’ at /home/regnat/.nix-defexpr/local/lib/customisation.nix:54:24, called from /home/regnat/.nix-defexpr/local/lib/customisation.nix:97:8:
while evaluating anonymous function at /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/wrapper/default.nix:1:1, called from /home/regnat/.nix-defexpr/local/lib/customisation.nix:56:12:
while evaluating anonymous function at /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/wrapper/default.nix:39:17, called from /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/wrapper/default.nix:39:8:
attribute ‘dfVersion’ missing, at /home/regnat/.nix-defexpr/local/pkgs/games/dwarf-fortress/wrapper/default.nix:39:20
```

### Steps to reproduce

```
nix-env -i foo
```

Cc @abbradar

**Comment by abbradar** [comment]
Hm, that's strange -- I can't reproduce this on `master` nor on the unstable channel (I have `dwarf_fortress` installed). I also don't have `d3b62c` commit. Can you please specify exact branch and revision?

**Comment by regnat** [comment]
Oops my bad, the commit is d3b642ce9ad056b60d8cfa576dd3fa800ec57ba4, not d3b62c.

I get this error on any revision containing this commit.

I'll try on a VM see if I can reproduce it on a fresh install

**Comment by regnat** [comment]
Ok, I can't reproduce it on a VM, and if I put it on environment.systemPackages, it installs without problem :unamused:

I suppose the problem comes from my setup.
I'll still investigate a little bit, and if I don't figure where it comes from, I close the issue

**Comment by abbradar** [comment]
Can you describe your workflow? Maybe we can notice something unusual.

**Comment by regnat** [comment]
Woops sorry, your message has been lost behind a lot of other stuff

I use a local checkout of nixpkgs (which include some personal modifications, but I also tested with the upstream branch).

My NIX_PATH is defined as `nixpkgs=/home/regnat/.nix-defexpr/local/:/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels`.

Not sure it matters, but my computer is managed via nixops.

Wed, Mar 23, 2016 at 01:32:45PM -0700, Nikolay Amiantov(notifications@github.com) a écrit:

**Comment by abbradar** [comment]
Hm, let's test this:

1. Make a local checkout of `nixpkgs` (master or unstable) to, say, `/foo/nixpkgs`
2. `nix-env -i dwarf-fortress -f /foo/nixpkgs`
3. `nix-env -i dwarf-fortress -f /home/regnat/.nix-defexpr/local/`
4. `nix-env -i dwarf-fortress`

**Comment by regnat** [comment]
Got the same error even with a fresh checkout of nixpkgs and NIX_PATH (and all the NIX_* variables except NIX_REMOTE) unset...

**Comment by abbradar** [comment]
Hrm, and `nix-build -A dwarf-fortress /foo/nixpkgs`?

**Comment by regnat** [comment]
Same thing too

**Comment by abbradar** [comment]
Now _that's_ interesting.

Can you please install `nix-repl`? Then do this:
```
> nix-repl /foo/nixpkgs
dwarf-fortress
```

**Comment by regnat** [comment]
Had already done that.
And it raises the same error :unamused:

**Comment by abbradar** [comment]
Hm, can you please paste it? I'm interested in line number.

**Comment by regnat** [comment]
From a checkout of the master branch I got : 
```
error: while evaluating the attribute ‘dwarf-fortress.override’ at /tmp/nixpkgs/pkgs/games/dwarf-fortress/default.nix:16:5:
while evaluating ‘callPackageWith’ at /tmp/nixpkgs/lib/customisation.nix:93:35, called from /tmp/nixpkgs/pkgs/games/dwarf-fortress/default.nix:16:22:
while evaluating ‘makeOverridable’ at /tmp/nixpkgs/lib/customisation.nix:54:24, called from /tmp/nixpkgs/lib/customisation.nix:97:8:
while evaluating anonymous function at /tmp/nixpkgs/pkgs/games/dwarf-fortress/wrapper/default.nix:1:1, called from /tmp/nixpkgs/lib/customisation.nix:56:12:
while evaluating anonymous function at /tmp/nixpkgs/pkgs/games/dwarf-fortress/wrapper/default.nix:39:17, called from /tmp/nixpkgs/pkgs/games/dwarf-fortress/wrapper/default.nix:39:8:
attribute ‘dfVersion’ missing, at /tmp/nixpkgs/pkgs/games/dwarf-fortress/wrapper/default.nix:39:20
```

**Comment by abbradar** [comment]
Please try to evaluate (via `nix-repl`) those:

1. `dwarf-fortress-packages.dwarf-fortress-original.dfVersion`
2. `dwarf-fortress-packages.dfhack.dfVersion`

**Comment by regnat** [comment]
Both evaluate (to "0.42.06").

And `dwarf-fortress-packages.dwarf-fortress-original` and `dwarf-fortress-packages.dfhack` evaluate too

**Comment by abbradar** [comment]
Let's do more debugging if you have some time.

Please apply this patch:
```
--- a/pkgs/games/dwarf-fortress/wrapper/default.nix
+++ b/pkgs/games/dwarf-fortress/wrapper/default.nix
@@ -36,7 +36,7 @@ let
   };
 in
 
-assert lib.all (x: x.dfVersion == dwarf-fortress-original.dfVersion) pkgs;
+#assert lib.all (x: x.dfVersion == dwarf-fortress-original.dfVersion) pkgs;
 
 stdenv.mkDerivation rec {
   name = "dwarf-fortress-${dwarf-fortress-original.dfVersion}";
@@ -65,4 +65,6 @@ stdenv.mkDerivation rec {
   '';
 
   preferLocalBuild = true;
+
+  passthru.pkgs = pkgs;
 }
```

And then let's try to evaluate `map (x: x.name) dwarf-fortress-packages.dwarf-fortress.pkgs`

**Comment by regnat** [comment]
Ok, I got the origin of the error...

I have an override defining `theme` as `pkgs.xfce.gtk_xfce_engine` in my configuration.nix, and it is passed as argument to the derivation. That's the packages which doesn't have the dfVersion.

Sorry for the stupid bug :/

**Comment by abbradar** [comment]
Good to know you found it!
