### ISSUE TITLE
XFCE auto mounting stopped working

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#1398]
Plugged in USB3.0 32GB stick formatted with ext4 and it wasn't auto-mounted.

```
$ ps aux | grep udisk
499       2408  0.0  0.0 297120  3852 ?        Sl   Dec17   0:00 /nix/store/nlpdr7k0mkvja3jpkf5w0wwhfwycbjvd-gvfs-1.14.2/libexec/gvfs-udisks2-volume-monitor
root      2416  0.0  0.0 419396  4200 ?        Ssl  Dec17   0:01 /nix/store/fw8b3hwmm8zqljnhw463rbfzgdcikq4n-udisks-2.1.0/lib/udisks2/udisksd --no-debug
499       2637  0.0  0.0 296992  4288 ?        Sl   Dec18   0:00 /nix/store/nlpdr7k0mkvja3jpkf5w0wwhfwycbjvd-gvfs-1.14.2/libexec/gvfs-udisks2-volume-monitor
root     26317  0.0  0.0 110104  1092 pts/2    S+   14:34   0:00 grep udisk
```

```
$ nixos-version 
14.02pre35786.9fc5753 (Baboon)
```

**Comment by andrewrk** [comment]
Auto-mounting does not work for me, and this is important to me.

version: 15.06pre64030.e1af50c (Dingo)

My [nix config](https://github.com/andrewrk/dotfiles/blob/d4f2b5bd5e4254b6f37738815890a0e075c0f441/nixconfigs/configuration.nix). 

```
$ ps aux | grep udisk
andy      1194  0.0  0.0 370224  6500 ?        Sl   23:38   0:00 /nix/store/ny19ab5sz0x13a809kz61nr5y5wjmbbz-gvfs-1.22.2/libexec/gvfs-udisks2-volume-monitor
root      1197  0.0  0.0 351112  6812 ?        Ssl  23:38   0:00 /nix/store/4vzpbr7fi0p7h3qzg92s5xv4094jc1ql-udisks-2.1.4/lib/udisks2/udisksd --no-debug
andy      1834  0.0  0.0 112716  2272 pts/1    S+   23:43   0:00 grep --color=auto udisk
```

I followed the steps here: https://nixos.org/wiki/Xfce#Volume_mounting_does_not_work

Still does not work. Thunar has this on stderr when I plug in my android phone over USB:

```
thunar-volman: Unsupported USB device type "usb".
thunar-volman: Unsupported USB device type "(null)".
```

**Comment by andrewrk** [comment]
I tried this in KDE2 as well as XFCE and was not able to mount the media device.

**Comment by andrewrk** [comment]
Can this issue be re-opened? Should I start a new one?

**Comment by vcunat** [comment]
Let's keep the same thread. Do I understand correctly that neither auto-mount nor click-to-mount works for you?

**Comment by andrewrk** [comment]
Yes that is correct. And know the device is working because I was able to transfer files by manually mounting with jmtpfs.

**Comment by Profpatsch** [comment]
(triage) does it work again?

**Comment by mimadrid** [comment]
I don't know if I am experiencing the same problem.
I'm using nixos unstable with i3 and pcmanfm and trying udisk2 service for auto mounting usb but the daemon doesn't start automatically for me and manually (without the no debug flag) detects the usb and udisk2 adds a uevents for sdb and sdb1 but doesn't show more information neither load it.

> 01:19:45.388:[12002]:[DEBUG]: uevent add /sys/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.3/1-1.3:1.0/host4/target4:0:0/4:0:0:0/block/sdb [udiskslinuxprovider.c:902, udisks_linux_provider_handle_uevent()]
> 01:19:45.436:[12002]:[DEBUG]: uevent add /sys/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.3/1-1.3:1.0/host4/target4:0:0/4:0:0:0/block/sdb/sdb1 [udiskslinuxprovider.c:902, udisks_linux_provider_]

I would be very grateful for any solution.

**Comment by razvan-panda** [comment]
My issue is that NixOS automounted the other disk drives but is unable to open them because of permissions:

https://i.imgur.com/s9gIItd.png

**Comment by andrewrk** [comment]
This happened to me again

**Comment by andrewrk** [comment]
Problem solved by rebooting the computer.......
