### ISSUE TITLE
gocryptfs: mounting as non-root broken

### ISSUE THREAD

**Issue by DeeUnderscore** [NixOS/nixpkgs#139939]
### Describe the bug
gocryptfs fails to mount a volume as non-root/without sudo

### Steps To Reproduce
as a non-root user: 
```shellsession
$ /nix/store/ldkp7i9yhf57hc2dfjznfvwh09pm102m-gocryptfs-2.1/bin/gocryptfs crypt plain  # newer build of package, with fuse as input
Password: 
Decrypting master key
DetectQuirks: Btrfs detected, forcing -noprealloc. See https://github.com/rfjakob/gocryptfs/issues/395 for why.
/nix/store/5fww4k3j02nbfyjgn4sslqlz48z8f752-fuse-2.9.9/bin/fusermount: mount failed: Operation not permitted
fs.Mount failed: fusermount exited with code 256
$ /nix/store/f1wxi2l7rx2c0k5r60583hqy4ws2q193-gocryptfs-2.1/bin/gocryptfs crypt plain  # older build of package, without fuse as input
Password: 
Decrypting master key
DetectQuirks: Btrfs detected, forcing -noprealloc. See https://github.com/rfjakob/gocryptfs/issues/395 for why.
Filesystem mounted and ready.

```

### Expected behavior
gocryptfs should mount volumes without needing sudo, as normal user

### Additional context
#138532 added fuse as input to the package, and added it to `PATH` in a wrapper. I assume that in older builds `fusermount` is grabbed from my `PATH`, which would be `/run/current-system/bin/fusermount`. The wrapper in `/run/current-system/bin/fusermount` has the setuid bit set, while the binary in the package does not; I assume this is the source of the problem. 

Running the wrapped binary directly (`/nix/store/ldk…102m-gocryptfs-2.1/bin/.gocryptfs-wrapped`) mounts the volume without problems.

### Notify maintainers
@flokli @offlinehacker @prusnak @kalbasit

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.67, NixOS, 21.05.20210926.fd8a7fd (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210922_bcd73eb`
 - channels(root): `""`
 - channels(d): `""`
 - nixpkgs: `/nix/store/mz8vpyg587llb4c802w96m956icc39vm-source`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by prusnak** [comment]
cc @sephalon

**Comment by Artturin** [comment]
The solution is to postfix fuse instead of prefix

**Comment by prusnak** [comment]
> The solution is to postfix fuse instead of prefix

What do you mean by postfix fuse?

**Comment by Artturin** [comment]
> > The solution is to postfix fuse instead of prefix
> 
> What do you mean by postfix fuse?

I meant use --suffix instead of --prefix here https://github.com/NixOS/nixpkgs/pull/138532/files#diff-993678093cadc7b431e6e7229421191a397df5d6574b0620358fc1bc1e6e98a7R56

**Comment by prusnak** [comment]
@DeeUnderscore Can you please try the proposed fix above and report back if that fixes the issue?

**Comment by DeeUnderscore** [comment]
Thanks, yes, it solves my issue. I was also able to mount via the `fileSystems` option with the fix applied, so I went ahead and opened a PR at #140057
