### ISSUE TITLE
go packages capture paths under /tmp

### ISSUE THREAD

**Issue by msackman** [NixOS/nixpkgs#13995]
## Basic info
- Kernel: (run `uname -a`)
  
  Linux nixos 4.4.4 #1-NixOS SMP Thu Mar 3 23:10:04 UTC 2016 x86_64 GNU/Linux
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  
  16.09pre78848.9549257 (Flounder)
- Nix version: (run `nix-env --version`)
  
  nix-env (Nix) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  
  "16.09pre78848.9549257"
## The compiled output of Go packages contains paths within /tmp which reflect the state of the build system outside the `buildInputs`

For example:

```
$ nix-build '<nixpkgs>' -A go15Packages.glog
$ strings result/share/go/pkg/linux_amd64/github.com/golang/glog.a|grep nix-build
```

The problem here is really the `.drv-0` in the paths as it is capturing the state of the system during the build, so different people will get different results regardless of the build inputs
### Expected result

There should be no results from the above command, or at least the results should be sanitised to not leak details of the build system
### Actual result

Lots of lines including things like:
`/tmp/nix-build-go1.5-glog-2015-07-31.drv-0/go/src/github.com/golang/glog/glog.go`

**Comment by msackman** [comment]
Thinking further about this, editing the binary at the end is going to be hard - ensuring that `drv-10` and `drv-9` end up with the same paths and thus binary isn't going to be easy. I suspect the only hope here is using some sort of fs namespace / chroot to make the `drv` directory become `/`

**Comment by domenkozar** [comment]
@edolstra should we have a check that prevents $out from referring to the build directory?

**Comment by domenkozar** [comment]
cc @lethalman

**Comment by msackman** [comment]
I can think of a cheap way and an expensive way to solve this.

The cheap way:
Make the numeric suffix to `drv` fixed length - eg 8 digits. Then at least the strings are always going to be the same length so they can probably be safely patched out by just replacing them with spaces or something. I would still worry about the effect of that though.

The expensive way:
Make all builds occur within a chroot (or similar) and just bind-mount in the build-inputs. With this approach, it doesn't matter if paths are captured as they're always going to be the same. Essentially the state of the build machine is masked out. There would then be no need to edit the binary, and no need for the check you suggest above.

**Comment by edolstra** [comment]
@domenkozar That would require setting $TMPDIR to something we scan for, e.g. /tmp/<128-bit random number>. However, forbidding $TMPDIR references would probably break a lot of packages.
