### ISSUE TITLE
youcompleteme does not build on latest unstable

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#14006]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`): `Linux yuu 4.3.6 #1-NixOS SMP Fri Feb 19 22:35:24 UTC 2016 x86_64 GNU/Linux`
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...): `16.09pre78286.0bf8a1a (Emu)`
* Nix version: (run `nix-env --version`): `nix-env (Nix) 1.11.2`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`): `"16.09pre78848.9549257"`

## Describe your issue here

`vimPlugins.youcompleteme` fails with

```
[...]
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/nix-build-vimplugin-youcompleteme-2016-03-08.drv-0/youcompleteme-381b213/build
make: *** No rule to make target 'ycm_support_libs'.  Stop.
builder for ‘/nix/store/vvwmin1545ibh9i89dq4dac8vpag9b61-vimplugin-youcompleteme-2016-03-08.drv’ failed with exit code 2
error: build of ‘/nix/store/vvwmin1545ibh9i89dq4dac8vpag9b61-vimplugin-youcompleteme-2016-03-08.drv’ failed
```

### Expected result

Build succeeds

### Actual result

Build fails

### Steps to reproduce

```
git checkout 954925771482b50493a24615c6e7e82e044a4fdf
nix-build -A vimPlugins.youcompleteme
```

### Maintainers

@marcweber @jagajaga

**Comment by jagajaga** [comment]
I have the same issue.
