### ISSUE TITLE
The sources of `nmigen` packages are a fork of the original nmigen by m-labs

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#140015]
I explored a few days ago projects developed by https://m-labs.hk and I noticed Nixpkgs' has a few package named with `nmigen` all sourced from [nmigen](https://github.com/nmigen/), while there's a project by m-labs under the domain [m-labs](https://github.com/m-labs). I asked a [question in their forums](https://forum.m-labs.hk/d/295-who-is-developing-nmigen) and I got a private reply from an m-labs employee. Part of this chat is quoted here:

```
the nmigen/nmigen fork was started by a former M-Labs employee, in
violation of trademark law and just basic respect. It ought to be renamed.

There are a number of technical and community issues with the fork and
we (M-Labs) are developing a private version of nmigen (nmigen2) to
address those problems and actually have a good Python HDL for our
projects such as ARTIQ. (Currently they are using the ancestor Migen)
```

And later he wrote:

```
> Do you think NixOS should mention in some way inside that expression
> that this is an unauthorized fork?

NixOS should remove that package.

> I noticed you responded to my
> question online privately, is this a sensitive issue?

The nmigen fork community likes to engage in mobbing, bullying and
slander, and while I can easily ban them from the M-Labs forum I'd
rather simply avoid the hassle.
```

I don't know if we should remove the package, but it'd be nice if it was a bit more clear when one does a `nix search` that the `nmigen` package is a fork. What do you think @emilazy ?

**Comment by marsam** [comment]
>the nmigen/nmigen fork was started by a former M-Labs employee, inviolation of trademark law and just basic respect. It ought to be renamed.

That is an outrageous statement 😠 . nmigen is a whitequark's project, M-labs acted in utterly bad faith and trademark it  https://twitter.com/marcan42/status/1358605354750205952
For practical purposes m-labs/nmigen, supposedly "upstream", is an outdated and unmaintained repo. All the development is happening in nmigen/nmigen where whitequark continues developing it.

**Comment by doronbehar** [comment]
> For practical purposes m-labs/nmigen, supposedly "upstream", is an outdated and unmaintained repo.

Sebastian wrote to me:

```
> [ ... ] we (M-Labs) are developing a private version of nmigen (nmigen2) [ ... ]
```

I don't want to argue here who is right. I only wish to reach an agreement with the maintainers here at nixpkgs, regarding how to name the project. I think we should use a `-fork` suffix to the current `nmigen` packaged, or mention at least in the meta that it's developed by whitequark.

**Comment by whitequark** [comment]
The term "fork" implies the existence of two diverging codebases. That's not and has never been the case; I started developing nMigen in the `m-labs/nmigen` repository, and continue to maintain it in the `nmigen/nmigen` repository, as anyone examining the git history can see for themselves. Of course, you're welcome to mention this fact in the meta.

**Comment by doronbehar** [comment]
@whitequark what's confusing for people that encounter your `nmigen/nmigen` repo is that the README looks exactly the same as in `m-labs/nmigen`, your domain looks similar but different. OTH you don't mention that you are a former employee of `m-labs` and that you are not part of them anymore and that you develop your project indipendently. These are all facts, call it a fork or however you want, I just wish to make the situation clear for people that encounter the short description from Nixpkgs, and it'd be nice if it was clearer for people that visit your `nmigen/nmigen` repo.

I support your work and I don't understand what's wrong with the fact you are maintaining your version of `nmigen` under your domain - sounds absolutely OK in terms of free software. I haven't read the LICENSE of `m-labs/nmigen` but common sense tells me that when you distribute your version of a free software you should mention to your users the original source of the software you produce.

**Comment by whitequark** [comment]
The confusion you're referring to was created by M-Labs, and is their responsibility to address, not mine.

**Comment by doronbehar** [comment]
I don't have any motive to take a side on the argument "who was first", but it seems to me that your repo is the one that diverged from `m-labs/nmigen` and not the other way around, according to what was done in: https://github.com/nmigen/nmigen/commit/3a4576e033bbed88541415e6a747c328cdd1f420 and discussed in: https://github.com/nmigen/nmigen/issues/412 .

**Comment by whitequark** [comment]
There's no divergence; that is, there aren't two versions of nMigen that are concurrently developed. There's just one in the `nmigen/nmigen` repository, and an outdated copy of it is lives at `m-labs/nmigen`.

**Comment by ktemkin** [comment]
Hi! I've looked into this quite a bit when I started a significant project based on nMigen, and I'm happy to provide some insight. (Note that while I've read the relevant agreements between whitequark and M-Labs, I am not a lawyer.)

At the point where nMigen was created, whitequark was not a formal employee of M-Labs; but instead was receiving a small amount of sponsorship for its development via them. As nMigen was intended to be a successor to M-Labs' original Migen, whitequark opted to initially create the repo under the M-labs organization, but given wq **was not a paid employee and was under no contractual agreement**, she remains the author of all nmigen code, including for purposes of copyright. 

I don't see how her moving her preferred git repository **for code she is the correct IP holder for** constitutes a fork. The fact that M-Labs later tried to claim the project as their own doesn't change that the whitequark has been its primary author since the very beginning, nor does that claim give them any legal ownership or authority over the project.

It seems to me like there's a simple choice, here: an uninformed user installing `nmigen` can either get the most up-to-date code from its original author and IP holder, or they can get a stale codebase that hasn't been maintained, but which matches the original location of the nmigen project. I'd think the choice is obvious.

**Comment by doronbehar** [comment]
Thanks for joining the discussion @ktemkin! The picture you are describing is much different then the one I had in mind.. I still think that someone should mention that `nmigen/nmigen` is not developed by `m-labs` at all. Ideally that info would have appeared in `nmigen/nmigen`'s README but that's as far as I can ask. Perhaps this would be acceptable: https://github.com/nmigen/nmigen/pull/638

**Comment by sbourdeauducq** [comment]
> At the point where nMigen was created, whitequark was not a formal employee of M-Labs; but instead was receiving a small amount of sponsorship for its development via them.

This is a lie.

**Comment by sbourdeauducq** [comment]
Even the LICENSE file of the Amaranth fork correctly lists M-Labs as a copyright holder, until whitequark's termination in January 2020.
https://github.com/amaranth-lang/amaranth/blob/7d611b8fc1d9e58853ff268ec38ff8f4131a9774/LICENSE.txt#L2
https://github.com/amaranth-lang/amaranth/commits/main/LICENSE.txt

![image](https://user-images.githubusercontent.com/720864/148751424-49c77555-e228-4d75-a20f-8170df7adee4.png)

**Comment by whitequark** [comment]
The sole reason that line is a part of `LICENSE.txt` is the presence of the `nmigen.compat` (now `amaranth.compat`) module, which is directly derived from Migen source code.

**Comment by sbourdeauducq** [comment]
> The sole reason 

Another lie.
I also have official documents issued by a government authority proving this and @ktemkin's statements wrong, but it is certainly better if I do not have to use them nor give public details about them.

**Comment by ktemkin** [comment]
I've read (and had counsel review) the details of the employment contract between M-Labs and @whitequark, issued well before this conflict -- which stipulated her employment at a given rate of pay -- and reviewed @whitequark's bank statements at the time that she was working on nmigen.

Given she did not receive the obligated income from M-Labs during that period, there's strong evidence that @whitequark either ceased to be an employee of M-Labs well before she started nmigen, or that M-Labs was in such a fundamental breach of that employment contract that she could not have legally been considered an employee.

Unless all of the documentation I've seen has been painstakingly forged, I can't see how you have a leg to stand on -- nor how this extended campaign of trademark-trolling is anything other than base harassment.

Either way, this doesn't seem like an appropriate venue for a protracted debate.

**Comment by sbourdeauducq** [comment]
Your counsel was told more lies and/or was unaware of the Hong Kong Employment Ordinance, Cap 57, 32. (2) (a).

**Comment by thoughtpolice** [comment]
`nmigen` no longer exists in the upstream package set in any form as of 34d3df28d58878dcfacb50ad55f24af509320e29 (approximately; see the immediate parents of 810e09c544b500e25951291eaf64fedb8c067300 for full details.) This is now closed.
