### ISSUE TITLE
Rhythmbox Python plugins don't work

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#140078]
### Describe the bug
Rhythmbox ships a bunch of plugins that are written in Python, but they don't seem to work in Rhythmbox as it's currently packaged.

### Steps To Reproduce
1. Install `rhythmbox`
2. Look in the settings, in the plugins tab
3. Observe that a large number of plugins (e.g. for replaygain support) are missing

### Expected behavior
Rhythmbox's Python plugins should be usable.

### Additional context
I got some way towards fixing this with the following overlay:

```nix
  (self: super: {
    rhythmbox = super.rhythmbox.overrideAttrs (old: {
      configureFlags = (old.configureFlags or []) ++ [
        "--enable-python"
      ];
      buildInputs = (old.buildInputs or []) ++ [
        super.python3Packages.pygobject3
        super.gobject-introspection
      ];
    });
  })
```

which at least makes the Python plugins show up in the settings menu, but enabling them fails, printing the following to xsession-errors:

```
Sep 30 21:33:15 the .rhythmbox-wrap[743623]: Error initializing Python Plugin Loader: PyGObject initialization failed
Sep 30 21:33:15 the xsession[743623]: ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))
Sep 30 21:33:15 the .rhythmbox-wrap[743623]: Please check the installation of all the Python related packages required by libpeas and try again
Sep 30 21:33:15 the .rhythmbox-wrap[743623]: Loader 'python3' is not a valid PeasPluginLoader instance
```

I tried setting `strictDeps = false;` as suggested in other issues related to gobject-introspection, and also adding gobject-introspection to nativeBuildInputs, but couldn't get any closer to getting the plugins working.

### Notify maintainers
@rasendubi

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.63, NixOS, 21.05.3065.b3083bc6933 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(ash): `"home-manager-21.05, nixos-unstable-21.11pre318500.51bcdc4cdaa"`
 - channels(root): `"nixos-21.05.3065.b3083bc6933"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by rasendubi** [comment]
Have you tried adding python modules to `propagatedBuildInputs`? Another option to try is adding `python` to dependencies—if I understand correctly, it should have a setup hook to set env variables for python to find its libraries later.

**Comment by sersorrel** [comment]
I tried moving `python3Packages.pygobject3` to propagatedBuildInputs, but it still doesn't seem to work. And buildInputs already includes `python3` in the nixpkgs derivation, right? https://github.com/NixOS/nixpkgs/blob/9a23237031b385945132c8dac7d7ad97ece67408/pkgs/applications/audio/rhythmbox/default.nix#L57-L58

**Comment by Abdillah** [comment]
The error come from [here](https://github.com/GNOME/libpeas/blob/1d50694f770b12e1e7447d2c606a1e46533e34b7/loaders/python/peas-plugin-loader-python.c#L258). I think `libpeas` must be patched to initialize using given PATH and PYTHONPATH or `sys.path`.

**Comment by Abdillah** [comment]
I'm able to take this further by wrapping rhythmbox with `PYTHONPATH` prefix.

```nix
{
  preFixup = ''
    gappsWrapperArgs+=(
      --prefix PYTHONPATH : "${super.python39Packages.pygobject3}/lib/python3.9/site-packages/"
      --prefix PYTHONPATH : "$out/lib/rhythmbox/plugins/"
    )
  '';
}
```
