### ISSUE TITLE
Discourse reverts notification email every time

### ISSUE THREAD

**Issue by LEXUGE** [NixOS/nixpkgs#140114]
### Describe the bug
Every time I rebuild my server, the notification email got reset back to `noreply@mydomain.org`.
I searched around and found the root cause of the issue being https://github.com/discourse/discourse/blob/main/db/fixtures/990_settings.rb
Discourse uses `site_settings.yml` as default for options, whereas the discourse module in nixpkgs use it as the final configuration.
And that database fixture then revert the setting back on every deployment.
I can confirm removing that fixture fixes this issue.

### Steps To Reproduce
1. set `notificationEmailAddress` and deploy

### Expected behavior
notification email address doesn't change.

### Notify maintainers
@talyz

**Comment by talyz** [comment]
Thanks for reporting this! Can you try out #140133 and see if it fixes the problem?

**Comment by LEXUGE** [comment]
Sure, I will try when available. I looked at the change, it should work great. But if upstream defaults change, it will break though.

**Comment by talyz** [comment]
Yeah, while the risk of that happening seems pretty low, maybe it would be best to just remove the file altogether - it doesn't seem to fill any function for us anyway. I'll do that instead.

**Comment by LEXUGE** [comment]
Yes. We have already got our own default for notification email, so removal should just be fine.
