### ISSUE TITLE
urxvt derivation sets TERMINFO incorrectly

### ISSUE THREAD

**Issue by tejing1** [NixOS/nixpkgs#140171]
### Describe the bug
```
$ env | grep TERMINFO=
TERMINFO=$terminfo/share/terminfo
```
... what's `$terminfo` doing there?

I suppose it doesn't actually cause any problems given that TERMINFO_DIRS is set, but still, it shouldn't be there.
### Steps To Reproduce
1. Install urxvt through nixpkgs (`pkgs.rxvt-unicode`)
2. Start a terminal (`urxvt`)
3. Check your environment variables as above

### Cause
The offending line is clearly
https://github.com/NixOS/nixpkgs/blob/88ca7b5b349dc7d285fbc25e0d7099602ab29192/pkgs/applications/terminal-emulators/rxvt-unicode/default.nix#L52

I suspect this may have worked at one point in the past, then stdenv's escaping logic was changed?

### Expected behavior
The variable should be set to a directory that actually exists and has the appropriate information in it, or not set at all.

### Notify maintainers
@rnhmjoj

### Metadata
I doubt it's relevant, but:
```
$ nix-shell -p nix-info --run "nix-info -m"
these 4 paths will be fetched (0.39 MiB download, 1.89 MiB unpacked):
  /nix/store/7gdji02y6rbnzv5mcxcf3mwksk785y8j-stdenv-linux
  /nix/store/7wy23fyz7lszd7izsla09d5bzmc57x22-gnumake-4.3
  /nix/store/86zys752g7fg2mwad7yhll285y9w3lym-patchelf-0.12
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/7wy23fyz7lszd7izsla09d5bzmc57x22-gnumake-4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/86zys752g7fg2mwad7yhll285y9w3lym-patchelf-0.12' from 'https://cache.nixos.org'...
copying path '/nix/store/7gdji02y6rbnzv5mcxcf3mwksk785y8j-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.52, NixOS, 21.05.20210729.2262d78 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210707_02dd6bb`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by Artturin** [comment]
#140172

**Comment by Artturin** [comment]
btw arch has a lot of configure options, i wonder if we should add some of them? https://github.com/archlinux/svntogit-community/blob/130e74f9e6cf104fb56d58173266506068dccb90/trunk/PKGBUILD#L32

**Comment by rnhmjoj** [comment]
> btw arch has a lot of configure options, i wonder if we should add some of them? 

I'll take a look, but I suspect most of these are enabled by default.

**Comment by rnhmjoj** [comment]
The only options off by default that we don't enable in Nixpkgs are
```
--enable-assert (default: off)
--enable-smart-resize (default: off)
```
The first is for only useful when developing urxvt, the description for
the second says:

> Add smart growth/shrink behaviour when resizing. This should keep
> the window corner which is closest to a corner of the screen in a
> fixed position.

I'm not sure how useful this is because I use a tiling WM.
Anyway, the option is off even in Arch Linux due to a [bug](https://bugs.archlinux.org/task/34807).
