### ISSUE TITLE
libgtop is not reproducible

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#140175]
### Describe the bug

libgtop is not reproducible, since it embed the output of `uname -r / -s / -v / -m` into one of its binaries.

### Steps To Reproduce

See [r13y](https://r13y.com/iso_gnome/diff/a065a4a046ce2fd0b3d39fecfeee252e255cc6c62aee33a5e78fe2fe453c3325-b88c54c2ca5f90e44b548e9a1fcd0934bb14d599e4b194c275731d6250daa8a4.html) or build on 2 machines with different kernel versions.

Report attached since r13y will not keep it, I think:
[diffoscope-report-r13y.html.txt](https://github.com/NixOS/nixpkgs/files/7269057/diffoscope-report-r13y.html.txt)

### Expected behavior

libgtop build should be reproducible.

### Additional context

This patch works from a nixpkgs perspective:

```patch
diff --git a/pkgs/development/libraries/libgtop/default.nix b/pkgs/development/libraries/libgtop/default.nix
index 98b0dc89fee..5e0f53d3fa3 100644
--- a/pkgs/development/libraries/libgtop/default.nix
+++ b/pkgs/development/libraries/libgtop/default.nix
@@ -7,6 +7,7 @@
 , gobject-introspection
 , gnome
 , gtk-doc
+, autoreconfHook
 }:
 
 stdenv.mkDerivation rec {
@@ -24,12 +25,23 @@ stdenv.mkDerivation rec {
     perl
     gettext
     gobject-introspection
+
+    # required due to patching the Makefile.am file
+    autoreconfHook
   ];
 
   propagatedBuildInputs = [
     glib

   ];
 
+  postPatch = ''
+    substituteInPlace src/daemon/Makefile.am \
+      --replace "\`uname -s\`" "DUMMY_KERNEL_NAME" \
+      --replace "\`uname -r\`" "DUMMY_KERNEL_RELEASE" \
+      --replace "\`uname -v\`" "DUMMY_KERNEL_VERSION" \
+      --replace "\`uname -m\`" "DUMMY_KERNEL_MACHINE"
+  '';
+
```

However, it should ideally be reported and fixed upstream.

### Notify maintainers

@NixOS/gnome 

### Metadata

N/A

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libgtop
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/210102
