### ISSUE TITLE
haskell-language-server doesn't build on aarch64-darwin

### ISSUE THREAD

**Issue by hexagonal-sun** [NixOS/nixpkgs#140180]
### Describe the bug
the `haskellPackages.haskell-language-server` package doesn't seem to build for `aarch64-darwin`.

Here's the job log on Hydra: https://hydra.nixos.org/build/155006253/nixlog/1.  It looks as though the issue is to do with the ormolu package?

### Steps To Reproduce
`nix-env -iA nixpkgs.haskellPackages.haskell-language-server`.

### Expected behavior
HLS builds.

### Notify maintainers
@maralorn 

### Metadata
 - system: `"aarch64-darwin"`
 - host os: `Darwin 20.6.0, macOS 11.5.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.14`
 - channels(matthew): `"home-manager, nixpkgs-21.11pre304425.2030abed586"`
 - channels(root): `"home-manager, nixpkgs-21.11pre317548.e0ce3c683ae"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by kurnevsky** [comment]
It also doesn't build for nixos 21.05: https://hydra.nixos.org/build/154147571

**Comment by maralorn** [comment]
> It also doesn't build for nixos 21.05: https://hydra.nixos.org/build/154147571

That’s an unrelated issue. That probably was a hardware/environment problem. I have restarted that build job in the hopes that it succeeds on the next run.

**Comment by maralorn** [comment]
Hey @hexagonal-sun, thx for the report. That build error looks quite weird and baffles me. I have also restarted that one, maybe it was a weird glitch …

Sadly I don‘t have a system for testing or the time to support aarch64-darwin.

Of course we will gladly accept any PRs fixing this and I can try to give input/feedback into attempts to debug this.

**Comment by kurnevsky** [comment]
I had exactly the same error when hasskell-ide-ingine was building locally after nixpkgs update, so it seems indeed broken.

**Comment by maralorn** [comment]
> > That’s an unrelated issue. That probably was a hardware/environment problem.
> 
> I had exactly the same error when hasskell-ide-ingine was building locally after nixpkgs update, so it seems indeed broken.

Oh, okay. I can reproduce. Thank’s for the report. Will fix this asap.

**Comment by maralorn** [comment]
> > > That’s an unrelated issue. That probably was a hardware/environment problem.
> > 
> > 
> > I had exactly the same error when hasskell-ide-ingine was building locally after nixpkgs update, so it seems indeed broken.
> 
> Oh, okay. I can reproduce. Thank’s for the report. Will fix this asap.

Will be fixed by #140518.

Now back to the original topic. Sorry for the noise.

**Comment by sternenseemann** [comment]
Closing in favor of #140774.
