### ISSUE TITLE
How to use linux-libre kernel package?

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#140354]
Hey,
I'm trying to use the linux-libre kernel in NixOS. What is the correct way to achieve this?

Setting `kernelPackages = pkgs.linuxPackages_libre;` results in:
```
error: attribute 'linuxPackages_libre' missing, at /etc/nixos/configuration.nix:65:22
```

Setting `kernelPackages = pkgs.linux-libre` in:
```
error: attribute 'extend' missing, at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/boot/kernel.nix:40:31
```

`kernelPackages = pkgs.linuxKernel.packages.linux_libre;`:
```
error: attribute 'linuxKernel' missing, at /etc/nixos/configuration.nix:65:22
```

Still no luck :,(

**Comment by Kranzes** [comment]
pkgs.linuxPackages-libre / pkgs.linuxPackages_latest-libre

**Comment by onny** [comment]
Thanks that worked. Unfortunately linux-libre is marked broken but I'll have a look :)
