### ISSUE TITLE
Haskell package 'llvm-general' does not compile on OS X

### ISSUE THREAD

**Issue by ChShersh** [NixOS/nixpkgs#14035]
## Basic info

To make sure that we are on the same page:

* Kernel: Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
* System: OS X 10.11.3 (Mac)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03pre76763.be0abb3"

## Describe your issue here
I have problems with entering nix-shell on Mac (OS X) and using llvm-general packages. I run the following command:

```
nix-shell -p "haskellPackages.ghcWithPackages (pkgs: with pkgs; [mtl array llvm-general-pure llvm-general])"
```

### Expected result
Entering to the nix-shell.

### Actual result
Got this error at the end of message:

No lhc found
No lhc-pkg found
Using llvm-config version 3.5.2 found on system at:
/nix/store/y8ig91q6yz5y2s6c12f4z1l3c61gagx9-llvm-3.5.2/bin/llvm-config
No pkg-config found
Using strip found on system at:
/nix/store/scw8qcqjzqa0gn7vwng5k5fcms4bsmda-cctools-binutils-darwin/bin/strip
Using tar found on system at:
/nix/store/aq56mr4w1a2kmvd0ijv9bf4iz2m0r0sw-gnutar-1.28/bin/tar
No uhc found
Setup: Missing dependency on a foreign library:
* Missing C library: stdc++
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
builder for ‘/nix/store/qyy5m5mbnwvk8vn6lfs1z95q2pfhkac5-llvm-general-3.5.1.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/njbgsa269mv9dsjb5p5c962g6s61cdws-ghc-7.10.3.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/njbgsa269mv9dsjb5p5c962g6s61cdws-ghc-7.10.3.drv’ failed
/Users/myUserName/.nix-profile/bin/nix-shell: failed to build all dependencies

### Steps to reproduce
Run command above on such OS X

cc @peti @jagajaga

**Comment by dalaing** [comment]
I haven't had time to add the OS-specific switching and make a PR, but this is working for me at the moment:

In pkgs/development/haskell-modules/configuration-common.nix

```
-  llvm-general = super.llvm-general.override { llvm-config = pkgs.llvm_35; };
+  llvm-general = overrideCabal (super.llvm-general.override { llvm-config = pkgs.llvm_35; }) (drv: {
+    preConfigure = ''
+      sed -i llvm-general.cabal \
+          -e 's,extra-libraries: stdc++,extra-libraries: c++,'
+    '';
+    configureFlags = (drv.configureFlags or []) ++ ["--extra-include-dirs=${pkgs.libcxx}/include/c++/v1"];
+    librarySystemDepends = [ pkgs.libcxx ] ++ drv.librarySystemDepends or [];
+  });
```

**Comment by peti** [comment]
Does this issue still exist?
