### ISSUE TITLE
ruby gems packaging: the howto seems not to work

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#14048]
I wanted to package a gem, so I followed the nixpkgs manual on that, but the resulting executable fails with:
```
/nix/store/p1smzl194057x5ixk5aymkal6cwmjq3j-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /nix/store/p1smzl194057x5ixk5aymkal6cwmjq3j-ruby-2.3.0-p0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./result/bin/fpm:16:in `<main>'
```
I did this on recent master; details are in the commits: https://github.com/NixOS/nixpkgs/compare/master...vcunat:p/fpm.

I know very little about ruby stuff; perhaps someone else knows what's wrong: @cstrahan, @zimbatm.

**Comment by zimbatm** [comment]
I was able to reproduce the issue and am working on a fix. I had bundler installed in my user GEM_HOME so didn't notice the problem until now. There are deeper issues that needs fixing so I'm not sure how fast I can produce a proper fix yet. Keep you posted.

**Comment by zimbatm** [comment]
In the mean time I recommend that you look at the `cide` package as an example. Right now bundlerEnv bleeds some common bin files into the environment which creates some conflicts. I'm working on making a rubyPackage that will automates all of this.

**Comment by zimbatm** [comment]
@vcunat try rebasing on top of this ^

**Comment by vcunat** [comment]
Yes, that commit certainly improves the situation, as `fpm --help` works. (I haven't tested more so far.)

**Comment by cstrahan** [comment]
I think @aespinosa's #13975 is the way to go. I think a similar change to the bundler packaging should fix this.

**Comment by vcunat** [comment]
Thanks, the package now does what I need it to, so I pushed it as f9cae4f.

Would you skim the example changes e5c319baa88d4 before I push them?
