### ISSUE TITLE
vscode-extensions.ms-python.python no longer works due to lttng update

### ISSUE THREAD

**Issue by kinnison** [NixOS/nixpkgs#140469]
### Describe the bug

When trying to use the `ms-python.python` extension for vscode from nixos-unstable I get a failure to build the extension because it contains binaries linked to `liblttng-ust.so.0` whereas the lttng version in nixos-unstable produces `liblttng-ust.so.1`.  Since this is a major SONAME update, I doubt that it can be directly substituted.

### Steps To Reproduce

1. Install vscode using `vscode.with-extensions.override { vscodeExtensions = [ vscode-extensions.ms-python.python ]; }`
2. notice how it fails to build the expressions because it can't find `liblttng-ust.so.0`
3. examine the lttng package in `/nix/store` and notice it has `liblttng-ust.so.1`

### Expected behavior

It should be possible to enable the extension for vscode.

### Additional context

Since the extension works in 21.05 it's likely part of this commit: https://github.com/NixOS/nixpkgs/commit/ab2501bd171f2c930ebd3f3bf6b6a1a228477a08

### Notify maintainers

@alyssais @bjornfor @jraygauthier

**Comment by jraygauthier** [comment]
Duplicates #137314.

**Comment by kinnison** [comment]
Apologies, I have no idea how I failed to spot that when I checked.  Closing in favour of #137314

**Comment by jraygauthier** [comment]
No trouble and nice work identify the cause of the failure on nixpkgs `master`.
