### ISSUE TITLE
`programs.ccache.enable` + `.packageNames` has no effect

### ISSUE THREAD

**Issue by eliasp** [NixOS/nixpkgs#140410]
### Describe the bug
Enabling ccache seems to have no effect. Repeated builds aren't sped up, the cache seems to remain empty.

### Steps To Reproduce
1. Enable `ccache`:
  ```nix
  programs.ccache.enable = true;
  programs.ccache.packageNames = [ "kalendar" "qt5" "qt5.qtbase" "kdeFrameworks" ];
  ```
2. `nixos-rebuild switch`
3. Build one of the listed packages
4. Check the cache:
  ```console
$ du -sh /var/cache/ccache
4.0K    /var/cache/ccache
$ nix-ccache --show-stats                 
Summary:
  Hits:               0 /    0
    Direct:           0 /    0
    Preprocessed:     0 /    0
  Misses:             0
    Direct:           0
    Preprocessed:     0
Primary storage:
  Hits:               0 /    0
  Misses:             0
  Cache size (GB): 0.00 / 5.00 (0.00 %)

Use the -v/--verbose option for more details.
  ```

### Expected behavior
- `ccache` is being used when building packages
- objects accumulate in the cache

### Notify maintainers
There is no recent maintenance of the `programs/ccache.nix` module besides generic changes/fixes.

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.66, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre319562.c21ba4f7bb4, unstable-small-21.11pre319918.96606addced"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: programs.ccache
```

**Comment by Princemachiavelli** [comment]
Add the default ccache cachedir, `/var/cache/ccache`, to you the `nix.settings.extra-sandbox-paths` option. You can also set it at the flake level via the `nixConfig.extra-sandbox-paths` option in flake.nix. I'm not sure why enabling the program doesn't add the path to the sandbox paths.

Also, from related issues it looks like some mkDerivation wrapper are not correctly overridden to enable ccache. Once you confirm that ccache is working, I think it would be best to create separate issues for each package/mkDerivation wrapper that isn't respecting the setting.

**Comment by Atemu** [comment]
The above should fix the issue. Closing because stale.
