### ISSUE TITLE
Julia compiler is missing zlib in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by dvc94ch** [NixOS/nixpkgs#14049]
`using GZip` in julia causes a libz not found error. Gzip uses dlopen("libz") to load zlib. Gzip is used by popular libraries like Gadfly.

Imo zlib should be added to LD_LIBRARY_PATH.

P.S. I think I am misunderstanding a key concept. Am I supposed to have to recompile julia anytime I try to use a julia package that has a C dependency?

P.S.S Never mind - sry for the spam

**Comment by sorpaas** [comment]
@dvc94ch Did you manage to solve this problem?

**Comment by dvc94ch** [comment]
I think the way it's supposed to be done is by creating a dev environment,
but that's annoying if you just want to plot some functions or do some math
from the command line.

@dvc94ch <https://github.com/dvc94ch> Did you manage to solve this problem?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/NixOS/nixpkgs/issues/14049#issuecomment-214746717>
