### ISSUE TITLE
result symlink stops buildPythonPackage

### ISSUE THREAD

**Issue by rvl** [NixOS/nixpkgs#14043]
Running on the nixos-16.03 channel, I get this problem with `buildPythonPackage` which I didn't have on nixos-15.09.

I have a Python project outside of nixpkgs with a `default.nix` which looks something like this:

```nix
# put this default.nix into a clone of https://github.com/pypa/sampleproject
{ sampleproject ? { outPath = ./.; name = "sampleproject"; }
, pkgs ? import <nixpkgs> {}
}:

let
  pkg = with pkgs.python35Packages;
    buildPythonPackage rec {
      name = "sampleproject-${version}";
      version = "1.2.0";
      src = [ sampleproject ];
      propagatedBuildInputs = [ peppercorn ];

      # workaround
      #buildInputs = [ (reallyEnsureNewerSourcesHook { year = "1980"; }) ];
    };

  reallyEnsureNewerSourcesHook = with pkgs; { year }: makeSetupHook {}
    (writeScript "ensure-newer-sources-hook.sh" ''
      postUnpackHooks+=(_reallyEnsureNewerSources)
      _reallyEnsureNewerSources() {
        echo "hack hack"
        '${findutils}/bin/find' -L "$sourceRoot" \
          '!' -newermt '${year}-01-01' -xtype l -print -exec rm '{}' '+'

        '${findutils}/bin/find' "$sourceRoot" \
          '!' -newermt '${year}-01-01' -exec touch -d '${year}-01-02' '{}' '+'
      }
    '');

in
  pkg
```

The problem is, second time I build, it will fail with this message:

```
these derivations will be built:
  /nix/store/h2056zzy5yf27qhvvd0xnd508maalh7h-python3.5-sampleproject-1.2.0.drv
building path(s) ‘/nix/store/di8plg0vw2kfzimww8vqsxyzkm96m69f-python3.5-sampleproject-1.2.0’
unpacking sources
unpacking source archive /nix/store/qyw10kw3va5j7xlpf1swf6lgh2i781bx-sampleproject
source root is sampleproject
touch: setting times of 'sampleproject/result': Operation not permitted
builder for ‘/nix/store/h2056zzy5yf27qhvvd0xnd508maalh7h-python3.5-sampleproject-1.2.0.drv’ failed with exit code 1
error: build of ‘/nix/store/h2056zzy5yf27qhvvd0xnd508maalh7h-python3.5-sampleproject-1.2.0.drv’ failed
```

If I uncomment the workaround above, problem goes away.

Considering that symlinks can't be included in the Python Wheel zip file, one solution could be to delete the symlinks in the `ensureNewerSourcesHook`. Another solution could be to silently ignore errors coming from the touch command.

Cheers

**Comment by domenkozar** [comment]
Hmm, do you understand what's causing line `touch: setting times of 'sampleproject/result': Operation not permitted`

**Comment by rvl** [comment]
Hi!

It's because the target of the `result` symlink is in the nix store (`/nix/store/1qr1slnjq3i4cd2lmmrh1n4ygqc7m2m1-python3.5-sampleproject-1.2.0`) and owned by root user. My nix build is running as `nixbld1`, so can't touch it.

I also have other symlinks to read-only locations which would also cause problems, even if `result` were removed.

**Comment by rvl** [comment]
Oh, and the touch comes from `ensureNewerSourcesHook`.

**Comment by rvl** [comment]
Looking at the git history, I think I should cc @vcunat.

**Comment by vcunat** [comment]
Well, I expect we should make the hook refuse touching symlinks, e.g. like this:
```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 9729e29..c2df1e9 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -264,6 +264,7 @@ let
       postUnpackHooks+=(_ensureNewerSources)
       _ensureNewerSources() {
         '${findutils}/bin/find' "$sourceRoot" \
+          '!' -type l -a \
           '!' -newermt '${year}-01-01' -exec touch -d '${year}-01-02' '{}' '+'
       }
     '');
```
Would you test it?

**Comment by rvl** [comment]
@vcunat yes, I just tested that patch and it works. Thanks.

**Comment by vcunat** [comment]
Hmm, although if some python sources contained a symlink, we might get into problems. @domenkozar: any estimate if that's likely to happen?

If it possible, this should be a surer way:
```diff
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index 9729e29..d5381db 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -264,7 +264,7 @@ let
       postUnpackHooks+=(_ensureNewerSources)
       _ensureNewerSources() {
         '${findutils}/bin/find' "$sourceRoot" \
-          '!' -newermt '${year}-01-01' -exec touch -d '${year}-01-02' '{}' '+'
+          '!' -newermt '${year}-01-01' -exec touch -h -d '${year}-01-02' '{}' '+'
       }
     '');
```

**Comment by domenkozar** [comment]
Sometimes people do a symlink `README.rst` -> `doc/index.rst` or similar so it might happen.

**Comment by rvl** [comment]
Hi @vcunat I think `touch -h` is a good solution. I have tested it and it has the following two properties:

1. symlinks into `/nix/store` are ignored and don't appear in the wheel.
2. symlinks within a project (e.g. symlinked python files) are kept. Both the link target and the symlink appear in the wheel. The symlink becomes a copy of its target.

**Comment by vcunat** [comment]
The effect should be that the symlink *itself* is touched instead of its target (no removals such as in your work-around). A quick search suggested that Linux and Darwin does support that.

**Comment by rvl** [comment]
OK thanks @vcunat, so the `touch -h` option fixes this issue (symlinks to `/nix/store`), and doesn't break existing usage of symlinks (within python package tree). I think if you committed that change it would close this issue.

**Comment by rvl** [comment]
Thanks @vcunat @domenkozar
