### ISSUE TITLE
mutt doesn't find the user mailbox at /var/mail/$USER on NixOS

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#14050]
## Basic info

To make sure that we are on the same page:
- Kernel: `Linux tux 3.18.26 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux`
- System: `15.09.1151.d8a1eaa (Dingo)`
- Nix version: `nix-env (Nix) 1.10`
- Nixpkgs version: `"15.09.1151.d8a1eaa"`
## Describe your issue here

MUA (eg `mutt`) doesn't find the correct spool mailbox
### Expected result

MUA opens on `/var/spool/$USER`
### Actual result

MUA opens on `$HOME/mailbox` which doesn't exist and isn't used by the MTA
### Steps to reproduce

`mutt`

I'm using `postfix` for the MTA, but `/var/mail/$USER` is considered the standard, and is reflected in the fact that `postfix` symlinks its actual spool directory (`/var/spool/mail`) into that location. This was done in #8206, and there's mention there of `bash` setting `MAIL` but that doesn't seem to be happening any more, and in any case it's fragile to rely on that.

**Comment by peti** [comment]
Cc: @the-kenny

**Comment by Profpatsch** [comment]
triage: still a problem?
