### ISSUE TITLE
GraalVM native images unnecessarily reference the GraalVM store path

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#140544]
### Describe the bug

When building a native image using `graalvm11-ce`, the produced (dynamically linked) executable will be linked against libraries in `"${graalvm11-ce.out}/lib"`, causing a runtime dependency on the entire store path. However this directory only contains symlinks to other packages.

By teaching GraalVM how to link against those libraries *directly* we would instantly save ~1GB of closure size for every dynamically linked binary produced by GraalVM since the runtime dependency would be eliminated. 

The question is of course *how* doable this is. Looking at the derivation, it seems that the symlinks were introduced in the first place to counter how inflexible GraalVM is in this regard.

### Notify maintainers

@hlolli @glittershark @babariviere @ericdallo

**Comment by ericdallo** [comment]
C/c @thiagokokada

**Comment by thiagokokada** [comment]
@sternenseemann Did you take a look at PR https://github.com/NixOS/nixpkgs/pull/140287?

That PR introduces the `lib` output that includes the dynamic libraries used at runtime. So if you link using `${graalvm11-ce.lib}/lib` instead of `${graalvm11-ce.out}/lib`, this will reduce the closure size a lot.

You can see at the commits how much the closure sizes for GraalVM are currently. They're much smaller (`babashka` was 2GB before, now it is ~120MB).

**Comment by sternenseemann** [comment]
Oh, that's a similar approach I had in mind! Tested this a week ago or so and just now remembered to open an issue about this.

One thing that's suboptimal is that it needs manual intervention for downstream users to benefit from this. Can't we inject the library path option in a wrapper for `native-image` or something?

**Comment by thiagokokada** [comment]
> One thing that's suboptimal is that it needs manual intervention for downstream users to benefit from this. Can't we inject the library path option in a wrapper for `native-image` or something?

Maybe we could do a `wrapProgram` on native-image and add that option. Not sure if this is a good idea though.

**Comment by sternenseemann** [comment]
No more like patching the inner workings of `native-image` when/how it passes the library path.

**Comment by thiagokokada** [comment]
I tried to do a `grep -aie "CLibraryPath" -r .` inside GraalVM derivation, didn't returned anything too conclusive. There is this file (`./languages/nfi/native-image.properties`) that sets `-H:CLibraryPath`, however  that seems to only affect compilation with `NativeFunctionInterface`.

There is also some other `native-image.properties` files that could be patched to include the `-H:CLibraryPath`, but this would be a shoot in the dark. I think the easiest way would be to wrap the binary like I said before, but I am still not sure if this is a good idea.

**Comment by thiagokokada** [comment]
> One thing that's suboptimal is that it needs manual intervention for downstream users to benefit from this. Can't we inject the library path option in a wrapper for `native-image` or something?

I think I have a better idea. We can have a `mkNativeImage` that can add this flag to the native-image derivations. This way nobody needs to fiddle with those command-line arguments.
