### ISSUE TITLE
lib389 (from 389-ds-base)

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#140637]
`lib389` is both a `python` library and set of applications to help administer/manage a `389-ds-base` server. The `python` applications provided by `lib389` use their own library from the same package.

Our `389-ds-base` derivation does not build/include `lib389` (even though the `nix` code suggests it does).

Some distros (`debian` at least) ship `lib389` separately from `389-ds-base`. We should either create a new `lib389` derivation, or include it in `_389-ds-base`.

I'm not great at `python` packaging for `nixpkgs` so don't know how to create a derivation that is a library and an application which depends on its own library. Anyone want to tackle this or help me?

Maybe @AndersonTorres or @lovesegfault? :man_shrugging: Any and all help appreciated.

**Comment by AndersonTorres** [comment]
> I'm not great at `python` packaging for `nixpkgs` so don't know how to create a derivation that is a library and an application which depends on its own library. Anyone want to tackle this or help me?

This is done via `toPythonApplication`. Read the manual: 

https://nixos.org/manual/nixpkgs/stable/#python

https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md
