### ISSUE TITLE
Gnome files "trash:///" Operation not supported

### ISSUE THREAD

**Issue by halturin** [NixOS/nixpkgs#140860]
### Describe the bug
Can't open my trash folder in Gnome Files. It very looks like https://github.com/NixOS/nixpkgs/issues/2746

### Screenshots
![image](https://user-images.githubusercontent.com/118860/136406952-00629ff8-9af8-46f8-85f9-0e911776f562.png)

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`                                     
 - host os: `Linux 5.14.9, NixOS, 21.11 (Porcupine)`            
 - multi-user?: `yes`                                           
 - sandbox: `yes`                                               
 - version: `nix-env (Nix) 2.3.15`                              
 - channels(root): `"nixos-21.11pre320706.01f2f2842aa"`         
 - channels(taras): `"home-manager"`                            
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
 ````

**Comment by Lyndeno** [comment]
Any solution to this issue? I am using Sway and Nautilus shows this behavior when run from wofi, but not from a terminal.

**Comment by tommy4st** [comment]
It's not limited to trash, but to all GVFS protocols like smb, sftp, dav or even ftp.

![image](https://user-images.githubusercontent.com/2656837/144838948-3ef21da7-228d-49fd-a4d2-a9138018fccb.png)

I already tried the following:
- update everything
- switch from unstable to 21.11
- switch from fish to bash as default shell
- override gvfs with gnomeSupport = true;

Could it be related to #89542 ?

**Comment by jtojnar** [comment]
Might be. Most likely some component is interfering with setting the `GIO_EXTRA_MODULES` environment variable. Try checking the environments of various running processes to see how it propagates.

**Comment by halturin** [comment]
here is my env

$ env | grep GIO_EXTRA_MODULES                                                                                                                                                                                                                        
GIO_EXTRA_MODULES=/nix/store/68c58b09wb0rg6zqj79apcanfgcamvh3-glib-networking-2.70.0/lib/gio/modules:/nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/lib/gio/modules:/nix/store/myyrjzc3fna3jqv0pgqygcw88ylppc9r-dconf-0.40.0-lib/lib/gio/modules

**Comment by jtojnar** [comment]
Well, having it in terminal does not guarantee it is passed to nautilus (depending on how it is launched). See `strings /proc/(pidof nautilus)/environ | grep GIO_EXTRA_MODULES`. You can also try to `pkill nautilus` and then run Nautilus from the terminal, that should pass the environment variables.

**Comment by tommy4st** [comment]
And here is my env

$ env | grep GIO_EXTRA_MODULES
GIO_EXTRA_MODULES=/nix/store/68c58b09wb0rg6zqj79apcanfgcamvh3-glib-networking-2.70.0/lib/gio/modules:/nix/store/p9dh7v3d05kz4id8k0q8a67npvd7nnm8-gvfs-1.48.1/lib/gio/modules:/nix/store/myyrjzc3fna3jqv0pgqygcw88ylppc9r-dconf-0.40.0-lib/lib/gio/modules

Funny thing, while I gathered this info: I ran `nautilus` right in this shell and ... everything worked! After I closed this nautilus instance and opened it using the overview, it didn't work anymore. Does this help in any way?

**Comment by tommy4st** [comment]
```
$ strings /proc/$(pidof nautilus)/environ | grep GIO_EXTRA_MODULES

GIO_EXTRA_MODULES=/nix/store/68c58b09wb0rg6zqj79apcanfgcamvh3-glib-networking-2.70.0/lib/gio/modules:/nix/store/myyrjzc3fna3jqv0pgqygcw88ylppc9r-dconf-0.40.0-lib/lib/gio/modules:/nix/store/68c58b09wb0rg6zqj79apcanfgcamvh3-glib-networking-2.70.0/lib/gio/modules:/nix/store/myyrjzc3fna3jqv0pgqygcw88ylppc9r-dconf-0.40.0-lib/lib/gio/modules
```

**Comment by jtojnar** [comment]
Yeah, missing gvfs as suspected.

**Comment by jtojnar** [comment]
You could try to check the process tree (run `htop` and press <kbd>t</kbd>) to see how nautilus is launched.

**Comment by halturin** [comment]
am I missing something in my config?

```
❯❯❯❯ grep gvfs /etc/nixos/configuration.nix                                                                                                           
95:   services.gvfs.enable = true;
❯❯❯❯ ps ax | grep gvfs                                                                                                                                
   3258 ?        Ssl    0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfsd
   3271 ?        Sl     0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfsd-fuse /run/user/1000/gvfs -f
 108296 ?        Sl     0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfsd-trash --spawner :1.27 /org/gtk/gvfs/exec_spaw/0
 109036 ?        Ssl    0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfs-udisks2-volume-monitor
 109041 ?        Ssl    0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfs-gphoto2-volume-monitor
 109045 ?        Ssl    0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfs-afc-volume-monitor
 109050 ?        Ssl    0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfs-mtp-volume-monitor
 109054 ?        Ssl    0:00 /nix/store/sxgccp7dyg2rbiygjlby07rq7pvdr8i6-gvfs-1.48.1/libexec/gvfs-goa-volume-monitor
 109752 pts/5    S+     0:00 rg gvfs
❯❯❯❯     
```                                                                                                                                             
and I can confirm, that if I start nautilus right from the shell it works as expected.

**Comment by halturin** [comment]
>You could try to check the process tree (run htop and press t) to see how nautilus is launched.

it starts as a child process of systemd

**Comment by tommy4st** [comment]
I used `ps` and remove everything unrelated. The working `gnome-terminal` process is actually right next to `nautilus`.
```
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:01 systemd
   1919 ?        Ss     0:00 /nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/lib/systemd/systemd --user
  18365 ?        Sl     0:03  \_ /nix/store/y3fkiswnvbf8902kci42smzisdkz73jj-nautilus-41.1/bin/nautilus --gapplication-service
  18494 ?        Ssl    0:11  \_ /nix/store/rncrxjz8g2mxc26n5gkn86wgmwlbcxc9-gnome-terminal-3.42.1/libexec/gnome-terminal-server
  18513 pts/0    Ss     0:00      \_ bash
  18607 pts/0    S      0:00          \_ bash --rcfile /tmp/nix-shell-18607-0/rc
  20327 pts/0    R+     0:00              \_ ps axf
```

**Comment by tommy4st** [comment]
Could this be related: #126832 ?

**Comment by jtojnar** [comment]
Terminal has it because bash runs shell initialization code (e.g. `/etc/profile`). Your session will have or lack the environment variable depending on how it is initialised. For example, it will be present if your login shell sources `/etc/profile`. But display-manager (GDM) can filter it out.

#126832 will likely fix it as `environment.sessionVariables` should be set by PAM so those will probably be exposed in the session environment. But again, one never knows with environment variables.

**Comment by tommy4st** [comment]
Right now, it's still not working 😞 
Is there some workaround possible to fix it temporarily?

**Comment by ncfavier** [comment]
#126832 was reverted because of #149539, there's a second attempt at #151105.

The workaround I'm using is

```nix
{
  environment.sessionVariables.GIO_EXTRA_MODULES = "${config.services.gvfs.package}/lib/gio/modules";
  environment.variables.GIO_EXTRA_MODULES = mkForce config.environment.sessionVariables.GIO_EXTRA_MODULES;
}
```

You can add dconf and glib-networking modules as needed.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/151105 was merged, this should be fixed now.

**Comment by simoneruffini** [comment]
> Do you use some desktop environment? Trash usually requires `services.gvfs.enable = true;` NixOS option.

If I don't use a DE but a WM with no file explorer (e.g. nautilius) do I still need gvfs to run gio trash?

**Comment by jtojnar** [comment]
@simoneruffini 

1. the tool runs `g_file_trash` https://github.com/GNOME/glib/blob/d37beda25e5d7b93c06e214f967b5cb5254e535f/gio/gio-tool-trash.c#L269
2. which calls the trash virtual method: https://github.com/GNOME/glib/blob/d37beda25e5d7b93c06e214f967b5cb5254e535f/gio/gfile.c#L4454
3. I have not looked into details how [Glib’s GVfs](https://github.com/zsx/glib/blob/af653f2c2de13fa6f8cd154b121201d50ec6b695/gio/gvfs.c#L228) (not to be confused with the GVfs project, which ships [another `GFile` implementation](https://github.com/GNOME/gvfs/blob/ffcd0427c903d5f00d2ffcbc726c7ee5964aa9f1/client/gdaemonfile.c#L56-L58)) chooses the implementation but if it chooses `GLocalFile`, it looks like that one at least seems to move the file to trash directory by itself: https://github.com/GNOME/glib/blob/d37beda25e5d7b93c06e214f967b5cb5254e535f/gio/glocalfile.c#L3022

**Comment by simoneruffini** [comment]
Yea, I should have been more precise! I'm curently using it for deletion and it works, but if used for restoring the deleted file, it returns me the same error of the first comment

**Comment by jtojnar** [comment]
Right, that too can be seen in the code – it requires the trash protocol, which is provided by gvfs, to restore files: https://github.com/GNOME/glib/blob/d37beda25e5d7b93c06e214f967b5cb5254e535f/gio/gio-tool-trash.c#L258
