### ISSUE TITLE
hsdev-0.1.6.0 tests fail when being built.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#14083]
### Basic info

To make sure that we are on the same page:

* Kernel:

    Linux lenovo 3.18.26 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux

* System:

    15.09.1155.7664d23 (Dingo)

* Nix version:

    nix-env (Nix) 1.10

* Nixpkgs version:

    15.09.1155.7664d23

### Describe your issue here

Starting a nix-shell with hsdev included fails during the build for hsdev.

### Expected result

Enter into a nix-shell with hsdev built.

### Actual result

    > nix-shell -p haskellPackages.hsdev --command zsh
    <lots of prior output>
    [1 of 1] Compiling Main             ( tests/Test.hs, dist/build/test/test-tmp/Main.dyn_o )
    Linking dist/build/test/test ...
    running tests
    Running 1 test suites...
    Test suite test: RUNNING...
    
    scan project
      should scan project FAILED [1]
    
    Failures:
    
      tests/Test.hs:29: 
      1) scan project should scan project
           uncaught exception: IOException of type NoSuchThing (tests\test-package: canonicalizePath: does not exist (No such file or directory))
    
    Randomized with seed 33653890
    
    Finished in 0.0009 seconds
    1 example, 1 failure
    20/03/16 16:17:49 +0000	INFO	> Log politics: low = Info, high = Warning
    Test suite test: FAIL
    Test suite logged to: dist/test/hsdev-0.1.6.0-test.log
    0 of 1 test suites (0 of 1 test cases) passed.
    builder for ‘/nix/store/15d1jjmbcksnh5blzqx0xj08z38bv800-hsdev-0.1.6.0.drv’ failed with exit code 1
    error: build of ‘/nix/store/15d1jjmbcksnh5blzqx0xj08z38bv800-hsdev-0.1.6.0.drv’ failed
    /run/current-system/sw/bin/nix-shell: failed to build all dependencies

### Steps to reproduce

Run ```nix-shell -p haskellPackages.hsdev ```

**Comment by joachifm** [comment]
Could you elaborate on why you think this is a nixpkgs issue (and not an upstream issue)?

**Comment by seanparsons** [comment]
@joachifm I don't if I'm perfectly honest, but I couldn't find it affecting anyone else and that it was something akin to a file not found error made raised my suspicion of it being specific to Nix. I managed to get version 0.1.7.1 working from the 16.03 beta, so I'm happy for this to be closed in truth.

**Comment by joachifm** [comment]
Okay. Looks like the error you hit is this one: https://github.com/fpco/stackage/pull/1206#issuecomment-181285050
