### ISSUE TITLE
error: a 'x86_64-darwin' with features {} is required to build '/nix/store/....-pandoc-2.14.0.2.drv', but I am a 'aarch64-darwin' 

### ISSUE THREAD

**Issue by shaunsingh** [NixOS/nixpkgs#140816]
### Describe the bug
Trying to build my configuration on macOS (m1, aarch64-darwin). Looks like pandoc is available (and it downloads from the cache) but refuses to install because of this  error: 

### Steps To Reproduce
1. Use an m1 machine, install nix
2. `nix-shell -p nixUnstable git`
3. `nix run github:shaunsingh/vimrc-dotfiles --extra-experimental-features nix-command --extra-experimental-features flakes  --impure`

### Expected behavior
Pandoc should install as usual 

### Screenshots
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/71196912/136299367-22854228-2f66-4294-8ade-974ca2d7e7cf.png">

### Notify maintainers
I think its @bgamari who maintains ghc (which allows pandoc to build) according to an old issue I found

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210922_bcd73eb`
 - channels(shauryasingh): `"darwin"`
 - channels(root): `"nixpkgs-21.11pre320922.ee084c02040"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by cdepillabout** [comment]
@shaunsingh Can you reproduce this without having your dotfiles invovled?  It is entirely possible that your dot files are causing the problem, and this isn't a problem in Nixpkgs.
