### ISSUE TITLE
mumble-1.3.0-git-2015-11-08 doesn't show icons

### ISSUE THREAD

**Issue by ben0x539** [NixOS/nixpkgs#14084]
## Basic info
- Kernel: Linux vigil 4.4.5 #1-NixOS SMP Wed Mar 9 23:35:58 UTC 2016 x86_64 GNU/Linux
- System: 16.09pre78848.9549257 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre78848.9549257"
## Describe your issue here

Most icons, for example in the toolbar, the tray area, and beside items in the various tree views in the GUI, are missing in mumble_git.

`nix-env -iA kde5.breeze-icons` seems to be a workaround, even though afaict most of those icons are mumble-specific and not part of breeze.
### Expected result

![](http://i.imgur.com/axI6W00.png)
### Actual result

![](http://i.imgur.com/41MIT8U.png)
### Steps to reproduce

`nix-env -iA nixos.mumble_git`, without having installed `nixos.kde5.breeze-icons` or presumably other parts of of kde that pull that in.

**Comment by codyopel** [comment]
@ben0x539 
Mumble bundles all of its own icons, the issue is that it fails to load svg icons.  I looked into this at one point and I believe it may be an issue with qt5 qtsvg, but I could be wrong.

cc @ttuegel

**Comment by abbradar** [comment]
I've seen this issue from time to time and can't still don't have any clue what's going on -- it fixes itself magically after a while.

**Comment by ttuegel** [comment]
I presume this pertains to the Qt 5 version of mumble. The package provides SVG icons, so it needs qtsvg at runtime; that is why installing breeze-icons may fix this issue. There are three things the maintainers (@viric @jgeerds @wkennington) need to do to fix this issue:

1. Call the package with `qt5.callPackage`.
2. Include `qtsvg` in `buildInputs`.
3. Wrap the resulting executable(s) with `wrapQtProgram` after `installPhase`.

**Comment by pstn** [comment]
I also had that problem with the default mumble package and it got fixed after I installed ```kde5.breeze-icons```.

**Comment by garbas** [comment]
@viric @jgeerds @wkennington pinging maintainers to fix the issue as described by @ttuegel

**Comment by garbas** [comment]
anybody else @pstn @ben0x539 @abbradar @codyopel also welcome to send a PR :)

**Comment by abbradar** [comment]
I had this issue before but I can't reproduce it now. I'm using Qt 4 version of Mumble.

**Comment by RonnyPfannschmidt** [comment]
i can reproduce on mumble_git

**Comment by abbradar** [comment]
@RonnyPfannschmidt can you try https://github.com/abbradar/nixpkgs/commit/5bf8b491322ce279ea993f788a901c71e2cfb901? Also, check if you can reproduce it with `mumble` (I still can't).

**Comment by RonnyPfannschmidt** [comment]
@abbradar building now, i noticed that also the buildinput for python is missing (and this causes nonfatal errors)

**Comment by RonnyPfannschmidt** [comment]
@abbradar the patch works

**Comment by abbradar** [comment]
Thanks for testing! I've also patched Python scripts.
