### ISSUE TITLE
pkg request: poweralertd: "UPower-powered power alerter"

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#140842]
**Project description**
>Gives you power notifications as you need them. Just run it.

>Depends on UPower and a notification daemon such as mako.

**Metadata**

* homepage URL: https://sr.ht/~kennylevinsen/poweralertd/
* source URL: https://sr.ht/~kennylevinsen/poweralertd/
* license: gpl3
* platforms: linux

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/tools/misc/poweralertd/default.nix
