### ISSUE TITLE
Installing the bind package does not enable `dig` command

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#140897]
### Describe the bug
After `nix-shell -p bind` the `dig` command is not available, contrary to the "command not found" output.

### Steps To Reproduce
1. Enter a shell where the `dig` command is unavailable
2. Run `nix-shell -p bind`
3. Run `dig`

### Expected behavior

`dig` should run.

### Actual behavior

I get the following error message:

```text
The program 'dig' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p bind
```

### Additional context

An actual shell session:

```console
$ dig example.org
The program 'dig' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p bind
$ nix-shell -p bind
these paths will be fetched (0.26 MiB download, 1.57 MiB unpacked):
  /nix/store/946536x76q28agq77s4r13826p2q0cp9-bind-9.16.16-dev
copying path '/nix/store/946536x76q28agq77s4r13826p2q0cp9-bind-9.16.16-dev' from 'https://cache.nixos.org'...
$ dig example.org
The program 'dig' is not in your PATH. You can make it available in an
ephemeral shell by typing:
  nix-shell -p bind
```

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.70, NixOS, 21.05.3532.aff647e2704 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3532.aff647e2704"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by holykol** [comment]
you can also get `dig` from `dnsutils`

`nix-shell -p dnsutils --run dig`

**Comment by jkxyz** [comment]
Related issue: https://github.com/NixOS/nixos-channel-scripts/issues/26

**Comment by l0b0** [comment]
@jkxyz I'd be OK with closing this in favour of that issue. Unfortunately it's been open for over two years now.
