### ISSUE TITLE
NFSv4 integrated security

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#14091]
If one looks at `http://nfs.sourceforge.net/nfs-howto/ar01s06.html` and compares that to what NixOS is currently offering, it seems the default setup is rather insecure. I would like to see a module which manages all aspects of NFS configuration (so, including managing /etc/hosts.{allow,deny}, etc).

**Comment by layus** [comment]
Your are most welcome to submit a pull-request for these. I would be happy to review it and provide feedbak. However I have no knowledge of how nfs is configured, and what options should be added for security.

**Comment by abbradar** [comment]
As part of https://github.com/NixOS/nixpkgs/pull/22303 I consider to disable tcp-wrappers and have users relying on NixOS firewall instead.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by layus** [comment]
@mmahut  We have no response from OP, and abbradar's #22303 was merged. It seems that this con be closed indeed.
