### ISSUE TITLE
Documentation: How to purge a packages state?

### ISSUE THREAD

**Issue by angerman** [NixOS/nixpkgs#14099]
So I just ran into the issue of trying to do a force reinstall of gitlab (which brings in redis). I failed to find a command that would take care of purging all the state, should I have wanted to.

What I ended up with was:

``` bash
$ rm -fR /var/lib/redis
$ rm -fR /var/gitlab
$ dropdb gitlab
$ dropuser gitlab
```

This seems far from perfect. Maybe I've just missed some documentation?

**Comment by vcunat** [comment]
If anywhere, such functionality could be in the gitlab service, but I believe there's nothing general. I can't even see what such a general thing might look like.

**Comment by angerman** [comment]
I have no idea how this could look either. But maybe integrate with the garbage collection. E.g. allow to collect `stateful` garbage. This clearly needs to be marked dangerous though.

Yet for the gitlab case, not properly purging the state, results in either a broken gitlab instance, with weird error messages (e.g. pushing through ssh is broken). Or if one forgets to drop the user, the service won't start with a message that the ROLE already exists. One needs to make the mental leap from ROLE to postgres database roles to make sense of it.

I initially tried to drop gitlab from the configuration file, rebuild, re-add it and rebuild again hoping I would be presented with a clean slate. But the system was in an invalid state due to dirty state. And yes, state is something very annoying!

Maybe @fpletz has some idea esp. with respect to gitlab, yet this could be a more general theme I think.

**Comment by vcunat** [comment]
In general I believe we add state to services only in those cases where you typically want to keep the state (i.e. persist across reboots and nixos version switches).

**Comment by angerman** [comment]
@vcunat certainly! Yet what happens to state that gets stale because the package that introduced that state was removed? Are you guaranteed that the state is going to work across versions even with multiple intermediate ones skipped?

This is probably getting even tricker as you have to keep track of the state introduced by each package (as future package might introduce different state, and won't be able to clean up state left behind by previous versions).

And you also run into the following issue:

Say version `A` introduces sate: `[W,X,Z]`, and version `B` introduces state: `[X, Y]`.

When going from `A` to `B`, would you want to have `[W,Z]` purged? If it's not used with `B` anymore, it could be considered garbage, I assume? This is certainly quite a hard thing to get right.

**Comment by vcunat** [comment]
Better move this discussion to https://github.com/NixOS/nixpkgs/issues/7420 to have it in one place.
