### ISSUE TITLE
Documentation: How to use lib.optional keys with configuration.nix

### ISSUE THREAD

**Issue by angerman** [NixOS/nixpkgs#14097]
Packages like `postfix` and `dovecot` come with `withMySQL` and `withPgSQL` options. 

I was unable to find the corresponding documentation on how to set those through the `configuration.nix` file. What I ended up with was (which feels wrong though):

```
  nixpkgs.config.packageOverrides = pkgs: { postfix = pkgs.postfix.override { withPgSQL = true; }; };
```

**Comment by fpletz** [comment]
Yes, that's the correct way to override these options of packages for the whole system.

Dovecot and some other service modules (but unfortunately not postfix) also support overriding the package to use. For Dovecot you could get away with:

```
services.dovecot2.package = pkgs.dovecot22.override { withPgSQL = true; };
```

**Comment by angerman** [comment]
@fpletz Thanks! Should this be considered a bug in the postfix pkg?

How do those flags play with hydra? I assume if hydra would build all that would result in a complexity explosion. On the other hand, what does a successful hydra build mean if one can break it using some of the options the packages provide? The test coverage of the packages would only partial?

**Comment by fpletz** [comment]
Yup, your assumptions are correct. Unfortunately the current state is that hydra builds only the versions referred from `pkgs/top-level/all-packages.nix`. If you need a special version you will have to compile it yourself right now and if a single flag or combinations of flags introduce a build failure we probably are not testing for it right now. There are some packages that do have multiple versions (like minimal or full) defined, but most don't.

We should do something about that, but I'm not sure how. We don't have the resources to build all combinations of flags over the whole package set.

**Comment by angerman** [comment]
Building all combination of flags is certainly going to just just explode. But maybe we could opt for N+1 extra builds? build each flag separately and build all flags together? Unless they are mutually exclusive?
Should the package provide common configurations?

**Comment by vcunat** [comment]
> We don't have the resources to build all combinations of flags over the whole package set.

Note that this isn't just about Hydra resources, but also about increasing the *maintenance* burden. It's just harder to keep all those versions working.

**Comment by peti** [comment]
The dovevot `package` option seems redundant to me and I'd be in favor of removing it.

**Comment by fpletz** [comment]
I don't really have an opinion on this, but we should stick to one solution instead of the current incoherent situation.
