### ISSUE TITLE
How to do NFSv4 with restricted exports?

### ISSUE THREAD

**Issue by aragnon** [NixOS/nixpkgs#14090]
I have the following setup:

```
fileSystems."/export/a" = {
    device = "/mnt/exported_data/a";
      options = "bind";
   };

   fileSystems."/export/b" = {
     device = "/mnt/exported_data/b";
      options = "bind";
   };

services.nfs.server.exports = ''
  /export/a                192.168.3.45(rw,fsid=0,no_subtree_check,root_squash)
  /export/b          192.168.3.45(rw,fsid=0,no_subtree_check,root_squash)
'';
```

However, on a client machine user `b` sees the data in `/mnt/exported_data` and not as desired only the data in `/mnt/exported_data/b`. In short, information (e.g. a file `/mnt/exported_data/test_file`) is shared which shouldn't be.

**Comment by layus** [comment]
It feels to me like your question lacks some info. Is this configuration on the same host or on three different hosts ?

Furthermore, could you look into /mnt/exported_data/b to see if it has the right content ? And in /export/b ? Have you looked into your /etc/exports, and yout /etc/fstabs on all these systems ?

**Comment by gleber** [comment]
Is this question still relevant? If not, please consider closing it.

**Comment by abathur** [comment]
Closing because none of the previous attempts to obtain more information succeeded and aragnon's account has no public activity beyond about 3 weeks after this issue was created. Happy to reopen if they or someone else speaks up for it, though :)
