### ISSUE TITLE
firefox-wayland: attribute 'gtk3' missing

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#141088]
### Describe the bug
gtk3 attribute is missing in firefox-wayland 

### Steps To Reproduce
1. install home-manager
2. switch to firefox-wayland
```nix
        programs.firefox = {
                enable = true;
                package = pkgs.firefox-wayland;
        };
```
3. run `home-manager switch`

### Expected behavior
Should be installed ;)

### Screenshots
```
attribute 'gtk3' missing, at /nix/store/mvlwybz40cl0awgrqkf5x5bddlqpcgdp-nixos-21.11pre321644.5e2018f7b38/nixos/pkgs/applications/networking/browsers/firefox/wrapper.nix:193:23
```

### Notify maintainers
 hope one of this is the maintainer: @eelco @lovesegfault @hexa

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/hkwbmwg2bzhrrjvwc1xassxcfy0ci76c-bash-interactive-5.1-p8-dev
copying path '/nix/store/hkwbmwg2bzhrrjvwc1xassxcfy0ci76c-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.70, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre321644.5e2018f7b38"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

My first issue here ... be kind

**Comment by jtojnar** [comment]
Yes, you are doing an unsupported thing. The only issue is that home-manager does not provide a more sensible error message.

**Comment by rofrol** [comment]
from the link @jtojnar  posted:

```nix
        default = if versionAtLeast config.home.stateVersion "19.09" then
          pkgs.firefox
        else
          pkgs.firefox-unwrapped;
```

**Comment by Sweenu** [comment]
I have the exact same issue while trying to override `firefox` to enable tridactyl native: https://github.com/nix-community/home-manager/issues/253
My `stateVersion` is 22.05.

**Comment by jtojnar** [comment]
Please make sure you have `home.stateVersion` set appropriately – it is distinct from NixOS `stateVersion`.

**Comment by Sweenu** [comment]
Thank you! That was it. Because `system.stateVersion`'s default was 22.05 I assumed this was also the case for `home.stateVersion` but the default is 18.09.
