### ISSUE TITLE
command-not-found is broken

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14115]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`) `Linux abbradarbook 4.5.0 #1-NixOS SMP Mon Mar 14 04:28:54 UTC 2016 x86_64 GNU/Linux`
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) `16.09.git.0907de9 (Flounder)`
* Nix version: (run `nix-env --version`) `nix-env (Nix) 1.11.2`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) `16.09.git.0907de9`

## Describe your issue here
`command-not-found` doesn't work because it cannot find SQLite database with programs. I'm not sure if that's because its location is changed or it's gone from the channel (IIUC `programs.sqlite` is distributed along with it).

### Expected result
`command-not-found` reports packages from which I can install the called application.

### Actual result
```
DBI connect('dbname=/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite','',...) failed: unable to open database file at /run/current-system/sw/bin/command-not-found line 13.
cannot open database `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite' at /run/current-system/sw/bin/command-not-found line 13.
```

### Steps to reproduce
1. `sudo nix-channel --update`
2. `command-not-found qdbus`

**Comment by joelmo** [comment]
See https://github.com/NixOS/nixos-channel-scripts/issues/4
