### ISSUE TITLE
addExtraLibrary, addExtraLibraries does not preserve haskell's .env derivation

### ISSUE THREAD

**Issue by rehno-lindeque** [NixOS/nixpkgs#14127]
When creating a `shell.nix` file, haskell gives you a handy `my-project.env` derivation that spins up a development environment without first compiling `my-project`.

E.g. 
```nix 
let
  drv = haskellPackages.callPackage ./. {};
in
  if pkgs.lib.inNixShell
  then drv.env # nifty!
  else drv
```

Unfortunately modifying the original derivation with `addExtraLibrary` causes the derivation to once again compile everything from scratch. I.e.

```nix
let
  drv = haskellPackages.callPackage ./. {};
in
  if pkgs.lib.inNixShell
  then (pkgs.haskell.lib.addExtraLibrary haskellPackages.foreign-store drv).env
  else drv
```

...causes `my-project` to compile...

```
$ nix-shell --run 'cabal repl --ghc-options="-package foreign-store-0.2"'
these derivations will be built:
  /nix/store/fkyly4sx4iaish9aiwljr1z1k3ivjd5b-my-project-0.0.4.drv
  /nix/store/x3i26gmblcaj5l869sfm46rw05d0lipc-ghc-7.10.3.drv
```

...instead of simply dropping me into an environment with `my-project`'s dependencies and `foreign-store` tacked on. I would hope to see this instead:

```
$ nix-shell --run 'cabal repl --ghc-options="-package foreign-store-0.2"'
these derivations will be built:
  /nix/store/hsmn1245fqh38l17g698fmzhz9x52lgr-interactive-my-project-0.0.4-environment.drv
```

**Comment by abbradar** [comment]
cc @peti

**Comment by peti** [comment]
I don't see why this behavior should be unexpected. When the compiler's environment is modified, Nix will build a new compiler environment (which is what `/nix/store/x3i26gmblcaj5l869sfm46rw05d0lipc-ghc-7.10.3.drv` refers too). There's no way to prevent that, and that build is super cheap and fast. I don't see what the problem is, really.

**Comment by rehno-lindeque** [comment]
Thanks @peti, sorry I think you misunderstood. Let me try a to restate the problem more clearly: I expected that `drv.env` will only build the dependencies for `my-projects`. However, from what I remember about this issue, `(pkgs.haskell.lib.addExtraLibrary haskellPackages.foreign-store drv).env` doesn't build only the environment, it seems to build `my-project` directly.
