### ISSUE TITLE
Tetrio +

### ISSUE THREAD

**Issue by Swalawaga** [NixOS/nixpkgs#141218]
**Project description**
Tetris client 

**Metadata**

* homepage URL:
* https://gitlab.com/UniQMG/tetrio-plus/-/wikis/home
* source URL:https://gitlab.com/UniQMG/tetrio-plus/-/wikis/home
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by abathur** [comment]
Is this tetrio equivalent to the tetrio contributed in this PR? 
- https://github.com/NixOS/nixpkgs/pull/146940

**Comment by Enzime** [comment]
I've packaged this in #201596

**Comment by huantianad** [comment]
Didn't notice this issue, should be closed by #199948.
