### ISSUE TITLE
Notion Repackaged

### ISSUE THREAD

**Issue by mys31f** [NixOS/nixpkgs#141238]
**Project description**
Basically a project that is made to bring the Notion note-taking application to more than the platforms that Notion supports

**Metadata**

* Homepage URL: https://github.com/notion-enhancer/notion-repackaged
* Source URL:
* License: MIT
* Platforms: Windows, Mac, Linux

**Comment by ElXreno** [comment]
I have prepared a temporary solution for now.
Need to solve the Electron problem, because Notion depends on the old version, which is already EoL.
https://github.com/ElXreno/nixpkgs/tree/notion-repackaged

**Comment by mys31f** [comment]
Is it on like a version before 13?

**Comment by ElXreno** [comment]
That's right. It is currently using version 11.

**Comment by WolfangAukang** [comment]
@ElXreno you can try something like [this](https://github.com/NixOS/nixpkgs/commit/d382dd518fc4456d317672fa245cc5231f7dc1f5#diff-7b36f17498dfeaec2566e48b41fd055120c4579fc4b032a362dffb3fefb568c7)
