### ISSUE TITLE
nftables triggers kernel panics when "socket cgroupv2" expressions are being used

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#141228]
### Describe the bug
Adding a rule that contains a socket cgroupv2 expression ([example](https://github.com/poscat0x04/nixos-configuration/blob/bb08132face479857fc7754d6c8da70d9b7625aa/modules/networking/firewall.nix#L53)) to nftables triggers a kernel after a short delay (~1s).

### Steps To Reproduce
1. use the latest linux kernel (linuxPackages_latest)
2. create the following file:
```
table ip tpxy {
  chain prerouting {
    type filter hook prerouting priority mangle; policy accept;
    socket cgroupv2 level 1 "system.slice" accept
  }
}
```
3. run `sudo nft -f YOUR_FILE_NAME`
4. wait for a few seconds

### Expected behavior
Clearly it should not cause a kernel panic

### Additional context
I've heard from an Arch Linux user that this expression works on Arch and does not trigger a kernel panic, so I think this might have something to do with NixOS's kernel config? IDK. But again, I've never verified his claim on an Arch machine myself.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.10, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/nix/store/bjq298kb21bmvyad0ks3r78mvyklc1kq-source`
 
btw I'm using my own [fork](https://github.com/poscat0x04/nixpkgs/tree/dev) of nixpkgs, which is basically just nixos-unstable with some unmerged PR cherry-picked in.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flokli** [comment]
@poscat0x04 is this still an issue? Could this be an upstream kernel bug? I'd be very surprised of this being a NixOS-specific bug…

**Comment by poscat0x04** [comment]
Nope this is no longer an issue. I'm fairly certain it was a kernel bug, but it might also had something to do with NixOS's kernel configuration (which triggered the bug). Anyways, I should close this issue as resolved.
