### ISSUE TITLE
The python version of docker-registry is deprecated

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#14129]
See https://github.com/docker/docker-registry; the replacement is https://github.com/docker/distribution

TODO:
- [ ] Package the Go version of the docker registry
- [ ] Update the docker-registry service to use the Go version
- [ ] Disable/remove the deprecated version of docker-registry

**Comment by joachifm** [comment]
@offlinehacker, thoughts?

**Comment by grahamc** [comment]
Not surewhat thoughts there are to be had, this is the appropriate action.

**Comment by offlinehacker** [comment]
Yep, it's deprecated, do it :)

**Comment by joachifm** [comment]
Just to clarify: I don't care about docker and probably won't be working on this issue. I think it's actionable, so I'm leaving it open.
