### ISSUE TITLE
`programs.bash.undistractMe.enable = true;` doesn't do anything

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#141332]
**Describe the bug**

I've set the above, but commands like `sleep 11` don't trigger any kind of notification. The documentation also doesn't mention what form these notifications should take.

**Steps To Reproduce**

1. Set `programs.bash.undistractMe.enable = true;` in /etc/nixos/configuration.nix
2. `sudo nixos-rebuild switch`
3. Open a terminal
4. Run `sleep 11`

**Expected behavior**

Some kind of notification should show after exceeding the default 10s timeout.

**`nix-env --version` output**

nix-env (Nix) 2.3.15

**Additional context**

I'm running GNU Bash 4.4.23 in kitty 0.20.3, using a heavily customized [~/.bashrc](https://gitlab.com/victor-engmark/tilde/-/blob/c833930388b5511a9c94dd1ada83edb4edec8be5/.bashrc).

**Comment by hmenke** [comment]
What does `echo $__ETC_BASHRC_SOURCED` say?

**Comment by l0b0** [comment]
This behaviour seems to persist in 21.11.

**Comment by Artturin** [comment]
what are the values of `UDM_PLAY_SOUND` `LONG_RUNNING_COMMAND_TIMEOUT`

**Comment by Artturin** [comment]
i did `source ./result/etc/profile.d/undistract-me.sh` in a fresh bash (i use zsh) and i got `Command completed in X`

**Comment by l0b0** [comment]
Shouldn't enabling undistract-me take care of sourcing that in the core Bash profile?

**Comment by l0b0** [comment]
undistractme seems to work in NixOS 23.05. Thank you for the help!
