### ISSUE TITLE
Cannot connect to Docker host when firewall enabled

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nixpkgs#141377]
### Describe the bug

Docker containers cannot connect to services hosted on the host machine. This _only_ happens whenever the firewall is enabled in NixOS.

For example, I have enabled the firewall in NixOS. I run a webserver on my host on port 8080. I start a container with access to the host. I try to connect to the webserver from the container and I get a connection refused.

Doing the same scenario with the firewall disabled results in a successful HTTP call.

I have tried to configure NixOS to allow docker, but it did not help:

```
networking.firewall.trustedInterfaces = [ "docker0" ];
```

I have little experience with iptables, so I had trouble finding how this should be resolved.

### Steps To Reproduce

My laptop runs the following configuration:

```
{
  networking.firewall.enable = true;
  virtualisation.docker.enable = true;
}
```

Start a HTTP server on port 8080 on the host machine:

```
$ nix run nixpkgs#darkhttpd .
darkhttpd/1.13, copyright (c) 2003-2021 Emil Mikulic.
listening on: http://0.0.0.0:8080/
```

Run a docker container that attempts to connect to the host machine:

```
$ docker run -it --add-host host:host-gateway curlimages/curl --connect-timeout 1 http://host:8080/
curl: (28) Connection timed out after 1001 milliseconds
```

To confirm this is a firewall issue I disabled the firewall in NixOS and ran the above `docker run` command again. It succeeded:

```
$ docker run -it --add-host host:host-gateway curlimages/curl --connect-timeout 1 http://host:8080/
...
Generated by darkhttpd/1.13 on Tue, 12 Oct 2021 16:05:21 GMT
...
```

### Expected behavior

I expected to be able to connect to the host machine from a Docker container when using `--add-host host:host-gateway`. I expected an option in NixOS to allow Docker containers to connect through an enabled firewall.

### Additional context

`--add-host host:host-gateway` in docker is a new feature that adds an entry to the hosts file of the container. The entry has a name `host` and the IP is the IP of the host in the Docker bridge interface.

### Notify maintainers

@Mic92 you were merging most of the PRs regarding `docker.nix`. Let me know if I'd need to ping someone from `firewall.nix`.

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.71, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"nixos-21.03pre268835.8c8731330b5"`
 - channels(bob.vanderlinden): `"home-manager, nixpkgs-21.03pre269329.dd65c8b2a7c"`
 - nixpkgs: `/home/bob.vanderlinden/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
nixos/modules/virtualisation/docker.nix
nixos/modules/services/networking/firewall.nix
```

**Comment by sebastiant** [comment]
Can you confirm that
`networking.firewall.trustedInterfaces = [ "docker0" ];`
still does not work? I am unable to reproduce the problem

**Comment by bobvanderlinden** [comment]
It indeed resolved! (with `networking.firewall.trustedInterfaces = [ "docker0" ];`)

Thanks for the reminder :+1:
