### ISSUE TITLE
jellyfin: add dataDir option

### ISSUE THREAD

**Issue by tmplt** [NixOS/nixpkgs#141367]
I currently run Jellyfin in a Docker container but want to deploy it using an ephemeral NixOS container. However, `services.jellyfin` does not expose a `dataDir` option and runs Jellyfin with `--datadir '/var/lib/${StateDirectory}'` where `serviceConfig.StateDirectory = "jellyfin"`. I understand that this directory will be cleared when the container restarts.

I'm not familiar with `systemd`'s `StateDirectory` nor the aggressive sandboxing. Need I consider something else when adding the `dataDir` option other than user permissions?

@minijackson

**Comment by rasmus-kirk** [comment]
I am experimenting with this, I just added some options for defining a `dataDir` and a `cacheDir`. It seems to "just work tm", but is there anything I should be aware of? I'll run my own nixpkgs branch on my own machine for a little bit before creating a PR, but so far it seems fine.

@tmplt

**Comment by bjornfor** [comment]
I looked a bit into this, and I think bind mounts is what works best with systemd. But I didn't really find a lot of info...

**Comment by bjornfor** [comment]
Relevant: https://discourse.nixos.org/t/infinite-recursion-when-creating-bind-mounts-for-certain-systemd-services

**Comment by ciferkey** [comment]
I'm interested in this as well. Currently the Sonarr, Radarr, Jackett, and Ombi servicesprovide `dataDir`. Is the approach they use also usable here? 

https://github.com/NixOS/nixpkgs/blob/0040164e473509b4aee6aedb3b923e400d6df10b/nixos/modules/services/misc/sonarr.nix#L50-L53
