### ISSUE TITLE
[pkgs.linux_rpi4] Out-of-date & cannot build.

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#141470]
Current version: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/linux-rpi.nix#L6
Latest version: https://github.com/raspberrypi/linux/releases/tag/1.20210928

###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: linux_rpi4
current version: 1.20210805
desired version: 1.20210928

###### Notify maintainers
maintainers: @thoughtpolice 

###### Note for maintainers
Please tag this issue in your PR.

**Comment by sealor** [comment]
I assume that I have the same problem.
After setting `boot.kernelPackages = pkgs.linuxPackages_rpi3;` the build fails with the following error message:

```
[...]
root module: ext2
  copying dependency: /nix/store/4ahwzl25nz7bqsqydkc7l8q7lnjvj4b7-linux-5.10.52-1.20210805-modules/lib/modules/5.10.52/kernel/fs/ext2/ext2.ko.xz
root module: ext4
  builtin dependency: ext4
root module: ahci
modprobe: FATAL: Module ahci not found in directory /nix/store/4ahwzl25nz7bqsqydkc7l8q7lnjvj4b7-linux-5.10.52-1.20210805-modules/lib/modules/5.10.52
builder for '/nix/store/mrr310qyphcb5mn218547yl9qi96z8gv-linux-5.10.52-1.20210805-modules-shrunk.drv' failed with exit code 1
cannot build derivation '/nix/store/k98qavxcv3qlc8wlkqm2dlq1sbbbrck4-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/r171hpg4d75iyrx0ffjx5h7m3w9ifn3z-initrd-linux-5.10.52-1.20210805.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/52r52bw4clbv3jikzawxb98hmy0kn3ja-nixos-system-raspi-21.11.334415.7d5ec2a2b4e.drv': 1 dependencies couldn't be built
error: build of '/nix/store/52r52bw4clbv3jikzawxb98hmy0kn3ja-nixos-system-raspi-21.11.334415.7d5ec2a2b4e.drv' failed
```
Exit code: `100`

I would like to fix this but I do not have enough experience. Could someone help?
Thx!

**Comment by sealor** [comment]
I found out that I need to set `boot.initrd.includeDefaultModules = false;` in my `configuration.nix`. Now, my `nixos-rebuild switch` runs successfully.
Nevertheless IMHO this should be set automatically when using an RaspberryPi kernel.

**Comment by VergeDX** [comment]
I also use option `boot.initrd.availableKernelModules = lib.mkForce [ ];` to make this.

**Comment by JamieMagee** [comment]
I recently rebuilt and updated the packages in #209742
