### ISSUE TITLE
i3-gaps as a package/package option?

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#14142]
## Basic info

Does it make sense to have i3-gaps as a package and/or windowManager option? If I understand the releases seem to match up (i3-4.11 and i3-gaps-4.11 are the same aside from the gaps additions).
ide from the gaps additions).

Maybe:

    services.xserver = {
      windowManager = {
        i3 {
           enable = true;
           gaps = true;
        }
      }
    }

**Comment by FRidh** [comment]
cc i3wm maintainers @garbas @modulistic

**Comment by garbas** [comment]
@sheenobu you can already override existing i3 `src` via common nix ways

as another way we could add `package` option (which defaults to i3). this would follow how other nixos modules are done (eg. look at postgresql).

makes sense?
