### ISSUE TITLE
jetbrains.clion: `$LD_LIBRARY_PATH` leaks into projects as path to search libraries to link

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#141593]
### Describe the bug

JetBrains editors run with `$LD_LIBRARY_PATH=${stdenv.cc.cc.lib}:...` which result in project built under the editors (i.e. `make` in `clion`'s terminal) always picks up `libstdc++.so.6` from `stdenv.cc.cc.lib`.
Even if the project is using for example `gcc11Stdenv`.
This result in ABI conflict when the build executable runs, because other components - which built using `nix-build`, outside clion - use `libstdc++.so.6` from `gcc11Stdenv.cc.cc.lib`

```
/nix/store/7zrjn2j9z86s2ba6gw9dcj1g96crg1xz-gcc-9.2.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/7rf5ciclwwzig5fjiv6bxnprbk9xb1ag-gtest-1.11.0/lib/libgtest.so.1.11.0)
```

https://github.com/NixOS/nixpkgs/blob/5724f5205cce3470f877ae3b807ea459c820ecd9/pkgs/applications/editors/jetbrains/common.nix#L79-L82

### Steps To Reproduce
well, this might be tricky to prepare a small project

### Expected behavior
`stdenv.cc.cc.lib` needed to support `clion` itself, should not leak into projects it edits

### Screenshots
![](https://imgur.com/QAIHCe9.png)

### Additional context
I suspect `libsecret` and `libnotify` in `$LD_LIBRARY_PATH` are problematic too

introduced in https://github.com/NixOS/nixpkgs/pull/24526 https://github.com/NixOS/nixpkgs/pull/36246 https://github.com/NixOS/nixpkgs/pull/47656 https://github.com/NixOS/nixpkgs/pull/134616

### Notify maintainers
@miltador @edwtjo 

```

**Comment by babbaj** [comment]
This is still a problem

**Comment by SemMulder** [comment]
Can confirm, this is an issue when using per-project environments which are on a different channel than my systems'. Shouldn't the "internals" be patched using e.g. `autopatchelf` instead?

**Comment by SemMulder** [comment]
For anyone else running into this: the workaround is to clear the `LD_LIBARY_PATH` environment variable in the IDE settings for the commands you want to run. Cumbersome, but it works.

**Comment by SemMulder** [comment]
The above workaround doesn't completely work. For instance, there is no way to remove `LD_LIBRARY_PATH` when setting the project interpreter in PyCharm.

**Comment by SemMulder** [comment]
The following seems to work:
```
{ pkgs
, lib
, jetbrains
, autoPatchelfHook
, stdenv
, libsecret
, e2fsprogs
, libnotify
, linux-pam
, audit
}:
jetbrains.pycharm-professional.overrideAttrs (attrs: {
  nativeBuildInputs = (attrs.nativeBuildInputs or [ ]) ++ [ autoPatchelfHook ];

  buildInputs = (attrs.buildInputs or [ ]) ++ [
    stdenv.cc.cc.lib
    libsecret
    e2fsprogs
    libnotify
    linux-pam
    audit
  ];

  # NOTE(Sem Mulder): Hacky way to disable LD_LIBRARY_PATH.
  installPhase = lib.replaceStrings [ "LD_LIBRARY_PATH" ] [ "WRONG_LD_LIBRARY_PATH" ] attrs.installPhase;
})
```

I'll try to prepare a PR in the coming days.

**Comment by lukovdm** [comment]
Has there been an update on this? I am trying to use prettier in Webstorm and all other tools to have needed the `LD_LIBRARY_PATH` to be reset, if I want to run them. But this is not possible for prettier. I suspect that it would work with `LD_LIBRARY_PATH` unset.

**Comment by babbaj** [comment]
Just had this come up again trying to build a program with gcc 13 in CLion. Simply removing `stdenv.cc.cc.lib` from `LD_LIBRARY_PATH` in [pkgs/applications/editors/jetbrains/linux.nix](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/jetbrains/linux.nix) fixes the issue and doesn't appear to break clion, idea, or rider.
