### ISSUE TITLE
gotify-desktop

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#141552]
**Project description**
Small Gotify daemon to receive messages and forward them as desktop notifications.

**Metadata**

* homepage URL: https://github.com/desbma/gotify-desktop
* source URL: https://github.com/desbma/gotify-desktop
* license: GPLv3
* platforms: linux, bsd, macOS, Windows

**Comment by bryanasdev000** [comment]
@genofire  can you give a try? https://github.com/NixOS/nixpkgs/pull/146341

I failed to make it work in a with the quick start from Gotify, it fails to connect, but otherwise the package looks OK.

Also, you want to me a maintainer?

**Comment by genofire** [comment]
nice, thank you - works for me

does we like to promote a systemd.unit user file? either?
 `~/.config/systemd/user/gotify-desktop.service`
```init
[Unit]
Description=Desktop notification from gotify
PartOf=graphical-session.target
After=graphical-session.target

[Service]
ExecStart=/home/genofire/.nix-profile/bin/gotify-desktop
Restart=on-failure

[Install]
WantedBy=graphical-session.target
```

it would be okay for me, that you add me as maitainer, but i am reallly a nix beginner ....

**Comment by bryanasdev000** [comment]
> nice, thank you - works for me
> 
> with `~/.config/gotify-desktop/config.toml` and my server (which has an open registration):
> 
> ```ini
> [gotify]
> url = "wss://gotify.sum7.eu"
> token = "SECRET"
> 
> [notification]
> min_priority = 1  # optional, ignores messages with priority lower than given value
> ```
> 
> does we like to promote a systemd.unit user file? either? `~/.config/systemd/user/gotify-desktop.service`
> 
> ```ini
> [Unit]
> Description=Desktop notification from gotify
> PartOf=graphical-session.target
> After=graphical-session.target
> 
> [Service]
> ExecStart=/home/genofire/.nix-profile/bin/gotify-desktop
> Restart=on-failure
> 
> [Install]
> WantedBy=graphical-session.target
> ```
> 
> it would be okay for me, that you add me as maitainer, but i am reallly a nix beginner ....

So do I :)

Usually updating existing expressions is easier than creating it, a bump in version and SHAs does the trick.

About the service I was thinking the same but by rule of thumb services that depends on something in $HOME is handled by home manager rather than NixOS modules. So I think a future PR can go there to enable a user service.

**Comment by genofire** [comment]
this way: https://github.com/NixOS/nixpkgs/pull/146743 ?

**Comment by bryanasdev000** [comment]
> this way: #146743 ?

Yeap! Just format and squash as bobby285271 asked and welcome aboard!
