### ISSUE TITLE
hydrogen-web

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#141586]
**Project description**
A minimal Matrix chat client, focused on performance, offline functionality, and broad browser support.

**Metadata**

* homepage URL: https://hydrogen.element.io/
* source URL: https://github.com/vector-im/hydrogen-web/
* license: Apache
* platforms: Browser

Deer matrix-team maintainers:
@ma27
@fadenb
@mguentner
@ekleog
@ralith
@mjlbach
@dandellion
@sumnerevans

**Comment by genofire** [comment]
No reaction, but still interresting for me.

**Comment by pbsds** [comment]
ftfy: @dali99
