### ISSUE TITLE
gnome ISO: limit exceeded

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#141521]
Hydra.nixos.org has limitation to 2G for the output size (uncompressed NAR), and currently the final gnome ISO is around 2.1G and therefore rejected: https://hydra.nixos.org/build/155865594

@NixOS/gnome

**Comment by jtojnar** [comment]
I noticed some low-hanging fruit of `propagatedBuildInputs` in `out` but https://github.com/NixOS/nixpkgs/pull/141533 only reduces the closure size of nautilus from 1.4G to 1.3G.

**Comment by vcunat** [comment]
And we're back: https://hydra.nixos.org/build/163381276

**Comment by jtojnar** [comment]
Looking at `nix-build nixos/release.nix -A iso_gnome`, quite a few `dev` outputs sneaked in:

- gnome.mutter → libgtop → glib.dev
- gnome-remote-desktop → libvncserver → zlib.dev
- pipewire-media-session → pipewire.dev
- chrome-gnome-shell → python3.pkgs.brotlicffi → python3.pkgs.brotlicffi.dev
- nix → aws-crt-cpp → s2n-tls.dev
- gnome-photos → ... → python3.pkgs.pygobject3.dev
- flatpak → p11-kit.dev

**Comment by jtojnar** [comment]
Started going down the list in https://github.com/NixOS/nixpkgs/pull/154064.

**Comment by legendofmiracles** [comment]
Just FYI: another tool that can show you what's taking up space in a derivation is `nix-tree`

**Comment by jtojnar** [comment]
That unfortunately does not seem to work for images:

![Result of running nix-tree on nix image](https://user-images.githubusercontent.com/705123/148978445-5ca8c5d3-c8b5-4c35-bd17-b3f65dd2857a.png)

**Comment by andersk** [comment]
You can run `nix-tree` on the closure that the image is built from:

```sh
nix-tree "$(nix-build nixos/release.nix -A closures.gnome.x86_64-linux)"
```

**Comment by vcunat** [comment]
I think the newly open issue contains better recent information now, let's only continue there: https://github.com/NixOS/nixpkgs/issues/159612

**Comment by edolstra** [comment]
We should probably revive #70981 to enforce that we don't have .dev outputs in our closures.
