### ISSUE TITLE
lens-4.12.3 broken using ghc-7.10.3

### ISSUE THREAD

**Issue by spacefrogg** [NixOS/nixpkgs#14162]
## Basic info

To make sure that we are on the same page:

* System: gentoo
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre78971.5bb0aa3

## Describe your issue here

The package lens_4_12_3 fails to build with the following error:

    Building lens-4.12.3...
    Preprocessing library lens-4.12.3...
    ...
    [18 of 81] Compiling Control.Lens.Internal.Fold ( src/Control/Lens/Internal/Fold.hs, dist/build/Control/Lens/Internal/Fold.o )

    src/Control/Lens/Internal/Fold.hs:223:21:
        Ambiguous occurrence ‘ReifiedMonoid’
        It could refer to either ‘Control.Lens.Internal.Fold.ReifiedMonoid’,
                                 defined at src/Control/Lens/Internal/Fold.hs:221:1
                              or ‘Data.Reflection.ReifiedMonoid’,
                                 imported from ‘Data.Reflection’ at src/Control/Lens/Internal/Fold.hs:39:1-22
    ...

### Expected result

lens builds successfully

### Actual result

lens build fails

### Steps to reproduce

`$ nix-env -f '<nixpkgs>' -iA haskellPackages.lens_4_12_3`

**Comment by peti** [comment]
What makes you think that this issue is in any way related to Nix?

**Comment by spacefrogg** [comment]
Well, shouldn't it have compiled at some point? And if, what changed? Shouldn't it then make assertions about required dependencies and versions? I mean, lens is a package in the official nixpkgs tree. And I am using no weird (meaning none) overrides but the current default versions for the haskell compiler and tools. Why should I not expect it to build correctly? And why should I not raise an issue about it if it starts failing to build?

**Comment by peti** [comment]
> Well, shouldn't it have compiled at some point?

No, why would you assume that? I'm sure that it compiles fine in some our 80+ Haskell package sets, but apparently it doesn't compile with GHC 7.10.3. Unless there is reason to believe that this failure is specific to Nix, I don't believe that we are the right people to report this issue to. Rather, you should probably report it upstream.

**Comment by spacefrogg** [comment]
Okay, I might not be familiar enough with package structure of haskell packages. This means, there is no continuous integration for the different package sets? I recognized that this specific lens version is exempt from hydra builds. Does this mean, that incompatibilities with specific package sets are not to be addressed when discovered? Anyway, I think it's safe to close this issue, then.

**Comment by peti** [comment]
> Does this mean, that incompatibilities with specific package sets are not to be addressed when discovered?

They are addressed when the issue is caused by *Nix*. If the upstream package is broken in some way, however, then you'll have to talk to the package's author -- not to us.
