### ISSUE TITLE
jre requiring X11 on OSX

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#14163]
### System:

 `darwin ; nix 1.11.2 ; channels/nixpkgs-unstable`
### Steps to reproduce:

```
$ nix-env -i groovy
$ groovysh
```
#### Expected:

groovy shell starts
#### Actual

This will open a dialogue telling me that I need to install X11 to run Java. If I build groovy with `jre8` instead of `jre` it works.

**Comment by garbas** [comment]
@gilligan could you try building jre without X11 on darwin. if it works you can make it optional for darwin then.

**Comment by Profpatsch** [comment]
triage: is this still a problem?
