### ISSUE TITLE
spacevim does not read global config when started from any directory other than $HOME

### ISSUE THREAD

**Issue by afwlehmann** [NixOS/nixpkgs#141626]
### Describe the bug
When starting `spacevim` from any directory other than `$HOME`, it will not read the global configuration under `~/.SpaceVim.d/init.toml` but instead fall back to the default config. Custom configuration will only be read as long as it is placed directly in the directory from where `spacevim` is started (such as should be the case for `spacevim` per-project configuration).

### Steps To Reproduce
1. Have your custom configuration stored under `~/.SpaceVim.d/init.toml`.
2. Change to any directory other than your home directory.
3. Start `spacevim` on a blank file or open any other file, e.g. `spacevim ~/.zshrc`.

### Expected behavior
`spacevim` reads and uses the global custom configuration unless overridden per-project.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@lourkeur (hope I got that right with `git blame`, sorry if I'm mistaken)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.70, NixOS, 21.05.3532.aff647e2704 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.3532.aff647e2704, nixos-unstable-21.11pre319271.31ffc50c571"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by lourkeur** [comment]
No big deal. The maintainer and the person who probably knows the most about this derivation is @fzakaria. I ran updates a couple times but I don't use this derivation anymore so I'm not sure what its intended behavior is in this situation.
