### ISSUE TITLE
espanso does not install on osX

### ISSUE THREAD

**Issue by maelp** [NixOS/nixpkgs#141638]
### Describe the bug
Trying to install espanso on osX, there are missing libraries, even after trying to install
`nixpkgs.darwin.apple_sdk.frameworks.Foundation` and `nixpkgs.darwin.apple_sdk.frameworks.CoreFoundation`

### Steps To Reproduce
1. `nix-env -iA espanso`
2. it tries to compile
3. it fails with 
```
  --- stderr
  /tmp/nix-build-espanso-0.7.3.drv-0/source/native/libmacbridge/bridge.mm:22:9: fatal error: 'Foundation/Foundation.h' file not found
  #import <Foundation/Foundation.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```
### Expected behavior
The build should work on osX

### Screenshots
n/a

### Additional context
latest osX with nixpkgs 21.15 and nix-darwin

### Notify maintainers
@numkem 
@legendofmiracles 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(primet): `"darwin, home-manager-21.05, nixpkgs-21.11pre320922.ee084c02040"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/primet/.nix-defexpr/channels/nixpkgs`
```

**Comment by legendofmiracles** [comment]
I tried adding them as dependencies, but the build still fails with the same error 🤷
