### ISSUE TITLE
torbrowser: support pluggable transports

### ISSUE THREAD

**Issue by Pleune** [NixOS/nixpkgs#14165]
#### System
- Kernel: `Linux nixos 4.4.4 #1-NixOS SMP Thu Mar 3 23:10:04 UTC 2016 x86_64 GNU/Linux`
- System: `16.09pre78286.0bf8a1a (Emu)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `16.09pre78286.0bf8a1a`
#### The issue:

The PluggableTransports have not been patched. I attempted to add them to the patch phase, but patchelf fails with the following:

> patchelf: patchelf.cc:693: void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym>::rewriteSectionsExecutable() [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym]: Assertion `(off_t) rdi(hdr->e_shoff) >= startOffset' failed.
> [1]    10371 abort      sudo patchelf --set-interpreter  meek-client

output of `file meek-client` :

> meek-client: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped

If you would like to see the log from tor: [pastebin.com](http://pastebin.com/6TAEK3kq/?e=1)
#### Steps to reproduce

Install tor-browser and attempt to use a bridge

**Comment by joachifm** [comment]
Could you explain in more detail how to reproduce this?

**Comment by joachifm** [comment]
Never mind, I get the same thing

**Comment by joachifm** [comment]
After looking at this, I think we can safely say that PluggableTransports are thoroughly broken at the moment

**Comment by joachifm** [comment]
@Pleune with 0a04f7a870e4a7e538387b4f8d0a79f9ebe76cb8 I'm now able to connect to pre-defined bridges using the obfs4 transport. Could you try if things have improved on your end?

**Comment by joachifm** [comment]
Well, I expect it to still fail on NixOS, but with a different error message at least.

**Comment by joachifm** [comment]
So on NixOS we're blocked by https://github.com/NixOS/patchelf/issues/66

**Comment by Pleune** [comment]
@joachifm I will test this out later today

**Comment by joachifm** [comment]
I think we need to think about building these things from source at some point. I'll be looking into at least building the transports from source, they are a rather important feature for those who need them, after all.

**Comment by Pleune** [comment]
I can confirm your findings. I can connect with predefined obfs4 bridges, and without obfuscation on all three of my machines. The default bridges do not work.

**Comment by joachifm** [comment]
I'm working on a re-write of the tor-browser package at https://github.com/joachifm/nixpkgs/tree/tor-browser Among other things, it adds a hack to allow plugin transports to be executed via the nixpkgs dynamic linker without patchelf, so should improve NixOS compatibility.

**Comment by spacekitteh** [comment]
Did you ever fix this?

I think we should definitely add pluggable transports to the standard Tor package as well.

**Comment by joachifm** [comment]
My rewrite effort did manage to get some of the transports working (except meek), but I utterly failed to get it working on grsec so lost interest. I might port over some of the wrapper improvements eventually.

From-source is probably the best way to go here. My thinking is that we build a custom bundle ontop of the firefox-esr derivation. My main worry is somehow introducing observable differences in the bundle that'd make nixpkgs users discernable from others ... avoiding that is the primary reason for using the upstream binaries.

Another possibility is to re-write the wrapper so that it copies the entire binary payload into $HOME and runs setfattr on it. That does work.

**Comment by joachifm** [comment]
I have mostly fixed this; all transports work for me now, all that remains is some polish & tweaks.

**Comment by spacekitteh** [comment]
How did you fix it?

**Comment by joachifm** [comment]
@spacekitteh brute force ... see https://github.com/joachifm/nixpkgs/commit/34c2f30959f027890de461c20ec0249b8b7a2a84

**Comment by spacekitteh** [comment]
hideous but I guess that can't be helped

**Comment by mmahut** [comment]
What is next here?

**Comment by spacekitteh** [comment]
@joachifm @Pleune any info?
