### ISSUE TITLE
Can't run JetBrains products.

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#141625]
### Describe the bug
Running any of the JetBrains products fails silently (visually). 

### Additional context
I am running the unstable version of all of them.

### Notify maintainers

@edwtjo @mic92

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.71, NixOS, 21.05.3740.ce7a1190a0f (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210922_bcd73eb`
 - channels(me): `"nixos-21.05.3740.ce7a1190a0f, nixos-unstable-21.11pre322215.9bf75dd50b7"`
 - channels(root): `"nixos-21.05.3740.ce7a1190a0f, nixos-unstable-21.11pre322215.9bf75dd50b7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Log output of `pycharm`:
https://hastebin.com/igibafiqan.sql

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: jetbrains.clion, jetbrains.idea-ultimate, jetbrains.pycharm-professional, jetbrains.webstorm
```

**Comment by em0lar** [comment]
Do you use Wayland or an XOrg based display manager?

**Comment by drupol** [comment]
Related to https://github.com/NixOS/nixpkgs/issues/147788

**Comment by mainrs** [comment]
> Related to #147788

After opening the issue I kept telling myself that this feels like a déjà vu...
Still the problem still exist in nixpkgs. Should I close my second issues and we use this one?

**Comment by drupol** [comment]
Duplicating issues is never a good idea... so I would say yes.

**Comment by hab25** [comment]
unstale

**Comment by mainrs** [comment]
Closed since the original one has been closed as well (https://github.com/NixOS/nixpkgs/issues/147788).
