### ISSUE TITLE
Deprecate usage of OpenGL utilties and NixOS options.

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#141803]
~~The `/run/opengl-driver/` directory contains more than just opengl libraries now. It also includes vulkan implementations, machine learning libraries, hardware-accelerated encoding and decoding, opencl implementations, and many others.~~ Directory renaming is now out of scope

This directory is also being used as the way to get access to the host machines gpu drivers. I think it's another source of confusion for many users to have to add `addOpenGLRunpath` so that they can get a vulkan game / cuda workload / opencl workload to work.

I think we should deprecate this prior to the 21.11 release, and fully move it to  something like `/run/gpu-driver/` or something more representative of the desired affect.

~~I would also like if someone specifies a value for `services.xserver.videoDrivers`, that they would also get the gpu libraries mounted automatically instead of needing to do a separate `hardware.opengl-drivers.enable = true;`.~~ This was done in https://github.com/NixOS/nixpkgs/commit/02cef04c8187 

cc @ryantm 

EDIT: roadmap (2.5 years later... lol):

- addOpenGLRunpath -> addDriverRunpath
  - Init addDriverRunpath: #269475
  - Deprecate ~~addOpenGLRunpath~~ `cudaPackages.addDriverRunpath`: https://github.com/NixOS/nixpkgs/pull/281576

- autoAddOpenGLRunpathHook -> autoAddDriverRunpath
  - Init autoAddDriverRunpath: #297212
  - Deprecate cudaPackages.autoAdd{OpenGLRunpathHook,DriverRunpath}:
    -  #300277
    -  #300278
    -  #300287
    -  #300288
    -  #300290
    -  #300292
    -  #300293
    -  #300294
    -  #300295
    -  #300296
    -  #300297
    -  #300298
    -  #300299
    -  #300300
    -  #300301
    -  #300302
    - #300321
- NixOS Module changes: TODO @atemu?

**Comment by jonringer** [comment]
For the transition period ( NixOS 21.11), I think keeping the old `/run/opengl-driver` would help alleviate a lot of the pain, would just like to get the ball rolling away from using `opengl` explicitly

**Comment by jonringer** [comment]
I propose two changes:

- move `/run/opengl-driver/` -> `/run/gpu-driver/`
  - make `/run/opengl-driver/` a symlink to `/run/gpu-driver/` for backwards compatibility of existing derivations
- `services.xserver.videoDrivers` -> `hardware.videoDrivers`
  - add a `(mkRemovedModule services.xserver.videoDrivers hardware.videoDrivers)`

**Comment by jonringer** [comment]
potential future work as well:

- `addOpenGLRunpath` -> `addGPURunpath`
  - Until 21.11 EOL, have it add both `/run/opengl-driver/` and `/run/gpu-driver/`, to avoid system vs package invariance

**Comment by SomeoneSerge** [comment]
Should we, in addition, consider using a libc-versioned directory? Motivated by https://discourse.nixos.org/t/python-dll-import/22594/17

**Comment by jonringer** [comment]
Decided to rename this issue since renaming the underlying path was deemed too risky for potential breakages.

**Comment by Atemu** [comment]
Could you provide some context as to why?

My naive assumption was that we'd have a new path but:

- have both new and legacy path added to rpath via the hook; new path preferred
- provide a legacy symlink pointing at the new path in NixOS

which would be quite trivial.

**Comment by SomeoneSerge** [comment]
TBH, I'm not sure how much value there is to migrating the filesystem path. I suspect what users see in practice is the nixos attribute path

**Comment by Atemu** [comment]
For the NixOS module change, I came up with these terms:

- acceleration API = an API standard which intends to provide hardware-assisted compute acceleration such as OpenGL, Vulkan or CUDA
- driver = userspace library component which implements one or more hardware-based acceleration APIs

***

The usage of the NixOS options API would then look a little like this:

```Nix
{
  hardware.acceleration.opengl.enable = true;
  hardware.drivers.mesa.enable = true;
}
```

Individual drivers would also have a `package` option which is a package selector for the specific package to use aswell as driver-specific settings. (More on the package selector data type when I have a more concrete implementation but it'd allow setting 64/32 bit using a single value.)

Each acceleration API would have a `drivers` option which is an attrset with driver names as keys and package selectors as values. These could then be overridden indivually. The intention behind this is to enable use-cases where e.g. different versions of the same driver are required for different APIs or a specific driver must be disabled for one API but enabled in all others.  
All enabling a driver would do would be to insert the driver's package into the options of all APIs that it implements.

Additionally, accel APIs have a `default` option if the API supports setting one and of course API-specific knobs.

Here's an example of how a non-trivial driver config could look like:

```Nix
{
  hardware.drivers.mesa.enable = true; # Would be default if GUI is enabled
  hardware.drivers.mesa.package = p: p.mesa_42; # Perhpaps possible at some point
  hardware.drivers.amdvlk.enable = true;
  hardware.drivers.amdgpu-pro.enable = true;
  hardware.drivers.cuda.enable = true;
  hardware.drivers.cuda.package = p: p.cudaPackages_12;

  hardware.acceleration.vulkan.enable = true;
  # Ideally you could specify the concrete driver name ("RADV", "radeonsi", "zink"
  # etc.) here but I don't think that'd be possible to implement
  hardware.acceleration.vulkan.default = "mesa"; # AMDVLK is still present but mesa's drivers are preferred
  hardware.acceleration.vulkan.drivers.amdgpu-pro = null; # Disable the vulkan driver; can't ever be used
  # Perhaps instead:
  # hardware.drivers.amdgpu-pro.apis = [ "opencl" ]; # to not insert itself into drivers other than OpenCL?

  hardware.acceleration.opencl.enable = true;
  hardware.acceleration.opencl.default = "amdgpu-pro"; # OpenCL from AMDGPU-PRO
}
```

***

It's currently not possible to know which `.so` implements which driver and all drivers are thrown into the same directory but the NixOS API drafted above requires this information for fine-grained control, so we will have to define an interface here. I've been thinking of defining the `drivers` output to contain all driver bits and subdivide it into driver subdirs like this

    vulkan/lib/libvulkan_radeon.so
    vulkan/share/vulkan/icd.d/radeon_icd.x86_64.json
    vulkan/...
    cuda/...
    opengl/...

Alternatively, I had thought of using multiple outputs; one for each driver. I kinda like that approach more as it generally strikes me as cleaner and has the potential to reduce closure size (`mesa.drivers` is ~200M) but am not sure about potential naming conflicts or other downsides of those.

In light of this, I'd also like to propose to split the global lib dirs into accel API subdirs for clean separation.  
Though as @SomeoneSerge said, the NixOS options are a lot more critical to UX and therefore the first steps. Global path name and other changes are almost entirely tangential and could happen independantly but I'd appreciate if they came after the NixOS options changes such that we can let the knowledge we gained from the NixOS options influence their design.

***

Anyhow, that's my current draft. Let me know what you think.

**Comment by jonringer** [comment]
>My naive assumption was that we'd have a new path but:
>    have both new and legacy path added to rpath via the hook; new path preferred
>    provide a legacy symlink pointing at the new path in NixOS

That was my initial take as well, but there's community projects like nixGL and others who likely have hard coded the path. And there's a potential that we could never fully remove it without breaking someone

**Comment by MattSturgeon** [comment]
> nixGL and others who likely have hard coded the path. And there's a potential that we could never fully remove it without breaking someone

Forgive my ignorance, but wouldn't it be ok to make those kinda breaking changes by deprecating in one release and then removing one or two releases later?

Surely nixos isn't promising to _never_ change paths because someone might be using the old location?

**Comment by SomeoneSerge** [comment]
> That was my initial take as well, but there's community projects like nixGL and others who likely have hard coded the path

nixGL only sets the LD_LIBRARY_PATH? Although in all probability we must break _someone_'s workflow...

>   hardware.drivers.cuda.package = p: p.cudaPackages_12;


Fun fact: cudaPackages don't ship the driver (except for `cuda_compat` for jetsons). All the relevant stuff comes with nvidia_x11 or with the datacenter driver. 

> hardware.acceleration.opencl.default = "amdgpu-pro"

Interesting. Would we somehow have to filter the glvnd/opencl loader/vulkan loader configs that come with the drivers to enforce that the declarative configuration be implemented?

**Comment by Atemu** [comment]
> there's community projects like nixGL and others who likely have hard coded the path. And there's a potential that we could never fully remove it without breaking someone

nixGL appears to be actively maintained. I don't think we need to worry about breaking it as they can simply adapt.

Also, we could simply keep providing the old path in both NixOS and binaries with a preference for the new path and that should work out fine.

> Fun fact: cudaPackages don't ship the driver (except for `cuda_compat` for jetsons). All the relevant stuff comes with nvidia_x11 or with the datacenter driver.

Oh, okay. I'll leave it to you CUDA people to figure that out. I will only be lifting drivers to this interface on a best-effort basis and the rest will keep using their legacy interface with a minor implementation change.

Though if you forsee possible issues you could have mapping your driver to this interface, let me know so that we can design the interface better from the start.

> Interesting. Would we somehow have to filter the glvnd/opencl loader/vulkan loader configs that come with the drivers to enforce that the declarative configuration be implemented?

That or simply write our own. Though I'll only be adding the `default` option where it is feasible; currently, I only know that Vulkan has sane mechanisms for this.

***

Some issues I still need to think about:

- How to handle drivers that only support 64 bit?
  - Will have to filter that somehow
- How to handle APIs that can only have a single exclusive driver?
  - Only have a `driver` option on the API, rather than `drivers`?
  - Have `drivers` but only install the default driver?

**Comment by SomeoneSerge** [comment]
> nixGL

I think NixGL doesn't care about `addDriverRunpath.driverLink`, it probably just exports an `LD_LIBRARY_PATH`?

**Comment by jonringer** [comment]
The original protest against renaming the path: https://github.com/NixOS/rfcs/pull/121#discussion_r998332668

I feel more strongly about the NixOS options being intuitive than the implementation consistent.

**Comment by Atemu** [comment]
I think @infinisil was more concerned with it being placed under `/run/current-system/` rather than some other directory in `/run/` because `/run/current-system/` is very much NixOS-specific while the current `/run/opengl-driver/` is not.

**Comment by jonringer** [comment]
I believe I got all of the packages. Once merged, I should be able to deprecate `cudaPackages.addDriverRunpath`

**Comment by nviets** [comment]
This thread is over my head, but I would like to check it [catboost](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/catboost/default.nix), [lightgbm](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/lightgbm/default.nix), and [python-modules/lightgbm](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/lightgbm/default.nix) need the same? All three have GPU or CUDA support options.

**Comment by jonringer** [comment]
> This thread is over my head, but I would like to check it [catboost](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/catboost/default.nix), [lightgbm](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/lightgbm/default.nix), and [python-modules/lightgbm](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/lightgbm/default.nix) need the same? All three have GPU or CUDA support options.

This is more about deprecating usage of the term `OpenGL`, as it's a bit of a misnomer. I don't see usage of the legacy OpenGL helpers in those packages.

**Comment by jonringer** [comment]
Talked to @Atemu , we concluded that we can close this ticket and have a more "NixOS options" specific ticket to represent that work.

**Comment by jonringer** [comment]
Going to do one last pass on documentation to ensure all references have been updated. I'll close this ticket after that sweep

**Comment by superherointj** [comment]
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/numba/default.nix#L23
`numba` might need an update. I'm not offering a PR yet because I'm out of context. Arrived here from a warning in nixos-rebuild. And I'm still wondering how this is being triggered [still checking].

**Comment by jonringer** [comment]
> I wonder if numba needs an update. I'm not offering a PR because I'm out of context.
Arrived here from a warning in nixos-rebuild. And I'm still wondering how this is being triggered [still investigating].

It should come from the toplevel `pkgs` scope now, so it should never need to default to pulling them out of cudaPackages. I can update the nix expression though.
