### ISSUE TITLE
`isl` tarball hosting on isl.gforge.inria.fr was shut down

### ISSUE THREAD

**Issue by datMaffin** [NixOS/nixpkgs#141819]
### Describe the bug
`isl` tarball hosting on isl.gforge.inria.fr was shut down.
See also: https://groups.google.com/g/isl-development/c/JGaMo2VUu_8

### Steps To Reproduce
There may not yet be any consequences.

### Expected behavior
The source urls in
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/isl/
need to be replaced by some working mirror.

### Notify maintainers
@veehaitch 
@raboof

I hope that I pinged relevant people :wink:

**Comment by veehaitch** [comment]
Thanks for pointing that out! According to the linked discussion, it's not yet decided what's the new "official" mirror. Looks like Homebrew decided to use Sourceforge for now: https://github.com/Homebrew/homebrew-core/pull/86896

**Comment by lincolnauster** [comment]
Hey - I'm running into this issue. Re "there may or may not be any consequences", it seems I can't get the stdenv to build (originating from rust-nightly in the mozilla nixpkgs overlay). Here's the trace:

```
error: 1 dependencies of derivation '/nix/store/ivkypsql6dxd68xwch8lxlnq0p535xzb-isl-0.20.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r78iq205fyrlgbc8j0zy02ly1nsx6b57-gcc-10.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/c4981mrh32m3qfj45h3rjfhk7wxydqrv-bootstrap-stage4-gcc-wrapper-10.3.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3mr1jfhkg67f2jasb9i56k18wvac980h-perl-5.34.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bqfy8ydlxs0xhzqmy7rc3zjw60vwab6j-stdenv-linux.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ilv0k727pwagf2sq0zv4mfd8dzb1v6yd-stdenv-linux.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7x6z4lndsf2bdmqk8risxixp2gpk5581-channel-rust-nightly.toml.drv' failed to build
```

I'm a bit confused about exactly what is having issues where, but it looks like gcc is relying on isl.gforge.inria.fr, which is ... more than a slight problem, if I'm interpreting this correctly.

**Comment by datMaffin** [comment]
> 
> I'm a bit confused about exactly what is having issues where, but it looks like gcc is relying on isl.gforge.inria.fr, which is ... more than a slight problem, if I'm interpreting this correctly.
> 

Yeah. An absolute ton of software depends on isl.
