### ISSUE TITLE
Request to Remove GraalVM8

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#141805]
GraalVM8 requires `mercurial_4` which requires `hg-git` which is broken in Python2.
As I'm attempting to clean-up Python 2 packages at #141794 .
Would be nice having it removed as it seems to be no longer used. And it would unblock removing `mercurial_4` and `hg-git`.

@hlolli @thiagokokada

**Comment by thiagokokada** [comment]
From a quick grep:

``` shellsession
$ rg 'graalvm8'
pkgs/top-level/all-packages.nix
12091:  }) mx jvmci8 graalvm8;
12097:  graalvm8-ce = graalvmCEPackages.graalvm8-ce;
12101:    graalvm8-ee

pkgs/development/interpreters/python/graalpython/default.nix
3:, graalvm8
13:    sourceVersion = graalvm8.version;
21:in lib.extendDerivation true passthru graalvm8

pkgs/development/compilers/graalvm/enterprise-edition.nix
181:  graalvm8-ee  = common  "8";

pkgs/development/compilers/graalvm/default.nix
358:  graalvm8 = 	stdenv.mkDerivation rec {
530:    passthru.home = graalvm8;

pkgs/development/compilers/graalvm/community-edition/default.nix
10:  graalvm8-ce = mkGraal rec {
```

The only package that depends on `graalvm8` directly seems to be `graalpython`. Both packages are also provided by `graalvm8-ce`. `graalvm11` doesn't seem to be available.

Also, the last commit from `graalvm8` derivation that was not a treewide refactoring was this one: thttps://github.com/NixOS/nixpkgs/commit/78b34b5e5bd8e36f67a6fcd0254b174423c2ebdd#diff-51b361d58d5e33cde96ee05747ddc5a7713c0b09ecdc9f9b5b8a712cb59f4cb4. From Jan 18, 2020.

I think it is pretty safe to assume that `graalvm8-ce` can suplement all usages of `graalvm8`, and it is also much more up-to-date.
