### ISSUE TITLE
NixOS user sockets: install section missing

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#14195]
At 16.09pre78848.9549257 (Flounder)

The config:
```
    systemd.user.sockets.ipython = {
      wantedBy = [ "basic.target" ];
      listenStreams = [ "127.0.0.1:8888" ];
    };
```

This should generate a unit that have the WantedBy command so that it can be activated.

This is what's generated:

```
joelmo ~ $ systemctl --user cat ipython.socket 
# /nix/store/r9a7f5xajzph9iq685s7gj6wgdrzmjpx-unit-ipython.socket/ipython.socket
[Unit]

[Socket]

ListenStream=127.0.0.1:8888
```

The unit will get activated anyway and linked. I can check that under `/run/booted-system/etc/systemd/user/basic.target.wants` IPython exists. But sometimes the unit will fail to start. The install section is mostly wanted for debugging reasons.

**Comment by joachifm** [comment]
I think you should use `sockets.target`. Other than that I fail to understand what you are asking for, can you clarify? How would the install section help you?

**Comment by joelmo** [comment]
That would indicate the unit is linked to the wanted directories. Maybe it's not very helpful because one could read the nix config files or check by nix-repl. But system sockets get this Install section see nix-daemon:

```
joelmo ~/Documents/nixpkgs systemd-units $ systemctl cat nix-daemon.socket 
# /nix/store/cza0kkcp7qwwr4qgdlm4xkaschir0xl8-nix-1.11.2/lib/systemd/system/nix-daemon.socket
[Unit]
Description=Nix Daemon Socket
Before=multi-user.target
RequiresMountsFor=/nix/store
ConditionPathIsReadWrite=/nix/var/nix/daemon-socket

[Socket]
ListenStream=/nix/var/nix/daemon-socket/socket

[Install]
WantedBy=sockets.target
```

**Comment by fpletz** [comment]
Maybe the reason for this behaviour is that `basic.target` is only available in the system session and not in the user session?

**Comment by joelmo** [comment]
Such targets are enabled but, the map to targets function is not enabled for user units but this seems to not have any difference (see this https://github.com/joelmo/nixpkgs/commit/d93930db901cdb549adc348f5a3d09ccbe785f6a). I get the same problem sometimes the unit will enter a failed state. And all these targets are available without the patch:

```
  basic.target                                         loaded active active  Basic System
  default.target                                       loaded active active  Default
  paths.target                                         loaded active active  Paths
  sockets.target                                       loaded active active  Sockets
  timers.target                                        loaded active active  Timers

```

Also using `sockets.target` made no difference. basic includes sockets timers and paths targets.

**Comment by joelmo** [comment]
At current version (16.09pre82105.7465bcd) I don't have this issue with sockets anymore. Install section is still missing, but this is maybe not considered as a bug.
