### ISSUE TITLE
programs.neovim.configure doesn't work

### ISSUE THREAD

**Issue by piotrKantor** [NixOS/nixpkgs#141982]
### Describe the bug
Configuration mentioned in documentation under following link doesn't work.
[the link](https://search.nixos.org/options?channel=21.05&show=programs.neovim.configure&from=0&size=50&sort=relevance&type=packages&query=nvim)

It looks like there is something wrong with escaping in line 63 of [following code](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/nixos/modules/programs/neovim.nix)

### Steps To Reproduce
1. Add following to your `configuration.nix`
```
programs.neovim.configure = {
    customRC = $'''
    set nu
    " here your custom configuration goes!
    $''';
    packages.myVimPackage = with pkgs.vimPlugins; {
      # loaded on launch
      start = [ fugitive ];
      # manually loadable by calling `:packadd $plugin-name`
      opt = [ ];
    };
  };
```
2. `nixos-rebuild switch`
3. Change `configuration.nix` so that neovim configuration looks as follows:
```
programs.neovim.configure = {
    customRC = ''
    set nu
    " here your custom configuration goes!
    '';
    packages.myVimPackage = with pkgs.vimPlugins; {
      # loaded on launch
      start = [ fugitive ];
      # manually loadable by calling `:packadd $plugin-name`
      opt = [ ];
    };
  };
```
4. `nixos-rebuild switch`
*Now it would rebuild*
5. Open `nvim`, and see that `set nu`didn't work

### Expected behavior
In given example, seeing the line numbers in neovim.

### Notify maintainers
@teto

**Comment by teto** [comment]
code looks ok. Do you have another neovim installed by home-manager by any chance ? Run
`cat $(readlink -f $(which nvim))` , see if neovim is wrapped with a `-u FILE` call and check that FILE contains `set nu`

**Comment by colinramsay** [comment]
I see this same issue but I don't use neovim. It seems to be a problem with tracker-3.2.0.

**Comment by teto** [comment]
@piotrKantor do you still have the issue ?  If you can add a failing test to pkgs/applications/editors/neovim/tests.nix  I can  have a look otherwise maybe we can close
