### ISSUE TITLE
Go doesn't install on darwin (llvm related error about 'aranges')

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#14208]
* Kernel: Darwin cmmbp.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
* System: OS X 10.11.4 (15E65)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre-git"

**Issue**: Go builds, but doesn't pass necessary tests.

Full log: https://gist.githubusercontent.com/anonymous/43ecd1df74291261fca5/raw/60950945f6d5a8dfde5121096da542577303eb1e/golog.txt

Relevant:
```
--- FAIL: TestDwarfAranges (0.59s)
	runtime-lldb_test.go:218: Missing aranges section
FAIL
FAIL	runtime	17.123s
```

Relevant: https://golang.org/src/runtime/runtime-lldb_test.go#L186

**Comment by houqp** [comment]
I've got hit by the same issue.

**Comment by nathan7** [comment]
I noticed this while packaging Go 1.6, but I haven't got a clue how I'd fix this.

**Comment by danielpcox** [comment]
✋ I see it too.

**Comment by danielpcox** [comment]
It's TestDwarfAranges that's failing,
https://github.com/golang/go/blob/release-branch.go1.6/src/runtime/runtime-lldb_test.go#L215-L220
and it seems that the binary output by `go build` doesn't contain this "__debug_aranges" section of the Mach-O binary.
