### ISSUE TITLE
nicotine-plus: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by aopom** [NixOS/nixpkgs#142014]
### Describe the bug
Whenever I open a file chooser dialog in Nicotine+, it crashes with this error:
```
(org.nicotine_plus.Nicotine:567058): GLib-GIO-ERROR **: 18:59:22.961: No GSettings schemas are installed on the system
fish: Job 1, 'nicotine-plus' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### Steps To Reproduce
1. An X environment without a DE
2. Install and run `nixpkgs.nicotine-plus`
3. Open a file dialog

### Additional context

I saw a similar issue on Chromium: #26560

Maintainers (thanks!): @ehmry @klntsky

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.68, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre319271.31ffc50c571"`
 - channels(ao): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by udf** [comment]
It looks like the glib setup hook isn't setting `$GSETTINGS_SCHEMAS_PATH` for some reason (maybe it's not running?)

The wrapped file looks something like

```bash
#! /nix/store/a54wrar1jym1d8yvlijq0l2gghmy8szz-bash-5.1-p12/bin/bash -e
export XDG_DATA_DIRS='/nix/store/gkx1aqa5ld1lxrkv9c5j7f8k7npzv9vp-nicotine-plus-3.1.1/share'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
export GI_TYPELIB_PATH=<removed for brevity>
exec -a "$0" "/nix/store/gkx1aqa5ld1lxrkv9c5j7f8k7npzv9vp-nicotine-plus-3.1.1/bin/.nicotine-plus-wrapped"  "$@"
```

So the packages `/share` is being added to `$XDG_DATA_DIRS`, which happens here:
https://github.com/NixOS/nixpkgs/blob/384d9fe3666cfb2bf87a3de54a17e443edceaf80/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L21-L28

Right above it, `$GSETTINGS_SCHEMAS_PATH` gets added to `$XDG_DATA_DIRS` if it's present, but that doesn't show in the wrapper, so the variable is not getting set.
