### ISSUE TITLE
github: *.nix files have no syntax highlighting anymore

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#14213]
I'm sure it worked less than 24h ago. Perhaps it's just a temporary problem?

**Comment by domenkozar** [comment]
```nix

stdenv.mkDerivation {
  name = "foo";
}
```

**Comment by domenkozar** [comment]
Might be: https://github.com/github/linguist/commit/aa6b88197123926c26b16a6a17ea5846b3917fc9

**Comment by domenkozar** [comment]
Aha see https://github.com/github/linguist/commit/07096f84f5a2cd96efbb39995405442fea178d48

**Comment by globin** [comment]
https://github.com/github/linguist/issues/2885

**Comment by domenkozar** [comment]
Their platform sucks so much even **they** are unable to use it correctly so that maintainers would get an email notification in time.

**Comment by copumpkin** [comment]
This is thankfully resolved :smile:
