### ISSUE TITLE
Package request: lldap

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#142275]
**Project description**
An lightweight authentication server that provides an opinionated, simplified LDAP interface for authentication: clients that can only speak LDAP protocol can talk to it and use it as an authentication server.

**Metadata**

* homepage URL: https://github.com/nitnelave/lldap
* source URL: https://github.com/nitnelave/lldap
* license: [GPL-3.0](https://github.com/nitnelave/lldap/blob/main/LICENSE)
* platforms: unix

**Comment by aanderse** [comment]
Here is what I came up with so far (with big help from @alyssais :heart:): https://github.com/NixOS/nixpkgs/compare/master...aanderse:lldap?expand=1

**Comment by Sohalt** [comment]
Still relevant

**Comment by IndeedNotJames** [comment]
I gave it a try in #227916 in case someone would like to take a look at it :)
