### ISSUE TITLE
Plasma hard-kills Brave browser on session end

### ISSUE THREAD

**Issue by cptMikky** [NixOS/nixpkgs#142263]
### Describe the bug
When Plasma desktop session ends with Brave browser running, the browser gets hard-killed to the point where in a new session when the browser is started it always complains about a "crash" and one needs to "restore" it.

### Steps To Reproduce
1. Start a KDE Plasma session
2. Start Brave browser
3. Log out / shut down / reboot
4. Log back in to any graphical session
5. Start Brave browser

### Expected behavior
On Plasma session termination Brave should shut down gracefully saving it's state and session (Brave session, i.e. open tabs, etc.) and after a new login and Brave start, the browser should "start where you left off" (if that is the intended behavior) and should *not* produce any messages about Brave "crashes".

Not sure if this is a Brave issue or KDE Plasma issue but with XFCE I never had this problem.

I noticed that on logout (reboot, etc.) the Brave windows stays open for an extended period of time (about 10s+) while other windows are closed. It is always killed eventually.

There is some kind of KDE browser integration which probably should work with  Brave (Brave being basically Chromium) but the integration works funnily - it is installed (via declarative nix) but the Brave plugin doesn't connect. However, Plasma has some integration nonetheless - namely media control. I have absolutely no idea if this is relevant or not.

### Notify maintainers

Brave maintainers: @rht @uskudnik @JeffLabonte @nasirhm 
Plasma Desktop maintainers: @ttuegel @nyanloutre 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.8-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre323695.9aeeb7574fb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixos modules affected by the problem
module:
  - pkgs.brave
  - pkgs.libsForQt5.plasma-desktop
```

**Comment by rht** [comment]
Does this also happen on Chromium? Not sure, since you didn't mention it.

**Comment by cptMikky** [comment]
I actually don't use Plasma anymore but iirc the last time I tried it the issue was gone (~2 months ago).
