### ISSUE TITLE
[discussion] VSCodium Release Number

### ISSUE THREAD

**Issue by daiyam** [NixOS/nixpkgs#142361]
Hi,

I'm a maintainer of the app VSCodium.
I'm planning to add a release number to its version tag. `1.61.2` would become `1.61.2+21293`.
It would be used to release hotfixes instead of waiting new release of VSCode...

I would like to know if the new version tag can become an issue for the nix package?
@samuela @happysalada Could I get your feedback? Thx

**Comment by jbedo** [comment]
It might make version matching outside of nixpkgs more difficult, see for example https://repology.org/project/vscode/versions.

There's also an RFC re. version normalisation here: https://github.com/NixOS/rfcs/pull/107

**Comment by daiyam** [comment]
Hi, I'm moving forward with the release number. Today, first release: `1.70.1.22228`

The release number will help in case we found an issue specific to VSCodium. We wont have to wait for an update from VSCode.
It will also me to move forward with the Insiders version.
