### ISSUE TITLE
[21.05] Backport request for patchelf 0.13

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#142325]
### Describe the bug

I'm currently cross-compiling software for PowerPC64 using nixpkgs' `nixos-21.05` branch for stability reason. Currently patchelf fails to shrink the rpath of executable and libraries for ppc64, but that was fixed with NixOS/patchelf#269. Since this makes program and libraries unusable without setting the proper `$LD_LIBRARY_PATH`, I thought it would be acceptable to request a backport for the 21.05 branch.

### Steps To Reproduce
1. Using this flake:

```nix
{
  description = "A very basic flake";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-21.05";

  outputs = { self, nixpkgs }: {
    defaultPackage.x86_64-linux =
      let
        pkgs = import nixpkgs {
          localSystem.config = "x86_64-linux";
          crossSystem = {
            config = "powerpc64-unknown-linux-gnueabihf";
            gcc = {
              cpu = "e6500";
            };
          };
          config.allowUnsupportedSystem = true;
        };
      in pkgs.hello;
  };
}
```

2. Compile with `nix build -L` **Warning**: this builds gcc
3. Observe empty rpath with `readelf -d ./result/bin/hello`.

### Expected behavior

The `rpath` of binaries is properly set for all architectures.

### Notify maintainers

@edolstra 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.70, NixOS, 21.05.20211019.8fe3b97 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"nixos-21.05.3532.aff647e2704"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - patchelf
# a list of nixos modules affected by the problem
module:
```

**Comment by bjornfor** [comment]
Look like the backport happened (above). Closing.
