### ISSUE TITLE
rust: add support for `wasm32-unknown-unknown`

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#142389]
Running [`wasm-pack build --target web`](https://github.com/nitnelave/lldap/blob/main/app/build.sh) errors out:
```
[INFO]: Checking for the Wasm target...
Error: wasm32-unknown-unknown target not found in sysroot: "/nix/store/sw7kr9clh3y3rpghgh50j023nbnwqz9i-rustc-1.55.0"

Used rustc from the following path: "/nix/store/sw7kr9clh3y3rpghgh50j023nbnwqz9i-rustc-1.55.0/bin/rustc"
It looks like Rustup is not being used. For non-Rustup setups, the wasm32-unknown-unknown target needs to be installed manually. See https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html on how to do this.
```

From `Nix/NixOS` on `matrix`:
> Alyssa Ross
> aanderse: it looks like we don't actually support wasm32-unknown-unknown in Nixpkgs, from what I can tell, only wasm32-unknown-wasi.

Any and all help is much appreciated.

Motivation: https://github.com/NixOS/nixpkgs/issues/142275

ping @alyssais @K900

**Comment by figsoda** [comment]
might be a duplicate of #89426

**Comment by aanderse** [comment]
ping @Ericson2314 in case. I'm really hoping this  issue can be fixed at some point. Thank you so much to everyone who has put effort in up to this point ❤️

**Comment by kevincox** [comment]
I'm going to close in favour of https://github.com/NixOS/nixpkgs/issues/89426 as they seem to both be about this target.
