### ISSUE TITLE
ejabberd 21.12

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#142465]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `nixpkgs.ejabberd`

current version: 21.04 (in unstable)
desired version: 21.12

###### Notify maintainers

maintainers:

@svanderburg
@abbradar

###### Note for maintainers

Please tag this issue in your PR.

**Comment by genofire** [comment]
Ping @abbradar and @svanderburg - one release already not packaged

**Comment by NickCao** [comment]
https://github.com/NixOS/nixpkgs/blob/60c84c8841fb3eef80f28e942a52b601625ed0c0/pkgs/servers/xmpp/ejabberd/default.nix#L18
