### ISSUE TITLE
pkgsStatic.systemd

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#142472]
It would be nice to have a static build of systemd, since many things depend on it.

Upstream doesn't support static linking of binaries, and also doesn't allow to disable building of shared libraries in the build system.
A WIP version with patches and `sed`s to fix this is available here:
https://github.com/yu-re-ka/nixpkgs/commit/fabe8b799ffa6c663a6927dac1b44605d4001623

However, there is one more technical obstacle. The symbol names from different dependencies conflict with eachother. `util-linux`'s `libmount.a` and `kmod`'s `libkmod.a` both have a `mkdir_p` symbol.
If anyone is aware of tooling to prefix all hidden/non-exported symbols in a static library, that would be really useful.

CC @alyssais

**Comment by 06kellyjac** [comment]
Prefixing all the symbols seems to be highly discouraged upstream. The best solution would be static linkers supporting namespacing

> If you want to make static linking work, then please work with the linker people to add a way to add namespacing to static linking. But we are simply not going to rename all our internal symbols.

https://github.com/systemd/systemd/issues/20600#issuecomment-912338965
