### ISSUE TITLE
sc-controller: LIBUSB_ERROR_ACCESS [-3]

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#142473]
![image](https://user-images.githubusercontent.com/11302521/138292472-161037bc-a5c2-4ef5-93f8-d283755a1204.png)

There was an error with enabling emulation: **Failed to open USB device: LIBUSB_ERROR_ACCESS [-3]**
You don't have access to controller device

Consult your distribution manual, try installing Steam packge or [install required udev rules manually](https://wiki.archlinux.org/index.php/Gamepad#Steam_Controller_not_pairing).

## Issue description

Emulation of the controller doesn't work

### Steps to reproduce
1. run `sc-controller` as non-root user
2. Enable emulation in the menu
![image](https://user-images.githubusercontent.com/11302521/138292710-64aff9c0-a4a9-4c95-b0f4-0149212148b5.png)
3. Expect the highlighted error

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[kreyren@leonid:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.05.3208.8dd8bd8be74 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixos-21.05.3208.8dd8bd8be74"`
 - channels(kreyren): `"home-manager-21.05, master, nixos-21.05.3801.83667ff60a8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

## Additional informations

Running as root user doesn't trigger the warning and the emulation works.

---

CC Maintainers: @orivej @rnhmjoj

**Comment by rnhmjoj** [comment]
Closing since I think I provided a fix.

**Comment by Kreyren** [comment]
Entry added in https://nixos.wiki/wiki/Packages/sc-controller
