### ISSUE TITLE
zsh not initialized correctly (ssh logins)

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#14256]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`) Linux lapole 3.18.25 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 15.09.952.55b0326 (Dingo)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.10
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 16.03pre75806.77f8f35

## Describe your issue here
I installed zsh-5.2 from nixpkgs channel to get away from a 5.0.8 bug. After I changed my login-shell to 5.2, ssh logins were no longer functional. Ie. PATH wasn't fully initialized.

Reverting to 5.0.8 fixed the problem.

I'm not sure why there's a difference between regular login shells and ssh though. 

Running `strings /nix/store/*zsh-5.2/bin/zsh` yields:

    /etc/profile
    .profile`
    /etc/suid_profile
    $out/etc/zprofile
    .zprofile
    profile signal

For 5.0.8 I get the expected /nix/store/... path instead of the strange $out path.

The line with $out seems wrong.. Checking the commit log I find https://github.com/NixOS/nixpkgs/commit/97332d30f62b149aa81a63f798e7e53825e12663

Dropping into nix-shell for zsh-5.2, setting `set -x` and manually running `configurePhase`I get:

    + ./configure --prefix=/nix/store/icd9hwav49fign863szpk4s3imn5dm2b-zsh-5.2 <snip> 
    --enable-multibyte '--enable-zprofile=$out/etc/zprofile' <snip>

So it seems to me that variables in `configureFlags` is not expanded leading to zprofile not being run. It could be something else of course (not everything seems to add up without more investigating), but the $out thing seems wrong either way.

**Comment by fpletz** [comment]
cc @calbrecht

**Comment by fpletz** [comment]
This is fixed by the merge of #14343. Cherry-picked to `release-16.03`.
