### ISSUE TITLE
Package request: VMware Player

### ISSUE THREAD

**Issue by simonkampe** [NixOS/nixpkgs#142553]
**Project description**
VMware Player is an easy (and industry standard in some industries) way to run virtual machines. Contrary to VMware Workstation, Player does not require a license.

**Metadata**

* homepage URL: https://www.vmware.com/products/workstation-player.html
* source URL: https://download3.vmware.com/software/player/file/VMware-Player-Full-16.2.0-18760230.x86_64.bundle
* license: unfree
* platforms: x86_64-linux

**Comment by JalilArfaoui** [comment]
Would love to see that !

**Comment by JalilArfaoui** [comment]
Some work has been done here : https://discourse.nixos.org/t/porting-vmware-workstation-to-nixos/5122/4

**Comment by JalilArfaoui** [comment]
There is also this attempt : https://github.com/simonkampe/nixpkgs/tree/submit/vmware-player/pkgs/applications/virtualization/vmware-player

**Comment by JalilArfaoui** [comment]
Maybe @teto @SuperSandro2000 @jerith666 @lovesegfault can help ?

**Comment by teto** [comment]
nope I use qemu :)

**Comment by JalilArfaoui** [comment]
> nope I use qemu :)

I’m searching for any way to emulate a Windows with decent GPU virtualization / 3D Acceleration … Is qemu capable of such @teto  ?

**Comment by teto** [comment]
I dont use windows personally or professionnaly but I am confident qemu can do that or virtualbox if you are not required to use the vmware player. qemu supports .vmdk files too (or at least, it's possible to convert those to a qemu compatible format, aka qcow

**Comment by lovesegfault** [comment]
Why was I pinged in this?

**Comment by JalilArfaoui** [comment]
Sorry @lovesegfault ! I thought you’ve worked on virtualization !

**Comment by JalilArfaoui** [comment]
> I dont use windows personally or professionnaly but I am confident qemu can do that or virtualbox if you are not required to use the vmware player. qemu supports .vmdk files too (or at least, it's possible to convert those to a qemu compatible format, aka qcow

No @teto , VirtualBox is not able to make 3D Graphics work properly under Windows 10, either lagging terribly, either crashing. I’ve tried Gnome Boxes too, but no GPU is even detected … I’ll give qemu a try !

**Comment by jerith666** [comment]
I have also tried VirtualBox for gaming (minecraft) and been disappointed with the performance.  I don't have any particular expertise that would help with packaging VMWare Player though.  :-(

**Comment by simonkampe** [comment]
I opened this because at work we use VMs to keep the IDEs separated (industrial automation, PLCs etc.). We also share the VMs between us so I cannot really switch from vmware without unwanted overhead. It would be nice to be able to main NixOS on the work lappy though :) I still haven't figured out a way to run it properly.

**Comment by simonkampe** [comment]
This is fixed in #169966
