### ISSUE TITLE
Add a warning to cordless package to avoid bans on Discord

### ISSUE THREAD

**Issue by bryanasdev000** [NixOS/nixpkgs#142530]
### Describe the bug

Per warning of the cordless maker on https://github.com/Bios-Marcel/cordless:

```
WARNING: Third party clients are discouraged and against the Discord TOS. There have already been cordless users that got banned, including me (Bios-Marcel, the maker and maintainer)
```

### Steps To Reproduce

Use `cordless`.

### Expected behavior

N/A

### Screenshots

N/A

### Additional context

N/A

### Notify maintainers

@colemickens 

### Metadata

N/A

Maintainer information:

N/A

**Comment by ratsclub** [comment]
I'm looking after this too. I think adding the `broken` meta tag would be an alternative too!

**Comment by legendofmiracles** [comment]
Why should it be removed? We're not breaking TOS by packaging it in nixpkgs.

I agree that we should somehow warn the user, but in general that's their responsibility

**Comment by bryanasdev000** [comment]
> Why should it be removed? We're not breaking TOS by packaging it in nixpkgs.
> 
> I agree that we should somehow warn the user, but in general that's their responsibility

Renamed. And agree.
