### ISSUE TITLE
nodejs doesn't cross-compile to non-executable hostPlatform

### ISSUE THREAD

**Issue by dwf** [NixOS/nixpkgs#142651]
### Describe the bug
Cross-compiling nodejs for a hostPlatform whose binaries can't be executed on the buildPlatform fails.

### Steps To Reproduce
1. `nix-build '<nixpkgs>' -A pkgsCross.raspberryPi.nodejs_latest`

Also fails with `nodejs-slim`, `nodejs-12_x`, `nodejs-14_x`, etc.

### Expected behavior
The package to be built successfully.

### Additional context

The problem seems to be that binaries, notably `out/Release/bytecode_builtins_list_generator`, need to be built with the build environment toolchain, not the host toolchain. Node's build process allows specification of the location of the necessary build compilers via environment variables (`AR_host`, `CXX_host`, `CC_host`, `LINK_host`, `CXXFLAGS_host` and `LDFLAGS_host` are mentioned in one of the links below).

nodejs/node#32717 seems relevant, as does nodejs/node#24317. The latter mentions [buildroot](http://www.buildroot.org/) getting this right, [here's what they do](https://github.com/buildroot/buildroot/blob/master/package/nodejs/nodejs.mk).

### Notify maintainers

@goibhniu @gilligan @cko @marsam

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@nixos-builder:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.74, NixOS, 21.05.3892.70904d4a992 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3892.70904d4a992, unstable-21.11pre323695.9aeeb7574fb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:

# a list of nixos modules affected by the problem
module:
```

**Comment by dwf** [comment]
Adding additional context to this: I've successfully been able to build by using an i686 build platform and the following overlay:

```
    nodejs-cross = super.nodejs-14_x.overrideAttrs (old: {
      preConfigure = ''
         export CC_host="${self.stdenv.buildPlatform.config}-gcc"
         export CXX_host="${self.stdenv.buildPlatform.config}-g++"
         export LINK_host="${self.stdenv.buildPlatform.config}-g++ -Wl,-lstdc++ -Wl,-lm -B${self.buildPackages.stdenv.glibc}/lib"
      '';
      depsBuildBuild = with self.buildPackages; [ stdenv.cc stdenv.glibc libuv zlib openssl ];
    });
```

I suspect this isn't quite the right fix though for a number of reasons.

I also wasn't able to find a way to cross-compile from x86-64 to armv6l. It seems one needs a toolchain with 32-bit support, which would suggest a multiStdenv for the buildPlatform but not the hostPlatform, and I'm not sure how to accomplish that.

**Comment by Hjdskes** [comment]
I am also running into this (the linked Discourse thread is mine). It looks like buildroot fixes this problem by compiling the build tools for the build platform first, and then using those binaries when compiling for the target platform (https://github.com/buildroot/buildroot/blob/master/package/nodejs/nodejs.mk#L105)

Do you have time to look at this, @goibhniu @gilligan @cko @marsam? I am willing to give this a shot but I'll need some pointers to get started...

**Comment by dwf** [comment]
The workaround I found is to replace `pkgsCross` with `pkgsi686Linux.pkgsCross`, so that you use x86-32 as the build platform. Not ideal as it requires installing a whole heck of a lot of 32-bit dependencies, but it's a testament to Nix that it works at all.
