### ISSUE TITLE
feh: Manpage unavailable

### ISSUE THREAD

**Issue by nbraud** [NixOS/nixpkgs#142671]
### Describe the bug

The derivation `feh` doesn't include the relevant manpage, while the application itself refers to the manpage as the only source of documentation.

### Steps To Reproduce

```console
$ nix-shell -p feh
$ feh --help
See 'man feh'

$ man feh
No manual entry for feh
```

### Expected behavior

The manpage ought to be available.

### Notify maintainers

@viric @willibutz @globin @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.69, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(nicoo): `"home-manager"`
 - channels(root): `"nixos-21.11pre319562.c21ba4f7bb4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - feh
# a list of nixos modules affected by the problem
module:
```

**Comment by KAction** [comment]
I would argue that separation of `man` and `out` is a very good thing -- you get only what you want.
Probably solution to UX issue would be to have `nix-shell -A foo` to implicitly add all (or configurable list?) of other outputs to the list.

**Comment by Artturin** [comment]
closing in favor of https://github.com/NixOS/nixpkgs/issues/25483
