### ISSUE TITLE
package glu-9.0.0 (mesa_glu) provides broken pkg-config file

### ISSUE THREAD

**Issue by Adjective-Object** [NixOS/nixpkgs#14260]
pkg-config does not give correct cflags for compiling against glu.

# System

* Kernel: 4.4.5
* System: 16.09pre78848.9549257 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre78848.9549257"

### Expected result
pkg-config will include the include directory of glu-9.0.0, i.e.
``` .bash
❯ pkg-config --cflags glu
-I/nix/store/yc12r8xv6iv9zm3z1riw24csbhv5sl7h-glu-9.0.0/include -I/nix/store/130nf1yrgs40qpm5xfpl56hhjbzalxmy-mesa-noglu-11.1.1/include
```

### Actual result
pkg-config does not include the include directory of glu-9.0.0
``` .bash
❯ pkg-config --cflags glu
-I/nix/store/130nf1yrgs40qpm5xfpl56hhjbzalxmy-mesa-noglu-11.1.1/include
```

### Steps to reproduce
``` .bash
❯ nix-shell -p mesa_glu pkgconfig
❯ pkg-config --cflags glu
```

### Proposed Solution
A cursory look at the [freedesktop ftp site](ftp://ftp.freedesktop.org/pub/mesa/glu/) 
suggests that there has not been a release of glu since 9.0.0 (the current in nixpkgs),
which has the above issue.

This is a problem with glu itself, not the nix pakaging. However, given the long gaps between releases of glu and the inherit risk of tracking the head of a git repo for something as essential as an OpenGL implementation, I would think that a small patch would be more appropriate until the next stable release of glu.

As a temporary fix, the following line can be added to the end of `${mesa_glu}/lib/pkgconfig/glu.pc`
```
Cflags: -I${includedir}
```

**Comment by vcunat** [comment]
Yes, thanks. Most systems wouldn't notice due to all being in the same directory.
