### ISSUE TITLE
Directories created from fetchFromGitHub are not writable

### ISSUE THREAD

**Issue by HittingSmoke** [NixOS/nixpkgs#14277]
## Basic info

* Kernel: Linux nixweb 3.18.26 #1-NixOS
* System: 15.09.1177.f8a795e (Dingo)
* Nix version: 1.10
* Nixpkgs version: 15.09.1177.f8a795e

## Describe your issue here

I am trying to modify the expression for Nginx at /pkgs/servers/http/nginx/default.nix to copmile with Google's [ngx_pagespeed module](https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source#build-instructions).

As you can see in the build instructions in that link, part of the build process is downloading the pagespeed optimization library (psol) and extracting it into the module's source directory. I can not find a way to use a Nix expression to write to a downloaded module directory.

### Expected result

Using the following code in the Nix expression:

```
# Get the ngx_pagespeed module source from GitHub
nps-ext = fetchFromGitHub {
  owner = "pagespeed";
  repo = "ngx_pagespeed";
  rev = "v1.10.33.7-beta";
  sha256 = "0xsvdrhgizn36qgpc7440s8nyjn0yn1w4da8lzcxqz723ji98msy";
};

# Get the psol library from Google
psol = fetchurl {
  url = https://dl.google.com/dl/page-speed/psol/1.10.33.6.tar.gz;
  sha256 = "0j9igiswrg8y9xin6xm37xdgcyhz9h6d7mdr2dp96c0an55r7kgm";
};

preConfigure = ''
  # Extract the psol module to the ngx_pagespeed module directory
  tar -xzvf ${psol} -C ${nps-ext}
'';
```

Nix should extract 1.10.33.6.tar.gz to the directory containing the ngx_pagespeed source that was fetched from Github before configuring and compiling Nginx. Then it should compile Nginx with the pagespeed module.

### Actual result

I've tried using tar to extract directly, I've tried extracting the psol archive and using mv to move it into the pagespeed directory. I've tried it in the preConfigure and postUnpack hooks. I've tried using chmod o+w on the pagespeed source directory. In every instance the package fails with a permission denied error when trying to create a directory inside the pagespeed source directory created by the fetchFromGitHub function. This includes when running nix-env with sudo.

### Steps to reproduce

In a Nix expression, use fetchFromGitHub to get source code from a repository.

Try to write to the directory containing the fetched source code.

Run `nix-env -i package -f /path/to/repo/fork/default.nix`

Here is the Nix expression I'm currently testing this with: http://pastebin.com/zVdx0E9K

The modified lines are 19-29, 97, and 131 being the downloading, the --add-module, and the extracting respectively.

**Comment by domenkozar** [comment]
`fetchFromGitHub`, `fetchurl` both use `derivation` primitive, which creates read-only directories. You have to create a new derivation and copy both sources there.

**Comment by HittingSmoke** [comment]
@domenkozar is there a reason for that from a design context? In the manual the option `dontMakeSourcesWritable` says it is set to 0 by default to not cause problems. It seems like forcing anything fetched from GitHub or any other URL outside of the context of `src` as read only would just cause problems, especially with no way to override it requiring an ugly workaround.

For now I've just copied the ngx_pagespeed source to another directory and got it compiling fine. It really just feels like an ugly and pointless hack though. If I understand derivations properly, creating a new one just to copy one folder into another sounds like adding a ton of unnecessary code for a problem that I've solved with a two-line hack consisting of creating a new folder and copying the contents of an already downloaded GitHub repo to it.

My working test expression really now only has two extra lines:

'''
preConfigure = ''
  mkdir psolshim
  cp -r ${nps-ext}/* psolshim/
  tar -xzvf ${psol} -C psolshim
'';
'''

At best this feels like it should be considered a bug. At worst a big design flaw. Maybe I'm missing something because of how new I am to Nix expressions, but it seems like a major violation of DRY in any context.

**Comment by joachifm** [comment]
The Nix store is immutable: outputs, once created, must never change. What you are proposing would violate that.

**Comment by HittingSmoke** [comment]
@joachifm But why are they considered immutable at that point in the build process? The sources are not, and in this context the modules are just _more sources_ that haven't been used yet. Like I said before, `dontMakeSourcesWritable` is set to 0 by default for a reason. If a package fetched from GitHub is for a module it's just another part of the package source that hasn't been compiled yet.

If there's a _technical limitation_ that requires this, that's one thing.  But saying that the Nix store must never change and this violates that doesn't make sense to me when we're talking about pre-build source code. I'm sure it must not change after the package build, but saying it "must never change" even before the configure phase sounds very wrong to me.

**Comment by vcunat** [comment]
> At best this feels like it should be considered a bug. At worst a big design flaw. Maybe I'm missing something because of how new I am to Nix expressions, but it seems like a major violation of DRY in any context.

@HittingSmoke: nix store contents doesn't change for derivations that have finished. (fetch* are finished and fixed before building their dependants starts.) It's at the root of nix design, a feature, not a flaw. There are many advantages implied that we utilize. Perhaps the immutability isn't very convenient in the exceptional case of `fetchFromGitHub`, but adding those two lines doesn't seem so wrong to me.

**Comment by 3noch** [comment]
@HittingSmoke Did you ever get `pagespeed` working? I'm having issues at the `configure` step, where it claims it can't find `psol` (even though I've extracted it exactly as the instructions say).
