### ISSUE TITLE
Update latexindent to 3.13.2

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#142754]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: latexindent part of: nixpkgs.texlive.combined.scheme-medium 

current version: 3.9.2
desired version: 3.13.2

###### Notify maintainers

maintainers: @veprbl 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by veprbl** [comment]
Bumped to 3.13.4 in #154105
