### ISSUE TITLE
js8call

### ISSUE THREAD

**Issue by danwdart** [NixOS/nixpkgs#142790]
**Project description**
Amateur radio digital mode

**Metadata**

* homepage URL:https://js8call.com/ or http://files.js8call.com/latest.html
* source URL: https://widefido@bitbucket.org/widefido/js8call.git
* license: gpl3
* platforms: unix, linux, darwin

**Comment by mattmelling** [comment]
@danwdart I've just submitted a PR for this, would appreciate any feedback you have on it.

**Comment by mattmelling** [comment]
Closing, merged in #178374
