### ISSUE TITLE
Glamor doesn't work

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#14286]
NixOS. Xorg with "useGlamor = true" but it doesn't work.

Full Xorg log: https://gist.githubusercontent.com/anonymous/7b1058a5d83c7b63743d/raw/b41b78adbc0000e8d31a96d9bc1c7dcdf6b2977d/X.0.log

Relevant bit:

```
[     5.485] (II) "glx" will be loaded by default.
[     5.485] (II) LoadModule: "dri2"
[     5.485] (II) Module "dri2" already built-in
[     5.485] (II) LoadModule: "glamoregl"
[     5.488] (WW) Warning, couldn't open module glamoregl
[     5.488] (II) UnloadModule: "glamoregl"
[     5.488] (II) Unloading glamoregl
[     5.488] (EE) Failed to load module "glamoregl" (module does not exist, 0)
[     5.488] (II) LoadModule: "glx"
[     5.488] (II) Loading /nix/store/11z579gdckk3mlh3hnk5845vyky3ln71-xorg-server-1.17.4/lib/xorg/modules/extensions/libglx.so
[     5.497] (II) Module glx: vendor="X.Org Foundation"
[     5.497] 	compiled for 1.17.4, module version = 1.0.0
[     5.497] 	ABI class: X.Org Server Extension, version 9.0
```

**Comment by vcunat** [comment]
It seems using "intel" driver doesn't add the module by default, and specifying the option changes nothing about that (only "intel-testing").

Can you try this patch? [My earlier comment](https://github.com/NixOS/nixpkgs/pull/1969#issuecomment-38480314) suggests this kind of setup had been tested with intel.
```diff
diff --git a/nixos/modules/services/x11/xserver.nix b/nixos/modules/services/x11/xserver.nix
index 0fcea6c..4715c51 100644
--- a/nixos/modules/services/x11/xserver.nix
+++ b/nixos/modules/services/x11/xserver.nix
@@ -15,7 +15,7 @@ let
   knownVideoDrivers = {
     virtualbox   = { modules = [ kernelPackages.virtualboxGuestAdditions ]; driverName = "vboxvideo"; };
     ati = { modules = [ pkgs.xorg.xf86videoati pkgs.xorg.glamoregl ]; };
-    intel-testing = { modules = with pkgs.xorg; [ xf86videointel-testing glamoregl ]; driverName = "intel"; };
+    intel = { modules = with pkgs.xorg; [ xf86videointel glamoregl ]; };
   };
 
   fontsForXServer =
```

**Comment by abbradar** [comment]
Tested that it works for me and pushed 63f1eb6b00ca3bb792c36b4ce26685de90a62f5d. Thanks! I'll cherry-pick to release.

**Comment by vcunat** [comment]
We might make inclusion of the module conditional on specifying the option, but that's just a nitpick and I'm not sure what the driver defaults are (going to be) anyway.

**Comment by abbradar** [comment]
Yeah, I did it this way because I'm not sure that Intel doesn't enable it (nor considers in short term) by default on some systems. It's ~300k anyway.

**Comment by abbradar** [comment]
BTW. I've set:
```
services.xserver.deviceSection = ''
  Option "DRI" "3"
'';
```
and finally got tearing-free experience everywhere without an OpenGL compositor on Intel! I.e. no more tears when fast-scrolling in Firefox on XFCE. It would be nice when it finally is enabled by default (I suppose it isn't now due to potential stability issues).

**Comment by vcunat** [comment]
I assume changing the default DRI upstream is tied to releasing `xf86-video-intel-3.*`.
