### ISSUE TITLE
proj.x86_64-darwin build failing

### ISSUE THREAD

**Issue by bdj** [NixOS/nixpkgs#142875]
### Describe the bug
https://hydra.nixos.org/job/nixpkgs/trunk/proj.x86_64-darwin

The build is failing on darwin since the update to 8.1.1 (https://github.com/NixOS/nixpkgs/pull/138479)

### Notify maintainers

@dotlambda @vbgl

**Comment by Artturin** [comment]
this is the tempfile creation logic in proj_context_test.cpp
```
static std::string createTempDict(std::string &dirname, const char *filename) {
    const char *temp_dir = getenv("TEMP");
    if (!temp_dir) {
        temp_dir = getenv("TMP");
    }
#ifndef WIN32
    if (!temp_dir) {
        temp_dir = "/tmp";
    }
#endif
    if (!temp_dir)
        return std::string();

    dirname = temp_dir;

    std::string tmpFilename;
    tmpFilename = temp_dir;
    tmpFilename += DIR_CHAR;
    tmpFilename += filename;

    return createTmpFile(tmpFilename) ? tmpFilename : std::string();
}
```

**Comment by risicle** [comment]
I can't reproduce the failure on macos 10.15

**Comment by risicle** [comment]
I think we agreed in chat that we should disable these specific tests on darwin because none of us can reproduce this failure outside hydra, so I'm going to prepare a PR to do that **but** I think we need to keep this issue open until that has gone through and we can check that hydra's output is identical to our own builds. Otherwise we could be missing the fact that it's a genuinely broken output that's being built on hydra rather than just a dodgy test going wrong on hydra.

**Comment by veprbl** [comment]
I can reproduce failure on Mojave

**Comment by r-burns** [comment]
Oh, maybe that's it? I can't reproduce on catalina, and I've seen failures for other packages which are due to the builders using mojave.

**Comment by toonn** [comment]
I've been looking into this and it's because of a hardcoded assumption on the number of allowed open file descriptors on Linux AFAICT. On macOS the limit used to be 256 instead of Linux's 1024, don't know whether that changed.

**Comment by veprbl** [comment]
Do we have enough information to report the issue upstream? https://github.com/OSGeo/PROJ/issues

**Comment by toonn** [comment]
I'm looking into this. `OPEN_MAX` from `stdio.h` is the canonical source of the maximum number of file descriptors that can be open simultaneously but according to SO it's deprecated on Linux?

**Comment by veprbl** [comment]
What about `getrlimit(RLIMIT_NOFILE)`?

**Comment by toonn** [comment]
That's what I'm doing now but it does give up a little POSIX compatibility so I don't know how upstream will feel about it.

**Comment by risicle** [comment]
So.. #145371 deals with the `CApi.open_plenty_of_contexts` failure, but what about `GridTest.VerticalShiftGridSet_gtx`?

**Comment by toonn** [comment]
@risicle, I'm not sure about that, it doesn't seem like an actual failure. There's weirdness with the test suite where some other tests are sometimes affected by failures.

**Comment by risicle** [comment]
:crossed_fingers:
