### ISSUE TITLE
GNOME 41 starts in X11 by default

### ISSUE THREAD

**Issue by fufexan** [NixOS/nixpkgs#142882]
### Describe the bug
When logging in from GDM, with "GNOME" selected in the WM dropdown menu, it still starts in X11. Only when logging out and back in does it start in Wayland mode as it normally should.

### Steps To Reproduce
1. Start up computer
2. Have "GNOME" selected in the cog menu
3. Log in
4. Check "Preferences > About"

### Expected behavior
GNOME should start in Wayland mode, as it did back on GNOME 40.

### Notify maintainers
@jtojnar 

### Metadata
```console
[mihai@io:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-rc6, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: gnome
```

**Comment by Elinvention** [comment]
For me, it always starts in a broken Wayland session, unless I press on `GNOME on X11` before logging in with GDM.

**Comment by fufexan** [comment]
I found out yet another thing. Suspending using GNOME 41 Wayland causes my screen to not turn back on after resuming the system. For a long time I thought it was a kernel regression causing it, but found out that suspending while using Wayfire didn't cause this behaviour. Lately I also found out that suspending even with GNOME 41 X11 doesn't trigger the bug.

So my guess is there's more to this problem than just starting in Wayland by default.

**Comment by alexeymuranov** [comment]
I cannot start GNOME 41 in X11 on NixOS 21.11: selecting "GNOME on Xorg" i still end up in Wayland.

Should it be considered the same issue, or should i open a new one?

**Comment by fufexan** [comment]
@alexeymuranov can you check GDM logs? `journalctl -eu display-manager.service`
In my case the display-manager starts the X server for some reason, so I suspect the problem lies with GDM itself rather than Gnome Shell.

**Comment by alexeymuranov** [comment]
Today with `nixos-21.11.333896.a640d8394f3` everything seems to work normally. I hope i didn't mix up something.

**Comment by Elinvention** [comment]
I think this is the issue we are talking about https://gitlab.gnome.org/GNOME/gdm/-/issues/733

**Comment by alexeymuranov** [comment]
> @alexeymuranov can you check GDM logs? `journalctl -eu display-manager.service` In my case the display-manager starts the X server for some reason, so I suspect the problem lies with GDM itself rather than Gnome Shell.

@fufexan, the issue is sporadic, i have it again. Here is a tail of the output of `journalctl -eu display-manager.service`:
```
-- Boot c1924e4e235e461b82ae46e243c2a495 --
Dec 04 13:26:10 Alexey-BU403UA-NixOS systemd[1]: Starting X11 Server...
Dec 04 13:26:10 Alexey-BU403UA-NixOS systemd[1]: Started X11 Server.
Dec 04 13:26:24 Alexey-BU403UA-NixOS gdm-password][1599]: gkr-pam: unable to locate daemon control file
Dec 04 13:26:24 Alexey-BU403UA-NixOS gdm-password][1599]: gkr-pam: stashed password to try later in open session
Dec 04 13:26:24 Alexey-BU403UA-NixOS gdm-password][1599]: pam_unix(gdm-password:session): session opened for user alexey(uid=1000) by (uid=0)
Dec 04 13:26:25 Alexey-BU403UA-NixOS gdm-password][1599]: gkr-pam: gnome-keyring-daemon started properly and unlocked keyring
Dec 04 13:26:41 Alexey-BU403UA-NixOS gdm[1047]: Gdm: Child process -1217 was already dead.
```

**Comment by fufexan** [comment]
@alexeymuranov see @Elinvention's comment. It seems that the issue has been fixed upstream. Now we're waiting for the next release and this should be fixed.

As a sidenote, I've tried manually adding the patch like this:
```nix
  nixpkgs.overlays = [
    (final: prev: {
      gnome.gdm = prev.gnome.gdm.overrideAttrs (o: { patches = o.patches ++ [ ../pkgs/patches/gdm.patch ]; });
    })
  ];
```
but this causes `gnome-shell` not to build anymore:
```sh
error: attribute 'gnome-shell' missing

       at /nix/store/ypirn5v82ry7q8j8s089cx246w1k4gg3-source/nixos/modules/services/x11/desktop-managers/gnome.nix:433:9:

          432|       xdg.portal.extraPortals = [
          433|         pkgs.gnome.gnome-shell
             |         ^
          434|       ];
```

**Comment by jtojnar** [comment]
Overlays do not perform recursive merges so when you do `(final: prev: { gnome = { gdm = …; }; })` you replace the whole `gnome` attrset. You nee to use `(final: prev: { gnome = prev.gnome // { gdm = …; }; })`.

**Comment by fufexan** [comment]
After a few updates of the system and tweaks to the kernel, GNOME starts properly in Wayland. Not sure what the cause was in the first place, but it seems to be fixed now.

However, I've got a new small issue, being that whenever I log in, I have to wait for a few seconds before the Shell pops up. I've checked `journalctl` but not sure what I should be looking for. I'll open a separate issue if it's outside the scope of this one.

**Comment by mplanchard** [comment]
Just adding in case anyone else lands here from a search engine.

I had a similar problem to this after switching to gnome from KDE on NixOS 22.11, where the "Gnome" session would boot into X11 rather than Wayland, persisting across reboots. 

The following resolved the issue for me:
- Log out or restart
- Select "Gnome on Xorg" and log back in
- Log out again
- Select "Gnome" and log in again
