### ISSUE TITLE
create a service for jool

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#142840]
**Project description**
the package for the [jool-cli](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/os-specific/linux/jool/cli.nix#L23) and [kernel module](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/os-specific/linux/jool/default.nix#L29) exists already.

But a service and a config file management per nixos would be nice.
(a plain json format)

https://www.jool.mx/en/run-persistent.html

---

maintainer:
- @fpletz

**Comment by Majiir** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/240982.
