### ISSUE TITLE
Packaging Gnome 3.20

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#14289]
Gnome 3.20 is out. How can we help package it?

/cc @lethalman

**Comment by simonvandel** [comment]
Can this be closed now that Gnome 3.20 is in nixpkgs?

**Comment by DamienCassou** [comment]
@simonvandel I don't know what is the process, but there is still at least one issue: https://github.com/NixOS/nixpkgs/issues/16155. Does anyone regularly use gnome 3.20 on nixos?

**Comment by lethalman** [comment]
Yes we can close this. Issues are something additional to this. Thanks.
