### ISSUE TITLE
Opengl/3D Rendering on slic3r, super-slicer and super-slicer-staging broken

### ISSUE THREAD

**Issue by ChrisOboe** [NixOS/nixpkgs#142937]
### Describe the bug
When starting slic3r (or the forks super-slicer or super-slicer-staging) it greets you with the following errors:
"./src/unix/glx11.cpp(626): assert ""Assert failure"" failed in InitVisual(): Failed to get a XVisualInfo for the requested attributes."
"./src/unix/glx11.cpp(493): assert ""vi"" failed in wxGLContext(): invalid visual for OpenGL"
"./src/gtk/window.cpp(3792): assert ""m_widget"" failed in DoSetSize(): invalid window"

After clicking continue on the error messageboxes the slicer starts up, but the 3D-Rendering is missing. 

### Steps To Reproduce
1. start slic3r

### Expected behavior
No error messages on startup.
3D rendering is there after startup.

### Additional context
prusa-slicer, another fork of slic3r, works just fine. 

### Notify maintainers
@bjornfor
@cab404 
@Moredread 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 ~  nix-info -m
warning: warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).system
             |         ^
 - system: `0`
 - host os: `Linux 5.14.14, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `""`
warning: warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1:

            1| <nixpkgs>
             | ^
 - nixpkgs: `0`
```
Regarding the errors of nix-info: My nixos is built through flakes. I don't have set up any nix-channel. So these errors are unrelated to the bug report. I rebuild my system today based on nixos-unstable.

**Comment by ChrisOboe** [comment]
Everything is fine. 
it was a severe misconfiguration of my system.

**Comment by Moredread** [comment]
What did cause that? I would have guessed that there was an issue with your graphics driver but I'd still be interested what causes that error.

**Comment by ChrisOboe** [comment]
@Moredread in the past i used to install software (like slic3r, super-slicer and super-slicer-staging) via nix-env -i. I don't do this anymore, since i removed all the nix-channels and exlusively use flakes for my systems. 

But since i still had slic3r installed in my user environment and the user env has priority over the system one. So my system slic3r was never used. Only the outdated user one. 
As soon as i noticed that, i removed all the derivations from my user env, the system env slic3r was used and worked just fine. 

I still don't understand how this could lead to such a weird error, since even if slic3r from my user env was used, all the dependencies of it should also exist in the user env, and everything should be fine (except that it never receives updates). 
I assume that it's somehow indirectly related to the gpu driver, in the way that my modern system env mesa (or one of it's deps) gets loaded and the slic3r from my user env was linked against a incompatible older version, which couldn´t get loaded since the newer version was already in memory. 
But that's just a wild guess.

**Comment by Moredread** [comment]
Thanks :)
