### ISSUE TITLE
syncthing service doesn't work with default settings

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#14304]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`)
Linux gurney 4.5.0 #1-NixOS SMP Mon Mar 14 04:28:54 UTC 2016 x86_64 GNU/Linux
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.git.874c6b1 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.git.874c6b1"

## Describe your issue here
syncthing service fails when enabled (`sudo systemctl status syncthing`)

### Expected result
it doesn't fail.

### Actual result
it fails.

### Steps to reproduce

services.syncthing.enable = true;

nixos-rebuild switch

### Note
it works just fine if I set user to be my user and set the dataDir to be in my home directory, which is probably what most people do. However it would be great if those were either required by some asserts, or if the default config worked.

**Comment by rnhmjoj** [comment]
I agree. I run it as my user because I keep synced folders in my home but it make sense running it as `syncthing` in `/var/lib/syncthing` and definitely should run out of the box.
Enabling syncthing should create the user `syncthing.user` and create/setting the ownership of `syncthing.dataDir` if it's not existing already.
I'll look into it, though I don't know how to do this exactly.

**Comment by joachifm** [comment]
@rnhmjoj you'd add the appropriate entries to `users.users` and `users.groups`, then perhaps enforce ownership in the `preStart` service hook. It is common to only create the user if it matches the service default (e.g., "syncthing").

**Comment by rnhmjoj** [comment]
@joachifm thanks. I gave a look at `namecoind` and other services: when adding the used they specify a `config.ids.uids.<service>`; not sure what it is, is it necessary?

**Comment by joachifm** [comment]
For this service, a static id is probably the way to go; most of the time you can just omit it and have the system dynamically allocate an id on activation.

**Comment by rnhmjoj** [comment]
This can be closed now.
