### ISSUE TITLE
mono: 6.12.0.122 -> 6.12.0.158

### ISSUE THREAD

**Issue by cherryblossom000** [NixOS/nixpkgs#143110]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: mono

current version: 6.12.0.122
desired version: 6.12.0.158

###### Notify maintainers

maintainers: @thoughtpolice @obadz @vrthra

###### Note for maintainers

Please tag this issue in your PR.

**Comment by YoshiRulz** [comment]
The Mono project hasn't officially released any versions past 6.12.0.122: https://www.mono-project.com/docs/about-mono/releases/
And thus there is no source tarball: https://download.mono-project.com/sources/mono/

My application requires Mono >= 6.12.0.151, so I had to [build Mono from source](https://github.com/TASEmulators/BizHawk/blob/master/mono-6.12.0.151.nix). It works, but is not reproducible, [here's a diff](https://gist.github.com/YoshiRulz/83f74ddc7f656f2eedbbeb912c409231).

**Comment by jiegec** [comment]
Upgraded by pr #181051
