### ISSUE TITLE
nix-install cannot run unattended because interactive passwd

### ISSUE THREAD

**Issue by josdotso** [NixOS/nixpkgs#14312]
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/tools/nixos-install.sh#L260

Feature request: Add a runtime argument to nix-install (e.g. --root-passwd PASS) to enable automated calls of nix-install.  Examples of where this would be useful include: building Docker images, running unattended nixos-in-place [1].

[1] https://github.com/jeaye/nixos-in-place/issues/10

If there's some creative hack to workaround this, please let me know ..  Thanks!

**Comment by vcunat** [comment]
> If there's some creative hack to workaround this, please let me know

To me, adding the option seems the easiest way around this.

**Comment by dezgeg** [comment]
Doesn't it already not ask the root password if the script is running non-interactively (i.e. stdin is not a terminal)?

**Comment by vcunat** [comment]
Oh, true, I see that condition. And I would assume in your case you want `mutableUsers = false;` which also switches of the `passwd` call.

**Comment by domenkozar** [comment]
I use a workaround for this, but I agree with this feature request. https://github.com/snabblab/snabblab-nixos/blob/master/make-iso.nix#L39

**Comment by copumpkin** [comment]
It doesn't feel to me like using `nixos-install` for making images is really the best way to do it. We have a lot of image-building machinery in nixpkgs already that just uses Nix to construct appropriately structured filesystems.

**Comment by jcrben** [comment]
Looking for the most elegant workaround for this in a packer build based roughly on https://github.com/oxdi/nixos... mutableUsers seems to sort of work but then it failed. I'll try a couple other things but the feedback loop is slow.

> Doesn't it already not ask the root password if the script is running non-interactively (i.e. stdin is not a terminal)?

Would a PR be accepted?
