### ISSUE TITLE
ip-up.target won't be activated in nixos-containers

### ISSUE THREAD

**Issue by fpletz** [NixOS/nixpkgs#14314]
We have some systemd services that are `wantedBy` the `ip-up.target`. This target is not available and won't get activated in nixos-containers and (probably) also lxc/docker containers.

What is the correct, universal target for services that require ip connectivity? `network.target`? In my tests, `network.target` works.

**Comment by groxxda** [comment]
[This](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) may answer your question.

> What is the correct, universal target for services that require ip connectivity?
If Unit A cannot live without connectivity: Requires=network-online.target so it is also stopped when connectivity is lost and After=network-online.target to delay activation until connectivity is available.

If the unit should only be pulled in when the network stack is activated, WantedBy=network.target is probably the right decision, so ip-up.target may have been the wrong choice in the first place.
To allow clean termination of connections on shutdown After=network.target may also be useful.

Should we remove ip-up.target completely in favor of the standard network-online.target?

**Comment by fpletz** [comment]
There is no `ip-up.target` anymore and this seems to work now as expected.
