### ISSUE TITLE
jackett: 0.18.95 -> 0.19.71 + Standalone

### ISSUE THREAD

**Issue by NicolasGuilloux** [NixOS/nixpkgs#143247]
###### Checklist

- [ ] Copy the code already made from the link down below
- [ ] Fix and tweak as you like to fit nixpkgs standard

###### Project name
`nix search` name: jackett

current version: 0.18.95
desired version: 0.19.71

###### Notify maintainers

maintainers: @edwtjo @nyanloutre @purcell 

###### Note for maintainers

I already did that but I have no time to make a PR. Everything is available here, from the hash update to the migration from Mono to the standalone version : https://gitlab.com/NicolasGuilloux/nixos-configuration/-/blob/master/pkgs/jackett/default.nix

Cheers guys!

**Comment by flexagoon** [comment]
this issue is closed by #144563
