### ISSUE TITLE
hplip udev rules

### ISSUE THREAD

**Issue by guaraqe** [NixOS/nixpkgs#14338]
## Basic info

* Kernel: 3.18.26
* System: NixOS 16.09pre79463.d88ae10 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre79463.d88ae10

## Issue

When adding hplip to CUPS and SANE drivers:

    # Enable CUPS to print documents.
    services.printing = {
     enable = true;
     drivers = [ pkgs.hplip ];
    };

    # Enable SANE for scanners
    hardware.sane = {
     enable = true;
     extraBackends = [ pkgs.hplip ];
    };

Then `nixos-rebuild switch` fails with:

    /nix/store/acr5li34vir6vjypx924whcakr9riyrg-udev-rules/56-hpmud.rules
    (originally from /nix/store/k2gyds3b93bg0addsys75rvxw4isyqj3-hplip-3.15.9/etc/udev/rules.d/56-hpmud.rules)
    contains references to /bin/sh, /bin/sh, /usr/bin/nohup and /usr/bin/hp-config_usb_printer

I'm not sure how to solve that, the source would have to be changed.

**Comment by nckx** [comment]
@guaraqe: does [this patch](https://github.com/nckx/nixpkgs/commit/a77ec8632db86ee42e8db4e6e9b374dfbb373679.patch) fix the problem?

**Comment by guaraqe** [comment]
Sorry for the delay, first time testing someone else's patch :)

Works ok here, builds without problems!

**Comment by nckx** [comment]
@guaraqe: Thanks! I'll merge it in.

Don't hesitate to ping me about other hplip issues you might have. I'm not currently using it but would like to keep it working for future me & others.
