### ISSUE TITLE
makeWrapper produces wrapper script with bad interpreter?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#143323]
### Describe the bug

I have a bash script that I package like so:

```nix
    phases = ["unpackPhase" "patchPhase" "installPhase"];

    buildInputs = [ pkgs.git pkgs.makeWrapper ];

    patchPhase = ''
      patchShebangs mirrorit
    '';

    installPhase = ''
      mkdir $out/bin -p
      cp mirrorit $out/bin/mirrorit.wrapped
      makeWrapper $out/bin/mirrorit.wrapped $out/bin/mirrorit --prefix PATH : ${lib.makeBinPath [ pkgs.git ]}
    '';
```

And it worked, but stopped working recently. I am executing that script from a systemd service that is triggered via a timer and I get:

```
/nix/store/9ywr69qi622lrmx5nn88gk8jpmihy0dz-bash-4.4-p23/bin/bash: bad interpreter: No such file or directory
```

### Steps To Reproduce

Not sure.

### Expected behavior

Proper bash executable is referenced.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.125, NixOS, 21.05.git.5ebb1dca9bb (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(m): `"unstable-20.09pre216896.0729b8c55e0"`
 - nixpkgs: `/var/src/nixpkgs`
```

**Comment by jonringer** [comment]
```
 version `GLIBC_2.33' not found (required by /nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/bash)
 ```
 
 Generally this is because an older version of glibc is loaded by your system, then the binary wants the version that it was built against.

**Comment by matthiasbeyer** [comment]
>  Generally this is because an older version of glibc is loaded by your system, then the binary wants the version that it was built against.

But why isn't the GLIBC in the dependencies? Isn't that the exact thing that nix
"solved"?

**Comment by jonringer** [comment]
If the code is running in an impure environment, then it's subject to impure behavior.
