### ISSUE TITLE
Zynaddsubfx: no loaded instrument on upgrade. 

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#143324]
### Describe the bug
I upgraded Zynaddsubfx (latest unstable), and was surprised to discover the new amazing interface (whooa)... and that I had no more loaded instrument (empty bank).

I solved that problem by removing the user zynaddsubfx configuration and bank cache (I think the problem is the bank cache):

```
~$ rm .zynadd*
```

and indeed, once you reload zynaddsubfx, you can see that the instruments are back. Also, a new file `~/.zynaddsubfx-bank-cache.xml` is created, and the bank path is hardcoded, like:

```
...
bank="/nix/store/2y9g74xs09x960m66g6pbnxxgmwpzvjv-zynaddsubfx-3.0.5/share/zynaddsubfx/banks/the_mysterious_bank_4/"
...
```

I guess that in other distributions this path does not change when zynaddsubfx is updated, but with nix the bank path changes on upgrade, so the user needs to manually clear the cache on each upgrade.

I'm not sure what's the best way to solve this problem. I was thinking that the best solution may be to add a small wrapper around zynaddsubfx which clears the cache if it detects in `~/zynaddsubfx-bank-cache.xml` a path to another nix executable. The other possibility may be to use `/run/current-system/sw/share/zynaddsubfx/banks/` instead of the `/nix/` one, but it won't work outside of NixOs.

If these options are not working, at least it would be nice to document that bank cache should be cleared on upgrades.

### Steps To Reproduce
1. Upgrade zynaddsubfx and potentially garbage collect the old version
2. Start zynaddsubfx: instruments may disapear

### Notify maintainers
@goibhniu
@kira-bruneau

**Comment by kira-bruneau** [comment]
still relevant, just haven't gotten around to fixing it

**Comment by tobiasBora** [comment]
I think this issue should not be closed as for now it is based on a non-accepted PR, so I'll re-open waiting for the changes to be merged upstream.
