### ISSUE TITLE
Installing OpenJDK pulls in X11 libraries even on servers

### ISSUE THREAD

**Issue by philip-wernersbach** [NixOS/nixpkgs#14345]
## Basic info
- Kernel: N/A
- System: NixOS (Any Version)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre79463.d88ae10
## Describe your issue here

Installing OpenJDK on NixOS pulls in X11 libraries even when the system is a GUI-less server. This results in unnecessary dependencies, as any package that depends on a JDK will cause OpenJDK to be installed, which will in turn cause the X11 libraries to be pulled in, which will in turn cause the dependencies of the X11 libraries to be pulled in and so on and so forth.

The unnecessary dependencies are installed regardless of if the program that depends on the JDK uses the Java GUI libraries.
### Expected result

X11 libraries and their dependencies are only installed if the system has GUI functionality enabled.
### Actual result

X11 libraries and their dependencies are always installed.
### Steps to reproduce

Install any package on NixOS that depends on a JDK.

**Comment by wkennington** [comment]
This might be possible with jigsaw and openjdk 9 but nontrivial for older
jdks

**Comment by copumpkin** [comment]
Might also be relevant to #12877

**Comment by Profpatsch** [comment]
triage: I can reproduce this still:

```
 ~> nix-store -q --tree /nix/store/i1b9s1fxb4v339q4dprjdb3rl1wlsfji-openjdk-8u172b11 | grep -i x11
+---/nix/store/adljsy5qhiv543iaivkn0qrryiwjmnff-libX11-1.6.5
```

Is there a sensible way to solve this?

**Comment by FliegendeWurst** [comment]
There is e.g. `jdk8_headless` since #65247
