### ISSUE TITLE
Rust dependencies report hash mismatch

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nixpkgs#143461]
### Describe the bug

My hydra instance started to report hash mismatches in rust packages (agate, ion, nushell, ox, ripgrep) (I'm cross-compiling to aarch64-multiplatform). It appears that the commit f17c3516fb298dc11890a358d25d0b652e7ac300 introduced this. See also the associated PR: https://github.com/NixOS/nixpkgs/pull/143076.

### Steps To Reproduce
1. Checkout nixpkgs @ 55495f7428c39117b02619b7eb3b2db1c14c015b
1. `nix-build -A pkgsCross.aarch64-multiplatform.ripgrep` (just building the `.cargoDeps` attribute would be enough)
1. Downloads all deps...
1. Hash mismatch for cargo dependencies.

```
error: hash mismatch in fixed-output derivation '/nix/store/8jmsdpj0pwr2vv8fwgrmji7l8289z743-ripgrep-13.0.0-vendor.tar.gz-aarch64-unknown-linux-gnu.drv':
         specified: sha256-lyclsHoW6ScPHHiNcW8Dv8bMebGUgtXY65Ko3BB8zc0=
            got:    sha256-fxvTpj7kfDqD1MkeuekI4+nGwSeZz2EWLtclsxjxPuc=
```

### Expected behavior

No hash mismatch.

### Additional context

I don't understand why the linked change would cause this.

### Notify maintainers

@lovesegfault Maybe you know why this happens?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.14-xanmod1-cacule, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre-rc1`
 - channels(root): `"nixos-21.11pre323695.9aeeb7574fb, nixpkgs-21.11pre303315.16105403bdd"`
 - channels(rick): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: ripgrep (example)
```

**Comment by Mindavi** [comment]
Reverting has fixed this. Hopefully the right solution can be found :).

**Comment by lovesegfault** [comment]
@Mindavi Would you have time to test a re-do of the original PR? I think I know how to get it to work correctly.
