### ISSUE TITLE
Get rid of GitHub's CODEOWNERS feature (and replace it)

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#143441]
Because it is totally, utterly broken.

- People are not getting pinged although they should #124085
- It's easy to accidentally ping **a lot** of people with a bad PR #143425
    - Things like this easily happen when switching the target branch of a PR from `master` to `staging`
    - According to @maralorn, wrong pings like these make up a significant proportion of their email inbox

Taken together, the feature very probably **causes more harm than good**. We should make it a priority to disable it, and maybe find an alternative that is less broken. My suggestion would be to add it as an OfBorg feature: https://github.com/NixOS/ofborg/issues/567

**Comment by piegamesde** [comment]
I'm increasingly in favor of using a GitHub actions as well, simply because nobody wants to touch OfBorg and I'd prefer any solution over no solution.

I've stumbled over https://github.com/sourcegraph/codenotify which also has a [good blog post](https://about.sourcegraph.com/blog/a-different-way-to-think-about-code-ownership/) that describes their thoughts on the issue (spoiler: they had many problems we have too). We might even use their code with modifications (for example, we prefer review requests rather than comment pings). But I'd be open to continuing work on our custom implementation as well.

I really liked their distributed approach across the file tree. It really makes sense to localize these, instead of keeping them in one huge file. I'm also increasingly in favor of moving the maintainership entirely out of the nix files, since it has caused much trouble w.r.t tooling support (pings for NixOS modules and tests are still broken if they ever worked).

**Comment by SuperSandro2000** [comment]
Since recently GitHub shows you exactly which entry is wrong https://github.com/NixOS/nixpkgs/blob/master/.github/CODEOWNERS

**Comment by FliegendeWurst** [comment]
This was done in #347610 and related PRs. Problems with the new mechanism should go in new issues.
