### ISSUE TITLE
Sysdig does not work

### ISSUE THREAD

**Issue by markus1189** [NixOS/nixpkgs#14359]
## Basic info

To make sure that we are on the same page:

* Kernel: `Linux nixos 4.4.6 #1-NixOS SMP Wed Mar 16 15:43:17 UTC 2016 x86_64 GNU/Linux`
* System: `16.09pre79453.32b7b00 (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09pre79453.32b7b00"`

## Describe your issue here
When installing `sysdig` and trying to run it, it does not find the sysdig driver.

### Expected result
sysdig starts and captures events.

### Actual result
sysdig fails with
```
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

### Steps to reproduce
* install sysdig (I did it via `environment.systemPackages` and `sudo nixos-rebuild switch`)
* try to run sysdig:

```
~ > sudo sysdig                                                                                                   
Unable to load the driver
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.
```

**Comment by markus1189** [comment]
pinging @7c6f434c because I guess that I am just doing something wrong ;)

**Comment by cleverca22** [comment]
sounds like either the sysdig package providing the module has to be added, or sysdig enabled in the kernel

**Comment by markus1189** [comment]
any idea on how to do that? I must admit I don't have one ;)

**Comment by markus1189** [comment]
Ah I found the required config.  Add this to your `configuration.nix`

```
boot.extraModulePackages = [ pkgs.linuxPackages.sysdig ];
```
