### ISSUE TITLE
Add Visual Studio Code editor

### ISSUE THREAD

**Issue by mucaho** [NixOS/nixpkgs#14354]
That's a code editor, developed by Microsoft.
There's already [syntax highlighting for nix in vscode](https://www.reddit.com/r/NixOS/comments/3vc9nf/nix_language_syntax_coloring_for_visual_studio/), but the `vscode` package itself is missing.

I got it working, but there are multiple alternatives how to package it:
* download the binary directly, patchelf it, license = MS's unfree license
* download the sources, compile them, during which the binary dependency `electron` is downloaded by their install script, patchelf the `electron` dependency, license = MIT
* download the sources, compile them, adapt their install script to use `electron` from the nixpkgs repository (which is compiled itself, need to change the nixpkgs `electron` expression to do patchelf instead of `wrapProgram` with `LD_LIBRARY_PATH`), license = MIT   
Problem: `vscode` requires specific `electron` version - have a separate `electron-vscode` expression for that?

Wrapping `electron` with `LD_LIBRARY_PATH` env var is not possible, since `vscode` and `electron` modify the user environment (see [https://github.com/Microsoft/vscode/issues/1033](https://github.com/Microsoft/vscode/issues/1033)).
For licensing terms, see [license explanation](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005).
One (major) drawback of the FOSS version is that the [extension manager is missing](https://github.com/Microsoft/vscode/issues/2647), which lets you conveniently install additional plugins. However, it can be easily enabled, by modifying a configuration file. Seems like that is [allowed for the FOSS version](https://github.com/Microsoft/vscode/issues/1557#issuecomment-173449135).

Which alternative to choose? Is there another?

Patchelf looks something like this:
```sh
patchelf --set-interpreter $(cat $NIX_CC/nix-support/dynamic-linker) --set-rpath /nix/store/<hash>-env-atom/lib64:/nix/store/<hash>-env-atom/lib:/run/opengl-driver/lib:/run/opengl-driver-32/lib:/path/to/root/of/binary /path/to/root/of/binary/code
```
For `atom-env`, refer to [`electron`'s nix expression](https://github.com/NixOS/nixpkgs/blob/7941e1c457a730e989c5cbb26a793d381dfeab81/pkgs/development/tools/electron/default.nix).

**Comment by vcunat** [comment]
In general, building everything from source is preferred.

**Comment by offlinehacker** [comment]
But, good luck with that ;)

**Comment by jgillich** [comment]
I'm :-1: on building from source on this one. The extension gallery only works with the unfree version, and without it, the editor is just a glorified notepad.

**Comment by mucaho** [comment]
Ah sorry for the misunderstanding, the (vital) extension manager can be enabled by adding merely 3 lines to a configuration file (I've somehow skipped that while skimming over the linked issue). Building everything from source is indeed the best option here.

**Comment by jgillich** [comment]
Amazing how some people can't just answer a simple yes/no question. Thank you very much for clarifying, and for packaging!

**Comment by mucaho** [comment]
Oh noes! The [hydra build for `vscode`](https://hydra.nixos.org/build/34029962) is complaining while trying to download external dependencies with `npm`:
> npm ERR! fetch failed https://registry.npmjs.org/...

I fear that this is by design and that a clean nix derivation may not access external resources, except for what has been defined as inputs (expression parameters + `src` files).

How should this be solved?
The node dependencies are `shrinkwrap`ed, that means the exact versions are specified for each (sub)dependency, which should produce a deterministic build. Is there some way to have `npm` install those dependency and let nix enumerate and hash the whole `node_modules` folder as a `src` dependency?
If there is no workaround, it will have to be repackaged as a binary :(

**Comment by jgillich** [comment]
I think you should be using `buildNodePackage`, example: https://github.com/NixOS/nixpkgs/blob/788800e437c4a0a25d95e217540bded68804b25e/pkgs/applications/networking/irc/shout/default.nix

**Comment by mucaho** [comment]
Thanks to combined effort (#14891), `vscode-1.0.0` should work now.
Assuming you have a `nixpkgs` channel setup which tracks the [`nixpkgs-unstable` channel](https://nixos.org/channels/nixpkgs-unstable/), and you have `{ allowUnfree = true; }` inside your `.nixpkgs/config.nix`, you can install it via `nix-env -iA nixpkgs.vscode`.

**Comment by razvan-panda** [comment]
What worked for me was:
* manually creating folder/file `~/.config/nixpkgs/config.nix` and adding `{ allowUnfree = true; }` to it
* running `nix-env -f '<nixpkgs>' -iA vscode` to install it

Thanks to the helpful people in Freenode #nixos: rycee, Fare, sphalerite

**Comment by sid-kap** [comment]
Is vscode no longer in nixpkgs?

**Comment by razvan-panda** [comment]
@sid-kap I installed it yesterday latest version using `nix-env -i vscode-1.19.2`
But for some reason it does not appear listed on the website search.

**Comment by vcunat** [comment]
It's marked as unfree, and therefore hidden by default.

**Comment by AMDphreak** [comment]
It all needs to be searchable from the website. The website is the natural way to search and list packages, and is the de-facto standard.

**De-facto standard**
If a programming language has a package manager, it is the de-facto standard to put it online. So, too, must OSes with package managers but no App store. It is an industry-wide expectation.

**The terminal is an inappropriate place to browse packages.**
Use of substring and fuzzy search are not appropriate, if such a project has many plugins with its root-name in it, for example, "gnome". Search for a "gnome" package; if there was a package called "gnome" you would never find it among all the similar names. (assuming it doesn't get sorted at the top).

**Comment by puffnfresh** [comment]
@AMDphreak https://nixos.org/nixos/packages.html

**Comment by puffnfresh** [comment]
vscode is not listed there because it is unfree. NixOS by default is a free software distribution.

**Comment by AMDphreak** [comment]
> vscode is not listed there because it is unfree. NixOS by default is a free software distribution.

You need to attract people to the OS. People use non-free software. Free/non-free is for the end-user to decide, not to be enforced by the distro. You're creating a very bad relationship between the distro and the end user. You live in a world full of non-free software. To get rid of it, you must embrace each user's right to choose their own software and provide a better experience than the non-free software. It is not the distro's right to tell users what they can or cannot run on their system, or pose an unreasonable obstruction to those who wish to do so (such as not showing non-free in search results). The free software community complains that Apple and Microsoft do this. The fact that they do the same is hypocritical.

**Comment by chloekek** [comment]
I came across this issue in a web search for “nixpkgs vscode unfree” in the hope to find clarification. The licensing issue is now clear to me: Microsoft offers only an unfree build of their otherwise free code. To help future visitors I post this here, since it’s what Startpage/DDG point to.

It appears the [_vscodium_](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/vscodium.nix#L35) package in Nixpkgs outputs a free build of VS Code, under the MIT license. There are some differences in the final product but those are only cosmetic, removal of telemetry, and the name of the executable. It also seems to be entirely up-to-date with the unfree version.

It would be nice if this somehow showed up if you searched for “vscode” in the [packages page](https://nixos.org/nixos/packages.html). Of course it doesn’t now, since “vscode” is not a substring of “vscodium”.
