### ISSUE TITLE
Some Qt applications randomly stop getting keyboard inputs

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#143695]
### Describe the bug

I upgraded last night my nixos unstable. Since then I've a strange behavior that happens from time to time, but quite regularly (it maybe occurred on 20 applications today, but I noticed it only 4-5 times realizing that many applications were blocked): I can't type anymore any text on the applications, it's like if the keyboard is not working. But when I go to another application, it works again!

I had this problem with Okular, Konsole, RaySession (freshly "packaged"), but Firefox seems not to be impacted… so I guess it's a Qt problem. When I don't use an application during a long time it usually finishes to be impacted. Like right now I opened maybe 5 hours ago 3 Konsole, they all lost keyboard access. I also opened maybe 2 hours ago 2 other Konsole, and they still work fine. Also, on the 5 pdf opens with Okular this afternoon, 4 of them are blocked (can't search, can't navigate with keys…).

When typing `journalctl -b -e` I see a single line:

```
oct. 29 18:17:53 me xsession[41061]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4429, resource id: 71303173, major code: 18 (ChangeProperty), minor code: 0
```

### Steps To Reproduce
1. Upgrade to latest unstable `a4bf4434570`, with a plasma session
2. Open multiple Konsole, Okular...
3. Wait a bit. At some point you should not be able to type any command or do any search in some of them. But the application is not frozen: mouse is still working. Only one solution to get keyboard back: restart the app.

### Notify maintainers
@NixOS/qt-kde

**Comment by ttuegel** [comment]
The error you see in `journalctl` is a normal failure and probably not related to the actual problem; I have been seeing this message for years.

**Comment by peterhoeg** [comment]
Still a problem for you @tobiasBora ?

**Comment by tobiasBora** [comment]
This issue mysteriously stopped after a few weeks… I have not experienced this in a while, and I recently upgraded and it's still working fine… I guess we can close it, I'll re-open if I ekperience it again.
