### ISSUE TITLE
16.03 moreutils 0.57 is a 404 link

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#14374]
## Basic info
Linux toadman 4.3.3 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
15.09.1180.e8e1cb8 (Dingo)
nix-env (Nix) 1.10
"16.03.468.2d840da"
## Describe your issue here
Trying to upgrade to 16.03 on my laptop I get stuck here.  It looks like the newer version 0.58 is in master already.  seems like most easy way to fix it will be to pull that change into 16.03  otherwise one could change the link to http://archive.ubuntu.com/ubuntu/pool/universe/m/moreutils/ which also has a copy of the tarball that moreutils is looking for.

**Comment by joachifm** [comment]
The moreutils changelog only lists two minor changes in 0.58, so I think we can safely backport it to stable.
