### ISSUE TITLE
`systemd.user.<unit-type>.<name>.wantedBy` suggests to use `multi-user.target`

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#143811]
### Describe the bug

The current documentation suggests to use the `multi-user.target` as `wantedBy` for user services. Some people who do not really know systemd just use this suggestion and am wondering about their services not beeing started.

A better example for user-units would be `default.target` or `graphical-session.target`, the same value could then be used as the default for user-units.

### Steps To Reproduce

1. Read the description for any of the `wantedBy` option within the `systemd.user` option hierarchy.
2. Use `multi-user.target` as its value as suggested
3. see how your service is not started, not even after a new login

### Expected behavior

Have a proper default communicated, that would actually cause the service beeing started with the users session, like `default.target` or `graphical-session.target`

### Notify maintainers

No maintainers listed, therefore mentioning the last 5 contributors to the file linked by the option from https://search.nixos.org/options

* @hyperfekt 
* @gebner 
* @peterhoeg 
* @grahamc 
* @roberth 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211028_0d00dd6`
 - channels(nmelzer): `"nixpkgs-21.11pre293089.1c2986bbb80"`
 - channels(root): `"nixos-21.05.3021.8b0b81dab17"`
 - nixpkgs: `/home/nmelzer/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: []
# a list of nixos modules affected by the problem
module:
- system/boot/systemd.nix
```

**Comment by justsomehumanbeing** [comment]
For me this was really confusing.
Especially as I learned that non-NixOS related documentation often is not helpful as NixOS handles things differently
it took me quite a while to figure out that I should replace `multi-user.target` by `default.target`.

Please update the documentation.

**Comment by liketechnik** [comment]
I believe the option is documented in [`nixos/lib/systemd-unit-options.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/systemd-unit-options.nix). The git log of that file points to #29453 as the last time the documentation was updated, which is the origin of that wording.

To me it sounds reasonable to update the wording to point to `default.target` or `graphical-session.target`. If I don't hear any complaints, I'll prepare a PR in the following days.

**Comment by liketechnik** [comment]
#199007 has been merged now, so I guess this can be closed now?

**Comment by NobbZ** [comment]
Yes, thats indeed a good start, though I'd love if the docs wouldn't be shared between user and system services and the option would only discuss the relevant target.

I see though how thats not that easy under the current architecture.

**Comment by ncfavier** [comment]
> Yes, thats indeed a good start, though I'd love if the docs wouldn't be shared between user and system services and the option would only discuss the relevant target.

Could you open a new issue for this? I'm going to close this one as the initial problem is fixed now.

(FWIW I think it's fine to have the docs shared; system and user units have more in common than they have differences)

**Comment by roberth** [comment]
The doc strings can be assembled with conditionals. Maybe add an internal option to distinguish between the user and system context, if we can't already discern that.
