### ISSUE TITLE
Outdated comment in fetchgit

### ISSUE THREAD

**Issue by pinn3** [NixOS/nixpkgs#143846]
### Describe the bug
While researching if it would be possible to implement a certain feature in the git fetcher, I found a comment that seemed out-of-date:

https://github.com/NixOS/nixpkgs/blob/6f53c067482743fd68a5beceeb1205fab0ebe4c4/pkgs/build-support/fetchgit/default.nix#L61

The quotation marks were removed in https://github.com/NixOS/nixpkgs/commit/7b8fb5c06cc28a9ed2bbe605de44570ad6c8fecc, but the comment was left in place. Not sure if what it says remains true or not though

**Comment by pinn3** [comment]
Some more context can be found in https://github.com/NixOS/nixpkgs/commit/b89514eced6d32203982c54e0ad8c2f83dbca900 and https://github.com/NixOS/nixpkgs/commit/2cf7069b7da368326b51520536ac0f1020157f7a

**Comment by Artturin** [comment]
the comment can be removed

**Comment by pinn3** [comment]
> the comment can be removed

Yeah probably, as this has been working since 2019. However I would like to understand **why** it's working before removing it
