### ISSUE TITLE
pulumi-bin: 3.14.0 -> 3.16.0

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#143837]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: pulumi-bin
current version: 3.14.0
desired version: 3.16.0

###### Notify maintainers
maintainers: @ghuntley @peterromfeldhk @jlesquembre @cpcloud 

###### Note for maintainers

I tried running the updater script, but if fails halfway, due to api.pulumi.com rate-limits. We get back a HTTP error 403. (cc @t0yv0)

Please tag this issue in your PR.

**Comment by t0yv0** [comment]
Hi Florian thanks for this, we might need to add retry/backoff around that script.

**Comment by t0yv0** [comment]
I'm trying here but cannot repro, maybe `sleep 1` around this line? We already have `sleep 1` in the script around GH APIs.

```
        sha256=$(nix-prefetch-url "$url")
```

**Comment by flokli** [comment]
I think I ran the script once with the current version (not realizing I need to manually update the updater script first), and /then/ with the new version. It might be that's what got me into the rate limiting.

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/pull/143962 has been merged some time ago, let's close this.
