### ISSUE TITLE
ocaml doesn't build for buildPlatform when a crossSystem exists

### ISSUE THREAD

**Issue by telent** [NixOS/nixpkgs#143883]
### Describe the bug

When I import nixpkgs with a `crossSystem` attribute, building caml for the "build" environment fails.

```
$ cat ocaml-env.nix
with import <nixpkgs> {
  crossSystem = { config = "aarch64-unknown-linux-gnu";};
};
buildPackages.ocamlPackages.ocaml

$ NIX_PATH=nixpkgs=`pwd` nix-build  ocaml-env.nix -o ocaml
[...]
Fatal error: cannot load shared library dllunix
Reason: dllunix.so: cannot open shared object file: No such file or directory
make[3]: *** [Makefile:403: stdlib_man/Stdlib.3o] Aborted (core dumped)
make[3]: Leaving directory '/build/ocaml-4.12.0/ocamldoc'
make[2]: *** [Makefile:883: manpages] 
```

(For clarity, I want ocaml running on the machine I am building on, so that I can use coccinelle to generate a kernel image for 
the machine I am deploying to)

The problem *appears* to be with the setting of `configurePlatforms` as `["host" "target"]` in https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ocaml/generic.nix#L67. If I change this to `["host" "build"]` then native (non-cross) compilation works again

```
# this works
with import <nixpkgs> {
  crossSystem = { config = "aarch64-unknown-linux-gnu";};};
buildPackages.ocamlPackages.ocaml.overrideAttrs(_:{  configurePlatforms = ["host" "build"];})
```

### Steps To Reproduce

See transcript in previous sesion

### Expected behavior
The package builds

### Additional context

Build system is x86-64 
Host system doesn't seem to matter - have tried with mips, mipsel and with aarch64
Tested against nixos-unstable 2deb07f3ac4eeb5de1c12c4ba2911a2eb1f6ed61 (Oct 28)

### Notify maintainers

My guess from git logs - @symphorien  @vbgl @Ericson2314 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 -  - host os: `Linux 5.10.62, NixOS, 21.05.2987.fd6dba47199 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(dan): `""` 
 - channels(root): `"nixos-21.05.2987.fd6dba47199, telent-nixos-config"` 
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Ericson2314** [comment]
We should ask upstream exactly what they expect. If it's like most compliers there is probably some degree of confusion as to what is expected.

**Comment by symphorien** [comment]
Ocaml does not support cross compilation at all: https://dune.readthedocs.io/en/latest/cross-compilation.html
pkgsStatic works somehow because it's possible to execute one platform to another, so it's not really cross.

If I try to reproduce your example with gcc I build a cross gcc:
```nix
with import <nixpkgs> {
  crossSystem = { config = "aarch64-unknown-linux-gnu";};
};
buildPackages.gcc6
```
```commands
$  nix-build test.nix
these derivations will be built:
  /nix/store/kpywzl8vim82vlc0ifqdzkd982mdh9vd-aarch64-unknown-linux-gnu-stage-final-gcc-debug-6.5.0.drv
  /nix/store/m78hsx56y1izf4pimcjlfj0dxgdqw3ck-aarch64-unknown-linux-gnu-stage-final-gcc-debug-wrapper-6.5.0.drv
```

buildPackages contains compilers that can be executed on the buildMachine, but which produce executable of the target machine. So buildPackages.ocaml fails, and it's normal.

If your goal is to build coccinelle to patch a crosscompiled kernel, you want an ocaml that builds for the build architecture. So probably you want `pkgsBuildBuild.ocaml`:
```nix
with import <nixpkgs> {
  crossSystem = { config = "aarch64-unknown-linux-gnu";};
};
pkgsBuildBuild.ocaml
```
and this builds :)

**Comment by telent** [comment]
That makes a lot of sense, thanks. 

Happy to close this
