### ISSUE TITLE
linux hardened 5.14

### ISSUE THREAD

**Issue by evrim** [NixOS/nixpkgs#143826]
Hello,

I was reading through the kernels in the following:
https://github.com/NixOS/nixpkgs/blob/7e66e35e1f44c7e027d0bd8a6cd7b44b22422d08/pkgs/top-level/linux-kernels.nix

```

  packageAliases = {
    linux_default = packages.linux_5_10;
    # Update this when adding the newest kernel major version!
    linux_latest = packages.linux_5_14;
    linux_mptcp = packages.linux_mptcp_95;
    linux_rt_default = packages.linux_rt_5_4;
    linux_rt_latest = packages.linux_rt_5_11;
    linux_hardkernel_latest = packages.hardkernel_4_14;
  };
```

On line 517, linux_hardkernel_latest is defined as version 4.14. Is this a typo or do we have hardened 5.14 alias elsewhere?
Looking for linux_latest_hardened >= 5.14.

thnx,
evrim.

**Comment by xaverdh** [comment]
That's not a typo. Note that `hardkernel != hardened kernel`. The hardkernel variant has something to do with https://en.wikipedia.org/wiki/ODROID.
Judging from the history of that file, that kernel is updated ~once per year and they follow LTS versions..

**Comment by xaverdh** [comment]
See https://github.com/NixOS/nixpkgs/pull/133587 for reasoning why `linux_latest_hardened` was dropped.

**Comment by evrim** [comment]
Thanks for the explanation. I see the note on line 498 in the following now.

https://github.com/NixOS/nixpkgs/blob/31b495592feadb2785279988a2d7db6e2bdd7ed2/pkgs/top-level/aliases.nix

**Comment by xaverdh** [comment]
`nix repl '<nixpkgs>'` is your friend here: typing `linux_hardkernel_latest` should give you that message.

**Comment by evrim** [comment]
Thnx :)

Btw, there is anew patch for the 5.15, might be good to update the hardened.

https://github.com/anthraxx/linux-hardened/releases/tag/5.14.15-hardened1

evrim.

**Comment by xaverdh** [comment]
> Thnx :)
> 
> Btw, there is anew patch for the 5.15, might be good to update the hardened.
> 
> https://github.com/anthraxx/linux-hardened/releases/tag/5.14.15-hardened1
> 
> evrim.

I think that the patches get updated automatically now with the kernel `update.sh` script. So it should be part of the next kernel updates (usually every ~10days).
