### ISSUE TITLE
Package request: Firefly (IOTA wallet)

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#143855]
**Project description**
 IOTA's New Wallet

**Metadata**

* homepage URL: https://firefly.iota.org/
* source URL: https://github.com/iotaledger/firefly/
* license: Apache License 2.0
* platforms: linux, darwin

**Comment by WolfangAukang** [comment]
I can try to build this one. Let me see how it goes.

**Comment by felschr** [comment]
Closed by #144337
