### ISSUE TITLE
Update NetworkManager to 1.1.92

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#14391]
NetworkManager has seen [release 1.1.92](https://download.gnome.org/sources/NetworkManager/1.1/). NixOS is currently at 1.0.6 (latest in 1.0 series is [1.0.12](https://download.gnome.org/sources/NetworkManager/1.0/)). Is it worth upgrading?

/cc @Phreedom @rickynils @domenkozar

**Comment by domenkozar** [comment]
9 usually means 'dev', but we should upgrade to 1.0.12

**Comment by abbradar** [comment]
We have an 1.0.12 update in https://github.com/NixOS/nixpkgs/pull/14421

**Comment by ttuegel** [comment]
Closing this because we have a PR for the stable version.
