### ISSUE TITLE
okular cannot open PDF files outside of KDE

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#14390]
On my unstable NixOS system, `okular` (KDE document viewer) is not able to open PDF files when run outside of the KDE desktop.

When trying to do so it shows a notification saying the file cannot be opened, and gives the following messages in the terminal:

```
okular(13454)/okular (app) Okular::Document::openDocument: No plugin for mimetype '"application/pdf"'.
```

I has been installed by adding `kde5.okular` to `environment.systemPackages`.

**Comment by vcunat** [comment]
It does work without KDE for me, but that's likely just because mime works in my setup. By recent reports it's not so for everyone, even when installing `shared_mime_info`, though I don't know why exactly.

**Comment by kevincox** [comment]
Is this still an issue? If so would it be possible to provide a minimal Nix config that reproduces the issue?

**Comment by rasendubi** [comment]
Adding this to the NixOS configuration should workaround the issue:
```nix
{
  environment.systemPackages = [ pkgs.shared_mime_info ];
  environment.pathsToLink = [ "/share" ];
}
```

**Comment by romildo** [comment]
It is still an issue and the mentioned workaround works for me.

**Comment by oleks** [comment]
Hi, the mentioned workaround didn't work for me. Listing `pkgs.shared_mime_info` in my `environment.systemPackages` creates no `/share/` directory.
