### ISSUE TITLE
Update default gcc from 10 to 11

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#143950]
`gcc-11` is already in `nixpkgs` as a `gcc11`  and `gcc11Stdenv` attribute, but it's not enabled by default yet. `gcc-11` has a few breaking changes that require gcc porting: https://gcc.gnu.org/gcc-11/porting_to.html. Let's track and fix them explicitly:

How to test a package:

```
$ nix-build -E 'with import <nixpkgs> {}; rapidsvn.override { stdenv = gcc11Stdenv; }'
```

# Default standard is now GNU++17
- [ ] rapidsvn: https://github.com/NixOS/nixpkgs/issues/143949
- [ ] liblastfm: https://github.com/NixOS/nixpkgs/issues/143956
- [ ] smesh: https://github.com/NixOS/nixpkgs/issues/143973

# Warning changes break `-Werror=...`
- [ ] edk2: https://github.com/NixOS/nixpkgs/issues/143951
- [ ] doctest: https://github.com/NixOS/nixpkgs/issues/143965
- [ ] openvino: https://github.com/NixOS/nixpkgs/issues/143972

# Header dependency changes
- [ ] libbitcoin: https://github.com/NixOS/nixpkgs/issues/143952
- [ ] armips: https://github.com/NixOS/nixpkgs/issues/143953
- [ ] crc32c: https://github.com/NixOS/nixpkgs/issues/143957
- [ ] faust: https://github.com/NixOS/nixpkgs/issues/143958
- [ ] intel-graphics-compiler: https://github.com/NixOS/nixpkgs/issues/143959

#  GCC 11 now enforces that comparison objects be invocable as const. 
- [ ] perseus: https://github.com/NixOS/nixpkgs/issues/143954
- [ ] exempi: https://github.com/NixOS/nixpkgs/issues/143966

# Ordered pointer comparison with integer
- [ ] mimetic: https://github.com/NixOS/nixpkgs/issues/143955
- [ ] hashdeep: https://github.com/NixOS/nixpkgs/issues/143968

# Unclear
- [ ] monkeysAudio: https://github.com/NixOS/nixpkgs/issues/143960
- [ ] stuntrally: https://github.com/NixOS/nixpkgs/issues/143970

# Explicit porting needed due to gcc version change
- [ ] itk, c3d: https://github.com/NixOS/nixpkgs/issues/143963

**Comment by Ma27** [comment]
Tbh while I appreciate the effort, I think that flooding the issue tracker with these kinds of issues is rather counter-productive.

In the past, we usually created a Hydra jobset and a branch (ahead of staging-next), did `Compare to staging-next` inside a jobset-eval and fixed all packages that are broken on the feature-branch, but not on staging-next. After a rebase against staging, it can be merged into staging.

Unless someone else wants to do it, I was planning to look into it as soon as I'm done with #133431.

**Comment by vcunat** [comment]
Yes, just one thread (e.g. this issue) instead of all the individual ones might be better IMHO, at least for the simpler cases.  I expect lots of similarity in approaches to resolving these problems (and in people attempting to do so).

**Comment by trofi** [comment]
> I think that flooding the issue tracker with these kinds of issues is rather counter-productive.

If they are useless I can close them and start chipping pull requests with fixes one by one. I don't see how I can signal other maintainers' help fixing the problems. I assume at least some of them are interested in doing some work.

> In the past, we usually created a Hydra jobset and a branch (ahead of staging-next), did Compare to staging-next inside a jobset-eval and fixed all packages that are broken on the feature-branch, but not on staging-next. After a rebase against staging, it can be merged into staging.

As an outside observer It's not clear to me how maintainers are communicated in this case if not through issues.

**Comment by trofi** [comment]
> Yes, just one thread (e.g. this issue) instead of all the individual ones might be better IMHO, at least for the simpler cases. I expect lots of similarity in approaches to resolving these problems (and in people attempting to do so).

My worry to dump everything into one issue  is that it would require a few hundreds of packages to update. Sounds like is would generate too many issue updates for everyone involved (I assume once user is tagged on the issue they get all the updates from it).

**Comment by Ma27** [comment]
> As an outside observer It's not clear to me how maintainers are communicated in this case if not through issues.

Usually that's something taken care of by the person who takes care of the bump.

> My worry to dump everything into one issue is that it would require a few hundreds of packages to update. Sounds like is would generate too many issue updates for everyone involved (I assume once user is tagged on the issue they get all the updates from it).

Why even dump this into an issue if we can use Hydra for this?

**Comment by trofi** [comment]
> > As an outside observer It's not clear to me how maintainers are communicated in this case if not through issues.
> 
> Usually that's something taken care of by the person who takes care of the bump. (Edit: or if you're talking about reviews, that's what ofborg does).

I'll try to rephrase the question. Let's pick specific example: gcc10 ->11 bump. Suppose I'm doing the bump (I don't have access to `hydra` or `nixpkgs`). I spent some time and found 100 (or 500) distinct broken packages that need some work to make it fixed in `nixpkgs`.

**How do I make 100 package maintainers aware of the problem?** I'd prefer not to write 100 (or 500) upstream reports/fixes and downstream fixes myself. My limit is about 20 per week.

> > My worry to dump everything into one issue is that it would require a few hundreds of packages to update. Sounds like is would generate too many issue updates for everyone involved (I assume once user is tagged on the issue they get all the updates from it).
> 
> Why even dump this into an issue if we can use Hydra for this?

Using hydra sounds great. I miss the link between "hydra detected build failure" and "package maintainer knows their package failed to build". Does hydra send build error notifications? If not how does it happen?

**Comment by vcunat** [comment]
I think that package maintainers have less role in this kind of changes than usually, as usually the problems and solutions repeat quite a bit across packages.  (Another problem is that often there's noone listed or those who are really aren't active.)

Hydra would be there just to find the regressions.  Making a WIP PR for the update + branch in the official repo (or other ways of being OK to push there)... might lure some other contributors to the effort, but practical experience seems that usually we don't get more people participating on such projects.

**Comment by trofi** [comment]
Oh, I did not realize an explicit expectations that maintainers don't take part in porting efforts. Sounds like maintainers have nothing to do at all in `nixpkgs` :)

Closed all tickets as INVALID.

**Comment by vcunat** [comment]
I'd probably involve them e.g. in case it seemed that an update of the package would be the best solution.
