### ISSUE TITLE
Firefox 45.0.1 fails to compile

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#14402]
## Basic info

* NixOS unstable
* Nix version: 1.11.2

## Describe your issue here

Compiling Firefox 45.0.1 with the following package override

```
firefox-unwrapped = pkgs.firefox-unwrapped.override {
  enableOfficialBranding = true;
};
```

Fails with the g++ error:

```
g++: internal compiler error: Killed (program cc1plus)
```

**Comment by bjornfor** [comment]
I get errors like that if my system OOMs (out of memory). Probably this is what happened to you too?

**Comment by joachifm** [comment]
Yes, that's most likely what's happening here.

**Comment by NicolasPetton** [comment]
indeed, that was it. Thank you!
