### ISSUE TITLE
nixos-rebuild --install-bootloader does not reinstall the bootloader

### ISSUE THREAD

**Issue by anund** [NixOS/nixpkgs#144007]
### Describe the bug
Contrary to https://nixos.wiki/wiki/Bootloader#Re-installing_the_bootloader adding `--install-bootloader` to `nixos-rebuild...` does not reinstall the boot loader.

### Steps To Reproduce
1. `sudo nixos-rebuild --install-bootloader switch`

### Expected behavior
nixos-rebuild should print roughly the following
```
Copied "/nix/store/3s1ygbkri8rc2z39cv53z55z4cqldpwq-systemd-247.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/3s1ygbkri8rc2z39cv53z55z4cqldpwq-systemd-247.6/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Random seed file /boot/loader/random-seed successfully written (512 bytes).
Successfully initialized system token in EFI variable with 512 bytes.
Created EFI boot entry "Linux Boot Manager".
```

### Additional context
A [change](https://github.com/NixOS/nixpkgs/commit/ab10bac1b177832b5e6b883ba95bf35f87229267) in ~2019 added `sudo --` as a prefix to various calls including `switch-to-configuration` whenever `$SUDO_USER` is set. This happens for both `sudo nixos-rebuild ...` and when run as `root`. (during the build? process sudo_user is set to root)
`--install-bootloader` relies on  [exporting](https://github.com/NixOS/nixpkgs/blob/ab10bac1b177832b5e6b883ba95bf35f87229267/nixos/modules/installer/tools/nixos-rebuild.sh#L42) `NIX_INSTALL_BOOTLOADER` to communicate through? [switch-to-configuration.pl](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/switch-to-configuration.pl) to [systemd-boot-builder.py](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py#L231). `sudo --` does not preserve `NIX_INSTALL_BOOTLOADER` effectively disabling this option.

### Notify maintainers
@zimbatm ?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.66, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(<user>): `"home-manager"`
 - channels(root): `"nixos-21.11pre325810.2deb07f3ac4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: 
# a list of nixos modules affected by the problem
module:
```

**Comment by anund** [comment]
```git
diff --git a/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh b/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
index 198a6eae600..6928a4734bb 100755
--- a/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
+++ b/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
@@ -127,7 +127,7 @@ while [ "$#" -gt 0 ]; do
 done
 
 if [ -n "$SUDO_USER" ]; then
-    maybeSudo=(sudo --)
+    maybeSudo=(sudo --preserve-env=NIXOS_INSTALL_BOOTLOADER --)
 fi
 
 if [ -z "$buildHost" -a -n "$targetHost" ]; then
```
That will fix the issue for local builds. I'm not sure if `maybeSudo` also needs to be changed when `--use-remote-sudo` is set.

**Comment by doronbehar** [comment]
@anund in 73369f8d0864854d1acfa7f1e6217f7d6b6e3fa1, I see:

https://github.com/NixOS/nixpkgs/blob/73369f8d0864854d1acfa7f1e6217f7d6b6e3fa1/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L131-L133

And at the top of the file:

https://github.com/NixOS/nixpkgs/blob/73369f8d0864854d1acfa7f1e6217f7d6b6e3fa1/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L33-L34

So to what version of the file did you mean to apply that patch?

**Comment by anund** [comment]
@doronbehar https://github.com/NixOS/nixpkgs/pull/144429/files is the associated pr. Both lines you're referencing are part of the change. it used to be ~`maybeSudo=(sudo --)` which cleared the env "unsetting" `NIXOS_INSTALL_BOOTLOADER`

**Comment by anund** [comment]
Bah, Closed via https://github.com/NixOS/nixpkgs/pull/144429
