### ISSUE TITLE
river: Doesn't start 'cause Segmentation fault

### ISSUE THREAD

**Issue by caionoliver** [NixOS/nixpkgs#144129]
The [river](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/window-managers/river/default.nix#L68) doesn't start 'cause probably the wlroots it's causing a compatibility issue. Everytime that i try start river, it doesn't open. I searched on official repository and i found this issue:
https://github.com/riverwm/river/issues/433

The current river's version on nixpkgs repository use **wlroots 0.13.0**, however the available on repository it's **0.14.1**.

Maintainers: @fortuneteller2k @HeavyRain266 @AndersonTorres

**Comment by HeavyRain266** [comment]
I'm not maintainer for months so I don't really care.

**Comment by fortuneteller2k** [comment]
I'll get to updating it in about ~2 hours.
