### ISSUE TITLE
ArchiSteamFarm Out-of-date: 4.3.1.0 -> 5.1.5.2

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#144183]
###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
current version: 4.3.1.0
desired version: 5.1.5.2

###### Notify maintainers
maintainers: @SuperSandro2000 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by IvarWithoutBones** [comment]
I've upgraded the application: https://github.com/IvarWithoutBones/nixpkgs/commit/67452523ae7b4dc94dbd40927e7a08a1acfa59ca. The binary launches, and unit tests succeed but I haven't tested it in any real-world scenarios. If you could confirm this works, I'll PR the change :)

**Comment by VergeDX** [comment]
It works fine for me! Thanks for contribution <3

**Comment by SuperSandro2000** [comment]
Just bump it. I have mine still running in Docker and didn't get around changing that yet.

**Comment by VergeDX** [comment]
https://github.com/NixOS/nixpkgs/pull/145542
