### ISSUE TITLE
I'd like to request the Plaidml python package.

### ISSUE THREAD

**Issue by AtilaSaraiva** [NixOS/nixpkgs#144140]
Hello!

**Project description**
The [PlaidML](https://github.com/plaidml/plaidml) project is an advanced and portable tensor compiler for enabling deep learning on laptops, embedded devices, or other devices where the available computing hardware is not well supported or the available software stack contains unpalatable license restrictions. 

In summary, it is a Keras backend that uses OpenCL instead of Cuda for GPU acceleration. Making it portable across a plethora of devices. I'd like it to be available on the nix repository so that I can use it on reproducible builds.

**Metadata**

* homepage URL: https://plaidml.github.io/plaidml/
* source URL: https://github.com/plaidml/plaidml
* license: Apache-2.0 License
* platforms: Linux, macOS, and Windows

Thx!

**Comment by abathur** [comment]
Closing as a duplicate of:
- https://github.com/NixOS/nixpkgs/issues/97056
