### ISSUE TITLE
CI for static builds

### ISSUE THREAD

**Issue by KAction** [NixOS/nixpkgs#144207]
I fixed static build of opens in [4879ea90342ea3afa4f301b3fab44a8ec3e7c3e7], but as of [31b495592feadb2785279988a2d7db6e2bdd7ed2] it is broken again:

```
...
/nix/store/syy77y0g93whfm2q7vawcgcjby41kwcm-x86_64-unknown-linux-musl-binutils-2.35.1/bin/x86_64-unknown-linux-musl-ld: /nix/store/82y864wrlmlqkw3mmydpkwp20gv0mnqa-libkrb5-1.18-x86_64-u
nknown-linux-musl/lib/libkrb5.a(cc_keyring.o): in function `krcc_generate_new':
/nix/store/syy77y0g93whfm2q7vawcgcjby41kwcm-x86_64-unknown-linux-musl-binutils-2.35.1/bin/x86_64-unknown-linux-musl-ld: /nix/store/82y864wrlmlqkw3mmydpkwp20gv0mnqa-libkrb5-1.18-x86_64-u
nknown-linux-musl/lib/libkrb5.a(cc_keyring.o): in function `krcc_generate_new':
(.text+0x1f00): undefined reference to `keyctl_search'
(.text+0x1f00): undefined reference to `keyctl_search'
/nix/store/syy77y0g93whfm2q7vawcgcjby41kwcm-x86_64-unknown-linux-musl-binutils-2.35.1/bin/x86_64-unknown-linux-musl-ld: (.text+0x1f8a): undefined reference to `add_key'
/nix/store/syy77y0g93whfm2q7vawcgcjby41kwcm-x86_64-unknown-linux-musl-binutils-2.35.1/bin/x86_64-unknown-linux-musl-ld: (.text+0x1f8a): undefined reference to `add_key'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make: *** [Makefile:210: ssh] Error 1
make: *** [Makefile:210: ssh] Error 1
builder for '/nix/store/mwnjzygh8mzw5ils01prfkirbfn8wq16-openssh-static-x86_64-unknown-linux-musl-8.7p1.drv' failed with exit code 2
```

There was quite a refactoring of openssh, according to git-blame, and I am still bisecting it. I'll probably fix it in weeks coming, but real question is to how to make fixed stuff fixed.

As I understand, static builds are not really checked by Hydra, in particular because unknown subset of them actually works.

So here I come with proposal -- export packages that are known to build statically as "static-foo" (subject to bike shedding)
in top-level/all-packages.nix, so we keep track of what is supposed to work and can check whether any particular patch broke it.

Opinions? Better proposals?

**Comment by roberth** [comment]
I'd like for the top-level fixpoint (aka `pkgs`) to remain conceptually simple and relying on non-strictness to work, without prescribing what can _not_ be done, even if that's implicit.
Instead we can add to `pkgs/top-level/release.nix` to describe what _is_ known to work and therefore should keep working.
This is to the degree that the community can realistically support this of course. Perhaps that expression could alter the `meta` to set or add specific maintainers to individual packages.
Currently only `stdenv` is listed.

**Comment by jonringer** [comment]
add a `passthru.tests.static = pkgsStatic.openssl` would probably help. At least ofborg would at least error if the build broke.
