### ISSUE TITLE
Skype produces no sound in 16.03

### ISSUE THREAD

**Issue by kototama** [NixOS/nixpkgs#14427]
## Issue description

Skype does not produce any sounds in NixOS 16.03.
### Steps to reproduce

Starts skype from the command line or menu. No sound is emitted after entering login or when calling the Skype test account.
## Technical details

```
$ nixos-version 
16.03.498.f8a5d1e (Emu)

$ nix-env --version
nix-env (Nix) 1.11.2

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.498.f8a5d1e"
```
## Workaround

Installing `apulse` and running `apulse skype` works.
## Related issues

Maybe related to #13895

**Comment by puffnfresh** [comment]
It ciuld be useful to have a wrapper to check if PulseAudio is running and otherwise using 32-bit apulse.

**Comment by grahamc** [comment]
On 16.03.503.3f96280 my skype works fine.

**Comment by pSub** [comment]
Closing, please reopen if this is still a problem for you in release 16.09.
