### ISSUE TITLE
Nix installer breaks ~/.profile by adding `-e` on a separate line

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#144288]
### Describe the bug

The Nix installer introduces some buggy code into ~/.profile in a vanilla Ubuntu 20.04 VM.

### Steps To Reproduce
1. `vagrant init generic/ubuntu2004`
2. `vagrant up --provider=libvirt`
3. `vagrant ssh`
4. (Note the contents of ~/.profile)
5. `sh <(curl -L https://nixos.org/nix/install)`
6. `exit`
7. `vagrant ssh`

### Expected behavior

The shell within Vagrant should start up without issue.

### Actual behavior

```console
$ vagrant ssh
Last login: Tue Nov  2 21:45:23 2021 from 192.168.121.1
-e: command not found
```

### Screenshots

![Screenshot from 2021-11-03 10-50-02](https://user-images.githubusercontent.com/168301/139956692-20585272-2410-41c4-a135-e372c51f0593.png)

### Additional context

In case it's relevant, I'm running Bash within KiTTY: `kitty bash`.

Workaround: Remove the line with just `-e` from ~/.profile.

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.05.3980.f0869b1a2c0 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3980.f0869b1a2c0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by andersk** [comment]
See NixOS/nix#5458.
