### ISSUE TITLE
kube3d missing arm platforms

### ISSUE THREAD

**Issue by ricochet** [NixOS/nixpkgs#144326]
**Project description**
k3d creates containerized k3s clusters. This means, that you can spin up a multi-node k3s cluster on a single machine using docker.

This package already exists in nix but is missing arm and darwin platforms.

Rancher does support darwin and arm as a target: https://github.com/rancher/k3d/releases/tag/v5.0.3

- k3d-darwin-amd64
- k3d-linux-arm64

https://github.com/NixOS/nixpkgs/blob/a0dbe47318bbab7559ffbfa7c4872a517833409f/pkgs/applications/networking/cluster/kube3d/default.nix

Missing:

- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin

**Comment by Artturin** [comment]
the assets are binaries not source code

aarch64-linux already works 

for darwin we need to change the platforms.linux to platforms.unix

**Comment by 06kellyjac** [comment]
If someone is up for testing it on aarch64-darwin semi-regularly I'm happy to swap the platform

**Comment by ricochet** [comment]
I can test semi-regularly. M1 is my main development env and this is a primary dependency for my work.

**Comment by 06kellyjac** [comment]
Cool, thanks. Ill get that swapped out
