### ISSUE TITLE
Tree-sitter grammars cannot be built on Mac OS due to differences with `strip`

### ISSUE THREAD

**Issue by sutherlanda** [NixOS/nixpkgs#144354]
### Describe the bug

Building tree-sitter grammars on MacOS results in a fatal error with the post-installation fixup stage due to differences in how `strip` is invoked on MacOS. The error reported is:

```
error: builder for '/nix/store/j8llfsdl9vbvh8dxvnmzqfji5bg5f7ns-tree-sitter-c-grammar-0.20.0.drv' failed with exit code 1;
       last 5 log lines:
       > patching sources
       > building
       > installing
       > post-installation fixup
       > fatal error: strip: no files specified
       For full logs, run 'nix log /nix/store/j8llfsdl9vbvh8dxvnmzqfji5bg5f7ns-tree-sitter-c-grammar-0.20.0.drv'.
```

### Steps To Reproduce
1. Run `nix-shell -p pkgs.tree-sitter.builtGrammars.tree-sitter-c` or with any other tree-sitter grammar.
2. Observe the fatal error in the post-installation fixup phase where it reports that no files are specified for `strip`.

### Expected behavior
The grammar should build and execute the fixup phase without errors.

### Additional context
This error does not occur on non-MacOS platforms. I reproduced the error on MacOS 12.0.1.

I suspect this error was introduced with this commit https://github.com/NixOS/nixpkgs/commit/3d313212052b415695de4a0737d4dad6c24bd6e4 but I'm not 100% sure.

### Notify maintainers
@oxalica 

### Metadata
```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20211001_4f49615`
 - channels(andrewsutherland): `"darwin, home-manager, nixpkgs-21.11pre326916.7053541084b"`
 - channels(root): `"nixpkgs-21.11pre326916.7053541084b"`
 - nixpkgs: `/Users/andrewsutherland/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by r-burns** [comment]
Some discussion: https://github.com/NixOS/nixpkgs/pull/143703#issuecomment-955992729

**Comment by siraben** [comment]
I can also replicate this with `nix-build -A pkgs.tree-sitter.builtGrammars.tree-sitter-c`.
