### ISSUE TITLE
Distribute Lidarr with .NET runtime

### ISSUE THREAD

**Issue by elvetemedve** [NixOS/nixpkgs#144456]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: nixpkgs.lidarr

current version: 0.8.1.2135 (with Mono 6.12.0.122)
desired version: 0.8.1.2135 (with .NET 5.0.10)

###### Notify maintainers

maintainers:
@etu @r-ryantm 

###### Note for maintainers

The current version of this package raises a warning in Lidarr about the switch from the Mono dependency to .NET.
![screenshot-2021 11 03-14_49_44](https://user-images.githubusercontent.com/596431/140073638-91879616-88f5-4451-b042-9f72bdfc24a8.png)

It's not only a warning that can be ignored, but certain functions of Lidarr is broken. For example adding indexers relaying on Let's Encrypt certificates.
![screenshot-2021 11 03-14_52_16](https://user-images.githubusercontent.com/596431/140073866-cba241e2-e556-4098-a7b8-f156422eeeba.png)

There is an open bug report at Mono about the certificate issue here: https://github.com/mono/mono/issues/21233

So the future proof fix would be compile the code with .NET.

Please tag this issue in your PR.

**Comment by JamieMagee** [comment]
Completed in #192888
