### ISSUE TITLE
Bitwarden package out-of-date

### ISSUE THREAD

**Issue by Schmensch** [NixOS/nixpkgs#144497]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: bitwarden

current version: 1.28
desired version: 1.29

###### Notify maintainers

maintainers: @Kiwi 

###### Note for maintainers

Maybe add support to use system electron via an override, as Bitwarden currently ships with Electron 11, which is severly outdated.

Edit: bitwarden not bitwarden-cli.

**Comment by prusnak** [comment]
Update in https://github.com/NixOS/nixpkgs/pull/144524
