### ISSUE TITLE
neovim: doesn't compile due to broken luajit/lpeg

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#14442]
## Issue description
Compilation of neovim fails finding luajit with lpeg

```
-- Checking Lua interpreter /nix/store/crrdz73q5pbgaj4dai816jf0hwg3ls1v-luajit-2.1.0-beta1/bin/luajit
-- [/nix/store/crrdz73q5pbgaj4dai816jf0hwg3ls1v-luajit-2.1.0-beta1/bin/luajit] The 'lpeg' lua package is required for building Neovim
-- Checking Lua interpreter /nix/store/crrdz73q5pbgaj4dai816jf0hwg3ls1v-luajit-2.1.0-beta1/bin/lua
-- [/nix/store/crrdz73q5pbgaj4dai816jf0hwg3ls1v-luajit-2.1.0-beta1/bin/lua] The 'lpeg' lua package is required for building Neovim
CMake Error at CMakeLists.txt:372 (message):
  A suitable Lua interpreter was not found.
```

### Steps to reproduce
Happens on PR #13575 and locally for the same commit.

## Technical details

* System: 16.09.git.4f3efd4M (Flounder
* Nix version: 1.11.2
* Nixpkgs version: See #13575

/cc @jagajaga @garbas

**Comment by aneeshusa** [comment]
As a temporary workaround, reordering `buildInputs` so that `luajit` is after `lua` instead of before fixes this for me. I don't think is a proper fix though.

**Comment by steveeJ** [comment]
@aneeshusa I can confirm that reordering solves the problem, but I don't feel comfortable calling this a proper solution either.

**Comment by the-kenny** [comment]
Why is order important here? Has anyone investigated this further?

**Comment by the-kenny** [comment]
Right now I'm inclined to commit this fix to make neovim work again but keep this issue open with the details. Anyone voting against this?

**Comment by aneeshusa** [comment]
Looks like this got fixed properly in https://github.com/NixOS/nixpkgs/commit/e0884e85cfc2634aeb2d7456f9e0cf6b7dc3b945.

**Comment by the-kenny** [comment]
yay!

**Comment by teto** [comment]
I've just had the same message, seems like the order was reversed afterwards in e0884e85cfc2634aeb2d7456f9e0cf6b7dc3b945

It works with
```
diff --git a/pkgs/applications/editors/neovim/default.nix b/pkgs/applications/editors/neovim/default.nix
index ca915b3..5c3597f 100644
--- a/pkgs/applications/editors/neovim/default.nix
+++ b/pkgs/applications/editors/neovim/default.nix
@@ -99,8 +99,8 @@ let
       ncurses
       neovimLibvterm
       unibilium
-      luajit
       luaPackages.lua
+      luajit
       gperf
     ] ++ optional withJemalloc jemalloc
       ++ lualibs;
```
but this is not a good patch. I believe the order doesn't matter, but lua libraries != luajit libraries so the package would need both, see https://github.com/neovim/neovim/issues/930 

Technical details:

    System: (NixOS: nixos-version): 17.03.1596.8d9c8383f9 (Gorilla)
    Nix version: (run nix-env --version): nix-env (Nix) 1.11.11
    Nixpkgs version: (run nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion) 17.03.1596.8d9c8383f9
    Sandboxing enabled: (run grep build-use-sandbox /etc/nix/nix.conf) false
