### ISSUE TITLE
Our swap creation uses fallocate, against the suggestion of man swapon

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#144572]
https://github.com/NixOS/nixpkgs/blob/42e9ec0c3962c4070a13ff7c403d5cde0b6237ae/nixos/modules/config/swap.nix#L217

https://man7.org/linux/man-pages/man8/swapon.8.html

> Files with holes
>     The swap file implementation in the kernel expects to be able to write to the file directly, without the assistance of the filesystem.  This is a problem on files with holes or on copy-on-write files on filesystems like Btrfs.
>
>    Commands like cp(1) or truncate(1) create files with holes.  These files will be rejected by swapon.
>
>    Preallocated files created by fallocate(1) may be interpreted as files with holes too depending of the filesystem.  Preallocated swap files are supported on XFS since Linux 4.18.
>
>    The most portable solution to create a swap file is to use dd(1) and /dev/zero.

We could also only `fallocate` on filesystems where it's sure to work.

(Just on this topic, we should probably `chattr +C` too if possible)

CC @abbradar as the person behind the most changed lines in `swap.nix`

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/91986

**Comment by expipiplus1** [comment]
Ah, theres even a comment there with the same man page text! Closing in favor of that one.
