### ISSUE TITLE
sslscan expression produces empty output on darwin 

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#14457]
## Issue description

On `ad8857a81a05062ef8b9dd622f426a27662d1551`, the `sslscan` expression produces empty output on Darwin.
### Steps to reproduce

```
$ git rev-parse HEAD
ad8857a81a05062ef8b9dd622f426a27662d1551
$ nix-build -A sslscan
/nix/store/s4qq3g5z1qsm3nnm14bygmml7pl0z11l-sslscan-1.11.0
$ ls -l /nix/store/s4qq3g5z1qsm3nnm14bygmml7pl0z11l-sslscan-1.11.0
$
```
## Technical details
- System: Darwin
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: ad8857a81a05062ef8b9dd622f426a27662d1551 (from git)

**Comment by matthewbauer** [comment]
No longer happening.
