### ISSUE TITLE
zoom-us: no webcam video after 5.7.29123.0808

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#144562]
### Describe the bug
The video feed from the webcam is black, both on a call and in settings.

### Steps To Reproduce
1. Open Zoom
2. Settings > Video
3. Video feed is black

### Expected behavior
Zoom can display the feed from the webcam.

### Screenshots
![Screenshot from 2021-11-03 17-18-59](https://user-images.githubusercontent.com/166791/140232568-f9a2236c-6667-40a0-aa4c-ae25736c1467.png)

### Additional context
Versions later than 5.7.29123.0808 all have the problem. Running this version from a previous profile works, and so does adding an overlay to revert the version:
```nix
self: super:
{
  zoom-us = super.zoom-us.overrideAttrs (old: rec {
    version = "5.7.29123.0808";

    src = self.fetchurl {
      url = "https://zoom.us/client/${version}/zoom_x86_64.pkg.tar.xz";
      sha256 = "WAeE/2hUaQbWwDg/iqlKSZVoH3ruVHvh+9SEWdPwCIc=";
    };
  });
}
```
Running the executable from the terminal doesn't produce any messages. The only entries in the systemd journal are like this:
```
Nov 03 17:18:34 host systemd[3021]: app-gnome-Zoom-478411.scope: Succeeded.
```
Other programs (eg guvcview, MS Teams) are able to use the webcam successfully.

### Notify maintainers
@danbst @tadfisher @doronbehar
@emmanuelrosa @LutzCle

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.71, NixOS, 21.05.3990.372e59d2af7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre-rc1`
 - channels(root): `"nixos-21.05.3990.372e59d2af7"`
 - channels($USER): `"nixpkgs-21.11pre327669.b67e752c29f"`
 - nixpkgs: `~/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by doronbehar** [comment]
Can't reproduce here with Gnome. Could be an issue with your camera..

**Comment by LutzCle** [comment]
I've experience the same issue in recent versions. Sometimes the video stream works, at other times it's black. Disabling virtual backgrounds seems to help.

@neilmayhew Have you tried reporting this upstream?

**Comment by jshcmpbll** [comment]
Funny.. I came looking for this same issue but for MS Teams 🤔 Zoom works fine for me running 5.8.6.739 but teams shows the same.. Just a black box. I assume you were unable to resolve this issue, right @neilmayhew ?

**Comment by neilmayhew** [comment]
@jshcmpbll I've been using the old version (5.7.29123.0808) via an overlay and hadn't bothered to check whether the problem has gone away. It's working for me now with 5.9.1.1380 and 5.8.3.145, so I think this issue can be closed.

I don't have much of a problem with Teams. My only issue is that every so often it switches the camera off and on again, and loses my preconfigured camera zoom settings (made with guvcview). It will then do the same thing a few minutes later and the correct zoom level comes back. It's annoying, but not terrible. I'm using 1.4.00.26453 currently.
