### ISSUE TITLE
Add Dart Sass

### ISSUE THREAD

**Issue by BD103** [NixOS/nixpkgs#144600]
**Project description**
Dart Sass is a faster and more updated version of the Sass compilers Nix already supplies. Technically `nodePackages.sass` works, but it is [very slow in comparison](https://github.com/sass/dart-sass/blob/main/perf.md).

**Metadata**

* homepage URL: https://sass-lang.com
* source URL: https://github.com/sass/dart-sass
* license: [MIT](https://github.com/sass/dart-sass/blob/main/LICENSE)
* platforms: Linux ia32 and x64, MacOS x64, and Windows ia32 and x64. You can also compile the source with [Dart's SDK](https://dart.dev/get-dart).

**Comment by 06kellyjac** [comment]
I think `nodePackages.sass` is now using `dart-sass`

```
    "sass-1.32.12" = {
      name = "sass";
      packageName = "sass";
      version = "1.32.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.32.12.tgz";
        sha512 = "zmXn03k3hN0KaiVTjohgkg98C3UowhL1/VSGdj4/VAAiMKGQOE80PFPxFP2Kyq0OUskPKcY5lImkhBKEHlypJA==";
      };
    };
    "sass-1.55.0" = {
      name = "sass";
      packageName = "sass";
      version = "1.55.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.55.0.tgz";
        sha512 = "Pk+PMy7OGLs9WaxZGJMn7S96dvlyVBwwtToX895WmCpAOr5YiJYEUJfiJidMuKb613z2xNWcXCHEuOvjZbqC6A==";
      };
    };
```

see homepage:
https://registry.npmjs.org/sass/

**Comment by BD103** [comment]
Yes, technically `nodePackages.sass` is compiled from dart-sass, but it is in a pure-Javascript form. One of the items in the [performance comparison](https://github.com/sass/dart-sass/blob/main/perf.md) is how the native executable of dart-sass is so much faster than the Javascript form.

The reason I created this was so that the native executable would be added to Nix packages.

**Comment by dmarcoux** [comment]
Are there other Dart packages in nixpkgs which we could use as a reference to package dart-sass?

**Comment by jnsaff** [comment]
Here's an example getting it in nix-shell. https://swwritings.com/post/2022-07-27-nixos-phoenix-and-sass
