### ISSUE TITLE
python3Packages.packaging is out of date

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#144678]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: python3Packages.packaging

current version: 20.9
desired version: 21.2

###### Notify maintainers

maintainers: @bennofs 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment]
#152550
