### ISSUE TITLE
Package request: invoiceplane (web app)

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#144606]
**Project description**
Web application for creating and managing invoices.

**Metadata**

* homepage URL: https://www.invoiceplane.com/
* source URL: https://github.com/InvoicePlane/InvoicePlane
* license: custom
* platforms: linux

**Comment by aanderse** [comment]
Looks like that hasn't been updated in 2 years. Maybe you could give this one a try instead: https://github.com/NixOS/nixpkgs/pull/141822

**Comment by onny** [comment]
> Looks like that hasn't been updated in 2 years. Maybe you could give this one a try instead: #141822

Thanks for the hint. Looks promising. Invoiceplane still works with the latest PHP version but of course it looks discontinued. Closing this issue for now.
