### ISSUE TITLE
crti.o: No such file or directory

### ISSUE THREAD

**Issue by fkarg** [NixOS/nixpkgs#144615]
Not sure if this is the right place, but I'm honestly stumped at this point.

### Describe the bug
`pip install fava-investor` fails (even in a virtual environment) due to `ld`/`gcc` not finding `crti.o`. It [seems like the solution for debian](https://stackoverflow.com/questions/6329887/compiling-problems-cannot-find-crt1-o) is to `install gcc-multilib`. I have no idea what the corresponding package for `nix` would be.

### Steps To Reproduce
1. `pip install fava-investor`

### Expected behavior
Successful installation of the python package (in virtual environment or not). Also, a tool to map missing library files to `nix`-packages would be awesome.

I've only recently begun using `nix-shell`, so I'm not sure if that'd even be the way to go. Please do tell me, I'd like to get this to work.

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.66, NixOS, 21.05.3915.95eed9b64ee (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3915.95eed9b64ee"`
 - channels(pars): `"nixos-21.05.3990.372e59d2af7, nixpkgs-21.11pre327669.b67e752c29f"`
 - nixpkgs: `/home/pars/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by Artturin** [comment]
https://github.com/bennofs/nix-index
```
...
glibc.out                                         2,768 r /nix/store/mij848h2x5wiqkwhg027byvmf9x3gx7y-glibc-2.33-50/lib/crti.o
glibc_multi.out                                       0 s /nix/store/dn1c6x2s1fll9qm261bnzqc32w3klv2m-glibc-multi-2.33-50/lib/crti.o
...
```

**Comment by applePrincess** [comment]
As an working example would be

```nix
with import <nixpkgs> {};
mkShell {
  buildInputs = [ python3 gcc ];
}
```

above `shell.nix` and run nix-shell.
within nix-shell run

```sh
python3 -m venv venv
. venv/bin/activate
pip3 install fava-investor 
```
will install fava-investor successfully.

**Comment by fkarg** [comment]
Yeah that works, thank you very much.
