### ISSUE TITLE
kubens

### ISSUE THREAD

**Issue by arbourd** [NixOS/nixpkgs#144660]
**Project description**

kubens is a tool used to switch kubernetes namespaces. it is apart of the kubectx repo, which [nix provides](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/kubectx/default.nix).

question is: should it be added as its own package `../tools/kubens/default.nix` or a part of kubectx? 

**Metadata**

* homepage URL: https://github.com/ahmetb/kubectx
* source URL: https://github.com/ahmetb/kubectx
* license: asl20
* platforms: unix, linux, darwin

**Comment by kira-bruneau** [comment]
@arbourd It looks like kubens is already provided in the kubectx package:
```
nix shell nixpkgs#kubectx -c kubectx --help
```
