### ISSUE TITLE
ZERO Hydra Failures 21.11

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixpkgs#144627]
## Mission
Every time we branch off a release we stabilize the release branch.
Our goal here is to get as little as possible jobs failing on the trunk/master jobsets.
I'd like to heighten, while it's great to focus on zero as our goal, it's essentially to 
have all deliverables that worked in the previous release work here also.

Please note the changes included in [RFC 85](https://github.com/NixOS/rfcs/blob/master/rfcs/0085-nixos-release-stablization.md).

Most significantly, branch off will occur on 2021 Nov 19; prior to that date, ZHF will be conducted
on master; after that date, ZHF will be conducted on the release channel using a backport
workflow similar to previous ZHFs.

## Jobsets

[nixos:release-21.11 Jobset](https://hydra.nixos.org/jobset/nixos/release-21.11)
[nixpkgs:nixpkgs-21.11-darwin Jobset](https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-21.11-darwin)

## How many failing jobs are there?
At the opening of this issue we have
- the main `x86_64-linux` jobset at [**653**](https://hydra.nixos.org/eval/1718945?filter=x86_64-linux&compare=1718890&full=#tabs-still-fail) failing jobs
- `x86_64-darwin` at [**1449**](https://hydra.nixos.org/eval/1718945?filter=x86_64-darwin&compare=1718890&full=#tabs-still-fail)
- `aarch64-linux` at [**782**](https://hydra.nixos.org/eval/1718945?filter=aarch64-linux&compare=1718890&full=#tabs-still-fail)

Thanks to [nix-review-tools](https://github.com/nix-community/nix-review-tools) we know which dependencies are causing the most jobs to fail in these individual jobsets:

- [nixos:trunk-combined](https://tomberek.info/eval_reports/1718946.html)
- [nixpkgs:trunk](https://tomberek.info/eval_reports/1718945.html)
- https://tomberek.info/eval_reports/1723307.html

### Previous releases first evals
[20.09](https://hydra.nixos.org/eval/1570712) had **1153** failing jobs
[21.05](https://hydra.nixos.org/eval/1668017) had **789** failing jobs

## How to help (textual)
1. Select an evaluation of the [trunk jobset](https://hydra.nixos.org/jobset/nixpkgs/trunk)
![Screenshot](https://user-images.githubusercontent.com/7673602/117478795-701baa00-af14-11eb-8a82-8a846b464cce.png)

2.  Find a failed job ❌️ , you can use the filter field to scope packages to your platform, or search for packages that are relevant to you.
![Screenshot from 2020-02-08 15 26 47](https://user-images.githubusercontent.com/28888242/74192277-3978b600-4c23-11ea-9f35-19a3988dd502.png)
Note: you can filter for architecture by filtering for it, eg: https://hydra.nixos.org/eval/1719540?filter=x86_64-linux&compare=1719463&full=#tabs-still-fail

3. Search to see if a PR is not already open for the package. It there is one, please help review it.

4. If there is no open PR, troubleshoot why it's failing and fix it.

5. Create a Pull Request with the fix targeting master, wait for it to be merged. 
If your PR causes around 500+ rebuilds, it's preferred to target `staging` to avoid compute and storage churn.

6. (after 2021 Nov 19) Please follow [backporting steps](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes) and target the `release-21.11` branch if the original PR landed in `master` or `staging-21.11` if the PR landed in `staging`. Be sure to do `git cherry-pick -x <rev>` on the commits that landed in unstable. @jonringer created [a video covering the backport process](https://www.youtube.com/watch?v=4Zb3GpIc6vk&t=520s).

Always reference this issue in the body of your PR:
```
ZHF: #144627
```

Please ping @NixOS/nixos-release-managers on the PR.
If you're unable to because you're not a member of the NixOS org please ping @jonringer, @tomberek , @nrdxp

## How can I easily check packages that I maintain?
You're able to check failing packages that you maintain by running:
```
# from root of nixpkgs
nix-build maintainers/scripts/build.nix --argstr maintainer <name>
```

## New to nixpkgs?
- [Packaging a basic C application](https://www.youtube.com/watch?v=LiEqN8r-BRw)
- [Python nix packaging](https://www.youtube.com/watch?v=jXd-hkP4xnU)
- [Adding a package to nixpkgs](https://www.youtube.com/watch?v=fvj8H5yUKu8)
- other resources at: https://github.com/nix-community/awesome-nix
- https://nix.dev/tutorials/

## Packages that don't get fixed
The remaining packages will be marked as broken before the release (on the failing platforms).
You can do this like:
```nix
meta = {
  # ref to issue/explanation
  # `true` is for everything
  broken = stdenv.isDarwin; 
};
```

## Closing
This is a great way to help NixOS, and it is a great time for new contributors to start their nixpkgs adventure.  :partying_face: 

cc @NixOS/nixpkgs-committers @NixOS/nixpkgs-maintainers @NixOS/release-engineers 

## Related Issues
- Timeline: [Discourse: 21.11 Release Timeline](https://discourse.nixos.org/t/lets-have-a-great-21-11-release-cycle/15262)
- Feature Freeze Items: ##140168

**Comment by nixinator** [comment]
Be nice to get @ryantm to run this report,, so we can find out the packages/dependencies  thar are that are causing the most failures.

https://discourse.nixos.org/t/finding-most-depended-upon-packages-that-fail-to-build-in-hydra/10090

**Comment by nrdxp** [comment]
@nixinator, @tomberek already ran this report during a meeting we just had and posted it under his personal domain. Not sure if he posted it up above and you just missed it or if he forgot to post it though.

**Comment by fabianhjr** [comment]
> Create a Pull Request with the fix targeting master, wait for it to be merged. If your PR causes around 500+ rebuilds, it's preferred to target staging to avoid compute and storage churn.

Hey, there had been some discussion about non-breaking (particularly unbreaking/fixing) commits going directly to `staging-next` rather than `staging`. Mentioning since any unbreaking changes targeting `staging` might miss the branch off of the 19th of November.

Eg, #137501

**Comment by legendofmiracles** [comment]
Can this issue be pinned?

**Comment by GuillaumeDesforges** [comment]
Can we search jobs based on package maintainers? I'd like to quickly check the ones I am maintainer of.

**Comment by dramaturg** [comment]
> Can we search jobs based on package maintainers? I'd like to quickly check the ones I am maintainer of.

This snippet might be what you are looking for:
`nix-shell maintainers/scripts/check-hydra-by-maintainer.nix --argstr maintainer dramaturg`

There is also another script to run a build of all your packages:
`nix-build maintainers/scripts/build.nix --argstr maintainer dramaturg`

**Comment by Ma27** [comment]
`nix-shell maintainers/scripts/check-hydra-by-maintainer.nix --argstr maintainer ma27`

Also there's a pending PR to directly integrate this into Hydra: https://github.com/NixOS/hydra/pull/743

**Comment by 06kellyjac** [comment]
@dramaturg `nix-shell maintainers/scripts/check-hydra-by-maintainer.nix --argstr maintainer dramaturg` is very very nice but does it only check `x86_64_linux` or does it only check the host you're on (which in my case is also `x86_64_linux`)?

**Comment by dramaturg** [comment]
> @dramaturg `nix-shell maintainers/scripts/check-hydra-by-maintainer.nix --argstr maintainer dramaturg` is very very nice but does it only check `x86_64_linux` or does it only check the host you're on (which in my case is also `x86_64_linux`)?

True. I just found out you can pass the architecture to `hydra-check` - so if you take the `nix-shell` command printed by the script and add an argument you can check other archs:
```
$ nix-shell -p hydra-check --run "hydra-check --arch=aarch64-linux openssl openttd"
Build Status for nixpkgs.openssl.aarch64-linux on unstable
✔ openssl-1.0.2q from 2018-12-22 - https://hydra.nixos.org/build/86211048
Build Status for nixpkgs.openttd.aarch64-linux on unstable
✔ openttd-1.8.0 from 2018-12-22 - https://hydra.nixos.org/build/86224141
```
(note those quotes)
((or amend the script to include that argument))

**Comment by Synthetica9** [comment]
nix-build maintainers/scripts/build.nix --argstr maintainer synthetica --argstr crosssytem "aarch64-linux"

Seems to work.

**Comment by 06kellyjac** [comment]
I've gone into `maintainers/scripts/check-hydra-by-maintainer.nix` and added `--arch=aarch64-linux` which works

Although I get a bunch of `⚠ This job is not a member of the latest evaluation of its jobset. This means it was removed or had an evaluation error.` but manually checking https://hydra.nixos.org/eval/1719259?filter=afetch&compare=1719196&full=#tabs-still-succeed mostly looks fine. I guess we can discuss this further in another issue at some point

**Comment by asymmetric** [comment]
@tomberek can you add that it's possible to filter jobs by arch by typing the arch in the "search field" in an eval page?

I had some more feedback on the previous ZHF effort [here].

**Comment by newAM** [comment]
For the future, is there a way to sign up for emails when a package I maintain fails to build in hydra?

**Comment by jonringer** [comment]
@newAM there was many years ago, but it was disabled because of a high noise to signal ratio

**Comment by Anton-Latukha** [comment]
> For the future, is there a way to sign up for emails when a package I maintain fails to build in hydra?

It should be not that hard to program.

Hydra has threads/package statuses: https://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.ghc.x86_64-linux#tabs-status
And an API, which description information is scattered in documentation: https://hydra.nixos.org/build/157495504/download/1/hydra/notifications.html
`Hydra-API` library in Haskell: https://github.com/triloxy/hydra-api
Hydra has a plugin system: https://github.com/NixOS/hydra/tree/master/src/lib/Hydra/Plugin
It is mainly in Perl. But relatively readable.
Posts the status of the build this thing: https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/Event/BuildFinished.pm

& it has Prometheus integration, so Hydra API is compatible with Prometheus API, which can also be (tried) to retrieve info through Prometheus API way.

If web address hooks to retrieve status - exist (and form of them found), or made provided & documented - it would be easy to setup even IFTTT - it has webhook support & so here you go - automate any action on return status through IFTTT, even an Android notification if one wants.

**Comment by tomberek** [comment]
Let's take a look at the newly failing jobs:
- https://hydra.nixos.org/eval/1719835?filter=x86_64-linux&compare=1718890&full=#tabs-now-fail  
- https://hydra.nixos.org/eval/1719835?filter=x86_64-darwin&compare=1718890&full=#tabs-now-fail  
- https://hydra.nixos.org/eval/1719835?filter=aarch64-linux&compare=1718890&full=#tabs-now-fail

x86_64-linux seems to need ceph work
x86_64-darwin needs arrow-cpp
aarch64-linux  needs .... perhaps a restart on the jobs

**Comment by domenkozar** [comment]
I've created [a call for darwin maintainers](https://github.com/NixOS/nixpkgs/issues/145230) to also help out with ZHF.

**Comment by sternenseemann** [comment]
Quick note regarding Haskell: If you end up looking at any Haskell packages, please remember to target your PRs against `haskell-updates`.

**Comment by kira-bruneau** [comment]
Is there a good way to reproduce the environment Hydra uses for macOS builds? I've been frequently seeing different errors from Hydra & cases where I can build the package locally, but Hydra fails (eg. texlab, minetest, ...).

**Comment by toonn** [comment]
@kira-bruneau, IME, especially with Python that usually comes down to the Hydra builders using HFS+, which is case-insensitive and uses unicode normal form D (NFD). So anything where unicode strings are compared to file names can be tedious.

**Comment by tobim** [comment]
> ...
>  x86_64-darwin needs arrow-cpp

I believe this has been fixed as part of https://github.com/NixOS/nixpkgs/pull/144610.

**Comment by balsoft** [comment]
https://hydra.nixos.org/build/158386594

Seems like this failure is strange, since we could build it locally.

[#zhfmsk](https://nixhax.github.io/zhf-21.11/index.en.html)

**Comment by nixinator** [comment]
> https://hydra.nixos.org/build/158386594
> 
> Seems like this failure is strange, since we could build it locally.
> 
> [#zhfmsk](https://nixhax.github.io/zhf-21.11/index.en.html)

is it a out of memory condition on the builder (OOM killer) ...

**Comment by balsoft** [comment]
https://hydra.nixos.org/build/158397595

This seems like a really strange failure: the job is failed, but the build result is available in cache

```
nix build /nix/store/zc3v69cd7383gw6dciv16farq5mr9nd4-rygel-0.40.2
```

succeeds.

**Comment by risicle** [comment]
@tomberek requesting a new evals report (preferably from a completed eval)

**Comment by jonringer** [comment]
> @tomberek requesting a new evals report (preferably from a completed eval)

hydra has been lacking in resources, not many x86_64-linux builds have been completed in the last 24 hours. Situation should improve soon.

**Comment by jonringer** [comment]
For next ZHF, we should probably make a `nixos/eval-reports` repo, which has some CI around generating the reports each time a new eval gets started

**Comment by wamserma** [comment]
> For next ZHF, we should probably make a `nixos/eval-reports` repo, which has some CI around generating the reports each time a new eval gets started

Don't know how expensive that is, but it might be useful for keeping things green 'round the year (so we can get into some sort of permanent ZHF state).

**Comment by smancill** [comment]
I created #146494 and #146667 to fix these darwin builds on Hydra, where the tests cannot write to `/tmp`:

- proj: https://hydra.nixos.org/build/158283234
- m3u8: https://hydra.nixos.org/build/157643942

But now I found that a few days before they were working (the logical conclusion is that `/tmp` was writable)

- proj: https://hydra.nixos.org/build/158006302
- m3u8: https://hydra.nixos.org/build/157042319

Then, what's the environment on Hydra? I cannot find any information, or I don't know where to search. Is `/tmp` writable and there was a configuration error, or it's not supposed to be writable?

**Comment by mweinelt** [comment]
> @tomberek requesting a new evals report (preferably from a completed eval)

Latest somewhat complete eval: https://shells.darmstadt.ccc.de/~hexa/1723396.html

**Comment by smancill** [comment]
> > @tomberek requesting a new evals report (preferably from a completed eval)
> 
> Latest somewhat complete eval: https://shells.darmstadt.ccc.de/~hexa/1723396.html

proj, which is listed as the second most complicated dependency, is fixed on darwin now: https://hydra.nixos.org/build/158869394

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/146719

**Comment by tomberek** [comment]
Next eval:
https://tomberek.info/eval_reports/1724022.html

**Comment by cab404** [comment]
flexget, osmscout-server and luabind just need a restart, they build fine.

**Comment by cab404** [comment]
same with soi and osrm-backend

**Comment by dasJ** [comment]
@cab404 Restarted them all, soi on aarch64-linux was successful this time

**Comment by risicle** [comment]
I think the same might be true for `apacheHttpdPackages.php` on darwin x86_64 and aarch64 linux. I can't reproduce the failures we're seeing there.

**Comment by dasJ** [comment]
Happily restarted them, one of them (don't remember which one) finished successfully

**Comment by risicle** [comment]
Another one for the list: `gdc` on darwin.

**Comment by smancill** [comment]
Sorry for the late set of PR with darwin fixes, but I wanted to try if they can make it before the release branch is created. I will stop now.

**Comment by risicle** [comment]
Don't stop we can always backport.

**Comment by Artturin** [comment]
@smancill if possible could you submit some of the fixes to the packages upstream repo?

with the gh cli its fast to fork and clone a repo `gh repo fork https://github.com/Nefelim4ag/Ananicy`
https://cli.github.com/

**Comment by smancill** [comment]
> @smancill if possible could you submit some of the fixes to the packages upstream repo?

I sent one, I may send a couple more.

Here is the list of packages in my PR that required to be patched in order to work on darwin, if somebody else wants to help:

- [python3Packages.ledgerwallet](https://github.com/NixOS/nixpkgs/pull/146447): It can be sent to upstream (although upstream resolved it by pinning a dependency)
- [python3Packages.pdftotext](https://github.com/NixOS/nixpkgs/pull/146519): We may request upstream to not hardcode the `brew` command (the cause of the error)
- [convbin](https://github.com/NixOS/nixpkgs/pull/146529): This is a nixpkgs-only patch, nothing to send to upstream.
- [lrzip](https://github.com/NixOS/nixpkgs/pull/146662): Homebrew is also patching it. There is an open issue about it but not much done. It needs a proper patch to `configure.ac`.
- [masscan](https://github.com/NixOS/nixpkgs/pull/146664): This is a nixpkgs-only patch, nothing to send to upstream.
- [python3Packages.m3u8](https://github.com/NixOS/nixpkgs/pull/146667): We may send a PR to use a proper temp dir instead of hardcoded `/tmp`.
- [apache-airflow](https://github.com/NixOS/nixpkgs/pull/146715): Temp dir already patched upstream, but when I tried to bump the version I found that the tarball now has no tests, so I just patched it manually.
- [fluent-bit](https://github.com/NixOS/nixpkgs/pull/146832): Already sent calyptia/cmetrics#57. I can open a follow-up PR to use upstream patch later.
- [python3Packages.pyahocorasick](https://github.com/NixOS/nixpkgs/pull/146838):  We may send a PR to use a proper temp dir instead of hardcoded `/dev/shm` or `/tmp`.
- [arj](https://github.com/NixOS/nixpkgs/pull/146891): Package is [16 years old](http://arj.sourceforge.net). Nothing to do.
- [libqb](https://github.com/NixOS/nixpkgs/pull/146896): Not sure about it, I just made it work on darwin.
- [hdr-plus](https://github.com/NixOS/nixpkgs/pull/146898): We can send a PR, it's a simple fix.
- [ctl](https://github.com/NixOS/nixpkgs/pull/146900): No development in more than 7 years. Nothing to do.

**Comment by roberth** [comment]
Some help with NixOps 1.7 Python 2 dependencies will be very much appreciated: #147034

It doesn't have to be pretty, imho, because it would be reasonable to drop NixOps 1.7 in favor of NixOps 2 (on Python 3) in the next release.

**Comment by tomberek** [comment]
The branch off just occurred a few moments ago. This means that any new fixes that land between now and the actual release should follow the usual backport procedure going forward. New fixes should go to `master` and backported to `release-21.11`.

**Comment by smancill** [comment]
The link to the backporting steps in this issue description is broken, because `CONTRIBUTING.md` was moved to the top-level directory.

**Comment by jonringer** [comment]
Yep, I think you're right

**Comment by mweinelt** [comment]
> Some help with NixOps 1.7 Python 2 dependencies will be very much appreciated: #147034
> 
> It doesn't have to be pretty, imho, because it would be reasonable to drop NixOps 1.7 in favor of NixOps 2 (on Python 3) in the next release.

#147055

**Comment by thiagokokada** [comment]
> The branch off just occurred a few moments ago. This means that any new fixes that land between now and the actual release should follow the usual backport procedure going forward. New fixes should go to `master` and backported to `release-21.11`.

Ouch. I may have backported some PRs to `staging-21.11` instead.

**Comment by Mindavi** [comment]
Staging is a valid target for a backport, so doesn't seem logical to remove it to me.

**Comment by tomberek** [comment]
Thank you everyone for a wonderful ZHF!

**Comment by roberth** [comment]
Do we have staging jobsets for 21.11? I don't see them in https://hydra.nixos.org/project/nixpkgs. Iirc, this has been improved in the last release, but maybe it hasn't been documented as part of the release process yet? cc @jonringer

**Comment by siraben** [comment]
Any chance we can get a final detailed eval report? I'm curious now the deltas are for each platform.

**Comment by tomberek** [comment]
Based on 
https://hydra.nixos.org/eval/1727142?compare=1718945
https://hydra.nixos.org/eval/1727142?filter=x86_64-linux&compare=1718945

x86_64-linux jobset at ~~653~~  182 failing jobs
x86_64-darwin at ~~1449~~ 1208 failing jobs (some aborted)
aarch64-linux at ~~782~~ 505 failing jobs

**Comment by jonringer** [comment]
> Do we have staging jobsets for 21.11? I don't see them in https://hydra.nixos.org/project/nixpkgs. Iirc, this has been improved in the last release, but maybe it hasn't been documented as part of the release process yet? cc @jonringer

we should

**Comment by jonringer** [comment]
done, just created it, and added notes about its creation to the update wiki PR

**Comment by vcunat** [comment]
Was there supposed to be a pass where (most of) the remains get marked with `meta.broken` or similar?

**Comment by risicle** [comment]
Note there are still a few outstanding unresolved PRs :point_up:  #148045 #147405 #147332  #147543 at least

**Comment by jonringer** [comment]
> Was there supposed to be a pass where (most of) the remains get marked with `meta.broken` or similar?

This is meant to be done on the release branch, but it is a PITA

cc @nrdxp @tomberek
