### ISSUE TITLE
Packaging Request: Copier

### ISSUE THREAD

**Issue by samuelludwig** [NixOS/nixpkgs#144602]
**Project description**

"Library and command-line utility for rendering project templates." 

It's functionality is similar to another project called `cookiecutter`, which is available in nixpkgs, however, Copier does not share some of it's limitations. For example: you can have a template which is just a single file, where cookiecutter requires an entire nested project dir (CC _does_ have a workaround, but its a bit of a hack). This particular difference makes Copier great for things such as, say, templating .nix files (like a flake.nix) into an existing project.

(As an explicit note: The thing that makes Copier exceptionally useful compared to a command like `nix flake init -t` is that Copier provides the ability to use and prompt for _variables_ to substitute strings in the templates.)

**Metadata**

* homepage URL: https://copier.readthedocs.io/en/stable/
* source URL: https://github.com/copier-org/copier
* license: mit
* platforms: Should be able to work on whatever platforms can run Python I believe

**Comment by samuelludwig** [comment]
I've personally tried to package this myself over the past week but my unfamiliarity with python-packaging/the-python-ecosystem in general has very much gotten the upper hand. I would love to see this packaged (both to use it, and so I can see how it's actually done 😅 (properly)).

**Comment by WolfangAukang** [comment]
#145528

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/210389
