### ISSUE TITLE
`config.xserver.config` is combined with other options in the wrong order

### ISSUE THREAD

**Issue by Twey** [NixOS/nixpkgs#14470]
## Issue description

I have a configuration in which I would like to have a generic base configuration, and then override it for a specific piece of hardware (I use a Dvorak layout, but one external keyboard has a Dvorak layout in hardware, so I would like its software layout to be `us(basic)`).  Therefore, I have a custom `xserver.config` in my [`config.nix`](https://github.com/NixOS/nixpkgs/files/204433/display.nix.txt).  However, because the `config` option is prepended rather than appended to the [generated config](https://github.com/NixOS/nixpkgs/files/204430/generated-config.txt), the generated `Keyboard catchall` class overrides the layout, driver, &c. of any custom input classes I might specify — input classes are applied from the top down.
## Technical details
- System: 16.09pre78848.9549257 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre78848.9549257

**Comment by Profpatsch** [comment]
triage: has this been fixed in the meantime?
