### ISSUE TITLE
nixos 16.03 gitlab won't start

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#14478]
## Issue description
I run gitlab inside of a container on my laptop
https://github.com/mogorman/dotfiles/blob/master/nixos/containers.nix
is my config.  when i upgraded to 16.03 it wouldnt start.  so I wiped it and reinstalled the container from scratch it still wont start. now attached below is the only error i see when i start it systemctl restart gitlab

### Steps to reproduce

use my config on nixos 16.03

## Technical details
16.03.498.f8a5d1e (Emu)
nix-env (Nix) 1.11.2
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

Apr 05 18:15:43 gitlab systemd[1]: Started gitlab.service.
Apr 05 18:15:43 gitlab systemd[1]: Starting gitlab-workhorse.service...
Apr 05 18:15:43 gitlab systemd[1]: Started gitlab-workhorse.service.
Apr 05 18:15:43 gitlab systemd[1]: Reached target Multi-User System.
Apr 05 18:15:43 gitlab systemd[1]: Startup finished in 44.243s.
Apr 05 18:15:43 gitlab gitlab-workhorse[764]: 2016/04/05 18:15:43 Starting gitlab-workhorse -20160404.142132
Apr 05 18:15:43 gitlab bundle[760]: Ignoring RedCloth-4.2.9 because its extensions are not built.  Try: gem pristine RedCloth --version 4.2.9
Apr 05 18:15:43 gitlab bundle[760]: Ignoring allocations-1.0.4 because its extensions are not built.  Try: gem pristine allocations --version 1.0.4
Apr 05 18:15:43 gitlab bundle[760]: Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Apr 05 18:15:43 gitlab bundle[760]: Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Apr 05 18:15:43 gitlab bundle[760]: Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Apr 05 18:15:43 gitlab bundle[760]: Ignoring charlock_holmes-0.7.3 because its extensions are not built.  Try: gem pristine charlock_holmes --version 0.7.3
Apr 05 18:15:43 gitlab bundle[760]: Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Apr 05 18:15:43 gitlab bundle[760]: Ignoring escape_utils-1.1.0 because its extensions are not built.  Try: gem pristine escape_utils --version 1.1.0
Apr 05 18:15:43 gitlab bundle[760]: Ignoring eventmachine-1.0.8 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.8
Apr 05 18:15:43 gitlab bundle[760]: Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Apr 05 18:15:43 gitlab bundle[760]: Ignoring http_parser.rb-0.5.3 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.5.3
Apr 05 18:15:43 gitlab bundle[760]: Ignoring kgio-2.10.0 because its extensions are not built.  Try: gem pristine kgio --version 2.10.0
Apr 05 18:15:43 gitlab bundle[760]: Ignoring mysql2-0.3.20 because its extensions are not built.  Try: gem pristine mysql2 --version 0.3.20
Apr 05 18:15:43 gitlab bundle[760]: Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Apr 05 18:15:43 gitlab bundle[760]: Ignoring pg-0.18.4 because its extensions are not built.  Try: gem pristine pg --version 0.18.4
Apr 05 18:15:43 gitlab bundle[760]: Ignoring posix-spawn-0.3.11 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.11
Apr 05 18:15:43 gitlab bundle[760]: Ignoring raindrops-0.15.0 because its extensions are not built.  Try: gem pristine raindrops --version 0.15.0
Apr 05 18:15:43 gitlab bundle[760]: Ignoring rblineprof-0.3.6 because its extensions are not built.  Try: gem pristine rblineprof --version 0.3.6
Apr 05 18:15:43 gitlab bundle[760]: Ignoring redcarpet-3.3.3 because its extensions are not built.  Try: gem pristine redcarpet --version 3.3.3
Apr 05 18:15:43 gitlab bundle[760]: Ignoring rinku-1.7.3 because its extensions are not built.  Try: gem pristine rinku --version 1.7.3
Apr 05 18:15:43 gitlab bundle[760]: Ignoring rugged-0.24.0b13 because its extensions are not built.  Try: gem pristine rugged --version 0.24.0b13
Apr 05 18:15:43 gitlab bundle[760]: Ignoring thin-1.6.4 because its extensions are not built.  Try: gem pristine thin --version 1.6.4
Apr 05 18:15:43 gitlab bundle[760]: Ignoring timfel-krb5-auth-0.8.3 because its extensions are not built.  Try: gem pristine timfel-krb5-auth --version 0.8.3
Apr 05 18:15:43 gitlab bundle[760]: Ignoring unf_ext-0.0.7.1 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.1
Apr 05 18:15:43 gitlab bundle[760]: Ignoring unicorn-4.8.3 because its extensions are not built.  Try: gem pristine unicorn --version 4.8.3
Apr 05 18:15:43 gitlab bundle[760]: Ignoring version_sorter-2.0.0 because its extensions are not built.  Try: gem pristine version_sorter --version 2.0.0
Apr 05 18:15:43 gitlab bundle[760]: Ignoring websocket-driver-0.6.3 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.3
Apr 05 18:15:44 gitlab bundle[760]: Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Apr 05 18:15:44 gitlab /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/bin/unicorn[760]: Refreshing Gem list
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:10: warning: already initialized constant Asana::Errors::APIError
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:10: warning: previous definition of APIError was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:20: warning: already initialized constant Asana::Errors::NotAuthorized
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:20: warning: previous definition of NotAuthorized was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:29: warning: already initialized constant Asana::Errors::Forbidden
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:29: warning: previous definition of Forbidden was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:38: warning: already initialized constant Asana::Errors::NotFound
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:38: warning: previous definition of NotFound was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:49: warning: already initialized constant Asana::Errors::ServerError
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:49: warning: previous definition of ServerError was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:65: warning: already initialized constant Asana::Errors::InvalidRequest
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:65: warning: previous definition of InvalidRequest was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:80: warning: already initialized constant Asana::Errors::RateLimitEnforced
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/errors.rb:80: warning: previous definition of RateLimitEnforced was here
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/sfb3p7rw71ayiryrki27y6s823nz7dh1-gitlab/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/version.rb:4: warning: already initialized constant Asana::VERSION
Apr 05 18:15:52 gitlab bundle[760]: /nix/store/58fl2vhr0dvfn2qvy1m87pl632miy27p-ruby2.2.3-p0-asana-0.4.0/lib/ruby/gems/2.2.3/gems/asana-0.4.0/lib/asana/version.rb:4: warning: previous definition of VERSION was here
Apr 05 18:15:54 gitlab bundle[760]: Rails Error: Unable to access log file. Please ensure that /nix/store/24jkskyf9l38xz5bgmfpz7yx57w28zjr-gitlab-8.5.7/share/gitlab/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /nix/store/24jkskyf9l38xz5bgmfpz7yx57w28zjr-gitlab-8.5.7/share/gi

**Comment by mogorman** [comment]
something else that doesn't make sense to me, this is a fresh install I rm -rf /var/lib/containers/gitlab

However when I logged in via nixos-container root-login
 
[root@gitlab:~]# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"15.09.911.53286a8"

Why is it not 16.03 like the core os? is my system somehow tainted?  I was running 15.09 and just upgraded to 16.03.  When I run it locally I get what I would expect

[root@toadman:~]# nixos-version
16.03.503.3f96280 (Emu)
[root@toadman:~]# nix-env --version
nix-env (Nix) 1.11.2
[root@toadman:~]# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.503.3f96280"

**Comment by mogorman** [comment]
i was able to clean out my system, but still getting same issue, looks like the logs are inside the nix store, which obviously wont work

**Comment by joachifm** [comment]
The gitlab module sets ` GITLAB_LOG_PATH = "${cfg.statePath}/log"`, which gitlab seems to be patched to respect, so something's not right here.

**Comment by mogorman** [comment]
ya i looked at diff it used to set  environment.GITLAB_APPLICATION_LOG_PATH = "${cfg.stateDir}/log/application.log

**Comment by mogorman** [comment]
traced it to this commit https://github.com/NixOS/nixpkgs/commit/bcfa59bf822dc696e963d7abccfdff2e58e70525 he isnt setting the log_path like it was previously being set

**Comment by joachifm** [comment]
cc @fpletz

**Comment by mogorman** [comment]
i have modifed my configs https://github.com/mogorman/dotfiles/blob/master/nixos/containers.nix  and when I curl the url i get a redirect to an invalid page <html><body>You are being <a href="https://10.137.137.3/users/sign_in">redirected</a>.</body></html> 

I have it set to be just http

**Comment by fpletz** [comment]
There is some relevant log output missing. The application log path is just a warning even though it says error. We have a new version coming up on master but we will not backport this as quite some things in the ruby infrastructure has changed. Please update to 16.09 when available.
