### ISSUE TITLE
vivaldi browser segfaults when experimental wayland support is enabled

### ISSUE THREAD

**Issue by matklad** [NixOS/nixpkgs#144860]
```console
λ vivaldi --enable-features=UseOzonePlatform --ozone-platform=wayland
[10172:10172:1106/142042.649664:ERROR:wayland_connection.cc(133)] Failed to load wayland client libraries.
[10172:10172:1106/142042.649687:FATAL:ozone_platform_wayland.cc(211)] Failed to initialize Wayland platform
[1106/142042.652325:ERROR:process_memory_range.cc(75)] read out of range
fish: Job 1, 'vivaldi --enable-features=UseOz…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

In contrast, `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland` works correctly. 

Given that vivaldi prints something about not being able to load wayland client libraries, I suspect the problem is on our side.

**Comment by matklad** [comment]
I think that’s dupe of https://github.com/NixOS/nixpkgs/issues/126652

**Comment by edrex** [comment]
I think this is a distinct issue from #126652, so suggest reopening.
I took a crack at adding the wayland client libs to the package which got rid of the error but not the fatal, so I think this isn't ready yet upstream.

**Comment by buehlefs** [comment]
We could reopen this issue and use #126652 only for screen sharing under wayland. If I remember right adding `libglvnd` worked without any crashes at the time, but that may have changed by now.

**Comment by edrex** [comment]
Thanks for the tip @buehlefs, that got it starting up native wayland. Opened :arrow_up:
