### ISSUE TITLE
mullvad-vpn: .desktop file doesn't work with rofi (no such file or directory)

### ISSUE THREAD

**Issue by nicooo** [NixOS/nixpkgs#144878]
### Describe the bug
Runnning mullvad-vpn through 'rofi -show drun' gives an error

### Steps To Reproduce
1. run 'rofi -show drun'
2. select 'Mullvad VPN'
3. press enter

### Expected behavior
The program opens

### Additional context
Same happens when running mullvad-vpn.desktop using dex
Removing the double quotes from the Exec= line fixes the problem for me.

### Notify maintainers

@flexagoon @ymarkus @Br1ght0ne 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.14-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre327669.b67e752c29f"`
 - channels(nico): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by flexagoon** [comment]
Yes, I'm aware of that. I opened a PR to fix this. #144636

**Comment by flexagoon** [comment]
@nicooo it got merged. You can close this issue now

**Comment by nicooo** [comment]
Thanks
