### ISSUE TITLE
Neovim's `withRuby` option seems to be a no-op

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nixpkgs#144830]
### Describe the bug

On the `programs.neovim` module, `withRuby` seems to be a no-op (I didn't find any other reference of `withRuby` usage except where it is defined: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/neovim.nix#L41).

### Steps To Reproduce
1. Ctrl+F here for `withRuby`: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/neovim.nix#L41

### Expected behavior
There should be a usage somewhere of `withRuby` in this module besides its declaration.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@teto 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.13-xanmod1-cacule, NixOS, 21.05.20211101.372e59d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"nixos-20.09.3124.2118cf551b9"`
 - nixpkgs: `/nix/store/w1kgp6j8n0w46q5d5a2d3zmas4g4xr28-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by thiagokokada** [comment]
Searching in GitHub or using ripgrep also didn't find anything interesting: https://github.com/NixOS/nixpkgs/search?q=withRuby

**Comment by teto** [comment]
indeed, patch welcome.
