### ISSUE TITLE
Ananicy - is Another auto nice daemon, with community rules support.

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#144821]
**Project description**
Ananicy (ANother Auto NICe daemon) — is a shell daemon created to manage processes' IO and CPU priorities, with community-driven set of rules for popular applications (anyone may add their own rule via github's pull request mechanism). It's mainly for desktop usage.

**Metadata**

* homepage URL: https://github.com/Nefelim4ag/Ananicy
* source URL: https://github.com/Nefelim4ag/Ananicy
* license: gpl3
* platforms:  linux

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/144933
