### ISSUE TITLE
TortoiseHG version included in nixpkgs is incompatible with the Mercurial version included

### ISSUE THREAD

**Issue by cumber** [NixOS/nixpkgs#14481]
I've installed both Mercurial and TortoiseHG from nixpkgs in nixos-16.03, but starting up TortoiseHG just aborts with this error message:

    #!python
    ** Mercurial version (3.7.1).  TortoiseHg version (3.6)
    ** Command: 
    ** CWD: /home/benme
    ** Encoding: UTF-8
    ** Extensions loaded: 
    ** Python version: 2.7.11 (default, Dec  5 2015, 19:47:20) [GCC 5.3.0]
    ** System: Linux benme-nixos 4.4.6 #1-NixOS SMP Wed Mar 16 15:43:17 UTC 2016 x86_64
    ** Qt-4.8.7 PyQt-4.11.3 QScintilla-2.9
    
    This version of TortoiseHg requires Mercurial version 3.5.n to 3.6.n, but found 3.7.1

They're both installed by being listed in the `paths` of a `buildEnv` in my config.nix (`mercurialFull` and `tortoisehg`). I haven't done any overriding of either.

* System: NixOS: 16.03.503.3f96280 (Emu)
* Nix version: 1.11.2
* Nixpkgs version: 16.03.503.3f96280

**Comment by cumber** [comment]
Looks like #13523 would already fix this

**Comment by FRidh** [comment]
#13523 is merged in a4ce0e233b086845324f6b4d38ce3a408612a8d7
Please check whether this works for you.

**Comment by cumber** [comment]
Yep, tortoisehg works with that build, thanks!
