### ISSUE TITLE
Our MultiMC build doesn't have keys to log into a Microsoft Account

### ISSUE THREAD

**Issue by kisik21** [NixOS/nixpkgs#144912]
### Describe the bug
Our build of MultiMC cannot log in to any Microsoft (migrated) account due to lack of API keys from Azure. AFAIK we cannot provide the keys in our build safely since they are secrets and therefore will have to be public in Nix store.

### Steps To Reproduce
1. Launch MultiMC
2. Try to log in
3. Observe the "Add Microsoft [account]" button grayed out

### Expected behavior
MultiMC from Nixpkgs can log in to Microsoft accounts.

### Additional context
We can package the official build of MultiMC which does contain API keys, by either patchelf-ing it or wrapping it in an FHS environment.

### Notify maintainers
@cleverca22 @starcraft66

**Comment by hqurve** [comment]
You need to provide your own. 

See:
- https://nixos.wiki/wiki/MultiMC
- https://github.com/NixOS/nixpkgs/pull/137147
