### ISSUE TITLE
Building octave-4.0.1 results in segfault in one of the tests

### ISSUE THREAD

**Issue by josefs** [NixOS/nixpkgs#14490]
## Issue description

I've been running octave-4.0.0 but now nixpkgs offers a newer version. When I try to upgrade I run into problems. Nix builds octave seemingly successfully but then runs the tests and one of them results in a segfault. Here's the end of the output during the build:

      scripts/general/prepad.m .................................... PASS     17/17  
      scripts/general/profile.m ...................................panic: Segmentation fault -- stopping myself...
    Makefile:2802: recipe for target 'check' failed
    make[1]: *** [check] Segmentation fault (core dumped)
    make[1]: Leaving directory '/tmp/nix-build-octave-4.0.1.drv-0/octave-4.0.1/test'
    Makefile:3071: recipe for target 'check' failed
    make: *** [check] Error 2
    builder for ‘/nix/store/1lq2m6zpyav6x6ibkvw4vgvhy4f0z6jj-octave-4.0.1.drv’ failed with exit code 2
    error: build of ‘/nix/store/1lq2m6zpyav6x6ibkvw4vgvhy4f0z6jj-octave-4.0.1.drv’ failed

### Steps to reproduce

Since I already have octave installed I just did:

```
nix-channel --update
nix-env --upgrade
```

## Technical details

* System: Ubuntu 15.10
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre79463.d88ae10

**Comment by domenkozar** [comment]
Same on Hydra: http://hydra.nixos.org/build/33847600/nixlog/1/raw

**Comment by FRidh** [comment]
Since the last channel update openblas 2.17 is used. Now, octave is building fine.
http://hydra.nixos.org/eval/1253801?filter=octave&compare=1253586&full=

**Comment by domenkozar** [comment]
Should we backport openblas to 16.03 then (I know you already requested that)

**Comment by FRidh** [comment]
This appears to fix the package and would also mean we could get rid of openblas 2.14 for numpy on stable so yes, I think we should. We just need to test it again first.

**Comment by josefs** [comment]
Works for me now. Though I'll leave it to someone else to close this ticket if they feel there is more work needed to be done.
