### ISSUE TITLE
Improve makeWrapper's wrapped program naming

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#144981]
## Issue description

Wrapped programs have a cryptic `.progname-wrapped` name which some applications like to display as their name in the application window and other places.

It'd be much better if the executable file kept its real name and was moved somewhere else like `$out/bin/wrapped/progname`.

The big problem here is how to handle more than one wrapping (which happens sometimes). A trivial implementation would be to just created nested `/wrapped` subdirs and a quick implementation of that in https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/make-wrapper.sh like

```bash
# Syntax: wrapProgram <PROGRAM> <MAKE-WRAPPER FLAGS...>
wrapProgram() {
    local prog="$1"
    local hidden

    assertExecutable "$prog"

    hidden="$(dirname "$prog")/wrapped/"
    while [ -e "$hidden" ]; do
      hidden="$hidden/wrapped"
    done
    mkdir -p "$hidden"
    mv "$prog" "$hidden"/"$(basename $prog)"
    # Silence warning about unexpanded $0:
    # shellcheck disable=SC2016
    makeWrapper "$hidden"/"$(basename $prog)" "$prog" --argv0 '$0' "${@:2}"
}
```

keeps the app name but unfortunately won't quite work:
* A second wrapping moves the first wrapper instead of the wrapped program
* Moving a wrapper like this would require editing its content because it now has to point one level deeper. 

Another idea I've had is to create `.wrapped{,_,__,___,...}` dirs to keep the wrappers in instead of filenames which I'll explore now but that doesn't sound very clean either.

What are your thoughts on how to do this?

**Comment by Artturin** [comment]
See https://github.com/NixOS/nixpkgs/pull/139213#discussion_r715141413

**Comment by Atemu** [comment]
That's a bummer. I guess we could keep the old behaviour around as an options for the packages where it doesn't work.

**Comment by milahu** [comment]
> It'd be much better if the executable file kept its real name and was moved somewhere else like `$out/bin/wrapped/progname`.

now you have a new problem:
the dirname has changed, and this can break the app

for scripts, it's possible to keep the original file path,
and only patch the shebang line, see my #171689

for binary exe's ... maybe we can patch the loader.
or just keep wrapping the binaries,
either with bash wrappers, or with `makeBinaryWrapper` #124556

**Comment by Artturin** [comment]
we have binary wrappers now

**Comment by bjornfor** [comment]
> we have binary wrappers now

And they fixed the problem? How? (Or should this issue just re-target *binary* wrappers?)

**Comment by Artturin** [comment]
> > we have binary wrappers now
> 
> And they fixed the problem? How? (Or should this issue just re-target _binary_ wrappers?)

binary wrappers are able to pass on ARGV0 better and wrapProgram passes --inherit argv0 to makeWrapper
