### ISSUE TITLE
Strategoxt does not build on Mac

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#14494]
I tried to install Stratego on my Mac, but the build of the dependency `sdf2bundle` failed. I presume that the error is caused by Clang (which is the standard compiler on Mac) and the project only builds with GCC. I also tried to compile the `sdf2bundle` with GCC, but this attempt failed because GCC itself cannot be built on Mac (*sigh*).

Here is the build log for `nix-env -i strategoxt`: https://gist.github.com/svenkeidel/3fb6d9440a00010d6a8718138ee0e09f

Best,
Sven

**Comment by copumpkin** [comment]
That's a pity. We used to have gcc working on Darwin.

**Comment by pSub** [comment]
This issue seems to be related to #7018.

**Comment by svenkeidel** [comment]
Yeah, it is exactly the same issue. Thanks for pointing that out.
