### ISSUE TITLE
pythonPackages.MySQL_python seems broken in 16.03

### ISSUE THREAD

**Issue by lancelotsix** [NixOS/nixpkgs#14512]
## Issue description

MySQL python binding is broken in 16.03 channel. Is seems to be OK in master. Apparently, 5982591afc07480808d9c71a5b97463fc4cc9943 is the commit in master that fixed that issue.

If it is OK, I’d like to cherrry pick that commit into the `16.03` branch (this will imply a massive re-downloads from the cache for the users).

### Steps to reproduce

```bash
$ nix-shell -p pythonPackages.MySQL_python --command "python -c 'import MySQLdb'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/l7bgcgm270zmq1138cm4qspb648qdgz2-python2.7-MySQL-python-1.2.5/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: /nix/store/l7bgcgm270zmq1138cm4qspb648qdgz2-python2.7-MySQL-python-1.2.5/lib/python2.7/site-packages/_mysql.so: symbol mysql_use_result, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference
```

## Technical details

* System: `16.03.468.2d840da (Emu)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `16.03.526.567b65d`

cc @domenkozar

**Comment by domenkozar** [comment]
@edolstra any objections for a full rebuild of 16.03? Maybe there's a workaround for this bug.

**Comment by basvandijk** [comment]
The error in #14351 seems related to this.

**Comment by domenkozar** [comment]
Cherry-picked to 16.03
