### ISSUE TITLE
Broken link `getty.target.wants/autovt@tty1.service` breaks terraform 

### ISSUE THREAD

**Issue by MrRacoon** [NixOS/nixpkgs#145119]
I've been using terraform/scalr for deployments, and a recent change somewhere (I think in scalr) started looking at 
`/etc/systemd/system/getty.target.wants/autovt@tty1.service` 

This symlink seems broken, as there is no `../autovt@tty1.service` file in the parent directory, where it points. From what I've gathered in my research around systemd, this is okay:
https://stackoverflow.com/a/57616016

However, for some reason, this breaks running remote-terraform-workspaces, from being locally run.

`Error from Terraform` 
```
Failed to upload configuration files: Failed to get symbolic link destination for "/nix/store/j47ia454a6h64wy863pvahca5l2qaqch-system-units/getty.target.wants/autovt@tty1.service": lstat /nix/store/j47ia454a6h64wy863pvahca5l2qaqch-system-units/autovt@tty1.service: no such file or directory
```

Line in Nixpkgs that creates the symlink:
https://github.com/NixOS/nixpkgs/blob/dfad31d753eccdd592850adf2599d132236b63cf/nixos/modules/system/boot/systemd-lib.nix#L229

I'm wondering if there is a better place to point the link? potentially `/dev/null`?

**Comment by MrRacoon** [comment]
this seems to be more of an issue with either terraform/scalr, as updating the link in the store, manually, leads to a new unrelated symlink issue, as if the thing is crawling all of the /nix/store for broken symlinks

**Comment by KiaraGrouwstra** [comment]
i just had this occur as well, while previously i did not run into this.
maybe i should try and find a minimum repro on this so as to document workarounds.

**Comment by KiaraGrouwstra** [comment]
hm, i seem to get this just based on the organization/workspace i use to log in for terraform's cloud backend. still not sure why tho.

**Comment by KiaraGrouwstra** [comment]
for me opting not to use the cloud backend seemed to help as a workaround, at least.
