### ISSUE TITLE
kodi: web interface doesn't work 

### ISSUE THREAD

**Issue by azazel75** [NixOS/nixpkgs#145116]
### Describe the bug
Since some time (for sure since the 21.05 release) the web interface that comes with Kodi, called "Chorus 2", doesn't work anymore. Enabling it and connecting to the dedicated port with a browser results in a blank page with a "File not found" at the top.

### Steps To Reproduce
1. Set `services.xserver.desktopManager.kodi.enable = true;`  in configuration.nix or alternatively install the `kodi` package;
2. launch the application and go to the following menu: `⚙ > Services > Control` and enable the web interface;
3. with a browser go to the web interface port, usually http://127.0.0.1:8080 , and verify that the web interface doesn't work

### Notify maintainers
@aanderse
@cpages
@edwtjo 
@minijackson
@peterhoeg
@sephalon
### Metadata
- system: `"x86_64-linux"`
- host os: `Linux 5.15.0, NixOS, 21.11 (Porcupine)`
- multi-user?: `yes`
- sandbox: `relaxed`
- version: `nix-env (Nix) 2.5pre20211007_844dd90`
- channels(root): `"nixos-21.11pre327669.b67e752c29f"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
- kodi
```

**Comment by aanderse** [comment]
Can you please share some screen captures of your `kodi` settings? Do you have "Require authentication" checked or not? Recently `kodi` started getting picky about that.

![Screenshot_20211108_165326](https://user-images.githubusercontent.com/7755101/140824214-05aa660a-cea3-4769-87dc-6691648bc7d3.png)

**Comment by azazel75** [comment]
Hi @aanderse and thanks for answering... here is the screenshot:
![20211108_23h28m14s_grim](https://user-images.githubusercontent.com/834719/140828913-2b60a1f5-05c0-4d97-b4c6-6f758b4ed779.jpeg)

But I found out another important detail. I really do not install kodi alone, but I use exactly the following expression:
```nix
    kodiDistro = kodi.withPackages (kpkgs: with kpkgs; [
      inputstreamhelper
      inputstream-adaptive
      inputstream-ffmpegdirect
      inputstream-rtmp
      pvr-iptvsimple
      vfs-sftp
      vfs-libarchive
    ]);
```
and then I add this `kodiDistro` to `environment.systemPackages`. I've just verified that the issue shows only with such configuration, but I don't know why. There's no "chorus" or "webinterface" distinct sub-package so I don't know if the above configuration is missing something.

**Comment by cpages** [comment]
I think I had this exact same issue and it was my user config pointing to a garbage collected store path. Could this be your case?

**Comment by azazel75** [comment]
I don't think so, I've updated today and I have yet to do a `nix-collect-garbage`

**Comment by aanderse** [comment]
What does `netstat -plant | grep 10000` say?

**Comment by azazel75** [comment]
> What does `netstat -plant | grep 10000` say?

```
$ netstat -plant | grep 10000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      17736/kodi.bin
tcp6       0      0 :::10000                :::*                    LISTEN      17736/kodi.bin
```

The port is open and the kodi's web server *is* responding, it's just the chorus webinterface addon that has issues. I've tried with by moving out my `~/.kodi`directory and letting it make one new on startup but the problem is still there.

To temporarily fix it I had to download the upstream [chorus2 distro](https://github.com/xbmc/chorus2/releases/download/19.x-2.4.7/webinterface.default.19.x-2.4.7.zip), unpack it to change the id in the `addon.xml` and change the root directory to have the same, then repack it and install into kodi via the *install addon from zipfile option*, the go to the aforementioned configuration menu and set it as the enabled webinterface.

**Comment by aanderse** [comment]
Oh boy... I tested and I have this issue too. Anyone interested in hunting down the last version that worked?

**Comment by azazel75** [comment]
hey, @aanderse,  do you confirm that it shows up only when using `kodi.withPackages`?

**Comment by aanderse** [comment]
@azazel75 I can confirm that this issue only occurs when using `kodi.withPackages` for me. I think it might help to determine what revision of nixpkgs introduced this regression, unless someone wants to actually dig into the `kodi` source code a bit.

HINT: I did very briefly dig into the code and it wasn't the most pleasant experience I've recently had :smile: Would need to run through the code with `gdb` to get a clear picture of exactly where the problem is.

**Comment by jfly** [comment]
I dug into this and it turns out to be related to the way nix's `makeWrapper` creates symlinks. See https://github.com/NixOS/nixpkgs/pull/152675 for details and a fix/workaround.

**Comment by azazel75** [comment]
Hi @jfly, thanks to spend some time on this, I've yet to check your PR, but the solution seems appropriate even if not optimal because of the copy.... Can I ask you how you found out where the issue was in the code ? It does seem to log anything only when the url matches the blacklist....

**Comment by jfly** [comment]
Yeah, it's a bummer kodi doesn't log something obvious in this case. I figured this out by strace-ing kodi both with things working and without things working. I saw a sequence of syscalls that I realized were likely a call to `realpath`, and that was enough of a clue to start reading the relevant kodi code.

**Comment by aanderse** [comment]
I have a feeling this isn't going to be the last time we run into this issue... This would be especially problematic for addons which don't come bundled with `kodi`.

@jfly thanks for the detective work!
