### ISSUE TITLE
nix-shell: Refactor proposal to allow (arguably) more functional usage

### ISSUE THREAD

**Issue by Kreyren** [NixOS/nixpkgs#145125]
nix-shell's `--run` argument only processes the first argument requiring the argument to be quoted and manipulated which increases the complexity of the integration compared to GNU Guix which uses `--` that processes all arguments following it:

```console
# Sending a `Hello` on ix.io paste service using curl

# On Guix
$ echo Hello | guix shell curl -- curl -F 'f:1=<-' ix.io
http://ix.io/3wiA

# On NixOS
$ echo Hello | nix-shell -p curl --run "curl -F 'f:1=<-' ix.io"
http://ix.io/3wiA
```

I argue that Guix's implementation is superior as it enables the use of quotes and expansions without having to manage the quotation:

```console
$ guix shell bubblewrap -- bwrap \
	--bind "$(pwd)" "$(pwd)" \
	--chdir "$(pwd)" \
	--unshare-user \
	...
```

Compared to nix-shell:

```console
$ nix-shell -p bubblewrap --run "bwrap --bind $(pwd) $(pwd) --chdir $(pwd) --unshare-user ..."
```

Which also requires handling for projected scenario which requires a variable expansion that may unexpectedly contain a space to mitigate [SC2086](https://github.com/koalaman/shellcheck/wiki/Sc2086):
```console
$ ls /bin/sh /usr/bin/env 
/bin/sh  /usr/bin/env
$ ls "$(echo "/bin/sh" "/usr/bin/env")"
ls: cannot access '/bin/sh /usr/bin/env': No such file or directory
```

Thus i propose nix-shell to be reworked to adapt GNU Guix's design.

**Comment by kira-bruneau** [comment]
`nix shell` does exactly what you're describing. Right now the command is marked as experimental, but it should replace `nix-shell` when Nix 3 is released.

If you want to, you can enable it right now by following the instructions at: https://nixos.wiki/wiki/Nix_command.

**Comment by Kreyren** [comment]
Closing as solved then
