### ISSUE TITLE
Plasma Wayland+Grid tiling+App menu in title bar+gtk app=App menu as a separate window

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#145274]
### Describe the bug
Under plasma wayland with Grid-Tiling script and menu button in the title bar resultin the menu being treated as a new window.
Of note that it has the same problem also with bismuth https://github.com/Bismuth-Forge/bismuth

### Steps To Reproduce
1. Install and enable Grid tiling or Bismuth
2. Add the app menu too the title bar
3. Run a plasma Wayland session
4. Click on the app menu on the title bar

### Expected behavior
App menu shows a menu under the button

### Screenshots
![image](https://user-images.githubusercontent.com/6931743/141020822-6bd97dc8-df15-43b8-adba-399f0fb4b113.png)

### Additional context
Both Bismuth and Grid tiling present the problem under Plamsa Wayland but not X11.

### Notify maintainers
@peterhoeg @jtojnar @Kranzes @ttuegel @nyanloutre
### Metadata

    system: "x86_64-linux"
    host os: Linux 5.10.77, NixOS, 21.11 (Porcupine)
    multi-user?: yes
    sandbox: yes
    version: nix-env (Nix) 2.4pre20211006_53e4794
    channels(root): "nixos-21.05.3801.83667ff60a8"
    nixpkgs: /nix/store/94hsmqk3nrx26yd46crlw5aygiya6pj4-source

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
That sounds like a bug in grid tiling and/or app menu. On  wayland, menus are separate _popup_ surfaces from the window and the compositor should deal with them as such.

**Comment by phrxmd** [comment]
I can't reproduce this with Bismuth - I'm running Bismuth 2.0 under KWin Wayland 5.23.2 and the app menu opens as it should.

**Comment by pasqui23** [comment]
@phrxmd Now I've cjecked and it does not happen with kde apps, but wuth gtk one like chrome, (patched) vscode and TexMacs it does happen

**Comment by SuperSamus** [comment]
Both of the linked issues are closed, I guess this can be closed too?
