### ISSUE TITLE
Avoid lots of empty lines in /etc/pam.d/ files

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#145286]
### Describe the bug

Basically redo #18580 after it was reverted in #18710.

### Steps To Reproduce
1. `cat` any file in /etc/pam.d/

### Expected behavior

The non-empty lines should be separated by at most one empty line.

### Example

```console
$ cat /etc/pam.d/cups 
# Account management.
account required pam_unix.so






# Authentication management.











auth sufficient pam_unix.so   likeauth try_first_pass




auth required pam_deny.so

# Password management.
password sufficient pam_unix.so nullok sha512







# Session management.
session required pam_env.so conffile=/nix/store/0iliy98dpm3kcmmqxd7dzg0kmv7ksqyz-pam-environment readenv=0

session required pam_unix.so


















```

### Notify maintainers

@bjornfor Would you be interested?

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.05.4044.e74894146a4 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4044.e74894146a4, home-manager-21.05"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bjornfor** [comment]
I still think it'd be nice to do. I messed up last time and haven't bothered trying again. Happy to se others giving it a try.

**Comment by l0b0** [comment]
Fair enough, @bjornfor; I'll give it a try based on what looks like a good pattern at the bottom of the same file.

That said, I have a major hole in my understanding of Nix which I'm hoping someone might point towards: _how do I build and verify the result of a single file_ like nixos/modules/security/pam.nix on its own? Is that possible, or do I have to build another package which depends on it just to see whether it works?
