### ISSUE TITLE
A call for Darwin maintainers

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#145230]
We'd really benefit from better coordination around fixing darwin/macOS packages.

We have [darwin-maintainers](https://github.com/orgs/NixOS/teams/darwin-maintainers/members) team which is currently 7 members.

If you'd like to join the team, we're looking for help with the following:

- [review and test open PRs](https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%226.topic%3A+darwin%22)
- [participate in reducing the number of failing darwin packages](https://github.com/NixOS/nixpkgs/issues/144627#issuecomment-962670816)

You're welcome to join MacOS+Nix community at https://matrix.to/#/#macos:nixos.org

If you need access to M1 community box see https://github.com/winterqt/darwin-build-box

Feel free to nominate yourself and help use bring macOS into a better state :)

**Comment by Kloenk** [comment]
I would like to nominate myself, as I'm using an m1 Mac. The macOS sdk is a bit above my knowledge, but I can try to help with other things.

I'm currently in University though, so I have to see how much time I have. But Pinging me could help to remember me to do nixpkgs things :-)

**Comment by fiddlerwoaroof** [comment]
Hi, I’m interested, but I’m not sure how much time I have. Is there any list of good first issues? I have both Intel and M1 hardware.

**Comment by mstone** [comment]
I’m also interested, at least for the current personal planning horizon.

**Comment by domenkozar** [comment]
Invited all three, thanks a lot for helping out :heart:

**Comment by uri-canva** [comment]
I have access to both `x86_64-darwin` and `aarch64-darwin`, happy to help!

**Comment by mikroskeem** [comment]
I have aarch64-darwin (and x86_64-darwin, via Rosetta), happy to help as well.

**Comment by winterqt** [comment]
Hi! I have access to an `aarch64-darwin` machine and would be happy to help.

**Comment by prusnak** [comment]
Please add me as well. I have aarch64-darwin (and x86_64-darwin, via Rosetta).

**Comment by griff** [comment]
I have a x86_64-darwin and though I am very busy at the moment I will try and timebox an hour a day for helping with this.

**Comment by kevingriffin** [comment]
I'd be happy to help with my `aarch64-darwin`, and probably an Intel one somewhere too.

**Comment by thefloweringash** [comment]
I'd like to help out where I can.

**Comment by kira-bruneau** [comment]
I have a x86_64-darwin machine, and I'd be happy to help out when I can :slightly_smiling_face:

**Comment by jonringer** [comment]
I would like to thank everyone who has volunteered, really helps.

I apologize ahead-of-time for spamming you all during ZHF :)

**Comment by kubukoz** [comment]
I have an x86_64 machine, M1 coming later in the month, happy to run checks but I don't know much about the underlying magic.

**Comment by olebedev** [comment]
I have x86_64 and M1 machines, I would be happy to help!

**Comment by willjr** [comment]
I'd also be happy to help!
I'm both a NixOS and MacOS user!

**Comment by samuela** [comment]
Happy to help any way I can!

**Comment by sikmir** [comment]
I use both NixOS and MacOS (x86_64), I'd like to help.

**Comment by smaret** [comment]
I can help too.

**Comment by groodt** [comment]
I'm happy to help. I'm `x86_64-darwin` and hopefully `aarch64-darwin` sometime in the future.

**Comment by domenkozar** [comment]
We've grown the @NixOS/darwin-maintainers team from 7 members to 25 in the last 24h.

That's an overwhelming response, thank you all for helping out!

**Comment by hexagonal-sun** [comment]
Happy to help with `aarch64-darwin`.  I also have an outstanding PR that aims to improve the Nix experience on darwin machines by creating `/Applications` launchers for packages (see  #131891).  Thanks!

**Comment by starcraft66** [comment]
Hi! I have both `x86_64-darwin` and `aarch64-darwin` machines at my disposal and would be happy to help!

**Comment by NilsIrl** [comment]
Hi, I'd be interested.

**Comment by marsam** [comment]
Hi, I would be happy to help!

**Comment by Artturin** [comment]
Interested people please take a look at issues with the darwin label 
https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+label%3A%226.topic%3A+darwin%22+is%3Aissue+

**Comment by maljub01** [comment]
I have x86_64 and M1 machines, I would also be happy to help.

**Comment by mexisme** [comment]
> I'd also be happy to help!
> I'm both a NixOS and MacOS user!

I'd also be very happy to help, for the same reasons.

**Comment by damien-biasotto** [comment]
I would be happy to help, I have both M1 and Intel macOS platforms, and NixOS is my daily driver.

**Comment by reckenrode** [comment]
I’d be happy to help too. I’ve already submitted a few PRs to add support for Darwin to a few packages or fix builds that were broken. I’ve got access to both Apple Silicon and Intel Macs as well as x86_64 and aarch64 Linux devices (for testing that Darwin changes don’t break Linux).

**Comment by 0x4A6F** [comment]
I have access to neither `aarch64-darwin` nor `x84_x64-darwin` and other people in this situation could tag issues/pr with the appropriate tag or join [#macos:nixos.org (matrix)](https://matrix.to/#/#macos:nixos.org) and ask for assistance.

That helped me in at least one occasion. Thanks for working on Darwin. :heart:

**Comment by reckenrode** [comment]
Some of you may have seen a response from me last night. I took it down because I wanted to take some more time to reflect on it. I appreciate the work everyone does on getting and keeping Darwin working with Nix. It can be demoralizing sometimes to run into packages that should work but don’t, especially if fixing them is non-trivial. I’ve submitted a few PRs so far to fix broken things and plan to continue submitting more in the future as I work through the overlays in my flake. Anyway, I just wanted to say again how great the work people do on Darwin support is.

I have access to both x86_64 and aarch64 systems for both macOS and NixOS. I’d be happy to help and do what I can.

**Comment by winterqt** [comment]
> Anyway, I just wanted to say again how great the work people do on Darwin support is.

Thank you for your work as well! (you might recognize me from the Home Manager application launcher issue, I'm still using your `rsync` snippet :)

**Comment by domenkozar** [comment]
We have 5 more macs (intel and arm) [running at ofborg as of recently](https://github.com/NixOS/nixos-org-configurations/issues/179), so do use ofborg to test PRs!

I suspect a lot of darwin failures are because a new package was added, it was marked as unix compatible (based on upstream claim) but the package really never built for darwin. It's totally fine if we mark such packages as not supported on darwin. Once ZHF is over, I'd just mark the rest as broken.

In case you work at a company that uses macOS+Nix, I'd kindly ask you to request your company to donate to https://opencollective.com/nix-macos so that we can fix the remaining big blockers that drag down darwin.

Thank you all

**Comment by flurie** [comment]
> I suspect a lot of darwin failures are because a new package was added, it was marked as unix compatible (based on upstream claim) but the package really never built for darwin.

These are pretty easy to spot. I've fixed a few of them so far. The good news is that the fixes are usually fairly obvious once one knows what to look for. The bad news is that sometimes these fixes must be done upstream.

**Comment by ylh** [comment]
Not sure if this is the place to ask, but I've been bitten in multiple different places by the fact that macOS SDK selection differs between aarch64 and x86_64 -- on the former, the fundamental build input is the command-line tools DMG, whereas on the latter, it's a bunch of opensource.apple.com packages. This is responsible for all sorts of cursed inconsistencies in building on both archs. Is the problem to do with waiting for a fresher open-source release from Apple to handle aarch64, or would we accept accepting the binary SDK as an input on both platforms? It's a tricky balance between expediency, consistency, and open-source purity, I suppose.

If there's some initiative to deal with this in particular, I'd love to be pointed to it and help.

**Comment by Artturin** [comment]
@ylh https://github.com/NixOS/nixpkgs/issues/116341

https://github.com/NixOS/nixpkgs/issues/101229

@toonn is being paid to work on nix on darwin
 https://opencollective.com/nix-macos
Please contribute financially if you'd like to support the effort

**Comment by Artturin** [comment]
someone on aarch64-darwin please take a look https://github.com/NixOS/nixpkgs/pull/147376#issuecomment-981226882

**Comment by yeongsheng-tan** [comment]
I'd like to help. In an active user benefiting a lot from nix nixpkgs and flakes for building out our homogeneous development environment for x86_64-darwin and x86_64-linux and hopefully in the next 6 months to 1 year on aarch64-darwin. I have a macOS x86_64-darwin BigSur machine as my primary workhorse now which may be able to contribute to the cause.

**Comment by cideM** [comment]
I run NixOS and have an M1 Mac powered by Home Manager, would love to help

**Comment by Steven0351** [comment]
I'm a little late to the party here and new to Nix, but I have both x86_64 (macbook pro) and aarch64 (mac mini) darwin machines and would like to help out.

**Comment by CorbanR** [comment]
I also have a new M1 Max Mac and would like to contribute back to nix!

**Comment by ixnij** [comment]
I'm using an M1 MacBook Pro with Nix and home-manager, I'd love to help.

**Comment by domenkozar** [comment]
Invited @cideM, @Steven0351, @CorbanR and @ixnij

**Comment by joedevivo** [comment]
I'd like to help as well

**Comment by willcohen** [comment]
Would love to be added too!

**Comment by domenkozar** [comment]
Invited :)

**Comment by shaunsingh** [comment]
I'm using two m1 macbook pro's (and an old intel macbook) with nix/nix-darwin/hm as well. I would love to contribute

**Comment by lutzmor** [comment]
Hey i'm also a nix user on a macbook pro ( intel ) and a macbook air m1 :). Would love to help :).

**Comment by Sciencentistguy** [comment]
I use nix on my 2021 MBP (as well as nixos on other systems), would love to be a darwin maintainer.

**Comment by Artturin** [comment]
i'll unpin this as i need to pin https://github.com/NixOS/nixpkgs/issues/169193

**Comment by viraptor** [comment]
Hi, I've been doing a bit of Darwin fixing and semi-automatic checking of packages in the last couple months. I've been keeping an eye out for new packages and making sure people include the right frameworks where they're not aware of Darwin requirements. Currently testing Intel only, with arm migration coming end of the year.
I'd love to be included in the team.

**Comment by arulagrawal** [comment]
I'm using an M1 macbook pro, would love to help out.

**Comment by domenkozar** [comment]
@wegank would you like to be a maintainer?

**Comment by stephank** [comment]
I'd like to apply. I've been doing mostly low-level stuff (SDK, Swift, bootstrap, etc.), but also like helping out with packaging here and there.

**Comment by Et7f3** [comment]
I have x86_64-darwin (and x86_64-linux) and beginned to repair ocaml on Darwin package https://github.com/NixOS/nixpkgs/pull/209132 https://github.com/NixOS/nixpkgs/pull/197367 I would like to apply. Also can you update link to zero failure link ?

**Comment by amz-x** [comment]
I can help out with x86_64-darwin and x86_64-linux. I would be interested in becoming a package maintainer. Is the criteria to become a package maintainer similar to Fedora?

**Comment by domenkozar** [comment]
No criteria, help out and have fun. Added :)

**Comment by totoroot** [comment]
@domenkozar I've been using NixOS for a little over two years and Nix on x86_64-darwin for a few months now at work.
Recently I've started packaging and reviewing for darwin, so I'd like to become a darwin maintainer as well.

**Comment by CL0Pinette** [comment]
Hey,
I am using a mac M1. I'd love to crontribute, I use nix-darwin on my mac since 6 months.
I will also be able to help transposing packages from linux to darwin

**Comment by inclyc** [comment]
Hi NixOS folks! I am using a M1 macbook and currently using nix flakes on my system. I'd like to help with testing packages & reviewing PRs. I'm also working in the LLVM community (committer, clang, backends), if there are any toolchain issues please cc me :)

**Comment by domenkozar** [comment]
We really need help with maintaining GHC, two issues are blocking a lot of packages:

- https://github.com/NixOS/nixpkgs/issues/140774: the problem here is that dead code elimination in GHC isn't as good as on Linux, so we need to rewrite the Cabal patch to be maintainable
- https://github.com/NixOS/nixpkgs/issues/149692 here the linker segfaults, I've tried pinning a newer llvmPackages stdenv, but seems like linker always stays from llvmPackages_11.

**Comment by Xel** [comment]
Heyii folks, I use an M1 MacBook as well and use Nix quite heavily. Willing to help testing packages etc...

**Comment by berryp** [comment]
Can't help with the Haskell work but happy to help anywhere else I can.

**Comment by Atemu** [comment]
@milahu pretty sure you must be in the NixOS org to see that link. I can see the 51 members: https://github.com/orgs/NixOS/teams/darwin-maintainers/members

**Comment by Patryk27** [comment]
Hi, I've recently switched to M1 as well - aarch64 is love, aarch is life - and I'd like to help 🙂

**Comment by StepBroBD** [comment]
I'd love to help!
About 2 months into this new world with my old Intel MacBook and a new Apple Silicon MacBook.

**Comment by pupbrained** [comment]
Got an aarch64-darwin machine for helping out if needed :)
I could probably even help with aarch64-linux using Asahi NixOS.

**Comment by 0xMRTT** [comment]
I can help out with x86_64-darwin and x86_64-linux. I would be interested in becoming a package maintainer.

**Comment by n8henrie** [comment]
I'm relatively new but also interested in helping. Also on aarch64-darwin.

**Comment by yurrriq** [comment]
I've pinged the Nix guild at work, where there are some Darwin users.

**Comment by Eliot00** [comment]
I have both intel macbook and m2 mac mini, I would like to help.

**Comment by emilazy** [comment]
I would be happy to get darwin-maintainers pings and try to help fix breakage that looks tractable, although I know better than to promise reliable responses or to spend time actively scouting for issues/PRs that don't affect me. My `aarch64-darwin` machine is currently broken but I have access to `x86_64-darwin` and `x86_64-linux`. I have worked on Darwin issues in the past (e.g. https://github.com/NixOS/nixpkgs/pull/137605, https://github.com/NixOS/nixpkgs/pull/137741, https://github.com/NixOS/nixpkgs/pull/137870, https://github.com/NixOS/nixpkgs/pull/137942 (stalled out, alas), https://github.com/NixOS/nixpkgs/issues/238791).

**Comment by cidkidnix** [comment]
Hey I work at @obsidiansystems and we use darwin/MacOS quite a bit commercially (mostly for iOS),

Besides our use I'm happy to step up to help maintain mostly the haskell side of things with Darwin

**Comment by khaneliman** [comment]
I use nix to manage my mac configuration and have been trying to add / fix darwin support in derivations. You can add me to the list, too.

**Comment by iFreilicht** [comment]
I would also like to be added to the list. I've only just opened [my first darwin-specific PR](https://github.com/NixOS/nixpkgs/pull/266050) but have gotten other PRs merged in the past, either [as author](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr++is%3Aclosed+author%3AiFreilicht) or [as tester](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+commenter%3AiFreilicht).

**Comment by heywoodlh** [comment]
I would be happy to also be added to this list, have opened a couple of MacOS-specific PRs in the past few months. :smile:

**Comment by DontEatOreo** [comment]
I would like to help also! I daily drive `aarch64-darwin` on M1 Mac Mini

**Comment by siriobalmelli** [comment]
I'd like to volunteer.

Recently went all-in and I'm now running nix-darwin and home-manager on both aarch64-darwin and x86_64-darwin.

**Comment by matteo-pacini** [comment]
@domenkozar Would like to help too, I have access to both `aarch64-darwin` and `x86_64-darwin` machines.

Made a few PRs already, adding Darwin support to a few packages:
#318047 
#318535 
#319268 
#320122 

Also a few iOS developement tools I use at work:
#318906 
#317561

**Comment by afh** [comment]
Happy to be part of the Nix Darwin maintainers if helpful for the team 👋🙂.

I too have access to `aarch64-darwin` (daily driver) and `x86_64-darwin` and have contributed a few darwin related improvements to nixpkgs, for details see list of [PRs created (13)](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Aafh+label%3A%226.topic%3A+darwin%22+draft%3Afalse) and [PRs reviewed (10)](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+label%3A%226.topic%3A+darwin%22+draft%3Afalse+reviewed-by%3A%40me+) by me and labeled **6.topic darwin**.

**Comment by domenkozar** [comment]
For same reasons I resigned in https://github.com/NixOS/nixpkgs/issues/50105#issuecomment-2183067965, until moderation actions improve I'm no longer going to spend time here.
