### ISSUE TITLE
rebuild issues, grub

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#145249]
### Describe the bug
When i rebuild my system, the desktop session (pantheon) crashes and there are some grub errors.

https://youtu.be/OT5M4J9bEak

```
Nov 09 19:14:30 gaming kernel: failed to validate module [nf_tables] BTF: -22
Nov 09 19:14:30 gaming kernel: BPF:[79706] ENUM  
Nov 09 19:14:30 gaming kernel: BPF:size=4 vlen=22
Nov 09 19:14:30 gaming kernel: BPF: 
Nov 09 19:14:30 gaming kernel: BPF:Invalid name
Nov 09 19:14:30 gaming kernel: BPF:
```

### Steps To Reproduce
1. nixos-rebuild
2. desktop session crash, so i ran rebuild again in tty1 to avoid the shell session dissapear
3. see a lot of grub (i guess) errors (reproducible)

### Expected behavior
no crash, no errors

### Notify maintainers
pantheon maintainer @bobby285271: do you experience this as well?

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.05, nixos-21.11pre328987.c935f5e0add, nixos-hardware, nixos-unstable-21.11pre328987.c935f5e0add"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
iirc this can happen because of mismatched kernel and kernel header versions

**Comment by Mic92** [comment]
This seems to be independent from both pantheon and grub. I also get this with sway and systemd-boot.

**Comment by davidak** [comment]
FYI: at the time of writing the issue, it was reproducible every time i re-run the rebluild, but after i rebooted, i did not have the issue again. it's annoying and i had it in the past

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/149244 *may* fix this because i saw similar errors in journalctl when i got that issue
