### ISSUE TITLE
Manual: broken link "Examples of real-world NixOS configuration files can be found at"

### ISSUE THREAD

**Issue by respeccing** [NixOS/nixpkgs#14522]
## Issue description
A link, from the manual, that was working in the past day is now broken.

### Steps to reproduce
1. go to: https://nixos.org/nixos/manual/
2. search for "Examples of real-world NixOS configuration files can be found at"
3. click on the following link, which is: https://nixos.org/repos/nix/configurations/trunk/

**Comment by joachifm** [comment]
I have no idea where that repository went, so I propose we just delete that reference.

**Comment by puffnfresh** [comment]
https://github.com/search?q=language%3Anix+config might be a useful resource, if we want to link to something.

**Comment by joachifm** [comment]
It certainly is a useful resource; it strikes me that we'd better link to something "official" or at least curated in the manual, though. Perhaps someone could take the time to find "good" repos to link to? For a newbie it'll be quite difficult to tell what's what.

**Comment by joachifm** [comment]
That said, I don't think we need to hash out the details of a replacement to deal with this issue.

**Comment by copumpkin** [comment]
It appears to have existed up until at least a month ago: https://web.archive.org/web/20160313023242/https://nixos.org/repos/nix/configurations/trunk/
