### ISSUE TITLE
package/module request: tandoor recipes

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#145244]
**Project description**

A recipe manager app written in python with django, with the ability to use external sources of recipes, manage cookbooks, share recipes with other users, and create shopping lists from meal plans.

It recently got its 1.0 release.

**Metadata**

* homepage URL: https://tandoor.dev/
* source URL: https://github.com/TandoorRecipes/recipes
* license: agpl3 (not sure if later versions are allowed)
* platforms: all (it's a django web app)

**Comment by ambroisie** [comment]
For reference, my in-progress packaging branch is here https://github.com/ambroisie/nixpkgs/tree/add-tandoor-recipes, where I am in the process of:

* making the project's (comprehensive) test-suite pass
		* about ~30 tests are not passing at the moment, mostly due to problems that look to be related to my second point
* compile the front-end
		* this is a Vue front-end, which does not have a `yarn.lock` in the repo (see https://github.com/TandoorRecipes/recipes/issues/1091 about that)
		* after generating a `yarn.lock` and adding it to nixpkgs, the following error appears when trying to use `mkYarnModule`:

If any passer-by has more experience with `yarn`, `vue`, and `django`, I'd be glad to hear your input.
```
warning Lockfile has incorrect entry for "workbox-webpack-plugin@^4.3.1". Ignoring it.
error Couldn't find any versions for "workbox-webpack-plugin" that matches "^4.3.1" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ambroisie** [comment]
So upstream has a new version, with `yarn.lock` included in the sources.

I still have the same issue with the "incorrect entry" however...

**Comment by ulrikstrid** [comment]
As a workaround I use something like this:
```nix
{
  virtualisation.oci-containers.containers."tandoor-web" = {
    image = "vabene1111/recipes";
    environment = {
      "SECRET_KEY" = "super_secret";
      "DB_ENGINE" = "django.db.backends.postgresql";
      "POSTGRES_HOST" = "192.168.1.101";
      "POSTGRES_PORT" = "5432";
      "POSTGRES_USER" = "tandoor";
      "POSTGRES_PASSWORD" = "YOUR_POSTGRES_SECRET_KEY";
      "POSTGRES_DB" = "tandoor";
    };
    ports = [ "5080:8080" ];
    volumes = [
      "/home/delegator/tandoor/staticfiles:/opt/recipes/staticfiles"
      "/home/delegator/tandoor/mediafiles:/opt/recipes/mediafiles"
    ];
  };

  networking.firewall.allowedTCPPorts = [
    5080
  ];
}
```

**Comment by ambroisie** [comment]
@ulrikstrid I know I can use the upstream container, I'd rather have it running as an actual systemd service though, and I'm probably not the only one.

**Comment by ambroisie** [comment]
I had a breakthrough thanks to @yu-re-ka on [discourse](

**Comment by ambroisie** [comment]
I've got a first draft of the module set-up, see the `add-tandoor-recipes-module` branch on my nixpkgs fork.
It's probably not working correctly for now, but does pass the basic NixOS test I added.

@ulrikstrid @bachp would you want to try it out?
