### ISSUE TITLE
RFC: remove node packages

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#14532]
I just had a look at `node-packages-generated.nix`. While I didn't go through every single package basically any package that I picked out was utterly outdated. I sure hope nobody is relying on those packages and so I currently see little value in having those.

In https://github.com/NixOS/nixpkgs/issues/13103#issuecomment-186148878 @svanderburg comments:

> The only NPM packages that should be in Nixpkgs IMO are:
> - Command-line utilities/end-user programs
> - Library packages that are dependencies of non-NPM packages

**I would thus suggest** to do exactly that: remove most of `node-packages.json` leaving only what falls into one of the two categories above.

It is too bad that interfacing with npm is such a flakey business so the integration cannot be automated further to allow for up to date packages with less manual work. Which is exactly the reason why the scope of included node packages should be limited.

I'm happy to provide a PR if this OK with everyone. 

/cc @zimbatm @lo1tuma

**Comment by zimbatm** [comment]
+1

We should take the same approach as ruby where default patches are provided for common packages, mostly for adding the missing buildInputs.

Then developers use npm2nix (bundix with ruby) to generate the dependency list for each program that is going to be added to nixpkgs (or their own programs). Each program has their own dependency set but that's fine. Building a single plane of all the node packages, all working together is not a tenable solution as it's exponential in complexity and probably even not possible.

Note that if each npm package is in it's own derivation then it's still possible to share code between projects even if the dependency set is declared independently. Hopefully in the future we will have some tool that is capable to run over all of our node projects and tries to nudge versions together to reduce the overall closure size.

**Comment by flosse** [comment]
+1

**Comment by joachifm** [comment]
So, merge it?

**Comment by garbas** [comment]
+1

i think this should also be done for python packages. any thoughts on this @domenkozar @FRidh of-course not jumping into it but to gradually going toward that.

**Comment by FRidh** [comment]
@garbas 
Regarding Python, we have outdated packages, but many are still used. The problem is the burden of updating versions/urls/hashes manually, and that we have to resolve (https://github.com/NixOS/nixpkgs/issues/15480). While I don't know much about Node I suppose the problem is the same there in the end.

**Comment by bobvanderlinden** [comment]
Just to give another alternative, what I've done for my applications is generate `npm-shrinkwrap.json`, create a builder that runs `npm install` with the `npm-shrinkwrap.json`, remove varying files/options that `npm install` creates and `sha256` the entirety of the resulting `node_modules`.

An implementation of the builder I'm using can be found here: https://gist.github.com/bobvanderlinden/4d02b7fdc6f3c52eda188f95667e3915

The downside is that this only works for dependencies without compiled binaries, as the resulting `node_modules` must always be exactly the same. Won't work for all purposes, but did for my projects.

**Comment by matthewbauer** [comment]
Is it okay to close this? I think that we have gotten a lot better at updating these. At least this seems like a step in the wrong direction to me.

**Comment by JohnRTitor** [comment]
Closed per above discussion.
