### ISSUE TITLE
nix run nixpkgs#fortune does not run

### ISSUE THREAD

**Issue by aadibajpai** [NixOS/nixpkgs#145314]
### Describe the bug
I run the command
`nix run nixpkgs#fortune`
I expect it to give me a fortune cookie
However, I get this error
![image](https://user-images.githubusercontent.com/27063113/141065092-d483dfec-da57-4347-9cc8-6b4f6d5e852e.png)

### Steps To Reproduce
1. run `nix run nixpkgs#fortune`
2. ??
3. profit

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(clash): `"nixpkgs-21.11pre312229.08ef0f28e3a"`
 - nixpkgs: `/Users/clash/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by siraben** [comment]
Fix is to add `mainProgram = "fortune";` in https://github.com/NixOS/nixpkgs/blob/c935f5e0add2cf0ae650d072c8357533e21b0c35/pkgs/tools/misc/fortune/default.nix#L42
