### ISSUE TITLE
Rare: A frontend for legendary, the open source Epic Games Launcher alternative.

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#145386]
**Project description**
Rare is a GUI for Legendary, a command line alternative to Epic Games launcher.

**Metadata**

* homepage URL: https://github.com/Dummerle/Rare
* source URL: https://github.com/Dummerle/Rare
* license: gpl3
* platforms: linux

**Comment by WolfangAukang** [comment]
Merged
