### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by Stupremee** [NixOS/nixpkgs#145318]
**Project description**

Microsoft Edge is the fast and secure browser that helps you protect your data and save time and money.

Related to #101223 but Microsoft Edge is now stable on Linux.

**Metadata**

* homepage URL: https://www.microsoft.com/en-us/edge
* source URL: n/a
* license: ?
* platforms: linux, darwin

**Comment by nixinator** [comment]
can you point me to the source code repository and i can have a look at building this from source.

**Comment by robbins** [comment]
@nixinator It seems it's only available as a .deb.

There was a working (at some point) overlay for it: https://gitlab.com/zanc/overlays/-/blob/master/microsoft-edge-dev/default.nix but according to comments it no longer works.

**Comment by aanderse** [comment]
It would be great if someone could package this... it is becoming a "corporate standard" at a number of workplaces I hear, mine included.

**Comment by Stupremee** [comment]
I can try to do this!

**Comment by zanculmarktum** [comment]
It's fixed now: https://github.com/NixOS/nixpkgs/issues/101223#issuecomment-983745849

**Comment by Stupremee** [comment]
@zanculmarktum does this allow packaging of the new / stable Edge version?

**Comment by zanculmarktum** [comment]
@Stupremee: Sure, go head.

**Comment by zanculmarktum** [comment]
@Stupremee: Sure, go ahead.

**Comment by Stupremee** [comment]
Alright. Will send the PR later today

**Comment by zanculmarktum** [comment]
@kuwii: yeah, go ahead

**Comment by kuwii** [comment]
PR is created: #161064

**Comment by aserowy** [comment]
Heho,

using this issue (to not open a new one):
I switched from x11 to wayland (again :)) and built edge on my own. I stumbled over this package, changed my config and tried to start edge with ozone to target wayland, but all wayland specific libs are missing.
Are you planing to introduce those as well?

Kind regards
Alexander

**Comment by aserowy** [comment]
@zanculmarktum @kuwii (ping for maintainers)

**Comment by kuwii** [comment]
Hi @aserowy , sorry for the delay. I've created another PR #175158 which should work.

**Comment by aserowy** [comment]
Hey, ty for the work!

**Comment by abathur** [comment]
It looks like this was added in:
- https://github.com/NixOS/nixpkgs/pull/161064
