### ISSUE TITLE
Package naming rules

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#145344]
Since we have 4 ways to extend package:
`git` and `gitFull`
`vim` and `vim_configurable`
`ffmpeg` and `ffmpeg-full`
`gtk4` and `gtk4.dev`
It is hard to find all package variation and choose one for new one

Also [Package naming](https://nixos.org/manual/nixpkgs/stable/#sec-package-naming) manual have no agreement for this issue.

What should I choose for new one?
How can I fast find all package variation?

**Comment by Artturin** [comment]
> Since we have 4 ways to extend package: `git` and `gitFull` `vim` and `vim_configurable` `ffmpeg` and `ffmpeg-full` `gtk4` and `gtk4.dev` It is hard to find all package variation and choose one for new one

i agree with renaming `xFull` packages to `x-full

vim_configurable is a nix configurable version of vim

gtk4.dev is a output of gtk4, not a separate package

**Comment by psydvl** [comment]
Then why `vim_configurable` rather `vim.configurable` or `vim-configurable`?

**Comment by Artturin** [comment]
> Then why `vim_configurable` rather `vim.configurable` 
we could probably do that with passthru attributes

> or `vim-configurable`?

iirc in 2007 when vim_configurable was added, package names didn't support `-`

**Comment by Artturin** [comment]
#145351
