### ISSUE TITLE
fix darwin build of unar

### ISSUE THREAD

**Issue by Artturin** [NixOS/nixpkgs#145368]
> It would be interesting to know if this is compatible enough with unrar so we could use it in place of unrar in some packages that nowadays depends on it optionally (like calibre and mcomix).

Sadly `unar` doesn't build on macOS right now, so we can't use this on macOS.

If someone could make `unar` work on macOS, it would be great. I did try to do it here but could get it to fix the link issue: https://github.com/thiagokokada/nixpkgs/commit/2e0db0e7475b3d3af01c06b3d8333566dff74e48

_Originally posted by @thiagokokada in https://github.com/NixOS/nixpkgs/issues/145229#issuecomment-965327235_

**Comment by thiagokokada** [comment]
If someone wants to know what is the link error I am getting, here is the build log: http://ix.io/3EBa

The error:

```
ld: file not found: /nix/store/q52ki50zqgjp75r4ng4q50aqbpdzc3ra-clang-7.1.0/lib/arc/libarclite_macosx.a
```

As far I understand searching, `libarclite_macosx.a` is proprietary so we can't link to it directly. Still, I am really curious on why it is trying to build with ARC enabled since I am not passing `-fobjc-arc` as parameter to `xcodebuild`.

**Comment by veprbl** [comment]
@thiagokokada Have you tried passing `-fno-objc-arc`?

**Comment by thiagokokada** [comment]
> @thiagokokada Have you tried passing `-fno-objc-arc`?

Not sure how to pass it, I tried this: https://github.com/thiagokokada/nixpkgs/commit/ed3fbec9a46bd931c74d28a91fa674b5d96c5446

Same error.

**Comment by thiagokokada** [comment]
To make it clear: it doesn't seem that `xcodebuild` is picking this option. Searching from my buffer if it was being passed I didn't found any references for `-fno-objc-arc`.

**Comment by veprbl** [comment]
@thiagokokada 
Here is a tip: you can check compiler flags by passing `NIX_DEBUG=6;` to `mkDerivation`

**Comment by thiagokokada** [comment]
> @thiagokokada Here is a tip: you can check compiler flags by passing `NIX_DEBUG=6;` to `mkDerivation`

It does seem to be passing it, but linker still tries to link with `libarclite_macosx.a`.

I also tried this. Same thing:

```diff
diff --git a/pkgs/tools/archivers/unar/default.nix b/pkgs/tools/archivers/unar/default.nix
index 9c3eedb8ffe..2d15b11208b 100644
--- a/pkgs/tools/archivers/unar/default.nix
+++ b/pkgs/tools/archivers/unar/default.nix
@@ -52,13 +52,12 @@ stdenv.mkDerivation rec {
     lib.optionals stdenv.isLinux [ gnustep.make ] ++
     lib.optionals stdenv.isDarwin [ xcbuildHook ];

-  NIX_CFLAGS_COMPILE = lib.optionals stdenv.isDarwin [ "-fno-objc-arc" ];
-
   buildPhase =
     if stdenv.isDarwin then ''
       for target in XADMaster unrar lsar; do
         xcodebuild -target "$target" -project "./XADMaster.xcodeproj" \
-          -configuration Release SYMROOT=build MACOSX_DEPLOYMENT_TARGET=10.12
+          -configuration Release SYMROOT=build MACOSX_DEPLOYMENT_TARGET=10.12 \
+          -OTHER_CFLAGS="-fno-objc-arc"
       done
     '' else ''
       make -f Makefile.linux
```

**Comment by veprbl** [comment]
This works here:
```diff
diff --git a/pkgs/tools/archivers/unar/default.nix b/pkgs/tools/archivers/unar/default.nix
index b55a0704949..36b12627f52 100644
--- a/pkgs/tools/archivers/unar/default.nix
+++ b/pkgs/tools/archivers/unar/default.nix
@@ -29,8 +29,6 @@ stdenv.mkDerivation rec {
     if stdenv.isDarwin then ''
       substituteInPlace "./XADMaster.xcodeproj/project.pbxproj" \
         --replace "libstdc++.6.dylib" "libc++.1.dylib"
-      # we need to build inside this directory as well, so we have to make it writeable
-      chmod +w ../UniversalDetector -R
     '' else ''
       for f in Makefile.linux ../UniversalDetector/Makefile.linux ; do
         substituteInPlace $f \
@@ -52,15 +50,16 @@ stdenv.mkDerivation rec {
     lib.optionals stdenv.isLinux [ gnustep.make ] ++
     lib.optionals stdenv.isDarwin [ xcbuildHook ];
 
-  NIX_CFLAGS_COMPILE = [ "-fno-objc-arc" ];
+  xcbuildFlags = [
+    "-target unar"
+    "-target lsar"
+    "-configuration Release"
+    "MACOSX_DEPLOYMENT_TARGET=10.12"
+    "CLANG_LINK_OBJC_RUNTIME=NO"
+  ];
 
   buildPhase =
-    if stdenv.isDarwin then ''
-      for target in XADMaster unrar lsar; do
-        xcodebuild -target "$target" -project "./XADMaster.xcodeproj" \
-          -configuration Release SYMROOT=build MACOSX_DEPLOYMENT_TARGET=10.12
-      done
-    '' else ''
+    lib.optionalString (!stdenv.isDarwin) ''
       make -f Makefile.linux
     '';
 
@@ -73,7 +72,7 @@ stdenv.mkDerivation rec {
   installPhase = ''
     runHook preInstall
 
-    install -Dm555 -t $out/bin lsar unar
+    install -Dm555 -t $out/bin ${lib.optionalString stdenv.isDarwin "Products/Release"}/{lsar,unar}
     for f in lsar unar; do
       installManPage ./Extra/$f.?
       installShellCompletion --bash --name $f ./Extra/$f.bash_completion
```

**Comment by thiagokokada** [comment]
> This works here:

Thanks @veprbl. Finally it works.

Just doing some checks and clean-up and I am going to open a PR.

**Comment by panda2134** [comment]
> If someone wants to know what is the link error I am getting, here is the build log: http://ix.io/3EBa
> 
> The error:
> 
> ```
> ld: file not found: /nix/store/q52ki50zqgjp75r4ng4q50aqbpdzc3ra-clang-7.1.0/lib/arc/libarclite_macosx.a
> ```
> 
> As far I understand from searching, `libarclite_macosx.a` is proprietary so we can't link to it directly. Still, I am really curious on why it is trying to build with ARC enabled since I am not passing `-fobjc-arc` as parameter to `xcodebuild`.

Maybe we should use Text API files, similar to what we do when linking against `Cocoa.Framework`?
