### ISSUE TITLE
LLVM 3.8 fails to build on OS X 10.11

### ISSUE THREAD

**Issue by bsmt** [NixOS/nixpkgs#14542]
## Issue description
Seems like it's just a hash mismatch, but I'm not certain.

```
~ > nix-env -i llvm
installing ‘llvm-3.8.0’
these derivations will be built:
  /nix/store/08fy4bggcvgck44jsds0kzaa3md5n1x2-libcxxabi-3.8.0.src.tar.xz.drv
  /nix/store/fyz4jqrccjqfl3cm5n2if4bvdl6k3c9i-libcxx-3.8.0.src.tar.xz.drv
  /nix/store/k04fx9qdz339dy3hpf0k4vpsqw8m0gp0-libc++abi-3.8.0.drv
  /nix/store/jjnfrdz0cj91zdixssbshbbd3wnj9z81-llvm-3.8.0.drv
building path(s) ‘/nix/store/qzdqpri06k1im9kdl3gr80ii5dksmbsb-libcxx-3.8.0.src.tar.xz’
trying http://llvm.org/releases/3.8.0/libcxx-3.8.0.src.tar.xz
output path ‘/nix/store/qzdqpri06k1im9kdl3gr80ii5dksmbsb-libcxx-3.8.0.src.tar.xz’ has sha256 hash ‘0yr3fh8vj38289b9cwk37zsy7x98dcd3kjy7xxy8mg20p48lb01n’ when ‘0i7iyzk024krda5spfpfi8jksh83yp3bxqkal0xp76ffi11bszrm’ was expected
cannot build derivation ‘/nix/store/k04fx9qdz339dy3hpf0k4vpsqw8m0gp0-libc++abi-3.8.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/jjnfrdz0cj91zdixssbshbbd3wnj9z81-llvm-3.8.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jjnfrdz0cj91zdixssbshbbd3wnj9z81-llvm-3.8.0.drv’ failed
```

### Steps to reproduce

`nix-env -i llvm-3.8.0`

## Technical details

* System: OS X 10.11
* Nix version: nix-env (Nix) 1.11.2

* Nixpkgs version: Given command doesn't work, likely due to my configuration, but nix-channel --update downloads from nixpkgs-16.09pre80183.551296a

**Comment by bsmt** [comment]
Alright, after fixing the hash issue, both libcxx and libc++abi needed to be changed, I ran into another issue. When building sanitizer_mac.cc in compiler-rt, the compiler spits something like this out:
```
/private/var/folders/gn/bmrb7z1x36x57qvfl77myt140000gn/T/nix-build-llvm-3.8.0.drv-0/llvm/projects/co
mpiler-rt/lib/sanitizer_common/sanitizer_mac.cc:446:55: error: too few arguments provided to functio
n-like macro invocation
        os_trace("Address Sanitizer reported a failure.");

/nix/store/5rcaaig3p888kagqx66l0mran7f2j88r-Libsystem-osx-10.9.5/include/os/trace.h:46:9: note: macro 'os_trace' defined here
#define os_trace(tag, fmt, ...) __extension__({\

/private/var/folders/gn/bmrb7z1x36x57qvfl77myt140000gn/T/nix-build-llvm-3.8.0.drv-0/llvm/projects/co
mpiler-rt/lib/sanitizer_common/sanitizer_mac.cc:446:7: error: use of undeclared identifier 'os_trace
'; did you mean '_os_trace'?
      os_trace("Address Sanitizer reported a failure.");
      ^~~~~~~~
      _os_trace
/nix/store/5rcaaig3p888kagqx66l0mran7f2j88r-Libsystem-osx-10.9.5/include/os/trace.h:35:1: note: '_os
_trace' declared here                                                                              
_os_trace(const char *msg, ...);
```
Since the 3.8 nix expressions were basically copy-pasted from 3.7, as shown by the hash error, and llvm 3.7 evidently built fine for OS X, this is strange. I'll try building everything outside of nix and see what happens.

**Comment by acowley** [comment]
Hey @bsmt, did you have any luck building outside of nix?

**Comment by bsmt** [comment]
yep, everything works fine.

**Comment by acowley** [comment]
I can get this to build if I update the hashes and replace calls to `os_trace` with `printf` in `sanitizer_mac.cc` in a darwin-only patch. The latter is a horrible hack, but properly fixing it would -- I think -- require updating to a newer OS X DevSDK. I am not sure how much of an issue that would be in terms of dropping support for older OS X host systems (I do not know if it would be an issue at all, to be honest).

I can open a PR with the `printf` hack if other people are interested in using LLVM- and clang-3.8 on OS X. Switching to the new SDK is a somewhat bigger job that we should perhaps track in a separate Issue or PR.

It also turns out that llvm_38 for linux is in the hydra cache despite the hashes apparently being incorrect. I do not know how to interpret that reality (thanks to @obadz for letting me know about this weirdness).

While I can run clang_38 in nix-shell, I am currently unable to install it into my darwin user environment due to this error,

```
$ nix-env -iA nixpkgs.clang_38
installing ‘clang-wrapper-3.8.0’
building path(s) ‘/nix/store/dj78g0i2w5z39wfaz5x2yd61y6lmdx2b-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 87.
error creating link ‘/nix/store/dj78g0i2w5z39wfaz5x2yd61y6lmdx2b-user-environment/share’: File exists at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 87.
builder for ‘/nix/store/c7bjx2q5r79f77g9fr00pjf63zhh4fx9-user-environment.drv’ failed with exit code 17
error: build of ‘/nix/store/c7bjx2q5r79f77g9fr00pjf63zhh4fx9-user-environment.drv’ failed
```

Which looks a bit like https://github.com/NixOS/nix/issues/468

*cc* @copumpkin @shlevy

**Comment by obadz** [comment]
```
<nixpkgs>/pkgs/development/compilers/llvm$ grep -sr 0i7iyzk024krda5spfpfi8jksh83yp3bxqkal0xp76ffi11bszrm
3.7/libc++/default.nix:  src = fetch "libcxx" "0i7iyzk024krda5spfpfi8jksh83yp3bxqkal0xp76ffi11bszrm";
3.8/libc++/default.nix:  src = fetch "libcxx" "0i7iyzk024krda5spfpfi8jksh83yp3bxqkal0xp76ffi11bszrm";
```

Copy/paste symdrome?

**Comment by acowley** [comment]
obadz: Yes, @bsmt [suggested this](https://github.com/NixOS/nixpkgs/issues/14542#issuecomment-208092429), but it doesn't explain (to me) how it is that you can pull a binary from the cache despite that problem.

**Comment by obadz** [comment]
llvm-38 installs, but does not depend on libcxx-3.8 (except apparently on darwin)
