### ISSUE TITLE
libpkgconf does not install pkg-config files

### ISSUE THREAD

**Issue by dcbaker** [NixOS/nixpkgs#145565]
### Describe the bug
A libpgkconf.pc file should be installed, but is not. This file is generated and installed by both the autotools and meson build systems, so it seems like it's getting lost somewhere along the way in the nix packaging process

### Steps To Reproduce
1. install libpkgconf
2. pkg-config libpkgconf --exists

### Expected behavior
the pkg-config file to be installed and be usable

### Notify maintainers
@zaninime 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.16, NixOS, 21.05.4029.ce48bcdde86 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.05, nixos-21.05.4029.ce48bcdde86, nixos-hardware, nixos-unstable-21.11pre328987.c935f5e0add"`
 - channels(dylan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
The libpkgconf.pc file is in the dev output like is standard in nixpkgs 
`libpkgconf.dev`

**Comment by dcbaker** [comment]
This is actually the first time I've ever had to explicitly install the .dev package
