### ISSUE TITLE
Lockups on Kernel 5.10.77 with amdgpu

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#145599]
### Describe the bug
Shortly after X login, computer hard-locks.

### Steps To Reproduce
1. Own an AMD GPU
2. Use `amdgpu` driver
3. Attempt to log in.

### Additional context

```console
$ nixos-version --json
{"nixosVersion":"21.05.20211108.e748941","nixpkgsRevision":"e74894146a42ba552ebafa19ab2d1df7ccbc1738"}

$ uname -r
5.10.77
```

Kernel patch [0db55f9a1bafbe3dac750ea669de9134922389b5](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/patch/?id=0db55f9a1bafbe3dac750ea669de9134922389b5) introduced the bug, and kernel patch [bbc920fb320f1c241cc34ac85edaa0058922246a](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/patch?id=bbc920fb320f1c241cc34ac85edaa0058922246a) fixed it:

> Seems that the older kernels can not handle this fix because, to quote Christian:
>
>> The problem is this memory leak could potentially happen with 5.10 as wel [sic], just much much much less likely.
>>
>> But my guess is that 5.10 is so buggy that when the leak does NOT happen we double free and obviously causing a crash.
>
> So it needs to be reverted.

I have added patch bbc920fb320f1c241cc34ac85edaa0058922246a to my `boot.kernelPatches` and can vouch for it.

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.77, NixOS, 21.05.20211108.e748941 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"home-manager-21.05, nixos-21.05.3801.83667ff60a8, nixos-emacs, nixos-unstable-21.11pre323695.9aeeb7574fb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vdot0x23** [comment]
I believe I ran in to the same bug on Wayland. Out of curiosity, how did you manage to determine the cause? I could not find it in dmesg (maybe i just overlooked it?).

**Comment by endgame** [comment]
Dumb luck. I just happened to be asking how to find the nixpkgs my nixos was built with, at the same time as some other guy was asking about crashes in `amdgpu`. Saved me a good few hours of `git bisect`.

**Comment by Nekdo** [comment]
I belive I hit the same issue. 
I just reported it here: #145601 
I also own AMD GPU

**Comment by jkarlson** [comment]
just note the kernel is in latest released stable kernel so just kernel update to 5.10.78 will fix this issue

**Comment by Elinvention** [comment]
I can confirm that updating to 5.10.78 fixed the issue.

**Comment by TredwellGit** [comment]
https://nixpk.gs/pr-tracker.html?pr=145358

**Comment by dotrosedotnet** [comment]
> I can confirm that updating to 5.10.78 fixed the issue.

how do I update the kernel at this time?
