### ISSUE TITLE
bazel_4 fails to build on macOS Monterey

### ISSUE THREAD

**Issue by uri-canva** [NixOS/nixpkgs#145590]
### Describe the bug

Upstream bug: https://github.com/bazelbuild/bazel/issues/14216

### Steps To Reproduce
1. Build `bazel_4` on macOS Monterey

### Expected behavior
Successful build.

### Notify maintainers
@mboes 

### Metadata
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixpkgs-21.11pre329388.f096b7122ab, darwin"`
 - channels(uri): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by wegank** [comment]
Closed by #147649.
