### ISSUE TITLE
mupen64plus fails to build on 16.03

### ISSUE THREAD

**Issue by AveryGlitch** [NixOS/nixpkgs#14569]
## Issue description
Not a high priority, but may be an indicator of some more serious issues: mupen64plus has failed to build (on my system, and [on hydra](https://hydra.nixos.org/job/nixos/release-16.03/nixpkgs.mupen64plus.x86_64-linux)) since the 11th of March. It's still fine and working on 15.09 (according to hydra).

### Steps to reproduce
Try to install mupen64plus on 16.03

## Technical details

* System: (NixOS: 16.03.280.531baf8)
* Nix version: 1.10
* Nixpkgs version: same as system

**Comment by joachifm** [comment]
Looks like fallout from the switch to gcc5. Pushed a work-around at 9a55b76db1a00dd735ab82b1c7c030ee6705ca89, will add it to the release as well.

**Comment by dezgeg** [comment]
Maybe `NIX_CFLAGS_COMPILE = "-fgnu89-inline";` could help as well.

**Comment by joachifm** [comment]
I tried both that and `gnu89`; they fix the inline errors but the build still fails with an undefined reference error.

**Comment by joachifm** [comment]
I think this is "fixed"; binaries probably won't show up on the release channel for a while, though, but that can't (or won't) be helped.
