### ISSUE TITLE
postcss-cli fails to start, unable to find postcss package

### ISSUE THREAD

**Issue by dominikh** [NixOS/nixpkgs#145618]
### Describe the bug
postcss-cli fails to start.

### Steps To Reproduce
1. `nix run nixpkgs.postcss-cli -c postcss`

### Expected behavior
No error.

### Screenshots
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'postcss' imported from /nix/store/ghljficzrf7kc09l7cbz04mrmaql9d2h-postcss-cli-9.0.2/lib/node_modules/postcss-cli/index.js
Did you mean to import postcss-8.3.11/lib/node_modules/postcss/lib/postcss.js?
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Additional context
`git bisect` points to 2d1cfc588248909680b6800dc26d0c1385287092.

### Notify maintainers
@Luflosi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.7, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.11pre329879.c5ed8beb478"`
 - channels(dominikh): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Luflosi** [comment]
I spent quite some time trying to figure this out but I just don't understand Node.js well enough to fix this, sorry.

**Comment by mlazowik** [comment]
```
[nix-shell:~]$ cat /nix/store/r5mxrik0kryxx0k8msk0kw4ajqbc8dkb-postcss-cli-9.1.0/bin/postcss 
#! /nix/store/iqprjr5k5385bhf1dzj07zwd5p43py1n-bash-5.1-p12/bin/bash -e
export NODE_PATH='/nix/store/cqfyz9nvpvhanbj58mh204rjfhaks29k-postcss-8.4.5/lib/node_modules'${NODE_PATH:+':'}$NODE_PATH
export NODE_PATH='/nix/store/vkiynyr2qrgfa027kzcs6j93ay049hji-autoprefixer-10.4.0/lib/node_modules'${NODE_PATH:+':'}$NODE_PATH
exec -a "$0" "/nix/store/r5mxrik0kryxx0k8msk0kw4ajqbc8dkb-postcss-cli-9.1.0/bin/.postcss-wrapped"  "$@"
```

`esm` does not support `NODE_PATH`, see https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#432-removal-of-non-local-dependencies

**Comment by mlazowik** [comment]
ref https://github.com/NixOS/nixpkgs/pull/130027/files

Maybe since then `postcss` moved from something else to esm? Not sure.

**Comment by GuillaumeRochat** [comment]
Could this actually be because `postcss-cli` (the bin) lists `postcss` (the lib) as a peerDependency since version 8 https://github.com/postcss/postcss-cli/blob/8.0.0/package.json#L46

Whenever node2nix runs, it doesn't check for peer dependencies so `postcss` (the lib) is not included. According to the node-packages.nix on master, the postcss-cli does not have postcss in its dependencies.

**Comment by mlazowik** [comment]
Nah, I have `postcss` installed at the path that is added to `NODE_PATH` in the `postcss-cli` bin wrapper and it still does not work.

**Comment by mlazowik** [comment]
Ha, they did move to esm pretty recently: https://github.com/postcss/postcss-cli/commit/10f2603c8ffd24b19c62037e8f27ab97e46afcd2

**Comment by mlazowik** [comment]
I guess replace the `NODE_PATH` wrapping with a symbolic link post install and it should work?

**Comment by Luflosi** [comment]
Thanks for the awesome insight. I'll try this tomorrow if I have some time.

**Comment by Luflosi** [comment]
I created #166804 to fix this.
