### ISSUE TITLE
Python astroid fails to build.

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nixpkgs#145669]
### Describe the bug
The bug is that I get this error when I run `nix-env -i poetry`.
```


tests/unittest_brain.py:1224: AssertionError
=========================== short test summary info ============================
FAILED tests/unittest_brain.py::TypingBrain::test_typing_alias_type - Asserti...
====== 1 failed, 912 passed, 36 skipped, 14 xfailed, 1 xpassed in 13.83s =======
error: builder for '/nix/store/84qlmiwsgz0dlz96jy8228xs3kyd0c4q-python3.9-astroid-2.5.1.drv' failed with exit code 1;
       last 10 log lines:
       >         assert isinstance(meta, nodes.ClassDef)
       > >       assert meta.name == "ABCMeta_typing"
       > E       AssertionError: assert 'Meta' == 'ABCMeta_typing'
       > E         - ABCMeta_typing
       > E         + Meta
       >
       > tests/unittest_brain.py:1224: AssertionError
       > =========================== short test summary info ============================
       > FAILED tests/unittest_brain.py::TypingBrain::test_typing_alias_type - Asserti...
       > ====== 1 failed, 912 passed, 36 skipped, 14 xfailed, 1 xpassed in 13.83s =======
```
I get the error while it is testing python astroid builds. It says testing python astroid then it fails.

### Steps To Reproduce
1.  run nix-env -i poetry
2. ...
3. ...

### Expected behavior
I expected the package to be installed normally.

### Screenshots
Here is a screenshot of my term!

![2021-11-12_19-53](https://user-images.githubusercontent.com/24791219/141519986-c1dbf2c9-d87e-4da1-9398-62b5dc960d2c.png)
### Additional context

I am new to NixOS so please, shout at me if I am stupid!

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.05.3916.3b1789322fc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(drzoidberg): `"home-manager-21.05, nixgl, nixos-unstable-21.11pre328987.c935f5e0add"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`




```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
Please try updating as this should be fixed now

**Comment by jakobneufeld** [comment]
I will try. I am running `nix-channel --update`

**Comment by jakobneufeld** [comment]
Thanks! It worked!
I will try installing pylint, a package which depends on astroid. Then I will close this issue! Thabks @Artturin for answering so quickly! Also I have a question, I am working on a wrapper on the nixcli and how do I publish it nixpkgs. Can you send me a link to a wiki page?

**Comment by jakobneufeld** [comment]
Pylint fails to install, but who cares! I will close this issue now!

**Comment by Artturin** [comment]
Why does pylint fail

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md

**Comment by jakobneufeld** [comment]
Same error as poetry!

**Comment by Artturin** [comment]
Builds for me on nixos-unstable branch. Perhaps you have something weird going on with your channels
