### ISSUE TITLE
bespokesynth: possible license violation in the derivation

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#145607]
It has been reported in the inofficial community discord, that the derivation might cause an access violation by using and redistributing files that it is not allowed to.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/bespokesynth/default.nix#L39-L48

It seems as if that file is used to compile a VST2 plugin, which is not allowed by the rights owner for the VST2 SDK as it seems:

https://developer.steinberg.help/pages/viewpage.action?pageId=9797948#Whichfilesfallunderwhichlicense?-What%C2%B4saboutVST2?

This page claims, that it is only allowed to distribute the binary form of a plugin if the distributor has written permission older than October 2018.

I therefore propose to build the package without VST support or mark it as unfree, then the "distribution" problem is not nixpkgs anymore.

It might also make sense to remove affected artifacts from hydra/binary cache to ensure that we can not made responsible for "redistribution"

### Notify maintainers

@astro

Also @edolstra and @grahamc as those names often appear as beeing legally responsible for the nix ecosystem

**Comment by NobbZ** [comment]
It has been mentioned in the same channel that there might be even more derivations suffer from this problem, they mentioned the next one as an example:

https://github.com/NixOS/nixpkgs/blob/371ffbd25e4b983141dacc518c0c0289bed0ffc5/pkgs/applications/audio/oxefmsynth/default.nix#L8

**Comment by tobiasBora** [comment]
This is really stupid law, especially considering that the creator of BespokeSynth does have such license. Maybe we could create two packages:
- one, marked as non-free, which is not cached by Hydra but that contains the VST2 SDK
- one cached by Hydra without VST2 support (the latest version do have VST3 support though, but won't be compatible with VST2)
For the second program, I made a derivation for the VST3 plugin [Ildaeil](https://github.com/DISTRHO/Ildaeil) that can load LV2 plugins:
![image](https://user-images.githubusercontent.com/2164118/141495314-199567a2-c14e-4de7-bf3b-a52731382788.png)

Note however the the author [said that the package is too young to be officially packaged](https://github.com/DISTRHO/Ildaeil/issues/3). For it to work, you also need to have all your plugins in `~/.lv2` (it's [not reading `$LV2_PATH`](https://github.com/DISTRHO/Ildaeil/issues/4)).

```
{ lib
, stdenv
, fetchFromGitHub
, cmake
, pkg-config
# Not sure which one I should keep (at least libGL for sure)
, liblo
, freetype, libX11, libXrandr, libXinerama, libXext, libXcursor, libGL
, gtk2, gtk3
, libjack2, alsa-lib, alsa-tools
}:

stdenv.mkDerivation rec {
  pname = "Ildaeil";
  version = "unstable-b1b71590";

  src = fetchFromGitHub {
    owner = "DISTRHO";
    repo = pname;
    rev = "b1b71590af50a8dcffb83eaeee832115fbe5baab";
    sha256 = "sha256-YSdGucOhHVL8E49f0GgayvgP9aqV5B68zrOHmBa6GT0=";
    fetchSubmodules = true;
  };

  nativeBuildInputs = [
    # cmake
    pkg-config
  ];
  buildInputs = [
    liblo
    freetype
    libX11 libXrandr libXinerama libXext libXcursor libGL
    gtk2 gtk3
    libjack2 alsa-lib alsa-tools
  ];

  buildPhase = ''
    patchShebangs dpf/utils/generate-ttl.sh
    make
  '';

  # No VST2 available?
  installPhase = ''
    mkdir -p $out/lib/{vst3,lv2,}
    cp -r bin/*.lv2 $out/lib/lv2
    cp -r bin/*.vst3 $out/lib/vst3
  '';
}
```

**Comment by NobbZ** [comment]
> especially considering that the creator of BespokeSynth does have such license

They have, not the nix eco system though.I'm wondering how other distributions deal with this case.

Though it seems as if its just not packaged by them:

https://repology.org/project/bespokesynth/versions

**Comment by grahamc** [comment]
I agree we should remove VST2 support by default. If VST2 is enabled we should probably change the license from gpl3Plus to `[ g4l3Plus unfree ]`, possibly creating a custom license in-line to refer to the very specific license used in this case. We have not often removed software from the cache, but we should do that in this case. We can query Hydra for the relevant closures.

**Comment by grahamc** [comment]
- [ ] Remove VST2 support from bespokesynth by default
- [ ] Optionally, create a `bespokesynthWithVST2` attribute which enables VST2 and has an unfree license.

**Comment by grahamc** [comment]
@astro can you address the licensing issues? I've opened #145766 as a stopgap.

**Comment by tobiasBora** [comment]
I've updated my ongoing PR https://github.com/NixOS/nixpkgs/pull/144708/

**Comment by astro** [comment]
IIRC I copied the VST2 stuff from another pkg.

**Comment by SuperSandro2000** [comment]
I think we can close this as this issue has been fixed in the commit linked 4 messages above.
