### ISSUE TITLE
ip vrf exec fails with BPF error

### ISSUE THREAD

**Issue by Lillecarl** [NixOS/nixpkgs#145673]
### Describe the bug
ip vrf exec is used to run commands inside a vrf-lite (thanks CumulusNetworks). It's really just multiple active routing tables, but without network namespaces.

### Steps To Reproduce
```
Script started on 2021-11-12 20:27:09+01:00 [TERM="screen" TTY="/dev/pts/3" COLUMNS="96" LINES="51"]
➜  ~ ip vrf list
Name              Table
-----------------------
vpn               1337
➜  ~ ip vrf exec vpn ping 1.1.1.1
Failed to load BPF prog: 'Operation not permitted'
➜  ~ sudo ip vrf exec vpn ping 1.1.1.1
[sudo] password for lillecarl:
Failed to load BPF prog: 'Operation not permitted'
➜  ~ exit

Script done on 2021-11-12 20:27:31+01:00 [COMMAND_EXIT_CODE="255"]
```

```
  systemd = {
    network = {
      enable = true;
      netdevs."vpn" = {
        enable = true;
        vrfConfig = {
          Table = 1337;
        };
        netdevConfig = {
          Kind = "vrf";
          Name = "vpn";
        };
      };
    };
  };
```

### Expected behavior
An error saying no route to host, unless you have routes in the VRF

### Additional context
VRF means Virtual Routing and Forwarding. Having multiple routing tables is an essential feature to any router. It is also useful for a system running as a hypervisor, since you (like with VLANs) can isolate networks, but on layer 3 rather than layer 2. 

### Notify maintainers

Not entirely sure who to ping here, could be kernel, could be userspace.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.05.3990.372e59d2af7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.3990.372e59d2af7, nixos-hardware, unstable-21.11pre327669.b67e752c29f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
not:
  sure: 1
```

Have not tested nixos-unstable.

**Comment by Anillc** [comment]
I upgraded the kernel to 5.15.0 and it worked

**Comment by Lillecarl** [comment]
@Anillc I can't go that high yet because of evdi and other kernel modules. But great to know, I'll leave this open until a stable release has this resolved.

**Comment by Ma27** [comment]
Don't you need a higher memlock for `ip vrf exec`?
I have

``` nix
{
  security.pam.loginLimits = [
    { domain = "*"; item = "memlock"; type = "-"; value = 8192; }
  ];
}
```

**Comment by Lillecarl** [comment]
@Ma27 That resolved the issue straight away, just a NixOS reload. Thank you. I don't think the issue is resolved however, I'm not sure if we should have to set this configuration ourselves or "have someone do it for us"

**Comment by Ma27** [comment]
I actually had similar issues when I moved to a 5.x Kernel a while ago, it was clarified by the kernel developers that this is expected behavior: https://lore.kernel.org/netdev/2583bdb7-f9ea-3b7b-1c09-a273d3229b45@gmail.com/

> > I can work around the issue by using `ip vrf exec`. However I get the
> > following error (unless I run `ulimit -l 2048`):
> > 
> > ```
> > Failed to load BPF prog: 'Operation not permitted'
> > ```
>
> 'ip vrf exec' loads a bpf program and that requires locked memory, so
> yes, you need to increase it.

**Comment by Lillecarl** [comment]
@Ma27 Is it sane defaults to keep this at 0 though? With Debian and Ubuntu I haven't seen this issue.

In a never version of the iputils it seems the error message is clearer though.

**Comment by anp135** [comment]
According to https://man7.org/linux/man-pages/man8/ip-vrf.8.html, you need to have **CAP_SYS_ADMIN**, **CAP_NET_ADMIN** and **CAP_DAC_OVERRIDE** capabilities for successfull run `ip vrf exec` code.

The same case with systemd unit runing with `ExecStart=ip vrf exec` - when run by hand all works and systemd fault with `ip[]: Failed to load BPF prog: 'Operation not permitted'` message

**Comment by Ma27** [comment]
What does "when run by hand mean"? Which user did you use? Did you use `sudo`? Did you increase the memlock before?

Also, please share the *full* unit including the logs, a single ExecStart isn't really helpful.

**Comment by anp135** [comment]
> What does "when run by hand mean"? Which user did you use? Did you use `sudo`? 

By hand I mean run 'ip vrf exec' in system shell. root user or sudo user - there is not matter.


> Did you increase the memlock before?

no of course. memlock reason will provide segmentation fault. Try to set ulimits -s 0 and run ip vrf exec.

 
> Also, please share the _full_ unit including the logs, a single ExecStart isn't really helpful.

```
# systemctl cat openvpn-client@.service
# /lib/systemd/system/openvpn-client@.service
[Unit]
Description=OpenVPN tunnel for %I
After=network-online.target
Wants=network-online.target
Documentation=man:openvpn(8)
Documentation=https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
Documentation=https://community.openvpn.net/openvpn/wiki/HOWTO

[Service]
Type=notify
PrivateTmp=true
WorkingDirectory=/etc/openvpn/client
ExecStart=/usr/sbin/openvpn --suppress-timestamps --nobind --config %i.conf
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE
LimitNPROC=10
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
ProtectSystem=true
ProtectHome=true
KillMode=process

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/openvpn-client@.service.d/override.conf
### Editing /etc/systemd/system/openvpn-client@.service.d/override.conf
### Anything between here and the comment below will become the new contents of the file



### Lines below this comment will be discarded

### /lib/systemd/system/openvpn-client@.service
# [Unit]
# Description=OpenVPN tunnel for %I
# After=network-online.target
# Wants=network-online.target
# Documentation=man:openvpn(8)
# Documentation=https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage
# Documentation=https://community.openvpn.net/openvpn/wiki/HOWTO
#
[Service]
# Type=notify
# PrivateTmp=true
# WorkingDirectory=/etc/openvpn/client
ExecStart=
ExecStart=/usr/sbin/ip vrf exec %i /usr/sbin/openvpn --suppress-timestamps --nobind --cd /etc/openvpn --config /etc/openvpn/client/%i.conf
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE BPF_PROG_LOAD BPF_PROG_ATTACH CGROUP_BPF CAP_SYS_ADMIN CAP_DAC_OVERRIDE
# LimitNPROC=10
# DeviceAllow=/dev/null rw
# DeviceAllow=/dev/net/tun rw
# ProtectSystem=true
# ProtectHome=true
# KillMode=process
#
# [Install]
# WantedBy=multi-user.target
```

**Comment by anp135** [comment]
I use mpls l3vpn with FRR (FRRouting). Sometimes need up shit-tunnels over openvpn (even normal interfaces does not work). I need here in the first use right vrf for outgoing connection, in the second change new tunnel to target vrf. This is made with NetworkManager dispatcher.

**Comment by Ma27** [comment]
> By hand I mean run 'ip vrf exec' in system shell. root user or sudo user - there is not matter.

If it works for these kinds of users, can you please share your limits.conf then?

> no of course. memlock reason will provide segmentation fault. Try to set ulimits -s 0 and run ip vrf exec.

I don't understand what you mean. Also, why `ulimit -s`? And why `0`?

You're decreasing the stack-size of your current shell to 0 which obviously results in a segfault, I suggested to increase the memlock to a higher value.

Regarding your systemd unit: considering that you're using `/usr/sbin/` which system are you on? And is `iputils` installed with Nix?

**Comment by anp135** [comment]
> If it works for these kinds of users, can you please share your limits.conf then?

My limits.conf is default for ubuntu 21.04
```
# cat /etc/security/limits.conf | grep -v "^#"
#
```
ulimit -s is 8192, -l is 630821


> Also, why ulimit -s? And why 0?

sorry, my mistake -). Speaking upper about `-l`.

 
> Regarding your systemd unit: considering that you're using `/usr/sbin/` which system are you on? And is `iputils` installed with Nix because it's also from `/usr/sbin`.

```
# whereis ip
ip: /usr/bin/ip /usr/sbin/ip /usr/share/man/man8/ip.8.gz /usr/share/man/man7/ip.7.gz
# which ip
/usr/sbin/ip
# ip -V
ip utility, iproute2-5.9.0, libbpf 0.3.0
```

**Comment by anp135** [comment]
Anyway `Failed to load BPF prog: 'Operation not permitted'` not about memory. This is about permittions and BPF.

**Comment by Ma27** [comment]
> Anyway Failed to load BPF prog: 'Operation not permitted' not about memory. This is about permittions and BPF.

It actually is, please read the kernel thread I linked above if you'd like to know more.

However, I don't think we can really fix something for you considering that you don't seem to be using Nix/NixOS and this is the issue tracker for these projects.

**Comment by Lillecarl** [comment]
People experiencing the same problem will find this because Github SEO is amazing.
https://github.com/NixOS/nixpkgs/issues/145673#issuecomment-992930602 is the answer.
