### ISSUE TITLE
programs.zsh.enableCompletion=true with nix 2.4 results in conflict over completions

### ISSUE THREAD

**Issue by antifuchs** [NixOS/nixpkgs#145728]
### Describe the bug

On nixpkgs-unstable as of today, if you set `programs.zsh.enableCompletion=true`, the `_nix` completion definition that the nix (2.4) package brings conflicts with the nix-zsh-completions package's `_nix` completion file.

### Steps To Reproduce
1. On current nixpkgs-unstable, set `programs.zsh = {enable=true; enableCompletion=true;};` (or set `nix.package` to a "2.4" release)
2. rebuild

Results in:
```console
building the system configuration...
system-path> error: collision between `/nix/store/csadkv9vsi64sxx8nq08ydy88j3b3kwp-nix-2.4/share/zsh/site-functions/_nix' and `/nix/store/9aggbz1bcndl0la8b42y4ridwp7wgvwq-nix-zsh-completions-0.4.4/share/zsh/site-functions/_nix'
error: builder for '/nix/store/z12xf8zy039003sl8v4x05dbx5ggwc28-system-path.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/csadkv9vsi64sxx8nq08ydy88j3b3kwp-nix-2.4/share/zsh/site-functions/_nix' and `/nix/store/9aggbz1bcndl0la8b42y4ridwp7wgvwq-nix-zsh-completions-0.4.4/share/zsh/site-functions/_nix'
       For full logs, run 'nix log /nix/store/z12xf8zy039003sl8v4x05dbx5ggwc28-system-path.drv'.
error: 1 dependencies of derivation '/nix/store/cxi7qsyz8zk0chcfvjpkk0h3gawmgcm1-darwin-system-21.11.20211112.8f39ad3+darwin4.85a2d01.drv' failed to build
```

### Expected behavior

No conflict.

### Additional context

I believe [this block](https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/nixos/modules/programs/zsh/zsh.nix#L288-L297) should prevent this very conflict: but now that nix 2.4 is released, the conditional might be wrong?

### Notify maintainers

spwhitt olejorgenb hedning ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20201102_550e11f`
 - channels(root): `"nixpkgs-21.03pre262186.e49e3a756b3"`
 - channels(asf): `"darwin, nixpkgs-20.03pre216218.929768261a3"`
 - nixpkgs: `/nix/store/4nx7xbybvdr5n2y5gsikwjxbq0xjplgg-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: programs.zsh
```

**Comment by cole-h** [comment]
This sounds like https://github.com/LnL7/nix-darwin/issues/373 -- seeing as you're on darwin, I think this issue is more appropriate for the `nix-darwin` repo. And indeed, that repo does not have the 2.4 version guard: https://github.com/LnL7/nix-darwin/blob/44da835ac40dab5fd231298b59d83487382d2fab/modules/programs/zsh/default.nix#L103

**Comment by antifuchs** [comment]
Agh, that's true: I missed that this is a nixos option, not a nix-darwin option. Thanks for the clarification.
