### ISSUE TITLE
Cannot install flutter on osX

### ISSUE THREAD

**Issue by maelp** [NixOS/nixpkgs#145701]
### Describe the bug
I'd like to install flutter on osX

### Steps To Reproduce
1. nix-env -iA nixpkgs.flutter

### Expected behavior
Install flutter

### Screenshots
```
warning: name collision in input Nix expressions, skipping '/Users/primet/.nix-defexpr/channels_root/home-manager'
installing 'flutter-2.5.1'
error: unsupported version/system: 2.14.2/x86_64-darwin
(use '--show-trace' to show detailed location information)
```

### Notify maintainers
@babariviere @ericdallo @thiagokokada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.15`
 - channels(primet): `"home-manager-21.05"`
 - channels(root): `"darwin, home-manager-21.05, nixpkgs-21.11pre320922.ee084c02040"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ericdallo** [comment]
I don't have a macos to test the derivation unfortunately :/

**Comment by babariviere** [comment]
Me neither, if you want to add support for darwin, add `"x86_64-darwin"` to the [platform list](https://github.com/NixOS/nixpkgs/blob/e29d818477aa67a4def398e2b510437ecfbd4704/pkgs/development/compilers/flutter/flutter.nix#L168) and build it locally.

**Comment by maelp** [comment]
Happy to try, although I'm not a nix expert, so I might have to ask a few questions from time to time haha

**Comment by veprbl** [comment]
You should be able to build `flutter.unwrapped`, although I don't know how useful it is.

**Comment by elken** [comment]
Hey @ericdallo, I'd be quite keen to get something like this sorted but I'm a beginner nixer, I'd be happy to test anything you needed though :)

**Comment by ericdallo** [comment]
I don't think my nix knowledge is enough to help with that :/ @thiagokokada is no longer one of the maintainers of this derivation but he knows a lot about nix, maybe he knows how to make that work?

**Comment by arrterian** [comment]
UP from 2023. I have tried to build the package on MacOS locally. The only problem — `buildFHSUserEnv` has no support on macOS.
