### ISSUE TITLE
Roundcube fails to start with `carddav` plugin enabled due to PHP Fatal error

### ISSUE THREAD

**Issue by ondt** [NixOS/nixpkgs#145775]
### Describe the bug
Roundcube with the `carddav` plugin enabled fails to start due to an error caused by [PHP deprecating the left-associative ternary operator](https://www.php.net/manual/en/migration74.deprecated.php). This seems to be caused by #142148.

```
Nov 13 06:12:48 server systemd[1]: Starting roundcube-setup.service...
Nov 13 06:12:48 server roundcube-setup-start[3861]:  2019092900
Nov 13 06:12:48 server roundcube[3862]: PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /nix/store/2aifms5v5gwv4i15girjs0zk9n8bx6y8-roundcube-plugin-carddav-3.0.3/plugins/carddav/carddav.php on line 352
Nov 13 06:12:48 server systemd[1]: roundcube-setup.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 13 06:12:48 server systemd[1]: roundcube-setup.service: Failed with result 'exit-code'.
Nov 13 06:12:48 server systemd[1]: Failed to start roundcube-setup.service.
```

### Steps To Reproduce
Enable the `roundcube` module with `services.roundcube.package = pkgs.roundcube.withPlugins (plugins: [ plugins.carddav ]);` and `services.roundcube.plugins = [ "carddav" ];`.

### Expected behavior
Roundcube with the `carddav` plugin enabled should start.

### Additional context
#125778 and #125796 are somewhat related to this issue.

### Notify maintainers
@Ma27 @Vskilet 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.78, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11pre329879.c5ed8beb478"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
- roundcube
```

**Comment by Vskilet** [comment]
Sorry, but I don't have a roundcube instance anymore and I don't have time to dig, so I'm going to step out of the role of maintainer of this package.

**Comment by rembo10** [comment]
Created a [PR](https://github.com/NixOS/nixpkgs/pull/162559) that will resolve this
