### ISSUE TITLE
Desktop hangs after logging in with kernel >=5.10.76

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#145721]
### Describe the bug

A few days ago, my GNOME desktop (tested on both Wayland and X11) started freezing after a few seconds whenever I boot kernel 5.10.76 or newer.

### Steps To Reproduce
1. `nixos-rebuild switch --upgrade-all` to kernel 5.10.76
2. Reboot
3. Select the latest boot entry
4. Log into GNOME
5. Wait a few seconds (between 10 and 30 or so)

At this point I can still move the mouse pointer around, but the machine does not react to any other mouse/keyboard inputs (such as clicking, Ctrl-Alt-F1, Alt-Tab, etc.).

### Expected behavior

The desktop should function as normal.

### Logs

From `journalctl --boot=-1`:

```
kernel: BUG: unable to handle page fault for address: 0000000018109530
kernel: #PF: supervisor instruction fetch in kernel mode
kernel: #PF: error_code(0x0010) - not-present page
```

### Additional context

Searching for similar error messages I've seen them pop up for video drivers. `lspci` lists my video card as "Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c5)". I would expect this to be a video driver or kernel regression, but I've not found dupes of this issue after a quick search.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.05.3926.5ebb1dca9bb (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4051.9e86f5f7a19, home-manager-21.05"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by FliegendeWurst** [comment]
I've experienced the same issue on 5.10.77. It was also reported on the amdgpu bug tracker: https://gitlab.freedesktop.org/drm/amd/-/issues/1778 (though that report claims 5.10.76 was still fine)

In any case it should be fixed in Linux 5.10.78 (#145358).

**Comment by tholzschuh** [comment]
I can confirm having the same issue on 5.10.76 as well.

**Comment by l0b0** [comment]
Thank you @FliegendeWurst; let's see if the next patch version (or nixpkgs 21.11, whichever comes first) fixes it.

**Comment by l0b0** [comment]
Yep, looks like 5.10.78 fixed it!
