### ISSUE TITLE
Xmonad is out of date

### ISSUE THREAD

**Issue by darealdrzoidberg** [NixOS/nixpkgs#145730]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.15
desired version: 0.17

###### Notify maintainers

maintainers:

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment]
maintainer: @peti

**Comment by prusnak** [comment]
There is already `xmonad_0_17_0` in hackage packages.

**Comment by jakobneufeld** [comment]
Yes but how do I use it with services.x11.windowManager.xmonad

**Comment by 174BD7E8** [comment]
@jakobneufeld https://search.nixos.org/packages?channel=unstable&show=haskellPackages.xmonad_0_17_0&from=0&size=50&sort=relevance&type=packages&query=xmonad

**Comment by peti** [comment]
Ping @NixOS/haskell.

**Comment by sternenseemann** [comment]
> How do I use xmonad _0_17_0 services.x11.windowManager.xmonad

It doesn't seem to be possible easily with how the module is implemented at the moment. You could try using an overlay like this:


```nix
self: super: {
  haskellPackages = super.haskellPackages.override {
    overrides = hself: hsuper: {
     xmonad = self.xmonad_0_17_0;
     xmonad-contrib = self.xmonad-contrib_0_17_0;
    };
  };
}
```

The default xmonad version will change as soon as stackage (lts atm) changes it. We could contemplate ignoring stackage for xmonad to have a more cutting edge version, but this likely means more maintenance work.

**Comment by cdepillabout** [comment]
I'm going to close this, since it is currently "by design", since we pin to packages in stackage, and xmonad is in stackage.
