### ISSUE TITLE
cmake docs

### ISSUE THREAD

**Issue by rardiol** [NixOS/nixpkgs#14585]
There seems to be a few hundreds of packages using cmake, so at least some documentation would be useful, and I couldn't find any. I assume it belongs in the nixpkgs manual with the rest of the configure phase or on the "7. Support for specific programming languages and frameworks" section.

I suppose cmakeFlags, cmakeFlagsArray could be described simply as similar to their normal configure equivalents?

It seems it already is on the wiki wishlist https://nixos.org/wiki/Contributing_to_the_Nix_wiki#WISH_LIST/

**Comment by Profpatsch** [comment]
triage: was documentation added?

**Comment by rardiol** [comment]
I don't see any on nixpkgs manual

**Comment by matthewbauer** [comment]
This will be in the 19.03 manual. See url:

https://hydra.nixos.org/build/87718220/download/1/nixpkgs/manual.html#ssec-setup-hooks
