### ISSUE TITLE
Can't change a cursor theme in KDE (Wayland)

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#145844]
KDE settings do not change the cursor theme.

### Steps To Reproduce
1. Run Plasma (Wayland) session
2. Open the settings
3. Pick a cursor theme

### Expected behavior
A cursor should use the cursor theme selected in the settings.

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.78, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"nixos-21.11pre329879.c5ed8beb478"`
 - channels(suhr): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by NoEnd-yt** [comment]
This happened to me too.

**Comment by FliegendeWurst** [comment]
Works for me. You may need to restart your session for it to apply fully.
