### ISSUE TITLE
Collision between nbclient and jupyter_client

### ISSUE THREAD

**Issue by okanua** [NixOS/nixpkgs#145968]
### Describe the bug

Tried today to update my nixOS system, which was last updated on 27/10/2021. 

Now when trying to nixos-rebuild switch i get the following error:

> error: collision between `/nix/store/mbb2gp3xrg3ajfmkdd4jbnfjafgv227i-python3.9-nbclient-0.5.8/bin/jupyter-run' and `/nix/store/7cdci6lpmgh3x7407xrxy2bnabjd9sdp-python3.9-jupyter_client-7.0.6/bin/jupyter-run'

### Additional context

Using unstable.

relevant part of setup:

  home.packages = with pkgs; [
    (python3.withPackages (ps: with ps; [jupyter numpy pandas matplotlib]))
    ];

flake was updated as below:

• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/a4bf44345706231f9dd56f85757499af1e940847' (2021-10-27)
  → 'github:nixos/nixpkgs/2fa862644fc15ecb525eb8cd0a60276f1c340c7c' (2021-11-13)

@erictapen @aborsu

**Comment by erictapen** [comment]
Hey, thanks for the report with the thorough explanations.

This seems to be an issue with [home-manager](https://github.com/nix-community/home-manager). For some reason they don't set `ignoreCollisions = true` in their `buildEnv` call in `modules/home-environment.nix`.

For the actual collision I'm afraid we can't do much about it. Users of both `jupyter-client` and `nbclient` might expect to find `jupyter-run` in the closure.

So I'd suggest to ask home-manager to allow collisions, or move your colliding packages into `environment.systemPackages`.

Feel free to ping me if you think there is another cause for the issue.

**Comment by alarsyo** [comment]
I've just hit this problem in a flake : 

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system;  };
      pythonWithPackages = pkgs.python3.withPackages (p: [
        p.jupyter
      ]);
    in
      {
        devShell.${system} = pkgs.mkShell {
          buildInputs = [
            pythonWithPackages
          ];
          PYTHONPATH="${pythonWithPackages}/${pythonWithPackages.sitePackages}";
        };
      };
}
```

**Comment by erictapen** [comment]
Reopening, as `python3.withPackages` is inside Nixpkgs. I'm somewhat surprised that it doesn't `ignoreCollisions`.

**Comment by alarsyo** [comment]
using a `shell.nix` file works though, so there's something different about flakes dev shells maybe ?

**Comment by erictapen** [comment]
Are you sure that you are supplying nixos-unstable to `nix-shell`? I can also reproduce with nix-shell:

```
$ cat shell.nix 
let
  pkgs = import <nixpkgs> { };
in
(pkgs.python3.withPackages (p: [
  p.jupyter
])).env

$ nix-shell -I nixpkgs=~/nixpkgs
this derivation will be built:
  /nix/store/brzir6z11878anl5ph376dxf67kb5ynd-python3-3.9.6-env.drv
building '/nix/store/brzir6z11878anl5ph376dxf67kb5ynd-python3-3.9.6-env.drv'...
error: collision between `/nix/store/mbb2gp3xrg3ajfmkdd4jbnfjafgv227i-python3.9-nbclient-0.5.8/bin/jupyter-run' and `/nix/store/7cdci6lpmgh3x7407xrxy2bnabjd9sdp-python3.9-jupyter_client-7.0.6/bin/jupyter-run'
error: builder for '/nix/store/brzir6z11878anl5ph376dxf67kb5ynd-python3-3.9.6-env.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/mbb2gp3xrg3ajfmkdd4jbnfjafgv227i-python3.9-nbclient-0.5.8/bin/jupyter-run' and `/nix/store/7cdci6lpmgh3x7407xrxy2bnabjd9sdp-python3.9-jupyter_client-7.0.6/bin/jupyter-run'
       For full logs, run 'nix log /nix/store/brzir6z11878anl5ph376dxf67kb5ynd-python3-3.9.6-env.drv'.
```

**Comment by FRidh** [comment]
> Reopening, as python3.withPackages is inside Nixpkgs. I'm somewhat surprised that it doesn't ignoreCollisions.

That's on purpose, so we can find packaging mistakes.

The version bump 214033c0840d2fe5e1294ac8bbb55af2bb87b39d introduced the regression.

**Comment by FRidh** [comment]
Proposed fix https://github.com/NixOS/nixpkgs/pull/146151

**Comment by risicle** [comment]
This appears to have broken `nbclient`: https://hydra.nixos.org/build/158386869

```
checking for references to /build/ in /nix/store/ccm2877zwmphld27k4qqhsjy20jjnb6i-python3.8-nbclient-0.5.8...
rm: cannot remove '/nix/store/ccm2877zwmphld27k4qqhsjy20jjnb6i-python3.8-nbclient-0.5.8/bin/.jupyter-run-wrapped': No such file or directory
```
