### ISSUE TITLE
Directories get opened by Baobab instead of Nautilus from GNOME Shell

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#14604]
## Issue description

When opening a directory from GNOME Shell from a search, Baobab is launched instead of Nautilus.
## Technical details
- System: NixOS  `16.09.git`
- Nix version: `1.11.2`

/cc @lethalman I think you fixed this already in the past (https://github.com/NixOS/nixpkgs/issues/247). Could the issue be back for some reason?

**Comment by lethalman** [comment]
Yes I fixed that while opening directories from nautilus itself. It would have opened them with baobab. I guess something has changed, or gnome-shell isn't picking the mime override.

**Comment by martijnvermaat** [comment]
I fixed this by right-clicking on some directory in Nautilus, choosing "Open With Other Application" and selecting Nautilus ("Files"). After I did this once, directories were opened with Nautilus from the activities view.

I'm not sure if what I did is the same as what would be a proper fix for this issue though.

**Comment by Profpatsch** [comment]
Closing because very old.
