### ISSUE TITLE
Installation Iso dropping into grub prompt on boot

### ISSUE THREAD

**Issue by zbskii** [NixOS/nixpkgs#146041]
### Describe the bug
The following installation isos all dropped into the grub prompt on boot.

### Steps To Reproduce
dd any of the following on to a usb stick:
nixos-gnome-21.05.4044.e74894146a4-x86_64-linux.iso
nixos-minimal-21.05.4044.e74894146a4-x86_64-linux.iso
nixos-minimal-21.05.4048.430e190b64d-x86_64-linux.iso
nixos-minimal-new-kernel-21.05.4049.33c866c82bb-x86_64-linux.iso

### Expected behavior
Grub boots as normal and shows a grub menu to boot into the installer 

### Additional context
This was reproducible with all isos I downloaded. I'm on a framework laptop. I was able to boot by setting:
set root=(hd0,gpt2)
set prefix=(hd0,gpt2)/boot/grub
configfile (hd0,gpt2)/boot/grub/loopback.cfg

```

**Comment by Artturin** [comment]
Please test a unstable channel iso https://releases.nixos.org/?prefix=nixos/unstable/

https://releases.nixos.org/nixos/unstable/nixos-21.11pre330462.2fa862644fc

**Comment by haltingstate** [comment]
Was not fixed. Still happening.
