### ISSUE TITLE
VLC opens two separate windows.

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#14610]
## Issue description

VLC shows the video in a separate window. I get two windows, one with the controls and the menus, and the other with the video.
This persists after clearing/resetting/changing the defaults, especially the option "integrate video in the interface" (loosely translated from french).

This is a know issue with vlc that appeared on other distros. See for example https://wiki.videolan.org/Ubuntu/#Separate_video_window or https://forum.videolan.org/viewtopic.php?t=117131 (among others, internet has plenty of these). However, there is no clear fix for it.

Does anyone observe the same behavior.

### Steps to reproduce

Run any video with vlc.

## Technical details

gnome(ish) desktop with i3.
vlc from nixos.qt5.vlc (selected or updated by name)

* System: (NixOS) 16.09pre79453.32b7b00 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre79453.32b7b00

**Comment by bjornfor** [comment]
Same issue here (NixOS 15.09). (I've been meaning to make an issue about it but didn't get that far.)

**Comment by layus** [comment]
@bjornfor do you also use i3 ?

**Comment by vcunat** [comment]
I assumed it was only because I used the qt5 version, but apparently you do not, right? (I use XMonad.)

**Comment by layus** [comment]
I am using /nix/store/chlgr1bdv4yf3aq917vd4ngn9ikmsxpi-vlc-2.2.2, which indeed depends on /nix/store/q3xcjq3rxh9gs6hn0mkmqr82555n684b-qtbase-5.4.2. I updated the bug report.

Apparently I got that version with a unconditional nix-env update. Using nixos.vlc fixes the issue.
(See also https://forum.videolan.org/viewtopic.php?t=124188 for vlc issues with qt5 on ubuntu.)

**Comment by vcunat** [comment]
> Apparently I got that version with a unconditional nix-env update.

That shouldn't happen anymore after my commit.
