### ISSUE TITLE
A question about search.nixos.org

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nixpkgs#146173]
I was wondering if I could acess some sort of api for search.nixos.org. I am writting a wrapper over the nix cli tools in rust, so it would help my project alot. When I use `nix search nixpkgs <query>` I get good json results, but I do not search through haskellPackages, nodePackages, and other package groups. Can I enable this in nix search. Is there an api for search.nixpkgs.org. If there is no solution, it is not a big deal, I was just wondering. I am quite new to NixOS so scream at me :-) if I am stupid!

**Comment by Fidgetcetera** [comment]
The search has its own repo at https://github.com/NixOS/nixos-search, and we found an issue discussing the API for the search: https://github.com/NixOS/nixos-search/issues/296
Apparently, it's mostly just base ElasticSearch, which has an existing API doc. Hopefully the comments there help you out!

**Comment by jakobneufeld** [comment]
Ok, I will try to integrate this into my cli!
Thanks!

**Comment by jakobneufeld** [comment]
I am still a bit confused, so is it ok if I make an issue on their repo?

Thanks for responding so quickly!

**Comment by Fidgetcetera** [comment]
Pretty sure it would be! We're not involved in NixOS or the search things very much, but that's definitely the better place to ask questions, and you could probably close this one and open something there. Good luck!
