### ISSUE TITLE
Cannot build interactive test driver anymore

### ISSUE THREAD

**Issue by cole-h** [NixOS/nixpkgs#146169]
### Describe the bug
When building an interactive test driver with `driverInteractive` and running the generated binary, the test just runs without an interactivity.

### Steps To Reproduce
1. `nix-build nixos/tests/abc.nix -A driverInteractive`
2. `result/bin/nixos-test-driver`
3. Observe that the test just starts instead of displaying the interactive prompt.

### Expected behavior

I'd expect to be dropped into the interactive prompt.

### Notify maintainers
cc @roberth as someone who's touched `testing-python.nix` a lot.

**Comment by roberth** [comment]
Mostly reviews and minor additions though.

Maybe #126713 broke it, but that's just a guess. Probably best to bisect with `bisect start -- <paths>` if going back to before that doesn't fix the problem.

**Comment by cole-h** [comment]
Ah, it was broken by https://github.com/NixOS/nixpkgs/pull/125979.
