### ISSUE TITLE
systemd error when `/usr` not `neededForBoot`

### ISSUE THREAD

**Issue by mightyiam** [NixOS/nixpkgs#146115]
### Describe the bug

systemd seems to use the term *split-usr* to refer to an attribute of a system, where:

1. `/usr` is a mount point.
2. `/usr` is not mounted "at boot".

Since systemd v248, support for a split-usr system is deprecated:
1. https://github.com/systemd/systemd/blob/e2de2d28f40ff5dded8104044792fb58cdd0afa6/NEWS#L931-L934
2. https://github.com/systemd/systemd/commit/9afd5e7b975e8051c011ff9c07c95e80bd954469

While [the news for v249](https://github.com/systemd/systemd/blob/e2de2d28f40ff5dded8104044792fb58cdd0afa6/NEWS#L3-L558) don't seem to mention a formal removal of support of split-usr, it seems that [the `systemd-remount-fs` service does not support it since v186](https://github.com/systemd/systemd/commit/b4efdf97203ddf781c17f77be84cc61516a077d2).

According to [the v249 `systemd-remount-fs` manpage](https://www.freedesktop.org/software/systemd/man/systemd-remount-fs.service.html):

> `systemd-remount-fs.service` is an early boot service that applies mount options listed in fstab(5) (...) to the root file system, the `/usr/` file system, and the kernel API file systems. This is required so that the mount options of these file systems — which are pre-mounted by the kernel, the initial RAM disk, container environments or system manager code — are updated to those configured in `/etc/fstab` and the other sources. This service ignores normal file systems and only changes the root file system (i.e. /), `/usr/`, and the virtual kernel API file systems such as `/proc/`, `/sys/` or `/dev/`.

It seems that if `/usr` is a mount point, this unit calls `mount` with `-o remount` on it, regardless of whether it is already mounted — making the assumption that it had already been mounted "at boot".

### Steps To Reproduce

When I installed my first NixOS on my workstation, I made a filesystem for each path under `/`.
This let me customize options per directory as I wished, both at install and later on.
ZFS's sharing of storage space between filesystems in the same zpool takes the cost out of being "generous" with the number of filesystems.

I didn't know that `/usr` is merely `/usr/bin/env` that happens to be generated at boot.
I also didn't know that systemd deprecated split-usr.

So I did not mark `/usr` as [`neededForBoot`](https://search.nixos.org/options?channel=unstable&show=fileSystems.%3Cname%3E.neededForBoot&from=0&size=50&sort=relevance&type=packages&query=filesystems.%3Cname%3E.neededForBoot).

The system built successfully and booted successfully. Except for an error in the logs:

```
systemd-remount-fs[1655]: filesystem 'nixos/root/usr' can not be mounted: Invalid argument
```

The failure seems to be due to the attempt to remount using `mount` with the `-o remount` option a non-mounted filesystem — `/usr`.

`/usr` is later successfully mounted along with the rest of the filesystems.

### Expected behavior

Since systemd seems to expect that if `/usr` is a mount point it would have already been mounted "at boot", I would expect NixOS to:
1. set `/usr`'s `neededForBoot` to `true` by default, [as it does for some other paths](https://github.com/NixOS/nixpkgs/blob/4e97bedf93d8bd35e12a5b99f66aaa811e74eb83/nixos/lib/utils.nix#L10-L13).
2. fail to build when `/usr`'s `neededForBoot` is `false` (that could be [somewhere here](https://github.com/NixOS/nixpkgs/blob/c935f5e0add2cf0ae650d072c8357533e21b0c35/nixos/modules/system/boot/stage-1.nix#L673-L701)).

### Additional context

Understanding this error took around three hours of collaborative debugging with the tremendous help of @tomberek.

A workaround is to set `neededForBoot = true;` for `/usr`, or to not have a `/usr` mount point at all.

The suggested solution (expected behavior) is with the goal of sparing all future users an investigation of this error.

### Notify maintainers

Not sure who to mention. Please ignore if you no longer wish to be involved. If you happen to know who should be mentioned here and is not, please comment mentioning them.
@emilazy @oxij @vcunat @edolstra @andersk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.78, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(mightyiam): `""`
 - channels(root): `"nixos-21.11pre330462.2fa862644fc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by Artturin** [comment]
gentoo notes this in their wiki as well https://wiki.gentoo.org/wiki/Systemd#Ensure_.2Fusr_is_present_at_boot_time

**Comment by aanderse** [comment]
ping a couple people who *might* care: @etu, @talyz, @grahamc, @arianvp, @flokli, and probably others.
