### ISSUE TITLE
R is broken on darwin

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#146131]
https://hydra.nixos.org/job/nixpkgs/trunk/R.x86_64-darwin

**Comment by domenkozar** [comment]
cc @NixOS/darwin-maintainers

**Comment by smaret** [comment]
It seems that the tests with TCL/TK hang:
```
Testing examples for package ‘tcltk’
building of '/nix/store/p0wkhl0l89y5g2qwp43a6dpxq15vwvig-R-4.1.1' timed out after 7200 seconds of silence
```

**Comment by toonn** [comment]
I believe @TyberiusPrime may know more about this. They've been talking about R packages and TCL and Rust lately.

**Comment by TyberiusPrime** [comment]
What I've found (on linux!) is that if the packages tctk/tcltk2, and their downstreams are not provided with an X server (xvfb via xvfbrun), they will run into an endless loop in tcl code.

**Comment by smaret** [comment]
On `darwin-x86`, `nix-build -A R` gives the following error:
```
esting examples for package 'tcltk'
/private/tmp/nix-build-R-4.1.2.drv-0/R-4.1.2/bin/BATCH: line 60: 10856 Abort trap: 6           ${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1
Error: testing 'tcltk' failed
```

**Comment by smaret** [comment]
Here is the full log of the failing test on `x86_darwin`: 
https://gist.github.com/smaret/a84767c9bb45445e0066d98c3967f9dc
It seems that the test tries to connect to a window server and fails (as expected). We should probably just skip that test.

**Comment by smaret** [comment]
I had a look at the code and I think that the relevant lines are in `tests/Examples/Makefile`:

```Makefile
test-Examples-Recommended: test-Examples-Base
	@$(ECHO) "tools::testInstalledPackages(scope='recommended', types='examples')" | _R_CHECK_FORCE_SUGGESTS_=FALSE $(R_EXE)
```

It calls the  R function [`testInstalledPackage`](https://www.rdocumentation.org/packages/tools/versions/3.6.2/topics/testInstalledPackage) that tests all installed packages. I don't know how to skip the `tcltk` tests.

**Comment by domenkozar** [comment]
Can we just disable that test?

**Comment by smaret** [comment]
Yes, but it would disable the test of all installed packages (not only `tcltk`).
