### ISSUE TITLE
[HBase module] Unrecognized VM option 'UseConcMarkSweepGC'

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#146246]
### Describe the bug
After enable HBase module `services.hbase.enable = true;`, and rebuild.
The service unit cannot start, it says JVM option `UseConcMarkSweepGC` not exists.

### Steps To Reproduce
1. Enable HBase by adding config `services.hbase.enable = true;`.
2. Do `nixos-rebuild switch`, it should be failed.
3. Error shows VM option is Unrecognized.

### Additional context
I found the same issues on the StackOverFlow, it seems jre 15 dropped the option:
https://stackoverflow.com/questions/65465889/hbase-error-unrecognized-vm-option-useconcmarksweepgc

I fixes this by adding this line, but it should be fixed in module.
`systemd.services."hbase".environment."JAVA_HOME" = lib.mkForce "${pkgs.jre8}";`

### Notify maintainers
@ocharles I can do the fixes PR if you want.

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.16-xanmod1-cacule, NixOS, 21.05.20211115.46251a7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"agenix, nixos-21.05.4116.46251a79f75, nixos-hardware, nixos-unstable-21.11pre330462.2fa862644fc"`
 - channels(vanilla): `"home-manager, nixpkgs-21.11pre330462.2fa862644fc"`
 - nixpkgs: `/home/vanilla/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ocharles** [comment]
@VergeDX go for it. I'm also not maintaining this anymore, so may be best to also remove from `maintainers`.
