### ISSUE TITLE
Any local users can talk to locally running X server by default

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#14623]
## Issue description

Any local users can talk to locally running X server by default. That includes sending keyboard/mouse events, popping windows, etc.

### Steps to reproduce

Log in as `user2` into a host running an X server under `user1`, and run `nix-shell -p xorg.xmessage --command xmessage\ pwnd`

I think normally you should have to do something like `xauth merge ~user1/.Xauthority` before you're able to talk to `user1`'s X server.

## Technical details

* System: NixOS: nix-shell -p xorg.xmessage --command xmessage\ test
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.d1a4b54

**Comment by edolstra** [comment]
Thanks, amazing nobody has spotted this before. The `-ac` flag has been present ever since 8532f2be8e7d46485feeef730496a29c1960ae2d (when it at least had a comment about being bad idea...).

**Comment by obadz** [comment]
:+1:
