### ISSUE TITLE
nixos-generate-config: generate DHCP config in hardware-configuration.nix instead

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#146226]
## Issue description
The [function that generates the DHCP configuration](https://github.com/NixOS/nixpkgs/blob/6abc7cd907ea06424e7963e949cf554a6b3914c2/nixos/modules/installer/tools/nixos-generate-config.pl#L570-L586), which is hardware specific since the network interfaces are not the same on every computer, [is called](https://github.com/NixOS/nixpkgs/blob/6abc7cd907ea06424e7963e949cf554a6b3914c2/nixos/modules/installer/tools/nixos-generate-config.pl#L647) during the generation of `configuration.nix`.
If one leaves it there and later transfers `configuration.nix` to another computer, the person will be in for a nasty surprise.
I thus suggest that the generation of the DHCP configuration is moved to `hardware-configuration.nix`, where I think it should belong.

**Comment by bjornfor** [comment]
Ref https://github.com/NixOS/nixpkgs/issues/73595, https://github.com/NixOS/nixpkgs/issues/75515.

**Comment by bjornfor** [comment]
Looks like a duplicate of https://github.com/NixOS/nixpkgs/issues/73595.

**Comment by SuperSamus** [comment]
I didn't notice that, sorry.
(If I search "nixos-generate-config" on Github that issue is on page 5...)
