### ISSUE TITLE
thunderbird: huge closure size

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#146219]
It got a huge closure size.  Jump happened here:
- 91.1.0: 0.5 G
- 91.1.1: 3+ G

https://hydra.nixos.org/job/nixpkgs/trunk/thunderbirdPackages.thunderbird.x86_64-linux#tabs-charts

On a quick glance, it's mainly due to dragging lots of toolchain packages, rustc in particular:
```
63992   /nix/store/9wxxikq0iqsq3jig60yzal77z2q2w2xv-llvm-13.0.0
85376   /nix/store/fkzla307l4mlcvfyshsrccwl7szihx2z-python3-3.9.6
180124  /nix/store/a87yinndp3fgpxxfxb9fyr9aln5yzsr7-gcc-10.3.0
197504  /nix/store/n3gwwqwpsimwmzgj5pfqbl6ypf2mqxqp-thunderbird-unwrapped-91.3.1
300648  /nix/store/jicwsjh2r4s2048i1manh4403mzijls9-clang-13.0.0-lib
370932  /nix/store/rn4hqvzb9w4ks83cf6lxpwqr97sqkqf0-llvm-13.0.0-lib
797792  /nix/store/449lmdsx8dv2q5fn4xbkxk51d4cg2zih-rustc-1.56.1
```

/cc other likely interested people: @lovesegfault, @taku0.

**Comment by vcunat** [comment]
`firefox` and `firefox-esr` don't suffer from this, by the way.

**Comment by taku0** [comment]
This may be relating to `no-buildconfig-90.patch` (https://github.com/NixOS/nixpkgs/pull/138358).
