### ISSUE TITLE
New versioning scheme for plan9port breaks `u` 

### ISSUE THREAD

**Issue by ylh** [NixOS/nixpkgs#146294]
### Describe the bug
The new `0.pre+date=...` scheme introduced in 9199162 confuses the `u` script.

### Steps To Reproduce
1. install latest plan9port from unstable as of writing
2. attempt to use `u` from within an environment spawned by `9`

### Expected behavior
`$PLAN9` gets moved from the front of `$PATH` to the back

### Typescripts
Here is a session using unmodified p9p:

    ylh@m1p ~ $ echo $PATH
    /Users/ylh/bin:/Users/ylh/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
    ylh@m1p ~ $ 9 zsh
    ylh@m1p ~ $ echo $PATH
    /nix/store/d4iwcgqwgk8whxjxgmhh20ykni7flkb2-plan9port-0.pre+date=2021-10-19/plan9/bin:/Users/ylh/bin:/Users/ylh/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
    ylh@m1p ~ $ u zsh
    ylh@m1p ~ $ echo $PATH
    /nix/store/d4iwcgqwgk8whxjxgmhh20ykni7flkb2-plan9port-0.pre+date=2021-10-19/plan9/bin:/Users/ylh/bin:/Users/ylh/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin

After applying the following overlay:

    self: { lib, plan9port, ... }: let
      lastby = sep: x: lib.last (lib.splitString sep x);
    in {
      plan9port = plan9port.overrideAttrs (old@{ pname, ... }: {
        version = lastby "=" (lastby "+" old.version);
        name = "${pname}-${version}";
      });
    }

the desired result is achieved:

    ylh@m1p ~ $ echo $PATH
    /Users/ylh/bin:/Users/ylh/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
    ylh@m1p ~ $ 9 zsh
    ylh@m1p ~ $ echo $PATH
    /nix/store/zh1iaayjg7baqvgh1g645k4wzxjrmfzx-plan9port-2021-10-19/plan9/bin:/Users/ylh/bin:/Users/ylh/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
    ylh@m1p ~ $ u zsh
    ylh@m1p ~ $ echo $PATH
    /Users/ylh/bin:/Users/ylh/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin:/nix/store/zh1iaayjg7baqvgh1g645k4wzxjrmfzx-plan9port-2021-10-19/plan9/bin

Amusingly, `u.rc` is left unaffected; the `u` tool calls out to `sed`, which, in a `9` environment (why else would you be calling `u`), is p9p sed, which interprets `+` as a metacharacter without the need for `-E`.

In any case, RFC 0107 clearly needs work, and this should hopefully demonstrate why enacting it (self-merging, no less) pre-approval is somewhat irresponsible.

### Notify maintainers
@AndersonTorres 

### Metadata
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixpkgs-21.11pre329302.d14ae62671f"`
 - channels(ylh): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by ehmry** [comment]
This obsession with arbitrary versioning formatting standards is getting annoying.
