### ISSUE TITLE
wine-wow-*-staging fails to build

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#14627]
### Steps to reproduce
```$ nix-build -E 'with import <nixpkgs> {}; wineStaging.override { wineBuild = "wineWow"; }'```

## Technical details

* System: recent NixOS, sandboxed
* Nixpkgs version: current master, e.g. 48972763c86; it used to build on f9cae4f6dc8be7
* Example output: 
```
gcc -m64 -c -o crypt_md4.o /tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32/crypt_md4.c -I. \
  -I/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32 -I../../include \
  -I/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/include -D__WINESRC__ -D_ADVAPI32_ \
  -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf -g -O2
/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32/crypt_md4.c: In function 'MD4Update':
/tmp/nix-build-wine-wow-1.9.7-staging.drv-0/wine-1.9.7/dlls/advapi32/crypt_md4.c:134:1: internal compiler error: in choose_baseaddr, at config/i386/i386.c:10412
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

**Comment by vcunat** [comment]
Unfortunately, updating didn't help. (/cc @tohl with that)

**Comment by abbradar** [comment]
Sadly, I can reproduce that. Maybe we want to downgrade the compiler here?

**Comment by abbradar** [comment]
Additionally, `wine64` build doesn't work too.

**Comment by vcunat** [comment]
> Maybe we want to downgrade the compiler here?

Oh, truly, I didn't realize that last working version I referenced was using gcc-4.9. I switched nixpkgs versions on our hydra instance at that point.

**Comment by abbradar** [comment]
Found the bug: https://bugzilla.suse.com/show_bug.cgi?id=966220
And corresponding compiler bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69140
