### ISSUE TITLE
iterm2 does not build on aarch64-darwin

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#146337]
### Describe the bug
The iterm2 package (https://search.nixos.org/packages?channel=21.05&show=iterm2&from=0&size=50&sort=relevance&type=packages&query=iterm2) does not build on aarch64-darwin. I'm getting the following error message:
```
warning: iTerm2 isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it. (in target 'iTerm2' from project 'iTerm2')
** BUILD FAILED **
```

### Steps To Reproduce
1. Try installing/building `iterm2`.
2. Observe the build failure.

### Expected behavior
The package to build.

### Screenshots
n/a

### Additional context
Complete logs are available here: https://gist.github.com/samuela/4bc3732dd27e2d6007ba0dc0390bd79a.

### Notify maintainers

@tricktron

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(samuelainsworth): `"darwin, home-manager, nixpkgs-21.11pre330734.5cb226a06c4"`
 - channels(root): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - nixpkgs: `/Users/samuelainsworth/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: iterm2
# a list of nixos modules affected by the problem
module:
```

**Comment by tricktron** [comment]
Hi @samuela,

Unfortunately, it was/is not possible to build item in a pure and reproducible way from source because it depends on your installed Xcode toolchain. It is therefore not an ideal candidate for nixpkgs and I didn't update the version of it either.

Do you see any benefit in having iterm2 in nixpkgs compared to just downloading it from their website?

**Comment by samuela** [comment]
Hi @tricktron, thanks for packaging this! I generally have a slight preference to installing things via nix so that I can put them in my home-manager config, but at the end of the day it doesn't make a huge difference to me.

It sounds like iterm2 is kind of a pain to package in general... Do you think it should be marked as broken or removed from nixpkgs?
