### ISSUE TITLE
Clockify

### ISSUE THREAD

**Issue by tomgtc** [NixOS/nixpkgs#146395]
**Clockify**
_desktop version of web timetracking app_

**Metadata**

* homepage URL: http://clockify.me
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by WolfangAukang** [comment]
I was [able](https://github.com/WolfangAukang/nixpkgs/commit/b5703dfc4b2a2afd0d2dcb1a29e08fab79cd9f88) to package it, but I would like someone to try it first and see if it works as intended.

**Comment by baronleonardo** [comment]
@WolfangAukang I had tested it and it works like a charm

**Comment by WolfangAukang** [comment]
Merged.
