### ISSUE TITLE
strange completion location breaks oh-my-zsh plugin

### ISSUE THREAD

**Issue by shmish111** [NixOS/nixpkgs#146393]
### Describe the bug
For some reason https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/admin/google-cloud-sdk/default.nix#L104 moves the zsh completion script from the usual location to a different one. There is no comment to explain this but what it does is break the gcloud plugin for oh-my-zsh.

### Steps To Reproduce
1. add the gcloud plugin to oh-my-zsh
2. set `CLOUDSDK_HOME` to the gcloud home in the nix store
3. try to use autocompletion in zsh

### Expected behavior
gcloud completion works

### Notify maintainers
@janders223 

### Metadata
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.0.1, macOS 12.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - channels(davidsmith): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Maintainer information:

**Comment by Artturin** [comment]
that plugin should not be needed as zsh automatically loads completions from `/run/current-system/sw/share/zsh/site-functions/` (where `$out/share/zsh/site-functions/_gcloud` gets linked to)

**Comment by shmish111** [comment]
This does not seem to be the case with home manager, do I need to do something other than include it in home.packages. I appreciate this isn't a nixpkgs thing.

**Comment by Artturin** [comment]
the package does not have the necessary `#compdef gcloud` in the completion script so zsh does not load it automatically from the dirs listed in $FPATH

Please test this with both the gcloud and gsutil completions
```
(google-cloud-sdk.overrideAttrs (oldAttrs: {
  postInstall = ''
    sed -i '1 i #compdef gcloud' $out/share/zsh/site-functions/_gcloud
  '';
}))
```

**Comment by shmish111** [comment]
thanks @Artturin this worked. Are you able to open a PR for this, or am I supposed to, or someone else?

**Comment by Artturin** [comment]
i have it in this pr https://github.com/NixOS/nixpkgs/pull/146456
