### ISSUE TITLE
Software making use of mariadb-connector can't find my_config.h

### ISSUE THREAD

**Issue by spease** [NixOS/nixpkgs#146340]
### Describe the bug
Software making use of mariadb-connector can't find my_config.h

### Steps To Reproduce
Something like this:
```
      mach-nix.buildPythonPackage {
        pname = "mysql-python";
        version = "1.2.5";
        requirements = "";
        src = "https://github.com/farcepest/MySQLdb1/archive/refs/tags/MySQLdb-1.2.5.tar.gz";
        propagatedBuildInputs = [ pkgs.mariadb.client pkgs.mariadb-connector-c ];
        configurePhase = ''
          export PATH="${pkgs.mariadb-connector-c.dev}/bin:$PATH"
          mysql_config --help
          bash
        '';
      }
```

### Expected behavior
Builds successfully

### Additional context
I tried building mariadb on my own, and this file seems to exist in mariadb/include/my_config.h . My attempts to patch mariadb with an overlay to not delete include files to get it to be found has failed.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

Maintainer information:
@thoughtpolice

**Comment by abathur** [comment]
It sounds like this should've been closed with the merge of #146442. Happy to reopen if I'm mistaken.
