### ISSUE TITLE
Add NixOS option for ModemManager FCC unlock

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#146486]
The not yet packaged ModemManager 1.18.4 will no longer run FCC unlock procedures, breaking the WWAN module in some laptops. Once 1.18.4 is out, the procedure will need to be explicitly enabled by each user, under their own responsibility. We should probably add an option to make that more convenient.
https://sigquit.wordpress.com/2021/11/18/fcc-unlock-procedure-updates-in-modemmanager-1-18-4/

cc @NixOS/freedesktop @maxeaubrey

**Comment by jwygoda** [comment]
https://github.com/NixOS/nixpkgs/pull/155414
