### ISSUE TITLE
hackage-packages: keep versioned aliases for default packages

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#14643]
## Issue description

Apparently, the "default" version of a hackage package doesn't have an alias with its proper version. This can cause problems when using newer versions, that become default.

### Steps to reproduce

The example is a current breakage with emacs2nix

0c0aa0413a43bcd4d2e1a6e57997bb5cb7a27262 makes aeson 0.11.1.4 the default, but gets rid of `aeson_0_11_1_4` in the process. https://github.com/ttuegel/emacs2nix/blob/201f59f0d12d6e2ba1122b9247d0d110cfdb3680/shell.nix#L14 however, already depends on that name.

## Technical details

* System: 16.09-pre-01141a2b8d914a90 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09-pre-ba221e4f00074840

cc @ttuegel @peti

**Comment by peti** [comment]
If you want a specific version of a Hackage package, please use:

    `callHackage "my-package" "my-version" {}` 

The `haskellPackage` set itself is not going to keep old versions around any longer since we can generate any Hackage package we want on the fly.

**Comment by bendlas** [comment]
@peti I think you're misunderstanding. This ticket is not about keeping old versions, but about providing a versioned package name, even for the default versions. Right now, future versions are named like `xyz_1_23`, but when they become default, they lose the suffix and are named like `xyz`. This is a problem for dependents, that are maintained manually. This ticket is about keeping a versioned alias, even for the default versions. This won't affect closure size at all. Please consider reopening and fixing this.

**Comment by peti** [comment]
I want to go into the exact opposite direction. I'm working towards removing  all "non-default" packages from our package set, i.e. attributes with a version suffix will cease to exist entirely.
