### ISSUE TITLE
nixos/xmrig: FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW

### ISSUE THREAD

**Issue by ratsclub** [NixOS/nixpkgs#146416]
### Describe the bug
When setting up the xmrig service, It displays the message `FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW`.

### Steps To Reproduce
1. 
```nix
services.xmrig = {
  enable = true;
  settings = {
    "autosave" = true;
    "cpu" = true;
    "opencl" = false;
    "cuda" = false;
    "pools" = [
      {
        "url" = "pool.supportxmr.com:443";
        # this wallet was created for this test
        "user" = "42NedUjDoofPSLsras4DChFVgVVonqXFo7iVau6DcxQDKWWSracWfB1XtEprm1PyKw1BXLSkPcHcvjcddVDWSZBD5ZKTiEg";
        "keepalive" = true;
        "tls" = true;
      }
    ];
  };
};
 ```
2. `journalctl -u xmrig.service`
3. See the output.

### Expected behavior
Not show this message.

### Additional context
I've tried the following:

1. Removing the `DynamicUser` attribute of the service;
2. Adding both `boot.kernelParams = [ "msr.allow_writes=on" ];` and `environment.systemPackages = [ pkgs.msr-tools ];`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/etc/nix/channels/nixpkgs`
```

**Comment by ratsclub** [comment]
@aanderse Do you have any idea on this problem?

**Comment by aanderse** [comment]
After a quick look I found the following relevant spots:

- https://github.com/xmrig/xmrig/blob/69590f9777a56cb1bcd32c39cfd1049a1c6348ad/src/crypto/rx/RxMsr.cpp#L158
- https://xmrig.com/docs/miner/randomx-optimization-guide/msr#configuration
- https://xmrig.com/docs/miner/config/cpu

I think you should create an issue upstream and link here so we could work together to figure this out. I don't even know what MSR is :man_shrugging:

**Comment by ratsclub** [comment]
I've got it working I'll open a PR with the fix in a minute!
