### ISSUE TITLE
Skype background blur no longer works

### ISSUE THREAD

**Issue by foolnotion** [NixOS/nixpkgs#146487]
### Describe the bug

Skype for linux provides an option to blur the webcam background. This used to work in previous versions but now it doesn't work (the relevant button is greyed out, nothing happens). Flatpak Skype does not have this issue and works correctly.

- Skype (nix) version: 8.77.0.97
- Skype (flatpak) version: 8.78.0.161

### Steps To Reproduce
1. Open Skype
2. Go to Tools -> Audio & Video Settings...
3. Try to activate "blur my background" under Camera

### Expected behavior
Background blur should be working.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@panaeon @jraygauthier

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(bogdb): `"nixos-21.11pre292520.540dccb2aea"`
 - channels(root): `"nixos-21.11pre331460.931ab058daa"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```
[user@system:~]$ neofetch
OS: NixOS 21.11 (Porcupine) x86_64 
Host: X570 AORUS MASTER -CF 
Kernel: 5.15.2 
Uptime: 22 mins 
Packages: 1675 (nix-system), 5190 (nix-user), 2 (nix-default), 11 (flatpak) 
Shell: bash 5.1.8 
Resolution: 2560x1440, 3840x2160 
DE: LXQt 1.0.0 
WM: i3 
Theme: Materia-dark-compact [GTK2/3] 
Icons: oxygen [GTK2/3] 
Terminal: tilix 
CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 4683MiB / 64306MiB 
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: skype
```

**Comment by jraygauthier** [comment]
@foolnotion : Please try latest 8.79.0.92. Background blur worked fine for me with this version.

**Comment by foolnotion** [comment]
@jraygauthier Thanks, background blur works again with 8.79.0.92.

**Comment by jraygauthier** [comment]
Happy that it helped ;)
