### ISSUE TITLE
Split outputs of gcj are cyclically dependent

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#14657]
## Issue description

After `closure-size` merge, `gcj` fails to build. It is a dependency of `pdftk` which is hard to replace…

The only relevant message I see:

```cycle detected in the references of ‘/nix/store/0qld6bfa7ibkbi7biq8mqlxxdhqlj0bn-gcj-4.9.3-lib’```

Fixing apparently requires meddling with multiple-outputs code of `gcc49`, so I am not sure what is the best fix.

### Steps to reproduce

`nix-build '<nixpkgs>' -A gcj`

## Technical details

* System: NixOS-like (hopefully this doesn't matter; NixPkgs everything, Nix with chroot builds enabled)
* Nix version: 1.11.2
* Nixpkgs version: 39ebb01d6e8d19b042fe65d303234d0db27877eb

@vcunat any advice?

**Comment by vcunat** [comment]
My quick-fix plan was not to split gcc when java is enabled :-) (except the safe stuff like docs)

**Comment by copumpkin** [comment]
Also, https://github.com/NixOS/nix/issues/494

**Comment by 7c6f434c** [comment]
Well, it also had some linking tricks…
