### ISSUE TITLE
Post-closure-size glibc question

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14655]
I'm fixing several things here and there after our Big Merge. When I've tried to run `nix-build -A glibc` it reported only one output, `-dev`. After some head-scratching I've tried `nix-build -A glibc.out` and guessed correctly -- it got me what I wanted. Why doesn't `nix-build` make symlinks for all outputs in this case?

cc @vcunat

**Comment by vcunat** [comment]
You can `nix-build -A glibc.all`; that shows and symlinks all the outputs. This I left as it was before the branch, as I didn't get convinced enough about an alternative approach.

**Comment by abbradar** [comment]
Does `.all` exist for all derivations?

**Comment by vcunat** [comment]
It did and it still does.

**Comment by abbradar** [comment]
Nice, thanks!
