### ISSUE TITLE
clang-tools is broken (again)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#146659]
### Describe the bug
The wrapper script created by clang-tools is broken again. Previous issue: https://github.com/NixOS/nixpkgs/issues/128909.

### Steps To Reproduce
```
$ cd nixpkgs
$ git checkout 7fad01d9d5a3f82081c00fb57918d64145dc904c  # nixpkgs-unstable @ 2021-11-17
$ nix-build -A clang-tools && ./result/bin/clangd
/nix/store/pkc8gzxdxp71b0x8940kgjc1h2m4qzd0-clang-tools-13.0.0
./result/bin/clangd: line 27: /nix/store/1f8vwdir1p2z48ppqm6zcm29y73r2q1x-clang-13.0.0/bin/clangd: No such file or directory
```

### Expected behavior
clang-tools should be built correctly so that it (`clangd`, `clang-tidy` etc.) can be started/used.

### Additional context
I briefly looked at the llvmPackages v12 and v13 Nix expressions (`$EDITOR pkgs/development/compilers/llvm/1{2,3}/clang/default.nix`) since the last clang-tools fix was in the v12 package. There are enough changes that I'm unable to mentally cherry-pick the fix for v12 onto v13. I'm not sure why/when v13 diverged enough from v12 to break the package.

### Notify maintainers
@aherrmann

**Comment by r-burns** [comment]
This seems to fix it for me, care to give it a try? I think we'd need to do the same for llvm git as well:

```diff
--- a/pkgs/development/compilers/llvm/13/clang/default.nix
+++ b/pkgs/development/compilers/llvm/13/clang/default.nix
@@ -44,6 +44,8 @@ let
     ];
 
     postPatch = ''
+      (cd tools; ln -s ../../clang-tools-extra extra)
+
       sed -i -e 's/DriverArgs.hasArg(options::OPT_nostdlibinc)/true/' \
              -e 's/Args.hasArg(options::OPT_nostdlibinc)/true/' \
              lib/Driver/ToolChains/*.cpp
```

**Comment by bjornfor** [comment]
Thanks! That seems to work. Will you make a PR? Suggestion: change `cd tools; ...` to `cd tools && ...` to fail as early as possible if "tools" is missing.

**Comment by bjornfor** [comment]
And yes, we'd need it for `pkgs/development/compilers/llvm/git/clang/default.nix` too (good catch!).

**Comment by aherrmann** [comment]
I'm listed as the maintainer of `clang-tools`, but unfortunately I no longer use it and no longer have time to maintain it. Would someone here be willing to take over maintainership for this package?

**Comment by Patryk27** [comment]
@aherrmann: yes, I'd love to 🙂

**Comment by hjones2199** [comment]
Can we get this fix backported to 21.11? Not sure what the policy is for mass-rebuilds of a release branch. If that's acceptable I can prepare the PR.

**Comment by r-burns** [comment]
Sure, I think we can make that happen. Each release has its own staging branch for mass rebuilds, and this is a regression bugfix so I think it qualifies for a backport.

**Comment by quantmint** [comment]
This issue should be closed, it works now.
