### ISSUE TITLE
CoreDNS: Allow to build with custom plugins

### ISSUE THREAD

**Issue by jlesquembre** [NixOS/nixpkgs#146603]
### Describe the bug
CoreDNS is all about plugins. By default it builds with a list of default plugins: https://coredns.io/plugins/

But you can also include your own plugins. CoreDNS team maintains a list of optional plugins, some of them maintained by the CoreDNS team directly: https://coredns.io/explugins/

I think we should provide a way to build coredns with extra plugins. The part that looks tricky to me, is how to combine the source code for those extra plugins with `buildGoModule`

### Notify maintainers

@rushmorem @rtreffer @deltaevo

**Comment by DeltaEvo** [comment]
> I think we should provide a way to build coredns with extra plugins. The part that looks tricky to me, is how to combine the source code for those extra plugins with buildGoModule

Yes it would be great. Some parts is already here to do that: the service have a `package` attribute that let you specify an alternative package.
For now I was handling only with package overrides but it's not very user friendly, a wrapper would be nice, https://github.com/DeltaEvo/nixos-configs/blob/master/machines/oracle.nix#50

**Comment by KFearsoff** [comment]
I've created a PR that aims to solve this: https://github.com/NixOS/nixpkgs/issues/14671. Do you mind taking a look and testing it?

**Comment by bct** [comment]
https://github.com/NixOS/nixpkgs/pull/256710 updates @KFearsoff's PR and allows pinning a specific version of each plugin.

**Comment by jpds** [comment]
I think this can be closed now that @bct's PR has merged?
