### ISSUE TITLE
[osu-lazer] The game cannot detect the tablet.

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#146636]
### Describe the bug
In the latest version of `pkgs.osu-lazer`: https://github.com/ppy/osu/releases/tag/2021.1113.0.
The game cannot detect my tablet, but OpenTabletDriver config utils can.

### Steps To Reproduce
1. Enable Tablet driver by adding `hardware.opentabletdriver.enable = true;`
2. Plug tablet (I have one CTL-471), 
3. ...

### Screenshots
![image](https://user-images.githubusercontent.com/25173827/142637230-4475cd2b-86af-4510-a67b-5753e3f3e250.png)

### Additional context
I'm not tested osu-lazer in another distro, I'm not sure if this is an upstream issues.
I check the log of osu! in `.local/share/osu/log/`, but I got nothing related...

### Notify maintainers
@oxalica 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.16-xanmod1-cacule, NixOS, 21.05.20211115.46251a7 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"agenix, nixos-21.05.4116.46251a79f75, nixos-hardware, nixos-unstable-21.11pre331460.931ab058daa"`
 - channels(vanilla): `"home-manager, nixpkgs-21.11pre331460.931ab058daa"`
 - nixpkgs: `/home/vanilla/.nix-defexpr/channels/nixpkgs
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jansol** [comment]
Not familiar with OpenTabletDriver, is it libinput based? If not, can you try if libinput applications such as Krita work?

**Comment by VergeDX** [comment]
I tried Krita from nixos-unstable channel, it works fine with pencil pressure.

**Comment by Artturin** [comment]
@thiagokokada

**Comment by Artturin** [comment]
https://github.com/OpenTabletDriver/OpenTabletDriver/issues/1541
> turn off raw input

please test

**Comment by thiagokokada** [comment]
Disabling "High Precision mouse" seems to work for me at least.

BTW, I am not sure if OpenTabletDriver is being recognized as a mouse instead of a tablet.

**Comment by pca006132** [comment]
2022.409.0 can now detect my tablet (it doesn't work previously). Is this still an issue for you?

**Comment by thiagokokada** [comment]
> So turns out that manually adding opentabletdriver via `hardware.opentabletdriver.enable = true;` will kind of fix things... But osu is supposed to completely include opentabletdriver and make it irrelevant for most use cases, by packaging it inside of osu.

Probably because you also need to backlist the kernel modules that conflicts with OpenTabletDriver. The `hardware.opentabletdriver.enable` does this by default, however if you want to use without it you need to blacklist them manually.

> Also even with opentabletdriver the cursor tp's all over the place. So there is additional breakage there.

This is not the fault of the package very likely, probably a upstream issue. As far I remember, osu works fine in X11 but using any Wayland based window manager will break things unpredictability.

**Comment by thiagokokada** [comment]
> I am using X11 and OpenTabletDriver does work as expected with my tablet under windows and arch using that same software. It is probably not a bug in OpenTabletDriver, but just something else also trying to set the cursor position at the same time.

If you're using OpenTabletDriver and not the internal OSU tablet settings you need to disable `High Precision Mouse` (it is enabled in your screenshot). As I said, this is an upstream issue, right now High Precision Mouse under Linux is kinda broken.

**Comment by thiagokokada** [comment]
> I did also test with it disabled. I know that it is broken. It just doesn't make any difference (since osu is not handling the tablet!).

Well, not sure then, but very unlikely to be a package issue.

And osu does detect the tablet if blacklist the kernel modules, that is this issue in question. So I see no reason to keep it open.

**Comment by thiagokokada** [comment]
> I assume I would just have to blacklist the same modules as otd?

Yes.

> And if so, why is that not a config option (as it is with otd)?

Because nobody cared to create a module yet. If you want feel free to do so, I can review it.

**Comment by thiagokokada** [comment]
> Well. I did just that and rebooted. I confirmed that the usermode otd service did not exist anymore. The system and osu do detect my tablet and I can use it to input into osu. I can however not adjust the rotation, and osu still has troubles opening the tablet device files.
> 
> ![image](https://user-images.githubusercontent.com/28912031/280524817-5a8a0648-96a8-42d8-858c-559dc3497c9c.png)

Probably missing the udev files:

https://github.com/thiagokokada/nixpkgs/blob/85f1ba3e51676fa8cc604a3d863d729026a6b8eb/nixos/modules/hardware/opentabletdriver.nix#L53-L55

You can either do the same as above and add the `opentabletdriver` to `services.udev.packages` (this will only add the udev rules), or manually add the udev rules for your tablet.

**Comment by thiagokokada** [comment]
> After applying that and a reboot it did indeed seem to fix osu's tablet configuration.
> 
> Could the kernelModule blacklist and the udev rule be made into config options? (also this issue can finally be closed, as there is a good workaround)

We can always create a module, like `programs.osu-lazer`, but considering how NixOS works it is impossible to have the "package" itself do so.

**Comment by thiagokokada** [comment]
I will close this issue them. Probably most people will want to use OpenTabletDriver with osu! anyway since it offers more features (at least myself I prefer to use external otd with osu!), so setting `services.opentabletdriver.enable = true` should be an ok workaround for most people.

Everyone else can just setup it manually now as described in this issue.

**Comment by jamesbt365** [comment]
The only reason this happens is because this package does not include udev rules for OTD, thats why when you install OTD it works because it comes with the required udev rules.
