### ISSUE TITLE
Broken package: groove

### ISSUE THREAD

**Issue by joeriexelmans** [NixOS/nixpkgs#146645]
## Issue description
Broken package: 'groove'

### Steps to reproduce
Install package. Run 'groove-simulator'. File -> New Grammar... Try to save, get an exception.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 21.05.4015.5c02380de39 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(maestro): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - channels(root): `"nixos-hardware, nixos-21.05.4116.46251a79f75"`
 - nixpkgs: `/home/maestro/.nix-defexpr/channels/nixpkgs`

Permalink to broken package:
https://github.com/NixOS/nixpkgs/blob/715f63411952c86c8f57ab9e3e3cb866a015b5f2/pkgs/applications/science/programming/groove/default.nix

### Steps to resolve
It seems that the broken Nix package depends on OpenJDK17.
Found that running their latest version (5.8.1) from SourceForge with the much older OpenJDK8 works just fine. Did not test with OpenJDK11.
Probably just have to depend on an older Java version. Package version can also be bumped to 5.8.1.

Don't have sufficient knowledge of Nix to fix this myself.

Thanks

**Comment by joeriexelmans** [comment]
Probably should be assigned to @jfrankenau

**Comment by wackbyte** [comment]
I think I've fixed it. I'll submit a PR soon.
Also, I tested OpenJDK11 and it crashed there as well.
