### ISSUE TITLE
[packaging request] PRU

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#146721]
**Project description**

Pipeable Ruby - forget about grep / sed / awk / wc ... use pure, readable Ruby

**Metadata**

* homepage URL: https://github.com/grosser/pru
* source URL: https://github.com/grosser/pru
* license: mit
* platforms: ruby

**Comment by abathur** [comment]
Looks like you got this in https://github.com/NixOS/nixpkgs/pull/147653
