### ISSUE TITLE
[Tracking] make openssh changes no a mass rebuild

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nixpkgs#146702]
## Issue description

openssh is security critical and making changes to it trigger less rebuilds allows to update it faster, possibly without a staging cycle.

### Steps to reproduce

Change openssh and rebuild your system.

## Technical details

Will follow.

**Comment by zimbatm** [comment]
Is that solved now?

**Comment by SuperSandro2000** [comment]
If we take a look at one of the last openssh PRs #259051 then I think so.
Thanks for the headsup.
