### ISSUE TITLE
`nixos-21.05` seems to have advanced without expected store paths in the cache

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#146719]
### Describe the bug

```
❯ nix build --json --derivation github:nixos/nixpkgs/nixos-21.05#legacyPackages.x86_64-linux.cachix     
[12/0/241 built] building primitive-0.7.1.0 (buildPhase): [ 3 of 13] Compiling Data.Primitive.Array ( Data/Primitive/Array.hs, dist/build/Data/Primitive/Array.o, dist/build/Dat^error: interrupted by the user
```

Why? I've gone to effort to make sure I'm not waiting on GHC to get cachix, and yet here I am, watching CI jobs balloon because they're going to take a few hours to build Haskell.

**Comment by vs49688** [comment]
It's not just GHC and cachix, it's thunderbird and libreoffice too. I never knew "unpacking source archive" could cause PTSD:
```
unpacking sources
unpacking source archive /nix/store/ckv6pkvavar9n8sgjc0n6b42r2xjps5i-thunderbird-91.3.0.source.tar.xz
...
unpacking sources
unpacking source archive /nix/store/zfv7vpi1988r5gg5xs93ik63pb06hhn4-libreoffice-7.1.4.2.tar.xz
...
```

**Comment by Artturin** [comment]
i saw something like this from someone on -unstable yesterday on matrix

**Comment by vcunat** [comment]
They should all be there.  (for about two days, I think)  As mentioned on matrix, I cancelled some "superfluous" rebuilds and didn't realize that on the next evaluation the `tested` job might succeed due to hashes being changed.  So it happened even though around 9k builds were missing.

As for possible extending of the channel-blocker set, I think that would be for another thread.

**Comment by colemickens** [comment]
No. I'm re-opening this. I can prove it happened again today.

What do we need to fix this? I'll dedicate time to investigating it if I can be enabled to fix it? This is horrible, I don't want new users hitting this.

**Comment by colemickens** [comment]
Well, this time it was `nixos-unstable`. I'll make this a more generic issue.
