### ISSUE TITLE
pkg request: appflowy: an open source notion clone/replacement

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#146724]
**Project description**

https://github.com/AppFlowy-IO/appflowy

> AppFlowy is an open-source alternative to Notion. You are in charge of your data and customizations. Built with Flutter and Rust. 

Note sure how hard/impossible this will be to publish, given it's Flutter.... *and* Rust.

**Metadata**

* homepage URL: https://github.com/AppFlowy-IO/appflowy
* source URL: https://github.com/AppFlowy-IO/appflowy
* license: agpl3
* platforms: unix?

**Comment by DarkOnion0** [comment]
Hi there, since the pull request #153333 has been merged into master, I think we can close this issue, dont you think so ?
