### ISSUE TITLE
[Packaging request] OpenDrop

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#146777]
**Project description**
OpenDrop is an AirDrop compatible implementation for Linux.

**Metadata**

* homepage URL: https://github.com/seemoo-lab/opendrop
* source URL: https://github.com/seemoo-lab/opendrop
* license: gpl3
* platforms: linux

**Comment by legendofmiracles** [comment]
Dependency [owl](https://github.com/seemoo-lab/owl) also would have to be packaged.

**Comment by WolfangAukang** [comment]
> Dependency [owl](https://github.com/seemoo-lab/owl) also would have to be packaged.

Here you go:

```
{ stdenv, lib, fetchFromGitHub, cmake, libev, libnl, libpcap }:

stdenv.mkDerivation rec {
  pname = "owl";
  version = "unstable-2020-12-19";

  src = fetchFromGitHub {
    owner = "seemoo-lab";
    repo = "owl";
    rev = "fb09463f6a3d175c125165b89ec39a25b33e14b1";
    sha256 = "sha256-QSwCxpqp9CyB/MPstgtYr73/STHbcljiCpozhzgzAvA=";
    fetchSubmodules = true;
  };

  nativeBuildInputs = [ cmake ];
  buildInputs = [ libev libnl libpcap ];
}
```

This one covers the dependencies listed (`libnl` is Linux specific). I haven't tested it yet though.

**Comment by WolfangAukang** [comment]
Btw, `[fleep](https://pypi.org/project/fleep/)` needs to be packaged.

**Comment by WolfangAukang** [comment]
I have packaged `owl`, `fleep` and `opendrop` [here](https://github.com/WolfangAukang/nixpkgs/tree/opendrop), but it seems my computer is not able to create an interface on `owl` to test it, so in case you want to try it, it would be much appreciated.

Plus, had to disable tests as I'm getting an unclear issue. It is described on the `opendrop` settings.

**Comment by legendofmiracles** [comment]
owl says that you need an interface capable of package injection. Most normal wifi antennas don't have that anymore...

**Comment by WolfangAukang** [comment]
> owl says that you need an interface capable of package injection. Most normal wifi antennas don't have that anymore...

Exactly. My hardware does not have that capability.

**Comment by onny** [comment]
@WolfangAukang Oh cool, can you create an PR?

**Comment by WolfangAukang** [comment]
Yes sure, on it
