### ISSUE TITLE
Package request: helix

### ISSUE THREAD

**Issue by jgarte** [NixOS/nixpkgs#146828]
A kakoune / neovim inspired editor, written in Rust.

The editing model is very heavily based on kakoune; during development I found myself agreeing with most of kakoune's design decisions.

**Metadata**

* homepage URL: https://helix-editor.com/
* source URL: https://github.com/helix-editor/helix
* license: Mozilla Public License 2.0
* platforms: unix, linux, darwin

> helix requires the 2021 edition of Rust, which came out just recently in October.

**Comment by jakobneufeld** [comment]
@jgarte. I have packaged a few rust a packages before, so I will try packging helix!

**Comment by msfjarvis** [comment]
Helix is already available in nixpkgs-unstable: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/helix/default.nix#L28

**Comment by theoparis** [comment]
I installed helix via this package and ran `hx -g fetch` and it complains about the helix runtiem directory being read only...

```
Error: Failed to fetch some grammar(s)

Caused by:
    0: Could not create grammar directory "/nix/store/k2w2nr3x2d9yhm3lj2xn3v43kx9wga3q-helix-22.03/lib/runtime/grammars/sources/toml"
    1: Read-only file system (os error 30)
```

**Comment by YoshiRulz** [comment]
Judging by helix-editor/helix#3310 that's intended behaviour. Syntax highlighting is already available, check `hx --health`.
