### ISSUE TITLE
remove patch which is in source code

### ISSUE THREAD

**Issue by soloturn** [NixOS/nixpkgs#146844]
this patch is already in xmoto-0.6.1 afaik, better remove it?
https://github.com/NixOS/nixpkgs/blob/b56d7a70a7158f81d964a55cfeb78848a067cc7d/pkgs/games/xmoto/default.nix#L16

**Comment by hqurve** [comment]
Hi, you should rename the issue title to include `xmoto` and should ping the package maintainers. 

Also, notice that although the master branch of xmoto includes the commit, the 0.6.1 release doesn't (https://github.com/xmoto/xmoto/tree/0.6.1). So, the patch is still necessary as long as we stay on the 0.6.1 release

**Comment by Artturin** [comment]
Closing because a maintainer will see that the patch fails to apply when they update the package
