### ISSUE TITLE
cernlib: build failure on upcoming gcc-11 and binutils-2.37. Consider removing?

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#146859]
### Describe the bug

`cernlib` (https://cernlib.web.cern.ch/cernlib/) is an old unmaintained software from 2006.

Currently fails to build on `gfortran-11` due to `fortran` typing changes:

```
cernlib> /build/2006/src/packlib/cspack/xz/xzctof.F:40:27:
cernlib>    40 |       DATA         IPATT/X'0123CDEF'/
cernlib>       |                           1
cernlib> Error: Hexadecimal constant at (1) uses nonstandard X instead of Z [see '-fno-allow-invalid-boz']
cernlib> make[3]: *** [Makefile:221: archive/xzctof.o] Error 1
```

And also on `binutils-2.37` that will need an `ar l` fix: https://github.com/NixOS/nixpkgs/pull/134917

WDYT of removing `cernlib` instead of patching it? Is it still useful?

CC @veprbl 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: cernlib
```

**Comment by veprbl** [comment]
@trofi Thank you for reporting!
