### ISSUE TITLE
regression in 'Howto keep multiple packages up to date at once'

### ISSUE THREAD

**Issue by jcumming** [NixOS/nixpkgs#14682]
## Issue description

In following https://nixos.org/wiki/Howto_keep_multiple_packages_up_to_date_at_once , after merging master,  a buildEnv with a ruby package in it blows up with:

```sh
$ nix-env -iA pkgs.testEnv --show-trace
installing ‘test’
error: while evaluating the attribute ‘pkgs’ of the derivation ‘test’ at nixpkgs/pkgs/build-support/trivial-builders.nix:10:14:
while evaluating the attribute ‘meta.outputsToInstall’ at nixpkgs/pkgs/development/ruby-modules/bundler-env/default.nix:64:14:
attribute ‘outputsToInstall’ missing, at nixpkgs/pkgs/build-support/buildenv/default.nix:54:46
```
### Steps to reproduce

In `~/.nixpkgs/config.nix` have 

```nix
{
 packageOverrides = pkgs_: with pkgs_; { 
    testEnv = with pkgs; buildEnv {
      name = "test";
      paths = [
        jekyll
      ];
    };
  };
}
```

And then do

`nix-env -iA pkgs.testEnv`

## Technical details

* System: NixOS: `master`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09.git.6802049M"`

**Comment by domenkozar** [comment]
cc @vcunat

**Comment by vcunat** [comment]
Thanks for catching this case.
