### ISSUE TITLE
google-chrome fails to find libpangocairo

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#14695]
## Issue description

Google chrome uses some rather unusual approach to set it's `LD_LIBRARY_PATH`:

```
  env = buildEnv {
    name = "google-chrome-env";
    paths = [ pango cairo ...  ]
  }

  LD_LIBRARY_PATH="${env}/lib:${env}/lib64"
```
etc.

In current master (366c19ffd8bda28012081e660beb45e52686c29e) this doesn't work anymore as google-chrome can't find `libpangocairo.so`. This happens because it isn't in the `buildEnv`s output.

`nix-build . -A pango` generates `results-dev` with only contains `/lib/pkgconfig/...`, not `libpangocairo.so`.

To fix this, I had to change `pango` to `pango.out` (not permanently, just as a check) which contains the necessary libs in `/lib`. Unfortunately, google-chrome continues failing to start, this time by failing to load `libdbus.so`. 

This leads me to the assumption that this goes deeper and is related to the `closure-size` merge.

### Steps to reproduce

`nix-build . -A google-chrome && result/bin/google-chrome`
`nix-build . -A pango`
`nix-build . -A pango.out`

## Technical details

* System: 3ae4d2a and later
* Nix version: 1.11.2
* Nixpkgs version: 16.09.git.366c19f

CC @vcunat @msteen

**Comment by abbradar** [comment]
I think I've fixed that in https://github.com/NixOS/nixpkgs/pull/14658 , but I may have overlooked several places.

**Comment by the-kenny** [comment]
Ah! `makeLibraryPath` looks like a good solution. I'll try porting `google-chrome` over to it.

**Comment by abbradar** [comment]
We also have `makeBinPath` and `makeSearchPathOutputs "lib64" ["lib"]` (which I've added recently and want to replace with `makeSearchPathOutput "lib" "lib64"` in https://github.com/NixOS/nixpkgs/pull/14694 -- but feel free to use it, I'll update it in the PR).

**Comment by the-kenny** [comment]
I left a note in 0c5ed43 as I'm not absolutely sure if adding `stdenv.cc.cc` to `makeLibraryPath` was the correct call here. If it's not, feel free to reopen and I'll fix it.

**Comment by msteen** [comment]
@the-kenny That approach of setting `LD_LIBRARY_PATH` was chosen because I based the initial version of the google-chrome package on Atom, which had [similar requirements](https://github.com/NixOS/nixpkgs/blob/67d2972645ca73062fd3bc8d99865013b31eb739/pkgs/applications/editors/atom/default.nix).

**Comment by abbradar** [comment]
Hm, I've recently replaced `buildEnv` with `makeLibraryPath` for `atom` to fix it. Would it cause problems?

**Comment by msteen** [comment]
@abbradar I do not think so, since as far as I know the reason for using `buildEnv` in Atom was the same as for the google-chrome package, to simplify setting the paths.

**Comment by mucaho** [comment]
When I created the PR for #14447 , there was no error. However, now that it has been merged I get the same error message, when trying to `nix-env -iA nixpkgs.vscode`:
```
code: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory
```
Could this be related to the error described here? If so, what is the solution?

**Comment by the-kenny** [comment]
`buildEnv` has many more use cases than this broken one, but I agree - we should check those. Could you create another ticket and tag it with the `closure-size` tag (like this one)?
