### ISSUE TITLE
Replace ad-hoc output splitting hacks with multiple outputs

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14693]
## Issue description

Now that multiple outputs branch has landed we can replace ad-hoc splitting hacks with it. avn from IRC suggested to do this for PulseAudio. This might be a simple task -- leaving it here to not lose it in the noise.

**Comment by avnik** [comment]
ffado, jackaudio, kerberos (both heimdal and krb5), nghttp2 as well.

**Comment by vcunat** [comment]
IIRC go packages often override `outputs` attribute in the resulting attrmap. Such use cases should be replaced by `meta.outputsToInstall`, at least after merging https://github.com/NixOS/nix/pull/815 yet.

**Comment by avnik** [comment]
Still actual ;(

May be would be good to create separate issues for each affected package?
(`git grep libOnly` shows them all). Although I try to fix at least some of them.

**Comment by edolstra** [comment]
Yes, separate issues would be more useful.

**Comment by avnik** [comment]
Well, I definelly know how (and would like) to do it for pulseaudio, although  jack2 and ffado mutually depends on each other, and libOnly breaks this loop at least partially

**Comment by avnik** [comment]
I revive it as PR, because at least biggest part of sound-related stuff is a solvable.
