### ISSUE TITLE
Gnome extension brightness-control-using-ddcutil not patched

### ISSUE THREAD

**Issue by pp5x** [NixOS/nixpkgs#146926]
### Describe the bug

The extension does not work correctly because it can not find `/usr/bin/ddcutil` in its path. The path is hardcoded in https://github.com/daitj/gnome-display-brightness-ddcutil/blob/master/display-brightness-ddcutil%40themightydeity.github.com/extension.js#L64

The path remain unchanged on my system.

### Steps To Reproduce

1. Enable gnome 3

```
services.xserver.displayManager.gdm.enable = true;
services.xserver.desktopManager.gnome.enable = true;
```
2. Enable ddcutil

 ```
environment.systemPackages = with pkgs; [
    ddcutil
    gnomeExtensions.brightness-control-using-ddcutil
];
```

3. Gnome extension is not working even though its detected by ddcutil
```
[pp5x@photon:~]$ ddcutil detect
Display 1
   I2C bus:  /dev/i2c-2
   EDID synopsis:
      Mfg id:               DEL
      Model:                DELL U2412M
      Product code:         41082
      Serial number:        Y1H5T2AT3WNL
      Binary serial number: 861359692 (0x33574e4c)
      Manufacture year:     2012,  Week: 44
   VCP version:         2.1

```

#### Side note

Should not the gnome extension also add a dependency to `ddcutil` and `ddcutil` to `hardware.i2c.enable = true` ?

### Expected behavior

The extension should show a slider for my display.

### Screenshots

![image](https://user-images.githubusercontent.com/1910979/142778472-1989c8b5-2746-463d-a62d-adf56bcf048a.png)

### Notify maintainers

@piegamesde 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[pp5x@photon:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.05.4132.24528474d2b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4132.24528474d2b"`
 - channels(pp5x): `"home-manager-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by piegamesde** [comment]
Interesting. See #136111, this should have been fixed in #137131. Please make sure you are using that commit and report back.

**Comment by pp5x** [comment]
My bad, indeed it is not available on the stable `nixpkgs`. I am closing.

Here is the fix in case someone else is running into the same beginner issue.
```nix
# configuration.nix
{ config, pkgs, ... }:

let
  unstable = import <nixos-unstable> {};
in {
  environment.systemPackages = with pkgs; [
    unstable.gnomeExtensions.brightness-control-using-ddcutil
  ];
}
```

**Comment by Yeshey** [comment]
I think I'm hitting this again recently

![Image](https://github.com/user-attachments/assets/cdc6c7b6-baac-4dc7-a14b-2e231413d74e)
