### ISSUE TITLE
runuser from utillinux doesn't work.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#14701]
## Issue description

The runuser command from utillinux doesn't work. This is apparently a PAM issue.

Original message on the mailing list: http://lists.science.uu.nl/pipermail/nix-dev/2016-April/020180.html

### Steps to reproduce

```sh
# runuser -ukevincox whoami
runuser: Failure setting user credentials
# echo $?
1
```

## Technical details

* System: 16.09pre79463.d88ae10 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 15.09.505.7adab11

**Comment by zimbatm** [comment]
The util-linux package in ubuntu xenial ships with the following pam.d config:
```
root@49f3316d64c6:/# cat /etc/pam.d/runuser
#%PAM-1.0
auth		sufficient	pam_rootok.so
session		optional	pam_keyinit.so revoke
session		required	pam_limits.so
session		required	pam_unix.so
root@49f3316d64c6:/# cat /etc/pam.d/runuser-l 
#%PAM-1.0
auth		include		runuser
session		optional	pam_keyinit.so force revoke
-session	optional	pam_systemd.so
session		include		runuser
```

**Comment by zimbatm** [comment]
Both files are shipped by `debian/util-linux.runuser.pam` and `debian/util-linux.runuser-l.pam` respectively in the original package source. It should be possible to integrate them in our own package.

**Comment by kevincox** [comment]
The following line in the NixOS config appears to solve the problem. But it would be nice to have it fixed in the package itself.

Also I know next to nothing about pam so I might be doing something very wrong.

```nix
security.pam.services.runuser = { };
```
