### ISSUE TITLE
stdenv-darwin build problem

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#14704]
## Issue description

i want to build a package on darwin (from git master commit https://github.com/NixOS/nixpkgs/tree/358900674b9ecf85ef4add5fa36aa0eb94f76c36) but get this error:

```
building path(s) ‘/nix/store/f2cdni6pj5mj7cv59w8hyny8gjn6q8gf-stdenv-darwin’
output ‘/nix/store/f2cdni6pj5mj7cv59w8hyny8gjn6q8gf-stdenv-darwin’ is not allowed to refer to path ‘/nix/store/96kz6yfzhx9v7i591sdp015lscwp1xa8-llvm-3.7.1’
```

same error on different machines, so not a local problem.

### Steps to reproduce

```
nix-env -iA hello -f ~/code/nixpkgs/
```

## Technical details

* System: OS X 10.10.5 / 10.9.5
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: git master

@edolstra @copumpkin

**Comment by copumpkin** [comment]
I'll try to take a look this weekend, but unsure I'll have the time

**Comment by davidak** [comment]
👍 Thank you, @copumpkin!

**Comment by domenkozar** [comment]
We should also fix mysql as it's blocking the channel: http://hydra.nixos.org/build/34620439

**Comment by davidak** [comment]
@domenkozar here is my latest error https://github.com/NixOS/nixpkgs/issues/11861#issuecomment-210936438

**Comment by copumpkin** [comment]
@davidak @domenkozar will take a look and see if it's an easy fix. Is there a bug for the actual mariadb brokenness? I couldn't see one

**Comment by davidak** [comment]
@copumpkin the linked issue is about that problem.

**Comment by copumpkin** [comment]
@davidak I _think_ mariadb/mysql is good again. Can you give it a quick go to make sure I didn't break something subtle?

**Comment by davidak** [comment]
@copumpkin it builds now but again this priority conflict:

```
/nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/lib/libmysqld.18.dylib: fixing dylib
stripping (with flags -S) in /nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/lib  /nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/bin
strip: can't process non-object and non-archive file: /nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/lib/mysql/plugin/daemon_example.ini
strip: can't process non-object and non-archive file: /nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/bin/mysql_config
patching script interpreter paths in /nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib
/nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/bin/mysql_config: interpreter directive changed from "/bin/sh" to "/nix/store/jd4z1i8wyzcaaymk4mh41bdn2qw80bx9-bash-4.3-p42/bin/sh  "
building path(s) ‘/nix/store/xb5sx67kjmpvfx166q9wa6kphvjd4aa2-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/vsr0d0rdk4qbvpxgdk85gl09afn7lrc0-mariadb-10.1.9/bin/mysql_config’ and ‘/nix/store/p0jqcgfnaygmjp26wlh49bs11c09rqsq-mariadb-10.1.9-lib/bin/mysql_config’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/88clrrxjcbdycqaax9npz1iricx4dzw3-user-environment.drv’ failed with exit code 2
error: build of ‘/nix/store/88clrrxjcbdycqaax9npz1iricx4dzw3-user-environment.drv’ failed
```

**Comment by copumpkin** [comment]
That sounds like a broader multiple-outputs issue that shouldn't be specific to darwin. It looks like the post-install script explicitly copies `mysql_config` into `$lib/bin`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sql/mariadb/default.nix#L112-L115

Not sure what the proper multiple-outputs behavior here is. @vcunat, any ideas?

**Comment by vcunat** [comment]
This issue has been there for much longer. https://github.com/NixOS/nixpkgs/issues/12072
