### ISSUE TITLE
PYBITMESSAGE not installing on NIXOS 21.05

### ISSUE THREAD

**Issue by alciono** [NixOS/nixpkgs#147100]
### Bug Description

_Installation of PYBITMESSAGE aborted with error message:_

> nix-env -iA nixos.pybitmessage --show-trace 
> installing 'pybitmessage-0.6.3.2'
> error: while evaluating the attribute 'drvPath' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:163:7:
> while evaluating the attribute 'propagatedBuildInputs' of the derivation 'pybitmessage-0.6.3.2' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/stdenv/generic/make-derivation.nix:201:11:
> while evaluating the attribute 'out.outPath' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:156:13:
> while evaluating the attribute 'propagatedBuildInputs' of the derivation 'python2.7-pyopencl-2021.1.4' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/stdenv/generic/make-derivation.nix:201:11:
> while evaluating 'getOutput' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/attrsets.nix:486:23, called from undefined position:
> while evaluating anonymous function at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/stdenv/generic/make-derivation.nix:166:17, called from undefined position:
> while evaluating 'callPackageWith' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:117:35, called from /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/top-level/python-packages.nix:6859:13:
> while evaluating 'makeOverridable' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:67:24, called from /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:121:8:
> while evaluating anonymous function at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/development/python-modules/pytools/default.nix:1:1, called from /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:69:16:
> while evaluating 'makeOverridablePythonPackage' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/top-level/python-packages.nix:32:37, called from /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/development/python-modules/pytools/default.nix:12:1:
> while evaluating 'makeOverridable' at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:67:24, called from /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/top-level/python-packages.nix:34:12:
> while evaluating anonymous function at /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/pkgs/development/interpreters/python/mk-python-derivation.nix:30:1, called from /nix/store/fyfzbrgqy4ir0nia9ypzkhfskcpwx3j0-nixos-21.05.4132.24528474d2b/nixos/lib/customisation.nix:69:16:
> pytools-2021.2.1 not supported for interpreter python2.7

### Notify maintainers

@FRidh
@fgaz
@dezgeg
@mguentner
@vcunat
@shak-mar
@prusnak
@OmnipotentEntity
@Profpatsch
@jgillich

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.05.4132.24528474d2b (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4132.24528474d2b"`
 - channels(k): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by prusnak** [comment]
BitMessage is not compatible with Python 3 and since Python 2.7 is unsupported for almost 2 years (since January 2020) we will have to wait until the upstream releases new version that fixes that.

**Comment by alciono** [comment]
Thank you prusnak!
