### ISSUE TITLE
Package Request:  Teapot, a compact, type-safe, 3D spreadsheet

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#147213]
**Project description**

Teapot is an interesting project that implements a compact spreadsheet in roughly 140k, with the following features:

- **UI:**  Ncurses terminal UI, FLTK windowed GUI, and a batch processing mode all available.
- **Cell Syntax:**  Cell locations represented as lists of coordinates.  Eg, instead of "B1" or "R1C2", cells are referenced as "@(1,2,0)".
- **Three Dimensions:**  This 3-coordinate style adds a third dimension to the spreadsheet, reducing the need for hiding columns or rows of intermediate results as is sometimes the case in traditional spreadsheets, among other things.
- **Relative References:**  This also enables both relative cell and relative formula references that make refactoring the spreadsheet easier.
- **Type-Safety:**  All values have a type, and all operations and formulas check types.  No more adding a float to a string and getting a (probably undesirable) result.
- **Iterative Expressions:**  Modeled on clocked expressions, these solve problems with circular dependencies in traditional spreadsheets and effectively make teapot Turing-complete.
- **Platform-Independent File format:**  Defined by XDR and portable across machines, especially floating point representation that may differ across platforms
- **Legacy File format support:**  Portable ASCII file format, standard CSV, SpreadsheetCalculator SC and Lotus 1-2-3 WK1 format.
- **Extensibility:**  Easily extended by new functions in C.
- **Internationalization:**  Can be internationalized and comes with English, Dutch, German and Polish message catalogs.
- **Interoperability:**  Interfaces to troff/tbl, LATEX, HTML and CSV which are well-suited for further processing, be it graphing, typesetting, accounting or anything else.

**Metadata**

* homepage URL:  https://www.syntax-k.de/projekte/teapot/
* source URL:  https://www.syntax-k.de/projekte/teapot/ (bottom of page)
* license: GPL3
* platforms: unix, linux, darwin

**Comment by WolfangAukang** [comment]
I tried to build this from source, but I'm getting an issue with it. Here is what I did so far, in case someone wants to try it:

```
{ stdenv, lib, fetchurl, cmake, glibc, libtirpc, gnulib }:

stdenv.mkDerivation rec {
  pname = "teapot";
  version = "2.3.0";

  src = fetchurl {
    url = "https://www.syntax-k.de/projekte/teapot/teapot-2.3.0.tar.gz";
    sha256 = "sha256-WA4MtBauP7Pfh7xukuQ79ykp1Htl6itQvAms6jv/C2U=";
  };

  nativeBuildInputs = [
    cmake
    gnulib
  ];

  buildInputs = [
    libtirpc
  ];

  NIX_CFLAGS_COMPILE = [ "-I${libtirpc.dev}/include/tirpc" ];
  NIX_LDFLAGS = [ "-ltirpc" ];
}
```

I am going to try with the deb and see if it works.

**Comment by WolfangAukang** [comment]
I got the deb working successfully (even created a desktop entry for the GUI client, although no icon).

I'm going to keep trying with the source today (it is an issue regarding mbslen not being recognized), but if I can't get that, then I will post the working one.

**Comment by AndersonTorres** [comment]
> I'm going to keep trying with the source today (it is an issue regarding mbslen not being recognized), but if I can't get that, then I will post the working one.

`mbslen` is just a warning, it can be fixed with a simple patch.

The more serious problems are compiling with FLTK support and build the docs. Maybe more patches are needed.

(On the other hand, it can be useful to package the already-given binary targz.)
