### ISSUE TITLE
Spotify fails with 'undefined symbol SSL_CTX_set_alpn_protos'

### ISSUE THREAD

**Issue by wandernauta** [NixOS/nixpkgs#14729]
## Issue description

When I start Spotify, it briefly flashes its main window, loads all playlists, then quits with the following message:

    /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/share/spotify/.spotify-wrapped:
    symbol lookup error: /nix/store/0x6mwl...-curl-7.47.1/lib/libcurl.so.4: undefined symbol:
    SSL_CTX_set_alpn_protos

Spotify seems to ship its own libssl which is apparently incompatible with the one libcurl expects.

### Steps to reproduce

* Install spotify (I used `nix-shell --pure -p spotify`)
* Start spotify (`spotify`)

## Technical details

From inside the nix shell:

> [nix-shell:~]$ spotify --version
> /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/bin/spotify: /nix/store/0x6mw...-curl-7.47.1/lib/libcurl.so.4: no version information available (required by /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/bin/spotify)
> /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/bin/spotify: /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/lib/spotify/libssl.so.1.0.0: no version information available (required by /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/bin/spotify)
> /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/bin/spotify: /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/lib/spotify/libcrypto.so.1.0.0: no version information available (required by /nix/store/l0361...-spotify-1.0.26.125.g64dc8bc6-15/bin/spotify)
> Spotify version 1.0.26.125.g64dc8bc6, Copyright (c) 2016, Spotify Ltd
>
> [nix-shell:~]$ curl-config --version
> libcurl 7.47.1
> 
> [nix-shell:~]$ curl-config --features
> SSL
> IPv6
> UnixSockets
> libz
> NTLM
> NTLM_WB
> TLS-SRP
> HTTP2
> 
> [nix-shell:~]$ curl-config --configure
>  '--disable-static' '--disable-dependency-tracking' '--prefix=/nix/store/0x6mwlvy3wp0zgph638kjq2v50nd9gxj-curl-7.47.1' '--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt' '--disable-manual' '--with-nghttp2=/nix/store/07p7mcgmgn0fpslvzwszhx0a52il69jg-libnghttp2-1.8.0' '--with-ssl=/nix/store/cd50ncj52230kmv6sbxhf9ybs7s6m3cq-openssl-1.0.2g' '--with-libssh2=/nix/store/riilgjaqdgp2na4y4dhd62bxfc8jy7dm-libssh2-1.7.0' '--disable-ldap' '--disable-ldaps' '--without-libidn' 'CC=gcc'

Outside:

> ~ » nixos-version
> 16.09pre80183.551296a (Flounder)
> ~ » nix-env --version
> nix-env (Nix) 1.11.2
> ~ » nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
> "16.09pre80183.551296a"

**Comment by wandernauta** [comment]
The 'outside' libssl appears to have SSL_CTX_set_alpn_protos while the one Spotify bundles doesn't:

> ~ » nm /nix/store/cd50nc\*-openssl-1.0.2g/lib/libssl.so.1.0.0 | grep -c SSL_CTX_set_alpn_protos
> 1
> ~ » nm /nix/store/l0361\*-spotify-\*/lib/spotify/libssl.so.1.0.0 |  grep -c SSL_CTX_set_alpn_protos
> 0

**Comment by joachifm** [comment]
cc @sheenobu has mentioned something about fixing ssl errors before, perhaps they know more.

**Comment by sheenobu** [comment]
This has been fixed on master and release-16.03 with spotify package 1.0.27.. Not sure how to get this into 16.09pre. 50e8994

The openssl bundled into spotify is actually placed by the spotify .nix file. The fix changes the linked version of spotify from openssl_1_0_1 to openssl .

> nm /nix/store/cd50nc*-openssl-1.0.2g/lib/libssl.so.1.0.0 | grep -c SSL_CTX_set_alpn_protos
1

> nm /nix/store/*spotify-1.0.27*/lib/spotify/libssl.so.1.0.0 | grep -c SSL_CTX_set_alpn_protos
> 1

**Comment by joachifm** [comment]
If it is already fixed in master, it is just a matter of waiting until nixos-unstable catches up (it is currently quite stale). @wandernauta you must either fix this via a local override or switch to the release channel (recommended).

**Comment by joachifm** [comment]
Closing, as I don't think there's anything more to do here

**Comment by wandernauta** [comment]
I've switched to the release channel, then built Spotify from `master`, and it works like a charm. Thanks, both!
