### ISSUE TITLE
Nix 2.4: Can't `nix search` without flake feature enabled

### ISSUE THREAD

**Issue by aopom** [NixOS/nixpkgs#147287]
## Issue description
On NixOS unstable, I can't run `nix search` without enabling the `flakes` feature flag. Before Nix 2.4, I was able to search for non-flakes packages.
I don't want to use flakes till it doesn't land on stable, because it's a big change I don't want to handle right now. But I'd like to continue to be able to search locally for packages.

### Steps to reproduce
On NixOS unstable, `nix --extra-experimental-features nix-command search hello`
outputs:
```
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.80, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11pre333218.263ef4cc414"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
This is a Nix bug not nixpkgs
