### ISSUE TITLE
nixosTests.keymap.qwertz fails on aarch64-linux

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#147294]
- https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.keymap.qwertz.aarch64-linux/all
- https://hydra.nixos.org/job/nixos/release-21.11/nixos.tests.keymap.qwertz.aarch64-linux

In combination with 21.11 adding it to the `tested` job, this prevents `nixos-21.11` channel.

_The keymap tests don't have any maintainers.  That's quite an issue for channel-blocking jobs, I think._

**Comment by vcunat** [comment]
Well, we could remove `keymap.qwertz.aarch64-linux` from the blocking set, at least for now.  It certainly doesn't feel so critical to me.  (Though qwertz layout gets vast majority in my country actually.)

**Comment by erictapen** [comment]
In https://github.com/NixOS/nixpkgs/pull/144106#issuecomment-979493318 it was discussed wether Linux 5.15 could be the cause, but the way I see it the test is running with Linux 5.10? 5.15 seems only to be used for the stdenv.

**Comment by rnhmjoj** [comment]
> Well, we could remove keymap.qwertz.aarch64-linux from the blocking set, at least for now. It certainly doesn't feel so critical to me. (Though qwertz layout gets vast majority in my country actually.)

Yes, It is at least surprising that a large part of the channel tests is about keyboard layouts.

**Comment by nrdxp** [comment]
if the keymap tests have no maintainers, perhaps they should be removed, or at leat disabled for now.

**Comment by Artturin** [comment]
it looks like its random which one symbol fails

https://hydra.nixos.org/build/159750551/nixlog/8
```
machine # [   33.872518] root[1121]: testReader: FAIL: Expected '@|{[]}' but got 'q|{[]}'.
```

https://hydra.nixos.org/build/159733263/nixlog/17
```
machine # [   26.037142] root[1041]: testReader: FAIL: Expected '@|{[]}' but got '@|{[]0'.
```

**Comment by rnhmjoj** [comment]
This test has been flaky since [forever](https://github.com/NixOS/nixpkgs/pull/33755) and does not provide much value.
I propose to simply remove it from the tested job.

**Comment by tomberek** [comment]
I'm thinking this is a race condition with sending keys too fast, maybe made worse when a builder is under high load. Something like this perhaps?
```
diff --git a/nixos/lib/test-driver/test-driver.py b/nixos/lib/test-driver/test-driver.py
index 643446f313e..adacca47abe 100755
--- a/nixos/lib/test-driver/test-driver.py
+++ b/nixos/lib/test-driver/test-driver.py
@@ -904,6 +904,7 @@ class Machine:
     def send_key(self, key: str) -> None:
         key = CHAR_TO_KEY.get(key, key)
         self.send_monitor_command("sendkey {}".format(key))
+        time.sleep(0.01)

     def start(self) -> None:
         if self.booted:
```

**Comment by Artturin** [comment]
> I'm thinking this is a race condition with sending keys too fast, maybe made worse when a builder is under high load. Something like this perhaps?
> 
> ```
> diff --git a/nixos/lib/test-driver/test-driver.py b/nixos/lib/test-driver/test-driver.py
> index 643446f313e..adacca47abe 100755
> --- a/nixos/lib/test-driver/test-driver.py
> +++ b/nixos/lib/test-driver/test-driver.py
> @@ -904,6 +904,7 @@ class Machine:
>      def send_key(self, key: str) -> None:
>          key = CHAR_TO_KEY.get(key, key)
>          self.send_monitor_command("sendkey {}".format(key))
> +        time.sleep(0.01)
> 
>      def start(self) -> None:
>          if self.booted:
> ```

i'll run the test with and without that. and with `stress` running to mimic high load

`nix build ".#nixosTests.keymap.qwertz" --system aarch64-linux`

i had to apply this patch to run the test vm because kvm was failing
```
diff --git a/nixos/lib/qemu-common.nix b/nixos/lib/qemu-common.nix
index 1a1f7531feb..26584bc0f54 100644
--- a/nixos/lib/qemu-common.nix
+++ b/nixos/lib/qemu-common.nix
@@ -24,7 +24,7 @@ rec {
   qemuBinary = qemuPkg: {
     x86_64-linux = "${qemuPkg}/bin/qemu-kvm -cpu max";
     armv7l-linux = "${qemuPkg}/bin/qemu-system-arm -enable-kvm -machine virt -cpu host";
-    aarch64-linux = "${qemuPkg}/bin/qemu-system-aarch64 -enable-kvm -machine virt,gic-version=host -cpu host";
+    aarch64-linux = "${qemuPkg}/bin/qemu-system-aarch64  -machine virt, -cpu max";
     powerpc64le-linux = "${qemuPkg}/bin/qemu-system-ppc64 -machine powernv";
     powerpc64-linux = "${qemuPkg}/bin/qemu-system-ppc64 -machine powernv";
     x86_64-darwin = "${qemuPkg}/bin/qemu-kvm -cpu max";
```

**Comment by vcunat** [comment]
So, at least the simple step for now?  https://github.com/NixOS/nixpkgs/pull/147715

**Comment by lheckemann** [comment]
@tomberek the sleep patch does indeed fix the issue, at least when building on my Honeycomb. I do think it's odd though that the test fails in exactly the same way every time I run it. I'd expect it to fail less consistently, or in different ways…

**Comment by Artturin** [comment]
azerty test fails sometimes too https://hydra.nixos.org/job/nixos/release-21.11/nixos.tests.keymap.azerty.aarch64-linux

**Comment by lheckemann** [comment]
While it's far from elegant, I'd be fine with adding the sleep patch. Since it's only 10ms per character, I don't think the performance impact will be significant, and I'd prefer to start verifying the functionality again (major use case: encryption passphrase input, where the results aren't even visible).

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/148491

**Comment by Artturin** [comment]
troubleshooted on my rpi4 and found out that 10ms is not enough, at least 20ms is needed

> I'm thinking this is a race condition with sending keys too fast, maybe made worse when a builder is under high load. Something like this perhaps?
> 
> ```diff
> diff --git a/nixos/lib/test-driver/test-driver.py b/nixos/lib/test-driver/test-driver.py
> index 643446f313e..adacca47abe 100755
> --- a/nixos/lib/test-driver/test-driver.py
> +++ b/nixos/lib/test-driver/test-driver.py
> @@ -904,6 +904,7 @@ class Machine:
>      def send_key(self, key: str) -> None:
>          key = CHAR_TO_KEY.get(key, key)
>          self.send_monitor_command("sendkey {}".format(key))
> +        time.sleep(0.01)
> 
>      def start(self) -> None:
>          if self.booted:
> ```


i've run some tests on my rpi4b and found that applying this patch fixes the issue even with load and no delay(i still think we should leave the delay)
 
```diff
diff --git a/nixos/modules/virtualisation/qemu-vm.nix b/nixos/modules/virtualisation/qemu-vm.nix
index c7c3d747464..fa3e25afb03 100644
--- a/nixos/modules/virtualisation/qemu-vm.nix
+++ b/nixos/modules/virtualisation/qemu-vm.nix
@@ -835,6 +835,7 @@ in

     # FIXME: Consolidate this one day.
     virtualisation.qemu.options = mkMerge [
+      [ "-device virtio-keyboard" ]
       (mkIf pkgs.stdenv.hostPlatform.isx86 [
         "-usb" "-device usb-tablet,bus=usb-bus.0"
       ])
```

<pre><del>0.02 sometimes works if there is no other load
at least 0.04 is needed to sometimes not fail when i run `stress -c 4`
0.1 is safe

according to this [paper](https://userinterfaces.aalto.fi/136Mkeystrokes/resources/chi-18-analysis.pdf)
the average inter-key interval of a human is 238ms

INTER-KEY INTERVALS Average inter-key interval is 238.656 ms
(SD = 111.6). A lower bound of about 60 ms can be observed.</del></pre>
