### ISSUE TITLE
Transient test failures

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#14733]
(If there's already an issue to discuss this issue, please reference it and close this one)

http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents often has failures (red crosses) that are fixed simply by relaunching the tests (only those with certain rights on hydra can do this).

I'm opening this issue so that we can document, discuss and hopefully fix these transient failures.

As an example, we can look at `nixos:trunk-combined:nixos.tests.networking.scripted.dhcpSimple.x86_64-linux` to get the discussion going:

http://hydra.nixos.org/build/34509732/log ⇐ succeeded
http://hydra.nixos.org/build/34566924/log ⇐ failed

cc @edolstra @domenkozar

**Comment by obadz** [comment]
Looks to me that the problem occurs on or around: http://hydra.nixos.org/build/34566924/log#line-1155

```
error: unit ‘network.target’ is inactive and there are no pending jobs
unit ‘network.target’ is inactive and there are no pending jobs
```

**Comment by obadz** [comment]
Looking at similar failure for `nixos.tests.printing.x86_64-linux` in: http://hydra.nixos.org/build/34566747/log#line-1022

```
error: unit ‘cups.service’ is inactive and there are no pending jobs
unit ‘cups.service’ is inactive and there are no pending jobs
```

**Comment by domenkozar** [comment]
See #13559

**Comment by cleverca22** [comment]
possibly related, http://i.imgur.com/zd1fpWG.png

i was trying to debug some xorg stuff, and discovered xorg cant load libdbus, because libz files are in the dbus derivation!

12 hours later, the exact same qemu-vm did the right thing, and dbus was inside the dbus derivation, it fixed itself

**Comment by viric** [comment]
That was with qemu using 9p-over-zfs, which may be troublesome (inode numbers mapping, ... who knows).

**Comment by vcunat** [comment]
Well, could it be because of the fact that we had a bad dbus updated that got reverted? 9eb107dc5

**Comment by cleverca22** [comment]
nope, this was a directory listing on the exact same dbus derivation, and the host /nix/store was mounted to the guest, the filesystems should be 100% identical

**Comment by domenkozar** [comment]
This is supposed to be fixed now: https://github.com/NixOS/nixpkgs/commit/ad29b726866b5abeed9ad05cad52995295cf4813

**Comment by obadz** [comment]
"This" mean, the source of all/most the transient test failures?

**Comment by domenkozar** [comment]
There is one more test failing: raid (mdadm). We could open a separate issue for that one.

**Comment by domenkozar** [comment]
Also fixed: https://github.com/NixOS/nixpkgs/commit/3e7b510281e6144a441646dd6e32cc3f3bae1f8a

**Comment by obadz** [comment]
Really impressive stuff, can't wait to have my eyes traumatized from seeing so much green!

**Comment by edolstra** [comment]
There is still a fairly common KDE test failure that I'm looking at now.
