### ISSUE TITLE
nodePackages.thelounge 4.2.0 -> 4.3.0

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#147357]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version:
desired version:

###### Notify maintainers

maintainers:

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment]
The nixpkgs master branch now has 4.3.0.
