### ISSUE TITLE
clangStdenv can't produce c++ binaries on x86_64-linux

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#147342]
It seems that `clangStdenv` is unable to produce c++ binaries. The reason being that there's a mismatch between compiler and binutils.

```
nix-repl> llvmPackages_10.bintools.bintools
«derivation /nix/store/bjp4rhvbr06xnfsy61kqxla3hsxdjmvb-llvm-binutils-10.0.1.drv»

nix-repl> llvmPackages_10.stdenv.cc.bintools.bintools
«derivation /nix/store/jl9gi8jxn2bdqvwcjibrjrh2yfwnq3cp-binutils-2.35.2.drv»
```

this is terrible because the gcc binutils wrapper will add things like `-lgcc` to LD_FLAGS which makes linking impossible as there isn't a corresponding library available.

probably related: #142901

**Comment by symphorien** [comment]
I cannot reproduce:
c.cpp:
```
#include <vector>
#include <iostream>
#include <algorithm>
#include <random>

int main() {
  std::vector<int> v(12);
  v[0] = 1;
  v[1] = 1;
  for (int i = 2; i<v.size(); i++) {
    v[i] = v[i-1] + v[i-2];
    std::cout << i << " -> " << v[i] << std::endl;
  }
  return 0;
}
```
foo.nix
```
with import ./. {};
clangStdenv.mkDerivation { name = "test"; }
```
`nix-shell foo.nix --run "c++ c.cpp && ./a.out"` works correctly.
tested on 73369f8d0864854d1acfa7f1e6217f7d6b6e3fa1 (nixos-unstable)

**Comment by jonringer** [comment]
The toolchain was using CMake, I'll try to come up with a minimum example

**Comment by jonringer** [comment]
Haven't ran into this for 2 years, going to close
