### ISSUE TITLE
Restore Chromium tests

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#14732]
In 3135af2511cd3dfa8e3874244c46054550c563e2, Chromium tests were removed from release deps with comment:

> This is failing because it exceeds the hydra-queue-runner size limit.

I thought, possibly wrongly, that #12794 would fix this. If it did, should we restore the tests? If it did not, what needs to be done so that we can restore the tests?

**Comment by obadz** [comment]
cc @edolstra @aszlig

**Comment by edolstra** [comment]
Yes, I think it should be fine to re-enable.

**Comment by obadz** [comment]
Done
