### ISSUE TITLE
Package docker-compose not working anymore under Linux

### ISSUE THREAD

**Issue by x80486** [NixOS/nixpkgs#147450]
### Describe the Bug

I used to have `docker-compose` installed with Nix. I can't tell when this stopped working, but since I use it quite frequently it shouldn't be more than a week or so. The package is installed, but the `docker-compose` command is not recognized anymore.

### Steps To Reproduce

1. Install Arch Linux
2. Upgrade `docker` to version `20.10.11`
3. Install `docker-compose` via Nix (`nix-env --install --prebuilt-only docker-compose`)
4. Good luck trying to execute `docker-compose` 🤪 

### Expected behavior

`docker-compose` command should be available in the `PATH` — I've sourced the shell, closed the `Terminal` application, restarted the system, etc.

### Additional context

Since Arch Linux is a rolling release, I'm not sure if the current `docker` version that might be interfering somehow with `docker-compose`.

```shell
$ nix-env --query | grep docker 
docker-compose-2.0.1
$ docker-
docker-init         docker-proxy        docker-slim         docker-slim-sensor
```

### Metadata

```shell
$ nix-shell -p nix-info --run "nix-info -m" 
these 21 paths will be fetched (48.73 MiB download, 222.85 MiB unpacked):
  /nix/store/1pd6qkib7k0lzjpj6njw34yiwnahmqx6-diffutils-3.8
  /nix/store/220vwl17jy619jfrmifarw09sgfdkvr9-gnused-4.8
 ...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81-1-lts, Arch Linux, noversion`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(gorre): `"nixpkgs-21.11pre333180.98747f27ecf"`
 - nixpkgs: `/home/x80486/.nix-defexpr/channels/nixpkgs`
```

**Comment by tshakah** [comment]
Since docker-compose v2 came out, it is now a docker extension instead of a separate command. What happens if you run `docker compose`?

**Comment by x80486** [comment]
Somehow, it's not available to `Docker`:

```shell
$ docker compose 
docker: 'compose' is not a docker command.
See 'docker --help'
```

If I run `docker --help` I can't see it either. I have `Docker` installed via the (usual) package manager, and `Docker Compose` installed with `Nix`.

**Comment by tshakah** [comment]
That's strange. I'm on NixOS, but installing docker-compose `1.29.2` still lets me run `docker-compose`. Saying that, I haven't installed anything - I just have docker itself (version `20.10.9`).

Since yours is more recent, I'm surprised it doesn't have `compose`. 

There _is_ a `docker-compose_2` package available, whose source is https://github.com/docker/compose. What happens if you try that?

**Comment by x80486** [comment]
Indeed, very weird. I can confirm that the same `Docker` version in macOS has the `compose` (management) command, so it probably is a problem with the package in Arch Linux as well.

Besides that, shouldn't be an issue with the `docker-compose` NixOS package as well? — at least when installed in Linux (besides NixOS),
