### ISSUE TITLE
nvim-treesitter is incompatible with some of the treesitter grammars

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#147420]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
current version: 2021-09-17
desired version: 2021-11-26 (I have verified that updating to `08243017f2498d7e9fa6a593520c62313f06d2ea` helps with the incompatibilities)

###### Notify maintainers
maintainers:

###### Note for maintainers

Please tag this issue in your PR.

**Comment by nagisa** [comment]
I think we should have a test case or similar to ensure similar breakage does not recur when the treesitter grammars are updated.

**Comment by teto** [comment]
It may be tough to have grammars that work well with all the treesitter consumers but having the possiblity to run a check would be nice indeed

**Comment by minijackson** [comment]
Another solution would be to use nvim-treesitter's [lockfile](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lockfile.json) to ensure that we are using the same versions of the grammar.

**Comment by Profpatsch** [comment]
Fixed by #198606; you will have to switch over to the `nvim-treesitter.withPlugins` to use the nvim lockfile versions.
