### ISSUE TITLE
minecraft-launcher incompatible with 1.18-pre2 onwards

### ISSUE THREAD

**Issue by robintown** [NixOS/nixpkgs#147522]
### Describe the bug

minecraft-launcher is unable to launch Minecraft versions from 1.18-pre2 onwards, since they [require Java 17](https://minecraft.fandom.com/wiki/Java_Edition_1.18_Pre-release_2#General).

### Steps To Reproduce

Launch an installation of Minecraft 1.18-rc3

### Expected behavior

The game should launch.

### Additional context

The game crashes with an error message saying that it cannot read version 61.0 class files, indicating an outdated JRE. This can be worked around by manually specifying a Java 17 executable in the installation's properties.

The launcher hasn't been updated in a while due to https://github.com/NixOS/nixpkgs/issues/114732, which has been fine so far, but some kind of solution needs to be found for the upcoming update to be accessible.

### Notify maintainers

@cpages @ryantm @Infinisil

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"node2nix, nixos-21.11pre323079.2cf9db0e3d4, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: minecraft
# a list of nixos modules affected by the problem
module:
```

**Comment by oxalica** [comment]
1.8-pre3 works on nixos-unstable. We already have `jre` pointing to `openjdk_17`.
You need to update the channel.

**Comment by robintown** [comment]
Oh, of course :woman_facepalming:
