### ISSUE TITLE
systemd confinement does not work well with UMask=0077 + non-root user

### ISSUE THREAD

**Issue by martinetd** [NixOS/nixpkgs#147599]
### Describe the bug
Upgrading another system, I've run into troubles with a couple of services that had gained `ServiceConfig.UMask="0077"`

### Steps To Reproduce
1. This service won't start:
```
    users.users.test.isSystemUser = true;
    users.users.test.group = "test";
    users.groups.test = {};
    systemd.services.test = {
      description = "test service";
      serviceConfig = {
        Type = "simple";
        User = "test";
        ExecStart = "${pkgs.coreutils}/bin/true";
        UMask = "0077";
      };
      confinement = {
        enable = true;
        binSh = null;
        mode = "chroot-only";
      };
    };
```
2. Logs
```
machine # [    8.816255] systemd[1]: Started test service.
machine # [    8.831186] systemd[873]: Failed to create directory at /var/empty/usr: Operation not permitted
machine # [    8.862977] systemd[1]: test.service: Main process exited, code=exited, status=203/EXEC
machine # [    8.867564] systemd[1]: test.service: Failed with result 'exit-code'.
```
3. I debugged this with bind-mounting a static binary directly in / that accepted to run and sleep peacefully to inspect the chroot, it turns out /nix and /nix/store are root:root and 0700 e.g. the UMask directly impacts directories implicitly needed for bind mounting. Since /nix is non-traversable, systemd can't run the ExecStart command. That took me a while to figure...

### Expected behavior
Either we can figure a way for UMask to not affect these paths, or somehow make these paths to be owned by the test user (but we'd have to figure what paths to chown...), or we should add an assertion that UMask is not &0001(o=x) in the confinement module

### Notify maintainers
@aszlig @flokli 

### Metadata
Running nixos-unstable with nixpkgs 39cb89ef2ffcbef8d2ac2d52267ac69121a6becb if that matters (confinement didn't change in ages, but systemd version might have changed something -- although in my case the 0077 umasks were added to services on nixpkgs side so I'm not sure)

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by aszlig** [comment]
Am I correct in my assumption that this leads to the `umask` being applied to *only* the leading directories but not the last component of each bind mount? If yes, then does it make a difference if we eg. use `TemporaryFileSystem = [ "/" "/nix/store" ];` or even uglier: `TemporaryFileSystem = [ "/" "/nix" "/nix/store" ];`?

**Comment by ju1m** [comment]
@martinetd, that's the reason why I'm usually relaxing `UMask` to `066` in the services I maintain using bind mounting (eg. [transmission](https://github.com/NixOS/nixpkgs/blob/9c191ebcdfe917043195c54ab6ae8e934434fe7b/nixos/modules/services/torrent/transmission.nix#L281-L283), [syncoid](https://github.com/NixOS/nixpkgs/blob/9c191ebcdfe917043195c54ab6ae8e934434fe7b/nixos/modules/services/backup/syncoid.nix#L409-L411), [sourcehut](https://github.com/ju1m/nixpkgs/blob/5f56892d6249b54c65d24284022506734f5762bb/nixos/modules/services/misc/sourcehut/service.nix#L47-L51), [freeciv](https://github.com/NixOS/nixpkgs/blob/9c191ebcdfe917043195c54ab6ae8e934434fe7b/nixos/modules/services/games/freeciv.nix#L133-L135), [biboumi](https://github.com/NixOS/nixpkgs/blob/9c191ebcdfe917043195c54ab6ae8e934434fe7b/nixos/modules/services/networking/biboumi.nix#L211), [croc](https://github.com/NixOS/nixpkgs/blob/9c191ebcdfe917043195c54ab6ae8e934434fe7b/nixos/modules/services/networking/croc.nix#L67-L69), [tor](https://github.com/NixOS/nixpkgs/blob/9c191ebcdfe917043195c54ab6ae8e934434fe7b/nixos/modules/services/security/tor.nix#L998)).

@aszlig, AFAICS `UMask=` is used for all the directories created by `systemd`'s bound paths, this includes the previously non-existent intermediary directories, and the target directory but on the host only.
For example, with this config in `nginx.service`:
```nix
BindPaths = ["/nix/store:/var/lib/parent/test"];
UMask = lib.mkForce "077";
```

```shell
$ sudo ls -al /var/lib/parent                                                                    
drwx------  3 root root  3 nov.  27 23:30 .                                                           
drwxr-xr-x 54 root root 58 nov.  27 23:30 ..                                                          
drwx------  2 root root  2 nov.  27 23:30 test
```
```shell
$ sudo nsenter -a -t "$(systemctl show --property MainPID --value nginx.service)" ls -al /var/lib/parent  
drwx------    3 root root       3 nov.  27 23:30 .                                                    
drwxr-xr-x   54 root root      58 nov.  27 23:30 ..                                                   
drwxrwxr-t 8924 root nixbld 36906 nov.  27 23:30 test
```

**Comment by martinetd** [comment]
@aszlig this actually works!

`TemporaryFileSystem = [ "/" "/nix/store" ];` didn't work, same error with /nix being inaccessible
`TemporaryFileSystem = [ "/" "/nix" "/nix/store" ];` worked
I'm concerned setting umask will fail for other paths if a user adds other bind mounts, but that's a valid workaround.

I've been able to reproduce with just systemd-run and e.g. /usr/bin, I'll open an upstream issue to see what they think about it.
It doesn't seem natural that automatically created directories and temporaryfilesystems fall under different mode.

**Comment by aszlig** [comment]
> @aszlig this actually works!

Thanks for testing... now we just need to find a way that is less ugly than this X-D

> @martinetd, that's the reason why I'm usually relaxing UMask to 066 in the services I maintain using bind mounting

If that's working for that service in question, that's also an option.

In this case however, we need to be as generic as possible and the less options we need to override, the better.

For example if we `mkDefault` a certain umask and the services actually uses a different one, we'll get the same behaviour as described here, if we `mkForce` (or override with anything below 100) the author of the service would be equally confused since the umask setting had no effect.

**Comment by pwaller** [comment]
I hit this error without using specifying a user nor a umask. I've got:
```
    confinement = {
      enable = true;
      packages = [ pkgs.git ];
      mode = "chroot-only"; # (no effect).
    };
```
and a `script` field only. 

I see in the journalctl:
```
systemd[1]: Started <my service>
systemd[60366]: Failed to create directory at /var/empty/usr: Operation not permitted
```

`nixos-version: 22.05.20220819.00e376e (Quokka)`.

`/var/empty` appears to have no write permission bit. Which makes some sense if it is to remain empty...

**Comment by martinetd** [comment]
> systemd[60366]: Failed to create directory at /var/empty/usr: Operation not permitted

That error message is unrelated, it's always there iirc but systemd continues anyway.
If your service doesn't run and you don't have more logs you'll need to log further, I generally just go full logs and `strace -f -p 1 -o /tmp/systemd-strace` then restart the service and look at that.

**Comment by martinetd** [comment]
The umask bug has been fixed upstream, closing this -- @pwaller feel free to open a new issue and cc aszlig and myself if you need help

**Comment by ju1m** [comment]
> systemd[60366]: Failed to create directory at /var/empty/usr: Operation not permitted

That error is due to `systemd`'s `setup_namespace()`
[which calls base_filesystem_create()](https://github.com/systemd/systemd/blob/bd1f75d5fb929bd15f25d4834d8d325db25ad0fc/src/core/namespace.c#L2452-L2454) which creates [usual top level directories](https://github.com/systemd/systemd/blob/017228934833d8618774353dcccbc5ec9f78ce98/src/shared/base-filesystem.c#L31-L41).

As [proposed elsewhere](https://discourse.nixos.org/t/hardening-systemd-services/17147/18?u=julm), I think we should drop `TemporaryFileSystem=/` in favor of a `RootDirectory=` inside a `RuntimeDirectory=`, which would also make `systemd-confinement.nix` compatible with `DynamicUser=`.

**Comment by aszlig** [comment]
@ju1m: Can you please either create a separate issue or a pull request for this, since I believe this is off-topic here?
