### ISSUE TITLE
Ocenaudio fails due to bad hash

### ISSUE THREAD

**Issue by MikulasVanousek** [NixOS/nixpkgs#147676]
### Describe the bug
When trying to install Ocenaudio, the installation fails due to a sha256 hash mismatch. 
```
hash mismatch in fixed-output derivation '/nix/store/jp2dv1x05fxd1w8hgjhq0p43zjcswpwf-ocenaudio_debian9_64.deb?version=3.10.6':
  wanted: sha256:0fgvm1xw2kgrqj3w6slpfxbb3pw9k8i0dz16q9d5d8gyyvr2mh8g
  got:    sha256:1yflpyl0d1mi0zxdyrlbg0px95s2c945ahy0agc8rha01ccf7jwy
cannot build derivation '/nix/store/4jy1ckxhq4axayamhim56hw8x0c0wxbj-ocenaudio-3.10.6.drv': 1 dependencies couldn't be built
```
### Steps To Reproduce
1. Add ocenaudio to my NixOS config
2. `sudo nixos-rebuild switch`

### Expected behavior
I expected the program to be installed.

### Notify maintainers

@onny 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.10.79, NixOS, 21.05.4381.3bea86e918d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(miki): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - channels(root): `"nixos-21.05.4381.3bea86e918d"`
 - nixpkgs: `/home/miki/.nix-defexpr/channels/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
ocenaudio
```

**Comment by Artturin** [comment]
looks like aur has the same problem 
https://aur.archlinux.org/packages/ocenaudio-bin/
> The checksum is correct, but the version is not. And since ocenaudio download is not versioned (that's an upstream problem), the checksum from 2.9.4 does not match the new version 2.9.5.
