### ISSUE TITLE
nghttp2_1.8.0.orig.tar.gz2 no longer available 

### ISSUE THREAD

**Issue by jxy** [NixOS/nixpkgs#14760]
## Issue description

There is no such file, `nghttp2_1.8.0.orig.tar.gz2`, under `http://http.debian.net/debian/pool/main/n/nghttp2/`

### Steps to reproduce

Try to install or fetch the source code of nghttp2

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, …)
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre80183.551296a"

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/commit/b4d3a7f62b43907fc7aecd7fa31fe5edbf29e02e
