### ISSUE TITLE
Requesting SwapSpace

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#147800]
**Project description**
A service that dynamically allocates and deallocates Swap Partitions based on need at a given moment. 

**Metadata**

* homepage URL: https://github.com/Tookmund/Swapspace
* source URL: https://github.com/Tookmund/Swapspace
* license: GPL 2
* platforms: Linux/NixOS

**Comment by Luflosi** [comment]
The program itself is already in Nixpkgs and a NixOS module is being worked on in https://github.com/NixOS/nixpkgs/pull/88093, although progress seems to have stalled on the latter.

**Comment by tomodachi94** [comment]
With https://github.com/NixOS/nixpkgs/pull/348588 adding the module, I think this can finally be closed 🥳
