### ISSUE TITLE
Remounting ZFS read-only returns exit status 128

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14783]
`mount -o ro,remount /nix/store/`
returns
`filesystem 'zpool/root/nixos' is already mounted` with exit status 128. 

16.03.581.e409886 (Emu)
"16.03.581.e409886"

Expected result: 
No output on stderr or stdout, `/nix/stor`e mounted as `ro` (in `mount` output) and an exit status of 0.

**Comment by wmertens** [comment]
What is your output of `mount`? Are there any interesting kernel messages?

**Comment by 0xABAB** [comment]
`mount` gave the same output as before the remount command. I didn't see any interesting kernel messages.

**Comment by wmertens** [comment]
Strange - I think this is a zfs issue though. Can you dig through https://github.com/zfsonlinux/zfs/search?q=remount&type=Issues&utf8=%E2%9C%93 to see if anything matches?

**Comment by Mic92** [comment]
I cannot reproduce this issue. On my system `/nix/store` is a bind mount though.
