### ISSUE TITLE
Bad doc output

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#14782]
I've noticed that many packages do not have their separate subdirectory in the doc output.
For example:
```
nix-build -A pcre.doc
ls result-doc/share/doc
```

Files are in there directly, instead it should have been `result-doc/share/doc/pcre`, otherwise buildEnv of doc outputs would be a mess.

This is also the reason why the printing test is failing, it doesn't find the files where they are expected to be.

cc @vcunat

**Comment by vcunat** [comment]
Ah, unexpected meaning of autotools `--docdir` option. Thank you! I should've noticed long ago; `./configure --help` even gives examples.

**Comment by vcunat** [comment]
I would solve this by e35a5fc. Any comments? It seems to work well &ndash; I checked outputs of xz, gettext and mpfr so far.

Note that after merging closure-size, this problem happens whenever you define `outputs`, even without splitting docs, except if you define `setOutputFlags = false;`.

**Comment by lethalman** [comment]
Looks good :)

**Comment by vcunat** [comment]
Hmm, I'll have to change it a bit. Further testing revealed that the reordering of `preConfigure` caused problems in packages that contain `cd some/other/path` within it, and that happens relatively commonly in nixpkgs.

**Comment by cleverca22** [comment]
looks like at least a problem with both cups and groff, the cups image is in the $out output, but its searching dev
and the groff output is in $doc but lacks share/doc/groff/ sub-dir

**Comment by lethalman** [comment]
I made the doc output of cups in `$out` on purpose, because the webroot is in doc.

**Comment by vcunat** [comment]
I staged the generic improvement and tested it for mass breakage, but some individual issues may remain, e.g. the cups tests.
