### ISSUE TITLE
Consider striping and omitting DWARF in Go packages

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nixpkgs#14791]
When building go packages, we might want to make it an option to pass `-ldflags="-s -w"`.

Per [the Go docs](https://golang.org/cmd/link/):

```
-s
    Omit the symbol table and debug information.
-w
    Omit the DWARF symbol table.
```

See the following for more details:
- https://golang.org/cmd/link/
- https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
- https://news.ycombinator.com/item?id=11515612

**Comment by cstrahan** [comment]
Regarding `-w`, that *should* just strip the debugging symbols, leaving enough for readable panic info. Also, we shouldn't forget to do this when building `go` itself (e.g. `go build -ldflags="-s -w" cmd/go`), which supposedly can drop the size down to ~9.0MB from ~12.5MB.

**Comment by Mathnerd314** [comment]
The normal strip utility is already run in ``fixupPhase``, so they're partially stripped already, but maybe the Go tools can strip it more. It would be nice to have numbers on some Go packages.

**Comment by Profpatsch** [comment]
triage: fixed?
