### ISSUE TITLE
Updating nix-channel with sudo fails

### ISSUE THREAD

**Issue by Semptic** [NixOS/nixpkgs#14796]
## Issue description
Running `sudo nix-channel --update` fails on osx 10.11.3 with `unable to check ‘https://nixos.org/channels/nixpkgs-unstable’`. Running without `sudo` doesn't have this issue and updates properly.
Maybe this is expected behaviour, but then the message is totally misleading for an nix beginner.

### Steps to reproduce
Install nix with `curl https://nixos.org/nix/install | sh` and run `sudo nix-channel --update`

## Technical details

* System: osx 10.11.3  
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre80183.551296a

**Comment by ericsagnes** [comment]
This might be due to the fact that `sudo` clears the environment, does that work better with `sudo -E`?

**Comment by Semptic** [comment]
Thx, but this leads to following warning:

```
# sudo -E nix-channel --update
downloading Nix expressions from ‘https://nixos.org/releases/nixpkgs/nixpkgs-16.09pre80183.551296a//nixexprs.tar.xz’...
warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
downloading ‘https://nixos.org/releases/nixpkgs/nixpkgs-16.09pre80183.551296a//nixexprs.tar.xz’... [6160/7141 KiB, 1223.9 KiB/s]
unpacking channels...
warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
```
Creating the group (with `sudo dscl . -create /Groups/nixbld` and rebooting) didn't help.

Will this cause problems?

**Comment by joachifm** [comment]
For single-user installations of Nix, I don't think it makes any difference.

Looks like the original issue was resolved, so I'm going to close this.
