### ISSUE TITLE
Package: lifeograph

### ISSUE THREAD

**Issue by merspieler** [NixOS/nixpkgs#147943]
Based on recommendation in the matrix room I post my currently working nix file for lifeograph here

```
{ fetchgit
, pkgconfig
, stdenv
, meson
, ninja
, lib
, libgcrypt
, enchant
, gtkmm3
, libchamplain
}:

stdenv.mkDerivation rec {
  pname = "lifeograph";
  version = "2.0.2";

  src = fetchgit {
    url = https://git.launchpad.net/lifeograph;
    rev = "d635bbb30011c0d33c33643e6fa5c006f98ed7d6";
    sha256 = "0j9wn5bj7cbfnmyyx7ikx961sksv50agnb53prymldbsq43rfgnq";
  };

  nativeBuildInputs = [
    meson
    ninja
    pkgconfig
  ];
  buildInputs = [
    libgcrypt
    enchant
    gtkmm3
    libchamplain
  ];

  meta = with lib; {
    homepage = http://lifeograph.sourceforge.net/wiki/Main_Page;
    description = "Lifeograph is an off-line and private journal and note taking application";
    license = licenses.gpl3Only;
    maintainers = with maintainers; [];
  };
}
```

**Comment by WolfangAukang** [comment]
Just to be sure, is this working or are there any errors with it?

**Comment by merspieler** [comment]
Points 1 through 3 I've changed above.

> Are you definitely sure it builds for all platforms?
idk... I've just copy pasted another package and made it working... I'm a newbie so I've got no clue about some of that stuff...

> You might need to edit the generated $out/share/applications/net.sourceforge.Lifeograph.desktop file, specially on the Exec parts where you need to point to the application path ($out/bin)

How would I do that?

> When you get that done, then follow the contributing instructions on the Nixpkgs manual, throw the PR and someone will check it for you.

Well... I was recommended to just open an issue instead of a PR... my main concern is the maintainer part... I don't want to maintain this... I just wanted to make it available to others in case someone looks for it.

**Comment by WolfangAukang** [comment]
Ready, it has been merged. Thank you!
