### ISSUE TITLE
Gitlab fails at start when opening symlink

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixpkgs#14795]
## Issue description
Gitlab fails to start with error:
``/nix/store/...ruby-2.2.3-p0/lib/ruby/2.2.0/rubygems/stub_specification.rb:75:in `initialize`: No such file or directory @ rb_sysopen - /nix/store/...gitlab/lib/ruby/gems/2.2.3/specifications/redis-rails-4.0.0.gemspec (Errno::ENOENT)``

Every time I restart the machine a different gemspec file is mentioned but I believe this is at random just the first gemspec it finds and attempts to load. The path that it says is missing does infact exist, however, it is a _symlink_ (because nix) which I suspect the `rb_sysopen` command might be taking issue with.

### Steps to reproduce
Use nixos options to enable the gitlab service:

`services.gitlab.enable = true;`

## Technical details

* System: NixOS: 16.03.560.4b66766
* Nix version: 1.11.2
* Nixpkgs version: 16.03.560.4b66766

**Comment by domenkozar** [comment]
cc @globin @fpletz
