### ISSUE TITLE
Package Request: Kavita, a self-hosted digital library

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#147923]
**Project description**

Kavita is a fast, self-hosted digital library which supports a vast array of file formats, including ebook, comic, and manga formats.

**Metadata**

* homepage URL: https://www.kavitareader.com/#downloads-v1-linux
* source URL: https://github.com/Kareadita/Kavita
* license: GPL3
* platforms: unix, linux, darwin

**Comment by pbsds** [comment]
Should be easier now that `pkgs.buildNpmPackage` exists

**Comment by Misterio77** [comment]
Relevant PRs: https://github.com/NixOS/nixpkgs/pull/227890 and https://github.com/NixOS/nixpkgs/issues/147923

**Comment by dit7ya** [comment]
I think this can be closed now as #228002 has been merged.
