### ISSUE TITLE
Package the alfaview client

### ISSUE THREAD

**Issue by neumantm** [NixOS/nixpkgs#147916]
**Project description**
alfaview is a video conferencing tool developed and hosted in Germany.
To use their service, a client is needed.

The project is proprietary, but they provide a .deb as download.

**Metadata**

* homepage URL: https://alfaview.com/en/
* source URL: -
* license: proprietary
* platforms: linux

**Comment by WolfangAukang** [comment]
I was able to build it, but it would be nice if someone could test it to ensure what's built works as intended.

**Comment by WolfangAukang** [comment]
Merged
