### ISSUE TITLE
github-runner fails to restart after reboot

### ISSUE THREAD

**Issue by yayayayaka** [NixOS/nixpkgs#148024]
### Describe the bug
After rebooting the machine, the `github-runner.service` systemd service fails to start due to an "invalid user: ‘github-runner’"

### Steps To Reproduce
1. Reboot

### Expected behavior
The `github-runner.service` systemd service enters the `active (running)` state

### Screenshots
`journalctl -u github-runner.service`:  
```
-- Boot 43ff3711b71649398efdeeb0ecf55dfa --
Nov 29 20:18:21 build-worker-01 systemd[1]: Starting GitHub Actions runner...
Nov 29 20:18:21 build-worker-01 z9k737rfg50ng5618a08kx10jc5np0f5-github-runner-own-config-tokens.sh[1697]: chown: invalid user: ‘github-runner’
Nov 29 20:18:21 build-worker-01 systemd[1]: github-runner.service: Control process exited, code=exited, status=1/FAILURE
Nov 29 20:18:21 build-worker-01 systemd[1]: github-runner.service: Failed with result 'exit-code'.
Nov 29 20:18:21 build-worker-01 systemd[1]: Failed to start GitHub Actions runner.
```

### Additional context
It does not happen after every reboot. I have not found the circumstances that make the systemd service fail.

One workaround to bring the service back to the running state is to manually restart `github-runner.service`.

### Notify maintainers
@veehaitch @newam

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/etc/src/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: github-runner
# a list of nixos modules affected by the problem
module: github-runner
```

**Comment by veehaitch** [comment]
Thanks for raising this. I guess I ran into this as well already but didn't give it too much thought. Now, after reading systemd.service(5) again, I believe we should prefix `ExecStartPre` with `!` instead of `+`:

> Similar to the "+" character discussed above this permits invoking command lines with elevated privileges. However, unlike "+" the "!" character exclusively alters the effect of User=, Group= and SupplementaryGroups=, i.e. only the stanzas that affect user and group credentials. Note that this setting may be combined with DynamicUser=, in which case a dynamic user/group pair is allocated before the command is invoked, but credential changing is left to the executed process itself.

I'm not sure that's really the issue but it seems like the user/group (`DynamicUser=`) is not always set up when systemd runs `ExecStartPre=`. It appears `+` would make sure they exist. 

I'm going to open a PR. Regardless of fixing this issue (which I hope it does), it makes sense to use `!` instead of `+`.

**Comment by yayayayaka** [comment]
Wow, thanks for the quick response! I will check out your PR soon.
