### ISSUE TITLE
melpa-stable-packages is 2 months old

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#14802]
That's a problem because packages in Emacs move fast. I can't currently update this file because of https://github.com/ttuegel/emacs2nix/pull/13.

**Comment by gridaphobe** [comment]
It would be nice to have an automated, periodic update for the melpa and melpa-stable sets.

**Comment by ttuegel** [comment]
Just updated.

> It would be nice to have an automated, periodic update for the melpa and melpa-stable sets.

There are instructions at the top of each package set file for how to generate the package list. I'm sure you could set up some bot which would open PRs periodically.
