### ISSUE TITLE
User home directory permissions are hardcoded to be 0700

### ISSUE THREAD

**Issue by aolasz** [NixOS/nixpkgs#148013]
The user's home directory permissions (mode 0700) are hardcoded in update-users-groups.pl:
https://github.com/NixOS/nixpkgs/blob/2553aee74fed8c2205a4aeb3ffd206ca14ede60f/nixos/modules/config/update-users-groups.pl#L213

Suggestion:  
Please add an extra option e.g.  
`users.users.<name>.homePermissions`
which might propagate to update-users-groups.pl via the json file created by
https://github.com/NixOS/nixpkgs/blob/2553aee74fed8c2205a4aeb3ffd206ca14ede60f/nixos/modules/config/users-groups.nix#L412

**Comment by runeksvendsen** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/129885

**Comment by SuperSamus** [comment]
Doesn't [users.users.\<name\>.homeMode](https://search.nixos.org/options?show=users.users.%3Cname%3E.homeMode) do that?

**Comment by aanderse** [comment]
@SuperSamus yes, this issue was created before that option existed. We can close this now. Thanks.
