### ISSUE TITLE
tightvnc fails to build on OS X

### ISSUE THREAD

**Issue by alxempirical** [NixOS/nixpkgs#14809]
## Issue description

Installing `tightvnc` fails with `ld: library not found for -lXext` when linking `vncconnect`.  I do have `libXext`, might just be a matter of pointing the build system at it:

```
# find / -name libXext\*
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/nix/store/cpjgfhls1sk0pqv2b0n89whazf62hm5r-libXext-1.3.3/lib/libXext.6.dylib
/nix/store/cpjgfhls1sk0pqv2b0n89whazf62hm5r-libXext-1.3.3/lib/libXext.dylib
/nix/store/cpjgfhls1sk0pqv2b0n89whazf62hm5r-libXext-1.3.3/lib/libXext.la
/nix/store/cpjgfhls1sk0pqv2b0n89whazf62hm5r-libXext-1.3.3/share/doc/libXext
/opt/X11/lib/libXext.6.dylib
/opt/X11/lib/libXext.dylib
```
### Steps to reproduce

`nix-env -i tightvnc` [produces this output.](https://github.com/NixOS/nixpkgs/files/224906/tightvnc-fail.txt)  This is after several attempts at that command.  Please let me know how to roll back if it would be helpful.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

OS X 10.11.4 (15E65)
- Nix version: (run `nix-env --version`)

```
alx$ nix-env --version
nix-env (Nix) 1.11.2
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
alx$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre80183.551296a"
```

**Comment by Profpatsch** [comment]
triage: still not building?
