### ISSUE TITLE
Alacritty does not start when using nvidia Wayland

### ISSUE THREAD

**Issue by cideM** [NixOS/nixpkgs#148000]
### Describe the bug

```shell
❯ $ alacritty
  Created log file at "/tmp/Alacritty-8555.log"
  [2021-11-30 11:02:23.470712958] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:

  Error creating GL context; eglCreateWindowSurface failed
```

### Steps To Reproduce

Here's my configuration:

```nix
{
  programs.xwayland.enable = true;     
  services.xserver = {                 
    enable = true;                     
    videoDrivers = [ "nvidia" ];                                               
                                                                               
    displayManager = {                                                         
      gdm = {                                                                  
        enable = true;                 
        nvidiaWayland = true;          
      };                                                                       
    };                
                                                                               
    desktopManager = {                                                         
      gnome = {                                                                
        enable = true;                                                         
      };                                                                       
    };                                                                         
  };
} 
```

### Additional context

For what it's worth, some related files:

```shell
$ tree /etc/egl/
/etc/egl/
└── egl_external_platform.d -> /etc/static/egl/egl_external_platform.d

1 directory, 0 files
$ tree /etc/egl/egl_external_platform.d/
/etc/egl/egl_external_platform.d/
├── 10_nvidia_wayland.json
└── 15_nvidia_gbm.json

0 directories, 2 files
$ cat /etc/egl/egl_external_platform.d/1*
{
    "file_format_version" : "1.0.0",
    "ICD" : {
        "library_path" : "/nix/store/7y1q853c1dm0fhiqa3hqr7w050s4n6zw-nvidia-x11-495.44-5.15.4/lib/libnvidia-egl-wayland.so.1"
    }
}
{
        "file_format_version" : "1.0.0",
        "ICD" : {
                "library_path" : "/nix/store/7y1q853c1dm0fhiqa3hqr7w050s4n6zw-nvidia-x11-495.44-5.15.4/lib/libnvidia-egl-gbm.so.1"
        }
}
```

### Notify maintainers
@colemickens I'm pinging you since you worked on https://github.com/NixOS/nixpkgs/pull/139354 which seems quite relevant

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211126_55275fc`
 - channels(tifa): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**I'm using Flakes** to configure my system and my system is using `nixpkgs-unstable` at `f366af7a1b3891d9370091ab03150d3a6ee138fa` which includes the most recent EGL related fixes.

Alacritty is at version `0.9.0`.

There are open issues about this in the Alacritty repository https://github.com/alacritty/alacritty/issues/1269 which leads to https://github.com/rust-windowing/glutin/issues/1188 and it seems that https://github.com/NVIDIA/egl-wayland/commit/2eb4628d64a8297fb4c08aa796fdf33ff54a670f is a fix for this (?) but I'm lost as to whether how many projects need to be updated to incorporate this.

**Comment by colemickens** [comment]
Quick thoughts:
- the glutin issue sorta predates the GBM nvidia driver so I'm not sure if or how much its relevant, plus, we have the commit in our `egl-wayland`, so that also shouldn't be an issue.
- something(s) are still not quite right. `eglinfo` shows X11 (Xwayland) not working (maybe this is Sway though, idk)

**Comment by LunNova** [comment]
Might be something to do with `libnvidia-vulkan-producer.so`, that was also needed here: https://github.com/NVIDIA/egl-wayland/issues/34#issuecomment-953176437

**Comment by LunNova** [comment]
I didn't see anything trying to read a file with that name in strace so it probably isn't that.
