### ISSUE TITLE
Pantheon workspace switching animation looks really bad

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#148185]
### Describe the bug
After updating to 21.11, the animation for directly switching between workspaces looks really bad. (I hope this isn't normal behaviour with Pantheon 6?)

### Steps To Reproduce
1. Install NixOS 21.05 w/ Pantheon
2. Test workspace switching
3. Install NixOS 21.11 w/ Pantheon
4. Compare workspace switching

### Expected behavior
Smooth workspace switching like on 21.05.

### Screenshots
Before:
https://cdn.discordapp.com/attachments/869683976133050380/915691427026051072/SimpleScreenRecorder-2021-12-01_20.18.14.webm

After:
https://cdn.discordapp.com/attachments/869683976133050380/915691497913978910/SimpleScreenRecorder-2021-12-01_19.53.22.webm

### Notify maintainers
@NixOS/pantheon 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
↪ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(bt1cn): `"unstable-21.11pre333218.263ef4cc414"`
 - channels(root): `"nixos-21.11.333823.96b4157790f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by davidak** [comment]
I can reproduce this on NixOS 21.11: https://youtu.be/6lKrlHE08Wk

@OPNA2608 you mean the grey space between the workspaces, right?

![vlcsnap-2021-12-02-00h32m16s334](https://user-images.githubusercontent.com/91113/144331049-f01a5776-7b6b-4b74-8ad6-510de13f8296.png)

@bobby285271 can you reproduce this too?

I think the best way forward would be an upstream  issue, since we can't do much about this (i think).

**Comment by OPNA2608** [comment]
Sorry for not being more specific, I was in a hurry to get some assignments done until midnight. I meant the way the workspace doesn't finish smoothly sliding in, instead opting to jump into place once it reaches the last sixth of the screen. This jumpiness is also present in your recording.

This looks very distracting coming from 21.05 where it was fully smooth. And it looks even more wrong because going to the workspace overview first (<kbd>Super</kbd> + <kbd>↓</kbd>) and then switching workspaces shows a completely smooth animation as expected. That's why I reported it here, because I assumed they wouldn't have shipped that in their own distro considering all the other animations *are* smooth.

**Comment by davidak** [comment]
Yes, that's quiet a difference.

**Comment by bobby285271** [comment]
FYI there is https://github.com/elementary/gala/issues/1325, not sure if that is the problem described here.

I made a patch to downgrade mutter and g-s-d to 3.36 two months ago ([here](https://gist.github.com/bobby285271/d5f5a4d50cbb9bd35e16157756a975b9)) and I will see if things work fine later.

Maybe it is not a good idea to downgrade default mutter and g-s-d for Pantheon especially for stable channel, but after issues like https://github.com/NixOS/nixpkgs/issues/139404 and https://github.com/elementary/gala/issues/1312, I guess it will be nice to introduce some options to specify mutter and g-s-d package, so I can re-add mutter 3.36 to nixpkgs while keeping 3.38 as default and do backports.

When doing Pantheon 7 upgrade, I guess I will be more careful with choosing mutter versions and just use what elementary is using :-(

**Comment by yellowgh0st** [comment]
I doubt they will fix it anytime soon. Focal might be stuck with mutter3.36.

**Comment by yellowgh0st** [comment]
3.36.4 should be pretty same story as this https://github.com/NixOS/nixpkgs/commit/634488aa608c863fa54eaaa232024856bc3463dd#diff-4df4e4d427576227ff641c821bc6fe018c675f0c7d3f7a26a72f36eec82153cb
so just replacing it would fix
gonna give it try

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/174220
