### ISSUE TITLE
Regression on google-compute-engine 20190124 => 20200113.0: all binaries are lost

### ISSUE THREAD

**Issue by PaulGrandperrin** [NixOS/nixpkgs#148127]
google-compute-engine-20190124 provided binaries:
```shell
$ ls /nix/store/6g2pd9ip0c1vczva134xqa5axc2kqlv7-python3.8-google-compute-engine-20190124/bin
google_accounts_daemon  google_clock_skew_daemon  google_instance_setup  google_metadata_script_runner  google_network_daemon  google_optimize_local_ssd  google_set_multiqueue
```

google-compute-engine-20200113.0 doesn't:
```sh

$ ls /nix/store/n1a9avrpyi0szq991aw4jfxrpjllnyzp-python3.8-google-compute-engine-20200113.0/bin
ls: cannot access '/nix/store/n1a9avrpyi0szq991aw4jfxrpjllnyzp-python3.8-google-compute-engine-20200113.0/bin': No such file or directory
```

FYI, it also breaks https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/google-compute-config.nix which assumes these binaries to be present.

@cpcloud @zimbatm @SuperSandro2000

**Comment by cpcloud** [comment]
@PaulGrandperrin Can you show the error(s) you're getting? I just created a NixOS VM on GCP using Pulumi, based on NixOS/nixpkgs@https://github.com/NixOS/nixpkgs/commit/0943a5c5a089761ea06ecf95e56bab8ce84e35f3 and had no problem SSH-ing into it through an IAP tunnel and poking around.

**Comment by PaulGrandperrin** [comment]
@cpcloud I'm answering from my phone.
There shouldn't be any errors while deploying the VM, however, the GCE related services will all fail, because of the missing executables, like `google_clock_skew_daemon` at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/google-compute-config.nix#L126

**Comment by PaulGrandperrin** [comment]
I can't copy more from my phone screen but you get the idea:

```
# systemctl status google-clock-skew-daemon.service|cat
× google-clock-skew-daemon.service - Google Compute Engine Clock Skew Daemon
     Loaded: loaded (/etc/systemd/system/google-clock-skew-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-12-01 11:48:34 CET; 3h 52min ago
    Process: 1233 ExecStart=/nix/store/7hhfk9vf2wmn6fk9xpmakfvldrkshbaw-python3.9-google-compute-engine-20200113.0/bin/google_clock_skew_daemon (code=exited, status=203/EXEC)
   Main PID: 1233 (code=exited, status=203/EXEC)
         IP: 0B in, 0B out
        CPU: 720us

Dec 01 11:48:34 nixos-gcp systemd[1]: Started Google Compute Engine Clock Skew Daemon.
Dec 01 11:48:34 nixos-gcp systemd[1233]: google-clock-skew-daemon.service: Failed to locate executable /nix/store/7hhfk9vf2wmn6fk9xpmakfvldrkshbaw-python3.9-google-compute-engine-20200113.0/bin/google_clock_skew_daemon: No such file or directory
Dec 01 11:48:34 nixos-gcp systemd[1233]: google-clock-skew-daemon.service: Failed at step EXEC spawning /nix/store/7hhfk9vf2wmn6fk9xpmakfvldrkshbaw-python3.9-google-compute-engine-20200113.0/bin/google_clock_skew_daemon: No such file or directory
Dec 01 11:48:34 nixos-gcp systemd[1]: google-clock-skew-daemon.service: Main process exited, code=exited, status=203/EXEC
Dec 01 11:48:34 nixos-gcp systemd[1]: google-clock-skew-daemon.service: Failed with result 'exit-code'.
```

And `/nix/store/7hhfk9vf2wmn6fk9xpmakfvldrkshbaw-python3.9-google-compute-engine-20200113.0` is indeed installed, but is missing the `bin` directory.

**Comment by PaulGrandperrin** [comment]
Here are all the failing services:
```
● google-clock-skew-daemon.service                                             ● google-instance-setup.service                                                ● google-network-daemon.service                                                                                  ● google-startup-scripts.service
```

I don't know how useful are the other missing binaries but anyway it looks like there's just an issue in the packaging process

**Comment by PaulGrandperrin** [comment]
@cpcloud sorry, that's not all the GCE related services that are failing, as you have seen the ssh key fetching service is still working 🙂

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/144761

> We were relying on some google-provided python script to perform various actions on the GCE guests. These scripts have been decommissioned in favor of a Golang daemon: GoogleCloudPlatform/guest-agent. The #131761 bump broke the google-compute-config NixOS module: the Python script are not longer present in the $out/bin directory (more info about that in the upstream commit), hence breaking the NixOS module that was relying on those scripts.

**Comment by PaulGrandperrin** [comment]
@Artturin oh I should have seen that before!

Thanks!
