### ISSUE TITLE
cross-compilation broken since using multiple outputs

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#14817]
Handling of build inputs and their propagation doesn't work well. The typical construction is that `.dev` is put into build inputs and `.out` is propagated from it; example: zlib. During cross-build this propagation doesn't work, so e.g. libpng can't see zlib.out and thus can't link. This did work just before merging closure-size (well, there all relevant zlib stuff was in a single output).

I'll try to fix this during this week.

**Comment by vcunat** [comment]
I suspect it's the handling of `propagatedBuildOutputs` that's the problem.

**Comment by vcunat** [comment]
Yes, most likely. The outputs should be propagated as non-native when cross-building. I'll test my patch properly now; it will take hours of building. Then I plan to stage it together with other stuff like https://github.com/NixOS/nixpkgs/issues/14782.

**Comment by dezgeg** [comment]
BTW I've also wondered how `pkg.dev` and `foo.crossDrv` interact.. E.g. do `foo.dev.crossDrv` and `foo.crossDrv.dev` both work and give the same result.

**Comment by vcunat** [comment]
I'm convinced `foo.crossDrv.outName` works fine, but the other doesn't. (I don't have a use case for the other way; it's possible the `force*` functions still do something on them.)

**Comment by vcunat** [comment]
Staged a fix. The regressions are gone now, at least all those I experienced on my set of several linux -> mingw builds.

**Comment by dezgeg** [comment]
If `buildInputs = [ foo.bin ]`; then the `mkDerivation` will internally try to do `foo.bin.crossDrv`, doesn't it? Of course `bin` isn't a terribly good example, but still...

**Comment by vcunat** [comment]
Yes, not a very common example, I think, but certainly a plausible use case. It might warrant some general thoughts on combining multiple adapters that add attributes. The set of them will likely only grow, so we're bound to hit problems at some point if we don't find a nice general solution.
