### ISSUE TITLE
llvm-config is unusable with static libraries and cross compilation

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#148117]
### Describe the bug
When cross-compiling LLVM, the produced llvm-config-native breaks when attempting to use it for the static libraries. The error messages are:

```
llvm-config: error: missing: /nix/store/bn4y633qrdc6972q6bdalvbawx8mv40p-llvm-aarch64-unknown-linux-gnu-12.0.1-dev/lib64/libLLVMDemangle.a
llvm-config: error: missing: /nix/store/bn4y633qrdc6972q6bdalvbawx8mv40p-llvm-aarch64-unknown-linux-gnu-12.0.1-dev/lib64/libLLVMSupport.a
...
```

### Steps To Reproduce
1. ``nix-build -A pkgsCross.aarch64-multiplatform.llvm_12.dev``
2. ``./result-dev/bin/llvm-config-native --link-static --libs``

Tested on current nixpkgs master (43ed12450ef5f6d6388ad5164a9f874a5e3b2f62)

### Expected behavior
Paths to the correct LLVM libraries are printed.

**Comment by sbourdeauducq** [comment]
Cc @lovek323 @dtzWill @primeos @7c6f434c

**Comment by r-burns** [comment]
I think the issue is in one of our downstream patches:

https://github.com/NixOS/nixpkgs/blob/971b383a28f4baee8ea3931af4840fa221929fd6/pkgs/development/compilers/llvm/12/llvm/outputs.patch#L20-L21

We should probably be overriding the ActiveLibDir unconditionally, without regard for WantShared. (I think it was originally done this way due to discussion in https://github.com/NixOS/nixpkgs/issues/18840 regarding keeping the static libraries in a separate output. Since static+shared libraries are all in the `lib` output now, it seems correct to do this unconditionally.)

**Comment by sbourdeauducq** [comment]
Thanks - that seems to work!

**Comment by sternenseemann** [comment]
Note the way this has been fixed changed in <https://github.com/NixOS/nixpkgs/pull/152944> (hopefully for the better), but if there are any new regression it may be due to this PR.

**Comment by maxbrunet** [comment]
It seems to be broken again:

```console
$ llvm-config --link-static --libnames
llvm-config: error: missing: /nix/store/9v0lw5dic6lclv5b2gzvzq2zwqcb1qf8-llvm-14.0.1-lib/lib/libLLVMDemangle.a
llvm-config: error: missing: /nix/store/9v0lw5dic6lclv5b2gzvzq2zwqcb1qf8-llvm-14.0.1-lib/lib/libLLVMSupport.a
...
```

Because static libraries have been moved to the `dev` output (#162607):

```console
$ ls -1 /nix/store/pnbwn67snfkmd5p0sf5rvl9a54wraqs8-llvm-14.0.1-dev/lib/{libLLVMDemangle.a,libLLVMSupport.a}
/nix/store/pnbwn67snfkmd5p0sf5rvl9a54wraqs8-llvm-14.0.1-dev/lib/libLLVMDemangle.a
/nix/store/pnbwn67snfkmd5p0sf5rvl9a54wraqs8-llvm-14.0.1-dev/lib/libLLVMSupport.a
```

I am new to Nix and not very familiar with LLVM, are there any workarounds? like an environment variable or an override to point `llvm-config` to the correct directory?

**Comment by sternenseemann** [comment]
Not in this case, we'll need to adapt `llvm-config.patch` or revert the offending PR. We probably should also be thinking about adding some tests guarding that this keeps working…
