### ISSUE TITLE
linux-firmware is really big

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#148197]
## Issue description

firmwareLinuxNonfree, aka firmware-linux-nonfree, aka https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git is giant. A look today revealed it to be over 700M. This is getting to a size that some machine's firmware can't fit it in to the limited available memory when netbooting.

For reference, Alpine splits the firmware in to several packages: https://pkgs.alpinelinux.org/packages?name=linux-firmware-*&branch=edge&arch=aarch64

```
# Put /lib/firmware/* folders in subpackages
_folders="3com acenic adaptec advansys amd amd-ucode amdgpu ar3k ath10k ath11k
	ath6k ath9k_htc atmel atusb av7110 bnx2 bnx2x brcm cadence cavium cis cpia2
	cxgb3 cxgb4 cypress dabusb dpaa2 dsp56k e100 edgeport emi26 emi62 ene-ub6250
	ess go7007 i915 imx inside-secure intel isci kaweth keyspan keyspan_pda korg
	libertas liquidio matrox mediatek mellanox meson microchip moxa mrvl mwl8k
	mwlwifi myricom netronome nvidia ositech qca qcom qed qlogic r128 radeon
	rockchip rsi rtl8192e rtl_bt rtl_nic rtlwifi rtw88 rtw89 sb16 silabs slicoss
	sun sxg tehuti ti ti-connectivity ti-keystone tigon ttusb-budget ueagle-atm
	vicam vxge yam yamaha"
```

I propose making individual packages for each subdirectory to allow users to opt in to specific subsets of the firmware as needed.

This will likely require a much more advanced configuration generator.

**Comment by samueldr** [comment]
With a proper symlink "forest", we could already improve the situation in an opt-in fashion, with a "compatibility" package. The defaults stay the same, but if you need a reduced set, you can disable whatever adds this package to the firmware list, and add the reduced sets.

With *additional out of scope work*, it could even be possible to match patterns at build time and hand-pick firmwares out of the package for even more space savings.

**Comment by grahamc** [comment]
It strikes me this could be an ideal multi-output package, with an output per directory, and verify every directory got an output and error if not. Then have the `out` output have a symlink forest to each output. What do you think about that?

**Comment by samueldr** [comment]
¯\\\_(ツ)\_/¯

Sounds about right I guess. I frankly don't know enough about multi-output packages to gauge what issus there could be.

What happens when a new folder is added at the root of the package, and we don't list it as one of the outputs? (I guess we could `mv` folders to their outputs, and have a `leftover` dir... we might even decide of a threshold necessary to split the output if splitting is costly?)

**Comment by grahamc** [comment]
> new folder is added at the root of the package, and we don't list it as one of the outputs?

I think the best answer is we fail. If we make the rule more complicated than "every directory gets its own output" then the rule is subject to change and break users by surprise and in ugly ways.

**Comment by samueldr** [comment]
I wonder how often there's an new subdir...

And uh, what about files at the root? Looks like [they use `other` there](https://git.alpinelinux.org/aports/tree/main/linux-firmware/APKBUILD?id=87f6509d7aee77e5c5f5b2753690e039be33d359#n82).

**Comment by vcunat** [comment]
> It strikes me this could be an ideal multi-output package, [...]

Fixed-output and multi-output derivations can't be mixed.  At least as of nix a few years ago.  FOD really decreases the impact of the size here.  Still, I can imagine multiple FODs sharing the same `src`.

**Comment by samueldr** [comment]
> FOD really decreases the impact of the size here.

Impact for *downloads*, I suspect. But the impact for size at rest is still problematic.

Did I understand the problem right?

Are there any limitations in making discrete packages rather than a multiple-output derivations to be aware of?

**Comment by vcunat** [comment]
With FOD the impact on disk size doesn't depend on `nix.autoOptimiseStore = true;` (i.e. FOD helps with disk size in default settings)

**Comment by samueldr** [comment]
@vcunat impact on disk size is about this use case:

> A look today revealed it to be over 700M. This is getting to a size that some machine's firmware can't fit it in to the limited available memory when netbooting.

The closure itself, even though it's limited to the derivation itself due to cheesing the use of an FOD, is getting too big for some limited use cases.

**Comment by vcunat** [comment]
Yes, I meant FOD properties assuming the same set of files.  I believe they will remain useful even after splitting the files into some groups.

**Comment by TredwellGit** [comment]
https://archlinux.org/news/linux-firmware-202201190c6a7b3-2-requires-kernel-53-and-package-splitting/

**Comment by Artturin** [comment]
https://github.com/archlinux/svntogit-packages/commit/4bf18f5a2d83ed8ddddaab708012ff6344cdea10

```patch
diff --git a/pkgs/os-specific/linux/firmware/linux-firmware/default.nix b/pkgs/os-specific/linux/firmware/linux-firmware/default.nix
index 22dc930d293..149c4d796bb 100644
--- a/pkgs/os-specific/linux/firmware/linux-firmware/default.nix
+++ b/pkgs/os-specific/linux/firmware/linux-firmware/default.nix
@@ -1,4 +1,4 @@
-{ stdenvNoCC, fetchgit, lib }:
+{ stdenvNoCC, fetchgit, lib, fetchpatch }:
 
 stdenvNoCC.mkDerivation rec {
   pname = "linux-firmware";
@@ -10,14 +10,22 @@ stdenvNoCC.mkDerivation rec {
     sha256 = "sha256-U5XZHzriZaPlgiAcrZnAA7K8PKnIGy58Pi6JziVFTR8=";
   };
 
+  patches = [
+    (fetchpatch {
+      url = "https://raw.githubusercontent.com/archlinux/svntogit-packages/4bf18f5a2d83ed8ddddaab708012ff6344cdea10/trunk/0001-Add-support-for-compressing-firmware-in-copy-firmware.patch";
+      sha256 = "sha256-2SSWoo28Tocyfp+vW/nuSsj2Uhqwgemw7vdBifFYlDU=";
+    })
+  ];
   installFlags = [ "DESTDIR=$(out)" ];
 
+  installTargets = [ "installcompress" ];
+
   # Firmware blobs do not need fixing and should not be modified
   dontFixup = true;
 
   outputHashMode = "recursive";
   outputHashAlgo = "sha256";
-  outputHash = "sha256-CAYJssH36aKhzvl0q60HyxgDXeAluspfnLLmawmWIQw=";
+  outputHash = "sha256-G8D8B7Wm3BTuia9DjXKkpmvxXdIhz0JYvZK+nxD7iT8=";
 
   meta = with lib; {
     description = "Binary firmware collection packaged by kernel.org";
```

```bash
$ thesize $(chase result1) # before
410M	/nix/store/l4iayn81ffjlpqah1jbhim21jmqi42f5-linux-firmware-20220310
410M	total
$ thesize $(chase result) # after
319M	/nix/store/wwdrcz4w6wxl02kq7df5fqzv68nrjcba-linux-firmware-20220310
319M	total
```

**Comment by vcunat** [comment]
Anyway, we could support both.  It's fairly easy to introspect what kernel version you have in the NixOS config.

**Comment by samueldr** [comment]
Turns out I never did share my strategy here

  - https://github.com/samueldr/nixpkgs/tree/wip/discrete-linux-firmware

I don't remember what was left to check, probably the whole FOD thing.

**Comment by vcunat** [comment]
I'll assume we can mark this as solved by PR https://github.com/NixOS/nixpkgs/pull/172820
```
$ nix path-info -s $paths
/nix/store/2n8jvxffzl2nfz5ddj8d7lzdsv5fj6z8-linux-firmware-20220509       917908560
/nix/store/yjyakfm79gaxp6vaiix44q4md4n4s8w3-linux-firmware-20220509-xz    353962392
```

**Comment by vcunat** [comment]
At least for now.  I see that the size grew by roughly 10% since the last comments a month ago :-/

**Comment by elikoga** [comment]
I think this one should be re-opened, I just saw 1.3G linux-firmware just now

**Comment by elikoga** [comment]
I was encountering 
https://github.com/nix-community/raspberry-pi-nix/blob/4f6706677c4adeca591ada531fc4d7b7b68c0414/overlays/default.nix#L80-L83

**Comment by NikunjK8** [comment]
I think splitting package like Arch and Alpine does is still the best solution moving forward. Arch's [linux-firmware-intel](https://archlinux.org/packages/core/any/linux-firmware-intel/) is just about 100MB for example, still 5 times smaller than NixOS.

**Comment by ngandrass** [comment]
> I think splitting package like Arch and Alpine does is still the best solution moving forward. Arch's [linux-firmware-intel](https://archlinux.org/packages/core/any/linux-firmware-intel/) is just about 100MB for example, still 5 times smaller than NixOS.

That would be very useful indeed. We now require specific Intel firmware to be present for our newer systems but including `linux-firmware` blows up the final image from 0.9 GiB to 1.7 GiB. This is a significant increase for us since we do parallel netboot of up to 250 clients with these images.

**Comment by Skallwar** [comment]
I was wondering why my Raspberry Pi 5 image with almost nothing was around 3G, I found out that linux-firmware is around 800Mo. I'm quite
