### ISSUE TITLE
opensnitch-ui doesn't install .desktop file at the right place and can't be found in the desktop environment menu

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#148168]
### Describe the bug

opensnitch-ui program is not available from GNOME menu certainly because its .desktop is at the wrong place

### Steps To Reproduce

Install opensnitch-ui and look into /nix/store, the file full path is available in `/nix/store/p5hllrz4jr76vqx96cs6sy9a18bxscs3-opensnitch-ui-1.3.6/lib/python3.9/site-packages/usr/share/applications/opensnitch_ui.desktop`

It seems the `lib/python3.9/site-packages` part shouldn't be there.

### Expected behavior

Install opensnitch-ui and be able to find it in desktop environment menu

### Notify maintainers

@raboof 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.333840.6bfd8c700fe"`
 - channels(solene): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aanderse** [comment]
ping @onny in case 🤷‍♂️

**Comment by raboof** [comment]
(I'm not planning to look into this as I don't use Gnome, so anyone feel free to pick this up!)

**Comment by rapenne-s** [comment]
> (I'm not planning to look into this as I don't use Gnome, so anyone feel free to pick this up!)

I didn't try on other DE but I suppose it doesn't work either on xfce/MATE/plasma because the menus should work the same.

**Comment by rapenne-s** [comment]
I tested with XFCE and I confirm it doesn't appear either. I didn't want to meant it was GNOME specific at first but I only had tried on GNOME.

I changed the title to be more generic.

**Comment by rapenne-s** [comment]
I confirm it's solved
