### ISSUE TITLE
Support both latest version and LTS version of QGis

### ISSUE THREAD

**Issue by lsix** [NixOS/nixpkgs#148213]
This ticket is a followup on the discussion started in  #147262.

Currently, `nixpkgs` maintains a port of the Long Term Release (LTR) of QGis.  Updates to the LTR series only include bug fixes.  Alongside with the LTR releases, upstream also provides Latest Releases (LR) which provide new features (See [here](https://github.com/qgis/QGIS#versions-and-release-cycle) for details)

There is growing demand to support LR releases in `nixpkgs`.

The proposition is:

- Keep the current LTR version in `nixpkgs` and rename it `qgis-lts` in `all-packages.nix` (`qgis-unwrapped` gets renamed `qgis-lts-unwrapped`)
- Introduce a new derivation for QGis-LR named `qgis` (with `qgis-unwrapped`) .

One down-side of doing this is that it is possible that somewhere in the lifecycle of a `nixpkgs` release, QGis LR requires updates (incl in its dependency tree) that we would not want to force on a stable branch (which is only supposed to receive bug and security fixes). This means that the LR variant of QGis could be stuck at some point without bugfixes in release branch, while LTR still receives such fixes.

This point might be discussed further when a PR is created for this.

Note: Given the release schedule, `21.11` will continue to only have one version of QGis which is LTR, while master and subsequent releases will have both versions.

cc @erictapen, @willcohen

**Project description**
 QGis is a a Free and Open Source Geographic Information System.

**Metadata**

* homepage URL: https://qgis.org/en/site/
* source URL: https://github.com/qgis/QGIS
* license: gpl2+ 
* platforms: linux, darwin

**Comment by mpickering** [comment]
Yes please. 

QGIS 3.18 adds support for viewing point cloud data, that was released in February.

There are also two shortcomings with the QGIS as packaged that I know about.

1. grass is not enabled, which severally limits the processing algorithms you can use. I know I fixed this at some point so it's a shame that this support has regressed.
2. The 3D viewer doesn't work.

**Comment by mpickering** [comment]
I have fixed the grass issue and 3D issue locally, I will test the build tomorrow.

@lsix Are you preparing a patch which packages more recent versions of qgis? I am keen to get point cloud support.

**Comment by mpickering** [comment]
For QGIS >= 3.18 we need to set the `WITH_PDAL=TRUE` cmake variable.

See https://github.com/archlinux/svntogit-community/blob/packages/qgis/trunk/PKGBUILD#L48

**Comment by mpickering** [comment]
Another issue with the current QGIS package is that the `-DGRASS_PREFIX7` is set incorrectly.

```
-DGRASS_PREFIX7=${grass}/${grass.name}
```

This resolves to `<nix store path>-grass/grass` but the correct directory is `<nix store path>-grass/grass78`.

**Comment by mpickering** [comment]
@lsix I packaged qgis-3.22.1 and introduced the other fixes I described on this thread.

https://github.com/mpickering/nixpkgs/tree/wip/grass

**Comment by lsix** [comment]
Hi @mpickering 

Thanks for working on this! I started looking into having qgis-3.22.1 working, and did it only locally (actually, this was more an assessment of what should be done). This only include qtlocation support in pyqt and version bump in qgis, so your branch is far head!

I just glanced at your branch (I am unfortunately quite busy ATM), and here are the few remarks I would have:

- I fill that the wrapper should not have to handle grass. It should be enabled directly in the unwraped derivation, and obey the `withGrass` parameter.  The wrapper (as it is) is mainly used so users can have a QGis with any python dependency they want without recompiling all the c++ code.
- I am not sure we need to introduce `pyqt5_with_qtlocation` in pythonPackages.  It is possible to do a local override in the python derivation with something like:

```nix
{}:
let
  localPython3Packages = python3Packages.python.override {
    packageOverrides = self: super: {
        pyqt5 = super.pyqt5.override { withLocation = true; };
    }
  };
  pythonBuildInputs = with localPython3Packages; [ ... ];
in ... {

   passthru = {
    inherit pythonBuildInputs;
    python3Packages = localPython3Packages;
  };
  
} 
```

What do you think?

**Comment by mpickering** [comment]
I changed the wrapper to be applied in the unwrapped.nix script but didn't make the qtlocation change as I couldn't get that to work. The `pyqt_with_location` follows the pattern for the other optional arguments (which is why I did it in the first place).

**Comment by willcohen** [comment]
Closing with #156747
