### ISSUE TITLE
Binary Build of Julia 1.7: julia_17-bin

### ISSUE THREAD

**Issue by totoroot** [NixOS/nixpkgs#148339]
Julia 1.7 has been released recently as the new stable version.
I'd love to get this packaged on NixOS to make use of the new features listed in the [release notes](https://docs.julialang.org/en/v1.7/NEWS/).

**Metadata**

* homepage URL: https://docs.julialang.org/en/v1.7/
* source URL: https://julialang.org/downloads/#current_stable_release
* license: mit
* platforms: unix, linux, darwin

Documentation might also have to be updated:
https://nixos.wiki/wiki/Julia

Pinging @samuela, as they seem to have been involved in packaging the Julia binary packages in the past.

**Comment by totoroot** [comment]
Also I noticed that the following packages are outdated:
- julia-lts (1.0.4)
- julia-lts-bin (1.0.5)

The current LTS release is 1.5.4 and the souce can be found [here](https://julialang.org/downloads/#long_term_support_release).

Also I noticed that the 1.6 binary build can neither be found on https://search.nixos.org/packages, nor with `nix-env -qaP julia_16-bin` although I can install it just fine with `nix-env -iA nixpkgs.julia_16-bin`.

Can anyone shine some light on these issues?

**Comment by samuela** [comment]
Yes, getting 1.7 packaged would be dope. And AFAIU there's no good reason for the lts versions to be outdated. We just need to get around to fixing them. The big problem with Julia is that source builds don't really work for any of the recent releases. I've wasted many hours trying to fix them. I think the easiest way forward is to just do the binary `-bin` releases. Previously there was some contention about whether or not we should ever alias `julia-lts` to a `-bin` package. But there's no reason for the `-bin` packages to be outdated AFAIK.

The search.nixos.org issue has been brought up in the past (https://github.com/NixOS/nixpkgs/issues/116697#issuecomment-982094681) but I don't think there's a bug report for it yet. No idea why that's failing...

**Comment by samuela** [comment]
To get up to speed on previous Julia packaging efforts the best place to start is prob https://discourse.nixos.org/t/need-special-build-of-nightly-julia-version/14504/4?u=samuela.

**Comment by totoroot** [comment]
The binary build of Julia 1.7 was added with commit https://github.com/NixOS/nixpkgs/commit/1526faf075bdb52ece4fd5c259c54c66d1fcf003
LTS got updated with commit https://github.com/NixOS/nixpkgs/commit/36afb5849371a1898dc605b0905f4d351cee4b39
Julia 10 has been marked as deprecated with commit https://github.com/NixOS/nixpkgs/commit/6e176f712be1dd51c2c53528f4ee1b3efb6ac222

Many thanks to @ninjin

**Comment by ninjin** [comment]
On Sat 18 Dec 2021, Matthias Thym wrote:
> 
> The binary build of Julia 1.7 was added with commit https://github.com/NixOS/nixpkgs/commit/1526faf075bdb52ece4fd5c259c54c66d1fcf003
> LTS got updated with commit https://github.com/NixOS/nixpkgs/commit/36afb5849371a1898dc605b0905f4d351cee4b39
> Julia 10 has been marked as deprecated with commit https://github.com/NixOS/nixpkgs/commit/6e176f712be1dd51c2c53528f4ee1b3efb6ac222
> 
> Many thanks to @ninjin 

My pleasure, I hope you can all put the packages to good use. Do feel free to poke me whenever there is a Julia release as I at times may not have my eyes in the right spot to notice.
