### ISSUE TITLE
pcre library is built without UTF8 support

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#14830]
## Issue description
Pandoc shows this error:
pandoc: Text.Regex.PCRE.Light: Error in regex: this version of PCRE is compiled without UTF support

### Steps to reproduce
I tried to convert rmarkdown document to html using pandoc from Nix. This is a part of a standard process to build an R package. The R package I was trying to build is configured to use UTF-8 encoding. 

## Technical details
* System: Red Hat Enterprise Linux 6.6
* Nix version: 1.11.2
* Nixpkgs version: "16.09pre81563.cfdef68"

**Comment by peti** [comment]
Well, I suppose we could configure the C library `pcre` with `--enable-utf` to remedy that issue. Is anyone aware of a good reason why we shouldn't do this? Does this feature have any unwanted side effects for people who don't use it? I wonder because it seems curious that `libpcre` does not enabled UTF support by default.

**Comment by peti** [comment]
Just to provide a data point: ArchLinux does *not* enable that flag: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/pcre.

openSUSE, however, does: https://build.opensuse.org/package/view_file/Base:System/pcre/pcre.spec?expand=1.

Now what?

**Comment by peti** [comment]
@alexvorobiev, would you mind pasting the result of the command

    nix-shell -p pcre --run "pcretest -C"

on your machine?

When I run that here, I get

~~~
PCRE version 8.38 2015-11-23
Compiled with
  8-bit support
  UTF-8 support
  Unicode properties support
  Just-in-time compiler support: x86 64bit (little endian + unaligned)
  Newline sequence is LF
  \R matches all Unicode newlines
  Internal link size = 2
  POSIX malloc threshold = 10
  Parentheses nest limit = 250
  Default match limit = 10000000
  Default recursion depth limit = 10000000
  Match recursion uses stack
~~~~

..., so it looks like UTF support *is* enabled by default.

**Comment by alexvorobiev** [comment]
@peti My apologies, I am getting the same output but it turned out pandoc was picking up libpcre from the host system (RHEL) via `LD_LIBRARY_PATH` defined in the script I use to build R packages. I have only used statically linked pandoc before so I didn't expect it to be a problem. Unsetting the variable fixed the issue.
