### ISSUE TITLE
install-grub.pl fails during "nixos-rebuild boot" on 16.03

### ISSUE THREAD

**Issue by plutotulp** [NixOS/nixpkgs#14831]
## Issue description

When going from NixOS 15.09 to 16.03, the install-grub.pl script dies.
### Steps to reproduce

```
# nix-channel --add https://nixos.org/channels/nixos-16.03-small nixos
# nix-channel --update
# nixos-rebuild boot
```
## Technical details

The error looks like this:

```
# nixos-rebuild boot
building Nix...
building the system configuration...
updating GRUB 2 menu...
Failed to get blkid info for /boot on /dev/md127 at /nix/store/w345fzhsr2ckzhazmxr3lc906glnxqiy-install-grub.pl line 174.
warning: error(s) occurred while switching to the new configuration
```

The system in question is has six hard drives, all partitioned the same way:

```
# parted /dev/sda
GNU Parted 3.2
Using /dev/sda
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) print                                                            
Model: ATA WDC WD10EADS-00L (scsi)
Disk /dev/sda: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
 1      1049kB  10.5MB  9437kB               grub  bios_grub
 2      10.5MB  547MB   537MB   ext4         boot  raid
 3      547MB   1000GB  1000GB               zfs
```

All the second partitions are mirrored using MD RAID:

```
# cat /proc/mdstat 
Personalities : [raid1] 
md127 : active raid1 sdd2[3] sdf2[5] sde2[4] sda2[0] sdb2[1] sdc2[2]
      524224 blocks super 1.0 [6/6] [UUUUUU]

```

The md127 device contains an ext4 file system for /boot. Because the md127 device uses version 1.0 of the RAID superblock, the metadata is put at the end of the device, meaning that in a pinch the system can boot by using any of the /dev/sd?2 partitions instead of the RAID. When doing system updates, the changes are written to the RAID, making sure all the boot partitions are updated at once.

The boot section of configuration.nix is:

```
  boot = {
    loader.grub = {
      enable = true;
      version = 2;
      devices = [ "/dev/sda" "/dev/sdb" "/dev/sdc" "/dev/sdd" "/dev/sde" "/dev/sdf" ];
    };
    supportedFilesystems = [ "zfs" ];
    kernelPackages = pkgs.linuxPackages_4_3;
  };
```

This should ensure that the boot loader is put on all the bios_grub partitions available. The file systems defined in hardware-configuration.nix are:

```
  fileSystems."/" =
    { device = "rpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ec724812-e836-412f-b8fd-fb98851866a3";
      fsType = "ext4";
    };
```

The /dev/disk/by-uuid/ec724812-e836-412f-b8fd-fb98851866a3 is the RAID partition, md127:

```
# ls -lh /dev/disk/by-uuid/ec724812-e836-412f-b8fd-fb98851866a3
lrwxrwxrwx 1 root root 11 Apr 19 20:09 /dev/disk/by-uuid/ec724812-e836-412f-b8fd-fb98851866a3 -> ../../md127
```

I have had a look at install-grub.pl. The bit that fails looks like this:

```
my ($status, @devInfo) = runCommand("blkid -o export @{[$fs->device]}");
if ($status != 0) {
  die "Failed to get blkid info for @{[$fs->mount]} on @{[$fs->device]}";
}
```

When I run blkid by hand, I do get results:

```
# blkid -o export /dev/md127 
DEVNAME=/dev/md127
LABEL=boot
UUID=ec724812-e836-412f-b8fd-fb98851866a3
TYPE=ext4
```

This makes me think that maybe the problem here is that blkid is not anywhere on the PATH when running install-grub.pl? I'm not terribly NixOS-savvy, so I'm not sure how to go about modifying install-grub.pl with e.g. a hard coded path to blkid to see if it makes a difference.
- System: 15.09.1202.2d32ae4 (Dingo)
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: 16.03.616.4ac4b35

**Comment by plutotulp** [comment]
I finally got around to learning how to mutate and test install-grub.pl. The script succeeded when I changed this bit:

`my ($status, @devInfo) = runCommand("blkid -o export @{[$fs->device]}");
if ($status != 0) {
  die "Failed to get blkid info for @{[$fs->mount]} on @{[$fs->device]}";
}`

into this

`my ($status, @devInfo) = runCommand("/run/currrent-system/sw/bin/blkid -o export @{[$fs->device]}");
if ($status != 0) {
  die "Failed to get blkid info for @{[$fs->mount]} on @{[$fs->device]}";
}`

So, I hard coded a full path for the "blkid" executable. So, perhaps the PATH isn't quite correct after all? I did dump the path to stderr, and it did include the "bin" dir of the version of util-linux used in 16.09. And as far as I can tell, the way the path is set to include util-linux didn't really change between 15.09 and 16.03.

So, I kind of got progress, but then I don't understand why yet.

**Comment by plutotulp** [comment]
Bad code formatting in the previous comment, my bad.

**Comment by myguidingstar** [comment]
Got the same problem when playing with nixpkgs today. I have a not-so-special setup with ext4 partition.
How did you change the `install-grub.pl`? I need the workaround, too

**Comment by plutotulp** [comment]
Edit `/my/path/to/nixpkgs/nixos/modules/system/boot/loader/grub/install-grub.pl`. Locate the bit that uses `blkid` and provide the full path to the executable: `/run/currrent-system/sw/bin/blkid`. Seemed to work for me, but I then reverted back to 15.09 because I wanted to try to find out what the real problem is.

**Comment by domenkozar** [comment]
@Lassulus hit the same issue. We should specify `blkid` and `btrfs` as full paths in the `install-grub.pl`.

**Comment by domenkozar** [comment]
Let's wait a bit and backport to 16.03

**Comment by fpletz** [comment]
We don't support 16.03 anymore.
