### ISSUE TITLE
jackett: 0.19.138 -> 0.20.83

### ISSUE THREAD

**Issue by GGG-KILLER** [NixOS/nixpkgs#148326]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: jackett

current version: 0.19.138
desired version: 0.20.83

###### Notify maintainers

maintainers:

###### Note for maintainers

From 0.19.x to 0.20.x, Jackett has upgraded from .NET 5 to .NET 6 so the following changes are required in `default.nix`:
```diff
@@ -19,8 +19,8 @@ buildDotnetModule rec {
   projectFile = "src/Jackett.Server/Jackett.Server.csproj";
   nugetDeps = ./deps.nix;
 
-  dotnetInstallFlags = [ "-p:TargetFramework=net5.0" ];
-  dotnet-runtime = dotnetCorePackages.aspnetcore_5_0;
+  dotnetInstallFlags = [ "-p:TargetFramework=net6.0" ];
+  dotnet-runtime = dotnetCorePackages.aspnetcore_6_0;
 
   runtimeDeps = [ openssl ];
```

I was planning to do it myself, but `nix-shell maintainers/scripts/update.nix --argstr package jackett` has been running for 72 hours and no signs of finishing.

**Comment by c0bw3b** [comment]
Done in #151468
