### ISSUE TITLE
Package `J` add-ons

### ISSUE THREAD

**Issue by TheBlackBeans** [NixOS/nixpkgs#148465]
**Project description**
`J` is a programming language, and its package manager sucks. But it has a few libraries that are hard to install otherwise (because `J` fetches them in the derivation directory), so it would be cool if its libraries were packaged directly under NixOS. Specifically, if the package could be overridden to specify which libraries to install.

This does not seem complicated since most libraries are very simply structured (most of the time two files, a manifest and the source file), and J is interprated so no building required (even though some libraries are bindings to other libraries, such as ncurses, and thus require the original library to be installed).

**Metadata**

* homepage URL: [overview of J libraries](https://code.jsoftware.com/wiki/Vocabulary/Libraries)
* source URL: [the repo](http://www.jsoftware.com/jal/j902/addons/)
* license: gpl3 or a commercial license from Jsoftware
* platforms: linux, darwin, android

**Comment by AndersonTorres** [comment]
We were studying this a long time ago.

Now it is 2022!

**Comment by AndersonTorres** [comment]
Well, the particular reason is redundancy. I am closing this in favor of the other issue, because

- there is no substantial difference between this and the other request
- the comments on the other request has many useful suggestions
