### ISSUE TITLE
Error with make-derivation.nix: 'name' is not a valid system type

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#148498]
## Issue description

`nix flake check` on [my flake here](https://github.com/JonathanReeve/jonreeve.com/blob/flake/flake.nix) returns the error: 

```
error: 'name' is not a valid system type, at /nix/store/n34qb77ksbikrw5ns5vq28i2migw74j7-source/pkgs/stdenv/generic/make-derivation.nix:205:7
```

That seems to refer to [this line in make-derivation.nix](https://github.com/NixOS/nixpkgs/blob/b864be6850906912c4e4a2d13c90609b45d64740/pkgs/stdenv/generic/make-derivation.nix#L205). 

I don't know much about what's happening here, but I'm guessing this is a bug in Nix, if the error is in make-derivation.nix, and not in my flake file. 

### Steps to reproduce

1. Download my flake. 
2. Run `nix flake check`
3. Notice that it fails with the error above

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-20.09.4393.068984c00e0"`
 - channels(jon): `"home-manager, nixpkgs-21.05pre276604.8e1891d5b8d"`
 - nixpkgs: `/home/jon/.nix-defexpr/channels/nixpkgs`

**Comment by FliegendeWurst** [comment]
It might be a bug in Nix. It certainly isn't a nixpkgs issue
