### ISSUE TITLE
Better darwin support

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1484]
nixpkgs is getting more and more users on darwin, and even more are leaving once they see how relatively poor our support is there. More likely than not, this could be *greatly* improved between now and the second 2014 nixpkgs release, and I think now is the time to do it. This is a meta-issue for what we'll consider "feature-complete"; if you have something that really should be done please add it to the checklist or ask me to if you don't have permissions.

- [ ] [Purer darwin stdenv](https://github.com/NixOS/nixpkgs/issues/1485)
- [ ] [Investigate the possibility of different values of `system` on different OSX versions](https://github.com/NixOS/nixpkgs/issues/1486)

I've assigned this to myself, as I'm the only person I know for sure has easy access to a darwin machine with nix and knows the ecosystem well. PLEASE let me know if you can help out in any way! Especially if you are interested in taking the lead in this effort or in maintenance afterwards (though barring that I currently willing to maintain until future notice)

**Comment by ballo** [comment]
I was excited at first when I read about nix, but attempting to install it on Yosemite it failed out of the gate with the "unable to check...unstable" error.

If it fails on step 1 it's not going to get much traction :)

**Comment by peti** [comment]
This issue doesn't seem particularly import to keep around open, IMHO, because it's fairly vague and unspecific. If there are concrete issues with Darwin support, then we should have tickets for those specific issues.
