### ISSUE TITLE
texlive 'lastpage' needs update

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#14857]
I can no longer build

    pkgs.texlive.combine { inherit (pkgs.texlive) scheme-medium lastpage; };

on `master`:

~~~
trying http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/lastpage.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3532  100  3532    0     0   4049      0 --:--:-- --:--:-- --:--:--  6925
output path ‘/nix/store/y6nngzrcdmi1vhraqswvhrpjl3wsp7jd-lastpage.tar.xz’ has md5 hash ‘3c133a17250306dceec19202d3823bd7’ when ‘ada3b026e2b95f5f767f258f9cdd3fa2’ was expected
~~~~

I'm not sure how to recover from this issue?

Cc: @vcunat

**Comment by joachifm** [comment]
Possibly related to https://github.com/NixOS/nixpkgs/issues/10026 ?

**Comment by vcunat** [comment]
Yes, I'm convinced it's still all the same problem. Any URLs other than `*.nixos.org` is likely to contain different versions than what nixpkgs encodes.

**Comment by vcunat** [comment]
Not that I have a nice solution yet... :-(

**Comment by sorpaas** [comment]
@vcunat Any way to work around this for now?

**Comment by vcunat** [comment]
I know of no better source of information than  #10026 ATM. Unfortunately there's not much.
