### ISSUE TITLE
wayland-protocols: Update to 1.24

### ISSUE THREAD

**Issue by cmarcelo** [NixOS/nixpkgs#148508]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: wayland-protocols

current version: 1.23
desired version: 1.24

###### Notify maintainers

maintainers: @primeos 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by primeos** [comment]
https://github.com/NixOS/nixpkgs/pull/147177, please check for PRs first, thanks! :)

**Comment by cmarcelo** [comment]
> #147177, please check for PRs first, thanks! :)

Sorry for the noise, missed the merged PR.  Thanks!
