### ISSUE TITLE
autoPatchelfHook contains unused code intended for optimisation

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#148547]
autoPatchelfHook has been modified to improve performance in https://github.com/NixOS/nixpkgs/pull/101142 but as far as I can tell, performance is still quadratic. Also, the current source code does not use the recently introduced associative array. It is only written to, hence the non increase in performance.

Pinging @DavHau could it be possible that your patch was not pushed in full, or only partial ? Looking at the current source code, does it look like the code you intended at the time ?

Pinging @aszlig for a second pair of eyes, and you feedback on the state of autoPatchelfHook.

Iff no-one works on this, I can submit a patch as we have abysmal performance on matlab which packages a tremendous amount of small shared objects.

**Comment by layus** [comment]
No kidding. ~16 hours for autoPatchelf to run :sweat_smile: 

```
[2021-12-04 14:32:55] automatically fixing dependencies for ELF files
...
[2021-12-05 06:12:03] autoPatchelfHook could not satisfy dependency libperl.so wanted by...
[2021-12-05 06:12:03] Add the missing dependencies to the build inputs or set ...
```

**Comment by DavHau** [comment]
Sorry, didn't see this so far. The patch back then definitely increased the performance for me noticeable and it definitely fixes a quadratic issue whenever something is added to the cache. But that doesn't mean that the code is free of quadratic runtime issues. My PR possibly fixed only one of several issues.

**Comment by layus** [comment]
@DavHau Thank you for your reply. It makes more sense now. My issue was with lookup time, so pretty orthogonal indeed.

**Comment by layus** [comment]
I guess https://github.com/NixOS/nixpkgs/pull/149731 closes this issue :tada:. Thanks everyone for feedback and participation :pray:
