### ISSUE TITLE
package-request: JetBrains DataSpell

### ISSUE THREAD

**Issue by istimaldar** [NixOS/nixpkgs#148564]
**Project description**
The IDE for Professional Data Scientists by JetBrains.

**Metadata**

* homepage URL: https://www.jetbrains.com/dataspell/
* license: Unfree
* platforms: linux, darwin

**Comment by lorenzleutgeb** [comment]
Resolved by #148037

**Comment by sei40kr** [comment]
Closing this since it's been already merged:
https://github.com/NixOS/nixpkgs/pull/226340
