### ISSUE TITLE
Purer darwin stdenv

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1485]
Currently, we have issues with builds on darwin due to impurities, especially because there are some significant differences between OSX versions. We should strive to make our darwin stdenv as pure as possible, even up to the libc if possible (it is open-source)

**Comment by domenkozar** [comment]
So now that we have #10187 this can be closed?

**Comment by copumpkin** [comment]
Purity can still be improved, but it's a world better than it was
