### ISSUE TITLE
[hardening] systemd service permissions default to group "root" even with explicitly set user

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#148555]
### Describe the bug
This is a hardening improvement / defense in depth suggestion. 88029bce39bd485fc07f1b2aa111c3ee9d12e684 accidentally ended up running a service with "root" group because it was not clear that setting a user explicitly would keep the group set to the default "root" value.

IMO it would make sense to never accept an explicitly set User without an explicitly set Group, and possibly vice versa. Someone who actually wants to have "customuser:root" can still do it, but they would have to be explicit about it.

If we have a general consensus on this, the first step would be to audit nixpkgs/nixos to find other occurrences of this pattern (User without Group, or Group without User) and remediating them. Then, we can add an error if one is provided but not the other.

**Comment by aanderse** [comment]
This is pretty straight forward and a great idea. Thanks for thinking of it. Let's do it :+1:

**Comment by delroth** [comment]
@mweinelt this is a bug I filed as a followup to your changes in #148543, but as far as I can tell the systemd documentation disagrees with the behavior that you have experienced:

https://man7.org/linux/man-pages/man5/systemd.exec.5.html#USER/GROUP_IDENTITY

> If no group is set, the default group of the user is used.

This also seems to match what I'm seeing in practice. The Grafana systemd unit file only sets User but not Group, but the process seems to run as the correct gid (not 0).

Could you double check your original findings? There might be some extra condition needed to end up with gid 0 that I haven't figured out, if you have a way to repro this would be appreciated!
