### ISSUE TITLE
ghc 8.10.7 subtly broken

### ISSUE THREAD

**Issue by bacchanalia** [NixOS/nixpkgs#148583]
### Describe the bug
The following fails with ghc 8.10.7 (haskell.compiler.ghc8107) on nixos, but works with ghc 8.10.4 (ghc) and also works with ghc 8.10.7 on other systems (tested with ghcup on debian sid) 

### Steps To Reproduce
```
> nix-shell -p haskell.compiler.ghc8107 cabal-install zlib
> git clone https://github.com/haskell/cabal
> cd cabal
> cabal build cabal-tests
> cabal run cabal-tests
```

### Expected behavior
tests run (can kill once tests start running)

### Actual behavior
> threads: 1
tests to run: 279
\<command line>: cannot satisfy -package-id Cabal-3.7.0.0-inplace
    (use -v for more information)
GHCi exited with ExitFailure 1 (use -v for more information)
cabal-tests: fd:14: hGetLine: end of file

### Notify maintainers
@cdepillabout @sternenseemann 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.4438.5854a24cfcc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.05.4438.5854a24cfcc"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
module:
  - haskell.compiler.ghc8107
```

**Comment by sternenseemann** [comment]
Can't reproduce on 95d8e017775871b82a83c4954b81094f840034f6.

**Comment by bacchanalia** [comment]
I couldn't reproduce on a clean install either. On further inspection it appears to be some sort of problem with my local package store. Closing.
