### ISSUE TITLE
libdrm: Update to 2.4.109

### ISSUE THREAD

**Issue by cmarcelo** [NixOS/nixpkgs#148510]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: libdrm

current version: 2.4.108
desired version: 2.4.109

###### Notify maintainers

maintainers: @primeos 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by primeos** [comment]
https://github.com/NixOS/nixpkgs/pull/147425, please check for PRs first, thanks! :)

**Comment by cmarcelo** [comment]
> #147425, please check for PRs first, thanks! :)

Sorry for the noise. I did look for code in master (so couldn't see it was merged in staging) and for open MRs, but not merged MRs.

Thanks!
