### ISSUE TITLE
Invalid syntax in the tt-rss module definition

### ISSUE THREAD

**Issue by MasseR** [NixOS/nixpkgs#148694]
### Describe the bug

The module for tt-rss service creates a PHP configuration file that has a syntax error when you are using a password file:

``` php
putenv('TTRSS_DB_PASS=file_get_contents('/etc/nixos/system/services/ttrss/db'');
```

### Steps To Reproduce
1. Enable the ttrss module
2. Enable the password file
3. Observe how the ttrss service fails silently with error code 255

``` nix
services.tt-rss = {
  enable = true;
  database = {
    type = "pgsql";
    passwordFile = "/path/to/your/password";
  };
};
```

### Expected behavior

The ttrss service start without failures.

### Screenshots

``` php
putenv('TTRSS_DB_PASS=file_get_contents('/etc/nixos/system/services/ttrss/db'');
```

### Notify maintainers

@globin 
@zohl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.94, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre335103.6daa4a5c045, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
- services.tt-rss
```

**Comment by FliegendeWurst** [comment]
This was fixed in #148696, thank you.
