### ISSUE TITLE
[kotatogram-desktop] Out-of-date 1.4.1 -> 1.4.5.

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#148654]
###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: kotatogram-desktop
current version: 1.4.1
desired version: 1.4.5

###### Notify maintainers
maintainers: @ilya-fedin 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ilya-fedin** [comment]
Yeah, I'm currently working on this. I have a package with my own patch in NUR, as soon as I get a working NUR build, I'll work at nixpkgs package update. I also want to try to set platforms.all in the derivation.

**Comment by brcha** [comment]
@ilya-fedin I've just installed kotatogram 1.4.8 from your NUR. I'll actually leave that channel for kotatogram, since it's probably gonna be updated faster. Thank you for your work.

**Comment by ilya-fedin** [comment]
Yeah, nixpkgs is very slow at merging PRs :(

**Comment by ilya-fedin** [comment]
#148672 was finally merged a week ago and #168059 finishing the idea of making webkit optional was merged today. So kotatogram now should be 1.4.9, have a macOS build on Hydra and no more require webkitgtk.
