### ISSUE TITLE
Installing `steam` on 21.05 results in getting a `package is broken` message

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#148628]
### Describe the bug
Installing `steam` on the release-21.05 channel errors with the message that the package is broken. However, the derivation doesn't have the broken flag set.

### Additional context
I switched my `nixos` channel from `nixos-unstable` to `nixos-21.05` before doing it. For that I ran the following commands:

```nix
sudo nix-channel --remove nixos
sudo nix-channel --add https://nixos.org/channels/nixos-21.05 nixos
sudo nix-channel --update

# add steam using `programs.steam.enable = true;`
sudo nixos-rebuild --update boot
```

My config:
```nix
nixpkgs.config = {
    allowUnfree = true;
    packageOverrides = pkgs: {
      nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/7e9776db925112f042f1a83099bf7cfaecbe84c8.tar.gz") {
        inherit pkgs;
      };
      unstable = import <nixos-unstable> {
        config = config.nixpkgs.config;
      };

      steam = pkgs.steam.override {
        extraPkgs = pkgs': with pkgs'; [ qt5.full jdk8 flite ];
        nativeOnly = true;
        withJava = true;
      };
    };
  };
programs.steam.enable = true;
```

Removing the package override for steam works as expected. I think nix picks up that the package is broken on unstable but not on the release. but it still errors.

### Notify maintainers

@jagajaga @jonringer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.4438.5854a24cfcc (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(me): `"nixos-21.05.3801.83667ff60a8, nixos-unstable-21.11pre323695.9aeeb7574fb"`
 - channels(root): `"nixos-21.05.4438.5854a24cfcc, nixos-unstable-22.05pre335103.6daa4a5c045"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by SuperSamus** [comment]
The reason it was broken is probably because of `nativeOnly`.
Now it's not an option anymore, if that was the case then this can be closed.

**Comment by jonringer** [comment]
nativeOnly was removed in master. However, 21.05 still has it... I'll close this as it's going to be a non-issue in 22.05
