### ISSUE TITLE
lua and pkg-config file naming (lua.pc)

### ISSUE THREAD

**Issue by rardiol** [NixOS/nixpkgs#14867]
I was packaging a game and was having problem with this: https://github.com/smcameron/space-nerds-in-space/blob/master/Makefile#L331. The makefile requests lua5.2.pc, but nix only includes lua.pc. I want a clarification if this is as should be.

The packages could simply be patched to look for a generic lua.pc, but if a package requests a specific lua version, shouldn't it be provided to it? A simple symlink from lua5.2.pc to it's own lua.pc would fix this.

http://lua-users.org/lists/lua-l/2011-12/msg00731.html ( and debian ) seems to be the closest to a standard according to #lua

compatibility: 
- debian uses lua5.X.pc :  [lua5.1.pc](https://packages.debian.org/search?searchon=contents&keywords=lua5.1.pc&mode=path&suite=testing&arch=any) [lua5.2.pc](https://packages.debian.org/search?searchon=contents&keywords=lua5.2.pc&mode=path&suite=testing&arch=any) [lua5.3.pc](https://packages.debian.org/search?searchon=contents&keywords=lua5.3.pc&mode=path&suite=testing&arch=any) [lua.pc](https://packages.debian.org/search?searchon=contents&keywords=lua.pc&mode=path&suite=testing&arch=any) (none),
- archlinux goes for maximum inconsistency: [5.1 -> lua5.1.pc](https://www.archlinux.org/packages/extra/x86_64/lua51/files/), [5.2 -> lua52.pc](https://www.archlinux.org/packages/extra/x86_64/lua52/files/), [5.3 -> lua.pc](https://www.archlinux.org/packages/extra/x86_64/lua/files/)

potentially related note: should there be a lua5.X binary for scripts that try to call a specific version of lua (folks on irc said it happens). That's how it already works for python, right?

**Comment by vcunat** [comment]
Oh, I've successfully run the game but I never got to polishing and pushing the expression. Now I found it and created a commit at least: 89cdc8d5685e.

**Comment by rardiol** [comment]
my own unpolished expression: https://github.com/rardiol/nixpkgs/commit/b0772a6cf122f6ed4c8bc581570c929d47aca911

**Comment by Profpatsch** [comment]
I guess that resolves this issue.
