### ISSUE TITLE
Investigate the possibility of different values of `system` on different OSX versions

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1486]
Unlike Linux, different major versions of OSX seem to come with huge changes that often break backwards compatibility. We should investigate whether these can be eliminated with properly pure builds, and if not we should consider giving each version a different value of `system` if a better solution can't be found.

**Comment by Profpatsch** [comment]
(triage) Is this still relevant?

If there are no concrete steps a concrete person wants to take, I suggest we close this.

**Comment by shlevy** [comment]
I'll defer to @copumpkin as to whether or not this is still relevant or if pure-darwin has actually fixed this issue, but as to closing this, I'm fine with a special tag but it would be good to have some persistent place to track long-standing issues like this.

**Comment by copumpkin** [comment]
I think we're 95% good with not needing different values of `system` here, now that we have PD. The remaining parts will likely get resolved, so I'd be tempted to close this until we find a compelling reason to do something different.

**Comment by grahamc** [comment]
Let's close it, then.
