### ISSUE TITLE
Nixos 16.03 regression - "Page not found" in browsers when `networking.useNetworkd` active

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixpkgs#14861]
## Issue description

I was using it when on _nixos 15.09_ and I could navigate without any problems.

As soon as I updated to _nixos 16.03_, both chromium and firefox are often returning
"Page not found" errors, pages without css or with partial css.
### Steps to reproduce
-  `networking.useNetworkd = true`
-  Start firefox or chromium.
-  Search the "test" keyword using google or any other search engine (you're lucky
  if you can do this).
-  Attempt to open returned search result one by one.
-  At some point, your browser will return the "Page not found" error.
### How to avoid the problem

Available solutions are:
1. `networking.useNetworkd = false`.
2. Revert to nixos _15.09_.
## Technical details
- System: nixos 16.03
- Nix version: irrelevant
- Nixpkgs version: latest of nixos 16.03 branch

**Comment by bjornfor** [comment]
Regressions are annoying. But at least the manual warns about using ```networking.useNetworkd = true```:

```
  Note that this option is experimental, enable at your own risk.
```

**Comment by Profpatsch** [comment]
triage: still a problem?

**Comment by Profpatsch** [comment]
I’ll close since this is issue is very old. Feel free to reopen if it still occurs.

**Comment by jraygauthier** [comment]
Alright, seem like a good idea.
