### ISSUE TITLE
Package request: GitKraken

### ISSUE THREAD

**Issue by a1russell** [NixOS/nixpkgs#14875]
[GitKraken](https://www.gitkraken.com/) looks like a neat Git GUI. It might be good to package it.

I'll probably package it myself eventually, but I'm filing this just in case someone else has more time/motivation than me. :wink:

**Comment by zimbatm** [comment]
There are already so many tickets I don't think that someone will look at this one and go: "ooh I need to package this". I had a quick look and the source doesn't seem to be available either.

**Comment by a1russell** [comment]
You never know, @zimbatm. Sometimes when I find that a package is missing on this distro, or a feature is missing from some development library I'm using, I'll search GitHub issues and/or pull requests to see if someone else is working on it. If I find something and activity on it is slow, for example, I can make suggestions if I'm able. Oftentimes I'll simply subscribe to the issue.

A GitHub issue like this would also be a good candidate for some label like `up-for-grabs` so that a newcomer could find it through a channel like http://www.firsttimersonly.com/, but I'm not sure the Nix project is doing that yet. It could be an idea, though.

On the subject of GitKraken, I think you're right about the source code. I searched a bit myself, and I think it's closed source, so it'd have to be marked as non-free.

**Comment by zimbatm** [comment]
I guess is depends what the issues should be used for. There is a long tail of things we could do but realistically never will, which means that the number of issues will only grow. Feel free to keep it open but also consider of that clutter :)

We do have a "3.skill: good-first-bug" label but it's not going to be easy here since pre-built binaries tend to need more arcane knowledges.

**Comment by peti** [comment]
I, too, consider open issues such as this one as wasteful. I cannot remember a single case where such a package request was solved by anyone.

**Comment by a1russell** [comment]
@peti Considering wastefulness, I strongly feel it's a waste of anyone's time who stumbles upon this issue and has to read you and @zimbatm attack my usage of GitHub issues. Can we move this off-topic discussion to the mailing lists, please? I'll provide my case there, including an example.

**Comment by peti** [comment]
@a1russell, the point of @zimbatm and my comments is to reach a consensus with you about how we would like this issue tracker to be used (and how not).

Anyhow, I don't think having open issues such as this one around makes sense for us, so I'm closing this item.

**Comment by a1russell** [comment]
@peti I realize that, and I think this is the wrong place for you and @zimbatm  to do that. It's completely off topic from the issue itself, and I still maintain that the issue is valid, as well as my usage of the issue tracker.

You claim that such issues are "wasteful", but you do not state what is being wasted. You claim that you "do not remember" any package requests being solved by anyone, but it's clear to me that this is selective bias.

Here's an example of an issue I raised here on nixpkgs, where someone else ended up creating the package (still in progress): #11407 

Absolutely non-comprehensive list of issues that other people filed, just from me searching for a few minutes: #287, #3399

And also just a few minutes searching the issue tracker of the more popular OS X alternative, Homebrew:
* https://github.com/Homebrew/legacy-homebrew/issues/151
* https://github.com/Homebrew/legacy-homebrew/issues/21798
* https://github.com/Homebrew/legacy-homebrew/issues/13471
* https://github.com/Homebrew/legacy-homebrew/issues/13092

**Comment by puffnfresh** [comment]
This package request issue has been an example of coordinating some work:

https://github.com/NixOS/nixpkgs/issues/10452

**Comment by vcunat** [comment]
In my experience, opening similar tickets almost never helps to fulfill them. (If I discount motivating the author, and that seem to have failed in this case ;-)

**Comment by razvan-panda** [comment]
@a1russell @peti Someone did end up packaging GitKraken until [version 2.7.0](https://github.com/NixOS/nixpkgs/pull/27571/files)

I tried to update it now to version 3.3.4
It required the library libxcb for it to start, but once it starts it hangs on the splash screen animation.
And using gitkraken --log-file "/home/neo/Desktop/kraken.txt" doesn't output anything.
