### ISSUE TITLE
Time-setting problem

### ISSUE THREAD

**Issue by vanzef** [NixOS/nixpkgs#14877]
## Issue description

It's impossible to set time and date via timedatectl. @abbradar said that it's a bug.
### Steps to reproduce

$ timedatectl set-time "2016-01-01 00:00:00"
Failed to set time: Changing system settings via systemd is not supported on NixOS.
(It's reproducible for any time and date)
## Technical details
- System: NixOS (with nixpkgs from git)
- Nix version: 1.11.2
- Nixpkgs version: 16.09pre78848.9549257

**Comment by abbradar** [comment]
Notice that this is very low priority because one can use `date -s`, but this is a bug nevertheless I think.

**Comment by lheckemann** [comment]
Fixed in https://github.com/NixOS/systemd/commit/a5af87e469ed3bd806d1ac34716d4f17ce9d3464
