### ISSUE TITLE
`nixos-21.11` doesn't update, even though `tested` succeeded

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#148710]
### Describe the bug

The `nixos-21.11` channel seems to be stuck for reasons I don't understand. Eval [1727706](https://hydra.nixos.org/eval/1727706) is finished and the `tested` job succeeded. Still there is no update to `nixos-21.11`.

One detail adding to the situation is that https://github.com/NixOS/nixpkgs/pull/148228 didn't reach the channel yet, which we might want to happen as soon as possible.

**Comment by quantmint** [comment]
Exactly the same seems to happen for nixos-unstable.

**Comment by vcunat** [comment]
Yes, I recommend following https://matrix.to/#/!QLQqibtFaVtDgurUAE:nixos.org/$jioO1Za_7oIeAI4Wpb_TZStnjAxJqVMLpqAxVjjwJ40?via=nixos.org&via=matrix.org&via=nixos.dev

**Comment by sternenseemann** [comment]
<https://monitoring.nixos.org/grafana/d/fBW4tL1Wz/scheduled-task-state-channels-website?viewPanel=4&orgId=1&refresh=10s>

**Comment by erictapen** [comment]
`nixos-unstable` and `nixos-21.11` both just advanced :partying_face:
