### ISSUE TITLE
redshift service cannot access the display (with workaround)

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#14882]
## Issue description

Redshift starts and immediately exits due to having insufficient access to X11. This is new as of:

 - https://github.com/NixOS/nixpkgs/issues/14623
 - https://github.com/NixOS/nixpkgs/commit/b6de72513f632bed4c16a15096a56868e711ffe4
 - https://github.com/NixOS/nixpkgs/commit/659c41a7d59d8354c58dccf5b97637b6a633aed9

### Steps to reproduce

1. Enable Redshift

```nix
{
  services.redshift = {
    enable = true;
    latitude = "30.25";
    longitude = "-97.75";
    temperature.night = 1900;
  };
}
```

2. Start it ...

```
Apr 21 21:11:38 NdNdNx systemd[1]: Started Redshift colour temperature adjuster.
Apr 21 21:11:38 NdNdNx redshift[2584]: No protocol specified
Apr 21 21:11:38 NdNdNx redshift[2584]: `RANDR Query Version' returned error -1
Apr 21 21:11:38 NdNdNx redshift[2584]: Initialization of randr failed.
Apr 21 21:11:38 NdNdNx redshift[2584]: Trying next method...
Apr 21 21:11:38 NdNdNx redshift[2584]: No protocol specified
Apr 21 21:11:38 NdNdNx redshift[2584]: X request failed: XOpenDisplay
Apr 21 21:11:38 NdNdNx redshift[2584]: Initialization of vidmode failed.
Apr 21 21:11:38 NdNdNx redshift[2584]: Trying next method...
Apr 21 21:11:38 NdNdNx redshift[2584]: No more methods to try.
Apr 21 21:11:38 NdNdNx systemd[1]: redshift.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 21:11:38 NdNdNx systemd[1]: redshift.service: Unit entered failed state.
Apr 21 21:11:38 NdNdNx systemd[1]: redshift.service: Failed with result 'exit-code'.
```

## Workaround:

Override and specify an XAUTHORITY file it can use.

A more proper fix would be having redshift run as a user service, I believe. While we're at it, it probably shouldn't be running as root.

```nix
{
  systemd.services.redshift.environment = {
    XAUTHORITY = "/home/grahamc/.Xauthority"; # Use %h and a user-service somehow
  };
}
```

## Technical details

* System: `16.03.616.4ac4b35 (Emu)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.03.616.4ac4b35"`

---

Related issue: https://github.com/NixOS/nixpkgs/pull/10018

**Comment by hiberno** [comment]
Confirmed.

+1 for implementing `Redshift.service` as `user.service`.

**Comment by domenkozar** [comment]
Backported to 16.03 in 82ca7f75d6f239502fad7df553aea36339bae8da

**Comment by valeriangalliat** [comment]
Hi, thanks for the fix!

However when upgrading from system service to user service for Redshift, the system service seems to be still running and keeps spamming logs with the same error, while the user service also runs successfully.

I can't find a way to stop the system service since systemd don't "know" anymore about it (even though it's constantly trying to restart it).

I'd rather avoid rebooting the computer, but maybe it's the only solution?

Thanks!

**Comment by 8573** [comment]
I still get the redshift error messages repeating indefinitely in my journal, with only the redshift user service(s) running, on NixOS `16.09pre87431.3badad8 (Flounder)`.
