### ISSUE TITLE
nixos-rebuild should treat any build/target host as an SSH target

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#148918]
### Describe the bug

`nixos-rebuild` treats the string build/target host "localhost" as special, using SSH to run the build job if the host is anything but this specific value. This is problematic in two ways:

- There are quite a few ways to refer to "this host". For example, IPv4 addresses like "127.0.0.1", "10.0.0.1" or "192.168.0.2" (depending on setup), IPv6 addresses like "::1", other local addresses like "localhost.localdomain", and probably more that I'm forgetting.
- On the flip side, it is at least conceivable that someone has mapped "localhost" to some other IP. I realise this isn't likely (although I've seen setups where "localhost" is unmapped), but it's a possibility.

### Steps To Reproduce
1. Run `nixos-rebuild` with the `--build-host` option and a loopback reference other than "localhost"

### Expected behavior
Rather than second guess the user `nixos-rebuild` should use the build and target host values *if non-empty*, no matter their value, to SSH into the relevant host. This way there's no magic value, and the script ends up simpler because of not having to treat "localhost" as special.

### Notify maintainers
@Artturin 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334027.e34c5379866, home-manager-21.05"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by znewman01** [comment]
> On the flip side, it is at least conceivable that someone has mapped "localhost" to some other IP.

I ran into this where I had port-forwarding from a VM configured, so `localhost:2221` forwarded to port 22 on the VM. Using `user@localhost` seems to work around for now.
