### ISSUE TITLE
collectd cannot be installed on non x86_64-linux because of xen

### ISSUE THREAD

**Issue by avdv** [NixOS/nixpkgs#148961]
### Describe the bug

I am using  NixOS 21.11 on aarch64 (raspberry pi) and enabled the influxdb service. This depends on the collectd service (actually collectd-data package).

Trying to run `nixos-rebuild switch` or trying to install collectd directly, results in an error:
```console
# nix-env -iA nixos.collectd
installing 'collectd-5.12.0'
error: Package ‘xen-4.10.4’ in /nix/store/mv1spk7lcrnmjkgzdayv5x6bq0hs1grl-nixos-21.11.333984.19df09617db/nixos/pkgs/applications/virtualization/xen/generic.nix:248 is not supported on ‘aarch64-linux’, refusing to evaluate.

a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

This is caused by the collectd xencpu plugin being enabled by default (since commit b102c5f715ff3e92552a3a26ef4840546b49a88e) which is only supported on x86_64-linux.

### Steps To Reproduce
1. on non-x86_64-linux try to install collectd

### Expected behavior

One should be able to install / enable collectd on any system which it supports, skipping plugins that are not supported on the current system.

Would it be possible to filter the plugins list by check-meta to only enable those where all `buildInputs` are non-broken and `!  hasUnsupportedPlatform`?!

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.333984.19df09617db"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
- collectd
# a list of nixos modules affected by the problem
module:
- influxdb
- collectd
```

**Comment by Artturin** [comment]
Let's try enabling xen for aarch64-linux

**Comment by avdv** [comment]
> Let's try enabling xen for aarch64-linux

But that does not really solve the problem, since one still cannot install collectd on any other supported platform... ?!

**Comment by luizribeiro** [comment]
I put up a PR for this to get this to build again, as I was also running into it.

Should we consider ways of splitting this package further? I'm fairly new to nix, but because all of these are `buildInputs` to `collectd`, aren't we dragging along a ton of dependencies just to install `collectd`?

**Comment by luizribeiro** [comment]
Well I guess you can get it to build with just the plugins you need using an overlay like:

```
final: prev: {
  collectd = prev.collectd.override {
    enabledPlugins = [
      "network"
      "sensors"
    ];
  };
}
```

**Comment by SigmaSquadron** [comment]
This was resolved a while ago. `collectd` no longer depends on Xen.
