### ISSUE TITLE
Missing secrets handling in asterisk

### ISSUE THREAD

**Issue by yayayayaka** [NixOS/nixpkgs#149042]
### Describe the bug
It does not seem to be possible to provide secrets to the asterisk module without writing them to the Nix store.

### Additional context
If there actually is a way to provide secrets securely, please let me know.

### Notify maintainers

@auntie @DerTim1 @yorickvp
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/etc/src/nixpkgs`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: asterisk
```

**Comment by yorickvP** [comment]
I was using `#include ` to [include](https://wiki.asterisk.org/wiki/display/AST/Using+The+include%2C+tryinclude+and+exec+Constructs) secret files from elsewhere.

**Comment by yayayayaka** [comment]
Oh, thanks for the hint! I'll leave the refactoring PR open for discussion.
