### ISSUE TITLE
Package Request: mastodon-twitter-poster

### ISSUE THREAD

**Issue by WolfangAukang** [NixOS/nixpkgs#149079]
**Project description**
This is an app for crossposting between Mastodon and Twitter. The app is made so that multiple users can connect to it using the OAuth interface from both Twitter and Mastodon and choose options on how the crosspost should work.

**Metadata**

* homepage URL:
* source URL: https://github.com/renatolond/mastodon-twitter-poster
* license: agpl 3.
* platforms: unix

**Comment by samueldr** [comment]
The project has been archived.

> This project is now archived. The code here has been functional but affected by Twitter changes. You can probably still run this locally, but no further support will be given and no component will be upgraded.

Closing, given that the platform is acting in a hostile manner toward its users anyways. Anyone needing such software, feel free to find anything that purportedly work, and package it (or ask for request) though.
