### ISSUE TITLE
Nautilus does not load its extension

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#14917]
## Issue description

Nautilus cannot find its extensions when started from GNOME-Shell.

If I start it from GNOME-Terminal, it find them though.
### Steps to reproduce
- Start nautilus from GNOME-Shell
- The terminal & file-roller extensions are missing (right click on a folder/archive, extensions should be in the context menu)
## Technical details
- NixOS: 16.09.git.d167450M (Flounder)
- nix-env (Nix) 1.11.2

**Comment by jonafato** [comment]
These items appear in the right-click menu now. Should this issue be closed?

**Comment by bjornfor** [comment]
Seems fixed here too (NixOS 18.03). Closing.
