### ISSUE TITLE
users.users.<name?>.createHome clobbers permissions of /var/empty when users.users.<name?>.home is unset

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#14910]
Title sums it up pretty well. The default value of home is "/var/empty" and createHome modifies that to have the usual home directory permissions for that user, which breaks polkitd (among other things). It's easy to assume that createHome will default to creating a conventional /home/<name?> directory, so the documentation should be updated and/or the default behavior changed.

The polkitd breakage manifests with the following error when e.g. systemctl commands requiring authentication are ran:

    Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Timeout was reached (g-io-error-quark, 24)

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixpkgs/pull/18365
