### ISSUE TITLE
`fakeroute`: upstream is 404 and even removed from The Wayback Machine

### ISSUE THREAD

**Issue by kvtb** [NixOS/nixpkgs#149201]
**Project description**

https://moxie.org/software/fakeroute/ and http://web.archive.org/web/*/https://moxie.org/software/fakeroute/ are 404, so `fakeroute` package cannot be built.

Does anyone have a backup ?

**Comment by vs49688** [comment]
[fakeroute-0.3.tar.gz](https://github.com/NixOS/nixpkgs/files/7665500/fakeroute-0.3.tar.gz)

It's still in the Nix cache:
```
nix-repl> :b pkgs.fakeroute.src

this derivation produced the following outputs:
  out -> /nix/store/3myrijdl1nbj8xjnskdxdylif4rr3290-fakeroute-0.3.tar.gz
```

**Comment by AndersonTorres** [comment]
For now, break it on meta.break.

**Comment by mohe2015** [comment]
Do you think there is any reason it got removed this way (even from wayback machine?). To me this looks kinda suspicious.

**Comment by vs49688** [comment]
No, he's excluded his entire site. Most likely he's reorganised everything and broken the URL.
```
$ curl https://moxie.org/robots.txt
User-agent: ia_archiver
Disallow: /
```

**Comment by vs49688** [comment]
Closing because https://github.com/NixOS/nixpkgs/pull/149396 is merged.
