### ISSUE TITLE
language-puppet-1.2 Hydra build request

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#14929]
## Issue description
`language-puppet-1.1.5.1` (haskellPackages) released on Mar 14 has never been build by Hydra.
The latest build seems to be http://hydra.nixos.org/build/33370404 and it uses `language-puppet-1.1.5`
I do know the error from `33370404` has been fixed and it does build correctly with the latest `lts` used by nixpkgs (currently lts-5.9)

Is there something I can do to request `language-puppet-1.1.5.1` to be built on Hydra using the `lts-5.x` package set ?

Let me know if there is a better place to discuss the above. Apologies in advance if this is the wrong one.

**Comment by PierreR** [comment]
`language-puppet-1.2` is now in `stackage-nightly`.

I have tested it using `nix-shell -p language-puppet` and the build passes.

@peti  does it need to be added in `haskell-modules/configuration-common.nix` so it is cached ? I would like to switch our internal sharing of this tool from `docker` to `nix` and caching the binary would ease that.

**Comment by peti** [comment]
`language-puppet` builds are disabled in `pkgs/development/haskell-modules/configuration-hackage2nix.yaml` because these builds used to fail. If that issue has been fixed, then we can remove the package from the "dont-distribute-packages" section  in that file.

**Comment by PierreR** [comment]
Thanks.

@peti If you wish you can disable the build for `x86_64-darwin` (it is not supported). 
`i686-linux` is also failing. I will ask the maintainer if he wish to support `hruby` for `i686-linux` but I really doubt it.

As far as I am concerned I only care about `x86_64-linux` which currently builds successfully.
