### ISSUE TITLE
Enabling Kerberos leaks implementation details

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14928]
I added 
```
services.kerberos_server.enable = true;
```

to configuration.nix and I return I got:

```
nixos-rebuild switch
building Nix...
building the system configuration...
error: attribute ‘heimdal’ missing, at /nix/store/0rb9zxfhc080mky5cxmhfqyyxlr4arbh-nixos-16.03.616.4ac4b35/nixos/nixpkgs/nixos/modules/services/system/kerberos.nix:3:4
(use ‘--show-trace’ to show detailed location information)
```

`16.03.616.4ac4b35 (Emu)`

**Comment by abbradar** [comment]
cc @dguibert (I had to look through essentially old SVN history to find a reference -- this service is untouched for a long time).

**Comment by dguibert** [comment]
I don't use this service anymore.

BTW I've fixed its evaluation in the PR #14959.

**Comment by abbradar** [comment]
Let's not close this unless fix hits master.

**Comment by abbradar** [comment]
@0xABAB can you please test the fix and see if there are any more problems with the service?
