### ISSUE TITLE
libadwaita: 1.0.0.alpha.3 -> 1.0.0.beta.1

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#149254]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: libadwaita

current version: 1.0.0.alpha.3
desired version: 1.0.0.beta.1

###### Notify maintainers

maintainers: @dotlambda

###### Note for maintainers

Please tag this issue in your PR.

NB: probably required meson >=59.0, when we have 57.1 latest on unstable; need this PR https://github.com/NixOS/nixpkgs/pull/144779 ?

**Comment by dotlambda** [comment]
> NB: probably required meson >=59.0, when we have 57.1 latest on unstable; need this PR #144779 ?

Yes, that's why it also hasn't been updated to 1.0.0.alpha4 yet.

**Comment by psydvl** [comment]
Looks like now we have meson 60.2 available
https://github.com/NixOS/nixpkgs/pull/150486
`meson_0_60`

**Comment by dotlambda** [comment]
But we don't have gtk4 >= 4.5.0 yet.

**Comment by Cogitri** [comment]
GTK4.6.0 and libadwaita 1.0.0 have been released recently, maybe this can be revisited.

**Comment by bobby285271** [comment]
https://nixpk.gs/pr-tracker.html?pr=153235
1.0.1 should be available in nixos-unstable for a while.
