### ISSUE TITLE
gazeboSim 6 failing on master

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#14921]
## Issue description

Gazebo installation fails on latest master
### Steps to reproduce

clone master. cd to folder, then:
`nix-env -f . -iA gazeboSimulator`
## Technical details

```
CMake Error at /nix/store/7s2qrfb4aywnqr8pf2gb2vgfv8jzs9wq-sdformat-3.7.0/lib/cmake/sdformat/SDFormatConfig.cmake:20 (message):
  Library 'sdformat' in package SDFormat is not installed properly
Call Stack (most recent call first):
  cmake/SearchForStuff.cmake:480 (find_package)
  CMakeLists.txt:128 (include)
```
- System: 16.09pre79453.32b7b00 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre79453.32b7b00"

cc:
@therealpxc

**Comment by therealpxc** [comment]
So sorry about not spotting & responding to this earlier. I've been dealing with some distracting personal upheaval lately. I'll try to get this fixed tomorrow.
