### ISSUE TITLE
Packaging request: tailwindcss cli

### ISSUE THREAD

**Issue by lobre** [NixOS/nixpkgs#149333]
**Project description**

Tailwindcss is a utility-first CSS framework. The team has recently built a cli to facilitate the compilation process.

**Metadata**

* homepage URL: https://tailwindcss.com/docs/installation#using-tailwind-cli
* source URL: https://github.com/tailwindlabs/tailwindcss
* license: mit
* platforms: it is an npm package, so unix, linux, darwin

Here is also the link to the npm package containing the executable of the cli: https://www.npmjs.com/package/tailwindcss

It does not seem complicated to build in Nix but I have just never done that before so it feels a little overwhelming to me. Would appreciate a hand.

**Comment by jyooru** [comment]
Welcome to nixpkgs! There's a [nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/) that contains useful information for packaging for nixpkgs. There are also specific sections for [adding packages](https://nixos.org/manual/nixpkgs/stable/#chap-quick-start) and [specific languages](https://nixos.org/manual/nixpkgs/stable/#chap-language-support). [Here's what I did to package tailwindcss](https://nixos.org/manual/nixpkgs/stable/#javascript-packages-nixpkgs).

**Comment by lobre** [comment]
Thanks, @jyooru for the warm welcome and the guidance. I did not know those docs were that accurate.
And thank you also for taking the time to create this PR, that is much appreciated.

**Comment by lobre** [comment]
Do you know by any chance why tailwindcss still does not appear on https://search.nixos.org/packages (unstable channel), while I can properly install it with `nix-env -iA nixpkgs.nodePackages.tailwindcss`?

The `nixpkgs-unstable` channel is correctly built of what I can see: https://status.nixos.org/

Is there anything special blocking me from finding it? Maybe there is a delay before it shows up on search.nixos.org.

**Comment by jyooru** [comment]
I've just tried installing it on my system and it's not working either.

search.nixos.org is updated hourly: https://github.com/NixOS/nixos-search/actions/workflows/cron-nixpkgs.yml
It seems to have broken 12 hours ago, but this was merged 2 days ago, and even running a local `nix search` doesn't show `nodePackages.tailwindcss`...

After a little investigation, it looks like there's a bigger problem here. 

I've tried a few PRs that add a new node package and none seem to be available on `nixos-unstable` but are available in the nixpkgs repository (eg `nix-build -A nodePackages.tailwindcss`.

For example, #129668, added 9th of July:
```
❯ nix-shell -p nodePackages.terser
error: attribute 'terser' missing
```
Where as running it through the master branch (through flakes):
```
❯ nix shell .#pkgs.nodePackages.terser
❯ terser --help
Usage: terser [options] [files...]
...
```

@Mic92, is this a bug worth making an issue for?

**Comment by Mic92** [comment]
This works for me:

```
$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz --builders '' -p nodePackages.tailwindcss
```

**Comment by lobre** [comment]
I confirm. From what I see, the package is included in the `nixpkgs-unstable` branch.

```
commit af0da8e2eaf7ccafba00fc778fe87ad3d7faf492
Author: Joel <joel@joel.tokyo>
Date:   Fri Dec 10 11:37:25 2021 +1000

    tailwindcss: init at 3.0.1
```

```
$ git branch --all --contains af0da8e2eaf7ccafba00fc778fe87ad3d7faf492

remotes/origin/haskell-updates
remotes/origin/master
remotes/origin/nixos-unstable
remotes/origin/nixos-unstable-small
remotes/origin/nixpkgs-unstable        <-- HERE
remotes/origin/staging
remotes/origin/staging-next
```

And the last successful build of `nixpkgs-unstable` (as reported on https://status.nixos.org/) is `c473cc8714710179df205b153f4e9fa007107ff9`.

And so `af0da8e2eaf7ccafba00fc778fe87ad3d7faf492` belongs to this build.

```
$ git log --oneline c473cc8714710179df205b153f4e9fa007107ff9 | grep af0da8e2eaf
af0da8e2eaf tailwindcss: init at 3.0.1
```

However, I still don’t see it in https://search.nixos.org

**Comment by Mic92** [comment]
I don't think search.nixos.org indexes all packages in `nodePackages` because we don't build all packages in nodePackages.
To make it show up in nixos-search, we need an alias in `all-packages.nix`. Something like:

```nix
tailwindcss = nodePackages.tailwindcss;
```

**Comment by lobre** [comment]
Are you sure about this? If I take for example `leetcode-cli`, it does not exist in `all-packages.nix` while it appears in [search.nixos.org](https://search.nixos.org).

And there are many other examples of packages that I can find in [search.nixos.org](https://search.nixos.org) belonging to `pkgs/development/node-packages/node-packages.json` and not to `all-packages.nix`.

**Comment by jyooru** [comment]
```nix
# pkgs/top-level/all-packages.nix
  nodePackages = dontRecurseIntoAttrs nodejs.pkgs;
```

I believe `dontRecurseIntoAttrs` means something along the lines of only evaluate the values you need. The packages that do show up have been evaluated because they have been aliased elsewhere or because they may be a dependency of another package that has been evaluated.

**Comment by Mic92** [comment]
> Are you sure about this? If I take for example `leetcode-cli`, it does not exist in `all-packages.nix` while it appears in [search.nixos.org](https://search.nixos.org).
> 
> And there are many other examples of packages that I can find in [search.nixos.org](https://search.nixos.org) belonging to `pkgs/development/node-packages/node-packages.json` and not to `all-packages.nix`.

looks like the import in nixos-search is broken: https://github.com/NixOS/nixos-search/runs/4521001235?check_suite_focus=true

**Comment by lobre** [comment]
Let’s first see what happens once the import is fixed then.

Thanks for creating the issue @Mic92.
