### ISSUE TITLE
calibre does not build

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#14938]
## Issue description

Recent changes in qmake configuration (I *think*) seem to have broken the build.

### Steps to reproduce

http://hydra.nixos.org/build/34856191/nixlog/2/raw has a log of a failed attempt. to build

## Technical details

* System: hydra
* Nix version: no idea
* Nixpkgs version: Don't know.

**Comment by FRidh** [comment]
There's been some changes in pyqt5, e.g. f1c2572479265d121d55d9e3270dc1ebfee4aa00

**Comment by mdorman** [comment]
I don't think the `pyqt` change is at fault.

I am fairly certain it's the `qmake` changes, because I was able to get by this first failure by adding `qmakeHook` to the build inputs---which provides the file that is otherwise missing, but then causes the configure phase to fail---and adding `dontUseQmakeConfigure` to the attributes, since calibre itself doesn't use qmake, just one of its components.

So now I've moved on to the following failure:

```
####### Building headless QPA plugin #######
Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
make: *** No rule to make target '/tmp/nix-build-calibre-2.55.0.drv-0/tmp.UOJEuKWcJ9/lib/libQt5PlatformSupport.a', needed by '/tmp/nix-build-calibre-2.55.0.drv-0/calibre-2.55.0/src/calibre/plugins/libheadless.so'.  Stop.
```

**Comment by mdorman** [comment]
So this library moved from qtbase -> qtbase-dev...but I don't have the slightest idea how to add that as a build input.

@pSub since he has done the last few releases

**Comment by vcunat** [comment]
Hydra [shows](http://hydra.nixos.org/build/34933296/nixlog/1/raw):
> Could not find qmake configuration file linux-g++.
> Error processing project file: pictureflow.pro

Perhaps @ttuegel has an idea?

**Comment by ttuegel** [comment]
The full error is
```
Could not find qmake configuration file linux-g++.
Error processing project file: pictureflow.pro
Error while executing: /nix/store/f50pcw9r6fsvmxgixfsqvh7l3m7yh8pl-qtbase-5.5.1-dev/bin/qmake pictureflow.pro
```
You must not *ever* use `${qtbase.dev}/bin/qmake`, rather you *must* use the one specified by `$QMAKE`. Are you using `qmakeHook`? That should guarantee that the correct `qmake` is first on `$PATH`.

**Comment by vcunat** [comment]
There's no explicit `qmake` call in the expression, and if I add `qmakeHook`, it fails earlier:
```
configuring
Usage: qmake [mode] [options] [files]
[...]
```

**Comment by ttuegel** [comment]
@vcunat No, so you need `dontUseQmakeConfigure = true`. According to Hydra, the builder is calling `qmake` at some point, so it needs to be set up.

**Comment by vcunat** [comment]
Nice, we back to another error :-) https://github.com/NixOS/nixpkgs/issues/7897#issue-77779716

We do have that file in `${qt55.qtbase.out}`, but somehow it isn't found.

**Comment by vcunat** [comment]
... so it apparently works to symlink the the *.a file into the place where it's looked for. That seems safe enough.

**Comment by pSub** [comment]
Thank you all for taking care of this build error!
