### ISSUE TITLE
Why does Qt 5 setup hook add all Qt modules to propagated user env packages?

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14937]
While trying to fix `dwarf-therapist` on master I ran into a strange issue. To reproduce, try building `dwarf-therapist` -- it should fail with:
```
rm: cannot remove '/nix/store/vzihksav0gb0f246ssbhx1g511n2z37k-dwarf-therapist-37.0.0/bin': Is a directory
```
Observe that the only `paths` member in `pkgs/games/dwarf-fortress/dwarf-therapist/wrapper.nix` is `dwarf-therapist-original`. To observe its contents, build `dwarf-fortress-packages.dwarf-therapist-original` -- its `bin` should contain only two files. Then, try to add `ls $out/bin` to `postBuild` in the wrapper and observe this:
```
DwarfTherapist
dwarftherapist
moc
qdbuscpp2xml
qdbusxml2cpp
qdoc
qlalr
qmake
rcc
syncqt.pl
uic
```
What happens here? Does anyone have any idea where do these files come from?

**Comment by abbradar** [comment]
cc @vcunat (you've modified it to work with multiple outputs -- maybe you have an idea?)

**Comment by vcunat** [comment]
I was following this ticket, but I've got no idea yet.

**Comment by abbradar** [comment]
I'll try to poke around with trace around the builder script (don't want to dive there yet ~_^) and see what I can find.

**Comment by abbradar** [comment]
I think [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/5.4/qtbase/setup-hook.sh#L31) in Qt 5 setup hook produces this. Still testing what happens without it. I'm not sure why is this needed; cc @ttuegel

**Comment by ttuegel** [comment]
I think the behavior of adding them all to `propagatedUserEnvPkgs` predates the multiple-outputs split. I think it should be fine to remove that, as long as they all still go into `propagatedBuildInputs`. I will check and get back to you.

**Comment by ttuegel** [comment]
Upon further investigation, we really do need to keep the `propagatedUserEnvPkgs` there. Many Qt components have dependencies they can only find at runtime. This is unfortunate, but it's the best I can do right now.

**Comment by abbradar** [comment]
Thanks for investigation! (I've forgotten about this)
