### ISSUE TITLE
gradle-2.12 not functioning

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#14931]
I can't run gradle-2.12 on NixOS 16.09pre79453.32b7b00. Here is the error I get:
```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log ou
```
Tried both with and wihtout nix-shell.

**Comment by joachifm** [comment]
I wonder if this is related to multiple-outputs. cc @NeQuissimus @Baughn

**Comment by NeQuissimus** [comment]
hmm, I would have expected this to be fixed with #14768

**Comment by joelmo** [comment]
Cherry-picked that and the previous commit to 32b7b00 and get `error: attribute ‘lib’ missing`. Will test again when this lands on unstable.

**Comment by joelmo** [comment]
gradle tried to read the library from `$HOME/.gradle`. When I removed that it is working.
