### ISSUE TITLE
Python: Flit format as alternative to setup.py

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#14945]
Flit is another method to create wheels and it's intended for small packages. 
https://github.com/takluyver/flit

It's not very common, but it starts being used, with the first relevant package being `entrypoints`, which is a dependency for `nbconvert`, and thus `notebook`, the Jupyter Notebook.

We can install Flit packages by overriding the `buildPhase` to build the wheel using Flit, or instead to just rely on the wheels provided on PyPi.
https://github.com/takluyver/entrypoints/issues/5

Important discussion on Flit and sdist/setup.py:
https://github.com/takluyver/flit/issues/74

**Comment by FRidh** [comment]
cc @domenkozar

**Comment by domenkozar** [comment]
Nice! I'll dump my thoughts there, really appreciated.

**Comment by FRidh** [comment]
Typically the wheels are published on PyPI which we can install since #15010 so closing this.

**Comment by FRidh** [comment]
In case anyone searches for it, Flit support was added in https://github.com/NixOS/nixpkgs/pull/20894.
