### ISSUE TITLE
VCVRack 2.0.2

### ISSUE THREAD

**Issue by dustinlacewell** [NixOS/nixpkgs#149427]
**Project description**
The 2.0 series of VCVRack has been released. 

I tried to simply update the git revision, but it seems some details of the build process has changed. 

Pinging @Moredread @nathyong @AndersonTorres  

**Metadata**

* homepage URL: https://vcvrack.com/
* source URL: https://github.com/VCVRack/Rack
* license: GPL3
* platforms: unix, linux, darwin

**Comment by abathur** [comment]
Looks like it was updated to a later 2.0.x release in:
- https://github.com/NixOS/nixpkgs/pull/177819
