### ISSUE TITLE
Meld(gui diff tool) requires installed dconf

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#14947]
I have use the i3wm and dconf was not installed by default.
The meld configuration can't change.
(.meld-wrapped:6905): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files

After installing dconf the meld working fine.
### Steps to reproduce

Run meld without dconf installed;
- System: 16.03.526.567b65d (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.03.526.567b65d"

**Comment by vcunat** [comment]
I suppose wrapping the meld executable should solve this.

**Comment by mimadrid** [comment]
Please @danykey,  try with #17376 
Thanks in advance.
