### ISSUE TITLE
NixOS manual should always use correct NixOS version

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14946]
Quoting from the manual (https://nixos.org/releases/nixos/16.03/nixos-16.03.616.4ac4b35/manual/index.html):

```
It’s often inconvenient to develop directly on the master branch, since if somebody has just committed (say) a change to GCC, then the binary cache may not have caught up yet and you’ll have to rebuild everything from source. So you may want to create a local branch based on your current NixOS version:

$ nixos-version
14.04.273.ea1952b (Baboon)
```

As a user I would expect to see outputs which I will actually see on my system (which is what the text suggests). While it is perfectly obvious how to interpret this, I would like to see manuals which are correct. So, in this case I would refer to some 16.X version. 

A solution is to automatically insert the right versions in some documentation build process.

**Comment by joachifm** [comment]
Would you mind using a more specific issue title?

I don't agree that the manual is "wrong", but inserting the current git version at build-time seems simple enough and it does add that little bit of extra polish.

**Comment by bobvanderlinden** [comment]
The offending line is here: https://github.com/NixOS/nixpkgs/blob/25387a1bedefb391db9f8585cfa1d160fc3bacfe/nixos/doc/manual/development/sources.xml#L42

Some kind of variable for the version/commitsha would be nice, but I don't see any variables being used anywhere else in the manual. It seems that [the nix expression for the manual](https://github.com/NixOS/nixpkgs/blob/25387a1bedefb391db9f8585cfa1d160fc3bacfe/nixos/doc/manual/default.nix#L100) also doesn't have any variables. I'm guessing they need to be introduced?

Or should the manual stay static and just update it for now?

**Comment by vcunat** [comment]
It has version and hash in the (sub-)title... and to be honest I personally don't much like that dependency, as whenever I add a commit locally, the manual gets rebuilt and in consequence also e.g. whole system path (huge forest of symlinks). It seems a waste.

**Comment by grahamc** [comment]
Perhaps adding `For example:` would improve this?

**Comment by Profpatsch** [comment]
triage: status?

**Comment by FliegendeWurst** [comment]
Doesn't seem worth it to implement this suggestion.
