### ISSUE TITLE
Fontconfig broken in NixOS 21.11

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nixpkgs#149462]
Since version `2.13.94`, fontconfig fails to detect all variations/weights for some fonts.
I've noticed this because fonts failed to render correctly after upgrading to NixOS 21.11.

I've filed an [upstream bug report](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/303), which contains a Nix-based [repro script](https://gist.github.com/erikarvstedt/10eb1a55f1eab6ae0fa77df290b51334).

We should revert to version `2.13.93` until this is fixed.

cc @jtojnar @andresilva

**Comment by andresilva** [comment]
Reverting to `2.13.93` will cause even more problems (e.g. https://github.com/NixOS/nixpkgs/issues/129733), so if we really need to revert we should probably use `2.13.92` (although other stuff might get broken anyway 🤷). I no longer remember the details but I think [this](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/277) is the reason `2.13.93` broke a lot of things.

**Comment by jtojnar** [comment]
I think this is too minor bug to revert, especially since the previous versions had other bugs too. I have bisected fontconfig to the precise commit causing it so hopefully Akira will come up with a fix soon.

**Comment by erikarvstedt** [comment]
This bug has now been [fixed upstream](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/92fbf14b0d7c4737ffe1e8326b7ab8ffae5548c3).
Can I add the patch to our fontconfig pkg?

**Comment by jtojnar** [comment]
Yes please.

**Comment by erikarvstedt** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/149851.
