### ISSUE TITLE
GDM failing to start on boot: white screen, "Please contact a system administrator"

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#149539]
### Steps To Reproduce

My machine:
* runs NixOS on bc5d68306b40b8522ffb69ba6cff91898c2fbbff
* has a discrete AMD card, and an integrated Intel card
* runs impermanence, with no /var persisted between boots

The machine's relevant config is:
```
{ pkgs, lib, config, ... }:
{
  imports =
    [
      "${nixos-hardware}/common/cpu/intel"
      "${nixos-hardware}/common/gpu/amd"
    ];

    services.xserver = {
      enable = true;
      displayManager.gdm.enable = true;
      displayManager.gdm.debug = true;
      desktopManager.gnome3.enable = true;
    };
}
```
Boot machine.

It fails. Only known workaround is to boot to an earlier generation.

### Expected behavior
I expected the machine to boot GDM and be able to log in to GNOME.

### Screenshots

This is what is displayed at boot, after the usual kernel/systemd logs:

![signal-2021-12-08-173042](https://user-images.githubusercontent.com/61303/145160279-874005ce-3014-4a46-9591-4bd36aebd69c.jpeg)

### Additional context

GDM debug logs: https://pastebin.com/sYvNhmHC

### Notify maintainers
@hedning @jtojnar @dasj19 @maxeaubrey 

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module: gdm
```

**Comment by tomfitzhenry** [comment]
Per "Dec 08 17:21:57 mymachine gdm[2218]: Gdm: Child process -2238 was already dead." in https://pastebin.com/sYvNhmHC, this might be related to https://github.com/NixOS/nixpkgs/issues/149537.

**Comment by jtojnar** [comment]
Hmm, the only thing I see is “Session never registered, failing”, could you please also try `services.xserver.desktopManager.gnome3.debug = true;`

**Comment by jtojnar** [comment]
Also, do you by chance know what commit of Nixpkgs the previous working derivation was?

**Comment by tomfitzhenry** [comment]
> Also, do you by chance know what commit of Nixpkgs the previous working derivation was?

Yes: 09a54b14cd1abb87c7f9e5357cd0030f9d8aefda.

I will try with `services.xserver.desktopManager.gnome3.debug = true;`.

**Comment by tomfitzhenry** [comment]
> Hmm, the only thing I see is “Session never registered, failing”, could you please also try services.xserver.desktopManager.gnome3.debug = true;

Done.

`journalctl -u display-manager.service`: https://pastebin.com/cac08hgh

`journalctl -u session-c1.scope`: https://pastebin.com/tv170GEX

**Comment by tomfitzhenry** [comment]
For comparison, here are the same logs for a working boot (on 09a54b14cd1abb87c7f9e5357cd0030f9d8aefda):

session-c1.scope: https://pastebin.com/DgHYD09m
display-manager.service: https://pastebin.com/tAKuDJsy

**Comment by jtojnar** [comment]
```
Dec 08 18:23:28 mymachine /nix/store/8c92zvlflv5gka582d5svbmbvmyww03q-gdm-41.0/libexec/gdm-wayland-session[2229]: gnome-session-binary[2229]: WARNING: Failed to upload environment to systemd: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.freedesktop.systemd1" does not exist
```
is suspicious but I can see it in the working log too.

But I would still try [early KMS](https://wiki.archlinux.org/title/Kernel_mode_setting#Early_KMS_start) per the suggestion in https://bbs.archlinux.org/viewtopic.php?id=262221 (I think the corresponding thing would be `boot.initrd.availableKernelModules`.)

Also there is this issue, not sure if related https://github.com/NixOS/nixpkgs/issues/103746

**Comment by tomfitzhenry** [comment]
> But I would still try early KMS per the suggestion in https://bbs.archlinux.org/viewtopic.php?id=262221 (I think the corresponding thing would be boot.initrd.availableKernelModules.)

Per https://github.com/NixOS/nixos-hardware/blob/4c9f07277bd4bc29a051ff2a0ca58c6403e3881a/common/gpu/amd/default.nix#L4 , nixos-hardware (which I use) sets `boot.initrd.kernelModules` correctly.

Per https://github.com/NixOS/nixpkgs/blob/2a512fa1be4516cf4131ec392ec5ac3d84e80dbf/nixos/modules/system/boot/stage-1.nix#L22 , either `boot.initrd.kernelModules` or `boot.initrd.availableKernelModules` is sufficient.

> Also there is this issue, not sure if related #103746

I tried the workaround in https://github.com/NixOS/nixpkgs/issues/103746#issuecomment-945091229 but this did not change the behaviour.

I will try to:
* build a minimal failing machine
* look for potentially breaking commits
* rig a bisect using https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/gnome.nix ? I suspect my issue is partly related to my hardware, and thus this wouldn't find it.

**Comment by jtojnar** [comment]
At worst, it should also be possible to bisect on live machine (though there is 11 steps between bc5d683 and 09a54b1 so it might take a while).

**Comment by andir** [comment]
I am seeing the exact same issue on my AMD notebook. We can cut down two bisect steps as I can report that with 6daa4a5c045d40e6eae60a3b6e427e8700f1c07f it was still working fine.

**Comment by jtojnar** [comment]
I can actually reproduce on intel/nouveau system too. Also works for me on  6daa4a5.

**Comment by jtojnar** [comment]
I can also reproduce in the following VM (built using `nixos-rebuild build-vm -I nixpkgs=$PWD -I nixos-config=../nix-playground/gdm-fail.nix` executed using `env QEMU_NET_OPTS="hostfwd=tcp::2222-:22" result/bin/run-*-vm`):

```nix
{ pkgs, config, ... }: {
  environment.systemPackages = with pkgs; [
    gdb
    binutils # readelf
    file
    htop
    less
  ];
  services.gnome.core-utilities.enable = false;
  environment.enableDebugInfo = true;
  services.xserver = {
    enable = true;
    layout = "cz";
    xkbVariant = "qwerty";

    displayManager.gdm = {
      enable = true;
      debug = true;
    };
    desktopManager.gnome = {
      enable = true;
      debug = true;
    };
  };
  services.openssh.enable = true;

  console.useXkbConfig = true;
  i18n = {
    defaultLocale = "en_UK.UTF-8";
  };

  users.extraUsers.jtojnar = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = [ "wheel" "networkmanager" ];
    password = "";
    openssh.authorizedKeys.keys = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYbOlZydfRRCGCT08wdtPcpfSrgxMc6weDx3NcWrnMpVgxnMs3HozzkaS/hbcZUocn7XbCOyaxEd1O8Fuaw4JXpUBcMetpPXkQC+bZHQ3YsZZyzVgCXFPRF88QQj0nR7YVE1AeAifjk3TCODstTxit868V1639/TVIi5y5fC0/VbYG2Lt4AadNH67bRv8YiO3iTsHQoZPKD1nxA7yANHCuw38bGTHRhsxeVD+72ThbsYSZeA9dBrzACpEdnwyXclaoyIOnKdN224tu4+4ytgH/vH/uoUfL8SmzzIDvwZ4Ba2yHhZHs5iwsVjTvLe7jjE6I1u8qY7X8ofnanfNcsmz/ jtojnar@kaiser" ];
  };
  virtualisation.memorySize = 2048;
  virtualisation.diskSize = 28048;
  virtualisation.qemu.options = [ "-device intel-hda" "-device hda-duplex" ];

  environment.etc."modprobe.d/floppy.blacklist.conf".text = ''
    blacklist floppy
  '';
}
```

**Comment by andir** [comment]
Shouldn't this be also caught by our VM test?

**Comment by andir** [comment]
As far as I can tell this issue was introduced with abfcb79abf3ba32eb4719c48915a143370093fb7

**Comment by andir** [comment]
As far as I can tell this issue was introduced with abfcb79abf3ba32eb4719c48915a143370093fb7

> As far as I can tell this issue was introduced with [abfcb79](https://github.com/NixOS/nixpkgs/commit/abfcb79abf3ba32eb4719c48915a143370093fb7)

Yep, reverting the commit allows me to boot into my system again.

**Comment by jtojnar** [comment]
Thanks. I can also confirm that, reverted for now.

That the tests cannot reproduce it is weird. And also since `environment.sessionVariables` should be merged into `environment.variables`:

https://github.com/NixOS/nixpkgs/blob/bcb4b714bdddec94d88ff974f242cdb3f3308dac/nixos/modules/config/shells-environment.nix#L172

cc @ncfavier

**Comment by tomfitzhenry** [comment]
Thanks for the diagnosis @jtojnar and @andir.

I can confirm this fixed my issue too.

**Comment by wllianwd** [comment]
Hey peeps, I can see this was fixed but I still get the same error, what needs to be done to fix?
Here my flake: https://github.com/wllianwd/my-nix-os/blob/main/flake.nix
And I'm updating the system using 
`nix flake update
sudo nixos-rebuild switch --flake .#`

**Comment by ncfavier** [comment]
This was fixed in master but nixos-unstable hasn't caught up yet (you can see [here](https://status.nixos.org/) that it was last updated two days ago).

**Comment by dcarosone** [comment]
The build has updated, but unfortunately the new one 581d2d6c9cd5 also *just* missed out this fix, so you will have to wait for the next.

![image](https://user-images.githubusercontent.com/11495017/145505370-07fa58b9-d503-4813-9248-6b7b35452b68.png)

**Comment by baracoder** [comment]
Or alternatively override the input referencing the fix commit bcb4b714bdddec94d88ff974f242cdb3f3308dac:
```
nix flake update --override-input nixpkgs 'https://github.com/NixOS/nixpkgs/archive/bcb4b714bdddec94d88ff974f242cdb3f3308dac.tar.gz'
sudo nixos-rebuild switch --flake .
```

**Comment by bbigras** [comment]
> nix flake update --override-input nixpkgs 'https://github.com/NixOS/nixpkgs/archive/bcb4b714bdddec94d88ff974f242cdb3f3308dac.tar.gz'

Or `nix flake update --override-input nixpkgs nixpkgs/bcb4b714bdddec94d88ff974f242cdb3f3308dac` :)

but thanks :+1:

**Comment by ncfavier** [comment]
It seems like this is related to dconf: commenting out the `environment.sessionVariables.GIO_EXTRA_MODULES` line in `dconf.nix` fixes the crash, as does removing the [`programs.dconf.profiles.gdm`](https://github.com/NixOS/nixpkgs/blob/a61fb15dd8a410ad6a77f2e804d5f01d11e823b0/nixos/modules/services/x11/display-managers/gdm.nix#L248-L281) block in `gdm.nix`.

Also, the successful logs contain the lines

```
Dec 11 10:07:31 nixos /nix/store/8c92zvlflv5gka582d5svbmbvmyww03q-gdm-41.0/libexec/gdm-wayland-session[898]: gnome-session-binary[898]: GLib-GIO-DEBUG(+): _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
Dec 11 10:07:31 nixos gnome-session-binary[898]: GLib-GIO-DEBUG(+): _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
```

while the failing logs contain

```
Dec 11 10:10:24 nixos /nix/store/8c92zvlflv5gka582d5svbmbvmyww03q-gdm-41.0/libexec/gdm-wayland-session[959]: gnome-session-binary[959]: GLib-GIO-DEBUG(+): _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
Dec 11 10:10:24 nixos gnome-session-binary[959]: GLib-GIO-DEBUG(+): _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
```

I don't know enough about the GNOME ecosystem to know what to do with this information.

**Comment by jtojnar** [comment]
Interesting. Possibly it tries to use dconf without the daemon running? Would expect more info about that in the logs if that is the case, though.

**Comment by ncfavier** [comment]
I've opened an issue upstream with all the information I have: https://gitlab.gnome.org/GNOME/gdm/-/issues/756

It turns out the crash doesn't happen if autologin is enabled, which is why the tests didn't catch it. I'll see if I can come up with a standalone GDM test that doesn't use autologin.
