### ISSUE TITLE
No UEFI installer tests

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nixpkgs#14956]
At the moment there are no UEFI installer tests. These were removed previously because they were broken at the time (https://github.com/NixOS/nixpkgs/commit/92837f2dbf2bf3691f3f82548ed29ce6cd79155d). @domenkozar raised the issue in #14902. [There are quite a few installer tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/installer.nix) at the moment, but none of them use GPT and none of them use Gummiboot. UEFI is probably being used quite a lot nowadays, so automated tests seem appropriate.

There are however tests that cover booting the ISO using UEFI, but they aren't being used to actually install a NixOS system. They do not cover a separate boot partition with GPT and do not cover generating Gummiboot configuration.

**Comment by dezgeg** [comment]
Here is one for Gummiboot: #14957.

I'm not an UEFI expert, reviews welcome.

**Comment by copumpkin** [comment]
Hasn't gummiboot been renamed to systemd-boot?

**Comment by dezgeg** [comment]
Yes, but we don't use it (yet).
