### ISSUE TITLE
google-chrome-stable has an invalid sha256 hash

### ISSUE THREAD

**Issue by nkaretnikov** [NixOS/nixpkgs#14961]
## Issue description

While running `nixos-rebuild switch --upgrade`:

```
[...]
curl: (22) The requested URL returned error: 404 Not Found

trying http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_49.0.2623.87-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found

trying http://repo.fdzh.org/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_49.0.2623.87-1_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    261      0 --:--:-- --:--:-- --:--:--   262
100   161  100   161    0     0     76      0  0:00:02  0:00:02 --:--:--   133
100 5880k  100 5880k    0     0   887k      0  0:00:06  0:00:06 --:--:-- 1570k
output path ‘/nix/store/w21wkbwp951xjfs4bhc8lx0kszhrq6ks-google-chrome-stable_49.0.2623.87-1_amd64.deb’ should have sha256 hash ‘1k6nhccdqzzzicwi07nldqfsdlic65i2xfyb7dbasbbg9zl3s9yw’, instead has ‘1hhrxx0qgmircanmnpwsqpwl7y04qz98nj7h3bsk1ib5jrwx9w1m’
building path(s) ‘/nix/store/04kp3dg9qh38im6q8ygdkygsp02q42j8-chfn.pam’
```

Is this a malicious or broken mirror? Should it be removed?

**Comment by puffnfresh** [comment]
Just got the same thing and I think with the same mirror.

**Comment by joachifm** [comment]
Something is amiss, the download is way smaller than it ought to be. Upstream .deb is ~50MB

**Comment by colemickens** [comment]
That mirror is regularly excruciatingly slow for me. I used to have it patched out.

**Comment by msteen** [comment]
The the source of Google Chrome is defined by the Chromium package, which was already using it to extract its plugins from. So as far as I know, the source of this issues lies with the deb mirrors [as defined in update.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/update.nix) of the Chromium package.

**Comment by vcunat** [comment]
So, /cc @aszlig as well, I guess.

**Comment by msteen** [comment]
It is unfortunate that Google does not keep the two previous versions around, but instead drops the previous version as soon as a new version arises. I tried to find other mirrors, but so far I have only found one that does not keep the same directory structure as the rest:
http://www.ubuntuupdates.org/pm/google-chrome-stable

**Comment by yamafaktory** [comment]
Hi, I am facing the same issue. Is there any workaround?

**Comment by vcunat** [comment]
This should be long resolved / outdated.
