### ISSUE TITLE
KWin crashes on first boot in virtualbox image

### ISSUE THREAD

**Issue by brainrape** [NixOS/nixpkgs#14972]
## Issue description

On graphical login to a fresh virtualbox image, KWin crashes with a floating point error. 
It does not happen on subsequent logins.
### Steps to reproduce
1. Download VirtualBox appliance, in my case: http://releases.nixos.org/nixos/16.03/nixos-16.03.616.4ac4b35/nixos-16.03.616.4ac4b35-x86_64-linux.ova
2. Import appliance in virtualbox (I used default settings) and start it
3. log in to the graphical session with user: demo, password: demo
   The KDE Crash handler appears, reporting that KWin crashed with a floating point error
   After installing gdb, here's the debug info:
   [kwin-20160425-140846.kcrash.txt](https://github.com/NixOS/nixpkgs/files/234705/kwin-20160425-140846.kcrash.txt)
## Technical details
- System: NixOS 16.03.616.4ac4b35 (Emu)
- Nix version: 1.11.2
- Nixpkgs version: 16.03.616.4ac4b35

**Comment by ttuegel** [comment]
This is fixed now, but please ping me if it recurs.
