### ISSUE TITLE
dstp: 0.3.0 -> 0.4.0

### ISSUE THREAD

**Issue by ycd** [NixOS/nixpkgs#149707]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: dstp

current version: 0.3.0
desired version: 0.4.0

###### Notify maintainers

maintainers: @jlesquembre

###### Note for maintainers

I'd love to update the package myself without annoying you :) 

If there is a documentation about how to upgrade packages, i'd love to learn it and try my best next time, thanks in advance!

**Comment by sikmir** [comment]
> If there is a documentation about how to upgrade packages, i'd love to learn it and try my best next time, thanks in advance!

https://nixos.org/manual/nixpkgs/stable/#chap-submitting-changes

**Comment by jlesquembre** [comment]
> If there is a documentation about how to upgrade packages, i'd love to learn it and try my best next time, thanks in advance!
 
For simple version updates, I update the version number and to get the new hash I run (in the nixpkgs top directory):

```
nix-prefetch-url -A dstp.src
```

For go packages, we also have to update the `vendorSha256` hash, that one is tricky, and what I do is to try to build the package. That will fail, but it gives us the new hash, I don't know a better way. 

```
nix-build '<nixpkgs>' -A dstp
# or
nix-shell -p dstp 
```

There is also a bot (https://github.com/r-ryantm) creating PR for those simple version updates. It uses repology to find the latest version: https://repology.org/project/dstp/versions

**Comment by ycd** [comment]
Awesome, thanks!
