### ISSUE TITLE
command-not-found is missing programs.sqlite

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#14987]
## Issue description

I think this problem has appeared relatively recently.

### Steps to reproduce

```bash
$ nix-channel --list
nixos https://nixos.org/channels/nixos-unstable
$ cat /nix/var/nix/profiles/per-user/root/channels/nixos/.git-revision 
32b7b0009f168cb7e020d297c2f336ef352e9ec1
$ command-not-found tar
DBI connect('dbname=/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite','',...) failed: unable to open database file at /run/current-system/sw/bin/command-not-found line 13.
```

## Technical details

* System: 16.09.git.48c3ea7 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.48c3ea7

**Comment by cstrahan** [comment]
See also:

* https://github.com/NixOS/nixos-channel-scripts/issues/4
* https://github.com/NixOS/nixpkgs/issues/12044
* http://stackoverflow.com/questions/36153603/command-not-found-not-working-because-programs-sqlite-is-missing

**Comment by obadz** [comment]
Thanks
