### ISSUE TITLE
nixos-option returns the wrong values.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#149891]
### Describe the bug
For example: ``cat /etc/hostname`` gives the correct hostname, but ``nixos-option networking.hostName`` returns the hostname of another config of this machine.

### Steps To Reproduce
I'm not sure how to reproduce this.

### Additional context
I run a kind of dual boot system; one config is focused on battery life, the other on real-time audio.
The wrong values (hostname is just one example), come from the other config.

### Notify maintainers
@chkno  

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.21, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(bart): `""`
 - channels(root): `"nixos-22.05pre336298.bc5d68306b4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
nixos-option uses either the 
```
NIXOS_CONFIG
    Path to the main NixOS configuration module. Defaults to /etc/nixos/configuration.nix.
```
env var to find the config 

or
```
-I path
    This option is passed to the underlying nix-instantiate invocation.
```
example `-I nixos-config=something.nix`

or the nixos-config in $NIX_PATH which is the default one thats set
```
/home/user/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
```

**Comment by magnetophon** [comment]
aha, now it all makes sense again.
Thanks!
