### ISSUE TITLE
biber is broken

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#14986]
## Issue description

`biber` doesn't build now on NixOS because it doesn't install anything to `$docdev` output. Looks like `buildPerlPackage` [expects](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/perl-modules/generic/default.nix) that all packages should install something to it. I'm not familiar with Perl ecosystem at all -- how should this be fixed?

cc @vcunat

**Comment by vcunat** [comment]
You simply define `outputs` explicitly. I had fixed a few already around ecf75f1b4f.

**Comment by abbradar** [comment]
Fast, thanks! Now just https://github.com/NixOS/nixpkgs/issues/14937 remained until I can finally switch my configuration to post-multiple-outputs ~_^.
