### ISSUE TITLE
x265: 3.4 -> 3.5

### ISSUE THREAD

**Issue by lunik1** [NixOS/nixpkgs#149817]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: x265

current version: 3.4
desired version: 3.5

###### Notify maintainers

maintainers: @codyopel

###### Note for maintainers

Please tag this issue in your PR.

**Comment by c0bw3b** [comment]
I'm working on this
