### ISSUE TITLE
papermc: 1.17.1r97 -> 1.17.1r398

### ISSUE THREAD

**Issue by jyooru** [NixOS/nixpkgs#149983]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: papermc

current version: 1.17.1r97
desired version: 1.17.1r398

###### Notify maintainers

maintainers: @aaronjanse @neonfuz 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by aaronjanse** [comment]
Oh yikes! I'm working on a PR right now. Thank you @jyooru for the heads up

**Comment by neonfuz** [comment]
These version bumps are a never ending task, unfortunately papermc doesn't have a concept of a slower updating stable channel. I made an auto updating version, it's a bit rough (it auto updates on every start), but I think some people would like it so maybe I'll make a PR soon
