### ISSUE TITLE
VUE is slower/buggier with openjdk8.jre, as compared to oraclejre8

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#14998]
`vue` is  slower and with the default JRE (which is `openjdk8.jre`), as compared to `oraclejre8`.
1. The speed differences manifest themselves with larger diagrams.
2. The font rendering / box sizing is systematically wrong with openjdk.

I understand that the Oracle option requires a clickthrough.  Shouldn't we think of what  can be done to improve the end user experience?

Warning the user, that VUE is less practical with openjdk?

**Comment by zimbatm** [comment]
I think it's always the case the openjdk is less stable and fast than the oracle alternative. Not really sure what we can do about it.

**Comment by Profpatsch** [comment]
Closing, since there seems to be nothing practical that can be done.
