### ISSUE TITLE
Service Jenkins fails to start (timeout, killed by systemd)

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#14991]
```
nixos-rebuild switch                                                                                                                                      
building Nix...
building the system configuration...
trace: warning: passing a comma-separated string for filesystem options is deprecated; use a list of strings instead. This will become a hard error in 16.09.
trace: warning: passing a comma-separated string for filesystem options is deprecated; use a list of strings instead. This will become a hard error in 16.09.
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
warning: the following units failed: jenkins.service

● jenkins.service - Jenkins Continuous Integration Server
   Loaded: loaded (/nix/store/ynj2nllwxjmib7absfwj0dwgkphnsphl-unit-jenkins.service/jenkins.service; bad; vendor preset: enabled)
   Active: failed (Result: timeout) since Tue 2016-04-26 00:01:17 CEST; 40ms ago
  Process: 4231 ExecStartPost=/nix/store/jgkrq62n5kg0cjxbhsnwf6v6kpaqf8fg-unit-script/bin/jenkins-post-start (code=killed, signal=TERM)
  Process: 4230 ExecStart=/nix/store/z1q7brjws210cl43jvw7g83p3fndriq0-unit-script/bin/jenkins-start (code=killed, signal=TERM)
  Process: 4225 ExecStartPre=/nix/store/zm7ys3hhbzgycfz58f0zh8a9dx5dz8w7-unit-script/bin/jenkins-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 4230 (code=killed, signal=TERM)

nixos jenkins-start[4230]: Apr 26, 2016 12:01:01 AM jenkins.InitReactorRunner$1 onAttained
nixos jenkins-start[4230]: INFO: Loaded all jobs
nixos jenkins-start[4230]: Apr 26, 2016 12:01:01 AM jenkins.InitReactorRunner$1 onAttained
nixos jenkins-start[4230]: INFO: Completed initialization
nixos jenkins-start[4230]: Apr 26, 2016 12:01:01 AM hudson.WebAppMain$3 run
nixos jenkins-start[4230]: INFO: Jenkins is fully up and running
nixos systemd[1]: jenkins.service: Start-post operation timed out. Stopping.
nixos systemd[1]: Failed to start Jenkins Continuous Integration Server.
nixos systemd[1]: jenkins.service: Unit entered failed state.
nixos systemd[1]: jenkins.service: Failed with result 'timeout'.
warning: error(s) occurred while switching to the new configuration
```

```
# relevant configuration
services.jenkins.enable = true;
services.jenkins.listenAddress = "localhost";
services.jenkins.prefix = "/jenkins";
```

**Comment by bjornfor** [comment]
Hm, so that means [this code](https://github.com/NixOS/nixpkgs/blob/release-16.03/nixos/modules/services/continuous-integration/jenkins/default.nix#L163-175) never finishes. Pasted here for reference:

```
  postStart = ''
    until ${pkgs.curl}/bin/curl -s -L ${cfg.listenAddress}:${toString cfg.port}${cfg.prefix} ; do
      sleep 10
    done
    while true ; do
      index=`${pkgs.curl}/bin/curl -s -L ${cfg.listenAddress}:${toString cfg.port}${cfg.prefix}`
      if [[ !("$index" =~ 'Please wait while Jenkins is restarting' ||
              "$index" =~ 'Please wait while Jenkins is getting ready to work') ]]; then
        exit 0
      fi
      sleep 30
    done
  '';
```

I'd try running those curl commands manually, while jenkins starts up, and hope it gives some hints on what's wrong.

FYI, I'm at NixOS 16.03.657.0c12bab and Jenkins works for me. My config:

```
services.jenkins = {
    enable = true;
    port = 5000;
    extraOptions = [ "--httpListenAddress=127.0.0.1" ];
   ...
}
```

**Comment by 0xABAB** [comment]
Looks as broken as ever from here:

```
# 16.03.678.2597f52 (Emu) 

services.jenkins = {
    enable = true;
    port = 5000;
    extraOptions = [ "--httpListenAddress=127.0.0.1" ];
};
```

returns 

```
● jenkins.service - Jenkins Continuous Integration Server
   Loaded: loaded (/nix/store/g65iqacwkpllifmpvj1l8anaf8jaq3lx-unit-jenkins.service/jenkins.service; bad; vendor preset: enabled)
   Active: failed (Result: timeout) since Sun 2016-05-01 23:06:16 CEST; 47ms ago
  Process: 18065 ExecStartPost=/nix/store/hkc5xhmp2i7lsvsdyrsvklmfymgzfmsf-unit-script/bin/jenkins-post-start (code=killed, signal=TERM)
  Process: 18064 ExecStart=/nix/store/jnsm46g9wy27n93wfpxrwahafh7221ky-unit-script/bin/jenkins-start (code=exited, status=0/SUCCESS)
  Process: 18059 ExecStartPre=/nix/store/zm7ys3hhbzgycfz58f0zh8a9dx5dz8w7-unit-script/bin/jenkins-pre-start (code=exited, status=0/SUCCESS)
 Main PID: 18064 (code=exited, status=0/SUCCESS)

May 01 23:04:55 nixos jenkins-start[18064]:         at jenkins.InitReactorRunner.run(InitReactorRunner.java:44)
May 01 23:04:55 nixos jenkins-start[18064]:         at jenkins.model.Jenkins.executeReactor(Jenkins.java:935)
May 01 23:04:55 nixos jenkins-start[18064]:         at jenkins.model.Jenkins.<init>(Jenkins.java:816)
May 01 23:04:55 nixos jenkins-start[18064]:         at hudson.model.Hudson.<init>(Hudson.java:83)
May 01 23:04:55 nixos jenkins-start[18064]:         at hudson.model.Hudson.<init>(Hudson.java:79)
May 01 23:04:55 nixos jenkins-start[18064]:         at hudson.WebAppMain$3.run(WebAppMain.java:225)
May 01 23:06:16 nixos systemd[1]: jenkins.service: Start-post operation timed out. Stopping.
May 01 23:06:16 nixos systemd[1]: Failed to start Jenkins Continuous Integration Server.
May 01 23:06:16 nixos systemd[1]: jenkins.service: Unit entered failed state.
May 01 23:06:16 nixos systemd[1]: jenkins.service: Failed with result 'timeout'.
warning: error(s) occurred while switching to the new configuration
```

**Comment by 0xABAB** [comment]
It seems Jenkins is downloading some stuff which might take longer than the allowed timeout. In short, the timeout makes assumptions which are wrong. It is very much possible that multiple of such actions are responsible for an overall exceeding of the timeout. 

What is the global timeout which is killing the above script essentially? A correct timeout script should depend on the service being deployed. 

So, however the timeout works now, it most likely is completely broken. What is the point of a nice configuration management system, when all the configuration automation is broken? 

```
jenkins-start[21515]: INFO: Finished Download metadata. 7,372 ms
```

Additionally, there is the following log information (note the last line (!)):

```
May 01 23:34:20 nixos jenkins-start[21838]: INFO: Augmented all extensions
May 01 23:34:25 nixos jenkins-start[21838]: May 01, 2016 11:34:25 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:25 nixos jenkins-start[21838]: INFO: Loaded all jobs
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM hudson.model.AsyncPeriodicWork$1 run
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Started Download metadata
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM hudson.model.AsyncPeriodicWork$1 run
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Finished Download metadata. 8 ms
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM org.jenkinsci.main.modules.sshd.SSHD start
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Started SSHD at port 45415
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Completed initialization
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Started initialization
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Listed all plugins
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Prepared all plugins
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Started all plugins
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Augmented all extensions
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Loaded all jobs
May 01 23:34:26 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM jenkins.InitReactorRunner$1 onAttained
May 01 23:34:26 nixos jenkins-start[21838]: INFO: Completed initialization
May 01 23:34:27 nixos jenkins-start[21838]: May 01, 2016 11:34:26 PM hudson.WebAppMain$3 run
May 01 23:34:27 nixos jenkins-start[21838]: INFO: Jenkins is fully up and running
```

So, despite it is "fully up and running", it is killed shortly afterwards. Great!

**Comment by bjornfor** [comment]
That looks different, doesn't it? It looks like a call stack traceback. Please paste the whole traceback. (Pass -n100 or something to get more log lines.)

**Comment by bjornfor** [comment]
(I had old browser cache, didn't see your update before posting. On phone, bbl.)

**Comment by bjornfor** [comment]
I see two ways forward:

* Increase the service timeout. (The NixOS test even sets the service startup timeout to 6 min.)
* Let the service enter "started" state earlier. Just wait until it responds to HTTP requests, don't wait until it reports that it's _fully_ up (idle).

I ran the NixOS test for Jenkins (```cd nixos/tests/ && nix-build jenkins.nix```) and found that the time between "Started Download metadata" and "Jenkins is fully up and running" is about 1 second. But the service isn't in "started" state until about 30 seconds later. Overall, it took about one minute on my system from systemd started jenkins until it actually became "started".

**Comment by 0xABAB** [comment]
@bjornfor Can I modify these values somewhere myself or are they builtins somewhere? 

Having different higher test than production timeouts seems rather silly, IMHO. Good investigation.

**Comment by bjornfor** [comment]
The 1.5 min timeout is systemd default value, I think. You can override it in your configuration.nix file like the NixOS test does (ref. https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/jenkins.nix): 

```systemd.services.jenkins.serviceConfig.TimeoutStartSec = "6min";```

I guess I agree that it's bad to have different value for tests and non-tests, but on the other hand, the test farm is generally overloaded and things take a lot longer time on it than typical user systems (in my experience). My 3.5+ years old Intel Core i5 PC managed to start the Jenkins service in the NixOS VM tests in just under a minute (not comfortably within limits, but worked).

Pinging @roconnor (Jenkins module author) for opinion on whether to extend timeout or to say that Jenkins is "started" as soon as it responds to HTTP requests, instead of waiting until it is idle (AFAICT).

**Comment by bjornfor** [comment]
Oops, I think I pinged wrong person, I meant @coreyoconnor.

**Comment by coreyoconnor** [comment]
My opinion is: say jenkins is "started" as soon as it responds to HTTP requests.

A few reasons:

0. Repeatedly curling for a specific human-readable string to determine "Active" is fragile. For instance, what happens when jenkins is localized?
1. The time jenkins takes to initializes is variable. This (at least used to) depend on the number of jobs and any plugin upgrades requested.
2. Jenkins can be requested to restart from the UI. Which will not affect the status of the service. This means that the service being "active" does not imply jenkins is initialized. Downstream services cannot assume jenkins is initialized if the service is active. Might as well accept that and remove the initialized test from service startup.

**Comment by 0xABAB** [comment]
I am not much of a systemd expert, but if the intention is that systemd reflects some kind of useful status, then that's what should be integrated via some hooks. 

I do also agree that this would not be in the scope of this issue.

From @coreyoconnor's reaction, 3 does put a nail in the coffin of this particular feature.  

I would probably never depend on systemd completely, but it would be nice if one could depend on it for such notifications. 

With @bjornfor's suggestions, I got it running.

**Comment by bjornfor** [comment]
I'm preparing a patch to remove the curl command that parse the index page from Jenkins.

**Comment by hestela** [comment]
Is there a way to disable postStart? The wait/curl never seems to complete with my nginx reverse proxy and https only setup. Jenkins starts up correctly and it works well until the post start script causes systemd to timeout and kill jenkins.

**Comment by bjornfor** [comment]
Try ```systemd.services.jenkins.postStart = lib.mkForce "";```.
