### ISSUE TITLE
Firefox segfaults when deleting bookmarks.

### ISSUE THREAD

**Issue by quantmint** [NixOS/nixpkgs#150030]
### Describe the bug
Firefox crashes with segmentation fault
### Steps To Reproduce
Open a new tab
Then open the bookmarks toobar with CTRL + B
Right click a bookmark and delete it.
Firefox crashes
### Expected behavior
It should not crash

### Additional context
This happened after updating firefox from 94.0.2 to 95

I am using firefox on sway running it with MOZ_ENABLE_WAYLAND=1.

### Notify maintainers

@edolstra 
@lovesegfault 
@mweinelt 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.6-xanmod2-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre337103.581d2d6c9cd, home-manager"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by mweinelt** [comment]
I can't reproduce this with firefox-wayland 95.0 on unstable.

**Comment by quantmint** [comment]
This somehow decided to fix itself without any apparent reason.
