### ISSUE TITLE
Hipchat is missing libstdc++.so.6

### ISSUE THREAD

**Issue by manveru** [NixOS/nixpkgs#15013]
## Issue description

Trying to start hipchat, you get following error:

    /nix/store/nd76wygl7xmg7gsix33s13zycr492lmn-hipchat-4.0.1631/libexec/hipchat/lib/HipChat.bin: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

### Steps to reproduce

    hipchat

I was able to work around the issue using this:

    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/nix/store/7rgyw6h12jvgnn8dnl6b7iaz1wib3qs6-hipchat-2.2.1388/libexec/hipchat/lib/cpp hipchat

which as far as I can tell uses the `libstdc++.so.6` from an older version of hipchat that was still working.

## Technical details

* System: NixOS 16.09pre81657.9445bb2 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre81657.9445bb2

**Comment by manveru** [comment]
pinging @jgeerds @puffnfresh since they're he maintainers

**Comment by cstrahan** [comment]
Looks like `"${stdenv.cc.cc}/lib"` has changed quite a bit recently.

Here's gcc-5.3.0 from the latest master:

    ~/src/nixpkgs (nixos) λ ls -l /nix/store/l8y2srrkp5fflwph7vq0gllj1k1ai17w-gcc-5.3.0/lib/
    total 13052
    dr-xr-xr-x 1 root root      48 Dec 31  1969 gcc
    -r--r--r-- 1 root root 2130926 Dec 31  1969 libasan.a
    -r--r--r-- 1 root root    1176 Dec 31  1969 libasan_preinit.o
    -r--r--r-- 1 root root  132786 Dec 31  1969 libatomic.a
    -r--r--r-- 1 root root   88266 Dec 31  1969 libcc1.a
    -r--r--r-- 1 root root  249914 Dec 31  1969 libcilkrts.a
    -r--r--r-- 1 root root     173 Dec 31  1969 libcilkrts.spec
    -r--r--r-- 1 root root  254498 Dec 31  1969 libgomp.a
    -r--r--r-- 1 root root     169 Dec 31  1969 libgomp.spec
    -r--r--r-- 1 root root  225574 Dec 31  1969 libitm.a
    -r--r--r-- 1 root root     162 Dec 31  1969 libitm.spec
    -r--r--r-- 1 root root  738484 Dec 31  1969 liblsan.a
    -r--r--r-- 1 root root  582218 Dec 31  1969 libquadmath.a
    -r--r--r-- 1 root root     290 Dec 31  1969 libsanitizer.spec
    -r--r--r-- 1 root root   27378 Dec 31  1969 libssp.a
    -r--r--r-- 1 root root    1702 Dec 31  1969 libssp_nonshared.a
    -r--r--r-- 1 root root 5242710 Dec 31  1969 libstdc++.a
    -r--r--r-- 1 root root  769250 Dec 31  1969 libstdc++fs.a
    -r--r--r-- 1 root root  365012 Dec 31  1969 libsupc++.a
    -r--r--r-- 1 root root 1831264 Dec 31  1969 libtsan.a
    -r--r--r-- 1 root root  661978 Dec 31  1969 libubsan.a
    -r--r--r-- 1 root root       8 Dec 31  1969 libvtv.a

Here's gcc-4.9.3 from the last time a built my machine, about a month ago:
    
    ~/src/nixpkgs (nixos) λ ls -l /nix/store/ikzdbd65z7453spdvm05r0izd56zdvkx-gcc-4.9.3/lib
    total 12804
    dr-xr-xr-x 1 root root      48 Dec 31  1969 gcc
    -r--r--r-- 1 root root 1445502 Dec 31  1969 libasan.a
    -r-xr-xr-x 1 root root    1089 Dec 31  1969 libasan.la
    -r--r--r-- 1 root root    1168 Dec 31  1969 libasan_preinit.o
    lrwxrwxrwx 1 root root      16 Dec 31  1969 libasan.so -> libasan.so.1.0.0
    lrwxrwxrwx 1 root root      16 Dec 31  1969 libasan.so.1 -> libasan.so.1.0.0
    -r-xr-xr-x 1 root root  666968 Dec 31  1969 libasan.so.1.0.0
    -r--r--r-- 1 root root  132850 Dec 31  1969 libatomic.a
    -r-xr-xr-x 1 root root    1011 Dec 31  1969 libatomic.la
    lrwxrwxrwx 1 root root      18 Dec 31  1969 libatomic.so -> libatomic.so.1.1.0
    lrwxrwxrwx 1 root root      18 Dec 31  1969 libatomic.so.1 -> libatomic.so.1.1.0
    -r-xr-xr-x 1 root root   24464 Dec 31  1969 libatomic.so.1.1.0
    -r--r--r-- 1 root root  250754 Dec 31  1969 libcilkrts.a
    -r-xr-xr-x 1 root root    1106 Dec 31  1969 libcilkrts.la
    lrwxrwxrwx 1 root root      19 Dec 31  1969 libcilkrts.so -> libcilkrts.so.5.0.0
    lrwxrwxrwx 1 root root      19 Dec 31  1969 libcilkrts.so.5 -> libcilkrts.so.5.0.0
    -r-xr-xr-x 1 root root  115392 Dec 31  1969 libcilkrts.so.5.0.0
    -r--r--r-- 1 root root     173 Dec 31  1969 libcilkrts.spec
    lrwxrwxrwx 1 root root      13 Dec 31  1969 libgcc_s.so -> libgcc_s.so.1
    -r--r--r-- 1 root root  101054 Dec 31  1969 libgcc_s.so.1
    -r--r--r-- 1 root root  177990 Dec 31  1969 libgomp.a
    -r-xr-xr-x 1 root root     988 Dec 31  1969 libgomp.la
    lrwxrwxrwx 1 root root      16 Dec 31  1969 libgomp.so -> libgomp.so.1.0.0
    lrwxrwxrwx 1 root root      16 Dec 31  1969 libgomp.so.1 -> libgomp.so.1.0.0
    -r-xr-xr-x 1 root root   90256 Dec 31  1969 libgomp.so.1.0.0
    -r--r--r-- 1 root root     164 Dec 31  1969 libgomp.spec
    -r--r--r-- 1 root root  257422 Dec 31  1969 libitm.a
    -r-xr-xr-x 1 root root     981 Dec 31  1969 libitm.la
    lrwxrwxrwx 1 root root      15 Dec 31  1969 libitm.so -> libitm.so.1.0.0
    lrwxrwxrwx 1 root root      15 Dec 31  1969 libitm.so.1 -> libitm.so.1.0.0
    -r-xr-xr-x 1 root root  134960 Dec 31  1969 libitm.so.1.0.0
    -r--r--r-- 1 root root     162 Dec 31  1969 libitm.spec
    -r--r--r-- 1 root root  611644 Dec 31  1969 liblsan.a
    -r-xr-xr-x 1 root root    1089 Dec 31  1969 liblsan.la
    lrwxrwxrwx 1 root root      16 Dec 31  1969 liblsan.so -> liblsan.so.0.0.0
    lrwxrwxrwx 1 root root      16 Dec 31  1969 liblsan.so.0 -> liblsan.so.0.0.0
    -r-xr-xr-x 1 root root  233192 Dec 31  1969 liblsan.so.0.0.0
    -r--r--r-- 1 root root  568354 Dec 31  1969 libquadmath.a
    -r-xr-xr-x 1 root root    1020 Dec 31  1969 libquadmath.la
    lrwxrwxrwx 1 root root      20 Dec 31  1969 libquadmath.so -> libquadmath.so.0.0.0
    lrwxrwxrwx 1 root root      20 Dec 31  1969 libquadmath.so.0 -> libquadmath.so.0.0.0
    -r-xr-xr-x 1 root root  250416 Dec 31  1969 libquadmath.so.0.0.0
    -r--r--r-- 1 root root     290 Dec 31  1969 libsanitizer.spec
    -r-xr-xr-x 1 root root    1089 Dec 31  1969 liblsan.la
    lrwxrwxrwx 1 root root      16 Dec 31  1969 liblsan.so -> liblsan.so.0.0.0
    lrwxrwxrwx 1 root root      16 Dec 31  1969 liblsan.so.0 -> liblsan.so.0.0.0
    -r-xr-xr-x 1 root root  233192 Dec 31  1969 liblsan.so.0.0.0
    -r--r--r-- 1 root root  568354 Dec 31  1969 libquadmath.a
    -r-xr-xr-x 1 root root    1020 Dec 31  1969 libquadmath.la
    lrwxrwxrwx 1 root root      20 Dec 31  1969 libquadmath.so -> libquadmath.so.0.0.0
    lrwxrwxrwx 1 root root      20 Dec 31  1969 libquadmath.so.0 -> libquadmath.so.0.0.0
    -r-xr-xr-x 1 root root  250416 Dec 31  1969 libquadmath.so.0.0.0
    -r--r--r-- 1 root root     290 Dec 31  1969 libsanitizer.spec
    -r--r--r-- 1 root root   27450 Dec 31  1969 libssp.a
    -r-xr-xr-x 1 root root     981 Dec 31  1969 libssp.la
    -r--r--r-- 1 root root    1710 Dec 31  1969 libssp_nonshared.a
    -r-xr-xr-x 1 root root     963 Dec 31  1969 libssp_nonshared.la
    lrwxrwxrwx 1 root root      15 Dec 31  1969 libssp.so -> libssp.so.0.0.0
    lrwxrwxrwx 1 root root      15 Dec 31  1969 libssp.so.0 -> libssp.so.0.0.0
    -r-xr-xr-x 1 root root   10064 Dec 31  1969 libssp.so.0.0.0
    -r--r--r-- 1 root root 3336506 Dec 31  1969 libstdc++.a
    -r-xr-xr-x 1 root root    1008 Dec 31  1969 libstdc++.la
    lrwxrwxrwx 1 root root      19 Dec 31  1969 libstdc++.so -> libstdc++.so.6.0.20
    lrwxrwxrwx 1 root root      19 Dec 31  1969 libstdc++.so.6 -> libstdc++.so.6.0.20
    -r-xr-xr-x 1 root root 1007624 Dec 31  1969 libstdc++.so.6.0.20
    -r--r--r-- 1 root root    2399 Dec 31  1969 libstdc++.so.6.0.20-gdb.py
    -r--r--r-- 1 root root  359336 Dec 31  1969 libsupc++.a
    -r-xr-xr-x 1 root root     942 Dec 31  1969 libsupc++.la
    -r--r--r-- 1 root root 1616126 Dec 31  1969 libtsan.a
    -r-xr-xr-x 1 root root    1089 Dec 31  1969 libtsan.la
    lrwxrwxrwx 1 root root      16 Dec 31  1969 libtsan.so -> libtsan.so.0.0.0
    lrwxrwxrwx 1 root root      16 Dec 31  1969 libtsan.so.0 -> libtsan.so.0.0.0
    -r-xr-xr-x 1 root root  714912 Dec 31  1969 libtsan.so.0.0.0
    -r--r--r-- 1 root root  525724 Dec 31  1969 libubsan.a
    -r-xr-xr-x 1 root root    1096 Dec 31  1969 libubsan.la
    lrwxrwxrwx 1 root root      17 Dec 31  1969 libubsan.so -> libubsan.so.0.0.0
    lrwxrwxrwx 1 root root      17 Dec 31  1969 libubsan.so.0 -> libubsan.so.0.0.0
    -r-xr-xr-x 1 root root  210480 Dec 31  1969 libubsan.so.0.0.0
    -r--r--r-- 1 root root       8 Dec 31  1969 libvtv.a
    -r-xr-xr-x 1 root root     981 Dec 31  1969 libvtv.la
    lrwxrwxrwx 1 root root      15 Dec 31  1969 libvtv.so -> libvtv.so.0.0.0
    lrwxrwxrwx 1 root root      15 Dec 31  1969 libvtv.so.0 -> libvtv.so.0.0.0
    -r-xr-xr-x 1 root root    4096 Dec 31  1969 libvtv.so.0.0.0


Note that `libstdc++.so.6` is missing from gcc-5.3.0.

**Comment by abbradar** [comment]
I think you need `stdenv.cc.cc.lib`.

**Comment by cstrahan** [comment]
> I think you need `stdenv.cc.cc.lib`.

Oh, yeah - of course. I was lead astray due to a sill mistake while using `nix-repl`:

    ~/src/nixpkgs (master) λ nix-repl
    Welcome to Nix version 1.11.2. Type :? for help.
    
    nix-repl> :l <nixpkgs>
    Added 6149 variables.
    
    nix-repl> stdenv.cc.cc.outputs
    [ "out" "info" ]
    
    nix-repl>
    
    ~/src/nixpkgs (master) λ nix-repl
    Welcome to Nix version 1.11.2. Type :? for help.
    
    nix-repl> :l .
    Added 6249 variables.
    
    nix-repl> stdenv.cc.cc.outputs
    [ "out" "lib" "man" "info" ]

**Comment by jagajaga** [comment]
We have lots of problems with that. @vcunat please help :/
Also yandex-disk, stack, yi are affected...

**Comment by abbradar** [comment]
I can look at this later to take some load of @vcunat.

**Comment by jagajaga** [comment]
@abbradar I think we need only sed :)

**Comment by vcunat** [comment]
IMHO you only need something like this:
```diff
diff --git a/pkgs/applications/networking/instant-messengers/hipchat/default.nix b/pkgs/applications/networking/instant-messengers/hipchat/default.nix
index b57b339..e356740 100644
--- a/pkgs/applications/networking/instant-messengers/hipchat/default.nix
+++ b/pkgs/applications/networking/instant-messengers/hipchat/default.nix
@@ -36,7 +36,7 @@ let
     xcbutilkeysyms
     systemd
     mesa_noglu
-  ] + ":${stdenv.cc.cc}/lib64";
+  ] + ":${stdenv.cc.cc.lib}/lib64";
 
   src =
     if stdenv.system == "x86_64-linux" then
```

If you spend a bit of time on it, you shouldn't have problem to fix the RPATHS to find what is needed.

**Comment by vcunat** [comment]
I've got more on my plate than I can well handle.

**Comment by abbradar** [comment]
Treewise sed patch at https://github.com/NixOS/nixpkgs/commit/87ebab128a466b6b3ac60711621ba6264cb7075a. Hipchat works, should hopefully also fix others.
