### ISSUE TITLE
Xorg server out of date.

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#150133]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: nix command complains about no flakes?

current version: 1.20.12
desired version: 21.1.1

###### Notify maintainers

maintainers: @TredwellGit 

###### Note for maintainers

Please tag this issue in your PR.

And maybe add the maintainers field?

as nixpkgs search says: This package has no maintainers.

There's also a new feature that could be added to the xserver service/module: https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/742

**Comment by Mindavi** [comment]
Overview of changes for 1.20 -> 21.1.0: https://lists.x.org/archives/xorg-announce/2021-October/003115.html

**Comment by TredwellGit** [comment]
We need to package libxcvt first.

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/153994

**Comment by jyooru** [comment]
#153994 has been merged
