### ISSUE TITLE
[pkgs.flutter] Out-of-date: 2.5.1 -> 2.8.0.

### ISSUE THREAD

**Issue by VergeDX** [NixOS/nixpkgs#150253]
###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: flutter
current version: 2.5.1
desired version: 2.8.0

###### Notify maintainers

maintainers:

###### Note for maintainers
@babariviere @ericdallo
Please tag this issue in your PR.

**Comment by ericdallo** [comment]
done on https://github.com/NixOS/nixpkgs/pull/150280
