### ISSUE TITLE
Incorrect hashes for latex packages

### ISSUE THREAD

**Issue by markus1189** [NixOS/nixpkgs#15039]
## Issue description
I am trying to add latex packages inside my `configuration.nix`, but the build fails due to unexpected md5 hashes.

### Steps to reproduce

In `configuration.nix` add

```
environment.systemPackages = with pkgs; [
(texlive.combine {
      inherit (texlive) scheme-medium framed minted;
    })
]
```

output is:

```
output path ‘/nix/store/5yb0gsnjh8hqzxzz9ns76w20k5z1ln9d-minted.tar.xz’ has md5 hash ‘5499940dd47a0c46f5607219fcf26687’ when ‘017fbfe849f7f0e5814d7947887a8eec’ was expected
```
for `minted` and 

```
output path ‘/nix/store/jsll8j97lgp40dic0mhs0lcij7hx2ww1-framed.tar.xz’ has md5 hash ‘e86e6af8de263056236211b3ae01160f’ when ‘e602c51704f15f8498357e3a7f0b209a’ was expected
```

for `framed`. 

I could just add those hashes to `pkgs/tools/typesetting/tex/texlive-new/pkgs.nix`, but how do I get the hash for e.g. `md5.doc` or `md5.run`?  

/cc @vcunat 

## Technical Details

* System: `16.09pre81686.f1675d9 (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `16.09pre81686.f1675d9`

**Comment by joachifm** [comment]
See https://github.com/NixOS/nixpkgs/issues/10026

**Comment by markus1189** [comment]
Oh well that sounds like a sad story.  Essentially that means I should better not hope to get a fix soon, I assume?

**Comment by domenkozar** [comment]
Closing, let's move discussion to the existing issue.
