### ISSUE TITLE
jool: 4.1.5 -> 4.1.6

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#150341]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: jool

current version: 4.1.5
desired version: 4.1.6

###### Notify maintainers

maintainers: @fpletz

###### Note for maintainers

Please tag this issue in your PR.

**Comment by fpletz** [comment]
Fixed by #154223.
