### ISSUE TITLE
KSycoca database breaks when XDG_DATA_DIRS is too large

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#15044]
## Issue description

Nixpkgs blows up the size of XDG_DATA_DIRS. In KDE, there is an upper limit on this variable of ~4096 bytes. Above this value, KSococa can write the cache file, but not read it.

### Steps to reproduce

- Make XDG_DATA_DIRS very long, either manucally or by installing many packages that add to it.
- Run a KDE application
- Observe 'ERROR: KSycoca database corruption!' on the console.

## Technical details

The attached patch to kde5.kservice fixes the issue.

https://git.reviewboard.kde.org/r/127770/

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

[patch.txt](https://github.com/NixOS/nixpkgs/files/239312/patch.txt)

**Comment by FRidh** [comment]
cc @ttuegel

**Comment by ttuegel** [comment]
Thanks for pointing this out. The patch LGTM. The ksycoca cache file actually causes other problems because it is not invalidated by `nix-env -i` and (much worse) each package runs with its own XDG_DATA_DIRS, so in the long-term, I would like to disable the cache file entirely.

**Comment by vandenoever** [comment]
The patch is now committed in KService master.

There is a different cache created for each different XDG_DATA_DIRS value. See ksycoca.h:

> Since 5.15, the filename includes language and a sha1 of the directories in GenericDataLocation, i.e. the directories with the desktop files. This allows to have one database per setup, when using different install prefixes or when switching languages.

**Comment by ttuegel** [comment]
> There is a different cache created for each different XDG_DATA_DIRS value.

That actually makes our cache-invalidation problem much worse because we cannot simply regenerate the cache at login with `kbuildsycoca5`. We will probably have to go back to generating a read-only cache for each package at build-time.

**Comment by vandenoever** [comment]
When using nix-shell, it's actually nice that XDG_DATA_DIRS triggers a new cache. In nix-shell, XDG_DATA_DIRS points to directories in /nix/store. Those are read-only directories identified by hash values. So the cache would be permanently valid. 

A changed mtime also triggers a new cache run.
For the normal shell, $HOME/.nix-profile/share, /nix/var/nix/profiles/default/share and /run/current-system/sw/share are used. A change in the contents of those dirs should give these directories a new mtime. When the mtime changes a new cache will be created.

**Comment by ttuegel** [comment]
> A changed mtime also triggers a new cache run.
> For the normal shell, $HOME/.nix-profile/share, /nix/var/nix/profiles/default/share and /run/current-system/sw/share are used. A change in the contents of those dirs should give these directories a new mtime. When the mtime changes a new cache will be created.

That induces spurious cache regeneration if you do something like rollback to a previous generation. I can live with that, I guess.
