### ISSUE TITLE
Audacious

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nixpkgs#150439]
**Project description**
_describe the project a little_
Audacium is an active no telemetry audacity fork. I think that this a good idea to package this. 
**Metadata**

* homepage URL:https://audacium.xyz
* source URL:https://github.com/SartoxSoftware/audacium
* license: mit, bsd, gpl2+ , ... gpl2
* platforms: unix, linux, darwin, ... linux, darwin

**Comment by WolfangAukang** [comment]
FYI, the package name is Audacium. Audacious is a music player, and people might get confused with it, as it is already packaged.

**Comment by jakobneufeld** [comment]
Sorry, that was autocomplete. Tenacity exists anyway, so we can close this @WolfangAukang

**Comment by WolfangAukang** [comment]
If you want, you can still leave this open just in case someone gets interested in building it. I mean, it will be just an extra alternative to Audacity on Nixpkgs, so it wouldn't hurt to have this :).
