### ISSUE TITLE
Update Janet from 1.16.1 -> 1.19.2

### ISSUE THREAD

**Issue by cideM** [NixOS/nixpkgs#150415]
Janet is pretty outdated in Nixpkgs right now. I tried updating to `1.19.2` but got the below error on my M1 Darwin machine:

```
Summary of Failures:

11/11 test/suite0009.janet TIMEOUT        30.01s   killed by signal 15 SIGTERM
```

It passes **on the same machine** when cloning the repo and running `make test` and the derivation can be built on my NixOS machine.

- `nix-build` M1: 🔴 
- `nix-build` NixOS: 🟢 
- `make test` M1: 🟢 

I asked for some help on Gitter but I thought I'd open an issue in the meantime so we can combine forces. I know absolutely zero whatsoever about Janet the project and Janet the language, yet.

**Janet no longer includes JPM** so we'll have to add it separately. Maybe do it in the same PR so there's no period where users of Nixpkgs are left without `jpm`.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `janet` or `Janet programming language`

current version: `1.16.1`
desired version: `1.19.2`

###### Notify maintainers
maintainers: @peterhoeg @andrewchambers 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by cideM** [comment]
This patch fixes the issue on my M1 machine:

```
diff --git a/test/suite0009.janet b/test/suite0009.janet
index 6095bc60..25360d60 100644
--- a/test/suite0009.janet
+++ b/test/suite0009.janet
@@ -174,15 +174,6 @@
   (defer (:close stream)
     (check-matching-names stream)))
 
-# Test localname and peername
-(repeat 20
-  (with [s (net/server "127.0.0.1" "8000" names-handler)]
-    (defn test-names []
-      (with [conn (net/connect "127.0.0.1" "8000")]
-        (check-matching-names conn)))
-    (repeat 20 (test-names)))
-  (gccollect))
-
 # Create pipe
 
 (var pipe-counter 0)
```

**Comment by cideM** [comment]
Janet builds now with that patch but I'm struggling with JPM https://gitter.im/janet-language/community?at=61b60756cdb5c1081a5d9f09

**Comment by andrewchambers** [comment]
Yeah sorry for the large delay, the reason it isn't updated is jpm as you said.

**Comment by cideM** [comment]
If it helps, here's what I have so far https://github.com/cideM/nixpkgs/commit/098fb7d8fc09256fe6ec2e5acb0e1041db336ac3 https://github.com/cideM/nixpkgs/commit/2578391e2be35eda7d168e9ce622b649231e67c4

**Comment by peterhoeg** [comment]
Closing in favour of #150618
