### ISSUE TITLE
mitmproxy is broken, likely everywhere, due to releases moving

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#15041]
mitmproxy package expects the source tar.gz to be here: http://mitmproxy.org//download/mitmproxy-0.14.0.tar.gz

However, that is no longer available. And source seems to only be available from Pypi in Pythons "wheel" format which is apparently just a zip.

https://pypi.python.org/pypi/mitmproxy/0.17

This is probably broken on the stable releases too....

**Comment by domenkozar** [comment]
Well wheel is a binary format, so using https://github.com/NixOS/nixpkgs/pull/15010 might help here.

**Comment by FRidh** [comment]
note that you can find the archives at https://github.com/mitmproxy/mitmproxy/releases

Latest: https://github.com/mitmproxy/mitmproxy/archive/v0.17.1.tar.gz

**Comment by colemickens** [comment]
I guess I'll send two commits then. One that fixes this without taking a dependency on the new wheel support (so that this can be back ported to stable releases) and then a new one changing to wheel?

Or is the second one unnecessary?

**Comment by FRidh** [comment]
I recommend you use the GitHub archive. While wheel support is added we should keep the amount of wheels in Nixpkgs to a minimum. The reason support was added was because packages exist that cannot be build with setuptools.

**Comment by colemickens** [comment]
@domenkozar this is now fixed in master. Leaving this open for someone to chime in on backporting.

**Comment by domenkozar** [comment]
Pushed to 16.03 in e3c29b27d85a89e45787b39b6181b3508af5e136
