### ISSUE TITLE
aarch64 build blocking release-channel for x86 users

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixpkgs#150532]
### Describe the bug

As can be seen on https://status.nixos.org/ the channel `release-21.11` has been blocked by build failures for quite a few days now.
The culprit is (most of the time) firefox for aarch64.
While it is reasonable to have single release-channel that keeps aarch64 and x86 in sync, this channel currently also serves as the x86-only channel and thus x86 users are affected by failing aarch64 builds.
This is especially unfortunate with some important security updates pending (*cough* log4j).
Given that we have `nixos-21.11-aarch64` we should probably also add `nixos-21.11-x86` and update documentation to advise for usage of the platform specific channel unless one has an heterogeneous system landscape and requires both channels to be in sync (as delivered by `nixos-21.11`).

**Comment by vcunat** [comment]
The `firefox-esr` builds have aarch64-linux issues on all branches now (all updates get backported).  Most of build attempts get stuck when linking libxul, even when nothing else is running on that machine.  As I remember from x86, that step is single-threaded but very expensive on RAM, so I assume the builders just run out of it and "freeze".

**Comment by wamserma** [comment]
@vcunat Yes, but this is also about the general problem that aarch64 blocks updates for x86 user (but no the other way round).

**Comment by vcunat** [comment]
Yes, I didn't mean to dispute that.  This thread just seemed like a good place for the information.

**Comment by vcunat** [comment]
All channels have updated.  Though some risks discussed here remain and may still "keep delaying" updates.

**Comment by wamserma** [comment]
@vcunat well, we've got this issue again (https://hydra.nixos.org/build/164543364).

What would be the best/official way to trigger creation of a `nixos-21.11-x86-64` channel?

**Comment by vcunat** [comment]
Yes, most of firefox aarch64-linux builds fail.  That is a long-term problem.  For now it's being mitigated by manually restarting, as we supposedly do want to support the package, but over long term it's rather bad.
