### ISSUE TITLE
mousai: Missing icons

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#150516]
### Describe the bug
The application mousai (v. 0.6.6) is missing various icons and doesn't display them correctly

### Steps To Reproduce
1. nix-shell -p mousai --run "mousai"

### Expected behavior
Icons should be present.

### Screenshots
![image](https://user-images.githubusercontent.com/757752/145790887-03288432-3604-43c9-a20a-bf6ca4b0a711.png)

### Notify maintainers
@dotlambda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.334247.573095944e7, unstable-22.05pre337103.581d2d6c9cd"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
If you are using GNOME, I think the dark style preference mousai supports will not be available before GNOME 42.

https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/

The dark style preference should work in Pantheon 6.0.3 though, not sure about other desktop.

| ![2021-12-13 18-15-23 的屏幕截图](https://user-images.githubusercontent.com/20080233/145793891-ccb9024b-a7cd-4fa1-86d9-b34667652d0f.png) | ![2021-12-13 18-15-24 的屏幕截图](https://user-images.githubusercontent.com/20080233/145793908-5d60dbea-654b-46c0-9d6e-61f51a8a53d1.png) |
|:---:|:---:|

**Comment by onny** [comment]
To be more precise, I'm not using a dark theme setting but a theme called "adwaita-dark". My home-manager configuration looks like this:

```
  home-manager = {
    users.onny = {
      gtk = {
        enable = true;
        iconTheme = {
          name = "Adwaita-dark";
          package = pkgs.gnome3.adwaita-icon-theme;
        };
        theme = {
          name = "Adwaita-dark";
          package = pkgs.gnome3.gnome_themes_standard;
        };
      };
[...]
```

As you can see on the screenshot Gedit (or Nautilus, Gnome-Calculator, etc.) are following it, whereas mousai does not:
![20211213_17h07m04s_grim](https://user-images.githubusercontent.com/757752/145846749-eb807d39-7b80-4203-89d4-3ae9735db546.png)

**Comment by bobby285271** [comment]
I think libadwaita "hardcodes" the theme, so no matter what theme you are using, Adwaita-dark, Numix, Arc, ... mousai will always use Adwaita (unless you change the dark style preference I guess). As soon as more GNOME apps are ported to libadwaita, I guess they will have the same behavior too.

To check if an app shipped by nixpkgs has been ported to libadwaita, maybe just check whether `libadwaita` is presented in `buildInputs`.

https://blogs.gnome.org/alatiera/2021/09/18/the-truth-they-are-not-telling-you-about-themes/

**Comment by onny** [comment]
Okay so we'll have to wait until "dark mode" is supported by libadwaita :)

Here's an other example about the missing icon set:
![image](https://user-images.githubusercontent.com/757752/146439859-f2e8d7cc-4827-4967-9b7e-bec99f191de7.png)

**Comment by bobby285271** [comment]
> Okay so we'll have to wait until "dark mode" is supported by libadwaita :)

No, libadwaita already supports dark style preference.

> Here's an other example about the missing icon set

Do you have any icon theme of your choice installed in `environment.systemPackages` (`gnome.adwaita-icon-theme` for example)?

<img src="https://user-images.githubusercontent.com/20080233/146474169-df0c8f47-4c35-47ce-8cf8-001c5b106f3c.png" width=50%>

**Comment by bobby285271** [comment]
> Okay so we'll have to wait until "dark mode" is supported by libadwaita :)

No, libadwaita already supports dark style preference.

> Here's an other example about the missing icon set:

Actually it looks good to me. So I am not sure if adding `gnome.adwaita-icon-theme` to `buildInputs` of this package or your `environment.systemPackages` will be helpful.

<img src="https://user-images.githubusercontent.com/20080233/146477640-5bac0aec-bbb9-479c-8ffb-39835f89c19a.png" width=50%>

**Comment by onny** [comment]
Oh thanks for the note, dark mode does indeed work with Gtk4 and libadwaita by creating the file `~/.config/gtk-4.0/settings.ini` with following content:
```
[Settings]
gtk-application-prefer-dark-theme=true
```
Putting `gnome.adwaita-icon-theme` into `buildInputs` didn't solve the problem with the missing icons :,(

**Comment by onny** [comment]
Updated the issue description that for now, only the icons are missing. I'll have to check which gnome icon package I need to have installed to fix this :)

**Comment by jtojnar** [comment]
Adding icon theme to `buildInputs` will not work. You need to install an icon theme globally, see https://github.com/NixOS/nixpkgs/pull/43150#issuecomment-450058333

**Comment by onny** [comment]
Still no luck. Added this to my system configuration:
```
environment.systemPackages = with pkgs; [
    gnome3.adwaita-icon-theme
    gnome.adwaita-icon-theme
    hicolor-icon-theme
    gtk3
    gtk4
  ];

  xdg.icons.enable = true; 

home-manager.users.onny = {
    gtk = {
      enable = true;
      iconTheme = {
        name = "Adwaita-dark";
        package = pkgs.gnome3.adwaita-icon-theme;
      };
      theme = {
        name = "Adwaita-dark";
        package = pkgs.gnome3.gnome_themes_standard;
      };
      gtk4.extraConfig = {
        gtk-application-prefer-dark-theme = true;
      };
    };
}
```
Icons still missing in Mousai:

![20211227_15h48m37s_grim](https://user-images.githubusercontent.com/757752/147482751-0997d0b6-249f-467b-bbf6-3bdbebc97b29.png)

![20211227_15h48m28s_grim](https://user-images.githubusercontent.com/757752/147482755-c98a121a-cda1-4d7f-a11b-ac41b5749de0.png)

@bobby285271 On which desktop environment are you running the application?

**Comment by bobby285271** [comment]
> On which desktop environment are you running the application?

I am using Pantheon, the Pantheon module [has icon themes](https://github.com/NixOS/nixpkgs/blob/f427295e61b3d878b2dd9d30cb8d24df312ae9da/nixos/modules/services/x11/desktop-managers/pantheon.nix#L178-L193) added to `environment.systemPackages`.

**Comment by jtojnar** [comment]
`Adwaita-dark` is not an icon theme. Use `Adwaita`.

**Comment by onny** [comment]
> `Adwaita-dark` is not an icon theme. Use `Adwaita`.

Oh sorry, that was the issue. Thank you!

**Comment by jtojnar** [comment]
Also note that `gnome3` is a legacy alias of `gnome`.
