### ISSUE TITLE
gtk2 applications not themed in StumpWM

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#15051]
## Issue description

GTK2 applications (like Firefox, Gimp and Inkscape) are not themed in StumpWM (the Raleigh theme is used).

Trying to set a theme in ~/.gtkrc-2.0 does not work either.
## Technical details
- System: 16.09.git.d167450M (Flounder)
- Nix version:  nix-env (Nix) 1.11.2

**Comment by laMudri** [comment]
I think I had this problem (and it's a fairly common problem), and the workaround involved setting the theme via `lxappearance`. If that doesn't fix it, either I've forgotten a few steps or it's a different problem.

**Comment by jgillich** [comment]
They also use Raleigh under GNOME 3. I have this in my nixos config:
```
  environment.variables = {
    GTK2_RC_FILES = "${pkgs.gnome_themes_standard}/share/themes/Adwaita/gtk-2.0/gtkrc";
  };
```

**Comment by Profpatsch** [comment]
Since the PR was resolved, I’m gonna close this issue.
