### ISSUE TITLE
Update ly to 0.5.0

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#150515]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: ly

current version: 0.2.1
desired version: 0.5.0

###### Notify maintainers

maintainers: @vidister 

###### Note for maintainers

https://github.com/nullgemm/ly

Ly now has a systemd service, having it on nixos would be nice.

Please tag this issue in your PR.

**Comment by vidister** [comment]
Hi! I've been working on that already, it's almost finished, I was just waiting for the maintainer to merge a PR by me, which got merged a few days ago.

Saying that: I also was working on a module to make the service usable with NixOS. It's a bit fiddly to get the unit working with NixOS, so far I didn't get it working and switching between TTYs just crashed my GPU, so I stopped testing. But I'll finish it and submit the module, when I find the time.
If you want to work on it drop me a message.

**Comment by WolfangAukang** [comment]
I have been trying to create the module based on [this config](https://gitlab.com/roosemberth/dotfiles/-/commit/dc50bb9e36613cad6612c46decaa74ea087bd66f) and with the newest commit from `ly`. It is [here](https://codeberg.org/wolfangaukang/nix-agordoj/src/branch/ly), and I'm currently checking it. I tihink it will take a lot of time to get it figured it out as I have never worked with a display manager before, but I think Roosemberth's draft might help a little more.

**Comment by WolfangAukang** [comment]
Using the following configuration:
```nix
{ config, pkgs, lib, ... }: {

  users.users.bjorn = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
  };

  environment.systemPackages = with pkgs; [
    vim
  ];
  services.xserver = {
    enable = true;
    layout = "us";
    desktopManager.enlightenment.enable = true;
    displayManager.ly = {
      enable = true;
      defaultUser = "bjorn";
    };
  };

  system.stateVersion = "20.09";
}
```

I get this at startup:
![image](https://user-images.githubusercontent.com/8378365/168507829-2034b105-b218-4396-8076-be4f190cab92.png)

My only issue, which I'm not sure if it is related with the created module, is that it doesn't load Enlightenment after logging in. Honestly, I just picked it randomly and have never used it.

**Comment by WolfangAukang** [comment]
Can confirm root can access Enlightenment if I write the `.xinitrc` and on `ly` I use the xinitrc option. Not completely sure if I need to enable something to allow the access to the virtual console for any user (as it doesn't have permissions).

**Comment by zoedsoupe** [comment]
any updates here? I'm interested to help

**Comment by WolfangAukang** [comment]
> any updates here? I'm interested to help

[I have this based on the master branch from May 12th](https://codeberg.org/wolfangaukang/nix-agordoj/src/branch/main/pkgs/ly), if you want to check out. For now, the only thing I haven't gotten to make it work was changing the language and the tty issue pointed on the comment above.

If you want to also try it with a module, [I also have this](https://codeberg.org/wolfangaukang/nix-agordoj/src/branch/main/modules/nixos/ly.nix). It works if you use a root user.

**Comment by vidister** [comment]
@theknyaa and I have been investigating this in the last days.
See: https://github.com/fairyglade/ly/issues/248#issuecomment-1181072689
It took a few patches, but we have a state that works with sway. (haven't tested X based window managers yet)
It still needs some love, though. I try to find some time on the weekend to finish it.

**Comment by the-argus** [comment]
I don't have time to work on this atm (trying to get unreal engine to compile on nixos atm) but I would love to see it done! Ly is easily the best display manager, its the only thing I remotely miss from using non-immutable distros. I'll do it myself if I get Unreal working before anyone does this.
