### ISSUE TITLE
Firefox on wayland fails to render ui popups

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#150557]
### Describe the bug
Permission popups doesn't show up when Firefox is using Wayland backend on Sway

### Steps To Reproduce
1. GDK_BACKEND=wayland firefox https://addons.mozilla.org/en-US/firefox/addon/screenshot-go
2. Click on "Add to Firefox"
3. Popup does not appear but is requested

### Expected behavior
Popup should appear

### Screenshots
![image](https://user-images.githubusercontent.com/757752/145845438-94430ea7-9c9e-43d3-9dce-bf3e8344c612.png)

### Additional context
Popup shows up when runnign Firefox with `GDK_BACKEND=x11 firefox`.

- Firefox v. 95
- Sway v. 1.6.1

### Notify maintainers
@eelco @lovesegfault @hexa

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.334247.573095944e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by berbiche** [comment]
Hi,

This isn't an issue with nixpkgs Firefox build.

The UI popup issues in Firefox are known (both a GTK bug and a Firefox bug).
See the discussions on the Sway issue tracker:
- https://github.com/swaywm/sway/issues/6147
- https://github.com/swaywm/sway/issues/6426

**Comment by onny** [comment]
Okay then we'll have to wait for the next Firefox/GTK release :)

**Comment by rembo10** [comment]
I was having this problem, but it went away but I can't remember on what version (I thought it was pre-95.0 but maybe not).
I am on firefox 95.0.2 and sway 1.6.1 now and am not facing the issue anymore

**Comment by onny** [comment]
Firefox is now at 95.0.1 at everything seems to work fine now :) Thanks for the feedback!
