### ISSUE TITLE
electron: version `GLIBC_X.XX' not found

### ISSUE THREAD

**Issue by DavHau** [NixOS/nixpkgs#150541]
I am currently working on electron support for dream2nix and have a question for the electron maintainers of nixpkgs.

What is the reason that LD_PRELOAD is used here?
https://github.com/NixOS/nixpkgs/blob/0dadd5fabb2a10d39e2641b5b7857ea1131517a6/pkgs/development/tools/electron/generic.nix#L96

This leads to errors on my system (NixOS):
`/bin/sh: /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6: version GLIBC_2.33 not found (required by /nix/store/3drz007zp3w7bksw73rnv1xry1pa1js1-libX11-1.7.2/lib/libX11.so.6)`

The cause seems to be that my current systems glibc is 2.32 but I built the electron app with 2.33.
Some part of the electron app defaults to using my systems glibc.

If I try to fix that by addind glibc 2.33 via `LD_LIBRARY_PATH`, another error occurs:
`/bin/sh: symbol lookup error: /nix/store/mij848h2x5wiqkwhg027byvmf9x3gx7y-glibc-2.33-50/lib/libc.so.6: undefined symbol: _dl_catch_error_ptr, version GLIBC_PRIVATE`

If I instead just remove the `LD_PRELOAD` from the wrapper, it everything works flawlessly.

Therefore my question: Do we really need that LD_PRELOAD in the wrapper? If yes, is there an alternative solution possible, like putting `libXScrnSaver` into `LD_LIBRARY_PATH` instead. I tried that and this doesn't break stuff.

I have seen the mentioned problem with multiple electron apps, so it is not a problem of a specific app.

### Notify maintainers

@travisbhartwell @manveru @prusnak 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.20211206.4a8751d (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - nixpkgs: `/nix/store/p53cz6rh27q40g9i0q98k3vfrz6lm12w-source`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - electron
# a list of nixos modules affected by the problem
module:
```

**Comment by prusnak** [comment]
@DavHau can you please check whether the fix in https://github.com/NixOS/nixpkgs/pull/172961 fixes this issue for you?
