### ISSUE TITLE
emacsPackages.elpy won't build

### ISSUE THREAD

**Issue by cfhammill** [NixOS/nixpkgs#150568]
### Describe the bug

Package fails to install with a permissions error copying between store locations

### Steps To Reproduce

`nix-shell -p 'emacsPackages.elpy'`

### Expected behavior

The package to install

### Error

```
nix-shell -p 'emacsPackages.elpy'
these 8 derivations will be built:
  /nix/store/vfrcxsbjizilbj7kznq03iyp68haxfia-source.drv
  /nix/store/01wi0v6j62azzj1k0x6750nf600xclq9-emacs-highlight-indentation-20210221.1418.drv
  /nix/store/hkbi32j2gmp7bbx5lha1lmq5i90ff5iz-source.drv
  /nix/store/cpjkikkldwwzdx9hlzn24bpqv47dsac3-emacs-company-20211112.2354.drv
  /nix/store/pqirnjjidwr612yz36q8k2bkrqrmxy8s-source.drv
  /nix/store/b5g14p7xi4rvk9xq4hvarpvhx2dl1cb0-yasnippet-recipe.drv
  /nix/store/xi7llqxi0ab4sdadhdlh7pw74kdixvk8-emacs-yasnippet-20200604.246.drv
  /nix/store/14v757nh2csm20brv4xpxzw5gvh0raz9-emacs-elpy-20210630.2317.drv
building '/nix/store/pqirnjjidwr612yz36q8k2bkrqrmxy8s-source.drv'...

trying https://github.com/jorgenschaefer/elpy/archive/8d0de310d41ebf06b22321a8534546447456870c.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   161  100   161    0     0    746      0 --:--:-- --:--:-- --:--:--   748
100  172k  100  172k    0     0   295k      0 --:--:-- --:--:-- --:--:--  295k
unpacking source archive /tmp/nix-build-source.drv-0/8d0de310d41ebf06b22321a8534546447456870c.tar.gz
mv: cannot move '/tmp/nix-build-source.drv-0/unpack/elpy-8d0de310d41ebf06b22321a8534546447456870c' to '/nix/store/c0751mv2jp9q8xrbba1k28dapnji7z85-source': Permission denied
error: builder for '/nix/store/pqirnjjidwr612yz36q8k2bkrqrmxy8s-source.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/14v757nh2csm20brv4xpxzw5gvh0raz9-emacs-elpy-20210630.2317.drv' failed to build
```

### Notify maintainers

From authors of  https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/recipes-archive-melpa.json

@AndersonTorres @shlevy @spacekitteh @adisbladis 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-17763-Microsoft, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(chris): `"nixpkgs-22.05pre336690.f225322e3be"`
 - nixpkgs: `/home/chris/.nix-defexpr/channels/nixpkgs`
```

Maintainer information:
```yaml
emacsPackages.elpy
```

**Comment by AndersonTorres** [comment]
I'll try to update the set,

**Comment by cfhammill** [comment]
thanks @AndersonTorres, any idea what could cause such an issue?

**Comment by AndersonTorres** [comment]
I can't know for sure.

From the log you provided, it looks like some weird filesystem permissions issue. It sometimes happened to me when I used to hack /nix/store manually (yes, I live dangerously and most of time I don´t know what I'm doing).

**Comment by cfhammill** [comment]
so far I haven't messed around with the store directly, I'm using nix under wsl, I don't know if that can cause any problems. Were you able to reproduce?

**Comment by AndersonTorres** [comment]
To be honest, no.

In this moment I am waiting for the automation scripts; but I made a quick testing.

I use [a personal script](https://github.com/AndersonTorres/etc/tree/subtree-house) that manages my `${HOME}` dir, and it accepted elpy without issues. It was even recognized by Emacs.

**Comment by cfhammill** [comment]
hmm, I also can't reproduce on an ubuntu vm and on my mac, maybe this is wsl specific. Thanks for updating the package set though @AndersonTorres, I'll try build using the update tomorrow (well, later today)

**Comment by cfhammill** [comment]
I haven't tried in a while but it seems unlikely to still be applicable. Closing
