### ISSUE TITLE
element-{desktop,desktop-wayland,web}: security update to 1.9.7

### ISSUE THREAD

**Issue by oxzi** [NixOS/nixpkgs#150552]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:
- `element-desktop`
- `element-desktop-wayland`
- `element-web`

current version: 1.9.5
desired version: 1.9.7

###### Notify maintainers

maintainers: @ma27 @fadenb @mguentner @ekleog @ralith @mjlbach @dandellion @sumnerevans

###### Note for maintainers

<https://matrix.org/blog/2021/12/13/disclosure-buffer-overflow-in-libolm-and-matrix-js-sdk> and <https://matrix.org/blog/2021/12/03/pre-disclosure-upcoming-security-release-of-libolm-and-matrix-js-sdk>
There seems to be a not yet disclosed security release. I created a RR for olm in #150550.

Please tag this issue in your PR.

**Comment by fpletz** [comment]
Fixed by #150558.
