### ISSUE TITLE
`docker compose` does not report version correctly

### ISSUE THREAD

**Issue by whentze** [NixOS/nixpkgs#150574]
### Describe the bug

Starting with NixOS 21.11, `pkgs.docker` ships with `pkgs.docker-compose_2` as a plugin by default.
This plugin seems to be build in a way that it fails to report its version correctly, leading to problems when tools check its version.
In particular, `docker compose version` prints `Docker Compose version dev` which appears to be a [fallback value](
https://github.com/docker/compose/blob/7c47673d4af41d79900e6c70bc1a3f9f17bdd387/internal/variables.go#L21) when the version is neither derived from a git tag nor injected by a build script.

This behavior unfortunately breaks docker-compose based self-hosted sentry deployments, as sentry will check `docker compose version` and, if the former doesn't work `docker-compose version`. Under NixOS 21.05, there is no `docker compose`, so this works fine, but in 21.11, it breaks because `dev` is not considered >= 2.

### Steps To Reproduce
1. `nix-shell -I nixpkgs=channel:nixos-21.11 --pure -p docker --run "docker compose version"`

### Expected behavior
`docker compose version` should print `version` from its [derivation](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/virtualization/docker/compose.nix#L5), e.g. `"2.0.1"`.

### Additional context
After reading the [upstream build script](https://github.com/docker/compose/blob/693732c4a7907a79a0865a7d185c752e03dd0c02/builder.Makefile#L29), I have tried to fix the derivation by adding either 
```nix
{
  GIT_TAG = version;
}
```
or
```nix
{
  LDFLAGS = "-X github.com/docker/compose/v2/internal.Version=${version}";
}
```
but that did not make any difference in the result.
I feel like I don't know enough about go packaging to fix this myself.

### Notify maintainers
@babariviere 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.4468.db200f7cf4a (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"agenix, nixos-21.05.4468.db200f7cf4a, unstable-22.05pre337603.47f45c8440e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - pkgs.docker-compose_2
  - pkgs.docker
# a list of nixos modules affected by the problem
module:
```

**Comment by babariviere** [comment]
Hello @whentze!

I think your second solution can work if you change it to:

```nix
{
  ldflags = ["-X github.com/docker/compose/v2/internal.Version=${version}"];
}
```

You can find it in the documentation: https://nixos.org/manual/nixpkgs/stable/#ssec-go-common-attributes

**Comment by Radvendii** [comment]
should this be added to the package in nixpkgs?

**Comment by whentze** [comment]
Thanks for the super quick response @babariviere :) I just tried your suggestion and it does indeed work!

I'd love to see this upstream and can make a PR

**Comment by babariviere** [comment]
> Thanks for the super quick response @babariviere :) I just tried your suggestion and it does indeed work!
> 
> 
> 
> I'd love to see this upstream and can make a PR

I will let you do it, if it's ok for you!
