### ISSUE TITLE
Wayland: 1.19.0 -> 1.20.0

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#150673]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `wayland`

current version: 1.19.0
desired version: 1.20.0

https://wayland.freedesktop.org/releases.html

###### Notify maintainers

maintainers: @primeos @codyopel @qyliss

###### Note for maintainers

Please tag this issue in your PR.

**Comment by primeos** [comment]
Update already merged 3 days ago: #148588
