### ISSUE TITLE
TLP fails to find config

### ISSUE THREAD

**Issue by Apppppppple** [NixOS/nixpkgs#150672]
### Describe the bug
When I run tlp (with `sudo tlp bat`), I get `Error: cannot read user configuration from /etc/tlp.conf or /nix/store/3h0pbbh2zvpdv2g7dcmbc45m5iaas1c8-tlp-1.4.0/etc/default/tlp.`. Downgrading from unstable to 21.05 yields `Error: cannot read user configuration from /etc/tlp.conf or /etc/default/tlp.`
### Steps To Reproduce
1. Install tlp
2. Run tlp with `sudo tlp bat`
3. Observe result.

### Expected behavior
TLP runs normally.

### Additional context
Given #141845 it seems like it works for some, so the repro steps may not work. I don't think I've done anything weird with my config that would cause this, however.

Something worth noting is that while `/etc/tlp.conf` and `/nix/store/*-tlp-1.4.0/etc/default/tlp` don't exist, `/nix/store/*-tlp-1.4.0/etc/tlp.conf` _does_ exist, so perhaps tlp is supposed to search there but doesn't?

### Notify maintainers
@abbradar @lovesegfault

### Metadata

```console
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(apple): `"nixos-21.05pre282015.a73020b2a15"`
 - channels(root): `"nixos-21.11pre299299.3a8d7958a61"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by quantmint** [comment]
You are supposed to configure tlp using nix [configuration](https://search.nixos.org/options?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=tlp) files, not by modifying tlp.conf directly.

**Comment by Apppppppple** [comment]
I'm not trying to configure tlp, this is just a fresh install. Did you mean that I need to use services.tlp rather than the tlp package?

**Comment by lovesegfault** [comment]
> I'm not trying to configure tlp, this is just a fresh install. Did you mean that I need to use services.tlp rather than the tlp package?

Yup

**Comment by Apppppppple** [comment]
Thanks! Out of curiosity, what is the TLP package used for? Is it just implementation details of the service or does it serve a different purpose?

**Comment by lovesegfault** [comment]
> Thanks! Out of curiosity, what is the TLP package used for? Is it just implementation details of the service or does it serve a different purpose?

Yeah, the service definition uses the package. 

Generally you should not use packages for services in NixOS; use the proper service module instead.
