### ISSUE TITLE
step-ca: access to keys

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#150719]
### Describe the bug
For the service to start, you need to open access to files for all users.
Service `step-ca` is started as dynamic user `step`. In system, it is not possible to set access rights only to user `step`.

### Steps To Reproduce
```
sudo mkdir -p /var/data/step-ca/{certs,secrets}
nano /var/data/step-ca/secrets/password
step certificate create "Example CA" /var/data/step-ca/certs/root_ca.crt /var/data/step-ca/secrets/root_ca.key --profile root-ca --password-file=/var/data/step-ca/secrets/password --kty=EC --crv=P-521
step certificate create "Example  Intermediate CA" /var/data/step-ca/certs/intermediate_ca.crt /var/data/step-ca/secrets/intermediate_ca.key --profile intermediate-ca --password-file=/var/data/step-ca/secrets/password --ca-password-file=/var/data/step-ca/secrets/password --ca /var/data/step-ca/certs/root_ca.crt --ca-key /var/data/step-ca/secrets/root_ca.key
chmod 0644 /var/data/step-ca/certs/*.crt
chmod 0644 /var/data/step-ca/secrets/*.key
```

сс @mohe2015

**Comment by mohe2015** [comment]
It seems like though this is not super easy to fix as the `$CREDENTIALS_DIRECTORY` variable is not known for the configuration file

**Comment by Izorkin** [comment]
> It seems like though this is not super easy to fix as the `$CREDENTIALS_DIRECTORY` variable is not known for the configuration file

Small temp fix?:
```
DynamicUser = false;
```

**Comment by mohe2015** [comment]
> > It seems like though this is not super easy to fix as the `$CREDENTIALS_DIRECTORY` variable is not known for the configuration file
> 
> Small temp fix?:
> 
> ```
> DynamicUser = false;
> ```

I think then we would need to create a user and I don't know how good it is to create users without a set id. I think there was a reason why we usually don't do that.
