### ISSUE TITLE
linux_zen: 5.15.6-zen2(5.13.13-zen1) -> v5.15.8-zen1

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#150713]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: linuxKernel.kernels.linux_zen

<details>
<summary>current version: 5.15.6</summary>

stable 21.11: 5.13.13
unstable: 5.15.5
master: 5.15.6

</details>

desired version: 5.15.8

###### Notify maintainers

maintainers: @atemu @andresilva

###### Note for maintainers

Please tag this issue in your PR.
Please update stable branch too.

**Comment by Atemu** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/150958
