### ISSUE TITLE
Plasma5+XMonad option missing in  login manager

### ISSUE THREAD

**Issue by Pauan** [NixOS/nixpkgs#150741]
### Describe the bug

I use unstable NixOS, Plasma (KDE) and XMonad.

When I boot up my computer and try to login, I get three options:

* Plasma (Wayland)
* none+xmonad
* Plasma (X11)

Unfortunately, it is missing the plasma5+xmonad option, which used to exist in NixOS 21.11

This means I cannot use XMonad together with Plasma, like I used to.

### Steps To Reproduce
1. Enable `services.xserver.desktopManager.plasma5.enable` and `services.xserver.windowManager.xmonad.enable`
2. Boot computer.
3. Look at the available options on the login screen.

### Notify maintainers

@lassulus @xaverdh @ivanbrennan

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.62, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-22.05pre338278.b0bf5f888d3, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

(I am using an older version of NixOS to write this bug report)

**Comment by Pauan** [comment]
This is still a problem with the latest Unstable, and also stable 21.11

This makes it impossible for me to use XMonad with NixOS.

Am I the only one who uses XMonad + Plasma?

Pinging more people: @peterhoeg @ttuegel @oxalica @SuperSandro2000 @samueldr @pasqui23

**Comment by peterhoeg** [comment]
Vanilla Plasma for me so I cannot comment.

**Comment by ttuegel** [comment]
This option was accidentally included in the past because we used a session script to start Plasma instead of the `.desktop` files. You may configure your window manager in Plasma through the `System Settings` application.

**Comment by Pauan** [comment]
@ttuegel I've looked at all the settings in `System Settings` and I don't see anything to change the window manager. Could you post a screenshot of where it is?

**Comment by peterhoeg** [comment]
https://userbase.kde.org/Tutorials/Using_Other_Window_Managers_with_Plasma

**Comment by Pauan** [comment]
@peterhoeg Thanks! But I'm confused... that link says that using a system-wide `.desktop` file is the preferred way to do things.

Shouldn't NixOS automatically add the appropriate `.desktop` file when enabling XMonad? As far as I know, that's what other distros do.

P.S. Since this change breaks existing user's configs (which have worked for years), this should have been mentioned in the NixOS changelog.

**Comment by CMCDragonkai** [comment]
This problem I have https://github.com/NixOS/nixpkgs/issues/58473 maybe related.

1. I do have plasma5 + xmonad option
2. However selecting only xmonad still causes plasma5 to start automatically

Why is the plasma5 starting automatically all the time even when not selected?

**Comment by Pauan** [comment]
A new version of KDE broke things again:

https://maxnatt.gitlab.io/posts/kde-plasma-with-i3wm/#kde-525-and-newer

Now if a user wants to use KDE + XMonad they have to run this command:

```sh
systemctl --user mask plasma-kwin_x11.service
```

And then create a new `plasma-xmonad.service` systemd service:

```ini
[Install]
WantedBy=plasma-workspace.target

[Unit]
Description=XMonad Window Manager
Before=plasma-workspace.target

[Service]
ExecStart=/nix/store/jy53q8lpwy5bfpxhvz2b8zmywnbyj62m-system-path/bin/xmonad
Slice=session.slice
Restart=on-failure
```

And lastly enable this service:

```
systemctl --user daemon-reload
systemctl --user enable plasma-xmonad.service
```

And the user has to manually update the `/nix/store/` path every time they update NixOS. This is really annoying and a super horrible user experience. It's incredibly hard for users to even figure out the above steps, this is not something users should have to deal with.

Can we please have NixOS automatically do the above steps when installing XMonad, just like how it used to in the past, so that way XMonad *just works* without requiring any extra steps from the user?

**Comment by Pauan** [comment]
I was able to get XMonad to work by adding this to my NixOS config:

```
systemd.user.services = {
  plasma-kwin_x11 = {
    enable = false;
  };

  plasma-xmonad = {
    wantedBy = ["plasma-workspace.target"];
    description = "XMonad Window Manager";
    before = ["plasma-workspace.target"];
    serviceConfig = {
      ExecStart = "/nix/store/jy53q8lpwy5bfpxhvz2b8zmywnbyj62m-system-path/bin/xmonad";
      Slice = "session.slice";
      Restart = "on-failure";
    };
  };
};
```

But I still have to hard-code the `/nix/store/` path, because I don't have access to the xmonad derivative.

So this really should be done automatically by the xmonad package.

**Comment by peterhoeg** [comment]
`ExecStart = "${pkgs.haskellPackages.xmonad}/bin/xmonad";` ?

**Comment by peterhoeg** [comment]
or presumably `ExecStart = lib.getExe pkgs.haskellPackges.xmonad`

**Comment by Pauan** [comment]
I don't think that will work, because the xmonad derivative is custom-made inside of the xmonad config:

https://github.com/NixOS/nixpkgs/blob/45b92369d6fafcf9e462789e98fbc735f23b5f64/nixos/modules/services/x11/window-managers/xmonad.nix#L8-L38

So it will have a different hash than `haskellPackages.xmonad`

**Comment by peterhoeg** [comment]
Then you have 3 options:

1. recreate the functionality from the nixos module that creates the wrapper script
2. expose `xmonad` from the nixos module through a `finalPackage` (or whatever you call it) attribute and use that to build your path
3. patch the xmonad nixos module to write out the systemd unit
