### ISSUE TITLE
Manual: misleading description for '' multi-line quotes

### ISSUE THREAD

**Issue by NotaseCretagen** [NixOS/nixpkgs#15076]
EDIT: **tl;dr:** https://github.com/NixOS/nixpkgs/issues/15076#issuecomment-215827389
## Issue description

The manual [here](https://nixos.org/releases/nixos/unstable/nixos-16.09pre79453.32b7b00/manual/index.html#sec-configuration-file) (or source code [here](https://github.com/NixOS/nixpkgs/blob/7475728593a49f09c4b7b959b15513aee38ab4b4/nixos/doc/manual/configuration/config-file.xml#L109-L113))says:
`The main difference is that preceding whitespace is automatically stripped from each line, and that characters like " and \ are not special (making it more convenient for including things like shell code).`

while talking about `''` quotes. 
But that's misleading, because it actually strips preceding whitespace intelligently with indentation in mind, as [this](https://github.com/NixOS/nixpkgs/blob/39ebb01d6e8d19b042fe65d303234d0db27877eb/doc/stdenv.xml#L79-L82) says:

```xml
(Note the use of <literal>''</literal>-style string literals, which
are very convenient for large multi-line script fragments because they
don’t need escaping of <literal>"</literal> and <literal>\</literal>,
and because indentation is intelligently removed.)</para>
```

ie. this remains unchanged
```nix
{
  a = ''
    line1
#   line2
    line3'';
}
```

**Comment by joachifm** [comment]
Automatic and intelligent are not mutually exclusive, though.

Anyway, would it be clearer if the NixOS manual said that whitespace is handled intelligently, or something to that effect, instead?

**Comment by NotaseCretagen** [comment]
I guess, but to me, reading `preceding whitespace is automatically stripped from each line` , I assume it means:
```nix
{
  a = ''
line1
#   line2
line3'';
}
```
(for the example above)

OR for an example like this:
```nix
{
  a = ''
    line1
  # line2
    line3'';
}
```

I would assume it becomes:

```nix
{
  a = ''
line1
# line2
line3'';
}
```

but instead, it actually becomes:

```nix
{
  a = ''
  line1
# line2
  line3'';
```

To me, `indentation is intelligently removed.` as it says in that other place tells me quite a different story than the first quote.

Anyway, it's no big deal, but as a newcomer reading that, that's what I expected vs. what actually happens. Worth knowing, I guess, if anyone's willing to change the wording to avoid misunderstanding...

Cheers!

**Comment by NotaseCretagen** [comment]
There's another (good)explanation [here](https://nixos.org/nix/manual/#ssec-values), as:

>The second way to write string literals is as an indented string, which is enclosed between pairs of double single-quotes, like so:

>```
''
  This is the first line.
  This is the second line.
    This is the third line.
''
```

>This kind of string literal intelligently strips indentation from the start of each line. To be precise, it strips from each line a number of spaces equal to the minimal indentation of the string as a whole (disregarding the indentation of empty lines). For instance, the first and second line are indented two space, while the third line is indented four spaces. Thus, two spaces are stripped from each line, so the resulting string is

>```
"This is the first line.\nThis is the second line.\n  This is the third line.\n"
```
>Note that the whitespace and newline following the opening '' is ignored if there is no non-whitespace text on the initial line.
```

**Comment by joachifm** [comment]
@NotaseCretagen it's always good to get the perspective of new users, please do not hesitate to point out things that are unclear.

**Comment by danbst** [comment]
Also, because it **is** intelligent, it can break here-documents.
Given default.nix:
```
{
  test = ''
    cat <<EOF
      multiline text
    EOF
   #comment
  '';
}
```
we will get an error
```
$ eval "$(eval echo -e "$(nix-instantiate --eval -E "(import ./default.nix).test")")"
-bash: warning: here-document at line 33 delimited by end-of-file (wanted `EOF')
   multiline text
 EOF
#comment
```

**Comment by NotaseCretagen** [comment]
I'll try to explain it differently:
in this `preceding whitespace is automatically stripped from each line`

`automatically` seems redundant to me, so it's like saying this: 

`preceding whitespace is stripped from each line`

I'll get a PR shortly with an attempted "fix".
