### ISSUE TITLE
Update firefox-beta-bin to 96.0b5

### ISSUE THREAD

**Issue by quantmint** [NixOS/nixpkgs#150752]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 95.0b3 
desired version: 96.0b5

###### Notify maintainers

maintainers: @taku0 @lovesegfault 

###### Note for maintainers
firefox-devedition-bin needs an update too.

Please tag this issue in your PR.

**Comment by rapenne-s** [comment]
firefox-bin has been updated to 96.0 in #154354 so this is obsolete now.
