### ISSUE TITLE
calls: 0.3.1 -> 41.1

### ISSUE THREAD

**Issue by tommy4st** [NixOS/nixpkgs#150838]
There is a change of the repository from [Purism](https://source.puri.sm/Librem5/calls) to official [GNOME GitLab](https://gitlab.gnome.org/GNOME/calls).

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: calls

current version: 0.3.1
desired version: 41.1

###### Notify maintainers

maintainers:
@craigem
@lheckemann 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/136537
