### ISSUE TITLE
telescope-nvim broken in nixos-21.05

### ISSUE THREAD

**Issue by ony** [NixOS/nixpkgs#150899]
### Describe the bug
Attempt to build HomeManager config that includes Neovim with `vimPlugins.telescope-nvim` from same nixpkgs revision of nixos-21.05 fails. [Telescope at 2021-05-16](https://github.com/NixOS/nixpkgs/blob/c5f1ee982246d09ae7f119c13aafcce90286221d/pkgs/misc/vim-plugins/generated.nix#L4806) requires Neovim 0.5+ while Neovim in exact same revision is only [at 0.4.4](https://github.com/NixOS/nixpkgs/blob/c5f1ee982246d09ae7f119c13aafcce90286221d/pkgs/applications/editors/neovim/default.nix#L34).

### Steps To Reproduce
1. Ensure [HomeManager](https://github.com/nix-community/home-manager) installed.
2. Prepare `dummy-home.nix` file with:
    ```nix
    { pkgs, ... }:
    {
      programs.neovim = {
        enable = true;
        plugins = with pkgs.vimPlugins; [ telescope-nvim ];
      };
    }
    ```
2. Try run `HOME_MANAGER_CONFIG=dummy-home.nix home-manager build`

### Expected behavior
You can use Neovim plugins with version of Neovim from same nixpkgs snapshot.

### Screenshots
```console
Error detected while processing /nix/store/lnpiw0rjzfszajlpygwb3a2gx24r2rph-vimplugin-telescope-nvim-2021-05-16/share/vim-plugins/telescope-nvim/plugin/telescope.vim:
line    2:
Telescope.nvim requires at least nvim-0.5. Please update or uninstall
```

### Additional context
It seems that some plugins are updated without testing and Telescope is one of them.  

As a work-around I have to use:
```nix
      (telescope-nvim.overrideAttrs (prev: {
        version = "2020-09-10";
        src = pkgs.fetchFromGitHub {
          owner = "nvim-telescope";
          repo = "telescope.nvim";
          rev = "37152f07fea32a2ae232d98519e0833e986a7c81";  # last supporting 0.4 as per README.md
          hash = "sha256-ufb6Y2pLFFxRfnhELEcwMEsR+fG1gBHXaa/6A4dLeA0=";
        };
      }))
```
*(though still struggling to get it working)*

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix shell nixpkgs\#nix-info --command nix-info -m
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.75, NixOS, 21.05.20211213.c5f1ee9 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"nixos-21.05.4481.c5f1ee98224"`
 - channels(nikolay): `"nixpkgs-unstable-21.11pre310022.14b0f20fa1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: vimPlugins.telescope-nvim
# a list of nixos modules affected by the problem
module:
```

**Comment by Kranzes** [comment]
I would suggest updating to 21.11 since 21.05 will be EOL by the end of the month.

**Comment by ony** [comment]
@Kranzes , that's what I did in the end. But I suspect that problem is still there even in 21.11 I suspect existed in 21.05 before November. It just might be smaller right now when we freshly forked 21.11 from unstable.

**Comment by teto** [comment]
Closing since either it has been fixed by now or no one will.
Note that I am working towards a soluton that should spot this https://github.com/NixOS/nixpkgs/pull/171064
