### ISSUE TITLE
"update-locatedb.service: Failed at step NAMESPACE spawning"

### ISSUE THREAD

**Issue by NotaseCretagen** [NixOS/nixpkgs#15083]
## Issue description

Manually invoking the updatedb systemd service (via `sudo -i systemctl start update-locatedb.service`) fails with: 
`update-locatedb.service: Failed at step NAMESPACE spawning /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start: No such file or directory`

That file exists:
`-r-xr-xr-x 2 root root 222 Jan  1  1970 /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start`
Its interpreter exists:
`-r-xr-xr-x 2 root root 222 Jan  1  1970 /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start`
Running it manually works:
`-r-xr-xr-x 2 root root 222 Jan  1  1970 /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start`
It even created the right file:
```
$ l /var/cache/
total 288K
drwxr-xr-x 1 root root   16 Apr 29 17:06 .
drwxr-xr-x 1 root root   86 Apr 29 17:06 ..
-rw-r--r-- 1 root root 286K Apr 29 17:06 locatedb
```

This is the relevant part of `journal -xe`:

```bash
Apr 29 16:58:32 vbox1 systemd[1]: Started Udisks2 service.
Apr 29 16:59:45 vbox1 sudo[1000]:        z : TTY=pts/0 ; PWD=/home/z ; USER=root ; COMMAND=/run/current-system/sw/bin/bash -c systemctl start update-locatedb.service
Apr 29 16:59:45 vbox1 sudo[1000]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 29 16:59:46 vbox1 polkitd[727]: Registered Authentication Agent for unix-process:1001:10113 (system bus name :1.16 [/run/current-system/sw/bin/pkttyagent --notify-fd 4 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Apr 29 16:59:46 vbox1 systemd[1]: Started Update Locate Database.
Apr 29 16:59:46 vbox1 kernel: audit: type=1130 audit(1461938386.111:61): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=update-locatedb comm="systemd" exe="/nix/store/ncx9b20bpm584kbrp2gvzmdvsgvmgj2c-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 29 16:59:46 vbox1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=update-locatedb comm="systemd" exe="/nix/store/ncx9b20bpm584kbrp2gvzmdvsgvmgj2c-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 29 16:59:46 vbox1 kernel: audit: type=1325 audit(1461938386.111:62): table=filter family=2 entries=0
Apr 29 16:59:46 vbox1 kernel: audit: type=1325 audit(1461938386.111:62): table=raw family=2 entries=0
Apr 29 16:59:46 vbox1 audit: NETFILTER_CFG table=filter family=2 entries=0
Apr 29 16:59:46 vbox1 audit: NETFILTER_CFG table=raw family=2 entries=0
Apr 29 16:59:46 vbox1 audit[1017]: SYSCALL arch=c000003e syscall=272 success=yes exit=0 a0=40000000 a1=7ffffec76e10 a2=40004040 a3=55a096fe0f00 items=0 ppid=1 pid=1017 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="(db-start)" exe="/nix/store/ncx9b20bpm584kbrp2gvzmdvsgvmgj2c-systemd-229/lib/systemd/systemd" key=(null)
Apr 29 16:59:46 vbox1 kernel: audit: type=1300 audit(1461938386.111:62): arch=c000003e syscall=272 success=yes exit=0 a0=40000000 a1=7ffffec76e10 a2=40004040 a3=55a096fe0f00 items=0 ppid=1 pid=1017 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="(db-start)" exe="/nix/store/ncx9b20bpm584kbrp2gvzmdvsgvmgj2c-systemd-229/lib/systemd/systemd" key=(null)
Apr 29 16:59:46 vbox1 kernel: audit: type=1327 audit(1461938386.111:62): proctitle="(db-sta"
Apr 29 16:59:46 vbox1 audit: PROCTITLE proctitle="(db-sta"
Apr 29 16:59:46 vbox1 sudo[1000]: pam_unix(sudo:session): session closed for user root
Apr 29 16:59:46 vbox1 polkitd[727]: Unregistered Authentication Agent for unix-process:1001:10113 (system bus name :1.16, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Apr 29 16:59:46 vbox1 systemd[1017]: update-locatedb.service: Failed at step NAMESPACE spawning /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start: No such file or directory
Apr 29 16:59:46 vbox1 kernel: audit: type=1131 audit(1461938386.150:63): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=update-locatedb comm="systemd" exe="/nix/store/ncx9b20bpm584kbrp2gvzmdvsgvmgj2c-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 29 16:59:46 vbox1 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=update-locatedb comm="systemd" exe="/nix/store/ncx9b20bpm584kbrp2gvzmdvsgvmgj2c-systemd-229/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 29 16:59:46 vbox1 systemd[1]: update-locatedb.service: Main process exited, code=exited, status=226/NAMESPACE
Apr 29 16:59:46 vbox1 systemd[1]: update-locatedb.service: Unit entered failed state.
Apr 29 16:59:46 vbox1 systemd[1]: update-locatedb.service: Failed with result 'exit-code'.
```

### Steps to reproduce
grr, tough...
1. use my config? https://github.com/NotaseCretagen/nixosian/blob/9cca80c018958c0c6392837e89ac72f97f263d76/configuration.nix
2. ensure `services.locate.enable = true;` is set
3. `sudo -i nixos-rebuild switch --fallback`
4. `sudo -i systemctl start update-locatedb.service`
5. `journal -xe`
shows: `update-locatedb.service: Failed at step NAMESPACE spawning /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start: No such file or directory`
6. reboot
7. do 4 and 5 again => same thing.

## Technical details

* System: 16.09.git.32b7b00M (Flounder)  using git sources in /etc/nixos/nixpkgs/ (but hard reset to nixos-unstable channel + applied this modification https://github.com/DamienCassou/nixpkgs/commit/a12c6cba85041386c508af2d4efbc2fc4a027c65 )
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09.git.32b7b00M"

**Comment by NotaseCretagen** [comment]
Well, this is the problem: https://github.com/NotaseCretagen/nixosian/blob/9cca80c018958c0c6392837e89ac72f97f263d76/configuration.nix#L809-L828

According to this: https://help.directadmin.com/item.php?id=614

Basically, mounting /tmp as tmpfs via systemd ... causes that in OP. I tested this by commenting out the above in my config, and keeping only the `boot.tmpOnTmpfs = false;` line.

related: https://github.com/NixOS/nixpkgs/issues/14777

**Comment by boobiesinc** [comment]
I got this even without any such custom tmpfs for /tmp !

Steps:
1. sudo systemctl start update-locatedb.service
2. journalctl -xe

you see "Failed at step NAMESPACE spawning"

**Comment by jerith666** [comment]
I can't reproduce on current `nixos-unstable`; `locate` appears to be working fine and I see no "Failed at step NAMESPACE" errors in `journalctl -u update-locatedb.service`.

**Comment by taohansen** [comment]
I'm getting this on stable.

**Comment by florianjacob** [comment]
Still a problem on NixOS 17.09: locate doesn't work with `boot.tmpOnTmpfs = true;`.

**Comment by bjornfor** [comment]
Does it work with mlocate?

```
  services = {
    locate = {
      enable = true;
      # "findutils" is the default package (as per NixOS 17.03), but "mlocate"
      # has benefits:
      # 1. It (supposedly) updates its database faster.
      # 2. Its 'locate' command checks user permissions so that
      #    (a) users only see files they have access to on the filesystem and
      #    (b) indexing can run as root (without leaking file listings to
      #    unprivileged users).
      locate = pkgs.mlocate;
      localuser = null;  # needed so mlocate can run as root (TODO: improve NixOS module)
    };
  };
```

**Comment by bjornfor** [comment]
> and I see no "Failed at step NAMESPACE" errors in journalctl -u update-locatedb.service.

@jerith666: Be aware that if a service that prints something _immediately_ before it exits it may leave systemd/journald unable to associate those messages with the unit that produced them (a race between the process exiting and journald getting process metadata from the kernel and attaching it to the log entry). Sometimes you have to "journalctl --since=-15m | grep the-service" to see it.

**Comment by florianjacob** [comment]
@bjornfor thanks for the hint, did not know NixOS doesn't use mlocate by default. 👍

…but I can reproduce this issue regardless of whether I use mlocate or findutils, and, as I just noted, regardless of `boot.tmpOnTmpfs` setting. 😦

**Comment by florianjacob** [comment]
@bjornfor found my problem: `update-locatedb.service: Failed at step NAMESPACE spawning /nix/store/rhx6vi4d236w8491i10jdqkdlj9b38cy-unit-script/bin/update-locatedb-start: No such file or directory` does not mean update-locatedb-start can't be found. It means `/var/cache` from the namespace restrictions can't be found, which does not exist on fresh installs. PR trying to fix this at https://github.com/NixOS/nixpkgs/pull/30312
