### ISSUE TITLE
nixos-container.pl has overly strict sanity checks

### ISSUE THREAD

**Issue by sh01** [NixOS/nixpkgs#15089]
## Issue description

nixos-container.pl checks container names against "^[a-zA-Z0-9-]+$" before operating on them. This is overly strict, and in particular more strict than what NixOS will create via configuration.nix container specs, which support e.g. container names with underscores just fine.
This means such containers can be created without issue, and nixos-container will then refuse to operate on them.
The relevant check should be relaxed to match the limits of configuration.nix, or removed entirely.
### Steps to reproduce

Declaratively produce a container containing an underscore in its name. Attempt to manipulate it with nixos-container.
## Technical details
- System: NixOS 16.03.581.e409886 (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.616.4ac4b35

**Comment by globin** [comment]
I've allowed `_` but technically one can use quotes in the container name in the declarative configuration which would allow any character so the check is still needed and you can still create invalid container names. This would have to be checked in the nixos config evaluation.
