### ISSUE TITLE
Appflowy

### ISSUE THREAD

**Issue by DarkOnion0** [NixOS/nixpkgs#150877]
**Appflowy**
_AppFlowy is an open-source alternative to Notion (a note-taking app)_

**Metadata**

* homepage URL: https://www.appflowy.io/
* source URL: https://github.com/AppFlowy-IO/appflowy
* license:  AGPL-3.0
* platforms: linux (x86 et aarch64), darwin

**Comment by colemickens** [comment]
dupe: https://github.com/NixOS/nixpkgs/issues/146724
