### ISSUE TITLE
nim: downloading packages.json with nimble fails with "Illegal storage access"

### ISSUE THREAD

**Issue by bandithedoge** [NixOS/nixpkgs#150982]
### Describe the bug
Trying to build any Nim package that has dependencies outside of Nix fails with `SIGBUS: Illegal storage access. (Attempt to read from nil?)`

```console
❯ nimble build
  Verifying dependencies for nix@0.1.0
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
SIGBUS: Illegal storage access. (Attempt to read from nil?)
fish: Job 1, 'nimble build' terminated by signal SIGBUS (Misaligned address error)
```

### Steps To Reproduce
1. `nimble init`
2. Add a dependency to the `.nimble` file
3. `nimble build`

### Expected behavior
`package.json` gets downloaded and the package is built.

### Notify maintainers
@ehmry

### Metadata

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(bandithedoge): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre330454.9cae36cff14"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Maintainer information:
```yaml
attribute:
	- nim
module:
```

**Comment by ehmry** [comment]
I will take a look at the issue, but are you working a Nix library? I started one a few years ago but never did anything serious with it: https://github.com/nix-community/flake-nimble/blob/master/src/private/nix.nim

**Comment by bandithedoge** [comment]
I was actually trying to do something with that but the issue happens with any other Nim project as well.

**Comment by ehmry** [comment]
Works for me. Nimble crashing is normal in my experience. You could file a in issue upstream if you figure out what is going on but try to avoid mentioning Nixos.

**Comment by bandithedoge** [comment]
![Screen Shot 2021-12-17 at 20 49 30](https://user-images.githubusercontent.com/26331682/146599871-776ef523-7b6f-441e-a620-dbd3478daf90.png)

Here are some more things I just found.
