### ISSUE TITLE
[staging-next] gdm / gnome-shell hang on startup

### ISSUE THREAD

**Issue by fabianhjr** [NixOS/nixpkgs#150985]
### Describe the bug

gdm / gnome hang on startup on current staging-next ( #148396 )

### Steps To Reproduce

rebuild on staging-next with gdm and gnome set

```
    xserver = {
      desktopManager.gnome.enable = true;
      displayManager.gdm.enable = true;
   };
```

### Additional context

Reverting 7fd3e067cd2929e1c0b59287b5b799ad7450f59d (mutter: 41.1 → 41.2, #150543) fixes the issue

### Notify maintainers

@NixOS/gnome

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre338278.b0bf5f888d3, nixos-small-22.05pre338428.69958994ab2"`
 - channels(fabian): `"home-manager, nixos-19.03-19.03.173691.34c7eb7545d, nixos-19.09-19.09.2522.75f4ba05c63, nixos-20.03-20.03.3330.1db42b7fe38, nixos-20.09-20.09.4407.1c1f5649bb9, nixos-21.05-21.05.4470.3b422991781, nixos-21.11-21.11.334247.573095944e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by jtojnar** [comment]
Weird, it seems to work on nixos-unstable. Anything weird in journal?

**Comment by fabianhjr** [comment]
Nothing, afaik it gets stuck and doesn't crash since I can change TTYs and when I go back to TTY 7 it retains whatever was getting displayed from the other 1-6 TTY (TTY8 is a blank screen)

**Comment by vcunat** [comment]
Any plans around this?  The current staging-next iteration has been running for almost three weeks.

**Comment by fabianhjr** [comment]
I don't have the technical know-how to debug this; could someone else reproduce it on staging next? (I am running staging-next with the mutter commit reverted)

**Comment by jtojnar** [comment]
I still cannot reproduce this in VM. Are you running it on real hardware?

**Comment by fabianhjr** [comment]
Yes, on real hardware but on staging-next ( `nixpkgs   staging-next +  nixos-rebuild -I nixpkgs="$PWD" build`)

**Comment by fabianhjr** [comment]
Cannot reproduce, a version increase or other changes might have solve the issue.

Closing
