### ISSUE TITLE
Packaging Request:  Electrum Personal Server

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#150927]
**Project description**

Electrum is one of the most popular desktop Bitcoin wallet applications, however it does not run its own full node, and sends and receives data and txs to other full nodes in the network.  Electrum Personal Server enables Electrum to connect to a local Bitcoin Core full node, which it can't do on its own, improving privacy and functionality (faster searches, etc).

**Metadata**

* homepage URL: https://github.com/chris-belcher/electrum-personal-server
* source URL: https://github.com/chris-belcher/electrum-personal-server
* license: MIT
* platforms: unix, linux, darwin

**Comment by prusnak** [comment]
You can use electrs and fulcrum - both packaged in Nixpkgs.

Unless there is strong reason for using EPS, I prefer not to package yet another implementation.

Closing. Feel free to reopen when you really really need EPS.
