### ISSUE TITLE
Title not visible properly

### ISSUE THREAD

**Issue by TarunavBA** [NixOS/nixpkgs#151062]
### Describe the bug
The NixOS Logo is not clearly visible in dark mode in GitHub

### Steps To Reproduce
1. Go to appearance in GitHub 
2. change it to dark mode
3. see the bug

### Expected behavior
I expect the logo to be seen more clearly. 

### Screenshots
Not needed since it can be reproduced by anyone just follow the steps I have above. 

### Additional context
Add a sticker like effect to make it support dark mode too

**Comment by veprbl** [comment]
Please file to https://github.com/NixOS/nixos-artwork

**Comment by TarunavBA** [comment]
Ok @veprbl
