### ISSUE TITLE
smplayer: Could not find qmake configuration file linux-g++.

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#15107]
## Issue description

Using unstable channel and refuses to rebuild due to smplayer error.

Could not find qmake configuration file linux-g++.
Error processing project file: /tmp/nix-build-smplayer-16.1.0.drv-0/smplayer-16.1.0/src/smplayer.pro
Makefile:43: recipe for target 'src/smplayer' failed
make: *** [src/smplayer] Error 3

### Steps to reproduce

Use unstable branch. Add smplayer to nix packages.

## Technical details

16.03.616.4ac4b35 (Emu)
nix-env (Nix) 1.11.2

**Comment by vbgl** [comment]
It should be fixed by 5de3cfe21039153757236d9569543e674cfaa6b6
