### ISSUE TITLE
Package Request: Add vcpkg

### ISSUE THREAD

**Issue by gracicot** [NixOS/nixpkgs#151096]
**Project description**

vcpkg is a package manager for C++ and many large and very small libraries are packaged there. Many of my projects use it for CMake configuration and for its toolchain file that automatically download and build libraries.

I want to setup dev environment with nix and this is one of the packages I'm looking for that I've been building manually (since the brew packaged vcpkg is not well configured for manifest files support)

**Metadata**

* homepage URL: https://vcpkg.io/
* source URL: https://github.com/microsoft/vcpkg
* license: MIT
* platforms: unix, linux, darwin, windows

**Comment by AndersonTorres** [comment]
I'll try something now.

**Comment by AndersonTorres** [comment]
Reading the [AUR script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vcpkg-git), it looks like a case for a module, not merely a package.

**Comment by gracicot** [comment]
@AndersonTorres I'm not sure what's the difference between a package and a module... but if it allows me to download a prebuilt binary of vcpkg that I can simply install, that's fine for me. Know that this package manager is made (partly) in C++ and need compiling. The build script is the `bootstrap-vcpkg.sh` you see there.

**Comment by AndersonTorres** [comment]
> @AndersonTorres I'm not sure what's the difference between a package and a module...

Maybe I am over-engineering here.

Reading the AUR script, vcpkg uses systemd scripts/services. Therefore I think it requires more integration with the operating system.
Modules are, roughly speaking, designed to "patch" and configure NixOS (the operating system).
