### ISSUE TITLE
Provide a way to change the location of the Xorg authority file

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#15110]
## Issue description

I have been using a custom location for the so called `.Xauthority` file by setting the `XAUTHORITY` variable in `config.environment.shellinit` script . I'm not sure whether this was respected or programs and services ignored it but somehow they all managed to connect to Xorg.
Now, after the latest unstable channel update, something must have changed because Xorg tries to write the file in the default location and the login manager, services, programs and even games fail to start; it took me a day to realize the problem was the missing authority file.
### Steps to reproduce

Move or delete `$HOME/.Xauthority`, set `XAUTHORITY` to something.
## Technical details
- System: 16.09pre82105.7465bcd (Flounder)
- Nix version: 1.11.2
- Nixpkgs version: 16.09pre82105.7465bcd

**Comment by rnhmjoj** [comment]
Yes, setting XAUTHORITY to something still doesn't really work.
I tried with this and couldn't even log into X:
```nix
{
  environment.variables.XAUTHORITY= "$HOME/.config/x/auth";
  environment.shellInit = ''
    mkdir -p $HOME/.config/x
  '';
}
```

**Comment by Profpatsch** [comment]
What does `echo $XAUTHORITY` give you in that case?

**Comment by rnhmjoj** [comment]
It is set correctly set but apparently ignored (by slim at least): `/home/vm/.config/x/auth`

**Comment by rnhmjoj** [comment]
It could be, but it used to work and stopped at some point so I guessed it was caused by a change in nixos.

**Comment by rnhmjoj** [comment]
It's not important to me anymore because I've since been using `startx` instead of a display manager. Anyway, I think the proper way to inform the display manager about the location of the authority file is setting `systemd.globalEnvironment.XAUTHORITY`.
