### ISSUE TITLE
cannot find nix.useSandbox

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#15112]
## Issue description

The template text for a PR mentions: ``Tested using sandboxing (nix.useSandbox on NixOS``, but I can't find that option, neither in the provided link nor in the [online search](https://nixos.org/nixos/options.html).

**Comment by joachifm** [comment]
You're right, it's `nix.useChroot`

**Comment by joachifm** [comment]
Err, I should say, it used to be, `useSandbox` is what you're supposed to use now

**Comment by joachifm** [comment]
I think the reason you can't find it, is that 7cf8daa2bbf7e9ac1b57305a22547271dca28a6e didn't make it to the release.

**Comment by magnetophon** [comment]
Ah, should have known...

**Comment by joachifm** [comment]
I agree its a bit confusing, though, so perhaps it'd make sense to backport that change. Doesn't look like it could break anything ...

**Comment by gilligan** [comment]
*bump* I stumbled over the exact same thing. If I get instructed to use something specific and the link pointing me to that does not work that is really not helpful.

**Comment by joachifm** [comment]
Looks to me like https://github.com/NixOS/nixpkgs/commit/7cf8daa2bbf7e9ac1b57305a22547271dca28a6e could be safely backported, what do you think @vcunat?

**Comment by vcunat** [comment]
@joachifm: I believe the problem is the other way around &ndash; the default nix on 16.03 still uses only the old *chroot** naming.

**Comment by vcunat** [comment]
We might "postpone" parts of the commit (partially revert it for now), as the old option naming is accepted by all nix versions, but would be a complication and it wouldn't avoid inconsistency at some point anyway.

**Comment by joachifm** [comment]
Hrm, I see ... What about mentioning both in the template? Lacks polish but is simple and might be sufficient to hold us over until the next release.

**Comment by joachifm** [comment]
Hm, I guess sticking with only `useChroot` in the template makes the most sense.

**Comment by vcunat** [comment]
Right, done in 156105c48. I'm fairly certain noone will remember to revert in on the next release, but that doesn't seem a big deal anyway...
