### ISSUE TITLE
telegram-desktop: random crash with "stack smashing detected" in logs

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#151133]
I was using Telegram earlier and it suddenly crashed. Looking at the `journalctl` logs, it seems it accidentally smashed the stack and it caused a SIGABRT. I have compiled a bit of info about this, and it seems `jemalloc` may be the "culprit": Telegram developers recommend compiling jemalloc using Clang instead of GCC to avoid this issue.

https://github.com/telegramdesktop/tdesktop/issues/16673
https://bugs.archlinux.org/task/71745

### Version
Happens with `telegram-desktop` version `3.1.11`.

### Possible fixes
Using a jemalloc version compiled with Clang should solve the issue, as it did for Arch Linux. I don't think it's a high priority nonetheless since otherwise it seems fairly stable, but it could be something worth looking into.

### Maintainers
Tagging @oxalica, @primeos, @VergeDX

**Comment by VergeDX** [comment]
It builds successfully after switch to clangStdenv, the change is easy to make.

**Comment by oxalica** [comment]
I've never met this issue. I'm curios why switching to `clang` would "fix" it, or is it just hide things via disabling stack protection?

Just a note: using `clang` + `jemalloc` may suffer mis-compilation (#146382), but there's already a fix for it in `staging-next` #148107. So this should be fine.

**Comment by blablablerg** [comment]
The stack smashing bug happens quite often to me.

**Comment by neirenoir** [comment]
Oh, hello @patka-123.

No, it does not happen anymore. I kinda forgot about this issue when it stopped happening. Gonna close the issue now, and will reopen if it somehow becomes relevant again.
