### ISSUE TITLE
Package request: nb

### ISSUE THREAD

**Issue by j-steinbach** [NixOS/nixpkgs#151138]
**Project description**
_from the repo:_ CLI and local web plain text note‑taking, bookmarking, and archiving with linking, tagging, filtering, search, Git versioning & syncing, Pandoc conversion, + more

_mine:_ This appears to be the most advanced cli-note-taking-utility available. It allows maintaining a personal wiki/zettelkasten from the cli, without needing an abstraction like Dendron, Obsidian, Roam, Org-Roam, TiddlyWiki, VimWiki, etc.

Building: _nb_ is on NPM and can also be built from a make file

**Metadata**

* homepage URL: https://xwmx.github.io/nb/
* source URL: [xwmx/nb](https://github.com/xwmx/nb)
* license: AGPL-3.0 License 
* platforms: no idea what you want to know, so I guess _linux_?

**Comment by j-steinbach** [comment]
I found two "private" packages that already build this:

- https://github.com/brynedwards/nixos-config/blob/87cb58105a6834e1c968d77043c037ad3fe86b95/packages/nb.nix 
- https://github.com/Stupremee/nix/blob/ec3f20c8a408b6874e37dc3de5ab28fa5a403525/pkgs/nb.nix. 

It looks a little bit hacky though, so I will leave this in the hands of experts:

_Note: The below code also includes the ZSH [tab-completion](https://github.com/xwmx/nb/tree/master/etc). There is also one for bash. No idea how to do it with fish._

```nix
(
	stdenv.mkDerivation rec {
		pname = "nb";
		version = "6.7.9";
		commit =  "337ae2af42e39ecb42d8b29d957b8333ae1fb418";
		shortcommit = " 337ae2a";

		src = fetchFromGitHub {
			owner = "xwmx";
			repo = "nb";
#rev = "${version}";
			rev = commit;
			sha256 = "sha256-TCuFRQ5t620dNhGAFT6ux8egLydElHi/wRWMPvp2QZ0=";
		};

		buildInputs = [
			git
				bat
				pandoc
				ripgrep
				ripgrep-all
				exa
#xpdf # BROKEN
				nmap
		];

		prePatch = ''
			rm Makefile
			'';

		installPhase = ''
			install -D ./etc/nb-completion.zsh $out/share/zsh/site-functions/_nb
			mkdir -p $out/bin
			install -D nb $out/bin/nb
			install -D bin/{bookmark,notes} $out/bin/
			'';

		meta = with lib; {
			description = "A command line and local web note‑taking, bookmarking, archiving, and knowledge base application.";
			homepage = "https://xwmx.github.io/nb/";
			platforms = with platforms; linux;
			changelog = "https://github.com/xwmx/nb/releases/tag/${version}";
		};
	}
)
```

**Comment by AndersonTorres** [comment]
Some optional packages look like "look at them into PATH".

**Comment by AndersonTorres** [comment]
Well, for now I am taking the dumb path of "add it to nodePackages"....

**Comment by uninsane** [comment]
#110962 added this `nb` package. i'm using it now, can confirm all the basic functionality works (`nb ls`, `nb show`, `nb edit`, `nb add`, `nb browse`). it sounds like there might be some rough edges conditional on how the user provisions their PATH when adding `nb`'s optional dependencies (like your editor or terminal web-browser). i just put these under home-manager's `home.packages` and `nb` finds them fine.
