### ISSUE TITLE
Steam/Proton: Proton Fails to Load OpenGL

### ISSUE THREAD

**Issue by seandheath** [NixOS/nixpkgs#151194]
### Describe the bug
I'm trying to launch Noita using Proton on Steam. The client attempts to launch the game but it immediately crashes.

The Proton log shows the following error:

```
290.182:010c:0110:err:wgl:X11DRV_WineGL_InitOpenglInfo  couldn't initialize OpenGL, expect problems
```
I have OpenGL and my CPU configured as follows:
```
  boot.kernel.sysctl = {
    "dev.i915.perf_stream_paranoid" = 0;
  };
  boot.kernelParams = [ "i915.enable_psr=0" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      libva
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-media-driver
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      libva
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
    ];
  };
```

I've tried both 21.05 stable and nixpkgs-unstable. I've tested mesa using the following:

```
nix run nixpkgs#glxinfo
nix run nixpkgs#pkgsi686Linux.glxinfo
```
 and both appear to be functioning normally.

I set the launch configuration for the game to use OpenGL 4.6 (as indicated by glxinfo) using the following game specific launch parameters:

```
MESA_GL_VERSION_OVERRIDE=4.6 MESA_GLSL_VERSION_OVERRIDE=460 PROTON_LOG=1 %command%
```

I have tried pipewire and pulseaudio. I've enabled 32 bit support for both.

I have attempted to enable steam-native per instructions on the NixOS wiki.

I have tried using Proton GE (installed using protonup) as well as Proton Experimental and Proton 5.13.

I still get the error. I'm not sure what else to try or how else to debug this.

### Steps To Reproduce

1. Enable steam using `programs.steam.enable = true;`
2. Enable steam compatibility layer for non-linux games in the settings menu
3. Install Noita
4. Launch Noita in the steam client 

### Expected behavior
The game should open and run normally.

### Additional context

 I share the majority of my configuration between my AMD/Nvidia desktop and my Intel laptop and the game opens and runs correctly on the AMD/Nvidia machine.

### Notify maintainers

@jagajaga @jonringer

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"nixos-21.05.4394.2553aee74fe, nixos-hardware"`
 - channels(user): `"home-manager-21.05, nixos-unstable-21.11pre328987.c935f5e0add"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
module:
steam
```

**Comment by jansol** [comment]
Duplicate & more affected games: #148483

**Comment by jtrees** [comment]
I'm also getting this for Final Fantasy X.

**Comment by jansol** [comment]
@seandheath @jtrees both games should work with [PR 184842](https://nixpk.gs/pr-tracker.html?pr=184842)

**Comment by SuperSamus** [comment]
Shouldn't this be closed now that it's fixed?
