### ISSUE TITLE
Package request: GDLauncher

### ISSUE THREAD

**Issue by l4ssc** [NixOS/nixpkgs#151244]
**Project description**
> GDLauncher is a custom open-source Minecraft launcher written from the ground up in electron/react. Its main goal is to make it easy and enjoyable to manage different Minecraft versions and install forge/fabric, bringing the playing and modding experience to the next level!

**Metadata**

* homepage URL: https://gdevs.io
* source URL: https://github.com/gorilla-devs/GDLauncher
* license: GPLv3, [LICENSE](https://github.com/gorilla-devs/GDLauncher/blob/master/LICENSE)
* platforms: darwin, linux

**Comment by lpuv** [comment]
Any progress on this?

**Comment by PassiveLemon** [comment]
Someone has made a derivation [here](https://github.com/andOrlando/nix-dotfiles/blob/main/programs/gdlauncher/default.nix) but I have recursion issues when importing it. Maybe someone else can figure that out?

**Comment by QuantumCoded** [comment]
If you really need to get this to work you can wrap the appimage using `appimageTools`.

```nix
{ appimageTools, fetchurl }:

appimageTools.wrapType1 {
  name = "gdlauncher";
  src = fetchurl {
    url = "https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.30/GDLauncher-linux-setup.AppImage";
    hash = "sha256-4cXT3exhoMAK6gW3Cpx1L7cm9Xm0FK912gGcRyLYPwM=";
  };
}
```

**Comment by PassiveLemon** [comment]
I've got an almost working derivation for this: https://github.com/NixOS/nixpkgs/pull/244249
The dependencies currently cause a lot of issues which need hacky workarounds. Except, all these do it cause it to not error when building, and doesn't actually build GDL. If anyone has suggestions for it, please, do let me know.

**Comment by huantianad** [comment]
The launcher has now risen up from the ashes as [GDLauncher Carbon](https://github.com/gorilla-devs/GDLauncher-Carbon), new repo and now under an unfree (BSL) license. 

Should this new version be in its own issue?

Also worth discussing if this should be packaged as a binary wrapper or from source. Quoting from the discord, if compiled from source the app "wont connect to our server / no curseforge support and you have to get your own mc auth stuff".

**Comment by PassiveLemon** [comment]
The new version should be in its own new issue since it's a different project. As for the source built problems, I'll give it a test later and see what I can come up with. Hopefully it's better than the original GDLauncher

**Comment by TsubakiDev** [comment]
GDLauncher Carbon has been added to nixpkgs. If you want to use legacy GDLauncher, try the `appimageTools` solution given above.
