### ISSUE TITLE
systemd-boot update touches EFI variables when told not to

### ISSUE THREAD

**Issue by Informatic** [NixOS/nixpkgs#151336]
### Describe the bug
During systemd-boot update step `bootctl` attempts to touch EFI variables, even when `boot.loader.efi.canTouchEfiVariables` is set to `false`.

### Steps To Reproduce
1. Install NixOS 21.05 with systemd-boot and `boot.loader.efi.canTouchEfiVariables = false;`
2. Upgrade to NixOS 21.11 (fa8aa7ff5995d539aabc6f6a009dfcc1e3fd33a8)
3. Configuration switch fails with:
```
Copied "/nix/store/rgjrn2vl55pyxahfggvbdgl5g0xn0an1-systemd-249.5/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/rgjrn2vl55pyxahfggvbdgl5g0xn0an1-systemd-249.5/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
updating systemd-boot from (247) to (249.5)
Failed to create EFI Boot variable entry: Input/output error
Traceback (most recent call last):
  File "/nix/store/5f69p1syxlsfyxxb54zs1gc59ngf2cxz-systemd-boot", line 314, in <module>
    main()
  File "/nix/store/5f69p1syxlsfyxxb54zs1gc59ngf2cxz-systemd-boot", line 267, in main
    subprocess.check_call(["/nix/store/rgjrn2vl55pyxahfggvbdgl5g0xn0an1-systemd-249.5/bin/bootctl", "--path=/boot", "update"])
  File "/nix/store/wl02plhc6zf84m6x9984l42wnnnbly5m-python3-3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/rgjrn2vl55pyxahfggvbdgl5g0xn0an1-systemd-249.5/bin/bootctl', '--path=/boot', 'update']' returned non-zero exit status 1.
```
An error is just an indication of update trying to touch EFI variables. (I have EFI vars touching disabled on that system because of some unrelated firmware breakage)
Manually running `bootctl --path=/boot update --no-variables` properly finishes, further switches work fine.

### Expected behavior
systemd-boot update should not touch EFI variables during upgrade.

### Notify maintainers
@andir @flokli @kloenk

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by LouisDK1** [comment]
I had a similar issue which I fixed by running "sudo nixos-rebuild --install-bootloader switch"

**Comment by ElvishJerricco** [comment]
@Mic92 The fix for this got reverted in https://github.com/NixOS/nixpkgs/commit/865a2cf8c1b5038d7beee47a2f39d4e20bbe433c
