### ISSUE TITLE
16.03 has broken spotify, lacks sheenobu in maintainers.nix

### ISSUE THREAD

**Issue by srhb** [NixOS/nixpkgs#15131]
## Issue description
accca28dfdbf8a6b7869cf0a454ce9d16b82eeb2 has been applied in 16.03, but relies on 15f46547d9feaef9c65cdcea5e3859deec95048f which hasn't.

The process for cherry picking it onto the channel isn't clear to me, since channels/nixos-16.03 seems to have seen zero PRs in its lifetime.

### Steps to reproduce
nix-env -iA nixos.spotify
produces

    error: undefined variable ‘sheenobu’ at /nix/store/p5n1qbzk61wnzg2syzcdjnvaxi5qqf7l-nixos-16.03.678.2597f52/nixos/pkgs/applications/audio/spotify/default.nix:107:66

## Technical details
    nixos-version: 16.03.678.2597f52 (Emu)
    nix-env --version: nix-env (Nix) 1.11.2
    nixpkgs version: 16.03.678.2597f52

**Comment by 7c6f434c** [comment]
I think pull requests go against `release-16.03`

`channel-…` are for things already built on Hydra

**Comment by bjornfor** [comment]
Fixed in e843b35e398878da7b809f7a65a1decabcce1125.
