### ISSUE TITLE
Why does the sdImage builder compress the ext4 image regardless of `sdImage.compressImage`?

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#151359]
This is particular wasteful when using binfmt emulation to build images for `aarch64`. I'd much prefer if the `build.sdImage` derivations args would allow me to opt out of any unnecessary compression.

https://github.com/NixOS/nixpkgs/blob/ae969de2bbf871583109d10f812d854ae8d4a878/nixos/modules/installer/sd-card/sd-image.nix#L21

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/commit/70c5a7806256518c9e63aceacba881da212a9125
@lovesegfault @samueldr

**Comment by lovesegfault** [comment]
Because without this the derivation is >3GB in size and hydra explodes.

**Comment by samueldr** [comment]
@lovesegfault "regardless of `sdImage.compressImage`".

The way it was implemented initially, it should be possible to not compress. Before the zstd work you did, an option `sdImage.compressImage` was added, which defaults to *true*. Your changes always use `true`. AFAICT using `compressImage = config.sdImage.compressImage;` should fix this to work as expected.

**Comment by wucke13** [comment]
That would be nice. At least when I'm locally building I do not care so much about the derivations size but much more about completely unnecessarily compressing and decompressing using emulation.

**Comment by wucke13** [comment]
@amarshall Yes I can confirm, this should be fixed now.
