### ISSUE TITLE
libocsync.so.0 not found after Owncloud client upgrade.

### ISSUE THREAD

**Issue by Mayeu** [NixOS/nixpkgs#15130]
## Issue description

After  upgrading the Owncloud client to 2.1.1, I'm can't launch it anymore. I updated the channel using `sudo nix-channel --update`, then reinstalled Owncloud. I did not upgrade my full NixOS (see system later on).

I get the following error:
```
owncloud: error while loading shared libraries: libocsync.so.0: cannot open shared object file: No such file or directory
```

I can see the file can be found in the `lib/owncloud` dir:
```
$ ls /nix/store/fpcmhd1incaj4bv6kih9d911z2vnlw8r-owncloud-client-2.1.1/lib/owncloud 
libocsync.so  libocsync.so.0  libocsync.so.2.1.1
```

(Poking the people that are in the history of the owncloud-client: @micxjo, @qknight, @arno01)

### Steps to reproduce

* Update channel
* Install the Owncloud-client 2.1.1

## Technical details

* System: NixOS 16.09pre79453.32b7b00 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre82105.7465bcd

**Comment by crunchop** [comment]
I can confirm this error. Until the package is fixed in the channel you can do an override of the package and uncomment the commented configurephase. 
``` haskell  
    packageOverrides = pkgs: rec {

      myowncloudclient = pkgs.stdenv.lib.overrideDerivation pkgs.owncloudclient (oldAttrs: {
        name = "owncloud-client-2.1.0";

	configurePhase = ''
		mkdir build
		cd build
		cmake -DBUILD_WITH_QT4=on \
		-DCMAKE_INSTALL_PREFIX=$out \
		-DCMAKE_BUILD_TYPE=Release \
		..
		'';
      });
  }; 

```

This worked for me.

**Comment by Mayeu** [comment]
That's solve it :) Thank you!

So should I submit a PR that uncomment the configure phase? Why is it commented in the first place anyway?

**Comment by HappyEnte** [comment]
Glad it worked :)

It seems like it was added with the initial commit of the package. I guess the package build fine beforehand without the additional configurePhase configuration.

 I think a PR to uncomment it would make sense to get it back into working state right now but
the build options might be worth to take a second look into. Isn't the owncloud client already completely ported over to qt5 for instance?

**Comment by Mayeu** [comment]
Not sure... I'm first going to send a PR to make it work, then we'll see for QT5 :)
