### ISSUE TITLE
Package Request: OpenSearch

### ISSUE THREAD

**Issue by afics** [NixOS/nixpkgs#151464]
**Project description**
Elasticsearch Fork

Via homepage:
> OpenSearch is a community-driven, open source search and analytics suite derived from Apache 2.0 licensed Elasticsearch 7.10.2 & Kibana 7.10.2. It consists of a search engine daemon, OpenSearch, and a visualization and user interface, OpenSearch Dashboards. OpenSearch enables people to easily ingest, secure, search, aggregate, view, and analyze data. 

**Metadata**

* homepage URL: https://opensearch.org/
* source URL: https://github.com/opensearch-project/OpenSearch
* license: apache-2.0
* platforms: unix, linux, darwin, ...

**Comment by shyim** [comment]
Has been merged with https://github.com/NixOS/nixpkgs/pull/175000
