### ISSUE TITLE
dwarf-fortress: cannot open libz

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#15146]
## Issue description

Running dwarf-fortress causes libz error message. It also happens if I don't do a pure shell and have zlib installed.

### Steps to reproduce

ryantm@nixos ~/p/nixpkgs (1603)$ nix-shell --pure -I nixpkgs=~/p/nixpkgs -p dwarf_fortress

[nix-shell:~/p/nixpkgs]$ dwarf-fortress 
Using /home/ryantm/.local/share/df_linux as Dwarf Fortress overlay directory.
If you do any changes in it, don't forget to clean it when updating the game version!
We try to detect changes based on data directories being symbolic links -- keep this in mind.

/nix/store/246rjsdfq04jf12yikpfyf0iqzs0k22i-dwarf-fortress-env-0.42.05/libs/Dwarf_Fortress: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)  
```
nixos-version
16.03.git.e843b35M (Emu)
```
* Nix version: (run `nix-env --version`)
```
nix-shell --pure -I nixpkgs=~/p/nixpkgs -p dwarf_fortress
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
nixpkgs git e843b35

**Comment by abbradar** [comment]
This was fixed in bdf714c3039411bcaa942822cfc7c039a391a552. You can cherry-pick the patch (do you need help with this?).
