### ISSUE TITLE
Amazon AMIs seem to expect ≥ 20GB of EBS storage

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#15148]
## Issue description

Amazon EC2 refuses to instantiate NixOS instances with less than 20GB of storage. Clearly the base NixOS install needs a lot less.

Who uploads the NixOS community AMIs and is this 20GB number something that can be set somewhere?

### Steps to reproduce

Go in EC2, try creating an instance with, say, 5GB in EBS storage, you'll get this error:

![image](https://cloud.githubusercontent.com/assets/3359345/14945476/2c453d0e-100a-11e6-9e91-b73ef018f5bf.png)

## Technical details

* AMI name: nixos-16.03.659.011ea84-x86_64-hvm-ebs - ami-ff27a98c

**Comment by obadz** [comment]
Looks like this is the culprit: https://github.com/NixOS/nixpkgs/blob/master/nixos/maintainers/scripts/ec2/create-amis.sh#L168

```bash
                        extraFlags="-b /dev/sda1=$snapId:20:true:gp2"
```

The doc seems to say that we must specify a size if we want to specify any subsequent arguments:

```
$ ec2-register --help
[…]
           - '[<snapshot-id>][:<size>[:<delete-on-termination>][:<type>[:<iops>]][:encrypted]]': indicates
             that an Amazon EBS volume, created from the specified Amazon EBS
             snapshot, should be exposed at the specified device. The following
             combinations are supported:
          
              - '<snapshot-id>': the ID of an Amazon EBS snapshot, which must
                be owned by the caller. May be left out if a <size> is
                specified, creating an empty Amazon EBS volume of the specified
                size.
          
              - '<size>': the size (GiBs) of the Amazon EBS volume to be
                created. If a snapshot was specified, this may not be smaller
                than the size of the snapshot itself.
          
              - '<delete-on-termination>': indicates whether the Amazon EBS
                volume should be deleted on instance termination. If not
                specified, this will default to 'true' and the volume will be
                deleted.
          
              - '<type>': specifies the volume type. This can be either
                'gp2', 'io1' or 'standard'. Defaults to standard.
          
              - '<iops>': The requested number of I/O operations per
                second that the volume can support. Only valid for io1
                volumes.
          
              - 'encrypted': Indicates that the volume should be encrypted.
```

**Comment by obadz** [comment]
@edolstra: do you think ca155dd would work and enable EC2 users to provision smaller EBS volumes for NixOS?

**Comment by edolstra** [comment]
BTW, the EC2 error is wrong, since the snapshot snap-7ef6f293 has a volume size of 3 GB (probably the `diskSize` of 2048 in `nixos/maintainers/scripts/ec2/amazon-image.nix` plus some padding). But apparently the size in the block device mapping is used as a minimum rather than as a default.

**Comment by obadz** [comment]
@edolstra: how about 4315d5634f23fe1b33fac633545cfe03cc31b3ac ?

cc // @cleverca22

**Comment by edolstra** [comment]
@obadz Looks good to me.

**Comment by obadz** [comment]
@edolstra, cool. I've never actually run the whole thing though because I'm not setup to upload AMIs. Who usually uploads the community AMIs?

**Comment by edolstra** [comment]
Usually I do, sometimes @rbvermaa.

**Comment by obadz** [comment]
@edolstra / @rbvermaa, ok I've pushed this to master, pls keep in the back of you mind next time your generate AMIs. Also might make sense to cherry-pick to stable next time you generate AMIs for 16.03?

**Comment by obadz** [comment]
@edolstra / @rbvermaa:

Hey guys, I see that new images were pushed to Amazon (1073.73e28bc) but still require 20Gb of space. Any chance to use this commit to generate images that require no more space than they need?

**Comment by edolstra** [comment]
Sorry, didn't cherry-pick this until after I generated the new AMI. It should be included next time the AMI get generated.
