### ISSUE TITLE
"Search NixOS options" outdated?

### ISSUE THREAD

**Issue by flosse** [NixOS/nixpkgs#15142]
## Issue description

On https://nixos.org/nixos/options.html I can read `Last changed on 2015-09-04` but I have no idea if this tells me the date of the web page or the according nixos version!?

It would be nice if there were buttons for each channel, like `NixOS 15.09`, `NixOS 15.09` and `NixOS unstable`.

**Comment by sheenobu** [comment]
If I understand: The Last changed on refers to the last time the page source https://github.com/NixOS/nixos-homepage/blob/master/nixos/options.tt was modified in git. 

The source of the options is this: https://nixos.org/nixos/options.json.gz but I can't tell when that was created. You'll probably want to move this issue to the https://github.com/NixOS/nixos-homepage git repo.

**Comment by davidak** [comment]
there is already an issue for that: https://github.com/NixOS/nixos-homepage/issues/53

**Comment by joachifm** [comment]
@davidak thank you, closing this one
