### ISSUE TITLE
`sssctl` can't find the `memberof` module 

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#151597]
### Describe the bug

This started with the update from 21.05 to 21.11.

When I execute `sudo sssctl domain-status`, I get the following error:

```
[sssd] [ldb] (0x0010): WARNING: Module [memberof] not found - do you need to set LDB_MODULES_PATH?
[sssd] [ldb] (0x0010): Unable to load modules for /var/lib/sss/db/cache_<MY.DOMAIN>.ldb: (null)
[sssd] [sss_tool_route] (0x0010): Command initialization failed [5] Input/output error
```

Further on, SSSD doesn't work in our setup, neither login nor `getent passwd` works on any ad supplied user. The following message is in the log:

```
There is no server that can be written into kdc info file.
```

So far I believe, both issues are related, e.g. not only the `sssctl` tool but `sssd` itself have issue opening the `.ldb` file due to the missing module.

### Steps To Reproduce
1. Install a complicated AD setup
2. Run `sssctl domain-status`

### Expected behavior
No error message appears

### Notify maintainers

@bbigras

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.14.21, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by buckley310** [comment]
I currently have nixos 21.11 machines on Active Directory using sssd, and getent works as expected in my setup, although I do see the same issue with sssctl that you describe. I dont think the same issue applies to sssd that applies to sssctl, because the launch script for sssd sets the LDB_MODULES_PATH variable.

**Comment by buckley310** [comment]
Interestingly, I cannot get sssctl to recognize that I'm joined to the domain, even if I manually set `$LDB_MODULES_PATH`

**Comment by wucke13** [comment]
@buckley310 Can you elaborate on your setup? Does sssd provide both accounts and auth? What does your config look like, do you also use samba and/or krb5 and/or winbind?

**Comment by buckley310** [comment]
Do you have any samba fileservers, or are you just looking for machine authentication? Asking since I have found winbind to be easier to get running properly for fileserver machines, but I use SSSD for all other cases, as it's a little bit nicer.

**Comment by wucke13** [comment]
Foremost I'm interested in using ad accounts on a NixOS machine, that's why I turned towards sssd too.

**Comment by buckley310** [comment]
Finally getting around to putting this into a module.
https://github.com/buckley310/nixos-config/blob/b2c86c29198eee78c2465d37d3aeed85daead561/modules/ad-domain.nix
(I will probably update it ongoing, but linking to the exact commit for posterity)
It installs samba, but just for joining the domain. This module doesn't use winbind. After joining, samba is basically not used. I know there's a domain-join workflow other than this, (for instance realmd does not require samba), but this works and I haven't researched it much at this point.

Also suggested:
```
services.timesyncd.servers = [ "whatever" ];
users.mutableUsers = false;
security.sudo.extraRules = [{
    commands = [{ command = "ALL"; }];
    groups = [ "domain\\ admins" ];
}];
services.openssh.extraConfig = ''
    AllowGroups "domain admins"
'';
```
