### ISSUE TITLE
coconut.vim

### ISSUE THREAD

**Issue by drperceptron** [NixOS/nixpkgs#151515]
**Project description**
Vim syntax highlight and indent definition for Coconut

**Metadata**

* homepage URL: https://github.com/manicmaniac/coconut.vim
* source URL: https://github.com/manicmaniac/coconut.vim
* license: none
* platforms: vim

**Comment by drperceptron** [comment]
Does the absence of a license imply `pkgs.lib.licenses.publicDomain`?

**Comment by drperceptron** [comment]
Blocked by #153960

**Comment by teto** [comment]
there shouldn't be any blocking anymore
