### ISSUE TITLE
LXD cloud-init support is broken

### ISSUE THREAD

**Issue by kstenerud** [NixOS/nixpkgs#151507]
### Describe the bug
Cloud-init never completes when creating a container via LXD in NixOS. It seems to get stuck right at the beginning because no commands get executed.

### Steps To Reproduce
1. Enable lxd (virtualisation.lxd.enable = true) and add yourself to the lxd group
2. Run the following from a shell:

```
cat << EOF >config.yml
#cloud-config
runcmd:
  - touch /run/cloud-config-did-run
EOF

lxc launch ubuntu: x --config=user.user-data="$(cat config.yml)"
lxc exec x -- bash -c "cloud-init status --wait"
```

### Expected behavior
It launches a container, prints a few dots to the screen and exits, after which one can see a file `cloud-config-did-run` in `/run` inside the container (this is what happens if run on an Ubuntu host).

### Actual behavior
`cloud-init status --wait` never completes, even after 30 minutes. It just fills the entire screen with dots as it waits to complete, and the file never gets created in `/run`. In fact, no cloud-init directives get run at all (I'm just using `runcmd` as a quick example).

### Additional context
Comparing to Ubuntu's behaviour:

#### /var/log/cloud-init-output.log

Both start the same but on an Ubuntu host the container has the following at the end of the log whereas on a Nixos host it does not:

```
Cloud-init v. 21.4-0ubuntu1~20.04.1 running 'modules:config' at Tue, 21 Dec 2021 04:36:00 +0000. Up 16.37 seconds.
Cloud-init v. 21.4-0ubuntu1~20.04.1 running 'modules:final' at Tue, 21 Dec 2021 04:36:01 +0000. Up 17.41 seconds.
ci-info: no authorized SSH keys fingerprints found for user ubuntu.
Cloud-init v. 21.4-0ubuntu1~20.04.1 finished at Tue, 21 Dec 2021 04:36:01 +0000. Datasource DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net].  Up 17.64 seconds
```

#### /var/log/cloud-init.log

On a Nixos host the log file ends here (on an Ubuntu host there are another 200 or so lines afterwards):
```
2021-12-21 04:41:25,312 - main.py[DEBUG]: Ran 15 modules with 0 failures
2021-12-21 04:41:25,313 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmprkhv1111) - w: [644] 568 bytes/chars
2021-12-21 04:41:25,313 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2021-12-21 04:41:25,314 - util.py[DEBUG]: Read 20 bytes from /proc/uptime
2021-12-21 04:41:25,314 - util.py[DEBUG]: cloud-init mode 'init' took 1.577 seconds (1.58)
2021-12-21 04:41:25,314 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
```

### Notify maintainers
@Mic92

### Metadata

```console
[karl@nas:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.05 MiB download, 0.28 MiB unpacked):
  /nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev
copying path '/nix/store/wzach25vwapl3sa6f7gylqank3jhhsin-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mic92** [comment]
I never used lxd really for a long time. I just happened to upgrade it once.

**Comment by kstenerud** [comment]
Sorry, the instructions said to ping someone from git blame on the module. I picked you at random ;-)

**Comment by Mic92** [comment]
Let's try @fpletz @wucke13 @marsam

**Comment by holmanb** [comment]
> I never used lxd really for a long time. I just happened to upgrade it once, when testing stuff. It's also news to me that it supports cloud-init.

[here are the related docs](https://cloudinit.readthedocs.io/en/latest/topics/datasources/lxd.html) :)

Confirming that this should work. Can't comment on its status on Nix, but this is the output I would expect (as described by the original reporter):
```bash
arc/tmp cat << EOF >config.yml
#cloud-config
runcmd:
  - touch /run/cloud-config-did-run
EOF

lxc launch ubuntu: x --config=user.user-data="$(cat config.yml)"
lxc exec x -- bash -c "cloud-init status --wait"
Creating x
Starting x                                
..........................................
status: done
arc/tmp lxc exec x -- bash -c "ls /run/cloud-config-did-run"
/run/cloud-config-did-run
```

**Comment by adamcstephens** [comment]
I've never seen this problem, and have used cloud-init guests on occasion. Re-verified using the sample test in this issue

```
─❯ lxc launch ubuntu: bonk:x --config=user.user-data="$(cat config.yml)"
Creating x
                                            
The instance you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to an instance, use: lxc network attach

Starting x

─❯ lxc exec bonk:x stat /run/cloud-config-did-run
  File: /run/cloud-config-did-run
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 6eh/110d	Inode: 370         Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-04 16:39:24.971858943 +0000
Modify: 2023-09-04 16:39:24.971858943 +0000
Change: 2023-09-04 16:39:24.971858943 +0000
 Birth: 2023-09-04 16:39:24.971858943 +0000
```

Closing. Please re-open if you can reproduce on unstable.
