### ISSUE TITLE
Standardize "Mavenization" for all Gradle Builds

### ISSUE THREAD

**Issue by lorenzleutgeb** [NixOS/nixpkgs#151524]
When you search for ["mavenize" (6 hits)](https://github.com/NixOS/nixpkgs/search?q=mavenize) or ["mavenizes" (8 hits)](https://github.com/NixOS/nixpkgs/search?q=mavenizes) in Nixpkgs you'll find duplicated code.

It's usually something like

```
find $GRADLE_USER_HOME/caches/modules-2 -type f -regex '.*\.\(jar\|pom\)' \
  | perl -pe 's#(.*/([^/]+)/([^/]+)/([^/]+)/[0-9a-f]{30,40}/([^/\s]+))$# ($x = $2) =~ tr|\.|/|; "install -Dm444 $1 \$out/$x/$3/$4/$5" #e' \
  | sh
```

but there are some variations. "Mavenizing" a Gradle cache should be standardized accross Nixpkgs.

**Comment by lorenzleutgeb** [comment]
I have this implementation in Bash.

```bash
#! /usr/bin/env bash

IN=${1:-${GRADLE_USER_HOME:-~/.gradle}}
OUT=${2:-${out}}

for dep in $(find "$IN/caches/modules-2" -type f -regex '.*\.\(jar\|pom\)')
do
    IFS='/' read -r -a component <<< "$dep"
    echo "install -Dm444 $dep $OUT/${component[-5]//./\/}/${component[-4]}/${component[-3]}/${component[-1]}"
done
```

Now where in the tree do such things live?

**Comment by fgaz** [comment]
Still important

**Comment by liff** [comment]
> Now where in the tree do such things live?

How about putting it to a new `gradle` subdirectory to [`pkgs/build-support`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support) or using the existing  [`pkgs/build-support/java`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/java) directory?

**Comment by CutestNekoAqua** [comment]
Hi, I also don't like the perl script, but I see the sense in build speedup of using something different than just bash, 
here is a variation in awk I wrote: ```awk -F/ '{gsub(/[0-9a-f]{30,40}/, "", $0); gsub(/\./, "/", $1); printf "install -Dm444 %s $out/%s/%s/%s/%s\n", $0, $1, $2, $3, $NF}'```

Test it with 
```
$ echo "com.squareup.okio/okio/1.13.0/a9283170b7305c8d92d25aff02a6ab7e45d06cbe/okio-1.13.0.jar" | \
awk -F/ '{gsub(/[0-9a-f]{30,40}/, "", $0); gsub(/\./, "/", $1); printf "install -Dm444 %s $out/%s/%s/%s/%s\n", $0, $1, $2, $3, $NF}'

expected result: 
install -Dm444 com/squareup/okio okio 1.13.0  okio-1.13.0.jar $out/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar
```

**Comment by tomodachi94** [comment]
> "Mavenizing" a Gradle cache

What does this entail?

> When you search for ["mavenize" (6 hits)](https://github.com/NixOS/nixpkgs/search?q=mavenize) or ["mavenizes" (8 hits)](https://github.com/NixOS/nixpkgs/search?q=mavenizes) in Nixpkgs you'll find duplicated code.

I can no longer find any hits for these queries.

**Comment by FliegendeWurst** [comment]
> What does this entail?

See https://github.com/NixOS/nixpkgs/commit/5aa611e4d0c22a30f10790fbaa708471b63783fb for example. I think all uses of this horribly unreproducible pattern were replaced by mitmCache.

**Comment by tomodachi94** [comment]
Yes, that appears to be the case. Closing, please leave a comment or open a new issue if a specific Gradle package is packaged in a non-standard way.
