### ISSUE TITLE
nzbget can not load shared library libz.so.1

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#15169]
## Issue description
nzbget can not load shared library libz.so.1

### Steps to reproduce
Use unstable channel
```
nix-env -iA nixos.nzbget
nzbget
```
Output:
```
nzbget: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

## Technical details

* System: 16.09 Flounder
* Nix version: nix-env (Nix) 1.11.2

@pSub

**Comment by Sicaine** [comment]
Have you tried to add zlib twice? when you use ldd, you will see that there is zlib twice.

**Comment by groxxda** [comment]
Most certainly fixed upstream with https://github.com/nzbget/nzbget/issues/192 - but not included in current stable.. 17.0 is still testing :clap:
