### ISSUE TITLE
python-language-server-0.36.2 not supported for interpreter python3.9 on Nixos 21.11?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#151659]
add spyder and nixos-rebuild,
I got this error 
error: python-language-server-0.36.2 not supported for interpreter python3.9
(use '--show-trace' to show detailed location information)

**Comment by collares** [comment]
We should probably migrate `python-language-server` to the community fork (https://github.com/python-lsp/python-lsp-server), especially considering the current version is from Palantir.

**Comment by kira-bruneau** [comment]
I don't think the issue is specific to NixOS, it looks like the repo hasn't been updated in over a year. The community fork is available at `python-lsp-server`, maybe we should alias `python-language-server` to that now that Plantir's version is completely broken across on the latest version of Python?

**Comment by prehonor** [comment]
file shell.nix:
with import <nixpkgs> {};
with pkgs.python3Packages;

buildPythonPackage rec {
  name = "spyder_latest";
  src = /gh/prehonor/gitproject/spyder;
  nativeBuildInputs = [ pyqtwebengine.wrapQtAppsHook ];
  propagatedBuildInputs = [ intervaltree jedi pycodestyle psutil rope numpy scipy matplotlib pylint keyring
    numpydoc qtconsole qtawesome nbconvert mccabe pyopengl cloudpickle spyder-kernels
    pygments qtpy pyzmq chardet pyqtwebengine qdarkstyle watchdog
    atomicwrites pyxdg diff-match-patch three-merge pyls-black pyls-spyder
    flake8 textdistance ];
}

nix-shell shell.nix :
 I got python-language-server-0.36.2 not supported for interpreter python3.9,how to take python-lsp-server stead of python-language-server

**Comment by prehonor** [comment]
I add spyder by myself，if someone need use it ，he can visit the url https://github.com/prehonor/nixos/tree/master/nixpkgs-overlays/pkgs/development/python-modules/spyder
