### ISSUE TITLE
Pantheon greeter crashes since NixOS 21.11 upgrade

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#151609]
### Describe the bug
Since upgrading to NixOS 21.11, the pantheon greeter crashes on me most of the time. It takes multiple restart attempts for me to get a working graphical session. Due to some additional problems with my graphics cards setup I haven't been able to debug this until today. The relevant upstream issue seems to be https://github.com/elementary/greeter/issues/578, this is half "this is an issue I ran into, should we do something on our end?", half "here's a workaround until this is fixed upstream":

The issue is the Pantheon greeter crashing in a loop, eventually giving up & failing the whole graphical session. `/var/log/lightdm/seat0-greeter.log` has the following to say:
> ```
> (io.elementary.greeter:7389): Handy-WARNING **: 17:56:55.751: Failed to load icon: Fehler beim Öffnen der Datei »/home/bt1cn/.face«: Permission denied
> 
> ** (io.elementary.greeter:7389): CRITICAL **: 17:56:55.755: MainWindow.vala:358: prompt: `Password: ' (1)
> ```

Relevant part of my system config is [here](https://github.com/OPNA2608/nixos-config/blob/e46b379167080cf43527469e8d869714ee06f8b0/profiles/desktop.nix#L19-L28). (not pushed 21.11 changes yet but none of those options were touched)

Switching to the GTK greeter helped me reliably get into a graphical session again. Stopping `display-manager.service` and switching back and forth between the `gtk` and `pantheon` ones has confirmed this for me:

```nix
{
  services.xserver = {
    greeters.gtk.enable = lib.mkForce true;
    greeter = {
      package = lib.mkForce pkgs.lightdm_gtk_greeter.xgreeters;
      name = lib.mkForce "lightdm-gtk-greeter";
    };
  };
}
```

### Steps To Reproduce
1. Be on 21.11
2. `services.xserver.displayManager.lightdm.greeters.pantheon.enable = true`
3. Restart

### Expected behavior
A reliably working graphical session.

### Screenshots
A video of an attemped `display-manager.service` restart:

https://user-images.githubusercontent.com/23431373/146973618-b9f24ff1-4043-403b-a377-24a74abcaeeb.mp4

### Additional context
https://github.com/elementary/greeter/issues/578

### Notify maintainers
@NixOS/pantheon 

### Metadata
```console
bt1cn@NixTop:~
↪ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(bt1cn): `"unstable-22.05pre336298.bc5d68306b4"`
 - channels(root): `"nixos-21.11.334247.573095944e7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by bobby285271** [comment]
Hmmmm... I don't think there is something I can do except doing reverts to be honest... https://github.com/elementary/greeter/commit/6f18c79c780582e43039032f6926816efa82e206 is about accent color, so by any chance, have you tried Switchboard → About → Restore Default Settings → Restore Settings? Yeah I guess this cannot be reproduced on a fresh VM using nixos-rebuild build-vm [[1]](https://github.com/NixOS/nixpkgs/pull/150634#issue-1079273080) (maybe?) so I actually think of state first...

**Comment by davidak** [comment]
FYI: I have updated my system now to 21.11.334639.9ab7d12287c and can not reproduce the issue.

**Comment by bobby285271** [comment]
I find myself run into this issue after adding and testing a fix for #156456 (and I can always reproduce the issue on both VM and my physical machine as soon as I change the accent color and do a reboot), I think I will do a revert for now (and backport to 21.11) as the relavent part has been updated in the port to GTK 4 pull request.

**Comment by bobby285271** [comment]
The revert should hit both nixos-unstable and nixos-21.11 now.

**Comment by bobby285271** [comment]
We will see whether upstream accept https://github.com/elementary/greeter/issues/578#issuecomment-1030746697.
