### ISSUE TITLE
`/etc/resolv.conf` generation broken in systemd containers

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#15164]
`resolvconf` is generating an invalid `/etc/resolv.conf` file for systemd containers. It contains nameservers that do not exist.
### Workaround

Copy the host's `/etc/resolv.conf` into the container.
### Technical details
- Nixpkgs version: 8a1ccb5f7093702afd6ed135539222683bc4d09d (but also much earlier, including NixOS 16.03)

**Comment by Profpatsch** [comment]
triaged has this been fixeds

**Comment by domenkozar** [comment]
No:

```
# cat /etc/resolv.conf 
# Generated by resolvconf
search lan
nameserver 192.168.1.1
options edns0
options edns0
```

**Comment by ttuegel** [comment]
I'm closing this as I have lost track of what the problem actually was.
