### ISSUE TITLE
DisplayLink prevents suspend

### ISSUE THREAD

**Issue by akaihola** [NixOS/nixpkgs#151706]
### Describe the bug
My laptop doesn't enter the suspend state when there are no DisplayLink devices connected.

### Steps To Reproduce
1. Install the DisplayLink driver by following the instructions on the [Displaylink](https://nixos.wiki/wiki/Displaylink) wiki page.
2. Make sure the driver works correctly when the computer is connected to a DisplayLink device.
3. Detach the DisplayLink device.
4. Close the laptop lid or execute `systemctl suspend`.
5. Systems like networking and sound shut down, and the screen turns off.
6. The computer stays in running state. On Lenovo laptops, the power LED is constantly on which indicates that the laptop didn't enter a suspend state.
7. Open the lid (if applicable) and press any key.
8. Network and sound don't work.
9. Execute `systemctl --no-pager --after list-jobs` to observe that pre-suspend jobs are still running, waiting for the DisplayLink [`pre-sleep-start`](https://github.com/NixOS/nixpkgs/pull/18041/files#diff-f73fbdf2e5737e22aabf1b00007d22057941bf9a09aadd4442af7061c0a8436bR27-R36) to finish.

### Expected behavior
The computer should prepare for suspending for a while, then blank the screen, and eventually it should enter the sleep state. For example, on Lenovo laptops, a pulsating power LED indicates that the suspend state is active. After resuming from suspend, systems like sound and network should start again.

### Additional context
I suspect the culprit is this line added by `displaylink.nix` to [config.powerManagement.powerDownCommands](https://github.com/NixOS/nixpkgs/pull/18041/files#diff-f73fbdf2e5737e22aabf1b00007d22057941bf9a09aadd4442af7061c0a8436bR27-R36):
```bash
      #flush any bytes in pipe
      while read -n 1 -t 1 SUSPEND_RESULT < /tmp/PmMessagesPort_out; do : ; done;
```

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/gd7ihraqqpginv5cmhgk347nfn2iiqkj-bash-interactive-5.1-p8-dev
copying path '/nix/store/gd7ihraqqpginv5cmhgk347nfn2iiqkj-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.87, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334639.9ab7d12287c, musnix"`
 - channels(kaiant): `"home-manager-21.11, nixpkgs-unstable-22.05pre337603.47f45c8440e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by akaihola** [comment]
Annoyingly, I can't reproduce this now. I definitely did have this behavior a week ago, and I did see the `pre-sleep-start` script hanging by inspecting the system with a `sleep 10 ; <commands to poke around the system>` just before trying to suspend, and removing the DisplayLink driver did fix suspending.

**Comment by Artturin** [comment]
That line is taken from https://aur.archlinux.org/cgit/aur.git/tree/displaylink-sleep.sh?h=displaylink

**Comment by akaihola** [comment]
I found a [similar report](https://displaylink.org/forum/showthread.php?p=87137) on the DisplayLink forums, and it led me to believe my issue would be due to the same reason:

>No DL adpater is coonected to the system and I do sudo pm-hibernate. The hibernate command does not end, no hibernate occurs and Ubuntu is running.
>The pm-suspend.log shows as last line:
>
>    `Running hook /etc/pm/sleep.d/displaylink.sh hibernate hibernate:`
>
>My `displaylink.sh` looks:
>```bash
># ...
>#flush any bytes in pipe
>while read -n 1 -t 1 SUSPEND_RESULT < /usr/lib/displaylink/PmMessagesPort_out; do : ; done;
>
>#suspend DisplayLinkManager
>echo "S" > /usr/lib/displaylink/PmMessagesPort_in
>
>#wait until suspend of DisplayLinkManager finish
>read -n 1 -t 10 SUSPEND_RESULT < /usr/lib/displaylink/PmMessagesPort_out
># ...
>```
>It seems to me that the displaylink.sh is waiting for an DL driver status change, but DL driver is not aktiv because I has it not connected.
>I expect there is a missing check for DL driver active!!!!
