### ISSUE TITLE
truecrypt "invalid characters encountered"

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#15172]
## Issue description

Truecrypt fails to mount devices with the error message "invalid character encountered". The issue is [known](https://bugs.archlinux.org/task/47325) and a fix is [downgrading](https://wiki.archlinux.org/index.php/TrueCrypt).

From the latter link:

> Note: truecrypt 1:7.1a-3 and veracryptAUR 1.16-5 cannot mount volumes since the C++ ABI change on 2015-12-10, see FS#47325 and the forum thread. Downgrading to truecrypt 1:7.1a-2 works around the problem.

### Steps to reproduce

Try to mount an encrypted device with truecrypt from latest unstable.

## Technical details

* System: 16.09.git.9510670 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre82105.7465bcd"

**Comment by abbradar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/ec6b547b17d102c44f8817bae875418bd2797786
