### ISSUE TITLE
fpm package does not depend on rpm

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#15177]
I tried to use `fpm` as packaged in nixpkgs to build myself an RPM and it complained that it was missing the `rpmbuild` binary. For now I can add it to my environment, but I think a better way to handle this sort of thing is to patch the source so that it explicitly depends on the tools it needs, rather than looking for them at runtime in the `PATH`.

I tried to amend the `bundlerEnv` invocation to patch the sources, but `bundlerEnv` doesn't appear to support patching 😕 

cc @vcunat

**Comment by vcunat** [comment]
Well, yes, it uses various tools from `$PATH`, depending on what commands you run. I know it uses `rpm` and `zip`. Maybe there are more. I wasn't sure if I should force the dependencies (I considered wrapping), so I left it as it is. For example, those who only want to build other packages than RPM &ndash; they won't need `rpmbuild`...

**Comment by vcunat** [comment]
But certainly feel free to introduce the `rpm` dependency. `bundlerEnv` supports `postBuild` attribute.

**Comment by cstrahan** [comment]
Surprised I wasn't cc'd :). I'll assign to myself so I can double check `bundlerEnv` and either tackle this myself, or provide direction.

**Comment by Profpatsch** [comment]
triage: any updates?
