### ISSUE TITLE
wpa_supplicant not able to associate with home wifi using default authProtocols list

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#151729]
### Describe the bug

I have a network config like this at home:

```nix
  networking.wireless = {
    enable = true;
    interfaces = [ "wlp3s0" ];
    networks = {
      "mySSID" = { psk = "mypassword"; };
      ...
    };
  };
```

On latest nixos, my laptop (a Lenovo x250) is completely unable to associate with the network due to authentication faults.

By leaving out the `key_mgmt` out of the wpa_supplicant config like this, i get it to work:

```
diff --git a/nixos/modules/services/networking/wpa_supplicant.nix b/nixos/modules/services/networking/wpa_supplicant.nix
index 07dec8ea718..0684737aef6 100644
--- a/nixos/modules/services/networking/wpa_supplicant.nix
+++ b/nixos/modules/services/networking/wpa_supplicant.nix
@@ -44,10 +44,12 @@ let
 
     options = [
       "ssid=${quote ssid}"
-      (if pskString != null || opts.auth != null
-        then "key_mgmt=${concatStringsSep " " opts.authProtocols}"
-        else "key_mgmt=NONE")
-    ] ++ optional opts.hidden "scan_ssid=1"
+    ] ++ optional (opts.authProtocols != null) (
+          if pskString != null || opts.auth != null
+            then"key_mgmt=${concatStringsSep " " opts.authProtocols}"
+            else "key_mgmt=NONE"
+         )
+      ++ optional opts.hidden "scan_ssid=1"
       ++ optional (pskString != null) "psk=${pskString}"
       ++ optionals (opts.auth != null) (filter (x: x != "") (splitString "\n" opts.auth))
       ++ optional (opts.priority != null) "priority=${toString opts.priority}"
@@ -253,19 +255,14 @@ in {
             };
 
             authProtocols = mkOption {
-              default = [
-                # WPA2 and WPA3
-                "WPA-PSK" "WPA-EAP" "SAE"
-                # 802.11r variants of the above
-                "FT-PSK" "FT-EAP" "FT-SAE"
-              ];
+              default = null;
               # The list can be obtained by running this command
               # awk '
               #   /^# key_mgmt: /{ run=1 }
               #   /^#$/{ run=0 }
               #   /^# [A-Z0-9-]{2,}/{ if(run){printf("\"%s\"\n", $2)} }
               # ' /run/current-system/sw/share/doc/wpa_supplicant/wpa_supplicant.conf.example
-              type = types.listOf (types.enum [
+              type = types.nullOr (types.listOf (types.enum [
                 "WPA-PSK"
                 "WPA-EAP"
                 "IEEE8021X"
@@ -287,7 +284,7 @@ in {
                 "FT-FILS-SHA384"
                 "OWE"
                 "DPP"
-              ]);
+              ]));
               description = ''
                 The list of authentication protocols accepted by this network.
                 This corresponds to the <literal>key_mgmt</literal> option in wpa_supplicant.
```

### Notify maintainers

@rnhmjoj 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(tfc): `""`
 - channels(root): `"nixos-21.11.334639.9ab7d12287c, home-manager-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

**Comment by rnhmjoj** [comment]
There's no need change the module for this: you can get the previous behavior with
```
  authProtocols = [ "WPA-PSK" "WPA-EAP" ];
```

About the authentication failure, can you tell me which protocols are advertised by your network?
Enable `userControlled.enable`, if not already, and run `wpa_cli scan_results | awk -F'[][]' '/mySSID/{print $2}'`.
If I had to guess, the network card doesn't support some feature (like 802.11w), but wpa_supplicant is not falling back to WPA-PSK.

**Comment by tfc** [comment]
Hi,

i get the following output:

```
WPA2-PSK+SAE-CCMP
WPA2-PSK-CCMP
WPA2-PSK-CCMP
WPA2-PSK+SAE-CCMP
WPA2-PSK+SAE-CCMP
WPA2-PSK-CCMP
WPA2-PSK+SAE-CCMP
WPA2-PSK-CCMP
WPA2-PSK+SAE-CCMP
WPA2-PSK-CCMP
WPA2-PSK+SAE-CCMP
WPA2-PSK-CCMP
```

From a user experience perspective i'd prefer to not have to know about all this and only set the authProtocols to something if i really *need* to tinker around if wpa_supplicant's default settings don't work... what do you think?

**Comment by rnhmjoj** [comment]
> From a user experience perspective i'd prefer to not have to know about all this and only set the authProtocols to something if i really need to tinker around if wpa_supplicant's default settings don't work... what do you think?

I agree. I didn't anticipate just changing the allowed protocols would have this sort of effects: it seems WPA3 support is still too rough to be enabled by default. I'll do some testing and possibly restrict them to something more conservative.

**Comment by tfc** [comment]
Awesome, let me know when you have something to test

**Comment by rnhmjoj** [comment]
I made some extensive tests and I'm pretty sure I found the problem. There are actually two issues:

1. I didn't enable 802.11w support. This is required by WPA3 but it's disabled by default in wpa_supplicant and it's not turned on even when you specify `SAE` (aka WPA3).
2. If a network has mixed WPA2/WPA3 (@tfc case) and WPA3 fails, wpa_supplicant doesn't fall back to other protocols.

Optionally enabling 802.11w (with `pmf=1`) would fix issue 1, but authentication would still fail if the hardware lacks support.
So, for now I have to remove `SAE`, but I'll report this issue to wpa_supplicant.

**Comment by rnhmjoj** [comment]
@tfc It would great if you could help with testing https://github.com/NixOS/nixpkgs/pull/154130 out.

**Comment by tfc** [comment]
@rnhmjoj awesome, i will report back as soon as i got to it.

**Comment by tfc** [comment]
@rnhmjoj i just checked out #154130 on my Lenovo x250 and can confirm that it **fixes** the problem.

**Comment by rnhmjoj** [comment]
Thank you!

**Comment by dasJ** [comment]
So can we close this?

**Comment by rnhmjoj** [comment]
Yes, this has has been fixed for a while.
