### ISSUE TITLE
Dropbox has no icon in KDE 5 since multiple-outputs merge

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#15171]
The command
```
$(nix-build -A dropbox)/bin/dropbox
```
should start the Dropbox daemon, but nothing happens. It works in NixOS 16.03, but it stopped working after multiple-outputs.

**Comment by groxxda** [comment]
I cannot reproduce the bug, dropbox works for me. Have you tried moving ~/.dropbox out of the way to make sure it's no local problem?

**Comment by ttuegel** [comment]
You're quite right; it's only the *icon* that is gone since the staging merge. If I reboot into a NixOS 16.03 generation, the icon returns. :confused:

**Comment by groxxda** [comment]
For me the icon shows up. Did you check for the icons in the output (`$out/opt/dropbox/images/hicolor/16x16/status/*.png`)?
From a quick strace:
dropbox finds the icon:
```
stat("/nix/store/a2pkzwn74ny21bqpfi5hb9br2ylnkfnw-qtbase-5.5.1/lib/qt5/plugins/iconengines/.", 0x7ffcfa29f760) = -1 ENOENT (No such file or directory)
stat("/nix/store/zlj3d5k7wkqrl6vdpl5jmz4siaw7q1sp-dropbox-3.18.1/opt/dropbox/iconengines/.", 0x7ffcfa29f760) = -1 ENOENT (No such file or directory)
stat("/run/current-system/sw/lib/qt5/plugins/iconengines/.", 0x7ffcfa29f760) = -1 ENOENT (No such file or directory)
stat("/nix/var/nix/profiles/default/lib/qt5/plugins/iconengines/.", 0x7ffcfa29f760) = -1 ENOENT (No such file or directory)
stat("/home/groxxda/.nix-profile/lib/qt5/plugins/iconengines/.", 0x7ffcfa29f760) = -1 ENOENT (No such file or directory)
open("/nix/store/zlj3d5k7wkqrl6vdpl5jmz4siaw7q1sp-dropbox-3.18.1/opt/dropbox/images/hicolor/16x16/status/dropboxstatus-logo.png", O_RDONLY|O_CLOEXEC) = 17
fcntl(17, F_SETFD, FD_CLOEXEC)          = 0
fstat(17, {st_mode=S_IFREG|0444, st_size=1778, ...}) = 0
stat("/nix/store/a2pkzwn74ny21bqpfi5hb9br2ylnkfnw-qtbase-5.5.1/lib/qt5/plugins/imageformats/.", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
open("/nix/store/a2pkzwn74ny21bqpfi5hb9br2ylnkfnw-qtbase-5.5.1/lib/qt5/plugins/imageformats", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 18
fstat(18, {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
brk(0x2da4000)                          = 0x2da4000
statfs("/nix/store/a2pkzwn74ny21bqpfi5hb9br2ylnkfnw-qtbase-5.5.1/lib/qt5/plugins/imageformats/", {f_type="EXT2_SUPER_MAGIC", f_bsize=4096, f_blocks=15448575, f_bfree=7321307, f_bavail=6635693, f_files=3932160, f_ffree=3060517, f_fsid={-2107249344, -1946593456}, f_namelen=255, f_frsize=4096, f_flags=4129}) = 0
getdents(18, /* 5 entries */, 32768)    = 144
getdents(18, /* 0 entries */, 32768)    = 0
close(18)                               = 0
```

and also libpng:
`open("/nix/store/jfxwvfpzykyyy72czdjwq34k1nhikj05-libpng-apng-1.6.20/lib/libpng16.so.16", O_RDONLY|O_CLOEXEC) = 7`

**Comment by ttuegel** [comment]
Yes, it finds both the icon and libpng.

**Comment by groxxda** [comment]
Just for the record: I'm using i3bar, not sure if it makes a difference

**Comment by abbradar** [comment]
FWIW I also have the icon showing up.

**Comment by ttuegel** [comment]
@abbradar What desktop are you using?

**Comment by abbradar** [comment]
XFCE, but with taffybar as a panel.

**Comment by abbradar** [comment]
_Maybe_ using `makeQtWrapper` would fix something? I'm completely making a guess here, though.

**Comment by ttuegel** [comment]
> Maybe using makeQtWrapper would fix something? I'm completely making a guess here, though.

That's a good idea, but it doesn't seem to help. Still, I updated the dropbox expression in master because it *should* be using `makeQtWrapper`.

Now I'm wondering if the problem is actually with KDE 5's system tray.

**Comment by peterhoeg** [comment]
@ttuegel is ```xembedsniproxy``` running?

**Comment by ttuegel** [comment]
Yes, `xembedsniproxy` is running, and I can't find any error messages from it in `~/.xsession-errors`.

**Comment by ttuegel** [comment]
This is now fixed in staging by some unrelated changes I made. At least, I thought they were unrelated. I guess not! :smiley:

**Comment by ttuegel** [comment]
Actually, the Dropbox icon appears only intermittently :frowning:

**Comment by ttuegel** [comment]
And, it's back now. For good? It survived at least one reboot; who knows.
