### ISSUE TITLE
citrix_workspace: "The option "-icaroot" is invalid"

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#151885]
### Describe the bug
When I launch a remote desktop session via Citrix Workspae I get the error messages:

* "The option "-icaroot" is invalid"
* "The option "/nix/store/...." is invalid

The error messages does not prevent the application from opening. So I'm unsure about the impact.

### Steps To Reproduce

1. Launch Citrix Workspace
2. Add a workspace
3. Launch Remote Desktop

### Expected behavior
No error message.

### Notify maintainers
@pmenke-de 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 ✘ asbachb@nixos-t14s  /tmp/tmp.99bn5797hG  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(asbachb): `"nixos-21.11pre304061.dd14e5d78e9, nixos-20.09-20.09.4393.068984c00e0"`
 - channels(root): `"nixos-22.05pre339888.81cef6b70fb, nixos-hardware, nixos-unstable-22.05pre336298.bc5d68306b4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
* citrix_workspace
module:
```

**Comment by asbachb** [comment]
reference: https://discussions.citrix.com/topic/402218-linux-workspace-app-icaroot-option-invalid/

**Comment by pmenke-de** [comment]
Hi @asbachb,

thanks for reporting. I've also encountered this behavior as of a couple versions ago (see here https://github.com/NixOS/nixpkgs/pull/127254#issuecomment-864886527).
Back then i proposed to remove the `-icaroot` option from the invocation, as it worked for me perfectly fine without it.

I somewhat lost the means and thus motivation to further investigate this issue though, as i no longer use / need / have-access-to citrix-workspace stuff.

Could you test the patch from my comment if it a) still works, and b) fixes the issue for you?

Thank you and kind Regards, Philipp

**Comment by asbachb** [comment]
Ah I see. @pmenke-de thanks for your fast response. A pity to hear that you aren't use citrix anymore.

I can have a look at your patch. But I think I'll try to update citrix workspace first to the most recent release.

Maybe that error message occurs only when you set ICAROOT env variable and pass it via parameters.
