### ISSUE TITLE
`vifm` help page is broken

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#151841]
### Describe the bug

Typing `:help` in `vifm` (with `vim` or `neovim` installed) leads to the following error in `vim`:

```
Error detected while processing command line:                                                                                           
E149: Sorry, no help for vifm-app.txt                                                                                                   
```

### Steps To Reproduce
1. Add `vifm` or `vifm-full` to your system packages
2. Add `vim` or `neovim` to your system packages
3. Open `vifm`
4. Type `:help`

### Expected behavior

I would expect the documentation to be readable.

### Notify maintainers
@7c6f434c 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11pre293089.1c2986bbb80"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by 7c6f434c** [comment]
Any idea which kind of the root cause this is? Is the problem that the file is installed but Vim only uses its own installation path?

**Comment by ambroisie** [comment]
Indeed, looks like this is now working.
