### ISSUE TITLE
A number of texlive-new packages have hash mismatches

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#15183]
## Issue description
A number of texlive-new packages have hash mismatches. Looks like packages hosted at http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2015/tlnet-final/archive/ can just change underneath us and as the packages are not versioned, hence the mismatch.

Any other ideas how to solve this short of downloading the whole archive and scripting a recall of the packages?

### Steps to reproduce
1. Add ```texlive.combined.scheme-full``` to ```environment.systemPackages```
2. Watch several packages fail with hash mismatch:
```output path ‘/nix/store/ayq32cfk92kiysywxnb35xfhsm4j3wbq-2up.tar.xz’ has md5 hash ‘7bb1a159a6e50d7cb807c58f471e360e’ when ‘6160fbc7ab71be778081500b908d2648’ was expected```

## Technical details

* NixOS: 16.09.git.52dd6dd (Flounder)
* Nix: nix-env (Nix) 1.11.2
* nixpkgs: "16.09pre79453.32b7b00"

cc @vcunat

**Comment by joachifm** [comment]
Possibly this again https://github.com/NixOS/nixpkgs/issues/10026

**Comment by peterhoeg** [comment]
Thanks @joachifm, it definitely looks like the same thing. Closing as duplicate.
