### ISSUE TITLE
Installed fonts are not visible to xfontsel

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#15189]
## Issue description

Installed fonts like deja-vu mono, fira, etc. are missing from xfontsel and xlsfonts

### Steps to reproduce

- install some fonts (I tried with dejavu_fonts, inconsolata, liberation_ttf, ubuntu_font_family, and some others)
- run xfontsel
- None of the installed fonts are present

I'm not sure if it changes anything, but I enabled `enableFontDir`, rebooted the machine and ran `fc-cache --really-force --verbose`

## Technical details

* System: 16.09.git.fc6eb14 (Flounder)
* Nix version: nix-env (Nix) 1.11.2

**Comment by edolstra** [comment]
AFAIK, `xfontsel` and `xlsfonts` don't show client side fonts. These commands (like all X11 server-side font support) are obsolete and probably shouldn't be used.

**Comment by NicolasPetton** [comment]
@edolstra I'm using stumpwm, which apparently needs server-side fonts.

**Comment by 7c6f434c** [comment]
>@edolstra I'm using stumpwm, which apparently needs server-side fonts.

You can install truetype support contrib module, though.

You would need an override like that:
```
 stumpwm = pkgs.lib.overrideDerivation pkgs.stumpwm (x: {
   nativeBuildInputs = x.nativeBuildInputs ++ [
     pkgs.stumpwm.lispPackages.clx-truetype
     pkgs.stumpwm.lispPackages.clx-xkeyboard
   ];
   installPhase = (x.installPhase or "") + ''
     echo "$nativeBuildInputs" > "$out/nix-support/build-inputs"
   '';
 });
```

and load the `ttf-fonts` module.

**Comment by NicolasPetton** [comment]
Thanks for the explanations, this is not a bug then, I'm closing the issue.
However, `clx-truetype` fails to find the fonts, and I cannot add a path to `*font-dirs*`, because of https://github.com/NixOS/nixpkgs/issues/15194.
