### ISSUE TITLE
google-clasp: expose nodejs version to allow overriding? 

### ISSUE THREAD

**Issue by JohannesRudolph** [NixOS/nixpkgs#151868]
I want to install `google-clasp` which is built from an npm package. However, it defaults to `nodejs-10_x` but I want to use a newer version of node for it. This is the package experssion, which does not seem to set/expose the nodejs argument

https://github.com/NixOS/nixpkgs/blob/9ab7d12287ced0e1b4c03b61c781901f178d9d77/pkgs/development/misc/google-clasp/default.nix#L3-L8

And here's the defaulting to `nodejs-10_x`

https://github.com/NixOS/nixpkgs/blob/9ab7d12287ced0e1b4c03b61c781901f178d9d77/pkgs/development/misc/google-clasp/google-clasp.nix#L5

This means I cannot do 

```nix
pkgs.mkShell {
  buildInputs = [
    pkgs.nodejs-16_x
    (pkgs.google-clasp.override { nodejs = pkgs.nodejs-16_x; })
  ]
}
```

Or is there another way to achieve this override?

Other packages, e.g. `yarn` expose nodejs, which allows easy overriding
https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/development/tools/yarn/default.nix#L1

I was thinking of just threading through a nodejs arg from default.nix to google-clasp.nix. Can maybe one of the maintainers (e.g. @mweinelt) comment on if a PR like that would be welcome?

**Comment by mweinelt** [comment]
Not sure if overriding that from the outside would work. This uses node2nix to generate a FOD and other files which are somewhat version-specific. 

it would also be prudent to move clasp off of nodejs 10 in nixpkgs by editing ´./generate.sh` and then trying to build clasp, to see if it still works. Also the clasp version is outdated and the package seems unmaintained, so if you want to pick that up, that'd be great.

I myself am not a nodejs package set maintainer fwiw.

**Comment by JohannesRudolph** [comment]
I'm closing this issue as I think https://github.com/NixOS/nixpkgs/pull/157930 has solved this or at least changed the context enough to make this issue obsolete.
