### ISSUE TITLE
CMake docs not installed

### ISSUE THREAD

**Issue by Phlogistique** [NixOS/nixpkgs#15184]
## Issue description

The help for CMake is not installed.

### Steps to reproduce

Any of these commands:
```
nix-shell --pure -p cmake --run "cmake --help-command-list"
nix-shell --pure -p cmake --run "cmake --help-policy-list" 
nix-shell --pure -p cmake --run "cmake --help-manual-list"
nix-shell --pure -p cmake --run "cmake --help-module-list"
nix-shell --pure -p cmake --run "cmake --help-property-list"
nix-shell --pure -p cmake --run "cmake --help-variable-list"
```

Expected: CMake prints a list of documented items
Observed: CMake prints nothing

## Technical details

* System: Debian GNU/Linux 8.4 (jessie)
* Nix version: nix-env (Nix) 1.10
* Nixpkgs version: 16.09pre82477.0d5ff13

**Comment by rardiol** [comment]
Seems like multiple-outputs trouble: 

```
$ nix-shell --pure -p cmake.all strace --run "strace -f cmake --help-variable-list
open("/nix/store/0fpn055wzzjksikp7msys9qh9ggdf48q-cmake-3.4.3/share/cmake-3.4/Help/variable/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

```
Should be /nix/store/6q5q5bjvsw2zzm67g9qh4nsf1m11vrj6-cmake-3.4.3-doc/ instead

**Comment by rardiol** [comment]
It seems cmake has a single CMAKE_ROOT (or GetCMakeRoot) inside of which it expects to find the folders Modules and Help, but those are separated by multiple outputs. Hardcoding the documentation part to use $doc seems to work:
`    substituteInPlace ./Source/cmDocumentation.cxx --replace "cmSystemTools::GetCMakeRoot()" "std::string(\"$doc/share/cmake-${majorVersion}\")"`
Someone who knows c++ could please tell if this is correct and not a memory leak or something?
