### ISSUE TITLE
allowUnfree must be set in BOTH config.nix and configuration.nix when adding pinned unfree systemPackages

### ISSUE THREAD

**Issue by illegalprime** [NixOS/nixpkgs#151860]
## Issue description

So was helping a friend with an install and they wanted to use [Insync](https://github.com/NixOS/nixpkgs/blob/b49473e6679c733f917254b786bfac42339875eb/pkgs/applications/networking/insync/v3.nix), but because it was broken (#139728) we decided to use a version from a known-working pinned nixpkgs, like so:

```nix
{
    nixpkgs.config.allowUnfree = true;
    environment.systemPackages = with pkgs; let
      insync_pin = import (builtins.fetchGit {
        name = "nixpkgs-insync";
        url = "https://github.com/nixos/nixpkgs/";
        ref = "refs/heads/nixos-unstable";
        rev = "b49473e6679c733f917254b786bfac42339875eb";
      }) {};
    in [
      insync_pin.insync-v3
    ];
}
```

I was able to get `sudo nixos-rebuild build` to work, but my friend's did not. Weird. Specifically the error they had was:

```
building Nix...
building the system configuration...
error: Package ‘insync-3.2.4.40856’ in /nix/store/kdiw9cgrfkp9v68is6ids6shmq1g3j5c-nixpkgs-insync/pkgs/applications/networking/insync/v3.nix:73 has an unfree license (‘unfree’), refusing to evaluate.

a) To temporarily allow unfree packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNFREE=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.
```

Finally after much checking I noticed that I had `{ allowUnfree = true; }` in my `~/.config/nixpkgs/config.nix`.

**Removing that option in config.nix caused the system-wide configuration.nix to fail to build.**

I feel like this because the pinned packages are built on the user's nix build environment and not the systems?

Not sure, but definitely seems like a bug if you need a configuration in a user's home directory to allow a system-wide config to be valid.

### Steps to reproduce

1. Add a closed-source package to `environment.systemPackages` that comes from a pinned nixpkgs.
2. Set `nixpkgs.config.allowUnfree = true;` in the nixos system configuration.
3. Unset any `allowUnfree` in `~/.config/nixpkgs/config.nix` and `~root/.config/nixpkgs/config.nix`.
4. Run `nixos-rebuild build`, the build should fail with a licensing error.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(michael): `""`
 - channels(root): `"nixos-21.11.334534.2627c4b7951, nixos-unstable-22.05pre338911.03ec468b140"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
You're Importing nixpkgs and not inheriting the main nixpkgs config so allowUnfree isn't passed to it

**Comment by illegalprime** [comment]
@Artturin that isn't the issue, inheriting the config doesn't affect it. I'm saying it depends on a config existing in `~/.config/nixpkgs/config.nix`
