### ISSUE TITLE
User dbus service symlinked to nonexistent file

### ISSUE THREAD

**Issue by harrisonthorne** [NixOS/nixpkgs#151974]
### Describe the bug

`pipewire` and `dunst` have suddenly stopped working on my sway setup. I've determined that my user `dbus.service` has gone missing, and the missing service seems to have disrupted `pipewire.socket` from triggering and `dunst.service` from starting. 

### Steps To Reproduce

Steps to reproduce the behavior: Honestly, I don't know, but I am using `nixos-unstable` with flakes. See my system configuration(s) below. 

### Expected behavior

User's `dbus.service` should be present, working, and should make services depending on it run. 

### Additional context

Logs over at nix-community/home-manager#2584

[My system config](https://codeberg.org/harrisonthorne/nixos-config)

[My home-manager config](https://codeberg.org/harrisonthorne/dotfiles)

### Notify maintainers

@rycee @domenkozar 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211126_55275fc`
 - channels(root): `"nixos-21.11pre304061.dd14e5d78e9"`
 - channels(harrison): `"home-manager, nixos-21.11pre332033.715f6341195, nixpkgs-21.11pre332093.7fad01d9d5a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by harrisonthorne** [comment]
Just found out that `~/.config/systemd/user/dbus.service` is a dangling symlink on my laptop:

```console
~ 
❯ ll ~/.config/systemd/user/
lrwxrwxrwx  86 harrison 15 Jul 00:33 dbus.service -> /nix/store/kwc8h9pbspkbm18xdd87042n20k4qiv6-dbus-1.12.20/etc/systemd/user/dbus.service
drwxr-xr-x   - harrison 24 Dec 10:33 default.target.wants
lrwxrwxrwx  97 harrison 24 Dec 10:33 dunst.service -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/dunst.service
lrwxrwxrwx 101 harrison 24 Dec 10:33 gammastep.service -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/gammastep.service
drwxr-xr-x   - harrison 24 Dec 10:33 graphical-session.target.wants
lrwxrwxrwx 101 harrison 24 Dec 10:33 hydroxide.service -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/hydroxide.service
lrwxrwxrwx 110 harrison 24 Dec 10:33 muse-status-daemon.service -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/muse-status-daemon.service
lrwxrwxrwx 100 harrison 24 Dec 10:33 spotifyd.service -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/spotifyd.service
lrwxrwxrwx 103 harrison 24 Dec 10:33 sway-session.target -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/sway-session.target
lrwxrwxrwx 101 harrison 24 Dec 10:33 syncthing.service -> /nix/store/6qh5va54js9clviqfy9vbgm6h6kms6i0-home-manager-files/.config/systemd/user/syncthing.service

~ 
❯ stat /nix/store/kwc8h9pbspkbm18xdd87042n20k4qiv6-dbus-1.12.20/etc/systemd/user/dbus.service
stat: cannot statx '/nix/store/kwc8h9pbspkbm18xdd87042n20k4qiv6-dbus-1.12.20/etc/systemd/user/dbus.service': No such file or directory
```

**Comment by berbiche** [comment]
@harrisonthorne if you remove the dbus service in `~/.config/systemd/user` and rerun the NixOS/HM activation script, is the file still created?

**Comment by rycee** [comment]
I'm not sure where the `~/.config/systemd/user/dbus.service` comes from, most likely it is not Home Manager since HM never has managed the user dbus service, that's done on the system level. You can also tell it's not from HM since it's not pointing into a `home-manager-files` directory.

It should be safe to delete this link and rely on `/etc/systemd/user/dbus.service`/`/etc/systemd/user/dbus.socket` (which I hope you have).

**Comment by harrisonthorne** [comment]
@berbiche 

Neither `sudo nixos-rebuild switch` nor `home-manager switch --flake /home/harrison/.config/nixpkgs#harrison` replaced ~/.config/systemd/user/dbus.service

I'm gonna try restarting my system now though and see if it works after deleting it 🤔

**Comment by harrisonthorne** [comment]
I'm guessing this was an error on my part because even after rollbacks, the issue persisted. Something like `systemctl --user enable dbus.service`probably caused the issue. I'll close this guessing it's not a bug with nixpkgs :)
