### ISSUE TITLE
`fonts.enableFontDir` doesn't produce a fonts directory

### ISSUE THREAD

**Issue by Twey** [NixOS/nixpkgs#15194]
## Issue description
The documentation for `config.fonts.enableFontDir` states that setting the option to `true` should cause a directory of fonts to be generated.  However, this option is set on my system, but the system does not have a fonts directory:

    [twey@othala:~]$ nixos-option fonts.enableFontDir
    Value:
    true
    
    Default:
    false
    
    Description:
    
    Whether to create a directory with links to all fonts in
    <filename>/run/current-system/sw/share/X11-fonts</filename>.
    
    Declared by:
      "/nix/store/yyswmfq27dmh2w9y92s01zzd34r67nsg-nixos-16.09pre82105.7465bcd/nixos/nixpkgs/nixos/modules/config/fonts/fontdir.nix"
    
    Defined by:
      "/etc/nixos/fonts.nix"

    [twey@othala:~]$ ls /run/current-system/sw/share/X11-fonts
    ls: cannot access '/run/current-system/sw/share/X11-fonts': No such file or directory

### Steps to reproduce
- Enable `fonts.enableFontDir` in `config.nix`.
- Rebuild system.
- Observe lack of directory.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
    [twey@othala:~]$ nixos-version
    16.09pre82105.7465bcd (Flounder)

* Nix version: (run `nix-env --version`)
    [twey@othala:~]$ nix-env --version
    nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
    [twey@othala:~]$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
    "16.09pre82105.7465bcd"

**Comment by NicolasPetton** [comment]
I can reproduce the issue

**Comment by michalrus** [comment]
:+1:, same here, for a loooong time now (sorry for not reporting earlier).

**Comment by vcunat** [comment]
BTW, what's this option good for?

**Comment by Twey** [comment]
It gives a place to point applications that want to know about fonts (e.g. LuaTeX).
On 7 May 2016 11:20, Vladimír Čunát <notifications@github.com> wrote:BTW, what's this option good for?

**Comment by vcunat** [comment]
I assumed everything uses fontconfig nowadays, but there may be some exceptions...

**Comment by DamienCassou** [comment]
Could you please write this in `configuration.nix` (and not in `config.nix` as you said in the issue description)?

```nix
{
  fonts = {
    enableFontDir = true;
    enableGhostscriptFonts = true;
    fonts = with pkgs; [
      cantarell_fonts
    ];
  };
}
```

Do you have the directory now?

**Comment by NicolasPetton** [comment]
I have this in configuration.nix:

```nix
{
  fonts = {
    enableFontDir = true;
    enableFontConfig = true;
    enableGhostscriptFonts = true;
    fonts = with pkgs; [
      fira
      fira-code
      fira-mono
      cantarell_fonts
      corefonts # Microsoft free fonts
      dejavu_fonts
      gentium
      inconsolata
      noto-fonts
      opensans-ttf
      freefont_ttf
      liberation_ttf
      xorg.fontmiscmisc
      ubuntu_font_family
      dejavu_fonts
    ];
  };
}
```

and no directory.

**Comment by joachifm** [comment]
I believe this is fixed by https://github.com/joachifm/nixpkgs/commit/b24e58a82ba3323ca0aa4db80a80e7725c7ff21d. I don't use nor really care about this feature, though, so I have no idea whether linking `X11-fonts` into `current-system/sw/share` really does anything useful ...
