### ISSUE TITLE
`bazel_4` incorrect arch set for aarch64-darwin

### ISSUE THREAD

**Issue by jacobfoard** [NixOS/nixpkgs#151908]
### Describe the bug
When using a `.bazelversion` file with the current `bazel_4`, you get a message like: 
```
bazel build //...
ERROR: The project you're trying to build requires Bazel 4.2.1 (specified in /local/project/path/.bazelversion), but it wasn't found in /nix/store/lh5cn9cmqvj6iry3i4k02vi5vyvcy58w-bazel-4.2.2/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /nix/store/lh5cn9cmqvj6iry3i4k02vi5vyvcy58w-bazel-4.2.2/bin/bazel-4.2.1-darwin-arm64
```

a quick `ls` in that store path shows that the bin is suffixed with `aarch64` instead of `arm64`

```
 /bin/ls -l /nix/store/lh5cn9cmqvj6iry3i4k02vi5vyvcy58w-bazel-4.2.2/bin/
total 62776
-r-xr-xr-x  1 root  nixbld      8734 Dec 31  1969 bazel
-r-xr-xr-x  1 root  nixbld  32123374 Dec 31  1969 bazel-4.2.2-darwin-aarch64
-r-xr-xr-x  1 root  nixbld       240 Dec 31  1969 bazel-execlog
```

### Steps To Reproduce
1. Add a `.bazelversion` file to an existing bazel project
2. Attempt to use `bazel_4` 

### Expected behavior
Build should work and continue forward without error

### Additional context
Once I remove the `.bazelversion` file, it works fine. 

### Notify maintainers

 @NixOS/bazel

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `/nix/store/2l43ycb2hl1pv05bifdvjf352x0g6sg8-lgfhg4n6445yizgf0xjirb4bc4j86fr9-source`
```

**Comment by rbraley** [comment]
This appears to still be an issue. Symlinking sudo ln -s bazel-4.2.2-darwin-aarch64 bazel-4.2.2-darwin-arm64 in the /nix/store/1mr7dcx24li4fa9a5dhnylz8bcf2p0i9-bazel-4.2.2/bin directory makes it work. But how should this be fixed in future?

**Comment by jacobfoard** [comment]
I believe if [this line](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/build-managers/bazel/bazel_4/default.nix#L138) was changed from `stdenv.hostPlatform.parsed.cpu.name` to `stdenv.hostPlatform.darwinArch` that would fix it. 

I don't have a super deep understanding of nix, but it looks like that would work regardless of the actual host system based on [these attributes](https://github.com/NixOS/nixpkgs/blob/master/lib/systems/default.nix#L128).

**Comment by jacobfoard** [comment]
This is also an issue with `bazel_5` since it uses the same logic for determining the arch name https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/build-managers/bazel/bazel_5/default.nix#L129

**Comment by divanorama** [comment]
should probably be resolved by https://github.com/NixOS/nixpkgs/pull/180251
