### ISSUE TITLE
Unable to perform a docker login on an AWS ECR repository

### ISSUE THREAD

**Issue by blackheaven** [NixOS/nixpkgs#151920]
### Describe the bug
When I try to login in an AWS ECR repository, it fails.

### Steps To Reproduce

1. Create `~/.docker/config.json` with `{"credsStore": "ecr-login"}`
2. Load your AWS's account credentials in your environment variable
3. Run the login command

Here's the result:

```
$ aws ecr get-login-password --region <<region>> | docker login --username AWS --password-stdin <<account-id>>.dkr.ecr.<<region>>.amazonaws.com
Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`
```

### Expected behavior
login should works

### Additional context
It works with my ArchLinux.

### Notify maintainers
@kalbasit 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre338578.a2e281f5770"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by blackheaven** [comment]
We're not supposed to use it anymore

**Comment by joee** [comment]
To be explicit: Removing `{"credsStore": "ecr-login"}` from ~/.docker/config.json solved the problem for me.
