### ISSUE TITLE
Rust no longer builds from snapshots

### ISSUE THREAD

**Issue by jgillich** [NixOS/nixpkgs#15199]
Details: https://github.com/rust-lang/rust/commit/02538d463a350f5c3658f7aabefca16eb599d31c

Do we want to build beta and master from rustc in nixpkgs now?

cc @abbradar @wizeman

**Comment by abbradar** [comment]
I envision something like this:

1. Use [binary stable release](https://www.rust-lang.org/downloads.html) to bootstrap our stable version.
2. Use stable version to build beta and master.

I don't have much time now to look at it now, but I suppose it won't be very hard -- rename "snapshot" to "bootstrap" or something like this for clarity, change URL and the first point is done. The second point is the actual improvement (less usage of binary blobs) and may require a bit more work (but I think should be simple, too).

**Comment by jgillich** [comment]
Yea, that's what I meant. The only downside is that a from-source build of rustcMaster would take forever, but that shouldn't really matter to anyone.

**Comment by abbradar** [comment]
Hm, don't we already build it from source? From code it looks like it but I don't remember well.

**Comment by jgillich** [comment]
We do, but currently if you want master, you build master. With this change, you'd have to build stable -> beta -> master. But at least on Linux and OSX, you'd get them from the cache anyway.

**Comment by dvc94ch** [comment]
So if we build our own rustcBeta will we get a different BOOTSTRAP_KEY? Do we have to remember CFG_FILENAME_EXTRA and patch stage0.txt?

**Comment by jgillich** [comment]
#15875
