### ISSUE TITLE
Multi architecture ISO

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#15206]
## Issue description

I'm just leaving this here as a reminder for me. Basically, Arch Linux is able to publish ISOs that run on both 64 and 32 bit modes. It should be possible with NixOS using Syslinux's ifcpu64.c32. Getting it to work with EFI should be fairly straightforward as well using the EFI standard directory structure.

It will probably increase ISO sizes by as much as double but it be able to remain under 1GB for nixos-minimal. In addition, we won't have to serve two architectures.

**Comment by edolstra** [comment]
But how is doubling the size of the ISO an improvement for the average user?

**Comment by matthewbauer** [comment]
Perhaps it's not.

The main benefit is that the user doesn't have to know if they need 32 or 64. Although it seems more and more safe to just assume 64bit.

**Comment by AndersonTorres** [comment]
2016-05-04 6:12 GMT-03:00 Eelco Dolstra <notifications@github.com>:

> But how is doubling the size of the ISO an improvement for the average
> user?
>
> ​He will not need to think "Ah, I downloaded the wrong version!"
And, in the remote possibility he doesn't know if the machine is 32-bit or
a 64-bit one, he can test with a single ISO burned in a single DVD.

Also, a not so averaged user can install in two distinct machines with only
one ISO file/DVD medium.​

**Comment by copumpkin** [comment]
What's the average age of a machine that can only run 32-bit code these days? It doesn't seem very valuable to me to invest effort in supporting a "dying" platform, and furthermore to impose a cost on all users to support that platform.

**Comment by wkennington** [comment]
If you exclude via chips which are not common at all, there was an atom
from 2009 (N280) that was 32bit only. Otherwise you have to go back to pre
core2 / amd64 era which began in 2006. This stuff should be mostly gone at
this point.

**Comment by matthewbauer** [comment]
Okay I can close this for now. But, I might end up making a pull request for having multiple systems on 1 ISO. Just remind when the first AMD128 processor comes out.

**Comment by vcunat** [comment]
:-) I personally see very little motivation to allow 128-bit address space in foreseeable future. Actually, most usermode apps would still do well with 32-bit address space, as discussed around *x32 ABI* for example.

**Comment by volth** [comment]
> What's the average age of a machine that can only run 32-bit code these days?

Few minutes or hours. 32-bit code suits well small clouds and containers.
