### ISSUE TITLE
Flutter doesn't work after 2.8.0 update

### ISSUE THREAD

**Issue by flexagoon** [NixOS/nixpkgs#152071]
### Describe the bug
Running `flutter run` fails with the following error:
```
Target debug_android_application failed: FileSystemException: Cannot copy file to
'/home/flexagoon/Documents/Code/flutter/fdc_meals_app/build/app/intermediates/flutter/debug/flutter_assets/fonts/MaterialIcons-Regular.otf', path =
'/home/flexagoon/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf' (OS Error: No such file or directory, errno = 2)
```
The issue is here: https://github.com/NixOS/nixpkgs/blob/f6da7b400708640ae1dae471b872f81164fe4e07/pkgs/development/compilers/flutter/patches/move-cache.patch#L23

Before the 2.8.0 update, this line used to say
https://github.com/NixOS/nixpkgs/blob/d05d2113bbd392c4b904f5942e0028bfd2276679/pkgs/development/compilers/flutter/patches/move-cache.patch#L26

So, flutter copied the cache to `~/.cache/flutter`, which was fine. Now, however, it tries to copy the cache to `~/bin/cache`, which doesn't exist, so flutter throws an error.

### Steps To Reproduce
1. Go do any flutter project
2. Run `flutter run

### Expected behavior
Flutter builds the app and runs it on the device

### Notify maintainers
@ericdallo @babariviere 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

I cannot run it because I use flakes, so it just says `file 'nixpkgs' was not found in the Nix search path`.

**Comment by ericdallo** [comment]
My bad, it should be fixed by https://github.com/NixOS/nixpkgs/pull/152094

**Comment by flexagoon** [comment]
Thanks!

**Comment by flexagoon** [comment]
@ericdallo thanks!
