### ISSUE TITLE
`jemalloc` build fails on aarch64-darwin

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#152056]
### Describe the bug
`python3Packages.tensorflow` does not build aarch64-darwin as of eac07edbd20ed4908b98790ba299250b5527ecdf.

### Steps To Reproduce
1. Check out eac07edbd20ed4908b98790ba299250b5527ecdf.
2. `nix-build -A python3Packages.tensorflow` on aarch64-darwin

### Expected behavior
The build to succeed or the package to be marked as broken.

### Screenshots
n/a

### Additional context
Full build log: https://gist.github.com/samuela/42e5da41bb7a2e32842bd3de3777fced

### Notify maintainers

@jyp @abbradar @ndl @veprbl @danieldk @timokau 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(samuelainsworth): `"darwin, home-manager, nixpkgs-21.11pre330734.5cb226a06c4"`
 - channels(root): `"nixpkgs-21.11pre330734.5cb226a06c4"`
 - nixpkgs: `/Users/samuelainsworth/.nix-defexpr/channels/nixpkgs`
```

**Comment by veprbl** [comment]
Can you try with 6bda212f691a94f5b16385a432e86b9e0c98cbf5?

**Comment by samuela** [comment]
Ah didn't realize this was a jemalloc failure at first. Sure, here's the result on https://github.com/NixOS/nixpkgs/commit/6bda212f691a94f5b16385a432e86b9e0c98cbf5:
```
❯ nix-build -A jemalloc
error: Package ‘compiler-rt-libc-10.0.1’ in /Users/samuelainsworth/dev/nixpkgs/pkgs/development/compilers/llvm/10/compiler-rt/default.nix:95 is marked as broken, refusing to evaluate.
```
Overriding with `NIXPKGS_ALLOW_BROKEN=1` gives me a more substantial failure:
```
...
[ 87%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_arm64_osx.dir/clear_cache.c.o
[ 87%] Linking C static library libclang_rt.builtins_arm64_osx.a
[ 87%] Built target clang_rt.builtins_arm64_osx
make: *** [Makefile:136: all] Error 2
error: builder for '/nix/store/7fxzrv6n5fglzh4wjvcg7xqd7zd43rf1-compiler-rt-libc-10.0.1.drv' failed with exit code 2;
```
Full build log: https://gist.github.com/samuela/6679addeea17f965c00b6bce9392ad7c

**Comment by prusnak** [comment]
LLVM 10.x is not compatible with aarch64-darwin and we can't use LLVM 11.x or later because of this upstream bug: https://github.com/jemalloc/jemalloc/issues/2091

So this issue is blocked until the upstream fixes this.

**Comment by prusnak** [comment]
ISTM there is another issue present as aarch64-darwin as well, wrong detection of `lg-vaddr` - see https://github.com/jemalloc/jemalloc/issues/1997 - adding `"--with-lg-vaddr=48"` to `configureFlags` seems to help to build jemalloc with newer LLVM, but I am still getting test failures on aarch64-darwin.
