### ISSUE TITLE
jellyfin: NVENC transcoding does not work

### ISSUE THREAD

**Issue by Kranzes** [NixOS/nixpkgs#152008]
### Describe the bug
When enabling transcoding via NVENC I get the error below (see screenshots)

I looked further into the transcoding logs and found that ffmpeg is erroring with this message:
 `[AVHWDeviceContext @ 0xa52500] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`.
 
I remember NVENC transcoding in the past.

### Steps To Reproduce
1. Enable jellyfin
2. Enable NVENC playback transcoding
3. Play a video which requires transcoding

### Expected behavior
Playback working with transcoding happening on the GPU instead of the CPU.

### Screenshots
![image](https://user-images.githubusercontent.com/56614642/147357430-f2ac8925-7431-4082-a881-d211d2e82686.png)

![image](https://user-images.githubusercontent.com/56614642/147357703-6f21239e-cd75-4bce-95f5-1f807b48452e.png)
### Additional context
I have an Nvidia GTX 950.
`nvidia-smi` output: (see screenshots:

### Notify maintainers
@minijackson @purcell @jojosch @nyanloutre 

### Metadata

```console
[kranzes@pongo ~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `""`
 - channels(kranzes): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs
```

**Comment by D4Delta** [comment]
I have the same issue, I tried to run the exact same command that jellyfin uses, using `sudo -u jellyfin /nix/store/ffmpeg...`, but it works fine, so I don't know what's causing this

**Comment by Kranzes** [comment]
See my comment here: https://github.com/NixOS/nixpkgs/pull/144082#issuecomment-1013568030
It is something with the systemd hardening we apply in nixpkgs for that module.

**Comment by D4Delta** [comment]
> See my comment here: [#144082 (comment)](https://github.com/NixOS/nixpkgs/pull/144082#issuecomment-1013568030) It is something with the systemd hardening we apply in nixpkgs for that module.

Thanks, I'll disable it on my system to make it work

**Comment by D4Delta** [comment]
Okay, for everyone waiting for this to be fixed upstream, add this in your `configuration.nix` to fix NVDEC and NVENC:

```
systemd.services."jellyfin".serviceConfig = {
  DeviceAllow = pkgs.lib.mkForce [ "char-drm rw" "char-nvidia-frontend rw" "char-nvidia-uvm rw" ];
  PrivateDevices = pkgs.lib.mkForce false;
  RestrictAddressFamilies = pkgs.lib.mkForce [ "AF_UNIX" "AF_NETLINK" "AF_INET" "AF_INET6" ];
};
```

**Comment by winterqt** [comment]
> for everyone waiting for this to be fixed upstream

Is this an upstream issue, though? It seems like only our hardening is at fault. (In case this sounds rude: I couldn't find a better way to word this, and my apologies.)

**Comment by peperunas** [comment]
@Kranzes, @D4Delta, can you please try the PR and confirm it solves the issue please?
