### ISSUE TITLE
haskellPackages.stack seems to have incorrect runtime dependencies

### ISSUE THREAD

**Issue by rrnewton** [NixOS/nixpkgs#15216]
## Issue description

`stack` should be a standalone executable with minimal dependencies.  And yet when I create a closure for it it's >1GB.

### Steps to reproduce

```bash
$ nix-env -f '<nixpkgs>' -iA haskellPackages.stack
...
$ nix-store -qR ~/.nix-profile/bin/stack | wc -l
158
$ nix-store --export $(nix-store -qR ~/.nix-profile/bin/stack) > /tmp/stack.closure
$ du -sch /tmp/stack.closure
1.7G    /tmp/stack.closure
```

I think the only things it should truly need to depend on are the linked dynamic libs:

```bash
$ ldd /nix/store/kff433s61k9808vwb9m0yl8pmipirvxs-stack-1.0.4.3/bin/stack
        linux-vdso.so.1 =>  (0x00007ffd06d9a000)
        libz.so.1 => /nix/store/ph89iai8wmwg232gwxl75sakb8f33wmx-zlib-1.2.8/lib/libz.so.1 (0x00007fa59d219000)
        libpthread.so.0 => /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libpthread.so.0 (0x00007fa59cffc000)
        libyaml-0.so.2 => /nix/store/vdjn5kp5kgh1fvb3h3jg6zw09ppg38bf-libyaml-0.1.6/lib/libyaml-0.so.2 (0x00007fa59cdde000)
        librt.so.1 => /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/librt.so.1 (0x00007fa59cbd6000)
        libutil.so.1 => /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libutil.so.1 (0x00007fa59c9d3000)
        libdl.so.2 => /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libdl.so.2 (0x00007fa59c7cf000)
        libgmp.so.10 => /nix/store/b7i1r1vfygnjig3xx42v4snrim1mzy7i-gmp-6.1.0/lib/libgmp.so.10 (0x00007fa59c53f000)
        libm.so.6 => /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libm.so.6 (0x00007fa59c23a000)
        libc.so.6 => /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/libc.so.6 (0x00007fa59be98000)
        /nix/store/phffgv3pwihmpdyk8xsz3wv8ydysch8w-glibc-2.23/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007fa59d432000)
```

I don't know enough about how runtime dependence checking is done.  How is it picking up these extra dependencies?

## Technical details

* System: (Ubuntu 14.04.4 LTS)
* Nix version: 1.11.2
* Nixpkgs version: "16.09pre82421.d27848a"

**Comment by rrnewton** [comment]
I came across this when exploring Stack/nix integration problems: https://github.com/commercialhaskell/stack/issues/2089

**Comment by rrnewton** [comment]
A related (newbie) question is how to ADD additional runtime dependencies manually.  It should probably include `git` and `pkg-config` as runtime dependencies, because `stack` will try to shell out to these.

Everything else stack does, it manages itself.  (I.e. downloading and installing Haskell packages, not via Nix.)

**Comment by peti** [comment]
Stack is not just an executable -- it's also a library and that library is what is pulling in 1GB worth of dependencies. Just run

    tree $(nix-build --no-out-link "<nixpkgs>" -A haskellPackages.stack)

and you'll see that the store patch for stack contains lots and lots of other stuff in addition to the executable itself.

**Comment by copumpkin** [comment]
@rrnewton the usual approach I use is to patch the source to point at the full store path of the tools in question. Something like

```nix
{
  patchPhase = ''
     substituteInPlace path/to/relevant/source.hs \
       --replace 'findInSearchPath "git"' '"${pkgs.git}/bin/git"'
  '';
}
```

**Comment by peti** [comment]
d74d8161bf452fd8c3eee259aed832998d6be841 creates a top-level attribute "stack" that contains only the executable -- not the library. That gives a closure size of ~17 MB. I'll merge that patch to `master` shortly.

**Comment by rrnewton** [comment]
@peti Thanks, that's perfect!

@copumpkin: That seems like a good trick.  

It looks like the first step will be to send a PR to Stack to refactor it so that it has a single place in a single file where it stores the `"git"` string.  Right now, it unfortunately references "git" in a bunch of places (also `"git-update"`).

```
[ ~/stack/src/Stack] 
$ git ls-files "*.hs" | xargs grep \"git\"
Config.hs:            RPTGit commit -> cloneAndExtract "git" ["--recursive"] ["reset", "--hard"] commit
New.hs:            catch (callProcess $ Cmd (Just dir) "git" menv ["init"])
PackageIndex.hs:                   (readInNull suDir "git" menv cloneArgs Nothing)
PackageIndex.hs:                    (Cmd (Just acfDir) "git" menv ["fetch","--tags","--depth=1"])
PackageIndex.hs:                readInNull suDir "git" menv cloneArgs Nothing
PackageIndex.hs:                (readInNull acfDir "git" menv ["tag","-v","current-hackage"]
PackageIndex.hs:         tryProcessStdout (Just dir) menv "git" ["rev-parse","current-hackage^{}"]
PackageIndex.hs:             "git" menv ["archive","--format=tar","-o",tarFileTmp,"current-hackage"]
PackageIndex.hs:isGitInstalled = flip doesExecutableExist "git"
Setup.hs:    -- runCmd (Cmd (Just destDir) "pacman" menv ["-Sy", "--noconfirm", "git"]) Nothing
Types/Config.hs:        mgit <- o ..:? "git"
Types/Config.hs:    toJSON (PLRemote x (RPTGit y)) = toJSON $ T.unwords ["git", x, y]
Types/Config.hs:            <$> o ..: "git"
Types/Config.hs:            "git" -> return Git
Types/Config.hs:    toJSON Git = toJSON ("git" :: Text)
Upgrade.hs:        remote <- liftIO $ readProcess "git" ["ls-remote", repo, "master"] []
Upgrade.hs:                runCmd (Cmd (Just tmp) "git" menv args) Nothing
```

**Comment by copumpkin** [comment]
Ouch, yes, they should keep their external command resolution stuff in a single place 😞 

An alternative approach that could also work is for you to wrap the stack executable (this is more painful for a library) with a wrapper script that sets the `PATH` variable to whatever we consider suitable. We have some automation around `makeWrapper` today that facilitates things like that, but my first inclination would be to patch it.
