### ISSUE TITLE
`tor-browser-bundle-bin`: error: hash mismatch in Russia

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#152281]
### Describe the bug

I live in Russia and we have blocked https://torproject.org/
So, when I connect to it, my internet provider replaces certificate to self-signed one and redirects to another site
However, according to console output, nix keeps trying to download from `https://dist.torproject.org/` instead of fully accessible second mirror from package https://github.com/NixOS/nixpkgs/blob/cb372c3b8880e504b06946e8fb2ca9777c685505/pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix#L95-L101

``` console
trying https://dist.torproject.org/torbrowser/11.0.3/tor-browser-linux64-11.0.3_en-US.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170  100   170    0     0   2465      0 --:--:-- --:--:-- --:--:--  2500
100  6571  100  6571    0     0  75228      0 --:--:-- --:--:-- --:--:-- 75228
error: hash mismatch in fixed-output derivation '/nix/store/85n1fj7ikpi7hmra79ccqmyg2aapn03j-tor-browser-linux64-11.0.3_en-US.tar.xz.drv':
         specified: sha256-ZdyTB9qfPhvGW6pZiP6OZPOVnuhY9r7ARfOFJ2vvVqg=
            got:    sha256-5K1w6i+bM/22aJ/sqaN1rxO91S56I0Uvf4EfUbZH/Pg=
error: 1 dependencies of derivation '/nix/store/xv9a1zmz36av7khlg65mwqzksr14abn0-tor-browser-bundle-bin-11.0.3.drv' failed to build
```

### Steps To Reproduce
1. Move to Russia(?) or launch VPN to Russia or create some DNS rule(?)
2. Try to install `tor-browser-bundle-bin`

### Expected behavior
Package successfully downloaded from second mirror

### Additional context

<details>
<summary>Firefox certificate data</summary>

``` url
about:certificate?cert=MIICLzCCAZgCCQD%2FIKpzd285qTANBgkqhkiG9w0BAQsFADBcMQswCQYDVQQGEwJSVTEPMA0GA1UECAwGTW9zY293MQ8wDQYDVQQHDAZNb3Njb3cxDTALBgNVBAoMBE1HVFMxDTALBgNVBAsMBE1HVFMxDTALBgNVBAMMBE1HVFMwHhcNMjAwNTA4MDgwNTU2WhcNMzAwNTA2MDgwNTU2WjBcMQswCQYDVQQGEwJSVTEPMA0GA1UECAwGTW9zY293MQ8wDQYDVQQHDAZNb3Njb3cxDTALBgNVBAoMBE1HVFMxDTALBgNVBAsMBE1HVFMxDTALBgNVBAMMBE1HVFMwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBANUC7TY6QI8%2FXjlG6UgqdYSPKLQN%2B7j2OSnztQTjZ75SxNDYlqLAIx6PBcF0EAdGAc0ERaeJXqnEoEyJbqHlWXPBpy%2FTMn%2FC3BPBBhebHot01oe9sNNV%2FWtQmOtdSgGoQd6KDBf1LhZTWgvzInOpXO3YjFwApL1rSaGnPnq27k8FAgMBAAEwDQYJKoZIhvcNAQELBQADgYEAB2LqJ%2FQsjHtR4oMV3fT9L9m3PiZncAw%2BH9nRt0B74Eipo5c88lRoQ9lG3yF11ZKmLBKqD%2FAh8VSJZtCpwSEq6bTJLYlAgGEYuSBtPIR8FCS7LT5GR4YkU4yMbmtP8sfnT9S9ISd7wkFiX1DvyOFvfNxRZ1FdwelM2XM1Uas6TaM%3D
```

</details>

### Notify maintainers
@offline @matejc @thoughtpolice @joachifm @hax404 @KarlJoad

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.3-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.334797.6979c0e49bb, nixos-unstable-22.05pre340469.cb372c3b888"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by joachifm** [comment]
My understanding is that the mirrors are tried only in case the *download* fails.  What you're seeing is what I'd expect if a listed mirror is serving bogus data (for whatever reason).

As a workaround I'd manually add the source from the alternate location to my store.

Perhaps the EFF mirror could be made the primary, if it's less likely to be tampered with (and is reliable).

**Comment by dotlambda** [comment]
> As a workaround I'd manually add the source from the alternate location to my store.

```sh
nix-prefetch-url "https://tor.eff.org/dist/torbrowser/11.0.3/tor-browser-linux64-11.0.3_en-US.tar.xz"
```

**Comment by psydvl** [comment]
Thank you for workaround, but I still think it's a bug when nix keep downloading file without checking certificate or following self-signed one

**Comment by joachifm** [comment]
For visibility and traction I suggest opening a new issue to address malicious redirects in `fetchurl`.

Note, however, that it's fairly common to rely on the hashes for security [^1], so it's possible that this will result in a wontfix. (I'm not arguing either way, just saying).

[^1]: The cURL based fetcher should check the cert *if* a ca bundle is available, but otherwise will happily ignore cert failures, whereas I believe the builtin `fetchurl` unconditionally ignores TLS checks.

**Comment by psydvl** [comment]
Since this is not `nixpkgs`, but `nix` issue, move to https://github.com/NixOS/nix/issues/5837
