### ISSUE TITLE
Emacs: request to add withXinput2 argument. (--with-xinput2)

### ISSUE THREAD

**Issue by FLAMEMASTER1** [NixOS/nixpkgs#152216]
[See News](https://github.com/emacs-mirror/emacs/blob/97133fb3d0ae59e391a94c6189719318cb44a232/etc/NEWS#L59)

**Comment by FLAMEMASTER1** [comment]
@adisbladis

**Comment by adisbladis** [comment]
How about you create a PR?

**Comment by FLAMEMASTER1** [comment]
> How about you create a PR?

OK, I will try.

**Comment by adisbladis** [comment]
You could use https://github.com/NixOS/nixpkgs/pull/152033 for inspiration.

**Comment by FLAMEMASTER1** [comment]
> You could use #152033 for inspiration.

I test work, please review, thank you.
https://github.com/NixOS/nixpkgs/pull/152328

**Comment by adisbladis** [comment]
Merged and backported to 21.11!

**Comment by FLAMEMASTER1** [comment]
> Merged and backported to 21.11!

Thank you!
