### ISSUE TITLE
Difference between plasma-integration, kwayland-integration and plasma-browser integration?

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixpkgs#152293]
## Issue description

When searching on https://search.nixos.org for "plasma integration" there are 2 different packages : `plasma-integration` and `plasma-browser-integration`. Looking further [in the repo](https://github.com/NixOS/nixpkgs/tree/master/pkgs/desktops/plasma-5) to try and find a distinction, there's additionally a [`kwayland-integration`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5/kwayland-integration.nix). To make matters even more confusing [`plasma-integration/default.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/plasma-5/plasma-integration/default.nix) requires `kwayland`

What are all these packages? Are they related? Aliases? Copies?

@ttuegel @bkchr would probably know more.

I don't know if `mkDerivation` allows adding a description, but that or a comment in the `.nix` files would be greatly appreciated.

**Comment by Zahrun** [comment]
Even if I have plasma-browser-integration in my configuration.nix, it seems that librewolf is not able to connect to the host
![image](https://user-images.githubusercontent.com/10415894/215277586-47826742-edf2-45f4-96f8-f4ee844ae597.png)

**Comment by huantianad** [comment]
Old issue, but these all have congruent kde packages:
https://github.com/KDE/plasma-browser-integration
https://github.com/KDE/plasma-integration
https://github.com/KDE/kwayland-integration

The naming in Nixpkgs is simply mirroring the KDE naming convention.

**Comment by LoveIsGrief** [comment]
It would be great if they had descriptions. Maybe I'll find some time to add it unless somebody beats me to the punch :)
