### ISSUE TITLE
Problem with RDRAND on AMD Ryzen

### ISSUE THREAD

**Issue by lagunoff** [NixOS/nixpkgs#152270]
### Describe the bug
When I try to upgrade the system from nixos-20.09 it won't start with following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device: rdrand failed
```
Same thing if I try to install something from unstable (`https://nixos.org/channels/nixos-unstable`) . 
```console
$ nix-channel --list
nixos https://nixos.org/channels/nixos-20.09
unstable https://nixos.org/channels/nixos-unstable
$ nix-env -iA unstable.tdesktop
$ telegram-desktop
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device: rdrand failed
[1]    28708 abort (core dumped)  telegram-desktop
```
Currently running `nixos-20.09` on `AMD Ryzen 9 5950X` it seems nixos-20.09 is the last release that can work with Ryzen processors 

### Steps To Reproduce
1. Running  nixos-20.09 on AMD Ryzen try to upgrade it to  nixos-21.11
2. It won't upgrade showing this error message:
```console
building Nix...
building the system configuration...
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device: rdrand fail
```

**Comment by LunNova** [comment]
rdrand shipped broken on some AMD processors, is your firmware up to date?

Might also be able to fix with `hardware.cpu.amd.updateMicrocode = true;`in your config on the old version before upgrading.

There may also be a more recent issue and I'm not sure if it's patched: Looking at https://github.com/systemd/systemd/issues/18184#issuecomment-758155962

**Comment by lagunoff** [comment]
@LunNova I tried to set the property you posted, run `nixos-rebuild` using old `nixos-20.09` channel, then reboot and tried to upgrade to `nixos-21.11` and still had same error 
```sudo nixos-rebuild boot
building Nix...
building the system configuration...
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device: rdrand failed
```
actually I did a mistake in original report — the problem occurs when I try to install new system, not when I start it. I suppose the firmware comes with new kernel, I never had to installed it previously, I don't know how to check and how to update the firmware. Thanks for help @LunNova do you have any more ideas what I should try?

**Comment by lagunoff** [comment]
I was finally able to resolve the issue, updating BIOS version for my motherboard helped, apparently newer nixpkgs use some unsupported by the old BIOS features. All I had to do is to go official asrock website https://www.asrock.com/mb/AMD/X570%20Pro4/#BIOS download the new BIOS and install via flash drive, they have instructions how to do that.
