### ISSUE TITLE
fetchFromGithub packages should imply github url in metadata

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#15227]
i just stumbled upon a few packages lacking the url in the metadata, - fetch-from-github could provide something to automate taking that over as a nice default

**Comment by joachifm** [comment]
I'm unaware of a mechanism that would allow `fetchFromGitHub` to affect the `meta` attribute directly. I think that would need to be handled in an outer layer, say, in a `buildFromGitHub` type of function (which would fill in a missing `meta.homepage` with `src.url`).

**Comment by peti** [comment]
`fetchFromGitHub` *does* provide those values. Just see the definition:

~~~~
  fetchFromGitHub = { owner, repo, rev, sha256, name ? "${repo}-${rev}-src" }: fetchzip {
    inherit name sha256;
    url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz";
    meta.homepage = "https://github.com/${owner}/${repo}/";
  } // { inherit rev; };
~~~~

It's up to the build expression, however, to inherit those values in the `meta` section if appropriate.

**Comment by RonnyPfannschmidt** [comment]
perhaps instead there is need for a linter then? at least i'd think that manually fixing the definitions is error prone and easy to forget

**Comment by peti** [comment]
We have `nixpkgs-lint`. I'm not sure how good it is, but it probably does catch a few issues that currently exist in the Nixpkgs tree. Generally speaking, if you notice that a package has bogus or missing meta information, the best way forward is to open a PR that fixes the issue.

**Comment by domenkozar** [comment]
Maybe `mkDerivation` could use `src.meta.homepage` if `meta.homepage` is missing?

**Comment by RonnyPfannschmidt** [comment]
would it make sense in general to merge `src.meta` and `meta` ?

**Comment by vcunat** [comment]
I don't know what "merging them" might mean.

The `mkDerivation` change seems easy. Perhaps we should do it, although there's a question of how much auto-magic we want in there &ndash; it reminds me of "output guessing"...

**Comment by vcunat** [comment]
And `nixpkgs-lint` does little else than warn about missing `meta` stuff.

**Comment by RonnyPfannschmidt** [comment]
i mean merge as in pull missing values if they are available,

i think its a reasonable magic to auto-fill derivation metadata from the source if its availiable

**Comment by edolstra** [comment]
IMHO `fetchFromGithub` shouldn't have a `meta` attribute since it's not a package.

**Comment by RonnyPfannschmidt** [comment]
@edolstra i think that "smart sources" (like a github repo or a pypi package) carry a good amount of structured metadata that would be nice to tap into instead of duplicating and hand-tracking

**Comment by vcunat** [comment]
> `fetchFromGithub` shouldn't have a meta attribute since it's not a package.

Technically, we could use e.g. `passthru.homepage` or some other location. `src.meta` is  already referenced on a few dozen places in nixpkgs, but that should be easy to mass-replace.

**Comment by peti** [comment]
Why not replace `fromFromGitHub` with something along the lines of `mkDerivationFromGitHub`? That function could define appropriate `src` and `meta` attributes directly without adding strange and unused intermediate values to the `src` attribute set.

**Comment by vcunat** [comment]
If we leave both functions, then possibly (as fetching is useful also on other places than `src` directly), but still the original suggestion feels better to me, as any other fetcher could define it as well without changing other code, e.g. `fetchurl` when passed `mirror://sourceforge`. We "export" many attributes *just in case*, e.g. almost everything passed to `mkDerivation`; it doesn't seem too bad.

**Comment by FRidh** [comment]
What metadata do your refer to @RonnyPfannschmidt ? In case of GitHub you can use the url as homepage, but aside from that you won't have any other metadata. The same with PyPI. Meta data that is available can be retrieved via an API, but that's not the job of fetchurl and if we would go as far as using fetchurl or derivates for this, that opens the question of what should be hashed then, a file consisting of the source + meta data from API? 

With many repositories we can use the API to extract metadata, urls and hashes, but these would have to be stored somewhere, either in Nixpkgs or retrieved from another repository. When we have that we can make special functions that take into account all this metadata (like `mkDerivationFromGitHub` or `buildPyPIPackage` in #15007) .

**Comment by RonnyPfannschmidt** [comment]
for something like github url its easier than for metadata that has to be indirectly pulled

maybe a convention could help, where a script would extract a number of versions from a repositroy and attach their metadata

as for kinds of repositories, there is pypi, rpm repos, debian repos

it might be helpful to get some basic tooling to interact with the blobs that are around

(btw, i also see a need to track exported apis/abis/rpm/debian names somewhere)
perhaps we should start over in a new issue about metadata automation

(for example it would be really easy to automate building derivations for vendor shipped deb/rpms's if there was a mapping of debian/redhat/fedora package names to nixpkgs and a script that would take debian/rpm metadata and output a nix expression that  obtains the dependencies from pkgs and puts them in as build/runtime inputs)

**Comment by RonnyPfannschmidt** [comment]
closing, next time i have an idea like this i#ll provide a proposal with a pr and/or discuss on nix-dev fist instead
