### ISSUE TITLE
Package request: itch

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#152256]
**Project description**
The best way to play itch.io games.

**Metadata**

* homepage URL: https://itch.io
* source URL:https://github.com/itchio/itch
* license: mit
* platforms: unix, windows

**Comment by davidak** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/90233. Please check for existing issues before opening a new one.

**Comment by pasqui23** [comment]
The linked issue is closed.
