### ISSUE TITLE
Have a version of `toYAML` that outputs pretty YAML.

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#152262]
`generators.toYAML` currently just outputs JSON:
https://github.com/NixOS/nixpkgs/blob/59b2ed7599c77be71f1d5a1bd05258c35aa28e89/lib/generators.nix#L198

While this is technically valid, it makes for some very hard to read config files.
To fix this, I've been copy-pasting this little package around:

`to-yaml-file.nix`
```
{ stdenv, writeText, haskellPackages }:
name:
config:
stdenv.mkDerivation {
  name = name;
  buildInputs = [ haskellPackages.json2yaml ];
  src = "${writeText "${name}.yaml" (builtins.toJSON config)}";
  buildCommand = ''
    json2yaml $src > $out
  '';
}
```

Is there any interest to upstream this?

**Comment by rvl** [comment]
It looks like this was addressed in PR #133807.
