### ISSUE TITLE
Postgis doesn't build

### ISSUE THREAD

**Issue by paraseba** [NixOS/nixpkgs#15236]
## Issue description
Using master, postgis fails to build because it can't find postgresql makefiles via pgxs

### Steps to reproduce
```bash
$ nix-build  . -A postgis
....
   checking for pg_config... /nix/store/q6y6cav5map2m1z2lqh0s29bf29j5gn8-postgresql-9.5.1/bin/pg_config
configure: error: the PGXS Makefile /nix/store/czdlgjgmy6iw1sy0r5kzxjw8xxi7cn9h-postgresql-9.5.1-lib/lib/pgxs/src/makefiles/pgxs.mk cannot be found. Please install the PostgreSQL server development packages and re-run configure.
builder for ‘/nix/store/34qa65505j29bgm5qacy4774dld3zxb9-postgis-2.2.1.drv’ failed with exit code 1
error: build of ‘/nix/store/34qa65505j29bgm5qacy4774dld3zxb9-postgis-2.2.1.drv’ failed
```
## Technical details
For some reason, with the last version postgresql pg_config reports extension as being in the `lib` output, but the nix expression is moving the makefiles to `out`. This would be easy to fix, just buy moving makefiles to `lib` instead, but the problem is the makefiles maintain a reference to the `out` path, so we would end up with circular dependencies.

A fix, I believe, but I don't fully understand this, would be finding a way to make pg_config from postgresql package, report pgxs in `out` instead of `lib`, as it was the case with the previous version of the package.

If somebody can point me in the right direction, I can provide a patch. 
 

* Nixpkgs version: "16.09pre82105.7465bcd"

**Comment by thall** [comment]
@paraseba do you have an temporary fix to share? I depend on it

**Comment by paraseba** [comment]
@thall unfortunately I don't have a fix. The key is finding a way to make compilation move the makefiles for pgxs outside of `lib` since lib can't depend on `out` paths. I guess an awful "fix" would be to generate a single output and make all `postgresql.lib` dependencies into `postgresql`, but that's not a route I'd like.

I don't have much time to put in this now, a few things that could be investigated are:

- Why was the previous version generating appropriate pgxs paths in `pg_config`. The problem is that when pg_config gets called it needs to point to `out` not `lib`, but the code seems to hardcode `lib`.
- Can we patch `pg_config` to do the right thing? It's a very simple executable, but the build chain is complex

**Comment by paraseba** [comment]
@thall See https://github.com/NixOS/nixpkgs/pull/15470

**Comment by thall** [comment]
@paraseba thanks for the fix! :+1: :)
