### ISSUE TITLE
Add a guard to prevent `NIXPKGS_CONFIG` from leaking into `nixos-rebuild`/hydra farm builds

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#15230]
Suggestion: In https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/default.nix#L57 …

```nix
      configExpr =
        if config_ != null then config_
        else if configFile != "" && pathExists configFile then import (toPath configFile)
        else if homeDir != "" && pathExists configFile2 then import (toPath configFile2)
        else {};
```

… `config == null` can make `~/.nixpkgs/config.nix` silently leak into `nixos-rebuild`. I noticed it because I had a parse error in `~/.nixpkgs/config.nix` but would otherwise not have.

I think it would be a good check to set some kind of throw trap that would make evaluation fail if `config == null` on build farm.

See #15225 for an example of how this issue can bite.

cc @aszlig @kmicu @edolstra

**Comment by obadz** [comment]
Taking inspiration from f28b71023cba59ba819b0978ebffa70e3e4d1785, maybe the build farm could run with `NIXPKGS_CONFIG=/path/to/broken.nix` where the contents of broken.nix are: `NIXPKGS_CONFIG_IS_LEAKING_INTO_YOUR_DERIVATION)`

**Comment by kevincox** [comment]
@obadz That sounds good to be, do you have time to open a PR?

**Comment by obadz** [comment]
@kevincox, I don't see an easy way to do this without putting an ugly hack in hydra. Also I think the more important underlying issue would be to clean up the hodge-podge of default hardcoded paths (e.g.: `$HOME/.nixpkgs/config.nix`), environment variables (e.g.: `NIXOS_CONFIG`), members of `NIX_PATH` (e.g.: `nixos-config`) that are currently in use.

I don't see a way to do this without breaking backward compatibility and I don't think I could come up with a natural enough proposal that it would be merged so I'll just put up with the status quo and close this issue for now.
