### ISSUE TITLE
ledger-live-desktop does not start

### ISSUE THREAD

**Issue by grnnja** [NixOS/nixpkgs#152423]
### Describe the bug
ledger-live-desktop hangs and does not open a window

### Steps To Reproduce
1. install ledger-live-desktop
2. launch in terminal

### Expected behavior
ledger-live-desktop opens a new window with the program in it.

### Additional context
this gets printed in the terminal:
```Ledger Live 2.36.3
init
Checking for update
spawned internal process 97
Update for version 2.36.3 is not available (latest version: 2.36.3, downgrade is disallowed).
```
and the program hangs and does not open a window.
I'm on wayland (sway) if that's relevant.
### Notify maintainers

@andresilva @thedavidmeister @nyanloutre @RaghavSood @th0rgal

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `"nixos"`
 - channels(prem): `"nixos-22.05pre335501.c71f061c68b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by asymmetric** [comment]
There have been many releases in the meantime, please commet if this is still an issue.
