### ISSUE TITLE
haskellPackages.haste-compiler: haste-boot problems

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#15248]
Two issues I'm having:

1) When installing `haskellPackages.ghcWithPackages (self: with self; [haste-cabal-install haste-compiler])` with `nix-env`, `haste-boot` fails with this error:

```
$ haste-boot 
Downloading base libs from GitHub
Downloading Google Closure compiler...
gcc: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

2) When running in `nix-shell --pure -p 'haskellPackages.ghcWithPackages (self: with self; [haste-cabal-install haste-compiler])'`

I'm going to need to patch haste some more.

```
$ haste-boot 
Downloading base libs from GitHub
Downloading Google Closure compiler...
/nix/store/s0kpgl8a101lkymj599f5a04s4wflf5s-binutils-2.26-dev/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Command 'gcc' failed with error  code 1
```

Maybe `closure-size`? Maybe gcc5?

`hastec` still works fine if you have a previously haste-booted install though.

Creating an issue to track that as I don't have a ton of time to debug.

I'm running on nixpkgs 007ea84222f31ee96202ad96d68446ce2795e387.

**Comment by peti** [comment]
haste and tools appear to be quite broken these days.
