### ISSUE TITLE
Complaints of name collisions when building openjdk

### ISSUE THREAD

**Issue by adnelson** [NixOS/nixpkgs#15253]
## Issue description

I can't install openjdk due to path collisions, even though openjdk is not already installed. Both paths seem to be generated by the same expression.
### Steps to reproduce

``` bash
$ git clone https://github.com/NixOS/nixpkgs
$ cd nixpkgs
$ git fetch
$ git checkout 69420c5
$ nix-env -f . -iA openjdk
installing ‘openjdk-8u76b00’
building path(s) ‘/nix/store/4kjzrmpa50jvv6v829hvday3q8hh7p9h-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/wdnjj40q4p4wjks3gn026pqbcldrp1jq-openjdk-8u76b00/bin/java’ and ‘/nix/store/w6kqwzpfyzi40bxckpd4b69dq3k9d7dk-openjdk-8u76b00-jre/bin/java’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/8q9mfyhbly6zs892nzynd2gvxpmhcfw6-user-environment.drv’ failed with exit code 2
error: build of ‘/nix/store/8q9mfyhbly6zs892nzynd2gvxpmhcfw6-user-environment.drv’ failed
```
## Technical details
- System: NixOS: 16.03.616.4ac4b35 (Emu)
- Nix version: 1.11.2
- Nixpkgs version: "16.03pre-git"

**Comment by ocharles** [comment]
Could you provide us with `nix-env -q \*`? That is, a list of everything currently installed in your profile.

**Comment by adnelson** [comment]
It doesn't include openjdk, which is the only thing that would seem to matter:

```
docker-1.10.3
hipchat-2.2.1388
i3status-2.10
ncdu-1.11
nix-repl-1.11.2-8a2f5f0
nixfromnpm-0.10.0
nodejs-4.3.1
procps-3.3.11
python-2.7.11
python2.7-lsi-0.2.2
python2.7-ns_nix_toolkit-0.0.0.dev0
python3.4-ipython-4.0.3
python3.4-PyYAML-3.11
silver-searcher-0.31.0
spotify-1.0.27.71.g0a26e3b2-9
sublimetext3-3103
tree-1.7.0
```

**Comment by adnelson** [comment]
(Presumably the steps I laid out would produce the same error regardless)

**Comment by vcunat** [comment]
I think this is just #1535 (again).

**Comment by vandenoever** [comment]
The collision for `bin/java` still occurs between `openjdk` and `openjdk-jre` in branch release-16.09.

This leads to a catch 22. `nix-env --set-flag priority openjdk 10` can only be called after openjdk has installed, but it will not install while the collision has not been resolved.

The files that cause the collision are exactly the same.

**Comment by vcunat** [comment]
I never really used java stuff, but my understanding has always been that JDK is supposed to contain JRE and additional dev stuff.

**Comment by Profpatsch** [comment]
(triage) closing because of stagnation; feel free to reopen.
