### ISSUE TITLE
hedgedoc can not open note

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#152558]
### Steps To Reproduce
1. Install a HedgeDoc instance from nixpkgs master
2. Try to open a note

### Expected behavior
The editor window should appear

### Screenshots
![image](https://user-images.githubusercontent.com/86169957/147630257-59320600-fb34-48b9-a0d6-de8685c9b5da.png)

### Additional context
Probably #151331

### Notify maintainers
@Ma27

**Comment by Ma27** [comment]
Oof, sorry! Let's revert temporarily then!

**Comment by yu-re-ka** [comment]
Fixed by #152555
