### ISSUE TITLE
elementary web does not render websites

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#152612]
### Describe the bug

Here is a demonstration video: https://youtu.be/wGp0jpSEB_U

This is how it looks:

![Screenshot from 2021-12-29 19-40-42](https://user-images.githubusercontent.com/91113/147693445-e3b162a9-1313-4d26-8cfb-e225918bf9e1.png)

### Steps To Reproduce
1. Open elementary Web
2. Visit some pages
3. Instead of pages, you see dark grey (with dark mode)

### Expected behavior
Working browser that renders websites

### Additional context
This is not a new issue. I had it on NixOS as long as i can think.

The browser did also not work on elementary OS. Pages like youtube crash. So i never considered a usable program.

### Notify maintainers
@bobby285271 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.11, nixos-21.11.334797.6979c0e49bb, nixos-hardware, nixos-unstable-22.05pre340469.cb372c3b888"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bobby285271** [comment]
Probably a duplicate of https://github.com/NixOS/nixpkgs/issues/32580?

**Comment by davidak** [comment]
The workaround does work, so it seem to be related.

Tested with: `env WEBKIT_DISABLE_COMPOSITING_MODE=1 epiphany --new-window`

I'm using an Nvidia GTX 1050 Ti right now.

**Comment by AdsonCicilioti** [comment]
> The workaround does work, so it seem to be related.
> 
> Tested with: `env WEBKIT_DISABLE_COMPOSITING_MODE=1 epiphany --new-window`
> 
> I'm using an Nvidia GTX 1050 Ti right now.

This is a beautiful workaround that, despite displaying the web pages, everything is extremely busy: scrolling pages, css animations, etc.

**Comment by sinner** [comment]
It still happens, why was this issue closed? Was it closed due to a workaround?
