### ISSUE TITLE
ADRgen

### ISSUE THREAD

**Issue by wraithm** [NixOS/nixpkgs#152638]
**ADRgen**
_A command-line tool for generating and managing Architecture Decision Records_

**Metadata**

* homepage URL: https://github.com/asiermarques/adrgen
* source URL: https://github.com/asiermarques/adrgen
* license: MIT
* platforms: unix

**Comment by IvarWithoutBones** [comment]
I've created a pull request which adds it: #152813

**Comment by wraithm** [comment]
> I've created a pull request which adds it: #152813

Thank you @IvarWithoutBones!
