### ISSUE TITLE
Cannot enable bluetooth from KDE settings

### ISSUE THREAD

**Issue by niknetniko** [NixOS/nixpkgs#152622]
### Describe the bug
When bluetooth is disabled, I cannot enable it from the KDE settings.
I can, however, enable it using blueman. Afterwards, I can manage using KDE settings fine, but I have to enable using blueman first.

(I'm pretty new to linux/nixos, so excuse me if the wrong terms are used here)

### Steps To Reproduce
1. Have bluetooth disabled.
2. Go to KDE system settings (or launch `kcmshell5 bluetooth`)
3. Press the button to enable bluetooth

### Expected behavior
Bluetooth should be enabled, just like with blueman.

### Additional context
When running from the console, this error is printed:

```console
$ kcmshell5 bluetooth
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86 ): This returns 1 when using Qt HiDPI scaling.
file:///nix/store/sknfvzd3wd7kqwxkcy55ijq8l0waqsb3-bluedevil-5.23.4/share/kpackage/kcms/kcm_bluetooth/contents/ui/Bluetooth.qml:83:13: QML InlineMessage: Cannot anchor to an item that isn't a parent or sibling.
kf.bluezqt: Cannot open /dev/rfkill for writing!
```

When in this state, `rfkill` lists:

```console
$ rfkill
ID TYPE      DEVICE              SOFT      HARD
 0 wlan      dell-wifi      unblocked unblocked
 1 bluetooth dell-bluetooth   blocked unblocked
 2 wlan      phy0           unblocked unblocked
```

However, once I turned on bluetooth using blueman, I can manage it from the KDE settings just fine.
The same error is printed though, so I'm not sure what's happening.

### Notify maintainers

@ttuegel @nyanloutre  (sorry if not the correct maintainers, unsure where the issue is exactly)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(niko): `""`
 - channels(root): `"nixos-22.05pre341453.ac169ec6371, android, nix-ld"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I'm on nixos-unstable, Plasma 5.23.4, KDE Frameworks 5.87.0, QT 5.13.3

**Comment by FPtje** [comment]
I found myself with the same issue. I don't have `blueman` installed, so I tried to unblock bluetooth with the `rfkill` command:

```bash
~ ❱ rfkill
ID TYPE      DEVICE      SOFT      HARD
 0 bluetooth hci0     blocked unblocked
 1 wlan      phy0   unblocked unblocked
~ ❱ sudo rfkill unblock 0
```

After that I could change the settings in the KDE settings screen. Something seems to persist after reboot as well, because after a reboot I can still enable Bluetooth using the KDE settings screen.

**Comment by niknetniko** [comment]
I haven't had this issue in a long time, so I'll close it. If someone else still suffers from the issue, I can re-open it.
