### ISSUE TITLE
Autologin on sddm plasmawayland crashes on start

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#152726]
### Describe the bug
If autologin is enabled and plasmawayland is the default session, the entire sddm session crashes on startup.
Weirdly if autologin is disabled it works normally.

### Steps To Reproduce
1. `services.xserver.displayManager.autologin.enable=true`
2. `services.xserver.displayManager.defaultSession ="plasmawayland"`
3. reload and reboot

### Expected behavior
No crashes, the session proceeds normally

### Notify maintainers

@NixOS/qt-kde 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/store/3c249himjn7sh3cwnapmh5qgrnmd42xg-source`

**Comment by zendo** [comment]
It seems SDDM bug. try this config:

`  services.xserver.displayManager = {
    # sddm.enable = true;
    lightdm.enable = true;
    defaultSession = "plasmawayland";
    autoLogin.user = "user";
  };`

**Comment by pasqui23** [comment]
Fixed in upstream by https://github.com/sddm/sddm/pull/1496

**Comment by jotapesse** [comment]
Hello! This still seems to be an issue for me currently. Enabling both settings on the `configuration.nix` file leads to the SDDM display manager failure to start and a blank/stuck screen. I have to change VT, manually login to shell and stop/start the display manager.

OS: `NixOS 23.11 (unstable)` (upgraded from default NixOS 23.05 KDE Plasma Live ISO install)
KDE Plasma: `5.27.8`
KDE Frameworks: `5.110.0`
Qt: `5.15.10`
