### ISSUE TITLE
policycoreutils: need to fix path to pkexec in system-config-selinux

### ISSUE THREAD

**Issue by nshalman** [NixOS/nixpkgs#15271]
## Issue description

system-config-selinux has corrected paths for bash and the final python script to be invoked but has an uncorrected "/usr/bin/pkexec" in it.

I think this is a red herring in terms of what I'm actually working on, but I figured I should report it anyway.
If anyone ever wants to be able to build an selinux enabled NixOS system with a graphical desktop it would probably nice to have this be fixed.

Priority: low
### Steps to reproduce
- Install policycoreutils
- attempt to invoke system-config-selinux
## Technical details
- System: NixOS netboot media built on from nixpkgs master 
- Nix version: 1.11.2 
- Nixpkgs version: master branch

**Comment by Profpatsch** [comment]
triage: has this been fixed?

**Comment by nshalman** [comment]
I don't know. I don't currently have a system on which to try to reproduce the error.

**Comment by Profpatsch** [comment]
The package is called `policycoreutils`, but I don’t see a `semanage` binary.
