### ISSUE TITLE
policycoreutils: semanage: python can't find seobjec module 

### ISSUE THREAD

**Issue by nshalman** [NixOS/nixpkgs#15274]
## Issue description

python can't find the `seobject`.
### Steps to reproduce
- install policycoreutil
- invoke semanage
## Technical details
- System: NixOS netboot built from nixpkgs master
- Nix version: 1.11.2
- Nixpkgs version: nixpkgs master branch

**Comment by FRidh** [comment]
cc maintainer @Phreedom  (via `libsepol`)

**Comment by Profpatsch** [comment]
triage: still a problem?

**Comment by nshalman** [comment]
I don't know. I don't currently have a system on which to try to reproduce the error.
