### ISSUE TITLE
libewf: build failure

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#15289]
## Issue description

libewf fails to build due to errors from undefined libuna symbols

It might be best to update to the latest version of libewf + dependencies: https://github.com/libyal

cc @7c6f434c 

### Steps to reproduce

`nix-build "<nixpkgs>" -A libewf`

## Technical details

* System: 16.09-pre-2afb53c6e9384acf (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09-pre-b3a6cd525986d434

**Comment by gebner** [comment]
Yes, this breaks the sleuthkit build at the moment.  However, sleuthkit doesn't work with the current libewf release...

**Comment by gebner** [comment]
For reference, here is the sleuthkit bug for this: https://github.com/sleuthkit/sleuthkit/issues/642
