### ISSUE TITLE
buildGoModule: `buildFlags` is still required in some cases that are not `ldflags` or `tags`

### ISSUE THREAD

**Issue by schickling** [NixOS/nixpkgs#152812]
When building Golang modules via `buildGoModule`, the `buildFlags` option is still required in some cases that are not `ldflags` or `tags`. Currently when it's used it results in a warning:

```
trace: warning: Use the `ldflags` and/or `tags` attributes instead of `buildFlags`/`buildFlagsArray`
```

My use case for the `buildFlags` option is to set `-mod=readonly` (e.g. see screenshot below)

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1567498/147789665-3a7ab134-3246-49c5-ab8d-d277c8594ee8.png">

---

This seems to be a regression introduced with the following commits:

- https://github.com/NixOS/nixpkgs/commit/3360a376cb905ac40e77d5424089d4893e9cd157#diff-3bd7a4c69ac3233f905d7a35364e4337a30261c93ee025491538ca7236a2d2a1
- https://github.com/NixOS/nixpkgs/commit/cb7d80dcaf926a38e80044c29a8210e69f27bb80#diff-3bd7a4c69ac3233f905d7a35364e4337a30261c93ee025491538ca7236a2d2a1

**Comment by zowoq** [comment]
`buildGoModule` requires that vendoring is provided by `buildGoModule`, I don't see that `readonly` will do that.

 Can you provide more context for what you're trying to do please? Providing the derivation you want to build would be preferable.

**Comment by schickling** [comment]
I'm building and packaging [Temporalite](https://github.com/DataDog/temporalite) (as [described here](https://github.com/DataDog/temporalite/issues/31#issuecomment-1003560454)).

**Comment by zowoq** [comment]
https://github.com/DataDog/temporalite doesn't have a `vendor` directory checked into the repo so it needs to be provided by setting the `vendorSha256`.

```nix
{ fetchFromGitHub
, lib
, buildGo117Module
}:

buildGo117Module rec {
  pname = "temporalite";
  version = "1.14.1";

  src = fetchFromGitHub {
    owner = "DataDog";
    repo = pname;
    rev = "583fa90e84e6730c85add1ad781b52ba5caf9342";
    sha256 = "sha256-JuaE+KCQV1Os7qk4ZyO8g45Qn7Q3BMtsAPTOVYAxVKQ=";
  };

  subPackages = [ "cmd/temporalite" ];

  vendorSha256 = "sha256-yR5Doasf41P86flsXCoY0kukC0YSXUFKFjkMJMoQ/i0=";

  doCheck = false;
}
```

**Comment by schickling** [comment]
Thanks a lot!
