### ISSUE TITLE
Out of memory when building options-docbook.xml, needed for nixos-help and nixos-manpages

### ISSUE THREAD

**Issue by JackTheEngineer** [NixOS/nixpkgs#152853]
I encountered an out of memory (OOM) Issue on a 1 GB Digital Ocean machine (populated with nixos-infect), 
when running 

```
nixos-rebuild test
.... 
these derivations will be built:
  /nix/store/nid79111x33g53wkrgqi1dmspfvxjvgs-options-docbook.xml.drv
  /nix/store/p3a7ky1acbsmgmg6ijbcwml9mcfn418g-generated-docbook.drv
  /nix/store/gg0sngxxlgx57zkcjnzk3kghnzkf8ld0-nixos-manual-combined.drv
  /nix/store/90c6dy75rbwbmw2jfrfckgm0j2nc5nvn-manual-olinkdb.drv
  /nix/store/47ra3hvr70qznapvynbckxi26pqa73bq-nixos-manual-html.drv
  /nix/store/n38lz50h1yv5dzgif351npsajibx5yji-nixos-manpages.drv
  /nix/store/hdf5jxkqsdj06was40zm091y17n41p8j-nixos-help.drv
  /nix/store/rf53s3sa6hx89m7apxisgflr5xccc01q-nixos-help.drv
... 
```
where memory issues occur when 
`building '/nix/store/nid79111x33g53wkrgqi1dmspfvxjvgs-options-docbook.xml.drv'...`, 
and `htop` reveals it's a python(3.9.6) process running `sortXML.py`.

Is there any way to avoid building the nixos-help and nixos-manpages ?

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334921.8588b14a397"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by pennae** [comment]
> Is there any way to avoid building the nixos-help and nixos-manpages ?

you can set `documentation.nixos.enable = false` and neither will get built, but nixos-rebuild does still need a good bit of memory to run. you may have to configure some kind of swap, depending on how large your config is.
