### ISSUE TITLE
qt5.qtsvg fails to build on x86_64-darwin [21.11]

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#152902]
https://hydra.nixos.org/build/162054046
This blocks the `nixpkgs-21.11-darwin` channel.

It was retried a few times on Hydra.  Someone with a compatible machine needs to look into this, I expect.  I tried simple manual eval-only bisection (hopefully without a mistake):

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 6e0b7f0c7a779fb2f14bab2621861169525c6e67
> 065d1fad7a538e178260137b2c042d3348821798
> 4ce0b95905b039ae9e1dfdb59e8bae85f41fc06a
> ee8ff1d8282629d8ea90ae8770e97c65c062cc10
> 017fb54c28a3b4c703d4364dc611a3079b8ba48c
> 4ef54c9d1c07e7b1cf0004cb57233dff10fea033
> 5a9a0b1e33953251e2d239bb689625f2653fda2f
> 717b53d52f6f5c2a5a2a6d4496d19df07da4b4e2
> 6eb08df677ffd83643c830bb48603eec808fa45a
> ba906044ba5481bc5ff881b232b339c6173511d0
> 0350e81da5ed0569b2ac4e521517909a3649acd6
> 72121eb172199373efb89cc1b23cc5e0c540d0cd
> 0f4ec0a1b296a690749986f07f70b4a0f13677db
> 9eeff7536cd622661e1a5d26f806053c322958a5
> 66d2a5c98ce874f8e03d3ae049ded1c4b8385bea
> 9ce2035e4d1e0c358e6760e5c00d1302fc546e7c
> 8c68c6fa969d887f49a51cc784bce92d3a9e5c16
> c0ce302c5668539b3c4300f81e3cbb30a2d3a280
> 065fec456ff09d0ee34b1ea8564fe052e791602e
> 72ac7ea6a66f05e3efe4137466e3ae2d7b97ca6c
> c1968ed909b94f63a10aa7f460c798aedad6fce7
> a4a044265616155eb63dbd81a450cb174808561f
> We cannot bisect more!

and I can't see a clear candidate on the list of commits.

**Comment by Artturin** [comment]
@NixOS/darwin-maintainers

**Comment by lutzmor** [comment]
I will take a look at this tonight to see if i find the problem or a solution :).

**Comment by r-burns** [comment]
I bisected this to a4a044265616155eb63dbd81a450cb174808561f. No idea why that bump would be causing this error, though. (Also note that the commit it's cherry-picked from is still on staging-next and hasn't hit master yet. Hasn't built yet but might end up causing the same issue.)

**Comment by r-burns** [comment]
Hmm, actually triggering a full rebuild on https://github.com/NixOS/nixpkgs/commit/a4a044265616155eb63dbd81a450cb174808561f seems to work fine, so maybe the issue is hydra-specific.

**Comment by lutzmor** [comment]
I can confirm that a full rebuild worked "fine" on my macbook as well before it died during the compilation.

**Comment by veprbl** [comment]
See #152859 for another Hydra issue

**Comment by uri-canva** [comment]
What version of macOS is everyone testing on? hydra uses a very old one, which has a different mechanism for dyld caching.

**Comment by r-burns** [comment]
That's true, I tested on catalina 10.15 but I think the x86_64-darwin hydra builders are on high sierra 10.13.

**Comment by uri-canva** [comment]
@sternenseemann can you change the derivation hash of these too since it's blocking the channel? Do you have an issue for the darwin builder corruptions where we can track all the different instances of it and pull some context together?

**Comment by sternenseemann** [comment]
Given that this happens without GHC's involvement as well, it seems to strengthen the theory that this is indeed caused by ZFS corruption on the darwin builders (and "limited" to the `mac*-guest` machines), see also [this message](https://matrix.to/#/!RROtHmAaQIkiJzJZZE:nixos.org/$TciVRNZusHKMptkeRXRK9ZBnIicIvL0PSeMd9ehWaDQ?via=nixos.org&via=matrix.org&via=nixos.dev).

**Comment by vcunat** [comment]
So what... you believe we should just trigger a rebuild, say on libjpeg for x86_64-darwin?  (changing the output hash; I see no other way there)

**Comment by sternenseemann** [comment]
Yes, this works if it is the same (zfs?) corruption issue we had in haskellPackages, although you need to get lucky with all dependent packages as well, a corruption can also crop up elsewhere of course.

That being said, I haven’t seen new corruptions in a while, so maybe Graham tried something which resolved it?

**Comment by vcunat** [comment]
Oh actually... it's a good time for staging 21.11 iteration anyway.

**Comment by vcunat** [comment]
That particular build did succeed: https://hydra.nixos.org/build/163873252

**Comment by vcunat** [comment]
`nixpkgs-21.11-darwin` after a month 🎉
