### ISSUE TITLE
Mesa updates trigger too many Darwin rebuilds

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#152910]
I don't know if Mesa is even required on Darwin but I think it definitely shouldn't cause more rebuilds on Darwin than on Linux.

CI currently reports 1001-2500 rebuilds on Linux and 5001+ rebuilds on Darwin (see e.g. https://github.com/NixOS/nixpkgs/pull/152678).

For https://github.com/NixOS/nixpkgs/pull/147421 CI reported 2501-5000 rebuilds on Darwin but for the next PR (https://github.com/NixOS/nixpkgs/pull/141793) this increased to 5001+ rebuilds.

Mesa updates are merged though staging-next as staging is too slow for the biweekly releases.

@NixOS/darwin-maintainers I'll leave this issue here for you in case you want to avoid that (those rebuilds are most likely unnecessary and AFAIK Hydra's build capacity for Darwin is severely lacking). Otherwise you may just close it as well.

**Edit:** Oh, and if something just needs the headers it shouldn't depend on Mesa, see: https://github.com/NixOS/nixpkgs/pull/118479 and https://github.com/NixOS/nixpkgs/issues/44831.

**Comment by veprbl** [comment]
> **Edit:** Oh, and if something just needs the headers it shouldn't depend on Mesa, see: #118479 and #44831.

Not the case on darwin:
https://github.com/NixOS/nixpkgs/blob/eb9d896be031f146fc200e3e947f78f0234943ac/pkgs/development/libraries/mesa/stubs.nix#L10-L17

**Comment by primeos** [comment]
@matthewbauer what does `On macOS, libglvnd is not supported` mean? I looked though the Git history and you didn't document this in https://github.com/NixOS/nixpkgs/commit/0121da2af1220a059732f00606d778339caf3e6b or https://github.com/NixOS/nixpkgs/pull/62715 (that code was later extracted into `stubs.nix`: https://github.com/NixOS/nixpkgs/commit/3c45b0c00a375c7b5b768cb5a6e6ddea2c88c67f).

It looks like `libglvnd` does at least build on Darwin, e.g.: https://github.com/NixOS/nixpkgs/commit/fb5bd7256dee9b6d5b2a5e28a2d139e458e11783 and ef13a2129b59d21410ea04a5fc2e9e26559aa43a. I have no idea if the dispatching works but I'd assume that at least the headers should be usable on Darwin.

**Comment by veprbl** [comment]
IIRC the `libglvnd` used to be marked as broken on darwin in the past, I don't know why.

**Comment by primeos** [comment]
The strange thing is that @matthewbauer fixed the `libglvnd` build on Darwin (https://github.com/NixOS/nixpkgs/commit/fb5bd7256dee9b6d5b2a5e28a2d139e458e11783) before https://github.com/NixOS/nixpkgs/commit/0121da2af1220a059732f00606d778339caf3e6b. And it wasn't marked as broken at that time.

The following doesn't return anything: `git log -pS broken pkgs/development/libraries/libglvnd/default.nix`.
And `git log -pS platforms pkgs/development/libraries/libglvnd/default.nix` only returns two commits: 750e7ba0d958a08cdef16a2147263586a55a3e4d and 7a39b0c43b6e8d913db2882b52e1f81b1eb96bd4 (the latter added the Darwin support).

**Comment by veprbl** [comment]
The original issue should be fixed now.

Regarding libglvnd, I'm not sure what the deal is. The X11 implementation for OpenGL with `libGL`/`mesa` probably shouldn't differ much between Linux/BSD and macOS. Probably not worth looking into that, unless there is some maintenance burden associated with that.

**Comment by primeos** [comment]
@veprbl Ok, thanks a lot for decreasing the number of unnecessary rebuilds.
