### ISSUE TITLE
Hebrew spell checker by default

### ISSUE THREAD

**Issue by Net-Mist** [NixOS/nixpkgs#152981]
Hello,

### Describe the bug
In some gtk applications (Zim for instance). I discover that I had by default an Hebrew spell checker.
This looks like a weird configuration and after investigation, I discover that pygtkspellcheck uses pyenchant that uses enchant that is built with hspell (a Hebrew spellchecker, not to confound with hunspell a generic one) as propagatedBuildInputs (see line 39 of .https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/enchant/2.x.nix)

I was wondering if this was on purpose, or if this is an issue that need to be fixed. And if so, how could I help ?

### Steps To Reproduce
1. install any app that uses pygtkspellcheck
2. see that by default, the spellchecker has a Hebrew option

### Expected behavior
If we don't need a Hebrew spellchecker, then don't install it

### Notify maintainers
@jtojnar

**Comment by jtojnar** [comment]
If we were to disable it we would need to find a way to enable it at runtime without having to rebuild enchant.

**Comment by Net-Mist** [comment]
I'm not sure to understand why hspell in an exception compared to all the other language-specific spell checkers.
As far as I know, users who want Hebrew spell checking could install `aspellDicts.he`, which would provide the same feature ?

I'm very new to Nix, so I'm not sure how we can enable it without having to rebuild enchant. Do you have any suggestion ?

**Comment by jtojnar** [comment]
I assume language specific libraries like voikko or hspell provide features that are more adapted to their respective languages, whereas aspell dictionaries are just glorified word lists. But not being speaker of those languages I am not able to tell.

There is really no simple way to implement dynamically loaded modules with Nix packages. One common method is installing the modules to a global path like `/run/current-system/sw/lib/program-xyz/plug-ins` and patching the plug-in loader to look there but that will only work on NixOS (or require manual installation to the directory on other platforms) and smells of FHS. Slightly nicer option is patching the plug-in loader to use plug-in path from some environment variable and then list store paths of individual modules in it but that still requires the env var to be defined somewhere (either in NixOS module or program wrapper).

And that assumes the dependency can be loaded dynamically (not sure if that is the case here).

**Comment by Net-Mist** [comment]
Hello,
after some time digging into it I now understand the difficulty of the task.
I will close the issue as right now I don't know how to solve this.
One note on the side : it seems [archlinux solved the issue on there side](https://github.com/archlinux/svntogit-packages/blob/packages/enchant/trunk/PKGBUILD). I tried to reproduce inside Nix without success.
Maybe one day I will have the level to write a PR. Thanks @jtojnar for your time

**Comment by jtojnar** [comment]
Arch links enchant against hspell too. The difference is that they rely on `libhspell.so.0` being found in `/usr/lib`. When user does not install the optional dependency, the dynamic linker will not be able to find it so [`dlopen` call will fail](https://github.com/AbiWord/enchant/blob/49d87fea52bb19770f76710cfaf69881246a7219/src/lib.c#L843), making enchant skip the provider. On Nix, we do not have `/usr/lib` so we rely `DT_RUNPATH` entry in the ELF file. And since the `DT_RUNPATH` contains absolute paths to directories containing libraries listed in `DT_NEEDED` entries, Nix will include the packages into the closure.
