### ISSUE TITLE
pypyPackages scripts are missing PYTHONPATH entries

### ISSUE THREAD

**Issue by rardiol** [NixOS/nixpkgs#15297]
## Issue description

python modules built for pypy are wrapped including only pypy's own site-packages, and not dependencies' site-packages or the module's own.
### Steps to reproduce

```

$ nix-build -A pypyPackages.pbr
$ ./result/bin/pbr
$ grep PYTHONPATH ./result/bin/pbr

```
## Technical details
- System: 16.09pre82504.a42f845 (Flounder)
- Nix version: nix-env (Nix) 1.11.24
- Nixpkgs version: I tried @a42f845 and @551296a

**Comment by FRidh** [comment]
Thanks for reporting. It's indeed only pypy's site-packages. Typically I test with `nix-shell`, and I noticed there it was the other way around: dependencies were in PYTHONPATH but not pypy's own site-packages.

**Comment by Profpatsch** [comment]
triage: has this been fixed?

**Comment by rardiol** [comment]
I think not:

```
Traceback (most recent call last):
  File "/nix/store/56zch2rmc4apz5r0lmlpgl4y1whrbww8-pypy5.10-pbr-4.0.2/bin/.pbr-wrapped", line 8, in <module>
    from pbr.cmd.main import main
ImportError: No module named pbr

```

and the wrapping for the executable:
```

#! /nix/store/qckzjk3406va7h6s40cy9s75z2w715rq-bash-4.4-p19/bin/bash -e
export PATH='/nix/store/wwwzb58bc72xgl4i0b986q1bsd7hs2vd-pypy-5.10.0/bin:/nix/store/56zch2rmc4apz5r0lmlpgl4y1whrbww8-pypy5.10-pbr-4.0.2/bin:/nix/store/92n6a59kpzw0kp1gw0w45a3qxjpraynv-pypy5.10-setuptools-39.0.1/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/56zch2rmc4apz5r0lmlpgl4y1whrbww8-pypy5.10-pbr-4.0.2/bin/.pbr-wrapped"  "${extraFlagsArray[@]}" "$@"

```

It was too long ago for me to remember much, but I assume there should be something about PYTHONPATH on the wrapping that is missing to tell the executable where to look for the pbr site package?

**Comment by rardiol** [comment]
Seems to work now
