### ISSUE TITLE
Gtk settings not respected in plasma wayland session

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#152914]
### Describe the bug
The theme of plasma wayland is not applied to gtk applications unlike on the X11 session.

### Steps To Reproduce
1. Modify plasma theme
2. Set gtk theme to breeze
3. Start plasmawayland

### Expected behavior
Gtk applications respect the breeze theme

### Screenshots
![immagine](https://user-images.githubusercontent.com/6931743/147820677-6255a64e-0b61-4e2c-9260-0bd3136d6236.png)

### Additional context
This is probably similar to https://github.com/NixOS/nixpkgs/issues/67704

### Notify maintainers

@NixOS/qt-kde @NixOS/gnome 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/store/3c249himjn7sh3cwnapmh5qgrnmd42xg-source`

**Comment by jtojnar** [comment]
EasyEffects is a libadwaita-based app, which only supports Adwaita theme, see also https://gitlab.gnome.org/GNOME/libadwaita/-/issues/215. The work around is using `GTK_THEME` environment variable.

**Comment by pasqui23** [comment]
Result with `GTK_THEME=Breeze`
![immagine](https://user-images.githubusercontent.com/6931743/147832198-0780cfbf-a6ca-4134-92cd-cb314495dd6b.png)

**Comment by jtojnar** [comment]
Then that sounds like Breeze bug. Not sure how well it supports GTK 4 and libadwaita since the [repo](https://invent.kde.org/plasma/breeze-gtk) only lists GTK 2 and 3 (even though there is `src/gtk4` directory).

**Comment by pasqui23** [comment]
The weird thing is that theme is NOT broken on X11
![immagine](https://user-images.githubusercontent.com/6931743/147840481-c62ff78d-4fad-4371-92c7-fda345ac3de2.png)

**Comment by pasqui23** [comment]
So I've put https://bugs.kde.org/show_bug.cgi?id=447755

**Comment by pasqui23** [comment]
Also as additional data point if I run `MOZ_WAYLAND_ENABLE=1 firefox` firefox does not take the colors from the surrounding Breeze theme anymore,unlike again on X11 or even XWayland

**Comment by pasqui23** [comment]
`GTK_THEME=Breeze lutris`
![immagine](https://user-images.githubusercontent.com/6931743/149671973-56ffa54d-d079-4e5e-9b56-90e2e6781ce9.png)

The problem seems to be specifically about cursors and characters as icons and colors seems to be picked up

**Comment by pasqui23** [comment]
But then again mozilla does not pick them up???

**Comment by jtojnar** [comment]
It is probably better to open a separate issue about GTK 3-based apps.
And for Firefox, do you perhaps set `GTK_USE_PORTAL=1`? With that enabled, the file chooser will be displayed by a different process, which might be running in a scope that does not include your session’s environment.

**Comment by pasqui23** [comment]
> It is probably better to open a separate issue about GTK 3-based apps.

I suspect  that there is the same underlying problem: on wayland gtk{3,4} apps do not take the correct gtk setting from the theme

> And for Firefox, do you perhaps set `GTK_USE_PORTAL=1`? With that enabled, the file chooser will be displayed by a different process, which might be running in a scope that does not include your session’s environment.

Yes but I was not talking about the file chooser

![immagine](https://user-images.githubusercontent.com/6931743/149676441-d496527c-31f6-46c8-9b31-1c821f1e81d2.png)

**Comment by pasqui23** [comment]
So to recap:
* Okular is how I want them to look, with a darker background
* Lutris (GTK4) takes the color scheme but not the fonts
* Firefox (GTK3) do not take anything from the environment

**Comment by jtojnar** [comment]
Did any of these work in the past?

- I believe Okular is Qt-based so no surprise there.
- Lutris is [GTK 3](https://github.com/lutris/lutris/blob/66675a4d5537f6b2a2ba2b6df0b3cdf8924c823a/lutris/gui/application.py#L30) so I would expect it to work unless the app does something.
- FIrefox probably uses something weird – maybe it just detect if theme is dark or light and use its own theme that most closely matches.

I would suggest using plain demo apps for testing:
- `nix-shell -I nixpkgs=channel:nixos-unstable -p gtk3.dev --run gtk3-widget-factory`
- `nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-widget-factory`
- `nix-shell -I nixpkgs=channel:nixos-unstable -p libadwaita.devdoc --run adwaita-1-demo`

**Comment by pasqui23** [comment]
Again both Lutris and Firefox did the were correctly themed on X11

`nix-shell -I nixpkgs=channel:nixos-unstable -p gtk3.dev --run gtk3-widget-factory`
![immagine](https://user-images.githubusercontent.com/6931743/149679938-649346c3-e547-4fb0-ae40-d1c5d313253b.png)
`nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-widget-factory`
```
; nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-widget-factory
def-matcher: command not found
these 64 paths will be fetched (97.49 MiB download, 340.46 MiB unpacked):
  /nix/store/0cf230fh397hq3kya1dx4nzwiywwyq2d-libbs2b-3.1.0
  /nix/store/1cqjdlzr2yrgbdhd9k7q88hc0zgwxi2s-fluidsynth-2.2.3
  /nix/store/1sq17rzzpkvx8f7kj7d0lkawvj40r1iy-opencv-4.5.4
  /nix/store/1wp9bdg5s1sp9gcsdhf031d0ccqry11i-soundtouch-2.2
  /nix/store/1z1jdja217gv02l12ldnkfhl1hvii2rv-lv2-1.18.2
  /nix/store/2h92j112cl2cs7ji5jrln0qygd5ywrb2-openh264-2.1.1
  /nix/store/2kp3qijgpvlc2yc0yrsdwilpc6414pdm-neon-0.31.2
  /nix/store/2lv6h3z953ssn156fa1gs59sdql2p6pk-faad2-2.10.0
  /nix/store/45636agiysjfajk142llsv10b1grix9q-webrtc-audio-processing-0.3.1
  /nix/store/4y0iyjm6rlhvzq7srrj8i0h016wx64s3-gst-plugins-bad-1.18.2
  /nix/store/5c6gjdbjb710wpqdawgfjl35kw4dh5s2-SDL-1.2.15
  /nix/store/5r12pcbz6la382zmv1iz8km0j0wdcw75-libXdamage-1.1.5
  /nix/store/637r6qqw02z110qxfdgfnybzk7bq1cn1-lilv-0.24.12
  /nix/store/68gdm05nkpa0gwrb5kdncv01zmw5bd7d-libnice-0.1.18
  /nix/store/6gayfyr00flshn5g7n053imcncaqq2mk-libofa-0.9.3
  /nix/store/6l05h77x3gg13n88ybbjc8hz4xsbnwzv-gtk4-4.4.1
  /nix/store/7rgld713p68chq6g0ffg8axjchh1hr6y-celt-0.11.3
  /nix/store/8nw2i2pqc52i5m79jd1g6clmspfn02bm-sbc-1.4
  /nix/store/9dwycjzvj9d4ps56rad53fr8qvz2igyl-graphene-1.10.6
  /nix/store/b2n79i6sfj7lmbdvh2ikccqb56qxmjyw-libaom-3.2.0
  /nix/store/b40z50z2qw2ggimavi7lmcb04ica35bb-gsm-1.0.19
  /nix/store/bqs2wzv6fq775zwq6c9fgfc4kgiakw31-libgme-0.6.3
  /nix/store/cqjdh15vkjnpygmfry7c5yxsmvbzmxps-serd-0.30.10
  /nix/store/cym256gjima8fr9g956gvaw9ds1yb4k9-libde265-1.0.8
  /nix/store/dfq7mfkxwirxy9pwd0idv8q6mm1hz195-sord-unstable-2021-01-12
  /nix/store/dsdmb6lrx1xla3ij12ds6g8fg5viib3j-libkate-0.4.1
  /nix/store/dvn2qlhbacvlplkyp2hzj47ngx4kk8nc-sratom-0.6.8
  /nix/store/dysrr4c8ww1mk94g37vs51i0ymhyskhc-mpg123-1.29.3
  /nix/store/f8hjvaj8ssnvjykmj3wb679yh3y3h8is-libsrtp-2.4.2
  /nix/store/f8ycpm67dbfpkbmqq7w2l8bqgls9wdzg-wildmidi-0.4.4
  /nix/store/fka04yxriqqdlln5ml4g59sd58nq26s9-chromaprint-1.5.1
  /nix/store/gj7lb382qsjkk75fapvm041j99gqb1g3-libjack2-1.9.19
  /nix/store/gypi2hb320gcrgbl8qm8yra1n816i4pz-libdc1394-2.2.6
  /nix/store/hamy8xwf0b2pqdw2p0i4azx3n1y5np16-gtk4-4.4.1-dev
  /nix/store/hnwn00ygvp0mwc40ngmrpwbz2ng7jzxm-libgudev-237
  /nix/store/i8cpqcm1bkfdjvj70lrhcps3kcmblb73-libopenmpt-0.5.11-lib
  /nix/store/im96wpq19b48q4yz2ycb653qx9x7yn1y-raptor2-2.0.15
  /nix/store/j6lx8wqkfgyp2fk3x6zfgk4s2qfbb8pg-vo-aacenc-0.1.3
  /nix/store/j9ln0wln743xdqv7j0arr39zq9c9xzjg-flite-2.2
  /nix/store/jbd0ar7b0idzf6sm6lf74c2mxfsmvln6-rtmpdump-unstable-2019-03-30
  /nix/store/jj0mx13i0am2n7nnhxxfq85qggjq0924-openal-soft-1.21.1
  /nix/store/jlchzfa36j064jzq86lrjb9j4fqhl1vc-libxslt-1.1.34
  /nix/store/l6jrsn7wi2bd4wb3cyx5ahgdsr9zm6yw-libmodplug-0.8.9.0
  /nix/store/lr7rwlzm4j464mz2wfb4939pxgg0v9ac-mjpegtools-2.2.1-lib
  /nix/store/m1n1m2lyikg37pv8qawvrccfbm65v61i-gupnp-igd-1.2.0
  /nix/store/mdyzs759dpdylsl5dsv7ns24wlwrfkl7-gssdp-1.4.0.1
  /nix/store/n0dhim8y9284rx8svsb9p01nij8psbjj-libraw1394-2.1.2
  /nix/store/n7gdh43w2pwizb49zf6713rsf7wfd9dz-gupnp-1.4.1
  /nix/store/nb7rwwfp2dagw59lc9c1wy59zmzd251c-spandsp-0.0.6
  /nix/store/nx3k95zan21pn0kl2v59ac9sk5bccb8z-libdvdread-6.1.2
  /nix/store/nzjmkizwy603czp2zchh1n1dbyd66xpk-fdk-aac-2.0.2
  /nix/store/p4izm080x2mlzd349wbca6jrzl1r4p9m-gtk+-2.24.33
  /nix/store/p6h5mg0d3sfbyj5siqn9sx30m4psbmah-libdvdcss-1.4.3
  /nix/store/qmbi73vhq7pyp25xvh8k6nq5i2nybsxc-fftw-double-3.3.10
  /nix/store/qnqg19z3w6s9nvpqnghjyibdb46x60iz-lrdf-0.6.1
  /nix/store/qwnvdnwpgibhangadxvakqiz53h7ivif-libdv-1.0.0
  /nix/store/riin5k0hqm7npm86r0izcpvgbbd1dgky-libmms-0.6.4
  /nix/store/ryj72ashr27gf4kh0ssgi3zpiv8fxw53-librsvg-2.52.4
  /nix/store/s5gnhm63nagx2c6r239n4dygffszrfkb-freepats-20060219
  /nix/store/vbby8b50iif61ac34vvkrbai20ll4n1h-libmicrodns-0.2.0
  /nix/store/vswfh6rm9i38yxja7ys8ndnky0f1ky08-libdvdnav-6.1.1
  /nix/store/xrxggr3q0b2xabb4wxnqpvnf603bqjlg-glu-9.0.2
  /nix/store/y7ifv9jzsqmhsp9w075061giayds36gk-ilmbase-2.5.7
  /nix/store/yfs944mkrq6wz0z5xf7hgccqc7k7ss7n-directfb-1.7.7
copying path '/nix/store/9dwycjzvj9d4ps56rad53fr8qvz2igyl-graphene-1.10.6' from 'https://cache.nixos.org'...
copying path '/nix/store/5r12pcbz6la382zmv1iz8km0j0wdcw75-libXdamage-1.1.5' from 'https://cache.nixos.org'...
copying path '/nix/store/2lv6h3z953ssn156fa1gs59sdql2p6pk-faad2-2.10.0' from 'https://cache.nixos.org'...
copying path '/nix/store/nzjmkizwy603czp2zchh1n1dbyd66xpk-fdk-aac-2.0.2' from 'https://cache.nixos.org'...
copying path '/nix/store/s5gnhm63nagx2c6r239n4dygffszrfkb-freepats-20060219' from 'https://cache.nixos.org'...
copying path '/nix/store/fka04yxriqqdlln5ml4g59sd58nq26s9-chromaprint-1.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/j9ln0wln743xdqv7j0arr39zq9c9xzjg-flite-2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/b40z50z2qw2ggimavi7lmcb04ica35bb-gsm-1.0.19' from 'https://cache.nixos.org'...
copying path '/nix/store/y7ifv9jzsqmhsp9w075061giayds36gk-ilmbase-2.5.7' from 'https://cache.nixos.org'...
copying path '/nix/store/b2n79i6sfj7lmbdvh2ikccqb56qxmjyw-libaom-3.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/0cf230fh397hq3kya1dx4nzwiywwyq2d-libbs2b-3.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/cym256gjima8fr9g956gvaw9ds1yb4k9-libde265-1.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/bqs2wzv6fq775zwq6c9fgfc4kgiakw31-libgme-0.6.3' from 'https://cache.nixos.org'...
copying path '/nix/store/hnwn00ygvp0mwc40ngmrpwbz2ng7jzxm-libgudev-237' from 'https://cache.nixos.org'...
copying path '/nix/store/dsdmb6lrx1xla3ij12ds6g8fg5viib3j-libkate-0.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/vbby8b50iif61ac34vvkrbai20ll4n1h-libmicrodns-0.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7rgld713p68chq6g0ffg8axjchh1hr6y-celt-0.11.3' from 'https://cache.nixos.org'...
copying path '/nix/store/qmbi73vhq7pyp25xvh8k6nq5i2nybsxc-fftw-double-3.3.10' from 'https://cache.nixos.org'...
copying path '/nix/store/xrxggr3q0b2xabb4wxnqpvnf603bqjlg-glu-9.0.2' from 'https://cache.nixos.org'...
copying path '/nix/store/mdyzs759dpdylsl5dsv7ns24wlwrfkl7-gssdp-1.4.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/p4izm080x2mlzd349wbca6jrzl1r4p9m-gtk+-2.24.33' from 'https://cache.nixos.org'...
copying path '/nix/store/qwnvdnwpgibhangadxvakqiz53h7ivif-libdv-1.0.0' from 'https://cache.nixos.org'...
copying path '/nix/store/p6h5mg0d3sfbyj5siqn9sx30m4psbmah-libdvdcss-1.4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/gj7lb382qsjkk75fapvm041j99gqb1g3-libjack2-1.9.19' from 'https://cache.nixos.org'...
copying path '/nix/store/riin5k0hqm7npm86r0izcpvgbbd1dgky-libmms-0.6.4' from 'https://cache.nixos.org'...
copying path '/nix/store/l6jrsn7wi2bd4wb3cyx5ahgdsr9zm6yw-libmodplug-0.8.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/n0dhim8y9284rx8svsb9p01nij8psbjj-libraw1394-2.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/ryj72ashr27gf4kh0ssgi3zpiv8fxw53-librsvg-2.52.4' from 'https://cache.nixos.org'...
copying path '/nix/store/n7gdh43w2pwizb49zf6713rsf7wfd9dz-gupnp-1.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/f8hjvaj8ssnvjykmj3wb679yh3y3h8is-libsrtp-2.4.2' from 'https://cache.nixos.org'...
copying path '/nix/store/jlchzfa36j064jzq86lrjb9j4fqhl1vc-libxslt-1.1.34' from 'https://cache.nixos.org'...
copying path '/nix/store/nx3k95zan21pn0kl2v59ac9sk5bccb8z-libdvdread-6.1.2' from 'https://cache.nixos.org'...
copying path '/nix/store/5c6gjdbjb710wpqdawgfjl35kw4dh5s2-SDL-1.2.15' from 'https://cache.nixos.org'...
copying path '/nix/store/gypi2hb320gcrgbl8qm8yra1n816i4pz-libdc1394-2.2.6' from 'https://cache.nixos.org'...
copying path '/nix/store/lr7rwlzm4j464mz2wfb4939pxgg0v9ac-mjpegtools-2.2.1-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/2kp3qijgpvlc2yc0yrsdwilpc6414pdm-neon-0.31.2' from 'https://cache.nixos.org'...
copying path '/nix/store/jj0mx13i0am2n7nnhxxfq85qggjq0924-openal-soft-1.21.1' from 'https://cache.nixos.org'...
copying path '/nix/store/1sq17rzzpkvx8f7kj7d0lkawvj40r1iy-opencv-4.5.4' from 'https://cache.nixos.org'...
copying path '/nix/store/1cqjdlzr2yrgbdhd9k7q88hc0zgwxi2s-fluidsynth-2.2.3' from 'https://cache.nixos.org'...
copying path '/nix/store/m1n1m2lyikg37pv8qawvrccfbm65v61i-gupnp-igd-1.2.0' from 'https://cache.nixos.org'...
copying path '/nix/store/dysrr4c8ww1mk94g37vs51i0ymhyskhc-mpg123-1.29.3' from 'https://cache.nixos.org'...
copying path '/nix/store/vswfh6rm9i38yxja7ys8ndnky0f1ky08-libdvdnav-6.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/2h92j112cl2cs7ji5jrln0qygd5ywrb2-openh264-2.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/68gdm05nkpa0gwrb5kdncv01zmw5bd7d-libnice-0.1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/6gayfyr00flshn5g7n053imcncaqq2mk-libofa-0.9.3' from 'https://cache.nixos.org'...
copying path '/nix/store/yfs944mkrq6wz0z5xf7hgccqc7k7ss7n-directfb-1.7.7' from 'https://cache.nixos.org'...
copying path '/nix/store/im96wpq19b48q4yz2ycb653qx9x7yn1y-raptor2-2.0.15' from 'https://cache.nixos.org'...
copying path '/nix/store/jbd0ar7b0idzf6sm6lf74c2mxfsmvln6-rtmpdump-unstable-2019-03-30' from 'https://cache.nixos.org'...
copying path '/nix/store/8nw2i2pqc52i5m79jd1g6clmspfn02bm-sbc-1.4' from 'https://cache.nixos.org'...
copying path '/nix/store/cqjdh15vkjnpygmfry7c5yxsmvbzmxps-serd-0.30.10' from 'https://cache.nixos.org'...
copying path '/nix/store/1wp9bdg5s1sp9gcsdhf031d0ccqry11i-soundtouch-2.2' from 'https://cache.nixos.org'...
copying path '/nix/store/nb7rwwfp2dagw59lc9c1wy59zmzd251c-spandsp-0.0.6' from 'https://cache.nixos.org'...
copying path '/nix/store/j6lx8wqkfgyp2fk3x6zfgk4s2qfbb8pg-vo-aacenc-0.1.3' from 'https://cache.nixos.org'...
copying path '/nix/store/45636agiysjfajk142llsv10b1grix9q-webrtc-audio-processing-0.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/dfq7mfkxwirxy9pwd0idv8q6mm1hz195-sord-unstable-2021-01-12' from 'https://cache.nixos.org'...
copying path '/nix/store/i8cpqcm1bkfdjvj70lrhcps3kcmblb73-libopenmpt-0.5.11-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/qnqg19z3w6s9nvpqnghjyibdb46x60iz-lrdf-0.6.1' from 'https://cache.nixos.org'...
copying path '/nix/store/dvn2qlhbacvlplkyp2hzj47ngx4kk8nc-sratom-0.6.8' from 'https://cache.nixos.org'...
copying path '/nix/store/1z1jdja217gv02l12ldnkfhl1hvii2rv-lv2-1.18.2' from 'https://cache.nixos.org'...
copying path '/nix/store/637r6qqw02z110qxfdgfnybzk7bq1cn1-lilv-0.24.12' from 'https://cache.nixos.org'...
copying path '/nix/store/f8ycpm67dbfpkbmqq7w2l8bqgls9wdzg-wildmidi-0.4.4' from 'https://cache.nixos.org'...
copying path '/nix/store/4y0iyjm6rlhvzq7srrj8i0h016wx64s3-gst-plugins-bad-1.18.2' from 'https://cache.nixos.org'...
copying path '/nix/store/6l05h77x3gg13n88ybbjc8hz4xsbnwzv-gtk4-4.4.1' from 'https://cache.nixos.org'...
copying path '/nix/store/hamy8xwf0b2pqdw2p0i4azx3n1y5np16-gtk4-4.4.1-dev' from 'https://cache.nixos.org'...

(gtk4-widget-factory:18821): Gtk-WARNING **: 23:07:58.029: Unknown key gtk-button-images in /home/me/.config/gtk-4.0/settings.ini

(gtk4-widget-factory:18821): Gtk-WARNING **: 23:07:58.029: Unknown key gtk-menu-images in /home/me/.config/gtk-4.0/settings.ini

(gtk4-widget-factory:18821): Gtk-WARNING **: 23:07:58.029: Unknown key gtk-toolbar-style in /home/me/.config/gtk-4.0/settings.ini

** (gtk4-widget-factory:18821): ERROR **: 23:07:58.983: GstPlayer: 'playbin' element not found, please check your setup
/tmp/nix-shell-16391-0/rc: riga 3: 18821 Trace/breakpoint trap   (core dump creato) gtk4-widget-factory

```

`nix-shell -I nixpkgs=channel:nixos-unstable -p libadwaita.devdoc --run adwaita-1-demo`
![immagine](https://user-images.githubusercontent.com/6931743/149680045-ddf6acaa-e110-4ba5-9087-58f44785d50e.png)

**Comment by pasqui23** [comment]
Ok so why did lutris pick the colors?

**Comment by jtojnar** [comment]
I do not know, maybe it is running as Xwayland client?

**Comment by pasqui23** [comment]
Ok now I've run it again and it does not seem to follow the theme anymore

**Comment by pasqui23** [comment]
Ah ok I had it ran with `GTK_THEME=Breeze`

**Comment by pasqui23** [comment]
`GTK_THEME=Breeze nix-shell -I nixpkgs=channel:nixos-unstable -p gtk3.dev --run gtk3-widget-factory`
![immagine](https://user-images.githubusercontent.com/6931743/149685650-30e17f0a-d6c0-470c-8d93-53a333669457.png)

`nix-shell -I nixpkgs=channel:nixos-unstable -p libadwaita.devdoc --run adwaita-1-demo`
![immagine](https://user-images.githubusercontent.com/6931743/149685757-8f05c105-6e36-4f90-9c7f-2be7077ddb13.png)

Of note that Adwaita's "Dark mode" do not change the colors unlike without `GTK_THEME=Breeze`

**Comment by pasqui23** [comment]
Seem like 4 different issues:

* The font is rendered badly
* GTK 4 apps do not run (But adwaita do?)
* GTK_THEME is not set by plasma
* The color theme is not passed to Adwaita apps

**Comment by pasqui23** [comment]
Again all the above only on plasma wayland

**Comment by jtojnar** [comment]
The GTK 4 widget factory is failing because it lacks the `playbin` element in `GST_PLUGIN_SYSTEM_PATH_1_0` environment variable (I have it in the global environment). You can also try `nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-demo`.

**Comment by pasqui23** [comment]
`nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-demo`
![immagine](https://user-images.githubusercontent.com/6931743/149689392-2fcc7176-c075-459b-9f60-cdb8785905e2.png)
`GTK_THEME=Breeze nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-demo`
![immagine](https://user-images.githubusercontent.com/6931743/149689445-cdf57d2f-3fbb-4f73-a55a-101840e92f16.png)

It seems that color themes are simply not passed to GTK 4

**Comment by pasqui23** [comment]
Ok I've created 3 new issue where we can discuss it further
* https://github.com/NixOS/nixpkgs/issues/155293
* https://github.com/NixOS/nixpkgs/issues/155292
* https://github.com/NixOS/nixpkgs/issues/155291

**Comment by eddyb** [comment]
I now suspect a strange `dconf` interaction: https://github.com/NixOS/nixpkgs/issues/180720#issuecomment-1228334905

I've also left a comment at https://bugs.kde.org/show_bug.cgi?id=447755#c6 with these suggestions:
- make sure you have `dconf`
  - for NixOS specifically: `programs.dconf.enable = true;` (maybe it should be enabled by default for plasma5, just like e.g. kde-gtk-config is?)
- run `dconf read /org/gnome/desktop/interface/gtk-theme` to confirm that it is in fact incorrect
- go in System Settings and set the Application Style GTK theme *again*
