### ISSUE TITLE
Systemd bump

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#153093]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version:
desired version:

###### Notify maintainers

maintainers: @andir @eelco @flokli @kloenk

###### Note for maintainers

Please tag this issue in your PR.

**Comment by flokli** [comment]
PRs were not checked. This is tracked in https://github.com/NixOS/nixpkgs/pull/150491.
