### ISSUE TITLE
elvish: ‘daemon is not supported in this build’

### ISSUE THREAD

**Issue by cherryblossom000** [NixOS/nixpkgs#153034]
### Describe the bug
Elvish v0.17.0 seems to be built without daemon support.

### Steps To Reproduce
1. Checkout master branch (caecbc46babb837d8021bcb5e250c83943720474)
2. `nix-build -A elvish`
3.
```
❯ ./result/bin/elvish
daemon is not supported in this build
Exception: ./result/bin/elvish exited with 2
[tty 149], line 1: ./result/bin/elvish
```

This error also occurs for e.g. `./result/bin/elvish -c 'echo test'`, but not when using `-help`, `-buildinfo`, and `-version`.

### Expected behavior
The Elvish interactive shell would start.

### Notify maintainers
@vrthra @AndersonTorres

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

As mentioned above I'm using the master branch of nixpkgs (commit caecbc46babb837d8021bcb5e250c83943720474).

 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.2.0, macOS 10.16` (I'm actually using macOS 12.1; not sure why `nix-info` gives the wrong result)
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(myusername): `"darwin, home-manager, nixpkgs-22.05pre340506.5c37ad87222"`
 - channels(root): `"darwin, home-manager, nixpkgs-22.05pre340506.5c37ad87222"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by fehnomenal** [comment]
I just came across this. It turns out that `excludedPackages` is ignored and so all packages get build and the new 'nodaemon' main overwrites the real main executable.

Fixed with #153110
