### ISSUE TITLE
NixOS 20.09 and onwards broke systemd predictable network interface naming

### ISSUE THREAD

**Issue by nh2** [NixOS/nixpkgs#153134]
I believe that this change

https://github.com/NixOS/nixpkgs/commit/822918df4cec0ee14a657efb86a08bf7f457e647#diff-344943ac406571508ecc8d0311e237519c34548ffaf4eba83a15758a1ced65a4R57

> nixos/scripted-networking: use udev to configure link MACAddress and MTUBytes

accidentally broke systemd's [PredictableNetworkInterfaceNames](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/).

For example, for my Nixops Hetzner machine, on 20.03, the default interface `eth0` got renamed to `enp6s0`, but on 21.11 it stays `eth0`, making it lose Internet on the upgrade.

---

I noticed this because my Hetzner server lost Internet during the upgrade and I spent > 16 hours figuring out why.

`diff`ing the output of `udevadm info -e` between 20.03 and 21.11, I found:

```diff
-E: ID_NET_LINK_FILE=/nix/store/vzbkzyw5x3ilqj6wg0q8l5gzcli5pn5f-systemd-243.7/lib/systemd/network/99-default.link
+E: ID_NET_LINK_FILE=/etc/systemd/network/40-eth0.link
```

On 20.03 that default file `/nix/store/abc123...-systemd-243.7/lib/systemd/network/99-default.link` contained:

```ini
[Match]
OriginalName=*

[Link]
NamePolicy=keep kernel database onboard slot path
MACAddressPolicy=persistent
```

This just says to do the usual systemd name policy finding as linked above.

But on 20.09 and onwards, `/etc/systemd/network/40-eth0.link` contains:

```ini
[Match]
OriginalName=eth0

[Link]  
```

The `[Link]` section is empty; that is probably the reason why there is none of the expected `systemd.log_level=debug` output like [this](https://github.com/systemd/systemd/blob/f6278558da0304ec6b646bb172ce4688c7f162a5/src/udev/net/link-config.c#L507), and why no renaming is happening.

Reading https://www.freedesktop.org/software/systemd/man/systemd.link.html, I am not even sure if it's allowed for `[Link]` to be empty; the systemd docs don't seem to specify what happens in that case.

As an aside, running what's suggested in section **Example 3. Debugging `NamePolicy=` assignments on 21.11 produces:

```
Parsed configuration file /nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/lib/systemd/network/99-default.link
Parsed configuration file /etc/systemd/network/40-eth0.link
Created link configuration context.
ID_NET_DRIVER=igb
eth0: Failed to query name_assign_type: Invalid argument
eth0: Config file /etc/systemd/network/40-eth0.link is applied
eth0: Failed to get ACTION= property: No such file or directory
eth0: Could not apply link configuration, ignoring: No such file or directory
ID_NET_LINK_FILE=/etc/systemd/network/40-eth0.link
```

**I am wondering:**

Shouldn't the generated `40-eth0.link` from that commit contain as default contents systemd's default values, namely:

```
NamePolicy=keep kernel database onboard slot path
MACAddressPolicy=persistent
```

Or was that intentionally not put in?

CC @flokli as author of the original commit
CC @aszlig because you might be interested in this

**Comment by nh2** [comment]
To elaborate a bit further on my specific problem with my Hetzner NixOps machine:

My machine has 2 network interfaces, a 1G (not in use) and a 10G (in use) one.

Nixops Hetzner integration generated into its nixops sqlite database this udev rule:

```
"extraRules": "ACTION==\"add\", SUBSYSTEM==\"net\", ATTR{address}==\"6c:b3:11:08:77:cc\", NAME=\"eth0\"\n"}, ...
```

as well as:

```
{"networking": ... "interfaces": {"eth0": {"ipv4": {"addresses": [...]
```

Because `networking.interfaces.eth0` is defined, that quite-empty `40-eth0.link` is generated (by [this line](https://github.com/NixOS/nixpkgs/commit/822918df4cec0ee14a657efb86a08bf7f457e647#diff-344943ac406571508ecc8d0311e237519c34548ffaf4eba83a15758a1ced65a4R66)):

```
[Match]
OriginalName=eth0

[Link]  
```

---

Now, what's supposed to happen, and what worked in 20.03, is that

1. systemd would rename the 1G interface `eth0 -> enp6s0`
2. The nixops-hetzner-generated udev rule would rename the 10G interface `eth1` -> `eth0` based on the MAC address

But because of `[Link]` being empty, the rename (1) does not happen, so (2) fails with:

```
systemd-udevd[605]: eth1: Failed to rename network interface 3 from 'eth1' to 'eth0': File exists
```

---

Side note, I did notice that the [20.09 changelog](https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-20.09-notable-changes) introduced by that commit says:

> The scripted networking system now uses `.link` files in `/etc/systemd/`network to configure mac address and link MTU, instead of the sometimes buggy network-link-* units, which have been removed. Bringing the interface up has been moved to the beginning of the network-addresses-* unit. Note this doesn't require systemd-networkd - it's udev that parses .link files. *Extra care needs to be taken in the presence of [legacy udev rules](https://wiki.debian.org/NetworkInterfaceNames#THE_.22PERSISTENT_NAMES.22_SCHEME) to rename interfaces*, as MAC Address and MTU defined in these options can only match on the original link name. In such cases, you most likely want to create a 10-*.link file through systemd.network.links and set both name and MAC Address / MTU there. 

I guess

> Extra care needs to be taken in the presence of legacy udev rules to rename interfaces

Is somewhat relevant.

However, I don't think that the changelog gives any hint at the problem in the issue description: It doesn't mention that it would disable persistent renaming at all, which is why I suspect that this was an accident, and is a bug.

---

As another aside (cc @aszlig):

* Nixops-hetzner renaming an interface to `eth0` is evidently a bad idea. When somebody plugs in another card, that name can be taken. It should rename it to a name that Linux and Systemd will not create, like `internet0`, so that there can be no such conflict.
* systemd docs have the same opinion in: https://www.freedesktop.org/software/systemd/man/systemd.link.html#Name=
 ".
  > Note that specifying a name that the kernel might use for another interface (for example `"eth0"`) is dangerous because the name assignment done by udev will race with the assignment done by the kernel, and only one interface may use the name. Depending on the order of operations, either udev or the kernel will win, making the naming unpredictable. It is best to use some different prefix, for example `"internal0"/"external0"` or `"lan0"/"lan1"/"lan3"`.

That part may need to be addressed in nixops-hetzner, perhaps as a combination of:

* Switching from the generated udev `extraRules` for renaming to a `.link` file
* Not using names `eth0` as the target names as suggested.

**Comment by flokli** [comment]
One way to make this more graceful could have been to add the `NamePolicy/MacAddressPolicy` statements at https://github.com/NixOS/nixpkgs/commit/822918df4cec0ee14a657efb86a08bf7f457e647#diff-344943ac406571508ecc8d0311e237519c34548ffaf4eba83a15758a1ced65a4R59 (only for scripted networking).

Back then, we assumed it was cleaner to have people do that migration once, to the more stable predictable network interface names. It has been documented in the release notes, and with this being active since 20.09, there's not really a way to change it after the fact (and breaking people's setups again backwards to reintroduce the old naming scheme).

nixops-hetzner never did the necessary changes in their custom (and error-prone) config. This should be fixed there - either by seting above `NamePolicy/MacAddressPolicy` values by yourself, or update nixops-hetzner to not use the error-prone `eth0` names.

Closing this one, it's not an nixpkgs issue anymore, but a nixops-hetzner bug.
