### ISSUE TITLE
Idris doesn't build because tests fail

### ISSUE THREAD

**Issue by gpyh** [NixOS/nixpkgs#15314]
## Issue description

Idris doesn't compile using nix.
See https://github.com/idris-lang/Idris-dev/issues/3155

### Steps to reproduce

```
nix-env -iA nixos.haskellPackages.idris
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
16.09pre82105.7465bcd (Flounder)
```

* Nix version: (run `nix-env --version`)

```
nix-env (Nix) 1.11.2
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
"16.09pre82105.7465bcd"
```

**Comment by laMudri** [comment]
I believe the problem with this is that the checker never outputs anything, so the tests that expect something (an error message) are the ones that fail.

**Comment by gpyh** [comment]
I thought so, but surprisingly a small number of tests do output something.

**Comment by laMudri** [comment]
The only thing the checker outputs is error messages, so test files that are supposed to check correctly expect no output.

**Comment by ericbmerritt** [comment]
Any thoughts on a work around guys? For various reasons I found I wanted to explore idris. I went to install and got the build problem reported here. :/

**Comment by gpyh** [comment]
Paging @shlevy

**Comment by gpyh** [comment]
I just updated and it seems magically fixed.
Can I have confirmation from you @ericbmerritt so I can close this?

**Comment by laMudri** [comment]
On the most recent `nixos-unstable` (up to [25e3c09](https://github.com/NixOS/nixpkgs-channels/commit/25e3c091a07374f49ff74d0a69a4515715bff43b)), I agree.

**Comment by gpyh** [comment]
Perfect.
