### ISSUE TITLE
gitFull package lacks dependencies for less/ssh

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#15324]
## Issue description
when entering a pure shell featuring gitFull, i expected push to ssh and git diff to work
however both openssh and less where missing from the env and git

## Technical details

* System: nixos-version = 16.03.733.74139a6 (Emu)

**Comment by domenkozar** [comment]
wont fix: https://github.com/NixOS/nixpkgs/pull/14207

**Comment by RonnyPfannschmidt** [comment]
if it cant be included, can there at least be warnings or propepr errors ?

random indirectly used binaries missing for a tool in a pure env is a horrible user experience
