### ISSUE TITLE
libvlc-3.0.16: fails to build on `nixpkgs-unstable`, affects KDE Plasma 5

### ISSUE THREAD

**Issue by azahi** [NixOS/nixpkgs#153284]
### Describe the bug
`libvlc` package fails to build. Breaks building `elisa` and subsequently Plasma 5 if `services.xserver.desktopManager.plasma5` is enabled.

### Steps To Reproduce
1. Checkout `nixpkgs-unstable` of nixpkgs
2. Run `nix build .#libvlc`
3. Encounter an error

### Expected behavior
`libvlc` builds normally.

### Additional context
Full build log:
https://gist.github.com/azahi/fcc77da55dae5384b2360ba49fbe93a1

### Notify maintainers
@NixOS/qt-kde (Affects `elisa` and Plasma 5)
@AndersonTorres (Could be a `libcaca` issue)

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(azahi): `""`
 - nixpkgs: `/nix/store/rfv5vc72q69qb9qzp8qif35pq3a8nfbi-source`
```

**Comment by r-burns** [comment]
This bisects to https://github.com/NixOS/nixpkgs/pull/153140

**Comment by K900** [comment]
Upstream issue: https://code.videolan.org/videolan/vlc/-/issues/26389

**Comment by vcunat** [comment]
Apply the not-yet-merged patch from upstream?  I have no clue about the libcaca changes, but at least the patch looks like trivial renames:
https://code.videolan.org/videolan/vlc/-/merge_requests/889/diffs?commit_id=d35391caa03c046149e7fe2497f51bf59ed8551d

To me that sounds better than reverting the update (though my information is very limited):
> (side note, the beta20 libcaca update fixes several security issues).

**Comment by AndersonTorres** [comment]
Yes. I will do this.
