### ISSUE TITLE
Request: Waterfox

### ISSUE THREAD

**Issue by SnowJuli** [NixOS/nixpkgs#153357]
**Project description**
Waterfox is an open-source browser based on the same principies as Firefox

**Metadata**

* homepage URL: https://www.waterfox.net/
* source URL: https://github.com/WaterfoxCo/Waterfox
* license: MPLv2
* platforms: linux and darwin (not sure about unix)

**Comment by wyndon** [comment]
Might as well package Librewolf instead, which has a better reputation on privacy. Waterfox had (and maybe have) issues concerning privacy : https://spyware.neocities.org/articles/waterfox_classic.html

There's also a pull request for Librewolf here : https://github.com/NixOS/nixpkgs/pull/151439

**Comment by Icey-Glitch** [comment]
The ownership has changed again, it is completely independent. I think this should be re considered

**Comment by andrewzah** [comment]
+1 for waterfox given the ownership changes (https://www.waterfox.net/blog/a-new-chapter-for-waterfox/).

**Comment by JustAlternate** [comment]
Definetly need a waterfox pkgs !

**Comment by labi-le** [comment]
+1

**Comment by JustAlternate** [comment]
https://github.com/NixOS/nixpkgs/pull/388679
