### ISSUE TITLE
falkon: broken due to kwallet [21.11]

### ISSUE THREAD

**Issue by cirno-999** [NixOS/nixpkgs#153394]
### Describe the bug
When trying to run the falkon browser, it doesn't succeed because it has a dependency on kwallet and that particular version is broken.

### Steps To Reproduce
1. Be on Nix channel 21.11
2. run `nix-shell -p falkon`

### Expected behavior
Falkon browser being ready to use in a shell.

### Additional context
```
[cirno@berlin:~/Me/c]$ nix-shell -p falkon
error: Package ‘kwallet-5.87.0’ in /nix/store/rqh37pgg8sg7bhwgh3m4k103p47mhm77-nixos-21.11.334921.8588b14a397/nixos/pkgs/development/libraries/kde-frameworks/default.nix:94 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```
The standard kwallet seems to work.
```
[cirno@berlin:~]$ nix-shell -p libsForQt5.kwallet

[nix-shell:~]$ 
```
### Notify maintainers
@peterhoeg

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixos-21.11.334921.8588b14a397, unstable-22.05pre334855.29d1f6e1f62"`
 - channels(cirno): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by hqurve** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/158777
