### ISSUE TITLE
problem building alacritty

### ISSUE THREAD

**Issue by dbarrosop** [NixOS/nixpkgs#153304]
### Describe the bug

Since this morning alacritty fails to build with the following error:

```
...
test zerowidth ... ok(B
test vim_simple_edit ... ok(B
test history ... ok(B
test vim_large_window_scroll ... ok(B
test vim_24bitcolors_bce ... ok(B
test row_reset ... ok(B

test result: ok(B. 40 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s

   Doc-tests alacritty_config_derive

running 0 tests

test result: ok(B. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests alacritty_terminal

running 1 test
test src/term/mod.rs - term::test::mock_term (line 1885) ... FAILED(B

failures:

---- src/term/mod.rs - term::test::mock_term (line 1885) stdout ----
Couldn't compile the test.

failures:
    src/term/mod.rs - term::test::mock_term (line 1885)

test result: FAILED(B. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.12s

error: test failed, to rerun pass '--doc'
error: builder for '/nix/store/yjzmbna9yga17j3nxw22kkc75i65kq8k-alacritty-0.9.0.drv' failed with exit code 101
```

### Steps To Reproduce

Just run

```
nix-env -f '<nixpkgs>' -iA alacritty
```

### Expected behavior

Alacritty should build succesfully.

### Screenshots

N/A

### Additional context

N/A

### Notify maintainers

@Br1ght0ne @mic92 @ma27
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"

warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
these 2 paths will be fetched (0.34 MiB download, 2.06 MiB unpacked):
  /nix/store/7jxjm2ghxmyswmbz9l69nzq1q09n7v5h-bash-interactive-5.1-p12-doc
  /nix/store/mwbn53zx1q26vn62741icrc8yp2lsfrs-bash-interactive-5.1-p12-dev
copying path '/nix/store/7jxjm2ghxmyswmbz9l69nzq1q09n7v5h-bash-interactive-5.1-p12-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/mwbn53zx1q26vn62741icrc8yp2lsfrs-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs-22.05pre343039.61d24cba728"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs`
```

**Comment by cideM** [comment]
Seems specific to MacOS. I can reproduce this on my M1 machine, not on NixOS. Not sure if it's even specific to `aarch64-darwin` as opposed to `x86_64-darwin`.

**Comment by azuwis** [comment]
It also failed on aarch64-linux https://hydra.nixos.org/build/162176062/nixlog/1/tail

**Comment by hexagonal-sun** [comment]
The list of commits that caused the breakage is [here](https://hydra.nixos.org/api/scmdiff?rev2=ee16e9c9274cdf43d07f5e01c1aef54954f2681e&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git&rev1=dad7a0fd1a1b6ab257ba0b212077324a97dbeaa7&type=git&branch=).  I see that `rustc` was updated, maybe a compiler regression?  I'm currently bisecting to see which commit caused the issue.

**Comment by hexagonal-sun** [comment]
Bisect finished.  Looks like this is a compiler regression:

```
f56f3f7dccb39d31bee9c8f6abb4b225a2b6cd9b is the first bad commit
commit f56f3f7dccb39d31bee9c8f6abb4b225a2b6cd9b
Author: Alyssa Ross <hi@alyssa.is>
Date:   Thu Dec 2 20:35:42 2021 +0000

    rustc: 1.56.1 -> 1.57.0
```
@alyssais Any ideas on what may be causing the issue?

**Comment by meguminloli** [comment]
> Bisect finished. Looks like this is a compiler regression:
> 
> ```
> f56f3f7dccb39d31bee9c8f6abb4b225a2b6cd9b is the first bad commit
> commit f56f3f7dccb39d31bee9c8f6abb4b225a2b6cd9b
> Author: Alyssa Ross <hi@alyssa.is>
> Date:   Thu Dec 2 20:35:42 2021 +0000
> 
>     rustc: 1.56.1 -> 1.57.0
> ```
> 
> @alyssais Any ideas on what may be causing the issue?

It's probably this regression https://github.com/rust-lang/rust/issues/91671 .

**Comment by pnkfelix** [comment]
So far, the main takeaway from my investigation in rust-lang/rust#91671 is that the thing that 1.57.0 did that injected this problem is that it started passing along the LTO (link-time optimzation) flags down into rustdoc generated code. We did not use to do this. But now that we have started, it has started exposing LTO-related issues that were masked before.

I would be curious to know if your problem here is indeed LTO-related. Do you know if you have link-time optimization enabled in alacritty?

**Comment by meguminloli** [comment]
> So far, the main takeaway from my investigation in [rust-lang/rust#91671](https://github.com/rust-lang/rust/issues/91671) is that the thing that 1.57.0 did that injected this problem is that it started passing along the LTO (link-time optimzation) flags down into rustdoc generated code. We did not use to do this. But now that we have started, it has started exposing LTO-related issues that were masked before.
> 
> I would be curious to know if your problem here is indeed LTO-related. Do you know if link-time optimization is enabled in this alacritty build?

I did some research and the v0.9.0 branch of alacritty is built with lto for release. If you test alacritty without LTO on release, it doesn't fail, so the bug is related to LTO on aarch64.

**Comment by lilyball** [comment]
I'm getting this problem with skim. Like alacritty, skim has `lto = true` in its release profile. Commenting that out allows `skim` to compile.

**Comment by breuerfelix** [comment]
is there any workaround instead of using the intel version? i would like to update my system again :D

**Comment by azuwis** [comment]
> is there any workaround instead of using the intel version? i would like to update my system again :D

You can use overlays to disable check:

```
# overlays.nix
[
  (self: super: {
    alacritty = super.alacritty.overrideAttrs (
      o: rec {
        doCheck = false;
      }
    );
  })
]

```
