### ISSUE TITLE
Malformed symbol table linking libiconv-osx

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#15335]
## Issue description

The following error occurs when certain tools try to link to the "libiconv-osx" derivation.

```
ld: malformed mach-o, symbol table not in __LINKEDIT file '/nix/store/fpvaajf5kbwwnrlzs839hbf0x224ha2k-libiconv-osx-10.9.5/lib/libiconv.dylib' for architecture x86_64
```

It looks like the offending part is [pkgs/os-specific/darwin/apple-source-releases/libiconv/default.nix line 10-13](https://github.com/NixOS/nixpkgs/blob/b10659196b14358858c786749824956fac3a889d/pkgs/os-specific/darwin/apple-source-releases/libiconv/default.nix#L10). Pinging @copumpkin to see whether the reexport_library part is still necessary because it looks like the XCode 7.3 update broke it somehow.

### Steps to reproduce

Install ghc and cabal-install.

Run "cabal install old-time". (only occurs on Darwin)

See [issue in stack](https://github.com/commercialhaskell/stack/issues/2044).

**Comment by copumpkin** [comment]
Thanks, I'll try to take a look later this week or possibly this weekend!

**Comment by newhoggy** [comment]
Does this help any?

http://stackoverflow.com/questions/20454327/how-to-re-export-a-dylib-symbol-from-a-dependent-bundle

**Comment by acowley** [comment]
I think this is a gcc/clang issue. In a `--pure` shell, `configure` complains about needing `gcc`. If you run `cabal install old-time --with-gcc=clang` (whether `--pure` or not), then it works.

**Comment by matthewbauer** [comment]
Hmm...

cc @peti

**Comment by dhess** [comment]
I just bumped into this issue as well when using `stack` (but not, oddly, using plain `cabal` on the same package that causes the problem with `stack`).

Is there a work-around, at least?

**Comment by acowley** [comment]
You need to manually pass `--with-gcc=clang` to whatever `Cabal` front-end you are using. The nixpkgs haskell infrastructure already does this.

**Comment by dhess** [comment]
Ahh, I see. I'll try that, thanks.

**Comment by peti** [comment]
Can we close this issue? It sounds like there is not much we (as in: Nix developers) can do abou this, i.e. we cannot control the options passed to `stack`. Am I missing something?

**Comment by robertmassaioli** [comment]
The `--with-gcc=clang` step saved me a lot of debugging time. That worked for me.

**Comment by acowley** [comment]
A note for posterity: You can put a `with-gcc:` field in a `stack.yaml`. I've had success using the `clang` from the darwin `stdenv`.
