### ISSUE TITLE
Gnome Tracker commands only show "usage" message

### ISSUE THREAD

**Issue by dag-h** [NixOS/nixpkgs#153378]
### Describe the bug
Pretty much all `tracker3` commands just show the "usage" output, regardless if the input is correct or not. 

For example, `tracker3 daemon` outputs:
```
usage: tracker3 [--version] [--help]
                <command> [<args>]

Available tracker3 commands are:
   help       Get help on how to use Tracker and any of these commands
   endpoint   Create a SPARQL endpoint
   export     Export data from a Tracker database
   import     Import data into a Tracker database
   sparql     Query and update the index using SPARQL or search, list and tree the ontology
   sql        Query the database at the lowest level using SQL

Additional / third party commands are:
   endpoint   
   export   
   help   
   import   
   sparql   
   sql   

See “tracker3 help <command>” to read about a specific subcommand.
```

### Steps To Reproduce
1. Run `tracker3 daemon`, `tracker3 index --add my-music-folder`, `tracker3 info my-file`, and many other `tracker3`commands
2. Observe incorrect output

### Expected behavior
I expect to see the correct output, for example `tracker3 daemon` should show the current status of all miners.

### Notify maintainers
@jtojnar, @hedning, @dasj19, @maxeaubrey 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
How did you determine the commands? The printed help page does not list any of those as supported.

**Comment by dag-h** [comment]
@jtojnar I got the commands from the Tracker documentation: https://gnome.pages.gitlab.gnome.org/tracker/docs/commandline/

You are right that they aren't listed in the help page. I do have manuals with usage for all those commands installed though.
