### ISSUE TITLE
Pretix

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#153495]
**Project description**
Ticket shop application for conferences, festivals, concerts, tech events, shows, exhibitions, workshops, barcamps, etc. 

**Metadata**

* homepage URL: https://pretix.eu/
* source URL: https://github.com/pretix/pretix/
* license: AGPLv3 (with specials)
* platforms: unix, linux, darwin

**Comment by n0emis** [comment]
There is a nix flake, which mostly works for this: https://github.com/n0emis/pretix-nix/tree/update-4.6.0

**Comment by lukasstevens** [comment]
I would also be really happy to have this :+1:

**Comment by pinpox** [comment]
+1 on this. The flake seems to be outdated

**Comment by e1mo** [comment]
Pretix was added in #296180 :partying_face:
