### ISSUE TITLE
Kavita comics/manga reader

### ISSUE THREAD

**Issue by amaumene** [NixOS/nixpkgs#153429]
**Project description**
Lighting fast with a slick design, Kavita is a rocket fueled self-hosted digital library which supports a vast array of file formats. Install to start reading and share your server with your friends.

**Metadata**

* homepage URL: https://www.kavitareader.com
* source URL: https://github.com/Kareadita/Kavita
* license: gpl3
* platforms: linux

**Comment by abathur** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/147923. Closing in favor of that one.
