### ISSUE TITLE
services.kresd.listenPlain says it supports ListenStream syntax from systemd.socket but doesn't

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#153485]
### Describe the bug

> Name: services.kresd.listenPlain
> Description: What addresses and ports the server should listen on. For detailed syntax see ListenStream in man systemd.socket.

However, the following input is is rejected as "services.kresd.*: incorrect address specification":

```
services.kresd.listenPlain = [ "[fe80::1]:53%ofborg" ] 
``` 

### Expected behavior

I expected kresd to listen on fe80::1 on port 53 on the ofborg interface, as the documentation suggests should be possible.

I don't mind that it is impossible, but the documentation for this option isn't correct anymore.

### Notify maintainers

@vcunat 

nixos-unstable-small, rev 18c84ea816348e2a098390101b92d1e39a9dbd45

**Comment by vcunat** [comment]
Well, it no longer uses systemd sockets anymore, and instead there are a few in-nix regexps that converts them.  It might not be perfect.

Either way, the inteface spec should surely be part of the IPv6 already, i.e. `"[fe80::1%ofborg]:53"` &ndash; and I think that should work (the generated config looks OK).

**Comment by vcunat** [comment]
Ah, I see that systemd is weird here, at least in docs.  So I don't know.  Either shuffle it in the in-nix regexps or document as a deviation, I suppose.
