### ISSUE TITLE
webkitgtk: broken on i686

### ISSUE THREAD

**Issue by vvs-** [NixOS/nixpkgs#153528]
### Describe the bug
I think it should be marked as broken to avoid frustrating other people. This package is impossible to build without more than 4G address space due to linker memory exhaustion. It can be built only on 64-bit hosts (the same as Firefox).

And that permanently breaks Gnome 3 on i686. It was possible to build it in the past using local modifications, though.

**Comment by malbarbo** [comment]
@vvs- what modifications did you used in the past?

**Comment by vvs-** [comment]
Only very few to some Gnome dependencies just to build Gnome itself, like `doCheck = false`.

AFAIK, there were no modifications at all to webkitgtk. It just required huge swap and to free as much RAM as possible, e.g. running nix-build with only one thread.

Last December I've tried to install NixOS 21.11 and it was impossible to build because of a linker exhausting all memory address space. I've tried both ld and gold. My investigations into other Linux distros revealed that they used cross-compiling tricks to build 32-bit webkitgtk on 64-bit host. I've spent a week before giving up. Right now I'm using only x86_64 arch because of that issue. I suppose it's impossible to fix on native 32-bit host just like Firefox.

**Comment by malbarbo** [comment]
I tried different configurations and was able to complete the building without any memory issue by setting separateDebugInfo to false.

**Comment by malbarbo** [comment]
I will now try to build firefox.

**Comment by vvs-** [comment]
> I tried different configurations and was able to complete the building without any memory issue by setting separateDebugInfo to false.

Interesting. Thanks for trying this. It was very painful to experiment with different configurations as it required too many hours to build on my computer.

AFAIK, Firefox had a different issue which didn't involve linker. It was probably a compiler.

Do you think it's sustainable? I mean, will it still be possible to build next year? Because a year ago it didn't require that trick either. I'm quite pessimistic about browsers on 32-bit architecture as is already evident from Firefox :( Also, there were similar troubles with Haskell (Pandoc) and Qt. Considering that Hydra doesn't have most 32-bit software in a binary cache and that it's often required to set `doCheck=false` in order to build it, it's really a huge pain to install NixOS on i686 arch.

**Comment by puffnfresh** [comment]
`webkitgtk.overrideAttrs (attrs: { separateDebugInfo = false; })` works great for me. Should add a `stdenv.is32bit` conditional for this derivation?
