### ISSUE TITLE
Something happened since 32b7b0009 that made my graphics awefully slow

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#15352]
## Issue description

My channel generation 60 is 32b7b0009f168cb7e020d297c2f336ef352e9ec1.
My latest channel update resulted in channel generation 62, which is 7465bcd67a2177c63adeec66398b1b581260b31e.

Something happened in between that made my `ati_unfree` graphics awefully slow. I tried to switch to the open source driver by converting:

```nix
services.xserver.videoDrivers = [ "ati_unfree" ];
```

into

```nix
services.xserver.videoDrivers = [ "amd-non-free" ];
```

but it didn't work (x-server crashed without logging anything useful). I tried

```nix
services.xserver = {
  videoDrivers = [ "ati" ];
  useGlamor = false;
  deviceSection = ''Option "NoAccel" "true"'';
};
```

(someone in IRC mentioned this) as well, but it didn't help.

This was both tested on kernel 4.1 and 4.5.

---

Either way: The above switch to `amd-non-free` was tested on a seperate branch. I then switched back to my master branch where I didn't alter any graphic-related configuration since channel generation 60 and re-build my system after two channel updates. Something in these updates broke the graphics driver and I have awefully slow graphics now (I can almost see how the bash writes the lines) and an awefully high CPU load (I assume it falls back to CPU rendering).

### Steps to reproduce

I don't really see a way to reproduce this besides me sharing my whole `configuration.nix` and my desktop machine. Though I'm more than happy helping debugging this (FYI: I'm on vacation from 12.05. until 22.05).

## Technical details

* System: 16.09pre79453.32b7b00 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre82105.7465bcd"

---

Until these things are solved, I have to boot into an older generation or reset my channel when rebuilding, I asume?

**Comment by matthiasbeyer** [comment]
`git diff 32b7b0009f168cb7e020d297c2f336ef352e9ec1..7465bcd67a2177c63adeec66398b1b581260b31e -- pkgs/os-specific/linux/ati-drivers/default.nix`

tells me that there is a diff in `nixpkgs/os-specific/linux/ati-drivers/default.nix`, but it doesn't look that suspicious.

Here are the commits which changed things in this file:

* 5d52f5542604fad210a1b16484f31d2f8bb5ed39
* 40ef23e7ed521abb7161dde01806ca62c9ed25ba
* 5a6a8213ebefade42f08bfba9ec94652631e0eb1
* 474f921bacefadaa7f123f7531adfa86062f4b0d
* 1894615f64502d66c2f5c4ad85e8ee50ee75cbf7
* ae74c356d94b795eb07dfe9978788b49b70f5959

(via `git log 32b7b0009f168cb7e020d297c2f336ef352e9ec1..7465bcd67a2177c63adeec66398b1b581260b31e -- pkgs/os-specific/linux/ati-drivers/default.nix`)

---

pinging the contributors from the commits listed above. @vcunat @dezgeg

**Comment by matthiasbeyer** [comment]
From the journal on x server from the boot of the latest generation which has awefully slow graphics:

```
Mai 10 12:25:10 lucy display-manager-start[911]: X.Org X Server 1.17.4
Mai 10 12:25:10 lucy display-manager-start[911]: Release Date: 2015-10-28
Mai 10 12:25:10 lucy display-manager-start[911]: X Protocol Version 11, Revision 0
Mai 10 12:25:10 lucy display-manager-start[911]: Build Operating System: Linux 3.14.58 x86_64
Mai 10 12:25:10 lucy display-manager-start[911]: Current Operating System: Linux lucy 4.1.20 #1-NixOS SMP Thu Mar 17 18:11:03 UTC 2016 x86_64
```

**Comment by dezgeg** [comment]
The latter is just one of the multiple-outputs merges, so it doesn't really tell anything new. Might be useful to try to collaborate with others who have the same problem(s): https://github.com/NixOS/nixpkgs/pull/15207

**Comment by edwtjo** [comment]
@matthiasbeyer the multiple-outputs breakage should be fixed as of 046ee5ac3ffbc7e5daa706bd3ad405bd30c7aad5 please try from that commit

**Comment by matthiasbeyer** [comment]
@edwtjo I'm going on vacation this evening and I'll be back on 22th/23th. I will try then. Thank you for your support!

**Comment by edwtjo** [comment]
No problem! You weren't alone stuck with gawd awful slow graphics :)

**Comment by matthiasbeyer** [comment]
I switched to `ati` instead of `ati_unfree` with the latest channel release and everything seems to work now. I guess I close this for now and open another issue if something breaks...
