### ISSUE TITLE
[Request] Burn my Windows

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#153575]
**Project description**
This is a Gnome addon that adds special effects to gnome, similar to Compiz back in the day.

**Metadata**

* homepage URL: https://github.com/Schneegans/Burn-My-Windows
* source URL: https://github.com/Schneegans/Burn-My-Windows
* license: gpl3+
* platforms: Linux

**Comment by maydayv7** [comment]
This has already been packaged automatically and is available from 1eb38afcb425e212496cedc8a65702d90c72b741, you can use the [`nixos-unstable`](https://github.com/NixOS/nixpkgs/tree/nixos-unstable) branch to install the extension
