### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#153577]
**Project description**
_describe the project a little_

Stats is a macOS app that displays system statistics such as CPU usage or power draw in the menu bar

**Metadata**

* homepage URL: https://github.com/exelban/stats
* source URL: https://github.com/exelban/stats
* license: mit
* platforms: darwin

**Comment by PartemImperium** [comment]
@Atemu 
I was looking into getting stats in nix as well. I haven't made any nix packages from source yet so I don't know how much help I could be in that front but usually when I want to manage an app through nix and it doesn't exist yet I add it in an overlay package that just downloads the bin to get something working. I have a working overlay that downloads their release in nix in my dotfiles (https://github.com/PartemImperium/dotfiles/blob/5b445f00db03bf2cc0c0bfdf7945b1134a436bab/dot_config/nixpkgs/overlays/stats.nix). If you put that file in ~/.config/nixpkgs/overlays it will be available as pkgs.stats.

Side note whenever I get to building from source I plan on making a PR (if it doesnt exist by then). But I don't know when I will get to figuring out how to build swift apps from source within nix. If there are any good examples someone could point me to I could take a stab at it.

**Comment by Atemu** [comment]
A -bin package like you did it is also fine for inclusion into Nixpkgs.

**Comment by PartemImperium** [comment]
I though doing bin packages was for when the source code is not available. In this case the source code is available I just don't know how to build it within nix as I haven't done that yet (and haven't found a good guide for building swift/objective c apps for darwin).

**Comment by Atemu** [comment]
IMO: Source package > Bin package > No package

**Comment by emilytrau** [comment]
Has been added
