### ISSUE TITLE
`nix-store --optimize` and `nixos-rebuild switch` fail with missing `mobile-broadband-provider-info`

### ISSUE THREAD

**Issue by wbadart** [NixOS/nixpkgs#153532]
### Describe the bug
Both `nix-store --optimize` and `nixos-rebuild switch` error out with `error: getting status of '/nix/store/...-mobile-broadband-provider-info-20210805': No such file or directory`

```console
$ nix-store --optimize
error: getting status of '/nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805': No such file or directory
$ nixos-rebuild switch
building Nix...
building the system configuration...
[...]
created 515 symlinks in user environment
error: getting status of '/nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805': No such file or directory
```

Using the `--show-trace` flag with `nixos-rebuild switch` doesn't show any additional information.

It seems the system does have some version of `mobile-broadband-provider-info`, but it doesn't share a hash with the version the above commands seem to expect:

```console
$ ls /nix/store/*mobile-broadband-provider-info*
/nix/store/as3fij7mchpgh8hdwhddf5pgl3xqxbd2-mobile-broadband-provider-info-20210805.drv
/nix/store/fg561mm2rj2lydqfysingfcqbiafp2h9-mobile-broadband-provider-info-20210805.tar.xz.drv
/nix/store/kyfhq50plb5sl17b313g0rw6jlc3pjdb-mobile-broadband-provider-info-20210805.tar.xz.drv
/nix/store/v9sb8gc22rk883sz1fzfxqn9s3fbh921-mobile-broadband-provider-info-20210805.drv

/nix/store/xfz696smzazzgfj2k0qaasqkhgmz62w4-mobile-broadband-provider-info-20210805:
share
```

I'm at a bit of a loss as to what the underlying issue could be, and am especially confused that both `nix-store` and `nixos-rebuild` are affected by it.

### Steps To Reproduce
I don't have an exact procedure, nor a specific tweak to my system configuration that seemed to trigger the error. It's just that a recent`nixos-rebuild switch --upgrade` (within the last week or two) failed as described above, as have all subsequent runs of the command. The exact configuration I'm attempting to build can be found at https://github.com/wbadart/dotfiles/blob/slim-down/configuration.nix

### Expected behavior
I expect the commands to succeed. `nixos-rebuild` in particular looks like it's about to (it reports creating the symlinks) but then crashes at the last second.

### Screenshots
n/a; see command output above

### Additional context
n/a

### Notify maintainers
n/a

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(will): `""`
 - channels(root): `"home-manager, nixos-22.05pre343321.78cd22c1b86"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Thanks in advance for your consideration!

**Comment by wbadart** [comment]
A little extra detail, I'm running on a Lenovo ThinkPad T470 without mobile/LTE capabilities. Here are the details about the wireless adapter from `lshw`:

```
           *-network
                description: Wireless interface
                physical id: 0
                bus info: pci@0000:04:00.0
                logical name: wlp4s0
                version: 78
                serial: 88:b1:11:bd:2a:c2
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=iwlwifi driverversion=5.10.81 firmware=36.ca7b901d.0 8265-36.ucode ip=192.168.0.7 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                resources: irq:132 memory:ec100000-ec101fff
```

**Comment by veprbl** [comment]
Can you try
```
nix-store --verify-path /nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805
nix-store --repair-path /nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805
```

**Comment by wbadart** [comment]
```console
# nix-store --verify-path /nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805
path '/nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805' was modified! expected hash 'sha256:1w9k5nz7dl4zxbi9mciwhawyrpd39gli3agc4hwj2hrzjmmrryza', got 'sha256:18ixg1ggwlhb88h7bifvmchai9bk3xcbk4mr73jvxhh89r136zil'

# nix-store --repair-path /nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805
copying path '/nix/store/647cb96gp8mvbbrqpdnzqqxpqgz5lmrr-mobile-broadband-provider-info-20210805' from 'https://cache.nixos.org'...
```

Looks like that did the trick; `nixos-rebuild switch` succeeded after running the above. Thanks for the tip! I wonder how I got into that bad state in the first place...
