### ISSUE TITLE
Maui Shell: convergent shell for desktops, tablets, and phones.

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#153657]
**Project description**
Maui Shell is a convergent shell for desktops, tablets, and phones.

**Metadata**

* homepage URL: https://nxos.org/english/nxd/
* source URL: https://github.com/Nitrux/maui-shell
* license: lgpl3
* platforms: linux

**Comment by onny** [comment]
Maui Shell is packaged https://github.com/NixOS/nixpkgs/pull/205800

Modules for configuring and enable it are still missing. Since maui-shell is a relatively new project, I'm fine leaving it as it is and working further on it while upstream releases new versions :)
