### ISSUE TITLE
Mobilizon

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#153697]
**Project description**
Gather, organize and mobilize yourselves with a convivial, ethical, and emancipating tool.

**Metadata**

* homepage URL: https://joinmobilizon.org
* source URL: https://framagit.org/framasoft/mobilizon/
* license: agpl3
* platforms: unix, linux, darwin,

**Comment by tournemire** [comment]
There is a work-in-progress PR: #119132.
