### ISSUE TITLE
ddclient does not build/install

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#15374]
## Issue description
ddclient fails to build/install.

### Steps to reproduce
/etc/nixos/configuration.nix:
`services.ddclient.enable = true;
`

## Technical details

* System: 16.09pre82105.7465bcd (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre82105.7465bcd"

**Comment by dezgeg** [comment]
At least the build is fixed on master.

**Comment by bjornfor** [comment]
ddclient builds OK, and ```services.ddclient.enable = true``` enables the service (and the services doesn't enter "failed" state) on both master (b11186a6369106d712149522c8a2f18ca5811cf6) and release-16.03 (0f9e365e0f7d3c12626d3e733d87a28a12567b71).

Please re-open of the issue appears again.

**Comment by d4g** [comment]
Seems to be fixed. Thanks.
