### ISSUE TITLE
Can't reproduce hydra failure for backintime-qt4

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#15379]
Hydra [fails to build backintime-qt4](https://hydra.nixos.org/build/35442715) and I can't reproduce it:

```shellCommands
$ bash <(curl https://hydra.nixos.org/build/35442715/reproduce)
[...]
/nix/store/0bwsc7axzx4f6spw60rbip06lfdqawn9-backintime-qt4-1.1.12
$ echo $?
0
```

* System: (NixOS: `16.09.git.94ee1b7)
* Nix version: 1.11.2
* Nixpkgs version: 16.09.git.94ee1b7

**Comment by domenkozar** [comment]
Blocker is for NixOS releases.

**Comment by DamienCassou** [comment]
I think it got fixed magically.
