### ISSUE TITLE
fetchCargoTarball fails with “gzip: Cannot exec: No such file or directory”

### ISSUE THREAD

**Issue by ruuda** [NixOS/nixpkgs#153774]
### Describe the bug

If I try to build a `buildRustProject` where the vendored dependencies are not available on cache.nixos.org, building them on my machine fails in the `installPhase` of `fetchCargoTarball`:

```
       > installing
       > tar (child): gzip: Cannot exec: No such file or directory
       > tar (child): Error is not recoverable: exiting now
       > tar: /nix/store/q1dy07and8y7g28hlnm64yf5mmmm8rim-solana-testnet-cli-1.9.2-vendor.tar.gz: Cannot write: Broken pipe
       > tar: Child returned status 2
       > tar: Error is not recoverable: exiting now
       For full logs, run 'nix log /nix/store/v7213glm17dbg8n925n5062dkssavkx5-solana-testnet-cli-1.9.2-vendor.tar.gz.drv'.
```

It is this command that fails: https://github.com/NixOS/nixpkgs/blob/952aa6f820ce6ec717425c54b5817c81aac279c5/pkgs/build-support/rust/fetch-cargo-tarball/default.nix#L75-L79

Changing `-czf` to `-cf` makes the problem go away, so the problem is really related to `gzip`. I also confirmed by adding a `stat $name` that the input directory exists.

I tried adding `gzip` to `nativeBuildInputs` of the `${name}-vendor.tar.gz` derivation, but that did not help either.

### Steps To Reproduce

For me it reproduces consistently so far with two different Rust packages. For example:
1. Open `pkgs/tools/text/ripgrep/default.nix`.
2. Add `cargoDepsName = "foo";` to ensure that you build the vendored dependencies instead of getting them from a cache.
3. Build `pkgs.ripgrep`.

But if these derivations did get built for cache.nixos.org in the first place, then probably it is not reproducibly broken? Could something from my system be interfering?

### Expected behavior
The derivation is built.

### Notify maintainers

@bhipple you seem to know a lot about `fetchCargoTarball`, do you have any clue how to debug this further?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10-arch1-1, Arch Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `/home/ruud/repos/nixpkgs`
```

**Comment by ruuda** [comment]
I tried on a different machine, and there I can build the derivation just fine, so it must be some kind of impurity.

**Comment by veprbl** [comment]
Try `nix-store --verify`

**Comment by bhipple** [comment]
That is really strange.  I can't see any reason why gzip would cause this type of failure.

**Comment by bhipple** [comment]
That is really strange.  I can't see any reason why gzip would cause this type of failure.

**Comment by ruuda** [comment]
> Try `nix-store --verify`

This didn’t find anything. I also tried with `--check-contents`, it also found nothing.

**Comment by veprbl** [comment]
Could you let replace "tar" with "strace -f tar" ?

**Comment by ruuda** [comment]
Great idea! I think this is the relevant part:

```
[pid    28] creat("/nix/store/5jkq3247rn48ihfwanbrpl4g49mxmzr8-foo-vendor.tar.gz", 0666 <unfinished ...>
[pid    27] <... getdents64 resumed>0x483e20 /* 60 entries */, 32768) = 1896
[pid    27] getdents64(3, 0x483e20 /* 0 entries */, 32768) = 0
[pid    28] <... creat resumed>)        = 3
[pid    27] newfstatat(3, ".cargo",  <unfinished ...>
[pid    28] close(1 <unfinished ...>
[pid    27] <... newfstatat resumed>{st_mode=S_IFDIR|0755, st_size=60, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid    28] <... close resumed>)        = 0
[pid    27] openat(3, ".cargo", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC <unfinished ...>
[pid    28] dup(3 <unfinished ...>
[pid    27] <... openat resumed>)       = 5
[pid    28] <... dup resumed>)          = 1
[pid    27] newfstatat(5, "",  <unfinished ...>
[pid    28] close(3 <unfinished ...>
[pid    27] <... newfstatat resumed>{st_mode=S_IFDIR|0755, st_size=60, ...}, AT_EMPTY_PATH) = 0
[pid    28] <... close resumed>)        = 0
[pid    27] newfstatat(5, "",  <unfinished ...>
[pid    28] execve("/bin/sh", ["/bin/sh", "-c", "gzip"], 0x7fffffffd190 /* 85 vars */ <unfinished ...>
[pid    27] <... newfstatat resumed>{st_mode=S_IFDIR|0755, st_size=60, ...}, AT_EMPTY_PATH) = 0
[pid    27] fcntl(5, F_GETFL)           = 0x28800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW)
[pid    27] fcntl(5, F_SETFD, FD_CLOEXEC) = 0
[pid    27] getdents64(5, 0x48c5b0 /* 3 entries */, 32768) = 80
[pid    28] <... execve resumed>)       = -1 ENOENT (No such file or directory)
[pid    27] getdents64(5, 0x48c5b0 /* 0 entries */, 32768) = 0
[pid    27] newfstatat(5, "config",  <unfinished ...>
[pid    28] write(2, "tar (child): ", 13 <unfinished ...>
tar (child): [pid    27] <... newfstatat resumed>{st_mode=S_IFREG|0755, st_size=113, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid    28] <... write resumed>)        = 13
[pid    27] openat(5, "config", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC <unfinished ...>
[pid    28] write(2, "gzip: Cannot exec", 17 <unfinished ...>
gzip: Cannot exec[pid    27] <... openat resumed>)       = 6
[pid    28] <... write resumed>)        = 17
[pid    27] newfstatat(6, "", {st_mode=S_IFREG|0755, st_size=113, ...}, AT_EMPTY_PATH) = 0
[pid    28] write(2, ": No such file or directory", 27 <unfinished ...>
: No such file or directory[pid    27] read(6,  <unfinished ...>
```
So it’s exec'ing `/bin/sh -c gzip`. That works fine when I run it in my normal terminal. I tried adding `/bin/sh -c gzip` before the `tar` to confirm that that is the issue, then it prints:

```
/nix/store/lwcfw5vyjlzrs35k1hanv21j1q2s5c5w-stdenv-linux/setup: line 1352: /bin/sh: No such file or directory
```

Is `gzip` the issue? Can it actually find `/bin/sh`? I tried adding `/bin/sh -c "echo hi"` and that fails as well. So it’s failing to start `/bin/sh`. What _is_ `/bin/sh` actually? On my system it’s a symbolic link to the relative path `bash`, and `/bin` is a symbolic link to `/usr/bin`.

Does it work if I make it run `/usr/bin/sh` instead of `/bin/sh`?

```
> /nix/store/lwcfw5vyjlzrs35k1hanv21j1q2s5c5w-stdenv-linux/setup: line 1352: /usr/bin/sh: No such file or directory
```

Nope ... is this because of sandboxing? I edited my `/etc/nix/nix.conf`, and sure enough, if I add `sandbox = false` there, then suddenly I _can_ run `/bin/sh`.

So the issue seems to be that `tar` calls `/bin/sh` and that’s not allowed with sandboxing enabled. I’m not sure if this is intended or not, but it looks like that is working well, and there’s a clear way to work around it: instead of running `tar -z`, manually pipe the output through `gzip`. That fixes the issue for me and doesn’t change the output hash. I’ll make a pull request for that.

**Comment by veprbl** [comment]
Can you share contents of your `nix --experimental-features nix-command show-config | grep sandbox-paths`?

**Comment by ruuda** [comment]
> Can you share contents of your `nix --experimental-features nix-command show-config | grep sandbox-paths`?

It shows

```
sandbox-paths = /bin/sh=/nix/store/hf35v6q12njd5izn5qsd85r67rc6c78q-busybox-static-x86_64-unknown-linux-musl-1.34.1/bin/busybox
```

but I now realize, this is not the relevant part, because even though `nix` may be using the right path, `nix-daemon` is not! It turns out, I should use a `nix-daemon` from the Nix store and not from my distribution package, see also https://github.com/NixOS/nixpkgs/pull/154030#issuecomment-1009295290. So this is really a bug in my distribution’s Nix package and not in Nixpkgs itself.

Mystery solved, thanks for your help everybody!
