### ISSUE TITLE
integer-simple does not exist for >= GHC 9.0

### ISSUE THREAD

**Issue by cocreature** [NixOS/nixpkgs#153742]
### Describe the bug

Nix provides `integer-simple` distributions for all versions. However, for GHC 9.0 integer-simple does not exist anymore. Instead it is replaced by `ghc-bignum`.

Currently the integer-simple distributions for GHC 9.0 in nixpkgs build and run but they are actually gmp distributions. 

### Steps To Reproduce

```
nix-shell -p "haskell.packages.integer-simple.ghc902.ghcWithPackages (pkgs: [])" --command "ghc-pkg list | grep gmp"
    integer-gmp-1.1
```
### Expected behavior

integer-simple distributions for GHC 9.0 and newer are replaced by distributions using the native GHC bignum backend. Note that this is configured using a different flag. A crude but working attempt which still uses the `integer-simple` infrastructure but changes the flag is the following but I expect we probably want a different attribute and flag:
```
-    INTEGER_LIBRARY = ${if enableIntegerSimple then "integer-simple" else "integer-gmp"}
+    BIGNUM_BACKEND = ${if enableIntegerSimple then "native" else "gmp"}
```

### Notify maintainers
@guibou @cdepillabout @expipiplus1 @maralorn @sternenseemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-91-generic, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(moritz): `"nixpkgs-22.05pre334669.f366af7a1b3, nixpkgs-unstable-22.05pre334669.f366af7a1b3"`
 - nixpkgs: `/home/moritz/.nix-defexpr/channels/nixpkgs`

```

**Comment by sternenseemann** [comment]
The `ghcHEAD` derivation has the necessary code for `ghc-bignum` already, it's just a matter of porting the changes back to 9.0 and 9.2. I missed this and thought the switch would be for 9.4 for some reason, thanks for the report.
