### ISSUE TITLE
python3Packages.cairocffi: segmentation fault on aarch64-darwin

### ISSUE THREAD

**Issue by PartemImperium** [NixOS/nixpkgs#153783]
### Describe the bug
cairosvg does not build on a m1 mac.

### Steps To Reproduce
1. Add python39Packages.cairosvg to home-manager or any method of building a nix package

### Expected behavior
The app builds and can be run.

### Additional context
If I install have it build as "x86_64-darwin" it builds just fine and works. It is just aarch64-darwin that does not work.

Below is part of the build output when the error starts.

platform darwin -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /nix/store/7l8c4hl7jykb44yay3m9x1zsgp159fig-python3.9-cairocffi-1.2.0/lib/python3.9/site-packages
collected 52 items / 1 skipped / 51 selected                                   

../../../../nix/store/7l8c4hl7jykb44yay3m9x1zsgp159fig-python3.9-cairocffi-1.2.0/lib/python3.9/site-packages/cairocffi/test_cairo.py . [  1%]
.FF...FF..FFFFFFFFFFF......FF................                            [ 88%]
../../../../nix/store/7l8c4hl7jykb44yay3m9x1zsgp159fig-python3.9-cairocffi-1.2.0/lib/python3.9/site-packages/cairocffi/test_numpy.py F [ 90%]
                                                                         [ 90%]
../../../../nix/store/7l8c4hl7jykb44yay3m9x1zsgp159fig-python3.9-cairocffi-1.2.0/lib/python3.9/site-packages/cairocffi/test_pixbuf.py Fatal Python error: Segmentation fault

### Notify maintainers
@SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(myUser): `"darwin, home-manager, nixpkgs-22.05pre340506.5c37ad87222"`
 - channels(root): `"darwin, home-manager, nixpkgs-22.05pre335173.56cbe42f166"`
 - nixpkgs: `/Users/myUser/.nix-defexpr/channels/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
The segmentation fault happens in cairocffi, not cairosvg.

**Comment by SuperSandro2000** [comment]
I am going to adopt cairocffi and update it to 1.3.0 but I don't know if this fixes it. Maybe with the help of ofborg I can fix it otherwise I will mark it as broken.
