### ISSUE TITLE
texlive-new tikz packages fail to build

### ISSUE THREAD

**Issue by exi** [NixOS/nixpkgs#15381]
## Issue description
The tikz-* family of packages in texlive-new fails to build because the hashes of the existing archives changed.

@vcunat

### Steps to reproduce
Add this to you systemPackages:
(pkgs.texlive.combine { inherit (texlive) scheme-basic moderncv etoolbox xcolor cm-super ec l3packages l3kernel microtype babel-german tikz-qtree; })
Try to install.

Error is:
output path ‘/nix/store/18f25dwj59hi8x3gw69gqwbfp8fpwj74-tikz-qtree.tar.xz’ has md5 hash ‘9f96fbc60291500af9c9116202245e7d’ when ‘1329ed27a685ab643f6f10c04dedfbfb’ was expected

## Technical details

* System: (NixOS: 16.09pre82105.7465bcd (Flounder))
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre82105.7465bcd

**Comment by vcunat** [comment]
Many of our texlive packages have no working mirror anymore. Details on https://github.com/NixOS/nixpkgs/issues/10026#issuecomment-207384934 and below
