### ISSUE TITLE
Packaging request: nodenv

### ISSUE THREAD

**Issue by mkobayashime** [NixOS/nixpkgs#153845]
**Project description**

nodenv is one of Node.js version managers. I know you can manege Node.js with Nix itself, but majority of people in the frontend world assume everyone uses Node.js version managers which respect files like `.nvmrc` or `.node-version`, so you have to use them when you're working with them.

**Metadata**

* homepage URL: https://github.com/nodenv/nodenv
* source URL: https://github.com/nodenv/nodenv
* license: MIT
* platforms: I'm not sure actually, but it's distributed as a homebrew formula

**Comment by Alexnortung** [comment]
Hello, please check the merged pull request for notes on the package. The package works, but might need some changes or be extended to work better in the future.

**Comment by mkobayashime** [comment]
@Alexnortung Wow, thanks a lot for your help!
