### ISSUE TITLE
audit prevents gnome control center and online accounts from working

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#15380]
log: [audit-dmesg.log.txt](https://github.com/NixOS/nixpkgs/files/258739/audit-dmesg.log.txt)
## Issue description

gnome online accounts no longer adds existing accounts (token is stored tho)
gnome control center lo longer starts
## Technical details

```
$ nixos-version
16.03.759.b10f61b (Emu)
```

**Comment by dezgeg** [comment]
Does disabling audit really make it work? I think it's just being a messenger here and telling you it crashed for some reason.

**Comment by RonnyPfannschmidt** [comment]
it seems that the online accounts package crashes - the strange bit is, if i run the online accounts thing one, afterwards gnome control center is broken

im not sure how to proceed

**Comment by RonnyPfannschmidt** [comment]
(note that there is no crash indication on the ux

* i start the online account app
* i press add
* i add my google account
* i press the allow in the form
* afterwards i see the online account list without my google account

i did the same in a fedora vm and it worked

**Comment by RonnyPfannschmidt** [comment]
fixed on unstable
