### ISSUE TITLE
Kitty: No "shell-integration" folder in package

### ISSUE THREAD

**Issue by houstdav000** [NixOS/nixpkgs#153810]
### Describe the bug
When building Kitty in nixpkgs, the "shell-integration" folder does not get copied into the output. As such, I cannot source the script to enable certain key-combinations as described on <https://sw.kovidgoyal.net/kitty/shell-integration/#shell-integration>.

### Steps To Reproduce
1. build the Kitty package
2. run `find ./result -name '*shell*'`
3. note there isn't any such output.

### Expected behavior
The "shell-integration" folder and its children should be copied from the source into the package.

### Notify maintainers
@tex @rvolosatovs @Luflosi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `"nixos-22.05pre338278.b0bf5f888d3"`
 - nixpkgs: `/nix/store/k6gcnpmwjmmmkrb8y8vzj47hmhra2g5h-source`
```

**Comment by Luflosi** [comment]
kitty in Nixpkgs is still at version 0.23.1, which does not support the shell integration feature and therefore does not contain such a folder.
When it is updated to > 0.24 and this is still broken, please report here again.

**Comment by jyooru** [comment]
#153928

**Comment by Luflosi** [comment]
Also see #153999.
