### ISSUE TITLE
Opencl regression: `OCL_ICD_VENDORS` not setup anymore?

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#153865]
### Describe the bug
As discussed here, it seems that since "recently" (I noticed that regression a few months ago, and I'm pretty sure that around one or two years ago it was working) opencl's environment variable is not properly configured when using `  hardware.opengl.extraPackages = with pkgs; [ intel-ocl ];`:
```
[nix-shell:~]$ clinfo
Number of platforms                               0

[nix-shell:~]$ OCL_ICD_VENDORS=/run/opengl-driver/etc/OpenCL/vendors clinfo
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL
[...]
```

Also, I'm not sure why but my opengl GPU is not recognized while ubuntu can see it...  But guess it's a different problem.

### Steps To Reproduce
1. Just add `  hardware.opengl.extraPackages = with pkgs; [ intel-ocl ];`
2. Check that the `OCL_ICD_VENDORS` environment variable is empty and that `clinfo` reports no opencl material.

### Expected behavior
I expect opencl to just work when properly installed.

### Notify maintainers
Sorry, I'm not sure who to notify... I just picked random people that modified the module, congrats you are the chosen ones ;-)

@jonringer @Infinisil @vcunat

**Comment by vcunat** [comment]
I can't say I know OpenCL stuff.  Maybe make the NixOS module create a symlink from `/etc/OpenCL` to `/run/opengl-driver/etc/OpenCL` would help?

**Comment by tobiasBora** [comment]
Oh sorry... Do you know who I may ping for opencl issues? (I'm going to report another issue)

Concerning your fix, I have no idea. I guess the module can always define `OCL_ICD_VENDORS=/run/opengl-driver/etc/OpenCL/vendors` and that should do the trick, no idea if it's the recommended way to proceed.

**Comment by vcunat** [comment]
Are you on 21.11 release?  Sounds like this might be fixed on unstable already: https://github.com/NixOS/nixpkgs/issues/153865

**Comment by tobiasBora** [comment]
Ahah, I'm on unstable, but my commit is like 2 weeks before this commit https://github.com/NixOS/nixpkgs/commit/a4bf4434570

My bad, I'll close for now and reopen once I upgraded. Thanks!

**Comment by vcunat** [comment]
Oh, now I see that 21.11 should contain that fix already, too.
