### ISSUE TITLE
Package request for rofi-rbw

### ISSUE THREAD

**Issue by farzin-az** [NixOS/nixpkgs#153841]
**Project description**
_describe the project a little_
rofi-rbw is a rofi client for rbw. Many rofi scripts have already been packaged but this rather new script is not. Though, it is possible to install it from pip, some applications don't recognize the binary.
**Metadata**

* homepage URL: https://github.com/fdw/rofi-rbw

**Comment by dataO1** [comment]
Would love to see This! I fiddled a bit around, but didnt quite get it running, im not very experienced with nix.
Does someone have a derivation, that works?

**Comment by dit7ya** [comment]
@dataO1 @farzin-az  I just added the above PR. Will highly appreciate testing and reviews.
