### ISSUE TITLE
Dolphin file manager doesn't create PDF and DJVU thumbnails

### ISSUE THREAD

**Issue by johkneisl** [NixOS/nixpkgs#153983]
### Describe the bug
KDE's file manager Dolphin doesn't create thumbnails of PDF files, despite being configured to do so and libsForQt5.kdegraphics-thumbnailers being installed. Thumbnails for images, videos, directories, and text files are created as expected.

### Steps To Reproduce
1. Install Dolphin and kdegraphics-thumbnailer on NixOS
2. Open Dolphin -> Configure Dolphin... -> Previews -> Select "PostScript, PDF and DVI Files" and "DjVu Files".
Set "No Limit" for previews and save.
3. Open Dolphin, set View -> Show Previews.

### Expected behavior
Thumbnails of PDF files are created.

### Screenshots
![image](https://user-images.githubusercontent.com/97337894/148640681-eded3f4f-9f42-4e25-b176-c4b8d67d95fe.png)

### Additional context
When I create a new user on my system, I can reproduce the problem.
PDF thumbnails can be created with either Nautilus+evince installed or Thunar+Tumbler installed.
Those thumbnails are not picked up by Dolphin, but by some other apps, such as index-fm.
Potentially relevant entry in the systemd journal:
    krunner[19796]: kf.kio.slaves.thumbnail.djvu: QProcess::FailedToStart ""
Installing several further KDE packages, following a working configuration by another user [here](https://gitlab.com/liketechnik/nixos-files/-/blob/master/profiles/graphical/default.nix#L27) doesn't resolve the problem. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre343944.ff377a78794"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by johkneisl** [comment]
Mostly solved by installing ghostscript.

**Comment by SuperSamus** [comment]
I don't think this issue should be closed until it works with kdegraphics-thumbnailers.

**Comment by SuperSamus** [comment]
Still an issue on NixOS 23.05.

**Comment by SuperSamus** [comment]
By the way, logs (with `QT_LOGGING_RULES="org.kde.dolphin=true"`) unfortunately aren't useful at all:
```
org.kde.dolphin: Failed to generate hover sequence preview #n for file "file:///path/to/file.pdf" (attempt n/3)
```
