### ISSUE TITLE
Go static compilation is broken

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#15399]
Just recently updated to the latest nixos-unstable commit.

`go build --ldflags '-extldflags "-static"' .` was working before.

Now it results in:

```
time go build --ldflags '-extldflags "-static"' .                                                                                                                     18:10:02
# k8s.io/kubernetes/cmd/hyperkube
/nix/store/wz2nx10xv5m6hn5j91w15abxnlz7sjsp-go-1.6.2/share/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/nix/store/s0kpgl8a101lkymj599f5a04s4wflf5s-binutils-2.26-dev/bin/ld: cannot find -lpthread
/nix/store/s0kpgl8a101lkymj599f5a04s4wflf5s-binutils-2.26-dev/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

go build --ldflags '-extldflags "-static"' .  289.63s user 19.02s system 525% cpu 58.706 total
```

**Comment by domenkozar** [comment]
What `nixos-version`?

**Comment by domenkozar** [comment]
@lethalman

**Comment by domenkozar** [comment]
@wkennington

**Comment by teh** [comment]
@colemickens I can't reproduce this - is this still an issue? If so, would you mind adding a bit more detail how you're running the command? E.g. in nix-shell? Installed via nix-env?

**Comment by drdaeman** [comment]
I know this is not StackOverflow, but I think I'll still write this comment - just in case someone else would find this issue from a search engine of their liking (that's how I came here).

If `go build -ldflags "-s -w -linkmode external -extldflags -static"` fails on NiOS, telling `cannot find -lpthread` and `cannot find -lc` - it's because the linker can't find static glibc to link with. You need to have `glibc.static` in your environment (and have `CFLAGS`/`LDFLAGS` adjusted accordingly).

One way to achieve this is to have something like the following as `shell.nix`, run `nix-shell` and then run `go build`/`make`/whatever:

    with import <nixpkgs> {}; {
      devEnv = stdenv.mkDerivation {
        name = "dev";
        buildInputs = [ stdenv git go glibc.static ];
        CFLAGS="-I${pkgs.glibc.dev}/include";
        LDFLAGS="-L${pkgs.glibc}/lib";
      };
    }

**Comment by domenkozar** [comment]
This could be added to https://nixos.org/nixpkgs/manual/#sec-language-go by making a PR to modify `doc/languages-frameworks/go.xml`

**Comment by Mic92** [comment]
Just in case it does not make it into the manual, I just copy 'n paste the snippet here: https://github.com/nixos-users/wiki/wiki/Go

**Comment by flokli** [comment]
I gave this a try in https://github.com/flokli/nixpkgs/commit/60d774c92a481daacf7d3844c7546b6da2d76804.

A
```
go build -ldflags "-v -linkmode external -extldflags -static"
````

of a simple helloworld project now succeeds.

However the `checkPhase` of the go derivation fails (which is why I didn't open a PR yet).

**Comment by zimbatm** [comment]
If there are no C dependencies, the easiest is to `export CGO_ENABLE = 0` and bypass the glibc entirely.

**Comment by Mic92** [comment]
We have it in the wiki: https://nixos.wiki/wiki/Go anything else required here?

**Comment by flokli** [comment]
Well, this documents a way to still build it with the current setup (and maybe `doc/languages-frameworks/go.xml` would be a more suitable place, as initially suggested in https://github.com/NixOS/nixpkgs/issues/15399#issuecomment-316040592).

I tried teaching the go compiler to know where the static libc is, so all this wouldn't be needed at all (but can't pursue this any further - if anyone could pick this up, I'd appreciate it)

As @zimbatm mentioned, setting `CGO_ENABLED=0` seems to be the better solution, at least as long as we don't need to link to any dynamic libraries. Wherever the docs about this would live, they should cover that solution aswell IMHO.

**Comment by Mic92** [comment]
> As @zimbatm mentioned, setting `CGO_ENABLED=0` seems to be the better solution, at least as long as we don't need to link to any dynamic libraries. Wherever the docs about this would live, they should cover that solution aswell IMHO.

Which docs?

**Comment by flokli** [comment]
The docs about how to build static go binaries (both with and without `CGO`) with the nixpkgs-provided go compiler.

**Comment by flokli** [comment]
I think this is sufficiently documented in https://nixos.wiki/wiki/Go, let's close this one.

I checked nixpkgs' `doc/languages-frameworks/go.section.md`. This seems to be mostly about the `buildGoModule` and `buildGoPackage` nixpkgs tooling.

**Comment by mitar** [comment]
The wiki didn't work for me inside `buildGo118Module`. I had to do the following:

```
  nativeBuildInputs = [musl];

  CGO_ENABLED = 0;

  ldflags = [
    "-linkmode external"
    "-extldflags '-static -L${musl}/lib'"
  ];
```

So important part is `CGO_ENABLED` because by default `buildGo118Module` sets `CGO_ENABLED=1`. I also decided to use musl so that I do not get warnings like:

```
warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Also setting `LDFLAGS` (nor `CGO_LDFLAGS`) didn't work for me. So I pass `-L` to `-extldflags` instead.

**Comment by flokli** [comment]
Yeah, glibc doesn't really like static linking :-)

Maybe you can extend the wiki with your findings?

**Comment by mitar** [comment]
Done: https://nixos.wiki/wiki/Go

**Comment by flokli** [comment]
Thanks!
