### ISSUE TITLE
Tor module is missing all client bridges functionality (can't use private bridges from tor project)

### ISSUE THREAD

**Issue by Fedcomp** [NixOS/nixpkgs#153921]
## Issue description

Commit https://github.com/NixOS/nixpkgs/commit/0ccdd6f2b043e5123ffd1f76cd2187c39ce19b94 changed the way tor module works. While making tor config options typesafe, it also lost a way to specify custom config (services.tor.extraConfig).
In turn, it seems (from my point of view, looking at https://github.com/NixOS/nixpkgs/blob/21.11/nixos/modules/services/security/tor.nix) users cannot specify custom bridges anymore, and use client bridge functionaly to bypass censorship in their countries.

I use following torrc config:
```
ExcludeExitNodes {fr}

UseBridges 1

ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy

Bridge obfs4 99.99.99.99:9999 somehash iat-mode=1
```
And it looks like none of these options can be expressed right now, in current tor module.
@ju1m i see you are current maintainer and the author of these changes. Is there a way for me to set custom config fow now, or use bridges? Or can it be added at some point to the module?
Right now i can't connect to tor directly, as all public bridges were banned in my country, so i specify them in bridge, and i consider this functionality to be very very important for using tor at all in censored countries.
ExcludeExitNodes also allows me not to land on the same country where external resources are banned (not to say about personal security concern).

**Comment by ju1m** [comment]
> Is there a way for me to set custom config fow now

@Fedcomp, sure, `services/security/tor.nix` follows [RFC0042](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md#part-1-structural-settings-instead-of-stringly-extraconfig) and uses [Freeform modules](https://nixos.org/manual/nixos/stable/index.html#sec-freeform-modules), so you should be able to set the custom options you want in `services.tor.settings` as you would do for explicitly typed options, this [is suggested by the migration instruction given when using extraConfig](https://github.com/NixOS/nixpkgs/blob/a7ecde854aee5c4c7cd6177f54a99d2c1ff28a31/nixos/modules/services/security/tor.nix#L207), but I agree this may not be obvious for newcomers as it is currently written.
Of course making a PR for typing more precisely the missing options would be welcome too :)

**Comment by Fedcomp** [comment]
Oh sorry i didn't know about nixos-freeform modules. I though i am locked to only typed options.
