### ISSUE TITLE
openmw-tes3mp: 0.7.1 -> 0.7.0-alpha

### ISSUE THREAD

**Issue by nixdaemon** [NixOS/nixpkgs#153944]
### Describe the bug
the latest version of [openmw-tes3mp](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/games/openmw/tes3mp.nix) in nixpkgs does not match the release version people use to host TES3MP servers ( 0.7.0-alpha). as a result, when someone tries to connect, they are kicked because their client's version doesn't match the server version.

### Steps To Reproduce
steps to reproduce the behavior:
1. install openmw-tes3mp (this will require data files from the game The Elder Scrolls III: Morrowind)
2. connect to a server ( I have a server up that is hosted at https://bottom.rs )
3. watch yourself get kicked

### Expected behavior
the packaged version of TES3MP should connect to a server without an issue

### Additional Content
the 0.7.0-alpha builds are advertised by the TES3MP community and it's developers as stable builds, listed here: https://github.com/TES3MP/openmw-tes3mp/releases/tag/0.7.0-alpha and that 0.7.1 is a dev build that is not meant for general use, usually with breaking features and additions that are still being tested out.

this is my first time filing a bug in this repo and i am not sure if this is the right place

**Comment by pufchek** [comment]
it seems this pr is what breaks this https://github.com/NixOS/nixpkgs/pull/123607

this pr rectifies ffmpeg3 vulns, but also changes the branch used from a stable build to an indev build, breaking compatibility with currently hosted public servers as a unintended side effect.

cc @peterhoeg

**Comment by peterhoeg** [comment]
Yeah, we should probably switch back to the officially sanctioned branch. Feel like taking a stab at it? Ping me if you need help.

**Comment by nixdaemon** [comment]
admittedly i dont know much about nix or how to package stuff for nixos, but (in theory) it may be as simple as swapping out a few lines

i guess this is a good place to start learning though, so ill give it a stab and see what comes of it

**Comment by peterhoeg** [comment]
Any luck @nixdaemon  ?

**Comment by peterhoeg** [comment]
@nixdaemon , there's a new 0.8.0 out just FYI.
