### ISSUE TITLE
dosfstools: upgrade is causing tests failures

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#15394]
## Issue description

135fe56183a2c125a777ce59aa5e78f51f3dfec2 &
346482c8d586de299ff8f457d69653917a4d62e2 are causing tests to fail:

```
Usage size: 10676566
Image size: 12582912
mkfs.fat 4.0 (2016-05-06)
Total number of sectors (24576) not a multiple of sectors per track (63)!
Add mtools_skip_check=1 to your .mtoolsrc file to skip this test
```
### Steps to reproduce

``` bash
$ nix-build '<nixos/release.nix>' -A tests.boot.biosUsb.x86_64-linux
```

**Comment by obadz** [comment]
see http://hydra.nixos.org/build/35505675/nixlog/1

cc @nckx

**Comment by obadz** [comment]
cc @dezgeg who seems to have a solution involving `export MTOOLS_SKIP_CHECK=1`

**Comment by wkennington** [comment]
You could also align the fs size correctly so that you don't need to skip
this check.

**Comment by dezgeg** [comment]
Not sure what's the benefit - all this cylinder-head-sector business should be long obsolete.

**Comment by obadz** [comment]
Reverted upgrade for now…

**Comment by Profpatsch** [comment]
triage: I’m gonna close, feel free to reopen.
