### ISSUE TITLE
Problem viewing H264 videos in Firefox

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#15408]
## Issue description

H264 videos in web pages are replaced by an error message:

```
No video with supported format and MIME type found
```

### Steps to reproduce

- switch to nixos-unstable-small (currently 6054c9f217a8db8219d5a63bcb2c275bc13962f0)
- go to http://www.quirksmode.org/html5/tests/video.html
- you should see the above error message instead of the H264/mp4 video

## Technical details

* System: NixOS: 16.09.git.94ee1b7 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.94ee1b7

**Comment by DamienCassou** [comment]
This can be related to 3a52c5fa7d059ff75b3f56a817832e84f2c96e04

**Comment by abbradar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/e81c6c77684e88887cc56af66bc77c68c9391561

**Comment by mario-holubar** [comment]
Apparently this has been fixed for eight years, but I am having this issue now, on NixOS 24.05, nix (Nix) 2.18.7.
