### ISSUE TITLE
licenses.sspl cannot be used in allowlistedLicenses/blocklistedLicenses or shortName should link to lib.licenses atrrset

### ISSUE THREAD

**Issue by ony** [NixOS/nixpkgs#154031]
### Describe the bug
Looks like `blocklistedLicenses`/`allowlistedLicenses` require referenced licenses `shortName` to match attribute name of `lib.licenses`.  
This is broken for SSPL license and for some packages that have inline license attrset.

### Steps To Reproduce
1. Add `nixpkgs.config.blocklistedLicenses = [ pkgs.lib.licenses.sspl ];` (can use also `allowlistedLicenses`) in NixOS global configuration.
2. Try to build configuration.

### Expected behavior
* Can build your system unless it references package with license `sspl` (I guess Mongodb related stuff) and which is referenced in `blocklistedLicenses`.  

* Can reference licenses in-lined in packages . E.g. `pkgs.ntp.meta.license` (or its direct value)

https://github.com/NixOS/nixpkgs/blob/048fd95f106ef4dca58ff01159207a027ab612d9/pkgs/tools/networking/ntp/default.nix#L33-L36

### Screenshots
```
error: ‘SSPL’ is not an attribute of lib.licenses

       … while evaluating anonymous lambda

       at /nix/store/9lx5wss5ky22gjfwwr2ia2h6h6f039qb-source/pkgs/stdenv/generic/check-meta.nix:23:20:

           22|   onlyLicenses = list:
           23|     lib.lists.all (license:
             |                    ^
           24|       let l = lib.licenses.${license.shortName or "BROKEN"} or false; in

       … from call site
...
       at /nix/store/9lx5wss5ky22gjfwwr2ia2h6h6f039qb-source/pkgs/stdenv/generic/check-meta.nix:31:14:

           30|     if lib.mutuallyExclusive allowlist blocklist then
           31|       assert onlyLicenses allowlist; assert onlyLicenses blocklist; true
             |              ^
           32|     else

       … while evaluating 'checkValidity'
...
       at /nix/store/9lx5wss5ky22gjfwwr2ia2h6h6f039qb-source/lib/attrsets.nix:369:15:

          368|       inherit name;
          369|       value = f name (catAttrs name sets);
             |               ^
          370|     }) names);

       … while evaluating the attribute 'ssh'
```

### Additional context

This was found out in attempt to use pre-approved list of "safe" open source licenses by adding in `blocklistedLicenses` all that are not on the list but present in `lib.licenses`. But `sspl` have next definition (notice upper case in `shortName`):
https://github.com/NixOS/nixpkgs/blob/048fd95f106ef4dca58ff01159207a027ab612d9/lib/licenses.nix#L757-L759

In order to fully implement pre-approved "allow list" (different from `allowlistedLicenses`) it is required to be able to reference licenses that are in package meta but not in `lib.licenses`.

### Notify maintainers

MongoDB maintainers: @bluescreen303 @offline @cstrahan

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
zsh%  nix run nixpkgs\#nix-info -- -m
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.334684.1158f346391"`
 - channels(nikolay): `"nixpkgs-unstable-21.11pre310022.14b0f20fa1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ony** [comment]
Why do we even have this restriction in a first place?

https://github.com/NixOS/nixpkgs/blob/c4bb9084aa159f029ae9e35edb580d22f0ed5fdb/pkgs/stdenv/generic/check-meta.nix#L22-L27

I'm not sure what it solves.

Tracing back to when it was introduced led me to [commit from 2015 with sole description "stdenv: take license parameter checks out of mkDerivation path"](https://github.com/NixOS/nixpkgs/commit/0feb19b6b498c7d494055c0c97fc38c052f595a3). But original code had no such restrictions:

https://github.com/NixOS/nixpkgs/blob/aca361fa4960b51e5bcdf13fc826ebdbcb534302/pkgs/stdenv/generic/default.nix#L91-L113

*(this is roughly what I expected when I tried to use `blocklistedLicenses`)*

**Comment by ncfavier** [comment]
@wmertens do you remember why you added this in https://github.com/NixOS/nixpkgs/commit/0feb19b6b498c7d494055c0c97fc38c052f595a3 ?

**Comment by wmertens** [comment]
Oops I missed this question, sorry. I don't remember, but I expect that I added the check to make sure that all licenses are maintained in the central registry.

**Comment by ony** [comment]
@wmertens 

I think I understand what motivates that. It is hard to control use of licenses if there is no easy way to reference them. If bunch of package will have their own in-line version of say MIT license it will be as good as listing packages instead of licenses in `allowlistedLicenses`.

But I also see benefit of inline licenses since some packages may have specific ones (e.g. `nixpkgs#ntp`). Requiring them to be present in `lib.licenses` in its extreme will result into something like secondary index of packages.

So, it seems that there needs to be a balance. And maybe instead of allow-listing in-lined licenses it makes more sense to allow-list individual packages in addition to licenses.

On the other hand, I wonder if it still makes sense to have such restriction nowadays when we have Flakes that may set direction to decentralize `nixpkgs`.

If it will be lifted off it will be possible to use `allowlistedLicenses` for both types of packages without much of effort. E.g.

```nix
{
  pkgs.config.allowlistedLicenses = [
    # license families
    pkgs.lib.licenses.mit

    # individual packages
    pkgs.ntp.meta.license
  ];
}
```
