### ISSUE TITLE
NixOS does not boot with WQHD (1440p) displays in default configuration on amdgpu

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#154132]
### Describe the bug
I've recently switched out my old Full HD (1080p) monitors connected over HDMI, for new WQHD (1440p) monitors connected over DisplayPort. This worked fine out of the box on Windows. However, I could not boot into NixOS; during the boot process, presumably during KMS, the screen would blank completely with no way to get graphics back.

After some searching around, I ran into [this thread](https://forum.manjaro.org/t/can-not-boot-when-using-a-3440x1440-monitor/61456), which describes a similar issue, with roughly the same journalctl output as I had. It mentions that the problem can be resolved by doing early KMS; in the case of NixOS, this turned out to involve setting `boot.initrd.kernelModules = [ "amdgpu" ];`, which solved the issue and let the system boot correctly.

### Steps To Reproduce
1. Have an existing install (using amdgpu) with 1080p monitors over HDMI?
2. Replace the monitors with 1440p monitors over DisplayPort.
3. Try to boot, run into a blank screen.

### Expected behavior
The system should boot correctly after switching out the monitors, without requiring further manual configuration.

### Screenshots
n/a, the screen is blank :)

### Additional context
The issue could be resolved on a NixOS level by automatically adding `amdgpu` to `boot.initrd.kernelModules`, at least when the `amdgpu` driver is being used. I don't know whether this has any undesirable tradeoffs.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(sven): `""`
 - channels(root): `"nixos-21.11.335005.c6019d8efb5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mainrs** [comment]
Just wanted to chime in and add that this is the case for `nvidia` as well.

**Comment by SuperSamus** [comment]
I'm using a 1440p (144Hz) monitor just fine, with both HDMI and DisplayPort. (AMD RX 6700XT)
Using the default configuration (`nixos-generate-config`):
```nix
  boot.kernelModules = [ "kvm-amd" ];
```

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3-zen1, NixOS, 23.05 (Stoat), 23.05.20230108.0c9aadc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
I repeat.
Right now, on my end, NixOS boots fine on a 1440p monitor with the default configuration from `nixos-generate-config`.
Is that the case for you?

**Comment by SuperSamus** [comment]
Bump, can you answer @joepie91?

**Comment by SuperSamus** [comment]
Bumping again.

**Comment by SuperSamus** [comment]
Bumping again.
