### ISSUE TITLE
qutebrowser reports missing qt5 libraries and fails to start

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#15419]
## Issue description
qutebrowser reports missing qt5 libraries and fails to start.

### Steps to reproduce
- install qutebrowser
- start qutebrowser
- look at the errormessage

## Technical details

* System: 16.09pre83100.25e3c09 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre83100.25e3c09"

**Comment by abbradar** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/15334. Please reopen if that's not the case.
