### ISSUE TITLE
Update SDL2 to 2.0.20

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#154137]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: SDL2

current version: 2.0.14
desired version: 2.0.20

###### Notify maintainers

maintainers: @cpages 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by prusnak** [comment]
SDL2 update is being worked on here : https://github.com/NixOS/nixpkgs/pull/136166

**Comment by quantmint** [comment]
> SDL2 update is being worked on here : #136166

That's for SDL 2.0.16.

**Comment by prusnak** [comment]
> That's for SDL 2.0.16.

Yes, the PR can be updated to 2.0.18

**Comment by prusnak** [comment]
PR https://github.com/NixOS/nixpkgs/pull/136166 updated to 2.0.18

**Comment by cpages** [comment]
I'm sorry because I have some issues with my nixos machine and I cannot help with this right now, but I just saw they released an update because joystick hotplugging is broken in 2.0.18 (https://discourse.libsdl.org/t/sdl-2-0-20-released/34407). Could you update to 2.0.20? Thanks!
