### ISSUE TITLE
rpi-eeprom is out of date

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#154202]
As far as I can tell, rpi isn't tagging their releases, but they drop releases in their firmware/stable dir:

https://github.com/raspberrypi/rpi-eeprom/tree/master/firmware/stable

For example, it seems there was a newest, latest release in dec 2021.

cc:  @superherointj

**Comment by avdv** [comment]
rpi-eeprom is at version 2022-03-10 currently.

According to the [release notes](https://github.com/raspberrypi/rpi-eeprom/blob/83347f3968200a031b3aaa4e49ed445304a1c4a0/firmware/release-notes.md#2022-03-10---promote-the-2022-03-10-beta-release-to-lateststable) this is the latest stable version.

Side note: They also have an entry "2022-04-22 - Add pieeprom-2022-04-26 release - STABLE/BETA" -- I am not sure what STABLE/BETA means.. is it stable? or is it beta? Maybe that's just a typo and they meant "LATEST/STABLE"?
