### ISSUE TITLE
[Package Request] guacamole-server

### ISSUE THREAD

**Issue by ilovefornite797** [NixOS/nixpkgs#154217]
**Apache guacamole-server**
_Remote desktop access via web browser_

**Metadata**

* homepage URL: [https://guacamole.apache.org/](https://guacamole.apache.org/)
* source URL: [https://dlcdn.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz](https://dlcdn.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz)
* license: apache 2.0
* platforms: unix, linux, darwin

**Comment by mausch** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/17879
