### ISSUE TITLE
Idea security updates

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#15425]
JetBrains just released updates for most of its applications including security updates.

http://blog.jetbrains.com/blog/2016/05/11/security-update-for-intellij-based-ides-v2016-1-and-older-versions/

This should probably be backported to older Nix releases.

I'm working on updating the Nix packages right now.

**Comment by edwtjo** [comment]
Pushed to 16.03, thanks!

**Comment by chris-martin** [comment]
Are we not doing security fixes in 15.09?

**Comment by joachifm** [comment]
@chris-martin 15.09 is unsupported, afaik, at least in the sense that nobody (that I know of) is systematically pushing security updates to it. If you care about 15.09, please open a PR against it.

**Comment by chris-martin** [comment]
Okay, I just didn't know.

**Comment by jagajaga** [comment]
15.09 is unsupported.

**Comment by bjornfor** [comment]
Eelco pushed latest openssl to 15.09 and I've been backporting various fixes and improvements myself. It's _officially_ unsupported I'd say. (But git log shows there is some support.)
