### ISSUE TITLE
`python3Packages.einops` does not build on x86_64-linux

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#154251]
### Describe the bug
einops fails to build on x86_64-linux as of 0cd9bb5dc14bfebec67003f53deb4da08e5a1eb9 (current master). It fails in the install tests, by hanging seemingly forever after
```
...
tests.test_layers.test_reduce_symbolic ... ok
<hangs forever........>
```

### Steps To Reproduce
1. `nix-build -A python3Packages.einops` on x86_64-linux as of 0cd9bb5dc14bfebec67003f53deb4da08e5a1eb9.
2. Observe the build failure: https://gist.github.com/samuela/d0c6fcd03e83c0d5ba59e8a61ecc1734

### Expected behavior
The package to build.

### Screenshots
n/a

### Additional context
Uncovered in the process of reviewing https://github.com/NixOS/nixpkgs/pull/154115.

### Notify maintainers

@yl3dy @veprbl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.87, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334578.75f3534c98a, nix-ld"`
 - channels(skainswo): `"home-manager, nixpkgs-unstable-22.05pre343295.adf7f03d3bf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by veprbl** [comment]
Duplicate of #152049

**Comment by samuela** [comment]
Closing in favor of dup
