### ISSUE TITLE
nscd not starting on boot

### ISSUE THREAD

**Issue by sylvainf911** [NixOS/nixpkgs#154306]
### Describe the bug
The nscd.service is not started on boot.

### Steps To Reproduce
1. Boot a recent NixOS 21.11 with an LDAP configuration
2. Do `id user_in_ldap` and get `id: ‘user_in_ldap’: no such user`
3. systemctl status nscd returns `Active: inactive (dead)`

My LDAP configuration:

```
    ldap = {
      enable = true;                                    
      daemon.enable = true;             
      base = "dc=example,dc=com";
      bind = {
        distinguishedName = "uid=ldapread,ou=People,dc=example,dc=com";
        policy = "soft";                     
        timeLimit = 5;
        passwordFile = ''${pkgs.writeText "ldap-bind" "readonlypassword"}'';
      };                                             
      server = "ldap://ldap.example.com";               
                 
      daemon.extraConfig = ''
        map passwd loginShell "/run/current-system/sw/bin/bash"
      '';
    };
```

### Expected behavior
`nscd` should start on boot like it was before the upgrade.

### Additional context
On NixOS 21.11.334027.e34c5379866 (with systemd 249.5) `nscd` started normally.
On NixOS 21.11.335119.79c7b6a353e (with systemd 249.7), the service does not start on boot anymore.

On my NixOS desktop with an up to date version, `nscd` starts normally but I don't use LDAP.

I am not really familiar with `systemd` details but a difference I see is that commit ec0131da46b35417ba7e6d41686659e0828368fe
by Arian van Putten talks about removing `nss-lookup.target` and `nss-user-lookup.target` from `multi-user.target.wants`.
I can see on the working server that `/etc/systemd/system/multi-user.target.wants/nss-user-lookup.target` is present
but not on the problematic one. When I search in `journalctl -b` to see any trace of `nscd`, I don't see any on the problematic server.
I see `Starting Name Service Cache Daemon...` and `Reached target User and Group Name Lookups.` on the working server.

It is like `nss-user-lookup.target` is nerver reached on the problematic server and so `nscd.service` is not started.
I added `systemd.services.nscd.wantedBy = ["multi-user.target"];` in my `configuration.nix` as a temporary fix and it now starts on boot.

### Notify maintainers
@arianvp

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.90, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335119.79c7b6a353e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by abbradar** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/154320.
