### ISSUE TITLE
bison: Test failures while bootstrapping on armv7l-linux

### ISSUE THREAD

**Issue by queezle42** [NixOS/nixpkgs#154308]
### Describe the bug
While building an Image for armv7l-linux, a `bison`-derivation fails it's test suite:

```
bison> ## --------------------------- ##
bison> ## GNU Bison 3.8.2 test suite. ##
bison> ## --------------------------- ##
[...]
bison>   2: Invalid number of arguments                     FAILED (input.at:29)
[...]
bison>  64: Deprecated directives                           FAILED (input.at:3031)
[...]
bison> 314: Invalid uses of %empty                          FAILED (actions.at:192)
[...]
bison> ## ------------- ##
bison> ## Test results. ##
bison> ## ------------- ##
bison> ERROR: 696 tests were run,
bison> 3 failed unexpectedly.
bison> 80 tests were skipped.
```

It's not `pkgs.bison`, but an earlier (bootstrap?) `bison`-derivation:
```
$ nix build -L --no-link nixpkgs/3f4e74e04cfe645c10d3423fa3e642491f16982a#legacyPackages.armv7l-linux.bison
[...]
error: builder for '/nix/store/wnr2b4sxb1k4h1g8cg94fh27652bqq9k-bison-3.8.2.drv' failed with exit code 2;
       last 10 log lines:
       >    To: <bug-bison@gnu.org>
       >    Subject: [GNU Bison 3.8.2] testsuite: 2 64 314 failed
       >
       > You may investigate any problem if you feel able to do so, in which
       > case the test suite provides a good starting point.  Its output may
       > be found below `tests/testsuite.dir'.
       >
       > make[1]: *** [Makefile:13927: installcheck-local] Error 1
       > make[1]: Leaving directory '/build/bison-3.8.2'
       > make: *** [Makefile:10377: installcheck-recursive] Error 1
       For full logs, run 'nix log /nix/store/wnr2b4sxb1k4h1g8cg94fh27652bqq9k-bison-3.8.2.drv'.
error: 1 dependencies of derivation '/nix/store/v2l8w9552acwx0a2gdcsnwnqbgcrm2h6-bash-5.1-p8.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1a01vynszdhyvpzrf99l0af7z309awgr-binutils-2.35.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7rq4jvx4j6v7h2nqra8ccfwfqm5hdjg4-binutils-2.35.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zlv3c1jzrzix31wnd15dxwa6axr2xpli-glibc-2.33-56.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1hv9rp4hcbm911r94kj3zppqzbhmyh2g-bison-3.8.2.drv' failed to build
```

The failure was introduced by https://github.com/NixOS/nixpkgs/pull/141210

I have tried to build from multiple nixpkgs revs:
- https://github.com/NixOS/nixpkgs/commit/d660d5c5b882c8302907735c735f5f1f2da047c2 before the PR, builds successfully
- https://github.com/NixOS/nixpkgs/commit/3f4e74e04cfe645c10d3423fa3e642491f16982a the merged PR, broken
- some commits up to https://github.com/NixOS/nixpkgs/commit/4bedea7ed1d8d0d1ad4b92fcb09790c2b9a8a27a (recent master), still broken

### Steps To Reproduce

I'm building with qemu binfmt, without any cache:
`boot.binfmt.emulatedSystems = [ "armv7l-linux" ];`

Bash directly depends on the broken bison:
`nix build -L nixpkgs#legacyPackages.armv7l-linux.bash`

### Notify maintainers
@trofi

I'm not sure who else should be tagged — this would be relevant for any `armv7l-linux`-maintainer.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.10, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `cb372c3b8880e504b06946e8fb2ca9777c685505`

**Comment by trofi** [comment]
Thank you for the report!

I'll try to reproduce locally. I'm not very familiar with binfmt on nixos. I guess "armv7l-linux" is a binfmt entry foe qemu-arm (32-bit). What does `nixpkgs#legacyPackages.aarch64-linux.bash` do? Should I just try it? Why it's an `aarch64`? I suspect I won't get -32-bint ARM binary.

Do you have a chance extracting
- `tests/testsuite.dir` directory (`--keep-failed` should help)
- full build log out of failed build?  (`nix log ...` should help)
out of failed build? It would ease comparing it against successful x86_64 build.

**Comment by queezle42** [comment]
Oops, that is a copy-paste error (I also verified aarch64, but it is not affected) - should have been `nixpkgs#legacyPackages.armv7l-linux.bash` (I've fixed that now).

Building with qemu-binfmt is full emulation of the target architecture and _should_ yield identical results to building on real hardware (i.e. slow but reliable) - I don't think that's the issue.

I can rebuild to get the logs in a few hours.

**Comment by trofi** [comment]
Aha, that makes sense. `$ nix build -f. bash --argstr system armv7l-linux` should be roughly the same, yes?

I left it spinning on `x86_64-linux` against today's `master` to see if it fails for me.

**Comment by trofi** [comment]
For me `$ nix build -f. bash --argstr system armv7l-linux` built successfully from 07e6e9d92f38f5b1064aca4fa3083852dd7b81b6  (`Tue Jan 11 08:41:46 2022 +0100`).

Now I'm trying your version: cb372c3b8880e504b06946e8fb2ca9777c685505  (`Sat Dec 25 13:07:40 2021 +0800`)

**Comment by trofi** [comment]
On cb372c3 (`Sat Dec 25 13:07:40 2021 +0800`) `$ nix build -f. bash --argstr system armv7l-linux` also succeeded for me.

**Comment by queezle42** [comment]
So far I could reproduce this on two machines (similar hardware/configuration though). I have asked friends to verify this and will have more results later.

I have also reproduced the bug without flakes (`nix build -f. bash --argstr system armv7l-linux`)

Here is my testsuite.dir from a failed run: [testsuite.dir.zip](https://github.com/NixOS/nixpkgs/files/7850574/testsuite.dir.zip)

**Comment by BBBSnowball** [comment]
```
[user@hetzner-temp:~/nixpkgs]$ nix build -f. bash --argstr system armv7l-linux                       
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: builder for '/nix/store/jfgnli3r88r276cj6iimg4swpkak2h4r-bison-3.8.2.drv' failed with exit code 2;
       last 10 log lines:                                                                           
       >    To: <bug-bison@gnu.org>                                                                 
       >    Subject: [GNU Bison 3.8.2] testsuite: 2 64 314 failed
       >                                                                                            
       > You may investigate any problem if you feel able to do so, in which                                                                                                                            
       > case the test suite provides a good starting point.  Its output may
       > be found below `tests/testsuite.dir'.                                                      
       >                                                                                                                                                                                                       > make[1]: *** [Makefile:13927: installcheck-local] Error 1                                                                                                                                             > make[1]: Leaving directory '/build/bison-3.8.2'                                                                                                                                                       > make: *** [Makefile:10377: installcheck-recursive] Error 1                                                                                                                                            For full logs, run 'nix log /nix/store/jfgnli3r88r276cj6iimg4swpkak2h4r-bison-3.8.2.drv'.                                                                                                        
error: 1 dependencies of derivation '/nix/store/a2ar6n8v4nf7criwv4yw5s6mxbm5ll8j-bash-5.1-p12.drv' failed to build                                                                                      
                                                                                                    
[user@hetzner-temp:~/nixpkgs]$ git status                                                           
On branch master                                                                                    
Your branch is up to date with 'origin/master'.                                                     
                                                                                                    
nothing to commit, working tree clean                                                                                                                                                                   
                                                                                                    
[user@hetzner-temp:~/nixpkgs]$ git rev-parse HEAD                                                    
fdbd3db45c58b7f04da9ace7c6d42e9ef03bd78f
```

`nix-build . -A bash --argstr system armv7l-linux` has the same result.

Build system is a Hetzner VM (CPX51) with config `github:BBBSnowball/nixcfg#nixosConfigurations.hetzner-temp.config.system.build.toplevel` plus `boot.binfmt.emulatedSystems = [ "armv7l-linux" ];`.

The failed tests are:
```
  2: Invalid number of arguments                     FAILED (input.at:29)
 64: Deprecated directives                           FAILED (input.at:3031)
314: Invalid uses of %empty                          FAILED (actions.at:192)
```

**Comment by queezle42** [comment]
That's it!

x86_64:
```
$ nix shell nixpkgs#bison
$ bison
bison: missing operand
Try 'bison --help' for more information.
```

qemu-binfmt aarch64:
```
$ nix shell nixpkgs#legacyPackages.aarch64-linux.bison
$ bison
/nix/store/mk6jf2n2bysmgvyl3g3krx1ml8r2b74z-bison-3.8.2/bin/bison: missing operand
Try '/nix/store/mk6jf2n2bysmgvyl3g3krx1ml8r2b74z-bison-3.8.2/bin/bison --help' for more information.
```

Since hydra builds on natively, the problem wasn't visible on aarch64.

**Comment by BBBSnowball** [comment]
I'm not sure what the "right" way would be but we can monkey-patch it. binfmt does have an option to preserve argv0 but we have to pass it to qemu in the right way. Debian just enabled all the flags and it works somehow. They don't have any wrapper script but maybe they set special options when compiling qemu, e.g. [`CONFIG_FORCE_PRESERVE_ARGV0`](https://patchew.org/QEMU/20191024153847.31815-1-laurent@vivier.eu/).

This is what works for NixOS:
1. enable `boot.binfmt.registrations.armv7l-linux.preserveArgvZero = true;`
2. patch the binfmt script to pass the second parameter after `-0`

Here is the modified `/run/binfmt/armv7l-linux`:
```
#!/nix/store/v1d8l3zqnia3hccqd0701szhlx22g54z-bash-5.1-p8/bin/sh
argv0="$2"; prog="$1"; shift; shift
exec -- /nix/store/v8r3mxj08v1i62a5mkjashyh4hflmlhi-qemu-6.1.0/bin/qemu-arm -0 "$argv0" "$prog" "$@"
# instead of: exec -- /nix/store/v8r3mxj08v1i62a5mkjashyh4hflmlhi-qemu-6.1.0/bin/qemu-arm "$@"
```

We can *almost* change this with `mkForce` but `boot.binfmt.registrations.armv7l-linux.interpreter` has to be a path.

In any case, this is a qemu / binfmt issue so I guess we should open a new issue. The test in bison is a bit unclean in my opinion but it will be fine in normal environments.

**Comment by trofi** [comment]
I wonder why test does not fail for me. I'm on NixOS unstable.

**Comment by trofi** [comment]
```
$ nix-build . -A bison --argstr system armv7l-linux
/nix/store/5gfdg82vbx7pp853098j0s2l96rq87fc-bison-3.8.2
$ file /nix/store/5gfdg82vbx7pp853098j0s2l96rq87fc-bison-3.8.2/bin/bison /nix/store/5gfdg82vbx7pp853098j0s2l96rq87fc-bison-3.8.2/bin/bison: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /nix/store/jngm0zhvalljnhmavzlgmrccvzfr45l4-glibc-2.33-59/lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, not stripped
$ /nix/store/5gfdg82vbx7pp853098j0s2l96rq87fc-bison-3.8.2/bin/bison
/nix/store/5gfdg82vbx7pp853098j0s2l96rq87fc-bison-3.8.2/bin/bison: missing operand
Try '/nix/store/5gfdg82vbx7pp853098j0s2l96rq87fc-bison-3.8.2/bin/bison --help' for more information.
```

```
$ file /run/binfmt/armv7l-linux
/run/binfmt/armv7l-linux: symbolic link to /nix/store/z2mpakccvnaxgwynlidbadgcmk9m7fg9-qemu-arm-binfmt-P-x86_64-unknown-linux-musl/bin/qemu-arm-binfmt-P
$ file /nix/store/z2mpakccvnaxgwynlidbadgcmk9m7fg9-qemu-arm-binfmt-P-x86_64-unknown-linux-musl/bin/qemu-arm-binfmt-P
/nix/store/z2mpakccvnaxgwynlidbadgcmk9m7fg9-qemu-arm-binfmt-P-x86_64-unknown-linux-musl/bin/qemu-arm-binfmt-P: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by trofi** [comment]
> I wonder why test does not fail for me. I'm on NixOS unstable.

Looking at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/binfmt.nix#L23-L32 I probably don't use `if wrapInterpreterInShell then` branch. That seems to depend on interpreter name: `preserveArgvZero = "qemu-${qemuArch}" == baseNameOf interpreter;`.

Probably was already fixed by 29acc14f0db8957855c1e629a105992a4c975100 `Merge pull request #143060 from zhaofengli/binfmt-argv0`.

**Comment by trofi** [comment]
Can you test against current `master`?

**Comment by BBBSnowball** [comment]
Nice! Looking for PR or making one was on my TODO list. It looks like zhaofengli beat me to it by a few months :-)

I can't easily test against master right now. However, I agree that the PR brings the binfmt feature that we need (and if it didn't work out, that would be a another bug).

I'm a bit puzzled because I thought that I had looked at master but apparently not: The code was already merged at that time and I didn't see it.

In any case, I think we can close this bug if queezle agrees.

**Comment by BBBSnowball** [comment]
Hah, wait, I can test it!

```
[root@hetzner-temp:/etc/nixos/nixcfg/hosts/hetzner-temp]# nix flake lock --update-input nixpkgs                                                                                                         
warning: Git tree '/etc/nixos/nixcfg' is dirty                                                                                                                                                          
warning: updating lock file '/etc/nixos/nixcfg/hosts/hetzner-temp/flake.lock':                      
• Updated input 'nixpkgs':                                                                                                                                                                              
    'github:NixOS/nixpkgs/e67c94a1adbb5cf8a0448bc9c434589b2dd293c2' (2022-01-05)                                                                                                                        
  → 'github:NixOS/nixpkgs/30a16ccb0828144a3f456f4e530004ac72078fef' (2022-01-15)                                                                                                                        
warning: Git tree '/etc/nixos/nixcfg' is dirty                                                                                                                                                          
                                                                                                                                                                                                        
[root@hetzner-temp:/etc/nixos/nixcfg/hosts/hetzner-temp]# nixos-rebuild --flake . test
...
[root@hetzner-temp:/etc/nixos/nixcfg/hosts/hetzner-temp]# PATH=/nix/store/9vw0przkg1ggnwmcri31554l254pyg6d-bison-3.8.2/bin/:$PATH bison
bison: missing operand
Try 'bison --help' for more information.

[root@hetzner-temp:/etc/nixos/nixcfg/hosts/hetzner-temp]# file /nix/store/9vw0przkg1ggnwmcri31554l254pyg6d-bison-3.8.2/bin/bison 
/nix/store/9vw0przkg1ggnwmcri31554l254pyg6d-bison-3.8.2/bin/bison: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /nix/store/winzj9hgq71zvqqff6al15ar5c7g8pxb-bootstrap-stage0-glibc-bootstrap/lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, not stripped

...
[user@hetzner-temp:~/nixpkgs]$ nix-build . -A bash --argstr system armv7l-linux
...
696 tests were successful.                                                                                                                                                                              
80 tests were skipped.                                                                                                                                                                                  make[1]: Leaving directory '/build/bison-3.8.2'
... (still building)
```

-> Looking good so far.

**Comment by queezle42** [comment]
Yes, booting in to a configuration that has https://github.com/NixOS/nixpkgs/pull/143060 applied and then rebuilding works. I could even build a commit that failed before, so I'm closing the issue. Thanks for the help!

**Comment by pickfire** [comment]
I tried building nixos image for raspberry pi 2 using binfmt-qemu and I faced the same issue with bison tets. But I am not using nixos, I am using arch linux binfmt-qemu-static with `--argstr system armv7l-linux`. How can I solve this issue since the mentioned solutions is to tweak nixos configuration.nix and do something there, but I am not quite sure what to do on arch here. This is how I build:
```
> cat sd-image.nix 
{ ... }: {
  nixpkgs.config.allowUnsupportedSystem = true;
  imports = [
    <nixpkgs/nixos/modules/installer/sd-card/sd-image-raspberrypi.nix>
  ];
  # put your own configuration here, for example ssh keys:
  users.extraUsers.root.openssh.authorizedKeys.keys = [
     "ssh-ed25519 ..."
  ];
}
> nix-build '<nixpkgs/nixos>' -A config.system.build.sdImage --argstr system armv7l-linux -I nixos-config=./sd-image.nix  # took roughly 2-4 hours I think on my laptop to get to the failure
```
I have installed `binfmt-qemu-static` and `qemu-user-static`, then restarted `systemd-binfmt` before building. How can I fix the issue on non-nixos?

**Comment by trofi** [comment]
Make sure your registered binfmt-misc interpreter preserves argv0 for ran programs.

**Comment by pickfire** [comment]
I did not try using binfmt qemu, lI tried building using cross but it still failed with the same error.

<details>
<summary>To reproduce:</summary>

Context, I built this on arch linux with a patched busybox https://bugs.archlinux.org/task/73998 and building for raspberry pi 2. (below took me roughly 3-5 hours to get to the failure on my laptop)
1. Have `flake.nix`
```nix
{
  description = "Example";
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  outputs = { self, nixpkgs }: rec {
    nixosConfigurations.rpi2 = nixpkgs.lib.nixosSystem {
      system = "armv7l-linux";
      modules = [
        "${nixpkgs}/nixos/modules/installer/sd-card/sd-image-raspberrypi.nix"
        {
          nixpkgs.config.allowUnsupportedSystem = true;
          nixpkgs.crossSystem.system = "armv7l-linux";
          # nixpkgs.overlays = [(self: super: {
          #   liburing = super.liburing.overrideAttrs (old: {
          #     postInstall = ''
          #       # Copy the examples into $bin. Most reverse dependency of this package should
          #       # reference only the $out output
          #       mkdir -p $bin/bin
          #       cp ./examples/io_uring-cp examples/io_uring-test $bin/bin
          #       cp ./examples/link-cp $bin/bin/io_uring-link-cp
          #       cp ./examples/ucontext-cp $bin/bin/io_uring-ucontext-cp || true
          #     '';
          #   });
          # })];
          users.extraUsers.root.openssh.authorizedKeys.keys = [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJjFZ141827Ow4fSCYL7SaRlsCI93cGbcfhRgQODcYes ivan@mi"
          ];
        }
      ];
    };
    images.rpi2 = nixosConfigurations.rpi2.config.system.build.sdImage;
  };
}
```
2. `git add flake.nix`
3. `nix build .#images.rpi2`
4. `nix log /nix/store/6lkl3npvpvr81m6x5if4aapg43gh9bwl-bison-3.8.2.drv` output
[bison-3.8.2-log.txt](https://github.com/NixOS/nixpkgs/files/8190836/bison-3.8.2-log.txt)

</details>

**Comment by trofi** [comment]
You already do use binfmt-qemu. The question is what do you have registered as an interpreter. Chances are you have the interpreter that does not preserve argv0. That would need to be fixed on host system (archlinux), not in nixpkgs.

**Comment by BBBSnowball** [comment]
I think this is the relevant config for Arch: https://aur.archlinux.org/cgit/aur.git/tree/qemu-static.conf?h=binfmt-qemu-static

It passes flags C and F but not P. P would be for "preserve program name", which is the relevant part. Unfortunately, it will *not* work to just pass that flag because the interpreter program has to be adjusted (i.e. you have to write a script that accepts the additional argument and passes things on to qemu in the right way). You can check in `/proc/sys/fs/binfmt_misc` which flags are actually set.

Maybe you should go the easy route: Verify that the program name is the only thing that is amiss for the tests and then build without the tests.

**Comment by pickfire** [comment]
Not sure why but bison tests seemed to pass on `nix-build` but `nix build` still fails using cross compile, so I can already continue building on other parts (it now fails on other parts), thanks for the help.
