### ISSUE TITLE
Gnome-shell regularly restarts

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#15434]
## Issue description

2 or 3 times per hour, gnome shell restarts. At this occasion, windows loose their decorations for a few seconds.
### Steps to reproduce

Use gnome 3.18 from nixos-unstable.
## Technical details

in journalctl:

``` journalctl
mai 13 14:00:36 luz3 audit[1335]: ANOM_ABEND auid=1000 uid=1000 gid=100 ses=2 pid=1335 comm=".gnome-shell-wr" exe="/nix/store/cnn0qldaw3nfklq80ggs9vaypi8azvc2-gnome-shell-3.18.3/bin/.gnome-shell-wrapped" sig=11
mai 13 14:00:36 luz3 kernel: do_general_protection: 3 callbacks suppressed
mai 13 14:00:36 luz3 kernel: traps: .gnome-shell-wr[1335] general protection ip:7f9bc3327801 sp:7ffd1a4e74d0 error:0 in libglib-2.0.so.0.4800.0[7f9bc32c3000+10c000]
mai 13 14:00:36 luz3 kernel: audit: type=1701 audit(1463140836.638:157): auid=1000 uid=1000 gid=100 ses=2 pid=1335 comm=".gnome-shell-wr" exe="/nix/store/cnn0qldaw3nfklq80ggs9vaypi8azvc2-gnome-shell-3.18.3/bin/.gnome-shell-wrapped" sig=11
mai 13 14:00:36 luz3 polkitd[913]: Unregistered Authentication Agent for unix-session:2 (system bus name :1.61, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
mai 13 14:00:36 luz3 gnome-session-binary[1259]: WARNING: Application 'gnome-shell.desktop' killed by signal 11
mai 13 14:00:36 luz3 gnome-session[1259]: gnome-session-binary[1259]: WARNING: Application 'gnome-shell.desktop' killed by signal 11
mai 13 14:00:39 luz3 gnome-session[1259]: current session already has an ibus-daemon.
```
- System: 16.09.git.565f319
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09.git.565f319

**Comment by jgillich** [comment]
If by "restart" you mean "crash", then yes, I also have that happen from time to time. Not just on NixOS, also on Fedora. Probably caused by bugs in upstream.

**Comment by kragniz** [comment]
How long has this been going on for you? I'm also running gnome shell and not seeing this.

**Comment by DamienCassou** [comment]
Louis Taylor <notifications@github.com> writes:

> How long has this been going on for you? I'm also running gnome shell
> and not seeing this.

I would say something like 2 months.

--
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
Jakob Gillich <notifications@github.com> writes:

> If by "restart" you mean "crash"

I mean "crash" and then "starts again" automatically. When this happens,
the window decorations disappear and reappear a few seconds later.

--
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jgeerds** [comment]
This issue is pretty old and addresses Gnome 3.18 (we're now at 3.26). To be honest, I experienced similar crashes with Gnome in Debian. I think it is mostly related to gnome shell extensions but sometimes there are of course bugs in gnome-shell (or NixOS). If you still encounter this issue, please deactivate all of your gnome shell extensions and check if the issue still occurs. If so, feel free to open this issue again.
