### ISSUE TITLE
mautrix python module incorrectly advertises python 3.7 support

### ISSUE THREAD

**Issue by chayleaf** [NixOS/nixpkgs#154437]
`mautrix` on py3.7 requires `typing_extensions` module ([source](https://github.com/mautrix/python/blob/master/requirements.txt)). `typing_extensions` isn't currently packaged for nix, so `mautrix` won't work on py3.7. It should either be packaged and added as an conditional dependency, or minimal version should be changed to py3.8.

**Comment by jonringer** [comment]
The issue template has this section, do you mind running the commands from it?:

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```


The exposed `pkgs.mautrix-*`  are using pyton3.9 on both unstable and 21.11.

Most likely, you're using an EOL release.

**Comment by pavlukivan** [comment]
I'm not using an EOL release, I just think it would be nicer to do it properly. You can reproduce it by doing `nix-shell -p python37.withPackages (pkgs: pkgs.mautrix)`. I do think it will most likely not affect anyone though.
