### ISSUE TITLE
request: vscode-extensions.rust-lang.rust

### ISSUE THREAD

**Issue by waynevanson** [NixOS/nixpkgs#154456]
**Project description**
Rust extension for Visual Studio Code

**Metadata**
* homepage URL: https://marketplace.visualstudio.com/items?itemName=rust-lang.rust
* source URL: https://github.com/rust-lang/vscode-rust
* license:  mit
* platforms: linux, darwin

**Comment by SuperSamus** [comment]
Isn't this extension deprecated in favor of rust-analyzer?

**Comment by ivan** [comment]
https://github.com/rust-lang/vscode-rust/issues/812 says `rust-lang.rust` is indeed being deprecated

@waynevanson I think you probably just wanted rust-analyzer instead? That's all you need for Rust in vscode. If not, @ me and I can reopen.

**Comment by waynevanson** [comment]
Your right, thank you.
