### ISSUE TITLE
Update Monitor (0.12.0)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#154578]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version:
desired version:

https://github.com/stsdc/monitor/releases/tag/0.12.0

###### Notify maintainers

maintainers:

###### Note for maintainers

@bobby285271 are you already working on it? if not i can do it

**Comment by bobby285271** [comment]
I have some exams to take tomorrow, so maybe I cannot open a PR in 17 hours.
Feel free to open one if you have done the update.

**Comment by davidak** [comment]
I just wanted to make sure you haven't started to work on it, so we don't do duplicate work.

I wish you great success with the exams!

**Comment by bobby285271** [comment]
Just also have a try on this, fails with `error adding symbols: DSO missing from command line`.

Actually I have no idea what happened so I just opened https://github.com/stsdc/monitor/issues/292, downstream workaround should be something like `NIX_LDFLAGS = "-lXext";` (seems to work).

Also I noticed that we maybe need `"-Dindicator-wingpanel=enabled"` in `mesonFlags`, haven't tested yet.

**Comment by davidak** [comment]
I'm already stuck at:

`meson.build:26:0: ERROR: C shared or static library 'XNVCtrl' not found`

Where you able to reference it from https://github.com/NixOS/nixpkgs/blob/0ffa5833d98094cb29534d3b97b5f472688462ff/pkgs/os-specific/linux/nvidia-x11/settings.nix#L16-L21 with passthru? On do we have to create a dedicated package for the library?

**Comment by davidak** [comment]
>downstream workaround should be something like `NIX_LDFLAGS = "-lXext";`, actually this seems to work, builds and launches.

i don't understand what it does, but it works

>Also I noticed that we maybe need `"-Dindicator-wingpanel=enabled"` in `mesonFlags`, haven't tested yet.

I noticed before that the indicators do not work. I'll try it.
