### ISSUE TITLE
KDE5: plasma 5.6 responds slowly

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#15450]
## Issue description

Yesterday I upgraded to Nix master just after the merge with staging. Plasma seems to respond very slow, buttons typically take half a minute before the response occurs. CPU usage is low. Applications behave good, there is no delay with them.

My NetworkManager passwords appear to be gone as well, since I have to enter them again. Actually, I think it's because kwallet doesn't appear to be prompted.

## Technical details

* System: NixOS `16.09.git.bb73e25`

I will try an upgrade to Plasma 5.6.4. and Applications 16.04.1.
cc @ttuegel

**Comment by ttuegel** [comment]
Plasma is pretty well-known for exposing graphics driver bugs. What type of graphics hardware do you have, and what drivers are you using? You may find other Plasma users with similar hardware are having the same experience. It may also help to change the rendering backend under `System Settings > Display and Monitor > Compositor`.

**Comment by FRidh** [comment]
Changing compositor settings doesn't seem to make a difference. I created a new user, and there the default session works just fine. 

It really appears to be as if something is blocking calls. It happens, and it happens fluently, but just half a minute after I pressed a button. 

It would at least appear that this is an issue for upstream.

**Comment by FRidh** [comment]
I removed a lot of dot files and now my session works good again. There is just a high CPU usage but that appears to be related to Baloo.
