### ISSUE TITLE
Questions / issues about cross-compiling

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#15461]
Hey,
I've been trying to do some cross-compiling and I have a few concerns about how the system works. Please excuse me if I got something wrong or the solution already exists.

**Issue 1**
I don't see a good way to conditionally do things only when the package is cross-compiled. I'm aware of crossAttrs but I don't think this is generally a solution. I think it should be possible to do this:

```
nativeBuildInputs = [foo bar] ++ optional crossCompiling [baz];
preConfigure = ''
  foo
'' + optionalString crossCompiling ''
  baz
'';
```

**Issue 2**
When I tried to use `nativeBuildInputs=[autoconf automake]` within `crossAttrs`, the build got broken because the configure script was no longer being passed the essential --build and --host options. I suppose the cross derivation wrapper doesn't consider this possibility.

**Issue 3**
I have seen `stdenv ? cross` used as a condition for cross compiling but this is not correct most of the time, because it is also true when the native package within a cross-stdenv is being compiled!

**Issue 4**
Often you need to do this:

```
configureFlags = "--with-foo=${foo} --with-bar=${bar}"
```

But you need to have the crossDrv passed when cross compiling. I'm pretty confident it will result in the native outputs being passed in case of a cross-compiled package. There should be a way to do this transparently so that crossDrv path is passed in case of cross-compiling. Actually I think this is the primary reason why cross-compiled _NixOS_ doesn't work - it just picks up the native builds of all packages.

**Comment by ambrop72** [comment]
Note, I think the only serious issue is that it is (apparently) not possible to specify different build inputs (all 4 kinds) depending on whether we're cross-compiling. I say this after looking at [makeStdenvCross](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/adapters.nix#L59). The modified `mkDerivation` will work just with the `*buildInputs` that were passed (which cannot possibly be dependent on cross-compiling) and also doesn't seem to account properly for any `*buildInputs` in `crossAttrs`.

**Comment by ambrop72** [comment]
An example would be packages that need to have their own native build in `nativeBuildInputs` when cross-compiling, because it uses some of its own binaries during the build, which it doesn't know how to build when cross-compiling.

**Comment by wkennington** [comment]
For your last issue, just set `selfNativeBuildInput = true;`

**Comment by vcunat** [comment]
I analyzed the worst of this on https://github.com/NixOS/nixpkgs/issues/14965.

I think that during build time at least you can reliably detect cross-compilation by `if [ -z "$crossConfig" ]; then...`

**Comment by Ericson2314** [comment]
1: Do `hostPlatform != buildPlatform` or similar.

3: I absolutely agree and that attribute is on its way out.  `hostPlatform != buildPlatform` is more correct and more clear.

4: Cross derivations are now the default so this issue is fixed.

That just leaves 2. I didn't think we automatically passed `--build` and the moment, just `--host`. I'll hopefully be cleaning up that soon.

**Comment by Ericson2314** [comment]
Number 2 was probably due to `crossAttrs.configureFlags` wiping out the hack, not the extra `nativeBuildInputs`. Those are now added anyways, controlled by `configurePlatforms`. See https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/make-derivation.nix#L28-L30.

That means all 4 are solved and this can be closed!
