### ISSUE TITLE
autorandr: upsteam broken and unmaintained

### ISSUE THREAD

**Issue by seschwar** [NixOS/nixpkgs#15466]
## Issue description

The autorandr package is affected by wertarbyte/autorandr#38 making the program unable to apply its saved profiles and therefore basically useless.

There is a well maintained [fork](https://github.com/phillipberndt/autorandr)/CLI compatible rewrite in Python which fixes this. However it no longer supports `disper`; only `xrandr`.

I'd like to switch the autorandr package to the fork. What should be about the `disper` support? Just drop it or crate a separate package for `autodisper` from the old autorandr?

### Steps to reproduce

    $ nix-env -i autorandr
    $ autorandr --save default
    $ autorandr --change --force
    /nix/store/k916lwh2rr91zznmzvpyl6zl5cmfzqa4-xrandr-1.4.3/bin/xrandr: failed to parse 'x' as a position
    Try '/nix/store/k916lwh2rr91zznmzvpyl6zl5cmfzqa4-xrandr-1.4.3/bin/xrandr --help' for more information.

## Technical details

* System: 16.03.769.f98d57b (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.769.f98d57b"

**Comment by rycee** [comment]
Thanks for bringing this up.

I'd support updating autorandr to the fork (I'm already using the fork on my system) and either delete the old package or put it as `autorandr-old` or something for a while.

**Comment by rycee** [comment]
The autorandr package was switched over to the phillipberdt fork when #16439 was merged. I have now also merged it into the 16.03 branch. Even though it uses the "legacy" branch, which is not based on Python, I think this resolves this issue.

Porting the package to the Python branch remains as an open item but I suppose that could be done under some other ticket?

I'll close this one, if you disagree then please reopen.
