### ISSUE TITLE
cdemu: missing Dbus service (regression)

### ISSUE THREAD

**Issue by vvs-** [NixOS/nixpkgs#154613]
### Describe the bug
There is no Dbus service file in the derivation outputs. This prevents `cdemu-daemon` from starting on demand. It works if it was started manually beforehand.

### Steps To Reproduce
1. run `cdemu status`

### Expected behavior
There should be a message about device slot 0 not loaded. But instead there is an error: `ERROR: Failed to acquire daemon interface version (this most likely means your daemon is out-of-date): g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name net.sf.cdemu.CDEmuDaemon was not provided by any .service files (2)`

### Additional context
This is a regression from at least NixOS 20.09 where this file was present. Apparently some `nixpkgs` defaults were changed since then.

### Notify maintainers
@bendlas

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bendlas** [comment]
Thanks for the report, I've also already wondered what broke ...

I think what may have changed is that cdemu has stopped installing a service file. See Section 14 in [its README](https://github.com/cdemu/cdemu/tree/master/cdemu-daemon)

Fortunately, it still provides [examples](https://github.com/cdemu/cdemu/tree/master/cdemu-daemon/service-example), so it shouldn't be too hard to generate a service file on our own.

From a quick glance, I see two ways:
1) rely on the nixos module, to have dbus activate a systemd service, as in the example
2) come up with a dbus - only solution, similar as before

**Comment by vvs-** [comment]
> I think what may have changed is that cdemu has stopped installing a service file. See Section 14 in its README

Yes, according to its git history it was removed in cdemu-daemon 3.2.5.

> 1. rely on the nixos module, to have dbus activate a systemd service, as in the example

I believe this should be the most straightforward and flexible solution. Also, this is actually recommended by upstream.

**Comment by cirno-999** [comment]
Also an issue on my machine.
![image](https://user-images.githubusercontent.com/73712874/150698243-a234df61-f575-45b9-99de-43c7c03db650.png)
```
[cirno@berlin:~]$ cdemu status
ERROR: Failed to acquire daemon interface version (this most likely means your daemon is out-of-date): g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name net.sf.cdemu.CDEmuDaemon was not provided by any .service files (2)
```

```
[cirno@berlin:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixos-21.11.334921.8588b14a397, unstable-22.05pre334855.29d1f6e1f62"`
 - channels(cirno): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by keenanweaver** [comment]
Experiencing this as well. New to NixOS, so I'm not sure how much I could contribute to resolve this.

**Comment by bendlas** [comment]
Just in case somebody stumbles upon this, to whom the workaround is not apparent, before a contributor got around to fixing this:

After running `cdemu-daemon` in a separate terminal, you can use CDEmu normally.

**Comment by TheOddler** [comment]
I just got this problem too, tried starting cdemu-deamon manually, but then got:

```
~ 
❯ cdemu-daemon 
Starting CDEmu daemon with following parameters:
 - config file: (null) (exists: 0)
 - num devices: 1
 - control device: /dev/vhba_ctl
 - audio driver: null
 - bus type: session
 - default CDEmu debug mask: 0x0
 - default libMirage debug mask: 0x0

Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)cdemu0: Kernel I/O: failed to open control device /dev/vhba_ctl: Permission denied!
cdemu: Daemon: failed to start device #0!
cdemu: Daemon: failed to create device!
Daemon initialization and start failed!

~ 
❯ sudo cdemu-daemon 
[sudo] password for pablo: 
Starting CDEmu daemon with following parameters:
 - config file: (null) (exists: 0)
 - num devices: 1
 - control device: /dev/vhba_ctl
 - audio driver: null
 - bus type: session
 - default CDEmu debug mask: 0x0
 - default libMirage debug mask: 0x0

Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)cdemu0: Mapping: device mapping (SCSI generic) for device #0 could not be determined; device mapping info for this device will not be available
```

Not really sure what to try next :sweat:

**Comment by bendlas** [comment]
@TheOddler that looks like you don't have the cdemu kernel module loaded.

Do you have [`programs.cdemu.enable = true`](https://search.nixos.org/options?channel=unstable&show=programs.cdemu.enable&from=0&size=50&sort=relevance&type=packages&query=cdemu) and added yourself to the `cdrom` group?

Also check `lsmod | grep vhba`

**Comment by TheOddler** [comment]
Hey! Yes, I have `programs.cdemu.enable = true` and `users.users.pablo.extraGroups = [... "cdrom" ...]`

And:

```
❯ lsmod | grep vhba
vhba                   32768  1
scsi_mod              274432  3 vhba,libata,sr_mod
```

Not sure what this tells me though? Does that look OK?

**Comment by bendlas** [comment]
Interesting. `lsmod` shows the module to be loaded, that's fine.

So the `groups` command already shows you as part of `cdrom` and also `/dev/vhba_ctl` is owned by group cdrom? And you still get permission denied?

**Comment by vvs-** [comment]
`/dev/vhba_ctl` should be owned by group `cdrom` _and_ also have group permissions `rw`.

**Comment by bendlas** [comment]
would appreciate if anybody could test the PR. there are issues with the tray icon not showing, due to xdg resources, but the dbus service should be functional now.

**Comment by Thornskade** [comment]
I have this exact issue on the Steam Deck...

**Comment by Shoun2137** [comment]
Aight, so I thought I might chime into this issue for all those poor souls that have problems with this exact problem:

`cdemuX: Mapping: device mapping (SCSI generic) for device #X could not be determined; device mapping info for this device will not be available`

And when you check with `cdemu device-mapping`:
```
$ cdemu device-mapping
Device mapping:
DEV   SCSI CD-ROM     SCSI generic   
0                     /dev/sg4       
1                     /dev/sg5       
```
Notice that `SCSI CD-ROM` is empty when it should be mapped to:
```
$ cdemu device-mapping
Device mapping:
DEV   SCSI CD-ROM     SCSI generic   
0     /dev/sr0        /dev/sg4       
1     /dev/sr1        /dev/sg5       
```

**Solution that worked for me:**
Check if you have any .conf files in `/etc/modprobe.d/*.conf` that block `cdrom`, `vhba`, `sr_mod`,  `sg`,  `libata` modules from loading. This is common problem nowadays, because of kernel hardening and stuff, so people/distro packagers could disable those for this reason. 

Sorry for necrobumping, but this is the only github issue that somewhat references this error above.

**Comment by Inqurity** [comment]
Also still having this three years later

**Comment by bendlas** [comment]
> Also still having this three years later

@Inqurity 

- are you sure you're seeing the same error message?
- do you see the same issue when running `cdemu-daemon` yourself, in a separate terminal?

**Comment by Inqurity** [comment]
> > Also still having this three years later
> 
> [@Inqurity](https://github.com/Inqurity)
> 
> * are you sure you're seeing the same error message?
> * do you see the same issue when running `cdemu-daemon` yourself, in a separate terminal?

It was not, in fact, the same error, and was caused by me not rebooting after adding my user to the "cdrom" group. Sorry for wasting time.
