### ISSUE TITLE
virsh/qemu:  The -accel and "-machine accel=" options are incompatible

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#154710]
### Describe the bug
I did update my nixos unstable installation on monday, in which I also use virsh/qemu. However I noticed now that I can't start VMs aymore using `virsh start VM`

### Steps To Reproduce
1. Update to latest unstable branch
2. Run a preexisting VM (not sure if new vms are affected also) using `virsh start VM`
3. You get an error:
```error: Failed to start domain 'VM'
error: internal error: process exited while connecting to monitor: 2022-01-12T06:56:56.144411Z qemu-system-x86_64: The -accel and "-machine accel=" options are incompatible
```

I looked at the xml file but I could not find but I could not find any accel or machine entries. Not sure where qemu gets this from.

### Expected behavior
The VM should be started using `virsh start VM`

### Notify maintainers
@eelco @qyliss

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.90, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(hyper): `"nixos-21.11pre326640.e544ee88fa4"`
 - channels(root): `"nixos-22.05pre344851.0ecf7d41481"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sjau** [comment]
This seems to be related:

https://listman.redhat.com/archives/libvir-list/2021-January/msg00536.html

Reverting to 5b091d4fbe3 makes virsh/qemu run again.

**Comment by alyssais** [comment]
If I'm reading that right, a qemu-kvm script is no longer required, and can just be a symlink to the appropriate QEMU binary for the architecture.  That's what Fedora's doing now, at least (verified in a container).  Perhaps we should be looking at a similar change.

**Comment by peterhoeg** [comment]
libvirtd is effectively broken on unstable as a consequence of this. I'll take a look as soon as I can.
