### ISSUE TITLE
Packaging request: wldash

### ISSUE THREAD

**Issue by coolshaurya** [NixOS/nixpkgs#154772]
**Project description**

A dashboard/launcher/control-panel thing for Wayland.

![a screenshot of wldash](https://user-images.githubusercontent.com/32027323/149168478-97f4dd75-0c9c-4bf5-87ca-e5413ba509c5.png)

**Metadata**

* homepage URL: https://github.com/kennylevinsen/wldash
* source URL: https://github.com/kennylevinsen/wldash
* license: GPL 3.0
* platforms: linux, only wayland, only wlroots compositors

**Comment by teto** [comment]
it's available in https://github.com/nix-community/nixpkgs-wayland

**Comment by tomodachi94** [comment]
Added by https://github.com/NixOS/nixpkgs/pull/313098, closing 🙂
