### ISSUE TITLE
dhall-toml

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#154762]
**Project description**
A CLI that converts dhall expressions to toml.

**Metadata**

* homepage URL: https://github.com/dhall-lang/dhall-haskell
* source URL: https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-toml
* license: bsd
* platforms: unix, linux, darwin
* maintainers: @Gabriel439

**Comment by Gabriel439** [comment]
This is mainly blocked on upgrading `dhall`.  The default `dhall` version is 1.39.0 and `dhall-toml` requires `dhall` version 1.40.1 or newer
