### ISSUE TITLE
[RFC] PHP should be compiled with ZTS or not ?

### ISSUE THREAD

**Issue by drupol** [NixOS/nixpkgs#154774]
Hi,

I'm opening this RFC hoping to gather comments from the Apache and PHP maintainers.

We know that there are two ways to compile the PHP interpreter (_yeah there are many others but in this thread, only those flags are relevant_):
* `NTS`: Non-Thread Safe
* `ZTS`: Zend-Thread Safe

Me, as a PHP developer, I remember these rules:

* When PHP is meant to be used with `mod_php` in Apache -> it's better to use `ZTS`
* When PHP is meant to used with CGI/FASTCGI/Nginx/CommandLine -> It's better `NTS`

The default PHP in Nixos is built with `ZTS` and I think it should be `NTS`. `NTS` is also the default in many other distributions.

What's your point of view about that?

Relevant links:
* https://externals.io/message/65332
* https://github.com/oerdnj/deb.sury.org/issues/1419
* https://github.com/fossar/nix-phps/issues/63

CC:
* Apache maintainers: @lovek323
* PHP maintainers: @aanderse @etu @globin @ma27 @talyz

**Comment by jtojnar** [comment]
Even if we change this line to false:

https://github.com/NixOS/nixpkgs/blob/b2737d4980a17cc2b7d600d7d0b32fd7333aca88/pkgs/development/interpreters/php/generic.nix#L53

PHP will still be built with ZTS due to

https://github.com/php/php-src/blob/5b01c4863fe9e4bc2702b2bbf66d292d23001a18/sapi/apache2handler/config.m4#L119

```
$ nix shell -f . apacheHttpd.dev -c sh -c '$(apxs -q SBINDIR)/$(apxs -q TARGET) -V' | grep threaded
  threaded:     yes (fixed thread count)
```

**Comment by talyz** [comment]
Yeah, I guess the question is if we should disable apxs2 by default and maybe provide a separate package with it enabled.

**Comment by drupol** [comment]
> Yeah, I guess the question is if we should disable apxs2 by default and maybe provide a separate package with it enabled.

Could be an idea yeah !

**Comment by drupol** [comment]
Do you have something to say here @lovek323 ?

**Comment by lovek323** [comment]
Like you say, it would be great to be able to have the CLI `php` binary using NTS by default, if apxs is the only thing that's blocking this, a separate package for that sounds good to me.

**Comment by drupol** [comment]
@lovek323 Thanks for your input !

@jtojnar how about making 2 packages:
- `php`: This would be the default PHP package, without `apxs2support` and `NTS`
- `php-apache`:  This would be the PHP package, with `apxs2support` and `ZTS`

WDYT?

**Comment by aanderse** [comment]
I'll mention that it is 2022 and people really shouldn't be using `mod_php` anymore... we have `php-fpm` which is almost always a better solution. @drupol I think your proposed solution is reasonable :+1:

https://cwiki.apache.org/confluence/display/httpd/PHP

**Comment by drupol** [comment]
> I'll mention that it is 2022 and people really shouldn't be using `mod_php` anymore... we have `php-fpm` which is almost always a better solution. @drupol I think your proposed solution is reasonable :+1:
> 
> https://cwiki.apache.org/confluence/display/httpd/PHP

I definitely agree and this is why I opened this rfc.

**Comment by etu** [comment]
Well, the changes is merged now :slightly_smiling_face: :tada:

**Comment by drupol** [comment]
Excellent :)
