### ISSUE TITLE
manpages: empty $out/bin

### ISSUE THREAD

**Issue by KAction** [NixOS/nixpkgs#154761]
```
$ nix-build -A manpages
/nix/store/l74pj6cxz94yc1lmwkm4c36nkpw6yj0b-man-pages-5.13
$ ls ./result/
bin
share
$ ls -a ./result/bin/
.
..
```

**Comment by alyssais** [comment]
I suspect this is necessary to get man to find it correctly with nix-shell -p manpages.  Can you test?

**Comment by Artturin** [comment]
its intentional https://github.com/NixOS/nixpkgs/blob/f9501af60e6241bbab8be023413d7a992a91162f/pkgs/data/documentation/man-pages/default.nix#L20
