### ISSUE TITLE
Adguardhome service fails

### ISSUE THREAD

**Issue by legendofmiracles** [NixOS/nixpkgs#154775]
## Issue description

I added:
```
services.adguardhome = {
  enable = true;
};
```
to my config and rebuilt. After a few minutes of downloading, it printed this error, and quit:

```
2022/01/12 14:23:54.220384 [info] AdGuard Home, version v0.107.0
2022/01/12 14:23:54.228677 [info] home.upgradeSchema0to1(): called
2022/01/12 14:23:54.228912 [info] deleting /nix/store/36xs8gfxdkfrwl44y4vj2krmscy1a8lf-adguardhome-0.107.0/bin/dnsfilter.txt as we don't need it anymore
2022/01/12 14:23:54.229405 [info] home.upgradeSchema1to2(): called
2022/01/12 14:23:54.229518 [info] deleting /nix/store/36xs8gfxdkfrwl44y4vj2krmscy1a8lf-adguardhome-0.107.0/bin/Corefile as we don't need it anymore
2022/01/12 14:23:54.230035 [info] home.upgradeSchema2to3(): called
2022/01/12 14:23:54.230683 [fatal] dns configuration is not a map
```

I'm running latest nixos-unstable, and the machine is a x86_64-linux, although the same is also happening in `qemu-aarch`.

### Steps to reproduce

Use latest nixos-unstable (currently `b2737d4980a17cc2b7d600d7d0b32fd7333aca88`)

Add the before mentioned code to your config

Rebuild your system

## Technical details

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `""`
 - channels(nix): `""`
 - nixpkgs: `/nix/store/0gaazn04dikcwqrwrw9y0h4x8rmrn3js-1hdyp90ilq8gksc56dryg991kq3pc9bb-source`
```

Maintainers: @numkem and @iagocq

**Comment by CRTified** [comment]
That's probably caused by my PR #152029. I probably should add a check on whether `service.adguardhome.settings = {}`.

**Comment by CRTified** [comment]
In theory, this should work as a workaround if you copy the appropriate values from your original (stateful) `/var/lib/AdGuardHome/AdGuardHome.yaml`:
```nix
  services.adguardhome.settings = {
    dns = {
      bind_host = "SET_TO_YOUR_DNS_IP";
      bootstrap_dns = "SET_TO_YOUR_BOOTSTRAP_DNS";
    };
};
```

As you can see in the original PR and the fix, the problem was that `services.adguardhome.settings` needs to describe a minimal *working* file for adguard, but an empty file does not work. It requires at least the two settings `dns.bind_host` and `dns.bootstrap_dns`.
