### ISSUE TITLE
variety doesn't work after bash update

### ISSUE THREAD

**Issue by linsui** [NixOS/nixpkgs#154840]
### Describe the bug

Recently variety stops working on NixOS. Pictures are downloaded well but the wallpaper can't be changed and can only be set in system setting. That's because of the hardcoded shebang which is taken from `${stdenv.shell}` on the first installation. So when the bash is updated the script can't find it. It should be set as something like `#!/usr/bin/env bash`. Not sure if this is a nixos bug.

### Steps To Reproduce
1. Install variety
2. Update bash

### Expected behavior
It works after the bash update.

### Notify maintainers

@p3psi-boo @AndersonTorres @zfnmxt

**Comment by AndersonTorres** [comment]
IIRC now we use `runtimeShell`.
