### ISSUE TITLE
Octave audio processing requires libsndfile

### ISSUE THREAD

**Issue by tmrts** [NixOS/nixpkgs#15494]
## Issue description
Octave needs `libsndfile` library to process audio (e.g. `audioread`).

## Technical details

* System: NixOS: `16.09pre83100.25e3c09 (Flounder)`
* Nix version: `1.11.2`
* Nixpkgs version: `16.09pre83100.25e3c09`

**Comment by FRidh** [comment]
See #15501

**Comment by tmrts** [comment]
Closing in favor of #15501
