### ISSUE TITLE
meson: update above 0.59.0 (0.61.0)

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#154956]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: meson

current version: 0.57.1
desired version: [0.61.0](https://pypi.org/project/meson/#history)

###### Notify maintainers

maintainers:
@brandonedens

###### Note for maintainers

Please tag this issue in your PR.

**Comment by zowoq** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/154172, currently in `staging-next`.
