### ISSUE TITLE
paxmarks aren't applied

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#15492]
For example, `firefox` is supposed to have the `m` flag, but `paxctl -v` reports
```
- PaX flags: -------x-e-- [/nix/store/...-firefox-unwrapped-46.0.1/lib/firefox-46.0.1/firefox]
        RANDEXEC is disabled
        EMUTRAMP is disabled
```

Using `paxctl` directly works, however. I previously believed flags didn't work because ELF header markings are disabled in the default grsecurity config, but looks like they aren't applied at all.

**Comment by joachifm** [comment]
Unsure how to debug this ... I'm fairly sure the problem is that the `paxmark` stub isn't being replaced by the one defined by `paxctl`'s setup hook. For some reason, the setup hook appears to not be sourced.

I'm tempted to replace uses of paxmark with
```nix
let # syntax highlighting
postFixup = ''
  # ...
'' + optionalString stdenv.isLinux "paxctl -czexm $out/bin/foo";
```
which does work, per my testing.

**Comment by AmatCoder** [comment]
I can confirm that deleting the dummy implementation of the paxmark function on
`pkgs/stdenv/generic/setup.sh` ([here](https://github.com/NixOS/nixpkgs/blob/3e387c3e005c87566b5403d24c86f71f4945a79b/pkgs/stdenv/generic/setup.sh#L374)) flags are applied, so it isn't being overwritten by setup hook from `paxctl` package.

**Comment by joachifm** [comment]
My experiments indicate that bash normally overwrites existing function definitions, I don't understand why that doesn't happen here. It looks like it *should* work but doesn't ...

**Comment by vcunat** [comment]
From reading `setup.sh` it seems clear the function is defined too late, after setup hooks are sourced. I wonder if this has ever worked...

**Comment by joachifm** [comment]
@vcunat oh, so the stub actually overwrites the real function? IIRC, there have been no relevant changes after the paxmark mechanism was moved to the paxctl setup hook, so I think this may have been broken ever since.

**Comment by vcunat** [comment]
It seems so; I was under the impression some people used this things, but apparently not.

**Comment by joachifm** [comment]
I've been slowly trying to get it into working shape, this is the only remaining stumbling block, that I know of. If you're right, the fix should be simple enough and we may finally get a working grsec desktop. Thanks.

**Comment by joachifm** [comment]
@vcunat I have a fix ready at https://github.com/joachifm/nixpkgs/commit/54109fc52827384b4ee9702f72beaf8493413e6c, is it okay to pick it into `staging` or should I wait until libxml2 has completed (I suspect that is a smaller rebuild, so it makes sense for me to wait ...)

**Comment by vcunat** [comment]
Wait for libxml2, please. It really is a significantly smaller rebuild, and more urgent (considering noone has noticed broken PaX for so long).

**Comment by joachifm** [comment]
@vcunat it's okay to pick now, right?

**Comment by vcunat** [comment]
Yes.
