### ISSUE TITLE
gzdoom (4.7.1) doesn't run due to kdialog error

### ISSUE THREAD

**Issue by nixinator** [NixOS/nixpkgs#154918]
### Describe the bug

running gzdoom results in `sh: kdialog: command not found` and quits.

### Steps To Reproduce
1. nix-shell -p gzdoom
2. gzdoom

### Expected behavior
I enter hell and banish demons.

### Additional context
https://github.com/flathub/org.zdoom.GZDoom/issues/10

mentioned here.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.05.20220103.88579ef (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(user): `"nixgl, stable-21.05.4709.88579effa7e"`
 - channels(root): `"nixos-21.11pre332093.7fad01d9d5a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SaltyKitkat** [comment]
I know nothing about gzdoom and new to NixOS. But I've tried to fix this by doing something like this:
```
diff --git a/pkgs/games/gzdoom/default.nix b/pkgs/games/gzdoom/default.nix
index e38294ff401..670a99dd40a 100644
--- a/pkgs/games/gzdoom/default.nix
+++ b/pkgs/games/gzdoom/default.nix
@@ -1,4 +1,4 @@
-{ lib, stdenv, fetchFromGitHub, cmake, makeWrapper, openal, fluidsynth
+{ lib, stdenv, fetchFromGitHub, substituteAll, kdialog, cmake, makeWrapper, openal, fluidsynth
, soundfont-fluid, libGL, SDL2, bzip2, zlib, libjpeg, libsndfile, mpg123
, game-music-emu, pkg-config, copyDesktopItems, makeDesktopItem }:

@@ -83,6 +83,10 @@ let
runHook postInstall
'';

+    fixupPhase = ''
+      wrapProgram $out/lib/gzdoom/gzdoom --prefix PATH ":" ${lib.makeBinPath [ kdialog ]}
+    '';
+
meta = with lib; {
homepage = "https://github.com/coelckers/gzdoom";
description =
```
The problem seems solved.
```
$ gzdoom
GZDoom <unknown version> -  - SDL version
Compiled on Jan  1 1980

OS: NixOS 22.05 (Quokka), Linux 5.15.19-xanmod1-tt on x86_64
M_LoadDefaults: Load system defaults.
```
But soon it pops up saying that 

> Cannot find a game IWAD (doom.wad, doom2.wad, heretic.wad, etc.).
>Did you install GZDoom properly? You can do either of the following:
>
>1. Place one or more of these wads in ~/.config/gzdoom/.
>2. Edit your ~/.config/gzdoom/gzdoom.ini and add the directories of your
iwads to the list beneath [IWADSearch.Directories]

Any idea about this?

**Comment by nixinator** [comment]
Yeah, you need the games data files, I have them, and i will pull from your branch and give it a try.

Thanks for looking at this..

and above all...


Welcome to Nixos..

**Comment by SaltyKitkat** [comment]
Got it.
I've pushed my branch and
Thank you for your reply!

**Comment by abathur** [comment]
Did this fix get confirmed?

**Comment by ThibaultLemaire** [comment]
@SaltyKitkat I couldn't find your branch, so I reconstructed a commit from your comment and submitted a PR.

The fix seems to work, but the game I'm trying it on does not, so I cannot say for sure everything is good. (Though I believe that's a different issue.)

For the impatient, you should now be able to run gzdoom with (if you have flakes enabled):

``` sh
nix shell github:ThibaultLemaire/nixpkgs/fix-gzdoom-kdialog-not-found#gzdoom
```
