### ISSUE TITLE
Setting src = ../../.; sourceRoot = "subproject" results in file system permission errors

### ISSUE THREAD

**Issue by moretea** [NixOS/nixpkgs#15495]
## Issue description

I encountered this error when I was building a rust crate with the `rustPlatform`, but have reduced it to a problem in `stdenv.mkDerivation`.

Setting `src = ../../.; sourceRoot = "<dir_where_this_file_is>";` results in permission errors.
#### Rust story

I have a hierarchy of crates, that will form safe rust bindings to `libzfs`.

```
<GITROOT>/zfs
<GITROOT>/zfs/zfs-sys
<GITROOT>/zfs/nvpair
<GITROOT>/zfs/nvpair/nvpair-sys
```

I'd rather not run the unit tests for `zfs-sys` and `zfs` crates on my laptop, so I planned to use NixOS' vm tests. 

Therefore, I need to build the `zfs-sys` crate using the `rustPlatform`. However, it depends on `nvpair`, and for the moment, the `Cargo.toml` in `zfs-sys` uses a relative path (`../nvpair/`) to point to that dependency.

I thought I solved this by creating a nix file in `<GITROOT>/zfs/zfs-sys`, and setting `src = ../../.; sourceRoot = "zfs-sys";`. AFAICS, this should just work. Unfortunately, I'm getting `Operation not Permitted` errors from `chmod`.

I can skip these errors by setting `dontMakeSourcesWritable`, but the rustPlatform actually modifies source files. 
### Steps to reproduce

I've created a repository https://github.com/moretea/nixos-rust-platform-sourceroot-issue that demonstrates this issue.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  `
  $ nixos-version
  16.09pre83100.25e3c09 (Flounder)
  `
- Nix version: (run `nix-env --version`)
  `
  $ nix-env --version
  nix-env (Nix) 1.11.2`
  `
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  `
  $ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
  "16.09pre78286.0bf8a1a"
  `

**Comment by dpc** [comment]
@moretea Why is this closed?  I think I'm hitting the same issue.

**Comment by moretea** [comment]
Sorry, I don't remember the details. I abandoned this library in any case.

**Comment by minijackson** [comment]
I've had a similar issue implementing #63655, where the command-line utility, whose crate is named "sequoia-tool", is in the `/tool` inside the git repository. I've solved it by simply putting `cargoBuildFlags = [ "--package=sequoia-tool"];` in the derivation.
