### ISSUE TITLE
gitlab - security update to 14.6.2

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#154960]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 14.6.1
desired version: 14.6.2

###### Notify maintainers

maintainers:
@fpletz @globin @krav @talyz @yayayayaka @yuka

###### Note for maintainers

https://about.gitlab.com/releases/2022/01/11/security-release-gitlab-14-6-2-released/

Maybe the Maintainers should subscribe gitlab's security announcements

**Comment by yayayayaka** [comment]
Thanks for the hint. Will update it in a second.
