### ISSUE TITLE
Plasma 5:notification buttons/textbox not working

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#155046]
### Describe the bug
If I get a notification with buttons I can't press those buttons to interact with it

### Steps To Reproduce
1. Recive a notification from your cell via KDE connect
2. Click on a button on the notification
3. See no iteraction, the notification does not even disappear

### Expected behavior
The notification disappear and the described action happen

### Notify maintainers

@NixOS/qt-kde 
### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/store/3c249himjn7sh3cwnapmh5qgrnmd42xg-source`

**Comment by mrhanman** [comment]
I am also having this issue

**Comment by peterhoeg** [comment]
Is this still a problem? I'm able to interact with the notifications just fine.

**Comment by peterhoeg** [comment]
Closing as it's working fine here.
