### ISSUE TITLE
Can't start VLC on Wayland

### ISSUE THREAD

**Issue by jbuchermn** [NixOS/nixpkgs#155092]
### Describe the bug
Packaged VLC does not seem to support wayland.

### Steps To Reproduce
1. Install vlc
2. Start with `QT_QPA_PLATFORM=wayland vlc` on e.g. sway
3. VLC opens as a XWayland window

### Expected behavior
VLC opens as a Wayland native window

### Screenshots
Not applicable

### Additional context
Possibly related to VLC not depending on qtwayland.

### Notify maintainers
@AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.91, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

EDIT: Typo

**Comment by AndersonTorres** [comment]
It is strange. I built it and verified, it is not linked with QT libraries even if they are put as inputs.

**Comment by jbuchermn** [comment]
Is [qtwayland](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/modules/qtwayland.nix) also pulled in as an input?

**Comment by AndersonTorres** [comment]
Nope. Working on it now.

**Comment by AndersonTorres** [comment]
Can you test the patch?

**Comment by jbuchermn** [comment]
Works like a charm, thanks a lot! :)

**Comment by haizaar** [comment]
I'm on NixOS 23.05 and discovered that vlc prefers to use XWayland if `DISPLAY` var is set. If I unset `DISPLAY` then vlc starts in Wayland mode. 

Does anyone know how to make it to start on Wayland by default?

**Comment by haizaar** [comment]
For now I hacked it with:

```nix
environment.systemPackages = with pkgs; [
    ...
    (pkgs.symlinkJoin {
      name = "vlc";
      paths = [ pkgs.vlc ];
      buildInputs = [ pkgs.makeWrapper ];
      postBuild = ''
        wrapProgram $out/bin/vlc \
          --unset DISPLAY
      '';
    })
];
```
Special thanks to https://nixos.wiki/wiki/Nix_Cookbook#Wrapping_packages

**Comment by AndersonTorres** [comment]
Well, if this is hardcoded on VLC, there is nothing to do (besides maybe searching some hidden `--force-wayland-and-please-ignore-xwayland-at-all-costs` commandline flag).

**Comment by MahtoSujeet** [comment]
VLC still opening with xwayland, started with `QT_QPA_PLATFORM=wayland vlc`
VLC version - 3.0.20
OS - Arch linux 6.6.7

**Comment by cmm** [comment]
The "use $DISPLAY if set, $QT_QPA_PLATFORM be damned" behavior is apparently just what QT does, and is not specific to VLC

**Comment by haizaar** [comment]
Here is the updated wrap that also addresses the desktop file
```nix
    # VLC starts on XWayland if DISPLAY is set (which we need to have for legacy apps)
    # Wrap it
    (pkgs.symlinkJoin {
      name = "vlc";
      paths = [ pkgs.vlc ];
      buildInputs = [ pkgs.makeWrapper ];
      postBuild = ''
        wrapProgram $out/bin/vlc \
          --unset DISPLAY
        mv $out/share/applications/vlc.desktop{,.orig}
        substitute $out/share/applications/vlc.desktop{.orig,} \
          --replace-fail Exec=${pkgs.vlc}/bin/vlc Exec=$out/bin/vlc
      '';
    })
```
