### ISSUE TITLE
xxHash derivation should include cmake support

### ISSUE THREAD

**Issue by foolnotion** [NixOS/nixpkgs#155007]
### Describe the bug
Currently the xxHash package only installs a pkg-config file, however it would be really useful if it could also install cmake support files. There are provided by upstream and are already used by e.g. vcpkg. 

### Steps To Reproduce
1. install xxHash
2. CMake support is missing
3. 

### Expected behavior
Cmake support files are installed for xxHash.

### I have made my own derivation of xxHash which looks like this:
```nix
{
  lib,
  stdenv,
  fetchFromGitHub,
  cmake,
  buildXXHSum ? false,
  buildSharedLibs ? true
}:

stdenv.mkDerivation rec {
  pname = "xxhash";
  version = "0.8.1";

  src = fetchFromGitHub {
    owner = "Cyan4973";
    repo = "xxHash";
    rev = "v${version}";
    sha256 = "sha256-2WoYCO6QRHWrbGP2mK04/sLNTyQLOuL3urVktilAwMA=";
  };

  nativeBuildInputs = [ cmake ];

  configurePhase = ''
    mkdir build
    cmake -S . -B ./build ./cmake_unofficial \
      -DCMAKE_BUILD_TYPE=Release \
      -DXXHASH_BUILD_XXHSUM=${if buildXXHSum then "ON" else "OFF"} \
      -DBUILD_SHARED_LIBS=${if buildSharedLibs then "ON" else "OFF"} \
      -DCMAKE_INSTALL_PREFIX=$out
    '';

  buildPhase = ''
    cmake --build build -j
    '';

  installPhase = ''
    cmake --install build
    '';

  meta = with lib; {
    description = "Extremely fast non-cryptographic hash algorithm.";
    homepage = "https://cyan4973.github.io/xxHash/";
    license = licenses.bsd2;
    platforms = platforms.all;
  };
}
```

I think it would be good if CMake support is included with the official package. Perhaps the above could be integrated with the existing derivation.

### Notify maintainers
@trofi

**Comment by trofi** [comment]
Yeah, installing cmake files makes sense. I'm slightly worried that `cmake` build system itself is considered unossicial by `xxHash`'es CI: https://github.com/Cyan4973/xxHash/blob/dev/.github/workflows/ci.yml#L247. Let's see if we can just install extra `.cmake` file using existing `Makefile`.

**Comment by trofi** [comment]
Filed https://github.com/Cyan4973/xxHash/issues/674 to ask if we can make `*.cmake` installation build system-agnostic.

**Comment by foolnotion** [comment]
hi @trofi thanks for the effort. I think it should be easy for them to add a new rule in the Makefile. Looking at https://github.com/microsoft/vcpkg/blob/master/ports/xxhash/vcpkg.json I think the unofficial cmake support is solid too.

**Comment by RasmusRendal** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/163279.

**Comment by Mindavi** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/177851
