### ISSUE TITLE
Update TLP to 1.5.0

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#155032]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: tlp

current version: 1.4.0
desired version: 1.5.0

###### Notify maintainers

maintainers: @abbradar @lovesegfault 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment]
Fixed in #156418
