### ISSUE TITLE
XFCE: Remove libglade dependency

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#155160]
`/pkgs/desktops/xfce/default.nix` still references `libglade`, which is primed for removal. I don't know anything about XFCE, so I thought it'd be better to ask first before ripping it out.

Pinging @romildo and @AndersonTorres in the hope of having aimed correctly ^^

**Comment by AndersonTorres** [comment]
I am not actively working in XFCE anymore.
If I remember correctly, libglade is mostly optional. Just go ahead and try to remove it, one package at time.

**Comment by piegamesde** [comment]
Thanks. Tracked in #155061.
