### ISSUE TITLE
Update NetworkManager to 1.34.0

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#155115]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: networkmanager

current version: 1.32.12
desired version: 1.34.0

###### Notify maintainers

maintainers: @jtojnar @domenkozar @obadz @maxeaubrey 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment]
Closed in #155553
