### ISSUE TITLE
libgcrypt 404

### ISSUE THREAD

**Issue by boobiesinc** [NixOS/nixpkgs#15510]
![virtualbox_nixos2_17_05_2016_10_39_05](https://cloud.githubusercontent.com/assets/19384416/15314731/546e8cae-1c1c-11e6-9d67-51599bf126c5.png)

context: https://github.com/NixOS/nixpkgs/issues/14562#issuecomment-219475505

**Comment by boobiesinc** [comment]
looks like the url should be: http://mirrors.dotsrc.org/gcrypt/libgcrypt/
and 1.7.0 is still not available... 1.6.4 is latest there

**Comment by boobiesinc** [comment]
well this one has 1.7.0
ftp://ftp.heanet.ie/mirrors/ftp.gnupg.org/gcrypt/libgcrypt/
but the url is different again. the `gcrypt` subfolder...

**Comment by vcunat** [comment]
Fix was pushed as af364c0.
