### ISSUE TITLE
Postgis extension doesn't work

### ISSUE THREAD

**Issue by thall** [NixOS/nixpkgs#15512]
## Issue description
Not able to create postgis extension 

### Steps to reproduce
``` 
$ psql -U postgres -h localhost -c "create database dummy"
CREATE DATABASE

$ psql -U postgres -h localhost -d dummy -c "create extension postgis"
ERROR:  could not access file "$libdir/postgis-2.2": No such file or directory
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre83703.0373eb8 (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre83703.0373eb8"

```
...
  services.postgresql = {
    enable = true;
    package = pkgs.postgresql95;
    extraPlugins = [ (pkgs.postgis.override { postgresql = pkgs.postgresql95; }).v_2_2_1 ];
  };
...
```

**Comment by thall** [comment]
Ping @paraseba

**Comment by paraseba** [comment]
I was able to reproduce it. Let me see if I can fix it

**Comment by paraseba** [comment]
I think something like the following _could_ work, but unfortunately I can't test it because my tree is not building (zfs problems) and I don't know how to build a nixos module independently. Any chance you could give it a try @thall ?

```diff
diff --git a/nixos/modules/services/databases/postgresql.nix b/nixos/modules/services/databases/postgresql.nix
index 80ee32f..aabbfa5 100644
--- a/nixos/modules/services/databases/postgresql.nix
+++ b/nixos/modules/services/databases/postgresql.nix
@@ -11,7 +11,7 @@ let
     if cfg.extraPlugins == [] then pg
     else pkgs.buildEnv {
       name = "postgresql-and-plugins-${(builtins.parseDrvName pg.name).version}";
-      paths = [ pg ] ++ cfg.extraPlugins;
+      paths = concatMap ( p: [ p (getLib p) ] ) ( [ pg ] ++ cfg.extraPlugins );
       postBuild =
         ''
           mkdir -p $out/bin
```

**Comment by thall** [comment]
I will give it a try, i havent rebuild nixos based on the git-repo with custom patches before. Im relative new to nixos.

**Comment by paraseba** [comment]
I don't think it's working. The problem is still pg_config. In the current version `pg_config --libdir`  points to the postgresql-lib path, in the old working version it pointed to nixos's postgresq-and-plugins which is where the DLLs are. Need to find a way to bring that behavior back in the new split outputs world.

**Comment by thall** [comment]
Im using an docker image with postgres and postgis as an workaround for the moment.
