### ISSUE TITLE
ocamlPackages, coq: remove liblgtk

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nixpkgs#155155]
I am in the process of removing `ocamlPackages.lablgtk` because it depends on `libglade`, which is about to be removed. I managed to handle most dependents but for `coq` I need your help. I see that it depends on both `lablgtk` and `lablgtk3` with some heavy version gating. Please help me removing the `lablgtk` dependency. This probably means that we will have to drop support for some older `coq` versions, but I'm not sure.

@roconnor @thoughtpolice @vbgl @Zimmi48

**Comment by vbgl** [comment]
Please try to write polite messages next time. Thanks.

**Comment by piegamesde** [comment]
I am sorry, but I don't understand. Which parts are offending you?

**Comment by Zimmi48** [comment]
Hi @piegamesde, I personally don't see any problem with your message.

AFAIK lablgtk is needed for Coq version < 8.10. I could understand that some users would like to keep these versions available, but I don't personally oppose to removing them.

cc @jwiegley

**Comment by piegamesde** [comment]
I've just discovered #155204 which removes the `libglade` dependency for `lablgtk`. With that, I could probably leave the packages in for now. However, since they also depend on Gtk2 which is EOL as well, it would be equally fine to just remove them (or some of them). What do you think?

**Comment by Zimmi48** [comment]
Let's keep these old Coq versions as long as Gtk2 is kept in nixpkgs. In fact, we could even keep them longer (if needed) by just removing the IDE part of the package.
