### ISSUE TITLE
`flex` package should provide `lex` binary

### ISSUE THREAD

**Issue by WesleyAC** [NixOS/nixpkgs#155168]
On most linux distributions, `/bin/lex` is provided by the `flex` package as a symlink to `/bin/flex`. This is not the case on NixOS, which makes building some software that expects a `lex` binary difficult.

NixOS should change the `flex` package to provide `/bin/lex` in addition to the `/bin/flex` and `/bin/flex++` that it currently provides.

**Comment by WesleyAC** [comment]
Here are several instances of people running into this problem on IRC:

https://logs.nix.samueldr.com/nixos/2018-06-10#1283909;
https://logs.nix.samueldr.com/nixos/2019-05-21#2239729;
https://logs.nix.samueldr.com/nixos/2020-12-31#4419780;

**Comment by abathur** [comment]
Closing since it sounds like it should've closed when #155208 merged. Happy to reopen if I'm mistaken.
