### ISSUE TITLE
gnulib: hash mismatch? using latest master nixpkgs

### ISSUE THREAD

**Issue by boobiesinc** [NixOS/nixpkgs#15520]
## Issue description
![hash_virtualbox_nixos2_17_05_2016_16_02_10](https://cloud.githubusercontent.com/assets/19384416/15323123/0d7b3f22-1c49-11e6-8ec8-2b646ff1ea6f.png)

### Steps to reproduce
During `nixos-install` from the `nixos-minimal-16.09pre83100.25e3c09-x86_64-linux.iso`
but using the latest master nixpkgs with set NIX_PATH (if necessary, see [this](https://github.com/NixOS/nixpkgs/issues/14562#issuecomment-219475505) for context)

## Technical details

these don't seem to be needed:
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by boobiesinc** [comment]
How could the hash be different? Presumably it was ok at one point. Doesn't this mean something got nefariously changed within that gnulib repo?

**Comment by boobiesinc** [comment]
Or... is [this](https://github.com/NixOS/nixpkgs/pull/15469) to "blame"

**Comment by joachifm** [comment]
Yes, this is #15469
