### ISSUE TITLE
Plasma does not pass color theme to gtk 4 apps

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#155293]
### Describe the bug
Even through gtk 4 app recognize the `GTK_THEME=Breeze` setting, they still do not take the color theme set from the system, instead utilizing the default Breeze light color scheme

### Steps To Reproduce
1. Start `plasmawayland`
2. `nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-demo`
3. ` GTK_THEME=Breeze nix-shell -I nixpkgs=channel:nixos-unstable -p gtk4.dev --run gtk4-demo`

### Expected behavior
GTK apps are themed according to the global theme

### Screenshots
![image](https://user-images.githubusercontent.com/6931743/149689392-2fcc7176-c075-459b-9f60-cdb8785905e2.png)
![image](https://user-images.githubusercontent.com/6931743/149689445-cdf57d2f-3fbb-4f73-a55a-101840e92f16.png)
### Additional context
GTK applications on Plasma X11 are correctly themed
### Notify maintainers
@NixOS/gnome @NixOS/qt-kde 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/store/3c249himjn7sh3cwnapmh5qgrnmd42xg-source`

**Comment by jtojnar** [comment]
That looks like Breeze colours to me. Perhaps you need to use `Breeze-Dark`, looking at the contents of `libsForQt5.breeze-gtk` package.

**Comment by pasqui23** [comment]
I've submitted https://bugs.kde.org/show_bug.cgi?id=448675

**Comment by pasqui23** [comment]
And yes it is not only a wayland problem

**Comment by pasqui23** [comment]
The problem is that gtk 4 apps do not apply the color theme like gtk 3
https://bugs.kde.org/attachment.cgi?id=145598
