### ISSUE TITLE
Steam: error loading libfuse.so.2

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#155278]
### Describe the bug

[SuperTux](https://store.steampowered.com/app/1572920/SuperTux/) is now available on Steam. It is packaged with AppImage, which needs FUSE to run.

```
Opted-in Controller Mask for AppId 1572920: 1
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
CAPIJobRequestUserStats - Server response failed 2
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1572920, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1572920, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/davidak/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1572920 -- '/home/davidak/.local/share/Steam/steamapps/common/SuperTux/SuperTux.AppImage'\0
Game process added : AppID 1572920 "/home/davidak/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1572920 -- '/home/davidak/.local/share/Steam/steamapps/common/SuperTux/SuperTux.AppImage'", ProcID 817562, IP 0.0.0.0:0
chdir /home/davidak/.local/share/Steam/steamapps/common/SuperTux
ERROR: ld.so: object '/home/davidak/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/davidak/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/davidak/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1572920, ActionID 1] : LaunchApp changed task to Completed with ""
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
Game process removed: AppID 1572920 "/home/davidak/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1572920 -- '/home/davidak/.local/share/Steam/steamapps/common/SuperTux/SuperTux.AppImage'", ProcID 817562 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1639697812)
```

### Steps To Reproduce
1. Install game
2. run game
3. see errors in terminal

### Expected behavior
games from steam should just work

### Additional context

People which use Steam as Flatpak also have issues. The game developers might use the steam runtime instead of AppImage, which might also fix this issue. Not sure if it's worth it to add this dependency now to support other games that potentially use AppImage.

https://www.gamingonlinux.com/2022/01/supertux-released-free-on-steam-an-open-source-classic/comment_id=217269

We can remove FUSE when not needed anymore.

### Notify maintainers
@jonringer

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"home-manager-21.11, nixos-21.11.335130.386234e2a61, nixos-hardware, nixos-unstable-22.05pre346004.5aaed40d22f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
Should just need to add libfuse to targetPkgs in the steam/fhsenv.nix

**Comment by davidak** [comment]
Then i get a different error.

```
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to DownloadingDepots with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to DownloadingDepots with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""

GameAction [AppID 1572920, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1572920, ActionID 2] : LaunchApp failed with AppError_28 with "/home/davidak/.local/share/Steam/steamapps/common/SuperTux/SuperTux.AppImage"
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to Failed with ""
```

I see if upstream can fix it.

**Comment by SuperSamus** [comment]
It's still an issue.

**Comment by necrophcodr** [comment]
> Then i get a different error.
> 
> ```
> Could not connect to X session manager: None of the authentication protocols specified are supported
> Could not connect to X session manager: None of the authentication protocols specified are supported
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to DownloadingDepots with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to DownloadingDepots with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SynchronizingControllerConfig with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
> GameAction [AppID 1572920, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
> 
> GameAction [AppID 1572920, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
> Could not connect to X session manager: None of the authentication protocols specified are supported
> Could not connect to X session manager: None of the authentication protocols specified are supported
> GameAction [AppID 1572920, ActionID 2] : LaunchApp failed with AppError_28 with "/home/davidak/.local/share/Steam/steamapps/common/SuperTux/SuperTux.AppImage"
> GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to Failed with ""
> ```
> 
> I see if upstream can fix it.

Did you attempt running it with the Steam launch parameters set to `appimage-run %command%`, while appimage-run was installed?

**Comment by tobbi** [comment]
@SuperSandro2000 Why was this closed as completed? Is the issue fixed? I'd like to know because there's dependent issues in the SuperTux repository that could get closed as well.

**Comment by SuperSandro2000** [comment]
This is likely no longer an issue due to steam's new runtime.
