### ISSUE TITLE
Package conflict: python packages & docker-compose

### ISSUE THREAD

**Issue by skogsbrus** [NixOS/nixpkgs#155373]
### Describe the bug
When installing docker-compose & Python packages from `pythonPackages39` in the same environment, Python is unable to import the installed packages.

#### Affected packages

 I have verified the same behavior with the following packages:
- `python39Packages.wget`
- `python39Packages.tqdm`
-  `python39Packages.numpy`
- `python39Packages.networkx`
- `python39Packages.boto3`

##### Instructions

Note: this description uses psycopg2 as an example.

1. Create a file `shell.nix`:

```
# shell.nix
let
  pkgs = import <nixpkgs> {};
in pkgs.mkShell {
  buildInputs = with pkgs; [
    python39Packages.psycopg2
    docker-compose
  ];
}
```

2. Enter the shell:

```
$ nix-shell shell.nix
```

3. Import psycopg2

```
$ python -c 'import psycopg2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'psycopg2'
$
```
4. Remove docker-compose from the shell file
5. Enter the shell
6. Import psycopg2
```
$ python -c 'import psycopg2'
$
```

### Expected behavior

Steps 5-6 above describe the expected behavior - having docker-compose in the same environment as these packages should not make the them unimportable.

### Additional context

* I use NixOS with flakes, here is my lockfile: https://github.com/skogsbrus/os/blob/master/flake.lock
* I have tried different packages than `docker-compose`, but it is the only one triggering this behavior.

### Notify maintainers

* @Frostman, tagging you as you are listed as maintainer of `docker-compose`. 
* Not sure who to tag from the Python side of things.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"home-manager-21.05, nixos-21.05.1542.268dee84298"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by skogsbrus** [comment]
For what it's worth, I see the same behaviour if I change the shell file like so:

1. 
```
let
  pkgs = import <nixpkgs> {};
in pkgs.mkShell {
  buildInputs = [
    pkgs.python39Packages.psycopg2
    pkgs.docker-compose
  ];
}
```
or use `nix-shell -p`:
2.
```
nix-shell -p python39Packages.psycopg2 docker-compose
```

So I think that rules out any configuration error on my part?

**Comment by skogsbrus** [comment]
Some additional checks that I've done after getting some help from @K9000 on Matrix:

* I have verified that the issue persists even when using `nix-shell --pure`. Packages are importable then too, until docker-compose is added.

* Running `nix-shell -p 'python39.withPackages(ps: [ ps.psycopg2 ])' docker-compose` actually does work. With this I'm able to run `python -c 'import psycopg2'` inside the shell.

But I suppose this still is an issue...?

**Comment by FRidh** [comment]
use `(python39.withPackages(ps: with ps; [ psycopg2 ]))` instead. That way, you have an interpreter that knows where to find its packages.

**Comment by FRidh** [comment]
> But I suppose this still is an issue...?

Nope, it is not. In your first case you were relying on build hooks to set up the environment, and they can't handle mixing Python versions, hence the `withPackages` method.

**Comment by skogsbrus** [comment]
I see, TIL. Thanks for taking a look at this so quickly!
