### ISSUE TITLE
`tmux` sessions do not show up in `who`/`users`/`last`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#155446]
### Describe the bug
A follow up to https://discourse.nixos.org/t/tmux-sessions-do-not-show-up-in-who-users-last/14698. It seems like `/var/log/wtmp` is not getting updated when tmux sessions begin/end.

Relevant links:
* https://bugs.launchpad.net/ubuntu/+source/tmux/+bug/1890406
* https://superuser.com/a/1501860/1286339

### Steps To Reproduce
1. Run `who` and note the results.
2. In a different shell, open a new tmux session: `tmux`
3. Without exiting tmux, run `who` again and note that the results are the same.

### Expected behavior
Tmux user sessions to show up in `who`, `users`, and `last`, as is custom in other OSes.

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers

@fpletz @tobias-hammerschmidt @malbarbo @marsam 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.87, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.334578.75f3534c98a, nix-ld"`
 - channels(skainswo): `"home-manager, nixpkgs-unstable-22.05pre343295.adf7f03d3bf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/201183
