### ISSUE TITLE
vim plugins have wrong hash

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#15547]
## Issue description

Many vim plugins have wrong hash on last unstable.
Probably due to 499195dfcffd9ab9063bd369bee0b85b7ef1f8ce

cc @garbas 

### Steps to reproduce

Some examples:

```
$ nix-shell -p vimPlugins.vim-airline -I nixpkgs=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
...
removing `.git'...
output path ‘/nix/store/pq50wfn758crzz6m7lvqfh3z05d0i7mw-vim-airline-70c16f4’ has r:sha256 hash ‘0sa3my8jhslcrk81lfk8f32wnq1akxazxpxhjmiwmpws74kbibql’ when ‘1ib3rs0ysz41dxk4fmzjrha005adrrlya5bnb8cv1p1ny7ipny1d’ was expected
cannot build derivation ‘/nix/store/grxqvfsxn2c3xm60jp77h02a3kgs9a0g-vimplugin-vim-airline-2016-05-15.drv’: 1 dependencies couldn't be built
```
```
nix-shell -p vimPlugins.Syntastic -I nixpkgs=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
removing `.git'...
output path ‘/nix/store/6qj1mgwxvfkd8hhikk62j70frwdvph6d-syntastic-c2c6a07’ has r:sha256 hash ‘1fkjq43rlacdpb5h6qvhpc4dpm0lrfzpa5kjv8m0irk4i635mzwg’ when ‘1b6wc3705n7pj93cf6cv2sazihqw11zq53a7slr646lcdx8r6d7f’ was expected
cannot build derivation ‘/nix/store/14p70y3dnav0i4m946y5igajycdqcx4n-vimplugin-Syntastic-2016-05-12.drv’: 1 dependencies couldn't be built
```

## Technical details

* Nixpkgs rev: d541e0dc1c05f5514bf30f8039e687adddb45616

**Comment by matthiasbeyer** [comment]
Can confirm. Same issue here for:

* ycm
* undotree
* fugitive
* ultisnips

**Comment by garbas** [comment]
weird ... i'll check and fix them tomorrow morning.

**Comment by ericsagnes** [comment]
Also could be related to #15469.

**Comment by groxxda** [comment]
Here are the (broken) hashes I identified:
https://gist.github.com/groxxda/e0243a05b214296c136aaa2678990428

See https://github.com/NixOS/nixpkgs/pull/15469#issuecomment-220318017 for more information how I obtained these.

Can mass replace and open PR if someone else confirms the hashes :wink:

**Comment by matthiasbeyer** [comment]
@groxxda If you file a PR, feel free to notify me so I can build the plugins on my build VM.

**Comment by garbas** [comment]
[fixed](https://github.com/NixOS/nixpkgs/compare/d06f9d834cd6...810a4dd656f9)

**Comment by ericsagnes** [comment]
Thank you!
