### ISSUE TITLE
Open-supaplex

### ISSUE THREAD

**Issue by bilufe** [NixOS/nixpkgs#155439]
**Project description**
OpenSupaplex is a 1:1 reimplementation of the original game Supaplex in C and SDL, with just a few changes to make it easy to use with game controllers, and also easy to port to any platform.

**Metadata**

* homepage URL: https://github.com/sergiou87/open-supaplex
* source URL: https://github.com/sergiou87/open-supaplex
* license: gpl3
* platforms: linux, windows, macos

**Comment by IvarWithoutBones** [comment]
I've created a PR which adds it, see #155505. Would you mind testing that?

**Comment by bilufe** [comment]
Works for me.
