### ISSUE TITLE
VSCode version is out of date

### ISSUE THREAD

**Issue by Tyriar** [NixOS/nixpkgs#15548]
The rev is set to v1.0.0 https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vscode/default.nix#L5, v1.1.1 is now out.

It will also need to symlink `./bin/code` instead of `./code` as the bin command as part of this update.

**Comment by bratfizyk** [comment]
Quick update: the version 1.2.0 of VS Code has just been released.
