### ISSUE TITLE
ttfautohint fails to build on macOS

### ISSUE THREAD

**Issue by Sciencentistguy** [NixOS/nixpkgs#155415]
### Describe the bug
ttfautohint throws lots of c++ errors when building `iosevka` on macos

This is on a 2021 M1 Max Macbook Pro

### Steps To Reproduce
1. Use this shell.nix
```nix
with import <nixpkgs> {};

mkShell {
  buildInputs = [
    iosevka
  ];
}
``` 
2. run nix-shell
3. c++ errors will occur:  https://gist.github.com/Sciencentistguy/735905199ae8a03b62cd0b1f6d158d3c

### Expected behavior
It should not error

### Notify maintainers
@cillianderoiste 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixpkgs-22.05pre346058.bc59ba15b64"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by veprbl** [comment]
Coincidentally, I've just filed #155458

**Comment by Sciencentistguy** [comment]
This does seem to fix it thankfully. Unfortunately until it is merged this means I'll have to build iosevka from source, which seems to take an age even on a powerful computer.

**Comment by veprbl** [comment]
It looks like `iosevka` hasn't built for a while on darwin Hydra:
https://hydra.nixos.org/job/nixpkgs/trunk/iosevka.x86_64-darwin
because the build is too quiet.

Perhaps, `iosevka-bin` would work for you?
