### ISSUE TITLE
Merge clang and gcc wrappers

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1554]
Currently gcc and clang are wrapped in almost identical fashions, with only minor differences and a lot of duplication. We should merge these, with any necessary divergence being built on top of a common base. Waiting for stdenv-updates.

**Comment by Mathnerd314** [comment]
This seems to have been fixed in 48f63c2f2e3752df2a0b73cad9b9bba9eda8ac60, Can someone close it?

**Comment by vcunat** [comment]
True.
