### ISSUE TITLE
Sioyek

### ISSUE THREAD

**Issue by foo-dogsquared** [NixOS/nixpkgs#155490]
**Project description**
A PDF reader primarily aimed at researchers.

**Metadata**

* homepage URL: https://sioyek.info/
* source URL: https://github.com/ahrm/sioyek
* license: gpl3
* platforms: unix, linux, darwin, windows

**Comment by SenchoPens** [comment]
Hi, it's been packaged a month ago, I think you can close the issue :)
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/sioyek/default.nix

**Comment by foo-dogsquared** [comment]
Nice! Thanks for notifying me.
