### ISSUE TITLE
manual: umount /mnt ?

### ISSUE THREAD

**Issue by boobiesinc** [NixOS/nixpkgs#15549]
https://github.com/NixOS/nixpkgs/blob/90d7041ce4d270bbcf0efefd1d1e42c097c1335d/nixos/doc/manual/installation/installing.xml#L186-L191
Any word for people wondering if they should do an `umount /mnt` first? (it did umount without errors)

**Comment by edolstra** [comment]
In principle unmounting should not be necessary, because shutdown will do it automatically. Also, `nixos-install` (via `switch-to-configuration`) will do a `sync` on the filesystem so the contents should be safe.

**Comment by boobiesinc** [comment]
It would be great if someone would mention that in the manual, else some readers would be wondering if they should `umount /mnt` or not. I know it's implied that they shouldn't but, it would be good to know, even if it's not explained as to why.
