### ISSUE TITLE
Some packages are missing source repositories

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#15558]
## Issue description

At least the following attributes cannot be fetched from git:
- [x] "caneda.src"
- [x] "ocamlPackages.bitstring_git.src"
- [x] "path64.src"
- [x] "urbit.src"
- [x] "vfdecrypt.src"
### Steps to reproduce

nix-build -A <attr> --check
## Technical details
- System: 16.09.git.daaf592
- Nix version: 1.11.2
- Nixpkgs version: 16.09.git.daaf592

**Comment by copumpkin** [comment]
@groxxda can you elaborate a bit on this ticket? I wasn't aware of a standard that dictated that the `src` attribute be populated, since sometimes packages will need `srcs` or have custom build processes that amalgamate a collection of different sources. Does the documentation promise somewhere that `src` will be defined, or is there something else that suggests that one should always expect it to be defined?

**Comment by groxxda** [comment]
@copumpkin I don't know of any standard either, I just came across these derivations that have a src specified that points to a repository that is (no longer) there.

**Comment by abbradar** [comment]
@copumpkin If I understand correctly, the issue is not about `.src` attribute, but about upstream removing/moving somewhere the repository.

**Comment by rasendubi** [comment]
`urbit.src` works ok.

`caneda` and `path64` seem to be dead projects.

`vfdecrypt` also seems to be dead and is marked as broken.

cc maintainer of bitstring_git @maurer.

**Comment by rasendubi** [comment]
Caneda moved to https://github.com/Caneda/Caneda. However, I can't find caneda components needed to build it. (There is https://github.com/Caneda/Libraries but it doesn't have 34cd36b.)

**Comment by maurer** [comment]
See #17002 (looks like google code went full archive and stopped supporting git cloning, but we didn't really need bitstring_git anyways)

**Comment by dtzWill** [comment]
I believe this can now be closed:

* caneda was fixed as part of #30067
* vfdecrypt was fixed in February with [this commit](https://github.com/NixOS/nixpkgs/commit/b55c259a7208e691050f341d8296ee044606a858), and I confirmed it's still valid
