### ISSUE TITLE
quvi doesn't work

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#15554]
## Issue description

`quvi` installs but is unusable.
### Steps to reproduce

``` bash
$ nix-env -i quvi
$ quvi scan https://www.youtube.com/watch?v=guMLPr6eBLo
** (scan:31922): CRITICAL **: [_chk_script_ident] ...34pryqk0d-lua5.1-socket-3.0-rc1/share/lua/5.1/socket.lua:12: module 'socket.core' not found:
        no field package.preload['socket.core']
        no file '/nix/store/7n9w59034z4a72zns96634f34pryqk0d-lua5.1-socket-3.0-rc1/share/lua/5.1/socket/core.lua'
        no file '/nix/store/m4h7vds970wgsqn8h16f08cqnjm9hq0c-quvi-scripts-0.9.20131130/share/libquvi-scripts/0.9/common/socket/core.lua'
        no file '/usr/lib/lua/5.2/socket/core.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './socket/core.so'
        no file '/usr/lib/lua/5.2/socket.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './socket.so'
error: while initializing libquvi: Could not find any subtitle scripts in the path
```
## Technical details
- System: `16.03.759.b10f61b (Emu)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `16.03.759.b10f61b`

**Comment by seanparsons** [comment]
I just tried to look at this a bunch and effectively got nowhere fast. Made both the lib and the tool use Lua 5.1 and the 5.1 sockets lib. Oddly in Googling around it there seems to be others elsewhere having issues with this particular combination.

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by dpaetzel** [comment]
While I'm not sure whether this solves this issue in its entirety, two things brought me a bit closer fixing it:

- Adding `"${lua5_sockets}/lib/lua/${lua5.luaversion}/?.so"` to the `LUA_CPATH`: 
  ```
  wrapProgram $out/bin/quvi --set LUA_CPATH "${lua5_sockets}/lib/lua/${lua5.luaversion}/?.so"
  ```
- Using `lua52` instead of `lua51`. In `all-packages.nix`:
  ```
  quvi = callPackage ../applications/video/quvi/tool.nix {
    lua5_sockets = lua52Packages.luasocket;
    lua5 = lua5_2;
  };
  ```

I don't have any experience with Lua, though, so there might be a better solution.

After doing this, I get a very different error which I had not yet the time to investigate (and which is why I didn't open a PR yet):

```
quvi get "https://www.youtube.com/watch?v=guMLPr6eBLo"
error: libquvi: while parsing media properties: ...0.9.20131130/share/libquvi-scripts/0.9/media/youtube.lua:121: no match: url_encoded_fmt_stream_map
```

**Comment by dpaetzel** [comment]
This issue persists exactly as originally described. Unfortunately, I did not get around to investigating any further than as described by my last comment.
