### ISSUE TITLE
Remove libraries relying on `use_2to3`

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#155516]
`use_2to3` was an automatic translation feature provided by setuptoos to convert python2 to python3 by running 2to3 during the build phase. Projects using it are in fact python2 projects and are mostly unmaintained and should be removed.

The feature itself was removed from setuptools in version 58, which is currently on python-unstable.

## Affected packages and their direct dependencies.

https://hydra.nixos.org/eval/1738807?filter=python39&compare=1738720&full=#tabs-now-fail

Check when removed or fixed.

- [x] `anyjso`
    - [x] `python.pkgs.carrot`
- [x] `deap`
    - [ ] `python.pkgs.sklearn-deap`
- [x] `demjson` (https://hydra.nixos.org/build/164886968/nixlog/1)
    - ~~`nixops`~~
- [x] `hdlparse` (https://hydra.nixos.org/build/164903277/nixlog/1)
- [x] `ipy`
- [x] `jsmin`
- [x] `keepalive` (https://hydra.nixos.org/build/164889231/nixlog/1)
    - [ ] `python.pkgs.sparqlwrapper`
- [x] `parameterizedtestcase` (https://hydra.nixos.org/build/164898488/nixlog/1)
    - [x] `python.pkgs.smart-open`
- [x] `parse-type` (https://hydra.nixos.org/build/164887997/nixlog/1)
    - [x] `python.pkgs.behave`
    - [x] `python.pkgs.pytest-bdd`
    - [x] `python.pkgs.radish-bdd`
    - [x] `python.pkgs.python-docx`
- [x] `pyvcf` @scalavision 
- [x] `pycallgraph` (https://hydra.nixos.org/build/164891698/nixlog/1)
- [x] `nose`
- [x] `nose-cover`
- [x] `s3bro`
- [x] `suds-jurko` (https://hydra.nixos.org/build/164902920/nixlog/1)
    - [ ] `jira_cli`
    - [x] `python.pkgs.suseapi`
    - [x] `python.pkgstransip`

**Comment by jonringer** [comment]
fail2ban was addressed in https://github.com/NixOS/nixpkgs/pull/154969/commits/df7d43efea558590230de77cf3ed0101a4006761

**Comment by jonringer** [comment]
client: https://github.com/NixOS/nixpkgs/pull/154969/commits/da183ea690dd9995ab23213407b049cb2657df2a

**Comment by jonringer** [comment]
setuptools bump has been moved to https://github.com/NixOS/nixpkgs/pull/155531 from the `python-unstable`, so that python-unstable isn't blocked by so many hard failures

**Comment by jonringer** [comment]
parse_type has been resolved: https://github.com/behave/behave/issues/994

**Comment by tjni** [comment]
I think this issue can finally be closed 🎉 . For the unchecked boxes:

- `deap`: https://github.com/NixOS/nixpkgs/pull/192368
- `jsmin`: https://github.com/NixOS/nixpkgs/pull/156050
- `keepalive`: https://github.com/NixOS/nixpkgs/pull/236395
- `parameterizedtestcase`: https://github.com/NixOS/nixpkgs/pull/204690
- `pyvcf`: https://github.com/NixOS/nixpkgs/pull/232816
- `nose`: https://github.com/NixOS/nixpkgs/commit/ce9944c4d4cfe441b716ce1bb036d3dc33ee9646
- `s3bro`: https://github.com/NixOS/nixpkgs/pull/174148
- `suds-jurko`: https://github.com/NixOS/nixpkgs/pull/218612
