### ISSUE TITLE
qbittorrent cannot open library libQt5Widgets.so.5

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#15556]
## Issue description

Trying to run `qbittorrent` fails with the following error message:

    $ qbittorrent
    qbittorrent: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
16.09pre83796.d541e0d (Flounder)
```
* Nix version: (run `nix-env --version`)
```
nix-env (Nix) 1.11.2
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
"16.09pre83796.d541e0d"
```

cc @viric

**Comment by rardiol** [comment]
I think it has something to do with the rpath being set to the qt build tmp folder, containing symlinks, instead of the actual place the qt libs are in the nix store.

**Comment by rardiol** [comment]
Similar problem at least on qtox. bisected it down to @d22df66c54df371039f5d71382beddf559ec5f05 (removing fixQtModuleCMakeConfig) from @ttuegel

**Comment by ttuegel** [comment]
qbittorrent should be linking to libQt5Widgets if necessary instead of trying to dlopen it from an absolute path. If it cannot be patched to do so, then it should be patched to not dlopen an absolute path and wrapped to prefix LD_LIBRARY_PATH.

**Comment by rardiol** [comment]
I'm not really familiar with dynamic loading, but I couldn't find any evidence of it being done for qbitorrent. And grepping for Qt5Widgets gives me the following line, which I think indicates it's dynamic linking to qt as normal

`../qbittorrent-3.3.4/src/Makefile:LIBS          = $(SUBLIBS) -L/nix/store/1nsz8wspax9363pmvvb4xjbcp5m7qg9g-mesa-noglu-11.1.3/lib -L/nix/store/d0j2nwz8sy89sh79i8wfvfcfnnfshvzi-boost-1.60.0/lib -L/nix/store/ks485pqry62dwddlqlbafhvjzpwzv1gv-zlib-1.2.8/lib -lz -L/nix/store/aw1mj6hvhna2nvxxgm1b23a4wq429z2k-libtorrent-rasterbar-1.0.9/lib -ltorrent-rasterbar -lboost_system -lpthread -L/run/user/1000/tmp.H5vmLWA7lN/lib -lQt5Widgets -lQt5Gui -lQt5DBus -lQt5Xml -lQt5Concurrent -lQt5Network -lQt5Core -lGL `

**Comment by rardiol** [comment]
What I have right now is that the tmp.hash/lib qt folder has only .la and .prl files when it worked, and after that commit that folder (which ends up in the beggining of qbittorrent's rpath) actually includes the .so files, meaning qbittorrent gets linked to it.

**Comment by ttuegel** [comment]
The offending linker flag is `-L/run/user/1000/tmp.H5vmLWA7lN/lib`. We will need to figure out why it is being inserted. None of the `-L` linker flags in that command are necessary. I don't know why this only affects some of the packages built with `qmake`.

> that folder (which ends up in the beggining of qbittorrent's rpath)

That is a **very serious security vulnerability** whether the `.so` files are located there during build or not.

**Comment by rardiol** [comment]
Note that's when I'm building interactively with nix-shell. the actual distibuted binaries have a rpath with something like "/tmp/nix-build-qbittorrent-3.3.4.drv-0/tmp.doBBpoVYn4/". Still dangerous I suppose. Also, it only shows up on the actually distributed qbittorrent from after the breaking commit, probably because before that nix would clean it up due to not being used. The equivalent line from just before that commit:

`LIBS          = $(SUBLIBS) -L/nix/store/hlk7gp0hwv2skjx7qlkzn1mdmjw8zdv6-mesa-noglu-11.1.3/lib -L/nix/store/vj8ln361w7wlsyws3015v9cqrzzwjykw-boost-1.60.0/lib -L/nix/store/r96cr60vj9vrxwv1fjwi9d8rh4243s9l-zlib-1.2.8/lib -lz -L/nix/store/xxbgysj47pzhxi0m7bqciz2dlh0h77nn-libtorrent-rasterbar-1.0.9/lib -ltorrent-rasterbar -lboost_system -lpthread -L/run/user/1000/tmp.dis4NqyfOq/lib -lQt5Widgets -lQt5Gui -lQt5DBus -lQt5Xml -lQt5Concurrent -lQt5Network -lQt5Core -lGL `

**Comment by rardiol** [comment]
`-L/nix/store/vj8ln361w7wlsyws3015v9cqrzzwjykw-boost-1.60.0/lib  -L/nix/store/r96cr60vj9vrxwv1fjwi9d8rh4243s9l-zlib-1.2.8/lib -lz -L/nix/store/xxbgysj47pzhxi0m7bqciz2dlh0h77nn-libtorrent-rasterbar-1.0.9/lib` comes from conf.pri which comes from conf.pri.in

As for the main problem, seems the problem starts in tmp.*/mkspecs/features/qt.prf, lines 72, 90 and 91, and then on line 128 MODULE_LIBS_ADD (containing /run/user/1000/tmp.*/lib) gets added to LIBS.

72:       MODULE_LIBS = $$eval(QT.$${QTLIB}.libs)
90:       MODULE_LIBS_ADD = $$MODULE_LIBS
91:       MODULE_LIBS_ADD -= $$QMAKE_DEFAULT_LIBDIRS

**Comment by obadz** [comment]
@ttuegel, could this have caused this error:

http://hydra.nixos.org/build/36460792/nixlog/1#line-57

**Comment by ttuegel** [comment]
Not this change, but a related one. Patch is inbound.
