### ISSUE TITLE
Update easyeffects to 6.2.1

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#155588]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: easyeffects

current version: 6.1.3
desired version: 6.2.1

###### Notify maintainers

maintainers: @jtojnar 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by nagisa** [comment]
With pipewire 0.3.44 onwards, easyeffects before 6.2.2 will just SIGSEGV on launch.
