### ISSUE TITLE
Current version of dropbox in 16.03 is soon outdated

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#15564]
### Steps to reproduce
    $ dropbox status
    You're using an old version of Dropbox. Please update within the next 5 days to continue using Dropbox.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/dropbox/default.nix#L22
https://github.com/NixOS/nixpkgs/blob/release-16.03/pkgs/applications/networking/dropbox/default.nix#L22

## Technical details

* System: NixOS: 16.03.802.01f5711 (Emu)
* Nix version: 1.11.2
* Nixpkgs version: 16.03.802.01f5711

**Comment by FRidh** [comment]
Fixed in #15566
