### ISSUE TITLE
intel-ocl download URL no longer valid

### ISSUE THREAD

**Issue by rileyinman** [NixOS/nixpkgs#155664]
## Issue description
When attempting to upgrade my system, intel-ocl returns a 403 error. Trying to download the source URL manually confirms that it no longer exists on the intel site. I'm unsure how to go about finding the new direct download URL.

### Steps to reproduce
Attempt to build intel-ocl.

## Technical details
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.4, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335376.610d4ea2750"`
 - channels(riley): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by csernazs** [comment]
For me it seems that the url https://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip is invalid (results 403) but the url with pure http (not https) is working: http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip.

**Comment by rileyinman** [comment]
That URL still gives me a 403 error... I wonder what the difference could be?

**Comment by hostops** [comment]
I have problem with both http and https versions. https returns 403 and http timeouts.

**Comment by TheDelus** [comment]
Http works for me. Added the following to my overlay to fix the build:
```
  intel-ocl = super.intel-ocl.overrideAttrs (oldAttrs: {
    src = super.fetchzip {
      url = "http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip";
      sha256 = "0qbp63l74s0i80ysh9ya8x7r79xkddbbz4378nms9i7a0kprg9p2";
      stripRoot = false;
    };
  });
```

**Comment by Krutonium** [comment]
Both of those URL's now 404 at least for me.

**Comment by SuperSandro2000** [comment]
#166886
