### ISSUE TITLE
gnupg 2.3.x update broke smartcard (Yubikey) support on Darwin

### ISSUE THREAD

**Issue by mikroskeem** [NixOS/nixpkgs#155629]
### Describe the bug

gnupg worked fine on 2.2.x; pinned nixpkgs-unstable to 0432195a4b8d68faaa7d3d4b355260a3120aeeae on my flake.

### Steps To Reproduce
1. Install gnupg from current nixpkgs-unstable, e.g rev d5dae6569ea9952f1ae4e727946d93a71c507821 & the usual `pkill gpg-agent`
2. Try `gpg --card-status`
3. See it break:

```
> gpg --card-status
gpg: error reading symlink '/proc/curproc/file': No such file or directory
gpg: selecting card failed: Operation not supported by device
gpg: OpenPGP card not available: Operation not supported by device
```

When signing something, you should get pinentry asking you to insert the smartcard - re-plugging has no effect.

### Expected behavior
```
> gpg --card-status
Reader ...........: Yubico YubiKey OTP FIDO CCID
...
```

& signing work etc.

### Additional context

<details>
<summary>gpg 2.3.x --version output</summary>

```
$ gpg --version
gpg: error reading symlink '/proc/curproc/file': No such file or directory
gpg (GnuPG) 2.3.3
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/mark/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

</details>

<details>
<summary>gpg 2.2.x --version output</summary>

```
gpg (GnuPG) 2.2.27
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/mark/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

</details>

### Notify maintainers

@fpletz @vrthra 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(mark): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/qcyrhggzysrnsm18kxhqy47wd6bvfk99-source`
```

**Comment by veprbl** [comment]
> `gpg: error reading symlink '/proc/curproc/file': No such file or directory`

This one is a red herring, to be fixed in #155651

**Comment by mikroskeem** [comment]
Adding `disable-ccid` to `~/.gnupg/scdaemon.conf` fixes smart card support.

https://dev.gnupg.org/T5415#145864

**Comment by KyleOndy** [comment]
> Adding `disable-ccid` to `~/.gnupg/scdaemon.conf` fixes smart card support.
> 
> https://dev.gnupg.org/T5415#145864

Had to do this too.

```nix
programs.gpg.scdaemonSettings = { disable-ccid = truel };
```

**Comment by jsfour** [comment]
@mikroskeem your fix worked for me. Thank you.

**Comment by smaret** [comment]
it seems that this has been fixed by #155651. Feel free to reopen if not.

**Comment by mikroskeem** [comment]
FYI issue was actually not about that error message (and its fix #155651). However, [`disable-ccid`](https://github.com/NixOS/nixpkgs/issues/155629#issuecomment-1016622930) provided a fix for described smartcard support.

I am still unsure why builtin CCID driver fails to handle smartcards now. This issue should stay open for further investigation.

**Comment by smaret** [comment]
> FYI issue was actually not about that error message

Sorry for the misunderstanding.

**Comment by tylerlevine** [comment]
This is still an issue for me with gpg 2.3.3.

The `disable-ccid` line in `scdaemon.conf` workaround does work for me to get `gpg` working, but it breaks `ykman` commands (eg, `ykman info`).

I added this to remove the `disable-ccid` line and reload `gpg-agent` before `ykman` invocations and put it back after.

It feels very hacky but I couldn't find a better way to get both `gpg` and `ykman` working at the same time.

```
  programs.zsh = {
    enable = true;

    # hack to avoid issues with gpg 2.3 needing CCID driver disabled for gpg,
    # but needing it enabled to use ykman
    initExtra = ''
      function ykman() {
        local SCDAEMON_CONF="$HOME/.gnupg/scdaemon.conf"
        [[ -e "$SCDAEMON_CONF" ]] && rm "$SCDAEMON_CONF" && pkill gpg-agent
        command ykman $*
        [[ ! -e "$SCDAEMON_CONF" ]] && echo "disable-ccid" > "$SCDAEMON_CONF" && pkill gpg-agent
      }
    '';
  };
```

**Comment by colemickens** [comment]
You're probably missing udev rules or whatever the mac equivalent is. I covered this and provided lots of various working/non-working configurations, with/without "disable-ccid" when I did the gpg23 PR.

**Comment by colemickens** [comment]
See: `hardware.gpgSmartcards.enable`.

**Comment by jbg** [comment]
I'm facing this problem with gpg 2.3.7 on Darwin, and `disable-ccid` in scdaemon.conf doesn't fix it.

After downgrading to 2.3.6 it works again (only with `disable-ccid` though).

On 2.3.7, with `disable-ccid` the card does light up when I run `gpg --card-status`, but then I get:

```
gpg: selecting card failed: Operation not supported by device
gpg: OpenPGP card not available: Operation not supported by device
```

Without `disable-ccid`, the card doesn't even light up (and output is the same).

**Comment by terlar** [comment]
I don't think this new issue is related to `disable-ccid`. I'm on Linux and `2.3.6` works without issues (I don't have `disable-ccid`), however when upgrading to `2.3.7` it is broken.

I don't get any errors/warnings when running `gpg --card-status`. But the card is not properly recognized:

**2.3.6**
```
$ gpg --card-status
Reader ...........: 1050:0407:X:0
Application ID ...: <REMOVED>
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Yubico
Serial number ....: <REMOVED>
Name of cardholder: <REMOVED>
Language prefs ...: en
Salutation .......: 
URL of public key : <REMOVED>
Login data .......: <REMOVED>
Signature PIN ....: not forced
Key attributes ...: ed25519 cv25519 ed25519
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 0 3
Signature counter : 114
KDF setting ......: on
UIF setting ......: Sign=off Decrypt=off Auth=off
Signature key ....: <REMOVED>
Encryption key....: <REMOVED>
Authentication key: <REMOVED>
General key info..: <REMOVED>
```

**2.3.7**
```
$ gpg --card-status
Reader ...........: 1050:0407:X:0
Application ID ...: <REMOVED>
Application type .: OpenPGP
Version ..........: 1.0
Manufacturer .....: ?
Serial number ....: <REMOVED>
Name of cardholder: [not set]
Language prefs ...: [not set]
Salutation .......: 
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: not forced
Max. PIN lengths .: 3 -2 0
PIN retry counter : 0 0 0
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]
```

**Comment by psanford** [comment]
This is the upstream bug in GPG: https://dev.gnupg.org/T6070.
