### ISSUE TITLE
fcitx-qt5 is not working with qt55 applications

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#15569]
## Issue description

`fcitx` is not working in `qt55` applications.

This is probably caused because the fcitx qt5 module, `fcitx-qt5`, is using `qt56` (as being a part of `kde5` package set).

This effect is that fcitx is not working in applications that use `qt55.callPackage` such as `calibre` or `qutebrowser`.

### Steps to reproduce

Enable fcitx and try a qt55 application.

## Technical details

* System: 16.09.git.a71cc6a (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre83796.d541e0d

## Workaround

Use iBus as a replacement.

**Comment by ericsagnes** [comment]
@ttuegel Do you have any suggestion on how this could be addressed?

**Comment by ttuegel** [comment]
`fcitx-qt5` should be added to [`qt5LibsFun`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L8755) so there will be a version for each Qt 5 version: `qt55.fcitx-qt5`, `qt56.fcitx-qt5`, etc. Unfortunately, it will not be possible at this time to use both versions at once in different applications due to #15498.

**Comment by ericsagnes** [comment]
@ttuegel I see, so there is nothing much that can be done at the moment.

I am still not very sure about how qt/kde packages are working so the following questions might be silly, but  at the moment `fcitx-qt5` is in `kde5PackagesFun` because it depends on `extra-cmake-modules`, so:

- Is it fine to have `fcitx-qt5` in `kde5PackagesFun` and `qt5LibsFun` at the same time?
- I tried to put `fcitx-qt5` in `qt5LibsFun` and build the package with `nix-build -A qt55.fcitx-qt5` but it failed with `called without required argument ‘extra-cmake-modules’`, is something missing?
- After #15498 get fixed, should `kde5.fcitx-qt5` in the [fcitx wrapper](https://github.com/NixOS/nixpkgs/blob/f6eb6862221bff46a143fb10b1c16a5ce1f32027/pkgs/tools/inputmethods/fcitx/wrapper.nix#L18) be replaced by `qt55.fcitx-qt5 qt56.fcitx-qt5`?

**Comment by ttuegel** [comment]
> I tried to put fcitx-qt5 in qt5LibsFun and build the package with nix-build -A qt55.fcitx-qt5 but it failed with called without required argument ‘extra-cmake-modules’, is something missing?

I didn't realize `fcitx-qt5` depended on KDE 5 as well as Qt 5. In that case, there is no way to have multiple versions of `fcitx-qt5`.

**Comment by ericsagnes** [comment]
> I didn't realize fcitx-qt5 depended on KDE 5 as well as Qt 5. In that case, there is no way to have multiple versions of fcitx-qt5.

This is unfortunate.

It seems that `fcitx-qt5` is only using ecm in a [few places](https://github.com/fcitx/fcitx-qt5/search?q=ECM&type=Code&utf8=%E2%9C%93), I wonder if it could be patched to remove the dependency so it could go in `qt5LibsFun`.

I will search in this direction and update the issue when I make some progress.

**Comment by ericsagnes** [comment]
Patched `fcitx-qt5` in #15584 so it get part of `qt5LibsFun` and removed the KDE 5 dependency.

**Comment by ericsagnes** [comment]
fixed by #15584
