### ISSUE TITLE
Guided installer

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#15573]
Given that options are organized hierarchically and have type annotations, it should in principle be straightforward (though a decent amount of work) to have a general tool for guiding users through the options available in the install process. Bonus points if it can automatically partition/format drives based on the filesystems options.

Moved from https://github.com/NixOS/nixos/issues/99

**Comment by lukeadams** [comment]
comment on UI mockup by @nbp from the original issue:
reminds me of the Visual Studio Code configuration editor:
![settings_lang-based-settings](https://user-images.githubusercontent.com/3508077/32412203-375e20ae-c1be-11e7-9ec2-29ad8dd358d4.png)
In our case, it would have a searchable list of options on the left, on the right only the local configuration.nix.

**Comment by nbp** [comment]
I want to add making the module system tooling friendly would be simple if we were to add a directory which contains a bunch of files, each having a single option definition.

Another point which might help would be to associate html form templates for each option type, and refine for some specific option declarations.  Thus we could make a web UI for tuning each of these parameters.  For example, we could a generic input type for strings, for packages, for integers, and have more specific one for timezones, keyboard layouts.

**Comment by davidak** [comment]
See also https://github.com/NixOS/nixpkgs/issues/21662

**Comment by davidak** [comment]
still needed to make nixos more accessible

**Comment by davidak** [comment]
still needed

**Comment by samueldr** [comment]
stale, sure... desired still? yes.
