### ISSUE TITLE
Epub format for manual

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#15575]
@silverhook:

I really like the fact that the NixOS manual is easy to find and browse and it's very nicely written as well.

What would make the manual even more usable for me would be if there was a usable downloadable file, so I can read it offline comfortably on an e-ink ebook reader.

Therefore I would propose that the NixOS manual (and Nix etc.) should be uploaded in ePUB and PDF format.

PDF is a very good format for documents that you want to send to someone to print and make sure their output is (pretty much) the same as yours. But they don't reflow the text and reading an A4 PDF on a A5 ebook reader is a bit of a pain. So we need a PDF version for printing and something else for reading on different screens.

EPUB is a (flexible and) reflowing open format and intended to be read in browsers, different screens and ebook readers.

It shouldn't be too much of an effort to export to, since ePUB is by definition just HTML, CSS, JavaScript and metadata put into a ZIP.

Ported from https://github.com/NixOS/nixos/issues/237

**Comment by grahamc** [comment]
@domenkozar Can you remove the code block formatting? It makes it very difficult to read the report. Interesting request, though.

**Comment by domenkozar** [comment]
done

**Comment by domenkozar** [comment]
Done in #15575
