### ISSUE TITLE
haskell-updates: ld.gold error with unreadable /lib on aarch64-linux aka nix-on-droid

### ISSUE THREAD

**Issue by 573** [NixOS/nixpkgs#155722]
### Describe the bug
Linking of sample project fails:
>Preprocessing executable 'main' for test-0.0.0..
Building executable 'main' for test-0.0.0..
Linking /data/data/com.termux.nix/files/home/easy-hls-nix/test/dist-newstyle/build/aarch64-linux/ghc-8.10.7/test-0.0.0/x/main/build/main/main ...
/nix/store/l59232a9b5dlip8yi3swyx7km3s35hzj-binutils-2.35.2/bin/ld.gold: error: /lib: can not read directory: Permission denied
collect2: error: ld returned 1 exit status
 `cc' failed in phase `Linker'. (Exit code: 1)

### Steps To Reproduce
1. Build https://github.com/573/aarch64-linux-ld-issue155722-reproduce on master using `nix-build` or `cabal build`, in fact github-actions do that

### Expected behavior
Sample project builds.
The linker should be called with a fallback instead of `/lib` when `/lib` exists but is not readable.

### Additional context
Similar issue https://github.com/nmattia/niv/issues/332.
https://github.com/t184256/nix-on-droid/, the system on which this error occurs has no read permissions on `/lib`.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-linux"`
- host os: `Linux 4.4.111-21427293`
- multi-user?: `no`
- sandbox: `no`
- version: `nix-env (Nix) 2.3.15`
- channels(nix-on-droid): `"nix-on-droid-21.05, nixpkgs-21.05.2796.110a2c9ebbf"`
- nixpkgs: `/nix/store/h7lizyjgzjmpj4pc18jxib40s0p8lns5-e49c2d09f8dbf84c6692baef7951518ed398e0e6.tar.gz`
```

**Comment by 573** [comment]
Applying the workaround described in linked nmattia/niv#332 didn't help either in this case:

```sh
 ~/src/test && cabal2nix . > myproject.nix
```

```nix
# default.nix
{ pkgs ? import <nixpkgs> {} }:
let
   workaround140774 = hpkg: with pkgs.haskell.lib;
    overrideCabal hpkg (drv: {
        enableSeparateBinOutput = false;
    });
in workaround140774 (pkgs.haskell.packages.ghc8107.callPackage ./myproject.nix { })
```

**Comment by 573** [comment]
Asked for help here: https://discourse.nixos.org/t/linker-error-on-aarch64-linux/17296

For a reproduction of this see  https://github.com/573/aarch64-linux-ld-issue155722-reproduce as well (Actions, nix-build section).

**Comment by hmih** [comment]
Is there an update on this? I'm hitting this issue for multiple packages.

**Comment by 573** [comment]
@hmih some person suggested using a more recent ghc (902+ afar).

**Comment by 573** [comment]
The unreadable "/lib" issue is ingrained to how  nix-on-droid (linked https://github.com/t184256/nix-on-droid/discussions/170 above) works, hence I emulated the behaviour https://github.com/573/aarch64-linux-ld-issue155722-reproduce/blob/8a54fd8/.github/workflows/test.yml#L24.

There doesn't seem to be means to handle such circumstance using the linker so I close this for now.

A follow up issue (this time using a remote builder as suggested in https://github.com/t184256/nix-on-droid/discussions/170) is here at https://github.com/haskell/cabal/issues/7950.

Feel free to follow the other ticket or re-open here in case of new findings.
