### ISSUE TITLE
add crowdsec packages (agents and bouncer)

### ISSUE THREAD

**Issue by amaumene** [NixOS/nixpkgs#155822]
**Project description**
CrowdSec - the open-source and participative IPS able to analyze visitor behavior & provide an adapted response to all kinds of attacks. It also leverages the crowd power to generate a global CTI database to protect the user network.

**Metadata**

* homepage URL: https://crowdsec.net
* source URL: https://github.com/crowdsecurity/crowdsec 
* license: mit
* platforms: linux

**Comment by klausagnoletti** [comment]
I am head of community at CrowdSec. Feel free to get in touch if you need any assistance in creating packages for NixOS.

**Comment by aanderse** [comment]
Fantastic! Thank you @klausagnoletti!

**Comment by klausagnoletti** [comment]
No problem. Feel free to join our [Discourse](https://discord.gg/wGN7ShmEE8) to ask for help from our community.

**Comment by 06kellyjac** [comment]
working on this

**Comment by AkechiShiro** [comment]
Hey any news on this @06kellyjac ? I'd be interested in helping to package it as well or trying/testing the draft PR, but I don't know what's the current status.
