### ISSUE TITLE
Impurity causing initrd failing to build.

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#15581]
Two different machines, same nixpkgs commit 6a142de011bb70003e6891aef7987e8409de724b (release-16.03)

On failing machine:

```
$ NIXOS_CONFIG=`pwd`/nixos/modules/virtualisation/nova-image.nix nix-build nixos -A config.system.build.initialRamdisk
these derivations will be built:
  /nix/store/szsgrz95ri6b8nafb2hjx4fysjzm8w6d-initrd.drv
building path(s) ‘/nix/store/6lcvva6gps6sy7kfy8z3r5z77gc1077l-initrd’
cp: missing destination file operand after '.'
Try 'cp --help' for more information.
builder for ‘/nix/store/szsgrz95ri6b8nafb2hjx4fysjzm8w6d-initrd.drv’ failed with exit code 1
error: build of ‘/nix/store/szsgrz95ri6b8nafb2hjx4fysjzm8w6d-initrd.drv’ failed
```

On working machine:

```
$ NIXOS_CONFIG=`pwd`/nixos/modules/virtualisation/nova-image.nix nix-build nixos -A config.system.build.initialRamdisk -K --check
checking path(s) ‘/nix/store/6lcvva6gps6sy7kfy8z3r5z77gc1077l-initrd’
30648 blocks
note: keeping build directory ‘/tmp/nix-build-initrd.drv-2’
error: derivation ‘/nix/store/szsgrz95ri6b8nafb2hjx4fysjzm8w6d-initrd.drv’ may not be deterministic: output ‘/nix/store/6lcvva6gps6sy7kfy8z3r5z77gc1077l-initrd’ differs from ‘/nix/store/6lcvva6gps6sy7kfy8z3r5z77gc1077l-initrd-check’
```

### Observations

- both using chroot
- both have the same hash

The failure seems to happen due to following line returning empty string in file pkgs/build-support/kernel/make-initrd.sh:

```
storePaths=$(perl $pathsFromGraph closure-*)
```

I'll check the difference in `$sourceRoot` now, but the conents should be the same?

**Comment by domenkozar** [comment]
It's ext4 and it's corrupted files (usually happens on sudden power loss).

`nix-store --repair-path /nix/store/igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl` fixes the issue

**Comment by dezgeg** [comment]
Well, I think that is indirectly caused by Nix not doing enough fsync() calls.

**Comment by domenkozar** [comment]
@dezgeg I've had this a few times, if you can fix it I'd be grateful forever :)

**Comment by domenkozar** [comment]
@dezgeg very relevant: https://www.usenix.org/node/186195

**Comment by dezgeg** [comment]
Yes I know it's tricky business in the general case, but AFAICT for Nix the only thing needed is a depth-first fsync of the output path before registering the paths in the SQLite database. Seems like there's even currently an undocumented option `sync-before-registering` to use the big hammer and call `sync()`, but that's likely not very performant. What dpkg seems to do in addition to `fsync` is to use `sync_file_range` to improve performance: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=605009

**Comment by domenkozar** [comment]
It turns out the issue was completely different impurity: https://github.com/snabblab/snabblab-nixos/issues/42#issuecomment-220933393

I'll open a trivial PR soon to address this (testing now if it works)
