### ISSUE TITLE
pcre fails to build for armv6

### ISSUE THREAD

**Issue by jyooru** [NixOS/nixpkgs#155837]
### Describe the bug

pcre fails to build on armv6

### Steps To Reproduce
1. `boot.binfmt.emulatedSystems = [ "armv6l-linux" ];`
2. Build pcre for armv6
3. pcre fails to build

### Expected behavior

pcre successfully builds

### Screenshots

[Log for `9gkfna81nf7mlhndid9h57945nlw6jxq-pcre-8.45.drv`](https://hercules-ci.com/accounts/github/jyooru/derivations/%2Fnix%2Fstore%2F9gkfna81nf7mlhndid9h57945nlw6jxq-pcre-8.45.drv/log?via-job=9a68e29f-7c98-4ce3-adf8-4f54c5e8117d)

### Notify maintainers

> If in doubt, check `git blame` for whoever last touched something.

@zowoq b17d08bf5cb612620d022a53219f99c85a45974a  #149736

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.90, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(joel): `""`
 - channels(root): `"nixos-21.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hintofbasil** [comment]
This is also failing for armv7 on the unstable channel.

**Comment by Artturin** [comment]
builds fine now
