### ISSUE TITLE
Unable to build container with init script

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#155839]
### Describe the bug

After updating from b2737d4980a17cc2b7d600d7d0b32fd7333aca88 to d5dae6569ea9952f1ae4e727946d93a71c507821, my config no longer builds:

```
error: Cannot merge definitions of `system.build.installBootLoader'. Definition values:
       - In `/nix/store/1q3bx2vjp4afq1wglhxgva9rhs69k8ri-source/nixos/modules/virtualisation/container-config.nix': "/nix/store/176gh50y24c0lx2bnnmsvf9wazb73php-coreutils-9.0/bin/true"
       - In `/nix/store/1q3bx2vjp4afq1wglhxgva9rhs69k8ri-source/nixos/modules/system/boot/loader/init-script/init-script.nix': <derivation /nix/store/65w7c71fli7vh0gnqa11272jrc6bqjxj-init-script-builder.sh.drv>
```

Those two modules appear to by enabled by the [copy](https://github.com/jtojnar/nixfiles/blob/1389878159d1957469b4e596894410d83ac35b53/hosts/azazel/vpsadminos.nix#L27-L29) of the [vpsadminos module](https://github.com/vpsfreecz/vpsadminos/blob/754f708a78520c56897d98f846363410bc24c869/os/lib/nixos-container/vpsadminos.nix#L27-L29) I am importing but weirdly, neither of those seem to have changed:

https://github.com/NixOS/nixpkgs/blob/3cbb02087b4c2dfc3be664d7152cec51765e53ef/nixos/modules/virtualisation/container-config.nix
https://github.com/NixOS/nixpkgs/blob/3cbb02087b4c2dfc3be664d7152cec51765e53ef/nixos/modules/system/boot/loader/init-script/init-script.nix

### Steps To Reproduce

Run `nixos-rebuild build-vm -I nixpkgs=$PWD -I nixos-config=<(echo '{ ... }: { boot.isContainer = true; boot.loader.initScript.enable = true; }')`

**Comment by jtojnar** [comment]
Bisecting points to https://github.com/NixOS/nixpkgs/commit/4014fb6a64bc5f68326fc08cbaa83475db1fae8e cc @roberth

**Comment by jtojnar** [comment]
Maybe this should be `mkDefault`?

https://github.com/NixOS/nixpkgs/blob/3cbb02087b4c2dfc3be664d7152cec51765e53ef/nixos/modules/virtualisation/container-config.nix#L21

**Comment by roberth** [comment]
This is great! Those were always in conflict, but one of them won, by luck of the `imports` order. You really don't want to have anything important depend on that, so I'm glad this was caught, although I wish the experience of catching it would be nicer.

> Maybe this should be mkDefault?

That line does feel like a default.

**Comment by roberth** [comment]
Hold on, it seems to be the other way around. That line should be a `mkForce` instead, to disable boot loader stuff for containers.

**Comment by roberth** [comment]
It's kind of the wrong way around, `imports`-ing stuff you don't need and then disabling it, but it's the best we can do without RFC22  / Minimal module list.

I've opened https://github.com/NixOS/nixpkgs/pull/148456 and #153211 to work towards those goals with minimal impact on regular NixOS.

**Comment by jtojnar** [comment]
> Hold on, it seems to be the other way around. That line should be a `mkForce` instead, to disable boot loader stuff for containers.

I would assume VPSAdminOS wants the boot loader even for containers if they are explicitly enabling the init scripts. cc @aither64

**Comment by aither64** [comment]
I don't fully understand all these changes, but yes, I would say that `boot.loader.initScript` (and `system.build.installBootLoader`) is needed when NixOS is in a container. I mean a container run e.g. by LXC, which is what we do on vpsAdminOS. We don't know what is inside the container and depend on it having `/sbin/init`. I think `mkDefault` on `installBootLoader` would work.

**Comment by roberth** [comment]
I thought of the wrong kind of container. https://github.com/NixOS/nixpkgs/issues/155839#issuecomment-1017327629 lgtm.

**Comment by jtojnar** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/155962
