### ISSUE TITLE
nixos-manpages fail to build

### ISSUE THREAD

**Issue by mpscholten** [NixOS/nixpkgs#15580]
## Issue description
Running `nixos-rebuild test` with latest nixpkgs fails with the following error message:
```
building path(s) ‘/nix/store/4ac1c3vya9kdvfkn2cl30263maxzxp25-nixos-manpages’
./man-pages.xml validates
/nix/store/bmahpgk6zwy54n912kh69mka5sla2wzf-stdenv/setup: line 868: 12118 Killed                  xsltproc --nonet --xinclude --param man.output.in.separate.dir 1 --param man.output.base.dir "'$out/share/man/'" --param man.endnotes.are.numbered 0 --param man.break.after.slash 1 --stringparam target.database.document "/nix/store/spd04nkgsxvghm4yz2i39mw1in5pd916-manual-olinkdb/olinkdb.xml" /nix/store/h6cjllv29vykagqy9fik0f2mbipwsrla-docbook-xsl-ns-1.78.1/xml/xsl/docbook/manpages/docbook.xsl ./man-pages.xml
builder for ‘/nix/store/12iwqx50gxdxkwy4vm37kn2mla0ggnzn-nixos-manpages.drv’ failed with exit code 137
```

Looks like the man pages are broken somehow. Any ideas on how to fix it (or atleast work around this, otherwise I cannot update the system) are welcome :) 

### Steps to reproduce

Run `nixos-rebuild test` with the latest nixpkgs master.

## Technical details

* System: NixOS with latest nixpkgs master (16.03.git.d231868M (Emu))
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.de3538c

**Comment by groxxda** [comment]
Are you mixing 16.03 and 16.09? I can not reproduce with current master. 
You may get around by setting `services.nixosManual.enable = false`

**Comment by mpscholten** [comment]
> Are you mixing 16.03 and 16.09?

Thanks for pointing this out 👍 any ideas how to fix that? Thought I can just upgrade the system by upgrading nixpkgs.

**Comment by joachifm** [comment]
@mpscholten I'd advise against running a system built from arbitrary master checkouts; is there a particular reason why you can't use a release channel?

**Comment by mpscholten** [comment]
Some packages I wanted to install were only available via the unstable channel (e.g. https://github.com/NixOS/nixpkgs/pull/15479 or https://github.com/NixOS/nixpkgs/pull/15468, also the latest version of factorio is not part of the latest stable release). But the unstable channel failed to build (same reason as above, the man pages failed to build), so I switched to the latest master to be sure it's not something which is already fixed in later versions.

**Comment by mpscholten** [comment]
Just for documentation purpose: setting `services.nixosManual.enable = false` has worked. Now `nixos-version` is also showing 16.09.

**Comment by joachifm** [comment]
I can't reproduce this either. Without more information, I don't think there's anything more to be done here.

**Comment by mpscholten** [comment]
Ok, the workaround is working pretty well anyways, so the problem is solved for now. Thanks for the help 👍
