### ISSUE TITLE
docker-compose breaks poetry2nix's interpreter

### ISSUE THREAD

**Issue by zupo** [NixOS/nixpkgs#155835]
### Describe the bug

If I add `docker-compose` to my `buildInputs` I can no longer import my Python package. 

### Steps To Reproduce

A Minimal Runnable Example is available on https://github.com/teamniteo/big-sur-poetry-test/tree/ebdf1764f3e34d8990be15b62842172d3df98e23. But basically:

```bash
# Enter nix-shell
$ nix-shell

# Try to import `trivial` package
[nix-shell:~/work/big-sur-poetry-test]$ python -m trivial
/nix/store/hpwbhg5pm8kxd93ar1dva1ixqhbz09n9-python3-3.9.6-env/bin/python3.9: No module named trivial
```

### Expected behavior

Importing works fine.

```bash
# Enter nix-shell
$ nix-shell

# Try to import `trivial` package
[nix-shell:~/work/big-sur-poetry-test]$ python -m trivial
Original
```

### Additional context

This issue was first reported in https://github.com/nix-community/poetry2nix/issues/523 but it seems the problem is not poetry2nix, but rather an unfortunate side effect of how nixpkgs python infra propagates its dependencies.

@adisbladis suggested on Matrix that a possible solution would be to change buildPythonApplication to not propagate python deps

### Notify maintainers

@Frostman, @fabaff, @SuperSandro2000

**Comment by zupo** [comment]
Potentially useful: using latest nixpkgs 21.05 (instead of 21.11), the bug goes away, and `trivial` can be imported. 

https://github.com/teamniteo/big-sur-poetry-test/commit/3a8b74148a8ca5cb5cbfe3704b21633daed42940

**Comment by SuperSandro2000** [comment]
Nothing related to docker-compose but a general thing that combing a program which uses buildPythonApplication and a pythonEnv don't work in nix-shell. Try adding docker-compose to poetry2nix.
