### ISSUE TITLE
nixos-install does not check for signature when downloading substitutes?

### ISSUE THREAD

**Issue by boobiesinc** [NixOS/nixpkgs#15591]
## Issue description

Apparently, roight?!, apparently, `nixos-install` does not check for signature when downloading substitutes
but `nixos-rebuild` does check!
### Steps to reproduce
1. boot from an iso (eg. nixos-minimal-16.09pre83100.25e3c09-x86_64-linux.iso)
2. follow the manual to get to the point to `nixos-install`
3. run `nixos-install` by avoiding the error `Curl error 77` like [so:](https://github.com/NixOS/nixpkgs/pull/15579#issuecomment-220638757)

`# SSL_CERT_FILE="/etc/ssl/certs/ca-bundle.crt" nixos-install`

What you see(no mention of `signed`):
![virtualbox_nixos_test1_21_05_2016_14_18_41](https://cloud.githubusercontent.com/assets/19384416/15448107/24e2a4c4-1f60-11e6-9dbb-caef03b8c70a.png)

This is how `nixos-rebuild` does it(mention of `signed`):
![virtualbox_nixos2_21_05_2016_14_30_04](https://cloud.githubusercontent.com/assets/19384416/15448114/a1090796-1f60-11e6-8000-3572af70cd98.png)
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by Profpatsch** [comment]
If this was ever a problem, it should definitely be fixed in newer nix versions.
