### ISSUE TITLE
Cannot boot 14.02 pre on AMD UEFI system

### ISSUE THREAD

**Issue by Raahul-Kumar** [NixOS/nixpkgs#1559]
I burned the 64 bit iso from here on 20 Jan.

http://releases.nixos.org/nixos/unstable/nixos-14.02pre38165.8088837/

It fails to pass Stage 1 of boot. Ubuntu 13.10 is installed and working on this hardware,
so it is not a kernel fault.

**Comment by geerds** [comment]
ping @Raahul-Kumar

**Comment by geerds** [comment]
I'm closing this issue. If the error still occurs we can reopen it
