### ISSUE TITLE
Shogun derivation installs wrong CMake files (i.e. which point to inexistent /nix/store/path)

### ISSUE THREAD

**Issue by foolnotion** [NixOS/nixpkgs#156098]
### Describe the bug
Using Shogun as a `builtInput` for another CMake-based project fails because the dependent project cannot properly find the shogun library (via its installed cmake files).

### Steps To Reproduce
1. Try to build a derivation based on shogun
2. Cmake files are wrong

### Expected behavior
Everything builds correctly

### Additional context
I am trying to build the following derivation
```nix
{ lib, stdenv, fetchFromGitHub, cmake, eigen, shogun }:
stdenv.mkDerivation rec {
  pname = "feat";
  version = "0.4.2";

  src = fetchFromGitHub {
    owner = "lacava";
    repo = "feat";
    rev = "${version}";
    sha256 = "sha256-mbvASAB3UQ3ObrVOmkLGVOdFtuAOcqotlQGxi2zSPXg=";
  };

  nativeBuildInputs = [ cmake ];

  buildInputs = [ eigen (shogun.overrideAttrs(old: rec {
    doCheck = false;
    cmakeFlags = old.cmakeFlags ++ [ "-DENABLE_TESTING=OFF" ];
  })) ];

  meta = with lib; {
    description = "FEAT is a feature engineering automation tool that learns new representations of raw data to improve classifier and regressor performance.";
    homepage = "https://lacava.github.io/feat";
    license = licenses.gpl3;
    platforms = platforms.all;
  };
}
```

However I get an error at the build generation step:
```
CMake Error at /nix/store/a6y70prh981r98hs1plk24r4rqzx335s-shogun-6.1.4-dev/lib/cmake/shogun/ShogunTargets.cmake:81 (message):
  The imported target "shogun::shogun" references the file

     "/nix/store/a6y70prh981r98hs1plk24r4rqzx335s-shogun-6.1.4-dev/lib/libshogun.so.18.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/nix/store/a6y70prh981r98hs1plk24r4rqzx335s-shogun-6.1.4-dev/lib/cmake/shogun/ShogunTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /nix/store/a6y70prh981r98hs1plk24r4rqzx335s-shogun-6.1.4-dev/lib/cmake/shogun/ShogunConfig.cmake:29 (include)
  CMakeLists.txt:54 (find_package)
```

This indicates that shogun CMake files are not in the right place and/or are pointing towards the wrong paths.

### Notify maintainers
@edwtjo @smancill

**Comment by smancill** [comment]
I fixed the issue with shogun. When installing the configuration files, CMake calculates the prefix to the installed library based on the `$dev` output directory, instead of the default `$out`, and I missed it when I split the derivation into multiple outputs. I wonder why it's not a more widespread issue, only a few derivations patch it.

But that `feat` derivation still doesn't build:

```
feat> /tmp/nix-build-feat-0.4.2.drv-0/source/src/pop/op/learn/n_split.cc:216:30: error: no viable overloaded '='
feat>             class_weights(c) = float(
feat>             ~~~~~~~~~~~~~~~~ ^ ~~~~~~
```

This is in macOS, though. Maybe it works on Linux.

**Comment by foolnotion** [comment]
Thanks, is the fix committed yet? The other error is unrelated and I can fix it.

**Comment by smancill** [comment]
> Thanks, is the fix committed yet? The other error is unrelated and I can fix it.

I'm working on the PR.
