### ISSUE TITLE
pop-shell features missing

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#156033]
### Describe the bug
In `pop-shell`'s tray menu the options "Floating Window Exceptions" & "Active Hint Color" don't work.

### Steps To Reproduce
1. install & enable pop-shell in GNOME (Wayland).
2. open pop-shell's tray menu and try clicking the mentioned options.

### Expected behavior
Further dialogs should open for the respective features.

### Notify maintainers
@genofire

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 5.16.0, NixOS, 22.05 (Quokka)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
- nixpkgs: `/nix/store/1q3bx2vjp4afq1wglhxgva9rhs69k8ri-source`
```

**Comment by genofire** [comment]
I found the problem: the compiled (g)js are not executible in filesystem. I do not know a solution yet.

Most beautiful solution, fix chmod in pop-shell (but how ...).
Or after compiling with an workaround in nix.
Other solutions are set path to gjs during patching.

Till fixing, you can run this features in your in, with calling it per gjs ...
