### ISSUE TITLE
Agda cannot be used with AgdaStdlib from Nixpkgs

### ISSUE THREAD

**Issue by nkaretnikov** [NixOS/nixpkgs#15617]
Looks like that the current state of things is somewhat broken:
1. The version of AgdaStdlib is not tied to Agda, which might cause problems.
2. AgdaStdlib from Nixpkgs cannot be used because Agda attempts to create an interface file next to each library source file, which fails due to a read-only filesystem.

Here's the solution I've found, but I wonder whether we can improve the packages themselves to make this less painful:
1. Install Agda from Nixpkgs via nix-env or nox (I have 2.4.2.3.), so `~/.nix-profile` can be referenced.
2. Clone AgdaStdlib from upstream and switch to the v2.4.0 tag (see above about incompatible versions).
3. Create a `~/bin/agda` shell wrapper (see below) and add that directory to `PATH`.
4. Add this line to `~/.vimrc` to make agda-vim work (I don't use Emacs): `let g:agda_extraincpaths = [$HOME."/agda/agda-stdlib/src"]`.

The wrapper:
```
% cat ~/bin/agda
#!/usr/bin/env bash

set -e

#Agda_datadir=$HOME/agda/agda/src/data       \
#  $HOME/agda/agda/dist/build/agda/agda      \
$HOME/.nix-profile/bin/agda                 \
  --include-path=$(pwd)                     \
  --include-path=$HOME/agda/agda-stdlib/src \
  $@
```

I've also tried building Agda from source by making a shell.nix file with `cabal2nix --shell --sha256 ./. Agda.cabal >
shell.nix` and running: `nix-shell --pure -I ~` (my Nixpkgs clone is in `~/nixpkgs`), `cabal configure && cabal build -j`. That's what the commented out lines are for. Note the `Agda_datadir` variable. It's necessary because Agda uses the `defaultLibDir` function, which relies on the `dist/build/autogen/Paths_Agda.hs` file, which points to nonexistent locations, but it's possible to override with the mentioned environment variable. I'm not using Agda from upstream mainly because agda-vim doesn't support it (yet?).

**Comment by nkaretnikov** [comment]
cc @Fuuzetsu, @copumpkin, @oxij, @Ericson2314.

**Comment by joachifm** [comment]
Possibly related/relevant: https://github.com/NixOS/nixpkgs/issues/15306

**Comment by laMudri** [comment]
The interface files are fixed by #15595. As for tying stdlib versions to Agda versions, I'm not sure how we could go about that, other than by being quick about updating `AgdaStdlib`. We could keep different versions of Agda, but its way of working generally requires global installation (for `agda-mode`, at least).

**Comment by Ericson2314** [comment]
> 2. AgdaStdlib from Nixpkgs cannot be used because Agda attempts to create an interface file next to each library source file, which fails due to a read-only filesystem.

I'm confused. Why wasn't this a problem all along? When I last touched this stuff Agda also made such interface files. I think either it put them elsewhere, or we copied the source in to `$out` while that was still mutable.

**Comment by laMudri** [comment]
@Ericson2314, the new version adds a bunch of builtin modules. See the [release notes](http://hackage.haskell.org/package/Agda-2.5.1/changelog); it's one of the first things. Previously, there was just `Agda.Primitive`, and this was indeed handled in the `postInstall` phase.

**Comment by copumpkin** [comment]
Just ran into this. It seems like none of the Agda stuff works properly?

**Comment by laMudri** [comment]
It should be fixed whenever peti gets round to merging stuff. See #15696.

**Comment by nkaretnikov** [comment]
@copumpkin You could try my workaround if you're in a hurry. It works, at least.

**Comment by laMudri** [comment]
Done via [cabal2nix#226](https://github.com/NixOS/cabal2nix/pull/226) and #16038.
