### ISSUE TITLE
Unbased paranoid thoughts about packages being fetched over HTTP

### ISSUE THREAD

**Issue by 3rd** [NixOS/nixpkgs#156157]
## Issue description
While setting up NixOS on a new computer and watching the logs I was surprised to see the installer trying to fetch a driver package from **Microsoft** over **HTTP**. Needless to say, that make the whole ordeal seem like a child's play, as no amount of sane configuration or post hardening can guarantee anything when any script kiddie and his grandma can MITM you during the setup.
 
That being said, what would be the way to:
- Figure out where that package is coming from?
- Figure out if it was actually downloaded over HTTP and where it ended up being installed (other than doing the setup again)?

Image:
![](https://i.imgur.com/x5pbLa8.jpg)

### Steps to reproduce

- Regular LUKS installation on a Thinkpad X1 Carbon 8th Gen.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre347261.6d8215281b2, nixos-stable-20.09.4407.1c1f5649bb9"`
 - channels(user): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by ivan** [comment]
```
nixpkgs:master# rg drvs/
pkgs/os-specific/linux/firmware/broadcom-bt-firmware/default.nix
11:    url = "http://download.windowsupdate.com/c/msdownload/update/driver/drvs/2017/04/852bb503-de7b-4810-a7dd-cbab62742f09_7cf83a4c194116648d17707ae37d564f9c70bec2.cab";
```

it is not affected by MTIM because nix will ensure that it matches the known hash

```
sha256 = "1b1qjwxjk4y91l3iz157kms8601n0mmiik32cs6w9b1q4sl4pxx9";
```

**Comment by 3rd** [comment]
My bad, totally disregarded that and entered paranoid mode.

**Comment by 7c6f434c** [comment]
And by the way the firmware (it's not code to run on the main CPU, and BT firmware security is a joke even without MITM anyway) in question seems to be served by an Akamai server not provided with an SSL certificate for download.windowsupdate.com anyway.

(And hash needs to match observations from multiple points for an update commit to reach the channel)

**Comment by 3rd** [comment]
Yes, I guess it is what it is. I entered paranoid mode instantly when I saw the http url.
Sorry for the waste of time.
