### ISSUE TITLE
Watchman 4.9 is 4+ years old

### ISSUE THREAD

**Issue by andrewhamon** [NixOS/nixpkgs#156177]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: watchman

current version: 4.9.0
desired version: 2022.01.17.00

###### Notify maintainers

maintainers: @cstrahan 

###### Note for maintainers

Please tag this issue in your PR.

## Watchman is effectively versionless now
[From the watchman website](https://facebook.github.io/watchman/docs/install.html#binary-downloads-for-linux-macos-and-windows-beta):

> Watchman is continuously deployed as it passes our internal test validation inside Facebook and doesn’t use manually assigned or “approved” version numbers.

I'm not sure what this means when it comes to packaging in nix. The version strings are basically dates now, e.g.

```
watchman --version                                                                                                                                          ~/flexport/flexport
2022.01.17.00
```

I probably don't need the latest version, but switching to the homebrew installed version solved some mysterious bugs with dependent tools I was using (namely: `flow`).

**Comment by andrewhamon** [comment]
I've tried my hand at upgrading locally, but I can't yet figure out how to stop it from downloading and building its own deps and instead using deps provided from nix (boost, openssl, etc). Tried passing them as build inputs but to no avail.

**Comment by kgtkr** [comment]
I also want an update for this.
Other facebook packages from nixpkgs may be helpful.

**Comment by peterbecich** [comment]
I am also attempting to update this, have encountered an error: https://github.com/facebook/watchman/issues/1073
