### ISSUE TITLE
Noto-fonts-cjk variable font doesn't work in gedit

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nixpkgs#156131]
### Describe the bug
The variable font build of Noto CJK was displaying tofus on some GTK apps such as gedit. #156080 fixed this in the short term by using the non-variable fonts, but the variable fonts are smaller/better and it would be better to track down why gedit isn't rendering correctly.

### Steps To Reproduce
1. Revert #156080 (88ef0666443aea0f9088a18056f923240fd1424f) if you have it
2. Cherry-pick https://github.com/NickCao/nixpkgs/commit/2cb96de17b9dad600c7bb1a2a14e0a4a6f83933c
3. Start VM test with `nix-build '<nixpkgs/nixos/tests/noto-fonts.nix>'`

### Expected behavior
No tofu, everything renders properly.

### Screenshots
See https://github.com/NixOS/nixpkgs/pull/156080#issuecomment-1019016416 for proper rendering of the VM test.
Improper rendering with the variable fonts looks like:
![image](https://user-images.githubusercontent.com/322214/150623490-a5ced7e5-a194-45f1-b599-50b0fb1e1a3e.png)

### Additional context
Fedora is switching to variable fonts for Noto non-CJK ([link](https://fedoraproject.org/wiki/Changes/DefaultToNotoFonts)). The plan for now is to wait and see if they encounter this problem and fix it, and check back sometimes around Fedora 36 release finalization (2022-04-14). But of course if someone wants to debug it they're welcome to.

### Notify maintainers
I'm the maintainer of the Noto fonts, this is just a tracking issue so I don't forget.

**Comment by Hentioe** [comment]
The system tools UI in my KDE no longer shows Noto Sans SC, but a fallback font. Although I don't have gedit installed, the same phenomenon occurs with my fcitx5. Because it seriously affects normal use, I rolled back to the previous generation to temporarily avoid this problem.

**Comment by tinywrkb** [comment]
Not a NixOS user, but I also hit this issue. This seems to be related to HarfBuzz, and it looks like it's fixed in 4.0.0.

**Comment by midchildan** [comment]
Since Nixpkgs unstable has HarfBuzz 3.3.2, I've created #166600 to switch noto-fonts-cjk back to variable fonts again. 

@tinywrkb Thanks for the heads up!
