### ISSUE TITLE
Noto Fonts CJK fails to build

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#156180]
### Describe the bug
When building my NixOS configuration, `w5r4h4cn7i6yk3xjhhvd7zv28xbbjydj-noto-fonts-cjk-sans-2.004.drv` failed to build.
I’m using `nixos-unstable` as my nixpkgs branch.

<details>

<summary> Error logs (click to expand) </summary>

```none
error: builder for '/nix/store/wx4spfncy8jfxirzqr1izj242p3dgywv-source.drv' failed with exit code 1;
       last 10 log lines:
       >                                  Dload  Upload   Total   Spent    Left  Speed
       > 100   162  100   162    0     0    154      0  0:00:01  0:00:01 --:--:--   154
       > 100  413M    0  413M    0     0   323k      0 --:--:--  0:21:50 --:--:--  317k
       > unpacking source archive /build/9f7f3c38eab63e1d1fddd8d50937fe4f1eacdb1d.tar.gz
       >
       > gzip: stdin: unexpected end of file
       > tar: Unexpected EOF in archive
       > tar: Unexpected EOF in archive
       > tar: Error is not recoverable: exiting now
       > do not know how to unpack source archive /build/9f7f3c38eab63e1d1fddd8d50937fe4f1eacdb1d.tar.gz
       For full logs, run 'nix log /nix/store/wx4spfncy8jfxirzqr1izj242p3dgywv-source.drv'.
error: 1 dependencies of derivation '/nix/store/w5r4h4cn7i6yk3xjhhvd7zv28xbbjydj-noto-fonts-cjk-sans-2.004.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bdnwibjnj6xwwf1hd85nshsjn2l9d9mn-fc-00-nixos-cache.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9cw9clp87vgxk768gfmnwirk5plz5s10-xserver.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/krbb4hzw6ca5c9icqx3nwd5nncz54lx5-fontconfig-conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a0k1z3aybp3y8bzad3g2b84f9n24rkbg-unit-display-manager.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dqm0ygz05dn7xscdcpv1049q3n5i75s3-fontconfig-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wbilm4sk2gkxgq3njar7bapwjbfswddh-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dfzfg8ypkbh3jmfxf3l17cms5al50ac0-nixos-system-buggeryyacht-nixos-22.05.20220119.6d82152.drv' failed to build
```

</details>

### Steps To Reproduce
Build the flake `github:schuelermine/nixos-configuration/81c34993dff48950d17ab476f4a09f8f39596001`

### Expected behavior
The system is buildt

### Notify maintainers

@mathnerd314
@emilazy

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```none
0 /etc/nixos $ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.0, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `"nixos, nixpkgs"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mathnerd314** [comment]
Looks like a download error, the fonts built fine locally for me.

> For full logs, run 'nix log /nix/store/wx4spfncy8jfxirzqr1izj242p3dgywv-source.drv'.

That might be helpful.

But more importantly IMO is that the builds are failing on [Hydra](https://hydra.nixos.org/eval/1739578?filter=noto-fonts-cjk&compare=1739383&full=) due to the Github archive download being too big.  CC @midchildan
Maybe there is some way to limit tar to extracting only the stuff we care about.

**Comment by schuelermine** [comment]
I’ve re-run the thing at least thrice now, it consistently fails

**Comment by schuelermine** [comment]
Is `tar` run before checking the hash or after?

**Comment by Mathnerd314** [comment]
It's [fetchzip](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchzip/default.nix), it unpacks and then hashes.

**Comment by schuelermine** [comment]
Hm. I’m still getting the error…
![Uploading Screenshot from 2022-01-22 19-38-32.png…]()

**Comment by schuelermine** [comment]
Hm. It’s still erroring out…
![Screenshot from 2022-01-22 19-38-32](https://user-images.githubusercontent.com/48802534/150651323-e8f4631c-0dba-4f94-93b3-ea06130b4219.png)

**Comment by schuelermine** [comment]
The font package itself is the same in `nixos-unstable` and `nixpkgs`
![Screenshot from 2022-01-22 20-05-26](https://user-images.githubusercontent.com/48802534/150652037-9da9f76c-262c-4571-94b6-16a5db9e015a.png)

**Comment by midchildan** [comment]
@schuelermine I too believe you're having problems with the download. The size of download indicated by your initial log output is 413MB, while in the next screenshot, it goes down to 274MB. Both are far too small considering that the total size of the unpacked archive is around 4GB. For reference, [Hydra downloaded around 2.9GB](https://hydra.nixos.org/build/165169526/nixlog/1).

**Comment by schuelermine** [comment]
I see. I will try again later, maybe the internet was too spotty.

**Comment by midchildan** [comment]
Since the combined size of Noto Sans CJK and Noto Serif CJK is roughly 300MB, it would probably be best to download the files individually. I could create a PR for this, but first I would have to get some sleep ;-)

**Comment by Eken-beep** [comment]
I am currently having the same issue with the same packages not downloading correctly.

**Comment by azuwis** [comment]
After this https://github.com/NixOS/nixpkgs/pull/135881 merged, this kind of problems can be largely solved by using `sparseCheckout`.

**Comment by Mathnerd314** [comment]
IIRC for GitHub http is preferred to git, because it's somewhat faster (git has more protocol overhead). But in general sparseCheckout could be useful.
