### ISSUE TITLE
RenderDoc-1.16 package fails to build

### ISSUE THREAD

**Issue by kvark** [NixOS/nixpkgs#156119]
### Describe the bug
I'm not able to get RenderDoc package working (any more).

Enabling the package appears to build something and fails:
> /build/source/qrenderdoc/Code/pyrenderdoc/function_conversion.h:328:3: error: could not convert '<lambda closure object>ConvertFunc<std::function<bool(const Bindpoint&)> >::<lambda()>{global_internal_handle, funcname, PyObjectRefCounter(funcptr), ExceptionHandler(exHandle)}' from 'ConvertFunc<std::function<bool(const Bindpoint&)> >::<lambda()>' to 'std::function<bool(const Bindpoint&)>'
/build/source/qrenderdoc/Code/pyrenderdoc/function_conversion.h: In instantiation of 'funcType ConvertFunc(const char*, PyObject*, ExceptionHandler) [with funcType = std::function<bool(const VKPipe::DescriptorBinding&)>; PyObject = _object]':

Final spew:
```
make: *** [Makefile:136: all] Error 2
error: builder for '/nix/store/y8lrdh7xn1l511azb994afwvphc5jbgs-renderdoc-1.16.drv' failed with exit code 2;
       last 10 log lines:
       > compiling .obj/moc_ToolWindowManagerWrapper.cpp
       > compiling .obj/moc_ScintillaDocument.cpp
       > compiling .obj/moc_ScintillaEdit.cpp
       > compiling .obj/moc_ScintillaEditBase.cpp
       > compiling .obj/moc_ScintillaQt.cpp
       > At global scope:
       > cc1plus: note: unrecognized command-line option '-Wno-unknown-warning' may have been intended to silence earlier diagnostics
       > linking ../bin/qrenderdoc
       > [100%] Built target build-qrenderdoc
       > make: *** [Makefile:136: all] Error 2
       For full logs, run 'nix log /nix/store/y8lrdh7xn1l511azb994afwvphc5jbgs-renderdoc-1.16.drv'.
```

### Steps To Reproduce
1. `nix-shell -p renderdoc`

### Expected behavior
Package works, I'm able to run QRenderDoc.

### Additional context
Last time I updated ~ month ago, and it was working.

### Notify maintainers
cc @janson

### Metadata
```
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.5.1, channels(root): "nixos-22.05pre346355.d5dae6569ea", channels(kvark): "", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by FliegendeWurst** [comment]
In NixOS 21.11 and unstable, the packaged version of RenderDoc is 1.17. Did you try updating your channels?

**Comment by kvark** [comment]
Oh wow, 1.17 builds without issues. Thank you!
