### ISSUE TITLE
fetchgit sha256 not matching nix-prefetch-git sha256 due to missing .gitignore

### ISSUE THREAD

**Issue by JJJollyjim** [NixOS/nixpkgs#15627]
## Issue description

When I build my derivation (a python script), I am told that:

```
output path ‘/nix/store/dvpappya941lvvgj4yk6mxmm9mgg1fd5-heckler-b5b29c9’ has r:sha256 hash
‘1ciq2x1v5h9ikycrx463r66v2bnlpmb970bdxgxn46jvpj9vb12n’ when
‘183mhhvl4j3fd8x1pysp0q9v17w8jznwc0nzrrb1g16q0s9lhl3w’ was expected
```

Diffing the directories from `fetchgit` and `nix-prefetch-git`:

```
diff  -r /nix/store/dvpappya941lvvgj4yk6mxmm9mgg1fd5-heckler-b5b29c9 /nix/store/y52axsi0k2nsf0bcqmnsz811wpjasjq9-heckler
Only in /nix/store/y52axsi0k2nsf0bcqmnsz811wpjasjq9-heckler: .gitignore
```

My derivation's `src` is

```
fetchgit {
    url = "git@bitbucket.org:[my private repo]";
    rev = "b5b29c96f75f8498879a719b8ad144851e2f7dfa";
    sha256 = "183mhhvl4j3fd8x1pysp0q9v17w8jznwc0nzrrb1g16q0s9lhl3w";
};
```

Full output of `nix-build`: http://lpaste.net/1532779428856201216
Full output of `nix-prefetch-git`: http://lpaste.net/7543578849573863424

### Steps to reproduce

(I assume):

1. Run `nix-prefetch-git` on a repo with a `.gitignore`
2. Create a derivation using `fetchgit` parameters based on the output of (1.)
3. Attempt to build derivation

I can't make the repo public; let me know how I can otherwise help diagnose.

## Technical details

* System: OS X 10.10 (Yosemite)
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09pre83068.300e495"`
* Git version: `git version 2.8.1` from homebrew is on my path, though `git version 1.9.3 (Apple Git-50)` is the system version.
* Git repo is hosted on BitBucket

**Comment by vcunat** [comment]
The semantics of `fetchgit` and `nix-prefetch-git` changed recently #15469. I believe you just have to use compatible versions &ndash; most likely you want to update your `nix-prefetch-git`.

**Comment by JJJollyjim** [comment]
@vcunat I'm actually running `nix-prefetch-git` straight from master. Might it be the other way around?

**Comment by vcunat** [comment]
Yes. Best use both from the same revision to avoid the problem. I haven't tested it, as I know `fetchgit` calls `nix-prefetch-git` to do the job.

**Comment by JJJollyjim** [comment]
Yep, that fixes it, thanks
