### ISSUE TITLE
[ledger-live-desktop] Changing TTY required before USB being detected

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#156211]
I am unsure if this is an issue with Ledger Live, NixOS or even my PC, but I can confirm it's not an issue with my USB port, USB cable or even Ledger Nano S (used two different ones with the same results).

### Steps To Reproduce
1. Install and open Ledger Live.
2. Connect device when prompted to do so and unlock it.
3. You will get the infamous "device detected but connection failed" error. Retries don't work.
4. Switch to any other TTY and return to your desktop.
5. Retry.
6. It now connects. 
7. Repeat process every time you disconnect the device.

### Expected behavior
Obviously, the device should be connecting on first try. I am not even sure what kind of udev wizardry happens behind the scenes so that swapping TTY causes it to connect properly.

### Additional context
I had to add the additional udev rules recommended by Ledger via `services.udev.extraRules`. Unsure if this same workaround could have worked before that, but I still had the same "device detected but connection failed" error.
```
# HW.1 / Nano
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2581", ATTRS{idProduct}=="1b7c|2b7c|3b7c|4b7c", TAG+="uaccess", TAG+="udev-acl"
# Blue
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0000|0000|0001|0002|0003|0004|0005|0006|0007|0008|0009|000a|000b|000c|000d|000e|000f|0010|0011|0012|0013|0014|0015|0016|0017|0018|0019|001a|001b|001c|001d|001e|001f", TAG+="uaccess", TAG+="udev-acl"
# Nano S
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0001|1000|1001|1002|1003|1004|1005|1006|1007|1008|1009|100a|100b|100c|100d|100e|100f|1010|1011|1012|1013|1014|1015|1016|1017|1018|1019|101a|101b|101c|101d|101e|101f", TAG+="uaccess", TAG+="udev-acl"
# Aramis
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0002|2000|2001|2002|2003|2004|2005|2006|2007|2008|2009|200a|200b|200c|200d|200e|200f|2010|2011|2012|2013|2014|2015|2016|2017|2018|2019|201a|201b|201c|201d|201e|201f", TAG+="uaccess", TAG+="udev-acl"
# HW2
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0003|3000|3001|3002|3003|3004|3005|3006|3007|3008|3009|300a|300b|300c|300d|300e|300f|3010|3011|3012|3013|3014|3015|3016|3017|3018|3019|301a|301b|301c|301d|301e|301f", TAG+="uaccess", TAG+="udev-acl"
# Nano X
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0004|4000|4001|4002|4003|4004|4005|4006|4007|4008|4009|400a|400b|400c|400d|400e|400f|4010|4011|4012|4013|4014|4015|4016|4017|4018|4019|401a|401b|401c|401d|401e|401f", TAG+="uaccess", TAG+="udev-acl"
# Ledger Test
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2c97", ATTRS{idProduct}=="0005|5000|5001|5002|5003|5004|5005|5006|5007|5008|5009|500a|500b|500c|500d|500e|500f|5010|5011|5012|5013|5014|5015|5016|5017|5018|5019|501a|501b|501c|501d|501e|501f", TAG+="uaccess", TAG+="udev-acl"
```

I would also like to add I do not have Gnome installed, so #106733 applies. I use `i3wm` and `sddm`, if that matters.

### Notify maintainers
Pinging @andresilva @thedavidmeister @nyanloutre  @RaghavSood @Th0rgal

**Comment by LunNova** [comment]
Shouldn't need udev rules manually, they're included with `hardware.ledger.enable`. Do you have that turned on?

**Comment by neirenoir** [comment]
> Shouldn't need udev rules manually, they're included with `hardware.ledger.enable`. Do you have that turned on?

Alright, I haven't tested extensively, but after disabling the custom rules, upgrading the system and enabling `hardware.ledger`, it seems to connect to Ledger Live on the first try. I am still having issue having it communicate transactions to Metamask, but I am going to guess it is because my firmware is outdated (and it won't let me update it until I update Ledger Live too; guess I will have to compile it myself), so I will close the issue for now. Thanks for the help!
