### ISSUE TITLE
vulkan-tools errors on installation with an assertion error from vulkan-headers

### ISSUE THREAD

**Issue by darbsh** [NixOS/nixpkgs#156272]
### Describe the bug
vulkan-tools fails with an assertion error from vulkan-headers 

### Steps To Reproduce
1. Add the nixos-unstable-small channel
2. Run `# nix-shell -p vulkan-tools --show-trace`

### Expected behavior
vulkan-tools being installed

### Screenshots
    # nix-shell -p vulkan-tools --show-trace
    error: assertion '(version == (vulkan-headers).version)' failed

       at /nix/store/cqbcz8k1wq604f8b8nc8khamyh2cl6dl-nixos-22.05pre348006.aec48ffcb12/nixos/pkgs/tools/graphics/vulkan-tools/default.nix:11:10:

           10|   # the rest of nixpkgs.
           11|   src = (assert version == vulkan-headers.version;
             |          ^
           12|     fetchFromGitHub {

       … while evaluating the attribute 'src' of the derivation 'vulkan-tools-1.2.189.1'

       at /nix/store/cqbcz8k1wq604f8b8nc8khamyh2cl6dl-nixos-22.05pre348006.aec48ffcb12/nixos/pkgs/stdenv/generic/make-derivation.nix:205:7:

          204|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          205|       name =
             |       ^
          206|         let

       … while evaluating the attribute 'buildInputs' of the derivation 'shell'

       at /nix/store/cqbcz8k1wq604f8b8nc8khamyh2cl6dl-nixos-22.05pre348006.aec48ffcb12/nixos/pkgs/stdenv/generic/make-derivation.nix:205:7:

          204|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          205|       name =
             |       ^
          206|         let    
  

### Notify maintainers
@SuperSandro2000 @Ralith 

### Metadata

```console
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.16, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre348006.aec48ffcb12"`
 - channels(darb): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ralith** [comment]
Fix at https://github.com/NixOS/nixpkgs/pull/156284, thanks for the report. I thought we had tests for this stuff...

**Comment by darbsh** [comment]
#156284 fixed it for me. Thanks!
