### ISSUE TITLE
feature request: use Fedora's pre-signed UEFI shim to support Secure Boot systems

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#156270]
### Describe the bug

My gaming PC really wanted to upgrade to Windows 11 and now it has Secure Boot enabled and I'd prefer not to disable it.

While I'm a bit skeptical of (what I understand of) rhboot/shim, it seems it will allow enrolling any other extra binary at boot time. This is useful for us, since we should presumably be able to just drop in the pre-built shim and then allow users to as-needed add signatures for their next stage bootloader.

(now that I think about it, since the shim is already signed and will already boot anywhere the default UEFI Secure Boot signing keys are enrolled, then it doesn't really represent any risk for us to have a module to optionally deploy this and poke an EFI entry with `efibootmgr`. A would-be attacker would generally be able to side-load the shim into the ESP or boot-from-media into the shim anyway.)

I'm not really sure how the shim finds it's next stage to attempt to boot though.

Also, I'm curious if you considered this @grahamc when evaluating nixos + secure boot.

**Comment by colemickens** [comment]
Also along these lines, it would be nice to have a way to say "grub, don't touch EFI vars, but shim is allowed to use efibootmgr", so that the user could ensure that only the shim is poked into their EFI system boot manager. From what I see, it looks like the "canTouchEFIVars" or whatever is set a level up from the individual bootloader settings.

**Comment by colemickens** [comment]
sounds like new versions of shim will require SBAT (though some verbiage seems to indicate that it might not be required until triggered by actually booting a SBAT-enabled kernel?): https://github.com/rhboot/shim/blob/main/SBAT.md

**Comment by colemickens** [comment]
Fedora's shim is hardcoded to their very custom grub install location (they don't use grub-install so it would be an invasive change to try to accommodate their pathing).

While the EFI entry can override the shim path and the second loader path, it seems like some EFI implementations don't really support this (primarily I'm testing with HyperV and it doesn't show the unicode args in its UI, and I suspect it's just not storing/passing them).

**Comment by danielphan2003** [comment]
I know this is a WIP, but I would love to also have secure boot for systemd-boot.

**Comment by colemickens** [comment]
While I am using this on a few systems, it's really not ideal and probably not worth pursuing. I have too many things going on right now but when I return to this I plan to contribute to DeterminateSystem's `bootspec`, though I have some slight differences in opinions on how to do a certain thing or two. (Particularly I want my SB key on a Yubikey, but I think I have to actually go write a tool to do that first, etc).

This isn't ideal since it (1) effectively requires disabling second-layer of SecureBoot since I can't get mokutil to enroll the kernel hashes properly anyway (2) it seems this extra DB can be stored in NVARs that get cleared, meaning I've been locked out on two systems after upgrading the BIOS and mokutil's exception being cleared. It also just doesn't feel like that much more work to just do it the right way and use my own keys now that I have the lay of the land.

**Comment by x10an14** [comment]
What's the rationale behind closing this? Lanzaboote?

**Comment by colemickens** [comment]
Yeah, sorry I didn't clarify. I didn't like what I did to make the fedora shims work, and it felt like redundant hacky work compared to just using lanzaboote, so I did that. I can re-open this if people would prefer.

**Comment by x10an14** [comment]
That's okay, just wanted to know what you thought/meant that the solution was =)
