### ISSUE TITLE
`bluetooth` command in tlp package fails due to wrapper?

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#15631]
## Issue description
Can't run `bluetooth` script

### Steps to reproduce
    $ which bluetooth
    /run/current-system/sw/bin/bluetooth -> /nix/store/jp40nqmh11x5cfyhwn8yah1ygsl49q67-tlp-0.8/bin/bluetooth

    $ bluetooth on
    Error: unknown device type ".bluetooth-wrapped".

This seems weird:

bluetooth:

     exec -a "$0" /nix/store/jp<snip>67-tlp-0.8/bin/.bluetooth-wrapped "${extraFlagsArray[@]}" "$@"

/nix/store/jp<snip>67-tlp-0.8/bin/.bluetooth-wrapped 

    <snip>
    self=${0##*/}
    
    case $self in
        bluetooth|wifi|wwan)
        <snip>
        *)
            echo "Error: unknown device type \"$self\"." 1>&2
            exit 1
            ;;
    <snip>

It's as if `exec -a` doesn't work.. ? (EDIT: seems like this is expected - see comments below)

Refs: 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/tlp/default.nix
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/make-wrapper.sh

## Technical details

* System: NixOS: 16.03.802.01f5711 (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.802.01f5711"

@abbradar

**Comment by bjornfor** [comment]
IIRC, argv0 set by "exec -a" is defeated by the spawning of the final shell process. I guess argv0 for the process that interprets that "case $self in ..." is ".bluetooth-wrapped" or something like that.

I really hope we eventually come up with a wrapping technique that doesn't break as much as the current one does.

**Comment by bjornfor** [comment]
Run it with strace and you'll see argv0.

**Comment by bjornfor** [comment]
Doh, I see you already pasted the "$self" or "argv0" value. It's late... :-)

**Comment by olejorgenb** [comment]
Yup, I just came back after some further investigation to note that it's probably expected behavior of `exec -a arg0 file` when `file` is a shell script

**Comment by olejorgenb** [comment]
In this case, wouldn't something like this work?

\<storepath\>/bin/bluetooth :

    # snip
    exec <store-path>/real-bin/bluetooth
    
Ie. name the wrapped script/binary the same as the wrapper script, but in a different folder? This would get rid of the ugly `.prog-wrapped` in tools like top, etc. too? I guess there's some drawbacks to that method though?

**Comment by bjornfor** [comment]
AFAIK, the drawback is that the binary is now located in a different directory (not /bin). It may or may not affect the functionality of the program. I think it affects (breaks) _some_ programs though. That's why it isn't the default wrapper behaviour.

Try it!
