### ISSUE TITLE
Update scons to 4.3.0

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#156326]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: scons

current version: 4.1.0
desired version: 4.3.0

###### Notify maintainers

maintainers: @andir 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by wegank** [comment]
Closed by #222960.
