### ISSUE TITLE
Can't build with raspberry pi with flakes

### ISSUE THREAD

**Issue by rasmus-kirk** [NixOS/nixpkgs#156356]
### Describe the bug
I can't rebuild on raspberry pi 4 using flakes.

### Steps To Reproduce
1. Install nixos image and install with the configuration from the wiki:
https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi_4
2. Update channel to nixos-unstable
3. Try rebuilding with a flake
4. It gives the following output:
```
sudo nixos-rebuild switch --flake .#     
[sudo] password for user: 
building the system configuration...
/nix/store/1n4s07415748vn60n3i631sk5njm0061-raspberrypi-builder.sh: illegal option -- g
usage: /nix/store/1n4s07415748vn60n3i631sk5njm0061-raspberrypi-builder.sh -c <path-to-default-configuration> [-d <boot-dir>]
warning: error(s) occurred while switching to the new configuration
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m" 
 - system: `"aarch64-linux"`
 - host os: `Linux 5.10.52, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by colemickens** [comment]
Flakes are largely a import syntax sugar, unless you're hitting a quirk of nixos-rebuild that has since been fixed, I suspect you might have an error in your configuration (since that error is coming out of your configured rpi bootloader option).

Can you please post the config/flake?

**Comment by rasmus-kirk** [comment]
Thank you for the response, you are correct. The issue was that the following options worked on nixos stable but not on nixos unstable:
```
  boot.loader.raspberryPi = {
    enable = true;
    version = 4;
  };
  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;
```
Where it worked if I removed the last option. The flake issue was just me being dumb and forgetting to update my flake config properly instead of just the `/etc/nixos` one. Strangely the error message actually pointed me in the right direction when building with `nixos-rebuild switch` instead of `nixos-rebuild switch --flake .#`.
