### ISSUE TITLE
mpc_cli is missing bash completion

### ISSUE THREAD

**Issue by laalsaas** [NixOS/nixpkgs#156332]
### Describe the bug
The mpc_cli package is missing bash_completion, even though a bash completion file is in the upstream repo under contrib/mpc-completion.bash .

### Steps To Reproduce
1. install the `mpc_cli` package
2. open a terminal and type `mpc <TAB><TAB>`
It tries only to complete with the contents of the current directory

### Expected behavior
mpc should be completed with the mpc subcomands like `play`, `pause`, etc.

### Additional context
On a regular system, the file would have to be installed under /etc/bash_completion.d/ . I don't know whats the nix(os) equivalent to this.

### Notify maintainers
@AndersonTorres
@DriesVanDaele 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/q6ayjwizl0xcbvknkcksy5g4n1ipa6b1-bash-interactive-5.1-p8-dev
copying path '/nix/store/q6ayjwizl0xcbvknkcksy5g4n1ipa6b1-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335443.e84444b14cc"`
 - channels(laalsaas): `"nixos-21.11.334587.e6377ff3554"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by AndersonTorres** [comment]
First, I am not the maintainer of this package. Nonetheless I will review this.

Second, in Nixpkgs we do "almost" the same: we use a special hook that installs those extra files at the `installPhase`.
Now I need to sleep; please wait a bit more.
