### ISSUE TITLE
emscripten

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#15636]
# issue description

using emscripten 1.36.4 (which i packaged myself but which is consitent with 1.35.4 in regards to this error) i can' compile xml.js on nixos 16.03. compiling xml.js on ubuntu with emscripten 1.36.4 works however.

question: what could cause this NixOS injection? i've tried to minimize PATH and other environment variables but the problem probably lies deeper in the way NixOS handles things.

# help

please advice where i could search next.
# steps to reproduce

emconfigure ../libxml2/configure --with-http=no --with-ftp=no --with-python=no --with-threads=no --with-debug

is supposed to set environment variables as CC/CXX which seems to work very well. however, when ./configure is executed it silently sneaks NixOS specific values into the toolchain:

    [pid 30735] execve("/nix/store/n4zpfi4zzw10s2g91v1swkwq41v1afzz-coreutils-8.25/bin/cat", ["cat", 
    "/nix/store/1yc1mxy0qa4dkybvckxdn58i87wmzc36-gcc-wrapper-5.3.0/nix-support/libc-ldflags-before"], 
    [/* 124 vars */] <unfinished ...>

build/config.log:
```
configure:3582: $? = 0
configure:3571: /nix/store/0llznkhcyyndfhwqah01i1zcdhqxrx0d-emscripten-1.36.4/share/emscripten/emcc -v >&5
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.36.4
clang version 3.9.0  (emscripten 1.36.4 : 1.36.4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/phd4xnam50rp46c1xncjnwn1wpy7zas8-emscripten-fastcomp-1.36.4
configure:3582: $? = 0
configure:3571: /nix/store/0llznkhcyyndfhwqah01i1zcdhqxrx0d-emscripten-1.36.4/share/emscripten/emcc -V >&5
ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
configure:3582: $? = 1
configure:3571: /nix/store/0llznkhcyyndfhwqah01i1zcdhqxrx0d-emscripten-1.36.4/share/emscripten/emcc -qversion >&5
ERROR:root:no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '/dev/null', '.bc', '.o', '.obj', '.lo', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
configure:3582: $? = 1
configure:3602: checking whether the C compiler works
configure:3624: /nix/store/0llznkhcyyndfhwqah01i1zcdhqxrx0d-emscripten-1.36.4/share/emscripten/emcc    conftest.c  >&5
configure:3628: $? = 0
configure:3676: result: yes
configure:3679: checking for C compiler default output file name
configure:3681: result: a.out
configure:3687: checking for suffix of executables
configure:3694: /nix/store/0llznkhcyyndfhwqah01i1zcdhqxrx0d-emscripten-1.36.4/share/emscripten/emcc -o conftest    conftest.c  >&5
configure:3698: $? = 0
configure:3720: result:
configure:3742: checking whether we are cross compiling
configure:3750: /nix/store/0llznkhcyyndfhwqah01i1zcdhqxrx0d-emscripten-1.36.4/share/emscripten/emcc -o conftest    conftest.c  >&5
/nix/store/60a1aqx579bjff3c90cw0l1zwyj2qxhg-binutils-2.26-dev/bin/ld: cannot find crt1.o: No such file or directory
/nix/store/60a1aqx579bjff3c90cw0l1zwyj2qxhg-binutils-2.26-dev/bin/ld: cannot find crti.o: No such file or directory
/nix/store/60a1aqx579bjff3c90cw0l1zwyj2qxhg-binutils-2.26-dev/bin/ld: cannot find crtbegin.o: No such file or directory
/nix/store/60a1aqx579bjff3c90cw0l1zwyj2qxhg-binutils-2.26-dev/bin/ld: cannot find -lgcc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3754: $? = 1
configure:3761: ./conftest
../libxml2/configure: line 3763: ./conftest: No such file or directory
configure:3765: $? = 127
configure:3772: error: in `/home/joachim/Desktop/projects/nlnet/xml.js/build':
configure:3774: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

```

a more complete log can be found here:

- https://gist.github.com/qknight/cc64f6965b02971af290ad20b8215784
- https://gist.github.com/qknight/5d5b4fed3c10b1358d8476dbae335d6e

# strace 

this strace shows that now **binutils-2.26-dev/bin/ld** is used for linking. normally that should just be **emcc** as it wraps the linking.

`
strace -s 234 -f emconfigure ../libxml2/configure --with-http=no --with-ftp=no --with-python=no --with-threads=no --with-debug

...
[pid 30725] execve("/nix/store/60a1aqx579bjff3c90cw0l1zwyj2qxhg-binutils-2.26-dev/bin/ld", ["/nix/store/60a1aqx579bjff3c90cw0l1zwyj2qxhg-binutils-2.26-dev/bin/ld", "-dynamic-linker", "/nix/store/x4p1cj8hi8n3xw60hpd62bfd20fi2arl-glibc-2.23/lib/ld-linux-x86-64.so.2", "--eh-frame-hdr", "-m", "elf_x86_64", "-dynamic-linker", "/lib64/ld-linux-x86-64.so.2", "-o", "conftest", "crt1.o", "crti.o", "crtbegin.o", "/run/user/1000/conftest-d7e90f.o", "-lgcc", "--as-needed", "-lgcc_s", "--no-as-needed", "-lc", "-lgcc", "--as-needed", "-lgcc_s", "--no-as-needed", "crtend.o", "crtn.o", "-rpath", "/nix/store/rc6gvgn52z44v1x8sdmmyjc2lili492a-shell/lib64", "-rpath", "/nix/store/rc6gvgn52z44v1x8sdmmyjc2lili492a-shell/lib", "-L/nix/store/97aj51dl9jvn2qyjapi7m2v2gai9mp27-nodejs-4.3.1/lib", "-L/nix/store/g47gdl1h8mzixl9566dnjlwgwvgpyvkr-libtool-2.4.6-lib/lib", "-L/nix/store/x4p1cj8hi8n3xw60hpd62bfd20fi2arl-glibc-2.23/lib", "-L/nix/store/m2ir96lr7a9kmljl5whmndfwgxf291za-gcc-5.3.0-lib/lib", "-rpath", "/nix/store/x4p1cj8hi8n3xw60hpd62bfd20fi2arl-glibc-2.23/lib", "-rpath", "/nix/store/m2ir96lr7a9kmljl5whmndfwgxf291za-gcc-5.3.0-lib/lib"], [/* 125 vars */]) = 0
`

the important parte of the strace with debugging enabled:
- https://lastlog.de/misc/strace-emscripten.txt

**Comment by qknight** [comment]
@bosu @matthewbauer @magnetophon maybe you could have a look?

**Comment by qknight** [comment]
joelmo and me are having a rather big discussion on IRC right now about this problem with a possible solution of adding:
emcc as ld and also adding try linking ld to ld in clang-wrapper

and things like that

**Comment by matthewbauer** [comment]
Looking in emcc it looks like it "fakes" it for the conftest because you can't natively run javascript output. You need to trick configure into thinking EMCC is a real compiler. Try setting the "CONFIGURE_CC" to `which gcc`. If that fixes it we can mod the default.nix to set it by default.

https://github.com/kripken/emscripten/blame/07b87426f898d6e9c677db291d9088c839197291/emcc.py#L187

**Comment by qknight** [comment]
@matthewbauer i've tried **CONFIGURE_CC=`which gcc`** but this needs more experiments.

back on ubuntu with **emscripten-1.36.4** i see that **/usr/bin/ld** from **binutils** is used:

`[pid 13245] execve("/usr/bin/ld", ["/usr/bin/ld", "-z", "relro", "--hash-style=gnu", "--build-id", "--eh-frame-hdr", "-m", "elf_x86_64", "-dynamic-linker", "/lib64/ld-linux-x86-64.so.2", "-o", "conftest", "/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../x86_64-linux-gnu/crt1.o", "/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../x86_64-linux-gnu/crti.o", "/usr/lib/gcc/x86_64-linux-gnu/5.2.1/crtbegin.o", "-L/usr/lib/gcc/x86_64-linux-gnu/5.2.1", "-L/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../x86_64-linux-gnu", "-L/lib/x86_64-linux-gnu", "-L/lib/../lib64", "-L/usr/lib/x86_64-linux-gnu", "-L/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../..", "-L/home/joachim/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin/../lib", "-L/lib", "-L/usr/lib", "/tmp/conftest-efd354.o", "-lgcc", "--as-needed", "-lgcc_s", "--no-as-needed", "-lc", "-lgcc", "--as-needed", "-lgcc_s", "--no-as-needed", "/usr/lib/gcc/x86_64-linux-gnu/5.2.1/crtend.o", "/usr/lib/gcc/x86_64-linux-gnu/5.2.1/../../../x86_64-linux-gnu/crtn.o"], [/* 92 vars */] <unfinished ...>
`

**Comment by qknight** [comment]
@matthewbauer funny as it sometimes, is you pointed me exactly to the right place to find the solution! thanks very much. took me 3 days to figure a way to build this software on NixOS without manual fiddling.

# solution
`export EMCONFIGURE_JS=2` 

before 

`emconfigure ../libxml2/configure --with-http=no --with-ftp=no --with-python=no --with-threads=no`

the xml.js unit test shows that the code runs out of the box! **yay**

# EMCONFIGURE_JS documentation
https://github.com/kripken/emscripten/blame/07b87426f898d6e9c677db291d9088c839197291/emcc.py#L192


```

  # Whether we fake configure tests using clang - the local, native compiler - or not. if not we generate JS and use node with a shebang
Beither approach is perfect, you can try both, but may need to edit configure scripts in some cases
By default we configure in js, which can break on local filesystem access, etc., but is otherwise accurate so we
disable this if we think we have to. A value of '2' here will force JS checks in all cases. In summary:
0 - use native compilation for configure checks
1 - use js when we think it will work
2 - always use js for configure checks
use_js = int(os.environ.get('EMCONFIGURE_JS') or 1)

```

yet i have to find out if this solution really makes me happy. more interesting is, can this be applied to other projects as nix-instantiate, which was used for the **tour of nix** at https://nixcloud.io/tour, also. if so i would really consider releasing the source code but until now it used to be a very huge mess to get things working and byond anything i would want to document.

**Comment by matthewbauer** [comment]
@qknight Awesome! Do you think we should set EMCONFIGURE=2 by default in Nix? I think emscripten is just having trouble finding whatever binutils it needs.

A while back I was looking into making a "crossSystem" for JavaScript - that is an stdenv based for JavaScript that would shim in the relevant emscripten stuff. It's difficult to do though because cross compilation is kind of broken right now.

**Comment by qknight** [comment]
@matthewbauer i will have to evaluate `EMCONFIGURE=2` much more. but option `0` and `1` are probably there, for a reason. next goal is to create a toolchain using emscripten to build the software i'm currently working on automatically (or using nix-shell to hack on it).

**Comment by qknight** [comment]
@matthewbauer 

i've been playing with `stdenv.mkDerivation` but what used to work interactively inside a nix-shell seems to fail in `mkDerivation`. any idea why?

```
json-c = stdenv.mkDerivation rec {
  name = "json-c";

  buildInputs = [ emscripten autoconf automake libtool pkgconfig gnumake ];

  src = ../json-c;

  configurePhase = ''
    export EMCONFIGURE_JS=2 
    ./autogen.sh
    emconfigure ./configure
  '';

  buildPhase = ''
    emmake make
  '';


  installationPhase = ''
    ...
  '';

};
```

**Comment by qknight** [comment]
maybe because of the `~/.emscripten_cache` which is missing then?

**Comment by qknight** [comment]
@matthewbauer 
@domenkozar 

what i do:
nix-shell, then it build the dependencies using `emscripten` and afterwards i can use `make` to hack on our project (here at nixcloud.io).

you asked me if `export EMCONFIGURE_JS=2` is a good thing and should be a default? after using it with these 4 targets, it is the only option which makes it work past the 'check if the compiler produces executable code' section. i also figured that you have to set a `$HOME` variable to make `emscripten` work.

# default.nix
```
with import <nixpkgs> { };

let

libz = stdenv.mkDerivation {
  name="libz";

  buildInputs = [ emscripten autoconf automake libtool pkgconfig gnumake ];

   src = fetchurl {
     url = "http://zlib.net/zlib-1.2.8.tar.gz";
     sha256 = "039agw5rqvqny92cpkrfn243x2gd4xn13hs3xi6isk55d2vqqr9n";
   };

  configurePhase = ''
    export EMCONFIGURE_JS=2 

    # Some tests require writing at $HOME
    HOME=$TMPDIR

    emconfigure ./configure --prefix=$out
  '';

  # FIXME unit tests

  buildPhase = ''
    emmake make
  '';
};

json-c = stdenv.mkDerivation rec {
  name = "json-c";

  buildInputs = [ emscripten autoconf automake libtool pkgconfig gnumake ];

  version = "json-c-0.12-20140410";

  src = fetchgit {
    url = "https://github.com/json-c/json-c";
    rev = "refs/tags/${version}";
    sha256 = "1cj9qvsc8djgs0x9g3xb7szgjpmyqkw4gr3pf26qal35lv2wb1ig";
  };

  configurePhase = ''
    export EMCONFIGURE_JS=2

    # Some tests require writing at $HOME
    HOME=$TMPDIR

    ./autogen.sh
    emconfigure ./configure --prefix=$out
  '';

  buildPhase = ''
    emmake make
  '';

# FIXME unit tests

};

xml-js = stdenv.mkDerivation rec {
  name = "xml-js";

  buildInputs = [ emscripten autoconf automake libtool pkgconfig gnumake ];

  src = ../xml.js/libxml2;

  configurePhase = ''
    export EMCONFIGURE_JS=2

    # Some tests require writing at $HOME
    HOME=$TMPDIR
    autoreconf -if -Wall

    emconfigure ../libxml2/configure --with-http=no --with-ftp=no --with-python=no --with-threads=no --prefix=$out #--with-debug
  '';

  buildPhase = ''
    emmake make
  '';

  # FIXME unit tests

};

# tested to work with emscripten 1.35.4
fastXmlLint = stdenv.mkDerivation rec {
  name = "fastXmlLint";

  buildInputs = [ json-c libz xml-js emscripten gnumake pkgconfig ];

  phases= [ "unpackPhase" "patchPhase" "configurePhase" "buildPhase" "checkPhase" "installPhase" ] ;

  src = ./.;

  configurePhase = ''
    pkg-config --list-all
    pkg-config json-c --libs
 
    export EMCONFIGURE_JS=2

    # Some tests require writing at $HOME
    HOME=$TMPDIR
  '';

  # wrapping make using 'emmake' would remove the required exports for pkg-config to function properly
  buildPhase = ''
    make
  '';

  # FIXME unit tests
  checkPhase = "";

  # this doesn't make much sense yet
  installPhase = ''
    mkdir $out/
    cp -R *.js* $out/
    cp -R *.xhtml $out/
    cp -R *.html $out/
    cp -R codemirror-5.12 $out/
    cp -R html5-rng $out/
    cp -R libreoffice-relax-ng-example $out/
  '';
};

in

stdenv.mkDerivation rec {

  name = "nlnet-${version}";
  version = "0.0.1";

  shellHook = ''
    export HISTFILE=".zsh_history"
    alias make=colormake
    alias c="while true; do inotifywait * -e modify --quiet > /dev/null; clear; make; done"
    alias s="python -m SimpleHTTPServer"
    alias cl="while true; do inotifywait -e modify --quiet ../* > /dev/null; clear; make| head -n 30; done"
  '';

  buildInputs = [ json-c libz xml-js ] ++ [ colormake nodejs emscripten autoconf automake libtool pkgconfig gnumake strace ltrace python openjdk ];

}
```

# Makefile

```

LIBXML20_CFLAGS += `pkg-config libxml-2.0 --cflags`
LIBXML20_LDFLAGS += `pkg-config libxml-2.0 --libs`

JSONC_CFLAGS += `pkg-config json-c --cflags`
JSONC_LDFLAGS += `pkg-config json-c --libs`

ZLIB_CFLAGS += `pkg-config zlib --cflags`
ZLIB_LDFLAGS += `pkg-config zlib --libs`

all: fastXmlLint.c 
        emcc -O3 -Wall -pedantic -Wextra $(JSONC_CFLAGS) $(ZLIB_CFLAGS) $(LIBXML20_CFLAGS) \
                -c fastXmlLint.c\
                -s AGGRESSIVE_VARIABLE_ELIMINATION=1 \
                --llvm-lto 3 \
                -o fastXmlLint.o 

        # https://github.com/kripken/emscripten/issues/2872
        # so -s EMULATE_FUNCTION_POINTER_CASTS=1
        emcc -O3 -Wall -pedantic -Wextra -std=gnu1x -i fastXmlLint.o  $(JSONC_LDFLAGS) $(ZLIB_LDFLAGS) $(LIBXML20_LDFLAGS)\
                -s EXPORTED_FUNCTIONS="['_validate', '_set_schema', '_my_echo', '_set_schema_file', \
                        '_set_relaxNG_schema', '_set_relaxNG_schema_file', '_validate_NG']" \
                -s ASSERTIONS=2 --emit-symbol-map  \
                -s EMULATE_FUNCTION_POINTER_CASTS=1 \
                --memory-init-file 0 \
                --pre-js pre.js \
                --memory-init-file 1 \
                -s TOTAL_MEMORY=234217728 \
                --llvm-lto 3 \
                --closure 0 \
                -o fastXmlLint.js

```
