### ISSUE TITLE
Pantheon not appear in the lightdm's login session list

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#156456]
## Describe the bug
After enabled the `pantheon` with
```
xserver = {
      enable = true;
      displayManager = {
        lightdm={
          enable = true;
        };
        defaultSession = "plasma";
      };

      desktopManager = {
        plasma5 = { enable = true; };
        xfce={enable = true;};
        pantheon = {enable = true;}; # <---THIS LINE!
      };
    };
```
and reboot the computer, I failed to choose the pantheon session in the `lightdm`'s login screen.

### Steps To Reproduce
1. Enable `pantheon` as above.
2. `sudo nixos-rebuild boot`
3. reboot the computer
4. Try to choose `pantheon` in the `lightdm` greeter screen.
5. Only `xfce` and `plasma` (X11 and wayland) are available, and `pantheon` is absent.
### Expected behavior

The `pantheon` sesson should be available in the session select combo box.

### Screenshots
![screen](https://user-images.githubusercontent.com/2651231/150750038-de917061-690d-4292-805e-03c2585f1f17.jpg)
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/jaa5l5g36aj1wwlmk9lqhslclmdqms3x-bash-interactive-5.1-p12-dev
copying path '/nix/store/jaa5l5g36aj1wwlmk9lqhslclmdqms3x-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre347947.689b76bcf36"`
 - channels(astrojhgu): `"android, nixos-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
I will fix this in the next Pantheon update PR.

**Comment by bobby285271** [comment]
The fix should hit nixos-unstable now (https://nixpk.gs/pr-tracker.html?pr=156646) and will be backported to 21.11 in a few weeks (#156723), please feel free to reopen this if the issue still exist.

**Comment by astrojhgu** [comment]
> The fix should hit nixos-unstable now (https://nixpk.gs/pr-tracker.html?pr=156646) and will be backported to 21.11 in a few weeks (#156723), please feel free to reopen this if the issue still exist.

Tested and confirmed that the pantheon item has appeared in the session list. thx!
