### ISSUE TITLE
omnisharp-rosyln 1.38.0

### ISSUE THREAD

**Issue by dustinlacewell** [NixOS/nixpkgs#156410]
###### Checklist

- [ x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: omnisharp-rosyln

current version: 1.37.15
desired version: 1.38.0

###### Notify maintainers

maintainers: @tesq0 @ericdallo @corngood

###### Note for maintainers

This version bump includes building omnisharp-rosyln with dotnet-sdk 6.0

Please tag this issue in your PR.

**Comment by corngood** [comment]
Currently we build msbuild and roslyn from source.  I'm a little unsure how to make the transition to .net 6 cleanly.  Anyone have any advice?  Our msbuild doesn't seem to play nice with .net 6.
