### ISSUE TITLE
Distrobox

### ISSUE THREAD

**Issue by X9VoiD** [NixOS/nixpkgs#156514]
**Project description**

Use any Linux distribution inside your terminal. Distrobox uses `podman` or `docker` to create containers using the Linux distribution of your choice. The created container will be tightly integrated with the host, allowing sharing of the HOME directory of the user, external storage, external USB devices and graphical apps (X11/Wayland), and audio.

**Metadata**

* homepage URL: https://distrobox.privatedns.org
* source URL: https://github.com/89luca89/distrobox
* license: GPL-3.0-only
* platforms: linux

**Comment by TheEvilSkeleton** [comment]
Correction: homepage URL is https://distrobox.privatedns.org.

**Comment by deinferno** [comment]
I make it properly work as system package i based it off [this](https://github.com/VergeDX/config-nixpkgs/blob/a177c194cf1fc9e20f7c2fe7cadee67be0d8edd9/packages/cli/distrobox.nix) and removed shebang patches for export and init to avoid nix paths in podman containers
I don't know how to deal with xhost part proper way
```nix
{ config, pkgs, lib, ... }:

let
  distrobox = pkgs.stdenvNoCC.mkDerivation rec {
    pname = "distrobox";
    version = "1.2.12-dev";

    src = pkgs.fetchgit {
      url = "https://github.com/89luca89/${pname}";
      rev = "aa1fe3769a054c90ffb30be577296b65640f0bdb";
      hash = "sha256-CGeK8HtYZDnDXCh8frVb+MPcLz8UlRBi/1qUBwZ9jeQ=";
    };

    phases = [ "unpackPhase" "installPhase" ];
    unpackPhase = "";

    installPhase = ''
      find . \( -not -name "distrobox-init" -and -not -name "distrobox-export" \) -type f | while read -r x; do patchShebangs "$x"; done
      mkdir -p $out/bin
      ./install -p $_
    '';
  };
in
{
    environment.systemPackages = [ pkgs.xorg.xhost distrobox ];
    virtualisation.podman.enable = true;
    virtualisation.podman.dockerCompat = true;
    environment.shellInit = ''
    [ -n "$DISPLAY" ] && xhost +si:localuser:$USER || true
    '';
}
```
