### ISSUE TITLE
the-powder-toy segfaults on aarch64-darwin

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#156625]
### Describe the bug
the-powder-toy segfaults when trying to execute it on aarch64-darwin.

```ShellSession
$ ./result/bin/powder
[1]    90495 killed     ./result/bin/powder
$ echo $?            
137
```

### Steps To Reproduce
```ShellSession
$ NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix run --impure nixpkgs#the-powder-toy
```

### Expected behavior
It should run and launch the game.

### Notify maintainers
@abbradar @siraben @NixOS/darwin-maintainers

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixpkgs-22.05pre348320.cc68710784f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by wegank** [comment]
It is fixed upstream from snapshot-231. Should we bump the version or make a patch?

**Comment by prusnak** [comment]
fix (update to latest commit) in https://github.com/NixOS/nixpkgs/pull/189098
