### ISSUE TITLE
mp3 contains video data, so trying to install ffmpeg

### ISSUE THREAD

**Issue by douineauromain** [NixOS/nixpkgs#15666]
Hello, 

It's strange, for me options `--extract-audio --audio-format mp3` with a youtube  link create me a big mp3 file which contains also video data.

but when I try to install 'ffmpeg' I have :
`E: Package 'ffmpeg' has no installation candidate`
on Ubuntu 14.04 64bits.

So I tried `sudo apt-get install -y libav-tools` which worked but `-bash: ffmpeg: command not found`.

So I tried following commands :
```
apt-get dist-upgrade
add-apt-repository -y ppa:mc3man/trusty-media
apt-get update
apt-get install -y ffmpeg
```

according to https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media

And I got it !
```
~# ffmpeg
ffmpeg version N-80026-g936751b Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

But my .mp3 still have video data 😞

**Comment by joachifm** [comment]
Wrong issue tracker?

**Comment by douineauromain** [comment]
I use https://www.npmjs.com/package/youtube-dl like this :
```
var options = ['--extract-audio', 
                       '--audio-format', 'mp3',
                       '--audio-quality', '7'];
var video = youtubedl(urlForYoutubeDl, options);
video.pipe(fs.createWriteStream('../public/'+songPathName));
```
I have ffmpeg installed.

But got the video in the mp3 :
![video mp3](http://g.recordit.co/H9Lu3F9E9Y.gif)

**Comment by douineauromain** [comment]
Sorry I don't understand why my issue was close

**Comment by 7c6f434c** [comment]
This is neither Ubuntu bug tracker nor `youtube-dl` bug tracker. This is Nixpkgs bug tracker, and there are no indications you are using Nix package manager in your issue. So, wrong bug tracker, just as you was told.

**Comment by douineauromain** [comment]
@7c6f434c  Oops sorry I haven't seen 😨
