### ISSUE TITLE
Tetrio does not install

### ISSUE THREAD

**Issue by Mateiadrielrafael** [NixOS/nixpkgs#156686]
### Describe the bug
Trying to install tetrio fails (see screenshots)

### Steps To Reproduce
1. Install tetrio-desktop from nixpkgs-unstable (I did it using a flake)

### Expected behavior
The package should install with no errors.

### Screenshots
![image](https://user-images.githubusercontent.com/39400800/150967207-92de6fb0-6a5d-4352-98dd-cbb6053c7421.png)

### Notify maintainers

@wackbyte 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.06 MiB download, 0.32 MiB unpacked):
  /nix/store/3k69hbxg04sdxlgi1236ddggs346sxf3-stdenv-linux
  /nix/store/p5lnl4zr45n7mf9kz9w8yz3rqh001b5c-bash-interactive-4.4-p23-dev
copying path '/nix/store/p5lnl4zr45n7mf9kz9w8yz3rqh001b5c-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/3k69hbxg04sdxlgi1236ddggs346sxf3-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.05.4132.24528474d2b"`
 - channels(adrielus): `"nixos-21.05.4132.24528474d2b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wackbyte** [comment]
Oops, it looks like I accidentally used a non-direct download link for the source. It also looks like audio is broken, so I'll start a PR soon.

**Comment by wackbyte** [comment]
@Mateiadrielrafael is it working for you now?
