### ISSUE TITLE
GNOME 3 window decoration theme broken

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#15661]
## Issue description

Using the default Adwaita theme, window decorations are not themed correctly (note the square corners and narrow window decoration)

![gnome-shell-theme](https://cloud.githubusercontent.com/assets/123539/15498122/7368212e-219e-11e6-995d-f3a3cc71c43f.png)

The colors of buttons in client-side window decorations are also off:

![nautilus](https://cloud.githubusercontent.com/assets/123539/15498686/e9bfb0f6-21a0-11e6-8231-e06dae9554b6.png)

While it should look like:

![screenshot from 2016-05-24 11-04-09](https://cloud.githubusercontent.com/assets/123539/15498691/ef79bc6c-21a0-11e6-96a2-fbdd2d3850de.png)
## Technical details
- System: 16.09.git.13f67b9 (Flounder)
- Nix version: nix-env (Nix) 1.11.2

where 13f67b9 is a private modification over cc41cb3 on something totally unrelated (unison downgrade).

**Comment by DamienCassou** [comment]
I confirm the problem

**Comment by jtojnar** [comment]
Is this still an issue?

**Comment by DamienCassou** [comment]
Neither @NicolasPetton nor I are using NixOS anymore. I guess this can be safely closed.
