### ISSUE TITLE
Use a different Go version on buildGoModule

### ISSUE THREAD

**Issue by ratsclub** [NixOS/nixpkgs#156650]
### Describe the bug
I want to use a different version of Go on the `buildGoModule` function. Currently it's only possible to use the `pkgs.go` version and not the `go_1_17` needed for some projects.

### Steps To Reproduce
1. Use `buildGoModule`
2. Try to use a different version of Go

### Expected behavior
Being able to use a different Go version.

### Additional context
I wanted to package [blocky](https://github.com/0xERR0R/blocky) but I need Go 1.17 or superior.

**Comment by zowoq** [comment]
```nix
  vault = callPackage ../tools/security/vault {
    buildGoModule = buildGo117Module;
  };
```

**Comment by ratsclub** [comment]
Thanks!
