### ISSUE TITLE
nixos/undervolt: both `cfg.package` and `pkgs.undervolt` are used

### ISSUE THREAD

**Issue by jian-lin** [NixOS/nixpkgs#156668]
### Describe the bug
Both cfg.package and pkgs.undervolt are used in this module. Is it intended or a mistake?

Also, does this module need a `cfg.package`? `pkg.undervolt` seems to be the only package suitable for this module. 

### Notify maintainers

@Atemu @pbogdan @Vodurden 

### Metadata
```console
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.84, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Atemu** [comment]
Thanks for letting me know about this.

I don't think undervolt needs a specific option for a package. If you really need to tweak it, you should use an overlay. I'll remove the option.
