### ISSUE TITLE
Nix on Ubuntu: Rust uses wrong GLIBC.

### ISSUE THREAD

**Issue by paholg** [NixOS/nixpkgs#156739]
### Describe the bug
I am using Nix on Ubuntu 21.10, which includes libc 2.34. When compiling various rust crates, the following error occurs:

```
error: /nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59/lib/libc.so.6: version `GLIBC_2.34' not found (required by /home/paho/git/tokio/target/debug/deps/libasync_stream_impl-7e8fca6e07c3864d.so)
```

I am not certain whether this is a bug, or expected behavior, but I can't for the life of me figure out why the compiler is using nix's libc and not the system one (which is the required version).

### Steps To Reproduce
1. Install Ubuntu 21.10
2. Install nix
3. Install rust
4. Try to compile e.g. tokio:

```
git clone https://github.com/tokio-rs/tokio
cd tokio
cargo build
```

### Expected behavior

Rust uses the system libc and compiles without complaint.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-1011-aws, Ubuntu, 21.10 (Impish Indri)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixpkgs-22.05pre348193.a3d847c3bd3"`
 - channels(paho): `"home-manager, nixgl"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by symphorien** [comment]
How did you install rust ? Are you running in nix-shell ? All compilation-related tasks should be performed inside nix-shell. https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F
Do you also have a system-wide rust and cargo installation ? do you have a manually installed rustup ? 
What is the content of the `LD_LIBRARY_PATH` and `LD_PRELOAD` environment variables ?

**Comment by paholg** [comment]
I have tried installing Rust from Nix and from https://rustup.rs -- the same issue is present in both cases.

This is not running in a nix-shell. I want to use Ubuntu's, not nix's, libc version, and I'm unclear why just having nix installed creates this conflict.

```console
$ echo $LD_LIBRARY_PATH
/nix/store/p36pgcv991mq5srvg765b78yqpxvk3qs-mesa-21.3.3-drivers/lib:/nix/store/gz7695iqdmgipi5kv6inp11pclasaq8x-mesa-21.3.3-drivers/lib:/nix/store/pm77649jvifmdpjn63hrg2lg1kz9ry75-libvdpau-va-gl-0.4.2/lib/vdpau:/nix/store/jkwkz3hnwnv05kd499lp5cfaw86pqkp6-libvdpau-va-gl-0.4.2/lib/vdpau:/nix/store/mgd0q188i52x4a3smsn986z8smqd9zv7-mesa_glxindirect/lib:/nix/store/hisqvx32cd57apbpcsnkpx6k3549wql1-libglvnd-1.4.0/lib:

$ echo $LD_PRELOAD

```

Note: there are various nix directories in `LD_LIBRARY_PATH`, but none of them are the libc directory.

**Comment by symphorien** [comment]
I don't think the nix installer populates $LD_LIBRARY_PATH

Can you check if the problem is solved by unsetting it? (`export LD_LIBRARY_PATH=`)

**Comment by symphorien** [comment]
How did you install rust? `nix-env`, `home-manager`, `nix-shell` ? Via `rustup` or by installing `cargo` directly ? Can you reproduce inside `nix-shell --pure -p cargo` ? Can you check that all elements of the toolchain come from the same source (nix or ubuntu): does `which cargo` and `which rustc` show consistent results ?

**Comment by L0g4n** [comment]
I'm also running into this exact problem. I ran into this problem when using the rust toolchain from:
1. rustup (the rustup from nixpkgs)
2. nix-unstable
3. rust-overlay

Initially, I thought switching to the nix version of rust would help, but it does not help. I am installing it all with `home-manager`.
When running inside `nix-shell --pure -p cargo` I can not reproduce this behaviour though, just in my normal nix shell.

**Comment by symphorien** [comment]
Let's focus on the case where you take the toolchain from nixpkgs, not rustup nor the overlay.

Can you check that all elements of the toolchain come from the same source: does which cargo and which rustc show consistent results ?

**Comment by L0g4n** [comment]
If you mean whether `cargo` and `rustc` orginate both from nix. Yes, I do not have it installed in any other way.
```bash
$ which cargo
/home/yk/.nix-profile/bin/cargo
$ which rustc
/home/yk/.nix-profile/bin/rustc
```

**Comment by witchof0x20** [comment]
Sort of similar bug I got
```
error: /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libc.so.6: version `GLIBC_2.33' not found (required by /snip/project/target/release/deps/libproc_macro_error_attr-de641a16be399cfd.so)
   --> /snip/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
    |
284 | pub use proc_macro_error_attr::proc_macro_error;
    |         ^^^^^^^^^^^^^^^^^^^^^

error: could not compile `proc-macro-error` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I was able to resolve this by just
```
rustup uninstall stable
rustup install stable
```

Would a decent solution be to just add another rustup patch to re-patch the various binaries on `rustup install` to avoid uninstalling first?

**Comment by symphorien** [comment]
what is /home/yk/rust-artifacts/debug/deps/libproc_macro_error_attr-c47f23f2c689374f.so ? It's not the cache of cargo as that would be a hidden directory, nor the `target` directory of a cargo project.

Also can you try cargo clean?

**Comment by L0g4n** [comment]
This is just my `CARGO_TARGET_DIR` which overrides the location of cargo placing the build artifacts in one common dir, instead of the default behavior of placing it in the current workspace at `target/`.
It does not really matter since it also happens with the default behavior when running `CARGO_TARGET_DIR="$PWD/target" cargo b

**Comment by symphorien** [comment]
Ok I understand better.
So part of these artifacts where built with a more recent glibc version, it seems. Is the issue fixed when you remove this directory (or run cargo clean, which should have the same effect I think)?

**Comment by symphorien** [comment]
Also: are you using nix's linker ? check that `which cc` and `which ld` point to the store.

**Comment by L0g4n** [comment]
> So part of these artifacts where built with a more recent glibc version, it seems. Is the issue fixed when you remove this directory (or run cargo clean, which should have the same effect I think)?

Yes, that's my suspicion, too. It seems some dependencies are just "too new" that are specified in there, I think. No, it is not fixed when I run `cargo clean` before the build.

> Also: are you using nix's linker ? check that which cc and which ld point to the store.
No, the are the default ubuntu ones.

**Comment by symphorien** [comment]
Ok so you are using a toolchain which is half ubuntu and half nix. That cannot work. I suspect that your issue disappears if you try inside `nix-shell` (but not necessarily --pure, which allows you to keep other ubuntu-installed tools).
Compilers provided by nixpkgs are only meant to work within nix-shell. They only happen to work by chance in simple situation when you install them. See a related problem https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F

My advice: don't install compilers with nix-env or home-manager at all. This will force you to use nix-shell. If thinking about nix-shell is too annoying, there is tooling to improve your workflow. To name a few: direnv, nix-direnv and lorri.s

**Comment by L0g4n** [comment]
I guess that makes sense (considering compiling inside with `nix-shell -p cargo` or `nix-shell --pure -p cargo` works fine).
One thing though, I guess this is a linux thing with GLIBC, as my arm64 darwin (using clang and the LLVM linker) works fine with the same config.

**Comment by symphorien** [comment]
On darwin nix does not ship its own libc because only the proprietary one can work, so there cannot be a libc mismatch. But you would have problems if you tried to link other libraries, I expect.
