### ISSUE TITLE
kernel panic ioremap.c:198 __ioremap_caller+0x2de/0x360()

### ISSUE THREAD

**Issue by kapralVV** [NixOS/nixpkgs#15679]
## Issue description

Please see the part of the dmesg output below: 
It happens during the boot

[    0.519391] ------------[ cut here ]------------
[    0.519400] WARNING: CPU: 0 PID: 1 at /tmp/nix-build-linux-4.4.11.drv-0/linux-4.4.11/arch/x86/mm/ioremap.c:198 __ioremap_caller+0x2de/0x360()
[    0.519403] Info: mapping multiple BARs. Your kernel is fine.
[    0.519406] Modules linked in:

[    0.519414] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.4.11 #1-NixOS
[    0.519417] Hardware name: LENOVO 20BSS01900/20BSS01900, BIOS N14ET33W (1.11 ) 11/09/2015
[    0.519420]  0000000000000000 ffff8802245d7b68 ffffffff812b8fce ffff8802245d7bb0
[    0.519427]  ffffffff8170e648 ffff8802245d7ba0 ffffffff8106e5b2 0000000000006000
[    0.519432]  ffffc90000cb8000 00000000fed10000 0000000000000000 ffff880223c637c0
[    0.519438] Call Trace:
[    0.519448]  [<ffffffff812b8fce>] dump_stack+0x63/0x85
[    0.519455]  [<ffffffff8106e5b2>] warn_slowpath_common+0x82/0xc0
[    0.519462]  [<ffffffff8106e63c>] warn_slowpath_fmt+0x4c/0x50
[    0.519467]  [<ffffffff810749fa>] ? iomem_map_sanity_check+0xba/0xd0
[    0.519473]  [<ffffffff8105fbae>] __ioremap_caller+0x2de/0x360
[    0.519479]  [<ffffffff8105fc47>] ioremap_nocache+0x17/0x20
[    0.519484]  [<ffffffff8103a0fa>] snb_uncore_imc_init_box+0x6a/0x90
[    0.519492]  [<ffffffff81038e8b>] uncore_pci_probe+0xcb/0x1c0
[    0.519497]  [<ffffffff812f68a5>] local_pci_probe+0x45/0xa0
[    0.519505]  [<ffffffff8122eea9>] ? sysfs_do_create_link_sd.isra.2+0x69/0xb0
[    0.519510]  [<ffffffff812f7c7b>] pci_device_probe+0xdb/0x130
[    0.519518]  [<ffffffff813c44a7>] driver_probe_device+0x1f7/0x310
[    0.519525]  [<ffffffff813c4644>] __driver_attach+0x84/0x90
[    0.519531]  [<ffffffff813c45c0>] ? driver_probe_device+0x310/0x310
[    0.519537]  [<ffffffff813c2554>] bus_for_each_dev+0x64/0xa0
[    0.519543]  [<ffffffff813c3d6e>] driver_attach+0x1e/0x20
[    0.519549]  [<ffffffff813c39a1>] bus_add_driver+0x1b1/0x220
[    0.519555]  [<ffffffff81903277>] ? uncore_cpu_setup+0x12/0x12
[    0.519561]  [<ffffffff813c4ed0>] driver_register+0x60/0xe0
[    0.519565]  [<ffffffff812f620c>] __pci_register_driver+0x4c/0x50
[    0.519571]  [<ffffffff81903359>] intel_uncore_init+0xe2/0x2d2
[    0.519576]  [<ffffffff81903277>] ? uncore_cpu_setup+0x12/0x12
[    0.519581]  [<ffffffff81002109>] do_one_initcall+0x99/0x1e0
[    0.519587]  [<ffffffff8108a858>] ? parse_args+0x268/0x3f0
[    0.519593]  [<ffffffff818f50f8>] kernel_init_freeable+0x158/0x1e3
[    0.519598]  [<ffffffff814e20b0>] ? rest_init+0x80/0x80
[    0.519603]  [<ffffffff814e20be>] kernel_init+0xe/0xe0
[    0.519609]  [<ffffffff814e8b7f>] ret_from_fork+0x3f/0x70
[    0.519613]  [<ffffffff814e20b0>] ? rest_init+0x80/0x80
[    0.519622] ---[ end trace 41a33bed694f44bc ]---
### Steps to reproduce

notebook lenovo thinkpad carbon x1
I'll send more details if needed

Please help. Thanks in advance. 
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  16.03.847.8688c17 (Emu)
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  "16.03.847.8688c17"

**Comment by Profpatsch** [comment]
triage: I assume this is not relevant anymore. If it is, please comment.
