### ISSUE TITLE
output path ‘/nix/store/xyz...’ has r:sha256 hash X when Y was expected

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#15675]
## Issue description

```
output path ‘/nix/store/yssgbm6zf3gzngpc7fidz7w3ckzzr3fb-linear-8da21dc’ has r:sha256 hash ‘0f4r7ww8aygxv0mqdsn9d7fjvrvr66f04v004kh2v5d01dp8d7f9’ when ‘08l0z6zrlbals2bwc2abbh31j9gf90vgp8sy3dcrp0knc98bgaa1’ was expected
```

### Steps to reproduce

```
 nix-build -A haskell.packages.ghc801.linear
```

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) `"16.09.git.429463d"`

cc @peti 

I'm not sure how could this happen -- any ideas?

**Comment by peti** [comment]
Maybe you use multiple binary caches that don't agree on the hash of that store path?

**Comment by abbradar** [comment]
Hm, strange. Notice that this happens only with `linear`.....
Oh, I noticed now that `linear` is pulled from git. I'm not sure however how would this hash change, too. Do you success building this package?

**Comment by abbradar** [comment]
I think I've found the problem: commit 64a072e3576daae794712d898efe0fa0f44075a0 has likely caused hashes to change. I'll push a fix for `linear`. This would actually likely change hash of _many_ sources.

**Comment by vcunat** [comment]
There's a thread about this `fetchgit` change https://github.com/NixOS/nixpkgs/pull/15469

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/be5b596deb7f619fdc47dc2d39940bed8bf9a44d
