### ISSUE TITLE
Level up the test functions

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#156785]
**Project description**

 - [ ] move generic testing functions into a separate file. (which may import other files of course)
 - [ ] document them in the Nixpkgs manual

Some functions, off the top of my head:

 - [x] testVersion
 - [x] testEqualDerivation
 - [x] invalidateFetcherByDrvHash
 - [ ] #156613 
 - [ ] nixosTest
 - [ ] nixosTests

**Comment by davidak** [comment]
testVersion,
testEqualDerivation and
invalidateFetcherByDrvHash

are documented here: https://nixos.org/manual/nixpkgs/unstable/#tester-testVersion

nixosTests are documented here

https://nixos.org/manual/nixos/unstable/#sec-nixos-tests
https://nixos.org/manual/nixpkgs/unstable/#var-meta-tests
https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking
