### ISSUE TITLE
compass can't find adaptor for it's own mixins

### ISSUE THREAD

**Issue by doshitan** [NixOS/nixpkgs#15676]
## Issue description

Compass can't seem to find the gem it needs to compile it's own mixins. Is there something else needed beyond just the `compass` package for it to work? I tried modifying the `compass` derivation to explicitly include the `json` gem (and verified the `json` gem was present in the gems folder of the resultant `compass`) and still hit the same error.

@offlinehacker you did the original packaging for compass, are you still using it?
### Steps to reproduce
- `mkdir sass && echo "@import 'compass/css3/transform';" > sass/style.scss`
- `nix-shell -p compass --command 'compass compile --force'`

Results in:

```
    error sass/style.scss (Line 7 of /nix/store/cikvaqhnzma7i7dd5af6r98n634m7jxp-compass-1.0.3/lib/ruby/gems/2.3.1/gems/compass-core-1.0.3/stylesheets/compass/_support.scss: Did not recognize your adapter specification (cannot load such file -- multi_json/adapters/json_gem). for `browsers')
Compilation failed in 1 files.

```
## Technical details
- System: 16.09.git.7465bcd (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre83796.d541e0d"

**Comment by Profpatsch** [comment]
triage: has this been fixed?

**Comment by florianjacob** [comment]
No, still broken.

**Comment by samueldr** [comment]
Closing; I assume it is either fixed, or the original 2016 issue is irrelevant to any similarly observed issue.

If you are facing issues with `compass`, please open a new issue. Feel free to cross-reference with this issue.
