### ISSUE TITLE
When enable private network, NixOS container fail to start if hostname too long

### ISSUE THREAD

**Issue by yuchangyuan** [NixOS/nixpkgs#15682]
## Issue description

The container will fail to start if hostname too long and privateNetwork = true.  Due the length limitation of network interface name, final created veth device name will not match "ve-$hostname", so cause container fail to start. I think we should check hostname length and warn user when this happen. 
### Steps to reproduce

Create any container on a machine which networking.hostName no less than 13 character, and enable private network.
## Technical details
- System: 16.03.836.aff03ae (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.836.aff03ae

**Comment by ericsagnes** [comment]
I just run into this today.
I am for automatically shorten the interface name as it can make sense to have quite long container names.

**Comment by fkjogu** [comment]
I just ran into this again with this (simplified) config:
```
containers.anamelongerthanten = {
    # network configuration
    privateNetwork = true;
    hostAddress = "10.0.1.21";
    localAddress = "10.0.2.21";
    autoStart = true;

    config =
         { config, pkgs, ... }: { ...};
};
```
I'm not too familiar with nix, does the assertion in #30127 also work when the interface name is derived from the container name?

**Comment by florianjacob** [comment]
@fkjogu The assertion is one level deeper than the container module, so the interface name deriving can't have anything to do with it.

From a quick glance: Seems like the container module does not use `config.networking.interfaces` anymore(?) for its network configuration, but a set of hand-rolled scripts instead. Therefore, my general assertion in the `config.networking` module did not trigger, and the `container` module will need its own copy of the assertion, applied to the `name` attribute.
