### ISSUE TITLE
`swapDevices` doesn't create a proper swapfile on btrfs

### ISSUE THREAD

**Issue by 1sixth** [NixOS/nixpkgs#156829]
### Describe the bug

When using `swapDevices` to create and activate a swapfile on btrfs, it fails with messages like this:

```
A dependency job for swap.target failed. See 'journalctl -xe' for details.
warning: the following units failed: swapfile.swap

× swapfile.swap - /swapfile
     Loaded: loaded (/etc/fstab; generated)
     Active: failed (Result: exit-code) since Wed 2022-01-26 18:15:02 CST; 23ms ago
       What: /swapfile
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
         IP: 0B in, 0B out
        CPU: 2ms

Jan 26 18:15:02 toy systemd[1]: Activating swap /swapfile...
Jan 26 18:15:02 toy swapon[125673]: swapon: /swapfile: swapon failed: Invalid argument
Jan 26 18:15:02 toy systemd[1]: swapfile.swap: Swap process exited, code=exited, status=255/EXCEPTION
Jan 26 18:15:02 toy systemd[1]: swapfile.swap: Failed with result 'exit-code'.
Jan 26 18:15:02 toy systemd[1]: Failed to activate swap /swapfile.
warning: error(s) occurred while switching to the new configuration
```

The kernel says:

```
Jan 26 18:15:02 toy kernel: BTRFS warning (device nvme0n1p2): swapfile must not be copy-on-write
```

I am not very familiar with Nix, but after reading the corresponding [swap.nix](https://github.com/NixOS/nixpkgs/blob/17c61e97723ef2b10b60fd497b0e4eebe3b8655c/nixos/modules/config/swap.nix) and [btrfs manual](https://btrfs.readthedocs.io/en/latest/Swapfile.html), it seems that creating a swapfile on btrfs requires disabling copy-on-write for that file (via `chattr +C swapfile`) as well. However, `swap.nix` doesn't do it currently.

BTW, manually creating the swapfile and letting NixOS activating it works fine for me.

### Steps To Reproduce

1. Add `swapDevices = [{ device = "/swapfile"; size = 1024; }];` to `hardware-configuration.nix` (`/` is supposed to be mounted as btrfs).
2. Run `sudo nixos-rebuild switch`.

### Expected behavior

Swapfile is created and activated without any issue.

### Additional context

There is a workaround on NixOS Discourse: <https://discourse.nixos.org/t/how-do-i-set-up-a-swap-file/8323/7>.

### Notify maintainers

@Artturin

### Metadata

- system: `"x86_64-linux"`
- host os: `Linux 5.15.11-zen1, NixOS, 22.05 (Quokka)`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.5.1`
- channels(root): `"nixos-22.05pre348581.c07b471b52b, home-manager"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by felschr** [comment]
I have the same `Failed to activate swap /swapfile.` issue. I already tried disabling copy-on-write for the partition but it still fails:
```
warning: the following units failed: \x2eswap-swapfile.swap

× \x2eswap-swapfile.swap - /.swap/swapfile
     Loaded: loaded (/etc/fstab; generated)
     Active: failed (Result: exit-code) since Mon 2022-01-31 22:55:53 CET; 11ms ago
       What: /.swap/swapfile
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
         IP: 0B in, 0B out
        CPU: 1ms

Jan 31 22:55:53 felix-nixos systemd[1]: Activating swap /.swap/swapfile...
Jan 31 22:55:53 felix-nixos swapon[314309]: swapon: /.swap/swapfile: swapon failed: Invalid argument
Jan 31 22:55:53 felix-nixos systemd[1]: \x2eswap-swapfile.swap: Swap process exited, code=exited, status=255/EXCEPTION
Jan 31 22:55:53 felix-nixos systemd[1]: \x2eswap-swapfile.swap: Failed with result 'exit-code'.
Jan 31 22:55:53 felix-nixos systemd[1]: Failed to activate swap /.swap/swapfile.
warning: error(s) occurred while switching to the new configuration
```

I also still get the `swapfile must not be copy-on-write` warning like @1sixth, even though I added the `nodatacow` attribute to my mount options (afterwards).

My current swap configuration can be found [here](https://gitlab.com/felschr/nixos-config/-/blob/b1aa0d977144b38677021df2495158ed301cbd55/hardware/felix-nixos.nix).

**Comment by 1sixth** [comment]
@felschr Mount `/.swap` with `nodatacow` attribute won't work because:

> Most mount options apply to the whole filesystem and only options in the first mounted subvolume will take effect. This is due to lack of implementation and may change in the future. This means that (for example) you can’t set per-subvolume nodatacow, nodatasum, or compress using mount options.

<https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#mount-options>

**Comment by n8henrie** [comment]
I came up with this yesterday, which seems to work (or at least you can follow the general pattern): https://github.com/n8henrie/nixos-btrfs-pi/blob/master/make_swap.sh

I have `@swap` as a separate subvolume, nothing else on it. Once you've run this to create the swapfile, it seems to mount and function properly from there on out.

But yes, it would be nice if this were taken care of automatically.

**Comment by felschr** [comment]
@n8henrie brilliant, that helped me solve my issue.
While your script didn't work out for me, I was able to adjust it so it did.

I noticed the following warning when running your script:
```
mkswap: /mnt/.swap/swapfile contains holes or other unsupported extents.
        This swap file can be rejected by kernel on swap activation!
        Use --verbose for more details.
```

So, I searched for this and found the following note on ArchWiki:

> Note: Using dd to allocate a swap file is the most portable solution, see [swapon(8) § Files with holes](https://man.archlinux.org/man/swapon.8#Files_with_holes) for details.
— https://wiki.archlinux.org/title/swap#Swap_file

This made the warning disappear for me but running `swapon` still failed for me with `swapon: /mnt/.swap/swapfile: swapon failed: Invalid argument`. Then I compared the script to what I've used in [my partitioning script so far ](https://gitlab.com/felschr/nixos-config/-/blob/2330efa42fd7bd58298dd130ed87ba74abfd63b7/scripts/setup-partitions) and noticed that I used `truncate` instead of `touch` to create the empty swapfile.

The full script I ended up with:
```sh
#!/usr/bin/env bash

set -Eeuf -o pipefail
set -x

main() {
  umount -R /mnt/.swap || true
  mkdir -p /mnt/.swap
  mount -o subvol=@swap,noatime /dev/mapper/enc /mnt/.swap
  cd /mnt/.swap
  truncate -s 0 /mnt/.swap/swapfile
  chattr +C /mnt/.swap/swapfile
  btrfs property set /mnt/.swap/swapfile compression none
  dd if=/dev/zero of=/mnt/.swap/swapfile bs=1M count=8192 status=progress
  chmod 0600 /mnt/.swap/swapfile
  mkswap /mnt/.swap/swapfile
}
main "$@"
```

**Comment by n8henrie** [comment]
Thanks for the update. I originally used `dd` , but switched after reading that `fallocate` should be much faster (and have to admit I can't remember if I tested that change yet -- thank you for the feedback). I've switched it back to `dd`.
