### ISSUE TITLE
Cryptic error message from freebsd trivial-bootstrap.sh

### ISSUE THREAD

**Issue by stebulus** [NixOS/nixpkgs#15683]
## Issue description

When prerequisite packages are missing, trivial-bootstrap.sh fails when the cryptic message "$2: unbound variable".
### Steps to reproduce

Do not install gnugrep.
Install the nix package manager.
Run `nix-env -i hello`
Read the error message.
## Technical details
- System: FreeBSD 10.3
- Nix version: 1.11.2
- Nixpkgs version: 16.09pre83147.df89584

**Comment by Profpatsch** [comment]
triage: any success debugging this?
