### ISSUE TITLE
GNOME Shell is slow to start

### ISSUE THREAD

**Issue by fufexan** [NixOS/nixpkgs#156830]
### Describe the bug
After logging in in GDM and starting GNOME (Wayland), the screen has a grey color (same as the GDM background), and I can't move the cursor. This lasts about 30s-1m until I get to the Shell and everything works. I also can't switch TTYs during that time.

I'm not sure if this is caused by GDM or Shell, and honestly I'm not sure where to start looking. I didn't find related errors in `journalctl` or `dmesg`.

### Steps To Reproduce
1. Choose GNOME session in GDM
2. Log in

### Expected behavior
The desktop should be immediately available, like it usually is.

### Additional context
GNOME version 41.2
Nixpkgs rev: `f3d9d4bd898cca7d04af2ae4f6ef01f2219df3d6`

### Notify maintainers

@NixOS/gnome 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
› nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.0, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by jtojnar** [comment]
You can try to enable more debug info with:

```nix
services.xserver.displayManager.gdm.debug = true;
services.xserver.desktopManager.gnome.debug = true;
```

but it might just be a slow IO when everything is being looked up in `XDG_DATA_DIRS` & co.

**Comment by fufexan** [comment]
I got a log with `journalctl -b`.
[gnome_debug.log](https://github.com/NixOS/nixpkgs/files/7941147/gnome_debug.log)

**Comment by jtojnar** [comment]
I scanned through the log quickly and I see some crashes. Taking core dumps might slow down the system a bit. And also several weird daemons – depending how well their systemd services are written (e.g. what they depend on), that might possibly affect startup too.

**Comment by fufexan** [comment]
Anything I can do to help you debug this further? Or perhaps there's some misconfiguration on my part?

**Comment by jtojnar** [comment]
I would start by [installing debug symbols](https://nixos.wiki/wiki/Debug_Symbols#NixOS) and opening issue for the crashes. Then I would try disabling bunch of the services like gamemoded, syncthing, otd-daemon, openrazer-daemon, and whatever else you can and see if it changed anything. systemd-analyze might also be an useful tool.

**Comment by fufexan** [comment]
I've disabled all those daemons but that didn't change anything. Checking `systemd-analyze` now.

**Comment by fufexan** [comment]
Didn't find much of use in `systemd-analyze`, seems like `NetworkManager-wait-online` takes a whopping 7 seconds but it doesn't impact boot time or Gnome upon disable.

Furthermore, I tested SDDM instead of GDM and the same problem exists. The screen now stays black until Gnome Shell starts and prompts a password entry for keyring.

**Comment by fufexan** [comment]
I think I've found the culprits:
```
› systemd-analyze blame --user
51.418s org.gnome.Shell@wayland.service
51.286s xdg-desktop-portal.service
50.965s xdg-desktop-portal-gnome.service
25.118s evolution-source-registry.service
25.006s gvfs-goa-volume-monitor.service
```

`systemctl --user status <unit>`:
<details>
  <summary>org.gnome.Shell@wayland</summary>
  
    ● org.gnome.Shell@wayland.service - GNOME Shell on Wayland
         Loaded: loaded (/etc/systemd/user/org.gnome.Shell@wayland.service; linked-runtime; vendor preset: enabled)
         Active: active (running) since Wed 2022-01-26 16:42:32 EET; 56min ago
        Process: 2582 ExecCondition=/bin/sh -c test "$XDG_SESSION_TYPE" = "wayland" || exit 2 (code=exited, status=0/SUCCESS)
       Main PID: 2584 (.gnome-shell-wr)
          Tasks: 57 (limit: 14151)
         Memory: 316.4M
            CPU: 2min 15.741s
         CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service
                 ├─ 2584 /nix/store/zqybvl4a2sp4lylzqm4fn8fakmd1v23l-gnome-shell-41.2/bin/gnome-shell
                 └─25526 /nix/store/9408hkxn38x145flsxgkasl4dbjl6xfp-xwayland-21.1.4/bin/Xwayland :1 -rootless -noreset -accessx -core -auth /run/user/1000/.mutter-Xwaylandauth.3TLQG1 -listenfd 4 -listenfd 5 -displayfd 6 -listenfd 7
    
    ian 26 17:36:31 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:36:52 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:36:53 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:37:07 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:37:35 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:38:15 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:38:30 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:39:00 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:39:11 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
    ian 26 17:39:13 io gnome-shell[2584]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
</details>
<details>
    <summary>xdg-desktop-portal</summary>
  
    ● xdg-desktop-portal.service - Portal service
         Loaded: loaded (/etc/systemd/user/xdg-desktop-portal.service; static)
         Active: active (running) since Wed 2022-01-26 16:42:33 EET; 46min ago
       Main PID: 2708 (.xdg-desktop-po)
          Tasks: 6 (limit: 14151)
         Memory: 4.7M
            CPU: 187ms
         CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal.service
                 └─2708 /nix/store/zlzkq9chxaclmq77bgz9k28a8m246fw6-xdg-desktop-portal-1.10.1/libexec/xdg-desktop-portal
    
    ian 26 16:41:40 io systemd[2270]: Starting Portal service...
    ian 26 16:42:32 io .xdg-desktop-po[2708]: Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.gnome: Timeout was reached
    ian 26 16:42:32 io .xdg-desktop-po[2708]: No skeleton to export
    ian 26 16:42:33 io systemd[2270]: Started Portal service.
</details>
<details>
    <summary>xdg-desktop-portal-gnome</summary>

    ● xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)
         Loaded: loaded (/etc/systemd/user/xdg-desktop-portal-gnome.service; static)
         Active: active (running) since Wed 2022-01-26 16:42:32 EET; 50min ago
       Main PID: 2729 (.xdg-desktop-po)
          Tasks: 4 (limit: 14151)
         Memory: 5.7M
            CPU: 239ms
         CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gnome.service
                 └─2729 /nix/store/3vsy2sd22i641a9b6ix83kdjqbffds19-xdg-desktop-portal-gnome-41.1/libexec/xdg-desktop-portal-gnome
    
    ian 26 16:41:40 io systemd[2270]: Starting Portal service (GNOME implementation)...
    ian 26 16:42:32 io systemd[2270]: Started Portal service (GNOME implementation).
</details>
<details>
  <summary>evolution-source-registry</summary>  

    ● evolution-source-registry.service - Evolution source registry
         Loaded: loaded (/etc/systemd/user/evolution-source-registry.service; linked-runtime; vendor preset: enabled)
         Active: active (running) since Wed 2022-01-26 16:42:06 EET; 55min ago
       Main PID: 2681 (.evolution-sour)
          Tasks: 4 (limit: 14151)
         Memory: 40.0M
            CPU: 286ms
         CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/evolution-source-registry.service
                 └─2681 /nix/store/wnqx0560nh9ra0f10ki4dpln085wq4is-evolution-with-plugins/libexec/.evolution-source-registry-wrapped_
    
    ian 26 16:41:40 io systemd[2270]: Starting Evolution source registry...
    ian 26 16:42:06 io .evolution-sour[2681]: Unable to connect to the GNOME Online Accounts service: Eroare la apelul StartServiceByName pentru org.gnome.OnlineAccounts: Limita de timp a fost atinsă
    ian 26 16:42:06 io systemd[2270]: Started Evolution source registry.
</details>
<details>
  <summary>gvfs-goa-volume-monitor</summary>
  
    ● gvfs-goa-volume-monitor.service - Virtual filesystem service - GNOME Online Accounts monitor
         Loaded: loaded (/etc/systemd/user/gvfs-goa-volume-monitor.service; linked-runtime; vendor preset: enabled)
         Active: active (running) since Wed 2022-01-26 16:42:07 EET; 56min ago
       Main PID: 2769 (.gvfs-goa-volum)
          Tasks: 3 (limit: 14151)
         Memory: 1.4M
            CPU: 13ms
         CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/gvfs-goa-volume-monitor.service
                 └─2769 /nix/store/y3slgij3mg56gwx87lr429vj0vdlmv7h-gvfs-1.48.1/libexec/gvfs-goa-volume-monitor
    
    ian 26 16:41:41 io systemd[2270]: Starting Virtual filesystem service - GNOME Online Accounts monitor...
    ian 26 16:42:07 io systemd[2270]: Started Virtual filesystem service - GNOME Online Accounts monitor.
</details>

**Comment by jtojnar** [comment]
Weird, the GNOME portal should unset the environment variable:

https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/081bff6ac8ca7a3f654e1da175be8a511a5359d7/src/xdg-desktop-portal-gnome.c#L206

And so should the plain one:

https://github.com/flatpak/xdg-desktop-portal/blob/75d16f5bf0be547cc3d7bfe55296cda6affc98d6/src/xdg-desktop-portal.c#L366
