### ISSUE TITLE
unityhub 2.4.4

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#156841]
###### Checklist
- [ X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [ X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: unityhub

current version: 2.3.2
desired version: 2.4.4

###### Notify maintainers

maintainers: @tesq0

###### Note for maintainers
Please tag this issue in your PR.

**Comment by JamieMagee** [comment]
Resolved in #204005
