### ISSUE TITLE
`python3Packages.apache-beam` is currently broken

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#156957]
## Issue description
`python39Packages.apache-beam` is failing as of 4d922730369d1c468cc4ef5b2fc30fd4200530e0 with the error:
```
ERROR: Could not find a version that satisfies the requirement typing-extensions<4,>=3.7.0 (from apache-beam) (from versions: none)
ERROR: No matching distribution found for typing-extensions<4,>=3.7.0
```
I believe this failure was caused by https://github.com/NixOS/nixpkgs/pull/152660.

### Steps to reproduce
* Checkout nixpkgs at commit 4d922730369d1c468cc4ef5b2fc30fd4200530e0. 
* `nix-build -A python39Packages.apache-beam`

## Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.91, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335376.610d4ea2750, nix-ld"`
 - channels(skainswo): `"home-manager, nixpkgs-unstable-22.05pre343295.adf7f03d3bf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cmm** [comment]
same thing with flexget (via transmission-rpc, which is also broken).  and I have no idea how to patch (or even locally override) poetry-based python packages :(
