### ISSUE TITLE
Firefox does not take advantage of hardware acceleration even when aviable 

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#157061]
### Describe the bug
Firefox would not take advantage of hardware acceleration, even through 
```
nix shell nixpkgs#libva-utils -c vainfo              
def-matcher: command not found
warning: unknown experimental feature 'ca-references'
libva info: VA-API version 1.13.0
libva info: Trying to open /run/opengl-driver/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Mesa Gallium driver 21.3.3 for AMD RENOIR (DRM 3.44.0, 5.16.2, LLVM 13.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```
And the suggestion at https://wiki.archlinux.org/index.php/Firefox#Hardware_video_acceleration were followed 
### Steps To Reproduce
1. Configure firefox as suggested by the arch wiki
2. MOZ_LOG="PlatformDecoderModule:5" firefox  > log.txt 2>&1
3. Open a video on youtube

### Expected behavior
No frames are dropped

### Additional context
[log.txt](https://github.com/NixOS/nixpkgs/files/7953996/log.txt)

### Notify maintainers
@mweinelt @primeos  
### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.2, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - nixpkgs: `/nix/store/77y898gmsx12v68zng6r00qrpxxq8fqj-source`

**Comment by mweinelt** [comment]
Which firefox version are you using? What display server are you using? Try to confirm that things work with `firefox-bin`, the official Mozilla build.

I have a vague idea in my mind that hwdec does not work on Wayland currently.

**Comment by pasqui23** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1752431

> Which firefox version are you using? What display server are you using? 

Firefox 96 on  plasma wayland, but similar oroblems I've got them even on X11

> Try to confirm that things work with `firefox-bin`, the official Mozilla build.

It seems that on `firefox-bin` there are still dropped frames,

**Comment by mweinelt** [comment]
```
[RDD 157209: MediaSupervisor #1]: D/PlatformDecoderModule Agnostic decoder supports requested type
[RDD 157209: MediaPDecoder #1]: D/PlatformDecoderModule Initialising VA-API FFmpeg decoder
libva info: VA-API version 1.13.0
libva info: Trying to open /run/opengl-driver/lib/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib32/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/i386-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /run/opengl-driver/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
[Child 156806: MediaPDecoder #3]: D/PlatformDecoderModule AudioTrimmer[7fa7c56d9100] ::PrepareTrimmers: sample[0,21000] no trimming information
[Child 156806: Main Thread]: D/PlatformDecoderModule Sandbox RDD decoder supports requested type
libva info: Trying to open /usr/lib32/dri/i965_drv_video.so
[Child 156806: MediaPDecoder #1]: D/PlatformDecoderModule Sandbox RDD decoder supports requested type
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/i386-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[RDD 157209: MediaPDecoder #1]: D/PlatformDecoderModule Failed to create VA-API device context
[RDD 157209: MediaPDecoder #1]: D/PlatformDecoderModule Initialising FFmpeg decoder.
```

On Intel 8th gen iGPU with VA-API support looking just fine.

```
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

**Comment by mweinelt** [comment]
> It seems that on `firefox-bin` there are still dropped frames,

I'm not sure what that means. Does the log indicate VA-API gets used?

**Comment by pasqui23** [comment]
```
r
libva info: VA-API version 1.13.0
libva info: Trying to open /run/opengl-driver/lib/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib32/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/i386-linux-gnu/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
```

**Comment by QuantMint** [comment]
> ```
> r
> libva info: VA-API version 1.13.0
> libva info: Trying to open /run/opengl-driver/lib/dri/radeonsi_drv_video.so
> libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
> libva info: Trying to open /usr/lib32/dri/radeonsi_drv_video.so
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
> libva info: Trying to open /usr/lib/i386-linux-gnu/dri/radeonsi_drv_video.so
> libva info: va_openDriver() returns -1
> ```

Same here in firefox 97 beta 9 installed from the mozilla overlay using an intel gpu.

**Comment by mainrs** [comment]
The issues posted after @pasqui23 seem to be different though. Their driver successfully loads. The other logs show that the driver fails to load, returning `-1`.

**Comment by mweinelt** [comment]
> The issues posted after @pasqui23 seem to be different though. Their driver successfully loads. The other logs show that the driver fails to load, returning `-1`. 

All logs I saw failed to load with -1, care to clarify?

**Comment by mainrs** [comment]
> nix shell nixpkgs#libva-utils -c vainfo              
> def-matcher: command not found
> warning: unknown experimental feature 'ca-references'
> libva info: VA-API version 1.13.0
> libva info: Trying to open /run/opengl-driver/lib/dri/radeonsi_drv_video.so
> libva info: Found init function __vaDriverInit_1_13
> libva info: va_openDriver() returns 0

The very first log. I can later attach mine as well, as mine does _also_ load successfully on an Intel CPU but doesn't show that hardware acceleration is enabled.

**Comment by pasqui23** [comment]
Upstream also asked me about `mesa-va-drivers`,apparently the libva api for AMD?
It seems to be not packaged on NixOS

**Comment by mainrs** [comment]
@pasqui23 https://wiki.archlinux.org/title/Hardware_video_acceleration This post is more detailed.

**Comment by pasqui23** [comment]
@mainrs I have read that wiki article but according to https://bugzilla.mozilla.org/show_bug.cgi?id=1752431#c6 it may be obsolete.

The problem is that it does not seem to be packaged https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=vaapi+mesa

**Comment by mainrs** [comment]
Ah! I wasn't aware of that bug report. Let me know if that mesa package works for you. I still haven't figured it out with Intel.

**Comment by Darkspirit** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1752431#c10
In your latest log, `/run/opengl-driver/lib/dri/radeonsi_drv_video.so` was found and loaded. Maybe it was just blocked by the RDD (media process) sandbox before?

**Comment by QuantMint** [comment]
I have just updated to firefox 98 beta and sadly the issue persists.

**Comment by Darkspirit** [comment]
Does it work if you start Firefox with MOZ_DISABLE_RDD_SANDBOX=1 environment variable?

**Comment by QuantMint** [comment]
> FWIW, I'm using intel's vaapi and the only settings I had to change to get firefox video hardware acceleration were:
> 
> ```
> "media.hardware-video-decoding.enabled" = true;
> "media.hardware-video-decoding.force-enabled" = true;
> ```
> 
> Work on wayland, with both `firefox` and `firefox-bin`. Checked with `MOZ_LOG="PlatformDecoderModule:5" firefox`.

It doesn't work for me.
I have tried intel-media-driver and vaapiIntel but no succes either.
I have also noticed this line while opening firefox with
MOZ_LOG="PlatformDecoderModule:5": 
`[Child 17882: Main Thread]: D/PlatformDecoderModule FFMPEG: VA-API FFmpeg is disabled by platform
`

**Comment by Technical27** [comment]
It seems that Firefox 97 (despite what archwiki claims, maybe from how its packaged) needs the environment variable `MOZ_DISABLE_RDD_SANDBOX=1` and maybe av1 to be disabled with an extension or the config `media.av1.enabled=false`
```
libva info: VA-API version 1.13.0
libva info: Trying to open /run/opengl-driver/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
[RDD 237719: MediaPDecoder #2]: D/PlatformDecoderModule OpusDataDecoder[7f18ea45ca80] ::Decode: Opus decoder skipping 312 of 960 frames
[Child 237555: MediaPDecoder #3]: D/PlatformDecoderModule AudioTrimmer[7ff315aba740] ::HandleDecodedResult: sample[0,21000] (decoded[0,13500] no trimming needed
libva info: va_openDriver() returns 0
```

**Comment by Technical27** [comment]
Nope, nixos-unstable only has Firefox 97

**Comment by immindich** [comment]
To add another data point here, I'm using Firefox 97 on NixOS stable and I have not been able to get video acceleration to work. It seems to work just fine for other applications like mpv, and I don't get any error messages when I run vainfo. I have intel-media-driver installed, since the older Intel driver is not compatible with my hardware.

I am using the `firefox-wayland` package on Plasma, with the following relevant config options set to true:

    media.ffmpeg.vaapi.enabled
    media.rdd-ffmpeg.enabled
    media.hardware-video-decoding.force-enabled
    media.hardware-video-decoding.enabled

However, I still get the message

    D/PlatformDecoderModule FFMPEG: VA-API FFmpeg is disabled by platform

when I run `MOZ_LOG="PlatformDecoderModule:5" firefox`.

**Comment by lovesegfault** [comment]
> @Technical27 is 98 available for nix already? I can't seem to find it thinking

Firefox 98 has not yet been released.

**Comment by KenMacD** [comment]
I also ran in to this issue. Here's my current findings. First what appears to be working for me on 97.0.2:

```
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/run/opengl-driver/lib/:$(nix eval --raw -f '<nixpkgs/nixos>' 'pkgs.intel-gmmlib.outPath')" firefox
```

With only the `media.ffmpeg.vaapi.enabled = true` set in `about:config`.

Okay, so for testing I've been using `MOZ_SANDBOX_LOGGING=1` to see what files are being blocked. There's a few options that are supposed to add paths to an allow list, but unfortunately they're not applied in [the RDD process policy](https://searchfox.org/mozilla-central/rev/9ca193b4233957439583f2eadabbd3cfb4cd9fed/security/sandbox/linux/broker/SandboxBrokerPolicyFactory.cpp#762-824).

I first noticed that the sandbox was blocking access to `/run/opengl-driver/lib/dri/iHD_drv_video.so`. The sandbox adds `/usr/lib` to the allow list, but of course that doesn't help here. It also adds anything in `ld.so.conf` and `LD_LIBRARY_PATH` though, so I put the driver in there. After that it then started complaining about `libigdgmm.so.12`, which is a build input of `intel-media-driver`, so I added that (there's a few others, but they at least didn't complain).

I don't know the best way to solve the overall issue. A partial solution seems to be to set `hardware.opengl.setLdLibraryPath = true`, but that still doesn't add the dependencies of the drivers. Perhaps some ldd magic in the wrapper would be better?

**Comment by mweinelt** [comment]
On Firefox 98.0.2 right now and I can confirm that VA-API with amdgpu works when disabling the RDD sandbox. This is awesome.

@KenMacD Thanks for your findings. Can you tell me where you foudn that `/usr/lib`´was allowed?

**Comment by mweinelt** [comment]
Everyone, feel free to test-drive #165964.

**Comment by Atemu** [comment]
@justinkb make sure you're decoding a video that your GPU is able to accelerate. Many GPUs (especially older ones) don't have VP9 decoder hardware which you need for i.e. YouTube or Netflix.

**Comment by justinkb** [comment]
Yeah, I did verify that. My AMD Radeon RX 6800 supports VP9 acceleration if
I'm reading the vainfo output correctly.

**Comment by amarshall** [comment]
To echo justinkb: I have an Intel 11th-gen iGPU and have

> [Child _____: Main Thread]: D/PlatformDecoderModule FFMPEG: VA-API FFmpeg is disabled by platform

but also

> [RDD _____: MediaPDecoder #1]: D/PlatformDecoderModule FFMPEG: Initialising VA-API FFmpeg decoder
> [RDD _____: MediaPDecoder #1]: D/PlatformDecoderModule FFMPEG:   codec h264 : H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
> libva info: VA-API version 1.13.0
> libva info: Trying to open /run/opengl-driver/lib/dri/iHD_drv_video.so
> [Child _____: Main Thread]: D/PlatformDecoderModule Sandbox RDD decoder supports requested type
> [Child _____: Main Thread]: D/PlatformDecoderModule Sandbox RDD decoder supports requested type
> [Child _____: Main Thread]: D/PlatformDecoderModule Sandbox RDD decoder supports requested type
> libva info: Found init function __vaDriverInit_1_13
> libva info: va_openDriver() returns 0

that being an improvement over before the patch.

However, when observing `intel_gpu_top`, there is no video render usage from Firefox (compared with e.g. mpv).
