### ISSUE TITLE
uTimer

### ISSUE THREAD

**Issue by danielb2** [NixOS/nixpkgs#157011]
**Project description**

µTimer ("utimer", pronounced "micro-timer") is a multifunction timer (command-line only). It provides a timer (e.g. count from 0 to 4 minutes), a countdown (e.g. count from 10 minutes to 0), and a stopwatch.

**Metadata**

* homepage URL: https://launchpad.net/utimer
* source URL: https://launchpad.net/utimer/0.4/0.4/+download/utimer-0.4.tar.gz
* license: GNU GPL v3
* platforms: unix, linux, darwin

**Comment by jansol** [comment]
NB: Homepage says this is no longer maintained and the last update is from 2009.

**Comment by danielb2** [comment]
if a package works as intended, does it matter whether it's being actively developed?

**Comment by jansol** [comment]
It's mostly about having someone take responsibility for fixing it when it breaks for whatever reason. "It's not maintained because it simply doesn't need to" is nice but tends to only work for so long. Even if the code once was "perfect" the environment it runs in is neither perfect nor does it stay the same as when the code was written.

**Comment by danielb2** [comment]
That's a fair concern, but it's still being in use by homebrew, and I came across it on another platform before that (but I don't recall which one).

**Comment by danielb2** [comment]
how long does it get these to get merged?

**Comment by jansol** [comment]
Depends on how busy the people with commit access are and how popular the package is.

**Comment by Artturin** [comment]
we have a timer in nixpkgs https://github.com/trehn/termdown

if you still want utimer then i suggest you maintain it in your own config or nur

**Comment by danielb2** [comment]
termdown is not even remotely the same, but forget it. I've now stopped using nix since it's not what I thought it would be
