### ISSUE TITLE
Dropbox couldn't start after update from 3.12.6 -> 3.20.1

### ISSUE THREAD

**Issue by rexim** [NixOS/nixpkgs#15703]
## Issue description

Couldn't start dropbox after upgrading it. Seeing the following error:

```
$ dropbox                                                                                                                                                                                ~
Couldn't start Dropbox.
This is usually because of a permissions error. Storing your home folder on a network share can also cause an error.

Get more help at https://www.dropbox.com/c/help/permissions_error

Please contact Dropbox support with the following info for help:

/tmp/dropbox_errorDIvhJa.txt
```

The info file that the error message refers to: [dropbox_errorDIvhJa.txt](https://github.com/NixOS/nixpkgs/files/282618/dropbox_errorDIvhJa.txt)

I believe the most interesting part there is

```
ImportError: /nix/store/ds09005c7a83ms3nzhsq6c0fc6rymw9v-dropbox-3.20.1/opt/dropbox/PyQt5.QtCore.so: undefined symbol: _ZN19QItemSelectionModel8setModelEP18QAbstractItemModel
```

Probably a wrong version of PyQt5, but I don't know for sure and have a little expertise in NixOS to troubleshoot that by myself, sorry. :(

Could be caused by #15566

(Even though the error message suggest to contact Dropbox support I still would like to consult here first)
### Steps to reproduce
- Have dropbox 3.12.6 installed on your system
- Upgrade dropbox with `$ nix-env --upgrade dropbox`
- Try to start dropbox `$ dropbox`

(Well I believe it may be reproduced without actually upgrading existing dropbox, but just by installing the 3.20.1 version for the first time, but I've never actually tried that)
## Technical details
- System: 16.03.836.aff03ae (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.836.aff03ae

**Comment by joachifm** [comment]
cc @ttuegel @bendlas

**Comment by bendlas** [comment]
Yeah, sounds like an outdated PyQT5, from the error message. I'll see whether we can't provide a more recent version in stable channel. Push comes to shove, we'll have to deactivate dropbox in stable :(

Unfortunately, Dropbox doesn't think it's necessary any more, to provide changelogs along with their releases.

**Comment by bendlas** [comment]
turns out, the situation isn't quite as dramatic, qt55 is already in stable and seems to work

**Comment by ttuegel** [comment]
We really need to fix the Dropbox build to use the bundled libraries whenever possible. (That will also resolve this issue permanently.) Dropbox ships libraries that have been incompatibly patched from the open source versions (and they won't say which libraries are patched).

**Comment by rexim** [comment]
The latest nixos-stable version of dropbox seems to be working for me. I don't know guys your process, so how should I proceed on that? Should I close this issue by myself or maybe you have some sort of verification phase where it's closed by someone else?

Anyway, thank you very much for fixing this! :)
