### ISSUE TITLE
Arcmenu gnome shell extension problems

### ISSUE THREAD

**Issue by RDKRACZ** [NixOS/nixpkgs#157003]
**The provided version is too old to even be enabled with the current gnome release in Nix 21.11. The official version of Arcmenu (from https://extensions.gnome.org/extension/3628/arcmenu/) doesn't detect Gmenu for some reason.**

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: gnome-shell-extension-arcmenu

current version: 14
desired version: 20

###### Notify maintainers

maintainers: https://github.com/dkabot

###### Note for maintainers

Please tag this issue in your PR.

**Comment by rhoriguchi** [comment]
[Master](https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome/extensions/arcmenu/default.nix#L5) uses version 20.

**Comment by maxeaubrey** [comment]
Closing as 22.05 has 30 and master has 37.
