### ISSUE TITLE
Adding SonoBus to nixpkgs

### ISSUE THREAD

**Issue by krissemicolon** [NixOS/nixpkgs#157139]
**SonoBus is a real-time network audio streaming collaboration tool.**
_SonoBus is an easy to use application for streaming high-quality, low-latency peer-to-peer audio between devices over the internet or a local network._
_It is really easy to use and has a nice GUI_
_Also it is efficient and written in C++._

**Metadata**

* homepage URL: [sonobus.net](https://sonobus.net)
* source URL: [github/sonosaurus/sonobus](https://github.com/sonosaurus/sonobus)
* license: gplv3
* platforms: windows, linux, darwin

**Comment by soispha** [comment]
This was already merged in #211341.
