### ISSUE TITLE
Missing library - libQt5Xml.so.5

### ISSUE THREAD

**Issue by RDKRACZ** [NixOS/nixpkgs#157183]
This library is needed for some binaries to run and it seems it's not available on NixOS.

* URL: https://packages.ubuntu.com/hirsute/libqt5xml5

**Comment by OPNA2608** [comment]
Should be part of the qtbase packages.

![Bildschirmfoto von 2022-01-28 21-11-58](https://user-images.githubusercontent.com/23431373/151614905-1d91eb8a-26b0-4efa-936d-d672afa5dd39.png)

**Comment by RDKRACZ** [comment]
![image](https://user-images.githubusercontent.com/43277609/151617192-44bebf7c-5363-468f-b4e3-4984629ef21b.png)

**Comment by OPNA2608** [comment]
I don't think using Steam's FHS wrapper will automagically include all your imperatively-installed packages, it has a fixed list of packages. You'll have to override the steam derivation and add `qtbase` to its `extraPkgs` if you want to stick with `steam-run`ning the application, or write a proper package for it.
