### ISSUE TITLE
xsession doesn't run the window/desktop manager upon login

### ISSUE THREAD

**Issue by dtulig** [NixOS/nixpkgs#15722]
## Issue description

Using the latest unstable build, be5b596, logging in via SDDM with 'none + xmonad' fails to run xmonad. Resetting back to f010ce65ec869487d86fbfe03966f4c69a6f591b allows it to work again.

Looking through the last few commits, c99608c63808f0fe244fe9619ef6d97bf8a5af6f is the most obvious change to the xsession startup scripts. In my tests the `.xsession` script would run and load the .xprofile script, so it seems to make it reasonably far but it doesn't execute the window manager (xmonad in my case).

There are no errors in `.xsession-errors`, the systemd journal doesn't show anything unusual. I noticed that it doesn't even attempt to compile my `xmonad.hs` file so it seems to completely skip executing anything else.

Here is my xserver config:

```
  services.xserver = {
    enable = true;
    layout = "us";
    windowManager.xmonad.enable = true;
    windowManager.xmonad.enableContribAndExtras = true;
    xkbOptions = "ctrl:nocaps";
    displayManager.sddm.enable = true;
  };
```

### Steps to reproduce

1. Update to the latest unstable release (be5b596).
2. Use SDDM and Xmonad as noted above.
3. Restart the display manager (in my case I restarted my machine).
4. Login, you should see that the window manager didn't load and just an xterm shows up.

## Technical details

* System: 16.09.git.be5b596 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: Using local nixpkgs at be5b596

**Comment by domenkozar** [comment]
This is fixed now, hoping for new channel update any minute now.

**Comment by domenkozar** [comment]
Can you try upgrading the channel?

**Comment by dtulig** [comment]
Upgrading to pick up the new xsession (`259hcyj6iz9cgwm84wk49nmqsi767pzn-xsession`) fixed it.
