### ISSUE TITLE
Adding checks for linking

### ISSUE THREAD

**Issue by rardiol** [NixOS/nixpkgs#15720]
I've ran into 2 issues which I think ought to have been caught automatically :

A built lib is missing some libs from rpath, which can be caught by running ldd in all built objects and looking for not founds, or something similar. For example: https://github.com/NixOS/nixpkgs/issues/14495

A built executable has a rpath point to its own build dir. For example qtox has "/tmp/nix-build-qtox-1.3.0.drv-0/tmp.uuCo2z2lm7/lib" on rpath for @be5b596

**Comment by abbradar** [comment]
Regarding ldd -- see https://github.com/NixOS/nixpkgs/commit/5471eed63ce770491a93f5c07543ba4ba818a90e#commitcomment-16858447. tl;dr: this is considered fragile and wouldn't work for, for example, cross-compilation. I've tried another approach in https://github.com/NixOS/nixpkgs/pull/14379 and intend to continue working on it some day.

**Comment by copumpkin** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/15004

**Comment by Profpatsch** [comment]
@copumpkin is this implemented in #15004? Then I’d close this issue.

**Comment by matthewbauer** [comment]
Closing in favor of #15004.
