### ISSUE TITLE
integer-simple 0.1.1.1 fails to build under GHC 7.10.3

### ISSUE THREAD

**Issue by teozkr** [NixOS/nixpkgs#15725]
## Issue description

`integer-simple` fails to build with the default GHC (7.10.3). It builds fine with GHC 8.0.1.
### Steps to reproduce
1. `$ nix-build -A 'haskell.packages.ghc7103.integer-simple' --no-out-link '<nixpkgs>'`

This should produce output [looking like this](https://gist.github.com/teozkr/567b1baa15bd16a425f39442c28a4ee9).
### Cause

This seems to be because the line `ghc-options: -this-unit-id integer-simple -Wall` in `build.cabal` was changed to `ghc-options: -package-name integer-simple -Wall` in a new release uploaded to Hackage 5 days ago: http://hackage.haskell.org/package/integer-simple-0.1.1.1 . Curiously enough, this version is not in [the git repo](http://git.haskell.org/packages/integer-simple.git). Apparently `-this-unit-id` was added in 8.0, which breaks this package for older GHC versions.

From what I can tell, this was already distributed with GHC for older versions, and shouldn't be downloaded separately at all.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) Arch Linux
- Nix version: (run `nix-env --version`) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 16.09pre84164.3e53001

**Comment by teozkr** [comment]
After som further investigation it seems like this became an issue because it was a dependency for old versions of Text (1.2.1.x and below) by default. All the modern package sets (that get checked by Hydra) have Text 1.2.2.x, and thus aren't affected. So for me it seems like I got lucky and an upgrade to a newer LTS Haskell fixed it.

**Comment by yegortimoshenko** [comment]
Still doesn't build.
