### ISSUE TITLE
Cannot build fcitx-libpinyin in the latest unstable channel

### ISSUE THREAD

**Issue by kuwii** [NixOS/nixpkgs#157354]
### Describe the bug

After updating to the latest NixOS unstable channel, when running `sudo nixos-rebuild boot`, the process will fail when building fcitx-libpinyin.

### Steps To Reproduce

Can repro this in a fresh installed NixOS using [nixos-gnome-22.05pre349657.5bb20f9dc70-x86_64-linux.iso](https://releases.nixos.org/nixos/unstable/nixos-22.05pre349657.5bb20f9dc70/nixos-gnome-22.05pre349657.5bb20f9dc70-x86_64-linux.iso)

1. Update `/etc/nixos/configuration.nix`, adding the following lines:

   ```
   i18n.inputMethod.enabled = "fcitx";
   i18n.inputMethod.fcitx.engines = with pkgs.fcitx-engines; [ libpinyin ];
   ```

2. Update channel: `sudo nix-channel --update`
3. Rebuild: `sudo nixos-rebuild boot`
4. The process will fail when building .....-fcitx-libpinyin-0.5.3.drv with exit code 2.

### Expected behavior
The rebuild process should succeed without failure.

### Screenshots

![Screenshot_20220130_121937](https://user-images.githubusercontent.com/10705175/151686477-ec30d0aa-95ef-4916-ba34-c106f50d054f.png)

### Notify maintainers

@ericsagnes 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.94, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-22.05pre349657.5bb20f9dc70"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by FliegendeWurst** [comment]
Updating to 0.5.4 seems to fix it: #157379
