### ISSUE TITLE
cloud-utils: depends on sed being available as gnused

### ISSUE THREAD

**Issue by martijnvermaat** [NixOS/nixpkgs#15736]
## Issue description

[cloud-utils](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/cloud-utils/default.nix) depends on the `gnused` binary being in `$PATH`, but stdenv has sed as just `sed`.
### Steps to reproduce

```
$ nix-shell -p cloud-utils
$ growpart /dev/sda 1
# I assume this fails, reported by jeaye on IRC
```

Or just:

```
$ nix-shell -p cloud-utils --run 'gnused --version'
/run/user/1000/nix-shell.x2PKAC/rc: line 1: gnused: command not found
```
## Technical details
- System: (NixOS: 16.03)
- Nix version: 1.11.2
- Nixpkgs version: unstable and master
## Cause and proposed solution

In `buildPhase`, use of `sed` is replaced by `gnused` [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/cloud-utils/default.nix#L14). I traced that code back to [this commit](https://github.com/NixOS/nixpkgs/commit/044a24e58bcf4cf48df02df936c542839fb08d90) which also includes [this line](https://github.com/NixOS/nixpkgs/commit/044a24e58bcf4cf48df02df936c542839fb08d90#diff-657f0a66367fa9a3b575d28f508a3e62R26) making sed available as `gnused`, but these are now separated in the codebase.

In [amazon-grow-partition](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/amazon-grow-partition.nix), cloud-utils is used in the original context (in initrd) where `gnused` is still explicitely made available, but of course this doesn't hold when using cloud-utils elsewhere.

It was mentioned on IRC by clever that using absolute paths instead of relying on PATH here would perhaps mess with the closure size of the initrd.

**Comment by martijnvermaat** [comment]
cc @domenkozar as you [separated](https://github.com/NixOS/nixpkgs/commit/96be420e44338776c083224ba892795c57d730a6) cloud-utils from amazon-grow-partition.

**Comment by chris-martin** [comment]
Please reopen, this is still a problem in NixOS 17.09.

```
# growpart /dev/xvda 1
/nix/store/hw5ydc3i92q686sb3yr275qihdhx2m5j-cloud-utils-0.29/bin/.growpart-wrapped: line 257: gnused: command not found
FAILED: gnused failed on dump output
```

**Comment by chris-martin** [comment]
There's a workaround here: https://github.com/NixOS/nixpkgs/issues/22211#issuecomment-341228226

**Comment by orivej** [comment]
`growpart` from the `cloud-utils` package uses `sed` not `gnused`, which is added to the PATH in the wrapper.

**Comment by chris-martin** [comment]
@orivej I could be mistaken, but I don't think that's the case for the version of `cloud-utils` currently in NixOS release 17.09.

**Comment by domenkozar** [comment]
afaik this wasn't backported

**Comment by domenkozar** [comment]
there was a PR in master to fix it, but never backported.
