### ISSUE TITLE
flexget (via transmission-rpc) is broken in unstable

### ISSUE THREAD

**Issue by cmm** [NixOS/nixpkgs#157381]
### Describe the bug
`flexget` (via the `transmission-rpc` python library, which fails to build) does not build in unstable.
The proximate cause, I think, is the recent upgrade of `typing-extensions`.

My understanding is that `transmission-rpc` is built from the latest pip release, which is still 3.3.0 and which declares itself incompatible with `typing-extensions`>=4.0 (not sure if for a good reason).  I don't know a thing about Python packaging in nixpkgs so have no clue what is to be done here.

### Steps To Reproduce
1. try building `transmission-rpc` or `flexget` in unstable

### Notify maintainers
@eyjhb (?)

**Comment by eyJhb** [comment]
https://github.com/NixOS/nixpkgs/pull/157127 :)

**Comment by cmm** [comment]
oops, should make it a habit to check pulls first :)
thank you!

**Comment by eyJhb** [comment]
No worries, it can be hard finding the hard PRs, in all the others especially with GitHubs search function... :p

**Comment by eyJhb** [comment]
You can follow the progress of the channels here btw. https://nixpk.gs/pr-tracker.html?pr=157127
