### ISSUE TITLE
Incorrect rendering of `---` in Nixpkgs manual

### ISSUE THREAD

**Issue by qrilka** [NixOS/nixpkgs#15735]
## Issue description

It appears that markdown rendering used on http://nixos.org/ and for Github markdown doesn't deal well with `---` which (I suppose) should show up as —
Readthedocs shows it correctly.
This character sequence seems to be used only in Haskell section of nixpkgs docs

### Steps to reproduce

Open http://nixos.org/nixpkgs/manual/#how-to-create-ad-hoc-environments-for-nix-shell or https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.md#how-to-create-ad-hoc-environments-for-nix-shell in the code you'll see `---` while on http://nixpkgs.readthedocs.io/en/latest/reference-guide/haskell.html#how-to-create-ad-hoc-environments-for-nix-shell there are `—`'s in the corresponding places

## Technical details

Not relevant for this issue

**Comment by vcunat** [comment]
Thanks. Hmm, nitpick: IIRC em-dashes with spaces around them aren't generally accepted; the common styles are `foo---bar` and `foo -- bar` (which I personally prefer).

**Comment by qrilka** [comment]
is there any nix documentation style guide where this should be added? I don't have any preference here but  it's better to be consistent at least :) Both in input and output

**Comment by vcunat** [comment]
No, we don't have that. There's not even full consensus about what formats can be used &ndash; originally it was just DocBook but a few parts are in a Markdown flavor now.
