### ISSUE TITLE
systemd-timedated not working because /etc/localtime does not point to /usr/share/zoneinfo

### ISSUE THREAD

**Issue by exi** [NixOS/nixpkgs#15746]
## Issue description

systemd-timedated does not start up because it expects the /etc/localtime symlink to point to /usr/share/zoneinfo/*
### Steps to reproduce

try to start systemd-timedated
## Technical details
- System: NixOS unstable
- Nix version: 1.11.2
- Nixpkgs version: 16.09pre84171.6d16979

**Comment by orivej** [comment]
This must have been fixed by #19449.
