### ISSUE TITLE
LoadCredential doesn't result in a credential file being created

### ISSUE THREAD

**Issue by Pacman99** [NixOS/nixpkgs#157449]
### Describe the bug
When a systemd service uses `LoadCredential` it doesn't seem to get access to that credential, and it seems like the file in `/run/credentials` doesn't even exist.

### Steps To Reproduce
1. I'm not sure what option is causing it, but I'm pretty sure it's `boot.isContainer = true`. So enable that option
2. Enable a service that makes use of `LoadCredential` like keycloak or nix-serve
3. The service will fail with an error that it doesn't have permissions for that file. Which I think happens because they don't have access to /run/credentials, but when inspecting that file, the file/folder where the credential should be doesn't exist.

### Expected behavior
Systemd should create a folder in `/run/credentials` like `nix-serve.service` with the credential file, so the service can access it.

### Additional context
I use vpsfree, so I've enabled the recommended options for a vpsfree server, https://gitlab.com/coffeetables/myrdd/-/blob/master/profiles/vpsadminos.nix. The rest of my server's config is in that repository.

I've also filed an issue in systemd/systemd#21789, but I think it might be a nixos specific issue. It was tagged in the systemd repo as an nspawn issue.

Here is log from nix-serve that i posted there:
[error(1).log](https://github.com/NixOS/nixpkgs/files/7966911/error.1.log)
I think this is the offending line: `Failed to mount /run/credentials/nix-serve.service (type n/a) on /run/systemd/unit-root/run/credentials/nix-serve.service (MS_BIND ""): No such file or directory`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(root): `"nixos-21.05pre287333.63586475587"`
 - nixpkgs: `/nix/store/q8fqyyh6l0apzm29x7syl04pdp886b2f-source`
```

**Comment by NULLx76** [comment]
I encounted the same issue when trying to run plausible, is there any workaround or fix?

**Comment by aither64** [comment]
Speaking for vpsFree.cz as mentioned by @Pacman99 , we have resolved this in February by mounting `/run` with the `shared` flag, which wasn't the default in our environment, but it seems to be the default elsewhere. A simple workaround to get LoadCredential working in our case was to run `mount --make-rshared /run`.

**Comment by benaryorg** [comment]
For anyone stumbling across this, as this happened to me too when running NixOS on LXD (on a NixOS host), here is a config snippet that may help:

```nix
boot.specialFileSystems."/run".options = [ "rshared" ];
```

**Comment by Pacman99** [comment]
Thanks for the help everyone, this issue seems to be resolved with the above fixes/suggestions
