### ISSUE TITLE
Mixxx not detecting JACK as an audio backend when PipeWire with JACK emulation is running

### ISSUE THREAD

**Issue by starcraft66** [NixOS/nixpkgs#157529]
### Describe the bug
When running Pipewire with the emulated JACK server, Mixxx does not detect JACK as a suitable audio backend. Other JACK-supporting applications like Carla do so just fine. I'm unsure what could be the cause. Mixxx uses PortAudio to handle all of the communication with jack and it looks like the PortAudio in nixpkgs is up to date but something might be wrong with it? I'm also pinging PortAudio maintainers for visibilit in case, feel free to ignore if this isn't a PortAudio problem.

### Steps To Reproduce
1. Enable `services.pipewire.enable` and `services.pipewire.jack.enable`
2. Launch Mixxx and open the preferences
3. Try to select JACK as an audio backend in the audio preferences

### Expected behavior
I expect JACK to be available in the audio preferences but only OSS and ALSA show up.

### Notify maintainers
@goibhniu @bfortz @lovek323 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.3, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `""`
 - channels(tristan): `""`
 - nixpkgs: `/nix/store/rdglycjss277jiy7zinn982jg4q525p9-md3lc3011brc36wdc9fydj2krj9idi8m-source`
```

**Comment by jansol** [comment]
Does it work if you launch it from a terminal as `pw-jack mixxx`? It might be linking directly to the real libjack such that pipewire can't replace it via LD_LIBRARY_PATH, or the wrapper might be overriding the library path.

**Comment by starcraft66** [comment]
Looks like our PortAudio is compiled without JACK support. I'm testing a tentative PR to enable it on Linux, just waiting for the large rebuild of my system to finish.

I think that will fix this.

**Comment by istepaniuk** [comment]
This works for me.

Not sure about the PRs, but mixxx 2.3.3 on Debian testing has Jack support and works out of the box with PipeWire (running it with `pw-jack mixxx`)

**Comment by prusnak** [comment]
Fixed via https://github.com/NixOS/nixpkgs/pull/215284
