### ISSUE TITLE
nixos-generate-config: Properly handle btrfs subvolumes

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#1575]
Currently, `nixos-generate-config` assumes that if two mount points come from the same device one is a bind mount. This assumption fails for btrfs subvolumes (which differentiate the devices by a mount option)

**Comment by zarelit** [comment]
Isnt't this the same as #1696 ?

**Comment by kevincox** [comment]
I'm not sure it's the same problem but the solution may well be the same.

**Comment by kevincox** [comment]
@shlevy What problems does the assumption cause? And in what way is this assumption made?

**Comment by shlevy** [comment]
This was fixed way back in 87b6232f3a4c9903a432fffd8bc627f2c445a10d

**Comment by kevincox** [comment]
Thanks!
