### ISSUE TITLE
nixos-rebuild always downloads nix expressions when doing --upgrade

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#15755]
## Issue description

When --upgrade'ing, nixos-rebuild always downloads nix expressions even if they are the same version (not a real upgrade).

### Steps to reproduce

nixos-rebuild [something] --upgrade

## Technical details

It happened about a week ago or more.
As i can see, it's certainly not an important bug and i just waited...

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
\# nixos-version
16.03.858.b8d7324 (Emu)

* Nix version: (run `nix-env --version`)
\# nix-env --version
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
\# nix-instantiate --eval '\<nixpkgs\>' -A lib.nixpkgsVersion
"16.03.858.b8d7324"

**Comment by joachifm** [comment]
A package may be updated even if its version does not change; for example if any of its inputs change. This is expected (and desired) behavior.

**Comment by comonoid** [comment]
I had never seen this in 15 or earlier...
Ok, thanks. So, we should close this issue?

**Comment by joachifm** [comment]
If there is a problem, please clarify, otherwise the issue may be closed.

**Comment by comonoid** [comment]
It's not a real problem for me.
I just thought that it's not a valid thing to download and install something if there are no changes.
And may be it's worth to report it...
As you tell me, the same version do not guarantee the same content.
I do not fully understand it _now_, but of course i believe you.

**Comment by joachifm** [comment]
The content depends on the inputs only, the version itself is just a human friendly indicator, really.

**Comment by comonoid** [comment]
Now i see, thanks!
And sorry for the false alarm...

**Comment by joachifm** [comment]
No worries; Nix can be a little odd if you're only used to traditional package managers.

**Comment by comonoid** [comment]
It's still ;-) not a problem, but i'm a little bit curious...
Would you please tell me?
I tried this —
for i in \{1..10\}; do nixos-rebuild dry-build --upgrade; done
Every time it downloaded nixexprs's (with the same nixos-16.03.885.15e7e6e version).
Is it normal?

**Comment by joachifm** [comment]
Yes, as far as I know.

**Comment by comonoid** [comment]
Ok, thanks!

**Comment by vcunat** [comment]
Yes, normal even if a bit wasteful.
