### ISSUE TITLE
`/etc/wpa_supplicant.conf` should automatically be created

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#157537]
### Describe the bug
When `networking.wireless.enable == true && allowAuxiliaryImperativeNetworks == true`, `wpa_supplicant` crashes due to a missing `/etc/wpa_supplicant.conf`. An unprivileged user is no able to fix this failure. IMHO it would be better if the file is just touched before attempting to launch `wpa_supplicant`, so that it is at least there. 

I'd suggest 

```bash
umask 077
touch /etc/wpa_supplicant.conf
chmod 700 /etc/wpa_supplicant.conf
```

as `pre` action to the `wpa_supplicant` systemd service

### Expected behavior
The service starts without issues

### Notify maintainers
@globin @rnhmjoj

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.05.3957.66d6ec6ed2d"`
 - channels(zaes_wa): `"nixpkgs-21.11.334247.573095944e7"`
 - nixpkgs: `/home/my_user/.nix-defexpr/channels/nixpkgs
```

**Comment by rnhmjoj** [comment]
Pinging @ma27 for `allowAuxiliaryImperativeNetworks`

**Comment by romildo** [comment]
Still important.
