### ISSUE TITLE
spaceFM's su, sudo and sudo

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#15758]
## Issue description
Nix's usage of spaceFM's _--with-preferable-sudo_ is both incorrect and outdated:

**Incorrect:** The flag allows customizing the graphics su (gksu), not the terminal su. But the .nix has _--with-preferable-sudo=${pkgs.sudo}/bin/sudo_.

**Outdated:** Since 1.0.4, spaceFM has two configurable entries in _/etc/spacefm/spacefm.conf_ for setting the su options: _terminal_su_ and _graphical_su_.

See relevant [release news section](http://ignorantguru.github.io/spacefm/news.html#1.0.4) for further details.

### Steps to reproduce

Right-click a file and Left-click _Open -> Edit As Root_ . Note the error.

### Suggestion

Drop the usage of _--with-preferable-sudo_ altogether. Allow per-user override of _/etc/spacefm/spacefm.conf_, or a system wide, package specific option to define _spacefm.conf_ in _configuration.nix_.

## Note

Note that since the spacefm package already provides it's own default _spacefm.conf_, the following doesn't work:
```
  environment.etc."spacefm/spacefm.conf" = {
    mode = "0644";
    text = ''
      # spacefm.conf
      # This file affects all users of SpaceFM on this system.

      # Documentation: /usr/share/doc/spacefm/spacefm-manual-en.html#programfiles-etc
      # http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#programfiles-etc

      # tmp_dir must be a root-protected user-writable dir like /tmp
      # ALL users must be able to write to this dir.
      # tmp_dir must NOT contain spaces or special chars - keep it simple
      tmp_dir=/tmp

      # Specify an absolute path to an additional terminal su or sudo program:
      terminal_su=${pkgs.sudo}/bin/sudo

      # Specify an absolute path to an additional graphical su program:
      graphical_su=${pkgs.gksu}/bin/gksu
    '';
  };
```
Also, recompiling the broken _--with-preferable-sudo_ flag with the following in _configuration.nix_:
```
  nixpkgs.config = {
    allowUnfree = true;
    packageOverrides = pkgs: {
      spaceFM = pkgs.stdenv.lib.overrideDerivation pkgs.spaceFM (oldAttrs : {
        configureFlags = [
          "--with-bash-path=${pkgs.bash}/bin/bash"
          "--with-preferable-sudo=${pkgs.gksu}/bin/gksu"
        ];
      });
    };
  };
```
Will also fail since without a correct terminal su, spacefm will refuse to use the graphical su. As such, it's necessary to add a postInstall to the package that either deletes _$out/etc_ altogether, or inserts the correct values into spacefm.conf.

## Technical details

* System: _NixOS 16.03.847.8688c17 (Emu)_
* Nix version: _nix-env (Nix) 1.11.2_
* Nixpkgs version: _16.03.847.8688c17_

**Comment by joachifm** [comment]
cc maintainers @jagajaga @obadz

**Comment by jagajaga** [comment]
https://github.com/IgnorantGuru/spacefm/blob/master/README#L197 this option is still exist. There aro no words that it is obsolete.
What about `spacefm.conf`: there is an option `--sysconfdir`. We just need to set it to `$out/etc` and `sed` the conf file afterwards to set sudo program.

Oh, as I've checked https://github.com/IgnorantGuru/spacefm/blob/master/etc/spacefm.conf, the sudo option is commented there. So how it could override the sudo flag?

**Comment by RamKromberg** [comment]
The option still exists and you can still change the compile time flag by correcting it to _--with-preferable-sudo=${pkgs.gksu}/bin/gksu_, but you'll need gksu as a runtime dependency AND it still won't work on it's own:
SpaceFM will complain with the error "Please configure a valid Terminal SU command in View[Preferences] Advanced" despite not needing it when trying to _Edit As Root_.

That is, **unless both terminal_su and graphical_su are correctly configured in _spacefm.conf_, _Edit As Root_ will fail.**

Regarding _--sysconfdir_, as long as the end result is a correctly configured _spacefm.conf_ that SpaceFM can find, it should work. I'm not in-front of my box right now, but I'll try the following in _configuration.nix_ later to test it out:
```
nixpkgs.config = {
    allowUnfree = true;
    packageOverrides = pkgs: {
      spaceFM = pkgs.stdenv.lib.overrideDerivation pkgs.spaceFM (oldAttrs : {
        configureFlags = [
          "--with-bash-path=${pkgs.bash}/bin/bash"
          "--with-preferable-sudo=${pkgs.gksu}/bin/gksu"
          "--sysconfdir =$out/etc"
        ];
        postInstall = ''
          echo 'terminal_su=${pkgs.sudo}/bin/sudo > $out/etc/spacefm/spacefm.conf'
          echo 'graphical_su=${pkgs.sudo}/bin/gksu >> $out/etc/spacefm/spacefm.conf'
        '';
      });
    };
  };
```

Though like I said, I'd personally opt to avoid declaring _--with-preferable-sudo_ at all since it's superfluous to _spacefm.conf_ and may cause troubles down the line regarding dependencies if the user doesn't have gksu in run-time or uses an alternative...

**Comment by obadz** [comment]
Overall agree with OP.

`gksu` would become a runtime dependency of spacefm even with `echo 'graphical_su=${pkgs.gksu}/bin/gksu >> $out/etc/spacefm/spacefm.conf'` though, but that would still be fine.

`--with-preferable-sudo=${pkgs.sudo}/bin/sudo` is utterly useless either way since sudo is only `setuid root` in `/var/setuid-wrappers/sudo`

Would also be fine to set `--sysconfdir=/etc` and configure the file from a nixos module.

**Comment by RamKromberg** [comment]
Well, technically now we know it's possible to avoid all the compile and runtime dependencies on sudo or gksu in the package and leaving it out to the user. This is could be done by not setting the _--with-preferable-sudo_ AND either:
**1.** Delete the config with something like _postInstall = "rm -rf $out/etc";_ which will allow the users to set their own with _environment.etc."spacefm/spacefm.conf"_.
**2.** Use _--sysconfdir =$out/etc_ in the package, and allow the users to declare their own _terminal-su_ and _graphical-su_ without invoking sudo or gksu default dependencies explicitly in the .nix package by creating a package string variable that represents _spacefm.conf_ content similarly to how service packages do things.

IMHO, although _--sysconfdir =$out/etc_ does open the way to a proper - albeit, troublesome - resolution, the former option (to just delete the provided _spacefm.conf_ file) is the easiest and most maintainable option.

**Comment by RamKromberg** [comment]
To summarize and clarify, for NisOX 16.03:

    { pkgs, fetchFromGitHub, stdenv, gtk3, udev, desktop_file_utils, shared_mime_info
    , intltool, pkgconfig, wrapGAppsHook, ffmpegthumbnailer, jmtpfs, ifuse, lsof, udisks
    , hicolor_icon_theme, adwaita-icon-theme }:

    stdenv.mkDerivation rec {
      name = "spacefm-${version}";
      version = "1.0.4";

      src = fetchFromGitHub {
        owner = "IgnorantGuru";
        repo = "spacefm";
        rev = "${version}";
        sha256 = "1jywsb5yjrq4w9m94m4mbww36npd1jk6s0b59liz6965hv3xp2sy";
      };

      configureFlags = [
        "--with-bash-path=${stdenv.shell}"
        #"--with-preferable-sudo=${pkgs.gksu}/bin/gksu"
      ];

      preConfigure = ''
        configureFlags="$configureFlags --sysconfdir=$out/etc"
      '';

      postInstall = ''
        rm -f $out/etc/spacefm/spacefm.conf
        ln -s /etc/spacefm/spacefm.conf $out/etc/spacefm/spacefm.conf 
      '';

      buildInputs = [ gtk3 udev desktop_file_utils shared_mime_info intltool pkgconfig wrapGAppsHook ffmpegthumbnailer jmtpfs ifuse lsof udisks ];

      meta = with stdenv.lib;  {
        description = "A multi-panel tabbed file manager";
        longDescription = ''
          Multi-panel tabbed file and desktop manager for Linux
          with built-in VFS, udev- or HAL-based device manager,
          customizable menu system, and bash integration
        '';
        homepage = http://ignorantguru.github.io/spacefm/;
        platforms = platforms.linux;
        license = licenses.gpl3;
        maintainers = with maintainers; [ jagajaga obadz ];
      };
    }

And for the 1.0.5 version at master:

    { pkgs, fetchFromGitHub, stdenv, gtk3, udev, desktop_file_utils, shared_mime_info
    , intltool, pkgconfig, wrapGAppsHook, ffmpegthumbnailer, jmtpfs, ifuse, lsof, udisks
    , hicolor_icon_theme, adwaita-icon-theme }:

    stdenv.mkDerivation rec {
      name = "spacefm-${version}";
      version = "1.0.5";

      src = fetchFromGitHub {
        owner = "IgnorantGuru";
        repo = "spacefm";
        rev = "${version}";
        sha256 = "06askkrwls09d1x382zjrmnvcm0ghfgz4cms2qbhdkazfyy0ff65";
      };

      configureFlags = [
        "--with-bash-path=${stdenv.shell}"
        #"--with-preferable-sudo=${pkgs.gksu}/bin/gksu"
      ];

      preConfigure = ''
        configureFlags="$configureFlags --sysconfdir=$out/etc"
      '';

      postInstall = ''
        rm -f $out/etc/spacefm/spacefm.conf
        ln -s /etc/spacefm/spacefm.conf $out/etc/spacefm/spacefm.conf 
      '';

      buildInputs = [ gtk3 udev desktop_file_utils shared_mime_info intltool pkgconfig wrapGAppsHook ffmpegthumbnailer jmtpfs ifuse lsof udisks ];

      meta = with stdenv.lib;  {
        description = "A multi-panel tabbed file manager";
        longDescription = ''
          Multi-panel tabbed file and desktop manager for Linux
          with built-in VFS, udev- or HAL-based device manager,
          customizable menu system, and bash integration
        '';
        homepage = http://ignorantguru.github.io/spacefm/;
        platforms = platforms.linux;
        license = licenses.gpl3;
        maintainers = with maintainers; [ jagajaga obadz ];
      };
    }

The user can then add the following in his _configuration.nix_:

    environment.etc."spacefm/spacefm.conf" = {
      mode = "0644";
      text = ''
        # spacefm.conf
        # This file affects all users of SpaceFM on this system.
    
        # Documentation: /usr/share/doc/spacefm/spacefm-manual-en.html#programfiles-etc
        # http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#programfiles-etc
    
        # tmp_dir must be a root-protected user-writable dir like /tmp
        # ALL users must be able to write to this dir.
        # tmp_dir must NOT contain spaces or special chars - keep it simple
        tmp_dir=/tmp
    
        # Specify an absolute path to an additional terminal su or sudo program:
        terminal_su=${pkgs.sudo}/bin/sudo
    
        # Specify an absolute path to an additional graphical su program:
        graphical_su=${pkgs.gksu}/bin/gksu
      '';
    };

But it's not mandatory. So, there's no explicit runtime dependencies on sudo or gksu.
While we're at it, https://github.com/NixOS/nixpkgs/issues/183 was also addressed.
