### ISSUE TITLE
x2goclient build fails at install phase

### ISSUE THREAD

**Issue by sephalon** [NixOS/nixpkgs#15761]
## Issue description

The x2goclient build fails at the install phase, but I cannot spot the reason for it. This is the relevant build log section:

```
glibPreInstallPhase
installing
install flags: install_client install_man SHELL=/nix/store/d20f169ryps7ds2qak0r5n1f4hhxr80h-bash-4.3-p42/bin/bash    gsettingsschemadir=/nix/store/vvjzsxf5i8d05d0h62cvqzpvy34r310g-x2goclient-4.0.5.1/share/gsettings-schemas/x2goclient-4.0.5.1/glib-2.0/schemas/
make: *** No rule to make target 'install_client'.  Stop.
```

The makefile has a target `install_client` though. Replacing this with a different target or removing the `installTarget` line in the derivation file altogether also leads to a halt at the install phase.

### Steps to reproduce

Just try to build the package x2goclient.

## Technical details

* System: 16.09.git.aa97587M (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09.git.aa97587M"

**Comment by sephalon** [comment]
Fixed by 747517da480c986e5f7146ede0ccfbc2b15b6924.

**Comment by bjornfor** [comment]
Actually, 41eafd25a0f7f7aa72293cec8bd51e736fe00d06 was the commit that unbroke x2goclient.

**Comment by sephalon** [comment]
Yep. Wrong clipboard entry…
