### ISSUE TITLE
Can't access shared folder in virtualbox appliance

### ISSUE THREAD

**Issue by ChrisJefferson** [NixOS/nixpkgs#15760]
## Issue description

In the virtualbox appliance on the nixos main page, I can't access shared folders, as they live in the `/media` directory, which is not accessible by the 'demo' user (I can change to root, but that a bit painful)
### Steps to reproduce

Download virtualbox appliance, install into virtualbox
Add a shared folder
Try to go into the `/media` directory
## Technical details
- System: 16.03.858.b8d7324 (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.858.b8d7324

**Comment by jpierre03** [comment]
(triage) @ChrisJefferson is this issue still relevant ?

**Comment by ChrisJefferson** [comment]
Sorry, no idea. I am unable to recheck.

**Comment by jpierre03** [comment]
Ok. Could @ChrisJefferson close this issue ?
cc  @aszlig

**Comment by rongcuid** [comment]
I think this is still a problem. I installed NixOS manually, and tried to mount it using this:

```
fileSystems."/vsfTemp" = {
  fsType = "vboxsf";
  device = "Temp";
  options = ["rw"];
}
```

And it turns out that:


- If I turn on automount in VBox, then
  - `/media/sf_Temp` is mounted but accessible only by root
  - `/vsfTemp` is empty and unmounted
- If I turn off automount
  - The VM does not boot at all, systemd entering emergency mode

**Comment by rongcuid** [comment]
OK, seems ridiculous, but if I move the mount points to `/mnt`, it actually works. So the wiki is wrong, but I still can't access `/media`

**Comment by cessationoftime** [comment]
FYI, This is still an issue for NixOs 17.03

**Comment by Pauan** [comment]
This is still an issue with `17.09.2905.c1d9aff56e0`

**Comment by bertdemiranda** [comment]
This is also a problem on version 18.03 (exported from nixos-18.03.133236.8edf566ee40-x86_64-linux.ova).
I noticed that the access bits of the /media folder do not give r and x access for others (on e.g. /mnt and /nix they do).
On another guest system I have (a Debian Stretch system) this access is enabled.
Doing a sudo chmod o+rx /media solved this problem.

**Comment by bertdemiranda** [comment]
No a problem in 19.09.
The issue can be closed.

**Comment by dbeckwith** [comment]
I'm experiencing this with `21.05.3021.8b0b81dab17`. In my config I have:

```
  fileSystems."/host" = {
    fsType = "vboxsf";
    device = "host";
    options = [ "rw" ];
  };
```

This works fine and mounts the shared folder when I do `nixos-rebuild switch`, but after reboot it isn't mounted. It looks like the VBox integrations are successfully auto-mounting it under `/media/sf_host`. And I have no problem mounting it manually. My `/etc/fstab` has the expected line:

```
host /host vboxsf rw 0 0
```

In the `journalctl` logs I see messages about `vbsvcAutoMountWorker` mounting `host` to `/media/sf_host`, then just after that `host.mount: Succeeded` and `The unit host.mount has successfully entered the 'dead' state.`. Looking back in the logs a bit, the message for `Mounted /host` and `A start job for unit host.mount has finished successfully.` shows about 2 seconds before. So it seems like it is getting mounted in the boot process, but maybe something is unmounting it? Anyone have any ideas?
