### ISSUE TITLE
Disk Quotas

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#157603]
**Project description**

We would like to define disk quotas:
https://www.linux.com/news/implementing-quotas-restrict-disk-space-usage/

I can implement it, but I just want to get some feedback on the idea before I make a PR, to make sure it's a good idea.

**Comment by NorfairKing** [comment]
Here's my idea:

We can add two more options to the `fileSystems.<name>` option.
One for user quotas and one for group quotas.

```
fileSystem.<name>.usrquota
fileSystem.<name>.grpquota
```

These would add the respective option to the fstab file, as well as make sure that `quotaon` is run.
The details for the quota configuration could be specified inside these options as well.

**Comment by NorfairKing** [comment]
We have implemented such a module here, in case anyone is interested:
https://github.com/NorfairKing/nix-quota-module

**Comment by NorfairKing** [comment]
How do I find out if a PR with such a module would be accepted?

**Comment by NorfairKing** [comment]
I guess @veprbl could answer this question?

**Comment by veprbl** [comment]
> How do I find out if a PR with such a module would be accepted?

The only way to know for sure is to submit it and see how it goes.

**Comment by NorfairKing** [comment]
@patka-123 There's definitely still work here but I won't be the one doing it so I'll close this.
