### ISSUE TITLE
Cannot install NixOS on btrfs encrypted root

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixpkgs#15786]
## Issue description

Installer is doing something wrong when installing on an encrypted btrfs root. At install time everything's okay. At boot time the following things happen:
- User is asked for the passphrase (which is correct)
- If the passphrase is correct it then fails complaining about not being able to mount root on /mnt-root
- If "continue" is chosen at this point, kernel panics and no emergency shell is spawn

### Steps to reproduce

1. Boot the nixos-emu graphical installer
2. Setup disk partitions like this: a small sda1 for boot, the rest goes to sda2 for use as luks container
3. cryptsetup luksFormat /dev/sda2
4. cryptsetup open /dev/sda2 cryptoroot
5. format cryptoroot with mkfs.btrfs
6. mount /dev/mapper/cryptoroot in /mnt
7. mount /dev/sda1 in /mnt/boot (after creating the mountpoint)
8. proceed with installation (config below)
9. reboot

Relevant parts of `configuration.nix`

~~~
 # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  # Define on which hard drive you want to install Grub.
  boot.loader.grub.device = "/dev/sda";

  # LUKS configuration
  boot.initrd.luks.devices = [ { name = "luksroot"; device = "/dev/sda2"; } ];
  
  fileSystems."/" =
    { device = "/dev/mapper/luksroot";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/537d95d8-0f65-41ac-9d36-79d2dd3c312f";
      fsType = "ext2";
    };
~~~

the hardware-configuration file of course has no parts about the filtesystems.

following the very same procedure by changing `mkfs.btrfs` to `mkfs.ext4` makes everything work so I assume it's just a btrfs related problem

## Technical details
NixOS version: 16.03.714.69420c5 (Emu)
16.03.714.69420c5 (Emu)

**Comment by fpletz** [comment]
Your steps to setup a encrypted btrfs seems correct to me. Did you maybe miss to the the following option?
```
  boot.initrd.supportedFilesystems = [ "btrfs" ];
```

By the way, you can also drop the extra boot partition and use a small (~4MB) BIOS boot partition (only GPT) if you enable cryptodisk support in with with `boot.loader.grub.enableCryptodisk`. Grub will place modules to access the root filesystem (like luks & btrfs) in the BIOS boot partition. At boot, grub will ask you to unlock your luks partition to load `grub.cfg`, the kernel and the initrd. When the kernel has finished initializing and runs the initrd, you will be prompted for you passphrase again because you have to unlock the luks partition for the kernel.

This way nobody can mess with your kernel or initrd but only with the bootloader which tends to be more complex at the expense of having to enable the luks passphrase twice at boot. :smile:

**Comment by joachifm** [comment]
You *could* embed a key in the initial ramdisk and use that for the second LUKS unlock.

**Comment by fpletz** [comment]
That's a pretty interesting idea. It's a bit disappointing though that then the key would be available world readable in the nix store. So owning just one service on the system is enough to leak the key.

**Comment by joachifm** [comment]
@fpletz that's true ... but the key only serves to prevent someone with physical access from booting the device; an attack involving both gaining physical access and owning a service to leak the key would be quite elaborate. I'm mainly concerned about protecting data in case of theft, though, if you're being targeted by a motivated attacker/government agency, storing the LUKS key for the rootfs in the Store is probably a bad idea.

**Comment by joachifm** [comment]
Hrm, well, some LUKS operations require an existing key, so I guess you could fall prey to someone messing with your LUKS container by getting the key from the Store ...

**Comment by zarelit** [comment]
@fpletz, @joachifm: thanks for the advices.
Actually that option was present, I just missed to write it in the issue. So it's not the case.

**Comment by joachifm** [comment]
@zarelit have you had the opportunity to test whether this problem persists on unstable? If it does, I think it's a fairly important issue that should be resolved before 16.09

**Comment by globin** [comment]
I've been using this for quite some time (~1.5yrs) without issues, possibly only happens when newly installing?

**Comment by zarelit** [comment]
@joachifm Sorry I hadn't enough time to retry so I installed nixos without btrfs.

**Comment by zarelit** [comment]
I am still a newbie to the whole nixos system but I am wondering if it's possible to write an installer test to cover this case

**Comment by joachifm** [comment]
@zarelit I think it should be possible to write a test; see for example the current rootfs-on-luks test at https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/installer.nix#L346.

Anyway, I suggest closing this issue until it can be confirmed.

**Comment by zarelit** [comment]
I'm going to close it until it can be re-confirmed by someone else or with a test
