### ISSUE TITLE
unifi v7.0.20

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#157877]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: unifi, unifi7

current version: 6.5.55
desired version: 7.0.20

###### Notify maintainers

maintainers:
@erictapen @globin @patryk27 @pennae 

###### Note for maintainers

https://community.ui.com/releases/UniFi-Network-Application-7-0-20/3e4a4099-c063-42f6-8e21-5fb2c99fcea9

**Comment by Patryk27** [comment]
Thanks for reporting, I'll prepare the patch in a moment 🙂
