### ISSUE TITLE
update rustcMaster

### ISSUE THREAD

**Issue by dvc94ch** [NixOS/nixpkgs#15783]
I'm trying to build a current version of rustcMaster. I'm running into an error. Has anyone had some success with updating rustcMaster?

https://github.com/rust-lang/rust/issues/33930

**Comment by retrry** [comment]
Probably this is the culprit: https://github.com/NixOS/nixpkgs/issues/15199

**Comment by dvc94ch** [comment]
mmh, I am using the beta compiler version that is described in stage0.txt

http://static.rust-lang.org/dist/2016-04-13/rust-beta-x86_64-linux.tar.gz

**Comment by dvc94ch** [comment]
I just changed the urls a little for testing, the solution described in #15199 does sound cleaner

**Comment by dvc94ch** [comment]
Closing as duplicate
