### ISSUE TITLE
Current vpnc source is no longer maintained; development has moved elsewhere

### ISSUE THREAD

**Issue by dccsillag** [NixOS/nixpkgs#157893]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vpnc

current version: 0.5.3
desired version: also 0.5.3, but forked

###### Notify maintainers

maintainers: @alyssais (last person to commit on https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/vpnc/default.nix, excluding merges)

###### Note for maintainers

Please tag this issue in your PR.

I first experienced issues when trying to use the already packaged `vpnc` for my institution's VPN, and things weren't working on NixOS (while they worked on my previous system running Manjaro). I eventually managed to narrow it down to the fact that, despite the version numbers being the same, the version shipped on Arch Linux is actually a fork of the one in nixpkgs, https://github.com/streambinder/vpnc.

In the fork's wiki (https://github.com/streambinder/vpnc/wiki/About), it is said:

> This repository has been forked to follow the work started originally by Maurice Massar. For more information about that, please, point to VPNC original web page.
>
> As stated in vpnc-devel mailing-list (vpnc-devel@2017-November), this repository hasn't been started to start working actively on this project, but to passively merge security patches, fixes and features additions explicitly requested by the community.

From what I undestood, it appears that the original code, present at https://www.unix-ag.uni-kl.de/~massar/vpnc/ is not only no longer maintained, but also contains security issues and is incompatible with some configurations. And, therefore, we should be shipping its maintained fork, https://github.com/streambinder/vpnc.

In the meantime, I was able to setup a (probably hacky) derivation for the fork, which I am using in my `configuration.nix`, and seems to work:

```nix
    stdenv.mkDerivation rec {
      name = "vpnc";
      version = "0.5.3";
      src = fetchFromGitHub {
        owner = "streambinder";
        repo = "vpnc";
        rev = "c8bb5371b881f8853f191c495e762f834c9def5d";
        sha256 = "1j1p83nfc2fpwczjcggsby0b44hk97ky0s6vns6md3awlbpgdn57";
        fetchSubmodules = true;
      };

      buildInputs = [ pkg-config perl libgcrypt gnutls ];

      postPatch = ''patchShebangs src/makeman.pl'';

      makeFlags = [
        "PREFIX=$(out)"
        "ETCDIR=$(out)/etc/vpnc"
        "SCRIPT_PATH=$(out)/etc/vpnc/vpnc-script"
      ];
    };
```

**Comment by MGlolenstine** [comment]
This issue was closed by #163070.
