### ISSUE TITLE
Python installed by `nixpkgs#conda` requires `libffi.so.6` which is not present.

### ISSUE THREAD

**Issue by charmoniumQ** [NixOS/nixpkgs#157860]
### Describe the bug

Python installed by `nixpkgs#conda` requires `libffi.so.6` which is not present.

### Steps To Reproduce
```
$ nix shell nixpkgs#conda --command conda-shell -c 'python -c "import _ctypes"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

### Expected behavior

The command should not error out.

### Additional context

Note that `nixpkgs#libffi` only provides `libffi.so.8` which is not ABI-compatible with `libffi.so.6`.

### Notify maintainers

Conda: @jluttine @bhipple

libffi: @matthewbauer: How to get `libffi.so.6` from Nix?

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.11.0-43-generic, Ubuntu, 20.04.3 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210503_6d2553a`
 - channels(sam): `"home-manager, nixpkgs-21.11pre332093.7fad01d9d5a"`
 - nixpkgs: `/home/sam/.nix-defexpr/channels/nixpkgs`
```

**Comment by FliegendeWurst** [comment]
This was fixed at some point.
