### ISSUE TITLE
nix search does not show Node packages

### ISSUE THREAD

**Issue by AmeerTaweel** [NixOS/nixpkgs#157851]
**Description**

Running `nix search nixpkgs QUERY` does not show Node packages. However, they show up on the [package search web tool](https://search.nixos.org/packages).

**Steps To Reproduce**

1. Go to [package search web tool](https://search.nixos.org/packages).
2. Search for `vue-language-server`. (Any Node package will do the job, but let's use this as an example)
3. You will find the packages `nodePackages.vue-language-server` and `nodePackages_latest.vue-language-server`.
4. Run `nix search nixpkgs vue-language-server` in your terminal.
5. You will **NOT** find the packages `nodePackages.vue-language-server` and `nodePackages_latest.vue-language-server`.

**Expected behavior**

When running `nix search nixpkgs vue-language-server`, I should find `nodePackages.vue-language-server` and `nodePackages_latest.vue-language-server`. This would change for different queries, but the idea is that I should see the Node packages in my search results in the command line.

**`nix-env --version` output**

`nix-env (Nix) 2.7.0pre20220124_0a70b37`

**Comment by hqurve** [comment]
According to the [nix3-search manual](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-search.html), `nix search` only recurses into attribute sets which explicitly set `recurseForDerivations = true`. 

However, in `pkgs/top-level/all-packages.nix`, we set

```
nodePackages_latest = dontRecurseIntoAttrs nodejs_latest.pkgs;

nodePackages = (dontRecurseIntoAttrs nodejs.pkgs).override {
  # It does not work on 16.x: https://github.com/NixOS/nixpkgs/issues/132456
  nodejs = nodejs-14_x;
};

```
which sets the attribute to false. I believe this is done for performance reasons, more specifically

- hydra does not build all nodePackages. For example when I ran `nix-shell -p nodePackages.vue-language-server`, some build operations were done locally.
- Some package sets are not recursed to increase search performance

To work around this, if you know that they package might be in nodePackages, you can search using `nix search nixpkgs#nodePackages vue`.


More info:
- https://github.com/NixOS/nixpkgs/commit/0fa8f6b36ba5f816e4ac31d68e370858007a57b4 
- https://github.com/NixOS/nixpkgs/issues/3594
- https://github.com/NixOS/nixpkgs/issues/30785
- https://github.com/NixOS/nixpkgs/issues/146173
