### ISSUE TITLE
screen dies when ssh connection closes

### ISSUE THREAD

**Issue by tokudan** [NixOS/nixpkgs#15798]
## Issue description

I'm used to running background programs in screen, however I just noticed that screen dies or is killed(?) when I log out and the ssh connection terminates.

### Steps to reproduce

1. Log into a system as a regular user through ssh
2. Open a new screen and enter something so you can recognize the session: screen
3. Hit CTRL+a, d to detach the session
4. Check if screen is still running: screen -ls
5. Disconnect or logout from the ssh connection. If you're using a ControlMaster connection, the background ssh process needs to be terminated.
6. Log into the system again
7. Check if screen is still running (it will be gone): screen -ls

## Technical details

* System: 16.09pre84211.d231cdf (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre84211.d231cdf"

**Comment by wkennington** [comment]
This is part of systemd-230 which kills all processes when a session ends.
You need to use user services or a new command to mark a process that
should live past the kill barrier.

**Comment by bjornfor** [comment]
According to an example in ```man systemd-run```:

```
systemd-run --scope --user screen
```

**Comment by tokudan** [comment]
ok... so apparently the solution are these two commands:
```
# loginctl enable-linger
# alias screen='systemd-run --scope --user screen'
```
The alias command should be put into bashrc or maybe better programs.bash.interactiveShellInit
