### ISSUE TITLE
fcgiwrap fails to build

### ISSUE THREAD

**Issue by k0ral** [NixOS/nixpkgs#15791]
## Issue description
When building fcgiwrap derivation, the following error is raised at configure step:

    configure: error: systemd support requested but libraries not found

There was no recent change on fcgiwrap. Systemd is correctly listed as a dependency.
Useful link: https://github.com/gnosek/fcgiwrap/blob/master/configure.ac

### Steps to reproduce
Build the fcgiwrap derivation.

## Technical details

* System: NixOS: channel nixos-unstable
* Nix version: nix-env (Nix) 1.10
* Nixpkgs version: local clone of nixpkgs pointing to nixos-unstable

**Comment by valeriangalliat** [comment]
Similar problem as with https://github.com/NixOS/nixpkgs/commit/f0de1c75b5241544eb80e05a0ed60acc6a1e27f8 apparently, need to use `libsystemd` instead of `libsystemd-daemon`.

I'm coming with a patch.
