### ISSUE TITLE
Packaging request: Motrix

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#157984]
**Project description**

Motrix is a full-featured download manager that supports downloading HTTP, FTP, BitTorrent, Magnet, etc.

**Metadata**

* homepage URL: https://motrix.app
* source URL: https://github.com/agalwood/Motrix
* license: mit
* platforms: linux, darwin, windows

**Comment by mainrs** [comment]
I can do that!

**Comment by Eliot00** [comment]
@mainrs hello, are you still doing this?

**Comment by mainrs** [comment]
Sorry for not reporting back! I have tried but I have trouble with Electron apps on my installation in general and therefore can't test the derivation properly. Might be better if someone can step in and take over.
