### ISSUE TITLE
When using `python.withPackages` overrides are lost.

### ISSUE THREAD

**Issue by neosimsim** [NixOS/nixpkgs#157958]
We override and and patch some python libraries and bundle those using `withPackages`.
After using `withPackages` the patched version is not part of the `pkgs` set anymore.

### Steps To Reproduce
Create `my-python.nix`

```
{ pkgs ? import <nixpkgs> { } }:
let
  myPython = pkgs.python38.override {
    packageOverrides = self: super: {
      myMatplotlib = super.matplotlib;
    };
  };
in
{
  python = myPython;
  pythonW = myPython.withPackages (p: [ p.myMatplotlib ]);
}
```

and try to instantiate `myMatplotlib` of `python` and `pythonW`.

`python.pkgs.myMatplotlib` works:

```
$ nix-instantiate -A python.pkgs.myMatplotlib my-python.nix
/nix/store/6z9d2yz98wrh64zkxzaapyyidkcc0gdf-python3.8-matplotlib-3.5.1.drv
```

but `pythonW.pkgs.myMatplotlib` does not, which seems to be a bug:

```
$ nix-instantiate -A pythonW.pkgs.myMatplotlib my-python.nix
error: attribute 'myMatplotlib' in selection path 'pythonW.pkgs.myMatplotlib' not found
```

@fridh you seem to have touche `withPackages` last

```
$ git blame pkgs/development/interpreters/python/default.nix | grep 'withPackages ='
efbe87f3ef76 (Frederik Rietdijk    2018-12-31 13:59:20 +0100 105)         withPackages = import ./with-packages.nix { inherit buildEnv pythonPackages;};
```

**Comment by FRidh** [comment]
The interpreter has a `passthru`. When you use `withPackages` or `buildEnv`, you get a different derivation. While some of the `passthru` items from the interpreter are part of this one, apparently not everything is. One can ask the question whether it should.

**Comment by neosimsim** [comment]
> One can ask the question whether it should.

Not really clear to me, tbh. One could argue that you shouldn't use `pkgs` once you finalized with `withPackages`.

For now I as a workaround I just overwrite `pkgs`

```
python =
      let
        withPackages = python.withPackages (pythonPkgs: with pythonPkgs; [...]);
      in
      withPackages
        // { inherit (python) pkgs; };
```

**Comment by FRidh** [comment]
The following shows how you can still access the overridden set:
```
$ nix eval --impure --expr '(let python = (import (fetchTarball "channel:nixos-21.11") {}).python3.override {packageOverrides=(self: super: {mymatplotlib=super.matplotlib;}); self = python;}; in python.withPackages(ps: [])).python.pkgs.mymatplotlib.pname'
```
The reason it was not working for you was because you did not pass the overridden interpreter to itself. The Nixpkgs manual shows that when correctly overriding that is needed.

**Comment by neosimsim** [comment]
Thank you. I found it.
