### ISSUE TITLE
Source Sans Por font package renamed font breaking all referenes to it

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#157972]
### Describe the bug
The `Source Sans Pro` font as installed by the `source-sans-pro` package, is now called `Source Sans 3`. This breaks all references to the font in documents, but also in web pages, etc. The font 

### Steps To Reproduce

Open this webpage: https://github.com/arximboldi/immer
The logo uses the Source Sans Pro font and it should look correct when the `source-sans-pro` package is installed. Instead, it shows an alternative font with serif.

### Expected behavior
The font should be called `Source Sans Pro` and not `Source Sans Pro 3`, keeping all references. If this was not desirable (because the font is just too different) then a package should be provided to install the old version with the old name.

### Notify maintainers

@ttuegel

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d, nixos-18.03-18.03.133402.cb0e20d6db9, nixos-18.09-18.09.2574.a7e559a5504, nixos-19.03-19.03.173691.34c7eb7545d, nixos-19.09-19.09.2522.75f4ba05c63, nixos-20.03-20.03.3330.1db42b7fe38, nixos-20.09-20.09.4407.1c1f5649bb9, nixos-unstable-22.05pre350017.efeefb2af14"`
 - channels(raskolnikov): `"nixgl, nixpkgs-22.05pre335173.56cbe42f166"`
 - nixpkgs: `/home/raskolnikov/.nix-defexpr/channels/nixpkgs`
```

**Comment by andersk** [comment]
The upstream name change was intentional (adobe-fonts/source-serif#77).

**Comment by arximboldi** [comment]
Thank you andersk that explains a lot! I guess then it makes sense to also install the older version?

**Comment by ttuegel** [comment]
We should be able to deal with this through fontconfig.

**Comment by wentasah** [comment]
If I understand correctly, it's not only the name that has been changed, but the renamed font has also different metrics. This means that if we just configure fontconfig to replace "Source Sans Pro" with "Source Sans 3", the layout of existing documents might change.

So I think, it would make sense to either reintroduce Pro fonts as a separate package, or include the older (Pro) version together with the new one (which is what [Archlinux is doing](https://github.com/archlinux/svntogit-packages/blob/packages/adobe-source-sans-fonts/trunk/PKGBUILD)).

If @ttuegel is interested, I can turn [my commit](https://github.com/wentasah/nixpkgs/commit/7a9a5af08d12df8c977f27962996f05e740058cb), which does the former, to a PR.

**Comment by arximboldi** [comment]
> So I think, it would make sense to either reintroduce Pro fonts as a separate package, or include the older (Pro) version together with the new one (which is what [Archlinux is doing](https://github.com/archlinux/svntogit-packages/blob/packages/adobe-source-sans-fonts/trunk/PKGBUILD)).

I agree. Either of these two solutions would be satisfying to me.

**Comment by ttuegel** [comment]
> So I think, it would make sense to either reintroduce Pro fonts as a separate package, or include the older (Pro) version together with the new one (which is what [Archlinux is doing](https://github.com/archlinux/svntogit-packages/blob/packages/adobe-source-sans-fonts/trunk/PKGBUILD)).
> 
> If @ttuegel is interested, I can turn [my commit](https://github.com/wentasah/nixpkgs/commit/7a9a5af08d12df8c977f27962996f05e740058cb), which does the former, to a PR.

@wentasah I wasn't aware of the metrics changes. I think adding the older version back as a new package makes perfect sense, thank you!
