### ISSUE TITLE
boot.initrd.secrets omits key file and fails during initial installation

### ISSUE THREAD

**Issue by ne9z** [NixOS/nixpkgs#157989]
### Describe the bug
Unfortunately I can not pinpoint the issue, but it seems that after a `nixos-rebuild switch --upgrade` on Feb 1st, boot.initrd.secrets starts to omit a key file out of 3 key files and completely fails with a fresh system installation.

### Steps To Reproduce
1. configuration.nix contains the following lines
```
  boot.initrd.secrets = {
    "/etc/cryptkey.d/rpool_${poolUuid}-nixos-key-zfs" = null;
    "/etc/cryptkey.d/bpool_${poolUuid}-key-luks" = null;
    "/etc/cryptkey.d/${diskName}-part4-key-luks-swap" = null;
  };

```

All three files exist on disk.

2. nixos-rebuild switch produces a initrd-secret archive that is missing the third key file.
3. Fresh system installation produces the following:
```
+ nixos-enter --root /mnt -- /run/current-system/bin/switch-to-configuration boot
setting up /etc...
updating GRUB 2 menu...
mktemp: failed to create directory via template ‘/mnt/tmp.torvrvFbQ5/initrd-secrets.XXXXXXXXXX’: No such file or directory
failed to create initrd secrets: No such file or directory
+ rm -rf /mnt/tmp.torvrvFbQ5
```

### Expected behavior
All key files are included in generated initrd-secrets and `nixos-install --root=/mnt` does not fail.

### Additional context
This issue does not exist before system update.

### Notify maintainers

This option is declared in <nixpkgs/nixos/modules/system/boot/stage-1.nix>.

@dasJ @grahamc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.17, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d"`
 - channels(user0): `"home-manager-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ne9z** [comment]
I specifically installed an encrypted root on zfs system with [this article](https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS/3-optional-configuration.html#encrypt-boot-pool).  GRUB will decrypt disk on boot and initrd will re-decrypt disk partitions and swap with the keys embedded here.

**Comment by maxbrunet** [comment]
I have faced that too, there seem to be a problem with `TMPDIR` here:
https://github.com/NixOS/nixpkgs/blob/ac8ded5c78b49f4d8141e7a3ea0c2f086a59a70c/nixos/modules/system/boot/stage-1.nix#L432

Not sure where it is set from, but its value should be relative to the chroot, e.g. `/tmp.torvrvFbQ5/initrd-secrets.XXXXXXXXXX`, not `/mnt/tmp.torvrvFbQ5/initrd-secrets.XXXXXXXXXX`.

It can be worked around by setting `TMPDIR` to an existing directory before installing/rebuilding, for example:
```shell
export TMPDIR=/tmp
```

Or by preparing a directory with `mktemp` yourself:

```shell
tmp="$(mktemp -d /mnt/tmp.XXXXXXXXXX)"
export TMPDIR="${tmp#/mnt}"
echo "${TMPDIR}" # /tmp.torvrvFbQ5
```

**Comment by maxbrunet** [comment]
May be a duplicate of #73404

**Comment by ncfavier** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/73404#issuecomment-1368423880 indeed.
