### ISSUE TITLE
Cheese will not close once a video is recorded, causes spiked CPU usage.

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#15790]
## Issue description

Once you take a video with cheese (as webm), a few strange things happen:
- No thumbnails for images or videos will load.
- Cheese will refuse to close without a 'kill/killall .cheese-wrapped'

Errors:

```
** (cheese:3543): WARNING **: Icon 'application-octet-stream' not present in theme gnome

(cheese:3543): GnomeDesktop-WARNING **: Unable to create loader for mime type application/octet-stream: Unrecognized image file format

(cheese:3543): GnomeDesktop-WARNING **: Error creating thumbnail for file:///home/sheenobu/videos/Webcam/2016-05-28-140931.webm: Unrecognized image file format

** (cheese:3543): WARNING **: could not generate thumbnail for /home/sheenobu/videos/Webcam/2016-05-28-140931.webm (application/octet-stream)
```
### Steps to reproduce
1. Record video in cheese.
2. Close cheese via 'Quit' button OR by closing the window

Check `ps aux | grep cheese` (cheese will still be running) and taking up 
quite a bit of CPU.

Normal behavior is returned once webm file is moved or deleted.
## Technical details

Cheese doesn't understand webm yet tries to record as webm. Then every attempt at loading the webm in the preview pane causes an error.

Maybe a dependency issue and we should depend on some webm support library? Or an upstream issue with Cheese itself?
- System: 16.09.1445.e9a8853 (Flounder); 16.03.885.15e7e6e (Emu)
- Nix version: nix-env (Nix) 1.11.4; nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09.1445.e9a8853; 16.03.885.15e7e6e
- Cheese version: 3.20.2; 3.18.1

**Comment by sheenobu** [comment]
Updated. Still an issue in 16.09.

**Comment by dtzWill** [comment]
I can reproduce the problems with thumbnails and webm-related issues on 17.03 and master.

It doesn't seem to crash on exit in my testing.

Playing with `propagatedUserEnvPkgs` gets problems with missing `gnome-video-effects` to disappear, adding gstreamer bits (like is done in totem or sushi) doesn't seem to be sufficient (I'm no expert here).

Related: #11634

**Comment by jtojnar** [comment]
I opened an upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=791120

**Comment by jtojnar** [comment]
Running cheese with `G_MESSAGES_DEBUG=all` environment variable revealed missing path to bubblewrap.

```
(cheese:15438): GnomeDesktop-DEBUG: Failed to launch script: Failed to execute child process “bwrap” (No such file or directory)
(cheese:15438): GnomeDesktop-DEBUG: Thumbnail script ('/nix/store/03b1njbh3p0akk5sqpplknarz6z8pl7l-totem-3.26.0/bin/totem-video-thumbnailer -s %s %u %o') failed for 'file:///home/jtojnar/Videos/Webcam/2017-12-02-053038.webm': Failed to execute child process “bwrap” (No such file or directory)
```

After patching `gnome_desktop`, user still needs to have thumbnailers (`gdk_pixbuf` and `totem`) installed, for now I have added them as dependencies like I did in #29970.

The infinite loop is still an upstream error but with thumbnailers, it at least should not appear.
