### ISSUE TITLE
DVC 2.9.3 has a bug in the dvc daemon patch

### ISSUE THREAD

**Issue by akiross** [NixOS/nixpkgs#157998]
### Describe the bug
There's a bug in the dvc daemon patch updated in PR #155094, here the relevant lines
```
+    cmd = [ "@dvc@" , "daemon", "-q"] + args
+    env = None
     env[DVC_DAEMON] = "1"
```

this causes env to be `None`d and being indexed the line after that, which raises an error when running `dvc init` or other commands

```
Traceback (most recent call last):
  File "/nix/store/c4m423nh1nqqrx793qrlxxm1m8vzwkli-dvc-2.9.3/bin/.dvc-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/c4m423nh1nqqrx793qrlxxm1m8vzwkli-dvc-2.9.3/lib/python3.9/site-packages/dvc/main.py", line 98, in main
    analytics.collect_and_send_report(args, ret)
  File "/nix/store/c4m423nh1nqqrx793qrlxxm1m8vzwkli-dvc-2.9.3/lib/python3.9/site-packages/dvc/analytics.py", line 37, in collect_and_send_report
    daemon(["analytics", fobj.name])
  File "/nix/store/c4m423nh1nqqrx793qrlxxm1m8vzwkli-dvc-2.9.3/lib/python3.9/site-packages/dvc/daemon.py", line 108, in daemon
    env[DVC_DAEMON] = "1"
TypeError: 'NoneType' object does not support item assignment
```

### Steps To Reproduce
1. Get a dev shell with dvc 2.9.3, I used `nix shell nixpkgs/nixos-unstable#dvc`
2. `git init` a repository, then `dvc init` it as well

### Expected behavior
DVC initializes the repository without errors.

### Notify maintainers
@fabaff @CMCDragonkai 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.12-100.fc34.x86_64, Fedora, 34 (Server Edition)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by TheAncientGoat** [comment]
Currently dvc fails to build on master / unstable due to asyncssh being too modern for scmrepo - here's a flake I made resolving the issue + including this patch if anyone wants to carry it forward: https://gist.github.com/TheAncientGoat/0cc387f48b9a43906610174dfc9e7a1f

**Comment by TheAncientGoat** [comment]
https://github.com/iterative/scmrepo has to be updated to support the latest version. Might be as easy as just removing the version restriction and re-building it; could help to create an issue on their side if that doesn't work

**Comment by fabaff** [comment]
There is a bit of a chain to get it working again. The next `staging` merge will bring us a step closer as `gpgme` will get support for Python 3.10 and will allow us to update `scmrepo`.

Unfortunately, it can't be fixed in `staging` at the moment because `gfortran` has issues.
