### ISSUE TITLE
Can't enable user service: Too many levels of symbolic links

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#15806]
## Issue description

When trying to enable a systemd user service, I get a `Too many levels of symbolic links`.

### Steps to reproduce
1. Add this to your `configuration.nix`
    ```
    {
    systemd.user.services.emacs = {
        description                 = "Emacs: the extensible, self-documenting text editor";
    
        serviceConfig               = {
          Type      = "forking";
          ExecStart = "${bigEmacs}/bin/emacs --daemon";
          ExecStop  = "${bigEmacs}/bin/emacsclient --eval (kill-emacs)";
          Restart   = "always";
        };
    }
    ```
2. run `sudo nixos-rebuild switch`
3. run `systemctl --user enable emacs`

## Technical details

* System: NixOS: `channels/nixos-unstable` d231cdf51fd00400f20815d5e2a7c84d1d23f891
* Nix version: 1.11.2
* Nixpkgs version: `channels/nixos-unstable` d231cdf51fd00400f20815d5e2a7c84d1d23f891

**Comment by DamienCassou** [comment]
@joachifm Another systemd user service UX problem, see also #7329 and #7326

**Comment by anderspapitto** [comment]
actually, you're probably just running into https://github.com/NixOS/nixpkgs/issues/7326 directly. Try `systemctl --user daemon-reload` first

**Comment by anderspapitto** [comment]
also, systemctl enable/disable isn't supported at all in nixos (also for system level services). Which services are enabled is determined by what's in configuration.nix (to have the "declarative" property)

**Comment by DamienCassou** [comment]
Thanks for the answer. `daemon-reload` doesn't change anything, my unit is not updated. I will investigate.

**Comment by DamienCassou** [comment]
It works fine now...
