### ISSUE TITLE
neovim fails to enable syntax highlighting as non-root user

### ISSUE THREAD

**Issue by sephalon** [NixOS/nixpkgs#15805]
## Issue description

If you try to enable syntax highlighting (`syntax on`) in neovim as a _non-root_ user, it fails with the following error message:

```
Error detected while processing "/nix/store/xq1gr3ja50cy5mss95515vxv5srb50fg-neovim-0.1.3/share/nvim/runtime/syntax/syntax.vim":
line   42:
E216: No such group or event: filetypedetect BufRead
```
### Steps to reproduce

Execute `:syntax on` as non-root user in neovim.
## Technical details
- System: 16.09.git.0b7e6deM (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09.git.0b7e6deM"

**Comment by bjornfor** [comment]
I don't know which version that is. I tried removing the "M", but still git doesn't recognize that commit.

I tried it on latest master branch (8d1fec55f68ffb20a4f1cf96cf444160236542db):

```
$ nix-build -A neovim && ./result/bin/nvim README.md   # open nixpkgs README file
```

Then I type ```:syntax on```. I see syntax highlight appear, but no error message.

(Btw, my neovim is unconfigured, I have nothing in ~/.config/nvim.)

**Comment by bjornfor** [comment]
All this, as my own user (non-root).

**Comment by luispedro** [comment]
I see the same thing on nixos. The culprit seems to be a very long `XDG_DATA_DIRS` environmental variable.

If `XDG_DATA_DIRS` is longer than 2955 characters on my system, I get the error above. Otherwise, I get syntax highlighting.

**Comment by sephalon** [comment]
Yeah, I also realized that this has something to do with length as the bug only occurs when I run neovim in a GNOME session. On my system, the maximum length of `XDG_DATA_DIRS` is 3433 chars though.

Since setting a arbitrary long `runtimepath` in the `init.vim` does not exhibit the same problem, the bug is probably somehow related to parsing`XDG_DATA_DIRS`. I guess we have to open an issue at upstream.

**Comment by luispedro** [comment]
Upstream has acknowledged that this is a neovim issue. I recommend closing here.

**Comment by davorb** [comment]
@luispedro that issue seems to have been closed, without this problem having been fixed.

**Comment by luispedro** [comment]
It seems that at least some fixes were merged into the upstream neovim. The problem seems to be gone on nixos as well, although my `XDG_DATA_DIRS` is now very short (perhaps there was some reorganization of how that's handled as well).

**Comment by primeos** [comment]
(triage) Seems to me like we can close this. Please drop a comment if you still get that error message.
