### ISSUE TITLE
nyxt-2.2.3: ERROR **: 00:27:46.959: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.

### ISSUE THREAD

**Issue by jian-lin** [NixOS/nixpkgs#158005]
### Describe the bug
When I open (C-l) a url, nyxt hangs and this message is printed in the console:

```console
** (nyxt:401949): ERROR **: 00:27:46.959: Unable to configure xdg-desktop-portal access in the WebKit sandbox: GApplication is required.
<WARN> [00:27:46] Warning: Error on GTK thread: The value
                       :INVALID-CODE-OBJECT-AT-PC
                     is not of type
                       FUNCTION
```

If I disable sandbox through `export WEBKIT_FORCE_SANDBOX=0`, no error occurs.

### Steps To Reproduce
1. open nyxt
2. open a url, e.g. https://bing.com

### Notify maintainers
@nlewo

### Metadata

```console
$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.93, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kenranunderscore** [comment]
I'm seeing the same; wanted to try out the browser yesterday with a roughly 1-week old pin.

Did it work earlier? If so I might try to go back in time to check it out.

**Comment by lostnet** [comment]
Seems to be tracked down to webkitgtk updates:
https://github.com/atlas-engineer/nyxt/issues/1781
https://github.com/atlas-engineer/nyxt/pull/1505#issuecomment-961925290

**Comment by jian-lin** [comment]
This seems like a nixpkgs issue. If I build nyxt from scratch, i.e. `make all` in the nix shell using `build-scripts/shell.nix` in the nyxt project, `export WEBKIT_FORCE_SANDBOX=0` is not needed.


I am new to common lisp. Do you have any ideas? @nlewo @7c6f434c @sternenseemann

**Comment by sternenseemann** [comment]
@jian-lin What version of `nyxt` did you build? I'd expect that it is working because the sandbox is disabled on nyxt's side since https://github.com/atlas-engineer/nyxt/commit/48ac0d8727f1ca1428188a1ab2c05b7be5f6cc51, but this commit is not part of any release and thus not in nixpkgs.

A workaround in nixpkgs could be applying the commit as a patch on top of the release we're shipping until upstream comes up with a proper solution.

**Comment by OliverEvans96** [comment]
I can confirm that building from source on `master` via `make` on NixOS works, but installing from nixpkgs produces this issue.

**Comment by OliverEvans96** [comment]
Although disabling sandboxing doesn't seem like a good long-term solution, in the meantime, I've wrapped `nyxt` in my personal NixOS config to set the env var at runtime without writing it explicitly at the terminal each time.

```nix
let
  nyxt = pkgs-unstable.nyxt.overrideAttrs (oldAttrs: {
    postFixup = ''
      wrapProgram $out/bin/nyxt \
        --set-default WEBKIT_FORCE_SANDBOX 0
    '';
  });
in {
  environment.systemPackages = [ nyxt ];
}
```

**Comment by kenranunderscore** [comment]
I'm quite sure that I've tried the update to 2.2.4 locally (and AFAIR updating the version number sufficed for it to work), but it had the same problem on my machine. Hence it's probably worth PR'ing this together with the proposed workaround.

**Comment by sternenseemann** [comment]
@kenranunderscore the change is not part of the 2.2.4 release, so the patch would need to be picked via fetchpatch.

**Comment by sternenseemann** [comment]
#180238
