### ISSUE TITLE
Adding a systemd user service for Emacs in NixOS

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#15807]
## Issue description

Several users are manually adding a systemd user service to their `configuration.nix`. It would be better to create a NixOS module so that people don't copy/paste half-baked definitions.

What do you think?

**Comment by DamienCassou** [comment]
Versions of such a user service can be found at:

- [@anderspapitto](https://github.com/NixOS/nixpkgs/issues/7329)
- [@TikhonJelvis](https://github.com/TikhonJelvis/dotfiles/blob/master/configuration.nix#L128)
- [@DamienCassou](https://gist.github.com/DamienCassou/0ca0a0b116acbdd77b6256c0b303bdc5)

Please tell me where I can find your version so we merge them all

**Comment by ttuegel** [comment]
On a related note, I use an XDG autostart [file](https://github.com/ttuegel/nixos-config/blob/master/programs/emacs.nix) to start the Emacs daemon. This may be preferable for some people because the environment will be set up correctly, though there are of course other ways to achieve this.

**Comment by rvl** [comment]
Sounds like a great idea to me. Those versions look quite similar to mine.

1. I build my emacs with GTK3 enabled. So there would obviously need to be a `services.emacs.package` config option.

2. Would there be a configuration option for the list of Melpa packages, or would this be handled using `emacsWithPackages` and the `services.emacs.package` option?

3. Re: Tikon's config. Having `wantedBy = [ "default.target" ];` will result in starting emacs for every user who logs in.

   For a general NixOS module it would be best to leave `wantedBy` empty and let the user enable the service with `systemctl --user enable emacs` (or adding a symlink in `~/.config/systemd/user`).

4. Re: Damien's config, You probably already know, but setting the `PHARO_VM` variable could be achieved by putting this in your configuration:
   ```
   environment.variables.PHARO_VM = "${pkgs.pharo-vm}/bin/pharo-vm-nox";
   ```
   Other variables such as `LOCATE_PATH` should already be taken care of by sourcing `${config.system.build.setEnvironment}`.

5. I note that systemd socket activation for Emacs server was implemented in April and should appear in Emacs 25.2.

**Comment by DamienCassou** [comment]
Please see PR #16356. 

@rvl thanks for your feedback. 

> Would there be a configuration option for the list of Melpa packages, or would this be handled using `emacsWithPackages` and the `services.emacs.package` option?

I didn't do anything special yet. I have the impression allowing that would just duplicate `emacsWithPackages` features. But I really don't know. Any opinion?

**Comment by rvl** [comment]
> I didn't do anything special yet. I have the impression allowing that would just duplicate `emacsWithPackages` features. But I really don't know. Any opinion?

Yes, it does overlap a little. I am trying to find out if it's possible to make the configuration of emacs any simpler for newcomers. In this case, I think not.
