### ISSUE TITLE
wpa_supplicant.conf wrongly generated

### ISSUE THREAD

**Issue by rhoriguchi** [NixOS/nixpkgs#158063]
### Describe the bug
When using `wpa_supplicant` and setting `networking.wireless.networks.<name>.authProtocols = [ "SAE" ]` it creates a duplicate entry of the network and one of them has an empty value for `key_mgmt`.

```conf
network={
  ssid="SSID"
  key_mgmt=SAE
  psk="12345678"
  priority=1
}

network={
  ssid="SSID"
  key_mgmt=
  psk="12345678"
}

pmf=1
bgscan="simple:30:-70:3600"
```

### Steps To Reproduce
Set this and rebuild.
```nix
networking.wireless.networks."SSID" = {
  psk = "12345678";
  authProtocols = [ "SAE" ];
};
```

### Expected behavior
Expected `wpa_supplicant.conf`
```conf
network={
  ssid="SSID"
  key_mgmt=SAE
  psk="12345678"
  priority=1
}

pmf=1
bgscan="simple:30:-70:3600"
```

### Additional context
`nixos-unstable` https://github.com/NixOS/nixpkgs/commit/7f65e4abd5ecaad12d2d26e4380d1a7d8edafea7

### Notify maintainers
@rnhmjoj

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.4, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

---

Edited:

I suspect https://github.com/NixOS/nixpkgs/commit/2eed89bbe1fd431079b6c824bbcb66a92d3bff7c is the issue. When setting `networking.wireless.fallbackToWPA2 = false` it fixes the issue. 

The expected file should have a duplicated of the network but the priority should be `priority=2` and the protocol should be `key_mgmt=WPA-PSK WPA-EAP FT-PSK FT-EAP`.

**Comment by rnhmjoj** [comment]
For tracking the fix: https://nixpk.gs/pr-tracker.html?pr=158085
