### ISSUE TITLE
v8 fails to build on darwin

### ISSUE THREAD

**Issue by viraptor** [NixOS/nixpkgs#158076]
### Describe the bug
V8 fails to build with:
```
In file included from ../../src/libplatform/tracing/trace-writer.cc:14:
../../src/libplatform/tracing/recorder.h:17:10: fatal error: 'os/signpost.h' file not found
#include <os/signpost.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

### Steps To Reproduce
1. build v8 from latest unstable (v8-9.7.106.18)

### Additional context

It seems the same issue has been discussed and fixed for nodejs here https://github.com/NixOS/nixpkgs/pull/132543 so the fix for v8 should be similar.

### Notify maintainers
@cstrahan @proglodyte @matthewbauer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(viraptor): `"home-manager-21.11.tar.gz, unstable"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by viraptor** [comment]
Doesn't seem to be the only issue. After patching the dependency locally, I also get:
```
In file included from ../../src/base/numbers/strtod.cc:9:
/nix/store/64nxa8d4zwvfycksdf3ahj4rxr2a08gj-libcxx-11.1.0-dev/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/nix/store/64nxa8d4zwvfycksdf3ahj4rxr2a08gj-libcxx-11.1.0-dev/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace; did you mean '__fpclassify'?
using ::fpclassify;
      ~~^
/nix/store/vf34267rv2j7kpmcls9rhbcml75f3l63-Libsystem-1238.60.2/include/math.h:130:12: note: '__fpclassify' declared here
extern int __fpclassify (long double);
```

**Comment by viraptor** [comment]
Related https://github.com/NixOS/nixpkgs/issues/63046

**Comment by veprbl** [comment]
> Doesn't seem to be the only issue. After patching the dependency locally, I also get:
> 
> ```
> In file included from ../../src/base/numbers/strtod.cc:9:
> /nix/store/64nxa8d4zwvfycksdf3ahj4rxr2a08gj-libcxx-11.1.0-dev/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
> using ::signbit;
>       ~~^
> /nix/store/64nxa8d4zwvfycksdf3ahj4rxr2a08gj-libcxx-11.1.0-dev/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace; did you mean '__fpclassify'?
> using ::fpclassify;
>       ~~^
> /nix/store/vf34267rv2j7kpmcls9rhbcml75f3l63-Libsystem-1238.60.2/include/math.h:130:12: note: '__fpclassify' declared here
> extern int __fpclassify (long double);
> ```

This is a known issue that the Libsystem's math.h conflicts with libcxx

**Comment by viraptor** [comment]
Just switching to `llvmPackages.libcxxStdenv` as some similar issues mention did not solve the math include problem :(

**Comment by veprbl** [comment]
You probably need to make a "proxy" derivation that only includes the necessary headers from `Libsystem`. Or you could just patch out the functionality that depends on sigpost.

**Comment by viraptor** [comment]
I may poke around a bit, but it's unlikely I'll dig deep enough to solve it properly. So if anyone knows what they're doing, please have a look.

**Comment by viraptor** [comment]
Some more research info:
- you can add `"v8_enable_system_instrumentation=false"` to disable the feature requiring `signpost.h` during compilation
- the next failure in that case becomes not being able to find `llvm-ar` which is expected in `clang_base_path="${stdenv.cc}"`
- if you change that to `${llvmPackages.bintools}` then the compiler can't be found
- setting the `AR` environment variable to the `llvm-ar` path doesn't seem to do anything

The build system of v8 doesn't seem to have a way to specify two base paths (one for clang / clang++ and one for llvm-ar), and nixpkgs has those in separate places.

**Comment by veprbl** [comment]
> * the next failure in that case becomes not being able to find `llvm-ar` which is expected in `clang_base_path="${stdenv.cc}"`
> * if you change that to `${llvmPackages.bintools}` then the compiler can't be found

Can use something like
```nix
symlinkJoin {
  paths = [ stdenv.cc llvmPackages.bintools ];
}
```

**Comment by viraptor** [comment]
Slow progress forwards, with the following changes:
- "v8_enable_system_instrumentation=false"
- clang base being a merge of stdenv.cc and llvm
the compilation goes further, but fails with:
```
clang++: error: invalid linker name in argument '-fuse-ld=lld'
```
at the `LINK default/bytecode_builtins_list_generator` step.

It looks like lld is not available on macos. There's this similar envoy issue: https://github.com/envoyproxy/envoy/issues/16482#issuecomment-962372629
Unfortunately v8 doesn't expose `use_lld` as a variable. There seems to be a `use_gold` which I tried setting to true, but it still requested lld anyway.

**Comment by veprbl** [comment]
Could it be that `lld` just needs to go to `nativeBuildInputs`?

Alternatively, you probably can patch out that option from v8.

**Comment by viraptor** [comment]
I'll give native inputs a go, but given it's in the same group of symlinks as clang (which works) I'm not expecting much.
I looked at patching the option itself, however it doesn't exist directly in the v8 sources. It could come from somewhere internal to bazel or ninja build systems.

**Comment by veprbl** [comment]
I did a small test:
```
# nix-shell -p stdenv.cc --pure --run "clang++ -fuse-ld=lld /dev/null"                    
clang-7: error: invalid linker name in argument '-fuse-ld=lld'
# nix-shell -p stdenv.cc -p llvmPackages.lld --pure --run "clang++ -fuse-ld=lld /dev/null"
ld64.lld: warning: ignoring unknown argument: -no_uuid
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
Cannot open /dev/null: Exec format error
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```
It would seem like just having lld in the $PATH should be enough.

From my experience with bazel, the rules_cc doesn't even use clang++, it always calls clang. So I'd guess you are dealing with some other build system. A useful check would be to run `grep -r fuse-ld=lld /nix/store` to see which tool sets that option.

**Comment by viraptor** [comment]
So the actual step is:
```
[274/3262] LINK default/bytecode_builtins_list_generator
FAILED: default/bytecode_builtins_list_generator
python3 "../../build/toolchain/gcc_link_wrapper.py" --output="default/bytecode_builtins_list_generator" -- clang++ -fuse-ld=lld -Wl,-fatal_warnings -Wl,--color-diagnostics -stdlib=libc++ -arch x86_64 -no-canonical-prefixes -isysroot ../../../../../../nix/store/dv68n128pgabr15ys9gs4gmakra2n333-xcodebuild-0.1.2-pre/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11.0 -Wl,-ObjC -Wl,-dead_strip -o "default/bytecode_builtins_list_generator"  @"default/bytecode_builtins_list_generator.rsp"
clang++: error: invalid linker name in argument '-fuse-ld=lld'
```
I'm pointing the `clang_base_path` at `symlinkJoin { name= "llvmCcAndBintools"; paths = [ stdenv.cc llvm lld ]; }` and that includes `clang`, `clang++`, `llvm-ar`, `lld` so in theory all the needed parts - listing it in nix/store confirms. (it's in nativeBuildInputs too)

I got nix to corrupt its store though, so I'm taking a break from this.

**Comment by veprbl** [comment]
> So the actual step is:
> 
> ```
> [274/3262] LINK default/bytecode_builtins_list_generator
> FAILED: default/bytecode_builtins_list_generator
> python3 "../../build/toolchain/gcc_link_wrapper.py" --output="default/bytecode_builtins_list_generator" -- clang++ -fuse-ld=lld -Wl,-fatal_warnings -Wl,--color-diagnostics -stdlib=libc++ -arch x86_64 -no-canonical-prefixes -isysroot ../../../../../../nix/store/dv68n128pgabr15ys9gs4gmakra2n333-xcodebuild-0.1.2-pre/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11.0 -Wl,-ObjC -Wl,-dead_strip -o "default/bytecode_builtins_list_generator"  @"default/bytecode_builtins_list_generator.rsp"
> clang++: error: invalid linker name in argument '-fuse-ld=lld'
> ```

This does look like bazel.

> 
> I'm pointing the `clang_base_path` at `symlinkJoin { name= "llvmCcAndBintools"; paths = [ stdenv.cc llvm lld ]; }` and that includes `clang`, `clang++`, `llvm-ar`, `lld` so in theory all the needed parts - listing it in nix/store confirms. (it's in nativeBuildInputs too)
> 

I was assuming that clang itself is getting called by an absolute path $clang_base_path/bin/clang++, but clang++ itself doesn't know about $clang_base_path, it can only lookup executables in $PATH.

**Comment by viraptor** [comment]
No resolution yet, but some more info for future reference. After updating nix unstable and rebuilding things from scratch, I get more explicit warnings/errors:
```
[437/3262] LINK default/bytecode_builtins_list_generator
FAILED: default/bytecode_builtins_list_generator
python3 "../../build/toolchain/gcc_link_wrapper.py" --output="default/bytecode_builtins_list_generator" -- clang++ -fuse-ld=lld -Wl,-fatal_warnings -Wl,--color-diagnostics -stdlib=libc++ -arch x86_64 -no-canonical-prefixes -isysroot ../../../../../../nix/store/dv68n128pgabr15ys9gs4gmakra2n333-xcodebuild-0.1.2-pre/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11.0 -Wl,-ObjC -Wl,-dead_strip -o "default/bytecode_builtins_list_generator"  @"default/bytecode_builtins_list_generator.rsp"
ld64.lld: warning: ignoring unknown argument: -platform_version
ld64.lld: warning: ignoring unknown argument: -no_uuid
ld64.lld: warning: ignoring unknown argument: -fatal_warnings
ld64.lld: warning: ignoring unknown argument: --color-diagnostics
ld64.lld: warning: ignoring unknown argument: -ObjC
ld64.lld: warning: -sdk_version is required when emitting min version load command.  Setting sdk version to match provided min version
Cannot open macos: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
so clang++ is found and lld is found now as well. Not a common issue, there's only one reference at https://www.reddit.com/r/rust/comments/kypi0l/what_is_the_current_way_to_link_with_lld_on_macos/

**Comment by veprbl** [comment]
Perhaps you could try monitoring the build with `sudo dtruss -n ld64` or add `NIX_DEBUG=1;`

**Comment by viraptor** [comment]
With `NIX_DEBUG` something adjacent seems to break so I don't even get to the LINK stage:
```
../../../../../../nix/store/8d4x83q2l01szzcb4azp2lns0yna0yw8-llvmCcAndBintools/bin/clang++: /nix/store/z6rd8wq02azalrlm2m5k08iy53klg624-bash-5.1-p12/bin/bash: bad interpreter: No such file or directory
```
but:
```
$ ls -la /nix/store/z6rd8wq02azalrlm2m5k08iy53klg624-bash-5.1-p12/bin/bash
-r-xr-xr-x  1 root  nixbld  839536  1 Jan  1970 /nix/store/z6rd8wq02azalrlm2m5k08iy53klg624-bash-5.1-p12/bin/bash
```
trying other things...

**Comment by jsierles** [comment]
Did you figure this one out @viraptor?

**Comment by viraptor** [comment]
No, the last step was getting stuck with bash not visible. I'll post my last patch leading to that point soon in case anyone wants to continue.

**Comment by jsierles** [comment]
Cool, thanks. I'll try it out and go from there.

**Comment by viraptor** [comment]
This was my last attempt - I think that's the one failing with bash. https://github.com/NixOS/nixpkgs/commit/0268ec4108ee1a4467031b150e9289ea71f81e88

I can't remember what was added why by now, so changes like `stdenv = llvmPackages.libcxxStdenv;` may be irrelevant.

`v8_enable_system_instrumentation=false` is definitely needed to work around the original issue of `signpost` not being available.

`llvmCcAndBintools = symlinkJoin...` is for lld/clang not found in the path.

**Comment by YorikSar** [comment]
I found that you can jus add `llvmPackages.llvm` to `nativeBuildInputs` - `llvm-ar` is detected then, no need for wrapping clang and tools together.

**Comment by 06kellyjac** [comment]
Out of interest was a solution to `-fuse-ld=lld` found? or was the plan to just patch it out?

I had a similar issue building deno because they moved aarch64-darwin to use that linker for speed, in the end I just patched it out

https://github.com/denoland/deno/blob/main/.cargo/config#L14

**Comment by yeongsheng-tan** [comment]
@YorikSar noted that v8 at version ‘v8-9.7.106.18’ has been marked broken since 14 May for x86_64-darwin. Latest version that shows a good build is [v8-9.7.106.18](https://search.nixos.org/packages?channel=unstable&show=v8&from=0&size=50&sort=relevance&type=packages&query=v8) !?!?

I have a RoR nix env project that relies on v8 at the above version, and needs to upgrade to ruby_3_1. So I had to perform a `nix flake update` to grab latest flakes. But now I am unable to get my `nix develop` dev shell to boot up with following error:

```Package ‘v8-9.7.106.18’ in /nix/store/8s6h654fj7inibkiikbd2h0hdv6k7ryx-source/pkgs/development/libraries/v8/default.nix:165 is marked as broken, refusing to evaluate.```

Is there any plan for the v8-9.7.106.18 fix soon? I am wondering how I can help to get this moving?

**Comment by viraptor** [comment]
@yeongsheng-tan Not sure if anything improved since my post https://github.com/NixOS/nixpkgs/issues/158076#issuecomment-1056771307

I could not reproduce @YorikSar 's fix on my side, but maybe I'm missing something - a link to a patch/commit would be useful.

The only change since then is that with https://github.com/NixOS/nixpkgs/pull/176661 you don't need to disable the tracing feature if you use `darwin.apple_sdk_11_0.callPackage pkgs/development/libraries/v8 {}`. But otherwise I haven't seen any solution to https://github.com/NixOS/nixpkgs/issues/158076#issuecomment-1036146135

**Comment by viraptor** [comment]
Please test with https://github.com/NixOS/nixpkgs/pull/189222
It builds correctly on Intel, but don't have an M1 to validate.
