### ISSUE TITLE
Self-reference issue in builldGoModule

### ISSUE THREAD

**Issue by diogox** [NixOS/nixpkgs#158158]
Inside a `buildGoModule` derivation, I need to do the following in the `postInstall` phase:

```sh
wrapProgram $out/bin/targetBinary \
  --prefix PATH : "${makeBinPath [ pkgs.go ]}"
```

When trying to build, I get this error: 
```sh
error: output '/nix/store/z6crf0b68h8hsc3hpskpa00486ipc1la-targetBinary' is not allowed to refer to the following paths:
         /nix/store/wpqh40bxac7f8zi9wnywl7cbsmhm3a8w-go
```

From what I can gather, this happens because it's a "self-reference'. `go` being pointed at inside a `buildGoModules` is not allowed.

My question is: Does anyone know how I can fix or workaround this error?

Any help is appreciated!

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/blob/b83fb95b30ed2f1ba4fece780376b0ff3fb3198f/pkgs/development/tools/operator-sdk/default.nix#L23-L27
