### ISSUE TITLE
Request < tauon > package update from 6.7.1 to 7.01

### ISSUE THREAD

**Issue by mannp** [NixOS/nixpkgs#158150]
Hi, hope I have completed the correct fields!

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

[tauon](https://search.nixos.org/packages?channel=unstable&show=tauon&from=0&size=50&sort=relevance&type=packages&query=tauon)
The Linux desktop music player from the future

    Name: tauonVersion: 6.7.1Licenses: [GNU General Public License v3.0](https://spdx.org/licenses/GPL-3.0.html)[Homepage](https://tauonmusicbox.rocks/)[Source](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/tauon/default.nix#L104)

nix-env -iA nixos.tauon

current version: 6.7.1
desired version: 7.0.1

###### Notify maintainers

HI @SuperSandro2000 any update to tauon if you have time, would be greatly appreciated :)

I also do not get a tauon icon showing up in gnome 4.x.x and have to exec from the command line instead...wondered if this was by design :)

**Comment by jansol** [comment]
Tried it out and updated the derivation while at it. I don't think I'll be using this in the long run though, since it seems to have problems with wayland and replaygain inconsistencies between file formats.

**Comment by jansol** [comment]
I guess it doesn't show up in the gnome dashboard because the derivation does not install a desktop file. There seems to be one in the extra/ dir in the upstream repo but that needs some adapting to work on NixOS.

**Comment by mannp** [comment]
Thanks for trying, although it seems to be working fine on one of my arch machings running waylamd?

Don't use replaygain so can't comment.

In what way does the desktop file need adjusting, as, in my experience, the tauon dev has been very receptive and amenable in the past.

**Comment by jansol** [comment]
It mostly works but I have a mixed-DPI setup and running with the X11 backend in Xwayland is notoriously blurry on scaled monitors which is a bit annoying. The native wayland backend in SDL does not have that problem but SDL also does not handle DPI changes in any way so when moving between screens with different scaling factors, first the viewport goes out of sync with window size and once it relayouts itself it does not rescale for the new DPI.

I reported the replaygain issue and that indeed got fixed in a matter of hours.

I usually just fetch and build PRs manually but yes, from a glance at the docs `nixpkgs-review` seems to do all that in one command.

**Comment by mannp** [comment]
Thanks for creating @jansol heads up v7.1 out overnight if you still have the pull out 😁

**Comment by mannp** [comment]
> It mostly works but I have a mixed-DPI setup and running with the X11 backend in Xwayland is notoriously blurry on scaled monitors which is a bit annoying. The native wayland backend in SDL does not have that problem but SDL also does not handle DPI changes in any way so when moving between screens with different scaling factors, first the viewport goes out of sync with window size and once it relayouts itself it does not rescale for the new DPI.
> 
> I reported the replaygain issue and that indeed got fixed in a matter of hours.
> 
> I usually just fetch and build PRs manually but yes, from a glance at the docs `nixpkgs-review` seems to do all that in one command.

v7.1.1 is out @jansol and appears to have some of your requested changes included already ...

**Comment by jansol** [comment]
@mannp It indeed is: #160513

**Comment by mannp** [comment]
Hope the new stuff works 👍
