### ISSUE TITLE
on current version of nixos-unstable, nix-env -i steam fails

### ISSUE THREAD

**Issue by danielbarter** [NixOS/nixpkgs#158145]
### Describe the bug
On current version of nixos-unstable (which went live yesterday or today), `nix-env -i steam` fails with the following error:

```
error: getting status of '/nix/store/4yhkjh0r8p764ahw6dsn9c4afdylsbcv-steam-original-1.0.0.74/share/iconshicolor': No such file or directory
```

it seems that the icons are in the following folder:

```
/nix/store/4yhkjh0r8p764ahw6dsn9c4afdylsbcv-steam-original-1.0.0.74/share/icons/hicolor
```

i.e a `/` is missing. Same issue is happening for chromium. Anyone else seeing this behavior? Probably not an issue in any leaf packages. My guess is maybe something related to gtk?

### Steps To Reproduce
1. run `nix-env -i steam` when channel is set to current version of nixos-unstable.

### Expected behavior
Steam should be installed.

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.94, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos-22.05pre350838.554d2d8aa25"`
 - channels(danielbarter): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by danielbarter** [comment]
yep, that makes sense.

**Comment by andersk** [comment]
Let’s reopen this until the version of Nix in nixpkgs is actually fixed. (And then, ideally, actually fix it. ☺)

**Comment by ncfavier** [comment]
Can we close this, now that nix 2.7.0 is in nixos-unstable?
