### ISSUE TITLE
`zsh-fzf~tab` from Nixpkgs can crash shell

### ISSUE THREAD

**Issue by JustinLovinger** [NixOS/nixpkgs#158120]
### Describe the bug
`zsh-fzf~tab` crashes shell when tab completing a command with more than one group if `zstyle ':completion:*:descriptions' format '%d'` and `zstyle ':fzf-tab:*' group-colors ''` are set.

### Steps To Reproduce
1. Add `programs.zsh.plugins = [ { name = "fzf-tab"; src = "${pkgs.zsh-fzf-tab}/share/fzf-tab"; } ]` in Home Manager.
2. Add
  ```nix
  programs.zsh.initExtra = ''
    zstyle ':completion:*:descriptions' format '%d'
    zstyle ':fzf-tab:*' group-colors '''
  ''
  ```
  in Home Manager.
3. Open shell and type `git <tab>`.

### Expected behavior
`fzf-tab` starts completion.

### Additional context
The crash does **not** occur if the plugin is loaded like
```nix
programs.zsh.plugins = [
  {
    name = "fzf-tab";
    src = pkgs.fetchFromGitHub {
      owner = "Aloxaf";
      repo = "fzf-tab";
      rev = "190500bf1de6a89416e2a74470d3b5cceab102ba";
      sha256 = "1dipsy0s67fr47ig5559bcp1h5yn8rdjshhs8zsq7j8plvvh99qb";
    };
  }
]
```
The crash only occurs when `zsh-fzf-tab` from Nixpkgs is used.

### Notify maintainers

@Vonfry

### Metadata
I just switched to flakes, and I'm not sure of the flake equivalent of `nix-info --run "nix-info -m"`.

**Comment by Vonfry** [comment]
It has been confirmed. It may be cause by the compiled `fzftab.so`.  I need some time to  debug.

**Comment by Vonfry** [comment]
The problem is caused by upstream. I create a vm, kali and bulid the fzftab.so which has the same issue.
