### ISSUE TITLE
I cant use llpp to view a pdf.

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#158197]
### Describe the bug
llpp Pro\ Java\ 7\ NIO.2.pdf 
Fatal error: exception Failure("X connection failed maj=11 min=0 reason=\"No protocol specified\\n\"")

### Steps To Reproduce
1. install llpp
2. llpp xxx.pdf in terminal

### Additional context
no

### Notify maintainers
@pSub 

### Metadata

[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.94, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by iblech** [comment]
Hello prehonor, I'm sorry you're having problems with llpp on Nix. Unfortunately I cannot reproduce the issue. On my machine (nixos-unstable from a couple days ago), llpp works just fine.
