### ISSUE TITLE
tmuxPlugins.tmux-fzf: Outdated and Broken

### ISSUE THREAD

**Issue by AmeerTaweel** [NixOS/nixpkgs#158162]
### Checklist

+ [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
+ [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

### Project name

`nix search` name: `tmuxPlugins.tmux-fzf`

current version:
+ name: `unstable-2020-12-07`
+ rev: `5efeb91086040a3becf5372fb38258acd0579954`

desired version:
+ name: `unstable-2021-10-20`
+ rev: `1801dd525b39154745ea668fb6916035023949e3`

### Notify maintainers

maintainers: @KyleOndy 

### Note for maintainers

+ The current version is broken, it simply does not work. [This error](https://github.com/sainnhe/tmux-fzf/issues/49) happens. And as mentioned in the link, the new version solves that. I tried it out and it's true.
+ Please tag this issue in your PR.

**Comment by KyleOndy** [comment]
I can take a few hours.

**Comment by KyleOndy** [comment]
I am set to watch releases on [`tmux-fzf`](https://github.com/sainnhe/tmux-fzf) but no releases are ever created. I'll find another way to monitor `master` and keep this package upto date.

**Comment by AmeerTaweel** [comment]
> I am set to watch releases on [`tmux-fzf`](https://github.com/sainnhe/tmux-fzf) but no releases are ever created. I'll find another way to monitor `master` and keep this package upto date.

Thanks for that!

And thank for your quick fix.
