### ISSUE TITLE
error when installing php

### ISSUE THREAD

**Issue by dwenaus** [NixOS/nixpkgs#15818]
## Issue description
php does not install. no version in fact. 

### Steps to reproduce
$ nix-env -i php

## Technical details

result:
installing ‘php-7.0.5’
error: Package ‘uw-imap-2007f’ in ‘/nix/store/phqb57liyaqm9jxlawk47y3d97whq2bv-nixpkgs-16.09pre83147.df89584/nixpkgs/pkgs/tools/networking/uwimap/default.nix:39’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

* System: OS X 10.11.4
* Nix version: 1.11.2
* Nixpkgs version: "16.09pre83147.df89584"

**Comment by mpscholten** [comment]
@dwenaus this should be fixed via #16078 :) Could you try it out and report if the issue still exists?

**Comment by cmpadden** [comment]
@mpscholten 

I can confirm that PHP now installs successfully on Darwin.
* System: Darwin 15.5.0 (OS X 10.11.5)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre-git
