### ISSUE TITLE
texlive: mfirstuc not packaged

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#15828]
The `mfirstuc` package is missing in the texlive distribution (https://www.ctan.org/pkg/mfirstuc)

**Comment by matthiasbeyer** [comment]
Pinging texlive maintainers here: @jgeerds @ttuegel @vcunat @peti @jwiegley

**Comment by matthiasbeyer** [comment]
Closing because too old to get addressed IMO.

**Comment by vcunat** [comment]
The package is there actually, called as you'd expect: `texlive.mfirstuc`.

**Comment by vcunat** [comment]
It was so on 16.09 already; I just haven't remembered this ticket.
