### ISSUE TITLE
luaPackages.vicious: Missing Dependencies

### ISSUE THREAD

**Issue by AmeerTaweel** [NixOS/nixpkgs#158245]
### Describe the bug

Vicious is a widget library, and some of its widgets have dependencies on other programs to work. None of these dependencies are specified in the current package definition. Personally, I use the volume widget, which depends on `alsa-utils`. The widget, of course, does not work because `alsa-utils` is not specified as a runtime dependency.

### Steps To Reproduce

1. Add `luaPackages.vicious` as a Lua module for AwesomeWM:<br>`xsession.windowManager.awesome.luaModules = [ pkgs.luaPackages.vicious ]`
2. Try to use the volume widget in your AwesomeWM config.
3. It will not work.

### Expected behavior

The volume widget (and other widgets) should have their dependencies declared, and work properly.

### Notify maintainers

@makefu
@Mic92 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.94, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220124_0a70b37`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by makefu** [comment]
thanks for your bug report, is adding `alsa-utils` to either system or user packages enough for the widget to work properly?

**Comment by AmeerTaweel** [comment]
@makefu before adding `alsa-utils` in my config, the widget did not appear in the first place. Now that I added it, it does appear, which is a step forward. However, I get a `nil` value for the volume.

I'm using the latest NixOS, and there is a problem currently with `amixer`. You can read about the issue [here](https://github.com/NixOS/nixpkgs/pull/157352). The pull request was merged to master, but still did not land in `nixpkgs`, as the merge happened only 3 days ago.

However, I understand that you cannot just add the change without verifying that it works.

I can wait until I get the fix for `amixer`, and test it and notify you.

**Comment by yipengsun** [comment]
I feel `vicious` probably should not include such runtime dependencies. For example, I'm using `vicious` with `pulseaudio`, so if `alsa-utils` is declared a dependency, I'd get a copy of `alsa-utils` which is not very useful to me.

In this case maybe just list `alsa-utils` to your config?

**Comment by AmeerTaweel** [comment]
@yipengsun I was trying to explain why we need to add all the dependencies, but I just noticed that you are a contributor! I cannot believe that a contributor to `nixpkgs` says such a thing.

Also, you don't have to get an extra copy, but even if you do, it's not a big deal, it's not like `alsa-utils` is 3 Gigabytes.

**Comment by yipengsun** [comment]
OK, I guess maybe I should say, `alsa-utils` can be treated as an optional dependency that maybe default to true, and if someone doesn't need it, then he/she can disable that in an overlay.

@AmeerTaweel Is that a reasonable compromise?

**Comment by yipengsun** [comment]
Well, `pulseaudio` actually depends on `alsa-lib`, so I already got my copy of `alsa-utils`. Then I have no more objection, and indeed, `alsa-utils` should be a dependency, not _an optional_ one.

**Comment by yipengsun** [comment]
Question: `vicious` has other "runtime" dependencies like `hddtemp` (that I don't use). How to add it as a dependency such that for users don't use it, they can disable it in an overlay without overriding the whole package?

**Comment by AmeerTaweel** [comment]
@yipengsun I started using Nix/NixOS just two weeks ago, so I have no idea how to write package definitions in such a way that makes them customizable by the user. So I don't know how it's done technically, but I kinda agree with you.

Most users don't use all of the widgets offered by `vicious`, so it makes sense to have all of them available by default, but still being able to turn them off if you want.

**Comment by yipengsun** [comment]
Actually, `toLuaModule` is defined as the following:

```
  toLuaModule = drv:
    drv.overrideAttrs( oldAttrs: {
      # Use passthru in order to prevent rebuilds when possible.
      passthru = (oldAttrs.passthru or {}) // {
        luaModule = lua;
        requiredLuaModules = requiredLuaModules drv.propagatedBuildInputs;
      };
    });
```

So can we extend that to something like:

```
toLuaModule = drv: attrs: ? {} {
  # ...
}
```

So we can optionally override the inputs to `lua` packages themselves?

**Comment by AmeerTaweel** [comment]
> > Most users don't use all of the widgets offered by vicious, so it makes sense to have all of them available by default
> 
> This reasoning isn't sound, it only makes sense if most people use most of the widgets. E.g. cmus and notmuch would be unnecessarily pulled. Since Vicious is a Lua module, build time is marginal, I strongly suggest disabling optional dependencies by default.

Totally makes sense. I also agree.
