### ISSUE TITLE
Can't update nixos to latest nixos-unstable (at least gdm doesn't start)

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#15824]
## Issue description

When updating my system to latest nixos-unstable, I can't reboot. This might be related to recent update from systemd 229 to 230.

### Steps to reproduce

- update nixpkgs to b7c38c7909f6acc4b3de449d419a26aa85eee483 (current channels/nixos-unstable)
- run `sudo nixos-rebuild boot`
- reboot

gdm doesn't start

**Comment by domenkozar** [comment]
Can you post some logs? It's hard to debug without it. @lethalman

**Comment by lethalman** [comment]
I'm having hard times in general with gnome :) sorry for the issues. I'm trying to understand what's wrong overall.

**Comment by lethalman** [comment]
I've built the gnome3-gdm test successfully on master though. I wonder if it's not your own issue?

**Comment by DamienCassou** [comment]
I've tried again and still have the same problem.

@domenkozar `journalctl -xb` doesn't show anything special compared with a working configuration. Anything you want to see in particular?

@lethalman I don't know

**Comment by lethalman** [comment]
I've just booted 2661511 on a virtual machine just fine after an upgrade... weird. Perhaps it's something to do with drivers? Do you have black screen?

**Comment by DamienCassou** [comment]
> Do you have black screen?

tty1 to tt6 are accessible. `Ctrl+Alt+F7` doesn't do anything. When I'm on a tty, I can type some commands, but after a minute or two, I get an error message:

> Welcome to emergency mode! [...] Cannot open access to console, the root account is locked

**Comment by DamienCassou** [comment]
I have the impression the problem was in my `configuration.nix`. I will investigate but I confirm the commit seems to work now:

```
$ nixos-version 
16.09.git.2661511 (Flounder)
```

**Comment by DamienCassou** [comment]
Sorry for the noise

**Comment by lethalman** [comment]
@DamienCassou what was the problem?

**Comment by DamienCassou** [comment]
@lethalman This code that I added to my `configuration.nix` and never tried:

```nix
{
  fileSystems."/media/cassou/sanyen-damien" =
    { device = "/dev/mapper/sanyen-damien";
      fsType = "ext4";
      options = ["uid=1000"];
    };
}
```

I guess it broke my system because `/dev/mapper/sanyen-damien` belongs to an USB HDD which was not plugged in.
