### ISSUE TITLE
Package request: emptty

### ISSUE THREAD

**Issue by StarrFox** [NixOS/nixpkgs#158258]
**Project description**

A simple to use cli display manager

**Metadata**

* source URL: https://github.com/tvrzna/emptty
* license: MIT
* platforms: linux

**Comment by jonringer** [comment]
I got a video on adding a package to nixpgks here: https://www.youtube.com/watch?v=fvj8H5yUKu8&t=28s

Go applications are generally easy to add

**Comment by a-vorobiev** [comment]
Is that free for grabs? I'ld like to start contributing to NixOS, this one looks pretty straightforward to start with.

**Comment by das-g** [comment]
> Is that free for grabs?

Seems so.

> I'ld like to start contributing to NixOS, this one looks pretty straightforward to start with.

:+1::rocket:

Shall I assign the issue to you?

**Comment by a-vorobiev** [comment]
> Shall I assign the issue to you?

Yes, please.
