### ISSUE TITLE
python: Why is `-lncurses` added to `LIBS` in `python3-config`?

### ISSUE THREAD

**Issue by panicgh** [NixOS/nixpkgs#158256]
### Question
Why is `-lncurses` added to `python3-config` on Nix/NixOS but missing on other Linux distributions?

NixOS 21.11 gives

```console
$ python3-config --libs
 -lpthread -ldl -lcrypt -lncurses -lutil -lm -lm 
```

while, for example, on plain Debian 11 (which I believe comes with ncurses [support](https://deb.debian.org/debian/pool/main/p/python3.9/python3.9_3.9.2-1.dsc)) it is:

```console
$ sudo apt install python3-dev
$ python3-config --libs
 -lcrypt -lpthread -ldl  -lutil -lm -lm
```

It seems to be caused by [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/cpython/default.nix#L287), but why is it done this way? (Locally, I removed the `optionalString` for ncurses and rebuilt python3, and indeed ncurses is removed from `python3-config --libs` output)

```nix
{
# ...
  CPPFLAGS = concatStringsSep " " (map (p: "-I${getDev p}/include") buildInputs);
  LDFLAGS = concatStringsSep " " (map (p: "-L${getLib p}/lib") buildInputs);
  LIBS = "${optionalString (!stdenv.isDarwin) "-lcrypt"} ${optionalString (ncurses != null) "-lncurses"}";
#                                                        \-------------------- why? -------------------/
}
```

`CPPFLAGS` and `LDFLAGS` are generated out of the `buildInputs`, but `LIBS` is not.
Note `ncurses` is [conditionally added](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/cpython/default.nix#L119-L120) to `buildInputs`, so shouldn't the configure script detect ncurses link flags on its own?

### Notify maintainers

Last edit in efbe87f3ef76 (2018) by @FRidh, but it seems to have first appeared in 27de56316 (2012, Python 3.2.3).

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.95, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.335733.f6ddd55d5f9"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by veprbl** [comment]
Can't reproduce, at least on Debian 10:

```
# nix-shell -I nixpkgs=channel:nixpkgs-unstable -p python3 --pure --run 'python3-config --libs'
 -lpthread -ldl -lcrypt -lncurses -lutil -lm -lm 
```

**Comment by panicgh** [comment]
Sorry, if what I wrote was misleading. I didn't mean Nix on Debian, but plain Debian:

```console
$ sudo apt install python3-dev
$ python3-config --libs
 -lcrypt -lpthread -ldl  -lutil -lm -lm 
```

**Comment by panicgh** [comment]
I'm still interested into why Nix/NixOS require `-lncurses` but not other Linux distros.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/164524 is in staging
