### ISSUE TITLE
Please update pyasn1

### ISSUE THREAD

**Issue by SmilingHorse** [NixOS/nixpkgs#15823]
Both [pyasn1](https://sourceforge.net/projects/pyasn1/files/pyasn1/0.1.9/) and [pyasn1-modules](https://sourceforge.net/projects/pyasn1/files/pyasn1-modules/0.0.8/) could really use updating.

Tarballs' change-logs:
http://pyasn1.cvs.sourceforge.net/viewvc/pyasn1/pyasn1/CHANGES.txt?revision=1.149&view=markup
http://pyasn1.cvs.sourceforge.net/viewvc/pyasn1/pyasn1-modules/CHANGES.txt?revision=1.32&view=markup

Though you may want to pull from the recent heads since some touch-ups were made 3 month later:
http://pyasn1.cvs.sourceforge.net/viewvc/pyasn1/pyasn1/CHANGES.txt?revision=1.152&view=markup
http://pyasn1.cvs.sourceforge.net/viewvc/pyasn1/pyasn1-modules/CHANGES.txt?revision=1.34&view=markup

**Comment by fpletz** [comment]
Is this for 16.03? In master, we have the current versions of pyasn1 and pyasn1-modules.

**Comment by SmilingHorse** [comment]
Yes it's for 16.03. The module development has mostly met specs half a year ago and has only been seeing bug fixes and minor improvements and the likes since then. So, I was hoping 16.03 could at least stick to the latest tarballs and possibly the heads since [they're mostly the same](http://pyasn1.cvs.sourceforge.net/viewvc/pyasn1/pyasn1-modules/setup.py?view=diff&r1=text&tr1=1.17&r2=text&tr2=1.19&diff_format=h).

**Comment by domenkozar** [comment]
16.03 is not supported anymore and we have latest versions in nixpkgs.
