### ISSUE TITLE
Request to add JanusGraph package

### ISSUE THREAD

**Issue by Givemeurcookies** [NixOS/nixpkgs#158371]
**Project description**
JanusGraph is a distributed, open source, massively scalable graph database. JanusGraph is a scalable graph database optimized for storing and querying graphs containing hundreds of billions of vertices and edges distributed across a multi-machine cluster.

JanusGraph is a project under The Linux Foundation, and includes participants from Expero, Google, GRAKN.AI, Hortonworks, IBM and Amazon.

JanusGraph is capable of both OLAP and OLTP. JanusGraph is one of the most major open source graph databases which has support for Apache Tinkerpop Gremlin.

Currently JanusGraph supports several types of backend storage databases such as Apache Cassandra, Apache HBase, Google Cloud BigTable, Oracle Berkley DB and ScyllaDB. It also has support for advanced full-text search that can optionally be enabled the following indexing databases: ElasticSearch, Apache Solr and Apache Lucene.

**Metadata**

* homepage URL: https://janusgraph.org/
* source URL: https://github.com/JanusGraph/janusgraph
* license: APACHE LICENSE, VERSION 2.0
* platforms: Support for unix, linux, darwin and windows

**Comment by Givemeurcookies** [comment]
Hopefully someone can bring this to fruition. I am fairly new to Nix and I am still learning how to create packages. JanusGraph is based upon JVM so I believe the implementation would be fairly similar to how Apache Cassandra has been implemented as a Nix package.

**Comment by ners** [comment]
I've added JanusGraph with this PR: https://github.com/NixOS/nixpkgs/pull/192649/

**Comment by jlesquembre** [comment]
Closing since JanusGraph was added to nixpkgs.
