### ISSUE TITLE
remmina: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#15835]
## Issue description
```
$ remmina 
/run/current-system/sw/bin/remmina: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

## Technical details

* System: 16.09pre84456.b7c38c7 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre84456.b7c38c7

**Comment by gebner** [comment]
This is already fixed in ad94726f9e35d8a2c48b4f2709ee2b2a2d93575b.
