### ISSUE TITLE
`nixos-unstable` `linux-pam` broken

### ISSUE THREAD

**Issue by psydvl** [NixOS/nixpkgs#158322]
### Describe the bug
`nixos-unstable` broken for me
I've tried `git bisect` problem and it shows brake somewhere between _good_ https://github.com/NixOS/nixpkgs/commit/075b606ef9b10e7bbe4e6d3dd21cf4f171c27e5c and _bad_ https://github.com/NixOS/nixpkgs/commit/efeefb2af1469a5d1f0ae7ca8f0dfd9bb87d5cfb

https://github.com/NixOS/nixpkgs/commit/c3805ba16cf4a060cdbb82d4ce21b74f9989dbb8 seems like probable reason, but it's way older than https://github.com/NixOS/nixpkgs/commit/075b606ef9b10e7bbe4e6d3dd21cf4f171c27e5c
But probably problem start appears on packages without prebuild cache and lately moved to cache, but I'm not sure

I've stop bisecting because for those commits there are no cached prebuild packages, and, for me, it takes too long time to build from scratch.

```
$ sudo nixos-rebuild boot --show-trace
building the system configuration...
error: builder for '/nix/store/f0971la3a54f74g4284cfrin5sl9imxy-ensure-all-wrappers-paths-exist.drv' failed with exit code 1;
       last 4 log lines:
       > Checking that Nix store paths of all wrapped programs exist... FAIL
       > The path /nix/store/g55rkqdbnq1rfmfcg2ldp29m55answ31-linux-pam-1.5.1/sbin/unix_chkpwd.orig does not exist!
       > Please, check the value of `security.wrappers."unix_chkpwd".source`.
       > 
       For full logs, run 'nix log /nix/store/f0971la3a54f74g4284cfrin5sl9imxy-ensure-all-wrappers-paths-exist.drv'.
error: 1 dependencies of derivation '/nix/store/5kwv6bv2xyh5vsfgn4hc9wz28hk4h454-nixos-system-nixos-21.11.20220130.0f316e4.drv' failed to build

$ ls /nix/store/g55rkqdbnq1rfmfcg2ldp29m55answ31-linux-pam-1.5.1/sbin/
faillock  mkhomedir_helper  pam_namespace_helper  pam_timestamp_check  pwhistory_helper  unix_chkpwd  unix_update
```

### Steps To Reproduce

0. Probably, any configuration, but [here](https://github.com/psydvl/nixos/tree/8a15b2e88b68bc936771642d9ed1b3d0711149e2) is mine if it's needed 
1. Use latest nixos-unstable
2. `nixos-rebuild boot`

### Expected behavior
Successful build

### Notify maintainers
According to log, `linux-pam` and `ensure-all-wrappers-paths-exist` are affected
[`linux-pam`](https://github.com/NixOS/nixpkgs/blob/efeefb2af1469a5d1f0ae7ca8f0dfd9bb87d5cfb/pkgs/os-specific/linux/pam/default.nix) last contributor: @winterqt 
[`ensure-all-wrappers-paths-exist`](https://github.com/NixOS/nixpkgs/blob/efeefb2af1469a5d1f0ae7ca8f0dfd9bb87d5cfb/nixos/modules/security/wrappers/wrapper.nix) all contributors: @Mic92 @cole-h 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `"nixos-21.11.334797.6979c0e49bb, nixos-unstable-22.05pre340469.cb372c3b888"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by winterqt** [comment]
Your configuration is mixing the modules from 21.11 with the packages from unstable, so the pam module from 21.11 won't find `unix_chkpwd.orig` in the linux-pam package from unstable.

**Comment by psydvl** [comment]
Yes, you are right!
Sorry about this
