### ISSUE TITLE
docker fails due to storage driver (ZFS with Zen Kernel)

### ISSUE THREAD

**Issue by ymarkus** [NixOS/nixpkgs#158459]
### Describe the bug
My system: zfs filesystem with zen kernel.
Since my last flake update (I didn't update for a few weeks), `docker.service` fails with this error:
```
level=error msg="[graphdriver] prior storage driver devicemapper failed: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed"
```
So it looks like docker is using devicemapper. If I set `virtualisation.docker.storageDriver = "zfs"`, it works properly.
Maybe this is a docker bug, but it worked before so I thought maybe first open an issue here.

### Steps To Reproduce
1. have zfs filesystem
2. set `virtualisation.docker.enable = true`
3. watch docker.service fail

### Notify maintainers
I'm really not sure who to ping here, as I don't really know if it might be the kernel missing something...
But for docker, I'll just ping:
@offline @tailhook @vdemeester @periklis @mikroskeem @maxeaubrey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.3-zen1, NixOS, 22.05 (Quokka)`
```

**Comment by mikroskeem** [comment]
IIRC upstream has never picked ZFS storage driver out of the box, even if ZFS is being used.

**Comment by ymarkus** [comment]
Hm, weird. It definitely worked fine before... Got any idea why it might have broken?

**Comment by mikroskeem** [comment]
Unable to reproduce. ZFS dataset set up on `/var/lib/docker` and Docker picks it up on its own (surprisingly).

```shell
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.0, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.1`
 - channels(root): `""`
 - channels(mark): `"nixpkgs-22.05pre336446.fe3e7ef66c3"`
 - nixpkgs: `/home/mark/.nix-defexpr/channels/nixpkgs`
 ```

**Comment by drperceptron** [comment]
I encountered the same error message when doing something like `docker load --input $(nix-build)`. Fixed it as per https://github.com/docker/for-linux/issues/46#issuecomment-583949616:
```bash
systemctl stop docker
thin_check --clear-needs-check-flag /var/lib/docker/devicemapper/devicemapper/metadata
thin_check /var/lib/docker/devicemapper/devicemapper/metadata
systemctl start docker
```
I believe it has something to do with low/no disk space.

**Comment by ymarkus** [comment]
Ok, for some reason I think my /var/lib/docker was corrupted. After simply rm-ing it, it works fine now. It was my development machine so no data to lose anyway. All my other machines never had this issue.

**Comment by ymarkus** [comment]
@drperceptron might have been your issue, thanks for having a look!
