### ISSUE TITLE
python3.pkgs.mailman is not a Python module

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#158424]
`python3.pkgs.mailman` is not a Python module and `python310.pkgs.mailman` actually uses Python 3.9!???
It can also not be added to `python3Packages` with the correct Python version cause it overrides sqlalchemy.
Thus mailman and the packages depending on it need to be removed from `python-packages.nix`.
cc @mweinelt @jonringer

**Comment by jonringer** [comment]
agreed

**Comment by FRidh** [comment]
cc @lheckemann
