### ISSUE TITLE
Mutable users vs authorizedKeysFiles

### ISSUE THREAD

**Issue by ip1981** [NixOS/nixpkgs#15841]
I have a feeling that with `users.mutableUsers = false;`
we should also deny user-uploaded SSH keys:

``` nix
{
# ...
services.openssh.authorizedKeysFiles
  = [ "/etc/ssh/authorized_keys.d/%u" "/root/.ssh/authorized_keys" ]
 ++ lib.optionals users.mutableUsers
    [ ".ssh/authorized_keys" ".ssh/authorized_keys2" ];
#...
}
```

There are security concerns: someone could upload a new SSH key, and we will never know.

**Comment by Profpatsch** [comment]
Has this been fixed? If not, would you be willing to prepare a pull request? I can help if you have any questions.

**Comment by ip1981** [comment]
https://github.com/NixOS/nixpkgs/pull/42526

**Comment by Profpatsch** [comment]
Awesome, thanks.
