### ISSUE TITLE
Update phantomjs to 2.1.1?

### ISSUE THREAD

**Issue by NicolasPetton** [NixOS/nixpkgs#15858]
## Issue description

Many npm packages now depend on [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) which will try to install phantomjs `2.1.1` (from the [official GitHub repository](https://github.com/ariya/phantomjs/)).

Since Nixos has issues running the prebuilt version of phantomjs, it would be nice to update phantomjs to 2.1.1.

/cc @aflatter

**Comment by joachifm** [comment]
Looks like this was fixed by 94036474c2b424ac19c4e8e30b5b026210649789, please re-open if that's not the case.
