### ISSUE TITLE
Bad UX: extraPostFetch vs postFetch

### ISSUE THREAD

**Issue by Radvendii** [NixOS/nixpkgs#158629]
Most fetchers have a `postFetch` attribute that runs code after the fetch occurs. Meanwhile, `fetchzip` already sets `postFetch`, and so it exposes `extraPostFetch` if you want to add something on after.

This is inconsistent UX in general, but the bigger problem is that `fetchFromGitHub` sometimes uses `fetchGit` and sometimes `fetchZip`, depending on the options you provide. This means that someone could write a `fetchFromGitHub` using `extraPostFetch`, and then come along and add a `fetchSubmodules = true;`, and all of a sudden it breaks, because now it's expecting `postFetch` instead. This seems really bad to me.

### Notify maintainers
not sure who to @ since the `fetch`ers don't have maintainers listed.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/173430
