### ISSUE TITLE
Request for Godot Engine nix build recipe

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#158628]
## Issue description
I'm requesting a recipe to build a Godot Engine project (vanilla without any gdnative) in the format of `default.nix`. I'm sorry if I'm not on the right channel to ask for this.

## Technical details

Right now, although Godot Engine and its template does exist in nixpkgs, I still have no idea how to use the template. As far as I've seen, people would only use Godot + Nix only for setting up their dev environments.

For added context, my recipe for default.nix is as follows,

```nix
{
  # Enable support for OpenGL/Vulkan for your drivers
  nixgl ? import (fetchTarball "https://github.com/guibou/nixGL/archive/7d6bc1b21316bab6cf4a6520c2639a11c25a220e.tar.gz") { }
, # Pin the version of the nix package repository
  pkgs ? import (fetchTarball "https://github.com/nixos/nixpkgs/archive/a2968d985bf46d046f67e33c313e61d310d0885a.tar.gz") { }
}:
pkgs.stdenv.mkDerivation {
  name = "competitive-fps";

  buildInputs = [
    # Godot Engine Editor
    pkgs.godot

    # The support for OpenGL/Vulkan
    nixgl.nixGLDefault
  ];

  # Alias the godot engine to use nixGL
  shellHook = ''
    alias godot="nixGL godot -e"
  '';
}
```

**Comment by tengkuizdihar** [comment]
Yeah I found the recipe by copying what's on https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/oh-my-git/default.nix. I think this could be documented better, but I have no idea where to put it.

**Comment by veprbl** [comment]
@tengkuizdihar The https://nixos.wiki/ might be the right place.
