### ISSUE TITLE
Error on changing kernel from vanilla to zen

### ISSUE THREAD

**Issue by macalimlim** [NixOS/nixpkgs#158604]
### Describe the bug
I'm trying to change my kernel package from vanilla to zen

### Steps To Reproduce
1. In configuration.nix
```nix
  boot.kernelPackages = pkgs.linuxKernel.kernels.linux_zen;
```
2. with root
```console
# nixos-rebuild boot
```

### Expected behavior
It should rebuild without worries. Next time I boot up, I should be using the zen kernel already (by running neofetch)

### Screenshots

![zen-kernel-rebuild-error](https://user-images.githubusercontent.com/5382992/152983265-469a8a32-31fa-439e-bbf7-024149d88b6e.png)

### Additional context
I also tried it with lqx and xanmod kernels, same error happened.

### Notify maintainers
@Atemu 
@andresilva 

### Metadata
```console
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.96, NixOS, 21.11 (Porcupine)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335820.521e4d7d13b, nixos-hardware, nixos-unstable-22.05pre351891.fbd030fb2d8"`
 - nixpkgs: `/etc/.nixpkgs`
```

**Comment by andresilva** [comment]
`kernelPackages` is for setting the kernel package **set** that should be used, so you should set it using `boot.kernelPackages = pkgs.linuxPackages_zen;`. Feel free to reopen if it doesn't solve your problem.
