### ISSUE TITLE
macOS sshfs Library not loaded libfuse.2.dylib

### ISSUE THREAD

**Issue by nasyxx** [NixOS/nixpkgs#158673]
### Steps To Reproduce
1. `nix-shell -p sshfs --run "sshfs --help"`

### Expected behavior
Show sshfs help info.

### Screenshots
<img width="1047" alt="Screen Shot 2022-02-08 at 00 08 21 PM" src="https://user-images.githubusercontent.com/5007613/153049142-89dc795c-e093-43a0-a382-498a40af501f.png">

### Additional context
I can make sure that macfuse now uses `libfuse.tbd` instead of `libfuse.dylib`.
<img width="266" alt="Screen Shot 2022-02-08 at 00 09 18 PM" src="https://user-images.githubusercontent.com/5007613/153049316-8a3d0ee5-2ddd-4127-92db-61a19fa12f7e.png">

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(Nasy): `"darwin, home-manager, nixpkgs-22.05pre351617.942b0817e89"`
 - channels(root): `"darwin, home-manager, nixpkgs-22.05pre351617.942b0817e89"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by smaret** [comment]
I can't reproduce this on `x86_64-darwin`.

**Comment by mikroskeem** [comment]
Unable to reproduce on `aarch64-darwin` with [macFUSE 4.2.4](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.2.4) installed.

**Comment by nasyxx** [comment]
Thanks!
