### ISSUE TITLE
Can't run docker with aufs storage driver

### ISSUE THREAD

**Issue by qrilka** [NixOS/nixpkgs#15879]
## Issue description

It appears that docker has a special handling of `zfs` for docker https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/docker.nix#L98 but it seems that there is nothing like that for AUFS support but it looks to be needed
### Steps to reproduce
1. Install docker with

```
virtualisation.docker.storageDriver = "aufs";
```
1. Start Docker
2. See Docker failing to start with

```
msg="Error starting daemon: error initializing graphdriver: driver not supported"
```

in the log
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ nixos-version
16.09pre84513.2661511 (Flounder)
```
- Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.2
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre84513.2661511"
```

I have found AUFS referenced at https://github.com/NixOS/nixpkgs/blob/fb23979833fa6885c939b3c9c9148219f2408040/doc/package-notes.xml#L130 but nothing about it in `all-packages.nix`

**Comment by qrilka** [comment]
The same seems to be applicable for OverlayFS - I see patch for OverlayFS but no option to enable it in the kernel :-\

**Comment by Profpatsch** [comment]
triage: still a problem?

**Comment by qrilka** [comment]
Sorry didn't have a chance to recheck yet - hope to do that in a couple of days or so

**Comment by qrilka** [comment]
It appears that at least for `overlay2` and `devicemapper` everything works OK
