### ISSUE TITLE
Virtualbox broken with latest kernel on NixOS 16.03

### ISSUE THREAD

**Issue by jgeerds** [NixOS/nixpkgs#15877]
## Issue description
[Virtualbox is broken](https://hydra.nixos.org/job/nixos/release-16.03/nixpkgs.linuxPackages_latest.virtualbox.x86_64-linux) for `NixOS 16.03` if running latest Linux kernel with `linuxPackages_latest`. Would it be possible to bump the Version in 16.03?

### Steps to reproduce
1) Choose `linuxPackages_latest` (4.6 series)
2) Set `virtualisation.virtualbox.host.enable = true`

## Technical details

* System: (NixOS: `16.03`)
* Nix version: (run `nix-env (Nix) 1.11.2`)
* Nixpkgs version: (run `"16.03.886.0068260"`)

**Comment by domenkozar** [comment]
@jgeerds sure, open a PR with a minor bump if there's one.

**Comment by FRidh** [comment]
see #15896

**Comment by jgeerds** [comment]
That was quick. I'm still testing to reproduce the build error on my machine (takes long time to build Virtualbox). I cherry picked two commits from the master branch to bump it to 5.0.20

**Comment by grahamc** [comment]
I skipped trying to cherry-pick because of how much seemed necessary to pick. I went straight to the update, and it compiled just fine.

**Comment by bjornfor** [comment]
Should be fixed now (76ebea5f534b7a3cf4fab61d6d8cb4c3acae4080).
