### ISSUE TITLE
Create patched versions of python packaging tools to avoid version checks

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#158892]
### Describe the bug
Versioning within python is usually a determinate to us. Should we just modify the main packaging packages to allow for a `--skip-version-check` option?

cc @FRidh @mweinelt @fabaff @dotlambda

**Comment by FRidh** [comment]
I don't understand quite what you mean here. Do you want that `buildPython*` has an option to disable version checks altogether? Or should it be able to ignore just constraints related to a specific package? `pip` already supports this when building a wheel, and so does `build` https://github.com/NixOS/nixpkgs/pull/105714.

**Comment by jonringer** [comment]
> Do you want that `buildPython*` has an option to disable version checks altogether?

I would like for that to be the default, as there a lot of patching done as it's not expect to explicitly disable it.

> pip already supports this when building a wheel, and so does build https://github.com/NixOS/nixpkgs/pull/105714.

Sure, but setuptools and other pep517 tools also do their own version checking. I was referring to these. and making pip always disabled by default.

**Comment by jonringer** [comment]
`pythonRelaxDepsHook` now exists. No longer relevant
