### ISSUE TITLE
Matplotlib Qt backend does not work on Wayland

### ISSUE THREAD

**Issue by jbuchermn** [NixOS/nixpkgs#158806]
### Describe the bug
Cannot start the Qt backend on matplotlib on Wayland. The following errors are thrown:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
```

Probably qtwayland (and also something like qtxcb?) is missing as a dependency. See https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/vlc/default.nix which had the same issue.

### Steps To Reproduce
1. Install matplotlib using `matplotlib = super.matplotlib.override { enableQt = true; };`
2. Try simple plot script `python3 -c "import matplotlib.pyplot as plt; plt.figure()"`

### Expected behavior
Plotting works on Qt natively on Wayland

### Screenshots
-

### Additional context
-
### Notify maintainers
@lovek323 @veprbl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.95, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rnhmjoj** [comment]
It has never been fixed, so yes, sadly.

**Comment by rnhmjoj** [comment]
No, the problem is there is currently no way to propagate variables from python packages to the interpreter wrapper.

A quick solution was https://github.com/NixOS/nixpkgs/pull/83321, but it was scrapped by @FRidh who later proposed https://github.com/NixOS/nixpkgs/pull/102949, now stalled.

Basically everything is waiting for a unified `makeWrapper` interface, which is never coming for some reason.

**Comment by veprbl** [comment]
I was thinking about implementing https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh in python and putting it in the pyqt5 module. This would act only for use of pyqt5 as a library in a development environment. The applications would need to be wrapped to "freeze" the paths.

**Comment by veprbl** [comment]
Could we plug the `QT_PLUGIN_PATH` setting into `qtbase` as a setup-hook?

**Comment by jbuchermn** [comment]
> If you want to use the Qt backend, for now, the only way is this workaround: [#80147 (comment)](https://github.com/NixOS/nixpkgs/issues/80147#issuecomment-784857897)

Thanks a lot, this works and I realize that this issue is a duplicate of #80147. For anyone stumbling upon this: Additionally to the comment one needs to add `qt5.qtwayland` as a `buildInput`.

Do you want me to close this issue, or do you want to continue the conversation here?

**Comment by FRidh** [comment]
Let's use https://github.com/NixOS/nixpkgs/issues/80147.
