### ISSUE TITLE
KWinFT: a kwin fork focused on performance, maintance, wayland/wlroots

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#158827]
**Project description**

>KWinFT (KWin Fast Track) is a robust, fast and versatile yet
easy to use composited window manager for the
[Wayland](https://wayland.freedesktop.org/) and
[X11](https://en.wikipedia.org/wiki/X_Window_System)
windowing systems on Linux.

>KWinFT is intended to be used as part of a
[KDE Plasma Desktop](https://kde.org/plasma-desktop/).
The [KWin](https://en.wikipedia.org/wiki/KWin)FT project is a reboot of KDE's
KWin.
KWinFT differentates itself from KWin in some important aspects:

>KWinFT values stability and robustness.
>This is achieved through upholding strict development standards
and deploying modern development methods to prevent regressions and code smell.
KWinFT values collaboration with competitors and and upstream partners.
>We want to overcome antiquated notions on community divisions
and work together on the best possible Linux graphics platform.
KWinFT values the knowledge of experts but also the curiosity of beginners.
Well defined and transparent decision processes enable expert knowledge to proliferate
and new contributors to easily find help on their first steps.

>In the last year our development focus for KWinFT was on the integration with the [wlroots library](https://gitlab.freedesktop.org/wlroots). In a single sentence our goal with this is to share underlying architecture, patterns and ideas across the Wayland ecosystem, instead of reimplementing things again and again for each and every big project while leaving smaller ones behind.

**Metadata**

recent release blog post with lots of info: https://subdiff.org/blog/2022/more-wlroots-with-kwinft-524/

* homepage URL: https://gitlab.com/kwinft/kwinft
* source URL: https://gitlab.com/kwinft/kwinft
* license: gpl2
* platforms: linux

**Comment by LunNova** [comment]
@cidkidnix was working on an overlay for this and might have some input.

**Comment by InternetUnexplorer** [comment]
I made some progress packaging it in https://github.com/InternetUnexplorer/kwinft-overlay, but it's not working yet unfortunately. At a minimum, I still need to copy [this patch](https://github.com/NixOS/nixpkgs/blob/7606968ba40a1457681716814a0d707f063f8269/pkgs/desktops/plasma-5/kwin/0001-NixOS-Unwrap-executable-name-for-.desktop-search.patch) and figure out why [this is needed](https://github.com/InternetUnexplorer/kwinft-overlay/blob/5d165dd5dbe0e8ff2a12e523dea233d4ea2c8be5/kwinft/default.nix#L30-L31) (maybe a bug in upstream?). The overlay itself might also be done incorrectly. Anyway, while I don't have the time/energy to get it working right now, feel free to use any of the stuff there if you want to try!
