### ISSUE TITLE
Obsidian depends on an electron version that is EOL

### ISSUE THREAD

**Issue by MasseR** [NixOS/nixpkgs#158956]
### Describe the bug
The obsidian tool is dependent on Electron 13.6.9 which is now [end of support](https://www.electronjs.org/releases/stable#end-of-support-for-13xy-1700).

### Steps To Reproduce
1. `NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:NixOS/nixpkgs/nixos-unstable#obsidian`

### Expected behavior

To get the package built.

### Screenshots

```
error: Package ‘electron-13.6.9’ in /nix/store/zwbw7dknw89ai257hicmwv8lhid3qb62-source/pkgs/development/tools/electron/generic.nix:26 is marked as insecure, refusing to evaluate.


       Known issues:
        - Electron version 13.6.9 is EOL

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) for `nixos-rebuild` you can add ‘electron-13.6.9’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "electron-13.6.9"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘electron-13.6.9’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "electron-13.6.9"
              ];
            }
(use '--show-trace' to show detailed location information)
```

### Notify maintainers

@ConradMearns @zaninime 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `""`
 - nixpkgs: `/nix/store/iy1bglqpc4rhbxf53m3ig0jd61w4qpcq-source`
```

**Comment by sersorrel** [comment]
unfortunately this appears to be the case in the official packages too; `process.versions.electron` in the devtools of the appimage for 0.13.23 is `13.6.2`.

there's a pre-release, [0.13.24](https://github.com/obsidianmd/obsidian-releases/releases/tag/v0.13.24), on github, which ships with electron 16.0.8, so presumably this can be fixed once that's released. it would be ideal if that could be backported to 21.11 – there's one breaking change I can see in the release notes (in 0.13.8, "Breaking change: the `data-task` css class has been moved to the line element, rather than being on each piece of `<span>`."), and maybe one other potentially-breaking change (0.13.17, "Heads up to theme developers: the `.list-bullet` CSS has been reworked. It will now keep the original character and superimpose the dot using the `:after` pseudo-element."), but otherwise the version of obsidian in stable nixpkgs will depend on an EOL electron until 22.05 releases.

**Comment by psydvl** [comment]
Just replace with electron_14 in overlay and all works fine, so far

**Comment by zaninime** [comment]
Backporting won't be a problem. Let's wait until the official release.

**Comment by jyooru** [comment]
Fixed in #160469

**Comment by sersorrel** [comment]
any chance of a backport to 21.11? (I can do it, but will be at least a few days before I have enough free time to get around to it)

**Comment by zaninime** [comment]
@sersorrel done. PR is waiting for some reviews. https://github.com/NixOS/nixpkgs/pull/164026

**Comment by umeat** [comment]
I'm now getting the same thing, but it's mentioning ‘electron-21.4.0’.

**Comment by sersorrel** [comment]
[apparently](https://forum.obsidian.md/t/cannot-move-rearrange-panes-when-running-under-wayland/42377/29):

> Obsidian 1.2.6 will ship with a new installer (electron 24).

1.2.6 was released to insiders four days ago (26th April).

**Comment by sersorrel** [comment]
...aaaaand obsidian 1.2.7 is now publicly available with electron 24; ~~whenever #229495 is merged this issue will go away~~ this was already fixed by #226591, it just didn't get backported to stable. (since 23.05 release is still several weeks away I don't know if it makes sense to backport?)

**Comment by idealo-ricardo-band** [comment]
Same situation again. `obsidian-1.4.16` depends on `electron-25.9.0` which is EOL. Would be nice if obsidian devs could get their shit together and update their dependencies earlier. :(

**Comment by XenGi** [comment]
Same situation again. `obsidian-1.4.16` depends on `electron-25.9.0` which is EOL. Would be nice if obsidian devs could get their shit together and update their dependencies earlier. :(
