### ISSUE TITLE
Support for vmTools with custom NIX_STORE_DIR

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#15908]
When running nix on a custom `NIX_STORE_DIR` (not `/nix`) without root access, it was found that using vmTools (qemu) was a decent alternative to workaround lack of isolation that caused some packages to fail. At the time of writing, this is true for `gnum4` on CentOS 6.5 systems where compilation succeeds but the build fails due to 4 failing tests. This has already been [fixed upstream  by disabling tests entirely for this particular package](https://github.com/NixOS/nixpkgs/commit/bb9fa90dca09fc02f5bdd0548c3e7d156b02da80).

In any case, running: `nix-build -E 'with import <nixpkgs> {}; vmTools.runInLinuxVM gnum4'` failed at several points due to hardcoded `/nix/store` entries in vmTools ([1,](https://github.com/NixOS/nixpkgs/blob/81eceb14befc1ba2cb096410e1287ada41246635/pkgs/build-support/vm/default.nix#L221) [2,](https://github.com/NixOS/nixpkgs/blob/81eceb14befc1ba2cb096410e1287ada41246635/pkgs/build-support/vm/default.nix#L174) [3](https://github.com/NixOS/nixpkgs/blob/81eceb14befc1ba2cb096410e1287ada41246635/pkgs/build-support/vm/default.nix#L130)) and possibly other locations in [vm/default.nix](https://github.com/NixOS/nixpkgs/blob/81eceb14befc1ba2cb096410e1287ada41246635/pkgs/build-support/vm/default.nix).

With that said, would it be possible to avoid these hardcoded paths and instead use the overrides provided by the user? Be it via `NIX_STORE_DIR` and `NIX_STATE_DIR` or `~/.nixpkgs/config.nix`.

**Comment by kevincox** [comment]
Would you be able to submit a patch? Most people don't have an alternative path for their nix store so finding someone to help you might be hard.

The fix should be fairly simple, just changing `/nix/store` with the proper variable. However I can't seem to find this available in the nixpkgs scripts. Maybe worth asking in nix-dev.

**Comment by Profpatsch** [comment]
Closing because stagnated.
