### ISSUE TITLE
NixOS: pam_systemd: Failed to connect to system bus

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#15911]
## Issue description

On a freshly installed system I'm constantly thrown out of my session and presented with emergency mode.
```
pam_systemd(login:session): Failed to connect to system bus: Connection refused
```
A `nixos-rebuild switch` is not possible. 

I have the issue with both 16.03 and unstable. Possibly relevant is that I'm using gummiboot.

**Comment by abbradar** [comment]
Recent similar issue: https://github.com/NixOS/nixpkgs/issues/15824. May be non-related to your case, though...

**Comment by FRidh** [comment]
It's indeed very similar. Turned out my boot filesystem was incorrect, so it wouldn't mount it during startup. When I fixed that, the issue disappeared.
