### ISSUE TITLE
ghc-mod-5.5.0.0 does not build with unstable

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#15922]
## Issue description

`ghc-mod-5.5.0.0` fails to build on unstable NixOS:

```
# nixos-rebuild switch
[...]
setting SOURCE_DATE_EPOCH to timestamp 1453233483 of file ghc-mod-5.5.0.0/Setup.hs
patching sources
Run jailbreak-cabal to lift version restrictions on build inputs.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-ghc-mod-5.5.0.0.drv-0/package.conf.d -j8 -threaded
[1 of 5] Compiling NotCPP.Utils     ( NotCPP/Utils.hs, /tmp/nix-build-ghc-mod-5.5.0.0.drv-0/NotCPP/Utils.o )

NotCPP/Utils.hs:27:12: error:
    • The constructor ‘VarI’ should have 3 arguments, but has been given 4
    • In the pattern: VarI n _ _ _
      In an equation for ‘infoToExp’:
          infoToExp (VarI n _ _ _) = Just (VarE n)
builder for ‘/nix/store/z8cdrrbkvk64c5jz8fx9y6m91nc245dw-ghc-mod-5.5.0.0.drv’ failed with exit code 1
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  16.09pre84660.e05dd52 (Flounder)

* Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  "16.09pre84660.e05dd52"

**Comment by joachifm** [comment]
I believe haskell build failures are typically regarded as upstream issues. Perhaps it could be fixed by adding the appropriate overrides to the haskell package set `configuration-common.nix`.

**Comment by romildo** [comment]
It seems to be failing because it has not been ported to `ghc-8.0.1` yet.

In `configuration.nix` I have:

``` nix
  nixpkgs.config.packageOverrides = pkgs: rec {
    # ...
    myHaskellEnv = pkgs.haskellPackages.ghcWithHoogle (
      haskellPackages: with pkgs.haskellPackages; [
        cabal-install
        ghc-mod
        hlint
        #pandoc
        #pandoc-citeproc
        stylish-haskell
      ]
    );
  };

  environment.systemPackages = with pkgs; [
    # ...
    myHaskellEnv
  ];
```
How should this be modified so that `ghc-7.10.3` is used instead of `ghc-8.0.1`?

**Comment by joachifm** [comment]
You could mark this as broken in the ghc8 package set, but other than that I think this issue can be closed, as there's really not much that can be done on our end.

**Comment by romildo** [comment]
`ghc-mod` now compiles and works with `ghc-8.0.1` on recent revisions of unstable NixOS.

``` shell
$ ghc-mod --version
ghc-mod version 5.5.0.0 compiled by GHC 8.0.1
 ```
