### ISSUE TITLE
PS/2 Microsoft keyboard stopped working in init ramdisk

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#1592]
After the `stdenv-updates` merge, my keyboard no longer works in the init ramdisk, which is bad, because I need it to enter the pass phrase for my encrypted root partition. It's a split-hand Microsoft keyboard that's connected to the machine via PS/2. (A comparable USB keyboard works fine; it's just the PS/2 one that seems dead.) I've had a similar problem before (see https://github.com/NixOS/nixpkgs/issues/1405), which was solved when 152da7671cf659a403e5d561ca1bc69940a7e90d switched the appropriate kernel module from `xtkbd` to `atkdb`. But what do I do now? Any suggestions, anyone?

**Comment by viric** [comment]
I committed a fix: force load of atkbd, master and release-14.12.
