### ISSUE TITLE
QGtkStyle and unstyled Qt 5 applications

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#15926]
## Issue description

When I run e.g. Dwarf Therapist (Qt 5.6 application) from `master`, I get:
```
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
```
and then window appears ugly and unstyled:

![Screenshot](https://i.imgur.com/DMYdpKY.png)

Interesting observations:
* `LD_DEBUG` shows that `libgtk-x11` and other libraries are tried to be loaded.
* There are mentions of `gtk-x11` string in `libQtWidgets`
* `qtbase.gtk` is not mentioned anywhere

I can't really remember if the themes actually got applied or there was some Qt default before.

### Steps to reproduce

1. Run `${dwarf-therapist}/bin/DwarfTherapist`

## Technical details

* NixOS version: `16.09.git.919db46 (Flounder) (919db46afd6cc9badb8d82985ec4697d3a0d5b6b)

cc @ttuegel

**Comment by abbradar** [comment]
When I add RPATH from `${qtbase.gtk}/lib/qt5/plugins/platformthemes/libqgtk2.so` to `LD_LIBRARY_PATH`, it works. This leaves two questions:

1. Why would `libQtWidgets`, not `libqgtk2.so` plugin, try to load GTK theme?
2. How does one use this plugin, so that it works for both 5.5 and 5.6?

**Comment by ttuegel** [comment]
> Why would libQtWidgets, not libqgtk2.so plugin, try to load GTK theme?

That's just the how Qt upstream chose to structure the plugin. I don't know what their rationale is, but from reading the source I can tell you that is where the references to `libgtk-x11` should be.

> How does one use this plugin, so that it works for both 5.5 and 5.6?

It should be enough to install it to a profile (system or user). The plugin should be backwards-compatible, so installing `qt56.qtbase.gtk` will work with Qt 5.6 or Qt 5.5.

**Comment by abbradar** [comment]
Oh well, at least it's indeed their decision. And, uh-oh, adding the plugin into environment actually _fixes_ calls from `libQtWidgets`. I'm not sure I can imagine how that works on their side.

Thank you for your help! I think this deserves a small notice in the manual -- I'll look at adding it later.

**Comment by abbradar** [comment]
@ttuegel Also, do I understand correctly that now when we split GTK style plugin into another output we can drop `gtkStyle` flag (I'm not even sure it would work disabled because moving the plugin to another output is unconditional)? If it's okay I'll prepare a patch.

**Comment by ttuegel** [comment]
> And, uh-oh, adding the plugin into environment actually fixes calls from libQtWidgets. I'm not sure I can imagine how that works on their side.

When you `dlopen()` a shared object (like the plugin), `ld` adds its `RPATH` to your own. So, `libQtWidgets` loads the plugin and when it subsequently tries to `dlopen()` `libgtk-x11`, `ld` looks in the combined `RPATH` of everything loaded by the current process (including the plugin). There is no reason for you to know any of this, but that's how the linker works! :smiley: 

> Also, do I understand correctly that now when we split GTK style plugin into another output we can drop gtkStyle flag (I'm not even sure it would work disabled because moving the plugin to another output is unconditional)? If it's okay I'll prepare a patch.

Yes, that would be fine. I thought I removed it already, but I must have forgotten.

**Comment by abbradar** [comment]
> `ld` adds its `RPATH` to your own
A-ha! I haven't known of that part, rather I imagined that it isolated contexts somehow. Then it makes sense, yes. A piece of knowledge was gained today ~_^

**Comment by abbradar** [comment]
Closed by https://github.com/NixOS/nixpkgs/commit/1942957b53aa4462ecca202ddec8fe841884ebd4

**Comment by Pitometsu** [comment]
Not sure, maybe I just have wrong configuration, but after adding `qt5.qtbase.gtk` to `systemPackages` and without `gtkStyle` flag.

``
$ qjackctl
qjackctl: symbol lookup error: /nix/store/7fx9g64j8n72wnvnc97f80ga6i7zk5zn-qtbase-5.5.1/lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface19registerTouchDeviceEP12QTouchDevice
```

**Comment by ttuegel** [comment]
@Pitometsu That is issue #15498.

**Comment by Pitometsu** [comment]
Also would be nice to have separate `qGtkStyle` package for `qt4` if it possible to avoid much recompilation.

**Comment by abbradar** [comment]
FWIW I've tried to split it to different package some time ago; it seems that GTK support is compiled not into some separate plugin but into Qt itself -- so we can't "split" it.

**Comment by Pitometsu** [comment]
@ttuegel even when I remove `qt5.qtbase.gtk`, qt5 applications still broken. Is there known workaround for now how to make them runnable?
