### ISSUE TITLE
Laptop overheating caused by gnome tracker

### ISSUE THREAD

**Issue by dvc94ch** [NixOS/nixpkgs#15921]
## Issue description

My XPS 13 Laptop suddenly started overheating while closed in my backpack. After ripping the battery out, waiting for it to cool down and rebooting I saw that tracker was consuming 99% CPU, so I killed it.

![screenshot from 2016-06-02 12-14-22](https://cloud.githubusercontent.com/assets/741807/15741847/d14b8c1c-28bb-11e6-8f0a-c8dec7cdef0e.png)

## Technical details

* System: 16.09pre84211.d231cdf (Flounder)
* nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre84211.d231cdf"

**Comment by joachifm** [comment]
Could you clarify how this relates to nixpkgs in particular?

**Comment by dvc94ch** [comment]
not sure, probably not if no one else has this problem

**Comment by joachifm** [comment]
I think you may have more luck with upstream, but it would be good to rule out misconfiguration in the nixos service.

**Comment by dvc94ch** [comment]
It seems like this issue is already known:
https://bugs.launchpad.net/ubuntu/+source/tracker/+bug/911981

It can easily be disabled: `services.gnome3.tracker.enable = false;`
Maybe this should be a default? Don't know.

**Comment by joachifm** [comment]
Did you try the workaround mentioned in the bug report:
> 
gsettings set org.freedesktop.Tracker.Miner.Files crawling-interval -2
gsettings set org.freedesktop.Tracker.Miner.Files enable-monitors false
tracker-control -r

?

I don't use this service, but it really sounds to me like it shouldn't be enabled by default if this is what it ends up doing ...

**Comment by dvc94ch** [comment]
Can't figure out which package provides gsettings. command-not-found seems to be gone.

**Comment by joachifm** [comment]
cc @lethalman

**Comment by lethalman** [comment]
I never had this problem sorry. Anyway `gsettings` is provided by glib.

**Comment by dvc94ch** [comment]
weird, glib is part of the core gnome3 packages, why isn't it in my PATH? now I'm getting: No schemas installed when trying to run gsettings. Gnome is a complicated beast... Is it important that I try the workaround?

**Comment by joachifm** [comment]
@dvc94ch not at all, I just wondered if you had noticed it; disabling the service is a bit drastic, but if you're happy with that resolution, that's fine.

**Comment by lethalman** [comment]
@dvc94ch it's long to explain, and actually it's the way nixos and nixos gnome packaging work that make it complicated. 

Enter this shell and run your gsettings commands:
```
nix-shell -p gnome3.tracker glib --command 'export XDG_DATA_DIRS=$XDG_DATA_DIRS:$GSETTINGS_SCHEMAS_PATH; return'
```

**Comment by dvc94ch** [comment]
So tracker-control doesn't exist anymore:
https://git.gnome.org/browse/tracker/commit/?id=25bb56cf04491573dc2320a959054ac4e374eeb7

I tried setting the gsettings and then `tracker reset -r`, but it doesn't prevent my cpu from revving.
