### ISSUE TITLE
MariaDB build broken on `master`

### ISSUE THREAD

**Issue by Obikawa** [NixOS/nixpkgs#159214]
### Description

MariaDB 10.6.6 does not seem to exist at the given source.

> `# nixos-rebuild boot --flake . -L`
>
> ```
> mariadb> trying https://downloads.mariadb.com/MariaDB/mariadb-10.6.6/source/mariadb-10.6.6.tar.gz
> mariadb>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> mariadb>                                  Dload  Upload   Total   Spent    Left  Speed
> mariadb>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> mariadb> curl: (22) The requested URL returned error: 404
> mariadb> error: cannot download mariadb-10.6.6.tar.gz from any mirror
> error: builder for '/nix/store/k792kjxjlaazwgb1vr75xblcdncganba-mariadb-10.6.6.tar.gz.drv' failed with exit code 1
> ```

### Workaround

After reverting the commit d70e970e48589c25ec473fe6ab71291d8150dfc2 I was able to complete the system build.

### Maintainers

@ajs124 @das_j @thoughtpolice

**Comment by ajs124** [comment]
Yeah, the unpublished those releases. I'd suggest just reverting the updates for now #159227
