### ISSUE TITLE
Cannot build NixOS from a Git submodule

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#15928]
Due to 47950b53538471c1aff04b00790fadded7eca207, it is not possible to build NixOS if your Nixpkgs clone is a Git submodule, rather than a full Git repository. Attempting to do so fails with

```
error: Not a .git directory: /home/ttuegel/nixos-config/nixpkgs/.git
```

This directory does not exist in a submodule, but it can be accessed from the parent's `.git` under `.git/modules/<submodule>`.

/cc @obadz

**Comment by obadz** [comment]
@ttuegel, could you show me the output of `ls -a …/nixpkgs/.git`?

**Comment by ttuegel** [comment]
```
$ ls -la ./nixpkgs/.git
-rw-r--r-- 1 ttuegel users 32 Jan 30  2015 ./nixpkgs/.git

$ cat ./nixpkgs/.git
gitdir: ../.git/modules/nixpkgs
```

The directory that `gitdir:` references *appears* to be a genuine Git directory.

**Comment by obadz** [comment]
@ttuegel: pls `cherry-pick` the above commit. If it works I'll merge it to `master`.

**Comment by ttuegel** [comment]
Yes, that works. Thanks!

**Comment by obadz** [comment]
great, it's pushed to `master`
