### ISSUE TITLE
Gnome 3: US alt-intl and altgr-intl keyboard layouts not available

### ISSUE THREAD

**Issue by martijnvermaat** [NixOS/nixpkgs#15923]
## Issue description

Keyboard layouts with dead keys (e.g., US alt-intl) are not available in the Gnome 3 keyboard layout chooser.

### Steps to reproduce

In `/etc/nixos/configuration.nix`:
```
services.xserver.enable = true;
services.xserver.displayManager.gdm.enable = true;
services.xserver.desktopManager.gnome3.enable = true;
```
In Gnome 3, go to *Region and Language*, click on the plus sign to add an input source. Observe that there are many layouts available, including *English (United States)*, but no variants with dead keys (on my Debian system I use *English (US, internation with dead keys)* which corresponds to the `alt-intl` variant of the `us` layout in X speak).

## Technical details

* System: 16.03.885.15e7e6e (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.03.885.15e7e6e

**Comment by martijnvermaat** [comment]
![layouts](https://cloud.githubusercontent.com/assets/623509/15743382/419f0120-28c5-11e6-9c79-5ee4e19a4349.png)

**Comment by martijnvermaat** [comment]
So it turns out I'm an ass, in recent Gnome 3 you have to first click *English (United States)* and it will show the available layouts only then, including those with dead keys. No Nix bug here.

**Comment by michaelmalonenz** [comment]
But it has helped me to figure out the exact same thing 2 years later - thanks for posting the solution!

**Comment by DevAlien** [comment]
I has now helped me as well, not very clear how that thing works

**Comment by AdsonCicilioti** [comment]
![image](https://user-images.githubusercontent.com/6278398/143961474-7ab9f47c-7bec-4b2f-b942-3c1d6117144e.png)


How define the first layout variant on nix config?
