### ISSUE TITLE
Package fwupd

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#15934]
Note to self to package fwupd

http://www.fwupd.org/

**Comment by eskimor** [comment]
Already packaged - this issue can be closed, I think.

**Comment by pSub** [comment]
Closing, see https://github.com/NixOS/nixpkgs/blob/e292d166e8e892dd6ca200245ef114e1db1c9807/pkgs/os-specific/linux/firmware/fwupd/default.nix.
