### ISSUE TITLE
Eval error in pkgs/build-support/coq/meta-fetch/default.nix

### ISSUE THREAD

**Issue by mohe2015** [NixOS/nixpkgs#159308]
### Describe the bug
According to our investigation https://github.com/NixOS/nixpkgs/blob/f9e7ee3fab11164ad6fe85879b661f84a6453f31/pkgs/build-support/coq/meta-fetch/default.nix#L62-L65 seems to be invalid syntax.

### Steps To Reproduce
```
nix repl
```
```nix
let { version = "dev"; src = {}; }
```
```
error: attribute 'body' missing
```

### Expected behavior
No error.

### Additional context
I'm writing a parser for Nix and this breaks it. It is also the only occurrence of the `let {}` syntax.

### Notify maintainers
@CohenCyril @vbgl

**Comment by piegamesde** [comment]
CC @Zimmi48 @CohenCyril @vbgl

**Comment by vbgl** [comment]
The `let` should probably be removed.
