### ISSUE TITLE
nixos-rebuild does not warns about error while local pkg repository does not exist

### ISSUE THREAD

**Issue by wdanilo** [NixOS/nixpkgs#1593]
Hello, there is a bug in ```nixos-rebuild``` command. If we run:
```nixos-rebuild switch -I nixpkgs=./my_nixpkgs```

and there is no ```my_nixpkgs``` directory, there is no warning nor an error generated, which can cause some confusion. Such important thing should generate an error.

**Comment by Profpatsch** [comment]
There is an error generated now. close @7c6f434c
