### ISSUE TITLE
Make tree-sitter grammar list extensible

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#159319]
Currently it's not possible to modify the list of tree-sitter grammars through the usual extension mechanisms (e.g. overlays), so this makes it inconvenient to test out new grammars locally without upstreaming to Nixpkgs. A way to override or extend the list of grammars would be useful.

cc @figsoda @Profpatsch

**Comment by Profpatsch** [comment]
> so this makes it inconvenient to test out new grammars locally without upstreaming to Nixpkgs.

What’s wrong with just adding the grammars to nixpkgs and using the local checkout? Unless you really don’t want to upstream the grammar.

**Comment by siraben** [comment]
Closed by #161456
