### ISSUE TITLE
tarsnap often wants fsck

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#15948]
```
Jun 02 09:50:18 guava tarsnap@-start[14392]: tarsnap: Sequence number mismatch: Run --fsck
Jun 02 09:50:18 guava tarsnap@-start[14392]: tarsnap: Error creating new archive
Jun 02 09:50:18 guava tarsnap@-start[14392]: tarsnap: Error exit delayed from previous errors.
```

I wonder if we should run `fsck` by default in the service? This is very common and blocks my backup, which has poor visibility unless I'm fiddling with systemd.

@thoughtpolice thoughts?

**Comment by joachifm** [comment]
I've used tarsnap for years and only ever needed fsck when starting with an empty cache (i.e., rarely). Just a data point.

**Comment by domenkozar** [comment]
Since there's no response I'll fix this for myself :)

**Comment by joachifm** [comment]
@domenkozar do you know of a good mechanism for getting stuff like that to the user? Back when I used BSD, it was set up to email me important information, out of the box, to make sure I'd see it and act on it. Is there a systemd equivalent? Having backups silently not happen is *terrible*.

**Comment by abbradar** [comment]
I encountered this issue and I think I've found out its cause. As of now, tarsnap NixOS service uses separate cache directories for all backups. This leads to inconsistency: after backup is completed caches of other backups are invalid and need `--fsck`.

For example, on my machine:
1. Run `tarsnap --fsck` for configurations `foo` and `bar`;
2. Run `tarsnap@foo`. observe that it works;
3. Run `tarsnap@bar`; observe that it fails;
4. Run `--fsck` for `bar`;
5. Run `tarsnap@bar`; observe that it works now;
6. Run `tarsnap@foo`; observe that it's broken.

**Comment by abbradar** [comment]
BTW I would also be interested in @joachifm's question; I had backups broken for a very long time it seems...

**Comment by abbradar** [comment]
I've asked on tarsnap-users mailing list about my findings: http://mail.tarsnap.com/tarsnap-users/msg01331.html

**Comment by joachifm** [comment]
@abbradar if I'm reading that correctly, we'd need to tie cache dirs to keys not archive jobs?

**Comment by abbradar** [comment]
Yeah. I'm working on the patch already ~_^

**Comment by abbradar** [comment]
See #19089
