### ISSUE TITLE
Request to add mongosh package

### ISSUE THREAD

**Issue by p3psi-boo** [NixOS/nixpkgs#159419]
**Project description**
The MongoDB Shell

**Metadata**

* homepage URL: https://github.com/mongodb-js/mongosh
* source URL: https://github.com/mongodb-js/mongosh
* license: APACHE LICENSE, VERSION 2.0
* platforms: linux, darwin

**Comment by marcelarie** [comment]
I will like to have it on `nixpkgs` too but fyi there is a NUR package.

https://nur.nix-community.org/repos/afreakk/
https://github.com/nix-community/nur-combined/blob/master/repos/afreakk/pkgs/mongosh/default.nix#L12
