### ISSUE TITLE
EC2 Enhanced networking support for official AMIs

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#15956]
I found a disappointing issue with NixOS on AWS EC2 - absence of support for Enhanced Networking (SRI/OV) out of box. 

See docs at http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

Here are separate issues:
1. ixgbevf is outdated on 16.03 (less then recommended 2.14). Amazon Linux AMI is better then NixOS here
2. HVM amis are built without --sriov flag. Because of 1) this makes starting spot instances with --sriov trickier

As I'm not an expert in AMI creating, instance management or kernel module packaging, I won't do pull requests on this topic. But I'd like to share some success with others.

Here is the  ixgbevf-3.1.2 kernel module package. [Docs say](https://sourceforge.net/projects/e1000/files/ixgbevf%20stable/3.1.1/) it

> supports kernel versions 2.6.18 up through 4.3.3

```
        ixgbevf = { stdenv, fetchurl, kernel }: stdenv.mkDerivation rec {
          basename = "ixgbevf-${version}";
          name = "${basename}-${kernel.version}";
          version = "3.1.2";
          
          src = fetchurl {
            url = "mirror://sourceforge/e1000/ixgbevf%20stable/${version}/${basename}.tar.gz";
            sha256 = "1vkrxbp9r3rw1q4ar26gny14swl0wlznvpvbbqdlkk2sdahkfpw4";
          };
          
          buildInputs = [ pkgs.xz ];
          
          kernelVersion = kernel.modDirVersion;

          preBuild = ''
            cd src
            substituteInPlace Makefile \
              --replace "\$(shell uname -r)" "$kernelVersion" \
              --replace "/lib/modules" "${kernel.dev}/lib/modules"
          '';
          installPhase = ''
            xz ixgbevf.ko 
            install -m444 -Dt $out/lib/modules/$kernelVersion/kernel/drivers/net/ethernet/intel/ixgbevf ixgbevf.ko.xz 
          '';
          meta.priority = 1;             # we want this to replace stock ixgbevf.ko.xz
        };
```

And here is extract from config to enable this module:
```
          boot.extraModulePackages = [ (ixgbevf { inherit (pkgs) stdenv fetchurl; kernel = pkgs.linuxPackages.kernel; }) ];
          boot.initrd.kernelModules = [ "ixgbevf" ];
```

My instance started and ssh works. Now I have this:
```
# ethtool -i eth0
driver: ixgbevf
version: 3.1.2
firmware-version: N/A
expansion-rom-version:
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

Ping @edolstra

**Comment by edolstra** [comment]
Thanks, I wasn't aware of Enhanced Networking. I'll look into it.

**Comment by edolstra** [comment]
Added the driver to the Amazon config: 04eb7492dccb3d314911666fea15a67602c1e422, 3adb769776199ea5e4fe8760fca0e4dca3193fae. Will need to rebuild the AMIs though (and make NixOps enable Enhanced Networking automatically), and add the `ena` driver for `x1` instances.
