### ISSUE TITLE
teamviewer. icons are absent [Failed reading PNG because unable to find libpng12.so.0]

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#15965]
## Issue description
On the teamviewer GUI the images are absent. Does't show a big blue connect button and other icons. So, I can't click to connect to the shared session.
Log show a several messages like below. I guess one message per one png icon on the UI.
err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng12.so.0

The libpng is installed. By `find` I found many installations in the /nix/store. In all places symlink libpng.so.0 is exists.

### Steps to reproduce
Install and run teamviewer.

## Technical details

* System: 16.03.802.01f5711 (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.802.01f5711"

**Comment by abbradar** [comment]
Thanks for the report! BTW for future reference, where do you look for log messages? I see nothing in stdout...

**Comment by danykey** [comment]
You can see log files in /home/$USERNAME/.local/share/teamviewer11/logfiles/ or click in the TeamViewer menu "Extras" -> "Open log files..."

**Comment by danykey** [comment]
I made a typo. "In all places symlink libpng.so.0 is exists." - > "In all places symlink libpng**12**.so.0 is exists."

**Comment by abbradar** [comment]
Yeah, I've fixed the library version. It should work now.

**Comment by offlinehacker** [comment]
Teamviewer users be aware of:
https://m.reddit.com/r/2007scape/comments/4m6n7y/psa_teamviewer_was_recently_compromised_if_you/

V sob., 4. jun. 2016 02:42 je oseba Nikolay Amiantov <
notifications@github.com> napisala:
