### ISSUE TITLE
Dwarf Fortress expression should set `dontPatchELF = true`

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#15969]
## Issue description

If you look at https://github.com/NixOS/nixpkgs/blob/224c24f0302f38c0d0c816c3b20d3f54c907d70d/pkgs/games/dwarf-fortress/game.nix#L31-L34 — it’s using `patchelf`, and not setting`dontPatchELF = true`.

Most probably it should do that, as suggested by @ttuegel on freenode/#nixos:

* 22:10 \<ttuegel\> michalrus: Oh! You probably need to set `dontPatchELF = true;' in your derivation. If that doesn't work, report it over at https://github.com/nixos/patchelf.

* 22:13 \<michalrus\> Dwarf Fortress uses patchelf manually and they don’t use dontPatchELF, see https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/dwarf-fortress/game.nix

* 22:16 \<ttuegel\> michalrus: They really should... I guess they just get lucky that the automated patchelf call doesn't break anything.

**Comment by joachifm** [comment]
Is there an actual problem? The `patchelf` setup hook removes entries in the rpath that appear redundant, so it's not clear to me that it inherently conflicts with setting the rpath manually.

**Comment by ttuegel** [comment]
This is not an *actual* problem, but something that could become a problem in the future. By the way, for pre-built binaries, you probably also always want `dontStrip = true;`.

**Comment by abbradar** [comment]
Hm, why can it be a problem? I usually leave it (setting `dontStrip = true` meanwhile) to clean unused RPATH entries.

**Comment by ttuegel** [comment]
> Hm, why can it be a problem?

I've had problems in the past when I am appending to the RPATH and the pre-built binary has RPATH entries which are not "needed," but used to `dlopen` things at runtime, but if you are just doing `--set-rpath` anyway, I suppose it is fine.

**Comment by abbradar** [comment]
Ah! Yes, this can be a problem, but I've used `--add-needed` to fix this more granularly... unless I'm lazy. Anyway, @michalrus, is there any problem with Dwarf Fortress which needs this fix?

**Comment by michalrus** [comment]
@abbradar, none that I know of. =) I just didn’t want this hint from @ttuegel to disappear in channel’s logs.
