### ISSUE TITLE
clang_35 doesn't build with nixpkgs head

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#15974]
## Issue description

Trying to build clang_35 with nixpkgs HEAD (8cb37c1) fails.

The build log: https://gist.github.com/dfc251b8e897f4810f0d35e4f1c3b816

### Steps to reproduce

`nix-shell -p clang_35`

**Comment by kevincox** [comment]
Is this still a problem?

**Comment by kevincox** [comment]
Never mind, it has been marked as broken. 

@andrewrk @dezgeg: You guys appear to be the clang experts. Do you have time to look into this?

**Comment by andrewrk** [comment]
That's a pretty strange compilation failure. Seems like it would be easy to patch if it came down to that. I'm not sure why that would be happening though.

**Comment by kevincox** [comment]
Would it be fine to merge that patch? It's really ugly but if you aren't developing visibility isn't too important.

**Comment by kevincox** [comment]
There is also the option that the old version of clang has been marked broken for a couple of months so it might be worth dropping it? I'm not sure if there is large value to fixing the old release.

**Comment by andrewrk** [comment]
I'm generally in favor of ditching the old in favor of the new if we can get away with it. You have my approval, for what it's worth.

It seems fair to drop support for it, but if someone submits a working build for it, then that's fine we could accept that.

**Comment by kevincox** [comment]
I'll see if @expipiplus1 wants to fix it otherwise I will create a PR to drop it this week.

**Comment by expipiplus1** [comment]
Clang 3.5 is required for running the Terra compiler, so removing Clang 3.5 does have wider ranging repercussions.

I'd be happy for my horrible patch to be merged (I can submit a PR if you want). I've not had any problems personally using this version of Clang. I'm not invested enough to implement a proper fix though :)

**Comment by kevincox** [comment]
@andrewrk Would you be prepared to accept that patch? Or what would your preferred course of action be?

**Comment by andrewrk** [comment]
I'd be happy to accept it but I'm not an official collaborator of nixpkgs.

**Comment by kevincox** [comment]
Well if you open a PR there will be at least 2 :+1:s so I would go for it.

**Comment by andrewrk** [comment]
> Clang 3.5 is required for running the Terra compiler, so removing Clang 3.5 does have wider ranging repercussions.

Interesting. I wonder why they're stuck on such an old version. I wonder if there were JIT regressions.

**Comment by expipiplus1** [comment]
I've opened the PR @andrewrk @kevincox
