### ISSUE TITLE
Master builds failing No space left on device

### ISSUE THREAD

**Issue by Azulinho** [NixOS/nixpkgs#15987]
https://hydra.nixos.org/jobset/nixos/trunk-combined
```
Last checked:	2016-06-04 19:16:12, with errors!
Last evaluation:	2016-06-04 11:15:21
```

https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors
```
error fetching latest change from git repo at `https://github.com/NixOS/nixpkgs.git':
fatal: write error: No space left on device
fatal: index-pack failed
```

**Comment by vcunat** [comment]
Such transient problems happen occasionally. It seems OK already, probably solved without anyone intervening.

**Comment by Azulinho** [comment]
disclaimer: ops person here

"Such transient problems happen occasionally"
Leads me to think that is related to the number of concurrent builds running that would sometimes exceed the available disk space.
Fat packages with a lot of dependencies would probably cause this issue every so often,
kde414 packages seem a bit guilty
https://hydra.nixos.org/build/36631521/nixlog/1/tail-reload

**Comment by vcunat** [comment]
No, probably not. AFAIK in the current setup the machine that does the evaluations stores none of the build results. The builds are performed by slaves that fetch and upload directly from/to Amazon S3.

**Comment by vcunat** [comment]
The slaves have the problems "relatively often" (not often wrt. the amount of builds done), as in that log you found. For the evaluator it's probably much rarer condition.
