### ISSUE TITLE
ati_unfree: doesn't work with some display managers

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#15988]
Data so far:
- OK: lightdm;
- KO: kdm, gdm.

For details see https://github.com/NixOS/nixpkgs/issues/9903#issuecomment-223483656

**Comment by cleverca22** [comment]
related, a few months ago, i found that ati_unfree 'worked' with slim+xfce, but the instant i enabled dual-monitor, it segfaulted X and left the gpu in a bad state

attempting to restart X caused the kernel to hang solid

and then upon rebooting, slim worked fine, i logged in, and xfce restored the monitor state, crashing it again!

**Comment by domenkozar** [comment]
cc @ocharles

**Comment by ocharles** [comment]
Thanks @domenkozar, this was exactly my problem. I'm now using ati_unfree with `lightdm` successfully. In the meantime, could we perhaps just throw an exception if someone tries to build a `configuration.nix` with `ati_unfree` and KDM or GDM?

**Comment by adelbertc** [comment]
Unsure if related, but prior to using ati_unfree I had `services.xserver.enable = true;` with XMonad enabled as my window manager. Seemed to be working fine, then I set:

```nix
nixpkgs.config.allowUnfree = true;

services.xserver.videoDrivers = [ "ati_unfree" ]
```

did a `nixos-rebuild switch` followed by a `reboot`, and now X doesn't seem to want to start anymore, I just get dropped into a shell as if X was never enabled.

Any ideas?

**Comment by jerith666** [comment]
Are you using a display manager?  Do you see the same stack trace as in https://github.com/NixOS/nixpkgs/issues/9903#issuecomment-223483656?

**Comment by davidak** [comment]
Linux 4.9, LightDM and Xfce works, but performance is very bad. https://github.com/NixOS/nixpkgs/issues/49726#issuecomment-485301170

**Comment by Artturin** [comment]
ati_unfree removed https://github.com/NixOS/nixpkgs/commit/7117588d2666f975e8239d0aebd8a9dc7d73a7cf
