### ISSUE TITLE
Packaging request: oh my posh

### ISSUE THREAD

**Issue by coolshaurya** [NixOS/nixpkgs#159963]
**Project description**
A prompt theme engine for any shell.

![image](https://user-images.githubusercontent.com/32027323/153837449-77884a2c-bfa2-4651-a4bc-17279c4b90fa.png)

**Metadata**

* homepage URL: https://ohmyposh.dev
* source URL: https://github.com/jandedobbeleer/oh-my-posh
* license: GPL-3.0
* platforms: MacOS and Linux (Windows too, but that's irrelevant for Nix)

**Comment by urandom2** [comment]
fixed in 45bc6744b2f
