### ISSUE TITLE
Pantheon (Gala) spamming logs with assertion failures (clutter_paint_volume_set_width)

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#159981]
I’m running NixOS unstable, but I had the same behaviour with 21.11 (and I think maybe even 21.05).

My journal is full of this:

```
Feb 13 21:30:55 kirXps .gala-wrapped[2559]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Feb 13 21:30:55 kirXps .gala-wrapped[2559]: clutter_paint_volume_set_height: assertion 'height >= 0.0f' failed
```

And there are tens (like sometimes ~60) of these messages per second. I am not exactly sure what causes this issue, it starts to happen once I launch a “heavy” app (Firefox, Chromium, GIMP) and does not start to happen for “lighter” apps. Once it starts, it does not stop even after I exit the app, only logging out helps.

The process with pid 2559 is Gala, but I am having a hard time figuring out what is the actual code that causes this. I am actually surprised that I can’t find any reports of this given that I don’t think there is anything special about my setup, this issue is happening constantly, has been present for quite a long time, and is pretty annoying since it makes the journal unreadable and causes tons of disk writes (like, right now, journald is writing on average ~12 KB/s, so almost 1 MB/minute).

I don’t understand what is special about those “large” apps that cause it yet, and I have no idea where to even start. Just wanted to create an issue to let others know that I’ll be looking into it. I’ll be grateful for any pointers.

**Comment by kirelagin** [comment]
(I have to admit, initially I assumed it had something to do with Wingpanel and the volume indicator, but no 😁.)

**Comment by bobby285271** [comment]
Please re-open (and provide a step to reproduce the log spam if possible) if you still have this, for now I assume this is fixed by https://github.com/elementary/gala/pull/1417, this commit is in stable channels.
