### ISSUE TITLE
Question: System configuration

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#16000]
I know there is Nix, NixOps, and NixOS. Let's say I wanted to control the permissions of all the created users by using ACLs, or I wanted `$HOME/mydir` to exist for all users (typically something done with tools like Puppet, Chef, etc.) or I wanted to do a checkout of some Mercurial repository as part of a nix-rebuild switch. How can that be controlled?  

It appears the language simply isn't there to express these things or am I missing something?

**Comment by dvc94ch** [comment]
To checkout a mercurial repository you can use `fetchhg`. Nix and nixos aren't meant to manage your home directory. What kind of ACL permissions do you want to set? Because everything is in /nix/store I don't know if there are too many permissions you have to manage. Home directories belong to the user and everything else is managed by nix. Nix expressions aren't meant to replace shell script or build tools, but are only meant to describe packages and configuration.

It kind of looks like you are looking for someone to convince you to use nix/nixos. If you don't know why you want to use nix, then you probably don't need it, and will save yourself a lot of frustration with something more mainstream ;)

**Comment by 0xABAB** [comment]
@dvc94ch I don't mind writing shell scripts, but where can I put such homedir shell script management logic then?

Fetchhg is also again in a build output; I just want to put it in an arbitrary location on the filesystem. 

This is also exactly what I asked. I didn't specifically ask for the Nix language; I asked whether there was any way to express this. Otherwise one still needs to resort to Puppet/Chef/<insert terrible tool> to do these kinds of things.

I *think* NixOS modules can do this, myself, because otherwise https://www.infoq.com/articles/configuration-management-with-nix would not make sense; it wouldn't be a complete configuration management system.

**Comment by dvc94ch** [comment]
Maybe `nixos-option environment.shellInit` or `nixos-option programs.bash` suit your needs. To put it in an arbitrary location on the filesystem you'll have to add a mercurial client to the environment packages and a script. Why would you want it to be part of a nixos-rebuild switch?

**Comment by 0xABAB** [comment]
@dvc94ch How can it be complete if it is not possible to set all properties of the system (this includes settings using interfaces like setfacl under the hood, etc.? I don't subscribe to the theory that one should draw an arbitrary line somewhere and say that managing "desktop wallpapers" is not part of configuration management; it is. If a solution is not able to manage such settings in some way, then it's simply an incomplete system. In the case of users, I am not sure what the interaction is between NixOS's declarative users and setting the permissions of home dirs via e.g. setfacl. 

In theory one should be able to override the `users` module to make a `myusers` module, and then use that to do the actual setfacl commands.

**Comment by danbst** [comment]
@0xABAB 
>  I don't subscribe to the theory that one should draw an arbitrary line somewhere and say that managing "desktop wallpapers" is not part of configuration management; it is.

I think, Nixos is incomplete in this sense. There is an authority, that defines what parts of a system should be available to all NixOS users.

Their is bunch of override mechanisms in Nixos to overcome this issue, but often you have to copypaste some solution (I'm talking about nixos modules now) and heavily patch code.

> It appears the language simply isn't there to express these things

Hardly true. You *can* build your own nixos by patching nixpkgs sources when overrides are too limited. 

> I wanted to do a checkout of some Mercurial repository as part of a nix-rebuild switch

```
  system.activationScripts.fetch-some-hg-on-nixos-rebuild = {
    text = ''
          mkdir -p "$hgfolder"
          if [ ! -d "$hgfolder/.hg" ]; then
            echo "Creating repository $hgfolder for $hgurl..."
            cd $hgfolder && ${pkgs.mercurial}/bin/hg init ${exts}
            echo -e "[paths]\ndefault = $hgurl" > $hgfolder/.hg/hgrc
            echo "Finished creating repository!"
          fi        
          ${pkgs.mercurial}/bin/hg pull -u ${exts} -R $hgfolder
    '';
    deps = [];
  };
```
(no timeout, but easy to add)

**Comment by 0xABAB** [comment]
@danbst Interesting example. 

I have no idea what you meant by "There is an authority, that defines what parts of a system should be available to all NixOS users.". Can you explain what you meant?
