### ISSUE TITLE
openvpn-<node>.service: Failed with result 'timeout'.

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#16002]
With latest stable NixOS, I rebuilt the system configuration which includes openvpn and it just timed out. Running it again did work without a timeout without it doing anything else. Can I override this value somewhere globally for all services?

**Comment by domenkozar** [comment]
Can you provide some logs? Timeouts are hard to debug without a lot of information.

You can probably set global timeout, check systemd documentation.

**Comment by grahamc** [comment]
Is this a dup of https://github.com/NixOS/nixpkgs/issues/7703?

**Comment by jpierre03** [comment]
@0xABAB is there some updates ?

**Comment by 0xABAB** [comment]
@grahamc Could be
@jpierre03 I wrote my own module in a way that would never be accepted in nixpkgs.

I am closing this, because I won't be reproducing it in the near future.
