### ISSUE TITLE
SML/NJ does not compile on Mac

### ISSUE THREAD

**Issue by svenkeidel** [NixOS/nixpkgs#16018]
When I trie to compile SML/NJ on Mac, I get the error below. It seams to be a x86 related issue. Is there a way to compile SML/NJ on a 64-Bit machine?

```
nix-env -iA nixpkgs.smlnj 
installing ‘smlnj-110.79’
these derivations will be built:
  /nix/store/1wpgvxabl6wagc80v4caq47z7r7jfqn2-MacOSX10.9.sdk.drv
  /nix/store/cfq25rc0086csa7najp0jfi9zfnbkr7r-smlnj-110.79.drv
building path(s) ‘/nix/store/ajpv8kn80c3ka4m6lchzp3zpmh27d6ls-MacOSX10.9.sdk’
[...]
echo "v-x86-darwin" > v-x86-darwin
cc -m32 -std=c99 -c -g -O2 -D_DARWIN_C_SOURCE -mmacosx-version-min=10.6 -I../config -I../objs -I../include ../config/gen-common.c
cc -m32 -std=c99 -g -O2 -D_DARWIN_C_SOURCE -mmacosx-version-min=10.6 -DHOST_X86 -DTARGET_X86 -DOPSYS_UNIX -DOPSYS_DARWIN -DGNU_ASSEMBLER -DDLOPEN -DINDIRECT_CFUNC -I../config -I../objs -I../include -o gen-sizes ../config/gen-sizes.c gen-common.o
ld: warning: ld: warning: ignoring file /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/crt1.10.6.o, file was built for x86_64 which is not the architecture being linked (i386): /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/crt1.10.6.oignoring file /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/libSystem.dylib, file was built for x86_64 which is not the architecture being linked (i386): /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/libSystem.dylib

Undefined symbols for architecture i386:
  "___stderrp", referenced from:
      _main in gen-sizes-e0508f.o
      _OpenFile in gen-common.o
      _main in gen-sizes-e0508f.o
      _OpenFile in gen-common.o
  "_exit", referenced from:
      _main in gen-sizes-e0508f.o
      _OpenFile in gen-common.o
  "_fclose", referenced from:
      _CloseFile in gen-common.o
  "_fopen$DARWIN_EXTSN", referenced from:
      _OpenFile in gen-common.o
  "_fprintf", referenced from:
      _main in gen-sizes-e0508f.o
      _OpenFile in gen-common.o
      _CloseFile in gen-common.o
  "_fputc", referenced from:
      _main in gen-sizes-e0508f.o
      _OpenFile in gen-common.o
      _CloseFile in gen-common.o
  "_fwrite", referenced from:
      _main in gen-sizes-e0508f.o
      _OpenFile in gen-common.o
  "start", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture i386
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
makefile:375: recipe for target 'gen-sizes' failed
make[1]: *** [gen-sizes] Error 1
make[1]: Leaving directory '/private/var/folders/0q/r91r4tq92d94d0r0_kz2x4680000gr/T/nix-build-smlnj-110.79.drv-0/base/runtime/objs'
mk.x86-darwin:46: recipe for target 'all' failed
make: *** [all] Error 2
./config/install.sh: !!! Run-time system build failed for some reason.
builder for ‘/nix/store/cfq25rc0086csa7najp0jfi9zfnbkr7r-smlnj-110.79.drv’ failed with exit code 1
error: build of ‘/nix/store/cfq25rc0086csa7najp0jfi9zfnbkr7r-smlnj-110.79.drv’ failed
```

Best,
Sven

**Comment by joachifm** [comment]
Please provide more details about which checkout this is, what arch, etc. The only salient part of the output, the rest being noise as far as I can tell, appears to be
> ld: warning: ld: warning: ignoring file /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/crt1.10.6.o, file was built for x86_64 which is not the architecture being linked (i386): /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/crt1.10.6.oignoring file /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/libSystem.dylib, file was built for x86_64 which is not the architecture being linked (i386): /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/libSystem.dylib
Undefined symbols for architecture i386:
[...]
ld: symbol(s) not found for architecture i386

**Comment by svenkeidel** [comment]
The error message was produced on the nixpkgs-unstable channel, but is also reproducible in master. My machine is a 64-bit MacBook Pro.

**Comment by henrytill** [comment]
cc @acowley

**Comment by acowley** [comment]
I can reproduce, but haven't been able to fix this yet. SML/NJ needs to build as a 32bit executable, and we're missing some basic symbols.

**Comment by svenkeidel** [comment]
@acowley, thanks for looking into this issue. Let me know if I can help.

**Comment by acowley** [comment]
We'll need people with more invested in the darwin architecture to weigh in.

The problem is this:

```
$ file /usr/lib/libSystem.dylib 
/usr/lib/libSystem.dylib: Mach-O universal binary with 2 architectures
/usr/lib/libSystem.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libSystem.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
```

vs.

```
$ file /nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/libSystem.dylib
/nix/store/d6pmsgblamr0wfvpdzikv8xnlfs5sjym-Libsystem-osx-10.9.5/lib/libSystem.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

I could not find an easy way to change the `nixpkgs` `libSystem` to target `i386` as well as `x86_64`, which leaves me with a nasty if expedient solution: link with `/usr/lib/libSystem.dylib` where needed.

I've done this [here](https://github.com/acowley/nixpkgs/commit/160122f049e8b307315ae9d6248f9b4326b5d176) and can open a PR if @copumpkin, @pikajude, or someone else with The Knowledge can chime in. It may be the wrong solution, but it gets `smlnj` working on darwin again.

**Comment by matthewbauer** [comment]
@acowley I think that will probably the path of least resistance here. I think the correct way to handle this would be to have an equivalent Darwin equivalent for "pkgsi686Linux" but we've never had a working i686 Darwin stdenv.

Is there a good reason for smlnj being built as a 32-bit executable?

**Comment by veprbl** [comment]
This seems to be the same issue as what I found in #8849 . It is basically what @acowley describes. I made some progress in restoring i386 symbols in the other ticket, but haven't completed it.

**Comment by acowley** [comment]
That's great progress @veprbl! Do you know why we filter out so many symbols from `libSystem`? Maybe we could whitelist these symbols as problems arise, but I'd like to better understand the motivation since we're working around a problem of our own creation.

**Comment by veprbl** [comment]
Well we explicitly filter out i386 because the tool that we use to "reexport" libSystems system seems to be working with one arch at a time. I was able to produce some subset of i386 symbols and glue them with x86_64 into one library, but I haven't completed adding all of them.

**Comment by matthewbauer** [comment]
smlnj is now building on nixpkgs-unstable.
