### ISSUE TITLE
`nixos-install` doesn't work within a `nix-shell`

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#16015]
## Issue description

running `nixos-install` while inside `nix-shell -p vim` eventually yields an error, as first observed here

http://lists.science.uu.nl/pipermail/nix-dev/2016-April/020189.html
### Steps to reproduce

install nixos. In particular, I reproduced this by following these instructions for setting up a Vultr vps https://www.vultr.com/docs/install-nixos-on-vultr

it reproduced with 14.12, 15.09, 16.03
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by Profpatsch** [comment]
triage: can you still reproduce this?
