### ISSUE TITLE
Packaging request: webkitgtk_5_0

### ISSUE THREAD

**Issue by Stunkymonkey** [NixOS/nixpkgs#160219]
**Project description**
there is already package `webkitgtk` and `webkitgtk_4_1`.
There is a new version `webkitgtk_5_0`, which is missing in nixpkgs. I think this comes with `gtk4`.
maybe having a look at the [arch-linux-build](https://github.com/archlinux/svntogit-packages/blob/packages/webkit2gtk-5.0/trunk/PKGBUILD) is helpfull.

ping to the gnome-team:
@hedning, @jtojnar, @dasj19, @maxeaubrey

**Metadata**

* homepage URL: https://webkitgtk.org/
* source URL: same as `webkitgtk`
* license: bsd2
* platforms: unix, linux, darwin

**Comment by jtojnar** [comment]
Yes, if you link webkitgtk against GTK 4, you get 5.0 ABI version. So far I have not packaged it because it is not considered stable yet and no project depends on it AFAIK, so I could not be bothered to endure the painfully slow build.

**Comment by Stunkymonkey** [comment]
I know, that `newsflash` will depend on it soon.

**Comment by Stunkymonkey** [comment]
thanks. is fixed by #191931
