### ISSUE TITLE
Libreoffice + Langtool plugin: java.lang.NoClassDefFoundError: java/util/logging/Logger

### ISSUE THREAD

**Issue by bryanhonof** [NixOS/nixpkgs#160315]
### Describe the bug

When using `libreoffice-fresh` with the [Languagetool plugin](https://extensions.libreoffice.org/en/extensions/show/languagetool) I get the following error.

![image](https://user-images.githubusercontent.com/5932804/154251284-b983c013-0748-4df4-b20b-34e2ab19e406.png)

I'm assuming this is caused by the following code. Since it doesn't include the `java.logging` module.

https://github.com/NixOS/nixpkgs/blob/a03ae0e6d078cfdbb8404c3bff3622bd4e2f1c57/pkgs/applications/office/libreoffice/default.nix#L27-L29

### Steps To Reproduce
1. Install `libreoffice-fresh`
1. Install the [Languagetool plugin](https://extensions.libreoffice.org/en/extensions/show/languagetool)
1. Try to open Libreoffice Writer

### Expected behavior

The Languagetool plugin doesn't cause a runtime error.

### Notify maintainers

@Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.99, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 7c6f434c** [comment]
>I'm assuming this is caused by the following code.
>
>https://github.com/NixOS/nixpkgs/blob/a03ae0e6d078cfdbb8404c3bff3622bd4e2f1c57/pkgs/applications/office/libreoffice/default.nix#L27-L29

Hm, jre_minimal tests seem to confirm it; does adding "java.logging" there help?

**Comment by Ma27** [comment]
Happy to take a look by the end of the week :)

**Comment by bryanhonof** [comment]
@Ma27 That'd be great if you could do that. I tried building it on my laptop. But it was still building after ~3 hours. :)
