### ISSUE TITLE
postgresql cannot find plugins

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#16032]
On latest unstable as of this posting (nixos-16.09pre84674.fbde3a7) postgresql seems to have $libdir set incorrectly, making it impossible to load plugins such as PostGIS.

```sql
root=# CREATE EXTENSION postgis;
ERROR:  could not access file "$libdir/postgis-2.2": No such file or directory
```

```sh
> pg_config --libdir
/nix/store/w619ay8m1h84ym3kpqhl7mwfar6py2vc-postgresql-9.4.6-lib/lib
```

Compare 16.03:
```sh
> pg_config --libdir
/run/current-system/sw/lib
```

**Comment by joachifm** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/15512

**Comment by danbst** [comment]
should this be marked as fixed?

**Comment by fpletz** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/17838.
