### ISSUE TITLE
iotop: CONFIG_TASK_DELAY_ACCT not enabled in kernel

### ISSUE THREAD

**Issue by MatthewCroughan** [NixOS/nixpkgs#160361]
### Describe the bug
When running `iotop` on `Linux t480 5.15.21 #1-NixOS SMP Sat Feb 5 18:21:09 UTC 2022 x86_64 GNU/Linux`, it results in iotop printing the message:

```
CONFIG_TASK_DELAY_ACCT not enabled in kernel, cannot determine SWAPIN and IO %    107 be/4 root        0.00 B/s    0.00 B/s  ?unavailable?  [kstrp]
```

### Steps To Reproduce
1. Ensure you are running the latest Linux kernel available from Nixpkgs at the time of writing (5.15.21) 
2. Grab iotop (`nix-shell -p iotop`)
3. See that it complains about `CONFIG_TASK_DELAY_ACCT` not being available in the kernel.

### Expected behavior
The IO column should have a percentage printed. 

#### Broken
![image](https://user-images.githubusercontent.com/26458780/154341964-e029e52a-d0b7-4d2f-a4d7-d479d93ee9ec.png)
#### Working
![image](https://user-images.githubusercontent.com/26458780/154342726-10f1ddb1-9f65-4f7b-888a-ff8a52784d68.png)

### Notify maintainers

@7c6f434c

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
user: matthew ~ 
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.21, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(root): `""`
 - channels(matthew): `""`
 - nixpkgs: `/nix/store/zwbw7dknw89ai257hicmwv8lhid3qb62-source`

```

**Comment by MatthewCroughan** [comment]
https://forum.manjaro.org/t/config-task-delay-acct-error-in-iotop-kernel-5-14/84466/2

**Comment by MatthewCroughan** [comment]
https://forums.gentoo.org/viewtopic-t-1144083-view-previous.html?sid=23a3f0609d89e30de53be25b4a999870

**Comment by nixinator** [comment]
maybe bumping iotop to the latest version wil resolve this, there is mention of this in iotop git logs.

https://repo.or.cz/iotop.git/commit/ab35334d374e588bec12d201fb8869c536f0545d
l

**Comment by 21stce** [comment]
The error message in iotop is not correct, but adding the following line to `/etc/nixos/configuration.nix` will fix the problem:

`boot.kernelParams = ["delayacct"];`

**Comment by jian-lin** [comment]
I tested with [this](https://repo.or.cz/iotop.git/commit/a14256a3ff74eeee59493ac088561f1bafab85a7) commit. Still has this issue.
![iotop-newest](https://user-images.githubusercontent.com/75130626/158845968-06a7b013-aeca-425c-ba9a-5db1d065e699.png)

Setting `kernel.task_delayacct` to 1 works for me.

**Comment by o8opi** [comment]
This seems to be fixed by either using the recommended C version of iotop: `iotop-c`, or  by setting `kernel.task_delayacct` to 1

**Comment by ebsf1** [comment]
Same issue on Ubuntu 22.04 (kernel 5.15.0-43-generic currently).

**Comment by Sepero** [comment]
I'm also experiencing this issue. Running iotop-c seems to very more accurately describe the problem.
`task_delayacct is OFF`
![Screenshot_20220914-140511](https://user-images.githubusercontent.com/1575546/190085353-fb924ad5-5e1e-42ab-a394-cfdf4d04e674.jpg)

**Comment by Sepero** [comment]
Here is the fix I put in my configuration. Now I'm no longer getting the error.
```boot.kernel.sysctl = { "kernel.task_delayacct" = 1; }```

Credit to @jian-lin

**Comment by Artturin** [comment]
with iotop-c you can press `Ctrl-T` to enable `task_delayacct` because our kernel is built with the required option

**Comment by 1265578519** [comment]
有人解决了吗？

**Comment by nixinator** [comment]
Well, a lot things can't be 'solved', you just have to patch and work around it.

i need to brush up on my Chinese/Japanese...

**Comment by Sepero** [comment]
> Here is the fix I put in my configuration. Now I'm no longer getting the error. `boot.kernel.sysctl = { "kernel.task_delayacct" = 1; }`
> 
> Credit to @jian-lin


The delayacct flag should have an option to enable in the program config here

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/iotop.nix

I believe this would resolve the problem properly.
