### ISSUE TITLE
`Failed to open` systemd service file warning in `switch-to-configuration`

### ISSUE THREAD

**Issue by B4dM4n** [NixOS/nixpkgs#160445]
### Describe the bug

Switching NIxOS configurations when using `networking.wireguard.interfaces` produces the following warning:
```
Failed to open /etc/systemd/system/wireguard-wg0-peer-Ks9y…BIx3d.service: No such file or directory at /run/current-system/specialisation/spec/bin/switch-to-configuration line 137.
Failed to open /nix/store/6m1ckayw2n6i7aqbzqd9qr7cm6iwp66h-nixos-system-machine-22.05.git.86a0c32d907/etc/systemd/system/wireguard-wg0-peer-Ks9y…SBIx3d.service: No such file or directory at /run/current-system/specialisation/spec/bin/switch-to-configuration line 137.
```

### Steps To Reproduce

1. Checkout `nixpkgs` b2de46276d01a88d068aa9b04bba387d2e7c991d (current master)
2. Create `switch-to-configuration-test.nix` file in the `nixpkgs` directory with the following content:
```nix
import ./nixos/tests/make-test-python.nix {
  name = "switch-to-configuration";
  machine = let keys = import ./nixos/tests/wireguard/snakeoil-keys.nix; in
    {
      networking.wireguard.interfaces.wg0 = {
        inherit (keys.peer0) privateKey;

        peers = [{ allowedIPs = [ "0.0.0.0/0" ]; inherit (keys.peer1) publicKey; }];
      };

      specialisation.spec.configuration = { };
    };

  testScript = ''
    machine.wait_for_unit("multi-user.target")
    out = machine.succeed("/run/current-system/specialisation/spec/bin/switch-to-configuration test 2>&1 | tee -a /dev/stderr")
    assert 'Failed to open' not in out
  '';
}
```
3. Run `nix build -f ./switch-to-configuration-test.nix`
4. The test fails and produces the `Failed to open` warning

### Expected behavior

`switch-to-configuration` should not produce warnings.

### Additional context

It looks like `switch-to-configuration` currently can't handle service file names containing a `\`.

```
wireguard-wg0-peer-Ks9yRJIi-0vYgRmn14mIOQRwkcUGBujYINbMpik2SBIx3d.service  # file switch-to-configuration is accessing
wireguard-wg0-peer-Ks9yRJIi-0vYgRmn14mIOQRwkcUGBujYINbMpik2SBI\x3d.service # actual service file
```

I tracked the first failing commit down to #157329.

The warning seems to not create any problems for me at the moment and all services are running.

### Notify maintainers

@dasJ

**Comment by dasJ** [comment]
Great… I'll take a look
