### ISSUE TITLE
mysql-workbench: error: pynacl-1.4.0 not supported for interpreter python2.7

### ISSUE THREAD

**Issue by danwdart** [NixOS/nixpkgs#160455]
### Describe the bug
Error when trying to install/run mysql-workbench:
```
error: pynacl-1.4.0 not supported for interpreter python2.7
```

### Steps To Reproduce
1. Either add to system packages or use nix-shell -p mysql-workbench
2. Error shown

### Expected behavior
MySQL Workbench installed

### Notify maintainers
Not sure if @gebner or @r-ryantm or someone else?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.21-hardened1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336020.2128d0aa28e, unstable-21.11pre306621.439b1605227, nixpkgs-20.09"`
 - channels(dwd): `"unstable-21.11pre306621.439b1605227, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Narice** [comment]
if I'm not mistaking, this is tracked as part of #101964

**Comment by rnhmjoj** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/191174
