### ISSUE TITLE
KDE5: keyboard layout switcher broken

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#16040]
## Issue description

For some time I have no keyboard layout switcher anymore in the system tray, even though I have configured multiple layouts.

### Steps to reproduce

Configure multiple layouts in System Settings / Input Devices / Keyboard / Layouts and set 'Show layout indicator'. If I am correct a keyboard layout switcher should appear in the System Tray.

In the log I noticed
```
Jun 07 13:22:47 fr-laptop xsession[999]: org.kde.kurifilter-ikws: "Jun 07 13:21:15 fr-laptop xsession[999]: org.kde.kcm_keyboard: Can't open the xml file \"/usr/share/xml/iso-codes/iso_639_3.xml\""
```

It seems the following path is needed
```
/nix/store/nabhg70f4fyg3xhcm47mmcnrymjck410-iso-codes-3.56/share/xml/iso-codes/iso_639_3.xml
```

## Technical details

* System: NixOS: `16.09.git.5474d37 (Flounder)`

cc @ttuegel

**Comment by FRidh** [comment]
I will try adding iso-codes to plasma-workspace

**Comment by ttuegel** [comment]
Thanks for tracking this down! 

You can quickly unpack the source with
```
$ nix-shell -A kde5.plasma-workspace --run unpackPhase
```
and `grep` through it for `iso-codes`. It's possible it needs to be patched in more than one place.

**Comment by ttuegel** [comment]
I added the `iso-codes` dependency. Please let me know if there are further problems!

**Comment by FRidh** [comment]
Thanks! I will test it as soon as Hydra has rebuilt it.

**Comment by FRidh** [comment]
It's all working now, thanks!
