### ISSUE TITLE
ffmpeg 3 is available

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#16069]
ffmpeg 3.0 has been available since Feb 15, and we should package it.

e.g. mpv has some problems loading subtitles (https://github.com/mpv-player/mpv/issues/3222) with the old version.

Also, we should clean up the ffmpeg packaging (https://github.com/NixOS/nixpkgs/issues/15930) in the process.

**Comment by vcunat** [comment]
See #13977.
