### ISSUE TITLE
packer 0.10.1 build not cooperating

### ISSUE THREAD

**Issue by Azulinho** [NixOS/nixpkgs#16079]
## Issue description

latest master build of packer fails with:

```
builder for ‘/nix/store/r6b32gawq8hlkv0kw79srxagvjwhqmci-go1.6-packer-20160507-4e5f651.drv’ failed with exit code 23
cannot build derivation ‘/nix/store/ihvwd296r5z27k98b2ikhxn7wfcdjf7m-packer-0.10.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/srdn87lbjyf1g9ry1lghqcd15yv10jw1-all.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/srdn87lbjyf1g9ry1lghqcd15yv10jw1-all.drv’ failed
```

reverting it back to the previous version 0.8.6, works fine
https://github.com/NixOS/nixpkgs/commit/3aa2992bc10d80ad9a3b3090f6b8ea5a5206f60b

### Steps to reproduce

```
git clone https://github.com/NixOS/nixpkgs.git the_thing
cd the_thing
nix-env --show-trace -f $PWD -i packer
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
nixos-version
16.03.902.a24903b (Emu)

* Nix version: (run `nix-env --version`)
nix-env --version
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.902.a24903b"

**Comment by kamilchm** [comment]
Should be ok after https://github.com/NixOS/nixpkgs/pull/16017

**Comment by rushmorem** [comment]
Closing since this is now fixed (https://github.com/NixOS/nixpkgs/pull/16017).
