### ISSUE TITLE
Ancient bitmap Lucida fonts are included when unfree packages and xserver are enabled

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#160740]
### Describe the bug
https://github.com/NixOS/nixpkgs/blob/3ddc71525fd0d12083620b8d2b181f62e73ffff0/nixos/modules/config/fonts/fonts.nix#L41-L47

Bitmap Lucida fonts are included if `config.services.xserver.enable` and `config.nixpkgs.config.allowUnfree` are enabled.

I think it would be better if these bitmap fonts were not included at all. When a website like XKCD asks for Lucida and you get these bitmap fonts it's not great.

It's confusing having an issue like this which only happens when `allowUnfree` is enabled as it's less obvious where they are coming from.

See https://discourse.nixos.org/t/cant-make-lucida-font-work-with-home-manager/14143 for some discussion.

### Steps To Reproduce
1. Enable `services.xserver.enable`
2. Enable `nixpkgs.config.allowUnfree`
3. You now have bitmap lucida fonts

### Expected behavior
Never include these fonts by default.  
Maybe also add an option to the fonts module to allow disabling the fonts that get included if `xserver.enable` is set.

### Screenshots
Here is an example of what these look like:
![](https://discourse.nixos.org/uploads/default/original/2X/c/c5d27e4466486add021860a235a9f5cc9f3dcfe8.png)

### Notify maintainers
No maintainers, last touched by @rnhmjoj 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.19-xanmod1-tt, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(root): `"nixos-21.11.333896.a640d8394f3"`
 - channels(lun): `""`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by rnhmjoj** [comment]
Those have been part of the default X.org fonts for more than 20 years. It's only recently (after I figured out they were actually unfree) that they have been gated behind `nixpkgs.config.allowUnfree`.

Probably there's old X11 software relying on those to be available, so I'm not sure if it's safe to remove. If it were for me, I would dropped them: they have a stupid license and honestly there are much better (bitmap) fonts nowadays.

**Comment by LunNova** [comment]
Another solution would be to find a better unfree Lucida font and add that to the list that gets included, if there isn't a free one?

I'm not sure where to look other than the jdk though, and having a package which downloads an entire oracle jdk to get one font seems like it'd suck.

What do other distros which don't have this problem do?

**Comment by Atemu** [comment]
I think we'd be better off disabling those fonts and waiting for someone to complain. I find it hard to believe that anyone still needs software that has a hard dependency on lucida bitmap. If there is any in Nixpkgs, it should be patched to have lucide in its font path or something.

We could also make our own bitmap "lucida" stub out of a Free bitmap font that actually looks good.

**Comment by LunNova** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/164050
