### ISSUE TITLE
NixOS build-vm does not know virtualisation.diskSize

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#16076]
### Issue description & Steps to reproduce

On current master (bdb8baf) and at least since 0b3e1f8:

```
$ nixos-rebuild build-vm -I nixpkgs=$HOME/projects/nixpkgs
building Nix...
error: The option `virtualisation.diskSize' defined in `/home/layus/projects/nix_config/inginious-server.nix' does not exist.
(use ‘--show-trace’ to show detailed location information)
error: The option `virtualisation.diskSize' defined in `/home/layus/projects/nix_config/inginious-server.nix' does not exist.
(use ‘--show-trace’ to show detailed location information)
building the system configuration...
# the build proceeds normally from here.
```

Importing `<nixos/modules/virtualisation/qemu-vm.nix>` fixes the first part, but breaks the vm build :disappointed: 

```
building Nix...
building the system configuration...
error: The option `virtualisation.writableStore' in `/home/layus/projects/nixpkgs/nixos/modules/virtualisation/qemu-vm.nix' is already declared in `/nix/store/8vs3b5l91pklnczz9rqmmdr5bw32bmnh-nixos-16.09pre82105.7465bcd/nixos/nixos/modules/virtualisation/qemu-vm.nix'.
(use ‘--show-trace’ to show detailed location information)
```

... which is kind of expected.

Importing `<nixpkgs/nixos/modules/virtualisation/qemu-vm.nix>` fixes all the warnings.

Is this the expected behavior? What has changed from one month ago where everything went fine without imports?
## Technical details
- nixos-version: 16.09.git.aa8bc97M (Flounder)
- nix-env --version: nix-env (Nix) 1.11.2
- nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion: "16.09pre82105.7465bcd"

/cc @nbp as you master the module import system :-).

**Comment by nbp** [comment]
> Is this the expected behavior? What has changed from one month ago where everything went fine without imports?

No this is not the expected behaviour.

This is indeed weird, as `qemu-vm.nix` is the only module to define `diskSize` and `writableStore` options.  Also, this module is supposed to be included by default in `vmConfig` of `nixos/default.nix`.

@layus Are you able to bisect the config `/home/layus/projects/nix_config/inginious-server.nix`, and isolate the minimal set which cause the same error?  And then bisect nixpkgs to find which commit cause this change?

**Comment by layus** [comment]
I can reproduce it with `export NIXOS_CONFIG=/path/to/minibug.nix`.

```nix
# minibug.nix
{
  virtualisation.diskSize = 1024 * 1024;
}
```
@nbp, Git bisect points at 05a36304ea812cc891a1d03a497b8ee7ce3729de, which look innocuous, but the commit contains a discussion about it triggering an infinite recursion, so maybe it induces a subtle breakage ?

**Comment by layus** [comment]
Lost interest in this one... Let's close it for now.

**Comment by nbp** [comment]
Yes, the bisect sounds wrong.
