### ISSUE TITLE
codelldb inside of vscode-lldb extension doesn't work

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#160874]
### Describe the bug
I want to use `vscode-extensions.vadimcn.vscode-lldb.adapter` (providing `codelldb`) for it's Debug Adapter support. Particularly it seems like Helix can utilize it with some early debugging support.

However, it doesn't seem to work. After adding that to my nix shell, and entering it, and trying to run it, I get:

```
[cole@porty:~/code/rust-nix-template]$ codelldb
Error: "\"/nix/store/rnqda0vmhg95ziahvl7r6y10x4xk1y6z-vscode-lldb-adapter-1.6.10/lldb/lib/liblldb.so: cannot open shared object file: No such file or directory\""
```

**Comment by colemickens** [comment]
cc: @nigelgbanks since I'm running your latest PR bumping this.

**Comment by colemickens** [comment]
I suspect that vscode-lldb's fork of lldb needs to be updated?

**Comment by colemickens** [comment]
Oh yeah, that would be because the adapter is patched-inline in the extension process and the unwrapped, useless, adapter is passed thru instead.

**Comment by colemickens** [comment]
I have some work that fixes this:

1. `codelldb` just uses regular lldb now, we can drop the "fork" with the "rust-enabled" check
2. `codelldb` tries to exec-itself in certain scenarios and must be patched so that it properly calls its wrapped version

But most of all, it seems like `lldb-vscode` is ... just built as part of `lldb` already. I'm not even sure if there's a huge point in bothering with `codelldb` and `vscode-lldb` in general.

I really wish this were less messy. `codelldb` was a hassle to figure out, `lldb-vscode` has a bad name, the repo that you find online is old and says darwin-only. yeesh.

**Comment by pearsche** [comment]
i got hit by this, but now it says
 
`Error: "\"/nix/store/wibfbvchp045fnk1kcj69x9kb694g6ix-vscode-extension-vadimcn-vscode-lldb-1.9.1/share/vscode/extensions/vadimcn.vscode-lldb/adapter/libcodelldb.so: cannot open shared object file: No such file or directory\""`

**Comment by Congee** [comment]
Actually https://github.com/NixOS/nixpkgs/pull/236915 only resolves the libcodelldb.so issue. The original issue of missing liblldb.so still exists somewhat. A working `codelldb` binary can be found at
> $(nix show-derivation github:NixOS/nixpkgs/nixpkgs-unstable#vscode-extensions.vadimcn.vscode-lldb | jq -r '.[].outputs.out.path')/share/vscode/extensions/vadimcn.vscode-lldb/adapter/codelldb

**Comment by mrcjkb** [comment]
@colemickens why was this closed? I don't think it's fixed.
