### ISSUE TITLE
Bug report instructions are flawed

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#16081]
You claim:

```
#!/bin/sh
if ! ~/.nix-profile/bin/nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion; then 
  echo Flawed
fi
```
should not output Flawed. 

However, I get:
```
error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I)
```
from the Nix command, (and obviously, it will also print Flawed in the script above)

## Technical details

* System: Ubuntu LTS 14.04.3
* `~/.nix-profile/bin/nix-shell --version`:  nix-shell (Nix) 1.11.2

The manual talks about setting `NIX_PATH`, but it seems rather odd that one *has* to set it, since one is already using channels to begin with. Additionally, the documentation also talks about github URLs, which don't actually exist anymore (because the dropped the archive feature, which also looks a bit sloppy). 

My recommendation would be to use whatever URL is associated with the channel configured by the user if `NIX_PATH` is not set. This is also a consistency issue, since e.g. `nix-env -i nix` does work without annoying the user about `NIX_PATH`.

**Comment by danbst** [comment]
After you installed Nix, there was a message to source `~/.nix-profile/etc/profile.d/nix.sh`. Did you do it?

Nix installer adds this to ~/.bash_profile

```
if [ -e /home/ec2-user/.nix-profile/etc/profile.d/nix.sh ]; then . /home/ec2-user/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
```

which in result sets $NIX_PATH
```
if [ -n "$HOME" ]; then
    # Append ~/.nix-defexpr/channels/nixpkgs to $NIX_PATH so that
    # <nixpkgs> paths work when the user has fetched the Nixpkgs
    # channel.
    export NIX_PATH=${NIX_PATH:+$NIX_PATH:}nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs
```

This is at least for me.
