### ISSUE TITLE
`mpv` is missing features on Darwin

### ISSUE THREAD

**Issue by leungbk** [NixOS/nixpkgs#160828]
### Describe the bug
1. Pressing `f` to go into full-screen mode doesn't work (other keys like `q` work as normal).
2. When not in full screen, the title bar and the quit/minimize/maximize buttons should not be visible under most circumstances; this is the behavior I observe when using `mpv` via Homebrew. However, a Nix-installed version of `mpv` does show the title bar and such.

### Steps To Reproduce
`nix-shell -p --pure mpv` on `aarch64-darwin`.

### Expected behavior
1. `f` should go into full-screen mode
2. Title bar and friends should not generally be visible even when not in full-screen mode

### Notify maintainers
@marsam 

He seems to be the most recent contributor to the `mpv` recipe who uses Darwin. I know he's not listed as a maintainer for `mpv`, but I don't think anybody on the maintainer list actually uses Darwin.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"darwin, home-manager-22.05pre347261.6d8215281b2, nixpkgs-22.05pre345869.46821ea01c8"`
 - channels(brian): `"darwin, home-manager-22.05pre347261.6d8215281b2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by veprbl** [comment]
This is probably because we use the deprecated cocoa backend, because we don't have swift: #37473

**Comment by Enzime** [comment]
Before Swift support is added to Nixpkgs, you can use IINA in the meantime which is built around libmpv and currently available in Nixpkgs.

https://iina.io/

**Comment by Atemu** [comment]
Note that our IINA is a binary package.
