### ISSUE TITLE
Rust: error: the lock file Cargo.lock needs to be updated but ...

### ISSUE THREAD

**Issue by tu-maurice** [NixOS/nixpkgs#160975]
### Describe the bug

I'm trying to update fishnet to version 2.5.1 (see commit 861c24c96a7fcc1197c4385a54469dc1553b0fd1) but it fails to build with the following message. The --frozen is obviously there for a reason, but why does it try to update Cargo.lock? How can I avoid that.

```
+ env CC_x86_64-unknown-linux-gnu=/nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/c++ CC_x86_64-unknown-linux-gnu=/nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/c++ cargo build -j 3 --target x86_64-unknown-linux-gnu --frozen --release
error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

### Steps To Reproduce
1. Checkout https://github.com/tu-maurice/nixpkgs/tree/fishnet-2.5.1
2. `nix-build -A fishnet`
3. ???

### Expected behavior
Cargo.lock should not need an update when using the dependencies that where just downloaded using the Cargo.lock in the first place.

### Additional context
Cargo.lock in question: https://github.com/lichess-org/fishnet/blob/v2.5.1/Cargo.lock

### Notify maintainers
@Ericson2314 has the latest commit in `pkgs/build-support/rust/build-rust-package/default.nix`

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos"`
 - channels(madmaurice): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jyooru** [comment]
This happens when Cargo.lock is out of date in the repository.

You will need to apply this patch to update Cargo.lock:

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 963e40e..fb76d78 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -230,7 +230,7 @@ dependencies = [

 [[package]]
 name = "fishnet"
-version = "2.5.1-dev"
+version = "2.5.1"
 dependencies = [
  "arrayvec",
  "atty",
```

**Comment by tu-maurice** [comment]
That worked marvelously! Thank you!
