### ISSUE TITLE
python3Packages.uvloop is broken on aarch64-darwin

### ISSUE THREAD

**Issue by Sciencentistguy** [NixOS/nixpkgs#160904]
`python3Packages.uvloop` is broken on aarch64-darwin. This breaks packages like `black`

Relevant hydra build: https://hydra.nixos.org/build/167153571

Log from my own machine: https://gist.github.com/Sciencentistguy/13484deadebb26d0b41d1e67893d7ac3

### Notify maintainers

@costrouc 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0`
 - channels(jamie): `"nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by prusnak** [comment]
Let's disable the broken test for now : https://github.com/NixOS/nixpkgs/pull/161348
