### ISSUE TITLE
Package quarto-cli

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#160911]
**Project description**
[Quarto-cli](https://github.com/quarto-dev/quarto-cli) is a CLI for Quarto, a package for scholarly publishing built on Pandoc.  

**Metadata**

* homepage URL: https://quarto.org/
* source URL: https://github.com/quarto-dev/quarto-cli
* license: gpl2+ 
* platforms: unix, linux, darwin

**Comment by das-g** [comment]
Even though #186697 mentions adding quarto support to RStudio, it seems like it will provide also the Quarto CLI.

**Comment by leonvonrabenmond** [comment]
Has been solved in #186697
