### ISSUE TITLE
logToJournal breaks when journald is stopped and started

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#16096]
## Issue description

`services.xserver.displayManager.logToJournal` uses `systemd-cat` to achieve writing session error logs to journald. Unfortunately, this breaks when journald is restarted by stopping and starting, i.e. during `nixos-rebuild switch`. After this, all applications that try to write something to stderr immediately fail (with SIGPIPE I presume).

I suspect that's because while (usually) journald is accessed through its own API or `syslog(3)` its restarts are handled gracefully -- however, what `systemd-cat` must be doing is opening some pipe or socket, `dup2`ing it into `STDERR_HANDLE` and `exec`ing the target program. This, of course, would fail when the handle is invalidated (e.g. because the target process is stopped), and there's nothing to reopen it properly.

### Steps to reproduce

1. Run gajim from the system menu or somehow else inside X11, _not_ from a terminal where stderr and stdout are hooked. I use `XMonad.Prompt`.
2. Observe that it works.
3. Run:
```
# systemctl stop systemd-journald
# systemctl start systemd-journald
```
4. Try running gajim again. Observe that it fails.
5. Try running gajim from a terminal. Observe success.

Not only gajim of course, other apps start to misbehave in strange ways. For example taffybar fails after some time running like this and I cannot longer restart it from XMonad prompt, only from a terminal.

This can be workarounded by setting `logToJournal = false`.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 16.09.git.5607ab6 (Flounder)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.12pre4523_3b81b26
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 16.09.git.5607ab6M

cc @edolstra

**Comment by abbradar** [comment]
Maybe we want to disable this by default for 16.09 to avoid people running into this, and document that there is an issue?

**Comment by abbradar** [comment]
I've experimented more, thinking to fix this before a release. I see two ways:

1. Conservative: `services.xserver.displayManager.logToJournal = false`.
2. Better but can have issues: `systemd.services.systemd-journald.restartIfChanged = false`.

@edolstra , what do you think? I'll go the first way if it's not agreed the second is okay -- cc @domenkozar  (ping me before a release to push the patch, please).

**Comment by groxxda** [comment]
Any idea why running `systemd-cat` in one terminal, then `systemctl restart systemd-journal` in another does not break the `systemd-cat` in the first process? A minimal example would be helpful to see what exactly causes the error. Imo the desktop-/window-manager should log to the journal itself, so our systemd-cat is only useful for our `xsession.script`, right?

**Comment by abbradar** [comment]
It breaks, you just don't know it yet -- try running `systemd-cat cat`, entering several lines, then stopping-starting and trying to add yet another line. Stopping-starting is what `nixos-rebuild` does.

**Comment by abbradar** [comment]
Restart can also break things, but not always. I've succeeded in breaking the session after several consecutive restarts. I'm not sure if it's a race condition or something else -- either way, `stopIfChanged = false` didn't fix this.

**Comment by edolstra** [comment]
`logToJournal` is hardly special in this regard. All services that log to stdout/stderr break if you restart the journal.

**Comment by abbradar** [comment]
Indeed, that's why I think that just disabling `logToJournal` is just hiding the true cause. What do you think of `systemd.services.systemd-journald.restartIfChanged = false`? I'm not sure if it can be bad, for example when systemd updates...

**Comment by edolstra** [comment]
From the systemd 219 release notes:
```
        * systemd now provides a way to store file descriptors
          per-service in PID 1.This is useful for daemons to ensure
          that fds they require are not lost during a daemon
          restart. The fds are passed to the daemon on the next
          invocation in the same way socket activation fds are
          passed. This is now used by journald to ensure that the
          various sockets connected to all the system's stdout/stderr
          are not lost when journald is restarted. File descriptors
          may be stored in PID 1 via the sd_pid_notify_with_fds() API,
          an extension to sd_notify(). Note that a limit is enforced
          on the number of fds a service can store in PID 1, and it
          defaults to 0, so that no fds may be stored, unless this is
          explicitly turned on.
```
I guess we should set that limit to something > 0...

**Comment by edolstra** [comment]
Hm, it's already set to 1024 for systemd-journald.

**Comment by abbradar** [comment]
Hmmm, _maybe_ `journald` detects that it's restarted instead of stopped-started somehow and saves fd? That explains why restart doesn't break things always, but doesn't explain why it breaks them anyway _sometimes_...

**Comment by edolstra** [comment]
BTW, I just tested restarting `systemd-journald` while `systemd-cat` is running and the latter keeps logging just fine.

**Comment by edolstra** [comment]
And so does my xsession BTW :-)

**Comment by edolstra** [comment]
Oh, I did a `systemctl restart`. I guess `stop/start` will prevent the FDs from being saved.

**Comment by abbradar** [comment]
Well, I'm not sure why I had occasional failures even with restarts, but let's say that I just had a bad luck then. I propose:
```
systemd.services.systemd-journald.stopIfChanged = false;
```
and also, as a bonus:
```
systemd.services.systemd-journald.restartTriggers = [ config.environment.etc."systemd/journald.conf".source ];
```

**Comment by abbradar** [comment]
(Do I understand correctly that `stopIfChanged` will make it restart instead of stop-start?)

**Comment by edolstra** [comment]
Yeah, `stopIfChanged = false` sounds like the right thing to do.

**Comment by abbradar** [comment]
I'll prepare a patch and test then. Thanks!

**Comment by abbradar** [comment]
Ugh, I think that what I really did hit was not a journald's problem but `switch-to-configuration.pl`'s:
```
 nixpkgs git:(stable) ✗ sudo nixos-rebuild switch
...
stopping the following units: systemd-journald.service
Warning: Stopping systemd-journald.service, but it can still be activated by:
  systemd-journald-dev-log.socket
  systemd-journald-audit.socket
  systemd-journald.socket
activating the configuration...
setting up /etc...
restarting the following units: systemd-journald.service
starting the following units: systemd-journald.service
 nixpkgs git:(stable) ✗ cat /etc/systemd/system/systemd-journald.service.d/overrides.conf
...
X-StopIfChanged=false

 nixpkgs git:(stable) ✗ 
```

Any ideas?

**Comment by abbradar** [comment]
Notice that journald is both stopped, restarted and started!

**Comment by abbradar** [comment]
@edolstra I think I found the source of a problem, but I need some advice. See these lines: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/switch-to-configuration.pl#L216

* Do we need to restart sockets at all? I thought that they would be "restarted" automatically when the service is restarted.
* We add a service to stop and start lists instead of a socket in line 227. I think that's a bug;
* Even if we do need to restart sockets, we don't want to do this when `X-StopIfChanged` is disabled. Therefore we probably want to move socket restarting logic under `else` (line 242).

**Comment by edolstra** [comment]
I think the main reason for stopping the socket is to ensure the (old) service doesn't get restarted via the socket before we've switched to the new configuration (which would prevent the subsequent start from doing anything). So yeah, in the case of `stopIfChanged = false`, stopping the socket is unnecessary.

Does look like a bug at line 227.

**Comment by abbradar** [comment]
Aha, I haven't thought of that (regarding service restarts while switch is in progress)! I have prepared a patch; see #19108.

**Comment by abbradar** [comment]
Backported to 16.09. Thanks @edolstra, @groxxda for help and testing!
