### ISSUE TITLE
discord update to 0.0.17

### ISSUE THREAD

**Issue by cafkafk** [NixOS/nixpkgs#161023]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: discord

current version: 0.0.16
desired version: 0.0.17

###### Notify maintainers

maintainers: 
@ldesgoui 
@MP2E 
@devins2518

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jyooru** [comment]
Already fixed in #160499.

**Comment by jyooru** [comment]
You can check what branches the update is available on using this link: https://nixpk.gs/pr-tracker.html?pr=160499
