### ISSUE TITLE
urxvtc sometimes stops working

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#16115]
## Issue description

I call `urxvtd` like [this](https://github.com/magnetophon/nixosConfig/blob/947b425761e78651d3b35c7cbc1188b4dd0df853/common.nix#L90).

After a reboot, it always works for a while, but then sometimes, when I try to run `urxvtc`, I get:

```
urxvt: can't fork, aborting.
```

Other times, I get:

```
unable to connect to the rxvt-unicode daemon: Connection refused
```

`urxvtd -q -o -f` is still running, taking up about 2G of RAM.

When I start another instance of `urxvtd`, `urxvtc` starts working again.

When I kill the original instance, all clients die, and a new (working) daemon starts. 

Idk how to troubleshoot further.
### Steps to reproduce

idk, sorry.
## Technical details
- System: 16.03.git.becde1fM (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.659.011ea84

**Comment by avnik** [comment]
Actually is a "normal" urxvtd behaviour, it have some incompatibles between running version of `urxvtd` and current `urxvtc`.  (same problem occurend in debian after urxvt upgrade).

Spawn new urxvtd is a fast and dirty solution.

More precious solution may require patching of urxvtd -- quit daemon if all terminal sessions ends (and enter into this mode by signal). Then it allow using  systemd activation and signal current (old) instance of daemon on upgrades.

**Comment by siddharthist** [comment]
@magnetophon Your first link in the issue description is broken, by the way. Press `y` on any Github page to get a versioned URL (rather than linking to `master`, which can break links).

**Comment by magnetophon** [comment]
@siddharthist Thanks, fixed now.

**Comment by siddharthist** [comment]
If this is the expected behavior of urxvtd, we might want to close this issue.
