### ISSUE TITLE
Steam not loading Nvidia Vulkan libs

### ISSUE THREAD

**Issue by tfmoraes** [NixOS/nixpkgs#161136]
### Describe the bug

After this PR https://github.com/NixOS/nixpkgs/pull/158276 the Steam helper is not loading the Nvidia Vulkan libs inside the Steam environment. And because of that Proton is slow.

### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - nixpkgs: `/etc/nixpkgs`

```

**Comment by jicksaw** [comment]
Discussed at: https://github.com/NixOS/nixpkgs/pull/157907#issuecomment-1042342710

**Comment by Atemu** [comment]
Is this still an issue?

**Comment by tfmoraes** [comment]
Nope, I'll close it.
