### ISSUE TITLE
wvdial: utils/wvtask.cc:304: static int WvTaskMan::yield(int): Assertion `*current_task->stack_magic == WVTASK_MAGIC' failed.

### ISSUE THREAD

**Issue by makefu** [NixOS/nixpkgs#16113]
## Issue description

with the latest nixpkgs stable channel wvdial stopped working for me as it raises an assertion when trying to connect my umts adapter:
`wvdial: utils/wvtask.cc:304: static int WvTaskMan::yield(int): Assertion `*current_task->stack_magic == WVTASK_MAGIC' failed.`

using the binary from channels/15.09 this issue does not occur.

Problem may be related to https://bugs.archlinux.org/task/48390
### Steps to reproduce
1. use latest nixos stable channel (16.03)
2. get Ericsson H5321 umts card and install into laptop
3. configure `/etc/wvdial.conf`: 

```
/etc/wvdial.conf 
[Dialer Defaults]
PPPD PATH = /nix/store/7kqd7nkaqvnl8q48wg9s1r7n1vbmpqgg-ppp-2.4.7/sbin/pppd
Phone = *99***1#
Dial Command = ATDT
Modem = /dev/serial/by-id/usb-Lenovo_H5321_gw_2D5A51BA0D3C3A90-if01
Baud = 460800
Init1 = AT+CGDCONT=1,"IP","pinternet.interkom.de","",0,0
Init2 = ATZ
Init3 = ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
ISDN = 0
Modem Type = Analog Modem
Username = netzclub
Password = netzclub
Stupid Mode = 1
Idle Seconds = 0
```
1. `wvdial -n`
## Technical details
- System: 16.03.git.63b9785 (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.git.63b9785
- UMTS Card: `0bdb:1926 Ericsson Business Mobile Networks BV`
### Error Log:

```
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: AT+CGDCONT=1,"IP","pinternet.interkom.de","",0,0
AT+CGDCONT=1,"IP","pinternet.interkom.de","",0,0
OK
--> Sending: ATZ
ATZ
OK
--> Sending: ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
ATQ0 V1 E1 S0=0 &C1 &D2 +FCLASS=0
OK
--> Modem initialized.
--> Sending: ATDT*99***1#
--> Waiting for carrier.
ATDT*99***1#
wvdial: utils/wvtask.cc:304: static int WvTaskMan::yield(int): Assertion `*current_task->stack_magic == WVTASK_MAGIC' failed.
```

**Comment by makefu** [comment]
with nixos-unstable @125ffff the problem persists.

**Comment by globin** [comment]
`wvdial` has been removed for 17.09 as it has not been maintained upstream nor has received care in nixpkgs.
