### ISSUE TITLE
NixOS desktop tests

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#16124]
I updated the kde5 test some time ago and since then it's always failing: http://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.sddm-kde5.x86_64-linux

I believe the test machine needs more power to make the test pass the 900s limit. Here I need VM acceleration and the test passes in 1m50.398s.

What can be done about this? Should the time limit be increased or is it possible to make hydra run the test on a more powerful machine?

Another option is to simplify or remove the test but I think the test is good to have if we want to move from kde4 to kde5 in the LiveCD.

**Comment by joelmo** [comment]
See #15866

**Comment by grahamc** [comment]
SDDM tests are passing now :)
