### ISSUE TITLE
fetchgit unable to handle repositories at `file:///` URLs

### ISSUE THREAD

**Issue by savannidgerinel** [NixOS/nixpkgs#161282]
### Describe the bug

`fetchgit` is unable to find or clone a repository if that repository is on my local filesystem. I have determined that `nix-fetch-git` is running in a very stripped-down environment and is unable to even see things like my /home and /var directories.

### Steps To Reproduce
1. Create this file as `test.nix`, replacing the repository with anything you have on your local filesystem:
  ```
let
  pkgs = import <nixpkgs> {};
in
pkgs.stdenv.mkDerivation {
  name = "fluent-ergonomics";
  src = pkgs.fetchgit {
    url = "file:///home/savanni/src/fluent-ergonomics/";
    rev = "d6adea30d2edfb8c7049459ff1e640f0c4def487";
    sha256 = "17vdf91caivz5afg51azk1lg7fgph3mjm6kbvszvkgvjxb4gw0pa";
  };
  dontUnpack = true;
  dontBuild = true;
}
  ```
2. Install it: `nix-env -i -f ./test.nix`

### Expected behavior

I expect it to find and clone my repository.

### Additional context

I built the above minimal example and included several sets of outputs, including outputs from embedding `ls -l /` into `nix-prefetch-git` on my local copy of the nixpkgs repository:

https://gist.github.com/savannidgerinel/fa5c0db1e7a5227a9fd4fee5d9481d60

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11, NixOS, 21.05.4719.0fd9ee1aa36 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20211006_53e4794`
 - channels(root): `"home-manager-21.05, nixos-21.05.4719.0fd9ee1aa36, pkgs-19.03-19.03.173691.34c7eb7545d, pkgs-19.09-19.09.2522.75f4ba05c63, pkgs-20.03-20.03.3330.1db42b7fe38, pkgs-20.09-20.09.4407.1c1f5649bb9, pkgs-21.05-21.05.4719.0fd9ee1aa36, pkgs-21.11-21.11.336045.4afca382d80, unstable-22.05pre356180.d5f23787297, pkg-20.09-20.09.2205.65c9cc79f1d"`
 - channels(savanni): `"local"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sternenseemann** [comment]
I'd say this is intended — nixpkgs fixed output derivations are allowed to access the network, but not the local file system, since there is no good reason for nixpkgs itself why they should. For your purposes, I'd recommend using `builtins.fetchGit` which can fetch local repositories, e. g. `builtins.fetchGit /home/savanni/src/fluent-ergonomics` should do what you want exactly.
