### ISSUE TITLE
bundlerEnv doesn't behave like most builders

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#16125]
Namely, I can't call `overrideDerivation` on its to inject patches into it.

Not sure what is missing, but it would be nice if that worked. cc @cstrahan @pikajude 

(also, I could've sworn I filed a ticket on this in the past but I can't find it now. Apologies if it's a duplicate!)

**Comment by cstrahan** [comment]
Not sure when I can improve this, but I'll tentatively assign it to myself so it stays on my radar.

**Comment by Profpatsch** [comment]
triage: any progress or changes?
