### ISSUE TITLE
dotnet-ef

### ISSUE THREAD

**Issue by kirinnee** [NixOS/nixpkgs#161332]
**Project description**
_describe the project a little_

**Metadata**

* homepage URL: https://docs.microsoft.com/en-us/ef/core/
* source URL: https://github.com/dotnet/efcore
* license: MIT
* platforms: unix, linux, darwin

**Comment by mdarocha** [comment]
Is it necessary to package it in Nix? [Installing it as dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install) works fine.

**Comment by kirinnee** [comment]
> Is it necessary to package it in Nix? [Installing it as dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install) works fine.

True, but dotnet tooling path needs to be added and multiple .NET version is a little messy. Lastly, CI becomes complicated when using nix-shell to execute CI

**Comment by mdarocha** [comment]
I personally use the [dotnet tool manifest](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use), along with `dotnet tool restore`. Won't that fit your use case?

**Comment by kirinnee** [comment]
> I personally use the [dotnet tool manifest](https://docs.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use), along with `dotnet tool restore`. Won't that fit your use case?

Yes, this will fit my use case!

I did not know this feature existed. Thank you!
