### ISSUE TITLE
i2pd: no support for Yggdrasil only router configuration

### ISSUE THREAD

**Issue by ne9z** [NixOS/nixpkgs#161367]
### Describe the bug
NixOS has no configuration options for yggdrasil-only i2p router, as described [in documentation](https://i2pd.readthedocs.io/en/latest/tutorials/yggdrasil-only-mode/).

I have configured the server as described [here](https://gist.github.com/ne9z/912773cba81fd638b8541b198f1a8479).

### Steps To Reproduce

See [here](https://gist.github.com/ne9z/912773cba81fd638b8541b198f1a8479).

### Expected behavior
User should be able to use i2pd with yggdrasil only.

### Notify maintainers

@edwtjo
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.99, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ne9z** [comment]
Currently the option for [encryted leasesets](https://geti2p.net/en/blog/post/2021/09/07/Level-Up-Encrypted-Leasesets), [for i2pd](https://github.com/PurpleI2P/i2pd/wiki/Publish-encrypted-LeaseSet) is also missing.

**Comment by kurnevsky** [comment]
I added yggdrasil settings here: https://github.com/NixOS/nixpkgs/pull/158346

**Comment by ne9z** [comment]
@kurnevsky Thanks!  Unfortunately i2pd [needs to be updated immediately](https://github.com/PurpleI2P/i2pd/issues/1734) to stop crashing.
