### ISSUE TITLE
TS3Client crashes on accessing the microphone

### ISSUE THREAD

**Issue by Shawn8901** [NixOS/nixpkgs#161395]
### Describe the bug
After switching from 21.11 to unstable and a clean reboot ts3client crashes as soon as it tries to access the microphone.

### Steps To Reproduce
1. Switch to current unstable
2. open ts3client
3. connect to a server or click Options -> Recording  ->Test 

### Expected behavior
Not crash when using microphone

### Screenshots
Attached the coredump i am receiving.
[coredump.txt](https://github.com/NixOS/nixpkgs/files/8118418/coredump.txt)

### Additional context
I am using pipewire in this context, but i can't circumscribe the issue on pipewire as other applications still work and are able to record without issues, also switching pipewire out and use pulseaudio seem not to solve the issue.

I tried to overlay the package with libForQt512 (just playing around with it) as one of the differences between stable and unstable are version changes on qt libraries. But that did not fix anything.

I have also tried the flatpack version, to check it there is something wrong with my pipewire config, but the flatpack version runs fine.

Switching back the nixpkg from unstable to 21.11 and rebooting fixes the issue, so at least would tackle it down to changes related with changes in unstable.

As stable and unstable ship the same ts3client version it has to be somehow related in between, or (hopefully not) just on my machine. I would not rule out that the issue is somewhere on my side. 

### Notify maintainers
@nathanielbaxter @lukegb

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[shawn@pointalpha:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.101, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`

```

**Comment by Atemu** [comment]
Running the version of a previous nixpkgs works just fine, even with an up-to-date environment. It must be a problem with the ts3 drv itself. I'll hopefully have time to run a bisect later.

**Comment by Atemu** [comment]
Bad is 60f9a9c262a69f1a490d8596d7c4fc2b401b77e0 which is a staging-next merge.

Bisecting staging-next now...

**Comment by Atemu** [comment]
Bad is 184d6ba76bc9db589223ba522027533c6c55f015.

(Note: Injecting a cached qtwebengine saves a lot of time here and doesn't falsify results.)
