### ISSUE TITLE
nixos-21.11.336103.40ef692a55b: linuxPackages_rt_5_10 fails to build

### ISSUE THREAD

**Issue by unclechu** [NixOS/nixpkgs#161447]
### Describe the bug

Real-time kernel fails to build with the latest release (2022-02-22T13:35:20Z) of “nixos” channel:

https://releases.nixos.org/nixos/21.11/nixos-21.11.336103.40ef692a55b

```
GOT: make[1]: Leaving directory '/build/linux-5.10.78/build'
GOT: make: Leaving directory '/build/linux-5.10.78'
error: unused option: BPF_UNPRIV_DEFAULT_OFF
warning: unused option: DEBUG_STACKOVERFLOW
warning: unused option: EXT4_ENCRYPTION
warning: unused option: F2FS_FS_ENCRYPTION
warning: unused option: RCU_PERF_TEST
warning: unused option: RT_GROUP_SCHED
warning: unused option: TRANSPARENT_HUGEPAGE
warning: unused option: TRANSPARENT_HUGEPAGE_ALWAYS
warning: unused option: TRANSPARENT_HUGEPAGE_MADVISE
warning: unused option: XEN_SCRUB_PAGES
warning: unused option: XEN_SELFBALLOONING
warning: unused option: XEN_STUB
warning: unused option: XEN_TMEM
builder for '/nix/store/h19rqc84lw3dkc5al9vih30fg31cbkak-linux-config-5.10.78-rt55.drv' failed with exit code 255
cannot build derivation '/nix/store/9yhc7mjhhrxvik00jkqsd8qr3b54h56m-linux-5.10.78-rt55.drv': 1 dependencies couldn't be built
```

### Steps To Reproduce

1. Set `nixos` channel to https://releases.nixos.org/nixos/21.11/nixos-21.11.336103.40ef692a55b (latest release at this moment)
1. `boot.kernelPackages = lib.mkForce pkgs.linuxPackages_rt_5_10`
2. `nixos-rebuild`

### Expected behavior

Real-time kernel builds and boots successfully.

### Additional context

My config where this real-time kernel is used (just in case): https://github.com/unclechu/nixos-config/blob/e739f03cadd43076255c9e004c19d8fc2fa7c9ff/configuration-audio.nix

### Notify maintainers

@TredwellGit
@ma27
@nequissimus
@alyssais
@thoughtpolice

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.5, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos, nixos-unstable"`
 - channels(wenzel): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/161287

**Comment by TredwellGit** [comment]
https://github.com/NixOS/nixpkgs/pull/161592
