### ISSUE TITLE
PETSc broken on aarch64-darwin

### ISSUE THREAD

**Issue by johnbcoughlin** [NixOS/nixpkgs#161450]
### Describe the bug
Building PETSc fails on aarch64-darwin.

### Steps To Reproduce
1. Check we're on a recent commit
```
> nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"22.05pre356557.74b10859829"
```
2. Try to build the default PETSc derivation: `nix-shell -p "petsc"` The `./configure` step fails with the message "Cannot determine Fortran module include flag". If we rebuild the derivation with 
```
nix-build /nix/store/swcdfv4pn4g23gsg1jppn8xs8algrj1s-petsc-3.16.4.drv --keep-failed
```
and check the `configure.log` file, there are errors similar to what is seen in [#158730](https://github.com/NixOS/nixpkgs/issues/158730).

I am about to submit a fix similar to https://github.com/NixOS/nixpkgs/pull/158992.

### Expected behavior
The derivation should build.

### Additional context
aarch64-darwin system.

### Notify maintainers
@cburstedde 

### Metadata
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixpkgs-21.11pre332093.7fad01d9d5a"`
 - channels(jack): `"nixos-22.05pre356435.7f9b6e2babf, nixpkgs-22.05pre356557.74b10859829"`
 - nixpkgs: `/Users/jack/.nix-defexpr/channels/nixpkgs`
```

**Comment by prusnak** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/161451

Thanks!
