### ISSUE TITLE
Nvidia GPU support broken in LXC/LXD

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#161431]
### Describe the bug
Using `nvidia.runtime=true` with `lxc launch` makes LXC unable to create the container.

### Steps To Reproduce
1. `virtualisation.lxd.enable = true;`
2. `lxc launch ubuntu:20.04 mycontainer -c nvidia.runtime=true`

```console
$ lxc launch ubuntu:20.04 mycontainer -c nvidia.runtime=true
Creating mycontainer
Starting mycontainer
Error: Failed to run: /nix/store/dfqrhkf2vr3gqmaxn61h3gqg3np1wpdi-lxd-4.20/bin/.lxd-wrapped forkstart mycontainer /var/lib/lxd/containers /var/log/lxd/mycontainer/lxc.conf:
Try `lxc info --show-log local:mycontainer` for more info

$ lxc info --show-log local:mycontainer
Name: mycontainer
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/02/22 22:45 GMT
Last Used: 2022/02/22 22:45 GMT

Log:

lxc mycontainer 20220222224534.857 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1251 - No such file or directory - Failed to fchownat(40, memory.oom.group, 65536, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc mycontainer 20220222224534.939 ERROR    conf - conf.c:run_buffer:321 - Script exited with status 1
lxc mycontainer 20220222224534.939 ERROR    conf - conf.c:lxc_setup:4381 - Failed to run mount hooks
lxc mycontainer 20220222224534.939 ERROR    start - start.c:do_start:1274 - Failed to setup container "mycontainer"
lxc mycontainer 20220222224534.939 ERROR    sync - sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 4)
lxc mycontainer 20220222224534.942 WARN     network - network.c:lxc_delete_network_priv:3617 - Failed to rename interface with index 0 from "eth0" to its initial name "veth646f7af1"
lxc mycontainer 20220222224534.942 ERROR    start - start.c:__lxc_start:2068 - Failed to spawn container "mycontainer"
lxc mycontainer 20220222224534.942 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:867 - Received container state "ABORTING" instead of "RUNNING"
lxc mycontainer 20220222224534.942 WARN     start - start.c:lxc_abort:1038 - No such process - Failed to send SIGKILL via pidfd 41 for process 8652
lxc 20220222224540.235 ERROR    af_unix - af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20220222224540.236 ERROR    commands - commands.c:lxc_cmd_rsp_recv_fds:127 - Failed to receive file descriptors
```

### Expected behavior
I should be able to use my GPU in LXC containers: https://blog.simos.info/running-x11-software-in-lxd-containers/

### Additional context
I am sick of trying to work out how to debug the problem, but if someone who understands LXC/LXD knows how to get it to actually tell me what's going wrong, I can keep trying.

Here's how far I got.

Firstly, you need to set $LXD_LXC_HOOK to tell LXD where the LXC hooks are (https://github.com/lxc/lxd/blob/7cf7ff1403dab27ddb3798aa5ce9c48431401e36/lxd/instance/drivers/driver_lxc.go#L1041), otherwise it will look in /usr/share/lxc/hooks, which doesn't exist, and you'll see "The NVIDIA LXC hook couldn't be found". I did this by adding `--set LXD_LXC_HOOK ${lxc}/share/lxc/hooks` to the `wrapProgram` invocation in lxd's postInstall.

Next, you'll find that it fails because `nvidia-container-cli` isn't available, and you'll see "The NVIDIA container tools couldn't be found". This is in nixpkgs, but it's not exposed publicly anywhere; I get the feeling you're meant to use `mkNvidiaContainerPkg` to get at it, but because I couldn't find _any_ documentation indicating sensible values to use for `containerRuntimePath` and `configTemplate`, I just added `(callPackage /path/to/the/nixpkgs/libnvidia-container {})` to the `makeBinPath` call in the lxd derivation.

Then you're basically as far as I got! I also added `config.security.wrapperDir` to $PATH, because lxc was complaining about not being able to find newuidmap and newgidmap, as well as `glibc` to the `makeBinPath` call because it seemed to want `getent`, but neither helped the fundamental problem, and I can't work out how to make LXC or LXD print any more useful debugging information (like "the output of the hook that's failing"...)

### Notify maintainers

@fpletz @wucke13 @marsam 

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.101, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(ash): `"home-manager-21.11, nixos-unstable-22.05pre356435.7f9b6e2babf"`
 - channels(root): `"nixos-21.11.336103.40ef692a55b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mt-caret** [comment]
I spent some time a while back trying to get this to work, and I have something which successfully gets `nvidia-smi` working inside of a ubuntu lxd container in NixOS:

```nix
{ config, pkgs, ... }:
let
  libnvidia-container = with pkgs; callPackage "${nixpkgs}/pkgs/applications/virtualization/libnvidia-container" { };
in
{
  systemd.services.lxd = {
    environment =
      let
        path = pkgs.lib.makeBinPath
          (with pkgs; [ which libnvidia-container util-linux ]);
        hook =
          (
            pkgs.srcOnly {
              name = "lxc-hooks";
              src = "${pkgs.lxc}/share/lxc/hooks";
              nativeBuildInputs = [ pkgs.makeWrapper ];
            }
          ).overrideAttrs (
            oldAttrs: rec {
              installPhase = ''
                ${oldAttrs.installPhase}
                wrapProgram $out/nvidia --prefix PATH : ${path}
              '';
            }
          );
      in
      {
        LXD_LXC_HOOK = "${hook}";
      };
  };

  virtualisation = {
    lxd = {
      enable = true;
      package =
        (
          pkgs.lxd.overrideAttrs (
            oldAttrs: {
              postPatch = ''
                ${oldAttrs.postPatch}
                substituteInPlace lxd/instance/drivers/driver_lxc.go \
                  --replace "nvidia-container-cli" "${libnvidia-container}/bin/nvidia-container-cli"
              '';
            }
          )
        );
    };
    lxc.lxcfs.enable = true;
  };
}
```

Note that putting this into a file and including it in your `imports` won't work, since `nixpkgs` needs to come from somewhere. I use flakes, so pass in the `nixpkgs` from the inputs, but if you don't use flakes `<nixpkgs>` should work.

This probably should be all included in the lxd module so people can just toggle this on and off, but I don't have a bunch of time working on this, so please feel free to take this and create a PR!

**Comment by adamcstephens** [comment]
I spent some time looking into this. While I haven't tested the example code, it does look like it may work for fixing the `nvidia.runtime` option.

That said, the GPU will technically work without `nvidia.runtime=true` as that just *Controls whether to pass the host NVIDIA and CUDA runtime libraries into the instance*

I was able to get a successful connection to the host GPU with the following steps:
`lxc config device add mycontainer gpu gpu`
2. `NIXPKGS_ALLOW_UNFREE=1 nix shell nixpkgs#linuxKernel.packages.linux_6_1.nvidia_x11 --impure`

This means you have to manage the runtime separately. I will come back after I have a chance to test the `nvidia.runtime` support fully.

**Comment by adamcstephens** [comment]
@mt-caret How are you accessing `nvidia-smi`? Was your snippet enough to expose `nvidia-smi` into the container? Or are you installing the nix package in the container?

**Comment by adamcstephens** [comment]
I realize now that others are probably using non-nixos as guests. Given that `nvidia-runtime=true` installs the runtime to `/usr/lib64`, it would likely only be used by non-nix packages anyway.

**Comment by shadowpsi** [comment]
> I spent some time a while back trying to get this to work, and I have something which successfully gets `nvidia-smi` working inside of a ubuntu lxd container in NixOS:


Was wondering if you could assist. Been trying to get this to work but I get:
```
         at /nix/store/y7q5xxdjsili4gw5jnzrjxzj8pykqdx4-source/modules/lxd/default.nix:39:15:

           38|             oldAttrs: {
           39|               postPatch = ''
             |               ^
           40|                 ${oldAttrs.postPatch}

       error: attribute 'postPatch' missing

       at /nix/store/y7q5xxdjsili4gw5jnzrjxzj8pykqdx4-source/modules/lxd/default.nix:40:19:

           39|               postPatch = ''
           40|                 ${oldAttrs.postPatch}
             |                   ^
           41|                 substituteInPlace lxd/instance/drivers/driver_lxc.go \
```

**Comment by mt-caret** [comment]
It's been a while since I last used this, but perhaps `oldAttrs.postPatch` no longer exists? Perhaps change that line to something that is more graceful[^1] like `oldAttrs.postPatch or ""`.

[^1]: https://discourse.nixos.org/t/how-to-gracefully-deal-with-missing-attributes/5407/2

**Comment by adamcstephens** [comment]
`lxd` is now a wrapper around `lxd-unwrapped` so the snippet above will no longer work. An (untested) solution could be

```nix
virtualisation = {
    lxd = {
      enable = true;
      package =
        pkgs.lxd.override {
          lxd-unwrapped = pkgs.lxd-unwrapped.overrideAttrs (
            oldAttrs: {
              postPatch = ''
                ${oldAttrs.postPatch}
                substituteInPlace lxd/instance/drivers/driver_lxc.go \
                  --replace "nvidia-container-cli" "${libnvidia-container}/bin/nvidia-container-cli"
              '';
            }
          )
        };
    };
```

Or you can overlay to update `lxd-unwrapped`

**Comment by adamcstephens** [comment]
Ideally we could solve this directly in the wrapper without having to patch the source. I don't have an nvidia GPU anymore and rarely use non-NixOS guests, so if someone else wants to work on it please feel free. 

Here was my previous attempt on my now slowly bitrotting repo: https://github.com/adamcstephens/lxd-nixos/pull/2/files (Don't use this repo, most of this work has moved or is moving directly into nixpkgs)

**Comment by shadowpsi** [comment]
> `lxd` is now a wrapper around `lxd-unwrapped` so the snippet above will no longer work. An (untested) solution could be

Thank you very much. That did the trick

**Comment by mt-caret** [comment]
For posterity, since the LXD nixos module points to `lxd` instead of `lxd-unwrapped`, you need to make sure to correctly override things in a slightly different way:
```nix
  virtualisation = {
    lxd = {
      enable = true;
      package = pkgs.lxd.override {
        lxd-unwrapped = pkgs.lxd-unwrapped.overrideAttrs (
          oldAttrs: {
            postPatch = ''
              ${oldAttrs.postPatch}

              substituteInPlace lxd/instance/drivers/driver_lxc.go \
                --replace "nvidia-container-cli" "${libnvidia-container}/bin/nvidia-container-cli"
            '';
          }
        );
      };
    };
    lxc.lxcfs.enable = true;
  };
```

**Comment by adamcstephens** [comment]
It looks like incus (and lxd) will try to find `nvidia-container-cli` in the path. There's no need to modify the source recompile the unwrapped version. You could try something like this, but I haven't tested it.

```
systemd.services.lxd.path = [ pkgs.libnvidia-container ];
```

Ideally this should just be added to the wrapper or as a module option. Feel free to submit a PR or stop by #lxc:nixos.org to discuss.

**Comment by adamcstephens** [comment]
This should be fixed in Incus, so I'm going to mark this closed. 

If someone wants to open a pull request against the LXD module, I'll review it, but I encourage all users to migrate to Incus if possible.
