### ISSUE TITLE
`emacsPackages.map` fails due to hash mismatch

### ISSUE THREAD

**Issue by drmrcol** [NixOS/nixpkgs#161544]
## Issue description

`nixos-rebuild switch --upgrade` fails due to hash mismatch

```
hash mismatch in fixed-output derivation '/nix/store/840nz9r58dw9nqqnp14x8pcfkhmic3k8-map-3.2.1.tar':
  wanted: sha256:1vy231m2fm5cgz5nib14ib7ifprajhnbmzf6x4id48h2491m1n24
  got:    sha256:1zj0y3nvkrd2v43za214xr3h9z6wyp7r5s6nf5g1pj272yb871d1
```

### Steps to reproduce

nixos-rebuild switch --upgrade

## Technical details

% nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336103.40ef692a55b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
That's probably something from your config instead of nixpkgs as I can't find a package called map in our repo

**Comment by hqurve** [comment]
@drmrcol In the future, it might be more helpful if you post what you believe may have caused the issue or instead share the part of your config which when included causes the issue.

I got lucky by grepping the hash and it showed up [here](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/editors/emacs/elisp-packages/elpa-generated.nix#L2332) and can be accessed by `emacsPackages.map`. Apparently the hash changed since on a recent commit to master  the only change was to the hash (https://github.com/NixOS/nixpkgs/commit/1dc68f203cc0d495dcd271d973590511adb1aaa6). It currently builds on master but not on nixos21.11

Here might be a possibly related issue where emacs packages hashes change. https://github.com/NixOS/nixpkgs/issues/75714  (I dont know if this is something we need to live with)

**Comment by drmrcol** [comment]
thank for the help to identify the problem

does it mean that this update will be ported from master to 21.11, or is it better for me to switch to master?

**Comment by drmrcol** [comment]
@AndersonTorres a few days ago you have commited a change (https://github.com/NixOS/nixpkgs/commit/1dc68f203cc0d495dcd271d973590511adb1aaa6) that fixes hashes of some emacs packages from elpa.gnu.org to master.  Could you also add the changes to 21.11 so that your fix is included in the stable branch. Thanks!

**Comment by drmrcol** [comment]
@AndersonTorres thx :green_heart:

**Comment by drmrcol** [comment]
@AndersonTorres, I'm afraid that the issue have not been fixed. https://github.com/NixOS/nixpkgs/pull/161753 did not contain update to the relevant emacs package (map).

See the hashes from both branches:
- https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/editors/emacs/elisp-packages/elpa-generated.nix#L2332 has 1vy231m2fm5cgz5nib14ib7ifprajhnbmzf6x4id48h2491m1n24
- https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/elpa-generated.nix#L2422 has 1zj0y3nvkrd2v43za214xr3h9z6wyp7r5s6nf5g1pj272yb871d1

thx in advance

**Comment by drmrcol** [comment]
Perhaps useful: the commit that was referenced (https://github.com/NixOS/nixpkgs/commit/1dc68f203cc0d495dcd271d973590511adb1aaa6) is really quite different from the changes that were merged in an attempt to fix this issue (https://github.com/NixOS/nixpkgs/pull/161753/files)

**Comment by AndersonTorres** [comment]
Yes, I have upgraded Emacs packages and backported it. I will look at it again.

**Comment by AndersonTorres** [comment]
Oh, I have noticed. I put it on release-21.11, not nixos-21.11.

**Comment by drmrcol** [comment]
@AndersonTorres , perhaps I misunderstand something, but if I look at your branch that you are trying to merge, it has the wrong hash for `emacsPackages.map`. Could you confirm? If yes, the your MR will not fix the problem, right?

1. Original error message

```
hash mismatch in fixed-output derivation '/nix/store/840nz9r58dw9nqqnp14x8pcfkhmic3k8-map-3.2.1.tar':
  wanted: sha256:1vy231m2fm5cgz5nib14ib7ifprajhnbmzf6x4id48h2491m1n24
  got:    sha256:1zj0y3nvkrd2v43za214xr3h9z6wyp7r5s6nf5g1pj272yb871d1
```
2. Hash in your branch: `1vy231m2fm5cgz5nib14ib7ifprajhnbmzf6x4id48h2491m1n24` which is different from "got"

https://github.com/AndersonTorres/nixpkgs/blob/nixos-21.11/pkgs/applications/editors/emacs/elisp-packages/elpa-generated.nix#L2339

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/161871

**Comment by drmrcol** [comment]
Hi @AndersonTorres , I've read the documentation on backporting and saw your merged PR (https://github.com/NixOS/nixpkgs/pull/161871) to release-21.11 branch.

I looked for the mis-matching hash and was not able to find it. Do you think that I've missed it? Like I said, https://github.com/NixOS/nixpkgs/commit/1dc68f203cc0d495dcd271d973590511adb1aaa6 seems to be fixing the hash. Do you think that it somehow did not get into the PR?

**Comment by AndersonTorres** [comment]
The problem is that it does make no sense. The idea of a backport is that the tip of master should be injected onto the release.

However it does not happen automatically, and the merge conflict is not something trivial with a few lines. The machine-generated files are big indeed.

**Comment by drmrcol** [comment]
> The problem is that it does make no sense. The idea of a backport is that the tip of master should be injected onto the release.

I'm really not that familiar with nixos' release process. That said, from the documentation about backporting that you referenced, I understood that only selected commits are cherry-picked from master and commited to release-*. I'm not sure what do you mean by "tip of master should be injected onto the release", but I'm pretty sure that the documentation does not mean to merge master onto release branch.

I also don't want to loose track of the issue at hand: the problem is that some Emacs packages from NixOS 21.11 are broken due to changes in hash values of source tar balls (which should btw not happen, but that's another issue). It's only about hashes. The logic & versions of those packages don't need to change.

I've pinged you, because I saw that you fixed those hashes in master and asked if you could fix those hashes in release-21.11 too.

Thanks for your effort!

**Comment by AndersonTorres** [comment]
https://github.com/NixOS/nixpkgs/pull/162109/files

Now I declare this fixed!

**Comment by drmrcol** [comment]
awesome! `nixos-rebuild switch --upgrade` finally worked after a few few weeks that it was failing!

thank you!
