### ISSUE TITLE
Gnome 3.20 and GDM have weird mouse behavior

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#16155]
## Issue description

I've activated gnome 3.20. In both gdm and gnome-shell 3.20, I can move the mouse cursor fine, but it regularly goes back to the center of the screen (every 2 or 3 seconds). This means it is nearly impossible to use the mouse.

/cc @lethalman

**Comment by DamienCassou** [comment]
I've just created a bootable USB stick with Gnome **3.18.3** and the bug is present as well. I've never seen this bug on the Gnome 3.18.3 installed on my computer though. I'm lost.

**Comment by DamienCassou** [comment]
I can reproduce on another laptop when booting Gnome 3.18.3 from a USB stick. The touchpad is affected, but the TrackPoint is not... Could it be a synaptics problem?

/cc @vcunat @chris-martin  @abbradar @lethalman @edolstra

**Comment by vcunat** [comment]
@DamienCassou: which nixpkgs version(s) did you use during these?

**Comment by DamienCassou** [comment]
@vcunat I'm always on latest `channels/nixos-unstable`.

**Comment by vcunat** [comment]
Hmm, I can't see any relevant releases since then on the xorg ML.

**Comment by DamienCassou** [comment]
I can't reproduce anymore. I successfully switched to gnome 3.20. Can this issue be closed?

**Comment by vcunat** [comment]
OK. Let's reopen when someone can reproduce it again.
