### ISSUE TITLE
supercollider: Emacs as dependency?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#16150]
## Issue description

What the hell? "supercollider" has "emacs" as non-optional dependency? Is this sane?

**Comment by joachifm** [comment]
From the supercollider expression:
```nix
{ # ...
  buildInputs = [ 
    gcc libjack2 libsndfile fftw curl libXt qt readline ]
    ++ optional useSCEL emacs;
}
```
Note the use of `optional`.
