### ISSUE TITLE
pwgen-secure fails to find its word list

### ISSUE THREAD

**Issue by x10an14** [NixOS/nixpkgs#161552]
### Describe the bug
```bash
$ spwgen -d w
Debug mode enabled. Verbosity = 11
Arguments:
{'-a': False,
 '-d': True,
 '-n': None,
 '-t': False,
 '-v': 0,
 '<class-option>': None,
 '<class>': 'w'}
Password count: 1
Generating passphrase
Traceback (most recent call last):
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/bin/.spwgen-wrapped", line 123, in <module>
    r.render_password()
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 361, in render_password
    passwords.append(self.generate_password())
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 352, in generate_password
    return self.generate_pass_phrase()
  File "/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/rpg.py", line 323, in generate_pass_phrase
    with open(word_list_path) as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure/words.txt'
```

### Steps To Reproduce
1. Install `pwgen-secure` nixpkgs pkg from nixpkgs rev `74b10859829153d5c5d50f7c77b86763759e8654` or later.
2. Invoke `pwgen-secure w` in terminal.

### Expected behavior
For the tool to output a password (read: passphrase) of words.

### Additional context
```bash
$ tree -I *.pyc /nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure
/nix/store/78ym0d5b4ik3rrni53cqrfpyky9hxbvh-pwgen-secure-0.9.1/lib/python3.9/site-packages/pwgen_secure
├── fileRandomizer.py
├── __init__.py
├── __pycache__
├── rpg.py
└── search_space_calculator.py
```

### Notify maintainers
@peterhoeg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by peterhoeg** [comment]
Thanks for the detailed bug report. 

If you have any questions about the linked PR with the fix, please shout.

As for the bump to latest master, we typically stick to released versions unless there are show-stopper bugs that are addresses in an unreleased version.

**Comment by x10an14** [comment]
> Thanks for the detailed bug report.

Yw, thanks for maintaining the software here at nixpkgs! 
> If you have any questions about the linked PR with the fix, please shout.

Will do! Will test tomorrow if I remember, getting late here. 
> As for the bump to latest master, we typically stick to released versions unless there are show-stopper bugs that are addresses in an unreleased version.

Fair!
