### ISSUE TITLE
w3m as an package downloader

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#16163]
Feature request: option to setup program for loading packages
I would prefer `w3m` because of:
- ability continue downloading in case of network interruption
- much nicer neat output.

**Comment by aeosynth** [comment]
[nix](https://github.com/NixOS/nix) is the package manager; you should probably move this issue over there

**Comment by Pitometsu** [comment]
> NixOS/nixos
> OBSOLETE (go to NixOS/nixpkgs)

where exactly?

**Comment by Pitometsu** [comment]
https://github.com/NixOS/nix/issues/935
Done.

**Comment by vcunat** [comment]
That depends what you mean by `loading packages`. Package sources are typically realized by `fetchurl`, which is implemented in nixpkgs.

**Comment by vcunat** [comment]
And it shouldn't be difficult to make this configurable. Flipping such switch won't cause any rebuilds.
