### ISSUE TITLE
borgbackup closure depends on tox, detox, eventlet and more

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#16171]
## Issue description

when adding borgbackup to my system packges,
to my surprise without actually compiling it sill depended on tox, detox eventlet and maybe more

i am also surprised that tests for nix package installs use tox, since that usage is misplaced

nix should run tests directly against the installed version

**Comment by joachifm** [comment]
cc maintainer @nckx
