### ISSUE TITLE
rambox-pro: 2.0.1

### ISSUE THREAD

**Issue by definitelynobody** [NixOS/nixpkgs#161741]
New release available at https://github.com/ramboxapp/download/releases

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: rambox-pro

current version: 1.5.0
desired version: 2.0.1

###### Notify maintainers

maintainers: @cawilliamson

###### Note for maintainers

Please tag this issue in your PR.

**Comment by kciredor** [comment]
By now it's 2.0.3. Could you take a look @cawilliamson please? Older versions have no Slack compatibility which hurts.

**Comment by NickCao** [comment]
done in https://github.com/NixOS/nixpkgs/pull/202175
