### ISSUE TITLE
NixOS services that depend on Go binaries need to be updated after #16017

### ISSUE THREAD

**Issue by rushmorem** [NixOS/nixpkgs#16181]
NixOS services that depend on `Go` binaries are now broken (eg [etcd]) after https://github.com/NixOS/nixpkgs/pull/16017. This is because the attribute path for binaries has now changed. For example `pkgs.etcd` should now be `pkgs.etcd.bin`.

[etcd]: http://hydra.nixos.org/build/36789129/nixlog/40#line-860

**Comment by kamilchm** [comment]
I can do it tomorrow.
