### ISSUE TITLE
ipopt package is missing its binary

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#161858]
### Describe the bug

The `ipopt` package doesn't include a `bin/` folder. I am looking for a version of `ipopt` which includes the executable. Are we building the package incorrectly such that it doesn't include a binary?

Any and all help/advice is much appreciated :bow:

### Steps To Reproduce
1. `nix-build -A ipopt`
2. inspect output - notice there is no `bin/` folder

### Expected behavior

I want the `ipopt` executable.

### Notify maintainers

@abbradar
@markuskowa might know something about this? :man_shrugging:

**Comment by markuskowa** [comment]
@aanderse It appears that the binary `ipopt` requires AMPL, a commercial package, which is not packaged in nixpkgs. 
See: https://coin-or.github.io/Ipopt/INTERFACES.html

**Comment by aanderse** [comment]
@markuskowa ah, I understand. Thank you.
