### ISSUE TITLE
Lutris missing symbols

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#161945]
### Describe the bug
Lutris comes out of the box with no font support

### Steps To Reproduce
1. ... Launch Lutris
2. ... See missing symbols
3. ...

### Expected behavior
Fonts show text

### Screenshots
![Screenshot_20220226_092055](https://user-images.githubusercontent.com/6344099/155836280-e25a3823-f11b-42ad-9096-15110f33a199.png)

### Notify maintainers
@chiiruno

### Metadata

    system: "x86_64-linux"
    host os: Linux 5.15.23-1, KaOS, 2022
    multi-user?: yes
    sandbox: yes
    version: nix-env (Nix) 2.6.1
    channels(root): "nixpkgs"
    nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixpkgs

**Comment by Matthelonianxl** [comment]
https://github.com/NixOS/nixpkgs

**Comment by ShalokShalom** [comment]
Yeah, this is this repo here? 
What do you like to tell me?

**Comment by Artturin** [comment]
Fonts have to be installed globally 

Try installing your distros equilevant of `ttf-liberation`

**Comment by ShalokShalom** [comment]
![Screenshot_20220227_122559](https://user-images.githubusercontent.com/6344099/155880546-200d2b26-5bac-402a-965a-45019d705468.png)

My RX 480 is also Vulkan capable.

**Comment by Madouura** [comment]
AFAIK, you can't install system or user fonts with a nix pkgs, it has to be enabled in your configuration, so I'm not entirely sure there's anything to be done here.

**Comment by ShalokShalom** [comment]
Not using Nix anymore
