### ISSUE TITLE
Steam crashing on launch

### ISSUE THREAD

**Issue by ShalokShalom** [NixOS/nixpkgs#161944]
### Describe the bug
Steam crashes, once the initial download is done.  

### Steps To Reproduce
1. ... Download this package
2. ... Launch it
3. ...

### Expected behavior
Steam starts

### Screenshots
![Screenshot_20220226_091957](https://user-images.githubusercontent.com/6344099/155836001-e88aefcd-1557-4b2e-9c73-b6371aaa4cda.png)

### Additional context
CrashID=bp-d42b02dc-fd23-48ad-a7d8-9a6a02220226

### Strace

https://paste.ee/p/yfbnB

### Notify maintainers
@jagajaga
@jonringer

### Metadata
nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                                     
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.23-1, KaOS, 2022`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
****

**Comment by jonringer** [comment]
do you have `programs.steam.enable = true;`?

I see some 32 bit errors, but those should be solved by the above setting

**Comment by jonringer** [comment]
add it to your `/etc/nixos/configuration.nix`.

Then run `sudo nixos-rebuild switch` to apply it.

After that, you should be able to launch steam.

**Comment by ShalokShalom** [comment]
I have /etc/nix/nix.conf here, is it also ok? I have no nixos under etc.

**Comment by jonringer** [comment]
Please try with https://github.com/guibou/nixGL

The root of the issue is that NixOS currently mounts everything video graphics related to `/run/opengl-driver/`, so that's the assumption that nixpkgs' steam makes as well.

**Comment by ShalokShalom** [comment]
And what's about Vulkan?

**Comment by jonringer** [comment]
> Why is this package not a dependency for Steam then?

because graphics are a part of your system, nix can only handle software dependencies, not hardware.
