### ISSUE TITLE
nextcloud-client: xdg-mime call doesn't work under certain circumstances

### ISSUE THREAD

**Issue by witchof0x20** [NixOS/nixpkgs#161901]
### Describe the bug
Nextcloud client doesn't properly open the folder on clicking the folder icon in some cases.

### Steps To Reproduce
1. Install `nextcloud-client`
2. Run `nextcloud` with `xdg-mime` not in `PATH`
3. Click tray icon and click the folder icon in the appearing window
4. No folder opens, or it falls back to using something strange like firefox

### Expected behavior
Nextcloud client opens the proper file manager when clicking the file icon

### Additional context
This seems to be due to https://github.com/nextcloud/desktop/blob/3fd4d5cd4b4ecea8574e4ab7fd2d8f0d0f0b654d/src/gui/openfilemanager.cpp#L58

I think a fix for this would add xdg-utils to dependencies for this package and patch the xdg-mime call here

Referred from: https://github.com/nix-community/home-manager/issues/2671

### Notify maintainers

@Kranzes 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Kranzes** [comment]
I've just played with it and weirdly enough, when I enable `services.nextcloud-client` in home-manager then launch home-manager manually from the program launcher (or terminal), the folder button takes me to firefox. But when disabling the systemd services and just launching it manually from program launcher/terminal, it opens it correctly in nemo.

**Comment by Kranzes** [comment]
Adding xdg-utils to the buildInputs of the nextcloud-client package did not help either.

**Comment by Kranzes** [comment]
After further research, it seems as if we need to use `makeWrapper` to add `xdg-utils` to the `PATH` of the nextcloud-client binary.
