### ISSUE TITLE
texlive.pdfpages don’t work with LuaTeX (and *do* with pdflatex/xelatex)

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#16193]
## Issue description

When using the `pdfpages` package and compiling with LuaTeX, I’m getting an error about `pdfpages` requiring at least pdfTeX version 1.00.

However, when you run `pdflatex main.tex` or `xelatex main.tex` below, instead, everything works as expected.
### Steps to reproduce

```
% cd $(mktemp -d)
% nix-shell --pure -p 'texlive.combine { inherit (texlive) scheme-small luatex pdfpages; }'
$ echo '\documentclass{article}\usepackage{pdfpages}\begin{document}\end{document}' > main.tex
$ lualatex main.tex
This is LuaTeX, Version beta-0.80.0 (Web2C 2015/NixOS.org) (rev 5238)
[…]
(/nix/store/hxd8khl8wplajji6x66zhrv4b5yggd1r-texlive-combined-2015/share/texmf/
tex/latex/pdfpages/pppdftex.def

! Package pdfpages Error: Package pdfpages requires at least
(pdfpages)                pdfTeX version 1.00.

[…]

l.38          {Update your TeX distribution.}

? X
[…]
(1)$
```
## Technical details
- System: 16.09pre84674.fbde3a7 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre84674.fbde3a7"

**Comment by vcunat** [comment]
It might be that LuaTeX still doesn't work well with our `texlive.*` packaging.

**Comment by michalrus** [comment]
@vcunat, oh… That would be really unfortunate, as I need LuaTeX for a project using Gregorio. :crying_cat_face: 

How do I go about debugging this?

**Comment by vcunat** [comment]
Ah, I confused context with luatex :-/ but it might still apply as it's certainly much less tested here than e.g. latex.

I managed to create most of our current texlive packaging, but such issues were resolved mainly by trial-and-error, as I could find no good documentation about it anywhere. https://github.com/NixOS/nixpkgs/pull/14681 seems closely related.

**Comment by Profpatsch** [comment]
triage: does this still happen?

@vcunat maybe it was fixed in the linked PR?

**Comment by vcunat** [comment]
Test case works on 18.03.
