### ISSUE TITLE
Hardened NixOS profile renders external mouse and keyboard unusable

### ISSUE THREAD

**Issue by ne9z** [NixOS/nixpkgs#161964]
### Describe the bug
After importing [hardened profile](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/hardened.nix), external USB connected trackball and keyboard are unusable.  The devices shows up in `lsusb` output but can not be powered up.  In dmesg the devices are disconnected after `mtpprobe: not a MTP device`.

Laptop built-in trackpad and keyboard are unaffected.  Can confirm that this issue is not related to the hardened kernel: disabling this profile and enabling hardened kernel alone can not reproduce this issue.

### Steps To Reproduce
1. On a laptop, enable hardened profile
2. Reboot, plug in keyboard
3. Not working.

### Expected behavior

External input devices should be working.
### Notify maintainers

@joachifm @emily
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by ne9z** [comment]
`nix-info` output:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98-hardened1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 21stce** [comment]
You have not sufficiently demonstrated that there is a problem. In order to do that you must first have a specification of what the hardened NixOS profile is supposed to accomplish. I can easily imagine that on a hardened profile people do not want to have external keyboards working. 

As such, I recommend first getting it clear what a hardened profile is supposed to accomplish and then file a feature request. 

In order to debug this (assuming there is a bug in the first place), you could write a program that would test all configurations using a greedy algorithm. That will take time linear in the number of options.

**Comment by joachifm** [comment]
Enabling the hardening profile whole-sale is expected to break useful functionality & reduce performance.

The first thing I would check is whether all required kernel modules are being loaded.  The profile blocks dynamic loading of kernel modules after boot up.  You may need to explicitly declare additional kernel modules (by adding them to `boot.kernelModules`).

**Comment by ne9z** [comment]
> what the hardened NixOS profile is supposed to accomplish

I admit I have not thoroughly investigated what are the implied effects of the various options are, i.e. whether security.lockKernelModules prevents external input devices from functioning.

But as input devices are fundamental in interacting with computers, it is IMHO at least necessary to warn users of this potential loss of functionality.

**Comment by ne9z** [comment]
@joachifm Thanks for your contributions to NixOS and the excellent advice!  I've identified the following modules being loaded when the keyboard is plugged in:
```
hid_generic
usbhid
hid
```

Will reapply the profile and hee if it's working.

**Comment by ne9z** [comment]
I also tested with MTP file transfer and USB tethering from phone, which are my main use cases for USB connection.  The former does not need any additional kmod. The latter needs the following:`rndis_host cdc_ether usbnet mii`.

**Comment by ne9z** [comment]
Problem solved.  Thanks again!

Besides this issue and setting memory allocator back to libc (for firefox), I have experienced no additional adverse effects on my laptop so far.   Disabling SMT also solved the issue of laptop fan npinning up constantly, which is pretty nice :-)

**Comment by joachifm** [comment]
@ne9z that's great :) The hardened profile is probably more suited for headless appliances, but it's great to have people actually testing it out with more desktop oriented configs.  I don't have too much bandwidth for NixOS these days but I'd be happy to look at any PRs to make desktop use with the hardened profile smoother out of the box.

**Comment by linsui** [comment]
The mouse and keyboard work for me by default but USB storage doesn't. `uas` is required. For encrypted wifi, `ccm` is required. I also set `unprivilegedUsernsClone = true;` to make Electron work. It's very helpful is these information can be add to the wiki.
