### ISSUE TITLE
xdg-user-dirs contains no options for configuring the directories it manages.

### ISSUE THREAD

**Issue by Avanesov79** [NixOS/nixpkgs#16200]
## Issue description

xdg-user-dirs contains no options for configuring the directories it manages. The only options are the defaults. The system default should be configurable via configuration.nix. 
### Steps to reproduce

Install nixos with xdg-user-dirs
## Technical details
- System: (NixOS: `16.03`)
- Nix version: 1.11.2 (run `nix-env --version`)
- Nixpkgs version: xdg-user-dirs-0.15 (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by jtojnar** [comment]
Duplicate of #33282
