### ISSUE TITLE
vscode-extensions.matklad.rust-analyzer 0.2.384 out of date, missing security updates

### ISSUE THREAD

**Issue by mstone** [NixOS/nixpkgs#162010]
###### Notes

`rust-analyzer` itself has been steadily updated in nixpkgs but nixpkgs' packaging of its bundled vscode extension, `vscode-extensions.matklad.rust-analyzer` has not been updated in >2 months. 

Additionally, during this time, the extension's dependencies have been updated to remove at least two security vulnerabilities: https://github.com/rust-analyzer/rust-analyzer/pull/11420.

I would like to help keep this extension up to date, but I am unfortunately insufficiently familiar with nixpkgs' `nodePackages` infrastructure (and the extension's packaging's use of it) to prepare an appropriate PR.

Thus:

a) can someone who is familiar with the extension's packaging please update it, perhaps to 0.3.953 or to one of the recent git tags such as https://github.com/rust-analyzer/rust-analyzer/releases/tag/2022-02-22, to match `rust-analyzer`?

b) additionally, if/when you do, could you also add a paragraph of comments (maybe to the nixpkgs manual, if not directly in the code?) on what the steps are to update it so that this is more clear?

Thanks!

courtesy cc: @inicola, who has been improving the extensions' compatibility with NixOS.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vscode-extensions.matklad.rust-analyzer

current version: 0.2.384
desired version: 0.4-dev

###### Notify maintainers

maintainers: @jonringer

###### Note for maintainers

Please tag this issue in your PR.

**Comment by austinbutler** [comment]
What I think happened here is that in https://github.com/NixOS/nixpkgs/pull/150775 the parts of the `rust-analyzer` package's update script that also updated the VS Code extension were deleted. I have a branch where I pull those deleted parts into a new update script for the extension itself. It's working for me locally, so today or tomorrow I will put up a PR (I encountered some issues relating to I think the fact that we're not on Rust 1.59.0 yet, and now I have to re-run the ~1h20m Node packages update).

I think for updating Node packages in general, it involves running the same `generate.sh` script as [adding a new package](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#javascript-packages-inside-nixpkgs-javascript-packages-nixpkgs). I might add that to the docs as well, I don't think it's very clear what the intended process is currently. As for this particular VS Code extension, I think adding the update script in the same folder should make it fairly clear how to update it.

**Comment by mstone** [comment]
@austinbutler -- thanks very much for both of these updates!
