### ISSUE TITLE
libjfxwebkit.so missing in jdk in unstable channel

### ISSUE THREAD

**Issue by linsui** [NixOS/nixpkgs#162064]
### Describe the bug
There is libjfxwebkit.so in openjdk 17 in 21.11 (on my system the path is `/nix/store/liziz11l6wjw4vrl45ad2255ak0n2cd8-openjdk-17.0.1+12/lib/openjdk/lib/`) while it is missed in unstable (on my system the path is `/nix/store/yirggs7jnyxbhdmk342f6an4ifkgmbgv-openjdk-17.0.1+12/lib/openjdk/lib/`).

### Steps To Reproduce
1. Install jdk from unstable

### Notify maintainers

@edwtjo @asbachb @bachp

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98-hardened1, NixOS, 21.11 (Porcupine)`
```

**Comment by bachp** [comment]
I think this is because openjfx17 is [built without webkit](https://github.com/nixos/nixpkgs/blob/master/pkgs/development/compilers/openjdk/openjfx/17.nix#L70) atm.

**Comment by linsui** [comment]
Oh, I got it. The libjfxwebkit.so in  21.11 is from openjfx15. Thanks! Could you please enable it for openjfx17?

**Comment by bachp** [comment]
Unfortunately I didn't manage to get it built with webkit enabled as it was trying to download some zips during the build that I did not manage to get into the fixed output derivation. But somebody else is welcome to try.

**Comment by linsui** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/300573.
