### ISSUE TITLE
[texlive] Adding Gregorio

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#16215]
## Issue description

I’d like to contribute a Nix expression for [Gregorio](http://gregorio-project.github.io/) — tools for beautifully typesetting Gregorian chant.

It needs to plug itself into a TeX Live installation.

I already have a working expression here — [`gregorio.nix` in michalrus/dotfiles@2183df5](https://github.com/michalrus/dotfiles/blob/2183df5384544d6e17f94da5fd44d41264b1c2b3/.nixos-config.symlink/pkgs/gregorio.nix) — but plugging into our `pkgs.texlive.combine` seems a bit… hacky (see the part in my [`notebook.nix`](https://github.com/michalrus/dotfiles/blob/2183df5384544d6e17f94da5fd44d41264b1c2b3/.nixos-config.symlink/notebook.nix#L94-L97) and the last lines of `gregorio.nix` above).

@vcunat, how should I improve that and _where_ should `gregorio.tex` be put inside the `<nixpkgs>` tree?
## Technical details
- System: 16.09pre84674.fbde3a7 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre84674.fbde3a7"

**Comment by vcunat** [comment]
I see `gregoriotex-4.1.4` in the latest texlive upstream, so this is just one piece of the bigger problem: our texlive state is around a year old, and quite a few users mind that.

IIRC there is at least one PR trying to (partially) resolve that. Lately I haven't been motivated to invest much time into *TeX* and others with merge privileges don't seem to step in a lot, so the state is lagging a bit. I see texlive-2016 was released about a week ago, so within a couple weeks I might get to updating to that version.

**Comment by michalrus** [comment]
Oh, great to hear that! :heart_eyes_cat:  Thank you!

And then, if I wanted a newer version, I’d just override one package’s version & hash? Pretty cool!

**Comment by vcunat** [comment]
I don't know of any easy overriding way except for modifying the nixpkgs tree.

**Comment by michalrus** [comment]
Oh… :disappointed_relieved:

**Comment by vcunat** [comment]
> so within a couple weeks I might get to updating to that version.

Now it doesn't seem too likely I'll manage it that soon.

**Comment by vcunat** [comment]
I was wrong: https://github.com/NixOS/nixpkgs/pull/16391

**Comment by michalrus** [comment]
Awesome! :heart_eyes_cat:

**Comment by Profpatsch** [comment]
Nice, fixed & closed.
