### ISSUE TITLE
why Sandboxing is not working on your platform nixos,and it doesn't matter,right ?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#162377]
fhs-chrootenv:prehonor@prehonor:~/.opam/4.13.1/.opam-switch/build/ocaml-base-compiler.4.13.1$ opam init --reinit -ni
No configuration file found, using built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!
[ERROR] Sandboxing is not working on your platform nixos:
        "~/.opam/opam-init/hooks/sandbox.sh build sh -c echo SUCCESS >$TMPDIR/opam-sandbox-check-out && cat
        $TMPDIR/opam-sandbox-check-out; rm -f $TMPDIR/opam-sandbox-check-out" exited with code 1 "bwrap: execvp sh: No such file or
        directory"
Do you want to disable it?  Note that this will result in less secure package builds, so please ensure that you have some other
isolation mechanisms in place (such as running within a container or virtual machine). [y/N] N

<><> Updating repositories ><><><><><><><><><><><><><><><><><><><><><><><><><><>

[default] no changes from https://opam.ocaml.org

**Comment by wamserma** [comment]
This was crossposted as https://github.com/ocaml/opam/issues/5077, which has more information.
Running OCaml in a FHS is not officially supported on NixOS, so when building the FHS you have to take care of dependencies yourself, especially Bubblewrap.
In general, please see the Manual about OCaml in Nix:
https://nixos.org/manual/nixpkgs/stable/#sec-language-ocaml

This thread in Discourse also has a link to a Telegram group, if you need more support: https://discourse.nixos.org/t/ocaml-builddunepackage-not-working-in-21-05/13700/5

**Comment by prehonor** [comment]
> 

Thank you
