### ISSUE TITLE
Building wine now requires a custom gcc build

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#16235]
```
    wine-wow-staging = 
        (callPackage <nixpkgs/pkgs/misc/emulators/wine> {
            wineRelease = "staging";
            wineBuild = "wineWow";
        });
```
```
~ $ nix-build '<nixpkgs>' -A wine-wow-staging --dry-run
these derivations will be built:
  /nix/store/07mlifsvj3nnvbq6wk4lr2wnyf95cr5k-gcc-4.9.3.drv
  /nix/store/0qybb5z3v7sqxa5d8cg2mkf9j1yz7k3j-gcc-wrapper-4.9.3.drv
  /nix/store/bp3z6mck5q6kffbydb25dl8n3slax5ka-stdenv.drv
  /nix/store/3235ydhccjs5hvcc4q4jp4c1fl3knhcc-wine-wow-1.9.11-staging.drv
```
Also tried this:
```
nix-repl> self.wine.override { wineRelease = "staging"; wineBuild = "wineWow"; }
error: Package ‘self-4.5.0’ in ‘/nix/store/bxr4qfl9xjh0jiyzlab0z3ykxhyahhbd-nixos-16.09pre85363.886c03a/nixos/pkgs/development/interpreters/self/default.nix:37’ is marked as broken, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.
```

Now wine requires a custom gcc, this wasn't needed before, can someone tell if this is needed?

@bendlas @abbradar

**Comment by bendlas** [comment]
see https://github.com/NixOS/nixpkgs/blob/06027595fcf802f2b8a8fc5bf29111d1ffac5c48/pkgs/misc/emulators/wine/packages.nix#L20

Feel free to try a build with gcc 5.4 ...

**Comment by joelmo** [comment]
I can call that and it's available from the binary cache:
```
nix-repl> :b overrideCC stdenv gcc49
these paths will be fetched (0.01 MiB download, 0.02 MiB unpacked):
  /nix/store/if6sd0fgd2798c8iskdblrvxsqx67d4v-stdenv
fetching path ‘/nix/store/if6sd0fgd2798c8iskdblrvxsqx67d4v-stdenv’...
```
That command produces a store path so I should be able to get that from the cache?

**Comment by bendlas** [comment]
oh, I see now what your question was about. so the multilib gcc 4.9 is not in the binary caches?

**Comment by joelmo** [comment]
Yes, that's because there is no wineWow buildt by hydra? don't know if it would help and work to replace wrapCCMulti, by pkgsi683.gcc49

**Comment by bendlas** [comment]
I doubt that it could be replaced like this. WineWOW deals with multilib, so its compiler probably needs to aswell. I think the reason for hydra exclusion is size concerns.

**Comment by abbradar** [comment]
I'm now very short on time because of deadlines, but if someone can build `wine-wow` with GCC 5.4 successfully we can revert this workaround back.
