### ISSUE TITLE
Error installing package - attribute 'jless' in selection path 'nixos.jless' not found

### ISSUE THREAD

**Issue by mh182** [NixOS/nixpkgs#162489]
### Describe the bug
When I try to install `jless` as described on the [NixOS Search Packages](https://search.nixos.org/packages?channel=21.11&show=jless&from=0&size=50&sort=relevance&type=packages&query=jless) I get an error.

### Steps To Reproduce
1. Copy installation command from the NixOS package search to install `jless` (see link above)
2. Paste the command into the command shell 
```
❯ nix-env -iA nixos.jless
error: attribute 'jless' in selection path 'nixos.jless' not found
```

### Expected behavior
`jless` is installed.

### Notify maintainers
@jfchevrette

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336020.2128d0aa28e"`
 - channels(max): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Guessing you have to update

**Comment by jfchevrette** [comment]
```
 - channels(root): `"nixos-21.11.336020.2128d0aa28e"`
 ```
Your channel seem to be up-to-date as of Feb 16, 2022 at commit https://github.com/NixOS/nixpkgs/commit/2128d0a

jless was backported to 21.11 on Feb 17 in commit https://github.com/NixOS/nixpkgs/commit/b68340cbd4165c48c1cdf025009018dc0de7ee7f

Update and jless should become available to install
