### ISSUE TITLE
mill: allow to override jre/jdk easily

### ISSUE THREAD

**Issue by gvolpe** [NixOS/nixpkgs#162471]
### Describe the issue

I have a dev-shell where I would like to override the Java version of multiple packages, to ensure they all use the same one. Unfortunately, there's no easy way to do this with `mill` other than overriding the `installPhase` as follows:

I think this is because at the `top-level/all-packages.nix`, the `jre` version is being hard-coded.

```nix
mill = callPackage ../development/tools/build-managers/mill {
  jre = jre8;
}
```
 
If this is hard-coded to `jre8`, I believe it would be better to make it an attribute of the derivation itself, unless it's being done this way for some reasons I'm missing.

### Workaround

To work-around the issue, we have two options. The first one is to override `jre8`.

```nix
mill-overlay = f: p: {
  jre8 = p.jdk17_headless;
}
```

But it feels wrong to set `jre8` to `jdk17`. This could create conflict with other packages.

The second option is to override the `installPhase`, but it's not great.

```nix
mill-overlay = f: p: {
  mill = p.mill.overrideAttrs (old: {
    installPhase = ''
      runHook preInstall
      install -Dm555 "$src" "$out/bin/.mill-wrapped"
      # can't use wrapProgram because it sets --argv0
      makeWrapper "$out/bin/.mill-wrapped" "$out/bin/mill" \
        --prefix PATH : "${p.jdk17_headless}/bin" \
        --set JAVA_HOME "${p.jdk17_headless}"
      runHook postInstall
    '';
  });
}
```

### Proposed solution

If we add a `jre` attribute to the [mill derivation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/mill/default.nix), we could override it as follows instead. 

```nix
mill-overlay = f: p: {
  mill = p.mill.overrideAttrs (old: {
    jre = p.jdk11;
  });
}
```

If the idea sounds, I'd be happy to submit a PR with the changes. /cc @scalavision

**Comment by scalavision** [comment]
I think this is a great idea @gvolpe and it seems to be a common pattern in other / similar jdk / jre dependent package, it would add a lot of value!

**Comment by gvolpe** [comment]
Great, thanks for the quick reply @scalavision ! I will submit a PR then 👍🏽

**Comment by Artturin** [comment]
Why not just 
```nix
(mill.override { jre = pkgs.jdk11; })
```

**Comment by gvolpe** [comment]
Oh does that work? 😯 I'm away from my computer until Sunday eve, I'll definitely try that, thanks @Artturin!

**Comment by scalavision** [comment]
Thanks @Artturin, this seems to work for me.
