### ISSUE TITLE
minecraftServers questions/feedback

### ISSUE THREAD

**Issue by jyooru** [NixOS/nixpkgs#162456]
The `minecraftServers` package set was introduced in #150197, and since then I've been working on [jyooru/nix-minecraft-servers](https://github.com/jyooru/nix-minecraft-servers). I now have packages for paper, purpur, vanilla, velocity and waterfall, and each package is generated using some JSON that is automatically updated (jyooru/nix-minecraft-servers#58 for example).

I would now like to add some of these packages back into nixpkgs and also automatically update them here too.

I would like some feedback from the nixpkgs community on how this should be done:

- what versions should be included in nixpkgs? Right now all minor (1.17, 1.16, ...) versions are available. I think this is fine, but should I do the same for the other Minecraft servers?
- when/how often should they an automated PR be created? I think weekly is fine.

---

cc @tomberek as you were interested in this flake

Also not sure what labels I should be adding to this issue, so please add the correct ones if I got them wrong.

**Comment by tomberek** [comment]
I'm not sure which direction to suggest here. There is value in bringing them all into Nixpkgs. Then again, it is also a nice use-case for the distributed nature of flakes to host all the updating versions in another location.

**Comment by jyooru** [comment]
Alright, thank you for your response. I'll open a PR soon.

**Comment by Krutonium** [comment]
> but should I do the same for the other Minecraft servers?

I vote Yes on this, because at the end of the day, a mod may only work on a specific build of Forge for example. I've come across this once or twice.

**Comment by jyooru** [comment]
I've stopped maintaining nix-minecraft-servers, so I will close this issue.
