### ISSUE TITLE
Untangle linux headers from glibc

### ISSUE THREAD

**Issue by dvc94ch** [NixOS/nixpkgs#16266]
To better support other libc's I think we should make the dependency on linuxHeaders explicit. I propose we merge linuxHeaders with the linux package using the `outputs = ["dev", "out"]` attribute, and add linux as a dependency to all packages in the `pkgs/os-specific/linux` folder. Any breakage / build failure is a "pkg misplaced bug". This issue is meant to track the progress of this.

**Comment by edolstra** [comment]
:-1: on merging because then any kernel update would require a stdenv rebuild, and it would slow down building stdenv by requiring a kernel build.

**Comment by dvc94ch** [comment]
If I understand correctly, this criticism only applys to merging linuxHeaders and linux into one package, but not necessarily to making the linuxHeaders dependency explicit?

**Comment by dvc94ch** [comment]
Ok figured out why it's was done the way it was done. So headers are part of libc from nixos's perspective. That's fair.
http://barryk.org/blog/?viewDetailed=02233
