### ISSUE TITLE
boost: needsUserConfig setting not compatible with enableStatic on Darwin

### ISSUE THREAD

**Issue by kfiz** [NixOS/nixpkgs#162699]
### Describe the bug
Currently in `generic.nix` needsUserConfig is set when `isDarwin` is true: 
https://github.com/NixOS/nixpkgs/blob/9ff63d04ed4bc8f2fce2c537349f432e5ef298e7/pkgs/development/libraries/boost/generic.nix#L71

This is not specific enough as this is not compatible with `enableStatic` and looking at the rest of the code should probably only be set when `isDarwin && enableShared` is true. I've tested the latter by building boost 1.77 on Darwin and it compiled successfully.

### Steps To Reproduce
1. Build boost 1.77 on Darwin with `enableStatic`

### Expected behavior
Should build

### Notify maintainers
@hjones2199 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.0pre20211217_6e6e998`
 - channels(louis): `"darwin, home-manager, nixpkgs-21.03pre269485.a58a0b5098f"`
 - nixpkgs: `/Users/louis/dev/projects/nixos/nixpkgs`
```

**Comment by kfiz** [comment]
@veprbl should I send a pr, so we can close this? This is blocking #137939 for Darwin.

**Comment by veprbl** [comment]
@kfiz Yes, PR's are welcome

**Comment by kfiz** [comment]
> @kfiz Yes, PR's are welcome

done. #168165
