### ISSUE TITLE
perlPackages.AppSqitch: 1.2.1

### ISSUE THREAD

**Issue by sekunho** [NixOS/nixpkgs#162687]
###### Checklist

Latest version bump: https://github.com/NixOS/nixpkgs/commit/ef87b2112369292e334e360cb7ef6b01e5c15f11

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `legacyPackages.x86_64-linux.perlPackages.AppSqitch`

current version: 1.1.0
desired version: 1.2.1

###### Notify maintainers

maintainers: `volth` but it doesn't seem like the email is tied to a GitHub account

###### Note for maintainers

Please tag this issue in your PR.

**Comment by NickCao** [comment]
https://github.com/NixOS/nixpkgs/blob/e6e389917a8c778be636e67a67ec958f511cc55d/pkgs/top-level/perl-packages.nix#L919
