### ISSUE TITLE
lapce

### ISSUE THREAD

**Issue by GaetanLepage** [NixOS/nixpkgs#162630]
**Project description**
Lightning-fast and Powerful Code Editor written in Rust.

**Metadata**

* homepage URL: https://lapce.dev/
* source URL: https://github.com/lapce/lapce
* license: Apache-2.0
* platforms: linux

**Comment by Eliot00** [comment]
If nobody WIP, I want to try

**Comment by davidak** [comment]
Was added in linked PR.

Waiting for channel to advance ([status](https://nixpk.gs/pr-tracker.html?pr=162984)).
