### ISSUE TITLE
Download nvidia driver failed.

### ISSUE THREAD

**Issue by yhuangh** [NixOS/nixpkgs#162625]
## Issue description
When building nvidia driver, the log tells

```
building '/nix/store/r0av8y74mag315g2nqnfkr168xayj2y8-NVIDIA-Linux-x86_64-495.44.run.drv'...

trying https://us.download.nvidia.com/XFree86/Linux-x86_64/495.44/NVIDIA-Linux-x86_64-495.44.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:04:21 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to us.download.nvidia.com:443 
error: cannot download NVIDIA-Linux-x86_64-495.44.run from any mirror
```

Try to access `https://us.download.nvidia.com/...run-file-path...` in firefox, but it failed too. But trying `https://download.nvidia.com/...run-file-path...` is OK. This is most likely due to the Internet environment in China. How about replacing the url in [pkgs/os-specific/linux/nvidia-x11/generic.nix](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/os-specific/linux/nvidia-x11/generic.nix) to `https://download.nvidia.com/...run-file-path...`?

### Steps to reproduce
1. add `services.xserver.videoDrivers = [ "nvidia" ];` in configurations.nix
2. `# nixos-rebuild boot`

## Technical details

```
yh@nixos ~ [1]> nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/977rrqjf3hfda1qbqlpp2pz22m6phczy-bash-interactive-5.1-p8-dev
copying path '/nix/store/977rrqjf3hfda1qbqlpp2pz22m6phczy-bash-interactive-5.1-p8-dev' from 'https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.102, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by eadwu** [comment]
That's probably fine, if I remember the reason it is `us.download.nvidia.com` is because that's typically where the links become live first, and waiting up to an extra few days for `download.nvidia.com` is not something I liked when I was experimenting with the updates.

**Comment by vcunat** [comment]
Seems fixed now.
