### ISSUE TITLE
Packaging : Python3  websockets 

### ISSUE THREAD

**Issue by ShowierData9978-Alt** [NixOS/nixpkgs#162651]
**Project description**
websockets is a library for building [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) servers and clients in Python with a focus on correctness, simplicity, robustness, and performance.

**Metadata**

* homepage URL: https://github.com/aaugustin/websockets
* source URL: https://github.com/aaugustin/websockets/tree/main/src/websockets
* license: BSD 3-Clause.
* platforms: Python3 Suported platforms

**Comment by fabaff** [comment]
Is already [available](https://search.nixos.org/packages?channel=unstable&show=python39Packages.websockets&from=0&size=50&sort=relevance&type=packages&query=websockets).
