### ISSUE TITLE
Unable to update system with home-manager and `podman`

### ISSUE THREAD

**Issue by austinbutler** [NixOS/nixpkgs#162694]
### Describe the bug

With `podman` installed to `home.packages`, running `home-manager switch` results in:

```
building '/nix/store/8rir90i2sgmyyqcsazm8vmac5wxgrp52-home-manager-path.drv'...
error: not a directory: `/nix/store/yyqyc86np5bisl5a1g25wvdvvamrxc1v-podman-wrapper-4.0.2/etc'
builder for '/nix/store/8rir90i2sgmyyqcsazm8vmac5wxgrp52-home-manager-path.drv' failed with exit code 2
```

### Steps To Reproduce

1. Add `podman` to `home.packages`
2. `home-manager switch`

### Expected behavior

Switch continues without error.

### Additional context

Strangely, building in `nixpkgs` seems to work fine: `nix-build -A podman`. If I pin podman to 4ee1f9eafc15a291bbb838f80a47bf2f4c97ce80 there is no problem. So it seems related to https://github.com/NixOS/nixpkgs/pull/161130.

### Notify maintainers

@marsam @zowoq 

### Metadata

```yaml
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(abutler): `"home-manager, nixpkgs-22.05pre358575.ad267cc9cf3"`
 - nixpkgs: `/Users/abutler/.nix-defexpr/channels/nixpkgs`
```

**Comment by zowoq** [comment]
```
nix-env -f. -iA podman
installing 'podman-wrapper-4.0.2'
building '/nix/store/l5mbkbd0mz2y1990wdsnvbhjm37df09h-user-environment.drv'...
warning: skipping dangling symlink '/nix/store/5z3fngz1sp8jini75wjm4xknb8x52h0i-user-environment/etc'
warning: skipping dangling symlink '/nix/store/5z3fngz1sp8jini75wjm4xknb8x52h0i-user-environment/lib'
```

Seems `home-manager` turns the warnings into an error.

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/162695

**Comment by zowoq** [comment]
TBH, would have expected this bug to have been filed against `home-manager` first as `nix-build -A podman` worked fine.

I'd suggest doing so anyway as it is a bit surprising that `home-manager` behaves differently.
