### ISSUE TITLE
murrine engine not found when using XFCE

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#16268]
## Issue description

GTK+-2 applications running in the XFCE desktop with a theme that depends on the murrine engine fails to load the engine. For instance, when launching `gvim` on a terminal with the theme set to Arc-Dark, I am getting the following messages:

``` shell
$ gvim ~/.gvimrc 

(gvim:4640): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
[...]
```

With other window managers (like openbox) this does not happen.

Looking at the XFCE module one can see that the environment variables `GTK_PATH` and `GTK_DATA_PREFIX` are explicitly set and some engines and themes are also explicitly included in the environment.

I have noticed that when the `GTK_DATA_PREFIX` variable is unset after login in XFCE, the murrine engine is found.

So, why is `GTK_DATA_PREFIX` set in the XFCE module? Is it really needed? If so, how to fix the issue of not finding the murrine engine?
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  16.09pre85363.886c03a (Flounder)
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  "16.09pre85363.886c03a"

**Comment by rnhmjoj** [comment]
I too use the Arc theme and this happens to me as well. I don't have a `GTK_DATA_PREFIX` set and I'm not using a DE though.

**Comment by Pitometsu** [comment]
I enabled both gtk2 and gtk3 themes next way:
```shell
    extraInit = ''
      # GTK2 theme
      export GTK_PATH=$GTK_PATH:${pkgs.gtk-engine-murrine}/lib/gtk-2.0:${pkgs.pkgsi686Linux.gtk-engine-murrine}/lib/gtk-2.0https://ru.wikipedia.org/wiki/WebP
      export GTK2_RC_FILES=${pkgs.writeText "iconrc" ''gtk-icon-theme-name="Numix-Light"''}:${pkgs.numix_solarized-gtk-theme}/share/themes/Numix\ Solarized/gtk-2.0/gtkrc:$GTK2_RC_FILES
      # GTK3 theme
      export GTK_THEME="Numix Solarized"
      # export XDG_DATA_DIRS="${pkgs.numix_solarized-gtk-theme}/share:$XDG_DATA_DIRS"
      # export XDG_CONFIG_DIRS="/etc/xdg:$XDG_CONFIG_DIRS"

      # SVG loader for pixbuf (needed for svg icon themes)
      export GDK_PIXBUF_MODULE_FILE=$(echo ${pkgs.librsvg.out}/lib/gdk-pixbuf-2.0/*/loaders.cache)
      # Set GTK_DATA_PREFIX so that GTK+ can find the system themes.
      export GTK_DATA_PREFIX=$GTK_DATA_PREFIX:${config.system.path}:${pkgs.numix_solarized-gtk-theme}
    '';
```
It works for me.

**Comment by Pitometsu** [comment]
Oh, and yes, I use custom theme:
```nix
      numix_solarized-gtk-theme = with pkgs; stdenv.mkDerivation rec {
        version = "0.0.1";
        name = "numix_solarized-gtk-theme-${version}";

        src = fetchFromGitHub {
          owner = "Ferdi265";
          repo = "numix-solarized-gtk-theme";
          rev = "b6fce07c95a84dd618ed8594d441d0543192c1bb";
          sha256 = "0gix5gx0n2bqyig3ngc9ky4296kqhnjr2vzjkidsjlkqp8raalmw";
        };

        # should be build dependency, maybe, but as buildDependency it doesn't see sass executable in PATH
        buildInputs = [ gdk_pixbuf glib sass libxml2 ];
        buildPhase = ''
          make DESTDIR=$out
        '';

        prePatch = ''
          sed -i 's/Numix/Numix Solarized/g' index.theme
          export bkgrn=586e75
          export white=eee8d5
          export black=002b36
          sed -i 's/selected_bg_color: #[^\\n]*;/selected_bg_color: #'$bkgrn';/g' gtk-3.0/scss/_global.scss
          sed -i 's/selected_bg_color: #[^\\n]*;/selected_bg_color: #'$bkgrn';/g' gtk-3.20/scss/_global.scss
          sed -i 's/white: #fff;/white: #'$white';/g' gtk-3.0/scss/_global.scss
          sed -i 's/white: #fff;/white: #'$white';/g' gtk-3.20/scss/_global.scss
          sed -i 's/black: #000;/black: #'$black';/g' gtk-3.0/scss/_global.scss
          sed -i 's/black: #000;/black: #'$black';/g' gtk-3.20/scss/_global.scss
          sed -i 's/nselected_bg_color:#[^\\n]*\\n/nselected_bg_color:#'$bkgrn'\\n/g' gtk-2.0/gtkrc
        '';

        installPhase = ''
          install -dm 755 $out/share/themes/Numix\ Solarized
          cp -dr --no-preserve='ownership' {LICENSE,CREDITS,index.theme,README.md,gtk-2.0,gtk-3.0,gtk-3.20,metacity-1,openbox-3,unity,xfce-notify-4.0,xfwm4} $out/share/themes/Numix\ Solarized/
        '';

        meta = {
          description = "Numix Solarized GTK theme";
          homepage = http://bitterologist.deviantart.com/art/Numix-Solarized-417575928;
          license = stdenv.lib.licenses.gpl3;
          platforms = stdenv.lib.platforms.all;
        };
      };
```

**Comment by rnhmjoj** [comment]
Thanks, I'll try this way. Anyway, since murrine it's specified as a depencency of Arc it should be nix to correctly setup the environment.

**Comment by nico202** [comment]
OT @Pitometsu: would you mind PR numix-solarized-gtk? :)

**Comment by Pitometsu** [comment]
@nico202, I'm not using NixOS for now, sorry, feel free to reuse any my source code snippets.

**Comment by matthiasbeyer** [comment]
Can confirm, I'm using xfce with the Arc-dark theme

**Comment by joepie91** [comment]
Installing `gtk-engine-murrine` in `systemPackages` made the error go away for me. Unfortunately, my themes are still broken in the exact same way...

I'd imagine that the same applies for other missing theme engines.

**Comment by yegortimoshenko** [comment]
Nix can't propagate global environment variables from installed packages, so it is not currently possible to fix this issue for user-installed packages. However, it is rather easy to do for `environment.systemPackages` case via `propagatedUserEnvPkgs`.

I'll switch all themes that use custom engines to `propagatedUserEnvPkgs`.
