### ISSUE TITLE
Scarab Hollow Knight mod installer

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#162865]
**Project description**

Game mod installers are often fiddly to set up, which makes them a perfect match for reproducible Nix derivations. Scarab is a cross-platform mod installer for Hollow Knight. However, the [latest ELF executable](https://github.com/fifty-six/Scarab/releases/tag/v1.10.0.0) fails to run:

```console
$ ./Scarab 
bash: ./Scarab: No such file or directory
```

ELF description:

```console
$ file Scarab
Scarab: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0d78e22dc15d366dce0f9844639a3b96ac2e139d, for GNU/Linux 2.6.32, stripped, too many notes (256)
```

Fixing up the interpreter is not enough:

```console
$ nix-shell -p patchelf --run 'patchelf --set-interpreter "$(patchelf --print-interpreter $(which mkdir))" Scarab'
$ ./Scarab 
./Scarab: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

I also tried building the project with [some help](https://github.com/fsprojects/fantomas/issues/412#issuecomment-798774514):

```console
export DOTNET_ROOT=$(dirname $(realpath $(which dotnet)))
$ dotnet build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/username/dev/Scarab/Scarab.Tests/Scarab.Tests.csproj (in 328 ms).
  Restored /home/username/dev/Scarab/Scarab/Scarab.csproj (in 349 ms).
  GenerateAvaloniaResourcesTask -> Root: /home/username/dev/Scarab/Scarab, 3 resources, Output:obj/Debug/net6.0//Avalonia/resources
  avares -> name:/App.xaml, path: /home/username/dev/Scarab/Scarab/App.xaml, size:535, ItemSpec:App.xaml
  avares -> name:/Views/MainWindow.xaml, path: /home/username/dev/Scarab/Scarab/Views/MainWindow.xaml, size:298, ItemSpec:Views/MainWindow.xaml
  avares -> name:/Assets/omegamaggotprime.ico, path: /home/username/dev/Scarab/Scarab/Assets/omegamaggotprime.ico, size:124504, ItemSpec:Assets/omegamaggotprime.ico
  Scarab -> /home/username/dev/Scarab/Scarab/bin/Debug/net6.0/Scarab.dll
  GenerateAvaloniaResourcesTask -> Root: /home/username/dev/Scarab/Scarab.Tests, 0 resources, Output:obj/Debug/net6.0//Avalonia/resources
  Scarab.Tests -> /home/username/dev/Scarab/Scarab.Tests/bin/Debug/net6.0/Scarab.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.51
$ ./Scarab/bin/Debug/net6.0/Scarab
```

The application just returns immediately with exit code 0, but creates this log:

```text
$ cat ModInstaller_Error_22-03-05\ 22-20-24.log 
System.DllNotFoundException: Unable to load shared library 'libX11.so.6' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11.so.6: cannot open shared object file: No such file or directory
   at Avalonia.X11.XLib.XInitThreads()
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options) in /_/src/Avalonia.X11/X11Platform.cs:line 54
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0() in /_/src/Avalonia.X11/X11Platform.cs:line 279
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 303
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 186
```

At this point I'm not sure how to fix it, and less sure how to formulate the fix as a Nix expression.

**Metadata**

* homepage URL: https://github.com/fifty-six/Scarab
* source URL: https://github.com/fifty-six/Scarab
* license: gpl3
* platforms: linux, darwin

**Comment by l0b0** [comment]
[ModInstaller_Error_22-03-05 22-20-24.log](https://github.com/NixOS/nixpkgs/files/8190359/ModInstaller_Error_22-03-05.22-20-24.log)

**Comment by Leixb** [comment]
Usually `--set-interpreter` is not enough, you also need to add  `--set-rpath` with all the runtime dependencies. However, the best approach is to package using `autoPatchelfHook` which takes care of most of this work for you. All this is explained in https://nixos.wiki/wiki/Packaging/Binaries.

You can also try to run it using `steam-run` which often works out of the box for running precompiled binaries in nix.

**Comment by Leixb** [comment]
The package `icu` provides `libicu.so` in it's `dev` output. What they refer in the issue is that installing libraries in nixos is different from other systems in that you cannot simply add it with `nix-env` and expect things to work, the binary you run should have the library added manually in their `rpath` or `LD_LIBRARY_PATH` in order to find it.

`steam-run` should work since `icu` is part of the packages that are added in the steamFHS:
https://github.com/NixOS/nixpkgs/blob/683b9050a2c776e3773f6eb81857dc6be81158b4/pkgs/games/steam/fhsenv.nix#L101

Maybe you need to install `steam-run` along with steam? I am not sure why it doesn't work for you.

Putting `steam-run` aside, I have made this, which should work:

```nix
{ lib
, stdenv
, fetchzip
, autoPatchelfHook

, glib
, fontconfig

, icu
, libX11
, libICE
, libSM
, wrapGAppsHook
, gtk3
, gsettings-desktop-schemas
}:

stdenv.mkDerivation rec {
  pname = "scarab";
  version = "1.10.0.0";

  src = fetchzip {
    stripRoot = false;
    url = "https://github.com/fifty-six/Scarab/releases/download/v${version}/linux.zip";
    sha256 = "sha256-mzDJebGz5bRrBzdW9QTwUVsEsiL23XnOqoHJGunyc3U=";
  };

  nativeBuildInputs = [ autoPatchelfHook wrapGAppsHook ];

  buildInputs = [ glib fontconfig ];
  runtimeDependencies = [ icu libX11 libICE libSM gtk3 gsettings-desktop-schemas ];

  # Stripping breaks the binary
  dontStrip = true;

  installPhase = ''
    runHook preInstall

    install -Dm755 Scarab $out/bin/Scarab
    install -Dm755 libHarfBuzzSharp.so $out/lib/libHarfBuzzSharp.so
    install -Dm755 libSkiaSharp.so $out/lib/libSkiaSharp.so

    runHook postInstall
  '';

  preFixup = ''
    patchelf \
      --add-needed libHarfBuzzSharp.so \
      --add-needed libSkiaSharp.so \
      $out/bin/Scarab
  '';
}
```

I have been able to run the executable with this, but since I don't have Hollow Knight I cannot get past selecting the game folder, so I cannot be sure it works properly. Feel free to try it and modify it to your needs.

**Comment by huantianad** [comment]
@l0b0, I've just* submitted a PR, if you're still looking to use scarab check it out and lemme know if it works!

*just as in like 2 days ago :stuck_out_tongue:

**Comment by l0b0** [comment]
@huantianad Nice, thanks! I won't be able to test for probably a couple months for reasons™, though.

**Comment by l0b0** [comment]
Works for me, thank you!
