### ISSUE TITLE
Gitea service's option mailerPasswordFile does not work.

### ISSUE THREAD

**Issue by dit7ya** [NixOS/nixpkgs#162853]
### Describe the bug
`services.gitea.mailerPasswordFile` has no effect - it does not set the mailer password

### Steps To Reproduce
1. Enable gitea service with `mailerPasswordFile` option. 
  
  <details>
  <summary>For example, my current configuration is </summary>
  
```nix
  services.gitea = {
    enable = true; # Enable Gitea
    database = {
      type = "postgres"; # Database type
      passwordFile = ./gitea_password;

    };
    disableRegistration = true;
    domain = "redacted"; # Domain name
    rootUrl = "redacted"; # Root web URL
    httpPort = 5883; # Provided unique port
    mailerPasswordFile = config.sops.secrets.sopsGiteaMailerPassword.path;
    settings = {
      mailer = {
        ENABLED = true;
        FROM = "redacted@gmail.com";
        HOST = "smtp.gmail.com:587";
        USER = "redacted@gmail.com";
        MAILER_TYPE = "smtp";
        IS_TLS_ENABLED = false;
        HELO_HOSTNAME = "redacted";
      };
      repository = { DEFAULT_BRANCH = "main"; };
      service = { REGISTER_EMAIL_CONFIRM = true; };
      ui = {
        DEFAULT_THEME = "gitea"; # Set the default theme
      };
    };
  };

```
</details>

3. Rebuild and switch system.
4. Check the generated config file - `sudo bat /var/lib/gitea/custom/conf/app.ini`. The field `PASSWD` under `[[mailer]]` is empty.

### Expected behavior
Should have the correct password in that field and work in the app as well.

### Additional context

I am not exactly sure but seems like this line should have the opposite predicate.
https://github.com/NixOS/nixpkgs/blob/e3a60c19f8918c72d8fb556b52216ec8e90d6fb5/nixos/modules/services/misc/gitea.nix#L422

Using a Flakes managed NixOS config.

### Notify maintainers
@srhb @ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.76, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by aanderse** [comment]
This works for me. I'll assume this is no longer an issue. Please feel free to re-open if the problem still impacts you.
