### ISSUE TITLE
Package duplicates xdragon and dragon-drop

### ISSUE THREAD

**Issue by anpryl** [NixOS/nixpkgs#162874]
### Describe the bug
There are two same packages with different names: [xdragon](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/misc/xdragon/default.nix#L23) and [dragon-drop](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/tools/X11/dragon-drop/default.nix#L22).

I believe one of them can be removed and another one aliased to first.

**Comment by anpryl** [comment]
cc @dasJ  @jb55 @markus1189

**Comment by markus1189** [comment]
:+1: from my side, I have no preference but having both is unnecessary :)

**Comment by jb55** [comment]
dragon-drop was a random name that I gave it, xdragon probably makes more sense

**Comment by dasJ** [comment]
I have no preference either

**Comment by WolfangAukang** [comment]
> I have no preference either. We also ened to close #163058 if we choose to use dragon-drop instead of xdragon.

#162968 is also open (this for dragon-drop)
