### ISSUE TITLE
xmonad no man page

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nixpkgs#16282]
```
$ ls /nix/store/39c8vwxfbs9a3rba5ccbvcxc646q98ri-xmonad-0.12/share/man/man1/xmonad.1.gz
/nix/store/39c8vwxfbs9a3rba5ccbvcxc646q98ri-xmonad-0.12/share/man/man1/xmonad.1.gz
$ man 1 xmonad                                                                         
No manual entry for xmonad in section 1
```

**Comment by bennofs** [comment]
You need to install xmonad in either your system environment (using `systemPackages` in configuration.nix) or your user environment (using `nix-env`) to get the man pages. Just having the path in the store is not enough, it also needs to be in your environment.

**Comment by Pitometsu** [comment]
> Not sure if this is a bug, you probably got into this situation by using services.xserver.windowManager.enable = true to enable xmonad, right? Perhaps we should add the man pages for xmonad to the system configuration in that module.

This way, yep.
