### ISSUE TITLE
jetbrains.rider: 2021.2.2 -> 2021.3.3

### ISSUE THREAD

**Issue by tjmaynes** [NixOS/nixpkgs#162821]
**Project description**
Hi friends, I'm relatively new to NixOS (just got [everything set up](https://github.com/tjmaynes/config) nicely in a local VM and loving it) and I this is my first time requesting to contribute to an existing NixOS package. I'd like to submit a pull request to update `jetbrains.rider` to version `2021.3.3`, *however it looks like a script does this for the [jetbrains products](https://github.com/NixOS/nixpkgs/blob/ed02c2ba0384b2800db41333045a6fb781f12aac/pkgs/applications/editors/jetbrains/default.nix#L367)*.

Not sure how this works, if I need to do anything besides make an issue...

I'd like to get `jetbrains.rider` updated to this latest version so that I can properly work on `.NET Core 6` projects with Rider (version `2021.2.2` is quite buggy / not working for `.NET Core 6` development).

**Metadata**

* homepage URL: https://www.jetbrains.com/rider/
* source URL: https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/editors/jetbrains/default.nix#L187
* license: Unfree
* platforms: linux

**Comment by pinn3** [comment]
Rider 2021.3.3 is already up to date on master:
https://github.com/NixOS/nixpkgs/commit/94cd939c4928fffb552742f82a28c38bc3e6d9e9#diff-92872f639568a7606b70ab0cf6f7b2d80aaa64215c6843ac65dd4ef80bf1a510R372

**Comment by tjmaynes** [comment]
Thank you for the help @pinn3!
