### ISSUE TITLE
SIGTRAP in zathura-0.3.3 in print dialog.

### ISSUE THREAD

**Issue by halfflat** [NixOS/nixpkgs#16287]
## Issue description

When issuing the ':print' command from within zathura, performing actions within the print dialog will cause zathura to crash with a trace trap.

Printin
### Steps to reproduce
1. Open a pdf document with zathura.
2. Bring up the print dialog, by typing `:print` followed by the return key,
3. Select 'Print to File' (e.g. by pressing the tab key).
4. Click on the text entry box with label 'File:'.

zathura then exits with a trace trap.
## Technical details
- System: 16.03.931.2f1174b (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.931.2f1174b

**Comment by regnat** [comment]
I can reproduce it. According to strace, it fails trying to load gtk2 stuff, while it uses gtk-3. This is probably the cause. Some patches used in the build ([this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/zathura/djvu/gtkflags.patch) and [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/zathura/ps/gtkflags.patch)) refers to gtk2, this may be related.

**Comment by jtojnar** [comment]
The patches were removed in https://github.com/NixOS/nixpkgs/pull/37932. However, the crash was not actually caused by them but rather by missing GSettings schemas.
