### ISSUE TITLE
Packaging request: Decoder

### ISSUE THREAD

**Issue by zendo** [NixOS/nixpkgs#162982]
**Project description**
Scan and Generate QR Codes.

**Metadata**
* homepage URL: https://apps.gnome.org/en/app/com.belmoussaoui.Decoder/
* source URL: https://gitlab.gnome.org/World/decoder/
* license: GNU GPLv3
* platforms: linux

**Comment by bjornfor** [comment]
Why close? We don't have this in nixpkgs yet, right?

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/pull/193369

**Comment by bjornfor** [comment]
Nice!
