### ISSUE TITLE
package request: aioboto3

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#162953]
**Project description**

aioboto3 is a wrapper for boto3 using aiobotocore that allows asynchronous python calls for AWS APIs.

we already have its required and optional dependencies: aiobotocore, cryptography, chalice. Don't mind doing this myself just putting in the tracking issue.

**Metadata**

* homepage URL: https://pypi.org/project/aioboto3/
* source URL: https://github.com/terrycain/aioboto3
* license: Apache2
* platforms: unix, linux, darwin

**Comment by sheenobu** [comment]
the dependencies might be a little too restrictive. aiobotocore must be 2.1.0 (nixpkgs master has 2.1.1, easy to fix with sed) but boto3 and botocore must be:

```
boto3 = {version = ">=1.20.24,<1.20.25", optional = true, markers = "extra == \"boto3\""}
botocore = ">=1.23.24,<1.23.25"
```

which feels way to restrictive. Might ask upstream about options.

**Comment by sheenobu** [comment]
already answered: https://github.com/terrycain/aioboto3/issues/238

**Comment by natsukium** [comment]
introduced in https://github.com/NixOS/nixpkgs/pull/258824
