### ISSUE TITLE
Can't build unstable.kicad

### ISSUE THREAD

**Issue by mayl** [NixOS/nixpkgs#162913]
### Describe the bug
Was looking to upgrade to KiCAD 6, but get the below error related to wxWidgets when trying to build KiCAD from unstable

### Steps To Reproduce
Run `nix develop` with [this](https://github.com/mayl/kicadDevshell) flake.

### Expected behavior
Working KiCAD build.

### Screenshots
```
-- Found Phoenix 4.1.1/gtk3 (wxWidgets 3.1.5)
CMake Error at /nix/store/sgsvy949kd2sr2vsxcffz5jkv855rmib-cmake-3.22.2/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets: Found unsuitable version "3.1.4", but required is
  at least "3.1.5" (found
  -L/nix/store/pcc4pldpa2xwqh65gazrlvv2z5y9xmbs-wxwidgets-3.1.4/lib;-pthread;;;-L/nix/store/5lzlfgrc37wqj400b4qgpaa6kc9d2wr1-libglvnd-1.4.0/lib;-L/nix/store/04yj0nllw5bqzzlay5m6zzbmyw7csgnk-g>
Call Stack (most recent call first):
  /nix/store/sgsvy949kd2sr2vsxcffz5jkv855rmib-cmake-3.22.2/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindwxWidgets.cmake:1019 (find_package_handle_standard_args)
  CMakeLists.txt:876 (find_package)
```

### Notify maintainers
@evils @Kiwi

**Comment by Artturin** [comment]
wxWidgets was updated in https://github.com/NixOS/nixpkgs/pull/157848

its currently in staging-next so you may either use that branch or overlay the package
https://nixos.wiki/wiki/Nixpkgs/Reviewing_changes#Pre-flakes

**Comment by mayl** [comment]
thanks, building out of staging-next seems to be working
