### ISSUE TITLE
TexLive: biber is not available

### ISSUE THREAD

**Issue by jokogr** [NixOS/nixpkgs#16294]
## Issue description

The `biber` command is not available.

@vcunat could you help me start writing it?

So far I have something like this inside `bin.nix`:

```
biber = stdenv.mkDerivation {
  name = "texlive-biber.bin-${version}";

  inherit (common) src;
  # hardcode to extraction path
  prePatch = "cd texmf-dist/source/bibtex/biber/biblatex-biber-2.4";

  buildInputs = [ perl ];

  buildPhase = "perl Build.PL --prefix=$out; ./Build build";
  installPhase = "./Build install";
  checkPhase = "./Build test";

};
```

but even the source files are unavailable. Could you let me know how to proceed? My guess is that biber.source is not ending in bin.nix, so we can not use it effectively.

Cheers!

## Technical details

* System: NixOS 16.09.git.c3d5a0a (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.57c9997

**Comment by vcunat** [comment]
I can't see anything biber-related in texlive sources. Better than inherit `common.src`, you should fetch source from biber upstream, I think. There's a short note: http://tug.org/texlive/build.html#biber

**Comment by vcunat** [comment]
BTW, better not duplicate https://github.com/NixOS/nixpkgs/issues/10926.

**Comment by vcunat** [comment]
In particular, note that we do have a separate biber package that reportedly works in combination with our new texlive.
