### ISSUE TITLE
Packaging requests: nodePackages.ansible-language-server

### ISSUE THREAD

**Issue by sei40kr** [NixOS/nixpkgs#162986]
**Project description**

Ansible Language Server

**Metadata**

* homepage URL: https://als.readthedocs.io/en/latest/
* source URL: https://github.com/ansible/ansible-language-server
* license: mit
* platforms: all

**Comment by stasjok** [comment]
Probably should be closed by #197341.

**Comment by mweinelt** [comment]
Is now availabe as `ansible-language-server`.
