### ISSUE TITLE
grocy forced to run nginx

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#163113]
### Describe the bug
If i enable the module/service it force me to use nginx - during I have already an caddyserver running ....

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior
An switch to deactivate nginx.
Maybe add support for caddyserver (like in [jitsi-meet](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/nixos/modules/services/web-apps/jitsi-meet.nix))

### Notify maintainers

@ma27

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by spinus** [comment]
I guess this service/module is designed that way it utilizes specific software.
If you wish to use other configuration you should write your own module.
