### ISSUE TITLE
firefox-bin requires gtk2

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#163101]
### Describe the bug
firefox-bin package requires gtk2 despite firefox doesn't use gtk2 for a long time

### Steps To Reproduce
1. Install any of packages from the firefox-bin family

### Expected behavior
firefox-bin doesn't install gtk2 as dependency

### Additional context
https://bugzilla.mozilla.org/show_bug.cgi?id=1377445#c32

### Notify maintainers
@taku0 @lovesegfault 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.3-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(root): `"nixos-22.05pre338578.a2e281f5770"`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by spinus** [comment]
```
❯ nix why-depends 'nixpkgs/98bb5b77c8c#firefox-bin' 'nixpkgs/98bb5b77c8c#gtk2'
/nix/store/6g8za142kb84b1w5q4p95ppaax3pv98s-firefox-bin-97.0
    └───/nix/store/m3vx51rkxj8n6dpykk8z5nzd2k18ps2a-gtk+-2.24.33
❯ nix why-depends 'nixpkgs/98bb5b77c8c#firefox-bin' 'nixpkgs/98bb5b77c8c#gtk3'
/nix/store/6g8za142kb84b1w5q4p95ppaax3pv98s-firefox-bin-97.0
    └───/nix/store/gm9zbw0aanbx1jq6rwjmzd9d5h62kkrc-gtk+3-3.24.31
```
I can reproduce this for your commit, but cannot reproduce with current master, potentially it was fixed, can you confirm?

```
❯ nixos-version
22.05pre352357.98bb5b77c8c (Quokka)
❯ nix why-depends 'nixpkgs#firefox' 'nixpkgs#gtk2'
'/nix/store/x8wmlcy4mgr64r9pg0p1n6silixw0m83-firefox-97.0.2' does not depend on '/nix/store/hzf8pp6ddxfqif209s07iyjdy43gkmvw-gtk+-2.24.33'
❯ nix why-depends 'nixpkgs#firefox' 'nixpkgs#gtk3'
/nix/store/x8wmlcy4mgr64r9pg0p1n6silixw0m83-firefox-97.0.2
    └───/nix/store/38s9harni8shwjfl4m4x1z94niz6cqj7-gtk+3-3.24.31
```

**Comment by ilya-fedin** [comment]
You're checking firefox rather than firefox-bin in the second output :thinking:

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/blob/d3a37786fb2e84983b41eb8bc79c3a6816ea1903/pkgs/applications/networking/browsers/firefox-bin/default.nix#L14
https://github.com/NixOS/nixpkgs/blob/d3a37786fb2e84983b41eb8bc79c3a6816ea1903/pkgs/applications/networking/browsers/firefox-bin/default.nix#L113
