### ISSUE TITLE
x2goclient segfaults when trying to connect

### ISSUE THREAD

**Issue by pasqui23** [NixOS/nixpkgs#163122]
### Describe the bug
x2goclient segfaults when trying to connect to a client

### Steps To Reproduce
1. Open x2goclient
2. try to open a connection with it
3. segfaults

### Expected behavior
A connection is established

### Additional context

[Core dump](https://e1.pcloud.link/publink/show?code=XZSEVHZmDBkGuGXaybAtYUSxcIppkKey5VX)

### Notify maintainers
@mkg20001

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - nixpkgs: `/nix/store/531v6sf2db04x3xqphfkh7zg2dgw135k-source`

**Comment by 7FM** [comment]
I am having the same issue while using sway. Here is my current workaround: `QT_QPA_PLATFORM=xcb x2goclient` (see my [wrapper](https://github.com/7FM/nixos-dotfiles/blob/15801df90bf48153977b296e05529ac01e7cc6ce/home-manager/modules/submodule/x2go-wayland-wrapper.nix#L5)).
