### ISSUE TITLE
Overriding NixOS option definitions with my own

### ISSUE THREAD

**Issue by zackp30** [NixOS/nixpkgs#16311]
## Issue description

Sorry if this is in the wrong place.

I would like to override, for example, the file containing defining `services.sshd` (and all suboptions) with my own.

Basically, `services.sshd` and all suboptions would use my NixOS module (`zack-sshd`, for example), instead of the built-in Nixpkgs one.

### Steps to reproduce

[Not relevant]

## Technical details

* System: 16.09pre85363.886c03a (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre85363.886c03a

**Comment by rnhmjoj** [comment]
You can clone nixpkgs and do whatever changes you would like (services are defined in `nixos/modules/services`) locally. Then you just rebuild the system specifying your version of nixpkgs with


    $ nixos-rebuild -I nixpkgs=<path-to-your-nixpkgs> switch

Now you can use the option you have added/modified.

**Comment by zackp30** [comment]
Ah, of course! Thanks!
