### ISSUE TITLE
pipewire installs gtk2 via lv2 dependency

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#163121]
### Describe the bug
Enabling xdg-desktop-portal or pipewire audio support installs pipewire that installs lv2 as a dependency, that installs gtk as a dependency, apparently for configuration tools... It would be nice to separate those tools to a separate package to not to pollute every system using pipewire with gtk2.

### Steps To Reproduce
1. Activate xdg.portal.enable with gtk/kde backend or services.pipewire.enable

### Expected behavior
Enabling pipewire doesn't install gtk2

### Notify maintainers
@jtojnar @Kranzes @cillianderoiste

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.3-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - channels(root): `"nixos-22.05pre338578.a2e281f5770"`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/pull/159875

**Comment by ilya-fedin** [comment]
Looks like the PR is abandoned, so maybe leave the issue open until someone else would willing to fix this?
