### ISSUE TITLE
darwin.apple_sdk.frameworks.System appears to be broken (aarch64-darwin)

### ISSUE THREAD

**Issue by mikroskeem** [NixOS/nixpkgs#163215]
### Describe the bug

System.framework System.tbd symlink is broken and causes linker to fail (on aarch64-darwin).

nixpkgs rev 1fc7212a2c3992eedc6eedf498955c321ad81cc2

### Steps To Reproduce

```shell
$ cd /nix/store/ii0zyfqjjl10ww62735ngaxshlbrfnnn-apple-framework-System-11.0.0
$ cd Library/Frameworks/System.framework
$ readlink System.tbd # => Versions/Current/System.tbd
$ cd Versions/Current/
$ readlink System.tbd # => ../../../../../../usr/lib/libSystem.B.tbd
$ realpath ../../../../../../usr/lib/libSystem.B.tbd # => realpath: ../../../../../../usr/lib/libSystem.B.tbd: No such file or directory
```

### Expected behavior

Symlink not to be broken

### Notify maintainers

@NixOS/darwin-maintainers 

### Metadata
(irrelevant, found this from flake pinned nixpkgs 1fc7212a2c3992eedc6eedf498955c321ad81cc2)

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.3.0, macOS 12.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(mark): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/09nmz4s952xg31z18qqc47vp7lanvdk3-source`
```

**Comment by mikroskeem** [comment]
cc @copumpkin, marked as apple_sdk maintainer

**Comment by stefan0102** [comment]
Are the any news about this problem?

**Comment by wegank** [comment]
While the issue exists, `libSystem.B.tbd` actually resides in `darwin.apple_sdk_11_0.Libsystem`, and almost all occurrences of `-framework System` can be replaced by `-lSystem`. I guess that's why it hasn't been fixed so far.
