### ISSUE TITLE
can't install mysql-workbench because dependency used older python

### ISSUE THREAD

**Issue by bastomiadi** [NixOS/nixpkgs#163258]
### Describe the bug
Error when building mysql-workbench

### Steps To Reproduce
1. add mysql-workbench in : sudo nano /etc/nixos/configuration.nix 
2. then sudo nixos-rebuild switch
3. pynacl-1.4.0 must be using 3.7 python version or newer (3.9) not 2.x, check here : https://python.on-nix.com/

### Expected behavior
Can Install mysql-workbench in nix-system,
Update this package for suitable using installed phyton in machine

### Screenshots
![Screenshot_20220306_043906](https://user-images.githubusercontent.com/13336571/157168936-b209a111-8e5b-486c-a7ab-b1aca41b3389.png)

### Metadata
bastomi@nugrohoeku:~/ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.11, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336340.2ebb6c1e5ae"`
 - channels(bastomi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bastomiadi** [comment]
So how to install it ?

**Comment by Narice** [comment]
@bastomiadi unfortunately, you can't :/
You can try replacing it by dbeaver or squirrel sql client, but I know it's not the same.
you can install these with nix or [flatpak](https://flathub.org/apps/search/sql)
I hope this is useful to you ;)

**Comment by rnhmjoj** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/191174.

**Comment by Narice** [comment]
woaw nice, thanks!

**Comment by kennethbruskiewicz** [comment]
I need to use this particular version of MySQL Workbench, would it be possible to pin a version pynacl that works?
