### ISSUE TITLE
Firefox - consider enabling Wayland by default

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#163206]
### Describe the bug

ref: https://www.phoronix.com/scan.php?page=news_item&px=Firefox-98.0

It sounds like:
- other distros are doing it
- it's about hesitancy around other bits of the user/gpu-space, where we know we're pretty up-to-date

It might also be overkill, we have `firefox-wayland`, but I'm also eager to test out the soon-to-be default path asap - I've been waiting for firefox+wayland for way, way too long.

**Comment by Abdillah** [comment]
Firefox Wayland currently shows undefined icon on GNOME shell.
This may be a blocking issue.

![Screenshot from 2022-03-22 16-26-16](https://user-images.githubusercontent.com/3030950/159449357-46668049-3286-4e3b-b07c-7e5fa1a10f92.png)

**Comment by jtojnar** [comment]
That is #165107

**Comment by mweinelt** [comment]
I'm not exactly sure how this is actionable. They cite that Ubuntu and Fedora carry "the patches", which is big boy words for very small real world changes.

- Ubuntu enables `MOZ_ENABLE_WAYLAND` 1y ago in a wrapper shellscript, just like `firefox-wayland` does
  https://bazaar.launchpad.net/~mozillateam/firefox/firefox.hirsute/revision/1478
- Fedora enables `MOZ_ENABLE_WAYLAND` 4y ago in a wrapper shellscript (`firefox-wayland.sh.in`) that gets used in `firefox-wayland.desktop`
  https://src.fedoraproject.org/rpms/firefox/c/c45606f4574eb364f78af13cde501c02c2207228?branch=rawhide
