### ISSUE TITLE
gnome-remote-desktop incompletely enables PipeWire, breaks audio and video playback

### ISSUE THREAD

**Issue by alyaeanyx** [NixOS/nixpkgs#163399]
### Describe the bug
The option `services.gnome-remote-desktop.enable = true` (enabled by default on GNOME) causes PipeWire to be enabled incompletely (https://github.com/NixOS/nixpkgs/blob/062a0c5437b68f950b081bbfc8a699d57a4ee026/nixos/modules/services/desktops/gnome/gnome-remote-desktop.nix#L28), i.e. without enabling ALSA/PulseAudio/Jack support. Since the switch to WirePlumber, this breaks all audio and video playback on some systems (see #163066).

As far as I can tell, the best option would be to disable gnome-remote-desktop by default, remove the `services.pipewire.enable = true` declaration from it, and add an assertion to let the user know that PipeWire must be enabled for gnome-remote-desktop to work.

**Comment by bobby285271** [comment]
FYI there is a pending pull request that tries to make GNOME be pipewire by default #163075

**Comment by jtojnar** [comment]
Should be fixed by #165231
