### ISSUE TITLE
Container interface is not removed when declarative container is removed.

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#16330]
## Issue description

Container interface is not removed when declarative container is removed. They are removed only after reboot
### Steps to reproduce

Add a declarative container `test-1`, rebuild systemd, remove container, rebuild system, observe `ve-test-1` in `ifconfig`.
## Technical details
- System: 16.03.946.256ebc4 (Emu)

**Comment by danbst** [comment]
Note to future me: this doesn't happen with bridged interfaces

**Comment by fpletz** [comment]
Is this still happening?

**Comment by danbst** [comment]
Yes. Here is minimal example:
```
  containers.test-eth = {
    privateNetwork = true;
    hostAddress = "10.231.136.1";
    localAddress = "10.231.136.2";
    autoStart = true;
    config = {};
  };
```
Rebuild, then rename container to `test-eth2`, and rebuild again. Observe:
```
$ nixos-container list                                                                                                                                    
test-eth2

$ ifconfig | grep ve-                                                                                                                                     
ve-test-eth: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500                                                                                                                                               
ve-test-eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
```

**Comment by pschuprikov** [comment]
I am not sure if the bug is still present, I've failed to reproduce it locally on 18.09 and using a VM (through `makeTest`) on both 18.09 (37694c8cc0e9ecab60d06f1d9a2fd0073bcc5fa3) and 19.03 (9055b33db045c55ccd669baeef9a2e98eeadeca7). For some reason, the VM test does not boot on 1e1472ed93e1256dfdac4908ae8edcb90ceff21c.

**Comment by danbst** [comment]
Indeed, no longer reproducible. Which is :+1:
