### ISSUE TITLE
Packaging request: bump version for clang-tool from 13 to 14

### ISSUE THREAD

**Issue by lednakashim** [NixOS/nixpkgs#163363]
Looks like clang14 is available but it would be good to have a matching version of the clang-tools package (which is on the previous version)

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=clang-tools

**Comment by linusg** [comment]
The default `clang-tools` now ships version 14.0.6, so I think this issue is solved (and needs to be replaced a bump from 14 to 15 :smile:)
