### ISSUE TITLE
haskell: cache intermediate files

### ISSUE THREAD

**Issue by knupfer** [NixOS/nixpkgs#16336]
It would speed up compilation considerably in many cases if intermediate outputs like .hi and .o are put into individual store paths. This would increase granularity of dependency tracking.
This would allow compilation caching between different versions of the same library.

**Comment by peti** [comment]
That would be a tool like `ccache`, but for Haskell, I suppose. This seems a little out of the scope of Nix, to be honest, and I don't believe that anyone would work on such a feature in the foreseeable future.
