### ISSUE TITLE
Pandoc update to 2.17

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs#163329]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`pandoc`

current version: 2.14.0.3
desired version: at least 2.17.0.0. Newest upstream is 2.17.1.1

###### Notify maintainers

@peti

###### Note for maintainers

Please tag this issue in your PR.

**Comment by rnhmjoj** [comment]
The next haskell-update [merge](https://github.com/NixOS/nixpkgs/pull/160733) will bring it to 2.17.1.1 on master.
