### ISSUE TITLE
please add package for gnu/stubs-32.h

### ISSUE THREAD

**Issue by FrancescoSpena** [NixOS/nixpkgs#163376]
**Project description**
_describe the project a little_

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by hqurve** [comment]
Im on nixos-unstable. Its already provided by the `glibc_multi.dev` derivation

```
❯ nix-locate gnu/stubs-32.h
zig.out                                             448 r /nix/store/135516hhwj4isshq97dr3y05wv252072-zig-0.9.1/lib/zig/libc/include/generic-glibc/gnu/stubs-32.h
zig_0_8_1.out                                       448 r /nix/store/la412lscipj709va2gjb1fxq2iqblvl9-zig-0.8.1/lib/zig/libc/include/generic-glibc/gnu/stubs-32.h
(zulip.out)                                         449 r /nix/store/3wxmsgdxjwn25b7m1zxf0n2js7vr7f7b-glibc-2.33-108-dev/include/gnu/stubs-32.h
vscode-extensions.tiehuis.zig.out                   490 r /nix/store/0w4jppbyjf2x39nq6l8ir8zsqddmacdy-vscode-extension-tiehuis-zig-0.2.5/share/vscode/extensions/tiehuis.zig/zig-cache/lib/zig/libc/include/generic-glibc/gnu/stubs-32.h
(steam-run-native.out)                              537 r /nix/store/dhcjqsvr0kynlx39mpfqagkydgclcdlf-bootstrap-tools/include-glibc/gnu/stubs-32.h
remarkable-toolchain.out                            295 r /nix/store/b72saf0185jkppyhr6y8ddshmikv2ls8-remarkable-toolchain-3.1.2/sysroots/cortexa9hf-neon-remarkable-linux-gnueabi/usr/include/gnu/stubs-32.h
remarkable2-toolchain.out                           295 r /nix/store/fdnbgb8silbsbdlcszalwjvm1w2ml6sh-remarkable2-toolchain-3.1.2/sysroots/cortexa7hf-neon-remarkable-linux-gnueabi/usr/include/gnu/stubs-32.h
glibc_multi.dev                                       0 s /nix/store/m1mgv4kzqiisg94cq17pbc7rkf08wkh5-glibc-multi-2.33-108-dev/include/gnu/stubs-32.h

```

**Comment by FrancescoSpena** [comment]
This is not true.
I installed this derivation "glibc_multi.dev" but it didn't work.
I compile with command:

gcc -m32 -o name_output file1.c file2.s




Il giorno mer 9 mar 2022 alle ore 22:05 hqurve ***@***.***>
ha scritto:

**Comment by hqurve** [comment]
How did you install it?

Loading it in a shell works just fine. If I have a file `a.c`

```
#include <gnu/stubs-32.h>

int main(){
}
```

and then 

```
❯ nix-shell -p gcc glibc_multi
❯ gcc a.c
❯ 

```
however, if i just load gcc

```

❯ nix-shell -p gcc

❯ gcc a.c
a.c:1:10: fatal error: gnu/stubs-32.h: No such file or directory
    1 | #include <gnu/stubs-32.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
❯        
```

**Comment by FrancescoSpena** [comment]
yes, this is true but I need to fill in gcc and with option -m32 otherwise
the program goes into seg fault because i use in the file assembly of the
instructions that are compatible with 32-bit only.

I don't know if you can help me understand how to compile in 32-bit
without the site giving me errors of libraries not included.


Il giorno mer 9 mar 2022 alle ore 23:39 hqurve ***@***.***>
ha scritto:

**Comment by hqurve** [comment]
Currently im trying https://nixos.org/guides/cross-compilation.html with gnu32 instead of `aarch64-multiplatform` however ... its still compiling musl. But there may be another way (will confirm if it works)

**Comment by hqurve** [comment]
In the meantime though, perhaps you can make a post on the discourse asking for help

**Comment by hqurve** [comment]
Okay, decided to take my own guidance and found [this post](https://discourse.nixos.org/t/how-do-i-compile-32-bit-assembly-with-gcc/6205). Apparently its as simple as using `pkgsi686Linux`.

For example, with a shell.nix file

```
{
  nixpkgs ? import <nixpkgs> {},
  pkgs ? nixpkgs.pkgsi686Linux
}:
with pkgs;
mkShell {
  # builtInputs = [glibc]; # not required since mkShell already pulls this dependency. Also note that it automatically uses the glibc with the 32bit header file
}
```

Then enter the shell with `nix-shell` and then `$CC a.c`. Also, to prove that its indeed compiling to a 32bit, `file` reports

```
a.out: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /nix/store/n8k71gd1a759s9mmi85iinfdb0ckkzkv-glibc-2.33-108/lib/ld-linux.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped

```
