### ISSUE TITLE
physlock doesn't work with suspend-then-hibernate

### ISSUE THREAD

**Issue by NomisIV** [NixOS/nixpkgs#163377]
### Describe the bug
According to the source code in the physlock module, it should activate on suspend (enabled by default) or on hibernation (also enabled by default) or suspend-then-hibernate if either suspend or hibernate are active.

https://github.com/NixOS/nixpkgs/blob/6bda3341faccbf5f6c30dbcdda0c4d435c755060/nixos/modules/services/security/physlock.nix#L113-L115

However, physlock does not trigger on suspend-then-hibernate.

### Steps To Reproduce
1. add `services.physlock.enable = true;` to config
2. add `services.logind.lidSwitch = "suspend-then-hibernate";` to config
3. run `systemd suspend-then-hibernate`, or close the laptop lid
4. Wake the computer, and you will be greeted with an open session

### Expected behavior
Physlock would trigger and lock the session, like the module declares. (I really don't know why it doesn't)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0pre20220127_558c4ee`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by NomisIV** [comment]
I can't reproduce this anymore, so I'll assume this is somehow fixed.

**Comment by pgarrison** [comment]
I am having this issue, just as described

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.11 (Raccoon), 22.11.20220618.e0a4226`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by magnetophon** [comment]
I'm also still having this issue.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.46, NixOS, 22.11 (Raccoon), 22.11pre386147.e0a42267f73`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(bart): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pgarrison** [comment]
Reopened as #178478
