### ISSUE TITLE
firefox can't build like pan package

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#163355]
### Describe the bug

Firefox can't be easily built like the `pan` package in a way matching the Nix manual. 

https://nixos.org/manual/nix/stable/introduction.html#managing-build-environments says:

> For example, the following command gets all dependencies of the Pan newsreader, as described by [its Nix expression](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/newsreaders/pan/default.nix):

```
`$ nix-shell '<nixpkgs>' -A pan`
<various output followed by >
unpacking source archive /nix/store/17md5j18x30jnbqxx7x2kwk2hzayhha7-pan-0.146.tar.bz2
<more output>
```
If you then replace `pan` by `firefox`:
```
`$ nix-shell '<nixpkgs>' -A firefox`, we have:

[nix-shell:~]$ unpackPhase 
variable $src or $srcs should point to the source
exit
```
### Expected behavior
Running `unpackPhase` should unpack `firefox` source code (and running the other phases would eventually result in a working build of `firefox`). In fact, if you wanted to write a test for this functionality, it could do this for every package in all-packages.nix, because the expectation of the nix-shell functionality within the context of nixpkgs is exactly that one can easily get a development environment going for a given package and for example not have to hunt for the sources yourself such that unpackPhase will get you a build directory with the source code.

## Additional information

This bug belongs in nixpkgs (and not in nix), because apparently it does work for `pan`.

### Notify maintainers

@eelco @lovesegfault @hexa

### Metadata
21.11 stable

**Comment by lovesegfault** [comment]
Try using `firefox-unwrapped`?

**Comment by 21stce** [comment]
That works (didn't wait for the whole thing to complete, but at least it started to download llvm, etc.), but I think it's still a  undesirable.

I doubt there is an actually good reason for breaking this property. 

How is a user supposed to know whether they should use the unwrapped version? In the case of pan, there is no unwrapped version. 

Here is someone else with the same question, so it does generate confusion: 
https://discourse.nixos.org/t/how-to-tell-the-difference-between-wrapped-and-unwrapped-package/6823

> Given a Nix expression that describes the dependencies of your package

I suppose the author here is talking about a `derivation`, but doesn't want to use technical language on purpose. 

I suppose this is the root cause of my misunderstanding here. In the case of `pan`, it probably is just an expression describing a derivation, but in the case of firefox it is not. Having some tool, which would find the "Nix expression that describes the dependencies" of a given query would then be useful, which probably also already exists.

As a user, I would like to just be able to run `nix develop -A firefox # or something similar` and have it figure out something useful it can do to get a shell in which `unpackPhase` unpacks firefox, etc.

**Comment by Artturin** [comment]
`firefox` is the unwrapped firefox wrapped with `wrapFirefox`

Many other packages reuse the same wrapper 
```nix
  firefox-unwrapped = firefoxPackages.firefox;
  firefox-esr-91-unwrapped = firefoxPackages.firefox-esr-91;
  firefox = wrapFirefox firefox-unwrapped { };
  firefox-wayland = wrapFirefox firefox-unwrapped { forceWayland = true; };
  firefox-esr-91 = wrapFirefox firefox-esr-91-unwrapped { };

  firefox-esr = firefox-esr-91;
  firefox-esr-unwrapped = firefoxPackages.firefox-esr-91;
  firefox-esr-wayland = wrapFirefox firefox-esr-91-unwrapped { forceWayland = true; };

  firefox-bin-unwrapped = callPackage ../applications/networking/browsers/firefox-bin {
    inherit (gnome) adwaita-icon-theme;
    channel = "release";
    generated = import ../applications/networking/browsers/firefox-bin/release_sources.nix;
  };

  firefox-bin = wrapFirefox firefox-bin-unwrapped {
    pname = "firefox-bin";
  };

  firefox-beta-bin-unwrapped = firefox-bin-unwrapped.override {
    inherit (gnome) adwaita-icon-theme;
    channel = "beta";
    generated = import ../applications/networking/browsers/firefox-bin/beta_sources.nix;
  };

  firefox-beta-bin = res.wrapFirefox firefox-beta-bin-unwrapped {
    pname = "firefox-beta-bin";
    desktopName = "Firefox Beta";
  };

  firefox-devedition-bin-unwrapped = callPackage ../applications/networking/browsers/firefox-bin {
    inherit (gnome) adwaita-icon-theme;
    channel = "devedition";
    generated = import ../applications/networking/browsers/firefox-bin/devedition_sources.nix;
  };

  firefox-devedition-bin = res.wrapFirefox firefox-devedition-bin-unwrapped {
    nameSuffix = "-devedition";
    pname = "firefox-devedition-bin";
    desktopName = "Firefox DevEdition";
  };

  librewolf-unwrapped = firefoxPackages.librewolf;

  librewolf = wrapFirefox librewolf-unwrapped {
    inherit (librewolf-unwrapped) extraPrefsFiles extraPoliciesFiles;
    libName = "librewolf";
  };
```

There are more wrapThing wrappers in nixpkgs as they allow us to reuse code.


Theres probably no way to transparently open the nix shell in the unwrapped drv when the wrapped drv is passed

To find the unwrapped drv for a wrapped firefox
`firefox.unwrapped` can be used  
https://github.com/NixOS/nixpkgs/blob/0a6fa5ec69dbe8eff77cf3dc6311f3de065be724/pkgs/applications/networking/browsers/firefox/wrapper.nix#L347

**Comment by Artturin** [comment]
Also it allows us to change wrapper settings without recompiling the browser

**Comment by lovesegfault** [comment]
As Artturin said, wrappers are very common in nixpkgs. I'm closing this as solved :)

**Comment by Artturin** [comment]
As a sidenote, if there's wrappers in nixpkgs which don't have the unwrapped drv in it's passthru then that should be added.
