### ISSUE TITLE
pkgs.haskell.packages.ghc7103.vector-algorithms is not building

### ISSUE THREAD

**Issue by luispedro** [NixOS/nixpkgs#16343]
## Issue description

`pkgs.haskell.packages.ghc7103.vector-algorithms` is not building on current master (or in the nixos-unstable channel).

The package `pkgs.haskell.packages.ghc801.vector-algorithms`  does build, however.

### Steps to reproduce

    nix-build . -A pkgs.haskell.packages.ghc7103.vector-algorithms

Leads to

    Setup: At least the following dependencies are missing:
    mtl -any, mwc-random -any

These dependencies seem to be needed for benchmarking only.

## Technical details

* System:
NixOS 16.03.909.f199be0 (Emu)
(but same thing on other systems)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
master & nixos-unstable

**Comment by deepfire** [comment]
It doesn't seem to build on the stable channel either.

Paging @peti ..

**Comment by deepfire** [comment]
Please, disregard the above message, `nixos-16.03` channel is fine -- a configuration issue creeped in.

**Comment by peti** [comment]
If someone submits a PR to fix this I'd be happy to merge it.

**Comment by dhess** [comment]
This bug still exists in master, does it not?

**Comment by obadz** [comment]
@LnL7 took care of it with b8a3174

**Comment by puffnfresh** [comment]
@obadz coincidentally I was looking into it this morning and just filed an issue with cabal2nix:

https://github.com/NixOS/cabal2nix/issues/238
