### ISSUE TITLE
PR Action builds Nix from scratch

### ISSUE THREAD

**Issue by ckiee** [NixOS/nixpkgs#163467]
### Describe the bug

For some reason, the PR eval action [builds Nix](https://github.com/NixOS/nixpkgs/runs/5482619456?check_suite_focus=true#step:4:6980) on a [trivial PR](https://github.com/NixOS/nixpkgs/pull/163465/files). That is rather obviously a big waste of CPU time and energy.

### Notify maintainers

@Mic92 @zowoq
```
# GitHub actions
/.github/workflows @NixOS/Security @Mic92 @zowoq
```

**Comment by zowoq** [comment]
ping @domenkozar

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/163510

**Comment by Artturin** [comment]
Well spotted!
