### ISSUE TITLE
postgresql_14: 14.1 -> 14.2

### ISSUE THREAD

**Issue by sekunho** [NixOS/nixpkgs#163403]
Latest version bump (14.0 -> 14.1): https://github.com/NixOS/nixpkgs/commit/85852b941d8e0888a98f1a21ac0a43875ccf7073

There are other non-14 versions that need to be bumped as well:

- `postgresql_13`: 13.5 -> 13.6 (Latest version bump (13.4 -> 13.5) https://github.com/NixOS/nixpkgs/commit/67abda7877aaf6af6f04be25fdff424302486d2f)
- `postgresql_12`:  12.9 -> 12.10 (Latest version bump (12.8 -> 12.9) https://github.com/NixOS/nixpkgs/commit/c046c5d6ff02699d5dbe7fb5287c56abd83af15d)
- `postgresql_11`:  11.14 -> 11.15 (Latest version bump (11.13 -> 11.14) https://github.com/NixOS/nixpkgs/commit/b701405be7879df38f3aebbc150f6b925ab2e9a1)
- `postgresql_10`: 10.19 -> 10.20 (Latest version bump (10.18 -> 10.19) https://github.com/NixOS/nixpkgs/commit/1d35ef9ee0951c0870484e7b8981b27a821e843b)

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `postgresql_14`

current version: 14.1
desired version: 14.2

###### Notify maintainers

maintainers: @marsam 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by marsam** [comment]
This was addressed by https://github.com/NixOS/nixpkgs/pull/159674, and it's already in `staging-next`. It will land into unstable one of these days.
<p align="center">
<a href="https://nixpk.gs/pr-tracker.html?pr=159674"><img width="500" alt="image" src="https://user-images.githubusercontent.com/65531/157371836-0ec5b053-28f1-4845-8f89-b5887579d6df.png"></a>
</p>

**Comment by sekunho** [comment]
Agh, my bad. Having a hard time searching through the PRs. Thanks!
