### ISSUE TITLE
fluffychat: 1.11.1

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#163515]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 1.10.0
desired version: 1.11.1

###### Notify maintainers

maintainers: @mkg20001

###### Note for maintainers

Please tag this issue in your PR.

**Comment by genofire** [comment]
next minor version is released ...

**Comment by genofire** [comment]
1.5.0 released on 2022-06-04

**Comment by mindmeshlink** [comment]
1.8.0 was released  2022-12-30, for what that's worth.

**Comment by NickCao** [comment]
https://github.com/NixOS/nixpkgs/blob/60c84c8841fb3eef80f28e942a52b601625ed0c0/pkgs/applications/networking/instant-messengers/fluffychat/default.nix#L10
