### ISSUE TITLE
mate-utils pulls inkscape to the system

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#163590]
### Describe the bug
It seems, inkscape is a build-only dependency of mate-utils, but wrapGAppHook makes it a runtime dependency

### Steps To Reproduce
1. Install mate-utils

### Expected behavior
mate-utils doesn't pull inkscape

### Notify maintainers
@johannesloetzsch @romildo

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.8-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0pre20220221_caf5172`
 - channels(root): `"nixos-22.05pre338578.a2e281f5770"`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by romildo** [comment]
In fact `inkscape` appears in the binary wrappers, in the definition of `XDG_DATA_DIRS`. Not being a runtime dependence, it should not.

I suppose this should be fixed in `wrapGAppsHook`.

**Comment by ilya-fedin** [comment]
By runtime dependency I mean it's installed with binary package

**Comment by romildo** [comment]
In the derivation it appears in `nativeBuildInputs`, making it a build dependence.

Probably the fact that it is mentioned in the binary wrappers created by `wrapGAppsHook` has the consequence of turning it into a runtime dependence.

**Comment by ilya-fedin** [comment]
Yeah, I see :(
Who is maintainer of wrapGAppsHook though?

**Comment by romildo** [comment]
cc @jtojnar

**Comment by jtojnar** [comment]
It probably gets picked up by `hicolorIconThemeHook` into `XDG_ICON_DIRS`, which then `gappsWrapperArgsHook` puts to `XDG_DATA_DIRS` inside `gappsWrapperArgs`.

**Comment by jtojnar** [comment]
I am not sure why would we even want to add the data directories of icon dependencies into `XDG_DATA_DIRS`. The app’s own icons should be covered by https://github.com/NixOS/nixpkgs/blob/b3b026509758cebbaa4e3173c1f1531102b28b64/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L27, and adding icon themes like `adwaita-icon-theme` will not work unless the user also configures the system to use that theme (in which case they should have the theme installed). Or the package contains icons in the fallback (`hicolor`) theme – but that should mostly just contain application icons (not something most apps would want to use).

**Comment by ilya-fedin** [comment]
I know Qt has API QIcon::setThemeName, so if gtk has something simillar, appications can distribute their own icons in separate packages and then pick up with such API

**Comment by jtojnar** [comment]
Sure, but I would not expect that to be common – not even Pantheon does that.

**Comment by jtojnar** [comment]
So I would suggest just removing this code:

https://github.com/NixOS/nixpkgs/blob/b3b026509758cebbaa4e3173c1f1531102b28b64/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L18

It can cause unintended fallout in cases where it picks up stuff like Vala vapi files but I would expect it to be pretty minor – `share/icons` exists mostly just in app packages, not libraries.

**Comment by abathur** [comment]
Closing since it sounds like this was fixed by the merge of https://github.com/NixOS/nixpkgs/pull/163623. Happy to reopen if I'm mistaken.
