### ISSUE TITLE
`jesec-libtorrent` should be merged in to `libtorrent-jesec`

### ISSUE THREAD

**Issue by luzpaz** [NixOS/nixpkgs#163578]
Found via [repology](https://repology.org/projects/?search=libtorrent&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=)  
![Screenshot_20220310_112628](https://user-images.githubusercontent.com/4140247/157708760-0294bee4-7638-43f3-bbf9-b6859db2cb28.png)

Is there a reason why these are split in to 2 different directories?

https://github.com/NixOS/nixpkgs/blob/release-21.11/pkgs/tools/networking/p2p/jesec-rtorrent/
https://github.com/NixOS/nixpkgs/blob/release-21.05/pkgs/tools/networking/p2p/libtorrent-jesec/

**Comment by roblabla** [comment]
It isn't split. It was renamed between 21.05 and 21.11 from libtorrent-jesec to jesec-libtorrent: https://github.com/NixOS/nixpkgs/commit/07e7d46e0c7ea23ad30ed7b55b040886dee94852

**Comment by luzpaz** [comment]
oh ok. thx. closing
