### ISSUE TITLE
Home Assistant module: Use Postgresql

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#163580]
### Describe the bug
Right now the Home Assistant module packaged in NixOS uses sqlite. 

Perhaps sqlite is useful on resource constrained installations of HA, but on systems with more capacity using Postgresql would be better. 

## Version of nixpkgs
All containing Home Assistant (reported when 21.11 was stable)

**Comment by mweinelt** [comment]
https://nixos.wiki/wiki/Home_Assistant#Using_PostgreSQL

**Comment by 21stce** [comment]
I am looking for something of the form 
```service.home-assistant.databaseBackend = "postgresql";``` 

and also in a way that would be considered a production setup.

**Comment by mweinelt** [comment]
Please use the documented way, I'm not going to implement anything else. This is as close as production gets.
