### ISSUE TITLE
qutebrowser.aarch64-linux broken due to pyqt5 not building the correct wheel

### ISSUE THREAD

**Issue by collinarnett** [NixOS/nixpkgs#163589]
### Describe the bug
[qutebrowser.aarch64-linux](https://hydra.nixos.org/job/nixpkgs/trunk/qutebrowser.aarch64-linux) is currently broken on hydra because of [python39Packages.pyqt5.aarch64-linux](https://hydra.nixos.org/job/nixpkgs/python-updates/python39Packages.pyqt5.aarch64-linux) 

### Steps To Reproduce
1. https://hydra.nixos.org/build/168939903/nixlog/1 - Leads to...
```
Successfully built PyQt5
Finished creating a wheel...
Finished executing pipBuildPhase
glibPreInstallPhase
glibPreInstallPhase
installing
Executing pipInstallPhase
/build/PyQt5-5.15.4/dist /build/PyQt5-5.15.4
ERROR: PyQt5-5.15.4-cp36-abi3-manylinux1_aarch64.whl is not a supported wheel on this platform.
```
### Expected behavior
PyQt5 should build the python3.9 version of the wheel. It is currently building the python3.6 version.

### Additional context
I'm not sure if this is an upstream issue or part of the derivation.

### Notify maintainers
@svanderburg

### Metadata
First known broken build of qutebrowser.
https://hydra.nixos.org/build/163538155

Which points to broken pyqt build.
https://hydra.nixos.org/build/160964258

**Comment by mhuesch** [comment]
I am also encountering the same issue:

```
ERROR: PyQt5-5.15.4-cp36-abi3-manylinux1_aarch64.whl is not a supported wheel on this platform.
```

I am not building qutebrowser and am not sure what depends on PyQt in my case, but seems like PyQt is the issue.

**Comment by a-m-joseph** [comment]
I am seeing this as well.

**Comment by a-m-joseph** [comment]
I was able to get the build to finish by manually unzipping the file `PyQt5-5.15.4-cp36-abi3-manylinux1_aarch64.whl` left behind by the failed build, changing `manylinux1` to `linux` in the `WHEEL` file, re-zipping the archive, and renaming it to again change `manylinux1` to `linux`.

According to [this](https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/) webpage, `manylinux1` should only be used by i386 and amd64 -- it predates python support for any other platform, such as arm64.

Unfortunately I don't know much about python, or "wheels".

**Comment by tpwrules** [comment]
Fixed on master: https://hydra.nixos.org/build/171187629

**Comment by a-m-joseph** [comment]
I think this can be closed.
