### ISSUE TITLE
graylog : the system group graylog is not created by the nixos module

### ISSUE THREAD

**Issue by Pascal-Vtx** [NixOS/nixpkgs#163571]
### Describe the bug

The graylog NixOS module creates a system user 'graylog' with a group of the same name but the group is never created.

The following expression does nothing :
https://github.com/NixOS/nixpkgs/blob/9548cdc0a529b3df4baba3f34f631e404d0d1b22/nixos/modules/services/logging/graylog.nix#L135

It should be either :
```nix
{
 users.groups = mkIf (cfg.user == "graylog") {  graylog = {}; }; 
}
```
or
```nix
{
 users.groups.graylog = mkIf (cfg.user == "graylog") {}; 
}
```

### Steps To Reproduce

1. enable the  nixos services.graylog  module
2. a warning about unknown 'graylog' group should appear when switching to the new nixos configuration
```console
[root@system:~]# nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
...
building '/nix/store/34pmkz6cj135pccrd306c5jzqdj3j5q0-nixos-system-nixos-21.11.336340.2ebb6c1e5ae.drv'...
updating GRUB 2 menu...
activating the configuration...
warning: user ‘graylog’ has unknown group ‘graylog’
setting up /etc...
reloading user units for root...
setting up tmpfiles
reloading the following units: dbus.service
the following new units were started: graylog.service
...
```
3. we can see that as a fallback the nogroup is used instead
```console
[root@system:~]# groups graylog
graylog : nogroup
```

### Expected behavior

```console
[root@system:~]# groups graylog
graylog : graylog
```

### Notify maintainers
@symphorien

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.102, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336340.2ebb6c1e5ae"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by symphorien** [comment]
Thanks for reporting. Your first proposition
```
{
 users.groups = mkIf (cfg.user == "graylog") {  graylog = {}; }; 
}
```
looks good to me. Would you mind opening a PR?

**Comment by Pascal-Vtx** [comment]
> looks good to me. Would you mind opening a PR?

Is there anything more to do ? Seems that the PR is awaiting approval
