### ISSUE TITLE
7zz is licensed as unfree

### ISSUE THREAD

**Issue by linsui** [NixOS/nixpkgs#163680]
### Describe the bug
The 7zip uses unrar's code. https://fedoraproject.org/wiki/Licensing:Unrar It's better to make the unrar part optional so that it's free by default.

### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers

@peterhoeg @thiagokokada

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by 06kellyjac** [comment]
The unfree part is optional already in `p7zip` ... https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/archivers/p7zip/default.nix#L1

`_7zz` is only free https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/archivers/7zz/default.nix#L49

which specific package are you referring to?

**Comment by linsui** [comment]
I'm talking about _7zz. It's built from the 7zip source and the UnRAR license is in the tarball. I don't know if the unrar code is excluded somehow though.

**Comment by 06kellyjac** [comment]
I understand now. I've created PR #163999 to resolve this

**Comment by linsui** [comment]
Thanks!
