### ISSUE TITLE
Slack fails to install on Mac OS Monterey

### ISSUE THREAD

**Issue by tylerlevine** [NixOS/nixpkgs#163643]
### Slack fails to install on Mac OS Monterey
When attempting to install `slack`, installation fails with the following error:

```
error: builder for '/nix/store/639ij43y08kbs7jp1x5nghg6sxzyad36-slack-4.23.0.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/1yxab68y3xf40gcia6zv3vbm7cvb0fsh-Slack-4.23.0-macOS.dmg
       > source root is Slack.app
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > no Makefile, doing nothing
       > installing
       > 2022-03-11 00:28:14.960 defaults[22350:333172] Unexpected argument YES; leaving defaults unchanged.
       For full logs, run 'nix log /nix/store/639ij43y08kbs7jp1x5nghg6sxzyad36-slack-4.23.0.drv'.
```

As noted in https://github.com/NixOS/nixpkgs/pull/125051#discussion_r815383229, the call to `/usr/bin/defaults` is incorrectly using a capital B in the `-Bool` flag. It should be `-bool`.

The error coming from the `installPhase` matches the error when running the same `/usr/bin/defaults` command by itself:
```
/usr/bin/defaults write com.tinyspeck.slackmacgap SlackNoAutoUpdates -Bool YES
2022-03-10 19:19:44.223 defaults[26087:398919] Unexpected argument YES; leaving defaults unchanged.
```

I searched for an existing issue which reports this, but didn't find any (aside from the comment linked earlier).

### Steps To Reproduce
```
$ NIXPKGS_ALLOW_UNFREE=1 nix-env -iA nixpkgs.slack
installing 'slack-4.23.0'
this derivation will be built:
  /nix/store/iflxk2dkbkjmdkffryqlkjsq654yy2nl-slack-4.23.0.drv
these 2 paths will be fetched (0.07 MiB download, 0.19 MiB unpacked):
  /nix/store/cn1kqfrayyc64vczry86a9q90yir6wvn-lzfse-1.0
  /nix/store/w8qn8lvm461n8g1n8zqlx25fcfdn602z-undmg-1.1.0
copying path '/nix/store/cn1kqfrayyc64vczry86a9q90yir6wvn-lzfse-1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/w8qn8lvm461n8g1n8zqlx25fcfdn602z-undmg-1.1.0' from 'https://cache.nixos.org'...
building '/nix/store/iflxk2dkbkjmdkffryqlkjsq654yy2nl-slack-4.23.0.drv'...
unpacking sources
unpacking source archive /nix/store/1yxab68y3xf40gcia6zv3vbm7cvb0fsh-Slack-4.23.0-macOS.dmg
source root is Slack.app
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
2022-03-11 03:10:56.193 defaults[26009:394028] Unexpected argument YES; leaving defaults unchanged.
error: builder for '/nix/store/iflxk2dkbkjmdkffryqlkjsq654yy2nl-slack-4.23.0.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/1yxab68y3xf40gcia6zv3vbm7cvb0fsh-Slack-4.23.0-macOS.dmg
       > source root is Slack.app
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > no Makefile, doing nothing
       > installing
       > 2022-03-11 03:10:56.193 defaults[26009:394028] Unexpected argument YES; leaving defaults unchanged.
       For full logs, run 'nix log /nix/store/iflxk2dkbkjmdkffryqlkjsq654yy2nl-slack-4.23.0.drv'.
```

### Expected behavior
Slack is installed successfully.

### Screenshots
N/A

### Additional context
N/A

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(tyler): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Artturin** [comment]
Can you make a pr fixing it? I can merge.

**Comment by tylerlevine** [comment]
> Can you make a pr fixing it? I can merge.

I made a commit to do that in my fork here: https://github.com/tylerlevine/nixpkgs/commit/01508b40a26fde523c37042300f47bd6c79f20fd

However it still fails during the `installPhase`, this time with `defaults[2342:1734766] Could not write domain com.tinyspeck.slackmacgap; exiting`. This was also reported in https://github.com/NixOS/nixpkgs/pull/125051 but only on `aarch64`. However it seems the same issue is also present on `x86_64` and I'm not sure where to go from here on fixing it I can run the same command from my terminal successfully. Is there anything different about running `/usr/bin/defaults` during the `installPhase` that might cause this?

**Comment by tylerlevine** [comment]
I think I figured out the problem.

`/usr/bin/defaults` writes to `~/Library/Preferences/com.tinyspeck.slackmacgap.plist`, but this isn't accessible to the user running the `installPhase` script (`_nixbld1`).

```
$ ls -lah ~/Library/Preferences/com.tinyspeck.slackmacgap.plist
-rw-------@ 1 tyler  staff    68B Mar 22 21:35 /Users/tyler/Library/Preferences/com.tinyspeck.slackmacgap.plist
```

I'm able to reproduce the problem now if I try to run the `/usr/bin/defaults` command as that user.

```
sudo -u _nixbld1 /usr/bin/defaults write com.tinyspeck.slackmacgap SlackNoAutoUpdates -bool YES
2022-03-22 21:43:34.488 defaults[39020:1835088] Could not write domain com.tinyspeck.slackmacgap; exiting
```

Is there some way to make this file writable by the `_nixbld1` user as part of the `installPhase`? I'll try to do some research on how other packages set property list attributes on darwin to see if there's some other workaround.
