### ISSUE TITLE
Allow 'double dash' syntax for nix-shell command

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixpkgs#16364]
It would be nice to be able to do something like this: 

`nix-shell -p my-package -- exe using -my --package` which is equivalent to `nix-shell -p my-package --command 'exe using -my --package'`

There plenty of precedence for this in other packages, and even elsewhere in the nix ecosystem: `nixops ssh machineName -- some command -with --flags`.

**Comment by expipiplus1** [comment]
Of course this might not make sense to do now while the tools are being rewritten in C++.

**Comment by joachifm** [comment]
I think this belongs on the Nix issue tracker?

**Comment by expipiplus1** [comment]
yes, that makes more sense. I'll repost it there.
