### ISSUE TITLE
nixos-install compiling drivers for hours

### ISSUE THREAD

**Issue by aeosynth** [NixOS/nixpkgs#16367]
## Issue description

i attempted to install `nixos-minimal-16.09pre85572` in VirtualBox, but cancelled after compiling drivers for hours without finishing. I was told on reddit that the ISOs have issues with certificates, which prevent me from accessing the binary cache?

### Steps to reproduce

grab `nixos-minimal-16.09pre85572`, attempt to install in VirtualBox

**Comment by domenkozar** [comment]
Can you specify exact commands for "attempt to install"

**Comment by abbradar** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/15579 -- please reopen if that's not the case.

**Comment by aeosynth** [comment]
will test once https://nixos.org/channels/nixos-unstable/ updates

@domenkozar 

```
$ fdisk /dev/sda # (or whatever device you want to install on)
$ mkfs.ext4 nixos /dev/sda1
$ mount /dev/sda1 /mnt
$ nixos-generate-config --root /mnt
$ nano /mnt/etc/nixos/configuration.nix
$ nixos-install # install canceled here
```
