### ISSUE TITLE
Infinite Recurion when using haskell.lib.buildStackProject

### ISSUE THREAD

**Issue by mckeankylej** [NixOS/nixpkgs#16371]
## Issue description

When trying to follow the [stack nix guide](http://docs.haskellstack.org/en/stable/nix_integration/) and set up a simple stack and nix project I ran into the following error: 

    error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘minimal-case’ at /home/kyle/repos/nix-stack-reflex/shell.nix:4:2:                                                                                                       
    infinite recursion encountered, at /nix/store/mprw6f2pwk42v6gf732b8yjnmi6b3j16-nixos-16.09pre85572.20a8349/nixos/pkgs/development/haskell-modules/generic-stack-builder.nix:8:9       

The shell.nix file is as follows:

    with (import <nixpkgs> { });

    haskell.lib.buildStackProject {
            name = "minimal-case";
            buildInputs = [];
    }

### Steps to reproduce

Copy the above shell.nix file into shell.nix

Run: `nix-shell shell.nix`

* System: NixOS: 16.09pre85572.20a8349 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre85572.20a8349

**Comment by puffnfresh** [comment]
You can work around this by setting a ghc property:

```nix
with import <nixpkgs> { };

haskell.lib.buildStackProject {
  name = "hello-example";
  ghc = haskell.packages.ghc7103.ghc;
  buildInputs = [ ];
}
```

**Comment by mckeankylej** [comment]
This worked!
