### ISSUE TITLE
Package request: whatweb

### ISSUE THREAD

**Issue by Jonathan-M-C** [NixOS/nixpkgs#163746]
**Project description**

A scanner informing the technologies and headers a website uses.

**Metadata**

* homepage URL: https://www.morningstarsecurity.com/research/whatweb
* source URL: https://github.com/urbanadventurer/WhatWeb
* license: GPL-2.0
* platforms: Agnostic (Darwin, Linux, Windows)

See also: https://github.com/NixOS/nixpkgs/issues/81418

**Comment by WolfangAukang** [comment]
@Jonathan-M-C I was able to build it, check it here https://github.com/WolfangAukang/nixpkgs/tree/whatweb
