### ISSUE TITLE
Standardize CUDA arch's/compute capabilities

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#163700]
### Describe the bug
Right now every package builds CUDA with their own notion of CUDA architectures. As @SomeoneSerge notes in https://github.com/numtide/nixpkgs-unfree/pull/8#discussion_r824044775,

> (e.g. `cudaArchList = [ "8.6+PTX" ];` in pytorch is `cudaCapabilities = [ "compute_86" ]` in jaxlib)

In order to provide a consistent experience we should probably standardize these possible options, much like how licenses and platforms are currently standardized into enum-ish concepts.

In the future perhaps we can add a nixpkgs-wide config option to set which CUDA arch you'd like things built against.

Opening this issue now to track the problem, and brainstorm possible solutions.

cc @NixOS/cuda-maintainers

**Comment by FRidh** [comment]
See also `lib/systems/architectures.nix` for inspiration.

**Comment by FRidh** [comment]
Following was shared via Matrix https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/.

I imagine we will have an attribute set connecting arch and supported cuda versions. We can then have several functions for generating sets looking like
```
{
  arch = "30";
  gencode = [ ... ];
}

One function computes given a cuda version the oldest compatible architecture and generates code for that arch and up for maximum compatibility. This we would then use as default. Then, there could be a function for generating gencode for a specific arch only for maximum performance, etc.

**Comment by samuela** [comment]
I think we can close this now that https://github.com/NixOS/nixpkgs/pull/205351 has been merged. There may be ways to improve on the system introduced in https://github.com/NixOS/nixpkgs/pull/205351 but we can address those design considerations in future discussions.
