### ISSUE TITLE
grub + efi broken

### ISSUE THREAD

**Issue by paspanag** [NixOS/nixpkgs#16374]
Currently booting an efi system with grub is broken. Tried to install using 

````nix
{               
        boot.loader.grub = {
                enable = true;
                version = 2;
                efiSupport = true;
                device = "nodev";};
        boot.kernelPackages = pkgs.linuxPackages_4_5;
}

````

Replaced the grub parts with systemd boot and it works. When I tried to use this config again, it reported success but the boot is still under systemd boot.

* System: 16.09pre85572.20a8349
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre85572.20a8349

**Comment by spinus** [comment]
@paspanag, I'm not very good with grub but device="nodev" looks suspicious to me. what does it do?
I'm using device="/dev/xxx" and works for me (I'm not sure that's the case here).

**Comment by paspanag** [comment]
Yeah looks odd but I got it from one of the open issues to get grub and efi to work. #9096

**Comment by spinus** [comment]
did you try to set this up for some device? Do you have EFI boot partition?

**Comment by paspanag** [comment]
Yeah it's for my laptop. 

I had Nixos, but installed another another distro, then went back to Nixos using the same config and same partitioning scheme as before I installed the other distro.

**Comment by cransom** [comment]
I noticed when testing my own laptop a few weeks ago that when disabling gummiboot/grub, the efi boot stubs don't get removed automatically. There are scripts that get called to install the boot loaders but there aren't any that remove said loaders. If you delete/disable/rename /boot/EFI/gummiboot grub or change the EFI boot settings in bios or via efibootmgr, you'll get grub back.

**Comment by paspanag** [comment]
@cransom, Thanks!

I used efibootmgr, I'll try to make a fix and do a pull request. Seems to be only one command is needed to do the transition from systemd-boot to grub.

**Comment by vcunat** [comment]
A few days ago I installed 16.03 successfully on UEFI by following the [manual](http://nixos.org/nixos/manual/index.html#sec-uefi-installation).

**Comment by domenkozar** [comment]
According to @avnik it's working:

- https://github.com/avnik/nixos-configs/blob/master/bulldozer.nix#L26
- https://github.com/avnik/nixos-configs/blob/master/common/efi.nix

**Comment by domenkozar** [comment]
But @obadz has also issues: `doesn't work unless installed from a UEFI enabled device`

**Comment by avnik** [comment]
@domenkozar  last one common for all distros,  debian also unable to install efi grub, unless booted from UEFI enabled device

**Comment by obadz** [comment]
this is a commit in the works that should be able to helpful when installing a UEFI system from a non-UEFI booted system or simply when one does not want to deal with the stateful messiness of efivars: https://github.com/obadz/nixpkgs/commit/45e219d03f80a0050b0a2b645a7ab72285d0cb7e

**Comment by jokogr** [comment]
If I understand well, the `device` attribute is required to write to the MBR, so "nodev" is correct.

My installation also works with Grub and UEFI, I had a setup initially similar to @avnik's (https://github.com/avnik/nixos-configs/blob/master/common/efi.nix), now I am working on properly cloning the ESP partitions (see #18584).
