### ISSUE TITLE
cudatoolkit: cuda-memcheck broken

### ISSUE THREAD

**Issue by mcwitt** [NixOS/nixpkgs#163739]
### Describe the bug
The `cuda-memcheck` binary included with `cudatoolkit` fails to produce the expected output, instead printing `Internal error (7)`.

### Steps To Reproduce
The following example (from the [cuda-memcheck docs](https://docs.nvidia.com/cuda/cuda-memcheck/index.html#example-use-of-memcheck)), when run under `cuda-memcheck`, does not produce the [expected output](https://docs.nvidia.com/cuda/cuda-memcheck/index.html#memcheck-demo-output-with-memcheck-release-build):

```cuda
#include <stdio.h>

__device__ int x;

__global__ void unaligned_kernel(void) {
    *(int*) ((char*)&x + 1) = 42;
}

__device__ void out_of_bounds_function(void) {
    *(int*) 0x87654320 = 42;
}

__global__ void out_of_bounds_kernel(void) {
    out_of_bounds_function();
}

void run_unaligned(void) {
    printf("Running unaligned_kernel\n");
    unaligned_kernel<<<1,1>>>();
    printf("Ran unaligned_kernel: %s\n",
    cudaGetErrorString(cudaGetLastError()));
    printf("Sync: %s\n", cudaGetErrorString(cudaDeviceSynchronize()));
}

void run_out_of_bounds(void) {
    printf("Running out_of_bounds_kernel\n");
    out_of_bounds_kernel<<<1,1>>>();
    printf("Ran out_of_bounds_kernel: %s\n",
    cudaGetErrorString(cudaGetLastError()));
    printf("Sync: %s\n", cudaGetErrorString(cudaDeviceSynchronize()));
}

int main() {
    int *devMem;

    printf("Mallocing memory\n");
    cudaMalloc((void**)&devMem, 1024);

    run_unaligned();
    run_out_of_bounds();

    cudaDeviceReset();
    cudaFree(devMem);

    return 0;
}
```

To reproduce:
```console
$ nix-shell --pure -p cudatoolkit_10_1 --command "nvcc memcheck_demo.cu && LD_LIBRARY_PATH=/run/opengl-driver/lib ./a.out"
Mallocing memory
Running unaligned_kernel
Ran unaligned_kernel: no error
Sync: misaligned address
Running out_of_bounds_kernel
Ran out_of_bounds_kernel: misaligned address
Sync: misaligned address
```
(Note: if the `LD_LIBRARY_PATH` setting is removed, this fails with `CUDA driver version is insufficient for CUDA runtime version`)

The above output is [as expected](https://docs.nvidia.com/cuda/cuda-memcheck/index.html#memcheck-demo-output). But when run under cuda-memcheck, errors are not detected and the message `Internal Error (7)` is printed:
```console
$ nix-shell --pure -p cudatoolkit_11_6 --command "nvcc memcheck_demo.cu && LD_LIBRARY_PATH=/run/opengl-driver/lib cuda-memcheck a.out"
========= CUDA-MEMCHECK
========= This tool is deprecated and will be removed in a future release of the CUDA toolkit
========= Please use the compute-sanitizer tool as a drop-in replacement
Mallocing memory
Running unaligned_kernel
Ran unaligned_kernel: no error
Sync: no error
Running out_of_bounds_kernel
Ran out_of_bounds_kernel: no error
Sync: misaligned address
========= Internal error (7)
========= No CUDA-MEMCHECK results found
```

This reproduction works for other versions of cudatoolkit I tried (e.g. 11.5, 10.1).

### Expected behavior
The cuda-memcheck binary should produce the [expected output](https://docs.nvidia.com/cuda/cuda-memcheck/index.html#memcheck-demo-output-with-memcheck-release-build) when run on the example. In particular, it should not print `Internal error (7)`.

### Notify maintainers
[@NixOS/cuda-maintainers](https://github.com/orgs/NixOS/teams/cuda-maintainers)

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.25, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(matt): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by samuela** [comment]
Thanks for your detailed report @mcwitt! Two things:
* This would make a great test case for my soon-to-be-realized suite of GPU-specific tests of nixpkgs software! See the TODO item in [this thread](https://discourse.nixos.org/t/announcing-the-nixos-cuda-maintainers-team-and-a-call-for-maintainers/18074).
* This should be a relatively straightforward `addOpenGLRunpath` issue to solve. Would be a great first PR for someone interested in contributing! If someone would like to take a stab at this let me know, and I'd be happy to help you figure it out.
