### ISSUE TITLE
fuse2fs is missing from the e2fsprogs package.

### ISSUE THREAD

**Issue by LukeSkyw** [NixOS/nixpkgs#163881]
### Describe the bug
fuse2fs is missing from the e2fsprogs package.

### Steps To Reproduce
1. Install e2fsprogs
2. fuse2fs utility not installed

### Expected behavior
fuse2fs is part of the e2fsprogs repository: https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/tree/configure#n11411
and should be installed with the package.

### Screenshots
NA

### Additional context
@Artturin found out that to have fuse2fs only requires adding the fuse library to buildInputs. But it increase the size of the packages from 22M to 36M.
Another solution would be to have a dedicated fuse2fs package like arch: https://archlinux.org/packages/core/x86_64/fuse2fs/

### Notify maintainers
@edolstra

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/q124axggd6wl6fh9508sxgkknkifrl0z-nix-info
copying path '/nix/store/q124axggd6wl6fh9508sxgkknkifrl0z-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-30-generic, Ubuntu, 21.10 (Impish Indri)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(user): `"nixpkgs"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by haras-unicorn** [comment]
it was still missing for me so i had to do this

```nix
    ((e2fsprogs.override { withFuse = true; }).overrideAttrs (final: prev: {
      postInstall = (prev.postInstall or "") + ''
        cp $fuse2fs/bin/fuse2fs $bin/bin
      '';
    }))
```

withFuse is probably redundant but i left it in just in case
