### ISSUE TITLE
GOROOT missing bin/go

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#16387]
## Issue description

In order for some commands to work with the go packages in nix, you must set GOROOT. It must be set to ${pkgs.go}/share/go (correct me if I am wrong...?)

However, the go packages do not install the go binary to $GOROOT/bin/ . This causes tools which expect the go binary to be in $GOROOT to fail. (vscode-go is an example).

I propose a copy or symlink of the go binary in /nix/store/_-go-_/share/go/bin 

PR incoming.
### Steps to reproduce

 $ nix-env -i go
 $ ls /nix/store/_-go-_/share/go/bin
 ... no go binary ...
## Technical details
- System: 16.03.948.a96c308 (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.948.a96c308

**Comment by tadfisher** [comment]
(triage) status?

**Comment by sheenobu** [comment]
There have been a bunch of go changes in 16.09. I'll see if this is still a problem. Most likely it's a non-issue

**Comment by sheenobu** [comment]
Still an issue. For go 1.7, the change is simple (listed below and waiting to finish building/testing). For 1.6 and below the change is a little more complicated. We may just want go 1.6 and below to use the same preFixup, install, and configure phases.

```
diff --git a/pkgs/development/compilers/go/1.7.nix b/pkgs/development/compilers/go/1.7.nix
index 0f78646..4da9d4d 100644
--- a/pkgs/development/compilers/go/1.7.nix
+++ b/pkgs/development/compilers/go/1.7.nix
@@ -138,7 +138,7 @@ stdenv.mkDerivation rec {
 
   preFixup = ''
     rm -r $out/share/go/pkg/bootstrap
-    mv $out/share/go/bin $out/bin
+    ln $out/share/go/bin $out/bin
   '';
 ```

**Comment by sheenobu** [comment]
New PR for 1.7 #19413

**Comment by kamilchm** [comment]
What is the reason of using `$out/share/go` instead of simple `$out`? If you look at binary package provided from golang.org it looks simple like that.

**Comment by sheenobu** [comment]
@kamilchm GOROOT was always "$pwd/" and at e58b3517 this was added, effectively making GOROOT share/go . Can't say 'why' but it's been a convention since go 1.0.2.

```
+  # I'm not sure what go wants from its 'src', but the go installation manual
+  # describes an installation keeping the src.
+  preUnpack = ''
+    mkdir -p $out/share
+    cd $out/share
+  '';
```

**Comment by sheenobu** [comment]
To compare: archlinux has /usr/lib/go and /usr/share/go. GOROOT is /usr/lib/go and share/go is the merging of both of those.

Additionally, my system has a ~/.nix-profile/share/go. if we install directly to $out then ~/.nix-profile would get the folders in GOROOT . ~/.nix-profile and /var/run/current-system/sw seem to mimic standard unix folders and NOT putting GOROOT in share or lib might break that pattern.

**Comment by sheenobu** [comment]
PR for this was closed. GOROOT=${pkgs.go}, $GOROOT/bin/go now works for go 1.7
