### ISSUE TITLE
Systemd v230 kills user processes

### ISSUE THREAD

**Issue by khoi-nguyen** [NixOS/nixpkgs#16395]
## Issue description

The new systemd sets `KillUserProcesses` to `yes` by default, breaking applications like tmux and screen. It also breaks mosh.

I can open a pull request if you want.

### Steps to reproduce

- Ssh into a NixOS machine with systemd v230;
- Open a screen/tmux session;
- Detach from the session and disconnect from ssh;
- Reconnect to the machine via SSH;

The tmux session should be gone.

## Technical details

* System: 16.09pre85572.20a8349 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre85572.20a8349"

**Comment by FRidh** [comment]
The default value has been changed in #16021 .
