### ISSUE TITLE
build-support/release/functions.sh not all jar files have a manifest

### ISSUE THREAD

**Issue by heilkn** [NixOS/nixpkgs#16409]
## Issue description

When antBuild is used to install a package that provides jar files it calls
canonicalizeJarManifest from functions.sh
Problem: Not every jar archive does provide a manifest file.

Please consider to apply the attached patch.
[functions.sh.txt](https://github.com/NixOS/nixpkgs/files/326670/functions.sh.txt)

**Comment by Profpatsch** [comment]
cc @copumpkin

**Comment by Profpatsch** [comment]
For reference, the patch is:

```
16,20c16,18
<     if [ -e $input ]; then
<       # http://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Notes_on_Manifest_and_Signature_Files
<       (head -n 1 $input && tail -n +2 $input | sort | grep -v '^\s*$') > $input-tmp
<       mv $input-tmp $input
<     fi
---
>     # http://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Notes_on_Manifest_and_Signature_Files
>     (head -n 1 $input && tail -n +2 $input | sort | grep -v '^\s*$') > $input-tmp
>     mv $input-tmp $input
```

and seems to still apply, though I haven’t checked its validity.

**Comment by heilkn** [comment]
Hi, feel free to close this. I don't require that any longer. I still think this is a bug, though. I stumbled upon it when trying to create a derivation for lightzone.

Kind regards

Konstantin

**Comment by Profpatsch** [comment]
let me close this, it will still show up in searches if somebody has the same problem in the future.
