### ISSUE TITLE
nm-openvpn user

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#16401]
## Issue description

After an upgrade a `nm-openvpn` user has appeared on my login screen (SDDM).

## Technical details

* 16.09.git.453086a (Flounder)

cc @fpletz because of recent openvpn changes.

**Comment by FRidh** [comment]
Relevant part of `configuration.nix`
```
  networking.networkmanager.enable = true;
  networking.networkmanager.packages = with pkgs; [
    networkmanager_pptp
    networkmanager_l2tp
    networkmanager_vpnc
    networkmanager_openconnect
  ];
```

**Comment by dezgeg** [comment]
Maybe the `nm-openvpn` should have `isSystemUser = true`. Though lots of other system users seem to be missing that as well, so might not be that...

**Comment by joelmo** [comment]
It's probably something with the openvpn module. I have that version and use SDDM but that user doesn't appear here. I also have nm enabled.

**Comment by FRidh** [comment]
The user hasn't appeared anymore for quite some time so I am closing this.
