### ISSUE TITLE
Apache Spark complains about missing libaudit

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#16403]
## Issue description

I am trying to install Nix version of Apache Spark on RHEL 6.5. The install completed without any issues but trying to run it in nix-shell produces the following errors

```
$ nix-shell -p spark

[nix-shell:/home/avorobi]$ spark-shell
ls: error while loading shared libraries: libaudit.so.1: cannot open shared object file: No such file or directory
grepwc: : error while loading shared librarieserror while loading shared libraries: : libaudit.so.1libaudit.so.1: : cannot open shared object filecannot open shared object file: : No s
uch file or directoryNo such file or directory
```

I tried adding a path to libaudit to LD_LIBRARY_PATH but then spark-shell just exits:

```
[nix-shell:/home/avorobi]$ export LD_LIBRARY_PATH=/nix/store/i4dqap4cihxirg2yw487hgcnm0ql65c4-audit-2.4.4/lib

[nix-shell:/home/avorobi]$ spark-shell

[nix-shell:/home/avorobi]$ 
```
### Steps to reproduce

```
nix-shell -p spark
spark-shell
export LD_LIBRARY_PATH=/nix/store/i4dqap4cihxirg2yw487hgcnm0ql65c4-audit-2.4.4/lib
spark-shell
```
## Technical details

System: 
$ lsb_release -a
LSB Version: :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description: Red Hat Enterprise Linux Server release 6.7 (Santiago)
Release: 6.7
Codename: Santiago

Nix version:
$ nix-env --version
nix-env (Nix) 1.11.2

Nixpkgs version: 
$ nix-instantiate --eval '' -A lib.nixpkgsVersion
"16.09pre83147.df89584"

**Comment by cko** [comment]
Would you mind checking if the problem still exists?

I tried to reproduce it with Debian stable and Nix 1.11.8 and everything looks fine.

**Comment by alexvorobiev** [comment]
The issue seems to have been fixed!
