### ISSUE TITLE
gnome.nautilus: No thumbnails for heic/heif files

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#164021]
### Describe the bug
Gnome nautilus does not generate thumbnails for heic/heif files.

### Steps To Reproduce
1. Ensure thumbnails are enabled in preferences
2. Open a folder containing heic files

### Screenshots
![image](https://user-images.githubusercontent.com/1482768/158070247-48286b05-0c95-4594-95dc-883c1c34f5b7.png)

### Notify maintainers
@hedning 
@jtojnar 
@dasj19 
@maxeaubrey 

### Metadata
```console
 asbachb@nixos-t14s  ~  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.12, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(asbachb): `""`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Hi, this is well known issue, see https://github.com/NixOS/nixpkgs/issues/87033. Currently it is blocked on https://github.com/NixOS/nixpkgs/pull/153275.

**Comment by jtojnar** [comment]
I think this can be closed, people can install the package if they want.

**Comment by usul0184** [comment]
Is `heif.thumbnailer` supposed to be automatically installed into `/run/current-system/sw/share/thumbnailers`?  If not, how do you do so?  Thanks!

**Comment by jtojnar** [comment]
See https://github.com/NixOS/nixpkgs/issues/164021#issuecomment-2078013231

**Comment by usul0184** [comment]
Maybe I'm doing something wrong, but I still don't see `heif.thumbnailer` in `/run/current-system/sw/share/thumbnailers` even after adding `environment.pathsToLink = [ "share/thumbnailers" ];`?  For what it's worth, I do see `evince.thumbnailer`, `gnome-font-viewer.thumbnailer`, and `totem.thumbnailer`.

**Comment by jtojnar** [comment]
Apparently, `libheif` has `bin` as the default output so you would need `environment.systemPackages = [ pkgs.libheif.out ];`

**Comment by Saiv46** [comment]
@jtojnar Shouldn't this be included in package itself? Or maybe as `heif-thumbnailer` like other distributions did

```
environment.systemPackages = [ pkgs.libheif pkgs.libheif.out ];
environment.pathsToLink = [ "share/thumbnailers" ];
```

**Comment by jtojnar** [comment]
It would be possible to add it to Nautilus but it is not clear to me how common these file types are and if the increased closure size is worth it. We already had people complaining about our Nautilus package being bloated by GStreamer.

`environment.pathsToLink` is only necessary if you do not use a desktop environment (e.g. GNOME) or build your own from scratch.

It would be nice to split the thumbnailer into a separate output so that user could just install `pkgs.libheif.thumnailer`. We have an issue about that: https://github.com/NixOS/nixpkgs/issues/32817 Patches welcome.

**Comment by Saiv46** [comment]
> `environment.pathsToLink` is only necessary if you do not use a desktop environment (e.g. GNOME)

Well, I use Cinnamon right from NixOS installer, it's strange how it's not working out-of-the-box.

**Comment by jtojnar** [comment]
Cinnamon links everything in `/share` just like GNOME:

https://github.com/NixOS/nixpkgs/blob/535b744c25ba95c29dd1b9a9c67268236e75934e/nixos/modules/services/x11/desktop-managers/cinnamon.nix#L210

**Comment by ahydronous** [comment]
> It would be possible to add it to Nautilus but it is not clear to me how common these file types are and if the increased closure size is worth it. We already had people complaining about our Nautilus package being bloated by GStreamer.

Not sure if you're still working on this @jtojnar but both iOS and Android shoot pictures in .heic, so they are incredibly, incredibly common. It would make sense to include it by default and give people an opt-out if they really want to shrink their Nautilus by a few mb.
