### ISSUE TITLE
libav-11.7 fails to build on nixos-unstable

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#16411]
## Issue description

`nixos-rebuild switch` fails for me because libav 11.7, which I have in `environment.systemPackages`, fails to build.

If I remove libav from `environment.systemPackages`, `nixos-rebuild switch` completes without error.

### Steps to reproduce

To reproduce libav's build failure:

```
$ nix-build '<nixpkgs>' -A libav
```

## Technical details

* System: NixOS `16.09pre85639.453086a (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09pre85639.453086a"`

**Comment by 8573** [comment]
Thanks for fixing!

**Comment by vcunat** [comment]
:-)
