### ISSUE TITLE
timeline: crashes on file dialog

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#164127]
re #162503, the `timeline` package crashes with

> (.timeline-wrapped:2422797): GLib-GIO-ERROR **: 17:05:40.072: No GSettings schemas are installed on the system
> Trace/breakpoint trap (core dumped)

when a file dialog is opened (eg. file -> open).

The rest of the program seems to work.

I tried adding wrapGAppsHook, gsettings-desktop-schemas, and glib, but none of those fixed it.

I'm running awesome wm, nixos 21.11

cc @davidak

**Comment by davidak** [comment]
Some resources i found related to the error message:

- https://stackoverflow.com/questions/28953925/glib-gio-error-no-gsettings-schemas-are-installed-on-the-system
- https://bbs.archlinux.org/viewtopic.php?id=249621
- https://github.com/jeffreywildman/homebrew-virt-manager/issues/168

timeline sources does not have schemas files.

maybe `XDG_DATA_DIRS` is not set correctly on your system

maybe we have to add `gsettings-desktop-schemas` to timeline dependencies. could you try that?

**Comment by fgaz** [comment]
> maybe XDG_DATA_DIRS is not set correctly on your system

other gnome stuff seems to work though

**Comment by fgaz** [comment]
I did try wrapGAppsHook, but that didn't fix it. maybe I did it wrong?

**Comment by jtojnar** [comment]
As mentioned above, for Python packages, you might also need to disable `strictDeps`.

**Comment by fgaz** [comment]
I tried using `wrapGAppsHook` and `striceDeps = false`, and it still errors out
