### ISSUE TITLE
HomeAssistant systemd start returns before web-interface is available

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#164154]
### Describe the bug
The systemd service should not return as "started", until the web-interface is available. 

### Steps To Reproduce
1. enable Home Assistant according to the wiki. 
2. `systemctl stop home-assistant &&  systemctl start home-assistant`
3. Quickly after visit the web-interface on the  configured port

### Expected behavior
Home Assistant web application is visible. 

It is debatable whether one should wait until Home Assistant has fully initialized and whether that actually has any meaning. I don't care about that, but *if* it is possible to wait for that state, that might be better.  

## Actual behavior
Browser reports that the website can't be found. 

### Metadata
Unstable branch

**Comment by mweinelt** [comment]
Home Assistant has no sd-notify support since they don't use systemd in their packaging. Nothing we can do about that.
