### ISSUE TITLE
tcsh seems to hang in `iconv_open`

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#16424]
## Issue description

Building `tcsh` and running `tcsh` via full path leads to a hanging `tcsh` process consuming a CPU core. Apparently the process enters an `iconv_open` library call and never leaves it.

### Steps to reproduce

```
$(nix-build --no-out-link '<nixpkgs>' -A ltrace)/bin/ltrace -n1 -S -f env -i $(nix-build --no-out-link '<nixpkgs>' -A tcsh)/bin/tcsh < /dev/null
```

Expected: process finishes.

Observed: process hangs inside `iconv_open`

Without `ltrace` I can get a backtrace using `gdb`, it points to `__wcsmbs_load_conv` called from `mbrtowc` from `mbtowc`.

## Technical details

* System: NixOS: 16.09.git.06d3636 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09.git.06d3636

latest git commit for Nixpkgs/NixOS: ffd2afd89d856545e1aae86b4e63c4e903ba7e47

**Comment by dezgeg** [comment]
Wow, that is bizarre:

````
Program received signal SIGINT, Interrupt.
0x000000000043db14 in calloc ()
(gdb) bt
#0  0x000000000043db14 in calloc ()
#1  0x00007ffff763dacf in __wcsmbs_load_conv () from /nix/store/dakzb4d5db59kkpghry6czgszlwl2spp-glibc-2.23/lib/libc.so.6
#2  0x00007ffff7632a94 in mbrtowc () from /nix/store/dakzb4d5db59kkpghry6czgszlwl2spp-glibc-2.23/lib/libc.so.6
#3  0x00007ffff75cd49c in mbtowc () from /nix/store/dakzb4d5db59kkpghry6czgszlwl2spp-glibc-2.23/lib/libc.so.6
#4  0x00000000004447d8 in ?? ()
#5  0x0000000000444851 in ?? ()
#6  0x00000000004448c2 in ?? ()
#7  0x0000000000444c3f in ?? ()
#8  0x0000000000403bf7 in ?? ()
#9  0x00007ffff75b7770 in __libc_start_main () from /nix/store/dakzb4d5db59kkpghry6czgszlwl2spp-glibc-2.23/lib/libc.so.6
#10 0x00000000004053b9 in ?? ()

(gdb) x/20i calloc
   0x43db10 <calloc>:	imul   %rsi,%rdi
=> 0x43db14 <calloc+4>:	mov    $0x1,%esi
   0x43db19 <calloc+9>:	jmp    0x43db10 <calloc>
(gdb) info sym calloc
calloc in section .text of /nix/store/njg4a7j5ir9vj50jdr0kmmqks3p96fvp-tcsh-6.18.01/bin/tcsh
````

So tcsh defines it's own version of `calloc`, which is compiled into an infinite loop (looks like that is due to GCC optimizing: https://gcc.gnu.org/ml/gcc-help/2015-03/msg00093.html), which gets used by glibc for some reason...

**Comment by dezgeg** [comment]
One of the Arch patches looks like it would fix this: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/tcsh

**Comment by joachifm** [comment]
See also https://github.com/NixOS/nixpkgs/pull/14583
