### ISSUE TITLE
dotnet overwrites HOME environment variable

### ISSUE THREAD

**Issue by d3zd3z** [NixOS/nixpkgs#164295]
### Describe the bug
A shell with 'dotnet-sdk_6' from unstable results in a shell where `$HOME` is set to a temporary directory, rather than the user's actual home directory. This makes numerous things fail to work.

### Steps To Reproduce
1. `nix-shell -I nixpkgs=<path-to-unstable> -p dotnet-sdk_6`
2. `echo $HOME`

### Expected behavior
The value of `$HOME` should not change when bringing in a given package.

### Additional context
This appears to be caused by

```
commit 8ef298b84f6c2426b62987f0eb31d5b754c990f3
Author: Ivar Scholten <ivar.scholten@protonmail.com>
Date:   Fri Mar 4 14:08:44 2022 +0100

    dotnet: add setup hook to set required env vars
```

### Notify maintainers
- @kuznero

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.105, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(davidb): `"unstable-22.05pre360355.b0e141e3fe1"`
 - channels(root): `"nixos-21.11.336515.0f85665118d"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by d3zd3z** [comment]
Pinging @kuznero, since I'm not sure if that works inside of the description.

**Comment by IvarWithoutBones** [comment]
My bad, I've pushed a fix in #164633.

Btw, I'd recommand to ping the person who created the faulty commit, I totally missed this issue.

**Comment by d3zd3z** [comment]
> Btw, I'd recommand to ping the person who created the faulty commit, I totally missed this issue.

Sorry, I was trying to do this, but wasn't sure how to map from the email address in the commit to a github ID.

**Comment by prusnak** [comment]
> Sorry, I was trying to do this, but wasn't sure how to map from the email address in the commit to a github ID.

`maintainers/maintainer-list.nix` helps
