### ISSUE TITLE
Wrong shell in /etc/passwd for isNormalUser = false

### ISSUE THREAD

**Issue by spencerjanssen** [NixOS/nixpkgs#16428]
## Issue description

Users with `isNormalUser = false` have the shell `/nix/store/6xfli9pns0cjwb1fi8kh21fd33jbrwq4-shadow-4.2.1` but should have something like `/run/current-system/sw/bin/nologin`.  One result of this issue is that these users can't create forward-only SSH sessions.

### Steps to reproduce

`grep shadow /etc/passwd`

## Technical details

clever on #nixos found commit 31c158ad453547993095b9425a60697738fdac5d which introduced the issue.

* System: `16.09.git.453086a (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: 453086a15fc0db0c2bc17d98350b0632551cb0fe

**Comment by ericsagnes** [comment]
cc @zimbatm

**Comment by zimbatm** [comment]
I just found out that the pkgs.shadow program doesn't export the shellPath passthrough for some reason.
