### ISSUE TITLE
Update qemu to qemu 2.6.0

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#16436]
Qemu 2.6 is out. This should be updated: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/qemu/default.nix

I'm not currnetly a NixOS user or I would send a PR.

**Comment by domenkozar** [comment]
I'm not following, it's already 2.6.0? https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/qemu/default.nix#L18

**Comment by colemickens** [comment]
I made my usual mistake. Searched GitHub, got a link to an older commit and then changed the hash to master when I made the issue. Never mind, sorry for the noise.
