### ISSUE TITLE
dotnet-sdk messes up the $HOME variable

### ISSUE THREAD

**Issue by prusnak** [NixOS/nixpkgs#164450]
## How to reproduce?

Run `nix-shell -p htop` and observe:

```
$ echo $HOME
/home/foo
```

Run `nix-shell -p dotnet-sdk` and observe:

```
$ echo $HOME
/tmp/tmp.c6ZOMDffpj
```

I assume this is caused by: https://github.com/NixOS/nixpkgs/blob/b13005f62433e5689c0d7b51606f2edacb035578/pkgs/development/compilers/dotnet/build-dotnet.nix#L93

// cc @IvarWithoutBones

**Comment by IvarWithoutBones** [comment]
My bad, I've pushed a fix in https://github.com/NixOS/nixpkgs/pull/164633.
