### ISSUE TITLE
nginx module: can't define listen directive without a listening address

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#164482]
According to nginx documentation, one can define:

```
  listen      80;
```

However, the NixOS module forbids this by including a colon that cannot be removed without forking the module. As such, this is a bug. 

https://github.com/NixOS/nixpkgs/blob/8c07b9ca35bd024b4ab702d780b783282383085b/nixos/modules/services/web-servers/nginx/default.nix#L258

@rnhmjoj Did you have some other method in mind for specifying equivalent semantics?

**Comment by rnhmjoj** [comment]
I'm actually not sure what `listen 80` means by looking at the documentation.
Do that mean to bind on all addresses?

**Comment by 21stce** [comment]
[Yes](https://nginx.org/en/docs/http/request_processing.html)

**Comment by rnhmjoj** [comment]
Apparently it means `0.0.0.0`, IPv4 only.
So, you should be able to specify that with `{ addr = "0.0.0.0"; port = 80; }`.

**Comment by aanderse** [comment]
Thanks @rnhmjoj!
