### ISSUE TITLE
libvirt: openGL does not work with Nvidia GPUs

### ISSUE THREAD

**Issue by Kranzes** [NixOS/nixpkgs#164436]
### Describe the bug
This bug has been discussed over at the discourse: https://discourse.nixos.org/t/opengl-with-libvirt-and-nvidia-driver/7177

### Steps To Reproduce
Try to create a VM with either virt-manager or virsh, with SPICE openGL enabled

### Expected behavior
The expected behavior is that the VM would be created accordingly without throwing errors.
Note: This does work correctly on my Intel iGPU laptop.

### Error output
```
error: internal error: qemu unexpectedly closed the monitor: 2022-03-16T14:11:19.539281Z qemu-system-x86_64: egl: eglGetDisplay failed
2022-03-16T14:11:19.539339Z qemu-system-x86_64: Failed to initialize EGL render node for SPICE GL
```

### Notify maintainers
@fpletz @globin

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.14, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220311_d532269`
 - channels(root): `""`
 - channels(kranzes): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs
```

**Comment by Myqiaoq** [comment]
> ### Describe the bug
> This bug has been discussed over at the discourse: https://discourse.nixos.org/t/opengl-with-libvirt-and-nvidia-driver/7177
> 
> ### Steps To Reproduce
> Steps to reproduce the behavior: Try to create a VM with either virt-manager or virsh, with SPICE openGL enabled
> 
> ### Expected behavior
> The expected behavior is that the VM would be created accordingly without throwing errors. Note: This does work correctly on my Intel iGPU laptop.
> 
> ### Error output
> ```
> error: internal error: qemu unexpectedly closed the monitor: 2022-03-16T14:11:19.539281Z qemu-system-x86_64: egl: eglGetDisplay failed
> 2022-03-16T14:11:19.539339Z qemu-system-x86_64: Failed to initialize EGL render node for SPICE GL
> ```
> 
> ### Notify maintainers
> @fpletz @globin
> 
> ### Metadata
> ```
>  - system: `"x86_64-linux"`
>  - host os: `Linux 5.16.14, NixOS, 22.05 (Quokka)`
>  - multi-user?: `yes`
>  - sandbox: `yes`
>  - version: `nix-env (Nix) 2.8.0pre20220311_d532269`
>  - channels(root): `""`
>  - channels(kranzes): `""`
>  - nixpkgs: `/etc/nix/inputs/nixpkgs
> ```

hi Kranzes, 
I have the same problem, is this problem solved now ?
My Host OS is CentOS 7.6.
Thanks for help.

**Comment by Kranzes** [comment]
A friend tested it on his Fedora system with a GTX 1070 and it didn't work either. I believe this isn't actually something with NixOS and my memory is incorrect.

**Comment by zer0x64** [comment]
I've got the same error message on Arch, using an RTX 3090.

**Comment by Myqiaoq** [comment]
https://libvirt.org/kbase/qemu-passthrough-security.html
[Disabling security protection host-wide]

I refer to the above configuration & systemctl restart libvirtd, 
and it works for me.

**Comment by vigne** [comment]
Same here on Fedora 36 with a RTX 3080(LHR)

**Comment by meisme-dev** [comment]
Same here, Fedora 36 and RTX 2070 Super

**Comment by AfoninZ** [comment]
Same problem, Ubuntu 22.04, GTX 1060

**Comment by sandikata** [comment]
Not work at all with Nvidia.
The only way is with remote desktop but it's a bit laggy.

sudo qemu-system-x86_64 -enable-kvm -cpu max -smp cores=4,threads=1,sockets=1 -m 6144 -device virtio-vga-gl -display egl-headless,gl=on,rendernode=/dev/dri/renderD128 -spice port=5900,addr=127.0.0.1,disable-ticketing=on -device ES1370 -boot menu=on -drive file=popos.qcow,if=virtio
,cache=none,aio=threads,format=qcow2 -net nic,model=virtio,macaddr=EE:00:D3:47:FE:50 -net bridge,br=br0 -device virtio-tablet-pci -name "PopOS 22.04" -daemonize -bios /usr/share/edk2-ovmf/OVMF_CODE.fd -cdrom ~/Свалени/iso/pop-os_22.04_amd64_intel_6.iso

for example

Nvidia RTX 3050

**Comment by cdstealer** [comment]
Hi, I had the same issue with Gentoo.  I solved this by downgrading the proprietary driver from version 510 to 470.  I have a 1660Ti.

Hope this helps.
CD

**Comment by cdstealer** [comment]
> Hello, and have you got it to work with virtio-gpu ?
> 
I haven't.  I'll need to build with virtio support.  I'll give it a try and reply back.

**Comment by sandikata** [comment]
Try it, but Nvidia do not support it at all. Virtio works over mesa (i've read some persons were succeeded with nvidia + virtio-gpu) but no one of their solutions works at all. Cannot say if they're fake or not.

**Comment by cdstealer** [comment]
> Try it, but Nvidia do not support it at all. Virtio works over mesa (i've read some persons were succeeded with nvidia + virtio-gpu) but no one of their solutions works at all. Cannot say if they're fake or not.

yep.. confirmed.  I feel this will be fun to solve :)

**Comment by serenovah** [comment]
I tried to downgrade to the proprietary Nvidia 470 driver (downgrade from 515).

I now get a black screen in the VM rather than an error message. So kind of progress but not actually progress. But there may be something to it. I may try other Nvidia drivers to see if any of them work. The Nouveau drivers didn't work at all for this despite some suggestions I saw elsewhere that suggested it.

**Comment by sandikata** [comment]
It definitely will work with nouveau (if they're improved)
For this you must have MESA drivers Nvidia sucks in linux.
All the hardware acceleration pass through MESA

**Comment by sandikata** [comment]
Your only chance is with AMD card not nvidia

**Comment by serenovah** [comment]
> Your only chance is with AMD card not nvidia

I've got it working actually. I was just hoping for a bit more power for the VM. I know there's a way to uncouple my GPU from Linux and give it to the VM, but that's a pain and I don't want to bother. It's actually working just fine as is, and does what I need it to do for work. I was just looking to see if I could improve it

And no, I can't replace the GPU, or at least not easily. I have a laptop, not a desktop because I need portability for my job

**Comment by sandikata** [comment]
> > Your only chance is with AMD card not nvidia
> 
> I've got it working actually. I was just hoping for a bit more power for the VM. I know there's a way to uncouple my GPU from Linux and give it to the VM, but that's a pain and I don't want to bother. It's actually working just fine as is, and does what I need it to do for work. I was just looking to see if I could improve it
> 
> And no, I can't replace the GPU, or at least not easily. I have a laptop, not a desktop because I need portability for my job

you don't have power because it doesn't have accelerated graphics inside VM

**Comment by Kranzes** [comment]
Closing this issue because I'm tired of it, also unsubscribing from notifications. You can keep discussing here though 🙃.

**Comment by Zi7ar21** [comment]
I also have this issue, I'm on Arch

**Comment by sandikata** [comment]
I've fixed the issue by replacing Nvidia with AMD GPU and now all is pretty fine out of the box.
Nvidia is a cancer and pain in the ass..

**Comment by GrabbenD** [comment]
Has anyone figured out a workaround for Nvidia?

**Comment by Pepeshki** [comment]
Still an issue.

**Comment by sandikata** [comment]
> Has anyone figured out a workaround for Nvidia?

The workaround for this is to switch to AMD (like i did and forgot for all these problems).

**Comment by 12471220** [comment]
fuck you nvidia

**Comment by GrabbenD** [comment]
I lost respect for NVIDIA and wont be buying their products for a long, long time. Replaced my 3080 Ti with 6800 XT and haven't been happier since. My next GPU will be AMD again or Intel if they catch up to AMD

**Comment by SteavenGamerYT** [comment]
its still an issue

**Comment by LethalManBoob** [comment]
still an issue
