### ISSUE TITLE
Video Trimmer

### ISSUE THREAD

**Issue by piousdeer** [NixOS/nixpkgs#164414]
**Project description**
Video Trimmer is a GTK 4 app that cuts out a fragment of a video given the start and end timestamps. The video is never re-encoded, so the process is very fast and does not reduce the video quality.

**Metadata**

* homepage URL: https://apps.gnome.org/app/org.gnome.gitlab.YaLTeR.VideoTrimmer/
* source URL: https://gitlab.gnome.org/YaLTeR/video-trimmer
* license: gpl3
* platforms: linux

**Comment by ocfox** [comment]
Finish at #187730
