### ISSUE TITLE
Automatically link OS X applications to ~/Applications

### ISSUE THREAD

**Issue by mpscholten** [NixOS/nixpkgs#16455]
Currently, when installing macOS GUI applications like iTerm2 or Sequel Pro, you always have to manually symlink the applications from `~/.nix-profile/Applications` to `~/Applications`. This is bad user experience. E.g. homebrew cask can automatically do this for me.

Maybe we can find a way to do this automatically if the host OS is macOS. Let me know what you think about this idea :)

**Comment by mpscholten** [comment]
nixpkgs also provides jetbrains IDEs. These are closed source IDEs and thus nixpkgs is also just a distribution platform for them. Another closed source package I know of is factorio. I'm pretty sure sublime text is also closed source and available via nixpkgs.

Also keep in mind that we can just build our own iTerm2 [because it's open source](https://github.com/gnachman/iTerm2). The current iTerm2 nix expression is just not doing that.

**Comment by copumpkin** [comment]
I do think there's room for full .app artifacts to be built in nixpkgs, but by the design of Nix, I'd consider this issue to belong under the Nix issue tracker as an enhancement for `nix-env` or whatever will follow it. Managing the contents of ~/Applications is very much like managing the content of ~/.nix-profile and friends, which is what `nix-env` does today. Regular builders and the vast majority of stuff in nixpkgs has no ability (in principle at least, and often in practice too) to even write to your home directory.

**Comment by matthewbauer** [comment]
Eventually, I think we'll want to have some sort of "macOS app wrapper" functionality. This would create a fake .app file, requiring an exe path, some resources, and some .plist metadata. That's all ".app" bundles are really and I don't think they care if it's actually a symlink skeleton and not the real files. This would be especially useful for apps that  need to access special Mac APIs that aren't provided to non-apps.

**Comment by mpscholten** [comment]
> I do think there's room for full .app artifacts to be built in nixpkgs, but by the design of Nix, I'd consider this issue to belong under the Nix issue tracker as an enhancement for nix-env or whatever will follow it. 

Good suggestion :) I'll close this issue here and reopen it on the nix repo.

> Eventually, I think we'll want to have some sort of "macOS app wrapper" functionality. This would create a fake .app file, requiring an exe path, some resources, and some .plist metadata. That's all ".app" bundles are really and I don't think they care if it's actually a symlink skeleton and not the real files. This would be especially useful for apps that need to access special Mac APIs that aren't provided to non-apps.

Like that idea 👍
