### ISSUE TITLE
referencing /dev/disk/by-partuuid/... in postBootCommands hangs after systemd updated from 220 to 225

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#16460]
After updating my desktop from 15.09 to 16.03, it hangs on boot after
printing the message `regenerating udev hardware database...`. I do not
think the problem is directly related to that message; see below. Any
ideas for debugging this?

Here's what I've figured out so far:
- Using git-bisect, it seems that the problem starts at commit
  ecbe04b4, "systemd: Update to 225". (I had to cherry-pick 3cc04956,
  "libseccomp: Fix hash", to got it to build.)
- I don't think the script that prints "regenerating udev hardware
  database" is the one that hangs. I added a debugging echo command to
  the end of system.activationScripts.udevd (in
  nixos/modules/services/hardware/udev.nix), and I saw the extra message
  when I booted. So the hang happens after.
- The problem also happens on master (commit 0167eef9).
  The `regenerating udev hardware database...` message is no longer
  printed at master (I think that code was changed between 16.03 and master); the last messages before the hang are `setting up /etc...` and a bunch of "removing obsolete symlink ..." and "removing group ..." messages.

My next step was going to be to add more debugging statements to the
boot process, but I'm having trouble figuring out where any of that
stuff is. I can't find where `system.activationScripts.udevd` is called
from, and I was mystified to find that grep -R "egenerating udev"
/nix/store/(...)-nixos-16.0.3.git.3cc0495M produces no output (except
some errors, e.g. etc/zoneinfo/posix is a directory loop).

**Comment by falsifian** [comment]
My `configuration.nix` (simplified for debugging):

```
{config, pkgs, ...}:

{
  imports =
  [
    ./hardware-configuration.nix
  ];

  boot =
  {
    initrd =
    { luks.devices =
      [
        { device = "/dev/sdb2"; name = "SfricBtrSec"; }
        { device = "/dev/sda2"; name = "KfricBtrSec"; }
      ];
      supportedFilesystems = [ "btrfs" ];
    };

    loader.grub =
    { device = "/dev/sdb";
      enable = true;
    };

    postBootCommands = "${pkgs.cryptsetup}/sbin/cryptsetup create -d /dev/urandom cswap /dev/disk/by-partuuid/1a2a682c-5001-4088-922e-70819ed67f37 && mkswap /dev/mapper/cswap && swapon /dev/mapper/cswap";
  };

  fileSystems =
  {
    # Filesystems mounted at boot are defined hardware-configuration.nix, but
    # we add some extra options here.

    # More space on tmpfs.
    "/tmp".options = "size=16g";

    # Options that will hopefully improve btrfs performance.
    "/".options = "autodefrag,noatime,subvol=nixos_root";
    "/home".options = "autodefrag,noatime,subvol=home";
    "/btr".options = "autodefrag,noatime";
  };

  networking =
  {
    hostName = "angel-nixos";
  };

  services =
  { openssh =
    {
      enable = true;
      ports = [ 22 7549 ];
    };
  };
}
```

**Comment by falsifian** [comment]
My `hardware-configuration.nix`, which I edited a tiny bit: removing swap and moving fs options to `configuration.nix`:

```
{ config, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "pata_jmicron" "firewire_ohci" "usbhid" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/SfricBtrSec";
      fsType = "btrfs";
      #options = "subvol=nixos_root";
    };

  fileSystems."/tmp" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/SfricBtrSec";
      fsType = "btrfs";
      #options = "subvol=home";
    };

  fileSystems."/btr" =
    { device = "/dev/mapper/SfricBtrSec";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4a621c7a-c1f9-4ce1-a0e5-8acdde829dae";
      fsType = "ext2";
    };

  nix.maxJobs = 3;
}
```

**Comment by groxxda** [comment]
You may want to take a look at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-2.nix and https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-2-init.sh :
The activationScripts are called from https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-2-init.sh#L178

Can it be that the `postBootCommand` running `cryptsetup` is causing the hang? (maybe it waits for data from /dev/random or something like this)

**Comment by bendlas** [comment]
The config you posted boots in a vm for me. The problem sounds like it was in the state on your machine `/var` `/run`. You could try to move `/var`, do a nixos-install and if that solves the problem, recurse with `/var` subdirs, until the cuprit service is found.
Turning up systemd's log level might also help: https://freedesktop.org/wiki/Software/systemd/Debugging/

**Comment by falsifian** [comment]
Thanks for the tips. @groxxda's guess about `cryptsetup` was right: when I commented out postBootCommands, my system booted fine.

When I have more time, my next step might be to check whether `/var/lib/systemd/random-seed` is writable when postBootCommands is run, based on [this Ubuntu bug report's comments](https://bugs.launchpad.net/snappy/+bug/1462954).

@bendlas, I like your suggestion of moving `/var` out of the way, but I'm worried that will make the state of my system a little confusing, so I'll treat that as a last resort.

**Comment by falsifian** [comment]
Also, I tried mashing my keyboard, which is sometimes said to fix /dev/random hangs. Mashed for maybe half a minute and it didn't work.

**Comment by groxxda** [comment]
Maybe have a look at systemd-cryptsetup. I'm not sure if it helps though..
Also keep in mind that it's pretty normal that reading for example 8G from /dev/urandom takes a long time (5-10min on my machine)

**Comment by falsifian** [comment]
@groxxda, I left my machine overnight (after mashing the keyboard for 30 seconds) and it was still hung, so I don't think it's a matter of waiting. Also, I would expect cryptsetup to read at most a few KiB, though I couldn't find documentation of exactly how much it reads.

Has anyone gotten systemd-cryptsetup working with NixOS? Even if that works, there's a regression here I'd like to track down.

I think my next step, when I have some time, will be to put `dd if=/dev/urandom of=/dev/null count=...` into postBootCommands to test the theory that reading `/dev/urandom` hangs.

**Comment by falsifian** [comment]
Progress: if I replace `/dev/disk/by-partuuid/...` with `/dev/sda4', the system boots. This is not a great solution, since my computer is fickle about which disk is `sda` and which is `sdb`. Ideally it would be possible to access `/dev/disk/by-partuuid/...` in `postBootCommands`.

I guess `/dev/disk/by-partuuid/...` is not initialized early enough for it to work in postBootCommands (it works fine after boot).

I don't know enough about the `/dev` filesystem to immediately understand why a systemd update would cause this. I hope to dig into it more at some point, but if anyone has ideas, I'm all ears :-)

**Comment by Profpatsch** [comment]
triage: were you able to fix this?

**Comment by falsifian** [comment]
No, but I also haven't tried recently. I'll try to find time to try again in the next week or so.

**Comment by falsifian** [comment]
I haven't had time to look yet. I'll close this issue now, and re-open it when/if I get around to reproducing it.

**Comment by falsifian** [comment]
I can confirm that this is still an issue on 19.03. Basically the same symptom as in my initial message here, except I think the last boot message is `setting up /etc...`.

**Comment by Ma27** [comment]
As we're way after 225 and I'm not sure if someone will be able to build a recent NixOS with systemd v220 for testing purposes, so do you have a simple configuration for a VM (or a physical machine) to reproduce?

**Comment by falsifian** [comment]
Sorry, not at the moment. I will close for now, and re-open if I'm able to put together a simple configuration that at least semi-reliably triggers the issue on my machine.

**Comment by falsifian** [comment]
Okay, I had some time to simplify my configuration and verify that it still happens. Sorry, I haven't pared it down to a VM configuration. If you want to try reproducing this, the important part is `boot.postBootCommands`; I guess you could create your own encrypted swap partition and replace the partuuid with yours.

I'm on the 20.03 branch. (`/root/.nix-defexpr/channels/nixos/.git-revision` is b0c285807d6a9f1b7562ec417c24fa1a30ecc31a so I think that's what `nixos-rebuild boot` is using.)

With the below configuration, my system still hangs after `setting up /etc...` followed by a few messages about removing obsolete things in `/etc`.

configuration.nix:

    { config, pkgs, ... }:

    {
      imports =
        [ # Include the results of the hardware scan.
          ./hardware-configuration.nix
        ];

      boot = {
        initrd = {
          luks.devices = {
            SFricBtrSec = { device = "/dev/sdb2"; };
            KfricBtrSec = { device = "/dev/sda2"; };
          };
          supportedFilesystems = [ "btrfs" ];
        };
        loader.grub = {
          enable = true;
          version = 2;
          device = "/dev/sdb";
        };
        # May not work: see https://github.com/NixOS/nixpkgs/issues/16460
        postBootCommands = "${pkgs.cryptsetup}/sbin/cryptsetup create -d /dev/urandom cswap /dev/disk/by-partuuid/1a2a682c-5001-4088-922e-70819ed67f37 && mkswap /dev/mapper/cswap && swapon /dev/mapper/cswap";
      };

      fileSystems = {
        "/" = {
          device = "/dev/mapper/KfricBtrSec";
          fsType = "btrfs";
          options = [ "subvol=nixos_root" ];
        };

        "/boot" = {
          device = "/dev/disk/by-uuid/4a621c7a-c1f9-4ce1-a0e5-8acdde829dae";
          fsType = "ext2";
        };

        "/btr" = {
          device = "/dev/mapper/KfricBtrSec";
          fsType = "btrfs";
        };

        "/home" = {
          device = "/dev/mapper/KfricBtrSec";
          fsType = "btrfs";
          options = [ "subvol=home" ];
        };
      };

      networking.hostName = "angel";

      users.users = {
        james = {
          isNormalUser = true;
          extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
        };
      };

      system.stateVersion = "20.03"; # Did you read the comment?

    }

hardware-configuration.nix:

    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    { config, lib, pkgs, ... }:

    {
      imports =
        [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
        ];

      boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "pata_jmicron" "firewire_ohci" "usbhid" "sd_mod" ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      swapDevices = [ ];

      nix.maxJobs = lib.mkDefault 3;
      # High-DPI console
      console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
    }

**Comment by falsifian** [comment]
Okay, I'm 80% sure this is happening because `/dev/urandom` doesn't start working until entropy is provided later in the boot process. I observed the problem still happens if I directly reference /dev/sda4 (which maps to the correct partition about half the time; fortunately my other disk doesn't have a partition 4).

I'm not sure why switching to `/dev/sda4` worked for me earlier, but that was a long time ago.

I will try just moving this later in the boot process. I don't need swap so early.

**Comment by falsifian** [comment]
In case it helps anyone, I discovered there's a `swapDevices.*.randomEncryption` option. I don't know if it was there when I first attempted this. I added the following to my configuration.nix and it seems to work (at least with nixos-rebuild switch).

    swapDevices = [
      {
        device = "/dev/disk/by-partuuid/1a2a682c-5001-4088-922e-70819ed67f37";
        randomEncryption.enable = true;
      }
    ];
