### ISSUE TITLE
can't build mime-types in stable 21.11

### ISSUE THREAD

**Issue by wh0** [NixOS/nixpkgs#164680]
### Describe the bug
I'm trying to use nix to build nix in a different store path. In the 21.11 nixpkgs, that involves building python3, which involves downloading mime-types. The URL it uses `https://mirrors.kernel.org/gentoo/distfiles/mime-types-9.tar.bz2` is rotted, and I've tried a few things:

- the url in the expression https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/data/misc/mime-types/default.nix#L7 doesn't use `mirror://gentoo`, so setting NIX_MIRRORS_gentoo doesn't help
- the other listed mirrors for gentoo don't have that file anymore either
- the hashed mirror system makes it skip the postFetch hook that unpacks it, which makes it fail as well

### Steps To Reproduce
1. set nixpkgs channel to stable 21.11
2. `NIX_STORE_DIR=/tmp/nix/store nix-build '<nixpkgs>' -A nix`

### Expected behavior
mime-types-9 builds

### Screenshots
```
$ nix-build /tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv                                                                                                                                             
warning: binary cache 'https://cache.nixos.org' is for Nix stores with prefix '/nix/store', not '/tmp/nix/store'
these derivations will be built:
  /tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv
building '/tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv'...

trying https://mirrors.kernel.org/gentoo/distfiles/mime-types-9.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download mime-types-9 from any mirror
builder for '/tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv' failed with exit code 1
error: build of '/tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv' failed
```

hashed mirror attempt:
```
$ NIX_HASHED_MIRRORS='http://localhost:9988' nix-build /tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv
warning: binary cache 'https://cache.nixos.org' is for Nix stores with prefix '/nix/store', not '/tmp/nix/store'
these derivations will be built:
  /tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv
building '/tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv'...

trying http://localhost:9988/sha256/0gyla4wfiaccs0qh0hw7n08kdpnkkssglcg0z2jblb2lsdr4qna0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15524  100 15524    0     0  6737k      0 --:--:-- --:--:-- --:--:-- 14.8M
builder for '/tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv' failed to produce output path '/tmp/nix/store/g03q34vqbzbs9n298fiai1d9a6xv8al3-mime-types-9'
error: build of '/tmp/nix/store/wzirvd0qi20v7fw42vdcbpsyb3lin7wn-mime-types-9.drv' failed
```

### Additional context
in unstable nixpkgs, mime-types is replaced with mailcap

### Notify maintainers

@peterhoeg @SuperSandro2000 , if I may

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.90+, Debian GNU/Linux, 11 (bullseye)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
find: '/nix/var/nix/profiles/per-user': No such file or directory
```

beware, it's actually nix-bin from debian, and /nix doesn't exist

**Comment by dylex** [comment]
FWIW I found the file at https://oss.neverware.com/app-misc/mime-types/mime-types-9.tar.bz2 and just substituting this URL works with the same hash, so it sholud be right (though who knows how long it will stay around). (nix-prefetch-url won't work on this again because of the postFetch.)

**Comment by SuperSandro2000** [comment]
You can also create an overlay and alias mime-types to mailcap or fetch https://github.com/NixOS/nixpkgs/pull/156082.

**Comment by wh0** [comment]
Late followup:

@dylex, nice find on a surviving copy! It did work out.

@SuperSandro2000, thanks for the suggestion. I didn't need to use the overlay system after all.

This is a fixed-output derivation, so it sufficed to create a copy of the mime-types/default.nix file, edit the URL, and build that. Then the rest of nixpkgs can use the output from that--in the same store path as the original would have built--without any other modifications.

What would be the preference for fixing this in nixpkgs? Shall I open a PR to swap in that URL?

**Comment by SuperSandro2000** [comment]
> What would be the preference for fixing this in nixpkgs? Shall I open a PR to swap in that URL?

Sure

**Comment by bobby285271** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/165864
