### ISSUE TITLE
[Flakes] abook refuse to evaluate error on darwin while I don't use it

### ISSUE THREAD

**Issue by ahmedelgabri** [NixOS/nixpkgs#164634]
### Describe the bug

I don't use `abook` at all, but I'm getting this error when I'm trying to rebuild my flakes `darwin-rebuild switch --flake .` (same happens when I run `nix build`) and also I don't really use it or install it

```
∴ nix why-depends /run/current-system "nixpkgs#abook" --all
error: Package ‘abook-0.6.1’ in /nix/store/2hk95qkrlxwcaphx9ryw6bhqphpaixfq-source/pkgs/applications/misc/abook/default.nix:25 is not supported on ‘x86_64-darwin’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

### Steps To Reproduce
1. clone https://github.com/ahmedelgabri/dotfiles
2. run `nix build './#pandoras-box'` or `darwin-rebuild switch --flake .`

### Expected behavior
Expect `nix build` or `darwin-rebuild switch --flake .` to work fine

### Additional context
I ran `nix flake update` before running `nix build`

### Notify maintainers

@edwtjo @Stunkymonkey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(ahmed): `"darwin, nixpkgs-21.05pre286546.2cca79be09c"`
 - nixpkgs: `/nix/store/vi3pmjrcgl3vhb2mmqc95cy9arnz8fn0-source`
```

**Comment by hqurve** [comment]
By grepping through nixpkgs, `lbdb` depends on `abook` by default. (see https://github.com/NixOS/nixpkgs/blob/c484c5788e643862dd70adf45e99eb1919145603/pkgs/tools/misc/lbdb/default.nix#L7). However, abook is only lists linux as supported https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/applications/misc/abook/default.nix#L28. (Im not sure if this this is just nixpkgs or abook in general)

Up until https://github.com/NixOS/nixpkgs/commit/a9b8e7d21d27cdadbfed53aef8abcfbb373de691, lbdb has not depended on abook by default. Perhaps a mistake was made while refactoring. @AndersonTorres 

In the meantime, you can just override the `lbdb` package.
