### ISSUE TITLE
nixos/paperless-ng: Unable to consume documents when classification model is present

### ISSUE THREAD

**Issue by mart-w** [NixOS/nixpkgs#164615]
### Describe the bug
If there is a classification model present, when trying to consume a document from either the web interface or the consumption directory, it gets stuck at the stage "Retrieving date from document..." according to the web interface. If no classification model is present (i.e. `${cfg.dataDir}/classification_model.pickle` does not exist), consumption works fine, but classification-based automatic tagging of documents is obviously not available.

The bug matches the behaviour described in issue #148644. The workaround @ambroisie described there also applies here as deleting `paperless-ng`’s state directory also deletes the classification model.

### Steps To Reproduce
1. Enable the service.
2. Upload a document through the web interface. This should work without a problem.
3. Create a new tag, set its matching algorithm to "Auto", and assign the uploaded document this tag.
4. Generate the classification model using `${dataDir}/paperless-ng-manage document_create_classifier`.
5. Upload another document through the web interface. The process should get stuck as described.

### Expected behavior
The document should be consumed without any errors.

### Screenshots
![grafik](https://user-images.githubusercontent.com/5788421/158857264-7c4a3516-c84c-4f34-a681-4e08ac27121b.png)

### Additional context
I have been able to trace the problem back to line `/nixos/modules/services/misc/paperless-ng.nix:69`: It seems like blocking the system call set `@resources` causes the worker task consuming the document to be killed. Adding `SystemCallFilter = defaultServiceConfig.SystemCallFilter ++ [ "@resources" ];` to `systemd.services.paperless-ng-server.serviceConfig` solves the issue, however I do not know which specific syscalls inside `@resources` are actually needed here.

### Notify maintainers
@erikarvstedt @Flakebi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.103, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336538.64fc73bd74f, nixos-unstable-22.05pre356180.d5f23787297"`
 - channels(mart-w): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by ambroisie** [comment]
I do remember trying to use that functionality, but I had not made the link between it and the failure.

Thank you for finding it!
