### ISSUE TITLE
(question) How should I name a `git-hub` package when there's already one in nixpkgs?

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#16478]
I'd like to package @ingydotnet's [git-hub] [ingydotnet/git-hub] for Nix, but @sociomantic-tsunami's [git-hub] [sociomantic-tsunami/git-hub] is already packaged and occupying the name "git-hub". What name should I use for ingydotnet/git-hub?

[ingydotnet/git-hub]: </ingydotnet/git-hub>
[sociomantic-tsunami/git-hub]: </sociomantic-tsunami/git-hub>

**Comment by bjornfor** [comment]
My suggestion for package names:

ingydotnet-git-hub
sociomantic-tsunami-git-hub

(I guess there is no other reasonable solution when two projects have same name and same intent...)

**Comment by ingydotnet** [comment]
I might suggest putting `git-hub` in the front and then:

* `git-hub-2`
* `git-hub-alternate`
* `git-hub-ingydotnet`
* `git-hub-@ingydotnet`
* `git-hub-<ingydotnet>`

or somesuch. I have no idea what characters are supported, but `git-hub-@ingydotnet` definitely conveys that `ingydotnet` is a person.

Just my 2 pennies...

**Comment by solson** [comment]
My preference would be `git-hub-ingydotnet` and `git-hub-sociomantic-tsunami`.

On another note, are we allowed to simply rename the existing `git-hub`, or is there a way to make it an alias for `git-hub-sociomantic-tsunami` with a deprecated warning?

**Comment by 8573** [comment]
> On another note, are we allowed to simply rename the existing git-hub, or is there a way to make it an alias for git-hub-sociomantic-tsunami with a deprecated warning?

@solson: I don't know the answer, but the [Racer] package was recently renamed from `racerRust` to `rustracer`, and I wish there'd been a message saying anything more than that `racerRust` no longer existed.

[Racer]: <https://github.com/phildawes/racer>

**Comment by vcunat** [comment]
We have a standard way for aliases (`pkgs/top-level/aliases.nix`), but no good way for warnings yet.

**Comment by rasendubi** [comment]
(triage) can this be closed?
