### ISSUE TITLE
`pkgs.gjs` should be included automatically if screen auto rotation is required

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#164865]
### Describe the bug
On my ThinkPad x1-yoga the screen should be rotated accordingly when I rotate my laptop in real world based on the measurement of the accelerometer given that `hardwared.sensor.iio.enable` is set to be `true` on `gnome` desktop.

Previously I was using `gnome on Xorg` several months ago, everything is fine.

Then I switch to `wayland` (still `gnome`), the screen no long auto rotates. 

Today I finally have time to debug it. By using `journal -f` I notice that it complains the command `gjs` is missing. Then I include it in `environment.systemPackages` and the screen rotation becomes OK.

### Steps To Reproduce
1. exclude `pkgs.gjs` from `environment.systemPackages`
2. rotate the laptop in real world
3. the screen orientation does not change.

### Expected behavior
When rotating the laptop in the real world, the screen orientation should change accordingly. 
And `pkgs.gjs` should be included in the `gnome` desktop.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.28, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
As far as I can tell, GNOME does not enable IIO by default. But I would still expect it to work when enabled.

Could you provide the full message (most importantly, what actually requires `gjs`)? I do not have any supported hardware to test.

**Comment by astrojhgu** [comment]
> , what actually requires `gjs`)?

I think it is ` gnomeExtensions.screen-autorotate`

**Comment by jtojnar** [comment]
Extensions need manual tweaks, cc @piegamesde.
