### ISSUE TITLE
GCC wrapper fails inside FHSUserEnv

### ISSUE THREAD

**Issue by robgssp** [NixOS/nixpkgs#16487]
## Issue description

When `buildFHSUserEnv` is used to make an environment with gcc, the contained gcc doesn't work.

### Steps to reproduce

```
$ nix-shell --pure -E 'with import <nixpkgs> {}; (buildFHSUserEnv { name = "test1"; multiPkgs = pkgs: [ pkgs.gcc ]; }).env'
$$ echo 'int main() { return 0; }' > true.c
$$ gcc true.c -o true
/nix/store/kqy04h4bifynyvvd12r389zhrnkczjs8-binutils-2.26/bin/ld: cannot find crt1.o: No such file or directory
/nix/store/kqy04h4bifynyvvd12r389zhrnkczjs8-binutils-2.26/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
$$
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre84674.fbde3a7 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre84674.fbde3a7"

**Comment by abbradar** [comment]
Try adding `extraOutputsToInstall = [ "dev" ];` -- it's needed now to avoid pulling headers and static libraries for those who don't use them.

**Comment by robgssp** [comment]
That worked, thanks.
