### ISSUE TITLE
HomeAssistant: No module named 'zwave_js_server'

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#164864]
### Describe the bug

```
ModuleNotFoundError: No module named 'zwave_js_server'
```

### Notify maintainers

@mweinelt

I also don't know how to use teams.home-assistant on Github, which makes the meta.maintainers value useless for me, unless I were to evaluate that value, potentially (which has way too much overhead). 

### Metadata
Unstable branch

**Comment by mweinelt** [comment]
What's your config? How did you try to load `zwave_js`?

**Comment by 21stce** [comment]
I am not using any zwave devices or plugins (I have removed the details of the configuration). So, the intention is to not load any zwave related code.  

These are the modules that I have loaded:

```
      "switch.mqtt"  "climate.mqtt"   mqtt   device_automation   
solaredge   device_tracker  tuya  zeroconf switchbot    
  default_config       esphome      met       zoneminder       camera      ffmpeg 
```

**Comment by mweinelt** [comment]
You need to be more clear about what module options you are using.

**Comment by 21stce** [comment]
I am fairly sure the cause is (because I can't imagine any of the other modules causing this):
```default_config = {};```

AFAIK, it's also known that not all modules are loaded are available in the NixOS version of Home Assistant, right? 

I don't have any more modules than the above loaded. 

Do you know what happens to my live installation if I were to remove almost all configuration and load a minimal configuration and then switch back again? I.e. is there some kind of mutable effect? 

I am using the unstable branch of home assistant (just updated).

**Comment by dotlambda** [comment]
Can you try to reproduce this with as minimal a configuration as possible? Or else, can you post your entire `configuration.nix`?

**Comment by 21stce** [comment]
Does this help?

```
Traceback (most recent call last):
  File "/nix/store/wr2vrc5xah9369bpqx479cq8wbqkncbv-homeassistant-2022.2.9/lib/python3.9/site-packages/homeassistant/config_entries.py", line 733, in async_create_flow
    integration.get_platform("config_flow")
  File "/nix/store/wr2vrc5xah9369bpqx479cq8wbqkncbv-homeassistant-2022.2.9/lib/python3.9/site-packages/homeassistant/loader.py", line 566, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/nix/store/wr2vrc5xah9369bpqx479cq8wbqkncbv-homeassistant-2022.2.9/lib/python3.9/site-packages/homeassistant/loader.py", line 583, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/nix/store/wr2vrc5xah9369bpqx479cq8wbqkncbv-homeassistant-2022.2.9/lib/python3.9/site-packages/homeassistant/components/zwave_js/__init__.py", line 9, in <module>
    from zwave_js_server.client import Client as ZwaveClient
ModuleNotFoundError: No module named 'zwave_js_server'

```

**Comment by dotlambda** [comment]
> Does this help?

No.

**Comment by 21stce** [comment]
Adding `"zwave_js"` is a workaround:

```
  extraComponents = ["zwave_js"];
```

Why I would need that code is still a mystery, but I expect that whoever wrote the Home Assistant module does not understand the life cycle of Home Assistant objects, because otherwise this issue would not exist. So, I can for example imagine if one has *ever* loaded zwave functionality, that it registers some object, which then would also need such a module for subsequent operations. 

Home Assistant is written in Python, not Haskell, so who knows what crazy things it might be doing?

If one would be interested in improving the quality of the module, one could write a test that would setup random functionality in Hydra (or on some test server) such that at some point these issues are also triggered. I understand that such issues take work, but right now you have *no* idea, so this would be a start.

**Comment by dotlambda** [comment]
> If one would be interested in improving the quality of the module

We are interested in improving the quality. But we're not able to reproduce the issue unless you give us further information, like what you set `services.home-assistant.config` to.

**Comment by 21stce** [comment]
@grahamc They have not demonstrated they need this information at all. They just asserted they do. 

Why is it always the case that people that pull out the volunteer card have no arguments, no substance?

**Comment by 21stce** [comment]
@grahamc You are closing this, because you are lazy and/or incompetent, because otherwise you would not have abused your status.

**Comment by grahamc** [comment]
After seeing a fairly regular pattern of abusive behavior towards abusers I'm applying a 7 day ban.

**Comment by dotlambda** [comment]
> If I can't reproduce the issue on a _new_ machine, what would make you think you can?

I don't think you mentioned this before.
I'm afraid but this doesn't seem to be a NixOS issue.
At the same time, it's not an upstream Home Assistant issue per se, because the missing package is usually installed automatically.
If we could find out why zwave_js_server is imported, we migh be able to fix it upstream. But that is impossible to find out with the given information.
