### ISSUE TITLE
brscan5 # error: cannot download brscan5-1.2.6-0.amd64.deb from any mirror - curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by InLaw** [NixOS/nixpkgs#164840]
### Describe the bug

brscan5 fails via nixos configuration 

curl: (22) The requested URL returned error: 404
error: cannot download brscan5-1.2.6-0.amd64.deb from any mirror 

## fails 
```
hardware = {
   sane = { 
      enable = true ;
      extraBackends = [
        pkgs.utsushi 
        ] ;
      brscan5 = {  # brscan4 works
        enable = true ;
      };
   }; 
  };
```

## works
`nix-env -i brscan5`

### Expected behavior

should work in each scenario

### Screenshots

trying https://download.brother.com/welcome/dlf104033/brscan5-1.2.6-0.amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download brscan5-1.2.6-0.amd64.deb from any mirror

### Notify maintainers
@mattchrist
@jraygauthier

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
warning: unknown setting 'experimental-features'
warning: unknown setting 'experimental-features'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.13, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
warning: unknown setting 'experimental-features'
 - version: `nix-env (Nix) 2.3.16`
warning: unknown setting 'experimental-features'
 - channels(root): `"nixos-21.11.335130.386234e2a61"`
warning: unknown setting 'experimental-features'
 - channels(user): `"home-manager-21.11, nixos-21.11.335665.0f316e4d72d, nixpkgs-21.11.335665.0f316e4d72d, nixpkgs-unstable-22.05pre349906.7f65e4abd5e"`
warning: unknown setting 'experimental-features'
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by mattchrist** [comment]
Non-free derivations aren't cached by cache.nixos.org. That means that any user of this module will try to download directly from Brother's servers instead of the cache. Unfortunately, that means that if Brother yoinks a release (as they did with 1.2.6-0), that this module breaks.

[This was already updated once in nixos-unstable](https://github.com/NixOS/nixpkgs/pull/149497), where version 1.2.7-0 is being used, but it now seems that that version has been pulled as well...
