### ISSUE TITLE
psycopg2: cross compilation fails

### ISSUE THREAD

**Issue by tusj** [NixOS/nixpkgs#164958]
Cross compiling `psycopg2` currently fails. [Psycopg2](https://www.psycopg.org/docs) is a postgresql adapter for python, and therefore requires `postgresql`.

The runtime libraries for `postgresql` needs to be available for the host platform, and the binary `pg_config` from `postgresql` needs to be available for the build platform.
Currently, `postgresql` is only specified in `nativeBuildInputs`. That makes the `pg_config` binary available. However, it also makes the runtime libraries available built for build platform, not host platform. From what I understand, to make the runtime libraries for `postgresql` available for the target platform, `postgresql` should be added to `buildInputs`. However, the linking step fails because it still finds the native / build platform libraries.

I'd like to fix this issue myself, but I need some pointers on the best way to proceed. I can see two ways to fix this:

1. The runtime libraries for native should not be available to the linker when building for the host platform.
2. In nativeBuildInputs, specify a `postgresql` package which does not include the runtime libraries.

Error when building: `pkgsCross.armv7l-hf-multiplatform.python39Packages.psycopg2`
`/nix/store/521z5w03bmrs4d2qxpnbcqk80lvn7p4v-postgresql-13.6-lib/lib/libpq.so: file not recognized: file format not recognized`
Examining the file format reveals that it is build for x86-64, the build platform.

**Comment by Artturin** [comment]
Looks like the bug caused by https://github.com/NixOS/nixpkgs/pull/177538 and fixed today in https://github.com/NixOS/nixpkgs/pull/177888

**Comment by Artturin** [comment]
Oops linked the wrong pr

https://github.com/NixOS/nixpkgs/pull/169475 caused it
