### ISSUE TITLE
golly-beta: still needed?

### ISSUE THREAD

**Issue by armeenm** [NixOS/nixpkgs#164983]
Is this package still needed? Golly is on version 4.1.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 2.8.99.2.20161122
desired version: -

###### Notify maintainers

maintainers: @7c6f434c

###### Note for maintainers

Please tag this issue in your PR.

**Comment by 7c6f434c** [comment]
>Is this package still needed? Golly is on version 4.1.

Hmm indeed probably can be dropped.

**Comment by armeenm** [comment]
Removed in #165100. Thanks!
