### ISSUE TITLE
Firefox 98 uses incorrect wmclass

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#165107]
### Describe the bug
Firefox 98 sets `firefox-default` as wmclass for its windows. This does not match the implicit wmclass of the desktop file (`firefox`), making GNOME dissociate them from the launcher icons.

### Steps To Reproduce

1. Rebuild GNOME session with Firefox 98 (have Firefox pinned in the panel)
2. Start Firefox
3. Notice there are two Firefox icons in the panel.

### Expected behavior
Firefox windows should re-use the launcher icons.

### Additional context
Looks like `RemotingName=firefox-default` in `${firefox.unwrapped}/lib/firefox/application.ini` might something to do with it (it was `RemotingName=firefox` previously). Likely originating from this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1530052.

### Notify maintainers
cc @buckley310 @K900 who talked about this on Matrix
cc @mweinelt who updated it in https://github.com/NixOS/nixpkgs/pull/163197

### Metadata

NixOS unstable 9bc841fec1c0e8b9772afa29f934d2c7ce57da8e

**Comment by K900** [comment]
Should probably just explicitly pass the right value to `wrapFirefox`.

**Comment by mweinelt** [comment]
```python
@depends("MOZ_APP_REMOTINGNAME", moz_app_name, update_channel)
def moz_app_remotingname(value, moz_app_name, update_channel):
    if value:
        return value[0]
    if update_channel == "release":
        return moz_app_name
    return moz_app_name + "-" + update_channel
```

Seems to be a result of this function, that we're now ending up with `firefox-default` because we're not using the release update channel.

I'm wondering if reusing the `binaryName` would be alright, or if we need to introduce another variable.

**Comment by K900** [comment]
Where does `update_channel` come from? Maybe that should be set to `release` instead?

**Comment by mweinelt** [comment]
```python
# Branding
# ==============================================================
option(
    env="MOZ_APP_REMOTINGNAME",
    nargs=1,
    help="Used for the internal program name, which affects profile name "
    "and remoting. If not set, defaults to MOZ_APP_NAME if the update channel "
    "is release, and MOZ_APP_NAME-MOZ_UPDATE_CHANNEL otherwise.",
)


@depends("MOZ_APP_REMOTINGNAME", moz_app_name, update_channel)
def moz_app_remotingname(value, moz_app_name, update_channel):
    if value:
        return value[0]
    if update_channel == "release":
        return moz_app_name
    return moz_app_name + "-" + update_channel


set_config("MOZ_APP_REMOTINGNAME", moz_app_remotingname)
```

I'd be more inclined to set `MOZ_APP_REMOTINGNAME` since we don't support any kind of update process.

**Comment by mweinelt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1752418 is the mozbz bug that introduced this regression.

**Comment by mweinelt** [comment]
```
❯ sleep 1; swaymsg -t get_Tree | jq '.. | select(.type?) | select(.focused==true).app_id'
"firefox-default"
❯ sleep 1; swaymsg -t get_Tree | jq '.. | select(.type?) | select(.focused==true).app_id'
"firefox"
```

Preparing a batch of fixes that I will publish later today.
