### ISSUE TITLE
Test kubernetes-rbac-singlenode is broken (21.11)

### ISSUE THREAD

**Issue by wamserma** [NixOS/nixpkgs#165109]
### Describe the bug

https://hydra.nixos.org/job/nixos/release-21.11/nixos.tests.kubernetes.rbac-single-node/all

The test started failing Jan 1st.

### Notify maintainers
@zowoq

**Comment by zowoq** [comment]
Sorry but I don't care about stable.

**Comment by wamserma** [comment]
21.11 is nearing EOL and the test works on 22.05.
