### ISSUE TITLE
Packaging request: realsense-viewer

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs#165140]
**Project description**

![](https://raw.githubusercontent.com/wiki/IntelRealSense/librealsense/res/realsense-viewer-backup.gif)

Realsense-viewer is an official application for playing around with Intel® RealSense™ depth cameras (D400 series and the SR300).
We already have [librealsense](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/development/libraries/librealsense/default.nix#L72) in nixpkgs, but it does not include all of the official tools:

```
$ ls /nix/store/sgcm8np2ix9vjal8safbwc773b5imwid-librealsense-2.45.0/bin 
rs-color    rs-distance           rs-fw-update        rs-pose-and-image  rs-save-to-disk
rs-convert  rs-enumerate-devices  rs-hello-realsense  rs-pose-predict    rs-terminal
rs-depth    rs-fw-logger          rs-pose             rs-record
```

**Metadata**

* homepage URL: https://github.com/IntelRealSense/librealsense/tree/master/tools/realsense-viewer
* source URL: https://github.com/IntelRealSense/librealsense/tree/master/tools/realsense-viewer 
* license: asl20
* platforms: unix

@brian-dawn :pray:

**Comment by brian-dawn** [comment]
Hello,

About a year ago I spent some time looking at what this would entail. According to my notes we need to add the libraries mesa, gtk3, glfw, and libGLU. Then we just need to turn on the flags BUILD_GRAPHICAL_EXAMPLES and BUILD_GLSL_EXTENSIONS.

I don't have much time these days to package it up, but hopefully this is helpful to someone!
