### ISSUE TITLE
LD_PRELOAD in electron wrapper breaks unwrapped commands called by obsidian.

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs#165148]
### Describe the bug
Obsidian is unable to run (non-nixpkgs) git commands, due to `$LD_PRELOAD` being prefixed with `libXScrnSaver`. 

### Steps To Reproduce
1. Have non-nixpkgs `git`
2. open [obsidian](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/applications/misc/obsidian/default.nix#L68) from nixpkgs
3. Setup [Obsidian Git](https://github.com/denolehov/obsidian-git) in obsidian
4. Run the `Obsidian Git: Backup Vault` command

### Expected behavior
Git syncing properly

### Actual behavior
`git: failed on initialization`

### Additional context

```console
$ nix-shell -p obsidian

[nix-shell:~]$ head `which obsidian`
#! /nix/store/bm7jr70d9ghn5cczb3q0w90apsm05p54-bash-5.1-p8/bin/bash -e
exec "/nix/store/xcrfxl4cb8s0q0w3c5qanym06vdpahw1-electron-13.6.9/bin/electron"  /nix/store/g3hg2i1m81rf68xpansw9jqpg7yk7wkr-obsidian-0.12.19/share/obsidian/app.asar "$@"

[nix-shell:~]$ head /nix/store/xcrfxl4cb8s0q0w3c5qanym06vdpahw1-electron-13.6.9/bin/electron
#! /nix/store/bm7jr70d9ghn5cczb3q0w90apsm05p54-bash-5.1-p8/bin/bash -e
export LD_PRELOAD='/nix/store/2nldwldgaiwd0zwph8sj13xdiqysdxgb-libXScrnSaver-1.2.3/lib/libXss.so.1'${LD_PRELOAD:+':'}$LD_PRELOAD
export GIO_EXTRA_MODULES='/nix/store/wsc48b6izbpm0v70wv9dryrnb0776pq1-dconf-0.40.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GIO_EXTRA_MODULES='/nix/store/wsc48b6izbpm0v70wv9dryrnb0776pq1-dconf-0.40.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GDK_PIXBUF_MODULE_FILE='/nix/store/nlpa9gavw5zszfyp50krca2iba7ymhvn-librsvg-2.52.4/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
export XDG_DATA_DIRS='/nix/store/z2phd72675fma3nz1l4jzpignf4zycvd-gtk+3-3.24.30/share/gsettings-schemas/gtk+3-3.24.30:/nix/store/vsf6wf9g6glsdw3mkbyd0q5m1gmvcfb4-gsettings-desktop-schemas-41.0/share/gsettings-schemas/gsettings-desktop-schemas-41.0'${XDG_DATA_DIRS:+':'}$XDG_DATA_DIRS
exec -a "$0" "/nix/store/xcrfxl4cb8s0q0w3c5qanym06vdpahw1-electron-13.6.9/lib/electron/.electron-wrapped"  "$@"

[nix-shell:~]$ which git
/usr/bin/git

[nix-shell:~]$ echo $LD_PRELOAD


[nix-shell:~]$ export LD_PRELOAD='/nix/store/2nldwldgaiwd0zwph8sj13xdiqysdxgb-libXScrnSaver-1.2.3/lib/libXss.so.1'${LD_PRELOAD:+':'}$LD_PRELOAD

[nix-shell:~]$ git
git: symbol lookup error: /nix/store/65hafbsx91127farbmyyv4r5ifgjdg43-glibc-2.33-117/lib/libdl.so.2: undefined symbol: _dl_catch_error_ptr, version GLIBC_PRIVATE
```

### Notify maintainers

@ConradMearns @zaninime @travisbhartwell @manveru @prusnak

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.25-1-MANJARO, Manjaro Linux, noversion`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(pbsds): `"nixpkgs-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/pbsds/channels/nixpkgs`
```

**Comment by prusnak** [comment]
Why don't you use git from nixpkgs (e.g. `nix-shell -p obsidian git`)?

**Comment by pbsds** [comment]
That does work, although I'd prefer not to install git with `nix-env` on manjaro. I have other workaround that i use, i simply wanted to report how `libXss.so` seem to break subcommands.

**Comment by pbsds** [comment]
Just updated, and this also affects electron 16

**Comment by zaninime** [comment]
We could consider prepending `git` to `PATH` in the derivation (the start script in the output).

**Comment by prusnak** [comment]
> We could consider prepending `git` to `PATH` in the derivation (the start script in the output).

@pbsds can you guesstimate how many percent of obsidian users have obsidian-git plugin installed?

**Comment by pbsds** [comment]
Of all obsidian users: few.
Of obsidian&cap;nixpkgs users: maybe 20%?

**Comment by pbsds** [comment]
Possibly related: #137871

**Comment by prusnak** [comment]
@pbsds can you please check whether the fix in https://github.com/NixOS/nixpkgs/pull/172961 fixes this issue for you?

**Comment by pbsds** [comment]
Seems to work!
