### ISSUE TITLE
bitbucket-cli: remove or use fork

### ISSUE THREAD

**Issue by armeenm** [NixOS/nixpkgs#165101]
bitbucket-cli on pypi has not been updated [since 2015](https://pypi.org/project/bitbucket-cli/#history) and depends on python2. It also seems it [no longer uses a functioning API](https://bitbucket.org/zhemao/bitbucket-cli/issues/34/api-no-longer-supported). This package can either be removed or we can use a [fork](https://bitbucket.org/gneel/bitbucket-cli/src/master) which supports the newer bitbucket API and python3. Thoughts?

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: bitbucket-cli

current version: 0.5.1
desired version: -

###### Notify maintainers

maintainers: @refnil 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by Mindavi** [comment]
My preference would be to remove it, since I don't think there are any users if it doesn't actually work. Repackaging can always be done in the future if new users arrive.
