### ISSUE TITLE
[RFC] fetchFromGitHub for release archives

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#16513]
## Issue description

Currently `fetchFromGitHub` only allows fetching the source archive.
Some programs (mainly those using autoconf) also provide a _release archive_ that includes a prebuilt configure script.

So a packager has to choose to use either 
- `fetchFromGitHub` and include `autoconf` / `autoreconfHook` plus possible some other dependencies
- `fetchurl` and specify the github url for the _release archive_.

It would be nice if we extended `fetchFromGitHub` to provide a way to download the _release archive_.

The change should be fairly trivial and backward-compatible, I'm just wondering if I'm missing something and this is already possible or if this would be considered an improvement in which case I'll be happy to make the required changes and submit a PR.

```
nixpkgs $ ag -A5 'fetch(zip|url)' | grep github.\*/release | wc -l
144
```

**Comment by joachifm** [comment]
Are release archives modified/generated by github? If not, I think it makes sense to simply use `fetchurl` for release archives.

**Comment by vcunat** [comment]
No, those true releases are only changed by hand, I think. It might still make sense, as there's a difference whether the result is already unpacked or not.

**Comment by c0bw3b** [comment]
Should we keep this open?
I find using `fetchurl` for stable releases to be clearer and more straightforward. The biggest problem is rather the opposite (some using fetchurl on unstable GH archives)

**Comment by c0bw3b** [comment]
Closing for now.
The current situation is that:
* `fetchurl` should be used for stable GH _release_ assets ; `fetchzip` can also be used is one wants to use its `postFetch` hook as seen in many fixed-output derivations.
* `fetchFromGitHub` or `fetchzip` should be used on GH _archives_ depending on personal preferences and features (the former allows to fetch git submodules).
