### ISSUE TITLE
rustUnstable isn't built by hydra

### ISSUE THREAD

**Issue by rardiol** [NixOS/nixpkgs#16526]
## Issue description

https://hydra.nixos.org/job/nixpkgs/trunk/rustUnstable.rustc.x86_64-linux is not on the jobset ( I think rustBeta isn't either)

https://hydra.nixos.org/job/nixpkgs/trunk/rustc.x86_64-linux is.
### Steps to reproduce

nix-shell -p rustUnstable.rustc
## Technical details
- System: 16.09pre85572.20a8349 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre85639.453086a"

maintainers    @madjar @cstrahan @wizeman @globin @havvy @wkennington @retrry

**Comment by primeos** [comment]
(triage) Looks like we can close this now :smile:.

https://github.com/NixOS/nixpkgs/blob/8ddfbe34bcfc9ab5abe36a53117af9be69423732/pkgs/top-level/aliases.nix:
```
rustUnstable = rustNightly; # added 2016-11-29
```

And `rustNightly` should be build by Hydra: https://hydra.nixos.org/job/nixpkgs/trunk/rustNightly.rustc.x86_64-linux/all?page=1

Latest build: https://hydra.nixos.org/build/50745520 (~4h ago).
