### ISSUE TITLE
autoResize and autoFormat should use mount options x-systemd.makefs and x-systemd.growfs instead of custom units

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#165256]
Systemd includes code in `systemd-fstab-generator` that will format and resize file systems automatically. There's no need for our custom units.

**Comment by flokli** [comment]
Is this all done for systemd-in-initrd?

**Comment by ElvishJerricco** [comment]
@flokli Yea but we have custom services in stage 2 that should be replaced with the systemd utilities. [I have a commit here for it that I haven't tried to get merged yet](https://github.com/NixOS/nixpkgs/commit/bb0cd5d48ae7f4feb85848d7c42aa42185306ae3). The main differences are there's no way to do `formatOptions` and the set of resizable file systems is a little different.

**Comment by flokli** [comment]
Yeah, we used this to construct different mkfs.* arguments depending on the filesystem types.

https://github.com/systemd/systemd/blob/main/src/shared/mkfs-util.c#L260 should have some of this logic, at least for most common filesystems today.

I'm a bit unsure about this - the additional options were used once, so all existing installations shouldn't regress if we drop this, and the assertion explains this. Should be fine?
