### ISSUE TITLE
Salt security update on 2022/03/28

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#165332]
https://saltproject.io/security_announcements/attention-some-critical-vulnerabilities-have-been-discovered-in-salt-versions-3004-and-earlier/

@Flakebi

**Comment by mweinelt** [comment]
@Flakebi are you on top of this?

**Comment by Flakebi** [comment]
Thanks for the heads up, yeah, just waited for the GitHub releases to appear. I’ll create a PR soon.
