### ISSUE TITLE
Octoprint fails to build due to recent change in black

### ISSUE THREAD

**Issue by gador** [NixOS/nixpkgs#165323]
### Describe the bug

Due to the update in #157800 which includes https://github.com/psf/black/pull/2791 octoprint fails to build in current unstable release. Octoprint needs a `click` version <8, whereas black now demands a version of >= 8. 

### Steps To Reproduce
1. `nix-build -A octoprint https://github.com/nixos/nixpkgs/tarball/nixos-unstable`

### Expected behavior
octoprint should build.

### Error message
```
ERROR: Could not find a version that satisfies the requirement click>=8.0.0 (from black) (from versions: none)
ERROR: No matching distribution found for click>=8.0.0
```

### Notify maintainers

@abbradar @gebner @WhittlesJr 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.26, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(florian): `"agenix"`
 - channels(root): `"agenix, nixos, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

One could add an additional overwrite for black at this point.
On the other hand, octoprint just released its rc2 which drops python2 support and makes a lot of the overwrites unnecessary.

**Comment by SuperSandro2000** [comment]
Please just remove black from the test pipeline. There is no reason to run it.

**Comment by gador** [comment]
AFAIK black isn't used in the test pipeline. At least neither click, nor octoprint have black as a build input. 
Still, some package version of derivation seems to require black. I submitted a PR, which pins the version of black to the last working version.

**Comment by SuperSandro2000** [comment]
> Still, some package version of derivation seems to require black.

Black is almost never a runtime dependency. Most of the time it can be safely removed from any requires which safes us the hassle of pinning it or fixing issues.

**Comment by gador** [comment]
Hi @SuperSandro2000 

as I said [here](https://github.com/NixOS/nixpkgs/pull/165389#issuecomment-1079719732)  it **is** a runtime dependency. In this case `ipython`.
In any case, I would rather see https://github.com/NixOS/nixpkgs/pull/165328 move forward, which would remove most of the overrides.

**Comment by SuperSandro2000** [comment]
We should probably wait for a stable release of octoprint first
