### ISSUE TITLE
gtk 3 wxGTX 3.1 programs POEdit, Kicad, and QGIS fail assertion '(withWebKit -> (stdenv).isDarwin)'

### ISSUE THREAD

**Issue by DarkKirb** [NixOS/nixpkgs#165444]
### Describe the bug
The pull request #163335 introduced a regression where certain wxGTK 3.1 applications fail the assertion `'(withWebKit -> (stdenv).isDarwin)'`. In particular the following packages seem to be affected:

- `poedit`
- `kicad`, `kicad-small`, `kicad-unstable`, `kicad-unstable-small`

### Steps To Reproduce
1. in a nix repl, `:lf github:NixOS/nixpkgs/55b85b13561945f6c8fcb84995b0f76762cf3362`
2. try to evaluate the expression `outputs.legacyPackages.x86_64-linux.poedit`

### Expected behavior
Something similar to 

```
«derivation /nix/store/152ybxsvldg9fpfbfik65j7l2vb6n4mv-poedit-3.0.1.drv»
```

### Actual behavior
```
nix-repl> outputs.legacyPackages.x86_64-linux.poedit        
error: assertion '(withWebKit -> (stdenv).isDarwin)' failed

       at /nix/store/z19plswfzbjzmv2pdh2bvp69rgq5h23m-source/pkgs/development/libraries/wxwidgets/wxGTK31.nix:35:1:

           34|
           35| assert withWebKit -> stdenv.isDarwin;
             | ^
           36|
[27.8 MiB DL]«derivation 
```

### Notify maintainers
@AndersonTorres @tfmoraes @knl

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.29, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by willcohen** [comment]
This is also affecting `qgis` on linux:

```
$ nix-build $NIXPKGS -A qgis
error: assertion '(withWebKit -> (stdenv).isDarwin)' failed

       at /home/wcohen/programming/nix/nixpkgs/pkgs/development/libraries/wxwidgets/wxGTK31.nix:35:1:

           34|
           35| assert withWebKit -> stdenv.isDarwin;
             | ^
           36|
(use '--show-trace' to show detailed location information)
```

**Comment by knl** [comment]
I'm looking into this, will try to find some time tonight. Probably the safest thing is to remove this assertion, as it's wrong (or reverse it).
