### ISSUE TITLE
enlightenment and terminology can't find evas's generic loaders

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#16541]
## Issue description

Enlightenment and terminology need evas_generic_loaders for loading svg icons and the likes. But those are packaged separately under evas.nix without the relevant dependencies and runtime library paths in place.

### Steps to reproduce

In Enlightenment, the menus and file-manager fail to render .svg icons.

In Terminology, tyls fails to do the same.

#### *Ugly* workaround for debugging purposes

"mount /nix/store -o remount,rw" and link\copy the evas store to the efl store. Restart enlightenment or execute tyls in a directory with a .svg.

#### Notes

0. Regardless of the actual issue, please consider renaming evas.nix to evas_generic_loaders.nix.

1. evas_generic_loaders depend on the EFL during compilation. But the EFL requires the loaders in it's search path... Unless packaged together with a custom builder.sh like audio players ([deadbeef](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/audio/deadbeef) is a good example) package their plugins, it might be necessary to do some substantial wrapping.

2. For upstream, this was likely a licensing issue where the EFL is BSD while the loaders function as shims to non-compatible licenses.

@matejc @tstrobel @ftrvxmtrx

**Comment by RamKromberg** [comment]
geany-with-vte has a really clean and simple solution for this problem that should work almost out of the box.

**Comment by matejc** [comment]
```

**Comment by matejc** [comment]
I was trying to get svg-s working for past 4 hours .. no success
here are 3 main variants: https://gist.github.com/matejc/bcbec1650aadf4b4d9d85f08df9df129
does anyone have any (more) ideas?

**Comment by matejc** [comment]
ideas - beside building all libs and apps in one prefix

**Comment by RamKromberg** [comment]
I couldn't keep up with the compilation duration and had to give up. But I concluded that following the order mentioned in the {release site)[https://www.enlightenment.org/download] should work:
```
 When compiling from source, build in this order:

    efl

    The following then only if using releases of 1.17 or before (GIT no longer needs these).

    elementary
    emotion_generic_players
    evas_generic_loaders

Then any further applications or tools (in any order now) such as:

    enlightenment
    terminology
    rage
    etc
```

So, _elf-unwrapped_ first.

Followed by _elementary-unwrapped_ depending on it.

Combine both using that geany-with-vte trick as a single store dir called _elf-elementary-unwrapped_. And then build _emotion_generic_players-unwrapped_ and _evas_generic_loaders-unwrapped_ depending on that.

Now combine everything as _efl-elementary-emotion-evas-wrapped_ and build enlightenment, terminology and rage depending on that.

Well, it's just cheap talk seeing how I couldn't even compile the EFL under 5hours with my potato... But if I could I would just have sorted it myself and wouldn't have bothered with opening an issue to being with ;)

**Comment by RamKromberg** [comment]
With the latest 1.18 version and git going forwards, the plugins were all rolled into the efl so this issue sorted itself out following https://github.com/NixOS/nixpkgs/issues/17941 :)
