### ISSUE TITLE
haskellPackages.semigroups missing build dependencies

### ISSUE THREAD

**Issue by stepcut** [NixOS/nixpkgs#16542]
Starting in this patch:

https://github.com/NixOS/nixpkgs/commit/05cdb0f621240d7e5815ffdb3af814872eb4d6fd#diff-e4ed6fefa9564bfd27ee249e42e145e2

semigroups only depends on  [ base ] even though it should depend on a bunch of other libraries. As a result I get a build failure:

```
building path(s) ‘/nix/store/3dfxzyazk4zamrnzw1rpz3jzbn7mkmbx-semigroups-0.18.1’
setupCompilerEnvironmentPhase
Build with /nix/store/744p99ryvxaivs4v8nnwlpnn2hks2qj2-ghcjs-0.2.0.
unpacking sources
unpacking source archive /nix/store/rhybh1ilb1n4szwhzb4z5qc41k2l248k-semigroups-0.18.1.tar.gz
source root is semigroups-0.18.1
setting SOURCE_DATE_EPOCH to timestamp 1453843016 of file semigroups-0.18.1/src/Data/Semigroup/Generic.hs
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/semigroups-0.18.1/revision/1.cabal.
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/var/folders/_b/wj7ns2190gd3hbz9w0f3m17c0000gn/T/nix-build-semigroups-0.18.1.drv-0/package.conf.d -j8
[1 of 1] Compiling Main             ( Setup.lhs, /private/var/folders/_b/wj7ns2190gd3hbz9w0f3m17c0000gn/T/nix-build-semigroups-0.18.1.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/3dfxzyazk4zamrnzw1rpz3jzbn7mkmbx-semigroups-0.18.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=clang --package-db=/private/var/folders/_b/wj7ns2190gd3hbz9w0f3m17c0000gn/T/nix-build-semigroups-0.18.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --disable-split-objs --disable-library-profiling --disable-executable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --disable-tests --with-hsc2hs=/nix/store/mwa46vkw4rf6swnnicdabf5d4107hryg-ghc-7.10.3/bin/hsc2hs --ghcjs
Configuring semigroups-0.18.1...
Setup: At least the following dependencies are missing:
hashable >=1.1 && <1.3,
tagged >=0.4.4 && <1,
text >=0.10 && <2,
unordered-containers ==0.2.*
builder for ‘/nix/store/rzlnvp59j7icfb443xi8g7cl4m0bdknp-semigroups-0.18.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/7sll91j2dbk4gs1zhfc1hhvys6mpsl8k-ghcjs-0.2.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/7sll91j2dbk4gs1zhfc1hhvys6mpsl8k-ghcjs-0.2.0.drv’ failed
/Users/stepcut/.nix-profile/bin/nix-shell: failed to build all dependencies

```

@peti

**Comment by peti** [comment]
According to http://hackage.haskell.org/package/semigroups-0.18.2/semigroups.cabal, the package needs additional build inputs only on pre 8.x compilers.

**Comment by stepcut** [comment]
Ah -- that makes sense, but doesn't solve my problem. In this case I am building with `ghcjs-0.2.0` which has not yet been updated to GHC 8.x. I updated the build output above to include more context. 

I see that in `configuration-ghc-7.8.x` there is a line:

    semigroups = addBuildDepend super.semigroups self.nats;

Do we need to update all the `configure-ghc-7.*.*.nix` files to manually add the dependencies back in?

**Comment by peti** [comment]
> Do we need to update all the configure-ghc-7.*.*.nix files to manually add the dependencies back in?

Yes.

The alternative is to use build expressions that have been generated specifically for the target platform, i.e. `haskell.packages.ghc7103.callHackage "semigroups" "0.18.2" {}` would give you a version of `semigroups` that's aware of the requirements of GHC 7.x. I'm not sure whether that works for ghcjs, too, but I think it should.

**Comment by peti** [comment]
I'm closing this issue because it doesn't seem actionable, i.e. I don't know what to do to improve matters. If someone who does submits a PR then that would be great.
