### ISSUE TITLE
util-linux `look` searches for `/usr/share/dict/words` which does not exist

### ISSUE THREAD

**Issue by vrthra** [NixOS/nixpkgs#16545]
## Issue description

The look program should look up words in the system dictionary, which either should be present at /usr/share/dict/words or another location.
### Steps to reproduce

```
$ look help
look: /usr/share/dict/words: No such file or directory
zsh: exit 1     look help
```
## Technical details
- System:

$ nixos-version
16.03.909.f199be0 (Emu)
- Nix version:

$ nix-env --version
nix-env (Nix) 1.11.2
- Nixpkgs version:

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.03.909.f199be0"

$ nix-instantiate --eval ~/Development/nixpkgs -A lib.nixpkgsVersion
"16.09pre-git"

**Comment by rnhmjoj** [comment]
Is there any package providing the `words` file?

**Comment by vrthra** [comment]
Not sure if a package in Nix provides it. In ubuntu, it is provided [thus](http://installion.co.uk/ubuntu/vivid/main/w/wamerican/install/index.html)

**Comment by ryantm** [comment]
It doesn't look like any package is specifically providing it. Maybe we should package the words package as described in the Arch User Repository ( https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/words ) and add it as a dependency on util-linux

**Comment by nixy** [comment]
I might take a swing at packaging `words` but this would also require patching `util-linux` to make `look` use the dictionaries from the package. Not sure if I know how that would be done.

**Comment by matthewbauer** [comment]
It looks like ```nixpkgs.scowl``` provides this list for us. But, I don't think we want to put it in everyone's closure. Instead, I think we can make a NixOS module using the ```WORDLIST``` env var

**Comment by mixmixmix** [comment]
still important to me. After installing `scowl` I can access the list in the store `/nix/store/bp5qlbs8fih1p84kxgf0xn87csayjahw-scowl-2019.10.06/share/dict` but this is hardly sufficient in the long run.

**Comment by OmnipotentEntity** [comment]
I've written up a very rough attempt at addressing this problem.  It's my very first attempt at a NixOS module.

I have not, yet, attempted to use this module at all, I just wanted to know if the approach was sane. If there are minor syntactical issues, I can work those out.  I'm more worried about the general approach.  Is it OK?  Am I missing something important that is already provided by something?

If it's OK, where in the nixpkgs directory tree should it live?

```
{ lib, pkgs, ... }:

{
  options = {
    wordlist = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to include (an) environment variable(s) containing (a)
          wordlist(s).
        '';
      };

      lists = mkOption {
        type = types.nonEmptyListOf ( types.submodule {
          options = {
            envVar = mkOption {
              type = types.nonEmptyStr;
            };
            source = mkOption {
              type = types.path;
            };
          };
        });
        default = [
          {
            envVar = "WORDLIST";
            source = "${pkgs.scowl}/share/dict";
          }
        ];
        description = ''
          A list of the environment variables and the word lists you'd like to
          associate.
        '';
        example = literalExpression ''
          lists = [
            {
              envVar = "WORDLIST";
              source = "${pkgs.scowl}/share/dict";
            }
          ];
        '';
      };
    };
  };

  config = lib.mkIf config.wordlist.enable {
    environment = lib.forEach config.wordlist.lists (x: "${x.envVar}" = x.source;);
  };
}
```

**Comment by OmnipotentEntity** [comment]
It seems like my PR is in the final stages of review.  If anyone has any good suggestions for it, please let me know!

**Comment by OmnipotentEntity** [comment]
#158034 has been merged :partying_face:

To use it simply set `environment.wordlist.enable = true` in your configuration.nix.  The default is sane.  It sets the `$WORDLIST` variable (which is used by `look` by default) to the default wordlist in the `scowl` package, which as mentioned upthread is the wordlist package used in many popular distributions by default.

As far as I am aware, this is everything needed to finally put this issue to bed, so I'm going to close this issue.  Special thanks to @pennae and the rest of the folken in the NixOS Dev Matrix Chat for guiding me through the process of making my first module.  Thanks to @rissson for giving me a review.  And thanks @Synthetica9 for the merge.
