### ISSUE TITLE
obsidian and dwarf-fortress-packages.themes.obsidian have conflicting names

### ISSUE THREAD

**Issue by avh4** [NixOS/nixpkgs#165559]
### Describe the bug

nixpkgs.obsidian (https://obsidian.md/) and nixpkgs.dwarf-fortress-packages.themes.obsidian (https://github.com/DFgraphics/Obsidian) have conflicting names, 1) causing confusion, and 2) causing issues when trying to update packages using `nix-env -u`.

### Steps To Reproduce
1. `nix-channel --add https://nixos.org/channels/nixpkgs-unstable` 
2. `nix-channel --update`  (current version is https://github.com/NixOS/nixpkgs/commit/3eb07eeafb52bcbf02ce800f032f18d666a9498d)
3. `nix-env -i -A nixpkgs.obsidian` (should install obsidian-0.13.31, the knowledge base app)
4. `nix-env -u` (removes obsidian-0.13.31, the knowledge base app, and installs obsidian-74.05, the dwarf fortress theme)

### Expected behavior
obsidian-0.13.31 (the knowledge base app) should remain installed.  (Or, later when a new version is available, that new version should be installed.)  It should not be removed and replaced by the dwarf fortress theme.

### Additional context

- obsidian-0.13.31 (the knowledge base app) has 1.9k github stars (https://github.com/obsidianmd/obsidian-releases)
- obsidian-74.05 (the dwarf fortress theme) has 3 github stars (https://github.com/DFgraphics/Obsidian)

imo, most people trying `nix-env -i obsidian` are probably looking for the knowledge base app.  I'd suggest either the dwarf fortress theme should be given a new name, or both packages should be given new names.

### Notify maintainers

obsidian-0.13.31 maintainers: @conradmearns @zaninime @opeik
obsidian-74.05 maintainers: @matthewbauer @shazow

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-37-generic, Ubuntu, 21.10 (Impish Indri)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(user): `"nixgl, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by shazow** [comment]
As a user of both, +1 to renaming the dwarf fortress theme. :)

**Comment by opeik** [comment]
I think renaming the dwarf fortress theme would be sensible 😅

**Comment by noghartt** [comment]
+1 to rename the Dwarf Fortress theme.
