### ISSUE TITLE
`nobody` user shown in LightDM login screen

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#16557]
## Issue description

If I use X11 and set my display manager to LightDM (`services.xserver.displayManager.lightdm.enable = true`), then go to log in via LightDM, the `nobody` user account is shown in LightDM's menu of user accounts available to log in to, complete with its GECOS description of "Unprivileged account (don't use!)".

By default, the `services.xserver` module has the display manager hide the `nobody` user account [(1)](https://github.com/NixOS/nixpkgs/blob/331fa2feff8cbdca5cc831d1fae36d9505618124/nixos/modules/services/x11/display-managers/default.nix#L209). However, the `nix` module overrides this default to hide its `nixbld` user accounts [(2)](https://github.com/NixOS/nixpkgs/blob/1d4b21ef42a41fcecc254f61f279ad306f41e6b3/nixos/modules/services/misc/nix-daemon.nix#L413), incidentally causing LightDM to not hide `nobody`.

SLiM and SDDM don't seem to be affected — SLiM doesn't list user accounts anyway, and SDDM seems to filter out `nobody` on its own initiative.
### Steps to reproduce

To see that the `nix` module overrides the `services.xserver` module's default of hiding `nobody`:

```
$ nixos-option services.xserver.displayManager.hiddenUsers
```

To see the result, log in with LightDM with no further configuration of `server.xserver.displayManager.hiddenUsers`.
## Technical details
- System: NixOS `16.09pre85639.453086a (Flounder)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: "16.09pre85639.453086a"`

**Comment by FRidh** [comment]
I encountered something similar with `nm-openvpn` user in https://github.com/NixOS/nixpkgs/issues/16401

**Comment by Profpatsch** [comment]
triage: still an issue?

**Comment by 8573** [comment]
I have failed to reproduce this issue on a system with the following `nix-info -m` output:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.48, NixOS, 18.09pre143771.a8c71037e04 (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

It appears that manually specifying `services.xserver.displayManager.hiddenUsers = ["nobody"]` is no longer necessary for LightDM not to list the `nobody` user.

**Comment by 8573** [comment]
@michalrus: I note that you "thumbs-upped" my initial report. Does this issue still apply to you?

**Comment by michalrus** [comment]
No longer
