### ISSUE TITLE
GraalVM builds broken for x86_64-darwin on unstable

### ISSUE THREAD

**Issue by whentze** [NixOS/nixpkgs#165670]
### Describe the bug

On current nixpkgs unstable, GraalVM 11 and 17 both fail to build for darwin.
Since this is a build dependency of several other packages like `babashka` and `clj-kondo`, these are also broken.

We have bisected nixpkgs and found that the regression was likely introduced in https://github.com/NixOS/nixpkgs/pull/149731

### Steps To Reproduce
1. Be a Mac
2. `nix-build -A graalvm11-ce https://github.com/nixos/nixpkgs/tarball/12e48068a5aa63a3965d9a0c65409c875c5877c4`

### Expected behavior
The build should succeed

### Screenshots
Error message from the build:
```
patching script interpreter paths in /nix/store/mh8g4k1azqa8xx6mnlcfknckdhaybx1i-graalvm11-ce-lib
Traceback (most recent call last):
  File "/nix/store/0jzc88szm7fsjrhzs7jbcj4ini24sj9f-auto-patchelf.py", line 322, in <module>
    with open_elf(interpreter_path) as interpreter:
  File "/nix/store/3j4k5ja8zpr7v5xiyfgjwjb8qnl4iycv-python3-3.9.10/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/nix/store/0jzc88szm7fsjrhzs7jbcj4ini24sj9f-auto-patchelf.py", line 26, in open_elf
    yield ELFFile(stream)
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 73, in __init__
    self._identify_file()
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/elf/elffile.py", line 482, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 77, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/nix/store/0qmwd1hj38nj7dsnyhn5pxbwqv6f52m1-python3-3.9.10-env/lib/python3.9/site-packages/elftools/common/utils.py", line 114, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Magic number does not match
```

### Additional context

The builds are failing on Hydra too:

https://hydra.nixos.org/job/nixpkgs/trunk/graalvm11-ce.x86_64-darwin
https://hydra.nixos.org/job/nixpkgs/trunk/graalvm17-ce.x86_64-darwin

#163924 Looks like it may be related to this.

### Notify maintainers
Author of #149731:
@layus

GraalVM package maintainers:
@bandresen
@volth
@hlolli
@glittershark
@babariviere
@ericdallo
@thiagokokada

**Comment by thiagokokada** [comment]
However, strange that this seems to be affecting only M1 and not Intel Macs. I will take a look but can't promise anything since I only have access to a Intel one.

**Comment by thiagokokada** [comment]
#163924 should already fix this, so I don't think we need to do anything.

**Comment by whentze** [comment]
> However, strange that this seems to be affecting only M1 and not Intel Macs. I will take a look but can't promise anything since I only have access to a Intel one.

Wait, is that true?

The machine that we reproduced this on happened to be a M1 mac running Nix in x86_64 emulation, but nothing I've seen so far indicated that Intel macs wouldn't be affected.

**Comment by david-morgan-otm** [comment]
> > However, strange that this seems to be affecting only M1 and not Intel Macs. I will take a look but can't promise anything since I only have access to a Intel one.
> 
> Wait, is that true?
> 
> The machine that we reproduced this on happened to be a M1 mac running Nix in x86_64 emulation, but nothing I've seen so far indicated that Intel macs wouldn't be affected.

I got the same error on my Intel Macbook.

**Comment by thiagokokada** [comment]
> > However, strange that this seems to be affecting only M1 and not Intel Macs. I will take a look but can't promise anything since I only have access to a Intel one.
> 
> Wait, is that true?
> 
> The machine that we reproduced this on happened to be a M1 mac running Nix in x86_64 emulation, but nothing I've seen so far indicated that Intel macs wouldn't be affected.

I am completely sure that I read in the report that it was happening only on `aarch64-darwin`, but it seems I misread. It makes more sense to happens on both anyway, since as I said `autoPatchElf` shouldn't be used on darwin at all (macOS doesn't use ELF format for binaries).

Anyway, it doesn't seem to matter to much since there is a fix already.

**Comment by thiagokokada** [comment]
Since #163924 was merged in `staging`, I am building `babashka` on `staging` right now to see if the issue is fixed. If not, I will try to investigate the issue.

**Comment by thiagokokada** [comment]
```
Finished generating 'bb' in 5m 22s.
installing
post-installation fixup
strip is /nix/store/2dwp1nhk1zsv8fq9djqq4nmhih2abnj9-cctools-binutils-darwin-949.0.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/gvy48ay4d4rvmg4ww6933zqsd405k1gc-babashka-0.7.8/bin
patching script interpreter paths in /nix/store/gvy48ay4d4rvmg4ww6933zqsd405k1gc-babashka-0.7.8
/nix/store/gvy48ay4d4rvmg4ww6933zqsd405k1gc-babashka-0.7.8

~/Projects/nixpkgs staging 12h 40m 40s
❯ ./result/bin/bb -e '(+ 1 1)'
2
```

So it seems to be working fine in `staging`.

**Comment by ajeetdsouza** [comment]
PowerShell seems broken too.

**Comment by whentze** [comment]
This has been solved for a while now in unstable, closing.
