### ISSUE TITLE
Crystal builder supports only github and cannot handle pre-releases

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#165748]
We call only `fetchFromGitHub` in our crystal builder, which means other sources aren't supported.

If a shard is tagged on GH as a pre-release, it isn't downloadable using `fetchFromGitHub` without munging the `rev` attribute as the URL is different.

Example: `rev = "v0.6.4";` vs `rev = "refs/tags/v0.6.4";` for crystal-email ref https://github.com/arcage/crystal-email/issues/74

**Comment by peterhoeg** [comment]
I'll be fixing this shortly. Cc: @NixOS/crystal-lang

**Comment by Artturin** [comment]
Dupe of https://github.com/NixOS/nixpkgs/issues/118021
Closed it in favor of this

**Comment by peterhoeg** [comment]
Wow, I managed to open a duplicate of my own issue......

**Comment by peterhoeg** [comment]
Fixed. Waiting for it to hit unstable.
