### ISSUE TITLE
nvidia udev process fails

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#165719]
```
Mar 24 18:20:17 porty systemd-udevd[90508]: card0: Process '/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0 c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 0'' failed with exit code 1.
Mar 24 18:20:17 porty systemd-udevd[90533]: card0-DP-3: Process '/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia3 c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 3'' failed with exit code 1.
Mar 24 18:20:17 porty systemd-udevd[90584]: card0-DP-2: Process '/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia2 c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 2'' failed with exit code 1.
Mar 24 18:20:17 porty systemd-udevd[90508]: card0-DP-1: Process '/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia1 c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 1'' failed with exit code 1.
Mar 24 18:20:17 porty systemd-udevd[90574]: card0-HDMI-A-1: Process '/nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia1 c $(grep nvidia-frontend /proc/devices | cut -d \  -f 1) 1'' failed with exit code 1.
```

This is on latest nixos unstable `commit 1ec61dd4167f04be8d05c45780818826132eea0d (nixos/nixos-unstable)`

**Comment by VergeDX** [comment]
Same issues here.
Every time I plug / unplug DP port, It appears and crash my GDM.

I found this line in hardware - nvidia NixOS module:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/nvidia.nix#L365=

**Comment by colemickens** [comment]
I've got some cleanup commit(s): https://github.com/colemickens/nixpkgs/commits/cmpkgs

ctrl-f "nvidia". I've got a lot of cleanups in progress.

I still have flickering (I think it's a sway issue) but no crashing and actually, I somehow fixed EGL+Xwayland.

I'm not sure what you're experiencing though -- at least, I can't imagine why a failing udev rule would just cause gnome to crash. For the most part these rules seem to be setting permission on hotPLUG rather than unplug. But, I just got it to quiet down, I didn't investigate super thoroughly.

**Comment by jessestricker** [comment]
I also have these warnings (added some whitespace for better reading):

<details>
<pre>
May 23 15:10:09 copper systemd-udevd[688]: nvidia:          Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidiactl c 195 255'' failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0-DP-1:      Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0-HDMI-A-1:  Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0-DP-2:      Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0-DP-3:      Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0-Unknown-1: Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:10 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:11 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:11 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:12 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
May 23 15:10:12 copper systemd-udevd[688]: card0:           Process '/nix/store/14lypyys4gfcl982rjddxa6jg7msqz9q-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0   c 195 0'    failed with exit code 1.
</pre>
</details>

Note that those `card0-???-#`, warnings are for the physical sockets on the back of the card which are **not connected** to any monitor. The `card0-Unknown-1` is a USB-C socket.
The connected sockets, `HDMI-0` and `DP-0`, do not generate a warning.

Also note that the first line (beginning with `nvidia: Process...`) is trying to create a different file.

My setup:

- NVIDIA RTX 2060 SUPER
- Latest stable proprietary driver
- Latest unstable nixpkgs
- `hardware.nvidia.modesetting.enable = true`

**Comment by nrdxp** [comment]
I can no longer use the HDMI port on my laptop either. Tried reverting to 22.05 to see if it would help but no dice. Either way, I get this in my log over and over again, and my system becomes laggy until I unplug the cable:
```
Jul 02 16:20:42 triton systemd-udevd[47004]: card1: Process '/nix/store/j9rc786ylq8cid4zgcn6idknilkbd4ax-bash-5.1-p16/bin/bash -c 'mknod -m 666 /dev/nvidia0 c 195 0' failed with exit code 1.
Jul 02 16:20:43 triton kernel: [drm:nv_drm_gem_export_nvkms_memory_ioctl [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to lookup NVKMS gem object for export: 0x00000001
```

**Comment by nrdxp** [comment]
after some testing, I found that #126604 resolves the udev errors in the log. It didn't fully resolve my HDMI issues, but it did help. I was able to render retroarch to an external monitor via VK_KHR_display, which I wasn't able to do previously. So that's definitely an improvement, and the system stalling repetitive erros are also gone. The PR does have a merge conflict but it's pretty simple to resolve, I just copy and pasted the line from the PR replacing the existing line in a fork of nixos-unstable to test and it worked well.

**Comment by nrdxp** [comment]
I don't use X so I'm not sure. I stil cannot use [Vivarium](https://github.com/nrdxp/vivarium) (wayland) with an external monitor, so something is still wrong since I was able to a few months ago. Like I mentioned, the main improvements are the fact that my system is not longer unresponsive when the HDMI cable is plugged in, and that I was at least able to use retroarch from a tty, which I wasn't before.

**Comment by exzombie** [comment]
For the record, I cherry-picked the commit on top of 22.05 to test. Plugging external monitors in hybrid mode still crashes X11 on my Thinkpad P15. This laptop is only usable in discrete GPU mode. Too bad, I was hoping this was related 🤷‍♂
