### ISSUE TITLE
Release Schedule for 22.05

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#165792]
This is a GitHub issue now to make it editable which is not the case on [Discourse](https://discourse.nixos.org/t/lets-have-a-great-22-05-release-cycle/18357).

|| Date | Branches Affected | Events |
|-| --- | --- | --- |
|:heavy_check_mark:| April, 03 | - | Ask ecosystems for desired changes, in "Feature Freeze" |
|:heavy_check_mark:| April, 17 | `staging-next`, `staging` | Restrict breaking changes to Release Critical Packages |
|:heavy_check_mark:| May, 01 | `staging-next`, `staging` | Restrict all breaking changes: allow only non-breaking updates and Desktop Manager changes |
|:heavy_check_mark:| May, 07 | `master` | (Day before ZHF) merge `staging-next` into `master`, prep for ZHF |
|:heavy_check_mark:| May, 08 | `master` | Begin ZHF, Focus on minimizing regressions in PRs targeting `master` |
|:heavy_check_mark:| May, 15 | `master` | Merge first `staging-next` fixes into `master`; begin second `staging-next` cycle |
|:heavy_check_mark:| May, 15 | `staging` | Unrestrict all breaking changes; new changes will not be present in `master` before branch-off |
|:heavy_check_mark:| May, 22 | `master` | Merge second `staging-next` fix cycle |
|:heavy_check_mark:| May, 22 | `staging-next` | Unrestrict all breaking changes; new changes will not be present in `master` before branch-off |
|:heavy_check_mark:| May, 22 | `master`, `22.05` | Perform Branch-off, create release channels, create new beta / unstable tags |
|:heavy_check_mark:| May, 22 | `master`, `22.05` | ZHF transitions to "backporting" workflow |
|:heavy_check_mark:| May, 22 | `22.05` | Prepare for release, finish remaining issues |
|:heavy_check_mark:| May, 30 | `22.05` | Release! Also, ZHF ends |
|:heavy_check_mark:| June, 30 | - | Release Retrospective Meeting |

**Comment by Artturin** [comment]
The release wiki is available at https://nixos.github.io/release-wiki/

**Comment by Mindavi** [comment]
Is anyone up for marking all packages that are not building at the end of ZHF as broken? Would be lovely if we could go all the way this time 🙂, even though it's quite a lot of work. I don't think I'll manage to do everything on my own though, so doing it together with some others would be nice.

Also, what would be the best moment to do this be? Towards the end of ZHF?

(Give me a thumbs down if you don't like this idea, I've seen it discussed before but last time it didn't happen afaik)

**Comment by vcunat** [comment]
At/after the end and ideally before forking (but could be merged to both afterwards).

**Comment by roberth** [comment]
> `22.05`

Are we changing the name of the release branch?
This used to be the name of the tag, which is a footgun https://github.com/NixOS/release-wiki/pull/13:

> the tags have caused confusion and security
problems when user configurations accidentally reference
the tag instead of the release branch.

> Releases are never final.

**Comment by shlevy** [comment]
The nixpkgs manual should be updated to note that `staging` and `staging-next` are sometimes restricted by the release process. As-is the docs suggest it's basically always OK to merge tested changes into `staging` and always OK to merge `staging` into `staging-next` if `staging-next` is not being used.

**Comment by davidak** [comment]
It would be great to get https://github.com/NixOS/nixpkgs/pull/175128 in, improving the documentation of installing NixOS.

Please help to review.
