### ISSUE TITLE
virtualisation.libvirtd.enable option brings up a broken virt-xml-validate

### ISSUE THREAD

**Issue by renatoGarcia** [NixOS/nixpkgs#165708]
### Describe the bug

If just enabled `virtualisation.libvirtd.enable = true` on `/etc/nixos/configuration.nix`, the `virt-xml-validate` executable will be on system path, but when called it will break with error:

    /nix/store/kwv9550j1ip0sgm9rgh70pz5ljhh1dj1-system-path/bin/virt-xml-validate: line 129: xmllint: command not found

### Steps To Reproduce
1. Enable `virtualisation.libvirtd.enable = true` on `/etc/nixos/configuration.nix`
2. Make sure that neither `libvirt` or `libxml2` are explicitly installed
3. Create an empty or use any libvirt xml (`touch /tmp/aaa.xml`)
4. Run `virt-xml-validate /tmp/aaa.xml domain`

### Expected behavior

I would expect that if the `virtualisation.libvirtd.enable = true` option adds `virt-xml-validate` to the system path, that program would work correctly.

### Additional context

The `virt-xml-validate` executable is part of `libvirt` package. The `libvirt` package by its turn is the default value of `virtualisation.libvirtd.package`.

The `xmllint` executable is part of `libxml2` package. The `libxml2` package is in the [`buildInputs` list](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/development/libraries/libvirt/default.nix#L115) of `libvirt`. If either `libvirt` or `libxml2` packages are explicitly installed, the `xmllint` executable will be put on system path, and the bug will be gone.

### Notify maintainers

@fpletz @globin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.105, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(renatofg): `"nixpkgs-22.05pre360843.3eb07eeafb5"`
 - channels(root): `"nixos-21.11.336538.64fc73bd74f"`
 - nixpkgs: `/home/renatofg/.nix-defexpr/channels/nixpkgs`
```

**Comment by FliegendeWurst** [comment]
Fixed in #159390
