### ISSUE TITLE
Packaging request: hred

### ISSUE THREAD

**Issue by tejing1** [NixOS/nixpkgs#165720]
**Project description**
I've been searching for a tool to extract structured data usefully from web pages which don't provide a machine-readable interface such as RSS, and I recently found `hred`. `hred` extracts data from html using a language based on css selectors, but unlike other programs such as `pup` that do the same, it outputs its matches in (fairly configurable) json rather than as a flat list, and if that's not configurable enough, it can easily be piped into `jq` for more complex processing. It also apparently handles xml.

It seems better-thought-out than other tools in the category to me, and it doesn't seem to die horribly when exposed to real-world html either, like xml-oriented things often do.

I did try running `node2nix` in a local checkout, and the derivation it produced worked for me with no tweaking, so this is probably fairly trivial to package. I'm just not really familiar with how nixpkgs handles node stuff, so I'm not confident doing it myself.

**Metadata**

* homepage URL: https://github.com/danburzo/hred
* source URL: https://github.com/danburzo/hred
* license: mit
* platforms: anywhere node.js works

**Comment by AndersonTorres** [comment]
I will play a bit with it.
