### ISSUE TITLE
gedit segfaults with gtk+-3.20.5 on nixos-unstable

### ISSUE THREAD

**Issue by womfoo** [NixOS/nixpkgs#16576]
Upstream has already [fixed](http://ftp.gnome.org/pub/gnome/sources/gtk+/3.20/gtk+-3.20.6.news) this and I can confirm that the issue goes away when compiling against gtk+-3.20.6.

What is the process for changes involving mass rebuilds? Should I raise a PR with the gtk version/hash under nixpkgs-master?

### Steps to reproduce

* launch gedit
* press the save button
* type in a filename and press save in the dialog
* notice that gedit crashed

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre85639.453086a (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre85639.453086a"

**Comment by vcunat** [comment]
The process is to commit mass rebuilds to the staging branch. You can create a PR against that.

**Comment by womfoo** [comment]
Thanks @vcunat just raised a PR.

**Comment by garbas** [comment]
this is fixed in master now, just check that gedit works
