### ISSUE TITLE
Mediathekview version 13.8.0 -> 13.8.1 (official log4j)

### ISSUE THREAD

**Issue by j-steinbach** [NixOS/nixpkgs#165881]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: mediathekview

current version: 13.8.0
desired version: 13.8.1

This update contains the official log4j fix: [changelog](https://mediathekview.de/changelog/13-8-1/)

###### Notify maintainers

maintainers: @Moredread 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by LeSuisse** [comment]
Done in #194125
