### ISSUE TITLE
No users.users.*.hashedPasswordFile option

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#165858]
Password hashes, while less sensitive than unhashed passwords, are secrets. We should therefore have a `hashedPasswordFile` option in `users.users` that avoids both placing the hashes in the store world-readable and storing the password unhashed.

**Comment by rnhmjoj** [comment]
This is a common misunderstanding due to the bad naming of these options:

- `password` → string of plaintext password
- `hashedPassword` → string of password hash
- `passwordFile` → file containing password hash

So, what you want already exists and it's `passwordFile`.

**Comment by lheckemann** [comment]
Oh wow, indeed. Thanks!

Given that the option is named so confusingly and that its description starts with "The full path to a file that contains the user's password." I think we should keep the issue, pending an option rename and a documentation improvement.
