### ISSUE TITLE
Packaging request: Oversteer

### ISSUE THREAD

**Issue by mightyiam** [NixOS/nixpkgs#165817]
**Project description**
 Steering Wheel Manager for GNU/Linux 

**Metadata**

* homepage URL: https://github.com/berarma/oversteer
* source URL: https://github.com/berarma/oversteer
* license: [GPL-3.0](https://github.com/berarma/oversteer/blob/master/LICENSE)
* platforms: linux

**Comment by MatthiasBenaets** [comment]
Would love to see this packaged as well!
Tried it myself, but I'm afraid I don't have the needed knowledge yet. Got it to build but no output.

**Comment by zimbatm** [comment]
Merged in #211423 thanks to @srounce

**Comment by mightyiam** [comment]
Thank you, @srounce!
