### ISSUE TITLE
Python: applications are affected by PYTHONPATH

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#16591]
## Issue description

pythonpath leaks into subprocesses all over the place
### Steps to reproduce an example
- `nix-env -i nox`
- `nix-shell -p python27Packages.enum34`
- `nox -h`

```
[nix-shell:~]$ nox -h
Traceback (most recent call last):
  File "/nix/store/6n255nladjbailvkkhs0ai0ls01iiphq-python2.7-enum34-1.0.4/lib/python2.7/site-packages/enum/__init__.py", line 371, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/wf1za4si6rl5y45kcxhslyjq9wywcakr-nox-0.0.3/bin/.nox-wrapped", line 8, in <module>
    from nox.search import main
  File "/nix/store/wf1za4si6rl5y45kcxhslyjq9wywcakr-nox-0.0.3/lib/python3.5/site-packages/nox/search.py", line 4, in <module>
    import subprocess
  File "/nix/store/q17rbyq94md0z91g289d5p8rc2q2b60c-python3-3.5.1/lib/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/nix/store/q17rbyq94md0z91g289d5p8rc2q2b60c-python3-3.5.1/lib/python3.5/signal.py", line 8, in <module>
    _IntEnum._convert(
  File "/nix/store/6n255nladjbailvkkhs0ai0ls01iiphq-python2.7-enum34-1.0.4/lib/python2.7/site-packages/enum/__init__.py", line 373, in __getattr__
    raise AttributeError(name)
AttributeError: _convert
```

**Comment by FRidh** [comment]
You know `nix-shell` sets `PYTHONPATH`, so you would know this will happen. Of course it is nice if it wouldn't but it does. 

I can imagine with Nix you expect better, but this would happen on other systems as well. If you set `PYTHONPATH`, then other Python applications will break. How do you suggest to protect Python applications from `PYTHONPATH`? Maybe we should unset `PYTHONPATH` in the wrapper first? 
https://github.com/NixOS/nixpkgs/pull/13721

**Comment by RonnyPfannschmidt** [comment]
the thing is, if all nix does for setting up environments is creating env vars, its pretty much not delivering its promise

it should pretty much set up different trees of symlinks for different working environments
this one is the same reason why the tox package on nix is completely broken for example

**Comment by FRidh** [comment]
In https://github.com/NixOS/nixpkgs/commit/def310df459f649a4ce2df8b7ba19aa8e4d5af58 I fixed a bug with setuptools that affected tox. Now you should be able to just `nix-env -i pythonPackages.tox`. However, at this point it still comes with a wrapper. In https://github.com/NixOS/nixpkgs/pull/16668 I took out the `PYTHONPATH` wrapper, although the `PYTHONHOME` wrapper remains.

Regarding your example with `nox`. You are aware of the `--pure` flag for `nix-shell`?

**Comment by FRidh** [comment]
See https://github.com/NixOS/nixpkgs/issues/16591 for a possible short-term fix.

**Comment by RonnyPfannschmidt** [comment]
#17749 fixes part of the problem, the nix-shell side needs more thought, perhaps off by one profiles are whats really needed

**Comment by RonnyPfannschmidt** [comment]
(in that case nix-shell is exactly correct)

**Comment by RonnyPfannschmidt** [comment]
@FRidh if i understand right, with the current python infrastructure, this one is fixed?

**Comment by FRidh** [comment]
In principle yes, but we still have quite some applications and services that use `--prefix`.

**Comment by mmahut** [comment]
Closing this, if you see find it in a specific application, please open an issue against it directly.
