### ISSUE TITLE
`start display-manager' doesn't work while booting NixOS iso

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#16596]
## Issue description

When booting from a NixOS iso, the message

> Type `start display-manager' to start the graphical user interface

is displayed on the screen. Howerver, `start display-manager` doesn't work (the command `start` doesn't exist). The message should instead say `systemctl start display-manager`.

## Technical details

* System: channels/nixos-unstable

**Comment by DamienCassou** [comment]
or the command `start` must be created.

**Comment by dezgeg** [comment]
The `start` was recently removed, so it should be changed to use `systemctl start`.

Also probably worth auditing the manual for the same in other places...

**Comment by matthewbauer** [comment]
This should be closed now, I think?

**Comment by DamienCassou** [comment]
Let's close it now, I will reopen if the problem persists next time I try. Thanks.
