### ISSUE TITLE
Konqueror starts with http://text/html

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#16601]
## Issue description

![virtualbox_nixos_29_06_2016_15_51_43](https://cloud.githubusercontent.com/assets/91113/16458626/09efe5ee-3e20-11e6-909e-ea7c6eb9171d.png)

There is a configured Home page <http://www.kde.org> but it's not loaded.
(could also be set to https://nixos.org/)

### Steps to reproduce

1. boot Graphical live CD, 64-bit
2. open Konqueror

## Technical details

* System: NixOS: 16.03.948.a96c308

**Comment by FRidh** [comment]
Since KDE 4 is [being deprecated](https://github.com/NixOS/nixpkgs/issues/15866) I doubt this issue will be fixed.

**Comment by davidak** [comment]
@FRidh Have you tested it in KDE 5?

**Comment by FRidh** [comment]
I don't think a KDE5/Qt5 port of Konqueror exists. There is also no repo at https://quickgit.kde.org/.

**Comment by davidak** [comment]
They seam to search a new maintainer since 2014: https://blogs.kde.org/2014/08/16/konqueror-looking-maintainer

So /close as `wontfix`.

**Comment by kupiqu** [comment]
This seems to be a problem of konqueror.desktop. You can try copying the one in your system to $HOME/.local/share/applications/ and replacing Exec line to: 
`Exec=konqueror`
