### ISSUE TITLE
broadcom-sta fails to build

### ISSUE THREAD

**Issue by X9VoiD** [NixOS/nixpkgs#166035]
### Describe the bug
`broadcom-sta` fails to build when I tried to execute `nixos-rebuild switch --upgrade`.

### Steps To Reproduce
1. `boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];`

### Expected behavior
`configuration.nix` should build successfully.

### Screenshots
![image](https://user-images.githubusercontent.com/10338031/160335087-e00e5767-b88c-4d21-9212-ff78d9cec215.png)

### Additional context
```console
[user@system:~]$ sudo nixos-rebuild switch --upgrade --verbose > nix.log 2>&1
```
[nix.log](https://github.com/NixOS/nixpkgs/files/8359991/nix.log)

### Notify maintainers
There are no maintainers for `broadcom-sta` anymore, so I'll instead mention the last contributors. 
@SebastienWae
@teto

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/5c9ixzdc3yr5yknb9axn2adagpi13m1n-bash-interactive-5.1-p16-dev
copying path '/nix/store/5c9ixzdc3yr5yknb9axn2adagpi13m1n-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.15, NixOS, 22.05 (Quokka), 22.05pre362445.9bc841fec1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - channels(oscar): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SebastienWae** [comment]
Sorry but I no longer have a machine that uses that driver, but it looks like it's broken with linux 5.17.
Here is the patch used by Arch: https://github.com/archlinux/svntogit-community/blob/packages/broadcom-wl-dkms/trunk/012-linux517.patch

**Comment by teto** [comment]
Likewise I dont have a machine that runs this driver anymore

**Comment by mannp** [comment]
Same issue for me on 3 machines.

**Comment by X9VoiD** [comment]
> Sorry but I no longer have a machine that uses that driver, but it looks like it's broken with linux 5.17. Here is the patch used by Arch: https://github.com/archlinux/svntogit-community/blob/packages/broadcom-wl-dkms/trunk/012-linux517.patch

Can confirm that this is working with
```
  boot.extraModulePackages = [ (config.boot.kernelPackages.broadcom_sta.overrideAttrs (old: {
    patches = old.patches ++ [
      (builtins.fetchurl {
        url = "https://raw.githubusercontent.com/archlinux/svntogit-community/5ec5b248976f84fcd7e3d7fae49ee91289912d12/trunk/012-linux517.patch";
        sha256 = "df557afdb0934ed2de6ab967a350d777cbb7b53bf0b1bdaaa7f77a53102f30ac";
      })
    ];
  })) ];
```
Will try to PR it.

**Comment by icodeforyou-dot-net** [comment]
Any idea when this issue will be resolved via the patch? I just failed to compile broadcom_sta when attempting to upgrade to kernel 5.17.1 on a Macbook Pro late 2013.

**Comment by SebastienWae** [comment]
> Any idea when this issue will be resolved via the patch? I just failed to compile broadcom_sta when attempting to upgrade to kernel 5.17.1 on a Macbook Pro late 2013.

It's unlikely to happen anytime soon, since it looks like no one with merging permission has hardware that uses this driver.

Maybe if @teto has some time he could review it since he is already familiar with it, and it seems that the PR is just the patch used by Arch.

In the meantime you can try and [review](https://nixos.org/manual/nixpkgs/stable/#chap-reviewing-contributions) the [PR](https://github.com/NixOS/nixpkgs/pull/166232) made bye X9VoiD.
