### ISSUE TITLE
breitbandmessung build fails due to missing command: autoPatchelfFile

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#166086]
### Describe the bug
Installing `breitbandmessung` fails due to missing command `autoPatchelfFile`:
```
$ sudo nixos-rebuild switch
building the system configuration...
error: builder for '/nix/store/bansdpcfz1p3yzrc2y2n61iklbc71z1h-breitbandmessung-3.1.0.drv' failed with exit code 127;
       last 8 log lines:
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > no Makefile, doing nothing
       > glibPreInstallPhase
       > installing
       > /nix/store/lkk0hf9h4x85mb4lrsf2sh25qm2i4n18-stdenv-linux/setup: line 1360: autoPatchelfFile: command not found
       For full logs, run 'nix log /nix/store/bansdpcfz1p3yzrc2y2n61iklbc71z1h-breitbandmessung-3.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/gvkryrkd675vr27y7ypdh8y39gd6nsxq-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lmv2zm0nwpk2n28di81kpfqag9rk86cx-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bk9nv989l6c7rbwzrcmfp9aha6691447-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z1y6yszbvwqbxn0j4j5alh20y71031hp-etc.drv' failed to build
error: error: 1 dependencies of derivation '/nix/store/91kzm0fr5kqjpfrfr3k02kgph4qh3x7a-nixos-system-home-pc-22.05.20220323.1d08ea2.drv' failed to build
```

### Steps To Reproduce
Install `breitbandmessung`, e.g. via `nix run "nixpkgs#breitbandmessung"`.

### Expected behavior
App should build, install & run without errors.

### Notify maintainers
@B4dM4n

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0, NixOS, 22.05 (Quokka), 22.05.20220323.1d08ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - nixpkgs: `/nix/store/hsff9pi1qinxljahr833z0xivr1apx27-source`
```

**Comment by felschr** [comment]
Looks like `autoPatchelfFile` was removed in https://github.com/NixOS/nixpkgs/commit/7b9fd5d1c9802131ca0a01ff08a3ff64379d2df4 as part of https://github.com/NixOS/nixpkgs/pull/149731.
@layus, was this change intended?

**Comment by layus** [comment]
Probably not. Let me see...

**Comment by layus** [comment]
Oh, yes, it seemed to me that it was only intended as an internal function for autoPachelf inner loop. Obviously, with bash nothing is really "internal". I think that you should be able to use autoPachelf for the same goal. Let me have a second look at it.

**Comment by felschr** [comment]
`breitbandmessung` is part of nixpkgs, but it also seems to be the only package in here that uses `autoPatchelfFile`:
https://github.com/NixOS/nixpkgs/blob/ce8cbe3c01fd8ee2de526ccd84bbf9b82397a510/pkgs/applications/networking/breitbandmessung/default.nix#L104

**Comment by layus** [comment]
Oh, I see. Do you happen to know why one would want to patch only that file, and specifically not the others ?

**Comment by felschr** [comment]
I'm not entirely sure, but I just replaced `autoPatchelfFile` with `autoPatchelf` without any other changes, and it still seems to build (in an older nixpkgs version before that python rewrite).

On the latest nixpkgs master, I can get the build working with:
```patch
- autoPatchelfFile $out/opt/Breitbandmessung/breitbandmessung
+ autoPatchelf $out/opt/Breitbandmessung
```

Now the GUI shows a curious error, though:
> Da ist etwas schiefgelaufen...
> Ihr Betriebssystem wird von dieser Anwendung nicht unterstützt

which roughly translates to:
> Something went wrong...
> Your operating system isn't supported by this application.

I get the same error when I try to run `breitbandmessung` from an older nixpkgs state that still has `autoPatchelfFile`, though.
So, it doesn't seem related to the patchelf change.

**Comment by felschr** [comment]
The runtime error is probably related to:
https://github.com/NixOS/nixpkgs/blob/e8ed7bf5202d9117a06f8f85844cc3b3c260fc78/pkgs/applications/networking/breitbandmessung/default.nix#L37-L48

https://github.com/NixOS/nixpkgs/blob/e8ed7bf5202d9117a06f8f85844cc3b3c260fc78/pkgs/applications/networking/breitbandmessung/default.nix#L106-L107

Perhaps @B4dM4n has some insight as to why this stopped working.

**Comment by layus** [comment]
Yes, indeed. The error happens because for some reason the other files should not be modified, only that one. And that is not feasible with my rewrite. Please have a look at my patch in https://github.com/NixOS/nixpkgs/pull/166118, to test if it works for you. I think it is a reasonable way forward without having to re-introduce autoPatchelfFile.
