### ISSUE TITLE
Black screen after opening the lid when VirtualBox is installed

### ISSUE THREAD

**Issue by martijnvermaat** [NixOS/nixpkgs#16609]
## Issue description

When I enable `virtualisation.virtualbox.host.enable = true;` the screen stays black after closing and opening the lid. I haven't found any key combinations that seem to have any effect.

Rebuilding without VirtualBox and rebooting solves the issue.

This is on a Lenovo ThinkPad Carbon X1 (4th gen, Skylake) and I'm using Gnome 3.

## Technical details

* System: `16.03.948.a96c308 (Emu)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `16.03.948.a96c308`

**Comment by martijnvermaat** [comment]
Might be related to #15005 (which also links my [lsmod with and without VirtualBox and lspci](https://github.com/NixOS/nixpkgs/issues/15005#issuecomment-223385754)).

**Comment by martijnvermaat** [comment]
Also, on closing the lid (with VirtualBox enabled), the red thinkpad led on the back doesn't go into the expected slow pulsing mode and I head the fans don't stop. This indicates that the system isn't acutally suspending on closing the lid.

I have actually at least once found my machine closed and in a sleeve with a noisy fan and feeling pretty hot. This could be a bit dangerous, although I'm hoping the BIOS would have some functionality in place to auto poweroff if it gets too hot.

@zimbatm can you confirm this? Might be Gnome 3 specific though...

**Comment by zimbatm** [comment]
I am getting the same behaviour on my XPS13 when closing the lid but it doesn't depend on virtualbox being installed. Some times the computer just goes in frenzy mode and heats like crazy.

My bet is that if you look at the journal you will find some kernel backtraces in there.

**Comment by martijnvermaat** [comment]
This is fixed for me in the 16.09 channel. Might be the same as what fixed #15005
