### ISSUE TITLE
fish: NixOS module is broken because of /share/fish/vendor_completions.d

### ISSUE THREAD

**Issue by solson** [NixOS/nixpkgs#16614]
## Issue description

The fish NixOS module, enabled by `programs.fish.enable = true;` is broken for me on the nixos-unstable channel. I first commented over on the PR which I believe caused this: https://github.com/NixOS/nixpkgs/pull/14526#discussion_r69010724.

### Steps to reproduce

When I `sudo nixos-rebuild switch` I get this:

```
cannot create directory `/nix/store/m3rrr54qspwiwyzn4gjrys36km6jz1g6-system-path//share/fish/vendor_completions.d': No such file or directory at /nix/store/xz5k60frmvvrj16lf7b0d8h3p0l4l7xw-builder.pl line 186.
builder for ‘/nix/store/bm5q3hs3pnijrjx1yrr647pslmzl986g-system-path.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/z8bwgpzs4wiiv72rm4anc4mx1ixph1w2-nixos-system-conway-16.09pre85931.125ffff.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/z8bwgpzs4wiiv72rm4anc4mx1ixph1w2-nixos-system-conway-16.09pre85931.125ffff.drv’ failed
```

There is a broken-looking path in there with a double slash: `/nix/store/m3rrr54qspwiwyzn4gjrys36km6jz1g6-system-path//share/fish/vendor_completions.d`.

I later realized this error only occurs if you have _no_ packages with `/share/fish/vendor_completions.d`. So, technically, I can work around this error by adding `docker` to `environment.systemPackages`. This also means that to reproduce you must remove any packages with that path.

## Technical details

* System: NixOS 16.09pre85931.125ffff (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre85931.125ffff

**Comment by Profpatsch** [comment]
That doesn’t seem to be the fault of the fish module, as this minimal system shows, which builds just fine:

    nix-build -E '(import <nixpkgs/nixos> { configuration = { programs.fish.enable = true; }; }).vm'

What is the last commit where it still works? Has it worked at all in the past?

**Comment by solson** [comment]
@Profpatsch Ah, nice example. Sorry for jumping to conclusions.

I minimized my error-inducing config and ended up with this, which you should be able to reproduce the problem with:

```sh
nix-build -E '(import <nixpkgs/nixos> { configuration = { programs.fish.enable = true;  services.xserver = { enable = true; desktopManager.kde5.enable = true; }; }; }).vm'
```

I'm not sure yet what part of KDE5 triggers the problem.

**Comment by rasendubi** [comment]
FYI: I have the same issue and I don't have kde5 enabled.

**Comment by Profpatsch** [comment]
@rasendubi can you create an invocation like the ones above?

**Comment by rasendubi** [comment]
I've tried to do that yesterday but failed. I'll be busy during the week but will try again next weekend. 

FWIW, my full config is available at [github](https://github.com/rasendubi/dotfiles/blob/master/nixos/configuration.nix) -- adding `programs.enable.fish = true;` breaks it for me.

**Comment by dezgeg** [comment]
The problem seems `environment.pathsToLink = [ "/share" ];` which is enabled by e.g. KDE and some others:

````
nix-build -E '(import <nixpkgs/nixos> { configuration = { programs.fish.enable = true; environment.pathsToLink = ["/share"]; }; }).vm'
````

**Comment by rasendubi** [comment]
I confirm I have this in my config, too.

**Comment by rasendubi** [comment]
Found and fixed the issue. See https://github.com/NixOS/nixpkgs/pull/16821.

**Comment by solson** [comment]
So I think this was ultimately fixed by https://github.com/NixOS/nixpkgs/pull/16828? I'll check it out later when I have access to NixOS.
