### ISSUE TITLE
breitbandmessung runtime error due to unsupported OS

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#166132]
### Describe the bug
Running `breitbandmessung` results in the following error message showing up:
> Da ist etwas schiefgelaufen...
> Ihr Betriebssystem wird von dieser Anwendung nicht unterstützt

which roughly translates to:
> Something went wrong...
> Your operating system isn't supported by this application.

### Steps To Reproduce
Run `breitbandmessung`, e.g. via `nix run "nixpkgs#breitbandmessung"`.

### Expected behavior
App should run without causing error that prevents usage.

### Additional context
See previous issue #166086 & #166118.

The runtime error is probably related to:
https://github.com/NixOS/nixpkgs/blob/e8ed7bf5202d9117a06f8f85844cc3b3c260fc78/pkgs/applications/networking/breitbandmessung/default.nix#L37-L48

https://github.com/NixOS/nixpkgs/blob/e8ed7bf5202d9117a06f8f85844cc3b3c260fc78/pkgs/applications/networking/breitbandmessung/default.nix#L106-L107

### Notify maintainers
@B4dM4n

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0, NixOS, 22.05 (Quokka), 22.05.20220323.1d08ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - nixpkgs: `/nix/store/hsff9pi1qinxljahr833z0xivr1apx27-source`
```

**Comment by B4dM4n** [comment]
I'm sorry for the delay, but I did't have much free time lately.

I could bisect the issue back to bae181d3f0f453d9a23cf5e899c2cb0f96e91fef, which adds the `/etc/lsb-release` file to NixOS. Digging into the node module used to handle the OS detection (`bizzby-lsb-release`) reveals that in fact this file is preferred over the `lsb_release` binary, which renders the fake data workaround ineffective.

I will open a PR soon to fix this.
