### ISSUE TITLE
KDE: Optionally unlock kwallet on login

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#16616]
## Issue description

It's possible to automatically unlock kwallet when logging in. 
https://wiki.archlinux.org/index.php/KDE_Wallet#Unlock_KDE_Wallet_automatically_on_login

I add it here since it's on my to do list.

**Comment by FRidh** [comment]
Discussion on common PAM settings https://github.com/NixOS/nixpkgs/issues/17044

**Comment by mkroehnert** [comment]
With the latest Nixos 17.03 unstable the wallet seems to get unlocked automatically.
Does it mean that this issue has been resolved?
