### ISSUE TITLE
ghc 8.0.1 is actually ghc 8.0.0 in nixos-16.03

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#16629]
```
> nix-shell -p haskell.compiler.ghc801 --run 'ghc --version'
The Glorious Glasgow Haskell Compilation System, version 8.0.0.20160204
```

This is a mistake, right?

**Comment by domenkozar** [comment]
On master:

```
$ $(nix-build -A ghc)/bin/ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
```

**Comment by chris-martin** [comment]
Yeah, it's correct on master, just not in 16.03.

**Comment by domenkozar** [comment]
cc @peti

**Comment by peti** [comment]
I've cherry-picked eb4cfc5, c0fc272, e2c04f2, d615935, and 66b0b28 into the release branch. Hopefully that is going to work correctly.

**Comment by peti** [comment]
I've cherry-picked eb4cfc5, c0fc272, e2c04f2, d615935, and 66b0b28 into the release branch. Hopefully that is going to work correctly.
