### ISSUE TITLE
protobuf==3.0.0b2 not found trying to install tensorflow

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#16624]
## Issue description
I tried to install tensorflow in nix-shell and got this error:
```
nix-shell -p python27 -p python27Packages.tensorflow
these derivations will be built:
  /nix/store/qmzalq1vgvkmgspp6vklm1mlad54zrnx-python2.7-tensorflow.drv
building path(s) /nix/store/2x4vm7p75c9ii1ilx7pkmscwb2585k4s-python2.7-tensorflow
...
Collecting protobuf==3.0.0b2 (from tensorflow==0.8.0)
  Could not find a version that satisfies the requirement protobuf==3.0.0b2 (from tensorflow==0.8.0) (from versions: )
No matching distribution found for protobuf==3.0.0b2 (from tensorflow==0.8.0)
builder for /nix/store/qmzalq1vgvkmgspp6vklm1mlad54zrnx-python2.7-tensorflow.drv failed with exit code 1
error: build of /nix/store/qmzalq1vgvkmgspp6vklm1mlad54zrnx-python2.7-tensorflow.drv failed
```

I am using nixos-unstable channel.

### Steps to reproduce
nix-shell -p python27 -p python27Packages.tensorflow

## Technical details

* System: 
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.7 (Santiago)
Release:        6.7
Codename:       Santiago
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre85931.125ffff

**Comment by FRidh** [comment]
cc maintainer @anderspapitto

**Comment by teh** [comment]
@alexvorobiev - is this still an issue or can this be closed?

**Comment by alexvorobiev** [comment]
@teh - confirming that tensorflow works in unstable.
