### ISSUE TITLE
File roller can't unzip rar files correctly

### ISSUE THREAD

**Issue by linsui** [NixOS/nixpkgs#166241]
### Describe the bug
File roller can't unzip rar files correctly. The extracted files are very large (more that 900M with a 12K file). I also reported upstream but the developer can't reproduce this problem. See https://gitlab.gnome.org/GNOME/file-roller/-/issues/153

### Steps To Reproduce
1. Open an rar file created by winrar. 
2. ...
3. ...

### Expected behavior
The file should be extracked correctly. Since bsdtar works well there are some problems in file roller..

### Additional context
A test file. 
[This is a test file.zip](https://github.com/NixOS/nixpkgs/files/8371508/This.is.a.test.file.zip)

### Notify maintainers

@NixOS/gnome 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.26-hardened1, NixOS, 22.05 (Quokka), 22.05pre364329.ce8cbe3c01f`
```

**Comment by QuantMint** [comment]
I can't reproduce this

**Comment by jtojnar** [comment]
Is it a rar or zip?

Also file-roller might have use a different backend depending on what programs are installed.

**Comment by linsui** [comment]
It's an rar file but I can't upload it directly.

> Also file-roller might have use a different backend depending on what programs are installed (that’s why we are [adding unzip to its PATH](https://github.com/NixOS/nixpkgs/commit/b209b81d7aeea27db4ee94a7588f4a153e74c949)).

I'll test with a new vm. Maybe there is something strange in my install.

**Comment by linsui** [comment]
I just tested on https://releases.nixos.org/nixos/unstable/nixos-22.05pre364329.ce8cbe3c01f/nixos-gnome-22.05pre364329.ce8cbe3c01f-x86_64-linux.iso in gnome boxes. The result is a little different that the extracted file is 35M. But it's still broken since the origin file is 12k. And every time the result is pretty different.

**Comment by weihua-lu** [comment]
I also had issue with file roller unzip multipart rar today.

When I open the first part of multipart rar(3 files, 4gb each, extract total should be around 15gb) files from Nautilus, click extract and the result file only size around 5 gb. It seems file-roller stop at just finishing rar part1. And file roller still tells me extract successfully.

When I manually start file-roller from terminal with that file's first part, eg `$:file-roller xxx.part1.rar`, then click Extract, it actually works and extracts the file to its full size(15Gb) correctly.

Just bare minimum gnome with `programs.file-roller.enable = true; environment.systemPackages = pkgs.gnome.nautilus;` 

Not sure what goes wrong here.

**Comment by jtojnar** [comment]
@weihua-lu That is a known issue, unrelated to File-Roller: https://gitlab.gnome.org/GNOME/gnome-autoar/-/issues/30

**Comment by linsui** [comment]
Looks like it's fixed! Thanks! Just curious why bsdtar is not affected.

**Comment by jtojnar** [comment]
Iibarchive has two different functions for getting data out of archive and only one of them contained the bug.
