### ISSUE TITLE
Allow unfree packages with `nix shell`

### ISSUE THREAD

**Issue by GuillaumeDesforges** [NixOS/nixpkgs#166220]
## Issue description

Currently, it's not possible to use unfree packages with `nix shell`

e.g.

```
nix shell nixpkgs#python3Packages.cupy
```

a current workaround is to use `--impure`, but one can want both unfree and not impure.

### Possible fix

My guess is that the `legacyPackages` is loaded with inherited `system`.

https://github.com/NixOS/nixpkgs/blob/c618329a61cd39c2b1d34bdd6e5d7127b1d14e3a/flake.nix#L43

There is no way to provide an argument to flakes (see https://github.com/NixOS/nix/issues/3843#issuecomment-661710951) and pass it to the instanciation, and most likely won't ever be.

Therefore, a suggestion would be to add

```nix
legacyPackages.withUnfree = forAllSystems (system: import ./. { inherit system; config.allowUnfree = true; });
```

The downside is that we get all packages twice, e.g. in commands such as `nix search`.

### Note

We could think of being able to pass an argument such as `--allow-unfree` to the Nix command, but in my opinion it is too focused on nixpkgs and most likely to be rejected.

**Comment by con-f-use** [comment]
So is there a solution or workaround for this? I'd like have a devShell with unfree backages.

**Comment by GuillaumeDesforges** [comment]
For now a workaround is to use

```
$ NIXPKGS_ALLOW_UNFREE=1 nix shell --impure nixpkgs#yourpackage
```

**Comment by con-f-use** [comment]
Norber (NobbZ) suggest the following, which seems to work well:
```nix
inputs = {
  nixunstable.url = "github:NixOS/nixpkgs/nixos-unstable";
};

outputs = { nixunstable }: {
  devShells.x86_64-linux.default = let
      pkgs = import nixunstable { system = "x86_64-linux"; config.allowUnfree = true; };
  in pkgs.callPackage ./myshelll.nix {};
};
```

**Comment by Artturin** [comment]
the error message already contains

```
a) To temporarily allow unfree packages, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNFREE=1

 Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
 (Flake) command, `--impure` must be passed in order to read this
 environment variable.
 ```

**Comment by guissalustiano** [comment]
You also could add in nxpkg import
```
{ pkgs ? (import <nixpkgs> { 
    config.allowUnfree = true;
    config.segger-jlink.acceptLicense = true; 
}), ... }:
pkgs.mkShell {
  packages = with pkgs; [
    nrfconnect
  ];
}
```
