### ISSUE TITLE
option description mentions mautrix-telegram instead of mautrix-facebook

### ISSUE THREAD

**Issue by f0x52** [NixOS/nixpkgs#166312]
When copying this to make a mautrix-twitter module, I realised that this line mentions mautrix-telegram instead of mautrix-facebook..

https://github.com/NixOS/nixpkgs/blob/ce8cbe3c01fd8ee2de526ccd84bbf9b82397a510/nixos/modules/services/misc/mautrix-facebook.nix#L95

Also since all these bridges use basically/exactly? the same module anyways, maybe they could be combined somehow?

**Comment by Luflosi** [comment]
Regarding the suggestion to combine the the many bridges somehow, there is #114419, which aims to do exactly that.
