### ISSUE TITLE
cudnn fails to download

### ISSUE THREAD

**Issue by freemagma** [NixOS/nixpkgs#166444]
When I try something like `nix-shell -p cudnn` or even a more specific version like `nix-shell -p cudnn_8_3_cudatoolkit_11`, I find that the download fails. I can't tell if the URL is wrong/changed, or maybe its just temporarily down.

The error messages all look like this:
```
error: cannot download cudnn-11.2-linux-x64-v8.1.1.33.tgz from any mirror
error: builder for '/nix/store/kz9jvvl0v690rcydwql455008i7br2jr-cudnn-11.2-linux-x64-v8.1.1.33.tgz.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://developer.download.nvidia.com/compute/redist/cudnn/v8.1.1/cudnn-11.2-linux-x64-v8.1.1.33.tgz
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0   445    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download cudnn-11.2-linux-x64-v8.1.1.33.tgz from any mirror
       For full logs, run 'nix log /nix/store/kz9jvvl0v690rcydwql455008i7br2jr-cudnn-11.2-linux-x64-v8.1.1.33.tgz.drv'.
error: 1 dependencies of derivation '/nix/store/p1vzd1iyaih9qs0scsxxs3yag0ivba01-cudatoolkit-11.0-cudnn-8.1.1.drv' failed to build
```

**Comment by witchof0x20** [comment]
Tried downloading CUDNN via the normal route (their developer page) and it also 404'd. Seems to be a problem on nvidia's side

**Comment by samuela** [comment]
yeah @NixOS/cuda-maintainers is aware of it. it appears to be very recent but no clear resolution yet... I'm not sure if this was intentional on NVIDIA's part or just an accident

**Comment by samuela** [comment]
seems to be good news that their official developer download page is also 404ing

**Comment by SomeoneSerge** [comment]
The `.../redist/cudnn/v${ver}` URLs work again, it must've been a temporary outage on NVIDIA's part.
But this only demonstrates that in terms of reliability, cudnn _needs_ to be cached, no matter how confusing the license is

**Comment by SomeoneSerge** [comment]
The way we rely on NVIDIA's CDN is a pity, but a separate issue. I'll close this, so that back-references don't display this issue in "green"
