### ISSUE TITLE
Cannot delete path ... since it is still alive. To find out why, use: nix-store --query --roots, but nix-store --query --roots shows nothing

### ISSUE THREAD

**Issue by a-m-joseph** [NixOS/nixpkgs#166477]
### Describe the bug

Recently, I needed to forcibly rebuild a derivation output.  I attempted to delete the old output:

```
$ nix-store --delete /nix/store/i9qmw2r3d78lma985g7qzipdmqv8jd5d-stdenv-bootstrap-tools-mips64el-linux-gnuabi64
finding garbage collector roots...
0 store paths deleted, 0.00 MiB freed
error: Cannot delete path '/nix/store/i9qmw2r3d78lma985g7qzipdmqv8jd5d-stdenv-bootstrap-tools-mips64el-linux-gnuabi64' since it is still alive. To find out why, use: nix-store --query --roots
```

After following `nix-store`'s advice, I got:

```
$ nix-store --query --roots /nix/store/i9qmw2r3d78lma985g7qzipdmqv8jd5d-stdenv-bootstrap-tools-mips64el-linux-gnuabi64
$
```

### Steps To Reproduce

This has happened to me a couple of times, but I don't know how to reproduce it, short of shipping you a complete tarball of my `/nix/store` (and possibly other parts of my system as well).

### Expected behavior

Either `/nix/store/i9qmw2r3d78lma985g7qzipdmqv8jd5d-stdenv-bootstrap-tools-mips64el-linux-gnuabi64` gets deleted, or `nix-store --query --roots` shows me something that references it, or else the tools print additional instructions for the user.

### Screenshots

See above.

### Additional context

I do feel like I might be abusing the issue tracker here to get technical support.  If so, I will make amends by submitting a PR to improve the documentation and/or error messages printed by `nix-store`.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.10+, Debian GNU/Linux, 10 (buster)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - nixpkgs: `/nix/nixpkgs`

```

**Comment by Artturin** [comment]
https://github.com/NixOS/nix/issues/6141

**Comment by a-m-joseph** [comment]
Ok!  At least I'm in good company :)
