### ISSUE TITLE
python3Packages.pytorchWithCuda: uses unsupported cudatoolkit 10.1

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#166403]
### Describe the bug

Since pytorch 1.10, `pytorchWithCuda` requires cuda `>= 10.2`.
Currently, `cudatooklit = cudatoolkit_10 = cudatooklit_10_1`.

Build log: [/nix/store/mdz5mgadv4bg86533g4s9i2diixrxl2z-python3.9-pytorch-1.10.2.drv](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Fmdz5mgadv4bg86533g4s9i2diixrxl2z-python3.9-pytorch-1.10.2.drv?via-job=f5fc6166-1af1-4d2f-ae08-ad09efb62b6b)

### Steps To Reproduce

```nix
with (import ./. {
  config.allowUnfree = true;
  config.cudaSupport = true;
});

mkShell {
  buildInputs = [
    python3Packages.pytorch
  ];
}
```
### Expected behavior
Pytorch builds

### Additional context

```
CMake Error at cmake/public/cuda.cmake:42 (message):
  PyTorch requires CUDA 10.2 or above.
```

### Notify maintainers

- [cuda-maintainers](https://github.com/orgs/NixOS/teams/cuda-maintainers)
- @teh
- @thoughtpolice 
- @tscholak

**Comment by freemagma** [comment]
Does anyone know of a temporary workaround to this?

**Comment by SomeoneSerge** [comment]
Has been fixed in https://github.com/NixOS/nixpkgs/commit/7a01e9096e94c924374eff58ace157ba2bcbc55d
Hasn't reached nixpkgs-unstable yet

**Comment by samuela** [comment]
cc @NixOS/cuda-maintainers

**Comment by SomeoneSerge** [comment]
[Fixed](https://hercules-ci.com/github/SomeoneSerge/nixpkgs-unfree/jobs/155) in https://github.com/NixOS/nixpkgs/pull/166784
