### ISSUE TITLE
Gnome Screen Autorotate not working after a recent upgrade

### ISSUE THREAD

**Issue by astrojhgu** [NixOS/nixpkgs#166438]
### Describe the bug
Gnome Screen Autorotate not work.
by using `journalctl -f`, some error message can be seen (see below)

### Steps To Reproduce
1. Install and enable `nixos.gnomeExtensions.screen-autorotate`
2. rotate laptop in real world
3. The screen does not rotate accordingly.

### Expected behavior

The screen should be auto rotated according to the orientation of the laptop in the real world.

### Screenshots
Following is a piece of message related, shown by `journalctl -f`
```
Mar 31 00:29:42 x1yoga .gnome-shell-wr[1753]: Rotate screen to left-up
Mar 31 00:29:42 x1yoga gjs[126321]: cannot register existing type 'GCancellable'
Mar 31 00:29:42 x1yoga gjs[126321]: cannot add private field to invalid (non-instantiatable) type '<invalid>'
Mar 31 00:29:42 x1yoga gjs[126321]: g_once_init_leave: assertion 'result != 0' failed
Mar 31 00:29:44 x1yoga .gnome-shell-wr[1753]: Rotate screen to normal
Mar 31 00:29:44 x1yoga gjs[126335]: cannot register existing type 'GCancellable'
Mar 31 00:29:44 x1yoga gjs[126335]: cannot add private field to invalid (non-instantiatable) type '<invalid>'
Mar 31 00:29:44 x1yoga gjs[126335]: g_once_init_leave: assertion 'result != 0' failed
Mar 31 00:29:46 x1yoga .gnome-shell-wr[1753]: Rotate screen to right-up
Mar 31 00:29:46 x1yoga gjs[126349]: cannot register existing type 'GCancellable'
Mar 31 00:29:46 x1yoga gjs[126349]: cannot add private field to invalid (non-instantiatable) type '<invalid>'
Mar 31 00:29:46 x1yoga gjs[126349]: g_once_init_leave: assertion 'result != 0' failed
Mar 31 00:29:48 x1yoga .gnome-shell-wr[1753]: Rotate screen to normal
Mar 31 00:29:48 x1yoga gjs[126362]: cannot register existing type 'GCancellable'
Mar 31 00:29:48 x1yoga gjs[126362]: cannot add private field to invalid (non-instantiatable) type '<invalid>'
Mar 31 00:29:48 x1yoga gjs[126362]: g_once_init_leave: assertion 'result != 0' failed
```

### Additional context

This abnormal condition happens since the latest upgrade.

### Notify maintainers

@piegamesde 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.29, NixOS, 22.05 (Quokka), 22.05pre364329.ce8cbe3c01f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by piegamesde** [comment]
#165840 I am confused.

**Comment by astrojhgu** [comment]
> #165840 I am confused.

Yes, your previous patch does make it work, however after a recent upgrade, the above error appears and the screen no longer rotates automatically.

After reboot my laptop, I have some updates:
In the gnome extension setting dialog, it says the screen autorotate is incompatible to current version of gnome.

**Comment by piegamesde** [comment]
I see. You effectively upgraded to GNOME 42, and the extension does not support it yet. Therefore, I think this is an upstream issue: https://github.com/kosmospredanie/gnome-shell-extension-screen-autorotate/issues/7

**Comment by astrojhgu** [comment]
> I see. You effectively upgraded to GNOME 42, and the extension does not support it yet. Therefore, I think this is an upstream issue: [kosmospredanie/gnome-shell-extension-screen-autorotate#7](https://github.com/kosmospredanie/gnome-shell-extension-screen-autorotate/issues/7)

Thanks, I realized that the current latest screen-autorotate does not yet support gnome 42.

**Comment by maxeaubrey** [comment]
If the extension ever gets a release supporting 43+, please open an issue requesting an update. `screen-rotate` exists as an alternative for GNOME 42 users.
