### ISSUE TITLE
Cross compiling v4l-utils for aarch64 fails

### ISSUE THREAD

**Issue by cyber-murmel** [NixOS/nixpkgs#166416]
### Describe the bug
Cross compiling v4l-utils for aarch64 fails with
```
error: attribute 'runtimeShell' missing, at /nix/store/pzl7yl8kf47lqnnqns8mzr22a3m8w7b8-ce8cbe3.tar.gz/pkgs/top-level/all-packages.nix:745:17
```

### Steps To Reproduce
```shell
$ nix-build https://github.com/NixOS/nixpkgs/archive/ce8cbe3.tar.gz \ # nixos-unstable Wed, 30 Mar 2022 12:48:45 +0000
    -A pkgsCross.aarch64-multiplatform.v4l-utils
```

### Expected behavior
I expect a `result` symlink to v4l-utils.

### Screenshots
Cross compilation on an x86 computer:
![image](https://user-images.githubusercontent.com/30078229/160838535-c9514c92-0e6e-452c-aacb-f4a581a17b09.png)

Native build on aarch64 machine:
![image](https://user-images.githubusercontent.com/30078229/160838692-07be88e0-fbfe-4fe3-b9c0-b5e872e2e9f5.png)

### Notify maintainers
@pSub

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.106, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(marble): `"nixos-unstable-22.05pre356180.d5f23787297"`
 - channels(root): `"nixos-21.11.336673.d89f18a17e5"`
 - channels(work): `"nixos-unstable-21.11pre328987.c935f5e0add"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.29, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(nixos): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cyber-murmel** [comment]
Using `v4l-utils.override{withGUI = false;}` works in my project.

**Comment by Mindavi** [comment]
This is due to the wrapQtAppsHook. I'm not really sure where exactly it's going wrong, but I have seen this issue in more places. It might be good to create a more generic issue about this at some point.

**Comment by Artturin** [comment]
there's no eval failure now
