### ISSUE TITLE
Upgrading to nixos-16.03-small shows these errors at stage 1 booting

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#16644]
## Issue description

```
killall: cryptsetup: no process killed
```

It's shown 7 times.
### Steps to reproduce

I'm using LUKS of course.
## Technical details
- System: 16.03.git.72a31bd (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: Custom git repo tracking nixos-16.03-small.

**Comment by pSub** [comment]
Were you able to update? If not does a update to 16.09-small succeeds?
