### ISSUE TITLE
Feedback regarding igraph package

### ISSUE THREAD

**Issue by szhorvat** [NixOS/nixpkgs#166573]
This is not a bug report, merely some hopefully useful feedback regarding how igraph is packaged in Nix:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/igraph/default.nix

It seems that you are simply grabbing a certain commit from GitHub. The recommended way is to use the release tarballs instead (unless you are working with a dev version). For example, for 0.9.7, the release tarball is here:

https://github.com/igraph/igraph/releases/download/0.9.7/igraph-0.9.7.tar.gz

This is not exactly the same as the snapshot of the v0.9.7 tag at https://github.com/igraph/igraph/archive/refs/tags/0.9.7.tar.gz

Specifically, the release tarball:

 - Contains pre-built documentation, making it unnecessary to build the documentation locally (it's slow), and eliminating multiple build dependencies (`fop`, `libxslt`, `python3`, `sourceHighlight`, `xmlto`).
 - Contains the parser sources, eliminating the need for `bison` and `flex` as well.
 - Comes "ready to build", making the hack on this line unnecessary: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/igraph/default.nix#L38 Normally, igraph is expected to be built either from an actual git repo (not merely a snapshot of its contents) or the release tarball.

Of course, if you are already aware of this, and are building from a specific commit on purpose, feel free to keep it that way. However, please do make sure that the version written to `IGRAPH_VERSION` is correct. For example, if you set it to a later commit that doesn't match any release tag, this should be indicated in the version by adding a part following a `-` sign. E.g., the version generated for given commits now looks like this: `0.10.0-dev+aba150fb`.

[This comment](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/igraph/default.nix#L33) is outdated as the build system is no longer autotools and there is no `tools/getversion.sh`. The `IGRAPH_VERSION` file is read with CMake.

After [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/igraph/default.nix#L77) you may want to add `IGRAPH_USE_INTERNAL_PLFIT=ON`. Since igraph 0.9.6, it is possible to use an external plfit, however, Nix does not currently contain this package.

You may want to make an explicit decision about whether to build with OpenMP and set `IGRAPH_OPENMP_SUPPORT` accordingly. The default is `AUTO` as the clang that comes with Xcode does not support OpenMP.

CC @MostAwesomeDude @dotlambda

**Comment by dotlambda** [comment]
Thank you very much for the feedback!

> It seems that you are simply grabbing a certain commit from GitHub. The recommended way is to use the release tarballs instead

I actually prefer building docs and parsers from source for e.g. supply chain security reasons.
Since we supply all build-time dependencies, there should be no real difference between our compiled binary and one compiled from a release tarball. Or do you see a problem?

> making it unnecessary to build the documentation locally (it's slow)
I don't mind the longer build time since we have a binary cache.

> However, please do make sure that the version written to IGRAPH_VERSION is correct.
This shouldn't be a problem since we set the variable to exactly what the tag is called.



> After [this line](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/igraph/default.nix#L77) you may want to add `IGRAPH_USE_INTERNAL_PLFIT=ON`. Since igraph 0.9.6, it is possible to use an external plfit, however, Nix does not currently contain this package.

I'll add plfit to Nixpkgs in the coming days.



> You may want to make an explicit decision about whether to build with OpenMP and set `IGRAPH_OPENMP_SUPPORT` accordingly. The default is `AUTO` as the clang that comes with Xcode does not support OpenMP.

Seems like we don't have an optimal solution for that yet: https://github.com/NixOS/nixpkgs/issues/79818
I'll unconditionally enable OpenMP anyway.

**Comment by dotlambda** [comment]
> Note that Apple's compiler doesn't support it.

Afaik we use our own clang, even on macOS.
I assume there would be a compilation error if I enabled `IGRAPH_OPENMP_SUPPORT` despite it not being supported?

**Comment by szhorvat** [comment]
Yes. `OFF` means disabled, no risk of error. `AUTO` means enabled if available, no risk of error. `ON` means enabled unconditionally, error if unsupported.

**Comment by MostAwesomeDude** [comment]
I have no strong feelings about any of this. I agree that building docs is not that big of an issue. I suppose that OpenMP is important, but I don't have any data about it.
