### ISSUE TITLE
Hydra Migration

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#166572]
## Issue description

Hydra.nixos.org will be down temporarily while it is migrated to a new host. I'll post updates periodically.

**Comment by grahamc** [comment]
I stoped ceres's hydra jobs. DNS is pointing to rhea, the GC roots and config data is copied and deployed. I'm about to bring up hydra on rhea.

**Comment by grahamc** [comment]
The webserver is up, evaluations appear to be proceeding normally. Working on the queue runner, which involves a new SSH key.

**Comment by grahamc** [comment]
Look like we're good.

Ceres' graph: https://monitoring.nixos.org/grafana/d/rYdddlPWk/node-exporter-full?orgId=1&var-DS_PROMETHEUS=default&var-job=node&var-node=ceres:9100&var-diskdevices=%5Ba-z%5D%2B%7Cnvme%5B0-9%5D%2Bn%5B0-9%5D%2B&from=1648145030302&to=1648739713629

**Comment by hello-smile6** [comment]
Why unpin this?

**Comment by cole-h** [comment]
Because the migration has finished and Hydra has been happily chugging along since it was closed :)

**Comment by hello-smile6** [comment]
> Because the migration has finished and Hydra has been happily chugging along since it was closed :)

Oh. I wonder what that's like, having a working server...
