### ISSUE TITLE
llvmPackages_{15,16,17}.lldb: broken, "ModuleNotFoundError: No module named 'lldb'"

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#166604]
### Describe the bug

`lldb` from `llvmPackages_14.lldb` seems to be broken, reporting:

```console
$ lldb --version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
lldb version 14.0.0
```

This error is present in all invocations of `lldb` I've tried: with no arguments, pointed at an executable, and debugging a coredump (`SYSTEMD_DEBUGGER=lldb` for `coredumpctl debug`(/gdb), FWIW).

Coredump usage is worse, with something like:

```
$ coredump debug
...<<snip>>...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
(lldb) target create "<<redacted>>" --core "/var/tmp/coredump-VXmhXt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined

Core file '/var/tmp/coredump-VXmhXt' (x86_64) was loaded.
(lldb)
```

### Steps To Reproduce
1. `lldb --version` or other `lldb` invocations, until this is fixed this works: `nix run nixpkgs#llvmPackages_14.lldb -- --version`.
2. Note the messages as described above

### Expected behavior

LLDB doesn't show this error, and presumably whatever functionality triggering this isn't working properly but I haven't tried using it after the error(s) are printed.

### Additional context

Another LLVM14 package to fix before this is ready for use:

cc https://github.com/NixOS/nixpkgs/pull/165701

### Notify maintainers

@lovek323 @7c6f434c @dtzWill @primeos 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0, NixOS, 22.05 (Quokka), 22.05pre364898.00e27c78d3d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220330_2252272`
 - channels(will): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dtzWill** [comment]
Hmm, seems the packaging of the python bits is broken.

We expect python bits to all be in the "lib" output.  We [wrap lldb to find its python bits in `.lib`](https://github.com/NixOS/nixpkgs/blob/366a59cdc312601b1d711a066e858bbf49bb9885/pkgs/development/compilers/llvm/14/lldb/default.nix#L100) and even [check for presence of some python files in that output during installCheckPhase](https://github.com/NixOS/nixpkgs/blob/366a59cdc312601b1d711a066e858bbf49bb9885/pkgs/development/compilers/llvm/14/lldb/default.nix#L94).

However, all the python bits end up in the primary output, which is probably why this is broken.  Hmm.

**Comment by dtzWill** [comment]
Also, the file we check for is `_lldb.so` which is no longer installed.  See ae389b2450bd604a3f3bbe5b09b333b2d99801dd .

The `gnu-install-dirs.patch` from LLVM13 has python bits which apply (with offsets), maybe they're still needed?

cc @Ericson2314 (thanks, sorry!).

**Comment by dtzWill** [comment]
WIP fix, discussed here: https://github.com/NixOS/nixpkgs/pull/166730#discussion_r840926824 .

**Comment by NickHu** [comment]
@dtzWill Any chance you could PR your WIP fix? Even if it's not perfect, it's better than the current state of LLDB 14 in nixpkgs.

**Comment by Ninja3047** [comment]
This still seems to be an issue for `lldb_15`

```
PYTHONPATH=${PYTHONPATH:+':'$PYTHONPATH':'}
PYTHONPATH=${PYTHONPATH/':''/nix/store/fdxcc2gx0hz56ik22yv4awjvhacgni5d-lldb-15.0.7-lib/lib/python3.10/site-packages/'':'/':'}
PYTHONPATH='/nix/store/fdxcc2gx0hz56ik22yv4awjvhacgni5d-lldb-15.0.7-lib/lib/python3.10/site-packages/'$PYTHONPATH
PYTHONPATH=${PYTHONPATH#':'}
PYTHONPATH=${PYTHONPATH%':'}
export PYTHONPATH
```

the wrapper sets the `PYTHONPATH` to `/nix/store/fdxcc2gx0hz56ik22yv4awjvhacgni5d-lldb-15.0.7-lib/lib/python3.10/site-packages/`

which does not actually exist

The path it it should be looking for is `/nix/store/fdxcc2gx0hz56ik22yv4awjvhacgni5d-lldb-15.0.7-lib/lib/python3.10/site-packages/`. This directory has the following content.
```
total 712
dr-xr-xr-x 5 root root   4096 Dec 31  1969 .
dr-xr-xr-x 3 root root   4096 Dec 31  1969 ..
-r--r--r-- 2 root root   4032 Dec 31  1969 embedded_interpreter.py
dr-xr-xr-x 3 root root   4096 Dec 31  1969 formatters
-r--r--r-- 2 root root 700563 Dec 31  1969 __init__.py
lrwxrwxrwx 3 root root     30 Dec 31  1969 lldb-argdumper -> ../../../../bin/lldb-argdumper
lrwxrwxrwx 6 root root     19 Dec 31  1969 _lldb.cpython-310-x86_64-linux-gnu.so -> ../../../liblldb.so
dr-xr-xr-x 2 root root   4096 Dec 31  1969 plugins
dr-xr-xr-x 2 root root   4096 Dec 31  1969 utils
```

The symlink for ` _lldb.cpython-310-x86_64-linux-gnu.so` is broken and points to `/nix/store/y6i9rrhcp4y64y1zwlisg0d6z7hz7z4z-lldb-15.0.7/lib/liblldb.so`. The correct file is located at `/nix/store/fdxcc2gx0hz56ik22yv4awjvhacgni5d-lldb-15.0.7-lib/lib/liblldb.so`.

There seems to be some kind of mixup between `/nix/store/fdxcc2gx0hz56ik22yv4awjvhacgni5d-lldb-15.0.7-lib` and `/nix/store/y6i9rrhcp4y64y1zwlisg0d6z7hz7z4z-lldb-15.0.7`.

**Comment by andrewrk** [comment]
Is there a workaround?

**Comment by schuelermine** [comment]
This seems to be fixed?
![image](https://github.com/NixOS/nixpkgs/assets/48802534/eb65224f-dd2c-435e-a634-c0609a180f8d)

**Comment by andrewrk** [comment]
Not fixed

```
andy@ark ~> nixos-version
23.05.3580.5d017a8822e0 (Stoat)
andy@ark ~> nix-shell -p lldb_16

[nix-shell:~]$ lldb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
(lldb) 
```

**Comment by schuelermine** [comment]
Hm, I’m getting an even more egregious error with 16. I think this issue is about 14 though, which doesn’t have this issue for me. (I’m using `nixos-unstable`)

```
~$ nixos-version
23.11.20230914.f2ea252 (Tapir)
~$ nix shell nixpkgs#lldb_16
~$ lldb
/nix/store/7ryjyq988rgag5rin91fa4v5807gyq61-lldb-16.0.6/bin/lldb: error while loading shared libraries: libclang-cpp.so.16: cannot open shared object file: No such file or directory
~ [127]$ 
```

**Comment by schuelermine** [comment]
15 has the module not found error, though, for me

**Comment by andrewrk** [comment]
what I really want is lldb 17
