### ISSUE TITLE
glib package directory needs to have dbus uuid

### ISSUE THREAD

**Issue by hello-smile6** [NixOS/nixpkgs#166741]
### Describe the bug
For some reason, many programs look for the dbus uuid in the glib package directory. However, it is never there.

### Steps To Reproduce
1. `nix-env -iA nixpkgs.pantheon`
2. `io.elementary.wingpanel`
3. Look at the command-line output.

### Expected behavior
I expected dbus to work without configuration.

### Screenshots
N/A

### Additional context
I have a NoVNC server running, feel free to use [the NoVNC server](https://vnc-gnome.9pfs.repl.co/vnc.html) to get more information. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
runner@7aede57d0f27:~/vnc-gnome$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-1021-gcp, Ubuntu, 20.04.2 LTS (Focal Fossa)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(runner): `"nixpkgs, nixpkgs-stable-21_11-21.11.tar.gz, nixpkgs-unstable"`
 - nixpkgs: `/home/runner/.nix-defexpr/channels/nixpkgs`
```

**Comment by iblech** [comment]
Just to add to this issue, the warning reads as follows:

```
(.io.elementary.wingpanel-wrapped_:270): wingpanel-WARNING **: 08:16:57.992: SessionManager.vala:60: Error registering client: Cannot spawn a message bus without a machine-id: Invalid machine ID in /nix/store/sxzai36pf2sk7dxwpk9hn1gqn94k4646-glib-2.70.2/var/lib/dbus/machine-id or /etc/machine-id
```

**Comment by Artturin** [comment]
Systemd nowadays should generate `/etc/machine-id` automatically.
This is still an issue on darwin https://github.com/NixOS/nixpkgs/issues/294640
