### ISSUE TITLE
Updating elmPackages

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#166816]
Hello! I'm wondering, how does one update `elmPackages`? I needed a newer `elm-language-server` and I just found that I'm walking knee-deep into some npm stuff and a simple override won't do it

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: elm-language-server

current version: 2.3.0
desired version: 2.4.1

###### Notify maintainers

maintainers: @turboMaCk 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by turboMaCk** [comment]
It's all automated. All you need to do is to run this shell script and open PR witch changes it makes https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/elm/update.sh

**Comment by turboMaCk** [comment]
Sorry I've meant this script https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/elm/packages/generate-node-packages.sh

**Comment by turboMaCk** [comment]
this PR updates elm-packages https://github.com/NixOS/nixpkgs/pull/166950
