### ISSUE TITLE
HomeAssistant module: NixOS is incompatible with Home Assistant

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#166821]
### Describe the bug

The line `solaredge = {};`

is a part of my configuration, and when I added it, I had to add it, because otherwise the integration would not be loaded. 

But with a recent Unstable version of Home Assistant, I get this in my logs: 

> The 'solaredge' option near /var/lib/hass/configuration.yaml:0 has been removed, please remove it from your configuration

So, how do I load the code for solaredge such that the integration continues to work, while not getting this message? 

### Notify maintainers

@jsimonetti

**Comment by jsimonetti** [comment]
See my answer in #166824.

**Comment by 21stce** [comment]
The solution suggested in https://github.com/NixOS/nixpkgs/issues/166824#issuecomment-1086119241 works.
