### ISSUE TITLE
Elasticsearch and Kibana 7 still on 7.11

### ISSUE THREAD

**Issue by WolfangAukang** [NixOS/nixpkgs#166840]
### Describe the bug

Recently, I have been trying to create a NixOS server with Elasticsearch and Kibana, both on version 7. Currently, Nixpkgs points that both ([Elasticsearch](https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=elasticsearch7) and [Kibana](https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=kibana7)) on 21.11 are on version 7.16.1 (https://github.com/NixOS/nixpkgs/pull/150879 is the PR where this is updated), but when I check the versions on the server, they are still on version 7.11.1, as shown below:

```
[root@nixos-elk:~]# curl localhost:9200
{
  "name" : "testing-1",
  "cluster_name" : "testing",
  "cluster_uuid" : "k_Lq7jarRveNHgZVbxSM7w",
  "version" : {
    "number" : "7.11.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "ff17057114c2199c9c1bbecc727003a907c0db7a",
    "build_date" : "2021-02-15T13:44:09.394032Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

[root@nixos-elk:~]# kibana --version --allow-root
7.11.1
```

### Steps To Reproduce
1. Create a configuration.nix file with the following setup:
```
{ modulesPath, lib, pkgs, ... }: {

  # AWS Defaults 
  imports = [ "${modulesPath}/virtualisation/amazon-image.nix" ];
  ec2.hvm = true;

  # Server
  networking.hostName = "nixos-elk";

  # Applications
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "elasticsearch"
      "kibana"
  ];
  services = {
    elasticsearch = {
      enable = true;
      package = pkgs.elasticsearch7;
      cluster_name = "testing";
      single_node = true;
      extraJavaOptions = [
        "-Xmx512m -Xms512m"
      ];
      extraConf = ''
        node.name: testing-1
        path.data: /data/elasticsearch
      '';
    };
    kibana = {
      enable = true;
      package = pkgs.kibana7;
      listenAddress = "0.0.0.0";
      extraConf = { 
        server.name = "testing";
      };
    };
    ssm-agent.enable = true;
  };
}
```
2. Run `nixos-rebuild switch`
4. Check if Elasticsearch and Kibana are on the stated version.

### Expected behavior
Elasticsearch and Kibana on version 7.16.1

### Notify maintainers

@apeschar @basvandijk 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@nixos-elk:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tpwrules** [comment]
Have you upgraded your nixos channel recently? Try `sudo nix-channel ---upgrade`, then `nixos-rebuild switch`.

**Comment by WolfangAukang** [comment]
Yes, that helped in updating it. As the Elasticsearch update was from December, I thought the current AMI was able to pick these changes.
