### ISSUE TITLE
Clarify that nixos-rebuild's --target-host doesn't cause cross compilation

### ISSUE THREAD

**Issue by jkozak** [NixOS/nixpkgs#166838]
### Describe the bug
Trying to use `nixos-rebuild` with `--target-host` to install onto a remote host.  Fails at what I think is the last hurdle.  

Here's the end of the output:
```console
copying path '/nix/store/y4wx0h1vad0k20njmhxr6s0i3bx8hy7y-system-units' to 'ssh://root@standus'...
copying path '/nix/store/6f97przhzd9l3p4xciqlmmgi0mhk8gv2-user-units' to 'ssh://root@standus'...
copying path '/nix/store/mr72r6vr69gncnn3p86504135c3k6s4p-etc' to 'ssh://root@standus'...
copying path '/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe' to 'ssh://root@standus'...
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 3: use: command not found
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 4: use: command not found
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 5: syntax error near unexpected token `('
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 5: `use File::Path qw(make_path);'
warning: error(s) occurred while switching to the new configuration
```

### Steps To Reproduce
`NIXOS_CONFIG=<cfg> nixos-rebuild --target-host root@host switch` 

### Expected behavior
New system installed on remote machine.

### Additional context
Command was run on a x86-64, target host is an i686.  

Trying to do this, I had previously encountered bug #159082 which I worked around as I described in that issue.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
jia:~/nixos$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.182, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.336755.efea022d6fe, nixos-unstable-22.05pre358986.062a0c5437b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jkozak** [comment]
Here's the metadata for the remote host:
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"i686-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.03.2262.2b417708c28 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-21.05.4726.530a53dcbc9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jkozak** [comment]
tried setting `--build-host` to the remote machine: that fails with "cannot execute binary file" when trying to run an `x86_64` version of `nix-store` (presumably on the remote `i686` machine).

I can't see a switch or env var for this, but should I be telling `nixos-rebuild` the target architecture?  I had presumed it would interrogate the target host...

**Comment by iblech** [comment]
I don't have any experience in cross compilation.

It seems that `switch-to-configuration` is treated as a bash script even though it's actually a Perl script. Could you try to run `/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration` (don't worry, if you don't pass any arguments to this script it won't do anything) on both of your computers?

From a quick look I didn't notice anything at odds with the way `pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh` calls `switch-to-configuration`.

**Comment by jkozak** [comment]
Running on the `x86_64`:
```console
jia:~/nixos$ /nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration
Usage: /nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration [switch|boot|test]

switch:       make the configuration the boot default and activate now
boot:         make the configuration the boot default
test:         activate the configuration, but don't make it the boot default
dry-activate: show what would be done if this configuration were activated
```

and on the `i686`:
```console
[jk@standus:~]$ /nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 3: use: command not found
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 4: use: command not found
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 5: syntax error near unexpected token `('
/nix/store/qdd3z2mwkyb9mmqchhsb3k696wbk8sb5-nixos-system-standus-21.11.336755.efea022d6fe/bin/switch-to-configuration: line 5: `use File::Path qw(make_path);'
```

the shebang for `switch-to-configutation` is:
```
#! /nix/store/4lfqnjvn4xm9nsm5mw78lvv31qmpjx1d-perl-5.34.0-env/bin/perl
```

and running that binary on the `i686` gives:
```console
[jk@standus:~]$ /nix/store/4lfqnjvn4xm9nsm5mw78lvv31qmpjx1d-perl-5.34.0-env/bin/perl -h
/nix/store/4lfqnjvn4xm9nsm5mw78lvv31qmpjx1d-perl-5.34.0-env/bin/perl: line 3: /nix/store/j4gm826s1ajlnqifayprzm528kjnznw2-perl-5.34.0/bin/perl: cannot execute binary file: Exec format error
/nix/store/4lfqnjvn4xm9nsm5mw78lvv31qmpjx1d-perl-5.34.0-env/bin/perl: line 3: /nix/store/j4gm826s1ajlnqifayprzm528kjnznw2-perl-5.34.0/bin/perl: Success

```
the same binary behaves as expected on the `x86_64` (prints `perl` help)
so it's trying to use an `x86_64` binary on an `i686`?

**Comment by iblech** [comment]
Okay! That is valuable output! Yes, I agree that it's trying to use an `x86_64` binary on an `i686`. A workaround fix for that concrete issue would be to change the shebang line into `#!/usr/bin/env perl`, which would (hopefully) find the correct perl to use at runtime.

However, that's probably not the best solution. The shebang line is specified in [nixos/modules/system/activation/switch-to-configuration.pl] as `#! @perl@/bin/perl`, which is in [nixos/modules/system/activation/top-level.nix] then rewritten by a call to `substituteAll` so that `@perl@` gets replaced by the path to whatever perl package which is currently in evaluation scope.

I hope that people who are more familiar with cross compilation can use this information to devise a good fix :-)

**Comment by iblech** [comment]
I tried to reproduce this here. Since all my machines are x86-64, I cannot use `--target-host` and instead tried cross compiling with `nix-build '<nixpkgs/nixos>' -A system -I nixos-config=i686.nix` where `i686.nix` has the following contents:

```
{ config, pkgs, ... }:

{
  boot.enableContainers = true;
  boot.isContainer = true;
  nixpkgs.crossSystem = {
    config = "i686-unknown-linux-gnu";
    system = "i686-linux";
  };   
}
```

However, this approach produces a `switch-to-configuration` file which references the correct (i686) perl.

I still assume that someone who is knowledgeable with the nixpkgs cross compilation architecture could resolve this very quickly, but time permitting I will also continue to think about this. @jkozak, do you have tuits to raise this issue over at our [Discourse](https://discourse.nixos.org/)?

**Comment by jkozak** [comment]
I have raised this on the discourse

**Comment by sternenseemann** [comment]
@iblech's [comment](https://github.com/nixos/nixpkgs/issues/166838#issuecomment-1087716102) has the answer I believe: `--build-host` and `--target-host` just tell `nixos-rebuild` where to run things *without any regard to their `system` architecture*. You need to make sure that your system configuration is cross compiled properly when going from x86_64 to i686.

**Comment by iblech** [comment]
Oh cool, thank you @sternenseemann! I didn't realize I had the solution :-)

So we are looking at a documentation bug, not at an implemention bug.

@jkozak, it looks like you need to add a `nixpkgs.crossSystem` section similar to my example in the relevant configuration.nix.

**Comment by jkozak** [comment]
Thanks!  I have inserted such a section and this almost works now, except that the cross-compile fails on `nghttp2` with `ld` failing on missing `-lz`, which I'll investigate separately.  

A caveat in the docs would be nice.
