### ISSUE TITLE
After zlib 1.2.12 upgrade, rustc spams '-zlib-1.2.12/lib/libz.so.1: no version information available'

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#166957]
### Describe the bug

The zlib upgrade to 1.2.12 seems to cause some sort of issue that causes rustup-downloaded rustc to output "libz.so.1: no version information available" messages when compiling.

### Steps To Reproduce

```
# rm -rf ~/.rustup
# rustup install nightly-2022-03-22 --force
# rustup default nightly-2022-03-22
# cargo new --bin delete
     Created binary (application) `delete` package
# cd delete
# cargo build
   Compiling delete v0.1.0 (/home/at/trash/delete)
/home/at/.rustup/toolchains/nightly-2022-03-22-x86_64-unknown-linux-gnu/bin/rustc: /nix/store/9vdc8d0gfmjzb0bqp7xyzjba69azqs9b-zlib-1.2.12/lib/libz.so.1: no version information available (required by /home/at/.rustup/toolchains/nightly-2022-03-22-x86_64-unknown-linux-gnu/lib/libLLVM-14-rust-1.61.0-nightly.so)
    Finished dev [unoptimized + debuginfo] target(s) in 0.57s
```

(nightly-2022-04-02 does this too.)

### Expected behavior

lack of "no version information available" messages as before

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.109, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
```

**Comment by Abdillah** [comment]
The warning come from here,

```
The warning come from here,

```
$ ldd /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-13-rust-1.59.0-stable.so                                                                                                                                                         Sun 10:35
ldd: warning: you do not have execution permission for `/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-13-rust-1.59.0-stable.so'
/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-13-rust-1.59.0-stable.so: /nix/store/9vdc8d0gfmjzb0bqp7xyzjba69azqs9b-zlib-1.2.12/lib/libz.so.1: no version information available (required by /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-13-rust-1.59.0-stable.so)
	linux-vdso.so.1 (0x00007ffcce9e6000)
	librt.so.1 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/librt.so.1 (0x00007f62deac4000)
	libdl.so.2 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libdl.so.2 (0x00007f62deabf000)
	libpthread.so.0 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libpthread.so.0 (0x00007f62dea9f000)
	libm.so.6 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libm.so.6 (0x00007f62de95e000)
	libz.so.1 => /nix/store/9vdc8d0gfmjzb0bqp7xyzjba69azqs9b-zlib-1.2.12/lib/libz.so.1 (0x00007f62de945000)
	libgcc_s.so.1 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libgcc_s.so.1 (0x00007f62de929000)
	libc.so.6 => /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libc.so.6 (0x00007f62de754000)
	/nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib64/ld-linux-x86-64.so.2 (0x00007f62e3b23000)
```
```

**Comment by marcgalois** [comment]
It looks like the underlying issue is https://github.com/madler/zlib/issues/617

Applying https://github.com/madler/zlib/commit/05796d3d8d5546cf1b4dfe2cd72ab746afae505d as a patch to zlib seems to resolve the problem.

**Comment by marcgalois** [comment]
It appears that https://github.com/NixOS/nixpkgs/pull/167395 should fix this once it's merged in.

**Comment by newAM** [comment]
This issue went away for me, but only for `x86_64-unknown-linux-gnu` targets, for embedded targets (`thumbv7em-none-eabi`) rustc still has this message.

```text
/home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: /nix/store/ilfqlmd6npxh3zaszdj7dj7zy6w96gmi-zlib-1.2.12/lib/libz.so.1: no version information available (required by /home/alex/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-14-rust-1.60.0-stable.so)
```

```console
$ readelf -d /nix/store/ilfqlmd6npxh3zaszdj7dj7zy6w96gmi-zlib-1.2.12/lib/libz.so.1         

Dynamic section at offset 0x16bd0 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/hbvq1160w7k0k0cfpmpd1hn3gf6apika-glibc-2.34-115/lib]
 0x000000000000000c (INIT)               0x3000
 0x000000000000000d (FINI)               0xfd00
 0x0000000000000019 (INIT_ARRAY)         0x17a70
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x17a78
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x200
 0x000000006ffffef5 (GNU_HASH)           0x588
 0x0000000000000005 (STRTAB)             0x1510
 0x0000000000000006 (SYMTAB)             0x940
 0x000000000000000a (STRSZ)              1746 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x17dd0
 0x0000000000000002 (PLTRELSZ)           1320 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x20a8
 0x0000000000000007 (RELA)               0x1d30
 0x0000000000000008 (RELASZ)             888 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x1ce0
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x1be2
 0x000000006ffffff9 (RELACOUNT)          28
 0x0000000000000000 (NULL)               0x0
 ```
 
 Missing SONAME.
 
Any got ideas?

**Comment by newAM** [comment]
Ack, never-mind, I found a straggler in `~/.rustup` that I didn't delete, it went away after cleaning that up.
