### ISSUE TITLE
HomeAssistant module: zoneminder component has a bug

### ISSUE THREAD

**Issue by 21stce** [NixOS/nixpkgs#166930]
### Describe the bug

> hass[121212]:   File "/nix/store/bk3grmdfi412lfw86dm8bvvh8mwgy1m5-python3.9-zm-py-0.5.2/lib/python3.9/site-packages/zoneminder/monitor.py", line 169, in is_recording
>  hass[121212]:     return int(status) == STATE_ALARM
> hass[121212]: ValueError: invalid literal for int() with base 10: 'false'

### Steps To Reproduce
1. I'd expect it's just a matter of `systemctl stop zoneminder`, because 
in a Python3 interpreter: `int('false')` returns the same error. So, it's probably just an upstream programming error. 

### Expected behavior
No such ValueError.

## Additional information

status_response.get("status") on line 164 clearly returns the string 'false', which implies that 
`self._client.get_state("api/monitors/alarm/id:{}/command:status.json".format(self._monitor_id))` also returns the wrong value. 

The Zoneminder API is here: https://pyzm.readthedocs.io/en/latest/source/pyzm.html. If someone wants to fix this, the first step is to `get_state` documented. Based on the semantics of get_state, one could then possibly write a working program. 

### Notify maintainers

@mweinelt (NixOS HomeAssistant) @pliablepixels (pyzm)

### Metadata
Unstable nixpkgs for home-assistant package and module, nixos-21.11 for the base system.

**Comment by mweinelt** [comment]
Not our issue. https://github.com/rohankapoorcom/zm-py/issues/48
