### ISSUE TITLE
Noto-fonts: switch to variable fonts

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nixpkgs#166953]
### Describe the bug

This is a follow up to https://github.com/NixOS/nixpkgs/pull/166600 and the comment in https://github.com/NixOS/nixpkgs/blob/a0a77f1c738384eb82560b9d359e27afb35c4dfc/pkgs/data/fonts/noto-fonts/default.nix#L34

AFAICT, just like the variable fonts are best for CJK, they are the best version to use for all the other Noto fonts too. This is what [Fedora thinks](https://fedoraproject.org/wiki/Changes/VariableNotoFonts#Benefit_to_Fedora). The variable fonts save a lot of disk space (10.94MiB vs 1.02MiB for Sinhala) and provide all variations, as well as enabling custom font variations in software that supports them.

I was wondering about hinting but it seems that all that's [happening](https://github.com/googlefonts/noto-source/blob/main/scripts/notobuilder.py#L46) is [ttfautohint](https://github.com/googlefonts/gftools/blob/0ede0eb58feeb0b44ad9ef9fb0ea7987a9b2b3ef/Lib/gftools/builder/autohint.py#L97). ttfautohint is built into FreeType so I think it gets run on Linux regardless for TTF fonts.

Now, the Adobe CFF renderer for OTF is better than the TTF renderer, and ideally we would get OTF variable fonts like with CJK. But those aren't available at the moment.

unhinted/slim-variable-ttf is a variable font with only 400 (Regular) through 700 (Bold) on the weight axis, prepared for Android system UI use ([script](https://github.com/googlefonts/noto-source/blob/main/misc_scripts/slimmer-vfs.sh#L20), [doc note](https://github.com/notofonts/noto-docs/issues/3)), it's smaller at 353 KB vs 1.03MB. Since we ship Light (300) in the main noto-fonts package I think we want the full range. Although Fedora [chose](https://src.fedoraproject.org/rpms/google-noto-fonts/blob/rawhide/f/google-noto-fonts.spec#_940) the slim, the savings from removing weights seems small IMO.

I'm opening this now but I think we should wait a week or two before switching over the fonts, in case there is more fallout from the variable CJK switch.

### Notify maintainers
cc @midchildan since you've been writing all the patches recently

**Comment by Mathnerd314** [comment]
OK, disk usage report on a download of https://github.com/googlefonts/noto-fonts:
```
755M    ./archive
483M    ./hinted/ttf
669M    ./unhinted
267M    ./unhinted/otf
336M    ./unhinted/ttf
47M     ./unhinted/variable-ttf
21M     ./unhinted/slim-variable-ttf
```
So sparse git checkout is the way to go, to avoid the archive directory. And slim is 26M less than full VF.

So now comparing the options:

| Option  | noto-fonts size | noto-extra size | Sum |
| --- | --- | --- | --- |
| Hinted TTF | 71M | 393M | 464M |
| Unhinted TTF | 52M | 269M | 321M |
| Pure OTF | 37M | 207M | 244M |
| OTF+Slim VF | 40M | 59M | 99 M |
| OTF + VF in noto-extra | 37M | 59M | 86M |
| OTF + VF in noto | 61M | 12M | 73 M |

The VF options are all combined with OTF since the variable fonts cover only a subset of the fonts.

The slim VF doesn't have Light, to keep the same font set I added the Light OTF font to noto-fonts (5M).  As I thought, Slim seems like a loser. It's worse than shipping the individual OTF's because Light is included, and even excluding Light it only saves 2M over the individual fonts.

The full variable fonts can either be in noto-fonts or noto-extra. If they are in noto-extra, we have to ship the normal OTF fonts `NotoX-Regular`; if in noto-fonts we can skip this. VF in noto-extra minimizes the size of noto-fonts, while VF in noto-fonts minimizes Hydra usage and avoid shipping fonts twice. Even with the VF in noto-fonts, it's still a savings versus the hinted TTF. 

So overall this confirms my initial thoughts, ship the full VF set in noto-fonts. What do other people think?

**Comment by midchildan** [comment]
VF in noto sounds good to me 👍

**Comment by Mathnerd314** [comment]
Also, Light/LightItalic should be in the extra package IMO, and the main package should be limited to `{Regular,Bold,Italic,BoldItalic}`. Those are the ["Microsoft 4 styles"](https://docs.microsoft.com/en-us/office/vba/api/excel.font.fontstyle), and the split is also what Debian does ([core](https://packages.debian.org/sid/all/fonts-noto-core/filelist) [extra](https://packages.debian.org/sid/all/fonts-noto-extra/filelist)). Looking at https://github.com/NixOS/nixpkgs/pull/31543#issuecomment-392394764 it seems Light was included in noto-fonts only because it was available in the 2016 git snapshot.

**Comment by Mathnerd314** [comment]
Ah, they were included because KDE says they need Light [for the calendar widget](https://mail.kde.org/pipermail/distributions/2017-November/000706.html). And there's a vague sort of promise that [that's all they'll use](https://mail.kde.org/pipermail/distributions/2017-November/000709.html). So I guess Light stays in. Although, most of the relevant languages have VF's with all weights, so it's kind of a corner case.

**Comment by Mathnerd314** [comment]
Alright, the status now is to wait a few days to see if Google fixes https://github.com/googlefonts/noto-fonts/issues/2315, https://github.com/googlefonts/noto-fonts/issues/2316, and https://github.com/googlefonts/noto-fonts/issues/2317, as fixing those will simplify the packaging. Worst case I'll have to special-case exclude the buggy fonts.

**Comment by Mathnerd314** [comment]
PR is up, #170355

**Comment by lhindir** [comment]
Only tangentially related, but since you're probably fairly familiar with the Noto packaging process now, I was wondering if you saw the [new version](https://developers.googleblog.com/2022/04/what-is-black-and-white-and-read-all.html) of the monochrome Noto Emoji (as opposed to Noto Color Emoji).

I can't seem to find the source on GitHub (the [noto-emoji repo](https://github.com/googlefonts/noto-emoji) still contains the old Noto Emoji, which is unmaintained and [pending removal](https://github.com/googlefonts/noto-emoji/pull/388)), but the new version is available from https://fonts.google.com/noto/specimen/Noto+Emoji/about under the SIL OFL. This bundle contains ttf's for five weights as well as a variable font; unfortunately, `fc-query` on the variable font indicates it only exposes three of these weights, so it might be best to hold off on the variable version for now.

What do you think about modifying the `noto-fonts-emoji` package to install this new version instead of the old one? The five weights weigh in under 5 MiB.

**Comment by Mathnerd314** [comment]
Hmm, it should at least be in https://github.com/google/fonts/tree/main/ofl. But it isn't. I think I will wait until it appears on GitHub somewhere, as the website link https://fonts.google.com/download?family=Noto%20Emoji looks like it will break when they update the font.
