### ISSUE TITLE
gnome-control-center graphical output stops (GNOME 42)

### ISSUE THREAD

**Issue by ryantm** [NixOS/nixpkgs#166980]
### Describe the bug

With GNOME 42 on master some tabs cause the application to stop outputting graphically.

### Steps To Reproduce
1. Open gnome-control-center
2. Click "Applications"

### Expected behavior
See the applications tab

### Screenshots
Here's a screencast of it:
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/umSsjUbDqNBDdfAbbFDQKwPo

### Additional context
When I reopen the gnome-control-center it shows the Applications tab and it works.

### Notify maintainers
@jtojnar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[ryantm@home2:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220401.e194871`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(root): `"agenix, nixos-20.09.4407.1c1f5649bb9"`
 - channels(ryantm): `"master"`
 - nixpkgs: `/nix/store/ph7i8qnxh9djkj9wmrhjmscixhn5bwzh-source`
```

**Comment by jtojnar** [comment]
That is likely this issue: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1672

**Comment by jtojnar** [comment]
We could apply `https://gitlab.gnome.org/GNOME/gtk/-/commit/cc02076b75115c799e029e5728e9fe65cab41ed0.patch` to `gtk4` if this becomes too annoying.

**Comment by ryantm** [comment]
`GSK_RENDERER=cairo gnome-control-center` fixes it for me.

**Comment by hello-smile6** [comment]
Not sure if it matters, but `gnome-control-center` fails with the following error for me:
```css
runner@03ba52370c61:~/vnc-gnome/hello$ GSK_RENDERER=cairo GDK_SYNCHRONIZE=1 gnome-control-center 
libGL error: MESA-LOADER: failed to open swrast: /nix/store/1jzl8nawbli2g2x94p6255wcs7m0w9al-libdrm-2.4.109/lib/libdrm_nouveau.so.2: undefined symbol: drmCloseBufferHandle (search paths /nix/store/p36pgcv991mq5srvg765b78yqpxvk3qs-mesa-21.3.3-drivers/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

(gnome-control-center:1138): Clutter-CRITICAL **: 23:38:19.524: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.
**
cc-object-storage:ERROR:../shell/cc-object-storage.c:167:cc_object_storage_add_object: assertion failed: (G_IS_OBJECT (object))
Bail out! cc-object-storage:ERROR:../shell/cc-object-storage.c:167:cc_object_storage_add_object: assertion failed: (G_IS_OBJECT (object))
Aborted (core dumped)
```
