### ISSUE TITLE
mplus-outline-fonts is broken

### ISSUE THREAD

**Issue by ngerstle** [NixOS/nixpkgs#166974]
### Describe the bug
Adding `mplus-outline-fonts` to system `fonts.fonts` results in a bad type error:

### Steps To Reproduce
1. Add 
```
  fonts.fonts = with pkgs; [
    mplus-outline-fonts
  ];
```
to `configuration.nix`
2. build system: 
```
$ sudo nixos-rebuild build 
building the system configuration...

error: A definition for option `fonts.fonts.[definition 1-entry 7]' is not of type `path'. Definition values:
       - In `/nix/store/mqkma522w1g3pfk9fr6llyvyg2dalnhv-source/configuration.nix':
           {
             githubRelease = <derivation /nix/store/fhaliawkzgb6r6dmysavhsr4mngx1c10-mplus-outline-fonts-github.drv>;
             osdnRelease = <derivation /nix/store/9lv5h4ss87aqizr9y46f7x2dxvl5q6wp-mplus-outline-fonts-osdn.drv>;
             override = <function, args: {fetchFromGitHub, fetchzip, lib}>;
             overrideDerivation = <function>;
           ...
(use '--show-trace' to show detailed location information)
```

### Expected behavior
A successful build, and addition of mplus-outline-fonts

### Additional context
This has been a recent change, and is occurring two systems which use flakes on an OS level (as well as an erase-your-darlings setup).

### Notify maintainers

@uakci (sorry, but given the recency of the issue, I can't help but wonder if it's tied to https://github.com/NixOS/nixpkgs/pull/151705 ?), 
@henrytill 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220330.710fed5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jansol** [comment]
It's not broken, [it was split into two variants](https://search.nixos.org/packages?channel=unstable&query=mplus-outline-fonts), `mplus-outline-fonts.osdnRelease` and `mplus-outline-fonts.githubRelease` with the big redesign upstream. The osdn variant is t he old one and github is the redesign.

**Comment by ngerstle** [comment]
Ah- unfortunate that this results in a misleading type error, rather than a notice that the package has been removed/replaced by one of the two options.

Changing from `mplus-outline-fonts` to `mplus-outline-fonts.githubRelease` worked for for me.

**Comment by jansol** [comment]
It would certainly be nice to have the original name throw a clear error pointing people in the right direction.

**Comment by layus** [comment]
It _is_ broken. Anyone using the old package name gets an error that fails the evaluation. The PR at #151705 removed a package and introduced two new ones. In practice it forces every user of the old package to pick a new one amongst the two new. In this situation it would be better to default to the old osdnRelease, as the new one is not backward compatible. (I have just tested). If it ever becomes backward compatible, we could redirect the default there. In the meantime, there is no point in breaking the evaluation for that new package. A deprecation warning would be better.

**Comment by layus** [comment]
But then, there is not proper mechanism in nixpkgs for renames and deprecation. That's a shame.

**Comment by layus** [comment]
Would you be okay with this fix ? https://github.com/NixOS/nixpkgs/pull/169420
