### ISSUE TITLE
Ensure that `torchvision` uses the same `cudatoolkit` version as `pytorch`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#166948]
## Issue description
As pointed out [here](https://github.com/NixOS/nixpkgs/pull/166784#issuecomment-1086656590), it's possible for the builds of pytorch and torchvision to use different cudatoolkit versions. We should eliminate this possibility in the same way that we eliminate the possibility of conflicting cudatoolkit versions when building pytorch:

https://github.com/NixOS/nixpkgs/blob/484bf4b741634c18e8b5fb68311782ba2d85f08b/pkgs/development/python-modules/pytorch/default.nix#L37-L38

There are two possible solutions:
* Create a `pytorch_compat_cudatoolkit` alias, similar to what TF does.
* Add cudatoolkit to the passthru of pytorch and then add asserts to the torchvision derivation. This has been proposed by @FRidh [here](https://github.com/NixOS/nixpkgs/blob/484bf4b741634c18e8b5fb68311782ba2d85f08b/pkgs/development/python-modules/pytorch/default.nix#L37-L38). Personally, I also think this is the best course of action.

**Comment by samuela** [comment]
cc @NixOS/cuda-maintainers

**Comment by SomeoneSerge** [comment]
> Add cudatoolkit to the passthru of pytorch and then add asserts to the torchvision derivation.

Agreed, we should definitely start with this before we attempt [any smart solutions](https://github.com/NixOS/nixpkgs/issues/163704#issuecomment-1083454974)

**Comment by FRidh** [comment]
Doing this now in https://github.com/NixOS/nixpkgs/pull/167016 however we're missing `cudaArchList`.

**Comment by SomeoneSerge** [comment]
> Doing this now in https://github.com/NixOS/nixpkgs/pull/167016 however we're missing cudaArchList.

Parameterizing the new `cudaPackages ` with `cudaArchList` is an interesting option! One question to answer is whether we want to (keep) allow(ing) to mix packages built with different cuda capabilities. Scenario: a user pulls an all-capabilities package from cache but then builds an unsupported package and wants to save time building just for their own hardware

**Comment by samuela** [comment]
Is there an advantage to relating `cudaArchList` to `cudaPackages`? They seem like orthogonal concepts IIUC.

**Comment by SomeoneSerge** [comment]
Agreed. _Yet another_ thought: different releases of cuda -> different supported gencodes (motived by now seeing mxnet fail trying to pass `-gencode sm_30` to nvcc from cuda 11.4)

**Comment by FRidh** [comment]
torchvision now uses pytorch.cudaPackages.
