### ISSUE TITLE
update ipfs to latest 0.4.x

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#16705]
i would like to run an ipfs node and write a NixOS service.

https://github.com/ipfs/go-ipfs#download-and-compile-ipfs

cc @zimbatm @kamilchm @rardiol

**Comment by zimbatm** [comment]
I started doing it. There is a branch at https://github.com/zimbatm/nixpkgs/tree/ipfs-0.4.2 and I've packaged the gx and gx-go tools that are now fetch dependencies to ipfs. The last bit would be to create a fetcher for those.

**Comment by kamilchm** [comment]
I'm working to change `deps.json` to `deps.nix` in `buildGoPackage`. I have it working for one package and need to migrate other pacakges. I can look at it after that.

**Comment by davidak** [comment]
>The last bit would be to create a fetcher for those.

@zimbatm something like replace `curl` with https://github.com/ipfs/ipget in fetchurl?

**Comment by zimbatm** [comment]
@davidak it has to be gx with the gx-go to provide the right structure on the disk (instead of ipget), but yes another fetcher basically.

**Comment by PierreR** [comment]
It looks like  https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/ipfs/default.nix is broken on the stable nixos channel:
```
builder for ‘/nix/store/vwpfqrwflh6khw8xl50si1rcfq6a6nbr-go1.7-ipfs-i20160112--7070b4d.drv’ failed with exit code 99
cannot build derivation ‘/nix/store/phb2b3qkrba1g6yzng9bp6n0gfjr9kqw-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/2si7m90l0av9k1h81wpw4iawhz4hz5l7-nixos-system-nixos-16.09.1149.e360c72.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/2si7m90l0av9k1h81wpw4iawhz4hz5l7-nixos-system-nixos-16.09.1149.e360c72.drv’ failed
```
Is it a known problem ? Shall open a new issue for this ?

**Comment by fpletz** [comment]
@PierreR Yeah, please open a new issue. This is an old issue that was fixed with my commit you mentioned. A little bit more

I've just built ipfs on the current master successfully. You're probably on the release-16.09 branch where ipfs was broken for a while. We could try backporting the version bump and the fetchgx stuff. You could try and test that and open a PR if you have the time. ;)
