### ISSUE TITLE
NVIDIA Proprietary driver missing nvidia-bug-report.sh script

### ISSUE THREAD

**Issue by starcraft66** [NixOS/nixpkgs#167180]
### Describe the bug
I want to report an NVIDIA driver bug to nvidia's forums and they require users to submit a log file generated by a script called `nvidia-bug-report.sh` included in their proprietary driver package, however the nix derviation for the drivers doesn't seem to include this script.

### Steps To Reproduce
1. Enable nvidia proprietary driver
2. Try running `nvidia-bug-report.sh`

### Expected behavior
A log file is created

### Notify maintainers
@jonringer 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.18, NixOS, 22.05 (Quokka), 22.05.20220403.1ddbc47`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `""`
 - channels(tristan): `""`
 - nixpkgs: `/nix/store/8qg31y2v1pn81305kmcqadna7rp6g22w-6lqy3gmi8ajsmljbhsvgx4gbk55152zk-source`
```

**Comment by FRidh** [comment]
See `for i in nvidia-cuda-mps-control nvidia-cuda-mps-server nvidia-smi nvidia-debugdump; do` in `pkgs/os-specific/linux/nvidia-x11/builder.sh`.  The expression needs to be updated to include other executables that are now not copied over.

**Comment by meditans** [comment]
As an owner of a 3090 card that crashes sometimes, this utility would be very helpful to have. In the meantime, I suggest people encountering this issue to find a copy of the script and issuing the commands in there one by one. This is unfortunately not as useful when interacting on the nvidia forum though. @NixOS/cuda-maintainers
