### ISSUE TITLE
godot 3.4.3 -> 3.4.4

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#167133]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: godot

current version: [3.4.3](https://github.com/NixOS/nixpkgs/pull/161989)
desired version: [3.4.4](https://github.com/godotengine/godot/releases/tag/3.4.4-stable)

###### Notify maintainers

maintainers: @Twey

###### Note for maintainers

Please tag this issue in your PR.

**Comment by clkamp** [comment]
Fixed by #167788
