### ISSUE TITLE
Remove unmaintained Go packages

### ISSUE THREAD

**Issue by aaronjheng** [NixOS/nixpkgs#167260]
I'm trying to refactor some Go packages built with `buildGoPackage`. I find there are some unmaintained/archived packages. Maybe we could just remove them?

**Comment by Mindavi** [comment]
Some cleanup is always welcome 🙂

**Comment by Artturin** [comment]
feel free to make a single pr called
`remove unmaintained/archived packages'
and then name the commits like so
`name: remove`
