### ISSUE TITLE
gnome-music 3.20 fails to load plugins

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#16729]
## Issue description

When launching gnome-music from a terminal, an error message is displayed:

> `grl-registry.c:1255: Could not open directory '/nix/store/mzq7732z6by6a729634sjkl0w5prdz7z-grilo-0.3.0/lib/grilo-0.3': Error opening directory`
> `14:47:17 ERROR   Failed to load plugins`

indeed, there is no directory `grilo-0.3` there, but I have the impression the library files should be searched in `/nix/store/rxzgpy3k2z8crp34ykk9d7p8bprcsh0z-grilo-plugins-0.3.1/lib/grilo-0.3` instead (please note the derivation name `grilo` vs. `grilo-plugins`).
## Technical details
- System: nixos-unstable

**Comment by jtojnar** [comment]
I can no longer reproduce this. Instead I get the following error when I try to play a song:

```
Info <GstPbutils.DiscovererInfo object at 0x7f6f3402b900 (GstDiscovererInfo at 0x21a7550)>: error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
02:46:38 WARNING	URI: file:///home/jtojnar/Music/Give%20My%20Love%20To%20London/01-give_my_love_to_london.mp3
02:46:38 WARNING	Error from element mpegaudioparse3: Internal data stream error.
02:46:38 WARNING	Debugging info:
     gstbaseparse.c(3597): gst_base_parse_loop (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin13/GstMpegAudioParse:mpegaudioparse3:
     streaming stopped, reason not-linked (-1)
```

**Comment by jtojnar** [comment]
Closing as it is probably fixed.
