### ISSUE TITLE
No way to install OpenJFX (JavaFX for OpenJDK) and use it for development

### ISSUE THREAD

**Issue by dimatomp** [NixOS/nixpkgs#16727]
## Issue description

Subj. Currently there is no way to install it via `nix-env` (or I have not found it)
### Steps to reproduce
1. `nix-env -i openjdk idea-community`
2. Run `idea-community`, open a JavaFX project
3. Set project SDK path to `~/.nix-profile/lib/openjdk`
4. Observe that idea fails to build the project or highlight javafx code
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.03.973.8bf31d7 (Emu)
- Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

nixos-16.03: 16.03.973.8bf31d7
nixos-unstable: 16.09pre85639.453086a

**Comment by mekeor** [comment]
Is there any work in progress, any news, any update, any hope, any ideas on this issue?

**Comment by dimatomp** [comment]
At the first sight, it seems like someone has to read and follow these instructions: https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX and obtain an OpenJFX package parameterized with a specific JDK derivation.
Personally, I'm not going to have time for this during next 4 days. In addition, I may not be able to test it properly because I don't use OpenJFX in any of my current projects.

**Comment by dimatomp** [comment]
There are at least two obstacles here:
- Building Gradle projects is not implemented yet: #17342
- OpenJFX is installed by copying binaries to OpenJDK directory: in our case, it implies that one will have to merge OpenJFX and OpenJDK folders somehow (symlinks?).

**Comment by eqyiel** [comment]
I packaged OpenJFX privately one time because I wanted to try Cryptomator, which depends on it.

https://github.com/eqyiel/nixos-config/blob/7f061191e906102588ff4d537f0b33e0c30d45eb/pkgs/openjfx/default.nix

I gave up on Cryptomator so I don't have any motivation to work on this, but you would be welcome to use it as a starting point.

You can tell OpenJDK how to find it like this: https://github.com/eqyiel/nixos-config/blob/7f061191e906102588ff4d537f0b33e0c30d45eb/pkgs/cryptomator/default.nix#L26-L55

**Comment by mekeor** [comment]
@eqyiel, I'm trying to use OpenJFX for Java development. When I run `javac Main.java`, OpenJFX is not found.

Do I understand correctly that the second snippet you linked to, can be used to make OpenJFX available for other Nix packages? But how do I tell OpenJDK (aka `javac`) in command-line where OpenJFX can be found?

**Comment by mekeor** [comment]
@dimatomp said:
> OpenJFX is installed by copying binaries to OpenJDK directory: in our case, it implies that one will have to merge OpenJFX and OpenJDK folders somehow (symlinks?).

Can't we solve this by copying the JAR files to `$out/share/java` as it is described in the [nixpkgs manual](https://nixos.org/nixpkgs/manual/#sec-language-java)?

**Comment by dimatomp** [comment]
@mekeor We can give it a try. I'm not sure if IntelliJ IDEA will recognize such an installation since IDEA does not currently require an OpenJFX dependency.

**Comment by mekeor** [comment]
These are the JAR files after the build-phase:

```
./apps/samples/Ensemble8/lib/lucene-grouping-3.2.0.jar
./apps/samples/Ensemble8/lib/lucene-core-3.2.0.jar
./tests/system/build/libs/systemTests.jar
./modules/swing/build/libs/swing.jar
./modules/base/build/libs/base.jar
./modules/media/build/libs/media.jar
./modules/builders/build/libs/builders.jar
./modules/controls/build/libs/controls.jar
./modules/graphics/build/libs/graphics.jar
./modules/fxml/build/libs/fxml.jar
./modules/extensions/build/libs/extensions.jar
./modules/web/build/libs/web.jar
./modules/fxpackager/build/libs/ant-javafx.jar
./modules/fxpackager/build/libs/packager.jar
./modules/swt/build/libs/swt.jar
./modules/jmx/build/libs/jmx.jar
./build/sdk/lib/ant-javafx.jar
./build/sdk/lib/packager.jar
./build/sdk/lib/javafx-mx.jar
./build/sdk/rt/lib/jfxswt.jar
./build/sdk/rt/lib/ext/jfxrt.jar
./build/libs/stringtemplate-3.2.jar
./build/libs/swt-debug.jar
./build/libs/ant-1.8.2.jar
./build/libs/antlr-runtime-3.1.3.jar
./build/libs/antlr-3.1.3.jar
./buildSrc/build/libs/buildSrc.jar
```

That's why I was thinking about adding these lines to the installPhase like this:

```nix
    installPhase = ''
      mkdir -p $out/share/java/openjfx

      cp -v  build/sdk/lib/*.jar        $out/share/java
      cp -v  build/sdk/rt/lib/*.jar     $out/share/java
      cp -rv build/sdk/rt/lib/ext/*.jar $out/share/openjfx

      cp -rv build/sdk $out
    '';
```

but the `javac` and `java` commands still can't find OpenJFX after installing [this package](https://github.com/mekeor/config/blob/b4d5418acb2760d95510d4dc524f04c8629171a3/nix/overlays/openjfx.nix).

**Comment by mekeor** [comment]
Do you have an idea what I'm doing wrong? You can check status of the WIP package here: https://github.com/mekeor/config/blob/master/nix/overlays/openjfx.nix

**Comment by eqyiel** [comment]
@mekeor yeah, it won't work with `javac` like this, the only reason that package I linked could find it is becuase of this patch: https://github.com/eqyiel/nixos-config/blob/7f061191e906102588ff4d537f0b33e0c30d45eb/pkgs/cryptomator/default.nix#L26-L55

AFAICT, the proper thing to do is overlay the result of building OpenJFX over an OpenJDK installation, which should be possible by overriding the OpenJDK derivation to copy the files into the right place: https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX#BuildingOpenJFX-Overlay-JDK8

I might take another look at this next weekend if no one has gotten around to it before then.

**Comment by moaxcp** [comment]
Should javafx work with oraclejdk? I have it installed with

```
  programs.java.enable = true;
  programs.java.package = pkgs.oraclejdk8;
```

I can see the javafx files in place but I'm still getting this error.

```
Caught: java.lang.NoClassDefFoundError: javafx/application/Application
java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by mekeor** [comment]
I installed `idea-community` which comes with its own JDK which includes a functioning JavaFX.

**Comment by moaxcp** [comment]
Yes I noticed that working but when I try to run my code using a groovy script (main use case) it doesn't work. Since the oracle jdk comes with javafx shouldn't that work? It seems like even if openjdk is overlayed with openfx it may not work.

**Comment by RCHG** [comment]
I am a beginner with Nixos, so I don't know if this would help but:
https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX
gives indications about how to build openjfx. Tecnically several nixos packages could be updated once openjfx is installed, for example, JabRef-3.8.1 to JabRef-4.1

**Comment by jlesquembre** [comment]
After #63574 openjfx works for me, I think we can close this issue
