### ISSUE TITLE
Unable to set locale for ssh session

### ISSUE THREAD

**Issue by surr** [NixOS/nixpkgs#16721]
## Issue description

Default value for LANG cannot be overriden by ssh session.
I have added "AcceptEnv LANG LANGUAGE LC_*" to sshd configuration (via services.openssh.extraConfig) but LANG is still set to nixos default value. 

Probably, the values of locale-related environment variables should be set only when not defined.
## Technical details

NixOS: 16.09pre85931.125ffff

**Comment by Profpatsch** [comment]
triage: can you still reproduce this?
