### ISSUE TITLE
Cassandra 4.0

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#167368]
Cassandra 4.0 has been released. It would be great if we could supply it as `cassandra_4_0` initially, and eventually move to it as a default. See https://cassandra.apache.org/_/download.html

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name

`nix search` name: `cassandra`

current version: 3.11.12
desired version: 4.0.3

###### Notify maintainers

maintainers: @roberth

###### Note for maintainers

Please tag this issue in your PR.

**Comment by roberth** [comment]
https://github.com/NixOS/nixpkgs/pull/167515 adds it. It passes the test, but I have not tested a migration. Is that something you could try?
