### ISSUE TITLE
Tor never finishes bootstrapping in the systemd service

### ISSUE THREAD

**Issue by wyndon** [NixOS/nixpkgs#167463]
### Describe the bug
At launch, the Tor daemon never finishes bootstrapping, it is stuck at 0%.
However when launching manually in a terminal, tor does starts, since it's using a default configuration instead.
### Steps To Reproduce
1. `tor.enable = true; tor.client.enable = true;`
2. check logs `journalctl -ef -u tor`

### Expected behavior
Tor should start.

### Additional context
```console
Starting Tor Daemon...
Apr 06 05:05:33.657 [notice] Tor 0.4.6.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.5.2 and Glibc 2.33 as libc.
Apr 06 05:05:33.657 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Apr 06 05:05:33.657 [notice] Read configuration file "/nix/store/p7ssp6fp8l8p82n94jkmbcqmdvw8mgls-torrc".
Configuration was valid
Started Tor Daemon.
Apr 06 05:05:33.731 [notice] Tor 0.4.6.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.5.2 and Glibc 2.33 as libc.
Apr 06 05:05:33.731 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Apr 06 05:05:33.731 [notice] Read configuration file "/nix/store/p7ssp6fp8l8p82n94jkmbcqmdvw8mgls-torrc".
Apr 06 05:05:33.733 [notice] Opening Socks listener on 127.0.0.1:9050
Apr 06 05:05:33.733 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
Apr 06 05:05:33.000 [notice] Parsing GEOIP IPv4 file /nix/store/v4jglpa7c2kmsng9000779kqc0sa16rd-tor-0.4.6.10-geoip/share/tor/geoip.
Apr 06 05:05:33.000 [notice] Parsing GEOIP IPv6 file /nix/store/v4jglpa7c2kmsng9000779kqc0sa16rd-tor-0.4.6.10-geoip/share/tor/geoip6.
Apr 06 05:05:33.000 [notice] Bootstrapped 0% (starting): Starting
Apr 06 05:05:34.000 [notice] Starting with guard context "default"
```

### Notify maintainers
@thoughtpolice @joachifm @prusnak

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.27-xanmod1-tt, NixOS, 22.05 (Quokka), 22.05.20220403.bc4b9ee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos-22.05pre347261.6d8215281b2"`
 - nixpkgs: `/nix/store/dpj59pj2msmd25q4mdmbvpmaa2j814rm-source`
```

**Comment by yuuyins** [comment]
i think this has something to do with 1b34039b5f1c3bfa6a9b1f7bd78ab3adecbe2a75 and maybe 3c63da7cf87473423a8138a82fbec59b9684d1c6.

i was getting the same but only when `tor.client.enable=false` (default), likely because 1b34039b5f1c3bfa6a9b1f7bd78ab3adecbe2a75. So, when I `tor.client.enable=true`, the client tries to connect to 9050 but that won't work likely because when `tor.enable=true` it uses that, so the client connects to 9051 instead. BUT that is only in joutnalctl, and the service is failed `Failed to start Tor Daemon.`?? Looking `netstat -plnt`, it actually connects to `9150` and `9051` instead. http request using socks5 on 9150  works.

**Comment by yuuyins** [comment]
generated torrc 
```
SOCKSPort 127.0.0.1:9050
SOCKSPort 9050
```

there seems so be some conflicting options here between `settings.SOCKSPort` and `client.socksListenAddress`.

**Comment by wyndon** [comment]
Okay, I've made some tests.

> alright this is a minimal config that works now @wyndon
> 
> ```
>   services.tor = {
>     enable = true;
>     settings = {
>       # socksListenAddress sets 9050 by default
>       # SOCKSPort = [{ port = 9050; }];
>       ControlPort = [{ port = 9051; }];
>     };
> 
>     client.enable = true;
>   };
> ```

Your solution didn't work for me.

So I took the configuration used by the service, used it manually with `sudo -u tor tor -f torrc`, and removed lines from the config file to see which part was causing the problem.

It turned out that, after removing `DataDirectory /var/lib/tor`, Tor worked as expected. So I simply deleted `/var/lib/tor` and restarted the systemd service, and everything was reworking. :shrug:

**Comment by yuuyins** [comment]
nixos reproducibility at its best 😂 glad you got it working too
