### ISSUE TITLE
Package request for Librewolf (Privacy-oriented Firefox)

### ISSUE THREAD

**Issue by rakinishraq** [NixOS/nixpkgs#167471]
**Project description**
Librewolf is a fork of Firefox focused on privacy with better settings options and defaults. 

**Metadata**

* homepage URL: https://librewolf.net/
* source URL: https://gitlab.com/librewolf-community/browser
* license: Mozilla Public License 2.0
* platforms: linux, darwin, windows

**Comment by squalus** [comment]
It's in master already as `librewolf`

**Comment by totoroot** [comment]
@squalus is right. `librewolf` is already packaged and can be installed from `unstable` or `nixpkgs`.

For future reference, if you're [searching for a package using the package search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=librewolf), please make sure to also check the unstable channel, as packages can be installed from there if they have been added after the last stable release (e.g. 22.05), as is the case for `librewolf`.

For more information on how to add channels take a look at the [official documentation](https://nixos.wiki/wiki/Nix_channels).

I'm going to close this issue but feel free to ping me if any problems arise when installing the package
