### ISSUE TITLE
mastodon-init-db.service fails with glibc 2.34

### ISSUE THREAD

**Issue by erictapen** [NixOS/nixpkgs#167433]
### Describe the bug

When using the Mastodon module on `nixos-unstable-small`, the service `mastodon-init-db.service` started to fail reliably inbetween 1eaa0a12120..b4729bad3d1.

```
Apr 05 23:45:48 myserver systemd[1]: Starting mastodon-init-db.service...
Apr 05 23:45:48 myserver mastodon-init-db-start[3873]: /nix/store/234gi4brgmw4ld21d4gi6y9rpcdxf9yy-wrapped-ruby-mastodon-gems-3.5.0/bin/ruby: symbol lookup error: /nix/store/rxjh6jxg7ksisbcxl0cjwcff5iprpdfz-glibc-2.33-123/lib/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE
Apr 05 23:45:48 myserver systemd[1]: mastodon-init-db.service: Main process exited, code=exited, status=127/n/a
Apr 05 23:45:48 myserver systemd[1]: mastodon-init-db.service: Failed with result 'exit-code'.
Apr 05 23:45:48 myserver systemd[1]: Failed to start mastodon-init-db.service.
```

Unfortunately I have no idea on how to approach this. We don't seem to provide Glibc 2.33, so falling back is no option. I also tested wether we could upgrade to Ruby 3.1.1, but that is not supported by upstream and it is unclear wethet that would help.

### Additional context

I somehow expect 97acaf6d65e869abf7dc9e6825aef4c0e7b98432 to be the culprit here.

### Notify maintainers

Any ideas, @Izorkin?
@erictapen @happy-river

**Comment by Izorkin** [comment]
Checking without `LD_PRELOAD`?

**Comment by Izorkin** [comment]
Needed update system with `sudo nixos-rebuild boot`, then reboot system.

**Comment by erictapen** [comment]
Mh I restarted the server and the error persisted? Don't see what `nixos-rebuild boot` would change about that.

**Comment by Izorkin** [comment]
Glibc 2.33 and 2.34 libraries conflict with each other. 
I was able to update my system. Mastodon works.
But nginx unit service stopped normal working normally with jemalloc memory allocator.

**Comment by mweinelt** [comment]
This was exactly the error message I got when I LD_PRELOADed the release-21.11 jemalloc package on a binary that was compiled against glibc 2.34.

> hass[5530]: /nix/store/30j23057fqnnc1p4jqmq73p0gxgn0frq-bash-5.1-p16/bin/bash: symbol lookup error: /nix/store/g02b1lpbddhymmcjb923kf0l7s9nww58-glibc-2.33-123/lib/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE

Updating to the unstable jemalloc package I got

> home-assistant-pre-start[44471]: /nix/store/00z6kxv40m8aq9rpf1g1sfgn9mfjvhzd-bash-5.1-p8/bin/bash: /nix/store/g02b1lpbddhymmcjb923kf0l7s9nww58-glibc-2.33-123/lib/libc.so.6: version GLIBC_2.34' not found (required by /nix/store/jh49s9hvd8g2jwpkgm3wdjcn40y86lls-jemalloc-5.2.1/lib/libjemalloc.so)
> home-assistant-pre-start[44471]: /nix/store/00z6kxv40m8aq9rpf1g1sfgn9mfjvhzd-bash-5.1-p8/bin/bash: /nix/store/g02b1lpbddhymmcjb923kf0l7s9nww58-glibc-2.33-123/lib/libc.so.6: version GLIBC_2.34' not found (required by /nix/store/khg2yz8aklbagx09h878a6c5vz94b9p0-gcc-10.3.0-lib/lib/libstdc++.so.6)

So I dropped jemalloc entirely for home-assistant (which I overlay from master), and now it's back working.

**Comment by erictapen** [comment]
Yeah, my suspicion is that the mixing of the two glibc caused the problem for me as well. I also saw the error an a setup that used Mastodon from nixos-unstable, but the remainder of the OS from 21.11. So I suppose my setup was at fault here :)
