### ISSUE TITLE
OpenAL gives wrong include and libs path with pkg-config

### ISSUE THREAD

**Issue by necessarily-equal** [NixOS/nixpkgs#167528]
### Describe the bug
The pkg-config file for OpenAL is unusable.

### Steps To Reproduce
1. open a devshell with pkg-config and openal (works both with the stable and unstable release of nixpkgs)
2. `pkg-config --cflags`
3. notice that the flags are not correct: « `-I/nix/store/iccwkh7yacv40zyqnj1mah73616mid5s-openal-soft-1.21.1//nix/store/iccwkh7yacv40zyqnj1mah73616mid5s-openal-soft-1.21.1/include -I/nix/store/iccwkh7yacv40zyqnj1mah73616mid5s-openal-soft-1.21.1//nix/store/iccwkh7yacv40zyqnj1mah73616mid5s-openal-soft-1.21.1/include/AL` »

in a single command, `nix-shell -E 'with (import <nixpkgs> {}); stdenv.mkDerivation{name="foo"; buildInputs=[pkg-config openal];}' --run 'pkg-config --cflags openal'`

here is the result on unstable: `-I/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1//nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/include -I/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1//nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/include/AL`

### Expected behavior
Include path is
* `/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/include`
* `/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/include/AL`
instead of
* `/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1//nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/include`
* `/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1//nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/include/AL`

Likewise for `--libs`, `-L/nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1//nix/store/dvb8l321pvzdyb2c2ljpc9wvrfzs335w-openal-soft-1.21.1/lib` should not contain the path twice.

### Notify maintainers
@ftrvxmtrx

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.106, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.336340.2ebb6c1e5ae, nixpkgs-git"`
 - channels(afontain): `"nixos-20.09-20.09.4407.1c1f5649bb9, nixpkgs-unstable-22.05pre342949.28d58b97925, nixpkgs-20.09-20.09.4407.1c1f5649bb9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
See https://github.com/jtojnar/cmake-snips on how to fix this.

**Comment by jtojnar** [comment]
cc @fufexan @ilya-fedin

**Comment by fufexan** [comment]
@jtojnar I'd happily work on this but I have no experience with CMake. Perhaps with some guidance I could try to make it work.

Would it need a patch on our side, or maybe a fix upstream?

**Comment by jtojnar** [comment]
Ideally, it would be fixed upstream. These are the offending lines (variables are absolute paths):

https://github.com/kcat/openal-soft/blob/22e6c0df6017aa86e2cd83d8073e4d490c55dd11/CMakeLists.txt#L1256-L1258

**Comment by ilya-fedin** [comment]
https://github.com/kcat/openal-soft/pull/696

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/181875 merged

**Comment by ilya-fedin** [comment]
Why not to update it to 1.22.2 rather than patching? :thinking:

**Comment by Artturin** [comment]
> Why not to update it to 1.22.2 rather than patching? thinking

looks like it was already done. i added a commit removing the patch in https://github.com/NixOS/nixpkgs/pull/172347

**Comment by ilya-fedin** [comment]
Does search-out.patch actually apply? The code in 1.22.2 is different, so it's very surprising if it applies cleanly. It's possible to set `-DALSOFT_SEARCH_INSTALL_DATADIR=ON` instead of the patch.
