### ISSUE TITLE
Some application icons missing in GNOME3 (NixOS 16.09/unstable)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#16758]
## Issue description
When moving a NixOS 16.03 system to 16.09/unstable, some application icons are missing in the GNOME3 UI (dash/dock/activities/overview or what's it called). One particular example is chromium. chromium is in in environment.systemPackages, so it's consistent with the rest of the system. Moving back to 16.03 makes the icons appear again.

Not all icons disappear. For instance, the GNOME "Web" application has working icons also on master.

### Steps to reproduce
* GNOME3 desktop (haven't tested other DEs)
* With chromium installed, see if it has the "chromium" icon in the gnome shell activities view. If broken, the icon is the stock "program" icon (or what's it called), which is used when no icon is available.

## Technical details

* System: NixOS 16.09/unstable @ 0d5be595a7c707be1cedebf1f14a47cafdf0a3f4 (master as of today, but the issue has been there for weeks)

**Comment by bjornfor** [comment]
I'm guessing it has something to do with multiple outputs.

**Comment by bjornfor** [comment]
Oh, it looks mostly fixed now (tested at nixpkgs master 6af0f57f91f5b87e10186f7d26a345cab565478c). Yay!

For completeness, I see missing icons for these apps in GNOME Shell overview:

* Audacious
* Cheese
* Firefox
* FMIT
* Meld
* Okular
* Pitivi
* qScreenshot
* Qt Creator

(But I don't know if they were missing before or not.)

**Comment by jluttine** [comment]
Is this fixed? I still have missing icons in GNOME, for instance: Firefox, Evolution, Shotwell. Should I open a new issue, should this be re-opened or is the issue fixed but I'm just doing something wrong. I'm using unstable channel.
