### ISSUE TITLE
toml format test broken after staging-next

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#167681]
### Describe the bug

The problem seems to be that `json2toml` no longer generates empty tables if they only have sub-tables and no other values:

```
--- /nix/store/abj1nld28vhb70fnr4c9njlqjjkp8zxk-expected        1970-01-01 00:00:01.000000000 +0000
+++ /nix/store/qpr7arq1xgl13skbic7cvll61i63bbi5-test-format-file        1970-01-01 00:00:01.000000000 +0000
@@ -7,8 +7,5 @@

 [attrs]
 foo = "foo"
-
-[level1]
-[level1.level2]
 [level1.level2.level3]
 level4 = "deep"
```

392eb5a52678f26bffe86798714c454334ba920c seems to be a likely culprit, but I haven't tried to bisect the issue yet.

The simplest fix would be to accept this behavior, but I think it's at least worth a discussion beforehand.

cc @mweinelt @infinisil 

### Steps To Reproduce

`nix-build -A tests.pkgs-lib`

**Comment by mweinelt** [comment]
As `remarshal` relies on `tomlkit` it seems like a reasonable assumption. Can you create an issue over at https://github.com/sdispater/tomlkit/issues? I didn't immediately spot anything in the release notes.

**Comment by vcunat** [comment]
Blocker note: this "only" blocks `nixpkgs-unstable` channel, not the NixOS ones (which advanced already by yesterday).

**Comment by sternenseemann** [comment]
home-manager chose to accept this in a *concrete* case: https://github.com/nix-community/home-manager/commit/66ffa7a0a6411c7c73a648bd0b426c73e2a14fa0
