### ISSUE TITLE
sage broken in master and unstable

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#167672]
### Describe the bug
`sage` does not build

### Steps To Reproduce
1. `nix build nixpkgs#sage`
2. `ERROR: No matching distribution found for networkx<2.7,>=2.4`

### Expected behavior
`sage` should build

### Screenshots
On hydra: https://hydra.nixos.org/build/172309817/nixlog/1

### Additional context
culprit is 018a61d48cb3bde374e5ec81b1b7d07f66b10152
> upgrade may break sage, please test the sage build or ping @timokau on upgrade

### Notify maintainers
@timokau @omasanori @7c6f434c @collares

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.20220405.1eaa0a1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - nixpkgs: `/etc/nix/channels/nixos`
```

**Comment by collares** [comment]
Thanks for the report! I will look at it today.
