### ISSUE TITLE
nettools for Darwin

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#16764]
## Issue description

Right now the "net-tools" package is required by quite a few different packages: https://github.com/NixOS/nixpkgs/search?q=nettools

The following commands are included:
- arp(8)
- hostname(1)
- ifconfig(8)
- ipmaddr
- iptunnel
- mii-tool(8)
- nameif(8)
- netstat(8)
- plipconfig(8)
- rarp(8)
- route(8)
- slattach(8)

Some of these should be available in Mac OS X. We should provide some sort of cross platform package that packages these tools.

**Comment by matthewbauer** [comment]
"network_cmds" is available from opensource.apple.com

**Comment by copumpkin** [comment]
It should definitely be possible to package network_cmds but if people expect it to behave like similar tools from linux they'll be disappointed. `hostname` and `ifconfig` are probably similar, but `netstat` and `route` are pretty different; no idea about the other ones.

**Comment by matthewbauer** [comment]
I think it's mainly "gnutls" that depends on "nettools"... I wonder why it actually needs that?

https://github.com/NixOS/nixpkgs/commit/325dafe82b74cf7d1c4883cd1ba4909741672eb0

**Comment by copumpkin** [comment]
@manveru was saying in the comment that it's not necessary, so we could just make it a conditional `buildInputs` entry?

**Comment by matthewbauer** [comment]
Probably, but I think there's lots of cases where something will need to run "hostname" or "ifconfig" for debugging/etc. but not really need the functionality to work.

see fish: https://github.com/NixOS/nixpkgs/blob/31c158ad453547993095b9425a60697738fdac5d/pkgs/shells/fish/default.nix

**Comment by copumpkin** [comment]
Sure, we can still package `network_cmds`; just doesn't seem as pressing for `gnutls` in particular!

**Comment by matthewbauer** [comment]
Definitely, most of the evaluation errors are caused by gnutls though I suspect some other packages need a fix too.

**Comment by matthewbauer** [comment]
I'm going to leave this open but #16783 should be a temporary fix.
