### ISSUE TITLE
anki-bin: blank main window

### ISSUE THREAD

**Issue by dnaq** [NixOS/nixpkgs#167765]
### Describe the bug

After upgrading to the current version of nixpgs (nixos-unstable) anki starts up to a blank main window. According to the documentation (https://docs.ankiweb.net/platform/linux/blank-window.html) that is because of the system glibc having changed to a version not compatible with anki. Their suggested fix is that users move to using the beta package instead.

### Steps To Reproduce
1. nix-shell -p `anki-bin`
2. anki

### Expected behavior
Anki working as usual

### Notify maintainers
@Atemu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220406.b6966d9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220322_d5d4d98`
 - channels(root): `""`
 - channels(user): `""`
 - nixpkgs: `/nix/store/gyzqxklnmyzl773qpqylnfvhg6gimyad-source`
output here
```

Excerpt from flake.lock:

```nix
"nixpkgs": {
      "locked": {
        "lastModified": 1646497237,
        "narHash": "sha256-Ccpot1h/rV8MgcngDp5OrdmLTMaUTbStZTR5/sI7zW0=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "062a0c5437b68f950b081bbfc8a699d57a4ee026",
        "type": "github"
      },
```

**Comment by yayayayaka** [comment]
Can confirm the behaviour.
