### ISSUE TITLE
rustc/cargo outdated in nixos 16.03

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#16776]
## Issue description

After [this issue](https://github.com/matthiasbeyer/imag/issues/515) was reported to my project, I filed [this issue](https://github.com/servo/rust-url/issues/213) with the upstream crate.

I think, though, that updating rustc and cargo in the nixos stable release shouldn't be much of an issue, as the rust people really check that the backwards compatibility never breaks.

What do you guys think of updating rustc and cargo on the stable release channel?

**Comment by SimonSapin** [comment]
@mckeankylej, I’m told you can get a more recent rustc at https://hydra.nixos.org/job/nixpkgs/trunk/rustc.x86_64-linux

**Comment by mckeankylej** [comment]
How do you specify this in a default.nix? fetchurl?

**Comment by flosse** [comment]
> What do you guys think of updating rustc and cargo on the stable release channel?

That would be really great!

But if this would be no option to others I'd be happy to know how I can use an up to date rust/cargo in conjunction with `buildRustPackage`.

**Comment by Mic92** [comment]
is this still an issue in `16.09`?

**Comment by NeQuissimus** [comment]
Looking at the upstream bug issues, it seems we should have a recent enough Rust version (1.0 is mentioned, 1.11.0 is what we have in 16.09)

**Comment by flosse** [comment]
I think we'll have this issue in every stable nixos release because the release cycle of rust stable is smaller (6 weeks) than the nixos ones. So I'd expect that `1.11.0` will cause troubles within a few month :-\

**Comment by NeQuissimus** [comment]
PRs for new Rust versions are always welcome to the `master` branch.
And those usually make it into stable releases.

Now, if you want to stick with a stable NixOS release, you may have to pull in Rust from `master`, of course.
