### ISSUE TITLE
Peazip

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nixpkgs#167707]
**Project description**

Peazip is a GUI archive manager for Linux, MacOS, Windows. It's open source. I think nixpkgs is missing a GUI archive manager.

**Metadata**

* homepage URL: https://peazip.github.io/peazip-linux.html
* source URL: https://github.com/peazip/PeaZip
* license: lgplv3
* platforms: linux

**Comment by papojari** [comment]
`gnome.file-roller` is a GUI archive manager.

**Comment by papojari** [comment]
I have no idea how to compile the program. There are no instructions on the website or readme. I've sent the developer an email.

**Comment by CMCDragonkai** [comment]
The `readme` https://github.com/peazip/PeaZip/tree/sources/peazip-sources mentions using lazarus IDE and the `.lpi` files.

**Comment by papojari** [comment]
the lazarus ide doesn't seem to have a way to compile stuff without a gui though judging by the help information.

**Comment by MrPancakes39** [comment]
Any news?

**Comment by auroraanna** [comment]
> Any news?

[The PR](https://github.com/NixOS/nixpkgs/pull/169447) produces a working peazip

**Comment by MrPancakes39** [comment]
Oh thanks for informing me ❤️

**Comment by thiagokokada** [comment]
Close with https://github.com/NixOS/nixpkgs/pull/169447.
