### ISSUE TITLE
Update mutt to 1.6.2

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#16772]
## Issue description

[Mutt 1.6.2 just came out](https://marc.info/?l=mutt-users&m=146787029025050&w=2). We still have mutt 1.6.0

The mutt infrastructure is rather complex, so I guess I won't be able to do the update myself, this is why I'm filing this issue.

**Comment by rnhmjoj** [comment]
The package itself can be updated just by changing the version and the hash: the problem seems to be the various sidebar/trash patches. 
I don't know where to find them.

**Comment by vrthra** [comment]
I was wondering, we carry `neomutt` which is nothing but patches and mutt. Do we need to carry the external patches in the main `mutt` package too?

**Comment by matthiasbeyer** [comment]
@vrthra possibly for people who want only some of them (neomutt simply contains all of them afaik).

**Comment by vrthra** [comment]
@matthewbauer It [seems](http://www.neomutt.org/manual/optionalfeatures.html) we can simply enable and disable individual patches during configuration (I have not tried whether different patches have interdependencies). Perhaps we can allow that as configuration options for neomutt? Right now, we are just carrying all the patches in mutt without the ability to choose which ones to apply (unless one edits the nix file).

**Comment by matthiasbeyer** [comment]
I think you wanted to @ mention me... but yes... I do not care that much about the patches as I use plain mutt. I just want to get the update to the next version. This is also why I didn't just file an PR for the update: I cannot test the patches - I don't even know where to find them!

So I only care for the update - The discussion you want to start should go to another issue, IMHO! :smile:

**Comment by vrthra** [comment]
@matthiasbeyer sorry about the name. Autocomplete is not my friend :(

**Comment by vrthra** [comment]
@rnhmjoj It [seems](https://dev.mutt.org/trac/ticket/3829) the sidebar patch has been integrated, so we can probably lose that patch.

**Comment by rnhmjoj** [comment]
I see from the commits in the mutt repo on bitbucket the sidebar patch was indeed merged however "sidebar" is not even mentioned in the [source for 1.6.2](http://ftp.mutt.org/pub/mutt/mut-1.6.2.tar.gz).
This is strange because it seems to me the patch was integrated before the 1.6.2 release but I may be wrong.

**Comment by joachifm** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/16805
