### ISSUE TITLE
firefox (all versions): some WebExtensions and first boot landing page crash silently

### ISSUE THREAD

**Issue by neirenoir** [NixOS/nixpkgs#167785]
Since my last NixOS upgrade, most of my Firefox addons have stopped working. Finding the root cause of the bug has been complicated since the bug is not consistent across computers of similar configuration, and the debugging tools or the CLI do not give away any information.

### Steps To Reproduce
1. Install any version of Firefox (vanilla, bin, ESR, devedition, beta, wayland, etc)
2. Install an addon that can replicate the bug ([uBlock](https://addons.mozilla.org/es/firefox/addon/ublock-origin/) seems to be prone to crashing)
3. Try to click the addon's icon to open it. You will be met with a vertical white strip instead.
4. Go to about:debugging and navigate through the Manifest link corresponding to the faulty extension shown in `This Firefox` until you find the addon's popup HTML file (in the case of uBlock, it is found in `moz-extension://{extension ID here}/popup.html`)
5. "Gah. Your tab just crashed."

### Expected behavior
Funnily enough, not all extensions, nor all of the pages inside of an extension will cause a crash. HTTPS Everywhere seems to work most of the time, but uBlock, uMatrix and also Metamask crash before being able to start. uBlock and uMatrix stop working completely, but Metamask still manages to inject `window.web3` and even attempts to open wallet connection request popups (although they don't manage to render) when interacting with it. uBlock and uMatrix's internal setting pages don't seem to crash the browser.

### Additional context
To make the issue more bizarre, this is only happening in my desktop, not in my laptop. The configuration of both machines is similar, and I am almost sure hardware is not the issue. Checking Mozilla's crash stats, there have been (to date) [78 crashes with the same signature](https://crash-stats.mozilla.org/search/?signature=%3Dlibc.so.6%400x1328a9%20%7C%20libc.so.6%400xd7ff7%20%7C%20libglib-2.0.so.0%400x92463&product=Firefox&platform=Linux&date=%3E%3D2022-03-31T22%3A10%3A00.000Z&date=%3C2022-04-07T22%3A10%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#crash-reports), of which 100% come from NixOS machines with all sorts of hardware configurations. The common point between all these crashes is that **Firefox reports to be missing `libc.so.6`, `libgio-2.0.so.0` and `libglib-2.0.so.0`**.

### Notify maintainers

Tagging @mweinelt @lovesegfault @edolstra @Ma27 @lovek323 @7c6f434c. Pardon me if this bug report is not relevant to some of you.

### Metadata
```console
[nix-shell:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05pre367572.b6966d911da`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by lovesegfault** [comment]
This can be worked-around by exporting `MOZ_DISABLE_CONTENT_SANDBOX=1`.

**Comment by neirenoir** [comment]
Effectively, `MOZ_DISABLE_CONTENT_SANDBOX=1`works like a charm. What's causing the sandbox to fail? I found some Gentoo bug reports that seem to suggest the issue is with the sandboxing level, but they are patching it on the glib side. Compiling glib without FAM does the trick, and it seems other distroes do the same. Looks like it's not the first time happening.
https://bugs.gentoo.org/show_bug.cgi?id=828070

**Comment by Infinidoge** [comment]
Can reproduce,
I was exceedingly confused when 90% of my addons suddenly failed to load entirely, adding the variable to my `sessionVariables` worked as described.

**Comment by flexagoon** [comment]
> Compiling glib without FAM does the trick

@neirenoir what's the easiest way to do that on NixOS?

**Comment by beardhatcode** [comment]
Interesting, sice FF99 I also had tabs crashing, but I did not notice that my extensions did not load.

**Comment by chvp** [comment]
I could reliably crash a tab by trying to open a PDF and most of my extensions were broken. Both issues are fixed by disabling the content sandbox.

**Comment by dit7ya** [comment]
> This can be worked-around by exporting `MOZ_DISABLE_CONTENT_SANDBOX=1`.

How secure/safe is it?

**Comment by mohe2015** [comment]
> > This can be worked-around by exporting `MOZ_DISABLE_CONTENT_SANDBOX=1`.
> 
> How secure/safe is it?

As far as I understand it disables all defense-in-dept (I think mozilla even considers it not a serious vulnerability to get code execution there). I think mozilla considers a sandbox escape the dangerous thing and this disables the sandbox. So this is probably really stupid. Reverting to a working commit is probably marginally better (maybe you can even cherry pick the Firefox update in top of it as that doesn't seem to the issue)

**Comment by mohe2015** [comment]
I'm currently trying to bisect

**Comment by mweinelt** [comment]
This is related to the glibc 2.34 bump if I understood the discussion correctly, so reverting will be a stdenv rebuild.

**Comment by mohe2015** [comment]
Yeah didn't bisect completely but pretty likely. I thought it wasn't certain whether we're affected by the same issue. So now the only possibility is reverting to before that?

**Comment by mohe2015** [comment]
My personal "workaround" is using a different browser.

**Comment by mohe2015** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/replace-dependency.nix could be attempted in theory.

**Comment by fabianhjr** [comment]
Current patch [v2] from sam: https://patchwork.sourceware.org/project/glibc/patch/20220314175316.3239120-2-sam@gentoo.org/

Could test locally and create a merge-request. Should target master as an urgent fix or staging-next?

**Comment by andersk** [comment]
I configured my system with

```nix
{
  system.replaceRuntimeDependencies = [{
    original = pkgs.glibc;
    replacement = pkgs.glibc.overrideAttrs (old: {
      patches = old.patches ++ [
        (pkgs.fetchpatch {
          url = "https://patchwork.sourceware.org/project/glibc/patch/20220314175316.3239120-2-sam@gentoo.org/raw/";
          hash = "sha256-YNqBMiNQW78cPu740P01iefAM4EQU9YwRAAmfh9Mfp0=";
        })
      ];
    });
  }];
}
```

and wrapped all packages in my user environment with a similar application of `replaceDependency`. (It would probably have been sufficient to wrap only Firefox, but I wanted to do a complete test.)

I get one console warning from Firefox:

`(/nix/store/50g6xfhppripm74h198kbmnapgs6f31a-firefox-bin-99.0/usr/lib/firefox-bin-99.0/firefox-bin:321213): GLib-WARNING **: 14:38:39.981: getpwuid_r(): failed due to: Permission denied.`

but it’s working fine.

**Comment by andersk** [comment]
Submitted a PR:

- #167932

**Comment by vcunat** [comment]
You could also use Firefox from 21.11 for now; we have the latest versions in there.

**Comment by KenMacD** [comment]
> This can be worked-around by exporting `MOZ_DISABLE_CONTENT_SANDBOX=1`.

As a more secure workaround, in `about:config` you can set `security.sandbox.content.level` to `3` for a bit.

**Comment by ghishadow** [comment]
I switched to flatpak Firefox as a workaround as `MOZ_DISABLE_CONTENT_SANDBOX=1` was reseting firefox profile data

**Comment by mweinelt** [comment]
I think what @KenMacD describes in https://github.com/NixOS/nixpkgs/issues/167785#issuecomment-1094071798 it the best solution for now.

It was also mentioned on the mozbz to which the link I can't find anymore.

**Comment by SebTM** [comment]
I'm using this:

```
programs = {
  firefox = {
    enable = true;
    package = (import <nixpkgs-stable> {}).firefox;
  };
};
```

where nixpkgs-stable is the 21.11-channel. Like @vcunat purposed :)

**Comment by mweinelt** [comment]
The reason this works is because the stable channel uses glibc 2.33, so a good workaround indeed.

**Comment by SebTM** [comment]
> The reason this works is because the stable channel uses glibc 2.33, so a good workaround indeed.
.

> How secure/safe is it?
Yeah, particularly I had security-concerns/questions like @dit7ya when I discovered it.

**Comment by mweinelt** [comment]
> This can be worked-around by exporting `MOZ_DISABLE_CONTENT_SANDBOX=1`.

Please look for one of the two other recommended workarounds instead.

- https://github.com/NixOS/nixpkgs/issues/167785#issuecomment-1094071798
- https://github.com/NixOS/nixpkgs/issues/167785#issuecomment-1094131737

**Comment by vcunat** [comment]
You can also use firefox from the `staging-next` branch; binaries are there already: https://hydra.nixos.org/build/173239449  (for x86_64-linux)

**Comment by vcunat** [comment]
It's in all channels now.

**Comment by mweinelt** [comment]
When updating please remember to rollback your workarounds, especially if you reduced the sandbox level as advised in https://github.com/NixOS/nixpkgs/issues/167785#issuecomment-1094071798 or if you disabled the sandbox entirely using `MOZ_DISABLE_CONTENT_SANDBOX`.
