### ISSUE TITLE
openmoji has started taking forever to build.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#167869]
### Describe the bug

openmoji-color and openmoji-black now both take >12h to build. They are timing out on hydra https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.openmoji-color.x86_64-linux.

### Steps To Reproduce
1. nix-build -A openmoji-color

### Notify maintainers
@fgaz

**Comment by fgaz** [comment]
Could this be the same as #97871? Should we switch to prebuilt fonts here too?

**Comment by kevincox** [comment]
It could be. But in the past the build only took a minute or 2. Now it takes basically forever. I'm trying to bisect when this was introduced but bisecting timeouts is slow and error-prone.

**Comment by kevincox** [comment]
According to `git bisect` d41fcfc34e327d0c09fd0770e56d0de4bf357797 is the first bad commit. That isn't particularly helpful.

**Comment by kevincox** [comment]
I did a better bisection and got 69da642a5a9bb433138ba1b13c8d56fb5bb6ec05 (https://github.com/NixOS/nixpkgs/pull/163439) which seems likely.  I saw that PR but thought it seemed too old. I guess I forgot how long a staging cycle can take.

cc @evils @jtojnar @erictapen 

I don't know what the best approach here is. Report the bug upstream to fontforge or openmoji? There are a lot of warnings and errors in the build so I suspect that it may be an openmoji problem and fontforge was doing its best before and working but now is failing?

The command I used for reference was:

```
git bisect run zsh -c 'set -x; nix build -f . openmoji-color --max-silent-time 600 |& tee /tmp/out; [[ $pipestatus[1] == 0 ]] && exit 0; grep -- "-openmoji-.*timed out after .* seconds of silence" /tmp/out && exit 1; exit 125'
```

**Comment by evils** [comment]
after a brief look at this
fontforge has a reported regression in its ability to remove overlaps (https://github.com/fontforge/fontforge/issues/4859)
but if openmoji is the only font that is failing because of that, maybe they're relying too much on fontforge's abliity to fix things at build time

(with the latest master commits from openmoji and fontforge, the openmoji build also hangs)

**Comment by kevincox** [comment]
I tried diffing the logs but they are basically completely different once `scfbuild` starts. In case they are helpful to anyone here are the builds before and after that commit. (The after obviously cuts off after the "infinite loop").

[before.log](https://github.com/NixOS/nixpkgs/files/8457969/before.log)
[after.log](https://github.com/NixOS/nixpkgs/files/8457970/after.log)

**Comment by fgaz** [comment]
Great investigation!

Maybe as a short-term fix we could override fontforge for this package?

**Comment by kevincox** [comment]
That sounds like a reasonable mitigation until a patch is available.

**Comment by OPNA2608** [comment]
Bump, would really love to have openmoji available when I upgrade 21.11 -> 22.05!

**Comment by kevincox** [comment]
Bumping issues is not a helpful thing to do.

**Comment by fgaz** [comment]
In general yes, though in this case it reminded me to fix this before 22.05 :)

Here you go @OPNA2608: #174795

**Comment by jtojnar** [comment]
I tried running bisection on fontforge itself using [nix-bisect](https://github.com/timokau/nix-bisect) after applying the patch below:

```ShellSession
$ git bisect start 20220308 20201107
$ extra-bisect run \
  nix-build-status \
    --option max-silent-time 240 \
    -f ~/Projects/nixpkgs \
    openmoji-color
```

Unfortunately, the automatic bisection did not work for some reason. Possibly because the [timeout regex](https://github.com/timokau/nix-bisect/blob/3b18985913cf32e62f3a5d3f9ccafb507fed9080/nix_bisect/nix.py#L26) does not match the error message: `error: building of '/nix/store/6z3q2pb6frq47ch617nayaambb7rsyxa-openmoji-13.1.0.drv!out' from .drv file timed out after 240 seconds of silence`

```patch
--- a/pkgs/data/fonts/openmoji/default.nix
+++ b/pkgs/data/fonts/openmoji/default.nix
@@ -3,6 +3,10 @@
 , fetchFromGitHub
 , scfbuild
 , nodejs
+, fontforge
+, libuninameslist
+, fetchpatch
+, patch
 , nodePackages
 , python3Packages
 , variant ? "color" # "color" or "black"
@@ -14,6 +18,30 @@ let
     [ "OpenMoji-Color.ttf" "OpenMoji-Black.ttf" ]
     variant;
 
+    fontforge-bisect = fontforge.overrideAttrs (old: rec {
+      version = "bisect";
+      src = /home/jtojnar/Projects/fontforge;
+      patches = [
+        (fetchpatch {
+          url = "https://salsa.debian.org/fonts-team/fontforge/raw/76bffe6ccf8ab20a0c81476a80a87ad245e2fd1c/debian/patches/0001-add-extra-cmake-install-rules.patch";
+          sha256 = "u3D9od2xLECNEHhZ+8dkuv9818tPkdP6y/Tvd9CADJg=";
+        })
+        # (fetchpatch {
+        #   url = "https://github.com/fontforge/fontforge/commit/69e263b2aff29ad22f97f13935cfa97a1eabf207";
+        #   sha256 = "06yyf90605aq6ppfiz83mqkdmnaq5418axp9jgsjyjq78b00xb29";
+        # })
+      ];
+      prePatch = ''
+        patch() {
+          ${patch}/bin/patch "$@"  || echo 'Failed to apply patch, continuing'
+        }
+      '';
+      buildInputs = old.buildInputs ++ [ libuninameslist ];
+    });
+    scfbuild-with-fontforge-bisect = scfbuild.override (old: {
+      fontforge = fontforge-bisect;
+    });
+
 in stdenv.mkDerivation rec {
   pname = "openmoji";
   version = "13.1.0";
@@ -26,7 +54,7 @@ in stdenv.mkDerivation rec {
   };
 
   nativeBuildInputs = [
-    scfbuild
+    scfbuild-with-fontforge-bisect
     nodejs
     nodePackages.glob
     nodePackages.lodash
```

**Comment by Artturin** [comment]
needs to be reported upstream

**Comment by fgaz** [comment]
Which one though? Openmoji or fontforge?
