### ISSUE TITLE
Packaging request: fcitx5-skk

### ISSUE THREAD

**Issue by zer0-star** [NixOS/nixpkgs#167872]
**Project description**
fcitx5-skk is an input method engine for Fcitx5, which uses libskk as its backend.

It seems some of the fcitx5 engines (including fcitx5-skk) are missing. Probably the other engines also need to be added.

**Metadata**

* homepage URL:　https://github.com/fcitx/fcitx5-skk
* source URL:　https://github.com/fcitx/fcitx5-skk
* license: gpl3+
* platforms: linux

**Comment by Vonfry** [comment]
PR is wellcome.

What is `ENABLE_QT` for? Is it involved in fcitx5-qt?
