### ISSUE TITLE
Modeline configuration?

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#16789]
## Issue description

After running into a strange incident with my GPU misreporting the resolution of my monitor over VGA, I've had to [manually configure a modeline](https://wiki.archlinux.org/index.php/xrandr#Adding_undetected_resolutions) to get to the correct (1680x1050) maximum resolution, rather than 1024x768. The relevant section in my `configuration.nix` now looks like this:

``` nix
  services.xserver = {
    videoDrivers = ["intel"];
    resolutions = [{ x = 1680; y = 1050; } { x = 1024; y = 768; }];
    monitorSection = ''
      Modeline "1680x1050" 146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync
      Option "PreferredMode" "1680x1050"
    '';
  };
```

Would it perhaps be an idea to have a separate configuration option in the `xserver` service for custom Modelines, potentially even using `cwt` to determine the parameters from the resolution? This would make the process of dealing with misdetections quite a bit less error-prone and more obvious.
## Technical details
- System: NixOS 16.03.1028.0546a4a (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.1028.0546a4a

**Comment by Profpatsch** [comment]
Sorry that there was no reply?

Are you still interested in NixOS and would want to prepare a pull request for this? I can help if you have any questions.
