### ISSUE TITLE
xgboost: checkPhase demands GPUs when built with cudaSupport

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#167931]
The failing build: [[233]](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F0la8zlmdr0r6z700w8nc2dny3ji47fn3-xgboost-1.5.2.drv/log?via-job=bb35aaa9-52f1-4846-ba13-22a8f90c0ea3).

CC @NixOS/cuda-maintainers @abbradar

**Comment by samuela** [comment]
Is it possible for us to skip the failing test?

**Comment by SomeoneSerge** [comment]
Probably. Not sure when I can have a look
Also, I think we could start implementing GPU tests as nixosTests.
We'd have to run them ourselves, of course.

**Comment by samuela** [comment]
Yeah, I set up https://github.com/samuela/cuda-nix-testsuite/ to help with this, but if we can get them incorporated into nixosTests that's great too!

My goal with cuda-nix-testsuite is to eventually find someone with a compatible GPU and set up a GH Actions to run them on hardware... but maybe we could do that with official nixos tests as well? I'm not sure.

**Comment by samuela** [comment]
If there's nothing we can do to skip individual tests, then I guess we'll just have to turn on checkPhase for xgboost.
