### ISSUE TITLE
Pantheon with amdgpu-pro driver: xorg fails to start

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#167909]
### Steps To Reproduce
1. `services.xserver.desktopManager.pantheon.enable = true;`
2. `services.xserver.videoDrivers = [ "amdgpu-pro" ];`
3. Fatal server error

Full Xorg log: https://gist.github.com/davidak/fc9fcbc2b23c0b67a678443b79f30ded

### Expected behavior
Same as with amdgpu driver.

### Screenshots

![signal-2022-04-08-205904](https://user-images.githubusercontent.com/91113/163630778-a970629e-018e-4b44-a9e5-e376d3c89ab7.jpeg)

### Additional context
It works perfectly with amdgpu driver.

### Notify maintainers

@corngood asked for log in https://github.com/NixOS/nixpkgs/pull/151019#issuecomment-1001810016.

Can you have a look?

### Metadata

Build from unstable: 22.05pre367572.b6966d911da

Still reproducible with 22.05pre369524.5181d5945ed

**Comment by davidak** [comment]
>AMDGPU(0): [drm] Failed to open DRM device for pci:0000:03:00.0: No such file or directory

https://gist.github.com/davidak/fc9fcbc2b23c0b67a678443b79f30ded#file-amdgpu-pro-xorg-pantheon-crash-txt-L74

When i'm booted into NixOS stable i can confirm it is the right PCI BusID.

```
[root@gaming:~]# lspci
...
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] (rev c1)
```

So it's not the issue that is does not find the GPU or use the wrong (i have only 1, not even integrated).

**Comment by corngood** [comment]
Could you share `modinfo amdgpu`, `uname -a`, and `dmesg` here for reference?  I'd like to make sure it's actually loading the dkms amdgpu module, but I'm not 100% sure how to verify that.  It'll be a few days before I can test it myself to compare.

**Comment by davidak** [comment]
```
[root@gaming:~]# modinfo amdgpu
filename:       /run/booted-system/kernel-modules/lib/modules/5.10.109/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko.xz
version:        5.11.19.21.30
...
```

Full output: https://gist.github.com/davidak/c776f07586ea640f87a15df5f6cce35f

```
[root@gaming:~]# uname -a
Linux gaming 5.10.109 #1-NixOS SMP Mon Mar 28 07:57:11 UTC 2022 x86_64 GNU/Linux
```

dmesg: https://gist.github.com/davidak/def549a347bc29419e4f1f2c5adbd898

i see no issues there

```
× display-manager.service - X11 Server
     Loaded: loaded (/etc/systemd/system/display-manager.service; linked; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-04-08 20:57:56 CEST; 12min ago
    Process: 1338 ExecStartPre=/nix/store/147dr7c7vpsjy8sscpkv555lfxz46pyp-unit-script-display-manager-pre-start/bin/display-manager-pre-start (code=exited, status=0/SU>
    Process: 1343 ExecStart=/nix/store/wlvpba9p8g6mxskbkw41gzf27rqsr15n-unit-script-display-manager-start/bin/display-manager-start (code=exited, status=1/FAILURE)
   Main PID: 1343 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 133ms

Apr 08 20:57:56 gaming systemd[1]: display-manager.service: Scheduled restart job, restart counter is at 3.
Apr 08 20:57:56 gaming systemd[1]: Stopped X11 Server.
Apr 08 20:57:56 gaming systemd[1]: display-manager.service: Start request repeated too quickly.
Apr 08 20:57:56 gaming systemd[1]: display-manager.service: Failed with result 'exit-code'.
Apr 08 20:57:56 gaming systemd[1]: Failed to start X11 Server.
Apr 08 20:57:56 gaming systemd[1]: display-manager.service: Triggering OnFailure= dependencies.
```

display-manager-start:

```
#!/nix/store/ld19k12mf0pa42ff43qs3sizamp09f03-bash-5.1-p16/bin/bash
set -e
export PATH=/nix/store/91q8d0jhmxn34lgjhank3sg0brgns21k-lightdm-1.30.0/sbin:$PATH
exec /nix/store/91q8d0jhmxn34lgjhank3sg0brgns21k-lightdm-1.30.0/sbin/lightdm
```

**Comment by tomodachi94** [comment]
`amdgpu-pro` was removed by https://github.com/NixOS/nixpkgs/pull/320228. It was unmaintained.
