### ISSUE TITLE
Remove patches from mainline mutt

### ISSUE THREAD

**Issue by vrthra** [NixOS/nixpkgs#16802]
## Issue description

We already carry `neomutt` which is `mutt` with patches. The project provides a mechanism to enable or disable particular patches (although we do not enable it in the nix file). Can we cleanup the mainline `mutt` package so that it does not contain external patches? Currently, it offers no option to choose different patch sets, and in this sense it is equivalent to `neomutt` package. If we can remove the patches, we can also update the `mutt` package faster.  (See also #16772)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by matthiasbeyer** [comment]
While I do not use any patches with mutt personally, I think we should really be careful about this ... this would be a rather radical step and some mutt users might not be pleased to see this change.

Maybe we should even post to the ML to ask if all mutt users are okay with this. (IMHO)

**Comment by vrthra** [comment]
@matthiasbeyer I agree. We need not make this change immediately, and can leave it open for users to comment.

I am not really familiar with the mutt ML to know whether they would be open to a discussion on external patches. So, don't feel comfortable posting there.

**Comment by matthiasbeyer** [comment]
I meant the nixos-dev mailinglist... we should ask the nixos/nixpkgs users if its okay for them that we do not longer include patches for mutt in the nixpkgs mutt. The mutt-ml people wouldn't care, obviousely!

**Comment by vrthra** [comment]
@matthiasbeyer it [seems](https://dev.mutt.org/hg/mutt/rev/6f2fe8f32dab) the sidebar patch may be integrated to mainline mutt. If so, we can eliminate the patch and directly upgrade mutt. I am not sure if that is the case, and will wait until they have a release note.

**Comment by vrthra** [comment]
Closing this issue, since sidebar has been added to mutt, (https://dev.mutt.org/trac/ticket/3829).
