### ISSUE TITLE
Package Request: obs-vkcapture

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#168100]
**Project description**

Vulkan/OpenGL plugin for OBS.

**Metadata**

* homepage URL: https://github.com/nowrep/obs-vkcapture
* source URL: https://github.com/nowrep/obs-vkcapture
* license: gpl2
* platforms: linux

@jb55 @MP2E  @V 

I quickly threw together this:

```nix
{ config, lib, pkgs, stdenv, fetchFromGitHub, vulkan-headers, ... }:
let info = lib.importJSON ./version.json;
in
  with pkgs;
  stdenv.mkDerivation {
    pname = "obs-vkcapture";
    name = "obs-vkcapture";
    src = fetchFromGitHub {inherit (info) owner repo rev sha256;};

    nativeBuildInputs = [ cmake gcc vulkan-headers libGL obs-studio vulkan-loader pkg-config];
  }
```

Edit: Took me a we while to get it working locally,

looks like upstream mentions some issues with 32bit games:

https://github.com/nowrep/obs-vkcapture/issues/36

**Comment by ashkitten** [comment]
addressed by #169882
