### ISSUE TITLE
LUA_PATH and LUA_CPATH wrongly defined in prosodyctl

### ISSUE THREAD

**Issue by khoi-nguyen** [NixOS/nixpkgs#16816]
## Issue description

Prosody on master doesn't start because the `LUA_PATH` and `LUA_CPATH` variables aren't declared properly in `bin/prosodyctl`. Since the variables contain `?`, the strings must be quoted.

### Steps to reproduce

Just install Prosody on unstable and try to start the service.

## Technical details

* System: 16.09pre85931.125ffff (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre85931.125ffff

**Comment by khoi-nguyen** [comment]
I had a closer look at the issue and it seems that in the bash scripts `bin/prosodyctl`,
the `LUA_PATH` and `LUA_CPATH` variables are defined without quotation marks, which is problematic because the string contains a `?`.

**Comment by vcunat** [comment]
Since 3afa246 the variable definition is double-quoted in the resulting wrapper, and it seems fine to me. Unfortunately, the *nixos-unstable* channel is still stuck on your commit.

**Comment by khoi-nguyen** [comment]
Oh I see. Thanks!
