### ISSUE TITLE
Make stage 1 systemd options visible

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#168161]
Issue to track where we have options that are currently invisible because the initrd is not stable yet:
- [ ] nixos/modules/services/hardware/udev.nix
- [ ] nixos/modules/system/boot/systemd/initrd.nix
- [ ] nixos/modules/tasks/swraid.nix
- [ ] nixos/modules/tasks/lvm.nix

Warnings to emit:

- [ ] hibernation needs to be explicitly enabled
- [ ] LVM2 needs to be explicitly enabled
- [ ] swraid needs to be explicitly enabled

**Comment by LunNova** [comment]
Is stage 1 systemd ready for testing/feedback? Is there a discussion thread or channel somewhere?

Gave it a go and it doesn't work on this machine (hangs mounting root) but it also looks very WIP so I was not sure if it's worth raising an issue or looking for somewhere to ask for help.

**Comment by dasJ** [comment]
No, it's not ready for testing/feedback yet. There is #stage1systemd:helsinki-systems.de for development though

**Comment by xaverdh** [comment]
I assume this was done by https://github.com/NixOS/nixpkgs/pull/226237?

**Comment by ElvishJerricco** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/226237
