### ISSUE TITLE
vimPlugins.coc-haxe

### ISSUE THREAD

**Issue by Ashe** [NixOS/nixpkgs#168275]
**Project description**
Neovim plugin for CoC support with the `haxe` language.

**Metadata**

* homepage URL: https://github.com/vantreeseba/coc-haxe
* source URL: https://github.com/vantreeseba/coc-haxe
* platforms: linux

**Comment by DarkOnion0** [comment]
I'm working on it and I hope to be able to make the pull request tomorrow

**Comment by Ashe** [comment]
Awesome! Thank you! I appreciate it, it's not a massive issue since we can just download it from the extension sure in an impure way but it's nice have it in the config (and if we ever get a nice flake-based way of doing haxe development then this will be crucial for dev environments!)
