### ISSUE TITLE
broken GNOME Authenticator

### ISSUE THREAD

**Issue by nesnera** [NixOS/nixpkgs#168272]
### Describe the bug
Package ‘authenticator-4.0.3’ in /nix/store/a9y4fzm81l0pv0kp7dkrzp22c94wjkcm-nixos-21.11.335677.ceaca998029/nixos/pkgs/applications/misc/authenticator/default.nix:95 is marked as broken, refusing to evaluate.

### Steps To Reproduce
1. # nix-env -iA nixos.authenticator

### Notify maintainers

@dotlambda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.3, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.335677.ceaca998029"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
There hasn't been an upstream release in a long time: https://gitlab.gnome.org/World/Authenticator/-/tags
Feel free to ask upstream for a new release or use https://git.sr.ht/~martijnbraam/numberstation in the meantime.
