### ISSUE TITLE
Wireplumber: Failed to set scheduler settings

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#168276]
### Describe the bug
In the system journal I see: 
wireplumber[1489]: Failed to set scheduler settings: Operation not permitted

### Steps To Reproduce
Enable pipewire that uses wireplumber by default.

### Notify maintainers
 @K900 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0-zen1, NixOS, 22.05 (Quokka), 22.05.git.5ebdf31e93e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by K900** [comment]
That's not really a problem, but if you're doing pro audio, you may want to also enable rtkit, to allow Wireplumber (and Pipewire itself) to acquire hard realtime priority.

**Comment by QuantMint** [comment]
> That's not really a problem, but if you're doing pro audio, you may want to also enable rtkit, to allow Wireplumber (and Pipewire itself) to acquire hard realtime priority.

I am currenty using rtkit, with `security.rtkit.enable`

**Comment by K900** [comment]
Oh, that looks like it's actually a different warning that originates from here: https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gthread-posix.c#L1263

Either way this does not seem to be a problem, unless you're observing some other issue?

**Comment by QuantMint** [comment]
> Oh, that looks like it's actually a different warning that originates from here: https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gthread-posix.c#L1263
> 
> Either way this does not seem to be a problem, unless you're observing some other issue?

No, I am not getting any other issue.

**Comment by K900** [comment]
Then I'm just going to go ahead and close this - looks like it's a false alarm.

**Comment by wedens** [comment]
I think this is a related issue: https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/255
