### ISSUE TITLE
32 bits builds?

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#16829]
`nix-env -i irssi` builds `irssi` from source on a relatively slow i686 32 bits machine when subscribed to the 16.03 channel. I expected it to just download the binaries.

Is 32 bits not supported anymore?

**Comment by rasendubi** [comment]
As far, as I can tell, Hydra does build packages for i686 (irssi is [not an exception](http://hydra.nixos.org/build/37404334)).

Your issue may be caused by binary caches misconfiguration. Could you please post the content of `/etc/nix/nix.conf` here?

**Comment by 0xABAB** [comment]
```
build-cores = 2
build-max-jobs = 2
build-users-group = nixbld
```

**Comment by vcunat** [comment]
It's possible that particular build for your revision has failed on Hydra for some reason. (Sometimes we get transient failures like out-of-disk.)

**Comment by 0xABAB** [comment]
@vnucat Considering the amount of work involved in compiling e.g. gcc, as an end-user I would like to see a link to Hydra on stderr showing an URL to the build if it exists and otherwise something explicit like "You requested to install package foo from source as it is *not* supported by design on Hydra". 

I understand that in the general model there might be other caches, and there should probably be additional APIs, but if such features were available I would have actually known something and this issue wouldn't have required any diagnosis anymore. Additionally, there could be a popcon like system for detecting which packages are often installed and this could drive Hydra again, etc. 

Thanks for your replies; I don't really see why a release would exist (as in that an URL nixos.org/channels/<release> exist) *without* everything available on Hydra. Considering that "we" want Nix to be a higher standard than other systems, this is one of the properties which I would expect to hold. Breaking these kind of invariants breaks the user experience.

Is that too much to expect? Is there a particular reason why it's a bad idea to expect this?

**Comment by vcunat** [comment]
It would be nice to provide links to Hydra, but we don't have a negative binary caches (yet).

> I don't really see why a release would exist

We have a set of channel-critical builds that can block its update. It's not viable for any single failure to block the channel. Even now it's common that a channel won't update for a few weeks even though there are people trying to fix it up.

**Comment by domenkozar** [comment]
Irssi builds correctly on 32bit: http://hydra.nixos.org/job/nixos/release-16.03/nixpkgs.irssi.i686-linux

Please reopen this issue with more details., for example hash of derivation or the nix store being built and what nixpkgs revision was used.
