### ISSUE TITLE
Matrix (Chat) server DOWN

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#168364]
### Describe the bug

![Screenshot from 2022-04-12 10-00-40](https://user-images.githubusercontent.com/91113/162911354-2da8efa2-0174-403e-afa8-eb4f6d6da370.png)

### Steps To Reproduce
1. https://matrix.to/#/#community:nixos.org

**Comment by 7c6f434c** [comment]
This looks indistinguishable from Element's message about loss of connectivity to the homeserver you are using, not something about the NixOS infrastructure.

**Comment by davidak** [comment]
You are right, all rooms are affected. So matrix.org is DOWN. :grimacing:

**Comment by 7c6f434c** [comment]
Or, alternatively, your routing to matrix.org… They do not admit downtime on the status page, I can login with my matrix.org test account fine…

**Comment by 7c6f434c** [comment]
(I tried logging in via default Element Web from Germany, actually; if it is a routing issue, it's probably AS-dependent, of course…)
