### ISSUE TITLE
Package request: Frame

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#168384]
**Project description**
A privacy focused Ethereum wallet that runs natively on macOS, Windows and Linux

**Metadata**

* homepage URL: https://frame.sh/
* source URL: https://github.com/floating/frame
* license: gpl3
* platforms: unix

**Comment by 0xnook** [comment]
I made a simple derivation for their appimage and it works well for me, your can find it [here](https://github.com/0xnook/nookpkgs/blob/master/packages/frame.nix), can open a PR later after reviewing the contribution guidelines

**Comment by 0xnook** [comment]
Package got added by #175379
