### ISSUE TITLE
Jellyfin exits to homescreen won't play back

### ISSUE THREAD

**Issue by mkiljan** [NixOS/nixpkgs#168315]
## Issue description

Hi - I have Jellyfin and have everything on it and stream it from my apple laptop to my roku on two tv's with a mesh wifi system and an extra wifi adapter to the older 2012 macbook.
Everytime I get on to either tv- jellyfin will show up, but when I attempt to play anything, it will only play for a few minutes and then exit right back to the homescreen- happens with movies and tv shows- with everything

### Steps to reproduce
Turn tv on. Turn roku on. or vice versa- always on- click on jellyfin and then choose show, then stops working

## Technical details
I know this isn't the most technical question, but I can't resolve it and cannot find a way to fix it anywhere on the net. Thank you.
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by erictapen** [comment]
How are you running Jellyfin on an Apple Laptop? Is NixOS or Nix involved at any point?

**Comment by dbrgn** [comment]
This ticket can probably be closed due to inactivity, and because Nix doesn't seem to be involved 🙂
