### ISSUE TITLE
Libffi not found in Vagrant when trying to install plugins

### ISSUE THREAD

**Issue by Mayeu** [NixOS/nixpkgs#16837]
## Issue description

I am trying to install two plugin in vagrant: [vagrant-bindfs](https://github.com/gael-ian/vagrant-bindfs) and [vagrant-hostmanager](https://github.com/devopsgroup-io/vagrant-hostmanager).

I install them with the normal vagrant workflow, but it fails in both case with the following error:
```
...
An error occurred while installing ffi (1.9.13), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.13'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /nix/store/cfagzvhnhh4hql3pg8x9nx6ds135aa1l-vagrant-1.8.1/opt/vagrant/embedded/bin/ruby -r ./siteconf20160710-22557-czop3m.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
...
```

Manually checking the store, `ls /nix/store/cfagzvhnhh4hql3pg8x9nx6ds135aa1l-vagrant-1.8.1/opt/vagrant/embedded/lib/`, there is a libffi folder containing the headers (` /nix/store/cfagzvhnhh4hql3pg8x9nx6ds135aa1l-vagrant-1.8.1/opt/vagrant/embedded/lib/libffi-3.0.13/include/ffi`), it seems that Vagrant does not know where to look for it's embedded headers.

### Steps to reproduce

```
$ nix-env -iA nixos.vagrant
$ vagrant plugin install vagrant-bindfs
ERROR
$ vagrant plugin install vagrant-hostmanager
ERROR
```
## Technical details

* System: NixOS: 16.09pre85931.125ffff (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre85931.125ffff"

**Comment by Fuuzetsu** [comment]
confirming on current master, on 16.03; works fine on 15.09
