### ISSUE TITLE
Define a standard way/location for non-standard(eg. html) package documentation

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#1684]
We need to define stanard way and possible helper functions to install non standard documentation eg. generated html. Gentoo has helper functions like dodoc and dohtml, nixos could also have something like that too.

The other thing is defining a standard way to install package with or without documentation and i can't find an easy way, besides multiple outputs, which does not solve this problem nicely.

**Comment by domenkozar** [comment]
@offlinehacker let me know if you want to work on this, shouldn't be much.

**Comment by vcunat** [comment]
On the closure-size branch docs are split into a ``package.doc`` output. Some kinds of standard doc locations are even moved automatically by default (if you add the "doc" output).

**Comment by gilligan** [comment]
@vcunat @domenkozar can this issue be closed?

**Comment by gilligan** [comment]
*bump* can this be closed?
