### ISSUE TITLE
GNOME Settings: Hangs when clicking "Applications"

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#168419]
### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers
@NixOS/gnome 

### Metadata

Installer image from 2022-04-04.

**Comment by jtojnar** [comment]
We will need to backport GTK, see patch https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1732.
