### ISSUE TITLE
unable to lock screen in xfce

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixpkgs#16845]
## Issue description

It's not possible to lock screen in xfce unless "xlockmore" is installed.
### Steps to reproduce
1. Add `services.xserver.desktopManager.xfce.enable = true;` in configuration.nix
2. Login in XFCE and try to lock without success
3. `nix-env -i xlockmore` and then retry to lock
## Technical details
- System: NixOS Emu
- Nix version: 1.11.2
- Nixpkgs version: "16.03.973.8bf31d7"

**Comment by abbradar** [comment]
I think that's because there is no blessed lock screen for XFCE. `xflock4` tries XScreenSaver, GNOME Screensaver, XLock and SLock -- in that order.

**Comment by zarelit** [comment]
Has a situation like this (multiple optional but at least one required dependency on an executable) already been handled in NixOS?

**Comment by abbradar** [comment]
I think this is generally resolved by some kind of switch, but we have to add one. Something like `services.xserver.displayManager.xfce.screenLock` of `types.enum`...

**Comment by zarelit** [comment]
I kept `slock` as-is: see #22532

**Comment by novoid** [comment]
I think the issue may be resolved.

At least with [my setup ](https://github.com/novoid/nixos-config) (as of 2023-09-17) lock screen is possible without having `xlockmore` installed.
