### ISSUE TITLE
nixpkgs-unstable: update as of today (14 Apr 22) fails due to missing lib.utils

### ISSUE THREAD

**Issue by amazari** [NixOS/nixpkgs#168569]
update as of today (14 Apr 22) fails due to missing lib.utils
`
error: attribute 'utils' missing

       at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/services/x11/desktop-managers/gnome.nix:458:9:
          457|         with pkgs.gnome;
          458|         lib.utils.removePackagesByName
             |         ^
          459|           ([
`

I suspect that the big Gnome 42 merge depends on a newly introduced util function in the namespace lib.utils. For some reason lib, on my current system, do not expose an 'utils' attributes set.

**Comment by bobby285271** [comment]
The issue is likely introduced in #168194.
