### ISSUE TITLE
restartIfChanged doesn’t seem to work for user services

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#16851]
e.g. for the following user service file:

```nix
      systemd.user = {
        services.pulseaudio = {
          description = "PulseAudio Server";
          # NixOS doesn't support "Also" so we bring it in manually
          wantedBy = [ "default.target" ];
          serviceConfig = {
            Type = "notify";
            ExecStart = binaryNoDaemon;
            Restart = "on-failure";
          };
          restartIfChanged = true;
        };
```

I would expect `journalctl --user -f` to output that `pulseaudio.service` was restarted if I change anything in the pulseaudio derivation, which it doesn’t. Neither does `sudo journalctl -f`.

**Comment by anderspapitto** [comment]
https://github.com/NixOS/nixpkgs/issues/7326 probably needs to be fixed first

**Comment by Profpatsch** [comment]
@anderspapitto Yes, same problem, only with reload. Of course both should be solved.
