### ISSUE TITLE
Upgrade to go 1.18 by default for 22.05

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#168534]
### Describe the bug

Only the last two go releases will receive security updates. Therefore we should at least the latest release to not have an unsupported go version before the next nixos release: https://go.dev/doc/devel/release

**Comment by mweinelt** [comment]
It can be expected from https://go.dev/doc/devel/release that the next release is due around 2022/08 or 2022/09, so 1.17 will become somewhat problematic in NixOS 22.05.

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/164320

**Comment by mweinelt** [comment]
I think it's fair to leave this open until the linked PR is actually merged. It will autoclose as soon as it happens, better to track these blockers.

**Comment by dasJ** [comment]
I'd like to remind the people here that branch-off is scheduled for tomorrow and depending on how good the staging builds progress, we will branch off rather soon.

**Comment by mweinelt** [comment]
It seems like we'll be heading for a branch-off without this critical separation from the soon to be EOL 1.17 release.

- 1.16 needs to be removed
- The default needs to migrate to 1.18

CCing golang team:
- @c00w 
- @cstrahan 
- @Frostman 
- @kalbasit 
- @Mic92 
- @orivej 
- @rvolosatovs 
- @zowoq

**Comment by Mic92** [comment]
Now only the 1.18 is remaining.

**Comment by mweinelt** [comment]
@Mic92 Do you have any plans to tackle this? I think we can still accept the change until the end of the month.

**Comment by mweinelt** [comment]
If noone steps up shortly we will likely end up with an EOL golang version as the default version mid-release.

**Comment by dasJ** [comment]
Since this doesn't appear to be solved, does anyone have objections to remove it as a release blocker?

**Comment by zowoq** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/179622

**Comment by dasJ** [comment]
For sake of completeness when somebody stumbles upon this: this PR never went into 22.05
