### ISSUE TITLE
[21.11] Can't Compose Email in Evolution (WebKitGtk issue)

### ISSUE THREAD

**Issue by blitz** [NixOS/nixpkgs#168645]
### Describe the bug

Since the webkitgtk update in #167920, Evolution is broken. The window for composing emails is not showing any content anymore: 

Reverting #167920 fixes the issue for me. Unfortunately, this was a security update. Now the problem is that either Evolution is insecure or non-functional...

There is an upstream issue [here](https://gitlab.gnome.org/GNOME/evolution/-/issues/1869).

### Steps To Reproduce

1. Open evolution and try to compose an email

### Expected behavior

Composing an email in Evolution works.

### Screenshots

https://user-images.githubusercontent.com/37907/163428507-a1a745ae-751f-43e5-8a8a-1667f0ae2c5d.mp4

### Additional context

Upstream issue: https://gitlab.gnome.org/GNOME/evolution/-/issues/1869

### Notify maintainers

@NixOS/gnome 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.337040.a62ce97f92b, nixos-hardware, nixos-unstable-22.05pre369117.ff9efb0724d, tuxedo"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
I am unable to reproduce when running evolution from 5db92536331da585eafa2aa55ce232ac900c9e9d:

![Evolution compose](https://user-images.githubusercontent.com/705123/163435388-9c2ac904-9ca5-4901-873d-f0611ec6ebc4.png)

Could you perhaps try to run `G_MESSAGES_DEBUG=all evolution` in the command line and see if anything sticks out?

And maybe also https://trac.webkit.org/wiki/WebKitGTK/Debugging#Loggingsupport.

**Comment by jtojnar** [comment]
Oh, this is on 21.11, could you try to update to [3.42.4](https://gitlab.gnome.org/GNOME/evolution/-/tags/3.42.4) first?

**Comment by hmenke** [comment]
I can confirm this issue on NixOS 21.11. Actually, just typing in the window *does* work, but you can't see what you're typing. Also composing in an another editor using the External Editor plugin works fine.

![Screenshot from 2022-04-14 19-45-39](https://user-images.githubusercontent.com/1903556/163447578-6edaa56c-bdc1-4604-9fe8-7f97d42e208d.png)

**Comment by blitz** [comment]
> Oh, this is on 21.11, could you try to update to [3.42.4](https://gitlab.gnome.org/GNOME/evolution/-/tags/3.42.4) first?

I've updated to 3.42.4 and the issue persists. Downgrading webkitgtk resolves the issue. :(

**Comment by blitz** [comment]
> Could you perhaps try to run G_MESSAGES_DEBUG=all evolution in the command line and see if anything sticks out?

I see nothing related to the broken message window, unfortunately.

**Comment by blitz** [comment]
@jtojnar 

> I am unable to reproduce when running evolution from https://github.com/NixOS/nixpkgs/commit/5db92536331da585eafa2aa55ce232ac900c9e9d

This looks like a commit on master. Recent release-21.11 should trigger the bug.

**Comment by jtojnar** [comment]
It might also be the compositing issue again, could you try the fix from https://github.com/NixOS/nixpkgs/issues/32580#issuecomment-350877197, running it with `env WEBKIT_DISABLE_COMPOSITING_MODE=1 evolution`.

**Comment by blitz** [comment]
@jtojnar You are my personal hero today! This works. Will add this to the upstream ticket in Evolution.

The weird thing is that I don't have an nvidia GPU like people in the referenced issue, but boring Intel iGPU.

What is the path forward here? Wrapping evolution to always set this environment variable?

**Comment by jtojnar** [comment]
Proper fix would probably need to be done in webkitgtk.

**Comment by hmenke** [comment]
I made a copy of `org.gnome.Evolution.desktop` in `~/.local/share/applications/` and replace all `Exec=` lines with `Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 `. Quick and dirty workaround.

**Comment by blitz** [comment]
Given that this happens on the release branch, I would propose to just disable compositing by default. It seems that this was enabled by the webkitgtk update.

**Comment by blitz** [comment]
@hmenke Can you test  #169058?

**Comment by hmenke** [comment]
Oof, rebuilding WebKit :unamused: Let's see if that's possible in reasonable time.

**Comment by blitz** [comment]
With https://github.com/NixOS/nixpkgs/pull/169170 merged, I think we can close this. :)

**Comment by jtojnar** [comment]
42.1 disables the HW acceleration https://gitlab.gnome.org/GNOME/evolution/-/commit/eb62ccaa28bbbca7668913ce7d8056a6d75f9b05
