### ISSUE TITLE
Weird extendModules behaviour when used inside a submodule

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#168767]
### Describe the bug

When `extendModules` is used inside a submodule, strange collisions / "not defined" errors can happen

### Steps To Reproduce
1. From this flake:

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs";
  outputs = {
    self,
    nixpkgs,
  }:
    with nixpkgs.lib; {
      lib.thing = evalModules {
        modules = [
          ({
            lib,
            extendModules,
            ...
          }: {
            options.sub = mkOption {
              default = {};
              type = types.submodule ({
                config,
                extendModules,
                ...
              }: {
                options.value = mkOption {
                  type = types.int;
                };

                options.specialisation = mkOption {
                  default = {};
                  inherit
                  (extendModules {
                    modules = [{specialisation = mkOverride 0 {};}];
                  })
                  type
                  ;
                };
              });
            };
          })
          {config.sub.value = 1;}
        ];
      };
    };
}

```

2. If we do `nix eval '.#lib.thing.config.sub.specialisation.value'`, we get:

```
error: The option `sub.specialisation.value' is used but not defined.
```

3. But if we add `{config.sub.specialisation.value = mkDefault 2;}` to the modules of `evalModules`, we get:

```
1
```

So from my understanding it wrongly assumes that the option isn't defined since it's not defined at the local level, but if defined locally still gets the global value afterwards.

4. Weirdly enough, if we add `{config.sub.specialisation.value = 2;}` instead (without the `mkDefault`), we get:

```
error: The option `sub.specialisation.value' has conflicting definition values:
       - In `<unknown-file>': 1
       - In `<unknown-file>': 2
```

But doing it in the same module as the setting of `config.sub.value` doesn't yield this error, and correctly reports back 2.

### Expected behavior

- Just setting `config.sub.value = 1` should be enough for `sub.specialisation.value == 1`.
- Also setting `config.sub.specialisation.value = 2` either in the same module or in another one should set the specialised value to 2.

### Additional context

The usecase I have for this is that I'm developing a deployment tool. At the top-level we define an attrset of nodes, whose configurations are submodules. I would like to have specialisation support at the node level, and came across `extendModules` by reading how NixOS does it.

### Notify maintainers

@roberth as the creator of `extendModules` (thank you a lot for that, by the way!)

### Metadata

N/A

**Comment by minijackson** [comment]
Linking #143207 in case someone has the same problem.

**Comment by roberth** [comment]
> 3\. If we do `nix eval '.#lib.thing.config.sub.specialisation.value'`, we get:
> 
> ```
> error: The option `sub.specialisation.value' is used but not defined.
> ```

This is the part that's broken.
When I tried to turn this into a `lib/tests/modules.sh` test case, it worked as expected. More on that later.

It seems that this bug has warped your understanding of the `extendModules` feature. It is supposed to include all configuration.

Observations so far

 - putting the  `evalModules` `modules` in separate files fixes `sub.specialisation.value`
 - putting the two `evalModules` `modules` in the `imports` of a single module does not fix the problem
 - putting the two `evalModules` `modules` in the `imports` in flipped order does not fix the problem
 - putting the two `evalModules` `modules` in the `imports` and `_file = "x"` to one of the modules does fix the problem
 - putting `_file = "x"` in the submodule fixes the problem 

Probably cause: some anonymous module is not assigned a unique key and is lost in `imports` closure resolution, which simultaneously deduplicates multiply imported modules.

**Comment by roberth** [comment]
I've drafted https://github.com/NixOS/nixpkgs/pull/168778. Will revisit later.

**Comment by roberth** [comment]
@minijackson I've merged the fix. Could you check that Nixpkgs master works for your original problem?

**Comment by minijackson** [comment]
I don't have my "original" original problem at hand since I worked around the issue, but I tested the code from the issue which I think represented the original problem quite well, so I'm confident it solves this issue. Thanks a lot!
