### ISSUE TITLE
wire-desktop fails to build

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#168765]
### Describe the bug
`wire-desktop` fails to build due to a missing shared-object dependency.

### Steps To Reproduce
1. Have the channel `nixpkgs` pointing to https://nixos.org/channels/nixpkgs-unstable in the user environment
2. Run `nix-build '<nixpkgs>' -A wire-desktop`
3. The build will fail with the error `error: auto-patchelf could not satisfy dependency libxshmfence.so.1 wanted by /nix/store/9lzm4sfmwmxa36islpfwzg0lzs4p863a-wire-desktop-3.27.2944/opt/Wire/wire-desktop`

### Expected behavior
For `wire-desktop` to build successfully.

### Notify maintainers

@arianvp @Kiwi @toonn 

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/jx971k1cp21nfb842jwy4camssl3k6l6-nix-info
copying path '/nix/store/jx971k1cp21nfb842jwy4camssl3k6l6-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.109, NixOS, 21.11 (Porcupine), 21.11.20220409.db81927`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(aidan): `"home-manager, nixpkgs-22.05pre369462.d08394e7cd5"`
 - channels(root): `"nixos-21.11.336755.efea022d6fe, home-manager-21.11.tar.gz"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by arianvp** [comment]
Cc @flokli

**Comment by flokli** [comment]
This was fixed in https://github.com/NixOS/nixpkgs/pull/168653, no?
