### ISSUE TITLE
bad test for stage-2 existence in stage-1 init script?

### ISSUE THREAD

**Issue by akavel** [NixOS/nixpkgs#16870]
## Issue description

In [stage-1-init.sh, l.465](https://github.com/NixOS/nixpkgs/blob/963327aacb67322c8cc1ace863e7747823aa89e0/nixos/modules/system/boot/stage-1-init.sh#L465), there's a condition:

``` bash
if ! test -e "$targetRoot/$stage2Init" -o ! -L "$targetRoot/$stage2Init"; then
```

which is equivalent to:

``` bash
if ! (test -e "$targetRoot/$stage2Init" -o ! -L "$targetRoot/$stage2Init"); then
# per De Morgan's laws, equivalent to:
if test ! -e "$targetRoot/$stage2Init" -a -L "$targetRoot/$stage2Init"; then
```

Shouldn't that be rather one of below (all equivalent), taking into account the [comment in l.464](https://github.com/NixOS/nixpkgs/blob/963327aacb67322c8cc1ace863e7747823aa89e0/nixos/modules/system/boot/stage-1-init.sh#L464)?

``` bash
if test ! -e "$targetRoot/$stage2Init" -a ! -L "$targetRoot/$stage2Init"; then
if ! test -e "$targetRoot/$stage2Init" -o -L "$targetRoot/$stage2Init"; then
if ! (test -e "$targetRoot/$stage2Init" -o -L "$targetRoot/$stage2Init"); then
```

To see those are not the same, [run](http://goo.gl/PC9TUU):

``` bash
$ for a in "" a; do
>   for b in "" b; do
>     echo -ne "$a\t$b\t"
>     (! test "$a" -o ! "$b") && printf T || printf F
>     (! (test "$a" -o ! "$b") ) && printf T || printf F
>     (test ! "$a" -o ! "$b") && printf T || printf F
>     printf "\n"
>   done
> done
        FFT
    b   TTT
a       FFT
a   b   FFF
```
### Steps to reproduce
1. in /etc/nixos/configuration.nix, add:  
   `boot.kernelParams = [ "init=not-existing-path" ];`
2. `$ nixos-rebuild switch -p testboot`
3. `$ shutdown -r now`
4. **kernel panic**
### Expected result
- instead of kernel panic:
  
  ```
  stage 2 init script (.../not-existing-path) not found
  
  An error occurred in stage 1 of the boot process, which must mount the
  root filesystem on \`$targetRoot' and then start stage 2.  Press one
  of the following keys:
  
    r) to reboot immediately
    *) to ignore the error and continue
  ```
## Technical details
- System: 16.09pre84674.fbde3a7 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre84674.fbde3a7"

**Comment by FRidh** [comment]
@aszlig @domenkozar you're into the NixOS tests, right?

**Comment by domenkozar** [comment]
I can confirm the issue, I've hit this a few times.

**Comment by Profpatsch** [comment]
(triage) still a problem?
