### ISSUE TITLE
Neovide failes in mixed glibc configuration

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#168769]
### Describe the bug

If you run NixOS 21.11 which uses glibc version 2.33 and want to run neovide from nixon-unstabled which is compiled with glibc version 2.34, then neovide failes to start.

Glibc 2.34 was introduced with https://github.com/NixOS/nixpkgs/pull/133431

### Steps To Reproduce

```
$ neovide --nofork
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([OsError("Could not create EGL display object"), OsError("`glXQueryExtensionsString` found no glX extensions")])', src/window/mod.rs:331:10
```

### Expected behavior

The application starts.

### Notify maintainers

I am the maintainer.

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.2-xanmod1-tt, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/store/l5lbpfccaxn6scvkaawj5hhi13if8d6q-source`
```

**Comment by teto** [comment]
can we close this ?

**Comment by SuperSandro2000** [comment]
Would be my call, too since mixed glibc is normally out for trouble.

**Comment by dccsillag** [comment]
Would be nice if there was some workaround out there first (something like overriding the glibc used?). At the end of the day, this issue means that I'm having to run an old and somewhat buggy version of neovide, whereas unstable has a much more solid one.

Nevertheless, I understand that this is tricky and likely won't have a definite solution.

**Comment by pca006132** [comment]
Just wondering, if there is a convenient way to use the package source in unstable but evaluate using other channels? The way I'm doing this right now is to copy the file `neovide/default.nix` and `neovide/skia-externals.json` locally, do some modification and import it. This works perfectly but perhaps there is a simpler way?

**Comment by ck3d** [comment]
I close this issue, since it is more general issue.
