### ISSUE TITLE
SteamVR does not work

### ISSUE THREAD

**Issue by wizardwatch** [NixOS/nixpkgs#168809]
### Describe the bug
On recent builds of NixOS unstable, SteamVR fails with the error "A key component of SteamVR isn't working properly." and the error code 307. Reverting back to an old build with Kernel 5.10 works, so it may be related to the kernel version. I tried updating to the latest kernel, both zen and vanilla based on https://gitlab.freedesktop.org/drm/amd/-/issues/1856, but this did not resolve the issue. I use an amd 5700xt for my GPU.

### Steps To Reproduce
1. Install Steam from latest unstable
2. Launch SteamVR with valve index

### Expected behavior
SteamVR works without issue.

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220411_f7276bc`
 - channels(wyatt): `"nixos-21.05pre281538.9e377a6ce42"`
 - channels(root): `"nixos-21.05pre290427.673aea9f84c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Atemu** [comment]
@wizardwatch are you still unable to run SteamVR? It's working for me.

**Comment by Atemu** [comment]
Played Beat Saber just yesterday.
