### ISSUE TITLE
coreutils 9.1

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#168901]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: coreutils

current version: 9.0
desired version: 9.1

###### Notify maintainers

maintainers: @dasJ 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by dasJ** [comment]
I'm already on it :) might take some while before I do the pr because I want to build stdenv first
