### ISSUE TITLE
timesyncd on 16.03

### ISSUE THREAD

**Issue by butterflya** [NixOS/nixpkgs#16894]
```
timedatectl status 
Failed to query server: Connection timed out
```
There are multiple things wrong here; it doesn't show to *which* server it tries to connect, it doesn't say how long it tried to connect (i.e., what the timeout value is). Probably all upstream problems. 

The only relevant configuration is:

```
services.timesyncd.enable = true;
```

systemd-timesyncd is running according to a process listing. 

journalctl shows

```systemd-timedated: /etc/localtime should be a symbolic link to a time zone data file in /usr/share/zoneinfo/```

This seems to indicate that the timesyncd module is not written correctly.

**Comment by fuzzy-id** [comment]
Apart from the `/etc/localtime should be symbolic link […]` message I also see this in my journal:
```
Failed to determine whether NTP is enabled: Too many levels of symbolic links
```
To me it looks like the latter is the critical point of failure.

**Comment by fuzzy-id** [comment]
I don't get this issue anymore since upgrading to NixOS 16.09.
