### ISSUE TITLE
[Security] 16.03 ntpd vulnerable 

### ISSUE THREAD

**Issue by butterflya** [NixOS/nixpkgs#16892]
See https://www.kb.cert.org/vuls/id/321640

4.2.8p8 is available upstream, you are shipping 4.2.8p6. 

If openntpd offers the same features as a simple configuration for ntpd, perhaps it would be better to steer people towards using openntpd. If there are no must have features in ntpd, I would like to see a complete deprecation of ntpd as I have the impression that openntpd actually is better. 

The first issue is a technical issue; the second is more open to debate. For something as fundamental as ntpd, I'd like to see automated packaging too. I.e., there is no reason why there shouldn't be a package available for the latest *stable* version of ntpd within one hour after publication (it just requires polling their website every hour).

**Comment by joachifm** [comment]
As concerns NixOS, I get the impression timesyncd is/will be the preferred ntp client.

**Comment by butterflya** [comment]
openntpd doesn't seem to have a version command line option. :/

**Comment by butterflya** [comment]
@joachifm timesyncd doesn't appear to work in NixOS 16.03:

```systemd-timedated[26384]: Failed to determine whether NTP is enabled: Too many levels of symbolic links```

**Comment by joachifm** [comment]
@butterflya how did you use it?

**Comment by butterflya** [comment]
@joachifm I just opened https://github.com/NixOS/nixpkgs/issues/16894, which I can actually reproduce. It might be the exact same issue.

**Comment by fpletz** [comment]
My personal preference is chrony, which should work fine with the nixos module: `services.chrony.enable = true;`

**Comment by butterflya** [comment]
@fpletz Chrony seems to have a worse trackrecord than openntpd: https://www.cvedetails.com/vulnerability-list/vendor_id-10533/product_id-18821/Tuxfamily-Chrony.html 

I switched back to openntpd.

**Comment by fpletz** [comment]
Oh, just remembered. I fixed that a few days ago ;) f57c4b5aac648c88807328576e5ce1575a472e7b
