### ISSUE TITLE
vimPlugins.coq_nvim needs aditional handling

### ISSUE THREAD

**Issue by lucasew** [NixOS/nixpkgs#168928]
### Describe the bug
The plugin definition is generated by a script but the way it works requires some extra handling.

It depends on some other python libs and requires patching to write state outside of the nix store.

I got it working on [my config](https://github.com/lucasew/nixcfg/tree/master/packages/custom/neovim). 

I would like to upstream those alternative techniques to benefit more people but I don't know what file to change and how to pass extra python packages to the target neovim. 

Another discussion that would help is where to store the files that would be stored otherwise in the .var folder.

### Steps To Reproduce
1. Just add coq_nvim to your neovim configuration and run `:COQnow` and you will see the problem

### Expected behavior
Plugin working out of the box from the nixpkgs build

### Additional context
- [My neovim config with the fixes](https://github.com/lucasew/nixcfg/tree/master/packages/custom/neovim)

### Notify maintainers

@teto @TomHotston 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
lucasew@acer-nix ~ 0$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - nixpkgs: `/nix/store/j4n45y0r4ybms9vz64wisbffq7hbf78q-source`
```

**Comment by teto** [comment]
If you have to patch the plugin, you should communicate with upstream to see how to work around that.
any additionnal dependency can be set in pkgs/applications/editors/vim/plugins/overrides.nix .

Remain the python dependencies to add to the neovim provider: I dont know how to automate that part, at least there is no system in place. Maybe we should just add the plugins as neovim's wrapper's dependencies and add any python dependency to neovim's python provider.

**Comment by lucasew** [comment]
What about using `propagatedBuildInputs` for the python dependencies of the plugins? Is this already supported by the wrapper?

**Comment by teto** [comment]
I dont think it would work. Feel free to experiment. The neovim wrapper is low-level, but in neovim/utils.nix one can provide higher-level interfaces.

What I wanted to do is provide an interface similar to home-manager's in `makeNeovimConfig` by passing a list of plugins:
```
    # expects a list of plugin configuration
    # expects { plugin=far-vim; config = "let g:far#source='rg'"; optional = false; }
    , plugins ? []
 ```
 it should be doable then to collect the plugins python dependencies and add them to the python provider of neovim.

**Comment by icyphox** [comment]
FYI, setting the `g.coq_settings.xdg` option to `true` solves this problem (it doesn't try to install deps to the nix store).

**Comment by lucasew** [comment]
Got it working by using @icyphox solution, now dismounting the patch workaround  (aka reproducible workaround) that I did to make it working. Thank you!
