### ISSUE TITLE
exaile fails to start: "python3: not found"

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#169031]
### Describe the bug
The program `exaile` does not launch, because it cannot find python.

### Steps To Reproduce
1. Set the user channel `nixpkgs` to `https://nixos.org/channels/nixpkgs-unstable`
2. Run `nix-shell -p exaile --run exaile`

This will output,
```console
/nix/store/aaaa....-exaile-4.1.1/bin/..exaile-wrapped-wrapped: line 14: exec: python3: not found
````

### Expected behavior
For the GUI application Exaile to launch.

### Notify maintainers

@ryneeverett

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.111, NixOS, 21.11 (Porcupine), 21.11.20220415.278ecd2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(aidan): `"home-manager, nixpkgs-22.05pre369575.0b43a436fbb"`
 - channels(root): `"nixos-21.11.336755.efea022d6fe, home-manager-21.11.tar.gz"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by ryneeverett** [comment]
I cannot reproduce. The gui launches without error for me when I follow the above steps.
