### ISSUE TITLE
caddy service: logging output

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#16905]
## Issue description

caddy don't start. there is some issue with the configuration.

journalctl -u caddy.service

```
Jul 13 04:17:01 binary systemd[1]: Started Caddy web server.
Jul 13 04:17:01 binary systemd[1]: caddy.service: Main process exited, code=exited, status=203/EXEC
Jul 13 04:17:01 binary systemd[1]: caddy.service: Unit entered failed state.
Jul 13 04:17:01 binary systemd[1]: caddy.service: Failed with result 'exit-code'.
```

not very helpful.
when i start it manually i get:

```
[root@binary:/var/www/aww/web]# caddy -conf=/nix/store/2cr5nf5g8vwgiabppxlfhg17jm4qpr1m-Caddyfile -email=post@davidak.de
Activating privacy features...2016/07/13 04:16:16 [aww.binary.lan.davidak.de] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for exact set of domains: aww.binary.lan.davidak.de
```

please log this kind of output to journald.
cc @angus-g
## Technical details
- System: nixos-version

```
/run/current-system/sw/bin/nixos-version: line 7: syntax error near unexpected token `)'
/run/current-system/sw/bin/nixos-version: line 7: `  --hash|--revision)'
```

(NixOS 16.09.git.dde259d)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre83796.d541e0d"

**Comment by myguidingstar** [comment]
Mainstream has already implemented systemd script. This should be adapted to nix package.
https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd

**Comment by mogorman** [comment]
in you config you can set log syslog which should put the dbug informaiton where you need it @davidak

**Comment by fpletz** [comment]
This is not an issue with caddy but with systemd/journald unfortuntely. I've seen similar issues with other services sometimes but wasn't able to find out what causes this. We cannot fix this and have to wait for a fix in systemd. We recently bumped systemd to 237, maybe it's fixed.

Closing for the meantime due to its age.
