### ISSUE TITLE
Fail2ban support for pyinotify

### ISSUE THREAD

**Issue by aopom** [NixOS/nixpkgs#169131]
Fail2ban [needs the pyinotify or gamin module](https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L117=) to achieve better performance when reading log files.

**Comment by peterhoeg** [comment]
While this doesn't do anything to address your specific issue, `sshguard` is pretty efficient and does (almost) everything `fail2ban` does.

**Comment by aopom** [comment]
Thanks for the tip, I'll look at it!
*The linked PR actually addresses my specific issue, so all is good*
