### ISSUE TITLE
ddclient with ssl = true fails to connect

### ISSUE THREAD

**Issue by butterflya** [NixOS/nixpkgs#16914]
```
verify failed SSL connect attempt failed error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```

Exact same configuration with ssl = false does work. 

NixOS 16.03

**Comment by layus** [comment]
I am replying from Vietnam, with my smartphone, so please excuse terseness.

This error alone can mean many things.

It could happen that the certificate *is* invalid. Have you tried to access the underlying HTTPS URL ?

Now, the issue could be related to changes in providing the default trust store location. You can read the PR and issues related to that. You posted into one I think.

I assume you use NixOS.

Could you check that

1. You can reproduce the issue when running the service command in a shell (use systemd cat ddclient... )
2. Verify the server certificate using openssl directly (use the openssl command and a good search engine *smile*)


If, as I expect, you get the error with 1 but not with 2, then some perl module in the use chain is trying to outsmart another.

could you also report all the environment variables containing SSL ? Like `env | grep SSL` ?

**Comment by rycee** [comment]
@butterflya, I used to have this exact problem and managed to resolve it by fixing the `IO::Socket::SSL` Perl module to use the `/etc/ssl/certs/ca-certificates.crt` path for the SSL certificates (in the commit that @layus correctly identified above).

This change went in to the 16.03 branch on June 17 so perhaps you haven't updated your 16.03 installation for a while?

**Comment by rycee** [comment]
@butterflya, please confirm whether you still have the issue with an up to date 16.03 channel.

**Comment by butterflya** [comment]
I do not.

**Comment by rycee** [comment]
Great, thanks!
