### ISSUE TITLE
wiki: Add deprecation banner to all pages

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#16918]
## Issue description
The wiki itself should have clearer messages about the deprecation that's going on. The homepage should say at least 
 1. That you can't edit/add anything because of the freeze 
 2. That the wiki is being migrated to this repo
 3. How someone might contribute to the migration

### Steps to reproduce
Visit https://nixos.org/wiki/Main_Page

## Technical details

* System: any
* Nix version: any
* Nixpkgs version: any

**Comment by siddharthist** [comment]
This issue belongs in the "Move the wiki!" milestone. Pinging @garbas since you seem to be on top of that one :)

**Comment by garbas** [comment]
@edolstra @rbvermaa would it be possible to edit Main_Page on the wiki?
@siddharthist good point. i guess we need to come up with some nice description of what is going on. below is my try at that. any help appreciated.

-----

NixOS wiki is currently being migrated to respected manual (links to manuals).
For the time of migration nixos wiki is running in read only mode.

If you wish to help please select a ticket from [Move the wiki!](https://github.com/NixOS/nixpkgs/milestone/8) milestone.

-----

does it make it clearer?

**Comment by siddharthist** [comment]
@garbas I think we should make it clear that the wiki will be deactivated as well. Here's my idea (much the same as yours):

> The NixOS wiki is being shut down. Content is being migrated into the NixOS Manual [link]. If you wish to add or improve content, please grab a ticket from the Move the wiki! [link] milestone.

**Comment by copumpkin** [comment]
More than the front page (which I doubt many people check), it seems worth adding some sort of prominent banner to all pages. Without that, people hitting the wiki from google (I'd expect 99% of cases) won't notice the change. I know mediawiki supports banners because I see Jimmy Wales on it for a few weeks every year 😄

**Comment by joepie91** [comment]
FWIW, I've found the wiki *considerably* more useful in my process of learning Nix than the manual, in part because the wiki has things split up by topic, and this makes it more easily searchable.

If the wiki is migrated to the manual wholesale without changing the one-page-for-the-entire-thing idea, then that's probably going to have a negative result on accessibility for users.

**Comment by garbas** [comment]
@joepie91 only once wiki is migrated then we can start talking about how to shape manual to be more user friendly. if this mean 100 small tutorials then so be it nobody, but a common thing to all those efforts is that current wiki content needs to moved.

**Comment by joepie91** [comment]
@garbas That will make documentation disappear for users (from their perspective) in the meantime, though, and that doesn't seem like a good approach.

I'd suggest the following instead:

1. Add a global deprecation warning to the wiki ("this information might be outdated", etc.)
2. Work out how to restructure the documentation to be more searchable and manageable (is there an issue for this already?)
3. Actually remove the wiki

That would keep users from relying on inaccurate information, and at the same time make sure that the availability of documentation doesn't *worsen* for a period of time,

**Comment by garbas** [comment]
@joepie91 

1. :+1: just somebody has to submit a PR (here)[https://github.com/NixOS/nixos-org-configurations/blob/master/nixos-org/webserver.nix]
2. it was tried in the past. and more people was willing to argue about the structure then actually write the documentation. quite bike-shading topic if you ask me. one thing was sure in either case... we need to move content out of wiki.

**Comment by siddharthist** [comment]
This still doesn't appear done. Does anyone have the ability/knowledge to tackle this @garbas @copumpkin?

**Comment by siddharthist** [comment]
Looks like this has been done: https://nixos.org/wiki/Main_Page
