### ISSUE TITLE
Package request: curl-impersonate

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#169150]
**Project description**

https://github.com/lwthiker/curl-impersonate is like curl, but doesn't get you blocked by cloudflare and other WAPs that insist you have the TLS fingerprint of a web browser.

> A special compilation of [curl](https://github.com/curl/curl)[](https://github.com/lwthiker/curl-impersonate#why) that makes it impersonate real browsers. It can impersonate the four major browsers: Chrome, Edge, Safari & Firefox. This curl binary is able to perform a TLS handshake that is identical to that of a real browser.

**Metadata**

* homepage URL: https://github.com/lwthiker/curl-impersonate
* source URL: https://github.com/lwthiker/curl-impersonate
* license: MIT
* platforms: linux

**Comment by ivan** [comment]
https://github.com/lwthiker/curl-impersonate/blob/main/INSTALL.md the build process produces a separate 'Chrome' and 'Firefox' impersonation binary

https://github.com/lwthiker/curl-impersonate/tree/main/chrome

https://github.com/lwthiker/curl-impersonate/tree/main/firefox

**Comment by ivan** [comment]
I started packaging the firefox variant of curl-impersonate in https://github.com/ivan/nixpkgs/commits/curl-impersonate, but it has unresolved issues, including: missing the curl-impersonate `curl_ff*` wrapper scripts; PATH conflicts with `curl`; disabled tests; missing shell completions; possible issues with getting an HTTP response from some sites including archive.org. But it does sort of work and may be useful as a starting point. (Note that I have not checked the TLS fingerprint.)

**Comment by lilyinstarlight** [comment]
I've opened #194310 which should add a fully working build from source of curl-impersonate (with both firefox and chrome variants)
