### ISSUE TITLE
Some packages installed with environment.systemPackages do not have their binaries in PATH

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#169111]
### Describe the bug
I have included `gettext` into `environment.systemPackages`, but I cannot use it from command line, i get the error:
```console
$ gettext
The program 'gettext' is not in your PATH. You can make it available in an ephemeral shell by typing:
  nix-shell -p gettext
```
The same with `msgfmt`.

### Steps To Reproduce
1. Include `pkgs.gettext` into `environment.systemPackages`.
2. Try to execute `gettext` from command line.

### Expected behavior
Either the installed binaries should be in `PATH`, or there should be a simple and well documented method to put them in `PATH`.

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.111, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(alexey): `""`
 - channels(root): `"nixos-21.11.337090.0a862f558d4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alexeymuranov** [comment]
Never mind, i did something stupid.

**Comment by maribrowne** [comment]
hi, do you remember what your stupid mistake was? i am having a similar issue :(
