### ISSUE TITLE
Mesos slave URI fetcher chokes on .tgz

### ISSUE THREAD

**Issue by moretea** [NixOS/nixpkgs#16917]
## Issue description
Apache Mesos' [fetcher implementation](https://github.com/apache/mesos/blob/ae0aee6e2bdecfe67a244cb5a5b343acaa2876d6/src/launcher/fetcher.cpp#L63-80) depends on several decompressors.

### Steps to reproduce
Follow the steps in https://github.com/moretea/nixpkgs-mesos-fetcher-fail/blob/master/README.md

## Technical details

* System: `unstable, 16.09pre85931.125ffff (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09pre85639.453086a"`

**Comment by rasendubi** [comment]
As far as I can tell, the patch is already in place: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/mesos/default.nix#L60-L63

**Comment by moretea** [comment]
@rasendubi you're 100% right. I'll create a minimal reproducible example.

**Comment by moretea** [comment]
I've updated the description to point to https://github.com/moretea/nixpkgs-mesos-fetcher-fail/blob/master/README.md.

/cc @wmertens given that I found some of your work with setting up a mesos cluster.

**Comment by wmertens** [comment]
It's been quite a while since I touched that, so I can't really be of any help. @nathan-gs ?

**Comment by nathan-gs** [comment]
Quite sure we didn't encounter any issue related to mesos fetcher... Maybe @mhausenblas can help?

**Comment by kamilchm** [comment]
@moretea try this https://github.com/NixOS/nixpkgs/pull/17294

**Comment by moretea** [comment]
I can confirm that the example I gave is working now. Thanks @kamilchm! If I ever meet you, I'll buy you a :beer:.

**Comment by kamilchm** [comment]
Unfortunately I will miss MesosCon in Amsterdam but LinuxCon Europe in Berlin sound like a good place to have a :beer: :yum:

**Comment by kamilchm** [comment]
BTW http://mesos.apache.org/blog/mesos-1-0-0-released/ :)
