### ISSUE TITLE
Print Screen not working in cinnamon desktop 

### ISSUE THREAD

**Issue by kamalsomani** [NixOS/nixpkgs#169178]
### Describe the bug
I am new to nixos...
When I try to use printScr Key on keyboard. it not responding.
non of the printScreen optins working..

### Steps To Reproduce
1. ... press Key PrintScr
2. ...
3. ...

### Expected behavior
Should take a screen shot
ask for location to save to.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/6iw7yxcpsn4p7q2lf93n021gjzji8lbl-bash-interactive-5.1-p8-dev
copying path '/nix/store/6iw7yxcpsn4p7q2lf93n021gjzji8lbl-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.98, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by hqurve** [comment]
I am not too sure but according to the [arch wiki](https://wiki.archlinux.org/title/Cinnamon#Screenshot), cinnamon does not have a "native" screenshot tool but gnome-screenshot could be used. I am not too sure if enabling cinnamon auto includes gnome-screenshot. If it doesn't you can just add it and see if it solves your problem.
