### ISSUE TITLE
SickGear is missing some "optional" dependencies

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#169182]
### Describe the bug

A number of dependencies which are *technically* optional (but without which some features don't work) appear to be missing from the SickRage package:

```
2022-04-18 11:28:01 WARNING  SUBLIMINAL :: Service tvsubtitles not available: none of available features could be used. One of ['lxml'] required
2022-04-18 11:28:01 WARNING  SUBLIMINAL :: Service addic7ed not available: none of available features could be used. One of ['lxml'] required
```

(Presumably this requires some Python `lxml` package?)

```
2022-04-17 03:47:13 SHOWUPDATER :: Failed to unpack archive: /var/lib/sickbeard/cache/alts/tmp/alt.rar with error: Cannot find working tool
2022-04-17 03:47:13 SHOWUPDATER :: Failed to unpack json data: /var/lib/sickbeard/cache/alts/tmp/alt.rar with error: [Errno 2] No such file or directory: '/var/lib/sickbeard/cache/alts/alt.json'
```

(Presumably this requires `unrar`?)

### Steps To Reproduce
1. Install SickGear from nixpkgs
2. Enable subtitle fetching
3. Add a show with subtitles enabled
4. Look at regular logs (for the subtitle warning) and error logs (for the rar error)

I'm not entirely sure when or why SickGear fetches the `.rar` file, but I *think* the subtitle fetch is attempted when a show episode is being searched for.

### Expected behavior
Features should work out of the box.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@rembo10 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.110, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(sven): `""`
 - channels(root): `"nixos-21.11.337090.0a862f558d4"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Note: SickGear is installed from `unstable`, even though I am running stable.

**Comment by rembo10** [comment]
The only problem I can see is that unrar is unfree.... Just looking through the [source](https://github.com/SickGear/SickGear/blob/0fdde84c1a6518a9bb7f2a935550c846ee89f7ad/lib/rarfile_py3/rarfile.py#L109), it looks like it can also use bsdtar from libarchive.... so I'm not sure the best way to handle it.

**Comment by rembo10** [comment]
Maybe you can test out [this PR](https://github.com/NixOS/nixpkgs/pull/187983)
