### ISSUE TITLE
josm: Scripting plugin clipboard fails with `IllegalAccessException`

### ISSUE THREAD

**Issue by AndrewKvalheim** [NixOS/nixpkgs#169233]
### Describe the bug

The [JOSM Scripting Plugin](https://gubaer.github.io/josm-scripting-plugin/) provides a simple [clipboard API](https://gubaer.github.io/josm-scripting-plugin/apidoc/modules/clipboard.html), but attempting to use it results in an `IllegalAccessException`. By cargo-culting from [an unrelated issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=65300#c3) I’ve found the following workaround—

```nix
josm.override {
  extraJavaOpts = "--add-opens java.desktop/sun.awt.datatransfer=ALL-UNNAMED --add-opens java.desktop/sun.awt.X11=ALL-UNNAMED";
}
```

—but I don’t know what any of that means or what at appropriate solution would look like.

### Steps To Reproduce

In JOSM:

1. Enable the plugin via *Edit → Preferences → Plugins → scripting*.
2. Open *Scripting → Show scripting console*.
3. Run this example script:

    ```javascript
    var clipboard = require("clipboard");
    
    clipboard.text = "example";
    ```

### Expected behavior

No visible output, but the text `example` should now be on the clipboard; you can paste in any other application.

### Actual behavior

The following is displayed in a modal window and logged to stdout:

> Wrapped java.lang.IllegalAccessException: class org.mozilla.javascript.MemberBox cannot access class sun.awt.X11.XToolkit (in module java.desktop) because module java.desktop does not export sun.awt.X11 to unnamed module @100c5fc2 (jar:file:/home/user/.local/share/JOSM/plugins/scripting.jar!/js/[clipboard.js#53](https://github.com/Gubaer/josm-scripting-plugin/blob/ba71468caec30cdd135508832f79e26f949cc2fa/javascript/clipboard.js#L53))

### Notify maintainers

@rycee @sikmir

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337053.2f06b87f64b, nixos-hardware"`
 - channels(user): `"home-manager-21.11, nixos-unstable-22.05pre369524.5181d5945ed, rust-overlay"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sikmir** [comment]
Well, your solution works for me. That's why `extraJavaOpts` parameter exists, since we can't test JOSM with all existing plugins, some of them require special tweaking. Some more tweaks:
https://github.com/JOSM/josm/blob/2d224605607e50335c8ff1ff319e10b41ce4f49f/native/linux/latest/usr/bin/josm-latest#L61-L68
```sh
    if [[ "${JAVACMD}" =~ 'java-9' ]] || [[ "${JAVACMD}" =~ 'java-10' ]]; then
        JAVA_OPTS="--add-modules java.activation,java.se.ee $JAVA_OPTS"
    elif [[ "${JAVACMD}" =~ 'java-1' ]]; then
        JAVA_OPTS="--module-path /usr/share/openjfx/lib --add-modules java.scripting,java.sql,javafx.controls,javafx.media,javafx.swing,javafx.web $JAVA_OPTS"
        JAVA_OPTS="$JAVA_OPTS --add-exports=java.base/sun.security.action=ALL-UNNAMED"
        JAVA_OPTS="$JAVA_OPTS --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED"
        JAVA_OPTS="$JAVA_OPTS --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED"
    fi
```
I don't thing this is a real bug. We can add it as an example of `extraJavaOpts`.

**Comment by AndrewKvalheim** [comment]
No interest in improving the derivation as we run across these though?

And I wonder what Debian is doing differently that doesn’t require this of the user.

**Comment by AndrewKvalheim** [comment]
I see that JOSM [ships with](https://github.com/JOSM/josm/blob/18433/native/josm.jnlp#L23) a handful of these holes punched. So maybe this ultimately needs to be worked out between JOSM and the scripting plugin? (And Debian has made some decision to insulate the user from that until it’s resolved?)

**Comment by AndrewKvalheim** [comment]
Looks like the reason it works in Debian is they’re using an older version of Java that defaulted to lax permissions; I can reproduce its behavior with:

```nix
josm.override { jre = jdk11; }
```

Reporting at Gubaer/josm-scripting-plugin#95 instead, thanks.
