### ISSUE TITLE
Update Ansible to v1.9.5

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#16923]
## Issue description
[It's currently 1.9.4](https://github.com/NixOS/nixpkgs/blob/d2435933c0a2c8981992fa73a10523af4d15b96b/pkgs/top-level/python-packages.nix#L816) but [1.9.5 is out](https://github.com/ansible/ansible/releases?after=v2.0.2.0-0.4.rc4).

**Comment by RamKromberg** [comment]
Actually it was 1.9.6.

**Comment by FRidh** [comment]
fixed with #16943 and pushed to 16.03 as well
