### ISSUE TITLE
"urwid-2.1.2 not supported for interpreter python2.7" prevents rebuild

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#169349]
### Describe the bug

I'm getting `error: urwid-2.1.2 not supported for interpreter python2.7` when I run `sudo nixos-rebuild switch` [`--show-trace` (output)](https://pastebin.com/raw/V9fNXccb). There's no mention of `urwid` anywhere in my configuration, so it must be a dependency of something. I have no idea how to find out of what, or why this is happening, since I updated my nix-channels but it prevents nixos-rebuilds and thus updating my system.

![image](https://user-images.githubusercontent.com/11145016/164057594-b9e8f72c-b65f-425f-bc94-dde554dfab0a.png)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.102, NixOS, 21.11 (Porcupine), 21.11.336297.47cd6702934`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-22.05pre369988.1ffba9f2f68, nixos-hardware, nixos-unstable-22.05pre369988.1ffba9f2f68, nixos2111-21.11.337090.0a862f558d4"`
```

**Comment by FRidh** [comment]
Yes, this is annoying but it can be found in the trace. In your case, it is `speedometer`.

**Comment by con-f-use** [comment]
Oh wow. Thanks, I don't know how I missed that. Should I file that issue against that package, then? @Baughn
