### ISSUE TITLE
"nix profile install nixpkgs#gnome.nautilus" ends with an error (...nautilus-42.0-dev': No such file or directory)

### ISSUE THREAD

**Issue by cryptix** [NixOS/nixpkgs#169431]
### Describe the bug
Installing nautilus from gnome fails when using `nix profile install`

### Steps To Reproduce

```console
nix profile install nixpkgs#gnome.nautilus
error: opening directory '/nix/store/vr4iy0rw3ri72i7sw4p8al9whdjrznvi-nautilus-42.0-dev': No such file or directory
```

### Expected behavior
An installed nautilus in my users profile.

### Additional context

I stumbled into `nix profile ...` because I'm using the unstable channel to use sway/wayland. `nix-env -iA` stopped working and prompted me to use `nix profile ...` instead but documentation is very sparse. I used this blog series to learn more about it but it could very well be that I missed a step:

https://ianthehenry.com/posts/how-to-learn-nix/new-profiles/

`nix-shell -p gnome.nautilus` works but is cumbersome. Not sure why but it also fetches a different version of `-dev`. Right now it's: `/nix/store/v7kc2jnvbafgdc2ihbh11f3spy2x1m2y-nautilus-42.0-dev`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/vkv057i6d4h2sw3ym8m76j193d54vi5d-bash-interactive-5.1-p16-dev
copying path '/nix/store/vkv057i6d4h2sw3ym8m76j193d54vi5d-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.26-hardened1, NixOS, 22.05 (Quokka), 22.05pre369988.1ffba9f2f68`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos"`
 - channels(cryptix): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
If you update your system to a revision that includes https://github.com/NixOS/nixpkgs/pull/167292

Then it should be fixed

**Comment by Artturin** [comment]
This has been fixed, either change nix to nixUnstable or update to get nix 2.8 once it's in the channels

**Comment by cryptix** [comment]
Thanks, confirmed.
