### ISSUE TITLE
journalctl refuses to read user logs

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#16954]
## Issue description

Separate from the nixos approach, systemd has user-configurable units, which can be set up in ~/.config/systemd/user.

These work. However, reading their logs does not; `journalctl --user-unit foo` fails with an ACL error:
```
Failed to search journal ACL: Operation not supported
No journal files were opened due to insufficient permissions.
```

### Steps to reproduce

Run `journalctl --user-unit foo`, as an arbitrary unprivileged user. You do not need to create the unit first.

## Technical details

* System: 16.03.1073.73e28bc (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.03.1073.73e28bc

**Comment by Baughn** [comment]
```
strace -ff -e open journalctl --user-unit foo 2>&1 | sprunge
http://sprunge.us/ABKM
```

**Comment by bjornfor** [comment]
I cannot reproduce it.

With a new, unprivileged user, I get:

```
$ id
uid=1001(testuser) gid=100(users) groups=100(users)
$ journalctl --user-unit foo
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
```

And with my normal user, which is member of the systemd-journal group (and wheel, adm), it works just fine. Tested on NixOS 16.03 and master/unstable/16.09pre.

**Comment by zarelit** [comment]
I cannot reproduce it either. On `16.03.1165.f5bcd93 (Emu)` I added a new unprivileged user as well, but it turns out different than @bjornfor. `journalctl --user-unit foo` gives me the same warning about not being in 'adm' or 'wheel' but `-- No entries --` instead of the permission error

**Comment by FRidh** [comment]
Did you mount with acl support? extX does so automatically, I don't know how it is with ZFS.

**Comment by Baughn** [comment]
No, that doesn't happen automatically, since most applications don't need it.

**Comment by dezgeg** [comment]
Yes, it adds these tmpfiles.d rules which uses ACLs:
````
z /run/log/journal 2755 root systemd-journal - -
Z /run/log/journal/%m ~2750 root systemd-journal - -

a+ /run/log/journal/%m - - - - d:group:adm:r-x,d:group:wheel:r-x
a+ /run/log/journal/%m - - - - group:adm:r-x,group:wheel:r-x
a+ /run/log/journal/%m/*.journal* - - - - group:adm:r--,group:wheel:r--

z /var/log/journal 2755 root systemd-journal - -
z /var/log/journal/%m 2755 root systemd-journal - -
z /var/log/journal/%m/system.journal 0640 root systemd-journal - -

a+ /var/log/journal    - - - - d:group:adm:r-x,d:group:wheel:r-x
a+ /var/log/journal    - - - - group:adm:r-x,group:wheel:r-x
a+ /var/log/journal/%m - - - - d:group:adm:r-x,d:group:wheel:r-x
a+ /var/log/journal/%m - - - - group:adm:r-x,group:wheel:r-x
a+ /var/log/journal/%m/system.journal - - - - group:adm:r--,group:wheel:r--
````

**Comment by Baughn** [comment]
That was the problem. I needed to `zfs set acltype=posixacl` on the pool, then restart systemd-journald.

I'd like to say it should be set by default, but so far I don't think there's any way to declaratively set ZFS attributes.

**Comment by Mic92** [comment]
Support for zfs attributes in nix would be a new different issue, wouldn't it?

**Comment by Baughn** [comment]
Naturally.

**Comment by Mic92** [comment]
this could be however documented in the documentation for zfs.
