### ISSUE TITLE
Howdy: pam Face auth

### ISSUE THREAD

**Issue by peterromfeldhk** [NixOS/nixpkgs#169572]
**Project description**
Windows Hello™ style authentication for Linux.
Face ID pam

**Metadata**

* homepage URL: https://github.com/boltgolt/howdy
* source URL: https://github.com/boltgolt/howdy
* license: mit
* platforms: linux

**Comment by ishammahajan** [comment]
This would be wonderful to have as a package. I can try making it with my preliminary NixOS knowledge if no one else is on it.

**Comment by bjornfor** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/76928.
