### ISSUE TITLE
Mathematica: Could not initialize GLX

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#169630]
### Describe the bug
```
Mathematica 
Qt issued a fatal error: Could not initialize GLX

Qt tried to load plugins from:
/nix/store/6sc5h4ggqzksnbvcddxfkaclv2k21y99-mathematica-13.0.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/Qt/plugins
/nix/store/6sc5h4ggqzksnbvcddxfkaclv2k21y99-mathematica-13.0.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64

Mathematica was installed in /nix/store/6sc5h4ggqzksnbvcddxfkaclv2k21y99-mathematica-13.0.1/libexec/Mathematica
/nix/store/6sc5h4ggqzksnbvcddxfkaclv2k21y99-mathematica-13.0.1/libexec/Mathematica/Executables/.Mathematica-wrapped: line 138: 18364 Aborted                 (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"
```
### Steps To Reproduce
Open Mathematica
### Notify maintainers
 @herberteuler 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2-zen3, NixOS, 22.05 (Quokka), 22.05.git.fc696dbcf8d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by herberteuler** [comment]
I tried the master version but did not reproduce it. Could you please provide more information?

**Comment by linsui** [comment]
https://github.com/NixOS/nixpkgs/issues/66755#issuecomment-657305962

**Comment by QuantMint** [comment]
> [#66755 (comment)](https://github.com/NixOS/nixpkgs/issues/66755#issuecomment-657305962)

`QT_XCB_GL_INTEGRATION=none` makes it work, but it used to work without it in the past(1-2months ago) using the exact same version of Mathematica.
I am using sway, that might be important.

**Comment by linsui** [comment]
I don't know. I have another app worked before but not anymore...

**Comment by herberteuler** [comment]
> > [#66755 (comment)](https://github.com/NixOS/nixpkgs/issues/66755#issuecomment-657305962)
> 
> `QT_XCB_GL_INTEGRATION=none` makes it work, but it used to work without it in the past(1-2months ago) using the exact same version of Mathematica. I am using sway, that might be important.

Could you provide a git hash of the nixpkgs repo from which you installed Mathematica? I can try that out here.

**Comment by QuantMint** [comment]
> > > [#66755 (comment)](https://github.com/NixOS/nixpkgs/issues/66755#issuecomment-657305962)
> > 
> > 
> > `QT_XCB_GL_INTEGRATION=none` makes it work, but it used to work without it in the past(1-2months ago) using the exact same version of Mathematica. I am using sway, that might be important.
> 
> Could you provide a git hash of the nixpkgs repo from which you installed Mathematica? I can try that out here. Because I did not find `fc696dbcf8d` in my earlier attempt.

ff9efb0724de5ae0f9db9df2debefced7eb1571d

**Comment by herberteuler** [comment]
> > > > [#66755 (comment)](https://github.com/NixOS/nixpkgs/issues/66755#issuecomment-657305962)
> > > 
> > > 
> > > `QT_XCB_GL_INTEGRATION=none` makes it work, but it used to work without it in the past(1-2months ago) using the exact same version of Mathematica. I am using sway, that might be important.
> > 
> > 
> > Could you provide a git hash of the nixpkgs repo from which you installed Mathematica? I can try that out here. Because I did not find `fc696dbcf8d` in my earlier attempt.
> 
> [ff9efb0](https://github.com/NixOS/nixpkgs/commit/ff9efb0724de5ae0f9db9df2debefced7eb1571d)

It is strange, still cannot reproduce.

**Comment by linsui** [comment]
I installed a package monthes ago with nix-env and forget that. It breaks later. I just found that the error disappears after I re-install it. So maybe you did somthing similiar?

**Comment by QuantMint** [comment]
> I installed a package monthes ago with nix-env and forget that. It breaks later. I just found that the error disappears after I re-install it. So maybe you did somthing similiar?

I have just fully reinstalled Mathematica with nix-env and it does work now, turns out that just upgrading it did nothing.

**Comment by linsui** [comment]
IIUC, packages installed with nix-env aren't updated with the system. So when it's deps updated it breaks silently.

**Comment by QuantMint** [comment]
> IIUC, packages installed with nix-env aren't updated with the system. So when it's deps updated it breaks silently.

I have tried to update it with `nix-env -u mathematica`, but nothing really happened so initially I though that maybe it was already updated. And it wasn't.

**Comment by herberteuler** [comment]
> IIUC, packages installed with nix-env aren't updated with the system. So when it's deps updated it breaks silently.

This is ironic if it is the reason, since Nix was invented to solve this kind of problem.

**Comment by linsui** [comment]
For me it's that case because I installed the package from a git repo...

**Comment by BalderHolst** [comment]
hello, i'm having the same issue when trying install a different version of mathematica. I have tried a lot of things and `QT_XCB_GL_INTEGRATION=none` seems to work, but the application becomes quite grainy looking.

The `default.nix` file i am trying to build:
``ǹix
let
    pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz") { };
in
pkgs.mathematica.override {
  source = pkgs.requireFile {
    name = "Mathematica_13.1.0_BNDL_LINUX.sh";
    # Get this hash via a command similar to this:
    # nix-store --query --hash \
    # $(nix store add-path Mathematica_XX.X.X_BNDL_LINUX.sh --name 'Mathematica_XX.X.X_BNDL_LINUX.sh')
    sha256 = "sha256:016638jwm9ipckh4pk3clagiv1a38ga96cg40sc90pwxqhkbp3rk";
    message = ''
      Your override for Mathematica includes a different src for the installer,
      and it is missing.
    '';
    hashMode = "recursive";
  };
}
```

I have added the file `Mathematica_13.1.0_BNDL_LINUX.sh` to the store at described by the command and it works, but i still get the same error message:
```console
[user@system:~]$ result/bin/mathematica
Qt issued a fatal error: Could not initialize GLX

Qt tried to load plugins from:
/nix/store/4cspdl0wha0sf2qlpw2hs7r1w0bsr7mq-mathematica-13.2.1/libexec/Mathematica/SystemFiles/Libraries/Linux-x86-64/Qt/plugins
/nix/store/4cspdl0wha0sf2qlpw2hs7r1w0bsr7mq-mathematica-13.2.1/libexec/Mathematica/SystemFiles/FrontEnd/Binaries/Linux-x86-64

Mathematica was installed in /nix/store/4cspdl0wha0sf2qlpw2hs7r1w0bsr7mq-mathematica-13.2.1/libexec/Mathematica
/nix/store/4cspdl0wha0sf2qlpw2hs7r1w0bsr7mq-mathematica-13.2.1/libexec/Mathematica/Executables/.mathematica-wrapped: line 154: 481640 Aborted                 (core dumped) "${MathematicaFE}" ${MESA_FLAG} -topDirectory "${TopDirectory}" "$@"
```

My system:
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.67, NixOS, 24.05 (Uakari), 24.05.20231211.a9bf124`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```
I am also running hyprland.

Thank you for your time!
