### ISSUE TITLE
PHP-CGI does not have any extensions loaded

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#169727]
### Describe the bug

Currently, the PHP-CGI binary does not load any php.ini file and therefore are not used

### Steps To Reproduce
1. Install some php extensions with buildEnv
2. php-cgi -m they are missing

### Expected behavior
My extensions are loaded

### Metadata
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(shyim): `"darwin, home-manager, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

**Comment by Princemachiavelli** [comment]
Looks like you fixed it already, thanks. #169728
