### ISSUE TITLE
Font looks different + really bad kerning

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#16978]
## Issue description
Somewhere between b5a95b1 and 6af0f57f91f5b87e10186f7d26a345cab565478c there is a commit that changes the default fonts on NixOS. Most text is just _different_ (I'd say, a bit less readable). But some text in the terminal (gnome-terminal) is completely borked (in regards to positioning):

![selection_002](https://cloud.githubusercontent.com/assets/133602/16868593/c71b8420-4a78-11e6-8346-b84243b8c9b9.png)

Look at how the 's' is drawn on top of the 'M'. And generally the positioning of glyphs is... not right!

### Steps to reproduce
Compare how fonts look in a few apps on nixpkgs b5a95b1 vs 6af0f57f91f5b87e10186f7d26a345cab565478c.

## Technical details

* System: x86_64-linux NixOS at master branch (6af0f57f91f5b87e10186f7d26a345cab565478c). No fonts.* settings in my configuration.nix file (never had that). GNOME3 desktop and gnome-terminal.

**Comment by abbradar** [comment]
My guess is 1e53d4a7776acbf61f42c094c103652c8068ad64. cc @ericsagnes. I'll try to switch to master and debug what happens.

**Comment by ericsagnes** [comment]
Wild guess, is there a `/etc/fonts.` and a `/etc/fonts.tmp` folder?

Could you post the result of `FC_DEBUG=1024 fc-match sans -s`?

**Comment by bjornfor** [comment]
```
bfo@whitetip ~
$ ls -l /etc/fonts*
lrwxrwxrwx 1 root root   17 Jul 15 10:51 /etc/fonts.tmp -> /etc/static/fonts

/etc/fonts:
total 8
drwxr-xr-x 3 root root 4096 Jul 15 10:47 2.11
drwxr-xr-x 2 root root 4096 Jul 15 10:47 conf.d
lrwxrwxrwx 1 root root   28 Jul 15 10:47 fonts.conf -> /etc/static/fonts/fonts.conf
```

```
bfo@whitetip ~
$ FC_DEBUG=1024 fc-match sans -s
FC_DEBUG=1024
	Loading config file /etc/fonts/2.11/fonts.conf
	Scanning config dir /etc/fonts/2.11/conf.d
	Loading config file /etc/fonts/2.11/conf.d/00-nixos.conf
	Loading config file /etc/fonts/2.11/conf.d/10-nixos-rendering.conf
	Loading config file /etc/fonts/2.11/conf.d/52-fontconfig-ultimate.conf
	Loading config file /etc/fonts/2.11/conf.d/99-user.conf
FreeMono.ttf: "FreeMono" "нормален"
FreeSans.ttf: "FreeSans" "нормален"
FreeSerif.ttf: "FreeSerif" "нормален"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
DejaVuSerif.ttf: "DejaVu Serif" "Book"
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
LiberationSerif-Regular.ttf: "Liberation Serif" "Regular"
luximr.ttf: "Luxi Mono" "Regular"
unifont.ttf: "Unifont" "Medium"
Roboto-Light.ttf: "Roboto" "Light"
DejaVuSerif-Italic.ttf: "DejaVu Serif" "Italic"
LiberationSerif-Italic.ttf: "Liberation Serif" "Italic"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
6x13.pcf.gz: "Fixed" "SemiCondensed"
9x15.pcf.gz: "Fixed" "Regular"
```

**Comment by bjornfor** [comment]
Hm, I upgraded another machine to the same commit. Fonts look generally a bit different than they used to (for instance, in chromium + gmail). (I think the glyphs are just thinner and there is a lot of "air" around each letter.) But the horribly broken stuff in gnome-terminal doesn't happen on this machine. What's going on?

**Comment by ericsagnes** [comment]
Can you try to remove `/etc/fonts` and `/etc/fonts.tmp` and do a `nixos-rebuild` to see if that improve the situation?

**Comment by bjornfor** [comment]
Yes it does! Now all text look like it used to. Thanks!

```
sudo rm -rf /etc/fonts*
sudo nixos-rebuild [...]
reboot
```

After this, /etc/fonts.tmp is no more, only /etc/fonts:

```
$ ls -l /etc/fonts*
lrwxrwxrwx 1 root root 17 juli  15 12:19 /etc/fonts -> /etc/static/fonts
```

**Comment by bjornfor** [comment]
Is this something we can fix in the NixOS module that sets up /etc/fonts, so that users upgrading from 16.03 to 16.09 won't hit this?

**Comment by abbradar** [comment]
A heuristic idea for this -- a function `isStatic :: Path -> Bool`:

* if path `/etc/foo` is a file, return True iff it's a symlink to `/etc/static/foo`. 
* if path is a directory, return True iff for all items in it `isStatic` is True. 

On any conflicts, if old path is static, it's safe to replace and/or delete stale. Otherwise make a backup and notify the user via a journal entry and console output.

What are the possible caveats? This would certainly be nice to implement. I can look into this if it seems a good idea, but I suspect corresponding code is in Perl, which I'm illiterate with. 

On July 15, 2016 1:25:53 PM GMT+03:00, "Bjørn Forsman" <notifications@github.com> wrote:
>Is this something we can fix in the NixOS module that sets up
>/etc/fonts, so that users upgrading from 16.03 to 16.09 won't hit this?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/issues/16978#issuecomment-232917151

-- 
Nikolay.

**Comment by ericsagnes** [comment]
> but I suspect corresponding code is in Perl ...

@abbradar Yes, the cause seems to be in the `link` function of [setup-etc.pl](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/etc/setup-etc.pl#L61).

**Comment by abbradar** [comment]
Truth be told, I like better an idea of making `/etc` fully static, with several files (like `/etc/passwd` when `mutableUsers = true`) explicitly set as symlinks to somewhere (`/var/lib/etc`?).  This simplifies the whole bookkeeping a lot, but however is a radical move. I'm eager to try implementing this but we need to survey possible cases when people manually change something in `/etc`. Maybe I'll get a chance asking in the ML...

**Comment by copumpkin** [comment]
@abbradar in principle I'd like that, but in practice FHS is pretty unclear about whether /etc is supposed to be mutable. Would definitely be interested in what you came up with though. Personally, I'd rather fix more programs to not use /etc and rather to link directly to configuration in the store that they need (since we get more granularity there and know exactly what needs to be mutable), but that's probably a lot of work in some cases.

**Comment by ericsagnes** [comment]
For input method packages, I used dedicated packages for the `etc` [subfolders](https://github.com/NixOS/nixpkgs/blob/3e387c3e005c87566b5403d24c86f71f4945a79b/nixos/modules/i18n/input-method/default.nix#L6) and added the folders under `/etc/` via [`environment.pathsToLink`](https://github.com/NixOS/nixpkgs/blob/3e387c3e005c87566b5403d24c86f71f4945a79b/nixos/modules/config/system-path.nix#L106).
Could a similar approach for `/etc/fonts` be a way to solve this problem?

**Comment by obadz** [comment]
@copumpkin, why would we care what FHS says? :-D

**Comment by rasendubi** [comment]
I get this line when switching (and then fonts look ugly):
```
Warning: something's wrong at /nix/store/1hzvalfcpsrymaclgf1szqbsfrxvps4j-setup-etc.pl line 81.
```

Where 81 line is https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/etc/setup-etc.pl#L81.

**Comment by rasendubi** [comment]
Opened a PR with a fix: https://github.com/NixOS/nixpkgs/pull/17042.

**Comment by rasendubi** [comment]
@abbradar see https://github.com/NixOS/nixpkgs/issues/3192 for read-only /etc

**Comment by abbradar** [comment]
@rasendubi Nice find! I haven't yet done any research, so this thread will come handy.
