### ISSUE TITLE
switch-to-configuration assertions

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#169820]
I am looking for a way to implement assertions for `nixos-rebuild switch`, that is, something that will allow me to test a condition at activation time and, if it is not satisfied, print an error and cancel activation entirely.

My current approach is to write a custom activation script, however, as far as I can tell, errors from activation snippets are ignored (only a message is printed). I can also do `exit 1`, but, while it will terminate the activation script (i.e. no more snippets will be executed), all other steps (e.g. restarting units) will still happen.

I was actually surprised by the facts that an error in an activation script does not cancel the activation, I would actually expect everything to fail in this case. However, I am not sure that changing this behaviour at this point is reasonable. But what about having something like an `$out/assertions` script that `switch-to-configuration.pl` will execute at the very beginning and cancel everything if it fails?

**Comment by roberth** [comment]
NixOS is actually a tiny _converging_-style configuration management tool built on a declarative language and declarative build system, so this may explain the design choice to keep going despite failure. You don't want an issue in the activation script to block other aspects of the configuration that might fix the issue.

An option for pre-activation checks seems like a really good feature.
It should probably also be overridable with an option, in case the user gets stuck and understands the problem.
