### ISSUE TITLE
haruna: request update 0.7.3 -> 0.8.0

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#169970]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: haruna

current version: 0.7.3
desired version: 0.8.0

###### Notify maintainers

maintainers: @jojosch 

###### Note for maintainers

I tried to update it myself, but when trying to open the result I get either:
```
fish: Job 1, '/nix/store/qjwn854dkqnbbx6pc6aw…' terminated by signal SIGSEGV (Address boundary error)
```
or:
```
unknown() : QQmlApplicationEngine failed to load component

unknown() : qrc:/qml/main.qml:78:5: SettingsEditor is not a type
```

Some dependencies could be moved to `nativeBuildInputs`, since they are build time only.

The project supports `yt-dlp` other than `youtube-dl`. Since `mpv` uses the former, maybe switching could be considered.

The homepage is outdated. It's now "https://invent.kde.org/multimedia/haruna".

Please tag this issue in your PR.

**Comment by klemensn** [comment]
Can you (re)produce #170026 after this update?

**Comment by SuperSamus** [comment]
This is an issue requesting an update, not a pull request (edited the title to be more clear).

Still, with the update I tried to do by myself I couldn't open Haruna in the first place.
