### ISSUE TITLE
tmux module's `keyMode` option changes standard key-bindings without warning

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#16999]
## Issue description

The `tmux` NixOS module describes [(1)] its `programs.tmux.keyMode` configuration option as:

> VI or Emacs style shortcuts.

From that description, I supposed that it would set the normal tmux options for using Vi-like or Emacs-like key-commands (`mode-keys` and `status-keys`). It does do that [(2)], but it also sets additional, undocumented key-bindings [(3)], including some that override the standard bindings of `<prefix>l` (go to previous window) and `<prefix>L` (go to previous session).

While I confess I was remiss in not confirming my supposition and using the `keyMode` option without first fully comprehending its effects, I might suggest that either the changes it makes to key-bindings be documented in the option's description, or those changes be given their own configuration option.

[(1)]: <https://github.com/NixOS/nixpkgs/blob/5404595b55eeefae69f2952a34dfc70e32523060/nixos/modules/programs/tmux.nix#L115>
[(2)]: <https://github.com/NixOS/nixpkgs/blob/5404595b55eeefae69f2952a34dfc70e32523060/nixos/modules/programs/tmux.nix#L27-L28>
[(3)]: <https://github.com/NixOS/nixpkgs/blob/5404595b55eeefae69f2952a34dfc70e32523060/nixos/modules/programs/tmux.nix#L30-L40>

## Technical details

* System: NixOS `16.09pre85931.125ffff (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09pre85931.125ffff"`

**Comment by peterhoeg** [comment]
I think you are absolutely right. Having written that module, I will clean it up.

**Comment by 8573** [comment]
Thanks!
