### ISSUE TITLE
Olaris Server

### ISSUE THREAD

**Issue by mrsetna** [NixOS/nixpkgs#169943]
**Project description**
Olaris is an open-source, community driven, media manager and transcoding server. 

**Metadata**

* homepage URL: [https://blog.olaris.tv](https://blog.olaris.tv)
* source URL: [https://gitlab.com/olaris/olaris-server](https://gitlab.com/olaris/olaris-server)
* license: GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
* platform: Linux

**Comment by kevincox** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/203710
