### ISSUE TITLE
Mauiki index-fm 2.1.1 segfault when trying to start

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#169936]
### Describe the bug
Trying to run index-fm 2.1.1 from unstable 

### Steps To Reproduce
1. Clone `nixpkgs` and run `nix-build -E 'with import /home/onny/projects/nixpkgs { }; libsForQt5.callPackage ./pkgs/applications/misc/index-fm/default.nix {}'`
2. Run `result/bin/index`
```
QApplication: invalid style override 'adwaita-dark' passed, ignoring it.
	Available styles: Breeze, qt5ct-style, Windows, Fusion
CREATING INSTANCE OF MAUI APP
QCommandLineParser: option not defined: "author"
QCommandLineParser: option not defined: "license"
QCommandLineParser: option not defined: "desktopfile"
QFileSystemWatcher::addPaths: list is empty
kf.kirigami: Failed to find a Kirigami platform plugin
Setting PlacesList model (QVariant(int, 13), QVariant(int, 1), QVariant(int, 3), QVariant(int, 2))
fish: Job 1, '/nix/store/a5a6s2n434q4jv6vh5mk…' terminated by signal SIGSEGV (Address boundary error)
```

### Expected behavior
index-fm / index should run as it was already working with version 2.1.0.

### Notify maintainers
@dotlambda 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3-gnu, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.337177.692729210d0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by onny** [comment]
Downgrading QT dependencies from 5.15 to 5.14 seems to solve the problem. I'm able to launch index-fm 2.1.1 (including mauikit dependencies @ 2.1.1). Maybe this is a upstream problem?

**Comment by dotlambda** [comment]
`nix-build -A index-fm && result/bin/index` works just fine.
This is either something you changed or Qt stuff from unstable can't be run on 21.11.

**Comment by onny** [comment]
Thank you @dotlambda for the feedback. I'm still struggling to test unstable packages. Hoping to get nixos-shell with a graphical session to work to test index-fm from an unstable system.

**Comment by onny** [comment]
Updated my system to unstable and now it is running :) Thank you for the info!
