### ISSUE TITLE
GHC bootstrapping broken by ncurses update

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#17008]
Commit  d2dab39bfa34ce23910b502ea0e2c77d02898a5a from @vcunat broke

* haskell.compiler.ghc6102Binary
* haskell.compiler.ghc704Binary

and therefore the packages

* haskell.compiler.ghc6104
* haskell.compiler.ghc704
* haskell.compiler.ghc722
* haskell.compiler.ghc742
* haskell.compiler.ghc763

which depend on them.

**Comment by dezgeg** [comment]
Please try #17023. I test-built the binary GHCs but no further.

**Comment by vcunat** [comment]
Aha. I relied on the update being API-compatible, but the first bootstraping steps don't recompile...

**Comment by vcunat** [comment]
I'm test-building the whole list above.

**Comment by vcunat** [comment]
All succeeded on x86_64-linux.
