### ISSUE TITLE
krita 5.0.2: fails to build

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#170091]
### Describe the bug

Krita fails to build with the following error

```
/build/krita-5.0.2/plugins/impex/raw/3rdparty/libkdcraw/src/kdcraw.cpp: In member function 'bool KDcrawIface::KDcraw::extractRAWData(const QString&, QByteArray&, KDcrawIface::DcrawInfoContainer&, unsigned int)'
:
/build/krita-5.0.2/plugins/impex/raw/3rdparty/libkdcraw/src/kdcraw.cpp:386:24: error: 'struct libraw_output_params_t' has no member named 'shot_select'
  386 |     raw.imgdata.params.shot_select = shotSelect;
      |                        ^~~~~~~~~~~
```

### Steps To Reproduce

Build `/nix/store/phqfm6gn6k7ql57i27ypmnvdxmz21q03-krita-5.0.2.drv`

### Expected behavior

Krita should build.

### Metadata

nixpkgs @ c157bf1222949b63073821678cbef211d9b6129f

**Comment by hamburger1984** [comment]
In https://github.com/NixOS/nixpkgs/pull/151592 libraw was updated. Switch to the old stable libraw_0_20 to fix this build.

**Comment by leiserfg** [comment]
Installing kirta is showing
``` 
building '/nix/store/phqfm6gn6k7ql57i27ypmnvdxmz21q03-krita-5.0.2.drv'
```
like it's not in the cache, any idea why?

**Comment by vcunat** [comment]
You're attempting to build the older derivation.  And building it would fail.  Newer binaries are available: https://hydra.nixos.org/job/nixpkgs/trunk/krita.x86_64-linux

**Comment by vcunat** [comment]
If you rely on channels, you might want to watch https://nixpk.gs/pr-tracker.html?pr=170108

**Comment by leiserfg** [comment]
I'm using  the "https://nixos.org/channels/nixpkgs-unstable"  and just updated it, and I get this:
```console
nix-env -i krita
installing 'krita-5.0.2'
this derivation will be built:
  /nix/store/phqfm6gn6k7ql57i27ypmnvdxmz21q03-krita-5.0.2.drv
  ....
 ```


> If you rely on channels, you might want to watch https://nixpk.gs/pr-tracker.html?pr=170108

So, that means the PR is not in that channel yet? If it's that, good to know, didn't know that tool.

**Comment by vcunat** [comment]
Yes, channels that are not -small usually lag by roughly one day.
