### ISSUE TITLE
zlib: Version 1.2.12 does not produce a shared object when cross-compiled

### ISSUE THREAD

**Issue by peperunas** [NixOS/nixpkgs#170002]
### Describe the bug
The current master version of zlib does not produce a shared object when used in a cross-compilation environment. Reverting to `1.2.11` fixes the issue.

Might be related to https://github.com/madler/zlib/issues/617

cc/ @Ericson2314 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.111, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
 - channels(root): `"nixos-21.05.2549.a1007637cea, home-manager-21.05, nixos-unstable-21.11pre304920.dd98b100651"`
 - channels(giulio): `""`
 - nixpkgs: `/nix/store/zvgn5cr40albrwmfzzn1mhffgfbs8yzl-source`
```

**Comment by Mindavi** [comment]
This fix should be coming to your channel soon (TM): https://github.com/NixOS/nixpkgs/pull/167395, https://github.com/NixOS/nixpkgs/pull/167643

**Comment by Ericson2314** [comment]
Thanks!
