### ISSUE TITLE
KWin does not load decoration or cursor theme at first start

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#17009]
## Issue description

The first time KWin is started, it does not load the Breeze cursor theme or window decoration. Instead, it falls back to the classic cursors and Plastik decoration. The cursor theme and decoration appear correctly after they are selected in System Settings, but this does not provide a good experience for new installations.
### Steps to reproduce

Start KDE in a new VM or as a user that has never run KDE before.
## Technical details
- System: NixOS
- Nix version: 1.12pre4523_3b81b26
- Nixpkgs version: 9fc0347c9335f2b6ee62e098e44a00641b65b589

**Comment by peterhoeg** [comment]
@ttuegel , I have a bunch of patches for ```startkde``` (proper dbus detection, fixing references to invalid variables, total hang if a KDE startup script does ```set -eu```) so I can take a look at this too. Should that patch go upstream or we just take it here?

**Comment by ttuegel** [comment]
We'll take it here. You can try to upstream it too, but that might take some time and our `startkde` is slightly different from upstream's anyway.
