### ISSUE TITLE
libretro dosbox fails to build on unstable

### ISSUE THREAD

**Issue by x10an14** [NixOS/nixpkgs#170024]
### Steps To Reproduce
1. Be on nixpkgs git sha `875b41570c41386017d787caefedc008ddb6e31b` (I've not bisected it more closely)
2. Have this config in your nixos config somewhere:
   ```nix
   environment.systemPackages = with pkgs; [retroarchFull]
   ```
3. `nixos-rebuild build`

### Expected behavior
For the build to be successful.

### Additional context
`nix log /nix/store/arskaab9sggpqc5jfh5jvwinm0znhhag-libretro-dosbox-unstable-2022-04-08.drv`:
https://paste.sr.ht/~x10an14/451f1df94f5fc9a63d6412e14cfe48916002b9f6

### Notify maintainers

@thiagokokada @kolbycrouch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.14, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by thiagokokada** [comment]
Should be fixed here, but still need someone to review so we can merge it: https://github.com/NixOS/nixpkgs/pull/169619

**Comment by thiagokokada** [comment]
With https://github.com/NixOS/nixpkgs/pull/169619 merged, this should be fixed.

**Comment by x10an14** [comment]
A little late, but this now works =)
