### ISSUE TITLE
request for packaging: spellcheck

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#17006]
A tool that gives warnings and suggestions for bash/sh shell scripts:
[spellcheck](https://github.com/koalaman/shellcheck)
It has a [web demo](http://www.shellcheck.net/) too, and easy integration with vim/emacs.

@peti @fuuzetsu @asppsa @ttuegel @jcumming @aszlig:
It's a Haskell package, so I hope you don't mind being pinged.

**Comment by bjornfor** [comment]
The package is called "shellcheck" (shell... not spell...) and it seems to be already packaged (on master). 

That was easy ;-)

**Comment by magnetophon** [comment]
@bjornfor that explains a lot!  :grin:

**Comment by bjornfor** [comment]
I guess it'd be nice if it was available on stable (NixOS 16.03) too.

**Comment by magnetophon** [comment]
@bjornfor I can't [find](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=shellcheck) it...

**Comment by peti** [comment]
It's been packaged for a long time, really, both in `master` and in `release-16.03`:

    nix-env -f "<nixpkgs>" -iA haskellPackages.ShellCheck

**Comment by magnetophon** [comment]
@peti @bjornfor Works a treat! Thanks.

Still weird that it doesn't turn up on a [github search](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ShellCheck).

**Comment by bjornfor** [comment]
@magnetophon: Hm, weird. Local search finds it (nixpkgs.git at fe17c7a00213dae76cb607dfd063b9e9d7aeb5df):

```
$ git grep shellcheck
pkgs/build-support/fetchgit/nix-prefetch-git:        # shellcheck disable=SC2064
pkgs/build-support/fetchgit/nix-prefetch-git:        # shellcheck disable=SC2064
pkgs/development/haskell-modules/hackage-packages.nix:       homepage = "http://www.shellcheck.net/";
pkgs/top-level/all-packages.nix:  shellcheck = self.haskellPackages.ShellCheck;
```

@peti: Good! I didn't see it because the above search doesn't match on release-16.03 (there is no lower-case "shellcheck" attribute in all-packages.nix).

**Comment by magnetophon** [comment]
Since I'm using NixOS stable, the above is my default way of checking if something is packaged in master.
Are there better ways?

**Comment by peti** [comment]
The package search doesn't find Haskell packages. There are just too many to include them all.

**Comment by peti** [comment]
As far as Haskell packages are concerned, there is no need to check. Nixpkgs has every single package ever published on Hackage.

**Comment by magnetophon** [comment]
@peti 
>The package search doesn't find Haskell packages. There are just too many to include them all.

I'm using the github search feature, you seem to assume I mean the nixos.org package search.

Or is nixos haskell in a separate repo?

>As far as Haskell packages are concerned, there is no need to check. Nixpkgs has every single package ever published on Hackage.

I know.  Thanks for that!  :+1:
