### ISSUE TITLE
azure-cli: Could not find a version that satisfies the requirement azure-mgmt-servicelinker==1.0.0b1

### ISSUE THREAD

**Issue by kuwii** [NixOS/nixpkgs#170043]
### Describe the bug
When building `azure-cli` through `nixos-rebuild` or `nix-shell -p azure-cli`, the build will fail with

```
ERROR: Could not find a version that satisfies the requirement azure-mgmt-servicelinker==1.0.0b1 (from azure-cli) (from versions: none)
ERROR: No matching distribution found for azure-mgmt-servicelinker==1.0.0b1
```

### Steps To Reproduce
Through `nix-shell`:
1. Update nix channel: `sudo nix-channel --update`
2. Run: `nix-shell -p azure-cli`

Through `nixos-rebuild`
1. Update nix-channel: `sudo nix-channel --update`
2. Add `azure-cli` to `environment.systemPackages`
3. Run: `nixos-rebuild boot` or `nixos-rebuild switch`

### Expected behavior
The package should be successfully built.

### Screenshots
![Screenshot_20220424_111957](https://user-images.githubusercontent.com/10705175/164954919-6e1ae4ca-639c-482e-949e-c1eda292a455.png)

### Notify maintainers
@jonringer  

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre369988.1ffba9f2f68`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"home-manager, nixos, nixos-2105-21.05, nixt"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jonringer** [comment]
I'm in the process of bumping it, but I think that was me

**Comment by jtrees** [comment]
I've also run into this. Is there a workaround we can use until it gets fixed?

**Comment by jtrees** [comment]
Thanks!
