### ISSUE TITLE
Profiles do not work as documented

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#17018]
I took this command from the manual:

```nix-env -p /nix/var/nix/profiles/other-profile -i subversion```

It results in
```error: opening lock file ‘/nix/var/nix/profiles/other-profile.lock’: Permission denied```

See chapter 9 of the Nix manual for the expected behaviour. 

If, however, this is a user-error (can't imagine how), then I would like the error message to say what permissions were expected.

**Comment by vcunat** [comment]
Does your user have write permission into the requested profile files? Normal user would *not* have it in your particular command.

With `-p /nix/var/nix/profiles/per-user/$USER/other-profile` it works for me fine. Let's keep #17017 open instead, as the documentation isn't good about this.
