### ISSUE TITLE
enblend-enfuse fails to build on unstable

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#170227]
### Describe the bug

Since about a day or two this package no longer builds.

### Steps To Reproduce
1. `nix-shell -p enblend-enfuse`

### Expected behavior
It should build.

### Additional context

[enblend-enfuse.log](https://github.com/NixOS/nixpkgs/files/8552969/enblend-enfuse.log)

### Notify maintainers
N/A

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre369988.1ffba9f2f68`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixos-22.05pre372012.bc41b01dd7a"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hqurve** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/169978 and currently building on hydra https://hydra.nixos.org/job/nixpkgs/trunk/enblend-enfuse.x86_64-linux
