### ISSUE TITLE
spacedrive: Packaging request

### ISSUE THREAD

**Issue by khrj** [NixOS/nixpkgs#170254]
**Project description**
Cross platform file manager supporting cloud providers

**Metadata**

* homepage URL: https://www.spacedrive.app/
* source URL: https://github.com/spacedriveapp/spacedrive
* license: GPL-3.0
* platforms: linux, darwin

**Comment by hmenke** [comment]
Clicking "Download" on the website shows

> You're here early! This is the only button on this page that does not work, I promise. Release build coming very soon—follow `@spacedriveapp` for updates.

**Comment by khrj** [comment]
They don't ship binaries yet since its in beta, but the repo is ready and has instructions to compile (cargo + pnpm)

**Comment by bbigras** [comment]
It seems we can use binaries from https://github.com/spacedriveapp/spacedrive/actions/workflows/release.yml

**Comment by MikaelFangel** [comment]
I've added the binary version to my [NUR](https://github.com/MikaelFangel/NUR/blob/master/pkgs/sp/spacedrive/default.nix) ❤️

**Comment by heisfer** [comment]
haven't done nixpkgs contribution but appimage version [spacedrive.nix](https://github.com/heisfer/nixdot/blob/1a802a5fffd1d606fe51e68afdab27e7dd93aba1/pkgs/spacedrive/default.nix) 
plus it needs to add meta field too.

**Comment by pbsds** [comment]
Combine the two above derivations, and it would be a quick merge into nixpkgs :+1:
