### ISSUE TITLE
The latest qjackctrl segfaults on launch.

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#17027]
## Issue description
As soon as you run it, qjackctl 0.4.2 segfaults.
0.4.0 built with the same NixOS does not have this issue.

## Technical details

* System: 16.09.git.125ffff (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre85931.125ffff"

ping @cillianderoiste

**Comment by FRidh** [comment]
hm, I do not get any segfault with `16.09.git.3badad8 (Flounder)` (current nixos-unstable) and neither with `125ffff`.

**Comment by magnetophon** [comment]
@FRidh Thanks for testing.  I rebuilt based on ``125ffff`` and got a segfault again. I'll investigate further.

**Comment by magnetophon** [comment]
NixOS ``2ef1c6b`` runs qjackctl just fine.
