### ISSUE TITLE
Enabling services.hardware.xow breaks

### ISSUE THREAD

**Issue by lasers** [NixOS/nixpkgs#170373]
### Describe the bug

Enabling services.hardware.`xow` (as a systemd service) breaks.

### Steps To Reproduce
1. Add `services.hardware.xow.enable = true;`
2. `sudo nixos-rebuild switch --upgrade`
3. An error about `git: command not found` and several other errors like "has not been declared", "does not name a type", etc.

### Expected behavior

To rebuild xow and everything else without any issues.

### Notify maintainers

@jansol 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 22.05 (Quokka), 22.05pre372388.87d34a6b898`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - channels(chris): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jansol** [comment]
The git not found problem is IIRC and the derivation overrides the version info anyway.

Looks like another victim of our stdenv compiler upgrade. Looks like upstream master has a fix for that. Upstream is also much orphaned so upgrading the derivation to an unstable revision is going to be needed in the short term and in the long term a replacement should probably be found. I don't have a working controller to test xow with any more so if someone wants to adopt the package, feel free to.
