### ISSUE TITLE
nixos.tests.lxd.aarch64-linux fails on hydra

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#170395]
For example https://hydra.nixos.org/build/174728144

This test has always been failing: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.lxd.aarch64-linux/all

From the logs:

```
machine: must succeed: lxc image import /nix/store/cafixfv42cfn63g8bbg592rxkrhnsmp9-lxd.tar.xz /nix/store/z3inz6kkrwj5nzn7d46av7iyfp7j926h-rootfs.tar.xz --alias alpine
machine # To start your first container, try: lxc launch ubuntu:20.04
machine # Or for a virtual machine: lxc launch ubuntu:20.04 --vm
machine # 
(finished: must succeed: lxc image import /nix/store/cafixfv42cfn63g8bbg592rxkrhnsmp9-lxd.tar.xz /nix/store/z3inz6kkrwj5nzn7d46av7iyfp7j926h-rootfs.tar.xz --alias alpine, in 2.94 seconds)
subtest: Containers can be launched and destroyed
machine: must succeed: lxc launch alpine test
machine # Error: Failed creating instance record: Requested architecture isn't supported by this host
machine: output: Creating test

Test "Containers can be launched and destroyed" failed with error: "command `lxc launch alpine test` failed (exit code 1)"
```

/cc @patryk27

**Comment by Patryk27** [comment]
Whoopsie!

Maybe instead of keeping hard-coded URL to x86-64's Alpine [in here](https://github.com/NixOS/nixpkgs/blob/d12430a3e79a869a7b0c20d36353d621aa4fa0ec/nixos/tests/lxd.nix#L4) we could build something dynamically? (this way the test would automatically work on all architectures)

I'll try to take a look over the weekend, but feel free to take a shot at it, if you want 🙂

**Comment by raboof** [comment]
> Maybe instead of keeping hard-coded URL to x86-64's Alpine [in here](https://github.com/NixOS/nixpkgs/blob/d12430a3e79a869a7b0c20d36353d621aa4fa0ec/nixos/tests/lxd.nix#L4) we could build something dynamically? (this way the test would automatically work on all architectures)

Hmm that is a cool idea. Though OTOH it is currently nice that when this test fails it is clear it is a problem with running the image, and not with creating it. 

Did you get that alpine/3.12/rootfs.tar.xz from somewhere or did you create it? Is it the 'mini root fs' from https://alpinelinux.org/downloads/ ?

**Comment by Patryk27** [comment]
> [...] Is it the 'mini root fs' from https://alpinelinux.org/downloads/ ?

Yeah, that's the one;
