### ISSUE TITLE
Btrfs not compressing nix/store where zfs does

### ISSUE THREAD

**Issue by jrgiacone** [NixOS/nixpkgs#170347]
### Describe the bug
When building the system in a vm to test out which file system I will use I noticed btrfs taking up much more space than zfs at default settings. The only difference was the nix/store was on btrfs not compressing all my files such as ghc.

Both Files have the same configuration with the corresponding file system adds.

### Steps To Reproduce
1. create two separate vm using zstd with a zfs pool and btrfs forced-compression=zstd (note for btrfs you will have to edit the hardware-config file and manually add options as these do not get run on their own)
2. Build xmonad which will pull ghc 9.0.2 (using untable)

### Expected behavior
With the same compression levels and zstd, I expect the compression to be equivalent.

ncdu for Btrfs:
![2022-04-25-17:31:43-screenshot](https://user-images.githubusercontent.com/71910145/165195857-7b3c0708-a544-4851-a0a7-f1dc1288ac16.png)

ncdu for Zfs:
![2022-04-25-17:32:52-screenshot](https://user-images.githubusercontent.com/71910145/165195984-f2a587f2-c872-4f8c-b81a-674966b58daf.png)

### Notify maintainers
I'm sorry I could not find a btrfs

### Metadata
![2022-04-25-17:31:01-screenshot](https://user-images.githubusercontent.com/71910145/165195803-4e5af25a-cafe-4624-9b11-4433374fc6ed.png)

**Comment by azuwis** [comment]
https://wiki.archlinux.org/title/Btrfs#Displaying_used.2Ffree_space

> General linux userspace tools such as [df(1)](https://man.archlinux.org/man/df.1) will inaccurately report free space on a Btrfs partition.

> The same limitations apply to tools which analyze space usage for some subset of the filesystem, such as [du(1)](https://man.archlinux.org/man/du.1) or [ncdu(1)](https://man.archlinux.org/man/ncdu.1), as they do not take into account reflinks, snapshots and compression. Instead, see [btdu](https://aur.archlinux.org/packages/btdu/)AUR and [compsize](https://wiki.archlinux.org/title/Btrfs#View_compression_types_and_ratios) for btrfs-aware alternatives.

You don't need to edit hardware-configuration.nix, if your hardware-configuration.nix contains something like:
```
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/xxx";
      fsType = "btrfs";
    };
```

Edit configuration.nix, add:
```
fileSystems."/".options = [ "compress-force=zstd" ];
```
instead, the configs will be merged.
