### ISSUE TITLE
Python: help does not function in --pure shell

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#17034]
## Issue description

The help function does not work with `nix-shell --pure` because it cannot find `less`.
### Steps to reproduce

```
$ nix-shell -p python --pure --run "python -c 'import sys; help(sys)'"
sh: less: command not found
```
## Technical details
- 16.09.git.0ad8d0b (Flounder)

**Comment by FRidh** [comment]
Is this an accepted consequence of `nix-shell --pure`, or should `python` depend on `less`? @domenkozar

**Comment by domenkozar** [comment]
`--pure` means nothing will be in the environment except `stdenv` and `python`. Neither of them have `less` as dependency.

```
$ nix-shell -p stdenv --pure

[nix-shell:~]$ less
bash: less: command not found
```

**Comment by FRidh** [comment]
Indeed. So we need to add `less` to the `propagatedBuildInputs` of `python` then.

**Comment by domenkozar** [comment]
Sure - if Python needs it at runtime, then yes.

**Comment by FRidh** [comment]
Fixed in 773f6225cbcb33cacd729d5308b8813d6618674d, e261818c687af3fee9caa77b349d6f74a9e6aa93, b410631d6ddc455b5652abafa63d2f77c895d0ef, c59d211b4b528ff17f422b564382225adde917e8, and bce5a51a9f33a16bf91e7d72a927c3382f333442.

**Comment by FRidh** [comment]
Could check the pager
https://github.com/python/cpython/blob/master/Lib/pydoc.py#L1416

**Comment by Profpatsch** [comment]
(triage) any more progress?

**Comment by FRidh** [comment]
A pager such as less is an optional dependency. Users will have to manually include it when they use Python in `--pure` mode when they want the `help` function.
