### ISSUE TITLE
Clean up hardware-configuration.nix

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#170481]
### Describe the bug

This is the created config:

```
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usbhid" "ums_realtek" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5fc95d4a-ead1-4851-8fe3-f430ada41292";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6fa3a32d-ffef-49b2-b662-05f3e2cf7e4e"; }
    ];

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
```

Problems:

`  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];`

strange way to refer to a package. should be `boot.extraModulePackages = with pkgs; [ kernelPackages.broadcom_sta ];` i guess

`  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;`

technically that should work, but it's not easy to debug. use IF enableRedistributableFirmware then TRUE or something

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior

`hardware-configuration.nix` should follow best practices in nix syntax and be easy to understand to (new) users

### Additional context

Maybe something of that came from the new graphical installer? @vlinkz

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by roberth** [comment]
This is crucial:

```
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
```

------



> strange way to refer to a package.

It's like that for good reason. `pkgs` doesn't know _which_ kernel you're going to boot, but `config.boot.kernelPackages` does.



> `hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;`
> 
> technically that should work, but it's not easy to debug. use IF enableRedistributableFirmware then TRUE or something

I don't see another way to express a default value.


This is a generated file, so it comes from generic good, and therefore it needs to be more like a module than like a typical configuration. It follows module practices for good reason.

**Comment by vlinkz** [comment]
The main issue I see with the way `hardware-configuration.nix` is that by default, it will include unfree packages in `boot.extraModulePackages`. This means that there could be a case where some user is trying to install NixOS using only free packages and either has to:
* Enable unfree packages
* Allow the specific unfree packages in `hardware-configuration.nix`
* Disregard the warning at the top of `hardware-configuration.nix` and remove the unfree packages
* Force override `boot.extraModulePackages` in `configuration.nix` without the unfree packages

Since by default, unfree packages are not enabled on NixOS, it doesn't really make sense that unfree packages show up in `hardware-configuration.nix` without any form of user acknowledgment beforehand
