### ISSUE TITLE
lm-sensors sensord is not currently available

### ISSUE THREAD

**Issue by sg2002** [NixOS/nixpkgs#17040]
Lm-sensors provides a daemon for logging its data called sensord.

The [current lm-sensors package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/lm-sensors/default.nix) does not compile it.

Not sure whether it should be made available as a part of lm-sensors package, or made into a separate package, since, even though it's a part of lm-sensors source code, it adds an extra dependency on rrdtool. 

I was able to build it as a part of lm-sensors. I've added rrdtool to buildinputs and then "PROG_EXTRA=sensord" to makeFlagsArray.

**Comment by Nadrieril** [comment]
Is `rrdtool` a large dependency ? If it is, a nice solution could be to add a `sensord` option to the package definition, that would control whether to compile `sensord` or not. You could then also even add a `lm-sensors-with-sensord` package to `all-packages.nix`.
Are you still (or is anyone else) interested in this feature and would be willing to do it ? If not, this issue can be closed.

**Comment by Infinisil** [comment]
Has been fixed with above PR
