### ISSUE TITLE
Adding an incorrect(?) fileSystem."/foo/bar" with fsType "bindfs" results in a killed SSH connection

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#17047]
One of the properties I expect to hold is that if an SSH session is used during a configuration that after a `nixos-rebuild switch` this same SSH session is still working. 

That is, I would not expect the following to happen. 

```
nixos-rebuild switch                                               
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/kq2zl5zngk0laps6j9x93fc6pmvmp9ps-etc-fstab.drv
  /nix/store/ip1bgsr8bb71nxmhvnx8x0iiryavnb02-etc.drv
  /nix/store/qrrdpdm6rciajdh3zbkar3a8vj1h2qx7-nixos-system-nixos-16.03.1083.d745044.drv
building path(s) ‘/nix/store/c3mi1nj39ykpbfxjvs2akfch780gk0sf-etc-fstab’
building path(s) ‘/nix/store/fqs8a3r47nnraa693q879qfbz9m59bvw-etc’
building path(s) ‘/nix/store/42g9cvxv32hixmigimwf8z1v8kmjidsd-nixos-system-nixos-16.03.1083.d745044’
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
A dependency job for local-fs.target failed. See 'journalctl -xe' for details.
Job for multi-user.target canceled.
Shared connection to foo.bar.org closed.
```

`journalctl -xe` isn't actually visible (which makes the error message rather silly), because I am locked out of the machine. 

I am not sure whether local access is also broken (I can imagine that the other file systems are not mounted now) in this state. 

Really "bad" configurations should by default not be possible. There are assertions for configurations where you don't have SSH keys for example too.

Update: apparently mount says: `unknown filesytem type "bindfs"`

**Comment by 0xABAB** [comment]
OK, I fixed this particular instance and it go into "emergency mode", so I was able to fix it remotely. So, not ideal, but far from super annoying too. Nice.

**Comment by vcunat** [comment]
I believe this would fall under "nofail" discussed in the lower half of #1858, but it seems questionable how to choose which FSs are "critical" and which aren't.

**Comment by 0xABAB** [comment]
Yeah, I applied "nofail" (before you mentioned it, but thanks for mentioning it). 

I think "critical" is everything which is required to modify `/etc/nixos/configuration.nix` by default. If that were the case I would have never needed to learn about the nofail systemd concept. 

The people who want more control could then set those options.
