### ISSUE TITLE
nix run disabled by default on NixOS 22.05

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#170465]
### Describe the bug

On a fresh install of NixOS:

```
[x@nixos:~]$ nix run nixpkgs.geekbench
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```

This works on NixOS 21.11, so it's a regression.

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior
Nix should work by default on NixOS.

### Additional context
Does also apply to other nix commands like nix shell.

### Notify maintainers
@eelco @lovesegfault @artturin

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
`nix` now points to `nix_2_8` while on 21.11 it still pointed to `nix_2_3`
see https://discourse.nixos.org/t/nix-2-4-and-what-s-next/16257 from november of last year for some more info 

if you enable `nix-command` then you'll be able to do
`nix run -f '<nixpkgs>' geekbench`

if you don't want to enable it you'll have to use the legacy commands
`nix-shell -p geekbench --command geekbench`

**Comment by davidak** [comment]
A user should not have to enable something for commands to work. They should work by default.

**Comment by lovesegfault** [comment]
FWIW, I think we should just enable flakes and nix-command by default and accept that Nix does not currently have a stable interface.

It's unfortunate for users, but it's an issue that we can't do anything about in nixpkgs, it's for the Nix project to fix.

**Comment by max-privatevoid** [comment]
I guess the options are either
- Set `experimental-features = nix-command flakes` by default
- Continue shipping Nix 2.3 by default until Nix 3.0 with a stabilized new CLI and stabilized flakes is released

**Comment by lovesegfault** [comment]
I fear shipping 2.3 until 3.0 comes out will be more destructive to the ecosystem than enabling the experimental features.

To be clear, I think of this picking the lesser of two evils, upstream choices have made the life of nixpkgs maintainers pretty hard.

**Comment by vcunat** [comment]
I can't see why Nixpkgs/NixOS should override these defaults of Nix.  If they should change (which I'm not sure of), it should be done in Nix itself.

Defaulting to 2.3 doesn't seem good (anymore), as you'd probably be complicating life of many other users (for flakes mainly, I think).

From my point of view, enabling the features is pretty simple, and there are various ways (e.g. interactive-only alias).  It's a form of acknowledgment that the enabled UI is unstable.  In this sense I see disablement of `nix run` more of a bugfix than regression.

**Comment by Ma27** [comment]
nix run was always experimental and subject to change btw.

**Comment by vcunat** [comment]
That applies to the whole `nix` command.

**Comment by dasJ** [comment]
I think a very clear mention in the changelog would be enough.
Enabling experimental features by default would defeat the purpose of the experimental features as people would be using them without knowing they are subject to change.

We could also add a warning about this upcoming change to the 21.11 branch when 22.05 is in beta. I think it's okay to see this warning for the ~2 weeks.

**Comment by dasJ** [comment]
Now mentioned as the first thing in the changelog: https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2205.section.md#highlights-sec-release-2205-highlights

**Comment by davidak** [comment]
The [Release Notes](https://nixos.org/manual/nix/stable/release-notes/release-notes.html) link points to an empty page. Can you point to a page where actually are instructions that are relevant for upgrade from 2.3 to 2.8?

**Comment by vcunat** [comment]
https://nixos.org/manual/nix/stable/release-notes/rl-2.4.html etc.  They're just "under that empty page".

**Comment by Mic92** [comment]
> The [Release Notes](https://nixos.org/manual/nix/stable/release-notes/release-notes.html) link points to an empty page. Can you point to a page where actually are instructions that are relevant for upgrade from 2.3 to 2.8?

Because there were several version bumps, I was not so sure to which I should link. Maybe I just should link to all of them.

**Comment by davidak** [comment]
Maybe we could have a section in NixOS release notes with the highlights from all  these Nix versions, like a release also lists every important commit made in that time period. A user might want to know in 5 seconds, what are the important changes and we can prepare that. Things to be careful with (breaking changes), but also things to try out (new features).
