### ISSUE TITLE
nix-shell does not work with unfree packages (even when they are allowed)

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#170463]
### Describe the bug

```
[x@nixos:~]$ nix-shell -p geekbench
error: Package ‘geekbench-5.4.4’ in /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/tools/misc/geekbench/default.nix:35 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "geekbench"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

![a298f304-6065-4523-a4c7-3269352a1da8](https://user-images.githubusercontent.com/91113/165368156-f96fe7f7-e96d-4834-af89-f3c04e15bee5.png)

### Steps To Reproduce
1. have `nixpkgs.config.allowUnfree = true;` in `configuration.nix`
2. `nix-shell -p geekbench`
3. error: has an unfree license

### Expected behavior
no errors

### Additional context
Maybe related to https://github.com/NixOS/nixpkgs/issues/166220
https://github.com/NixOS/nixpkgs/issues/116340

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Princemachiavelli** [comment]
It's a bit unclear and perhaps inconvenient but the `nixpkgs.config.allowUnfree` setting only applies to building the system configuration (or any derivation using that nixpkgs probably(?)).

Only options A and/or C apply when using `nix-shell`. Normally ~/.config/nixpkgs/config.nix is an user created configuration file but it looks like you could use home-managers `xdg.configFile.PATH` option [1] to manage it decoratively.

[1] https://nix-community.github.io/home-manager/options.html#opt-nixpkgs.config

**Comment by lolbinarycat** [comment]
closing this as intended behavior, although perhaps the error message could be clarified.
