### ISSUE TITLE
github-desktop: Cannot connect github account

### ISSUE THREAD

**Issue by MichaelAkvo** [NixOS/nixpkgs#170419]
### Describe the bug

Trying to connect a github account will open a browser, request access, and finally fail to send the access token to the application as it can't be opened.

### Steps To Reproduce
1. File > Settings
2. Sign in to Github 
![image](https://user-images.githubusercontent.com/91939214/165310594-10079bb1-d537-44c5-b0f5-6abd5f146ec2.png)

3. Login and give access

### Expected behavior

The github desktop app should be opened after the token has been given access

### Screenshots

![image](https://user-images.githubusercontent.com/91939214/165310752-b0ec78b7-5efa-4593-be80-afa5df17ea20.png)

### Additional context

It's trying to call `x-github-desktop-dev-auth://oauth?code=CODE&state=STATE`

### Notify maintainers

@dan4ik605743

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.111, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337100.7b38b03d76a"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
probably caused by the package not having a desktop file with a `x-scheme-handler` entry or not having a desktop file at all

**Comment by VergeDX** [comment]
It does have `x-scheme-handler` of `x-github-desktop-dev-auth` in `github-desktop.desktop` in version `2.9.12`.
Also, upstream has many same issues. So maybe this is a upstream issues : (

**Comment by dan4ik605743** [comment]
@MichaelAkvo  check https://github.com/NixOS/nixpkgs/pull/180558

**Comment by Yeshey** [comment]
Having a similar issue, not sure if it's the same. Can't connect either, but it just loads indefinitely and never shows the pop-up the OP has.

am in KDE and enabled the gnome keyring adding 
```
  services.gnome.gnome-keyring.enable = true;
  security.pam.services.sddm.enableGnomeKeyring = true;
```
to /etc/nixos/configuration.nix

flatpak version of github-desktop works so it should be a problem with the nix package
