### ISSUE TITLE
qutebrowser segfaults under Qt 5.5

### ISSUE THREAD

**Issue by awjamison** [NixOS/nixpkgs#17052]
## Issue description

On unstable, qutebrowser 0.7 is built with Qt 5.5.1 and PyQt 5.5.1. There is a known issue in this version of Qt where non-scalable fonts result in a segfault (https://bugreports.qt.io/browse/QTBUG-45963). Loading a webpage that uses these fonts causes the browser to crash. 

The fix is to build against a newer version of Qt, e.g. 5.6. I'm unsure whether PyQt also needs to be bumped. PyQt is currently at 5.5.1 and will need to be updated if that is the case.

### Steps to reproduce

Install qutebrowser
Go to github.com

## Technical details

* System: NixOS 16.09pre85931.125ffff (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre85931.125ffff

**Comment by gebner** [comment]
Yes, PyQt needs to be the same version as Qt as far as I know.  However updating PyQt should be as easy as updating the version in `pyqt/5.x.nix` and then referencing the correct Qt version in `python-packages.nix`.  We also only have three packages depending on PyQt (qutebrowser, calibre, and openshot-qt), so it should be straightforward to test.

**Comment by abbradar** [comment]
This is fixed now -- PyQt was bumped to 5.6 some time ago.
