### ISSUE TITLE
Prisma 3.12.0 is broken

### ISSUE THREAD

**Issue by DAlperin** [NixOS/nixpkgs#170550]
### Describe the bug
When using prisma v3.12.0 sourced from nixpkgs/master, the @prisma/client library errors out with:
```
throw new PrismaClientInitializationError(`Unable to load Node-API Library from ${import_chalk4.default.dim(this.libQueryEnginePath)}, Library may be corrupt`, this.config.clientVersion);

PrismaClientInitializationError: Unable to load Node-API Library from /nix/store/gvv3vbqx7sxb3va391bh8ps2p20axkc6-prisma-engines-3.12.0/lib/libquery_engine.node, Library may be corrupt
```

Using an earlier version that packages 3.11.0 works fine.

### Steps To Reproduce
1. Create a node project with this configuration https://gist.github.com/DAlperin/d57f9412f98a1ae965fce9443b81b2cd
2. Run `prisma generate` from inside the devshell
3. Attempt to use the generated @prisma/client

### Expected behavior
@prisma/client should initialize and function correctly

### Notify maintainers

@pamplemousse @pimeys @superherointj

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by superherointj** [comment]
I haven't tested your example yet. But my project that uses prisma is working properly w/ 3.12.0.

But node: The prisma version has to be `exact`. Which `"prisma": "^3.12.0",` is not.

Make sure NPM is configured to use exact versions: `npm config set save-exact=true`

Remove the ^ from version, delete `package-lock.json`, npm install.

Also, run prisma client from `node_modules/.bin/prisma`.
(There is two prismas, NixOS's prisma, and node_module's client prisma.)

Let me know if problem persists.

**Comment by pimeys** [comment]
Yep, this looks like a version mismatch and the steps described by @superherointj should help. The TS code has checks to see checksums and commit id of the rust library, and will error out if something unexpected.

**Comment by pimeys** [comment]
You should only install the `@prisma/client` library from npm, and the cli part from nix. The cli compiles a special version of the rust engines.

Your `prisma` binary should be in nix, e.g. `/run/current-system/sw/bin/prisma`.

**Comment by DAlperin** [comment]
I have historically used the system prisma but tried the node_modules one as per @superherointj suggestion.

## Relevant info

`which prisma`: `/nix/store/jil7aq79s5s3k3hxijjd2mygigv8yzdn-prisma-3.12.0/bin/prisma`

`prisma generate`: 
```console
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Warning Precompiled binaries are not available for nixos.
Warning Precompiled binaries are not available for nixos.

✔ Generated Prisma Client (3.12.0 | library) to ./node_modules/@prisma/client in 144ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

Running my application:
```
throw new PrismaClientInitializationError(`Unable to load Node-API Library from ${import_chalk4.default.dim(this.libQueryEnginePath)}, Library may be corrupt`, this.config.clientVersion);
Error: Unable to load Node-API Library from /nix/store/gvv3vbqx7sxb3va391bh8ps2p20axkc6-prisma-engines-3.12.0/lib/libquery_engine.node, Library may be corrupt
```

**Comment by DAlperin** [comment]
@pimeys @superherointj here is an example of my use in a production application where I am experiencing this problem: https://github.com/DAlperin/dov.dev-remix/tree/broken-prisma-nixos

**Comment by superherointj** [comment]
> I have historically used the system prisma but tried the node_modules one as per @superherointj suggestion.
> ## Relevant info
> 
> `which prisma`: `/nix/store/jil7aq79s5s3k3hxijjd2mygigv8yzdn-prisma-3.12.0/bin/prisma`
> 
> `prisma generate`:
> 
> ```
> Environment variables loaded from .env
> Prisma schema loaded from prisma/schema.prisma
> Warning Precompiled binaries are not available for nixos.
> Warning Precompiled binaries are not available for nixos.
> 
> ✔ Generated Prisma Client (3.12.0 | library) to ./node_modules/@prisma/client in 144ms
> You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
> 
> import { PrismaClient } from '@prisma/client'
> const prisma = new PrismaClient()
> ```
> 
> Running my application:
> 
> ```
> throw new PrismaClientInitializationError(`Unable to load Node-API Library from ${import_chalk4.default.dim(this.libQueryEnginePath)}, Library may be corrupt`, this.config.clientVersion);
> Error: Unable to load Node-API Library from /nix/store/gvv3vbqx7sxb3va391bh8ps2p20axkc6-prisma-engines-3.12.0/lib/libquery_engine.node, Library may be corrupt
> ```

As you had a version mismatch problem first.
Please confirm that after you fixed the version problem:
1) deleted package-lock.json
2) delete node_modules
3) npm config set save-exact=true
4) npm install
Did you do this?

**Comment by pimeys** [comment]
I did a test with my example repo (in here: https://github.com/pimeys/nix-prisma-example/):

First I `nix flake update`, and get the latest prisma from main (3.12.0). I also updated the `package.json` to use the client version 3.12.0.

I can `prisma generate`, `prisma db push` and I can `npx ts-node index.ts` successfully...

**Comment by pimeys** [comment]
In the example repo posted by @DAlperin, I cannot continue due to missing dependencies:

```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react18-react-command-palette@0.16.5
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.0" from the root project
npm ERR!   peer react@">=16.8" from @remix-run/server-runtime@1.4.1
npm ERR!   node_modules/@remix-run/node/node_modules/@remix-run/server-runtime
npm ERR!     @remix-run/server-runtime@"1.4.1" from @remix-run/node@1.4.1
npm ERR!     node_modules/@remix-run/node
npm ERR!       @remix-run/node@"^1.4.0" from the root project
npm ERR!       2 more (@remix-run/express, remix-redis-session)
npm ERR!   22 more (@remix-run/react, @remix-run/server-runtime, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.x" from react18-react-command-palette@0.16.5
npm ERR! node_modules/react18-react-command-palette
npm ERR!   react18-react-command-palette@"^0.16.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.x" from react18-react-command-palette@0.16.5
npm ERR!   node_modules/react18-react-command-palette
npm ERR!     react18-react-command-palette@"^0.16.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/pimeys/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pimeys/.npm/_logs/2022-04-27T13_59_23_703Z-debug-0.log
```

**Comment by superherointj** [comment]
> @pimeys yes unfortunately there is a peer dependency mismatch with react I haven't gotten around to fixing. You can force npm to ignore the mismatch with npm install -f since the mismatch is in a frontend dep unrelated to prisma.

Ideally you should aim to reduce the scope of problem by removing parts as much as you can. Delete everything but what is not working (with Prisma). Or you could start a new simple demo, which would be ideal, so you get to test Prisma and not something else.

**Comment by DAlperin** [comment]
Ah alright figured it out. After upgrading from 1.11.0 to 1.12.0 for some reason using the node installed by home-manager `/etc/profiles/per-user/dovalperin/bin/node` stopped working with prisma. Switching to explicitly requiring node in my flake.nix as per @pimeys demo. If this is intended behavior we should probably mention it somewhere since google currently indexes an [old answer](https://github.com/prisma/prisma/issues/3026#issuecomment-927258138) from @pimeys which does not include listing node explicitly in the flake when searching for "[prisma nixos](https://www.google.com/search?q=prisma+nixos&oq=prisma+nixos)".

Maybe we could ask the prisma folks to add a note in their docs pointing to https://github.com/pimeys/nix-prisma-example/

**Comment by pimeys** [comment]
I am working for Prisma :D

I'll see this thread tomorrow...

**Comment by DAlperin** [comment]
Ahhh sorry about that. That's what I get for not clicking on folks profiles ;)

**Comment by superherointj** [comment]
> @pimeys Any idea why i'm getting the following?

Please follow the troubleshoot section at package file and report back!

https://github.com/NixOS/nixpkgs/blob/941c24d3496d1b4bec95c93d240103d237767bf4/pkgs/development/tools/database/prisma-engines/default.nix#L66

**Comment by malteneuss** [comment]
@superherointj I had seen that troubleshooting list, but it's supposed to help when the prisma binaries are running (at least `prisma --version`.

I was able to pin point the issue to direnv. When running with direnv and `use flake` in `.envrc` i get the previously mentioned error with nodejs:
```bash
$ node -v
/nix/store/dkarbgfm9nwadqk2nycrg6g4gnzirk2f-nodejs-14.19.1/bin/node: /nix/store/lh6d4lflcz4l62xzjv21mniixjfkgv66-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/dkarbgfm9nwadqk2nycrg6g4gnzirk2f-nodejs-14.19.1/bin/node)
```
but when disabling direnv with `direnv deny` and loading the flake manually with `nix develop` it works:
```bash
$ node -v
v16.15.0
```
Something about direnv is not working here on my machine. Is that working for you?

**Comment by DAlperin** [comment]
@malteneuss replace your .envrc with:
```
use flake
eval "$shellHook"
```
And let me know if that works. If it doesn't you should probably open an issue on direnv.

**Comment by superherointj** [comment]
`direnv` is working properly here. I just enter folder and prisma works. I use `nixos-unstable`.

**Comment by malteneuss** [comment]
@DAlperin Thanks for that hint. I have to correct myself however. The issue seems to lie with the IntelliJ/Webstorm terminal, not direnv. Running direnv in a usual terminal window (like Alacritty) outside the IDE works fine. I'll probably open a ticket for the nix executable.

**Comment by superherointj** [comment]
@DAlperin Can we close this issue?

**Comment by DAlperin** [comment]
@superherointj probably fine yeah. It is weird that you can no longer use the node installed by home manager with Prisma. But if that's intended behavior/not a regression then yeah I'm fine closing this one out.

**Comment by superherointj** [comment]
The version is different, I suppose? 

At flakes.nix, I use:
```
{ inputs.home-manager.inputs.nixpkgs.follows = "nixos-unstable"; };
```
This syncs nixpkgs (`nixos-unstable`) with home-manager. Saves space/resources, builds faster, etc.

Does it solve your problem?

**Comment by DAlperin** [comment]
I'm fairly certain I already have that set. I can look into it more later. More likely than not I just got lucky that the version home manager installed was compatible with 3.11.0 and my luck ran out with the version bump. I'll go ahead and close this and open a more specific issue/PR if I find out what exactly happened.
