### ISSUE TITLE
qtcreator unusable

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#17057]
## Issue description

Qt Creator segfaults when an attempt to open the options menu is made and cannot create new projects. It also doesn't seem to be able to open existing projects, with errors similar to the new project issue for qmake projects. This presents a serious obstacle to developing Qt applications on NixOS--even if you're not using it as an IDE, it's by far the easiest way to lay out a GUI. This occurs regardless of the presence of a DE.
#### Segfault
1. `nix-env -iA nixos.qtcreator && qtcreator`
2. Open the "Tools" menu and select "Options"
#### Unable to create a new project
1. `nix-env -iA nixos.qtcreator && qtcreator`
2. Click "New Project," then "Choose," then "Next"
3. Observe "No valid kits found." error
## Technical details

nixos-version is `16.09pre85931.125ffff`
Issues reproduce on master. The segfault does not reproduce on 16.03, but issues creating a new project do.

**Comment by bjornfor** [comment]
I think the "No valid kits found" error is by design. The qtcreator package doesn't bundle a Qt toolkit, you have to install that yourself.

The segfault however... is not by design :-) When I run qtcreator from master branch, I don't get any text in the menus. So when I enter the "Tools" menu, it's all blank. If I select the location where I know "Options" is (last entry), I get the segfault.

**Comment by bjornfor** [comment]
Compared with release-16.03, running qtcreator on master gives these warnings:

```
$ ./result/bin/qtcreator 
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
...
```

I think this may be due to the multiple outputs change.

**Comment by bjornfor** [comment]
Cc @akaWolf, @bbenoist (qtcreator maintainers)

**Comment by bjornfor** [comment]
The QGtkStyle errors can be worked around like this:

```
$ LD_LIBRARY_PATH=$(nix-build --no-out-link -A gtk2.out)/lib ./result/bin/qtcreator 
```

With the above command, at least the menus have text again. But still segfault.

**Comment by Ralith** [comment]
> I think the "No valid kits found" error is by design. The qtcreator package doesn't bundle a Qt toolkit, you have to install that yourself.

Regardless of whether it's a feature on most distros, nothing I try (install qt5Full in the profile, launch from inside a Qt package's nix-shell) can get me past it. It's trying and failing to find something that NixOS needs to be able to point it at.

**Comment by bjornfor** [comment]
I'm unable to reproduce the OP issues. I'm able to build example Qt Widgets projects in qtcreator with ```nix-shell -p qt5Full -p qtcreator --run qtcreator```. (And if it finds no Qt Kits, ```rm -rf ~/.config/QtProject*``` and start again.)

**Comment by Ralith** [comment]
Thanks for having another look! I'm not working on Qt projects at the moment, but it's good to hear things have probably been sorted out.
