### ISSUE TITLE
`sound.enableMediaKeys` values in percent instead of hardware value

### ISSUE THREAD

**Issue by dermetfan** [NixOS/nixpkgs#17068]
## Issue description

`sound.enableMediaKeys` works, but changes the volume by +/- 1 (hardware value). In practice this makes no perceptible difference, at least on some systems. I'd like to propose to change by +/- 1 % instead.

I would send a PR but am not yet involved enough to try and test this myself. The necessary change is merely an additional %-sign in the `amixer` command line in [nixos/modules/services/audio/alsa.nix](https://github.com/NixOS/nixpkgs/blob/release-16.03/nixos/modules/services/audio/alsa.nix#L95):

```
# "Lower Volume" media key
{ keys = [ 114 ]; events = [ "key" "rep" ]; command = "${alsaUtils}/bin/amixer -q set Master 1%- unmute"; }

# "Raise Volume" media key
{ keys = [ 115 ]; events = [ "key" "rep" ]; command = "${alsaUtils}/bin/amixer -q set Master 1%+ unmute"; }
```
## Technical details
- System: `16.09pre85931.125ffff (Flounder)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `16.09pre85931.125ffff`

**Comment by laMudri** [comment]
Do make this an option, and default false for least surprise to upgrading users. I might do it myself if I get some spare time.

**Comment by dermetfan** [comment]
Closing as this has been handled in #21538.
