### ISSUE TITLE
environment.gnome3.excludePackages not working?

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#17065]
## Issue description
After reading the documentation[1], I thought adding

```
  environment.gnome3.excludePackages = with pkgs; [
    gnome3.evolution
  ];
```

would stop nixos-rebuild from building evolution. But apparently not:

```
$ sudo nixos-rebuild -I nixpkgs=. boot -Q
building Nix...
building the system configuration...
these derivations will be built:
...
  /nix/store/9zvf3wml5zgh3gxzcj70wipsgh7x3nd9-evolution-3.18.4.drv
...
```

I looked at the implementation, and it seems excludePackages only allows excluding packages in gnome3.optionalPackages. However, evolution *is* in gnome3.optionalPackages.

So what am I missing?

[1] https://nixos.org/nixos/manual/options.html#opt-environment.gnome3.excludePackages

## Technical details

* System: NixOS: 16.03.git.a0c4a3a (Emu)
* Nix version: 1.11.2
* Nixpkgs version: a0c4a3a

**Comment by rasendubi** [comment]
Enabling gnome3 enables gnome3.evolution-data-server (https://github.com/NixOS/nixpkgs/blob/c78f7c4874cd3c261239cf5fb46ae1dda1c18e11/nixos/modules/services/x11/desktop-managers/gnome3.nix#L89) which brings evolution as a dependency.

**Comment by bjornfor** [comment]
@rasendubi: Aha! That must be it. Thank you! (It would be nice if the system didn't behave like that, but that's something we can improve (way) later.)
