### ISSUE TITLE
NixOS: Store SSH fingerprints as part of configuration

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#17064]
In order to not suffer from man in the middle attacks, it would be nice to have a feature where you can create a mapping between hosts and SSH fingerprints such that you don't get the question 

```
The authenticity of host <x> can't be established.
<snip>
Are you sure you want to continue connecting (yes/no)?
```

Especially when one is using e.g. nixops or similar tooling, it would be possible to have a secure SSH WAN connection between two NixOS systems with zero user-hassle. 

The below paragraphs is mostly directed at the designers of SSH: 
From a security point of view, there is something to be said to even modifying the complete UI of SSH, since it is now optimized for convenience. SSH could also just ask the user for what he/she thinks the fingerprint should be and if it is different, alert the user. Currently, it's designed to be MITM heaven.  

If it had been designed like that initially, automation (like above) would already have been common place, but back in the real world people even blindly trust new keys due to system administrators, who change host keys just because they feel like it. 

So, to make this feature a bit more concrete, it would be

```
config.ssh.hostFingerprints = [["foo.acme.org" "some host key fingerprint"]];
```

**Comment by grahamc** [comment]
Great idea. Does the KnownHosts configuration do it for you? https://github.com/NixOS/nixpkgs/blob/release-16.03/nixos/modules/programs/ssh.nix#L105-L139

**Comment by 0xABAB** [comment]
Love the sarcasm. That probably works just fine. Thanks.
