### ISSUE TITLE
Package Requests:  httm, a ZFS CLI

### ISSUE THREAD

**Issue by byrongibson** [NixOS/nixpkgs#170698]
**Project description**

httm prints the size, date and corresponding locations of available unique versions (deduplicated by modify time and size) of files residing on ZFS snapshots, but can also be used interactively to view and restore such files. httm might change the way you use ZFS snapshots (because ZFS isn't designed for finding for unique file versions) or the Time Machine concept (because httm is very fast!).

**Metadata**

* homepage URL: https://github.com/kimono-koans/httm
* source URL: https://github.com/kimono-koans/httm
* license: Mozilla Public License 2.0
* platforms: unix, linux, darwin

**Comment by zendo** [comment]
[#169637](https://github.com/NixOS/nixpkgs/pull/169637)

**Comment by byrongibson** [comment]
> [#169637](https://github.com/NixOS/nixpkgs/pull/169637)

Oh great thanks!  Searched first but missed this.
