### ISSUE TITLE
pycapnp broken on master (and hydra)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nixpkgs#170796]
### Describe the bug

pycapnp on latest master is now broken.

Apologies I'm short on time.  Hydra shows the failure:

https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.python310Packages.pycapnp.x86_64-linux

**Comment by dtzWill** [comment]
Hmm, okay well progress.  30b30332967dc5caadd84c3d5930221e5c7813d6 broke it, reverting this fixes the build here.

Not sure why this is, or why that didn't break when the commit was made, but at least it's a start.

@SuperSandro2000 can you take a look, or any guess? Thanks!

**Comment by SuperSandro2000** [comment]
fixed in the meanwhile
