### ISSUE TITLE
nextcloud: nextcloud-setup.service fails to enable enabled apps

### ISSUE THREAD

**Issue by arnottcr** [NixOS/nixpkgs#170720]
## Issue description
the `nextcloud-setup.service` script is failing on [the second to last line](https://github.com/NixOS/nixpkgs/blob/a3917caedfead19f853aa5769de4c3ea4e4db584/nixos/modules/services/web-apps/nextcloud.nix#L766). it appears that despite [the comment](https://github.com/NixOS/nixpkgs/blob/a3917caedfead19f853aa5769de4c3ea4e4db584/nixos/modules/services/web-apps/nextcloud.nix#L765), we actually are "fail[ing] when one of them cannot be enabled".

### Steps to reproduce

have `services.nextcloud.extraApps` configured, e.g.
```nix
{config, lib, pkgs, ...}: {
  services.nextcloud.extraApps.spreed = pkgs.fetchNextcloudApp {
    name = "spreed";
    sha256 = "sha256-566oKMVRBjaZ69Ntg4zC7rjW01u0GF4RT4vJnzIl2Zk=";
    url = "https://github.com/nextcloud-releases/spreed/releases/download/v13.0.5/spreed-v13.0.5.tar.gz";
    version = "13.0.5";
  };
}
```
make a change, like a new version, that triggers an upgrade [recte `nextcloud-setup.service`]. run `nixos-rebuild switch`, and see that the configuration change took place, but that the service run failed:
```
warning: the following units failed: nextcloud-setup.service

× nextcloud-setup.service
     Loaded: loaded (/etc/systemd/system/nextcloud-setup.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-04-28 01:47:19 UTC; 44ms ago
    Process: 453410 ExecStart=/nix/store/385yp1x94zykg4h0k6rzk8486aqqzmy3-unit-script-nextcloud-setup-start/bin/nextcloud-setup-start (code=exited, status=1/FAILURE)
   Main PID: 453410 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 7.002s

Apr 28 01:47:19 localhost nextcloud-setup-start[453484]: spreed already enabled
Apr 28 01:47:19 localhost systemd[1]: nextcloud-setup.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 01:47:19 localhost systemd[1]: nextcloud-setup.service: Failed with result 'exit-code'.
Apr 28 01:47:19 localhost systemd[1]: Failed to start nextcloud-setup.service.
Apr 28 01:47:19 localhost systemd[1]: nextcloud-setup.service: Consumed 7.002s CPU time, no IP traffic.
warning: error(s) occurred while switching to the new configuration
```

## Possible fixes

It seems like running `nextcloud-occ app:enable ... || true` or `nextcloud-occ app:enable --force ...`, such that we are actually ignoring the failures would resolve this, but I am unclear on the implications of the `--force` flag: "enable the app regardless of the Nextcloud version requirement".

## Technical details

```
  - system: `"x86_64-linux"`
 - host os: `Linux 5.10.107, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aidalgol** [comment]
I do not think passing the `--force` option is the correct fix, going by that comment.
> Try to enable apps (don't fail when one of them cannot be enabled , eg. due to incompatible version)
To me, that means simply ignore errors.

**Comment by arnottcr** [comment]
agreed, the root cause for this issue were some masked `App "Xxx" cannot be installed because it is not compatible with this version of the server.` log lines. not sure if there is a great way to improve things, since this is definitely a reading comprehension issue, thus I will go ahead and close this.
