### ISSUE TITLE
Wavebox needs a version upgrade to 10.x from 4.x

### ISSUE THREAD

**Issue by kciredor** [NixOS/nixpkgs#170773]
###### Project name
`nix search` name: wavebox
current version: 4.11.3
desired version: 10.101.9-2

###### Notify maintainers
maintainers: @r-ryantm

###### Note for maintainers
Please tag this issue in your PR.

**Comment by auroraanna** [comment]
It seems like it wen closed source? I can't find the source code on their github for the new version. There is no explanation on how to build the program. We could of course just keep sourcing the binary.

**Comment by auroraanna** [comment]
Also why is this in instant-messengers? It's a browser.

**Comment by auroraanna** [comment]
I doubt r-ryantm is gonna update this. It's a bot.
