### ISSUE TITLE
The NVIDIA driver was unable to open 'libnvidia-glvkspirv.so.510.60.02'.  This library is required at run time.

### ISSUE THREAD

**Issue by jrgiacone** [NixOS/nixpkgs#170788]
### Describe the bug
When trying to launch elden ring on nvidia 3080 with the 510.60 drivers I get the following errors with a crash on launch: The NVIDIA driver was unable to open '[libnvidia-glvkspirv.so](http://libnvidia-glvkspirv.so/).510.60.02'.  This library is required at run time.

### Steps To Reproduce
1. nix.pkgs.config.allowUnfree = true;
2. services.xserver.videoDrivers = ["nvidia" ];
3. hardware.opengl.enable = true;
4. programs.steam.eanble = true;

### Expected behavior
The game should launch without crashing as it does on other distributions

### Notify maintainers

@colemickens (just added this here because you said cc you)

**Comment by colemickens** [comment]
cc: me. I have some commits to push related to nvidia, I'll update and see if I can repro this and address it.

**Comment by jrgiacone** [comment]
> cc: me. I have some commits to push related to nvidia, I'll update and see if I can repro this and address it.

are you getting this issue as well?

**Comment by jrgiacone** [comment]
https://inbox.vuxu.org/voidlinux-github/20210727232846.qe2ZUqckbjL_9JyFeNsGMDlIT82dvCtva-DRkE_LeOk@z/T/

Might be some useful stuff in here, it's talking about running sudo ldconfig to fix a similar error, however filesystem is read only

**Comment by colemickens** [comment]
Uh, I'm not actually sure, I might have to rope in my partner to login to Steam to fully test out the Elden Ring scenario. If there's an easier repro or another Vulkan? game or something that triggers it, please let me know.

**Comment by jrgiacone** [comment]
@colemickens I wish, I just tried ghostrunner in dx12 mode and it ran just fine, so its not a dx12 to vulkan issue...

**Comment by jrgiacone** [comment]
@colemickens I figured it out, I'm an idiot, I was installing steam as a package ontop of having programs.steam.enable = true; 

having both created a system conflict!
