### ISSUE TITLE
lazarus package out of date

### ISSUE THREAD

**Issue by laalsaas** [NixOS/nixpkgs#170847]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: legacyPackages.x86_64-linux.lazarus

current version: 2.0.12
desired version: 2.2.0

###### Notify maintainers

maintainers: @raskin 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by eliandoran** [comment]
@laalsaas , I am currently unable to run Lazarus due a start-up crash:

```
Runtime error 203 at $000000000043D487
  $000000000043D487
  $00000000004473BC
```

Do you also happen to have this issue?
