### ISSUE TITLE
question: How to specify fileSystems.X where X = an element of a list

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#17088]
fileSystems is partly defined in `hardware-configuration.nix`. Under the assumption that I don't want to modify system generated files, it seems impossible to fill fileSystems like the following:

```
fileSystems."a" = <whatever>;
fileSystems."b" = <whatever>;
```

by writing a single expression which takes as input a list ["a" "b"], some fold or map function and a single textual reference to fileSystems. 

This probably is not impossible, but it seems non-obvious.

**Comment by danbst** [comment]
Are you talking about something like
```
let lib = (import <nixpkgs> {}).lib;
    mapFunction = fsname: "fsdefinition ${fsname}";
    generator = mapF: lib.fold (x: prev: prev // {fileSystems."${x}" = f x;}) {};
in 
  generator mapFunction [ "a" "b" ]
```
? 

This doesn't work, because `(//)` operator doesn't merge recursively. Still have to figure out which of combinators merge recursively. (There is also https://github.com/NixOS/nix/issues/916 limitation of course)

**Comment by 0xABAB** [comment]
@danbst The generating part is not the hard part. The missing part is the assignment to fileSystems at some point.

**Comment by danbst** [comment]
@0xABAB so, you want something like this:

```
#/etc/nixos/configuration.nix
{pkgs, config, ...}:
let generatedFSs =...;
in {
  various configurations ...;
}
// generatedFSs
```

with `(//)` as recursively merging combinator, right?

**Comment by 0xABAB** [comment]
@danbst Correct, specifically for a value which is defined partially in `hardware-configuration.nix` and partially in `configuration.nix`.

**Comment by danbst** [comment]
You should be possible to do it like this:
```
{pkgs, config, ...}:
let generatedFSs =...;
in {
  various configurations ...;
  imports = [ ... generatedFSs ... ];
}
```
The `imports` clause performs deep merge of NixOS attrsets. Also, there exists `recursiveUpdate` in `lib/attrsets.nix`, which performs similar job.

**Comment by danbst** [comment]
Give me more concrete example of a problem, perhaps the module systemd is exactly what you want.

**Comment by Infinisil** [comment]
This is easily achievable like this:
```nix
fileSystems = genAttrs [ "/" "/foo" ] (x: {
  device = x;
  options = [];
});
```

or 

```nix
fileSystems = map (x: {
  mountPoint = x;
  device = x;
  options = [];
}) [ "/" "/foo" ];
```

The first generates an attrset, the second one a list, both of which can be assigned to fileSystems. In the former case it just uses the attribute names as the `mountPoint` by default. See https://github.com/NixOS/nixpkgs/blob/67b9a11fb1103909f6b85170faab9aab2bccd9cd/nixos/modules/tasks/filesystems.nix#L62 and https://github.com/NixOS/nixpkgs/blob/67b9a11fb1103909f6b85170faab9aab2bccd9cd/nixos/modules/tasks/filesystems.nix#L162 (loaOf = listOrAttributeSet)
