### ISSUE TITLE
python applications propagate python and messes up PATH

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#170887]
### Describe the bug

I have the equivalent of
```
stdenv.mkShell {
  buildInputs = with pkgs; [
		myPythonEnvWithSomeLibraries  # my python.withPackages with 2/3 libraries
        yq  # a python application
	];
}
```
I start my shell with nix develop / nix-shell. Then when I run python I get a basic python != myPythonEnvWithSomeLibraries. I investigated a bit and turns out that `yq` is a python application and it has python in its propagatedBuildInputs. 
When I enter my nix-shell yq's propagated python ends up at the beginning of my PATH, thus shadowing myPythonEnvWithSomeLibraries's interpreter.

I have 2 questions then:
- I think Python applications shouldn't propagate python ? python packaging is so complex that I wonder if I miss something. Sorry if I missed a closed ticket (found https://github.com/NixOS/nixpkgs/issues/10597 that could be related)
- to work around it, how could I remove python from the propagatedBuildInputs of yq ?

### Expected behavior
Python applications should not shadow my shell python interpreter.

### Notify maintainers

cc @FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by FRidh** [comment]
`nix-shell` is a utility for creating a *development environment*. As such it will run hooks. All Python packages propagate the interpreter to the build environment and thereby the hooks. The solution? Use buildEnv or symlinkJoin.

**Comment by polygon** [comment]
Not sure if this was closed prematurely. If `yq` is primarily a Python application, I believe it should not live in `python-modules` and should also use `buildPythonApplication` instead of `buildPythonPackage` which would prevent this issue I believe.

**Comment by Artturin** [comment]
> yq is written as `buildPythonPackage` but in all-packages.nix, it is defined as `yq = python3.pkgs.toPythonApplication python3.pkgs.yq;`. I believe toPythonApplication should strip python from the propagated inputs: I dont want to develop with it, I want the application. Otherwise I would have selected the python module `yq`



https://github.com/NixOS/nixpkgs/blob/27078775c0b3f77bdf4cf9fd787842cf5c823dce/pkgs/top-level/python-packages.nix#L82-L91

propagatedBuildInputs is not stripped
adding `      propagatedBuildInputs = [];`

fails with
```
python3.9-yq> ERROR: Could not find a version that satisfies the requirement toml>=0.10.0 (from yq) (from versions: none)
python3.9-yq> ERROR: No matching distribution found for toml>=0.10.0
```

**Comment by FRidh** [comment]
>  I believe toPythonApplication should strip python from the propagated inputs

That's on purpose not done to avoid a rebuild.

**Comment by teto** [comment]
>That's on purpose not done to avoid a rebuild.

ha I seebut that may be worth a comment then, do you mind if I add one ?

**Comment by FRidh** [comment]
> ha I seebut that may be worth a comment then, do you mind if I add one ?

Not at all, good idea!

**Comment by teto** [comment]
@FRidh I've opened https://github.com/NixOS/nixpkgs/pull/179318 . Feel free to push directly to the branch if you are not happy with phrasing.
While writing the PR, I wondered if we could not have the propagatedBuildInputs be appended to the PATH rather than prepended ?

**Comment by teto** [comment]
what I had in mind is :
- for python applications, append "python" to path so that in a nix-shell, my selected python takes precedence (and the python application works regardless of the presence of a python in PATH)
- for python libraries, keep as is, aka prepend "python" to path 

but I suppose it wont avoid a rebuild so that's not a good idea anyway, let's forget about it xD
