### ISSUE TITLE
rust{Beta,Unstable} is outdated

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#17097]
## Issue description

Our packages for `rustBeta` and `rustUnstable` are outdated and don't seem to compile anymore.

I've worked on packaging current `beta`. Currently, `rustc` builds & works fine but `cargo` fails to build. I'm open for any suggestions/ideas.

Current status is at https://github.com/the-kenny/nixpkgs/tree/rustc-beta-1.11.0

**Comment by matthiasbeyer** [comment]
@the-kenny I guess this can be closed as #16920 was merged, right?

**Comment by sjmackenzie** [comment]
`head.nix` doesn't work as there is reference to a `use-rustc-1.9.0.patch` in the `patches` folder.

**Comment by the-kenny** [comment]
@matthiasbeyer No, not yet. `beta` and `unstable` are still broken. 

I've got `beta` and a corresponding `cargo` working, now building `unstable`. Will open a PR as soon as it's working for review.

**Comment by the-kenny** [comment]
The PR above fixes `rustBeta` but fails for `rustUnstable` as the `tcp-stress-test.rs` fails. I'm not yet sure if this is an upstream issue or not.

**Comment by the-kenny** [comment]
My hydra is building `rustBeta` and `rustUnstable` right now. Will push these as soon as it succeeds.

**Comment by the-kenny** [comment]
For reference: http://hesperos.tarn-vedra.de:3000/jobset/nixpkgs/rust-updates

**Comment by sjmackenzie** [comment]
It would be really excellent if rustUnstable + rustBeta were working.

Hopefully Nix can be a strong foundation to work on.

Great seeing this work!

kr/sjm

**Comment by the-kenny** [comment]
8cd3e1e :tada: :beers:

**Comment by Ericson2314** [comment]
Didn't we figure out last time that beta should be building unstable?

**Comment by the-kenny** [comment]
John Ericson <notifications@github.com> writes:

> Didn't we figure out last time that beta should be building unstable?

It does, we pass `rustBeta` from `all-packages.nix:5505` to `rustUnstable`.

**Comment by Ericson2314** [comment]
Oh ok. I wrongly assumed everything was just inherited.

**Comment by qknight** [comment]
just tried f731ca3 and rustUnstable isn't building:

```
source root is rust-822166b
patching sources
applying patch /nix/store/7m1x11i60p4xkb0wkmv591vajahdbvfi-disable-lockfile-check.patch
patching file src/tools/tidy/src/main.rs
applying patch /nix/store/21pn42r95749rgmrzkkmfmhmnspjnw8y-grsec.patch
patching file src/test/run-make/relocation-model/Makefile
Hunk #1 succeeded at 2 with fuzz 1.
Hunk #2 succeeded at 17 with fuzz 2 (offset -1 lines).
removed 'src/test/run-make/linker-output-non-utf8/Makefile'
removed 'src/test/run-make/linker-output-non-utf8/library.rs'
removed 'src/test/run-make/linker-output-non-utf8/exec.rs'
removed directory 'src/test/run-make/linker-output-non-utf8/'
rm: cannot remove 'src/test/run-pass/issue-36023.rs': No such file or directory
builder for ‘/nix/store/pqdfk5xpja6yhldwybqsv938fhkdy3h7-rustc-beta-2016-08-17-g822166b.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/9rdis426q568gg5backzydv76vgpal4p-cargo-master-2016-07-25.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/9rdis426q568gg5backzydv76vgpal4p-cargo-master-2016-07-25.drv’ failed
```
