### ISSUE TITLE
tmux on build failure darwin

### ISSUE THREAD

**Issue by sufianrhazi** [NixOS/nixpkgs#17092]
## Issue description

Issue #16224 appears to have introduced a regression in darwin builds, this was detected by the automated build: https://hydra.nixos.org/build/36852692/log

Reverting commit 94627e658beabf2b4c766d31afa273a55879b46a causes a successful build.

### Steps to reproduce

On OS X (currently running OS X 10.11.5), run `nix-env -i tmux`

Output of the failed `nix-env -i tmux` can be found in this gist: https://gist.github.com/sufianrhazi/470f0854f6f23610e197485c50822338

## Technical details

* System: OS X 10.11.5
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre87025.cb53771

**Comment by dmgm** [comment]
still a problem with Nixpkgs version 16.09pre87038.039f0e5

**Comment by j-hao** [comment]
change output order works for me:

```
outputs = [ "bin" "out" "man" ];
```
or change propagatedBuildOutputs like https://github.com/NixOS/nixpkgs/blob/3748cdc791b990ab6df6ee9f66f457f10cd5c949/pkgs/tools/system/awstats/default.nix#L18
