### ISSUE TITLE
wineWowPackages.staging fails to build

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#170946]
### Describe the bug

While trying to create https://github.com/NixOS/nixpkgs/pull/170943 I noticed that my buils were failing, but even rolling back to current master, wine won't build for me. This is on 57ba746ca7b.

```
$ nix-build -A wineWowPackages.staging --keep-failed --check
[...]
error: builder for '/nix/store/x2j1290fkwyzh200fxikwx6i59jwpcif-wine-wow-7.4-staging.drv' failed with exit code 2;
       last 10 log lines:
       > tools/winebuild/winebuild -b x86_64-w64-mingw32 -w --implib -o dlls/kernelbase/libkernelbase.cross.a --export \
       >   /build/wine-7.4/dlls/kernelbase/kernelbase.spec
       > tools/winebuild/winebuild -b x86_64-w64-mingw32 -w --implib -o dlls/sechost/libsechost.cross.a --export \
       >   /build/wine-7.4/dlls/sechost/sechost.spec
       > tools/winebuild/winebuild -b x86_64-w64-mingw32 -w --implib -o dlls/setupapi/libsetupapi.cross.a --export \
       >   /build/wine-7.4/dlls/setupapi/setupapi.spec
       > /nix/store/6nsvi3ar932jjlslpgywas2fkzmvasg8-x86_64-w64-mingw32-binutils-2.38/bin/x86_64-w64-mingw32-dlltool: dlls/rpcrt4/librpcrt4.delay.a: error reading rpcrt4_dll_t.o: No such file or directory
       > winebuild: /nix/store/6nsvi3ar932jjlslpgywas2fkzmvasg8-x86_64-w64-mingw32-binutils-2.38/bin/x86_64-w64-mingw32-dlltool failed with status 1
       > make: *** [Makefile:171142: dlls/rpcrt4/librpcrt4.delay.a] Error 1
       > make: *** Waiting for unfinished jobs....
       For full logs, run 'nix log /nix/store/x2j1290fkwyzh200fxikwx6i59jwpcif-wine-wow-7.4-staging.drv'.
```

### Steps To Reproduce

On master (57ba746ca7b):
$ nix-build -A wineWowPackages.staging --keep-failed --check

### Expected behavior

Wine staging builds successfully, as it did before.

### Additional context

I've tried to bisect this issue (I suspect that the gcc compiler or binutils bump that happened since the 7.4 update in nixpkgs may be causing the issue), but my machine has been chugging along for twelve hours on 52f8cf58a45 and I still haven't reached the actual wine build yet, so that is turning out to be impractical for me. Commit dd6c7096d629d9c6814c6980180254d3336a9a3b (which bumps the wine version to 7.4) works for me.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 22.05 (Quokka), 22.05.20220426.cdb0887`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220411_f7276bc`
 - channels(frijters): `""`
 - channels(root): `"nixos, nixos-unstable-20.09pre225264.683c68232e9"`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by SFrijters** [comment]
Continued my bisection - 52f8cf58a4504e5e219faebffa51033e400e3aec builds.

**Comment by SFrijters** [comment]
At e2d150f6b17175c16b8bfeb452790efb1170bf44 mingw fails to build...

```
error: builder for '/nix/store/nl2vwg5k1m1wldgnh5wch0qcbzirlxk3-mingw-w64-i686-w64-mingw32-9.0.0.drv' failed with exit code 2;
       last 10 log lines:
       > i686-w64-mingw32-dlltool: failed to open temporary head file: D3DCompiler_dll_h.o: No such file or directory
       > make[3]: *** [Makefile:83807: lib32/libd3dcompiler_36.a] Error 1
       > mv -f crt/.deps/lib32_libucrt_extra_a-ucrtbase_compat.Tpo crt/.deps/lib32_libucrt_extra_a-ucrtbase_compat.Po
       > rm lib32/libapi-ms-win-core-winrt-registration-l1-1-0.a lib32/libapi-ms-win-core-winrt-error-l1-1-1.a lib32/libapi-ms-win-ro-typeresolution-l1-1-0.a lib32/libapi-ms-win-core-winrt-error-l1-1-0.a lib32/libapi-ms-win-core-winrt-l1-1-0.a lib32/libapi-ms-win-core-winrt-roparameterizediid-l1-1-0.a lib32/libapi-ms-win-core-synch-l1-2-0.a lib32/libapi-ms-win-core-winrt-robuffer-l1-1-0.a lib32/libapi-ms-win-core-winrt-string-l1-1-0.a
       > make[3]: Leaving directory '/build/mingw-w64-v9.0.0/mingw-w64-crt'
       > make[2]: *** [Makefile:13841: all] Error 2
       > make[2]: Leaving directory '/build/mingw-w64-v9.0.0/mingw-w64-crt'
       > make[1]: *** [Makefile:364: all-recursive] Error 1
       > make[1]: Leaving directory '/build/mingw-w64-v9.0.0'
       > make: *** [Makefile:305: all] Error 2
       For full logs, run 'nix log /nix/store/nl2vwg5k1m1wldgnh5wch0qcbzirlxk3-mingw-w64-i686-w64-mingw32-9.0.0.drv'.
```

**Comment by SFrijters** [comment]
So e9cfdc6b77fefd77ed04a7eb3e3e0796dfca270c is fine, but e2d150f6b17175c16b8bfeb452790efb1170bf44 has issues (see above). @lovesegfault any idea what might be going on? Testing this one commit took another 12+ hours so brute-forcing bisecting to when the mingw error changes to a wine error  it is not a good option for me.

**Comment by SFrijters** [comment]
Possible fix / related https://github.com/NixOS/nixpkgs/pull/171147

**Comment by vcunat** [comment]
No, not really related.  It's good to have a closer look at the logs.  It's always failing to find some generated file, so `--cores 1` works around that reliably, but it takes a long time.  [On Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/wineWowPackages.staging.x86_64-linux) it seems OK, so perhaps its default `--cores 2` suffice usually.

**Comment by SFrijters** [comment]
Still (slowly) bisecting the loss of enableParallelBuild: 

```
git bisect start
# bad: [8ba23e138d9714bf309facf0003d69b1f8b86265] Merge remote-tracking branch 'nixpkgs/staging-next' into staging
git bisect bad 8ba23e138d9714bf309facf0003d69b1f8b86265
# good: [35619ce1e513fa044b341f62a633deaa458eed06] Merge pull request #165453 from helsinki-systems/feat/systemd-manager-environment
git bisect good 35619ce1e513fa044b341f62a633deaa458eed06
# good: [711906d8ec0d7a306973375bd40396cc33136cb2] wine{unstable,staging}: 7.2 -> 7.4, vkd3d: 1.2 -> 1.3
git bisect good 711906d8ec0d7a306973375bd40396cc33136cb2
# good: [e9d2785e6b2bccfeb5b23d1eb3c474d0877861ec] cppy: 1.1.0 -> 1.2.0
git bisect good e9d2785e6b2bccfeb5b23d1eb3c474d0877861ec
# good: [474f700b19782fd6bdaf28fe77627d8d991ee14a] Merge #166381: knot-dns: 3.1.6 -> 3.1.7
git bisect good 474f700b19782fd6bdaf28fe77627d8d991ee14a
# good: [f97a925ba30ae62216b4bd00ba182308b1951977] Merge pull request #165405 from SuperSandro2000/pyparsing
git bisect good f97a925ba30ae62216b4bd00ba182308b1951977
```

I still suspect the binutils update causes something, but we'll see.

**Comment by Nephyrin** [comment]
This is likely https://sourceware.org/bugzilla/show_bug.cgi?id=28885

See also https://github.com/Frogging-Family/wine-tkg-git/issues/764

**Comment by SFrijters** [comment]
Oh, great find! That seems like the culprit for sure. The commit I just skipped in my bisect was exhibiting the mingw build issue.

**Comment by SFrijters** [comment]
Currently wine has its `enableParallelBuilding` attribute set to `false` which allows it to build without issues.
I will make a PR to put it back to `true` after #172617 reaches master and close this issue once that has been merged.

**Comment by mweinelt** [comment]
As the binutils fix is part of the final staging-next iteration for 22.05 I think it would be important to have `enableParallelBuilding` reenabled on 22.05.

**Comment by SFrijters** [comment]
FWIW, I'm keeping an eye on it. But would it be possible to make a PR against staging-next directly with a commit just to enable the parallel wine build? When I made the binutils PR the flag was not yet set to `false` on staging so I couldn't add a commit for that at the time.

**Comment by mweinelt** [comment]
I don't believe wine causes many rebuilds, so that certainly would be an option.

**Comment by SFrijters** [comment]
Closed via https://github.com/NixOS/nixpkgs/pull/172617 and  https://github.com/NixOS/nixpkgs/pull/173981 .
