### ISSUE TITLE
Scala 3

### ISSUE THREAD

**Issue by schlichtanders** [NixOS/nixpkgs#170911]
**Project description**
Scala 3 is more than a year old. It would be nice to have it packaged in nixpkgs as well.

Maybe it is, but I couldn't find it under "scala-3" or respective versions.

**Metadata**

* homepage URL: https://scala-lang.org/
* source URL: https://github.com/lampepfl/dotty
* license:  Apache-2.0 License
* platforms: unix, linux, darwin, ...

**Comment by misuzu** [comment]
[Dotty](https://github.com/lampepfl/dotty) is already packaged.

**Comment by raboof** [comment]
Indeed: the Scala 3 compiler started out under the codename 'dotty', and that's how it was packaged initially in nixpkgs.

Now that dotty has become the 'official' scala 3 compiler (see also b0f0e1d175655a529a250aa6ec1a73c703803e0a), we should probably rename the package to as well?

/cc @karolchmist @virusdave @NeQuissimus

**Comment by NeQuissimus** [comment]
Feel free to update, rename and alias the old `dotty` name :)
Maybe `scala` should point at `scala_2` and `scala_3` can be added
