### ISSUE TITLE
python3Packages.spacy won't build on Darwin x86

### ISSUE THREAD

**Issue by AxelTLarsson** [NixOS/nixpkgs#171055]
### Describe the bug

python3Packages.spacy won't build on my macOS x86 machine apparently due to ‘python3.9-parameterizedtestcase-0.1.0’ being marked as broken.

    error: Package ‘python3.9-parameterizedtestcase-0.1.0’ in /nix/store/m0sa64bwv0iaa1b4d5wmznmm83k5qbq1-nixpkgs/nixpkgs/pkgs/development/python-modules/parameterizedtestcase/default.nix:26 is marked as broken, refusing to evaluate.

### Steps To Reproduce

1. `nix-shell -p "python3Packages.spacy"`

### Expected behavior

The spacy module is made available for use in my Python environment.

### Notify maintainers

@mweinelt 

### Metadata

```console
❯  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(axel): `"home-manager, nixpkgs"`
 - nixpkgs: `/Users/axel/.nix-defexpr/channels/nixpkgs`

```

**Comment by r-burns** [comment]
The dependency on parameterizedtestcase is via our currently packaged version of smart-open. Bumping smart-open to 6.0.0 will drop the dependency on parameterizedtestcase, but spacy also depends on pathy which does not yet support smart-open 6.0.0 and will require upstream changes.

https://github.com/RaRe-Technologies/smart_open/releases/tag/v6.0.0
https://github.com/justindujardin/pathy
