### ISSUE TITLE
Systemd services with generated names fail silently

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#17102]
## Issue description

When you create service with dynamically created name (created from string, like "service-name" or systemd.services."${name}") when job fails there is no error message and everything looks OK (it fails only sometimes but it should fail always when there is an error)
### Steps to reproduce

Create service like that:

```
systemd.services."crazy" = {                                            
 wantedBy = ["multi-user.target"];                                     
 after = ["network.target"];                                           
 script = "exit 1;";                                                   
};
```

nixos-rebuild test
## Technical details
- System: (NixOS: 16.09pre85931.125ffff (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre85931.125ffff

**Comment by Profpatsch** [comment]
(triage) can you still reproduce this?

**Comment by spinus** [comment]
yes, still can reproduce but I learnt that it's systemd feature not particularly related to nix. 
Thanks for triaging!
