### ISSUE TITLE
beancount-language-server does not build

### ISSUE THREAD

**Issue by bhankas** [NixOS/nixpkgs#171138]
### Describe the bug
beancount-language-server is currently being built as a node package (https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/node-packages/node-packages.nix#L82268), it is:

- outdated in nixpkgs
- not built and cached by cahce.nixos.org
- fails to build when added to configuration.nix

I believe the reason being it is really a Rust package: https://github.com/polarmutex/beancount-language-server

I tried to create a simple derivation to build it as a Rust package and it seems to be working: https://github.com/bhankas/nixpkgs/commit/b29b62b349475783de9ce183d775a36b8ddc1c43

I would have opened a PR, but since the package is already present under nixpkgs (although in arguably wrong location), the source is same and I am not sure how the case should be handled. Any direction welcome.

If someone wants to cherry-pick my commit and contribute themselves, that is fine as well.

### Steps To Reproduce
1. Add `nodePackages.beancount-langserver` in configuration.nix
2. `nixos-rebuild` boot`

### Expected behavior
`beancount-language-server` should be available in $PATH after nixos-rebuild

### Notify maintainers
Not sure who the maintainer is, as the source is a 4+MB json file.

**Comment by polarmutex** [comment]
I can work on this since I maintain the app in question
