### ISSUE TITLE
Why is GRUB enabled by default?

### ISSUE THREAD

**Issue by Madouura** [NixOS/nixpkgs#171133]
Just an odd thing I noticed, I'm not sure this should be ideally the case.
I feel it may be a good thing to generate by default by ``nixos-generate-config`` per-platform (x86, standard desktop/laptop) but having it on by default seems somewhat unnecessary.
We support several different platforms, some of which don't need or use GRUB, or the user may want to use another bootloader instead.
Having GRUB enabled by default also means the user has to explicitly disable GRUB if the user doesn't want to use it.

**Comment by hqurve** [comment]
I don't think GRUB is enabled by default https://github.com/NixOS/nixpkgs/blob/nixos-21.11/nixos/modules/system/boot/loader/grub/grub.nix#L101. Nixos-search might have some bug ....

Also, `nixos-generate-config` auto chooses a bootloader (https://github.com/NixOS/nixpkgs/blob/nixos-21.11/nixos/modules/installer/tools/nixos-generate-config.pl#L625-L653). For me on a desktop, it chose systemd-boot.

**Comment by Madouura** [comment]
Double false = true;
Unless I'm misunderstanding, ``boot.isContainer`` is still false at ``nixos-rebuild``, assuming you don't enable it manually, thus ``default = !config.boot.isContainer;`` becomes true. Thus, GRUB is technically enabled by default.

**Comment by Madouura** [comment]
We should probably have grub disabled by default with a hard ``false`` and have ``virtualisation/nixos-containers.nix`` instead manually force grub to be false if needed there.

**Comment by hqurve** [comment]
> Unless I'm misunderstanding, boot.isContainer is still false at nixos-rebuild or nixos-install, assuming you don't enable it manually, thus default = !config.boot.isContainer; becomes true. Thus, GRUB is technically enabled by default.

Ahh, I missed the `!` symbol.

I guess it might make more sense to have all bootloaders disabled by default and just throw an error if a bootloader is required but none are enabled.

**Comment by Madouura** [comment]
>and just throw an error if a bootloader is required but none are enabled.

How would you go on about doing that?
Gonna submit a PR removing all the ``boot.loader.grub.enable = false`` and changing the default to false, etc.

**Comment by hqurve** [comment]
I'm not too sure if its possible to detect when a bootloader is required. I tried disabling systemd-boot and setting boot.loader.grub.enable to false but my config built without any errors. That being said, I'm not brave enough to actually run nixos-rebuild with elevated permissions

**Comment by Madouura** [comment]
Not working on this.
