### ISSUE TITLE
`services.home-assistant.openFirewall = true` causes "obsolete option" warning for `port`

### ISSUE THREAD

**Issue by lilyball** [NixOS/nixpkgs#171198]
### Describe the bug
On nixos-unstable it appears that `services.home-assistant.port` was renamed to `services.home-assistant.config.http.server_port`. However the config line for applying the `services.home-assistant.openFirewall` option still references the obsolete option name:

https://github.com/NixOS/nixpkgs/blob/e10da1c7f542515b609f8dfbcf788f3d85b14936/nixos/modules/services/home-automation/home-assistant.nix#L363

This means that enabling `openFirewall` produces a warning like

```
trace: Obsolete option `services.home-assistant.port' is used. It was renamed to `services.home-assistant.config.http.server_port'.
```

Relatedly, using this without defining `services.home-assistant.config` also throws an error ``The option `services.home-assistant.config' is used but not defined.``, as the renamed option is now part of the `config` tree (which is defined as a `nullOr submodule` with no default value).

### Steps To Reproduce

```nix
{
  services.home-assistant = {
    enable = true;
    openFirewall = true;
    # config.default_config = {};
  };
}
```

```console
> nix flake check
trace: Obsolete option `services.home-assistant.port' is used. It was renamed to `services.home-assistant.config.http.server_port'.
error: The option `services.home-assistant.config' is used but not defined.
```

### Expected behavior
`openFirewall = true` should not produce any warnings or errors.

Uncommenting the `config.default_config` line removes the error but leaves the warning.

### Notify maintainers
@fab @globin @hexa @mic92

### Metadata

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3.1`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.8.0`
 - channels(lily): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.11pre330171.92204897f3d"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

(though the flake output in question is for `aarch64-linux`)

**Comment by dotlambda** [comment]
You used the wrong GitHub handles for some of the maintainers.
cc @fabaff @mweinelt

**Comment by mweinelt** [comment]
> Is there any simple way to look up the github handles for a given module?

https://github.com/NixOS/ofborg/issues/568#issuecomment-962072864
