### ISSUE TITLE
Issue stats badges on readme.md don't load anymore

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#17114]
The "build: passing" badge works fine, but that comes from travis. The other two (that displayed stats about our PR merge rate and issue close rate) fail to load on all my devices.

**Comment by copumpkin** [comment]
Looks like http://www.issuestats.com/ is just down and has been for a couple of days? cc @jagajaga who I think originally added the stats badges.

**Comment by grahamc** [comment]
Based on the issues on the repo of issuestats.com, they made it as part of a GitHub Data Challenge and don't really maintain it outside of accepting PRs. We could switch to isitmaintained.com but they don't have very nice things to say about us :) http://isitmaintained.com/project/nixos/nixpkgs

[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/nixos/nixpkgs.svg)](http://isitmaintained.com/project/nixos/nixpkgs "Average time to resolve an issue")

[![Percentage of issues still open](http://isitmaintained.com/badge/open/nixos/nixpkgs.svg)](http://isitmaintained.com/project/nixos/nixpkgs "Percentage of issues still open")

**Comment by grahamc** [comment]
Looking now, IssueStats says our issues are closed in 5 days (the second badge just loaded)

**Comment by matthewbauer** [comment]
I don't know how useful this is.. We have a lot of issues and pull requests that are left open for long periods of time. Some issues are addressed quickly but take a long time to resolve.

What would be really cool is if someone could make some badges that incorporate information from Hydra regarding the last evaluation.

**Comment by copumpkin** [comment]
These seem to be working again now, so I'm closing this. Agree with @matthewbauer's suggestion, but it's probably worth submitting a ticket against Hydra for that instead of putting it in a comment here.

**Comment by jagajaga** [comment]
We can probably remove this badge.

**Comment by grahamc** [comment]
This weekend I made a readme-badge thing which shows: https://jsfiddle.net/45g501mw/ -- is that interesting enough to show on our readme? :) (I made it to examine the data, turns out we do pretty  
good.) https://gist.github.com/grahamc/878017f8ce04d2f1a8404088c0214618

(specifically looking for a +1 / -1 @domenkozar or @edolstra )

**Comment by domenkozar** [comment]
@grahamc how would we use that badge? Can we host the logic somewhere?

**Comment by grahamc** [comment]
Here's where we are:

 - I've built the data collector
 - I have it running on a regular basis to update
 - I have the SVG output I want to make (linked above)
 - Next is to wire up the data to the SVG output over HTTP

I was planning on (and am currently) hosting it on my own, but I don't mind it running elsewhere. It requires a mysql database.

A couple notes:

 - our actual number is 56% merged in the first day.
 - I can come up with different data to output, if there are specific ideas.
 - @copumpkin mentioned showing a distribution of all the times, I can do this (see the linked gist above) but it'd be much bigger than the widget currently is :)

**Comment by Profpatsch** [comment]
The one existing badge at the moment seems to work just fine.
