### ISSUE TITLE
{citra,duckstation}: Cubeb audio backend doesn't work on SDL interface

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#171173]
### Describe the bug
Cubeb is an audio backend often used in emulators, and it doesn't work on two specific emulators: Citra and Duckstation. Launch a game with this backend, and there will be no audio.

Both emulators also have an SDL audio backend that works, but Cubeb is the default one.

Strangely, this issue affects only the SDL interface: the emulators also have a Qt interface, and there is no issue there. (Do not confuse the SDL interface with the SDL audio backend!)

### Steps To Reproduce
1. Install Citra or Duckstation;
2. You don't have to change any settings, the audio backend is already Cubeb;
3. Launch a game from the SDL interface (`citra /path/to/game` or `duckstation-nogui /path/to/game`);
4. No audio.

### Expected behavior
There is audio when playing the game.

### Additional context
The issue isn't new, it's probably there from the very beginning.
On Duckstation the problem was even worse, the Cubeb audio backend didn't work on the Qt interface either. I have no idea what happened that made it work.
There are comments on both their respective `default.nix` about this issue. They should be removed when this is solved (and Duckstation's one is outdated).

Dolphin should experience the same issue, but it doesn't. Cubeb initializes just fine (logs say it uses the pulse backend).

By the way, are there any other emulators with an SDL interface other than these three to test?

Citra says:
```
[   0.253248] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:31: cubeb_init failed
```
And Duckstation:
```
[    2.3029] I/HostInterface: Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer size = 2048
[    2.3032] E(OpenDevice): Could not initialize cubeb context: -1
[    2.3032] E(ReportError): Failed to create or configure audio stream, falling back to null output.
```
Which is logged from here: https://github.com/stenzek/duckstation/blob/master/src/frontend-common/cubeb_audio_stream.cpp#L37.

### Notify maintainers
Citra: @abbradar 
Duckstation: @guibou @AndersonTorres 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2-zen3, NixOS, 22.05 (Quokka), 22.05pre372388.87d34a6b898`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - channels(<redacted>): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I'm using Pipewire with Wireplumber (and used media-session in the past).

**Comment by S-NA** [comment]
`LD_LIBRARY_PATH` likely needs to be populated. libcubeb is also used in Firefox and you can see an example of populating `LD_LIBRARY_PATH` in the wrapper.

**Comment by SuperSamus** [comment]
I gave a look at Firefox's derivation, and Cubeb isn't in `LD_LIBRARY_PATH`.
Cubeb is vendored in all of these applications (Citra, Duckstation, Dolphin and Firefox) and I guess statically linked too, so I doubt that's the problem.

**Comment by S-NA** [comment]
Sorry I should have clarified. libcubeb uses `dlopen()`, you need libpulse, sndio, jack and friends in `LD_LIBRARY_PATH`.
