### ISSUE TITLE
Can't install LaTeX with doc: collision dvipdfmx

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#171230]
### Describe the bug
In NixOs unstable, I installed Texlive with the documentation:
```
    (texlive.combine {
      inherit (texlive) scheme-full;
      pkgFilter = pkg: lib.elem pkg.tlType [ "run" "bin" "doc" ];
    })
```
to avoid this issue https://github.com/NixOS/nixpkgs/issues/171218, I also need to switch first my configuration to (maybe a smaller number would also work):
```
  security.pam.loginLimits = [{
    domain = "*";
    type = "soft";
    item = "nofile";
    value = "262144";
  }];
```

then I get an error:
```
building '/nix/store/abkk30qqmcz8glismg1ahcyg42wjv08y-texlive-combined-2021.drv'...
error: collision between `/nix/store/qhgzxnry5lljagbsv9chafjcmgn6p186-texlive-dvipdfmx.doc-61101/doc/man/man1/dvipdfmx.1' and `/nix/store/0h425354rllsyzn3xz2pb6iyfh9hqy9y-texlive-bin-2021-doc/doc/man/man1/dvipdfmx.1'
error: builder for '/nix/store/abkk30qqmcz8glismg1ahcyg42wjv08y-texlive-combined-2021.drv' failed with exit code 25
error: 1 dependencies of derivation '/nix/store/6wgslqcfbkpjird7rbik39k4kg7ya5nb-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/95ic53n912pjin89i8qjcks9f49mkr5m-nixos-system-bestos-22.05pre-git.drv' failed to build
```

### Notify maintainers

@xworld21 @veprbl

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220411_f7276bc`
 - channels(leo): `"nixos-unstable-22.05pre369988.1ffba9f2f68, local-nixos-unstable-22.05pre366144.bc4b9eef3ce, home-manager, local-nixpkgs-unstable-21.11pre304920.dd98b100651, nixos-20-03-20.03.3328.6d1a044fc9f, test"`
 - channels(root): `"nixos-21.11pre325514.a4bf4434570"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by veprbl** [comment]
We should add a regression test for this one.

**Comment by tobiasBora** [comment]
So basically two packages (texlive and dvipdfmx) provide the same man page for dvipdfmx, right?

Note that as a workaround, one can do:
```
    ((texlive.combine {
      inherit (texlive) scheme-full;
      pkgFilter = pkg: lib.elem pkg.tlType [ "run" "bin" "doc" ];
    }).override (args: { ignoreCollisions = true; }))
```
to ignore collisions.
