### ISSUE TITLE
SooperLooper install error

### ISSUE THREAD

**Issue by diegueins680** [NixOS/nixpkgs#17135]
## Issue description
When adding the sooperlooper package to configuration.nix, and trying to rebuild the system, I get errors. This is a link to the whole output: http://pastebin.com/QEupPdFv

### Steps to reproduce
1. Add sooperlooper to environment.systemPackages in configuration.nix
2. Run sudo nixos-rebuild test

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre85931.125ffff (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre85931.125ffff"

**Comment by knedlsepp** [comment]
See: https://github.com/NixOS/nixpkgs/pull/17095

**Comment by matthewbauer** [comment]
Can this be closed then?

**Comment by diegueins680** [comment]
I got my NixOs laptop stolen just after opening this issue, but it seems the error is gone, so I'm closing this issue.
