### ISSUE TITLE
Bisected Regression: Bismuth Broken

### ISSUE THREAD

**Issue by Obikawa** [NixOS/nixpkgs#171318]
@pasqui23 

Commit dca930fa9f9a192e17f5839e727b2402ce39db63 broke Bismuth for me.
Since then it does not start up and Plasma works as if it was never installed.

I use Plasma Wayland with almost no KDE customizations in the configuration flake.
I am open to more questions, if needed.

**Comment by pasqui23** [comment]
Have you tried:
1) Logging out
2) Loggin in to a termin via ctrl+alt+F1
3) `trash .{cache,config}/{k*,plasma*}
4) going back to the gui by ctrl+alt+F7

In the past I often fixed KDE update problems this way.

**Comment by Obikawa** [comment]
@pasqui23 Could you tell me, whether Bismuth v3 works for you in Wayland Plasma?

**Comment by pasqui23** [comment]
I am using it right now

**Comment by Obikawa** [comment]
Thank you. That greatly increases confidence in the config file conflict hypothesis.

**Comment by Obikawa** [comment]
I caved in and created a fresh home folder for my user account.

Bismuth now works. I still have no idea what was wrong, but I do not care anymore.

**Comment by rimmington** [comment]
For anyone else who stumbles across this: `trash ~/.cache/{k*,plasma*}` fixed this issue for me, so give that a shot.

**Comment by AngryAnt** [comment]
I wasn't quite so nuclear about it, but I'm sure you could dial it in further than the specific bits I trashed to get back on track:
- `~/.cache/ksplash`
- `~/.cache/ksplashqml`
- `~/.cache/kwin`
- `~/.cache/kwin_rules_diag`
- `~/.cache/plasmashell`
- `~/.cache/plasmawindowed`

**Comment by SuperSamus** [comment]
I guess it's related to #177720?
