### ISSUE TITLE
rspamd's sytemd unit has invalid RuntimeDirectory setting

### ISSUE THREAD

**Issue by r-raymond** [NixOS/nixpkgs#17144]
## Issue description
The systemd unit for rspamd specifies
`RuntimeDirectory = /var/lib/rspamd`

However, the documentation of `RuntimeDirectory` clearly states that
1) All runtime directories need to be in /run
2) Only relative paths are accepted

This prevents the rspamd daemon from working correctly

### Steps to reproduce
Enable
`services.rspamd.enable = true;`
Check the created systemd file

## Technical details

* System: NixOS 16.03.1093.368214c (Emu)
* Nix version:  1.11.2
* Nixpkgs version: 16.03.1093.368214c

**Comment by joachifm** [comment]
It should probably just use "rspamd" as the runtime directory. @r-raymond are you interested in submitting a PR for this?

**Comment by r-raymond** [comment]
@joachifm in principle yes, however I don't know what other implications this change may have (maybe this directory is also mentioned elsewhere).

**Comment by joachifm** [comment]
cc @avnik

**Comment by joachifm** [comment]
From looking at the service module, I wonder whether `WorkingDirectory` was intended here. I also see a few other things that could be cleaned up, but I don't use this myself so I'm hesitant to do anything about it ...

**Comment by avnik** [comment]
I'll take a look folks, ty for pointing on issue
