### ISSUE TITLE
Fix sile for darwin platforms now that there is a makeBinaryWrapper solution

### ISSUE THREAD

**Issue by zaphar** [NixOS/nixpkgs#171473]
### Describe the bug
The sile is currently broken on darwin platforms due to issue #23018. The solution for that is now fixed however. It would be nice if we could get sile deployable on darwin again using that solution.

### Steps To Reproduce
1. Use a darwin based platform (MacOS)
2. run `nix-shell -p sile`
3. See an error that sile is broken on the darwin platform

### Expected behavior
I should get a shell with `sile` available

### Notify maintainers
@doronbehar @alerque

**Comment by doronbehar** [comment]
> It would be nice if we could get sile deployable on darwin again using that solution.

cc @teto as the Lua eco system maintainer. Do you think we can make all Lua environment wrappers use `makeBinaryWrapper`?

**Comment by teto** [comment]
is it easy to toggle between the plaintext and binary versions ? 
I think the lua wrapping system is currently broken (at least some stuff is suboptimal) and I rely on the plaintext wrappers a lot to fix the issues.

I am ok with the idea but I need to learn about implications/how it affects the code. A PR would be nice

**Comment by zaphar** [comment]
It would take me a while to put together a PR. I'm not familiar with the lua nixpkg ecosystem that much. I'm experimenting locally to see if I can fix it but it is going to take me a while to figure out how everything wires together and I'm a little short on time right now :-D

**Comment by FRidh** [comment]
> 

override your package or package set and pass in the other `makeWrapper` package. They are compatible, the binary just misses a few hardly used arguments if I am correct.

**Comment by zaphar** [comment]
I have naively tried an override in a nix flake and a local copy of the sile package as an attempt to fix this:

```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = {self, nixpkgs, flake-utils}:
  flake-utils.lib.eachDefaultSystem (system:
  let
    pkgs = import nixpkgs { inherit system; };
    sile = with pkgs; (callPackage ./package.nix { makeWrapper = pkgs.makeBinaryWrapper; });
  in {
      defaultPackage = sile;
  });
}
```

and I still get this kind of error:

```
/nix/store/ysiz8w1ga4mb3psw2hiphyvjswyaa7bm-sile-0.12.5/bin/sile: line 2: SYSTEM_SILE_PATH: command not found
/nix/store/ysiz8w1ga4mb3psw2hiphyvjswyaa7bm-sile-0.12.5/bin/sile: line 3: SHARED_LIB_EXT: command not found
/nix/store/ysiz8w1ga4mb3psw2hiphyvjswyaa7bm-sile-0.12.5/bin/sile: line 5: syntax error near unexpected token `('
/nix/store/ysiz8w1ga4mb3psw2hiphyvjswyaa7bm-sile-0.12.5/bin/sile: line 5: `local executable = debug.getinfo(1, "S").short_src'
```

Which indicates that it isn't using the binary wrapper? I'm not sure if I'm doing something wrong or if it's less simple than just passing in the binary wrapper instead of the regular wrapper.

**Comment by Artturin** [comment]
> is it easy to toggle between the plaintext and binary versions ? I think the lua wrapping system is currently broken (at least some stuff is suboptimal) and I rely on the plaintext wrappers a lot to fix the issues.
> 
> I am ok with the idea but I need to learn about implications/how it affects the code. A PR would be nice

makeBinaryWrapper contains these lines in the binary

```
# ------------------------------------------------------------------------------------
# The C-code for this binary wrapper has been generated using the following command:


makeCWrapper /nix/store/jp1y8aw7i87dxqp34wk9caxav179s8li-any-nix-shell-1.2.1/bin/.any-nix-shell-wrapped \
    --inherit-argv0 \
    --prefix 'PATH' ':' '/nix/store/jp1y8aw7i87dxqp34wk9caxav179s8li-any-nix-shell-1.2.1/bin'


# (Use `nix-shell -p makeBinaryWrapper` to get access to makeCWrapper in your shell)
# ------------------------------------------------------------------------------------
```

**Comment by alerque** [comment]
I don't have access to anything where I could even test on Darwin, so I'm not much use as a reviewer here, sorry.

**Comment by zaphar** [comment]
Did some more digging and it looks like the issue is that we actually need the luaEnv wrapper to be a binary wrapper but I'm out of my depth with that package and it will take me some time to figure it out. If someone wanted to assist I can provide a Darwin M1 platform to test on if they can guide me through where I should be making changes.

**Comment by zaphar** [comment]
I believe now that my fix has landed in master that this can be considered fixed. But I'm not sure what rules govern closing these.
