### ISSUE TITLE
gnome-maps not working

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#17143]
## Issue description
On NixOS 16.03 (3beaca99cbf9f185d72584b81a0733a2e1e0b693):

```
$ gnome-maps 

(org.gnome.Maps:896): GLib-GIO-ERROR **: Settings schema 'org.gnome.Evolution.DefaultSources' is not installed

Trace/breakpoint trap
```

On NixOS 16.09pre/master/unstable (afcf3176ec9dcb3fe6d00c7161d592b52a04203c):

```
$ gnome-maps 

(org.gnome.Maps:20593): Gjs-WARNING **: JS ERROR: Error: Requiring WebKit2, version none: Typelib file for namespace 'WebKit2' (any version) not found
@resource:///org/gnome/Maps/js/application.js:29
@resource:///org/gnome/Maps/js/main.js:43
start@resource:///org/gnome/gjs/modules/package.js:176
@/nix/store/8dl7mkqhaw0zqgymn0i7lwqxlcin84vr-gnome-maps-3.20.1/bin/.gnome-maps-wrapped:5

JS_EvaluateScript() failed
```

## Technical details

* System: NixOS with gnome3 desktop

**Comment by bjornfor** [comment]
Oh, it seems that even if nixpkgs packaging is fixed, there is currently a problem with fetching map tiles, rendering the application useless (I guess):

https://mail.gnome.org/archives/maps-list/2016-July/msg00000.html

**Comment by FRidh** [comment]
That seems to have been fixed 
http://jonasdn.blogspot.se/2016/07/maps-has-tiles-again.html

**Comment by bjornfor** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/19099 (for NixOS 16.09 and master).
