### ISSUE TITLE
`python3Packages.nbclient` does not work: `import nbclient` fails

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#171493]
### Describe the bug
From a nixpkgs checkout at af911e8452bd05d40674bf603332f37480ceb03d,
```
❯ NIX_PATH=.. nix-shell -p python3Packages.nbclient

[nix-shell:~/dev/nixpkgs]$ python -c "import nbclient"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nbclient'
```

Notably the [source](https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/development/python-modules/nbclient/default.nix#L23) does not contain a `pythonImportsCheck`. Oddly however adding such a check doesn't seem to break the build...

How does one go about using/import nbclient?

### Steps To Reproduce
1. Checkout nixpkgs at af911e8452bd05d40674bf603332f37480ceb03d.
2. Enter a nix-shell with nbclient
3. Attempt to `import nbclient` from Python.

### Expected behavior
The `nbclient` module to be available for import.

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers

@erictapen lsix@lancelotsix.com 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-1022-aws, Ubuntu, 20.04.4 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(ubuntu): `"home-manager, nixgl"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by samuela** [comment]
FWIW this is currently blocking upgrading python3Packages.wandb to 0.12.16.

**Comment by samuela** [comment]
Upgrading nbclient to 0.6.2, the current latest at the time of writing, doesn't work either.

**Comment by samuela** [comment]
I'm getting the following directory structure in the build output:
```
❯ tree /nix/store/j5789sc21lcnawwpm91ba2lxbpcwip1m-python3.9-nbclient-0.6.2
/nix/store/j5789sc21lcnawwpm91ba2lxbpcwip1m-python3.9-nbclient-0.6.2
├── lib
│   └── python3.9
│       └── site-packages
└── nix-support
    └── propagated-build-inputs

4 directories, 1 file
```

**Comment by samuela** [comment]
Curiously, the `nbclient` module does seem to be provided by the python3Packages.nbconvert attribute. Why is that?

**Comment by erictapen** [comment]
Regarding nbclient 0.6.2: https://github.com/NixOS/nixpkgs/pull/168473
But that doesn't seem to fix the problem yet.

**Comment by samuela** [comment]
Yeah, I tried something similar in https://github.com/NixOS/nixpkgs/pull/171563. Lots of other things to fix and upgrade, but I didn't manage to find a way to fix this `import nbclient` issue.

**Comment by samuela** [comment]
I've tried other `fetchPypi` and `fetchFromGitHub` but neither seems to work. The pypi tarall does contain the source and everything, it's just not getting copied into the output for some reason.
```
❯ tree ~/Downloads/nbclient-0.6.2
/Users/samuelainsworth/Downloads/nbclient-0.6.2
├── CHANGELOG.md
├── CONTRIBUTING.md
├── LICENSE
├── MANIFEST.in
├── PKG-INFO
├── README.md
├── RELEASING.md
├── docs
│   ├── Makefile
│   ├── UPDATE.md
│   ├── _static
│   │   └── custom.css
│   ├── autogen_config.py
│   ├── client.rst
│   ├── conf.py
│   ├── index.rst
│   ├── installation.rst
│   ├── make.bat
│   ├── reference
│   │   ├── index.rst
│   │   ├── modules.rst
│   │   ├── nbclient.rst
│   │   └── nbclient.tests.rst
│   └── requirements-doc.txt
├── nbclient
│   ├── __init__.py
│   ├── _version.py
│   ├── cli.py
│   ├── client.py
│   ├── exceptions.py
│   ├── jsonutil.py
│   ├── output_widget.py
│   ├── py.typed
│   ├── tests
│   │   ├── __init__.py
│   │   ├── base.py
│   │   ├── conftest.py
│   │   ├── fake_kernelmanager.py
│   │   ├── files
│   │   │   ├── Autokill.ipynb
│   │   │   ├── Check\ History\ in\ Memory.ipynb
│   │   │   ├── Clear\ Output.ipynb
│   │   │   ├── Disable\ Stdin.ipynb
│   │   │   ├── Empty\ Cell.ipynb
│   │   │   ├── Error.ipynb
│   │   │   ├── Factorials.ipynb
│   │   │   ├── HelloWorld.ipynb
│   │   │   ├── Inline\ Image.ipynb
│   │   │   ├── Interrupt.ipynb
│   │   │   ├── JupyterWidgets.ipynb
│   │   │   ├── Other\ Comms.ipynb
│   │   │   ├── Output.ipynb
│   │   │   ├── Parallel\ Execute\ A.ipynb
│   │   │   ├── Parallel\ Execute\ B.ipynb
│   │   │   ├── SVG.ipynb
│   │   │   ├── Skip\ Exceptions\ with\ Cell\ Tags.ipynb
│   │   │   ├── Skip\ Exceptions.ipynb
│   │   │   ├── Skip\ Execution\ with\ Cell\ Tag.ipynb
│   │   │   ├── Sleep1s.ipynb
│   │   │   ├── Unicode.ipynb
│   │   │   ├── UnicodePy3.ipynb
│   │   │   ├── python.png
│   │   │   └── update-display-id.ipynb
│   │   ├── test_client.py
│   │   └── test_util.py
│   └── util.py
├── nbclient.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── requires.txt
│   └── top_level.txt
├── pyproject.toml
├── requirements-dev.txt
├── requirements.txt
├── setup.cfg
└── setup.py

7 directories, 71 files
```

Why would these contents not be copied into the output?

**Comment by FRidh** [comment]
An untested version of the package is already propagated. Old mistake of mine in https://github.com/NixOS/nixpkgs/commit/113083c7ebb7bb1921ea0195f9e0661e657fda7f#diff-c92f7f96550b1858c6f77e04239fada5c9dc1bfecf7ba9f598a0a6b0017ad2efR39.

**Comment by FRidh** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/171572

**Comment by FRidh** [comment]
We check whether a version already exists when both are installed, not when installing the second. I consider this a bug in pip, but since the use case (installing in different prefixes) is so rare, we should maybe not bother them with it.

**Comment by samuela** [comment]
Shout out to @SuperSandro2000 for cracking the nut on this on matrix, and @FRidh for being so quick with a fix!

**Comment by SuperSandro2000** [comment]
I had the same problem already multiple times myself. 🙃
