### ISSUE TITLE
Hatchling backport

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#171447]
I cannot use hatchling as part of `poetry2nix` from nixos-21.11, because it's only in nixpkgs-unstable.
Is there any chance it could be backported?

The question came from here: https://github.com/nix-community/poetry2nix/issues/605

**Comment by NorfairKing** [comment]
cc @[r-ryantm](https://github.com/r-ryantm) and [mweinelt](https://github.com/NixOS/nixpkgs/commits?author=mweinelt)

**Comment by SuperSandro2000** [comment]
If it just works with python packages on 21.11 maybe, if it requires more changes definitely no.

**Comment by NorfairKing** [comment]
@SuperSandro2000 sounds good to me. How do we check?

**Comment by SuperSandro2000** [comment]
Clone the repo, checkout nixos-21.11, cherry-pick the commit and see hot that works.

**Comment by NorfairKing** [comment]
@SuperSandro2000 Trying that here: https://github.com/NixOS/nixpkgs/pull/171541
Looks like it's not that simple.

**Comment by dotlambda** [comment]
fixed in https://github.com/NixOS/nixpkgs/pull/171576
