### ISSUE TITLE
Cross compiling gobject-introspection fails

### ISSUE THREAD

**Issue by cyber-murmel** [NixOS/nixpkgs#171415]
### Describe the bug
Cross compiling gobject-introspection fails with
```
ERROR: An exe_wrapper is needed but was not found. Please define one in cross file and check the command and/or add it to PATH.
```
This package is needed for the `tracker` library which in turn is needed for GNURadio.

### Steps To Reproduce
1. `nix-build '<nixpkgs>' -A pkgsCross.aarch64-multiplatform.gobject-introspection`

### Expected behavior
I expected it to cross compile

### Additional context
Building from nixos-21.11 nixpkgs.

### Notify maintainers
@lovek323

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.109, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(marble): `""`
 - channels(root): `"nixos-21.11.337311.fd3e33d696b"`
 - channels(work): `"nixos-unstable-21.11pre328987.c935f5e0add"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cdepillabout** [comment]
Looks like this has come up before: https://github.com/NixOS/nixpkgs/issues/72868

**Comment by cyber-murmel** [comment]
Ah, you're right. Sorry.
https://github.com/NixOS/nixpkgs/issues/72868
