### ISSUE TITLE
Kalendar

### ISSUE THREAD

**Issue by jmercouris** [NixOS/nixpkgs#171596]
**Project description**
Kalendar is a KDE calendar.

**Metadata**

* homepage URL: https://apps.kde.org/kalendar/
* source URL: https://github.com/KDE/kalendar
* license: gpl3+
* platforms: linux

**Comment by anthr76** [comment]
@jmercouris Kalandar is packaged.

**Comment by jmercouris** [comment]
@anthr76 how come: https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=Kalendar returns "No Packages found!"?

**Comment by zendo** [comment]
It's in the unstable channel.

**Comment by anthr76** [comment]
+1 on what @zendo I would suggest closing this issue or requesting it to be back-ported. Though there are some issues that need to be taken care of first. 

https://github.com/NixOS/nixpkgs/issues?q=Kalendar+is%3Aopen
