### ISSUE TITLE
Tor Browser currently broken

### ISSUE THREAD

**Issue by wyndon** [NixOS/nixpkgs#171559]
### Describe the bug
On startup, Tor Browser doesn't start if some variables about Wayland aren't set. 

### Steps To Reproduce
1. Unset `MOZ_ENABLE_WAYLAND` and `WAYLAND_DISPLAY` (if set)
2. Launch Tor Browser in a terminal and see the error message.

### Expected behavior
Tor Browser should start.

### Additional context
This issue was caused by #168497. #171167 currently does not fix the problem.
```console
[user@system:~]$ tor-browser
/etc/profiles/per-user/wyndon/bin/tor-browser: line 81: MOZ_ENABLE_WAYLAND: unbound variable
```

In the meantime, an easy fix would be :
```console
[user@system:~]$ MOZ_ENABLE_WAYLAND= WAYLAND_DISPLAY= tor-browser
```

### Notify maintainers

Notifying peoples from the aforementioned PRs instead.
@Artturin @LutzCle 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34-xanmod1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos-22.05pre347261.6d8215281b2"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by xaverdh** [comment]
I can confirm this issue

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/171820

**Comment by xaverdh** [comment]
thanks @Artturin !
