### ISSUE TITLE
GDM missing icons

### ISSUE THREAD

**Issue by max-privatevoid** [NixOS/nixpkgs#171692]
### Describe the bug
GDM is missing all its icons (network, battery, user profile, back button, ...). See screenshot.
git bisect says it's https://github.com/NixOS/nixpkgs/commit/b1e73fa2e086f1033a33d93524ae2a1781d12b95
See also related PR https://github.com/NixOS/nixpkgs/pull/163623

### Steps To Reproduce
Used this config (based on the GNOME ISO) for bisecting with VMs. The mkOverrides are there to reduce the build time a little bit.
```
{ lib, modulesPath, ... }:

with lib;

{
  imports = [ "${modulesPath}/installer/cd-dvd/installation-cd-graphical-base.nix" ];

  isoImage.edition = "gnome";

  services.xserver.desktopManager.gnome = {
    # Add Firefox and other tools useful for installation to the launcher
    favoriteAppsOverride = ''
      [org.gnome.shell]
      favorite-apps=[ 'firefox.desktop', 'nixos-manual.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'gparted.desktop' ]
    '';
    enable = true;
  };

  documentation.enable = lib.mkOverride 9 false;
  documentation.man.enable = lib.mkOverride 9 false;
  documentation.doc.enable = lib.mkOverride 9 false;
  documentation.info.enable = lib.mkOverride 9 false;
  documentation.nixos.enable = lib.mkOverride 9 false;
  services.gnome.core-utilities.enable = lib.mkOverride 9 false;
  services.xserver.displayManager = {
    gdm = {
      enable = true;
      # autoSuspend makes the machine automatically suspend after inactivity.
      # It's possible someone could/try to ssh'd into the machine and obviously
      # have issues because it's inactive.
      # See:
      # * https://github.com/NixOS/nixpkgs/pull/63790
      # * https://gitlab.gnome.org/GNOME/gnome-control-center/issues/22
      autoSuspend = false;
    };
  };

}
```

### Screenshots
![Screenshot from 2022-05-05 17-47-34](https://user-images.githubusercontent.com/55053574/166979699-f4cd7258-3b93-42ac-b8a5-e657374dc1e8.png)

### Notify maintainers
```console
$ nix eval gnome.gdm.meta.maintainers --apply "map (x: x.github)"
[ "bobby285271" "hedning" "jtojnar" "dasj19" "maxeaubrey" ]
```
@bobby285271 
@hedning 
@jtojnar 
@dasj19 
@maxeaubrey 

PR author: @ilya-fedin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.20, NixOS, 22.05 (Quokka), 22.05.20220426.e10da1c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix Super) 2.8.0pre20220415_0883a09`
 - channels(root): `""`
 - channels(max): `""`
 - nixpkgs: `/etc/nix/flake-channels/nixpkgs`
```

**Comment by zendo** [comment]
I also have the same problem.

**Comment by jtojnar** [comment]
We should probably add adwaita-icon-theme to gdm. Probably in the module like we did for the a11y icon https://github.com/NixOS/nixpkgs/commit/87d18174d317e78fdfd9ab1fd35b685deb812aa8. Maybe a wrapper in gnome-shell or gdm would be a better place but I am currently not sure which is more appropriate.
