### ISSUE TITLE
Add dump1090 webinterface support

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#171675]
### Describe the bug
Dump1090 supports a web interface with Lighttpd, but this package doesn't include it. It would be very nice to have.

### Notify maintainers
 @earldouglas 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2-xanmod1, NixOS, 22.05 (Quokka), 22.05pre374583.cbe587c735b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
@QuantMint : do you have a link to where it was fixed?

**Comment by QuantMint** [comment]
> @QuantMint : do you have a link to where it was fixed?

It wasn't fixed, I just no longer need it.

**Comment by aciceri** [comment]
Still relevant, see #288695
