### ISSUE TITLE
spyder broken on 21.11

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#171613]
### Describe the bug
Spyder cannot be installed on NixOS 21.11 and master. The message is "error: python-language-server-0.36.2 not supported for interpreter python3.9", but even after working around this by using ``python38Packages`` there are many other issues.

The attached patch for 21.11 makes it work for at least Python 3.8 and 3.9. Unfortunately I do not have time to clean it up and submit the many different PRs that would be required.

[spyder_ok.zip](https://github.com/NixOS/nixpkgs/files/8628732/spyder_ok.zip)

### Steps To Reproduce
nix-shell -p spyder

**Comment by sbourdeauducq** [comment]
@drewrisinger

**Comment by drewrisinger** [comment]
Replicated: 
```bash
$ nix-shell -p spyder -I nixpkgs=channel:nixos-21.11
unpacking 'https://nixos.org/channels/nixos-21.11/nixexprs.tar.xz'...
error: python-language-server-0.36.2 not supported for interpreter python3.9
(use '--show-trace' to show detailed location information)
```

Will try to look into when I get a chance.

**Comment by drewrisinger** [comment]
pinging maintainer @gebner

**Comment by drewrisinger** [comment]
Addressed on ``nixpkgs-unstable`` in #171704. Needs backported to stable ``release-21.11``, will try to get that done at some point. Or someone else could if they want to cherry-pick the commits from #171704.

**Comment by sbourdeauducq** [comment]
stable would need more updates, just applying your changes results in:
```
       > ERROR: Could not find a version that satisfies the requirement ipykernel>=6.9.2; python_version >= "3" (from spyder-kernels) (from versions: none)
       > ERROR: No matching distribution found for ipykernel>=6.9.2; python_version >= "3"
```
Unless it is happy with version 6.4.1 currently in stable? It seems many version constraints are too tight, but I am not familiar enough with ipython/spyder to know this one is justified.

**Comment by sbourdeauducq** [comment]
Now that 22.05 is almost released, perhaps we can just close this?
