### ISSUE TITLE
Building gnome failed

### ISSUE THREAD

**Issue by wiredhikari** [NixOS/nixpkgs#171760]
### Steps To Reproduce
1. nix-env -iA nixos.gnome
2. ...
3. ...

### Expected behavior
On trying to install gnome, it gets an error while installing gnome-documents

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/b6lg7x9x7ya3g3vfsnpw5wypw0sh7gin-gnome-documents-3.34.0.tar.xz
source root is gnome-documents-3.34.0
setting SOURCE_DATE_EPOCH to timestamp 1571902526 of file gnome-documents-3.34.0/subprojects/libgd/test-tagged-entry.c
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/jszq563rv6p07ajq5qgsdrq4jlw60x5r-0f55a18c40a61e6ae4ec4652604775f139892350.diff
patching file getting-started/meson.build
patching script interpreter paths in meson_post_install.py
meson_post_install.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/wq6s8i407ic4qp1dvd5yhrnd0kflzh6x-python3-3.9.12/bin/python3"
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/lib --libexecdir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/libexec         --bindir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/bin --sbindir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/sbin         --includedir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/include         --mandir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/share/man --infodir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/share/info         --localedir=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/f13p6fd267f0qwpq65xajywbl3mnw0d4-gnome-documents-3.34.0 -Dgetting_started=true 
[1mThe Meson build system[0m
Version: 0.57.1
Source dir: [1m/build/gnome-documents-3.34.0[0m
Build dir: [1m/build/gnome-documents-3.34.0/build[0m
Build type: [1mnative build[0m
Project name: [1mgnome-documents[0m
Project version: [1m3.34.0[0m
C compiler for the host machine: [1mgcc[0m (gcc 10.3.0 "gcc (GCC) 10.3.0")
C linker for the host machine: [1mgcc[0m ld.bfd 2.35.2
Host machine cpu family: [1mx86_64[0m
Host machine cpu: [1mx86_64[0m
Found pkg-config: [1m/nix/store/561d5sd2r3ih63v7n38k2pgx4bhibl0m-pkg-config-wrapper-0.29.2/bin/pkg-config[0m (0.29.2)
Run-time dependency [1mgjs-1.0[0m found: [1;32mYES[0m [36m1.70.0[0m
Run-time dependency [1mevince-document-3.0[0m found: [1;32mYES[0m [36m41.3[0m
Run-time dependency [1mevince-view-3.0[0m found: [1;32mYES[0m [36m41.3[0m
Run-time dependency [1mglib-2.0[0m found: [1;32mYES[0m [36m2.70.1[0m
Run-time dependency [1mgnome-desktop-3.0[0m found: [1;32mYES[0m [36m41.1[0m
Run-time dependency [1mgobject-introspection-1.0[0m found: [1;32mYES[0m [36m1.70.0[0m
Run-time dependency [1mgtk+-3.0[0m found: [1;32mYES[0m [36m3.24.30[0m
Run-time dependency [1mlibsoup-2.4[0m found: [1;32mYES[0m [36m2.74.1[0m
Did not find CMake 'cmake'
Found CMake: [1;31mNO[0m
Run-time dependency [1mtracker-control-2.0[0m found: [1;31mNO[0m (tried pkgconfig)

meson.build:62:0: [1;31mERROR:[0m Dependency "tracker-control-2.0" not found, tried pkgconfig

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/pbh7amf03i8fj84x5gh5dw2ir6g20w04-bash-interactive-5.1-p8-dev
copying path '/nix/store/pbh7amf03i8fj84x5gh5dw2ir6g20w04-bash-interactive-5.1-p8-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.337241.a3917caedfe"`
 - channels(hikari): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Installing GNOME using `nix-env` is not supported, it requires various global changes that only NixOS module can do. If you want to install specific apps, you will need to list them individually.

**Comment by bobby285271** [comment]
> meson.build:62:0: �[1;31mERROR:�[0m Dependency "tracker-control-2.0" not found, tried pkgconfig

For the build log you posted, gnome-documents has been [archived](https://gitlab.gnome.org/Archive/gnome-documents) on upstream and marked as broken in Nixpkgs because it does not support Tracker 3 so the build failure is expected.

https://github.com/NixOS/nixpkgs/blob/72cce37c479161163a436a9a2ee642532856790d/pkgs/desktops/gnome/apps/gnome-documents/default.nix#L120

**Comment by jtojnar** [comment]
The broken packages were removed in https://github.com/NixOS/nixpkgs/pull/197884
