### ISSUE TITLE
Merge aarch64-darwin into nixpkgs channels

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#171799]
Looking at https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-unstable-aarch64-darwin, it seems to have similar ratio of failure compared to https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-21.11-darwin

I'd suggest we merge it into https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-22.XX-darwin and https://hydra.nixos.org/jobset/nixpkgs/trunk

I'm not sure what's the criteria and we can make a transition period to see if the resources on hydra is sufficient to preform the evaluation.

The benefit is that the users have to worry only about 2 instead of 4 channels to track successfully built binaries.

**Comment by FliegendeWurst** [comment]
I don't see a specific aarch64-darwin jobset in https://hydra.nixos.org/project/nixpkgs, so this must have been done at some point. Right?
