### ISSUE TITLE
Can't reach graphical user interface on nix unstable

### ISSUE THREAD

**Issue by BloomnDoom** [NixOS/nixpkgs#171770]
I'm on KDE with NetworkManager and GRUB, trying to get nixos-unstable drops me into a tty instead of the GUI

1. Upgrade to unstable channel by running `nix-channel --add https://nixos.org/channels/nixos-unstable nixos` and then `nixos-rebuild switch --upgrade` 
2. After the update is over, the restart button on KDE does not work.
3. Manually rebooting drops me into a tty
4. Trying to start sddm by `systemctl enable sddm.service` gives the error that `Unit sddm.service not found`

Nix env version : 2.8.0

Letting the system go to sleep after the update but before rebooting shows this instead of the login screen when woken up

![image](https://user-images.githubusercontent.com/104047347/166859177-adb8b1c1-0940-4a0b-b44e-a0d6bcecd87b.png)

Meta data:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.36, NixOS, 22.05 (Quokka), 22.05pre374583.cbe587c735b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(ash): `"nixos-22.05pre374583.cbe587c735b"`
 - channels(root): `"nixos-22.05pre374583.cbe587c735b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by FRidh** [comment]
I think this issue has always existed on NixOS.

**Comment by SuperSandro2000** [comment]
Yeah, certain updates cause this. There is not much we can do other than rebooting. You can prevent this by doing nixos-rebuild boot and then reboot.
