### ISSUE TITLE
Hyperlink sources on GHC distribution packages

### ISSUE THREAD

**Issue by lf-** [NixOS/nixpkgs#171841]
### Describe the bug

Currently the sources of packages such as `text`, etc, that come in the GHC distribution are not hyperlinked. This is unfortunate as it interacts with the source hyperlinker of hackage packages poorly by having a different URL format (hyphens instead of dots in the names of module source files). I am currently fixing some bugs in the hyperlinker and noticed that this URL format thing was happening.

### Steps To Reproduce

Look at `/nix/store/3bwbsy0llxxn1pixx3ll02alln56ivxy-ghc-9.0.2-doc/share/doc/ghc/html/libraries/text-1.2.5.0/src/Data-Text-Array.html` or similar paths in your ghc doc package, which don't have hyperlinks to items in them.

Do `nix-build '<nixpkgs>' -A haskell.compiler.ghc902.doc` and replace the first part of that path as appropriate.

### Expected behavior

I would like these packages to have hyperlinked sources.

### Screenshots

Not-hyperlinked source from Data.Text.Array:
![image](https://user-images.githubusercontent.com/6652840/167183678-5dda4a77-3035-4622-9d15-f51614de9020.png)

### Additional context

I am guessing this is something that needs to be set in the GHC build system custom to pass `--hyperlinked-source` to haddock.

### Notify maintainers

@guibou 
@cdepillabout 
@expipiplus1 
@maralorn 
@sternenseemann 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixpkgs"`
 - channels(jade): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by lf-** [comment]
Related upstream filing: https://gitlab.haskell.org/ghc/ghc/-/issues/19455, which we can probably follow to figure out what we'd need to do.

**Comment by cdepillabout** [comment]
@lf- This definitely sounds like something we should enable if you want to figure it out and send a PR!  It is hard to imagine anyone being against it, since the hyperlinked docs are so helpful.
