### ISSUE TITLE
`path:` or `file:` flake URLs containing whitespace do not work

### ISSUE THREAD

**Issue by kenranunderscore** [NixOS/nixpkgs#171821]
### Describe the bug
Local flake paths containing whitespace lead to `file:` and `path:` flake URLs not working. That is, I cannot reference such flakes when using `nix flake new --template "path:/home/me/foo bar/my-flake"`, or even enter a `nix develop` environment in this directory.

### Steps To Reproduce
1. Create a directory containing whitespace, `~/tmpdev/foo bar` in my case and `cd` there.
2. Add the following `flake.nix` (with fitting `system` of course):

```nix
{
  description = "test";
  outputs = { self, nixpkgs }: {
    devShells.x86_64-linux.default =
      nixpkgs.legacyPackages.x86_64-linux.mkShell {
        buildInputs = [ nixpkgs.legacyPackages.x86_64-linux.cowsay ];
      };
  };
}
```

3. Execute `nix develop`. Then the following error message appears:

```console
error: 'file:///home/johannes/tmpdev/foo bar' is not a valid URL
```

### Expected behavior

I should enter the development environment.

### Additional context
In the template case as described at the top (that is, just using `path:` instead of `file:`), I get the following similar message instead:

```console
error: 'path:/home/johannes/tmpdev/foo bar' is not a valid URL
```

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 22.05 (Quokka), 22.05.20220417.1ffba9f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220411_f7276bc`
 - channels(root): `"nixos"`
 - channels(johannes): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by liketechnik** [comment]
Relevant nix issue and pr:
- NixOS/nix#6394
- NixOS/nix#6614

**Comment by LEv145** [comment]
It also doesn't work with Cyrillic
```sh
error: 'file:///home/lev145/Проекты/Lunohod-joystick' is not a valid URL
```

**Comment by kenranunderscore** [comment]
Closing this as it basically duplicates the linked issue.
