### ISSUE TITLE
espanso missing setxkbmap as a runtime depdency

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nixpkgs#171848]
### Describe the bug
The `espanso` package/NixOS service module is missing `setxkbmap` as a runtime depdency which is causing a lot of log spam

### Steps To Reproduce
1. Set `services.espanso.enable = true;`
2. Observe journal logs:
```
unable to retrieve current keyboard layout with 'setxkbmap': No such file or directory (os error 2)
```

### Expected behavior
`setxkbmap` should be provided as a runtime dependency to espanso

### Notify maintainers
@kimat

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.1, NixOS, 22.05 (Quokka), 22.05.20220505.c777cdf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220505_f4102de`
```

**Comment by bobvanderlinden** [comment]
https://github.com/NixOS/nixpkgs/pull/231062 has been merged :partying_face: @PAI5REECHO could you give it a try?

**Comment by n8henrie** [comment]
I do not see this error in my espanso logs, I presume the above noted PR resolved it. Please let me know if this should be re-opened.
