### ISSUE TITLE
bashInteractive evaluates to multiple store paths

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nixpkgs#171840]
### Describe the bug
In trying to `nix develop` a flake I am seeing the following:

```console
error (ignored): error: argument 'github:NixOS/nixpkgs/c464dc811babfe316ed4ab7bbc12351122e69dd7#bashInteractive' should evaluate to one store path
```

This flake uses the above nixpkgs however I can reproduce this on the nixpkgs from my system too:

```console
[jkolb@nixos:~/nixpkgs]$ nix why-depends nixpkgs#bashInteractive nixpkgs#bashInteractive
error: argument 'flake:nixpkgs#bashInteractive' should evaluate to one store path
```

### Steps To Reproduce
1. `nix why-depends nixpkgs#bashInteractive nixpkgs#bashInteractive`

### Expected behavior
nixpkgs#bashInteractive should evaluate to one store path.

### Notify maintainers

@dtzWill 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.36, NixOS, 22.05 (Quokka), 22.05.20220505.c777cdf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220503_9489b4b`
 - channels(root): `"nixos"`
 - channels(jkolb): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Artturin** [comment]
opened https://github.com/NixOS/nix/issues/6500
