### ISSUE TITLE
mysql and mariadb are bloated, probably due to static linking

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#172]
Our MySQL 5.1 build is 50 MiB, while 5.5 is 152 MiB. It's mostly in the bin directory, which is 110 MiB.  Apparently MySQL does some very bad static linking (for instance, the trivial MySQL utilities "replace" and "resolveip" are both almost 3 MiB).

**Comment by domenkozar** [comment]
Is this still relevant?

**Comment by vcunat** [comment]
Now we have a bloated mariadb instead (by default) :-) but it's not too bad anymore:
```
36M     /nix/store/07f80n3kjncdnxvmfdysby824519vzgg-mariadb-10.0.21-lib
173M    /nix/store/gs3brddzpcxlsi0fh267rdn5bm9kpbrw-mariadb-10.0.21
```

**Comment by vcunat** [comment]
To the actual issue:
```
143M    /nix/store/q9x4gy1k1xwyr5w3xm8cwy0vi9pkgsrh-mysql-5.5.45
```
After deleting `lib/*.a` in f7d52106:
```
120M    /nix/store/yky32ik5y42k5ra991wgkiymdvl9hgrc-mysql-5.5.45
```
That doesn't look too bloated to me in comparison, and `mysql55` isn't in default closures anyway (anymore).

**Comment by lethalman** [comment]
It is bloated, because all the binaries are kind of statically linked. They are dynamic, but the build process include something static into them. The binaries are huge, while they could be much smaller.

**Comment by vcunat** [comment]
Hmm, it seems Debian has much smaller sizes.

**Comment by vcunat** [comment]
At least, what is in most closures, `libmysqld`, is about similar size. Maybe some plugins or other stuff could be removed from the default closure, I don't know.

**Comment by jagajaga** [comment]
Is it relevant nowadays?

**Comment by vcunat** [comment]
It's still bloated but excluded from most closures.

**Comment by ocharles** [comment]
While it might still be a problem, do we actually care about this? It's been an open issue for close to 5 years, yet the world hasn't exploded. @edolstra reported this, but do you still actually care about this?

**Comment by globin** [comment]
With the mariadb-connector-c change coming up with the next mariadb bump, libmysqlclient is completely seperate at least (WIP on the openssl-1.1 branch).

The binaries sadly still are the same size, but should only be in a closure that actually needs the mariadb server..

**Comment by edolstra** [comment]
I personally don't care about mysql/mariadb themselves, but only about the fact that they're part of many closures (e.g. of Qt). But if the client libraries are going to be completely separate, then the size of mysql/mariadb is not a problem anymore.

**Comment by vcunat** [comment]
For over a year, most closures only have `mariadb-client`, currently sized ~7 MB.
