### ISSUE TITLE
epiphany: TLS/SSL support

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#17221]
## Issue description

I installed Epiphany on NixOS with XFCE but can't load pages with TLS encryption.
### Steps to reproduce
1. install epiphany on [this configuration](https://github.com/davidak/nixos-config/blob/29dbbb8f9e48f8351160956ef63469c7f8cfdbd6/default-desktop/configuration.nix)
2. open a random website with TLS, for example https://nixos.org/
3. get `TLS/SSL support not available; install glib-networking.`
4. just installing `gnome3.glib_networking` doesn't help, it schould be a dependencie of epiphany
## Technical details
- System: NixOS 16.09pre87354.d217279 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre87354.d217279" (nixos-unstable)

**Comment by cleverca22** [comment]
xfce4-screenshooter has the same problem when uploading images, but only shows the error if built with debug enabled

**Comment by Mic92** [comment]
is glib_networking a dependencies of both? Usually GIO_EXTRA_MODULES are picked up by wrapGAppsHook

**Comment by jtojnar** [comment]
Fixed in #19433.
