### ISSUE TITLE
ecos-python: license does not appear to be Apache 2.0?

### ISSUE THREAD

**Issue by mstone** [NixOS/nixpkgs#172235]
https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/pkgs/development/python-modules/ecos/default.nix#L47 suggests that the ecos-python license as Apache 2.0 but https://github.com/embotech/ecos-python/blob/master/LICENSE looks like a copy of the GPLv3, not the ASLv2.

cc: @drewrisinger, @fabaff.

**Comment by fabaff** [comment]
Thanks for the hint. The license is GPLv3.

**Comment by drewrisinger** [comment]
Thanks. Probably a copy-pasta issue.
