### ISSUE TITLE
Syncthing systemd service wrongly generated

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nixpkgs#17229]
## Issue description

Syncthing systemd system service as currently generated misses `ExecStart` and `ExecStop` lines.

From what I can tell, given it contains only After=/Description=/Environment= lines, it looks like only `header` (as defined in the nix expression) is used to build the service, instead of the complete set union.

### Steps to reproduce

Add the following lines to `configuration.nix`:
```
  services.syncthing.enable = true;
  services.syncthing.user = "ekleog";
```

Run `nixos-rebuild switch`.

Open `/etc/systemd/system/syncthing.service`. Notice the lines `ExecStart` and `ExecStop` are missing, thus making the service impossible to launch.

## Technical details

* System: NixOS: 16.09pre87355.a18abd2 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre87355.a18abd2

The systemd service, as defined in `/root/.nix-defexpr/channels/nixos/nixos/modules/services/networking/syncthing.nix` (hopefully this is actually the installed nix expression ; I installed earlier today and am not yet used to nix) contains the following statement:
```
    systemd.services.syncthing = mkIf cfg.systemService
      header // {
        wantedBy = [ "multi-user.target" ];
        serviceConfig = service // {
          User = cfg.user;
          Group = cfg.group;
          PermissionsStartOnly = true;
          ExecStart = "${cfg.package}/bin/syncthing -no-browser -home=${cfg.dataDir}";
        };
      };
```

I guess the issue may come from https://github.com/NixOS/nixpkgs/commit/267e362fbc41dffd0d978ab5c8d91668b5d7d8fc ; as it is most likely a recent bug as no one seems to have reported it yet. Moreover, the generated service contains what looks to me like what the output would be if only `mkIf cfg.systemService header` was present.

I would guess it is just lacking parenthesis around the set union ; but don't know how to test it without starting a complete development environment for NixOS -- thing I am not yet ready to do, given I don't know if I'll stay on NixOS more than a few days (even though the first day is really promising!).

Thanks for your work!

**Comment by pshendry** [comment]
I'm seeing this too (see #17244). FYI, from one relative NixOS newbie to another, tinkering with a local nixpkgs clone is quite easy! [Here's a guide](http://anderspapitto.com/posts/2015-11-01-nixos-with-local-nixpkgs-checkout.html) (it's a one-liner in your configuration).

**Comment by Mayeu** [comment]
While I am also experiencing this, syncthing does start when I boot my computer. But then I can not control it via ```systemctl```.

Some info:
- NixOS 16.09pre87431.3badad8 (Flounder)
- nix-env (Nix) 1.11.2
- Nixpkgs 16.09pre87431.3badad8

The generated ```syncthing.service``` files looks like that (I am using syncthing013 for android compatibily, but the error was the same with the last version), and indeed lack a ```ExecStop```, but the ```ExecStart``` is actually present:
```
[Unit]
After=network.target
Description=Syncthing service

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/m7iw35lmsbfi033jjrs2cfdrwfnpk7x7-glibc-locales-2.23/lib/locale/locale-archive"
Environment="PATH=/nix/store/038z6c3idjsy5a4gkqb70s1vml7ydylw-coreutils-8.25/bin:/nix/store/izh9gsfvi765hi89b0mwnfd58l4xgxd7-findutils-4.6.0/bin:/nix/store/8nm7vp5zw2lq3y2bvmq4yjnn2qgcm9rq-gnugrep-2.25/bin:/nix/store/r3m6xxf11rr65pyvfjslvj8lawpxjwi0-gnused-4.2.2/bin:/nix/store/qh030qmi0bqazrfjzgszagnpj45cwaaz-systemd-230/bin:/nix/store/038z6c3idjsy5a4gkqb70s1vml7ydylw-coreutils-8.25/sbin:/nix/store/izh9gsfvi765hi89b0mwnfd58l4xgxd7-findutils-4.6.0/sbin:/nix/store/8nm7vp5zw2lq3y2bvmq4yjnn2qgcm9rq-gnugrep-2.25/sbin:/nix/store/r3m6xxf11rr65pyvfjslvj8lawpxjwi0-gnused-4.2.2/sbin:/nix/store/qh030qmi0bqazrfjzgszagnpj45cwaaz-systemd-230/sbin"
Environment="STNORESTART=yes"
Environment="STNOUPGRADE=yes"
Environment="TZDIR=/nix/store/qykbpgnvs4vfl59663msq92rsbmgzwwa-tzdata-2016e/share/zoneinfo"

ExecStart=/nix/store/50qy104rdgg3s59m26h6y8dncps16zs4-syncthing-0.13.10/bin/syncthing -no-browser
Restart=on-failure
RestartForceExitStatus=3 4
SuccessExitStatus=2 3 4
```

```systemctl status syncthing```:
```
sudo systemctl status syncthing                                                                                                         ~
Failed to dump process list, ignoring: Unit syncthing.service is not loaded properly: Invalid argument.
● syncthing.service - Syncthing service
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Jul 26 09:47:50 azathoth systemd[1]: syncthing.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```
And has I was saying, it is actually running:
```
$ pgrep syncthing
3313
```
Hope that help.
