### ISSUE TITLE
No way to have Haskell executable (or test) depend on binary at runtime

### ISSUE THREAD

**Issue by jml** [NixOS/nixpkgs#17226]
## Issue description

I want to have a Haskell binary (and also some Haskell tests) execute standard, non-Haskell binaries at runtime (e.g. `tree`, `git`, `ssh`). 

However, there seems to be no way to write a `mkDerivation` expression that expresses this dependency.

### Steps to reproduce

https://github.com/jml/nix-haskell-example has a minimal example of what I want to do that demonstrates the problem.

Simply:

* write some Haskell code that uses `callCommand` or similar to execute a binary assuming it is on the PATH
* try to package that in Nix
* observe that on running, the binary is not available

## Technical details

* System: this occurs on NixOS 16.03 and on Darwin
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre83147.df89584

**Comment by LnL7** [comment]
```
{ pkgs ? import <nixpkgs> {} }:

let
  inherit (pkgs) haskell pstree;
  example = import ./nix-haskell-example {};

in haskell.lib.overrideCabal example (drv: {
  propagatedBuildInputs = [ pstree ];
})
```

**Comment by jml** [comment]
Saving that example as `extended.nix` and modifying it to the following:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  inherit (pkgs) haskell pstree;
  example = pkgs.haskellPackages.callPackage ./. {};

in haskell.lib.overrideCabal example (drv: {
  propagatedBuildInputs = [ pstree ];
})
```


And then running with:

```command
$ nix-build -E 'with (import <nixpkgs> {}).pkgs; haskellPackages.callPackage ./extended.nix {}'
error: anonymous function at /nix/store/phqb57liyaqm9jxlawk47y3d97whq2bv-nixpkgs-16.09pre83147.df89584/nixpkgs/pkgs/development/haskell-modules/generic-builder.nix:5:1 called with unexpected argument ‘propagatedBuildInputs’, at /nix/store/phqb57liyaqm9jxlawk47y3d97whq2bv-nixpkgs-16.09pre83147.df89584/nixpkgs/pkgs/development/haskell-modules/lib.nix:6:25
```

**Comment by jml** [comment]
Adding an `extended.nix` file with the following contents:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  inherit (pkgs) haskell pstree;
  example = pkgs.haskellPackages.callPackage ./. {};

in haskell.lib.overrideCabal example (drv: {
  buildDepends = [ pkgs.makeWrapper ];
  postInstall = ''
    wrapProgram "$out/bin/nix-haskell-example" \
      --prefix PATH ":" "${pstree}/bin"
  '';
})
```

And building like this:

```command
$ nix-build -E 'with (import <nixpkgs> {}).pkgs; haskellPackages.callPackage ./extended.nix {}'
```

Appears to work.

**Comment by jml** [comment]
Updated to have a [generic wrapper for doing this for Haskell packages](https://github.com/jml/nix-haskell-example/blob/master/extended.nix). Repasting here.

```nix
  addRuntimeDependency = drv: x: addRuntimeDependencies drv [x];
  addRuntimeDependencies = drv: xs: haskell.lib.overrideCabal drv (drv: {
    buildDepends = (drv.buildDepends or []) ++ [ pkgs.makeWrapper ];
    postInstall = ''
      ${drv.postInstall or ""}
      for exe in "$out/bin/"* ; do
        wrapProgram "$exe" --prefix PATH ":" \
          ${pkgs.lib.makeBinPath xs}
      done
    '';
  });
```

I don't have bandwidth to handle the PR for this, but others are welcome.

**Comment by jml** [comment]
In a similar spirit:

```nix
{
  addTestDependency = drv: x: addTestDependencies drv [x];
  addTestDependencies = drv: xs: haskell.lib.overrideCabal drv (drv: {
    preCheck = ''
      export PATH=${lib.makeBinPath xs}:$PATH

      ${drv.preCheck or ""}
    '';
  });
}
```

**Comment by jml** [comment]
Note: this approach would not work if you have a library that works by executing a command that it assumes is on the `PATH`. I do not currently know a way around that.

**Comment by peti** [comment]
I'm closing this issue because it's not actionable. If someone feels like suggestion a concrete PR, that would be great but as-is this issue doesn't seem to add value at the moment.

**Comment by deepfire** [comment]
@peti, do we want to standartize, cross-language-infra-wise, on this kind of PATH-extension?

**Comment by deepfire** [comment]
..and now I see your suggestion to go the generic route at https://github.com/NixOS/nixpkgs/pull/18520.
