### ISSUE TITLE
mkForce on environment.etc.*.source is broken

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#17237]
## Issue description

I'm unable to override a file in /etc by using mkForce. In particular, I want to override /etc/pulse/client.conf, which the pulseaudio module intentionally generates even when disabled. The error looks like this

```
$ nixos-rebuild switch
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/19rmp978pxk5v12p4g5dpaymxw47zkhx-etc.drv
  /nix/store/rsjhxx88ag67c5djni3zdyknwqljc31k-nixos-system-gurney-16.09.git.e12b425.drv
building path(s) ‘/nix/store/h1vamvsg8857m8lzqcgi1hbih2maji20-etc’
duplicate entry pulse/client.conf -> /nix/store/18ndhf1s92yz3f6fky348whkzna07kj5-client.conf
mismatched duplicate entry /nix/store/wg7g3wc9d2abz2dyh1i8z0m3937ynln4-client.conf <-> /nix/store/18ndhf1s92yz3f6fky348whkzna07kj5-client.conf
builder for ‘/nix/store/19rmp978pxk5v12p4g5dpaymxw47zkhx-etc.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/rsjhxx88ag67c5djni3zdyknwqljc31k-nixos-system-gurney-16.09.git.e12b425.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/rsjhxx88ag67c5djni3zdyknwqljc31k-nixos-system-gurney-16.09.git.e12b425.drv’ failed
```

This was previously reported as https://github.com/NixOS/nixpkgs/issues/6161.
### Steps to reproduce

I have this in my configuration.nix

```
  environment.etc = [
    { target = "pulse/client.conf";
      source = pkgs.lib.mkForce clientConf;
    }
  ];
```

where `clientConf` is the result of some call to `pkgs.writeText` - contents shouldn't matter.
## Technical details

running nixos, nixpkgs commit d45802973fa3281fdf10c6dafa9b6889b64b5b2f

**Comment by bjornfor** [comment]
CC @nbp for help.

**Comment by copumpkin** [comment]
That `.source` vs. `.text` stuff in general behaves in a fairly counterintuitive manner, since overriding one with the other doesn't really work. It seems like it might be worth giving the module system first-class knowledge of "synonymous options" so it can treat overrides/ordering of the two as a unit.

**Comment by anderspapitto** [comment]
yeah, that was indeed the issue. Maybe an easier fix is to just give a clear error when both `source` and `text` are specified?

**Comment by anderspapitto** [comment]
actually, I take that back. It still doesn't work, even when I'm careful to have both versions using `source` or both versions using `text`. I suspect it might be because `environment.etc` is a list, rather than an attribute set - so `{ source = "foo"; text = "bar"; }` can be a neighboring element of `{ source = "foo"; text = "baz"; }`

**Comment by nbp** [comment]
> I suspect it might be because environment.etc is a list, rather than an attribute set - so { source = "foo"; text = "bar"; } can be a neighboring element of { source = "foo"; text = "baz"; }

This is correct. `evironment.etc` is a list-or-attribute-set of submodules.  Thus you can use `mkForce` only when all elements are attribute sets.  This implies modifying pulseaudio from  https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/pulseaudio.nix#L196-L199 to : 

```nix
      environment.etc."pulse/client.conf".source = clientConf;
```

Which would give you the ability to do:

```nix
      environment.etc."pulse/client.conf".source = mkForce myClientConf;
```

**Comment by anderspapitto** [comment]
In that case, it seems like a bug to allow lists, instead of requiring attribute-sets only. It breaks this feature, and I don't see anything that is only enabled by using lists. Are there any features that require the list option?

**Comment by copumpkin** [comment]
@nbp do you agree that it might make sense to give the module system first-class understanding of "alternative" options like that, so that `mkForce` and friends work more intuitively on things like that? I can file another ticket for it if it seems worthwhile.

**Comment by nbp** [comment]
@copumpkin Honestly, I am not completely sure, because this would imply carrying the priority level as part of the value when one makes a definition.  Currently the definitions are not tied to the usage of option declarations that compose the nix expression of their definitions.  Thus merging these promess to be a nightmare and introduce more slow down.

I would prefer a documentation / convention order to approach this problem instead of a module system special case.  If you want to open a bug to make a default convention, I think this would be a good thing.

**Comment by Profpatsch** [comment]
I think there is no real solution or conclusion here, feel free to propose changes to the module system in other issues or pull requests.
