### ISSUE TITLE
Packaging request: pkgs.vscode-extensions.TheaFlowers.witch-hazel

### ISSUE THREAD

**Issue by medecau** [NixOS/nixpkgs#172418]
**A dark, feminine color theme.**
_A dark & feminine color scheme for Sublime, VS Code, JetBrains, and Pygments._

**Metadata**

* homepage URL: https://witchhazel.thea.codes/
* source URL: https://github.com/theacodes/witchhazel
* license: apache2
* platforms: any

**Comment by importantblimp** [comment]
@medecau I know it's not in nixpkgs, but [nix-community/nix-vscode-extensions](https://github.com/nix-community/nix-vscode-extensions) has many VS Code extensions including `witch-hazel`.
There are [reasons](https://discourse.nixos.org/t/vs-code-why-are-extensions-packaged-manually-and-not-automatically/20717) why VS Code extensions aren't typically included in nixpkgs. I don't know if that's official policy, but using `nix-community/nix-vscode-extensions` could get you started.

`extensions.[your system].vscode-marketplace.theaflowers.witch-hazel` is the attribute you're looking for in this case.
