### ISSUE TITLE
python39Packages.pydeck does not build: ValueError: invalid pyproject.toml config: `project`

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#172411]
### Describe the bug
python39Packages.pydeck does not build: ValueError: invalid pyproject.toml config: `project` due to updated setuptools in nixpkgs. There is a fix upstream https://github.com/visgl/deck.gl/pull/6777.

### Steps To Reproduce
```
nix-shell -p '(python39Packages.pydeck.overrideAttrs (attrs: {
  doCheck = false;
  doInstallCheck = false;
}))'
```
...
```
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:103: _ExperimentalProjec
tMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
  warnings.warn(msg, _ExperimentalProjectMetadata)
configuration error: `project` must not contain {'requires'} properties
```
### Expected behavior
pydeck builds

### Notify maintainers
@Creator54 @jonringer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 3.10.0-1160.62.1.el7.x86_64, Red Hat Enterprise Linux Server, 7.9 (Maipo), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.0`
 - channels(alex): `"nixpkgs"`
 - nixpkgs: `/u/alex/.nix-defexpr/channels/nixpkgs`

```

**Comment by Creator54** [comment]
![Screenshot_2022-05-11-13-25-57-048_com sonelli juicessh](https://user-images.githubusercontent.com/34543609/167798865-c1946444-23d4-4b1e-8259-7e54dee00aee.jpg)

does looks working for me in latest nixpkgs-unstable and latest nixpkgs(GitHub) 🤔

**Comment by KAction** [comment]
Build for me too:

```
; git log --format='%H %cd' -n1
88be12e5ddb27415e4c6c5f632695a1c46680bdf Thu May 12 21:09:49 2022 +0200
; nix-build -A python3.pkgs.pydeck
/nix/store/54fybg2cqy9pimn8z18h9vr19zf507zj-python3.9-pydeck-0.7.1
```

**Comment by alexvorobiev** [comment]
I am on nixpkgs-unstabe and it didn't build until I made a patch from that upstream PR I mentioned. Then it built.

**Comment by KAction** [comment]
Try building from master. This is what I always do (despite technically being not-promised-to-work configuration).

**Comment by natsukium** [comment]
close as resolved
