### ISSUE TITLE
hardware.video.hidpi.enable fails to set the console font early with systemd stage 1

### ISSUE THREAD

**Issue by andersk** [NixOS/nixpkgs#172403]
### Describe the bug

The `hardware.video.hidpi.enable` option, which `nixos-generate-config` enables by default on high-resolution displays like my 4K laptop screen, is supposed to set the console font within the initrd before displaying the LUKS password prompt. However, with `boot.initrd.systemd.enable`, this does not happen until stage 2, so the prompt is tiny.

### Steps To Reproduce
Enable `hardware.video.hidpi.enable = true`, `boot.initrd.systemd.enable = true`, and [LUKS encryption](https://nixos.org/manual/nixos/stable/index.html#sec-luks-file-systems).

### Expected behavior
The console font should be switched before the LUKS password prompt, not after.

### Notify maintainers
@dasJ @Mic92

### Metadata

```yaml
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.git.804685b6c8d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dasJ** [comment]
Relevant code is probably that it sets `console.earlySetup = mkDefault true;`.

`systemd-vconsole-setup` should then properly set everything up if it can find its files in `/etc/kbd`: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/console.nix#L154

**Comment by dasJ** [comment]
Does it work when you do `boot.initrd.systemd.additionalUpstreamUnits = [ "systemd-vconsole-setup.service" ]`?

**Comment by andersk** [comment]
No, it can’t, because `/etc/vconsole.conf` points to a font file that’s not present in the initrd.

```console
$ systemctl status systemd-vconsole-setup
○ systemd-vconsole-setup.service - Setup Virtual Console
     Loaded: loaded (/etc/systemd/system/systemd-vconsole-setup.service; linked; vendor preset: enabled)
     Active: inactive (dead) since Sat 2022-06-04 09:37:52 PDT; 1min 38s ago
       Docs: man:systemd-vconsole-setup.service(8)
             man:vconsole.conf(5)
   Main PID: 151 (code=exited, status=0/SUCCESS)

Jun 04 09:37:45 localhost systemd-vconsole-setup[153]: setfont: ERROR setfont.c:421 kfont_load_font: Unable to find file: /nix/store/wdrs5dxk88jg8jd6maxqsgsrcr3mvjrj-terminus-font-4.49.1/share/consolefonts/ter-v32n.psf.gz
```

**Comment by andersk** [comment]
This works though.

```nix
{
  boot.initrd.systemd.additionalUpstreamUnits = [ "systemd-vconsole-setup.service" ];
  boot.initrd.systemd.storePaths = [ config.console.font ];
}
```

It’s a little jarring in that the font is changed about a second *before* the framebuffer resolution is changed; ideally those would happen simultaneously. But at least they both happen in time for the LUKS prompt.
