### ISSUE TITLE
syncthing service failing to start (no ExecStart written to syncthing.service)

### ISSUE THREAD

**Issue by pshendry** [NixOS/nixpkgs#17244]
## Issue description

I hadn't updated my server in a month or so and have since updated it for syncthing 0.14. Now it will not start because the syncthing.service file does not have ExecStart content written to it.

I've looked at the source for the service and it looks fine to my non-expert eyes, so I'm not sure what's going wrong here.

### Steps to reproduce

My configuration for syncthing looks like this:

```
    syncthing = {
      enable = true;
      dataDir = "/path/to/data/dir";
    };
```

I tried explicitly setting `systemService = true` as well but this had no effect.

## Technical details

* System: 16.09pre87381.ddb7588 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre87381.ddb7588"

**Comment by NeQuissimus** [comment]
This is likely the same issue as #17229

**Comment by pshendry** [comment]
@NeQuissimus: quite right, not sure how I missed that one. Thanks!
