### ISSUE TITLE
Can compiler overrides for icu be removed?

### ISSUE THREAD

**Issue by SFrijters** [NixOS/nixpkgs#172462]
## Issue description

While doing some extensive rebuilds for a bisection for a wine issue I noticed I was getting gcc 6.5 things in my closure and I was wondering why.
It looks like the icu packages all override `stdenv = gcc6Stdenv;` for `stdenv.hostPlatform.isi686 && stdenv.cc.isGNU`, according to the comment to avoid issues with gcc 7: `# with gcc-7: undefined reference to '__divmoddi4'`.
Since we are way beyond gcc-7 I was wondering if we can rid of these overrides. 

As a quick test I did `nix-build -A pkgsi686Linux.icu71` after removing the override and it built just fine (on `x86_64-linux`).
I'd do a full nixpkgs-review but I'm still trying to bisect a wine issue that is taking forever, so I wanted to check for opinions first.

@7c6f434c @marsam 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.20220510.117f62e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220505_f4102de`
 - channels(frijters): `""`
 - channels(root): `"nixos, nixos-unstable-20.09pre225264.683c68232e9"`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by 7c6f434c** [comment]
Just in case: does at least one reverse dependency build after the change? But yes, seems sensible to me.

**Comment by SFrijters** [comment]
My NixOS machine was busy doing rebuilds for some other PRs, but I'll do some more thorough checking now that I know for sure that it's a sensible idea at least.
