### ISSUE TITLE
Unable to open VSCode

### ISSUE THREAD

**Issue by kuwii** [NixOS/nixpkgs#172450]
### Describe the bug

Unable to open VSCode. Using `code --verbose`, the error message is:

```
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
[1480:0511/131027.276644:FATAL:platform_selection.cc(45)] Invalid ozone platform: wayland}}
```

Using `code --ozone-platform=x11` works as expected.

### Steps To Reproduce

1. Related NixOS configurations:
    ```
    nixpkgs.config.allowUnfree = true;
    services.xserver.enable = true;
    services.xserver.displayManager.sddm.enable = true;
    services.xserver.desktopManager.plasma5.enable = true;
    environment.systemPackages = with pkgs; [ vscode ];
    ```
2. Rebuild, and login using Plasma X11.
3. Open terminal and run `code --verbose`

### Expected behavior

VSCode should be opened.

### Screenshots

![Screenshot_20220511_131748](https://user-images.githubusercontent.com/10705175/167774314-7ccb4e37-3687-412d-a51f-faea089c204a.png)

### Additional context

Desktop environment is KDE Plasma X11.

### Notify maintainers

@samuela 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.37, NixOS, 22.05 (Quokka), 22.05pre376605.f419dc5763c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos, nixt"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by mnuccioarpae** [comment]
I have the same issue, but it works with:

    code --enable-features=UseOzonePlatform --ozone-platform=wayland

**Comment by archer-65** [comment]
> I have the same issue, but it works with:
> 
>     code --enable-features=UseOzonePlatform --ozone-platform=wayland

Doesn't work for me, are you on wayland?

**Comment by samuela** [comment]
I'm not a maintainer of vscode. You're looking for @eadwu @Synthetica9 @maxeaubrey @bobby285271.

**Comment by ncfavier** [comment]
This was fixed by https://github.com/NixOS/nixpkgs/pull/172320
