### ISSUE TITLE
gtk: input methods stop working for gtk apps after version 3.24.32 under wayland (sway)

### ISSUE THREAD

**Issue by theknyaa** [NixOS/nixpkgs#172406]
### Describe the bug
An upstream change between version 3.24.31 and 3.24.32 modifies the build system, such that a file named `immodules.cache`, which is required for input method support, is no longer generated along with the build, which causes apps depending on gtk to no longer support text input via an IME.

### Steps To Reproduce
1. on current nixos unstable (`22.05pre372961.e10da1c7f54 (Quokka)`), start gedit using WAYLAND_DISPLAY=1
2. search for `text_input` in the resulting log. Only the global announcement event for the text_input_manager is present, and there are no further interactions.

### Expected behavior
The program requests `zwp_text_input_manager_v3.get_text_input` from the wayland compositor so that it can receive input via an input method.

### Additional context
i was perhaps a bit too quick and [reported this upstream](https://gitlab.gnome.org/GNOME/gtk/-/issues/4908), where I was told that managing this file is up to the package manager anyways. Subsequently, I have found out that there is some kind of mechanism for managing a custom version of this file via `i18n.inputMethod`, but I'm (a) not sure how to add wayland (text_input_v3) there, and (b) I think that having this work out of the box, at least on wayland, was probably a desirable feature? Either way, I'd be happy to hear more about this from someone who knows more about this.

I've just tested a patch where I simply run the missing invocation in postInstall, and this does actually fix the problem. If you think this approach is sensible, I'm happy to open a PR, but given the existing mechanisms I thought I'd ask first about how all this was intended.

The thing I've added to postInstall is just an invocation of `gtk-query-immodules-3.0` (it's not pretty, but enough for testing):

```
immodules_cache="''${out:?}/lib/gtk-3.0/3.0.0/immodules.cache"
GTK_PATH="''${out:?}/lib/gtk-3.0/3.0.0/immodules/" GTK_IM_MODULE_FILE="''${immodules_cache}" ''${dev:?}/bin/gtk-query-immodules-3.0 --update-cache
```

### Notify maintainers

@7c6f434c @bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 22.05 (Quokka), 22.05pre372961.e10da1c7f54`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Looks like this commit is responsible: https://gitlab.gnome.org/GNOME/gtk/-/commit/b5d0c44a87443bc4aadcb35009ecb5e2674432df

Looking at the [script that was used before](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.33/build-aux/meson/post-install.py#L45), your solution looks about right. Maybe it would be possible to get the paths from pkg-config but not sure if it will end up looking cleaner.

**Comment by theknyaa** [comment]
Hmm, so, there already is a script touching this exact file in [pkgs/development/libraries/gtk/hooks/clean-immodules-cache.sh](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gtk/hooks/clean-immodules-cache.sh), and my initial attempt at fixing this was actually doing it in there. (Or, ideally, adding a second hook like that.) However, that lead to weird problems where this somehow affected the build for libpeas, and I'm also a bit confused as to why the script runs as a setup hook only to add a function to fixupOutputHooks. If you agree with the approach in principle, I think now might be the time for me to actually find out what's going on there '^^

**Comment by theknyaa** [comment]
... nevermind, I think the [documentation](https://nixos.org/manual/nixpkgs/stable/#ssec-setup-hooks) just answered both of my questions at once, I apologize for not checking more thoroughly earlier ^^

**Comment by jtojnar** [comment]
I think we still want to have the file cleared everywhere other than in GTK, which the setup hook does. So we just need to add the code you mention in the opening post to `postInstall` of `gtk3`.

**Comment by theknyaa** [comment]
Neat, thank you. I'll submit a PR, and then we can talk about how to make things pretty there.
