### ISSUE TITLE
makeBinaryWrapper: breaks downstream derivations which edit wrappers

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#172592]
### Describe the bug
At least one derivation exists which copies and then edits a wrapper. This no longer works with makeBinaryWrapper.

https://github.com/LavaDesu/powercord-overlay/blob/61458f8d09b977fe4347ef68c1a29b4ac4ae3baf/drvs/discord.nix

### Steps To Reproduce
1. Build the linked derivation

### Expected behavior
Succeeds

### Actual behavior
substituteInPlace fails with:

```
error: builder for '/nix/store/hhifdwfj3265yq6kgk27dlp4v0i1rvv4-discord-plugged.drv' failed with exit code 1;
       last 1 log lines:
       > consumeEntire(): ERROR: Input null bytes, won't process
```

**Comment by LunNova** [comment]
Made this issue as I wasn't sure how best to handle this downstream.

**Comment by ncfavier** [comment]
A similar issue came up with the firefox wrapper: https://github.com/NixOS/nixpkgs/pull/171985. Do you happen to know why exactly editing the wrapper is needed? How does discord decide where to look for its resources?

**Comment by ncfavier** [comment]
Ah, forgot discord was closed source. Good luck with that.

**Comment by LunNova** [comment]
Looks like the same fix for the firefox thing applies here.

Adding a generic way of extracting the original arguments to makeWrapper somewhere in `pkgs/build-support` sound like a good way of dealing with this for the general case? I could extract out the code you added in #171985.

The issue isn't specific to discord, it's just the first thing I ran into.

**Comment by ncfavier** [comment]
Ah thanks for reminding me, I wanted to do that. I'll squeeze it into https://github.com/NixOS/nixpkgs/pull/172366

**Comment by LunNova** [comment]
Approach which works regardless of wrapper type:

```
    if grep '\0' $out/opt/DiscordCanary/DiscordCanary && wrapperCmd=$(${extractCmd} $out/opt/DiscordCanary/DiscordCanary) && [[ $wrapperCmd ]]; then
      # Binary wrapper
      parseMakeCWrapperCall() {
        shift # makeCWrapper
        oldExe=$1; shift
        oldWrapperArgs=("$@")
      }
      eval "parseMakeCWrapperCall ''${wrapperCmd//"${discord-canary.out}"/"$out"}"
      makeWrapper $oldExe $out/opt/DiscordCanary/DiscordCanary "''${oldWrapperArgs[@]}" --add-flags "${extraElectronArgs}"
    else
      # Normal wrapper
      substituteInPlace $out/opt/DiscordCanary/DiscordCanary \
      --replace '${discord-canary.out}' "$out" \
      --replace '"$@"' '${extraElectronArgs} "$@"'
    fi
```
