### ISSUE TITLE
Is it time to remove flatbuffers 1.12?

### ISSUE THREAD

**Issue by tjni** [NixOS/nixpkgs#172596]
We define two [flatbuffers](https://github.com/google/flatbuffers) packages, one for version 1.12 and one for version 2.0. The package for version 1.12 [no longer builds on Hydra with clang](https://hydra.nixos.org/build/176096751).

Upstream has the fixes needed but only for version 2.0. The version 1.12 branch does not appear maintained, and there [have not been any commits](https://github.com/google/flatbuffers/commits/v1.12.1) to it since March of 2020.

We can continue to maintain this (e.g. we can disable warnings, or we can adapt those fixes to 1.12 and patch them), but perhaps we could drop support for the old version altogether?

ZHF: #172160

/cc @teh @cpcloud

**Comment by Mindavi** [comment]
Disabling -Werror is always reasonable, but if there's no users left in nixpkgs I think it's ok to drop it. Unless the maintainer @teh or someone else still has a use for this.

**Comment by SuperSandro2000** [comment]
`flatbuffers_1_12` is unused and can be safely removed.
