### ISSUE TITLE
Manual page validation & generation is getting too slow

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#17261]
With the current amount of configuration options the system rebuild process is approaching unbearably long times (10+s on my CPU from 2007).
With the amount of options growing exponentially this is going to be a serious problem quite soon.

I noticed `xsltproc` only uses one core for validation, so a big speedup is trivialy achievable. Sadly, `xsltproc`  doesn’t support multithreading, but the manual generation should be easily paralellizable, by splitting the manual sections up in single derivations.
Maybe even one for each nix module file, that would also lead to the manual not completely rebuilding on every change to an option.

**Comment by domenkozar** [comment]
Maybe using GNU parallel: https://www.gnu.org/software/parallel/parallel_tutorial.html

**Comment by edolstra** [comment]
Generally changing the system configuration should not trigger a rebuild of the manual (so the manual/manpages will be fetched from the binary cache). If that does happen, it's usually caused by something like an option default depending on an option value.

**Comment by Profpatsch** [comment]
Ah, this is for developers & patchers of course. Everyone who defines new options. I think the time of those people is extremely important as well, if not more (otherwise nobody likes to define new options anymore).

**Comment by Profpatsch** [comment]
I’d still like to see a solution to this, but wasn’t annoyed enough yet to start working on it.

**Comment by Profpatsch** [comment]
Will hopefully fixed by the new manual format in the near future.

**Comment by mbrgm** [comment]
@Profpatsch Could you provide a reference to that?

**Comment by Profpatsch** [comment]
https://github.com/NixOS/rfcs/pull/64
