### ISSUE TITLE
lean's cmake discovers non-nix lua

### ISSUE THREAD

**Issue by cobbal** [NixOS/nixpkgs#17260]
## Issue description

lean fails to build when homebrew version of lua is installed; cmake gets confused and dies.

### Steps to reproduce

Have a version of lua installed in /usr/local/lib, then try to install lean:

    $ brew install lua
    ...
    $ nix-env -iA nixpkgs.lean
    ...
    -- Found Lua: /usr/local/lib/liblua.dylib (found version "5.1.4")
    ...
    Undefined symbols for architecture x86_64:
      "_luaL_loadfile", referenced from:
    ...

If the brew version is unlinked the build works fine, and finds the nix lua version. I assume that somewhere in `src/cmake/Modules/FindLua.cmake` cmake is searching global paths. However, I don't see an explicit reference to /usr/local, and I don't understand cmake well enough to debug it.

## Technical details

* System: OS X 10.11.6 (15G31)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre87131.292bfed

**Comment by gebner** [comment]
The lean version in nixpkgs is pretty old.  Lua support has since been removed by upstream, so it would be enough to switch to a newer git revision to fix this.
