### ISSUE TITLE
 dart 2.15.1->2.17.0

### ISSUE THREAD

**Issue by NANASHI0X74** [NixOS/nixpkgs#172674]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 2.15.1
desired version: 2.17.0

###### Notify maintainers

maintainers: @GRBurst @flexagoon

###### Note for maintainers

Please tag this issue in your PR.

**Comment by flexagoon** [comment]
Seems to be done in #172780

**Comment by NANASHI0X74** [comment]
nice 👍
