### ISSUE TITLE
packaging request: rt-tests

### ISSUE THREAD

**Issue by peng1999** [NixOS/nixpkgs#172655]
**Project description**
Some programs that test various rt-linux features

**Metadata**

* homepage URL: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
* source URL: https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
* license: gpl2+
* platforms: linux

**Comment by importantblimp** [comment]
Hey @peng1999, I see this was done under #172330. Can we close off this issue?

**Comment by peng1999** [comment]
> Hey @peng1999, I see this was done under #172330. Can we close off this issue?

Sure.
