### ISSUE TITLE
GNOME 42: On-screen keyboard broken

### ISSUE THREAD

**Issue by lorenz** [NixOS/nixpkgs#172629]
### Describe the bug
In GNOME 42 in Tablet mode the on-screen keyboard (OSK) is very broken. On Gnome's own UI it shows up but was not reacting to touches (that was https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5273, https://github.com/NixOS/nixpkgs/pull/169429), but on normal applications (tried GTK3, GTK4 and QT5) it doesn't even show up. When manually enabling it through accessibility options it doesn't show up either. The gesture is broken upstream (https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5335), but it not working at all is AFAIK a NixOS issue.

This should really be fixed for 22.05 as otherwise this release is basically unusable on 2-in-1s and tablets.

### Steps To Reproduce
1. Use a Tablet or a 2-in-1 (with SW_TABLET_MODE working) in tablet mode
2. Open a GTK3 (known-working) application and tap into a text field
3. Use the swipe gesture to pull up the text field

### Expected behavior
The On-screen keyboard should appear and take touch input.

### Notify maintainers
@bobby285271
@hedning
@jtojnar
@dasj19
@maxeaubrey

### Metadata
Not currently on the machine, was running nixos-unstable from ~7 days ago with my backport for the first issue.

**Comment by jtojnar** [comment]
GTK 3 might also be affected by #172406.

**Comment by lorenz** [comment]
Still doesn't explain why it doesn't even come up by manually enabling it from the accessibility settings.

**Comment by Erfboom** [comment]
So for me it maybe works in the session manager, but sometimes I have to enable it in the accessibility settings. Once in gnome, it works for anything gnome related, but I can't swipe up to bring it up (and I believe the other gestures haven't worked for me as well). It doesn't work in any QT5 app I have (kate, dolphin, konsole), but it does work in Firefox and Thunderbird provided I export MOZ_USE_XINPUT2=1 MOZ_ENABLE_WAYLAND=1. Xinput will allow firefox to respond to touch gestures (pinch to zoom) and enable wayland will allow the keyboard to appear for almost all text boxes within firefox (but it has issues with extensions: bitwarden).

Sometimes even in the gnome apps, and firefox, I have to tap the text box a few times until the keyboard appears, but as a 2-in-1 user myself, the lack of OSK makes gnome unusable with any programs that aren't provided by gnome in tablet mode.

Finally, exporting QT_QPA_PLATFORM=wayland in environments nor commandline seems to have an affect on the KDE QT5 apps.

**Comment by lorenz** [comment]
Has long been fixed in GNOME 42.2 with https://github.com/NixOS/nixpkgs/pull/175424.

**Comment by peigongdsd** [comment]
Seems it's broken again now in gnome 46 now, Exactly the same issue.

**Comment by jtojnar** [comment]
That will be a different issue then, since this was resolved upstream.

**Comment by Aitanuqui** [comment]
Was there a regression? **The OSK** —in tablet mode or when enabled from accessbility options— only shows up in text fields from gnome-shell's launcher, the search bar in the Clipboard Indicator extension and GDM's login. It **doesn't show up in gnome core apps or firefox.** The swipe gesture to bring it up works and the OSK does react to touch input.

This happens on GNOME 49 and GNOME 50 with NixOS 25.11 and 26.05. I used to have fedora 43 with GNOME 49, and I didn't have this problem.

**Comment by Aitanuqui** [comment]
I found a fix with
```
i18n.inputMethod.enable = lib.mkForce false;
```

I wonder what part of it interferes with the OSK in a way it won't open it.

In Firefox I usually have to click/tap twice for the OSK to pop up. In GTK4 apps the OSK seems to work much better, though.
FWIW, if [this](https://issues.chromium.org/issues/510839988) gets implemented, we may be closer to using the OSK in chromium-based apps.

**Comment by peigongdsd** [comment]
> I found a fix with
> 
> ```
> i18n.inputMethod.enable = lib.mkForce false;
> ```
> 
> I wonder what part of it interferes with the OSK in a way it won't open it.
> 
> In Firefox I usually have to click/tap twice for the OSK to pop up. In GTK4 apps the OSK seems to work much better, though. FWIW, if [this](https://issues.chromium.org/issues/510839988) gets implemented, we may be closer to using the OSK in chromium-based apps.

I believe a better approach is
```
  environment.variables = {                                                                                                                                                                                                                                                                     
        GTK_IM_MODULE = lib.mkForce "";                                                                                                                                 
        QT_IM_MODULE = lib.mkForce "";                                                                                                                                  
        XMODIFIERS = lib.mkForce "";                                                                                                                                                                                                                                        
      };      
```
These are automantically set in nixpkgs once you enable some IME, but this is a wrong behaviour. It shouls be filled in during runtime by gnome shell.

**Comment by Aitanuqui** [comment]
@peigongdsd I'm thinking of making an issue about this. What do you think is the module/pkg at fault?

**Comment by peigongdsd** [comment]
> king of making an issue about this. What do you think is the module/pkg at fault?

I did not take action because of my laziness, and I did not know if this works on others' side or not... if it works on your side, then,

Actually this requires patches on two sides. These variables are set on the modules of IMEs, e.g. https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/i18n/input-method/ibus.nix and this is the right behaviour if you're using some wm other than gnome. However, if one wants to use gnome with ibus, then they must have these settings disabled. So there should also be some setting in gnome, detecting if config has enabled ibus, and disable these variables respectively

**Comment by Aitanuqui** [comment]
> > king of making an issue about this. What do you think is the module/pkg at fault?
> 
> I did not take action because of my laziness, and I did not know if this works on others' side or not... if it works on your side, then,
> 
> Actually this requires patches on two sides. These variables are set on the modules of IMEs, e.g. https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/i18n/input-method/ibus.nix and this is the right behaviour if you're using some wm other than gnome. However, if one wants to use gnome with ibus, then they must have these settings disabled. So there should also be some setting in gnome, detecting if config has enabled ibus, and disable these variables respectively

I was thinking that the i18n.inputMethod module could provide an option to enable or disable these environment variables, and the gnome module could have this option disabled by default.
