### ISSUE TITLE
Package new NVIDIA open-source GPU kernel modules

### ISSUE THREAD

**Issue by danielfullmer** [NixOS/nixpkgs#172603]
**Project description**
NVIDIA has released some new GPU kernel modules licensed under dual GPL/MIT. It's be nice be able to use these on NixOS. See the links below for further details.

CC @jonringer @abbradar 

**Metadata**

* homepage URL: https://developer.nvidia.com/blog/nvidia-releases-open-source-gpu-kernel-modules/
* source URL: https://github.com/NVIDIA/open-gpu-kernel-modules
* license: mit, gpl2
* platforms: linux

**Comment by VergeDX** [comment]
ArchLinux got the job done first!
https://archlinux.org/packages/testing/x86_64/nvidia-open/

**Comment by SomeoneSerge** [comment]
cc @NixOS/cuda-maintainers

**Comment by dmayle** [comment]
Hi, is this still going to be merged?

**Comment by nrdxp** [comment]
Just fyi, I'm giving this a shot right now. Actually building the sources was very straightfoward. It looks like we just need some modifications to the installPhase. With any luck I'll have a PR later today.

**Comment by samuela** [comment]
@nrdxp how is your build different from https://github.com/NixOS/nixpkgs/pull/172660?

**Comment by nrdxp** [comment]
@samuela whoops somehow I totally overlooked the open PR. Anyway, I got mine building but I haven't had a chance to test it yet. I guess on first glance mine is different in that it prefers the open source build if it's available.

**Comment by NickCao** [comment]
> @samuela whoops somehow I totally overlooked the open PR. Anyway, I got mine building but I haven't had a chance to test it yet. I guess on first glance mine is different in that it prefers the open source build if it's available.

The open source version is alpha quality and should be opt-in for now.
