### ISSUE TITLE
flutter:2.10.1->3.0.0

### ISSUE THREAD

**Issue by NANASHI0X74** [NixOS/nixpkgs#172673]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: flutter, dart

current version: 2.10.1
desired version: 3.0.0

###### Notify maintainers

maintainers: @ericdallo @babariviere @thiagokokada 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by NANASHI0X74** [comment]
was released yesterday. I think I'm going to have a go at this

**Comment by smancill** [comment]
Should be solved by #173200
