### ISSUE TITLE
package request: sfz - simple static file server (rust)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#172753]
**Project description**

https://github.com/weihanglo/sfz

 A simple static file serving command-line tool written in Rust. 

**Metadata**

* homepage URL: https://github.com/weihanglo/sfz
* source URL: https://github.com/weihanglo/sfz
* license: apl2
* platforms: *

**Comment by ModdedGamers** [comment]
Working on this now.

**Comment by dit7ya** [comment]
@theHedgehog0 Are you working on this? Otherwise I will give it a try.

**Comment by theHedgehog0** [comment]
I'm no longer working on this. Feel free.
