### ISSUE TITLE
jxplorer: A free java ldap client

### ISSUE THREAD

**Issue by benwbooth** [NixOS/nixpkgs#172879]
**Project description**
A free java ldap client with LDIF support, security (inc SSL, SASL & GSSAPI), translated into many languages (inc. Chinese), online help, user forms and many other features.

**Metadata**

* homepage URL: http://jxplorer.org/
* source URL: https://github.com/pegacat/jxplorer
* license: CA open source license
* platforms: unix, linux, darwin

**Comment by importantblimp** [comment]
Hey @benwbooth, it looks like you sorted this out under #210461. Can you please close this issue?
