### ISSUE TITLE
grantpt failed: Operation not permitted

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#17284]
## Issue description

In the most recent nixos-unstable `16.09pre87431.3badad8`, when I tried to run `xfce4-terminal`, it would fail with the error `grantpt failed: Operation not permitted`.

After a little bit of search I found this:
http://lists.science.uu.nl/pipermail/nix-dev/2010-January/003752.html

And resolved the issue by adding my user to the `tty` group.

I would just like to people having the same issue to avoid having to search elsewhere than Github, so this issue is just a way for people to find this solution easily.

Best.

**Comment by bburdette** [comment]
Fixed this by adding the line 
```
    extraGroups= [ "tty" ];
```
to my user definition in /etc/nixos/configuration.nix

**Comment by dezgeg** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/17822. Any workarounds involving the tty group should not be needed or used now.
