### ISSUE TITLE
veriT does not build on darwin

### ISSUE THREAD

**Issue by siraben** [NixOS/nixpkgs#172929]
### Describe the bug
The `veriT` package fails to build on `aarch64-darwin`. Log: http://ix.io/3XHc

```
$ nix log /nix/store/p38hp0qgjw59zlzq5k88y5rrz3vlcv5m-veriT-2021.06.2.drv | ix
http://ix.io/3XHc
```
### Steps To Reproduce
`nix build .#veriT` on commit 7daec9cdd73b45b31a1012df321b9122de5ae42f

### Expected behavior
It should build.

### Notify maintainers
@gebner

### Metadata
```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.4.0, macOS 12.3.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.0pre20220422_7f814d6`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by wegank** [comment]
Closing since veriT now builds on darwin ([x86_64](https://hydra.nixos.org/job/nixpkgs/trunk/veriT.x86_64-darwin), [aarch64](https://hydra.nixos.org/job/nixpkgs/nixpkgs-unstable-aarch64-darwin/veriT.aarch64-darwin)).

**Comment by siraben** [comment]
Great!
