### ISSUE TITLE
Please update generated list of Emacs packages

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#17298]
### Steps to reproduce

The list of Emacs packages is 3 weeks old. Could somebody please update it?

I can't do it myself because of https://github.com/ttuegel/emacs2nix/issues/23.

/cc @ttuegel @bendlas @dezgeg @mdorman

**Comment by mdorman** [comment]
At home I have an updated list I can open a pr for this evening.
 
Mike
 
 
On Wed, Jul 27, 2016, at 08:33, Damien Cassou wrote:
> Steps to reproduce
> The list of Emacs packages is 3 weeks old. Could somebody please
> update it?
> I can't do it myself because of ttuegel/emacs2nix#23[1].
> /cc @ttuegel[2] @bendlas[3] @dezgeg[4] @mdorman[5]
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[6], or mute the thread[7].
>

Links:

  1. https://github.com/ttuegel/emacs2nix/issues/23
  2. https://github.com/ttuegel
  3. https://github.com/bendlas
  4. https://github.com/dezgeg
  5. https://github.com/mdorman
  6. https://github.com/NixOS/nixpkgs/issues/17298
