### ISSUE TITLE
Leading dot in repo name throwing illegal name error - fetchFromBitbucket, fetchFromGitHub, nix-prefetch-git

### ISSUE THREAD

**Issue by erlandsona** [NixOS/nixpkgs#17291]
Why aren't leading dots allowed in the repo name for them to be valid Nix expressions / derivations?

## Issue description
The following all fail with the following ```error: illegal name: `.dotfiles` ``` 
nix-prefetch-git
fetchFromGitHub - in nix-repl
fetchFromBitbucket - in nix-repl

### Steps to reproduce
nix-prefetch-git https://bitbucket.org/erlandsona/.dotfiles
or in a nix-repl
```
fetchFromBitbucket { owner = "erlandsona"; repo = ".dotfiles"; rev = "6a7f45c3d5dd73d61f2c46eb4339ae1626d58e02"; sha256 = "1234"; }
```

## Technical details

* System: NixOS in a VirtualBox machine on a 15" MBP.
* Nix version: 1.11.2
* Nixpkgs version: 16.03.1083.d745044

**Comment by rasendubi** [comment]
As far as I understand, the issue is caused by fact derivation names can't contain `.`. Use `name` parameter to override derivation name:
```nix
fetchFromBitbucket {
  name = "erlandsone-dotfiles";
  owner = "erlandsona";
  repo = ".dotfiles";
  rev = "6a7f45c3d5dd73d61f2c46eb4339ae1626d58e02";
  sha256 = "1234";
}
```
