### ISSUE TITLE
Update vlang

### ISSUE THREAD

**Issue by Milo123459** [NixOS/nixpkgs#173062]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: weekly.2021.51
desired version: weekly.2022.19

###### Notify maintainers

@Madouura 

maintainers:

###### Note for maintainers

Could some sort of auto-updater be added in for this?

**Comment by Madouura** [comment]
Current PR regarding this is #161333

**Comment by Milo123459** [comment]
I saw that PR, but for some of my projects I need the latest version as it has some features I need. Thought I'd make an issue.

What about auto-updating, btw?

**Comment by Madouura** [comment]
I'm not sure, superficially I think it would be okay though.
vlang is rather fast-moving, and that's both a good reason to auto-update, and a bad reason as there may be breaking changes regarding packaging it.

**Comment by Milo123459** [comment]
Yeah, good point. I still think that auto-updating is just a good idea so that issues like this don't have to be created.
