### ISSUE TITLE
upgrade to contour 0.3

### ISSUE THREAD

**Issue by felschr** [NixOS/nixpkgs#173020]
**Project description**
Currently, `contour` in nixpkgs is at 0.1.1 while upstream is currently at [0.3.1.200](https://github.com/contour-terminal/contour/releases/tag/v0.3.1.200).

I've attempted updating it myself, but I'm having issues with the new `libunicode` dependency. I'm not very familiar with cmake, ninja and C++ packaging in general. Perhaps someone else can help.
Here's my attempt: https://github.com/felschr/nixpkgs/commits/contour

**Metadata**
* homepage URL: https://github.com/contour-terminal/contour
* source URL: https://github.com/contour-terminal/contour
* license: asl20
* platforms: unix

**Maintainers**
@fortuneteller2k

**Comment by fortuneteller2k** [comment]
#175239
