### ISSUE TITLE
Vagrant error when adding images since 1.8.4

### ISSUE THREAD

**Issue by Mayeu** [NixOS/nixpkgs#17300]
## Issue description

Since the last 1.8.4 version of Vagrant I can not download or import images anymore (the previous 1.8.1 version is fine), every time I get the following error:
```
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

/nix/store/g4z762r2qzrwp1dmjjlks67mwx6mgg2p-vagrant-1.8.4/opt/vagrant/embedded/bin/bsdtar: symbol lookup error: /nix/store/g4z762r2qzrwp1dmjjlks67mwx6mgg2p-vagrant-1.8.4/opt/vagrant/embedded/bin/bsdtar: undefined symbol: archive_read_set_passphrase_callback
```

But when I rollback to vagrant 1.8.1 everything is fine.

### Steps to reproduce

1. Install vagrant 1.8.4
2. Try to download a image not in your cache: ```vagrant box add ubuntu/xenial64```

## Technical details

* System: NixOS 16.09pre87431.3badad8 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: "16.09pre87431.3badad8"

*Allowing myself to poke the maintainers and the person that did the last pull request: @lovek323, @globin, @jgeerds, and @siddharthist*

**Comment by jdreaver** [comment]
I'm experiencing the same issue. Is there a workaround? I wonder if this is an issue with vagrant or with `libarchive` (where `bsdtar` is from).

**Comment by Mayeu** [comment]
@jdreaver my current workaround is to use 1.8.1 :)

It seems there is a new 1.8.5 version out for Vagrant, maybe it solves that? (I have seriously no clue what is this ```undefined symbol: archive_read_set_passphrase_callback```)

**Comment by Mayeu** [comment]
Quick precision, I use the version 1.8.1 via an old commit of the Nixpkgs repository, so it comes with old libarchive also. So maybe it could be worth exploring mixing those old libarchive and new vagrant to see what trigger the bug. Saddly I do not have much time currently for testing this.

**Comment by jdreaver** [comment]
I cloned `nixpkgs`, set it to `nixos-unstable`, manually reverted vagrant to `1.8.1`, and the errors still persisted. I'm pretty sure the problem is with `libarchive` (where `bsdtar` is located).

**Comment by jdreaver** [comment]
Weird, I manually ran `bsdtar` by archiving and unarchiving some files and I couldn't reproduce the error.

**Comment by jdreaver** [comment]
Okay, I manually downloaded a box and ran `bsdtar` on it with the same options Vagrant does (see [here](https://github.com/mitchellh/vagrant/blob/c6f2f3bd12ea1baf22ae6a37e1bd045b3df2b627/lib/vagrant/box_collection.rb#L119) for their usage). I got no errors. I wonder if the Ruby Subprocess is affecting this in any way.

I'm not really sure where to go from here :/

Sorry for making multiple comments in a row like this. Next time I'll do my research and chunk everything I find together in one comment :)

**Comment by retrry** [comment]
So, I found a workaround for this problem (my whole work grinded to a halt with this bug), but beware that it is the ugliest thing you can do on NixOS. 

remount /nix/store with rw permissions remove all libarchive files from vagrant/embedded/lib and replace those files with new ones from Nix libarchive.

As I said - this goes against everything that is NixOS.

**Comment by jdreaver** [comment]
Interesting, that is ugly! Haha

I think we've arrived at the conclusion then that the libarchive `bsdtar` is fine when used alone, and it's fine when used as a symlink (in `/nix/store/...-vagrant/opt/vagrant/embedded/bin/bsdtar`) from the shell, but when vagrant uses it in a Ruby subprocess we get an error.

My workaround was just to downgrade my nix-channel to 16.03, use Vagrant 1.8.1 to download and unpack the box, and then switch back to nixos-unstable.

**Comment by globin** [comment]
Vagrant most probably uses a precompiled gem linking to libarchive where the newer vagrant version comes with a gem that depends on a different ABI than our current libarchive.

**Comment by jdreaver** [comment]
Hmm, I can't seem to find any gems for bsdtar or libarchive in vagrant. Also, it looks like they `apt-get install bsdtar` for [their CI](https://github.com/mitchellh/vagrant/blob/d7c43723ff7d9593d8f3920780067ccdfd84c3e8/.travis.yml#L13), so I don't think they are using a gem for it, at least on Linux.

Since they are just using a Ruby subprocess that calls "bsdtar", wouldn't there have to be a binary in their PATH called exactly `bsdtar`?

Thanks for the tip, I'm not very experienced in Ruby :)
