### ISSUE TITLE
packaging request: KDiskMark

### ISSUE THREAD

**Issue by coolshaurya** [NixOS/nixpkgs#173010]
**Project description**
KDiskMark is an HDD and SSD benchmark tool with a very friendly graphical user interface. KDiskMark with its presets and powerful GUI calls [Flexible I/O Tester](https://github.com/axboe/fio) and handles the output to provide an easy to view and interpret comprehensive benchmark result. The application is written in C++ with Qt and doesn't have any KDE dependencies. 

**Metadata**

* homepage URL: https://github.com/JonMagon/KDiskMark
* source URL: https://github.com/JonMagon/KDiskMark
* license: GPL 3.0
* platforms: Linux

**Comment by Lyndeno** [comment]
I am currently trying to work on this. It builds and runs, sometimes I run into a Kauth error

**Comment by symphorien** [comment]
see https://github.com/NixOS/nixpkgs/pull/181605, please review
