### ISSUE TITLE
nm-applet: Segmentation fault

### ISSUE THREAD

**Issue by danykey** [NixOS/nixpkgs#17319]
## Issue description

I have use i3wm and sometimes run nm-applet for managing network connections.
Today I got:

```
** (nm-applet:4844): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Segmentation fault
```

When I tried run nm-applet under root then got "Segmentation fault" without the warning.

Some times ago I had run nm-applet without any troubles.
### Steps to reproduce

Run `nm-applet`.
## Technical details
- System: 16.03.1148.c78f7c4 (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.03.1148.c78f7c4"
- Linux nixos 4.6.4 #1-NixOS SMP Mon Jul 11 16:30:07 UTC 2016 x86_64 GNU/Linux

**Comment by mogorman** [comment]
@danykey is this still an issue? can you provide anymore  info?

**Comment by isaacaggrey** [comment]
I think this can be closed. I have a relatively fresh install of NixOS, use i3wm, and don't have issues with `nm-applet` segfaulting. However, I also don't need to run `nm-applet` as root.
