### ISSUE TITLE
dotnet 5 is EOL

### ISSUE THREAD

**Issue by mdarocha** [NixOS/nixpkgs#173115]
## Issue description

Since May 10, .NET 5.0 is EOL (End Of Life), and should not be used.
Should it be marked as EOF similar to dotnet 2.2 and 3.0?

### Steps to reproduce

See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

## Replacing packages using `dotnet-sdk_5`

All packages using dotnet 5.0 should be updated to use a newer, supported version.
These packages still need updating:

- [x] pkgs/servers/nosql/eventstore/default.nix - https://github.com/NixOS/nixpkgs/pull/202571
- [x] pkgs/applications/science/logic/formula/default.nix - https://github.com/NixOS/nixpkgs/pull/178481#pullrequestreview-1019321122
- [x] pkgs/applications/blockchains/wasabiwallet/default.nix - https://github.com/NixOS/nixpkgs/pull/202582
- [x] pkgs/development/tools/build-managers/msbuild/default.nix - https://github.com/NixOS/nixpkgs/pull/202751
- [x] pkgs/development/compilers/roslyn/default.nix - https://github.com/NixOS/nixpkgs/pull/202765

**Comment by IvarWithoutBones** [comment]
> Btw, I'm not sure if we have any policy regarding packages removal, for nixpkgs in general or specifically for it's dotnet part

I think we should just mark it as depricated, as many projects do still use it upstream. Dotnet version 3 is also still commonly used, so I dont expect it would be realistic to remove version 5 any time soon.

> There is at least one package, which currently uses dotnet 5 sdk

`buildDotnetModule` also uses dotnet 5 by default, I'll go ahead and switch that over now. See #173304. That doesnt mark dotnet 5 as deprecated or change anything from a SDK perspective, just some preperation work.

**Comment by IvarWithoutBones** [comment]
See #175354 as well, it adds a warning whenever dotnet version 5 is used. Not using a throw for now since a few packages depend on it and I dont have the time to clean that all up at the moment.

**Comment by mdarocha** [comment]
> See #175354 as well, it adds a warning whenever dotnet version 5 is used. Not using a throw for now since a few packages depend on it and I dont have the time to clean that all up at the moment.

Can you provide a list of packages that need updating?

**Comment by IvarWithoutBones** [comment]
> > See #175354 as well, it adds a warning whenever dotnet version 5 is used. Not using a throw for now since a few packages depend on it and I dont have the time to clean that all up at the moment.
> 
> Can you provide a list of packages that need updating?

Based on a quick grep:

* pkgs/servers/nosql/eventstore/default.nix
* pkgs/applications/science/logic/formula/default.nix
* pkgs/applications/blockchains/wasabiwallet/default.nix
* pkgs/development/tools/build-managers/msbuild/default.nix

**Comment by mdarocha** [comment]
I believe that after all the above PRs are merged, we should be able to safely remove .NET 5 from nixpkgs :)
