### ISSUE TITLE
have dynamic linker warn when loading library outside of nix store

### ISSUE THREAD

**Issue by jcumming** [NixOS/nixpkgs#1731]
It would be nice to have glibc's dynamic linker throw a warning to stderr when it resolved symbols from shared objections outside the nix store. 

This would help debug issues where LD_LIBRARY_PATH or LD_PRELOAD injects impurities.

**Comment by Mathnerd314** [comment]
You can trace the libraries that are loaded with ``LD_DEBUG=reloc <cmd>``, which does indeed write to stderr. Someone could further extend this by adding a ``LD_DEBUG=nixos`` type, but it seems like little benefit would be gained; NixOS already has obvious impurities, such as ``/run/opengl-driver``, so filtering would be better off as a post-processing step.

**Comment by garbas** [comment]
@jcumming @shlevy @Mathnerd314 is somebody working on this?

on cygwin i used few scripts which warn me about this.

**Comment by Profpatsch** [comment]
triage: I’m gonna close since this stagnated, feel free to reopen.
