### ISSUE TITLE
[Packaging Request] Shipwrite / Ocarina of Time

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#173119]
**Project description**
This is a PC Port of The Legend of Zelda: Ocarina of Time from the Nintendo 64.

**Metadata**

* homepage URL: https://github.com/HarbourMasters/Shipwright
* source URL: https://github.com/HarbourMasters/Shipwright
* license: (so far as I can tell) MIT except for Fast3D which seems to require not sharing compiled binaries.
More info: https://github.com/HarbourMasters/Shipwright/issues/31
* platforms: linux

**Comment by stapelberg** [comment]
Looks like @IvarWithoutBones and @PaulGrandperrin have already done some work on packaging shipwright: https://github.com/IvarWithoutBones/nixpkgs/pull/1

**Comment by majiru** [comment]
I have packaged this as part of an [overlay](https://git.sr.ht/~moody/gameover/), as the requirements to use the source rom make it impractical for inclusion into proper nixpkgs.

**Comment by IvarWithoutBones** [comment]
Hi! Apologies about the delayed response, this issue completely flew over my head. A shipwright derivation has been merged to nixpkgs ~2 months ago, see https://github.com/NixOS/nixpkgs/blob/02ea919a89de89569c036f9de11ff64ab91e8fc1/pkgs/games/shipwright/default.nix :)



> [...] the requirements to use the source rom make it impractical for inclusion into proper nixpkgs in my opinion.


I can understand this point of view, though I do think there is value in having an "official" derivation for the sake of discoverability and collaborative maintaince.

**Comment by majiru** [comment]
Thank you, I have no idea how I missed this being put in to nixpkgs proper!
