### ISSUE TITLE
xorgserver / modesetting DDX built without Glamor support

### ISSUE THREAD

**Issue by Shados** [NixOS/nixpkgs#17327]
Currently, xorgserver is built without `--enable-glamor` + `epoxy` as a dependency, which are needed to enable Glamor support in the in-built modesetting DDX. This is unfortunate, as modesetting with Glamor behaves better than the intel DDX on a decent proportion of Intel hardware.

I would submit a PR to fix this, but the Perl script used to generate `pkgs/servers/x11/xorg/default.nix` is pretty opaque to me.

**Comment by joachifm** [comment]
@vcunat may know more about this (but is possibly too busy to answer right now ...)

**Comment by vcunat** [comment]
@shados: no changes to the perl script or that generated file should be needed; the server is heavily overridden in `overrides.nix` already.

**Comment by vcunat** [comment]
Hmm, could it be why with my skylake I'm getting an unrecoverable black screen after resume, ~50% time? (Well, I can switch to text mode and restart X.)

**Comment by Shados** [comment]
@vcunat Probably not? The modesetting DDX may support the hardware better than the intel one, but I don't think the lack of Glamor support would actively cause bugs. Glamor just provides 2D hardware acceleration.

**Comment by gebner** [comment]
@Shados Did you get a chance to look at this?  Otherwise I will submit a PR later today.

**Comment by gebner** [comment]
The modesetting driver now has glamor support on the master branch.  The only issue I had was that scrolling became unbearably slow in chromium, but this was fixed by setting the "Override software rendering list" flag.
