### ISSUE TITLE
nixos/postgresql: some options aren't working

### ISSUE THREAD

**Issue by boogewooge** [NixOS/nixpkgs#173256]
### Describe the bug
The options `services.postgresql.authentication` and `services.postgresql.identMap` are without any effect for me on `nixos-unstable`.

(I suspect that `ensureUsers` isn't working correctly either, since when I use that for a system user without password, it complains about it not having a password, eventhough the option description suggests a password is not necessary. But maybe I misunderstand how this is supposed to work.)

### Steps To Reproduce
Use, on `nixos-unstable`, for example

```
services.postgresql = {
  enable = true;
  identMap = "test test test";
  authentication = "host test test 0.0.0.0/0 trust";
};
```

### Expected behavior
The files `/var/lib/postgresql/13/pg_ident.conf` and `/var/lib/postgresql/13/pg_hba.conf` should contain the above respective lines. But they aren't affected at all by the above configuration block.

### Notify maintainers

@thoughtpolice @danbst

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.36, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aanderse** [comment]
cc @talyz @Ma27

**Comment by talyz** [comment]
From what I can see in the module, the files you're looking at are not used. Instead, `postgres.conf` sets the paths to the files used. Can you check its contents?

**Comment by boogewooge** [comment]
You're right, `postgresql.conf` is in there and defines the files' paths. I should have read the module definition more carefully. =)

Sorry for the trouble.
