### ISSUE TITLE
Package request: Autopsy

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#173227]
**Project description**
Autopsy is a digital forensics platform and graphical interface to The Sleuth Kit and other digital forensics tools.

**Metadata**

* homepage URL: https://www.sleuthkit.org/autopsy/index.php
* source URL: https://github.com/sleuthkit/autopsy
* license: Apache 2.0
* platforms: Linux, macOS

**Comment by dotlambda** [comment]
related to https://github.com/NixOS/nixpkgs/issues/138724 and https://github.com/NixOS/nixpkgs/issues/81418

**Comment by realsnick** [comment]
https://github.com/juliosueiras-nix/nix-security
