### ISSUE TITLE
Geth service: extraArgs is broken

### ISSUE THREAD

**Issue by wanderer** [NixOS/nixpkgs#173236]
### Describe the bug
Specifying extraArgs for the geth service does not work since 
[escapeShellArgs](https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/nixos/modules/services/blockchain/ethereum/geth.nix#L172) adds single quotes to arguments which for some reason geth cannot handle.
### Steps To Reproduce
This service definition will not work
```
  services.geth.eth = {
    enable = true;
    extraArgs = [
        "--v5disc"
         "--light.serve 50"
      ];
  };
```
### Expected behavior
The above definition should work

### Notify maintainers
@ncfavier @bachp

**Comment by ncfavier** [comment]
`"--light.serve" "50"`
