### ISSUE TITLE
Slack crashes at start or intermittently - Wayland/XWayland

### ISSUE THREAD

**Issue by cptMikky** [NixOS/nixpkgs#173385]
### Describe the bug
Slack desktop application crashes randomly, usually after an incoming message with mention/notification.

### Steps To Reproduce
1. Start Slack
2. Use Slack
3. Random crash

### Expected behavior

Slack should not crash.

### Additional context

Running under Wayland/Sway. When Slack is started with native Wayland it crashes immediately in about 2/3 cases with a segfault. If it survives the start, it crashes later randomly (in minutes, even hours) *without* a segfault.

When forced to run under XWayland, it never crashes on startup but crashes later randomly as above also *without* a segfault or any other indication of a problem. There's just a json about the last received message.

### Notify maintainers 
@mmahut
@maxeaubrey

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2-xanmod1, NixOS, 22.05 (Quokka), 22.05pre378063.1d7db1b9e4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(user): `"home-manager, nixos"`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by iNecas** [comment]
It happens to me as well when clicking on `mako` notification from slack

**Comment by Abdillah** [comment]
if happened often you can start Slack from terminal and see the logs.
It will likely produce the error..

**Comment by iNecas** [comment]
```
[320241:0100/000000.788109:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[1]    320154 segmentation fault (core dumped)  slack
```

**Comment by iNecas** [comment]
I've started observing this after upgrading `nix: 2.8pre20220411_f7276bc → 2.8pre20220505_f4102de`, slack was not touched during the upgrade, but I see some relevant changes when doing `diff-closures` (no versions changes though):

```
mako: +27.5 KiB
wayland: +376.0 KiB
wayland-protocols: +472.6 KiB
```

**Comment by iNecas** [comment]
btw. tried updating slack to `4.26.1`, but that didn't do the trick, still seeing the issue

**Comment by cptMikky** [comment]
> if happened often you can start Slack from terminal and see the logs. It will likely produce the error..

Nope, just the segfault when present as described above.

**Comment by iNecas** [comment]
Looking at the core dump and digging a bit deeper led me to https://github.com/vector-im/element-web/issues/20926 and https://github.com/vector-im/element-web/issues/21996 and finally to https://gitlab.gnome.org/GNOME/libnotify/-/issues/25/.

I can see that libnotify got update on my system during last upgrade `libnotify: 0.7.9 → 0.7.11` so this is most likely the cause.

**Comment by iNecas** [comment]
Seems libnotify 0.7.12 should have the fix already (based on https://github.com/sumnerevans/home-manager-config/commit/159a2fdc154a8216739377cb65498e52c1a3fbd5), I will check if it helps later today.

**Comment by iNecas** [comment]
I can confirm updating libnotify to 0.7.12 fixes the issue for me.

**Comment by Artturin** [comment]
https://nixpk.gs/pr-tracker.html?pr=172287
