### ISSUE TITLE
Gnome Extension GSconnect does not show menu nor activates its daemon

### ISSUE THREAD

**Issue by crims0nHD** [NixOS/nixpkgs#173301]
### Describe the bug
After adding pkgs.gnomeExtensions.gsconnect to environment.systemPackages in /etc/nixos/configuration.nix and running sudo nixos-rebuild switch and restarting the computer, GSconnect will not activate its daemon (Gnome menu -> Mobile Devices -> stuck on "Enable"). Furthermore, it will refuse to launch the settings window when clicking on "Mobile Settings".

### Steps To Reproduce
0. On a NixOS unstable system with gnome installed
1. Add pkgs.gnomeExtensions.gsconnect to environment.systemPackages in /etc/nixos/configuration.nix
2. run sudo nixos-rebuild switch
3. reboot
4. login
5. click on Gnome menu -> Mobile Devices -> Enable

### Expected behavior
"Enable" should start the GSconnect service.
"Mobile Settings" should launch the settings window 

### Screenshots
![image](https://user-images.githubusercontent.com/49682210/168662678-c688c0f9-c43f-4b19-b8ca-4df94ab65336.png)
Note: Text in screenshot in german.

### Logs
journalctl -xe:
```
Mai 16 20:43:20 nixos dbus-daemon[1381]: [session uid=1000 pid=1381] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.11' (uid=1000 pid=1445 comm>
Mai 16 20:43:20 nixos dbus-daemon[5039]: writing oom_score_adj error: Permission denied
Mai 16 20:43:20 nixos daemon.js[5039]: JS ERROR: Error: Requiring Gdk, version 3.0: Typelib file for namespace 'Gdk', version '3.0' not found
                                       @/home/david/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:18:13
Mai 16 20:43:20 nixos daemon.js[5039]: Script /home/david/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js threw an exception
Mai 16 20:43:20 nixos dbus-daemon[1381]: [session uid=1000 pid=1381] Activated service 'org.gnome.Shell.Extensions.GSConnect' failed: Process org.gnome.Shell.Extensions.GSConne>
Mai 16 20:43:20 nixos .gnome-shell-wr[1445]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch bloc>
                                               start@/home/david/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/utils/remote.js:429:16
                                               _enable@/home/david/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/extension.js:154:30
                                               addAction/<@resource:///org/gnome/shell/ui/popupMenu.js:555:21
                                               activate@resource:///org/gnome/shell/ui/popupMenu.js:197:14
                                               vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:141:14
```

### Notify maintainers
@team.gnome.members (sorry but i did not find who that is)

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/hk2mydhxsxbw7xalwa4s0dyk0c6gmgkf-bash-interactive-5.1-p16-dev
copying path '/nix/store/hk2mydhxsxbw7xalwa4s0dyk0c6gmgkf-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.39, NixOS, 22.05 (Quokka), 22.05pre377845.43ff6cb1c02`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - channels(david): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by crims0nHD** [comment]
After installing "nix-env -i gjs" the settings window shows itself.

**Comment by jtojnar** [comment]
Looking at the path, `/home/david/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:18:13`, you seem to have installed the extension manually, rather than through NixOS.

**Comment by crims0nHD** [comment]
My apologies. Deleting the manually installed version did resolve the issue.

**Comment by giggio** [comment]
I'm also having this issue. I'm on home-manager. Adding `gjs` did not fix it. Can this extension run through home-manager?
