### ISSUE TITLE
packages using elk6Version have reached EOL

### ISSUE THREAD

**Issue by marsam** [NixOS/nixpkgs#173449]
### Describe the bug
Kibana6 has reached EOL on February 10, 2022 https://www.elastic.co/support/eol#kibana

### Steps To Reproduce
master branch as of 2022-05-17 (52dc75a4fee3fdbcb792cb6fba009876b912bfe0).

### Expected behavior
`kibana6` and `kibana6-oss` should be removed for the 22.05 release

### Notify maintainers

@offlinehacker @basvandijk

**Comment by mweinelt** [comment]
The maintainers have last touched kibana in 2019/05 and 2015/09. I think it's unrealistic that they will clean this up and someone else needs to do it.

**Comment by Artturin** [comment]
Removal done in https://github.com/NixOS/nixpkgs/pull/194420
