### ISSUE TITLE
Add booster initramfs generator package

### ISSUE THREAD

**Issue by anatol** [NixOS/nixpkgs#173437]
I see that you started working on a new initramfs generator here https://github.com/NixOS/nixpkgs/commit/d193ef8a57266938b00422144efc04d9dba4d3a9. I wonder if you are interested to look at my project called `booster` https://github.com/anatol/booster

Booster is a small and fast initramfs. It does not require external libraries (it is a static go binary) and generates a minimalistic image (no systemd, no even libc by default). It supports root filesystem encryption, clevis-type binding, remote unlocking, etc...

It is currently packaged at Arch, Void, Alpine Linuxes and tested at Fedora as well.

I am happy to answer your questions about the project.

**Metadata**

* homepage URL: https://github.com/anatol/booster/
* source URL: https://github.com/anatol/booster/
* license: MIT
* platforms: linux

**Comment by ElvishJerricco** [comment]
We are currently moving towards using systemd in initrd for NixOS, but if you would like to package `booster` in Nix for inclusion in nixpkgs, a PR would be welcome. In theory we could include a NixOS option for using `booster` instead in NixOS's initrd, but I don't expect we'll be able to maintain 3 different initrd infrastructures (the old shell script infra, the new systemd infra, and a new booster infra)

**Comment by anatol** [comment]
> In theory we could include a NixOS option for using booster instead in NixOS's initrd

If you provide some framework that allows integrating pluggable initrd then it should work. The framework should be able to call the initrd hooks on events like "kernel updated", "package updated". Many distros use this technique - Arch, Debian, Fedora, ...

> we'll be able to maintain 3 different initrd infrastructures

the framework itself needs to be created by nixos team. But it is relatively simple and stable codebase. I do not expect much effort to maintain this code.

As of `booster` maintenance itself - I'll be happy to do it for NixOS users the same way as I currently do for Arch/Void/Alpine users.
