### ISSUE TITLE
Bluetooth Plasmoid needs bluez-qt to be installed

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#17344]
The Bluetooth Plasmoid needs `bluez-qt` to be installed. The latter is installed automatically if Bluetooth is enabled on the system. We should move the Plasmoid to its own package which will also only be installed if Bluetooth is enabled.

See also #17235.

**Comment by peterhoeg** [comment]
I have ```hardware.bluetooth.enable = true;``` and bluedevil.nix adds bluez-qt to propagatedUserEnvPkgs, but I am getting the qml missing error unless I add bluez-qt to ```environment.systemPackages``` as well. I'll make a minimal working example over the weekend.

**Comment by ttuegel** [comment]
> I am getting the qml missing error unless I add bluez-qt to environment.systemPackages as well.

That's really weird; `bluedevil` propagates its `bluez-qt` dependency to the user environment...

**Comment by domenkozar** [comment]
Ping, will this be done until tomorrow? :)

**Comment by peterhoeg** [comment]
@ttuegel fixed it. At least it's working here.
