### ISSUE TITLE
It would be nice if fetchpatch had an "invert" parameter

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#17350]
It seems like you sometimes have an upstream patch that you want to apply backwards, and `fetchpatch` feels like a good place to do that.

**Comment by copumpkin** [comment]
Perhaps it makes more sense as a separate function that takes a path to a patch (like the one returned by `fetchpatch`) and returns another patch derivation.

**Comment by obadz** [comment]
:+1:

**Comment by Artturin** [comment]
fixed in 30585139410578e9cbf3091a3f930dcd22de1ebc
