### ISSUE TITLE
[feature request] add a function to generate hydra channels to releaseTools

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#17356]
Hydra got support for channels with nixos/hydra#211.

Generating channels is undocumented for the moment, but there is an example in https://github.com/openlab-aux/vuizvui/blob/master/release.nix#L103.

the [`mkChannel`](https://github.com/openlab-aux/vuizvui/blob/b74835bcb966af7956e33471a8d97e9c54d451bb/pkgs/build-support/channel.nix) function look useful, and having something similar in nixpkgs would help for custom hydra setups.

cc @aszlig

**Comment by domenkozar** [comment]
I've refactored it further a bit, see https://github.com/snabblab/snabblab-nixos/blob/customchannel/jobsets/snabblab.nix

**Comment by ericsagnes** [comment]
@domenkozar Great! do you think it is ready to go in nixpkgs or does it need some more work?

**Comment by ericsagnes** [comment]
closing this as PR is in review.
