### ISSUE TITLE
Deprecate lesstif: port motif to darwin and switch texlive to motif

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#17359]
Currently, TexLive is the last package to depend on lesstif.  Lesstif was abandoned circa 2012 (http://lesstif.sourceforge.net/ dates the last commit to May 27, 2009) when motif became available under lgpl. By contrast, motif just received an update and is available in nixpkgs (https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/motif/default.nix).

As such, if a Mac user could port the motif package to darwin, it would be possible to completely deprecate lesstif.

### How to fix:
1. ~~Try to compile motif on darwin with the demos. Resolve any issues.~~ (DONE; https://github.com/NixOS/nixpkgs/issues/17410)
2. ~~Disable demos.~~ (DONE; https://github.com/NixOS/nixpkgs/issues/17410)
3. ~~Try porting catclock (it should work as is since it's very minimal x11 and motif and upstream already tested it on mac).~~ (DONE; https://github.com/NixOS/nixpkgs/issues/17410)
4. Try switching TexLive to motif. (TODO;)

**Comment by knedlsepp** [comment]
I'm currently trying to compile motif on my 10.9 machine. It seems to compile fine with only small modifications. One of them would be:

```
--- a/lib/Xm/XmP.h
+++ b/lib/Xm/XmP.h
@@ -1437,7 +1437,7 @@ extern void _XmDestroyParentCallback(
 
 #endif /* NO_XM_1_2_BC */
 
-#if __GNUC__
+#if __GNUC__ && ! __APPLE__
 #  define XM_DEPRECATED  __attribute__((__deprecated__))
 #  define XM_ALIAS(sym)  __attribute__((__weak__,alias(#sym)))
 #else
```

This however clashes with your entire removal of the file XmP.h:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/motif/default.nix#L32
Is there any reason to remove the entire file?

**Comment by knedlsepp** [comment]
I'm currently compiling this on my 10.9 machine and it seems to compile fine with only minimal changes.

-  Removing the weak aliasing `XM_ALIAS`, which is not supported on darwin
- Including the correct header for `malloc` in the demo program `demos/programs/workspace/xrmLib.c`

Especially I didn't have to [remove `lib/Xm/Xm.h`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/motif/default.nix#L32) or patch the `bindings` file to make it work.

My changes are located here: https://github.com/knedlsepp/nixpkgs/commit/d148388679275f499338aa8e4dca3ec6d1159a76

I have only tested a few of the demos and they seem to work correctly.

**Comment by knedlsepp** [comment]
Oh. The patch to not compile the demos does not achieve its goal. Still compiles all the demos.

**Comment by RamKromberg** [comment]
@knedlsepp nice :) I'll comment on the changes but for the most part you just need to condition the changes for darwin only using ```if stdenv.isDarwin then``` and so on... Once that done it's ready for a PR :)

**Comment by knedlsepp** [comment]
Ok. I'll add the removal of `Xm.h` and the bindings-patch to my commit.

**Comment by RamKromberg** [comment]
@knedlsepp  thanks :) I  kept commenting a little further as well explaining some of the whats and whys...

Btw, it will probably be faster to push a PR and move the review over there. I don't have merge privileges so I suspect one of nixpkgs maintainers would want to weight in on the changes and make some of their own alterations.

**Comment by knedlsepp** [comment]
I have not used any texlive from nixpkgs up until now. It seems the `texLive` one a deprecated one and `texlive` is the new one. However there are still lots more.
Do you know which of all those different derivations we should use for testing the motif+texlive combo?

**Comment by RamKromberg** [comment]
It's not deprecated. texLive refers to texlive. Do the following:
1. _git grep lesstif_: Shows only _pkgs/tools/typesetting/tex/texlive-new/bin.nix_ _pkgs/tools/typesetting/tex/texlive/default.nix_ are left.
2. _git grep tools/typesetting/tex/texlive_: shows how texLive relates to texlive.

There's also texlive-new which represents the current texlive as opposed to the stable derivation. 

Regardless, at this point we actually shouldn't be doing it ourselves. Once your darwin motif PR gets committed, I'll PR the texlive maintainers and have them make the switch themselves.

**Comment by AndersonTorres** [comment]
But texLive is an old derivation, and texlive is a new infrastructure.

**Comment by RamKromberg** [comment]
@AndersonTorres see my previous comment. Also, run ```git grep texlive``` and ```git grep texLive```. They're both being used.

**Comment by AndersonTorres** [comment]
It doesn't imply texLive being "upstream-maintained".
But, anyway, it is another thing: texlive explicitly uses lesstif and not a "choose if you like motif".
The "change to motif" part is the easier one, I think.

**Comment by RamKromberg** [comment]
> The "change to motif" part is the easier one, I think.

I'm not sure which texlive package depends on motif. ```texlive-bin-2014.20140926.35254/texk/xdvik/LESSTIF-BUGS``` suggests to me we should at least try:
```
texlive.combine { inherit (texlive) scheme-full scheme-gust xdvi; }
texlive.combine { inherit (texlive) scheme-full scheme-gust seetexk; }
texlive.combine { inherit (texlive) scheme-full scheme-gust xetexko; }
texlive.combine { inherit (texlive) scheme-full scheme-gust luatexko; }
```
As https://nixos.org/wiki/TexLive_HOWTO explains. However, https://github.com/NixOS/nixpkgs/pull/17347 is probably holding us back on the first one.

Anyhow, even if I was sure this was all there is to it and that there's no need to get the texlive maintainers involved right up until PR time, I'd still prefer to at least wait until everything else is committed to master. Maybe even unstable...

Still, if you'd like, nothing is stopping you from running with this.

**Comment by RamKromberg** [comment]
cc texlive-new maintainers @vcunat @abbradar now that https://github.com/NixOS/nixpkgs/issues/17410 got through regarding switching lesstif -> motif. Also note https://github.com/NixOS/nixpkgs/pull/17347.

**Comment by RamKromberg** [comment]
The old texlive package can't be recompiled (mirror gone; missing tarballs. https://github.com/NixOS/nixpkgs/issues/10026#issuecomment-207384934). So, I'm trying to piggy back on the upgrade PR for texlive-new (https://github.com/NixOS/nixpkgs/issues/16391).

**Comment by vcunat** [comment]
Just note these are both about "texlive-new" (as typically used, by the directory name). The really old `texLive*` attributes are in https://github.com/nixos/nixpkgs/tree/master/pkgs/tools/typesetting/tex/texlive

**Comment by RamKromberg** [comment]
Thanks!
