### ISSUE TITLE
Package request for mermaid-filter

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#173666]
**Project description**

 a pandoc filter that adds support for mermaid syntax diagrams in markdown

**Metadata**

* homepage URL: https://github.com/raghur/mermaid-filter
* source URL:https://github.com/raghur/mermaid-filter
* license: ? unspecified
* platforms: node

**Comment by taranarmo** [comment]
Seems like the license is BSD 2-clause
https://github.com/raghur/mermaid-filter/blob/97f0bfb2498b70377365fcfd1a376baa2e1fe140/package.json#L16

**Comment by ppom0** [comment]
It has been added on june, it's available on NixOS 23.11!
https://github.com/NixOS/nixpkgs/pull/236667
