### ISSUE TITLE
Cups-Pdf

### ISSUE THREAD

**Issue by nrdsp** [NixOS/nixpkgs#173745]
**Cups-Pdf**
Adds a local CUDS-PDF virtual printer to Cups with the ability to print directly to PDF. 

**Metadata**

* homepage URL: https://www.cups-pdf.de/
* source URL: https://www.cups-pdf.de/download.shtml
* license: gpl 
* platforms: unix, linux, darwin

**Comment by Yarny0** [comment]
Hi, I prepared a similar package, "cups-pdf-to-pdf" for nixpkgs: https://github.com/NixOS/nixpkgs/pull/182360  Maybe you can have a look and give it a review, if you have time.

**Comment by Yarny0** [comment]
Given https://github.com/NixOS/nixpkgs/pull/182360 got [merged into master](https://github.com/NixOS/nixpkgs/pull/182360#event-8119601716), can the issue at hand be closed?
