### ISSUE TITLE
error: attribute ‘phonon-backend-gstreamer’ missing

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#17374]
## Issue description

```nixos-rebuild``` fails with
```error: attribute ‘phonon-backend-gstreamer’ missing, at /home/peter/src/active/nixpkgs_unstable/nixos/modules/services/x11/desktop-managers/kde5.nix:151:9```

Removing that line makes it work.

Cc: @ttuegel 

### Steps to reproduce

Minimal configuration that triggers the issue:

```
{ pkgs, ... }:

{
  nix.useSandbox = true;

  services.xserver = {
    enable = true;
    displayManager.sddm.enable = true;
    desktopManager.kde5.enable = true;
  };
}
```

## Technical details

* NixOS: 16.09.git.0a4bdbfM (Flounder)
* Nix: nix-env (Nix) 1.11.2
* nixpkgs: 16.09pre86979.d458029

**Comment by ttuegel** [comment]
This was fixed in 3dea00d90ef000a41652a6b629c76fffce3727c7.
