### ISSUE TITLE
Order of link flags for rust seems significant now

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#173711]
### Describe the bug
Rust 1.61 and rust builder in nixpkgs don't play nicely together anymore.

See first point of https://github.com/rust-lang/rust/blob/fe5b13d681f25ee6474be29d748c65adcd91f69e/RELEASES.md#compatibility-notes, linking to https://github.com/rust-lang/rust/pull/93901/

### Steps To Reproduce
I don't have a small/public repro on hand right now. If someone has one, please contribute. If not, I can try to come up with one on Monday. Might be easy to get one out of rust issue tracker as they seem to be getting flooded with linker tickets today due to the change.

### Expected behavior
Programs build and link but instead we get linker errors.

### Notify maintainers
(edit by artturin)
@andir @LnL7 @Mic92 @zowoq

### Metadata
nixpkgs `55fad6c081850b3e1d93f87a72c14a383a8e1e9d`, rest not that relevant? I'm using oxalica's rust-overlay to get Rust 1.61.

**Comment by Fuuzetsu** [comment]
I updated to Rust 1.62 and recent nixpkgs and issue seems to be gone somehow. Maybe by luck or maybe https://github.com/rust-lang/rust/pull/96436/ had something to do with it?

**Comment by duxovni** [comment]
Was this fixed by #177436 ? That seemed to solve all of my nix rust building issues.

**Comment by Fuuzetsu** [comment]
@duxovni aha, yes, I think this is exactly it. I was surprised to find that `-l` flags were missing from the output when trying with recent nixpkgs and Rust 1.62 because their wrong order was the cause of an error to start with. I will close the ticket, thank you for the link.
