### ISSUE TITLE
deja-dup: Deja Dup's Google support will break in September 2022 for versions < 43.3

### ISSUE THREAD

**Issue by mikix** [NixOS/nixpkgs#173780]
Hello! I'm the upstream maintainer of Deja Dup. Google will be removing a particular oauth workflow that Deja Dup uses in September.

This means that any new authentications for users trying to connect Deja Dup to their Google account will fail after that date (existing users that have already authenticated themselves will continue to work).

If possible, updating to 43.3 will fix this. But for older releases (Nix 21.05 and 21.11 are on 42.7 at time of writing, I believe), I recommend a backported patch.

Here's a wiki page for more information about the issue, including backported patches for older versions: https://wiki.gnome.org/Apps/DejaDup/GoogleAuthChange2022

**Comment by jtojnar** [comment]
Thanks for the info. Sorry it took so long, I opened https://github.com/NixOS/nixpkgs/pull/176489 now and the update will be backported to 22.05 (21.05 is already EOL and 21.11 should be EOL next month) .
