### ISSUE TITLE
Current nixos livedvd fails at stage 1 boot

### ISSUE THREAD

**Issue by Raahul-Kumar** [NixOS/nixpkgs#1737]
I downloaded the current nixos dvd. 

http://releases.nixos.org/nixos/unstable/nixos-14.02pre39344.42c083d/

It fails to get past stage 1 boot. There is a fatal modprobe error "Scsi-wait-scan not found".

The hardware is an AMD FX-8350 Eight-Core system with a Gigabyte 990FXA-UD3 motherboard and a MSI r7850  video card. I have successfully installed Ubuntu 13.10 on this hardware, so linux does in fact work with this hardware.

**Comment by Profpatsch** [comment]
Okay, this is out of date. Close @jagajaga
