### ISSUE TITLE
Gqrx core dumps when saving settings.

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#173848]
### Describe the bug
`(gqrx:11034): GLib-GIO-ERROR **: 10:19:00.592: No GSettings schemas are installed on the system`
`zsh: trace trap (core dumped)  gqrx`

### Steps To Reproduce
1. Open gqrx
2. Configure the I/O device
3. Click the save icon

### Expected behavior
It should save the current configuration

### Notify maintainers
 @bjornfor @fpletz 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.2-xanmod1, NixOS, 22.05 (Quokka), 22.05pre376824.41ff747f882`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
I think it needs a similar patch as this: 61afa3e16b1e7c0cafe9dbce8cbc7b919f1a1a6b.
