### ISSUE TITLE
error: attribute 'kernelAtLeast' missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#173832]
### Describe the bug

When i try to rebuild my mobile nixos on the pinephone from latest unstable channel i get this error.

```
...
error: attribute 'kernelAtLeast' missing

       at /nix/store/9qk04qfc1vxa59h5ncdgyfch16bbbbyp-nixos/nixos/pkgs/top-level/linux-kernels.nix:249:42:

          248|   packagesFor = kernel_: lib.makeExtensible (self: with self;
          249|     let callPackage = newScope self; in {
             |                                          ^
          250|     inherit callPackage;
(use '--show-trace' to show detailed location information)
```

This issues is not present at 17c252aab1772d36acd6d3f57f6512f25b6f9e9c.

### Steps To Reproduce
1. boot Pinephone from image https://davidak.de/tmp/gs6kzw3vhpdwkrmzk6wxd68fhap6hsdr-pine64-pinephone_full-disk-image.img
2. create config
3. nixos-rebuild

### Expected behavior

no errors

### Metadata
 - system: `"aarch64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05.git.9e47e609715`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by adisbladis** [comment]
Bisected this to 8aa8e0ce7f137fe329608efcbb3494a5e6a63f42.

**Comment by adisbladis** [comment]
I think this is better fixed in mobile-nixos.
