### ISSUE TITLE
qgroundcontrol: "No text-to-speech plug-ins were found."

### ISSUE THREAD

**Issue by TilCreator** [NixOS/nixpkgs#173872]
### Describe the bug
Qgroundcontrol is not able to find a TTS plugin, so the TTS feature doesn't work.

### Steps To Reproduce
1. install `qgroundcontrol` from NixOS/nixpkgs/a7ecde854aee5c4c7cd6177f54a99d2c1ff28a31 (probably also from stable and unstable)
2. start `$ QGroundControl`
3. notice "No text-to-speech plug-ins were found." and the missing speech output

### Expected behavior
I would expect that Qgroundcontrol can find a usable TTS module.

### Additional context
I already tried adding speechd and espeak to the `buildInputs` of `qgroundcontrol`, but that didn't fix anything. Also the `spd-say` command from `speechd` works fine.

### Notify maintainers
@lopsided98 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.114, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.337558.2d474d6a4a4"`
 - channels(tilcreator): `"nixos-21.11, nixos-21.11-21.11, nixos-21.11-small-21.11-small, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lopsided98** [comment]
This is an issue with qtspeech, see: https://github.com/NixOS/nixpkgs/pull/173941
