### ISSUE TITLE
Xfce: dragging .desktop entries from applications menu to desktop results in "Untrusted application launcher" error

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#17399]
## Issue description

Xfce (and other DEs) require user’s custom launchers to have `execute` bit set, e.g. with `chmod +x blah.desktop`.

It also doesn’t allow to run symlinks in `~/Desktop/` that point to real `.desktop` files in `/nix/store/`.

Dragging a launcher from Xfce applications menu and dropping it onto the desktop will result in such a symlink. Double clicking the symlink displays “Untrusted Application Launcher” error, instead of running it.

Another related problem is: the dropped symlink points to `/nix/store/$hash-$app/share/applications/$app.desktop` and therefore the link will break after upgrade. It should really point to `/run/current-system/sw/share/applications/$app.desktop`.
### Steps to reproduce
1. Install Xfce.
2. Open applications menu.
3. Drag any application from there and drop it on the desktop.
4. Try to run (double-click) the dropped icon.
## Technical details
- System: 16.03.1162.1425a1f (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.03.1162.1425a1f"

**Comment by yegortimoshenko** [comment]
I can't reproduce this issue:

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.5, NixOS, 18.03.git.ab1d2a5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"overlay, nixos-18.03pre122666.afe9649210c"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

I've tried drag and dropping Mousepad to desktop and then running it, and it works. This issue has been opened a while ago, is this still a problem in 17.09 or unstable?

**Comment by samueldr** [comment]
I presume that since it couldn't be reproduced back in 2017, this issue can be closed.

If anyone experiences something that *looks* like this, please open a fresh new issue detailing your exact situation. Feel free to cross-reference this issue if you think this is relevant.
