### ISSUE TITLE
locate: `/var/cache/locatedb': No such file or directory

### ISSUE THREAD

**Issue by basilevs** [NixOS/nixpkgs#17397]
## Issue description

Locate command is unable to access file database. Updatedb fails to update it.
### Steps to reproduce
- Deploy demo VM from https://nixos.org/releases/nixos/latest-ova-x86_64-linux
- Login as demo user
- elevate to root: `sudo -i`
- run `updatedb`
- run `locate etc`
### Expected

Many files from /etc/ folder are found
### Actual

Locate responds:
`locate:`/var/cache/locatedb': No such file or directory`
### Session log:

```
[demo@nixos:~]$ sudo -i
[sudo] password for demo: 

[root@nixos:~]# updatedb
/run/current-system/sw/bin/updatedb: line 278: /nix/store/l65knk24c08q0lwdcf0yyh7x6l5shhqj-findutils-4.4.2/var/locatedb.n: Read-only file system
Failed to generate /nix/store/l65knk24c08q0lwdcf0yyh7x6l5shhqj-findutils-4.4.2/var/locatedb.n

[root@nixos:~]# locate etc
locate: `/var/cache/locatedb': No such file or directory

[root@nixos:~]# ls /etc/
bashrc            issue           NIXOS          resolv.conf      subgid
dbus-1            locale.conf     nsswitch.conf  resolvconf.conf  subuid
default           localtime       os-release     rpc              sudoers
dhcpcd.duid       login.defs      pam.d          samba            sysctl.d
dhcpcd.exit-hook  machine-id      passwd         services         systemd
fonts             modprobe.d      pki            shadow           tmpfiles.d
fstab             modules-load.d  polkit-1       shells           udev
group             mtab            profile        ssh              vconsole.conf
hosts             nix             protocols      ssl              X11
inputrc           nixos           pulse          static           zoneinfo
```
## Technical details
- System: 16.0.3.1162.1425a1f (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version:  16.0.3.1162.1425a1f

**Comment by cleverca22** [comment]
you need to enable services.locate.enable and then wait until systemd updates it

**Comment by basilevs** [comment]
If a command is visible in PATH, should not it have a proper environment when run?

**Comment by danbst** [comment]
Probably we have to update `findutils` to change default path for locatedb:
```
    findutils = super.findutils.overrideDerivation (sup:{
      configureFlags = [ "--localstatedir=/var/cache" ];
    });
```
But one more patch to `updatedb` is required - `mkdir -p /var/cache` before any operations on DB file.

**Comment by danbst** [comment]
Highly relevant https://github.com/NixOS/nixpkgs/pull/23152, https://github.com/NixOS/nixpkgs/issues/24250
Should this be closed as resolved?

**Comment by stefano-m** [comment]
@danbst I would not close this yet since `updatedb` still needs `/var/cache` to be present (that's the issue that landed me here).

I am using
```
$ nixos-version
17.03.1395.9b948ea439 (Gorilla)
$ nix-env --version
nix-env (Nix) 1.11.11
```
and had to create `/var/cache` manually to make `updatedb` happy.

**Comment by danbst** [comment]
@stefano-m you're right, a patch to updatedb is still required, but this isn't now nixpkgs/nixos fault

**Comment by stefano-m** [comment]
Wouldn't it be possible to have some hook in nixpkgs that ensures that the directory is created when `findutils` is installed?

(Disclaimer: I'm pretty new to the nix ecosystem)

**Comment by danbst** [comment]
No, it's a feature of Nix, that installing a package (via `nix-env -i` or `environment.systemPackages`) won't mess with FS other that in /nix/store and nix profile dir.

You may ask for setup hooks on Nix issue tracker though...

**Comment by calbrecht** [comment]
A possible solution could be to wrap updatedb like it is done in pkgs/development/libraries/accountsservice/default.nix
```
preFixup = ''
    wrapProgram "$out/bin/updatedb" \
      --run "${coreutils}/bin/mkdir -p /var/cache"
'';
```

**Comment by stefano-m** [comment]
@danbst this is just to report that with 

```
nixos-version
17.09.2683.360089b3521 (Hummingbird)
```

the issue does not present itself any longer: `/var/cache/locatedb` is created the first time that `update-locatedb.service` is run.

It may be time to close this issue and #14132 too?
