### ISSUE TITLE
AdGuardHome settings should have a schema_version

### ISSUE THREAD

**Issue by rickhull** [NixOS/nixpkgs#173938]
See https://github.com/NixOS/nixpkgs/blob/634141959076a8ab69ca2cca0f266852256d79ee/nixos/modules/services/networking/adguardhome.nix#L64

The package is configured via `settings`, which corresponds to `/var/lib/AdGuardHome/AdGuardHome.yaml` on the filesystem.  There have been some schema changes to this yaml file, and while explicit versioning may not have been necessary earlier, it appears to be necessary now.  The user is able to set `schema_version = 12;` (corresponding to the version of the package), but I think the package should do this by default.

If the user attempts to populate `settings` using the latest schema, but without setting `schema_version = 12;`, **the build will fail**, as the supplied configuration will be brought from schema version 0 up to schema version 12, and the latest schema will fail config checks against, say, schema version 0.

### Steps To Reproduce

```
  services.adguardhome = {
    enable = true;

    # just the http(s) admin interface
    port = 3000;
    openFirewall = true;

    # corresponds to /var/lib/AdGuardHome/AdGuardHome.yaml
    settings = {
      # schema_version = 12;
      dns = {
        bind_hosts = ["0.0.0.0"];

        # query logging
        querylog_enabled = true;
        querylog_file_enabled = true;
        querylog_interval = "24h";
        querylog_size_memory = 1000;   # entries
        anonymize_client_ip = false;   # for now

        # adguard
        protection_enabled = true;
        blocking_mode = "default";     # NXDOMAIN
        filtering_enabled = true;

        # upstream DNS
        upstream_dns = [
          "8.8.8.8"     # google
          "8.8.8.4"     # google
        ];
        # if upstream has any hostnames
        bootstrap_dns = ["192.168.1.1"];  # ask the gateway

        # caching
        cache_size = 536870912;  # 512 MB
        cache_ttl_min = 1800;    # 30 min
        cache_optimistic = true; # return stale and then refresh
      };
```
`nixos-rebuild switch`

ACTUAL RESULT: build fails, --check-config fails against early schema versions

EXPECTED RESULT: build succeeds, --check-config passes

@CRTified
@lunik1
@aanderse 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.39, NixOS, 22.05 (Quokka), 22.05pre377845.43ff6cb1c02`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos-22.05pre377845.43ff6cb1c02"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by CRTified** [comment]
That's a problem. Thanks for bringing it up.

I need to think about how to fix this, especially in combination with `mutableSettings = true`.
One option would be to automatically set the highest `schema_version`, but that might break backwards compability somewhat often :thinking: Alternatively, we could drop the [`checkPhase`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/adguardhome.nix#L23) and hope for the user to keep it manually in a sane state.

Alternatively, we could force the user to set the schema version by an assertion. That would break the least things and keep the nix-config compatible to future releases.

What do you think about these approaches? Feedback would be great at this point.

**Comment by rickhull** [comment]
> Alternatively, we could force the user to set the schema version by an assertion. That would break the least things and keep the nix-config compatible to future releases.

This has immediate appeal.  But this would lead to a lot of breakage for those who don't have it set yet have a working schema.  In this case, it would probably break less people to default to `schema_version = 12`, perhaps with a big warning when the default is taken.  Just thinking out loud...

**Comment by mario-kr** [comment]
Hi,

This is probably also the cause for the checkPhase removing the original `bind_hosts` list?

I made an example yaml, and let the checkPhase command ron through it, here's the diff:
```
bind_host: 1.0.0.0                                              bind_host: 1.0.0.0
bind_port: 3000                                                 bind_port: 3000
dns:                                                            dns:
                                                              >   bind_host: 1.2.3.4
  bind_hosts:                                                     bind_hosts:
  - 1.2.3.4                                                   |   - 5.6.7.8
  bootstrap_dns:                                              |   - 10.11.12.13
  - 8.8.8.8                                                   |   bootstrap_dns: 8.8.8.8
  port: 53                                                        port: 53
  querylog_interval: 2160h                                    |
os:                                                           <
  group: ""                                                   <
  rlimit_nofile: 0                                            <
  user: ""                                                    <
schema_version: 12                                            <
```

My immediate asumption would be, that an older schema-check removes `bind_hosts` completely, and a newer one renames or moves the value of `bind_host` into `bind_hosts`

**Comment by CRTified** [comment]
@mario-kr Yes, that is possible. You could verify that by setting an appropriate `schema_version` in the original version and try again.

**Comment by CRTified** [comment]
@rickhull 
>  But this would break those who don't have it set yet have a working schema right now. In this case, it would probably break less people to default to schema_version = X,

The more I think about it the more I like this approach. At the moment, we're implicitly defaulting to `schema_version = 0` (as apparent by the `checkPhase` steps). So defaulting to this and then issuing a warning if it's unset would not break any existing setup while making it obvious *why* newer options may fail (as shown by @mario-kr ).

Alternatively, we could throw an error if it's unset. In there, we could state that `schema_version = 0` is sufficient if no newer options are used, but we'd recommend to use a newer one. Explicitly checking and maintaining the `schema_version` default (to keep it at the newest one) might be too much of a maintenance burden.

**Comment by aanderse** [comment]
Pardon my ignorance but what is the problem with just setting the schema to the corresponding package version? Add `passthru.schema_version = latest supported by this version of the software;` and then `services.adguardhome.settings.schema_version = cfg.package.schema_version or 0;`, etc...?

**Comment by CRTified** [comment]
@aanderse That would work, but it would require manual maintenance to keep that in sync - which in turn requires either inspection of the source code, or creating a config and extracting that value.

This is what I meant with
> Explicitly checking and maintaining the schema_version default (to keep it at the newest one) might be too much of a maintenance burden.

Maybe there is a way to solve this in an automated fashion - that would be the best case.

At this point, I'd also assume that some people use the module in its current state - implicitly using a `schema_version` 0. Defaulting to that and/or adding an error/warning would keep these configs working without much intervention. Maybe I'm a bit too anxious to break old configs at this point.

**Comment by CRTified** [comment]
I found a way to incorporate it in the `update.sh`. Will open a PR soon.
