### ISSUE TITLE
moonlight-qt tends to crash on startup after updates

### ISSUE THREAD

**Issue by ChrisOboe** [NixOS/nixpkgs#174019]
### Describe the bug
Often after updates moonlight-qt segfauls on startup. 

After deleting ```~/.cache/Moonlight Game Streaming Project``` it works again. 

### Steps To Reproduce
1. run moonlight-qt
2. update the system (e.g go from 21.11 to unstable)
3. try to run moonlight-qt again and see it segfault

### Expected behavior
Moonlight-qt should start without segfaulting

### Additional context
My guess would be it's related to the  ```~/.cache/Moonlight Game Streaming Project/qmlcache``` folder.
This seems to contain compiled qml files. Maybe these get incompatible when qt gets updated?

A possible solution could be, to add a small code to the moonlight wrapper script, that deletes the ```~/.cache/Moonlight Game Streaming Project/qmlcache/*.qmlc``` files when moonlight gets updated.

According to the moonlight-qt source the qmlcache depends on the qt runtime:
https://github.com/moonlight-stream/moonlight-qt/blob/48bcb6b9a681b140544a0cd63fb25e2c34bd8802/app/app.pro

Another (propably more elegant?) solution could be to apply a patch to the linked project file, that the qmlc files are generated during build time for linux too, so they wouldn't be generated on runtime anymore.

### Notify maintainers

@luc65r

**Comment by SuperSandro2000** [comment]
Should be fixed with #197010

**Comment by kajdo** [comment]
Hi,

I think i face the same issue - just did an update on my linux box and moonlight causes a coredump

is there any workaround until the update fixes the issue?
