### ISSUE TITLE
stdenv.hostPlatform.linker == "gold" does nothing

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#174126]
We allow setting `linker = "gold"` in `crossSystem`, but it currently does nothing because it will pick `binutils` as `bintools`, but the derivation itself will ignore that it's supposed to use gold by default.

cc @Ericson2314

**Comment by Artturin** [comment]
maybe helps https://github.com/NixOS/nixpkgs/pull/239247
