### ISSUE TITLE
Add Jailer - Database Subsetting and Relational Data Browsing Tool. 

### ISSUE THREAD

**Issue by aszenz** [NixOS/nixpkgs#174120]
**Project description**
Jailer is a tool for database subsetting and relational data browsing.

**Metadata**

* homepage URL: https://wisser.github.io/Jailer/
* source URL: https://github.com/Wisser/Jailer
* license: apache2
* platforms: unix, linux, windows, ...

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/311371
