### ISSUE TITLE
Packaging request: selectdefaultapplication

### ISSUE THREAD

**Issue by pbsds** [NixOS/nixpkgs#174133]
**Project description**

![](https://github.com/sandsmark/selectdefaultapplication/raw/master/screenshot.png)
Selectdefaultapplication is a very simple GUI application that lets you define default applications on Linux in a sane way.
Basically it just loads all installed applications by reading their .desktop files, reads the MimeType fields to see what it supports, and updates ~/.config/mimeapps.list with what the user wants.
Not all desktop environments provide such a tool, prompting for an agnostic tool.

**Metadata**

* homepage URL: https://github.com/sandsmark/selectdefaultapplication
* source URL: https://github.com/sandsmark/selectdefaultapplication
* license: gpl2
* platforms: linux

**Additional info:**
AUR package: https://aur.archlinux.org/packages/selectdefaultapplication-git

**Comment by S-NA** [comment]
You can try using this in an overlay, use `self.libsForQt5.callPackage`.
```nix
{ lib, mkDerivation, fetchFromGitHub, qmake, qtbase }:

mkDerivation rec {
  pname = "selectdefaultapplication";
  version = "unstable-2021-08-12";

  src = fetchFromGitHub {
    owner  = "sandsmark";
    repo   = "selectdefaultapplication";
    rev    = "c752df6ba8caceeef54bcf6527f1bccc2ca8202a";
    hash   = "sha256-C/70xpt6RoQNIlAjSJhOCyheolK4Xp6RiSZmeqMP4fw=";
  };

  nativeBuildInputs = [ qmake ];

  buildInputs = [ qtbase ];

  installPhase = ''
    mkdir -p $out/bin
    mv ./selectdefaultapplication $out/bin
  '';

  meta = with lib; {
    homepage = "https://github.com/sandsmark/selectdefaultapplication";
    description = "an ugly hack to be able to select default applications in linux in a better way";
    license = licenses.gpl2;
    platforms = platforms.linux;
  };
}
```

**Comment by pbsds** [comment]
Seems to work!
