### ISSUE TITLE
Using allRefs results in a SEGV

### ISSUE THREAD

**Issue by Cobaltarena** [NixOS/nixpkgs#174174]
### Describe the bug
Using `allRefs` results in a SEGV when trying to build the package.

### Steps To Reproduce
```
{
  description = "Test";

  inputs = {
    nixpkgs = {
      type = "github";
      owner = "NixOs";
      repo = "nixpkgs";
      ref = "nixos-unstable";
    };

    futils = {
      type = "github";
      owner = "numtide";
      repo = "flake-utils";
      ref = "master";
    };
  };
  outputs = { self, nixpkgs, futils }:
    let
      inherit (nixpkgs) lib;

      inherit (lib) attrValues recursiveUpdate optional;
      inherit (futils.lib) eachSystem;
      anySystemOutputs = { };

      systems = [ "x86_64-linux" ];

      multiSystemOutputs = eachSystem systems (system: rec {
        pkgs = import nixpkgs { inherit system; };

        test = pkgs.python3Packages.buildPythonPackage rec {
          pname = "test";
          version = "v1.0";

          src = fetchGit {
            url = "https://github.com/BillMills/python-package-example";
            allRefs = true;
            rev = "4343ff0a1d432d9c6963f42027585acf302d4bed";
          };
        };
        packages = { inherit test; };
        devShell = pkgs.mkShell {

          buildInputs = with pkgs; [
            test
          ];
        };

      });
    in
      recursiveUpdate multiSystemOutputs anySystemOutputs;
}
```
1. `nix develop` or `nix build .#test` 

### Expected behavior
No SEGV but crash on missing dependencies

### Additional context
It appeared right after updating my system on unstable and is still there after a clean install. This bug does not seem to occur on non-Nixos users.

Not specifying both `ref` and `allRefs` also produce this behaviour

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.117, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220512_d354fc3`
 - channels(user): `"nixpkgs-21.11.337635.cbd40c72b26"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`
```

**Comment by Mindavi** [comment]
cc @edolstra @thufschmitt maybe belongs in nixos/nix. Sounds like it may be hard to reproduce though :/.

**Comment by thufschmitt** [comment]
> cc @edolstra @thufschmitt maybe belongs in nixos/nix

It probably does, indeed (but I don’t have the right to move it).

I can’t reproduce it however, might be linked to some (inconsistent?) state in ~/.cache/nix

**Comment by Cobaltarena** [comment]
> It probably does, indeed (but I don’t have the right to move it).

My bad, I'll open it there if you think this is not the appropriate repository. 

> I can’t reproduce it however, might be linked to some (inconsistent?) state in ~/.cache/nix
 
 It is still happening on my side even after deleting ~/.cache/nix.

**Comment by Mindavi** [comment]
I suggest you open an issue on nixos/nix. Think we cannot really fix it here
