### ISSUE TITLE
Elm 0.17.1 doesn't build

### ISSUE THREAD

**Issue by bburdette** [NixOS/nixpkgs#17424]
## Issue description

I'm on unstable.  When doing nix-env --upgrade, the Elm compile fails, leaving me with the previous version.  The specific error:

```
[75 of 88] Compiling Elm.Docs         ( src/Elm/Docs.hs, dist/build/Elm/Docs.o )

src/Elm/Docs.hs:102:25: error:
    • No instance for (Num Json.Indent) arising from the literal ‘2’
    • In the ‘confIndent’ field of a record
      In the expression:
        Json.Config
          {Json.confIndent = 2, Json.confCompare = Json.keyOrder keys}
      In an equation for ‘config’:
          config
            = Json.Config
                {Json.confIndent = 2, Json.confCompare = Json.keyOrder keys}
            where
                keys = ["tag", ....]
builder for ‘/nix/store/irjap10vl1idnkk0flmxjncj1nlqnagq-elm-compiler-0.17.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/v7w2l6vjngs67z9pxmnnd91z368bw309-elm-0.17.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/v7w2l6vjngs67z9pxmnnd91z368bw309-elm-0.17.1.drv’ failed
```

### Steps to reproduce

Have elm installed, execute nix-env --upgrade.  Or presumably not have elm installed, be on unstable, and install it.  

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.09pre87733.dbd856d (Flounder)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"16.09pre87733.dbd856d"

**Comment by bradediger** [comment]
Related to https://github.com/elm-lang/elm-compiler/pull/1431. elm 0.17.1 is broken against aeson-pretty 0.8.

Bulids for me locally by locking the upstream `aeson-pretty` dependency to `aeson-pretty_0_7_2` within both elm-package and elm-compiler; however I'm not submitting a PR for that as this was fixed upstream and we're just waiting for a new elm release to drop.

**Comment by bradediger** [comment]
Because my teachers always asked me to show my work, here is my patch... it's just a temporary solution until upstream cuts a new release.

https://gist.github.com/bradediger/f0b478259b3c494b9cbf08ad19446bfc

**Comment by despairblue** [comment]
@bradediger  when applying your patch I get `error: undefined variable ‘aeson-pretty_0_7_2’ at /home/despairblue/git/nixpkgs/pkgs/development/compilers/elm/packages/elm-package.nix:25:11` 

Do I need to declare that specific version somewhere else as well?

**Comment by despairblue** [comment]
Nevermind, working now :confused:

**Comment by domenkozar** [comment]
Could someone open a PR?

**Comment by bradediger** [comment]
@domenkozar: #17511. Thanks!
