### ISSUE TITLE
cagebreak wayland compositor failed to launch

### ISSUE THREAD

**Issue by apluos** [NixOS/nixpkgs#174201]
### Describe the bug
Running cagebreak(wayland compositor from the terminal results in error messages)

### Steps To Reproduce
1. nix-env -iA nixpkgs.cagebreak
2. reboot
3. cagebreak

### Expected behavior
launch/start a wayland session

### Screenshots
`MESA-LOADER: failed to open crocus: /run/opengl-driver/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix_dri)`

`failed to load driver: crocus`

`MESA-LOADER: failed to open kms_swrast: /run/opengl-driver/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix_dri)`

`failed to load driver: kms_swrast`

`MESA-LOADER: failed to open swrast: /run/opengl-driver/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/dri, suffix_dri)`

`failed to load swrast driver`

`00:00:00:008 [backend/drm/renderer.c:29] Failed to create GBM device`

`00:00:00:008 [backend/drm/backend.c:237] Failed to create initialize renderer`

`00:00:00:023 [backend/backend.c:230] Failed to create DRM backend`

`00:00:00:023 [backend/backend.c:371] Failed to open any DRM device`

`00:00:00:078 [../cagebreak.c:323] Unable to create the wlroots backend`

### Additional context
installed nix from alpinelinux edge repositories, using on alpinelinux 

### Notify maintainers
<<[nicolas@normie.dev](mailto:nicolas@normie.dev)>>

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
error: file `nixpkgs` was not foun din the Nix package search path (add it using $NIX_PATH or -I), at (string):1:13
```

**Comment by Artturin** [comment]
You need to use https://github.com/guibou/nixGL for opengl on non-nixos
