### ISSUE TITLE
packaging request: swaynag-battery

### ISSUE THREAD

**Issue by asbachb** [NixOS/nixpkgs#174264]
**Project description**
Shows a message on top of all displays (using [swaynag](https://github.com/swaywm/sway/tree/master/swaynag)) when battery is discharging and bellow an appointed threshold. Also, closes the message when a power supply is plugged in.

**Metadata**

* homepage URL: https://github.com/m00qek/swaynag-battery
* source URL: https://github.com/m00qek/swaynag-battery.git
* license: mit
* platforms: linux

**Comment by teto** [comment]
packaged in https://github.com/NixOS/nixpkgs/pull/175905
