### ISSUE TITLE
Super+/ is broken in pop-shell, because the pop-launcher is missing from our package

### ISSUE THREAD

**Issue by lf-** [NixOS/nixpkgs#174353]
### Describe the bug

When I bring up the pop-shell (gnome extension) launcher with the key `Super+/`, it tries to exec `pop-launcher`, which does not exist. `nix-locate pop-launcher` turns up nothing, so it seems like NixOS is not packaging it properly somehow. This executable being missing makes the launcher not do anything when you type into it.

```
May 24 17:02:01 chonkpad .gnome-shell-wr[2017]: pop-shell: [DEBUG] starting pop-launcher service
May 24 17:02:01 chonkpad .gnome-shell-wr[2017]: pop-shell: [ERROR] failed to spawn pop-launcher: GLib.SpawnError: Failed to execute child process “pop-launcher” (No such file or directory)
```

### Steps To Reproduce
1. add `gnomeExtensions.pop-shell` to `environment.systemPackages` of a GNOME system
2. enable it in "Extensions" app
3. log out+log back in
4. hit `Super+/`

### Expected behavior

The launcher should do something.

### Notify maintainers

@genofire 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

nixpkgs rev 41ff747f882914c1f8c233207ce280ac9d0c867f

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/nix/store/4hwpsjcdsrvxjibhys9n326agch5a4rd-nixpkgs-src`

```

**Comment by genofire** [comment]
I am sorry, but the pop-launcher is not packaged (and will not by me - for me pop-shell is enougth).
So i am just fixing pop-shell related issues.


But you could package pop-launcher for nixos.
Here is an old PR as a good start point:
https://github.com/NixOS/nixpkgs/pull/144411

**Comment by lf-** [comment]
Ooh, I see. Thanks for the clarification. I'll see how feasible it is to package it myself, although I also can't promise a huge amount given I only use NixOS or GNOME on my work computer.

**Comment by samhug** [comment]
I cleaned up the pop-launcher package I've been using and made a PR #176303

**Comment by flokli** [comment]
With `pop-launcher` from https://github.com/NixOS/nixpkgs/pull/176303 in `$PATH`, `Super+/` works for me like a charm!
