### ISSUE TITLE
Building mesa 12.0

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#17442]
I'm [trying](https://github.com/rnhmjoj/nixpkgs/blob/mesa/pkgs/development/libraries/mesa/default.nix) to upgrade the mesa package to 12.0.1, with no success so far.
The library now requires `mako` (a python template engine) to generate code
Without it the build fails with the error:
```
Making all in mesa
make[3]: Entering directory '/tmp/nix-build-mesa-noglu-12.0.1.drv-0/mesa-12.0.1/src/mesa'
  GEN      main/format_info.h
  GEN      main/format_pack.c
Traceback (most recent call last):
  File "./main/format_pack.py", line 3, in <module>
    from mako.template import Template
ImportError: No module named mako.template
```
However adding `pythonPackages.Mako` to the build inputs doesn't work either: it fails with the same error but in a different module:
```
  GEN      brw_nir_trig_workarounds.c
Traceback (most recent call last):
  File "./brw_nir_trig_workarounds.py", line 24, in <module>
    import nir_algebraic
  File "/tmp/nix-build-mesa-noglu-12.0.1.drv-0/mesa-12.0.1/src/compiler/nir/nir_algebraic.py", line 32, in <module>
    import mako.template
ImportError: No module named mako.template
```
The package is the correct one, I tested it with
```sh
nix-shell -p pythonPackages.Mako --pure --run 'python -c "import mako.template"'
```
So, what am I missing?

**Comment by FRidh** [comment]
While you added both the interpreter and the module, the interpreter doesn't know where the module is. Typically we solve this by adding the path to the module to `PYTHONPATH`.

In my opinion a nicer solution is to add to `buildInputs` the following
`(python.withPackages (ps: [ps.Mako])`

This builds an environment where the interpreter can find the modules that are specified, in this case only Mako and dependencies. I've tested this approach and it works.

**Comment by rnhmjoj** [comment]
Thank you! Could you also tell me what other solutions are?
I noticed some package uses `pythonPath = [ ... ];` 
I tried adding python and mako in the buildInputs and mako to pythonPath but it doesn't seem to work.

**Comment by FRidh** [comment]
`pythonPath` is used when creating wrappers for binaries. Since you don't produce any scripts that depend on Python modules that is irrelevant.

The solution I referred to first is to export `PYTHONPATH` in say the `configurePhase`. If `PYTHONPATH` then contains the path to `Mako` then when `python` is invoked, it will find `Mako`.

**Comment by rnhmjoj** [comment]
Ok, thank you again.
