### ISSUE TITLE
Feh is added to the system PATH when “only” Xfce is enabled.

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#17450]
## Issue description

Currently the `(none)` DE is always enabled, see https://github.com/NixOS/nixpkgs-channels/blob/e781a8257b4312f6b138c7d0511c77d8c06ed819/nixos/modules/services/x11/desktop-managers/none.nix

Because of that, feh is always added to system PATH, in here:

https://github.com/NixOS/nixpkgs-channels/blob/e781a8257b4312f6b138c7d0511c77d8c06ed819/nixos/modules/services/x11/desktop-managers/default.nix#L82-L83

… because in here:

https://github.com/NixOS/nixpkgs-channels/blob/e781a8257b4312f6b138c7d0511c77d8c06ed819/nixos/modules/services/x11/desktop-managers/default.nix#L43-L52

… `needBGPackages` is always true, as the `list` always contains `none`, which doesn’t define `bgSupport = true`.

This whole code is totally pointless if we cannot turn `(none)` off.

**Idea: let’s make `(none)` optional, but by default turned on, not to break people’s setups.**

How I stumbled upon this? While configuring a machine for my mom, with Xfce enabled, I’ve noticed that feh is the default app for opening images, while it shouldn’t even be in `PATH`.
### Steps to reproduce

Turn on Xfce, open file manager, double click on a photo ⇒ feh opens instead of Xfce’s Ristretto.
## Technical details
- System: 16.03.1162.1425a1f (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.03.1162.1425a1f"

**Comment by yegortimoshenko** [comment]
Still a problem in 18.03pre116054.a75265924f (Impala). `feh` is the default photo viewer on my system.

**Comment by michalrus** [comment]
This needs to be reopened.
