### ISSUE TITLE
graphite database has incorrect permissions

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixpkgs#1745]
The `/var/db/graphite` directory seems to get created with `graphite:nogroup` permissions, with the current `HEAD` (6a95e90f27f63a49d07df59f8305773d0ddc3e7c). When I installed Graphite a while ago, I got `graphite:graphite` - using `chown` to change permissions seems to fix things.

Could this be related to the new declarative user management stuff?

**Comment by Profpatsch** [comment]
Seems to be fixed. Close? @domenkozar
