### ISSUE TITLE
syncthingtray: needs update from 1.1.3 to 1.1.20

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#174571]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: syncthingtray

current version: 1.1.3
desired version: 1.1.20

###### Notify maintainers

maintainers: @doronbehar

###### Note for maintainers

Please tag this issue in your PR.

**Comment by doronbehar** [comment]
There's a new dependency now needed for syncthingtray - https://github.com/Martchus/qtforkawesome but there's a problem in the logic upstream here:

https://github.com/Martchus/qtforkawesome/blob/v0.0.4/qtforkawesome/CMakeLists.txt

Here's my packaging attempt:

https://github.com/doronbehar/nixpkgs/pull/new/pkg/syncthingtray
