### ISSUE TITLE
Truecrypt wxGUI=false has no effect

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#17457]
## Issue description

The package definition sets `makeFlags = if wxGUI then "" else "NOGUI=1";`, but `makeFlags` is never used. The `builder.sh` script invokes `make` and does not refer to `makeFlags`. When `NOGUI=1` is actually passed to `make`, compilation fails.
### Steps to reproduce

Set `config.truecrypt.wxGUI` to `false` and run any `truecrypt` command. A GUI will open.
## Technical details

Nixpkgs version 16.03 or unstable (any, really - truecrypt is an old package that hasn't been touched in years)

**Comment by joachifm** [comment]
cc maintainer @viric

**Comment by c0bw3b** [comment]
Closing this since Truecrypt is outdated and unmaintained by now.
One should replace it with `veracrypt` which can be built with or without GUI as expected.
