### ISSUE TITLE
chromium won't start under a grsecurity kernel

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#17460]
## Issue description

Running chromium with a grsecurity kernel yields the error:

```
[1500:1500:0802/235641:FATAL:setuid_sandbox_host.cc(162)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/6xhfxlrnjwq8f54qpmzp9c0jjpxya8b0-chromium-51.0.2704.103/libexec/chromium/chrome-sandbox is owned by root and has mode 4755.
#0 0x002b7fe2835e base::debug::StackTrace::StackTrace()
#1 0x002b7fe3ccde logging::LogMessage::~LogMessage()
#2 0x002b82971a1e sandbox::SetuidSandboxHost::PrependWrapper()
#3 0x002b8273d895 content::ZygoteCommunication::Init()
#4 0x002b8273debe content::CreateZygote()
#5 0x002b827beb54 content::BrowserMainLoop::EarlyInitialization()
#6 0x002b825e406b content::BrowserMainRunnerImpl::Initialize()
#7 0x002b825e3303 content::BrowserMain()
#8 0x002b7fdfbbad content::ContentMainRunnerImpl::Run()
#9 0x002b7fdfb081 content::ContentMain()
#10 0x002b7fa3a8da ChromeMain
#11 0x039130667770 __libc_start_main
#12 0x002b7fa3a789 _start
``` 

### Steps to reproduce

```bash
$ cat > test.nix << EOF
{ config, pkgs, ... }:

{
  # The two misbehaving kids
  security.grsecurity.enable = true;
  environment.systemPackages = with pkgs; [ chromium ];

  # Some X environment
  services.xserver.enable = true;
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.windowManager.i3.enable = true;

  # A user
  users.extraUsers.testUser = {
    isNormalUser = true;
    uid = 1000;
    password = "";
  };
}
EOF
$ nixos-rebuild build-vm -I nixos-config=./test.nix && ./result/bin/run-nixos-vm 
```

Login as `testUser`, pop open a terminal (Mod4+Enter), invoke `chromium-browser`.

## Technical details

* System: NixOS
* Nixpkgs version: 26a2392

cc @aszlig @thoughtpolice @joachifm

**Comment by joachifm** [comment]
Thanks for adding this issue, it's been raised before but not recorded (as far as I can tell). You should also see a message like 
> grsec: denied RWX mmap of <anonymous mapping>  /nix/store/6xhfxlrnjwq8f54qpmzp9c0jjpxya8b0-chromium-51.0.2704.103/libexec/chromium/chromium[chromium:5077]

The "normal" fix for this is to disable `mprotect()` restrictions, however that's already done (per `paxctl -v`). For some reason, chromium does work if you set the flag via xattrs. I'm stumped ...

**Comment by copumpkin** [comment]
Do xattrs get preserved in the nix store/NAR files?

**Comment by joachifm** [comment]
@copumpkin relevant Nix issue https://github.com/NixOS/nix/issues/185

**Comment by copumpkin** [comment]
Ah 😦 we could try using paxctld?

**Comment by joachifm** [comment]
Hm, I think this may have been a red herring. Per a comment on IRC, I tried `--disable-setuid-sandbox` which allows chromium to run for me.

**Comment by joachifm** [comment]
I hope that is the solution, because paxctl not working vs xattr working doesn't make any sense to me.

**Comment by obadz** [comment]
I seem to recall that the chrome sandbox meaningfully contributes to security as well, probably don't want to have to choose between grsec and that.

**Comment by obadz** [comment]
Is the a nixos module that will let me disable mprotect via a config entry?

**Comment by joachifm** [comment]
@obadz I'm almost certain that `mprotect()` hardening is not to blame, I think the logs just mislead me. I've tried disabling all PaX per-file protections (by running in non-enforcing mode) but to no avail. On a grsec enabled arch linux system, the only thing I need to do is disable `mprotect()` hardening on chromium itself (as is done in Nixpkgs). The main difference is that their chromium sandbox helper is permitted to retain the setuid bit. 

My understanding is that `--disable-setuid-sandbox` doesn't disable sandboxing entirely, but falls back on namespace-only sandboxing.
> The intention is if you want to run Chrome and only use the namespace sandbox, you can set --disable-setuid-sandbox.  But if you do so on a host without appropriate kernel support for the namespace sandbox, Chrome will loudly refuse to run.

https://bugs.chromium.org/p/chromium/issues/detail?id=598454#c11

Given that the Nixpkgs chromium can't use the setuid sandbox helper anyway, I'd think that you're no worse off for telling chromium to skip trying to enable it at startup. (chromium does warn you about using an unofficial command-line flag, though, but that looks like a generic warning).

Now, why trying to enable the setuid sandbox and failing causes chromium to trigger a PaX violation is unclear to me.

**Comment by obadz** [comment]
@joachifm, thanks for doing this research.

Would it make sense to set up a chromium wrapper that creates `makeWrapper` and a `.desktop` file that  invokes `chromium-browser` with the correct flag?

**Comment by joachifm** [comment]
@obadz possibly. For my own edification I'd like to know why the PaX violation occurs, but more importantly I'd like confirmation that `--disable-setuid-sandbox` really makes you no worse off than you already are when using Nixpkgs chromium.

**Comment by joachifm** [comment]
You can use `chrome://sandbox` to see which sandboxing measures are in effect. It's probably useful to compare those for the `disable-setuid-sandbox` case and vanilla Nixpkgs chromium. If they're the same, I think a wrapper is a viable alternative (you'll get an annoying error, though ...)

**Comment by obadz** [comment]
@aszlig might know

**Comment by joachifm** [comment]
Then again, per the bug I linked, the setuid helper is as good as obsolete anyway ...

**Comment by obadz** [comment]
> IMPORTANT NOTE: The Linux SUID sandbox is almost but not completely removed. See https://bugs.chromium.org/p/chromium/issues/detail?id=598454 This page is mostly out-of-date.

So, safe to remove globally from `nixpkgs` ?

**Comment by obadz** [comment]
Oddly, turning on `security.grsecurity.enable` makes Chromium report that it's not adequately sandbox.

![image](https://cloud.githubusercontent.com/assets/3359345/17398860/d9818f7e-5a36-11e6-9f51-77e0a0952853.png)

If `security.grsecurity.enable = false`, then Chromium is happy even with #17485.

@jasom / @joachifm / @aszlig, any idea whether this is a red herring?

**Comment by copumpkin** [comment]
@obadz perhaps check the system log to see if chromium is making calls that are getting rejected by grsecurity? That could help diagnose what to enable/disable to make it happy again.

**Comment by joachifm** [comment]
@obadz so to be clear, without grsecurity you're getting network, PID, and user namespacing? (I'd expect the SUID sandbox to be off in any case, unless you've convinced Nix to start accepting suid executables in the Store). I'm unaware of any PaX/grsecurity restriction that interferes with unprivileged namespaces. Per my testing, grsecurity is compatible with all the sandboxing features used by chromium (including the suid sandbox).

**Comment by joachifm** [comment]
Ugh, now I'm so confused ... I'm back to having to set PaX flags via xattrs to get Nixpkgs chromium to run, with just paxctl it keeps getting killed for creating a RWX mapping. Even with ALL restrictions removed on the chromium binary via paxctl, it still gets killed. With xattrs, all it needs is `user.pax.flags = m` and the `--disable-setuid-sandbox` runtime option.

**Comment by joachifm** [comment]
Err, scratch that last comment, I'm just stupid. (I was testing this on Arch Linux, whose kernel doesn't support ELF PaX markings at all, hah).

**Comment by joachifm** [comment]
@obadz on the non-grsecurity system, are you able to do `unshare -n`, `unshare -p` or `unshare -u` as an ordinary user? In my nixos test environment those do not work with or without grsecurity enabled.

**Comment by joachifm** [comment]
If you can't do those as an ordinary user, I don't know how chromium would be able to setup those namespaces without a suid helper.

**Comment by obadz** [comment]
> @obadz so to be clear, without grsecurity you're getting network, PID, and user namespacing?

Withour grsecurity, I get this:

![image](https://cloud.githubusercontent.com/assets/3359345/17408175/288312a2-5a62-11e6-81b7-880ff5c304e5.png)

_(By the way, this is trivially reproducible with the VM config file I pasted above)_

**Comment by obadz** [comment]
> @obadz on the non-grsecurity system, are you able to do unshare -n, unshare -p or unshare -u as an ordinary user?

No:
![image](https://cloud.githubusercontent.com/assets/3359345/17408267/6f309d78-5a62-11e6-8175-2f852725d8fa.png)

**Comment by obadz** [comment]
Btw it looks like #14961 is going to force a Chromium version bump shortly so things might shift a bit (https://github.com/obadz/nixpkgs/tree/chromium-update)

**Comment by copumpkin** [comment]
I wouldn't expect you to be able to `unshare` as a regular user, unless you combine those options with `-U`, to request a user namespace (which then lets you behave like root for the other namespaces you request)

**Comment by joachifm** [comment]
@copumpkin ah, you're right I forgot about that

**Comment by joachifm** [comment]
`unshare -U` works in the non-grsec NixOS vm but fails in the grsec enabled one ... I've never seen anything about that in the grsec docs, so this is news to me.

**Comment by obadz** [comment]
@copumpkin,

> @obadz perhaps check the system log to see if chromium is making calls that are getting rejected by grsecurity?

Logs are identical with grsec on/off :-(

**Comment by joachifm** [comment]
There are no grsec options pertaining to unprivileged unshare nor is there anything about it in the docs. As far as I can tell, all the namespace related kernel configs are enabled also in the grsec kernel (i.e., it doesn't appear to deselect anything either). I suppose the reason why this all appears to work on arch linux is only due to being able to use the suid helper.

**Comment by copumpkin** [comment]
```
[12:04:32]  <copumpkin>	are user namespaces expected to work with a grsecurity kernel?
[12:04:43]  <strcat>	copumpkin: yes but they require CAP_SYS_ADMIN
[12:05:24]  <copumpkin>	oh, so that diverges from a standard kernel
[12:06:08]  <copumpkin>	what was the motivation for that? can we disable that restriction in particular?
[12:06:38]  <strcat>	there's no configuration option
[12:06:56]  <strcat>	copumpkin: unpriv user namespaces expose a HUGE amount of additional code to unpriv users
````

**Comment by obadz** [comment]
So the SUID sandbox is useless but a side effect of having it is that Chrome can use grsecurity features that it otherwise can't? 

But how is it than one is adequately sandboxed *without* grsecurity? Does it get in the way?

**Comment by obadz** [comment]
@copumpkin, so is the only way to use this namespace feature to start the app as root and release privileges once they are setup??

(I'm not familiar with namespaces at all)

**Comment by copumpkin** [comment]
Here's the rest of the conversation:

```
[12:06:56]  <strcat>	copumpkin: unpriv user namespaces expose a HUGE amount of additional code to unpriv users
[12:07:14]  <copumpkin>	ah
[12:07:20]  <strcat>	copumpkin: makes local priv escalation much easier when you have a whole bunch of extra mount, networking (netfilter, etc.) code exposed
[12:07:24]  <spender>	and their strategy to exposing more code is to first expose it
[12:07:28]  <copumpkin>	:)
[12:07:33]  <spender>	then add little tweaks after they get owned a dozen times
[12:07:50]  <copumpkin>	we're just trying to get proper grsecurity support in NixOS and someone's complaining that the chromium sandbox stops working with the kernel
[12:07:59]  <copumpkin>	is there a "proper" way to do that?
[12:08:15]  <copumpkin>	(your motivation makes sense btw, I've found them concerning)
[12:09:19]  <strcat>	copumpkin: the chromium sandbox still works, if you enable the setuid sandbox
[12:09:34]  <copumpkin>	yeah, but I think they just phased that out as of a couple of weeks ago
[12:09:38]  <copumpkin>	saying it was mostly irrelevant now :)
[12:09:43]  <strcat>	copumpkin: I think it's still supported
[12:09:49]  <copumpkin>	ah
[12:10:01]  <strcat>	chrome://sandbox/
[12:10:05]  <strcat>	Sandbox Status
[12:10:07]  <strcat>	SUID Sandbox Yes
[12:10:09]  <strcat>	Namespace Sandbox No
[12:10:18]  <copumpkin>	so the pattern for user namespaces is setuid, then voluntarily reduce powers, then take user namespace?
[12:10:24]  <copumpkin>	(in general)
[12:10:28]  <strcat>	or just don't use user namespaces
[12:10:41]  <strcat>	the only real reason people use them is unpriv access to namespaces
[12:10:53]  <strcat>	they aren't particularly useful themselves, all they do is map a range of uids to another
[12:10:55]  <copumpkin>	and y'all just took that away anyway, I guess :)
[12:11:22]  <strcat>	chrome sandbox on android where they got to decide how to implement it doesn't use user namespaces
[12:11:30]  <copumpkin>	okay, I'll think about it and pass on the knowledge to the folks implementing NixOS support
[12:11:32]  <copumpkin>	thanks
```

**Comment by joachifm** [comment]
@copumpkin ah, very interesting, thank you.

@obadz I guess without grsecurity, unprivileged users are permitted to create the namespaces necessary to sandbox chromium.

**Comment by joachifm** [comment]
I have no idea how much worse off you are for running without the namespaces, but if we want them looks like setuid is the only choice. What a roller coaster ride of a bug report this been, though ..

**Comment by obadz** [comment]
> Btw it looks like #14961 is going to force a Chromium version bump shortly so things might shift a bit

Scratch that, I'm now running Chromium 52, nothing changed.

**Comment by jasom** [comment]
So to summarize this so far:

1) Without grsecurity Chromium is happy using user-namespaces sandbox

2) With grsecurity, since user-namespaces doesn't work, it tries to fall back on the setuid sandbox

3) The setuid sandbox is not installed with the nix version of chromium, so it fails

4) passing -disable-setuid-sandbox causes it to not try to start the setuid sandbox

Is it possible to install the setuid sandbox still?  I think they keep it around in the chromium codebase for CrOS, but it might be hard to get it in a vanilla linux build

**Comment by joachifm** [comment]
@jasom I think that's a good summary, except the setuid sandbox *is* installed (@obadz it is still included in the new version, right?) but won't have the setuid bit and so is useless. We'd have to move it out of the Nix store for it to work and possibly also patch chromium. Maybe @aszlig  knows more about how we could make chromium use a setuid sandbox at a custom location.

**Comment by obadz** [comment]
> @obadz it is still included in the new version, right?

Yup it's there

**Comment by obadz** [comment]
```
$ grep -b vycrgv9bbaawvfz69lac6avl860yg15h-chromium-52.0.2743.116 ./chrome-sandbox 
$ ./chrome-sandbox 
Usage: ./chrome-sandbox <renderer process> <args...>
```

Looks like the sandbox does not have any reference to Chrome's `$out` and takes the rendering process as an argument. Should be relatively easy to factor out as a separate output and package a NixOS module this so that it's SUID.

**Comment by obadz** [comment]
```
$ cp /nix/store/vycrgv9bbaawvfz69lac6avl860yg15h-chromium-52.0.2743.116/libexec/chromium/chrome-sandbox .
$ sudo chown 0.0 chrome-sandbox 
$ sudo chmod u+s chrome-sandbox

$ ls -l chrome-sandbox
-r-sr-xr-x  1 root  root   23K Aug  4 19:37 chrome-sandbox*

$ ./chrome-sandbox /nix/store/vycrgv9bbaawvfz69lac6avl860yg15h-chromium-52.0.2743.116/libexec/chromium/chromium 
The setuid sandbox provides API version 1, but you need 0
Please read https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md.

The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

That's a bit concerning.

**Comment by obadz** [comment]
cc @cleverca22

**Comment by cleverca22** [comment]
http://pastebin.com/azn0G2NU

chrome-sandbox tries to close fd#7, chrome appears to leak it to all of its children
and it doesnt search $PATH for it, so http://pastebin.com/x4JZ819r doesnt fix things

one solution would be to modify the nix package to
- move chrome-sandbox to a second output
- symlink the old chrome-sandbox location to /var/setuid-wrappers/chrome-sandbox
- install the setuid wrapper via nixos, even if chromium isnt installed (its only 23kb and is now its own output)

**Comment by obadz** [comment]
```
diff --git a/pkgs/applications/networking/browsers/chromium/common.nix b/pkgs/applications/networking/browsers/chromium/common.nix
index 997551f..e987530 100644
--- a/pkgs/applications/networking/browsers/chromium/common.nix
+++ b/pkgs/applications/networking/browsers/chromium/common.nix
@@ -134,6 +134,12 @@ let
     ];
 
     postPatch = ''
+      # We want to be able to specify where the sandbox is via CHROME_DEVEL_SANDBOX
+      substituteInPlace sandbox/linux/suid/client/setuid_sandbox_host.cc
+        --replace \
+          'std::string sandbox_binary(GetSandboxBinaryPath().value());' \
+          'std::string sandbox_binary(GetDevelSandboxPath());'
+
       sed -i -r \
         -e 's/-f(stack-protector)(-all)?/-fno-\1/' \
         -e 's|/bin/echo|echo|' \
```

I'm not sure why we would install the wrapper via nixos without letting the user first ask for it via an option? And if he asks for it we might as well download chromium. I like the multiple outputs solution but I think it can come as a second stage.

**Comment by cleverca22** [comment]
some users may want to update chromium via nix-env without rebuilding all of nixos, and some people want to keep chromium in the profile only

and then chrome just doesnt work until they discover the nixos option

**Comment by joachifm** [comment]
@cleverca22 @obadz thanks to your efforts we now have the building blocks we need. 

@obadz as a chromium user what would be the most convenient way of getting the setuid helper working? Normally, we'd ask the user to simply add an entry to `setuidPrograms` but that doesn't seem to quite fit the bill in our case. 

I'm not too keen on unconditionally dumping a copy of the suid sandbox onto the user's system, although it would be the most magical solution. I guess it wouldn't be too bad if we only did that within the grsecurity module (as long as nixos continues to support unprivileged namespaces out of the box, I see no reason why anybody would want to use the suid sandbox). 

Alternatively, we could do `programs.chromium.useSuidSandbox` or something and set it to `true` within the grsecurity module. I kind of dislike enlarging `programs.*` but that'd work.

Then there's the possibility of a` security.gsecurity.supportChromiumSuidSandbox` option.

Any other suggestions?

**Comment by obadz** [comment]
(Continuing conversation from https://github.com/NixOS/nixpkgs/commit/d6528a1b7fad8bdcd5f9ff8cc11565e6c4a1747a#commitcomment-18543799)

This still doesn't work for me :-(

I copy the sandbox binary out of the nix store, `chown 0.0, chmod u+s` and `export CHROME_DEVEL_SANDBOX=$PWD/chrome-sandbox` and invoke the `/nix/store/6h7p0j2c4ammzy4c4jphk8a2brhdkryi-chromium-52.0.2743.116/libexec/chromium/chromium` and chrome://sandbox still doesn't report the SUID Sandbox as Yes :-(

Running out of ideas…

**Comment by joachifm** [comment]
Just to have this here as well: I don't think the suid sandbox will be used unless chromium determines that its necessary (to create the namespaces).

**Comment by joachifm** [comment]
@obadz also, just to be sure we're on the same page: my understanding is that the SUID sandbox only enhances security inasmuch as it enables the use of namespaces on systems where unprivileged namespaces are unavailable. The chromium sandbox comprises namespaces + seccomp filtering.

**Comment by obadz** [comment]
So to recap, with 987f887 & `grsecurity.enable = true`, I get:

![image](https://cloud.githubusercontent.com/assets/3359345/17455753/eaea3e62-5bb9-11e6-81f7-9614395cb777.png)

Is that sufficient? And can we do better?

**Comment by joachifm** [comment]
@obadz I think that's as good as it gets. SUID vs namespace is mutually exclusive, so that should be okay. The Yama security module is disabled in the common kernel config, but it overlaps with a feature grsecurity also provides (ptrace hardening, specifically preventing the ability to ptrace a running process), so we should actually be covered there as well.

**Comment by obadz** [comment]
@joachifm, great merging now

**Comment by obadz** [comment]
Also merging in 231ed9e which splits out the sandbox as a separate output from the main Chromium output

**Comment by joachifm** [comment]
@obadz cool, great work. Looking forward to trying this out.

**Comment by obadz** [comment]
Hydra is building the split up chromium now: http://hydra.nixos.org/build/38353737/nixlog/1/tail-reload

Thanks a lot for your help @joachifm. And @cleverca22 @jasom @aszlig and @copumpkin too!

**Comment by aszlig** [comment]
Sorry for being a bit late on this, but you won't need either the SUID or the namespace sandbox in grsecurity, because the whole reason why it needs root or user namespaces is to chroot/setuid/setgit to an unprivileged user. I think a RBAC policy for the sandbox created using learning mode should be enough to have an effective layer 1 sandbox (the layer 2 sandbox still uses seccomp-BPF, which I think shouldn't be an issue with grsecurity) without the need to make it setuid or use user namespaces.

**Comment by obadz** [comment]
@aszlig, I'm afraid I don't know how to do any of this but happy to try an patch :)

**Comment by joachifm** [comment]
@aszlig  could you elaborate on this idea? Do you mean to grant CAP_SYS_ADMIN via policy or to outright replace the whole namespace based sandboxing with rbac policy? Policy is probably better but the suid stub requires less effort ... either way, I don't think it has to be either/or.

**Comment by bman7903** [comment]
yall are silly.  This is not as complicated as your making it out to be.  your path is preventing you from changing namespaces.  Check to make sure you have xattr enabled on your /usr/lib partition as a advanced option.  This is as simple as zfs set xattr=yes zpool/usr on real systems, you can use fstab otherwise if you are lost.  Finally cd to the /usr/lib/chromium directory and invoke ./chromium from that directory.  Some one say some thing about memory?  silly rabbit, tricks are for kids.  Building out of tree from source would also work.  I find that to be the answer to any problem, learn how the thing is built then do it yourself.  Or we can just blame debian until the end of time... I like both options.

**Comment by obadz** [comment]
If only there was such a thing as `/usr/lib` ¯\\\_(ツ)\_/¯ …
```
$ find /usr
/usr
/usr/bin
/usr/bin/env
$
```
