### ISSUE TITLE
Gnucash gnucash-2.4.15

### ISSUE THREAD

**Issue by lverns** [NixOS/nixpkgs#17465]
## Issue description

gnucash-2.4.15 does not work out of the box

### Steps to reproduce
I just did a fresh install of NixOS and installed GnuCash with `nix-env -i gnucash`. It installed fine, but I had to walk through a wizard to configure `~/.gconf-path`. After walking through the wizard, the dialog would just hang. Running in a terminal emulator showed that it couldn't connect to gconf. Installing `gconf-3.2.6` solved that issue. After that, the splash screen would only get as far as "Checking Finance::Quote" and then hang. Running `strace -ff gnucash` produced tons of output, but there seemed to be mentions of missing perl protocol https stuff. Installing `perl-LWP-Protocol-https-6.04` solved that issue and GnuCash then started fine.

## Technical details

* System: 16.03.1083.d745044 (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.1083.d745044"

Maintainers
@peti, @domenkozar

**Comment by lverns** [comment]
Just did a test with a fresh user account:
```
$ nix-env -q --installed

$ nix-env -i gnucash-2.6.9
installing ‘gnucash-2.6.9’
building path(s) ‘/nix/store/qzfrnpfq6nm9lf52hac69g9nis7g0yr5-user-environment’
created 6 symlinks in user environment

$ gnucash
Found Finance::Quote version 1.38

$ # started up fine
$ nix-env --uninstall gnucash
uninstalling ‘gnucash-2.6.9’
building path(s) ‘/nix/store/s0qay9qyqrn92zayldbvvj3zrfcl7a72-user-environment’
created 0 symlinks in user environment

$ nix-env -i gnucash-2.4.15
installing ‘gnucash-2.4.15’
building path(s) ‘/nix/store/w8h9l1sm2z9a0iic5y0f1h5k7qblqfww-user-environment’
created 6 symlinks in user environment

$ gnucash

(gnucash:22625): qof-CRITICAL **: qof_object_shutdown: assertion 'object_is_initialized == TRUE' failed

$ # gives GUI error about not finding gconf stuff
```
So it looks like the newer version is pulling the dependencies in properly. I'm actually using the 2.6.* because my data files are too new for 2.4.* .

**Comment by peti** [comment]
I have no clue what to make of this. I am sorry.

**Comment by lverns** [comment]
Just to be clear, is it my bug reporting that is confusing or is it GnuCash/Gconf that is confusing? 

If it my communication that is failing you, I *might* revisit this issue in the future with a clearer presentation of the problem.
