### ISSUE TITLE
`/etc/os-release` is incompatible with the R interpreter

### ISSUE THREAD

**Issue by mtoohey31** [NixOS/nixpkgs#174633]
### Describe the bug

The `/etc/os-release` file generated for nixos is not compatible with the R programming language's interpreter (`pkgs.R`). On startup, the R interpreter prints the following warning (though it does continue as normal after printing the warning):

```
During startup - Warning message:
In readLines("/etc/os-release") :
  incomplete final line found on '/etc/os-release'
```

This could be resolved by adding a trailing newline to `os-release`.

### Steps To Reproduce

1. Start the R interpreter by running `R`, or `nix-shell -p R --command R` if you don't have R installed.

### Expected behavior

No error message should be printed.

### Additional context

I'm not entirely sure whether this should be resolved adding the trailing newline to `os-release`, or whether R should be modified so it doesn't assume a trailing newline. The man page for `os-release` describes the format of the file as "a newline-separated list of environment-like shell-compatible variable assignments". The existing format (no trailing newline) is indeed newline-separated and shell-compatible (bash and zsh both have no problems with it), so maybe I should bring this up with the R folks instead?

On the other hand, all the other distros I've checked (ubuntu, archlinux, and alpine) include a trailing newline, so maybe we should just stick to what they're doing? The fix is trivial:

```diff
diff --git a/nixos/modules/misc/version.nix b/nixos/modules/misc/version.nix
index 010acdb72f6..da458a57484 100644
--- a/nixos/modules/misc/version.nix
+++ b/nixos/modules/misc/version.nix
@@ -13,7 +13,7 @@ let
   attrsToText = attrs:
     concatStringsSep "\n" (
       mapAttrsToList (n: v: ''${n}=${escapeIfNeccessary (toString v)}'') attrs
-    );
+    ) + "\n";
 
   osReleaseContents = {
     NAME = "NixOS";
```

Let me know what you think, and I'd be happy to open a PR wherever we decide the fix should be made.

### Notify maintainers

@peterhoeg @dasJ

**Comment by peterhoeg** [comment]
> -    );
> +    ) + “\n”;

This! It shouldn’t be needed and yet here we are. No harm in doing so that though, so I’m all for this.

> Let me know what you think, and I’d be happy to open a PR wherever we decide the fix should be made.

Sounds great!
