### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by ebzzry** [NixOS/nixpkgs#17463]
## Issue description

I can’t install applications, nor run some. When I try to install chromium, I get:

```
curl: error while loading shared libraries: /nix/store/sfypzdarn7pbmvqhw1vh4d73fl37j2qr-openssl-1.0.2h/lib/libssl.so.1.0.0: invalid ELF header
```

When I run directvnc, I get:

```
directvnc: error while loading shared libraries: /nix/store/hyraq5xzzb435724yfiby3rlrvvkrqz9-libjpeg-turbo-1.5.0/lib/libjpeg.so.62: invalid ELF header
```

There are other operations that are affected, that displays a similar message.

### Steps to reproduce

nix-env -iA nixos.chromium

## Technical details

* System: 16.03.1168.44b1d6b (Emu)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.03.1168.44b1d6b

**Comment by matthewbauer** [comment]
This sounds like an issue with 32-bit vs 64-bit incompatibility. Do you know whether you are on x86_64 or i686?

Also try running this:

```
nix-instantiate --eval -E 'builtins.currentSystem'
```

**Comment by ebzzry** [comment]
@matthewbauer I am on x86_64

**Comment by ebzzry** [comment]
I also can’t upgrade with `nix-env --upgrade`.

**Comment by ebzzry** [comment]
I’m closing this. I think my frequent upgrades from the git checkout rendered my system unusable.

**Comment by vcunat** [comment]
It does sound like that file got corrupted.

**Comment by ebzzry** [comment]
There are other files that were affected, too. I couldn’t remember exactly which, but there were at least three, that other packages depended on. If they were indeed corrupted, I’m wondering how did it happen?
