### ISSUE TITLE
How do we use kdeApp wrapper for applications not part of the official KDE Applications?

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#17467]
## Issue description

@ttuegel has done some great work on making it super easy to build applications against the KDE framework, so in order to build http://www.aelog.org/kronometer, all I had to do was:

1. add a reference in ```pkgs/desktops/kde-5/applications.nix```
2. add the actual derivation (I just copied the one for ```kcalc``` and adjusted it slightly)
3. manually add the source reference in ```srcs.nix```.

All in all - 5 minutes worth of work and kronometer was running. Very smooth.

Now, the problem is that ```kronometer``` isn't distributed as part of the KDE Applications bundle, so the script that generates the ```srcs.nix``` file will overwrite my manual changes made in step 3 on the next run and embedding the ```src``` attribute inside the main definition doesn't work as ```kdeApp``` expects the ```srcs.kronometer``` attribute to exist.

So what is the proper way to use kdeApp to build applications when said application is not part of the official KDE Applications distribution? Or should we modify ```kde-app.nix``` to allow embedding ```src``` as part of the derivation instead of inside ```srcs.nix```?

## Technical details

* NixOS: 16.09.git.5c75180 (Flounder)
* Nix: nix-env (Nix) 1.11.2
* nixpkgs: 16.09pre87801.26a2392

**Comment by FRidh** [comment]
As I noted in #17468 you can given the `src` to `kdeApp`.

**Comment by peterhoeg** [comment]
Indeed, thanks!

**Comment by ttuegel** [comment]
It might be better to use `kdeDerivation` instead of `kdeApp`. `kdeDerivation` has all the typical options for CMake and it will work with `kdeWrapper`. `kdeApp` adds versions, sources, and metadata on top of `kdeDerivation`; you can always override those settings, but if you forgot one of them, you might not get what you expect.

**Comment by peterhoeg** [comment]
That's exactly what I did based on @FRidh's feedback in my second take on #17468 which should be good to merge. Thanks for all the pointers.
