### ISSUE TITLE
qt6Packages.callPackage should not add qt6.qtdeclarative to dependencies

### ISSUE THREAD

**Issue by milahu** [NixOS/nixpkgs#174828]
low priority

qt6.qtdeclarative is a large package, so it should be excluded for non-GUI qt apps ([example](https://github.com/milahu/qt6-project-template/blob/main/src/main-cli.cc))

currently, when i build a package with `qt6Packages.callPackage` and empty buildInputs, it pulls

* qt6.qtbase
* qt6.qtwayland
  * qt6.qtdeclarative
    * qt6.qtshadertools

the problem is wrapQtAppsHook and its deps

https://github.com/NixOS/nixpkgs/blob/271f15a2384a8744d0b25f3c88484d71b577079b/pkgs/development/libraries/qt-6/default.nix#L86-L89

and qtwayland pulls qtdeclarative

```
$ nix why-depends ./nixpkgs#qt6.qtwayland ./nixpkgs#qt6.qtdeclarative
/nix/store/9hwcqcvv8lb38w57y5pjzqxg65d7d1qs-qtwayland-6.3.0
└───/nix/store/wksjqhyckaji17wmzgx0096hikv5bcvi-qtdeclarative-6.3.0
```

the problem is fixed by removing `self.qtwayland.dev` from deps
wrapQtAppsHook should use only the declared buildInputs

disabling wrapQtAppsHook (dontWrapQtApps = true) is no option, as also CLI qt apps need the qt wrapper

qtwayland is there, so that users dont need to add it to buildInputs
assuming that all qt apps are GUI apps

im in favor of making this consistent with cmake
so that all GUI apps must add qtwayland to buildInputs

CLI qt app:

```cmake
find_package(Qt6 REQUIRED COMPONENTS Core)
target_link_libraries(${target_name} PRIVATE Qt6::Core) # = qtbase
```

GUI qt app:

```cmake
find_package(Qt6 REQUIRED COMPONENTS Core Widgets)
target_link_libraries(${target_name} PRIVATE Qt6::Core Qt6::Widgets) # = qtbase qtwayland
```

since #169296 

cc @NickCao @ttuegel

**Comment by NickCao** [comment]
I'm in favour of this change, but the proportion of qt cli app night be relatively small, and it's not immediately clear that qtwayland should be added if the build log yields Qt6::Widgets is missing.

**Comment by NickCao** [comment]
Actually we are *abusing* qtwayland as a shortcut to bringing in qtdeclarative, this should be fixed too.

**Comment by milahu** [comment]
> it's not immediately clear that qtwayland should be added if the build log yields Qt6::Widgets is missing.

we could patch the cmake message to "please add qtdeclarative to your propagatedBuildInputs"

the alternative would be to add a `qtDisableGui` flag, but thats more obscure than buildInputs

**Comment by NickCao** [comment]
Adding the lines to nixpkgs manual is sufficient.

**Comment by ttuegel** [comment]
By the way, `qtwayland` is not only needed to pull in `qtdeclarative`, but it's required for all GUI apps so that they work seamlessly on X11 or Wayland.
