### ISSUE TITLE
Enable NaCl support on chromium

### ISSUE THREAD

**Issue by PkmX** [NixOS/nixpkgs#1748]
Passing `enableNaCl = true` to chromium currently fails to build with the following error:

    ninja: Entering directory `out/Release'
    ninja: error: '../../native_client/toolchain/.tars/naclsdk_linux_x86.tgz', needed by 'gen/sdk/toolchain/linux_x86_newlib/stamp.untar', missing and no known rule to make it

**Comment by Profpatsch** [comment]
(triage) @PkmX still an issue?

**Comment by grahamc** [comment]
I'm almost certain this is fixed based on https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/google-chrome/default.nix#L111 and https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/default.nix#L6  can someone close it?
