### ISSUE TITLE
Stable Chrome 51 no longer exists

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#17480]
## Issue description
It would seem that Google has removed Chrome 51 from their repository.
Because of that, we can no longer build `google-chrome-stable`.

I believe this to be the latest stable but I am having a hard time finding out the versions for beta/dev (we generally update all three at the same time):
https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_52.0.2743.82-1_amd64.deb

### Steps to reproduce
Try to install Chrome stable

**Comment by jdreaver** [comment]
See https://github.com/NixOS/nixpkgs/issues/14961 and https://github.com/NixOS/nixpkgs/issues/17389. I'm experiencing the same issue and had these issue links handy.

**Comment by NeQuissimus** [comment]
Closing as it would seem that @benley did fixed this in #17500
