### ISSUE TITLE
nix flake check fails when pkgs.pre-commit is a dependency

### ISSUE THREAD

**Issue by jmgilman** [NixOS/nixpkgs#174847]
### Describe the bug
Running `nix flake check` with `pkgs.pre-commit` as a dependency is failing with an obscure error. 

### Steps To Reproduce
Create a flake.nix:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.pre-commit
          ];
        };
      }
    );
}
```

Run:

```
nix flake lock && nix flake check
```

Receive error:

```
error: Package ‘dotnet-sdk-6.0.300’ in /nix/store/7dccdvyr8kpvaiv7axcrw38gja5j0m07-source/pkgs/development/compilers/dotnet/build-dotnet.nix:89 is not supported on ‘i686-linux’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
```

### Expected behavior
Expected `nix flake  check` to not fail due to an i686-linux compatibility issue.

### Screenshots
N/A

### Additional context
It's not clear to me how I can safely bypass this problem. I'm currently unable to run any of my tests if I happen to have `pkgs.pre-commit` as a dependency anywhere. If I remove the offending package the check passes fine. 

### Notify maintainers
@borisbabic 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(josh): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by lourkeur** [comment]
Happens because the flake exports an i686 shell too due to `defaultSystems`. See `nix eval .#devShells.i686-linux.default`.

I think it is intended behaviour for `check` to check if every output (in every arch) evaluates.

**Comment by jmgilman** [comment]
I see. Are you aware of a way to get around this limitation? I have all my tests written using `nix flake check` and they are currently failing due to adding this dependency.

**Comment by lourkeur** [comment]
I can think of a couple:
- drop `i686-linux` from your flake if that fits your model
- conditionally disable some tests on `i686-linux`. `lib.optionalAttrs` can help, [example from one of my projects](https://github.com/lourkeur/miniguest/blob/471740f66f22933e3e611d245b43aa136dcc72e9/checks/declarative-management.nix#L53). (Or you can use `if then else` directly)

I'm also assuming there isn't a sensible way to fix dotnet-sdk on Intel32 but that's a hunch.

**Comment by jmgilman** [comment]
Unfortunately, the flake is consumed by third parties, so disabling `i686-linux` across the whole flake isn't feasible. I'm using `pre-commit` in my local environment when developing the flake (it's not actually a direct dependency of the flake). 

The second method is what I've been looking at, but it's not actually the tests that are failing, Nix never even gets to the tests defined in `checks` because it fails before that happens. I need a way to conditionally disable `nix flake check` from trying to evaluate `i686-linux`. Given my limitation of not wanting to effect downstream consumers, it feels like I'm in a bit of a pickle.

**Comment by lourkeur** [comment]
Wait, there's a way. You can conditionally include the problematic devShell:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShells = nixpkgs.lib.optionalAttrs (system != "i686-linux") {
          default = pkgs.mkShell {
            packages = [
              pkgs.pre-commit
            ];
          };
        };
      }
    );
}

**Comment by jmgilman** [comment]
Amazing, thank you for the help!
