### ISSUE TITLE
Test errors when building git from source on armv7l-linux

### ISSUE THREAD

**Issue by kip93** [NixOS/nixpkgs#174934]
### Steps to reproduce

1. (On an `armv7l-linux` machine) run `nix-build '<nixpkgs>' -A git`.

### Build log

```console
$ nix-build '<nixpkgs>' -A git
this derivation will be built:
  /nix/store/1y3ci5fa1dbmcmmn58wgfx6lap2zp2np-git-2.36.0.drv
building '/nix/store/1y3ci5fa1dbmcmmn58wgfx6lap2zp2np-git-2.36.0.drv'...
...
t3800-mktag.sh ..................................... ok
t3904-stash-patch.sh ............................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/8 subtests
t3905-stash-include-untracked.sh ................... ok
t3701-add-interactive.sh ........................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 3/70 subtests
t3908-stash-in-worktree.sh ......................... ok
...
Test Summary Report
-------------------
t3904-stash-patch.sh                             (Wstat: 256 Tests: 8 Failed: 1)
  Failed test:  8
  Non-zero exit status: 1
t3701-add-interactive.sh                         (Wstat: 256 Tests: 70 Failed: 3)
  Failed tests:  25, 35, 58
  Non-zero exit status: 1
Files=949, Tests=24136, 1672 wallclock secs (18.75 usr  7.84 sys + 2327.43 cusr 3439.82 csys = 5793.84 CPU)
Result: FAIL
make[1]: *** [Makefile:56: prove] Error 1
make[1]: Leaving directory '/tmp/nix-build-git-2.36.0.drv-0/git-2.36.0/t'
make: *** [Makefile:2949: test] Error 2
```

[Full log](https://gist.github.com/kip93/116619dbba0a2c64e8422600ceea0249)

### Additional context

* Sandbox disabled because of running into #124372.
  ```console
  $ cat /etc/nix/nix.conf
  filter-syscalls = true
  sandbox = false
  auto-optimise-store = true
  max-jobs = auto
  experimental-features = nix-command
  ```
* Also tested on an `x86_64-linux` machine where it built successfully (with substitutes disabled).

### Notify maintainers

Based on [pkgs/applications/version-management/git-and-tools/git/default.nix#L388](https://github.com/NixOS/nixpkgs/blob/41cc1d5d9584103be4108c1815c350e07c807036/pkgs/applications/version-management/git-and-tools/git/default.nix#L388):
* @primeos
* @wmertens
* @globin

### Metadata

```console
$ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"armv7l-linux"`
 - host os: `Linux 5.15.32-v7l+, Raspbian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.1`
 - channels(pi): `"nixpkgs"`
 - nixpkgs: `/home/pi/.nix-defexpr/channels/nixpkgs`
$ cat ~/.nix-defexpr/channels/nixpkgs/.git-revision
41cc1d5d9584103be4108c1815c350e07c807036
```

**Comment by primeos** [comment]
I wonder if it would make sense to only enable the tests on x86_64 and aarch64. Our main CI only runs on those platforms so we don't notice test failures on other platforms, we already had tests failing on aarch64, and usually we can just ignore such test failures as they don't seem to affect users. So IMO it would likely be best to simply disable all tests on other platforms to avoid such issues. However, I'm not sure how often this causes such problems. In this case it could also be related to the disabled build sandbox (or maybe https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-filter-syscalls but according to the documentation it should default to `true`).

**Comment by kip93** [comment]
That is exactly how I ended up working around the problem. Assuming that the unstable channel itself is tested on `x86_64` and `aarch64` before making it out to the public anyway, I wrote this `~/.config/nixpkgs/config.nix` to simply ignore test errors, with an added clause to check for the current system's arch to make it more portable:
```nix
{
  # Modify packages
  packageOverrides = pkgs:
    # Apply function to all packages
    builtins.mapAttrs
      (_: pkg:
        if
          # Is not one of the architectures tested on nixpkgs hydra
          # See https://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-configuration & https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/release.nix
          (builtins.all (s: s != builtins.currentSystem) [ "x86_64-linux" "i686-linux" "aarch64-linux" "x86_64-darwin" ]) &&
          # Is an overridable package
          (builtins.isAttrs pkg) && (builtins.hasAttr "overrideAttrs" pkg) &&
          # Has got tests & has not yet been overriden (avoids infitite recursion)
          (((builtins.hasAttr "doCheck" pkg) && pkg.doCheck) || ((builtins.hasAttr "doInstallCheck" pkg) && pkg.doInstallCheck))

        then
          # Disable tests
          pkg.overrideAttrs (_: { doCheck = false; doInstallCheck = false; })

        else
          # Don't touch package
          pkg
      ) pkgs;
}
```
I could just hard-coded the packages that actually have failing tests and just disable those, but as you said code is not tested on `armv7l-linux` anyway, so might as well disable them all.

Disabling tests though has the drawback of changing the hash of the derivation itself, which for my use case is not ideal.

For the interpreter sandboxing problem, at first I just disabled it entirely since it was one of the suggested workarounds; now I tried to do the suggested approach of only allowing `/bin/sh` through the sandbox but no dice, feels like the options `sandbox-paths` and `extra-sandbox-paths` are ignored either when set on `/etc/nix/nix.conf` or via command line, resulting in the same invalid interpreter error. That is probably a conversation for another place, though.

**Comment by misuzu** [comment]
> - multi-user?: `no`

Single-user nix is crippled, it's probably the reason `git` build is failing for you. I have a [hydra](https://hydra.armv7l.xyz/project/nixpkgs) instance building some packages for `armv7l-linux`, and there seems to be no issues with `git` package.
