### ISSUE TITLE
Can't Boot LiveCD ISO from USB

### ISSUE THREAD

**Issue by mfine** [NixOS/nixpkgs#17496]
## Issue description

![img_4819](https://cloud.githubusercontent.com/assets/60851/17386853/5999ce5e-59a3-11e6-82b3-3ee5a909b233.JPG)

![img_4821](https://cloud.githubusercontent.com/assets/60851/17386964/21f1fb42-59a4-11e6-842b-332a8c1451f9.JPG)

Booting `nixos-minimal-16.03.1168.44b1d6b-x86_64-linux.iso` gets stuck in stage 1. I've seen this described in earlier issues, but this seems to be continuing to happen. I followed the steps from the manual and the wiki. I set the label of my USB drive to be NIXOS_ISO:

```
$ sudo file /dev/sdc1 -s
/dev/sdc1: DOS/MBR boot sector, code offset 0x58+2, OEM-ID "SYSLINUX", sectors/cluster 32, Media descriptor 0xf8, sectors/track 32, heads 255, hidden sectors 2, sectors 62844670 (volumes > 32 MB) , FAT (32 bit), sectors/FAT 15336, serial number 0xf5ca18e8, label: "NIXOS_ISO  "
```

Ran this against a couple of different systems with similar results. Let me know of anything I can do to help troubleshoot.

**Comment by domenkozar** [comment]
Are you booting as UEFI?

**Comment by jokogr** [comment]
Did you verify the checksum of the ISO file? How did you flash the USB disk? Could you try with another one?

**Comment by mfine** [comment]
@domenkozar don't think it's booting with UEFI - I'm trying to switch over to UEFI in my bios but having difficulties.

@jokogr the ISO is looking ok - I was able to boot off it on a third, different system.

**Comment by cleverca22** [comment]
do you see device nodes for the hdd in /dev?
what does ```cat /proc/cmdline``` show?

`/dev/sdc1: DOS/MBR boot sector, code offset 0x58+2, OEM-ID "SYSLINUX", sectors/cluster 32, Media descriptor 0xf8, sectors/track 32, heads 255, hidden sectors 2, sectors 62844670 (volumes > 32 MB) , FAT (32 bit), sectors/FAT 15336, serial number 0xf5ca18e8, label: "NIXOS_ISO  "`

is that 2 extra spaces in your label?, why is it fat?

**Comment by mfine** [comment]
There seem to be device nodes for the hdd:

![img_4822](https://cloud.githubusercontent.com/assets/60851/17420279/b28d3f42-5a56-11e6-8e3b-c1872e3b2e8a.JPG)

The label is 11 character limit - the extra two characters are spaces. I followed the instructions on the wiki to make a bootable USB stick:

> Obtain a USB stick formatted with the VFAT/FAT32 filesystem with enough free disk space to hold the contents of the ISO image.

**Comment by mfine** [comment]
Figured out the problems in my bios settings - sorry about the issue! Had not properly forced UEFI.
