### ISSUE TITLE
Inconsistent Mosquitto ACL rules

### ISSUE THREAD

**Issue by anti-social** [NixOS/nixpkgs#174971]
### Describe the bug

Mosquitto's global listener ACL allows to describe patterns, but user's ACL does not. User's ACLs are always prepended with `topic` prefix.

### Steps To Reproduce

Following configuration:

```nix
services.mosquitto = {
  enable = true;
  listeners = [
    {
      acl = [ "topic readwrite #" ];
      users = {
        iot_device = {
          password = "12345678";
          acl = [
            "topic write tasmota/discovery/#" 
            "topic write homeassistant/#" 
            "pattern read cmnd/tasmota/%c/#"
            "pattern write stat/tasmota/%c/#"
            "pattern write tele/tasmota/%c/#"
          ];
        };
    }
  ];
};
```

produces an invalid ACL configuration:

```
topic readwrite #
user iot_device
topic topic write tasmota/discovery/#
topic topic write homeassistant/#
topic pattern read cmnd/tasmota/%c/#
topic pattern write stat/tasmota/%c/#
topic pattern write tele/tasmota/%c/#
```

### Expected behavior

I would expect that user's ACL syntax is the same as listener's.

For backward compatibility it's worth to add `topic` prefix if an ACL rule is not started with `topic` or `pattern`.

### Additional context

https://github.com/NixOS/nixpkgs/blob/023e25264cb8022f93ecdff5f28c4a8762cb34ec/nixos/modules/services/networking/mosquitto.nix#L150

**Comment by pennae** [comment]
that's intentional. pattern acls are not scoped to users, so they're only valid in the global acl:

> The substitution pattern must be the only text for that level of hierarchy. Pattern ACLs apply to all users even if the "user" keyword has previously been given.

**Comment by anti-social** [comment]
Understood. Thanks for the clarification.
