### ISSUE TITLE
rnote seems broken

### ISSUE THREAD

**Issue by dccsillag** [NixOS/nixpkgs#174935]
### Describe the bug

The current derivation for rnote seems to be broken. I haven't really played around with it much, but quite notably the color picker for the brushes is very wrong: instead of extruding the selected color, it changes the color of the first color box (and only after switching menus!). This appears to be particular to this derivation: on both the official flatpak and my derivation, this doesn't seem to be an issue.

### Steps To Reproduce
1. open the program
2. draw something with the default black pen
3. select the green color for the pen
4. nothing will seem to have changed, but if you write now it will be green
5. switch to the shapes menu
6. switch back to the pen menu
7. now the first color box (which was black) is green, and there is no longer a black pen box

### Expected behavior

on step 4, there should be a visible change in that the black color gets de-extruded and the green one gets extruded.
step 7 shouldn't happen at all.

### Additional context

I've ended up making my own derivation for rnote, which seems to work perfectly fine. Here it is (note: `./.` refers to rnote's git repository checked out at `dcb9016`, which corresponds to v0.5.3; it should be the same as a `fetchGitHub` or similar):

```nix
{ pkgs ? import <nixos-unstable> { } }:
pkgs.rustPlatform.buildRustPackage rec {
  pname = "rnote";
  version = "0.5.3";

  src = ./.;

  nativeBuildInputs = with pkgs; [
    cargo
    rustc
    pkg-config
    cmake
    meson
    ninja
    gtk4
    gtk3
    desktop-file-utils
    shared-mime-info
    librsvg
    wrapGAppsHook
  ];
  buildInputs = with pkgs; [
    alsa-lib
    gtk4
    libadwaita
    poppler
    libxml2
    librsvg
  ];

  cargoSha256 = "sha256:16a7siwkgv2lk2sx6qx61r8vprrjdkncdvzzqrqz9lb0b36fr8xm";

  configurePhase = ''
    meson setup --prefix=$out _mesonbuild
  '';
  buildPhase = ''
    meson compile -C _mesonbuild
  '';
  installPhase = ''
    mkdir -p $out/bin
    meson install -C _mesonbuild
  '';
}
```

I'm still a noob at Nix stuff, but it might be of help.

### Notify maintainers

@dotlambda 
@yrd 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(daniel): `""`
 - channels(root): `"nixos-unstable-22.11pre380124.5ce6597eca7, nixpkgs-21.11.337659.06db2e21974"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by yrd** [comment]
Hm.... Can't seem to be able to reproduce this under mostly vanilla GNOME. What DE are you running?

**Comment by yrd** [comment]
@dccsillag Is this still relevant?

**Comment by dccsillag** [comment]
Oops, I'm terribly sorry for my lack of response.

I tried this out again with rnote from nixpkgs unstable and was unable to reproduce it, so I'll close this issue.
Sorry for the inconvenience.

**Comment by yrd** [comment]
Great – no worries!
