### ISSUE TITLE
mailspring 1.10.3 fails to launch with ozone-platform=Wayland

### ISSUE THREAD

**Issue by berbiche** [NixOS/nixpkgs#175069]
### Describe the bug

Mailspring 1.10.3, which was merged in 32bcc243c45e3536714231a176d2d91583c3756c, updated to Electron 17.4, yet it cannot be started with the Wayland backend!

### Steps To Reproduce

1. Run a Wayland session

2. `nix-shell -I "nixpkgs=https://github.com/nixos/nixpkgs/archive/32bcc243c45e3536714231a176d2d91583c3756c.tar.gz" -p "mailspring.overrideAttrs(drv: { buildInputs = drv.buildInputs or [ ] ++ [ libglvnd ]; })"`

3. `strace -f mailspring --ozone-platform=wayland`

    A window appears after a few hundred milliseconds.

    ```
    Running database migrations
    App load time: 594ms
    ```

4. `mailspring --ozone-platform=wayland`

    No window appears and the following log is produced

    ```
    [147490:0528/000909.742204:ERROR:egl_util.cc(74)] Failed to load GLES library: libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
    [147490:0528/000909.743600:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
    Running database migrations
    App load time: 293ms
    </snip>
    ```

### Expected behavior

I'm not sure why mailspring only finds libGLESv2 when ran through strace (probably touches dll loading or uses ld-preload?).

Mailspring should start correctly.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers
@primeos for all the Wayland knowledge you have :)
@doronbehar

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.5-zen1, NixOS, 22.05 (Quokka), 22.05.20220514.38f7769`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - nixpkgs: `/run/current-system/nixpkgs`
```

**Comment by primeos** [comment]
Might be multiple packaging issues (https://github.com/NixOS/nixpkgs/issues/158175). It might help to look at Google Chrome (especially recent-ish changes: https://github.com/NixOS/nixpkgs/commits/master/pkgs/applications/networking/browsers/google-chrome). It might e.g. require cleaning up some symlinks (https://github.com/NixOS/nixpkgs/commit/c3e8270c3a623c8230879d8eb174d31fb9382d35). I also "fixed" it via https://github.com/NixOS/nixpkgs/pull/155138/files once but IIRC that's the wrong approach. But I'm a bit out of the loop as I don't use Electron anymore.

**Comment by berbiche** [comment]
Stale issue
