### ISSUE TITLE
Building util-linux-2.28 on a grsecurity kernel fails at chmod

### ISSUE THREAD

**Issue by mrobbetts** [NixOS/nixpkgs#17501]
## Issue description
In updating my system to latest master commit of nixpkgs, it needs to rebuild util-linux. The build reliably fails for this package with:

```
chmod 4755 /nix/store/5h4p154sq6b39cccxk52g0kbnq62zgjf-util-linux-2.28-bin/bin/mount
chmod: changing permissions of '/nix/store/5h4p154sq6b39cccxk52g0kbnq62zgjf-util-linux-2.28-bin/bin/mount': Permission denied
make[4]: *** [Makefile:11838: install-exec-hook-mount] Error 1
make[4]: Leaving directory '/tmp/nix-build-util-linux-2.28.drv-0/util-linux-2.28'
make[3]: *** [Makefile:11621: install-exec-am] Error 2
make[3]: Leaving directory '/tmp/nix-build-util-linux-2.28.drv-0/util-linux-2.28'
make[2]: *** [Makefile:11510: install-am] Error 2
make[2]: Leaving directory '/tmp/nix-build-util-linux-2.28.drv-0/util-linux-2.28'
make[1]: *** [Makefile:11202: install-recursive] Error 1
make[1]: Leaving directory '/tmp/nix-build-util-linux-2.28.drv-0/util-linux-2.28'
make: *** [Makefile:11504: install] Error 2
builder for ‘/nix/store/4mz88a452sqhpvr4l1027f1x335rr7gd-util-linux-2.28.drv’ failed with exit code 2
```

I am running `grsecurity` on this system; at the time of the failure, my `dmesg -T` shows:
```
...
[Wed Aug  3 23:31:14 2016] grsec: denied chmod +s of /nix/store/2z8glfy8gm2798jvf82difl5d4p2nfmp-openssh-7.2p2/libexec/ssh-keysign by /nix/store/07axizqswlwc819xcd8dk2m1q0ylddmh-coreutils-8.25/bin/coreutils[/nix/store/07ax:16147] uid/euid:30002/30002 gid/egid:30000/30000, parent /nix/store/5ypfn4kd8518d0qs094zk3bq8ma0gyzj-gnumake-4.2.1/bin/make[make:16101] uid/euid:30002/30002 gid/egid:30000/30000
[Wed Aug  3 23:31:21 2016] grsec: denied chmod +s of /nix/store/5h4p154sq6b39cccxk52g0kbnq62zgjf-util-linux-2.28-bin/bin/mount by /nix/store/07axizqswlwc819xcd8dk2m1q0ylddmh-coreutils-8.25/bin/coreutils[chmod:19105] uid/euid:30003/30003 gid/egid:30000/30000, parent /nix/store/5ypfn4kd8518d0qs094zk3bq8ma0gyzj-gnumake-4.2.1/bin/make[make:19091] uid/euid:30003/30003 gid/egid:30000/30000
```

So I guess there's something fishy going on between this package and `grsecurity`. Any ideas where the problem might be?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`16.09.git.99f63b4 (Flounder)`

* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.2`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"16.09.git.99f63b4"`

**Comment by vcunat** [comment]
Perhaps there's some policy in grsecurity about setuid bits? After the build finishes, those bits would be stripped by nix as nix store doesn't allow them, but the upstream builder apparently tries to set them.

**Comment by mrobbetts** [comment]
I think that grsecurity has some opinion on `setuid` bits indeed. I guess, the question is, does this file really need `setuid` to be set? This seems to be the only build I am having trouble with, so I would guess no... but then `util-linux` seems somewhat unique, so I could believe it has unusual needs.

I'm trying to figure out if there's a `sysctl` or so that will allow me to relax this restriction, at least temporarily, so I can play a bit further. But grsecurity is a complex beast...

**Comment by vcunat** [comment]
> I guess, the question is, does this file really need setuid to be set?

As I wrote, it doesn't; nix clears the bit at the end of build anyway.

**Comment by vcunat** [comment]
BTW, you should be able to avoid such problems by using our binaries from Hydra (typically just by following a channel).

**Comment by mrobbetts** [comment]
> As I wrote, it doesn't; nix clears the bit at the end of build anyway.

Ah, interesting. Is it an error in `util-linux`s Makefile/builder, then? Or, at least, something that needs to be fixed in the package?

> BTW, you should be able to avoid such problems by using our binaries from Hydra (typically just by following a channel).

Well, heh, I don't deliberately not use Hydra's output! I just hit the Go button and it builds what it builds. I guess some aspect of my configuration is forcing it to build this package locally. I was actually assuming it was my using `grsecurity` that did it, but since you're asking, maybe it's something else instead...

Is there an easy way to figure out what's caused by what?

**Comment by joachifm** [comment]
@mrobbetts I'm assuming you're doing sandboxed builds? You could try setting `boot.kernel.sysctl."kernel.grsecurity.chroot_deny_chmod"`, it controls whether a chrooted process is permitted to do `chmod +s`. I'll look into adding that to the module, but I'm going to be semi afk for a while.

**Comment by joachifm** [comment]
@mrobbetts did you try the workaround I suggested? It should allow the build to proceed. I don't know if it makes sense to patch the build, as it's only a problem on grsecurity enabled systems.

**Comment by mrobbetts** [comment]
Hi @joachifm,
Yep, I did try and it works perfectly. Sorry for not getting back to you.

If you'd prefer not to patch the build itself, would fixing this involve a change to the package's expression which adds the sysctl automatically?

On the other hand, does requiring this setting weaken chroot protections system-wide? I am assuming that, in a world where ideally everyone would use some subset of grsecurity (for what reasons would somebody *not* want to use it? Performance?), we would want to support grsecurity as smoothly as possible. I guess, if the chmod protection specifically isn't very important either way, then just disabling it for everyone should be fine...?

**Comment by joachifm** [comment]
I think this has to be addressed on the host OS side of things. As a short-term solution, I'll push a patch that conditionally permits `chmod +s` if the user has configured Nix to do sandboxed builds. Non-NixOS users will have to do so manually. Setting sysctls from within the build environment is not viable.

Disabling chroot restrictions makes it easier for privileged processes to break out of a chroot jail, so it's kind of terrible to do so just to support an action that occurs every once in a while (or only very rarely for users primarily relying on binary substitutes), but for now that is the easiest way to go. That said, it's not like you're auto-owned by relaxing the chroot restrictions (you might be if you tend to run network facing daemons as root that rely on chroot for security, though).

Ideally, we'd rely on RBAC to selectively grant permissions as and when needed. A close second would be to disable the restrictions before the build and re-enable them afterwards, but it's not clear to me how to make that user-friendly, suggestions are welcome.

**Comment by mrobbetts** [comment]
@joachifm, I think I am confused actually. Based on what @vcunat said above, the setuid permission being set is subsequently stripped from the executable by nix anyway when it installed into the store.

Given that, isn't this a case of the util-linux build script trying to do something privileged that it doesn't even need to do? And if so, would it be better for everyone if this were fixed upstream?

**Comment by joachifm** [comment]
@mrobbetts util-linux contains several executables that are traditionally installed with the suid bit set, such as `su`, `mount` &c. I think it's fair for upstream to assume the ability to set the expected bits upon install (these being system utilities, the install is rightly considered a privileged operation). In the Nix world, this is merely pointless, it is only when grsec is brought into it that a problem occurs (and then only under specific configurations).

If you care to, you could propose a patch that removed the `chmod +s` from the util-linux build, but I'd consider that too invasive and entirely the wrong place to address the issue, but someone else might agree with it.

**Comment by mrobbetts** [comment]
Getting closer! :)

My confusion is reduced to: *since these are system utilities and require privileges to do their work (this makes perfect sense), and since nix strips them of these privileges when they are installed, then, how do they manage to function at all on nix?*

I'm certainly not going to dispute your wisdom on this topic. Hell, I am still trying to understand how nix even works. In any case, I believe we already need to weaken grsecurity's chroot hardening for nix builds to work at all, so one more dent in it here is probably acceptable to the wider world. And maybe one day someone will figure out how to fix it all in one go.

**Comment by joachifm** [comment]
@mrobbetts the suid problem has to be solved by the host OS. In NixOS we generate wrapper programs outside of Nix's purview (e.g., we have `/var/setuid-wrappers/su` which has the correct bits and in turn calls out to the "real" `su` binary). You'd have to do something similar to get suid executables to work in other environments.

**Comment by mrobbetts** [comment]
Theeeere we go. Thanks for your heroic patience explaining it to me! That all makes sense.

(Nix's solution sounds very elegant, also :)
