### ISSUE TITLE
Amdgpu error - X11 initialization failed

### ISSUE THREAD

**Issue by Mounium** [NixOS/nixpkgs#17504]
## Issue description

Switching to the unstable channel, display-manager.service can't start up due to (I think) amdgpu driver failure. 
It may be the dubious line:
`amdgpu 0000:01:00.0: Invalid ROM contents`

[journalctl -b with hardware.opengl.driSupport32Bit = true](https://github.com/NixOS/nixpkgs/files/401182/journal.txt)
[journalctl -b with hardware.opengl.driSupport32Bit = false](https://github.com/NixOS/nixpkgs/files/401200/journal64.txt)
[lsmod.txt](https://github.com/NixOS/nixpkgs/files/401181/lsmod.txt)

### Steps to reproduce

Switch to unstable channel and `nixos-rebuild switch --upgrade`, with the following configuration.nix (and likely with the same video card as I have Radeon R9 380):
[hardware-configuration.nix](https://github.com/NixOS/nixpkgs/files/401202/hardware-configuration.nix.txt)  I don't have any hardware relevant line in configuration.nix and other imported files, except for maybe `hardware.pulseaudio.enable = true`.

## Technical details

* System: 16.09pre87839.99f63b4 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre87839.99f63b4
* Videocard: Radeon R9 380 (tonga)

**Comment by vcunat** [comment]
Do I understand correctly that on 16.03 it works OK with the same config?

**Comment by vcunat** [comment]
@Mounium: contents of `/var/log/X.0.log` tends to be useful to debug X problems, assuming the startup gets far enough to create it.

**Comment by Mounium** [comment]
I don't know what may have caused it, but as of now I get full hardware acceleration on unstable.
