### ISSUE TITLE
kodi derivation not building

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#17516]
## Issue description

I guess activating vdpau makes a derivation in kodi so it skips the substitudes and builds it on my machine. but then in fails:

> 
CDDADirectory.cpp: In member function 'virtual bool XFILE::CCDDADirectory::GetDirectory(const CURL&, CFileItemList&)':
CDDADirectory.cpp:75:65: warning: '0' flag ignored with precision and '%i' gnu_printf format [-Wformat=]
     std::string strLabel = StringUtils::Format("Track %02.2i", i);
                                                                 ^
CDDADirectory.cpp:79:73: warning: '0' flag ignored with precision and '%i' gnu_printf format [-Wformat=]
     std::string path = StringUtils::Format("cdda://local/%02.2i.cdda", i);
                                                                         ^
CPP     xbmc/filesystem/CDDAFile.o
CPP     xbmc/filesystem/CurlFile.o
In file included from CurlFile.cpp:42:0:
DllLibCurl.h:30:16: error: conflicting declaration 'typedef struct XCURL::Curl_easy XCURL::CURL_HANDLE'
   #define CURL CURL_HANDLE
                ^
In file included from CurlFile.cpp:21:0:
CurlFile.h:30:16: note: previous declaration as 'typedef void XCURL::CURL_HANDLE'
   typedef void CURL_HANDLE;
                ^
In file included from /nix/store/idqyp6skbp1mp3w8xz3babcndcsnn6ax-curl-7.50.0-dev/include/curl/curl.h:2421:0,
                 from DllLibCurl.h:31,
                 from CurlFile.cpp:42:
/nix/store/idqyp6skbp1mp3w8xz3babcndcsnn6ax-curl-7.50.0-dev/include/curl/multi.h:55:27: error: conflicting declaration 'typedef struct XCURL::Curl_multi XCURL::CURLM'
 typedef struct Curl_multi CURLM;
                           ^
In file included from CurlFile.cpp:21:0:
CurlFile.h:31:16: note: previous declaration as 'typedef void XCURL::CURLM'
   typedef void CURLM;
                ^
make[1]: *** [/tmp/nix-build-kodi-16.1.drv-0/xbmc-16.1-Jarvis/Makefile.include:98: CurlFile.o] Error 1
make: *** [Makefile:420: xbmc/filesystem/filesystem.a] Error 2
builder for ‘/nix/store/hasrry3dy226j1kxn7vbr4fihnrvd3rl-kodi-16.1.drv’ failed with exit code 2

### Steps to reproduce
1.  add to your configuration:
```
  hardware.opengl.enable = true;
  hardware.opengl.extraPackages = [ pkgs.libvdpau-va-gl ];
```
2. nixos-rebuild switch --upgade

## Technical details

* System: 16.09pre87524.2ef1c6b (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre87916.8983df7"

**Comment by spiderbit** [comment]
btw I try to activate vdpau an my amd apu system with the free ati drivers, if thats the wrong way to do that or incomplete I would happy if somebody could tell me :)

doesnt it make sense to activate vdpau by default, and make a non vdpau build a derivation? kodi without vdpau makes not that much sense?

**Comment by womfoo** [comment]
This might not be an issue with vdpau but curl. More details in PR #17486.

**Comment by domenkozar** [comment]
fixed in master
