### ISSUE TITLE
Update to 22.05 beta errors on configuration.nix

### ISSUE THREAD

**Issue by est31** [NixOS/nixpkgs#175245]
## Issue description

I have the following overlay in my configuration.nix:

```nix
vim = super.vim_configurable.override {
  name = "vim";
  vimrcConfig.customRC = ''
    set mouse-=a
  ''; guiSupport = false; };
```

It worked fine on Nix OS 21.11, and before. When trying to update to the 22.05 beta, I am getting an error though:

```
error: anonymous function at /nix/store/r57zz35hfd9ag8jxcywxvhdyj8kgc7is-nixos-22.05beta67.6efc186e607/nixos/pkgs/applications/editors/vim/configurable.nix:1:1 called with unexpected argument 'name'
```

The changelog suggests I should use `customize` now, but if I replace it with customize:

```nix
vim = super.vim_configurable.customize {
  name = "vim";
  vimrcConfig.customRC = ''
    set mouse-=a
  ''; guiSupport = false; };
```

I get:

```
error: 'customize' at /nix/store/r57zz35hfd9ag8jxcywxvhdyj8kgc7is-nixos-22.05beta67.6efc186e607/nixos/pkgs/applications/editors/vim/plugins/vim-utils.nix:413:7 called with unexpected argument 'guiSupport'
```

I also tried going with `override` and removing `name`, but I get a similar error for `customRC` too, so it only works if I remove both. Is there a way I can both disable `guiSupport` and set `customRC`?

I'm filing this as a bug as this was suggested in IRC.

cc vim maintainers @lovek323 @equirosa

**Comment by pennae** [comment]
you're trying to do two different things here: changing how the derivation is built, and customizing the final vim package. try this:
```
vim = (super.vim_configurable.override { guiSupport = false; }).customize {
  name = "vim";
  vimrcConfig.customRC = ''
    set mouse-=a
  '';
};
```

**Comment by teto** [comment]
closing since no comment. Feel free to reopen

**Comment by est31** [comment]
I cannot remember if that trick worked or not, I'm sorry. But closing is fine I think.
