### ISSUE TITLE
Problem when trying to package nuitka

### ISSUE THREAD

**Issue by geck333** [NixOS/nixpkgs#17529]
## Issue description
I got a problem trying to package [nuitka python compiler] (http://www.nuitka.net) with python27Packages.buildPythonApplication.
I wrote appropriate shell.nix file (see below), and when i execuite "nuitka" command from nix-shell, it shows help, everything seems to be ok. But when i try to compile any python file, i see this error:

>[nix-shell:~/projects/test_project]$ nuitka test.py
/nix/store/13rkxv7rzmy1bkr1f6wsxiy2njxybgga-python-2.7.11/bin/python2.7: can't open file 'nuitka': [Errno 2] No such file or directory

### Steps to reproduce
1). create nix file with this content:
```
nuitka = pkgs.python27Packages.buildPythonApplication rec{
      version = "0.5.20";
      name = "Nuitka-${version}";
      src = pkgs.fetchurl {
        url = "https://pypi.python.org/packages/source/N/Nuitka/${name}.tar.gz";
        md5 = "b79beab5943d2b644b97e1439c873ecc";
        };
      doCheck = false;
  };
```
2). enter nix-shell
3). execute nuitka on any existing python file:
```
nuitka test.py
```

it will produce this error:
>[nix-shell:~/projects/test_project]$ nuitka test.py
/nix/store/13rkxv7rzmy1bkr1f6wsxiy2njxybgga-python-2.7.11/bin/python2.7: can't open file 'nuitka': [Errno 2] No such file or directory

## Technical details

* System: Ubuntu 14.04.4 LTS
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre79463.d88ae10

**Comment by danbst** [comment]
You have to patch sources for nuitka to work correctly. 

running `nuitka script.py` in fact runs python, which runs nuitka MainControl, which spawns new python and feeds it "nuitka" as argument. Trying strace on it, I see:

```
execve("/nix/store/nxy8hlcz7xc79mq9lfp89vbznimdnsxa-python-2.7.12/bin/python2.7", ["/nix/store/nxy8hlcz7xc79mq9lfp89"..., "-S", "nuitka", "file.py"], [/* 106 vars */]) = 0
readlink("nuitka", 0xbfc12c8e, 4096)    = -1 ENOENT (No such file or directory)
lstat64("/home/danbst/dev/nuitka", 0xbfc11be0) = -1 ENOENT (No such file or directory)
stat64("nuitka", 0xbfc14bb8)            = -1 ENOENT (No such file or directory)
stat64("nuitka", 0xbfc15b70)            = -1 ENOENT (No such file or directory)
open("nuitka", O_RDONLY|O_LARGEFILE)    = -1 ENOENT (No such file or directory)
```

At least, it tries to read in CWD. I have to symlink the actual python script to curdir:

```
[nix-shell:~/dev]$ ln -fs /nix/store/cyh9gh2b2qv7aa5kz5zpgr9my3x1rmmi-Nuitka-0.5.20/bin/.nuitka-wrapped nuitka
```

After that nuitka works and successfully compiles.

**Comment by FRidh** [comment]
@danbst , do you have any suggestion how this can truly be fixed? 

I'm also interested in Nuitka (https://github.com/NixOS/nixpkgs/pull/17695) and especially the standalone option which required patching `locateDLL('uuid')`.

**Comment by FRidh** [comment]
I've fixed it by not creating any wrapper; we don't need them anyway.

The issue seems solved, and there is a working (though not tested very well) Nuitka in Nixpkgs now.

**Comment by geck333** [comment]
By the way, problem with **uuid** do not require patching - i solved this by adding "**libuuid**" to the buildInputs in my shell.nix file.
