### ISSUE TITLE
zoom-us: Broken URL, latest version depends on unpackaged qt56.webengine

### ISSUE THREAD

**Issue by tadfisher** [NixOS/nixpkgs#17524]
## Issue description

Zoom doesn't appear to make older client versions available, so this doesn't work as they have bumped versions:

```
https://zoom.us/client/latest/zoom_${version}_x86_64.tar.xz
```

If you do a `curl -I` on the latest version available, you get a Cloudfront redirect which you can munge to get older client tarballs:

```
curl -I https://zoom.us/client/latest/zoom_2.0.57232.0713_x86_64.tar.xz | grep Location
Location: https://d11yldzmag5yn.cloudfront.net/prod/2.0.57232.0713/zoom_2.0.57232.0713_x86_64.tar.xz
```

I've attempted to simply update the version to the latest. Findings:
- They've switched Qt versions to 5.6
- They've switched from `qt55.webkit` to `qt56.webengine`
- `qt56.webengine` has yet to be packaged in master (it is currently stubbed)
### Steps to reproduce

`nixos-env -f '<checkout>' -i zoom-us`

```
trying https://zoom.us/client/latest/zoom_2.0.52458.0531_x86_64.tar.xz
curl: (22) The requested URL returned error: 403 Forbidden
error: cannot download zoom_2.0.52458.0531_x86_64.tar.xz from any mirror
builder for ‘/nix/store/3yffxab8lszqzkm2zvdls67921gd0j7m-zoom_2.0.52458.0
531_x86_64.tar.xz.drv’ failed with exit code 1                          
```
## Technical details
- System: 16.03
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: https://github.com/NixOS/nixpkgs-channels/commit/3f3d18c0174786baff0d9e378b2f014c4663ef27

**Comment by domenkozar** [comment]
@k0001

**Comment by k0001** [comment]
Thanks for reporting this @tadfisher. I'll try to get this updated.

**Comment by bdimcheff** [comment]
unless I'm misreading something, qt56.webengine is available now in unstable, and this should be able to be updated... I'll give it a shot later today if I find the time.

**Comment by bdimcheff** [comment]
hm ok maybe not... webengine doesn't actually build a usable package (see #16561) which I guess is maybe what @tadfisher meant by "stub"

**Comment by bdimcheff** [comment]
Has anyone tried binpatching the bundled binaries in the zoom package instead of depending on system qt?  That might be an easier solution, and if you're already using binaries it seems like not that much of a sacrifice to just use all the binaries...

**Comment by danbst** [comment]
https://github.com/NixOS/nixpkgs/pull/26446
close this
