### ISSUE TITLE
par derivation

### ISSUE THREAD

**Issue by jljox** [NixOS/nixpkgs#17521]
## Issue description
I need the par utility so that I can work on Haskell projects using Vim.

### Steps to reproduce
N/A

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/commit/526291231b4f57386b841c8ff148546ae1e4ce62
