### ISSUE TITLE
Can't get module's options to be type-checked

### ISSUE THREAD

**Issue by dsferruzza** [NixOS/nixpkgs#17536]
Hi!

## Issue description

I'm trying to create a module that exposes some options.

I want to add some checks to an option that can contains a list of ints, but the `check` function doesn't seem to be called when building my configuration.

### Steps to reproduce

*/etc/nixos/configuration.nix*:
```nix
# ...
{
  imports =
      [ # Include the results of the hardware scan.
        ./hardware-configuration.nix
        ./test-definition.nix
      ];
  # ...
}
```

*/etc/nixos/test-definition.nix*:
```nix
{ config, lib, pkgs, ... }:

{
  imports = [
    ./test.nix # This is where I provide values for the option defined in this file
  ];

  options = with lib; {
    test.someOption = mkOption {
      type = with types; addCheck (types.listOf types.int) (x: builtins.trace "should fail" false);
      #                                                     ^ This check should always fail
    };
  };

  config = lib.mkIf config.test.someOption {
    # Whatever
  };
}
```

*/etc/nixos/test.nix*:
```nix
{
  test.someOption = "string";
}

```

When running `nixos-rebuild build --show-trace`, I don't get any error.
Even without the `types.addCheck` in the definition, no error whereas I provide a string value instead of an int.

Also, the trace doesn't appear, which means my check function is never called.

Any idea?
Am I doing something wrong?

## Technical details

* System: `16.03.1171.9cb194c (Emu)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.03.1171.9cb194c"`

**Comment by ericsagnes** [comment]
The `mkIf` content block must not be empty to get its condition evaluated (and type-checked).

This can be easily verified by setting `config` to the following:

```
config = mkIf (builtins.abort "unevaluated") {};
```

So, for example, if you change the `config` declaration to:

```
  config = lib.mkIf (config.test.someOption != []) {
    environment.systemPackages = [ pkgs.hello ];
  };
```

`config.test.someOption` will be evaluated and type-checked:

```
building Nix...
building the system configuration...
error: The option value `test.someOption' in `/tmp/configuration.nix' is not a list of integers.
```
Note: the `trace` contents doesn't appear because the list type-check fails first and abort the evaluation.

**Comment by dsferruzza** [comment]
Hi!

Sorry it took me so long to answer :/
I made some tests and it seems to work just as you said!
Thanks a lot!
