### ISSUE TITLE
Grub should check if kernel/initrd/init exist while generating the grub.cfg

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#17531]
It can happen that `install-grub.pl` generates invalid grub entries and results into unbootable system. We should sanity check if referenced files exist upon install.

Fixes https://github.com/NixOS/nixpkgs/issues/14999

**Comment by domenkozar** [comment]
cc @wkennington @edolstra

**Comment by wkennington** [comment]
It might be worth just copying the kernel always.

**Comment by dezgeg** [comment]
`grub-mkrelpath` and `grub-fstest` sound like they could be useful here.

**Comment by domenkozar** [comment]
@dezgeg are you willing to take this on? :)

**Comment by domenkozar** [comment]
Well, I'll try to debug this further today as it's really annoying on servers.

**Comment by domenkozar** [comment]
I wanted to implement this using `findmnt`, but it's tricky to filter our `/nix/store` bind mount:

```
$ findmnt --target /nix/store
TARGET     SOURCE                FSTYPE OPTIONS
/nix/store /dev/dm-0[/nix/store] btrfs  ro,noatime,ssd,space_cache,subvolid=5,subvol=/nix/store
```

**Comment by domenkozar** [comment]
@wkennington I think it's best if we just symlink the kernels if `/boot/` is the same as filesystem as `/nix/store`. And otherwise copy.

**Comment by domenkozar** [comment]
On second thought, should `grub-install` really inspect current state of mounts to determine the booting logic? That really sounds error prone as configuration may be different than the state.

**Comment by domenkozar** [comment]
Here's how the logic should go, but it requires a substantial refactoring:

- determine if `/nix/store` and `/boot/` are the same filesystem
- if yes, use symlinks, otherwise copy the kernels
- figure out what the device for boot mountpoint is
- check if boot device + path really exist
- generate the grub menu

**Comment by dezgeg** [comment]
There is a comment: `240     # FIXME: should use grub-mkconfig.`. I think that could might help in the long term, as GRUB probably has more battle-tested code e.g. for the "figure out what the device for boot mountpoint is" part.

**Comment by therealpxc** [comment]
What's the simplest way to recover from this? I'm in the process of doing so but the process I have taken is pretty messy (potentially destructive?).

I booted the system from some live media I could find (non-NixOS, incidentally), mounted the system in a chroot (as in the [install from linux](https://nixos.org/wiki/How_to_install_NixOS_from_Linux) instructions, changed my configuration to require a new kernel so it would actually build the thing, ran nixos-rebuild switch and rebooted. (Not yet sure if this will work, still in progress.)

Is the best way to do nixos-install again without changing anything on the filesystem?

**Comment by domenkozar** [comment]
I edited the grub manually to boot and then redeployed nixos cofrectly.

**Comment by samueldr** [comment]
Closing while triaging, I don't think this specific 2016 issue is an issue anymore.

@domenkozar: feel free to re-open if you are hitting what you think is the same failure. I've never heard of anything like that since I've begun using NixOS in early 2017. I believe the scripts and our handling of boot files also have changed a lot since.

Anyone else: feel free to cross-reference this issue in a new issue if you think it is relevant to any issue you may be encountering related to GRUB and the way we handle boot entries.
