### ISSUE TITLE
systemd-tmpfiles-setup failes on reiserfs (and probably other filesystems)

### ISSUE THREAD

**Issue by jekor** [NixOS/nixpkgs#17544]
## Issue description

This is a bug in systemd (https://github.com/systemd/systemd/issues/560) but the systemd maintainers have declined to fix it. It results in an incorrect system state (incorrect `/dev/null` permissions for one). Can we create a workaround for it in NixOS?

### Steps to reproduce

Mount root on a reiserfs partition (or any other partition that doesn't support ACLs). Watch `systemd-tmpfiles-setup` fail with the message: `ACL operation on "/var/log/journal" failed: Invalid argument`.

## Technical details

* System: 16.09.git.ad0a9f5 (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.03.1083.d745044"

**Comment by joachifm** [comment]
For convenience, this is the [suggested work-around](https://github.com/systemd/systemd/issues/560#issuecomment-126340181):
> If you want to disable it, simply symlink /dev/null to /etc/tmpfiles.d/journal-nocow.conf. This will mask the file, as tmpfiles.d follows the usual rule that files in /etc override similar named files in /usr/lib and can be masked away by symlinking /dev/null over it. See tmpfiles.d(5) for more info.

**Comment by jekor** [comment]
@joachifm Thanks for the link.

The suggested work-around does not appear to work:

```
# ls -l /etc/tmpfiles.d/journal-nocow.conf
lrwxrwxrwx 1 root root 9 Aug  8 13:39 /etc/tmpfiles.d/journal-nocow.conf -> /dev/null
```

```
[/etc/tmpfiles.d/journal-nocow.conf:1] Unknown modifiers in command 'hostname'
ACL operation on "/var/log/journal" failed: Invalid argument
```

**Comment by jekor** [comment]
I was reading through the original bug in more detail and I saw that they did actually merge a downgrade from error to warning (https://github.com/systemd/systemd/pull/663) at one point for chattr() failure, but not for ACL failure. This is explains why the linked workaround doesn't work. I'll report the issue upstream. In the meantime, here's a workaround for NixOS:

```
  environment.etc = {
    "tmpfiles.d/systemd.conf" = pkgs.lib.mkForce {
      source = pkgs.runCommand "systemd.conf" {} ''
        sed -s 's/^[aA]\+.*$//' < ${pkgs.systemd}/example/tmpfiles.d/systemd.conf > $out
      '';
    };
  };
```
