### ISSUE TITLE
vam seems to fail to recognize plugin overrides

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#175493]
### Describe the bug

Consider an overlay like this:

```
self: super: {
  vimPlugins = super.vimPlugins // {
    nvim-treesitter-full = self.vimPlugins.nvim-treesitter.withPlugins (_:
      self.tree-sitter.allGrammars);
  };

  neovim = self.callPackage ({ vimPlugins }: super.neovim.override {
      vimAlias = true;
      # Python2 is no longer supported.
      withPython = false;
      configure = {
        vam = {
          knownPlugins = vimPlugins;
          pluginDictionaries = [{ name = "nvim-treesitter-full"; }];
        };
        customRC = ''
          lua <<LUA
            require('nvim-treesitter.configs').setup {
              highlight = {enable = true},
              indent = {enable = true},
            }
          LUA
        '';
      };
    }
  ) {};
}
```

It used to work just fine until quite recently, but today it will ignore the `override` and only use the original `nvim-treesitter` plugin, without any of the grammars. Any `overrideAttrs` will also be ignored, such as in this case:

```
    nvim-treesitter-full = ((self.vimPlugins.nvim-treesitter.withPlugins (plugins:
      self.tree-sitter.allGrammars)
    ).overrideAttrs (old: {
      version = "2022-03-18";
      src = self.fetchFromGitHub {
        owner = "nvim-treesitter";
        repo = "nvim-treesitter";
        rev = "fd92e70c69330dd8f2f6753d3d987c34e7dacd24";
        sha256 = "sha256-hTs9eH9DERlMnUK9dHlJPU6jNZWrmnGgR4l6rIkfW+E=";
      };
    }));
```

If you look at the generated vim config, you will find that a 2022-05-13 version is used anyway. Running `vimPlugins.nvim-treesitter.withPlugins (_: tree-sitter.allGrammars);` in a `nix repl` produces a package as expected.

### Steps To Reproduce
1. Apply the overlay above

### Expected behavior

`parsers/` directory is populated properly and `overrideAttrs` is not ignored.

**Comment by sheeaza** [comment]
same as vim-plug,
the vim package works fine.

**Comment by teto** [comment]
do you really need vam ? I deprecated vam for reasons explained in https://github.com/NixOS/nixpkgs/pull/179039 so your best bet is to switch to boring native vim packages. The following code should work:
```
      withPython = false;
      configure = {
        packages.toto = {
          start = [{ plugin = nvim-treesitter-full; }];
        };
        customRC = ''
          lua <<LUA
            require('nvim-treesitter.configs').setup {
              highlight = {enable = true},
              indent = {enable = true},
            }
          LUA
        '';
      };
```

**Comment by nagisa** [comment]
I no longer use vam, and I can’t check right now if moving away from it fixed the problem with ignored overrides etc.
