### ISSUE TITLE
Bump digikam to 5.1

### ISSUE THREAD

**Issue by clefru** [NixOS/nixpkgs#17552]
Digikam 5.0 got released. Packaging-wise that's not a simple version bump as digikam removed most of its KDE4 dependencies and ported to Qt5. For reference https://quickgit.kde.org/?p=digikam-software-compilation.git&a=blob&f=DEPENDENCIES

As 4.12 isn't really usable for me, I am offering 0.1 Bitcoin (~56$ ATM) as reward for the pull request that closes this issue, claimable till 2016/10/01. Please let me know if offers like these are inappropriate on the issue tracker.

**Comment by vcunat** [comment]
/cc maintainers @cillianderoiste, @viric.

> Please let me know if offers like these are inappropriate on the issue tracker.

On the contrary, I appreciate such bounties. Several months ago, I tried living on nix-related freelancing, but I stopped as it didn't seem very sustainable over long term.

**Comment by clefru** [comment]
@vcunat: Thanks for the clarification!

If I may update the bounty, digikam 5.1 just saw the light of day, see https://www.digikam.org/node/756. Packaging-wise, it should be the same as 5.0.

**Comment by the-kenny** [comment]
Got it working here with most optional features enabled. Just need some more time to get the geo-stuff (based on marble) working.

@clefru may I ask what use case made `4.12` unusable for you?

**Comment by clefru** [comment]
@the-kenny I struggled for some time to have digikam delete pictures for me because the kio-slave for trash:/ wouldn't launch. "nix-env -i kderuntime" into my user's nix-env eventually solved that problem as apparently it had nothing to do with digikam's own dependencies. I expect KDE5 to be much more of a hassle free experience, so I am committed to my bounty :)

**Comment by the-kenny** [comment]
Good news then! I'm not running any desktop environment either, and `nix-env -i digikam5` just works™. The new non-kde trash also works flawlessly (it just stores trashed files in `<dbdir>/.dtrash`).

I'll ping you as soon as the PR gets merged.

**Comment by the-kenny** [comment]
One more thing: I noticed one bug that I couldn't solve yet: After the first start, I don't see any icons in the UI. This is solved by going into `Digikam Settings -> Miscellaneous -> Icon Theme` and selecting `Breeze`

**Comment by edolstra** [comment]
What is `<dbdir>/.dtrash` exactly? Does that directory ever get cleaned up?

**Comment by the-kenny** [comment]
Digikam has the concept of `collections` - a directory tree with photos in it. The `~/.dtrash` directory is in the root of that tree. It also provides an UI to show the trashed photos and to delete them permanently.

**Comment by clefru** [comment]
Thanks @the-kenny for your work! I've sent you your reward :).
