### ISSUE TITLE
Where is latexmk?

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#17550]
I'm trying to figure out how to install latexmk. I assume it's in here somewhere, right?

**Comment by chris-martin** [comment]
Ah nevermind, followed https://nixos.org/wiki/TexLive_HOWTO and got it from `texLiveAggregationFun`

**Comment by vcunat** [comment]
We do have `texlive.latexmk`; `texlive.*` is described on that page, too. Old `texLive*` hasn't been maintained for many months now, most likely.

**Comment by chris-martin** [comment]
I tried that approach first, but didn't get the `latexmk` executable.

**Comment by vcunat** [comment]
@chris-martin: what did you try?
```
$ nix-build -E 'with import ./. {}; texlive.combine { inherit (texlive) scheme-basic latexmk; }' -Q
$ ls -l ./result/bin/latexmk
-r-xr-xr-x 1 root root 555 Jan  1  1970 ./result/bin/latexmk
```

**Comment by chris-martin** [comment]
This may have been one of my problems: the derivation fails to build if `scheme-basic` is omitted. I left it out because scheme didn't sound relevant to my build.

```
> nix-build -E 'with import ./. {}; texlive.combine { inherit (texlive) latexmk; }'
these derivations will be built:
  /nix/store/73zry2hji0vd85kpc7qz3nmpq4rrja16-texlive-combined-2015.drv
building path(s) ‘/nix/store/dli7dcv469jm819dv5rrqvzlmbdbkpgl-texlive-combined-2015’
created 2 symlinks in user environment
/nix/store/62h3c4d6rdnlxichixqg8h9jxi8nhxk0-stdenv/setup: line 841: cd: ./share/texmf/web2c/: No such file or directory
builder for ‘/nix/store/73zry2hji0vd85kpc7qz3nmpq4rrja16-texlive-combined-2015.drv’ failed with exit code 1
error: build of ‘/nix/store/73zry2hji0vd85kpc7qz3nmpq4rrja16-texlive-combined-2015.drv’ failed
```

**Comment by chris-martin** [comment]
I just realized: "scheme" isn't talking about the programming language, is it.

**Comment by chris-martin** [comment]
The next problem is that `scheme-full` is broken :(

`output path ‘/nix/store/ayq32cfk92kiysywxnb35xfhsm4j3wbq-2up.tar.xz’ has md5 hash ‘7bb1a159a6e50d7cb807c58f471e360e’ when ‘6160fbc7ab71be778081500b908d2648’ was expected`

This is in channel 16.03

**Comment by vcunat** [comment]
Yes, that's because upstream updated archived files in-place; some smaller schemes are still likely to work. There's WIP to improve that: #16391.

**Comment by vcunat** [comment]
And, on master/unstable there were some ad-hoc updates of individual packages, so the hash mismatches should be less likely.
