### ISSUE TITLE
mesa's vdpau is broken

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#17559]
## Issue description

```
$ DISPLAY=:0 vdpauinfo
display: :0   screen: 0
Failed to open VDPAU backend libvdpau_r600.so: cannot open shared object file: No such file or directory
Error creating VDPAU device: 1
```

### Excepted result

vdpauinfo and other apps find the libvdpau_r600.so file and vdpau is working.

### Steps to reproduce
1. in config:
```
  environment.systemPackages = with pkgs; [
    libvdpau-va-gl vaapiVdpau glxinfo vdpauinfo
  ];
  hardware.opengl.enable = true;
  hardware.opengl.extraPackages = [ pkgs.libvdpau-va-gl pkgs.vaapiVdpau pkgs.vaapiIntel];
  services.xserver.videoDrivers = [ "ati" ];
```

2. nixos-rebuild switch (--upgrade)
3. optionaly restart display-manager
4. DISPLAY=:0 vdpauinfo

## Technical details

* System: latest nixos-unstable

**Comment by spiderbit** [comment]
$ DISPLAY=:0 vainfo
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /run/opengl-driver/lib/dri/r600_drv_video.so

$ ls /run/opengl-driver/lib/dri/r
r200_dri.so      r300_dri.so      r600_dri.so      radeon_dri.so    radeonsi_dri.so  

does the vainfo and vdpauinfo tools refer to the wrong files?

**Comment by spiderbit** [comment]
k it seems to work in reality, kodi only uses 40% cpu while I watch a fullhd video before it did use >100% cpu.

so only that info tools seem to be broke.

**Comment by vcunat** [comment]
There's something fishy going on. Both on 16.03 and master our `${mesa_drivers}` contains lots of broken vdpau-related symlinks. @abbradar: you looked into this recently in #12616, any ideas? Is it "right" that there's only `libvdpau_gallium.so.*` and thus we should just delete the symlinks?

**Comment by vcunat** [comment]
I suspect bugs in 1a52fdc3c6.

**Comment by vcunat** [comment]
Yes, it looks like it's all supposed to be symlinked to that single library.

**Comment by spiderbit** [comment]
dont forget the va-info too, you renamed the bug to no vdpau-info..., but vainfo does also not work. I think it supposed to work, too? Right, even its a bit confusing cause normaly vainfo should show somethnig, too if I remember it right from fedora?

**Comment by vcunat** [comment]
I changed it according to your comments and before I noticed the broken symlinks. Now I think/hope restoring those should fix all the apps.

**Comment by vcunat** [comment]
The broken symlinks are now fixed in staging and 16.03. @spiderbit: thanks!

**Comment by vcunat** [comment]
I forgot to add that `vdpauinfo` works again.

**Comment by spiderbit** [comment]
funny enough I seem to have the exact same problem again, I do not even remember what I changed or when it happend just recently my videos startet to lag, so I checked again on the same machine vdpauinfo.

can I somehow reopen that bug?

**Comment by spiderbit** [comment]
Ok false alarm I guess, I am not shure what happend but after a rebuild --upgrade at least that info tools give a sane output, I will make further testings but for now the problem seems gone in latest upstream.
