### ISSUE TITLE
redis-desktop-manager broken in unstable

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#17563]
Last successful build in 2016-07-15 https://hydra.nixos.org/job/nixpkgs/trunk/redis-desktop-manager.i686-linux
Last successful build in 2016-07-14 https://hydra.nixos.org/job/nixpkgs/trunk/redis-desktop-manager.x86_64-linux

cc @cstrahan

**Comment by domenkozar** [comment]
fixed
