### ISSUE TITLE
`nixos-rebuild switch` switches out of graphical mode

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#17560]
## Issue description
Just after running `nixos-rebuild switch` on recent nixos-unstable versions, the desktop environment becomes inaccessible, with an empty dark grey area resembling that seen on boot and shutdown taking focus. Any key strokes sent to it are printed out (with backspace printing previous characters, prefixed with `\`, in reverse), and ctrl-alt-delete causes a reboot. Everything is fine after rebooting, and the switch has taken effect.

This has happened for the last two times I have run `nixos-rebuild switch`. The first time was Wednesday (2016-08-03), I think.

I will do some more testing when this issue has been posted, since testing this usually causes a reboot of the machine I'm writing on.

[configuration.nix](http://nixpaste.lbr.uno/WOBmK-xs)

### Steps to reproduce
`sudo nixos-rebuild switch` and wait.

## Technical details

* System: `16.09.git.d0dbf56 (Flounder)`
* Nix version: `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.09.git.d0dbf56"` (nixos-unstable)

**Comment by laMudri** [comment]
It seems that what's happening is that the X session is being killed (thanks to kmicu for pointing that out).

**Comment by laMudri** [comment]
I've only managed to reproduce this by reducing my configuration.nix to just
```nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
  ];

  boot = {
    loader.grub = {
      enable = true;
      version = 2;
      device = "/dev/sda";
    };
    tmpOnTmpfs = true;
  };

}
```
and then running `sudo nixos-rebuild test`. It seems to only occur after large changes, for some definition of “large” which includes replacing the configuration.nix file and updating nixpkgs.

**Comment by vcunat** [comment]
Normally `nixos-rebuild` never restarts the `display-manager.service`, exactly to keep the X session. However, I've seen e.g. xfce session paralyzed after dbus.service gets restarted.

I personally use `nixos-rebuild switch` only for "smaller" changes and tend to prefer `nixos-rebuild boot` overall. (Actually I prefer to manage almost all packages I use by `nix-env`, but that's another story.)

**Comment by vcunat** [comment]
Could this be another instance of https://github.com/NixOS/nixpkgs/issues/18158 and thus fixed recently?

**Comment by laMudri** [comment]
I think it is, yes.

**Comment by rasendubi** [comment]
Closing as it seems to be fixed. Feel free to reopen if the issue still exists.
