### ISSUE TITLE
RNDC does not work for bind+dhcpd setups on NixOS 22.05

### ISSUE THREAD

**Issue by illustris** [NixOS/nixpkgs#175624]
### Describe the bug
Up to NixOS 21.11, it was possible to have DHCPD update records on Bind through RNDC.

```nix
services.dhcpd4 = {
  enable = true;
  interfaces = [ "eth0" ];
  extraConfig = ''
    include "/etc/bind/rndc.key";
    .
    .
    # DNS zones to update
    zone 10.168.192.in-addr.arpa. {
      primary 192.168.10.2;
      key "rndc-key";
    }
```

This was broken by https://github.com/NixOS/nixpkgs/commit/59e51f359bb8819343fa1159af1ccddf70c7f87d

Previously, dhcpd started as root and dropped privileges after reading configs. The rndc key file generated by bind defaults to `600` with `named:root` as owner and group. Now that dhcpd starts as an unprivileged dynamic user, it can't read the rndc key.

### Steps To Reproduce
1. add `include "/etc/bind/rndc.key";` to `services.bind.extraConfig`
2. enable bind and dhcpd4

### Expected behavior
dhcpd4 starts

### Logs
```
dhcpd4[3625306]: Internet Systems Consortium DHCP Server 4.4.3
dhcpd[3625306]: Internet Systems Consortium DHCP Server 4.4.3
dhcpd[3625306]: Copyright 2004-2022 Internet Systems Consortium.
dhcpd[3625306]: All rights reserved.
dhcpd[3625306]: For info, please visit https://www.isc.org/software/dhcp/
dhcpd4[3625306]: Copyright 2004-2022 Internet Systems Consortium.
dhcpd4[3625306]: All rights reserved.
dhcpd4[3625306]: For info, please visit https://www.isc.org/software/dhcp/
dhcpd4[3625306]: Can't open /etc/bind/rndc.key: Permission denied
dhcpd[3625306]: Can't open /etc/bind/rndc.key: Permission denied
dhcpd[3625306]: If you think you have received this message due to a bug rather
dhcpd[3625306]: than a configuration issue please read the section on submitting
dhcpd[3625306]: bugs on either our web page at www.isc.org or in the README file
dhcpd[3625306]: before submitting a bug.  These pages explain the proper
dhcpd[3625306]: process and the information we find helpful for debugging.
dhcpd[3625306]: exiting.
dhcpd4[3625306]:
dhcpd4[3625306]: If you think you have received this message due to a bug rather
dhcpd4[3625306]: than a configuration issue please read the section on submitting
dhcpd4[3625306]: bugs on either our web page at www.isc.org or in the README file
dhcpd4[3625306]: before submitting a bug.  These pages explain the proper
dhcpd4[3625306]: process and the information we find helpful for debugging.
dhcpd4[3625306]:
dhcpd4[3625306]: exiting.
systemd[1]: dhcpd4.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: dhcpd4.service: Failed with result 'exit-code'.
systemd[1]: Failed to start DHCPv4 server.
```

### Additional context
I see two ways to fix the issue:
1. revert the [revert commit](https://github.com/NixOS/nixpkgs/commit/59e51f359bb8819343fa1159af1ccddf70c7f87d) that un-reverted the [previous revert commit](https://github.com/NixOS/nixpkgs/commit/0e5dab9db7d183e762310478fc1da46a7db58778) that reverted [the commit that introduced the issue](https://github.com/NixOS/nixpkgs/commit/dd9883b2fbd2b9ea01d53654d383b29b4d68d05a).
2. change the bind prestart script at https://github.com/NixOS/nixpkgs/blob/49a2bcc6e2065909c701f862f9a1a62b3082b40a/nixos/modules/services/networking/bind.nix#L255 to set the permission of `/etc/bind/rndc.key` to be world-readable.

1 is of course the preferred option, as 2 will allow any unprivileged user to read the rndc key and update records on bind.

### Notify maintainers
@vcunat  @rnhmjoj @globin 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/store/4fq7hg1gi3fv8gwla444m87b8vbydkiv-lqd54dk5jrqqs4sdfp9qz9xa7a0lli3n-nixpkgs-src`
```

**Comment by rnhmjoj** [comment]
> Previously, dhcpd started as root and dropped privileges after reading configs.

Yes, this was documented in the [release notes](https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-22.05-incompatibilities).

> The rndc key file generated by bind defaults to 600 with named:root as owner and group. Now that dhcpd starts as an unprivileged dynamic user, it can't read the rndc key.

The best solution would be to just change the user/group of this file. 
If for some reason you can't do that, I would do, in order of preference,

  1. Add an ACL rule to give the dhcp user read access;
  2. Add the `CAP_DAC_READ_SEARCH` capability to bypass the file read check
  3. Run dhcpcd as root (you can still do this by `changing systemv.services.dhcpd6`)

**Comment by illustris** [comment]
Makes sense. But it would be nice to fix at the module level. I'm not too familiar with all of systemd's unit options, but BindReadOnlyPaths or readOnlyPaths seem like they might work.

**Comment by rnhmjoj** [comment]
> Makes sense. But it would be nice to fix at the module level. 

Do you mean the bind module? If this is a standard setup, yes, we may add an option to configure named and setting that file permissions.

If you mean reverting dhcpd to running as root, no. This is working an intended: I've enabled the systemd hardening options for dhcpd as part of the trend of reducing the amount of services running with elevated privileges.

**Comment by illustris** [comment]
> If you mean reverting dhcpd to running as root

Oh no, I wasn't talking about reverting to DHCP as root. I went over the PR and related discussions, the decision to harden services makes sense.

> Do you mean the bind module? 

Not exactly... Changing the permissions of the file in the bind module is less preferred because
1. I'm only familiar with dhcpd, but things other than dhcpd might want to use the rndc key to update records.
2. the dhcpd user will not exist if only bind is enabled

I was suggesting adding bindReadOnlyPaths/readOnlyPaths to the dhcpd module. Does that sound good?

**Comment by rnhmjoj** [comment]
> I was suggesting adding bindReadOnlyPaths/readOnlyPaths to the dhcpd module

Sorry, I'm still not sure what you're proposing. Do you mean adding a covenience option like `services.dhcpd6.readOnlyPaths` that maps to `systemd.services.dhcpd6.bindReadOnlyPaths` or something like
```
// optionalAttrs (config.services.bind.enable)
  {
    services.systemd.dhcpd6.bindReadOnlyPaths = [ "/etc/bind/rndc.key" ];
  }
```
to the dhcpd module?

At any rate, it's probably easier to review a PR than discussing this here.

**Comment by illustris** [comment]
> `services.systemd.dhcpd6.bindReadOnlyPaths = [ "/etc/bind/rndc.key" ];`

Yes. I was hoping this would be enough, but it looks like BindReadOnlyPaths preserves the file permissions of the source file.

https://github.com/NixOS/nixpkgs/pull/176274

All this does is expose rndc.key as a read-only bind mount with the same file permissions as before. the bind user will not have access to it.

**Comment by illustris** [comment]
Closing this as I'm switching to kea for DHCP. Anyone else having this issue can get around it by setting permissionsstartonly to true for DHCPD, and copying the bind key to /var/lib/dhcpd in execstartpre. This is a crude imitation of the old behavior with more steps, but it gets the job done. I still don't get the point of running dhcpd as an unprivileged user when it already drops privileges and runs as the user specified by the `-user` flag after reading configs and binding sockets as root.
