### ISSUE TITLE
compiz broken in unstable

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#17561]
last successful build was in 2016-03-06

https://hydra.nixos.org/job/nixpkgs/trunk/compiz.i686-linux
https://hydra.nixos.org/job/nixpkgs/trunk/compiz.x86_64-linux

cc @7c6f434c

**Comment by matthewbauer** [comment]
fixed

**Comment by arconix** [comment]
Awesome! Thanks guys.
