### ISSUE TITLE
bootstrap-tools in libidn2's closure

### ISSUE THREAD

**Issue by misuzu** [NixOS/nixpkgs#175693]
### Describe the bug
libidn2 package has the bootstrap-tools package in it's closure for some reason.

```bash
$ nix why-depends /nix/store/c56lvnhbyb9pf5p7c7qfj7ki8b3r0dqv-netdata-1.32.1 /nix/store/p4s4jf7aq6v6z9iazll1aiqwb34aqxq9-bootstrap-tools
/nix/store/c56lvnhbyb9pf5p7c7qfj7ki8b3r0dqv-netdata-1.32.1
└───/nix/store/rdsmqcan6ws916mkqcqx92qdj0514680-libidn2-2.3.2-dev
    └───/nix/store/82jnccxb8djlhgzwb87d3jk01awaw9kb-libidn2-2.3.2-bin
        └───/nix/store/p4s4jf7aq6v6z9iazll1aiqwb34aqxq9-bootstrap-tools
```

```bash
$ nix path-info -shr /nix/store/c56lvnhbyb9pf5p7c7qfj7ki8b3r0dqv-netdata-1.32.1 | LC_ALL=C sort -k2 -hr | head
/nix/store/p4s4jf7aq6v6z9iazll1aiqwb34aqxq9-bootstrap-tools                      126.5M
/nix/store/hpppiam2slc5x9jbf7g67051bygf0bzi-perl-5.34.1                           52.9M
/nix/store/c56lvnhbyb9pf5p7c7qfj7ki8b3r0dqv-netdata-1.32.1                        31.1M
/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210                        29.2M
/nix/store/c2785a9h9138impj7wjk16g6md0wg2p1-netdata-go.d.plugin-0.31.0            27.6M
/nix/store/j3jkxwyidvqyzm6pfsscgga9rzqqh9yk-freeipmi-1.6.9                        13.8M
/nix/store/d86ic2p5ym09zrh8h06px677bifah21s-file-5.41                              7.2M
/nix/store/g9x3cm8wdmpm86pyiff6arx8skmdwkn7-gcc-11.3.0-lib                         6.1M
/nix/store/8jj82lv4a1wd2vlvf0ppk3vxnqg619j8-util-linux-minimal-2.37.4-bin          6.1M
/nix/store/sysqj1krpfqw1mjph9x7i5sniw07rn24-shadow-4.11.1                          4.0M
```

### Expected behavior
No bootstrap-tools in system closure unless really needed.

### Additional context
Something happened with libidn2 between 437e1f69be786bfbd06a611530bbd2fac6af1d35 and 500a8ffd96962c672a08ba39e6a783234d907591.

https://hydra.nixos.org/build/111559400#tabs-details
https://hydra.nixos.org/build/112044947#tabs-details

### Notify maintainers

@fpletz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.41, NixOS, 22.11 (Raccoon), 22.11.20220526.83658b2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/store/ny7x54058ki7k1d3ny0jx5h6kw926mxv-source`
```

**Comment by trofi** [comment]
A bit of debugging:

depgraph (via `$ nix-store --query --graph $(nix-build -A libidn2) | dot -Tsvg > /tmp/depgraph.svg`): 
![depgraph](https://user-images.githubusercontent.com/226650/171346416-b57be050-0765-4f0c-a515-b4fc27ddbb18.svg)

Confirm that `libidn2.bin` is linked against bootstrap glibc:

```
$ nix path-info -rsh $(nix-build -A libidn2.bin) |& fgrep bootstrap
these 2 derivations will be built:
  /nix/store/xvrq6jbjaxs7flgaa9xhw2iyxpwa9rkw-libunistring-1.0.drv
  /nix/store/r50vgyqgwpa5xmhl9f00fq3ysa5cd067-libidn2-2.3.2.drv
/nix/store/i3ibpx67yncp4w4mpkf5pwvjjsd0aqln-bootstrap-tools                      126.5M
/nix/store/39k40hf9z4wr5wac5xbnznza1ym2f8kz-bootstrap-stage0-glibc-bootstrap     608.0
```

We explicitly use bootstrap glibc (via interpreter):

```
$ LANG=C readelf -a /nix/store/v7zppsi2kmj2zzrjr1mjaqvl2p7sv1jh-libidn2-2.3.2-bin/bin/idn2 |& fgrep bootstrap
      [Requesting program interpreter: /nix/store/39k40hf9z4wr5wac5xbnznza1ym2f8kz-bootstrap-stage0-glibc-bootstrap/lib/ld-linux-x86-64.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/gymz5nlyi567m9rbi6gmqc19glgvldsw-libidn2-2.3.2/lib:/nix/store/7mm9v9csgjhhkrblgv180ns024997sg7-libunistring-1.0/lib:/nix/store/gymz5nlyi567m9rbi6gmqc19glgvldsw-libidn2-2.3.2/lib64:/nix/store/39k40hf9z4wr5wac5xbnznza1ym2f8kz-bootstrap-stage0-glibc-bootstrap/lib:/nix/store/i3ibpx67yncp4w4mpkf5pwvjjsd0aqln-bootstrap-tools/lib]
```

Looking at our [bootstrap steps](https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/linux/default.nix#L251) we carefully thread `libidn2` built at `stage2` through `stage3`, `stage4` and `final` as it's a low level dependency of `glibc`. We carefully mangle references in `$out` output (libraries), but not the `$bin` one.

`netdata` happens to retain `libidn2.bin` reference.

**Comment by trofi** [comment]
Proposed closure shrinking for `netdata` as https://github.com/NixOS/nixpkgs/pull/175719.

It does not fix underlying `libidn2.bin` reference. But at least it does not pull in too much.

**Comment by vcunat** [comment]
> Something happened with libidn2

glibc got dependency on libidn2, instead of their not-very-good bundled code.  That was in 2aea16c4d6.

I propose yet another hack in PR https://github.com/NixOS/nixpkgs/pull/175785

**Comment by misuzu** [comment]
I guess this is fixed now.
