### ISSUE TITLE
Some of the default fonts are nonfree, and not marked as such

### ISSUE THREAD

**Issue by cmfwyp** [NixOS/nixpkgs#17571]
The Luxi fonts, distributed as [fontbhttf](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/default.nix#L262) in X.Org, are distributed under a license that does not permit redistribution with modification. For that reason, Debian and Fedora remove them from the X.Org distribution.¹ ²

These fonts are packaged in Nixpkgs as `pkgs.fontbhttf`, not marked as nonfree, and included in the default font paths.

The license meta-attribute for the font-bh-ttf attribute should be set to `licenses.unfreeRedistributable` and fontbhttf should be removed from [`nixos/modules/config/fonts/fonts.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/fonts/fonts.nix#L25), [`pkgs/development/libraries/fontconfig/make-fonts-cache.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/fontconfig/make-fonts-cache.nix#L1), [`pkgs/development/libraries/fontconfig/default.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/fontconfig/default.nix#L1), [`pkgs/servers/x11/xquartz/default.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xquartz/default.nix#L63), and [`pkgs/development/libraries/fontconfig/make-fonts-conf.nix`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/fontconfig/make-fonts-conf.nix) so that NixOS installations without `allowUnfree` are not broken. (They are not necessary for any of these modules or packages and were just included as default fonts.)

1: https://packages.debian.org/wheezy/ttf-xfree86-nonfree
2: https://bugzilla.redhat.com/show_bug.cgi?id=317641

**Comment by cmfwyp** [comment]
The `pkgs/servers/x11/xorg/default.nix` file is generated automatically, so the license meta-attribute would need to be added to `pkgs/servers/x11/xorg/overrides.nix`.

**Comment by vcunat** [comment]
It's unlucky we chose those as the default fallback font-set.

**Comment by cmfwyp** [comment]
@vcunat Do we need replacement fallback fonts? If so, the Liberation fonts are 4.1 MiB, the DejaVu fonts are 10.2 MiB, the GNU FreeFont collection is 10.8 MiB, and the Noto fonts are 27.1 MiB. The locale-specific fonts can be excluded from the Noto fonts to reduce them to 2.8 MiB.

My recommendation would be to replace fontbhttf as a default fallback family by the DejaVu fonts, as they are standard default fonts in many Linux distributions and have good Unicode coverage. If size is a very important consideration, however, then we should go with the Liberation fonts, which are also high quality fonts. The DejaVu fonts, the Liberation fonts, and the GNU FreeFont collection are already installed by default on NixOS, though not on other platforms.

**Comment by vcunat** [comment]
Well, the fallback fonts get to the closure of anything depending on fontconfig. ~10 MiB isn't small, although most machines will likely contain DejaVu anyway. We added it during time where it was relatively common to break fontconfig by /etc from a different version and in such case you only have the fallback font.

**Comment by vcunat** [comment]
This should be fixed now in staging.
