### ISSUE TITLE
textadept: Merge packages?

### ISSUE THREAD

**Issue by patricksjackson** [NixOS/nixpkgs#175768]
### Describe the bug
I stumbled across the [textadept](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/textadept) packages the other day, and after investigating a bit I think they should be merged.

**Is there a procedure or set of best practices for merging two packages?**

There are 2 separate packages:
1. `textadept`, which is located in `pkgs/applications/editors/textadept/10`, and is on textadept v10.8.
2. `textadept11`, which is located in `pkgs/applications/editors/textadept/11`, and is at the current release of textadept, v11.3.

I was the one who recently pinned/updated these packages, but previous updates for version 11 have gone into `textadept11` with no backporting to `textadept`, which is why I kept `textadept` on v10.

### History

AFAICT, there is no reason these should be separate packages. They were split in #102488 because someone wanted access to the v11 beta, and the changes have carried forward since.

There seems to be no breaking change or issue between v10 and v11.

### Notify Maintainers

@ioplker, @mirrexagon, @7c6f434c

**Comment by FRidh** [comment]
If 11 is stable and there is no need anymore for 10 we should drop then and make 11 the default attribute.

**Comment by ioplker** [comment]
Hi, @patricksjackson!
So, I'm the one who wanted to try the beta :sweat_smile: 
Let me describe my point:
1. v10 and v11 are two major versions - they have [changes in the editor's API](https://orbitalquark.github.io/textadept/manual.html#migrating-from-textadept-10-to-11). So some plugins (and so on) from [v10 won't work in v11](https://github.com/orbitalquark/textadept/wiki#stuff-only-working-for-10x).
2. This was the first time I contributed to `nixpkgs` - and I still do not know when to migrate a package from one major version to the next. So, please, tell me more about this topic! :sweat_smile: 

I, personally, don't have any problems to use old versions like so:
```nix
let
  nixos_21_11_tarball =
    fetchTarball
      https://github.com/NixOS/nixpkgs/archive/nixos-21.11.tar.gz;
in
{
  nixpkgs.config = {
    packageOverrides = pkgs: {
      nixos_21_11 = import nixos_21_11_tarball {
        config = config.nixpkgs.config;
      };
    };
  };

  environment.systemPackages = with pkgs; [
    nixos_21_11.textadept11
    ...
```

---

As a sidenote: I've tried nixos-22.05 ~a week ago and it fails to build on Textadept. Something with QScintilla - does it builds for you, @patricksjackson?

**Comment by patricksjackson** [comment]
Hi @ioplker. I am new to contributing around here as well so I'm figuring this out as I go along :)

I fixed the build for both Textadept versions in #174632 and #174999, and that was how I noticed this oddity with the package names.

With the package names, it generally makes the most sense to have `textadept` refer to the current latest version of the project (11.3 at the moment). If there's good reason to keep the old version around then maybe we want to go back and add a `textadept10` that is pinned to stay on v10.8, as per the conventions in [Versioning](https://github.com/NixOS/nixpkgs/blob/master/doc/contributing/coding-conventions.chapter.md#versioning-sec-versioning).

The wiki pages talking about incompatible plugins is over a year old, so I assumed that the plugins were mostly updated for v11 and that v10 was no longer used. But it seems that I may have been wrong.

You are more familiar with using this program than I am. If you think it's necessary to keep v10 around then I'll support it. With Nix, there are of course ways to keep using prior versions, but it seems like there may be a reason that users would choose to continue using that specific version.

**Comment by ioplker** [comment]
@patricksjackson, hi again! Sorry it took so long to answer.
Thanks for versioning conventions, now I know :sweat_smile: 
But I've started using Textadept from v11 and cannot be sure for v10 users :/

From [Versioning](https://github.com/NixOS/nixpkgs/blob/master/doc/contributing/coding-conventions.chapter.md#versioning-sec-versioning):
> Other examples are having both the latest stable and latest pre-release version of a package, or to keep several major releases of an application that differ significantly in functionality.

I get the versioning conventions, but how to decide when to leave older major version?
*... differ significantly in functionality* seems to be a little unclear. Maybe there is some discussion or voting process? Not saying we should start it in this case though, just curious.

If you ask me, I agree to leave only v11 (as just `textadept` package).

Also, thank you for maintaining the package :wink:
