### ISSUE TITLE
i3lock-fancy: use absolute paths for getopt and fc-match

### ISSUE THREAD

**Issue by rail** [NixOS/nixpkgs#17570]
i3lock-fancy fails locking when passed to xss-lock/xautolock running as a systemd user service.

When I checked the logs, I found that it was unable to find `getopt`. I added `getopt` to `paths` and then it failed to find `fc-match`. 

https://github.com/NixOS/nixpkgs/pull/17569 should fix the issue.

Adding `getopt` and `fontconfig` to `path` works as a work around.

### Steps to reproduce
Example entry:
```
  systemd.user.services.i3lock-sleep = {
    enable = true;
    description = "Automatically lock screen before going to sleep";
    wantedBy = [ "default.target" ];
    path = with pkgs; [ xss-lock i3lock-fancy ];
    serviceConfig = {
      Restart = "always";
      ExecStart = "${pkgs.xss-lock}/bin/xss-lock ${pkgs.i3lock-fancy}/bin/i3lock-fancy";
    };
  };
```

Close the lid, wait until the laptop goes to sleep, then open it. Nothing happens. Checking the logs would give you the errors I mentioned above.

## Technical details
* System: NixOS: 16.09pre87928.3f3d18c (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre87928.3f3d18c

**Comment by garbas** [comment]
i guess we can close this now.

**Comment by rail** [comment]
Agree
