### ISSUE TITLE
defining a path for a systemd service breaks the build

### ISSUE THREAD

**Issue by joehenry087** [NixOS/nixpkgs#17572]
## Issue description

If you specify a path attribute for a systemd service it fails because nix can't properly merge the path attribute in. 

clever from IRC suggested that this is a nix bug here:
https://github.com/NixOS/nixpkgs/blob/release-16.03/nixos/modules/system/boot/systemd.nix#L224
### Steps to reproduce

put something like this in your config
`systemd.services.myservice = {
        description = "demo app";
        path = "${myenv}/bin"
    };
`
then try to build.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by joachifm** [comment]
I'm unable to reproduce this; also, I'd think you'd have to specify it as a list of packages, not a string.

**Comment by fpletz** [comment]
The error message for these sorts of errors is very confusing IIRC. But there is an issue in the nix repo for that already.
