### ISSUE TITLE
gazebo{6,7}(-headless) broken in unstable

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#17578]
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo6-headless.i686-linux
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo6-headless.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo6.i686-linux
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo6.x86_64-linux

https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo7-headless.i686-linux
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo7-headless.x86_64-linux
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo7.i686-linux
https://hydra.nixos.org/job/nixpkgs/pr-12895/gazeboSimulator.gazebo7.x86_64-linux

cc @therealpxc

**Comment by therealpxc** [comment]
I'm looking into this now. I think editing the sdformat/default.nix file so cmake is in the nativeBuildInputs list rather than buildInputs will fix it. I should have made that change already regardless. I'll update you after my OGRE build finishes. -_-

**Comment by arconix** [comment]
Cool. Thanks @therealpxc

**Comment by nico202** [comment]
Any update on this?
Thanks, Nicolò

**Comment by domenkozar** [comment]
Note that this affects the release of 16.09, we're trying to ship without failing builds. See https://github.com/NixOS/nixpkgs/issues/18209

**Comment by domenkozar** [comment]
Fixed
