### ISSUE TITLE
iBus does not work in Firefox on 22.05

### ISSUE THREAD

**Issue by andyliuhaowen** [NixOS/nixpkgs#175802]
### Describe the bug
iBus does not work in Firefox on 22.05. Works fine for all other applications.

### Steps To Reproduce
Install firefox and iBus. Try to use iBus in firefox and nautilus (and everything else).

### Expected behavior
iBus works in everything.

### Screenshots

https://user-images.githubusercontent.com/35328328/171479391-42abfd4f-3d66-4797-87d5-6008b3169ec4.mp4

### Additional context
Relevant parts of `configuration.nix`.
```
{
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.inputMethod = {
    enabled = "ibus";
    ibus.engines = with pkgs.ibus-engines; [ libpinyin ];
  };

  fonts.fonts = with pkgs; [
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-cjk-serif
  ];

  environment.systemPackages = with pkgs; [
    firefox
  ];

  system.stateVersion = "22.05";
}
```

Might be related: https://github.com/NixOS/nixpkgs/issues/37853

### Notify maintainers

I'm not sure where to problem lies so I'm pinging maintainers for both firefox and iBus.

@ttuegel @sowelisuwi @ericsagnes @lovesegfault @mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.262.2a64cd672b2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(haowenl): `""`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by michzappa** [comment]
I've had on-and-off issues with ibus working in Firefox and other apps (occasionally emacs) in GNOME for months, both on 21.11 and unstable (on 21.11 now). Seems like some weird state thing since several times I have simply rebooted with no change in configuration and the functionality flipped. For me, ibus has always worked in raw GNOME shell textboxes, like searching in the activities page.

**Comment by andyliuhaowen** [comment]
Same experience. Native GNOME/Gtk entries are fully and always functional. And for me, it never works on firefox since the upgrade, regardless of reboot and things.

**Comment by jtojnar** [comment]
For what is worth, it works form on Wayland with `firefox-wayland` package.

**Comment by andyliuhaowen** [comment]
It works! Didn't know there's a `firefox-wayland` package. Is there a way for the `firefox` package to emit a warning if `XDG_SESSION_TYPE` says wayland?

**Comment by michzappa** [comment]
Using the firefox-wayland package my ibus imes (rime and anthy) work in Firefox on both Wayland and X11.

**Comment by andyliuhaowen** [comment]
I guess this can be closed since `firefox-wayland` works. A warning from the `firefox` package would still be nice tho.

**Comment by michzappa** [comment]
Don't need to re-open, but just going to weigh in that on a fresh install of 22.05 ibus works for me in X11 and Wayland, with both firefox and firefox-wayland, giving more weight to it being a weird stateful issue.
