### ISSUE TITLE
pyopenssl fails to build on aarch64-darwin

### ISSUE THREAD

**Issue by davidarmstronglewis** [NixOS/nixpkgs#175875]
### Steps To Reproduce
1. build `python3Packages.pyopenssl` on aarch64-darwin

### Build log
```
error: Package ‘python3.9-pyopenssl-22.0.0’ in /nix/store/x1w5yls3p126bk9bj4j8lb6mf9qzm9qn-nixpkgs/nixpkgs/pkgs/development/python-modules/pyopenssl/default.nix:73 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
```

### Additional context
This is a known issue that's being tracked in https://github.com/pyca/pyopenssl/issues/873

I didn't see an open issue here to help with tracking this issue, so I'm creating this one.

Not sure if this issue impacts other systems, but feel free to tag this as `Darwin` and (if there is a tag) `aarch64`.

### Notify maintainers
Not sure who to tag here.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by nagisa** [comment]
Could this be made conditional on the `system`? Right now this package is reported as broken for `x86_64-linux` systems too even though WX pages should work fine there.

**Comment by PhilTaken** [comment]
> @nagisa I am encountering the same problem, not sure what is causing it

if you are using serokell's deploy-rs try this for tests:

```
checks = lib.filterAttrs
  (system: _: ! lib.hasInfix "darwin" system)
  (builtins.mapAttrs
    (system: deployLib: deployLib.deployChecks self.deploy)
    deploy-rs.lib);
```

**Comment by winterqt** [comment]
YMMV, but I've built this package even though it's marked as broken, and everything that I use that at least depends on it works fine.

**Comment by SuperSandro2000** [comment]
> YMMV, but I've built this package even though it's marked as broken, and everything that I use that at least depends on it works fine.

Building a python package that contains no Cython code is usually only checking the dependency constraints and then installing the files. To verify that a package actually works we need to execute tests. For pyopenssl until here most things kinda work on m1 macs **but** there are numerous failures in downstream packages which use the ffi interface. If a package 4 dependencies down the chain breaks because of this bug and pyopenssl has no upstream support for m1 macs since 2.5 years, the right thing to do is to mark it broken on that platform. Otherwise we gamble with every package that depends somehow on pyopenssl if it works or not and potentially waste lots of time debugging this exact issue over and over in other packages.

**Comment by tricktron** [comment]
@SuperSandro2000 both `python310Packages.pyopenssl` and `python39Packages.pyopenssl` build on my macOS m1 machine. Can we remove the broken again?

**Comment by winterqt** [comment]
> @SuperSandro2000 both `python310Packages.pyopenssl` and `python39Packages.pyopenssl` build on my macOS m1 machine. Can we remove the broken again?

No, please read his comment more closely. The issue is that some applications that use it depend on functions that are broken on aarch64-darwin, not that the package doesn't build.

**Comment by malob** [comment]
Not sure how it would be done, but it would be nice if there was some standard workaround for this since so many packages have `pyopenssl` as a dependency, including things like Kitty which is one of the most popular terminal emulators. I've implemented a manual workaround in my own config, but it would be nice if folks less familiar with Nix don't end up updating their channels and running into issues with important packages like Kitty.

**Comment by tricktron** [comment]
@malob Indeed. I am using `export NIXPKGS_ALLOW_BROKEN=1` and `nix build .#<pkgs>` much too often in the recent days:smiley:.

**Comment by Atemu** [comment]
Note that this also affects qemu which is a very important package IMHO.

**Comment by ivankovnatsky** [comment]
Hm, wasn't able to rebuild my system with with `nixpkgs.config.allowBroken = true;`. My nixpkgs is still pinned on 2 month old nixpkgs / nixos-unstable.

Why the heck I even need twisted, no clue:

```
python3.10-twisted> Ran 11095 tests in 591.935s
python3.10-twisted> FAILED (skips=2019, failures=10, errors=100, successes=9009)
error: builder for '/nix/store/zwwkj80ynamf3k2g5zg7fawqzpyhwv07-python3.10-twisted-22.4.0.drv' failed with exit code 1;
       last 10 log lines:
       >   File "/nix/store/wwy5jhcykcdv13a9b9rs0zbsf20np1fg-python3.10-pyopenssl-22.0.0/lib/python3.10/site-packages/OpenSSL/SSL.py", line 359, in __init__
       >     self.callback = _ffi.callback(
       > builtins.MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
       >
       > twisted.words.test.test_jabberxmlstream.TLSInitiatingInitializerTests.test_certificateVerify
       > twisted.words.test.test_jabberxmlstream.TLSInitiatingInitializerTests.test_wantedSupported
       > -------------------------------------------------------------------------------
       > Ran 11095 tests in 591.935s
       >
       > FAILED (skips=2019, failures=10, errors=100, successes=9009)
       For full logs, run 'nix log /nix/store/zwwkj80ynamf3k2g5zg7fawqzpyhwv07-python3.10-twisted-22.4.0.drv'.
```

**Comment by sudosubin** [comment]
> Hm, wasn't able to rebuild my system even with `nixpkgs.config.allowBroken = true;`. My nixpkgs is still pinned on 2 month old nixpkgs / nixos-unstable.
> 
> Why the heck I even need twisted, no clue:
> 
> ```
> python3.10-twisted> Ran 11095 tests in 591.935s
> python3.10-twisted> FAILED (skips=2019, failures=10, errors=100, successes=9009)
> error: builder for '/nix/store/zwwkj80ynamf3k2g5zg7fawqzpyhwv07-python3.10-twisted-22.4.0.drv' failed with exit code 1;
>        last 10 log lines:
>        >   File "/nix/store/wwy5jhcykcdv13a9b9rs0zbsf20np1fg-python3.10-pyopenssl-22.0.0/lib/python3.10/site-packages/OpenSSL/SSL.py", line 359, in __init__
>        >     self.callback = _ffi.callback(
>        > builtins.MemoryError: Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
>        >
>        > twisted.words.test.test_jabberxmlstream.TLSInitiatingInitializerTests.test_certificateVerify
>        > twisted.words.test.test_jabberxmlstream.TLSInitiatingInitializerTests.test_wantedSupported
>        > -------------------------------------------------------------------------------
>        > Ran 11095 tests in 591.935s
>        >
>        > FAILED (skips=2019, failures=10, errors=100, successes=9009)
>        For full logs, run 'nix log /nix/store/zwwkj80ynamf3k2g5zg7fawqzpyhwv07-python3.10-twisted-22.4.0.drv'.
> ```

That is the reason why `pyopenssl` was marked as broken in `aarch64-darwin`. It should be fixed with upstream work.
Also check this PR: https://github.com/NixOS/nixpkgs/pull/172117

**Comment by SuperSandro2000** [comment]
> Why the heck I even need twisted, no clue:

You should see the dependency chain down below which other builds failed. It is probably a checkInput somewhere.



> That is the reason why `pyopenssl` was marked as broken in `aarch64-darwin`. It should be fixed with upstream work.
> Also check this PR: #172117

👍🏼

**Comment by pecigonzalo** [comment]
> Not sure how it would be done, but it would be nice if there was some standard workaround for this since so many packages have `pyopenssl` as a dependency, including things like Kitty which is one of the most popular terminal emulators. I've implemented a manual workaround in my own config, but it would be nice if folks less familiar with Nix don't end up updating their channels and running into issues with important packages like Kitty.

Maybe something less radical like
```
python3 = prev.python3.override {
    packageOverrides = python-self: python-super: {
      pyopenssl = python-super.pyopenssl.overrideAttrs (oldAttrs: {
        meta.broken = false;
      });
    };
  };
```

**Comment by SuperSandro2000** [comment]
> `prev.pkgs-stable` is essentially `inputs.nixpkgs-22-05`

mixing different channels which are far apart can create a number of different issues which are not easily fixable.

**Comment by pecigonzalo** [comment]
Potentially, but I'm not suggesting people mix channels (I so without any issues), I just want to show an example that would work in case you do as well, as I struggled with that for a bit.

Unfortunately, some packages (like dnstools) do not work in anything newer on M1.

**Comment by SuperSandro2000** [comment]
fix for this is on unstable if I am not mistaken

**Comment by pecigonzalo** [comment]
@SuperSandro2000 do you have a link to the commit?

**Comment by SuperSandro2000** [comment]
It is not one commit but a collection of 3 or 4.

**Comment by winterqt** [comment]
> fix for this is on unstable if I am not mistaken 

@SuperSandro2000 This isn't fixed upstream as far as I can tell, what do you mean by this?

**Comment by florianehmke** [comment]
The only commits I see are ones referencing the upstream issue - and in those pyopenssl is only moved to optional dependencies on darwin.

**Comment by Atemu** [comment]
This issue hasn't been fixed, only worked around.

Question is whether we even want to fix this issue, given pyopenssl's status.

**Comment by SuperSandro2000** [comment]
We don't need to keep this none actionable issue open. We removed the biggest pyopenssl usages across the python package set and upstream didn't fix this in the last 3 years and I doubt it will be fixed anytime soon.

My call is to close this issue because there is nothing we can do here except remove pyopenssl where it is optional.

**Comment by Atemu** [comment]
> remove pyopenssl where it is optional

I think that'd be a good actionable goal.

**Comment by SuperSandro2000** [comment]
but we already did that in most places or do you have packages in mind where that would still need to happen?

**Comment by winterqt** [comment]
> My call is to close this issue because there is nothing we can do here except remove pyopenssl where it is optional.

I believe we should keep it open merely as an informational issue, so people don't open duplicates; it's already labeled as wait for upstream so I think it's fine to stay open like this.

**Comment by kkharji** [comment]
I'm having issues installing pytorch due this issue :(

**Comment by bergkvist** [comment]
I'm having issues with fastapi due to this dependency chain: `fastapi -> httpx -> trustme -> pyopenssl`

**Comment by Atemu** [comment]
You should look into why trustme requires pyopenssl.

**Comment by SuperSandro2000** [comment]
trustme only requires pyopenssl for one test

**Comment by dbaynard** [comment]
@bergkvist I've just made #200717 to fix trustme — the test that required pyopenssl had already been disabled but the derivation and test suite still required the dependency and import.

**Comment by tjni** [comment]
https://github.com/NixOS/nixpkgs/pull/204002 has made it from `staging` to `master`. It should solve this issue, so I'm closing it. If anyone discovers anything new, please open a new one and feel free to tag me.
