### ISSUE TITLE
pocket-casts fails to build due to out of date electron

### ISSUE THREAD

**Issue by ciferkey** [NixOS/nixpkgs#175999]
### Steps To Reproduce
Pocket casts was previously building but now fails since the electron version is insecure.

The [package.json](https://github.com/felicianotech/pocket-casts-desktop-app/blob/trunk/package.json#L65) for the project however has "^17.0.0".

### Build log
```
error: Package ‘electron-14.2.9’ in /nix/store/z8fi1f38y14lmsyhnph1l98qr3r9x7wr-source/pkgs/development/tools/electron/generic.nix:26 is marked as insecure, refusing to evaluate.


       Known issues:
        - Electron version 14.2.9 is EOL

       You can install it anyway by allowing this package, using the
       following methods:

       a) To temporarily allow all insecure packages, you can use an environment
          variable for a single invocation of the nix tools:

            $ export NIXPKGS_ALLOW_INSECURE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) for `nixos-rebuild` you can add ‘electron-14.2.9’ to
          `nixpkgs.config.permittedInsecurePackages` in the configuration.nix,
          like so:

            {
              nixpkgs.config.permittedInsecurePackages = [
                "electron-14.2.9"
              ];
            }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          ‘electron-14.2.9’ to `permittedInsecurePackages` in
          ~/.config/nixpkgs/config.nix, like so:

            {
              permittedInsecurePackages = [
                "electron-14.2.9"
              ];
            }
```

### Notify maintainers
@wolfangaukang

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.39, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by WolfangAukang** [comment]
The problem is that we are picking the AppImages, and the latest release is 0.5.0. The best thing to do would be asking the devs to publish a new release.

**Comment by ciferkey** [comment]
The author has [released ](https://github.com/felicianotech/pocket-casts-desktop-app/releases/tag/v0.6.0) 0.6.0 bumping the electron version!

**Comment by WolfangAukang** [comment]
@ciferkey working on this. Right now I have found some issues with this new version (problems unpacking the deb, no `/opt` and probably need to create the `app.asar` file), but I hope to get them solved at least this week.

**Comment by WolfangAukang** [comment]
@ciferkey do you want to test it? [Here is the branch](https://github.com/WolfangAukang/nixpkgs/tree/pocket-casts-0.6). As there were some considerable changes and the latest version of Electron is working fine, I want to ensure the functionality hasn't been affected.

**Comment by ciferkey** [comment]
I was able to build and run your branch. Login, playback etc all work. The only thing I noticed is it uses the default electron logo:
![Screenshot from 2022-11-15 15-09-29](https://user-images.githubusercontent.com/101422/202015823-363ad00c-5a0f-44bc-b3b7-afa96a5ca768.png)

Its been a while since I was able to run 0.5.0 but I believe it used the application logo.

**Comment by WolfangAukang** [comment]
Got it. I had to edit the `postInstall` to reflect the new changes, and it contained some edits to the desktop file. So it makes sense the default logo is being used here. Luckily the complicated part is fixed.

**Comment by WolfangAukang** [comment]
@ciferkey Just posted the PR on nixpkgs. Feel free to check the final changes and if everything looks fine, throw an approval.
