### ISSUE TITLE
Division of packages outputs

### ISSUE THREAD

**Issue by YPares** [NixOS/nixpkgs#17593]
## Issue description

In order to know the path to some headers and libraries in packages which have 2 separated outputs (like .dev and .out), we had to resort to this technique: https://github.com/commercialhaskell/stack/issues/2435 because we don't know for each package whether it is split or not.

Is it a recommended pattern? Because this means that I have to parse the output of `lib.makeLibraryPath` or `lib.makeSearchPathOutput`, to get a list of directories, which looks a bit like an anti-pattern.
Is there a better way to do it? Should we add some functions to better support that pattern?

**Comment by abbradar** [comment]
Perhaps you want `lib.getDev` and `lib.getOutput` in general (that said it's not really convenient to use it instead of `.dev` everywhere -- there were talks of making `.dev`, `.bin` and others present in all packages and point the real output but no code).

**Comment by YPares** [comment]
@abbradar Yes, that's indeed what I wanted, thanks!
So `lib.getOuput "dev"` is the same than `lib.getDev`, right?
