### ISSUE TITLE
Graphite-cursors

### ISSUE THREAD

**Issue by gekoke** [NixOS/nixpkgs#175928]
**Project description**
A cursor theme

**Metadata**

* homepage URL: https://github.com/vinceliuice/Graphite-cursors
* source URL: https://github.com/vinceliuice/Graphite-cursors
* license: GPL-3.0
* platforms: linux

**Comment by Lord-Valen** [comment]
This was done at some point but the pr never linked to this issue.

**Comment by Lord-Valen** [comment]
See https://github.com/NixOS/nixpkgs/pull/228911
