### ISSUE TITLE
Update GDM 42.0 due to bug with multiple displays

### ISSUE THREAD

**Issue by TeeraAskort** [NixOS/nixpkgs#175920]
GDM 42.0 has a bug where with multiple displays, when you change a display it crashes to GDM and you have to log back in, this has been fixed on newer commits adopted by different distributions like Arch, Fedora and Ubuntu.

Thanks for the help.

###### Checklist

- [ x ] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 42.0
desired version: 42.0+r11+g4a52f026

###### Notify maintainers

maintainers: Bobby Rong, Tor Hedin Brønner, Jan Tojnar, Daniel Șerbănescu, Maxine Aubrey

###### Note for maintainers

Please tag this issue in your PR.

**Comment by FliegendeWurst** [comment]
@bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey

**Comment by maxeaubrey** [comment]
I cannot reproduce this myself or find a relevant upstream issue. Could you link to something that details the problems? I only see commits mentioning disabling wayland under some specific circumstances.

**Comment by TeeraAskort** [comment]
I couldn't find an specific issue, but the problem was solved upon adopting the new commit, so maybe the issue was solved when solving the nvidia problems.
To reproduce the issue it's as simple as connecting a new display to a laptop or changing the input on the display to the computer, then it will instantly go to the login page and extensions will stop working.
On 42 release I was monitoring every single change on other distros and when they adopted this new commits the problem stopped altogether [Commit 1](https://gitlab.gnome.org/GNOME/gdm/-/commit/dba05ca9da4200eb789a87a4493a090d2ce5d224) [Commit 2](https://gitlab.gnome.org/GNOME/gdm/-/commit/c1e1abf312cde2ffb77d0242b161c57d962b8e3f).
Maybe I'm just wrong in identifying the issue as a GDM bug, but it pretty sure has happened to me on the latest 22.05 nixos release.

**Comment by max-privatevoid** [comment]
From simple empirical evidence (repeatedly plugging and unplugging my external monitor while logged into GNOME session), simply patching GDM with [commit 1](https://gitlab.gnome.org/GNOME/gdm/-/commit/dba05ca9da4200eb789a87a4493a090d2ce5d224.diff) seems to have done the trick.

**Comment by bobby285271** [comment]
[gdm 43.0](https://github.com/NixOS/nixpkgs/commit/0530435ac0ef6403edb0f1fdb0bf56c92bd5ed34) is in nixos-unstable, please re-open if this is still an issue on unstable.
