### ISSUE TITLE
qiling 1.4.3

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#175911]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: python3.9-qiling-1.4.2

current version: 1.4.2
desired version: 1.4.3

###### Notify maintainers

maintainers:

@cole-h 
@grahamc 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by fabaff** [comment]
Looks like we need an `unicorn` update as well.

**Comment by fabaff** [comment]
The update will be part of `python-updates` due to the amount of rebuilds.

**Comment by cole-h** [comment]
Closing this as I am led to believe it was fixed in https://github.com/NixOS/nixpkgs/pull/175805.
