### ISSUE TITLE
timewarrior: manpages not installed properly

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#17591]
**I post this as issue because I do not know how to fix it**

## Issue description

```bash
man timew
```

results in not found.

### Steps to reproduce

See above

## Technical details

* System: 16.09pre87999.20f009d (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre87999.20f009d"

**Comment by regnat** [comment]
The manpages were installed in a wrong directory. #17667 fixes it.
