### ISSUE TITLE
services.nginx.config not working as described

### ISSUE THREAD

**Issue by lfam** [NixOS/nixpkgs#17604]
## Issue description
The variable ```services.nginx.config``` is described as "Verbatim nginx.conf configuration." I have used this variable for a while without any problems.

However, something changed recently that caused there to be a second "http" block added to the generated /nix/store/...-nginx.conf, which causes the nginx service to fail in the configuration verification invoked in the nginx systemd unit's ```ExecStartPre``` field.

### Steps to reproduce
Use the nixos "unstable" channel corresponding to Git revision 20f009d56df9a0e5f224761ba48aa4142564753e.

Pass a valid nginx configuration file to ```services.nginx.config```, enable ```services.nginx```, and rebuild the system. `systemctl status nginx` should demonstrate that the service has failed like this:

```
nginx[14176]: nginx: [emerg] "http" directive is duplicate in /nix/store/...-nginx.conf:70
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre87999.20f009d (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09pre87999.20f009d"

**Comment by rvl** [comment]
You are probably referring to the change from #15862, which on the whole seems like a good idea to me. I assume someone will add an nginx section to the release notes for next release.

**Comment by globin** [comment]
I'll have a look later today, do you use any other nginx config options apart from `services.nginx.config`?

**Comment by lfam** [comment]
> I'll have a look later today, do you use any other nginx config options apart from services.nginx.config?

The only additional variable I had been using was ```services.nginx.enable```.

**Comment by lfam** [comment]
> You are probably referring to the change from #15862, which on the whole seems like a good idea to me. I assume someone will add an nginx section to the release notes for next release.

Having a declarative abstraction over 3rd party software configuration is a great idea but, in general, I think there needs to be an "escape hatch" for users who want to use the 3rd party upstream's configuration format.
