### ISSUE TITLE
Maven can't be used directly

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#17603]
## Issue description

Using nixpkg.maven, the `mvn` command doesn't work - it cannot find java.lang by default.

Digging into this, the `mvn` wrapper sets a JAVA_HOME environment variable incorrectly.

### Steps to reproduce

What I'm doing (which is hardly minimal...) is:

`git clone git@github.com:HubSpot/Singularity.git`
create default.nix like:
```
{ pkgs ? import <nixpkgs> {} }:
let
  inherit (pkgs) stdenv maven;
in stdenv.mkDerivation {
  name = "singularity";
  src = ./.;
  buildInputs = [
    maven
  ];
}
```
```
nix-shell
mvn compile
```

Result is that the build fails pretty early with 'cannot find java.lang in classpath`

More directly, compare:
```
echo $JAVA_HOME
```
to
```
cat $(which mvn)
```
(note that the enviroment variable has an extra `lib/openjdk`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  NixOS: `16.03.847.8688c17 (Emu)`
* Nix version: (run `nix-env --version`)
  `nix-env (Nix) 1.11.2`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
 `16.03.847.8688c17`

**Comment by NeQuissimus** [comment]
Can you do `mvn -v` and see if Maven picks up what the wrapper sets or what your JAVA_HOME is?
My output is like this and works just fine:

```
~> echo $JAVA_HOME
/nix/store/2wpybw1df139dc366ra8qc3i2g3whfd5-openjdk-8u102b04/lib/openjdk
~> cat $(which mvn)
#! /nix/store/d44582rghk696yw704sh5nbvbpnm69iv-bash-4.3-p42/bin/bash -e
export JAVA_HOME="/nix/store/2wpybw1df139dc366ra8qc3i2g3whfd5-openjdk-8u102b04"
exec /nix/store/idqkpb1dx3544nlp9y948bvbipnd2gzs-apache-maven-3.3.9/maven/bin/mvn "${extraFlagsArray[@]}" "$@"
~> mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /nix/store/idqkpb1dx3544nlp9y948bvbipnd2gzs-apache-maven-3.3.9/maven
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /nix/store/2wpybw1df139dc366ra8qc3i2g3whfd5-openjdk-8u102b04/lib/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.7.0", arch: "amd64", family: "unix"
```

**Comment by NeQuissimus** [comment]
Slightly offtopic, I am not sure how much luck you are going to have using Maven like this.
When building a nix expression you generally do not have network access available.
Unless you are building something that only required the JDK, there will be more work for you to do :D

**Comment by nyarly** [comment]
Huh.
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /nix/store/w8fynhmbl79zlybpmwb1s5cw41wbfgiw-apache-maven-3.3.9/maven
Java version: 1.8.0_76, vendor: Oracle Corporation
Java home: /nix/store/s8arhzg4k4d0xx14j4qgi9crasbfh5qd-openjdk-8u76b00/lib/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.11", arch: "amd64", family: "unix"
```

Here's the thing: my ad hoc solution was to copy $(which mvn) into the working directory and edit the JAVA_HOME line, which then let me build.

It's not a small project, but how far do you get with Singularity?

Re: "using Maven like this" - I'm not using this to actually build a nix expression for release, but rather to set up my dev environment to build this one project. Maybe I'd have better luck simply installing maven into my user environment? Still, part of the goal here was to get more experience building single-project nix expressions and using nix-shell to develop.

**Comment by NeQuissimus** [comment]
hmmm, I see the same issue.
It has nothing to do with nix-shell itself at least because I do Java development every day and can't build Singularity at work either...
Very strange... Fixing Maven may actually do the trick but it is curious how I can build pretty much anything BUT this project :D

**Comment by NeQuissimus** [comment]
This works for me, essentially unwrapping mvn :D
It does run into a node.js issue for my master branch checkout...

```
export JAVA_HOME="${$(readlink -e $(type -p java))%*/bin/java}"
$(readlink -e $(type -p mvn) | sed 's|bin/mvn|maven/bin/mvn|') compile
```

So I do think we will have to do something about the JAVA_HOME variable in the mvn wrapper...

**Comment by NeQuissimus** [comment]
I just sent in a PR for the wrapper change
