### ISSUE TITLE
caja-with-extensions doesn't install .desktop files into $XDG_DATA_DIRS

### ISSUE THREAD

**Issue by sshilovsky** [NixOS/nixpkgs#176089]
### Describe the bug
caja-with-extensions doesn't install .desktop files into $XDG_DATA_DIRS

In particular, after installing caja-with-extensions, other applications aren't able to run it when they need to show folder content to the user.

caja package does install .desktop files, and doesn't have this problem.

### Steps To Reproduce
1. `$ nix-shell -p mate.caja-with-extensions`
2. ```$ find `echo $XDG_DATA_DIRS|tr ":" " "` -name 'caja*.desktop'```

no `caja*.desktop` entries found

### Expected behavior
multiple `caja*.desktop` records should be found, like with `caja` package

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.0, NixOS, 22.05 (Quokka), 22.05.379.08950a6e29c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Aquinary** [comment]
+

**Comment by Aquinary** [comment]
Is there any workaround to fix this?
I've been struggling with this problem for a whole day, but I still can't figure out the solution.

**Comment by sshilovsky** [comment]
@aquinary I've installed `mate.caja` and `mate.caja-extensions` instead, although it seems that not all extensions are working.

**Comment by aquinary** [comment]
> @aquinary I've installed `mate.caja` and `mate.caja-extensions` instead, although it seems that not all extensions are working.

I just changed the package a caja-extensions: 
```
postInstall = ''
     mkdir -p $out/share/applications

    for file in `find $caja/share/ -type f -name "*"`
    do
      pathToFile=$(echo $file | awk -F "/" 'OFS = "/" {$2=$3=$4=""; print substr($0, 5)}')
      pathToDir=$(echo $pathToFile | awk -F "/" 'OFS = "/" {$NF=""; print $0}')
      
      mkdir -p $out/$pathToDir

      cat $caja/$pathToFile > $out/$pathToFile
      sed -i "s|$caja|$out|gi" "$out/$pathToFile"
    done
  '';
  ```
By default /usr/share/applications/caja.desktop contains a link to caja (without extensions). The script above goes through all the files and changes all occurrences from caja to caja-extensions. And it works great
And if I put mate.caja and mate.caja-extensions together, then only regular caja works, without extensions
