### ISSUE TITLE
jellyfin-web does not build on master

### ISSUE THREAD

**Issue by newAM** [NixOS/nixpkgs#176288]
### Steps To Reproduce

`nix-build -A jellyfin` at commit 0fe729dfae92b676a99067312e1637b3527cb75d

### Build log

```text
these 2 derivations will be built:
  /nix/store/0r26521cd4ihaw9ia1q320819i7rzkya-jellyfin-web-10.7.7.drv
  /nix/store/k1lv8acvrbaqmms5dx7ihqw8nay95sv8-jellyfin-10.7.7.drv
building '/nix/store/0r26521cd4ihaw9ia1q320819i7rzkya-jellyfin-web-10.7.7.drv'...
unpacking sources
unpacking source archive /nix/store/4n28kmji75gd671zm8v6xg8ywghv3s2s-source
source root is source
patching sources
configuring
no configure script, doing nothing
building

error: builder for '/nix/store/0r26521cd4ihaw9ia1q320819i7rzkya-jellyfin-web-10.7.7.drv' failed with exit code 243;
       last 8 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/4n28kmji75gd671zm8v6xg8ywghv3s2s-source
       > source root is source
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       >
       For full logs, run 'nix log /nix/store/0r26521cd4ihaw9ia1q320819i7rzkya-jellyfin-web-10.7.7.drv'.
error: 1 dependencies of derivation '/nix/store/k1lv8acvrbaqmms5dx7ihqw8nay95sv8-jellyfin-10.7.7.drv' failed to build
```

### Additional context

Same root cause as #176127, see that issue for more details.

As a workaround change this line:

https://github.com/NixOS/nixpkgs/blob/0fe729dfae92b676a99067312e1637b3527cb75d/pkgs/servers/jellyfin/web.nix#L59

to `HOME="$(mktemp -d)" npm run build:production`

This seems to be impacting a few packages.  I am not sure if I should open a pull-request with my workaround, or wait for a fix for npm.

### Notify maintainers

@nyanloutre  @minijackson @purcell @jojosch 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(alex): `""`
 - channels(root): `"nixos-21.11, nixos-unstable, nixos-unstable-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by purcell** [comment]
Yeah, I suspect the right solution here would be a fix that covers all the affected packages, rather than doing it on a case-by-case basis.

**Comment by imsofi** [comment]
Excuse my above commit referencing this issue. I wrongly escaped the URL referencing this issue.

**Comment by marius851000** [comment]
It seems the peertube service is also impacted by this. Npm with nodejs 16.15.0 work well, but not 16.15.1

**Comment by Kranzes** [comment]
is it known what caused this issue?

**Comment by newAM** [comment]
> is it known what caused this issue?

Yes:

* related nixpkgs issue: https://github.com/NixOS/nixpkgs/issues/176127
* related npm issue: https://github.com/npm/cli/issues/4769
* npm commit that introduced this behaviour: https://github.com/npm/cli/commit/cc6c09431d7fe2db8ac1dc7a707f2dab7a7a1f83

**Comment by minijackson** [comment]
jellyfin-web now builds on master, since the NPM update was reverted in https://github.com/NixOS/nixpkgs/pull/177002.

If upstream does not remove the dependency on the home directory, I think it might be best to open a new common issue instead of one for each affected package, so I'm closing this issue. Feel free to re-open if you feel otherwise.
