### ISSUE TITLE
gnucash: Getting quotes is broken in 22.05

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#176230]
### Describe the bug

On NixOS 22.05, getting financial quotes in gnucash no longer works because the `gnc-fq-*` helper scripts are now binary wrappers, but gnucash calls `perl gnc-fq-...` so this fails.

```
$ file ./result/bin/gnc-fq-check 
./result/bin/gnc-fq-check: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped
```

Commit 7b74a76d9b8d6dfc097a6578e3f3999392d7cfad suggests that `dontWrapGApps = true` should avoid this, but for some reason the scripts still get wrapped with binaries.

### Notify maintainers

@StephenWithPH, @AndersonTorres 

### Metadata

NixOS 22.05.20220602.40e2b1a

**Comment by StephenWithPH** [comment]
I can reproduce this on my machine from nixpkgs/master, so it's not a 22.05 problem.

```
$ nixos-version 
20.03.3330.1db42b7fe38 (Markhor)

$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-21.11
unstable https://nixos.org/channels/nixpkgs-unstable
```

Interestingly, when backport GnuCash's derivation from the master back to a known-good commit (7b74a76d9b8d6dfc097a6578e3f3999392d7cfad), things appear ok. I'll continue digging.

**Comment by StephenWithPH** [comment]
@rski ... I see you added yourself as a maintainer. Any interest in taking a stab at this?

Per
> when I backport GnuCash's derivation from nixpkgs/master back to a known-good commit (https://github.com/NixOS/nixpkgs/commit/7b74a76d9b8d6dfc097a6578e3f3999392d7cfad), things appear ok. I'll continue digging.

I think we're being broken by a change somewhere related to `dontWrapGApps`.

**Comment by rski** [comment]
>@rski ... I see you added yourself as a maintainer. Any interest in taking a stab at this?
still getting my head together after a bad bout of covid, not sure I'll be able to work on anything serious any time soon
