### ISSUE TITLE
hydra module: bad command line switches

### ISSUE THREAD

**Issue by k0001** [NixOS/nixpkgs#17624]
As of nixos/nixpkgs@4c43ac2db55a4313313d6d6393c40b771ae4c0ad (i.e., today) `hydra-server` seems to be failing due to an unsupported `-f` command line switch being passed (see https://github.com/NixOS/nixpkgs/blob/4c43ac2db55a4313313d6d6393c40b771ae4c0ad/nixos/modules/services/continuous-integration/hydra/default.nix#L307)

```
Aug 09 23:53:56 hydra-master hydra-server[14830]: Unknown option: f
```

Actually, starting `hydra-master` doesn't fail, but some (all?) of the other command line arguments are ignored. For example, I tried setting `port = 8000`, but see how `hydra-server` insists on starting on port `3000`. 

```
Aug 09 23:53:56 hydra-master hydra-server[14830]: Unknown option: f
Aug 09 23:53:56 hydra-master hydra-server[14830]: [warn] Unicode::Encoding plugin is auto-applied, please remove this from your appclass and make sure to define "encoding" config
Aug 09 23:53:57 hydra-master hydra-server[14830]: DEPRECATION WARNING: The Regex dispatch type is deprecated.
Aug 09 23:53:57 hydra-master hydra-server[14830]:   It is recommended that you convert Regex and LocalRegex
Aug 09 23:53:57 hydra-master hydra-server[14830]:   methods to Chained methods. at /nix/store/fn664jhpryflf56w6zmhwmbpxpjvd0h4-hydra-perl-deps/lib/perl5/site_perl/5.22.2/Catalyst/DispatchType/Regex.pm line 210.
Aug 09 23:53:58 hydra-master hydra-server[14830]: 2016/08/09-23:53:58 Starman::Server (type Net::Server::PreFork) starting! pid(14830)
Aug 09 23:53:58 hydra-master hydra-server[14830]: Resolved [*]:3000 to [0.0.0.0]:3000, IPv4
Aug 09 23:53:58 hydra-master hydra-server[14830]: Binding to TCP port 3000 on host 0.0.0.0 with IPv4
Aug 09 23:53:58 hydra-master hydra-server[14830]: Setting gid to "122 122 122"
Aug 09 23:53:58 hydra-master hydra-server[14830]: Starman: Accepting connections at http://*:3000/
```

Removing the `-f` switch makes `hydra-server` start as expected, respecting the other given command line switches, but is this what we want to do?

cc @domenkozar

**Comment by domenkozar** [comment]
@k0001 this was broken due to Catalyst bump. See duplicated https://github.com/NixOS/nixpkgs/issues/16074 - I don't know how to best fix this as `-f` switch might have an impact. If someone has time to fix it, I'd be very happy :)
