### ISSUE TITLE
Nitter is outdated

### ISSUE THREAD

**Issue by artemislena** [NixOS/nixpkgs#176216]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: Nitter? Not sure what's meant by `nix search`, that command seems to be something for flakes.

current version: 2022-05-13
desired version: 2022-06-04

###### Notify maintainers

maintainers: @erdnaxe @ehmry 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ehmry** [comment]
Make a PR.

**Comment by erdnaxe** [comment]
Please note that Nitter is a rolling-release software, there is no "stable" versions so it is quite hard to know when to update.
I am not against updating if you believe that the new version brings interesting changes or fixes.

It seems that in the new version:
 - There are some changes on how video playback is handled. MP4 videos are now preferred over m3u8 when proxyVideos is off.
 - Dependencies are updated to markdown#a661c26, karax#5498909 and zippy#0.9.9 (https://github.com/zedeus/nitter/commit/93f605f4fe9f0787e3dd618cba85130b9cba2438). We might need to also update these in nixpkgs.

If you open a pull request I will happily review it.

**Comment by AndersonTorres** [comment]
OK then, I will try this.

**Comment by artemislena** [comment]
> Make a PR.

fc17: Sorry… if we knew how… we would already… I mean… we know how to do a PR… but not the entire dependencies thing and how to get the SHA256 hash and how to test it… We… haven't ever done any Nix packaging…

> Please note that Nitter is a rolling-release software, there is no "stable" versions so it is quite hard to know when to update.

L: Yeah, we saw that, hence why we just set the "version" to the date of the latest commit, which is apparently what you did previously too. Maybe updating (automatically) on new commits would make sense? It looks like the Docker image does that, I think. We'd honestly even use that (even though that means we would have to use an amd64 machine, unless we want to use a third-party image), but then we either couldn't make our config public, or would miss out on having a secret HMAC key, because apparently you can't set things through environment variables or a second config file or the like, as far as we can tell.

> if you believe that the new version brings interesting changes or fixes

T.: Dunno. I mean, the video format thingy's *a* change, n the other stuff seems sensible too (I mean, updating dependencies's always good, given there might be security issues in old versions n what not).

**Comment by ehmry** [comment]
> Maybe updating (automatically) on new commits would make sense?

I think that is a violation of the spirit of package management, which is that packages are updated when they are release and are not a salad of developement snapshots. Some parts of the Nim community have a "works-on-my-machine" attitude and a disregard for packaging standards, and I think its our place to push back against that.
