### ISSUE TITLE
Package Request: wrangler2

### ISSUE THREAD

**Issue by houstdav000** [NixOS/nixpkgs#176233]
**Project description**
Cloudflare released a rewrite of their "wrangler" application for Workers last month, rewritten in TypeScript, and stored in a different repository.

**Metadata**

* homepage URL: https://github.com/cloudflare/wrangler2
* source URL: https://github.com/cloudflare/wrangler2
* license: apache2
* platforms: all (that Node.js support)

**Comment by houstdav000** [comment]
I can probably add the package, but the real problem is whether to keep v1 in there, and if so, how to differentiate the two.

One possibility is to go by the repository names, and keep "wrangler", and add "wrangler2".

**Comment by AndersonTorres** [comment]
In the name, obviously. wrangler is wrangler, wrangler2 is wrangler2.

They are not versions from a same guy, but different guys.

**Comment by CMCDragonkai** [comment]
I think it should definitely be kept separate as `wrangler2`.

**Comment by KenMacD** [comment]
I'd suggest the opposite. Cloudflare isn't calling this `wrangler2` in documentation, they're calling it `wrangler`, and saying to install it with `npm install -g wrangler`. The docs list the `1.x` version as `Wrangler 1 (legacy)`.

I'd expect installing `wrangler` to install the latest  version, maybe with the option to install `wrangler_1` if I really needed it. I'd be surprised if I read the cloudflare workers documentation, installed `wrangler` and it didn't match.

**Comment by houstdav000** [comment]
That's fair. I'd expect the latest major version, regardless of which package. Might need to update aws-cli to match though...
-------- Original message --------From: Kenny MacDermid ***@***.***> Date: 9/12/22  11:33 AM  (GMT-05:00) To: NixOS/nixpkgs ***@***.***> Cc: David Houston ***@***.***>, Author ***@***.***> Subject: Re: [NixOS/nixpkgs] Package Request: wrangler2 (Issue #176233) 
I'd suggest the opposite. Cloudflare isn't calling this wrangler2 in documentation, they're calling it wrangler, and saying to install it with npm install -g wrangler. The docs list the 1.x version as Wrangler 1 (legacy).
I'd expect installing wrangler to install the latest  version, maybe with the option to install wrangler_1 if I really needed it. I'd be surprised if I read the cloudflare workers documentation, installed wrangler and it didn't match.

**Comment by domenkozar** [comment]
Anyone has a package ready to test?

**Comment by houstdav000** [comment]
I used to. Looks like I might not have pushed that branch to my fork of nixpkgs before wiping my laptop though, so I've since lost it. It's an npm package though, so it should be easy to add (though might take a second given how node2nix works). I've got it started, but we'll see if it finishes before I have to start work

**Comment by houstdav000** [comment]
Ah, now I remember why I didn't finish it. Wrangler2 requires at least Node.js v16.13.0, but `nodePackages` builds for v14. Trying to build for `nodePackages_latest` gives me a cache failure, which I think means one of the dependencies builds using different packages for newer versions of Node, but `node2nix` doesn't configure the version per-package, and so doesn't build a `node-packages.nix` listing the cache references for anything but the version provided. I remember trying to look into napalm last time as a result and wanted to try just building the package on its own (as node packages probably should), but couldn't figure it out.

Incidentally, I'm running back into napalm again due to other Node.js package issues with aws-cdk (which has a runtime node package dependency???), so not sure if that's better to pursue, or to build a one-time fix for this use-case.

**Comment by houstdav000** [comment]
Alright, got a working workaround w/ the help of @lilyinstarlight by adding an override:

```nix
  wrangler = prev.wrangler.override {
    dontNpmInstall = true;
    nativeBuildInputs = [ pkgs.buildPackages.makeWrapper ];
    postInstall = ''
      makeWrapper "$out/lib/node_modules/wrangler/bin/wrangler.js" "$out/bin/wrangler" \
        --inherit-argv0
    '';
  };
```
