### ISSUE TITLE
Change hashes to SRI format

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#176283]
## Issue description

The various hashes should be unified to the most recent SHA256 SRI format.

### Steps to reproduce

A simple RG can find them. I have tried 

```
rg 'sha256 = "(sha256:|)...................................................."' 

```

and found the files below:

http://ix.io/3Zoq

**Comment by AndersonTorres** [comment]
Part I

- [ ] applications/accessibility/espeakup/default.nix
- [ ] applications/accessibility/mousetweaks/default.nix
- [ ] applications/audio/AMB-plugins/default.nix
- [ ] applications/audio/ChowCentaur/default.nix
- [ ] applications/audio/ChowKick/default.nix
- [ ] applications/audio/FIL-plugins/default.nix
- [ ] applications/audio/MMA/default.nix
- [ ] applications/audio/aacgain/default.nix
- [ ] applications/audio/abcde/default.nix
- [ ] applications/audio/adlplug/default.nix
- [ ] applications/audio/aeolus/default.nix
- [ ] applications/audio/aether-lv2/default.nix
- [ ] applications/audio/airwave/default.nix
- [ ] applications/audio/aj-snapshot/default.nix
- [ ] applications/audio/amarok/default.nix
- [ ] applications/audio/ams-lv2/default.nix
- [ ] applications/audio/ams/default.nix
- [ ] applications/audio/apple-music-electron/default.nix
- [ ] applications/audio/ardour/default.nix
- [ ] applications/audio/ario/default.nix
- [ ] applications/audio/artyFX/default.nix
- [ ] applications/audio/asunder/default.nix
- [ ] applications/audio/audacious/default.nix
- [ ] applications/audio/audio-recorder/default.nix
- [ ] applications/audio/aumix/default.nix
- [ ] applications/audio/autotalent/default.nix
- [ ] applications/audio/bambootracker/default.nix
- [ ] applications/audio/baudline/default.nix
- [ ] applications/audio/bespokesynth/default.nix
- [ ] applications/audio/bitmeter/default.nix
- [ ] applications/audio/bitwig-studio/bitwig-studio1.nix
- [ ] applications/audio/bitwig-studio/bitwig-studio2.nix
- [ ] applications/audio/bitwig-studio/bitwig-studio3.nix
- [ ] applications/audio/boops/default.nix
- [ ] applications/audio/bristol/default.nix
- [ ] applications/audio/bucklespring/default.nix
- [ ] applications/audio/cadence/default.nix
- [ ] applications/audio/calf/default.nix
- [ ] applications/audio/caps/default.nix
- [ ] applications/audio/cd-discid/default.nix
- [ ] applications/audio/cdparanoia/default.nix
- [ ] applications/audio/clementine/default.nix
- [ ] applications/audio/clerk/default.nix
- [ ] applications/audio/cmt/default.nix
- [ ] applications/audio/cmusfm/default.nix
- [ ] applications/audio/cozy/default.nix
- [ ] applications/audio/crip/default.nix
- [ ] applications/audio/csa/default.nix
- [ ] applications/audio/csound/csound-manual/default.nix
- [ ] applications/audio/csound/csound-qt/default.nix

**Comment by AndersonTorres** [comment]
Part II

- [ ] applications/audio/curseradio/default.nix
- [ ] applications/audio/cyanrip/default.nix
- [ ] applications/audio/deadbeef/default.nix
- [ ] applications/audio/deadbeef/plugins/headerbar-gtk3.nix
- [ ] applications/audio/deadbeef/plugins/lyricbar.nix
- [ ] applications/audio/deadbeef/plugins/mpris2.nix
- [ ] applications/audio/dfasma/default.nix
- [ ] applications/audio/diopser/default.nix
- [ ] applications/audio/dirt/default.nix
- [ ] applications/audio/distrho/default.nix
- [ ] applications/audio/dr14_tmeter/default.nix
- [ ] applications/audio/drumgizmo/default.nix
- [ ] applications/audio/easytag/default.nix
- [ ] applications/audio/ebumeter/default.nix
- [ ] applications/audio/ecasound/default.nix
- [ ] applications/audio/eflite/default.nix
- [ ] applications/audio/ekho/default.nix
- [ ] applications/audio/ensemble-chorus/default.nix
- [ ] applications/audio/eq10q/default.nix
- [ ] applications/audio/espeak-ng/default.nix
- [ ] applications/audio/espeak/default.nix
- [ ] applications/audio/espeak/edit.nix
- [ ] applications/audio/exaile/default.nix
- [ ] applications/audio/famistudio/default.nix
- [ ] applications/audio/faust/faust1.nix
- [ ] applications/audio/faustStk/default.nix
- [ ] applications/audio/flac/default.nix
- [ ] applications/audio/flac123/default.nix
- [ ] applications/audio/fmit/default.nix
- [ ] applications/audio/fmsynth/default.nix
- [ ] applications/audio/freewheeling/default.nix
- [ ] applications/audio/freqtweak/default.nix
- [ ] applications/audio/furnace/default.nix
- [ ] applications/audio/fverb/default.nix
- [ ] applications/audio/game-music-emu/default.nix
- [ ] applications/audio/giada/default.nix
- [ ] applications/audio/gigedit/default.nix
- [ ] applications/audio/gjay/default.nix
- [ ] applications/audio/gmpc/default.nix
- [ ] applications/audio/gmu/default.nix
- [ ] applications/audio/gnome-podcasts/default.nix
- [ ] applications/audio/google-play-music-desktop-player/default.nix
- [ ] applications/audio/gpodder/default.nix
- [ ] applications/audio/gradio/default.nix
- [ ] applications/audio/grandorgue/default.nix
- [ ] applications/audio/gspeech/default.nix
- [ ] applications/audio/gtkpod/default.nix
- [ ] applications/audio/guitarix/default.nix
- [ ] applications/audio/gxmatcheq-lv2/default.nix
- [ ] applications/audio/gxplugins-lv2/default.nix
- [ ] applications/audio/helm/default.nix
- [ ] applications/audio/helvum/default.nix
- [ ] applications/audio/hivelytracker/default.nix
- [ ] applications/audio/hushboard/default.nix
- [ ] applications/audio/hybridreverb2/default.nix
- [ ] applications/audio/id3v2/default.nix
- [ ] applications/audio/industrializer/default.nix
- [ ] applications/audio/infamousPlugins/default.nix
- [ ] applications/audio/ingen/default.nix
- [ ] applications/audio/ir.lv2/default.nix
- [ ] applications/audio/jaaa/default.nix
- [ ] applications/audio/jack-capture/default.nix
- [ ] applications/audio/jack-oscrolloscope/default.nix
- [ ] applications/audio/jack-rack/default.nix
- [ ] applications/audio/jackmeter/default.nix
- [ ] applications/audio/jackmix/default.nix
- [ ] applications/audio/jamin/default.nix
- [ ] applications/audio/jconvolver/default.nix
- [ ] applications/audio/jellycli/default.nix
- [ ] applications/audio/kapitonov-plugins-pack/default.nix
- [ ] applications/audio/keyfinder-cli/default.nix
- [ ] applications/audio/keyfinder/default.nix
- [ ] applications/audio/klystrack/default.nix
- [ ] applications/audio/kmetronome/default.nix
- [ ] applications/audio/ladspa-sdk/default.nix
- [ ] applications/audio/ladspa-sdk/ladspah.nix
- [ ] applications/audio/lash/default.nix
- [ ] applications/audio/librespot/default.nix
- [ ] applications/audio/lingot/default.nix
- [ ] applications/audio/littlegptracker/default.nix
- [ ] applications/audio/lmms/default.nix
- [ ] applications/audio/losslessaudiochecker/default.nix
- [ ] applications/audio/ltc-tools/default.nix
- [ ] applications/audio/luppp/default.nix
- [ ] applications/audio/lv2-cpp-tools/default.nix
- [ ] applications/audio/lv2bm/default.nix
- [ ] applications/audio/lyrebird/default.nix
- [ ] applications/audio/m4acut/default.nix
- [ ] applications/audio/magnetophonDSP/CharacterCompressor/default.nix
- [ ] applications/audio/magnetophonDSP/CompBus/default.nix
- [ ] applications/audio/magnetophonDSP/ConstantDetuneChorus/default.nix
- [ ] applications/audio/magnetophonDSP/LazyLimiter/default.nix
- [ ] applications/audio/magnetophonDSP/MBdistortion/default.nix
- [ ] applications/audio/magnetophonDSP/RhythmDelay/default.nix
- [ ] applications/audio/magnetophonDSP/VoiceOfFaust/default.nix
- [ ] applications/audio/magnetophonDSP/faustCompressors/default.nix
- [ ] applications/audio/magnetophonDSP/pluginUtils/default.nix
- [ ] applications/audio/magnetophonDSP/shelfMultiBand/default.nix
- [ ] applications/audio/mamba/default.nix

**Comment by elikoga** [comment]
wondering: Would this cause a mass-rebuild?

**Comment by AndersonTorres** [comment]
> wondering: Would this cause a mass-rebuild?

Ideally not. Many of those packages are leaves.

The machine-generated can be problematic, however.

**Comment by milahu** [comment]
> The various hashes should be unified to the most recent SHA256 SRI format.

why?

**Comment by AndersonTorres** [comment]
> why?

Because reasons.

**Comment by winterqt** [comment]
Also see https://github.com/NixOS/rfcs/pull/131.

**Comment by sternenseemann** [comment]
I'm closing this since the RFC is still under discussion. It is (as of writing this) just a proposal and there hasn't even been a shepherd discussion yet. We should defer any (treewide) actions until we have come to a decision.

I specifically want to avoid a situation as with the version format RFC where facts were created in nixpkgs and it later turned out that the actions taken were not necessarily the way to go.
