### ISSUE TITLE
zoom-us does not scale window properly (sway)

### ISSUE THREAD

**Issue by pgarrison** [NixOS/nixpkgs#176218]
### Describe the bug
On sway, Zoom windows are scaled so that the controls are offscreen, making the application unusable. See screenshots below.

### Steps To Reproduce
1. `$ NIXPKGS_ALLOW_UNFREE=1 nix-shell -p zoom-us pulseaudio-ctl --run zoom-us`

### Expected behavior
The application should fit inside its window

### Screenshots

![06-04-2022_02-34-40](https://user-images.githubusercontent.com/5379348/171994718-bce5ddab-cd52-4279-a467-e0f81182a087.jpg)
![06-04-2022_02-34-26](https://user-images.githubusercontent.com/5379348/171994720-69d6da84-0193-43db-93d0-ddc0ff39661b.jpg)

### Additional context
[Full log here](https://gist.github.com/pgarrison/5fd7831fd14e4c38afd53d2419448e31)

For my hidpi screen I usually run at 1.5x scale, but the problem persists even at 1x scale (`wlr-randr --output eDP-1 --scale 1`). 

Enabling `xwayland` does not change the behavior

### Notify maintainers
@danbst @tadfisher @doronbehar 

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11.20220603.236cc29`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by pgarrison** [comment]
I have run into the same issue with FoxitReader, so perhaps this is a configuration issue on my end?

![06-13-2022_18-51-48](https://user-images.githubusercontent.com/5379348/173481212-dd9515de-aea9-48ff-866a-b3c377efab9d.jpg)

**Comment by Artturin** [comment]
can't repro, perhaps it's because you have a HIDPI display. in any case its/it was likely a upstream issue because both of these use QT

```
$ nixos-version
23.05.20230319.60c1d71 (Stoat)
$ sway --version
sway version 1.9-dev
```
