### ISSUE TITLE
expose services.restic.package option for restic backup module

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nixpkgs#176314]
### Describe the bug
I'd like to be able to customize the package in the `restic` backup service with some shell script wrappers. Can we get a `services.restic.package` option to compliment the current `services.restic.server.package`?

### Notify maintainers
@mbrgm

**Comment by winterqt** [comment]
What would this allow (other than privilege dropping, which we may be able to come up with a better solution for) that the pre backup and post backup hooks don't?

**Comment by alan-strohm** [comment]
It's a very common option to many services.  You can see a list here:
https://search.nixos.org/options?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=package

In the past, I've seen it used to select different major versions of a package or different patched versions.  I suppose that's what overlays are for, but the package option has a better UI (easier to discover, etc.). 

In general it's a good escape hatch.  I already have a wrapped version of restic which sets up all the credentials properly.  I could use the services credential options, but it's easier to just reuse my wrapped package that already takes care of it.
