### ISSUE TITLE
ceph and ceph-dev broken in unstable

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#17633]
http://hydra.nixos.org/build/38383775 	nixpkgs.ceph-dev.i686-linux
http://hydra.nixos.org/build/38382794 	nixpkgs.ceph-dev.x86_64-linux
http://hydra.nixos.org/build/38382582 	nixpkgs.ceph.i686-linux
http://hydra.nixos.org/build/38382862 	nixpkgs.ceph.x86_64-linux

**Comment by FRidh** [comment]
cc maintainers @ak @wkennington

**Comment by dezgeg** [comment]
Should be fixed in master now.

**Comment by arconix** [comment]
Awesome! Thanks @dezgeg
