### ISSUE TITLE
document how to run tests

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#17634]
on my local nixpkgs branch I could do

`nix-build -A packagename`

but I can't do something like (actual failing job in hydra)

`nix-build -A vm-test-run-blivet`

How do I run tests?

**Comment by domenkozar** [comment]
http://nixos.org/nixos/manual/index.html#sec-running-nixos-tests-interactively

**Comment by arconix** [comment]
Embarrased that I didn't see that section. Thanks @domenkozar!
