### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by MRFROG2106** [NixOS/nixpkgs#176483]
### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by LunNova** [comment]
It looks like you forgot to fill anything in.

**Comment by knedlsepp** [comment]
Seems this was accidentally opened. Closing. 🙂
