### ISSUE TITLE
Gnome 3.20 Seahorse or Terminal SSH agent broken

### ISSUE THREAD

**Issue by bfrog** [NixOS/nixpkgs#17648]
## Issue description

Seahorse appears to not store passphrases for ssh keys (this works well on other distros) such that whenever ssh'ing to a remote host for the first connect, even with the keyring unlocked, I have to enter my ssh key passphrase
### Steps to reproduce

Create an ssh key with passphrase using ssh-keygen, attempt to ssh to a remote host using key auth after your keyring is already open and has the ssh-key listed, get a pop up asking for the ssh key passphrase
## Technical details
- System:  16.09pre88063.43da8b1 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre88063.43da8b1"

**Comment by bfrog** [comment]
I can't figure this one out honestly, though the env var for ssh ask pass was not set to the seahorse-ask-pass binary

**Comment by Profpatsch** [comment]
(triage) is it broken still?

**Comment by jtojnar** [comment]
Works for me.
