### ISSUE TITLE
K3s service does not include ipset in path

### ISSUE THREAD

**Issue by shawnhwei** [NixOS/nixpkgs#176445]
### Describe the bug
`services.k3s` does not include `ipset` command in the systemd path (even if the pkg is installed) which prevents the k3s network policy controller from starting.

### Steps To Reproduce
1. Enable k3s service
2. Check the k3s journalctl logs
3. Observe a warning like: `k3s[612]: time="2022-06-06T02:56:24+08:00" level=warning msg="Skipping network policy controller start, ipset unavailable: ipset utility not found"`

### Expected behavior
`ipset` should be in the path of the k3s systemd service to take advantage of network policies.

### Additional context
You can check this by copying the PATH from the systemd service (/etc/systemd/system/k3s.service), export it into your current shell, and try to run `ipset`.

I am using this quick fix in my configuration: `systemd.services.k3s.path = [ pkgs.ipset ];`

### Notify maintainers
@euank 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.118, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337763.ec6eaba9dfc"`
 - channels(shawn): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by euank** [comment]
Thanks for the report! I've put up a PR that should fix this over here: #176520

The fix you've got (adding it to the systemd path) is quite reasonable; I opted for adding it to the binary's path a layer down to make sure ipset is also available for someone running `sudo k3s server` or such by hand too.
