### ISSUE TITLE
systemd-boot: sbsign warns about gaps in the section table and Secure Boot fails

### ISSUE THREAD

**Issue by hmenke** [NixOS/nixpkgs#176584]
### Describe the bug

The systemd-boot image built in nixpkgs has gaps in the section table. This leads to signature verification failure with some UEFI Secure Boot implementations (e.g. Dell XPS 13 9310)

### Steps To Reproduce

Using NixOS 22.05 @ d9794b04bffb468b886c553557489977ae5f4c65

```console
$ sbsign --key db.key --cert db.crt --output /tmp/systemd-bootx64.efi "$(nix eval --raw nixpkgs#systemd.outPath)/lib/systemd/boot/efi/systemd-bootx64.efi"
warning: gap in section table:
    .reloc  : 0x00012ef0 - 0x000132f0,
    .data   : 0x00013100 - 0x00018900,
gaps in the section table may result in different checksums
warning: data remaining[107760 vs 123032]: gaps between PE/COFF sections?
Signing Unsigned original image
```

### Expected behavior

Using some old version from NixOS 21.11 that I still have in the store:

```console
$ sbsign --key db.key --cert db.crt --output /tmp/systemd-bootx64.efi /nix/store/w4my56mxgknxk5m0vilgizi37iyibmvb-systemd-249.7/lib/systemd/boot/efi/systemd-bootx64.efi
warning: data remaining[84992 vs 96038]: gaps between PE/COFF sections?
warning: data remaining[84992 vs 96040]: gaps between PE/COFF sections?
Signing Unsigned original image
```

### Screenshots

N/A

### Additional context

Allegedly something like this was fixed in systemd upstream and the commit is present in v250.4 but for some reason it still appears and Secure Boot fails.
https://github.com/systemd/systemd/issues/21956
https://github.com/systemd/systemd/pull/21960
https://github.com/systemd/systemd-stable/commit/2c99c399363830bb3360f1b68817dc9ffc921de4

### Notify maintainers

@NixOS/systemd 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.11, NixOS, 22.05 (Quokka), 22.05.20220604.d9794b0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/etc/nixpkgs`

**Comment by hmenke** [comment]
Relevant: https://github.com/NixOS/nixpkgs/pull/150491#issuecomment-1003521107

@andir @NickCao @jonringer

**Comment by hmenke** [comment]
This commit might be the culprit: f5c243d6c291671d256ec12a4c6805e9cb049565
I will try confirm this, but since it requires rebuilding systemd, it'll take a while.

**Comment by NickCao** [comment]
> It's more likely a problem of sbsigntools: https://git.kernel.org/pub/scm/linux/kernel/git/jejb/sbsigntools.git/commit/?id=98d3ce77b4960785c5180277989542bfb90a9666

Does your hardware still correctly validate the signature with this patch applied?

**Comment by hmenke** [comment]
Yes, signature verification works with this patch (and only with this patch). Hardware is Dell XPS 13 9310.

See also https://github.com/hmenke/nixos-modules/commit/4cb46f0a670b30149ae1caeded22d7ca12163749
