### ISSUE TITLE
Packaging request: WindTerm

### ISSUE THREAD

**Issue by ProxyVT** [NixOS/nixpkgs#176556]
**Project description**

WindTerm is an advanced SSH/Telnet/Serial/Shell/Sftp client for DevOps.

**Metadata**

* homepage URL: https://kingtoolbox.github.io
* source URL: https://github.com/kingToolbox/WindTerm
* license: apache2
* platforms: linux, darwin, windows

**Comment by goodosoft** [comment]
waiting for it!

**Comment by Aleksanaa** [comment]
It seems that subsequent versions of this software are not open source? Although the version number is still 2.6.0, the release artifacts have been updated.

**Comment by ProxyVT** [comment]
> It seems that subsequent versions of this software are not open source? Although the version number is still 2.6.0, the release artifacts have been updated.

The manual says that "source codes (except thirdparty directory) are provided under the terms of Apache-2.0 license". But also it says that "WindTerm is a partial open source project". So I'm not sure which license should be chosen for packaging: unfree or apache2.
