### ISSUE TITLE
Package 'hoauth2-0.5.4.0' is broken

### ISSUE THREAD

**Issue by jezen** [NixOS/nixpkgs#17652]
## Issue description

I am unable to build my Haskell project because there is a problem with either 'hoauth2-0.5.4.0', or 'yesod-auth-oauth2-0.2.1', or both.

Part of the failed build output that I think may be relevant is here:

```
Configuring hoauth2-0.5.4.0...
Setup: At least the following dependencies are missing:
wai ==3.2.*, warp ==3.2.*
builder for ‘/nix/store/xdqszziy6ilb8rfqzy7a553yvmj62rc9-hoauth2-0.5.4.0.drv’ failed with exit code 1
building path(s) ‘/nix/store/y70n99fmgys9di3jid3z6rg9r612pa1q-mime-mail-ses-0.3.2.2’
cannot build derivation ‘/nix/store/krsl8c1y3cc1dilxnv6cqadihh6xxcyn-yesod-auth-oauth2-0.2.1.drv’: 1 dependencies couldn't be built
killing process 29320
```

The full failed build output is [here](http://sprunge.us/fQLc).

People who I think may be able to help include @peti, @LnL7, and @obadz.

### Steps to reproduce

This happens as a result of NixOps trying to build and deploy my Haskell project, as you can see in the full output linked to above.

*edit*: Actually, this issue can be reproduced with:

```
nix-build '<nixpkgs>' -A haskell.packages.ghc7103.hoauth2
```

## Technical details

* Compiling project with GHC 7.10.3
* System: Ubuntu 12.04 LTS
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre88190.a4161ac

**Comment by obadz** [comment]
Let's see if we can get you on `ghc8` with something like this: https://github.com/obadz/nixpkgs/commit/bce3672234c13643e2885cc3be6cfcaedc16ffb1
