### ISSUE TITLE
nixos.tests.firefox{,-esr} fails on hydra

### ISSUE THREAD

**Issue by bobby285271** [NixOS/nixpkgs#176502]
### Describe the bug

Likely caused by build failure of `nixosTests.allDrivers.firefox{,-esr}`.

- https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/firefox.nix
- https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.firefox.x86_64-linux
- https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.firefox-esr.x86_64-linux

https://github.com/NixOS/nixpkgs/blob/66172026e025bfdf08d5be4f9b8d5be9b70f912f/nixos/tests/firefox.nix#L53-L64

[Sample run](https://hydra.nixos.org/build/179329476/nixlog/1):

```
testScriptWithTypes:48: error: Argument 1 to "contextmanager" has incompatible
type "Callable[[Machine], None]"; expected
"Callable[[Machine], Iterator[<nothing>]]"
    @contextmanager
     ^
testScriptWithTypes:49: error: The return type of a generator function should
be "Generator" or one of its supertypes
    def audio_recording(machine: Machine) -> None:
    ^
Found 2 errors in 1 file (checked 1 source file)
builder for '/nix/store/s3xnkjsvn2b6fj6h7d3z5dqk66ykgfln-nixos-test-driver-firefox.drv' failed with exit code 1
```

### Additional context

I am really sorry I didn't test this in #176182 and seems like this is one of channel blockers left.

- https://github.com/NixOS/nixpkgs/pull/171280
- https://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents

### Notify maintainers

Firefox maintainer @mweinelt, also cc #171280 @m1-s.

**Comment by K900** [comment]
FWIW I think you can just remove the `-> None` and it'll typecheck fine.

**Comment by mweinelt** [comment]
Agreed, the yield does not yield anything and is only used to interrupt the function calls.
