### ISSUE TITLE
mullvad-vpn: split tunneling doesn't work, mullvad-exclude fails with "Cannot set the cgroup", "Permission denied"

### ISSUE THREAD

**Issue by piousdeer** [NixOS/nixpkgs#176603]
### Describe the bug
Mullvad VPN's split tunneling is supposed let you launch apps and have their traffic bypass the VPN tunnel, but clicking on any app results in a ["Unable to launch selection" message](https://user-images.githubusercontent.com/31318219/172223489-1ec47cb7-ea2c-40e5-bd07-917870a655d4.png). Trying to run e.g. `mullvad-exclude epiphany` as a normal user fails too:
```
Cannot set the cgroup
Caused by: Permission denied (os error 13)
```

### Steps To Reproduce
1. `services.mullvad-vpn.enable = true;` and install `mullvad-vpn`
2. In the app, go to Settings > Advanced > Split tunneling and try to launch an app
3. Try to use `mullvad-exclude`

### Expected behavior
Split tunneling works as expected via both GUI and CLI.

### Additional context
Running `mullvad-exclude` as root doesn't result in an error and works as expected.

### Notify maintainers
@ymarkus 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.11, NixOS, 22.05 (Quokka), 22.05.379.08950a6e29c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(v): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by piousdeer** [comment]
Pinging other maintainers: @Br1ght0ne @flexagoon @cole-h

**Comment by flexagoon** [comment]
I have a wrapper in my config which fixes this issue, and I can share it with you if. I unfortunately don't really know how to include it in the mullvad derivation itself, as it is NixOS-specific.

**Comment by flexagoon** [comment]
I will share my config here later.

**Comment by flexagoon** [comment]
@piousdeer here is my configuration for mullvad-exclude. Just add it to your config and it'll fix the issue.

```nix
security.wrappers.mullvad-exclude = {
  setuid = true;
  owner = "root";
  group = "root";
  source = "${pkgs.mullvad-vpn}/bin/mullvad-exclude";
};
```

**Comment by ymarkus** [comment]
I've opened a PR which should fix this error in the module. Please test if you have time!
