### ISSUE TITLE
julia and julia-git for i686 broken in unstable

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#17661]
http://hydra.nixos.org/build/38449631 	nixpkgs.julia-git.i686-linux
http://hydra.nixos.org/build/38451075 	nixpkgs.julia.i686-linux

cc @7c6f434c

**Comment by 7c6f434c** [comment]
I have since tried to understand it a few times, something strange happens there…

**Comment by domenkozar** [comment]
We've just disabled these builds for now
