### ISSUE TITLE
Add fastfetch

### ISSUE THREAD

**Issue by Alxhr0** [NixOS/nixpkgs#176799]
**Project description**
fastfetch is a [neofetch] like tool for fetching system information and displaying them in a pretty way. It is written in c to achieve much better performance,

**Metadata**

* source URL: https://github.com/LinusDierheimer/fastfetch
* license: mit, bsd, gpl2+ ,:  mit
* platforms: unix, linux, darwin, : linux

**Comment by Yureien** [comment]
Please review https://github.com/NixOS/nixpkgs/pull/176819
