### ISSUE TITLE
caddy update to 0.9

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#17678]
I'm working on it.

**Comment by davidak** [comment]
i need the output of:

```
go2nix --until auto --rev f28af637327a4f12ae745284c519cfdeca5502ef --tags v0.9.0 --pkg github.com/mholt/caddy --out-json deps.json
```

but i only get errors :(

**Comment by kamilchm** [comment]
It looks like you are using https://github.com/cstrahan/go2nix
You should use the one provided in `nixpkgs` https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/go2nix/default.nix
