### ISSUE TITLE
how to start the gitlab-runner with debug logging ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#176700]
## Issue description

I would like to enable the "debug" setting of the gitlab-runner but I couldn't find an easy way out with the module options. It might be doable by overriding the systemd config . I solved it locally by adding             `".log_level = ${toJSON "debug"}"` line 102.
Not sure what's best here.

## Technical details

current master

**Comment by applePrincess** [comment]
I haven't used gitlab-runner yet but, from
https://github.com/NixOS/nixpkgs/blob/564cc281688810bc00c5e8311430d14f9e187a5f/nixos/modules/services/continuous-integration/gitlab-runner.nix#L121
and a quote from https://docs.gitlab.com/runner/faq/

> Debug logging can be enabled in the [global section of the config.toml](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section) by setting the log_level setting to debug. Add the following line at the very top of your config.toml, before/after the concurrent line:

```nix
{config, pkgs, lib, ...}:
{
  services.gitlab-runner = {
    enable = true;
    configFile = ''
    log_level = "debug"
    '';
  };
}
```
