### ISSUE TITLE
scrcpy: Could not initialize SDL: No available video device

### ISSUE THREAD

**Issue by fufexan** [NixOS/nixpkgs#176781]
### Describe the bug
I'm trying to run `scrcpy` and it doesn't work, with any `--render-name` option nor with `--v4l2-sink`. Also tried setting `SDL_VIDEODRIVER` to `wayland`, `dummy` and `x11`, as well as running through `gamescope`.

### Steps To Reproduce
1. `nix shell nixpkgs#scrcpy`
2. `sudo scrcpy`

### Expected behavior
The usual SDL window should pop up and display the video feed from the phone.

### Additional context
Command output
```sh
nix-shell › sudo scrcpy
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
Authorization required, but no authorization protocol specified
error: XDG_RUNTIME_DIR not set in the environment.
/nix/store/c9ljhlckjznywzhvhjkqr462pr72ygw0-scrcpy-1.24/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 175.5 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: realme RMX2001 (Android 11)
ERROR: Could not initialize SDL: No available video device
WARN: Killing the server...
```

### Notify maintainers
@DeltaEvo @lukeadams @msfjarvis 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/6pkx11fz05v4m8jgx76y1q1ri6llpf3i-bash-interactive-5.1-p16-dev
copying path '/nix/store/6pkx11fz05v4m8jgx76y1q1ri6llpf3i-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.8-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20220605.c5d810f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220530_af23d38`
 - nixpkgs: `/etc/nix/flake-channels/nixpkgs`
```

**Comment by msfjarvis** [comment]
I currently only have headless NixOS machines so I can't confirm the package works on it, but it does work fine w/ Nix on Linux Mint Una and Nix on macOS Monterey. Is there a reason you do `sudo scrcpy` rather than just `scrcpy`?
