### ISSUE TITLE
Python: some packages don't propagate `python` causing "nix-shell -p" to fail

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#17679]
### Steps to reproduce

Example:

```
nix-shell -p python2Packages.pycairo
echo $PYTHONPATH
# empty
exit

nix-shell -p python2Packages.pycairo python2
echo $PYTHONPATH
# <snip>:/nix/store/*-python2.7-pycairo-1.10.0/lib/python2.7/site-packages
```
## Technical details

It's the setup-hook of the python package that set `PYTHONPATH`. If a package doesn't propagate (`propagatedBuildInputs`) python, the envHook wont run and the package wont be usable from the shell. (unless python is explicitly added also)

I talked to @domenkozar on IRC, and the policy is that all python packages should be usable without explicitly specifying python too.

I've created a [script](https://gist.github.com/olejorgenb/7c2c4328060cf5be0b55bfb5b4b08f2f) that finds packages that might break this principle.

The script isn't perfect so the candidates must be checked manually.

I've identified the following python 2 packages so far: [1] (attribute names under python2Packages)
- [ ] PyXML
- [ ] PyXAPI
- [ ] bsddb
- [ ] crypt
- [ ] curses_panel
- [ ] dbus
- [ ] gdbm
- [ ] gst-python
- [ ] libvirt
- [ ] notify
- [ ] pyblock
- [ ] pycairo
- [ ] pygobject
- [ ] pygobject3
- [ ] pygtksourceview
- [ ] pyside
- [ ] pysvn
- [ ] pywebkitgtk
- [ ] qscintilla
- [ ] recursivePthLoader
- [ ] sip
- [ ] sip_4_16
- [ ] readline (*)
- [ ] curses (*)
- [ ] sqlite3 (*)

(*) These are importable without PYTHONPATH (native modules?), but with `--pure` the python interpreter is not available

To prevent this error in the future a note should be added to the nixpkgs manual?  Something like:

> Python packages should propagate python (through `propagatedBuildInputs` such that `nix-shell -p pkg` works. `buildPythonPackages` does this automatically.

Maybe it's even possible to add a test?
- System: NixOS: 16.03.948.a96c308 (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre88185.52a875f" (not my system, but the version I ran my detection script against)

[1] by doing (against nixos stable though, so some might have been fixed in master in a way that "fools" my script, and I've omitted the master-only candidates)

```
check() {
    nix-shell --run "echo $PYTHONPATH" -p python2Package.$1
    nix-shell --run "echo $PYTHONPATH" -p python2Package.$1 python2
}
```

**Comment by FRidh** [comment]
With packages that don't use `buildPythonPackage` there's at least two things we need to fix:
- setting `pythonPath = []` so its discovered by `python.buildEnv`
- fixing the hook as you point out here.

**Comment by FRidh** [comment]
this list should be quite a bit smaller since 2a3077d2cc4f78882537a49a5a36df352ecb36da

**Comment by edolstra** [comment]
Well, propagated build inputs are generally a bad thing IMHO. For Perl packages I always do `nix-shell -p perl perlPackages.Foo ...`.

**Comment by FRidh** [comment]
What is bad about `propagatedBuildInputs`? I wouldn't be surprised if I misunderstand them. Typically I read these as "these are run-time dependencies". 

We could do without propagating `python`. Python applications would still function since their shebangs have been patched. However, wouldn't you then get another inconsistency, when using `nix-shell -p pythonPackages.foo` where `foo` is a package without any items in `/bin` and a `pythonPackages.bar` where `bar` is a package that does have `/bin`? The latter would then have `python` on its path, right?

**Comment by edolstra** [comment]
`propagatedBuildInputs` lead to undeclared, implicit dependencies. For example, if package A depends on B and C, but B has a propagated dependency on C, then A will build fine even if it doesn't declare its dependency on C. That can then lead to unexpected build failures, for example, if B drops its dependency on C, or if A's dependency on B is optional.

**Comment by corps** [comment]
@edolstra While that is true, it's no more annoying than a shell with -p python pythonPackages.A working one day, but then failing another day when pythonPackages.A also needs libY as a runtime dependency (assuming that propagatedBuildInputs is not used).  Needing to propagate runtime dependencies is an expected cost for an interpretive programming model.  If either approach is going to lead to potential pains, why not take the more "intuitive" approach? (installed pythonPackages set up the environment to be run "as is").

**Comment by FRidh** [comment]
@olejorgenb I think all Python libraries are in `python-packages.nix` now and, they all use `buildPythonPackage` thereby propagating `python`. Therefore I am closing this issue. If you happen to notice any that has this issue, then please report it.
