### ISSUE TITLE
services.prometheus.exporters.nextcloud, with 0.5.1 not able to use nextcloud auth token

### ISSUE THREAD

**Issue by nivadis** [NixOS/nixpkgs#176849]
### Describe the bug
when i try to use a auth token instead of admin user account, it failed to build.
``
error: The option `services.prometheus.exporters.nextcloud.passwordFile' is used but not defined.
``
### Steps To Reproduce
use nextcloud exporter without username and password

i removed the options ``.username`` and ``.passwordFile``
and added ``.extraFlags = [ "--auth-token @/root/nextcloud-exporter-tokenfile" ];``

### Expected behavior
on cli with correct parameters the service runs smoothly

### Notify maintainers
@Ma27 @ajs124

**Comment by raboof** [comment]
I think this is a 'missing feature' more than a bug, but indeed a feature I'd enjoy a lot :).

I guess we could do something like #242942?

**Comment by nmasur** [comment]
@raboof I don't use `tokenFile` in my config, so it's simply left at default (`""`). It seems with this update, I'm now getting this error:

```
       error: A definition for option `services.prometheus.exporters.nextcloud.tokenFile' is not of type `path'. Defin
ition values:                                                                                                         
       - In `/nix/store/ifdk68fj3gv9fyfvkyh2ay88qybh2dd9-source/modules/nixos/services/nextcloud.nix': ""
```

It seems like both `passwordFile` and `tokenFile` should be `types.nullOr types.path` and check for `null`, rather than the non-path `""`? Otherwise, I think this breaks those of us who just use a `passwordFile`.

**Comment by raboof** [comment]
> @raboof I don't use `tokenFile` in my config, so it's simply left at default (`""`). It seems with this update, I'm now getting this error:
> 
> ```
>        error: A definition for option `services.prometheus.exporters.nextcloud.tokenFile' is not of type `path'. Defin
> ition values:                                                                                                         
>        - In `/nix/store/ifdk68fj3gv9fyfvkyh2ay88qybh2dd9-source/modules/nixos/services/nextcloud.nix': ""
> ```
> 
> It seems like both `passwordFile` and `tokenFile` should be `types.nullOr types.path` and check for `null`, rather than the non-path `""`? Otherwise, I think this breaks those of us who just use a `passwordFile`.

Ouch, sorry about that - I'm sure I looked at the derivation output when only `passwordFile` was set, but apparently I broke it again in a subsequent refactor.

Would https://github.com/NixOS/nixpkgs/pull/254563 fix it for you?

**Comment by nmasur** [comment]
Thanks, that looks good to me!
