### ISSUE TITLE
Nginx and Acme dependency.

### ISSUE THREAD

**Issue by ibrahimsag** [NixOS/nixpkgs#17686]
## Issue description

As i understood,
- nginx depends on acme client to prepare the certificates
- acme client depends on nginx to serve the challenge response.

I might be missing something but i expect acme-client services to not fail on startup. 

Particularly, the following lines are where i think there's a problem.
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme.nix#L267-L272

But i couldn't grasp the whole picture.

**Comment by fpletz** [comment]
@ibrahimsag Are you on 16.03? This is fixed in master and will be fixed in 16.09. We now generate self-signed certificates for bootstrapping.

**Comment by ibrahimsag** [comment]
Yes, i'm on 16.03. i'll try using it from master.

Thanks for the quick reply!

**Comment by ibrahimsag** [comment]
I've moved to nixos-unstable channel. at first it worked. but when i tried a rebuild it started getting the same error. any ideas?

**Comment by domenkozar** [comment]
You have to follow http://hydra.nixos.org/build/38602601/download/2/nixos/index.html#idm140737315732592

**Comment by ibrahimsag** [comment]
Ah, sorry. I wasn't clear. Those instructions work nicely. 

This problem is about vhosts configuration in nginx module.
when i use the `enableACME` option for the vhost, it somehow can't write to `/var/lib/acme/acme-challenge` or it's writing somewhere else. My only clue is nginx access logs show that letsencrypt server tried the challenge file from `.well-known/acme-challenge/X` but got a 404 response.
