### ISSUE TITLE
fish completions broken in NixOS 22.05

### ISSUE THREAD

**Issue by mrcjkb** [NixOS/nixpkgs#176848]
### Steps To Reproduce
1. Enable vendor fish completions provided by Nixpkgs by adding `programs.fish.enable = true;` to configuration.nix (nixos-22.05)
(see also https://nixos.wiki/wiki/Fish)
2. Run `nixos-rebuild switch`

### Build log
```
building Nix...
building the system configuration...
error: value is a string with context while a set was expected

       at /nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/programs/fish.nix:262:16:

          261|           generateCompletions = package: pkgs.runCommand
          262|             "${package.name}_fish-completions"
             |                ^
          263|             (
(use '--show-trace' to show detailed location information)
```

### Notify maintainers
@hyperfekt 

### Additional context
Additional fish-configurations:
* `users.defaultUserShell = pkgs.fish`

### Metadata
```console
[user@system:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.118, NixOS, 22.05 (Quokka), 22.05.590.f05e7d39a48`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - channels(mrcjk): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hyperfekt** [comment]
One of your packages isn't a derivation? Weird but I suppose there's no rule against it. 😅 Should be fairly easy to fix, give me a little.

**Comment by MrcJkb** [comment]
It only happened after I upgraded to the nixos-22.05 channel.

**Comment by hyperfekt** [comment]
@MrcJkb Could you test #176886?
