### ISSUE TITLE
Please add xf86-video-amdgpu

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#17682]
## Issue description

Please add the xf86-video-amdgpu which provides support for the amdgpu kernel module in the X server.

**Comment by corngood** [comment]
Here's a branch with the driver, just add:

`services.xserver.videoDrivers = [ "amdgpu" "modesetting" ]`

and possibly:

`boot.blacklistedKernelModules = [ "radeon" ];`

I have an R9 290, so I also needed a custom kernel (4.7) with:

```
  boot.kernelPackages = with pkgs;
    let self = linuxPackagesFor (pkgs.linuxPackages_latest.kernel.override { extraConfig = "DRM_AMDGPU_CIK y"; }) self; in self;
```

**Comment by vcunat** [comment]
I made amdgpu blacklist radeon automatically b4821ece. @corngood: is that kernel option override required or generally useful? We do have `amdgpu.ko` in the default nixos kernels.

**Comment by corngood** [comment]
@vcunat @abbradar The kernel option just enables experimental support for certain GPUs in amdgpu.  They are fully supported in radeon, so it's probably best to leave upstream defaults.  They may eventually remove the option or enable it by default, and most people with new GPUs won't need to set it.

As for blacklisting radeon, I think that's a reasonably way to do it, you'll just obviously need to be careful that nobody adds amdgpu to the default video driver list.

**Comment by abbradar** [comment]
Actually I think that if this option enables new GPUs we should enable it by default. radeon is our default driver anyway, so it should allow strictly more configurations (like yours), without breaking or changing anything for other people.

**Comment by corngood** [comment]
Sounds fine if you don't mind departing from the defaults.   I can't think of a problem it would cause, and it would save us CIK users a kernel build.

**Comment by vcunat** [comment]
The official description doesn't enlighten me at all about what it could actually mean: https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/amdgpu/Kconfig

**Comment by vcunat** [comment]
In every reference I see it's considered "experimental" and thus likely unfit to be in (NixOS) defaults.

**Comment by abbradar** [comment]
It's experimental in a different sense than usual though, in that it adds support for new hardware without touching anything existing. In this it's quite similar to staging kernel drivers, which we already do build.

Notice however that I may have no idea what I'm talking about (maybe this switch does change the behaviour for already supported cards).

**Comment by vcunat** [comment]
[Arch is relatively helpful](https://wiki.archlinux.org/index.php/AMDGPU#Enable_amdgpu_for_Sea_Islands_Cards): it's apparently needed for amdgpu on SI cards, but I've got no good idea what it does.

**Comment by abbradar** [comment]
I've looked through kernel source. This switch enables things like this in various files:
```
                case CHIP_BONAIRE:
                case CHIP_HAWAII:
                        amd_pp->ip_funcs = &ci_dpm_ip_funcs;
                        break;
                case CHIP_KABINI:
                case CHIP_MULLINS:
                case CHIP_KAVERI:
                        amd_pp->ip_funcs = &kv_dpm_ip_funcs;
                        break;
```

That is, it adds new cases to switches with chip names and new entries for PCI id tables -- things like that. I haven't seen any other usage of this switch so I believe it's safe for existing hardware.

**Comment by Mounium** [comment]
Isn't this driver supposed to provide a way for lm-sensors to display GPU temperature? (under other OSs it does so)
