### ISSUE TITLE
BCC tries to link against wrong kernel

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#17683]
## Issue description

The installed BCC scripts complain "no such file or directory" because they are looking in `uname -r` in the kernel source derevation. The trouble is, I'm installing BCC from nixpkgs on a NixOS system, so in this case, the source package is for 4.4.16 and I have 4.4.14 installed, resulting in:

chdir(/nix/store/kkzdps9f5b5siil7d4xa9jdy94kawvk1-linux-4.4.16-dev/lib/modules/4.4.14/source): No such file or directory
### Steps to reproduce

```
Install NixOS
nix-env -iA linuxPackages.bcc
fileslower 
```
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  `16.03.1189.96097f1 (Emu)`
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.2
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  16.03.1189.96097f1

**Comment by womfoo** [comment]
I'm unfamiliar with BCC but kernel modules are usually enabled in /etc/nixos/(hardware-)configuration.nix

i.e.

```
  boot.kernelModules = [ "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
```

If BCC does not come with modules (didn't notice one), then sticking `config.boot.kernelPackages.bcc` in `environment.systemPackages` might be enough.

cc @ragnard

**Comment by nyarly** [comment]
Trouble is that bcc doesn't appear to be in the NixOS channel, so adding it to systemPackages leads to a not-found error. Nixpkgs includes a different kernel version, so bcc (which live-compiles kernel modules) builds against the wrong kernel version.

I've been considering writing an expression that knits together bcc from nixpkgs with the kernel from nixos, which would work as a one-off, but I wonder about the general case

**Comment by ragnard** [comment]
Thanks for raising this. I don't currently have access to a NixOS install so I can't help any further with this issue.

For context, there was some discussing around how this should be done in original PR: https://github.com/NixOS/nixpkgs/pull/14479

**Comment by orivej** [comment]
@Mic92 has made the correct installation simple (with `programs.bcc.enable = true;` in `configuration.nix`) in https://github.com/NixOS/nixpkgs/commit/44b6a1509daf214d292dadafaedf8fea994c12a5 .

**Comment by Mic92** [comment]
And I was not even aware of this issue, though I made the same mistake.
