### ISSUE TITLE
Print a real hash in paths-from-graph printRegistration

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#17697]
Currently we [have](https://github.com/NixOS/nixpkgs/blob/2045b40b1061f24e9a51e1f312c9d9e131b8b43b/pkgs/build-support/kernel/paths-from-graph.pl#L73):

> print "0000000000000000000000000000000000000000000000000000000000000000\n"; # !!! fix

in `paths-from-graph.pl`. This breaks the tests for NixOS/nix#1027, because the new path copy code does hash checking. We should store the real hash there.

**Comment by shlevy** [comment]
@edolstra has said he will work on this

**Comment by domenkozar** [comment]
Happy to hook up the nixpkgs branch to https://headcounter.org/hydra/jobset/iElectric/nix-without-perl once it's ready.

**Comment by domenkozar** [comment]
Following files use `Nix::` perl namespace in nixpkgs:

```
nixos/modules/installer/tools/nixos-install.sh:binary_caches=$(@perl@/bin/perl -I @nix@/lib/perl5/site_perl/*/* -e 'use Nix::Config; Nix::Config::readConfig; print $Nix::Config::config{"binary-caches"};')
```

**Comment by shlevy** [comment]
Wrong issue? Anyway we still build the perl bindings as a separate drv.

**Comment by shlevy** [comment]
Closing this to clear up my open issues list, please open a new one if interested in pursuing this.
