### ISSUE TITLE
Xanmod: Ashmem not found

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#177011]
### Describe the bug
The xanmod [website](https://xanmod.org/) says that Ashmem is included by default, but it doesn't seem to be the case.

### Steps To Reproduce
```
- modprobe ashmem_linux
modprobe: FATAL: Module ashmem_linux not found in directory /run/booted-system/kernel-modules/lib/modules/5.18.1-xanmod1
```
Also trying to start waydroid-container service:
```
Jun 09 11:45:21 nixos-wlaptop systemd[1]: Started Waydroid Container.
Jun 09 11:45:21 nixos-wlaptop waydroid[21215]: [11:45:21] Failed to load ashmem driver
Jun 09 11:45:21 nixos-wlaptop waydroid[21215]: [11:45:21] modprobe: FATAL: Module ashmem_linux not found in directory /run/booted-system/kernel-modules/lib/modules/5.18.1-xanmod1
Jun 09 11:45:21 nixos-wlaptop waydroid[21215]: [11:45:21] Failed to load Ashmem driver
```

### Notify maintainers
 @fortuneteller2k @lovesegfault @Atemu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.1-xanmod1, NixOS, 22.11 (Raccoon), 22.11pre383837.033bd4fa9a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Atemu** [comment]
From the log: `warning: unused option: ASHMEM`. Xanmod shouldn't be special here, that's a regular upstream feature.

I'd go and ask upstream about it.

**Comment by NickCao** [comment]
ashmem was removed in linux 5.18, and waydroid has an issue for that: https://github.com/waydroid/waydroid/issues/406

**Comment by Atemu** [comment]
It should be disabled for all 5.18 kernels then.
