### ISSUE TITLE
Comment.nvim doesn't work when lazyloaded

### ISSUE THREAD

**Issue by ObsidianChickenz** [NixOS/nixpkgs#177092]
### Describe the bug
When I try to use Comment.nvim in Neovim, the keybindings do nothing.

### Steps To Reproduce
1. Install Neovim with the plugin `comment-nvim` via Nix.
2. Call the setup function for Comment.nvim.
3. Press `gcc` in a plaintext file.

### Expected behavior
When I press the keybind `gcc`, the selected line should be commented in Neovim.

### Additional context
This plugin works on Arch Linux with Packer.nvim, but not on NixOS with Nix.

### Notify maintainers

@QuantMint 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
these 2 paths will be fetched (0.07 MiB download, 0.34 MiB unpacked):
  /nix/store/6pkx11fz05v4m8jgx76y1q1ri6llpf3i-bash-interactive-5.1-p16-dev
  /nix/store/ypszvxqskanxpxplcda0pfa6kmj2yjy0-stdenv-linux
copying path '/nix/store/6pkx11fz05v4m8jgx76y1q1ri6llpf3i-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/ypszvxqskanxpxplcda0pfa6kmj2yjy0-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.11 (Raccoon), 22.11pre384129.e0169d7a9d3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hqurve** [comment]
I'm not currently using comment.nvim, however, I have several thoughts

- ensure the keybinding is registered. Look for the keybinding `gcc` in the output of `:nmap`
- Perhaps it has something to do with the filetype. You mention a plain text file. However, I dont think the filetype `text` sets `commentstring`. Maybe try open `test.c` and use the keybinding (ensure that the line has text on it; it does not need to be valid)

(Also, linking your issue in case someone else is looking https://github.com/numToStr/Comment.nvim/issues/168)

**Comment by ObsidianChickenz** [comment]
1) The keymap exists on `:map`.
2) My actual test file was a .lua file, sorry for being unclear.

**Comment by hqurve** [comment]
Okay, I'm unable to reproduce using the same commit (latest unstable) and just the basic setup `require('Comment').setup()`. 

Perhaps there is some interaction with other plugins with the same keymap? (i'm not too sure). But one think you could try is disable all other plugins and see if the problem still exists

**Comment by ObsidianChickenz** [comment]
I've had a slight revelation: Comment.nvim works when autoloaded, but NOT when lazyloaded. Will update the title accordingly.

**Comment by gravndal** [comment]
You're probably hitting this: https://github.com/vim/vim/issues/1994, which arguably isn't a bug as Comment.nvim really shouldn't be abusing the after directory like it is.

Anyway, a workaround is manually doing `:runtime after/plugin/Comment.lua` after the plugin has been loaded, or better yet as a part of the lazy loading procedure.

**Comment by ObsidianChickenz** [comment]
Manually sourcing the file worked, so I'll close the issue, but I have a question: how does Packer.nvim lazyloading work out of the box with Comment.nvim? In other words, does it do something special to get around this issue?

**Comment by gravndal** [comment]
Packer doesn't do anything special, it just sources files in the after directory if there are any.

**Comment by ObsidianChickenz** [comment]
Got it. Thanks for the help!
