### ISSUE TITLE
Dovecot requires mailUser and mailGroup for sieve

### ISSUE THREAD

**Issue by uwap** [NixOS/nixpkgs#17702]
## Issue description
When services.dovecot2.mailUser and services.dovecot2.mailGroup is not set, nixos-rebuild terminates with the type error "cannot coerce null to a string", when services.dovecot2.sieveScripts is set. The reason for it is in line 257 of the dovecot module:
```
chown -R '${cfg.mailUser}:${cfg.mailGroup}' '${stateDir}/sieve'
```
mailUser and mailGroup default to null.

One way to solve this could be to default to the dovecot user and group when no virtual mail user was set.

### Steps to reproduce
Set services.dovecot2.mailUser or services.dovecot2.mailGroup to the default and then set services.dovecot2.sieveScripts to anything other than {}.

## Technical details

* System: 16.09pre / Master
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre

**Comment by grahamc** [comment]
I was looking in to fixing this. It looks like mailUser / mailGroup could default to cfg.user and cfg.group? I don't know why they are separate. Anyone know if that works?

**Comment by uwap** [comment]
I don't know if that works tbh. If not, it would suffice to just add another assertion that requires mailUser and mailGroup to be defined when sieveScripts is set.
