### ISSUE TITLE
Kitty fails to build on Hydra for `x86_64-darwin`

### ISSUE THREAD

**Issue by malob** [NixOS/nixpkgs#177074]
Kitty (v0.25.1) seem to be having issues building on Hydra for `x86_64-darwin` ([log](https://hydra.nixos.org/build/179644390/nixlog/1)). 

This is strange since,

* Hydra has no issues building the same package on `aarch64-darwin` ([log](https://hydra.nixos.org/build/179646101/nixlog/2));
* @ofborg didn't have any issues building the package on `x86_64-darwin` ([log](https://logs.nix.ci/?key=nixos/nixpkgs.175243&attempt_id=527ccead-4551-4cb3-a56c-a4ccc1a535f7)); and
* I don't have any issues building it locally on `x86_64-darwin`.

I don't understand enough about Hydra, and the configuration of the different build machines to really understand what's going on here, but it seems like the issue is likely due to some configuration difference between the build machines for `aarch64-darwin` and those for `x86_64-darwin`.

**Comment by malob** [comment]
cc: @tex @rvolosatovs @Luflosi

**Comment by Luflosi** [comment]
This should be fixed now.
