### ISSUE TITLE
freeplane: 1.9.14 > 1.10.2

### ISSUE THREAD

**Issue by j-steinbach** [NixOS/nixpkgs#177199]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: freeplane

current version: 1.9.14
desired version: [1.10.2](https://github.com/freeplane/freeplane/releases/tag/release-1.10.2)

###### Notify maintainers

maintainers: @chaduffy (or is it @charles-dyfis-net)?

###### Note for maintainers

Please tag this issue in your PR.

**Comment by yuuyins** [comment]
i've https://github.com/NixOS/nixpkgs/pull/202372

if you can get https://github.com/yuuyins/nixpkgs/tree/freeplane and try building it, getting the needed hashs and see if the builds succeeds... for some reason ofborg won't try building it when i changed the PR to open and gave it a command to build

**Comment by charles-dyfis-net** [comment]
Not sure I missed the notification on this one earlier; mea culpa. Looking at it now.

**Comment by maxhbr** [comment]
hey, I just recently created https://github.com/NixOS/nixpkgs/pull/275479

**Comment by pbsds** [comment]
fixed in #275479
