### ISSUE TITLE
Integrated webcam not being detected with nixOS 22.05

### ISSUE THREAD

**Issue by UdittLamba** [NixOS/nixpkgs#177121]
## Issue description
Recently updated to nixOS and noticed my laptop's webcam is not being detected at all. I tried updating the kernel to the latest to see if that did something but nothing changed.

laptop model: `ASUSTeK COMPUTER INC. ASUS TUF Gaming A15 FA506QM_FA566QM`

### Steps to reproduce
Install GNOME nixOS 22.05 from the iso.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/yjgdgysbfm79s3a5xjawcvz2qyfgpiw6-bash-interactive-5.1-p16-dev
copying path '/nix/store/yjgdgysbfm79s3a5xjawcvz2qyfgpiw6-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.0, NixOS, 22.05 (Quokka), 22.05.538.d9794b04bff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fabaff** [comment]
Use `lsusb` to get the ID of the device and then use the search engine of your choosing to see how the general Linux support for the cam is. E.g., [this](https://linux-hardware.org/?view=computers&type=Notebook&vendor=ASUSTek+Computer&model=ASUS+TUF+Gaming+A15+FA506QM_FA506QM) could help.

**Comment by UdittLamba** [comment]
> Use `lsusb` to get the ID of the device and then use the search engine of your choosing to see how the general Linux support for the cam is. E.g., [this](https://linux-hardware.org/?view=computers&type=Notebook&vendor=ASUSTek+Computer&model=ASUS+TUF+Gaming+A15+FA506QM_FA506QM) could help.

The cam works fine, that's the thing. I distro hop quite frequently and never had this issue before.
Also, my mistake was to clean install nixOS on my work laptop. Now I moved back to pop os and everything is fine.
Maybe I will try dual boot sometime in the future.
Thanks for the help though. much appreciated!
