### ISSUE TITLE
Komga package & module

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#177164]
**Project description**

Komga is a media server for your comics, mangas, BDs and magazines.
You can organize, read, and manage your collection.

**Metadata**

* homepage URL: https://komga.org/
* source URL: https://github.com/gotson/komga
* license: MIT
* platforms: all (Java)

**Comment by ambroisie** [comment]
I've never package a Java app, will read up on it and try to create a PR if I manage to do it.

**Comment by dit7ya** [comment]
Closing this as both the package and module are now in Nixpkgs.

https://github.com/NixOS/nixpkgs/pull/186356
