### ISSUE TITLE
grsec, CAP_SYS_ADMIN, and systemd-nspawn (systemd-231)

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#17714]
## Issue description
In the hardened-stdenv branch, trying to start a container with i2p in it:

`grsec: use of CAP_SYS_ADMIN in chroot denied for /nix/store/a8q38pvn8d9783q4mbmz3h5072hpp5y6-systemd-231/bin/systemd-nspawn[systemd-nspawn:1493] uid/euid:0/0 gid/egid:0/0, parent /nix/store/a8q38pvn8d978`

## Technical details

* System: 16.09pre-git (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre88185.52a875f

**Comment by spacekitteh** [comment]
@joachifm

**Comment by joachifm** [comment]
Try `boot.kernel.sysctl."kernel.grsecurity.chroot_caps" = 0`. This is currently not set when containers are enabled, so maybe I should add it. Though it is a bit unfortunate that we seem to have to disable all chroot restrictions in order for things to work ... I guess we really need to get role based access control going.
