### ISSUE TITLE
SteamVR Room Setup not working

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#177197]
### Describe the bug

When i start the room setup, an empty window appears and disappears directly.

When i have started Steam from terminal, i see this output:

```
Found path: /home/davidak/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup
Mono path[0] = '/home/davidak/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Managed'
Mono path[1] = '/home/davidak/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono'
Mono config path = '/home/davidak/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libopenvr_api.so'
LuaDbg - Debugging stopped
CSteam3Client::Shutdown
```

### Steps To Reproduce
1. Start Steam
2. Start SteamVR (with HMD connected)
3. Start Room Setup from SteamVR settings

### Expected behavior
Working Room Setup

### Additional context
It worked in 2019: https://chaos.social/@davidak/102414382682090253

Tested with current, beta and old version.

GPU: AMD RX 6600 XT
Driver: AMDGPU

Upstream issue: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/458

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.714.e5556c75ac0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Atemu** [comment]
It's been working just fine for me on unstable for as long as I can remember.

**Comment by Atemu** [comment]
Played Beat Saber just yesterday.
