### ISSUE TITLE
Shield users against Spotify origin changes.

### ISSUE THREAD

**Issue by seanparsons** [NixOS/nixpkgs#17711]
## Issue description
So it appears that Spotify regularly update their app and remove old versions from the origin, which causes havoc if you try to install it at the wrong time. It appears to be getting updated regularly even in the 16.03 branch, but as of my typing this it's 9 days old and the file has already disappeared from the origin.

## Steps to reproduce
Install Spotify a week or so after the derivation has been updated.

**Comment by joachifm** [comment]
See related discussion here: https://github.com/NixOS/nixpkgs/pull/14273#issuecomment-202472913; I don't think we can solve this other than to stay ontop of updating our versions. Redistributing or mirroring the source/binaries/whatever appears to be out of the question.

**Comment by seanparsons** [comment]
I might fire a tweet at their engineering Twitter account to see if it's possible for them to keep older versions maybe to lessen the issue a bit.

**Comment by jeremejevs** [comment]
Is there a precedent for a bot which would check the origin regularly and open a PR to this repo automatically, whenever it detects a newer binary, a la [Greenkeeper](https://github.com/lodash/lodash/pulls?q=greenkeeper)? If not, would such bot be welcome? Could be used for the majority of packages here, actually (with some noise-reducing precautions).
