### ISSUE TITLE
Clisp-2.49 doesn't work with PaX on nixos-unstable

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#17713]
## Issue description

As per the title:

`Aug 13 23:50:54 spaceserv kernel: grsec: denied RWX mmap of <anonymous mapping> by /nix/store/5fy4swr6j4nll97nja1ma1w70pvnylcx-clisp-2.49/lib/clisp-2.49/base/lisp.run[lisp.run:10845] uid/euid:30001/30001 gid/egid:30000/30000, parent /nix/store/pb0rmdf2dq0g7jgczjicbndb3z5xqvrb-gnumake-4.2.1/bin/make[make:10842] uid/euid:30001/30001 gid/egid:30000/30000`
## Technical details
- System: (NixOS: 16.09pre88185.52a875f (Flounder))

**Comment by spacekitteh** [comment]
@joachifm

**Comment by joachifm** [comment]
Every interpreter in the tree without `paxmark` is likely broken under grsec currently. If you are motivated to do so, simply adding `paxmark m` on the appropriate binary should fix the problem.

**Comment by joachifm** [comment]
As far as I can tell, this is actually due to a problem with the way clisp is packaged. I've played with a minimal clisp build that works fine under PaX. I *suspect* it might be because the nixpkgs clisp always uses libffi (due to what looks like a logic bug to me).

**Comment by joachifm** [comment]
Hrm, perhaps it's the combination of dynamic modules and executable stack. Re-compiling against a libffcall with non-executable stack fixes the Nixpkgs clisp for me. Testing reverse deps now, will push the updated libffcall if nothing breaks, might resolve this.

**Comment by joachifm** [comment]
0028abeb4ed1432b99c0b977825c577b3baff3d1 resolves the problem for me.
