### ISSUE TITLE
Bolt bolt.service not installed to systemd path

### ISSUE THREAD

**Issue by OrdoFlammae** [NixOS/nixpkgs#177208]
### Describe the bug
For some reason, `/nix/store/22n8gc5w7qqjgs6dck3lw9p6g7ymcfx3-bolt-0.9.2/lib/systemd/system/bolt.service` is not being installed to nix's list of systemd services.

### Steps To Reproduce
1. Install `pkgs.bolt`.
2. (symptom) `find /nix/store -name bolt.service` only shows it in `...system-path/lib/systemd/system` and `...bolt-0.9.2/lib/systemd/system`.
3. (symptom) `boltctl` returns
```
boltctl: error: could not create client: Error calling StartServiceByName for org.freedesktop.bolt: Unit bolt.service not found.
```

### Expected behavior
bolt.service should be discoverable by systemd.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@callahad 
@jtojnar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.714.e5556c75ac0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, personal"`
 - channels(ordoflammae): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Systemd services need to be installed through `systemd.packages` NixOS option – or you can use `services.hardware.bolt.enable = true;`, which will do that for you.
