### ISSUE TITLE
Package Request: Nody-Greeter

### ISSUE THREAD

**Issue by ObsidianChickenz** [NixOS/nixpkgs#177348]
**Project description**
_describe the project a little_
Nody-Greeter is a highly customizable LightDM greeter that can be themed with HTML, CSS, and JavaScript. There are several user-created themes made to work with the greeter. If I can include a theme in this issue, it would be [https://github.com/JezerM/Aether](https://github.com/JezerM/Aether) (GPL v2). Please let me know if I need to make a separate request for the theme.

**Metadata**

* homepage URL: [https://github.com/JezerM/nody-greeter](https://github.com/JezerM/nody-greeter)
* source URL: [https://github.com/JezerM/nody-greeter](https://github.com/JezerM/nody-greeter)
* license: GPL v3
* platforms: Linux

**Comment by ObsidianChickenz** [comment]
Since this has gotten virtually no attention in months, and I've switched away from using graphical display managers, I'm closing.

**Comment by KitsuneDev** [comment]
I'm currently working on this. Can we reopen this issue, as it was never truly completed?
