### ISSUE TITLE
keyd: A key remapping daemon for linux.

### ISSUE THREAD

**Issue by benwbooth** [NixOS/nixpkgs#177301]
**Project description**

Linux lacks a good key remapping solution. In order to achieve satisfactory results a medley of tools need to be employed (e.g xcape, xmodmap) with the end result often being tethered to a specified environment (X11). keyd attempts to solve this problem by providing a flexible system wide daemon which remaps keys using kernel level input primitives (evdev, uinput).

**Metadata**

* homepage URL: https://github.com/rvaiya/keyd
* source URL:https://github.com/rvaiya/keyd
* license: mit
* platforms: linux

**Comment by dit7ya** [comment]
Closing as duplicate - #132474.
