### ISSUE TITLE
nixos: define defaut state dir (/var...) prefix

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#1773]
We need an option to define a default state dir prefix, something like `system.defaultStateDir = "/var";`. other nixos modules can then use it like `dataDir = ${config.system.defaultStateDir}/db/postgresql;`.

I want to know:

- Where should i put this option(in which nixos file, under which namespace)?
- Do you see any problems with this behaviour?

This is also related to https://github.com/NixOS/nixpkgs/issues/1689

**Comment by domenkozar** [comment]
Closing since it's little value and PR can be opened any time
