### ISSUE TITLE
postgresql_14: (upstream) possible silent data corruption in indexes

### ISSUE THREAD

**Issue by bryanasdev000** [NixOS/nixpkgs#177447]
### Describe the bug

This issue is more to alert users and keep in our radar to update our expression once upstream releases the fixes (ETA June 16, 2022)

Since the release of PostgreSQL 14.0, there existed an issue with [`CREATE INDEX CONCURRENTLY`](https://www.postgresql.org/docs/current/sql-createindex.html) and [`REINDEX CONCURRENTLY`](https://www.postgresql.org/docs/current/sql-reindex.html) that could cause silent data corruption in indexes. This issue is fixed in the upcoming PostgreSQL 14.4 release.

For more information, please check https://www.postgresql.org/message-id/165473835807.573551.1512237163040609764%40wrigleys.postgresql.org

### Steps To Reproduce
1. N/A

### Expected behavior
N/A

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@thoughtpolice @danbst @globin @marsam @ivan

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by marsam** [comment]
Addressed by #177903
