### ISSUE TITLE
`linuxPackages_latest` fails to load `amdgpu` module on boot

### ISSUE THREAD

**Issue by jakehamilton** [NixOS/nixpkgs#177581]
### Describe the bug

I recently upgraded from [21.11](https://github.com/jakehamilton/config/blob/7a50d7c554307270dc8e9f3969e41d1a0422a9ef/flake.nix#L7) to [22.05](https://github.com/jakehamilton/config/blob/2b26bd3a99a896f2f7d7d7d83d387ff00f30df6e/flake.nix#L7). After updating configuration and restarting, the boot process stopped on Stage 1 failing to load the `amdgpu` module (`Failed to load firmware "amdgpu/polaris10_mc.bin"`).

### Steps To Reproduce

Assuming you have the same AMD graphics card(s) that are causing the problem:

1. Use the current version of `nixos-22.05`: `github:nixos/nixpkgs?rev=1f8d88087a3753e55a29b5207f7f0997f7c813fa`
2. Set `boot.kernelPackages = pkgs.linuxPackages_latest`
3. Rebuild (`sudo nixos-rebuild switch --flake .`) and reboot.

### Expected behavior

The `amdgpu` module should successfully load.

### Screenshots

Apologies, the screen width makes it a bit tough to get everything in frame without it being very small. Here's the majority of the output.

![Boot screen screenshot](https://user-images.githubusercontent.com/7005773/173460592-9f539e07-312d-4816-9e03-b000936211b0.jpg)

### Additional context

I have two AMD graphics cards in my system. The main card is an RX 5700xt and the secondary card (used for passthrough) is an RX 480. I believe the loading error is complaining about loading firmware for the RX 480, but could be wrong.

The current version of `linuxPackages_latest.kernel` is `5.18`. However, downgrading to `linuxPackages_5_15` resolves the problem for me.

### Notify maintainers

@TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice 

Apologies if these are the wrong people, I'm pinging maintainers for the Linux kernel package. If there is someone better to include here, please let me know!

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.20220612.1f8d880`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by jakehamilton** [comment]
I have since updated my version of `nixos-22.05` to `72783a2d0dbbf030bff1537873dd5b85b3fb332f`. My version of `linuxPackages_latest.kernel` is now `5.19.9` and the problem seems to have been resolved!

Closing this issue as it's no longer a problem.

**Comment by willbush** [comment]
> I have since updated my version of `nixos-22.05` to `72783a2d0dbbf030bff1537873dd5b85b3fb332f`. My version of `linuxPackages_latest.kernel` is now `5.19.9` and the problem seems to have been resolved!
> 
> Closing this issue as it's no longer a problem.

@jakehamilton thanks! I ran into the same issue and using `linuxPackages_latest.kernel` fixed it for me
