### ISSUE TITLE
Mark as broken or remove keybase node.js client

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nixpkgs#17755]
## Issue description
The old node.js client is not working anymore: every command fails with this error:
```
error: Upgrade is required! Please download v1.0.16 from https://keybase.io/download -- now with KBFS!
```

### Steps to reproduce
Try running : `keybase sign -m 'test'`

--------------------------
I think `keybase-go` should just replace `keybase`. Is there any reason while it's still there?

**Comment by NeQuissimus** [comment]
I encountered the same thing. I think the node client should just be removed
