### ISSUE TITLE
isso: update to 0.13.0

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#177529]
Isso [just got a release](https://github.com/posativ/isso/releases/tag/0.13.0), and I maintain the isso package.

In 21f0b451550d7880384899fc118816d8d2815560 though the package got modified to build javascript files too, and I have no idea how to update that part. It seems to be node2nix + some custom glue code. Is there a way to update that in a single command? `node2nix` just overwrites the package.

cc @asbachb

**Comment by fgaz** [comment]
Ping @asbachb

**Comment by asbachb** [comment]
I guess it was essential just node2nix. I assume the new version of node2nix might generate different files.

If I remember right I copied package.json from repo and generate the files with node2nix.

If I get it right the build system changed so I'm not entirely sure if that entire node stuff is still needed.

**Comment by fgaz** [comment]
Done in #233399
