### ISSUE TITLE
boost155 broken on darwin/OSX

### ISSUE THREAD

**Issue by clacke** [NixOS/nixpkgs#17759]
## Issue description

Since 2016-01-18 (see https://github.com/NixOS/nixpkgs/commit/a3dcb3051#commitcomment-15482351 ), boost-1.55.0 does not compile on x86_64-darwin.

### Steps to reproduce

    $ bash <(curl http://hydra.nixos.org/build/30727396/reproduce)

or just try to build `nixpkgs.boost155`.

## Technical details

* System: OSX 10.11.6 (15G31)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre88539.21df40f

## Relevant log output

    clang -cc1as: error: unknown target triple 'unknown-apple-macosx10.7.0', please use -triple or -arch

**Comment by acowley** [comment]
Note that the following produces the same error,

```
> nix-shell -p stdenv
> as
```

This looks like it may well be a bug in the `stdenv` or with `clang`, but it's not clear why it would prevent `boost155` from working when, for example, `boost160` does work.

**Comment by copumpkin** [comment]
I have a fix for this but I can't build staging right now and it's a full stdenv rebuild so I don't want to send it straight to master.

**Comment by copumpkin** [comment]
This should be fixed by https://github.com/NixOS/nixpkgs/commit/ead242498132ae3b4a2c547f7cadbccb26c9c5a6.

**Comment by clacke** [comment]
Awesome! Now I just need to figure out what it was that I once wanted to build that depended on boost. :-D
