### ISSUE TITLE
Add grub-customizer

### ISSUE THREAD

**Issue by Game-Warrior** [NixOS/nixpkgs#177537]
**Add the grub-customizer**
It would be helpful for new users to have this program to edit the grub screen and boot order in a GUI 

**Metadata**

* homepage URL:https://launchpad.net/grub-customizer
* source URL:https://code.launchpad.net/grub-customizer
* license: GNU GPL v3
* platforms:linux

**Comment by winterqt** [comment]
Any changes made here wouldn't persist, since we override the GRUB configuration upon switching to a configuration.

See the `boot.loader.grub` options if you'd like to configure (some of) these options.
