### ISSUE TITLE
Update torbrowser to 6.0.4

### ISSUE THREAD

**Issue by rqcy** [NixOS/nixpkgs#17750]
## Issue description

The current version of Tor Browser is 6.0.3, but the nix packages still has 6.0.2.

### Steps to reproduce

N/A

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.03.1199.3234a4a

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by ng-0** [comment]
The current torbrowser version is 6.0.4, there has been an update since then: https://dist.torproject.org/torbrowser/6.0.4/

**Comment by rqcy** [comment]
thanks!

**Comment by ng-0** [comment]
For me torbrowser stopped working with this commit and update.

**Comment by joachifm** [comment]
@ng-0 can you elaborate? It works for me. If you can, please open a separate issue with details.
