### ISSUE TITLE
Package dsymutil for darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#17753]
Up until recently, Apple didn't release public source for `dsymutil`, which is needed for proper debug builds on Darwin. 

Recently, they contributed work back upstream to llvm for a public `dsymutil`, which has now made it back out to http://opensource.apple.com/source/clang/clang-703.0.31/src/tools/dsymutil/ (and https://github.com/llvm-mirror/llvm/tree/master/tools/dsymutil). 

Once we get it working, `dsymutil` would also allow us to put debug info into a separate output from the main derivation, which would be cute.

**Comment by copumpkin** [comment]
cc @pikajude @gridaphobe

**Comment by periklis** [comment]
AFAIK we disable the current impure utils like dsymutil in `binutils/default.nix`, don't we?
However, is there any temporary to use the impure ones until the merge happens?
In my case, i try to build to valgrind for osx and it fails on the install-step, because it tries to dsymutil some shared libraries and the like.

**Comment by periklis** [comment]
btw, can't we introduce dsymutil like install_name_tool as an opt-in tool in all-packages for those who like to use the impure binaries from apple.

**Comment by periklis** [comment]
I just push a PR #23393 for discussion on the valgrind case

**Comment by matthewbauer** [comment]
llvm-dsymutil is available through llvmPackages.llvm. Okay to close?

**Comment by copumpkin** [comment]
Is it actually full-featured? For the longest time, `llvm-dsymutil` was neutered compared to the official Apple one.

**Comment by copumpkin** [comment]
And by neutered, I don't mean deliberately, but more that Apple hadn't merged back their changes to LLVM in over a year, which was the period when they replaced their fully homegrown `dsymutil` with the LLVM version (and thus filled out all the missing features in it). Judging by https://github.com/llvm-mirror/llvm/commits/master/tools/dsymutil it looks like a fair amount has happened since then, but in that case we should probably stop putting a dummy `dsymutil` into `cctools` and actually just symlink to the LLVM one.

**Comment by matthewbauer** [comment]
This is now part of the Darwin stdenv:

https://github.com/NixOS/nixpkgs/commit/0a996c8ef31eb5ffb55d24dc4703fe0fe29589ff
