### ISSUE TITLE
Searching is broken for every Haskell compiler except GHC801

### ISSUE THREAD

**Issue by jezen** [NixOS/nixpkgs#17752]
## Issue description

With the following command, I am able to browse a list of available Haskell packages:

```
nix-env -f "<nixpkgs>" -qaP -A haskellPackages
```

However, when I specify an older compiler like this…

```
nix-env -f "<nixpkgs>" -qaP -A haskell.packages.ghc7103
```
…I am met by the following error:

```
error: attribute ‘Glob_0_7_9’ missing, at /nix/store/brv5102ay5lkp4b0idfxyf0nw30pdd2l-nixpkgs-16.09pre88195.26d2577/nixpkgs/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix:212:32
```

According to Freenode IRC user `kmicu`, the same is true of _any_ compiler version older than GHC 8.0.1.

## Technical details

* System: Ubuntu 12.04 LTS
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre88195.26d2577

**Comment by peti** [comment]
This is intended behavior and it's clearly stated in the Nixpkgs manual.

**Comment by rasendubi** [comment]
`nix-env -f "<nixpkgs>" -qaP -A haskell.packages.ghc7103` works for me. (As well as for `haskellPackages`.)
