### ISSUE TITLE
ldc fails to build for aarch64-linux

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#177637]
### Steps To Reproduce
1. build *ldc* for `aarch64-linux` with `nix-build -E '(import <nixpkgs> { crossSystem = "aarch64-linux" ; }).ldc'`

### Build log

[gist](https://gist.github.com/very-good-fish/870a5b4b479f27bf7c3714c04798f73c)

### Additional context

While trying to solve this on my own, I was able to get past the ldc-bootstrap missing library by using an overlay to create an `ldcBootstrap` package that provided the library.

However, `ldc` still failed to build after that.

```
$ nix-build -I nixpkgs-overlays="$PWD/ldc-bootstrap.nix" -E '(import <nixpkgs> { crossSystem = "aarch64-linux" ; }).ldc' 2>&1 | tee ~/ldc.log
```

```
# $PWD/ldc-bootstrap.nix
[
	(
		self: super: {
			ldcBootstrap = (
				super.callPackage <nixpkgs/pkgs/development/compilers/ldc/bootstrap.nix> {}
			).overrideAttrs ( previousAttrs: {
				buildInputs = previousAttrs.buildInputs ++ [ super.stdenv.cc.cc.lib ];

				preFixup = ''
				addAutoPatchelfSearchPath $(
					find ''${buildInputs} \( -ipath '*/${super.stdenv.hostPlatform.config}/lib' -a -type d \)
				)
				'';
			});
		}
	)
]
```

[gist](https://gist.github.com/very-good-fish/2f91d4439f9eb5e2e98da5468ec9c6a3)

### Notify maintainers
@ThomasMader
@lionello

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.112-1.fc32.qubes.x86_64, Debian GNU/Linux, 11 (bullseye), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(user): `"nixos-21.11.337846.2a9a64710a3, nixpkgs-22.11pre385191.3c2068d6c90"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/user/channels/nixpkgs`
```

**Comment by abathur** [comment]
Closing since I don't think this is actionable. https://hydra.nixos.org/job/nixpkgs/trunk/ldc.aarch64-linux/all indicates successful aarch64-linux builds both now and at the time of this report. The user (and their logged gists) are gone, so we wouldn't even know if we duplicated this failure...
