### ISSUE TITLE
fetchurl can‘t be used to download files (like the nix-index database) which contain hashes in the closure of fetchurl

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#177660]
### Describe the bug

I encounter an `error: unexpected end-of-file` when downloading a binary file with fetchurl.

Bisection shows that this probably a regression introduced by https://github.com/NixOS/nixpkgs/pull/172962.

All this happens in my checkout of nixpkgs:

```commandline
❯ git log --oneline | head -n2
1d44ac176ce treewide: add enableParallelBuilding's to bootstrap packages so hashes stay the same
39a2f446959 Merge staging-next into staging
```
### Steps To Reproduce

After commit:
```
❯ git checkout 1d44ac176ce
Previous HEAD position was 39a2f446959 Merge staging-next into staging
HEAD is now at 1d44ac176ce treewide: add enableParallelBuilding's to bootstrap packages so hashes stay the same
❯ nix-build -E 'with import ./. {}; fetchurl  { url = "https://github.com/maralorn/nix-index-database/releases/download/2022-06-14/index-x86_64-linux"; sha256 = ""; }'
warning: found empty hash, assuming 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
this derivation will be built:
  /nix/store/8m7rh978gmqhj1yfs8sq76hgxcyzvnxk-index-x86_64-linux.drv
building '/nix/store/8m7rh978gmqhj1yfs8sq76hgxcyzvnxk-index-x86_64-linux.drv'...

trying https://github.com/maralorn/nix-index-database/releases/download/2022-06-14/index-x86_64-linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 42.6M  100 42.6M    0     0  24.3M      0  0:00:01  0:00:01 --:--:-- 29.2M
error: unexpected end-of-file
```

### Expected behavior

Before commit:
```
❯ git checkout 39a2f446959
Previous HEAD position was 1d44ac176ce treewide: add enableParallelBuilding's to bootstrap packages so hashes stay the same
HEAD is now at 39a2f446959 Merge staging-next into staging
❯ nix-build -E 'with import ./. {}; fetchurl  { url = "https://github.com/maralorn/nix-index-database/releases/download/2022-06-14/index-x86_64-linux"; sha256 = ""; }'
warning: found empty hash, assuming 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
this derivation will be built:
  /nix/store/pwhd6xkxyjw6vhwslp121acgqfhcxck1-index-x86_64-linux.drv
building '/nix/store/pwhd6xkxyjw6vhwslp121acgqfhcxck1-index-x86_64-linux.drv'...

trying https://github.com/maralorn/nix-index-database/releases/download/2022-06-14/index-x86_64-linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 42.6M  100 42.6M    0     0  20.8M      0  0:00:02  0:00:02 --:--:-- 28.2M
error: hash mismatch in fixed-output derivation '/nix/store/pwhd6xkxyjw6vhwslp121acgqfhcxck1-index-x86_64-linux.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-LAU2aqk0GRIY5rfigwQ23l3PuEOoqhCg59fTsT7GH4U=
```

The hash mismatch is the expected behavior. It means that the download went well until this point.

### Additional info

nix-index-databases are binary blobs. I tried different ones and got the same error. strangely the error does not happen when downloading the darwin nix-index-database.

### Notify maintainers

@siraben @Artturin @SuperSandro2000 @Mindavi

I currently have the bisect cached on my system, so I can gladly test different things, if required.

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-21.03pre260787.56bb1b0f7a3"`
 - channels(maralorn): `""`
 - nixpkgs: `/etc/nix-path/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
Can reproduce it even on nixos-unstable where the mentioned commit did not land yet.
A bit clueless on the actual problem tbh.

**Comment by maralorn** [comment]
@SuperSandro2000 are you sure? According to https://nixpk.gs/pr-tracker.html?pr=172962 the PR is already in unstable, which is not surprising since it’s twenty days old.

**Comment by maralorn** [comment]
For debugging purposes I have inserted a `ls -lh $out` right before the `exit 0` in the fetchurl builder.sh. It prints:
`-rw-r--r-- 1 nixbld nixbld 43M Jun 14 17:23 /nix/store/5aaa60q677aflnin86qas5hgqp2mlbc0-index-x86_64-linux`

So the derivation is successful, but then Nix encounters an error? Especially since Nix doesn’t give the usual “builder failed” message. It just aborts.

But if this is a Nix bug, what does that have to do with a change in nixpkgs?

**Comment by Mindavi** [comment]
Sometimes changes in nixpkgs expose nix bugs.

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 are you sure? According to [nixpk.gs/pr-tracker.html?pr=172962](https://nixpk.gs/pr-tracker.html?pr=172962) the PR is already in unstable, which is not surprising since it’s twenty days old.

Then GitHub fooled me.

**Comment by pennae** [comment]
might be an instance of <https://github.com/NixOS/nix/issues/6660>/<https://github.com/NixOS/nix/issues/5509>

**Comment by maralorn** [comment]
@pennae Oh, yeah you are right! This does not have anything to do with the mentioned PR. When I turn up the verbosity I get: 
```
scanning for references for output 'out' in temp location '/nix/store/46mpv8vifpdb1dhg3pc8y7c51r8bsx0b-index-x86_64-linux.drv.chroot/nix/store/5aaa60q677aflnin86qas5hgqp2mlbc0-index-x86_64-linux'
found reference to 'fz33c1mfi2krpg1lwzizfw28kj705yg0' at offset '33169'
```
that reference belongs to glibc. Of course the nix-index database contains tons of hashes of the packages currently in nixos-unstable. This explains why this looks like a regression, because fetchurl can‘t be used on a nix-index databases which contains a hash of one of the inputs of fetchurl. An old enough database should probably work. Also this explains why I have no trouble downloading the darwin db, but it probably won‘t work for people on darwin, which is kinda unfortunate.

It remains a) the question how to workaround it. And b) that the error message in Nix is really unhelpful.

**Comment by thufschmitt** [comment]
> If anyone has an idea how to work around this, please tell me

If you're OK with a fairly dirty workaround, you can `base64` (or even `rot13`) the output in `postFetch` (to hide the references) and have a (non fixed-output) wrapper that decodes it

**Comment by maralorn** [comment]
thx thufschmitt!

The problem is, that that will break my usage of nix-prefetch-url.

It appears I can use pkgsStatic.busybox to do the download without pulling in any inputs with a hash in the database.
