### ISSUE TITLE
Handle -nostdinc++ properly in cc-wrapper.sh

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#17769]
I'm running into an awkward situation when trying to shift the darwin stdenv to use llvm 3.8 (all part of the broader darwin renovation effort). Basically `libc++abi` passes `-nostdinc++` to its build, because it manually passes in the `libc++` headers by hand in some way that pleases it more. Unfortunately, our `libc++` setup hook still goes and appends its `-isystem` parameter, which then messes up the build due to some nasty interaction between `#include_next` and double-include prevention.

cc @shlevy @abbradar @vcunat as people who might know how best to handle this. I'd post how to reproduce this situation but it's in the stdenv bootstrap and involves two separate nixpkgs trees, so it's not the most pleasant situation to reproduce/test in.

**Comment by copumpkin** [comment]
So to make this a little more concrete, the `libc++abi` build invokes:

```
clang++
	-I/path/to/libcxxabi-3.8.0.src/include
	-I/path/to/libcxx-3.8.0.src/include
	-nostdinc++
	-c /path/to/source.cpp
```

and gets this search path:

```
#include <...> search starts here:
 /path/to/libcxxabi-3.8.0.src/include
 /path/to/libcxx-3.8.0.src/include
 ...
 /path/to/system/libcxx/include
 /path/to/system/libcxx/include/c++/v1
 ...
```

Which then breaks it because `libc++` now doesn't like appearing twice in the search path due to some unfortunate `#include_next` behavior. I think that's why we could get away with this before and can't now.

**Comment by abbradar** [comment]
That's because we don't handle `-nostdinc` and `-nostdinc++` in the wrapper (if I understood the problem correctly), which should be fixed anyway. Try [this patch]((https://github.com/abbradar/nixpkgs/commit/9b1c5cdee533841d3dde070f9973102a2969fb9c).

**Comment by dtzWill** [comment]
Haha I have a very similar patch locally, @abbradar although I don't handle `-nostdinc`.  Can confirm works great for fixing libc++abi build at least in my non-darwin local tree,

If we're looking to accept the patch I'd suggest not intercepting "-nostdinc" unless we handle it's primary use: removing libc/etc paths from header search.  Offhand I'm not sure whether it removes C++ headers from search path or not, I'd guess it does but would have to check :).

**Comment by abbradar** [comment]
We pass those flags to GCC, too, which will remove libc. It works like this:

1. GCC has a hardcoded path to glibc via `--with-native-system-header-dir`. It will handle its removal itself;
2. But it doesn't know about path to C++ library. We handle this in wrapper, both for `--nostdinc` and `-nostdinc++`.

**Comment by dtzWill** [comment]
Oh, indeed! Awesome, well then great and thank you.  LGTM then! :)

**Comment by abbradar** [comment]
I'll wait till @copumpkin tests it for his case and make a PR to staging then. Thanks for looking at it!

**Comment by copumpkin** [comment]
Thanks! I'll try it out this evening

**Comment by copumpkin** [comment]
@abbradar 👍👍👍👍👍👍👍👍👍👍 seems to be working! Still building the rest of the stdenv so I don't know if something subtle will break later on, but it seems unlikely.

**Comment by dtzWill** [comment]
(Is this issue ready to be closed then? Or still testing? :))

**Comment by abbradar** [comment]
Indeed, we can close.

**Comment by teto** [comment]
Seems like I still have the problem in a nix-shell with llvm_4/clang

I am trying to compile some out of tree ebpf extension but even with -stdinc, glibc headers (and zlib are still picked up). I am on nixos-unstable.
```
$ clang  -O2 -emit-llvm -nolibc -nostdinc -c test_ebpf_tc.c -v -I/home/teto/mptcp/build/include -I /home/teto/mptcp/build/arch/x86/include/generated/   -include /home/teto/mptcp/include/linux/kconfig.h -E >toto
clang version 5.0.2 (tags/RELEASE_502/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin
Found candidate GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib/gcc/x86_64-unknown-linux-gnu/7.3.0
Found candidate GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0
Selected GCC installation: /nix/store/5d2njc16vdwq5ivc8y53cdlr63vmbzpf-gcc-7.3.0/lib64/gcc/x86_64-unknown-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
clang-5.0: warning: argument unused during compilation: '-nolibc' [-Wunused-command-line-argument]
 "/nix/store/lwhakjfxvz93dswnwicxcmqr4p6ckiqc-clang-5.0.2/bin/clang-5.0" -cc1 -triple x86_64-unknown-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test_ebpf_tc.c -mrelocation-model pic -pic-level 2 -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -v -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/teto/testbed/test_ebpf_tc.gcno -nostdsysteminc -nobuiltininc -resource-dir /nix/store/sn0yjh2wcd7243chgb1yyz1vg26lis7g-clang-wrapper-5.0.2/resource-root -include /home/teto/mptcp/include/linux/kconfig.h -idirafter /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include -isystem /nix/store/bknhdy2d2919ni794mnr7hy0warkwydl-llvm-4.0.1/include -isystem /nix/store/i1lyv0v01z1ivndra433kvmaagfhlmym-ncurses-6.1-dev/include -isystem /nix/store/ggdq1si53c6qb0b67lgx145xkndfy4zy-zlib-1.2.11-dev/include -isystem /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include -isystem /nix/store/bknhdy2d2919ni794mnr7hy0warkwydl-llvm-4.0.1/include -isystem /nix/store/i1lyv0v01z1ivndra433kvmaagfhlmym-ncurses-6.1-dev/include -isystem /nix/store/ggdq1si53c6qb0b67lgx145xkndfy4zy-zlib-1.2.11-dev/include -isystem /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include -isystem /nix/store/bknhdy2d2919ni794mnr7hy0warkwydl-llvm-4.0.1/include -isystem /nix/store/i1lyv0v01z1ivndra433kvmaagfhlmym-ncurses-6.1-dev/include -isystem /nix/store/ggdq1si53c6qb0b67lgx145xkndfy4zy-zlib-1.2.11-dev/include -isystem /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include -D _FORTIFY_SOURCE=2 -I /home/teto/mptcp/build/include -I /home/teto/mptcp/build/arch/x86/include/generated/ -O2 -Wformat -Wformat-security -Werror=format-security -fdebug-compilation-dir /home/teto/testbed -ferror-limit 19 -fmessage-length 272 -fwrapv -stack-protector 2 -stack-protector-buffer-size 4 -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o - -x c test_ebpf_tc.c
clang -cc1 version 5.0.2 based upon LLVM 5.0.2 default target x86_64-unknown-linux-gnu
ignoring duplicate directory "/nix/store/bknhdy2d2919ni794mnr7hy0warkwydl-llvm-4.0.1/include"
ignoring duplicate directory "/nix/store/i1lyv0v01z1ivndra433kvmaagfhlmym-ncurses-6.1-dev/include"
ignoring duplicate directory "/nix/store/ggdq1si53c6qb0b67lgx145xkndfy4zy-zlib-1.2.11-dev/include"
ignoring duplicate directory "/nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include"
ignoring duplicate directory "/nix/store/bknhdy2d2919ni794mnr7hy0warkwydl-llvm-4.0.1/include"
ignoring duplicate directory "/nix/store/i1lyv0v01z1ivndra433kvmaagfhlmym-ncurses-6.1-dev/include"
ignoring duplicate directory "/nix/store/ggdq1si53c6qb0b67lgx145xkndfy4zy-zlib-1.2.11-dev/include"
ignoring duplicate directory "/nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/teto/mptcp/build/include
 /home/teto/mptcp/build/arch/x86/include/generated
 /nix/store/bknhdy2d2919ni794mnr7hy0warkwydl-llvm-4.0.1/include
 /nix/store/i1lyv0v01z1ivndra433kvmaagfhlmym-ncurses-6.1-dev/include
 /nix/store/ggdq1si53c6qb0b67lgx145xkndfy4zy-zlib-1.2.11-dev/include
 /nix/store/pi0lr4cj88vig3s5bwl6dpnrvvpc9css-compiler-rt-5.0.2-dev/include
 /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include
End of search list.

```

**Comment by teto** [comment]
what is strange is that even after unsetting NIX_TARGET_CFLAGS_COMPILE / NIX_CFLAGS_COMPILE, there is still glibc included (even though a env|grep  /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include won't return anything)
 ```
#include "..." search starts here:
#include <...> search starts here:
 /home/teto/mptcp/build/include
 /home/teto/mptcp/build/arch/x86/include/generated
 /nix/store/z10kkr081zb02kyjw8ybf2s9zll49cvx-glibc-2.27-dev/include
End of search list.

```

**Comment by teto** [comment]
It seems the libc is unconditionnaly included due to the https://github.com/NixOS/nixpkgs/blob/29387fbbe98c6ad0c554dd2ccfc81456b2ec5419/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L25

-> https://github.com/NixOS/nixpkgs/blob/29387fbbe98c6ad0c554dd2ccfc81456b2ec5419/pkgs/build-support/cc-wrapper/add-flags.sh#L34 call
