### ISSUE TITLE
`boot.initrd.network.ssh.enable` breaks initrd build

### ISSUE THREAD

**Issue by elitak** [NixOS/nixpkgs#17767]
## Issue description

Support for running dropbear in init-stage-1 is broken. The initrd cannot be generated when this option is enabled.

### Steps to reproduce

1. add `boot.initrd.network.ssh.enable = true;` to configuration.nix
2. set `boot.initrd.network.ssh.hostRSAKey` as well, to avoid the failed assertion
3. `nixos-rebuild build`

### Potential Fix

The problem has something to do with dropbear pulling in libnss, libc when it's not supposed to. I think dropbear should be rebuilt using static linking anyway, so my proposed fix is:

    diff --git a/nixos/modules/system/boot/initrd-ssh.nix b/nixos/modules/system/boot/initrd-ssh.nix
    index d0a4ce5..0c59560 100644
    --- a/nixos/modules/system/boot/initrd-ssh.nix
    +++ b/nixos/modules/system/boot/initrd-ssh.nix
    @@ -91,8 +91,7 @@ in
         } ];
     
         boot.initrd.extraUtilsCommands = ''
    -      copy_bin_and_libs ${pkgs.dropbear}/bin/dropbear
    -      cp -pv ${pkgs.glibc.out}/lib/libnss_files.so.* $out/lib
    +      copy_bin_and_libs ${pkgs.dropbear.override { enableStatic=true; }}/bin/dropbear
         '';
     
         boot.initrd.extraUtilsCommandsTest = ''

Dropbear fails to build statically though, so I abandoned the endeavor at this point, since I'm not even sure I know what the real problem is. Removing that `cp -pv` line does fix the build, at least.

## Technical details

* System: "16.03pre75806.77f8f35"
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09.git.ee23909 (Flounder)

**Comment by abbradar** [comment]
I cannot reproduce this on latest master nor on ee23909. Can you paste your log output?

**Comment by elitak** [comment]
It's that `cp -pv` step that fails in extra-utils. I'm not sure why. By the way, is there a flag to set somewhere on the command line so I get `set -x` in every bash script?

Attached is the build log, but it doesn't look very helpful.

[dropbear-failure.log.txt](https://github.com/NixOS/nixpkgs/files/421325/dropbear-failure.log.txt)

**Comment by abbradar** [comment]
I _feel_ this is https://github.com/NixOS/nixpkgs/issues/17513. Try applying https://github.com/NixOS/nixpkgs/pull/17596/commits/68922e3f7407c5aecd8cc9cc3d22d753269b3f31 and see if it helps.

**Comment by elitak** [comment]
Yeah, that fixed it. Thanks.
