### ISSUE TITLE
`nixos-generate-config` does not set `nixpkgs.system` (purity, flakes)

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#177664]
### Describe the bug

Observing that
 - We try to avoid `currentSystem` these days.
 - The CPU platform is part of the hardware

it would seem logical to set `nixpkgs.system` in `hardware-configuration.nix`.

### Steps To Reproduce
1. apply https://github.com/NixOS/nixpkgs/pull/177012
2. write a flake with `nixosSystem { modules = [ ./configuration.nix ./hardware-configuration.nix ]; }`
3. :boom:

### Expected behavior

`hardware-configuration.nix` records the `system`.

### Additional context

I tried to perl, but I can't. I was almost there.

`nixos-generate-config.pl`:
```perl

# nixpkgs.system
my ($status, @systemLines) = runCommand("nix-instantiate --impure --eval --expr builtins.currentSystem");
if ($status != 0 || join("", @systemLines) =~ /error/) {
    die "Failed to retrieve current system type from nix.\n";
}
my $system = chomp(@systemLines[0]);
push @attrs, "nixpkgs.system = lib.mkDefault $system;";
```

It generates the following, if you would believe it.

```
  nixpkgs.system = lib.mkDefault 1;
```

### Notify maintainers

Many people maintain NixOS. I know @grahamc knows perl.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by pennae** [comment]
`chomp(my $system = $systemLines[0]);` *should* be the thing you're looking for? :thinking:
