### ISSUE TITLE
nextcloud (23+) config is broken when using objectstore because of a missing comma

### ISSUE THREAD

**Issue by mickours** [NixOS/nixpkgs#177683]
There is a missing comma at the end of this line:
https://github.com/NixOS/nixpkgs/blob/9ff91ce2e4c5d70551d4c8fd8830931c6c6b26b8/nixos/modules/services/web-apps/nextcloud.nix#L736

Because the opbjectstore config in injected after this line, It make the config parsing fails with this error:
```
Jun 13 10:30:48 nixos nextcloud-setup-start[2012374]: ParseError: syntax error, unexpected single-quoted string "objectstore", expecting "]" in /nix/store/7jvy28bxljxjc2xdy1zzf6xq0dd20xcj-nextcloud-config.php:39
```

Happen on Nixos 22.05 with nextcloud 24

**Comment by Luflosi** [comment]
This has been fixed in #175165.
