### ISSUE TITLE
KMPlayer doesn't install: Unknown CMake command "check_include_files"

### ISSUE THREAD

**Issue by sindikat** [NixOS/nixpkgs#17760]
## Issue description

Trying to install kmplayer fails with the following error:

```
CMake Error at CMakeLists.txt:61 (check_include_files):
  Unknown CMake command "check_include_files".
```
### Steps to reproduce

Run `nix-env -iA nixos.kde4.kmplayer`
## Technical details
- System: 16.09pre88185.52a875f (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre88185.52a875f"

**Comment by Profpatsch** [comment]
Sorry that there was no reply. Can you still reproduce this error?
