### ISSUE TITLE
[gnome3] DejaDup missing

### ISSUE THREAD

**Issue by s1lvester** [NixOS/nixpkgs#17763]
## Issue description
Hi all,

[dejaDup](https://wiki.gnome.org/Apps/DejaDup) is a good graphical frontend for duplicity which integrates seamlessly into the gnome-desktop. I'm still learning about nixos and am in no way proficient enough to package this myself. Could someone from the gurus using gnome3 please try to package this? Thx so much!

NixOS v. 16.03 #

**Comment by s1lvester** [comment]
This is a first try at an nix expression, unfortunately it doesn't compile because vala doesn't seem to support libsecret apis

```nix
{ stdenv, fetchurl, cmake, pkgconfig, vala, 
  gettext, gnome3, libnotify, intltool, itstool, 
  glib, gtk3, packagekit, libsecret, ... }:

stdenv.mkDerivation rec {
  name = "dejadup-${version}";
  version = "34.2"; 

  src = fetchurl {
    url = "https://launchpad.net/deja-dup/34/34.2/+download/deja-dup-34.2.tar.xz";
    sha256 = "ff30732f28233e2422d069f1769a725d4a39c91a279c3bf885c4162fd85818bb";
  };

  doCheck = true;
  buildInputs = [ cmake pkgconfig vala gettext libnotify 
                  gnome3.libpeas intltool itstool glib gtk3 
                  packagekit libsecret ];

  meta = {
    description = "Déjà Dup is a simple backup tool. It hides the complexity of backing up the Right Way (encrypted, off-site, and regular) and uses duplicity as the backend.";
    homepage = "https://launchpad.net/deja-dup";
    license = stdenv.lib.licenses.gpl3;
    maintainers = with stdenv.lib.maintainers; [ s1lvester ];
    platforms = with stdenv.lib.platforms; linux;
  };
}
```

**Comment by abbradar** [comment]
Welcome to NixOS! That's a good start; could you perhaps open a PR with it? This would allow us to review and comment on individual lines of code easily.

**Comment by s1lvester** [comment]
Thank you for the warm welcome. Here is a PR cherry-picked onto current master: #17844
