### ISSUE TITLE
gopls fails due to `GOPROXY=off`

### ISSUE THREAD

**Issue by WhyNotHugo** [NixOS/nixpkgs#177632]
### Describe the bug

`GOPROXY=off` is set when building nix packages to avoid `go` itself from performing any network access to fetch new versions and alike.

gopls seems to somehow "retain" this value; even when using `GOPROXY=direct gopls`, it still uses value `off`. I think maybe this value is baked into the binary at build time...?

When trying to perform code navigations, it errors:

```
gopls: 0: err: exit status 1: stderr: go: github.com/adrg/xdg@v0.3.3: module lookup disabled by GOPROXY=off                  
go: github.com/adrg/xdg@v0.3.3: module lookup disabled by GOPROXY=off
```

Note that this affects `gopls` at runtime; module resolution is necessary for things like code navigation.

### Steps To Reproduce

- Set up any code editor (e.g.: neovim) to run `gopls` for go code.
- Open a codebase which uses _any_ external module.
- Try to execute a "go to definition".

### Expected behavior

Should work.

### Notify maintainers

@mic92 @rski @SuperSandro2000 @zimbatm

### Metadata

```console
> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.2-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(hugo): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/hugo/channels/nixpkgs`

```

**Comment by rski** [comment]
can you post the output of go env and possibly that of `cat $(go env GOENV)`?

**Comment by SuperSandro2000** [comment]
Are you using nix-shell? Is that variable somehow bleeding into your environment?

**Comment by WhyNotHugo** [comment]
I'm setting `GOPROXY="direct"` explicitly myself.

**Comment by rski** [comment]
are you using some variant of vim? what does :echo $GOPROXY say?

**Comment by WhyNotHugo** [comment]
> are you using some variant of vim?

I'm using this flake: https://git.sr.ht/~whynothugo/dotfiles/tree/7e106262/item/v/flake.nix

I've added  `pkgs.go` to line 19 for debugging this too.

> what does :echo $GOPROXY say?

`direct`

**Comment by WhyNotHugo** [comment]
```console
> which gopls
/nix/store/sbi3zrg9h4ik0aci6d2wbqif8skwa23g-gopls-0.8.4/bin/gopls

> file $(which gopls)
/nix/store/sbi3zrg9h4ik0aci6d2wbqif8skwa23g-gopls-0.8.4/bin/gopls: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamicall
y linked, interpreter /nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/ld-linux-x86-64.so.2, Go BuildID=lMqRYihlEr0n
5Y8uaH-C/jJSgXPAEN4D-L3AnGUNN/Yat0zj3QOjI43Ooah3bF/oigJ1siUX9Wl-And8ilC, not stripped
```

**Comment by rski** [comment]
I read the source a bit, and have two suggestions:
- what if you build gopls from source in this workspace? does that work?
- does setting [allowImplicitNetworkAccess](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#allowimplicitnetworkaccess-bool) work around this issue?
- 
Admittedly, I think gopls is getting confused somehow here and setting GOPROXY=off when it should not

**Comment by rski** [comment]
there is also https://github.com/golang/go/issues/53313 upstream. At this point I think it's very unlikely it is a nix specific issue. Perhaps it is some interaction with the text editor lsp plugin that is causing this. The go repo has instructions on how to debug this https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capture-logs

**Comment by rski** [comment]
to be clear, if setting [allowImplicitNetworkAccess](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#allowimplicitnetworkaccess-bool) works, then it definitely is not a nix issue as that would mean gopls injecting the variable.

**Comment by Mic92** [comment]
Is it some sort of security feature that the authors of `gopls` don't want to this network access or what is the reasoning behind it?

**Comment by rski** [comment]
the reasoning is explained in https://github.com/golang/tools/commit/43adb69d7e9407736bb2eda6bc96c80299187b0e

**Comment by WhyNotHugo** [comment]
> I read the source a bit, and have two suggestions:
>
>     what if you build gopls from source in this workspace? does that work?
>     does setting allowImplicitNetworkAccess work around this issue?

I'm not building `gopls`; I'm using the one provided by nixpkgs as_is. I'm not
entirely certain how to build it inside this environment. Any pointers?

---

FWIW, the arch package works out the box, and doesn't seem to be changing any upstream defaults. This makes me think it's _not_ an upstream issue: https://github.com/archlinux/svntogit-community/blob/packages/gopls/trunk/PKGBUILD

---

Using `-logfile` creates an empty log file and never writes anything to it, even when using `-vv`.

Does `gopls` work for anyone else here? I find that for projects with _any_ dependencies, most functionality will fail entirely with the same error.

**Comment by WhyNotHugo** [comment]
Indeed, the issue was DNS not working in this environment. The error wrong error message is shown (this sounds like a bug in `gopls`), and that sent on a wild goose chase.

Thanks for the assistance here, sorry for the noise!

**Comment by rski** [comment]
wow, never would have guessed that
