### ISSUE TITLE
ytmdesktop: 1.13.0 -> v1.17.0

### ISSUE THREAD

**Issue by ciferkey** [NixOS/nixpkgs#177793]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: ytmdesktop

current version: 1.13.0 
desired version: [v1.17.0](https://github.com/th-ch/youtube-music/releases/tag/v1.17.0) note it seems they added a "v" to the front of the version

###### Notify maintainers

maintainers: @LogicalOverflow 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by LogicalOverflow** [comment]
Thanks for the issue, but the `ytmdesktop` package does not package https://github.com/th-ch/youtube-music (which you linked in the issue), but https://github.com/ytmdesktop/ytmdesktop, whose latest stable release still is 1.13.0. I'll close this issue for now, but feel free to create a new packaging request (or to turn this issue into one and re-open it).

(Having had a quick look at it, it does look like an interesting alternative for me. I *might* get around to packaging it, but most likely not in the next few week.)

**Comment by ciferkey** [comment]
Thanks for the follow up. The current app no longer starts up and just crashes immediately on launch. So switching may be the only solution.
