### ISSUE TITLE
GNOME Evolution restore does nothing

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#177703]
### Describe the bug

Importing the configuration of one GNOME Evolution instance in another does nothing. I'm not sure which of the [log messages](https://gist.github.com/l0b0/264f627ccad6e563f28b999d036d3fbe) is the core issue, hence the vague title.

### Steps To Reproduce
1. Set `config.environment.systemPackages` to include `pkgs.evolution`
2. Build the configuration
3. Reboot
1. Use File → Back Up Evolution Data… to create a configuration backup
4. Move the resulting tarball to another machine with a hitherto unused and unconfigured Evolution
5. Start Evolution
6. In the "Restore From Backup" step of the configuration wizard, tick "Restore from a backup file:" and select the tarball above
7. Wait for the progress bar to disappear and Evolution to restart

At this point, Evolution shows an empty local calendar (there should be another calendar there) and if I go back to the email view it re-opens the configuration wizard.

I also tried to remove `pkgs.evolution` from `config.environment.systemPackages` and instead set `programs.evolution.enable = true;`, but that seems to result in just [more error messages](https://gist.github.com/l0b0/ace055ed6c05c925fd212fe8a70d16f3).

I also tried [this](https://github.com/NixOS/nixpkgs/issues/12756), setting `services.gnome.evolution-data-server.enable = true;` and `services.gnome.gnome-settings-daemon.enable = true;`, but the result seems to be the same.

### Expected behavior

The configuration should be imported.

### Additional context

Both machines are running Evolution 3.44.2 on NixOS 22.05.

### Notify maintainers
@bobby285271, @hedning, @jtojnar, @dasj19, @maxeaubrey

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.915.9ff91ce2e4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by symphorien** [comment]
did you try rebooting after the import? It looks like the only error is that evolution fails to quit in the error messages you showed.

**Comment by l0b0** [comment]
That worked! It never occurred to me that the import was successful. Hopefully the messaging can be fixed, though.
