### ISSUE TITLE
yarn2nix: support yarn v2 and yarn v3

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#177762]
### Describe the bug

[Yarn's PnP mode](https://yarnpkg.com/features/pnp) is really similar to Nix and it would be great if yarn2Nix supported it.

### Steps To Reproduce
1. In a new directory, create `.yarnrc.yml`:
   ```
   enableGlobalCache: true
   
   nmMode: hardlinks-global
   
   nodeLinker: pnp
   ```
2. create `package.json`:
   ```
   {
     "name": "yarntest",
     "packageManager": "yarn@3.2.1",
     "dependencies": {
       "bcrypt": "*"
     }
   }
   ```
3. Run `corepack yarn`
4. Run `yarn2nix` => crashes

### Expected behavior

Nix derivations that create a PnP compatible build.

There's a `.pnp.cjs` file that implements the resolution strategy and has the dependency hashes hardcoded; hashes and system-local binaries under .yarn/; and then a per-user hashed cache of the original modules under `~/.yarn/berry/cache`.

Node.js needs to be wrapped so it loads the `.pnp.cjs` file as a module.

### Additional context

When running Node.js in ESM mode, it needs an ESM loader instead of the pnp file, but the principle is the same.

Currently multiple loaders can't be composed. Node.js master can already chain multiple loaders, but that hasn't been released yet, and the loaders can't be loaded by previous loaders. This is called `ambient loaders` and [is being discussed](https://mtngs.io/nodejs/loaders-team/Sxm3l5V6GgM.html).

So using this to package ESM apps is not yet possible but should be.

**Comment by yu-re-ka** [comment]
yarn2nix in general only supports yarn v1. IMO this issue should be titled "yarn2nix support yarn v2 and yarn v3"

**Comment by wmertens** [comment]
See also https://discourse.nixos.org/t/yarn-plugnplay-and-direnv-packaging/19759/2 :thinking:

**Comment by wmertens** [comment]
going to close this as it's more for a separate tool like dream2nix to solve for now.
