### ISSUE TITLE
How to properly setup wayfire in nixos ?

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#177708]
What should I config the configuration.nix ,such as install some packages or services ?
Who can give me a right configuration.nix about wayfire?

**Comment by Nosirus** [comment]
I would not even be against a little more information.
Even a simple example might help

**Comment by prehonor** [comment]
> I would not even be against a little more information. Even a simple example might help

Sorry ,I should closed this issue ,beacause I have installed wayfire successfully.
This is my configuration.nix . https://github.com/prehonor/nixos/tree/master/nixpkgs-overlays/pkgs/applications/window-managers/wayfire
