### ISSUE TITLE
ghdl-llvm fails to build due to LLVM update

### ISSUE THREAD

**Issue by RRvW** [NixOS/nixpkgs#177748]
### Steps To Reproduce
1. build ghdl-llvm on unstable or 22.05: `NIX_PATH=nixpkgs=channel:nixpkgs-unstable nix-build '<nixpkgs>' -A ghdl-llvm`
2. Failure in configurePhase 

### Build log
```
configuring
configure flags: --prefix=/nix/store/rnpf4d7alf10x76b9bwsr11a3l3sbh26-ghdl-llvm-1.0.0 --enable-synth --with-llvm-config=/nix/store/hiaiw25qdb0sn3sj453885hqxhh0c4ql-llvm-11.1.0-dev/bin/llvm-config
Use full IEEE library
Build machine is: x86_64-unknown-linux-gnu
Unhandled version llvm 11.1.0
```

### Additional context
The current GHDL version in nixpkgs is 1.0.0, which handles LLVM upto version 11.0, but not 11.1. After 21.11, LLVM version 11.1 is the default, so the configure script fails. It can be solved by either:
 - Updating GHDL to 2.0 
 - Using LLVM 11.0 or lower as build input

### Notify maintainers
@Lucus16 @thoughtpolice 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.3, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(rijk): `"home-manager-21.11"`
 - channels(root): `"nixos-21.11.337846.2a9a64710a3, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by abathur** [comment]
Closing as complete since ghdl was updated to 2.0.0 in #194947 and appears to have been green on hydra since then.
