### ISSUE TITLE
HeroicGamesLauncher v2.2.6 is outdated

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#177882]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: heroic

current version:  2.2.6
desired version: 2.4.0 beta

###### Notify maintainers

maintainers: @WolfangAukang 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by bryanasdev000** [comment]
https://github.com/NixOS/nixpkgs/pull/179608
