### ISSUE TITLE
python buildEnv does not work for python packages outside of nixpkgs

### ISSUE THREAD

**Issue by Zer0-** [NixOS/nixpkgs#17785]
## Issue description

According to [the manual](http://nixos.org/nixpkgs/manual/#ssec-python-build-env)

> You can also use env attribute to create local environments with needed packages installed (somewhat comparable to virtualenv).

The example given works (if you change requests to requests2)

```
with import <nixpkgs> {};

(python3.buildEnv.override {
  extraLibs = with python3Packages;
    [ numpy
      requests2
    ];
}).env
```

However using a package that you have built yourself using buildPythonPackage does not work. `nix-shell` finishes successufully but you cannot run python and import the package.
### Steps to reproduce

I have made a very simple python package to test this with. All it does is serve up "hello world" via http on port 8000. I probably could have done something even simpler. So to reproduce:
1. Create a working directory, cd into it.
2. Execute `mkdir sources` -- we want to avoid cloning the source directory into our working directory otherwise we will get a false positive during the python import test (since `import trivial` will work if there is a directory named "trivial" here)
3. Execute `git clone https://code.vitrostudios.com/phil/trivial.git sources/trivial`
4. Create a file `default.nix` here with the contents given below
5. Execute `nix-shell --arg trivial_src ./sources/trivial default.nix`
6. Execute `python3.5 -c "import trivial"` inside the shell environment.
#### `default.nix` contents:

```
{ trivial_src }:

let
  pkgs = import <nixpkgs> {};
  trivial =
    pkgs.python35Packages.buildPythonPackage {
      name = "trivial";
      src = trivial_src;
      meta = {
        homepage = "https://code.vitrostudios.com/phil/trivial";
        description = "Test python package";
      };
    };
in
(pkgs.python35.buildEnv.override {
  extraLibs = 
    [ 
      trivial
    ];
}).env
```

The expected output is the command returns without failure or output.
What actually happens is this:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'trivial'
```
## Technical details
- System: NixOS: 16.03.1199.3234a4a (Emu)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.1199.3234a4a

**Comment by FRidh** [comment]
thanks for the report @Zer0- .

I've never actually used a `__main__.py` file myself, so there's a good chance I am wrong here, however, I think you're confusing `__main__.py` and `__init__.py`.

You're using `__main__.py` in which case you want to execute a module, and thus you need to use the `-m` flag when calling `python`.

Second, in your `__main__.py` you want to import from `trivial.application`. If there is no `__main__.py` inside your package that contains `import trivial.application` there is no way it can find that module.

If you make those changes, and also set `doCheck = false;` in the build expression of your package (unrelated issue) it will work.

**Comment by Zer0-** [comment]
>If there is no __init__.py inside your package that contains import trivial.application there is no way it can find that module

Crap you're right!

**Comment by FRidh** [comment]
@Zer0- I guess you accidentally reopened it so I am closing it now again.

**Comment by Zer0-** [comment]
@FRidh You're totally correct about needing a __init__.py file and that worked for me. I have edited the trivial repo to include it. There is still something weird going on though, I hope it's just an error on my part.

If you split the build process into two steps, first a step using nix-build and a second step to launch the nix-shell with a python environment, then the import fails.

So modifying my opening post's steps, changing default.nix contents to be:

```
{ trivial_src }:

let
  pkgs = import <nixpkgs> {};
  jobs = {
    trivial = 
      pkgs.python35Packages.buildPythonPackage {
        name = "trivial";
        src = trivial_src;
        doCheck = false;
        meta = {
          homepage = "https://code.vitrostudios.com/phil/trivial";
          description = "Test python package";
        };
      };
  };
in jobs
```

and also creating a shell.nix file with the contents:

```
{ trivial }:

let
  pkgs = import <nixpkgs> {};
in
(pkgs.python35.buildEnv.override {
  extraLibs = 
    [ 
      trivial
    ];
}).env
```

If I execute `nix-build --arg trivial_src ./sources/trivial default.nix` I get path to the store as an output.
Then I launch the shell with `nix-shell --arg trivial <store path from earlier step> shell.nix`
and execute `python3.5 -m trivial` as you said, the command still fails. Same with launching python and importing trivial, which as far as I know would work if I was using virtualenv.

Of course the difference here is I am passing the value for extraLibs through the nix-shell command line versus it being defined in the same nix expression. So that must be the root of the problem.

Sorry to bother you and reopen this, but I cannot figure it out.

**Comment by FRidh** [comment]
> You're totally correct about needing a init.py file 

its a __init__.py , not init.py. I did see you updated the repo correctly.

> Then I launch the shell with nix-shell --arg trivial <store path from earlier step> shell.nix
and execute python3.5 -m trivial as you said, the command still fails.

`nix-shell -p /nix/store/qjznavzsh5c6gg1p22lb1a2ihky7xyk0-python3.5-trivial` gives you a working shell with the package, not the env. So building the `trivial` package is at least working correctly.

But, you want the environment in a `nix-shell`, and by passing the store path. Well, that doesn't seem to be working as you've shown so let's try to find out why.

I put the expressions and source path together into one `shell.nix` file.
```
$ cat shell.nix 


let
  pkgs = import <nixpkgs> {};
  trivial = 
      pkgs.python35Packages.buildPythonPackage {
        name = "trivial";
        src = ./sources/trivial;
        doCheck = false;
        meta = {
          homepage = "https://code.vitrostudios.com/phil/trivial";
          description = "Test python package";
        };
      };
in
(pkgs.python35.buildEnv.override {
  extraLibs = 
    [ 
      trivial
    ];
}).env
```
Running `nix-shell --run "python3 -m trivial"` gives you the application. So that works.

I have no idea why this isn't working actually. It seems as `trivial` is passed, since otherwise there should have been an error, but then again, it doesn't actually do anything with it.

**Comment by FRidh** [comment]
actually, I think trivial is considered a string here, and in `buildEnv` it filters on derivations, so it is ignored.

**Comment by FRidh** [comment]
Using `builtins.toPath` with the sandbox turned off doesn't work either. 

Furthermore, why would that work. Its just a path that happens to be a store path. But Nix doesn't know that right, to Nix it can be any path. Also, it likely would need the .drv because it cannot determine from just a hash what was needed to build it. But, it can at least check for the .drv in the store. @copumpkin , do you have an idea? Can you pass a store path with `--arg` and use it as a derivation?

**Comment by Zer0-** [comment]
You can pass a store path to at least build things. For example if I were to make a package that depends on trivial (needs trivial in its propagatedBuildInputs list) then I can pass the store path to trivial as an --arg to nix-build and it works. So I assumed this was a valid workflow.

**Comment by Profpatsch** [comment]
I think the questions have been answered. Feel free to reopen, though.
