### ISSUE TITLE
Zathura packages are organized confusingly

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#17787]
## Issue description
With the following in my `configuration.nix`:
```nix
  environment.systemPackages = with pkgs; [
    zathura
    zathuraCollection.zathura_core
    zathuraCollection.zathura_pdf_poppler
  ];
```
When I launch zathura:
```bash
 zathura my-doc.pdf
```
I get the following error:
```
error: could not open plugin directory: /nix/store/2kr6n75x8yxqvnfgf75jr1z0lrzzp6y0-zathura-core-0.3.6/lib/zathura
error: Unknown file type: 'application/pdf'
```
And indeed, that directory doesn't exist:
```
/etc/nixpkgs > ls /nix/store/2kr6n75x8yxqvnfgf75jr1z0lrzzp6y0-zathura-core-0.3.6/lib 
pkgconfig
/etc/nixpkgs > ls /nix/store/2kr6n75x8yxqvnfgf75jr1z0lrzzp6y0-zathura-core-0.3.6/lib/pkgconfig
zathura.pc
```
However, when I install `zathura` with 
```
nix-env -i zathura
```
everything works as expected.

### Steps to reproduce
Install zathura with above config, try to open a PDF 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
```
16.09.git.5a501bd (Flounder)
```
* Nix version: (run `nix-env --version`)
```
nix-env (Nix) 1.11.2
```
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
"16.09.git.5a501bd"
```

**Comment by abbradar** [comment]
You shouldn't install plugins into your system path. Instead, install just `zathura` -- it's a wrapper that installs `zathura_djvu`, `zathura_ps` and `zathura_pdf_mupdf` (or `zathura_pdf_poppler` if you pass `useMupdf = false` to it). Unfortunately we still haven't done so that you can choose plugins more granularly, but it can be trivially implemented if needed.

**Comment by siddharthist** [comment]
@abbradar Thanks for the clarification. Is there a way we could make this more readily understood for users?

**Comment by abbradar** [comment]
Hmm, I don't have much ideas. Maybe renaming `zathuraCollection` somehow would help?

**Comment by rasendubi** [comment]
I must say I haven't had an issue with Zathura. I've just installed `zathura` and expected it to work -- that's what actually happened.

We can change `zathura`'s `name` to `zathura-with-plugins` (similar to `rxvt-unicode-with-xxx`). Don't change attribute path, though.

**Comment by the-kenny** [comment]
Is there a reason to keep `zathuraCollection` in `all-packages.nix` at all? Sounds like an implementation detail to me.
