### ISSUE TITLE
default config's `services.xserver.xkbOptions` is invalid

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nixpkgs#177811]
this is just blatantly invalid syntax, at least as far as I know:

https://github.com/NixOS/nixpkgs/blob/199933efdf5945792f149253256e983f0643cddb/nixos/modules/installer/tools/tools.nix#L161-L164

the correct format for the option is a comma-separated string.

**Comment by delroth** [comment]
I think this was fixed by https://github.com/NixOS/nixpkgs/pull/221576
