### ISSUE TITLE
flatpak update throws GLib-GIO:ERROR on NixOS 22.05

### ISSUE THREAD

**Issue by k-u-bux** [NixOS/nixpkgs#177847]
### Describe the bug

After upgrading to 22.05, some subcommands of flatpak abort throwing the error

GLib-GIO:ERROR:../gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
Bail out! GLib-GIO:ERROR:../gio/gsocketclient.c:1982:g_socket_client_enumerator_callback: assertion failed: (data->error_info->best_error)
Aborted (core dumped)

This affects notably 'flatpak update'.

### Steps To Reproduce
1. issue the command "flatpak update" on the command line

### Expected behavior
'flatpak update' completes without error and updates whichever packages can be updated.

### Notify maintainers
There seems to be an empty list of maintainers in 
pkgs/development/libraries/flatpak/default.nix

### Metadata
Output of `nix-shell -p nix-info --run "nix-info -m"` follows:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.14, NixOS, 22.05 (Quokka), 22.05.915.9ff91ce2e4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(bux): `"home-manager, nixos-22.05, nixos-20.03-20.03, nixos-20.09-20.09, nixos-21.05-21.05, nixos-21.11-21.11, nixos-22.05-22.05, nixos-unstable, nixpkgs-unstable"`
 - channels(root): `"nixos-22.05, nixos-21.11-21.11, nixos-22.05-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Best regards,

Kai-Uwe Bux

**Comment by Artturin** [comment]
same issue in https://www.reddit.com/r/archlinux/comments/tl7w0b/flatpak_cant_upgrade_or_install_after/

**Comment by k-u-bux** [comment]
The issue is resolved: the cause was an empty HTTP_PROXY variable.
