### ISSUE TITLE
nixosTest: allow tests to customize partition layout

### ISSUE THREAD

**Issue by T0astBread** [NixOS/nixpkgs#177963]
I would like to write integration tests with `nixosTest` that use different partition layouts in test VMs than the standard ext4-on-disk. My main motivation for that is being able to test systems with an ephemeral rootfs (AKA "erase your darlings"-type systems) with a filesystem/partition layout that's faithful to production.

The filesystem mounted at `/nix` would remain un-overridable since it's imperative to the way `nixosTest` works (afaict). But the filesystem setup script in the initrd could be overridden. I've hacked up a quick patch for this at https://github.com/T0astBread/nixpkgs/commit/c53891fa6594f653e2fc4e097c4c1f8e8244d88d, if that sounds approximately good to you I can open a proper PR.

**Comment by T0astBread** [comment]
This should also work for the `build-vm` command though I haven't tested that.

**Comment by roberth** [comment]
> ephemeral rootfs

Awesome.

> un-overridable since it's imperative to the way nixosTest works (afaict).

There's `virtualisation.useNixStoreImage`, which puts the relevant store paths in a disk image instead. I wouldn't recommend putting disk images in the store like that, but that's another option. Perhaps we could add an alternative to this. Variations on this could run the activation script as well, or build the image at the last minute, although both of those will be slower.

> I've hacked up a quick patch

I don't think we can change the default to one that disappears when user modules set it at the default priority.
It would break configurations like those in the `bees`, `ec2`, `glusterfs` and other tests.
To discard the default in your own configuration, you could use `lib.mkForce` instead.
Another small thing is to switch from `nixosTest` to the glue that the other tests use.
Feel free to open that PR.

**Comment by T0astBread** [comment]
Apologies for being a bit slow with the PR. I just accidentally destroyed my filesystem (unrelated to this issue) so I'm currently busy restoring things from backups. 😓

About using `mkForce`: `mkVMOverride` (which is used in `qemu-vm.nix`) has a higher priority than `mkForce`. Does that mean we should change the priority of `mkVMOverride` to give `mkForce` precedence? Or are you suggesting we use something else instead of `mkVMOverride` for the bootloader and filesystem options required here?

**Comment by roberth** [comment]
> Apologies for being a bit slow

Don't worry. Everyone contributes at their own pace.

> About using `mkForce`: `mkVMOverride` (which is used in `qemu-vm.nix`) has a higher priority than `mkForce`.

Ohh. I made a mistake. I thought they were the other way around. Changing them is a rather breaking change.

I think we've reached the point where `nixosTest` and `nixos-rebuild build-vm` have different requirements. A more sustainable solution I think is to refactor the module, to split it up into distinct modules with their own purposes and a common module. Probably most of it can be in the common module.
One trick we might use is a `mkVMOverride`-like function with a new name, that is not in `lib`, but in an internal option, so that we can make it behave the right way for each of the use cases. I'd like to avoid that if possible though.

**Comment by roberth** [comment]
> right?

NixOS is rather vulnerable to spacebar heating. We can't be sure, but it seems so.



> Could we perhaps check if the user has explicitly set `virtualisation.fileSystems."/"` (or `/boot`, `/nix`, etc.) and then use that value instead?

Not really feasible. We only get to access the final value.

Maybe we need to add a flag that can disable the default definitions. Explicit and minimal magic.



> And it also shouldn't cause problems with production configurations since those use `fileSystems` instead.

Seems so. Also in case of `build-vms`, users should be specifying their vm-only options in `vmVariant` anyway, and `nixosTest` configs are never production.

**Comment by T0astBread** [comment]
Cool, so does the following look like a plan to you:

  - Add an option called `virtualisation.useDefaultFilesystems` (default `true`)
  - If true, everything stays the way it is right now
  - Else, we omit the definition of the root filesystem and initrd options for formatting the disk with ext4
    - I guess the root filesystem is the only one we need to omit. Looks like everything else can already be changed in some other way.

Then users can just set `virtualisation.useDefaultFilesystems = false;` and define their own in `virtualisation.fileSystems` + initrd for setup.

**Comment by roberth** [comment]
sgtm
