### ISSUE TITLE
pybitmessage needs update to version 0.6.1

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#17798]
The current version in nixpkgs of PyBitmessage is 0.4x, 0.6.1 was released.
The package maintainer (@jgillich ?) should update it.

**Comment by FRidh** [comment]
@ng-0 you can ask the maintainer nicely whether he or she would like to update or, even better, come with a PR! :wink:

**Comment by ng-0** [comment]
I don't know who the maintainer is, I just saw this name in the default.nix of pybitmessage.

Thanks, but I just started today with Nix and need to understand more of the development process, so I can't fix it myself.
Additionally I maintain packages for 2 different operating systems and a simple "it's outdated" message is easier to handle for me.

**Comment by shak-mar** [comment]
Pybitmessage was updated to 0.6.2 in #28824.
