### ISSUE TITLE
cik_cp: Failed to load firmware "radeon/KABINI_pfp.bin"

### ISSUE THREAD

**Issue by noffle** [NixOS/nixpkgs#17790]
## Issue description

I noticed after rebooting my system recently (after many `nixos-rebuild switch`s) that X no longer starts on boot. I did a diff on the Xorg log between the broken snapshot and the last working snapshot: no differences. However I also diffed `dmesg` output and noticed the following on the bad snapshot:

```
 radeon 0000:00:01.0: VRAM: 512M 0x0000000000000000 - 0x000000001FFFFFFF (512M used)
 radeon 0000:00:01.0: GTT: 2048M 0x0000000020000000 - 0x000000009FFFFFFF
 Detected VRAM RAM=512M, BAR=256M
 RAM width 128bits DDR
 Zone  kernel: Available graphics memory: 1651696 kiB
 Initializing pool allocator
 Initializing DMA pool allocator
 radeon: 512M of VRAM memory ready
 radeon: 2048M of GTT memory ready.
 Loading kabini Microcode
 audit: type=1305 audit(1471413395.004:14): audit_enabled=1 old=1 auid=4294967295 ses=4294967295 res=1
 audit: type=1305 audit(1471413395.005:15): audit_backlog_limit=64 old=64 auid=4294967295 ses=4294967295 res=1
 audit: type=1305 audit(1471413395.005:16): audit_failure=1 old=1 auid=4294967295 ses=4294967295 res=1
 audit: type=1305 audit(1471413395.005:17): audit_rate_limit=0 old=0 auid=4294967295 ses=4294967295 res=1
 radeon 0000:00:01.0: Direct firmware load for radeon/kabini_pfp.bin failed with error -2
 radeon 0000:00:01.0: Direct firmware load for radeon/KABINI_pfp.bin failed with error -2
 cik_cp: Failed to load firmware "radeon/KABINI_pfp.bin"
 *ERROR* Failed to load firmware!
 radeon 0000:00:01.0: Fatal error during GPU init
 radeon: finishing device.
 Finalizing pool allocator
 Finalizing DMA pool allocator
 Zone  kernel: Used memory at exit: 0 kiB
 radeon: ttm finalized
 radeon: probe of 0000:00:01.0 failed with error -2
```

I'm not sure how to reproduce this: the video-related pieces of my config are still just

```
services.xserver.videoDrivers = [ "ati" ];
```

which hasn't changed between the good and bad snapshots. Any ideas how I might poke more deeply at this?
## Technical details
- System: 15.09.1253.91371c2 (Dingo)
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: 16.09pre88185.52a875f

**Comment by domenkozar** [comment]
cc @ocharles is this relevant to your issues?

**Comment by ocharles** [comment]
@domenkozar I don't have this problem. @noffle are you still having this problem? Note that I'm using `videoDrivers = [ "ati_unfree" ]` though.

**Comment by noffle** [comment]
@ocharles: Could you share your configuration? I'm no longer running NixOS, but am considering giving it another try to see if the situation has improved for my laptop.

**Comment by regnat** [comment]
(triage) @ocharles, is there a reason why you eventually did not close the issue ? May it be closed now ?

**Comment by ocharles** [comment]
Seems like I just forgot to click the button, thanks for the ping.
