### ISSUE TITLE
nixos/systemd-networkd: networking.defaultGateway.address is overridden by networking.defaultGateway6.address

### ISSUE THREAD

**Issue by m1cr0man** [NixOS/nixpkgs#178078]
### Describe the bug

Setting the default IPV4 _and_ IPV6 gateway using `networking.defaultGateway.address` and `networking.defaultGateway6.address` respectively results in a system configuration in which only the IPV6 default gateway is configured.

Looking at the generated network configuration files, this seems to be due to an order of precedence and non-merging behaviour within the `[Route]` section of the config.

My system has only one network interface with both an ipv4 and ipv6 address configured. I expect both routes to be applied to this interface.

Reverse-engineering the [networkd Nix config](https://github.com/NixOS/nixpkgs/blob/2a3aac479caeba0a65b2ad755fe5f284f1fde74d/nixos/modules/tasks/network-interfaces-systemd.nix#L59-L61), I discovered that the gateways are configured differently to what `systemd.network.networks.*.gateway` would apply. As a result, I was able to test the alternative method and found that the following would correctly configure the network:

```nix
{ systemd.network.networks."40-eth0".gateway = [ "1.2.3.4" "abcd::1" ]; }
```

With that, I also noticed that the `Gateway=` entries were added to the `[Network]` section rather than the `[Route]` section. This would imply to me that the handling of defaultGateway* should do the same.

### Steps To Reproduce

1. Configure both `networking.defaultGateway.address` and `networking.defaultGateway6.address` with `networking.useNetworkd = true;`.
2. Apply the configuration.
3. Run `ip route show table all` to view the active routes, and note the lack of an IPV4 default route.

### Expected behavior

Both IPV4 and IPV6 default routes/gateways should be configured. The behaviour should match setting `systemd.network.networks.*.gateway` to the value of each gateway.

### Files

Broken configuration example:

```ini
[Match]
Name=eth0

[Network]
DHCP=no
Domains=example.com
IPv6PrivacyExtensions=kernel
Address=1.2.3.4/24
Address=abcd::2/64

[Route]
Gateway=1.2.3.1
Gateway=abcd::1
GatewayOnLink=false
```

Working configuration example:

```ini
[Match]
Name=eth0

[Network]
DHCP=no
Domains=example.com
IPv6PrivacyExtensions=kernel
Address=1.2.3.4/24
Address=abcd::2/64
Gateway=1.2.3.1
Gateway=abcd::1
```

### Notify maintainers

@NixOS/systemd 

### Metadata

```console
nixos-version
22.05.20220509.2a3aac4 (Quokka)
```

**Comment by pennae** [comment]
looks like we should be generating one route per gateway instean of one route with multiple gateways. putting the gateways into `[network]` would have the same effect, but emitting multiple routes seems clearer.
