### ISSUE TITLE
linux kernel 4.7.0-grsec build script broken

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#17801]
## Issue description
`  DEPMOD  4.7.0-grsec
make[1]: Leaving directory '/tmp/nix-build-linux-4.7.drv-0/build'
unlink: cannot unlink '/nix/store/0r55r9vsv5y40w29pzdwh3nwj0n5s6n7-linux-4.7/lib/modules/4.7.0/build': No such file or directory`

This is because the folder isn't `.../modules/4.7.0/build`, but `.../modules/4.7.0-grsec`. 

## Technical details

* System: 16.09pre-git (Flounder), hardened-stdenv branch
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre88185.52a875f

**Comment by spacekitteh** [comment]
@joachifm

**Comment by joachifm** [comment]
This was fixed by https://github.com/NixOS/nixpkgs/commit/d82ddd6dc0e4d4d59b52accac930720b77884ed8

**Comment by fpletz** [comment]
Merged master in b4cc9bd.

**Comment by joachifm** [comment]
@fpletz thanks!
