### ISSUE TITLE
libselinux Python bindings cannot be imported

### ISSUE THREAD

**Issue by mbrock** [NixOS/nixpkgs#17808]
## Issue description

On current `master`, but not `16.03`, the Python module generated by `pkgs.libselinux` fails to load, possibly due to some SWIG-related problem.

This in turn causes `nixpart` to fail to run, which breaks NixOps.

The Python error occurs when the generated binding tries to use `importlib.import_module` to load the `_selinux.so` file.

## Steps to reproduce

Check out `master`.

    nix-shell -E 'with import <nixpkgs> {}; stdenv.mkDerivation { \
      name = "foo"; buildInputs = [ (pkgs.libselinux.override { \
        enablePython = true; }) python ]; }' \
      --run "python -m selinux"

I get this error:

    Traceback (most recent call last):
      File "/nix/store/3wl86vswinz1cam7jmzdvvaglg2566l6-python-2.7.12/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
      File "/nix/store/3wl86vswinz1cam7jmzdvvaglg2566l6-python-2.7.12/lib/python2.7/runpy.py", line 111, in _get_module_details
        __import__(mod_name)  # Do not catch exceptions initializing package
      File "/nix/store/9vvlf6vvs48679dbcd674kpj2c175ga6-libselinux-2.4/lib/python2.7/site-packages/selinux/__init__.py", line 21, in <module>
        _selinux = swig_import_helper()
      File "/nix/store/9vvlf6vvs48679dbcd674kpj2c175ga6-libselinux-2.4/lib/python2.7/site-packages/selinux/__init__.py", line 20, in swig_import_helper
        return importlib.import_module('_selinux')
      File "/nix/store/3wl86vswinz1cam7jmzdvvaglg2566l6-python-2.7.12/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named _selinux

## Technical details

* System: 16.09.git.1883a89 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09.git.1883a89

**Comment by mbrock** [comment]
No difference when using the previous SWIG version, 3.0.9.

**Comment by mbrock** [comment]
Ah, the previous SWIG version used in Nixpks was actually 3.0.7---which works.

I found some relevant discussion:

http://swig.10945.n7.nabble.com/Problem-with-python-bindings-td14827.html

It's some really obscure problem related to Python's import semantics and SWIG. There's some indication in the SWIG manual about a `-relativeimport` option that might help. I'll try it.

http://www.swig.org/Doc3.0/Python.html#Python_absrelimports

**Comment by mbrock** [comment]
That didn't help either, but I came up with a patch to the libselinux Makefile that does work.

It puts `_selinux.so` in `site-packages/_selinux.so` instead of in `site-packages/selinux/_selinux.so`.

**Comment by mbrock** [comment]
Turns out this was already fixed on SELinux master, so I'm just applying their patch.

**Comment by FRidh** [comment]
Closing this since it's fixed in #17817

**Comment by mbrock** [comment]
Thanks.
