### ISSUE TITLE
Need a Nix 1.11 maintenance release before 16.09

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#17804]
## Issue description

https://github.com/NixOS/nix/issues/977 was a pretty annoying bug which @shlevy fixed and pushed https://github.com/NixOS/nix/commit/66151dc154ea6f3f3c2ffb9e41afe1526d35f4f0  to the `1.11-maintenance` branch.

We need a version bump on that branch so that we can merge it into `nixpkgs` before 16.09 to avoid having that bug in stable.

cc @edolstra @shlevy @domenkozar

**Comment by copumpkin** [comment]
another ping to @domenkozar @shlevy @edanaher in case one of you missed it, given that the release date is creeping up

**Comment by shlevy** [comment]
Only @edolstra or @rbvermaa can do this.

**Comment by vcunat** [comment]
Yeah, the tarball is probably the only missing thing: http://nixos.org/releases/nix/nix-1.11.3

**Comment by edolstra** [comment]
The release is online now.

**Comment by domenkozar** [comment]
There are no debs/rpms, is that intentional?
