### ISSUE TITLE
groovy: 3.0.7 => 3.0.11

### ISSUE THREAD

**Issue by jacobtolar** [NixOS/nixpkgs#178073]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: groovy

current version: 3.0.7
desired version: 3.0.11

###### Notify maintainers

maintainers: @pSub 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by jacobtolar** [comment]
Submitted because groovy 3.0.7 doesn't work with jdk17 (fixed in https://issues.apache.org/jira/browse/GROOVY-9943 ).

**Comment by pSub** [comment]
Fix in master and 22.05.
