### ISSUE TITLE
Steam client Asian fonts issue

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#178121]
Asian characters are all rendered as squares in client(not in games). Looks like steam client is not picking up system font configs?

### Steps To Reproduce
```
 ;; with latest unstable branch
  programs.steam.enable = true;
```
### Screenshots
![image](https://user-images.githubusercontent.com/9002575/174430468-80c5d5ac-cef0-4dcb-993e-9cd61efc57cd.png)
![image](https://user-images.githubusercontent.com/9002575/174430506-2d7a1846-4d05-4ace-b809-db8618d323d7.png)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.14, NixOS, 22.11 (Raccoon), 22.11.20220614.6616de3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Patryk27** [comment]
Note that Arch's wiki contains some useful information on that (https://wiki.archlinux.org/title/steam#Asian_Font_Problems_with_Flatpak).

**Comment by weihua-lu** [comment]
> Note that Arch's wiki contains some useful information on that (https://wiki.archlinux.org/title/steam#Asian_Font_Problems_with_Flatpak).

Thanks, @Patryk27. After a bit of testing, I realized steam client need `wqy_zenhei` font to display Asian characters. Adding `wqy_zenhei` to font.font would resolve this. Maybe we could include that as a config option for programs.steam.

Another thing I'm not so sure is about the font-config. My font configuration originally has some default config setting like:
 `fontconfig.defaultFonts.sansSerif = [ "Noto Sans CJK SC" ];`
 
With that setting enabled, even adding `wqy_zenhei` to font.font, Steam client still won't able to display Asian fonts. I have to disable the defaultFonts config to make Steam happy. I'd expect if `Noto Sans CJK` not fount, it'd fall back to  `wqy_zenhei` installed in the system this case. Maybe I misunderstood the purpose of defaulFonts config.

My previous full font config:
```
  fonts = {
    fonts = with pkgs; [
      noto-fonts
      noto-fonts-cjk
      noto-fonts-emoji
      source-code-pro
      source-han-mono
      source-han-sans
      source-han-serif
    ];

    fontDir.enable = true;
    fontconfig.enable = true;

    enableDefaultFonts = true;
    fontconfig.defaultFonts = {
      emoji = [ "Noto Color Emoji" ];
      monospace = [ "Source Han Mono" ];
      sansSerif = [ "Noto Sans CJK SC" ];
      serif = [ "Source Han Serif" ];
    };
```

Below one makes steam happy (without defaultFonts):
```
  fonts = {
    fonts = with pkgs; [
      noto-fonts
      noto-fonts-cjk
      noto-fonts-emoji
      source-code-pro
      source-han-mono
      source-han-sans
      source-han-serif
      wqy_zenhei
    ];

    fontDir.enable = true;
    fontconfig.enable = true;
```

**Comment by amnore** [comment]
Steam seems to have issues with variable fonts (noto-fonts-cjk-sans is packaged as a vf in nixpkgs). I am able to make it display CJK characters correctly after applying this PR: https://github.com/NixOS/nixpkgs/pull/205641.

**Comment by sagehane** [comment]
Just came here to say I'm also having this problem with the Flatpak version of Steam on NixOS. https://github.com/ValveSoftware/steam-for-linux/issues/9418 seems to be the upstream issue.

**Comment by Cryolitia** [comment]
Over time, this problem has had multiple different and complex causes on different Steam versions. This includes historical inability to load variable fonts, and font specification for Arial. 

For the author of this post, a detailed explanation and solution to this problem is here: https://github.com/NixOS/nixpkgs/pull/312268#issuecomment-2125806330

**Comment by FossPrime** [comment]
Non of the solutions mentioned here worked for me... I even cleared the fonts cached of steam and the system. What did work was adding this to my configuration.nix

```
environment.systemPackages = with pkgs; [
    (pkgs.steam.override {
      extraPkgs = pkgs: [
        pkgs.noto-fonts-cjk
        # Include other fonts or packages if necessary
      ];
    })
  ];
```

Yes I know that's not how you install steam and it seems superfluous, but it is the only thing that worked.

Proof:
![image](https://github.com/user-attachments/assets/be111cfc-e6a1-4781-901e-43905f8606a6)

**Comment by Cryolitia** [comment]
I have already fixed this issue in https://github.com/NixOS/nixpkgs/pull/312268, now steam will use the system fonts, and the font config in your home dir.
