### ISSUE TITLE
Double Commander

### ISSUE THREAD

**Issue by alpha-bit** [NixOS/nixpkgs#178186]
**Project description**

GTK mc-like dual panel file browser ::: very nice for mc users... :)

"Double Commander is a free cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas."

**Metadata**

* homepage URL: https://doublecmd.sourceforge.io/
* source URL: https://github.com/doublecmd/doublecmd
* license: https://www.gnu.org/philosophy/free-sw.html
* platforms: linux, ???...

**Comment by AndersonTorres** [comment]
Man, this is a Pascal app! I never tried to build such a thing before...

**Comment by alpha-bit** [comment]
i'm just suggesting because i'm migrating from debian where i use it... :)
... though have no idea about building or packaging... :(
debian has it, if it helps in any way....

https://packages.debian.org/search?suite=stable&section=all&arch=any&searchon=names&keywords=doublecmd

i use doublecmd-gtk

**Comment by AndersonTorres** [comment]
Debian rarely provides their build scripts. I am reading the ubiquitous AUR (https://archlinux.org/packages/community/x86_64/doublecmd-qt5/).

However, I have seen that the GTK they use is the old and abandoned-by-us GTK2.

**Comment by alpha-bit** [comment]
i do not "depend" on gnome/gtk... and was about to eventually give a try qt software... so feel free not to oblige to my request, though i do think is a nice piece of software that deserves a chance of availability... maybe wait for them to upgrade their dependencies...

( hour after )

... i just tried krusader... and filled this bug report: https://github.com/NixOS/nixpkgs/issues/178445

O.o ... so seams there is not a nice working dual panel graphical browser available... :(

**Comment by AndersonTorres** [comment]
Perfect. Friday I will look at this.

**Comment by AndersonTorres** [comment]
It means that now the Hydra bot will build the caches in order to include this package.
You can follow the progress of it in the link below:

https://nixpk.gs/pr-tracker.html?pr=179260

When it reaches nixpkgs-unstable you can possibly call it.

**Comment by alpha-bit** [comment]
... and is now available... :) ... and installed... :)

Seams to work fine, except...

When i try to "Commands" -> "Search", "New search instance..." or "Synchronize dirs...", sometimes i get a "Function not supported!" error... :( ... After opening the program, if it happens, it always happens until i close it... If does do happen, then does not happen until i close it... o.O?... And now that i'm trying to repeat the error, all seams to work fine... Have no idea what was that... The debian version never gave this error... Since i'm not being able to repeat this error, i will not report it until if it ever happens in a repeatable way... (5 min later) Yap ::: no error for several program restarts, cannot repeat it,  have no idea on what may have caused the error (maybe is just be from sharing my home (~) with both versions, of debian and /nix).

& thank you for packaging this... :)

**Comment by alpha-bit** [comment]
for mere curiosity ::: do you have plans to pack also the "qt" version?

**Comment by AndersonTorres** [comment]
Isn't this the QT version already? Or it has support for older QT releases?

**Comment by alpha-bit** [comment]
lolz ::: yes, you are right... sorry, it does look like gtk version, here in my debian, i presumed it was the same...

so then, do you have any plans to also pack the "gtk" version?...

**Comment by AndersonTorres** [comment]
I don't feel motivated to do it because it uses GTK2, an abandoned release of GTK.

**Comment by peterhoeg** [comment]
The Free Pascal support for GTK3 is in very rough shape. GTK2 is preferred and Qt5 is getting there. @alpha-bit what problem do you have with the qt5 version that gtk2 will solve?

**Comment by alpha-bit** [comment]
@peterhoeg, i have no "problem" "with the qt5 version"... :) ... it works just fine... :) ... unlike krusader ::: https://github.com/NixOS/nixpkgs/issues/178445 ... :(

I just asked "do you have any plans to also pack the "gtk" version?" out of curiosity... :)
And with the small concern that if some one only uses only gnome/gtk and installs the doublecmd (qt5) ::: will be also installing some qt5 libraries just for doublecmd, when the necessary libraries for the doublecmd (gtk) are probably already installed and being shared among other gtk programs.

For example, if i want to make a small-as-possible live CD based on gnome, and the only installed qt5 package is doublecmd (qt5) ::: some space could be spared with the doublecmd (gtk) instead...

O.o ... i presume.

So, there is not a big "problem", that i don't mind now ::: but is also not perfect... i do undersand that @AndersonTorres might rather wait for "Free Pascal support for GTK3", and agree that adding "GTK2, an abandoned release of GTK" may just be a swim against the current and a waste of time (if no one needs it for a stronger reason).

**Comment by peterhoeg** [comment]
> And with the small concern that if some one only uses only gnome/gtk and installs the doublecmd (qt5) ::: will be also installing some qt5 libraries just for
> doublecmd, when the necessary libraries for the doublecmd (gtk) are probably already installed and being shared among other gtk programs.

Fortunately space is cheap, so it doesn’t seem like something truly worth optimizing for. Once you start dragging in graphical programs, you’re going to carry a lot of libraries.

> For example, if i want to make a small-as-possible live CD based on gnome, and the only installed qt5 package is doublecmd (qt5) ::: some space could be
> spared with the doublecmd (gtk) instead…

Use GNOME Commander in this case? I know it’s not packaged in nixpkgs, but that should be trivial to sort out.

**Comment by alpha-bit** [comment]
"space is cheap" ... o.O?... & what does life has to do with price?...

... and sure GNOME Commander could be a solution ::: but is not in nixpgks... (as you mentioned)... and is not double-commander... maybe is better, i have not tried it ::: is also not in debian stable, that i use... by the screenshots i would presume that has less features and looks not so nice.

... on my part, for now i'm happy with having dblcmd qt ::: i have not yet decided which to choose: qt, gtk, other or none, to cross with my xmonad... and still far from any kind of release, if ever any... and just scouting for the possibility of using nixos, or debian, or both.

**Comment by alpha-bit** [comment]
i do agree with Anderson ::: "the choice is obvious."

... and sorry, for bringing "life" into the subject... what i meant was ::: i don't care about "cheap" but rather well done... o.O?... a "cheaper" typical size DVD ::: costs more and takes more space than a mini-DVD, which does fit a pocked...

& yes, "This is getting off-topic"... but the thread is closed, i presume that now we are just drinking coffee, right?... :) ... "NixOS is so much nicer"... o.O?... lolz ::: at consuming hdd space and having broken packages?... i like debian because is stable, and distinguishes between "required,recommended and suggested" dependencies... i use debian since 2000, and every time i try some other distro ::: i end up getting back to debian... :) ... debian can be small, can be big, is quite stable, and others are always missing something i need... :) ... as for nix ::: i do like the one-file configuration.nix ... but still find unbearable when i bump into a "broken package" (why is it listed for install at all?), and miss the suggested/recommnended variations of packages... NixOS is yet not nice enough to replace my debian... :) ... and debian + /nix is very nice enough for now... :) ... i just run 3 personal machines ::: "so nothing big" at all... :)

**Comment by peterhoeg** [comment]
This isn't particularly constructive, but I'll bite.

>> "NixOS is so much nicer"

> at consuming hdd space 

When you have multiple versions of the same package, you are bound to take up more space than on a distribution where only a single version can exist. The entire closure of bash (as an example) with all its transitive dependencies doesn't take up more space than bash and its dependencies on Debian. Complaining about NixOS using more space than traditional FHS distributions is a bit like complaining that water is wet.

> and having broken packages?

Sure, we have broken packages. All distributions have broken packages (for various definitions of "broken" of course). Certain types of packages (KDE applications on !NixOS) is less likely to be tested well and as a consequence will be more likely to break, that's correct. Do we have more or less broken packages that others as a percentage of all packages? Are they more or less broken? I can't give you a quantifiable answer. In my experience broken packages has not been an issue.

> but still find unbearable when i bump into a "broken package" (why is it listed for install at all?), 

Because the existence of a package in the repository is orthogonal to its build status. Exactly the same way that a package in debian can also be installable but not fit for purpose due to bugs (or conflicts or pollution from the global environment and so on).

> and miss the suggested/recommnended variations of packages... 

Apart from overriding a given package which is of course always an option, some packages will allow you to toggle various features, but having an application's runtime environment be a product of the global environment is not something we strive for. It's pretty much the antithesis of what we're trying to do here.

> NixOS is yet not nice enough to replace my debian... :) 

That's fine, you do you. I was simply making the point that for *my* personal use-cases as well as those of the company in which I work have been a tremendous upgrade from Debian. Forget about "not even the same ballpark" - it's pretty much "not even playing the same game".

**Comment by alpha-bit** [comment]
> This isn't particularly constructive, but I'll bite.

O.o ... please do so... :) ... i think is constructive... i' learning about stuff... :)
... and ::: just having another coffee... :)

Debian takes me much (much, much, than with recommended) less space, because i only install required packages, never the recommend, never ever the suggested... :) ... nixos seams to do that some extent with configuration and package options... :) ... but still feel much less clear and customizable to me... :( ... or maybe just don't know, NixOS yet enough, how easy that would be... o.O?...

> All distributions have broken packages

... though never seen it on debian stable... since 2000... :D

> Do we have more or less broken packages that others as a percentage of all packages?

O.o ... lolz ::: & i just started now, trying to use NixOS... 

  https://github.com/haskell/cabal/issues/6339#issuecomment-1173811931

O.o ... & should i report this brokenness it as a bug?... (but "thanks god" ::: it worked on debian)
... seriously ::: please answer this... :)

> In my experience broken packages has not been an issue.

O.o ... lolz ::: am i "experienced" or what?... (just kidding)

> Exactly the same way that a package in debian can also... bla,bla,bla...

O.o ... never had packaging problems with debian since 2000... :) ... have you? ::: lolz, would be ironic... :D

> ... having an application's runtime environment be a product of the global environment

sorry ::: did not understand this.

> ... what we're trying to do here.

O.o ...  are "you" not trying to please everyone and everything possible?... is not that what "you" also want?...

> ... it's pretty much "not even playing the same game".

O.o ... yes ::: i'll end up using both... :) ... i'm comparing with debian and sharing my transitional experience for "you" to be aware of it... :) ... i do find the nix* approach very nice... :) ... and single file for the whole configuration is really nice... :) ... all my haskell work now goes into a nix-shell of my Debian /nix, that i test in a NixOS... o.O?... "you" do brag about good haskell support ... o.O?... and lolz ::: i bump haskell broken packages?... lolz... :D

so ::: don't brag so much just yet... :) ... & make this "bite" ::: "constructive"... :) ... better yet ::: more construct-able... :) ... and more stable when announced (by being in the NixOS channel ) as stable... :) ... and ::: i hope the "bite" tasted nice... o.O?... i have not much more food for now... :( ... with any luck (for "you") i'll just keep bumping into bugs and brokennesses and report them... :)

**Comment by alpha-bit** [comment]
Just to be clear, the bokenness i mention above is also broken in NixOS, i did try both.

**Comment by alpha-bit** [comment]
A bit nore spacing concerns...

I'm now upgrading NixOS... noticed all the *-doc packages passing by...

is there a way of switching them all off?
... and is there such thing like a central html index, linked to the *-doc files installed?
how can i access them?

**Comment by 7c6f434c** [comment]
Oh well, if you are comfortable using Debian Stable, your needs are such that NixOS won't be of use to you… NixOS is about avoiding conflicts between unrelated packages, supporting rollbacks so you can install fresh stuff with less risk, etc. If you want a minimal setup with Debian Stable, sure, that's another way of avoiding problems that Nix handles for large combinatations of fresh packages.

**Comment by alpha-bit** [comment]
> Oh well, if you are comfortable using Debian Stable, your needs are such that NixOS won't be of use to you…

O.o ... uau ::: not bad, for a dictator... o.O?... good thing i have a will of my own... :D
but thank you, for the more clear answer to my question:

  > are "you" not trying to please everyone and everything possible?... is not that what "you" also want?...

O.o ... guess not... "NixOS won't be of use to you" ... :( sorry, i had not realized that NixOS just targets a specific audience ): ... as you explain, is not good as debian ::: to make a smallest live-cd, with no repetition of packages and with no *-doc packages... :( ... ok ::: upon your advice i'll try to use debian for that... :) ... ty

And please notice ::: that you just failed in answering any of the questions i made... :( ... which would actually be even more useful to go with the coffee... :) ... suggestion ::: "get your self a cookie"... :D

**Comment by AndersonTorres** [comment]
I could even try to bite this, however my learning and attention problems trigger as a hell before such a badly written text.

For someone complaining about elitism and bloat in an obscure and niche distro, your text does no favor being such an obfuscated and unreadable blob.

**Comment by alpha-bit** [comment]
Sorry Anderson... I also was happier when we were just 2 making the more useful dialog already closed. Also my "learning and attention problems trigger"ed when someone else when off the good interpretation of my writing...

> For someone complaining about elitism and bloat in an obscure and niche distro

O.o ... lolz ... have no idea of you are talking about.

ps ::: according to you published location ::: Presumo que sejas brasileiro, e falas portugues... :) ... a minha lingua nativa ::: sempre escrevo melhor o portugues (sem acentos nem cedilhas porque o teclado nao os tem), que o ingles... e' isso ::: peco desculpa pela falta de qualidade do meu ingles nao nativo... sei e' escrever o meu codigo, e apenas aqui venho para me-vos tentar ajudar... seja ao debian, ao nixos ou whatever... :) ... mas se te estou a fazer confusao ::: ja' nao gosto... o.O?... e menos a ti ::: que empakotaste o dblcmd tao eficazmente... :) ... (lolz ::: maybe someday i'll consider inviting you for my yet non-existing crew) ... enquanto o extendido off-topic apenas esta' a deixar mais duvidas que respostas... :( ... portanto vou ficar por aqui ::: e evitar dar alento a "elitismos" maioritariamente incompreendentes... :)

[ & bom dia para ti, obrigado por tudo, ]
pode ser que nos encontremo-nos noutra thread.

For the English speaking ::: if thou have no answers to my actual questions, please don't waste our time in replying ::: i came by to learn and help a bit, even if for now if is just by complaining and asking... :) ... sorry for my noticeable lack of "social skills" ::: thanks god for that... :) ... unfortunately written words don't carry the voice of the writer, nor attitude ::: and are quite prone to miss understanding... in future threads i'll try to hold my self from expressing so at ease.

[ & have you all hopefully a nice day ]

**Comment by peterhoeg** [comment]
This conversation has really veered off the original path. If you have any questions, I suggest taking them over to https://discourse.nixos.org which is a far better forum for those types of conversations. I would however recommend considering if your writing style helps or hinders the chances of constructive feedback.
