### ISSUE TITLE
nomad module does not support systemd LoadCredential + CREDENTIALS_DIRECTORY

### ISSUE THREAD

**Issue by jhillyerd** [NixOS/nixpkgs#178269]
### Describe the bug
I currently generate an HCL file with my consul token and nomad server encryption key.  When dropping privileges, it requires me keeping this HCL file world readable.

Having support for `LoadCredentials` (easy to override as-is) and `$CREDENTIALS_DIRECTORY` (not overridable due to `path` type requirement on `services.nomad.extraSettingsPath`) would allow systemd to copy secrets somewhere readable by nomad.

### Steps To Reproduce
1. Set services.nomad.extraSettingsPaths to contain a root:root 0400 file.
2. Set services.nomad.dropPrivileges = true
3. Set services.nomad.enable = true
4. (potentially more settings for a minimum viable nomad config)

### Expected behavior
Nomad reads secrets from extra settings HCL file, starts successfully.

### Notify maintainers
No official maintainers, but @GTrunSec @nh2 may have ideas.

I spent some time experimenting, root of the problem is that we need to pass "-config ${CREDENTIALS_DIRECTORY}/somefile.hcl" in ExecStart, along with those files in the LoadCredentials systemd stanza.  I'm not sure if there is an idiomatic way to do this in Nix.

**Comment by GTrunSec** [comment]
Could you test #211559 ? make sure I have solved your problem.

**Comment by jhillyerd** [comment]
Will take a look, thanks!
