### ISSUE TITLE
python3.9-treq-22.2.0 fails to build on aarch64-darwin

### ISSUE THREAD

**Issue by jmgilman** [NixOS/nixpkgs#178274]
### Steps To Reproduce
1. build python3.9-treq-22.2.0

### Build log
https://gist.github.com/jmgilman/9988e9fd2c299645c47173db12d4585d

### Additional context
This error occurred while attempting to build `python3.9-magic-wormhole-mailbox-server-0.4.1`.

### Notify maintainers
@SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.7.0`
 - channels(root): `"nixpkgs"`
 - channels(josh): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

**Comment by jmgilman** [comment]
This is probably related to [outstanding pyopenssl failures](https://github.com/pyca/pyopenssl/issues/873)?

**Comment by SuperSandro2000** [comment]
On which commit/version are you? pyopenssl should be marked broken on arch64-darwin.

**Comment by jmgilman** [comment]
> On which commit/version are you? pyopenssl should be marked broken on arch64-darwin.

Ah, you are correct. I was previously allowing pyopenssl to go through because a dependent package was actually building correctly. I had forgotten about that. Sorry for the confusion.
