### ISSUE TITLE
Can't change screen resolutions in Plasma

### ISSUE THREAD

**Issue by vs49688** [NixOS/nixpkgs#178393]
### Describe the bug

Can't change screen resolutions in Plasma.

### Steps To Reproduce
1. Install NixOS with Plasma
2. Attempt to change screen resolution

### Expected behavior
The screen resolution changes.

### Additional context

This happens on multiple machines, both laptops, on the Wayland session. When I open `systemsettings` and click on `Display & Monitor`, it spits out `kf.coreaddons: "Could not load plugin from kcm_kscreen: The shared library was not found."` in console, which makes me think it's something related to NixOS and pathing.

Suspiciously, both `$ kscreen-console config` and `$ kscreen-console outputs` are empty, and `$ kscreen-console monitor` reports nothing.

After changing the resolution, the refresh rate field in the GUI changes to something nonsensical, e.g.:

* 3546x2160 - 60Hz (original, good)
* 2560x1600 - 728501Hz
* 1920x1200 - 1293352Hz

This might be related to https://bugs.kde.org/show_bug.cgi?id=455477, but I'm not getting a crash.

I'm prepared to submit this upstream, if it's a non-NixOS issue.

### Logs

[systemsettings.log](https://github.com/NixOS/nixpkgs/files/8945019/systemsettings.log)

### Notify maintainers

@ttuegel @nyanloutre @peterhoeg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.15, NixOS, 22.11 (Raccoon), 22.11.20220618.e0a4226`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
I just tried and I **can** change the resolution but I **also** get the message that you do:
```
$ systemsettings
kf.service.services: The desktop entry file "/run/current-system/sw/share/applications/kcm_krunnersettings.desktop" has Type= "Application" but no Exec line
kf.service.sycoca: Invalid Service :  "/run/current-system/sw/share/applications/kcm_krunnersettings.desktop"
QQmlEngine::setContextForObject(): Object already has a QQmlContext
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
kf.coreaddons: "Could not load plugin from kcm_kscreen: The shared library was not found."
QQmlEngine::setContextForObject(): Object already has a QQmlContext
qml: The item SubCategoryPage_QMLTYPE_103(0xe53140) is already in the PageRow
kf.coreaddons: "Could not load plugin from kcm_kscreen: The shared library was not found."
```

Both `$ kscreen-console config` and `$ kscreen-console outputs` give me lots of output.

Could you try to run this:
```
$ rm $HOME/.cache/systemsettings/qmlcache
```

And then try again?

**Comment by vs49688** [comment]
First thing I did when I updated to 5.25. Just tried again, no change.

**Comment by peterhoeg** [comment]
I have no idea why my mail reply isn't being picked up, so pasting it in here:

You want the good news or the bad news first? Doesn’t matter - it’s both good and bad. 

It’s working fine (as mentioned) for me on the desktop but on the laptop, I’m seeing the same as you do - the resolution doesn’t change, although it depends on which resolution I try. 

The laptop LCD supports 1080p natively. 
- If I try to change to 1600x900, “Display Configuration” tells me it changed, but the screen doesn’t. 
- If I try 1280x720, it **does** change. 

I’m thinking this is maybe a hardware issue where the panel simply doesn’t support certain resolutions.

**Comment by vs49688** [comment]
Could you try it in an X11 session on the laptop? I can change resolutions fine when using X11, I suspect it may be an issue with https://invent.kde.org/plasma/kwin/-/merge_requests/2235.

The panel on my laptop only reports 3840x2160 (have checked the EDID) and the integrated HD 530 can't handle it well, so I want to run it lower. X11's fake modes work fine, kwin's fake don't.

**Comment by vs49688** [comment]
I would love to, but the vendor cheaped-out on the integrated GPU - it _struggles_ to drive it at 4k. I've found it s significantly more responsive at 1080p.

**Comment by vs49688** [comment]
This is fixed on unstable now.

**Comment by peterhoeg** [comment]
You want the good news or the bad news first? Doesn’t matter - it’s both good and bad.

It’s working fine (as mentioned) for me on the desktop *but* on the laptop, I’m seeing the same as you do - the resolution doesn’t change, although it depends on which resolution I try.

The laptop LCD supports 1080p natively. If I try to change to 1600x900, “Display Configuration” tells me it changed, but the screen doesn’t. If I try 1280x720, it *does* change.

I’m thinking this is maybe a hardware issue where the panel simply doesn’t support certain resolutions.

**Comment by vs49688** [comment]
Yeah, that does sound like the panel not supporting the mode. Mine only reports 2160p, but supports basically everything, now that "Display Configuration" creates the "fake" modes.

Oddly enough, mine supports 1080p, but it isn't displayed in the drop-down.
