### ISSUE TITLE
vconsole setup fails in systemd initrd

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#178340]
With `boot.initrd.systemd.enable = true;` and `console.earlySetup = true;`, I still have to type my LUKS passphrase in qwerty. The logs say this:

```
systemd-udevd[176]: vtcon0: Process '/nix/store/09iq39jicajnvf3305176rj1pghgyn0i-systemd-stage-1-250.4/lib/systemd/systemd-vconsole-setup' failed with exit code 1.
```

but not much else apparently.

The vconsole is set up fine by the time I get a login prompt.

**Comment by oxalica** [comment]
Dup of #172403
