### ISSUE TITLE
Woodpecker CI server, runner, and CLI

### ISSUE THREAD

**Issue by ambroisie** [NixOS/nixpkgs#178332]
**Project description**

[Woodpecker CI](https://woodpecker-ci.org) is a simple CI engine, [forked from Drone CI after their license change](https://woodpecker-ci.org/faq#why-is-woodpecker-a-fork-of-drone-version-08)

**Metadata**

* homepage URL: https://woodpecker-ci.org/
* source URL: https://github.com/woodpecker-ci/woodpecker
* license: apache 2.0
* platforms: all (since it's written in Go), but the docker backend is linux-specific

**Comment by wyndon** [comment]
This is a start #169470

Seems abandoned tho.

**Comment by ambroisie** [comment]
@wyndon thanks, I hadn't seen that MR. Will take a look.

**Comment by ambroisie** [comment]
@f0x52 I saw your comment. If I end up adding the packages in an MR, would you like/be willing to be added to the maintainer list?
