### ISSUE TITLE
LunarVim

### ISSUE THREAD

**Issue by gekoke** [NixOS/nixpkgs#178488]
**Project description**
An IDE layer for Neovim with sane defaults. Completely free and community driven.

**Metadata**

* homepage URL: https://www.lunarvim.org/
* source URL: https://github.com/LunarVim/LunarVim
* license: GPL-3.0
* platforms: unix, linux, darwin

**Comment by f3zhead** [comment]
I found this [default.nix](https://github.com/V1RE/nixpkgs/blob/75198a323d6cdf86838755421c60cfea124ea3ad/pkgs/applications/editors/lunarvim/default.nix)
 from [this issue](https://github.com/LunarVim/LunarVim/issues/1507)
