### ISSUE TITLE
"fetching arbitrary (maybe dangling) commits may be a security risk"

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [NixOS/nixpkgs#178410]
https://github.com/NixOS/nixpkgs/blob/f0db300ceb72f40dd48e0687f985dfd9040ad9f7/pkgs/build-support/fetchgit/default.nix#L35

Can anybody provide a pointer on why allowing dangling commits to be fetched is a security risk?  I can't seem to find any details on this.  Is the risk because people assume "unreachable" means "deleted"?

**Comment by kilianar** [comment]
There's a guess in https://github.com/NixOS/nix/issues/4760#issue-873814982. @MarcWeber is the original author of the `fetchgit` documentation (see https://github.com/NixOS/nixpkgs/commit/edf78fcb6a144444cdea9897f87d486252a1e090)

**Comment by amjoseph-nixpkgs** [comment]
> There's a guess in [NixOS/nix#4760 (comment)](https://github.com/NixOS/nix/issues/4760#issue-873814982).

Hrm, that guess has to do with github's PRs, not with anything in git.

**Comment by amjoseph-nixpkgs** [comment]
Well, I found a *reason* why git would want to prohibit this, but it isn't related to security.

If you `git push --force origin mybranch:mybranch` a branch, the commit that `origin/mybranch` used to point to is still available in the `origin` repository -- at least until the next `git gc` happens.

If people are allowed to fetch commits by their hash even when those commits are unreachable, a force-push like this would put those commits at risk of being garbage collected.  But nobody would notice the breakage until (potentially) much later, when a `git gc` happened.  If those other users are forced to mention a commit from which their desired ref is reachable, they will notice the breakage *immediately*.  And they will know who to go yell at (the person who just did a `push --force`).

I think this is the reason.

If nobody else can come up with a security-related explanation I'm going to submit a PR to remove the word "security" in `fetchgit/default.nix`.
