### ISSUE TITLE
Missing "button" in services.xserver.libinput.scrollMethod

### ISSUE THREAD

**Issue by yshui** [NixOS/nixpkgs#17840]
## Issue description

"button" is mentioned in scrollButton but not actually in scrollMethod

**Comment by Profpatsch** [comment]
(triage) Is this still a problem? If yes, would you be willing to submit a pull request?

**Comment by yshui** [comment]
@Profpatsch it should be as simple as:

```diff
      scrollMethod = mkOption {
-type = types.enum [ "twofinger" "edge" "none" ];
+type = types.enum [ "twofinger" "edge" "none" "button" ];
```

**Comment by Profpatsch** [comment]
@yshui Can you open a pull request? that would be great.
