### ISSUE TITLE
Unable to use smart card with gpg2

### ISSUE THREAD

**Issue by svend** [NixOS/nixpkgs#1784]
Attempting to access a gnupg smart card (http://g10code.com/p-card.html) fails:

```
$ gpg2 --card-status
gpg: selecting openpgp failed: Card error
gpg: OpenPGP card not available: Card error
```

I believe this is because the gnupg package does not depend on the pcsclite package, which provides libpcsclite.so.1. The scdaemon man page states:

```
       --pcsc-driver library
              Use  library to access the smartcard reader.  The current default is ‘libpcsclite.so’.  Instead of using this option you
              might also want to install a symbolic link to the default file name (e.g. from ‘libpcsclite.so.1’).
```

On a debian system where the card works, running gpg2 spawns a scdaemon process which starts the following process: `gnupg-pcsc-wrapper -- 1 libpcsclite.so.1`.

**Comment by wkennington** [comment]
Fixed via 9631f5a7183cfdd8975e03d741a1a49f0100ef94
