### ISSUE TITLE
epson-escpr2 fails to build on nixos-unstable 0d68d7c857f

### ISSUE THREAD

**Issue by barryfm** [NixOS/nixpkgs#178452]
### Describe the bug
During a nix-reinstall i get:

```
patching sources
applying patch /nix/store/ljqnzvnhv6v0c4pvwry3617fp8j7q3bv-cups-filter-ppd-dirs.patch
patching file configure
configuring
fixing libtool script ./ltmain.sh
mktemp: (null): Invalid argument
error: builder for '/nix/store/iw9r9n1bshy17hmzdyc5fvk469qkg6k5-epson-inkjet-printer-escpr2-1.1.46.drv' failed with exit code 1
```

### Steps To Reproduce
While using the nixos-unstable channel:

```
nixos-rebuild switch --upgrade
```
I get
```
this derivation will be built:
  /nix/store/iw9r9n1bshy17hmzdyc5fvk469qkg6k5-epson-inkjet-printer-escpr2-1.1.46.drv
building '/nix/store/iw9r9n1bshy17hmzdyc5fvk469qkg6k5-epson-inkjet-printer-escpr2-1.1.46.drv'...
unpacking sources
epson-inkjet-printer-escpr2-1.1.46-1lsb3.2.tar.gz
lsb-rpm.spec
8799 blocks
epson-inkjet-printer-escpr2-1.1.46/
epson-inkjet-printer-escpr2-1.1.46/config.h.in
...
epson-inkjet-printer-escpr2-1.1.46/ChangeLog
epson-inkjet-printer-escpr2-1.1.46/epson-inkjet-printer-escpr2.spec.in
epson-inkjet-printer-escpr2-1.1.46/bootstrap
patching sources
applying patch /nix/store/ljqnzvnhv6v0c4pvwry3617fp8j7q3bv-cups-filter-ppd-dirs.patch
patching file configure
configuring
fixing libtool script ./ltmain.sh
mktemp: (null): Invalid argument
error: builder for '/nix/store/iw9r9n1bshy17hmzdyc5fvk469qkg6k5-epson-inkjet-printer-escpr2-1.1.46.drv' failed with exit code 1
```
### Expected behavior
A success update.

## Notifymaintainers

@ma9e @ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.11 (Raccoon), 22.11pre386147.e0a42267f73`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by trofi** [comment]
I think it was fixed in https://github.com/NixOS/nixpkgs/pull/178626 (not in master yet).

**Comment by vcunat** [comment]
It does build on current staging-next: https://hydra.nixos.org/job/nixpkgs/staging-next/epson-escpr2.x86_64-linux

**Comment by barryfm** [comment]
I made my own change (locally) and followed:
https://aur.archlinux.org/packages/epson-inkjet-printer-escpr2

Using `nativeBuildInputs` ``rpm` and `cpio`  rather `busybox` to fix any issue with the drivers internal copy of `ltmain.sh` invocation of `mktemp`.

It also updated to [version 1.1.48](https://download3.ebz.epson.net/dsc/f/03/00/13/52/26/977f2b2c13cc185981479fbd225b802c35c92beb/epson-inkjet-printer-escpr2-1.1.48-1lsb3.2.src.rpm) and included another patch [bug_x86_64.patch](https://aur.archlinux.org/cgit/aur.git/tree/bug_x86_64.patch?h=epson-inkjet-printer-escpr2).
