### ISSUE TITLE
Redshift service tries to run even for DISPLAY-less users

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#17858]
The Redshift user service apparently tries to run for any logged-in
user, regardless of whether that user has an X11 environment and a
useful `DISPLAY` environment variable, which [it seems to depend on](https://github.com/NixOS/nixpkgs/pull/17746).

I suppose this is fine if I only log in via an X11 display manager,
but when I log in at the kernel console as a user not already logged
in with an X environment running (e.g., to administer the system as
the superuser, or in case X wasn't working), this becomes problematic,
as Redshift tries to start, fails, and keeps trying, spewing error
messages into the journal seemingly until the system is shut down.

I would suggest that the Redshift service be prevented from starting
unless and until it would have access to an X11 environment and a
useful `DISPLAY` variable, which I haven't presently sufficient
knowledge of systemd to effect.

**Comment by rnhmjoj** [comment]
You could remove the service from the `default.target` and let users manually enable it.

**Comment by joachifm** [comment]
Seems to me that the solution proposed by @rnhmjoj is the easiest way to solve this currently.

**Comment by nixy** [comment]
@8573 It seems like you found a workaround for this. Is this still an issue for you?

I imagine you could probably achieve what you want by adding an if statement to check for $DISPLAY in the service configuration in nixos/modules/services/x11/redshift.nix, though I am not sure if $DISPLAY would be set at that point in the boot process

**Comment by joachifm** [comment]
Note that for systemd 232 upwards, `graphical-session.target` is the user equivalent for `graphical.target`, but I think we're some ways away from that being quite viable (you can't just add stuff to it). There's some discussion about this elsewhere on the issue tracker, I believe, but I can't find it right now.

**Comment by rnhmjoj** [comment]
Thanks. Maybe [this](https://github.com/NixOS/nixpkgs/issues/22671)?

**Comment by joachifm** [comment]
Something like that; there's also been some discussion on IRC. I wonder if it'd be good to unify these issues under a single tracking issue. I think a proper `graphical-session` implementation would solve all of them.

**Comment by rnhmjoj** [comment]
I agree. Also it's not really clear how to manage user services on NixOS: which services in the configuration are system-wise or per-user, which ones autostart... It seems they are only briefly mentioned in the manual under the Emacs section.

#17858, #22670, #22671, #23363, #23491

**Comment by joachifm** [comment]
@rnhmjoj great list. In addition, under the broader scope of making "user services" first class: https://github.com/NixOS/nixpkgs/issues/7329, https://github.com/NixOS/nixpkgs/issues/7326, https://github.com/NixOS/nixpkgs/issues/3702, https://github.com/NixOS/nixpkgs/issues/22734, https://github.com/NixOS/nixpkgs/issues/21460

**Comment by 8573** [comment]
@nixy I didn't so much find a workaround as stop using the service altogether; I'm now starting/stopping `redshift` manually.

**Comment by benley** [comment]
Am I right in thinking that the redshift service is essentially unusable until this gets fixed? (unless you don't mind the system journal filling with redshift crashes forever, that is)

**Comment by fpletz** [comment]
Opened PR #26094 to possibly fix this issue until somebody finds out how we can use graphical-session.target.
