### ISSUE TITLE
new emacsWrapper breaks existing emacsWithPackages expressions

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#17853]
## Issue description

In my config.nix, I've been using the following expressions for a while:

```
{
  packageOverrides = super: let self = super.pkgs; in rec {
    ...
    emacsPackageSet = super.emacsPackagesNg.override (super: self: (with self; {
      htmlize = melpaPackages.htmlize;
      org-plus-contrib = orgPackages.org-plus-contrib;
      undo-tree = elpaPackages.undo-tree;
    }));
    emacsTools = emacsPackageSet.emacsWithPackages (super: (with super;
    [
      ace-link
      org-plus-contrib
      ...
    ]));
    ...
}
```

The new `emacsWrapper` introduced in da68127 breaks these expressions in a fairly opaque way:

```
error: while evaluating the attribute ‘pkgs’ of the derivation ‘everything’ at /home/mdorman/src/nixpkgs/pkgs/build-support/trivial-builders.nix:10:14:
cannot convert a function to JSON
```

I don't actually mind adapting, but 1) the change description specifically implies that it should maintain compatibility, and 2) there's no guidance as to what should be changed.

@ttuegel @matthewbauer maybe some guidance?

**Comment by ttuegel** [comment]
The new `emacsWrapper` should not require any changes on your end. I will revert it while I investigate.

**Comment by matthewbauer** [comment]
So this was reverted I believe. Is it still a problem for you?

**Comment by mdorman** [comment]
It's not a problem for me; did the wrapper get revised in a way that fixed the problem, or are we simply still using the old wrapper?

**Comment by spacekitteh** [comment]
Bump, @ttuegel ?

**Comment by ttuegel** [comment]
We are still using the old wrapper, but for that matter I consider this issue closed. If someone wants to revive the new wrapper, I fully support that, but I never did uncover the actual problem.
