### ISSUE TITLE
Vulkan apps doesn't work except vkcube

### ISSUE THREAD

**Issue by Mifom** [NixOS/nixpkgs#178539]
### Describe the bug
I've tried to run Veloren(related issue https://github.com/NixOS/nixpkgs/issues/166101), build simple vulkan apps via  [bevy](https://bevyengine.org/) and [vulkano](https://vulkano.rs/), and it doesn't work. But vkcube works fine and vulkaninfo shows that vulkan is working fine.
```console
$ vulkaninfo | grep GPU
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
		GPU id = 0 (AMD RADV NAVI14)
		GPU id = 1 (AMD RADV RENOIR)
		GPU id = 2 (llvmpipe (LLVM 13.0.1, 256 bits))
GPU id : 0 (AMD RADV NAVI14):
GPU id : 1 (AMD RADV RENOIR):
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
GPU id : 2 (llvmpipe (LLVM 13.0.1, 256 bits)):
GPU0:
	deviceType        = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
GPU1:
	deviceType        = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
GPU2:
```

### Steps To Reproduce
1. Setup vulkan as described [here](https://nixos.org/manual/nixos/stable/index.html#sec-gpu-accel-vulkan)
2. Try to run any vulkan program
3. Try to run vkcube or vulkaninfo

### Expected behavior
Programs that use vulkan API should find drivers and work

### Screenshots

![vkcube](https://user-images.githubusercontent.com/23462908/174965996-427e44c3-dc7d-4175-bb15-e233bd8a6578.png)
![veloren](https://user-images.githubusercontent.com/23462908/174966516-107ccce1-ad21-488f-819e-4c0f94a28c6b.png)
![bevy](https://user-images.githubusercontent.com/23462908/174966538-9c462534-884f-4984-b452-ce117f88e25b.png)

### Additional context
GPU configuration for now is
```nix
{
  # boot.initrd.kernelModules = ["amdgpu"];

  hardware.opengl = {
    driSupport = true;
    # extraPackages = [pkgs.amdvlk];
  };
}
```
I've tried amdgpu on and off, it has no effect.

### Notify maintainers

@Ralith @yusdacra

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[mifom@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-21.05.4501.6d684ea3ade"`
 - channels(mifom): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Ralith** [comment]
If vkcube works, then Vulkan is working fine; the other programs you are having issues with are buggy, and you should consult with their maintainers. All of the screenshots you posted appear to use wgpu, so you could try reaching out to the wgpu maintainers as well.

**Comment by SuperSamus** [comment]
`vulkan-loader` cannot be dynamically linked if it's not in `LD_LIBRARY_PATH`.
[Example on Bevy](https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#nixos) .

**Comment by Ralith** [comment]
Dynamic linking works regardless of `LD_LIBRARY_PATH`, and is how vkcube is working fine above. You're thinking of dynamic *loading*, which is much less robust.
