### ISSUE TITLE
nodePackages.thelounge fails to build

### ISSUE THREAD

**Issue by al3xtjames** [NixOS/nixpkgs#178528]
### Steps To Reproduce
1. Add `services.thelounge.enable=true` to `configuration.nix` and run `nixos-rebuild`.
2.  Observe the following error:

### Build log
```
error: hash mismatch in fixed-output derivation '/nix/store/zdmxinjclx7bhwdi2rxw4mhckg9v6cfr-node-sqlite3-918052b.drv':
         specified: sha256-ec96SZpzXrYMPJVhlWmRAWIBjfhpj/XEOzc4ZjToB18=
            got:    sha256-aVBFmkxZsosRJtUuZ+cipdEVD7rP7tt6nfpGd4oWigQ=
error: 1 dependencies of derivation '/nix/store/w5lb2xjnds4bbanyrhc59vdgfwf7yz0w-thelounge-4.3.1.drv' failed to build
building '/nix/store/ydc9ln3sfxzqayvr9z3cnxa588f4b16w-perl-5.34.1-env.drv'...
error: 1 dependencies of derivation '/nix/store/r1dgbvd6p85nwi4g2mg1wmny05i57d57-system-path.drv' failed to build
```

### Additional context
This started failing on Hydra with https://hydra.nixos.org/build/180616880. I narrowed this down to 7245b3fb673e8c81596ee13b797d6538b6a91955, which changed the sha256 of the version of node-sqlite3 used by nodePackages.thelounge. I ran `nixpkgs/pkgs/dev/node-packages/generate.sh` in a local copy of nixpkgs and it restored the original sha256, so I think this may have been a mistake. I opened #178401 to revert the sha256 change, though I'm not sure if this will break anything.

### Notify maintainers

@winterqt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.46-hardened1, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by winterqt** [comment]
This is super weird -- the revision of the sqlite3 repo didn't change, yet the hash that node2nix generated was completely different. The fact that this fixed itself after running it again just adds to it. Guess we can just hope it doesn't happen again (to this or any other packages), else we have a much worse issue in our hands.

@SuperSandro2000 Since this was your run of node2nix, do you have any clue what could've happened here?

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 Since this was your run of node2nix, do you have any clue what could've happened here?

Not sure but since it is such a long running process it might change things between the start and the hash is generated.

But fixed for now.

**Comment by winterqt** [comment]
> Not sure but since it is such a long running process it might change things between the start and the hash is generated.

But how would it do that, if the exact same revision was written (just a different hash)?
