### ISSUE TITLE
Qt 5 setup hook sets -fPIC which can break builds

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#17862]
## Issue description

At [this line of code](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/5.5/qtbase/setup-hook.sh#L65) we add `-fPIC` flag to `NIX_CFLAGS_COMPILE`, causing it to apply to all compiled builds unconditionally. This breaks build of new VirtualBox because it tries to build kernel modules, which shouldn't have `-fPIC` applied. It can be disabled by setting `NIX_QT_PIC` but the name seems to convey that this is a guard against adding it several times, not a disable flag. But the bigger question is -- why is it there at all? It's strange to have a compile flag inserted like this.

cc @ttuegel

**Comment by ttuegel** [comment]
Without `-fPIC`, a number of non-KDE CMake-based builds fail because the upstream developers don't respect Qt's compile flag requirements. I will remove it; I would rather break builds written by folks who don't know what they're doing than break builds written by folks who do.

**Comment by abbradar** [comment]
Yeah, I found the reason already -- `-reduce-relocations` requires that. Arch has disabled this option and someone [there](https://bugs.archlinux.org/task/45283) suggests that this can break PIE, and thus, reduce security. It remains a question how serious this claim is; also, this feature was not disabled in [Gentoo](https://github.com/gentoo/qt/blob/master/eclass/qt5-build.eclass#L617), [Fedora](http://pkgs.fedoraproject.org/cgit/rpms/qt5-qtbase.git/tree/qt5-qtbase.spec#n392) or Ubuntu/Debian (at least all they don't specify the flag which means that `./configure` tries to figure out its best, which IIUC means that it's enabled for x86).

**Comment by ttuegel** [comment]
It sounds like the best thing to do is disable `-reduce-relocations`.

**Comment by abbradar** [comment]
Hm, I'm not sure how effective those optimizations are what is to measure... Generally I'm against optimizations that require downstream modifications like that, but I don't have a strong opinion here.
