### ISSUE TITLE
nodejs: support corepack

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#178640]
NodeJS ships with corepack nowadays, and with `corepack enable` that installs a bunch of wrappers for npm, pnpm, yarn so that they honor the `packageManager` field in package.json.

It's fairly trivial to ship these wrappers too. I wouldn't mind if they were part of the regular nodejs package, but perhaps they should be a separate corepack package?

**Comment by wmertens** [comment]
Thinking about it some more, since upstream doesn't make them part of the package, I think a corepack package is better. I'll try to make one.

**Comment by wmertens** [comment]
Thinking about it some more, since upstream doesn't make them part of the package, I think a corepack package is better. I'll try to make one.

**Comment by aduh95** [comment]
FWIW I've opened https://github.com/nodejs/corepack/pull/244 to document a workaround for users of Nix.

**Comment by wmertens** [comment]
I created #244646 instead but it's waiting on review from someone.
