### ISSUE TITLE
vala shouldn't have a default version

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#17869]
## Issue description

vala major versions break backwards compatibility. This, while using older vala version causes runtime errors and possibly compile time errors.

As such, vala shouldn't have a default version.

Note: Originally, this issue was about tracking the current version with the default vala namespace thinking the breakage only goes one way. Informed there's issues with runing both too old and too new versions, the proposal is now changed to dropping the vala default namespace altogether.

<details>
<summary>Original submission:</summary>
Beyond the obvious bug fixes, upstream vala updates (0.32.1 being the latest) include binding and symbol updates matching latest GTK\GNOME libraries: https://github.com/GNOME/vala/commits/0.32.1

In practice, this means that vala needs to track the latest packaged gtk and glib or runtime and compile time error will occur. Already, the latest GNOME explicitly depends on 0.32 vala branch.

However, while vala itself compiles quickly enough, the whole gnome ecosystem depends on vala and will need recompilation & testing for the newer bindings.
</details>

**Comment by vcunat** [comment]
I think @lethalman understands the vala stuff.

**Comment by vcunat** [comment]
IIRC there used to be an argument that the major vala version should best be specified explicitly for each package.

**Comment by RamKromberg** [comment]
> vala version should best be specified explicitly

I'm guessing it was gnome2 vs. gnome3 conflicts. If that's the case, those should be resolved now with the removal of gnome2.

Regardless, I agree waiting for someone who actually understand Vala is best. After all, this is an issue, rather then a pull request, for a reason ;)

p.s. I'm surprised vala wasn't just baked in with the rest of gnome seeing how the whole language hangs on gobjects so they're joined at the hip...

**Comment by lethalman** [comment]
Vala major release are often not backwards compatible. So it's not a good idea to have a "default" version of it. Minor updates are obviously not a problem.

**Comment by RamKromberg** [comment]
@lethalman ok then I'll change the thesis... :D

**Comment by RamKromberg** [comment]
I've PRed the deprecation of the default namespace. I kept the current versions the same so it shouldn't lead to any recompilation I hope. The idea is that next time someone touches the package, they'll be aware of the specific vala version and will try to match it to their glib of choice so the problem will sort itself out over time.

**Comment by RamKromberg** [comment]
PR merged. Thanks everyone :)
