### ISSUE TITLE
multimarkdown has incomplete closure

### ISSUE THREAD

**Issue by phanimahesh** [NixOS/nixpkgs#17863]
## Issue description

mmd2pdf complains that latexmk is missing. It looks like a bad closure
### Steps to reproduce

```
nix-env -i multimarkdown
mmd2pdf anything.md
```

cries out

```
$HOME/.nix-profile/bin/mmd2pdf: line 54: latexmk: command not found
It doesn't appear that latexmk is installed properly.
Be sure you have a working LaTeX installation.
```
## Technical details
- System: Ubuntu 16.04.1 LTS
- Nix version: 1.11.2
- Nixpkgs version: "16.09pre88706.b8e215f"

**Comment by Profpatsch** [comment]
Has been fixed in the meantime.
