### ISSUE TITLE
nixos-unstable not being updated

### ISSUE THREAD

**Issue by laMudri** [NixOS/nixpkgs#17866]
Despite some [new successful builds](http://hydra.nixos.org/build/38616152) of nixos-unstable in the past week, the corresponding branch in the [NixOS/nixpkgs-channels](https://github.com/NixOS/nixpkgs-channels) repository hasn't had any commits since 2016-08-10.

**Comment by vcunat** [comment]
It happens sometimes that the channel doesn't update for no apparent reason; I don't know why.

**Comment by domenkozar** [comment]
It's due to https://github.com/NixOS/nixos-channel-scripts/commit/ab086b22efb4865c2b9180bff1d17aa46f64da70

To quote @edolstra from IRC:

```
15:17:49        niksnut | domenkozar: looks like the programs.sqlite generation is barfing                                                              │ alanz
15:17:50        niksnut | Aug 19 12:25:00 webserver update-nixos-unstable-small-start[30523]: error: this derivation has bad ‘meta.outputsToInstall’

**Comment by obadz** [comment]
So related to https://github.com/NixOS/nixos-org-configurations/commit/26989b60bb2b46ebd73ee3110bd54f3365a85156 then ?

**Comment by domenkozar** [comment]
Yes.

**Comment by obadz** [comment]
@edolstra: looks like you're the only one who usually pushes things to these these 2 repos.

**Comment by ibor** [comment]
Unstable still does not upgrade. Just realized that since August, 10th, all directories in http://nixos.org/releases/nixos/unstable/ have the string "-tmp" to their name.

**Comment by obadz** [comment]
Reopening as `nixos-unstable` seems to no longer be readable in https://nixos.org/channels/ (doesn't even show in directory listing)

**Comment by vcunat** [comment]
That seems to be the only case. The others have today's timestamp and look OK (tested updating nixpkgs-unstable).

**Comment by vcunat** [comment]
It will likely be fixed automatically when the next channel bump is initiated, but first we've got to fixup the remaining failures on Hydra.

**Comment by despairblue** [comment]
@vcunat What is a channel bump? Is it when nixos-unstable gets changed to nixos-16.09?

**Comment by edolstra** [comment]
Channel is back via some temporary hackery.

**Comment by vcunat** [comment]
@despairblue: FTR I meant channel update, i.e. any change of its commit revision.

**Comment by laMudri** [comment]
Happening again?

**Comment by vcunat** [comment]
Possibly. Yesterday I thought it was a bit suspicious.

**Comment by 8573** [comment]
It seems to have disappeared from <https://nixos.org/channels/> again. The previous time I checked, it was there but hadn't been updated since August.

**Comment by domenkozar** [comment]
It seems to be fixed now.

**Comment by philandstuff** [comment]
Is it happening again? nixos-unstable was lasted updated 2016-09-13 05:32, while nixos-unstable-small is a week newer at 2016-09-20 11:36.  I'd expect [this hydra job](http://hydra.nixos.org/build/40827703) to have hit the unstable channel by now.

**Comment by bachp** [comment]
There doesn't seem to be a nixos-unstable at https://nixos.org/channels/ at the moment. Same issue as before?

**Comment by puffnfresh** [comment]
Hitting this problem right now.

**Comment by edolstra** [comment]
It's back again (and hosted on S3).

**Comment by vcunat** [comment]
@edolstra: this "broke" the link to unstable releases from bottom of http://nixos.org/nixos/download.html &ndash; the URL doesn't provide a directory listing now (noticed on IRC).

**Comment by vcunat** [comment]
More problems in separate thread: https://github.com/NixOS/nixpkgs/issues/20735
