### ISSUE TITLE
signal-desktop: failure to create tray icon

### ISSUE THREAD

**Issue by AndrewKvalheim** [NixOS/nixpkgs#178892]
### Describe the bug

Signal fails to create its tray icon due to a missing runtime dependency.

### Steps To Reproduce

With a system tray (e.g. `gnomeExtensions.appindicator`) available, start Signal with [`--use-tray-icon`](https://github.com/signalapp/Signal-Desktop/issues/2210). Signal logs an error and no tray icon appears:

> ```console
> $ nix-shell --packages 'pkgs.signal-desktop' --run 'signal-desktop --use-tray-icon'
> …
> {"level":30,"time":"2022-06-24T19:26:59.675Z","pid":143240,"hostname":"laptop","msg":"System tray service: created"}
> {"level":30,"time":"2022-06-24T19:26:59.676Z","pid":143240,"hostname":"laptop","msg":"System tray service: updating main window. Previously, there was not a window, and now there is"}
> {"level":30,"time":"2022-06-24T19:26:59.676Z","pid":143240,"hostname":"laptop","msg":"System tray service: rendering no tray"}
> {"level":30,"time":"2022-06-24T19:26:59.676Z","pid":143240,"hostname":"laptop","msg":"System tray service: enabling"}
> {"level":30,"time":"2022-06-24T19:26:59.676Z","pid":143240,"hostname":"laptop","msg":"System tray service: rendering the tray"}
> {"level":30,"time":"2022-06-24T19:26:59.676Z","pid":143240,"hostname":"laptop","msg":"System tray service: creating the tray"}
> [143240:0624/122659.678303:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> [143240:0624/122659.679224:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> ```
>
> <img alt="screenshot" src="https://user-images.githubusercontent.com/1844746/175656299-37ad9e66-b3ef-4ddb-b8c3-d9955cfc86a8.png" width="200" />

### Expected behavior

Adding `libappindicator-gtk3` as a runtime dependency restores the expected behavior—the error message is gone and the tray icon appears:

> ```console
> $ nix-shell --packages 'pkgs.signal-desktop.overrideAttrs (a: { runtimeDependencies = a.runtimeDependencies ++ [ pkgs.libappindicator-gtk3 ]; } )' --run 'signal-desktop --use-tray-icon'
> …
> {"level":30,"time":"2022-06-24T19:33:24.345Z","pid":145914,"hostname":"laptop","msg":"System tray service: created"}
> {"level":30,"time":"2022-06-24T19:33:24.345Z","pid":145914,"hostname":"laptop","msg":"System tray service: updating main window. Previously, there was not a window, and now there is"}
> {"level":30,"time":"2022-06-24T19:33:24.346Z","pid":145914,"hostname":"laptop","msg":"System tray service: rendering no tray"}
> {"level":30,"time":"2022-06-24T19:33:24.346Z","pid":145914,"hostname":"laptop","msg":"System tray service: enabling"}
> {"level":30,"time":"2022-06-24T19:33:24.346Z","pid":145914,"hostname":"laptop","msg":"System tray service: rendering the tray"}
> {"level":30,"time":"2022-06-24T19:33:24.346Z","pid":145914,"hostname":"laptop","msg":"System tray service: creating the tray"}
> ```
>
> <img alt="screenshot" src="https://user-images.githubusercontent.com/1844746/175656486-94e5e173-08f3-4a48-bbfa-18d7b742c9a2.png" width="200" />

### Additional context

I think this problem started upon updating to NixOS 22.05, but I wasn’t paying close attention to it.

### Notify maintainers

@mic92 @equirosa

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka), 22.05.1191.ccf8bdf7262`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-hardware"`
 - channels(user): `"home-manager-22.05.tar.gz, nixos-unstable, rust-overlay"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by equirosa** [comment]
Seems like a straightforward fix, would you like to make a PR?

**Comment by AndrewKvalheim** [comment]
Thanks @teutat3s. I got bogged down trying to create a test for this.

`--use-tray-icon` works fine in the existing X11+IceWM test so I’ve been trying to add a Wayland+Waybar one to cover this case.
