### ISSUE TITLE
Upgrading to NixOS 16.03.1241.5c40862 fails on texlive-cyrillic-2015 (wrong sha1 hash) 

### ISSUE THREAD

**Issue by fuzzy-id** [NixOS/nixpkgs#17907]
## Issue description

Running `nixos-rebuild switch --upgrade` fails with the following tail:
```
building path(s) ‘/nix/store/95ig3j604m482jd0fh6m5ar0dqixdf04-texlive-cyrillic-2015’
output path ‘/nix/store/95ig3j604m482jd0fh6m5ar0dqixdf04-texlive-cyrillic-2015’ has r:sha1 hash ‘1ydilc1c5h6bzsxd5frnjiaz3vhi06g8’ when ‘65scrc6656qqln2ifa9z6pcf3yv2lz5n’ was expected
cannot build derivation ‘/nix/store/vgngq4xy7irysd4bw9jhhhryc3l5fdd2-texlive-combined-2015.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/f7nlhsbfs5vj6nsqmf8mcw8s4qp8gpkl-texlive-xindy.bin-2015.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/is8hsrap5md2wrkc69alcr2h077a66k8-texlive-combined-medium-2015.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/bn0qxhn663j3al72vbdy5gahygz0wlic-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/lr9d8nvzn4ly0xm7ai60j4by4dw8myfh-nixos-system-nixos-16.03.1241.5c40862.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/lr9d8nvzn4ly0xm7ai60j4by4dw8myfh-nixos-system-nixos-16.03.1241.5c40862.drv’ failed
```

### Steps to reproduce

I guess having `texlive.combined.scheme-medium` in `environment.systemPackages` and then trying to evaluate the configuration should be sufficient. Nothing special when it comes to tex in my installation. 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
`16.03.1224.5237768 (Emu)`

* Nix version: (run `nix-env --version`)
`nix-env (Nix) 1.11.2`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
`"16.03.1241.5c40862"`

**Comment by fuzzy-id** [comment]
Looks like this could simply be solved by updating the corresponding hash in `pkgs/tools/typesetting/tex/texlive-new/fixedHashes.nix`. @peti is this the way to go here? If so, I'll see if I can make the corresponding changes, test and file a pull request. (Sounds like a nice exercise to get some hands-on experience in NixOS dev.)

**Comment by peti** [comment]
Yes, I think so. The hash changed upstream, so if we change it in Nixpkgs, too, then we should be fine.

**Comment by vcunat** [comment]
I suppose we could take what's in master now.

**Comment by vcunat** [comment]
Pushed; please, reopen in case of further problems.
