### ISSUE TITLE
Add Python libraries in neuron package

### ISSUE THREAD

**Issue by rqcy** [NixOS/nixpkgs#17914]
## Issue description

The NEURON simulation environment is often scripted with Python instead of its native hoc interpreter. Adding Python to the `neuron` package would be very useful.

**Comment by rqcy** [comment]
@adevress would it be difficult to implement?

Thanks for maintaining this (esoteric ;) ) package!

**Comment by adevress** [comment]
Hi rqcy,

No it should be doable and rather easy, I will add this in a future pull request.

**Comment by adevress** [comment]
@obadz Can you assign this ticket to me ? thank you in advance.

**Comment by obadz** [comment]
Hmmmm… apparently I can only assign to project members, sorry. I guess if anyone finds this issue they will know it's all yours.

**Comment by adevress** [comment]
@obadz That's fine but that's wierd, I was thinking I'm automatically attached for anything related to a package I maintain.

**Comment by rqcy** [comment]
> No it should be doable and rather easy, I will add this in a future pull request.

Thanks, that's really great!

Stefan

**Comment by FRidh** [comment]
when you mean you want to use Python with Neuron, is then the base interpreter enough or do you also want to use additional modules?

**Comment by rqcy** [comment]
> when you mean you want to use Python with Neuron, is then the base
> interpreter enough or do you also want to use additional modules?

Hi,

I'm not sure what do you mean by “base interpreter” and “additional
modules”.

I usually start Python or IPython, and import required modules, e.g.:

   import neuron
   from neuron import h

   import numpy as np
   import pandas as pd

etc.

Stefan

**Comment by FRidh** [comment]
I see, thanks for the example @rqcy .

Certain applications have a built-in interpreter that can be used to write plugins, e.g. FreeCAD, in which case you might want to use additional modules, like numpy. 

But sometimes, you want to use the libraries offered by the program, like you seem to want to do with Neuron. If you want to use it like this, then it makes sense to make this package available as a Python library. 

@adevress I recommend making the `python` parameter optional, that is, `python ? null`, and keep it as `null` for `pkgs.neuron` and `pkgs.neuron-mpi`. Then, in `python-packages.nix` you take `pkgs.neuron` and override it to add `python`. That way, `pkgs.neuron` is for those that want to use `neuron` without Python`, and `pkgs.pythonXXPackages.neuron` is build for the right interpreter version. We can discuss those details further in the PR.

**Comment by adevress** [comment]
Hi @FRidh 

I updated the pull request following your recommendation.

You have now a standard neuron and neuron-mpi modules without python support.
and a pythonPackages.neuron and pythonPackages.neuron-mpi with the python support for every version of python.

**Comment by FRidh** [comment]
Great! Merged so closing this.

**Comment by FRidh** [comment]
Actually, the bindings don't work just yet.

**Comment by adevress** [comment]
@FRidh  Ok I found the issue, the old prefix was not renamed properly, sorry for that.

Thank you for your testing @FRidh 

I just fixed it and tested it in an isolated python environment. The fix is available in this pull request #18187
