### ISSUE TITLE
gnome3.gnome-calculator doesn't build due to glib 2.48.2 bugfix bump

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#17912]
`nix-build '<nixpkgs>' -A gnome3.gnome-calculator` fails on `master`.

I've bisected the issue to 532f88cd3a568a18b4dc8f1b5dc39baae94b3374 (glib 2.48.1->2.48.2 bugfix revision) but don't know how to fix (Googling doesn't really help).

Build output:
```
  CCLD     libcalculator.la
make[1]: Leaving directory '/tmp/nix-build-gnome-calculator-3.20.2.drv-0/gnome-calculator-3.20.2/lib'
Making all in src
make[1]: Entering directory '/tmp/nix-build-gnome-calculator-3.20.2.drv-0/gnome-calculator-3.20.2/src'
make[1]: *** No rule to make target 'history-entry.ui', needed by 'resources.c'.  Stop.
make[1]: Leaving directory '/tmp/nix-build-gnome-calculator-3.20.2.drv-0/gnome-calculator-3.20.2/src'
make: *** [Makefile:427: all-recursive] Error 1
builder for ‘/nix/store/ly4pc321667bn8cdphm0bz7dq6kd0d0v-gnome-calculator-3.20.2.drv’ failed with exit code 2
```

We're probably not going to revert `glib` for this but at the same time this holds back `tests.gnome3` which holds back `nixos-unstable` release so we should address this.

If we can't find the solution maybe we can temporarily remove `gnome-calculator` from Gnome's default packages?

cc @lethalman @DamienCassou @vcunat

**Comment by vcunat** [comment]
I suspect https://bugzilla.gnome.org/show_bug.cgi?id=673101 as it seems closely related and is listed to be "fixed" between those two versions.

**Comment by vcunat** [comment]
Confirmed. Patching glib to remove that single upstream commit fixes the build.

**Comment by obadz** [comment]
`!m vcunat`

**Comment by vcunat** [comment]
Pinged the upstream bug and hack-fixed the calculator build without a mass rebuild.
