### ISSUE TITLE
Darwin: can't update unstable channel due to case-sensitive issues 

### ISSUE THREAD

**Issue by kevingriffin** [NixOS/nixpkgs#179272]
### Describe the bug
Updating the unstable channel fails on Darwin:

```error: hash mismatch in file downloaded from 'https://releases.nixos.org/nixpkgs/nixpkgs-22.11pre387732.72d1b0d0fac/nixexprs.tar.xz':
         specified: sha256:04h7r496nc0vvd45d2v1ml1rjgb5hfgmp67sbqz1bz98vyi2r0jb
         got:       sha256:1alxxmr1dzn4vyfzcvgcs12mym0rh5l4vir4x861fiybwhx3b41x
```

this seems to be due to the by-default case-preserving nature of APFS (and HFS+), introduced with this PR:

https://github.com/NixOS/nixpkgs/pull/178509

which adds a path `tools/x11` which to macOS is the same as the already existing `tools/X11` path.

### Steps To Reproduce
1. Add the unstable channel to a macOS machine
2. `nix-channel --update`

### Expected behavior
A new version of the channel is successfully added to the machine.

### Notify maintainers
@azahi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.0.0, macOS 13.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.16`
 - channels(kevin): `"darwin, nixpkgs-22.11pre382065.5643714dea5"`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
 - nixpkgs: `/Users/kevin/.nix-defexpr/channels/nixpkgs`
```

**Comment by azahi** [comment]
My bad. Should we add a channel blocker label to this to get the PR merged faster?
