### ISSUE TITLE
16.03 dropbear initrd not seeing keys

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#17927]
## Issue description
I have an encrypted root system.  I am using grub to boot it. I tried to enable remote unlocking.  I feel like I am missing something simple but I can't figure it out for the life of me.
my config
```
boot.initrd.network.enable= true;
boot.initrd.network.ssh.enable = true;
boot.initrd.network.ssh.port=2000;
boot.initrd.network.ssh.authorizedKeys=[ "my public rsa key" ];
boot.initrd.network.ssh.hostRSAKey = "/etc/ssh/dropbear_rsa_host_key";
boot.initrd.network.ssh.hostECDSAKey = "/etc/ssh/dropbear_ecdsa_host_key";
boot.initrd.network.ssh.hostDSSKey = "/etc/dropbear/dropbear_dss_host_key";
```
There are keys there but the build initrd doesnt seem to do anything with this, when i boot it says that no key was at those three locations, meaing i assume they werent copied into the initrd 
### Steps to reproduce
install grub, build an initrd with this config, reboot to see error message.

## Technical details
16.03.1242.c5cbda2 (Emu)
nix-env (Nix) 1.11.2
"16.03.1242.c5cbda2"

**Comment by cleverca22** [comment]
if you specify the key paths without quoting things, it will copy the keys into /nix/store and treat them as normal dependencies

**Comment by abbradar** [comment]
Unfortunately, you need the keys in store (because we need to pack them into initrd), so you need to use unquoted paths.

We need to check that the keys is really there in initrd, will do later..

**Comment by mogorman** [comment]
passing without quotes did copy them into the nix store, but I won't be able to do a reboot till i get home today, i dont fully trust that it rebuilt the initrd and will work. Thanks for advice, I could have swarn I tried without quotes, but maybe I just had the path wrong.

**Comment by mogorman** [comment]
I just unpacked the initrd it looks like it did the job right. I will verify when I reboot from home later. Thanks for all help

**Comment by abbradar** [comment]
You are welcome! I've pushed a fix -- we now verify that keys have really got into initrd or fail during build.

**Comment by AntonLydike** [comment]
I just encountered the same Issue, dropbear states that no host key was found, but the build succeeds. This is my config:

```
boot.initrd.availableKernelModules = [ "igb" ];
  boot.initrd.network = {              
    enable = true;
    ssh = {                  
      enable = true;
      port = 2222;
      authorizedKeys = [ "ecdsa-sha2-nistp256 <key>" ];
      hostECDSAKey = /etc/nixos/host_ecdsa_key;
    };
    postCommands = ''
      echo 'cryptsetup-askpass' >> /root/.profile
    '';
  };
``` 

And the host key exists:
``` 
~# ll /etc/nixos/host_ecdsa_key
-rw------- 1 root root 141 Aug 11 10:30 /etc/nixos/host_ecdsa_key
```

Should I open a new issue for this, or is it a simple error on my end?
