### ISSUE TITLE
deluge: incompatible with libtorrent-rasterbar 1.1

### ISSUE THREAD

**Issue by xconstruct** [NixOS/nixpkgs#17924]
## Issue description

Deluge 1.3.12 is incompatible with current libtorrent-rasterbar 1.1 introduced in 0236661. There are a few exceptions thrown in the log and several core features do not work as expected, e.g. seeding torrents get queued, although queues are disabled. The Deluge team does not plan to fix this, but it looks like libtorrent might in version 1.1.1.

References:
http://forum.deluge-torrent.org/viewtopic.php?t=53939
http://forum.deluge-torrent.org/viewtopic.php?f=7&t=54059
https://bugs.archlinux.org/task/49861

## Technical details

* System: 16.09pre87431.3badad8
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre87431.3badad8

**Comment by phanimahesh** [comment]
Should we include an older version of libtorrent-rasterbar in the repos alongside current? We can point deluge to use it instead.

**Comment by xconstruct** [comment]
Yes, that would probably best in the meantime. 1.0.9 should work as expected.

**Comment by joachifm** [comment]
Looks like the PR that fixes this has been merged.
