### ISSUE TITLE
Qutebrowser needs the library tldextract in order for qute-pass to work

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#179361]
### Describe the bug
A clear and concise description of what the bug is

Qutebrowser has a userscript called qute-pass, which requires the Python library `tldextract`. However, installing `tldextract` system-wide apparently has no effect on whether qutebrowser can see it. 

### Steps To Reproduce
1. Install qutebrowser
2. Run qute-pass from within qutebrowser `:spawn --userscript qute-pass`
3. Notice that it complains about a missing `tldextract` library. But `tldextract` is already installed and available to the PATH

### Expected behavior

I should be able to run qute-pass 

### Notify maintainers
@jagajaga @rnhmjoj @ebzzry @dotlambda

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.4, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(jon): `"nixos"`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by dotlambda** [comment]
Qutebrowser already ships with tldextract:
https://github.com/NixOS/nixpkgs/blob/2be2461a98380707dcd3858f927f4fa090b84682/pkgs/applications/networking/browsers/qutebrowser/default.nix#L62
I am using qute-pass regularly and it works flawlessly.

How did you install qutebrowser and which commits are your channels on?

**Comment by dotlambda** [comment]
We patch the userscripts that qutebrowser ship with:
https://github.com/NixOS/nixpkgs/blob/2be2461a98380707dcd3858f927f4fa090b84682/pkgs/applications/networking/browsers/qutebrowser/default.nix#L103-L113
If you write your own or download others you have to manually make the required dependencies available to them.

**Comment by JonathanReeve** [comment]
Oh OK. I didn't realize they could be read if they weren't in ~/.local/share/... Just deleting my local copies of the userscripts did the trick. Thanks
