### ISSUE TITLE
nodejs upstream uses openssl 3

### ISSUE THREAD

**Issue by wmertens** [NixOS/nixpkgs#179346]
### Describe the bug

Our build of nodejs 18 uses OpenSSL v1, but upstream uses v3.

Actually, that suits me because it doesn't break webpack 4 like it does with upstream, but it also feels wrong so I thought I'd report it :-)

### Steps To Reproduce
1. `node -e 'console.log(process.versions.openssl)'`

### Expected behavior
return openssl v3

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka), 22.05.20220617.d17a56d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(wmertens): `"nix-ld"`
 - channels(root): `"nixos-21.11beta333771.8e6b3914626, nixos-hardware"`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by ajs124** [comment]
See #150093, sort of

**Comment by wereHamster** [comment]
I need to revert to openssl 1.1 (due to reasons…), but .override doesn't work:

```
pkgs.nodejs.override { openssl = pkgs.openssl_1_1; };
```

fails with

```
error: anonymous function at /nix/store/7xvq2zg4c26lp9gd1afv2j118zsn41xw-nixpkgs/nixpkgs/pkgs/development/web/nodejs/v18.nix:1:1 called with unexpected argument 'openssl'

       at /nix/store/7xvq2zg4c26lp9gd1afv2j118zsn41xw-nixpkgs/nixpkgs/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|
(use '--show-trace' to show detailed location information)
```

Overriding openssl works with (some) other packages, for example curl. Is there anything that can be done in the definition of the nodejs packages to allow it?

**Comment by ajs124** [comment]
you should be able to override. We do so in `pkgs/top-level/all-packages.nix` e.g.
```
  nodejs-14_x = callPackage ../development/web/nodejs/v14.nix {
    openssl = openssl_1_1;
  };
```

Also, since we build `nodejs-18_x` with `openssl_3` now, I'll close this issue.
