### ISSUE TITLE
pdfstudio: Can't build due to a 404 when fetching the source

### ISSUE THREAD

**Issue by camtauxe** [NixOS/nixpkgs#179490]
### Steps To Reproduce

(shown here with `nix` command syntax)
1. `NIXPKGS_ALLOW_UNFREE=1 nix build --impure nixpkgs#pdfstudio`

### Build log
```
trying https://download.qoppa.com/pdfstudio/v2021/PDFStudio_v2021_1_3_linux64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   330    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download PDFStudio_v2021_1_3_linux64.deb from any mirror
```

### Additional context

Trying that same URL in a browser does indeed get a 404. I guess Qoppa changed how their files or named (or worse, removed them).

### Notify maintainers

- @PhilippWoelfel 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.47, NixOS, 22.05 (Quokka), 22.05.20220623.b824c03`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by PhilippWoelfel** [comment]
Qoppa must have removed the download link for version 2021.1.3. PR https://github.com/NixOS/nixpkgs/pull/179495 upgrades to the latest 2021 version, which fixes the issue.
