### ISSUE TITLE
vaultwarden: Insecure permissions of files in state directory

### ISSUE THREAD

**Issue by PhilippWoelfel** [NixOS/nixpkgs#179415]
### Describe the bug
The service vaultwarden creates a state directory `/var/lib/bitwarden_rs`. After creation, the state directory and all files in it (including the sqlite database) are world readable. Since the point of vaultwarden is to store sensitive information, this seems like a bad choice. 

### Steps To Reproduce
1. Enable the vaultwarden service (`services.vaultwarden`)
2. Check permissions of  `/var/lib/bitwarden_rs`

### Expected behavior
All files in the directory `/var/lib/bitwarden_rs` (except for possibly `rsa_key.pub.pem` should have permissions 0600.

### Notify maintainers

@K900 @ncfavier @pennae @dywedir @alarsyo 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by K900** [comment]
That is actually not a major issue as Bitwarden is end-to-end encrypted, so the database dump is useless without the master password. That said, it should be an easy and harmless fix to set it to 0600.

**Comment by PhilippWoelfel** [comment]
I agree.

**Comment by PhilippWoelfel** [comment]
I suppose this is a security issue. We probably want to prevent someone from getting a database dump as much as possible.

**Comment by K900** [comment]
Sorry, completely forgot to actually submit the change. Here it is.
