### ISSUE TITLE
cant start docker 1.10 with ipv6 disabled via ipv6.disable=1 and an existing bridge with an IP

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#17946]
## Issue description

Docker 1.10 fails to run if you are using ipv6.disable=1 in your boot config and the docker0 bridge already exists. This is due to an upstream docker issue, https://github.com/docker/libnetwork/issues/892, so I'm putting it here for documentation sake.
### Steps to reproduce

Set boot.kernelParams = [ "ipv6.disable=1" ];
Set virtualisation.docker.enable = true;

$ docker --version
Docker version 1.10.3, build a34a1d59

Reboot, start docker. Stop docker, then restart docker. Docker will not start:

`
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: Failed to setup IP tables, cannot acquire Interface address: Interface docker0 has no IPv4 addresses 
`

Can be fixed, temporarily, by using  ip link set docker0 down; brctl delbr docker0; before starting docker.
## Technical details
- System:  16.03.1242.c5cbda2 (Emu)
- Nix version:  nix-env (Nix) 1.11.2
- Nixpkgs version: 16.03.1242.c5cbda2

**Comment by offlinehacker** [comment]
We have docker 1.12 in unstable and nixos 16.09, do you have the same issue if you update to latest docker?

**Comment by sheenobu** [comment]
@offlinehacker Nope! Thanks.
