### ISSUE TITLE
buildGoModule doesn't propagate buildInputs

### ISSUE THREAD

**Issue by dbarrosop** [NixOS/nixpkgs#179550]
### Describe the bug

I am trying to build a go application with `buildGoModule` that wraps around a binary. So when building the package I am passing the pkg with the binary as part of `buildInputs`, however, when the package is built the binary isn't made available. For instance:

``` nix
            backup-job = pkgs.buildGoModule.override { go = pkgs.go_1_18; } rec {
              pname = "backup-job";
              version = nixpkgs.lib.fileContents ./backup-job/VERSION;

              src = ./.;

              vendorSha256 = null;

              buildInputs = with pkgs; [ postgresql_13 ];

              doCheck = false;

              subPackages = [ "backup-job" ];
            };
```

Will compile the program correctly but won't make postgres binaries avaialble.

Looking at buildGoModule and buildGoPackage looks like it might have been an oversight. BuildGoModule doesn't do anything with the argument `buildInputs`:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-modules/generic/default.nix#L5
(there is no other occurrence of buildInputs in that file)

while `buildGoPackage` does:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-packages/generic/default.nix#L88

### Steps To Reproduce
1. Try to build a go app with buildGoModule passing buildInputs

### Expected behavior

Packages/Binaries in `buildInputs` should be available to the go program.

### Screenshots
N/A

### Additional context
N/A

### Notify maintainers

@NickCao @zowoq 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(dbarroso): `"darwin, home-manager, nixpkgs"`
 - nixpkgs: `/Users/dbarroso/.nix-defexpr/channels/nixpkgs`
```

**Comment by NickCao** [comment]
There's no reference of `buildInputs` in `buildGoModule` because it does not need special handling, the one in `buildGoPackage` is also extraneous and can be removed.

Back to your qestion, to make the binaries available to your go program at runtime, putting them in `buildInputs` just won't work, you need to instead wrap your program as such:
```nix
postInstall = ''
  wrapProgram $out/bin/pan --suffix PATH : ${gnupg}/bin
'';
```

**Comment by dbarrosop** [comment]
Ok, that did the trick. Apologies for the noise and thanks for the help. Nix/Nixpkgs is amazing but has quite the learning curve...
