### ISSUE TITLE
googleearth missing fontconfig

### ISSUE THREAD

**Issue by pngwjpgh** [NixOS/nixpkgs#17956]
## Issue description

Google Earth fails to start saying:
`./googleearth-bin: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`
### Steps to reproduce

```
$ nix-shell -p googleearth --run googleearth
```
## Technical details
- System: `16.09pre88945.5120af0 (Flounder)`
- Nix version: `nix-env (Nix) 1.11.2`
- Nixpkgs version: `16.09pre88945.5120af0`

**Comment by puffnfresh** [comment]
Reproduced

**Comment by puffnfresh** [comment]
The version is very old (from 2010) and doesn't use the new makeLibraryPath function. Will update.

**Comment by cleverca22** [comment]
i manualy filled in LD_LIBRARY_PATH to get it to start, but it promptly crashes within ~3 seconds

```
mmap2(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xe72bd000
mmap2(NULL, 2147487744, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap2(NULL, 2147618816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap2(NULL, 2147487744, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
Fatal error in __driConfigOptions line 1, column 0: out of memory.
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=14206, si_uid=1000} ---
Google Earth has caught signal 6.
```
and it is a 32bit process, it is trying to blow 2gig of its 3gig address space the instant it starts

**Comment by puffnfresh** [comment]
@cleverca22 can you try #18115 with the callPackage_i686?

**Comment by cleverca22** [comment]
both 32 and 64bit versions fail, he used the google-earth-stable_current debian files, and google updated them, so now the hashes are all wrong

**Comment by knedlsepp** [comment]
One reason why this is not working:
When trying `readelf -d /nix/store/rbhw0ss3vxg8d864qr23mvxwph022000-googleearth-6.0.3.2197/opt/googleearth/googleearth-bin`
I get the following runpaths. All of them refer to the `.dev` output of the libraries, which actually don't contain any shared objects.

`0x0000001d (RUNPATH)                    Library runpath: [:/nix/store/77rcbhg9s7klyf2b3v6apwn00qpglvcs-glibc-2.24-dev/lib:/nix/store/nqf16qqmzwgdc61fjd7j7q7sfwrg2yb3-glib-2.50.1-dev/lib:/nix/store/7s424vgakgvd91dqa33rwpvgsw96vbhn-gcc-5.4.0/lib:/nix/store/78ppdbsnpk4dfpw2a7d16yhp16hxdw71-libSM-1.2.2-dev/lib:/nix/store/0c8zvla57c0jxrrsyikrg40ana354nvg-libICE-1.0.9-dev/lib:/nix/store/k5lid1zqpjlwfn2mp95k054xk1imrb73-libXi-1.7.8-dev/lib:/nix/store/cqw8r9d7hbcl34szchrb9b4jixks4624-libXv-1.0.11-dev/lib:/nix/store/ncfk010ksq9jdnr62d76gnrm3lsna2vi-mesa-13.0.1/lib:/nix/store/3ghyg8r2ma0205b7phxjaa4k7h45v3an-libXrender-0.9.10-dev/lib:/nix/store/91836sdzzrq358b8wqjzich0y4bk5rwc-libXrandr-1.5.1-dev/lib:/nix/store/sc5hx8r5izlcpw8wkyi1lblkpmmayac3-libXfixes-5.0.2-dev/lib:/nix/store/222qay7ghad0ggwa7a869wr5hhhpwdwd-libXcursor-1.1.14-dev/lib:/nix/store/2a5zqbmckz16wcv1i7gd7rw5m2nnb3mi-libXinerama-1.1.3-dev/lib:/nix/store/5iamqcarbbwsb2w3w3sv2z331sz4ndrw-freetype-2.6.5-dev/lib:/nix/store/s0mvp1pn8k4n7acfx96i3pylbz89m4xn-libXext-1.3.3-dev/lib:/nix/store/rq864zkcb7c705pmg03bq1kzqm6m35wh-libX11-1.6.4-dev/lib:/nix/store/idh8ba4ycqj84ssrrh8772jh73zaxbsc-qt-4.8.7-dev/lib:/nix/store/x95zgnqc23pscf4nwwm5ksvikc1ka0li-zlib-1.2.8-dev/lib:/nix/store/8by8rwngb90kbdwkfvlm7q3hrrszga55-fontconfig-2.12.1-dev/lib]`
