### ISSUE TITLE
genericUpdater fails if nix-command isn't enabled

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#179602]
### Describe the bug
Trying to update my package `furnace` fails because `genericUpdater` assumes that `nix edit` just works.

```console
bt1cn@NixTop:~/devel/nixpkgs
↪ nix-shell maintainers/scripts/update.nix --argstr package furnace

Going to be running update for following packages:
 - furnace-0.5.8

Press Enter key to continue...

Running update for:
 - furnace-0.5.8: UPDATING ...
 - furnace-0.5.8: ERROR

--- SHOWING ERROR LOG FOR furnace-0.5.8 ----------------------

[...]

+ '[' -n 0.6pre1 ']'
+ '[' 0.5.8 '!=' 0.6pre1 ']'
++ EDITOR=echo
++ /nix/store/1psw6gi16i6188ww3clbnxaqr3mp9hqy-nix-2.9.1/bin/nix edit -f. furnace
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
+ pfile=


--- SHOWING ERROR LOG FOR furnace-0.5.8 ----------------------
```

### Steps To Reproduce
1. Don't have `nix-command` enabled? :shrug: 
2. `nix-shell maintainers/scripts/update.nix --argstr package furnace` or another package that uses `genericUpdater` / `gitUpdater`

### Expected behavior
I should be able to run the updateScript without having to worry about experimental features & whether or not they're enabled.

### Screenshots
n/a

### Additional context
https://github.com/NixOS/nixpkgs/blob/78f79c21e92eccda2edd66fe106f5b7e6881f9b9/pkgs/common-updater/generic-updater.nix#L95

I don't mess with experimental stuff (`nix-command` or `flakes`) and Nix versions aside from the default one. Would adding `--extra-experimental-features nix-command` be enough here without breaking stuff for everyone else?

### Notify maintainers
@romildo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.40-xanmod1, NixOS, 22.05 (Quokka), 22.05.342.a634c8f6c1f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(bt1cn): `"unstable"`
 - channels(root): `"nixos-22.05.342.a634c8f6c1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by romildo** [comment]
When the script was written, `nix edit` worked without any further options. `--extra-experimental-features nix-command` was introduced later.
