### ISSUE TITLE
add a mpvpaper ,please

### ISSUE THREAD

**Issue by prehonor** [NixOS/nixpkgs#179656]
**Project description**
MPVPaper is a wallpaper program for wlroots based wayland compositors, such as sway. That allows you to play videos with mpv as your wallpaper.

**Metadata**

* homepage URL: https://github.com/GhostNaN/mpvpaper
* source URL: https://github.com/GhostNaN/mpvpaper
* license: GPLv3
* platforms:  linux,

**Comment by wegank** [comment]
Blind-packaged [here](https://github.com/wegank/nur-packages/blob/main/pkgs/applications/graphics/mpvpaper/default.nix). Could you test if it works?

**Comment by prehonor** [comment]
> Blind-packaged [here](https://github.com/wegank/nur-packages/blob/main/pkgs/applications/graphics/mpvpaper/default.nix). Could you test if it works?

Thank you , I installed mpvpaper successfully, but I find wayfire could not use it as background program, so I cant make it run.

**Comment by lelgenio** [comment]
> Blind-packaged [here](https://github.com/wegank/nur-packages/blob/main/pkgs/applications/graphics/mpvpaper/default.nix). Could you test if it works?

Works great with sway :+1:

**Comment by wineee** [comment]
init at https://github.com/NixOS/nixpkgs/pull/185745
