### ISSUE TITLE
LDAP: NSLCD.conf File not generated if extraConfig more than one line long

### ISSUE THREAD

**Issue by SohamG** [NixOS/nixpkgs#179641]
### Describe the bug
I'm trying to get a nixos box setup with LDAP authentication provided by an AD domain controller.

I have noticed that /run/nslcd and children do NOT get generated if the value of `users.ldap.daemon.extraConfig` contains more than one line

### Steps To Reproduce
1. Use a config similar to this:
```
  users.ldap = {
    enable = true;
    base = "dc=domain,dc=tld";
    server = "ldap://ad.domain.tld";
    loginPam = true;
    nsswitch = true;
    bind.distinguishedName = "user@domain.tld";
    bind.passwordFile = "/root/binddn.passwd";
    daemon = {
      enable = true;
      extraConfig = ''
        bindpw super_secret_password
        some_other setting
      '';
    };
  };
```
2. Use `nixos-rebuild `test 
3. Notice `/run/nslcd` does not exist
4. Delete `some_other setting` from `extraConfig` and make it have only one (1) line
5. Re run `nixos-rebuild test`
6. Notice `/run/nslcd/*` exist

### Expected behavior
The `/run/nslcd/*` folder and subfiles should generate even for multi line extraConfig options

### Additional context
Trying to setup LDAP authentication on a nixos workstation.

I have bundled the system config in a basic flake which is pinned to nixpkgs release 22.05

Again, nixpkgs version is `release-22.05`

### Notify maintainers

@roberth @lheckemann @aanderse (Pinging because y'all seem to be involved in the ldap.nix file)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.05 (Quokka), 22.05.20220626.cd90e77`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by roberth** [comment]
I don't think I've worked on the module.
Looks like your file is written by a systemd service. Did you check the log with, say, `journalctl -u nslcd.service -n 100`?
That's all I can do, I'll defer to the others now.

**Comment by SohamG** [comment]
Sorry for bothering you Robert.

That command did tell me what was going wrong. I had some syntax troubles in my extraConfig which would prevent the systemd service from starting, resulting in no /run/nslcd

Closing.
