### ISSUE TITLE
fetchgit hash is not deterministic anymore

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#179623]
### Describe the bug
Noticed while debugging hash errors for #179604.

Since 1dfaad73ed98254c1c0522156fe45b115e0a8eb4 got merged via #177575 (bisect log further down), `fetchgit` doesn't produce fully deterministic results anymore. Sometimes I get an identical hash, several times in a row even? But often it's different.

It is worth noting that the fetcher output has changed after that commit. Using `furnace.src` as an example, the final line
```console
Removing `.git'...
```
has been replaced by
```console
Enumerating objects: 814, done.
Counting objects: 100% (814/814), done.
Compressing objects: 100% (789/789), done.
Writing objects: 100% (814/814), done.
Total 814 (delta 149), reused 646 (delta 0), pack-reused 0
Enumerating objects: 814, done.
Nothing new to pack.
```
for the main repository + every fetched submodule.

### Steps To Reproduce
1. `nix repl 'https://github.com/NixOS/nixpkgs/archive/15e41e3edfaa82c4a3aa2d1527fd142d59bdba7f.tar.gz'` (current master at the time of writing)
2. Inside repl: `:b fetchgit { url = "https://github.com/NixOS/nixpkgs.git"; rev = "15e41e3edfaa82c4a3aa2d1527fd142d59bdba7f"; fetchSubmodules = false; leaveDotGit = false; deepClone = false; sha256 = lib.fakeSha256; }`
3. Repeat 2. multiple times and you should get a different hash eventually. "Best" combo I got so far is 3 identical hashes before a different one.

### Expected behavior
Hashes shouldn't randomly be different. It would be understandable if the not-yet-deterministic `leaveDotGit` was used, but this happens even with `leaveDotGit = false`.

### Screenshots
Changing hashes:
![Bildschirmfoto von 2022-06-29 22-35-06](https://user-images.githubusercontent.com/23431373/176539673-f7730031-ef5b-4c4b-b03d-611e5cc6bb84.png)
![Bildschirmfoto von 2022-06-29 22-47-23](https://user-images.githubusercontent.com/23431373/176545218-f6d1cb65-6c67-4d31-9696-fc2a6dd7a5d6.png)

Changed output: (last identical lines are highlighted)
![Bildschirmfoto von 2022-06-29 21-54-03](https://user-images.githubusercontent.com/23431373/176546689-564e2380-4a6d-453c-a3aa-905a27831386.png)

### Additional context
Bisect log:
```console
git bisect start
# bad: [15e41e3edfaa82c4a3aa2d1527fd142d59bdba7f] Merge pull request #179358 from helsinki-systems/upd/jitsi
git bisect bad 15e41e3edfaa82c4a3aa2d1527fd142d59bdba7f
# good: [6b99e9620ee37b55610c7f23d3e46f2baa108d23] Merge pull request #177287 from trofi/fix-fno-common-for-fpm2
git bisect good 6b99e9620ee37b55610c7f23d3e46f2baa108d23
# good: [b83b1763a6cf40b337b6ee9c42bf13fe42a38cf8] Merge pull request #174673 from r-ryantm/auto-update/frostwire
git bisect good b83b1763a6cf40b337b6ee9c42bf13fe42a38cf8
# good: [a5bc99a9c9b2f15d38a97a8fe59157810c4b46f9] Merge pull request #179273 from r-ryantm/auto-update/python3.10-nibabel
git bisect good a5bc99a9c9b2f15d38a97a8fe59157810c4b46f9
# good: [62b05d9742520c1332d7060a287d2322c2571d95] Merge remote-tracking branch 'origin/master' into staging-next
git bisect good 62b05d9742520c1332d7060a287d2322c2571d95
# bad: [149d4997e80dd8b7f3ecf62457f89ceb5003ef14] Merge pull request #179453 from fabaff/niapy
git bisect bad 149d4997e80dd8b7f3ecf62457f89ceb5003ef14
# bad: [8f0e9204265181edc52e8608c9d079e984ff2751] Merge pull request #179437 from r-ryantm/auto-update/python3.10-plaid-python
git bisect bad 8f0e9204265181edc52e8608c9d079e984ff2751
# good: [f2bcc211d7fc313d6b83e666dc184c7fa0bebe7b] Merge pull request #179279 from AndersonTorres/file-managers
git bisect good f2bcc211d7fc313d6b83e666dc184c7fa0bebe7b
# good: [16de63fcc54e88b9a106a603038dd5dd2feb21eb] Merge pull request #179296 from fabaff/amass-bump
git bisect good 16de63fcc54e88b9a106a603038dd5dd2feb21eb
# good: [b5c2b76cf4e1888b231bd011c4e699ec937b23ac] androidndkPkgs.binaries: correct passthru parameters
git bisect good b5c2b76cf4e1888b231bd011c4e699ec937b23ac
# good: [038d9b4d2f987b7e56fab736a259a9778262e802] Merge pull request #178423 from wineee/notepad
git bisect good 038d9b4d2f987b7e56fab736a259a9778262e802
# good: [40a7e76ddeb00c1843faa898eada218183ab3f57] Merge pull request #178940 from r-ryantm/auto-update/apk-tools
git bisect good 40a7e76ddeb00c1843faa898eada218183ab3f57
# bad: [e4bf881ee0f38cfbd2c0ca63d97e9f73ae88ae46] Merge pull request #177575 from seppeljordan/nix-prefetch-git-fix
git bisect bad e4bf881ee0f38cfbd2c0ca63d97e9f73ae88ae46
```

Bisection done with `nix-build . -A furnace.src --no-out-link --check`. `furnace` uses `fetchFromGitHub` with `fetchSubmodules = true`, which uses `fetchgit` under the hood, but the hash change should be observable by directly using `fetchgit` as well.

### Notify maintainers
CC @seppeljordan (commit author)
CC @Ma27 (PR merger)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.40-xanmod1, NixOS, 22.05 (Quokka), 22.05.342.a634c8f6c1f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(bt1cn): `"unstable"`
 - channels(root): `"nixos-22.05.342.a634c8f6c1f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alyssais** [comment]
Pinning this until the fix has made its way into [channels](https://nixpk.gs/pr-tracker.html?pr=179689) and staging.

**Comment by Ma27** [comment]
Thanks a lot to everyone involved in investigating and fixing this! Also, I'm sorry for breaking this in the first place!

**Comment by johnrichardrinehart** [comment]
I'm seeing behavior that I think may be related to this issue. Please consider the derivation contained within the following flake:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/fe4be92e42ef0ebf5bf9e9fdc73ed6832b00e6d3";
  };

  outputs = { self, nixpkgs }: 
  let
    pkgs = nixpkgs.legacyPackages.x86_64-linux;
  in
  {
    defaultPackage.x86_64-linux = pkgs.fetchgit {
      #sha256 = pkgs.lib.fakeSha256; # suggests sha256-FZOLqCJkg/SSzAdAnL+51vl1iTPhoTxEHFvnrDK4iKY=
      #sha256 = nixpkgs.lib.fakeSha256; # suggests sha256-cyGMnYVHa9MjaU8gDy4tlPKwFivkErue1GgnbKjNnt8=
      #sha256 = ""; # suggests sha256-FZOLqCJkg/SSzAdAnL+51vl1iTPhoTxEHFvnrDK4iKY=
      url = "https://github.com/golang/go";
      rev = "913e3713bed373f85c7cdb933d3714dd587e685e";

      leaveDotGit = true;
    };
  };
}
```

Changing the dummy value of `sha256` results in different suggested replacement values. It seems to me that any value except for the corrected one should result in the same suggestion.

Furthermore, all suggestions _do_ build successfully (so the allowed values of `sha256` are not  unique) but the only one that actually respects `leaveDotGit = true` is the empty string case. This may indicate a separate problem with `fetchgit`.
