### ISSUE TITLE
[NixOS only] Option for Hyprland

### ISSUE THREAD

**Issue by ObsidianChickenz** [NixOS/nixpkgs#179726]
**Project description**
_describe the project a little_
Hyprland, a new Wayland compositor, recently got added to Nixpkgs. However, there is no option to enable it in configuration.nix, unlike Sway, another Wayland compositor. Is there any way for Hyprland to get its own option in configuration.nix?

**Metadata**

Note: Hyprland is already in the repos
* homepage URL: https://github.com/hyprwm/Hyprland
* source URL: https://github.com/hyprwm/Hyprland
* license: BSD 3-Clause "New" or "Revised" License
* platforms: Linux

**Comment by cid-chan** [comment]
Right now, the project uses experimental feature in wlroots.
However, the project already has a flake and within it a nixosModule. You can use that one.

**Comment by ObsidianChickenz** [comment]
Thanks!
