### ISSUE TITLE
kexec-tools fails to cross-compile for powerpc64

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#179714]
### Steps To Reproduce
1. `nix build 'nixpkgs/master#pkgsCross.ppc64.kexec-tools'`

### Build log

```
  powerpc64-unknown-linux-gnu-gcc -fno-zero-initialized-in-bss -m64 -msoft-float -fno-exceptions -mcall-aixdesc -Os -fno-builtin -ffreestanding -fno-zero-initialized-in-bss -fno-PIC -fno-PIE -fno-stack-protector -m64 -msoft-float -fno-exceptions -mcall-aixdesc -I./purgatory/include -I./purgatory/arch/ppc64/include -I./util_lib/include -I./include -Iinclude -I/nix/store/gsi5xm27kwwim182m9yk66ghpyr5iy4k-powerpc64-unknown-lin  ux-gnu-stage-final-gcc-debug-10.3.0/lib/gcc/powerpc64-unknown-linux-gnu/10.3.0/include  -c -MD -o purgatory/purgatory.o purgatory/purgatory.c
  cc1: error: '-mcall-aixdesc' incompatible with '-mabi=elfv2'
  make: *** [Makefile:124: purgatory/purgatory.o] Error 1
```

### Additional context

From my little research, it seemed that the usage of the ELFv2 ABI on PowerPC64 big-endian is non-standard? (Not sure, I'm pretty new at this).

The [GCC documentation on PowerPC options](https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/RS_002f6000-and-PowerPC-Options.html#RS_002f6000-and-PowerPC-Options) says that ELFv1 is the default for ppc64be and ELFv2 the default for ppc64le, and that:

> Overriding the default ABI requires special system support and is likely to fail in spectacular ways.

While I can run ELFv2 code on a ppc64be board that I have, some packages expect ELFv1, notably old version of the Kernel, and kexec-tools

Newer versions of the kernel explicitly set `-mabi=elfv1`.

Related PR: #116495

So, should we:

- switch the ppc64 abi back to ELFv1?
- or add "powerpc64-linux" in `meta.badPlatforms`? (This prevent kexec-tools to be built when building a NixOS configuration)

Seems to me like we can't patch `kexec-tools` to force ELFv1?

### Notify maintainers

@r-burns for his PR mentioned above.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.20220628.babb041`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-22.05"`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by minijackson** [comment]
Note: switching the ppc64 ABI to ELFv1 makes the NSS build fail.

**Comment by minijackson** [comment]
Other note: it seems that the nettle library only supports ELFv1 for ppc64be. From the [README](https://git.lysator.liu.se/nettle/nettle/-/blob/cbb93c3d1121feb40c2642d3b9b920a3e71b2e69/powerpc64/README):

> Big-endian systems only support ELFv1 ABI

**Comment by r-burns** [comment]
There's some more rationale for using elfv2 in my original ppc64be PR https://github.com/NixOS/nixpkgs/pull/111345. It's true that some older packages have problems with elfv2, but modern packages can have problems with elfv1 or outright refuse to support it, so I thought elfv2 would be a more reliable default going forward. FreeBSD, Gentoo, and Void Linux repos are useful for finding elfv2 patches, e.g. https://github.com/void-linux/void-packages/blob/6c1192cbf166698932030c2e3de71db1885a572d/srcpkgs/nettle/patches/ppc64-elfv2.patch

**Comment by r-burns** [comment]
Oh also, here's Void's patch for kexec-tools: https://github.com/void-linux/void-packages/blob/6c1192cbf166698932030c2e3de71db1885a572d/srcpkgs/kexec-tools/patches/ppc64-elfv2.patch

**Comment by minijackson** [comment]
@r-burns thanks a lot for your comment, it helped me quite a lot! I managed to have a fully usable NixOS config for PowerPC64 BE :tada: 

I'll be upstreaming a few PRs related to that, if you want me to tag you, please tell me.

**Comment by r-burns** [comment]
Great to hear! Please do tag me. I can't promise I'll have time to review them but I would certainly like to follow along.

**Comment by minijackson** [comment]
Issue was fixed in linked PR above and backported
