### ISSUE TITLE
How do i use iptables legacy

### ISSUE THREAD

**Issue by JosiahBSharkey** [NixOS/nixpkgs#179741]
## Issue description
Nftables breaks kubernetes so it is unusable also the default firewall is way to insecure I need to be able to set input output forward to default to drop because I dont trust tor without that I need prerouting for full system torify and full router torify and post routing to masquerade between different subnets and vlans

### Steps to reproduce 
The firewall Nat and nftables modules are all broken because they use nftables and that breaks kubernetes

## Technical details
Nftables is broken and not supported by kubernetes and it is the only option I have been able to find for the current version of nixos

**Comment by bryanasdev000** [comment]
> ## Issue description
> Nftables breaks kubernetes so it is unusable also the default firewall is way to insecure I need to be able to set input output forward to default to drop because I dont trust tor without that I need prerouting for full system torify and full router torify and post routing to masquerade between different subnets and vlans
> 
> ### Steps to reproduce
> The firewall Nat and nftables modules are all broken because they use nftables and that breaks kubernetes
> 
> ## Technical details
> Nftables is broken and not supported by kubernetes and it is the only option I have been able to find for the current version of nixos

I think you can use:

```
networking.nftables.enable = false;
networking.firewall.package = pkgs.iptables-legacy;
```

**Comment by flokli** [comment]
> Nftables breaks kubernetes so it is unusable also the default firewall is way to insecure I need to be able to set input output forward to default to drop because I dont trust tor without that I need prerouting for full system torify and full router torify and post routing to masquerade between different subnets and vlans

Can you be a bit more precise, and provide some references on why/how nftables breaks kubernetes? We use iptables-nftables-compat, so you (or kubernetes) should still be able to invoke iptables, it'd just internally be configured in the nft ruleset. See https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables#using_iptables_nft for details.

**Comment by nikhiljha** [comment]
> level=warning msg="Failed to install iptables rules" error="unable to run 'iptables -t filter -S' iptables command: exit status 1 stderr="iptables v1.8.7 (nf_tables): table `filter' is incompatible, use 'nft' tool.\n\n"" subsys=iptables

@flokli Here's a logline from cilium (a kubernetes component). The nf_tables backend doesn't support everything it needs.

**Comment by flokli** [comment]
https://github.com/cilium/cilium/issues/4825 seems to be the upstream tracking issue in Cilium. The bug here is really Cilium still not having proper nftables support.

If you need to run Cilium, you probably need to give it an old iptables (as was described in https://github.com/NixOS/nixpkgs/issues/179741#issuecomment-1188796132), or get that part of `iptables-nft` fixed (which is not a NixOS issue, many distros switched to `iptables-ntf`).

`iptables-nft` is a bandaid, and userspace tools should properly support the new stuff.
NixOS (and other distros) won't stick with old iptables just because some userspace hasn't upgraded their stuff.

**Comment by lucasfcnunes** [comment]
@nikhiljha, how did you make cilium stop spamming this log line?
I'm having the exact same issue right now with seemingly nothing broken in my cluster.
