### ISSUE TITLE
folly: incorrect license

### ISSUE THREAD

**Issue by adevress** [NixOS/nixpkgs#17977]
## Issue description

The folly package is reference with a MIT license (licenses.mit).
This is incorrect, the license of the facebook's folly library is an Apache 2.0 ( ASL 2.0 ) 

https://github.com/facebook/folly/blob/master/LICENSE

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by adevress** [comment]
@abbradar ping

**Comment by abbradar** [comment]
Thanks for reporting this!
