### ISSUE TITLE
pjsip: move to different directory ?

### ISSUE THREAD

**Issue by adolfogc** [NixOS/nixpkgs#17971]
## Issue description

Should the _pjsip_ package be moved from _pkgs/applications/networking_ to _pkgs/development/libraries_?
### Steps to reproduce

N/A
## Technical details
- System: 16.09pre87999.20f009d (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre87999.20f009d"

**Comment by joachifm** [comment]
cc maintainer @viric
