### ISSUE TITLE
fetchgit ignore deepClone and does a shallow clone anyway

### ISSUE THREAD

**Issue by jbgi** [NixOS/nixpkgs#179788]
Since #130040 `deepClone = true;` (for `fetchgit` and `fetchFromGitHub`) and `nix-prefetch-git --deepClone` don't work anymore.
ie, when running
```sh
cat $(nix-prefetch-git --quiet --deepClone --leave-dotGit https://github.com/NixOS/rfcs 220af8e4f171425d168334f07163ea3db2eb8161 | jq -r .path)/.git/shallow
```
Actual result : 
```
220af8e4f171425d168334f07163ea3db2eb8161
```
Expected:
```
cat: /nix/store/h1rfypna3gfbxnkhza30yjd792wr0id5-rfcs-220af8e/.git/shallow: No such file or directory
```

Reverting #130040 fix the issue, but the optimization should be kept when `deepClone` is not used.

**Comment by Atemu** [comment]
Could you give a real-world scenario for deepClone? All the ones in Nixpkgs are broken, with or without the optimisation.

AFAICT your reproducer merely checks whether a clone is sparse?

**Comment by jbgi** [comment]
My real-world scenario is for a short-lived, local only derivation where the broken aspect (non-determinism) of `deepClone` are ok.

My issue is that the doc say:
> If `deepClone` is set to true, the entire repository is cloned as opposing to just creating a shallow clone. 

but my reproducer shows that this is not the case: `--deepClone` produce a shallow clone. This should either be fixed, or `--deepClone` be removed entirely if we don't want to support it. I don't really care either way, I can use 21.05 for the non (completely) broken fetchgit, and anyway my use-case is mostly for some convenience during testing a "merge multiple repos" script, but nothing I can't live without.

**Comment by Atemu** [comment]
What I need is a concrete Nix example snippet that makes use of a property of deepClone and doesn't work without because I don't know what deepClone is useful for.  
I need to be able to understand what the script did before my patch, why it's different now and how that affects real-world deepClone usage.

Relying on a stable version is not a good idea as that will be deprecated in half a year or so and will likely break in the future. My change should also not have caused any regressions in the real world.

Given that it's taken this long for someone to find out though, I also question why we even need deepClone. I also don't really understand why you'd need it in the first place. It'd be great if you, as a real-world consumer of that feature, could enlighten me of that

**Comment by jbgi** [comment]
Well the point of using deepClone is to retain the full git history, my use case is merging multiple repos into one, while preserving history, which is why I needed deepClone to work (though I could work around it by not doing this in a nix derivation). It's here :
https://github.com/input-output-hk/cardano-world/blob/prepare-monorepo/nix/cardano/prepare-mono-repo/default.nix

#130040 force use of `--depth=1` (shallow clone), even if a `deepClone` is asked for.

**Comment by wcole3** [comment]
Bumping to see if anyone has workarounds for this.  Some projects make use of the contents in the .git folder and without deep clones they cannot be built cleanly.  An example of a repo that makes use of the .git folder is https://github.com/PX4/PX4-Autopilot

**Comment by emily-is-my-username** [comment]
@wcole3
Disabling the optimized shallow clone when `--deepClone` is explicitly requested worked for me [(patch here)](https://github.com/emily-is-my-username/nixpkgs/commit/ad945416620b651dce0857c75377d979e7a8ac71)

@Atemu
My use case is building OpenStack projects directly from git with Nix. Most of them use [PBR](https://docs.openstack.org/pbr/latest/), which requires a working git repository to build sdist tar archives. It seems to be possible to build them from a shallow copy, but it breaks some of PBRs features and messes up package metadata.

Admittedly, that is not really a concern for NixOS nor nixpkgs - the upstream projects could be packaged using tarballs from PyPI - but developing and testing custom builds seems cumbersome if they need to be preprocessed *outside* of Nix.

At the moment, I don't have anything to show but I may be able to provide a snippet next week.

**Comment by infinisil** [comment]
@emily-is-my-username I created a PR from your patch! I hope you don't mind: https://github.com/NixOS/nixpkgs/pull/252865
