### ISSUE TITLE
VibrantLinux Packaging Request

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#179873]
**Project description**
vibrantLinux is a GUI tool to serves the same purpose as [VibranceGUI](https://vibrancegui.com/) for Windows, which to modify the saturation of any given screen whenever certain programs are launched/are in focus.

**Metadata**

* homepage URL: https://github.com/libvibrant/vibrantLinux
* source URL: https://github.com/libvibrant/vibrantLinux
* license: MIT
* platforms: Linux Only

**Comment by vid** [comment]
Bump. I have some low vision issues and "vibrance" makes it much easier to read the screen. Thanks!
