### ISSUE TITLE
Difference between `nix-shell -A sthg` and `nix-shell shell.nix`

### ISSUE THREAD

**Issue by YPares** [NixOS/nixpkgs#17984]
## Issue description

When I run `nix-shell '<nixpkgs>' -A haskell.compiler.ghc801`
the dependencies are downloaded like they should and everything goes OK.

However, if I make this simple `shell.nix` which should do the same:
```
let p = import <nixpkgs> {};
in p.haskell.packages.ghc801
```

and then run `nix-shell ./shell.nix` then it fails with:
```
error: assertion failed at /nix/store/175hf0qc88288pmdgfnr90r76nj465vi-nixpkgs-16.09pre88945.5120af0/nixpkgs/pkgs/os-specific/darwin/apple-source-releases/CF/default.nix:4:1
(use ‘--show-trace’ to show detailed location information)
```

and I had to add `allowBroken = true` to my `.nixpkgs/config.nix` to see that, or else in the second case it just goes:
```
error: Package ‘Elm-0.13’ in ‘/nix/store/175hf0qc88288pmdgfnr90r76nj465vi-nixpkgs-16.09pre88945.5120af0/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:4632’ is marked as broken, refusing to evaluate.
```

## Technical details

* System: Ubuntu 15.10
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre88945.5120af0

**Comment by aspiwack** [comment]
I can reproduce with an older nixpkgs version:

```
$ ﻿⁠⁠⁠⁠nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre83147.df89584
```

**Comment by YPares** [comment]
My bad, I had put "packages" instead of "compiler" in the shell.nix file...

**Comment by YPares** [comment]
Didn't want to close it.
The problem is th

**Comment by YPares** [comment]
Ok, so the problem is that compilers are available both under
`haskell.compiler.ghc*`
and `haskell.packages.ghc*`
why is there a difference between both? That's sort of error-prone.
