### ISSUE TITLE
pkgs.linux.override { extraConfig = ... } stopped working?

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#17989]
## Issue description

On NixOS 16.03 I use this override to customize the kernel config:

```
  nixpkgs.config = {
    packageOverrides = pkgs: {
      linux_4_4 = pkgs.linux_4_4.override {
        # Add Ubuntu CIFS configuration
        extraConfig = ''
          CIFS_STATS y
          CIFS_WEAK_PW_HASH y
          CIFS_UPCALL y
          CIFS_XATTR y
          CIFS_POSIX y
          CIFS_ACL y
          CIFS_DEBUG y
          CIFS_DFS_UPCALL y
          CIFS_SMB2 y
          CIFS_SMB311 y
          CIFS_FSCACHE y
        '';
      };
    };
  };
```

But on NixOS unstable (git master) that config is not applied. Both master and stable use the linux 4.4 kernel, so I think I'm modifying the right attribute. But somethings wrong. What? Where?

(Btw, is there a way to customize the _current_ kernel? I don't like that I'm using version specific attribute above.)
### Steps to reproduce

Build NixOS on release-16.03 and master with customized kernel config. Notice that the customization isn't applied on master.
## Technical details
- System: NixOS
- Nix version: 1.11.2
- Nixpkgs version: 6bfe45935541c20032bcaab910dc1a69087adfbf (master branch today)

**Comment by bjornfor** [comment]
Test for current config: ```zgrep CIFS /proc/config.gz```

**Comment by joachifm** [comment]
Are you using the top-level `linux` directly or via `linuxPackages`? In the latter case, my experience has been that only overriding the top-level `linux` is insufficient, you need to construct a new `linuxPackages` as well.

**Comment by joachifm** [comment]
What I meant is that I've had to do something like `boot.kernelPackages = let self = linuxPackagesFor myKernel self; in self`, otherwise the override fails to propagate.

**Comment by vcunat** [comment]
I think this should be another instance of https://github.com/NixOS/nixpkgs/issues/18316

**Comment by bjornfor** [comment]
Should be fixed with https://github.com/NixOS/nixpkgs/commit/5c6bcee944a3c03b0c0274a9e91e0c61b6bd5b33 (I'll re-open if not).

**Comment by bjornfor** [comment]
Keeping open until https://github.com/NixOS/nixpkgs/commit/5c6bcee944a3c03b0c0274a9e91e0c61b6bd5b33 is backported to release-16.09.

**Comment by bjornfor** [comment]
Note to self: an easier way to get the kernel config (no need to reboot):

```
$ nix-build nixos -A config.system.build.kernel && ~/forks/linux/scripts/extract-ikconfig ./result/bzImage
/nix/store/xqj3gvvxdc3zr5cqrngpixd821i5rf0g-linux-4.4.19
#
# Automatically generated file; DO NOT EDIT.
# Linux/x86_64 4.4.19 Kernel Configuration
#
CONFIG_64BIT=y
CONFIG_X86_64=y
CONFIG_X86=y
[...]
```

**Comment by dezgeg** [comment]
A faster way to do that (doesn't need building the kernel):
````cat $(nix-build nixos -A config.system.build.kernel.configfile)````

**Comment by fooblahblah** [comment]
Any updates here?

**Comment by bjornfor** [comment]
I haven't tested it since my last comment here, but since that comment is only about backporting to NixOS 16.09, which is EOL now, I think it's safe to close.
