### ISSUE TITLE
Enable Intel Vulkan driver for mesa 12.0.1

### ISSUE THREAD

**Issue by lummax** [NixOS/nixpkgs#17993]
With the update to mesa 12.0.1 in #17495 it would now be possible to enable the intel vulkan driver with the `--with-vulkan-drivers=intel` configure flag. It might be good to do this before the mesa update transitions from `staging` to `master`.

(I tried it and failed as a nix noob. :/)

**Comment by domenkozar** [comment]
cc @vcunat

**Comment by vcunat** [comment]
@lummax: can you/someone test running the driver? 26ae67fad5 I'll use a Skylake tomorrow, but I may not have enough time.

**Comment by vcunat** [comment]
I read you need DRI3 enabled for it, too. /cc @expipiplus1 may be interested in vulkan stuff.

**Comment by lummax** [comment]
@vcunat Thats where the noob comes in. I dont know, how to test this without rebuilding my system on `staging`/your commit. Or is that the way? Any help is appreciated :)

To test the driver I created this [`shell.nix`](https://gist.github.com/lummax/f64f24c738c1c2369d4126d3b250cc0d) based on https://github.com/NixOS/nixpkgs/pull/14404. `vulkaninfo` should be available with that.

**Comment by vcunat** [comment]
@lummax, you only need to rebuild the mesa drivers, I think:
1. get into a git checkout with my commit
2. ``$ nix-build -Q -A mesa_drivers``
3. ``$ ls -l ./result-drivers/lib/libvulkan* # to verify you got it right``
3. ``$ sudo mv /run/opengl-drivers{,-original} && sudo ln -s "$(readlink ./result-drivers)" /run/opengl-drivers``

**Comment by lummax** [comment]
It builds, thats good :)

But as `/run` resides on a read-only partition I used `LD_LIBRARY_PATH`.

- 1 `git checkout <your commit>`
- 2 `nix-build -Q -A mesa_drivers`
- 3 `cp ~/dev/mesa/src/intel/vulkan/intel_icd.json ~/.local/share/vulkan/icd.d`
- 4 load vulkan as per my [`shell.nix`](https://gist.github.com/lummax/f64f24c738c1c2369d4126d3b250cc0d)
- 5 `LD_LIBRARY_PATH=~/dev/nixpkgs/result-drivers/lib vulkaninfo`

This gives a lot of [output](https://gist.github.com/lummax/4819b7a691b4f2d799f0047c9a741cae). It works :)

The missing step would be to include `intel_icd.json` into the right directory. I chose `~/.local/share` as it was easy, but the loader searches a lot of [places](https://gist.github.com/lummax/6382acbd4b334c2d2c1b8713464dce5a) (part of `strace` output). `/etc/vulkan/icd.d` or `/usr/share/vulkan/icd.d` seem the right choice.

**Comment by lummax** [comment]
Now that `mesa` got into `master` I tried some more. But I still failed. All thats left would be [this patch](https://gist.github.com/lummax/50462b3094e8c6e25c536d658bf8fb7c) on top of your https://github.com/NixOS/nixpkgs/commit/26ae67fad54c0bf1f4ef1f03d7f71dc1fbac6014 @vcunat . Building it and linking the files by hand lets me run `vulkaninfo`.

Setting the git repo as a root in `nix-shell` wont apply the changes, and even rebuilding the system based on on my branch wont work. I suspect the configuration in `nixos/modules/hardware/opengl.nix` to be the culprit (Interestingly this `opengl.nix` would now control the creation of the vulkan driver :) ).

**Comment by lummax** [comment]
I had indeed an error about missing DRI3 support. As proposed in the [arch wiki](https://wiki.archlinux.org/index.php/Vulkan#Error_-_vulkan:_No_DRI3_support) I added some xserver configuration. This could maybe be done automatically, but this is again the point where my knowledge of nix comes to an end. :)

``
services.xserver.deviceSection = '' Option      "DRI"    "3" '';
``

**Comment by Ralith** [comment]
@lummax: Can you see if #18717 removes the need for the X config tweak? I'm having trouble getting your nix-shell environment to build; `install-headers.patch` doesn't want to apply.

**Comment by Ralith** [comment]
In the hopes of moving things along, I've opened PR #19918 with these changes.

**Comment by vcunat** [comment]
The support is staged and eventually will appear in the unstable channel.
