### ISSUE TITLE
Support AMD Radeon RX 480 Polaris

### ISSUE THREAD

**Issue by gebner** [NixOS/nixpkgs#17991]
As [reported elsewhere](https://www.phoronix.com/scan.php?page=news_item&px=AMD-Open-Sourced-Polaris), this recently released graphics card already has upstream driver support in Mesa, LLVM, and the kernel. I'm collecting the required changes and upgrades that are required to add support in NixOS here.

 - [x] Linux >= 4.7
 - [x] Mesa >= 12: this is already in staging, see #17957
 - [x] LLVM >= 3.9, see #18007 
 - [x] Switch Mesa to LLVM 3.9
 - [x] Set `DRM_AMD_POWERPLAY=y` in kernel config, see #18005
 - [x] ~~Figure out why plymouth fails in staging.~~ No idea what happened, I did not even have plymouth enabled.

Then it should work with the following configuration:
```nix
{ boot.kernelPackages = pkgs.linuxPackages_4_7;
  services.xserver.videoDrivers = [ "amdgpu" ]; }
```
(The radeon kernel module does not need to blacklisted as we have a nixos module that adds it the blacklist when amdgpu is used as an xorg driver.)

**Comment by abbradar** [comment]
Not sure if related: https://github.com/NixOS/nixpkgs/issues/17682, `DRM_AMDGPU_CIK` is also needed for some new cards.

**Comment by gebner** [comment]
`DRM_AMDGPU_CIK` is only for the cards before polaris, IIRC.  I'm not sure whether to enable it by default.  Debian for example only enables `DRM_AMD_POWERPLAY`, but not `DRM_AMDGPU_CIK`.

**Comment by vcunat** [comment]
LLVM 3.9 seems planned to be released within days; switching mesa might be easy, if it "just works", even in time for 16.09.

Why should one put `"modesetting"` among the drivers? Just for a fallback if it goes wrong?

**Comment by gebner** [comment]
> LLVM 3.9 seems planned to be released within days; switching mesa might be easy, if it "just works", even in time for 16.09.

Yes, its planned for [next week](http://lists.llvm.org/pipermail/llvm-dev/2016-August/104077.html) now.  Right now I'm trying to build lldb.  I just hope we don't into problems as we had with LLVM 3.7 (#11467).

> Why should one put "modesetting" among the drivers? Just for a fallback if it goes wrong?

Thanks for the pointer! I was using the config suggested in #17682, and was happy that it worked at all.  Apparently neither modesetting nor the extra firmware are necessary.

**Comment by vcunat** [comment]
Mesa builds fine against your updated.

**Comment by vcunat** [comment]
We still have a month to stabilize 16.09, so having all in seems realistic.

**Comment by gebner** [comment]
> Mesa builds fine against your updated llvm.

Yes, in fact I'm using the Polaris driver right now.

> We still have a month to stabilize 16.09, so having all in there seems realistic.

I agree, the only big missing piece is LLVM 3.9 and that should come next week.  That would leave enough time for everyone to test the mesa built against the new llvm version.

**Comment by vcunat** [comment]
Great!

**Comment by gebner** [comment]
All the changes are now in staging.

**Comment by jgeerds** [comment]
@gebner So `16.09` will support the new driver? I should order one of these :smiley:

**Comment by vcunat** [comment]
AFAIK there's only e1eea15a missing, but I plan to push that.

**Comment by vcunat** [comment]
All done, I believe.
