### ISSUE TITLE
packaging request: readarr

### ISSUE THREAD

**Issue by UncoveredBulb** [NixOS/nixpkgs#179941]
**Readarr**
_Readarr is a ebook collection manager for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new books from your favorite authors and will interface with clients and indexers to grab, sort, and rename them._

**Metadata**

* homepage URL: https://readarr.com/
* source URL: https://github.com/Readarr/Readarr
* license: GNU GPL v3
* platforms: Windows, Linux, macOS, Raspberry Pi, etc.

**Comment by jocelynthode** [comment]
@purcell @edwtjo As you bundled some of the *arr software earlier, I'd be interested in trying out to package readarr, however I have 0 experience with these kind of package and the dotnet environment. Would one of you be willing to help me?

**Comment by purcell** [comment]
@jocelynthode Pretty much the same tbh, I'd honestly just start with a copy of one of the existing snippets and change the appropriate parts.
