### ISSUE TITLE
Packaging Request: Game Conqueror (or GameConqueror) frontend for scanmem which is already in nixpkgs

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#179974]
**Project description**
Game Conqueror is a graphical game cheating tool under Linux, a frontend for scanmem.

**Metadata**

* homepage URL: https://github.com/scanmem/scanmem
* source URL: https://github.com/scanmem/scanmem
* license: GPLv3, LGPLv3 for libscanmem
* platforms: Linux

**Comment by Ashe** [comment]
Why was this marked as completed? Is it in nixpkgs?
