### ISSUE TITLE
Can’t login as user with LightDM

### ISSUE THREAD

**Issue by nerdbude** [NixOS/nixpkgs#180016]
### I can’t login as user 

I start my laptop running NixOS 22.05 with LightDM and XMonad. When I want to login as normal user LightDM won’t let me login

### Steps To Reproduce
1. Boot 
2. login as root 
3. $> lightdm 
4. login as user 
5. enter password 
6. screen turn black 
7. login prompt appear again 

It works fine with root but not with the user. 

Output from journalctl:

![E71A62AA-6621-417F-8EC8-202FB79E2EB2](https://user-images.githubusercontent.com/55981615/177044628-27773670-a7e5-4e06-b718-417a955ad059.jpeg)

**Comment by 06kellyjac** [comment]
if you remove lightdm does xmonad successfully start just using startx with your xinit setup? Looks to me like your xmonad setup is broken.
Have you ran xmonad before? I've seen several people want to instantly swap to xmonad while also new to nixos and having too many new issues at the same time.

Also without any configuration it's very difficult to help

**Comment by nerdbude** [comment]
No I can't use startx. startx brings also errors but it never worked since beginning. 
I use XMonad since two years now without any problems until now. 
Here is my configurations.nix: 

```
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Set your time zone.
  time.timeZone = "Europe/Berlin";

  # Automatic remove old unused packages
  nix.gc = {
	automatic = true;
	dates = "daily";
	options = "--delete-older-than 30d";
  }; 

  # Limit Bootoptions to 5
  boot.loader.systemd-boot.configurationLimit = 5; 

  # Deduplicate nix-store filebase
  nix.optimise.automatic = true;

  networking.useDHCP = false;
  networking.interfaces.enp0s31f6.useDHCP = true;
  networking.interfaces.wlp4s0.useDHCP = true;
  networking.wireless.userControlled.enable = true;
  # Configure keymap in X11
  services.xserver.enable = true;
  services.xserver.layout = "de";
  services.xserver.xkbOptions = "eurosign:e";
  services.xserver.windowManager.xmonad.enable = true;
  services.xserver.windowManager.xmonad.enableContribAndExtras = true;
  services.xserver.autorun = false;
  
  programs.zsh.enable = true;
  # Enable sound.
  # sound.enable = true;
  # hardware.pulseaudio.enable = true;

  # Enable touchpad support (enabled default in most desktopManager).
  services.xserver.libinput.enable = true;
  
  # Sound
  services.jack = {
	jackd.enable = true;
	alsa.enable = false;
	loopback = {
		enable = true;
	};
  };

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.pho = {
     isNormalUser = true;
     extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
     shell = pkgs.zsh;
   };

  # FONTS
  fonts.fonts = with pkgs; [
	ibm-plex
	google-fonts
	noto-fonts
  ];
  
  # AUTOUPGRADE NIXOS
  system.autoUpgrade.enable = false;
  system.autoUpgrade.allowReboot = false;


  # List packages installed in system profile. To search, run:
  # $ nix search wget
  # environment.systemPackages = with pkgs; [
  #   wget vim
  #   firefox
  # ];
  system.stateVersion = "20.09"; # Did you read the comment?

}
```
Thanks for your help :)

**Comment by 06kellyjac** [comment]
hmm yeah I'm not sure then. It's quite hard to track xmonad's history since it's part of the mega haskel packages file.

Are you able to move your xmonad config and try a config that's default/minimal :shrug:

**Comment by 06kellyjac** [comment]
@nerdbude 
Out of interest did you resolve your problem? Stop using xmonad/lightdm? Or are just looking to clean up stale issues?
:slightly_smiling_face:

**Comment by nerdbude** [comment]
No not really. I just reinstall the whole OS. Thought I destroyed some essential files within ~/ 

I just saw today that I never responded to this. Sorry for that

**Comment by 06kellyjac** [comment]
No problem at all. Shame about those files but I'm glad things are working.
