### ISSUE TITLE
exa: Fix impure Cargo dependency

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#18002]
## Issue description

`exa` has an impure cargo dependency (git repository without any ref/hash attached in `Cargo.toml`)
### Steps to reproduce

`nix-build '<nixpkgs>' -A exa`

**Comment by gebner** [comment]
Exa is now marked as broken since #20460.

**Comment by the-kenny** [comment]
That's somewhat acceptable as a fix :) Thanks for the heads-up
