### ISSUE TITLE
nixos.modules.config.qt5: provide the possibility of using QT_QPA_PLATFORMTHEME="kde"

### ISSUE THREAD

**Issue by PedroHLC** [NixOS/nixpkgs#180131]
The reason why I didn't open a PR, is described in [Additional context](#Additional_context).

### Describe the bug
I'm aware of four platforms for Qt's themes right now:
- Using GTK themes through `qtstyleplugins` + `QT_STYLE_OVERRIDE`;
- Using GNOME themes through `qgnomeplatform` + `QT_STYLE_OVERRIDE`;
- Using Qt themes, with the non-KDE solution `qt5ct`, ***which uses [its own color schemes](https://sourceforge.net/p/qt5ct/code/HEAD/tree/trunk/qt5ct/colors)***;
- Using Plasma-targeted Qt themes, with `kde` as `QT_QPA_PLATFORMTHEME`, as done natively in a plasma session, ***using the theme's colorscheme***.

### Steps To Reproduce
1. Check [`qt5.platformTheme`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/config/qt5.nix) and it does not provide `kde`;
2. No equivalent to [`programs.qt5ct.enable`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/programs/qt5ct.nix) providing `kde`;
3. Enable `services.xserver.desktopManager.plasma5.enable = true;`, then add some Pasma-target themes like `[breeze-gtk breeze-icons breeze-qt5]`, then adjust envvars `export QT_QPA_PLATFORMTHEME='kde' QT_PLATFORM_PLUGIN='kde' QT_PLATFORMTHEME='kde'`, set the theme in `~/.config/kdeglobals` or with `QT_STYLE_OVERRIDE`, you'll get the right theme with the proper color scheme.

### Expected behavior
`qt5.platformTheme` should provide `kde` (or `plasma`) as an option, it should add only the required packages to the system, and set the proper envvars. (or maybe rename it, since qt6 also uses the same variables and envvars)

### Screenshots
- qbittorrent + breeze + `QT_QPA_PLATFORMTHEME=kde` + dark:
![screenshot](https://user-images.githubusercontent.com/1368952/177183185-83272d96-65e6-409a-aa88-1ea5d77e9f42.png)

- qbittorrent + breeze + `QT_QPA_PLATFORMTHEME=qt5ct` + dark:
![screenshot](https://user-images.githubusercontent.com/1368952/177183831-a8ad325a-cf6f-498a-8926-85d77656ddb7.png)

- qbittorrent + `QT_QPA_PLATFORMTHEME=gtk2` (ignored my theme):
![screenshot](https://user-images.githubusercontent.com/1368952/177184354-f4b85ade-7c88-4a04-ac44-2383054bbf93.png)

- qbittorrent + `QT_QPA_PLATFORMTHEME=gnome` (also ignored my theme):
![screenshot](https://user-images.githubusercontent.com/1368952/177184692-8b6e6191-c4e7-483d-9d28-c599d6f37b25.png)

### Additional context
I tried to discover what package that is being added when evaluating `services.xserver.desktopManager.plasma5` provides this platform-theme, but I failed miserably.

### Notify maintainers
- stated as maintainers of plasma-integration: @ttuegel @nyanloutre
- stated as maintainer of qt5ct: @Ralith
- qt5 module contributors: @worldofpeace
- cc @thiagokokada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
╭─pedrohlc at desktop in /home/pedrohlc
╰─λ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.51, NixOS, 22.11 (Raccoon), 22.11.20220702.660ac43`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by thiagokokada** [comment]
Not exactly your bug, but we should remove `programs.qt5ct` and integrate it with `qt5` configs instead.

**Comment by romildo** [comment]
> Not exactly your bug, but we should remove `programs.qt5ct` and integrate it with `qt5` configs instead.

`lxqt` is another QT platform theme that can be integrated into `qt5` config.
