### ISSUE TITLE
google-cloud-cpp is our of date

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#180138]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: google-cloud-cpp
current version: 1.38.0
desired version: 1.42.0

###### Notify maintainers
maintainers: @cpcloud

@tobim who did the last update

###### Note for maintainers

Please tag this issue in your PR.

**Comment by tobim** [comment]
I don't have time to work on this at the moment.
