### ISSUE TITLE
Atom no longer works after upgrading to 22.05

### ISSUE THREAD

**Issue by adamlwgriffiths** [NixOS/nixpkgs#180204]
### Describe the bug
Atom editor fails to run in Gnome 42 on NixOS 22.05, with Nvidia drivers and X11.

When run from console I get the following output:

```console
/nix/store/4vbf2kvqx2ll0qfkp4h8b31fbz98w4ag-atom-1.58.0/bin/.atom-wrapped: line 190:  2753 Illegal instruction     (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[2753:0705/162616.049798:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id:
```

Running with `atom --disable-gpu-sandbox` resolves the issue and Atom finally starts up.

This seems to be an issue in electron / atom's version of electron.

Potentially related discussion:

https://github.com/atom/atom/issues/23167
https://github.com/iotaledger/firefly/issues/1628
https://github.com/atom/atom/issues/23608

### Steps To Reproduce
1. run Atom

### Additional context
NixOS 22.05
Gnome 42
Nvidia 1080

### Notify maintainers
@offlinehacker @ysndr

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.05 (Quokka), 22.05.1377.09c32b0bda4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05.1377.09c32b0bda4, home-manager-21.11"`
 - channels(adam): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by davidak** [comment]
I can't reproduce the issue on NixOS 22.11.3408.a575c243c23 with AMD GPU and X11.

Do you still have the issue? Maybe it's Nvidia specific?

Maybe one of the 2 community forks fixes it.

**Comment by adamlwgriffiths** [comment]
Issue still persists with the almost the same error.
```
$ /nix/store/lzzslgkqg31pfj38alq186xk4zsqrxm6-atom-1.60.0/bin/.atom-wrapped: line 195:  3802 Illegal instruction     (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[3802:0411/181315.429182:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```

I suspect this is a low-value issue as Atom has been end-of-life'ed by Microsoft.

**Comment by FliegendeWurst** [comment]
Atom was removed in #258440.
