### ISSUE TITLE
Electron 19

### ISSUE THREAD

**Issue by sumnerevans** [NixOS/nixpkgs#180260]
Element v1.11.0 updated to Electron 19, so we need this packaged in Nixpkgs: https://github.com/vector-im/element-desktop/releases/tag/v1.11.0

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `electron`

current version: 18.1.0
desired version: 19.0.7

https://github.com/electron/electron/releases/tag/v19.0.7

###### Notify maintainers

maintainers: @travisbhartwell @manveru @prusnak

###### Note for maintainers

Please tag this issue in your PR.

**Comment by prusnak** [comment]
PR that brings electron_19 but does not provide electron_19 headers: https://github.com/NixOS/nixpkgs/pull/180269

**Comment by hqurve** [comment]
I believe that [this blog post](https://www.electronjs.org/blog/s3-bucket-change) states that they migrated storage. So, I think the new url would be https://artifacts.electronjs.org/headers/dist/v19.0.7/node-v19.0.7-headers.tar.gz

**Comment by prusnak** [comment]
> I believe that [this blog post](https://www.electronjs.org/blog/s3-bucket-change) states that they migrated storage. So, I think the new url would be https://artifacts.electronjs.org/headers/dist/v19.0.7/node-v19.0.7-headers.tar.gz

Great find, thanks! Updated PR https://github.com/NixOS/nixpkgs/pull/180269 to include this change and electron_19 now provides the headers.
