### ISSUE TITLE
lightburn: 1.1.03 -> 1.2.00

### ISSUE THREAD

**Issue by seghers** [NixOS/nixpkgs#180278]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: lightburn

current version: 1.1.03
desired version: 1.2.00

###### Notify maintainers

maintainers:
@q3k 
###### Note for maintainers

Please tag this issue in your PR.

https://github.com/LightBurnSoftware/deployment/releases

**Comment by seghers** [comment]
https://lightburnsoftware.com/blogs/news/lightburn-1-2-00-galvo-fiber-support-and-a-bunch-more

**Comment by seghers** [comment]
Dear @ryantm @r-ryantm

Your bot used to update this package. Did anything change?

https://github.com/NixOS/nixpkgs/pull/163840
https://github.com/NixOS/nixpkgs/pull/163125

**Comment by seghers** [comment]
https://github.com/NixOS/nixpkgs/pull/183512

**Comment by ryantm** [comment]
@seghers I fixed some problems recently. Glad it's working again!
