### ISSUE TITLE
DisplayLink support

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18023]
DisplayLink, as far as I can tell, seems to be unfortunately emerging as the only choice for connecting external monitors to laptops without display ports (for example, via the [Dell adapter](http://accessories.us.dell.com/sna/productdetail.aspx?c=us&cs=19&l=en&sku=470-ABHH)). It would be great if NixOS could support it.

I have no idea what is involved in this. There is an Ubuntu driver. DisplayLink the company claims that it should be possible to port ([Porting the DisplayLink Ubuntu driver to other Linux distributions](http://support.displaylink.com/knowledgebase/articles/679060)). The [Arch wiki](https://wiki.archlinux.org/index.php/DisplayLink) says it's difficult to get working.

**Comment by abbradar** [comment]
Do you have hardware for testing this? The driver itself seems fairly straightforward and I could help packaging it.

**Comment by chris-martin** [comment]
I do - I have the Dell adapter linked above.
