### ISSUE TITLE
Xorg logs are lost with SDDM

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixpkgs#18034]
## Issue description

Using SDDM (`services.xserver.displayManager.sddm.enable=true`) with the latest nixpkgs apparently results in X server logs going to nowhere. They do not show up in the journal of `display-manager.service` (`journalctl -u display-manager.service`). Only specific messages from SDDM show up there.

This is a regression caused by https://github.com/NixOS/nixpkgs/commit/d84741a4bfb6ed2531ec7154479c147d2c9a737c.

**Comment by jokogr** [comment]
This is upstream-related, sddm still does not support this. I'd say to wait a bit for https://github.com/sddm/sddm/issues/539

If it is an issue for you, just re-enable `/var/log/Xorg.log` by overriding the `logfile` flag in `services.xserver.displayManager.xserverArgs`

**Comment by aske** [comment]
See #19235.

**Comment by aske** [comment]
@Mic92 Why close it now?  I think #18716 was duplicate of this issue, or have you found some other issue like this?

**Comment by aske** [comment]
Nevermind, #19235 is merged now.
