### ISSUE TITLE
Hyprland v0.22.0beta

### ISSUE THREAD

**Issue by godalming123** [NixOS/nixpkgs#180323]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: hyprland (only in unstable repos)

current version:0.6.1
desired version:0.22.0 beta

###### Notify maintainers

maintainers: vexerski

###### Note for maintainers

Please tag this issue in your PR.

**Comment by godalming123** [comment]
There is a pr for hyprland v0.6.3

**Comment by peterhoeg** [comment]
This issue will be closed automatically when the referenced PR is merged.

**Comment by godalming123** [comment]
Ok good to know

**Comment by pinkcreeper100** [comment]
Hyprland is now at 0.16.0beta

**Comment by mindmeshlink** [comment]
Now at 0.22.0beta. The reccommendation on the [wiki](https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/) is to use the Flake instead of nixpkgs, with how out of date we are.

**Comment by peterhoeg** [comment]
We just need someone using hyprland to do up a PR and test it out - there really is nothing preventing us from bumping it.

**Comment by wineee** [comment]
https://github.com/NixOS/nixpkgs/pull/221617
