### ISSUE TITLE
big \ many fonts stall the display manager (lightdm) and prevent login

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#18035]
## Issue description

big \ many fonts (nerdfont, for instance) cause lightdm to halt \ delay for a prolonged time leaving the user watching a black screen while the font cache is being rebuild.

A workaround is to set ```nix.useSandbox = true;```, and add/remove a font to force a rebuild. Following a reboot, the system should boot properly.

(the issue seemed to have surfaced\resurfaced post audit 2.4.4 -> 2.6.6 but there's no clear consensus on this. oddly, setting audit=0 fails to help while reverting to the older audit did help...)

### Steps to reproduce

minimal configuration.nix for build-vm: https://gist.github.com/RamKromberg/a12c04bd24ba91e1faf4f7b1dd7b5faf

**Comment by joachifm** [comment]
The configuration.nix linked above is far from minimal ... A minimal config would be something like
```
{ pkgs, ... }:
{
  services.xserver.enable = true;
  fonts.fonts = [ pkgs.nerdfonts ];
  # Strictly unecessary, lets us test login if we get that far:
  users.mutableUsers = false;
  users.users.foo = { isNormalUser = true; password = "foo"; };
}
```

To assess interaction audit, build one config with `boot.kernelParams = [ "audit=0" ]` and one without.

**Comment by RamKromberg** [comment]
the issue disappeared without a good explanation. disk fragmentation causing a prolonged disk search was proposed... a bit flipping after the build was complete (disk error) was also mentioned.
Regardless, I'm no longer able to reproduce the issue on either metal no vm so I'm closing it down.

**Comment by RamKromberg** [comment]
the issue reappeared... a workaround and a theory explaining the problem were proposed... I'll keep the issue open until something lands in unstable \ unstable small for me to check since people might need the workaround if they stumble on the same issue.

**Comment by the-kenny** [comment]
@RamKromberg did you re-open this issue intentionally?

**Comment by RamKromberg** [comment]
@the-kenny Yeah. It was gone one minute and back the next. There was some irc discussions regarding how the font cache is built and some package changes... But I didn't follow up on the technical details and I haven't tested the proposed solution (as opposed to the _nix.useSandbox = true;_ workaround) or heard if it ever ended up in master so I can't close this just yet.

Since it happened in the unstable-small channel, very few people would have noticed it when it happened. So, in case this leaks to other channels, I'm keeping this open so if someone runs into this they'll know about the workaround at least.

**Comment by RamKromberg** [comment]
I'm closing this since I've cut back to using just a handful of font packages and can't be bothered downloading and compiling the 3+ gb of fonts necessary to test the problem.
