### ISSUE TITLE
dockerized Haskell app crashes: getProtocolByName: does not exist (no such protocol name: udp)

### ISSUE THREAD

**Issue by rlupton20** [NixOS/nixpkgs#18038]
I tried the basic example of a distributed program using Cloud Haskell (distributed-process), and tried to test it using nix to cook a docker image and then use multiple containers to simulate a network of machines.

However, when I try to run the app inside a docker container (using docker-compose) I get errors in each of the containers, e.g.:

```
node_1 | node-exe: getProtocolByName: does not exist (no such protocol name: udp)
```

The executable runs fine outside of a container. I'm assuming the nix container is lacking some functionality here.

`image.nix` file describing the container image:

```
{ pkgs ? import <nixpkgs> {} , node }:

with pkgs;
dockerTools.buildImage {
  name = "node-container";
  # Don't use another image a base, just build
  # what is necessary to run
  runAsRoot = ''
    #!${stdenv.shell}
    ${dockerTools.shadowSetup}
    mkdir /data
  '';
  contents = [ node ];

  config = {
    Cmd = [ "node-exe" "slave" "0.0.0.0" "5000" ];
    WorkingDir = "/data";
    };
}
```

Haskell code:

```
module Main where

import System.Environment (getArgs)
import Control.Distributed.Process
import Control.Distributed.Process.Node (initRemoteTable)
import Control.Distributed.Process.Backend.SimpleLocalnet

import System.IO (hPutStrLn, stderr)

master :: Backend -> [NodeId] -> Process ()
master backend slaves = do
  -- log list of slaves to stderr
  liftIO . hPutStrLn stderr  $ "MASTER :: Found slaves: " ++ show slaves
  -- Terminate all the slaves
  terminateAllSlaves backend


main :: IO ()
main = do
  args <- getArgs

  case args of
    ["master", host, port] -> do
      backend <- initializeBackend host port initRemoteTable
      startMaster backend (master backend)
    ["slave", host, port] -> do
      backend <- initializeBackend host port initRemoteTable
      startSlave backend
```

As a separate and related issue, there doesn't seem to be any documentation of dockerTools.
## Technical details
- System: nixos 16.03
- Nix version: 1.11.2
- Nixpkgs version: "16.03.1242.c5cbda2"

**Comment by puffnfresh** [comment]
Your base image is empty. You have no /etc/hosts or /etc/nsswitch.conf which are probably required for that code.

I recommend using an Alpine base image with nsswitch, like so:

https://github.com/purefn/hiplambda/blob/master/deploy/docker.nix

**Comment by puffnfresh** [comment]
Judging by the error message, it might be /etc/services that you're missing.

**Comment by rlupton20** [comment]
Or possibly even `/etc/protocols`. Is there any way to add some reasonable defaults for the standard image?

I'll play around with the alternatives (I have been anyway), but surely the basic nix image should be fixed/improved/documented?

**Comment by puffnfresh** [comment]
@rlupton20 there is no standard base image.

I have some code somewhere to put a NixOS configuration into an image, which sounds closer to what you want. I'll publish that in a few hours and link it here.

**Comment by puffnfresh** [comment]
This will build a Docker image from a NixOS configuration:

https://github.com/puffnfresh/nix-files/blob/master/nixos-docker/default.nix

It should be more extensible, but it's currently working for what I need it to do. We should probably try and get this in nixpkgs, too.

**Comment by rlupton20** [comment]
@puffnfresh Ace, thanks, I'll give that a go. Yeah, I meant the image generated by the most basic configuration (generated images and configuration files are, in principle, in bijection anyway right? :wink: ). That probably being an ill defined concept...

Are there any docs for this kicking about already? If not I might start an entry on the wiki and start figuring out how these things work a little better (assuming time etc.). I'm aware of the nix pills article as a starting point.

**Comment by rlupton20** [comment]
@puffnfresh Took a bit of hacking around and reading of source, but I've got something working now (well, I still need to figure out why my nodes don't find each other, but they're not crashing now so that's a start :smile:). For others who may come across this, on my system I needed to use `symlinkJoin` with the following incantation:
```
symlinkJoin "node-contents" [ node system.build.etc system.path ];
```
(i.e. without referring to attributes --- though nix is fairly new to me so maybe I'm missing something here). It looks like this has changed in "recent" `nixpkgs`.

In my opinion, it looks like nix was behaving sensibly, but the problem was one of documentation. I'd be happy to take this on, and maybe write a wiki entry outlining a basic example for a nix derived docker image with a "complete basic nixos system" (which I assume is what your example provides). I'd guess that's really nothing more than a stripped down version of your work with a little explanation. Its super cool that nix can do this, so if the API isn't prone to heavy change it'd be worth having it written down somewhere properly (otherwise it might be worth holding off for a bit).

**Comment by rlupton20** [comment]
For future searchers, this was what I ended up with:
```
{ pkgs ? import <nixpkgs> {} , node }:
let
  minimalDocker = {
    imports = [ <nixpkgs/nixos/modules/profiles/minimal.nix> ];
    boot.isContainer = true;
    environment.etc.machine-id.text = "node";
  };

  eval = import <nixos/lib/eval-config.nix> {
    modules = [
      minimalDocker
    ];
  };

  system = eval.config.system;
   
in

with pkgs;
dockerTools.buildImage {
  name = "node-container";

  contents = 
    symlinkJoin "node-contents" [ node system.build.etc system.path ];
  
  config = {
    Cmd = [ "node-exe" "slave" "0.0.0.0" "5000" ];
    };
}
```

**Comment by puffnfresh** [comment]
@rlupton20 the API is meant to be unstable. It hasn't been changed significantly for a while, though.

You should be able to change your expression to only using a NixOS configuration:

```nix
myConfig =
  systemConfig = {
    environment.systemPackages = [ node ];
  };

eval = import <nixos/lib/eval-config.nix> {
  modules = [
    minimalDocker
    myConfig
  ];
};
```

**Comment by rlupton20** [comment]
@puffnfresh better still! Thanks!

Good to know about the API. I'll add a little note if i get around to writing anything.

**Comment by gleber** [comment]
Is there anything left here to do? Is the only thing to add an example of a minimal NixOS image building with nix? Maybe let's close this issue and open a new more targeted one?
