### ISSUE TITLE
texlive: mktexlsr not available on PATH

### ISSUE THREAD

**Issue by dnadlinger** [NixOS/nixpkgs#180475]
### Describe the bug

The mktexlsr.pl script is usually installed onto the PATH as `mktexlsr`, but is only available directly from the Nix store (e.g. `/nix/store/y4qnj1mhr7gm26bcxpk3lb4875wyf83y-texlive-texlive-scripts-58791/scripts/texlive/mktexlsr.pl`).

### Steps To Reproduce

1. Install texlive-combined, e.g. /nix/store/my6nskw81axgw8n4kap21qckbsryqwxz-texlive-combined-full-2021.20210408.
2. Try to run `mktexlsr`, which is not available. Note that `man mktexlsr` does display a man page for the suffix-less `mktexlsr` as expected.

### Expected behavior

As this is important to managing a user texmf root – not managed by Nix, e.g. in `$HOME`, or a project-specific directory –, the script should probably be available, as it usually is part of a texlive install (and the man page in fact still is).

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.5.0, macOS 12.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(dpn): `""`
 - channels(root): `"nixpkgs-22.05pre338661.3c52ea8c921"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by ben-ben-ben** [comment]
By the way, this issue also exists in texlive.combined.scheme-small
