### ISSUE TITLE
Define platform support tiers (RFC 36)

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixpkgs#180492]
> [RFC 36](https://github.com/NixOS/rfcs/blob/master/rfcs/0046-platform-support-tiers.md)
> The definition of support tiers and a list of platforms with the corresponding support tiers is added as an appendix to the Nixpkgs manual. The list of platforms is further maintained as a part of the Nixpkgs manual. The platform list in the manual will be initially based on the list in the appendix of the present RFC.

**Comment by FliegendeWurst** [comment]
Started in #254741
