### ISSUE TITLE
Suggestion: Force package names to include the version number

### ISSUE THREAD

**Issue by rishflab** [NixOS/nixpkgs#180421]
DISCLAIMER: I am nix noob so this issue may be born from a fundamental misunderstanding of Nix.

## Issue description

Nix package names do not include version numbers. This does not reflect reality.

For example; here is the [go-ethereum package.](https://search.nixos.org/packages?channel=22.05&show=go-ethereum&from=0&size=50&sort=relevance&type=packages&query=go-ethereum)

It is actually `go-ethereum-1.10.18`. 

It was updated 22 days ago from 1.10.17 -> 1.10.18
https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/applications/blockchains/go-ethereum/default.nix#L57

How would i lock to `1.10.17` in my `shell.nix`?

```
{ pkgs ? import <nixpkgs> { } }:
with pkgs;
mkShell {
  buildInputs = [
    pkgconfig
    go-ethereum
    go_1_18
  ];
}

```

## Potential Solution

Force packages to include the version number. 

Some packages already do this to some degree:
https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=python

**Comment by peterhoeg** [comment]
We typically only carry a single version of libraries so once updated from 1.10.17 to 1.10.18, your only way to get the older version is to override the derivation and set the src to point to the previous version.

Alternatively, you can pin nixpkgs to a commit from before the upgrade.

nixpkgs isn't a collection of multiple versions of multiple libraries you can mix and match - it's more like a point in time snapshot (similar to xBSD).
