### ISSUE TITLE
Failing Darwin packages

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#18067]
## High-priority packages

These are some broken Darwin packages that are used at least somewhere as build inputs. They probably should be high priority.
- [x] [rustc](http://hydra.nixos.org/job/nixpkgs/trunk/rustc.x86_64-darwin)
- [x] [wxwidgets](http://hydra.nixos.org/job/nixpkgs/trunk/wxGTK.x86_64-darwin): see #16192 #21048
- [ ] [transfig](http://hydra.nixos.org/job/nixpkgs/trunk/transfig.x86_64-darwin): tries to use `xcode-select`
- [x] [rcs](http://hydra.nixos.org/build/39392037): see #18063
- [x] [fontforge](http://hydra.nixos.org/job/nixpkgs/trunk/fontforge.x86_64-darwin): see #18063
- [ ] [libdiscid](http://hydra.nixos.org/build/39412202): just missing frameworks?
- [x] [boost-1.55.0](http://hydra.nixos.org/job/nixpkgs/trunk/boost155.x86_64-darwin): see #17759
- [x] [talloc](http://hydra.nixos.org/job/nixpkgs/trunk/talloc.x86_64-darwin): tries to use a bsd specific `ar` flag on darwin?
- [ ] python2.7-Cython
- [x] go-1.7: ~~see #18546~~
- [x] gcc\* see #16806
- [x] ffmpeg: see #18137
- [ ] vty-ui
- [ ] [p7zip](https://hydra.nixos.org/job/nixpkgs/trunk/p7zip.x86_64-darwin): tries to use `xcode-select`
## Low-priority packages
- [ ] [PPSSPP](https://hydra.nixos.org/job/nixpkgs/trunk/PPSSPP.x86_64-darwin)
- [ ] [alot](https://hydra.nixos.org/job/nixpkgs/trunk/alot.x86_64-darwin)
- [x] [ansible](https://hydra.nixos.org/job/nixpkgs/trunk/ansible.x86_64-darwin)
- [x] [aria](https://hydra.nixos.org/job/nixpkgs/trunk/aria.x86_64-darwin)
- [ ] [arora](https://hydra.nixos.org/job/nixpkgs/trunk/arora.x86_64-darwin)
- [ ] [avian](https://hydra.nixos.org/job/nixpkgs/trunk/avian.x86_64-darwin)
- [ ] [avro-cpp](https://hydra.nixos.org/job/nixpkgs/trunk/avro-cpp.x86_64-darwin)
- [ ] [backblaze-b2](https://hydra.nixos.org/job/nixpkgs/trunk/backblaze-b2.x86_64-darwin)
- [ ] [bear](https://hydra.nixos.org/job/nixpkgs/trunk/bear.x86_64-darwin)
- [ ] [bigloo](https://hydra.nixos.org/job/nixpkgs/trunk/bigloo.x86_64-darwin)
- [ ] [blitz](https://hydra.nixos.org/job/nixpkgs/trunk/blitz.x86_64-darwin)
- [ ] [cadvisor](https://hydra.nixos.org/job/nixpkgs/trunk/cadvisor.x86_64-darwin)
- [x] [certbot](https://hydra.nixos.org/job/nixpkgs/trunk/certbot.x86_64-darwin)
- [ ] [chromaprint](https://hydra.nixos.org/job/nixpkgs/trunk/chromaprint.x86_64-darwin) #18063
- [ ] [chuck](https://hydra.nixos.org/job/nixpkgs/trunk/chuck.x86_64-darwin)
- [ ] [cjdns](https://hydra.nixos.org/job/nixpkgs/trunk/cjdns.x86_64-darwin)
- [ ] [ckan](https://hydra.nixos.org/job/nixpkgs/trunk/ckan.x86_64-darwin)
- [ ] [clutter](https://hydra.nixos.org/job/nixpkgs/trunk/clutter.x86_64-darwin)
- [ ] [codeblocks](https://hydra.nixos.org/job/nixpkgs/trunk/codeblocks.x86_64-darwin)
- [ ] [cogl](https://hydra.nixos.org/job/nixpkgs/trunk/cogl.x86_64-darwin)
- [ ] [consul-ui](https://hydra.nixos.org/job/nixpkgs/trunk/consul-ui.x86_64-darwin)
- [ ] [cutecom](https://hydra.nixos.org/job/nixpkgs/trunk/cutecom.x86_64-darwin)
- [ ] [cwebbin](https://hydra.nixos.org/job/nixpkgs/trunk/cwebbin.x86_64-darwin)
- [ ] [dbench](https://hydra.nixos.org/job/nixpkgs/trunk/dbench.x86_64-darwin)
- [ ] [dblatexFull](https://hydra.nixos.org/job/nixpkgs/trunk/dblatexFull.x86_64-darwin)
- [ ] [diagrams-builder](https://hydra.nixos.org/job/nixpkgs/trunk/diagrams-builder.x86_64-darwin)
- [ ] [dibbler](https://hydra.nixos.org/job/nixpkgs/trunk/dibbler.x86_64-darwin)
- [ ] [dico](https://hydra.nixos.org/job/nixpkgs/trunk/dico.x86_64-darwin)
- [ ] [dirac](https://hydra.nixos.org/job/nixpkgs/trunk/dirac.x86_64-darwin)
- [ ] [djview](https://hydra.nixos.org/job/nixpkgs/trunk/djview.x86_64-darwin)
- [ ] [dlib](https://hydra.nixos.org/job/nixpkgs/trunk/dlib.x86_64-darwin)
- [ ] [doomseeker](https://hydra.nixos.org/job/nixpkgs/trunk/doomseeker.x86_64-darwin)
- [ ] [dotnetPackages.GitVersionTree](https://hydra.nixos.org/job/nixpkgs/trunk/dotnetPackages.GitVersionTree.x86_64-darwin)
- [ ] [drive](https://hydra.nixos.org/job/nixpkgs/trunk/driver.x86_64-darwin)
- [ ] [dub](https://hydra.nixos.org/job/nixpkgs/trunk/dub.x86_64-darwin)
- [ ] [ecm](https://hydra.nixos.org/job/nixpkgs/trunk/ecm.x86_64-darwin)
- [ ] [eggdrop](https://hydra.nixos.org/job/nixpkgs/trunk/eggdrop.x86_64-darwin)
- [ ] [emojione](https://hydra.nixos.org/job/nixpkgs/trunk/emojione.x86_64-darwin)
- [ ] [errbot](https://hydra.nixos.org/job/nixpkgs/trunk/errbot.x86_64-darwin)
- [x] [flow](https://hydra.nixos.org/job/nixpkgs/trunk/flow.x86_64-darwin)
- [ ] [flpsed](https://hydra.nixos.org/job/nixpkgs/trunk/flpsed.x86_64-darwin)
- [ ] [fltk](https://hydra.nixos.org/job/nixpkgs/trunk/fltk.x86_64-darwin)
- [ ] [focuswriter](https://hydra.nixos.org/job/nixpkgs/trunk/focuswriter.x86_64-darwin)
- [x] fzf #18605
- [ ] [gccgo](https://hydra.nixos.org/job/nixpkgs/trunk/gccgo.x86_64-darwin)
- [ ] [gcj](https://hydra.nixos.org/job/nixpkgs/trunk/gcj.x86_64-darwin)
- [ ] [gdmap](https://hydra.nixos.org/job/nixpkgs/trunk/gdmap.x86_64-darwin)
- [ ] [gitAndTools.qgit](https://hydra.nixos.org/job/nixpkgs/trunk/gitAndTools.qgit.x86_64-darwin)
- [ ] [gkrellm](https://hydra.nixos.org/job/nixpkgs/trunk/gkrellm.x86_64-darwin)
- [ ] [globalplatform](https://hydra.nixos.org/job/nixpkgs/trunk/globalplatform.x86_64-darwin)
- [ ] [gnuplot_qt](https://hydra.nixos.org/job/nixpkgs/trunk/gnuplost_qt.x86_64-darwin)
- [ ] [go_1_6](https://hydra.nixos.org/job/nixpkgs/trunk/go_1_6.x86_64-darwin): see #18223 and #18546
- [ ] [go-mtpfs](https://hydra.nixos.org/job/nixpkgs/trunk/go-mptpfs.x86_64-darwin)
- [ ] [go-sct](https://hydra.nixos.org/job/nixpkgs/trunk/go-sct.x86_64-darwin)
- [ ] [goaccess](https://hydra.nixos.org/job/nixpkgs/trunk/gpaccess.x86_64-darwin)
- [ ] [gpgstats](https://hydra.nixos.org/job/nixpkgs/trunk/gpgstats.x86_64-darwin)
- [ ] [gppcscconnectionplugin](https://hydra.nixos.org/job/nixpkgs/trunk/gppcscconnectionplugin.x86_64-darwin)
- [ ] [gpshell](https://hydra.nixos.org/job/nixpkgs/trunk/gpshell.x86_64-darwin)
- [ ] [guitone](https://hydra.nixos.org/job/nixpkgs/trunk/guitone.x86_64-darwin)
- [ ] [hdf5-fortran](https://hydra.nixos.org/job/nixpkgs/trunk/hdf5-fortran.x86_64-darwin)
- [ ] [herqq](https://hydra.nixos.org/job/nixpkgs/trunk/herqq.x86_64-darwin)
- [ ] [html2text](https://hydra.nixos.org/job/nixpkgs/trunk/html2text.x86_64-darwin)
- [ ] [hugs](https://hydra.nixos.org/job/nixpkgs/trunk/hugs.x86_64-darwin)
- [ ] [hwinfo](https://hydra.nixos.org/job/nixpkgs/trunk/hwinfo.x86_64-darwin)
- [ ] [i3blocks](https://hydra.nixos.org/job/nixpkgs/trunk/i3blocks.x86_64-darwin)
- [ ] [icewm](https://hydra.nixos.org/job/nixpkgs/trunk/icewm.x86_64-darwin)
- [ ] [idnkit](https://hydra.nixos.org/job/nixpkgs/trunk/idnkit.x86_64-darwin)
- [ ] [idutils](https://hydra.nixos.org/job/nixpkgs/trunk/idutils.x86_64-darwin)
- [ ] [imatix_gsl](https://hydra.nixos.org/job/nixpkgs/trunk/imatix_gsl.x86_64-darwin)
- [ ] [javaCup](https://hydra.nixos.org/job/nixpkgs/trunk/javaCup.x86_64-darwin)
- [ ] [javasvn](https://hydra.nixos.org/job/nixpkgs/trunk/javasvn.x86_64-darwin)
- [ ] [john](https://hydra.nixos.org/job/nixpkgs/trunk/john.x86_64-darwin)
- [ ] [jonprl](https://hydra.nixos.org/job/nixpkgs/trunk/jonprl.x86_64-darwin)
- [ ] [jpegrescan](https://hydra.nixos.org/job/nixpkgs/trunk/jpegrescan.x86_64-darwin)
- [ ] [khal](https://hydra.nixos.org/job/nixpkgs/trunk/khal.x86_64-darwin)
- [ ] [kinetic-cpp-client](https://hydra.nixos.org/job/nixpkgs/trunk/kinetic-cpp-client.x86_64-darwin)
- [ ] [kpcli](https://hydra.nixos.org/job/nixpkgs/trunk/kpcli.x86_64-darwin)
- [ ] [kyotocabinet](https://hydra.nixos.org/job/nixpkgs/trunk/kyotocabinet.x86_64-darwin)
- [ ] [ldb](https://hydra.nixos.org/job/nixpkgs/trunk/ldb.x86_64-darwin)
- [ ] [leocad](https://hydra.nixos.org/job/nixpkgs/trunk/leocad.x86_64-darwin)
- [x] [letsencrypt](https://hydra.nixos.org/job/nixpkgs/trunk/letsencrypt.x86_64-darwin)
- [ ] [leveldb](https://hydra.nixos.org/job/nixpkgs/trunk/leveldb.x86_64-darwin)
- [ ] [libasyncns](https://hydra.nixos.org/job/nixpkgs/trunk/libasyncns.x86_64-darwin)
- [ ] [libcrafter](https://hydra.nixos.org/job/nixpkgs/trunk/libcrafter.x86_64-darwin)
- [ ] [libffcall](https://hydra.nixos.org/job/nixpkgs/trunk/libffcall.x86_64-darwin)
- [ ] [libircclient](https://hydra.nixos.org/job/nixpkgs/trunk/libircclient.x86_64-darwin)
- [ ] [libjack2](https://hydra.nixos.org/job/nixpkgs/trunk/libjack2.x86_64-darwin)
- [ ] [liblastfm](https://hydra.nixos.org/job/nixpkgs/trunk/liblastfm.x86_64-darwin)
- [x] [libmemcached](https://hydra.nixos.org/job/nixpkgs/trunk/libmemcached.x86_64-darwin)
- [ ] [libpfm](https://hydra.nixos.org/job/nixpkgs/trunk/libpfm.x86_64-darwin)
- [x] [libpulseaudio](https://hydra.nixos.org/job/nixpkgs/trunk/libpulseaudio.x86_64-darwin)
- [ ] [libqalculate](https://hydra.nixos.org/job/nixpkgs/trunk/libqalculate.x86_64-darwin)
- [ ] [libqglviewer](https://hydra.nixos.org/job/nixpkgs/trunk/libqglviewer.x86_64-darwin)
- [ ] [libvisual](https://hydra.nixos.org/job/nixpkgs/trunk/libvisual.x86_64-darwin)
- [ ] [libx86emu](https://hydra.nixos.org/job/nixpkgs/trunk/libx86emu.x86_64-darwin)
- [ ] [llvmPackages.lldb](https://hydra.nixos.org/job/nixpkgs/trunk/llvmPackages.lldb.x86_64-darwin) #18420
- [ ] [lout](https://hydra.nixos.org/job/nixpkgs/trunk/lout.x86_64-darwin)
- [ ] [marathi-cursive](https://hydra.nixos.org/job/nixpkgs/trunk/marathis-cursive.x86_64-darwin)
- [ ] [mathics](https://hydra.nixos.org/job/nixpkgs/trunk/matchis.x86_64-darwin)
- [x] [mbedtls](https://hydra.nixos.org/job/nixpkgs/trunk/mbedtls.x86_64-darwin) #18067
- [ ] [mcrypt](https://hydra.nixos.org/job/nixpkgs/trunk/mcrypt.x86_64-darwin)
- [x] [metis-prover](https://hydra.nixos.org/job/nixpkgs/trunk/metis-prover.x86_64-darwin)
- [ ] [ming](https://hydra.nixos.org/job/nixpkgs/trunk/ming.x86_64-darwin)
- [x] [minisat](https://hydra.nixos.org/job/nixpkgs/trunk/minisat.x86_64-darwin)
- [ ] [mktemp](https://hydra.nixos.org/job/nixpkgs/trunk/mktemp.x86_64-darwin)
- [ ] [mlton](https://hydra.nixos.org/job/nixpkgs/trunk/mlton.x86_64-darwin)
- [x] [mongodb](https://hydra.nixos.org/job/nixpkgs/trunk/mongodb.x86_64-darwin)
- [ ] [mosquitto](https://hydra.nixos.org/job/nixpkgs/trunk/mosquittp.x86_64-darwin)
- [ ] [mp3info](https://hydra.nixos.org/job/nixpkgs/trunk/mp3info.x86_64-darwin)
- [ ] [mpdris2](https://hydra.nixos.org/job/nixpkgs/trunk/mpdris2.x86_64-darwin)
- [ ] [mtx](https://hydra.nixos.org/job/nixpkgs/trunk/mtx.x86_64-darwin)
- [ ] [mutt-kz](https://hydra.nixos.org/job/nixpkgs/trunk/mutt-kz.x86_64-darwin)
- [ ] [mxt-app](https://hydra.nixos.org/job/nixpkgs/trunk/mxt-app.x86_64-darwin)
- [ ] [mysocketw](https://hydra.nixos.org/job/nixpkgs/trunk/mysocketw.x86_64-darwin)
- [ ] [ncurses6](https://hydra.nixos.org/job/nixpkgs/trunk/ncurses6.x86_64-darwin)
- [ ] [ndn-cxx](https://hydra.nixos.org/job/nixpkgs/trunk/ndn-cxx.x86_64-darwin)
- [ ] [neardal](https://hydra.nixos.org/job/nixpkgs/trunk/neardal.x86_64-darwin)
- [ ] [neomutt](https://hydra.nixos.org/job/nixpkgs/trunk/neomutt.x86_64-darwin)
- [ ] [nimble](https://hydra.nixos.org/job/nixpkgs/trunk/nimble.x86_64-darwin)
- [ ] [notmuch](https://hydra.nixos.org/job/nixpkgs/trunk/notmuch.x86_64-darwin)
- [ ] [nss](https://hydra.nixos.org/job/nixpkgs/trunk/nss.x86_64-darwin)
- [ ] [nss_wrapper](https://hydra.nixos.org/job/nixpkgs/trunk/nss_wrapper.x86_64-darwin)
- [ ] [octave](https://hydra.nixos.org/job/nixpkgs/trunk/octave.x86_64-darwin)
- [ ] [offrss](https://hydra.nixos.org/job/nixpkgs/trunk/offrss.x86_64-darwin)
- [ ] [oldsindhi](https://hydra.nixos.org/job/nixpkgs/trunk/oldsindhi.x86_64-darwin)
- [ ] [open-pdf-presenter](https://hydra.nixos.org/job/nixpkgs/trunk/open-pdf-presenter.x86_64-darwin)
- [ ] [opencryptoki](https://hydra.nixos.org/job/nixpkgs/trunk/opencryptoki.x86_64-darwin)
- [ ] [openct](https://hydra.nixos.org/job/nixpkgs/trunk/openct.x86_64-darwin)
- [ ] [opensc](https://hydra.nixos.org/job/nixpkgs/trunk/opensc.x86_64-darwin)
- [ ] [packer](https://hydra.nixos.org/job/nixpkgs/trunk/packer.x86_64-darwin)
- [ ] [pdnsd](https://hydra.nixos.org/job/nixpkgs/trunk/pdnsd.x86_64-darwin)
- [ ] [pgadmin](https://hydra.nixos.org/job/nixpkgs/trunk/pgadmin.x86_64-darwin)
- [ ] [picosat](https://hydra.nixos.org/job/nixpkgs/trunk/picosat.x86_64-darwin)
- [x] [pinentry](https://hydra.nixos.org/job/nixpkgs/trunk/pinentry.x86_64-darwin)
- [ ] [platinum-searcher](https://hydra.nixos.org/job/nixpkgs/trunk/platinum-searcher.x86_64-darwin)
- [ ] [polarssl](https://hydra.nixos.org/job/nixpkgs/trunk/polarssl.x86_64-darwin)
- [ ] [pond](https://hydra.nixos.org/job/nixpkgs/trunk/pond.x86_64-darwin)
- [ ] [poppler_qt4](https://hydra.nixos.org/job/nixpkgs/trunk/poppler_qt4.x86_64-darwin)
- [ ] [prelink](https://hydra.nixos.org/job/nixpkgs/trunk/prelink.x86_64-darwin)
- [ ] [prometheus-node-exporter](https://hydra.nixos.org/job/nixpkgs/trunk/prometheus-node-exporter.x86_64-darwin)
- [ ] [pumpio](https://hydra.nixos.org/job/nixpkgs/trunk/pumpio.x86_64-darwin)
- [x] [pxattr](https://hydra.nixos.org/job/nixpkgs/trunk/pxattr.x86_64-darwin)
- [ ] [pycapnp](https://hydra.nixos.org/job/nixpkgs/trunk/pycapnp.x86_64-darwin)
- [ ] [pyside](https://hydra.nixos.org/job/nixpkgs/trunk/pyside.x86_64-darwin)
- [ ] [qalculate-gtk](https://hydra.nixos.org/job/nixpkgs/trunk/qalculate-gtk.x86_64-darwin)
- [ ] [qscreenshot](https://hydra.nixos.org/job/nixpkgs/trunk/qscreenshot.x86_64-darwin) #18063
- [ ] [qtscriptgenerator](https://hydra.nixos.org/job/nixpkgs/trunk/qtscriptgenerator.x86_64-darwin)
- [ ] [quicktun](https://hydra.nixos.org/job/nixpkgs/trunk/quicktun.x86_64-darwin)
- [ ] [qweechat](https://hydra.nixos.org/job/nixpkgs/trunk/qweechat.x86_64-darwin)
- [ ] [radamsa](https://hydra.nixos.org/job/nixpkgs/trunk/radamsa.x86_64-darwin)
- [ ] [radare](https://hydra.nixos.org/job/nixpkgs/trunk/radare.x86_64-darwin)
- [ ] [resolv_wrapper](https://hydra.nixos.org/job/nixpkgs/trunk/resolv_wrapper.x86_64-darwin)
- [ ] [rowhammer-test](https://hydra.nixos.org/job/nixpkgs/trunk/rowhammer-test.x86_64-darwin)
- [ ] [rssh](https://hydra.nixos.org/job/nixpkgs/trunk/rssh.x86_64-darwin)
- [x] rtags: see #20191
- [ ] [runit](https://hydra.nixos.org/job/nixpkgs/trunk/runit.x86_64-darwin)
- [ ] [safecopy](https://hydra.nixos.org/job/nixpkgs/trunk/safecopy.x86_64-darwin)
- [ ] [scanmem](https://hydra.nixos.org/job/nixpkgs/trunk/scanmem.x86_64-darwin)
- [ ] [schroedinger](https://hydra.nixos.org/job/nixpkgs/trunk/schroedinger.x86_64-darwin)
- [ ] [signing-party](https://hydra.nixos.org/job/nixpkgs/trunk/signing-party.x86_64-darwin)
- [ ] [simp_le](https://hydra.nixos.org/job/nixpkgs/trunk/simp_le.x86_64-darwin)
- [ ] [simpleTpmPk11](https://hydra.nixos.org/job/nixpkgs/trunk/simpleTpmPk11.x86_64-darwin)
- [ ] [spaceOrbit](https://hydra.nixos.org/job/nixpkgs/trunk/spaceOrbit.x86_64-darwin)
- [ ] [spass](https://hydra.nixos.org/job/nixpkgs/trunk/spass.x86_64-darwin)
- [ ] [spectrwm](https://hydra.nixos.org/job/nixpkgs/trunk/spectrwm.x86_64-darwin)
- [ ] [speedcrunch](https://hydra.nixos.org/job/nixpkgs/trunk/speedcrunch.x86_64-darwin)
- [ ] [spek](https://hydra.nixos.org/job/nixpkgs/trunk/spek.x86_64-darwin)
- [ ] [spidermonkey](https://hydra.nixos.org/job/nixpkgs/trunk/spidermonkey.x86_64-darwin)
- [ ] [sqsh](https://hydra.nixos.org/job/nixpkgs/trunk/sqsh.x86_64-darwin) #18063
- [ ] [sslscan](https://hydra.nixos.org/job/nixpkgs/trunk/sslscan.x86_64-darwin) #18063
- [ ] [stockfish](https://hydra.nixos.org/job/nixpkgs/trunk/stockfish.x86_64-darwin)
- [ ] [streamripper](https://hydra.nixos.org/job/nixpkgs/trunk/streamripper.x86_64-darwin)
- [ ] [strigi](https://hydra.nixos.org/job/nixpkgs/trunk/strigi.x86_64-darwin)
- [ ] [stxxl](https://hydra.nixos.org/job/nixpkgs/trunk/stxxl.x86_64-darwin)
- [ ] [sup](https://hydra.nixos.org/job/nixpkgs/trunk/sup.x86_64-darwin)
- [ ] [svrcore](https://hydra.nixos.org/job/nixpkgs/trunk/svrcore.x86_64-darwin)
- [ ] [swaks](https://hydra.nixos.org/job/nixpkgs/trunk/swaks.x86_64-darwin)
- [ ] [synergy](https://hydra.nixos.org/job/nixpkgs/trunk/synergy.x86_64-darwin)
- [ ] [taffybar](https://hydra.nixos.org/job/nixpkgs/trunk/taffybar.x86_64-darwin)
- [ ] [tagainijisho](https://hydra.nixos.org/job/nixpkgs/trunk/tagainijisho.x86_64-darwin)
- [ ] [tcp_wrappers](https://hydra.nixos.org/job/nixpkgs/trunk/tcp_wrappers.x86_64-darwin)
- [ ] [tcpcrypt](https://hydra.nixos.org/job/nixpkgs/trunk/tcpcrypt.x86_64-darwin)
- [ ] [tevent](https://hydra.nixos.org/job/nixpkgs/trunk/tevent.x86_64-darwin)
- [ ] [textql](https://hydra.nixos.org/job/nixpkgs/trunk/textql.x86_64-darwin)
- [ ] [tightvnc](https://hydra.nixos.org/job/nixpkgs/trunk/tightvnc.x86_64-darwin) #14809
- [ ] [tpm-tools](https://hydra.nixos.org/job/nixpkgs/trunk/tpm-tools.x86_64-darwin)
- [ ] [transfig](https://hydra.nixos.org/job/nixpkgs/trunk/transfig.x86_64-darwin)
- [ ] [trousers](https://hydra.nixos.org/job/nixpkgs/trunk/trousers.x86_64-darwin)
- [ ] [tsocks](https://hydra.nixos.org/job/nixpkgs/trunk/tsocks.x86_64-darwin)
- [ ] [tthsum](https://hydra.nixos.org/job/nixpkgs/trunk/tthsum.x86_64-darwin)
- [ ] [ttyrec](https://hydra.nixos.org/job/nixpkgs/trunk/ttyrec.x86_64-darwin)
- [ ] [urlwatch](https://hydra.nixos.org/job/nixpkgs/trunk/urlwatch.x86_64-darwin)
- [ ] [vdirsyncer](https://hydra.nixos.org/job/nixpkgs/trunk/vdirsyncer.x86_64-darwin)
- [ ] [vimNox](https://hydra.nixos.org/job/nixpkgs/trunk/vimNox.x86_64-darwin)
- [ ] [vmmlib](https://hydra.nixos.org/job/nixpkgs/trunk/vmmlib.x86_64-darwin) #18063
- [ ] [webrtc-audio-processing](https://hydra.nixos.org/job/nixpkgs/trunk/webrtc-audio-processing.x86_64-darwin)
- [ ] [wiredtiger](https://hydra.nixos.org/job/nixpkgs/trunk/wiredtiger.x86_64-darwin)
- [ ] [xautolock](https://hydra.nixos.org/job/nixpkgs/trunk/xautolock.x86_64-darwin)
- [ ] [xbase](https://hydra.nixos.org/job/nixpkgs/trunk/xbase.x86_64-darwin)
- [ ] [xca](https://hydra.nixos.org/job/nixpkgs/trunk/xca.x86_64-darwin)
- [x] zeroc_ice
- [ ] [zookeeper_mt](https://hydra.nixos.org/job/nixpkgs/trunk/zookeeper_mt.x86_64-darwin)

**Comment by l2dy** [comment]
p7zip is also broken. <https://hydra.nixos.org/job/nixpkgs/trunk/p7zip.x86_64-darwin>

**Comment by LnL7** [comment]
`go-1.7` will be fixed by #18546

**Comment by knedlsepp** [comment]
Just as a note: I think the problems of `python2.7-Cython` and `gdal`  #18194  are somehow related. Both fail on building python extensions by wrongly choosing `clang` instead of `clang++` as the CXX compiler and thus cannot find the C++ Standard Library headers.

**Comment by LnL7** [comment]
I think the rust build was broken by the last update https://github.com/NixOS/nixpkgs/commit/8cd3e1e2bac5d7b8d3ae84a91f1019007f82c483

**Comment by LnL7** [comment]
@matthewbauer Thank you for putting this list together

**Comment by acowley** [comment]
The `fltk` problem needs `Foundation` from the 10.10 SDK or newer.

**Comment by acowley** [comment]
Regarding `octave`, I use it on darwin, but I have this in my `config.nix`:

```
octave = pkgs.callPackage (<nixpkgs> + /pkgs/development/interpreters/octave) {
      openblas = pkgs.openblasCompat;
      jdk = null;
    };
```

Not sure if that counts as a fix.

**Comment by matthewbauer** [comment]
@acowley It looks like it can build but you need to have XCode installed.

**Comment by acowley** [comment]
@matthewbauer Are you referring to `octave` or `fltk`?

**Comment by matthewbauer** [comment]
Sorry, octave.

**Comment by knedlsepp** [comment]
@matthewbauer: The python2.7-Cython build can be fixed by adding:
```
NIX_CFLAGS_COMPILE = stdenv.lib.optionalString (stdenv.cc.isClang) "-I${pkgs.libcxx}/include/c++/v1";
```
The problem is that distutils does not seem to probably honor the difference between CC and CXX. `gcc` does not complain when compiling C++ code, but nix-`clang` cannot find the C++ headers.
I however do suspect that all the packages that depend on cython would also need this extra include flag. What's your opinion on a simpler solution. Should we add the C++ headers to nix-clang itself by default? I think the Apple supplied clang uses this already.

**Comment by periklis** [comment]
@matthewbauer Could you elaborate how you did compile this list? Is this the list of all packages on osx with `allowBroken=true` directive in `~/.nixpkgs/config.nix`?

**Comment by Mic92** [comment]
Do you have suggestions, how I can test packages as a Linux contributor without having apple native hardware? I recently found this one: https://github.com/AndrewDryga/vagrant-box-osx

**Comment by Mic92** [comment]
Would it help, when we have platform specific maintainers? Often I have pull requests, which will update the package but break Darwin support. In these cases there is nobody I can consult.

**Comment by matthewbauer** [comment]
@periklis These are all from Hydra so packages that are marked broken aren't included. The same goes for packages that don't have "x86-64-darwin" in meta.platforms.

**Comment by LnL7** [comment]
@Mic92 I didn't know there are box images for osx, but that's probably still a violation of apple's software EULA.

I think having some sort of list of maintainers for a platform would be useful, but feel free to cc me if you run into darwin specific issues.

**Comment by LnL7** [comment]
@matthewbauer FYI staging was merged in yesterday, this means master now includes updated frameworks. Perhaps it's a good idea to update this when hydra is finished building everything.

**Comment by blakesweeney** [comment]
I was looking into the `gcc` issue a bit (I wanted to install `dub`). I saw hydra is showing the same failure that I have been getting. I found this: https://superuser.com/questions/995360/missing-usr-include-in-os-x-el-capitan it suggests running `xcode-select --install` prior to trying to compile `gcc`. I tried it and it fixed my issue with compiling `gcc` and `dub`. It's probably worthwhile to try this on hydra and see what works afterwards.

**Comment by LnL7** [comment]
@blakesweeney It's supposed to work without xcode or the command line tools. We have pure versions of everything in nixpkgs, some packages just try to use `xcode-select` anyway, or look for stuff in hardcoded places.

**Comment by matthewbauer** [comment]
`gcc` should be fixed but I'm going to wait for it to hit the unstable channel before I check it off.

**Comment by matthewbauer** [comment]
I'm happy to report after >1 year of failing, "gcc" has finally hit the unstable channel.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixpkgs/commit/fc4c0d4ba173f7ef9021f31c360da525b0b91e0e should fix `talloc`

**Comment by copumpkin** [comment]
`p7zip` seems to work for me 😄

**Comment by matthewbauer** [comment]
@copumpkin you probably have Xcode.app installed?

**Comment by copumpkin** [comment]
Oh, you're probably right. I really need to get around to fixing that sandbox 🙁

**Comment by matthewbauer** [comment]
@copumpkin Is there an open issue for Darwin sandboxing? The only information I can find of it is from the old wiki page: https://nixos.org/wiki/Nix_on_OS_X#Darwin_Sandboxes.

**Comment by copumpkin** [comment]
Not sure! I vaguely remember something but on my phone now. I'm going to
devote some time this weekend fixing Nix to build on Darwin and then
starting to fix the sandbox (hard to fix that if Nix doesn't build :P)

**Comment by acowley** [comment]
I've been using sandboxing for a little while now; it's really essential for avoiding "works for me" problems. The killer about fixing it in nixpkgs is that changing the sandbox definition there requires rebuilding everything. It's not that onerous to run `sandbox-exec -f nix.sb -- nix-build ...`, but it might be nicer if such ad hoc sandboxing was offered by the nix command line tools themselves.

**Comment by copumpkin** [comment]
@acowley have you done stdenv builds with it turned on? I think it'll generally be fine later in the build but the stdenv build seems to fail miserably with sandbox turned on. Trying to look into it in the next few days.

**Comment by acowley** [comment]
@copumpkin. I have not, sorry. The old sandbox definition in nixpkgs can't build anything (presumably due to macOS changes) as far as I've seen. Are you also using a different sandbox spec than what is in nixpkgs?

**Comment by copumpkin** [comment]
Nope, just trying to fix the sandbox to be as functional as it used to be 😄

**Comment by periklis** [comment]
fyi, just PR'ed rtags #20191

**Comment by knedlsepp** [comment]
libmemcached must be some kind of general hydra/nix problem https://github.com/NixOS/nixpkgs/pull/15231 Hydra consistently outputs wrong hashes for a file it tries to download: https://hydra.nixos.org/build/43986509/nixlog/1/raw

**Comment by copumpkin** [comment]
Could be a cached failure? @shlevy?

**Comment by shlevy** [comment]
Restarted the build

**Comment by NejcZupec** [comment]
Now also `libmemcached` can be successfully built on darwin.

**Comment by LnL7** [comment]
It would be great to have a better way of tracking this stuff and keep it up to date properly. You can get a diff compared to a day/week earlier from hydra, perhaps there's some way we could leverage that?

http://hydra.nixos.org/eval/1320213?filter=x86_64-darwin&compare=1310591&full=#tabs-now-fail

**Comment by yurrriq** [comment]
`p7zip` works for me with 0d936b03668cf0d9cd68b9a1bda72b14c59be407 and the following, since `libuv` is acting up on my machine again:

```nix
{
 nixpkgs.config.packageOverrides = pkgs: rec {
    libuv = pkgs.lib.overrideDerivation pkgs.libuv (p: { doCheck = false; });
  };
}
```
