### ISSUE TITLE
DaVinci Resolve Studio 18 Beta or atleast Studio 17

### ISSUE THREAD

**Issue by v3eil** [NixOS/nixpkgs#180656]
NixOS packages already contains a free version of Resolve 17 so there should be Studio version too.

I more like to use Resolve 18 Beta it is stable and very good to use. Studio please. I would do this by myself but I don't know how, I am not that good on handling package management.

**Comment by truvatech** [comment]
@jshcmpbll any chance you could update the davinci resolve package to 18 please? I'd try to do that myself but not at all familiar enough with nix packages to make that kind of upgrade myself :(

**Comment by pbsds** [comment]
Closing in favor of #166902 and #169901
