### ISSUE TITLE
services.nginx: Use $scheme for globalRedirect.

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#18071]
## Issue description

Right now the nginx service does prepend `http` or `https` (depending on `enableSSL`) to the value of `globalRedirect`. Nginx supports the `$scheme` variable to automatically use whatever the current context uses. Is there any reason why we're not using it?

**Comment by globin** [comment]
Probably because I didn't think of it :sweat_smile:

**Comment by Profpatsch** [comment]
(triage) @globin fixed?

**Comment by tomberek** [comment]
(triage) close?
