### ISSUE TITLE
SDDM: Plasma Wayland session starts on the same TTY

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#180727]
### Describe the bug
When SDDM launches a Plasma Wayland session, it is supposed to launch it on a separate TTY to avoid certain problems. https://github.com/sddm/sddm/issues/1409
However, this is not done (on my end, they are both on TTY 7).
One of the issues caused by this is, for example, if you change TTY during the Plasma Wayland session, when returning the desktop is unusable (it's completely black, with only the cursor being in a cross form. This should be the behavior when selecting the TTY where SDDM is, but since they are both and same TTY...). This doesn't happen when Plasma Wayland is launched via TTY (`dbus-run-session startplasma-wayland`).
I didn't test whether this issue happens only on SDDM specifically.

### Steps To Reproduce
1. Enable SDDM and Plasma.
2. Launch Plasma Wayland from SDDM.
3. Both are on the same TTY.

### Expected behavior
They should be on different TTYs.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.9-zen1, NixOS, 22.11 (Raccoon), 22.11pre390234.2770cc0b1e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jansol** [comment]
For me they are both on tty2, but switching back and forth between ttys does not seem to cause any problems. Is this related to virtualization stuff?

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.8, NixOS, 22.11 (Raccoon), 22.11pre389487.18b14a254dc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
Seems fixed now. I can switch between users and TTYs with no problem.
Closing.
