### ISSUE TITLE
"exa" fails on unstable

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#18081]
## Issue description

`exa` fails to build

### Steps to reproduce

`nix-shell -p exa --pure` (the `--pure` because of the nix-shell issues reported elsewhere)

## Technical details

* System: 16.09.git.52a875f (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "16.09pre89269.8512747"

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixpkgs/issues/18002
