### ISSUE TITLE
virt-manager should include netcat-openbsd into its env

### ISSUE THREAD

**Issue by lierdakil** [NixOS/nixpkgs#180806]
### Describe the bug
 
Virt-manager requires netcat version with support for `-U` arguments. `nc` version available by default does not.

### Steps To Reproduce
1. install virt-manager into a profile
2. start
3. try connecting to remote machine

### Expected behavior

Connection successful

### Actual behavior

virt-manager complains about `netcat` not supporting `-U` flag.

### Screenshots

![image](https://user-images.githubusercontent.com/7275622/178091456-5bff1bd8-0c19-4fab-826c-e2790f9097c4.png)

### Notify maintainers

@qknight @offline @fpletz @globin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.11-gentoo, Gentoo, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(root): `""`
 - channels(livid): `"nixpkgs-22.05pre349906.7f65e4abd5e"`
 - nixpkgs: `/home/livid/.nix-defexpr/channels/nixpkgs`
```
(this is probably mostly irrelevant as I'm using flakes to manage my profile)

**Comment by fpletz** [comment]
Both `netcat` and `netcat-openbsd` do support -U but `netcat-gnu` does not. Since this needs to be available on the remote machine, we should add this to the `virtualisation.libvirtd` module.
