### ISSUE TITLE
Document how to use other init systems on NixOS

### ISSUE THREAD

**Issue by arconix** [NixOS/nixpkgs#18082]
like sinit and tini are available in all-packages.nix. I know tini is for containers, but how about sinit?

**Comment by joachifm** [comment]
Just because a package is in Nixpkgs does not mean it is supported on NixOS.

**Comment by shlevy** [comment]
You can't currently.

**Comment by vcunat** [comment]
@7c6f434c had some (hacky) systemd-free setup IIRC.

**Comment by 7c6f434c** [comment]
It's not NixOS in any sense, though — it is just a set of shell scripts that happen to rely on this great build manager software called Nix, and use NixPkgs because Nix is used anyway.
