### ISSUE TITLE
avahi / nssmdns working inconsistently

### ISSUE THREAD

**Issue by graysonhead** [NixOS/nixpkgs#180883]
### Describe the bug
Recently I've started converting a lot of my desktops to NixOS. Things have been going swimmingly, but one persistent issue I've had is inconsistent printer support via mdns. Adding the printer works fine, but print jobs often fail with an error message of `Unable to locate printer "<hostname>.local`. Restarting the print job will result in it completing sucesfully.

Digging down a bit further, I see an explanation for this behavior when I ping or resolve the host:

```console
[grayson@green:~]$ ping brn30055c705e6e.local
ping: brn30055c705e6e.local: System error

[grayson@green:~]$ ping brn30055c705e6e.local
PING brn30055c705e6e.local (10.5.5.159) 56(84) bytes of data.
64 bytes from 10.5.5.159 (10.5.5.159): icmp_seq=1 ttl=255 time=4.41 ms
```
```console
[grayson@green:~]$ getent hosts brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local
10.5.5.159      brn30055c705e6e.local
```

At first I thought it was just the first query that would fail, and subsequent ones would hit a cache of some kind, but it turns out the behavior is much more random than that:

```console
[grayson@green:~]$ getent hosts brn30055c705e6e.local
10.5.5.159      brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local
10.5.5.159      brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local
10.5.5.159      brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local
10.5.5.159      brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local

[grayson@green:~]$ getent hosts brn30055c705e6e.local

```

But `avahi-resolve` consistently works, I've yet to see it fail:
```console
[grayson@green:~]$ avahi-resolve -n brn30055c705e6e.local
BRN30055C705E6E.local   10.5.5.159
```

This leads me to believe that the issue is somewhere in the nss-mdns integration.

### Steps To Reproduce
1. Check avahi-resolve to ensure device is functioning properly
2. Repeatedly ping/resolve the .local address
3. Sadness :(

### Expected behavior
An address which can be resolved by avahi-resolve consistently should be consistently resolved by the system/nss.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[grayson@green:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.52, NixOS, 22.05 (Quokka), 22.05.20220708.71d7a4c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Most of the relevant configuration is here: https://github.com/graysonhead/nixos-configs/blob/main/roles/plasma-desktop.nix

**Comment by graysonhead** [comment]
Just for fun I swapped out nss-mdns for `v0.15.1` from this repository: https://github.com/lathiat/nss-mdns .

This fixed my issue and also considerably sped up resolution of mdns hostnames.

I'd make a PR to update it right now, but in addition to switching the provider of the package source (I'm not sure if there is any additional review that is needed for this in nixos)  I had to disable the patch made by @r-burns regarding musl support, and I'm not familiar enough with musl to know why it was needed in the first place and if it is still needed with this version.

For context, this is what my current override looks like: https://github.com/graysonhead/nixos-configs/commit/dec05fae021dd9042a68e73f776b47fc91ca290b

**Comment by gloaming** [comment]
@graysonhead Closed by https://github.com/NixOS/nixpkgs/pull/182236 ?

**Comment by graysonhead** [comment]
Yep it is. Closing
