### ISSUE TITLE
tclgpg: svn repository doesn't exist anymore

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#18093]
They moved to fossil, their new repo is here: https://chiselapp.com/user/sgolovan/repository/tclgpg/index. I can't work out what revision to pick, so I am opening this as an issue.

**Comment by jonafato** [comment]
It looks as though tclgpg was removed in 4a702e8b74e9b208f3b5d51893b70731cf548e4a. Should this issue be closed?

**Comment by sternenseemann** [comment]
Yeah, thanks!
