### ISSUE TITLE
Package request: wayshot

### ISSUE THREAD

**Issue by Jedsek** [NixOS/nixpkgs#180944]
**Project description**
screenshot tool for wlroots based compositors implementing zwlr_screencopy_v1 

**Metadata**

* homepage URL: https://github.com/waycrate/wayshot
* source URL: https://github.com/waycrate/wayshot
* license: bsd
* platforms: linux

**Comment by teto** [comment]
have you looked if any of these packages are not already in  https://github.com/nix-community/nixpkgs-wayland ?

**Comment by Jedsek** [comment]
@teto yes
