### ISSUE TITLE
Package request: wayout

### ISSUE THREAD

**Issue by Jedsek** [NixOS/nixpkgs#180946]
**Project description**
A simple output management tool for wlroots based compositors implementing zwlr_output_power_management_v1

**Metadata**

* homepage URL: https://github.com/waycrate/wayout
* source URL: https://github.com/waycrate/wayout
* license: bsd
* platforms: linux

**Comment by onny** [comment]
Tried to package wayout but somehow I get an build error
```
> Executing cargoBuildHook
> ++ env CC_x86_64-unknown-linux-gnu=/nix/store/kia8xygy2r9iblwbjrl163j4bpz84wz7-gcc-wrapper-11.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/kia8xygy2r9iblwbjrl163j4bpz84wz7-gcc-wrapper-11.3.0/bin/c++ CC_x86_64-unknown-linux-gnu=/nix/store/kia8xygy2r9iblwbjrl163j4bpz84wz7-gcc-wrapper-11.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/kia8xygy2r9iblwbjrl163j4bpz84wz7-gcc-wrapper-11.3.0/bin/c++ cargo build -j 4 --target x86_64-unknown-linux-gnu --frozen --release
> error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
> If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```
Not sure if this is an upstream issue

**Comment by Shinyzenith** [comment]
@onny @Jedsek Thank you for the interest in the project :D

I have update Cargo.lock and tagged a release accordingly (`1.1.3`).

**Comment by onny** [comment]
Thank you @Shinyzenith , that worked.

@Jedsek Feel free to test out and review the PR :)
