### ISSUE TITLE
Package request for Solaar

### ISSUE THREAD

**Issue by Odyssey346** [NixOS/nixpkgs#180954]
**Project description**
Solaar is an app that allows you to manage many Logitech peripherals. For me, it would be most useful because of my MX Master 3.

**Metadata**

* homepage URL: https://pwr-solaar.github.io/Solaar/
* source URL: https://github.com/pwr-Solaar/Solaar
* license: GPL2
* platforms: Linux

**Comment by fabaff** [comment]
[`solaar`](https://search.nixos.org/packages?channel=unstable&show=solaar&from=0&size=50&sort=relevance&type=packages&query=solaar) is already available.

**Comment by Odyssey346** [comment]
since when? I searched it and could not find it.Sendt fra min Galaxy

**Comment by gi-yt** [comment]
> since when? I searched it and could not find it.Sendt fra min Galaxy

its on unstable. ig you were checking the stable release channel
