### ISSUE TITLE
build-node-package.nix takes excessive amount of time

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#18090]
## Issue description

A profile of `NIX_COUNT_CALLS=1 nix-env -qa --drv-path` on Nixpkgs master shows that `build-node-package.nix` is the most dominant function during evaluation:

```
calls to 9295 functions:
    210846 anonymous function at /home/eelco/Dev/nixpkgs-stable/pkgs/development/web/nodejs/build-node-package.nix:314:33
    201017 anonymous function at /home/eelco/Dev/nixpkgs-stable/pkgs/tools/typesetting/tex/texlive-new/combine.nix:31:36
    201017 anonymous function at /home/eelco/Dev/nixpkgs-stable/pkgs/tools/typesetting/tex/texlive-new/combine.nix:31:39
     93926 ‘optional’ at /home/eelco/Dev/nixpkgs-stable/lib/lists.nix:175:14
     93926 ‘optional’ at /home/eelco/Dev/nixpkgs-stable/lib/lists.nix:175:20
...
```

In fact about 23% of Nixpkgs evaluation time is spent in nodejs stuff.

This is strange because hardly any nodejs packages are included in the output:

```
$ nix-env -f ~/Dev/nixpkgs -qa --drv-path | grep nodejs | wc -l
14
```

So it looks like there is some opportunity for optimisation here...
## Technical details
- System: 16.03.git.7a41a40M
- Nix version: 1.11.2
- Nixpkgs version: 8a84fc0217344990b646cbfbf01037b935407a40

**Comment by domenkozar** [comment]
I wonder, how do you know 23% of time is spent on nodejs stuff?

**Comment by edolstra** [comment]
Just by disabling node-packages.nix:
```
diff --git a/pkgs/top-level/node-packages.nix b/pkgs/top-level/node-packages.nix
index d8eb668..3d9cf8d 100644
--- a/pkgs/top-level/node-packages.nix
+++ b/pkgs/top-level/node-packages.nix
@@ -15,7 +15,7 @@
 , ...
 } @ args:
 
-with stdenv.lib;
+with stdenv.lib; assert false;
 
 let
   removeDeps = remove: deps: filterAttrs (n: d: all (r: r != d.pkgName) remove) deps;
```

**Comment by domenkozar** [comment]
There is some deep magic in `pkgs/development/web/nodejs/build-node-package.nix`.

So hopefully https://github.com/NixOS/nixpkgs/pull/16886 will yield https://github.com/NixOS/nixpkgs/issues/14532

**Comment by domenkozar** [comment]
@svanderburg how is the new code performance comparing to previous?

**Comment by FlorentBecker** [comment]
This seems to be fixed (texlive is now at the top of that listing).

**Comment by globin** [comment]
Yep, looks fine
