### ISSUE TITLE
Regression: some CIFS/SMB3 mounts broken on 22.05 / linux-5.18.8+

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#181016]
### Describe the bug
Description in https://lore.kernel.org/linux-cifs/211885e7-1823-9118-836b-169c7163d7c2@gmail.com/T/#u

### Steps To Reproduce
1. find a smb server ("`srv`") running samba<4.15
1. `mount.cifs -o vers=3.1.1,... //srv ./mntpnt`

### Expected behavior
Mount works as it did on linux-5.18.7.

### Additional context
* Also observed by others: https://bugs.archlinux.org/task/75241
* From what I can see from the diffstats this hasn't been addressed in 5.18.9 or 5.18.10 so far.

### Metadata

 - host os: `Linux 5.18.9, NixOS, 22.05 (Quokka), 22.05.1543.71d7a4c037d`

**Comment by Emantor** [comment]
According to the Archlinux bug tracker entry this was fixed in kernel commit `32f319183c439b239294cb2d70ada3564c4c7c39` which was contained in 5.19. Closing this issue.
