### ISSUE TITLE
Haskell: 

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#18116]
## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by domenkozar** [comment]
dupes https://github.com/NixOS/nixpkgs/issues/18118

**Comment by obadz** [comment]
Ha, sorry, my fingers were slipping on Ctrl+Enter I think and browser kept opening new page…
