### ISSUE TITLE
Build rustc{Beta,Unstable} on Hydra?

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#18111]
## Issue description

Right now it's still quite common to use `rustUnstable.rustc` for Rust development as many nice features (most notably procedural macros) are only enabled there at the moment. 

Users have shown interest for binary-substitutes for rustc, and I can fully understand that you don't want to wait ~4 hours for a `rustc` build.

Is there a process or someone to ask if we can add these packages to the Hydra build? The builds take quite some time, so I'd rather not do it without discussing it first.

**Comment by the-kenny** [comment]
Thinking a bit more about this I don't think it's a good idea to have `unstable` (and even `beta`) in `nixpkgs` anyway. While `beta` is rarely used (as unstable features are disabled there which is the primary cause for not using `stable`) `unstable` is updated too frequently for us to keep track. 

Better solutions for `unstable` exist (https://github.com/solson/rust-nightly-nix), so we should just get rid of `beta` and `unstable`.

**Comment by sjmackenzie** [comment]
good grief, please don't.

**Comment by sjmackenzie** [comment]
Building on nixpkgs is quickly descending into a nightmare. I thought it would be solid.

**Comment by sjmackenzie** [comment]
Like in your thinking, did you factor in the people that are using this at all? Like even a little?

**Comment by the-kenny** [comment]
Wow, is there any reason for being so hostile? I obviously didn't delete anything yet. I just want to start a discussion. 

Keep in mind that our unstable was last updated in July. If you depend on such an old *unstable* version you might want to consider copying the expression for the compiler into your project.

**Comment by sjmackenzie** [comment]
Breaking public APIs is hostile, closing this issue with a unilateral "so we should just get rid of beta and unstable." is hostile. The whole point of nixpkgs going through hydra is binary distribution, saving Fractalide and Nixpkgs users 4~5 hours of compilation, most of the interesting features for complex projects like Fractalide are in rustUnstable. I've just contracted people to fix *this* very problem.

**Comment by the-kenny** [comment]
Ok, so it boils down if we should treat `nixpkgs.git` as a stable API. This surely isn't the right ticket to discuss this.

Also keep in mind that you can always pin your nixpkgs to a specific revision or a `stable` channel. These are guaranteed to have a stable api.

**Comment by sjmackenzie** [comment]
Look Kenny, I get that you don't have time to maintain this. I will take over the maintenance of Rust, I have financial incentives to keep this up and running and stable as possible.

There is a patch that is ready to fix this right now. Shall we say that myself and a few other people take over the maintenance of Rust on nixpkgs please?

We're doing a whole bunch right now from stripping out cargo in Fractalide to developing something called `nixcrates` which basically reads crates.io-index and writes nix expressions to a repo called nix-crates.io-index, thus allowing us to get rid of the cognitive dissonance that exists between cargo and nix, and allowing fractalide users to directly interact with rust programs using nix. There is a whole bunch of stuff going on and really it's becoming hard interacting with Rust on nixpkgs. It would be very helpful if you allowed us to take over please.

**Comment by the-kenny** [comment]
Feel free to submit a pull request updating beta and master and I'll merge it if it looks good. I wasn't aware of anyone relying on such an old version of `rustcMaster`. I'm sorry if I was mistaken.

That said, please refrain from guessing about my intentions or my personal timetable. If you have financial incentives that's fine. It still doesn't mean you can lecture me.

**Comment by sjmackenzie** [comment]
I'm getting ready to stabilize Fractalide at 1.0 very soon, part of the stabilization is fixing this issue. It's really not good having users say `WTF` I just waited 5 hours to compile Fractalide. Fractalide also has potential to being a very good source of new nix users and potentially new maintainers. Which will hopefully boost not only nixpkgs, but also hydra and nixops because all these tools are being used in Fractalide.

**Comment by qknight** [comment]
@the-kenny @vcunat @davidak 

i've filed a bug-report but i'm not 100% sure if this is a nix related issue or rust related issue:

https://github.com/rust-lang/rust/issues/38026

**Comment by the-kenny** [comment]
I've seen this before. Please see the linked ticket for a description of
the problem and a possible fix.

Joachim Schiele <notifications@github.com> writes:

> @the-kenny @vcunat @davidak 
>
> i've filed a bug-report but i'm not 100% sure if this is a nix related issue or rust related issue:
>
> https://github.com/rust-lang/rust/issues/38026
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/issues/18111#issuecomment-263131817

--
