### ISSUE TITLE
Unable to build gnumake with guile Support

### ISSUE THREAD

**Issue by jiegec** [NixOS/nixpkgs#181188]
### Describe the bug

```shell
$ nix-shell -p 'gnumake.override { guileSupport = true; }'
error: anonymous function at /nix/store/69pqivsw2n1mg90fnq24dsg8k4w6yaz6-nixpkgs/nixpkgs/pkgs/build-support/fetchurl/boot.nix:5:1 called with unexpected argument 'postFetch'

       at /nix/store/69pqivsw2n1mg90fnq24dsg8k4w6yaz6-nixpkgs/nixpkgs/pkgs/build-support/fetchpatch/default.nix:31:1:

           30| in
           31| lib.throwIfNot (excludes == [] || includes == [])
             | ^
           32|   "fetchpatch: cannot use excludes and includes simultaneously"
(use '--show-trace' to show detailed location information)
```

### Steps To Reproduce
1. run `nix-shell -p 'gnumake.override { guileSupport = true; }'`

### Expected behavior

Build GNU make with guile support.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$  - system: `"x86_64-linux"`
 - host os: `Linux 5.18.5, Debian GNU/Linux, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.2`
 - channels(root): `"nixpkgs"`
 - channels(jiegec): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by trofi** [comment]
1 year ago at 7c6cfb041b8a15bd77a5bf42a9cc499d9f24add5 it still worked. Bisect points at cb955555df9bfff95f8a417927f6aca265da37ee `libffi: Run test suite`. 

The following workaround restore `gnumake`'s override:

```diff
--- a/pkgs/development/libraries/libffi/default.nix
+++ b/pkgs/development/libraries/libffi/default.nix
@@ -3,7 +3,7 @@

   # test suite depends on dejagnu which cannot be used during bootstrapping
   # dejagnu also requires tcl which can't be built statically at the moment
-, doCheck ? !(stdenv.hostPlatform.isStatic)
+, doCheck ? false
 , dejagnu
 }:
```

/cc @zhaofengli

**Comment by trofi** [comment]
Another workaround seems to be to inline `expect`'s patch to avoid external fetch.

The proper fix would probably be to force `guileSupport = false;` for bootstrap dependencies. I'll try to do it, but don't guarantee if I succeed.

**Comment by trofi** [comment]
Proposed my attempt at fixing it as https://github.com/NixOS/nixpkgs/pull/181536

**Comment by trofi** [comment]
https://github.com/NixOS/nixpkgs/pull/181536 was merged a while ago and `nix-shell -p 'gnumake.override { guileSupport = true; }'` works in current unstable. Let's declare it done.
