### ISSUE TITLE
duply: No module named cryptography.hazmat.backends

### ISSUE THREAD

**Issue by reinhardt** [NixOS/nixpkgs#18112]
## Issue description

When running duply with the sftp backend it throws the error

`BackendException: Could not initialize backend: No module named cryptography.hazmat.backends
09:42:15.986 Task 'BKP' failed with exit code '23'.`

### Steps to reproduce

`nix-shell --pure -p duply --run 'duply test create; mkdir -p source; mkdir -p target; echo SOURCE="$PWD/source`
`TARGET=sftp://localhost/$PWD/target`
`TARGET_PASS=''" > ~/.duply/test/conf; duply test backup' -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz`

## Technical details

* System: 16.09pre89501.898edb0 (Flounder)
* Nix version: 1.11.2
* Nixpkgs version: 16.09pre89501.898edb0

**Comment by domenkozar** [comment]
@FRidh is the backend missing or is it using wrong version of cryptography?

**Comment by FRidh** [comment]
if cryptography isn't added as a buildInput I'm not surprised it won't work. @reinhardt could you test https://github.com/FRidh/nixpkgs/tree/duply
cc maintainer @bjornfor

**Comment by FRidh** [comment]
well, I accidentally merged it already, so @reinhardt you can try master as well.

**Comment by reinhardt** [comment]
Using FRidh/nixpkgs like this

`nix-shell --pure -p duply --run 'duply test create; mkdir -p source; mkdir -p target; echo SOURCE="$PWD/source
TARGET=sftp://localhost/$PWD/target
TARGET_PASS=''" > ~/.duply/test/conf; duply test backup' -I nixpkgs=https://github.com/FRidh/nixpkgs/archive/duply.tar.gz`

still gives the same error I'm afraid.

**Comment by FRidh** [comment]
I suppose it is duplicity that needs this library.

**Comment by FRidh** [comment]
cc maintainers @viric @peti

**Comment by reinhardt** [comment]
FTR, as a workaround I tried installing older versions of duply/duplicity using [Edward Tjörnhammar's method](http://edwtjo.me/posts/2016-04-24-installing-older-pkgs-in-nixos/) but still got the same error. (Which of course is weird because it worked for me until days ago.)

**Comment by reinhardt** [comment]
Sorry, must have mixed something up yesterday - I was able to install duplicity-0.7.06/duply-1.9.2 from nixpkgs 5b0a045d07 just now and backup is running. Meaning I have a workaround for now.

**Comment by peti** [comment]
Sounds like this has been fixed.

**Comment by reinhardt** [comment]
How? Where?

**Comment by reinhardt** [comment]
I don't see how this is fixed. The nix-shell invocation from the description still throws the same error.

**Comment by reinhardt** [comment]
Any ideas here? With a pointer or to I would be willing to try and fix it myself, but I'm not sure where to start.

**Comment by FRidh** [comment]
If I am correct, `duply` calls `duplicity`, so the error we're seeing is in `duplicity`, and not in `duply` (therefore my fix in https://github.com/NixOS/nixpkgs/commit/400d1d5c89741c2d6e94aa5c60b13f03fdc53e1c didn't work). The `duplicity` package doesn't seem to have `cryptography`, only `pycrypto`, so I imagine that to be the problem.

**Comment by reinhardt** [comment]
Thanks! That was the right direction. There were a couple more missing dependencies but I managed to sort them out.
