### ISSUE TITLE
Emacs wrapper loads autoloads redundantly

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#181175]
The `nix-generated-autoload` file generated by the Emacs wrapper is redundant
because the autoload definitions are already processed by the builtin `package.el`:
the `nix-generated-autoload` is loaded after `init.el` with the command line option `-l`,
but `package.el` loads the package autoloads before `init.el`.
We can understand this better by considering a few scenarios.

### Scenario 1: `nix-generated-autoload` enabled, `package.el` disabled

If we start Emacs with `package.el` disabled,
then the autoloads will not be available in `init.el`
because `nix-generated-autoload` is not loaded until later:

``` sh
cd $(mktemp -d)
nix-build -E "with import <nixpkgs> {}; emacs.pkgs.withPackages(epkgs: [epkgs.magit])"
mkdir .emacs.d
echo "(setq package-enable-at-startup nil)" >>.emacs.d/early-init.el  # disable package.el
echo "(unless (autoloadp (symbol-function 'magit-init)) (error \"Missing autoloads\"))" >>.emacs.d/init.el
env HOME=$(pwd) ./result/bin/emacs  # observe that there is no autoload for magit-init
```

### Scenario 2: `nix-generated-autoload` disabled, `package.el` enabled

If we modify the wrapper as in #181174 so that `nix-generated-autoload` is not loaded,
the autoloads will still be found as long as `package.el` is enabled:

``` sh
cd $(mktemp -d)
nix-build -E "with import <nixpkgs> {}; emacs.pkgs.withPackages(epkgs: [epkgs.magit])"
mkdir .emacs.d
echo "(unless (autoloadp (symbol-function 'magit-init)) (error \"Missing autoloads\"))" >>.emacs.d/init.el
env HOME=$(pwd) ./result/bin/emacs  # observe no error
```

### Conclusion

`package.el` is enough on its own to handle autoloads for the Emacs wrapper.
Therefore, I propose to remove `nix-generated-autoload` in favor of the builtin Emacs functionality.

### Notify maintainers

@nagy @ttuegel

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.49, NixOS, 22.11 (Raccoon), 22.11.git.5270c1d1cb7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - nixpkgs: `/etc/nixos/nixpkgs`
```

**Comment by tadfisher** [comment]
Somehow, removing this broke `tramp` from emacs-overlay. I have to manually run `M-x load-library tramp-autoloads` or anything depending on autoloaded tramp functions errors out with "no such function".

I do disable `package.el` as my site-lisp directory is managed by Nix. Is this configuration no longer recommended/supported? Is there a way to just engage package.el's autoload mechanism without allowing it to access the network or install packages?

**Comment by ParetoOptimalDev** [comment]
I also fully disable `package.el` since all of my emacs packages are installed via nix and noticed this change broke things for me.

>  Is there a way to just engage package.el's autoload mechanism without allowing it to access the network or install packages?

I'm interested in this as well.

**Comment by DamienCassou** [comment]
Did you manage to make this work @tadfisher and @ParetoOptimalDev? I have package.el disabled and would like autoloads of nix packages.

**Comment by ParetoOptimalDev** [comment]
@DamienCassou No. Having `(package-activate)` or `(package-activate-all)` also causes this warning for me:

```
⛔ Warning (package): Package org is activated too late.
The following files have already been loaded: ("/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-version" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-table" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-src" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-pcomplete" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-macs" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-macro" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-loaddefs" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-list" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-keys" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-footnote" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-fold" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-fold-core" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-faces" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-entities" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-cycle" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/org-compat" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ol" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/oc" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-tangle" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-table" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-ref" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-lob" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-exp" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-eval" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-emacs-lisp" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-core" "/nix/store/klfrbkb522ydq8ksna9ryj6lvhmsr6hj-emacs-packages-deps/share/emacs/site-lisp/elpa/org-9.7.24/ob-comint")
```

**Comment by bestlem** [comment]
Any progress on this.

If I don't use emacs package manager then you should turn it off by (setq package-enable-at-startup nil)

But then I got the autoload errors as @ParetoOptimalDev says - I get them on treemacs and lsp - which autoload thinmgs not from the main <package>.el file.

I had package-enable-at-startup but it was loading stuff and gave an error on another package.

The originbal comment at the top of this issue by @ttuegel is correct but the issue is that emacs should not be loading packages by package.el if you are using nix to load packages.

I must admit if I had seen this issue earlier I would not be using nix as straight.el and elpaca deal with this correctly.

I think this means that your emacs config is not reproduceable as doesn't it  now depend what is in elpa etc and not just what is in nix.

**Comment by xaltsc** [comment]
@bestlem Sorry to revive an old issue, but I have found that `(package-activate-all)` in `early-init.el` solves the issue.
