### ISSUE TITLE
Haskell: unable to decommit memory: Invalid argument"

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#18117]
## Issue description

ghc-pkg: unable to decommit memory: Invalid argument
ghc-pkg: unable to decommit memory: Invalid argument
Warning: haddock-interfaces: /nix/store/wl28b2dpilqqriwvq9x06g9l6vmgrpmm-network-interfacerequest-0.0.2/share/doc/x86_64-linux-ghc-8.0.1/network-interfacerequest-0.0.3/html/network-interfacerequest.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/wl28b2dpilqqriwvq9x06g9l6vmgrpmm-network-interfacerequest-0.0.2/share/doc/x86_64-linux-ghc-8.0.1/network-interfacerequest-0.0.3/html doesn't exist or isn't a directory
ghc-pkg: unable to decommit memory: Invalid argument
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Configuring tunder-0.1.0.0...
cabal: unable to decommit memory: Invalid argument

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by domenkozar** [comment]
dupes https://github.com/NixOS/nixpkgs/issues/18118
