### ISSUE TITLE
Haskell: "unable to decommit memory: Invalid argument"

### ISSUE THREAD

**Issue by obadz** [NixOS/nixpkgs#18118]
## Issue description

Post `staging` merge, lots of Haskell programs print the following errors:

```
ghc-pkg: unable to decommit memory: Invalid argument
cabal: unable to decommit memory: Invalid argument
```

Incidentally, it seemed that some Haskell builds were running out of memory (None left on Hydra as I restarted all of the them).

There's a GHC issue mentioning this problem along with a suggested patch: https://ghc.haskell.org/trac/ghc/ticket/12495

@peti, should we apply?

### Steps to reproduce

http://hydra.nixos.org/build/39371982/log/raw

**Comment by PierreR** [comment]
There are some information about this issue to grab from [the IRC channel.](https://botbot.me/freenode/nixos/)

Apparently the problem is not related to Haskell but to the version of `glibc` which is fairly recent for the default nixos kernel. So if you upgrade the kernel the error should disappear.

I haven't tested or try to upgrade the kernel but instead was hoping the issue would disappear with some recent nix-channel updates (the unstable channel). But so far it hasn't.  I still hope for a fix to come up in a near future.

**Comment by PierreR** [comment]
Well I probably misunderstood the messages from the IRC channel. Initially this happens to me on `nixos` only but it has just started to show up with `nixpkgs` in another linux distro after updating the nix channel:

```
> nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable 
```

**Comment by obadz** [comment]
Also see @ttuegel's post on nix-dev: http://lists.science.uu.nl/pipermail/nix-dev/2016-September/021556.html

Worked for me.

Still an issue given that hydra runs on 4.4.x…

**Comment by obadz** [comment]
@PierreR, the glibc, or binutils, or hardening flags could all be causing this but using kernel 4.7 does fix it.

**Comment by peti** [comment]
Personally, I'd rather configure the build with ` --disable-large-address-space` than patch the script. IMHO that's a cleaner solution.

Does anyone understand the implications of this setting, i.e. does it reduce performance in any significant way etc.?

**Comment by ttuegel** [comment]
> Does anyone understand the implications of this setting, i.e. does it reduce performance in any significant way etc.?

The idea is to reduce the number of system calls. With `--enable-large-address-space`, GHC `mmap`s a 1TB region of virtual memory and does its own allocations there. Disabling this feature will incur a small performance penalty when allocating.

GHC has a different implementation of `--enable-large-address-space` if it doesn't detect MADV_FREE, so I think forcibly disabling that check in the configure script is the right way to go. That way there is no performance penalty (even if it is small).

**Comment by peti** [comment]
> forcibly disabling that check in the configure script is the right way to go

OK. Does anyone have a patch ready that accomplishes this? The patch from https://ghc.haskell.org/trac/ghc/ticket/12495 goes a different route which doesn't feel ideal.
