### ISSUE TITLE
Telegram on Wayland doesnt use system cursor theme.

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#181176]
### Describe the bug
On Wayland (with QT_QPA_PLATFORM=wayland), Telegram doesn't use the system cursor theme.

### Steps To Reproduce
1. Open Wayland with QT_QPA_PLATFORM=wayland set
2. notice how the cursor doesn't use the system's cursor theme and instead uses a simple, small black cursor theme

### Expected behavior
Telegram on wayland should use the system's cursor theme.

### Screenshots
![Screenshot from 2022-07-11 20-22-13](https://user-images.githubusercontent.com/78878262/178387834-feb652ba-27fb-4c73-b954-41f904801f63.png)
![Screenshot from 2022-07-11 20-22-46](https://user-images.githubusercontent.com/78878262/178387838-17400847-0810-46be-bc2d-c4cc3417ab4a.png)
Here it's on wayland
![Screenshot from 2022-07-11 20-23-43](https://user-images.githubusercontent.com/78878262/178387886-34828b46-353d-46a3-b778-bdf3e5f28856.png)
![Screenshot from 2022-07-11 20-23-46](https://user-images.githubusercontent.com/78878262/178387890-e9dbfd44-d040-49d2-9391-15a7abf5d50e.png)
Here it's on Xwayland.

### Additional context
Also just noticed that it only renders like half the cursor or 75% of the cursor, but screenshots seem to make the cursor render correctly. 

### Notify maintainers
@oxalica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.10-zen1, NixOS, 22.11 (Raccoon), 22.11pre390948.5f43d8b088d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by iosmanthus** [comment]
Same issue is encountered in xorg + i3. I currently pinned `tdesktop` package to commit: 0c3bf3a5c3ab6be29138b88900c417660a284fbd to workaround this issue.

**Comment by Hentioe** [comment]
Contrary to you, I found this behavior in X11, everything works fine in Wayland.

**Comment by leiserfg** [comment]
The same happens in `awesome`, will be good to test it on kde/gnome maybe is something qt6 is using from the desktop?

**Comment by Zylanx** [comment]
Having the same issue under KDE with Wayland too.

**Comment by Zylanx** [comment]
Having the same issues under KDE with X11. Wayland works correctly however.

**Comment by lfdominguez** [comment]
Happens in `XMonad` too..

**Comment by berberman** [comment]
+1 for xmonad

**Comment by oxalica** [comment]
Sorry I'm not really maintaining tdesktop now. cc @NickCao, seems to be an issue of Qt6?

Personally, I doesn't have cursor issue on sway.

**Comment by NickCao** [comment]
Most likely an issue with Qt6, but I'm also at a loss what to do to fix this.

**Comment by m911t** [comment]
This still happens on gnome wayland, same as i reported on the original post.

**Comment by SamLukeYes** [comment]
I can reproduce it on gnome wayland.

**Comment by m911t** [comment]
Ok, so, this also affects other applications:
- mpv #198192
- obs-studio

**Comment by MartiniMoe** [comment]
Any news on this? Still facing this issue :(

**Comment by leiserfg** [comment]
I'm using qtile in x11 and hyprland in wayland and it's working fine in both.

**Comment by pearsche** [comment]
it's still an issue, almost opened another bug report lol
@leiserfg this affects apps running on wayland mode.

**Comment by almino** [comment]
It also happens to me on multiple machines.

**Comment by 9ary** [comment]
Dug into this a bit, I can't figure out what tries to load libXcursor yet, but:
- running telegram with `LD_DEBUG=libs` shows libXcursor being loaded; it also seems like it is in RUNPATH, but I can't see it with chrpath (most likely it's in the rpath of a dependency or something loaded by dlopen)
- telegram does not seem to call into libXcursor at all (according to ltrace), so it's probably the wrong place to look (unless it's being used as a fallback or something else)

For what it's worth, I can't repro this bug (on sway).

**Comment by 9ary** [comment]
By the way, for whoever this is still broken, it could simply be a configuration issue. Just for a sanity check, and to cross-check variables, please post the following information:
- Qt theme and platform theme in use
- whether the cursor is broken on eg file dialogs (if not using XDG portals, and especially if using a gtk-based platform theme)
- whether the cursor is broken on another qt6 application such as syncplay
- how you're configuring the cursor theme; if not using home-manager, do take a look at what it does and see whether you're missing something that would possibly fix it (https://github.com/nix-community/home-manager/blob/master/modules/config/home-cursor.nix)

**Comment by stereomato** [comment]
I don't have this issue anymore, but I do have issues on other applications such as mpv and xwayland games :/

**Comment by almino** [comment]
I also confirm the issue is gone. Cursors are working on Telegram.

**Comment by leiserfg** [comment]
I use nix as:
- nixos with wayland
- nixos with x11
- home-manager with wayland over debian 

and it does not happen to me in any of them, so I consider the issue gone a long time ago.
