### ISSUE TITLE
etherape crashes on start

### ISSUE THREAD

**Issue by rue-mogorman** [NixOS/nixpkgs#18129]
## Issue description

When I run etherape on my machine it complains I don't have permission to access eth0 but the app opens and seems fine.  When I rerun the app as root it immediately crashes with the following error 

```
# etherape

(etherape:28221): libglade-WARNING **: Could not load support for `gnome': libgnome.so: cannot open shared object file: No such file or directory

(etherape:28221): libglade-WARNING **: Could not load support for `canvas': libcanvas.so: cannot open shared object file: No such file or directory

(etherape:28221): libglade-WARNING **: unknown widget class 'GnomeMessageBox'

(etherape:28221): libglade-WARNING **: unknown widget class 'GnomeCanvas'

(etherape:28221): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(etherape:28221): Gtk-CRITICAL **: IA__gtk_style_set_background: assertion 'window != NULL' failed

(etherape:28221): GLib-GObject-WARNING **: invalid cast from 'GtkLabel' to 'GnomeCanvas'

(etherape:28221): GLib-GObject-WARNING **: invalid cast from 'GtkLabel' to 'GnomeCanvas'

(etherape:28221): GnomeCanvas-CRITICAL **: gnome_canvas_get_scroll_region: assertion 'GNOME_IS_CANVAS (canvas)' failed

(etherape:28221): GLib-GObject-WARNING **: invalid cast from 'GtkLabel' to 'GnomeCanvas'

(etherape:28221): GnomeCanvas-CRITICAL **: gnome_canvas_root: assertion 'GNOME_IS_CANVAS (canvas)' failed

(etherape:28221): GnomeCanvas-CRITICAL **: gnome_canvas_item_new: assertion 'GNOME_IS_CANVAS_GROUP (parent)' failed
**
ERROR:diagram.c:211:addref_canvas_obj: assertion failed: (obj)
Aborted
```
### Steps to reproduce

install etherape
run etherape
## Technical details

16.03.1210.9906378 (Emu)
nix-env (Nix) 1.11.2
"16.03.1210.9906378"
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by Gokul656** [comment]
When i try to open ehterape it is showing like this.
please help me.
(etherape:7094): libglade-WARNING **: Could not load support for `gnome': libgnome.so: cannot open shared object file: No such file or directory

(etherape:7094): libglade-WARNING **: unknown widget class 'GnomeCanvas'

(etherape:7094): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead
EtherApe-INFO: sctp protocol not supported
EtherApe-INFO: ddp protocol not supported
EtherApe-INFO: ddp protocol not supported
EtherApe-INFO: ddp protocol not supported
EtherApe-INFO: ddp protocol not supported

(etherape:7094): GLib-GObject-WARNING **: invalid cast from 'GtkLabel' to 'GnomeCanvas'

(etherape:7094): GnomeCanvas-CRITICAL **: gnome_canvas_root: assertion 'GNOME_IS_CANVAS (canvas)' failed

(etherape:7094): GnomeCanvas-CRITICAL **: gnome_canvas_item_new: assertion 'GNOME_IS_CANVAS_GROUP (parent)' failed
**
ERROR:diagram.c:250:addref_canvas_obj: assertion failed: (obj)
unexpected EOF in read_all()
critical: read_all() failed on control socket
Aborted

**Comment by hant0508** [comment]
Installation of `libgnomeui-0` solved the issue for me.

**Comment by peterhoeg** [comment]
EtherApe now works.
