### ISSUE TITLE
setuid-wrapper activationScript is not atomic

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#18124]
It's currently possible to cancel `nixos-rebuild` between deletion of previous setuid wrappers and population of new ones. And yes, I've been able to lock myself out of machine (almost, if I didn't have root ssh key).

Current implementation: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/setuid-wrappers.nix#L118-L120

Proposed implementation (see at the bottom of blog post): https://axialcorps.com/2013/07/03/atomically-replacing-files-and-directories/

**Comment by domenkozar** [comment]
@edolstra @shlevy so this was failing because it's ready a tmpfs upon install:

```
nixos/modules/installer/tools/nixos-install.sh:mount -t tmpfs -o "mode=0755" none $mountPoint/var/setuid-wrappers
```

So, if we want `/var/setuid-wrappers/` to be a tmpfs and a symlink that won't work.

My proposal would be to make `/var/setuid-wrappers/` a tmpfs and move conents to `/var/setuid-wrappers/bin` which could then be a symlink. This would be a backwards incompatible change, but we can fix it in nixpkgs and document it. 

Thoughts?

**Comment by shlevy** [comment]
I think it would be better to just not have /var/setuid-wrappers be a tmpfs since we're symlinking to a tmpfs anyway.

**Comment by edolstra** [comment]
@domenkozar Well, we can just change nixos-install not to create that tmpfs, right? Not sure why it's doing that anyway...

**Comment by domenkozar** [comment]
I'll have a PR ready soon, fixing a bug atm.
