### ISSUE TITLE
GnuPG: Tools in $out/libexec inaccessible

### ISSUE THREAD

**Issue by SohamG** [NixOS/nixpkgs#181315]
### Describe the bug

I don't know if this is a "bug" or what, but the GnuPG derivation produces a bunch of ["Helper Tools"](https://www.gnupg.org/documentation/manuals/gnupg/Helper-Tools.html#Helper-Tools) in the `$out/libexec` directory. These tools can be handy on the command line but they are essential lost because nix never symlinks from `$out/libexec/`

I encountered this when I tried to use `gpg-preset-passphrase` to cache my gpg key passphrase while my session was active.

### Steps To Reproduce
1. Have GnuPG installed
2. Attempt to use `gpg-preset-passphrase` or similar GnuPG Helper Tool
3. Notice said tool is not available

### Expected behavior
Ideally, GnuPG helper tools should be available to use.

### Notify maintainers
@fpletz 
@vrthra

**Comment by trofi** [comment]
I think `libexec` is not supposed to be in the `PATH`. Those should be internal to `gnupg` tools. Do you know other distributions that make it available in the `PATH`?

**Comment by SohamG** [comment]
@trofi I got here by trying to follow what the [Arch Wiki recommends for passphrase caching](https://wiki.archlinux.org/title/GnuPG#Configuration_2). They tell you to use `/usr/lib/something` to be fair. 

Secondly the GnuPG manual section on Helper Tools doesn't seem to mention them being internal use tools, rather provides examples and stuff on what to do with them (manual linked in original post). 

I agree that `libexec` is for internet stuff. I have no clue why the gnupg people decided to put those tools there....?

Lastly, the issue really arises when you need/want to use this and you have to fish it out of the store instead of a short `/usr/libexec/` path of a traditional distro. I feel its worth considering if nixos wants to expose these "helper tools" somehow

**Comment by trofi** [comment]
I wonder if asking gnupg upstream to also expose it via bin would work.

**Comment by Artturin** [comment]
Not a bug on our side 

Add /libexec to https://search.nixos.org/options?channel=22.05&show=environment.pathsToLink&from=0&size=50&sort=relevance&type=packages&query=Pathsto and they'll be available in 
/run/current-system/sw/libexec
