### ISSUE TITLE
openmpi : libtool .la files are not stripped and cause dependency issue

### ISSUE THREAD

**Issue by adevress** [NixOS/nixpkgs#18147]
## Issue description
openmpi nix package do not strip the *.la files coming from libtool.

This generate dependency issues for other project using libtool and nix, due to libtool trying to link against the dependencies of openmpi itself ( e.g libibverbs ) when it should not.

This issue has been encountered here #17937

It is a general good practice to strip libtool *.la file in package. 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by FRidh** [comment]
closed with #18148
