### ISSUE TITLE
emacs: subdirs.el isn't being loaded properly from load-path

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#18146]
## Issue description

Emacs uses `load-path` to determine file paths from where `.el` and `.elc` files should be loaded.

We create a `subdirs.el` which when stuck into `/run/current-system/sw/share/emacs/site-lisp` should mean sub directories are added to `load-path`, however although the file is there, subdirectories are not added.

Here is one report:
https://github.com/djcb/mu/issues/663#issue-106055324
### Steps to reproduce

1) install emacs
2) install `nixos.mu`
3) in an emacs-lisp-mode buffer run: `(require 'mu4e)` which throws an error about mu4e not being found

If you manually add the mu4e directory it works:
`(add-to-list 'load-path "/run/current-system/sw/share/emacs/site-lisp/mu4e")`
## Technical details
- NixOS: 16.09.git.eb9a6d0M (Flounder)
- Nix: nix-env (Nix) 1.11.3
- nixpkgs: 16.09pre89269.8512747

cc:  @chaoflow @lovek323 @peti @the-kenny @jwiegley @DamienCassou

**Comment by DamienCassou** [comment]
I think the nix way is to use build an Emacs derivation with mu4e inside. I suggest you read http://hydra.nixos.org/build/39510439/download/2/nixos/index.html#module-services-emacs.

**Comment by peterhoeg** [comment]
Although what you suggest looks really neat and I'm definitely going to give that a go, I'm sure others will be confused (as I was) by the presence of ```subdirs.el``` and sub-directories not being loaded as this deviates from normal behavior.

My own workaround was just to add the sub-directory to the load path and everything is peachy.

**Comment by peterhoeg** [comment]
@DamienCassou, I just tried briefly using the configuration described in the manual and I can confirm that subdirectories are still not added properly. ```mu4e``` goes into a sub-directory in the -deps derivation, but it is still not in the load path.

```nix
{ pkgs ? import <nixpkgs> {} }: 

let
  myEmacs = pkgs.lib.overrideDerivation (pkgs.emacs25pre.override {
    withGTK3 = true;
    withGTK2 = false;
  }) (attrs: {
    postInstall = attrs.postInstall + ''
      rm $out/share/applications/emacs.desktop
    '';
  });
  emacsWithPackages = (pkgs.emacsPackagesNgGen myEmacs).emacsWithPackages;

in 
  emacsWithPackages (epkgs: (with epkgs.melpaStablePackages; [
  ]) ++ (with epkgs.melpaPackages; [
  ]) ++ (with epkgs.elpaPackages; [
  ]) ++ (with pkgs; [
    mu
    notmuch
  ]))
```

**Comment by DamienCassou** [comment]
@peterhoeg if `load-path` includes `/nix/store/xxx-emacs-packages-deps/share/emacs/site-lisp`, everything is fine. Just make sure

- the site file is loaded (don't start Emacs with `-Q` or `--no-site-file`)
- `(package-initialize)` is executed

If I put your Nix expression in a `peter.nix` and do the following, everything works:

1. `$ nix-build peter.nix`
2. `$ ./result/bin/emacs --no-init-file`
3. `(require notmuch)`
4. `M-x notmuch`

**Comment by peterhoeg** [comment]
The problem was ```-Q```.

**Comment by ahmedtd** [comment]
This still seems to occur on unstable.

@DamienCassou, your example works because `notmuch` helpfully places all of its files directly in `/nix/store/xxx-emacs-packages-deps/share/emacs/site-lisp`.

`mu` places its files in `/nix/store/xxx-emacs-packages-deps/share/emacs/site-lisp/mu4e`, which doesn't get added to `load-path`.

**Comment by DamienCassou** [comment]
On April 1, 2017 11:57:05 PM GMT+02:00, Taahir Ahmed <notifications@github.com> wrote:
>@DamienCassou, your example works because `notmuch` helpfully places
>all of its files directly in
>`/nix/store/xxx-emacs-packages-deps/share/emacs/site-lisp`.

I'm not using Nix anymore and won't be able to help you.
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
