### ISSUE TITLE
nixosTests.signal-desktop is failing on master

### ISSUE THREAD

**Issue by kilianar** [NixOS/nixpkgs#181463]
### Describe the bug
The nixos test for signal-desktop [has been failing for a week](https://hydra.nixos.org/build/183151865) with the following error
```
Exception: command `su - alice -c 'sqlite3 ~/.config/Signal/sql/db.sqlite .databases'` unexpectedly succeeded
```
According to a comment in the source code, trying to access the encrypted signal database with `sqlite` should fail, because only `SQLCipher` should be able to read it:
https://github.com/NixOS/nixpkgs/blob/294bba4d99d2909b5f8bdeeb6bcb0436279333a9/nixos/tests/signal-desktop.nix#L61-L64

### Steps To Reproduce
1. run `nix build .#nixosTests.signal-desktop` on master

### Additional context
The [change set](https://hydra.nixos.org/api/scmdiff?rev2=b39924fc7764c08ae3b51beef9a3518c414cdb7d&branch=&rev1=a5c867d9fe9e4380452628e8f171c26b69fa9d3d&type=git&uri=https%3A%2F%2Fgithub.com%2FNixOS%2Fnixpkgs.git) between the last succeeding and the first failing build:
- doesn't include changes to `signal-desktop`
- does include a version bump of `sqlite`

So the issue might be caused by some changes to `sqlite`.
 
### Notify maintainers
@flokli @primeos

**Comment by flokli** [comment]
@kilianar can you try a bisect between these two changesets?

**Comment by kilianar** [comment]
I tried bisecting the issue, but running the test (`nix build .nixosTests.signal-desktop`) requires mass rebuilds for most of the commits, so at least on my machine it's not feasible to find the faulty commit in a timely manner.

**Comment by primeos** [comment]
I just had a brief look (sorry for the delay, I don't have as much time anymore).
Luckily the encryption still seems to work.
`/home/alice/.config/Signal/sql/db.sqlite: data` is fine and I also dumped the content to the log with `hexdump` and it looks like random data / garbage (-> encrypted).

However, the behaviour of `sqlite` seems to have indeed changed... :o
The command succeeds now and outputs just this:
```
(finished: must succeed: su - alice -c 'sqlite3 ~/.config/Signal/sql/db.sqlite .databases', in 0.11 seconds)
main: /home/alice/.config/Signal/sql/db.sqlite r/w
```

Theoretically we could just remove that command but for extra security I'd find it best to replace it with something that still works. However, it seems best to simply replace `.databases` with `.tables` (or (full)schema):
```
machine: must fail: su - alice -c 'sqlite3 ~/.config/Signal/sql/db.sqlite .tables'
machine # [   47.036720] su[1178]: Successful su for alice by root
machine # [   47.041049] su[1178]: pam_unix(su:session): session opened for user alice(uid=1000) by (uid=0)
machine # Error: file is not a database
machine # [   47.116070] su[1178]: pam_unix(su:session): session closed for user alice
(finished: must fail: su - alice -c 'sqlite3 ~/.config/Signal/sql/db.sqlite .tables', in 0.12 seconds)
```

I'll send in a quick PR.
Thanks for the report and pinging me! :)
