### ISSUE TITLE
NixOS Stage 1 boot broken for build-vm

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#18159]
## Issue description
```nixos-rebuild build-vm``` on latest master (21282246208b7591d1431beef7fc6c8e7affef0d) yields this:

![qemu i7pc _001](https://cloud.githubusercontent.com/assets/133602/18129770/8788e0c6-6f8c-11e6-90e5-916784a7f18e.png)

Basically, the boot hangs with the message ```/init: line 95: can't open '/dev/null'```. I guess I could be brave and try this on a real system (possibly it only affects the VM), but I figured it post this issue anyway :-)

It works like it should just a few days ago: 898edb0fbc3f23b24b7e28bad0cdd3e57ad5dcc7.

## Steps to reproduce
* Enter latest nixpkgs.git working tree (i.e. 21282246208b7591d1431beef7fc6c8e7affef0d)
* ```nixos-rebuild -I nixpkgs=. build-vm```
* ```./result/bin/run-*-vm -m 4096```

## Technical details

* System: NixOS 16.09pre 64-bit

**Comment by bjornfor** [comment]
CC @abbradar (has touched stage-1 in the affected commit range).

**Comment by abbradar** [comment]
Ouch, I think this is me indeed. Investigating...

**Comment by abbradar** [comment]
This happens because we force-override filesystems for VMs. Because we now set special filesystems in common `fileSystems` attribute set, they are overriden and no special filesystems are mounted. It's a miracle it goes through stage 1 ~_^.

I guess I'll fix this by adding `boot.specialFileSystems` and moving them there...

**Comment by bjornfor** [comment]
@abbradar: That was quick! Thank you. (I've confirmed the fix works.)

**Comment by edolstra** [comment]
IMHO, if certain filesystems need special treatment, it's nicer to have an option in the filesystem, similar to the `neededForBoot` flag.

And it's not clear what the semantics of `specialFileSystems` is. It seems to implicitly be "those filesystems that should be mounted in a QEMU VM anyway".

**Comment by edolstra** [comment]
Although, since the option is marked as internal, I guess it's not a huge problem.

**Comment by abbradar** [comment]
@edolstra First implementation did just what you have described (only the option was named `early`). I would be glad to return to this, however I have no idea how to do so with this override taking place. Any ideas?
