### ISSUE TITLE
No GSettings schemas are installed on the system (pkgs.onlykey)

### ISSUE THREAD

**Issue by Lerrrtaste** [NixOS/nixpkgs#181500]
### Describe the bug
The onlykey package crashes when a file dialog should open ("Save as" / "Choose file")

### Steps To Reproduce
1. Install onlykey
2. Go to the Firmware / Backup Tab
3. Click "Choose file" or "Save as"

### Expected behavior
A select file window should open, not crash.

### Screenshots
![onlykey1](https://user-images.githubusercontent.com/22920627/179063013-a4b7c074-025b-4008-abc5-35cbc22a9aed.png)

![onlykey2](https://user-images.githubusercontent.com/22920627/179063056-41ce144c-8818-4e33-9d68-d10657dc311c.png)

### Additional context
I have nautilus and LF installed, which is successfully used by other programs (firefox etc).
Already tried installing gsettings-desktop-schemas and setting XDG_DATA_DIRS as described [here](https://github.com/NixOS/nixpkgs/issues/72282#issuecomment-549651957).
I use dwm and no Gnome and no Gnome Packages except nautilus.
I would guess it needs to use wrapGAppsHook as nativeBuildInputs but I have no idea how/where to add that.

### Notify maintainers

@kalbasit 

### Metadata
[username@host:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05.1627.4aceab3cadf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(username): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bjornfor** [comment]
> I would guess it needs to use wrapGAppsHook as nativeBuildInputs but I have no idea how/where to add that.

Have you cloned nixpkgs? Did you find the nix file where the package recipe is defined?

**Comment by Lerrrtaste** [comment]
> > I would guess it needs to use wrapGAppsHook as nativeBuildInputs but I have no idea how/where to add that.
> 
> Have you cloned nixpkgs? Did you find the nix file where the package recipe is defined?

Yes, it seems to be generated with node2nix which I do not really understand. It doesn't look like other .nix files. According to the [wiki](https://nixos.wiki/wiki/Packaging/Quirks_and_Caveats#GLib-GIO-Message:_Using_the_.27memory.27_GSettings_backend._Your_settings_will_not_be_saved_or_shared_with), wrapGAppsHook can be added like in [this pr](https://github.com/NixOS/nixpkgs/pull/24617/files). But I can't find `buildInputs`, the `preFixup`hook or even just the `mkDerivation` part where it is supposed to be added.

**Comment by milahu** [comment]
the important parts of default.nix are

```nix
{
  script = writeShellScript "${onlykey.packageName}-starter-${onlykey.version}" ''
    ${node_webkit}/bin/nw ${onlykey}/lib/node_modules/${onlykey.packageName}/build
  '';
}
```

and


```nix
runCommand "${onlykey.packageName}-${onlykey.version}" { } ''
  mkdir -p $out/bin
  ln -s ${script} $out/bin/onlykey
''
```

runCommand
https://ryantm.github.io/nixpkgs/builders/trivial-builders/#trivial-builder-runCommand

so you could replace the `runCommand` call with the usual

```nix
stdenv.mkDerivation {
  pname = "...";
  version = "...";
  nativeBuildInputs = [ wrapGAppsHook ];
  dontUnpack = true;
  buildPhase = "ln -s ${script} $out/bin/onlykey";
}
```
