### ISSUE TITLE
Unzip fails to unpack bigger zips

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#181572]
### Describe the bug
It looks like that nixpkgs is also effected by the same bug here. https://gitlab.alpinelinux.org/alpine/aports/-/issues/11986
When you unpack, sometimes some big zips it extracts the file content as symlink.

I am on Mac, with the native unzip it works

### Steps To Reproduce
See https://gitlab.alpinelinux.org/alpine/aports/-/issues/11986

### Expected behavior
It works

### Metadata

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.0.0, macOS 13.0`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"darwin, home-manager, nix-darwin-modules, nixpkgs"`
 - channels(shyim): `"darwin, home-manager, nix-darwin-modules, nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

**Comment by FliegendeWurst** [comment]
This was fixed in #181574, thank you.
