### ISSUE TITLE
Cannot compile Linux 4.6 on stable channel. Backport needed

### ISSUE THREAD

**Issue by taku0** [NixOS/nixpkgs#18157]
## Issue description

Linux kernel 4.6 on the stable channel cannot be compiled due to an outdated patch.
The patch is removed from the master by the commit 1e806458dc4fbca4d2c67e93f0933d4193b5666b but it is not removed from the  stable channel. Please backport the commit.

**Comment by domenkozar** [comment]
Cc @globin
