### ISSUE TITLE
Video DownloadHelper Companion App

### ISSUE THREAD

**Issue by Quantenzitrone** [NixOS/nixpkgs#181510]
**Project description**
vdhcoapp provides the [Video DownloadHelper](https://downloadhelper.net/) browser add-on with:
- file writing API features that are not available from the browser
- temporary file name generation
- launching default application on a data file
- a build of the [ffmpeg](http://ffmpeg.org/) video converter

**Metadata**

* homepage URL: https://www.downloadhelper.net/ or https://github.com/mi-g/vdhcoapp
* source URL: https://github.com/mi-g/vdhcoapp/tree/v1.6.3  is that the right url?
* license: GNU General Public License v2.0
* platforms: linux, maybe darwin and unix
the package is available for mac if that is a requirement for darwin

**Comment by WolfangAukang** [comment]
Yes, as @Shawn8901 indicated, I created this on a NUR and it is working fine. Let's move the discussion to the other issue.
