### ISSUE TITLE
Sanoid Template variable not functioning

### ISSUE THREAD

**Issue by djohnson1865** [NixOS/nixpkgs#181561]
### Describe the bug
services.sanoid.datasets.<name>.useTemplate does not work as expected.

### Steps To Reproduce
1. Within configuration.nix set something along the lines of
```
services.sanoid = {
  enable = true;
  templates.backup = {
    autoprune = true;
    autosnap = false;
    hourly = 24;
    daily = 30;
    monthly = 6;
  };
  datasets.tank = {
    useTemplate = ["backup"];
  };
};
```
2. Build config and check the built sanoid.conf file in the nix store. Within the config file use_template is not set on the appropriate directories.

### Expected behavior
use_template in sanoid.conf should be set using the useTemplate variable for datasets in question (or the alias should be removed from the package/documentation)

### Additional context
services.sanoid.datasets.<name>.use_template works as expected.

Tried on multiple machines with different zfs datasets just to sanity check and got the same result. Fairly new to nix, so definitely let me know if I'm just missing something. Couldn't tell what the issue was looking at the service derivation for sanoid. 

### Notify maintainers
@lopsided98 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05.1627.4aceab3cadf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lopsided98** [comment]
I think this is either a bug `mkAliasDefinitions` or in the way it is used. Sanoid is the only user of this function in the entirety of nixpkgs, so I can't check other examples.

cc @ju1m
