### ISSUE TITLE
Geogebra source tarball is only available for a few weeks after release

### ISSUE THREAD

**Issue by moyamo** [NixOS/nixpkgs#18165]
## Issue description

The [Geogebra download server](http://download.geogebra.org/installers/5.0/) only serves the 5 most recent version of Geogebra. This means that after a few weeks nix will be unable to build Geogebra as the source tarball will not be available..
## Possible solution

Is it possible for nix to host a copy of the Geogebra tarball?

**Comment by joachifm** [comment]
My understanding is that packages that are part of a release will have their sources mirrored at tarballs.nixos.org (if permitted by their license).

**Comment by moyamo** [comment]
Hmm, geogebra is partially non-free. I guess this is causing the problem. The license allows redistribution for non-commercial purposes which should not be a problem for nixpkgs. Is there any way to force tarballs.nixos.org to mirror the tarball?

**Comment by moyamo** [comment]
However the restriction is on "The GeoGebra installers, web services and various copyright materials, graphics and resources . . ." I'm not sure what counts as an "installer."

**Comment by joachifm** [comment]
I see now that the geogebra package is explicitly excluded from Hydra builds. The geogebra license is marked as unfree, which I expect would exclude it from the Hydra jobset anyway. I'm afraid this means the package won't be covered by the automatic tarball mirroring mechanism.

You could ask somebody with access to the S3 infrastructure to do a manual upload to the mirror, though I'm unsure if that's really a good use of their (very limited) time.

More realistically, you can 1) advocate for changes that would alllow the package to be included in the automatic mirroring set; 2) petition upstream to provide long-term urls; 3) be vigilant about updating the version in Nixpkgs.

I'm sure this isn't the answer you're looking for. When upstream refuses to host older versions and also decide to make mirroring difficult users suffer.
