### ISSUE TITLE
NixOS rendered unbootable after upgrading to latest nixos-unstable

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nixpkgs#181649]
### Describe the bug
After upgrading to the latest `nixpkgs-unstable` my system was rendered unbootable, I was dropped into an emergency shell and had to `chroot` into the system. 

### Steps To Reproduce
Steps to reproduce the behavior (probably not feasible as I don't have a clue where this issue comes from), here is the flake rev that caused trouble
https://gitlab.com/mangoiv/dotfiles/-/commit/3df4bffdaeccfbb8b4d0c56b778461572e3d5dcc

### Expected behavior
NixOS should boot

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.10, NixOS, 22.11 (Raccoon), 22.11.20220711.f904e35`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
Log?

**Comment by MangoIV** [comment]
what log do you need exactly?

**Comment by MangoIV** [comment]
I will close this issue as I don't have this problem anymore and nobody seems to have run into this either
