### ISSUE TITLE
cannot render: echo "\ue0b0 \ue0a0"

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [NixOS/nixpkgs#18167]
## Issue description

 after installing powerline-fonts, I put in terminal:
$ echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"
And I can render everything except "\ue0b0 \ue0a0"
## relevant part of /etc/nixos/configuration.nix

fonts = {
enableFontDir = true;
enableGhostscriptFonts = true;
fonts = with pkgs; [
corefonts
inconsolata
ubuntu_font_family
unifont
terminus_font
powerline-fonts
];
};
## Technical details
- System: NixOS: 16.03.1242.c5cbda2 (Emu)
- Nix version: 1.11.2

**Comment by Profpatsch** [comment]
(triage) is this still an issue?
