### ISSUE TITLE
services.xserver.xkbOptions doesn't take effect

### ISSUE THREAD

**Issue by f--t** [NixOS/nixpkgs#18173]
## Issue description
`services.xserver.xkbOptions` don't take effect in KDE5, Xmonad, and Gnome3. Requires running 
```
$ setxkbmap
``` 
manually after login would however fix the issue. 

### Steps to reproduce
None

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09pre90254.6b20d5b (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.3

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
16.09pre90254.6b20d5b

**Comment by laMudri** [comment]
You mean `services.xserver.xkbOptions`? There is no `nixos` option group.

I'm successfully using `services.xserver.inputClassSections` on the same version (with a few desktop environments), and I don't see why `services.xserver.xkbOptions` should be much different.

**Comment by tohl** [comment]
services.xserver.xkbOptions doesn't work for me either, on unstable

**Comment by f--t** [comment]
No longer can reproduce the issue on my machine, might have been an upstream bug in Xorg.

**Comment by Kharacternyk** [comment]
I'm experiencing the same issue on the 20.09 release. Running `setxkbmap` manually is required for the options to take effect. Can we have this issue reopened?

**Comment by sasoiliev** [comment]
I just upgraded my system to 21.05 (`21.05.2734.74d017edb67 (Okapi)`) and I'm facing this issue.

My X.org version is 1.20.11, I checked `/var/log/X.0.log` for anything related with no luck. The XKB options are present in the log file but they don't seem to take any effect in my session:

```
❯ setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+bg(phonetic):2+inet(evdev)"	};
	xkb_geometry  { include "pc(pc104)"	};
};
```
