### ISSUE TITLE
haskellPackages.Yi marked as broken but builds.

### ISSUE THREAD

**Issue by guaraqe** [NixOS/nixpkgs#18188]
Yi is currently marked as broken. The last issue I see about this is this one: https://github.com/NixOS/nixpkgs/issues/14967 , where in the end it was supposedly solved.

I just tested here (NixOS 16.03, nixpkgs-unstable) and besides a huge number of warnings, it builds and works. Somebody can confirm?

**Comment by dezgeg** [comment]
cc @peti
