### ISSUE TITLE
flake check mentions cabal2nix in its error message 

### ISSUE THREAD

**Issue by aleeusgr** [NixOS/nixpkgs#181855]
I am writing a unit test for the experimental cli.
I need to run HelloWorld.hs.
running `nix flake check` produces: 
`error: a 'aarch64-linux' with features {} is required to build cabal2nix, but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
`
Do you have any thoughts on debuggin this error?
Thank you

I use this flake:
```
# https://magnus.therning.org/2022-03-13-simple-nix-flake-for-haskell-development.html 
{
  inputs = {
    #nixpkgs.url = "github:nixos/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      with nixpkgs.legacyPackages.${system};
      let
        t = lib.trivial;
        hl = haskell.lib;

        name = "project-name";

        project = devTools: # [1]
          let addBuildTools = (t.flip hl.addBuildTools) devTools;
          in haskellPackages.developPackage {
            root = lib.sourceFilesBySuffices ./. [ ".cabal" ".hs" ];
            name = name;
            returnShellEnv = !(devTools == [ ]); # [2]

            modifier = (t.flip t.pipe) [
              addBuildTools
              hl.dontHaddock
              hl.enableStaticLibraries
              hl.justStaticExecutables
              hl.disableLibraryProfiling
              hl.disableExecutableProfiling
            ];
          };

      in {
        packages.pkg = project [ ]; # [3]

        defaultPackage = self.packages.${system}.pkg;

        #warning: flake output attribute 'devShell' is deprecated; use 'devShells.<system>.default' instead
        devShell = project (with haskellPackages; [ # [4]
          cabal-fmt
          cabal-install
          haskell-language-server
          hlint
        ]);
      });
}
```

**Comment by sternenseemann** [comment]
`developPackage` uses `cabal2nix` during evaluation via ifd, so to evalute `packages.aarch64-linux` requires building a derivation. Since your setup uses native compilation for this, it is impossible to evaluate this attribute path on `x86_64-linux`.

At least this would be my guess, I don't know what `nix flake check` does exactly. As I see it, this is not a bug, but a case of holding it wrong.

**Comment by aleeusgr** [comment]
What's ifd?

**Comment by maralorn** [comment]
That‘s right. `nix flake check` is incompatible with ifd. Nothing cabal2nix can do about this.

**Comment by turion** [comment]
> As I see it, this is not a bug, but a case of holding it wrong.

How do I "hold it right"? What can I use instead of `developPackage` that yields a similar result?

**Comment by maralorn** [comment]
`nix flake check` evaluates all attributes of a flake (at least all which are in one of the well known namespaces of nix flakes) to make sure they can evaluate and that they have the right type.

I guess the correct but not quite satisfying solution would be to not check attributes for foreign plattforms (which use ifd).
I am not sure if this is a matter of holding it wrong or nix purposefully making live hard for IFD users.

Another solution would be to configure remote builders for every system. Or like sterni said avoiding ifd.

Yet another simple solution would be to only add attributes for x86_64 to flake in the first place.

**Comment by turion** [comment]
> `nix flake check` evaluates all attributes of a flake

> Yet another simple solution would be to only add attributes for x86_64 to flake in the first place.

Is it possible to tell `nix flake check` to only check these attributes? I tried `nix flake check --system x86_64-linux` and `nix flake check --arg system x86_64-linux`, but that didn't work.
