### ISSUE TITLE
NixOS Live CD spams console with audit messages

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#18181]
## Issue description
This is a low impact issue, but it does give a bad impression of NixOS (IMHO):

![qemu_009](https://cloud.githubusercontent.com/assets/133602/18160520/2e510c66-702e-11e6-9e7e-c6ce493b7a0f.png)

I can think of a few ways to improve this:

1. Change console log level
2. Remove that audit thing: https://github.com/NixOS/nixpkgs/issues/16590#issuecomment-238052210
2. Boot directly into the desktop environment (why aren't we doing that already?). (Won't fix it for the "minimal" (non-graphical) live CDs though.)

Thoughts?

### Steps to reproduce
```
$ cd nixpkgs/nixos/
$ nix-build -A config.system.build.isoImage -I nixos-config=modules/installer/cd-dvd/installation-cd-graphical-kde.nix
$ qemu-system-x86_64 -cdrom ./result/iso/nixos-16.09.git.e446b9f-x86_64-linux.iso
```

## Technical details

* System: NixOS 16.09pre (master branch as of today: e446b9f1b1354bd7bd026c4d5dd81904a0d57a4d)

**Comment by rasendubi** [comment]
Relevant: https://github.com/NixOS/nixpkgs/pull/17916

**Comment by dezgeg** [comment]
Audit is now off by default in master (#17916). I think the firewall can still spam the console though...
