### ISSUE TITLE
Move key-binder, bars, compositors and alike out of window-managers

### ISSUE THREAD

**Issue by Anachron** [NixOS/nixpkgs#18180]
## Issue description

sxhkd is a keybinding-manager, not a window-manager. A window-manager can use this key-binder to manage its functions, but does not depend on it.

compton is a compositor, not a window-manager. Lemonbar, yabar and dzen2 are bars to display information, not required to be bound to window-managers and don't depend on any.

I suggest to put these applications in a new folder like compositors, bars, key-binder and alike.
### Steps to reproduce
- none
## Technical details
- none

**Comment by Profpatsch** [comment]
Would you like to prepare a patch? Otherwise I’m gonna close.
