### ISSUE TITLE
@volar/vue-language-server

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#181842]
**Project description**
A language server for vue and nuxt projects which is used for web development.

**Metadata**

* homepage URL: https://www.npmjs.com/package/@volar/vue-language-server
* source URL: https://github.com/johnsoncodehk/volar
* license: mit
* platforms: all

**Comment by re-kaptcha** [comment]
Updates?

**Comment by Alexnortung** [comment]
@re-kaptcha  I don't think anyone has added it

**Comment by Alexnortung** [comment]
This has been added https://github.com/NixOS/nixpkgs/blob/3b7deba8c8a241eca2805d5f7e0aa26948795d1a/pkgs/development/node-packages/node-packages.json#L23C4-L23C30

**Comment by towry** [comment]
Hi, this package is deprecated. 
[@volar/vue-language-server](https://www.npmjs.com/package/@volar/vue-language-server)
