### ISSUE TITLE
Wrong license for simple-rlp

### ISSUE THREAD

**Issue by hegjon** [NixOS/nixpkgs#181932]
https://github.com/NixOS/nixpkgs/blob/8f485713f5e6b6883a9b6959afa98688360a3ecb/pkgs/development/python-modules/simple-rlp/default.nix#L20

simple-rlp is not MIT license since they include this line in their license file:
```
This software cannot be used by state organizations.
```

Might be related to https://github.com/SamuelHaidu/simple-rlp/issues/1

**Comment by hegjon** [comment]
@prusnak

**Comment by prusnak** [comment]
Let's give it a few days to see how https://github.com/SamuelHaidu/simple-rlp/issues/1 develops

**Comment by hegjon** [comment]
Upstream released a new version with standard MIT license

**Comment by prusnak** [comment]
Fixed via https://github.com/NixOS/nixpkgs/pull/191496
