### ISSUE TITLE
Can't add Intl (icu) support to nodejs.

### ISSUE THREAD

**Issue by despairblue** [NixOS/nixpkgs#18191]
## Issue description

I tried to build nodejs with Intl/icu support. 

I tried to let it download icu during the configure phase which failed. I suppose network requests are being blocked because they are side effects.

I also tried importing icu and using this one in configure, but that also failed because of weird configure flags that where generated (`shared-icu`)
#### Download ICU

Use [this commit](https://github.com/despairblue/nixpkgs/commit/be36046e76e2100c3ce6beded3280979272abdd0). This [branch](https://github.com/despairblue/nixpkgs/commits/nodejs-icu)
#### System ICU

Use [this commit](https://github.com/despairblue/nixpkgs/commit/cd13d939bf446882b29a80f13f2de3ceffbde4af). This [branch](https://github.com/despairblue/nixpkgs/tree/nodejs-icu2).
## Technical details
- System: 16.09pre89269.8512747 (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "16.09pre89269.8512747"

**Comment by Profpatsch** [comment]
Sorry that there was no answer. Were you able to solve your problem?

**Comment by despairblue** [comment]
Nope, I gave up and did it in a docker container instead, and eventually I went to another OS :/

Feel free to close this or leave it open if ICU is something you want to have added to the node package :)

**Comment by Profpatsch** [comment]
Thanks for the quick response. NixOS got a lot cooler in the meantime, maybe it’s worth a second try? :)

**Comment by despairblue** [comment]
I'll look into it :)
