### ISSUE TITLE
Dive now failing to build on Darwin

### ISSUE THREAD

**Issue by khaled** [NixOS/nixpkgs#181991]
### Describe the bug

Dive now fails to build on darwin.  This was working up until maybe a week ago.

### Steps To Reproduce
https://hydra.nixos.org/build/183982999

### Additional context
I poked at the vendor code that is failing.  Looks like there some failed symbol references that look like:

```
//go:linkname libc_getgroups libc_getgroups
//go:cgo_import_dynamic libc_getgroups getgroups "/usr/lib/libSystem.B.dylib"
```

I saw some ramblings about libSystem updates, iirc.  Is this related?

### Notify maintainers
@marsam 
@spacekookie 
@SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.5.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(xxyy): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by marsam** [comment]
Looks like dive doesn't build with go 1.18 yet. You can fix it with:
```diff
--- i/pkgs/top-level/all-packages.nix
+++ w/pkgs/top-level/all-packages.nix
@@ -15733,7 +15733,9 @@ with pkgs;
       binutils = binutils;
     };
 
-  dive = callPackage ../development/tools/dive { };
+  dive = callPackage ../development/tools/dive {
+    buildGoModule = buildGo117Module;
+  };
 
   doclifter = callPackage ../development/tools/misc/doclifter { };
 
```

**Comment by SuperSandro2000** [comment]
dive needs to update its vendoring, not reverting back to golang 1.17. Please don't pin programs needlessly to go 1.17 just because of this.

**Comment by SuperSandro2000** [comment]
> Looks like dive doesn't build with go 1.18 yet.

That is only true for aarch64-darwin, not any other platform.
