### ISSUE TITLE
explainshell

### ISSUE THREAD

**Issue by babaric-dev** [NixOS/nixpkgs#181905]
explainshell: match command-line arguments to their help text

* homepage URL: https://github.com/idank/explainshell
* source URL:
* license: gpl-3.0
* platforms: unix, linux

**Comment by elikoga** [comment]
looking into this

**Comment by babaric-dev** [comment]
thanks!

**Comment by edrex** [comment]
reopen?

**Comment by dzmitry-lahoda** [comment]
please reopen. explainshell is used by bash-ide extension for visual studio code.
