### ISSUE TITLE
xfce4-terminal fails to start (nixos-unstable)

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#18204]
## Issue description

I cannot start xfce4-terminal anymore. After running a `git bisect`, I believe the incriminating commit to be d020caa.

When called from xmonad via dmenu, xfce4-terminal fails silently.

When called from xterm, it outputs:
```xfce4-terminal: symbol lookup error: /run/opengl-driver/lib/libEGL.so.1: undefined symbol: wl_proxy_marshaled_constructor_versioned```

I'm not quite sure what to do to describe this more. It might have to do with what happened around here:
https://github.com/NixOS/nixpkgs/tree/d020caa5b2eca90ea051403fbb4c52b99ee071b9/pkgs/desktops/xfce/core

People of interest: @vcunat @globin

**Comment by domenkozar** [comment]
Maybe https://github.com/NixOS/nixpkgs/commit/49d59ce0adf8397778ec3b9a36a149a66a013c88 will help?

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixpkgs/issues/16779
