### ISSUE TITLE
Jabref SIGSEGV

### ISSUE THREAD

**Issue by fleimgruber** [NixOS/nixpkgs#182065]
### Describe the bug
Jabref segfaults on start

### Steps To Reproduce
1. Start Jabref

### Expected behavior
Jabref starts up.

### Additional context
The output from starting `jabref` on CLI follows. Please let me know if you need to see the contents of the log file or the core dump:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=14678, tid=14679
#
# JRE version:  (16.0.2+7) (build )
# Java VM: OpenJDK 64-Bit Server VM (16.0.2+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump will be written. Default location: Core dumps may be processed with "/nix/store/iirqa1lqni18mcaii3g1l5s15jxwz17a-systemd-250.4/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/fps/core.14678)
#
# An error report file with more information is saved as:
# /home/fps/hs_err_pid14678.log
#
#
Aborted (core dumped)
```

### Notify maintainers
@gebner @linsui 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
- host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05.1711.c06d5fa9c60`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.8.1`
- channels(fps): `""`
- channels(root): `"nixos-22.05"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by linsui** [comment]
I guess you installed it from 22.05? It does crash so I fixed it in https://github.com/NixOS/nixpkgs/pull/162593. This fixed version is only available in unstable channel.

**Comment by fleimgruber** [comment]
> I guess you installed it from 22.05?

Correct, see also my nix-info.

> It does crash so I fixed it in https://github.com/NixOS/nixpkgs/pull/162593. This fixed version is only available in unstable channel.

Could this be reasonably backported to 22.05?

**Comment by linsui** [comment]
> Could this be reasonably backported to 22.05?

I guess so. You can open a PR.

**Comment by fleimgruber** [comment]
> I guess so. You can open a PR.

Thanks for confirming, will take a shot at it.

**Comment by smancill** [comment]
This can be closed, then, right?
