### ISSUE TITLE
restic: Use ExecStopPost instead of ExecStartPost for the backupCleanupCommand?

### ISSUE THREAD

**Issue by DeskworkTrickster** [NixOS/nixpkgs#182089]
Wouldn't it make sense to use `ExecStopPost` instead of `ExecStartPost` for the `restic` `backupCleanupCommand`?

That way the `backupCleanupCommand` can also run when the backup service failed for some reason.

@otavio

**Comment by otavio** [comment]
It does make sense. Could you prepare a PR?

**Comment by DeskworkTrickster** [comment]
Thanks for the fast answer.
Since I'm pretty new to NixOS, I can try. :)

Is it simply changing `postStart` to `postStop` here?
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/backup/restic.nix#L315

**Comment by otavio** [comment]
Yes, it'd use in all cases.

**Comment by otavio** [comment]
Yes. PR rules need to be followed.

**Comment by otavio** [comment]
No worries. You can use the nixpkgs clone to test in your machine. Also restic has regression tests.

**Comment by DeskworkTrickster** [comment]
Sorry, I'm too busy right now and this is pretty low on my priority list.
So I think I won't do that.
Maybe at some point in the future ...
