### ISSUE TITLE
sway wrapper is not available

### ISSUE THREAD

**Issue by syphoxy** [NixOS/nixpkgs#182034]
# Background

I am trying to use `programs.sway.extraSessionCommands` but it appears that the wrapper script that those commands are written to does not exist in the final package.

I'm opening this ticket to confirm whether I've correctly identified the problem and talk about potential paths forward. As it stands, there's an option available to sway users that does not work.

If my conclusion below is correct, there are at least two paths we can take:

1. the wrapper is named `sway-wrapper` or similar and the `sway` binary remains unchanged.
2. the wrapper is named `sway` and the binary is installed as `.sway-wrapped` or similar.

# Investigation

_Warning: I am still very new to Nix and NixOS so I might be wrong about my interpretation below._

As far as I can tell, this is where the wrapper is written.

https://github.com/NixOS/nixpkgs/blob/08e93dbc3765047da5cef623ca98150e2e6ebd82/pkgs/applications/window-managers/sway/wrapper.nix#L20

And this is where the sway binary is written.

https://github.com/NixOS/nixpkgs/blob/08e93dbc3765047da5cef623ca98150e2e6ebd82/pkgs/applications/window-managers/sway/wrapper.nix#L52

In my system, `sway` is a binary.

``` console
$ file $(readlink $(which sway))
/nix/store/ha0y3nnsn1gir4kin64fs1pg24y52s1y-sway-1.7/bin/sway: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/scd5n7xsn0hh0lvhhnycr9gx0h8xfzsl-glibc-2.34-210/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, with debug_info, not stripped
```

# Conclusion

I'm not absolutely certain about this but it appears they're both written to `$out/bin/sway`, thus the binary clobbers the wrapper.

# Side note regarding GTK wrapper

It's unclear to me whether the gtk wrapper is being installed despite the above. I'm not really sure I understand what the gtk wrapper is so it's hard to confirm whether it's successfully being installed.

**Comment by Artturin** [comment]
we have binary wrappers now so open `/nix/store/ha0y3nnsn1gir4kin64fs1pg24y52s1y-sway-1.7/bin/sway` in vim and you can see the wrapper flags used to create it
