### ISSUE TITLE
UT2004 is limited to i686

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#18213]
Per the [expression for the UT2004 demo](https://github.com/NixOS/nixpkgs/blob/88c9f8b574ead01e32c5ee5228679723343cd52c/pkgs/games/ut2004demo/default.nix#L30), `ut2004demo` can only be installed on 32-bits systems. Is this still correct? It's a rather old expression, and given that other 32-bits software can be installed on 64-bits NixOS just fine, I'm not sure whether this needs to be changed.

**Comment by FRidh** [comment]
`nix-shell -p pkgsi686Linux.ut2004demo`
I think there was another attribute for `i686` as well, but I am not sure about that.

**Comment by FRidh** [comment]
this should be documented actually

**Comment by dezgeg** [comment]
Or the expression could be patched to transparently install the 32-bit version. Like this does (I think):
````
 4670   gcc-arm-embedded-4_7 = callPackage_i686 ../development/compilers/gcc-arm-embedded {
 4671     version = "4.7-2013q3-20130916";
 4672     releaseType = "update";
 4673     sha256 = "1bd9bi9q80xn2rpy0rn1vvj70rh15kb7dmah0qs4q2rv78fqj40d";
 4674   };
````

**Comment by joepie91** [comment]
> I think there was another attribute for i686 as well, but I am not sure about that.

You might be refering to `callPackage_i686` there?

**Comment by FRidh** [comment]
I thought there was also something called `pkgs_i686` without the `Linux` part but I guess I am wrong with that. In any case, the solution @dezgeg proposes looks like a good one?

**Comment by vcunat** [comment]
Does the package work actually? I'm trying to test it, but it seems to be downloading forever.

**Comment by vcunat** [comment]
OK, it seems to play fine.
