### ISSUE TITLE
Waydroid Can Break NixOS Including all Previus Generations. 

### ISSUE THREAD

**Issue by FedX-sudo** [NixOS/nixpkgs#182279]
### Describe the bug
I was attempting to fix an issue on my laptop where Waydroid was not booting, but as Waydroid was re-downloading the LineageOS image, I suddenly find myself in a Systemd panic screen. I attempt to reboot into a previous generation, but every generation gets me the same panic screen. After looking through journalctl logs, the only error I can find that would cause a full panic is this: `Failed to mount /var/lib/waydroid/rootfs/vendor.` Sorry I can't be more descriptive, this happened incredibly sudden. 

### Steps To Reproduce
Steps to reproduce the behavior (I don't know how repeatable this bug is because I have taken these steps with no issue in the past):
1. Install Waydroid
2. Run `sudo rm -rf ~/.local/share/waydroid /var/lib/waydroid`
3. Run `sudo waydroid init -f`

### Expected behavior
Waydroid image downloads normaly. 

### Notify maintainers
@CajuM 

### Metadata
(Note, this may not accurate because I am running this in Systemd emergency mode)

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
system: "x86_64-linux", multi-user? no, version: nix-env (Nix) 2.10.3, channels(root): "nixos, nixpkgs", channels(fedx): "nixpkgs", nixpkgs: /root/.nix-defexpr/channels/nixpkgs
```

**Comment by FedX-sudo** [comment]
Ok, I figured out why I was unable to boot, I am unsure what caused it to break, however. When Waydroid first installs, it adds the following to `hardware-configuration.nix`: 
```
234567891011121314151617  fileSystems."/var/lib/waydroid/rootfs" =
    { device = "/var/lib/waydroid/images/system.img";
      fsType = "ext4";
      options = [ "loop" ];
    };

  fileSystems."/var/lib/waydroid/rootfs/vendor" =
    { device = "/var/lib/waydroid/images/vendor.img";
      fsType = "ext4";
      options = [ "loop" ];
    };

  fileSystems."/var/lib/waydroid/data" =
    { device = "/home/fedx/.local/share/waydroid/data";
      fsType = "none";
      options = [ "bind" ];
    };
```
When I disabled Waydroid those lines remained, but that could be because I am using flakes and my `hardware-configuration.nix` is not located in `/etc/nixos/`. I was able to get my laptop booting by modifying `fstab` directly. 

I am currently wondering if there is something we can restructure to mitigate this issue because this is the first time NixOS has truly broken on me.

**Comment by CajuM** [comment]
Ok, how do you generate `hardware-configuration.nix` in your set-up? Did you install waydroid before running `nixos-generate-config`?

**Comment by FedX-sudo** [comment]
I never really touch my `hardware-configuration.nix` so I assume I generated it from the `nixos-generate-config` at initial install...

**Comment by CajuM** [comment]
I'm not sure if this is a bug with NixOS, we could put a warning on the wiki to avoid installing waydroid before installing NixOS? But then again, any extra mounts before `nixos-generate-config` would do the same thing.

**Comment by FedX-sudo** [comment]
True, after I realized that was the issue, I was simply wondering if there was a way to mitigate the issue...
