### ISSUE TITLE
8pk0rb4d3a09wb7klpdy9rdhrx0cx2lh-python3.10-awslambdaric-2.0.0.drv fails on x64

### ISSUE THREAD

**Issue by sebastien** [NixOS/nixpkgs#182298]
1. build python3.10-awslambdaric on Nix 26fe7618c7efbbfe28db9a52a21fb87e67ebaf06 (nixos-22.05-small 2022-07-21)

### Build log

https://gist.github.com/91de4b430eab437250046a037d86d2d9

### Additional context

One unit test is failing, maybe it's a pytest change?

### Notify maintainers

@zowoq 

### Metadata

Note that I'm running Nix through a build system that checks out a specific commit of Nix, and I'm not sure the output below matches what is actually used (ie, the channel and nixpkgs).

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.11-200.fc36.x86_64, Fedora Linux, 36 (Workstation Edition)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(spierre): `"nixpkgs-21.11pre310022.14b0f20fa1f, home-manager"`
 - nixpkgs: `/home/spierre/.nix-defexpr/channels/nixpkgs`

```

**Comment by zowoq** [comment]
Don't know why you've tagged me for this issue?
