### ISSUE TITLE
hqplayer-desktop: binary version no longer exist

### ISSUE THREAD

**Issue by anttisoikkeli** [NixOS/nixpkgs#182467]
This refers to a version of hqplayer-desktop that doesn't exist anymore on Signalyst's servers:

https://github.com/NixOS/nixpkgs/blob/a65b5b3f5504b8b89c196aba733bdf2b0bd13c16/pkgs/applications/audio/hqplayer-desktop/default.nix#L24

The whole fc34 path has disappeared. Latest package can be found from: https://www.signalyst.eu/bins/hqplayer/fc36/

I would also check hqplayerd -package as well to make sure that both hqplayerd and hqplayer-desktop are referring to latest packages and be compatible.

**Comment by FliegendeWurst** [comment]
Fixed in #230019
