### ISSUE TITLE
kmymoney fails to build

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#182499]
### Steps To Reproduce
1. `$ nix-build '<nixpkgs>' -A kmymoney`

### Build log
https://gist.github.com/aidalgol/f19c931b1f46e9f957c39a7a555f953b
(Errors on lines [6327](https://gist.github.com/aidalgol/f19c931b1f46e9f957c39a7a555f953b#file-gistfile1-txt-L6327=) and [6331](https://gist.github.com/aidalgol/f19c931b1f46e9f957c39a7a555f953b#file-gistfile1-txt-L6327=))

### Notify maintainers

No maintainers listed.  @roberth last modified this package a year ago.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev
copying path '/nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05.20220714.c06d5fa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by roberth** [comment]
Seems to be a Qt related build failure.

I don't use or maintain this package; my commit was a trivial treewide technicality.

@alyssais wrote the last fix. Maybe she's interested?

**Comment by das-g** [comment]
https://invent.kde.org/office/kmymoney/-/commit/265d4dc3d1dc8592ec1122aa04bfb7d431a43d5d (after resolving a trivial merge conflict) seems to fix this **if** one additionally changes `KMYMONEY_DEPRECATED` to `KMM_MYMONEY_DEPRECATED`.

(Before creating a PR, I'm going to try whether just changing `DEPRECATED` to `KMM_MYMONEY_DEPRECATED` also works or whether the changes to the imports are also needed.)

**Comment by das-g** [comment]
> (Before creating a PR, I'm going to try whether just changing `DEPRECATED` to `KMM_MYMONEY_DEPRECATED` also works or whether the changes to the imports are also needed.)

That _does_ indeed work, but I can't seem to find where `KMM_MYMONEY_DEPRECATED` is defined, so I have _no idea_ what the effect is (other that it gets the software to compile and run).

**Comment by das-g** [comment]
KMyMoney 5.1.3 (which will include https://invent.kde.org/office/kmymoney/-/commit/265d4dc3d1dc8592ec1122aa04bfb7d431a43d5d) will be released the coming weekend, so I guess we can just wait for that.

**Comment by aidalgol** [comment]
I just had a go at building 5.1.3, and the `postInstall` phase fails because there is `$out/share/kmymoney/weboob/kmymoneyweboob.py` does not exist.  It seems that weboob has been renamed to "woob" since KMyMoney 5.1.1.

**Comment by das-g** [comment]
Any help in getting #183973 ready and working would be appreciated.
