### ISSUE TITLE
Add a way to filter trusted Certificate Authorities

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#18242]
## Issue description

There are ways to add to CAs, but not to remove any from the default generated cacert.
### Steps to reproduce

see:
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/ca.nix
https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/misc/cacert/default.nix
## Technical details
- System: 16.09pre90208.f19c961 (Flounder)
- Nix version: nix-env (Nix) 1.11.3
- Nixpkgs version: 16.09pre90208.f19c961

**Comment by wkral** [comment]
Seems like this has been addressed in: 0d59fc1 this issue can probably be closed.

**Comment by abathur** [comment]
Closing per comment above that this is likely addressed.
