### ISSUE TITLE
nix-shell: cabal2nix: cannot create environment with a newer version of `brick`

### ISSUE THREAD

**Issue by listx** [NixOS/nixpkgs#18240]
## Issue description

`nix-env -qaP -A nixpkgs.haskellPackages` shows this:

```
nixpkgs.haskellPackages.brick_0_4_1                                  brick-0.4.1
nixpkgs.haskellPackages.brick                                        brick-0.8
```

I need to install the brick-0.8 version, because my code with the earlier 0.4.1 version will break. I cannot install the newer 0.8 version with `nix-shell`.

I am only running into this issue now, because before running nix-shell never had this problem with trying to install brick_0_4_1.

### Steps to reproduce

Here is a sample cabal file:

```
-- Initial foofoo.cabal generated by cabal init.  For further
-- documentation, see http://haskell.org/cabal/users-guide/

name:                foofoo
version:             0.1.0.0
-- synopsis:
-- description:
license:             BSD3
license-file:        LICENSE
author:              Linus Arver
maintainer:          linusarver@gmail.com
-- copyright:
-- category:
build-type:          Simple
extra-source-files:  ChangeLog.md
cabal-version:       >=1.10

executable foofoo
  main-is:             Main.hs
  -- other-modules:
  -- other-extensions:
  build-depends:       base >=4.9 && <4.10, brick > 0.7
  -- hs-source-dirs:
  default-language:    Haskell2010
```

Create the `shell.nix` with `cabal2nix --shell .`. It should say something like this:

```
{ nixpkgs ? import <nixpkgs> {}, compiler ? "default" }:

let

  inherit (nixpkgs) pkgs;

  f = { mkDerivation, base, brick, stdenv }:
      mkDerivation {
        pname = "foofoo";
        version = "0.1.0.0";
        src = ./.;
        isLibrary = false;
        isExecutable = true;
        executableHaskellDepends = [ base brick ];
        license = stdenv.lib.licenses.bsd3;
      };

  haskellPackages = if compiler == "default"
                       then pkgs.haskellPackages
                       else pkgs.haskell.packages.${compiler};

  drv = haskellPackages.callPackage f {};

in

  if pkgs.lib.inNixShell then drv.env else drv
```

Running `nix-shell` now results in nix trying to download the brick_0_4_1 version, even though I state that I want `brick > 0.7` in my cabal file.

## Technical details

* System: NixOS: `16.03.1224.5237768 (Emu)`
* Nix version: run `nix-env (Nix) 1.11.2`
* Nixpkgs version: `"16.03.1224.5237768"`

cabal2nix version: cabal2nix 2.0.1

**Comment by teh** [comment]
Your cabal file says `brick > 7`, not `brick > 0.7` - is that intentional?

**Comment by listx** [comment]
@teh Oops, no it was not. I meant `brick > 0.7`. Still, the behavior is the same.

**Comment by listx** [comment]
@peti Ping?

**Comment by listx** [comment]
So, it looks like I missed this discussion: http://lists.science.uu.nl/pipermail/nix-dev/2016-June/020642.html . So basically all haskellPackages are tracking the LTS release, which is why it's not using the latest "brick" package. Closing for now as this is the intended behavior.

**Comment by peti** [comment]
Also, note that Nix doesn't resolve these kind of dependencies. Builds are functions that take their dependencies as arguments and whatever version of `brick` is passed to that function will be used for the build. In other words, the generated expression has no way of specifying any particular version of `brick`. This decision is made at the place that call that function.
