### ISSUE TITLE
SDL + OpenGL is broken

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#18247]
```
X11 driver not configured with OpenGL
```

Reproduced 100 % during startup in multiple games, on master and 16.09. See initial discussion at https://github.com/NixOS/nixpkgs/commit/297008b959

**Comment by rycee** [comment]
I got SDL to recognize OpenGL support by using `mesa_glu` instead of `mesa_noglu` as a build input:
```patch
diff --git a/pkgs/development/libraries/SDL/default.nix b/pkgs/development/libraries/SDL/default.nix
index de699e2..ca097b8 100644
--- a/pkgs/development/libraries/SDL/default.nix
+++ b/pkgs/development/libraries/SDL/default.nix
@@ -1,5 +1,5 @@
 { stdenv, fetchurl, fetchpatch, pkgconfig, audiofile, libcap
-, openglSupport ? false, mesa_noglu
+, openglSupport ? false, mesa_glu
 , alsaSupport ? true, alsaLib
 , x11Support ? true, libXext, libICE, libXrandr
 , pulseaudioSupport ? true, libpulseaudio
@@ -32,7 +32,7 @@ stdenv.mkDerivation rec {
     optionals x11Support [ libXext libICE libXrandr ] ++
     optional alsaSupport alsaLib ++
     optional stdenv.isLinux libcap ++
-    optional openglSupport mesa_noglu ++
+    optional openglSupport mesa_glu ++
     optional pulseaudioSupport libpulseaudio ++
     optional stdenv.isDarwin Cocoa;
```
Then at least `nixpkgs.blackshades` started OK.

**Comment by vcunat** [comment]
`teeworlds` as well. Amazingly fast resolution. I assume you want to push it yourself?

**Comment by rycee** [comment]
Sorry, I'm having to step or for a few hours so I'd appreciate if you could update the package.

On September 3, 2016 12:37:24 PM GMT+02:00, "Vladimír Čunát" <notifications@github.com> wrote:
>`teeworlds` as well. Amazingly fast resolution. I assume you want to
>push it yourself?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/issues/18247#issuecomment-244539408

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vcunat** [comment]
@rycee: OK. I'll push it with your authorship ;-)

**Comment by rycee** [comment]
Thanks!
