### ISSUE TITLE
kotatogram-desktop fails to start while loading shared libraries

### ISSUE THREAD

**Issue by kotatsuyaki** [NixOS/nixpkgs#182426]
### Description

After updating my system flake from nixpkgs commit `0906692` to `a174de1`, `kotatogram-desktop` started to fail with the following error.

```console
$ kotatogram-desktop
/run/current-system/sw/bin/kotatogram-desktop: error while loading shared libraries: libpipewire-0.3.so.0: cannot open shared object file: No such file or directory
```

### Additional context

- This happens on both Plasma Wayland and Gnome X11.
- I was able to start `kotatogram-desktop` after adding the following missing library paths to `LD_LIBRARY_PATH`:
  - `pipewire.lib`
  - `xorg.libXdamage`
  - `xorg.libXrandr`
  - `xorg.libXtst`

### Notify maintainers

@ilya-fedin

### Metadata

The channel shown below is no longer relevant, since I'm using flake and don't have any channels configured on the system.

```console
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos-21.11.334797.6979c0e49bb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by NickCao** [comment]
The same happened to tdesktop days ago: https://github.com/NixOS/nixpkgs/pull/182138

**Comment by vcunat** [comment]
See PR #182437

**Comment by vcunat** [comment]
Ah OK, so maybe you'd like a different resolution than I whipped up.  Feel free to choose any.

**Comment by ilya-fedin** [comment]
The right fix would be moving all tg_owt buildInputs to propagatedBuildInputs I guess as it's a static library
