### ISSUE TITLE
Enable udevSupport in SDL

### ISSUE THREAD

**Issue by leiserfg** [NixOS/nixpkgs#182558]
### Describe the bug
SDL2 is being compiled with `udevSupport` set to false, and that causes problems with some controllers.

### Expected behavior
SDL links to udev so the programs work as they should

### Notify maintainers
@cpages

**Comment by leiserfg** [comment]
Going through the history of all-packages I see it was enabled years ago, but I can't see why/when was it disabled.

**Comment by leiserfg** [comment]
@OPNA2608  I'm linking you cause it seems like @cpages  is inactive and I see you have recent commits merged in that file, sorry if I shouldn't.

**Comment by leiserfg** [comment]
@ashley
@ivar
@joshuafern
@sbruder
It's not my intention to spam, so sorry if that's what I'm achieving but this bug affects yuzu and I don't know what to do to solve it, I tried overriding SDL2 locally but it requires me to build a lot of apps because they depend on ffmpeg that also depends on SDL2.

**Comment by leiserfg** [comment]
> odes supported by my 8BitDo Pro 2 and all worked except the Nintendo Switch mode, which also doesn’t work

I also own an 8BitDo Pro 2  and it works well in switch mode via Bluetooth but without motion (that's the  issue I'm facing) and yuzu on other systems that use udev work fine (my laptop with manjaro) with motion.
Try setting   `hardware.steam-hardware.enable = true;` y your nixos config and that should make the steam mode work (again, without motion).
I will try forcing the SDL override and come back if I make it work.

**Comment by leiserfg** [comment]
![image](https://user-images.githubusercontent.com/2947276/180841762-c85a6eb6-30eb-4997-801d-0bece27304b9.png)
After applying the override, the controller works fully (including motion control as shown in the picture), but it does not with Bluetooth.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/182851

**Comment by leiserfg** [comment]
After unpairing and pairing my controller again (via bluetoth) and with the udev flag and the steam udev rules, the controller works in that mode too (including motion control), so now with the PR from @Artturin  it should work for everybody. Will it be backported to the stable release of nixos?

**Comment by Artturin** [comment]
backported
