### ISSUE TITLE
openconnect doesn't set default route

### ISSUE THREAD

**Issue by rqcy** [NixOS/nixpkgs#18253]
## Issue description

It seems that openconnect doesn't set default route through tun0.

### Steps to reproduce

Start openconnect with the following options:

openconnect --authgroup=MyGroup --user=auser https://server.local
route 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.03.1271.546618c (Emu)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.2

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

nix-instantiate --eval openconnect -A lib.nixpkgsVersion
error: getting status of ‘/root/openconnect’: No such file or directory

**Comment by puffnfresh** [comment]
@rqcy I have this problem. What was your fix?

**Comment by rqcy** [comment]
> @rqcy I have this problem. What was your fix?

Hmm, I hove no access to that computer at the moment and I don't
remember any more.  Just guessing... perhaps some dependency was missing
or I have used vpnc instead.  Good luck!
