### ISSUE TITLE
`maim` broken since f7414e2b3ac69f220e19b1ef9ddfe8d64650c5ca (potentially more)

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#182568]
### Describe the bug

`maim` errors with "/nix/store/y6w2r99psf1cznq179kyq2mzk1zyh6xn-maim-5.7.4/bin/maim: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory" (or equivalent) since f7414e2b3ac69f220e19b1ef9ddfe8d64650c5ca which was a cmake/rpath related change.

As the commit was a treewide operation, there might actually be much more packages affected, though `maim` happened to be the first one reported in the inofficial discord.

### Steps To Reproduce
1. `nix run github:nixos/nixpkgs/f7414e2b3ac69f220e19b1ef9ddfe8d64650c5ca#maim -- --version`

### Expected behavior

Maim reports its version, and is generally usable

### Notify maintainers

@knedlsepp for being the author of the offending commit, sadly maim has no maintainers listed on its own.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.9, NixOS, 22.11 (Raccoon), 22.11.20220714.4a01ca3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.0pre20220715_59764eb`
 - channels(nmelzer): `""`
 - channels(root): `"nixos-21.05.4044.e74894146a4"`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by Kranzes** [comment]
Will be fixed by https://github.com/NixOS/nixpkgs/pull/182506
