### ISSUE TITLE
Bottles: vulkan/dxvk doesnt work on runners 

### ISSUE THREAD

**Issue by m911t** [NixOS/nixpkgs#182539]
### Describe the bug
Vulkan/dxvk doesnt work on bottles. Vulkan is working correctly on my laptop as vkcube, vulkaninfo and the game im trying to run on bottles (that i ran thru wineWowPackages.staging + dxvk install from the official archive file) run perfectly.

### Steps To Reproduce
1. Open bottles
2. Create a bottle for gaming
3. Install a game.
4. Watch the "directx error" pop up.

Also, the dxvk log files say that the "VK_KHR_surface" extension failed to load.

### Expected behavior
DXVK/Vulkan should work on bottles.

### Screenshots
![image](https://user-images.githubusercontent.com/78878262/180592453-a12d5059-871a-46b9-8e4f-70209b9bda07.png)

### Notify maintainers
@psydvl @SCOTT-HAMILTON
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev
copying path '/nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.12-zen1, NixOS, 22.11 (Raccoon), 22.11pre393241.a65b5b3f550`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by phaitonican** [comment]
Having the exact same Issue on 22.11pre393800.e494a908e88 (Raccoon)

**Comment by Blisto91** [comment]
If `VK_KHR_surface` fails then there is a driver issue. Vulkan wont be able to draw anything to screen without it.

**Comment by m911t** [comment]
update: using the system wine doesn't fix dxvk either. only running thru the command line does.
@Blisto91 As i said, running it thru wine on the terminal does work, so something in the bottles thing is not working right.

**Comment by SuperSamus** [comment]
I found the cause: these hardcoded paths right there: https://github.com/bottlesdevs/Bottles/blob/main/bottles/backend/utils/vulkan.py#L26
With this extra lines in `postPatch`, Vulkan will work:
```
    substituteInPlace src/backend/utils/vulkan.py \
      --replace '/usr' '/run/opengl-driver'
```
(`bottles` instead of `src` in the newer versions)

I'm not sure if this is the best way to solve it, though.

**Comment by m911t** [comment]
!!! nice find!
