### ISSUE TITLE
bottles: Add an override for the wine package used

### ISSUE THREAD

**Issue by m911t** [NixOS/nixpkgs#182540]
### Describe the bug
An override for the wine package would be nice to have, as I currently installed wineWowPackages.staging but can't use it on bottles.

### Notify maintainers
@psydvl @SCOTT-HAMILTON 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev
copying path '/nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.12-zen1, NixOS, 22.11 (Raccoon), 22.11pre393241.a65b5b3f550`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by phaitonican** [comment]
same

**Comment by psydvl** [comment]
Watch this link to see when PR will merged into your channel
https://nixpk.gs/pr-tracker.html?pr=182850
After that you can replace `bottles` with
``` nix
bottles.override { wineWow = wineWowPackages.staging }
```

**Comment by m911t** [comment]
very nice! thanks.
