### ISSUE TITLE
Update echidna from 1.7.3 to 2.0.2

### ISSUE THREAD

**Issue by NanezX** [NixOS/nixpkgs#182500]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 1.7.3
desired version: 2.0.2

###### Notify maintainers

maintainers: 
- @arcz

###### Note for maintainers

Please tag this issue in your PR.

**Comment by arcz** [comment]
waiting for 0.50.0 release of https://github.com/ethereum/hevm

**Comment by arcz** [comment]
@NanezX I fixed echidna.

**Comment by NanezX** [comment]
> @NanezX I fixed echidna.

Lovely. Thanks you so much for you effort.
