### ISSUE TITLE
GLMakie.jl and GLFW.jl fails to run due to missing libs (Julia)

### ISSUE THREAD

**Issue by joshniemela** [NixOS/nixpkgs#182583]
### Describe the bug
Both `GLMakie.jl` and `GLFW.jl` return `ERROR: GLFWError (API_UNAVAILABLE): GLX: No GLXFBConfigs returned`

### Steps To Reproduce
1. Install julia-bin
2. Enter Julia REPL
3. `import Pkg; Pkg.add("GLFW"); using GLFW; GLFW.Window()`

### Expected behavior
Julia should open an empty window.

### Screenshots
Result:
![image](https://user-images.githubusercontent.com/88747315/180607651-146116d5-1c5d-460a-b357-593c3e76301c.png)
Expected result:
![image](https://user-images.githubusercontent.com/88747315/180608081-310c848a-853d-4ef6-b06c-6be790152b1c.png)

### Additional context
`steam-run julia` fixes the problem.

### Notify maintainers
@rob @garrison @raskin

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.12-zen1, NixOS, 22.11 (Raccoon), 22.11.20220720.614a842`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```
### Stack trace:
[strace.log](https://github.com/NixOS/nixpkgs/files/9173901/strace.log)

**Comment by wentasah** [comment]
I solve this with `nix-ld` and a Julia wrapper script. 
See https://github.com/wentasah/nix-conf/blob/34ffe8c9d550a112edfe1984ae6a50405c9286cf/pkgs/julia-wrapper/default.nix
and https://github.com/wentasah/nix-conf/blob/34ffe8c9d550a112edfe1984ae6a50405c9286cf/steelpick/configuration.nix#L192.
You would need to add OpenGL libraries to the list of libraries in the wrapper script.

**Comment by joshniemela** [comment]
> I solve this with `nix-ld` and a Julia wrapper script. See https://github.com/wentasah/nix-conf/blob/34ffe8c9d550a112edfe1984ae6a50405c9286cf/pkgs/julia-wrapper/default.nix and https://github.com/wentasah/nix-conf/blob/34ffe8c9d550a112edfe1984ae6a50405c9286cf/steelpick/configuration.nix#L192. You would need to add OpenGL libraries to the list of libraries in the wrapper script.

How would I go on doing that? Tried adding opengl to the libs and seemingly nothing changed.

**Comment by wentasah** [comment]
Hmm, the trick with `nix-ld` allowed me to use `Plots.jl` under NixOS, but it seems that GLFW.jl needs something more.

I can get the black window from your example shown when I run `julia` as:

    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/run/opengl-driver/lib julia

However, I'm not sure whether it is safe to make this by default. I'd need to understand more about how Julia loads shared libraries to its address space.

**Comment by joshniemela** [comment]
That does seem to work, any recommendations as to how to write that into the wrapper with the rest of the libs?

**Comment by wentasah** [comment]
I ended up with the following wrapper (see [here](https://github.com/wentasah/nix-conf/blob/9981b24de36a320bbb344b795230e14f9ccae016/pkgs/julia-wrapper/default.nix)):
```nix
writeShellScriptBin "julia" ''
  # Set variables for nix-ld
  export NIX_LD=${stdenv.cc.libc}/lib/ld-linux-x86-64.so.2
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH''${LD_LIBRARY_PATH:+:}/run/opengl-driver/lib"
  exec ${julia}/bin/julia "$@"
''
```
For some reason, the libraries and their locations in `NIX_LD_LIBRARY_PATH` variable are no longer needed. Perhaps, newer Julia versions already contain those libraries and Julia can find them well. However, `NIX_LD` is still needed for Plots.jl. I don't fully understand why, but it works.

**Comment by joshniemela** [comment]
Alright, thank you for the solution.
