### ISSUE TITLE
lighttpd is missing the directory listing mod

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#182663]
### Describe the bug

lighttpd is missing the [directory listing mod](https://doc.lighttpd.net/lighttpd2/mod_dirlist.html)

### Steps To Reproduce

Config:

```
services.lighttpd.enable = true;
services.lighttpd.modsEnabled = [ "mod_dirlist" ];
```

```
andy@arksm ~> sudo nixos-rebuild switch
building Nix...
building the system configuration...
error:
       Failed assertions:
       - One (or more) modules in services.lighttpd.enableModules are
       unrecognized.

       Known modules: mod_rewrite mod_redirect mod_alias mod_access mod_auth mod_status mod_simple_vhost mod_evhost mod_userdir mod_secdownload mod_fastcgi mod_proxy mod_cgi mod_ssi mod_compress mod_usertrack mod_expire mod_rrdtool mod_accesslog mod_authn_dbi mod_authn_file mod_authn_gssapi mod_authn_ldap mod_authn_mysql mod_authn_pam mod_authn_sasl mod_cml mod_deflate mod_evasive mod_extforward mod_flv_streaming mod_geoip mod_magnet mod_mysql_vhost mod_openssl mod_scgi mod_setenv mod_trigger_b4_dl mod_uploadprogress mod_vhostdb mod_webdav mod_wstunnel

       services.lighttpd.enableModules: mod_dirlist mod_accesslog
(use '--show-trace' to show detailed location information)
```

### Expected behavior

I expected lighttpd to be enabled and for the directory listing mod to be enabled which makes file system directories be listed when accessing the httpd web page.

### Notify maintainers

@bjornfor @brecht

### Metadata

> Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

sorry I am reporting this on a different computer than the affected one

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by bjornfor** [comment]
If you're thinking of the `mod_dirlisting` (note the `ing` suffix) it is (supposed) to be enabled by default: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/lighttpd/default.nix#L15-L16.

However, I wonder if the eval time asserting of known modules is worth it. Should we just drop it? What kind of error does lighttpd produce if we try to load a missing module?

**Comment by bjornfor** [comment]
Reading https://redmine.lighttpd.net/projects/1/wiki/Server_modulesDetails again, I guess we can/should add those three modules (`mod_indexfile`, `mod_dirlisting`, `mod_staticfile`) to the `knownModules` list, since that'd be less confusing for users.

**Comment by bjornfor** [comment]
>However, I wonder if the eval time asserting of known modules is worth it. Should we just drop it?

lighttpd modules must be loaded in a given order, so I think it makes sense for NixOS to handle that ordering.

**Comment by bjornfor** [comment]
> lighttpd is missing the [directory listing mod](https://doc.lighttpd.net/lighttpd2/mod_dirlist.html)

That looks like a lighttpd 2.x thing, whereas nixpkgs only has lighttpd 1.x.

**Comment by andrewrk** [comment]
I got this working last night after a lot of troubleshooting. For future users, `mod_dirlisting` is indeed enabled by default, but you still must configure it to be activated with `extraConfig`:

```
services.lighttpd.extraConfig = ''
    dir-listing.activate = "enable"
''
```

Thanks for the help @bjornfor
