### ISSUE TITLE
Packaging request: hatch

### ISSUE THREAD

**Issue by pyjamafish** [NixOS/nixpkgs#182726]
**Project description**
Hatch is a modern, extensible Python project manager.

**Metadata**
* homepage URL: https://hatch.pypa.io/latest/
* source URL: https://github.com/pypa/hatch
* license: MIT
* platforms: unix, linux, darwin

**Comment by onny** [comment]
Isn't this already packaged as `hatchling`? The projects look similar https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=hatchling
