### ISSUE TITLE
Setting `nixos.config.networking.enable`: attribute ‘networking’ missing

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#18271]
## Issue description / reproduce steps

I have 

```nix
let
  nixos = (import <nixos> {});
  wlanPkgs = pkgs:
    if nixos.config.networking.wireless.enable then
      [
        # some pkgs
      ]
    else [];
in
pkgs: [
    # some pkgs
] ++ (wlanPkgs pkgs)
```

in my `configuration.nix` setup. Today, after a channel update to current nixos-unstable, I get this error:

```
sudo nixos-rebuild -Q switch
building Nix...
building the system configuration...
error: attribute ‘networking’ missing, at /nix/store/njjlcj5knbsbsldy1n3khfskib1cldld-nixos/pkgs/networkingPackages.nix:4:8
(use ‘--show-trace’ to show detailed location information)
```

## Technical details

* System: 16.09pre90254.6b20d5b (Flounder)
* Nix version: nix-env (Nix) 1.11.3
* Nixpkgs version: "16.09pre90254.6b20d5b"

**Comment by ericsagnes** [comment]
Have you tried to change `nixos.config.networking.wireless.enable` to `config.networking.wireless.enable`?

**Comment by matthiasbeyer** [comment]
Actually yes, it didn't help.

**Comment by ericsagnes** [comment]
Is it possible to see the full `configuration.nix`?
It should be possible to use `config` as it is included in the `configuration.nix` main function arguments.

**Comment by matthiasbeyer** [comment]
my `configuration.nix´ is actually split over ~50 files. The snippet above is one of these files, I return a list from it and concat this list with other lists, setting `environment.systemPackages = lists` in my main file.

I can try what you suggested as soon as I'm back at my other machine where this problem occured.

**Comment by matthiasbeyer** [comment]
It _seems_ that when `(import <nixos> {})` the attribute `nixos.config` is _empty_ (but there is supposed to be `nixos.config.networking`

**Comment by domenkozar** [comment]
If you wish to evaluate NixOS config, call `nixos/lib/eval-config.nix`. Otherwise please specify what exactly do you want to accomplish.

**Comment by matthiasbeyer** [comment]
I just try to re-build my configuration, really. The snippet from the issue description worked until the last channel release, including some of the packages only if wlan was enabled on the machine.

**Comment by joachifm** [comment]
If `(import <nixos> {}).config` is empty, then you probably have an evaluation error somewhere, the attribute you're referring to is certainly still available.

**Comment by matthiasbeyer** [comment]
But how could that be if the last channel succeeded, ... I mean, yes there are changes in the nixpkgs, but I would say not changes that are _so_ big that this stuff doesn't work anymore?

**Comment by joachifm** [comment]
Can you provide a minimal reproducible test case? Without it, I don't know how we can proceed.

**Comment by matthiasbeyer** [comment]
I just did another `nixos-rebuild` on the latest channel update (from 3 days ago) and I guess it works again... still building, though.

**Comment by matthiasbeyer** [comment]
Issue can be closed as last channel update seems to fix this. I just rebuild my configuration successfully.
