### ISSUE TITLE
Postgres fails to start if locale is not set explicitely

### ISSUE THREAD

**Issue by pinpox** [NixOS/nixpkgs#182798]
### Describe the bug
The postgres service fails to start after rebuilding my system with the following error:
```
The database was initialized with LC_COLLATE "en_US.UTF-8",  which is not recognized by setlocale().
```
Upon further investigation I noticed that setting `i18n.supportedLocales` explicitely resolves the problem. Adding this to my configuration results in postgres running without errors as it did before:

```nix
  i18n.supportedLocales = [
    "en_US.UTF-8/UTF-8"
    "en_DK.UTF-8/UTF-8"
  ];
```

I am running postgres 11 and my default locale is set to
```nix
    i18n.defaultLocale = "en_DK.UTF-8";
```

This might be related to https://github.com/NixOS/nixpkgs/pull/177318

### Steps To Reproduce
1. 
```nix
    i18n.defaultLocale = "en_DK.UTF-8";
    services.postgresql.enable =  true;
    services.postgresql.package = pkgs.postgresql_11;
```
2. `nixos-rebuild switch`
3. `systemctl status postgres.service`

### Expected behavior
Postgres works with the default `i18l.defaultLocale` setting

### Notify maintainers
@SuperSandro2000 @thoughtpolice @danbst

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.11 (Raccoon), 22.11.20220714.8591f14`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `""`
 - channels(pinpox): `"home-manager"`
 - nixpkgs: `/nix/store/xd5ma751ipnmx4vfli808rl1gsc6gp0y-source`
```

**Comment by Mic92** [comment]
I think this is by design now so. Also read the changelog: https://github.com/NixOS/nixpkgs/pull/177318/files#diff-127f942ecb068c0807b0f2b48f7ccc949d1236061766447c4af79250a6da2662R98

**Comment by SuperSandro2000** [comment]
Yes, I am not sure how to programmatically fix this but we could append that information to the changelog.

**Comment by Mic92** [comment]
Can we get the locale from postgres somehow and append it to `i18n.supportedLocales`?

**Comment by pinpox** [comment]
Or maybe include `en_US.UTF-8` as it seems to be the default for various applications

**Comment by SuperSandro2000** [comment]
> Can we get the locale from postgres somehow and append it to `i18n.supportedLocales`?

That is on a database level, so I don't think so.
