### ISSUE TITLE
haskellPackages.vty fails with pkgsStatic due to terminfo dependency

### ISSUE THREAD

**Issue by pmiddend** [NixOS/nixpkgs#182785]
### Describe the bug
I'm trying to build my application with `pkgsStatic`. This fails because I am depending on `vty`, which gives me an error about the `terminfo` dependency:

```
Configuring vty-5.33...

Setup: Encountered missing or private dependencies:
terminfo >=0.3 && <0.5
```

I can fix this via:

```
    hp = nixpkgs.pkgsStatic.haskellPackages.override {
      overrides = self: super: {
        vty = (super.vty.override {
          terminfo = super.terminfo_0_4_1_5;
        });
      };
    };
```

Thanks @cdepillabout for figuring this out!

I'm using the latest master from yesterday: https://github.com/NixOS/nixpkgs/archive/28e2fa05340c0c20f16edddc51c5e953adf659b3.tar.gz

I'd assume to reproduce this, you can just create a derivation that depends on `vty`.

### Notify maintainers

@NixOS/haskell 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-39-generic, Ubuntu, 22.04 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.8`
 - channels(pmidden): `"home-manager, nixgl, nixpkgs-22.11pre393322.e2b34f0f11e"`
 - nixpkgs: `/home/pmidden/.nix-defexpr/channels/nixpkgs`

**Comment by sternenseemann** [comment]
Thanks for the report! This is a genuine issue with the cross package sets. They erroneously believe `terminfo` is a core library (which it usually is), but it is [disabled for GHC cross compilers](https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.0/mk/flavours/perf-cross.mk#L10).

Should be an easy fix though.

**Comment by cdepillabout** [comment]
This came up on the Haskell Discourse:

https://discourse.haskell.org/t/portable-haskell-executables-anyone-doing-that-possibly-using-nix/4816/14?u=cdepillabout
