### ISSUE TITLE
How can I fix a corrupt manifest.nix?

### ISSUE THREAD

**Issue by Ptival** [NixOS/nixpkgs#18279]
## Issue description

I'm really not sure when or what happened, but suddenly my nix-env is unusable!

```
nix-env -q
error: syntax error, unexpected $end, at /nix/store/0722zxv7zijaljpkrx342rjyjf56k979-env-manifest.nix:1:1
```

I couldn't find anything to fix it! I tried:

```
sudo nix-store --verify --repair --check-contents
reading the Nix store...
checking path existence...
checking hashes...
path ‘/nix/store/0722zxv7zijaljpkrx342rjyjf56k979-env-manifest.nix’ was modified! expected hash ‘632ec35215ef2d5e7adc4698e87db5ee331c21633f5a4a351e10a7e249c6dd00’, got ‘77ac62e2629d8e45f624589c0c8bf99e24b3a722349bf1e79bc186008534e246’
error: cannot repair path ‘/nix/store/0722zxv7zijaljpkrx342rjyjf56k979-env-manifest.nix’
```

I tried to ask on IRC or search the chat logs but couldn't really find any help anywhere. Is anyone knowledgeable enough to fix this kind of issue!?

**Comment by cleverca22** [comment]
can you pastebin the contents of the manifest.nix?

**Comment by Ptival** [comment]
It's empty.

**Comment by cleverca22** [comment]
ah, then your only option is nix-env --rollback to switch to the previous version

**Comment by Ptival** [comment]
It says `no environment older than the current one exists`... :(

**Comment by Ptival** [comment]
To anyone this happens to (corrupt profile + garbage-collected other profiles), you can delete your corrupt profile. First you might want to remember what was installed:

```
nix-store -q --references ~/.nix-profile
```

Then wipe the corrupted profiles out:

```
sudo rm /nix/var/nix/profiles/per-user/yourname/profile
sudo rm /nix/var/nix/profiles/per-user/yourname/profile-*-link
```

Then start again from scratch.

Thanks to clever and vcunat for helping me!

**Comment by jonringer** [comment]
This was helpful in diagnosing my issue:
```
# any nix-env command, including the one ran by home-manager
error: syntax error, unexpected $end, at /nix/store/ry2b0qwvhdvdlmrrkawj9c6xiy9d6krs-env-manifest.nix:1:1
```


For home-manager users, see what is populating your profile:
```
nix-store -q --references ~/.nix-profile
```
look for `home-manager-path`, mine was:
```
/nix/store/ghj6r1157710pdw113rmfg1nj46f0f7s-home-manager-path
```

To fix the broken manifest:
```
$ sudo rm -r /nix/var/nix/profiles/per-user/user/profile-*-link
```
then I could run home-manager again (using the path from earlier):
```
/nix/store/ghj6r1157710pdw113rmfg1nj46f0f7s-home-manager-path/bin/home-manager switch
```

Everything works as intended now

**Comment by johnchandlerburnham** [comment]
Sorry to comment on a closed issue, but I ran into the same manifest.nix + garbage collecting problem after a crash mid-rebuild and wanted to add my solution here for posterity in case someone else runs into it. 

I fixed it by building directly from the nixpkgs tarball with -I:

```
$ sudo nixos-rebuild switch -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz
```

Then you can `sudo nix-channel --update` again and `nixos-rebuild` as normal

**Comment by onny** [comment]
> sudo nixos-rebuild switch -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz

Didn't work for me

**Comment by Lillecarl** [comment]
Somehow i ran into this issue this morning. For me it was essential to clear
```
~/.local/state/nix/profiles
```
then run
```
sudo nix-collect-garbage -d
```
then reinstall my home-manager profile as usual. Note that this is dangerous and could eat your dog

**Comment by jheidbrink** [comment]
I encountered a corrupt `manifest.nix` for both users. I don't use `nix profile` myself, the profiles were created by home-manager. Given that I include home-manager in my configuration.nix, the broken manifest.json also broke `nixos-rebuild switch`. What I did was to remove `/nix/var/nix/profiles/per-user/<user>/{profile,profile-xyz-link}` and create a new symlink to `profile-abc-link` where `abc = xyz - 1`.

**Comment by jheidbrink** [comment]
I found that instead of changing the symlink, I could have used `nix-env rollback`, and instead of removing the broken profile I could have used `nix-env --delete-generations`. That's probably safer than to fiddle directly with the files.

**Comment by jDmacD** [comment]
> Somehow i ran into this issue this morning. For me it was essential to clear
> 
> ```
> ~/.local/state/nix/profiles
> ```
> 
> then run
> 
> ```
> sudo nix-collect-garbage -d
> ```
> 
> then reinstall my home-manager profile as usual. Note that this is dangerous and could eat your dog

life saver! I was starting to panic.
