### ISSUE TITLE
Using `cargo build` returns linker cc not found 

### ISSUE THREAD

**Issue by AlePon123** [NixOS/nixpkgs#182812]
### Steps To Reproduce
```Compiling serde v1.0.140
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)
```
### Expected behavior
when i compling any rust project it give me error "linker cc not found" 

### Screenshots
![image](https://user-images.githubusercontent.com/72556979/180779585-54985692-2224-4ea8-a163-3f5aa5403536.png)

**Comment by yu-re-ka** [comment]
In case you are looking for a quick solution/workaround: add gcc to your environment. Either to the packages in your system configuration, or `nix-shell `p rustc cargo gcc`
