### ISSUE TITLE
libvirtd: "Cannot find 'parted' in path" when creating volume

### ISSUE THREAD

**Issue by collinarnett** [NixOS/nixpkgs#182835]
### Describe the bug
When attempting to create a volume on a physical node pool parted is not found.

```console
$ sudo virsh vol-create-as nvme0n1 nixos-unstable 1863GB
error: Failed to create vol nixos-unstable
error: Cannot find 'parted' in path: No such file or directory
```

### Steps To Reproduce
Create a physical disk node pool.
Attempt to create a volume using that node pool.
```
sudo virsh vol-create-as nvme0n1 nixos-unstable 1863GB
```
In this case I have created a node pool called `nvme0n1` and I am attempting to create a volume called `nixos-unstable`

### Expected behavior
Volume is created normally.

### Additional context
I have tried to add parted manually using and overriding the package in the libvirtd module:
```nix
  libvirt = pkgs.libvirt.overrideAttrs (old: {
    buildInputs = old.buildInputs ++ [ pkgs.parted ];
  });
```
but this did not fix the issue.

### Notify maintainers
@fpletz 
@globin
@lovesegfault

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m
∙ "
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(collin): `""`
 - channels(root): `"nixos-21.11.335130.386234e2a61"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lovesegfault** [comment]
> I have tried to add parted manually using and overriding the package in the libvirtd module:
> 
> ```nix
>   libvirt = pkgs.libvirt.overrideAttrs (old: {
>     buildInputs = old.buildInputs ++ [ pkgs.parted ];
>   });
> ```
> 
> but this did not fix the issue.

That won't work, it seems like we need to wrap `virsh` to include `parted` in its `PATH`. I'll take a look.

**Comment by fpletz** [comment]
> That won't work, it seems like we need to wrap `virsh` to include `parted` in its `PATH`. I'll take a look.

You most likely need to add it to `systemd.services.libvirtd.path` in `nixos/modules/virtualisation/libvirtd.nix` because libvirtd will probably call it.
