### ISSUE TITLE
Lutris: ntlm_auth error

### ISSUE THREAD

**Issue by phaitonican** [NixOS/nixpkgs#182813]
### Describe the bug
`ntlm_auth: /home/cenk/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/vkmwymdwyjwgmpr1f2zs6mlh54g1pl39-samba-4.15.5/lib/samba/libcommon-auth-samba4.so)`

### Steps To Reproduce
1. Download Lutris
2. Download League of Legends
3. Start League of Legends

### Expected behavior
Password Popup

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.07 MiB download, 0.34 MiB unpacked):
  /nix/store/523zlfzypzcr969p058i6lcgfmg889d5-stdenv-linux
  /nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev
copying path '/nix/store/qx63l5swii7wll35xfgj7jqhycf9iy19-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/523zlfzypzcr969p058i6lcgfmg889d5-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.13, NixOS, 22.11 (Raccoon), 22.11pre393800.e494a908e88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(cenk): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by phaitonican** [comment]
Unfortunately somebody with more knowledge has to fix it in Lutris or the nixpkg Lutrie or the nixpkg samba itself. I think this error doesn't come in the stable version of NixOS. It's not an error of us/me setting up NixOs basically rather a error in the packages itself.

**Comment by clr-cera** [comment]
Hi! Has anyone managed to solve this by now? I am having the same problem.

**Comment by phaitonican** [comment]
> Hi! Has anyone managed to solve this by now? I am having the same problem.

As far as I know it was just an aesthetic issue and happens on non-nix packages too. Something else was my problem which prevented Lutris from running. Closing this thanks.
