### ISSUE TITLE
freetts not installing

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#18282]
## Issue description

freetts won't compile, since ant is missing a jdk/jre
### Steps to reproduce

nix-env -iA nixos.freetts (on NixOS)
## Technical details
- System: 16.09pre90254.6b20d5b (Flounder)
- Nix version: nix-env (Nix) 1.11.3
- Nixpkgs version: "16.09pre90254.6b20d5b"

**Comment by grahamc** [comment]
Seems this was fixed by a PR last September.
