### ISSUE TITLE
gke-gcloud-auth-plugin

### ISSUE THREAD

**Issue by nyarly** [NixOS/nixpkgs#182856]
**Project description**

Tool used by GKE to do go-client kubernetes auth. If `google-cloud-sdk` is installed via nixpkgs, so ought gke-cloud-auth-plugin

**Metadata**

* homepage URL: https://cloud.google.com/sdk/
* source URL: https://packages.cloud.google.com/apt/dists/cloud-sdk/main/binary-amd64/Packages
* license: ?
* platforms: unix, linux, darwin, ...

**Comment by heyarne** [comment]
See also https://github.com/talzion12/gke-gcloud-auth-plugin-flake/

**Comment by shinzui** [comment]
Both the reference source URL and the linked flake repo would not work on darwin machines. Ideally, the `google-cloud-sdk` would support specifying which components to install declaratively.

**Comment by michielboekhoff** [comment]
Maybe this doesn't apply to Darwin, but on NixOS I am able to do `google-cloud-sdk.withExtraComponents [google-cloud-sdk.components.gke-gcloud-auth-plugin]` and it shows as having been installed.

**Comment by shinzui** [comment]
It looks like support for `withExtraComponents` was added on [August 21st](https://github.com/NixOS/nixpkgs/commit/95a77857ef1db1825cbd02d038bacf02a3913111), and it didn't get merged to `nixpkgs-unstable` yet.

**Comment by jupblb** [comment]
I believe it already is at `nixpkgs-unstable`: https://nixpk.gs/pr-tracker.html?pr=187793

**Comment by shinzui** [comment]
@jupblb, thank you for pointing me to [nixpkg.gs](https://nixpk.gs/). That should save me time from checking my local clone.

**Comment by cyounkins** [comment]
For reasons that are unclear to me, when using home-manager I had to do
```
let
  gcloud = pkgs.google-cloud-sdk.withExtraComponents [ pkgs.google-cloud-sdk.components.gke-gcloud-auth-plugin ];
in
{
...
  home.packages = with pkgs; [
    gcloud
  ];
}
```

**Comment by pedro93** [comment]
@cyounkins your suggestion worked, thank you very much for that!
Do you have any idea why the variable needs to be defined?

**Comment by seh** [comment]
Another way to write the same thing for your `home.packages` entry is as follows:
```nix
(google-cloud-sdk.withExtraComponents (
  with google-cloud-sdk.components;
  [
    gke-gcloud-auth-plugin
  ]
))
```
I adapted that from @kittydoor's https://github.com/NixOS/nixpkgs/issues/377779#issue-2818823414.
