### ISSUE TITLE
VirtualboxGuestAdditions don't build for kernel 5.18

### ISSUE THREAD

**Issue by manuelbb-upb** [NixOS/nixpkgs#182985]
### Steps To Reproduce
In the `configuration.nix`
1. Set kernel to 5.18.x via `boot.kernelPackages = pkgs.linuxPackages_latest;` or `boot.kernelPackages = pkgs.linuxPackages_zen;`.
2. Enable guest-additions: `virtualisation.virtualbox.guest.enable = true;`
3. (Enable installation of broken packages: `nixpkgs.config.allowBroken = true;`)

Then try to update with `sudo nixos-rebuild switch --upgrade`.

### Build log
[Link to gist](https://gist.github.com/manuelbb-upb/b1fbf8498b3e11bb8c311d2af12d807a)

### Additional context
This bug is known for other Linux derivations and patches seem to be available, see [this bugzilla report](https://bugs.gentoo.org/847097).

### Notify maintainers
@Yarny0 @alyssais

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.05 (Quokka), 22.05.1974.d1ca40ea766`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(user): `"home-manager-22.05.tar.gz, nixpkgs-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Yarny0** [comment]
There is a pull request fixing the issue: https://github.com/NixOS/nixpkgs/pull/183280 .  Maybe you can test that pull request and add a review if you have time.  Note that the pull request fixes the issue, however, in its current version, you still need to manually override the "broken" flag of the guest additions to build them.

For the record: I don't see myself as maintainer of virtualbox.

**Comment by Yarny0** [comment]
Since https://github.com/NixOS/nixpkgs/pull/183280 got merged, can this issue be closed now?

**Comment by manuelbb-upb** [comment]
Hi, sorry for the belated response. Was on vacation for a few days. I just tested the latest kernel from the unstable channel with guest additions enabled and it has built without complaints and appears to work well so far.
So, the issue seems to be fixed on the unstable channel. Thanks!
