### ISSUE TITLE
Motrix

### ISSUE THREAD

**Issue by chengen12** [NixOS/nixpkgs#182977]
**Project description**:  A full-featured download manager
_describe the project a little_:  it is a download manager that Support downloading HTTP, FTP, BitTorrent, Magnet, etc. I think it is a substitute for idm. You know, idm can only run on windows

**Metadata**

* homepage URL: https://motrix.app/
* source URL: https://github.com/agalwood/Motrix
* license: mit, bsd, gpl2+ , ... :  The MIT License
* platforms: unix, linux, darwin, ...  it provide opensource for linux , window, macos

**Comment by fabaff** [comment]
Duplicate of #157984

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/pull/185804

**Comment by oluceps** [comment]
#185804 Merged.
