### ISSUE TITLE
headscale: 0.15 -> 0.16

### ISSUE THREAD

**Issue by JayRovacsek** [NixOS/nixpkgs#182913]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: headscale
current version: 0.15
desired version: 0.16

New version released recently as per: https://github.com/juanfont/headscale/releases/tag/v0.16.0 😍 
Happy to create the pull request if maintainers prefer 👍 

###### Notify maintainers
maintainers: @kradalby @NKJe

###### Note for maintainers
Please tag this issue in your PR.

**Comment by kradalby** [comment]
Already merged https://github.com/NixOS/nixpkgs/pull/182804
