### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found -- file misdireted

### ISSUE THREAD

**Issue by BanagherL** [NixOS/nixpkgs#182997]
### Describe the bug
I am actually using a special software under the nix os and when I lanced the program it returns me this error:

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/librt.so.1)  

When I check the version of glibc in the file libc.so.6, using the command strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC, then I found a version of GLIBC_2.3.2 instead of GLIBC_2.32.

So I am wondering if I've already got the right version but the file is misdirected to a wrong place.

If I am true, how could I fix this kind of problem?

The software is installed within a univ's cluster so the options of sudo does not work..

Any help would be very thankful.
```

**Comment by SuperSandro2000** [comment]
You cannot mix significantly different versions of glibc.
