### ISSUE TITLE
Shutdown hangs for ~ 90s waiting for s6-svscan

### ISSUE THREAD

**Issue by izuk** [NixOS/nixpkgs#182916]
### Describe the bug

On shutdown/reboot, the system hangs for ~ 90s with the message:

```
systemd-shutdown[1]: Waiting for process:  XXXX [s6-svscan]
```

Immediately after 90s there's a message re `watchdog` and then my system powers off/reboots.

### Steps To Reproduce

```
$ sudo systemctl reboot
```

### Expected behavior

After drives are unmounted, I expect shutdown to be fast, not take another 90s.  The rest of the shutdown only takes ~ 2s.

### Additional context

I have docker and virtualization running; not sure if that has anything to do with it.

Here's what journalctl reports:

```
Jul 25 20:42:32 monolith systemd[1]: Finished System Reboot.
Jul 25 20:42:32 monolith systemd[1]: Reached target System Reboot.
Jul 25 20:42:32 monolith systemd[1]: Shutting down.
Jul 25 20:42:32 monolith systemd[1]: Using hardware watchdog 'iTCO_wdt', version 0, device /dev/watchdog0
Jul 25 20:42:32 monolith systemd[1]: Watchdog running with a timeout of 10min.
Jul 25 20:42:32 monolith kernel: watchdog: watchdog0: watchdog did not stop!
Jul 25 20:42:32 monolith systemd-shutdown[1]: Using hardware watchdog 'iTCO_wdt', version 0, device /dev/watchdog0
Jul 25 20:42:32 monolith systemd-shutdown[1]: Watchdog running with a timeout of 10min.
Jul 25 20:42:32 monolith systemd-shutdown[1]: Syncing filesystems and block devices.
Jul 25 20:42:32 monolith systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Jul 25 20:42:32 monolith systemd-journald[618]: Journal stopped
```

I believe the 90s hang happens *after* the last message.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.13, NixOS, 22.11 (Raccoon), 22.11pre393800.e494a908e88`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(zukerman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by alyssais** [comment]
Do you know where s6 is coming from?  Do you use it on your NixOS system, or in one of your containers?  I don't see any upstream NixOS modules that use s6.

**Comment by izuk** [comment]
No idea where s6 is coming from.  I don't reference it in any of my
configs.  I assume it's some recent dependency-of-a-dependency of some
nixos base thing.

It looks like the hang happens after all the containers are shut down, but
I'm not sure.

**Comment by frprm** [comment]
I have been experiencing the same issue. It appears some containers make use of [s6-overlay](https://github.com/just-containers/s6-overlay) which is where the process `s6-svscan` comes from...

After applying [the solution shared in this thread on Discourse](https://discourse.nixos.org/t/docker-hanging-on-reboot/18270/5), I'm no longer experiencing this issue.

Set `virtualisation.docker.liveRestore = false` to get rid of this issue.
