### ISSUE TITLE
OpenVINO fails to build with linker error (`undefined reference ...@CXXABI_1.3.13`)

### ISSUE THREAD

**Issue by akiross** [NixOS/nixpkgs#182999]
### Describe the bug

When trying to get openvino in a shell, something fails to build with a linker error similar to

```
/nix/store/0gzd0049bywqhzi5anbydsxil7r1lfrj-binutils-2.38/bin/ld: /nix/store/dk31cwsfaqggdkj0bgd42n3mvbwsbixl-tbb-2020.3/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
```

### Steps To Reproduce

1. nix shell nixpkgs#openvino

### Expected behavior
OpenVINO builds successfully and it's provided in a shell.

### Additional context
The nix build log is attached.
[openvino.log](https://github.com/NixOS/nixpkgs/files/9191795/openvino.log)

### Notify maintainers
@tfmoraes 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
akiross@eva01 ~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.05 (Quokka), 22.05.20220724.d1ca40e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-22.05"`
 - channels(akiross): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nagy** [comment]
Web-viewable logs on hydra:

https://hydra.nixos.org/job/nixpkgs/trunk/openvino.x86_64-linux

https://hydra.nixos.org/build/186583702/nixlog/4

**Comment by mweinelt** [comment]
Would also be nice to have a more recent version that could work with frigate. https://github.com/blakeblackshear/frigate/blob/dev/requirements-ov.txt

**Comment by mweinelt** [comment]
> /nix/store/0gzd0049bywqhzi5anbydsxil7r1lfrj-binutils-2.38/bin/ld: /nix/store/dk31cwsfaqggdkj0bgd42n3mvbwsbixl-tbb-2020.3/lib/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'

The original error meant that tbb was built with gcc 11, while openvino was built using gcc 10.
