### ISSUE TITLE
Builders should use ${stdenv.shell} instead of /bin/sh

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#183]
Any Nix expression that refers to the impure path `/bin/sh` should be fixed to use `${stdenv.shell}` (which can be assumed to be Bash).

Potential offenders are (determined by `for n in $(grep -Rl /bin/sh pkgs); do echo "- [ ] $n"; done` at 2017-01-03):

- [ ] pkgs/tools/compression/gzip/default.nix
- [ ] pkgs/tools/package-management/nixui/generate.sh
- [ ] pkgs/tools/package-management/checkinstall/glibc-check.patch
- [ ] pkgs/tools/text/gnugrep/default.nix
- [ ] pkgs/tools/text/patchutils/drop-comments.patch
- [ ] pkgs/tools/filesystems/bcache-tools/bcache-udev-modern.patch
- [ ] pkgs/tools/admin/daemontools/default.nix
- [ ] pkgs/tools/typesetting/tex/texlive/fixHashes.sh
- [ ] pkgs/tools/typesetting/lout/builder.sh
- [ ] pkgs/tools/virtualization/nixos-container/nixos-container.pl
- [ ] pkgs/tools/virtualization/xe-guest-utilities/default.nix
- [ ] pkgs/tools/backup/store-backup/default.nix
- [ ] pkgs/tools/archivers/rpmextract/rpmextract.sh
- [ ] pkgs/tools/archivers/sharutils/default.nix
- [ ] pkgs/tools/security/eid-mw/eid-nssdb.in
- [ ] pkgs/tools/security/ecryptfs/default.nix
- [ ] pkgs/tools/networking/zap/default.nix
- [ ] pkgs/tools/networking/ccnet/default.nix
- [ ] pkgs/tools/networking/badvpn/default.nix
- [ ] pkgs/tools/networking/network-manager/default.nix
- [ ] pkgs/tools/misc/xfstests/default.nix
- [ ] pkgs/tools/misc/qjoypad/default.nix
- [ ] pkgs/tools/misc/autojump/default.nix
- [ ] pkgs/tools/misc/fileschanged/unused-variables.debian.patch
- [ ] pkgs/tools/misc/debootstrap/default.nix
- [ ] pkgs/tools/misc/grub/2.0x.nix
- [ ] pkgs/tools/misc/grub/trusted.nix
- [ ] pkgs/tools/graphics/povray/default.nix
- [ ] pkgs/tools/graphics/briss/default.nix
- [ ] pkgs/tools/graphics/zxing/zxing.sh
- [ ] pkgs/tools/graphics/zxing/java-zxing.sh
- [ ] pkgs/tools/graphics/zxing/zxing-cmdline-runner.sh
- [ ] pkgs/tools/graphics/zxing/zxing-cmdline-encoder.sh
- [ ] pkgs/tools/X11/xnee/default.nix
- [ ] pkgs/desktops/gnustep/make/wrapper.sh
- [ ] pkgs/desktops/kde-4.14/l10n/l10n-manifest.sh
- [ ] pkgs/desktops/kde-4.14/kde-package/kde-manifest.sh
- [ ] pkgs/shells/bash/4.4.nix
- [ ] pkgs/shells/bash/4.3.nix
- [ ] pkgs/shells/bash/cygwin-bash-4.3.33-1.src.patch
- [ ] pkgs/shells/bash/update-patch-set.sh
- [ ] pkgs/shells/dash/default.nix
- [ ] pkgs/build-support/fetchzip/nix-prefetch-zip
- [ ] pkgs/build-support/fetchsvn/nix-prefetch-svn
- [ ] pkgs/build-support/release/ant-build.nix
- [ ] pkgs/build-support/setup-hooks/patch-shebangs.sh
- [ ] pkgs/build-support/docker/default.nix
- [ ] pkgs/build-support/upstream-updater/update-upstream-data.sh
- [ ] pkgs/build-support/upstream-updater/create-src-info.sh
- [ ] pkgs/build-support/upstream-updater/update-walker.sh
- [ ] pkgs/build-support/upstream-updater/create-src-info-git.sh
- [ ] pkgs/build-support/upstream-updater/urls-from-page.sh
- [ ] pkgs/build-support/icon-conv-tools/bin/extractWinRscIconsToStdFreeDesktopDir.sh
- [ ] pkgs/build-support/icon-conv-tools/bin/icoFileToHiColorTheme
- [ ] pkgs/build-support/vm/windows/default.nix
- [ ] pkgs/build-support/vm/default.nix
- [ ] pkgs/build-support/fetchbzr/nix-prefetch-bzr
- [ ] pkgs/build-support/fetchcvs/nix-prefetch-cvs
- [ ] pkgs/build-support/singularity-tools/default.nix
- [ ] pkgs/build-support/kdewrapper/default.nix
- [ ] pkgs/development/tools/tradcpp/tradcpp-configure.patch
- [ ] pkgs/development/tools/java/jclasslib/builder.sh
- [ ] pkgs/development/tools/misc/ctags/wrapped.nix
- [ ] pkgs/development/tools/misc/ccache/default.nix
- [ ] pkgs/development/tools/misc/distcc/default.nix
- [ ] pkgs/development/tools/misc/libtool/libtool2.nix
- [ ] pkgs/development/tools/misc/libtool/default.nix
- [ ] pkgs/development/tools/misc/autoconf/2.64.nix
- [ ] pkgs/development/tools/misc/autoconf/default.nix
- [ ] pkgs/development/tools/misc/autoconf/2.13.nix
- [ ] pkgs/development/tools/misc/automake/automake-1.13.x.nix
- [ ] pkgs/development/tools/misc/automake/automake-1.14.x.nix
- [ ] pkgs/development/tools/misc/automake/automake-1.15.x.nix
- [ ] pkgs/development/tools/misc/automake/automake-1.12.x.nix
- [ ] pkgs/development/tools/misc/automake/automake-1.11.x.nix
- [ ] pkgs/development/tools/build-managers/buildbot/default.nix
- [ ] pkgs/development/interpreters/guile/default.nix
- [ ] pkgs/development/interpreters/picolisp/default.nix
- [ ] pkgs/development/ocaml-modules/gmetadom/gcc-4.3.dpatch
- [ ] pkgs/development/libraries/aqbanking/update.sh
- [ ] pkgs/development/libraries/beignet/default.nix
- [ ] pkgs/development/libraries/nss/default.nix
- [ ] pkgs/development/libraries/nss/nss-3.21-gentoo-fixups.patch
- [ ] pkgs/development/libraries/cloog-ppl/default.nix
- [ ] pkgs/development/libraries/libgpg-error/default.nix
- [ ] pkgs/development/libraries/pango/default.nix
- [ ] pkgs/development/libraries/glibc/common.nix
- [ ] pkgs/development/libraries/ccnx/default.nix
- [ ] pkgs/development/libraries/icu/default.nix
- [ ] pkgs/development/libraries/postgis/pg_db_postgis_enable.sh
- [ ] pkgs/development/libraries/postgis/pg_db_postgis_fix_or_load_sql_dump.sh
- [ ] pkgs/development/libraries/cloog/default.nix
- [ ] pkgs/development/libraries/cloog/0.18.0.nix
- [ ] pkgs/development/python-modules/libgpuarray/cuda/default.nix
- [ ] pkgs/development/lisp-modules/clwrapper/common-lisp.sh
- [ ] pkgs/development/lisp-modules/clwrapper/build-with-lisp.sh
- [ ] pkgs/development/lisp-modules/clwrapper/cl-wrapper.sh
- [ ] pkgs/development/lisp-modules/define-package.nix
- [ ] pkgs/development/lisp-modules/from-quicklisp/barebones-quicklisp-expression.sh
- [ ] pkgs/development/lisp-modules/from-quicklisp/asdf-description.sh
- [ ] pkgs/development/lisp-modules/from-quicklisp/quicklisp-beta-env.sh
- [ ] pkgs/development/lisp-modules/from-quicklisp/quicklisp-dependencies.sh
- [ ] pkgs/development/mobile/titaniumenv/examples/kitchensink/generatekeystore.sh
- [ ] pkgs/development/mobile/androidenv/generate-sources.sh
- [ ] pkgs/development/mobile/androidenv/generate-platforms.sh
- [ ] pkgs/development/mobile/androidenv/fetch.sh
- [ ] pkgs/development/mobile/androidenv/generate-sysimages.sh
- [ ] pkgs/development/mobile/androidenv/generate-addons.sh
- [ ] pkgs/development/perl-modules/expression-generator/retrieve-file-link.sh
- [ ] pkgs/development/perl-modules/expression-generator/retrieve-meta-yaml.sh
- [ ] pkgs/development/perl-modules/expression-generator/make-clean-dir.sh
- [ ] pkgs/development/perl-modules/expression-generator/requirements.sh
- [ ] pkgs/development/perl-modules/expression-generator/full-requirements.sh
- [ ] pkgs/development/perl-modules/expression-generator/filtered-requirements.sh
- [ ] pkgs/development/perl-modules/expression-generator/write-nix-expression.sh
- [ ] pkgs/development/perl-modules/expression-generator/source-download-link.sh
- [ ] pkgs/development/perl-modules/expression-generator/grab-url.sh
- [ ] pkgs/development/perl-modules/expression-generator/retrieve-modulepage.sh
- [ ] pkgs/development/web/remarkjs/generate.sh
- [ ] pkgs/development/node-packages/generate.sh
- [ ] pkgs/development/node-packages/node-env.nix
- [ ] pkgs/development/compilers/ccl/default.nix
- [ ] pkgs/development/compilers/fsharp/default.nix
- [ ] pkgs/development/compilers/ocaml/configure-3.08.0
- [ ] pkgs/development/compilers/adobe-flex-sdk/default.nix
- [ ] pkgs/development/compilers/ghc/gcc-clang-wrapper.sh
- [ ] pkgs/development/compilers/rust/print-hashes.sh
- [ ] pkgs/development/compilers/openjdk/8.nix
- [ ] pkgs/development/compilers/cmdstan/default.nix
- [ ] pkgs/development/misc/avr8-burn-omat/default.nix
- [ ] pkgs/test/mkOption/test.sh
- [ ] pkgs/applications/editors/music/tuxguitar/default.nix
- [ ] pkgs/applications/version-management/smartgithg/install_freedesktop_items.sh
- [ ] pkgs/applications/virtualization/xen/generic.nix
- [ ] pkgs/applications/science/logic/coq/configure.8.3.patch
- [ ] pkgs/applications/science/logic/iprover/default.nix
- [ ] pkgs/applications/science/logic/hol_light/default.nix
- [ ] pkgs/applications/science/geometry/drgeo/struct.patch
- [ ] pkgs/applications/science/misc/simgrid/default.nix
- [ ] pkgs/applications/science/misc/openmodelica/update-src-libs-git.sh
- [ ] pkgs/applications/science/misc/openmodelica/update-src-libs-svn.sh
- [ ] pkgs/applications/audio/abcde/default.nix
- [ ] pkgs/applications/display-managers/lightdm/fix-paths.patch
- [ ] pkgs/applications/networking/cluster/mesos/nixos.patch
- [ ] pkgs/applications/networking/instant-messengers/telegram/telegram-cli/default.nix
- [ ] pkgs/applications/networking/instant-messengers/telepathy/kde/update.sh
- [ ] pkgs/applications/networking/browsers/google-chrome/default.nix
- [ ] pkgs/applications/networking/browsers/w3m/cygwin.patch
- [ ] pkgs/applications/networking/browsers/chromium/update.sh
- [ ] pkgs/applications/misc/keepass/extractWinRscIconsToStdFreeDesktopDir.sh
- [ ] pkgs/applications/misc/freemind/default.nix
- [ ] pkgs/applications/misc/translate-shell/default.nix
- [ ] pkgs/applications/misc/cdrtools/fix-paths.patch
- [ ] pkgs/applications/misc/googleearth/default.nix
- [ ] pkgs/applications/misc/openjump/default.nix
- [ ] pkgs/applications/misc/thinking-rock/default.nix
- [ ] pkgs/applications/misc/jbidwatcher/default.nix
- [ ] pkgs/applications/graphics/qscreenshot/default.nix
- [ ] pkgs/applications/graphics/zgrviewer/default.nix
- [ ] pkgs/applications/graphics/alchemy/default.nix
- [ ] pkgs/applications/graphics/sane/backends/generic.nix
- [ ] pkgs/applications/graphics/swingsane/default.nix
- [ ] pkgs/applications/graphics/wings/default.nix
- [ ] pkgs/applications/graphics/shutter/default.nix
- [ ] pkgs/applications/graphics/digikam/5.nix
- [ ] pkgs/applications/graphics/xzgv/fix-linker-paths.patch
- [ ] pkgs/applications/video/handbrake/default.nix
- [ ] pkgs/applications/video/simplescreenrecorder/fix-paths.patch
- [ ] pkgs/applications/video/zdfmediathk/default.nix
- [ ] pkgs/applications/video/shotcut/default.nix
- [ ] pkgs/data/misc/geolite-legacy/builder.sh
- [ ] pkgs/games/eduke32/default.nix
- [ ] pkgs/games/andyetitmoves/default.nix
- [ ] pkgs/games/zangband/default.nix
- [ ] pkgs/games/openttd/default.nix
- [ ] pkgs/games/trigger/default.nix
- [ ] pkgs/games/tremulous/default.nix
- [ ] pkgs/games/crawl/crawl_purify.patch
- [ ] pkgs/games/oilrush/default.nix
- [ ] pkgs/games/freeorion/fix-paths.sh
- [ ] pkgs/games/vessel/default.nix
- [ ] pkgs/games/worldofgoo/default.nix
- [ ] pkgs/games/ue4/generate-expr-from-cdn.sh
- [ ] pkgs/games/mars/default.nix
- [ ] pkgs/games/minecraft-server/default.nix
- [ ] pkgs/misc/seafile-shared/default.nix
- [ ] pkgs/misc/drivers/foomatic-filters/default.nix
- [ ] pkgs/misc/drivers/hplip/3.15.9.nix
- [ ] pkgs/misc/drivers/hplip/default.nix
- [ ] pkgs/misc/vim-plugins/vim-utils.nix
- [ ] pkgs/misc/freestyle/default.nix
- [ ] pkgs/misc/cups/drivers/mfcj6510dwlpr/default.nix
- [ ] pkgs/misc/emulators/retrofe/default.nix
- [ ] pkgs/misc/emulators/wine/builder-wow.sh
- [ ] pkgs/os-specific/gnu/mig/default.nix
- [ ] pkgs/os-specific/linux/nfs-utils/default.nix
- [ ] pkgs/os-specific/linux/udisks/2-default.nix
- [ ] pkgs/os-specific/linux/alsa-plugins/wrapper.nix
- [ ] pkgs/os-specific/linux/bbswitch/default.nix
- [ ] pkgs/os-specific/linux/util-linux/default.nix
- [ ] pkgs/os-specific/linux/rfkill/udev.nix
- [ ] pkgs/os-specific/linux/rfkill/rfkill-hook.sh
- [ ] pkgs/os-specific/linux/tp_smapi/default.nix
- [ ] pkgs/servers/xmpp/pyMAILt/default.nix
- [ ] pkgs/servers/xmpp/pyIRCt/default.nix
- [ ] pkgs/servers/meteor/main.patch
- [ ] pkgs/servers/nosql/eventstore/default.nix
- [ ] pkgs/servers/x11/xquartz/startx
- [ ] pkgs/servers/x11/xquartz/privileged
- [ ] pkgs/servers/x11/xquartz/xinitrc
- [ ] pkgs/servers/x11/xorg/darwin/bundle_main.patch
- [ ] pkgs/servers/shellinabox/default.nix
- [ ] pkgs/servers/mail/postfix/postfix-script-shell.patch
- [ ] pkgs/servers/asterisk/runtime-vardirs.patch
- [ ] pkgs/stdenv/generic/default.nix
- [ ] pkgs/stdenv/freebsd/trivial-bootstrap.sh
- [ ] pkgs/stdenv/nix/default.nix
- [ ] pkgs/stdenv/cygwin/wrap-exes-to-find-dlls.sh
- [ ] pkgs/stdenv/linux/bootstrap-tools/scripts/unpack-bootstrap-tools.sh
- [ ] pkgs/stdenv/darwin/make-bootstrap-tools.nix
- [ ] pkgs/stdenv/darwin/unpack-bootstrap-tools.sh
- [ ] pkgs/stdenv/darwin/standard-sandbox.sb
- [ ] pkgs/stdenv/darwin/default.nix

**Comment by matthiasbeyer** [comment]
After doing #8881 it seems that the following are false positives in the list above:

```
pkgs/shells/dash/default.nix
pkgs/tools/misc/qjoypad/default.nix
pkgs/tools/compression/gzip/default.nix
pkgs/development/tools/misc/libtool/libtool2.nix
development/tools/misc/libtool/default.nix
pkgs/development/tools/misc/automake/automake-1.10.x.nix
pkgs/development/tools/misc/automake/automake-1.11.x.nix
pkgs/development/tools/misc/automake/automake-1.12.x.nix
pkgs/development/tools/misc/automake/automake-1.13.x.nix
pkgs/development/tools/misc/automake/automake-1.14.x.nix
pkgs/development/tools/misc/automake/automake-1.15.x.nix
pkgs/development/tools/misc/autoconf/2.13.nix
pkgs/development/tools/misc/autoconf/default.nix
pkgs/development/libraries/cloog-ppl/default.nix
pkgs/development/libraries/pango/default.nix
pkgs/development/libraries/libgpg-error/default.nix
pkgs/development/libraries/nss/default.nix
pkgs/development/libraries/cloog/0.18.0.nix
pkgs/development/libraries/cloog/default.nix
pkgs/development/libraries/glibc/common.nix
pkgs/development/r-modules/default.nix
pkgs/stdenv/nix/default.nix
pkgs/stdenv/linux/default.nix
pkgs/applications/graphics/shotwell/default.nix
pkgs/applications/networking/cluster/mesos/default.nix
pkgs/applications/editors/music/tuxguitar/default.nix
pkgs/applications/video/shotcut/default.nix
pkgs/build-support/builder-defs/builder-defs.nix
```

and the following are done:

```
development/libraries/icu/default.nix
```

**Comment by Profpatsch** [comment]
(triage) There’s still a lot of /bin/bash. Maybe an easy task for a beginning contributor? (Is there a tag for that?)

**Comment by fubarbaz** [comment]
I want to be able distinguish between using `sh` and `bash`. If `${stdenv.shell} ` can be assumed to be bash compatible (also *which* Bash?), then I would also like to have a `${stdenv.posix_shell} `which is just plain old `/bin/sh`. `/bin/sh` is a part of POSIX, so it seems weird if that doesn't work or is considered to be "wrong", but perhaps this is related to allow cross builds to work. 

The motivation for getting rid of `/bin/sh` seems to be lacking. So, while there might be a motivation, this ticket doesn't contain one and I am not in favor of "fixing" this, until there is a motivation in the ticket.

**Comment by 7c6f434c** [comment]
Using `/bin/sh` breaks purity, and there are a few realistic scenarios where it does create annoying problems. POSIX is not relevant here — we provide `/bin/sh` on NixOS because of POSIX, but it is still a good idea not to use it inside builds. #1424 is a problem with `system()` using `/bin/sh`, but any use can trigger a similar problem.

**Comment by cleverca22** [comment]
there is also a second major fault in /bin/sh and sandboxes, if you need to build a missing output of the glibc /bin/sh uses, the entire glibc has to be rebuild, so ${glibc.lib} is omitted from the sandbox, and now /bin/sh is broken

99% of the time, the binary cache will have you covered, but if you aren't getting glibc from the cache for whatever reason, and you nix-collect-garbage one of glibc's outputs, your screwed

only way out is to make sure the build uses a different glibc from /bin/sh (so sh has to be held behind a mass-rebuild)

**Comment by vcunat** [comment]
Over long term, I'd prefer if `/bin/sh` in builds were taken from `stdenv.shell`, to improve purity.  That would side-step this problem of trying to rebuild bash's glibc.

**Comment by Mic92** [comment]
I think we can close this one.
