### ISSUE TITLE
mediawiki doesn't work with postgres

### ISSUE THREAD

**Issue by chayleaf** [NixOS/nixpkgs#183097]
### Describe the bug
config:
```nix
    name = "Test Wiki";
    passwordFile = ".../admin_password";
    database = {
      type = "postgres";
      socket = "/var/run/postgresql/.s.PGSQL.5432";
      host = "127.0.0.1";
      port = 5432;
      name = "mediawiki";
      user = "mediawiki";
      passwordFile = ".../db_password";
    };
```
the install script generated:
```bash
/nix/store/...-php-with-extensions-8.1.7/bin/php /nix/store/...mediawiki-full-1.37.2/share/mediawiki/maintenance/install.php \
  --confpath /tmp \
  --scriptpath / \
  --dbserver 127.0.0.1:/var/run/postgresql/.s.PGSQL.5432 \
  --dbport 5432 \
  --dbname mediawiki \
  --dbuser mediawiki \
  --dbpassfile .../db_password \
  --passfile .../admin_password \
  Test Wiki \
  admin 
```
Fixed install script:
```bash
/nix/store/...-php-with-extensions-8.1.7/bin/php /nix/store/...mediawiki-full-1.37.2/share/mediawiki/maintenance/install.php \
  --confpath /tmp \
  --scriptpath / \
  --dbtype postgres \
  --dbserver 127.0.0.1 \
  --dbport 5432 \
  --dbname mediawiki \
  --dbuser mediawiki \
  --dbpassfile .../db_password \
  --passfile .../admin_password \
  "Test Wiki" \
  admin 
```

I'm on 22.05, but the service's code hasn't been updated since 2021 so it's broken on unstable too.

**Comment by pennae** [comment]
looking at the module code it looks like it should be sufficient to not set `socket`. which makes sense, rarely would you want to configure *both* unix and ip connections to the database. can you test that?

**Comment by chayleaf** [comment]
> looking at the module code it looks like it should be sufficient to not set `socket`. which makes sense, rarely would you want to configure _both_ unix and ip connections to the database. can you test that?

that isn't enough, at the very least `--dbtype` needs to be set. Also wiki name needs to be quoted in the script, that's a separate issue, but it probably should be fixed in the same PR.

**Comment by h7x4** [comment]
I guess this was fixed by https://github.com/NixOS/nixpkgs/commit/d9c613d746e0b88ec9afc558368dd5422aff8448 (with the exception of the quoted name thing)?

**Comment by abhillman** [comment]
Works for me against 23.11
