### ISSUE TITLE
replace prelink in gobject-introspection wrapper

### ISSUE THREAD

**Issue by NickCao** [NixOS/nixpkgs#183071]
### Steps To Reproduce
1. `nix build github:NixOS/nixpkgs/staging#prelink`

### Build log
```
prelink-unstable> SKIP: movelibs.sh
prelink-unstable> FAIL: reloc1.sh
prelink-unstable> PASS: reloc2.sh
prelink-unstable> FAIL: reloc3.sh
prelink-unstable> SKIP: reloc4.sh
prelink-unstable> SKIP: reloc5.sh
prelink-unstable> FAIL: reloc6.sh
prelink-unstable> FAIL: reloc7.sh
<the rest omitted>
```

### Additional context
[`prelink` is dropped by openembedded](https://git.openembedded.org/openembedded-core/commit/?id=3ea0f248acf60791a25f496e2aff06c68d218ba7), [support for prelink is removed from glibc](https://git.openembedded.org/openembedded-core/commit/?id=23c0be78106f1d1e2bb9c724174a1bb8c56c2469), and itself is effectively abandoned by the upstream (yocto project). I think we may as well drop it rather than fix it. However `gobject-introspection` now relies on it as a runtime linker for use in cross compilation, we have to find an alternative.

### Notify maintainers
@Artturin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Artturin** [comment]
openembedded replaced prelink with objdump
https://github.com/openembedded/openembedded-core/commit/767e0880d4d729e659e859dd99c1cdb084b8ba51

will test

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/183145
