### ISSUE TITLE
packageOverrides no longer respected by aliases

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#18316]
For example, in `all-packages.nix` we have:
```
dbus_tools = self.dbus.out;
dbus_daemon = self.dbus.daemon;
```
while in `nixos/modules/config/no-x-libs.nix` we have:
```
nixpkgs.config.packageOverrides = pkgs:
  { dbus = pkgs.dbus.override { x11Support = false; }; };
```

In NixOS 16.09, the override to `dbus` is no longer propagated to `dbus_tools` and `dbus_daemon`. Thus these continue to use `libX11`. This is a regression from 16.03. (Workaround in ba70ce28ae4032a4674634c2a00615f7a0908357.)

Changing `self` back to `pkgs` restores the 16.03 behaviour, where overrides did propagate properly.

So should we change `self` back to `pkgs` everywhere, or should `self` be fixed?

**Comment by domenkozar** [comment]
@nbp

**Comment by nbp** [comment]
I left a comment on https://github.com/NixOS/nixpkgs/commit/ba70ce28ae4032a4674634c2a00615f7a0908357#commitcomment-18902806 .

The easiest solution for the release would be to revert to patches that made these aliases, and add a test to ensure that aliases are expected to alias the overwritten packages, and not the original packages.

To solve this issue, we would either have to move `aliases.nix` after customOverride, or maybe add a second fix-point to resolve dependencies separately.

**Comment by nbp** [comment]
This issue is caused by #14398
