### ISSUE TITLE
Mullvad VPN 2022-02 RPC Errors

### ISSUE THREAD

**Issue by totoroot** [NixOS/nixpkgs#183295]
### Describe the bug
The update from 2022-01 to 2022-02 with PR #180180 seems to have broken Mullvad VPN on my machine.

A VPN connection be established, but I am getting strange RPC errors:

```
λ mullvad relay get
RPC failed: Internal: failed to decode Protobuf message: Settings.relay_settings: invalid wire type value: 6
````

Status is reported as connected:
```
λ mullvad status
Connected to at8-wireguard in Vienna, Austria
```

The GUI is stuck at "Connecting to Mullvad system service...", as can be seen in the screenshot below.

### Screenshots
![image](https://user-images.githubusercontent.com/39650930/181503337-8b77d739-a344-4a09-be83-0218b23b6606.png)

### Additional context

The daemon seems to be running without an issue and I seem to be connected
```
λ sudo systemctl status mullvad-daemon.service                                                          ~/dev/nixpkgs master
● mullvad-daemon.service - Mullvad VPN daemon
     Loaded: loaded (/etc/systemd/system/mullvad-daemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-07-28 14:13:05 CEST; 17s ago
```

Restarting the service did not fix the issue.

2022-01 works fine

### Notify maintainers
Maintainers: @cole-h @Br1ght0ne @ymarkus @flexagoon 
PR opened by: @kilianar

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.13, NixOS, 22.05 (Quokka), 22.05.20220727.d9536b9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(...): `"home-manager-21.11.tar.gz, unstable"`
 - nixpkgs: `/nix/store/v039w5dpnfqy2qvqq04a489s8zqvr4di-source`
```

**Comment by cole-h** [comment]
Could you please post your `/var/log/mullvad-vpn/daemon.log` here (censoring anything you don't want public)?

Additionally, you may want to peruse the files in your `/etc/mullvad-vpn` (specifically, the `settings.json`, as that's where the `relay_settings` are configured). Maybe even try moving that file out of the way, and re-logging in to your Mullvad account?

**Comment by totoroot** [comment]
The logs don't show anything interesting. Just the following over and over:
```
[2022-08-01 21:50:46.619][mullvad_daemon::management_interface][DEBUG] get_settings
[2022-08-01 21:50:46.622][mullvad_daemon::management_interface][DEBUG] get_settings
[2022-08-01 21:50:46.645][mullvad_daemon::management_interface][DEBUG] get_tunnel_state
[2022-08-01 21:50:46.649][mullvad_daemon::management_interface][DEBUG] get_tunnel_state
```

I killed all processes connected to mullvad, installed the new version and removed `/etc/mullvad-vpn/settings.json`.
When I then launch mullvad again, the mentioned issues persist.

`mullvad relay get` outputs this:

```
RPC failed: Internal: failed to decode Protobuf message: LocalProxySettings.port: BridgeSettings.r#type: Settings.bridge_settings: invalid wire type: LengthDelimited (expected Varint)
```

**Comment by patricksjackson** [comment]
This issue only applied to version 2022.2. Since this was reported the package version has been reverted in the linked issue  #186743, and successfully updated to a newer release 2022.4. This issue is no longer relevant.
