### ISSUE TITLE
batik source URL is dead

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18339]
The source URL for `pkgs/applications/graphics/batik/default.nix` is http://tarballs.nixos.org/batik-1.6.zip which is a 404.

**Comment by fleimgruber** [comment]
This? `ftp://gd.tuwien.ac.at/pub/infosys/servers/http/apache/dist/xmlgraphics/batik/binaries/batik-1.6.1.zip`

**Comment by chris-martin** [comment]
I'm not sure, but it has a different hash.

**Comment by fleimgruber** [comment]
True, but `1.6.1` should be preferred, it was a security fix - see also https://xmlgraphics.apache.org/batik/download.html

**Comment by rasendubi** [comment]
http://tarballs.nixos.org is [a hashed mirror](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/mirrors.nix#L4-L6) and uses a [different algorithm for finding actual url](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/builder.sh#L65).

```
rasen@Larry ~/nixpkgs> nix-build -A batik.src --check
checking path(s) ‘/nix/store/d38wqq4v7q6vb76mbf5dg8kssk2gi0g4-batik-1.6.zip’

trying http://tarballs.nixos.org/md5/edff288fc64f968ff96ca49763d50f3c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7590k  100 7590k    0     0   617k      0  0:00:12  0:00:12 --:--:--  613k
/nix/store/d38wqq4v7q6vb76mbf5dg8kssk2gi0g4-batik-1.6.zip
```
