### ISSUE TITLE
`qt5.qtwebengine` is marked broken on `x86_64-darwin`, however maybe it can be made work?

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#183383]
### Describe the bug

`qtwebengine` is marked broken on macOS x86 for a while: https://github.com/NixOS/nixpkgs/blob/9478ec747c459cf96a46f2ae4148cc3451df65c5/pkgs/development/libraries/qt-5/modules/qtwebengine.nix#L261-L265

Apparently it is because of the `apple_sdk` version, however, it seems this issue is maybe partly resolved: https://github.com/NixOS/nixpkgs/pull/176661

Can we make this work now?

**Comment by arximboldi** [comment]
I don't have time today but I may get it a shot next week...

**Comment by arximboldi** [comment]
More references: https://github.com/NixOS/nixpkgs/issues/146385

**Comment by sikmir** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/e526bb7756039607e508982ccafe479dbdc19422
