### ISSUE TITLE
plenary.nvim is outdated 

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#183304]
###### Checklist

See https://github.com/NixOS/nixpkgs/pull/178180#issuecomment-1197726116 cc @thatsmydoing

**Comment by DieracDelta** [comment]
It seems like that `data` folder mentioned in that issue contains the mappings telescope needs to do syntax highlighting correctly. Any idea how to include it?

**Comment by teto** [comment]
related https://github.com/nvim-lua/plenary.nvim/issues/390 + assocaited PR https://github.com/nvim-lua/plenary.nvim/pull/391

**Comment by DieracDelta** [comment]
I think this can be closed once plenary is updated in nixpkgs.

**Comment by teto** [comment]
My plenary PR has been merged but seems like luarocks hasn't been updated yet https://luarocks.org/search?q=plenary&non_root=on

**Comment by teto** [comment]
Closing this since plenary in nixpkgs is from september 2022. A better fix might be https://github.com/NixOS/nixpkgs/pull/190824
