### ISSUE TITLE
Tomcat 5.0 source URL is dead

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18336]
The source for `pkgs/servers/http/tomcat/5.0.nix` is http://apache.essentkabel.com/jakarta/tomcat-5/v5.0.27/bin/jakarta-tomcat-5.0.27.tar.gz - the DNS doesn't even resolve for this anymore.

**Comment by mdorman** [comment]
That seems like something that was once redirected to, and https://archive.apache.org/dist/tomcat/tomcat-5/archive/v5.0.27/bin/jakarta-tomcat-5.0.27.tar.gz is the canonical URL.

**Comment by chris-martin** [comment]
Yep, that's the same md5.

**Comment by bjornfor** [comment]
Tomcat 5.0 is now removed (https://github.com/NixOS/nixpkgs/pull/18341).
