### ISSUE TITLE
cua-mode source URL is dead

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18338]
The source URL for `pkgs/applications/editors/emacs-modes/cua/default.nix` is http://tarballs.nixos.org/cua-mode-2.10.el which is a 404.

**Comment by fleimgruber** [comment]
> Cua-mode is part of GnuEmacs versions 22.1.1 and later (at least).

https://www.emacswiki.org/emacs/CuaMode

**Comment by rasendubi** [comment]
http://tarballs.nixos.org is [a hashed mirror](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/mirrors.nix#L4-L6) and uses a [different algorithm for finding actual url](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/builder.sh#L65).

Downloading source succeeds:
```
rasen@Larry ~/nixpkgs> nix-build -A emacsPackages.cua.src --check
checking path(s) ‘/nix/store/5jw4prhh04di7gaaqq8jip0jj8cdv5ja-cua-mode-2.10.el’

trying http://tarballs.nixos.org/md5/5bf5e43f5f38c8383868c7c6c5baca09
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  100k  100  100k    0     0   130k      0 --:--:-- --:--:-- --:--:--  556k
/nix/store/5jw4prhh04di7gaaqq8jip0jj8cdv5ja-cua-mode-2.10.el
```

**Comment by chris-martin** [comment]
Huh, thanks. That seems... extremely counterintuitive and undiscoverable to express this using URLs that aren't real URLs?
