### ISSUE TITLE
sane-frontends source URL is dead

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18340]
The source URL for `pkgs/applications/graphics/sane/frontends.nix` is ftp://ftp.sane-project.org/pub/sane/sane-frontends-1.0.14/sane-frontends-1.0.14.tar.gz and this FTP server doesn't seem to exist anymore.

**Comment by mdorman** [comment]
Seems to have moved to https://alioth.debian.org/frs/download.php/file/1140/sane-frontends-1.0.14.tar.gz?

**Comment by chris-martin** [comment]
Thanks, that checks out. I'll submit a PR.

**Comment by joachifm** [comment]
Looks like this was resolved
