### ISSUE TITLE
libjpeg-6b patch source URLs are dead

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18346]
In `pkgs/development/libraries/libjpeg/62.nix`, both patch sources are 404s:
- http://svn.macports.org/repository/macports/trunk/dports/graphics/jpeg/files/patch-ltconfig
- http://svn.macports.org/repository/macports/trunk/dports/graphics/jpeg/files/patch-ltmain.sh

**Comment by RamKromberg** [comment]
@chris-martin I think these should work:

https://trac.macports.org/browser/trunk/dports/graphics/jpeg/files/patch-ltconfig?rev=61349&format=raw

https://trac.macports.org/browser/trunk/dports/graphics/jpeg/files/patch-ltmain.sh?rev=61349&format=raw

If not, try walking revisions back in https://trac.macports.org/browser/trunk/dports/graphics/jpeg/Portfile?rev=61349 and try out different patches.

**Comment by matthewbauer** [comment]
It looks like this version has been dropped and the patches are no longer needed. Probably can be closed!

**Comment by vcunat** [comment]
Right, it looks OK, already on 16.09.
