### ISSUE TITLE
Lenovo Ideapad Z510 doesn't resume after suspend 

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#18356]
## Issue description

Lenovo Ideapad Z510 doesn't resume after suspend.

### Steps to reproduce

Close the laptop lid. Open it - system becomes unresponsive

I can type text, I can switch with Ctrl-{F1,F6}, but the only reaction from system is printing keystrokes to screen. Last line in `journalctl` is "systemd-sleep: suspend". I have to do hard reset to recover from this state.

Config is pretty minimal, system is fresh after nixos-install.

## Technical details

* System: pre 16.09

**Comment by danbst** [comment]
I forgot to mention, that Asus Eeepc 1215b with same system has suspend/resume working.

**Comment by bjornfor** [comment]
Have you tested with a different distro on this machine? (I.e. is the issue NixOS specific?)

**Comment by danbst** [comment]
@bjornfor No, I didn't, but this is still very bad UX.

As a workaround for now, I have
```
environment.etc."systemd/sleep.conf".text = lib.mkAfter ''
   SuspendState=freeze
'';
```

In that case suspend is disabled, which is still bad but better than periodic system hang.

Googling led me to think, that this is not NixOS specific, but kernel specific. I'm searching further...

**Comment by vcunat** [comment]
> this is still very bad UX.

Yes. I'm convinced the question was only meant as a clue to narrow the possibilities. I'd personally try a new kernel.

**Comment by danbst** [comment]
Figured out a buggy driver and made PR to nixos-hardware https://github.com/NixOS/nixos-hardware/pull/18

The debugging technique described in https://wiki.ubuntu.com/DebuggingKernelSuspend was really helpfull. At first I thought that disabling "nouveau" would stop xserver, but that was not the case.

In any case, this isn't NixOS problem at all.

**Comment by vcunat** [comment]
> At first I thought that disabling "nouveau" would stop xserver, but that was not the case.

X can work with various drivers. You [don't even have a nvidia GPU](http://shop.lenovo.com/us/en/laptops/lenovo/z-series/z510/#tab-tech_specs), do you?

**Comment by danbst** [comment]
Actually, yes, I have Intel integrated graphics (which loads i950 module) but nouveau was loaded because of some NVidia 3D technology. I can investigate into this more, if you are interested.

**Comment by vcunat** [comment]
Hmm, well, probably not, but it seems a bit strange to me.
