### ISSUE TITLE
bcache userspace is installed unconditionally

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#18369]
## Issue description

`nixos/modules/tasks/bcache.nix` adds `bcache-tools` to the `systemPackage` set and adds the udev rule. 
Should this be optional (at least opt-out) to allow smaller system closure?
CC @lethalman 
### Steps to reproduce

Install NixOS
Look for bcache-tools in /nix/store
## Technical details
- System: Flounder (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: 1.11.3 (run `nix-env --version`)

**Comment by aneeshusa** [comment]
I'd like `bcache-tools` to be added to `systemPackages` only if there is a filesystem using it, similar to how the `nixos/modules/tasks/filesystems/btrfs.nix`module works for `btrfs-progs`.

**Comment by Profpatsch** [comment]
I’ll close since this stagnated; feel free to reopen.
