### ISSUE TITLE
`systemctl --user` is broken in tests

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixpkgs#183629]
### Describe the bug

When running `machine.systemctl("start repro.service --wait", user="repro")` in a nixos test, we get this error:
```
machine # Failed to connect to bus: No such file or directory
```

### Steps To Reproduce

This is a small repro:
```
let
  nixpkgs = <nixpkgs>;
  pkgs = import nixpkgs { };
  homeManagerModule = pkgs.home-manager.src + "/nixos/default.nix";
in
pkgs.nixosTest ({ lib, ... }: {
  name = "repro";
  nodes.machine = {
    imports = [
      homeManagerModule
    ];
    users.users.repro = {
      isNormalUser = true;
    };
    home-manager = {
      useGlobalPkgs = true;
      useUserPackages = true;
      users.repro = {
        systemd.user = {
          startServices = true;
          services = {
            "repro" = {
              Service = {
                ExecStart = "/run/current-system/sw/bin/true";
                Type = "oneshot";
              };
            };
          };
        };
      };
    };
  };
  testScript = ''
    machine.start()
    machine.wait_for_unit("multi-user.target")

    (c, out) = machine.systemctl("start repro.service --wait", user="repro")
    print(out)
    assert c == 0
  '';
})
```

You can use `feedback -- nix-build test.nix --no-out-link` as a feedback loop.

### Expected behavior

A passing test.

### Metadata

From inside the test:

```console
 - system: `0`
 - host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `0`
```

**Comment by NorfairKing** [comment]
It would be great if we could add this nixos test so that it's not broken again in the future as well.

**Comment by nh2** [comment]
My guess:

For `systemctl --user` to work, DBUS must be running for that user. But there's nothing in the NixOS config that would result in it running for the user `repro`.

According to https://serverfault.com/questions/936985/cannot-use-systemctl-user-due-to-failed-to-get-d-bus-connection-permission/1047069#1047069 there are 3 things that commonly start DBUS for a user:

1. graphical session
2. login on terminal (username and password)
3. ssh

So I think one way to address the issue could be to start a graphical session, as is done in this KDE test:

https://github.com/NixOS/nixpkgs/blob/dfda4ec196a5b882c1e7d962d8d635a8379766aa/nixos/tests/plasma5-systemd-start.nix#L38

In the GNOME test https://github.com/NixOS/nixpkgs/blob/dfda4ec196a5b882c1e7d962d8d635a8379766aa/nixos/tests/gnome.nix#L55 `DBUS_SESSION_BUS_ADDRESS` is set directly, which may also be relevant; but I think the key thing here, too, is that a graphical session is running.

You may try to find another way to start DBUS for the user `repro` without a graphical session, which would be lighter-weight.

---

The following works for me, copying the code from `plasma5-systemd-start.nix` and putting the `DBUS_SESSION_BUS_ADDRESS` in:

```nix
let
  nixpkgs = <nixpkgs>;
  pkgs = import nixpkgs { };
  homeManagerModule = pkgs.home-manager.src + "/nixos/default.nix";
in
pkgs.nixosTest ({ lib, ... }: {
  name = "repro";
  nodes.machine = {
    imports = [
      homeManagerModule
    ];
    services.xserver = {
      enable = true;
      displayManager.sddm.enable = true;
      displayManager.defaultSession = "plasma";
      desktopManager.plasma5.enable = true;
      desktopManager.plasma5.runUsingSystemd = true;
      displayManager.autoLogin = {
        enable = true;
        user = "repro";
      };
    };
    users.users.repro = {
      isNormalUser = true;
      uid = 1000;
    };
    home-manager = {
      useGlobalPkgs = true;
      useUserPackages = true;
      users.repro = {
        systemd.user = {
          startServices = true;
          services = {
            "repro" = {
              Service = {
                ExecStart = "/run/current-system/sw/bin/true";
                Type = "oneshot";
              };
            };
          };
        };
      };
    };
  };
  testScript = { nodes, ... }:
    let
      user = nodes.machine.config.users.users.repro;
      uid = toString user.uid;
    in
      builtins.trace uid ''
        machine.start()
        machine.wait_for_unit("multi-user.target")

        with subtest("Wait for login"):
            start_all()
            machine.wait_for_file("${user.home}/.Xauthority")
            machine.succeed("xauth merge ${user.home}/.Xauthority")

        with subtest("Check plasmashell started"):
            machine.wait_until_succeeds("pgrep plasmashell")
            machine.wait_for_window("^Desktop ")

        machine.succeed("sudo -u repro DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${uid}/bus systemctl --user start repro.service --wait")
      '';
})
```

**Comment by NorfairKing** [comment]
@nhI think it's possible to make this work

**Comment by NorfairKing** [comment]
Ok I figured it out, here is the result with a bunch of comments:
```
let
  nixpkgs = <nixpkgs>;
  pkgs = import nixpkgs { };
  homeManagerModule = pkgs.home-manager.src + "/nixos/default.nix";
in
pkgs.nixosTest
{
  name = "repro";
  nodes.machine =
    ({ lib, config, ... }: {
      imports = [
        homeManagerModule
      ];
      users.users.repro = {
        isNormalUser = true;
      };
      # We must enable lingering so that the Systemd User D-Bus is enabled.
      # We also cannot do this with loginctl enable-linger because it needs to happen before systemd is loaded.
      # It would be nice if there were a nixos option for this.
      # See https://github.com/NixOS/nixpkgs/issues/3702
      system.activationScripts = {
        enableLingering = ''
          # remove all existing lingering users
          rm -rf /var/lib/systemd/linger
          mkdir -p /var/lib/systemd/linger
          # enable for the subset of declared users
          touch /var/lib/systemd/linger/repro
        '';
      };
      home-manager = {
        users.repro = {
          # We must enable xdg so that the ~/.config directory exist
          # Because the systemd user services are stored in .config/systemd/user
          # and home manager will fail to put them there otherwise.
          xdg.enable = true;
          systemd.user = {
            services = {
              "repro" = {
                Service = {
                  ExecStart = "/run/current-system/sw/bin/true";
                  Type = "oneshot";
                };
              };
            };
          };
        };
      };
    });
  testScript = ''
    machine.start()
    machine.wait_for_unit("multi-user.target")

    (c, out) = machine.systemctl("start repro.service --wait", user="repro")
    print(out)
    assert c == 0
  '';
}
```

So we need to:

1. Enable lingering so that the Systemd User D-Bus is running when we run the start command.
2. Enable xdg so that home manager has a place to put the unit files

**Comment by NorfairKing** [comment]
You can use this to enable lingering for all users;
```
system.activationScripts = {
          enableLingering =
            let touchUserLinger = username: _: "touch /var/lib/systemd/linger/${username}";
            in
            ''
              # remove all existing lingering users
              rm -rf /var/lib/systemd/linger
              mkdir -p /var/lib/systemd/linger
              # enable for the subset of declared users
              ${lib.concatStringsSep "\n" (lib.mapAttrsToList touchUserLinger config.users.users)}
            '';
        };

```

**Comment by georgefst** [comment]
> It would be great if this could be a nixos option.

Agreed! Your workaround cleared the final hurdle for me to be able to stop running all my services as root, on a headless device where there are often no user logged in.

**Comment by georgefst** [comment]
Okay, I spoke slightly too soon. This didn't do quite what I expected.

In particular, multiple instances (up to 46!) of some services are started at boot. This is presumably since `config.users.users` has 47 members, including `avahi`, `dhcpcd`, `root`, `sshd`, `systemd-coredump`, and `nixbld1` all the way up to `nixbld32`.

Then again, to be fair, there's nothing in the specification of these user units that says they should only run for one particular user (and I wouldn't even know _how_ to do this without https://github.com/NixOS/nixpkgs/issues/26128), so maybe my whole approach is just misguided, and if I want only one copy of each service I should just run them as root. Anyway, I'm now only enabling lingering for a single user, and everything seems to be fine.

**Comment by georgefst** [comment]
This workaround also seems to be causing relevant units not to be automatically restarted after a system rebuild.
