### ISSUE TITLE
qt5Full broken on master and release-16.09

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#18367]
## Issue description
```
$ nix-build -A qt5Full
these derivations will be built:
  /nix/store/wrl9v5rygw4ackxw4h2nln46nll9i5cf-qt-5.6.1-1.drv
building path(s) ‘/nix/store/1ak5cvnmvnmsbxbgl58mbrhfwr657xrb-qt-5.6.1-1’
cp: cannot stat '/nix/store/pjw2nfhk6plffb1imyznnjbsq4sfvv4l-qtbase-5.6.1-1/bin/qmake': No such file or directory
builder for ‘/nix/store/wrl9v5rygw4ackxw4h2nln46nll9i5cf-qt-5.6.1-1.drv’ failed with exit code 1
error: build of ‘/nix/store/wrl9v5rygw4ackxw4h2nln46nll9i5cf-qt-5.6.1-1.drv’ failed
```

**Comment by bjornfor** [comment]
Seems like a multiple-outputs issue (there is no "bin/qmake" here):

```
$ ls -l /nix/store/pjw2nfhk6plffb1imyznnjbsq4sfvv4l-qtbase-5.6.1-1/
total 8
dr-xr-xr-x 3 root root 4096 jan.   1  1970 lib
dr-xr-xr-x 3 root root 4096 jan.   1  1970 share
```

**Comment by dezgeg** [comment]
Does https://github.com/dezgeg/nixpkgs/commit/cfe790c48614a70e20f125727d3fcdaec840eb88 fix it?

**Comment by bjornfor** [comment]
Yes, that fixes it (```nix-build -A qt5Full``` == success).

**Comment by dezgeg** [comment]
I was wondering more about whether the contents are correct or not.

**Comment by bjornfor** [comment]
I don't remember the old structure (and is cumbersome to reproduce -- how far back do I have to go to get something to build?). At least 'qmake' is in the bin/ directory with your fix. And more importantly, I was able build an example qt app inside ```nix-shell -p qtcreator gcc qt5Full gnumake```. So yes, I think this is a good fix.

I'm running nox-review with this patch to check if there are any breakage (I'm paranoid when it comes to regressions), but I guess it cannot break more than the current state ;-) So please push it if you like.

**Comment by dezgeg** [comment]
D'oh, it indeed does have a reverse dependency in the repo (`multimc`) which does build now.  Pushed to master & release-16.09.

**Comment by bjornfor** [comment]
@dezgeg: Thanks!
