### ISSUE TITLE
xcode-wrapper fails because of non-existing path

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#18389]
## Issue description

I tried to build some package that uses xcode-wrapper and it fails with:

```
Error: /Applications/Xcode.app/Contents/Developer/Applications/iOS Simulator.app/Contents/MacOS/iOS
Simulator does not exist. Check that XCode is installed.
```

I do have XCode installed and I have the file `/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator` - so it is `Simulator` instead of `iOS Simulator`.

I have XCode `Version 7.3.1 (7D1014)` installed running on El Capitain 10.11.6 (15G31)
### Steps to reproduce

I ran into this in a quite specific setup and sadly I lack the insight to produce some minimal setup to reproduce this.
## Technical details
- System: El Capitain 10.11.6 (15G31) / XCode `Version 7.3.1 (7D1014)
- Nix version: 1.11.4
- Nixpkgs version: 16.09pre90369.202d9e2

**Comment by matthewbauer** [comment]
I think iOS Simulator is still available under XCode Components but you have to download it separately.

**Comment by mjhoy** [comment]
Excuse my ignorance, what is `xcode-wrapper`?

I definitely have the iOS simulator installed, but it is not at the location you give. Possible that the tool needs to be updated?

**Comment by mjhoy** [comment]
Ah! This: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/mobile/xcodeenv/xcodewrapper.nix

It looks like it was updated in https://github.com/NixOS/nixpkgs/commit/b6d84748b913c9ffc9937ec64ca868cffa8797b4 to use the updated path to the simulator.

**Comment by matthewbauer** [comment]
Is it ok to close this?
