### ISSUE TITLE
bundlerEnv should have defaults for gemfile, lockfile and gemset

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#18384]
## Issue description

When using the `bundlerEnv`, everybody has to set the same variables:

``` nix
inherit ruby;
gemfile  = ./Gemfile;
lockfile = ./Gemfile.lock;
gemset   = ./gemset.nix;
```

Can't we set defaults here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ruby-modules/bundler-env/default.nix#L9

cc: @cstrahan 
## Technical details
- NixOS: 16.09.git.0b1fad6M (Flounder)
- Nix: nix-env (Nix) 1.11.3
- nixpkgs: 16.09pre89269.8512747

**Comment by joachifm** [comment]
What do you have in mind? Setting `gemfile = ./Gemfile` in `bundler-env/default.nix` won't work.

**Comment by peterhoeg** [comment]
I had a sneaky suspicion things weren't going to be that easy or they would probably already have been done, which is why I opened an issue to ask.

Will ```gemfile = ./Gemfile``` not work because that would end up being ```bundler-env/Gemfile```? What if we pass it as a string ```gemfile = "./Gemfile"``` - would it then be relative to the actual environment or am I getting that wrong?

**Comment by joachifm** [comment]
You're correct. `./Gemfile` copies the file at that position in the file system hierarchy, relative to the expression. Using a string would require additional work to actually create the store paths, I expect you'd end up with the same amount of code, if not more (unless I'm thinking about it in a backwards way).

A common solution is to generate Nix expressions. Macros would make this kind of thing much easier.

I'm sure others with more experience in this area can chime in with ideas on how to do this, I have none.

**Comment by joachifm** [comment]
cc @zimbatm

**Comment by zimbatm** [comment]
cc @manveru
 
We could extend the bundlerEnv interface to also accept a `src` argument. In that case the typical usage would be:
```nix
bundlerEnv {
  name = "...";
  src = ./.;
}
```

It's something we would need anyways if we want to support the `path` directive in the Gemfile (provided it points within the src).

**Comment by peterhoeg** [comment]
We now have support for ```gemdir``` so this is moot.
