### ISSUE TITLE
Login screen blanks out on fresh install - Framework Intel 12 Gen

### ISSUE THREAD

**Issue by munyari** [NixOS/nixpkgs#183955]
## Issue description
I have a new Framework laptop. I ran the graphical installer of a Live USB to install Nix 22.05 with Gnome, and that ran to completion just fine. After installation and rebooting, I see the login prompt for a few seconds, but this disappears and the whole screen blanks out, leaving a blinking cursor in the top right. 

### Steps to reproduce
1. Make a USB live image with NixOS 22.05
2. Insert and install on Framework Laptop with Intel 12th Gen
3. Reboot

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by munyari** [comment]
I've also posted about this on the framework forum https://community.frame.work/t/nixos-login-screen-blanks-out-on-fresh-install-framework-intel-12-gen/20747

**Comment by munyari** [comment]
And a video https://www.dropbox.com/s/4t3wc08rrijxh2c/2022-07-30%2008.33.13.mp4?dl=0

**Comment by sputn1ck** [comment]
I successfully installed NixOS on my framework 12th gen. 

I encountered the same problem as you. What I did was press `ctrl+alt+f1` to get in a terminal and update my `configuration.nix` with the line `
  boot.kernelPackages = pkgs.linuxPackages_5_18;`. I also disabled secure boot in the BIOS.

**Comment by munyari** [comment]
Thanks @sputn1ck! I ended up installing KDE instead of Gnome, and it worked fine.
