### ISSUE TITLE
acme: Fails to build if port 1234 is in use

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixpkgs#18399]
## Issue description

At least one of the acme standalone tests binds to port 1234. If this port was in use, then the tests will fail and acme will fail to build.

### Steps to reproduce
```
netcat -l -p 1234 &
nix-build "<nixpkgs>" -A pythonpackages.acme
```

## Technical details

* System: 16.09pre90208.f19c961 (Flounder)
* Nix version: nix-env (Nix) 1.11.3
* Nixpkgs version: 16.09pre90254.6b20d5b

## Suggested solution

The most reliable solution should be to run builds in a separate networking namespace, aka. partial containerization.

This can be done relatively trivially with `ip netns`. Example:

```
netcat -lp 1234 &
# Port 1234 is now in use. Try to use it again...
netcat -lp 1234 # Will fail.

# Setup a new networking namespace:
NS=$(dd if=/dev/urandom count=1 bs=64 | sha256sum | awk '{print $1}')
ip netns add $NS
ip netns exec $NS bash

# We're now in a totally distinct namespace!
ping 8.8.8.8  # Will fail, unless you make an effort to connect it. That's positive though, right?
netcat -lp 1234  # Succeeds! Success.
exit

# Clean up.
ip netns del $NS
```

This is something that would be best applied to *everything*, necessitating a mass rebuild. Additionally, it requires root access to set things up. A suitable compromise might be to run the nixbld users in distinct namespaces, one per user.

**Comment by vcunat** [comment]
And do you run the builds with sandboxing on? IIRC it does use network namespaces.

**Comment by Baughn** [comment]
Right you are, that's already implemented. Now I feel silly.

Unfortunately, turning it on breaks the kinda-impure builds in a user account, but.. I should be fixing those anyway.
