### ISSUE TITLE
didyoumean: 1.1.0 -> 1.1.3

### ISSUE THREAD

**Issue by hisbaan** [NixOS/nixpkgs#184088]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: didyoumean

current version: 1.1.0
desired version: 1.1.3

###### Notify maintainers

maintainers: @evanjs 

###### Note for maintainers

Version 1.1.3 comes with a man page as well as shell completions for a few shells (bash, zsh, fish, elvish). I'd like to have the script install these. I'm more than willing to do the actual update myself, but I'm very new to Nix, so I'll probably need some guidance, specifically on how to install these completions and the man page, and how to update the `sha256` hash.

Thanks!

**Comment by wegank** [comment]
- To update the `sha256` hash, you can simply set `sha256 = "";` and `cargoSha256 = "";`, and update them as suggested by `nix build .#didyoumean`. Having done it right, you'll have
```nix
  src = fetchFromGitHub {
    owner = "hisbaan";
    repo = "didyoumean";
    rev = "v${version}";
    sha256 = "sha256-hHl9PGNDFN7Dad2JOlAy99dz0pC9OmphwYMJHBBwx7Y=";
  };

  cargoSha256 = "sha256-rjkj9MO6fXVOk3fA87olGt/iIaJ8Zv/cy/Cqy/pg6yI=";
```
- To install the man page and the shell completions, set
```nix
  nativeBuildInputs = [
    installShellFiles
  ];

  postInstall = ''
    installManPage man/dym.1
    installShellCompletion completions/dym.{bash,fish}
    installShellCompletion --zsh completions/_dym
  '';
```
- You may also need to set `doCheck = false;` on some platforms (at least on `aarch64-darwin`?). Before doing this, feel free to make a pull request.

**Comment by hisbaan** [comment]
I'm running into some issues trying to test it to ensure it's doing what I want it to. I'm going to the directory with `didyoumean/default.nix` in it and running `nix-build` but I'm running into issues regarding `installShellFiles` being undefined:
```
error: undefined variable 'installShellFiles'

       at /home/hisbaan/projects/nixpkgs/pkgs/tools/misc/didyoumean/default.nix:34:25:

           33|
           34|   nativeBuildInputs = [ installShellFiles ];
             |                         ^
           35|   postInstall = ''
```
Any pointers? I wasn't able to find anything searching through the web

**Comment by winterqt** [comment]
`installShellFiles` needs to be in the attrset at the top of the file for you to be able to use it.

**Comment by wegank** [comment]
As @winterqt explained, we need to add

```nix
, installShellFiles
```

at the top of the file.
