### ISSUE TITLE
wifi flakey on 16.09beta

### ISSUE THREAD

**Issue by mogorman** [NixOS/nixpkgs#18410]
## Issue description
every few hours wifi quits on my machine.  i see this in my logs 
```
[ 6945.686202] wlan0: deauthenticating from f4:f2:6d:63:99:2b by local choice (Reason: 3=DEAUTH_LEAVING)
```
i then have to reenable wifi support in network-manager to get it to going again, it reconnects to my network without any problem.  I was running the pkgs.linuxPackages_4_7 on 16.03 before hand. and not having this issue.

### Steps to reproduce
is my wifi card
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 83)

## Technical details
Linux toadman 4.7.2 #1-NixOS SMP Sat Aug 20 16:11:18 UTC 2016 x86_64 GNU/Linux
16.09beta133.ebe7f35 (Flounder)
nix-env (Nix) 1.11.4
"16.09beta133.ebe7f35"

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by mogorman** [comment]
[ 6987.278556] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[ 7437.049926] wlan0: deauthenticating from f4:f2:6d:63:99:2b by local choice (Reason: 3=DEAUTH_LEAVING)
[ 7506.933213] iwlwifi 0000:03:00.0: L1 Enabled - LTR Enabled
[ 7506.933819] iwlwifi 0000:03:00.0: L1 Enabled - LTR Enabled
[ 7507.145790] iwlwifi 0000:03:00.0: L1 Enabled - LTR Enabled
[ 7507.146556] iwlwifi 0000:03:00.0: L1 Enabled - LTR Enabled
[ 7507.174499] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 7507.204254] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[ 7510.449621] wlan0: authenticate with f4:f2:6d:63:99:2b
[ 7510.454367] wlan0: send auth to f4:f2:6d:63:99:2b (try 1/3)
[ 7510.455746] wlan0: authenticated
[ 7510.455960] wlan0: associate with f4:f2:6d:63:99:2b (try 1/3)
[ 7510.457072] wlan0: RX AssocResp from f4:f2:6d:63:99:2b (capab=0x11 status=0 aid=2)
[ 7510.458434] wlan0: associated
[ 7510.458518] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready

**Comment by mogorman** [comment]
transferring more data across the link seems to make it happen faster but I can't reliably make the error happen yet

**Comment by mogorman** [comment]
has not been a problem since i disabled powersave via modprobe. but I did not have the need of this setting before.

**Comment by teh** [comment]
Thanks for reporting this! I suspect this is a kernel issue, not a NixOS issue, and there are several upstream bugs already (links in [1]). I think we can close this here if you are OK with that? If anyone else has the same issue they'll still find your bug and your solution in Google.

[1]
http://askubuntu.com/questions/616119/unstable-wireless-with-intel-7260-iwlwifi-after-upgrade-to-15-04

**Comment by mogorman** [comment]
ya thats fine, i just wanted to flag it as it was a change and thought others might hit it
