### ISSUE TITLE
Issues brought on by open source Radeon Driver.

### ISSUE THREAD

**Issue by volkswagen** [NixOS/nixpkgs#1842]
This is just a fresh install with flashplayer and scrot as the only applications I have installed.  My GPU is a Radeon HD Mobile 4200 and kernel version 3.10.31.

On Nixos version 14.02pre39818.c11f32a (Baboon) I have downloaded flashplayer and configured Konquerer to the location of the plugin. 

When viewing videos on Youtube the button "small player" and "large player" when clicked do nothing.

And videos have a blueish tint to them.  The Youtube thumbnail and the video suggestions on the side displays the correct  color  but the video displays the tint.  This is a problem from Adobe which was fixed in later versions of flash, and can be easily fixed in version 11 if the user turns off hardware acceleration.

Also flash pop-ups that display the capatcha slogans dont work properly, the capctcha slogans do not show what you are supposed to type in, preventing log-ins on sites that require authenticity with that service.

When a flash menu or pop up comes up, the theme falls back to the systems fall back theme, this can be seen by right clicking on a Youtube video and also when uploading a photo to a social network or photo networking site.

I took screen shots, however all of the upload picture sites have the flash capatches, and those wont show what to type in.

**Comment by vcunat** [comment]
I just tested the default settings on a recent version: open-source driver on an AMD integrated GPU, firefox, youtube with flash and HW acceleration enabled, FullHD video. It seems fine, and almost no CPU is used.

Reopen if you still can reproduce it (releases older than 14.12 are probably unsupported now).
