### ISSUE TITLE
libproxy: build failure on darwin

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#184328]
### Steps To Reproduce
1. `nix build nixpkgs#libproxy`

### Build log
```
CMake Error at libproxy/cmake/modules/pacrunner_duktape.cmk:10 (px_check_modules):
  Unknown CMake command "px_check_modules".
Call Stack (most recent call first):
  libproxy/cmake/modules.cmk:21 (include)
  libproxy/CMakeLists.txt:14 (include)


-- Configuring incomplete, errors occurred!
```

See [Hydra](https://hydra.nixos.org/job/nixpkgs/trunk/libproxy.x86_64-darwin).

### Additional context

- Regression of #181917
- Blocks: #157874
- Blocks: porting GSound and GNOME Clocks to macOS
- Notify upstream: libproxy/libproxy#161

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by jiegec** [comment]
A possible fix:

```diff
diff --git a/libproxy/cmake/pkgconfig.cmk b/libproxy/cmake/pkgconfig.cmk
index 89bfc62..ffa0897 100644
--- a/libproxy/cmake/pkgconfig.cmk
+++ b/libproxy/cmake/pkgconfig.cmk
@@ -1,4 +1,4 @@
-if(NOT WIN32 AND NOT APPLE)
+if(NOT WIN32)
   find_package(PkgConfig)
 
   # Define our magical px_check_modules function

```

**Comment by jtojnar** [comment]
That looks like an upstream bug – the build system should never use functions it is undefining.

And either way, on Darwin, I would expect system JavaScriptCore to be used instead of Duktape.
