### ISSUE TITLE
Building `libreoffice` with `gdb` in `buildInputs` could be useful

### ISSUE THREAD

**Issue by 7c6f434c** [NixOS/nixpkgs#18431]
LibreOffice build process seems to support using `gdb` to report failures. Currently `gdb` is an argument to the expression (just because there is no harm in it), but it is not used by default. In case of a failure that means one more LibreOffice rebuild than necessary.

I propose either adding `gdb` as a build input or at least adding it to `$PATH` in `preBuild`. I think the second option should not make `gdb` included in the closure (and I hope even the first approach would be fine). Of course, it is an extra build dependency.

Are there any arguments against such a change? Is anyone against adding such a build dependency?

**Comment by 7c6f434c** [comment]
Experiment shows that `gdb` in `buildInputs` doesn't affect the run-time closure.

**Comment by Profpatsch** [comment]
@7c6f434c do you want to prepare a pull request?

**Comment by 7c6f434c** [comment]
Hm. I think I have since silently included this change into one of the bumps. Will move `gdb` from `buildInputs` to `nativeBuildInputs` as a part of cleanup of the current mess…
