### ISSUE TITLE
slack: blank screen on startup, nothing happens when using menu

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nixpkgs#18433]
## Issue description

When starting slack the top menu and a blank screen is shown. None of the buttons does anything in the top menu except for the about button.

Here's what it looks like when I start it from my terminal:

![Screenshot](http://i.imgur.com/6f9MkLv.png)

Starting slack with logging and debug log level (`slack -l . -g debug`) creates two log files. On for the browser process and one for the rendering process.

In `browser.log` there are two errors:

```log
2016-09-08T12:14:20.302Z - info: Creating local storage instance at path: /home/rzetterberg/.config/Slack/local-settings.json
2016-09-08T12:14:20.303Z - error: Couldn't load /home/rzetterberg/.config/Slack/local-settings.json: ENOENT: no such file or directory, open '/home/rzetterberg/.config/Slack/local-settings.json'
2016-09-08T12:14:20.447Z - error: Couldn't initialize keytar: Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory Check to make sure that all native keytar dependencies are installed properly (especially libgnome-keyring on Linux)
```

Inside the `renderer-xxx.log` there is a javascript exception catched by [bugsnag](https://bugsnag.com/):

```log
  "stacktrace": "TypeError: path must be a string or Buffer\n    at TypeError (native)\n    at Object.fs.readdirSync (fs.js:945:18)\n    at Object.fs.readdirSync (ELECTRON_ASAR.js:496:28)\n    at Function.getInstalledLanguages (/src/renderer/dictionary-sync.js:323:49)\n    at Function.createDictionariesForInstalledLanguages (/src/renderer/dictionary-sync.js:242:63)\n    at new ContextMenuBuilder (/src/renderer/context-menu-builder.js:54:51)\n    at ContextMenuBehavior.setup (/src/renderer/behaviors/context-menu-behavior.js:40:30)\n    at behaviors.forEach.behavior (/src/renderer/components/web-view-ctx.jsx:139:37)\n    at Array.forEach (native)\n    at WebViewContext.componentDidMount (/src/renderer/components/web-view-ctx.jsx:138:20)",
```

### Steps to reproduce

1. Use NixOS unstable
2. Install slack `nix-env -iA nixos.pkgs.slack` 
3. Delete `~/.config/Slack` if it exists, to make sure there aren't any old settings
4. Start slack `slack`

## Technical details

* Slack version: 2.1.0
* System: NixOS unstable 16.09pre90254.6b20d5b (Flounder)
* Nix version: 1.11.3

**Comment by BonBonSlick** [comment]
Same issue for me debian stretch 9

**Comment by vcunat** [comment]
Now is not a good moment to test, according to https://status.slack.com/

**Comment by BonBonSlick** [comment]
Yeah, servers was down, laggy :)
