### ISSUE TITLE
containers that require networking during startup fail

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#18440]
## Issue description

Currently the host side of the networking is setup during `ExecStartPost`. That means that networking is only available **after** the container finished startup.
If the container has a service that **requires** routable networking configured to be part of it's `default.target`, the startup will wait for the routes to be created and the routes will wait for the startup to finish, resulting in a deadlock and eventually container startup timeout.
## Use case

A container that uses the `acme` client
### Steps to reproduce
- Add to `configuration.nix`:

```
containers.test = {
  privateNetwork=true;
  hostAddress = '10.1.1.1';
  localAddress = '10.1.1.2';
  autoStart = true;
  config = {config,pkgs,...}: {
    security.acme.certs."example.com" = { };
  };
};
```
- nixos-rebuild switch
## Technical details
- System: Gorilla
- Nix version: 1.11.4
- Nixpkgs version: master

**Comment by Jookia** [comment]
This happens on my system too, reverting to container code used a few months ago 'fixes' it

**Comment by bqv** [comment]
no longer an issue?

**Comment by m1cr0man** [comment]
I don't believe so, but I will test it
