### ISSUE TITLE
I need to override init= for systemd-bootchart

### ISSUE THREAD

**Issue by RamKromberg** [NixOS/nixpkgs#18445]
I'm trying to package systemd-bootchart (https://github.com/systemd/systemd-bootchart) and I need to override the _init=_ pid0 kernel parameter. Unlike the many alternative init issues raised in the past (https://github.com/NixOS/nixpkgs/issues/18082 recently), systemd-bootchart is part of systemd and should be made a part of the module so it could be a simpler case to solve.

Currently, I got most of the boring stuff mostly worked out in a wip module (https://gist.github.com/RamKromberg/21f64797e972564139c8ac84c364b943) except for sticking it all into the systemd unit (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/systemd.nix) so the conf file will actually get written. While I could just link that conf elsewhere, overriding the _init=_ kernel command line isn't so straightforwards.

So, any thoughts?

p.s. Also, if anyone wants to pick up it where I left it off and push it on their own, I won't mind :D

**Comment by groxxda** [comment]
Have a look at #16930 #16902
Especially https://github.com/NixOS/nixpkgs/pull/16930/commits/df9c91c3acb36afd3140e3416ef7ddca9b4090ba

**Comment by RamKromberg** [comment]
@groxxda well, at least my options part is fuller... :/ I'll close this up and move things to those other PRs.
