### ISSUE TITLE
Alias TrueZen-nvim is still in vim-plugins

### ISSUE THREAD

**Issue by minijackson** [NixOS/nixpkgs#184552]
### Describe the bug

Building the TrueZen-nvim plugin on nixpkgs master leads to the evaluation error:

```
error: Alias TrueZen-nvim is still in vim-plugins
```

### Steps To Reproduce
1. `nix build '.#vimPlugins.TrueZen-nvim'`

### Expected behavior

TrueZen-nvim builds.

### Additional context

It seems that the `TrueZen-nvim` attribute is deprecated, but the new attribute (`true-zen-nvim`) does not exist in `generated.nix`. I'm not sure what's going on here.

The change originates from https://github.com/NixOS/nixpkgs/pull/183091, but TrueZen-nvim was updated automatically.

### Notify maintainers

@teto since it seems like an update script issue?

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.05 (Quokka), 22.05.20220727.d9536b9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos-22.05"`
 - channels(minijackson): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
I've got my hands full at the moment so feel free to take a stab at it.
