### ISSUE TITLE
Linux 4.7.3 keyboard not working

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#18451]
## Issue description
Linux Kernel 4.7.3 seems broken, as my laptops keyboard doesn't work.
experienced by the arch community too: https://bugs.archlinux.org/task/50700

### Steps to reproduce
update, reboot - 4.6 and 4.7.2 work, 4.7.3 doesn't

## Technical details
* nixos-version: 17.03.git.8179a23 (Gorilla)
* nix-env --version: nix-env (Nix) 1.11.4
* nix-instantiate --eval github/nixpkgs -A lib.nixpkgsVersion: "17.03.git.515bc7c"

**Comment by Mic92** [comment]
Same issue with kernel 4.4.20 (lts). I can no longer enter my cryptsetup password.

**Comment by ikervagyok** [comment]
@Mic92 Thanks, created a quick fix with your solution, which should fix it for everyone
