### ISSUE TITLE
opentabletdriver package crashes due to missing GSettings schema path

### ISSUE THREAD

**Issue by tewkanz** [NixOS/nixpkgs#184652]
### Describe the bug
If you install the opentabletdriver package, then click the Load Settings menu option, the application crashes trying to find the GSettings for the file picker.

I'm pretty new to nix, so I don't know if maybe I'm missing some configuration? :)

### Steps To Reproduce
1. ``nix-shell -p opentabletdriver``
2. ``otd-gui``
3. Click File => Load Settings
4. ``(OpenTabletDriver.UX.Gtk:118957): GLib-GIO-ERROR **: 17:47:44.092: No GSettings schemas are installed on the system
Aborted (core dumped)``

### Expected behavior
The file picker opens.

### Additional context
I was able to fix this with the following overlay
```nix
(self: super: {
    opentabletdriver = super.opentabletdriver.overrideAttrs (old: {
        nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.gtk3 ];
        preFixup = (old.preFixup or "") + ''
            makeWrapperArgs+=("--prefix XDG_DATA_DIRS: \"$GSETTINGS_SCHEMAS_PATH");
            '';
    });
})
```

### Notify maintainers
@thiagokokada 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.05 (Quokka), 22.05.2099.1e5d0fbd82f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
```

**Comment by thiagokokada** [comment]
> I'm pretty new to nix, so I don't know if maybe I'm missing some configuration? :)

Yeah, I think you're missing some configuration, because it works fine for me:

![2022-08-02_09-45-29-screenshot](https://user-images.githubusercontent.com/844343/182332914-03b45ccc-0a7b-4ab9-8432-4648ec95edf0.png)

CC @jtojnar, maybe he knows the reason and if we should add the `--prefix XDG_DATA_DIRS: "$GSETTINGS_SCHEMAS_PATH"` or not.

**Comment by jtojnar** [comment]
Looks like opentabletdriver correctly uses `wrapGAppsHook` as [required](https://nixos.org/manual/nixpkgs/stable/#sec-language-gnome) for apps using GTK:

https://github.com/NixOS/nixpkgs/blob/8849b7ae5c1c1fa1da78edb625b2c8b95def3add/pkgs/tools/X11/opentabletdriver/default.nix#L45

but looks like the `${gtk3}/share/gsettings-schemas/${gtk3.name}` is missing from `XDG_DATA_DIRS` in the `bin/otd-gui` wrapper. Probably because `buildDotnetModule` is doing something weird again.

cc @IvarWithoutBones

**Comment by IvarWithoutBones** [comment]
I cannot currently test this, but the issue might be because `gtk3` is only in `runtimeDeps`, and not in `buildInputs`.

**Comment by thiagokokada** [comment]
> I currently cannot test this, but the issue might be because `gtk3` is only in `runtimeDeps`, and not in `buildInputs`.

Is there any reason they should not be the same by default :thinking: ?

**Comment by thiagokokada** [comment]
Adding `gtk3` to `buildInputs` seems to do the trick. I decided to make `buildInputs = runtimeDeps` since this should avoid forgetting to add something in the future, but I am not sure if this will cause any problems.

CC @IvarWithoutBones.

**Comment by jtojnar** [comment]
It looks like it might actually be a bug in `wrapGAppsHook` – it should already propagate `gtk3`. I would expect `wrapGAppsHook.tests.basic` to include the GTK schemas but it looks like it only does that when `gobject-introspection` is also present like in `wrapGAppsHook.tests.typelib-user`.

**Comment by tewkanz** [comment]
FWIW, I updated my overlay to only include ``nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.glib ];`` without messing with ``makeWrapperArgs`` based on what's done in the inkscape package, and that seemed to be enough as well. Inkscape uses uses ``wrapGAppsHook`` as well, though it doesn't list ``gtk3`` as a dependency at all.

**Comment by thiagokokada** [comment]
Merged #184846, however will keep this issue open since @jtojnar mentioned the possibility of this being a bug in `wrapGAppsHook`.

**Comment by tewkanz** [comment]
I can confirm that the directory containing the settings schemas is getting correctly added to the wrapper's XDG_DATA_DIRS environment variable, and it no longer crashes after removing my overlay. Thanks!

**Comment by Artturin** [comment]
bug prolly got fixed by https://github.com/nixos/nixpkgs/commit/2c471e647963e8bf50934580fe38c5ea176c6b34
