### ISSUE TITLE
[question] Surge (synth) binary location

### ISSUE THREAD

**Issue by thomasheartman** [NixOS/nixpkgs#184653]
## Issue description

[This is really more of a question than an issue, but I didn't know where else to take. Please point me in the right direction if it's not here.]

When building the Surge package, where do the files/binaries get symlinked from? I want to use the synth in my daw, but I need to point the daw at a directory that contains plugins: where should I point it? 

I found the files in the nix store, so I can point it there, but that definitely does not feel like the right place to point it.

@magnetophon @orivej You're listed as maintainers, so I'll tag you in here. Apologies if this is not expected here.

### Steps to reproduce

1. Add Surge to a system configuration
2. Build the system
3. See no obvious location to locate the plugin

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.198, NixOS, 21.11 (Porcupine), 21.11.337971.a1fe662eb26`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(thomas): `"dhall, nixos-unstable-22.11pre396318.7b9be38c725, nixpkgs"`
 - channels(root): `"nixos-21.11.337971.a1fe662eb26, nixos-unstable-22.11pre396318.7b9be38c725, nixpkgs-22.11pre396356.67f49b2a385"`
 - nixpkgs: `/home/thomas/.nix-defexpr/channels/nixpkgs`
```

**Comment by magnetophon** [comment]
The correct locations are here:
https://github.com/musnix/musnix/blob/master/modules/base.nix#L68-L75
Musnix has many usefull tweaks for musicians, I suggest using it.

**Comment by thomasheartman** [comment]
Thanks! And I wasn't aware of musnix, so I'll give that a go too 😄
