### ISSUE TITLE
assertion failed in setuid-wrapper.c:34

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#18474]
## Issue description
```
$ light --help
light: setuid-wrapper.c:34: main: Assertion `(strncmp(self, wrapperDir, strlen(wrapperDir)) == 0) && (self[strlen(wrapperDir)] == '/')' failed.
zsh: abort      light --help

$ sudo systemctl --help
sudo: setuid-wrapper.c:34: main: Assertion `(strncmp(self, wrapperDir, strlen(wrapperDir)) == 0) && (self[strlen(wrapperDir)] == '/')' failed.
```

### Steps to reproduce
 1. Try using a program that utilizes setuid-wrapper
 2. Watch it fail!

## Technical details
* System: 16.09pre90254.6b20d5b (Flounder)
* Nix version: nix-env (Nix) 1.11.3
* Nixpkgs version: "17.03.git.190b1d1"

**Comment by siddharthist** [comment]
To be clear, this prevents the use of `systemctl` and `sudo`, which should probably be considered a major bug.

**Comment by siddharthist** [comment]
I just upgraded and `nixos-rebuild switch`ed, and the problem resolved itself. 

 * 17.03.git.ffddcc8 (Gorilla)

**Comment by Rotsor** [comment]
This error message means that the setuid wrapper binary is not in the directory where it's supposed to be.

One possible reason to have it be in the wrong directory is that pre-a6670c1a0b8cda8235296900cff950f39f60cf4f activate script is broken if used in a post-that-commit environment.
