### ISSUE TITLE
Nixpkgs no longer works on Mac OS <=10.9

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#18472]
I broke our main compatibility layer in https://github.com/NixOS/nixpkgs/commit/948b7f23bbc42a87e66a473c5c4543cfa5a03da7, since I don't really feel like supporting it and didn't think the effort was worth it for how few Mac users keep their machines on older systems.

Looking for feedback from people who think this is a bad idea and want support for old Darwin versions. It might be possible to revive the old approach, or by inserting other compatibility shims to approximate the syscall variations between kernels.

**Comment by matthewbauer** [comment]
I think trying to support older versions is going to be a losing battle. Once you've upgraded, there's not really a way to go back, is there?

According to [Omni Software Update Statistics][1] in April,
- 10.11: 64.4%
- 10.10: 22.1%
- 10.9: 6.6%
- 10.8 1.0%

10.9 should hopefully cover everybody.

**Comment by squiddle** [comment]
even though i am a 10.9 user i am ok with this, as i think the hassle really might not be worth it. in 10 days mac OS Sierra is going to be released which makes 10.9 the 4th oldest release available.

**Comment by vcunat** [comment]
Could that cause a problem on (some of) the Hydra slaves? In particular, now I glimpsed
```
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
```
in a [PyQT build](http://hydra.nixos.org/build/40195338).

**Comment by mjhoy** [comment]
I'm a 10.9 user on unstable (who plans on upgrading at some point), what can I do in the meantime? Also, would be nice to update this page: https://nixos.org/wiki/Nix_on_OS_X which is what I get when I google "nix darwin".

**Comment by vcunat** [comment]
Wiki PR: https://github.com/NixOS/nixos-org-configurations/pull/19.

**Comment by mjhoy** [comment]
Just leaving a note for any other 10.9 users. `LnL` on irc pointed me to a [tag](https://github.com/LnL7/nixpkgs/tree/darwin-10.9) for the last commit that supported 10.9, and you can do this:

```
NIX_PATH=nixpkgs=https://github.com/LnL7/nixpkgs/archive/darwin-10.9.tar.gz
```

**Comment by matthewbauer** [comment]
@copumpkin It may not always be obvious when macOS version are not supported. But when it is obvious, it may be a good idea to tag the previous commit as something like "last-macos-10.X" like in the previous comment.

**Comment by grahamc** [comment]
Closing, since the helpful note from September 17 will still be here, and we've clearly moved on :)
