### ISSUE TITLE
woodpecker-cli: fails to find certs

### ISSUE THREAD

**Issue by abeforgit** [NixOS/nixpkgs#184875]
### Describe the bug
Any attempt at using the woodpecker-cli, provided by the package in unstable with the same name, have resulted in an error about not finding the system CA certs.

### Steps To Reproduce
1. install `woodpecker-cli`
2. correctly configure env vars WOODPECKER_SERVER and WOODPECKER_TOKEN
3. attempt to use any of the commands (e.g. `woodpecker-cli info`)

### Expected behavior
The command works as intended

### Additional context

Exact error: 
```
8:54PM ??? github.com/woodpecker-ci/woodpecker/cli/common/zerologger.go:20 > LogLevel = trace
8:54PM ERR github.com/woodpecker-ci/woodpecker/cli/internal/util.go:40 > failed to find system CA certs: <nil>
```

I delved into the go file that spits out the error. It seems they are using the stdlib `crypto/x509` module. That module tries to find cert files in several locations, a classic cause of problems in nix. However, they also (claim to, and as far as I can understand the source, they do) respect the SSL_CERT_FILE and SSL_CERT_DIR env vars, which I've tried to set with `${pkgs.cacert.out}/etc/ss/certs/ca-bundle.crt`, but to no avail.

I originally tried this in the context of a devshell, then globally installed on my nixos system, both with identical results.

It's entirely possible this is a problem in upstream, but in that case surely no one has ever been able to use this package?

### Notify maintainers
@ambroisie 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.11 (Raccoon), 22.11.20220723.42ca9be`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(arne): `"home-manager-21.11"`
 - channels(root): `"nixos-21.11.335109.00acdb2aa81, home-manager-21.11"`
 - nixpkgs: `/nix/store/v30d42gs5j2x46486d3jrx23hr9qhdvh-source`
```

**Comment by ambroisie** [comment]
Unfortunately I have not had the chance to migrate my Drone installation to Woodpecker yet, so this error had slipped by me 🙃 (the `--help` didn't try to connect to the server).

Will takes a look when I can.

**Comment by winterqt** [comment]
> However, they also (claim to, and as far as I can understand the source, they do) respect the SSL_CERT_FILE and SSL_CERT_DIR env vars, which I've tried to set with `${pkgs.cacert.out}/etc/ss/certs/ca-bundle.crt`, but to no avail.

Was this (`ss` instead of `ssl`) a typo you made in writing this comment, or the actual testing? (Just making sure.)

**Comment by winterqt** [comment]
Also: NixOS sets up the locations for the certificate bundle [by default](https://github.com/NixOS/nixpkgs/blob/64b54e365330b281fbb89a7d480da5e843e68bf4/nixos/modules/security/ca.nix), so something weird is definitely going on here. ([These are the paths that Go looks in](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/crypto/x509/root_linux.go;drc=fd4b391849dcd3ac0e90d3a86b0ee7df00b9b269).) Can you strace it, to see if it's even trying to load the file?

**Comment by winterqt** [comment]
Oh, lmfao: https://github.com/woodpecker-ci/woodpecker/commit/1fb800329488de74c9db7cfc5dc43fb5a4efbad8

They were throwing an error no matter what, even if the process didn't error (that's why you see `nil` in the logs.)

You can apply that patch as a stopgap, to maintain compatibility with the server version (since I have no clue if the currently packaged server would be compatible with the newest CLI, we're a few months out of date). Alternatively, you can PR an upgrade for the entire Woodpecker suite.

**Comment by ambroisie** [comment]
Thank you @winterqt, I'm about to submit an MR to add the patch until the next release.

**Comment by abeforgit** [comment]
Thanks for the quick reactions!
Yeah just found out this morning that the errors are nonsense, my colleagues get them too
Will tryout the pr later today

(and yes `ss` was a typo only in the comment)

**Comment by winterqt** [comment]
Wait, here's something I didn't notice:

@abeforgit @ambroisie Are the commands actually *failing*, or is it just logging the error? From my understanding of the code, the function they're unconditionally calling to log the error doesn't exit after doing so.

**Comment by ambroisie** [comment]
@winterqt I have not run the command, but to me this is a warning on stderr.

**Comment by abeforgit** [comment]
No they are not failing (although I initially thought so), they're just printing the error but otherwise work fine
