### ISSUE TITLE
Packaging Request: marksman

### ISSUE THREAD

**Issue by cbebe** [NixOS/nixpkgs#184873]
**Project description**
Markdown LSP server providing completion, cross-references, diagnostics, and more. 

**Metadata**

* homepage URL: https://github.com/artempyanykh/marksman
* source URL: https://github.com/artempyanykh/marksman/commit/f9bc6139566418130f5f269b75f359cefc9a492d
* license: mit
* platforms: linux, darwin

**Comment by rski** [comment]
fwiw, I have this in my home-manager config:
```
    file."bin/marksman" = {
      source = builtins.fetchurl {
        url = "https://github.com/artempyanykh/marksman/releases/download/2022-06-23/marksman-linux";
        sha256 = "0c7zqhfbn6675f7rj11if306hg6qx97jcr6wlpmn553a8viqr6nm";
      };
      executable = true;
    };
```

**Comment by onny** [comment]
Tried to package the binary version but unfortunately it fails to run https://github.com/NixOS/nixpkgs/pull/185100
Feel free to use and update it :)
