### ISSUE TITLE
Does our texlive-new support htlatex?

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#18480]
And if it does, how can I use it? Has anyone use `htlatex` successfully and can provide a working example to me?

Cc: @vcunat

**Comment by vcunat** [comment]
Link to the executable isn't created, it seems. It's the same in 2015 and 2016 (staged now).

**Comment by vcunat** [comment]
@peti: after applying patch 20c6f5c56, I was able to
```
$ nix-build -E 'with import ./. {}; texlive.combine { inherit (texlive) scheme-basic tex4ht ec; }' -Q
$ ./result/bin/htlatex my-simple-file.tex
$ firefox my-simple-file.html
```

**Comment by peti** [comment]
I cannot apply that patch to either `master`  or `staging`. It appears to be based on other changes that haven't been pushed yet?

**Comment by peti** [comment]
Ah, now I got it. It's already in `staging`. That's why I couldn't apply it there. :-)

**Comment by vcunat** [comment]
It's applicable to master as well, and I expect it should work there with 2015 as well.

**Comment by peti** [comment]
You are right. The patch does apply to master and the resulting tex4ht tools work, too. Not sure why that didn't succeed when I tried it earlier. Anyway, thank you for the quick fix! Would you like to push the patch to master (and release-16.09?) or shall I?

**Comment by vcunat** [comment]
Tomorrow I expect to merge whole staging to master and cherry-pick all TeX-related changes to 16.09 (and some other bugfixes as well).

**Comment by vcunat** [comment]
BTW, the `tex4ht` executable was there even before the patch.
