### ISSUE TITLE
jabref: File open dialog results in crash due to missing GSettings schema path

### ISSUE THREAD

**Issue by fleimgruber** [NixOS/nixpkgs#184857]
### Describe the bug
File open dialog results in crash due to missing GSettings schema path. This seems similar to https://github.com/NixOS/nixpkgs/issues/184652.

### Steps To Reproduce
1. `jabref`
2. Click on "Open library" icon
3. `(java:55735): GLib-GIO-ERROR **: 19:28:22.222: No GSettings schemas are installed on the system`

### Expected behavior
File open dialog opens.

### Notify maintainers
@linsui @gebner 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.05 (Quokka), 22.05.2065.9370544d849`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(fps): `""`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by linsui** [comment]
I can't reproduce it on a clean NixOS VM.

**Comment by Artturin** [comment]
to reproduce these issues do `XDG_DATA_DIRS= *command*` to empty XDG_DATA_DIRS

**Comment by linsui** [comment]
Great! Now I can reproduce it with a VM.

**Comment by linsui** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/185019

**Comment by fleimgruber** [comment]
Thanks for the quick fix, https://github.com/NixOS/nixpkgs/pull/185019 works for me.

**Comment by fleimgruber** [comment]
Would be nice if this could be backported (let's try with issue label on the PR again after it is merged, if you would be so kind @linsui) to 22.05 as well.

**Comment by linsui** [comment]
I'll add the label. :ok_hand:

**Comment by fleimgruber** [comment]
I am not sure whether this label should only be applied after the PR is successfully merged, i.e. only then does the action trigger, but let's see about that assumption.

**Comment by linsui** [comment]
Unfornately there is confilctions so the auto backport failed.

**Comment by fleimgruber** [comment]
Yes, already saw it. Will open a manual backport PR.
