### ISSUE TITLE
Add Z3 dependency for Cryptol REPL users

### ISSUE THREAD

**Issue by aneeshusa** [NixOS/nixpkgs#18490]
## Issue description

[Cryptol](http://www.cryptol.net/) has a [dependency on Z3](http://www.cryptol.net/downloads.html), but its Nix derivation does not express this dependency.
I have worked around this locally with an override and `wrapProgram` (or alternatively `nix-env -iA z3` works), but I would like to upstream this change. It looks like `haskell-packages.nix` is auto-generated - what is the best way to add this dependency to `nixpkgs`?

cc @peti 

### Steps to reproduce

```console
$ nix-env -iA cryptol
$ cryptol
```

cryptol will exit with this error:
```
Errors encountered on startup; exiting:
    [error] z3 is required to run Cryptol, but was not found in the system path. See the Cryptol README for more on how to install z3.
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...): 17.03pre91001.f4c2339 (Gorilla)
* Nix version: (run `nix-env --version`): nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`): "17.03pre91001.f4c2339"

**Comment by peti** [comment]
My understanding is that cryptol supports a whole range of SMT solver via "SBV", i.e. one can also use Yices or CVC4 instead of Z3. Is that correct?

**Comment by aneeshusa** [comment]
@peti I'm not sure, I'm trying to learn Cryptol for the first time :)

Based on the codebase it looks like the REPL has a hard-coded dependency on Z3, but the rest of the library seems to have pluggable solvers via SBV.
See:
- https://github.com/GaloisInc/cryptol/blob/master/src/Cryptol/REPL/Monad.hs#L701
- https://github.com/GaloisInc/cryptol/blob/master/cryptol/Main.hs#L203

**Comment by peti** [comment]
Well, I am reluctant to make the package depend on Z3 because it's not a hard dependency that users absolutely have to have to use cryptol. IMHO, it's okay for people who want to use Z3 to just make it available in $PATH. Is that not sufficient?

**Comment by aneeshusa** [comment]
That's reasonable as well, just thought this might make it slightly-easier for first time users like myself. Happy to close this, thanks for listening.

Another thought (not sure if this is possible): can Haskell packages have separate outputs? If only the REPL binary depends on Z3 and we use `wrapProgram` on the bin output, will the lib output depend on Z3?

**Comment by peti** [comment]
> Another thought (not sure if this is possible): can Haskell packages have separate outputs? If only the REPL binary depends on Z3 and we use wrapProgram on the bin output, will the lib output depend on Z3?

Yes, that would be a good solution indeed. Users of the REPL would probably want Z3, but users of the library don't necessarily want it. I suppose it would also be okay to add Z3 to the package available as `pkgs.cryptol` but not to `pkgs.haskellPackages.cryptol`.

**Comment by aneeshusa** [comment]
Reopening with smaller scope.
