### ISSUE TITLE
smartd: notification scripts are broken

### ISSUE THREAD

**Issue by al3xtjames** [NixOS/nixpkgs#185095]
### Describe the bug

I noticed that `smartd` was failing to run warning scripts after enabling it. This appears to be caused by [configure.ac in smartmontools building these scripts with a hardcoded PATH](https://github.com/smartmontools/smartmontools/blob/34653e284d6c18a7cc214a35104902c09ea34364/smartmontools/configure.ac#L259-L265):
```bash
$ cat /nix/store/9z87pd6af28vs3q2bw3bmjvk128zfjzp-smartmontools-7.3/etc/smartd_warning.sh
...
# Set by config.status
export PATH="/usr/local/bin:/usr/bin:/bin"
```

### Steps To Reproduce
1. Enable `services.smartd` in configuration.nix:
```nix
{
  services.smartd = {
    enable = true;
    autodetect = true;
    defaults.autodetected = "-M test -a";
  };
}
```
2. Check status of smart with `systemctl smartd`:
```bash
$ systemctl status smartd
...
Aug 03 01:57:14 nix smartd[158753]: /nix/store/9z87pd6af28vs3q2bw3bmjvk128zfjzp-smartmontools-7.3/etc/smartd_warning.sh: line 125: sed: command not found
...
```

### Expected behavior
`smartd` successfully generated a notification.

### Additional context
I tried to fix this in https://github.com/NixOS/nixpkgs/pull/185094. configure.ac in smartmontools stops hardcoding PATH if you specify `--with-scriptpath=no`. This can be done when `enableMail` is false.

### Notify maintainers

@Frostman 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.58, NixOS, 22.11 (Raccoon), 22.11.20220731.5857574`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(alex): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
Maybe you need `notifications.*.enable`? I use this config an do get notifications (by email at least -- the machine is now headless so I don't know about the x11 notifications):

```
{ config, lib, pkgs, ... }:

{
  services = {
    smartd = {
      enable = true;
      autodetect = true; # monitor all devices found on startup
      # See smartd.conf(5) man page for details about these options:
      # "-a": enable all checks
      # "-o VALUE": enable/disable automatic offline testing on device (on/off)
      # "-s REGEXP": do a short test every day at 3am and a long test every
      #              sunday at 3am.
      defaults.autodetected = "-a -o on -s (S/../.././03|L/../../7/03)";
      notifications = {
        mail.enable = true;
        x11.enable = true;
        #test = true; # send notification on service startup, for test
      };
    };
  };
}
```

And I don't have "sed: command not found" in my system log.

**Comment by al3xtjames** [comment]
Do you have the `enableMail` set to true for [`pkgs.smartmontools`](https://github.com/NixOS/nixpkgs/blob/168d1c578909dc143ba52dbed661c36e76b12b36/pkgs/tools/system/smartmontools/default.nix#L5) (or `pkgs.zfs`, which also overrides it for `pkgs.smartmontools`)? `--with-scriptpath` is correctly specified in that case. Is `PATH` set in `smartd_warning.sh`? It should be located in `$NIX_STORE/$HASH-smartmontools-7.3/etc/smartd_warning.sh`.

**Comment by bjornfor** [comment]
> Do you have the `enableMail` set to true for [`pkgs.smartmontools`](https://github.com/NixOS/nixpkgs/blob/168d1c578909dc143ba52dbed661c36e76b12b36/pkgs/tools/system/smartmontools/default.nix#L5) (or `pkgs.zfs`, which also overrides it for `pkgs.smartmontools`)? `--with-scriptpath` is correctly specified in that case.

I don't have `enableMail` in my configuration.nix. (Unless it's being set indirectly via some other option.)

> Is `PATH` set in `smartd_warning.sh`? It should be located in `$NIX_STORE/$HASH-smartmontools-7.3/etc/smartd_warning.sh`.

```
$ grep PATH= $(nix-store -qR /run/current-system | grep smartmontools)/etc/smartd_warning.sh
export PATH="/usr/local/bin:/usr/bin:/bin"
```

I happen to have other smartmontools store paths on this machine (because it's a binary cache for my machines), with different PATH=:

```
$ grep PATH= $(find /nix/store/*smartmontools* -name smartd_warning.sh)
/nix/store/6jwgd6pffpyx60c3x8z2qwnxxs7zw5qr-smartmontools-7.2/etc/smartd_warning.sh:export PATH="/nix/store/z5md9v0hqnmjgfgli3all91rnbfw3886-inetutils-1.9.4/bin:/nix/store/zj226fb9pmvwxigsrlg6a9arjr63vakj-mailutils-3.12/bin"
/nix/store/9q7kjh24m1kfdbzxxzphdbiqsq1ym1gf-smartmontools-7.2/etc/smartd_warning.sh:export PATH="/usr/local/bin:/usr/bin:/bin"
/nix/store/hk6jq97njg4kwa6qk1albkc1dv1a5821-smartmontools-7.2/etc/smartd_warning.sh:export PATH="/usr/local/bin:/usr/bin:/bin"
/nix/store/q2287dh4dczz34wks7z5lv7kfdyvr31m-smartmontools-7.2/etc/smartd_warning.sh:export PATH="/nix/store/vgzqshafzxfynkc0y5gqw8vlj67kwpvy-inetutils-1.9.4/bin"
/nix/store/zvryxpd0avn6f0qw3brb0zcsg7l38xir-smartmontools-7.2/etc/smartd_warning.sh:export PATH="/nix/store/z5md9v0hqnmjgfgli3all91rnbfw3886-inetutils-1.9.4/bin"
```

**Comment by al3xtjames** [comment]
Unfortunately I'm still seeing this after a7855f2235a1876f97473a76151fec2afa02b287:

```
Aug 22 20:07:23 host smartd[3706906]: Executing test of /nix/store/nbyq9gzr2p7zdp6lw9ql1ra864imlfp6-telegram_notify.sh to <nomailer> ...
Aug 22 20:07:23 host smartd[3706906]: Test of /nix/store/nbyq9gzr2p7zdp6lw9ql1ra864imlfp6-telegram_notify.sh to <nomailer> produced unexpected output (118 bytes) to STDOUT/STDERR:
Aug 22 20:07:23 host smartd[3706906]: /nix/store/2iwn0lzf58n7aqhrrzgifmvq5pwjhrm7-smartmontools-7.3/etc/smartd_warning.sh: line 125: sed: command not found
Aug 22 20:07:23 host smartd[3706906]: Test of /nix/store/nbyq9gzr2p7zdp6lw9ql1ra864imlfp6-telegram_notify.sh to <nomailer>: failed (32-bit/8-bit exit status: 32512/127)
```

This is what my configuration.nix looks like (the environment variables are set by overriding `systemd.services.smartd.serviceConfig.EnvironmentFile`:

```nix
{ config, pkgs, ... }:

let
  telegramNotify = pkgs.writeScript "telegram_notify.sh" ''
    ${pkgs.curl}/bin/curl -G \
      --data-urlencode "parse_mode=Markdown" \
      --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" \
      --data-urlencode "text=$SMARTD_FULLMESSAGE" \
      "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" >&/dev/null
  '';
in {
  services.smartd = {
    enable = true;
    autodetect = true;
    notifications.wall.enable = false;
    defaults.autodetected = "-m <nomailer> -M exec ${telegramNotify} -M test -a";
  };
}
```

I have `enableMail` set to false. https://github.com/NixOS/nixpkgs/pull/186809 only fixes the script bin path if `enableMail` is true (as far as I can tell).

**Comment by hanleym** [comment]
Sorry @al3xtjames, I didn't see your comment on the original PR. #188044 should fix it for you.
