### ISSUE TITLE
mongodb-compass: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by rdk31** [NixOS/nixpkgs#185011]
### Describe the bug

Trying to run MongoDB Compass but it segfaults. I am running on unstable (1.32.5) but tried the 22.05 version as well (1.31.2). Also I'm running sway (could contribute I guess). It used to work a few flake updates ago.

### Steps To Reproduce
1. open terminal
2. run `mongodb-compass`

### Expected behavior

MongoDB Compass works.

### Additional context

The GUI pops up for a second and then it crashes.
Running: `ELECTRON_ENABLE_LOGGING=1 WAYLAND_DEBUG=1 ELECTRON_ENABLE_STACK_DUMPING=1 mongodb-compass`
```
[52820:0803/143515.511689:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[52786:0803/143515.792559:INFO:CONSOLE(13)] "(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.", source: electron/js2c/renderer_init.js (13)
[52786:0803/143515.843304:INFO:CONSOLE(82)] "SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.", source: internal/worker.js (82)
[52786:0803/143516.322842:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (33)
[52786:0803/143516.665676:INFO:CONSOLE(1)] "in app:launched", source: file:///nix/store/p490pv6dfkzkv4vmhj23zi33kb03yq7z-mongodb-compass-1.32.5/lib/mongodb-compass/resources/app.asar/build/index-43dd7041.ba28e7da093a7395389a.renderer.js (1)
Received signal 11 SEGV_MAPERR 000000000000
#0 0x55c6c1abccf9 (/nix/store/p490pv6dfkzkv4vmhj23zi33kb03yq7z-mongodb-compass-1.32.5/lib/mongodb-compass/MongoDB Compass+0x4703cf8)
  r8: 0000000000000000  r9: 0000000000000000 r10: 000000000000006a r11: 00007f55d6ca8750
 r12: 000027b452287f60 r13: 000027b4522fff30 r14: 000055c6c583e6a8 r15: 00007f55be451640
  di: 0000000000000000  si: 00007f55ae50ad74  bp: 0000000000000000  bx: 000027b4522664a0
  dx: 000027b4545a9520  ax: 0000000000000000  cx: 000000002b629bc0  sp: 00007f55be4515b8
  ip: 00007f55d6d73b38 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

### Notify maintainers

@bryanasdev000 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.58, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by bryanasdev000** [comment]
> ### Describe the bug
> Trying to run MongoDB Compass but it segfaults. I am running on unstable (1.32.5) but tried the 22.05 version as well (1.31.2). Also I'm running sway (could contribute I guess). It used to work a few flake updates ago.
> 
> ### Steps To Reproduce
> Steps to reproduce the behavior:
> 
> 1. open terminal
> 2. run `mongodb-compass`
> 
> ### Expected behavior
> MongoDB Compass works.
> 
> ### Additional context
> The GUI pops up for a second and then it crashes. Running: `ELECTRON_ENABLE_LOGGING=1 WAYLAND_DEBUG=1 ELECTRON_ENABLE_STACK_DUMPING=1 mongodb-compass`
> 
> ```
> [52820:0803/143515.511689:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
> [52786:0803/143515.792559:INFO:CONSOLE(13)] "(electron) The remote module is deprecated. Use https://github.com/electron/remote instead.", source: electron/js2c/renderer_init.js (13)
> [52786:0803/143515.843304:INFO:CONSOLE(82)] "SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.", source: internal/worker.js (82)
> [52786:0803/143516.322842:INFO:CONSOLE(33)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (33)
> [52786:0803/143516.665676:INFO:CONSOLE(1)] "in app:launched", source: file:///nix/store/p490pv6dfkzkv4vmhj23zi33kb03yq7z-mongodb-compass-1.32.5/lib/mongodb-compass/resources/app.asar/build/index-43dd7041.ba28e7da093a7395389a.renderer.js (1)
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x55c6c1abccf9 (/nix/store/p490pv6dfkzkv4vmhj23zi33kb03yq7z-mongodb-compass-1.32.5/lib/mongodb-compass/MongoDB Compass+0x4703cf8)
>   r8: 0000000000000000  r9: 0000000000000000 r10: 000000000000006a r11: 00007f55d6ca8750
>  r12: 000027b452287f60 r13: 000027b4522fff30 r14: 000055c6c583e6a8 r15: 00007f55be451640
>   di: 0000000000000000  si: 00007f55ae50ad74  bp: 0000000000000000  bx: 000027b4522664a0
>   dx: 000027b4545a9520  ax: 0000000000000000  cx: 000000002b629bc0  sp: 00007f55be4515b8
>   ip: 00007f55d6d73b38 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> ```
> 
> ### Notify maintainers
> @bryanasdev000
> 
> ### Metadata
> * system: `"x86_64-linux"`
> * host os: `Linux 5.15.58, NixOS, 22.11 (Raccoon)`
> * multi-user?: `yes`
> * sandbox: `yes`
> * version: `nix-env (Nix) 2.10.3`
> * nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

Can you try with Xorg to validate if is a issue related to Wayland?

**Comment by rdk31** [comment]
Running: `env -u WAYLAND_DISPLAY mongodb-compass` works. I really don't know why I didn't try it before.

**Comment by bryanasdev000** [comment]
> Running: `env -u WAYLAND_DISPLAY mongodb-compass` works. I really don't know why I didn't try it before.

Nice!

I am closing the issue, feel free to reopen if any issue arise.

**Comment by rdk31** [comment]
After running it once with xorg it works now on wayland (I tried cleaning .config before and it didn't change anything). I also had issues with gnome-keyring and I finally got it to work so I'm really not so sure if it's actually related to xorg/wayland. Anyway, it works now and I'm just making this comment for anyone who stumbles upon this issue. Thanks for help and please close the issue.
