### ISSUE TITLE
python3.10-nbclassic-0.4.3: npm unavailable

### ISSUE THREAD

**Issue by collinarnett** [NixOS/nixpkgs#185028]
### Steps To Reproduce
[1. build ](https://hydra.nixos.org/build/184847936#tabs-summary)

### Build log
https://hydra.nixos.org/build/184847936/nixlog/1

### Additional context
This is a dependency of jupyterlab which prevents me from using the latest jupyterlab in jupyterWith

I think this just needs `node` added somewhere but I'm not experienced enough with nixpkgs to inject it in the correct place.

### Notify maintainers
@elohmeier 

### Metadata
https://hydra.nixos.org/build/184847936#tabs-details

**Comment by zseri** [comment]
Note: I tried to fix this using
```nix
     pythonPackageExtensions =
       prev.pythonPackageExtensions
       ++ [
         (pfinal: pprev: {
           nbclassic = pprev.nbclassic.overridePythonAttrs (old: {
             # see also https://github.com/NixOS/nixpkgs/issues/185028
             buildInputs =
               (
                 if old ? buildInputs
                 then old.buildInputs
                 else []
               )
               ++ [final.nodejs];
           });
         })
       ];
```
but it didn't work... idk why.
