### ISSUE TITLE
dwdiff

### ISSUE THREAD

**Issue by unhammer** [NixOS/nixpkgs#185013]
**Project description**
dwdiff word-level diff, it is different from wdiff in that it allows the user to specify what should be considered whitespace, and in that it takes an optional list of characters that should be considered delimiters. Also supports color.

**Metadata**

* homepage URL: https://os.ghalkes.nl/dwdiff.html
* source URL: https://os.ghalkes.nl/dist/dwdiff-2.1.4.tar.bz2
* license: GPL3
* platforms: unix, linux, darwin

**Comment by onny** [comment]
Added a PR, feel free to test it :)
