### ISSUE TITLE
superTux error while loading shared libraries: libSM.so.6

### ISSUE THREAD

**Issue by vpfeiffer** [NixOS/nixpkgs#185076]
### Describe the bug
Unable to run superTux on NixOS. A shared object file appears to be missing.

### Steps To Reproduce
1. `nix shell nixpkgs#superTux`
2. `supertux2`
    Output: `supertux2: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory`

### Expected behavior
The superTux game is expected to launch and be playable.

### Screenshots
N/A

### Notify maintainers
@pSub 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.95, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11, nixos-unstable"`
 - channels(violetp): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by McSinyx** [comment]
The library (among other X ones) are not declared, my guess would be they used to be propagated from one of the build inputs but not anymore.  The fix would be to include these libraries conditionally on X.  I suggest you try to do it yourself, but if you don't feel like it I'll take a look at the weekend.  We'll need someone to test on Wayland too.

**Comment by astrobeastie** [comment]
I can confirm the same error also occurs on wayland (running river)
