### ISSUE TITLE
What does `hiPrioSet` for `python27Packages` do?

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#18512]
The only usage of `hiPrioSet` in the entire nixpkgs history is this which was added by @domenkozar in 2014:

```
10130   python27Packages = lib.hiPrioSet (recurseIntoAttrs (callPackage ./python-packages.nix {
10131     python = python27;
10132     self = python27Packages;
10133   }));
````

````
commit eac9fe354c06ee7306935225e4db145edaa9c7da
Author: Domen Kožar <domen@dev.si>
Date:   Thu May 22 08:58:49 2014 +0200

    python27Packages is now a hiPrioSet to avoid other python versions interfering
````

I wonder what it achieves, given that the derivation names are versioned like `python2.7-setuptools-26.1.1`, so they won't conflict with `nix-env -i` anyway.

What it does does do though is to cause the `meta.priority` that is set for `setuptools` to be ignored:
````
$ nix-instantiate --eval -A python2Packages.setuptools.meta.priority
"-10"                                                                                   

$ nix-instantiate --eval -A python3Packages.setuptools.meta.priority
10
````

Is there any use for `hiPrioSet`? Should it be removed to remove the `setuptools` inconsistency? (It does affect some hashes, as `buildEnv` uses `meta.priority`.)

**Comment by domenkozar** [comment]
Some packages used to remove `namePrefix`

**Comment by dezgeg** [comment]
Ah, indeed some still do. So keeping that for now then.
