### ISSUE TITLE
Document branches and tags

### ISSUE THREAD

**Issue by yuuyins** [NixOS/nixpkgs#185168]
## Description
Document branches and tags, their objective, differences, usage (users, development), etc.

> [...] in the maintainer section of the contributor guidelines [...]
> [...] GitHub issue or something like that from last year or so where you roughly outlined the process [...]
> ---[fricklerhandwerk](https://discourse.nixos.org/u/fricklerhandwerk), https://discourse.nixos.org/t/pinning-nixpkgs-in-documentation-examples/20749/10

## More information
- https://discourse.nixos.org/t/pinning-nixpkgs-in-documentation-examples/20749/8
- https://nixos.org/manual/nixpkgs/unstable/#submitting-changes-commit-policy
- https://nixos.wiki/wiki/Nix_channels
- https://nix.dev/reference/pinning-nixpkgs

**Comment by olafklingt** [comment]
> More information

https://nix.dev/reference/pinning-nixpkgs

**Comment by samueldr** [comment]
I believe this is now solved with all the details added in [`CONTRIBUTING.md`](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#flow-of-merged-pull-requests).

If it isn't, feel free to re-open with details about what can be done to solve this issue. I don't see any clear actionable goals here.
