### ISSUE TITLE
How to have systemd unit files disabled at boot?

### ISSUE THREAD

**Issue by jokogr** [NixOS/nixpkgs#18517]
Hello,

I would like to have systemd unit files available on my system, yet not enabled. Currently, setting `enable = false;` on a unit file makes it a symlink to /dev/null.

Although this is conventional for unit files such as `serial-getty@ttyS0` (mentioned in the manual), I would like to have unit files ready to start on my machine if I request so. E.g., I would like to start the syncthing service manually or I am on a network where a specific network mount described using a systemd mount unit is possible. Is there any way to accomplish that already?

**Comment by bjornfor** [comment]
If it's a service you're defining yourself in your configuration.nix, setting "wantedBy = [ ]" for the service should do it. If it's a Nixos service you might have to mkForce that value. (Assuming that no other service pull in your service.)

**Comment by jokogr** [comment]
Many thanks, @bjornfor! Both of the solutions you mentioned are working flawlessly.
