### ISSUE TITLE
Jameica crashes when trying to print / render a page

### ISSUE THREAD

**Issue by derjohn** [NixOS/nixpkgs#185140]
### Describe the bug
I use Jameica with the Hibiscus homebanking plugin. When I try to print/render a printable page, jameica crashes with

[Thu Aug 04 16:04:45 CEST 2022][INFO][main][de.willuhn.jameica.hbci.io.VelocityExporter.getIOFormats]   found template: /home/aj/projekte/linuxconfigs/shared/.jameica/plugins/hibiscus/lib/velocity/de.willuhn.jameica.hbci.rmi.Umsatz.html.vm

(Jameica 2.10.2:471465): GLib-GIO-ERROR **: 16:04:58.211: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)

### Steps To Reproduce
1. Start jameica with installed hibiscus plugin
2. Go to e.g. Menuitem Umsaetze , click export

### Expected behavior
It shows a rendered page

### Additional context
Workaround: 
export GSETTINGS_SCHEMA_DIR=/nix/store/34gizkg2d1p27ym1rfcihxncpdi5vham-gtk+3-3.24.34/share/gsettings-schemas/gtk+3-3.24.34/glib-2.0/schemas

### Notify maintainers
@flokli 
@r3dl3g 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.13, NixOS, 22.05 (Quokka), 22.05.2019.d9536b9b1e3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(aj): `"nixos-unstable"`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
Java 15

Hint: "I would guess it needs to use wrapGAppsHook as nativeBuildInputs but I have no idea how/where to add that." ( Taken from https://bytemeta.vip/repo/NixOS/nixpkgs/issues/181500 )

**Comment by Shawn8901** [comment]
Could you check if it's fixed by #183969 ?

**Comment by derjohn** [comment]
> Could you check if it's fixed by #183969 ?

Yup, I checked with jameica in nixos unstable and I am able to print without workaround. Thx.

#closing
