### ISSUE TITLE
obs-glcapture not multiarch

### ISSUE THREAD

**Issue by ashkitten** [NixOS/nixpkgs#185274]
i may try and fix this in the future but obs-glcapture should build 32-bit versions as well on x86_64

cc @AtilaSaraiva

**Comment by YellowOnion** [comment]
I had a solution to this, but I didn't like it. The problem is, unlike other OS's we don't have a lib32 directory, so we have to rename the files or something to get it to work correctly.

**Comment by fpletz** [comment]
We don't have obs-glcapture packaged. obs-vkcapture was done in #188699.

**Comment by ashkitten** [comment]
obs-glcapture is part of the same build. is that working multiarch as well?

**Comment by fpletz** [comment]
Ah, I see. Not entirely sure what you mean by multiarch and why this would be needed but `pkgsi686Linux.obs-studio-plugins.obs-vkcapture` builds.
