### ISSUE TITLE
services.xserver.resolutions does not apply in qemu VMs

### ISSUE THREAD

**Issue by sheenobu** [NixOS/nixpkgs#18523]
## Issue description

I've got a test setup that runs:

```
nix-build -I nixpkgs=~/nixpkgs -I nixos-config=./test/test-config.nix '<nixpkgs/nixos>' -A vm
./result/bin/run-machine-test-vm
```

The test-config.nix sets the option `services.xserver.resolutions` to a supported resolution but the generated X config does not contain the resolution. The `services.xserver.virtualScreen` _does_ add things to the X config, but does not change anything.

I can switch to my requested resolution in the virtual machine via xrandr, so I don't think it's a resolution support issue.
### Steps to reproduce

basic.nix:

```
{ config, pkgs, lib, ... }:
{

  services.xserver.enable = true;
  services.xserver.windowManager.i3.enable = true;
  services.xserver.windowManager.default = "i3";
  services.xserver.displayManager.slim.enable = true;
  services.xserver.displayManager.auto.enable = true;
  services.xserver.displayManager.auto.user = "root";
  services.xserver.resolutions = { x = 1680; y = 1050; };
  services.xserver.virtualScreen = { x = 1680; y = 1050; };

  virtualisation.memorySize = 1024;
  virtualisation.qemu.options = [ "-full-screen -sdl" ];

  networking.hostName = "basic-test";

  system.stateVersion = "16.03";
}
```

Commands: 

```
  $ nix-build -I nixpkgs=path-to-nixpkgs \
                   -I nixos-config=./basic.nix \
                    '<nixpkgs/nixos>' -A vm
  $ ./result/bin/run-basic-test-vm
```

Result is an X11 setup with 1024x768 as the resolution, instead of what has been set in `services.xserver.resolutions`.
## Technical details
- Host System: 16.03.1287.6ac7ffd 
- Host Nix version: nix-env (Nix) 1.11.2
- Host Nixpkgs version: 16.03.1287.6ac7ffd

Tested nixpkgs=... for:
- no nixpkgs, using 16.03.1287.6ac7ffd directly.
- release-16.03 revision a8e0739 (16.03pre-git).
- release-16.09 revision dccf8c5 (16.09pre-git).

**Comment by domenkozar** [comment]
Can you also print the output of `xrandr` on the guest? Maybe it can not use the resolution you specified.

**Comment by sheenobu** [comment]
@domenkozar: "I can switch to my requested resolution in the virtual machine via xrandr, so I don't think it's a resolution support issue."

That said (switched to openbox since i3 in i3 was causing keybinding conflicts):
![2016-09-12-091922_1678x1022_scrot](https://cloud.githubusercontent.com/assets/1443459/18437256/0ed403bc-78ca-11e6-955a-4a26d9e6e3df.png)

**Comment by ThibautMarty** [comment]
For posterity:

`resolutions` is overrided at [nixos/modules/virtualisation/qemu-vm.nix line 512](https://github.com/NixOS/nixpkgs/blob/b6a746daa1677f3a56a72cea8bc97a9618a667bd/nixos/modules/virtualisation/qemu-vm.nix#L512).
`mkVMOverride` is `mkOverride 10`, so you can force the value you want with something like:
`services.xserver.resolutions = lib.mkOverride 9 { x = 1680; y = 1050; };`

This old issue can be closed.

**Comment by rnhmjoj** [comment]
As reported by @ThibautMarty , `lib.mkOverride` is needed to change the resolution.
