### ISSUE TITLE
Can't run "solaar" after some recent changes

### ISSUE THREAD

**Issue by SebTM** [NixOS/nixpkgs#185291]
### Describe the bug
If I try to run Solaar via Rofi nothing happens, when trying it via terminal the following error occurred:
> Solaar: missing required system package gir1.2-gtk-3.0

If I open a nix-shell with `nix-shell -p solaar` and run solaar it opens and works without issues.

### Steps To Reproduce
Relevant configuration:
```
hardware.logitech.wireless = {
  enable = true;
  enableGraphical = true;
};
```

1. Rebuild system from unstable
2. Try to run solaar

### Expected behavior
Solaar GUI main windows opens

### Additional context
I've tried to find out more and was directed from @SuperSandro2000 that it could be related to missing `gtk3-x11` but regardless where I added it it didn't solve the issue.

### Notify maintainers
@spinus @ysndr @oxalica

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.15, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(sebtm): `""`
 - channels(root): `""`
 - nixpkgs: `/run/nixpkgs`
```

nixos-unstable -> 168d1c578909dc143ba52dbed661c36e76b12b36

**Comment by SuperSandro2000** [comment]
see #185310

**Comment by SebTM** [comment]
Thanks 👍🏻 :)
