### ISSUE TITLE
Kernel warning about zswap during boot after 16.03 → 16.09

### ISSUE THREAD

**Issue by rycee** [NixOS/nixpkgs#18533]
## Issue description

Switched from 16.03 to 16.09 and started seeing warnings about zswap early in the boot process. From the journal:
```
Sep 12 08:18:22 beta kernel: zswap: default zpool zbud not available
Sep 12 08:18:22 beta kernel: zswap: pool creation failed
```
Doesn't seem to cause any harm but it doesn't look very nice to start your computer and immediately get a kernel warning :-)

If this is expected with the switch from 16.03 to 16.09 then perhaps a mention in the release notes with instructions how to remove the warning?

### Steps to reproduce

I think using a typical 16.03 configuration.nix to boot 16.09 would cause this. I've only checked one computer.

## Technical details

* System: 16.09beta172.e3bdf6b (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09beta172.e3bdf6b

**Comment by NeQuissimus** [comment]
I have the same thing at work, I have not yet dug into this.

When I have a few minutes, I am going to try adding the modules mentioned here:
http://techpatterns.com/forums/about2444.html

Not quite sure where to put them yet, but I suspect `boot.initrd.kernelModules`

**Comment by NeQuissimus** [comment]
So, I am not sure where I need to add the `zbud` module. Whatever I do, the error persists.
However, if you change from `zbud` to `zsmalloc`, the error goes away.

```
boot.kernelParams = [ "zswap.zpool=zsmalloc" ];
```

From what I can tell, `zbud` is preferred over `zsmalloc`, so it may be worth the effort to make this work. I am not much of a kernel guy, so not quite sure where to start :)

**Comment by NeQuissimus** [comment]
What I can gather from `dmesg` is that zbud is loaded if I put it into `boot.initrd.kernelModules` or `boot.initrd.availableKernelModules` but too late.

```
[    0.590548] zswap: compressor lz4 not available, using default lzo
[    0.590715] zswap: default zpool zbud not available
[    0.590737] zswap: pool creation failed
...
[    1.288679] stage-1-init: loading module zbud...
[    1.290140] zbud: loaded
[    1.291221] stage-1-init: loading module lz4...
[    1.294255] stage-1-init: loading module lz4_compress...
```

I have no idea how to have it load even earlier than stage 1.

**Comment by NeQuissimus** [comment]
I wonder if @edolstra or @abbradar have any ideas about this.

**Comment by abbradar** [comment]
ZSWAP needs to be compiled into the kernel -- it's not a module. So, to fix this error, we need to compile `zbud` into kernel too, and maybe make `zsmalloc` a module to save some space.

**Comment by NeQuissimus** [comment]
We should also port the change onto 16.09.

**Comment by rycee** [comment]
Many thanks @NeQuissimus for taking the time to look into this!

**Comment by abbradar** [comment]
Backported to release as https://github.com/NixOS/nixpkgs/commit/d24dc8c1d21f600feff27df8d8596a9ca8d10f52. Indeed, many thanks for the investigation!
