### ISSUE TITLE
neovim plugin infrastructure

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#185397]
## Issue description

As reported in https://github.com/NixOS/nixpkgs/pull/178180#issuecomment-1197726116, buildNeovimPluginFrom2Nix (currently) ignores the "src" which is confusing.
https://github.com/NixOS/nixpkgs/blob/551e65e946d7261f956175845a739072dd2ac6e0/pkgs/applications/editors/vim/plugins/generated.nix#L3156

Solutions:
1. either dont write src so it's clear we are using the version from the lua package
2. we use the "src" version but it means we need

This is sthg I am invested in so I've assigned it to myself.

**Comment by miuirussia** [comment]
How to build custom plugin with lua, which not included in nixpkgs?

**Comment by teto** [comment]
@miuirussia your question is a bit orthogonal, maybe ask on the discourse instead. You may find info here https://github.com/NixOS/nixpkgs/pull/126633

**Comment by teto** [comment]
a few plugins to add to lua
- https://github.com/hrsh7th/nvim-cmp/pull/1051
- https://github.com/rktjmp/lush.nvim/pull/58

**Comment by teto** [comment]
the process should be clearer now that staging was merged.
