### ISSUE TITLE
Gimp needs a more recent cairo or green fringe will appear on text 

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#185385]
### Describe the bug

When adding a text in Gimp, a green border is visible:

![image](https://user-images.githubusercontent.com/2164118/183240016-c531d542-c119-46f1-937c-ddc1830c89d7.png)

However, I would expect something like that:

![image](https://user-images.githubusercontent.com/2164118/183240026-63fb4425-bdff-492c-aff3-605c8eedb9a1.png)

After [some investigations](https://gitlab.gnome.org/GNOME/gimp/-/issues/8455), a [fix has been applied upstream](https://gitlab.gnome.org/GNOME/gimp/-/issues/6210) on both Gimp (need 3.10.30) and [Cairo](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/114) (need 1.18 apparently). However, in NixOs Cairo 1.16 is used instead, so I guess it is necessary to upgrade cairo.

### Steps To Reproduce
1. Add some text on gimp, say white text on black background

### Expected behavior

I expect 

### Notify maintainers

Cairo does not have maintainers so I'm pinging random people that contributed:

@jtojnar @vcunat @jiegec @alyssais @EggBaconAndSpam @dtzWill @trofi @samuelgrf 

### Metadata

Running NixOs 1ffba9f2f68 with KDE Plasma.

**Comment by trofi** [comment]
Looking at https://repology.org/project/cairo/versions no distributions ship 1.18 yet. I wonder why. Is it an API-breaking release?

**Comment by trofi** [comment]
Proposed cairo one-liner backport as https://github.com/NixOS/nixpkgs/pull/185394

**Comment by jtojnar** [comment]
The 1.18 branch [does not have a stable release](https://gitlab.freedesktop.org/cairo/cairo/-/tags) yet. We could switch to development snapshots (1.17.x) if there are more concerns. But cherry-picks will probably be enough for now.

**Comment by tobiasBora** [comment]
The above PR solved the issue, thanks a lot!

**Comment by tobiasBora** [comment]
Actually I'll maybe let it open until it's merged to unstable (for now it's in stagging) and backported.

**Comment by vcunat** [comment]
GitHub should auto-close once the fixing commit reaches master branch.  Though I'm not sure if that wasn't broken by closing and reopening.

**Comment by vcunat** [comment]
It's reached all channels.
