### ISSUE TITLE
libspatialite: builds fine on darwin, but platform is disabled

### ISSUE THREAD

**Issue by ElessarWebb** [NixOS/nixpkgs#18537]
## Issue description

The package libspatialite has `meta.platforms = linux` but is documented to work fine on darwin.
The current derivation indeed does not build, but only because libiconv is missing from buildInputs.

### Steps to reproduce

Add libiconv as a buildInput to `nixpkgs/pkgs/development/libraries/libspatialite/default.nix` and  add `platforms.darwin` to `meta.platforms` and build on darwin. It succeeds!

## Technical details

* Nixpkgs version: 16.09

**Comment by adnelson** [comment]
You could make a pull request where you change `meta.platforms` to `unix`

**Comment by vcunat** [comment]
Merged.
