### ISSUE TITLE
calibre segfault on start on master

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#18535]
## Issue description

Calibre segfault when starting. The same is true with the calibre-debug -g command.
calibre-debug --test-build show 2 failures and 5 errors

Calibre installed from git 

```
calibre --version  = calibre 2.66
```
### Steps to reproduce

run the `calibre` command
## Technical details

```
❯calibre-debug -g                                                                                                                      ~/.config
calibre 2.66  embedded-python: False is64bit: True
Linux-4.7.2-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '4.7.2', '#1-NixOS SMP Sat Aug 20 16:11:18 UTC 2016')
Python 2.7.12
Linux: ('', '', '')
[1]    25944 segmentation fault  calibre-debug -g                                                              
```

calibre-debug --test-build: [log](https://gist.github.com/nico202/8426ceabcf78d16d06ae0c509c01be9f)
- System: 16.09pre90254.6b20d5b (Flounder)
- Nix version: nix-env (Nix) 1.11.3
- Nixpkgs version: "16.09pre90254.6b20d5b"

edit: moved log to gist

**Comment by nico202** [comment]
@viric @domenkozar @pSub @AndersonTorres

**Comment by rasendubi** [comment]
Works fine for me on latest master (6a9fb8b9e0ab806ae83a19a001f742f78087dd5d):
```
rasen@Larry ~/nixpkgs> ./result/bin/calibre-debug -g
calibre 2.66  embedded-python: False is64bit: True
Linux-4.4.18-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '4.4.18', '#1-NixOS SMP Tue Aug 16 07:31:54 UTC 2016')
Python 2.7.12
Linux: ('', '', '')
devicePixelRatio: 1.0
logicalDpi: 96.0756501182 x 96.0504201681
physicalDpi: 106.387434555 x 106.822429907
Starting up...
Failed to create system tray icon, your desktop environment probably does not support the StatusNotifier spec
Started up in 1.63 seconds with 96 books
```

**Comment by nico202** [comment]
The package is not pure?. Using nix-shell (with only calibre as a dependency)

    nix-shell --run calibre
sefault. But the following does work

    nix-shell --pure --run calibre

Hope this helps

**Comment by teh** [comment]
@nico202 Is calibre a GUI program? Maybe it needs the `DISPLAY` environment var, or some other thing like `DBUS_SESSION_BUS_ADDRESS`?

**Comment by nico202** [comment]
@teh yes, it's a GUI program.
Adding the current `DBUS_SESSION_BUS_ADDRESS` and the current `DISPLAY` values to `shell.nix` (with the `export` under `shellHook`) does not change the things: the `pure` command works, the unpure segfaults.

At the same time, unsetting `DBUS...` before calling calibre leads to a segfault. Unsetting DISPLAY prevents it from starting because `QXcbConnection: Could not connect to display`.

I'm trying `printenv` to see what changes

**Comment by nico202** [comment]
Ok, the one that causes the segfault is `NIX_PROFILES`. Running calibre with:
`NIX_PROFILES= calibre` works.
The same is true if I remove from those my `.nix-profile` folder (`~/.nix-profile`)

If anybody knows how to further investigate this, please let me know

**Comment by vcunat** [comment]
I expect it's an instance of https://github.com/NixOS/nixpkgs/issues/17448#issuecomment-246197556.

**Comment by nico202** [comment]
@vcunat Hi, is there a way to test your hypotesis? like uninstalling some Qt5 app

**Comment by vcunat** [comment]
Yes, I think so. I worked around my problems by getting rid of incompatible `~/.nix-profile/lib/libQt5*` versions. (It may apply to `/run/current-system/sw/lib/libQt5*` as well, as I had none.)

**Comment by nico202** [comment]
Closing since right now calibre is working, but don't know if it has been solved or not
