### ISSUE TITLE
Debug symbols not available despite following manual

### ISSUE THREAD

**Issue by stapelberg** [NixOS/nixpkgs#18538]
## Issue description

I read https://nixos.org/nixos/manual/options.html#opt-environment.enableDebugInfo and added this to my /etc/nixos/configuration.nix and rebuilt my system, which took way over 6 hours:

```
  environment.enableDebugInfo = true;

  nixpkgs.config.packageOverrides = pkgs: {
    libffi = pkgs.stdenv.lib.overrideDerivation pkgs.libffi (attrs: {
      outputs = attrs.outputs or ["out"] ++ ["debug"];
      buildInputs = attrs.buildInputs ++ [<nixpkgs/pkgs/build-support/setup-hooks/separate-debug-info.sh>];
    });
  };
```

…only to discover that there’s still no debug symbols for libffi:

```
(gdb) info sharedlibrary 
From                To                  Syms Read   Shared Object Library
[…]
0x00007ffff4a95b00  0x00007ffff4a9a3bc  Yes (*)     /nix/store/m49w1acl7z0pbcgqcg57xr0iz6dnbp3y-libffi-3.2.1/lib/../lib64/libffi.so.6
(*): Shared library is missing debugging information.
[…]
```

What did I do wrong here?
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  16.09.git.e446b9f (Flounder)
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.3
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  16.09pre90254.6b20d5b

**Comment by rasendubi** [comment]
I believe this is the same issue as https://github.com/NixOS/nixpkgs/issues/18530 -- libffi does not build debug symbols even though `environment.enableDebugInfo` is `true`.

The other part of the expression is responsible for separating debug info, but it does nothing if debug info is not built in the first place.

**Comment by vcunat** [comment]
The canonical way to enable the symbols in a package is to set `separateDebugInfo = true;` (instead of changing `outputs` and `buildInputs`). Still, I believe your changes had (almost) the same effect.

> What did I do wrong here?

Do you have `libffi` in `systemPackages`?

**Comment by vcunat** [comment]
I forgot the "canonical way" doesn't work with overrides yet: https://github.com/NixOS/nixpkgs/issues/10721

**Comment by rasendubi** [comment]
#10721 is resolved now. @stapelberg, could you try `overrideAttrs` with `separateDebugInfo = true`?

**Comment by stapelberg** [comment]
Will try this weekend, thanks.

**Comment by stapelberg** [comment]
I added this to my `/etc/nixos/configuration.nix`:
```
  nixpkgs.config.packageOverrides = pkgs: {
    libffi = pkgs.stdenv.lib.overrideDerivation pkgs.libffi (attrs: {
      outputs = attrs.outputs or ["out"] ++ ["debug"];
      buildInputs = attrs.buildInputs ++ [<nixpkgs/pkgs/build-support/setup-hooks/separate-debug-info.sh>];
    });
  };
```

…and ran `nixos-rebuild switch`. After >2 days of compiling, this does not seem to have worked at all:

```
$ gdb /nix/store/a52xqnhkcvi9igda9d8z1fzk44c5kbcs-network-manager-1.4.2/bin/NetworkManager
Reading symbols from /nix/store/a52xqnhkcvi9igda9d8z1fzk44c5kbcs-network-manager-1.4.2/bin/NetworkManager...(no debugging symbols found)...done.
gdb $ b main
Breakpoint 1 at 0x4360a0
gdb $ r
Starting program: /nix/store/a52xqnhkcvi9igda9d8z1fzk44c5kbcs-network-manager-1.4.2/bin/NetworkManager 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/hwbvmr4imiyi5ziq6v2snynr7zf022b5-glibc-2.24/lib/libthread_db.so.1".

Breakpoint 1, 0x00000000004360a0 in main ()
gdb $ info sharedlibrary 
From                To                  Syms Read   Shared Object Library
[…]
0x00007ffff43b5b00  0x00007ffff43ba3bc  Yes (*)     /nix/store/j6x44pvr10m7pyln1zl4qs9kasxfh8y1-libffi-3.2.1/lib/../lib64/libffi.so.6
[…]
(*): Shared library is missing debugging information.
```

The feedback cycle is infuriatingly long. Before running any further tests, can someone please explain to me how I can get just NetworkManager’s transitive closure compiled with debug symbols, not the whole world?

**Comment by rasendubi** [comment]
Sorry, I've meant trying method described in #10721 with using `.overrideAttrs` instead of `overrideDerivation`.

The docs for `debug-info` module has been updated: https://github.com/aneeshusa/nixpkgs/blob/master/nixos/modules/config/debug-info.nix#L12-L29

Try this on master:
```nix
let # fix syntax highlight
  nixpkgs.config.packageOverrides = pkgs: {
    libffi = pkgs.libffi.overrideAttrs (attrs: {
      separateDebugInfo = true;
    });
  };
```

**Comment by rasendubi** [comment]
If you want to patch `libffi` for `NetworkManager` only, you should create your own `pkgs` version with patched `libffi`, then use `networkmanager` from it. Something like that:
```nix
let # fix syntax highlight
  nixpkgs.config.packageOverrides = pkgs: {
    networkmanager =
        let
          pkgs-for-networkmanager = pkgs.overridePackages (oldPkgs: {
            libffi = oldPkgs.libffi.overrideAttrs (attrs: {
              separateDebugInfo = true;
            });
          });
        in pkgs-for-networkmanager.networkmanager;
  };
```

**Comment by Profpatsch** [comment]
Closing, since @stapelberg afaik doesn’t use NixOS at the moment.
