### ISSUE TITLE
Support user-defined cgroups in NixOS

### ISSUE THREAD

**Issue by PkmX** [NixOS/nixpkgs#1854]
Ideally we should be able to declare cgroups in Nix (in a way similar to `cgconfig.conf (5)`) and probably reuse`cgconfigparser` to setup the cgroup filesystem, and also support the `cgrulesengd` daemon which distributes processes to cgroups automatically.

This should be an easy task and has some fairly useful use cases, such as being to able to limit affinity/memory usage per user (as opposed `ulimit` which is per process).

**Comment by eborden** [comment]
Is there a status on this ticket?

**Comment by Profpatsch** [comment]
(triage) Given the inactivity and that it was already bumped, can we close? @shlevy

**Comment by shlevy** [comment]
What was already bumped? Also FWIW I've never tried using cgroups, I'd ask @PkmX if this is closable.

**Comment by Profpatsch** [comment]
@shlevy The commit above me asked about the status in late 2015, but no reaction.
