### ISSUE TITLE
Nixpkgs channel names no longer contain git commit hash

### ISSUE THREAD

**Issue by adnelson** [NixOS/nixpkgs#18544]
## Issue description

I have a local git clone of the `nixpkgs` on my machine. I find it very useful to duplicate a channel snapshot (e.g. of the `nixpkgs-unstable` or `nixos` channels) in my local clone, so that I can get access to prebuilt binaries from the nix cache while still having the ability to hack on the expressions if need be.

This used to be very easy to do: I could look at the store path of my nixpkgs channel to see what commit corresponded to my current channel:

```
$ readlink -f ~/.nix-defexpr/channels/nixpkgs
/nix/store/41fgyj42s0d6yvv82jirqn9l6x7mip8y-nixos-16.03.887.009fa8e
```

(The commit hash was the last 7 characters, in this case `009fa8e`)

Or I could use `curl` against the channel URL to determine what the new commit hash would be:

```
$ curl -Ls -o /dev/null -w %{url_effective} https://nixos.org/channels/nixpkgs-unstable
https://nixos.org/channels/nixos-16.03.887.009fa8e/
```

Unfortunately, now it seems that neither the store object nor the channel URL display the commit hash, or even a full version; instead they just show the major and minor version (in fact the `nixpkgs-unstable` channel doesn't even show this):

```
$ readlink -f ~/.nix-defexpr/channels/nixpkgs
/nix/store/lqkji0adam5ah7axwnwn8mb3a024k7ws-nixos-16.03/nixos

$ curl -Ls -o /dev/null -w %{url_effective} https://nixos.org/channels/nixos
https://nixos.org/channels/nixos-16.03/
```

This is a real bummer :disappointed: and it seems to have been a recent change. I'm not sure why this happened, but as it is the only way to derive the git commit for a channel snapshot is to download the channel and use `nix-instantiate`, which is clunky, harder to script, and also requires downloading a full channel before I can inspect it. I thought perhaps that the `nixpkgs` repo might have git tags which would convey this information, but this does not seem to be the case as there are only a handful of these tags.

### Steps to reproduce

Try any of the above commands, possibly after running `nix-channel --update`

## Technical details

In the description

* System: any
* Nix version: any
* Nixpkgs version: n/a

**Comment by bjornfor** [comment]
Unless I'm mistaken, I think this is what you want:

```
git remote add channels git://github.com/NixOS/nixpkgs-channels.git
git fetch channels
```

**Comment by edolstra** [comment]
Thanks, fixed! This was caused by a full disk.
