### ISSUE TITLE
db is broken on darwin on staging

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#18549]
See the discussion starting at https://github.com/NixOS/nixpkgs/issues/18461#issuecomment-246485172

cc @dhess

**Comment by copumpkin** [comment]
> Would the cxxSupport change you mentioned use gcc to compile db rather than clang?

Nope, it just turns off the c++ part of the bdb library, which will break downstream c++ consumers

> (I'm sorry for the noise in this thread, it's clearly unrelated to libiconv and we should probably move it to a new issue.)

That's why we're here now!

**Comment by dhess** [comment]
According to the Oracle thread you linked in the other thread, this may be a C++11 issue. It might be possible to force clang to use an earlier libstdc++. I'll start there. Probably won't have time to look at this for another day, though.

**Comment by dhess** [comment]
c.f. http://stackoverflow.com/questions/19774778/when-is-it-necessary-to-use-use-the-flag-stdlib-libstdc, especially the top answer's mention of Mavericks.

**Comment by copumpkin** [comment]
Clang has only ever used libc++ (not libstdc++) in nixpkgs for as long as I remember, and I don't think it "likes" having inconsistent library versions. Might be worth a try, but I'd mostly want to understand why we were fine with clang 3.7 and things broke when we moved to 3.8, since the Oracle thread suggests that he was seeing the issue on 3.7 when we never did.

**Comment by dhess** [comment]
Hmm, yes, good point. According to http://clang.llvm.org/cxx_status.html clang has implemented full C++11 since clang 3.3, so it seems unlikely this is a C++11 issue.

**Comment by LnL7** [comment]
This should be fixed in https://github.com/NixOS/nixpkgs/commit/10dae237c6364576e926dc72fc559b94a2d30ad4

**Comment by dhess** [comment]
Fixed! Thanks!

(New 10.12 problem now related to GHC 7.4.2. I'll file something when I've gotten to the bottom of it.)
