### ISSUE TITLE
Bubblewrap doesn't work on Wayland terminals launched with a KDE shortcut

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#185582]
### Describe the bug

EDIT: This might affect other programs too. 

Attempting to use the command `bwrap` in Wayland terminal launched with a KDE shortcut (or children of it, whether it's `steam-run` or another terminal launched from it), will return the error:
```
bwrap: Unexpected capabilities but not setuid, old file caps config?
```
No matter the arguments (even `--help`).

The terminal must be launched with a KDE shortcut. And it must be on Wayland. You also must **not** have root access (not using `sudo`). It happens no way else.

### Steps to Reproduce
With Konsole:

- Place the following file in `$HOME/.config` (remove the .txt, it's there because GitHub forces it): [kglobalshortcutsrc.txt](https://github.com/NixOS/nixpkgs/files/9282272/kglobalshortcutsrc.txt);
- Start a Plasma Wayland session (the file must be already placed);
- Launch Konsole with `CTRL+ALT+T`.
- Enter `bwrap`.

### Additional context
It seems that something is causing `capget` to return a different value.
The error message comes from the function https://github.com/containers/bubblewrap/blob/main/bubblewrap.c#L853.

Look at the `strace` logs (line 174):

- Terminal launched with KDE shortcut: [bwrap-strace-fail.txt](https://github.com/NixOS/nixpkgs/files/9277353/bwrap-strace-fail.txt)
- Otherwise: [bwrap-strace-success.txt](https://github.com/NixOS/nixpkgs/files/9277354/bwrap-strace-success.txt)

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.16-zen1, NixOS, 22.11 (Raccoon), 22.11.20220806.998bc5d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(martino): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
I finally found the exact reproducing conditions (edited the post above).
I wonder why and how they are so specific.

**Comment by kurnevsky** [comment]
I have the same problem, reported it to kde before thought to find the similar issue here :)
https://bugs.kde.org/show_bug.cgi?id=457844

**Comment by kurnevsky** [comment]
Can be fixed with this patch: https://github.com/kurnevsky/nixfiles/commit/4a60a78ff1519b14df6c2b1b7fe5183692e38899

**Comment by kurnevsky** [comment]
Here is the fix: https://github.com/NixOS/nixpkgs/issues/185582
