### ISSUE TITLE
opentrack-user-interface.so: invalid ELF header

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#185520]
### Describe the bug
`opentrack` crashes with
```
/nix/store/khm7x0lhf4j8mc43q4lycv1ylb532xfj-opentrack-2.3.13/bin/opentrack: error while loading shared libraries: /nix/store/khm7x0lhf4j8mc43q4lycv1ylb532xfj-opentrack-2.3.13/libexec/opentrack/opentrack-user-interface.so: invalid ELF header
```

### Steps To Reproduce
1. `nix run nixpkgs#opentrack`

### Expected behavior
No crash

### Additional context
It appears that `opentrack-user-interface.so` is wrapped by a Qt hook.

Also affected on 22.05.

Reported on [Reddit](https://www.reddit.com/r/NixOS/comments/wi2qs6/invalid_elf_header/)

### Notify maintainers
@zaninime 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.05 (Quokka), 22.05.20220806.72f492e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/etc/nix/channels/nixos`

**Comment by zaninime** [comment]
Thanks for reporting, once the above PR is merged I will also submit a backport to 22.05. There was indeed a problem with wrapping (but was working in the past, as I was using it almost daily).
