### ISSUE TITLE
FreeSO, An Open Source Reimplementation of The Sims Online

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#185539]
**Project description**
A full reimplementation of The Sims Online, using Monogame. While FreeSO aims to be faithful to the original game, it includes many quality of life changes such as hardware rendering, custom dynamic lighting, hi-res output and >2 floor houses. If you simply wish to play, you can install FreeSO and the original TSO files using our installer on http://freeso.org/, and it will connect to our official servers.

**Metadata**

* homepage URL: https://freeso.org/
* source URL: https://github.com/riperiperi/FreeSO
* license: MPL 2.0
* platforms: Windows, [Linux](https://lutris.net/games/install/10602/view)

**Comment by tengkuizdihar** [comment]
This project depends on mono, I haven't tried packaging it in anyway so I have no idea whether it is possible or not.

**Comment by raspher** [comment]
> FreeSO currently depends on the original game files (objects, avatars, ui) to function, which are available for download from EA servers. FreeSO is simply a game engine, and does not contain any copyrighted material in and of itself.

**Comment by tengkuizdihar** [comment]
@raspher https://www.youtube.com/watch?v=OTLmD2kFDm0
