### ISSUE TITLE
Emacs package Jade on melp-stable-generated is broken

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#18550]
## Issue description

Currently, jade in [melpa-stable-generated](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs-modes/melpa-stable-generated.nix) is defined as:

```nix
{
    jade = callPackage ({ company, emacs, fetchFromGitHub, fetchurl, js2-mode, lib, map, melpaBuild, seq, websocket }:
    melpaBuild {
        pname = "jade";
        version = "0.17";
        src = fetchFromGitHub {
          owner = "NicolasPetton";
          repo = "jade";
          rev = "11769bf8419202819a25047f57dd9aa0c98f5ebb";
          sha256 = "09zfvcirz7hcp255yhsf7d04vrc078kk69qhwy1j31ar0rb4fy1b";
        };
        recipeFile = fetchurl { [...] };
        packageRequires = [ company emacs js2-mode map seq websocket ];
        meta = { [...] };
      }) {};
}
```
When trying to install it, nix complains about missing `map` (which is included by default in Emacs 25):

```
error: anonymous function at /home/cassou/nixpkgs/pkgs/applications/editors/emacs-modes/melpa-stable-generated.nix:16665:25 called without required argument ‘map’, at /home/cassou/nixpkgs/lib/customisation.nix:56:12
```

Please also consider the `emacs` dependency which is put in `packageRequires`. This comes from Jade [defining Emacs 25 as a requirement](hhttps://github.com/NicolasPetton/jade/blob/53f99de02d786644c646b915121740d8ebb963a9/jade.el#L9):

```emacs
;; Author: Nicolas Petton <nicolas@petton.fr>
;; URL: https://github.com/NicolasPetton/jade
;; Keywords: tools, javascript
;; Version: 0.11
;; Package-Requires: ((emacs "25") (seq "2.16") (map "1.0") (js2-mode "20140114") (company "0.9.0") (websocket "1.6"))
```
Is it supposed to work?

Finally, please consider that Jade got a new release yesterday which removes `map` as an explicit dependency (because the `map` in Emacs 25 is enough).

## Technical details

* System: nixos-unstable

/cc @ttuegel @NicolasPetton

**Comment by ttuegel** [comment]
This is fixed now in master. We don't have the ability right now to filter packages based on Emacs version, so there is an Emacs 24 version listed which I presume doesn't work. However, the Emacs 25 version should be present and working.

**Comment by DamienCassou** [comment]
@ttuegel thanks for your reactivity
