### ISSUE TITLE
Package `inkdrop`

### ISSUE THREAD

**Issue by NotRennaru** [NixOS/nixpkgs#185546]
**Project description**
The Markdown Note-taking App

**Metadata**

* homepage URL: https://www.inkdrop.app/
* source URL: https://www.inkdrop.app/
* license: mit,
* platforms: cross-platform

**Comment by dit7ya** [comment]
Cannot find sources at the provided URL, nor does it seem like MIT licensed. Are you sure those details are correct?

**Comment by NotRennaru** [comment]
I will close this for now i think these details is incorrect
