### ISSUE TITLE
about iso \EFI\boot\grub.cfg 

### ISSUE THREAD

**Issue by jcleng** [NixOS/nixpkgs#185543]
**Describe the bug**

\EFI\boot\grub.cfg There are syntax errors in the contents of the file, and it cannot be started. It needs to be manually modified every time. It has been a long  long  time, and no one has found it?

**To Reproduce**

**Expected behavior**

**Screenshots**

[![vKgFiR.png](https://s1.ax1x.com/2022/08/07/vKgFiR.png)](https://imgtu.com/i/vKgFiR)
**Hydra Server:**

**Comment by milahu** [comment]
the indent is wrong, but the curly braces are ok

grub.cfg is produced by nixpkgs/nixos/modules/installer/cd-dvd/iso-image.nix

with the ISO from https://nixos.org/download.html ...

```
wget https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso

mkdir mnt

sudo mount -o loop nixos-*.iso mnt

grub-script-check mnt/EFI/boot/grub.cfg && echo ok
ok
```

[nixos-minimal-22.05.2818.b82ccafb541-x86_64-linux_EFI_boot_grub.cfg.txt](https://github.com/NixOS/nixpkgs/files/9479212/nixos-minimal-22.05.2818.b82ccafb541-x86_64-linux_EFI_boot_grub.cfg.txt)

**Comment by jcleng** [comment]
> the indent is wrong, but the curly braces are ok
> 
> grub.cfg is produced by [nixpkgs/nixos/modules/installer/cd-dvd/iso-image.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/iso-image.nix#L370)
> 
> with the ISO from https://nixos.org/download.html ...
> 
> ```
> wget https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso
> 
> mkdir mnt
> 
> sudo mount -o loop nixos-*.iso mnt
> 
> grub-script-check mnt/EFI/boot/grub.cfg && echo ok
> ok
> ```
> 
> [nixos-minimal-22.05.2818.b82ccafb541-x86_64-linux_EFI_boot_grub.cfg.txt](https://github.com/NixOS/nixpkgs/files/9479212/nixos-minimal-22.05.2818.b82ccafb541-x86_64-linux_EFI_boot_grub.cfg.txt)

If I boot in legy mode, I have no problem. If I boot in uEFI mode, then can't boot. Could this be a compatibility problem

**Comment by milahu** [comment]
cannot reproduce in qemu + [uefi bios](https://www.ubuntubuzz.com/2021/04/how-to-boot-uefi-on-qemu.html)

```
wget https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso

nix-shell -p qemu OVMF.fd

qemu-system-x86_64 -bios /nix/store/ksch3xpsb8cs5x143zml99gafd8fnl26-OVMF-202202-fd/FV/OVMF.fd -cdrom nixos-*.iso -m 512
```

> If I boot in uEFI mode, then can't boot.

whats your error?

> It needs to be manually modified every time.

how do you fix `grub.cfg`?

**Comment by jcleng** [comment]
> cannot reproduce in qemu + [uefi bios](https://www.ubuntubuzz.com/2021/04/how-to-boot-uefi-on-qemu.html)
> 
> ```
> wget https://channels.nixos.org/nixos-22.05/latest-nixos-minimal-x86_64-linux.iso
> 
> nix-shell -p qemu OVMF.fd
> this path will be fetched (0.91 MiB download, 8.00 MiB unpacked):
>   /nix/store/ksch3xpsb8cs5x143zml99gafd8fnl26-OVMF-202202-fd
> copying path '/nix/store/ksch3xpsb8cs5x143zml99gafd8fnl26-OVMF-202202-fd' from 'https://cache.nixos.org'...
> 
> qemu-system-x86_64 -bios /nix/store/ksch3xpsb8cs5x143zml99gafd8fnl26-OVMF-202202-fd/FV/OVMF.fd -cdrom nixos-*.iso -m 512
> ```
> 
> > If I boot in uEFI mode, then can't boot.
> 
> whats your error?
> 
> > It needs to be manually modified every time.
> 
> how do you fix `grub.cfg`?

but the latest version seems to fail, and only Legey mode works on the Livecd

**Comment by ne9z** [comment]
LiveCD GRUB EFI boot works for me, as of NixOS `22.11.20230318.08ef7dc (Raccoon)
`.
