### ISSUE TITLE
Define what unfree means

### ISSUE THREAD

**Issue by Jookia** [NixOS/nixpkgs#18557]
## Issue description

There seems to be no clear definition of what an 'unfree' package is in documentation
### Steps to reproduce

N/A
## Technical details

N/A

**Comment by vcunat** [comment]
I believe it's mostly clear. There are several widely recognized "authorities" that classify licenses as (un)free: [OSI](https://opensource.org/), [FSF](http://www.fsf.org/) or e.g. DFSG (in no particular order). AFAIK the licenses where these disagree [are rather rare](https://en.wikipedia.org/wiki/The_Free_Software_Definition#Comparison_with_the_Open_Source_Definition).

I think the worst we could do is to start working on yet another definition.

**Comment by Jookia** [comment]
See https://github.com/NixOS/nixpkgs/pull/16852#issuecomment-233159949

**Comment by 7c6f434c** [comment]
«Hydra cannot redistribute» means «we don't think the _license_ allows us to redistribute it from Hydra»

**Comment by vcunat** [comment]
We also have redistributable pseudo-licenses: `licenses.unfreeRedistributable` and `licenses.unfreeRedistributableFirmware`; those aren't built on Hydra for now, though in theory they could be. Related: https://github.com/NixOS/nixpkgs/issues/15162#issuecomment-217628104

**Comment by Jookia** [comment]
Could it get noted that unfree means the software license is generally agreed to be nonfree?

**Comment by nixy** [comment]
While I understand the rationale behind this definition, I think it could be more specific. For example, the Linux kernel, which contains proprietary blobs, is licensed under the GPLv2 and is considered free according to these standards. Some organizations, such as the FSF, would not consider this to be free.

I wouldn't go so far as to say that the Linux kernel should be in the unfree category, but it might be better to create another category for varying levels of "freeness".

**Comment by Jookia** [comment]
It'd be better to start with a good definition now so packages can be fixed

**Comment by nixy** [comment]
Well, I think that unfree as defined by licenses accepted by organizations, such as the FSF and OSI, is fine. I don't think there is a much better way to categorize whether or not something is free and the existing definition should be upheld.

I would like it if we defined an additional layer of "freeness" that would be compliant with the FSF's [free distribution guidelines](https://www.gnu.org/distros/free-system-distribution-guidelines.html). However, this would require quite a bit of effort to maintain as it would require packages to be explicitly flagged as free based on their contents and not just their licensing. If this was implemented as an additional optional flag for each package I think it might work, but the overhead in maintaining such a thing would be significant.

I just wanted to put this out there. I think it would be a good thing to do, but I am not sure if the nixpkgs community would be willing to do this as it would require a non-trivial amount of work.

**Comment by Jookia** [comment]
On Fri, Sep 16, 2016 at 01:13:39AM -0700, Andrew Miller wrote:
> Well, I think that unfree as defined by licenses accepted by organizations, such as the FSF and OSI, is fine. I don't think there is a much better way to categorize whether or not something is free and the existing definition should be upheld.

To my knowledge there's no existing definition of unfree in nixpkgs that notes
this. Could this be fixed?

**Comment by vcunat** [comment]
Well, the whole `meta.license` thing tends to be vague. For example, there are loads of packages where different *source* files come under different licenses; not all of those necessarily affect the resulting binary files, etc.

Personally, when I care for precise info, I go to corresponding [Debian copyright file](http://metadata.ftp-master.debian.org/changelogs//main/b/bash/bash_4.3-11_copyright).

IMHO the very purpose of `licenses.unfree` is that you don't want to go into details about that non-standard license, often a long custom EULA text.

**Comment by Jookia** [comment]
On Fri, Sep 16, 2016 at 11:54:57AM -0700, Vladimír Čunát wrote:
> Well, the whole `meta.license` thing tends to be vague. For example, there are loads of packages where different *source* files come under different licenses; not all of those necessarily affect the resulting binary files, etc.
> 
> Personally, when I care for precise info, I go to corresponding [Debian copyright file](http://metadata.ftp-master.debian.org/changelogs//main/b/bash/bash_4.3-11_copyright).
> 
> IMHO the very purpose of `licenses.unfree` is that you don't want to go into details about that non-standard license, often a long custom EULA text.

I'm not trying to talk about how precise things are, we don't have a way to say
a package is under a nonfree license, just different opinions what
licenses.unfree means.

**Comment by Profpatsch** [comment]
Unfree is every license in https://github.com/NixOS/nixpkgs/blob/master/lib/licenses.nix that has the field `free = false`.
