### ISSUE TITLE
prometheus-zfs-exporter

### ISSUE THREAD

**Issue by razielgn** [NixOS/nixpkgs#185575]
**Project description**
Prometheus exporter for ZFS (pools, filesystems, snapshots and volumes).

**Metadata**

* homepage URL: https://github.com/pdf/zfs_exporter
* source URL: https://github.com/pdf/zfs_exporter
* license: MIT https://github.com/pdf/zfs_exporter/blob/master/LICENSE
* platforms: linux

**Comment by peterhoeg** [comment]
The standard node exporter has support for zfs. That doesn't do it for you?

Btw, the prometheus exporters are generally trivial to package, so it might not be a bad place to start if you want to give it a go.

**Comment by razielgn** [comment]
I checked but unfortunately the node exporter does not have the ability to expose datasets/pools properties as metrics.

Yes I am almost done with the derivation to include it, I'll submit a PR soon.
Since I'm also adding a nixos module to make it a systemd service (same as the other exporters) and provide some basic configuration knobs, is it ok to include it in the same PR as the derivation?

**Comment by peterhoeg** [comment]
Damn, I didn't realize you were in Kiev. PR open. Hope you're safe.

**Comment by peterhoeg** [comment]
Crossed lines, sorry, it was as fast as I could do it.

There is in principle nothing wrong with having the nixos module be part of the same PR as long as the commits are separate. 

However, the more a PR covers, the more likely getting it merged will drag out. I typically split them up (package first, module later) or do the 2 PRs concurrently.

**Comment by razielgn** [comment]
>Crossed lines, sorry, it was as fast as I could do it.

No worries, I still learned a lot, it came out 95% similar to you PR.

>Damn, I didn't realize you were in Kiev.

Thanks, I'm safe in another country. :)

>However, the more a PR covers, the more likely getting it merged will drag out. I typically split them up (package first, module later) or do the 2 PRs concurrently.
Ok got it, so I'll open a PR after yours get merged to add the nixos modules.
