### ISSUE TITLE
Use GTK3 by default where applicable

### ISSUE THREAD

**Issue by aske** [NixOS/nixpkgs#18559]
With #18498 merged there's still some work left with distinguishing packages which may benefit from using GTK3.

The list below contains packages which seem to support both GTK2 and GTK3 or do something strange (like using both gtk versions or using `libcanberra_gtk2` with GTK3).
Right now they are all set to use GTK2.

(feel free to fill in checkboxes if you make any changes): 
- [ ] `gegl`
- [ ] `gksu`
- [x] `gvfs`
- [ ] `geary`
- [ ] `pomodoro` (via caribou and ibus GTK immodules)
- [x] `kazam`
- [ ] `keybinder`
- [ ] `libgksu`
- [ ] `libreoffice`
- [x] `nvidia-x11`
- [ ] smth in `top-level/lua-packages.nix`
- [ ] `lxappearance`
- [ ] `mkcast`
- [ ] `mysql-workbench`
- [ ] `oneteam`
- [ ] `planetaryannihilation`
- [ ] `scilab`
- [ ] `slurm`
- [x] `spice-gtk`
- [ ] `tango-icon-theme`
- [ ] `vivaldi`
- [ ] `workrave`
- [ ] `atom/env.nix`
- [ ] `celestia`
- [ ] `chromedriver`
- [ ] `bluez5`
- [ ] `java/classpath.nix`
- [ ] `python-notify` (?)
- [ ] `desmume`
- [ ] `dia`
- [ ] `pango` from haskell
- [ ] `factor-lang`
- [x] `firefox-bin`
- [ ] `gnome-shell`
- [x] `guake`
- [ ] `guileGnome` in toplevel
- [ ] `MonoAddins`
- [ ] `node-webkit`
- [ ] `tangogps`
- [x] `terminator`
- [ ] `thrust`
- [x] `thunderbird-bin`
- [x] `totem`
- [ ] `wicd`
- [ ] `wine`
- [x] `libcanberra_kde`
- [x] `libcanberra_gtk3`
- [ ] `aumix`
- [x] `wireshark`
- [x] `libinfinity`
- [ ] `radare`
- [ ] `mtr`
- [ ] `chromium`
- [ ] `emacs24`
- [x] `emacs25`
- [ ] `pinentry` (see references below)

**Comment by aske** [comment]
( **TODO** )
`libcanberra` contains  
```
passthru = {
    gtkModule = "/lib/gtk-2.0/";
  };
```
Which seems to be used only in firefox right now (09f342edc991e63d5873ca474fa8c850dcafad2a).

**Comment by rycee** [comment]
Perhaps could add `emacs24` and `emacs25` to this list?

**Comment by aske** [comment]
@rycee Thanks, added!

Also if anyone wants to see some packages on that list -- feel free to edit the post with it.

**Comment by siddharthist** [comment]
@aske Could this issue include an outline of how to transition a given package to GTK3? I would love to help but don't know where to start.

**Comment by aske** [comment]
@siddharthist Well, things to do will probably vary wildly from package to package.
A lot probably wouldn't require any changes; also could be a lot of bumping `libcanberra` to gtk3 (gtk3 and `libcanberra_gtk2` are used together a lot for some reason)

Very roughly it can go like this:

1. Open package, look for uses of `gtk{2,3}`, `pygobject{2,3}`, `gtk-sharp-{2_0,3_0}`, `gtkmm{2,3}`, `gtkspell{2,3}`, `gnome{2,3}`, `libcanberra_gtk{2,3}`.
2. Try to identify whether package can use newer gtk (or we can remove unneeded inputs) by looking at nix file, package homepage, but tracker, etc. 
3. Try to build package with new gtk and look at results.

Hope that helps a bit!

**Comment by peterhoeg** [comment]
You can close ```wireshark```.

**Comment by peterhoeg** [comment]
And ```emacs25```.

**Comment by vcunat** [comment]
I checked-off those, including nvidia #22304.

**Comment by jtojnar** [comment]
Please add pinentry to the list. It was originally done in https://github.com/NixOS/nixpkgs/pull/27468/commits/3f7e3db74426f658b4625505d262c1f7b288606d but it was reverted due to https://github.com/NixOS/nixpkgs/pull/27468#issuecomment-334016411

**Comment by vcunat** [comment]
done

**Comment by jtojnar** [comment]
In #32749, I removed `libcanberra_gtk2` from `gnome3.gsound`, `gnome3.gnome_control_center`, `gnome3.mutter` and `gnome3.pomodoro`. Though some of them still have gtk2 transitively from other derivations (`ibus`, `gnome3.caribou`).

Maybe it would be possible to move the gtk modules (`$out/lib/gtk-{2,3}.0`) into a separate outputs whitelisted through NixOS module (e.g. `i18n.inputMethod.ibus.toolkits = [ "gtk2" "gtk3" "qt5" ]`). Or perhaps blacklisting makes more sense here. `libcanberra` would be more complicated since there are also [libraries](https://user-images.githubusercontent.com/705123/34076716-c45b982c-e2ef-11e7-9e62-1f2f17daabab.png). And `gnome3.caribou` is troubling as well since GNOME Shell will presumably crash when trying to use touch screen in the absence of some of caribou’s component (gtk module? need to investigate).

**Comment by vcunat** [comment]
NixOS can do per-name output white-listing already, so that could be re-used easily: `environment.extraOutputsToInstall` (affecting additions via `systemPackages`).

**Comment by worldofpeace** [comment]
This is pretty out of date. Internally we should probably just open a tracking issue and start a new GitHub project. I don't see much point of adding this to our milestones where there's not much to do with this exact issue.
