### ISSUE TITLE
qt5 applications broken on darwin

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#185615]
### Describe the bug

Upon launch of any qt application it's icon appears in the dock, but no windows are opened. It will hang indefinitely and dock says "Application does not respond".

Bisecting, say, `wireshark` points to a88af94894f31e6cce358e49610a6fcb5b4f6f13 cc @willcohen
```
a88af94894f31e6cce358e49610a6fcb5b4f6f13 is the first bad commit
commit a88af94894f31e6cce358e49610a6fcb5b4f6f13
Author: Will Cohen <willcohen@users.noreply.github.com>
Date:   Wed Apr 13 15:27:00 2022 -0400

    qt5, libsForQt5: 5.12 -> 5.14 on darwin

 pkgs/top-level/all-packages.nix | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
```

### Steps To Reproduce
1. `nix-build . -A wireshark`
2. `result/Applications/Wireshark.app`

### Expected behavior

Qt applications should work

### Additional context
The issue is not specific to wireshark.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: macOS 10.16 and on 10.14
```

**Comment by OPNA2608** [comment]
![Screenshot_macOS_2022-08-08_03:00:33](https://user-images.githubusercontent.com/23431373/183319368-2d281ec3-3523-4e6e-af98-43fb8e8954bf.png)

Also tested one other Qt5 application (`bambootracker`) and it launched fine.

```yml
- system: `"x86_64-darwin"`
- host os: `Darwin 17.7.0, macOS 10.13.6`
```

**Comment by jiegec** [comment]
I can reproduce this problem on:

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.5`
```

**Comment by veprbl** [comment]
On force quitting the Wireshark it lets me open the "report to Apple window", from which I'm able to pick up some traces
https://gist.github.com/veprbl/3be95a6f0fa41a7b25f0dba0eb8c7c44
What is strange about those, is that it mentions OpenSCAD. Could be some clashing UUID somewhere. However I've tried removing OpenSCAD from my home-manager profile and logging in with a "Guest" user, and that did not resolve the issue.

**Comment by jiegec** [comment]
Bamboo Tracker:

- Qt 5.12 Good
- Qt 5.14 Failed to launch
- Qt 5.15 Good

Wireshark

- Qt 5.12 To be tested
- Qt 5.14 Failed to launch
- Qt 5.15 To be tested

By the way, when I was building Wireshark, `lrelease` might crash if sandbox is enabled, see https://github.com/NixOS/nixpkgs/pull/82815.

**Comment by tanshihaj** [comment]
Wireshark, qt5.15, aarch64-darwin:
Launches with warning window `The plugin usbdump.so has no plugin_version symbol` and this messages in `stderr`:
```
...
dyld[35216]: Library not loaded: @rpath/libwsutil.13.dylib
  Referenced from: /nix/store/0244jj9cwb86sdl5bgcfs995nnz8sv5z-wireshark-qt-3.6.5/Applications/Wireshark.app/Contents/MacOS/extcap/.ciscodump-wrapped
  Reason: tried: '/tmp/nix-build-wireshark-qt-3.6.5.drv-0/wireshark-3.6.5/build/run/libwsutil.13.dylib' (no such file), '/nix/store/y5cp9q9h6p80mzbsijs00zxpi7g0lc9d-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/libwsutil.13.dylib' (no such file), '/tmp/nix-build-wireshark-qt-3.6.5.drv-0/wireshark-3.6.5/build/run/libwsutil.13.dylib' (no such file), '/nix/store/y5cp9q9h6p80mzbsijs00zxpi7g0lc9d-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/libwsutil.13.dylib' (no such file), '/usr/local/lib/libwsutil.13.dylib' (no such file), '/usr/lib/libwsutil.13.dylib' (no such file)
```
