### ISSUE TITLE
Synpatics touchpad missing with kernel 5.19

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#185623]
### Describe the bug

Putting this out here in case anybody else is seeing this.

On am Acer Swift SF314-43, the touchpad goes missing with kernel 5.19. Works again with kernel 5.18 and no other changes.

### Steps To Reproduce
1. upgrade to kernel 5.19
2. observe that it's broken

### Additional context

With kernel 5.18:
```console
$ journalctl -k -b-1 | grep SYNA
Aug 08 11:18:45 midge kernel: input: SYNA7DAB:00 06CB:CD40 Mouse as /devices/platform/AMDI0010:03/i2c-5/i2c-SYNA7DAB:00/0018:06CB:CD40.0001/input/input7
Aug 08 11:18:45 midge kernel: input: SYNA7DAB:00 06CB:CD40 Touchpad as /devices/platform/AMDI0010:03/i2c-5/i2c-SYNA7DAB:00/0018:06CB:CD40.0001/input/input8
Aug 08 11:18:45 midge kernel: hid-generic 0018:06CB:CD40.0001: input,hidraw0: I2C HID v1.00 Mouse [SYNA7DAB:00 06CB:CD40] on i2c-SYNA7DAB:00
Aug 08 11:18:45 midge kernel: input: SYNA7DAB:00 06CB:CD40 Mouse as /devices/platform/AMDI0010:03/i2c-5/i2c-SYNA7DAB:00/0018:06CB:CD40.0001/input/input11
Aug 08 11:18:45 midge kernel: input: SYNA7DAB:00 06CB:CD40 Touchpad as /devices/platform/AMDI0010:03/i2c-5/i2c-SYNA7DAB:00/0018:06CB:CD40.0001/input/input12
Aug 08 11:18:45 midge kernel: hid-multitouch 0018:06CB:CD40.0001: input,hidraw0: I2C HID v1.00 Mouse [SYNA7DAB:00 06CB:CD40] on i2c-SYNA7DAB:00
```

With kernel 5.19:
```console
$ journalctl -b -k | grep SYNA
```

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.11 (Raccoon), 22.11.20220807.e7cc56e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/store/3xxgfpsdmjnavbflp7hgl8myiifkb5fm-yachiv88197s4v5ssvqcr8njafgina19-source`
```

**Comment by ikselven** [comment]
This happended to me as well, on a Tuxedo Aura Gen 1 with an ElanTech clickpad and NixOS 22.05.

Comparing the output of `lsmod` between kernel 5.18 and 5.19 I found three modules, which haven't been loaded on 5.19: `hid_generic`, `hid_multitouch` and `pinctrl_amd`. I added them to `boot.kernelModules`, ran `nixos-rebuild switch` and after  rebooting the touchpad is working again.

**Comment by peterhoeg** [comment]
Ah, on 5.19:

```console
$ zgrep PINCTRL_AMD /proc/config.gz
# CONFIG_PINCTRL_AMD is not set
```

Kernel rebuilding time. Haven't done that in a while...

**Comment by peterhoeg** [comment]
So that did it. I didn't need to specify the list of modules, only add the
kernel option.

**Comment by ikselven** [comment]
That fixed it on my Tuxedo as well.
