### ISSUE TITLE
GNOME System Monitor cannot kill a process owned by root

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#185764]
### Describe the bug
When trying to terminate or kill a process owned by root, it fails without asking for the password.

### Steps To Reproduce
1. Launch System Monitor as normal user
2. Run some command as root for testing (e.g. `sudo sleep 666`)
3. Find the process in System Monitor, and try to kill it

### Expected behavior
It should ask for my password, and then kill the process.

### Screenshots
[录屏 2022年08月09日 17时03分30秒.webm](https://user-images.githubusercontent.com/12882091/183610413-b5d738b4-7051-4d02-8ff3-c49a5ba0cae2.webm)

### Notify maintainers
@jtojnar @bobby285271 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.11 (Raccoon), 22.11pre398503.4bdf4169ad2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(yes): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by NickCao** [comment]
A more appropriate fix to be upstreamed.
```cpp
diff --git a/src/gsm_pkexec.cpp b/src/gsm_pkexec.cpp
index 868969ba..4060846e 100644
--- a/src/gsm_pkexec.cpp
+++ b/src/gsm_pkexec.cpp
@@ -33,6 +33,8 @@ gboolean gsm_pkexec_create_root_password_dialog(const char *command)
 gboolean
 procman_has_pkexec(void)
 {
-    return g_file_test("/usr/bin/pkexec", G_FILE_TEST_EXISTS);
+    gchar *command = g_find_program_in_path("pkexec");
+    g_free(command);
+    return (command != NULL) ? TRUE : FALSE;
 }
```

**Comment by jtojnar** [comment]
Thanks for reporting, I opened https://github.com/NixOS/nixpkgs/pull/185765.
