### ISSUE TITLE
pkgs.networkmanager_strongswan does not work with NetworkManager properly

### ISSUE THREAD

**Issue by EvgenyNerush** [NixOS/nixpkgs#185761]
### Description
With `networkmanager_strongswan` IPsec/IKEv2 VPN can be added in Gnome's user interface, but connection to VPN with NetworkManager is missing. 

### Steps To Reproduce
1. Install networkmanager_strongswan: add the following lines to `/etc/nixos/configuration.nix`:
```console
networking.networkmanager = {
  enable = true;
  plugins = [ pkgs.networkmanager_strongswan ];
};
```
then run `nixos-rebuild switch`.
2. Configure VPN with `Settings -> Network -> VPN -> + -> IPsec/IKEv2 (strongswan)` (I try [FuckRKN1](https://github.com/nezavisimost/FuckRKN1)).
3. Try to connect (slide bar to "on" position), but with no result (VPN is off).

### Expected behavior
VPN on

### Error
`journalctl -u NetworkManager` shows the following error message:

```console
charon-nm[1715]: Failed to initialize a plugin instance: Connection ":1.81" is not allowed to own the service "org.freedesktop.NetworkManager.strongswan" due to security policies in the configuration file
charon-nm[1715]: 00[CFG] DBUS binding failed
charon-nm[1715]: 00[LIB] feature CUSTOM:NetworkManager backend in critical plugin 'nm-backend' failed to load
charon-nm[1715]: 00[LIB] failed to load 1 critical plugin feature
charon-nm[1715]: 00[DMN] initialization failed - aborting charon-nm
```

### System
`nixos-version`: 22.05.2199.478f3cbc844 (Quokka)
`nix-env --version`: 2.8.1

**Comment by EvgenyNerush** [comment]
The problem is solved. The packages `networkmanager`, `strongswanNM` and `networkmanager_strongswan` should be properly added to `/etc/nixos/configuration.nix`:

```bash
  services.dbus.packages = [ pkgs.networkmanager pkgs.strongswanNM ];
  networking.networkmanager = {
    enable = true;
    plugins = [ pkgs.networkmanager_strongswan ];
  };
```

Then VPN can be configured in GUI and works properly.

**Comment by NickHu** [comment]
You can set `networking.networkmanager.enableStrongSwan = true;` instead
