### ISSUE TITLE
gitMinimal reproducibly fails t3910-macos-precompose.sh on ZFS with formD normalization

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#185882]
### Steps To Reproduce
1. Set up NixOS on ZFS
2. Build `gitMinimal`
3. Observe `t3910-mac-os-precompose.sh` failing

### Build log
```
[...]
git-minimal> t3910-mac-os-precompose.sh ......................... Dubious, test returned 1 (wstat 256, 0x100)
git-minimal> Failed 10/25 subtests 
git-minimal>         (1 TODO test unexpectedly succeeded)
[...]
git-minimal> Test Summary Report
git-minimal> -------------------
git-minimal> t0050-filesystem.sh                              (Wstat: 0 Tests: 11 Failed: 0)
git-minimal>   TODO passed:   9-10
git-minimal> t3910-mac-os-precompose.sh                       (Wstat: 256 (exited 1) Tests: 25 Failed: 10)
git-minimal>   Failed tests:  1, 4, 6, 8, 11-16
git-minimal>   TODO passed:   23
git-minimal>   Non-zero exit status: 1
git-minimal> Files=956, Tests=24217, 93 wallclock secs (18.06 usr  5.03 sys + 724.41 cusr 2624.67 csys = 3372.17 CPU)
git-minimal> Result: FAIL
git-minimal> make[1]: *** [Makefile:56: prove] Error 1
git-minimal> make[1]: Leaving directory '/build/git-2.37.1/t'
git-minimal> make: *** [Makefile:3065: test] Error 2
```

### Additional context
This reproducibly happens on the one host that runs on ZFS on the root filesystem / nix store.

### Notify maintainers
@primeos 
@globin 
@wmertens 

### Metadata
Reproduced today on 14463eff815e2b1129ee79dd55c64de97d0d712d.

**Comment by wmertens** [comment]
I presume this is ZFS on Linux? Do you have some error output?

I think the first step is determining if it is an upstream issue or due to the NixOS build.

**Comment by mweinelt** [comment]
Yes, ZoL. I don't have any more output than that. Running the tests from the repo requires a `GIT-BUILD-OPTIONS` file.

**Comment by mweinelt** [comment]
Detailed logs on the two test failures.

https://gist.github.com/mweinelt/88f2637a7d3e94d0805d894ec9bbe4fb

**Comment by winterqt** [comment]
This is an upstream issue, and I've submitted a patch to fix it (see https://github.com/git/git/pull/1351). When it gets accepted, we can backport it here until it lands in a release.
