### ISSUE TITLE
Nixos: robustness of device mounts

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#1858]
Yesterday I got a drive device renamed that contained an inessential mount [1]. As a result, booting into any previous config was quite impossible, and it took me hours to rescue from this deadlock. I don't really understand the boot process, but some things struck me as wrong:
- the job for bringing up the non-existent device/fs was taking tens of seconds to fail (it would even make shutdown take roughly a minute),
- attempting to ignore the error by ^D wouldn't work,
- other essential services failed, e.g. logind, dhcpcd, wpa_supplicant (no idea why, they were OK with the mount working);
- in emergency shell, any attempt to start the failed devices, or e.g. start dhcpcd by hand resulted in the shell not responding to anything (except Ctrl+Alt+Del).

Would you enlighten me on this issue?

[1] Unrelated thing -- how it originated: I deleted one fs partition in gparted, and it automagically renamed my /dev/sda10 to /dev/sda9 (I don't know why). As HW detection in nixos doesn't add mounts by label name, it resulted in configs not finding it (I had hand-config for mount-by-label before, but I deleted that when detection added the same mounts).

**Comment by Profpatsch** [comment]
(triage) I think it is quite crucial that this issue be resolved asap. Can we put this on the agenda again?

**Comment by vcunat** [comment]
Our hardware-configuration.nix gets mounts by UUID (maybe for a year already), so the probability of running into missing mounts is somewhat lessened. Otherwise the issue probably persists, judging from (my) lack of knowledge of any (other) steps that would address it.

**Comment by 0xABAB** [comment]
https://github.com/NixOS/nixpkgs/issues/17047 might also be an instance of this.

**Comment by 0xABAB** [comment]
```nixos-rebuild switch``` 
is not pure, because it depends on the location of the current working directory (the general problem is worse). E.g. if your configuration tries to umount a location where you currently are, it fails. 

At the very least it should be possible to add an assertion.

**Comment by vcunat** [comment]
It's impossible to be completely pure. You can't in general completely switch without a reboot; it's best-effort but there certainly is a room for improvement.

**Comment by Nadrieril** [comment]
This issue seems stalled, but the problem is important.
Would it suffice to document using `fileSystems.<name?>.options = [ "nofail" ]` for non-critical filesystems in https://nixos.org/nixos/manual/index.html#ch-file-systems ?
Otherwise, setting `nofail` by default can IMHO only reduce the number of whole-system crashes due to a filesystem failure and therefore seems worth a try.

**Comment by 0xABAB** [comment]
> Anyway, this is why you should always use /dev/disk/by-uuid or /dev/disk-by-label.

@edolstra I agree that this is what should be done. I don't see why we should even support any other configuration and to properly model this in NixOS, we should treat it as an error to configure it in any other way. 

It's just a matter of protecting the user against themselves. /dev/sda1, etc. are meant for kernel developers, not system developers. If one is a kernel developer, we could add a flag `kerneldeveloper', which then disables all such protections (which I am sure some people would be against to have). This way, for the majority of the people it will just work.

**Comment by vcunat** [comment]
The `nixos-install` tools does (now) generate the mounts as `/dev/disk/by-uuid`.  (I believe it wasn't the case years ago.)  If people explicitly write `/dev/sXXn`, I'd expect they know what they're doing, but I don't see good arguments *against* adding something similar to what you suggest.
