### ISSUE TITLE
nixos successfully activate broken systemd timer

### ISSUE THREAD

**Issue by spinus** [NixOS/nixpkgs#18593]
## Issue description

I have systemd service with timer. When I activate configuration, nixos exits successfully but timer configuration is broken.
### Steps to reproduce
1. Add some broken timer 

```
+  100     systemd.services.my-cron = {                 
+  101       preStart = ''                                                             
+  102         # just check if the command is for sure installed                       
+  103         exec command --help
+  104       '';                                                                       
+  105       script = ''exec command import'';
+  106       startAt = "* *-*-* 06:00:00";                                             
+  107       restartIfChanged = false;                                                 
+  108       stopIfChanged = false;                                                    
   109     };  
```
1. `nixos-rebuild switch`, activation scripts says everything is good
2. `systemctl cat my-cron.timer`

```
Failed to parse calendar specification, ignoring: * *-*-* 06:00:00
```
## Technical details
- System: (NixOS: `16.09pre-git`)
- Nix version: (run `nix-env (Nix) 1.11.2`)
- Nixpkgs version: (run `15.09.1134.19a3dd8`)

I'm deploying 16.09 nixpkgs using NixOps to instance created from 15.09 AMI.

**Comment by vcunat** [comment]
I see no use to have two almost identical tickets. When activating NixOS, it's a bit late for this and AFAIK it would be no good to fail at that point.

**Comment by spinus** [comment]
@vcunat why do you think they are almost identical?
Is build validation almost identical to service activation?

I see this as two completle separate problems, also (probably) they are implemented in different places. One is just pure build time problem, and the other is activation script. I discovered them at once but those are different things. Also it's easier to progress through them as somebody could fix one by one. Where now somebody will fix only one, or have to fix both at the same time.

**Comment by vcunat** [comment]
I don't think the activation script really can fail. You would have half-started system. IMHO it's better to try to keep going and get as close to success as possible.

**Comment by spinus** [comment]
also, I'm not huge fan of ignoring errors silently :[

**Comment by vcunat** [comment]
I see. This **silence** is what could be improved.

**Comment by Profpatsch** [comment]
systemd ignores malformed entries in unit files. This is intended functionality, to “improve boot stability” as the systemd devs say. So this is a wontfix by upstream. 

As I mentioned in https://github.com/NixOS/nixpkgs/issues/18594#issuecomment-399750489 we cannot easily check the files at build time, regrettably.
