### ISSUE TITLE
$HOME/.profile isn't read by X11 display managers

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixpkgs#185979]
### Describe the bug

When coming from another distro, the environment of the sessions started by the X11 display managers aren't similar. This can lead to some custom programs not working, especially those that depend on environment variables e.g `PYTHONPATH`, `PATH`, or whatever else these custom programs depend on.

### Steps To Reproduce
1. set an environment variable in `$HOME/.profile` e.g `MY_ENVIRONMENT=hello`
2. Make an application shortcut on the desktop with the command `echo $MY_ENVIRONMENT > /tmp/environment`
3. Log out and login
4. Execute the application short
5. Open `/tmp/environment`

### Expected behavior

`/tmp/environment` should contain `hello`

### Screenshots

![image](https://user-images.githubusercontent.com/2829538/184009986-bc3ef8b7-55f9-49c2-b143-c829c9d488d1.png)

### Additional context

nixOS has an undocumented and non-standard `$HOME/.xprofile` that is sources in [`xsession-wrapper`](https://github.com/NixOS/nixpkgs/blame/6b13dd0e9e7e0097bf796394386f0e88c33b172e/nixos/modules/services/x11/display-managers/default.nix#L40) which took me days to find before understanding why `$HOME/.profile` wasn't being loaded.

It would be great to not have to dig through code to find out a bout `.xprofile`, but it would be even better to just use a standard file (namely `.profile`) instead of the aforementioned undocumented and non-standard `.xprofile`.

### Notify maintainers

@vcunat @pSub (who was the earliest author I could find for `$HOME/.xprofile` https://github.com/NixOS/nixpkgs/commit/badb4753e48b80b95bf9688b6fff153a92ec48c3)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.05 (Quokka), 22.05.2340.490f6174c03`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vcunat** [comment]
I think that's this old and long thread: https://github.com/NixOS/nixpkgs/issues/5200
