### ISSUE TITLE
guideline/hints for module style

### ISSUE THREAD

**Issue by cransom** [NixOS/nixpkgs#18603]
## Issue description

I'm interested in writing more modules for NixOS and making it easier for others to do so also. I have a few that I use internally that may be of use to the community but they currently do some things that appear to be against NixOS best practices. The trouble is, I'm having a hard time finding a list of those practices.

I'd be happy to submit a PR for https://nixos.org/nixos/manual/index.html#sec-writing-modules to give some more guidance about what code should and shouldn't do if there are any current recommendations. 

Some things I've picked up that I think should be included but are up for discussion:
- `environment.systemPackages` should not be included in a server module
- referencing files from a package, triggering `import-from-derivation`, is possible, but shunned. A comment in nixpkgs states it being controversial but no documentation pointers mentioning why.
- mention `defaultText`

Questions:
- What should a module do? A network service isn't useful unless the firewall is open. Should the module add it to the allowed ports? Should there be a separate option to open the firewall that's disabled by default?  Similar for strongly recommended suggestions options like the swappiness sysctl.
- For services that have overly verbose config files, should that be contained in the module? Or should the user supply it.
### Steps to reproduce

n/a
## Technical details

n/a

**Comment by domenkozar** [comment]
Firewall should be opened manually, openssh is an exception. We should document that.

Overly verbose config files usually have different hooks, so you can override the whole config or just add an extra snippet.

**Comment by mpsyco** [comment]
Related: Agree on common high-level packaging guidelines #16041

**Comment by vcunat** [comment]
> triggering import-from-derivation, is possible, but shunned. A comment in nixpkgs states it being controversial but no documentation pointers mentioning why.

It makes nix *build* stuff during *evaluation*, which breaks assumptions of some tools and people, and it currently doesn't work on Hydra AFAIK.

**Comment by Nadrieril** [comment]
There are some pointers in the nixpkgs contributors manual (https://nixos.org/nixpkgs/manual/#idm140737317248784, section 12.4. New modules), but not a lot.

**Comment by aanderse** [comment]
@cransom the situation today is better than 2 years ago... but is the situation good enough you would consider this resolved?

**Comment by cransom** [comment]
I think it is better.
