### ISSUE TITLE
libtiff source URLs are dead

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18607]
Any URLs at `remotesensing.org` no longer work.

[Libtiff goes offline](https://madfileformatscience.garymcgath.com/2016/09/08/libtiff-offline/):

> It was located at remotesensing.org, a domain whose owner apparently was willing to host it without having any close connection to the project. The domain fell into someone else’s hands, and the content changed completely, breaking all links to Libtiff material.

> For the moment, there’s no primary source for Libtiff on the Web.

This affects two nix packages, `libtiff` and `libgeotiff`.

**Comment by rasendubi** [comment]
From remotesensing.org:

GeoTiff  is geotiff.osgeo.org
Libtiff is Libtiff.org

**Comment by rasendubi** [comment]
This one seems to be online and recent: http://libtiff.maptools.org/

**Comment by obadz** [comment]
http://download.osgeo.org/libtiff/ seems to work fine

**Comment by rasendubi** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/18611.
