### ISSUE TITLE
Add node.js to nixpkgs manual's "Support for specific programming languages" section

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#18609]
## Issue description
Right now, we have sections covering Perl, Python, Ruby, Go, and more. Node.js is another popular language and we have an easy/automated way to add new node.js packages to nixpkgs. We should make this easier for people who don't already know how!

I plan on tackling this based on instructions I received over at https://github.com/svanderburg/node2nix/issues/16

**Comment by domenkozar** [comment]
cc @svanderburg

**Comment by siddharthist** [comment]
Some of the entries in the document `doc/languages-frameworks/index.xml` have a comment like
```xml
<xi:include href="r.xml" /> <!-- generated from ../../pkgs/development/r-modules/README.md  -->
```
Should I enhance the README.md in `pkgs/development/node-packages` and then generate the XML file? Can anyone clue me in to how they're generated?

**Comment by ericsagnes** [comment]
> Can anyone clue me in to how they're generated?

They are generated in https://github.com/NixOS/nixpkgs/blob/master/doc/default.nix#L24-L66 (using pandoc).

**Comment by siddharthist** [comment]
Once I've added it to `doc/default.nix`, how can I actually generate the XML?
```gitdiff
diff --git a/doc/default.nix b/doc/default.nix
index f4f467b..03134cf 100644
--- a/doc/default.nix
+++ b/doc/default.nix
@@ -61,6 +61,10 @@ pkgs.stdenv.mkDerivation {
       outputFile = "languages-frameworks/idris.xml";
     }
   + toDocbook {
+      inputFile = ../pkgs/development/node-packages/README.md;
+      outputFile = "languages-frameworks/node.xml";
+    }
+  + toDocbook {
       inputFile = ../pkgs/development/r-modules/README.md;
       outputFile = "languages-frameworks/r.xml";
     }
```

**Comment by ericsagnes** [comment]
> Once I've added it to doc/default.nix, how can I actually generate the XML?

The XML is generated during the build. To have it in the manual you need to include it with `<xi:include href="node.xml" />` in `doc/languages-frameworks/index.xml`.

The confusing part is that `languages-frameworks/index.xml` refers some files that exists only at build-time (the files generated by `toDocBook`).

It is also possible to keep the build directory with `nix-build -K doc` to inspect the generated files.
