### ISSUE TITLE
DaVinci Resolve crashes

### ISSUE THREAD

**Issue by flexagoon** [NixOS/nixpkgs#186116]
### Describe the bug
Whenever I try to launch DaVinci Resolve, it crashes. Console logs are attached below.

### Steps To Reproduce
1. Install `davinci-resolve`
2. Run `davinci-resolve`

### Expected behavior
DaVinci Resolve runs

### Screenshots
![image](https://user-images.githubusercontent.com/66178592/184173528-c8cbba42-dec1-40e9-93ec-6f157face138.png)

![image](https://user-images.githubusercontent.com/66178592/184173293-66198b85-c3ea-4eff-9d30-a577bf46062a.png)

### Additional context

Console logs in text form:

```console
❯ davinci-resolve
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
17.4.3.0010 Linux/Clang x86_64
Main thread starts: 16033680
log4cxx: setFile(./logs/rollinglog.txt,true) call failed.
log4cxx: IO Exception : status code = 30
0x7fd616033680 | Undefined            | INFO  | 2022-08-11 18:40:14,436 | --------------------------------------------------------------------------------
log4cxx: No output stream or file set for the appender named [RollLogAppender].
0x7fd616033680 | Undefined            | INFO  | 2022-08-11 18:40:14,436 | Loaded log config from /home/flexagoon/.local/share/DaVinciResolve/configs/log-conf.xml
0x7fd616033680 | Undefined            | INFO  | 2022-08-11 18:40:14,436 | --------------------------------------------------------------------------------
```

### Notify maintainers
@jshcmpbll 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.15, NixOS, 22.11 (Raccoon), 22.11.20220731.5857574`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `""`
 - channels(flexagoon): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by brcha** [comment]
Could you include your ~/.local/share/DaVinciResolve/logs/ResolveDebug.txt file? I had the similar problem and it was fixed by correcting the QT_PLUGIN_PATH in davinci-resolve package. Perhaps your problem is related.

**Comment by flexagoon** [comment]
@brcha I can't, because I am no longer using NixOS. Should I close this issue?

**Comment by brcha** [comment]
@flexagoon I have no idea, probably better not to. I've made a pull request that fixed the issue for me, and the issue looked exactly like yours. When somebody reviews my PR, I'll ask them about closing this issue.

**Comment by kunihir0** [comment]
this issue persist
