### ISSUE TITLE
proxmox-backup-client packaging request

### ISSUE THREAD

**Issue by cofob** [NixOS/nixpkgs#186282]
**Project description**
Client for proxmox backup server written in Rust.

**Metadata**

* homepage URL: https://pbs.proxmox.com/
* source URL: https://git.proxmox.com/?p=proxmox-backup.git;a=summary
* license: aGPLv3.
* platforms: unix, linux

**Comment by cofob** [comment]
It would also be nice if added some sort of service that backups certain folders on a CRON timer to the server.

Like:
```nix
service.proxmox-backup.client = {
  enable = true;
  enableAutoBackup = true;
  on = "4:45";
  data = [
    {"path" = "/some/data"; "type" = "pxar"; "name" = "filename";}
  ];
};
```

**Comment by jojosch** [comment]
I have built a derivation for `proxmox-backup-client` in 2020 (but currently only at version `1.1.3`) that I'm using on some machines and my phone (via nix-on-droid). 

I'll see if I can update that derivation to the latest release and clean it up for inclusion in nixpkgs.

**Comment by cofob** [comment]
@jojosch any updates?

**Comment by averyanalex** [comment]
Hello, I packaged 2.2.1: https://git.frsqr.xyz/firesquare/nixos/src/branch/main/pkgs/proxmox-backup-client

**Comment by cofob** [comment]
> Hello, I packaged 2.2.1: https://git.frsqr.xyz/firesquare/nixos/src/branch/main/pkgs/proxmox-backup-client

I moved this version to PR, thanks.
