### ISSUE TITLE
Enable JNI for secp256k1

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18638]
To create a package bitcoinj, `secp256k1` needs to be compiled with JNI enabled.

To do this, we need to set the `--enable-jni` configure flag, and we also need to have the `JAVA_HOME` environment variable to some JDK when we run `autogen.sh`.

I'm not sure what's the best way to do this, since a JDK is a heavyweight dependency and not all users of secp256k1 will need it. Should there be a parameter on the package somehow to enable JNI, or two derivations?

**Comment by rasendubi** [comment]
Please, add a parameter (disabled by default). This way interested users can enable it with `secp256k1.override { enableJni = true; }`.

**Comment by Profpatsch** [comment]
(triage) any progress?
