### ISSUE TITLE
coreboot-toolchain missing pkgconfig and ncurses

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#186344]
I'm unable to start `make menuconfig` when in an environment with `coreboot-toolchain.x64`, because it tells me that ncurses and pkg-config are missing.

```
❯ make menuconfig
*
* Unable to find the ncurses package.
* Install ncurses (ncurses-devel or libncurses-dev
* depending on your distribution).
*
* You may also need to install pkg-config to find the
* ncurses installed in a non-default location.
*
make: *** [build/util/kconfig/Makefile.real:210: build/util/kconfig/mconf-cfg] Error 1
```

@felixsinger

**Comment by felixsinger** [comment]
These packages are not meant to be shipped with the toolchain package. The toolchain package just contains the output of util/crossgcc, which is the minimum requirement to compile coreboot itself.

Also, I don't recommend using the 64-bit toolchain except you know what you are doing. 64-bit support in coreboot is experimental. I recommend using i386.
