### ISSUE TITLE
Could `services.xserver.xkboptions` be a list not a string?

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#18646]
I have a dell as my personal latop, and a mac book pro for work, and I want to exchange option/command key only on the mbp. If this nixos option was a list which was then comma-separated, this would be trivial, since the module system would be able to combine `xkboptions` for me.

I'd make this change myself, but I'm a bit busy ATM.

**Comment by chris-martin** [comment]
It does seem like it ought to be a list - but it also seems pretty trivial regardless, since you can use `builtins.concatStringsSep ", "` to concat your list together.

**Comment by chris-martin** [comment]
There are also options to go even further...

    "grp:caps_toggle, grp_led:scroll"

    [
      "grp:caps_toggle"
      "grp_led:scroll"
    ]

    [
      [ "grp" "caps_toggle" ]
      [ "grp_led" "scroll" ]
    ]

    [
      { 
        symbol = "grp";
        key = "caps_toggle";
      }
      {
        symbol = "grp_led";
        key = "scroll";
      }
    ]

**Comment by Ericson2314** [comment]
@chris-martin well I mean with a list/object, the module system will transparently combine definitions in different modules, whereas with concatStringSep, one needs to route the data oneself.

Good idea going further. I like the second one as a compromise between structure and brevity.

**Comment by Profpatsch** [comment]
(triage) any progress?

**Comment by Ericson2314** [comment]
Nope, but I think it would still be good to have (though thankfully I no longer need to use a macos laptop!). It would be nice if we could tag things like this with some sort of "easy" / "first issue" tag, so they can have a positive role for community building, rather than just being yet another old issue needing triaging.
