### ISSUE TITLE
Create TLA+ packages

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18640]
I have the TLA+ [Toolbox](http://research.microsoft.com/en-us/um/people/lamport/tla/toolbox.html) and [TLAPS](https://tla.msr-inria.inria.fr/tlaps/content/Home.html) in Nix packages in my local config:
- https://github.com/chris-martin/home/tree/2015254b3e1b07643a602bf3366ae7aabfd6a410/nix/pkgs/tla-plus
- TLA+ requires a specific older version of Isabelle, 2011.1: https://github.com/chris-martin/home/tree/2015254b3e1b07643a602bf3366ae7aabfd6a410/nix/pkgs/isabelle2011-1

I'm planning to submit a PR at some point, but leaving this to-do item here in case somebody wants to get to this before I do.

**Comment by CMCDragonkai** [comment]
Since you already have it working, why no submit it as a package?

**Comment by Ralith** [comment]
Are you still planning on contributing this?

**Comment by Ekleog** [comment]
(triage) needs closing
