### ISSUE TITLE
Packaging request: Quarto

### ISSUE THREAD

**Issue by leonvonrabenmond** [NixOS/nixpkgs#186437]
**Project description**
Quarto® is an open-source scientific and technical publishing system built on [Pandoc](https://pandoc.org/)

**Metadata**

* homepage URL: https://quarto.org/
* source URL: https://github.com/quarto-dev/quarto-cli
* license: gpl2+
* platforms: unix, linux, darwin

**Comment by das-g** [comment]
Duplicate of #160911
