### ISSUE TITLE
Environment files: changes in files are not saved after system reboot

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nixpkgs#186420]
### Describe the bug
Some environments are not added to `/etc/set-environment` file

### Steps To Reproduce
1) Add to configuration:
```
  programs.ssh.startAgent = true;
```
or
```
  programs.gnupg.agent = {
    enable = true;
    pinentryFlavor = "tty";
    enableSSHSupport = true;
  };
2) Running command 'sudo nixos-rebuild switch'
3) Reboot system.
```

### Expected behavior
The following content is added to the `/etc/set-environment` file:
```
if [ -z "$SSH_AUTH_SOCK" -a -n "$XDG_RUNTIME_DIR" ]; then
  export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent"
fi
```
or
```
if [ -z "$SSH_AUTH_SOCK" ]; then
  export SSH_AUTH_SOCK=$(/nix/store/rwgxk8ayk7qadzlcx4pry4bq5pb81yxw-gnupg-2.3.6/bin/gpgconf --list-dirs agent-ssh-socket)
fi
```

### Current behavior
Only these variables are written:
```
...
# Wrappers override other bin directories.
export PATH="/run/wrappers/bin:$PATH"


unset ASPELL_CONF
for i in /run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/$USER $HOME/.nix-profile ; do
  if [ -d "$i/lib/aspell" ]; then
    export ASPELL_CONF="dict-dir $i/lib/aspell"
  fi
done

export NIX_USER_PROFILE_DIR="/nix/var/nix/profiles/per-user/$USER"
export NIX_PROFILES="/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/$USER $HOME/.nix-profile"
...
```

Before rebooting, `/etc/set-environment` contains lines with `SSH_AUTH_SOCK`. Disappears after reboot.

Similar behavior can be seen in this example:
```
  environment.etc."example".text = ''
    # Example test
  '';
```
File `/etc/example` will disappear after a reboot.

cc @SuperSandro2000 @andir @Kreyren

**Comment by Izorkin** [comment]
Error does not always reproduce.

**Comment by LunNova** [comment]
Are you sure you're booting into the right generation?

Might be running into one of the bugs where /boot fills up and adding new boot entries fails without being very obvious in the log. If that's it you can use `nix-collect-garbage` then switch again to free up space.

**Comment by Izorkin** [comment]
Yes, I forgot to mount the boot partition.
Thanks for the help.
