### ISSUE TITLE
gnat11 build fail

### ISSUE THREAD

**Issue by GenericNerdyUsername** [NixOS/nixpkgs#186482]
### Steps To Reproduce
1. `nix-shell -p gnat11`

### Build log
https://gist.github.com/GenericNerdyUsername/bfad5ec58d980163e20e2ecadf2da4e0

### Notify maintainers
@Synthetica9 @vcunat @Ericson2314 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.11 (Raccoon), 22.11.20220813.65c15b0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by vcunat** [comment]
I commented about that on https://github.com/NixOS/nixpkgs/pull/182414#issuecomment-1213005012

**Comment by GenericNerdyUsername** [comment]
#201637 fixes this
