### ISSUE TITLE
How do you generate libreoffice sources?

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18649]
I can't figure out how to run [`generate-libreoffice-srcs.sh`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/libreoffice/generate-libreoffice-srcs.sh).

There's a comment at the top that seems to be a hint, but I don't know what it means:

```
# Take the list of files from the main package, ooo.lst.in

# This script wants an argument: download list file
```

This is some very... advanced... bash for me, and I'm not making much progress trying to read the code. Should we consider rewriting this is something that might be easier to read?

cc @7c6f434c

**Comment by 7c6f434c** [comment]
>I can't figure out how to run [`generate-libreoffice-srcs.sh`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/libreoffice/generate-libreoffice-srcs.sh).

You get the source package, you unpack download.lst from the source
package, you pass the full path to download.lst as the only parameter to
the script, you redirect the output of the script to a .nix file.

>This is some very... advanced... bash for me, and I'm not making much progress trying to read the code. Should we consider rewriting this is something that might be easier to read?

Given that most such rewrites end up being rewrites into Perl, the 
result will not be necessarily easier to read.

download.lst doesn't have fully consistent format, so the code parsing
it doesn't really have an option of being straightforward…

**Comment by chris-martin** [comment]
> Given that most such rewrites end up being rewrites into Perl

I was probably going to suggest Python.

**Comment by domenkozar** [comment]
Note that we should change the script to not use md5. The upstream doesn't plan/want to move away from it, so it will be tedious for us a bit.

**Comment by chris-martin** [comment]
> to not use md5

(That's why I'm looking into this script, by the way.)

**Comment by chris-martin** [comment]
With #18682, the answer to this question should be clear now.
