### ISSUE TITLE
pyqt5 build on darwin-aarch64

### ISSUE THREAD

**Issue by tanshihaj** [NixOS/nixpkgs#186489]
### Steps To Reproduce
1. Get an computer with M1 or M1 Pro processor running macOS 12.1 (21C52).
2. Clone and checkout nixpkgs repo: `git clone https://github.com/NixOS/nixpkgs.git`
3. Try to build qt515.qtbase: `python3Packages.pyqt5`
4. Get an error when pip installs wheel.

### Build log
```shell
$ nix-build . -A python3Packages.pyqt5
...
Successfully built PyQt5
Finished creating a wheel...
Finished executing pipBuildPhase
buildPhase completed in 14 minutes 34 seconds
installing
Executing pipInstallPhase
/private/tmp/nix-build-python3.10-PyQt5-5.15.7.drv-1/PyQt5-5.15.7/dist /private/tmp/nix-build-python3.10-PyQt5-5.15.7.drv-1/PyQt5-5.15.7
ERROR: PyQt5-5.15.7-cp37-abi3-macosx_10_13_arm64.whl is not a supported wheel on this platform.
...
```

### Additional context
The main issue is name of the wheel `PyQt5-5.15.7-cp37-abi3-macosx_10_13_arm64.whl` which is not supported (?) by pip:
```shell
$ nix-shell -p python3Packages.pip --run "pip debug --verbose"
...
Compatible tags: 404
...
  cp37-abi3-macosx_12_0_arm64
  cp37-abi3-macosx_12_0_universal2
  cp37-abi3-macosx_11_0_arm64
  cp37-abi3-macosx_11_0_universal2
  cp37-abi3-macosx_10_16_universal2
  cp37-abi3-macosx_10_15_universal2
  cp37-abi3-macosx_10_14_universal2
  cp37-abi3-macosx_10_13_universal2
  cp37-abi3-macosx_10_12_universal2
  cp37-abi3-macosx_10_11_universal2
  cp37-abi3-macosx_10_10_universal2
  cp37-abi3-macosx_10_9_universal2
  cp37-abi3-macosx_10_8_universal2
  cp37-abi3-macosx_10_7_universal2
  cp37-abi3-macosx_10_6_universal2
  cp37-abi3-macosx_10_5_universal2
  cp37-abi3-macosx_10_4_universal2
...
```
Here what I discovered for now:
1. min macos sdk set by pyqt-builder (based on Qt version) is 10.13: https://www.riverbankcomputing.com/hg/PyQt-builder/file/068a418ac90b/pyqtbuild/builder.py#l127
2. this min macos sdk is passed to the sip, and sip using platform tag `macosx-11.0-arm64` calculate `macosx_10_13_arm64` as final target platform tag: https://www.riverbankcomputing.com/hg/sip/file/a3c9672f761a/sipbuild/project.py#l335. 
3. this platform tag with project name, Python version and ABI lead to `PyQt5-5.15.7-cp37-abi3-macosx_10_13_arm64.whl` wheel name as `python -m pip wheel ...` output.
4. but pip expects `universal2` arch for SDK version 10.13: https://github.com/pypa/pip/blob/dec279ecdf8fd2b0f984dd213198635fdbe320c7/src/pip/_vendor/packaging/tags.py#L313-L414

First I thought that issue in sip (since it generates tag incompatible with pip), but same sources without significant patches works on Homebrew and I don't understand why. That would be great if someone who understands how it should work help me with debug.

### Notify maintainers
@sander

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixpkgs"`
 - channels(zaripov-kamil): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by veprbl** [comment]
I guess pyqt 5.15 does not know about arm64. At the same time we don't usually build fat binaries in nixpkgs. A workaround in this case would be to rename the wheel to have an acceptable suffix.

**Comment by tpwrules** [comment]
FWIW sip doesn't seem to have a good understanding of wheel names. I went through a very similar issue for the Linux aarch64 wheels. There is no such thing as arm64 on macOS prior to 11 so I think the wheel should be renamed to `cp37-abi3-macosx_11_0_arm64`. But I'm not sure where to hook that in. I ended up patching sip itself but that's kind of an exhausting experience.

**Comment by tanshihaj** [comment]
Well, I know how to do it easily, but a bit ugly - add `minimum-macos-version = "11.0"` for aarch64-darwin in `pyproject.toml` somewhere here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pyqt/5.x.nix#L32-L46. Will prepare PR with changes.
