### ISSUE TITLE
kdiff3 lacks icons/themes

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#18655]
## Issue description

kdiff3 comes without access to kde icons
### Steps to reproduce

```
nix-shell '<nixpkgs>' --pure -p pkgs.kde4.kdiff3.out
kdiff3
```

opens the window with icons missing
## Technical details

```
$ nixos-version
16.09beta235.49c43db (Flounder)
$ nix-env --version
nix-env (Nix) 1.11.4
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09beta235.49c43db"
```
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by RonnyPfannschmidt** [comment]
this is still an issue in unstable, any fix in sight?

**Comment by RonnyPfannschmidt** [comment]
ever since i enabled plasma5 this works out, so i think there are system path elements missing for kdiff3 on its own

**Comment by globin** [comment]
cc @ttuegel

**Comment by mmahut** [comment]
This looks to be fixed.
