### ISSUE TITLE
bcrypt-3.2.0 not supported for interpreter python2.7

### ISSUE THREAD

**Issue by thecalcc** [NixOS/nixpkgs#186645]
After trying to install [syncthing-gtk](https://search.nixos.org/packages?channel=22.05&show=syncthing-gtk&from=0&size=50&sort=relevance&type=packages&query=syncthing) I reloaded my config with `sudo nixos-rebuild switch` and the following error showed. 
![image](https://user-images.githubusercontent.com/45574768/184536616-9c6bb56c-ef9a-471a-b935-1f7b9fe8062b.png)

Here is a version with `--show-trace` enabled. I'm guessing that there's a problem with the package itself but since I'm new to NixOS I thought I'd put this here. 

![image](https://user-images.githubusercontent.com/45574768/184536656-0feb89bd-2e58-408c-ad3c-4ffe792c9625.png)

**Comment by vojta001** [comment]
I am afraid there is no hope to get syncthing-gtk fixed. It was completely removed from nixpkgs in 100b75a44b2c30e1bfe9d034cf72c256b11a8a1c

**Comment by thecalcc** [comment]
> I am afraid there is no hope to get syncthing-gtk fixed. It was completely removed from nixpkgs in [100b75a](https://github.com/NixOS/nixpkgs/commit/100b75a44b2c30e1bfe9d034cf72c256b11a8a1c)

Thank you, didn't notice that in the repo
