### ISSUE TITLE
JupyterLab build fail

### ISSUE THREAD

**Issue by Wisehh** [NixOS/nixpkgs#186694]
### Steps To Reproduce

I have this in my home-manager config packages, and the build only fails if jupyterlab is uncommented.

```
    (python3.withPackages (packages: with packages; 
      [
        jupyterlab
        pandas
        numpy
        pycryptodome
      ])
    )
```

### Build log

[Logs](https://gist.github.com/Wisehh/52bc2c5320b4b69a573bec1c8c4275cc)

### Notify maintainers

@zimbatm 
@costrouc

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.11 (Raccoon), 22.11.20220729.2a93ea1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by smancill** [comment]
Looks like it's broken because of `nbclassic`:

https://hydra.nixos.org/job/nixpkgs/trunk/python310Packages.jupyterlab.x86_64-linux

Broken by https://github.com/NixOS/nixpkgs/pull/181620 in https://github.com/NixOS/nixpkgs/commit/91e79004d17eeb146ec7a66d3ff59ca795735cb6.

**Comment by smancill** [comment]
Already reported: https://github.com/NixOS/nixpkgs/issues/185028

**Comment by Wisehh** [comment]
> Already reported: https://github.com/NixOS/nixpkgs/issues/185028

Right, thanks for the info. So I close the issue.
