### ISSUE TITLE
libcaca built with only BMP support?

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#18683]
`man cacaview` says:

> cacaview can load the most widespread image formats: PNG, JPEG, GIF,
> PNG, BMP etc.

However, if I try to open a PNG image in `cacaview`, `cacaview` says:

> Error loading \<file\>. Only BMP is supported.

Looking at `pkgs/development/libraries/libcaca/default.nix`, it
doesn't look like any image format libraries are passed to it, and I'm
guessing that the BMP support is built in.

Why is `libcaca` built with only BMP support, if I'm correct in
guessing that it is?

**Comment by Mic92** [comment]
I suppose just nobody added this dependency.
You could expand this in a pull request.

**Comment by the-kenny** [comment]
Note that I reverted the change in `master` as it causes quite a big rebuild (thanks to `gstreamer`). It's in `staging` now and will hit `master` at some point. Feel free to reopen the issue until it's in `master`.

**Comment by 8573** [comment]
Okay, thanks.
