### ISSUE TITLE
Steam Tinker Launch

### ISSUE THREAD

**Issue by TheOddler** [NixOS/nixpkgs#186826]
**Project description**

Steam Tinker Launch is a Linux wrapper tool for use with the Steam client which allows customizing and start tools and options for games quickly on the fly (see [Features](https://github.com/frostworx/steamtinkerlaunch#Features))

**Metadata**

* homepage URL: https://github.com/frostworx/steamtinkerlaunch
* source URL: https://github.com/frostworx/steamtinkerlaunch
* license: GPL-3.0 
* platforms: linux

**Comment by SuperSamus** [comment]
I guess it's related to #73323 (partially, since it can also be used as launch command).

**Comment by TheOddler** [comment]
Yes true. You think we should merge these requests? Or is this different enough as it's also a launch command?
