### ISSUE TITLE
[Packaging Request]  system-monitoring-center

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#186969]
**Project description**
A Multi-featured system monitor

**Metadata**

* homepage/source URL: https://github.com/hakandundar34coding/system-monitoring-center
* license:  GPL-3.0
* platforms: linux

**Comment by Aleksanaa** [comment]
system-monitoring-center has been archived. If we cannot find another fork, we may not be able to continue packaging.
