### ISSUE TITLE
Biber fails to build with Perl 536 

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nixpkgs#186946]
### Steps To Reproduce
`perl5.36.0-biber-2.17` fails to build.
1. `nix build .#biber` in current Nixpkgs repository.

### Build log
[biber.log](https://github.com/NixOS/nixpkgs/files/9350677/biber.log)

### Additional context
Bug in Gentoo bug tracker: https://bugs.gentoo.org/850733
Upstream fix of biber: https://github.com/plk/biber/commit/d9e961710074d266ad6bdf395c98868d91952088.patch

### Notify maintainers
@ttuegel (but no gh user name?)

### Metadata

- Nixpkgs unstable small, commit hash `6c6409e965a6c883677be7b9d87a95fab6c3472e`
- x86 linux

**Comment by collares** [comment]
I submitted your proposed change as https://github.com/NixOS/nixpkgs/pull/187039. Thanks!
