### ISSUE TITLE
Make vendorSha256 or vendorHash optional in buildGoModule

### ISSUE THREAD

**Issue by bigzilla** [NixOS/nixpkgs#186910]
I kinda see why we need to specify the vendor hash, it's for validation purposes. But if we look at this [FAQ](https://github.com/golang/go/wiki/Modules#is-gosum-a-lock-file-why-does-gosum-include-information-for-module-versions-i-am-no-longer-using) from Go repository, `go.mod` provide enough information for 100% reproducible builds while `go.sum` provide expected cryptographic checksums for validation purposes.

So I propose to change `vendorSha256` or `vendorHash` in `buildGoModule` to **optional** (or even removed if possible) since it's unnecessary as `go.sum` already does the job.

**Reference code:**

https://github.com/NixOS/nixpkgs/blob/985524984f344a382519416f42f562eae165ddfb/pkgs/build-support/go/module.nix#L61-L62

**Comment by zowoq** [comment]
> it's for validation purposes.

It isn't for validation, it is the hash of the vendor tarball.

**Comment by bigzilla** [comment]
Isn't hash is for validation?

> It isn't for validation, it is the hash of the vendor tarball.

Isn't hash is used for validation?

**Comment by haraldh** [comment]
Yeah, this is strange. Coming from the rust world with `Cargo.lock` (and no vendorSha256 equivalent), I see `go.mod` and `go.sum` ... and still I have to correct `vendorSha256` in my flake.nix every time...

**Comment by squalus** [comment]
It would be nice to have an explanation on record of why the go.mod/go.sum files are insufficient.
