### ISSUE TITLE
[Packaging Request] QLC+

### ISSUE THREAD

**Issue by poelzi** [NixOS/nixpkgs#187049]
**Project description**
Q Light Controller Plus (QLC+) is a free and cross-platform software to control DMX or analog lighting systems like moving heads, dimmers, scanners etc. 

**Metadata**

* homepage URL: https://www.qlcplus.org
* source URL:https://github.com/mcallegari/qlcplus
* license: apache
* platforms: unix, linux, darwin, windows

**Comment by Aleksanaa** [comment]
This package already exists: [qlcplus](https://search.nixos.org/packages?channel=unstable&show=qlcplus&type=packages)
