### ISSUE TITLE
nixos/system/boot: disk partition temporary mounting leaked

### ISSUE THREAD

**Issue by penglei** [NixOS/nixpkgs#187072]
### Describe the bug

I want to install nixos to replace an existing debian system (In fact, it's a cloud vm).
The vm has only one storage device and partition(/dev/vda1) which mounted at `/`.
I downloaded the nixos iso file and stored it at `/nixos.iso`.
Then, I modified the existing grub configuration  by using the `findiso=/nixos.iso copytoram` options to boot a in-memory installer so that I could overwrite the /dev/vda1 partition to install nixos. 

However, after the installer runs, I found that the /dev/vda1 partition is busy, which prevents me from installing nixos on the /dev/vda1 partition that can't be formatted (interrupted by device is busy).

```
menuentry nixos-installer {
  set isopath="/nixos.iso"
  set stage2init="/nix/store/***********/init"   #### inspect iso to get stage2Init path

  search --fs-uuid --set=installer_root MY_DISK_UUID
  loopback loop ($installer_root)$isopath
  linux (loop)/boot/bzImage findiso=$isopath copytoram init=$stage2init boot.shell_on_fail loglevel=4
  initrd ($installer_root)/boot/nixos-initrd
}
```

**Comment by rnhmjoj** [comment]
Not relevant this problem, but note that if you have a working GNU/Linux installation and want to install NixOS you don't need the installer. The installer is useful if you have a empty disk, but from Debian you can easily install just Nix and the few tools needed to perform the installation.

I suggest you look at this [chapter](https://nixos.org/manual/nixos/stable/#sec-installing-from-other-distro) of the NixOS manual, search/highlight the term `NIXOS_LUSTRATE` and follow the instructions.

**Comment by penglei** [comment]
> 

Thanks for your suggestion. The key problem is that I don't have an empty disk, but I want to re-format the unique disk and install NixOS to replace the existing Linux(Debian).

**Comment by rnhmjoj** [comment]
> I don't have an empty disk, but I want to re-format

That's exactly what `NIXOS_LUSTRATE` is for.

**Comment by penglei** [comment]
> > I don't have an empty disk, but I want to re-format
> 
> That's exactly what `NIXOS_LUSTRATE` is for.

Wow!  I tried to install NixOS from an existing Linux via NIXOS_LUSTRATE config, the whole installing process went very well and easy.

**Comment by penglei** [comment]
This Issue is another problem: when findiso and copytoram are working together, stage-1-init should run an in-memory installer and should not continue to occupy the device where the file specified by findiso is located.
