### ISSUE TITLE
no package for powerDNS

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#18703]
## Issue description
I'd like to use powerDNS but there is no package.

https://www.powerdns.com/

I opened powerdns/pdns#4484 but they asked me to come here.

## Technical details

* System: 16.09beta250.feef017 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09beta250.feef017"

**Comment by aljones15** [comment]
How do I install power dns? I have been trying to include it in my configuration.nix but it doesn't seem to show up.

**Comment by fpletz** [comment]
@aljones15 There is `services.powerdns.enable` and `services.powerdns.extraConfig`. You can get more info on those by invoking `nixos-option` with one of them.

Note that powerdns is current only available on master/unstable and not in 16.09/stable.

**Comment by aljones15** [comment]
Yeah I tried all of that and just kind of assumed my current version is behind and he pkg isn't available for me. Ended up installig power dns on an ubuntu rig.

**Comment by nhooyr** [comment]
it's really easy to switch to the unstable channel. just do `nix-channel --remove nixos && nix-channel --add https://nixos.org/channels/nixos-unstable nixos && nix-channel --update`

**Comment by CMCDragonkai** [comment]
How does the service work with the pdns-recursor service? https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/pdns-recursor.nix

**Comment by vcunat** [comment]
Shameless advert: I don't know but I'm dedicated to maintenance of alternative `services.kresd.enable = true;` :-)

**Comment by CMCDragonkai** [comment]
PowerDNS can hook its resolution to kresd?

**Comment by vcunat** [comment]
Oh... @CMCDragonkai you want both authoritative DNS and recursor at once?  (Maybe we should move out of this thread?)

**Comment by CMCDragonkai** [comment]
Why not? ;-)

**Comment by vcunat** [comment]
It's not a problem, it just seems an unusual setup to have both on a single machine.  Note: modern implementations are typically separate for the auth. and recursor (possibly sharing some common code through a library).

**Comment by Mic92** [comment]
@CMCDragonkai you need to listen on a address (127.1.0.27 for instance) with one service.

**Comment by vcunat** [comment]
That's not enough by itself.  You need to "multiplex" between them in some way, as without inspecting the message you typically don't know if it's for one or the other.

**Comment by vcunat** [comment]
... and if you want to support TCP (kinda compulsory nowadays), doing this isn't that easy...

**Comment by CMCDragonkai** [comment]
It's not for production. Only experiments. I have read on the PDNS authoritative docs that it says that the authoritative server won't resolve hostnames outside its control. So I thought it would have a direct integration to pdns recursor considering they are from the same vendor .

**Comment by vcunat** [comment]
The venerable `bind` still can do both in one service; I haven't heard of direct support anywhere else, but I haven't really looked.  It's said nowadays almost noone does the combination.  (E.g. my employer operates both public recursor and authoritative DNS, but on disjoint IP sets.)

For testing it seems easiest to have them on a separate IP or port and let the client choose explicitly (if that fits your test case).

**Comment by aljones15** [comment]
Thanks for the response. I actually ended up doing it in ubuntu. Glad to know it will be available in the future.
