### ISSUE TITLE
rPackages.ExomeDepth 1.1.15 : error: expected ';' before 'extern' in mathcalls.h

### ISSUE THREAD

**Issue by apraga** [NixOS/nixpkgs#187113]
### Steps To Reproduce
1. nix build nixpkgs#rPackages.ExomeDepth

### Build log
https://gist.github.com/apraga/2b944b217226553759ae94379e13547e

### Additional context
What I don’t understand is that only the macro after `#if defined __USE_XOPEN_EXTENDED || defined __USE_ISOC99` fails, even though the syntax is similar. I’ve tried to compile with `-std=c11`, but to no avail.

### Notify maintainers
@jbedo 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.16.3-microsoft-standard-WSL2, Ubuntu, 20.04.4 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(apraga): `"nixpkgs"`
 - nixpkgs: `/home/apraga/.nix-defexpr/channels/nixpkgs`
```

**Comment by jbedo** [comment]
This is working in 22.05 so something in the toolchain has changed. Should be able to bisect this and figure it out.

**Comment by jbedo** [comment]
Well that took a while but it did isolate the issue to this commit:

```
commit 272fc53af162d1e4619d03987bc0701ec12d5df7
Author: Bernardo Meurer <bernardo@meurer.org>
Date:   Fri Jul 22 22:30:56 2022 -0700

    glibc: 2.34-210 -> 2.35-163
```

Looks like the package is not compatible with glibc 2.35.

**Comment by apraga** [comment]
Thanks for the quick answer.
So the update did not triggered a new build of ExomeDepth ?
Also, is there a way to patch this ?

**Comment by jbedo** [comment]
We don't build rPackages regularly, only on the r-updates branch which hasn't had a bump for a while now. Need to look further into it and see if upstream are aware.

**Comment by apraga** [comment]
@jbedo  Did you have time to look into this issue ? It does not seem to be solved on my end. Thanks !

**Comment by jbedo** [comment]
This seems to be fixed in ExomeDepth 1.1.16, which will be part of nixpkgs once we bump R to 4.2.2 (and pull in the latest CRAN). In the meantime you can override ExomeDepth and point it to the 1.1.16 source tarball.

**Comment by abathur** [comment]
Closing since the update to 1.1.16 was added in #206157 which has been available in unstable for a while and should also be present in the 23.05 as soon as it's officially released.

Happy to reopen if I'm mistaken. @apraga are you able to confirm?

**Comment by apraga** [comment]
With latest unstable, it does compile. Thanks @abathur .
