### ISSUE TITLE
A PAE processor need to be declared for the VirtualBox application

### ISSUE THREAD

**Issue by dufresnep** [NixOS/nixpkgs#1871]
(Now about 3 days) Yesterday I downloaded nixos-13.10.35663.bc3f4f3-i686-linux Open Virtualization Format Archive, but it did not start. The error message stated that it had to be stopped because trying to enable PAE over a virtual processor that does not have this feature.

Fixing it was as easy as marking the processor as a PAE/NX processor in the configuration. But I believed it would be better if the shipped OVF archive would have it already set that way.

I am using VirtualBox 4.3.8 (downloaded yesterday too).

**Comment by Profpatsch** [comment]
(triage) has this been fixed?

**Comment by Profpatsch** [comment]
No response, so close @zimbatm.

**Comment by domenkozar** [comment]
Now that 32bit ova is not generated anymore this is really not relevant.
