### ISSUE TITLE
Snipe-IT: barcode generation fails due to missing directory

### ISSUE THREAD

**Issue by jhackenberg** [NixOS/nixpkgs#187179]
### Describe the bug
Snipe-IT needs the directory public/uploads/barcodes/ in order to generate barcodes and QR codes for asset labels. This directory should be created during installation, but isn't. Creating this directory manually fixes the problem.

### Steps To Reproduce
1. Setup a Snipe-IT instance.
2. Add an asset.
3. Generate an asset label. 

### Expected behavior
The directory (public/uploads/barcodes/) should exist and have the same content as in the Snipe-IT GitHub repository.

### Notify maintainers

@yayayayaka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.88, NixOS, 22.05 (Quokka), 22.05.2473.cfabaa15e98`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05-small"`
 - channels(helmholtzschule): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by yayayayaka** [comment]
Thanks for the report! I will open a PR in the morning.
