### ISSUE TITLE
polkit does not work as nativeBuildInput for embedded cross-compiling

### ISSUE THREAD

**Issue by sbruder** [NixOS/nixpkgs#187109]
### Describe the bug

When polkit (or a package depending on polkit) is added to `nativeBuildInputs` in a derivation that is compiled for an embedded system like `arm-none-eabi`, it fails with this error:

    error: Don't know how to run arm-none-eabi executables.

### Steps To Reproduce

Evaluate/instantiate the following expression:

```nix
{ pkgs ? import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/archive/a1bc7b4dbe4f0f979d810e71b40e1ab6c1768d33.zip") { crossSystem.config = "arm-none-eabi"; } }:

pkgs.callPackage ({ stdenv, polkit }: stdenv.mkDerivation {
  name = "has-native-polkit-dependency";
  nativeBuildInputs = [ polkit ];
}) { }
```

### Expected behavior

While above expression should not build, it should evaluate/instantiate. Because polkit (or a package depending on it) is only added to `nativeBuildInputs`, it should not try to run on `arm-none-eabi`.

### Additional context

This happened when I tried to package the [nitrokey-fido2-firmware](https://github.com/Nitrokey/nitrokey-fido2-firmware), which requires [a recent version of pynitrokey](https://github.com/NixOS/nixpkgs/pull/183099) as a build dependency. That has the following dependency chain: pynitrokey → nrfutil → pc-ble-driver → systemd → libfido2 → pcsclite → polkit → gobject-introspection.

gobject-introspection’s wrapper [references `targetPlatform`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gobject-introspection/wrapper.nix#L27), which in this case is `arm-none-eabi`, because it itself is included in `buildInputs`.

I could successfully build the firmware after I removed `gobject-introspection` from `buildInputs` of polkit. Can this be applied to nixpkgs or does polkit require `gobject-introspection` at run-time?

### Notify maintainers

@Artturin (added this in #177538)
@NixOS/freedesktop (polkit maintainers)
@NixOS/gnome @lovek323 @Artturin (gobject-introspection maintainers)

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.05 (Quokka), 22.05.20220814.8791216`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/l03wjzqnr81273fx3hbcj38p9a66jifn-source`

**Comment by Atemu** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/192808
