### ISSUE TITLE
X logs are discarded

### ISSUE THREAD

**Issue by Ralith** [NixOS/nixpkgs#18716]
## Issue description

As of @edolstra's commit d84741a4bfb6ed2531ec7154479c147d2c9a737c X is configured to log to `/dev/null`. Contrary to the claims in the commit message, `journalctl -u display-manager` does not contain any logs from X. It's not clear why this isn't working properly, since the Xorg(1) manpage supports the idea that `-verbose 3` should cause log output to show up on stderr.

### Steps to reproduce

Run `journalctl -u display-manager`, observe absence of X logs.

## Technical details

* System: 17.03.git.2b0eace (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre91207.2b0eace

**Comment by Mic92** [comment]
Seems to work with Slim as a display manager.

**Comment by Ralith** [comment]
I'm using `sddm`, if that's relevant.

**Comment by vcunat** [comment]
I believe this is https://github.com/NixOS/nixpkgs/issues/18034. Reopen otherwise.
