### ISSUE TITLE
Packaging request: Gridcoinresearch

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#187264]
**Project description**
Gridcoin is an open source cyptocurrency that rewards volunteer computing for science through the BOINC platform.

**Metadata**

* homepage URL: https://gridcoin.us/
* source URL: https://github.com/gridcoin-community/Gridcoin-Research
* license: mit
* platforms: linux, darwin

**Comment by tpdcl** [comment]
They also have packages for other distros at the bottom of the page.

**Comment by GiggleSquid** [comment]
pr #242002
