### ISSUE TITLE
no package for YAZ toolkit (library)

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#18721]
## Issue description

There is no package for the YAZ library.

> YAZ is a programmers’ toolkit supporting the development of Z39.50/SRW/SRU clients and servers.

[http://www.indexdata.com/yaz](http://www.indexdata.com/yaz)
### Prerequisites

`nix-shell -p stdenv libiconv libxslt libxml2 icu` seems to be sufficient.
Acquire source from github ([https://github.com/indexdata/yaz](https://github.com/indexdata/yaz)) or their website.
### Steps to Compile

See http://www.indexdata.com/yaz/doc/installation.unix.html#installation.source.unix

```
./configure
make
```

seems sufficient, but I am not familiar with the library.

**Comment by Profpatsch** [comment]
I’ll close, it will be added by someone once they need it.
