### ISSUE TITLE
no package for BiblioteQ

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#18722]
## Issue description

There is no package for BiblioteQ .

> BiblioteQ strives to be a professional cataloging and library management suite, utilizing a Qt interface and providing connectivity to PostgreSQL and SQLite. The SRU and Z39.50 protocols are used for retrieving data for books, journals, and magazines. The software is available for all major operating systems and should be compatible with any system that supports Qt. BiblioteQ is distributed under a BSD license.

[https://textbrowser.github.io/biblioteq/index.html](https://textbrowser.github.io/biblioteq/index.html)
### Prerequisites

> Some dependencies are as follows: Qt 4.8.x or Qt 5.x, and YAZ 4.x or YAZ 5.x. PostgreSQL 8.x, PostgreSQL 9.x, and SQLite 3.x are supported database engines. - [https://textbrowser.github.io/biblioteq/download.html](https://textbrowser.github.io/biblioteq/download.html)

YAZ #18721
### Steps to Compile

Clone [https://github.com/textbrowser/biblioteq](https://github.com/textbrowser/biblioteq)
Acquire a supported version of Qt. 
nix-shell -p qt5.qtbase seems to be sufficient. (+ YAZ)

(See Documentation/COMPILING)

```
qmake -o Makefile "INCPATH+=\"../yaz/yaz-5.16.0/pref/include\"" "LIBS+=\"-L../yaz/yaz-5.16.0/pref/lib\"" biblioteq.qt5.pro
make
```

This is the way I got it to compile.
Someone more familiar with QMake probably knows if there's a better way to do that.
Of course this complains about not being able to find the YAZ library when I run because of dynamic linking and not setting stuff up, but this is just to illustrate.

**Comment by Profpatsch** [comment]
Closing, it will be added once a contributor needs it.
