### ISSUE TITLE
Emacs Cleanup

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#18720]
## Issue description

While packaging `emacs-25.1` I noticed that we still keep the old (deprecated) emacs package sets (`emacs25Packages`) around. 

I think that now is the right time to get rid of the deprecated `emacs25packages` along with a cleanup of the emacs packaging in `all-packages.nix` (note that I still refer to `emacs25` in these comments):
- [ ] Remove all instances of `emacs25Packages` and `emacsPackages`
- [ ] Rename `emacsPackagesNg` and `emacs25PackagesNg` to `emacsPackages` and `emacs25Packages`
- [x] Rename the `emacs-24` folder to just `emacs` (drop the version-extension)

Additionally:
- [ ] Adapt consistent naming scheme for `emacs25Macport_24_5`
- [ ] Get rid of `emacs25Packages` and `emacs25` completely in favor of just `emacsPackages` and `emacs`? (as we don't need to keep `emacs25` around)
- [ ] Introduce `emacs_humongous` (similar to `vim_humongous`) with all (even unstable) features enabled

**Comment by joachifm** [comment]
Is this related to https://github.com/NixOS/nixpkgs/issues/11503?

**Comment by periklis** [comment]
fyi, i've added support for emacs25macport, #18363. I've already put it under emacs/macport-25.1.nix.

**Comment by jagajaga** [comment]
cc @oxij

**Comment by adisbladis** [comment]
I have a PR addressing most of these points: https://github.com/NixOS/nixpkgs/pull/66301

**Comment by adisbladis** [comment]
The only outstanding thing here is 
> Introduce emacs_humongous (similar to vim_humongous) with all (even unstable) features enabled

Which I do not plan to address at this time.
