### ISSUE TITLE
bpftools requires configured+working `linuxPackages_latest.kernel` to build

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#187330]
If `linuxPackages_latest.kernel` is broken, bpftools fails to build.

### Steps To Reproduce
1. Use an out-of-tree kernel driver "mydriver" compatible with `linuxPackages_one` or older.
2. Specify mydriver and linuxPackages_one in `configuration.nix`.
3. Add `bpftools` to `environment.systemPackages` in `configuration.nix`.
4. Wait for linuxPackages_latest reference move from linuxPackages_one => linuxPackages_two
5. `bpftools` fails to build b/c mydriver cannot be built linuxPackages_two (yet). As a result the whole system configuration fails to build.

### Additional context
Looks like there are two approaches:

* make bpftools build against `config.boot.kernelPackages`, same as e.g. perf or bpftrace
* make bpftools build against a clean `linuxPackages_latest` that doesn't take any customization into account.

### Notify maintainers
@thoughtpolice 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.16, NixOS, 22.05 (Quokka), 22.05.2512.a82127cea64`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by alyssais** [comment]
bpftools was decoupled from linux_latest in f12d2f016b6.
