### ISSUE TITLE
rathole

### ISSUE THREAD

**Issue by Abdillah** [NixOS/nixpkgs#187346]
**Project description**
 A lightweight and high-performance reverse proxy for NAT traversal, written in Rust. An alternative to frp and ngrok. 

**Metadata**

* homepage URL: https://github.com/rapiz1/rathole
* source URL: https://github.com/rapiz1/rathole/archive/refs/tags/v0.4.3.tar.gz
* license: asl20 ( Apache-2.0 license )
* platforms: linux

**Comment by ajs124** [comment]
see #185388

**Comment by Abdillah** [comment]
Ah.. thanks, I was going to make one.
