### ISSUE TITLE
NSS patch 'nss-3.15.4-pem-support-20140109.patch.xz' URL is a 404

### ISSUE THREAD

**Issue by rb2k** [NixOS/nixpkgs#187314]
### Steps To Reproduce

1. build nss on basically any branch

### Build log
```
  trying http://dev.gentoo.org/~polynomial-c/mozilla/nss-3.15.4-pem-support-20140109.patch.xz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   357  100   357    0     0    816      0 --:--:-- --:--:-- --:--:--   815
    0   261    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  curl: (22) The requested URL returned error: 404
  error: cannot download nss-3.15.4-pem-support-20140109.patch.xz from any mirror
```

### Additional context

It's from here: https://github.com/NixOS/nixpkgs/blob/0608bffda6cd018075afc7ec73a2c97bd23ae31f/pkgs/development/libraries/nss/generic.nix#L23

http://dev.gentoo.org/~polynomial-c/mozilla/nss-3.15.4-pem-support-20140109.patch.xz seems to be indeed dead.
Couldn't quickly find a mirror using google

### Notify maintainers
@mweinelt 
@ajs124

**Comment by mweinelt** [comment]
I propose we follow other distros and drop this patch entirely in favor of nss-pem (https://github.com/kdudka/nss-pem). Nothing should depend on this patched in functionality in NSS.

**Comment by rb2k** [comment]
For a quick fix, it's still available in:

https://web.archive.org/web/20210305023555/http://dev.gentoo.org/~polynomial-c/mozilla/nss-3.15.4-pem-support-20140109.patch.xz

**Comment by mweinelt** [comment]
Nope, we're dropping it #187357.

**Comment by rb2k** [comment]
> Nope, we're dropping it #187357.

Sweet. Any idea how far this would be backported (if at all)?

**Comment by fzakaria** [comment]
Right -- basically every nixpkg stable build that existed before now cannot be built from source since this thing 404s...
The web archive should be backported?

NSS is such an early dependency for the whole graph of nixpkg this should be fixed I think?

**Comment by SuperSandro2000** [comment]
You should be able to to download the file from web.archive.org and add it with ``nix store add-file``.

```
wget https://web.archive.org/web/20210305023555/http://dev.gentoo.org/~polynomial-c/mozilla/nss-3.15.4-pem-support-20140109.patch.xz
nix store add-file nss-3.15.4-pem-support-20140109.patch.xz
```

**Comment by fzakaria** [comment]
We have a CICD setup with our own private cache... so I guess I have to add
something to it.

I know nix store can do that but I don't have the signing keys...
I am trying to just cherry-pick that change for now and do the rebuild.

Farid Zakaria

**Comment by mweinelt** [comment]
> > Nope, we're dropping it #187357.
> 
> Sweet. Any idea how far something like this would be backported (if at all)?

Backported into staging-22.05 just now, sorry I forgot. Will take a few days to get into release-22.05.

**Comment by raboof** [comment]
with https://github.com/NixOS/nixpkgs/pull/187357 (and the backport in https://github.com/NixOS/nixpkgs/pull/187930) merged I'm pretty sure this can be closed - feel free to reopen if I'm mistaken :)
