### ISSUE TITLE
install-grub.pl fails when / is tmpfs

### ISSUE THREAD

**Issue by Baitinq** [NixOS/nixpkgs#187361]
### Describe the bug
I'm attempting to migrate my root onto a tmpfs. When rebuilding the system, the system errors when switching configurations and the grub boot menu doesn't get properly updated. The exact error is:

```
Failed to get blkid info (returned 512) for / on none at /nix/store/...-install-grub.pl line 205.
```

### Steps To Reproduce
1. Setup / as tmpfs
2. Install grub in efi mode (not sure if it happens as well in legacy mode)

### Expected behavior
Grub installs succesfully

EDIT: My mistake. I had grub attempting to install efi at /boot/efi and itself at /boot, when /boot was part of the tmpfs, and hence obviously couldnt logically install itself there.

Duplicate of #94210

**Comment by buckley310** [comment]
Can you share more information about your configuration? I am using grub EFI with tmpfs-as-root successfully.

**Comment by Baitinq** [comment]
@buckley310 It was my mistake, I have edited the original issue.
