### ISSUE TITLE
gh: /usr/bin/gh: No such file or directory

### ISSUE THREAD

**Issue by riceicetea** [NixOS/nixpkgs#187463]
### Describe the bug
GitHub no longer allows cloning a private repo over HTTPS with a simple password auth:

https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls 

Therefore, one may try to use the `gh` official cli tool, which is packaged. This fails.

### Steps To Reproduce
1. `nix-shell -p gh`
2. `gh auth login`, choose `GitHub.com`, `HTTPS` git mode, `web browser` login and authorize
3. Try to clone a repo with `gh repo clone secret` (where `secret` is the repo name)
4. Throws:
```console
$ gh repo clone secret
Cloning into 'secret'...
/usr/bin/gh auth git-credential get: line 1: /usr/bin/gh: No such file or directory
```

### Expected behavior
The gh tool clones the repository.

### Notify maintainers

@zowoq 

### Additional info
This only seems to happen when choosing `HTTPS` as the git method during the authorization. SSH works fine.
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.05 (Quokka), 22.05.2307.72f492e275f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by zowoq** [comment]
Please post your `.gitconfig`.

**Comment by riceicetea** [comment]
Oh yeah, thanks. My `.gitconfig` was left over from a previous non-Nix installation with the whole home directory. SSH worked because the nix-packaged `gh` wrote it, HTTPS didn't because I used that earlier.

Thanks for the help.
