### ISSUE TITLE
vim-go in neovim doesn't work anymore

### ISSUE THREAD

**Issue by halturin** [NixOS/nixpkgs#187465]
### Describe the bug

I'm using neovim with vim-go plugin, and now it has become unusable. simple shortcut ctrl-] doesn't go to the term definition as I expected. At the same time, it does work with manually running GoDecls.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.2, NixOS, 22.11 (Raccoon), 22.11pre401467
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(taras): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by teto** [comment]
still relevant ?

**Comment by halturin** [comment]
I've made a workaround and didn't check these changes yet. I'll take a look. Thanks for the update.

**Comment by qbit** [comment]
This is working for me, IMO this can be closed.
