### ISSUE TITLE
GNU Screen + Sshd Artifacts

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#187597]
### Describe the bug
I don't know of a word to describe the issue/glitch occurring, so I am uploading a video to demonstrate. I will refer to these misplaced and left over screen characters as "artifacts". 

Artifacts are appearing on the screen when using the combination of GNU Screen+SSH (see video below).

### Steps To Reproduce
1. Boot the 22.05 iso
2. Set a root password. `sudo passwd root`
3. Login to the machine from another pc/device. `ssh root@machineip`
4. Run: screen
5. Set minimal shell prompt. `PS1="\w "`
6. Clear the terminal: `reset`
7. Enter gnu screen copy mode ctrl+a [
8. Start selecting text on the screen: spacebar

### Expected behavior
When replicating these conditions with other distros, like Debian, these screen artifacts do not appear.
https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current-live/amd64/iso-hybrid/debian-live-11.4.0-amd64-standard+nonfree.iso

### Screenshots
https://user-images.githubusercontent.com/1575546/185747929-ba4ec570-5ef2-42f9-b262-ef8777b6f348.mp4

### Additional context
I also tested this this issue against zsh and nushell, and it persists. So I eliminate bash as the source of issue.

I also tested this issue against Termux, Connectbot, and Mate Terminal, and it persists. So I eliminate the terminal emulator as the source of the issue.

I also tested this issue by using Tmux instead of GNU Screen, and did Not experience Artifacts. So we might eliminate Sshd as the source of the issue.

My suspicion is that the issue appears to be with in the NixOS build of GNU Screen, and not Sshd.

**Comment by Sepero** [comment]
This issue persists on installation also. Both stable and unstable NixOS.

**Comment by Artturin** [comment]
try this overlay

```
  nixpkgs.overlays = [
    (self: super: {
      screen = super.screen.overrideAttrs (oldAttrs: rec {
        configureFlags = oldAttrs.configureFlags ++ [ "--enable-rxvt_osc" ];
      });
    })
  ];
```

**Comment by Artturin** [comment]
i merged the pr anyways even if it does not fix this

**Comment by Artturin** [comment]
reopen this if the fix didn't work

**Comment by Sepero** [comment]
Apologizes for my late response. I will try it and report back. Thank you 👍🏻

**Comment by Sepero** [comment]
Added and nixos-rebuild boot&& reboot

Unfortunately, the fix didn't work. No apparent difference

**Comment by cleverca22** [comment]
the above overlay does not fix it on my end either

**Comment by Sepero** [comment]
I just upgraded to 23.05, and happy to report that the issue appears to be resolved. Things are looking very nice now
