### ISSUE TITLE
Postgis doesn't build: attribute version missing

### ISSUE THREAD

**Issue by ElessarWebb** [NixOS/nixpkgs#18762]
## Issue description

Trying to include `pkgs.postgis.v_2_2_1` as extraPlugins for `services.postgresql` in a configuration for nixops, deploying from darwin to a virtualbox results in:

```
error: attribute ‘version’ missing, at /nix/store/3gwj4sm07yfzjyn7qj99f5n9xcqb2qmm-nixpkgs-16.09beta264.aadcffc/nixpkgs/pkgs/development/libraries/postgis/default.nix:36:17
```

Building the same configuration, against the same version of nixpkgs _on linux_ builds fine, strangely enough.
### Steps to reproduce

Deploy a nixos configuration that includes 

```
      services.postgresql = {
        enable = true;
    extraPlugins = [ pkgs.postgis.v_2_2_1 ];
        package = pkgs.postgresql;
     }
```

from darwin to a vbox target.
## Technical details
- System: OSX
- Nixpkgs version: 16.09beta264.aadcffc

**Comment by domenkozar** [comment]
I don't know, but for sure it's making it hard to say if it is.

**Comment by ElessarWebb** [comment]
Agreed. I can try and get rid of composableDerivation in this particular instance (postgis) and I'll submit a PR for that.

**Comment by Profpatsch** [comment]
(triage) I’ll close, since I assume this has been fixed in the meantime. Feel free to reopen.
