### ISSUE TITLE
No doublequotes around attribute name in NixOS module errors

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#18764]
## Issue description

(moved from https://github.com/NixOS/nix/issues/1065)

I've got this error when trying to configure nginx module.

```
building all machine configurations...
error: The option `services.nginx.virtualHosts.content.defenders.com./' defined in `/home/deployer/testing/fleet/test.nix' does not exist.
(use ‘--show-trace’ to show detailed location information)
```

I think, this warning should include double-quotes around `content.defenders.com` and `/`
### Steps to reproduce

Make some errorneous nginx config

```
    services.nginx.enable = true;
    services.nginx.virtualHosts."content.defenders.com"."/" = "/";
```
## Technical details
- Nixpkgs and nixos version: https://github.com/NixOS/nixpkgs/archive/c47eb4a43a9ab338c26b6b05d59ad0cb90507ed1.tar.gz

**Comment by Profpatsch** [comment]
iirc the quoting issue was fixed.
