### ISSUE TITLE
How to document abandoned packages?

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#18766]
## Issue description
I noticed recently [on the ArchWiki](https://wiki.archlinux.org/index.php/SLiM) that [SLiM](https://github.com/NixOS/nixpkgs/blob/f94a806c4a91af4ef403b8202129eabfa47cba46/pkgs/applications/display-managers/slim/default.nix) has been abandoned. I was wondering how we should document this, if at all?

## Technical details

* System: 17.03.git.8d8f57d (Gorilla)

**Comment by vcunat** [comment]
SLiM: we've had quite some discussions around https://github.com/NixOS/nixpkgs/pull/12690. It's still our default `displayManager`.

Packages that are abandoned *and don't work well* should probably be removed. I don't think any documentation is really needed.

**Comment by siddharthist** [comment]
@vcunat Sounds good!
