### ISSUE TITLE
Duplicate desktop items for prusa-slicer

### ISSUE THREAD

**Issue by A-Walrus** [NixOS/nixpkgs#187604]
### Describe the bug
The prusa-slicer package has duplicate desktop files

### Steps To Reproduce
1. Install `prusa-slicer` package
2. Notice there are duplicate icons in menus
3. 

### Expected behavior
There should only be one of each desktop file: Gcode viewer and slicer. Instead there are two of each.

### Screenshots
![image](https://user-images.githubusercontent.com/58790821/185749797-9b94475f-cd80-42cc-aa2b-7a6d6cb0ebf0.png)

### Additional context
```
/nix/store/gf80b3hykw31mkf08kndf52nq2z8swy0-prusa-slicer-2.4.2/share/applications $ ls
prusa-gcodeviewer.desktop  PrusaGcodeviewer.desktop  prusa-slicer.desktop  PrusaSlicer.desktop
```

### Notify maintainers
@Moredread 
@thorstenweber83

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.05 (Quokka), 22.05.2568.9b9f4bb4e11`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(guy): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 06kellyjac** [comment]
Looks like we can drop our generated desktop items in favor of the defaults

https://github.com/prusa3d/PrusaSlicer/tree/master/src/platform/unix

They dont need patching either since it's not using absolute paths
