### ISSUE TITLE
Output indices

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#18760]
We currently have a rather painful process to build `command-not-found` support and other things. I was thinking that we could hack the generic `mkDerivation` definition to add a magic `outputIndex` output to every derivation that records in a very simple textual format the contents of `bin` and maybe `lib`. Then `command-not-found` would only pull the `outputIndex` outputs and get a few hundred bytes instead of possibly dozens of megabytes.

It would be nice to index language-specific libraries but I think we can probably get the majority of benefit this way.

This seems fairly easy to add to `mkDerivation`, so I'm really just looking for feedback before making a PR of it.

cc @edolstra @domenkozar @shlevy

**Comment by copumpkin** [comment]
It might pay to make a few aspects of it overridable, so that people can suppress annoying binaries from the index for packages that have a ton of annoyingly named stuff, or binaries in unexpected locations, or only want to advertise a handful of standard things.

**Comment by shlevy** [comment]
Yes please! And definitely with some overriding framework.

**Comment by domenkozar** [comment]
+1, I assume `store-paths.xz` includes all build time outputs, so we don't need to depend on any of these magic `outputIndex`.

**Comment by domenkozar** [comment]
Just for reference, I already proposed that in https://github.com/NixOS/nixos-channel-scripts/issues/4#issuecomment-191226825, so the next step is to implement a protoype. 

Go @copumpkin

**Comment by copumpkin** [comment]
@domenkozar sweet!

@vcunat btw, you can press "subscribe" on the sidebar for a similar effect

**Comment by vcunat** [comment]
@copumpkin: I *am* subscribed to the whole repo. Someone once suggested to me to unsubscribe and subscibe again, but that didn't work for me to change the "participating" status. I use https://github.com/notifications/participating

**Comment by copumpkin** [comment]
Oh okay, makes sense

**Comment by edolstra** [comment]
Sorry, I fail to see the advantage here. Why is it easier to have a `outputIndex` output (which could be incorrect, missing, etc), rather than have the index generator simply list the *actual* contents of the package?

**Comment by copumpkin** [comment]
Way smaller thing to download?

**Comment by edolstra** [comment]
Well, the solution to that would be to have hydra-queue-runner upload an index to S3. E.g. for each `<foo>.nar` also upload `<foo>.narindex`.

**Comment by shlevy** [comment]
Why would that help? Then you can't use command-not-found etc.

**Comment by edolstra** [comment]
@shlevy I don't follow... The index generator would just download `<foo>.narindex` instead of `<foo>.nar`

**Comment by shlevy** [comment]
Oh, I see, I thought the narindex files were replacing the generator

**Comment by copumpkin** [comment]
@shlevy @edolstra not sure I understand. What would be the interface to the .narindex files? With a separate output, I know how to write a script that indexes arbitrary things inside derivations. Can someone walk through how I'd consume a .narindex in a command-not-found or similar?

Happy to close this if it's already covered, but I don't think many people understand the alternate path.

**Comment by copumpkin** [comment]
Can anyone elaborate on how narindex files will work? Should I just close this ticket?

**Comment by edolstra** [comment]
Currently, the program that generates `programs.sqlite` fetches the NAR of every store path in the release from cache.nixos.org to enumerate the files inside it (see <a href="https://github.com/NixOS/nixos-channel-scripts/blob/master/generate-programs-index.cc#L191-L211">here</a>). This is kind of slow (though it does cache the results per store path locally).

So instead `hydra-queue-runner` could upload a small file describing the contents of the store path (`foo.narindex`) along with the NAR. Then `generate-programs-index` could download the `.narindex` files instead.

**Comment by bennofs** [comment]
@copumpkin `command-not-found` is broken due to https://github.com/NixOS/nixos-channel-scripts/issues/13, it used to work before that change I believe. 

Hydra currently generates a `{.ls,.ls.xz}` file for each `nar` that it pushes to the cache, so you can simply fetch all those files to generate the db. This is also how `generate-programs-index.cc` is implemented. I don't see how this solution would be better.

**Comment by baracoder** [comment]
(triage) as I understand, there is an alternative solution using `.ls` files in place and there are no updates since 2017. I think this issue can be closed.
