### ISSUE TITLE
qmmp is outdated

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#187725]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: `1.4.4`
desired version: `2.1.1`

###### Notify maintainers

maintainers: @bjornfor 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by bjornfor** [comment]
Thanks for the notification. PRs welcome.

**Comment by bjornfor** [comment]
Does nixpkgs have qt6 yet? If not we should apparently upgrade to 1.6, not 2.x: http://qmmp.ylsoftware.com/downloads.php

**Comment by SamLukeYes** [comment]
> Does nixpkgs have qt6 yet?

Yes, we have. At least `tdesktop` has already migrated to qt6 AFAIK.

**Comment by NickCao** [comment]
https://github.com/NixOS/nixpkgs/blob/60c84c8841fb3eef80f28e942a52b601625ed0c0/pkgs/applications/audio/qmmp/default.nix#L29
