### ISSUE TITLE
[Packaging Request] nextcloud-client-nautilus

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#187774]
**Project description**
Nautilus plugin for Nextcloud client integration

**Metadata**

* homepage/source URL: https://github.com/nextcloud/desktop
* license: gpl2
* platforms: linux

**Comment by Stunkymonkey** [comment]
So the goal you want to have are the green check-marks, ... for nextcloud?
When using gnome this works automatically.
I am using sway with this config and it works as well: https://github.com/Stunkymonkey/nixos/blob/master/nixos/modules/nautilus.nix
Please report if this config solves your issue.

**Comment by IceDBorn** [comment]
@Stunkymonkey You can share a file's link too

**Comment by Stunkymonkey** [comment]
you mean this:?
![Screenshot-2022-08-23_173604](https://user-images.githubusercontent.com/1315818/186200808-dc3ce2d3-1363-4799-9a89-fb535251e315.png)

**Comment by IceDBorn** [comment]
@Stunkymonkey I copied your configuration and I'm not getting the nextcloud context item, nor the green check marks.

**Comment by langfingaz** [comment]
Hi, not sure if I should open a new issue. But I have the same problem: The Nextcloud client integration in Nautilus is not working. I have `nextcloud-client` and `gnome.nautilus-python` (Nautilus python extension API) installed on NixOS.

The file `/nix/store/wv61npymx8qz4c2521a3zhx1m83bg45v-nextcloud-client-3.8.2/share/nautilus-python/extensions/syncstate-Nextcloud.py` is part of the package `nextcloud-client`, so the Nautilus extension is there. But maybe in the wrong place?

**Comment by langfingaz** [comment]
They further pointed me to the `NAUTILUS_4_EXTENSION_DIR`:

https://github.com/NixOS/nixpkgs/blob/5a6cd93cb5b9a0e1c60a823cd51496395b7b9f1b/nixos/modules/services/x11/desktop-managers/gnome.nix#L516

**Comment by Stunkymonkey** [comment]
@langfingaz please have a look at my own workaround-module: https://github.com/Stunkymonkey/nixos/blob/master/profiles/nautilus/default.nix

**Comment by langfingaz** [comment]
> @langfingaz please have a look at my own workaround-module: https://github.com/Stunkymonkey/nixos/blob/master/profiles/nautilus/default.nix

Many thanks for sharing this @Stunkymonkey! However, after adding the following lines from your config to mine, the nextcloud-client integration is still not working for me:

```nix
    environment.sessionVariables.NAUTILUS_4_EXTENSION_DIR = "${config.system.path}/lib/nautilus/extensions-4";
    environment.pathsToLink = [
      "/share/nautilus-python/extensions"
    ];
```

I don't quite understand these two lines. I thought, that the second one would create a symlink at `/run/current-system/sw/share/nautilus-python/extensions`, but on my system this is just an empty folder:

```shell
stat /run/current-system/sw/share/nautilus-python/extensions
```
```
  File: /run/current-system/sw/share/nautilus-python/extensions
  Size: 0         	Blocks: 0          IO Block: 4096   directory
Device: 0,29	Inode: 2768760     Links: 1
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-05 14:33:42.751447432 +0200
Modify: 1970-01-01 01:00:01.000000000 +0100
Change: 2023-09-05 14:33:42.255447738 +0200
 Birth: 2023-09-05 14:33:40.822448608 +0200
```

And as I am using the GNOME desktop, I think that your first line has no effect for me as this is set in a GNOME related nix file already:

https://github.com/NixOS/nixpkgs/blob/5a6cd93cb5b9a0e1c60a823cd51496395b7b9f1b/nixos/modules/services/x11/desktop-managers/gnome.nix#L516

**Comment by bjornfor** [comment]
Seems fixed, closing.

(I also got Nextcloud integration in Nautilus working with [this snippet](https://github.com/NixOS/nixpkgs/issues/187774#issuecomment-1710347602), on top of a NixOS/GNOME setup. Thanks!)
