### ISSUE TITLE
teamspeak3 selectors missing

### ISSUE THREAD

**Issue by goetzst** [NixOS/nixpkgs#18772]
## Issue description
It seems that the nix selectors for the teamspeak client and sever have gone missing.

### Steps to reproduce
(~/workspace/nixpkgs is the upstream master of NixOS/nixpkgs)
nix-env -f ~/workspace/nixpkgs -u teamspeak_client (judging from pkgs/top-level/all-packages this should be the selector)
error: selector ‘teamspeak_client’ matches no derivations

nix-env -f ~/workspace/nixpkgs -qaP --description '*' | grep teamspeak
no output

same results when using channels/nixos-unstable

output when using channels//nixos-16.03:
nix-env -qaP --description '*' | grep teamspeak
nixos.teamspeak_client  teamspeak-client-3.0.18.2 The TeamSpeak voice communication too

## Technical details

* System: 16.09pre88185.52a875f (Flounder)
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: "17.03pre91382.642a428"/"16.03.1299.a8e0739"

**Comment by rasendubi** [comment]
Selector is package's name, which is `teamspeak-client`.

`teamspeak_client` is attribute path. If you want to pass that, to nix-env, add `-A` option:
```
nix-env -f . -uA teamspeak_client
```

I see teamspeak is present in the master:
```
rasen@ashmalko ~/nixpkgs> nix-env -f . -qaP --description '*' | grep teamspeak
teamspeak_client                                          teamspeak-client-3.0.19.4                                                     The TeamSpeak voice communication tool
teamspeak_server                                          teamspeak-server-3.0.12.4                                                     TeamSpeak voice communication server
```

**Comment by goetzst** [comment]
thanks for the insight, I did try using teamspeak-client too. The used grep command also should not care wether it is written with a _ or -. Which led me to belive that the query didn't return teamspeak in the first place.
After some more mindless trying of some comands I finaly got an error regarding the licence of teamSpeak3. For 16.09+ it is listed as an unfree package.
So adding allowUnfree = true; to my config solved the problem.
