### ISSUE TITLE
Can't get Zink working

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#187791]
### Describe the bug
As seen in #122147 Zink can be built as part of Mesa now. Right now, as far as I can tell, Zink is *not* built by default? If it is, then that's something else to note.

Basically, `zink_dri.so` don't appear in `/run/opengl-driver/lib/dri/`, even when I override mesa IE
`mesa = pkgs.mesa.override { galliumDrivers = [ "zink" "r600" "swrast" "nouveau" "i915" "iris" ]; };` and then install it.

### Steps To Reproduce
1. Attempt to add Zink to system
2. Nix recognizes the change and rebuilds Mesa from the ground up
3. Zink is not actually enabled.

### Expected behavior
`zink_dri.so` should appear and be usable to the system

### Screenshots

![Screenshot from 2022-08-21 17-15-15](https://user-images.githubusercontent.com/3945538/185811221-0ef33824-75f8-4228-a22a-d1a9e94cb273.png)

![Screenshot from 2022-08-21 17-15-56](https://user-images.githubusercontent.com/3945538/185811227-b200b95c-5a41-4921-aa5f-027143aab700.png)

https://github.com/Krutonium/My_Unified_NixOS_Config/blob/3265f9f736da0f2597e37f12da04ab8285683233/desktops/gnome.nix#L3-L6

### Notify maintainers

@primeos  https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix#L10553
@vcunat https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix#L13669
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/mesa/default.nix#L278

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.14-zen1, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(krutonium): `""`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by vcunat** [comment]
`systemPackages` have no influence on `/run/opengl-driver*`.  In past I've used `hardware.opengl.package = myMesa;` (and `.package32` variant), but I'm not sure if that's the best way (anymore).

**Comment by Krutonium** [comment]
Okay so I tried that, and while it did change the contents, it still doesn't work. 
Giving it `  mesa = pkgs.mesa.override { galliumDrivers = [ "zink" "r600" "swrast" "nouveau" "i915" "iris" "auto" ]; };` and setting `hardware.opengl.package = mesa` (and the same for 32 bit) Leaves me with only these:
![Screenshot from 2022-08-21 18-46-08](https://user-images.githubusercontent.com/3945538/185814013-781d564c-f7e5-4add-a3f6-622a92e2837f.png)

**Comment by Krutonium** [comment]
@veprbl I'm not entirely sure Hardware covers this, because it's technically an OpenGL-on-Vulkan layer similar in idea to DXVK, even though it is part of Mesa.

**Comment by veprbl** [comment]
> @veprbl I'm not entirely sure Hardware covers this, because it's technically an OpenGL-on-Vulkan layer similar in idea to DXVK, even though it is part of Mesa.

Most of the actionable hardware-related issues for NixOS are about composing the high-level components.

**Comment by Krutonium** [comment]
Fair enough! 👍

**Comment by LunNova** [comment]
Add `ln -s -t $drivers/lib/ ${pkgs.vulkan-loader}/lib/lib*` to mesa's `postInstall` + these args (add intel if you need that):

```
        galliumDrivers = [ "zink" "radeonsi" "swrast" ];
```

Launch an app with `MESA_LOADER_DRIVER_OVERRIDE=zink` and it will try to run with zink.

![image](https://user-images.githubusercontent.com/782440/196084811-3068b27d-1603-4313-b9d1-a3981ea3f67f.png)

Adding links to the vulkan libs to mesa is not the right fix. I'm not sure what needs fixed to get zink to use the right search path.

**Comment by Krutonium** [comment]
@LunNova I copied what you used in your config, but I'm getting an error when it builds about not being able to find `glslangValidator` - Which so far as I can tell, should exist (base package has it) and I even tried explicitly adding it *again* in my .nix file, but I'm having no luck. Did you do something I've missed?

https://gitea.krutonium.ca/Krutonium/My_Unified_NixOS_Config/src/commit/248734090c052297a35cdbab4d5416b8c78d7185/desktops/gnome.nix#L4-L21

**Comment by LunNova** [comment]
Does the version of mesa you're overriding in stable have it as an input yet? You probably need to add pkgs.glslang to nativeBuildInputs in your override.

**Comment by Krutonium** [comment]
> Does the version of mesa you're overriding in stable have it as an input yet? You probably need to add pkgs.glslang to nativeBuildInputs in your override.

So I've sorted that out but my issue is that, of all things, `libsecret` is failing to build with a zink enabled mesa.

**Comment by LunNova** [comment]
I recommend not using an overlay for mesa, there are way too many rebuilds.

Set `hardware.opengl.package/32` specifically instead and you will only have to rebuild mesa.

**Comment by Krutonium** [comment]
> I recommend not using an overlay for mesa, there are way too many rebuilds.
> 
> Set `hardware.opengl.package/32` specifically instead and you will only have to rebuild mesa.

When I tried that, GDM and Gnome decided to no longer function. :(

**Comment by surfaceflinger** [comment]
`zink_dri.so` is now available for me, but doing `MESA_LOADER_DRIVER_OVERRIDE=zink glxinfo` results with

```
name of display: :0
libGL error: glx: failed to create drisw screen
libGL error: failed to load driver: zink
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  60
  Current serial number in output stream:  61
```

**Comment by m911t** [comment]
also happens here on intel

**Comment by kanashimia** [comment]
@surfaceflinger @L911P https://github.com/NixOS/nixpkgs/pull/224857 should fix this, please test if you can

**Comment by surfaceflinger** [comment]
> @surfaceflinger @L911P #224857 should fix this, please test if you can

Can't test PR because it's impossible for me to rebuild so many derivations but I tested with

```
LD_LIBRARY_PATH=$(nix eval --raw nixpkgs#vulkan-loader)/lib:$LD_LIBRARY_PATH MESA_LOADER_DRIVER_OVERRIDE=zink glxinfo
```

like it was suggested in #150398 and it's indeed working ❤️ 

Would it be possible for someone to get your PR to rebuild together with mesa 23? Not sure how it exactly works but it seems to me that it'll take some time before your change is live 😕

**Comment by kanashimia** [comment]
@surfaceflinger 
```nix
{ pkgs, ... }: {
  nixpkgs.overlays = [(final: prev: {
    mesa-fix = let
      nixpkgs-fix = builtins.fetchTarball {
        url = "https://github.com/nixos/nixpkgs/tarball/19be5ac0119740b050ddcfd8608691ebf65abf9e";
        sha256 = "0z38lf6gq8ciq5nlw9ziryi9j9klhwzz2xims10pgcwllbn3acw7";
      };
    in (import nixpkgs-fix { inherit (pkgs) system; }).mesa;
  } )];
  hardware.opengl = {
    package = pkgs.mesa-fix.drivers;
    package32 = pkgs.pkgsi686Linux.mesa-fix.drivers;
  };
}
```

You can test it with something like this, basically you don't have to rebuild all of the packages that depend on mesa, just the system one.
