### ISSUE TITLE
[Packaging Request] nautilus-image-converter

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#187772]
**Project description**
Nautilus extension to rotate/resize image files

**Metadata**

* homepage/source URL: https://git.gnome.org/browse/nautilus-image-converter
* license: gpl3
* platforms: linux

**Comment by jtojnar** [comment]
That project is no longer maintained, the source URL is dead due to being moved to https://gitlab.gnome.org/Archive/nautilus-image-converter.

**Comment by IceDBorn** [comment]
I'm closing this issue then.

**Comment by Thatoo** [comment]
It is again maintained and alive : https://gitlab.gnome.org/coreyberla/nautilus-image-converter
I opened a new issue here https://github.com/NixOS/nixpkgs/issues/298732
