### ISSUE TITLE
Webcord

### ISSUE THREAD

**Issue by nilnail** [NixOS/nixpkgs#187766]
**Project description**
_describe the project a little_
A Discord and Fosscord(https://fosscord.com/) client implemented directly without [Discord API]. Made with the Electron framework.
**Metadata**

* homepage URL: https://github.com/SpacingBat3/WebCord
* source URL: https://github.com/SpacingBat3/WebCord
* license: mit
* platforms: unix, linux, darwin,

**Comment by figsoda** [comment]
duplicate of #183061
