### ISSUE TITLE
ruby packages installed in system env step on each other

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#18778]
## Issue description

Installing 2 packages (bundler and fpm as examples) based on `bundlerEnv` using `environment.systemPackages` causes collisions:

```
collision between `/nix/store/3f7pwjkb60jad1ybfj4nn5iz5z3s2521-fpm-1.6.2/lib/ruby/gems/2.3.1/gems/bundler-1.13.1/man/bundle.ronn' and `/nix/store/mm3j1v194vlis0w4dm3g6ri1rcnb9lb6-bundler-1.13.1/lib/ruby/gems/2.3.1/gems/bundler-1.13.1/man/bundle.ronn'
collision between `/nix/store/3f7pwjkb60jad1ybfj4nn5iz5z3s2521-fpm-1.6.2/lib/ruby/gems/2.3.1/gems/bundler-1.13.1/man/gemfile.5.ronn' and `/nix/store/mm3j1v194vlis0w4dm3g6ri1rcnb9lb6-bundler-1.13.1/lib/ruby/gems/2.3.1/gems/bundler-1.13.1/man/gemfile.5.ronn'
collision between `/nix/store/3f7pwjkb60jad1ybfj4nn5iz5z3s2521-fpm-1.6.2/lib/ruby/gems/2.3.1/gems/bundler-1.13.1/man/index.txt' and `/nix/store/mm3j1v194vlis0w4dm3g6ri1rcnb9lb6-bundler-1.13.1/lib/ruby/gems/2.3.1/gems/bundler-1.13.1/man/index.txt'
```
### Steps to reproduce

Contents of `ruby.nix`:

``` nix
{ pkgs, ... }:

{
  nix.useSandbox = true;

  boot = {
    kernelPackages = pkgs.linuxPackages_4_6;
  };

  environment.systemPackages = with pkgs; [
    bundler
    fpm
  ];

  users = {
    mutableUsers = false;

    extraUsers = {
      root = {
        password = "root";
      };
    };
  };
}
```

Then run

``` shell
nixos-rebuild build-vm -I nixos-config=./ruby.nix
```

Cc: @cstrahan @svanderburg 
## Technical details
- NixOS: 17.03.git.6ee876aM (Gorilla)
- Nix: nix-env (Nix) 1.11.4
- nixpkgs: 16.09pre89269.8512747

**Comment by FRidh** [comment]
cc @zimbatm

**Comment by nicknovitski** [comment]
I'm experiencing this when trying to install any two `bundlerEnv` packages with `nix-env -i` (or one that way and one in `systemPackages`).

**Comment by zimbatm** [comment]
By default bundlerEnv installs all the listed gems bins into it's output derivation. If the bundlerEnv uses `pname` instead, then the version is derived from the gemset.nix and only that gem's binaries are exposed. I expect some issues for gems who have runtime dependencies but most of them should be ok like that.

**Comment by zimbatm** [comment]
My bad that's another issue actually, it looks like the gem dependencies themselves are clashing.

**Comment by nicknovitski** [comment]
Maybe I should have added, I actually tested having one or both of the packages use `pname`, but since I didn't notice, I assumed it wasn't material.

**Comment by zimbatm** [comment]
Weird, I can't reproduce the issue on the nixos-16.09 channel.
