### ISSUE TITLE
It'd be nice to update the Jetbrains suite to 2022.2

### ISSUE THREAD

**Issue by patflynn** [NixOS/nixpkgs#187881]
###### Checklist

- [ x ] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: Jetbrains versions

there are lots of different IDEs, mostly on the same version with some slight variations.
current version: 2022.1.3
desired version: 2022.2.1

###### Notify maintainers

maintainers:  @Olliroxx @fabianhjr 

###### Note for maintainers

I just need IJ Ultimate, so I started putting together a PR, then noticed that I needed all the darwin entries and I'm not quite sure how I'm supposed to test this at the end of it. 
https://github.com/patflynn/nixpkgs/blob/update-intellij/pkgs/applications/editors/jetbrains/versions.json

Please tag this issue in your PR.

**Comment by fabianhjr** [comment]
There is a script to update the versions (`pkgs/applications/editors/jetbrains/update.py`)

Will open a PR as requested

**Comment by GenericNerdyUsername** [comment]
#186976 got merged, time to close the issue?

**Comment by patflynn** [comment]
will do thanks. how long does it usually take to show up in stable?

**Comment by GenericNerdyUsername** [comment]
no idea, i use unstable. I dont think its a breaking change, so it wouldn't be too difficult to backport yourself
