### ISSUE TITLE
Spock-api-ghcjs doesn’t find ghcjs-base

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#18789]
```
Configuring Spock-api-ghcjs-0.11.0.0...
Setup: At least the following dependencies are missing:
ghcjs-base -any
```

``` nix
  "Spock-api-ghcjs" = callPackage
    ({ mkDerivation, aeson, base, bytestring, ghcjs-base, hvect
     , Spock-api, text
     }:
     mkDerivation {
       pname = "Spock-api-ghcjs";
       version = "0.11.0.0";
       sha256 = "d533e4e76c50e8120675d0bbe1c7dd8d6909a4c7455cf0eea2ee75b7d868518c";
       libraryHaskellDepends = [
         aeson base bytestring ghcjs-base hvect Spock-api text
       ];
       jailbreak = true;
       homepage = "https://www.spock.li";
       description = "Another Haskell web framework for rapid development";
       license = stdenv.lib.licenses.bsd3;
       # broken = true;
     }) {ghcjs-base = null;};
```

Note that it’s marked broken by default.
There’s one other package that wants `ghcjs-base`, `fwgl-javascript`, and it’s also marked as broken. That package has the same problem.

**Comment by Profpatsch** [comment]
Update: I just saw that the last line sets `ghcjs-base = null`, which would explain where the missing package comes from. But when you remove it, the error changes to

    error: attribute ‘ghcjs’ missing, at …/nixpkgs/pkgs/development/haskell-modules/configuration-ghcjs.nix:133:16

**Comment by Profpatsch** [comment]
Oh, `ghcjs` was missing because of an other failed experiment of mine. When you remove the null, it builds.

The question is: where and why is it added?

**Comment by Profpatsch** [comment]
Okay, if you build non-ghcjs the package is missing and it throws an error. So this needs a redesign. What speaks against modeling the backends after how nixpkgs itself deals with architectures? Some derivations work for everything, some only for a subset.

**Comment by peti** [comment]
Is anyone working on this issue? Is this ticket still needed for anything?

**Comment by Profpatsch** [comment]
It probably is; I’ve been using a stale (patched) version for my ghcjs project, since keeping up-to-date with the ghcjs packages was a drag.
But the packages are probably still broken on master.

**Comment by peti** [comment]
@Profpatsch, do you feel that keeping this ticket -- which nobody works on -- open helps improve the situation?
