### ISSUE TITLE
Neovim nix tree-sitter grammar doesn't work

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#187834]
### Describe the bug
Nix grammar isn't working, there is no highlighting at all.

### Steps To Reproduce
Open a .nix file in neovim

### Additional context
Inside :checkhealth
```
  - ERROR: nix(highlights): ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 268
    nix(highlights) is concatenated from the following files:
    | [ERROR]:"/nix/store/7chxpc59yrihgwz7h5ghg5kqyaz3s0b1-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/nix/highlights.scm", failed to load: ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 268
  - ERROR: nix(locals): ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 16
    nix(locals) is concatenated from the following files:
    | [ERROR]:"/nix/store/7chxpc59yrihgwz7h5ghg5kqyaz3s0b1-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/nix/locals.scm", failed to load: ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 16
  - ERROR: nix(folds): ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 86
```

### Notify maintainers
 @Profpatsch @oxalica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60-xanmod1, NixOS, 22.11 (Raccoon), 22.11pre402057.13711c9ab9f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"home-manager, nixos"`
 - channels(quantmint): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by 06kellyjac** [comment]
Since this is an [upstream](https://github.com/cstrahan/tree-sitter-nix) problem I will close this in nixpkgs

tracked by: https://github.com/cstrahan/tree-sitter-nix/issues/27

**Comment by QuantMint** [comment]
@06kellyjac I don't think that this is and upstream problem.
Installing the nix grammar with, `:TSinstall nix` works.

**Comment by 06kellyjac** [comment]
upstream tree-sitter-nix, not nvim-treesitter or tree-sitter/tree-sitter

The error you post is essentially identical to the error in that issue, I'm still not convinced this is an issue with how nixpkgs is packaging tree-sitter-nix

What version of `nvim-treesitter` are you using and what version of the grammar did it grab?
