### ISSUE TITLE
tea: dependencies include unlicensed code

### ISSUE THREAD

**Issue by vielmetti** [NixOS/nixpkgs#187890]
### Describe the bug

The "tea" package, a CLI for "gitea", included code in a dependency
which does not have a proper license. Subsequent versions of that
dependency update the license (MIT).

Once all the dust settles, "tea" should be updated.

### Steps To Reproduce

1. Review https://artemis.sh/2022/08/21/this-program-is-illegally-packaged-in-14-distributions.html
2. Review https://github.com/seletskiy/godiff/issues/4
3. Review https://gitea.com/gitea/tea/pulls/4934. 
4. Review https://gitlab.alpinelinux.org/alpine/aports/-/issues/141295. 

Observe that the deficiency was mostly an oversight and that the
license was promptly updated once it was brought to the author's attention.

### Expected behavior

All code in nixpkgs has a proper license which reflects the intent of the authors.

### Additional context

This was presented with a lot of drama, but looks relatively easy to fix.

### Notify maintainers

attn @j4m3s-s

**Comment by 360ied** [comment]
This has since been resolved: https://github.com/seletskiy/godiff/commit/865648740d705a24a9cf927dfa73f458322141d9

**Comment by 6543** [comment]
upstream got fixed :tada: 

... I guess best is to release next tea version soon

**Comment by j4m3s-s** [comment]
I think everything has been merged and fix so I'll close the issue. Thanks again for bringing it up!
