### ISSUE TITLE
"Inappropriate ioctl for device while reading flags on /var/empty" when /var/empty is on tmpfs

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#18781]
`chattr` during system activation fails if /var/empty is on a tmpfs (e.g. in my case because / is a tmpfs).

**Comment by dezgeg** [comment]
I noticed the same when booting the installer one day.

Test log: http://hydra.nixos.org/build/40849093/log/raw

**Comment by groxxda** [comment]
Ref: https://github.com/NixOS/nixpkgs/pull/18365#issuecomment-245023354

**Comment by domenkozar** [comment]
At the end, having `/var/empty` as a symlink to nix store wasn't such a bad idea.

Should we just skip immutability guarantee if tmpfs is used?

**Comment by domenkozar** [comment]
@shlevy this doesn't break anything right, you just see the error during activation?

**Comment by shlevy** [comment]
Right

**Comment by shlevy** [comment]
I kind of like the zero-size tmpfs at /var/empty though :smile:

**Comment by domenkozar** [comment]
What we could do is `mount -t tmpfs -o size=1,nr_inodes=1 none /var/empty` instead of immutability. That would yield misleading errors for /var/empty though.

**Comment by edolstra** [comment]
Why not just do `chattr ... || true`? Let's not overengineer this...

**Comment by shlevy** [comment]
chattr 2>/dev/null || true please :smile:

**Comment by edolstra** [comment]
Yeah :-)

**Comment by domenkozar** [comment]
@edolstra https://github.com/NixOS/nixpkgs/pull/18365#commitcomment-19100105

Any objections going back to a symlink to empty nix store folder? It's going to work without these filesystem hiccups.

**Comment by edolstra** [comment]
Well, that depends on the Nix store being immutable, which is not necessarily the case. Also files in the Nix store can be owned by the `nixbld` group.

**Comment by domenkozar** [comment]
Fixed
