### ISSUE TITLE
"nixos-rebuild build-vm-with-bootloader" fails

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#18783]
'build-vm-with-bootloader' fails. 'build-vm' works.
### Steps to reproduce

```
$ nixos-rebuild -I nixpkgs=. -I nixos-config=configuration.nix build-vm-with-bootloader
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/zzbjpxcfxrnzihkkdqghdm3ywfrwzg9b-nixos-boot-disk.drv
  /nix/store/6gxp4bflsaqavb493p9wg8wsjl6clqxl-run-nixos-vm.drv
  /nix/store/488cakp8gq6p59289bn4a3ilsxq73y1z-nixos-vm.drv
building path(s) ‘/nix/store/x98r4wi5iyvh4aaxl49d6kxw5nmqsc4z-nixos-boot-disk’
Formatting '/nix/store/x98r4wi5iyvh4aaxl49d6kxw5nmqsc4z-nixos-boot-disk/disk.img', fmt=qcow2 size=41943040 encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
QEMU 2.6.1 monitor - type 'help' for more information
(qemu) char device redirected to /dev/pts/0 (label serial0)
builder for ‘/nix/store/zzbjpxcfxrnzihkkdqghdm3ywfrwzg9b-nixos-boot-disk.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/6gxp4bflsaqavb493p9wg8wsjl6clqxl-run-nixos-vm.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/488cakp8gq6p59289bn4a3ilsxq73y1z-nixos-vm.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/488cakp8gq6p59289bn4a3ilsxq73y1z-nixos-vm.drv’ failed

```

configuration.nix:

```
{ config, lib, pkgs, ... }:

{ # empty config
}
```

At first I thought it was just poor error handling due to missing boot.loader config or something. But the same error happens when I using my regular/working configuration.nix file.
## Technical details
- System: NixOS 16.09
- Nix version: 1.11.4
- Nixpkgs version: 62606be9b07e11b59fad35113a9a22627fc15e1b (master branch as of today), also tested on NixOS 16.03/16.09/unstable

**Comment by bjornfor** [comment]
If also fails for me on NixOS 16.03.

**Comment by lbonn** [comment]
It seems to fail on this line:

https://github.com/NixOS/nixpkgs/blob/c311871a6d0a3f83a0cec3e6b8804a741b83dcb5/nixos/modules/virtualisation/qemu-vm.nix#L147

I traced it with trial and error by inserting some `return 0`. If someone knows a better way to debug `runInLinuxVM` invocations, I'd be glad to know about it.

**Comment by globin** [comment]
@edolstra, @ts468

**Comment by ts468** [comment]
Thanks, I'll have a look!

**Comment by ts468** [comment]
Should be fixed in master: https://github.com/NixOS/nixpkgs/commit/0a8d9779c5b3bce15b252bb0f31c94744107ecf6

@globin: Maybe you want to cherry-pick it into 17.03?

@lbonn: For debugging the VM it might help to remove "-nographic" in https://github.com/NixOS/nixpkgs/blob/0a8d9779c5b3bce15b252bb0f31c94744107ecf6/nixos/modules/virtualisation/qemu-vm.nix#L136

**Comment by ts468** [comment]
@globin: I leave the issue open until the fix is confirmed and cherry-picked into 17.03.

**Comment by ts468** [comment]
@globin: Please cherry-pick that one as well: https://github.com/NixOS/nixpkgs/commit/b9a7aacef71671bdeffdc7c4f21e3b25cb3d4a5a

**Comment by bjornfor** [comment]
Confirmed that it works on release-17.03.

**Comment by globin** [comment]
Thanks btw, made it possible for me to fix memtest easily as I don't have a grub on my system. :)

**Comment by bjornfor** [comment]
Yeah, thanks for fixing this!
