### ISSUE TITLE
collision when creating an env with liblapack and openblas

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#187875]
### Steps To Reproduce

I am trying to create a docker image with both openblas and liblapack but they collide. 
Shouldn't openblas refer to liblapack libraries directly ? I dont know these 2 libraries much so looking for the maintainer's feedback.

I've dropped this file "test.nix" in my nixpkgs checkout (a fork of unstable a7855f2235a1876f97473a76151fec2afa02b287)
```
with import ./. {};

buildEnv {
  name = "test";
  paths = [
    openblas
    liblapack
  ];
}
```
then build it
```
$ nix-build test.nix   
this derivation will be built:
  /nix/store/v91bpfdirz41pk5iawn97m4vss0ksjf2-test.drv
this path will be fetched (2.61 MiB download, 11.49 MiB unpacked):
  /nix/store/dpb9w4hjaqnnladvfmpxbxdr17szxpz9-liblapack-3.10.1
copying path '/nix/store/dpb9w4hjaqnnladvfmpxbxdr17szxpz9-liblapack-3.10.1' from 'https://cache.nixos.org'...
building '/nix/store/v91bpfdirz41pk5iawn97m4vss0ksjf2-test.drv'...
error: collision between `/nix/store/dpb9w4hjaqnnladvfmpxbxdr17szxpz9-liblapack-3.10.1/lib/liblapack.so.3' and `/nix/store/x1k3di4axjkq4jiy32k16s57867254rq-openblas-0.3.20/lib/liblapack.so.3'
note: keeping build directory '/tmp/nix-build-test.drv-0'
error: builder for '/nix/store/v91bpfdirz41pk5iawn97m4vss0ksjf2-test.drv' failed with exit code 25;
       last 1 log lines:
       > error: collision between `/nix/store/dpb9w4hjaqnnladvfmpxbxdr17szxpz9-liblapack-3.10.1/lib/liblapack.so.3' and `/nix/store/x1k3di4axjkq4jiy32k16s57867254rq-openblas-0.3.20/lib/liblapack.so.3'
       For full logs, run 'nix log /nix/store/v91bpfdirz41pk5iawn97m4vss0ksjf2-test.drv'.
```

**Comment by teto** [comment]
cc @ttuegel @markuskowa

**Comment by markuskowa** [comment]
This is not surprising to me that there is a collision. `openblas` and `liblapack` both their own implementation of `liblapack.so`. Putting both in an environment directly thus will not work. In principle, you only need one of them.

If you want to build a package against different implementations, I would recommend taking a look at the override mechanism: https://nixos.org/manual/nixpkgs/stable/#sec-overlays-alternatives-blas-lapack.

**Comment by teto** [comment]
+I expected something along those lines. I will run some tests on my side and reopen if I have other issues. Thanks !
