### ISSUE TITLE
plex on aarch64-linux: error: i686 Linux package set can only be used with the x86 family

### ISSUE THREAD

**Issue by ohlus** [NixOS/nixpkgs#187904]
### Steps To Reproduce

`flake.nix`:

```nix
{
  description = "plex build repro";
  inputs = {
    nixpkgs.url = "nixpkgs/master"; # error
    # nixpkgs.url = "nixpkgs/nixos-unstable"; # error
    # nixpkgs.url = "nixpkgs/nixos-22.05"; # OK
  };
  outputs = inputs@{ self, nixpkgs, ... }:
    let
      plex-system = {
        system = "aarch64-linux";
        modules = [
          ({ pkgs, ... }:
            {
              # error: i686 Linux package set can only be used with the x86 family.
              services.plex.enable = true; # either this,
              environment.systemPackages = with pkgs; [ plex ]; # or this

              nixpkgs.config.allowUnfree = true;
              # settings that are required to build the system
              system.stateVersion = "22.05";
              fileSystems."/".device = "/this-is-just-a-test";
              boot.loader.grub.enable = false;
            })
        ];
      };
    in
    {
      nixosConfigurations = {
        plex = nixpkgs.lib.nixosSystem plex-system;
      };
    };
}
```

1. Create `flake.nix`
2. Update lock file:

    ```
    nix flake update
    ```
4. Try to build the nixosConfiguration:

    ```
    nixos-rebuild build --flake .#plex
    ```

### Build log

```
$ nixos-rebuild build --flake .#plex
building the system configuration...
error: i686 Linux package set can only be used with the x86 family.
(use '--show-trace' to show detailed location information)
```

### Additional context

I'm building an aarch64-linux NixOS system on x86_64-linux system. It last wokred a few weeks ago on `nixos-unstable` and currently works on `nixos-22.05`. Currently it doesn't work on `nixos-master` and `nixos-unstable`. Only recent change mentioning plex I found is #132963, maybe that's the cause?

### Notify maintainers

@badmutex
@forkk
@lnl7
@pjones
@thoughtpolice
@maxeaubrey
@MayNiklas

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.0, NixOS, 22.11 (Raccoon), 22.11.20220812.c4a0efd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jdheyburn** [comment]
Experiencing the esame too. This PR might be related too:

- https://github.com/NixOS/nixpkgs/pull/187344

**Comment by danwdart** [comment]
yeah, this also happens with everything under the cross compilation set like wine and steam, even when using pkgsCross. Any ideas about the rest?

**Comment by jdheyburn** [comment]
Updated my nixpkgs to include #227510 and that fixed it for me - so I no longer need to use an overlay with the bugfix.
