### ISSUE TITLE
flutter for darwin (aarch64)

### ISSUE THREAD

**Issue by kirinnee** [NixOS/nixpkgs#187947]
**Flutter**
Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.

**Metadata**

* homepage URL: https://flutter.dev/
* source URL: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/flutter/flutter.nix#L170
* license: [BSD 3-clause "New" or "Revised" License](https://spdx.org/licenses/BSD-3-Clause.html)
* platforms: darwin-aarch64

**Comment by wegank** [comment]
#196133

**Comment by wegank** [comment]
Duplicate of #145701.
