### ISSUE TITLE
mkvtoolnix: building does not find qt5

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#18796]
## Issue description

Although the nix expression for `mkvtoolnix` has `qt5.qtbase` in `buildInputs`, qt5 is not being found when the package is built.

`mkvtoolnix` is built using the `drake` build tool.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03pre91207.2b0eace (Gorilla)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre91207.2b0eace"

**Comment by FRidh** [comment]
have you tested 79995e91de6fa05e276cf1d19beb52d5c39988df?

**Comment by romildo** [comment]
Yes, I have tested. It builds all applications but the GUI version. I did not saw immediately that the GUI version was not there. Current version in unstable NixOS also has this issue.

Probably the issue is a consequence of changes in the way QT applications are built in NixOS. It seems that most QT applications now are built with specialized QT hooks in the nix expression. But `mkvtoolnix` uses `drake` as a building helper. I do not know how to make one aware of the other.

Maybe someone more knowledgeable than me on QT and Ruby may help with this issue.

cc @bbenoist @qknight @ttuegel

**Comment by ttuegel** [comment]
> But mkvtoolnix uses drake as a building helper. I do not know how to make one aware of the other.

The default hooks make `g++` and `gcc` aware of the Qt libraries. IIUC, `drake` is only a replacement for `make`, so getting this to work will probably involve modifying the Qt checks that the `mkvtoolnix` project is performing. That will take some familiarity with their build system.

**Comment by romildo** [comment]
In order to find QT5 at build time, the dependency `qt5.qtbase.dev` is needed instead of `qt5.qtbase`, because it looks for some binary tools like `moc`, `rcc` and `uic`.
