### ISSUE TITLE
gnomeExtensions.freon fails to build successfully

### ISSUE THREAD

**Issue by pmarreck** [NixOS/nixpkgs#188077]
### Steps To Reproduce
1. build *X*

### Build log
```
error: builder for '/nix/store/x4nqrz2zl51sxmgvdds7v5frw56zx150-gnome-shell-extension-freon-48.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/6mpsjbp6jgxv9qlfk629m4sglannppb2-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ibn0484j5n1dx0rjr13jci2pfhjqdqyj-nixos-system-nixos-22.05.2609.52527082ea2.drv' failed to build
```

### Notify maintainers
@piegamesde 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.17, NixOS, 22.05 (Quokka), 22.05.2609.52527082ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by pmarreck** [comment]
Just noticed that if I install the `unstable` version, it does build successfully

**Comment by piegamesde** [comment]
This build log does not contain the relevant information about why exactly the build fails. Regardless, extensions are hardly maintained on the stable channel. Feel free to investigate and provide a fix, but I suggest you to overlay the current unstable extensions into your system.
