### ISSUE TITLE
Xorg libinput configuration is ignored

### ISSUE THREAD

**Issue by deejayem** [NixOS/nixpkgs#188046]
### Describe the bug
At least some options set for services.xserver.libinput are ignored. I have the following in `/etc/nixos/configuration.nix`:
```
  services.xserver.libinput = {
    enable = true;
    touchpad = {
      clickMethod = "clickfinger";
      naturalScrolling = true;
    };
  };
```

but neither of these options appear in `/etc/X11/xorg.conf.d/40-libinput.conf` (`egrep -i 'click|natural' /etc/X11/xorg.conf.d/40-libinput.conf`
 returns nothing).

`man configuration.nix` says that `services.xserver.libinput.touchpad.clickMethod` and `services.xserver.libinput.touchpad.naturalScrolling` are valid options (with the later being a boolean, and the type of the former being 'null or one of "none", "buttonareas", "clickfinger"')

My whole `/etc/X11/xorg.conf.d/40-libinput.conf` file is here: http://ix.io/1TMa

Several people reported the same issue here: https://discourse.nixos.org/t/xorg-libinput-configuration-seems-to-be-ignored/15504 , someone saying it started when upgrading from 21.11 to 22.05

### Steps To Reproduce
1. Add configuration for `services.xserver.libinput.touchpad` to `/etc/nixos/configuration.nix`
2. Run `nixos-rebuild switch`

### Expected behavior
The configured options should appear in `/etc/X11/xorg.conf.d/40-libinput.conf`.

### Additional context
Everything in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/hardware/libinput.nix looks okay to me.

### Notify maintainers
There's no meta.maintainers in https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/hardware/libinput.nix but @thiagokokada and @dsg22 have touched this recently-ish. Sorry if you're the wrong people to @ 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.05 (Quokka), 22.05.2609.52527082ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(djm): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by thiagokokada** [comment]
It definitively works for me. And we also have tests that should prove it (assuming the tests for NixOS are being run): https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/libinput.nix

As can be seen in the tests, you shouldn't look at the `/etc/X11/xorg.conf.d/40-libinput.conf`, but in the logs to see if the configs are being loaded. And it definitively is being loaded in my config.

Now, how this works actually I also have no idea.

**Comment by thiagokokada** [comment]
> Now, how this works actually I also have no idea.

Actually, I just remembered. It is this part: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/hardware/libinput.nix#L276-L279

That writes in the `/etc/X11/xorg.conf` instead.

**Comment by deejayem** [comment]
Thank you for the pointer.

In my case:
```$ ls /etc/X11/xorg.conf  
ls: cannot access '/etc/X11/xorg.conf': No such file or directory
```
`egrep -ir 'click|natural' /etc/X11/*` returns nothing (and looking in `/etc/*` they don't appear anywhere except my configuration.nix). 


I have no `/var/log/Xorg.0.log`, so I guess it only goes to the systemd journal. I don't see those options appearing in the `journalctl` output, which I assume it would be.

It's hard to tell if the options are somehow present somewhere anyway, as I'm using gdm+gnome until I can get the touchpad properly configured without it, and gnome has it's own settings for these iirc.

**Comment by thiagokokada** [comment]
> Thank you for the pointer.
> 
> In my case:
> 
> ```
> ls: cannot access '/etc/X11/xorg.conf': No such file or directory
> ```
> 
> `egrep -ir 'click|natural' /etc/X11/*` returns nothing (and looking in `/etc/*` they don't appear anywhere except my configuration.nix).
> 
> I have no `/var/log/Xorg.0.log`, so I guess it only goes to the systemd journal. I don't see those options appearing in the `journalctl` output, which I assume it would be.
> 
> It's hard to tell if the options are somehow present somewhere anyway, as I'm using gdm+gnome until I can get the touchpad properly configured without it, and gnome has it's own settings for these iirc.

I think that is the issue then, because I definitively have a `/etc/X11/xorg.conf` file.

Maybe the issue is your display manager? I don't use one.

**Comment by thiagokokada** [comment]
https://github.com/NixOS/nixpkgs/blob/50f9b3107a09ed35bbf3f9ab36ad2683619debd2/nixos/modules/services/x11/xserver.nix#L637-L642

This seems to be the culprit of your issue. It is defined here:

https://github.com/NixOS/nixpkgs/blame/50f9b3107a09ed35bbf3f9ab36ad2683619debd2/nixos/modules/services/x11/xserver.nix#L188-L195

So setting `services.xserver.exportConfiguration = true;` should solve the issue.

The strange thing is that this is not set on mine config and it still works. It is probably set indirect in some other place, and GDM itself doesn't 🤔 ?

**Comment by deejayem** [comment]
Thank you, `services.xserver.exportConfiguration = true;` got me an Xorg.conf file.

I made an error earlier: apparently a recent gnome upgrade meant I'm now using wayland. Telling gdm to use xorg I see:
```
Aug 23 17:53:07 egalmoth /nix/store/f1pskczpshwwqx5pj88nq0i6lzcy2w1l-gdm-42.0/libexec/gdm-x-session[6923]: (**) Option "NaturalScrolling" "off"
Aug 23 17:53:07 egalmoth /nix/store/f1pskczpshwwqx5pj88nq0i6lzcy2w1l-gdm-42.0/libexec/gdm-x-session[6923]: (**) Option "NaturalScrolling" "on"
Aug 23 17:53:07 egalmoth /nix/store/f1pskczpshwwqx5pj88nq0i6lzcy2w1l-gdm-42.0/libexec/gdm-x-session[6923]: (**) Option "ClickMethod" "clickfinger"
Aug 23 17:53:07 egalmoth /nix/store/f1pskczpshwwqx5pj88nq0i6lzcy2w1l-gdm-42.0/libexec/gdm-x-session[6923]: (**) Option "NaturalScrolling" "off"
```

So it seems to work once I have the configuration, and once I'm actually using xorg again!

I'm still a little confused, as my touchpad doesn't work properly in gdm, (i.e. before logging into gnome), which I thought meant that xorg wasn't configured properly, (but then gnome's own magic takes over and makes it work). But I'd like to be free from gdm anyway, and everything in the config looks okay now, so I'll just close this.
