### ISSUE TITLE
nixos-install doesn't ask for root password anymore

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#18808]
Since a while doing a stock installation (which doesn't set `mutableUsers = false`) doesn't ask for the root password anymore.

Probably the `if [ -z "$noRootPasswd" ] && [ -x $mountPoint/var/setuid-wrappers/passwd ] && [ -t 0 ]; then` check doesn't work since the latest setuid wrapper changes, as the absolute symlink resolves incorrectly in the installing host.

````
+ ls -lah /mnt/var/setuid-wrappers
lrwxrwxrwx 1 root root 51 Sep 21 15:41 /mnt/var/setuid-wrappers -> /run/setuid-wrapper-dirs/setuid-wrappers.zHrN5I4dUK
````

cc @domenkozar

**Comment by domenkozar** [comment]
806e88c1

**Comment by domenkozar** [comment]
Maybe it should be:

`[ "$(chroot $mountPoint '[-x /var/setuid-wrappers/passwd ] && echo true') = true ]`

or something similar. cc @obadz

**Comment by ericsagnes** [comment]
Not directly related to this issue, but the password setup phase is a point of possible failure (in the case the user make a mistake in the password check).

Would it make sense to separate the password setup in a dedicated command (`nixos-install --setup-root-password`), or to at least to add some instructions in the documentation for what to do when the password setup failed?

**Comment by dezgeg** [comment]
Well the install command can simply be re-run.

If someone wants to make it fancy, I guess it could ask the user whether to retry if the passwd command did not exit with status 0.

**Comment by obadz** [comment]
Argl, this definitely needs to be fixed :-(

The idea is to find out if the closure has `mutableUsers` turned on or off, without invoking invoking a nix evaluation (since with `--closure` we may only have the output and not the nix source).

Right now I can only think of parsing the json out of `grep users-groups.json$ /nix/var/nix/profiles/system/activate`. That's quite ugly. Maybe a better solution would be to modify the `nixos/modules/config/users-groups.nix` so that it creates a `/etc/static/mutable-users` whose existence we can test?

**Comment by dezgeg** [comment]
The flag file approach sounds sensible to me.

**Comment by cstrahan** [comment]
Is there any reason you can't do something like this?

```
if [ -z "$noRootPasswd" ] && [ -x "$mountPoint/$(readlink -f $mountPoint/var/setuid-wrappers/passwd)" ] && [ -t 0 ]; then
    echo "setting root password..."
    chroot $mountPoint /var/setuid-wrappers/passwd
fi
```

**Comment by cstrahan** [comment]
... although, a flag file would probably be less fragile.

**Comment by obadz** [comment]
@cstrahan, I like your solution the best.  If someone has a chance to test & push that would be great.  I'm really tied out these days so can't do it myself.

**Comment by dezgeg** [comment]
That solution feels kind of brittle, since if anybody changes the absolute symlink to relative, it will break again.

**Comment by dezgeg** [comment]
I settled for a34ec1517fc76dca1d3aa1cd3f04a04ef4109753.

**Comment by obadz** [comment]
@dezgeg, thanks!
