### ISSUE TITLE
pkgs.python310Packages.ifcopenshell: Out-of-date 210410 -> Latest Version.

### ISSUE THREAD

**Issue by PlumpMath** [NixOS/nixpkgs#188049]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/ifcopenshell/default.nix

I privately maintain the latest version of the build, but as it has recently been updated to python 310, in nixos, even if the build succeeds, python loading fails.

**Comment by PlumpMath** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/issues/2347

import error log.

**Comment by PlumpMath** [comment]
From a few days ago, in the latest version of ifcopenshell
Another new error occurred.
Now, maybe it needs the lib and bin folders under the global path(nix store) python installed,

error: builder for '/nix/store/65qhxngq2wjzwwpy87q0b8qsx6sizk0f-python3.10-ifcopenshell-master.drv' failed with exit code 2;
       last 10 log lines:
       > -- Installing: /nix/store/9h9jln7v9x5cbiakja9imgs9vgmp26c2-python3.10-ifcopenshell-master/include/serializers/schema_dependent/XmlSerializer.cpp
       > CMake Error at ifcwrap/cmake_install.cmake:49 (file):
       >   file cannot create directory:
       >   /nix/store/c4i6xn02gfljkh7n84f0qm2nbk3a5bd7-python3-3.10.6/lib/python3.10/site-packages/ifcopenshell.
       >   Maybe need administrative privileges.
       > Call Stack (most recent call first):
       >   cmake_install.cmake:574 (include)
       >
       >
       > make: *** [Makefile:120: install] Error 1
       For full logs, run 'nix log /nix/store/65qhxngq2wjzwwpy87q0b8qsx6sizk0f-python3.10-ifcopenshell-master.drv'.
error: 1 dependencies of derivation '/nix/store/4v61z1k87yflv7x014vqn6hi54knnh84-python3-3.10.6-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/drry2q44vpgm2gippci3agshx74prf6i-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/34bc7879naqmpbq3v9n51siq6zmjflw9-darwin-system-22.11.20220901.b57e495+darwin4.80cec51.drv' failed to build

**Comment by PlumpMath** [comment]
Again, it builds & use fine on Nix-Darwin.
NixOS is, as the first mentioned problem,
I'm not sure how import (use) works since it's built... but building now anyway.
I posted the latest code below, can anyone test it and change nixpkgs to make it work on NixOS as well?

On nixos,
  This error occurs as a result of importing the latest version of the Python module.

-----------------------------------------------------------  
$ python
Python 3.10.6 (main, Aug  1 2022, 20:38:21) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell

Traceback (most recent call last):
  File "/nix/store/qfn7q2m9zp2b1la796qhmgbmkvczi120-python3-3.10.6-env/lib/python3.10/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: libTKernel.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/qfn7q2m9zp2b1la796qhmgbmkvczi120-python3-3.10.6-env/lib/python3.10/site-packages/ifcopenshell/__init__.py", line 54, in <module>
    from . import ifcopenshell_wrapper
  File "/nix/store/qfn7q2m9zp2b1la796qhmgbmkvczi120-python3-3.10.6-env/lib/python3.10/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 17, in <module>
    _ifcopenshell_wrapper = swig_import_helper()
  File "/nix/store/qfn7q2m9zp2b1la796qhmgbmkvczi120-python3-3.10.6-env/lib/python3.10/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_ifcopenshell_wrapper')
  File "/nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ifcopenshell_wrapper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/qfn7q2m9zp2b1la796qhmgbmkvczi120-python3-3.10.6-env/lib/python3.10/site-packages/ifcopenshell/__init__.py", line 62, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python3.10'
-----------------------------------------------------------

@xaverdh  @SuperSandro2000  @Mindavi  @Profpatsch  @ju1m  @alyssais  @wamserma  @fehnomenal 

Help me. Sorry & Thanks.

my nix code:

  IFCOPENSHELL = let
    cgal = stdenv.mkDerivation rec {
      pname = "cgal";
      version = "master";
      src = inputs.cgal;
      buildInputs = [ boost gmp mpfr ];
      nativeBuildInputs = [ cmake ];
      doCheck = false;
    };
  in with python310Packages;
  # if stdenv.isDarwin then (
    buildPythonPackage rec {
    pname = "ifcopenshell";
    format = "other";
    version = "master";
    src = inputs.ifcopenshell;
    # version = if stdenv.isDarwin then "master" else "220817";
    # src = if stdenv.isDarwin then inputs.ifcopenshell else fetchFromGitHub {
      #   owner  = "IfcOpenShell";
      #   repo   = "IfcOpenShell";
      #   fetchSubmodules = true;
      #   rev    = "blenderbim-${version}";
      #   sha256 = "sha256-051c7igcrlmsQjgJt8a/ZszZolrkZOooItT8qMpyqyE="; # 220817
      # };
      doCheck = false;
      buildInputs = [
        cmake libiconv swig libaec mpfr icu pcre libxml2 boost174 cgal ftgl gcc python310
      ] ++ (if stdenv.isDarwin then [] else [
        stdenv.cc.cc.lib
        cython numpy python-dateutil pytz
      ]);
      propagatedBuildInputs = buildInputs;
      nativeBuildInputs = buildInputs;
      enableParallelBuilding = true;
      dontUsePytestXdist = true; # don't max out build cores, it breaks tests
      preConfigure = ''
        cd cmake
      '';
        # mkdir -pv $out/bin
        # mkdir -pv $out/lib/python3.10/site-packages/ifcopenshell
        # mkdir -pv $out/${python310.sitePackages}/ifcopenshell
      PYTHONUSERBASE=".";
      cmakeFlags = [
        "-DOPENCOLLADA_INCLUDE_DIR=${opencollada}/include/opencollada"
        "-DOPENCOLLADA_LIBRARY_DIR=${opencollada}/lib/opencollada"
        # -DPCRE_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu/
        "-DCGAL_INCLUDE_DIR=${lib.getDev cgal}/include"
        "-DGMP_LIBRARY_DIR=${gmp}/lib"
        "-DMPFR_LIBRARY_DIR=${mpfr}/lib"
        "-DGMP_INCLUDE_DIR=${gmp.dev}/include"                    
        "-DHDF5_SUPPORT=OFF"
        
        "-DUSERSPACE_PYTHON_PREFIX=ON"
        "-DOCC_INCLUDE_DIR=${opencascade-occt}/include/opencascade"
        "-DOCC_LIBRARY_DIR=${opencascade-occt}/lib"
        # "-DCOLLADA_SUPPORT=0"
        "-DSWIG_EXECUTABLE=${swig}/bin/swig"
        "-DLIBXML2_INCLUDE_DIR=${libxml2.dev}/include/libxml2"
        "-DLIBXML2_LIBRARIES=${libxml2.out}/lib/libxml2${stdenv.hostPlatform.extensions.sharedLibrary}"
        # ---------------------
        # "-DCGAL_INCLUDE_DIR=${if stdenv.isDarwin then lib.getDev CGAL else lib.getDev cgal}/include"
        "-DBoost_INCLUDE_DIR=${lib.getDev boost174}/include"
        "-DBoost_LIBRARY_DIR=${lib.getDev boost174}/lib"
      ];
      # postInstall = ''          
      # '';
  };

**Comment by PlumpMath** [comment]
All of the above builds worked fine.
I switched to Pypi.
In wsl(nixos) and nix-darwin, even without changing the directory, it was imported well.
However, to import on NixOS linux,
You have to move to /nix/store/blahblah-system-path/lib/python3.10/site-packages or the built ifcopenshell-python nix-store directory to import it.

I don't know why, but the day will come when nixos will solve it? thank you

                ifcopenshell-python = with python310Packages; buildPythonPackage rec {
                  pname = "ifcopenshell-python";
                  version = "0.7.0-220912";
                  format = "wheel";
                  disabled = pythonOlder "3.9";
                  src = fetchPypi ({
                    pname = "ifcopenshell_python";
                    inherit version format;
                    dist = "py310";
                    python = "py310";
                  } // (if stdenv.isDarwin then {
                    platform = "macosx_10_15_x86_64";
                    sha256 = "sha256-JTaZtWtn5B3OSgZ+8tZjqhSK/3MNDY8uTkKQivqW0J8=";
                  } else {
                    platform = "manylinux1_x86_64";
                    sha256 = "sha256-PORLVjZXDa4JsCUaGQmMC4DtcuW1t3ZMCiHFg+3g92w=";
                  }));
                  nativeBuildInputs = if stdenv.isDarwin then [] else [
                    pam gcc wrapGAppsHook
                    stdenv.cc.cc.lib autoPatchelfHook glibc
                  ];
                  buildInputs = nativeBuildInputs;
                  pythonImportsCheck = [ "ifcopenshell" ];                  
                };

**Comment by Mindavi** [comment]
Somehow I totally missed this, but I'm also afraid I cannot really help you further with this :(

**Comment by PlumpMath** [comment]
ifcopenshell = with pkgs; with pkgs.python3Packages; buildPythonPackage rec {
      pname = "ifcopenshell";
      version = "0.7.0-221014";
      format = "wheel";
      disabled = pythonOlder "3.9";
      # src = inputs.ifcopenshell;
      src = fetchPypi ({
        pname = "ifcopenshell";
        inherit version format;
        dist = "py310";
        python = "py310";
      } // (if stdenv.isDarwin then {
        platform = "macosx_10_15_x86_64";
        sha256 = "sha256-bsWXS2Y9+e8572q8KClNOKTKljZqq+ugj8uSFld8IlA=";
      } else {
        platform = "manylinux1_x86_64";
        sha256 = "sha256-01S8HCULx58l9JdBLrVUaRgbEkbj9MfQ4dp11KUX8YM=";
      }));
      nativeBuildInputs = if stdenv.isDarwin then [] else [
        pam gcc wrapGAppsHook
        stdenv.cc.cc.lib autoPatchelfHook glibc
      ];
      buildInputs = nativeBuildInputs;
      pythonImportsCheck = [ "ifcopenshell" ];                  
    };

Some credible sources...
  I would like to change it to flake inputs.

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/commit/b9f2aa31ae111f656cea317717a9ffe4b4b5d313
