### ISSUE TITLE
Packaging Request: Black Box

### ISSUE THREAD

**Issue by Lyndeno** [NixOS/nixpkgs#188062]
**Project description**
A GTK4 terminal application

**Metadata**

* homepage URL: https://gitlab.gnome.org/raggesilver/blackbox
* source URL: https://gitlab.gnome.org/raggesilver/blackbox
* license: GPL3
* platforms: linux

**Comment by dit7ya** [comment]
Closing as completed. Please feel free to reopen if I am misunderstanding.
