### ISSUE TITLE
can't download luaunbound archive

### ISSUE THREAD

**Issue by teto** [NixOS/nixpkgs#188090]
### Steps To Reproduce

I am trying to update the lua package set but luaunbound is blocking the update: 
error: unable to download 'https://code.zash.se/dl/luaunbound/luaunbound-1.0.0.tar.gz': Timeout was reached (28);
Seems like the website hosting the archive is down
https://luarocks.org/modules/zash/luaunbound
https://github.com/Zash/lua-unbound

Not sure what to do here, I could probably add some code to the updater to that it considers this derivation as broken ?
Otherwise contact their maintainer ? luaunbound seems only used by prosody: @globin what do you think ? could you contact the maintainer so that he fixes his hosting ?

**Comment by Artturin** [comment]
site is up currently

**Comment by teto** [comment]
indeed it is back now ty
