### ISSUE TITLE
OBS plugin Source Record

### ISSUE THREAD

**Issue by Not-a-true-statement** [NixOS/nixpkgs#188196]
**Project description**
Plugin for OBS Studio to make sources available to record via a filter

**Metadata**

* homepage URL: https://obsproject.com/forum/resources/source-record.1285/
* source URL: https://github.com/exeldro/obs-source-record
* license: gpl2
* platforms: linux, darwin, windows

**Comment by robbins** [comment]
Created a PR here: #188925

**Comment by fpletz** [comment]
Merged https://github.com/NixOS/nixpkgs/pull/188925.
