### ISSUE TITLE
perlPackages.CryptDES has unfree license?

### ISSUE THREAD

**Issue by wentasah** [NixOS/nixpkgs#188103]
### Describe the bug

PR #187842 added (among others) missing metadata about perl packages and changed the license of `CryptDES` to `unfreeRedistributable`. This makes the the `ikiwiki` package, which I maintain, not build without NIXPKGS_ALLOW_UNFREE=1 or similar settings. I wonder whether *unfreeRedistributable* was selected after the analysis of the license or it is just a consequence of the fact that [metacpan](https://metacpan.org/dist/Crypt-DES) lists the license as *unknown*.

The license (shown below) is similar to [3-clause BSD license](https://opensource.org/licenses/BSD-3-Clause), but the 3rd clause is different. Note that Debian [distributes this package](https://tracker.debian.org/pkg/libcrypt-des-perl) in its main archive, which means, they consider the license free.

```
This library and applications are FREE FOR COMMERCIAL AND NON-COMMERCIAL USE
as long as the following conditions are adhered to.

Copyright remains with Systemics Ltd, and as such any Copyright notices
in the code are not to be removed.  If this code is used in a product,
Systemics should be given attribution as the author of the parts used.
This can be in the form of a textual message at program startup or
in documentation (online or textual) provided with the package.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by Systemics Ltd (http://www.systemics
.com/)

   THIS SOFTWARE IS PROVIDED BY SYSTEMICS LTD ``AS IS'' AND
   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
   FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
   OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
   HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
   OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
   SUCH DAMAGE.

   The licence and distribution terms for any publically available version or
   derivative of this code cannot be changed.  i.e. this code cannot simply be
   copied and put under another distribution licence
   [including the GNU Public Licence.]


```

### Steps To Reproduce
1. `nix-build -A ikiwiki`

### Expected behavior
Package builds

### Notify maintainers
@dasJ @stigtsp

**Comment by dasJ** [comment]
> I wonder whether unfreeRedistributable was selected after the analysis

that was the best I could come up with, yeah.

I'm a bit conflicted about the license.
CentOS categorizes it as [BSD](https://centos.pkgs.org/7/centos-x86_64/perl-Crypt-DES-2.05-20.el7.x86_64.rpm.html) (no clause count) while I don't see anything on your Debian page but the [copyright file](https://metadata.ftp-master.debian.org/changelogs//main/libc/libcrypt-des-perl/libcrypt-des-perl_2.07-4_copyright) leads me to believe that they also think the license is "other".

We have the same issue with `Crypt::Blowfish`. Buildroot just [labels it as BSD-4](https://buildroot.uclibc.narkive.com/SXyOcIJt/patch-1-5-perl-crypt-blowfish-add-missing-license-declaration) and Fedora labels it as [BSD + other](https://lists.fedoraproject.org/pipermail/devel/2015-June/211278.html).

Last one I labeled unfree (let's do all of them) is `Crypt::IDEA`. EPEL labels it as [BSD with advertising](https://yum-info.contradodigital.com/view-package/epel/perl-Crypt-IDEA/).

Does anone have concrete ideas what license to give these packages? Do we maybe need yet another entry in licenses.nix?

**Comment by wentasah** [comment]
Interesting, I didn't know about the original BSD-4 license. [Debian explicitly states](https://www.debian.org/legal/licenses/) that this license can be in the main archive and hence is free. So I'd suggest to either switch the license to `bsdOriginal`, which would be a bit inaccurate, or to add a new license, say `bsdAdvertising`, and use this license for `Crypt::DES`, `Crypt::Blowfish` and `Crypt::IDEA`. All these packages have the same 3 clauses in the license. Let me know if I should prepare a PR with either of these changes.

**Comment by dasJ** [comment]
I don't see why we wouldn't add `bsdAdvertising` to the licenses, I added 2 licenses for my change anyway so yet one more wouldn't hurt ;)
