### ISSUE TITLE
vim plugins are loaded after $VIMRUNTIME ftplugin files

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#188167]
## Issue description

when using neovim.override to "install" pure-nixpkgs plugins, ftplugin files provided by plugins are loaded after ftplugin files from $VIMRUNTIME, which break plugins like vimtex.

this is a regression of https://github.com/NixOS/nixpkgs/pull/184364, cc @teto 

### Steps to reproduce

Consider
```nixpkgs
with import ./. {};
neovim.override {
  configure = {
    packages.myVimPackage = with pkgs.vimPlugins; {
      start = [ vimtex ];
    };
  };
}
```

On 60b0ef2931f945d118ab1e34ea3c7436c764d568 (https://github.com/NixOS/nixpkgs/pull/184364) running `nvim main.tex` does not load vimtex correctly (type `:Vim<tab>` there are only two commands defined)
This is due to vimtex ftplugin running after $VIMRUNTIME one, which sets `b:did_ftplugin` and inhibits vimtex:
```
:exe 'filter #ftplugin/' . &filetype . '.vim$# scriptnames'
 29: /nix/store/j3rp7xiwb9r2csr8196680hlwsjx8g45-neovim-unwrapped-0.7.2/share/nvim/runtime/ftplugin/tex.vim
 32: /nix/store/ybkfxbyhfrq9ci91awj7372izs0lgipw-vimplugin-vimtex-2022-07-26/ftplugin/tex.vim
 33: /nix/store/ybkfxbyhfrq9ci91awj7372izs0lgipw-vimplugin-vimtex-2022-07-26/after/ftplugin/tex.vim
```
Before this PR (74a50898fdece3efe305386a07272fd09a1a26b4), vimtex is loaded before
```
:exe 'filter #ftplugin/' . &filetype . '.vim$# scriptnames'
 29: /nix/store/ybkfxbyhfrq9ci91awj7372izs0lgipw-vimplugin-vimtex-2022-07-26/ftplugin/tex.vim
 90: /nix/store/j3rp7xiwb9r2csr8196680hlwsjx8g45-neovim-unwrapped-0.7.2/share/nvim/runtime/ftplugin/tex.vim
 91: /nix/store/ybkfxbyhfrq9ci91awj7372izs0lgipw-vimplugin-vimtex-2022-07-26/after/ftplugin/tex.vim
```
and typing `:Vim<tab>` autocompletes many ;Vimtex commands

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.05 (Quokka), 22.05.2609.52527082ea2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - channels(symphorien): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by teto** [comment]
thanks for the detailed report <3 I would like to avoid reverting the MR since it improves on other issues.
What if you set the rtp after the packpath as advised here ?
https://discourse.nixos.org/t/neovim-runtimepath-broken/21003/5?u=teto

Would be nice to have a test to prevent this kind of regression. Anyone feel free to contribute.

**Comment by symphorien** [comment]
thank you for pointing me to the solution. I opened #188205
