### ISSUE TITLE
OCaml Compiler Versions

### ISSUE THREAD

**Issue by maurer** [NixOS/nixpkgs#18819]
We currently have support for a huge number of OCaml compilers, from the truly ancient 3.0.8, up to 4.02.3.

An increasing number of OCaml packages are mandating 4.02 or higher to build - in the tree right now, 57 packages which either fail to build with OCaml < 4.02, need to use an older version of the package, or need to add configure switches/patches to disable features.

This problem is not going away, it's only getting worse - of the packages I've been adding to the tree for work, only one of them did not mandate OCaml >=4.02 to work.

To exacerbate the situation, OCaml is switching to a new macro system (`ppx`) which is only supported in 4.02 and up. In #18572 I've tried to keep support around for the `camlp4` stuff around, but this is mostly a stopgap measure.

We need to make a few decisions:
1. Do we want to change the default OCaml version?
2. Do we really want to keep all these versions around?
3. Do we want to support `camlp4` in the future?

Personally, I'd propose:
1. Bump default OCaml to 4.02
2. Keep a minimal set of compiler versions (hopefully just 4.02 + one other) in order to keep any applications (not libraries) which may depend on older OCaml working.
3. Similarly to legacy OCaml compiler support, I'd recommend keeping `camlp4` versions of libraries around only in cases where they are used by a binary.

Obviously I'm not the one to make the decision, but something needs to be done about this or it's only going to get more difficult to keep up with the OCaml ecosystem.

**Comment by maurer** [comment]
cc: @aske @vbgl (I think you may have opinions on this)

**Comment by aske** [comment]
I'm all for version bump and bumping to 4.02 and removing old clutter.
Will take a look on what to keep a bit later.

Also +1 for switching to `ppx`.

I think we should keep latest 3.12 compiler in case user wants to use some ancient research project or similar and 4.01 for packages that may not work with 4.02+ (are there any?).

For new packages it's probably better to operate under assumption that it will be used with 4.02+ only (btw, will it require a lot of work to switch to 4.03 as a default version?).

**Comment by regnat** [comment]
I think we could directly switch to 4.03, as the vast majority of packages working with 4.02 have also a working version for 4.03 (the [opam weather service](http://ows.irill.org/latest/today/weather.html) gives a neat overview of the state of packages against various compiler versions), and 4.04 is already about to land soon.

Also :+1: for keeping one (but no more) old version if needed for some packages -- but this may not be needed, as --- except for ppx --- the compiler keeps a rather good retro-compatibility.

**Comment by regnat** [comment]
Now that ocaml 4.03 is in nixpkgs, is there a possibility to set-up a hydra jobset for ocamlPackages_4_03 --- and maybe ocamlPackages_4_02 too, so that one can see which packages build fine and which one needs to be fixed before any decision is taken ?

**Comment by Zimmi48** [comment]
Any news on this topic?

**Comment by FlorentBecker** [comment]
We did switch to 4.02 by default.

**Comment by maurer** [comment]
(Going through my backlog of open issues)

* As Florent said, we switched to 4.02 as our default
* Packages seem to be being migrated to `ppx` opportunistically, as long as `nox-review` and friends indicate no breakage

As a result, the really awkward package splitting I was complaining about seems to be resolved, and I'm closing the issue.

**Comment by vbgl** [comment]
What about making 4.04 the default? 4.05 should land next week, but many packages in nixpkgs are not ready for it yet.
