### ISSUE TITLE
$HTTP_PROXY is not set when setting a proxy

### ISSUE THREAD

**Issue by iopq** [NixOS/nixpkgs#188132]
### Describe the bug

Certain software (e.g. Wine) expects $HTTP_PROXY to be set when using a proxy. NixOS sets $http_proxy only

### Steps To Reproduce
1. In configuration.nix set `networking.proxy.default = "socks5://127.0.0.1:1080/";`
2. Check that $http_proxy is set `echo $http_proxy`
3. Check that $HTTP_PROXY is NOT set `echo $HTTP_PROXY`

### Expected behavior
Wine should have internet access, but it uses $HTTP_PROXY variable instead

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.56, NixOS, 22.05 (Quokka), 22.05.2019.d9536b9b1e3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

**Comment by FRidh** [comment]
Should this be fixed at our side or maybe at the Wine side? I wonder how much other software requires uppercase for this environment variable.

**Comment by iopq** [comment]
> Should this be fixed at our side or maybe at the Wine side? I wonder how much other software requires uppercase for this environment variable.

Actually, I just noticed they use both variables, but some software sometimes ignores proxies, so it might not be a Wine issue after all

https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca

https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

Maybe it's not worth changing after all
