### ISSUE TITLE
#188084 breaks nixos profiles using NVIDIA video driver

### ISSUE THREAD

**Issue by Mechtecs** [NixOS/nixpkgs#188206]
### Describe the bug
NVIDIA driver still sets _useGlamor_ option, which prohibits a nixos build using the master branch.

### Steps To Reproduce
1. Build nixos system using master branch & nvidia video driver

### Expected behavior
Profile validates and builds.

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.3, NixOS, 22.11 (Raccoon), 22.11.20220824.f7124f2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
$ nixos-rebuild dry-build
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error:
       Failed assertions:
       - The option definition `services.xserver.useGlamor' in `/nix/store/rw3blmd5ar6jmwsg8z6x6zd2jlp9ddd2-source/nixos/modules/hardware/video/nvidia.nix' no longer has any effect; please remove it.
       Option services.xserver.useGlamor was removed because it is unnecessary. Drivers that uses Glamor will use it automatically.
(use '--show-trace' to show detailed location information)
FAIL
```

### Notes
Introduced by #188084.
I guess removing [this line](https://github.com/NixOS/nixpkgs/blob/0b4b412714e798056424b5e01e04a8bf462a9859/nixos/modules/hardware/video/nvidia.nix#L263) would solve the problem. Currently testing this hotfix, but as I am no export on the matter, this is probably not the solution.
Fix can be found [here](https://github.com/Mechtecs/nixpkgs/tree/fix/nvidia). Currently rebuilding 3000+ packages. If everything works, I would create a PR.

**Comment by S-NA** [comment]
> I guess removing [this line](https://github.com/NixOS/nixpkgs/blob/0b4b412714e798056424b5e01e04a8bf462a9859/nixos/modules/hardware/video/nvidia.nix#L263) would solve the problem. Currently testing this hotfix, but as I am no export on the matter, this is probably not the solution.

It probably is the solution. Setting `glamor` only ever made sense for when `intel` was in `services.xserver.videoDrivers`. [NVIDIA PRIME render offload requires `modesetting`](https://download.nvidia.com/XFree86/Linux-x86_64/515.65.01/README/primerenderoffload.html) and that should automatically enable glamor. From what I can tell the mechanism that specifies the driver for the device still specifies modesetting.

**Comment by Mechtecs** [comment]
I could also successfully test my fix and will try to submit my first PR now :smile:
