### ISSUE TITLE
expose more postgresql initdb flags

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#18829]
The line https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/postgresql.nix#L208

Does not use the value of `i18n.defaultLocale` but maybe it should?

**Comment by danbst** [comment]
Probably not (you don't always init new DB, sometime you want to start postgres with existsing DB, and locale guaranties are lost). But exposing `initdb` additional flags as nixos options would be an improvement.

**Comment by nhooyr** [comment]
Nevermind, it does set it correctly, I made a mistake.

I'll rename this issue to be about exposing additional flags.

**Comment by spinus** [comment]
This would be nice as you can pass -k (if I remember correctly) and this enabled data checksums in postgresql and can be done only on cluster init.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by danbst** [comment]
@mmahut the PR https://github.com/NixOS/nixpkgs/pull/65245 is aimed to fix that, but it is still in review phase

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
