### ISSUE TITLE
GnuPG regression with YubiKey

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#188228]
### Describe the bug
GnuPG can no longer see the keys on my YubiKey 5.

### Steps To Reproduce
1. Enable pcscd in the system configuration with `services.pcscd.enable = true;`
2. Enable gpg-agent in the home-manager configuration like
   ```nix
   programs.gpg = {
     enable = true;
     settings = {
       default-key = "AAAA...";
     };
     scdaemonSettings = {
       disable-ccid = true;
     };
   };
   services.gpg-agent = {
     enable = true;
     enableSshSupport = true;
     pinentryFlavor = "gtk2";
   };
   ```
3. Reboot to fully apply changes to services.
4. Run `gpg --card-status`
```text
Reader ...........: Yubico YubiKey OTP FIDO CCID 00 00
Application ID ...: ████████████████████████████████
Application type .: OpenPGP
Version ..........: 1.0
Manufacturer .....: ?
Serial number ....: 12345678
Name of cardholder: [not set]
Language prefs ...: [not set]
Salutation .......:
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: not forced
Max. PIN lengths .: 3 -2 0
PIN retry counter : 0 0 0
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]
```

### Expected behavior
Expected `gpg --card-status` to output full card information like below (private information redacted).
```text
Reader ...........: Yubico YubiKey OTP FIDO CCID 00 00
Application ID ...: ████████████████████████████████
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Yubico
Serial number ....: 12345678
Name of cardholder: [not set]
Language prefs ...: [not set]
Salutation .......:
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: not forced
Key attributes ...: nistp521 nistp521 nistp521
Max. PIN lengths .: x y z
PIN retry counter : x y z
Signature counter : xxx
KDF setting ......: off
UIF setting ......: Sign=off Decrypt=off Auth=off
Signature key ....: DEAD BEEF DEAD BEEF DEAD  BEEF DEAD BEEF DEAD BEEF
      created ....: 20██-██-██ ██:██:██
Encryption key....: DEAD BEEF DEAD BEEF DEAD  BEEF DEAD BEEF DEAD BEEF
      created ....: 20██-██-██ ██:██:██
Authentication key: DEAD BEEF DEAD BEEF DEAD  BEEF DEAD BEEF DEAD BEEF
      created ....: 20██-██-██ ██:██:██
General key info..: pub  nistp521/0xDEADBEEFDEADBEEF 20██-██-██ Aidan Gauland <...@example.com>
sec>  nistp521/0xDEADBEEFDEADBEEF  created: 20██-██-██  expires: ███
                                   card-no: ████ ████████
ssb>  nistp521/0xDEADBEEFDEADBEEF  created: 20██-██-██  expires: ███
                                   card-no: ████ ████████
ssb>  nistp521/0xDEADBEEFDEADBEEF  created: 20██-██-██  expires: ███
                                   card-no: ████ ████████
```

### Additional context
I am using pcscd instead of having gpg-agent talk to the card directly so that I can also use yubioath-desktop.

This regression seems to have come from PR #183753, going by the commit log on `nixpkgs/pkgs/tools/security/gnupg/` and when I last updated the nixpkgs input in my user profile flake.

### Notify maintainers
@fpletz @vrthra

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.05 (Quokka), 22.05.20220822.5252708`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by genofire** [comment]
I am not sure, if #184493 solve this - once it is merged.

**Comment by aidalgol** [comment]
That PR looks unrelated, since it is for the NixOS module, while I am using the home-manager module, and I already have the `disable-ccid` flag set to `true` via that module.

**Comment by aidalgol** [comment]
This regression has definitely come from PR #183753, because if I have my user profile updated to the latest commit of `nixpkgs-unstable` but set `programs.gpg.package` (in the home-manager module) to use the `gnupg` package from a separate flake input that is pinned to commit 22e81f39ace64964bae3b6c89662d1221a11324c (the last commit to `nixpkgs/pkgs/tools/security/gnupg`/ before this PR was merged), then I get the correct behaviour.

**Comment by aidalgol** [comment]
Sorry, I misread the commit history.  22e81f39ace64964bae3b6c89662d1221a11324c is the commit immediately before the update from 2.3.6 → 2.3.7, not the PR being merged, so this regression has come from GnuPG 2.3.7.

**Comment by psanford** [comment]
This is the upstream bug: https://dev.gnupg.org/T6070

**Comment by terlar** [comment]
Thank you for the link to the upstream bug. Seeing there is a fix already, here is a solution to apply the patch via overlay, I have tested it and it works:

```
final: prev:

{
  gnupg = prev.gnupg.overrideAttrs (old:
    if old.version == "2.3.7" then {
      patches = old.patches ++ [
        (final.fetchpatch {
          name = "fix-yubikey.patch";
          url =
            "https://files.gnupg.net/file/data/io6l7fvfebflbqm44ll3/PHID-FILE-7ppyegfowo5do2d6izc4/file";
          sha256 = "sha256-J/PLSz8yiEgtGv+r3BTGTHrikV70AbbHQPo9xbjaHFE=";
        })
      ];
    } else
      { });
}
```

**Comment by aidalgol** [comment]
That patch works for me with the home-manager module by applying the patch with `overrideAttrs`.
```nix
  programs.gpg = {
    enable = true;
    package = pkgs.gnupg.overrideAttrs (final: prev: {
      patches = prev.patches ++ [
        (pkgs.fetchpatch {
          name = "fix-yubikey.patch";
          url = "https://files.gnupg.net/file/data/io6l7fvfebflbqm44ll3/PHID-FILE-7ppyegfowo5do2d6izc4/file";
          sha256 = "sha256-J/PLSz8yiEgtGv+r3BTGTHrikV70AbbHQPo9xbjaHFE=";
        })
      ];
    });
    # ...
};
```

**Comment by aidalgol** [comment]
@terlar That URL is now returning a 404.

**Comment by GoldsteinE** [comment]
```nix
: prev: {
  gnupg = prev.gnupg.overrideAttrs (old: if old.version == "2.3.7" then {
    patches = old.patches ++ [(final.fetchpatch {
      name = "fix-yubikey.patch";
      url = "https://gist.githubusercontent.com/GoldsteinE/529ebe029af14d43b4cf4cbb521b9869/raw/6b9415160a40dd4c6517831416e29c5d70971743/gpg.patch";
      sha256 = "sha256-KD8H6N9oGx+85SetHx1OJku28J2dmsj/JkJudknCueU=";
    })];
  }
  else {});
})
```
fixes the issue (I reuploaded patch to Gist for URL stability).

**Comment by terlar** [comment]
Perhaps this URL from the GnuPG git is better:
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=f34b9147eb3070bce80d53febaa564164cd6c977;hp=95651d1a4fec9bc5e36f623b2cdcc6a35e0c30bb

Not so familiar with the development of GnuPG so wasn’t sure how to get the patch. Perhaps going via the git web UI instead of the issue tracker is the way.

**Comment by Ma27** [comment]
Void Linux has already included this patch, so perhaps someone could also give it a try here, right? :)

**Comment by x10an14** [comment]
I still haven't properly learned how overlays work, could someone please tell me what I've misunderstood wrt. to the sugtested fixes above?

```
[2022-09-08 23:45:32] 0 user@machine:~/Documents/nix-config
-> $ git diff home-manager/programs/terminal/gpg-agent.nix

home-manager/programs/terminal/gpg-agent.nix

  1 ⋮    │{config, ...}:
    ⋮  1 │{config, pkgs, ...}:
  2 ⋮  2 │{
    ⋮  3 │  programs.gpg = {
    ⋮  4 │    enable = true;
    ⋮  5 │    package = pkgs.gnupg.overrideAttrs (final: prev: {
    ⋮  6 │      gnupg = prev.gnupg.overrideAttrs (old:
    ⋮  7 │        if old.version == "2.3.7" then {
    ⋮  8 │          patches = old.patches ++ [(final.fetchpatch {
    ⋮  9 │            name = "fix-yubikey.patch";
    ⋮ 10 │            url = "https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=f34b9147eb3070bce80d53febaa564164cd6c977;hp=95651d1a4fec9bc5e36f623b2cdcc6a35e0c30bb";
    ⋮ 11 │            sha256 = "sha256-KD8H6N9oGx+85SetHx1OJku28J2dmsj/JkJudknCueU=";
    ⋮ 12 │          })];
    ⋮ 13 │        } else {}
    ⋮ 14 │      );
    ⋮ 15 │    });
    ⋮ 16 │  };
  3 ⋮ 17 │  services.gpg-agent = {
  4 ⋮ 18 │    enable = true;
  5 ⋮ 19 │    enableExtraSocket = true;
[2022-09-08 23:45:35] 0 user@machine:~/Documents/nix-config
-> $ home-manager build
warning: Git tree '/home/user/Documents/nix-config' is dirty
warning: Git tree '/home/user/Documents/nix-config' is dirty
error: attribute 'gnupg' missing

       at /nix/store/fjqmpfcydb2wby9j11xc0zyi25lcimcn-source/home-manager/programs/terminal/gpg-agent.nix:6:15:

            5|     package = pkgs.gnupg.overrideAttrs (final: prev: {
            6|       gnupg = prev.gnupg.overrideAttrs (old:
             |               ^
            7|         if old.version == "2.3.7" then {
(use '--show-trace' to show detailed location information)
[2022-09-08 23:45:45] 1 user@machine:~/Documents/nix-config
-> $ 
```

(Left column line numbers is old lines, right column line numbers are new/edited lines).

**Comment by terlar** [comment]
@x10an14 You are mixing the overlay with the override attributes. I would suggest basing your solution on:
https://github.com/NixOS/nixpkgs/issues/188228#issuecomment-1234952403

But change to the new hash/URL.

```
  # ...
  programs.gpg = {
    enable = true;
    package = pkgs.gnupg.overrideAttrs (final: prev: {
      patches = prev.patches ++ [
        (pkgs.fetchpatch {
          name = "fix-yubikey.patch";
          url = "https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=f34b9147eb3070bce80d53febaa564164cd6c977;hp=95651d1a4fec9bc5e36f623b2cdcc6a35e0c30bb";
          sha256 = "sha256-KD8H6N9oGx+85SetHx1OJku28J2dmsj/JkJudknCueU=";
        })
      ];
    });
    # ...
```

**Comment by x10an14** [comment]
:tabo

> @x10an14 You are mixing the overlay with the override attributes. I would suggest basing your solution on: [#188228 (comment)](https://github.com/NixOS/nixpkgs/issues/188228#issuecomment-1234952403)
> 
> But change to the new hash/URL.
> 
> ```
>   # ...
>   programs.gpg = {
>     enable = true;
>     package = pkgs.gnupg.overrideAttrs (final: prev: {
>       patches = prev.patches ++ [
>         (pkgs.fetchpatch {
>           name = "fix-yubikey.patch";
>           url = "https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=f34b9147eb3070bce80d53febaa564164cd6c977;hp=95651d1a4fec9bc5e36f623b2cdcc6a35e0c30bb";
>           sha256 = "sha256-KD8H6N9oGx+85SetHx1OJku28J2dmsj/JkJudknCueU=";
>         })
>       ];
>     });
>     # ...
> ```

Ahhh, okay. I was trying to combine them so as to keep the "if version" logic you see =)

**Comment by terlar** [comment]
@x10an14 Ah, of course that should be possible as well, then this should work:
```
  # ...
  programs.gpg = {
    enable = true;
    package = pkgs.gnupg.overrideAttrs (old:
      if old.version == "2.3.7" then {
        patches = old.patches ++ [
          (pkgs.fetchpatch {
            name = "fix-yubikey.patch";
            url = "https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=patch;h=f34b9147eb3070bce80d53febaa564164cd6c977;hp=95651d1a4fec9bc5e36f623b2cdcc6a35e0c30bb";
            sha256 = "sha256-KD8H6N9oGx+85SetHx1OJku28J2dmsj/JkJudknCueU=";
          })
        ];
      } else { });
  };
  # ...
```

**Comment by auroraanna** [comment]
Same issue here, did a reset of the OpenPGP module and wiped my keys with it :( Afterwards still same issue.

**Comment by auroraanna** [comment]
@terlar Did you open a PR with the patch?

**Comment by auroraanna** [comment]
Or is it already fixed upstream and the package just needs to be updated?

**Comment by x10an14** [comment]
> Or is it already fixed upstream and the package just needs to be updated?

This is what's happening =)

**Comment by terlar** [comment]
Yes, unfortunately there has been no new release since the fix:
![Screenshot from 2022-09-13 09-30-28](https://user-images.githubusercontent.com/280235/189838682-641d3e34-ea8a-4996-956e-e3c1c2747173.png)

So in the meantime I guess the best fix would be to add the patch to the nixpkgs gnupg package. Anyone could create a PR adding the patch to nixpkgs, I think that would be a justified patch to include. I haven't personally gotten around to it yet.

**Comment by auroraanna** [comment]
> 

Well, I can't create signed commits right now unless I make a new key just for that commit.

**Comment by mweinelt** [comment]
Works again on nixos-unstable.
