### ISSUE TITLE
binutils conflicts with itself (due to .dev output)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#18839]
## Issue description

So it cannot be installed:

```
$ nix-env -iA nixos.binutils
installing ‘binutils-2.27’
building path(s) ‘/nix/store/g6iksgvyza9470w1rsvk2mhxkk747cp0-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/xank34knz9h7351m1km1x4bz4p8l1x46-binutils-2.27/bin/addr2line’ and ‘/nix/store/nqdk6dzwwhrq63gmiy4hm473z51yxcan-binutils-2.27-dev/bin/addr2line’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/idd9rbr78x1i0kipk5qvf6ylq85f5jlk-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/idd9rbr78x1i0kipk5qvf6ylq85f5jlk-user-environment.drv’ failed
```
## Technical details
- System: NixOS 16.09

**Comment by dezgeg** [comment]
Is that an old nix? I think the newer ones have the logic to install only relevant outputs. I don't know if that code is only on master though.

**Comment by bjornfor** [comment]
It's the default Nix on NixOS 16.09 (as of a couple of days old, c02b9b93f6bff1dcebdb7b7148e405aec6e5df66):

```
$ nix-env --version
nix-env (Nix) 1.11.4
```

**Comment by dezgeg** [comment]
Hm, damn. I guess the workaround in the meantime is to install `binutils.out`.

**Comment by bjornfor** [comment]
@dezgeg: Does that work for you? I get

```
$ nix-env -iA nixos.binutils.out
installing ‘binutils-2.27’
building path(s) ‘/nix/store/a08pjik14zzdf7qifc9n5vnzxgm1l113-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/nm9r5lymydnsrlxjn30ym2kix6mbyr19-binutils-2.27/bin/addr2line’ and ‘/nix/store/37hyhsfqz2wdd6gi9ns7c5h7f6gsnxbm-binutils-2.27-dev/bin/addr2line’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/f5yxclwyfpdskpg7h6y8ismab5qqzdqn-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/f5yxclwyfpdskpg7h6y8ismab5qqzdqn-user-environment.drv’ failed
```

**Comment by dezgeg** [comment]
D'oh, I forgot that it doesn't actually work...

**Comment by LnL7** [comment]
Why does the dev output have binaries, those should only be in the `out` output.

**Comment by dezgeg** [comment]
It has a symlink `${binutils.dev}/bin` -> `${binutils.out}/bin`, probably that could be removed if anything that depends on is fixed.

**Comment by LnL7** [comment]
A quick grep seems to indicate that the dev output is only used for include paths `${binutils.dev}/include`

**Comment by manpages** [comment]
I'll just throw it in, in case it's not obvious for someone — a nasty workaround is to put some symlinks into your `~/.local/bin` directory. On my machine, the following command does it:

```
cd ~/.local/bin
for x in /nix/store/dxmcix1wv08fad29nmwh07y3hjply7y3-binutils-2.27-dev/bin/*; do ln -s $x $(basename $x); done
```

**Comment by vcunat** [comment]
I somehow missed this.  I believe the symlink is useless, especially now that we have `binutils.out` as the default.
