### ISSUE TITLE
GNOME Frog cannot launch

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#188331]
### Describe the bug
`gnome-frog` crashes, even when installed into the system.

### Steps To Reproduce
1. nix shell "nixpkgs#gnome-frog" -c frog

### Expected behavior
Program doesn’t crash

### Notify maintainers
@foo-dogsquared

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.2, NixOS, 22.11 (Raccoon), 22.11.20220824.f034b56`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos, nixpkgs"`
 - channels(anselmschueler): `""`
 - nixpkgs: `/nix/store/nzjbgdb2air9pq73qrqz9m5bs5zchm50-source`
```

**Comment by foo-dogsquared** [comment]
Interestingly, I was able to build and run the app in commit f034b56 (I also rebuild it with `nix build --rebuild` just to double check).

![image](https://user-images.githubusercontent.com/34962634/186888062-9ffbd7aa-e87e-4171-bf94-93bf89fe8415.png)

Though, it does fail to build and run in recent revisions (at least in 2ae8a945fb63714db951c4304135601cc18fd261). It needs to apply #186056 to be able to build. Running it however gives me the following error:

```
Traceback (most recent call last):
  File "/nix/store/dbj4kjghs1gbgr39c1wbrg0fkak08b4h-gnome-frog-1.1.3/bin/.frog-wrapped", line 61, in <module>
    sys.exit(main.main(VERSION))
  File "/nix/store/dbj4kjghs1gbgr39c1wbrg0fkak08b4h-gnome-frog-1.1.3/lib/python3.10/site-packages/frog/main.py", line 185, in main
    app = Application(version)
  File "/nix/store/dbj4kjghs1gbgr39c1wbrg0fkak08b4h-gnome-frog-1.1.3/lib/python3.10/site-packages/frog/main.py", line 53, in __init__
    super().__init__(application_id='com.github.tenderowl.frog',
TypeError: gobject `frog+main+Application' doesn't support property `application_id'
```

Not exactly familiar with GTK development but I'll see what I can do. Thank you for reporting!

**Comment by OPNA2608** [comment]
Running it on my end gives me another error:

```
bt1cn@NixTop:~
↪ nix-shell -I nixpkgs=channel:nixos-unstable -p gnome-frog

[nix-shell:~]$ frog
Traceback (most recent call last):
  File "/nix/store/wwnp7r7k7rbwlc2vjp59x2cgwzi3mvy5-gnome-frog-1.1.3/bin/.frog-wrapped", line 60, in <module>
    from frog import main
  File "/nix/store/wwnp7r7k7rbwlc2vjp59x2cgwzi3mvy5-gnome-frog-1.1.3/lib/python3.10/site-packages/frog/main.py", line 34, in <module>
    gi.require_version('Gtk', '4.0')
  File "/nix/store/6vcggmcwn0azvl6wnzls678m3ipapca4-python3.10-pygobject-3.42.2/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by jtojnar** [comment]
``TypeError: gobject `frog+main+Application' doesn't support property `application_id'`` looks like a typelib compiled against an incompatible glib version being loaded or something. Probably because `gobject-introspection` is incorrectly put in `buildInputs` instead of `nativeBuildInputs`, which breaks the setup hooks and results in `wrapGAppsHook` not adding `GI_TYPELIB_PATH` and typelibs being picked up from the environment.

**Comment by foo-dogsquared** [comment]
Thank you for the explanation, @jtojnar . Simply putting `gobject-introspection` into `nativeBuildInputs` did build and run the app (at least in the recent commits).
