### ISSUE TITLE
Gitea service uses wrong config file

### ISSUE THREAD

**Issue by cofob** [NixOS/nixpkgs#188461]
### Describe the bug
The service tries to find the config in the nix store (`/nix/store/hfpbw4ylk29bm0fqf7nbw6alwmy2z216-gitea-1.16.9/bin/custom/conf/app.ini`), but it actually exists in `/var/lib/gitea/custom/conf/app.ini`

### Steps To Reproduce
1. Enable gitea service
```nix
services.gitea = {
  enable = true;
};
```
2. Check `gitea.service` unit status

### Expected behavior
Use the correct config file.

### Additional context
The error can be corrected by adding the `-c` flag, in all `gitea` [commands](https://github.com/NixOS/nixpkgs/blob/6039648c50c7c0858b5e506c6298773a98e0f066/nixos/modules/services/misc/gitea.nix#L546).

```console
❯ gitea -h
..skipped..
DEFAULT CONFIGURATION:
     CustomPath:  /nix/store/hfpbw4ylk29bm0fqf7nbw6alwmy2z216-gitea-1.16.9/bin/custom 
     CustomConf:  /nix/store/hfpbw4ylk29bm0fqf7nbw6alwmy2z216-gitea-1.16.9/bin/custom/conf/app.ini
     AppPath:     /nix/store/hfpbw4ylk29bm0fqf7nbw6alwmy2z216-gitea-1.16.9/bin/gitea
     AppWorkPath: /nix/store/hfpbw4ylk29bm0fqf7nbw6alwmy2z216-gitea-1.16.9/bin
```

### Notify maintainers
@aanderse @pennae @Izorkin @dasJ @etu

### Metadata
```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.59, NixOS, 22.05 (Quokka), 22.05.20220814.8791216`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cofob** [comment]
I tried to run it on another machine - everything works there. Closing.

**Comment by Izorkin** [comment]
https://github.com/NixOS/nixpkgs/issues/94751 - not the same case?

**Comment by cofob** [comment]
> #94751 - not the same case?

No, in this case gitea did not start at all.
