### ISSUE TITLE
mesa_noglu.drivers closure size increase

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#18840]
## Issue description

The LLVM package in the closure of `mesa_noglu.drivers` has increased dramatically from 16.03 to 16.09, from 77 MiB to 194 MiB:
```
# 16.03
$ nix path-info -rs $(nix-build -A mesa_noglu.drivers) | grep llvm
/nix/store/cyr7nnpp7wvz121ig7mpnvcn8qq3hl18-llvm-3.7.1                     80634520

# 16.09
$ nix path-info -rs $(nix-build -A mesa_noglu.drivers) | grep llvm
/nix/store/xdjw917wvykbjp6ymxj3mn7fhj1fl3xr-llvm-3.9.0                    204421320
```

In fact `llvm` is the biggest package in my 16.09 system closure.

In 16.03, the `llvm` package only contained .so libraries, but now it also includes static libraries (109 MiB).  Maybe these should be moved to a `dev` output, or removed altogether (if we're not using the static libraries anywhere)?

Ping @vcunat. Do you know if there is any obstacle to splitting `llvm` into multiple outputs?

**Comment by vcunat** [comment]
Hmm, yes, I completely forgot about that when switching mesa's llvm, even though there were long discussion about closure size https://github.com/NixOS/nixpkgs/pull/12759.

**Comment by vcunat** [comment]
> Do you know if there is any obstacle to splitting llvm into multiple outputs?

It seems the only viable way. I see no switch in LLVM to specify the output (like all autotool-based packages have), so it will be more complex. Let me have a look...

**Comment by vcunat** [comment]
Hmm, this is rather hard. For example, mesa uses ``LLVM_LIBDIR=`$LLVM_CONFIG --libdir```, i.e. it doesn't indicate that it wants to use shared libraries. Maybe we should make the shared mode default.

**Comment by vcunat** [comment]
Staged d2965a7d8.

**Comment by edolstra** [comment]
Thanks! Testing on my 16.09 branch...
