### ISSUE TITLE
gnupg1compat needs a meta description

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18843]
The [meta](https://github.com/NixOS/nixpkgs/blob/f081a1aaf4ec30f953c8c68ce1be9f687179d4e5/pkgs/tools/security/gnupg/1compat.nix#L21-L23) info for gnupg1compat is pretty sparse; I can't tell what this package is for.

Well, I guess by reading the build script, I can tell.

I am confused about why the package name is "1compat", though. It seems like it ought to have "2" in the name, since what it does is set up the gpg command to point to version 2, and version 1 is not involved at all?

**Comment by Profpatsch** [comment]
ping maintainers @wkennington @fpletz @peti @vrthra

**Comment by peti** [comment]
This has been fixed a while ago.
