### ISSUE TITLE
GNOME Control Center dies on clicking "View and Customize Shortcuts"

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#188404]
### Describe the bug
After clicking "View and Customize Shortcuts", Control Center dies. The following error can be seen if launched in terminal:

```console
(gnome-control-center:39317): GLib-GIO-ERROR **: 22:53:41.107: Settings schema 'org.gnome.GPaste' is not installed
```

### Steps To Reproduce
1. Launch `gnome-control-center` in terminal
2. Go to keyboard settings
3. Click "View and Customize Shortcuts"

### Expected behavior
The shortcut setting interface should appear.

### Additional context
I've set `programs.gpaste.enable = true` in my NixOS configuration. The error is likely to be related to GPaste, but GPaste works without issues for me so far. 

### Notify maintainers

@bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.62, NixOS, 22.11 (Raccoon), 22.11pre403473.b784c5ae63d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(yes): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jtojnar** [comment]
This is a known issue, you need to install GPaste through `programs.gpaste.enable` NixOS option.

**Comment by SamLukeYes** [comment]
> This is a known issue, you need to install GPaste through `programs.gpaste.enable` NixOS option. 

This is exactly what I have done before I encounter the issue.

**Comment by jtojnar** [comment]
Sorry, on the phone and missed that. Also forgot to mention you need to re-log in since the module sets new environment variables.

**Comment by SamLukeYes** [comment]
> Sorry, on the phone and missed that. Also forgot to mention you need to re-log in since the module sets new environment variables.

Actually, I've set `programs.gpaste.enable = true` [when I installed NixOS](https://github.com/SamLukeYes/nixos/blob/5f9781231e74497ac34e430cdd4022082be26e14/programs.nix#L10) and reboot my system every day, but still found the issue yesterday :confused:

**Comment by jtojnar** [comment]
What terminal emulator and shell do you use? It sounds like it doesn't inherit the environment set by PAM.

**Comment by SamLukeYes** [comment]
> What terminal emulator and shell do you use? It sounds like it doesn't inherit the environment set by PAM.

I'm using gnome-console as default terminal and xonsh as login shell.

**Comment by milachew** [comment]
Are you sure the problem still exists?
On my configuration, it doesn't exist.

NixOS 22.11, Linux 5.15.93, has installed from graphical installation.

On _configuration.nix_ I have deleted all `i18n` lines, left only `i18n.supportedLocales` which set to `"all"`.

![изображение](https://user-images.githubusercontent.com/113530911/221405654-95087237-1ad7-43c9-bb53-bf3749596d88.png)

**Comment by jtojnar** [comment]
It will only happen when you have shortcut extensions such as GPaste installed (and not added to `sessionPath`).

**Comment by Abdillah** [comment]
Then, this is likely due to different shell other than bash issue, right?
I use Nushell and encountered it as well.

**Comment by SamLukeYes** [comment]
![图片](https://github.com/NixOS/nixpkgs/assets/12882091/0cad2b70-765b-413e-b522-26ccfd2962c8)
The issue is now gone for xonsh.
