### ISSUE TITLE
lib.optionalString should accept null in addition to booleans

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#18841]
the pattern of `optionalString (cfg.localAddress != null)`

as used in b9df84cd4f6b70bdfa395a91dbf3d712adc7e18d
seems repetive

i believe null should be accepted just as true/false are

**Comment by domenkozar** [comment]
This becomes an overloaded term if you're checking for an option that has a boolean value but no default.

**Comment by RonnyPfannschmidt** [comment]
True
