### ISSUE TITLE
kitty, discord and possibly more not rendering on x11 with dwm

### ISSUE THREAD

**Issue by con-f-use** [NixOS/nixpkgs#188494]
### Describe the bug
I'm on the latest [nixos-unstable](https://github.com/NixOS/nixpkgs/commit/b784c5ae63dd288375af1b4d37b8a27dd8061887) using lightdm with dwm on xserver. A couple of programs do not redraw/update except when I manually resize the window.

As far as I can tell, these include:
 - [Discord](https://github.com/NixOS/nixpkgs/tree/b784c5ae63dd288375af1b4d37b8a27dd8061887/pkgs/applications/networking/instant-messengers/discord)
 - [Kitty](https://github.com/NixOS/nixpkgs/tree/b784c5ae63dd288375af1b4d37b8a27dd8061887/pkgs/applications/terminal-emulators/kitty)
 - Alacritty
 - Kdenlive
 - Possibly more

All make heavy use of GL.

### Video
[clip.webm](https://user-images.githubusercontent.com/11145016/187030173-fa4dd4ca-eeae-409e-80cf-fc964b215416.webm)

### Expected behavior
Interaction with UI elements inside the window cause visible changes and render.

### Update
Problem seems not to occur with "modsetting" xserver video driver.

### Notify maintainers
 - kitty: @tex @rvolosatovs @Luflosi
 - dwm @viric @neonfuz
Although it's probably an underlying issue with packaging of xserver, opengl or some framework that kitty, discord and whatever else have in common.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.3, NixOS, 22.11 (Raccoon), 22.11.20220824.b784c5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(jan): `""`
 - channels(root): `"nixos, nixos_22_05-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Nevermind the channel, it's a flake installation. At first I thought it was a [kitty issue](https://github.com/kovidgoyal/kitty/issues/5418), but then I realized it happens with Discord, too.

**Comment by con-f-use** [comment]
Not sure which maintainers I should ping here @SuperSandro2000

**Comment by neonfuz** [comment]
I'm only a maintainer because I added a feature back to DWM and they wanted me to be a maintainer. I use  NixOS stable + DWM so I can't test this easily.

**Comment by wentasah** [comment]
I tried to reproduce it in a VM, but without success.

My `configuration.nix` was:
```nix
{config, pkgs, ...}: {
  users.users.root.initialPassword = "root";

  services.xserver.enable = true;
  services.xserver.windowManager.dwm.enable = true;
  environment.systemPackages = with pkgs; [kitty dmenu];

  boot.kernelPackages = pkgs.linuxPackages_5_19;

  documentation.nixos.enable = false;
  services.openssh.enable = true;
}
```
Then I run:
```sh
NIXOS_CONFIG=$PWD/configuration.nix nixos-rebuild build-vm --no-flake
./result/bin/run-nixos-vm
```
It might be that the behavior depends on graphics drivers or other setup. @con-f-use Are you able to reproduce it if you run your config in a VM? Does it happen, if you run the above config on your hardware? Maybe, you can use [specialisations](https://www.tweag.io/blog/2022-08-18-nixos-specialisations/) to easily test different configurations.

**Comment by con-f-use** [comment]
Problem occurs on my [framework](https://frame.work) laptop with 12th gen cpu + graphics.

I'll try to find a minimal configuration that reproduces the bug once I have time.

**Comment by con-f-use** [comment]
Okay so an update: the framework laptop uses intel on-board graphics, which seem to have problems at the moment (e.g. requiring a [gpu hang workaround](https://github.com/NixOS/nixos-hardware/blob/master/framework/12th-gen-intel/default.nix#L17)).

My problem was that I had:

```nix
services.xserver.videoDrivers = ["intel"];  # works with "modsetting"
```

when it works with "motstetting" **instead** of "intel". I have no idea why or what exactly they even do. Maybe somebody can explain.

**Comment by wentasah** [comment]
I think that the `intel` driver is more or less deprecated these days. Years ago, switching from `intel` to `modesetting` solved many problems for me. Some information with links to relevant sources about deprecation can be found in [Arch wiki](https://wiki.archlinux.org/title/Intel_graphics#Installation) (in the blue *Note* box).
