### ISSUE TITLE
llpp fails to build

### ISSUE THREAD

**Issue by cafkafk** [NixOS/nixpkgs#188525]
Thanks in advance for your time and contributions.

### Steps To Reproduce
1. build llpp

### Build log
https://gist.github.com/cafkafk/1b4e101d45b71d6ca81f96402b7a90ce

### Additional context
Updated system and all packages today.

### Notify maintainers
@pSub 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.3, NixOS, 22.11 (Raccoon), 22.11.20220824.b784c5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixos"`
 - channels(ces): `"nixos"`
 - nixpkgs: `/nix/store/06gmb4plrmlcmqz82xfv77pzwdaixp3h-source`

**Comment by cafkafk** [comment]
Started work on this in #189538

**Comment by cafkafk** [comment]
As stated in that PR
> NOTICE: Recent upstream commits (after v35) deleted everything
and replaced it with various files (including videos and such).
> https://repo.or.cz/llpp.git/shortlog

So I might fork the project instead to avoid future instability.

**Comment by tg-x** [comment]
or remove it entirely since it appears to be unmaintained?

**Comment by pSub** [comment]
I have contacted the owner and last commiter of the llpp repository and asked them about the current state of the repository and future plans.

**Comment by pSub** [comment]
For the I `moosotc@gmail.com` received `The email account that you tried to reach does not exist.` from the mail server. Maybe the owner / project was hacked?

Arch uses the fork https://github.com/criticic/llpp. I haven't check if this state builds successfully.

**Comment by pSub** [comment]
Response from clamky@hotmail.com:
> I had/ve plans, back in february have decided not to code as long as RF
> wages a war. I have no control over or.cz, i still can push (my ssh key
> is intact) but have no means of changing anything else (html and such).

**Comment by TLATER** [comment]
The package should probably be marked as broken at least, at this point.

**Comment by cafkafk** [comment]
Seems like llpp is back in working order
