### ISSUE TITLE
Put fonts into their own namespace

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#18855]
In the discussion on #18775 we touched on the possibility of putting fonts into their own set - for example, the top-level package `inconsolata` instead becomes `fonts.inconsolata`. I think it would make it easier to search for fonts, and might be nice to clean up the top-level namespace a little (we have a lot of font packages, and there are plenty more out there that could be added - I wouldn't be surprised if some names conflict with software names).

**Comment by rycee** [comment]
Yes please, I would very much like to see such a change and would be willing to do it if nobody else feels inspired.

**Comment by chris-martin** [comment]
@rycee I felt inspired.

**Comment by Profpatsch** [comment]
Closing, since the PR didn’t work out.
