### ISSUE TITLE
example value for fileSystems is incorrect

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#18865]
Search for "fileSystems" in https://nixos.org/nixos/options.html

The example value is `{ / = { device = "/dev/hda1"; }; /bigdisk = { label = "bigdisk"; }; /data = { device = "/dev/hda2"; fsType = "ext3"; options = [ "data=journal" ]; }; }`

However a path cannot be used as an attribute name which means the above is a syntax error.

**Comment by danbst** [comment]
Example value is OK, just look at https://github.com/NixOS/nixpkgs/blob/release-16.03/nixos/modules/tasks/filesystems.nix#L115

You should better report issue to https://github.com/NixOS/nixos-homepage . I've noticed that option generation changed some weeks ago, now examples are oneliners... I don't know who to ping, maybe @domenkozar @edolstra ?

**Comment by joachifm** [comment]
I agree this belongs somewhere else.
