### ISSUE TITLE
package noto-fonts-cjk-sans not installable

### ISSUE THREAD

**Issue by clayt0nk** [NixOS/nixpkgs#188602]
### Describe the bug
All attempts to install this package error out

### Steps To Reproduce

nix-env -iA nixos.noto-fonts-cjk-sans
error: attribute 'noto-fonts-cjk-sans' in selection path
'nixos.noto-fonts-cjk-sans' not found

### Expected behavior
Package should install per the instructions on
https://search.nixos.org/packages?channel=22.05&show=noto-fonts-cjk-sans&from=0&size=50&sort=relevance&type=packages&query=cjk

### Additional context
Trying to install in configuration.txt fails in the same way.

### Notify maintainers
Mathnerd314 <mathnerd314.gph+hs@gmail.com>
Emily <nixpkgs@emily.moe>

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.126, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337973.511f6a5c324"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
same as above
```

**Comment by SamLukeYes** [comment]
NixOS 21.11 is EOL. The instructions you followed is for 22.05.

To upgrade NixOS, see https://nixos.org/manual/nixos/unstable/index.html#sec-upgrading

**Comment by clayt0nk** [comment]
Spot on, thanks, that fixed it. As a new NixOS user I was somehow under the impression that NixOS was a rolling distribution. I stand corrected.....

**Comment by SamLukeYes** [comment]
> Spot on, thanks, that fixed it. As a new NixOS user I was somehow under the impression that NixOS was a rolling distribution. I stand corrected.....

There are also rolling channels, e.g. `nixos-unstable`. See [differences between nix channels](https://discourse.nixos.org/t/differences-between-nix-channels/13998).
