### ISSUE TITLE
nextcloud configuration outdated

### ISSUE THREAD

**Issue by litchipi** [NixOS/nixpkgs#188654]
### Describe the bug
The configuration `dbport` is ignored by `nextcloud` when setting up the database as it is a configuration no longer used in the latest versions of `nextcloud`
See https://github.com/nextcloud/server/issues/12979

### Steps To Reproduce
1. Set up "dbhost" to "/run/postgresql", and "dbport" to anything else than 5432 (default pgsql port), let's say 5435 for example
2. nextcloud-setup.service will fail saying the file `/run/postgresql/.s.PGSQL.5435` is not found

### Expected behavior
In `config.php`, the value `dbhost` should be set as `host:port` instead, any `dbport` field is ignored (and should then be deleted)

### Notify maintainers
@risicle 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.43, NixOS, 22.05 (Quokka), 22.05.20220530.ce6aa13`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
FYI @revol-xut @Ma27
