### ISSUE TITLE
Package Request: linx-server

### ISSUE THREAD

**Issue by YHNdnzj** [NixOS/nixpkgs#188667]
**Project description**
Self-hosted file/code/media sharing website.

**Metadata**

* homepage URL: https://put.icu
* source URL: https://github.com/ZizzyDizzyMC/linx-server
* license: GPLv3
* platforms: Linux

**Comment by urandom2** [comment]
to confirm you are keen on getting the fork, not original tool packaged: https://github.com/andreimarcu/linx-server

**Comment by YHNdnzj** [comment]
> to confirm you are keen on getting the fork, not original tool packaged: https://github.com/andreimarcu/linx-server

Yes.
