### ISSUE TITLE
chrome-gnome-shell 10.1 -> gnome-browser-connector 42.0

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#188746]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 10.1
desired version: 42.0

Upsteam has renamed `chrome-gnome-shell` to `gnome-browser-connector`.
See https://wiki.gnome.org/action/show/Projects/GnomeShellIntegration/Installation

###### Notify maintainers

maintainers: @bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by bobby285271** [comment]
Currently part of #182618.

**Comment by bobby285271** [comment]
Done in https://github.com/NixOS/nixpkgs/commit/50c6895e772b76a9bb5d7be7158a60ea1fb02bea
