### ISSUE TITLE
Drop JDK 1.6 and 1.7

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#18878]
## Issue description

Oracle's JDK for 1.6 and 1.7 is no longer receiving public security updates. We should probably drop them from nixpkgs.

Reference:

 - https://github.com/NixOS/nixpkgs/issues/18856#issuecomment-249193199
 - https://github.com/NixOS/nixpkgs/issues/18856#issuecomment-249179789

**Comment by danbst** [comment]
Hm, maybe better would be to add flag `meta.upstreamMaintained = false` to indicate, that nobody is interested in adding fixes to this version. It is still inconvenient to pin nixpkgs to get needed package.

**Comment by joachifm** [comment]
Software that is known or likely to be vulnerable *should* be inconvenient to use, imo.

**Comment by NeQuissimus** [comment]
Maybe similar to how we have `goPackages` and `nodePackages`, have an `unmaintainedPackages`, so that you have to qualify you want one of those? That would also cut down on the size of the list of packages in all-packages :)

**Comment by grahamc** [comment]
Done with:

https://github.com/NixOS/nixpkgs/pull/19057 and https://github.com/NixOS/nixpkgs/pull/19056 and oracledk6's PR above.
