### ISSUE TITLE
SDL2: 2.0.22 -> 2.24.0

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#188794]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: SDL2

current version: 2.0.22
desired version: 2.24.0

###### Notify maintainers

maintainers: @cpages 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by siph** [comment]
Can this be closed?

**Comment by SuperSamus** [comment]
Yes, I forgot.
