### ISSUE TITLE
newlib fails to cross-compile for arm-embedded

### ISSUE THREAD

**Issue by rndmono** [NixOS/nixpkgs#188817]
### Steps To Reproduce
1. `nix build nixpkgs#pkgsCross.arm-embedded.buildPackages.newlib`

### Build log
I believe the relevant errors are
```
[...]
/nix/store/1b9p07z77phvv2hf6gm9f28syp39f1ag-bash-5.1-p16/bin/bash: line 1: arm-none-eabi-cc: command not found
[...]
/nix/store/1b9p07z77phvv2hf6gm9f28syp39f1ag-bash-5.1-p16/bin/bash: line 3: arm-none-eabi-ar: command not found
[...]
```
full output here: https://gist.github.com/rndmono/b18bee838ef7e497dd17b1672ef72f87

### Notify maintainers
@Ericson2314 @matthewbauer 

## Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.05 (Quokka), 22.05.2764.0ba2543f8c8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-hardware, nixos-unstable"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by quapka** [comment]
I had the same issue and was told (on NixOS Matrix) to either omit `.buildPackages` or use `.__splicedPackages`.

```bash
$ nix build nixpkgs#pkgsCross.arm-embedded.__splicedPackages.newlib
$ nix build nixpkgs#pkgsCross.arm-embedded.newlib
```

Both of the above commands finish successfully on 22.11.

**Comment by rndmono** [comment]
> I had the same issue and was told (on NixOS Matrix) to either omit `.buildPackages` or use `.__splicedPackages`.
> 
> ```shell
> $ nix build nixpkgs#pkgsCross.arm-embedded.__splicedPackages.newlib
> $ nix build nixpkgs#pkgsCross.arm-embedded.newlib
> ```
> 
> Both of the above commands finish successfully on 22.11.

Thank you! I can confirm that this still works on 23.05.

**Comment by Avimitin** [comment]
> ... and was told (on NixOS Matrix) to either omit `.buildPackages` or use `.__splicedPackages`.

Do you know why adding sub attrs `buildPackages` will cause this failure?
