### ISSUE TITLE
sane-backends fails to cross-compile on aarch64

### ISSUE THREAD

**Issue by yvesf** [NixOS/nixpkgs#188858]
### Steps To Reproduce
1. `nix build nixpkgs#pkgsCross.aarch64-multiplatform.sane-backends`

### Build log
(this is the first error, the sane-desc problem would appear later in the build if we skip pieusb by setting BACKENDS=genesys for example).
```
pieusb_buffer.c: In function 'sanei_pieusb_buffer_create':
pieusb_buffer.c:201:2: error: #error mmap(2) not available, aborting
  201 | #error mmap(2) not available, aborting
      |  ^~~~~
pieusb_buffer.c: In function 'sanei_pieusb_buffer_delete':
pieusb_buffer.c:241:2: error: #error mmap(2) not available, aborting
  241 | #error mmap(2) not available, aborting
      |  ^~~~~
rm -f ricoh2-s.c
```

### Additional context
The `sane-desc` tool executed during the build procedure in `postInstall` is built for the target architecture, not for the build machine architecture.

The `pieusb` backend of sane uses autoconf's `HAVE_MMAP` which is never defined under cross-compilation (since it's checks the availability of the mmap syscall during the build-process on the build-machine). In consequence the build aborts.

### Metadata
```console
nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.132, NixOS, 22.05 (Quokka), 22.05.20220728.9370544`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(yvesf): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/189130
