### ISSUE TITLE
diesel-cli is out of date (1.4.1 -> 2.0.0)

### ISSUE THREAD

**Issue by PhotonQuantum** [NixOS/nixpkgs#188876]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `diesel-cli`

current version: 1.4.1
desired version: 2.0.0

###### Notify maintainers

maintainers: @ivan 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ivan** [comment]
It looks like I removed myself from diesel-cli maintainers on 2020-01-03 and it is currently unmaintained. I don't use diesel, so if you wish, you can add yourself to `nixpkgs/maintainers/maintainers-list.nix` and update diesel with yourself as the maintainer.

**Comment by ivan** [comment]
https://github.com/NixOS/nixpkgs/pull/189697

**Comment by superherointj** [comment]
@PhotonQuantum It is (usually) fairly straight forward to bump packages. Instead of opening an issue. You are much better bumping it (opening a PR) yourself. And also, as Ivan said, add yourself as maintainer when doing so.

**Comment by superherointj** [comment]
Closed by #189697

**Comment by PhotonQuantum** [comment]
> It is (usually) fairly straight forward to bump packages. Instead of opening an issue. You are much better bumping it (opening a PR) yourself.

Sorry for the inconvenience! I'm new to nix and was not familiar with the packaging workflow.

I'll open a PR next time. Thanks!

**Comment by superherointj** [comment]
> > It is (usually) fairly straight forward to bump packages. Instead of opening an issue. You are much better bumping it (opening a PR) yourself.
> 
> Sorry for the inconvenience! I'm new to nix and was not familiar with the packaging workflow.
> 
> I'll open a PR next time. Thanks!

No worry. We always help on PRs.
