### ISSUE TITLE
hardeningEnable and hardeningDisable not documented

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#18887]
There is the `Hardening in Nixpgs` section in the manual and both variables are listed, but it is not explained what types they are or what the semantics are (I first I thought `hardeningDisable = true;` would have an effect).

It gets worse because `mkDerivation` just forwards anything it gets and no error is thrown on wrong usage.

cc @globin @fpletz

**Comment by groxxda** [comment]
https://nixos.org/releases/nixpkgs/nixpkgs-16.09pre90369.202d9e2/manual/#sec-hardening-in-nixpkgs describes the flags
Do you mean it should be mentioned that both take a `list` ?

**Comment by Profpatsch** [comment]
Yes. And what they do exactly (why there’s two). It seemed to me like `hardeningEnable = []` doesn’t actually disable all flags (what I expected).

**Comment by fpletz** [comment]
`hardeningEnable` just enables optional hardening flags. To disable all hardening, there's a special `"all"` flag. That's indeed undocumented and should be fixed.

This would disable all hardening: `hardeningDisable = [ "all" ]`.
