### ISSUE TITLE
Having a swap file delays boot by 20 seconds

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#18891]
## Issue description
If a configured swapDevice is a file (instead of a partition), NixOS stage-1 waits for the device for up to 20 seconds, then times out and continues the boot:

```
$ journalctl -b
[...]
Sep 23 21:28:32 whitetip stage-1-init: waiting for device /var/swapfile to appear.......................
```

(Each '.' after the first three represents one second. In total it waits 20 seconds.)

I think the problem is related to resumeDevices, which, unless configured by the user, defaults to using swapDevice as resume device. And, AFAICT, dealing with resume devices is done before the root filesystem is mounted. So it is obvious that a swapfile in the rootfs isn't found.

### Steps to reproduce
```
  swapDevices = [
    { device = "/var/swapfile";
      size = 8192; # MiB
    }
  ];
```

Reboot and see ``` stage-1-init: waiting for device /var/swapfile to appear...``` for 20 seconds.

## Technical details
* System: NixOS 16.09

**Comment by bjornfor** [comment]
Maybe it's enough to add a check for ```.size``` in where the resumeDevices list is is built:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/stage-1.nix#L200-L203

**Comment by bjornfor** [comment]
This patch does fix it for me:

```patch
diff --git a/nixos/modules/system/boot/stage-1.nix b/nixos/modules/system/boot/stage-1.nix
index 513c121..ca3c757 100644
--- a/nixos/modules/system/boot/stage-1.nix
+++ b/nixos/modules/system/boot/stage-1.nix
@@ -200,7 +200,9 @@ let
     resumeDevices = map (sd: if sd ? device then sd.device else "/dev/disk/by-label/${sd.label}")
                     (filter (sd: (sd ? label || hasPrefix "/dev/" sd.device) && !sd.randomEncryption 
                     # Don't include zram devices
-                    && !(hasPrefix "/dev/zram" sd.device)) config.swapDevices);
+                    && !(hasPrefix "/dev/zram" sd.device)
+                    # Don't include swap _files_
+                    && !(sd ? size)) config.swapDevices);
 
     fsInfo =
       let f = fs: [ fs.mountPoint (if fs.device != null then fs.device else "/dev/disk/by-label/${fs.label}") fs.fsType (builtins.concatStringsSep "," fs.options) ];
```

**Comment by bjornfor** [comment]
@abbradar: Thanks! Backport to stable immediately, or wait a few days?

**Comment by abbradar** [comment]
I did it already since the fix seems very straightforward (even if it's invalid the check is still redundant).
