### ISSUE TITLE
qt6: darwin / macOS support

### ISSUE THREAD

**Issue by arximboldi** [NixOS/nixpkgs#188938]
**Project description**

Qt6 has been out for a while. It is particularly important for Mac, as Qt5 does not support M1/2 processors, but Qt6 does.

Qt6 has been in `nixpkgs` already for a few months, but `darwin` support is lacking.

I imagine this is a very non-trivial project. I would be happy to set up a bountie or hire someone to do this, please contact privately if you are interested.

**Comment by milahu** [comment]
> I would be happy to set up a bountie or hire someone to do this, please contact privately if you are interested.

talk is cheap. this reminds me of https://github.com/NixOS/nixpkgs/issues/108008#issuecomment-765390949 and https://github.com/NixOS/nixpkgs/issues/108008#issuecomment-1016443895

how about: keep your money, and find us a 32 core darwin build server

**Comment by arximboldi** [comment]
hi @milahu. I'm not sure I understand your comment. Are you saying that you need a MacOS machine to proceed with that work yourself?

I also don't understand what you are saying about cross-compile. The current definition only works for `linux`. It is marked as that in the `supportedPlatforms` and looking at the definition of the derivations, it depends on a lot of linux stuff unconditionally, and there are no bits for example that bring in the darwin frameworks, so I do not think it works at the moment on Darwin alone.

Not sure about the "talk is cheap" comment either. Do you mean that the offer is insincere? Or that I should just do the port myself? I would love to do it myself but I do not have the time, that is why I am offering money instead.

**Comment by veprbl** [comment]
> It is particularly important for Mac, as Qt5 does not support M1/2 processors, but Qt6 does.

Allegedly, we got Qt5 working. See #180327 and #186612.

**Comment by arximboldi** [comment]
Oh, interesting. Thanks @veprbl!

**Comment by boeyms** [comment]
@wegank @arximboldi Can this be closed as resolved in light of the merger of #202015?

**Comment by wegank** [comment]
Unless one wants to use Qt6 with qmake. #204724 targets this, but it doesn't seem to be enough, since PyQt can't be built without the hack in https://github.com/NixOS/nixpkgs/pull/202015#issuecomment-1326941691.
