### ISSUE TITLE
Semgrep - additional platform support

### ISSUE THREAD

**Issue by ck3mp3r** [NixOS/nixpkgs#188944]
@ambroisie is there anything stopping aarch64-darwin to be added as a supported architecture?

https://github.com/NixOS/nixpkgs/blob/a63021a330d8d33d862a8e29924b42d73037dd37/pkgs/tools/security/semgrep/common.nix#L56

**Comment by ambroisie** [comment]
@ck3mp3r if upstream packages it in its releases, sure.

`semgrep` is a chore to build from source due to their large amount of vendoring and using custom, non-tagged released versions of their dependencies. For now we simply make use of their static binary releases.

**Comment by ck3mp3r** [comment]
@ambroisie says on their release notes page "Semgrep installation through PyPi is now supported on Apple M1 processors!"
What binaries are they using there or is pip doing something on top of it?

**Comment by ambroisie** [comment]
```
$ file artifacts/semgrep-core 
artifacts/semgrep-core: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>
```

The `*-osx.zip` release is still only x86_64 only. You could open an issue upstream asking them to also add their aarch64 releases if you need them.

**Comment by ck3mp3r** [comment]
Just added this upstream request: https://github.com/returntocorp/semgrep/issues/6015

**Comment by Janik-Haag** [comment]
Since the pr is merged this can be closed, feel free to reopen if something is missing.
