### ISSUE TITLE
Quarto-cli

### ISSUE THREAD

**Issue by Kupac** [NixOS/nixpkgs#189017]
**Project description**
Quarto: an open-source scientific and technical publishing system

**Metadata**

* homepage URL: https://quarto.org/
* source URL: https://github.com/quarto-dev/quarto-cli
* license: gpl2+
* platforms: unix, linux, darwin, win?

**Comment by Kupac** [comment]
Sorry, just saw it's a duplicate

**Comment by milahu** [comment]
duplicate of #160911

@Kupac please close this issue
