### ISSUE TITLE
PrivateUserOwnership should be PrivateUsersOwnership in the systemd-nspawn module

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nixpkgs#189046]
### Describe the bug
According to [man pages](https://man.archlinux.org/man/systemd.nspawn.5#%5BFILES%5D_SECTION_OPTIONS), the name is `PrivateUsersOwnership`, not `PrivateUserOwnership`

The file in question:

https://github.com/NixOS/nixpkgs/blob/a63021a330d8d33d862a8e29924b42d73037dd37/nixos/modules/system/boot/systemd/nspawn.nix#L30

**Comment by ck3d** [comment]
Thanks for reporting the issue. I created a PR to fix it.
