### ISSUE TITLE
emacs lsp-bridge

### ISSUE THREAD

**Issue by SheetKey** [NixOS/nixpkgs#189022]
**Project description**
lsp-bridge is an lsp client for emacs.

**Metadata**

* homepage URL: https://github.com/manateelazycat/lsp-bridge
* source URL: https://github.com/manateelazycat/lsp-bridge
* license: 
* platforms: linux

**Comment by jian-lin** [comment]
Added in https://github.com/NixOS/nixpkgs/pull/219993
