### ISSUE TITLE
Jazz² Resurrection (run Jazz Jackrabbit 2)

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#189179]
**Project description**
Jazz² Resurrection is reimplementation of the game Jazz Jackrabbit 2 released in 1998.

**Metadata**

* homepage URL: http://deat.tk/jazz2/
* source URL: https://github.com/deathkiller/jazz2
* license: [gpl3](https://github.com/deathkiller/jazz2/blob/master/LICENSE)
* platforms: linux

**Comment by surfaceflinger** [comment]
bump, it's now in C++ and uses CMake. It might need patching to allow loading assets/content from directory like `.local/share/jazz2`.

**Comment by surfaceflinger** [comment]
:^) https://github.com/NixOS/nixpkgs/pull/212426

**Comment by revuwa** [comment]
> :^) #212426

Thank you so much for that ❤️
I enjoy the game currently, YAY!
