### ISSUE TITLE
kooha update available

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#189168]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: [kooha](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/video/kooha/default.nix)

current version: 2.0.1
desired version: [2.1.1](https://github.com/SeaDve/Kooha/releases/tag/v2.1.1)

###### Notify maintainers

maintainers:

@austinbutler 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by austinbutler** [comment]
Seems [`libadwaita` > 1.2 is required now](https://github.com/SeaDve/Kooha/issues/182), but that's [still just at RC stage](https://gitlab.gnome.org/GNOME/libadwaita/-/blob/24e143e90ec2c7c4de20a754883c37331eb7a38d/NEWS), so best to wait for 1.2 `libadwaita` release and upgrade in nixpkgs.

**Comment by austinbutler** [comment]
Got it to build locally with the RC in case you want to use that: https://github.com/austinbutler/nixpkgs/tree/kooha-2-1

**Comment by pbsds** [comment]
fixed in 
* #193793
