### ISSUE TITLE
Android SDK packages could contain JARs with sources

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#18918]
## Issue description

Currently, our Android SDK derivations contain only binary files. This is unfortunate during development, when one wants to jump to a definition of a particular symbol in the SDK and it is not found.

For comparison, ArchLinux is doing this in their `android-sources-##` packages, e.g. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=android-sources-16:

```bash
source=("http://dl-ssl.google.com/android/repository/sources-16_r02.zip")

mkdir -p "${pkgdir}/opt/android-sdk/sources/"
mv "${srcdir}/src" "${pkgdir}/opt/android-sdk/sources/android-16"
```

## Technical details

* System: 16.09pre-git (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09beta335.7617e7e"

---

/cc @svanderburg @taku0

**Comment by taku0** [comment]
Created PR #19385.
