### ISSUE TITLE
nixos-unstable channel vanished

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#18914]
## Issue description

There is no nixos-unstable channel in http://nixos.org/channels/ anymore.

**Comment by Mic92** [comment]
still a problem? I saw: "nixpkgs-unstable/	2016-09-23 18:45	-	 "

**Comment by vyp** [comment]
Is nixpkgs different from nixos?

**Comment by ericsagnes** [comment]
> Is nixpkgs different from nixos?

Yes it is, nixos include tests and nixpkgs includes some darwin builds.

- `nixos-*` channels expression: https://github.com/NixOS/nixpkgs/blob/master/nixos/release-combined.nix
- `nixpkgs-*` channels expression: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/release.nix

**Comment by rzetterberg** [comment]
It seems that the *channel symlink* to the latest `unstable` release is gone, it also seems that the actual `unstable` release that was created at `2016-09-23` is gone from the release folder, can only see an earlier release that was created at `2016-09-21`. 

Also seeing a deadlock error on hydra for trunk-combined: 

```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  deadlock detected
DETAIL:  Process 19543 waits for ShareLock on transaction 20589107; blocked by process 10826.
Process 10826 waits for ShareLock on transaction 20589096; blocked by process 19543.
HINT:  See server log for query details.
```

Maybe the latest release was removed accidentally and the channel symlink couldn't be created?

cc @edolstra

**Comment by d4g** [comment]
The issue still persists. Are there any news?

**Comment by joachifm** [comment]
cc @domenkozar @rbvermaa

**Comment by Yury-Zakharov** [comment]
The same issue:
nixos-rebuild switch --upgrade results in error:
unable to download ‘https://nixos.org/channels/nixos-unstable/nixexprs.tar.bz2’:

Is there any hope this to be fixed soon?

**Comment by tohl** [comment]
> The same issue:
> nixos-rebuild switch --upgrade results in error:
> unable to download
> ‘https://nixos.org/channels/nixos-unstable/nixexprs.tar.bz2’:

same issue here.  This blocks any nixos upgrade on unstable channel.

**Comment by edolstra** [comment]
Should work again.

**Comment by gpyh** [comment]
It does. Thank you very much!

**Comment by danbst** [comment]
still broken (at least in webUI) for 16.03 and unstable
https://nixos.org/channels/

I get "nix-channel compatibility placeholder" and link to https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.03pre92039.adfcc2d for unstable channel

**Comment by vcunat** [comment]
Well `nix-channel --update` seems to work fine on those placeholders.

**Comment by 8573** [comment]
I have `system.autoUpgrade` running nightly, yet my `nixos-version` seems to have been stuck at adfcc2d9531e78bf6a9e3b56e2f4fc873cb3d87b for multiple weeks. Does `system.autoUpgrade` do something different from `nix-channel --update` such that it wouldn't update?

**Comment by vcunat** [comment]
@8573: that *is* the latest nixos-unstable, unfortunately.
