### ISSUE TITLE
scilab package won't work

### ISSUE THREAD

**Issue by KKlochko** [NixOS/nixpkgs#189148]
### Describe the bug
I get this error:
error: Package ‘scilab-4.1.2’ in /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/applications/science/math/scilab/default.nix:62 is marked as broken, refusing to evaluate.

### Steps To Reproduce
1. nix-shell -p scilab

### Expected behavior
I expect to get the valid package.

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.05 (Quokka), 22.05.2583.00e376e3f3c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wegank** [comment]
scilab has been removed from nixpkgs in #175961. Use scilab-bin instead.
