### ISSUE TITLE
github-runner: wrong node directory

### ISSUE THREAD

**Issue by peperunas** [NixOS/nixpkgs#189104]
### Describe the bug
github-runner looks for `node` in the wrong directory.

This is the log from one of the actions on my CI system:

```
Error: An error occurred trying to start process '/nix/store/5xvlnqw5jbwf2l8s42vwgclgw1p2gfzd-github-runner-2.296.0/externals/node12/bin/node' with working directory '/run/github-runner/....'. No such file or directory
```

I inspected the derivation, and `externals/node12` should be replaced with `externals/node16`

**Comment by milahu** [comment]
https://github.com/NixOS/nixpkgs/blob/e50697278bf4ff7a1dfc30cbb44f17832d1d1250/pkgs/development/tools/continuous-integration/github-runner/default.nix#L249-L253

sounds like it needs both, node12 and node16

old node versions are needed for backward compatibility

**Comment by 573** [comment]
I also hit this, see [log](../../../573/nix-config-1/actions/runs/3151577186/jobs/5125700620#step:3:5)

**Comment by kirinnee** [comment]
I also hit this:
![image](https://user-images.githubusercontent.com/15990242/197674483-911179e0-e010-44c3-9ab7-2a0ce8e7654d.png)

**Comment by hlolli** [comment]
> Make sure you use version 3 or newer of the checkout (and other node based tools) https://github.com/actions/checkout.
> 
> For me upgrading to version 3 solved it.

you're a saint!

**Comment by veehaitch** [comment]
Closing this as Node 12 has been EoL for some time. Feel free to re-open if your issue is not resolved.

**Comment by cherusk** [comment]
Don't get it, what was the solution to this?
Happend to me on 23.05, runner version '2.304.0'.
So that's on latest ...
