### ISSUE TITLE
raze (run Build engine games like: Duke Nukem 3D, Blood, Redneck Rampage, Shadow Warrior, ...)

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#189163]
**Project description**
Raze is a fork of Build engine games backed by GZDoom tech and combines Duke Nukem 3D, Blood, Redneck Rampage, Shadow Warrior and Exhumed/Powerslave in a single package. It is also capable of playing Nam and WW2 GI.

**Metadata**

* homepage URL: https://raze.zdoom.org/about
* source URL: https://github.com/ZDoom/Raze
* wiki URL: https://zdoom.org/wiki/Raze
* license: non-build code: [gpl2](https://github.com/ZDoom/Raze#non-build-code-is-licensed-under-the-gpl-v2), build engine & tools: [license info](https://github.com/ZDoom/Raze/blob/master/build-doc/buildlic.txt)
* platforms: linux

The build instructions should be the same as for gzdoom, so I want to notify the maintainer of gzdoom @Lassulus if he/she is interested in this. 
Also I want to notify the maintainer of eduke32 @mikroskeem because this project could more or less replace eduke32(?)

**Comment by Lassulus** [comment]
I can take a look, but my current schedule is pretty full. maybe at the end of the year?
But if someone else is happy to do it, feel free and ping me on the PR

**Comment by mikroskeem** [comment]
Might take a look next week. EDuke32 replacement probably won't do, because iirc HRP runs only on it etc.

**Comment by revuwa** [comment]
Thank both of you to possibly have a look into this.

> EDuke32 replacement probably won't do, because iirc HRP runs only on it etc.

I think you're right. But I see that three projects:

- Enhanced Resource Pack
- Fixes for Duke Nukem 3D
- Duke!Zone II Fixed Release

of the [HRP DL site](https://hrp.duke4.net/download.php) got raze support, already. Possibly HRP will follow sometime...
