### ISSUE TITLE
Jetbrains IDEs with plugins?

### ISSUE THREAD

**Issue by GenericNerdyUsername** [NixOS/nixpkgs#189183]
**Project description**
I feel it would be beneficial for extensions to be in the store instead of/in addition to the regular mechanism. For example, #188488 adds a dependency which most people won't use, but is a pain to set up otherwise, and I doubt go is the only extension where this is the case.

I'm planning on doing this myself, but made this issue because I have other things to work on first.

**Comment by gbtb** [comment]
Considering plugins, I think we can look at what vscode packages do. There are 3 versions of them: without plugin support, with FHS environment which allows imperative installation of plugins, and fully declarative variant.

**Comment by GenericNerdyUsername** [comment]
so turns out theres just a `plugins` directory, and all you have to do is copy the .jar or extract the .zip in there

**Comment by gbtb** [comment]
If you're going to install plugins as separate derivations in the /nix/store, then symlinking is a better approach.
