### ISSUE TITLE
nix-shell runs old version

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#189221]
### Describe the bug

I have the latest unstable channel.

```
[root@gaming:~]# nix-channel --update nixos-unstable
unpacking channels...

[root@gaming:~]# nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'
"22.11pre405311.97747d3209e"
```

```
[davidak@gaming:~/code/pyzufall]$ nix-shell '<nixos-unstable>' -p scorecard --run "scorecard version"
         __  ____     ____    ___    ____    _____    ____      _      ____    ____
        / / / ___|   / ___|  / _ \  |  _ \  | ____|  / ___|    / \    |  _ \  |  _ \
       / /  \___ \  | |     | | | | | |_) | |  _|   | |       / _ \   | |_) | | | | |
  _   / /    ___) | | |___  | |_| | |  _ <  | |___  | |___   / ___ \  |  _ <  | |_| |
 (_) /_/    |____/   \____|  \___/  |_| \_\ |_____|  \____| /_/   \_\ |_| \_\ |____/
./scorecard: Security Scorecards

GitVersion:    v4.2.0
GitCommit:     44ad5f53ad75aa220fc16c1bd2ab3facdf4d69c1
GitTreeState:  clean
BuildDate:     2022-04-22T23:22:43Z
GoVersion:     go1.17.10
Compiler:      gc
Platform:      linux/amd64
```

the version should be 4.6.0 according to https://search.nixos.org/packages?channel=unstable&show=scorecard&from=0&size=50&sort=relevance&type=packages&query=scorecard

maybe i'm doing something obvious wrong and i don't see it because i'm too tired

or it could be that it is actually the right version, but the output is wrong (had that before with go programs). but it has a check for that which does not fail

`nix build -f "<nixos-unstable>" scorecard`

### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers
@06kellyjac

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.62, NixOS, 22.05 (Quokka), 22.05.2711.294ef54a1e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jk** [comment]
@davidak I'm not the maintainer

**Comment by davidak** [comment]
@jk sorry. your github username is listed here. maybe that's someone else https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/security/scorecard/default.nix#L75

**Comment by davidak** [comment]
@06kellyjac could you change your nixpkgs maintainer name to the github user name to prevent such confusion?

**Comment by 06kellyjac** [comment]
> @06kellyjac could you change your nixpkgs maintainer name to the github user name to prevent such confusion?

that's not a requirement of the nixpkgs maintainer list and I'm far from the only one. I kindly ask that you check the github attribute of the maintainer as that's what it's for.

```nix
> builtins.length (lib.filter (i: (lib.toLower i.n) != (lib.toLower i.gh)) (lib.mapAttrsToList (n: v: { inherit n; gh = v.github; }) lib.maintainers))
302
```

---

You can check that in much the same way that you check your channel version.

```bash
λ nix-instantiate --eval --strict -E "with import <nixos-unstable> {}; builtins.map (i: i.github) scorecard.meta.maintainers"
[ "06kellyjac" ]
```

or you can click this link on https://search.nixos.org

![image](https://user-images.githubusercontent.com/9866621/187862629-9b08c694-3491-4d6a-9fb3-2413ba10a42a.png)


---

On the topic of fixing your issue:

There is a line that checks the version is accurate (and version drift is a problem with building go programs) but it's actually commented out at the moment.
However it can only be what's set via ldflags which is `4.6.0` or the fallback of `devel`

I've also validated that the actual copy in nixos-unstable is accurate

```bash
λ nix run github:nixos/nixpkgs/nixos-unstable#scorecard version
         __  ____     ____    ___    ____    _____    ____      _      ____    ____
        / / / ___|   / ___|  / _ \  |  _ \  | ____|  / ___|    / \    |  _ \  |  _ \
       / /  \___ \  | |     | | | | | |_) | |  _|   | |       / _ \   | |_) | | | | |
  _   / /    ___) | | |___  | |_| | |  _ <  | |___  | |___   / ___ \  |  _ <  | |_| |
 (_) /_/    |____/   \____|  \___/  |_| \_\ |_____|  \____| /_/   \_\ |_| \_\ |____/
./scorecard: Security Scorecards

GitVersion:    v4.6.0
GitCommit:     2cbf5afd5460b51fd40939f8c44b32543b1a0bcb
GitTreeState:  clean
BuildDate:     2022-08-18T21:58:35Z
GoVersion:     go1.18.5
Compiler:      gc
Platform:      linux/amd64
```

if you look at the output of your command not only is the git version old but so is the commit, and it's using go 1.17 which we moved from quite a long time ago

Looking at the output you provided I think it's highly likely you have `<nixos-unstable>` channels for both your root user and your normal davidak user

run `nix-channel --list` and `nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'` on your normal user and we should have found the issue

From there you can decide whether you keep updating the channel for both or you remove it for one user or the other.

**Comment by davidak** [comment]
> or you can click this link on https://search.nixos.org

thanks. didn't knew that

> run `nix-channel --list` and `nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'` on your normal user and we should have found the issue

the first has empty output, so i think it has no channels. the second puts out the same version as root

```
[root@gaming:~]# nix-channel --list
home-manager https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz
nixos https://nixos.org/channels/nixos-22.05
nixos-hardware https://github.com/NixOS/nixos-hardware/archive/master.tar.gz
nixos-unstable https://nixos.org/channels/nixos-unstable
```

that does look correct and i think `nix-channel --update` should update all channels, but i also run the update for the specific channel, so it should be up to date

```
[root@gaming:~]# nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'
"22.11pre405311.97747d3209e"
```

is that the latest version or maybe an old one?

```
[davidak@gaming:~/code/pyzufall]$ nix-shell '<nixos-unstable>' -p scorecard --run 'readlink -f $(which scorecard)'
/nix/store/nydkvcw9nqwhnlr665w9kaink3wk987k-scorecard-4.2.0/bin/scorecard
```

**Comment by 06kellyjac** [comment]
As I said `nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'` on your normal user will *likely* give a different output to your root user

I've not spotted anything in hydra that matches that output path but I have no idea how to actually check everywhere

Or it could be a case of having overrides in your `~/.config/nixpkgs/config.nix`?

**Comment by davidak** [comment]
> As I said `nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'` on your normal user will _likely_ give a different output to your root user

```
[root@gaming:~]# nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'
"22.11pre405311.97747d3209e"
```

```
[davidak@gaming:~]$ nix-instantiate --eval -E '(import <nixos-unstable> {}).lib.version'
"22.11pre405311.97747d3209e"
```

no, that's not it

```
[davidak@gaming:~]$ nix-channel --list

```

the normal has no channel configured

**Comment by 06kellyjac** [comment]
hmmmmm, do you get a newer version on root or also the old 4.2.0 copy?

Only other thing I can think of is keep adding `-v` flags (e.g. `-vvvvvv`) until you notice something weird

**Comment by davidak** [comment]
> do you get a newer version on root or also the old 4.2.0 copy?

```
[root@gaming:~]# nix-shell '<nixos-unstable>' -p scorecard --run "scorecard version"
...
GitVersion:    v4.2.0
```

same version
