### ISSUE TITLE
pass: broken in Darwin

### ISSUE THREAD

**Issue by sorpaas** [NixOS/nixpkgs#18929]
## Issue description

The new `pass` dependency `procps` apparently doesn't build on Darwin.

```
Undefined symbols for architecture x86_64:
  "_sched_setscheduler", referenced from:
      _main in test-schedbatch.o
ld: symbol(s) not found for architecture x86_64
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:429: test-schedbatch] Error 1
make[2]: Leaving directory '/private/var/folders/9b/v666t1m950qbvs8_jtd1mh680000gn/T/nix-build-procps-3.3.11.drv-0/procps-ng-3.3.11/testsuite'
make[1]: *** [Makefile:1468: all-recursive] Error 1
make[1]: Leaving directory '/private/var/folders/9b/v666t1m950qbvs8_jtd1mh680000gn/T/nix-build-procps-3.3.11.drv-0/procps-ng-3.3.11'
make: *** [Makefile:765: all] Error 2
builder for ‘/nix/store/97v57jlbmrdvb2qlgjycz29ifbq9rdp7-procps-3.3.11.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/fkr1gy9wlv6gfckpraln61bmagwibphr-password-store-1.6.5.drv’: 1 dependencies couldn't be built
```

### Steps to reproduce

`nix-env -iA pkgs.pass`

## Technical details

* System: Mac OS X 10.11.6
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre91860.124f25b

**Comment by matthewbauer** [comment]
If you remove "procps" from the build inputs it will build. procps should be linux-only.

**Comment by sorpaas** [comment]
Is it okay to just revert the last commit for `pass/default.nix`? I'm using an older checkout from unstable now and it works fine here. If so, I can submit a PR.

**Comment by matthewbauer** [comment]
@sorpass I think we want it to be optional so Linux systems can get props in that path.

**Comment by Mic92** [comment]
can you test if the following fixes your problem? https://github.com/NixOS/nixpkgs/pull/19165
