### ISSUE TITLE
mysql80: failing to build on aarch64-linux

### ISSUE THREAD

**Issue by tristanpemble** [NixOS/nixpkgs#189333]
### Steps To Reproduce
1. build `mysql80` on `aarch64-linux`

### Build log
https://gist.github.com/tristanpemble/4466d5e823caa3d6fcc7523b5f408b78

### Additional context
I reproduced in a VM after experiencing the same error on our CI server. here is the first hydra build where it failed: https://hydra.nixos.org/build/180810912

### Notify maintainers
@orivej 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.0-46-generic, Ubuntu, 22.04 (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by jdelStrother** [comment]
@tristanpemble did you find any workaround for this?

**Comment by tristanpemble** [comment]
> @tristanpemble did you find any workaround for this?

no, unfortunately. I've tried to debug this on my own and it's more involved than I am capable of. we are just pinning an older version of nixpkgs right now.

@orivej any chance you can take a look at this?

**Comment by tristanpemble** [comment]
@jdelStrother it looks like as of Nov 14th this is working again: https://hydra.nixos.org/build/198712749

I confirmed locally in a VM
