### ISSUE TITLE
julia-bin update available

### ISSUE THREAD

**Issue by leonvonrabenmond** [NixOS/nixpkgs#189444]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: [julia-bin](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/julia/1.7-bin.nix)

current version: 1.7.3
desired version: [1.8.0](https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.0-linux-x86_64.tar.gz)

###### Notify maintainers

maintainers:
@ninjin 
@7c6f434c 
###### Note for maintainers

Please tag this issue in your PR.

**Comment by wentasah** [comment]
I started preparing the update in #189656.

Cc: @raskin @rikhuijzer
