### ISSUE TITLE
Build `gnome-books-40.0` fails

### ISSUE THREAD

**Issue by MikiVanousek** [NixOS/nixpkgs#189416]
### Steps To Reproduce
1. Build `gnome-books-40.0`

### Build log
```
error: Package ‘gnome-books-40.0’ in /nix/store/p5jayhh78vbq7kpw6p3m1s61g365zwam-nixos/nixos/pkgs/desktops/gnome/apps/gnome-books/default.nix:93 is marked as broken, refusing to evaluate.
```

### Notify maintainers

@bobby285271 @hedning

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.61, NixOS, 22.11 (Raccoon), 22.11pre402826.963d27a0767`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(miki): `""`
 - channels(root): `"android-nixpkgs, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kilianar** [comment]
`gnome-books` was marked as broken because the build is failing after a meson update and the upstream project was archived. See https://github.com/NixOS/nixpkgs/pull/186941#issuecomment-1221601016.

**Comment by MikiVanousek** [comment]
Do I understand the app is gone for good?

**Comment by bobby285271** [comment]
gnome-books has been archived as upstream hasn't found a new maintainer: https://discourse.gnome.org/t/gnome-books-looking-for-a-maintainer/8912.

(And yeah it does not build with latest meson)

**Comment by MikiVanousek** [comment]
Should we perhaps remove `gnome-books` from nixpkgs?
