### ISSUE TITLE
Nspawn containers: doc recommends option (wantedBy) that doesn't work

### ISSUE THREAD

**Issue by PaulGrandperrin** [NixOS/nixpkgs#189499]
[systemd.nspawn.<name>.wantedBy](https://search.nixos.org/options?channel=22.05&show=systemd.nspawn.%3Cname%3E.wantedBy&from=0&size=50&sort=relevance&type=packages&query=nspawn) recommends setting it to `[ "multi-user.target" ]` to make the container be launched automatically.

It doesn't work, at least on my machine.

However, setting
`systemd.targets.machines.wants = [ "systemd-nspawn@ubuntu.service" ];`
does work. I don't remember how/where I found this solution.

@ck3d @ElvishJerricco @devplayer0

**Comment by ck3d** [comment]
I have written a NixOS test, which shows and tests an autostart for nspawn containers in
https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/systemd-machinectl.nix#L40

You tried to define a systemd nspawn file with wantedBy, which is for my understanding not conform to systemd. A nspawn file configures the nspawn container, a nspawn service does the runtime handling.

**Comment by ElvishJerricco** [comment]
@ck3d that doesn't change the fact that we have a problematic NixOS option (`systemd.nspawn.<name>.wantedBy`) that doesn't function.

**Comment by ck3d** [comment]
You are right, wantedBy is not a valid option for nspawn files. It was introduced with following commit by adding `sharedOptions`:
https://github.com/NixOS/nixpkgs/commit/522c16bd8669dd2d71fd4c01b2b2fe02a0a7a02c
