### ISSUE TITLE
Unable to build gamescope

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#189464]
### Steps To Reproduce
1. Attempt to install gamescope as seen here: https://github.com/Krutonium/My_Unified_NixOS_Config/blob/adadd3a3ec12201a08bf1f5c6a5ce2a0a17b72f9/packages/steam.nix

### Build log

[notbuilding.txt](https://github.com/NixOS/nixpkgs/files/9478436/notbuilding.txt)

### Additional context
It seems to be unable to locate either cmake or pkgconfig.

### Notify maintainers

@nrdxp 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.05 (Quokka), 22.05.20220901.b82ccaf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`


```

**Comment by polypoyo** [comment]
I was having the same issue, and this patch seems to have resolved it:
```patch
diff --git a/pkgs/applications/window-managers/gamescope/default.nix b/pkgs/applications/window-managers/gamescope/default.nix
index 7e4003c6..b8828bba 100644
--- a/pkgs/applications/window-managers/gamescope/default.nix
+++ b/pkgs/applications/window-managers/gamescope/default.nix
@@ -22,6 +22,7 @@
 , wlroots
 , libliftoff
 , lib
+, cmake
 , makeBinaryWrapper
 }:
 let
@@ -45,6 +46,7 @@ stdenv.mkDerivation {
     pkg-config
     ninja
     makeBinaryWrapper
+    cmake
   ];
 
   buildInputs = [
```

**Comment by aviallon** [comment]
I am actually wondering how this got merged into 22.05, while being broken...

**Comment by nrdxp** [comment]
It wasn't broken when it was first backported, and it is not broken in master. Seems `stb` is missing a pkgconfig file again. I fixed that in one of the original PRs but I'm not sure how it got reverted on the release branch. I'll see if I can get a fix up soon.

**Comment by Krutonium** [comment]
It builds on 22.11
