### ISSUE TITLE
Package request: below

### ISSUE THREAD

**Issue by hab25** [NixOS/nixpkgs#189498]
**Project description**

`below` is an interactive tool to view and record historical system data.

**Metadata**

* homepage URL: https://github.com/facebookincubator/below
* source URL: https://github.com/facebookincubator/below#installing-from-source
* license: Apache License 2.0 https://github.com/facebookincubator/below/blob/main/LICENSE
* platforms: linux (support for others is unclear)

**Comment by dit7ya** [comment]
@hab25 Can you please test the linked PR since some of the package tests fail (most likely due to filesystem differences on NixOS)?

**Comment by hab25** [comment]
@dit7ya sorry for the delay. I'm on Pop_OS! 22.04 (nix 2.9.1).

- `sudo below live` seems to work.
- `sudo below record` works but output warnings/errors on startup:
    ```
    Sep 06 11:42:57.143 DEBG Starting up!
    Sep 06 11:43:02.143 ERRO System error, errno: 4007 
    Sep 06 11:43:07.143 WARN bpf error channel disconnected
    ```
  Not sure what the error is about. Probably worth investigating.
  The warning indicates https://github.com/facebookincubator/below/issues/8122 and so it's likely not nix-related.

- `sudo below replay`, `sudo below dump` seem to work as expected

After running all of these commands:
- `journalctl | grep below` does not show any `below` errors.
- `cat /var/log/below/error_root.log` shows only instances of the above error and warning

**Comment by hab25** [comment]
I tried running the package tests and also getting the 4 failures. My Pop_OS! 22.04 does have a `/sys/fs/cgroup/`; I believe the failures are due to `nix` sandboxing.

This should be nothing new to you @dit7ya, but here's the log just in case, and to help with search engine indexing.
```
running 9 tests
test test::default_cgroup_io_model ... ok
test test::calculate_pressure ... ok
test test::calculate_cpu_usage ... ok
test test::no_cgroup_io_model ... ok
test test::testing_fold_string ... ok
test test::disable_disk_stat ... FAILED
test test::disable_io_stat ... FAILED
test test::advance_forward_and_reverse ... FAILED
test test::record_replay_integration ... FAILED

failures:

---- test::disable_disk_stat stdout ----
thread 'test::disable_disk_stat' panicked at 'failed to collect sample: Os { code: 2, kind: NotFound, message: "No such file or directory" }: "/sys/fs/cgroup/"

Caused by:
    No such file or directory (os error 2)', below/src/test.rs:218:6

---- test::disable_io_stat stdout ----
thread 'test::disable_io_stat' panicked at 'failed to collect sample: Os { code: 2, kind: NotFound, message: "No such file or directory" }: "/sys/fs/cgroup/"

Caused by:
    No such file or directory (os error 2)', below/src/test.rs:201:6

---- test::advance_forward_and_reverse stdout ----
thread 'test::advance_forward_and_reverse' panicked at 'failed to collect sample: Os { code: 2, kind: NotFound, message: "No such file or directory" }: "/sys/fs/cgroup/"

Caused by:
    No such file or directory (os error 2)', below/src/test.rs:146:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::record_replay_integration stdout ----
thread 'test::record_replay_integration' panicked at 'failed to collect sample: Os { code: 2, kind: NotFound, message: "No such file or directory" }: "/sys/fs/cgroup/"

Caused by:
    No such file or directory (os error 2)', below/src/test.rs:49:6


failures:
    test::advance_forward_and_reverse
    test::disable_disk_stat
    test::disable_io_stat
    test::record_replay_integration

test result: FAILED. 5 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/206132
