### ISSUE TITLE
Update kanidm to v1.1.0-alpha.9

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#189588]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: kanidm

current version: v1.1.0-alpha.8
desired version: v1.1.0-alpha.9

###### Notify maintainers

maintainers:

@flakebi @erictapen 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by erictapen** [comment]
Closed through https://github.com/NixOS/nixpkgs/pull/189847
