### ISSUE TITLE
Update qemu (build without stack protection)

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#18954]
## Issue description
As part of #18856, we will need to update qemu.
qemu 2.7.0 cannot be built with stack protection (see https://mail-index.netbsd.org/pkgsrc-bugs/2016/09/16/msg060363.html)

I do not know how to build without or how to circumvent this, so help would be appreciated :)

### Steps to reproduce
- Change the `qemu/default.nix` to use 2.7.0, remove custom patches (they seem to all be included in 2.7.0 except for our `no-etc-install`, leave that in).
- `nix-build -A qemu`

Output ends with

```
  Building optionrom/linuxboot.img
  CC    qga/guest-agent-command-state.o
  Building optionrom/linuxboot_dma.img
linuxboot_dma.o: In function `bios_cfg_read_entry':
/tmp/nix-build-qemu-2.7.0.drv-0/qemu-2.7.0/pc-bios/optionrom/linuxboot_dma.c:181: undefined reference to `__stack_chk_fail_local'
linuxboot_dma.o: In function `load_kernel':
/tmp/nix-build-qemu-2.7.0.drv-0/qemu-2.7.0/pc-bios/optionrom/linuxboot_dma.c:298: undefined reference to `__stack_chk_fail_local'
make[1]: *** [Makefile:49: linuxboot_dma.img] Error 1
make: *** [Makefile:230: romsubdir-optionrom] Error 2
make: *** Waiting for unfinished jobs....
builder for ‘/nix/store/7d05cqywpk0h4bk5wyfv3325064dccaw-qemu-2.7.0.drv’ failed with exit code 2
error: build of ‘/nix/store/7d05cqywpk0h4bk5wyfv3325064dccaw-qemu-2.7.0.drv’ failed
```

## Technical details

* System: 17.03.git.455772e (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09beta335.7617e7e"

**Comment by joachifm** [comment]
`hardeningDisable = [ "stackprotector" ]`

**Comment by fpletz** [comment]
This is one of those cases where enabling hardening flags for all gcc calls is not desirable. I'm not happy with disabling the stackprotector for all qemu code but we have to for now. :cry:

**Comment by joachifm** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/18959
