### ISSUE TITLE
Systemd-nspawn: NixOS conf only allows to map a single port

### ISSUE THREAD

**Issue by PaulGrandperrin** [NixOS/nixpkgs#189506]
In [systemd.nspawn.<name>.networkConfig](https://search.nixos.org/options?channel=22.05&show=systemd.nspawn.%3Cname%3E.networkConfig&from=0&size=50&sort=relevance&type=packages&query=systemd.nspawn), we can specify `Port`, but since it's a map/dictionary, we can only specify it once.

This means, we can only forward **one** port to the container.

And since, there are no things like `extraConfig`, there's really no way around this limitation.

@ck3d @ElvishJerricco @devplayer0

**Comment by PaulGrandperrin** [comment]
If someone has the same issue, here's my solution:
```nix
  #systemd.nspawn."ubuntu" = {
  #  enable = true;
  #  # wantedBy = [ "multi-user.target" ]; # doesn't work https://github.com/NixOS/nixpkgs/issues/189499
  #};
  environment.etc."systemd/nspawn/ubuntu.nspawn".text= ''
    [Exec]
    Hostname=ubuntu

    [Network]
    Port=222:22
    Port=2379
    Port=20160
    Port=4000
    Port=9090
    Port=3000
  '';
  # systemd.services."systemd-nspawn@ubuntu".restartTriggers = [ config.environment.etc."systemd/nspawn/ubuntu.nspawn".source ]; # FIXME breaks the conf because it doesn't understand templates
  systemd.targets.machines.wants = [ "systemd-nspawn@ubuntu.service" ];
  systemd.targets.multi-user.wants = [ "machines.target" ];
```

It completely bypasses NixOS' handling of nspawn and write files manually. It doesn't trigger a restart when the conf changes but it also doesn't do it in the NixOS module anyway.

**Comment by poscat0x04** [comment]
Have you tried to set `Port` to a list?

**Comment by PaulGrandperrin** [comment]
@poscat0x04 Oh wow! That's nice!

I think it would make sense to document that briefly in all `systemd.*.*Config`.

I could make a PR, what do you think?

**Comment by poscat0x04** [comment]
I agree that the documentation on systemd options is very lacking

**Comment by ElvishJerricco** [comment]
Yes setting the option to a list is supported by all `*Config` options as far as I'm aware, and results in multiple directives of the same name to be generated. Perhaps this should be better documented but I'm not sure where it should be better documented. And seeing as the solution exists, I think this issue can be closed.

**Comment by PaulGrandperrin** [comment]
@ElvishJerricco @poscat0x04 
I'm glad the feature exists, but without discoverability, it's almost like secret.
I'm thinking about making a PR adding one sentence to all `*Config`, like:
- "To specify an attribute multiple times, join their values in one array"
- "Use an array of values to instantiate an attribute multiple times"

wdyt?

**Comment by poscat0x04** [comment]
I don't know much about NixOS documentation unfortunately. I suggest consulting the documentation team.
