### ISSUE TITLE
buildRustPackage does not apply patches

### ISSUE THREAD

**Issue by 0xnook** [NixOS/nixpkgs#189533]
### Describe the bug
When building a rust package that applies `patches` to `src`, patches are not correctly applied, and old source code is used when `cargo test` is eventually ran.

I ran into the issue when trying to package `https://github.com/radicle-dev/radicle-cli`, where I remove a rust test called `fn can_be_initialized()` via a patch, 

### Steps To Reproduce
1. Enter the command `nix build -L github:0xnook/nookpkgs#radicle-cli`
2. The derivation will fail due to `fn_can_be_initialized()` still being present.

Please be aware derivation takes a long time (15 mins in my machine).

### Expected behavior
When I fork the `radicle-cli` repo and remove the test manually from the source code, and use my fork as `src`, the test never runs and the derivation completes correctly, in fact I generated the diff patch from [this fork](https://github.com/0xnook/radicle-cli/blob/master/auth/src/lib.rs#L337).

You can verify this by running
`nix build -L github:0xnook/nookpkgs/nix-issue#radicle-cli`

### Additional context
In [the radicle-cli nix derivation I wrote](https://github.com/0xnook/nookpkgs/blob/master/packages/radicle-cli/default.nix#L23) I am logging the file containing the test, and it appears the patch is applied correctly during the `postPatch` phase.

### Notify maintainers
Not sure, please ping accordingly.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.11 (Raccoon), 22.11.20220828.a63021a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(nook): `"home-manager"`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by winterqt** [comment]
1. `radicle-cli` is already packaged
2. `patches` works fine with `buildRustPackage`, the issue is that there are two tests named `can_be_initialized`, you're only patching one

**Comment by 0xnook** [comment]
Indeed, I somehow missed the package, and the test, thanks for the heads up and sorry about the confusion

**Comment by 0xnook** [comment]
On a second thought, I am still a bit puzzled on to why my fork with the patch still passes compilation, but I will look in to that, perhaps that I fork from master and not the release branch
