### ISSUE TITLE
Reorganize gnome package set

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#18952]
## Issue description

We have packages that are part of the gnome package-set spread out over `nixpkgs`.
For example:
- clutter
- gcab
- glib
- gtk
- networkmanager
- vala

Imo these should be part of the gnome package set and only have top-level aliases.
This would make the gnome set consistent with upstream and also make updating easier. Currently the maintainers script only picks up the stuff that is actually inside `pkgs/desktops/gnome-3/` and is limited to packages that follow the gnome release cycle versioning.
If we stick to the gnome package layout for all packages we can check the `cache.json` for the relevant gnome version und pick up all version changes from [there](http://ftp.acc.umu.se/pub/GNOME/core/3.22/3.22.0/cache.json) 

Just take a look at clutter and vala for examples of the problems this introduces into nixpkgs. 
There are old unused derivations and the current versions use overrides to pick up correct dependencies.
I'm working on cleaning up some of the cruft at the moment, but in the future I think this change will facilitate stuff greatly.

Most if not all of these packages should probably be moved:

```
ag --ignore 'gnome-*' mirror...gnome pkgs
95
```

CC
gnome maintainers @DamienCassou @lethalman 
glib maintainers @lovek323 raskin urkud
gtk+ maintainers urkud raskin @vcunat @lethalman 
vala maintainers @antono @lethalman

**Comment by lethalman** [comment]
I somewhat agree but something tells me this is not a good idea... have to think about it. @vcunat do you have an idea about this?

**Comment by vcunat** [comment]
**glib**: I believe this one can be shared and makes little sense to bind to gnome version. I don't remember a glib update causing wider problems anywhere.

**gtk+**: I suppose you only mean versions >= 3.x, but even there I'm not certain what exactly will happen with the [new stable versioning scheme](https://blog.gtk.org/2016/09/01/versioning-and-long-term-stability-promise-in-gtk/). I assume gnome releases will require those "unstable" 3.9x, perhaps each gnome release with a different "x" (we might alias the latest one as `gtk4`). Most of nixpkgs tree will have to remain on `gtk3` 3.22.y, as I don't expect apps to move so fast, similarly to what was happening with 2->3. If this holds, then 3.9x might belong under gnome and 3.22.y outside, but it might be unnecessary duplication of code.

I know very little about the others, except that NetworkManager is certainly used outside gnome a lot, but that might not be any problem for this at all.

**Comment by vcunat** [comment]
**gtk+**: the duplication could be avoided e.g. by having most of the expression shared and then just stubs [like this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/protobuf/2.6.nix) in individual gnome releases.

**Comment by vcunat** [comment]
BTW, Raskin is @7c6f434c and urkud has been inactive for years now (we might just purge him from maintainers).

**Comment by lethalman** [comment]
Also consider xfce.

>

-- 
NixOS Linux <http://nixos.org>

**Comment by FRidh** [comment]
Somewhat relevant. Gnome provides Python bindings for quite some packages. Currently these are (indirectly) available via `all-packages.nix`. I think the functions building those derivations should be *called* from `python-packages.nix` since that way we can guarantee the same version of the interpreter is used.

**Comment by jtojnar** [comment]
Or we could improve the maintainer script and dissolve the GNOME package set à la [triton](https://github.com/triton/triton), keeping it only virtually.

**Comment by worldofpeace** [comment]
We've pretty much decided to dissolve the `gnome3` attribute completely so I will close this issue.
Everything at `gnome3` is slowly turning into aliases, and eventually we'll have some sort of solution for the maintainer script.
