### ISSUE TITLE
Google-Chrome: 104.0.5112.101 -> 106.0.5249.21

### ISSUE THREAD

**Issue by thistechguy** [NixOS/nixpkgs#189633]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: google-chrome

current version: 104.0.5112.101
desired version: 106.0.5249.21

###### Notify maintainers

maintainers: @primeos 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by primeos** [comment]
105.0.5195.102 is the most recent stable version and already in Nixpkgs.
