### ISSUE TITLE
Sage docs don't have a complete index

### ISSUE THREAD

**Issue by aikrahguzar** [NixOS/nixpkgs#189607]
### Describe the bug

I have installed sage thorough the nix package manager and it is the only thing I use nix for so it is entirely possible I am doing something stupid and wrong.

I have the latest from here build https://hydra.nixos.org/build/189042799

When I try to get to the index for all entries which is located `/nix/store/r77k14kq9iw92w32bd9sny7d98dbrq32-sagedoc-9.6/share/doc/sage/html/en/reference/genindex-all.html` on my computer, I get a page with very few entries (see the screenshot) below
![Screenshot 2022-09-03 at 16-02-51 Index — Reference Manual](https://user-images.githubusercontent.com/88336724/188273974-db8b4957-214e-4e91-8ea8-0152965fee47.png)

While I expect something more like https://doc.sagemath.org/html/en/reference/genindex-all.html

### Steps To Reproduce
Compare /nix/store/r77k14kq9iw92w32bd9sny7d98dbrq32-sagedoc-9.6/share/doc/sage/html/en/reference/genindex-all.html and https://doc.sagemath.org/html/en/reference/genindex-all.html

### Expected behavior
A full fledged index.

### Additional context
I want to use `dash2doc` to generate a docset which I can then search following the answer here https://ask.sagemath.org/question/42435/offline-docset-for-sagemath/. I can build a docset after copying the reference directory to somewhere I have write access to. However when I try to search there are almost no results and I think this might be responsible. 

### Notify maintainers
@timokau 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.2-1-default, openSUSE Tumbleweed, noversion, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixpkgs"`
 - channels(rahguzar): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

```

**Comment by timokau** [comment]
I'm not very involved in sage maintenance these days, I mostly contribute by reviewing @collares and @omasanori's PRs every now and then. They are probably better qualified to help you :)

Maybe we should drop me from the maintainers list, or at least change the order to reflect reality?

**Comment by aikrahguzar** [comment]
> I'm not very involved in sage maintenance these days, I mostly contribute by reviewing @collares and @omasanori's PRs every now and then. They are probably better qualified to help you :)
> 
> Maybe we should drop me from the maintainers list, or at least change the order to reflect reality?

Sorry for the bother then! I was actually going by the information here https://trac.sagemath.org/wiki/Distribution#Nix which looked outdated but I didn't have any better idea.

**Comment by collares** [comment]
Thanks for the report! Will take a look today.

**Comment by aikrahguzar** [comment]
> Thanks for the report! Will take a look today.

Thanks a lot!

**Comment by timokau** [comment]
> Sorry for the bother then! I was actually going by the information here https://trac.sagemath.org/wiki/Distribution#Nix which looked outdated but I didn't have any better idea.

No bother :) Thanks for the pointer, I have updated the maintainer information there.
