### ISSUE TITLE
package request: detekt

### ISSUE THREAD

**Issue by humancalico** [NixOS/nixpkgs#189664]
**Project description**
Static code analysis for Kotlin 

**Metadata**

* homepage URL: https://detekt.dev/
* source URL: https://github.com/detekt/detekt
* license: apache
* platforms: all

**Comment by mdr** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/211352

**Comment by humancalico** [comment]
Thanks @mdr! Closing this.
