### ISSUE TITLE
[package request] Seahorse Nautilus extension

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#189671]
**Project description**
The Seahorse Nautius extension is an extension for Nautilus (also known as Files) which allows encryption and decryption of OpenPGP files using GnuPG.

**Metadata**

* homepage URL: https://gitlab.gnome.org/GNOME/seahorse-nautilus
* source URL: https://gitlab.gnome.org/GNOME/seahorse-nautilus
* license: gpl2+
* platforms: linux

**Comment by baronleonardo** [comment]
@jtojnar

I have started doing this but I 2 issues
1- I can't understand how can I handle the install part (after building)
2- how can I add or link the output to nautilus derivation output

till now that what I have

```nix
{ meson, python3, gtk3, gnupg, cmake, pkg-config, gnome, libcryptui, gcr, libnotify, gpgme, ninja, mkDerivation, fetchgit }:
mkDerivation {
  name = "seahorse-nautilus";
  src = fetchgit {
    url = "https://gitlab.gnome.org/GNOME/seahorse-nautilus.git";
    sha256 = "d59dc92f4f703b734dac82ce0c186c1751133df5";
  };

  nativeBuildInputs = [
    meson
    python3
    cmake
    pkg-config
    ninja
  ];

  buildInputs = [
    gtk3.dev
    gnupg
    gnome.nautilus.dev
    libcryptui
    gcr
    libnotify
    gpgme
  ];

  meta = with lib; {
    description = "An extension for Nautilus (also known as Files) which allows encryption and decryption of OpenPGP files using GnuPG.";
    homepage = "https://gitlab.gnome.org/GNOME/seahorse-nautilus";
    license = licenses.gpl2;
    platforms = platforms.linux;
    maintainers = teams.gnome.members;
  };
}
```

**Comment by jtojnar** [comment]
> 1- I can't understand how can I handle the install part (after building)

The module will be installed automatically:

https://gitlab.gnome.org/GNOME/seahorse-nautilus/-/blob/d59dc92f4f703b734dac82ce0c186c1751133df5/nautilus-ext/meson.build#L15

The path is determined here:

https://gitlab.gnome.org/GNOME/seahorse-nautilus/-/blob/d59dc92f4f703b734dac82ce0c186c1751133df5/meson.build#L38

Currently, it is being unconditionally installed into nautilus’s prefix. Instead, it should be installed into this package’s prefix as follows:

https://gitlab.gnome.org/GNOME/nautilus-python/-/blob/0b68c283292d8f518d1e6bcef259ae77f529435b/meson.build#L27

See also https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/

> 2- how can I add or link the output to nautilus derivation output

You do not need to. You will install the extension package with `environment.systemPackages` and the GNOME module will make Nautilus pick it up:

https://github.com/NixOS/nixpkgs/blob/fc9bff20b4700e91b23bd4e4da2cb19e4a9c3b2f/nixos/modules/services/x11/desktop-managers/gnome.nix#L523

**Comment by baronleonardo** [comment]
@jtojnar  now I successfully had build using the following derivation, but there is nothing appears in nautilus, what did I miss ?

```nix
{ meson, python3, gtk3, gnupg, cmake, pkg-config, gnome, libcryptui, gcr, libnotify, gpgme, ninja, stdenv, fetchgit, lib }:
stdenv.mkDerivation rec {
  name = "seahorse-nautilus";
  version = "master";

  src = fetchgit {
    url = "https://gitlab.gnome.org/GNOME/seahorse-nautilus.git";
    sha256 = "sha256-n5Q6ciE/3o0FYraweZWDY5suvwG+SXU1pU05VxA68Ls=";
  };

#  src = ./.;

  nativeBuildInputs = [
    meson
    python3
    cmake
    pkg-config
    ninja
  ];

  buildInputs = [
    gtk3.dev
    gnupg
    gnome.nautilus.dev
    libcryptui
    gcr
    libnotify
    gpgme
  ];

  patches = [ ./gpg-version.patch ];

  postPatch = ''
    patchShebangs \
      meson/gpg_check_version.py
  '';

#  patchPhase = ''
#    patch -p1 < ./gpg-version.patch
#  '';

#  configurePhase = ''
#    cat $src/meson/gpg_check_version.py
#    meson build --prefix $out -D nautilus-ext-dir=$out/lib/nautilus/extensions-4
#    cat /build/seahorse-nautilus/build/meson-logs/meson-log.txt
#  '';

  mesonFlags = [
    "-D nautilus-ext-dir=${placeholder "out"}/lib/nautilus/extensions-4"
  ];

#  ConfigureFlags = [
#    "--prefix $out"
#    "-D nautilus-ext-dir=$out/lib/nautilus/extensions-4"
#  ];

#  buildPhase = ''
#    ninja -C build
#  '';

#  installPhase = ''
#    ninja -C build install
#  '';

  meta = with lib; {
    description = "An extension for Nautilus (also known as Files) which allows encryption and decryption of OpenPGP files using GnuPG.";
    homepage = "https://gitlab.gnome.org/GNOME/seahorse-nautilus";
    license = licenses.gpl2;
    platforms = platforms.linux;
    maintainers = teams.gnome.members;
  };
}
```

and the patch
```patch
diff --git a/meson/gpg_check_version.py b/meson/gpg_check_version.py
index 4f1ccaf..0b752d5 100755
--- a/meson/gpg_check_version.py
+++ b/meson/gpg_check_version.py
@@ -13,6 +13,7 @@ def parse_version(gpg_output):
 # For GPG, this means that the major and minor version should be equal;
 # for GPGME, this means only the major version should be equal.
 def check_version(gpg_version, accepted_version, is_gpgme = False):
+    gpg_version = gpg_version.split('-')[0]
     gpg_major, gpg_minor, gpg_micro = [int(ver) for ver in gpg_version.split('.', 2)]
     acc_major, acc_minor, acc_micro = [int(ver) for ver in accepted_version.split('.', 2)]
     if is_gpgme:
```

**Comment by baronleonardo** [comment]
@jtojnar oh I got it I needed to logout, now everything works as expected. I will create a merge request then
very thanks

**Comment by baronleonardo** [comment]
now it works after logout and then login
but when I encrypt/sign and error message appears
`GLib-GIO-ERROR **: 20:45:31.154: Settings schema 'org.gnome.seahorse.nautilus' is not installed`

**Comment by jtojnar** [comment]
For testing, you can run `NAUTILUS_4_EXTENSION_DIR=$(nix-build -A seahorse-nautilus)/lib/nautilus/extensions-4 nautilus` (make sure nautilus process is not running).

For the settings, you will need to do [some patching](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-common-issues-unwrappable-package-gsettings-c).

These two files specifically:

https://gitlab.gnome.org/GNOME/seahorse-nautilus/-/blob/d59dc92f4f703b734dac82ce0c186c1751133df5/tool/seahorse-tool.c#L710
https://gitlab.gnome.org/GNOME/seahorse-nautilus/-/blob/d59dc92f4f703b734dac82ce0c186c1751133df5/tool/seahorse-widget.c#L107

Ideally, we would use `glib.mkHardcodeGsettingsPatch` like e.g. [evolution-data-server does](https://github.com/NixOS/nixpkgs/blob/2ce4eabb037cc97f6a01c5750e7216fe614331f7/pkgs/desktops/gnome/core/evolution-data-server/default.nix#L153-L163) but that does not currently support `g_settings_new_with_path` so the patch will need to be created manually until it does.

**Comment by jtojnar** [comment]
https://github.com/NixOS/nixpkgs/pull/206291 will add support for `g_settings_new_with_path` to `makeHardcodeGsettingsPatch`.

**Comment by SamLukeYes** [comment]
Upstream abandoned
