### ISSUE TITLE
Build of Haskell's `evdev` fails

### ISSUE THREAD

**Issue by tannerlegvold** [NixOS/nixpkgs#189673]
### Steps To Reproduce
1. `nix-shell -p haskellPackages.evdev`
or
```bash
export NIXPKGS_ALLOW_BROKEN=1
nix-shell -p haskellPackages.evdev
```

### Build log
Heres the output of `nix-shell -p haskellPackages.evdev` (without setting `NIXPKGS_ALLOW_BROKEN`)
```
error: Package ‘evdev-2.1.0’ in /nix/store/5ahhafra1z3r1acp7n5lcgdyjbfgihj6-nixpkgs/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:90322 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```
If you set `export NIXPKGS_ALLOW_BROKEN=1` then the output gets larger, but you can see at the end the build failure is due to a failed test called `smoke`. 

### Additional context
I'm basically requesting that test be temporarily removed, it may not run properly because of some feature of the build environment, at least according to the maintainer @georgefst. We discussed this [here](https://github.com/georgefst/evdev/issues/25).

### Notify maintainers
@georgefst 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-47-generic, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(tanner): `""`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by cdepillabout** [comment]
@tannerlegvold Thanks for reporting this!

We'd appreciate if you'd send a PR disabling the tests for `evdev` and marking it unbroken.

Here's an example PR:

https://github.com/NixOS/nixpkgs/pull/173658

**Comment by sternenseemann** [comment]
Done in cab5dc490e4.
