### ISSUE TITLE
NormCap

### ISSUE THREAD

**Issue by igorlogius** [NixOS/nixpkgs#189702]
**Project description**

OCR powered screen-capture tool to capture information instead of images 

**Metadata**

* homepage URL: https://github.com/dynobo/normcap
* source URL: https://github.com/dynobo/normcap
* license: https://github.com/dynobo/normcap/blob/main/LICENSE  (GPL) 
* platforms: linux, windows, macOS

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/166228

**Comment by cafkafk** [comment]
As pinn3 noticed, duplicate of #166228, closing
