### ISSUE TITLE
wiki: signup and password reset broken - PHP mail() error

### ISSUE THREAD

**Issue by brainrape** [NixOS/nixpkgs#18974]
## Issue description

Signup and Password Reset are broken on Nix Wiki.

### Steps to reproduce
1. Try to sign up
2. Get Error:

> Nix Wiki could not send your confirmation mail. Please check your email address for invalid characters.
> Mailer returned: Unknown error in PHP's mail() function.

Account is created and you are logged in but after the validation period expires you are no longer able to log in. Password reset doesn't work because of the same error.

**Comment by FRidh** [comment]
The wiki has been closed. See https://github.com/NixOS/nixpkgs/issues/16918.
