### ISSUE TITLE
gazebo still generate wrong cmake file

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#18978]
## Issue description
Package that depends on gazebo fails finding it using cmake. (latest master)

## Technical details

Piece of gazebo cmake file:

```
set(GAZEBO_PLUGIN_PATH "/nix/store/9bavxdfavww2araaa9ykx60lxyvkv88z-gazebo-7.0.0//nix/store/9bavxdfavww2araaa9ykx60lxyvkv88z-gazebo-7.0.0/lib/gazebo-7/plugins")

# The media path contains the location on disk where images,
# materials scripts, shaders, and other related resources are stored.
set(GAZEBO_MEDIA_PATH "/nix/store/9bavxdfavww2araaa9ykx60lxyvkv88z-gazebo-7.0.0/share/gazebo-7/media")

set(GAZEBO_PLUGIN_PATH "/nix/store/9bavxdfavww2araaa9ykx60lxyvkv88z-gazebo-7.0.0//nix/store/9bavxdfavww2araaa9ykx60lxyvkv88z-gazebo-7.0.0/lib/gazebo-7.0/plugins")

# The media path contains the location on disk where images,
# materials scripts, shaders, and other related resources are stored.
set(GAZEBO_MEDIA_PATH "/nix/store/9bavxdfavww2araaa9ykx60lxyvkv88z-gazebo-7.0.0/share/gazebo-7.0/media")
```

**Comment by Mic92** [comment]
can we get more context on the program, you try to compile?

**Comment by nico202** [comment]
@Mic92 yes, sorry for the extremely bad bug report. I'm in a hurry and recompiling gazebo takes hours.

This is one a dependency I have in the nix shell I need to run: [default.nix](https://gist.github.com/nico202/90f832713e07ea3fba5bc35dcb1e2eee)

It is failing to find gazebo. This is the error I get:
```
-- Found Protobuf: /nix/store/5s149wk0b1yqkas54r53yzq4lqd5d13v-protobuf-2.6.1-lib/lib/libprotobuf.so;-lpthread (found version "2.6.1") 
CMake Error at /nix/store/i3a69xr2irahb3ykkwrvfxkza6y7an6h-gazebo-6.5.1/lib/cmake/gazebo/gazebo-config.cmake:95 (message):
  Library 'gazebo' in package GAZEBO is not installed properly
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)
```

(different gazebo version (6.5/7) because I'm trying both)

**Comment by Mic92** [comment]
what are the files in the gazebo package? There should be at least a cmake file (gazebo.cmake)
and a library (libgazebo.so...). The last thing is missing or your current build failed to find it.
The content of the cmake file would be interesting in this case.

**Comment by nico202** [comment]
@Mic92 I put an extract of the cmake file on the first post, uploaded the full version right [here](https://gist.github.com/nico202/17e6bbc94cbe9de733ce184513fc26a4) now.

As you can see, the paths are repeated (like: $path//$path/lib), while the correct path (like: $path/lib) exists

**Comment by nico202** [comment]
Ok, looking at the [source](https://bitbucket.org/osrf/gazebo/src/73fae73d688a67241403ed58636f5da0fd72e314/cmake/gazebo-config.cmake.in?at=default&fileviewer=file-view-default):
    set(@PKG_NAME@_PLUGIN_PATH "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@/gazebo-@GAZEBO_MAJOR_VERSION@/plugins") 

It seems that `CMAKE_INSTALL_LIBDIR` should be relative to `CMAKE_INSTALL_PREFIX`

**Comment by Mic92** [comment]
Ok, you should be able to override this in using in `cmakeFlags`

**Comment by nico202** [comment]
Ok, do you know the right path/flags to set? A wrong one might costs me hours

**Comment by Mic92** [comment]
I can only take make a good guess:

```nix
cmakeFlags=["-DCMAKE_INSTALL_LIBDIR=lib"];
```

also enable withQuickBuild to skip the tests.


The strange thing, is that all the files actually end up in the correct directory.

you could try to add and add a test command:

```nix
preBuild = ''
cmake ${cmakeDir:-.} $cmakeFlags "${cmakeFlagsArray[@]}"
exit 1
'';
```

and build with "-K" flag to keep the build directory.

otherwise just patch this file: https://bitbucket.org/osrf/gazebo/src/73fae73d688a67241403ed58636f5da0fd72e314/cmake/gazebo-config.cmake.in?at=default&fileviewer=file-view-default

**Comment by nico202** [comment]
Hi, thanks again :)

    cmakeFlags=["-DCMAKE_INSTALL_LIBDIR=lib"];
This worked (the previous cmake error is solved), but still the include dir is wrong.
I did `CMAKE_INSTALL_INCLUDEDIR=include` and this time it got solved. Tomorrow I'll pull request, thanks!
