### ISSUE TITLE
Laptop suspends again incorrectly after opening the lid

### ISSUE THREAD

**Issue by mikael-andersson** [NixOS/nixpkgs#18981]
## Issue description

After my laptop (Lenovo X1 Carbon) has been suspended by closing the lid, opening the lid wakes it up properly but instantly, I get to see the login screen shortly, suspends.

I got this problem after upgrading from 16.03 to 16.09.

If I suspend the laptop with 'systemctl suspend' first and then close the lid, opening the lid will wake up the laptop properly.
### Steps to reproduce

Close lid and let it suspend. Open the lid and then laptop wakes up and after a second it will suspend.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
  16.09beta430.c4469ed (Flounder)
- Nix version: (run `nix-env --version`)
  nix-env (Nix) 1.11.4
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
  "16.09beta430.c4469ed"

**Comment by Mic92** [comment]
Do you get the same behavior, 
if you set your power key to suspend.

```
# /etc/nixos/configuration.nix
logind.extraConfig = "
  HandleLidSwitch=ignore
  HandlePowerKey=suspend
";
```

There was also a udev command, which shows events like lid close, but I cannot remember...
Maybe lid open does also send a lid close event or something like that? 
Or the lid close event gets triggered a second time after wakeup.

**Comment by mikael-andersson** [comment]
Thanks for the tip and the quick reply!

It could very well be either of those things you mention, I suppose.

The power key will not suspend after these additions although the systemd-logind.service was restarted. Do I need to reboot?

Do you have any ideas what files may be affected? Then I can try to do git diff between 16.03 and 16.09 for those files.

**Comment by Mic92** [comment]
I think it is a kernel or hardware problem. You only need: 
```
sudo nixos-rebuild switch -K
```

systemd-logind should be restarted after this change.
Otherwise `systemctl restart systemd-logind` definitely should do the job.

Is this maybe related to: https://github.com/systemd/systemd/issues/2807 ?

**Comment by groxxda** [comment]
@Mic92  you were probably talking about `udevadm monitor` 
I think that handling of lidswitch by logind may be new in 16.09.
@mikael-andersson do you have any other software installed that could case the suspend? `acpid` for example? Which desktop environment are you using?

**Comment by mikael-andersson** [comment]
@Mic92 I suppose it could be related to that issue. I am not able to suspend my laptop with the power button but what is more interesting is that your configuration suggestion now made it work properly.

@groxxda No, I have not explicitly installed acpid, but I found out that I have a process ktpacpid running. Is it good or bad? :) I am running KDE at the moment by the way.

Do you think there is a conflict between ktpacpid and systemd?

Thanks for the tip about udevadm monitor, I might look into it, I have some other issues that I need to resolve where it can be useful. :)

**Comment by Mic92** [comment]
Yes. Looks both system are in conflict.

**Comment by Mic92** [comment]
Maybe, this could be solved for all KDE users like mentioned in this [Bugtracker](https://bugzilla.redhat.com/show_bug.cgi?id=910240)

**Comment by Mic92** [comment]
KDE does disable systemd-logind suspend: https://wiki.archlinux.org/index.php/Power_management#Power_managers

The question is, why this is not done on Nixos properly.

**Comment by mikael-andersson** [comment]
I suppose the nicest solution is to let KDE take the internal locks as is pointed out here: https://bugzilla.redhat.com/show_bug.cgi?id=910240#c2

As long as NixOS is not taking care of it, I think it should at least be documented on NixOS wiki that either KDE's or systemd's power manager must be used to not conflict with each other.

How should I/we proceed with this?
