### ISSUE TITLE
Request to update to vscode 1.71.0

### ISSUE THREAD

**Issue by aserowy** [NixOS/nixpkgs#189820]
###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vscode
current version: 1.70.2
desired version: 1.71.0

###### Notify maintainers
maintainers:
@samuela 
@bobby285271 
@billewanick 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by aserowy** [comment]
I can PR the update myself, if you leave me a short guide on what i have to do :)

Regards
Alexander

**Comment by bobby285271** [comment]
If you are using unstable, you can wait for the channel to update: https://nixpk.gs/pr-tracker.html?pr=189383

Feel free to do a backport if you are using 22.05.

**Comment by aserowy** [comment]
ty, the merged pr slipped through my fingers! sry for the false alarm :D
