### ISSUE TITLE
Trying to figure out lm-sensors

### ISSUE THREAD

**Issue by erlandsona** [NixOS/nixpkgs#18991]
## Issue description

I'm trying to get lm_sensors to work as the fans won't stop blowing at what seems like full speed or 80 - 90% full speed.
### Steps to reproduce

I ran `sudo sensors-detect` with the defaults - it took me through the scanning steps and finished with.

```
Now follows a summar of the probes I have just done.

Driver `coretemp':
  * Chip `Intel digital thermal sensor' (confidence: 9)

Do you want to generate /etc/sysconfig/lm_sensors? (yes/NO):
To load everything that is needed, add this to one of the system
initialization scripts (e.g. /etc/rc.d/rc.local):

#--- cut here ---
# Chip Drivers
modprobe coretemp
/usr/local/bin/sensors -s
#--- cut here ---

You really should try these commands right now to make sure everything
is working properly. Monitoring programs won't work until the needed
modules are loaded.

Unloading i2c-dev... OK
Unloading cpuid... OK

$
```

In which it said I needed to add something to my kernel modules but I'm not really sure what that means or how to do that.

Then `sudo pwmconfig` but it gave me There are no pwm-capable sensor modules installed.

I did some digging and realized I need to set these things up in my configuration.nix file. Not really sure what to put in there though.

I'm still relatively new to Nixos but I'm proud to say I got it installed and working on my machine so much faster than I got Arch linux running on my Mac Book Pro thanks to the nixos-install process which made it all relatively trivial. Now I just need to iron out the kinks and get musnix working!
## Technical details
- System: Acer Predator G9-792-74YC
  - NixOS: 16.03.1299.a8e0739 (Emu)
- Nix version: 1.11.2
- Nixpkgs version: 16.03.1299.a8e0739 (Emu)

**Comment by ericsagnes** [comment]
Maybe [`mbpfan`](https://github.com/NixOS/nixpkgs/blob/24f79464899a7db23886f148781374630e201912/pkgs/os-specific/linux/mbpfan/default.nix) can help?

**Comment by erlandsona** [comment]
How so?
Does the Acer Predator have the same sort of hardware as a MacBook Pro?

More importantly, I'm still learning / tweaking knobs per se... So an example or some sort of documentation would be greatly appreciated. Thank you so much for your time.

**Comment by ericsagnes** [comment]
Sorry, I confused with the Mac Book Pro mentioned in the last paragraph.

**Comment by jcumming** [comment]
IIRC, with recent hardware the BIOS manages fans, exposing controls through ACPI thermal zones. 

If the fans are running 80-90% capacity, use `sensors` from  `lm_sensors` with the `coretemp` module to see if the processor cores are hot. If they're at room temperature, then you might have a problem...

**Comment by erlandsona** [comment]
@jcumming thanks! That sounds accurate. My issue primarily is Im still new to some of the Nix concepts and I'm not sure what to do with the sensors info or how to configure lm_sensors for a NixOS environment?

I'm on my phone at the moment but generally the output from sensors indicates the cores running nice and cool right around room temp.

I haven't seen any settings to control fan speed from the bios (f2 boot menu)?

I think my main issue is Im not really sure how to configure lm_sensors for NixOS? And I haven't seen much in the way of documentation for fan speed control. That or I'm just missing some rudimentary understanding of Linux which is also highly likely as I'm coming at this from being terminal happy on MacOSX.

**Comment by bjornfor** [comment]
@erlandsona: Maybe this configuration.nix file snippet will help you:

```nix
  # Enable many sensors (try running "sensors" now and see the
  # difference). Module names were found by running "sudo sensors-detect".
  boot.kernelModules = [ "coretemp" "nct6775" ];
```

**Comment by erlandsona** [comment]
So I added `boot.kernelModules = [ "coretemp" ];` to my /etc/nixos/configuration.nix. Saved and ran `sudo nixos-rebuild switch`. 
Fans are still blowing at 80% and sensors is showing ~80ºF (~30ºC) temps for the cores...

My current configuration.nix can be found https://bitbucket.org/erlandsona/.dotfiles/src/2b73da3b961265539d997372f525bcde45984d5a/configuration.nix?at=master&fileviewer=file-view-default

It's only ~120 lines so I definitely feel like I'm missing something obvious...

Also network manager isn't working right? I'll add my hardware-configuration.nix to the repo as well...

Thank you all so much for your time helping me with this. I really want to use nix because the philosophically this os will save me loads of headache down the road. But it does feel a bit like learning Vim at the moment.

**Comment by erlandsona** [comment]
Extra info... I've got a Killer Networking 1535 wireless chip in the machine... maybe this is relevant for networking?
http://www.killernetworking.com/product-support/knowledge-base/17-linux

**Comment by bjornfor** [comment]
> My current configuration.nix can be found https://bitbucket.org/erlandsona/.dotfiles/src/2b73da3b961265539d997372f525bcde45984d5a/configuration.nix?at=master&fileviewer=file-view-default

It requires a login.

> Extra info... I've got a Killer Networking 1535 wireless chip in the machine... maybe this is relevant for networking?
http://www.killernetworking.com/product-support/knowledge-base/17-linux

Probably. (Sorry, cannot help.)

**Comment by erlandsona** [comment]
Oh my bad! Didn't realize I made my bitbucket dotfiles a private repo. I just opened up access so you shouldn't need a login.

**Comment by bjornfor** [comment]
@erlandsona: Looks to me like the NixOS part of your problem is solved(?). (If you have trouble with fan control, maybe contact upstream?) Close?
