### ISSUE TITLE
Update Espanso and add Espanso Wayland

### ISSUE THREAD

**Issue by dit7ya** [NixOS/nixpkgs#189978]
Espanso has not been updated in a while - the current release is 2.1.6 while we only have 0.7.3

Also, espanso does not work on Wayland, and upstream has a wayland version, which got packaged to AUR -  https://aur.archlinux.org/packages/espanso-wayland

https://github.com/espanso/espanso

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.7.3
desired version: 2.1.6-beta

###### Notify maintainers

maintainers: @kimat

###### Note for maintainers

Please tag this issue in your PR.

**Comment by mimame** [comment]
Hi @dit7ya 
I would like to help you to update espanso to the last version because it's too complex to do it by myself
What do you think?

**Comment by K1aymore** [comment]
Check out PR #208949

**Comment by hugosenari** [comment]
#208949 closed
#231062 is new one, ready for reviews.

**Comment by hervyqa** [comment]
how to run `espanso-wayland` with systemd service if there is no options `services.espanso.package` to replace `espanso` to `espanso-wayland`?
https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=espanso

**Comment by fearlessgeekmedia** [comment]
I'd also like to know how exactly I'm supposed to run espanso on Wayland. Using Hyprland here.
