### ISSUE TITLE
zld fails to build

### ISSUE THREAD

**Issue by cherryblossom000** [NixOS/nixpkgs#189952]
### Steps To Reproduce
1. `nix-build '<nixpkgs>' -A zld`

### Build log
```
these 2 derivations will be built:
  /nix/store/i9abs3d039b60m5x6wlmpr0kxzj1krsx-source.drv
  /nix/store/92vvs8ba68w37sfcvhj6g7v8m3k79jn5-zld-1.3.4.drv
building '/nix/store/i9abs3d039b60m5x6wlmpr0kxzj1krsx-source.drv'...

trying https://github.com/michaeleisel/zld/releases/download/1.3.4/zld.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2306k  100 2306k    0     0  1819k      0  0:00:01  0:00:01 --:--:--     0
unpacking source archive /private/tmp/nix-build-source.drv-0/zld.zip
error: hash mismatch in fixed-output derivation '/nix/store/i9abs3d039b60m5x6wlmpr0kxzj1krsx-source.drv':
         specified: sha256-4yTh5Ky+8WfqtudAsyWiPB982CsqjR3tsYk24Gdm7ec=
            got:    sha256-w1Pe96sdCbrfYdfBpD0BBXu7cFdW3cpo0PCn1+UyZI8=
error: 1 dependencies of derivation '/nix/store/92vvs8ba68w37sfcvhj6g7v8m3k79jn5-zld-1.3.4.drv' failed to build
```

### Additional context
```console
❯ nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"22.11pre405756.21de2b973f9"
```

### Notify maintainers

@rgnns

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(cherryblossom): `"darwin, home-manager, nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by winterqt** [comment]
Looks like the hash in #188830 is invalid somehow, and nobody caught it since OfBorg and Hydra don't build this package, and nobody built it on Darwin to make sure.

@astutecat How did you get `1rzdcrky0dl9n7niv39a5gc7q7rwl8jv6h77nvm6gwdymkjf2973`, did you test building the package with that hash?

**Comment by astutecat** [comment]
Hi, thanks for filing a PR to fix the hash, it appears that in my hurry to include this update, I forgot to add `--unpack` to the nix-prefetch-url call I made. 

Apologies for the inconvenience, I'll be more careful next time and actually check stuff works before rushing to get a PR in.
