### ISSUE TITLE
Packaging request: Rounded Window Corners - GNOME Shell Extension

### ISSUE THREAD

**Issue by Nytrona** [NixOS/nixpkgs#189930]
**Project description**
_A gnome-shell extensions that try to add rounded corners for all windows_

**Metadata**

* homepage URL: https://extensions.gnome.org/extension/5237/rounded-window-corners/
* source URL: https://github.com/yilozt/rounded-window-corners
* license: GPL-3.0
* platforms: linux

**Comment by z0al** [comment]
It has [been added](https://search.nixos.org/packages?channel=unstable&show=gnomeExtensions.rounded-window-corners&from=0&size=50&sort=relevance&type=packages&query=rounded-window-corners) but 2 versions behind
