### ISSUE TITLE
nix package unavailable: 404 Not found

### ISSUE THREAD

**Issue by robberer** [NixOS/nixpkgs#19000]
## Issue description

I'm unable to download any NIX version from Hydra.

https://hydra.nixos.org/project/nix#tabs-releases

I'm trying to upgrade my NIXOS with a newer version and I need the .nixpkg file to so.

### Steps to reproduce

Try downloading any .nixpkg file from the link above

## Technical details

* System: 14.04.git.ca55f6c (Baboon)
* Nix version: nix-env (Nix) 1.7
* Nixpkgs version: "14.04.630.8a3eea0"

**Comment by robberer** [comment]
Got it working with this command: `nix-env -i /nix/store/356dj8w9171dajl0wq32m41dhg2ngq35-nix-1.11.2` . It was mentioned in another issue #15344 .

But this is really bad. Why not putting the .nixpkgs packages to http://nixos.org/releases/nix/latest/ or at least make it available on Hydra.

**Comment by Mic92** [comment]
How is in administrative charge of nixos.org? This problem is related to: https://github.com/NixOS/nixpkgs/issues/18914 in some way.

**Comment by robberer** [comment]
Yeah, in some way :-) . Looks like PingPong:

#19000
#17631
#15344
#1021

Upgrading should be as simple as saying Yes or NO and not to dig out the latest Github issues or dev comments. Sorry, I have a high opinion of NixOS and Nix in general, but by not providing a "simple" upgrade for users who already are using Nix is something I'm afraid of.

**Comment by Mic92** [comment]
I think this is related to: https://hydra.nixos.org/job/nix/master/release#tabs-constituents

**Comment by domenkozar** [comment]
The correct link is http://nixos.org/releases/nix/nix-1.11.4/
