### ISSUE TITLE
MythTV: 31.0 -> 32.0

### ISSUE THREAD

**Issue by kleytr6s** [NixOS/nixpkgs#190082]
MythTV 
current version 31.0 
desired version 32.0

Note to maintainer
@https://github.com/titanous
I tried installing Mythtv 31.0 in the latest version of NixOS and the following error appeared.
collect2: error: ld returned 1 exit status
       > make[2]: *** [Makefile:205: mythavtest] Error 1
       > make[2]: Leaving directory '/build/source/mythtv/programs/mythavtest'
       > make[1]: *** [Makefile:67: sub-mythavtest-make_first] Error 2
       > make[1]: Leaving directory '/build/source/mythtv/programs'
       > make: *** [Makefile:66: programs] Error 2
       For full logs, run 'nix log /nix/store/i7hayl96078skrs46yksjqxjsh31cmfv-mythtv-31.0.drv'. 

Reading the log displayed   error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

**Comment by acarrico** [comment]
I am currently building MythTV 32.0 (sha256 = "0i4fs3rbk1jggh62wflpa2l03na9i1ihpz2vsdic9vfahqqjxff1") with two patches. The first is called ```disable-os-detection.patch```:

```
diff -Naur a/configure b/configure
--- a/configure	2022-04-20 16:54:16.201216465 -0400
+++ b/configure	2022-04-22 14:39:29.998895626 -0400
@@ -5894,9 +5894,9 @@
     die "ERROR: cannot find soundtouch 1.8.0 or later."
 fi
 
-if [ $target_os = "linux" ] ; then
-    . /etc/os-release
-fi
+#if [ $target_os = "linux" ] ; then
+#    . /etc/os-release
+#fi
 
 # libudfread
 if enabled system_libudfread ; then
```

The second patch is called ```fix-qmake-var-syntax.patch```.  I patched it up [upstream](https://github.com/MythTV/mythtv/issues/549), and it looks like my patch has been [merged](https://github.com/MythTV/mythtv/pull/550). Here is that patch:

```
diff -Naur b/configure c/configure
--- b/configure	2022-04-22 14:39:29.998895626 -0400
+++ c/configure	2022-04-22 14:38:36.688266601 -0400
@@ -6296,7 +6296,7 @@
 
 # add some linker flags
 check_ldflags -Wl,--warn-common
-check_ldflags '-Wl,-rpath-link,\${SRC_PATH_BARE}/external/FFmpeg/libpostproc:\${SRC_PATH_BARE}/external/FFmpeg/libswresample:\${SRC_PATH_BARE}/external/FFmpeg/libswscale:\${SRC_PATH_BARE}/external/FFmpeg/libavfilter:\${SRC_PATH_BARE}/external/FFmpeg/libavdevice:\${SRC_PATH_BARE}/external/FFmpeg/libavformat:\${SRC_PATH_BARE}/external/FFmpeg/libavcodec:\${SRC_PATH_BARE}/external/FFmpeg/libavutil:\${SRC_PATH_BARE}/external/FFmpeg/libavresample'
+check_ldflags '-Wl,-rpath-link,\$\${SRC_PATH_BARE}/external/FFmpeg/libpostproc:\$\${SRC_PATH_BARE}/external/FFmpeg/libswresample:\$\${SRC_PATH_BARE}/external/FFmpeg/libswscale:\$\${SRC_PATH_BARE}/external/FFmpeg/libavfilter:\$\${SRC_PATH_BARE}/external/FFmpeg/libavdevice:\$\${SRC_PATH_BARE}/external/FFmpeg/libavformat:\$\${SRC_PATH_BARE}/external/FFmpeg/libavcodec:\$\${SRC_PATH_BARE}/external/FFmpeg/libavutil:\$\${SRC_PATH_BARE}/external/FFmpeg/libavresample'
 enabled rpath && add_ldexeflags -Wl,-rpath,$libdir
 enabled rpath && add_ldlibflags -Wl,-rpath,$libdir
 test_ldflags -Wl,-Bsymbolic && append SHFLAGS -Wl,-Bsymbolic
```

My current ```default.nix``` derivation is like this:

```
  version = "32.0";

  src = fetchFromGitHub {
    owner = "MythTV";
    repo = "mythtv";
    rev = "v${version}";
    sha256 = "0i4fs3rbk1jggh62wflpa2l03na9i1ihpz2vsdic9vfahqqjxff1";
  };

  patches = [
    # Disables OS detection in configure script
    ./disable-os-detection.patch
    ./fix-qmake-var-syntax.patch
  ];
```

Sorry that was back in April and I didn't propagate my changes to NixOS yet!

**Comment by acarrico** [comment]
@zero-one01 it looks like your branch and mine are basically the same except for the ```fix-qmake-var-syntax.patch```.  I don't know if it is better to add my patch, or for you to move to a version of MythTV after the pull mentioned above.

**Comment by acarrico** [comment]
@kleytr6s, I didn't paste my whole default.nix, there are also new deps (soundtouch, libzip) which you can see in the branch by @zero-one01

**Comment by acarrico** [comment]
I added the ```fix-qmake-var-syntax``` patch on top of @zero-one01 's  branch [here](https://github.com/acarrico/nixpkgs/tree/fix-190082). I haven't tried building it yet since my machine is already building my original version of the derivation in the background (due to NixOS upgrade), and it takes hours. That is actually what prompted me to notice this issue :).

**Comment by zero-one01** [comment]
@acarrico I'll try if my issue is gone with your patch now (I also need lots of time for one build).

Going forward I think it's best to use the release version of MythTV 32 and your patch for bumping the version in NixOS.
I'll however try the other route with the MythTV version after the merge of your fix as I want to set up a combination of official and my own packages anyway.

**Comment by zero-one01** [comment]
I'm happy to confirm that both routes work. for the one with the updated MythTV version I took the commit of the pull request @acarrico mentioned.

@acarrico would you be so kind and open a pull request for the version bump ?
