### ISSUE TITLE
buildBazelPackage: provide a way to run the tests, maybe have a `bazelTestTarget` ?

### ISSUE THREAD

**Issue by hzeller** [NixOS/nixpkgs#190095]
It would be good to be able to run bazel tests in the `checkPhase`.

Due to the magic that the `buildBazelPackage` does in the background (fetching/accessing the fixed output derivation, setting various flags...), it is not  as easy as simply running `bazel test //...`

## Wish
Similar to the `bazelTarget`, I'd like to be able to set `bazelTestTarget` that then executes `${bazel with all the magic} test ${bazelTestTarget}` if `doCheck = true`.

I suspect it might be easily derived from the regular build rule, however I am not as versed yet in nix to be able to contribute that.

(context: I am maintaining [verible](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/verible/default.nix) and would like to run the tests as part of the build checks).

**Comment by hzeller** [comment]
CC: @NixOS/bazel

**Comment by hzeller** [comment]
@aherrmann do you think this would be easy to add ?
I certainly think this would be very useful as running the tests will improve the confidence and robustness of a release.

**Comment by aherrmann** [comment]
I agree this would be useful. It sounds feasible.
@ylecornec did you have a chance to look into this, yet? Any findings so far?

**Comment by ylecornec** [comment]
Yes, adding a `bazelTestTargets` attibute and running these tests before the actual build seems to work (I tested it on the `verible` package).

I will clean the code a bit and open a PR.

**Comment by avdv** [comment]
Closing, since https://github.com/NixOS/nixpkgs/pull/192639 has been merged. Please re-open if there is still something missing.
