### ISSUE TITLE
Package request: nix-serve-ng

### ISSUE THREAD

**Issue by ivan** [NixOS/nixpkgs#190161]
**Project description**

> nix-serve-ng, a backwards-compatible Haskell rewrite of [nix-serve](https://github.com/edolstra/nix-serve) (a service for hosting a /nix/store as a binary cache). It provides better reliability and performance than nix-serve (ranging from ≈ 1.5× to 32× faster).

https://www.haskellforall.com/2022/09/nix-serve-ng-faster-more-reliable-drop.html

**Metadata**

* homepage URL: https://github.com/aristanetworks/nix-serve-ng
* source URL: https://github.com/aristanetworks/nix-serve-ng
* license: bsd3
* platforms: linux

**Comment by Kranzes** [comment]
it will be packaged automatically for the haskellPackages package set.
