### ISSUE TITLE
Update python poetry from 1.1.4 to 1.2.0

### ISSUE THREAD

**Issue by yawhide** [NixOS/nixpkgs#190185]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: poetry
https://search.nixos.org/packages?channel=unstable&show=poetry&from=0&size=50&sort=relevance&type=packages&query=poetry

current version: 1.1.4
desired version: 1.2.0

https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md

###### Notify maintainers

maintainers: @adisbladis @jbaum98 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by rszamszur** [comment]
FYI, there is already PR awaiting in the upstream: https://github.com/nix-community/poetry2nix/pull/704

**Comment by yawhide** [comment]
Great news :tada:

**Comment by austinbutler** [comment]
PR linked above is merged. Looks like the nixpkgs PR is blocked: https://github.com/NixOS/nixpkgs/pull/193552

**Comment by sciyoshi** [comment]
I think this can be closed now that https://github.com/NixOS/nixpkgs/pull/195449 is merged.

**Comment by yawhide** [comment]
I can confirm: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/poetry/default.nix#L44

In the future, would it make more sense to create an issue here: https://github.com/nix-community/poetry2nix?
or did I do the right thing to make an issue in this repo?

**Comment by austinbutler** [comment]
I don't think you did anything wrong. It's a bit confusing, from what I can tell there's a top-level `poetry` that is tied to `poetry2nix`, then there's a separate Python package for Poetry, such as `python310Packages.poetry`, which had already been updated to 1.2.0.

Assuming that doesn't change then yeah reporting to `poetry2nix` would probably be a more direct way of getting it done. But updates were needed in `nixpkgs` anyways, so IMO this issue was fine.

**Comment by yawhide** [comment]
@austinbutler thanks.

another question: say the latest poetry update fixed some critical bugs. would I open another PR asking to update again? what is the best practice here?

**Comment by adisbladis** [comment]
> another question: say the latest poetry update fixed some critical bugs. would I open another PR asking to update again? what is the best practice here?

You could open another issue, or just wait a bit. We're usually only hours behind upstream and normally not more than a few days.
