### ISSUE TITLE
nix-channel: unable to check ‘http://nixos.org/channels/nixos-unstable’ on launch EC2 instance from AMI

### ISSUE THREAD

**Issue by matejc** [NixOS/nixpkgs#19010]
## Issue description

After building AMI and launching instance on AWS...

journalctl entries for `stage-2-init` are:

```
Sep 27 14:29:05 localhost stage-2-init: running activation script...
Sep 27 14:29:05 localhost stage-2-init: setting up /etc...
Sep 27 14:29:05 localhost stage-2-init: attempting to fetch configuration from EC2 user data...
Sep 27 14:29:05 localhost stage-2-init: /nix/store/vykgd7rpwm3hjvj91ny0nxhl7cppmps0-nix-1.11.4/bin/nix-channel: unable to check ‘http://nixos.org/channels/nixos-unstable’
```

Debugging shows that resolv.conf is empty at the time... so nixos.org could not be resolved because it starts building if I add line

```
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
```

to somewhere around this line https://github.com/NixOS/nixpkgs/blob/bee04a37ad9157fa7992b80df53919759b1ebffd/nixos/modules/virtualisation/amazon-init.nix#L14
and then rebuild the system and reboot to repeat the process.
### Steps to reproduce

build AMI image with

```
nix-env -iA awscli 
nix-env -iA qemu 
nix-env -iA ec2_api_tools 
nix-env -iA jq 

export AWS_ACCOUNT="############"
export AWS_ACCESS_KEY_ID="#############"
export AWS_SECRET_ACCESS_KEY="###########"

./nixpkgs/nixos/maintainers/scripts/ec2/create-amis.sh
```

OR just click on the `ami-17a45178` (nixos-16.03.1073.73e28bc-x86_64-hvm-ebs) on http://nixos.org/nixos/download.html, 
- Launch instance with this AMI inside AWS with this userdata:

```
### http://nixos.org/channels/nixos-unstable nixos

{
  imports = [ <nixpkgs/nixos/modules/virtualisation/amazon-image.nix> ];
  ec2.hvm = true;
  security.sudo.wheelNeedsPassword = false;
  users.extraUsers.matejc =
    { createHome      = true;
      home            = "/home/matejc";
      description     = "Matej";
      extraGroups     = [ "wheel" ];
      useDefaultShell = true;
      openssh.authorizedKeys.keys = [
        "ssh-rsa ....."
      ];
    };
}
```
- check the journalctl -b
## Technical details
- Tried on Nixpkgs versions: 16.09beta437.210ebb5 and 17.03pre92039.adfcc2d and nixos-16.03.1073.73e28bc

**Comment by Profpatsch** [comment]
Sorry that there was no reply, feel free to reopen if it’s still an issue.
