### ISSUE TITLE
NixOS: nativeBuildInputs do not work

### ISSUE THREAD

**Issue by ck3d** [NixOS/nixpkgs#190289]
### Describe the bug

Derivations defined with pkgs are not compatible with cross compilation as defined in Nixpkgs manual.
This is the case for all derivation defined in NixOS modules.

### Steps To Reproduce

Following derivation fails to build, since pkgs is used:
```nix
with (import <nixpkgs> { crossSystem.system = "aarch64-linux"; });
runCommand "bad" { nativeBuildInputs = [ jq ]; } "jq > $out"
```

Following dervation builds, since __splicedPackages is used:
```nix
with (import <nixpkgs> { crossSystem.system = "aarch64-linux"; }).__splicedPackages;
runCommand "good" { nativeBuildInputs = [ jq ]; } "jq > $out"
```

The NixOS module system uses not __splicedPackages and therefor all derivations defined with pkgs which depends on nativeBuildInputs will fail to cross compile.

### Workaround

Select the package by hand and do not use stdenv cross compilation automatism:

```nix
with (import <nixpkgs> { crossSystem.system = "aarch64-linux"; });
runCommand "workaround" { } "${pkgsBuildBuild.jq}/bin/jq > $out"
```

### Expected behavior

Derivations defined in NixOS modules can be cross compiled.

**Comment by ck3d** [comment]
That's true, but not all parts in nixos uses `callPackage` and I did not expect this behavior.
I created a PR to fix this issue.

**Comment by Artturin** [comment]
(linking the main issue https://github.com/NixOS/nixpkgs/issues/49526)
