### ISSUE TITLE
Lorien

### ISSUE THREAD

**Issue by DerDennisOP** [NixOS/nixpkgs#190371]
**Project description**
Lorien is an infinite canvas drawing/note-taking app that is focused on performance, small savefiles and simplicity.

**Metadata**

* homepage URL: https://github.com/mbrlabs/Lorien
* source URL: https://github.com/mbrlabs/Lorien
* license: mit
* platforms: linux, darwin, windows

**Comment by DerDennisOP** [comment]
this link is: "Not found". And I cant find it on nixos.org/packages

**Comment by DerDennisOP** [comment]
> looks like we already have it in nixpkgs: https://github.com/NixOS/nixpkgs/blopkgs/applications/graphics/lorien/default.nix
> 
> #164178

found it on unstable branch, thanks a lot

**Comment by figsoda** [comment]
> this link is: "Not found". And I cant find it on nixos.org/packages

my bad, i edited the link on accident, this is the actual link
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/lorien/default.nix
