### ISSUE TITLE
JetBrain products cannot start -- "The IDE cannot execute a test script in the directory"

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#190316]
### Describe the bug
JetBrain products cannot run on Guix System. I don't know the root cause, but I've identified a potential problem.
As part of the startup, the products creates a temporary file, and assumingly tries to execute this.

The generated file looks like
```
#!/bin/sh
exit 0
```

On my system, `/bin/sh` links to a bash in guix: `/gnu/store/d99ykvj3axzzidygsmdmzxah4lvxd6hw-bash-5.1.8/bin/sh`.

The file is created executable by my user, and I'm able to execute the script.

The error message:

```
Invalid Temp Directory
The IDE cannot execute a test script in the directory.
Possible reason: the partition is mounted with 'no exec' option.

If you have modified the 'idea.system.path' property, please make sure it is correct,
otherwise, please re-install the IDE.

-----
Location: /home/simendsjo/.cache/JetBrains/Rider2022.2/tmp
java.io.IOException: Unexpected exit value: 1
```

### Steps To Reproduce
1. Use Guix System
2. Install jetbrains.rider or jetbrains.datagrip through nix (the ones I tested)
3. Run program

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.5, Guix System, noversion, nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(simendsjo): `"nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `/home/simendsjo/.nix-defexpr/channels/nixpkgs`
```

**Comment by simendsjo** [comment]
I found a similar issue: https://github.com/netblue30/firejail/issues/3480
The problem was that /home was mounted with noexec (as the error message indicates).
It doesn't look like that is the case here though:

```
$ nix-env -p jetbrains.rider

[nix-shell:~]$ mount | grep -i noexec
none on /run/systemd type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
```

**Comment by simendsjo** [comment]
Found the "offending" code, and it doesn't look wrong, but I cannot reproduce this: https://git.jetbrains.org/?p=idea/community.git;a=blob;f=platform/platform-impl/src/com/intellij/idea/StartupUtil.kt;h=621a9ec75b3ff5293be8420ff862f9346b0975dc;hb=HEAD#l795

**Comment by raphaelr** [comment]
I can't reproduce it on NixOS or Kubuntu, so I assume this is a guix specific issue - maybe rider runs in a mount namespace that doesn't have /bin/sh?

**Comment by simendsjo** [comment]
> I can't reproduce it on NixOS or Kubuntu, so I assume this is a guix specific issue - maybe rider runs in a mount namespace that doesn't have /bin/sh?

Strange. I've asked over at r/guix: https://www.reddit.com/r/GUIX/comments/x9o8q8/guix_system_gets_in_the_way_for_a_local_nix/

**Comment by simendsjo** [comment]
Unrelated to this issue, I have a workaround for running Rider on my system:
- Using the nonguix channel, install dotnet
- Install rider through flatpak
- Launch using `flatpak --user run --filesystem=~/.guix-profile/share/dotnet com.jetbrains.Rider`
- Manually set the dotnet binary in settings

**Comment by simendsjo** [comment]
I think this is only a Guix issue, completely unrelated to Nix. I downloaded Rider manually, and patched all binaries/libraries. Starting rider gives me the same error even though Nix isn't involved.

**Comment by kapsh** [comment]
@simendsjo I had similar issue with another JB IDE on another distro, landed here from search anyway. The real issue were missing permissions on some files in JRE. 
If you are running IDE with jetbrains-runtime (bundled in jbr subdir or installed separately), check files `lib/{jcef_helper,jexec,jspawnhelper}` inside it, they should be executable.
