### ISSUE TITLE
security.acme.certs fails to renew certs if email has changed.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#190493]
### Describe the bug

When the ACME email address has changed renewal fails with error "Account me@example is not registered. Use 'run' to register a new account.".

### Steps To Reproduce
1. Setup `security.acme.certs` to issue a certificate.
2. Change `security.acme.certs.<name>.email` to something else.
3. Wait for renewal to run.

### Expected behavior

The module re-registers and issues a certificate.

### Screenshots

```
2022/09/09 09:35:54 Account kevin@example is not registered. Use 'run' to register a new account.
```

### Additional context

It appears that this situation should be detected and a "fresh" run should be performed. (Or maybe we should ask upstream to allow renew to re-register.

### Notify maintainers

@aanderse @andrew-d @arianvp @emily @flokli @m1cr0man

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.5, NixOS, 22.11 (Raccoon), 22.11pre405560.2da64a81275`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(kevincox): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by kevincox** [comment]
The problem may be here:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme/default.nix#L379

We are checking that we have an account, but not checking that it actually matches `accountHash`.

**Comment by kevincox** [comment]
I have a possible fix here: https://github.com/NixOS/nixpkgs/commit/904276066ba98811ef755ea29f512f1240ff2db8

It definitely isn't production ready because we remove the hardcoded domain but unblocked me. Maybe we can just use a `*` as there should only be one domain per account hash? Or we just do the API URL mangling that I presume is where this comes from.

**Comment by m1cr0man** [comment]
Hey thanks for the bug report. I've not been able to reproduce this. I [created a test](https://github.com/m1cr0man/nixpkgs/commit/d628af463ad24a7e2fe0ed1380bbaec58a4ad97a#diff-6c35ab23c4eabfad5626d09cace05b501531016ec4a1509a33874fab651014f6) to force renewal (using validMinDays) and an email change, and the module correctly identifies the change in account details and performs a "run" rather than a "renew", which in turn registers the new account.

The account change detection happens above where you pointed out in your example fix - [a hash is generated](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme/default.nix#L14) out of the account related options and used to create a [unique folder](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/security/acme/default.nix#L163) for those credentials.

Example output from the tests (abbreviated):
```
webserver: must succeed: /run/current-system/specialisation/general/bin/switch-to-configuration test
...
webserver # [   17.426560] acme-http.example.test-start[1080]: ACCOUNT HASH d590213ed52603e9128d
webserver # [   17.427820] acme-http.example.test-start[1080]: + cmp -s domainhash.txt certificates/domainhash.txt
webserver # [   17.439019] acme-http.example.test-start[1080]: + lego --accept-tos --path . -d http.example.test --email hostmaster@example.test --key-type ec256 --http --http.port :80 --server https://acme.test/dir run
webserver # [   18.116908] acme-http.example.test-start[1082]: 2022/09/18 23:16:55 No key found for account hostmaster@example.test. Generating a P256 key.
...
webserver: must succeed: /tmp/specialisation/changeemail/bin/switch-to-configuration test
...
webserver # [   26.983815] acme-http.example.test-start[1271]: ACCOUNT HASH 87b7f452d88c005a1ce0
webserver # [   26.985088] acme-http.example.test-start[1271]: + cmp -s domainhash.txt certificates/domainhash.txt
webserver # [   26.989416] acme-http.example.test-start[1273]: ++ ls -1 accounts
webserver # [   26.996994] acme-http.example.test-start[1271]: + '[' -e certificates/http.example.test.key -a -e certificates/http.example.test.crt -a -n '' ']'
webserver # [   26.999384] acme-http.example.test-start[1271]: + lego --accept-tos --path . -d http.example.test --email admin@example.test --key-type ec256 --http --http.port :80 --server https://acme.test/dir run
webserver # [   27.014819] acme-http.example.test-start[1274]: 2022/09/18 23:17:04 No key found for account admin@example.test. Generating a P256 key.
```

As you can see, it correctly detects the change of email address.

What I will say is, in brainstorming possible failure points here, checking if the accounts folder is empty may not be sufficient. I'm going to upgrade it to check if a key file exists for the configured email address. I don't want to get more sophisticated than that (e.g. checking the key type, checking acmeServer) in Bash because the service script is already so complex. It should do to cover your issue.

**Comment by kevincox** [comment]
Hmm, that is a good point. Well I can confirm that I somehow got into this state and that [the commit I referenced fixed it](https://github.com/NixOS/nixpkgs/commit/904276066ba98811ef755ea29f512f1240ff2db8). I'm trying to figure out exactly how I managed to get there. I see that the email has been part of the account hash for years (https://github.com/NixOS/nixpkgs/commit/85769a8cd8012e5dfb907f49555ccc7c3c5a9d35).

Now I'm wishing I had logs of what was in that accountHash directory. Because even the fix is checking in the existing directory. Maybe there is some way that we can create a subdirectory there before registering? Or maybe registration failed?

**Comment by m1cr0man** [comment]
My best guess is that registration failed for some reason, but the folders were created. If you changed email -> "run" happens but registration fails -> next run may detect a folder but it is empty.

I've created a [draft PR](https://github.com/NixOS/nixpkgs/pull/191861) and you can [see the fix](https://github.com/NixOS/nixpkgs/pull/191861/files#diff-f72bfee4e4288266759893ea9ae9b14380c9169157e61dae1a35132757b387e0R381) I've implemented here. This should be more than enough to catch your case.

**Comment by kevincox** [comment]
Unfortunately my logs don't go back far enough. The earliest record I have of this occuring is:

```
2022/07/21 04:53:27.154 -0400	+ set -euo pipefail
2022/07/21 04:53:27.155 -0400	+ cmp -s domainhash.txt certificates/domainhash.txt
2022/07/21 04:53:27.155 -0400	+ echo c228c387b7245edf24fc
2022/07/21 04:53:27.268 -0400	++ ls -1 accounts
2022/07/21 04:53:27.271 -0400	+ '[' -e certificates/s1.kevincox.ca.key -a -e certificates/s1.kevincox.ca.crt -a -n acme-v02.api.letsencrypt.org ']'
2022/07/21 04:53:27.272 -0400	+ lego --accept-tos --path . -d s1.kevincox.ca --email kevin@example --key-type ec256 --dns cloudflare -d '*.s1.kevincox.ca' -d nc.kevincox.ca renew --days 30
2022/07/21 04:53:28.233 -0400	2022/07/21 08:53:28 Account kevin@example is not registered. Use 'run' to register a new account.
2022/07/21 04:53:28.236 -0400	+ pem=out/full.pem
2022/07/21 04:53:28.236 -0400	+ is_expiration_skippable out/full.pem
2022/07/21 04:53:28.237 -0400	+ [[ -e out/full.pem ]]
2022/07/21 04:53:28.238 -0400	++ openssl x509 -noout -enddate
2022/07/21 04:53:28.238 -0400	++ set -euxo pipefail
2022/07/21 04:53:28.239 -0400	++ sed -e 's/^notAfter=//'
2022/07/21 04:53:28.239 -0400	++ grep notAfter
2022/07/21 04:53:28.390 -0400	+ [[ -n Sep 26 15:35:51 2022 GMT ]]
2022/07/21 04:53:28.390 -0400	+ expiration_line='Sep 26 15:35:51 2022 GMT'
2022/07/21 04:53:28.391 -0400	++ date -d 'Sep 26 15:35:51 2022 GMT' +%s
2022/07/21 04:53:28.501 -0400	+ expiration_date=1664206551
2022/07/21 04:53:28.503 -0400	++ date +%s
2022/07/21 04:53:28.505 -0400	+ [[ 67 -gt 30 ]]
2022/07/21 04:53:28.505 -0400	+ expiration_days=67
2022/07/21 04:53:28.505 -0400	+ expiration_s=5812943
2022/07/21 04:53:28.505 -0400	+ now=1658393608
2022/07/21 04:53:28.506 -0400	+ mv domainhash.txt certificates/
2022/07/21 04:53:28.506 -0400	nixos-acme: Ignoring failed renewal because expiration isn't within the coming 30 days
2022/07/21 04:53:28.506 -0400	+ echo 'nixos-acme: Ignoring failed renewal because expiration isn'\''t within the coming 30 days'
2022/07/21 04:53:28.554 -0400	+ chown acme:ssl_s1_kevincox_ca certificates/domainhash.txt certificates/s1.kevincox.ca.crt certificates/s1.kevincox.ca.issuer.crt certificates/s1.kevincox.ca.json certificates/s1.kevincox.ca.key
2022/07/21 04:53:28.557 -0400	+ cmp -s certificates/s1.kevincox.ca.crt out/fullchain.pem
2022/07/21 04:53:28.597 -0400	+ chmod 640 out/cert.pem out/chain.pem out/fullchain.pem out/full.pem out/key.pem
```

Interestingly it didn't occur on another server with the same ACME config. I'm not sure if I somehow bypassed it by changing the cert list or something else. Maybe lego failed part-way through such that the simple subdirectory check isn't enough but my deeper check found a file that hadn't been written yet. IDK if there is a clean way to ask lego if it thinks that an account is registered which would make this more robust and less dependent on implementation details.

**Comment by m1cr0man** [comment]
My best guess is if you configured both servers at roughly the same time you might have run into account creation rate limits from LE on the failed one. Alas, this is not the first time we've had an inexplicable failure scenario in the acme module that we just had to add checks to cover 😅  don't worry about digging into it too much, hopefully the new check for a key file will suffice 🤞

**Comment by kevincox** [comment]
Yeah, I saw the new check and it is probably good enough. It would be nice if there was an official interface for this but checking for the file should be good enough.
