### ISSUE TITLE
Could Mathematica get updated from version 13.0.1 to version 13.1.0?

### ISSUE THREAD

**Issue by pmarreck** [NixOS/nixpkgs#190419]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: mathematica

current version: mathematica-13.0.1
desired version: mathematica-13.1.0

###### Notify maintainers

maintainers: @herberteuler 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by pmarreck** [comment]
This may help:

```
❯ sha256sum Mathematica_13.1.0_BNDL_LINUX.sh
2c8a46009dee4e46608dcd18ca4c2eb32c8740a9429d3beb6464ad15f48ecfad  Mathematica_13.1.0_BNDL_LINUX.sh
```

**Comment by herberteuler** [comment]
Sorry about the delay. The old friend of Qt plugins came along, and it took some time to resolve that.
