### ISSUE TITLE
plan9port build broken on non-nixos

### ISSUE THREAD

**Issue by jxy** [NixOS/nixpkgs#19055]
## Issue description

It doesn't compile.  It goes through the installation, and after that you can find the install.sum file:

```
$ cat /sandbox/nix/store/qlwqlw4phi8ps13nphf9lw5f6s2i6xjz-plan9port-2016-04-18/plan9/install.sum
* Compiler version:
        gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
* Running on Linux: checking for NPTL...
        NPTL found.
        fontsrv dependencies found.
>>> Using LOCAL.config options:
        CFLAGS="-I/sandbox/nix/store/3c4yyhhhbjj846xih2cwfldkhjp8yni8-fontconfig-2.11.1-dev/include -I/sandbox/nix/store/y0mpj7fhg265v25xjikgf0x9i2l808z2-libXt-1.1.5-dev/include -I/sandbox/nix/store/l4vf7jp2g308rchg9l6fgd9lfqh3q825-freetype-2.6.5-dev/include"
        X11="/sandbox/nix/store/y0mpj7fhg265v25xjikgf0x9i2l808z2-libXt-1.1.5-dev/include"

* Installation failed: /tmp/nix-build-plan9port-2016-04-18.drv-0/plan9-35d4392/bin/cleanname does not exist.
```

So it finds the system gcc instead of the nixpkgs gcc, and it fails after that `cleanname` does not exist.

I put nixpkgs directory under `/sandbox/nix` for that's where I have write privilege, but I don't think it matters in this issue.
### Steps to reproduce

Install it with nix-env on a non-nixOS.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, …)

```
$ lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```
- Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.4
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre91860.124f25b"
```

**Comment by vcunat** [comment]
Work-around: such things shouldn't happen if you enable [sandboxing](http://nixos.org/nix/manual/#conf-build-sandbox-paths). Unfortunately, setting it up is a little cumbersome on non-NixOS, as you have to manually specify the paths to bash and glibc.

**Comment by KoviRobi** [comment]
In the plan 9 supplied INSTALL file, there is a line
```sh
PLAN9=`pwd` export PLAN9
PATH=/bin:/usr/bin:$PLAN9/bin:$PATH export PATH
```

I wonder if you change that (e.g. make a patch and add it to the patches in the plan9port/default.nix), will that fix this problem? Just make something simple, even if it is specific to your system, then if that fixes it we can work out the general solution

**Comment by RamKromberg** [comment]
If this is a new issue, it's possibly the freetype dependency I needed to add in https://github.com/NixOS/nixpkgs/commit/e852a8e8b609bcd2cce1747fb4d6645d4620504a#diff-4a837f76e3d9d56ba0aabaab7351ad6a to make fontsrv work properly.

Try reverting the references to _freetype_ in _builder.sh_ and _default.nix_ and see if that helps.

**Comment by Profpatsch** [comment]
Not broken on current nixpkgs anymore, though heavily outdated.
