### ISSUE TITLE
testVersion: no one follows the manual :(

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#190524]
## Issue description

The example from the manual:

```
passthru.tests.version = testVersion {
  package = seaweedfs;
  command = "weed version";
};
```

https://nixos.org/manual/nixpkgs/unstable/#tester-testVersion

Literally all instances in nixpkgs use `testers.testVersion`:

https://github.com/NixOS/nixpkgs/blob/18105ef3b7c56f55d1c36ad8a023d1a79eeab0f3/pkgs/applications/networking/seaweedfs/default.nix#L23-L24

The manual and nixpkgs should be consistent. As a contributor, i should be able to use examples from the manual (it does not even work).

`error: undefined variable 'testVersion'`

### Steps to reproduce

https://github.com/NixOS/nixpkgs/search?p=1&q=testVersion

**Comment by davidak** [comment]
To make the example from the manual work, you have to add:

```
{ testers, ... }:
let
  inherit (testers) testVersion;
in
stdenv.mkDerivation rec {
...
```

which adds 3 lines instead of `testers.`

i think it is more readable, idiomatic and elegant, but also clutters the devication... so the version used in nixpkgs seems to be pragmatic.

i suggest we update the manual to reflect nixpkgs. do you agree?

**Comment by ck3d** [comment]
I would prefer the `testers.` version. Inherits in a let block should only be used, when the attribute is need many times and is a common well known attribute, e.g. lib, version, ...

**Comment by IvarWithoutBones** [comment]
`testVersion` used to be it's own attribute before it got moved to `testers.testVersion`, I'm guessing the manual was just forgotten to be updated.

**Comment by IvarWithoutBones** [comment]
Opened a PR that updates the documentation: https://github.com/NixOS/nixpkgs/pull/190818

**Comment by Artturin** [comment]
> `testVersion` used to be it's own attribute before it got moved to `testers.testVersion`, I'm guessing the manual was just forgotten to be updated.

yup I forgot
