### ISSUE TITLE
Haskell: failure on extensions-0.0.0.1 while bumping from ghc8107 to ghc902

### ISSUE THREAD

**Issue by JeanHuguesdeRaigniac** [NixOS/nixpkgs#190654]
### Steps To Reproduce
```console
[user@system:~]$ direnv reload
```
### Build log
[gist](https://gist.github.com/JeanHuguesdeRaigniac/5e14bbd90de1d3a6056f9fba3e2d242f)
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.6.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by sternenseemann** [comment]
Upstream doesn't support GHC 9.0 yet: https://github.com/kowainik/extensions/issues/73

If only trivial changes are required to accomodate a new compiler version we usually consider carrying a downstream fix, if one is PR-ed.

**Comment by JeanHuguesdeRaigniac** [comment]
OK, thanks.
Since there is a [PR](https://github.com/kowainik/extensions/pull/75) to address it already, I will use its forked repo until it is merged.
