### ISSUE TITLE
Korganizer can't add calendars

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixpkgs#190671]
### Describe the bug

After installing Korganizer, it's not possible to add a calendar. Only the "Knut" for debugging is available.

### Steps To Reproduce
1. Install `libsForQt5.korganizer`
2. Open `korganizer`
3. Got to settings > General > Calendar
4. Try to add calendar with "Add..."

### Expected behavior

Ability to add calendars just like on ubuntu.

### Screenshots

![image](https://user-images.githubusercontent.com/2829538/189483465-d8bc67a0-017b-4b7e-a78c-ef3dac5906b6.png)

### Additional context

`-`

### Notify maintainers

@alyssais @ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.64, NixOS, 22.05 (Quokka), 22.05.2889.67e45078141`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by 2xsaiko** [comment]
You need to set `environment.pathsToLink = ["/share/akonadi"];` if not using Plasma. At least that made KDE PIM work for me.

**Comment by SuperSandro2000** [comment]
Merging with #299153
