### ISSUE TITLE
Package Request: Tauri

### ISSUE THREAD

**Issue by ScottFreeCode** [NixOS/nixpkgs#190685]
[comment: Tauri is similar to Wails (added, #136707) and Neutralino. Comparison at https://github.com/tauri-apps/tauri/discussions/3521 ]

**Project description**
_Build an optimized, secure, and frontend-independent application for multi-platform deployment._

[comment: This description is lifted from the Tauri homepage. Where Wails's is "Build applications using Go + HTML + CSS + JS", Tauri if I understand correctly is similar but uses Rust as the backend instead of Go, and might allow bundling arbitrary additional programs.]

**Metadata**

* homepage URL: https://tauri.app/
* source URL: https://github.com/tauri-apps/tauri
* license: apache-2.0
* platforms: linux, darwin, Windows, planning for mobile: https://tauri.app/v1/guides/building/cross-platform

**Comment by ScottFreeCode** [comment]
(See also #190686 )

**Comment by dit7ya** [comment]
cargo-tauri already exists in nixpkgs. Can you please clarify what exactly are you requesting for?

**Comment by ScottFreeCode** [comment]
My mistake – I searched Nixpkgs for Nixos-22.05 and forgot to check Unstable. Thanks for pointing it out to me!
