### ISSUE TITLE
ROS2 Humble

### ISSUE THREAD

**Issue by realsnick** [NixOS/nixpkgs#190619]
The Robot Operating System, is a meta operating system for robots.

* homepage URL: https://ros.org/
* source URL: https://github.com/ros2 
* license: Creative Commons Attribution 4.0 International
* platforms: linux

**Comment by jtojnar** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/11713. And it should be available in https://github.com/lopsided98/nix-ros-overlay.

**Comment by ibootstrapper** [comment]
Thank you
