### ISSUE TITLE
python/pip: ModuleNotFoundError after doing user install

### ISSUE THREAD

**Issue by nektro** [NixOS/nixpkgs#190644]
### Steps To Reproduce
1. `nix-shell -p python3 python3.pkgs.pip`
2. `pip install --user bikeshed`
3. `cd path/to/dev`
4. `bikeshed spec`

```
Traceback (most recent call last):
  File "/home/meghan/.local/bin/bikeshed", line 5, in <module>
    from bikeshed import main
ModuleNotFoundError: No module named 'bikeshed'
```

### Expected behavior
https://github.com/tabatkins/bikeshed to run properly

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.52, NixOS, 22.05 (Quokka), 22.05.1543.71d7a4c037d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nektro** [comment]
nvm its packaged as `nix-shell -p bikeshed`

**Comment by devurandom** [comment]
> nvm its packaged as `nix-shell -p bikeshed`

Is there a way to run modules that are not packages for NixOS?
