### ISSUE TITLE
kontact shows up with an empty interface

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixpkgs#190658]
### Describe the bug

After installing `libsForQt5.kontact`, the interface that shows up is completely

### Steps To Reproduce
1. Add `libsForQt5.kontact` to systemPackages in `configuration.nix`
2. `sudo nixos-rebuild switch`
3. `kontact`

### Expected behavior

See the standard Kontact interface will all the apps:

![image](https://user-images.githubusercontent.com/2829538/189478570-8c63b296-3e25-4656-8288-cdf506c26de1.png)

### Screenshots

Actual result

![image](https://user-images.githubusercontent.com/2829538/189478595-1ac3a0be-742c-4b7c-89d9-884ed05cce8a.png)

### Additional context

The "Kontact Suite" promises, [according to the KDE wiki](https://kontact.kde.org/), to

> Handle your email, calendar, contacts and other personal data with Kontact. Kontact groups everything together in one place and helps you manage your communications, organize your day and work with your colleagues. Become more productive with Kontact.

That means the package should depend on:

 - kmail
 - kaddressbook
 - korganizer
 - akregator

Additionally, there's a `libsForQt5.kontactinterface` package that has no executable binary yet seems related to `kontact`. What is is for?

### Notify maintainers

@kdepimTeam @HolgerPeters @alyssais @vandenoever @ttuegel 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.64, NixOS, 22.05 (Quokka), 22.05.2889.67e45078141`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by LoveIsGrief** [comment]
Possibly related to #38887

**Comment by LoveIsGrief** [comment]
```
org.kde.pim.grantleetheme: Cannot load template "loading_kontact.html" , please check your installation. Tried in these dirs: ("/nix/store/64cqavy49nx3abm1nmx04f8w5pnf5rhb-messagelib-22.12.1/share/messageviewer/about")
Trying to create ksycoca...
kf.service.sycoca: Service type not found: "application/x-rar"
org.kde.pim.grantleetheme: Cannot load template "introduction_kontact.html" , please check your installation. Tried in these dirs: ("/nix/store/64cqavy49nx3abm1nmx04f8w5pnf5rhb-messagelib-22.12.1/share/messageviewer/about")
```

Looks like grantleetheme is looking in the wrong directory for resources. The files do exist in `/nix/store/fay1ljqfrazbv4an7s1kcms7fkzhi371-kontact-22.12.1/share/messageviewer/about/default`. Other package managers would just write the files to the global messageviewer path, but that doesn't work with nix.

There must be some way to make grantlee theme look in the right directory.

**Comment by Zahrun** [comment]
See https://github.com/NixOS/nixpkgs/issues/105052#issuecomment-1450354439 and https://github.com/NixOS/nixpkgs/issues/38887#issuecomment-1450355870
