### ISSUE TITLE
Packaging request: hex

### ISSUE THREAD

**Issue by Samisafool** [NixOS/nixpkgs#190768]
**Project description**
 Futuristic take on hexdump, made in Rust. 

**Metadata**

* homepage URL: https://github.com/sitkevij/hex
* source URL: https://github.com/sitkevij/hex
* license: MIT
* platforms: Windows, unix

**Comment by IvarWithoutBones** [comment]
I've opened https://github.com/NixOS/nixpkgs/pull/190813 which adds the program :)
