### ISSUE TITLE
Packaging requests: captdriver

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#190776]
**Project description**
Alternative driver for Canon CAPT printers

**Metadata**

* homepage URL: https://github.com/mounaiban/captdriver
* source URL: https://github.com/mounaiban/captdriver
* license: gpl3+
* platforms: linux

I have a LBP2900 canon printer driver and wish that it can work in NixOS. Does anyone here have any Canon printers support in that repo list and can create a package to make it work with NixOS?

**Comment by goatastronaut0212** [comment]
Closed in favor of https://github.com/NixOS/nixpkgs/pull/312291
