### ISSUE TITLE
Unable to pin version of xanmod kernel to 5.18 with override

### ISSUE THREAD

**Issue by cawilliamson** [NixOS/nixpkgs#190722]
## Issue description

Trying to override xanmod version to 5.18.x (because I need this for both ZFS and VMWare modules) but the following code did not work:

```
boot.kernelPackages = pkgs.linuxPackagesFor (pkgs.linux_xanmod_latest.override {
  argsOverride = rec {
    modDirVersion = "${version}-${suffix}";
    suffix = "xanmod1";
    version = "5.18.19";

    src = pkgs.fetchFromGitHub {
      owner = "xanmod";
      repo = "linux";
      rev = "${version}-${suffix}";
      hash = "sha256-1h5S6ox6v44CK1pSm42HHXHqR7Y0GM+JdcgNC/w5TBx=";
    };
  };
});
```

The resulting kernel is 5.19.x - am I doing something wrong or is this a genuine bug?

NOTE: The checksum is wrong - just a test value which would need to be updated once a fetch is attempted.

### Steps to reproduce

1. Add the above code to your `configuration.nix` (or included file)
2. Run `nixos-rebuild switch --upgrade`
3. See built kernel is 5.19.x

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.19, NixOS, 22.11 (Raccoon), 22.11pre407325.74a1793c659`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(chrisaw): `""`
 - channels(root): `"home-manager, nixos, nixos-small"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Emantor** [comment]
Should be fixed since https://github.com/NixOS/nixpkgs/pull/330834 went in, closing.
