### ISSUE TITLE
Update python310Packages.snowflake-connector-python to 2.7.12

### ISSUE THREAD

**Issue by padhia** [NixOS/nixpkgs#190703]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: python310Packages.snowflake-connector-python

current version: 2.7.9
desired version: 2.7.12

###### Notify maintainers

maintainers: @mweinelt 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by mweinelt** [comment]
> maintainers: @mweinelt

Uh, no. The package simply has no maintainer.

**Comment by padhia** [comment]
Sorry if I tagged you in error -- I just went by the instructions that suggested tagging the last person who made the change when there is no designated maintainer. Maybe this could be an opportunity for me to learn some light package updates. :)

Cheers!

**Comment by tjni** [comment]
This has been updated to 2.8.0 in master now, so I'm going to close this issue.

**Comment by padhia** [comment]
Thank you!
