### ISSUE TITLE
Can't query attribute set emacsPackagesNg on channel branch nixos-16.09

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nixpkgs#19084]
## Issue description

Some sort of issue in the emacsPackagesNg in the nixos-16.09 channel that breaks querying (okay in prior nixos channel releases and nixpkgs-unstable too).
### Steps to reproduce

``` bash
nix-env --show-trace --query --available --attr-path --attr nixpkgs.emacsPackagesNg
```

```
error: while evaluating ‘override’ at /nix/store/q50r17ccfm9ip0dy7ncbfznl79w7bxyi-nixpkgs/nixpkgs/lib/customisation.nix:60:22, called from /nix/store/q50r17ccfm9ip0dy7ncbfznl79w7bxyi-nixpkgs/nixpkgs/pkgs/applications/editors/emacs-modes/melpa-stable-packages.nix:38:16:
while evaluating ‘makeOverridable’ at /nix/store/q50r17ccfm9ip0dy7ncbfznl79w7bxyi-nixpkgs/nixpkgs/lib/customisation.nix:54:24, called from /nix/store/q50r17ccfm9ip0dy7ncbfznl79w7bxyi-nixpkgs/nixpkgs/lib/customisation.nix:60:31:
anonymous function at /nix/store/q50r17ccfm9ip0dy7ncbfznl79w7bxyi-nixpkgs/nixpkgs/pkgs/applications/editors/emacs-modes/melpa-stable-generated.nix:485:27 called with unexpected argument ‘company’, at /nix/store/q50r17ccfm9ip0dy7ncbfznl79w7bxyi-nixpkgs/nixpkgs/lib/customisation.nix:56:12
```

compare this to nxpkgs-unstable channel

``` bash
nix-env --show-trace --query --available --attr-path --attr nixpkgs-unstable.emacsPackagesNg
```

```
nixpkgs-unstable.emacsPackagesNg.emacs                            emacs-25.1
nixpkgs-unstable.emacsPackagesNg.aa-edit-mode                     emacs-aa-edit-mode-20160227.2217
nixpkgs-unstable.emacsPackagesNg.abc-mode                         emacs-abc-mode-20140225.944
...
```
## Technical details
- System: CentOS release 6.7 (Final) (also in my friend's NixOS 16.09beta480)
- Nix version: nix-env (Nix) 1.10
- Nixpkgs version: 16.09pre91019.8d0901c

**Comment by oxij** [comment]
I think /cc @ttuegel as I have no competency in that piece of code.

(FYI, in general, its a good idea to use `git blame` on related files to
mention people in issues as mention bot doesn't process them since there
are no code changes. I found this issue by pure chance since I filter
everything about "emacs" into my inbox and read it from time to time.)

**Comment by twhitehead** [comment]
From that commit message, sounds like this should be closed now... :grinning:
