### ISSUE TITLE
packaging request: signal-desktop for aarch64-linux

### ISSUE THREAD

**Issue by tomfitzhenry** [NixOS/nixpkgs#190896]
**Project description**

https://github.com/signalapp/Signal-Desktop

nixpkgs has this packaged, but as a x86_64 binary only: https://github.com/NixOS/nixpkgs/blob/276b680c8f9b5e36e2f489c4e746273f7e7f8fb5/pkgs/applications/networking/instant-messengers/signal-desktop/default.nix

Signal doesn't publish aarch64 binaries, so we'd have to compile these ourselves.

Arch Linux has a package for building Signal x86_64 from source, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=signal-desktop-beta , with reports that only a small patch is needed to make it build on aarch64: https://aur.archlinux.org/packages/signal-desktop-beta#comment-880073.

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/272432
