### ISSUE TITLE
Tangram is packaged without SSL/TLS support

### ISSUE THREAD

**Issue by Lillecarl** [NixOS/nixpkgs#190890]
### Describe the bug
Tangram doesn't support SSL/TLS. "Please install glib-networking"

### Steps To Reproduce
1. Install Tangram
2. Browse any TLS site

### Expected behavior
Site opens

### Screenshots
![image](https://user-images.githubusercontent.com/207073/189597975-9779931d-0ae2-49df-a163-9131abc2cff7.png)

### Additional context
This bug is so crucial to the usage of the package that it proves nobody is using it(Who browses the web w/o TLS today?). Is this a perfect example for https://discourse.nixos.org/t/should-we-consider-a-deprecation-removal-policy-for-nixpkgs/17516 ?

### Notify maintainers
@austinbutler 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.63, NixOS, 22.11 (Raccoon), 22.11.20220901.2da64a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by austinbutler** [comment]
For context, SSL was working previously. However it's true I don't end up using this much as it was never very stable due to underlying Epiphany issues. See https://github.com/NixOS/nixpkgs/issues/32580 for one. I was hoping to revisit Tangram if/when Epiphany is more stable.
