### ISSUE TITLE
Package Request: Komorebi

### ISSUE THREAD

**Issue by kreatoo** [NixOS/nixpkgs#190814]
**Project description**
(From https://github.com/cheesecakeufo/komorebi/#what-is-komorebi)
Komorebi is an awesome animated wallpapers manager for all Linux platforms. It provides fully customizeable image, video, and web page wallpapers that can be tweaked at any time!

**Metadata**
* homepage URL: https://github.com/cheesecakeufo/komorebi/
* source URL: https://github.com/cheesecakeufo/komorebi
* license: GPLv3
* platforms: Linux

**Comment by tengkuizdihar** [comment]
already done with https://github.com/NixOS/nixpkgs/pull/243347
