### ISSUE TITLE
Chibi Scheme does not start on Mac OS due to missing (probably misplaced) dylib

### ISSUE THREAD

**Issue by dpk** [NixOS/nixpkgs#190889]
### Describe the bug

When the package `chibi` is installed on Mac OS, running the main `chibi-scheme` program fails because the dynamic library containing most of the Scheme implementation is expected to be in the global `/usr/lib` or `/usr/local/lib` directories, but isn’t.

The specific error is:

```
> chibi-scheme -R
dyld[67877]: Library not loaded: '/usr/local/lib/libchibi-scheme.0.10.0.dylib'
  Referenced from: '/nix/store/gn5fj0bz79p8kimk1kccs8in2kzcap2h-chibi-scheme-0.10/bin/.chibi-scheme-wrapped'
  Reason: tried: '/usr/local/lib/libchibi-scheme.0.10.0.dylib' (no such file), '/usr/lib/libchibi-scheme.0.10.0.dylib' (no such file)
fish: Job 1, 'chibi-scheme -R' terminated by signal SIGABRT (Abort)
```

### Steps To Reproduce

I installed Chibi with `nix-env -iA nixpkgs.chibi` on Mac OS 12.5 and ran `chibi-scheme` at the command line. The version of Chibi it installed was 0.10.

### Expected behavior

`chibi-scheme` should just work when installed.

### Notify maintainers

@DerGuteMoritz 

### Metadata

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by wegank** [comment]
Please format the commit as shown in this [link](https://ryantm.github.io/nixpkgs/contributing/submitting-changes/). Thanks!
