### ISSUE TITLE
Update OpenOCD

### ISSUE THREAD

**Issue by Wulfsta** [NixOS/nixpkgs#190866]
v0.11.0 of OpenOCD is over a year old, does anyone have time to update or add an unstable branch? 

@bjornfor @prusnak

**Comment by bjornfor** [comment]
v0.11.0 seems to be the latest release (https://github.com/openocd-org/openocd/releases). I suggest asking upstream for a new release.

**Comment by prusnak** [comment]
@Wulfsta We don't update to unstable unless there is a good reason to do so. Do you have any?

**Comment by Wulfsta** [comment]
Yes - there is no sign of a 0.12.0 release that I can see, and the software has been actively developed since the 0.11.0 release. There is currently [a pull request](https://github.com/NixOS/nixpkgs/pull/189014) open to update ElmerFEM for similar purposes. I’m not convinced that it should be on users or maintainers to ask upstream for a release number in cases like this.

**Comment by prusnak** [comment]
> update ElmerFEM for similar purposes

That's a different case, since the person opening the PR indicated there is something they need from the unreleased version of the software. So let me repeat and rephrase my question: Do you have any reason why you want us to update OpenOCD to unstable? Any bug fixes, any features you are missing from the latest stable release?

**Comment by Wulfsta** [comment]
Now that v0.12.0 is out, would you take action to update this? I want to see if any of the changes related to `bcm2835` allow me to flash an atsamc21g18 that drives it’s SWD pins from a rpi.

**Comment by bjornfor** [comment]
@Wulfsta: Can you test https://github.com/NixOS/nixpkgs/pull/216607?
