### ISSUE TITLE
runInLinuxVM documentation

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#190809]
The `vmTools.runInLinuxVM` is a very useful function, however it is not mentioned in the manuals. I think a (nixpkgs, I guess) manual entry should be added for it.
The text in the comment above its definition seems like a good, sufficient description for what `runInLinuxVM` does, just that there is no html-rendered version of it, and it is not discoverable for people looking in the manuals.

**Comment by 9glenda** [comment]
A usage example can be found here https://github.com/NixOS/nixpkgs/blob/350fd0044447ae8712392c6b212a18bdf2433e71/pkgs/build-support/singularity-tools/default.nix#L50

**Comment by Janik-Haag** [comment]
This was closed by #197247
