### ISSUE TITLE
first output from multiple outputs isn't assigned to $out

### ISSUE THREAD

**Issue by redbaron** [NixOS/nixpkgs#190907]
general builder relies on $out being set, but if derivation declares multiple outputs and none of them has name "out", then sensible behavior is to set $out to name of first one.

```
{ stdenv  }:

stdenv.mkDerivation rec {
  name = "test_out";
  outputs = [ "one" "two" ];
  preHook = "echo '>>>>>>>>>>>' $out";
}
```

PS.we should also add "set -ue" at the top of generic builder to catch such errors, but that probably will break many packages ATM

**Comment by samueldr** [comment]
I think it's fair to close this as "won't fix".

 - Multiple outputs are not a surprise (anymore).
 - implicitly aliasing the first output as `$out` isn't desirable AFAIK.

I don't see anything actionable here. If I'm wrong, feel free to open, and/or comment with what can be done here.
