### ISSUE TITLE
fcitx5-unikey out of date package 

### ISSUE THREAD

**Issue by zenfas** [NixOS/nixpkgs#190912]
Current version on NIX: 5.0.9
New source version: 5.0.11

**Comment by bobby285271** [comment]
We have fcitx5-unikey 5.0.11 in nixos unstable: https://github.com/NixOS/nixpkgs/pull/180244, if you are using 22.05 and have a good reason that this should be backport please feel free to cherry-pick the relevant commits and PR against release-22.05, thanks!
