### ISSUE TITLE
ibus-bamboo out of date package

### ISSUE THREAD

**Issue by zenfas** [NixOS/nixpkgs#190910]
Current version on NIXOS 0.7.7
New version from source  0.8.1-RC4

**Comment by SuperBo** [comment]
hi @katexochen, will work on this on weekend

**Comment by katexochen** [comment]
Thanks. :) But no pressure, I was just scrolling though older open issues.

**Comment by SuperBo** [comment]
https://github.com/NixOS/nixpkgs/pull/271978
