### ISSUE TITLE
Package wxGTK32

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#190946]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 3.1.5
desired version: 3.2.1

Tried packaging wxPython 4.2.0 and it seems to require wxGTk 3.2, because it is missing some header files.

###### Notify maintainers

maintainers: @tfmoraes 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by tfmoraes** [comment]
@mweinelt created a [PR](https://github.com/NixOS/nixpkgs/pull/191729) to add wxgtk32
