### ISSUE TITLE
nginx with enableACME+forceSSL don't work when basicAuth is set

### ISSUE THREAD

**Issue by LeuX** [NixOS/nixpkgs#19105]
## Issue description
as discussed with @fpletz:

```nix
services.nginx.virtualHosts = {
        "<hostname>" = {
            forceSSL = true;
            enableACME = true;
            basicAuth = {
                user = "<password>";
            };
        };
    };
```

don't work. I assume this is because of lets-encrypt being unable to verify the challenge because the basicAuth is being set before the domain validation is complete.

## Technical details
* System: NixOS: 16.09beta264.aadcffc (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09beta264.aadcffc"

**Comment by fpletz** [comment]
@LeuX Hmm, I've built a small testcase to reproduce this, but it worked for me.

 After looking through the code I found that we in fact disable basic auth, so this should work: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/nginx/default.nix#L124

Let's invest some more next week at the office.
