### ISSUE TITLE
gawk-with-extensions fails on unstable due to haru plugin

### ISSUE THREAD

**Issue by barryfm** [NixOS/nixpkgs#191072]
### Steps To Reproduce
1. nix-build  '<nixpkgs>' -A gawk-with-extensions 

### Build log
[gist of log](https://gist.github.com/barryfm/bb5b66b266d3f550de29c34a9d7bf362)

### Additional context
Still fails when I used `libharu-2.4.2`

My current workaround is removing haru from gawkextlib with:
```
packageOverrides = pkgs: {
      gawk-with-extensions = pkgs.gawk-with-extensions.override {
        extensions = with pkgs.gawkextlib;
          lib.subtractLists [ haru ] full;
      };
};
```

### Notify maintainers

@tomberek

### Metadata
```
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.64, NixOS, 22.11 (Raccoon), 22.11pre407906.c97e777ff06`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(barry): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tomberek** [comment]
Related: 
- https://github.com/libharu/libharu/commit/88271b73c68c521a49a15e3555ef00395aa40810
- and not yet updated in gawkextlib: https://sourceforge.net/p/gawkextlib/code/ci/master/tree/haru/pdf.h
