### ISSUE TITLE
uwimap packages for darwin

### ISSUE THREAD

**Issue by ebauger** [NixOS/nixpkgs#191099]
**Project description**
Build of [uwimap](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/tools/networking/uwimap/default.nix) for

- x86_64-darwin

- aarch64-darwin

**Why** 

Can have impact about PHP80Extensions.imap or others languages dependancies.

**Notify maintainers**

@globin 
@dezgeg 
@lovek323 
@Phreedom 
@OmnipotentEntity 
@mmahut 
@alyssais 
@lheckemann 
@Synthetica9 
@Fuuzetsu 
@fpletz 
@edolstra

**Comment by wegank** [comment]
Closed by #194109.
