### ISSUE TITLE
Cannot start synology-drive-client anymore

### ISSUE THREAD

**Issue by JalilArfaoui** [NixOS/nixpkgs#191125]
### Describe the bug

Since reboot after update, does nothing from application menu

From shell I get 

```shell
QApplication: invalid style override passed, ignoring it.                                                                                                                                         
    Available styles: Windows, Fusion
```

In journalctl I can see more info, only for the first attempt 👍🏾 

```shell
systemd[2437]: app-gnome-synology\x2ddrive-3418.scope: Couldn't move process 3418 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-synology\x2ddrive-3418.scope':>
sept. 14 00:12:04 gandalf systemd[2437]: app-gnome-synology\x2ddrive-3418.scope: Failed to add PIDs to scope's control group: No such process
sept. 14 00:12:04 gandalf systemd[2437]: app-gnome-synology\x2ddrive-3418.scope: Failed with result 'resources'.
sept. 14 00:12:04 gandalf systemd[2437]: Failed to start Application launched by gnome-shell.
sept. 14 00:12:04 gandalf synology-drive.desktop[3420]: QApplication: invalid style override passed, ignoring it.
sept. 14 00:12:04 gandalf synology-drive.desktop[3420]:     Available styles: Windows, Fusion
```

### Steps To Reproduce
Steps to reproduce the behavior: Start synology-drive-client

### Expected behavior
I should see the UI  and/or the notification icon

### Additional context

- I tried update from 22.05 and from unstable
- I tried from Flatpak

### Notify maintainers

@jcouyang 
@MoritzBoehme 

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                         mer. 14 sept. 2022 00:21:17
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/51zlypw5hnf1b9lg56vlgfwla5zq1s9w-bash-interactive-5.1-p16-dev
copying path '/nix/store/51zlypw5hnf1b9lg56vlgfwla5zq1s9w-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka), 22.05.3050.d86a4619b7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-unstable, release-22.05.tar.gz-22.05.tar.gz"`
 - channels(jalil): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by MoritzBoehme** [comment]
Okay, I don't seem to have these issues, but I will try to look into it.

**Comment by JalilArfaoui** [comment]
Thanks …

I do have the same issue with the FlatPak version, so I suspect another component changed in 22.05 channel … 

And I forgot to mention that logs is ~/.SynologyDrive have not been updated since I have the issue, so it looks like a very early crash …

**Comment by MoritzBoehme** [comment]
I tried installing different versions of the package (from stable, unstable), but everything seems to work fine for me...
My system info: ```
❯ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.6, NixOS, 22.11 (Raccoon), 22.11.20220902.21de2b9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-21.11pre324423.34ad3ffe08a, nixpkgs-21.11pre325327.30f73c6493b"`
 - channels(moritz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
 I'll try using 22.05 as my systems nixpkgs flake input to see if this breaks my synology drive :pray:

**Comment by MoritzBoehme** [comment]
Okay, I just turned on my PC and noticed it does not work for me anymore either :(

**Comment by JalilArfaoui** [comment]
Oh thanks @MoritzBoehme ! That did the trick !
