### ISSUE TITLE
Install with Gnome desktop fails due binary cache miss for Python3-3.6.4

### ISSUE THREAD

**Issue by bryaan** [NixOS/nixpkgs#191127]
Using 17 and latest 18.03 with Gnome enabled at some point in install it fails. (Text install works just fine)

I'm getting an error "Could not download from any binary cache" for `python3-3.6.4`.

But I'm not convinced that is the problem because right after it exits, I try running `nix-env -i python3` and I get "No space left on device"!!!

How is that even possible with a disk of 60GB like I set???
Or is that bc I'm trying to install to the readonly install image?

Additional Questions:
1. Is there any way to scroll up in shell after fail, or a log file of STDOUT during install?
1. Is there a retry setting I should increase or mirrors to use? 
1. Is there an easy way to setup local caching? Its a shame to download these files again and again.

**Comment by SuperSandro2000** [comment]
> No space left on device

Your disk is full. 60 GB is not that much for a full NixOS installation.
