### ISSUE TITLE
How to manually replicate/reproduce/obtain the sha256 hash specified in Nix with fetchgit or fetchFromGitHub?

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#191128]
At https://nixos.org/nixpkgs/manual/ we see this example:

    src = fetchgit {
      url = "git://github.com/NixOS/nix.git";
      rev = "1f795f9f44607cc5bec70d1300150bfefcef2aae";
      sha256 = "1cw5fszffl5pkpa6s6wjnkiv6lm5k618s32sp60kvmvpy7a2v9kg";
    }
    
    src = fetchgit {
      url = "https://github.com/NixOS/nix.git";
      rev = "1f795f9f44607cc5bec70d1300150bfefcef2aae";
      sha256 = "1cw5fszffl5pkpa6s6wjnkiv6lm5k618s32sp60kvmvpy7a2v9kg";
    }
    
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nix";
      rev = "1f795f9f44607cc5bec70d1300150bfefcef2aae";
      sha256 = "04yri911rj9j19qqqn6m82266fl05pz98inasni0vxr1cf1gdgv9";
    }

How do I obtain these hashes myself? I tried the commands

    $ nix-prefetch-url https://github.com/NixOS/nix/archive/1f795f9f44607cc5bec70d1300150bfefcef2aae.tar.gz
    downloading ‘https://github.com/NixOS/nix/archive/1f795f9f44607cc5bec70d1300150bfefcef2aae.tar.gz’... [13/589 KiB, 3.3 KiB/s]
    path is ‘/nix/store/4hrp5jv1rv51lcwf097hbcjjksnwpwi6-1f795f9f44607cc5bec70d1300150bfefcef2aae.tar.gz’
    1311maadkx2xq2ll9apfsyjq5gy5q874z4db7l2riz7vqpx1bxhs
    
    $ nix-prefetch-url https://github.com/NixOS/nix/archive/1f795f9f44607cc5bec70d1300150bfefcef2aae.zip
    downloading ‘https://github.com/NixOS/nix/archive/1f795f9f44607cc5bec70d1300150bfefcef2aae.zip’... [306/835 KiB, 146.0 KiB/s]
    path is ‘/nix/store/gy1zkg71mrlpf5lh8ypl1kg8d2ps6m05-1f795f9f44607cc5bec70d1300150bfefcef2aae.zip’
    1b3vnxfpidwpmgh9dlpmhvrrkkgn3a0r56bv175y6hzfhnx4s5kn

but as you can see, both hashes are completely different from any of the above two.

So how do I actually replicate/reproduce/obtain the sha256 hash specified in Nix with fetchgit or fetchFromGitHub?

**Comment by kaiba42** [comment]
Here's an example to get that sha256. You can verify this example against [the current pkg for the GitHub CLI](https://github.com/NixOS/nixpkgs/blob/cd749f58ba83f7155b7062dd49d08e5e47e44d50/pkgs/applications/version-management/git-and-tools/gh/default.nix#L11).
nix-shell -p nix-prefetch-git jq --run "nix hash to-sri sha256:\$(nix-prefetch-git --url https://github.com/cli/cli --quiet --rev v2.20.2 | jq -r '.sha256')"

**Comment by SuperSandro2000** [comment]
I think this is a question and there is nothing actionable except documentation left.

**Comment by cameronraysmith** [comment]
> Here's an example to get that sha256. You can verify this example against [the current pkg for the GitHub CLI](https://github.com/NixOS/nixpkgs/blob/cd749f58ba83f7155b7062dd49d08e5e47e44d50/pkgs/applications/version-management/git-and-tools/gh/default.nix#L11).
> 
> ```shell
> nix-shell -p nix-prefetch-git jq --run "nix hash to-sri sha256:\$(nix-prefetch-git --url https://github.com/cli/cli --quiet --rev v2.20.2 | jq -r '.sha256')"
> ```

This may now be

```shell
nix-shell -p nix-prefetch-git jq --run "nix hash convert --to sri sha256:\$(nix-prefetch-git --url https://github.com/cli/cli --quiet --rev v2.49.2 | jq -r '.sha256')"          
sha256-RevdHBF/7etEstUhsTO9KVK45KTiJnhAhAZAamuEUwk=
```

**Comment by HannesGitH** [comment]
> > Here's an example to get that sha256. You can verify this example against [the current pkg for the GitHub CLI](https://github.com/NixOS/nixpkgs/blob/cd749f58ba83f7155b7062dd49d08e5e47e44d50/pkgs/applications/version-management/git-and-tools/gh/default.nix#L11).
> > ```shell
> > nix-shell -p nix-prefetch-git jq --run "nix hash to-sri sha256:\$(nix-prefetch-git --url https://github.com/cli/cli --quiet --rev v2.20.2 | jq -r '.sha256')"
> > ```
> 
> This may now be
> 
> ```shell
> nix-shell -p nix-prefetch-git jq --run "nix hash convert --to sri sha256:\$(nix-prefetch-git --url https://github.com/cli/cli --quiet --rev v2.49.2 | jq -r '.sha256')"          
> sha256-RevdHBF/7etEstUhsTO9KVK45KTiJnhAhAZAamuEUwk=
> ```

now it is only `nix hash to-sri` even

**Comment by rawkode** [comment]
This is now:

```shell
nix-shell -p nix-prefetch-git jq --run "nix hash convert sha256:\$(nix-prefetch-git --url https://github.com/cli/cli --quiet --rev v2.49.2 | jq -r '.sha256')"
```
