### ISSUE TITLE
NixOS user passwords lost when rebooting

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#191190]
### Describe the bug

When i reboot, all passwords are lost.

### Steps To Reproduce
1. Set root password with `passwd`
2. Check `/etc/shadow` that root has a password
3. Reboot
4. Check `/etc/shadow` that root has no password

### Expected behavior
NixOS should not loose passwords or any other data.

### Additional context
The password is then set to `!` which means the account is locked. I can't log in locally on the system.

When i also can't log in via SSH because the network is messed up, **i'm completely locked out**!

Similar issue: https://github.com/NixOS/nixpkgs/issues/4955

This seem to be expected behavior when `mutableUsers = false` is set, but i don't think i have that set.

My config.: https://codeberg.org/davidak/nixos-config/src/commit/b7eaf83737320ec2d1586eb4e7c85a7730e7d52c/machines/atomic/configuration.nix

I don't have this issue on any other system. Only this VM in Hetzner Cloud.

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka), 22.05.3050.d86a4619b7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Minion3665** [comment]
> This seem to be expected behavior when `mutableUsers = false` is set, but i don't think i have that set.

https://codeberg.org/davidak/nixos-config/src/commit/b7eaf83737320ec2d1586eb4e7c85a7730e7d52c/machines/atomic/configuration.nix#L122

**Comment by davidak** [comment]
@Minion3665 well spotted. Thanks a lot!

Sorry for taking up your time for this.
