### ISSUE TITLE
request: add llvmPackages_15

### ISSUE THREAD

**Issue by nektro** [NixOS/nixpkgs#191132]
**Project description**
The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.

**Metadata**

* homepage URL: https://llvm.org/
* source URL: https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.0
* license: Apache License v2.0 with LLVM Exceptions
* platforms: x86_64-darwin, aarch64-darwin, aarch64-linux, i686-linux, x86_64-linux
* notes: previously added as llvmPackages_14

**Comment by nektro** [comment]
cc maintainers @lovek323 @7c6f434c @dtzWill @primeos

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.1

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.2

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.3

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.5

**Comment by rrbutani** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.6

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.7
