### ISSUE TITLE
ddclient preventing systemd Bootup finish

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#191105]
### Describe the bug
Using ddclient prevents systemd from finishing boot.

Checking blame shows boot unfinished.

```
# systemd-analyze blame
Bootup is not yet finished (org.freedesktop.systemd1.Manager.FinishTimestampMonotonic=0).
Please try again later.
Hint: Use 'systemctl list-jobs' to see active jobs

# systemctl list-jobs
JOB UNIT              TYPE  STATE
2   multi-user.target start waiting
88  ddclient.service  start running
1   graphical.target  start waiting

3 jobs listed.
```

### Steps To Reproduce
My ddclient config. When I change ddclient.enable to false, then systemd boot completes.
```
  services.ddclient.enable = true;
  services.ddclient.interval = "60min";
  services.ddclient.extraConfig =
  ''
    daemon=1800
    use=web, web=checkip.dynu.com/, web-skip='IP Address'
    protocol=dyndns2
    server=api.dynu.com
    login=xxxx
    password='"xxxx'
    xxxx.dynu.com
  '';
```

If any further information is needed, then please request.

**Comment by SuperSandro2000** [comment]
> Using ddclient prevents systemd from finishing boot.

It most likely only delays the boot and does not prevent it.

**Comment by Sepero** [comment]
It occurred to me that I was instructing ddclient to run as a daemon, but the systemd service already has an instruction to rerun the command on timer. So I removed the daemon line, and the issue went away. Now it is no longer hanging the boot sequence. May I suggest to make a note in the documentation for others, don't run ddclient as a daemon. Thank you

    # daemon=1800
