### ISSUE TITLE
Emby has runtime dependancy on FFmpeg

### ISSUE THREAD

**Issue by andjscott** [NixOS/nixpkgs#19118]
## Issue description
Emby uses ffmpeg for transcoding media and for generating thumbnails. Emby fails to find the FFmpeg binary during the setup wizard but `/run/current-system/sw/bin/ffmpeg` can be specified manually if FFmpeg has been installed separately.
 
### Steps to reproduce
Add `emby.enable = true` to `/etc/nixos/configuration.nix`, browse to `localhost:8096`, and advance through the wizard.

## Technical details

* System: 17.03pre92039.adfcc2d (Gorilla)
* Nix version:nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre92039.adfcc2d

**Comment by joachifm** [comment]
cc @fadenb

**Comment by fadenb** [comment]
Funny thing is that I was just watching a movie when I was mentioned on a system without any ffmpeg/ffprobe binary. My system was upgraded from an older version (config was already existing so no check was done by the wizard).

I was able to reproduce the issue. Will take a more detailed look at it sometime tomorrow :)
