### ISSUE TITLE
Improve guidelines for commit messages

### ISSUE THREAD

**Issue by bachp** [NixOS/nixpkgs#19126]
## Issue description

Nixpkgs already has some guidelines how to write commit messages in CONTRIBUTING.md.
It describes how to structure the message.

Most commits follow this guideline which is very good.
However one Problem is that many people do really good changes in their commit but for somebody not directly involved it is really hard to understand why.

In my opinion it's very important to have this "why" in the commit message, especially if the project has many collaborators of various degree of involvement. One project I found to do this very well is [OpenEmbedded](https://github.com/openembedded/openembedded-core/commit/9e9875fc19df6b924aa7f9d06e7b4e07222d0799).

I propose to add a section to CONTRIBUTING.md that encourages to explain a bit more why the changes were made. Maintainers should then encourage people to follow this guidelines when reviewing PRs.

**Comment by ericsagnes** [comment]
Do you have any special kind of commits in mind?
I am asking because package updates and new package commits seems pretty much self-explanatory. (one improvement I can see in this regard is to put release notes for package updates commits)

Also, the why, while not in mandatory in the commit message, should figure in the pull-request `motivation for this change`.

**Comment by bachp** [comment]
I recently stumbled upon this commit for example: 3b89a6e0209fb75e36473905dd8bbae1e30d2ac5
While the commit message clearly states what is done, I have no Idea why it was done.

Having the motivation in the pull request is good but doing self contained commits with all the information for somebody to understand the changes and the reasons behind is even better.

**Comment by groxxda** [comment]
I second that the motivation should be in the commit message and not only the pr, so one can read it without searching for the pr on github first..
