### ISSUE TITLE
Package Request: Picom-jonaburg

### ISSUE THREAD

**Issue by MatusModder** [NixOS/nixpkgs#191211]
**Project description**
from the project README - "This is a forked version from Sandmark's picom branch, including Blackcapcoder's animation code inside. The animations here are further smoothed and time deltas reduced from 1ms to 40us for high refresh rates and buttery smooth transitions."

**Metadata**

* homepage URL: https://github.com/jonaburg/picom
* source URL: https://github.com/jonaburg/picom
* license: MPL 2 and MIT
* platforms: linux (and maybe unix)

**Comment by ocfox** [comment]
Finished at #192343
