### ISSUE TITLE
Lapce fails to start on Wayland and complains about openGL

### ISSUE THREAD

**Issue by MadMcCrow** [NixOS/nixpkgs#191232]
### Describe the bug
Lapce fails to launch complaining about libGL or libEGL. used under gnome wayland.

### Steps To Reproduce
1. Use Gnome with wayland in your nix configuration
2. Launch Lapce, either with command line or directly with the gnome launcher
3. notice it fails to start.

### Expected behavior
Adding the lapce package should also include all dependancy to run on any Nix desktop.

### Screenshots
Output of command line when lauching lapce from gnoe-terminal
```console
[perard@NixAF:~]$ lapce
thread 'main' panicked at 'launch failed: Other(window build error: Received multiple errors. Errors: `[NotSupported("lacking either libGL or libEGL so could not fallback to other"), NotSupported("both libGL and libEGL are not present")]` srgb false)', lapce-ui/src/app.rs:54:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Additional context
[here](https://github.com/MadMcCrow/nixos-configuration) is my full configuration for context.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[perard@NixAF:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.14-zen1, NixOS, 22.05 (Quokka), 22.05.3050.d86a4619b7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by catlion** [comment]
Built from source on Fedora 37, it just does not start silently.

**Comment by eclairevoyant** [comment]
Closing, as both NixOS and non-NixOS users seem to be able to use this normally.
