### ISSUE TITLE
pcsx2 doesn't start from shortcut in GNOME system

### ISSUE THREAD

**Issue by apolon210788** [NixOS/nixpkgs#191337]
Doesn't start from shortcut in GNOME system. Runs in the terminal. The shortcut does not work.

**Comment by apolon210788** [comment]
Doesn't start from shortcut in GNOME system. Runs in the terminal. The shortcut does not work.

**Comment by SuperSamus** [comment]
This seems to be caused by the fact that the desktop file sets `GDK_BACKEND=x11`. https://github.com/PCSX2/pcsx2/commit/8958b2042fc1877617dcdcc335b8a0f082e2ca89
```
Error: Unable to initialize GTK+, is DISPLAY set properly?
```
The problem also occurs on Plasma Wayland, so I guess it happens on Wayland in general. (Didn't test X11 window managers.)
