### ISSUE TITLE
Doesn't start from shortcut in GNOME system. Runs in the terminal. The shortcut does not work.

### ISSUE THREAD

**Issue by apolon210788** [NixOS/nixpkgs#191335]
### Steps To Reproduce
1. ...
2. ...
3. ...

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by apolon210788** [comment]
Doesn't start from shortcut in GNOME system. Runs in the terminal. The shortcut does not work.

**Comment by buckley310** [comment]
Looks like this report didn't get finished?
Is this issue a duplicate of one of the other similar ones from around this time?

**Comment by jtojnar** [comment]
Closing as there is not enough info for us to act upon.
