### ISSUE TITLE
Zsh wrong behaviour of some keys

### ISSUE THREAD

**Issue by alexpetrean80** [NixOS/nixpkgs#191389]
### Describe the bug
Pressing keys like "HOME", "END" produce no character and pressing "DELETE", "PGUP", "PGDOWN" produce a "~" in the zsh terminal

### Steps To Reproduce
1. run zsh in gnome terminal or konsole in any way(nix-shell, system package or user package)
2. try running the aforementioned keys
3. validate that the keys work as expected in kate/gnome editor, as well as in bash/fish

### Expected behavior
The keys working as expected

### Additional context
Noticed this bug while trying to delete a string using the "DELETE" button. thought that the key didn't work, tried other keys to see which work and which not, check that they work in gnome editor. changed gnome for kde, tried it in konsole, same issue
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka), 22.05.3050.d86a4619b7e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(padfoot): `"home-manager-22.05.tar.gz"`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
output here
```

**Comment by ShrykeWindgrace** [comment]
I'd venture a guess that the problem lies in setting correct `$TERM` and providing proper bindings via something like
```
bindkey '^[[4~'   end-of-line
```
in your `.zshrc`...
