### ISSUE TITLE
 Package Request: SurrealDB

### ISSUE THREAD

**Issue by jhackenberg** [NixOS/nixpkgs#191385]
**Project description**
SurrealDB is an end-to-end cloud native database for web, mobile, serverless, jamstack, backend, and traditional applications. SurrealDB reduces the development time of modern applications by simplifying your database and API stack, removing the need for most server-side components, allowing you to build secure, performant apps quicker and cheaper. SurrealDB acts as both a database and a modern, realtime, collaborative API backend layer. SurrealDB can run as a single server or in a highly-available, highly-scalable distributed mode - with support for SQL querying from client devices, GraphQL, ACID transactions, WebSocket connections, structured and unstructured data, graph querying, full-text indexing, geospatial querying, and row-by-row permissions-based access.

**Metadata**

* homepage URL: https://surrealdb.com
* source URL: https://github.com/surrealdb/surrealdb
* license: Business Source License 1.1
* platforms: unix, linux, darwin

**Comment by sikmir** [comment]
#187990
