### ISSUE TITLE
ibus does not work with any toolkit

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#19134]
## Description

ibus does not work with GTK 2, GTK 3, or Qt 5.

## Reproduce

I have the following in `configuration.nix`:
```
  i18n.inputMethod = {
    enabled = "ibus";
    ibus.engines = with pkgs.ibus-engines; [ table table-others ];
  };
```
The ibus icon appears in my system tray and I can use the keyboard shortcut to select input methods, but they do not have any effect in any application.

## Details

* System: NixOS 16.09.git.6c34d85 (Flounder)
* Nix version: nix-env (Nix) 1.12pre4523_3b81b26

## Related 
#17277 #11558

Attn. @ericsagnes

**Comment by ericsagnes** [comment]
I tested the ibus 1.5.14 with i3 today with a few engines and it was working fine.

There is an issue with ibus and gnome 3 (#17277), but I am not familiar enough with gnome be helpful on that one (as far as I can tell, gnome 3 putting a vanilla ibus in environment sounds wrong).

What was the desktop environment(s) this problem happened? Also what version of ibus is affected, 1.5.13 or 1.5.14 only?

**Comment by ttuegel** [comment]
This is ibus 1.5.13 under KDE 5. The desktop environment shouldn't make a difference, though, if all the environment variables are set correctly. In my case, they seem to be:
```
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS='@im=ibus'
```
Is there something missing?

**Comment by abbradar** [comment]
FWIW I have it working okay for both Qt, GTK2 and X11 apps on XFCE with a similar configuration (different engines).

**Comment by ttuegel** [comment]
> FWIW I have it working okay for both Qt, GTK2 and X11 apps on XFCE with a similar configuration (different engines).

@abbradar Which engines are you using? It could be the engines that are broken here.

**Comment by abbradar** [comment]
@ttuegel Just `uniemoji`. It works for me properly after I select it via a hotkey.

**Comment by ericsagnes** [comment]
@ttuegel What are the engines you are using?
Doing some tests now, will give report ASAP.

**Comment by ttuegel** [comment]
@ericsagnes Just `table` and `table-others`. Specifically, the LaTeX input method.

**Comment by ericsagnes** [comment]
##### i3

configuration.nix

```
{ config, pkgs, ... }:


{
  imports =
    [
      <nixos/modules/installer/scan/not-detected.nix>
    ];
  nix.maxJobs = 4;

  nix.useSandbox = true;

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    # gtk 2
    geany
    # gtk 3
    gnome3.gedit
    # kde 4
    kde4.kate
    # kde 5 + pyqt5
    qutebrowser
    tree
  ];

  users.extraUsers.alice = {
    createHome = true;
    home = "/home/alice";
    description = "Alice";
    extraGroups = [ "wheel" ];
    isSystemUser = false;
    useDefaultShell = true;
    password = "alice";
  };

  hardware.enableAllFirmware = true;

  sound.enable = false;
  
  # Select internationalisation properties.
  i18n = {
    consoleFont = "lat9w-16";
    consoleKeyMap = "jp106";
    defaultLocale = "en_US.UTF-8";
  };

  i18n.inputMethod = {
    enabled = "ibus";
    ibus.engines = with pkgs.ibus-engines; [ anthy hangul ];
  };

  services.xserver = {
    enable = true;
    layout = "jp";
    videoDrivers = ["intel"];

    desktopManager.default = "none";
    desktopManager.xterm.enable = false;
    displayManager.slim.enable = true;
    windowManager.default = "i3";
    windowManager.i3.enable = true;
  };

  time.timeZone = "Asia/Tokyo";

}
```

command:

```
nixos-rebuild build-vm -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/6c34d85.tar.gz -I nixos-config=/tmp/ibus.nix
```

result:

![i3](https://s13.postimg.org/ljly3p8tz/image.png)

**Comment by ttuegel** [comment]
OK, I'm trying to rebuild with anthy now.

**Comment by ericsagnes** [comment]
##### kde5

configuration.nix

same as previous, except xserver block

```
  services.xserver = {
    enable = true;
    layout = "jp";
    videoDrivers = ["intel"];

    desktopManager.default = "none";
    desktopManager.xterm.enable = false;
    displayManager.slim.enable = true;
    desktopManager.kde5.enable = true;
  };
```

command:

```
$ nixos-rebuild build-vm -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/6c34d85.tar.gz -I nixos-config=/tmp/ibus.nix
$ ./result/bin/run-nixos-vm -m 4000
```

result:

![kde5](https://s14.postimg.org/sf6gdnu3l/kde5.png)

**Comment by ttuegel** [comment]
@ericsagnes It looks like this is definitely a problem with the table-based engines, then?

**Comment by ericsagnes** [comment]
I will give a try with table and table others.
I have no experience with these ones, what should I try to input to reproduce your problem?

**Comment by ttuegel** [comment]
A simple test is, with the LaTeX input method, `\alpha \beta \gamma` should give you lowercase Greek characters.

**Comment by ericsagnes** [comment]
Figured almost the same test :)
But it seems to work fine here. (using the same settings for the previous i3, only changed the engines)

![i3-latex](https://s14.postimg.org/g4bnnnp1t/i3_latex.png)

**Comment by ericsagnes** [comment]
Does trying the configuration in vm or with a new user also fails? (just guessing that something in the environment might causing trouble)

**Comment by ttuegel** [comment]
It does work in a VM, so something is wrong in my environment. Also, I noticed that in my broken environment, trying to switch input methods doesn't actually work. (The tray icon never changes.) I also notice there are lots of `/nix/store` paths in `$HOME/.cache/ibus/bus/registry` and many errors logged in `$HOME/.cache/ibus-table/debug.log`. What do you recommend?

**Comment by ttuegel** [comment]
I just noticed that direct Unicode input works with ibus, so it's definitely a problem with the table methods.

**Comment by ttuegel** [comment]
Deleting `$HOME/.cache/ibus-table` fixed the problem, even though there didn't seem to be anything actually cached there! It was just logs... Should we update the ibus-daemon wrapper to delete that cache at startup? It doesn't hold any configuration data. Actually, it doesn't seem to hold anything at all.

**Comment by aske** [comment]
I had similar problems and everything was solved after deleting `.cache/ibus`, then I've found flag for `ibus-daemon` which seemed to deal with this problem -- it was something like `--refresh`, though you better recheck (I'm away from my nixos right now).

**Comment by ericsagnes** [comment]
The current command to start ibus already include `--cache=refresh`, could it be that an ibus-daemon process is already present so the command gets ignored?

In that case, adding `--replace` to the [autostart](https://github.com/NixOS/nixpkgs/blob/caac16a924560abcc8e56a413963caf608776c26/nixos/modules/i18n/input-method/ibus.nix#L20) command to force the restart of the daemon might help.

**Comment by abbradar** [comment]
I think it's better to add `--cache=refresh` to a wrapper around `ibus-daemon`. Some environments don't even call things from XDG autostart and prefer running ibus-daemon directly (desktop manager-less custom sessions). This way we would consistently clean cache in any possible usecase.
