### ISSUE TITLE
aspell-dict-en-2016.06.26-0 fails on osx

### ISSUE THREAD

**Issue by mbucc** [NixOS/nixpkgs#19147]
## Issue description

```nixpkg -i aspell-dict-en-2016.06.26-0``` crashes with the error

```
installing ‘aspell-dict-en-2016.06.26-0’
these derivations will be built:
  /nix/store/3a6fbddilmb77zkgrs60w1cnpqbwhsni-aspell-dict-en-2016.06.26-0.drv
building path(s) ‘/nix/store/z08ghia6fcn5zsx5mr7h2f7m7jnvagy0-aspell-dict-en-2016.06.26-0’
unpacking sources
unpacking source archive /nix/store/vfds8i804ji39j75sw3gdvd18j6jdjri-aspell6-en-2016.06.26-0.tar.bz2
dyld: lazy symbol binding failed: Symbol not found: _mkdirat
  Referenced from: /nix/store/ld37dbm6jm59a6q9n0c04cz0p0jhccdl-gnutar-1.29/bin/tar
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkdirat
  Referenced from: /nix/store/ld37dbm6jm59a6q9n0c04cz0p0jhccdl-gnutar-1.29/bin/tar
  Expected in: /usr/lib/libSystem.B.dylib

/nix/store/lfql80l8m1l1y69n7zr4zfwwaqh5xld4-stdenv-darwin/setup: line 532: 16481 Trace/BPT trap: 5       tar xf "$fn"
do not know how to unpack source archive /nix/store/vfds8i804ji39j75sw3gdvd18j6jdjri-aspell6-en-2016.06.26-0.tar.bz2
builder for ‘/nix/store/3a6fbddilmb77zkgrs60w1cnpqbwhsni-aspell-dict-en-2016.06.26-0.drv’ failed with exit code 1
error: build of ‘/nix/store/3a6fbddilmb77zkgrs60w1cnpqbwhsni-aspell-dict-en-2016.06.26-0.drv’ failed
```

### Steps to reproduce

Use head nixpkgs (commit 854e00943b65396d2dadaa9d0e73bec5e34817d8) on osx and try to install that package

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
Darwin marks-mbp-3 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre-git"

**Comment by mbucc** [comment]
Per @copumpkin's comment in #17902, I will try upgrading OSX.

**Comment by mbucc** [comment]
Upgraded to 10.12 (Sierra) and this package installed fine.  Closed.

**Comment by domenkozar** [comment]
I also hit this and opened https://github.com/NixOS/nix/pull/1199
