### ISSUE TITLE
Haskell infrastructure doesn't include sublibs with cabal

### ISSUE THREAD

**Issue by MangoIV** [NixOS/nixpkgs#191481]
### Describe the bug

When trying to depend on a sublibrary of a package in `haskellPackages`, cabal reports that the component is missing although it *does* exist in the source.

### Steps To Reproduce
1. make a new cabal project
2. add `attoparsec:attoparsec-internal` to your build depends 
3. open a new shell with `nix-shell -p cabal-install -p "haskell.packages.ghcWithPackages (ps: [ps.attoparsec])"`
4. make sure your cabal version (`cabal --version`) is above `3.4`
5. try to `cabal repl` your project
6. error: 
```
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: bla-0.1.0.0 (user goal)
[__1] next goal: attoparsec (dependency of bla)
[__1] rejecting: attoparsec-0.14.4/installed-CgGnI4Zw7rLxLPa1up6Ms (does not
contain library 'attoparsec-internal', which is required by bla)
[__1] fail (backjumping, conflict set: attoparsec, bla)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: bla, attoparsec
```  

### Expected behavior
Nix includes the sublibs just like the normal lib

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.8, NixOS, 22.11 (Raccoon), 22.11.20220913.78bce16`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(mangoiv): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by MangoIV** [comment]
My reproducer is actually wrong, I will open again if I find one with a public sublib.

**Comment by Shimuuar** [comment]
@MangoIV  `vector-0.13.2`  (not yet in snapshot) does provide public sublibary. 

It looks like nix is able to build packages which depend on sublibraries. However in environment created using `ghcWithPackage` ghci cannot access sublibraries, cabal build can't find them either.

**Comment by MangoIV** [comment]
That’s a known issue I think. There’s something wrong with the package DB. I haven’t had more time to trouble shoot this though, it seems quite hairy.

**Comment by Shimuuar** [comment]
I also tried to patch `*.conf` files by adding `exposed: True` to subliraries. this way ghci is able to load modules but cabal still doesn't see them. It seems we have several mechanisms for looking up libraries.

BTW is there issue for tracking progress on this?

**Comment by MangoIV** [comment]
There’s at least on here and at least one at the haskell.nix repo.
