### ISSUE TITLE
pgadmin 6.12 failed to build

### ISSUE THREAD

**Issue by boozedog** [NixOS/nixpkgs#191511]
### Steps To Reproduce
1. build pgadmin.service

### Build log
```
building the system configuration...
error: builder for '/nix/store/qvd2f9k1nakpdrbnc7627a32h3himixy-python3.10-flask-2.2.2.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'Flask-2.2.2.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/Flask-2.2.2/dist /build/Flask-2.2.2
       > Processing ./Flask-2.2.2-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement Werkzeug>=2.2.2 (from flask) (from versions: none)
       > ERROR: No matching distribution found for Werkzeug>=2.2.2
       > 
       For full logs, run 'nix log /nix/store/qvd2f9k1nakpdrbnc7627a32h3himixy-python3.10-flask-2.2.2.drv'.
error: 1 dependencies of derivation '/nix/store/shjp3g6fcag9a693260j2dk21kjvnysi-pgadmin-6.12.drv' failed to build
error: 1 dependencies of derivation '/nix/store/v2afk6yvxgbny0k88g3dwjqza17aq0ad-unit-pgadmin.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vglfmmw4qnrxx5k097pjgjzmpa9p9d3m-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ss52bi9ja5rvw2s9k9yh7mvpzac67mgb-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gsszxmchwjagg9wjlv9h7apq2cp6lsyc-nixos-system-dab-xps-nixos-22.11.20220914.1158501.drv' failed to build
```

### Notify maintainers
@gador 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
Built from flake using nixos-unstable
```

**Comment by gador** [comment]
I know.

The PR #188575 needs to be merged.

**Comment by boozedog** [comment]
@gador seems like it might be some time before this gets fixed.

In the meantime, is there a way I could like force my system to use an older version of pgadmin? I'm using flakes for my system config.

**Comment by boozedog** [comment]
@gador OK I got it working for now by changing my `flake.nix` as follows:

```
nixpkgs.url = "github:gador/nixpkgs/e5061559f3a7cc1382e980c5c35126725cb965a7";
```

Please let me know if that's a terrible idea in your opinion ...

**Comment by gador** [comment]
No, not really. I use my branch `current` which I regularly update, which includes my cherry-picked commits.
The commit you picked reflects the status of `master` at the time of the commit of pgadmin (and obviously the changes to pgadmin)

You just need to be aware that due to the pinning, a `nix flake update` will not update `nixpkgs` currently and should probably be reverted once the PR got merged.

**Comment by boozedog** [comment]
@gador thanks that's what I'll do!

**Comment by gador** [comment]
The PR needs to be merged. AFAIK everything is done with the PR

**Comment by boozedog** [comment]
Got it working using `github:NixOS/nixpkgs/2e977bf954e84a981b15ff4d2442802ce9b675f9` in my flake.
