### ISSUE TITLE
GCC cannot print its configuration options

### ISSUE THREAD

**Issue by DavidEGrayson** [NixOS/nixpkgs#19151]
## Issue description

It seems like any version of GCC 5.4.0 compiled by Nix cannot print its own configuration options when you run it with the `-v` option.  Usually GCC prints a line that says "Configured with:" followed by the arguments that were passed to its configure script.
### Steps to reproduce

Run `nix-shell -p hello` and then run `gcc -v`.  It just says "Configured with:" and has no configuration options on that line.
### Workaround

I suppose I can just look at the derivation files for the GCC in question to see how it was configured/built.
## Technical details
- System: Arch Linux x86_64
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09pre88195.26d2577

**Comment by shlevy** [comment]
I think the reason for this is that otherwise gcc would keep a reference to all of its build-time dependencies, since those are hard-coded in the configure string, even if it didn't otherwise need them at runtime.

**Comment by Ericson2314** [comment]
Could we mangle the hash, e.g., insert underscores, as a hack around this?

**Comment by vcunat** [comment]
Probably possible, but I'm not sure it would be worth it.

**Comment by Ericson2314** [comment]
If I have some time I'll take a look at whatever patch removes the ability right now. If one can just sed a built-time log file, should be easy enough. If one needs to patch some C in GCC probably not worth ti.

**Comment by DavidEGrayson** [comment]
I think mangling the hashes would just require one line that calls `sed` inside of the top-level `configure` file.  There is a variable there called `TOPLEVEL_CONFIGURE_ARGUMENTS` that holds the arguments.

Does anyone know in particular what build-time dependencies GCC has which are not run-time dependencies?  If those dependencies are small then maybe we should just have the full configure flags be printed and not try to mangle anything.

**Comment by vcunat** [comment]
>  If those dependencies are small

They are significant. It depends on the tools that bootstrap it, for example.

**Comment by Ericson2314** [comment]
*Transitively* bootstrap, I might clarify. If it's just a sed it's definitely worth it.

**Comment by DavidEGrayson** [comment]
Are you sure that all the bootstrap tools are listed in the arguments to `configure`?  The transitive ones would certainly not be there.

**Comment by vcunat** [comment]
Right, that might be true. I don't remember what exactly we pass among the flags.

**Comment by Ericson2314** [comment]
Er yeah, I meant runtime deps are transitively part of the closure, not transitively listed. And good point about $PATH.

**Comment by copumpkin** [comment]
We already have a `nukeReferences` [tool](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/nuke-references/default.nix) that does the magic `sed` invocation for us, if that helps.

**Comment by Profpatsch** [comment]
(triage) has this been fixed?

**Comment by tomberek** [comment]
(triage) Not fixed, but we should consider closing due to age

**Comment by copumpkin** [comment]
Why is "closing due to age" a thing? If things are still desirable, I don't see why keeping information about a given desired feature/bug in a canonical discoverable location is a bad thing. Closing it just makes it harder for new folks to find out previous knowledge about the issue.

**Comment by tomberek** [comment]
Not a big deal.  Perhaps add a label for backlog? I’m just trying to go through old issues and PR’s to clean them up right now. Having thousands of open issues can be intimidating, Perhaps mark as low priority?

**Comment by Profpatsch** [comment]
Anything to move this forward?

**Comment by Profpatsch** [comment]
okay, closing because no replies.
