### ISSUE TITLE
intel-ocl: cannot download source from any mirror

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#191619]
### Describe the bug

```
...
building '/nix/store/qc75z9m71d83w7v8h41l2n8w8l47di3q-source.drv'...

trying https://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   145    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 403

trying http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   145    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403
error: cannot download source from any mirror
error: builder for '/nix/store/qc75z9m71d83w7v8h41l2n8w8l47di3q-source.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/p51yznsw68gcwq1a1hyhjxvmn1pgaqgy-intel-ocl-5.0-63503.drv' failed to build
...
```

### Steps To Reproduce
1. Add `hardware.opengl.extraPackages = with pkgs; [ intel-ocl ];` to system config
2. and rebuild

### Expected behavior
No errors please.

### Additional context

This seem to be a frequent issue.

https://github.com/NixOS/nixpkgs/issues/166886
https://github.com/NixOS/nixpkgs/pull/166901
https://github.com/NixOS/nixpkgs/issues/155664

### Notify maintainers
@kierdavis

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.62, NixOS, 22.05 (Quokka), 22.05.3065.178fea1414a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tpwrules** [comment]
Looks like the archive.org URL in https://github.com/NixOS/nixpkgs/pull/179342 never got backported to 22.05. Is there a process to do a manual backport?

**Comment by davidak** [comment]
@tpwrules it is documented here: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#backporting-changes
