### ISSUE TITLE
Neovim opt packages are put in start directory

### ISSUE THREAD

**Issue by ObsidianChickenz** [NixOS/nixpkgs#191614]
### Describe the bug
All of my Neovim plugins that I installed as opt are put in the start directory, forcing them to autoload.

### Steps To Reproduce
1. Install Neovim plugins via the module. (`programs.neovim.configure.packages.myVimPackage.opt = [ # Put plugins here ];`)
2. Build the system
3. Run `ls` on the opt folder (`/nix/store/hash-vim-pack-dir/pack/myNeovimPackages/opt`)

### Expected behavior
Nix should install Neovim packages from the opt list into the opt folder.

### Notify maintainers

@manveru @rvolosatovs 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.8, NixOS, 22.11 (Raccoon), 22.11.20220914.1158501`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by teto** [comment]
ha yeah I think that's here: 
https://github.com/NixOS/nixpkgs/blob/6560d311d5cdcc4e2c6a9fb3b9c8fad6bcfef747/pkgs/applications/editors/neovim/utils.nix#L173 calls https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/neovim/utils.nix#L33 but loses the "optional" character of the plugin. 
Interested in fixing that @ObsidianChickenz ? would be nice to test this as well.

**Comment by ObsidianChickenz** [comment]
I'd be interested in fixing it, but I don't know where to start. Can you give me any tips?

**Comment by teto** [comment]
so `makeNeovimConfig` is the interface I would like to promote. It accepts as argument an array "plugins" of the form `[ { plugin=far-vim; config = "let g:far#source='rg'"; optional = false; } ]`. 
```
      genPlugin = packageName: {start ? [], opt?[]}:
        start ++ opt;
```
should become
```
      genPlugin = packageName: {start ? [], opt?[]}:
        start ++ (map (p: { plugin = p; optional = true; }) opt);        
```
then you can add a test in pkgs/applications/editors/neovim/tests/default.nix that fails on master but succeeds with your patch. You can run the tests via `nix-build -A neovim.tests ~/nixpkgs`

**Comment by colin-heffernan** [comment]
Alt account here, will update as things progress on my end.

**Comment by colin-heffernan** [comment]
I have a test written and I think I found where optional is set, but I don't know why it's failing. It uses lib.partition to split the list of plugins on whether they are optional, but for some reason they still all get put into start in genPlugin.

**Comment by colin-heffernan** [comment]
Going into `genPlugin`, opt is working fine. Coming out from `genPlugin`, and even out of `lib.mapAttrsToList`, the plugin is fine, and it says optional is true. Things go wrong somewhere after `res` inherits `plugins`.

**Comment by colin-heffernan** [comment]
I think my test is slightly messed up. I manually checked the packpath and the test's plugin was in the `/opt/` folder. However, the test nvim couldn't see the packpath, so I assume that's the fault of the test being set up incorrectly.

**Comment by colin-heffernan** [comment]
I think I just did it, opening a PR now.

**Comment by teto** [comment]
pr in question: https://github.com/NixOS/nixpkgs/pull/191733
