### ISSUE TITLE
nixpkgs expression broken by python package `uncompyle6`

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#19160]
## Issue description

#19158 includes a reference to `spark_parser` that doesn't exist.

### Steps to reproduce

Try to evaluate the nixpkgs expression and get:

    error: undefined variable ‘spark_parser’ at /home/mdorman/src/nixpkgs/pkgs/top-level/python-packages.nix:12029:42

Without wishing to seem unkind, I have to wonder if these changes were tested at all before being submitted?

@7c6f434c @groxxda 

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by 7c6f434c** [comment]
Hm, this actually breaks `pythonPackages.hypothesis`. Looks like the first part of the update (`mccabe`) was tested fine, and the hypothesis update was committed wrong with wrong `git add -i` — probably the mistake was made _after_ testing…

**Comment by 7c6f434c** [comment]
`uncompyle6` builds OK now

**Comment by 7c6f434c** [comment]
`test-eval-release.sh` passes now…

**Comment by 7c6f434c** [comment]
`pythonPackages.hypothesis` builds fine, too. Is there anything else to check @mdorman ? Thanks for catching this.

**Comment by groxxda** [comment]
I'm _really_ sorry for the trouble. Of course the changes were tested (they cause a huge rebuild including 3x webkitgtk24x) yesterday. In the mean time there were overlapping changes (see pr for details) that I fixed and tested again. Then cherry-picked the hypothesis update range but forgot the first commit is not included. Will try to be more careful in the future..

**Comment by mdorman** [comment]
@groxxda it's hardly the end of the world; ultimately I suspect it's just a reminder to all of us that git's flexibility and power in being able to reorder and cherry-pick stuff around sometimes puts us in a great position to shoot ourselves in the foot.  Thanks for getting things back in order.
