### ISSUE TITLE
sabnzbd service is broken

### ISSUE THREAD

**Issue by d4g** [NixOS/nixpkgs#19166]
## Issue description
The service does not start successfully.

### Steps to reproduce
Enable service:
services.sabnzbd.enable = true;

It seems, that the wrapper script is broken:
/nix/store/pdm2f331jvxp9s8mz6npzi4chsvyfp35-sabnzbd-0.7.20/bin/..sabnzbd-wrapped-wrapped:

`import sys;import site;import functools;sys.argv[0] = 'sabnzbd';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/9v5n8kmw24cqfyvlkj5b3hf1mbdid0sa-python2.7-pyopenssl-16.0.0/lib/python2.7/site-packages','/nix/store/7c1cl4jqwrk4f9vpilzyplib7f54qppk-python2.7-cryptography-1.5.1/lib/python2.7/site-packages','/nix/store/8jx3dfm7g2sknq3k3djw4qrypia0vaiz-python2.7-six-1.10.0/lib/python2.7/site-packages','/nix/store/i51c2w12h2hrn05fk9d2fnknv6wi4p47-python2.7-setuptools-26.1.1/lib/python2.7/site-packages','/nix/store/498ih4abg134fr3ipvvrp3mxm8zx37f8-python2.7-idna-2.0/lib/python2.7/site-packages','/nix/store/9pazgxc95g699gk2m1yfyn0kgsghd4v3-python2.7-ipaddress-1.0.16/lib/python2.7/site-packages','/nix/store/nmk4dxk6vmrsqz5w53mfi4xjpg89m43v-python2.7-pyasn1-0.1.9/lib/python2.7/site-packages','/nix/store/pzjxn15b04v95wvwrawc8z80snkzq75z-python2.7-cffi-1.7.0/lib/python2.7/site-packages','/nix/store/yrd9r1shbxgg02gy4p397p2pwvgs7wf9-python2.7-pycparser-2.14/lib/python2.7/site-packages','/nix/store/gwi4xfqzhcx2s7yi65y4aiia7yss8g9q-python2.7-pyasn1-modules-0.0.8/lib/python2.7/site-packages','/nix/store/mpg3rgbhm50a1v3j18i1k3hi7z8512yj-python-sqlite3-2.7.12/lib/python2.7/site-packages','/nix/store/x0m6kiik7z457ig1x0i36s9a1hgrw327-python2.7-pytz-2016.6.1/lib/python2.7/site-packages','/nix/store/hpi1y4ppb767d0h54xcs86c5vxs9xxd9-python2.7-enum34-1.0.4/lib/python2.7/site-packages','/nix/store/4im2pl2ynaggxpp8ldjf5p2k0n0gbqr1-python2.7-cheetah-2.4.4/lib/python2.7/site-packages','/nix/store/1amq3aysnp0zakii90pyfh2nq9nnz1dj-python2.7-markdown-2.6.4/lib/python2.7/site-packages'], site._init_pathinfo());
/nix/store/w9020qsqapllmfcdh2x686y8ng6n15mh-python-2.7.12/bin/python /nix/store/pdm2f331jvxp9s8mz6npzi4chsvyfp35-sabnzbd-0.7.20/SABnzbd.py $*`

This seems to me to be a weird mix of a python script and a shell script. The script fails to execute. No shebang ist specified.

## Technical details

* System: 17.03pre92039.adfcc2d (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre92039.adfcc2d

**Comment by FRidh** [comment]
hmm, I updated sabnzbd in 36586c2ab3171445d17dd2d5fd3569c6d186ad7e and f3d7afa86d8bda6e0ef8aa9def6475ab5b0e6bf5 and its working here

**Comment by FRidh** [comment]
I now see that you were testing an older version.

**Comment by d4g** [comment]
... i am on nixos unstable and updated everything yesterday.

**Comment by FRidh** [comment]
But the channel with the fixes hasn't updated yet.

**Comment by d4g** [comment]
Ok. So I have to wait for nixos-unstable to update, right?
