### ISSUE TITLE
nixos-rebuild: -I flag is not documented in man page

### ISSUE THREAD

**Issue by louwers** [NixOS/nixpkgs#191714]
## Issue description

The [man page of nixos-rebuild](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/man-nixos-rebuild.xml) does not document the `-I [path]` flag.

**Comment by samueldr** [comment]
It is documented now.

 - https://github.com/NixOS/nixpkgs/blob/eb3ce1cf0c5d552c237a45f9e5569cb3b15d6fa4/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.8#L35
