### ISSUE TITLE
Operator Mono Nerd Font

### ISSUE THREAD

**Issue by jab** [NixOS/nixpkgs#191827]
**Project description**
Operator Mono Nerd Font

**Metadata**

* homepage URL: https://github.com/40huo/Patched-Fonts/tree/master/operator-mono-nerd-font
* source URL: https://github.com/40huo/Patched-Fonts/tree/master/operator-mono-nerd-font
* license: 
* platforms: unix, linux, darwin, ...

**Comment by 13k** [comment]
afaik, Operator is not a free typeface: https://www.typography.com/fonts/operator/overview
