### ISSUE TITLE
librewolf is outdated on Nixos 22.05 and maybe on unstable as well

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#191944]
## Issue description

I'm new to Nixos but it is my understanding that the librewolf package in 22.05 is outdated (103.0-3), as Firefox 104 brought numerous [security fixes](https://www.mozilla.org/security/advisories/mfsa2022-33/). The unstable channel has got librewolf 104.0-1, which also doesn't correspond to the current version of firefox (104.0.2).

Also, why doesn't the librewolf package follow the version number of firefox (104.0.2) but is missing the last digit? Can i rely on librewolf being up-to-date? 

I tried to send an email to the listed package maintainer @squalus but the email was returned as undeliverable.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by buckley310** [comment]
https://github.com/NixOS/nixpkgs/pull/188759

**Comment by buckley310** [comment]
So as soon as the 22.05 branch advances, it will have the same version of librewolf as unstable.
The good news about 104.0.1 -> 104.0.2 is that it doesn't look like a security update.

On a related note, firefox 105 comes out tomorrow, so maybe at this point just wait a day and go straight to that.
https://wiki.mozilla.org/Release_Management/Calendar
