### ISSUE TITLE
pkgsMusl.go,pkgsStatic.go: build fails

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#191941]
### Steps To Reproduce

1. nix build .#pkgsMusl.go
2. nix build .#pkgsStatic.go

### Build log

* nix build .#pkgsMusl.go
  [logs](https://termbin.com/ra65)
  ![image](https://user-images.githubusercontent.com/5861043/191064073-1b349e50-fd1f-4e27-9aa9-f31d9e3d015f.png)

  Notice: Musl error is related to package: `bootstrap116`

* nix build .#pkgsStatic.go
  [logs](https://termbin.com/nv1i2)
  ![image](https://user-images.githubusercontent.com/5861043/191067253-085e61c8-4c4a-42a9-b602-36a25e93ce29.png)

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.8, NixOS, 22.11 (Raccoon), 22.11.20220918.f677051`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - channels(intj): `""`
 - nixpkgs: `/nix/store/fr68dr66gmggn62jir7vp1bcnignwxp9-source`
```

Pending:
* Mark `go` as broken for static & musl.

**Comment by superherointj** [comment]
On problem confirmation likely this should be marked as broken:

As `pkgsStatic.go` is not building too:

> broken = stdenv.targetPlatform.isMusl && !stdenv.targetPlatform.isStatic;

**Comment by yu-re-ka** [comment]
```diff
+++ b/pkgs/development/compilers/go/1.18.nix
@@ -250,7 +250,7 @@ stdenv.mkDerivation rec {
 
   checkPhase = ''
     runHook preCheck
-    (cd src && HOME=$TMPDIR GOCACHE=$TMPDIR/go-cache ./run.bash --no-rebuild)
+    (cd src && HOME=$TMPDIR GOCACHE=$TMPDIR/go-cache ./run.bash --no-rebuild${lib.optionalString stdenv.hostPlatform.isMusl " --run=='!(^cgo_test$)'"})
     runHook postCheck
   '';

**Comment by yu-re-ka** [comment]
There are no musl bootstrap binaries available for the go compiler.
Alpine packaging uses their own bootstrap binaries.
Void packaging runs the upstream glibc bootstrap binaries with [gcompat](https://github.com/Stantheman/gcompat).

**Comment by yu-re-ka** [comment]
How is this solved?

**Comment by superherointj** [comment]
> How is this solved?

Issue is solved for me. Open an issue for you.
