### ISSUE TITLE
Add msedgedriver

### ISSUE THREAD

**Issue by fel1xjh** [NixOS/nixpkgs#192050]
**A WebDriver server for running Selenium tests on Microsoft Edge**

**WebDriver is an open-source tool for automated testing of web apps across many browsers. It provides capabilities for navigating to web pages, user input, JavaScript execution, and more.**

* homepage URL: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
* source URL: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by SigmaSquadron** [comment]
Completed in #348821
