### ISSUE TITLE
Build fails due to unpack-bootstrap-tools.sh:unxz for arbitrary package

### ISSUE THREAD

**Issue by proteansec** [NixOS/nixpkgs#19202]
## Issue description

Cloned fresh nixpks, switched to origin/release-16.09 branch and run "nix-build -A vagrant" and obtained error while building.
### Steps to reproduce

Clone the nixpkgs:

> # git clone git://github.com/NixOS/nixpkgs.git

Checkout to the release-16.09 branch:

> # git checkout -b origin/release-16.09 

Try to build vagrant:

> **# nix-build -A vagrant**
> ...
> **\* Downloading ‘http://cache.nixos.org/nar/1mykiyxi9n996ykd5xf2qnlsr7g4xq7h6rycc0k22r50gsd84q7r.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/a048k7r603jq7sphp907zja27gpyzbx1-zlib-1.2.8.tar.gz’...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  557k  100  557k    0     0  53720      0  0:00:10  0:00:10 --:--:-- 47157
> 
> building path(s) ‘/nix/store/x0npxkrhasb6cjw7pyd0brzx9i17chf6-bootstrap-tools’
> Unpacking the bootstrap tools...
> : not found  5 4309k    0     0  42770      0  0:29:08  0:01:43  0:27:25 47433/nix/store/iawi9wwlpxdkj1l7jkq84dsi3npaz8qk-unpack-bootstrap-tools.sh: line 5:
> builder for ‘/nix/store/rr9v0qhiga7kycv0das0cyf7309zpzpy-bootstrap-tools.drv’ failed with exit code 127
> killing process 459
> killing process 584
> cannot build derivation ‘/nix/store/3czcn7gp2gslpcnfzrfig9334cbmlql5-acl-2.2.52.drv’: 1 dependencies couldn't be built
> killing process 1555
> cannot build derivation ‘/nix/store/gfpbd2r4aras8qhkscpm011yvff1l1jr-attr-2.4.47.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/kbisdd5vzjr01d4n04ifpmrp28j2x8iw-bash-4.3-p46.drv’: 1 dependencies couldn't be built
> killing process 454
> killing process 456
> killing process 461
> killing process 460
> cannot build derivation ‘/nix/store/j8nps3z2fh6136y7blsd0cp7igcq36s7-bzip2-1.0.6.0.1.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/ngzfrgjv0bp33bzi77mmf17n0zrdbgvl-coreutils-8.25.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/ghidk9l2xjia1b16gc42i4ya1shynhc4-diffutils-3.5.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/4kiq5szd570c2a1r09ijyg49gcvc9f3q-findutils-4.6.0.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/v4g49nb6kwqgbpbmwdzj9wbbg7hw1jiq-gawk-4.1.3.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/9a4bp0dnd698p1j1y3x74isf2qmqjba6-gcc-5.4.0.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/gv4i6hqd7sr3bdy7bjnzfrpizh1p617s-gcc-wrapper-5.4.0.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/xk13jhnak6jgmjbq8wmvghnjl34hnpyg-glibc-2.24.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/dl8gbhhha1l0bbxqnb30xs77b7wl38dl-gnugrep-2.25.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/n06rir10b4mnw4wfq26pk6m0mnnb6pvz-gnumake-4.2.1.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/iprwsx1xnzl6v3bv9gs88c90r0kqrkm6-gnused-4.2.2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/ixb160rvyprlkjhw1s6swddbfa5xf8k5-gnutar-1.29.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/lm564js0bbjzlr8is7inkr6xad6k6jm1-gzip-1.8.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/bkypfa6x87f9lal1djhzy5nasbgwkfgy-patch-2.7.5.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/96pmks0fjdp3q2a560473g7fnhknlv6v-patchelf-0.9.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/1g7flxjf4rd62fqbqpnlx3x38ljwwzza-paxctl-0.9.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/44w030glx3n9h2k0qnw6sz2m843m9ayf-xz-5.2.2.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/mcbiqgm2il9hy3k9finwf8hs85vm28y2-zlib-1.2.8.drv’: 1 dependencies couldn't be built
> cannot build derivation ‘/nix/store/2dnm79hsa6haj3wfw96sww9hp4bsjqvy-vagrant-1.8.5.drv’: 1 dependencies couldn't be built
> error: build of ‘/nix/store/2dnm79hsa6haj3wfw96sww9hp4bsjqvy-vagrant-1.8.5.drv’ failed
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

> 16.09beta335.7617e7e (Flounder)
- Nix version: (run `nix-env --version`)

> nix-env (Nix) 1.11.4
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

> "16.09beta335.7617e7e"
### Purpose

I'm doing this, because I would like to install **vagrant-libvirt**. 

> # vagrant plugin install vagrant-libvirt
> Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
> Bundler, the underlying system Vagrant uses to install plugins,
> reported an error. The error is shown below. These errors are usually
> caused by misconfigured plugin installations or transient network
> issues. The error from Bundler is:
> 
> An error occurred while installing ruby-libvirt (0.6.0), and Bundler cannot continue.
> Make sure that `gem install ruby-libvirt -v '0.6.0'` succeeds before bundling.
> 
> Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

This is obviously due to the reason that we cannot install gems manually, since we don't have access to the nix store due to being read-only. This is why, I propose we inspect the [vagrant](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/vagrant/default.nix) pkg and add an optional flag for **vagrant-libvirt**. 

Maybe the simplest solution would be to add something like this to the installPhase of the vagrant package:

```
"$out/bin/vagrant" plugin install vagrant-libvirt
```

I propose the error obtained trying to build vagrant be fixed first, then proceeding further to vagrant-libvirt, possibly with another feature request or pull request; if somebody points me into the right direction about how to solve the above issue, I can probably put this together rather quickly.

**Comment by Mic92** [comment]
I thought vagrant installs into home by default. Adding libvirt to vagrant as an option would be an option, but getting `plugin install` working would be also desirable.

**Comment by proteansec** [comment]
Hi,

I modified the https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/pkgs/stdenv/linux/scripts/unpack-bootstrap-tools.sh#L2 into the following:

> echo Unpacking the bootstrap tools...$builder : $out : $tarball : $(unxz --help) 

When rebuilding the package, the following was displayed to stdout, where the **unxz** was not found - thanks @matejc .

> /nix/store/vcglbrdajzbp72cxa2br8x9zl71a2jij-unpack-bootstrap-tools.sh: line 2: unxz: not found

This isn't specific to vagrant, but the build fails with every package, which is why I'm changing the title of this issue.

**Comment by Profpatsch** [comment]
(triage) does this still happen?

**Comment by Mic92** [comment]
According to https://github.com/NixOS/nixpkgs/pull/49220 this is fixed.
