### ISSUE TITLE
smartd module notification emails end up in spam

### ISSUE THREAD

**Issue by ettom** [NixOS/nixpkgs#192147]
### Describe the bug
`services.smartd.notifications.mail` will send emails with `undisclosed-recipients :` in the To: field. For me, this causes rspamd to categorize these emails as spam. Notably, rspamd assigns the following symbols to the mails:
```
R_UNDISC_RCPT (3)
FORGED_RECIPIENTS (1)
```

https://github.com/NixOS/nixpkgs/blob/814026db2ded64af1526843a774478c3ece3d748/nixos/modules/services/monitoring/smartd.nix#L23

### Steps To Reproduce
1. Configure `services.smartd.notifications.mail`
2. Send test email, can probably be done by setting `-M test` in the relevant `services.smartd.devices.*.options` field
3. Check if email landed in spam folder (dependent on the spam filter and its configuration)

### Expected behavior
The module sets the To: field to the value of `services.smartd.notifications.mail.recipient`. As far as I can tell, this would solve the problem without any downsides.

### Notify maintainers

@tmplt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.64, NixOS, 22.05 (Quokka), 22.05.3153.20dc478985d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-hardware, nixos-unstable, sops-nix"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by RageKnify** [comment]
@tmplt can I open a PR changing the line in question to:
```
To: ${nm.recipient}
```
? I have tested it locally and it did fix the problem improving the score given by `rspamd`

**Comment by tmplt** [comment]
I forgot this was upstreamed. Feel free to open a PR.
