### ISSUE TITLE
nvi doesn't compile because of `-lcurses` passed to the linker

### ISSUE THREAD

**Issue by jxy** [NixOS/nixpkgs#19214]
## Issue description

Try to build nvi.  The configure phase would die because it couldn't find some system calls.  Investigating the build directory, `mybuild`, you would find that all of the configure script generated code failed to build because the linker couldn't find the library `-lcurses`.

Simple fix: add one more line to the `sed` command in the `patchPhase`

```
-e s@-lcurses@-lncurses@ \
```
### Steps to reproduce

Try to build nvi.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, …)

```
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```
- Nix version: (run `nix-env --version`)

```
nix-env (Nix) 1.11.4
```
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
"17.03pre92059.b3d7eae"
```

**Comment by Mic92** [comment]
Do you want to make a pull request against nixpkgs?

**Comment by Profpatsch** [comment]
Builds on current nixpkgs.
