### ISSUE TITLE
Missing 'clean up' reference in nix-env help

### ISSUE THREAD

**Issue by winks** [NixOS/nixpkgs#19216]
## Issue description

I only found about `nix-collect-garbage` after some searching (not long, but still) because (as a beginner) I had only used `nix-env` and `nix-channel`. I would have expected to find something in the `nix-env` man page (there is something about  `--delete-generations` but it's not helpful), even just a reference. 
- System: Debian
- Nix version: nix-env (Nix) 1.11.4

**Comment by Profpatsch** [comment]
Superseded by https://github.com/NixOS/nix/issues/2252
