### ISSUE TITLE
pysaml depends on pythonFull?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#19225]
## Issue description

`pysaml2` depends on `dbm`, which is a core package of python that's only available on `pythonFull`.

### Steps to reproduce

Run:

```
nix-shell -p "(import ./. {}).python" -p "(import ./. {}).pythonPackages.pysaml2"
```

In the shell, import `saml2.server`, and it'll tell you 

```
>>> import saml2.server
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/3rn4v9cqh5yi6askkcdjq4wipmswxjr9-python2.7-pysaml2-3.0.2/lib/python2.7/site-packages/saml2/server.py", line 12, in <module>
    import dbm
ImportError: No module named dbm
```

If instead you use:

```
nix-shell -p "(import ./. {}).pythonFull" -p "(import ./. {}).pythonPackages.pysaml2"
```

Everything works fine.

## Technical details

* Nix version: nix-env (Nix) 1.10
* Nixpkgs version: e70a2badc2f956ecfb975484e2dc3037a2e24573

**Comment by domenkozar** [comment]
It seems like we don't build `dbm` extension when whitelisting for minimal python.

**Comment by copumpkin** [comment]
This goes back to an earlier question I raised about how much is this whole "minimal python" thing buying us in the grand scheme of things? Is it 100MB of closure difference or a handful?

**Comment by FRidh** [comment]
@copumpkin its about 40 MB difference in the case of Python 2.7, of which 20 MB is `tkinter`. I personally don't care at all about this bit of extra space, but others do, so we need to find some kind of balance. In https://github.com/NixOS/nixpkgs/pull/19309 I modified the expressions to put only `tkinter` in a separate output. I think that's the right balance.

**Comment by FRidh** [comment]
```
$ nix-shell -p pythonPackages.pysaml2 -I nixpkgs=. --run "python -c 'import saml2.server'"
```
works on staging since #19309 was merged.
