### ISSUE TITLE
ova fails to rebuild the default configuration

### ISSUE THREAD

**Issue by juh2** [NixOS/nixpkgs#19223]
## Issue description

The OVA fails to rebuild the default configuration
### Steps to reproduce

Install the fresh ova NixOS 16.09.663.3dc0897 (x86_64-linux)

Import the ova to VirtualBox

Start NixOS

type: nixos-rebuild test

Error see attached screenshot.
## Technical details

https://d3g5gsiof5omrk.cloudfront.net/nixos/16.09/nixos-16.09.671.c89c1ba/nixos-16.09.671.c89c1ba-x86_64-linux.ova

![virtualbox_nixos 16 09 663 3dc0897 x86_64-linux _04_10_2016_15_56_01](https://cloud.githubusercontent.com/assets/1416069/19077389/bde71bda-8a4c-11e6-8512-de1de6598815.png)

**Comment by domenkozar** [comment]
The interesting output is hidden (should scroll up), but this might be a side effect of https://github.com/NixOS/nixpkgs/commit/58db7f508f815ac7c1e12e3abd8f7d0fcf25a0cb /cc @obadz

**Comment by matthewbauer** [comment]
This doesn't seem to be a problem any more. Can we close iy?
