### ISSUE TITLE
keepassxc tests are failing

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nixpkgs#192247]
### Steps To Reproduce

#175104 introduced a regression in `nixos/tests/keepassxc.nix`

Reproducible using `nix-build nixos/tests/keepassxc.nix`

### Build log

```
error: builder for '/nix/store/v169qf39icb49phzd86fnyfczlmyz9c2-vm-test-run-keepassxc.drv' failed with exit code 1;
       last 10 log lines:
       > machine # [   35.686089] traps: .keepassxc-wrap[995] trap int3 ip:7f3232b0e19f sp:7ffecedcb200 error:0 in libglib-2.0.so.0.7200.3[7f3232ad0000+8c000]
       > (finished: must succeed: sleep 5, in 5.08 seconds)
       > machine: must succeed: ps -e | grep keepassxc
       > machine: output:
       > Test "Can open existing database" failed with error: "command `ps -e | grep keepassxc` failed (exit code 1)"
       > cleanup
       > kill machine (pid 6)
       > machine # qemu-kvm: terminating on signal 15 from pid 4 (/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/bin/python3.10)
       > (finished: cleanup, in 0.04 seconds)
       > kill vlan (pid 5)
       For full logs, run 'nix log /nix/store/v169qf39icb49phzd86fnyfczlmyz9c2-vm-test-run-keepassxc.drv'.
```

### Notify maintainers

@turion @jonafato 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.1-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20220918.f677051`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - nixpkgs: `/nix/store/iw3xi0bfszikb0dmyywp7pm590jvbqvs-source`
```

**Comment by rapenne-s** [comment]
This predates #192226 :/ so I prefered to make another issue.

**Comment by fstamour** [comment]
I found this issue when looking if somebody else has the same problem than me: when I try to open a database (or press `ctrl-o`, like the test does) keepassxc crashes, leaving the following in the console:

```
(keepassxc:153086): GLib-GIO-ERROR **: 22:05:01.981: Settings schema 'org.gtk.Settings.FileChooser' is not installed
fish: Job 1, 'keepassxc' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

I have no idea if it's related, but it's at the very least suspicious that my keepassxc crashes at the same place that it crashes in the tests.

---

I also found this PR #175104 that mentions both GTK and Qt, _might_ be related too.

---

Hopes this helps, sorry for the uncertainty, I don't have more time to investigate :sweat_smile:

**Comment by 7FM** [comment]
I think I might have found the problem, see https://github.com/NixOS/nixpkgs/pull/203534.
The problem appears to be that the `gappsWrapperArgs` are ignored when added in the `postFixup` instead of the `preFixup` phase. Hence, the created wrappers did not contain any `gappsWrapperArgs`, which causes the tests to fail due to the missing `gsettings-schemas` path in `XDG_DATA_DIRS`.
Still need to run the tests, but manually testing and inspecting the wrappers worked just fine.

**Comment by turion** [comment]
The test still fails, but with a different message now:

```
(finished: must succeed: ps -e | grep keepassxc, in 0.03 seconds)
machine: waiting for foo.kdbx to appear on screen
machine # [   53.192300] systemd[1]: systemd-hostnamed.service: Deactivated successfully.
machine # [  560.706877] systemd[1]: Started Logrotate Service.
machine # [  560.718448] systemd[1]: logrotate.service: Deactivated successfully.
machine # [  906.956017] systemd[1]: Starting Cleanup of Temporary Directories...
machine # [  907.034273] systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
machine # [  907.036584] systemd[1]: Finished Cleanup of Temporary Directories.
machine # [  907.037323] systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.
error: building of '/nix/store/v3i53cc5ldghwqr48wyvp5cy9b3v2nxa-vm-test-run-keepassxc.drv!out' from .drv file timed out after 3600 seconds
```

See also https://github.com/NixOS/nixpkgs/pull/203534#issuecomment-1330541093.

**Comment by eliandoran** [comment]
@rapenne-s , can we close this issue?
