### ISSUE TITLE
Upgrade default golang to 1.19

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#192333]
Golang releases once every 6 month and supports the latest two releases. These are currently

- 1.19 was released on 2022/08/02
- 1.18 was released on 2022/03/15 and will be EOL around 2023/03, two months before 22.11's EOL.

Cf. https://endoflife.date/go

@c00w 
@kalbasit 
@Mic92 
@zowoq

**Comment by zowoq** [comment]
Besides fixing or pinning broken builds/nixosTests would need to check vendor hashes are reproducible or fix/pin them as well. 

The PR for 1.18 has more detail about what needs to be done when changing the default `go`: https://github.com/NixOS/nixpkgs/pull/179622

**Comment by tjni** [comment]
Would we accept a PR that pins every existing user of `buildGoModule` to `buildGo118Module` and switching the default to `buildGo119Module` on master. This would change the default for new modules and allow piecemeal work on migrating  all existing modules.

I'm not against a single effort like https://github.com/NixOS/nixpkgs/pull/179622, but I don't think I could set aside the time to manage something like that, and I'm interested in helping out.

**Comment by mweinelt** [comment]
@zowoq @Mic92 As the two active go maintainers, can both of you clarify whether you will take care of the required update?

**Comment by zowoq** [comment]
I'll do it this week.

**Comment by mweinelt** [comment]
I'll count that as a check-in for #194208. Thanks!

**Comment by zowoq** [comment]
I've rechecked vendor hashes after the staging-next merge, no breakage. As hydra catches up I'll continue fixing/pinning any other breakage from 1.19 that I didn't catch initially.

**Comment by mitar** [comment]
Which version of NixOS Docker image has/will have Go 1.19?

**Comment by mweinelt** [comment]
Go 1.19 is on NixOS unstable right now and will be part of NixOS 22.11. I'm not sure about the base of your docker images though.
