### ISSUE TITLE
Whisper by OpenAI (automatic speech recognition)

### ISSUE THREAD

**Issue by dit7ya** [NixOS/nixpkgs#192386]
**Project description**
Whisper is a general-purpose speech recognition model. It is trained on a large dataset of diverse audio and is also a multi-task model that can perform multilingual speech recognition as well as speech translation and language identification.

**Metadata**

* homepage URL: https://openai.com/blog/whisper/
* source URL: https://github.com/openai/whisper
* license: mit
* platforms: all

**Comment by mweinelt** [comment]
PTAL.
