### ISSUE TITLE
git has an undeclared runtime dependency on ssh

### ISSUE THREAD

**Issue by zopa** [NixOS/nixpkgs#1923]
Running `git clone` with my still-quite-new nix environment, I get:

    error: cannot run ssh: No such file or directory

Installing openssh fixes the problem for me, of course. But this means that git really ought to declare a dependency on openssh, no?

**Comment by mbrgm** [comment]
Is there a recommended solution for this now?

**Comment by peti** [comment]
The recommended solution is to patch SSH, IMHO. It's not hard, as @7c6f434c pointed out.

**Comment by grahamc** [comment]
Triage: this issue _does_ still exist on 16.03-beta:

```
$ nix-shell --pure -p git --command "git clone git@github.com:NixOS/nixpkgs.git"
Cloning into 'nixpkgs'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

**Comment by zimbatm** [comment]
Patched in #14207

**Comment by primeos** [comment]
The solution to this issue is now causing a different issue on Fedora: https://github.com/NixOS/nixpkgs/issues/160527
I'm not sure if we should really hard-code a SSH binary or if we should e.g. just reference a SSH binary as a fallback.
Opinions welcome :)

**Comment by primeos** [comment]
> I'm not sure if we should really hard-code a SSH binary or if we should e.g. just reference a SSH binary as a fallback.

FYI: https://github.com/NixOS/nixpkgs/pull/166334 is about to revert this and I currently believe that this is a good idea.
