### ISSUE TITLE
Can't find dual-function-keys package

### ISSUE THREAD

**Issue by petitengineer** [NixOS/nixpkgs#192487]
**Project description**
A plug-in for interception tools. Helps configure things like utilizing capslock as both escape on release and control when held. Helpful for Wayland users in particular.

**Metadata**

* homepage URL: https://gitlab.com/interception/linux/plugins/dual-function-keys
* source URL: https://gitlab.com/interception/linux/plugins/dual-function-keys
* license: mit.
* platforms: Linux

**Comment by infinisil** [comment]
It's already there, was added in https://github.com/NixOS/nixpkgs/pull/94097 :)

**Comment by petitengineer** [comment]
Okay, weird. I thought that all packages would show up on https://search.nixos.org/, but a search for "dual-function-keys" yields "no packages found". Moreover, nix-env won't resolve "nix-env -iA nixpkgs.dual-function-keys", but it _will_ resolve "nix-env -iA nixpkgs.interception-tools-plugins.dual-function-keys". The only way I was able to figure out how to install the package was by looking at https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/top-level/all-packages.nix . So I guess I should open an issue at https://github.com/NixOS/nixos-search/issues ?

**Comment by infinisil** [comment]
Ah no, the problem is that in `all-packages.nix` the definition of `interception-tools-plugins` needs a `recurseIntoAttrs` to expose nested packages:

```diff
-  interception-tools-plugins = {
+. interception-tools-plugins = recurseIntoAttrs {
    caps2esc = callPackage ../tools/inputmethods/interception-tools/caps2esc.nix { };
    dual-function-keys = callPackage ../tools/inputmethods/interception-tools/dual-function-keys.nix { };
  };
```

**Comment by petitengineer** [comment]
Ah, Okay. Can you commit the change to https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/top-level/all-packages.nix ?

**Comment by infinisil** [comment]
I'm a bit short on time, I'd appreciate it if you could make a PR for that, I can review and merge it if you ping me :)
