### ISSUE TITLE
SSH X forwarding broken

### ISSUE THREAD

**Issue by reinhardt** [NixOS/nixpkgs#19246]
## Issue description

X forwarding over ssh fails. No window opens, warning/error see below.

### Steps to reproduce

```
local:~$ ssh -Y remote
Warning: No xauth data; using fake authentication data for X11 forwarding.
remote:~$ hgk
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyapplication-specific initialization failed: couldn't connect to display "localhost:10.0"
```

### Analysis and workaround

strace has a line

`stat("/usr/X11R6/bin/xauth", 0x7ffde1c22f80) = -1 ENOENT (No such file or directory)`

Symlinking xauth to /usr/X11R6/bin/xauth fixes the issue:

`ln -s /run/current-system/sw/bin/xauth /usr/X11R6/bin/xauth`

## Technical details

* System: 17.03pre92039.adfcc2d (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre92039.adfcc2d
* SSH version: OpenSSH_7.3p1, OpenSSL 1.0.2i  22 Sep 2016

**Comment by CharlesHD** [comment]
I have the exact same issue.
I tried in `configuration.nix` : 
```
programs.ssh.forwardX11 = true;
programs.ssh.setXAuthLocation = true;
```
but both fail : `nix-rebuild switch` refuses to perform because XAuth location is not set.
Seems like setXAuthLocation is set to false somewhere else later.

**Comment by groxxda** [comment]
@CharlesHD please post the error message you are receiving, `programs.ssh.forwardX11 = true;` does not cause an error for me with `nix-rebuild switch`

**Comment by CharlesHD** [comment]
Of course, here the result of  `nix-rebuild switch --show-trace` : 
```
building Nix...
building the system configuration...
error: while evaluating the attribute ‘config.system.build.toplevel’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:246:5:
while evaluating ‘fold’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:29:19, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:127:12:
while evaluating ‘fold'’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:32:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:36:8:
while evaluating ‘showWarnings’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:93:18, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:100:16:
while evaluating ‘fold’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:29:19, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/system/activation/top-level.nix:93:23:
while evaluating ‘fold'’ at /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:32:15, called from /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/lib/lists.nix:36:8:

Failed assertions:
- cannot enable X11 forwarding without setting XAuth location
```

**Comment by groxxda** [comment]
@CharlesHD That `mkDefault` line is fairly new: https://github.com/NixOS/nixpkgs/commit/f3c32cb2c1344c9a831bb9e4f47c1b20527dbe0b

but even before that change, the assertion should not fail with `services.xserver.enable = true;` or `programs.ssh.setXAuthLocation = true;`

**Comment by CharlesHD** [comment]
Both are. Here is exactly my configuration.nix : 
```
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  networking.hostName = "nixos"; # Define your hostname.

  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "fr-bepo";
    defaultLocale = "en_US.UTF-8";
  };

  # Set your time zone.
  time.timeZone = "Europe/Paris";

  # List packages installed in system profile. To search by name, run:
  # $ nix-env -qaP | grep wget
  environment.systemPackages = with pkgs; [
    wget
    emacs 
    haskellPackages.xmobar
    dmenu
  ];

  # List services that you want to enable:
  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable the X11 windowing system.
  services.xserver = {
    enable = true;
    layout = "fr";
    xkbVariant = "bepo";
    
    displayManager.lightdm.enable = true;
    
    windowManager.xmonad.enable = true;
    windowManager.xmonad.enableContribAndExtras = true;
    windowManager.default = "xmonad";
    desktopManager.xterm.enable = false;
    desktopManager.xfce.enable = true;
    desktopManager.default = "xfce";
  };
   
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.extraUsers.charleshd = {
    isNormalUser = true;
    uid = 1000;
    name = "charleshd";
    group = "users";
    extraGroups = [
      "wheel" "disk" "audio" "video" "networkmanager" "systemd-journal"
     ];
    createHome = true;
    home = "/home/charleshd";
    shell = "/run/current-system/sw/bin/bash";
  };

  # The NixOS release to be compatible with for stateful data such as databases.
  system.stateVersion = "16.09";

  programs.ssh.forwardX11 = true;

}
```
Still, I get the error.

**Comment by groxxda** [comment]
There is also https://github.com/NixOS/nixpkgs/blob/f3c32cb2c1344c9a831bb9e4f47c1b20527dbe0b/nixos/modules/services/networking/ssh/sshd.nix#L366
Can you set `services.openssh.forwardX11 = true;` and test again?
This is slightly messy...

**Comment by reinhardt** [comment]
FTR, I don't get an error from `nix-rebuild switch` when setting `programs.ssh.setXAuthLocation`, but it doesn't solve the original problem either.

**Comment by CharlesHD** [comment]
Setting `services.openssh.forwardX11 = true;` fixed the issue for me too. I do not have `programs.ssh.setXAuthLocation` set, just `forwardX11` for ssh and openssh.

**Comment by pschuprikov** [comment]
I stumbled into this problem today. 

After looking through the code my first thought was that this [line](https://github.com/NixOS/nixpkgs/blob/f3c32cb2c1344c9a831bb9e4f47c1b20527dbe0b/nixos/modules/services/networking/ssh/sshd.nix#L230) explains the behavior we see. Since `openssh.forwardX11` appears to be an ultimate variable that influences `programs.ssh.setXAuthLocation`. Everything else has lower priority. 

But then I looked at this [line](https://github.com/NixOS/nixpkgs/blob/f3c32cb2c1344c9a831bb9e4f47c1b20527dbe0b/nixos/modules/services/networking/ssh/sshd.nix#L88). And now  it started to look like an infinite recursion of some sort, that results to `false`.

**Comment by pschuprikov** [comment]
I was wrong, I looked at the wrong revision. The last line should be [this](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/ssh/sshd.nix#L88) one. Now everything is clear.

**Comment by reinhardt** [comment]
So does that explain why setting setXAuthLocation alone still gets me the error?

**Comment by pschuprikov** [comment]
Yes, as mentioned in [nixos manual](https://nixos.org/nixos/manual/) default option definition (like if you add `services.ssh.setXAuthLocation = true`) has priority 1000, while mkForce has priority 50 (lower takes precedence).

**Comment by reinhardt** [comment]
Ah, I see, thanks!

So I'm assuming there was some change to all this that broke my config. Since I know what to do now I'm OK with not digging any deeper and closing this.

Thank you everyone!

**Comment by CharlesHD** [comment]
In my opinion this is still a bogus behavior.
`programs.ssh.forwardX11` should request X11 forwarding by default for outgoing connections.
`service.openssh.forwardX11` should allow X11 forwarding for incoming connections. 
`programs.ssh.setXAuthLocation` should set XAuthLocation. That's something you may want independently of the other two. (but the first two should implie setXAuthLocation to true).

**Comment by reinhardt** [comment]
I agree. While it works as it is, it's not very intuitive or transparent.

**Comment by ryantrinkle** [comment]
One thing I just noticed here (running on 18.09.git.5e425e2) is that I had to manually `sudo systemctl restart sshd.service` after configuring these settings - it did not happen automatically.
