### ISSUE TITLE
Add polkit.packages

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#19256]
## Issue description

Currently one must add a package that provides a polkit policy file to `environment.systemPackages`. This also adds any other directory the package has to the system path.

Alternatively we can do something like we do for systemd and dbus:
Add an option `polkit.packages` and add packages that provide policy files there.

I'd like to get thoughts on this before I implement anything.

polkit maintainer, @urkud seems inactive?

not sure whom to cc....

**Comment by abbradar** [comment]
This is good time for incompatible changes, and I think this is a good one. I'm not sure about how much users intentionally add something to `environment.systemPackages` to get it in polkit. It seems to me that it's mostly done by us (modules from DMs etc.) so the amount of breakage won't be so bad.

This should be mentioned in release notes if implemented.

**Comment by Profpatsch** [comment]
(triage) what’s the status?
