### ISSUE TITLE
The pythonFull vs. python distinction causes (me) a lot of pain

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#19255]
Most recently https://github.com/NixOS/nixpkgs/issues/19225 and #17607.

As an example, let's say I'm running a python project that requires `dbm`, and it produces an executable script as part of its build process. If I refer to it by `${pythonPackages.mypackage}bin/myscript`, I get an error that `dbm` isn't available (no mention of `pythonFull` in the error). After that, it's not at all obvious to me how to replace the python that gets hardcoded into the shebang with `pythonFull`, and this is after I poke around the nix files for a while. Also, due to the wrapper script, it's not easy at all to explicitly run the script by running `pythonFull` against `which myscript`, because it's not a python script.

In the end I ended up biting the bullet and making myself a `pythonFullPackages` (by copying and pasting what we do for the other python package flavors and passing in `pythonFull`) and then using `buildPythonPackage` from there to build the package with `myscript` in it.

Ultimately though, I wouldn't expect any newcomer to Nix to have any clue what to here, or even how they'd figure out why `dbm`, which is generally shipped with python, doesn't import in the first place.

Where I'm going with this is that I think it'd pay to either re-evaluate having any distinction between `python` and `pythonFull`, or if that's still warranted (presumably by a huge closure size difference), to at least change the mechanism by which it happens to be less obscure.

cc @garbas @domenkozar

**Comment by FRidh** [comment]
Yep, its annoying. Its understandable why we have both, and it should be easier to have packages using `pythonFull`. I have a PR around here where I introduced package sets for that as well. Due to how these extra modules are implemented it wouldn't take any extra time to build these package sets.

Anyway, because there's already a couple of issues on this topic (have a look at the placeholder issue which I keep up to date https://github.com/NixOS/nixpkgs/issues/1819) , I would like to close this one.

---

> If I refer to it by ${pythonPackages.mypackage}bin/myscript, I get an error that dbm isn't available (no mention of pythonFull in the error). After that, it's not at all obvious to me how to replace the python that gets hardcoded into the shebang with pythonFull, and this is after I poke around the nix files for a while. Also, due to the wrapper script, it's not easy at all to explicitly run the script by running pythonFull against which myscript, because it's not a python script.

This is a different issue, and is about how we use wrappers on Nix. We shouldn't explicitly construct wrappers in phases like we do now, but instead describe what kind of paths should be set. Then, whenever an environment is constructed, the wrappers are build. For this reason I want to get rid of building wrappers in `buildPythonPackage`/`mkPythonDerivation` and always use `python.buildEnv`. But that also means running the tests in a separate env, etc.

> Ultimately though, I wouldn't expect any newcomer to Nix to have any clue what to here, or even how they'd figure out why dbm, which is generally shipped with python, doesn't import in the first place.

at which point they either ask someone what's going on, or check the Nixpkgs manual which describes this issue. Okay, its not easy to find, but its there.

**Comment by garbas** [comment]
@copumpkin i don't use ``pythonPackages`` anymore and moved my python work outside nixpkgs. i think @FRidh is currently working on them.

**Comment by edolstra** [comment]
Yeah, it would be nice to get rid of `pythonFull`. The use of multiple outputs in most of the dependencies already makes it less painful to have those dependencies, e.g. `readline` support no longer increases the Python closure that much. So the need for the `python` / `pythonFull` distinction is less than it used to be.

However, the big remaining problem is the TCL/TK dependency, which does increase the closure size a lot. One solution would be to move the TCL/TK Python bindings to a separate output (e.g. `python.tcltk`), so TCL/TK would be a build-time dependency of every Python user but not necessarily a runtime dependency.

**Comment by domenkozar** [comment]
Just to backk @edolstra words:

```
$ du -sh $(nix-store -qR /nix/store/fkpz8hm6zpmkgxpk20pn1pf3kgkials8-python3-3.5.2/)
22M     /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24
576K    /nix/store/1ina447a9m6b4h53l7rjh4hbdnk4rsi5-gdbm-1.12
32K     /nix/store/9z7phjyp9qjk0hnbl1bzwxvnwgrjsw5v-libXau-1.0.8
40K     /nix/store/pk7kb4lz8albgx1i723id6xpn1061ppf-libXdmcp-1.1.2
1.6M    /nix/store/29ni6dkyc46z73cla82431pg8pran369-libxcb-1.12
952K    /nix/store/29q2gn7qdf5wwd4lrllh53gqjg0gfx3l-sqlite-3.14.1
84K     /nix/store/2rhp2bz6k3p1v5iia6myjlfzakignkky-bzip2-1.0.6.0.1
828K    /nix/store/migghb7advw9a6hxi3vhyw2kyyxlyihx-bash-4.3-p46
7.2M    /nix/store/4f8h76kqrak8rlxnbxfsrhwybhcmb5m8-tcl-8.6.6
12M     /nix/store/4qc6mqycx15syj9zqgk7ibimrg4yh09x-ncurses-6.0
104K    /nix/store/wz7l2zqdsa78jxnzkigv5gy2c7hxnbxh-zlib-1.2.8
256K    /nix/store/r8s92n0xdkry2s8a4jglr3l2mfsydh5n-libpng-apng-1.6.23
880K    /nix/store/6zw5zxss5mmfdhyi686wfay9a613jk46-freetype-2.6.5
196K    /nix/store/pl19g0g47kkgvy0ck6xnkw6h5ilyvbgp-expat-2.2.0
740K    /nix/store/wph1j0wcrkkwrm778vc97qbl1fhy3n6i-dejavu-fonts-2.37-minimal
300K    /nix/store/fm282pmyyy4hqygidad6k0ra4545yrhd-fontconfig-2.11.1-lib
3.2M    /nix/store/g304iqfg2bdwwdgfq0xznr7fbfwhhsfq-libX11-1.6.3
60K     /nix/store/h8rfy5l5rwlzbkwiqzjn1wz0yh89i03l-libXrender-0.9.9
120K    /nix/store/i8lmlx73d8ygk4s6ahjj02ahh6440yzq-libXft-2.3.2
3.4M    /nix/store/64w64hli0f23vlg3r7kv1dy2hkpysc6a-tk-8.6.6
100K    /nix/store/6sp63j6m6vyspqm2d7zw15ipiym70kzc-attr-2.4.47
344K    /nix/store/8jwqlpyxp5c2rl5g7yspdfbh58dsciwx-xz-5.2.2
140K    /nix/store/ci7bn61pfds1y1ijkf3c85il0jdp87ar-acl-2.2.52
11M     /nix/store/8rn45r9ndfq5h7mx58r35p2szky5ja6n-coreutils-8.25
3.4M    /nix/store/clp627rkaqz8pn0h658vmsx32j5s3srq-openssl-1.0.2j
400K    /nix/store/hrj2ic7v3dmd947arxr52wn9a5g1kxv5-readline-6.3p08
72M     /nix/store/fkpz8hm6zpmkgxpk20pn1pf3kgkials8-python3-3.5.2
```

**Comment by FRidh** [comment]
I just made an attempt with adding an extra output and copying the tkinter files into it. However, the closure size of the main output was hardly affected by it. If I however build without tk/X11 support by removing the inputs, the size is much smaller. This leads me to think there are other references to the libraries, outside of the files I copied. Do you have any suggestions in how to find those references?

**Comment by vcunat** [comment]
@FRidh: I simply use `grep thebighash -R ./result/`.

**Comment by FRidh** [comment]
Thanks @vcunat 

So putting `tkinter` in a separate output gives
```
$ du -sch $(nix-store -qR $(nix-build -A python35))
23M     /nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24
952K    /nix/store/4kmvzlc587bmx6lbfqy171pim5za36az-sqlite-3.14.1
172K    /nix/store/scblgh0h3sh65s0rp0nv79rr82mjd6cm-attr-2.4.47
200K    /nix/store/6h29qi09p6p4kh04n3pyg7wa0sn7gryv-acl-2.2.52
7.5M    /nix/store/m4fscyf6j97wh5yfi6gww86x79jsw321-ncurses-6.0
396K    /nix/store/9a3x1y7pbsj98yn7rgan0341wkpfjngw-readline-6.3p08
84K     /nix/store/9jplq6zqlfixn2drgq07jgvcabjrmn47-bzip2-1.0.6.0.1
104K    /nix/store/b5mwbrx8cldkchiqgwgkaagw91xfjr89-zlib-1.2.8
3.4M    /nix/store/cax4kw158vdgx5wz9j0chhh7aszsjq2h-openssl-1.0.2j
832K    /nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46
676K    /nix/store/vxp1gknlmmhb6ham6zgi1b2dm3cy9ydx-gdbm-1.12
400K    /nix/store/zgdgh3bhiqnxdfpsh9wsq2ci7f47xmp4-xz-5.2.2
11M     /nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25
71M     /nix/store/hd20aks7791aa655ksnsk2wp19zpilk8-python3-3.5.2
118M    total
```

instead of

```
$ du -sch $(nix-store -qR $(nix-build -A python35))
23M     /nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24
84K     /nix/store/9jplq6zqlfixn2drgq07jgvcabjrmn47-bzip2-1.0.6.0.1
104K    /nix/store/b5mwbrx8cldkchiqgwgkaagw91xfjr89-zlib-1.2.8
248K    /nix/store/rapy57vhj8fckrh7wbpm5fzlls62k6yq-libpng-apng-1.6.23
892K    /nix/store/07fdvyiml8hayl2xs1f7vldn8nlh2gkb-freetype-2.6.5
32K     /nix/store/1v5pbv6wigbs6mqwafnz836rbc278yi6-libXau-1.0.8
756K    /nix/store/3yxc0r7ms1br2z9kb9vxcb1r50h0fdrx-dejavu-fonts-2.37-minimal
952K    /nix/store/4kmvzlc587bmx6lbfqy171pim5za36az-sqlite-3.14.1
40K     /nix/store/ha1awfhfl8107qgj77g4clc040668f93-libXdmcp-1.1.2
1.4M    /nix/store/g34vm9agkdr96cm4i1iisg6n5f9i7f6h-libxcb-1.12
3.5M    /nix/store/jhc9wckygk0a0mcfzia7xc9lgd5y69mn-libX11-1.6.3
60K     /nix/store/5ad8vggvqmx0d1rhchwa276jdi5m3sxs-libXrender-0.9.9
172K    /nix/store/scblgh0h3sh65s0rp0nv79rr82mjd6cm-attr-2.4.47
200K    /nix/store/6h29qi09p6p4kh04n3pyg7wa0sn7gryv-acl-2.2.52
7.5M    /nix/store/m4fscyf6j97wh5yfi6gww86x79jsw321-ncurses-6.0
396K    /nix/store/9a3x1y7pbsj98yn7rgan0341wkpfjngw-readline-6.3p08
3.4M    /nix/store/cax4kw158vdgx5wz9j0chhh7aszsjq2h-openssl-1.0.2j
196K    /nix/store/nq9bc7x8r8xh40yprwdrkbxhmigazwz0-expat-2.2.0
300K    /nix/store/i8i2j0i2y8d158kma8lzh8wk8m9idp96-fontconfig-2.11.1-lib
120K    /nix/store/gymfw5r2kmq05n9ydyg46qsqmh9n7ri8-libXft-2.3.2
832K    /nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46
7.3M    /nix/store/x1rpiq9h8wpnga0s8vsmdhzvai5a3x30-tcl-8.6.6
3.4M    /nix/store/irlshka7bbsp5gnmvjsrx7gh9a277mvj-tk-8.6.6
676K    /nix/store/vxp1gknlmmhb6ham6zgi1b2dm3cy9ydx-gdbm-1.12
400K    /nix/store/zgdgh3bhiqnxdfpsh9wsq2ci7f47xmp4-xz-5.2.2
11M     /nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25
73M     /nix/store/8wshs9znf0kkwbyj4fvdy69ssadm3vmq-python3-3.5.2
138M    total
```

That's a saving of 20 MB, but still 30 MB more than Python 2.7.

If we're happy with this solution I'll make the changes to the other interpreter versions and docs as well.

**Comment by vcunat** [comment]
Also `ncurses` might be worth it, but the rest seems OK to me, as it's all either small or typically present even on a headless server.

**Comment by FRidh** [comment]
`libX11` indirectly depends on Python 2.7 and so we get a circular dependency. If I am correct it is only a build-time dependency, so I suggest keeping a `x11Support` parameter as well.

**Comment by FRidh** [comment]
A disadvantage of using multiple outputs is also that `nix-shell -p python3 python3.tkinter` won't give `tkinter` on `PYTHONPATH`. If we instead build `tkinter` like we do other modules (or use the approach done with 2.7) that should be possible.

**Comment by FRidh** [comment]
That issue is now solved in https://github.com/NixOS/nixpkgs/pull/19307. `tkinter` works both with `nix-shell` and `buildEnv`.

**Comment by FRidh** [comment]
[This issue](https://github.com/NixOS/nixpkgs/issues/492)  will remain if we split the Python package (although now with tkinter instead of sqlite).

**Comment by FlorentBecker** [comment]
shouldn't we rename python to pythonMinimal and pythonFull to python?

**Comment by FRidh** [comment]
Please review https://github.com/NixOS/nixpkgs/pull/19309.

**Comment by FRidh** [comment]
#19309 has been merged so I am closing this.
