### ISSUE TITLE
users.user."user".openssh.authorizedKeys.keys doesnt have expected behaviour

### ISSUE THREAD

**Issue by Baitinq** [NixOS/nixpkgs#192598]
### Describe the bug
Adding a public key fingerprint to users.user."user".openssh.authorizedKeys.keys creates the /etc/ssh/authorized_keys.d/user file but is not read/works by the sshd daemon.

It does work if I use the traditional method of creating a ~/.ssh/authorized_keys file including the public key manually.

Maybe Im missunderstanding how this options should work?

### Steps To Reproduce
1. Add your ssh public key's fingerprint to the users.user."user".openssh.authorizedKeys.keys  array
2. Rebuild
3. Try to login to your machine with ssh
4. Fail (denied publickey)

### Expected behavior
SSH public key login works

### Additional context
- NixOS unstable
- Using a gpg-agent "generated" ssh key

### Notify maintainers
@edolstra  ?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.19.10-zen1, NixOS, 22.11 (Raccoon), 22.11.20220921.d6490a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by misuzu** [comment]
I've never had any issues with this option. Maybe you're using some kind of custom sshd configuration? Check if your `/etc/ssh/sshd_config` has `AuthorizedKeysFile %h/.ssh/authorized_keys %h/.ssh/authorized_keys2 /etc/ssh/authorized_keys.d/%u`.

**Comment by Baitinq** [comment]
@misuzu Im using home-manager for my ssh client configuration, but that shouldnt have anything to do with the server right?

This is my sshd_config content:
```
UsePAM yes

Banner none

AddressFamily any
Port 22


ListenAddress 0.0.0.0:2222


XAuthLocation /nix/store/xkrlfvm3fd3nn5np8j54z1d6rfgrcb12-xauth-1.1/bin/xauth


X11Forwarding no

Subsystem sftp /nix/store/6761i1m2w357mxx3p78h532w98lw989f-openssh-9.0p1/libexec/sftp-server


PermitRootLogin prohibit-password
GatewayPorts no
PasswordAuthentication yes
KbdInteractiveAuthentication yes

PrintMotd no # handled by pam_motd

AuthorizedKeysFile %h/.ssh/authorized_keys %h/.ssh/authorized_keys2 /etc/ssh/authorized_keys.d/%u


HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key


KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

LogLevel INFO

UseDNS no
```

An this are the ssh relevant parts of my config:
```
services.openssh = {
      enable = true;
      passwordAuthentication = true;
      kbdInteractiveAuthentication = true;
      listenAddresses = [{
        addr = "0.0.0.0";
        port = 2222;
      }];
    };

 programs.ssh = {
      enableAskPassword = false;
      forwardX11 = true;
    };
```

**Comment by rapenne-s** [comment]
Can you look at sshd.service logs to see if there is an error when you try to login with a key?

This option works for everyone AFAIK.

**Comment by Baitinq** [comment]
> sshd.service

Hi @rapenne-s , thank you for your help, it seems like the problem was:

```
Authentication refused: bad ownership or modes for directory /
```

Ive checked for how to fix this error and run the following commands:
```
chmod go-w /home/user
chmod 700 /home/user/.ssh
```

But it seems like that hasnt resolved the issue. Does this have anything to do with nix's store permissions?

**Comment by Baitinq** [comment]
SOLUTION:

Turns out I had to add this to the hardware configuration as to fix tmpfs / permissions:

```
fileSystems."/".options = [ "defaults" "mode=755" ];
```
