### ISSUE TITLE
After upgrading to 16.09, cannot log in with GNOME 3.

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#19269]
## Issue description

After upgrading NixOS to 16.09, trying to log in with GNOME 3 does not work: the screen is changing a few times and i am put back to the login prompt (`lightdm`).

I can still log in from console or with Xmonad.
### Steps to reproduce

Try to log in with GNOME 3 desktop.
## Technical details
- NixOS: `16.09.680.4e14fd5 (Flounder)`.
- Nix version: `1.11.4`.
- Nixpkgs version: `16.09.680.4e14fd5`.

**Comment by groxxda** [comment]
Please post the output of journalctl? (`journalctl -xb`)

**Comment by alexeymuranov** [comment]
Here: https://gist.github.com/alexeymuranov/76fcd6de31821b35f75e917ac5a3a696

**Comment by groxxda** [comment]
```
Oct 05 21:50:47 nixos xsession[1159]: /nix/store/lyvi4r0v8jhv2n5qdcgrhrqrb74yqkpg-xsession: Window manager 'gnome3' not found.
```

Can you post the relevant part from your `configuration.nix`? (services.xserver.*)

**Comment by alexeymuranov** [comment]
```nix
{
  services.xserver.enable = true;
  services.xserver.layout = "us";
  services.xserver.xkbOptions = "eurosign:e";
  services.xserver.videoDrivers = [ "intel" "nouveau" ];

  services.xserver.windowManager.xmonad.enable = true;
  services.xserver.windowManager.xmonad.enableContribAndExtras = true;

  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;

  services.xserver.multitouch.enable = true;
}
```

**Comment by alexeymuranov** [comment]
I have just discovered that i can log in as my second user, the one i could not log in in #19164 before switching back an forth between `gdm` and `lightdm`.  As i said, i am using `lightdm` now.  Weird.  I will try to investigate when i have time.

**Comment by groxxda** [comment]
As I mentioned in the other issue, there are probably incompatibilities if you use only one part of gnome.

I don't know what should happen if you set desktopManager to gnome3 and windowManager to xmonad. 
To be honest I don't even know what setting a desktopManager should do in general.

But judging from the error I extracted last time from your log and a quick glance at the code there seems to be a problem somewhere around https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/display-managers/default.nix#L112-L135

Setting `services.xserver.desktopManager.gnome3.enable = true;` should create a session with `manage = desktop` and setting `  services.xserver.windowManager.xmonad.enable = true;` should create a session with `manage = window`.

You should try to debug why that script thinks you want to use windowManager=gnome3. Maybe `cfg.windowManager.default` is somehow overwritten by the gnome desktopManager module or anything like that.

Can you check `nixos-option services.xserver.windowManager`, in particular `nixos-option services.xserver.windowManager.default`

**Comment by alexeymuranov** [comment]
Well, if i check `nixos-option services.xserver.windowManager.default` as a root from a console, i get `Value: "none"`, etc.

**Comment by alexeymuranov** [comment]
I tried removing from my home directory all GNOME-related subdirectories i could find, but this did not fix the problem.  I start suspecting that this could indeed be NixOS-specific, maybe related to user-installed packages...

**Comment by alexeymuranov** [comment]
I have fixed it!  The problem was caused by `gnome-session-3.18.1.2` package that i had installed for the broken account (i do not even remember installing it or what it was for).  Upgrading NixOS from 16.03 to 16.09 upgraded `gnome-shell` from 3.18.3 to 3.20.3.  Apparently the version of `gnome-session` became incompatible.  It was enough to remove `gnome-session-3.18.1.2`.

Please feel free to close this issue if you do not consider it Nix related.

**Comment by vcunat** [comment]
Hmm, it *would* be nicer if gnome wasn't broken by installing additional stuff, but it seems there's far too little manpower here to deal with such "nitpicks".
