### ISSUE TITLE
Emacs with withPgtk does not have GUI

### ISSUE THREAD

**Issue by accelbread** [NixOS/nixpkgs#192692]
### Describe the bug
When built with `withPgtk = true;`, emacs does not use the pgtk GUI. When launched from a terminal, Emacs launches in TUI instead of with the pgtk GUI. Launching emacs from the application drawer fails.

### Steps To Reproduce
1. Install `pkgs.emacs.override{ withPgtk = true; };`  using  emacs package from nixos-unstable
2. Launch emacs

### Expected behavior
Emacs should launch in GUI mode with pgtk.

### Additional context

I tried building with withX enabled as well but this causes nixios-rebuild to error with `assert withPgtk -> withGTK3 && !withX && gtk3 != null;`

### Notify maintainers

@lovek323 @jwiegley @adisbladis 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.14-zen1, NixOS, 22.05 (Quokka), 22.05.20220921.9bdbbaa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by adisbladis** [comment]
pgtk is not in a stable release yet. this option exists for the overlay packages.
you will have to wait for release 29.
