### ISSUE TITLE
Packaging request: Apache Druid

### ISSUE THREAD

**Issue by Uthar** [NixOS/nixpkgs#192752]
**Project description**
Apache Druid is a real-time database to power modern analytics applications.

**Metadata**

* homepage URL: https://druid.apache.org/
* source URL: https://github.com/apache/druid
* license: Apache-2.0
* platforms: unix

**Comment by vsharathchandra** [comment]
https://github.com/NixOS/nixpkgs/pull/219942

I have an open PR for druid package and module.  
I have been using this in production.  
You can use overlays to use this along with any version of nixpkgs.

**Comment by thtrf** [comment]
#219942 has been closed
