### ISSUE TITLE
`evscript` is not installed with setuid

### ISSUE THREAD

**Issue by TheBlackBeans** [NixOS/nixpkgs#192756]
### Describe the bug
evscript is not installed with setuid, so one is forced to either launch it with sudo or su, or to allow the user to access `/dev/input/event*`.

### Steps To Reproduce
1. Install `evscript` with `nixos-rebuild switch` or alike.
2. Launch `evscript -d /dev/input/event1`. This will crash with `evdev open(): Sys(EACCES)`.
3. Launch `sudo evscript -d /dev/input/event1`. It works (and hangs).

### Expected behavior
`evscript -d /dev/input/event1` should work as the `sudo` version. According to the [README](https://github.com/unrelentingtech/evscript), you need to install the binary with the appropriate rights.

Indeed, the following works
```console
$ sudo install -Ss -o root -m 4755 `which evscript` here
$ ./here -d /dev/input/event1
```

### Notify maintainers
@MilesBreslin 

### Metadata
```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.11 (Raccoon), 22.11.20220918.f677051`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.05pre338578.a2e281f5770"`
 - channels(user): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
$
```

**Comment by MilesBreslin** [comment]
Closing because I cannot fix. This is a limitation of the nix store. To get the setuid bits on NixOS, use `security.wrappers` to install. I personally workaround this issue by running as a systemd service under the root user. See #99101 as an example of a similar issue.
