### ISSUE TITLE
texlive.combined.scheme-basic: ordering nondeterminism

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#192736]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

### Steps To Reproduce

    nix-build '<nixpkgs>' -A texlive.combined.scheme-basic --check --keep-failed

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

    nix-store --read-log $(nix-instantiate '<nixpkgs>' -A texlive.combined.scheme-basic)

### Additional context

Tested on nixpkgs e8a0af93710b18a99c9450301ea47403c3ebb238

Notably the ordering of the words in `share/texmf-var/web2c/luahbtex/luahbtex.fmt` and similar seem nondeterministic, perhaps the other differences are effects of that.

https://arnout.engelen.eu/nixos-iso-minimal-r13y/diff/5ebd412485037603adc516ecc963ae9813f03df52103e169e1ecc869af646b3b-bec50a8273cff095f79a0563d1b744dd83c15b3a0e384b2871a268e2545ff9a1.html

**Comment by wamserma** [comment]
That is an issue with [`fmtutil]`(https://github.com/TeX-Live/texlive-source/blob/ee52d1cdef61c4a97029a79588526b0a8553b257/texk/texlive/linked_scripts/texlive/fmtutil.pl#L683), respectively the tools called by `fmtutil`, so it should be solved upstream.

**Comment by raboof** [comment]
Do you know where fmtutil is coming from in the build for `texlive.combined.scheme-basic`? I thought it would be from https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/texlive/bin.nix#L21 , but I replaced it and that didn't have any effect.

**Comment by wamserma** [comment]
I think this is already [discussed on the mailinglist](https://mailman.ntg.nl/pipermail/dev-luatex/2022-May/006669.html) referring to [a patch posted on the list](https://mailman.ntg.nl/pipermail/dev-luatex/2022-April/006659.html).

**Comment by raboof** [comment]
> I think this is already [discussed on the mailinglist](https://mailman.ntg.nl/pipermail/dev-luatex/2022-May/006669.html) referring to [a patch posted on the list](https://mailman.ntg.nl/pipermail/dev-luatex/2022-April/006659.html).

Huh! Indeed that covers the same issue - I did search before digging into this problem, but not good enough apparently :laughing: .
