### ISSUE TITLE
python3Packages.bootstrapped-pip: unreproducible vendored pyc

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#192728]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

### Steps To Reproduce

    nix-build '<nixpkgs>' -A python3Packages.bootstrapped-pip --check --keep-failed

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

    nix-store --read-log $(nix-instantiate '<nixpkgs>' -A python3Packages.bootstrapped-pip)

### Additional context

Tested on e8a0af93710b18a99c9450301ea47403c3ebb238

https://arnout.engelen.eu/nixos-iso-minimal-r13y-bak2/diff/4a36df4e811067c93892ce2a9180e0d03fbf8fce0dee5cbf673c572c46fb945c-e92d419c5d63d62173b44c10301dcfc7dce60e1d5c63eee57231ee92c20e62e9.html

All single-character differences, swapping `d` and `f`.

I cannot reproduce the problem with `python311Packages.bootstrapped-pip`, so perhaps (like with #188978) we should simply wait until Python 3.11 is released and use that instead.

**Comment by raboof** [comment]
A later run (https://arnout.engelen.eu/nixos-iso-minimal-r13y/diff/7078cc35d0a86b63420310121b8c13b99f6e1503c51b8d9c0ea51056eb9995cb-d186e65f389bce4c0e33a539908207833d76b2b392e86165d2c7ec2cc44417d8.html) also has a different timestamp and checksum for vendored .exe files

**Comment by aij** [comment]
[Python 3.11](https://www.python.org/downloads/release/python-3110/) was released Oct. 24, 2022 but it looks like we're still using 3.10 as the default  `python3`.

**Comment by raboof** [comment]
> [Python 3.11](https://www.python.org/downloads/release/python-3110/) was released Oct. 24, 2022 but it looks like we're still using 3.10 as the default `python3`.

Correct, following the update schedule (https://nixos.org/manual/nixpkgs/unstable/#python-cpython-update-schedule) we can expect the update 'real soon now' :)

**Comment by mweinelt** [comment]
Closed via #263294.
