### ISSUE TITLE
pkgs.openscad: cannot export to PDF

### ISSUE THREAD

**Issue by pacien** [NixOS/nixpkgs#192895]
## Issue description

OpenSCAD seems to be built without support for PDF exports.

(This is a very useful feature to print projections on paper to check the
dimensions of a design for example).

Version: OpenSCAD version 2021.01
On nixpkgs: master (2022-09-18)

## Steps to reproduce

- Open OpenSCAD
- Go to File -> Export -> Export as PDF…
- Save to some file
- Observe the following error in the OpenSCAD console:
  > ERROR: Export to PDF format was not enabled when building the application. 

---

CC package maintainers: @bjornfor @7c6f434c @gebner

**Comment by 7c6f434c** [comment]
Any idea what dependency they need for PDF?

(image file export has been enough for me so I never looked)

**Comment by bjornfor** [comment]
I think cairo. (I was looking into this earlier today.)

**Comment by bjornfor** [comment]
Yes, cairo was missing: https://github.com/NixOS/nixpkgs/pull/192916
