### ISSUE TITLE
Mathematica: repeatedly having to add `Mathematica_13.1.0_BNDL_LINUX.sh` to nix store is annoying

### ISSUE THREAD

**Issue by auroraanna** [NixOS/nixpkgs#192886]
### Describe the problem
I often have to add the `Mathematica_13.1.0_BNDL_LINUX.sh` file to the nix store with `nix-store --add-fixed sha256 ~/mathematica/Mathematica_13.1.0_BNDL_LINUX.sh`. Somehow it gets removed so that I have to add it again.

### Steps To Reproduce
1. Add the shell script to nix store
2. Install mathematica
3. Wait?
4. Have to add the shell script again.
5. Rebuild your NixOS or Home Manager config

### Expected behavior
Not having to repeatedly add the shell script to the nix store.

### Additional context
```
error: builder for '/nix/store/pi5d4a2kr7f0lmbkdaz18cgbaxs9nflb-Mathematica_13.1.0_BNDL_LINUX.sh.drv' failed with exit code 1;
       last 8 log lines:
       >
       > ***
       > This nix expression requires that Mathematica_13.1.0_BNDL_LINUX.sh is
       > already part of the store. Find the file on your Mathematica CD
       > and add it to the nix store with nix-store --add-fixed sha256 <FILE>.
       >
       > ***
       >
       For full logs, run 'nix log /nix/store/pi5d4a2kr7f0lmbkdaz18cgbaxs9nflb-Mathematica_13.1.0_BNDL_LINUX.sh.drv'.

```

### Notify maintainers

@herberteuler 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the 
result.

```console
[annaaurora@LenOwO:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.11 (Raccoon), 22.11.20220918.f677051`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Patryk27** [comment]
You're probably running `nix-collect-garbage` or have [auto garbage-collecting](https://nixos.wiki/wiki/Storage_optimization) set up - those remove any manually-added files, since `nix-store --add-fixed` (or, equivalently, `nix store add-path`) don't register the files as garbage-collection roots.

Instead of running `nix-store --add-fixed`, I'd try referencing the file somehow in your `flake.nix` / `configuration.nix` - a _very_ rough idea could be:
```
environment.variables.MATHEMATICA = ./path-to-your-mathematica;
```
This will prevent the Nix's garbage collector from removing Mathematica's installer, since it will see that it's referenced somewhere.

Arguably, it's a hack, so maybe there's a better way.

**Comment by herberteuler** [comment]
Yes, my guess is garbage collection too. Installing Mathematica takes a long time, and I have done many re-installations without adding the script.

Another way to avoid constantly adding the script is to use `nix-env -i` to install Mathematica. This "pins" Mathematica to a specific revision, but I think this is acceptable given that Mathematica itself only receives a new release every year or so.

**Comment by tpwrules** [comment]
I think that solution with `nix-env -i` would still require a rebuild when your channels updated and a dependency changed.

Another way would be to directly call `nix-build` on the derivation to create a symlink somewhere you won't disturb it. Like `nix-build /nix/store/pi5d4a2kr7f0lmbkdaz18cgbaxs9nflb-Mathematica_13.1.0_BNDL_LINUX.sh.drv -o ~/files/installers/mathematica-link`. Then the GC will see that root and avoid deleting it.

I've thought before about the utility of making these sorts of things runtime dependencies so they are always kept around but that's a lot of baggage in some cases (I use software which has a 74GB installer I have to add to the store, it's so big `nix-store --add-fixed` doesn't even work) and there are workarounds for people who really want it. I wonder if instructions on the above could be added to the default `requireFile` prompt.

**Comment by herberteuler** [comment]
> I think that solution with `nix-env -i` would still require a rebuild when your channels updated and a dependency changed.

IIRC packages installed through `nix-env -i` don't get updated with `nixos-rebuild` but with `nix-env -u` instead, and their channels are typically separated (system vs. per-user). But yeah, this does not solve the problem, it just reduces its frequency to as low as such that it is not annoying, I think.

**Comment by auroraanna** [comment]
@Patryk27 Well, I have no idea how to get Home Manager to use that path instead of requiring it in the nix store.

**Comment by Patryk27** [comment]
@auroraanna if referencing the path in `environment.variables` is not enough for Nix to consider it present (maybe evaluation order here matters?), then I think you can invoke `nix-store --add-fixed` just once and then rebuild your system with that `environment.variables` hack on - this should prevent Nix from garbage-collecting that installer in the future.

**Comment by auroraanna** [comment]
@Patryk27 You mean the environment variable `MATHEMATICA` makes nix use the path from that variable?

**Comment by auroraanna** [comment]
> @auroraanna if referencing the path in `environment.variables` is not enough for Nix to consider it present (maybe evaluation order here matters?), then I think you can invoke `nix-store --add-fixed` just once and then rebuild your system with that `environment.variables` hack on - this should prevent Nix from garbage-collecting that installer in the future.

But why would it not garbage collect the file anymore? How does nix know that that environment variable is the path to the file?

**Comment by Patryk27** [comment]
> But why would it not garbage collect the file anymore? 

For the same reason it won't remove `./my-script` from `/nix/store` if you do:

```
let
  my-script-wrapper = pkgs.writeShellScriptBin "my-script-wrapper" ''
    ${./my-script} --something 
  '';
  
in
{
  environment.systemPackages = [ my-script-wrapper ];
}
```

That is to say: if some file is referenced inside the Nix expression used to build your system, Nix will know about it and keep track (using mechanisms such as [string contexts](https://shealevy.com/blog/2018/08/05/understanding-nixs-string-context/)).

Otherwise e.g. installing a game and doing `nix-collect-garbage` would remove all of that game's assets from `/nix/store`, which is not what anybody wants 🙂

**Comment by SuperSandro2000** [comment]
You want to set ``keep-outputs`` in ``nix.conf`` to true.
