### ISSUE TITLE
How to add a user to the sudoers

### ISSUE THREAD

**Issue by usuha** [NixOS/nixpkgs#19283]
Hello.
I'm using "NixOS KDE 16.09".
I have created a user, but I am in trouble I do not know the way that I want to add to the sudoers.
Please professor how to add a user to sudoers.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by tohl** [comment]
add the user to the wheel group.

**Comment by Zimmi48** [comment]
@usuha You should not ask such questions on the issue tracker. Questions are for sites like http://unix.stackexchange.com/ or the IRC channel. The issue tracker is essentially for bugs.

**Comment by usuha** [comment]
Thanks a lot tohl.
Thanks a lot Zimmi48.
Many thanks.

**Comment by grahamc** [comment]
We have an example of adding a user to sudoers here: https://nixos.org/nixos/manual/#sec-user-management see that their extraGroups includes "wheel".

**Comment by globin** [comment]
Closing as this seems to have all necessary information :)

**Comment by AMDphreak** [comment]
Adding a "wheel" group in the user declaration failed to create the "wheel" group during `nixos-rebuild build`.
