### ISSUE TITLE
How to display the Thunderbird on the menu

### ISSUE THREAD

**Issue by usuha** [NixOS/nixpkgs#19295]
Hello.
I'm using "NixOS KDE 16.09".
I installed Thunderbird, but it does not appear in the menu.
Please professor how to display the Thunderbird on the menu.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by jgeerds** [comment]
Can someone confirm this? It seems to work for me with Gnome.

**Comment by usuha** [comment]
Thanks a lot jgeerds.
This thread has appeared at the end.

**Comment by grahamc** [comment]
@usuha Does thunderbird appear in the menu? If you open a console or terminal and run thunderbird-bin or maybe it is just called thunderbird, does it run? Does it then show up in the menu?

**Comment by usuha** [comment]
Thanks a lot grahamc.
Many thanks.

**Comment by usuha** [comment]
This problem was solved thanks to everyone.
Thank you very much.

**Comment by Zimmi48** [comment]
Apparently this is solved: http://unix.stackexchange.com/questions/314697/how-to-display-the-thunderbird-on-the-menu#comment553612_314697

**Comment by carldong** [comment]
I have this problem, where Thunderbird does not show up in KDE 5 menu, but I can run it from terminal/Alt-F2 as normal.

System info:

```
$ nixos-version                                                                                                                                                                      
16.09.1599.5fff5a9 (Flounder)                                                                                                                                                                              
                                                                                                                                                                                                           
$ nix-env --version                                                                                                                                                                  
nix-env (Nix) 1.11.6                                                                                                                                                                                       
                                                                                                                                                                                                           
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.1599.5fff5a9"   
```

**Comment by carldong** [comment]
Actually there are quite  a lot of packages that have this problem. More accurately, most packages don't work well with the KDE menu in NixOS.
