### ISSUE TITLE
scribus scripts cannot find Tkinter

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#19292]
## Issue description

The python scripts included with scribus (at least the calendar wizard) fail with "cannot find Tkinter".

### Steps to reproduce

install scribus. run it and select Scripts > Calendar Wizard.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 16.09pre85931.125ffff
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.2
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 
"16.09pre85931.125ffff"

**Comment by copumpkin** [comment]
Is this another `python` vs. `pythonFull` issue?

**Comment by FRidh** [comment]
just adding python.modules.tkinter should fix this.
