### ISSUE TITLE
[Build Failure] PowerDNS Admin

### ISSUE THREAD

**Issue by scottbot95** [NixOS/nixpkgs#192990]
### Steps To Reproduce
1. `nix build github:NixOS/nixpkgs/nixos-unstable#powerdns-admin` (as of fde244a8)

<details>
<summary>Build Log</summary>
<pre>
error: builder for '/nix/store/8r1frbwzxwncagff57r7zz86zl2nsxbm-python3.10-jsonschema-3.2.0.drv' failed with exit code 1;
       last 10 log lines:
       > Sourcing python-namespaces-hook
       > unpacking sources
       > unpacking source archive /nix/store/8bvp01hkv4wxb6wjvs7wvshbivqjmn98-jsonschema-3.2.0.tar.gz
       > source root is jsonschema-3.2.0
       > setting SOURCE_DATE_EPOCH to timestamp 1574081815 of file jsonschema-3.2.0/setup.cfg
       > patching sources
       > applying patch /nix/store/9n60qhpjc4w3cvr2mygdmlkxyp1y7ny7-remove-fancy-pypi-readme.patch
       > patching file pyproject.toml
       > Hunk #1 FAILED at 76.
       > 1 out of 1 hunk FAILED -- saving rejects to file pyproject.toml.rej
       For full logs, run 'nix log /nix/store/8r1frbwzxwncagff57r7zz86zl2nsxbm-python3.10-jsonschema-3.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/2413pkb4n4z1bj0rywpcfbi8s1yisvkg-python3.10-bravado-core-5.17.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/x9h491ipp10gpp771jzfr3qyn3y6pbf9-powerdns-admin-0.3.0.drv' failed to build
</pre>
</details>

### Additional context
Looks like json schema got updated to 4.13 which requires adding a patch. When [we override jsonschema to an older version](https://github.com/NixOS/nixpkgs/blob/78fd35f98e9411ddd2c31ef201a2fd8821bcd85a/pkgs/applications/networking/powerdns-admin/default.nix#L16-L29), we're not patching `patches` (please excuse the pun), so it tries to apply to new patch against 3.2.0 which, of course, fails. Seems like we probably just need to override the `patches` to remove the offending patch?

### Notify maintainers

@Flakebi @zhaofengli 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60.1-microsoft-standard-WSL2, Ubuntu, 20.04.3 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(scott): `"nixpkgs"`
 - nixpkgs: `/home/scott/.nix-defexpr/channels/nixpkgs`
```

**Comment by wahjava** [comment]
`gns3-server`, and `gns3-gui` are also broken in similar fashion.

**Comment by zhaofengli** [comment]
I'll take a look later today.

**Comment by zhaofengli** [comment]
I opened #193124.
