### ISSUE TITLE
LightDM shows the nixbld users

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#19291]
## Issue description

In NixOS (both 16.09 and 16.03), LightDM lists the 10 users from the nixbld group as well as my own user (the only real user on this machine). This bug does not appear with SDDM or GDM (which I have tested in NixOS 16.09).
### Steps to reproduce

My configuration is the following:

```
{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  # Define on which hard drive you want to install Grub.
  boot.loader.grub.device = "/dev/sda";

  networking.networkmanager.enable = true;

  # Select internationalisation properties.
  i18n = {
    consoleFont = "Lat2-Terminus16";
    consoleKeyMap = "fr";
    defaultLocale = "fr_FR.UTF-8";
  };

  # Set your time zone.
  time.timeZone = "Europe/Paris";

  # List packages installed in system profile. To search by name, run:
  # $ nix-env -qaP | grep wget
  environment.systemPackages = with pkgs; [
    wget
    firefox
    thunderbird
    libreoffice
    emacs
    networkmanagerapplet
  ];

  # Enable the X11 windowing system.
  services.xserver.enable = true;
  services.xserver.layout = "fr";
  services.xserver.xkbOptions = "eurosign:e";

  # Desktop Environment.
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.gnome3.enable = true;
  services.xserver.desktopManager.xfce.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.theo = {
    isNormalUser = true;
    uid = 1000;
    extraGroups = [
      "audio"
      "networkmanager"
    ];
  };

  # The NixOS release to be compatible with for stateful data such as databases.
  system.stateVersion = "16.09";

}
```
## Technical details
- System: NixOS 16.09.680.4e14fd5 (Flounder)
- Nix version: 1.11.4
- Nixpkgs version: 16.09.680.4e14fd5

**Comment by groxxda** [comment]
We should simply build lightdm with accountsservice support and enable `services.accounts-daemon` from the lightdm module.

Apart, this looks like a regression. We set hidden-users (and also hidden-shells) in lightdm/users.conf which should take care of it.

Can you check the contents of `/etc/lightdm/users.conf` ?

**Comment by Zimmi48** [comment]
```
[UserList]
minimum-uid=500
hidden-users=nixbld1 nixbld2 nixbld3 nixbld4 nixbld5 nixbld6 nixbld7 nixbld8 nixbld9 nixbld10
hidden-shells=/run/current-system/sw/bin/nologin
```

**Comment by groxxda** [comment]
According to the Debian wiki you can run `/usr/sbin/lightdm --show-config` to show the effective config. Does it include the hide-* directives?

**Comment by Zimmi48** [comment]
```
$ /nix/store/j2ir0m0fbjp9x4h15f1wqc3g7nz4g514-lightdm-1.18.1/bin/lightdm --show-config
   [LightDM]
A  greeter-user=lightdm
A  greeters-directory=/nix/store/g7vpgsj1hjgc17i7ihxapvj8wrp01n27-lightdm-gtk-greeter
A  sessions-directory=/nix/store/jmf9rvrb662p0y540m3cwngxhcir6zy5-desktops

   [Seat:*]
A  xserver-command=/nix/store/1s11gz68902qjc3r74qw5568s2lhi4z7-xserver-wrapper
A  session-wrapper=/nix/store/n1pp080z4wn3q0s8dggwn1srqscqjdi4-xsession
A  greeter-session=lightdm-gtk-greeter

Sources:
A  /etc/lightdm/lightdm.conf
```
Not sure what this means :/

**Comment by Zimmi48** [comment]
To note: removing `services.xserver.desktopManager.gnome3.enable = true;` solved the issue.
So the problem was coming from a bad interaction between LightDM, Gnome3, and possibly XFCE.

**Comment by obadz** [comment]
@Zimmi48, I suspect by removing gnome3, you removed accountservice (which enables lightdm to remember what window manager you wanted so not all good).

However, 8a547ae / ff81b74833768d3b5b77f688237d1fdea876e64e should have removed `nixbld` users from account service. Since that commit is in `master` but not in 4e14fd5 (your system version), that's what you were seeing the `nixbld` users.

**Comment by Zimmi48** [comment]
Then closing this issue. If someone experiences the problem again with a recent enough version, this can be opened again.

**Comment by obadz** [comment]
It's broken in 16.09, but I think fixing it requires merging too much.
