### ISSUE TITLE
Package Request: Lorien

### ISSUE THREAD

**Issue by dnswd** [NixOS/nixpkgs#192983]
**Project description**
From the project README.md -- "Lorien is an infinite canvas drawing/note-taking app that is focused on performance, small savefiles and simplicity. It's not based on bitmap images like Krita, Gimp or Photoshop; it rather saves brush strokes as a collection of points and renders them at runtime (kind of like SVG). It's primarily designed to be used as a digital notebook and as brainstorming tool."

**Metadata**

* homepage URL: https://github.com/mbrlabs/Lorien
* source URL: https://github.com/mbrlabs/Lorien
* license: mit
* platforms: linux (and maybe unix), darwin

**Comment by figsoda** [comment]
It is already in nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/lorien/default.nix
also see #164178

**Comment by dnswd** [comment]
Ah my bad.

I searched this package in channel [`22.05`](https://search.nixos.org/packages) and didn't find any, so I made this issue. Turns out it's available in [`unstable`](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=lorien) channel.

Closing this issue.
