### ISSUE TITLE
iio-sensor-proxy

### ISSUE THREAD

**Issue by huantianad** [NixOS/nixpkgs#192978]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `iio-sensor-proxy`

current version: 3.0
desired version: 3.4

###### Notify maintainers

maintainers: @peterhoeg 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by peterhoeg** [comment]
I unfortunately no longer have hardware that works with iio-sensor-proxy, so I have no way of testing out a new version.

**Comment by PJungkamp** [comment]
I got `iio-sensor-proxy` working on the latest version. I'm still somewhat new to Nix, but here is what changed from `3.0` to `3.4`.

- The build system changed from `autotools` to `meson`. (remove `automake` and add `meson`/`ninja`)
- A new dependency on `polkit` was introduced.
- The `polkit_policy_directory` in the `meson.build` needs to be patched.

Here's my overlay which I used to make it work:
```nix
final: prev: {
  iio-sensor-proxy = prev.iio-sensor-proxy.overrideAttrs (finalAttrs: prevAttrs: rec {
    version = "3.4";
    src = final.fetchFromGitLab {
      domain = "gitlab.freedesktop.org";
      owner = "hadess";
      repo = "iio-sensor-proxy";
      rev = version;
      sha256 = "sha256-O1rob/LVjNNY4F0d/Z9h8ZO7gVHZR8fvRhPpZ6GcyX0=";
    };
    patchPhase = ''
      sed -i "s|^polkit_policy_directory = .*\$|polkit_policy_directory = '$out/share/polkit-1/actions'|" meson.build
    '';
    configurePhase = null;
    mesonFlags = [
      "-Dudevrulesdir=${placeholder "out"}/lib/udev"
      "-Dsystemdsystemunitdir=${placeholder "out"}/lib/systemd/system"
    ];
    nativeBuildInputs = with final; [
      pkg-config
      meson
      ninja
    ];
    buildInputs = with final; [
      glib
      libgudev
      polkit
      systemd
    ];
  });
}
```

**Comment by wrenix** [comment]
@PJungkamp do you like to create an pullrequest ?

**Comment by applePrincess** [comment]
Close this as at be9851316f0ce73f2404a20e376cec886f239aeb, iio-sensor-proxy has version 3.5.
