### ISSUE TITLE
Vivaldi — some videos do not play

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#19300]
## Issue description

Some videos do not play in Vivaldi, for example —
https://www.youtube.com/watch?v=eoIQmWd8LTQ
Is says —
Your browser does not currently recognise any of video formats available.

All is fine in chromium or firefox.
### Steps to reproduce

Just open this link —
https://www.youtube.com/watch?v=eoIQmWd8LTQ
in Vivaldi.
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.09.680.4e14fd5 (Flounder)
- Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.4
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"16.09.680.4e14fd5"
- Vivaldi version

1.3.551.30 (Stable channel) (64-bit)

P.S. It also would be nice to have a newer version of Vivaldi.

**Comment by romildo** [comment]
It works for me on NixOS unstable.
```
$ nixos-version
17.03pre92039.adfcc2d (Gorilla)
```

**Comment by comonoid** [comment]
Oh, i forgot to write a Vivaldi version...
Vivaldi	1.3.551.30 (Stable channel) (64-bit)
As i can see, "needs: package (update)" label added.

**Comment by comonoid** [comment]
I switched to unstable — now it works for me...

**Comment by comonoid** [comment]
That youtube link works for me now.
Flash do not work completely.
Maybe it's worth to raise another ticket about flash in Vivaldi...
