### ISSUE TITLE
`slade` is out-of-date

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#193079]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: slade

current version: 3.1.1.5
desired version: 3.2.1

###### Notify maintainers

maintainers: @abbradar

###### Note for maintainers

Please tag this issue in your PR.

**Comment by wegank** [comment]
Closed by #198185.
