### ISSUE TITLE
Cannot build texlive.luatex on latest unstable

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#19301]
## Issue description / Steps to reproduce

```bash
nix-shell -p texlive.luatex --pure --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘shell’ at /nix/store/zcdzalwzz4s71vd6iv7340ljs73qn1ip-nixos-17.03pre92039.adfcc2d/nixos/pkgs/build-support/trivial-builders.nix:10:14:
cannot coerce a set to a string, at /nix/store/zcdzalwzz4s71vd6iv7340ljs73qn1ip-nixos-17.03pre92039.adfcc2d/nixos/pkgs/build-support/trivial-builders.nix:10:14
```

## Technical details

* System: 17.03pre92039.adfcc2d (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre92039.adfcc2d"

**Comment by vcunat** [comment]
You use it wrong. `texlive.pname` isn't meant to be separately usable (and it's not even meant to be a package).

**Comment by vcunat** [comment]
@matthiasbeyer: you probably want to depend on `texlive.combine { inherit (texlive) scheme-small luatex; }` or something similar.

**Comment by vcunat** [comment]
Example:
```
$ nix-build -Q -E 'with import <nixpkgs> {}; texlive.combine { inherit (texlive) scheme-small luatex; }'
/nix/store/jshaxzvdi9sq1xykc3iw5qmxy64chxl7-texlive-combined-2016
$ ./result/bin/luatex --version
This is LuaTeX, Version 0.95.0 (Web2C 2016/NixOS.org)
...
```

It's a bit complicated to use texlive with nix-env, unless you want some sledge-hammer like `texlive.combined.scheme-full`.

**Comment by matthiasbeyer** [comment]
ACK, that'll do the trick, I'm sure. Thanks for pointing out! :-)

**Comment by matthiasbeyer** [comment]
rebuilding my tex setup now. Goodby CPU! :-)

**Comment by matthiasbeyer** [comment]
Just for documentation purposes: Exactly what @vcunat mentioned was the problem.

**Comment by Mic92** [comment]
In which section we could document this? I also had a hard time getting started with latex.

**Comment by vcunat** [comment]
BTW, if you see something particular to improve in [the docs](http://nixos.org/nixpkgs/manual/#sec-language-texlive)...
