### ISSUE TITLE
super-slicer 3D rendering broken in unstable

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#193135]
### Describe the bug

Try to run super-slicer from nixos-unstable, on Wayland. The 3D view doesn't render at all, and the console logs are full of `Unable to init glew library`. I'm on Wayland, haven't checked if this repros in X11 or not.

### Steps To Reproduce

On Wayland:

`nix shell nixos-unstable#super-slicer`
`superslicer`

### Screenshots

![foo](https://user-images.githubusercontent.com/1918/192423596-43110029-590b-46a0-b4f5-8c6328bdb526.png)

(the gray window on the RHS should be a rendered 3D canvas with a 3D printer build plate in it)

### Additional context

This appears to have been caused by the wxWidgets upgrade to 3.1.5. 3.1.5 apparently enabled EGL support by default, and this causes some incompatibility in the bowels of SuperSlicer/wxWidgets/GLEW somewhere. There seem to be ~3 options to fix, with varying degrees of grossness:

*Option 1*: FreeBSD worked around this in prusa-slicer by hacking out the `return false`: https://cgit.freebsd.org/ports/commit/?id=b519599f37853728e94aba3d2c3c9d0d1022a512 . Ew!

*Option 2*: [SuperSlicer upstream bug](https://github.com/supermerill/SuperSlicer/issues/1093) suggests rebuilding wxWidgets with `--disable-glcanvasegl` to revert to 3.1.4 behavior. I've confirmed that rebuilding wxWidgets like this in nixpkgs fixes superslicer's rendering.

Note if we do this, Kicad will need a partial revert of https://github.com/NixOS/nixpkgs/pull/191887, where it enabled EGL in kicad's build to function with the new wxWidgets. I guess the question here is whether we suspect that wxWidgets+EGL is more widely broken than just the slic3r family of programs?

*Option 3*: Prusa Slicer in nixpkgs is already being built with a forked 3.1.4 wxWidgets. SuperSlicer is explicitly overriding that back to stock 3.1.5, which is why Prusa Slicer is still working fine in unstable. I've verified that changing superslicer to use prusa3d's wxWidgets fork also fixes rendering. Most likely any 3.1.4 wxWidgets will work, but prusa3d's version is handy because it's already in nixpkgs.

This is just delaying the headaches though: at some point prusaslicer will upgrade its wxWidgets and either this will break again, or prusaslicer will be fine but then superslicer will be broken until it finishes its rebase onto newer prusaslicer (which usually takes a few months iirc).

### Notify maintainers

@tfmoraes (wxWidgets maintainer), @Moredread @thorstenweber83 (prusa-slicer/superslicer maintainers), @evils @Kiwi (kicad maintainers)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.67, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(dave): `"nixos-unstable-22.05pre356435.7f9b6e2babf, nixpkgs-20.09.4407.1c1f5649bb9"`
 - nixpkgs: `/home/dave/.nix-defexpr/channels/nixpkgs`
```

**Comment by evils** [comment]
side note: wouldn't happen to know what change enabled EGL by default?

i'm building super-slicer with wxwidgets 3.2.1 to see if that changes anything

**Comment by evils** [comment]
with 3.2.1 it just segfaults

**Comment by danderson** [comment]
The change is just an upstream change: wxWidgets 3.1.5 turned on EGL support by default for wxGLCanvas. Previously it was a build flag but off by default. Source: [wxWidgets 3.1.5 release notes](https://www.wxwidgets.org/news/2021/04/wxwidgets-3.1.5-released/).

Given that Kicad seems to work with 3.1.5+EGL, I'm guessing the slic3r-derivative codebases are doing something wrong when EGL is involved. I guess that sort of makes sense since Kicad needed some ifdefs to make EGL work...

**Comment by Moredread** [comment]
I think option 2, but with an option added to the wxwidgets derivation  for enabling/disabling EGL support, and overriding wxwidgets in all-packages.nix for only those packages that have problems.

Or if we want to be more conservative for now, only enabling it for packages that have confirmed support like kicad.

Or we could add a package variant `wxwidgets-egl` to make the intention clearer. On the other hand this is likely a temporary problem.

**Comment by danderson** [comment]
Sounds reasonable to me. As you say this should be a temporary problem and I couldn't find anything but slic3r derivatives reporting this issue, so I'll prepare a PR that parameterizes the wxwidgets derivation and fixes up super-slicer in all-packages.nix.

**Comment by danderson** [comment]
Prusa folks did some digging and filed https://github.com/wxWidgets/wxWidgets/issues/22580 upstream, which looks like the bug superslicer hits with EGL. So, the option in #194021 should indeed be temporary until an upcoming wxwidgets relase :crossed_fingers:
