### ISSUE TITLE
"Mutt" message transmission error

### ISSUE THREAD

**Issue by usuha** [NixOS/nixpkgs#19316]
## Technical details
When I send an E-mail using the "Mutt", I will receive an error message such as the following.
Message transmission error. Child process has been completed in 127 (Exec error.).
14 line with an error in the /home/user_name/.mutt/muttrc:
set smtp_url = 'smtps: //user_name@gmail.com: password@smtp.gmail.com: 465 /'
: Unknown command
source: error in /home/pure/.mutt/muttrc
sh: ispell: not found command.

* System: (NixOS: `16.09`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by usuha** [comment]
This problem has been resolved.

**Comment by sternenseemann** [comment]
> This problem has been resolved.

Close?

**Comment by usuha** [comment]
Closed.
Many thanks.
