### ISSUE TITLE
Warning to prepare for Nextcloud 25.0.0 admin panel few breaking changes

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#193235]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `nextcloud`

current version: 24.0.5
desired version: 25.0.0beta7 (maybe we should just have a draft PR opened up?)

###### Notify maintainers

maintainers: @schneefux @globin @bachp 

###### Note for maintainers

Please tag this issue in your PR.

Please see this, a new package might be needed, lots of changes will be brought about: 
https://github.com/nextcloud/server/issues/32117#issuecomment-1259211942
https://help.nextcloud.com/t/scss-support-dropped-with-nextcloud-25/141471

Namely, this package [`christophwurst/nextcloud`](https://packagist.org/packages/christophwurst/nextcloud) is replaced by [`nextcloud/ocp`](https://packagist.org/packages/nextcloud/ocp).

**Comment by RaitoBezarius** [comment]
We are not affected by these issues AFAIK.
