### ISSUE TITLE
Packaging request: Xfce4-time-out-plugin

### ISSUE THREAD

**Issue by baronleonardo** [NixOS/nixpkgs#193299]
**Project description**
Xfce4-time-out-plugin makes it possible to take periodical breaks from the computer at user-configurable intervals. During breaks it locks your screen for a period specified by the user. It optionally allows you to postpone breaks for a certain time.

**Metadata**

* homepage URL: https://docs.xfce.org/panel-plugins/xfce4-time-out-plugin
* source URL: https://gitlab.xfce.org/panel-plugins/xfce4-time-out-plugin
* license: gpl2
* platforms: linux

**Comment by baronleonardo** [comment]
for now I'm using this derivation I created

```nix
{ lib, mkXfceDerivation, gtk3, libxfce4ui, libxfce4util, xfce4-panel, xfconf }:

mkXfceDerivation {
  category = "panel-plugins";
  pname = "xfce4-time-out-plugin";
  version = "1.1.2";
  rev-prefix = "xfce4-time-out-plugin-";
  odd-unstable = false;
  sha256 = "sha256-xfkQjlUfvm0YXs3bRJD4W/71VkaPq3Y+cDFVNiL/bjc=";

  buildInputs = [
    gtk3 libxfce4ui libxfce4util xfce4-panel xfconf
  ];

  meta = with lib; {
    description = "Xfce panel plugin acts like pomodoro";
    license = licenses.gpl2Plus;
    maintainers = with maintainers; [ ] ++ teams.xfce.members;
  };
}
```

**Comment by prusnak** [comment]
> for now I'm using this derivation I created and it works

Can you try to create a pull request? Should be trivial since you already figured out how the derivation should look like.

Just add it to the `pkgs/desktops/xfce/panel-plugins/xfce4-time-out-plugin/default.nix` file and add the reference to the `pkgs/desktops/xfce/default.nix` file.

**Comment by baronleonardo** [comment]
https://github.com/NixOS/nixpkgs/pull/193477
