### ISSUE TITLE
vimPlugins.project-nvim

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#193225]
**Project description**
The superior project management solution for neovim. 

**Metadata**

* homepage URL: https://github.com/ahmedkhalf/project.nvim
* source URL: https://github.com/ahmedkhalf/project.nvim
* license: apache 2.0
* platforms: all

**Comment by colin-heffernan** [comment]
Isn't this already in the repository?

**Comment by Alexnortung** [comment]
Oh yeah, how weird I coldn't find it the other day.
