### ISSUE TITLE
rst2pdf

### ISSUE THREAD

**Issue by opdavies** [NixOS/nixpkgs#193241]
**rst2pdf**
_The usual way of creating PDF from reStructuredText is by going through LaTeX. This tool provides an alternative by producing PDF directly using the ReportLab library._

**Metadata**

* homepage URL: https://rst2pdf.org
* source URL: https://github.com/rst2pdf/rst2pdf
* license: MIT
* platforms: unix, linux, darwin, ...

**Comment by gilice** [comment]
I want to package this - will try to do it in a few hours.
