### ISSUE TITLE
mariadb-client depends on gcc at runtime

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixpkgs#19338]
## Issue description

mariadb-client depends on gcc at runtime
### Steps to reproduce

``` shell
[clever@amd-nixos:~]$ nix-build '<nixpkgs>' -A mariadb.client
/nix/store/phvyvha8amcw7dm8557hkk4c66jyl6ac-mariadb-client-10.1.17-bin
[clever@amd-nixos:~]$ grep gcc result-bin/bin/mysqlbug 
COMP_CALL_INFO="CC='/nix/store/45qrn064f92kfxnjg99z39zxda671h6f-gcc-wrapper-5.4.0/bin/gcc'  CFLAGS=''  CXX='/nix/store/45qrn064f92kfxnjg99z39zxda671h6f-gcc-wrapper-5.4.0/bin/g++'  CXXFLAGS=''  LDFLAGS=''  ASFLAGS=''"
```

**Comment by copumpkin** [comment]
See https://github.com/NixOS/nixpkgs/issues/12898 and https://github.com/NixOS/nixpkgs/issues/5895

**Comment by matthewbauer** [comment]
Is "mysqlbug" the only thing referencing gcc? It was removed in mariadb 10.2, I think.

**Comment by cleverca22** [comment]
yeah, only mysqlbug references gcc, and master is on 10.1.17, bug still present

**Comment by NeQuissimus** [comment]
I think until MariaDB 10.2 becomes stable, we should leave this alone. As stated, `mysqlbug` has been removed from the 10.2.x series. Once they declare 10.2.x stable, we can update our mariadb and should no longer have the gcc dependency at runtime.

**Comment by Profpatsch** [comment]
(triage) fixed?

**Comment by vcunat** [comment]
Fixed now.
```
$ nix path-info -rf. mariadb.client | xargs du -sc | sort -n
128     /nix/store/bv6znzsv2qkbcwwa251dx7n5dshz3nr3-zlib-1.2.11
732     /nix/store/lgi2vjw1r2q67h8jibwx07snwscf1gcw-mariadb-client-10.2.17
1192    /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23
3616    /nix/store/9kr8r78bwk12050ppywfbhg1vrsd6dp8-openssl-1.0.2p
5636    /nix/store/zk5zj2307zxaq7dx585yia3dn5k4qlsl-gcc-7.3.0-lib
10780   /nix/store/s2n99784krxl91mfw3cnn9ylbb5fjvkx-ncurses-6.1
26428   /nix/store/fg4yq8i8wd08xg3fy58l6q73cjy8hjr2-glibc-2.27
39564   /nix/store/jv5ri2hp7m7714085qai3ysjilmcjngd-mariadb-client-10.2.17-bin
88076   total
```

The client has suspiciously large binaries in bin/ &ndash; possibly due to static linkage or something, but no gcc anymore.
