### ISSUE TITLE
Viber (16.1.0.37) cannot connect to the internet

### ISSUE THREAD

**Issue by icyrockcom** [NixOS/nixpkgs#193398]
### Describe the bug

Viber cannot connect to the internet. Other apps are able to connect to the internet.

### Steps To Reproduce

Install viber and start it.

### Expected behavior

Should be able to connect to the internet.

### Screenshots

![image](https://user-images.githubusercontent.com/785140/192887958-faeaad78-6b88-4886-8f05-ce0b0eb83b5b.png)

### Additional context

Nix configuration via flakes. Viber installed through an entry in `environment.systemPackages`.

Found similar issues with Ubuntu 22.04 e.g. https://askubuntu.com/questions/1403319/viber-no-connection-on-ubuntu-22-04-even-i-have-an-internet

### Notify maintainers

@jagajaga 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.11 (Raccoon), 22.11.20220926.62228cc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by onny** [comment]
Please open a new issue if this problem still exists. Closing this for now as there are more up-to-date viber versions in nixpkgs
