### ISSUE TITLE
Remove outdated protobuf versions

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#193370]
The following security advisory affects releases before 3.16.1, 3.17.3 and prior while fixes are only provided for 3.18.x and later.

https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf

> A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated.

We should therefore consider versions before 3.18.x end of life.

cc @jonringer

This affects:
- [x] `protobuf3_17`
  - [x] `ghidra` @roblabla 
  - [x] `python2Packages.protobuf` @knedlsepp 
- [x] `protobuf3_11`
  - Removed in #193365 
- [x] `protobuf3_8`
  - [x] `ibus-engines.mozc`
    - #193416 
  - [x] `fcitx-engines.mozc` @ericsagnes  @gebner 
  - [x] `python3.pkgs.tensorboardx` @lebastr @akamaus
    - #193416 
  - [x] `rippled` @offlinehacker @RaghavSood 
    - #193416 
- [x] `protobuf3_7`
  - [x] `hadoop` @illustris 
    - https://github.com/NixOS/nixpkgs/pull/193665
  - [x] `mysql57`@LeSuisse

**Comment by roblabla** [comment]
Ghidra upstream is still using 3.17.3: https://github.com/NationalSecurityAgency/ghidra/blob/c51183f1a262c80d45aac48d4f3343c67b6bd41a/Ghidra/Debug/Debugger-gadp/build.gradle#L36

They've been planning to update for a good while now... https://github.com/NationalSecurityAgency/ghidra/pull/4415#issuecomment-1198321500

I'm not sure what's the hold up on their end. We may be able to update on our end without waiting for upstream.

**Comment by mweinelt** [comment]
Feel free to give this a try and ideally remove protobuf3_17 at the same time, since ghidra is its last consumer.

**Comment by vcunat** [comment]
Their master is on 3.21.8 right now
https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Debug/Debugger-gadp/build.gradle#L36
but the tagged versions are still on the old one.

**Comment by RaitoBezarius** [comment]
I see that `protobuf3_8` is not used anymore, I don't know which PR fixed that.

**Comment by RaitoBezarius** [comment]
@roblabla @knedlsepp It seems like Ghidra can upgrade and get the latest Protobuf at the moment, could you look into it for the 23.05 release? Thank you!

**Comment by roblabla** [comment]
Latest Ghidra release is still stuck on protobuf 3.17. I can look into cherry-picking the commits that update protobuf to our build.

**Comment by erdnaxe** [comment]
Ghidra 10.3 (released last week) seems to update protobuf:

> Debugger. Upgraded protobuf to 3.21.8. (GP-2302, Issue #4415, #4540)

Should we update Ghidra for 23.05 (and there are some new cool features)?
