### ISSUE TITLE
Publii: desktop CMS for creating static websites

### ISSUE THREAD

**Issue by milahu** [NixOS/nixpkgs#193461]
**Project description**

Publii is a desktop-based CMS for Windows, Mac and Linux
that makes creating static websites fast and hassle-free, even for beginners.

fix #104376

**Metadata**

* homepage URL: https://getpublii.com/
* source URL: https://github.com/GetPublii/Publii
* license: gpl3
* platforms: unix, linux, darwin

**Comment by SebTM** [comment]
#226522

**Comment by Granitosaurus** [comment]
The current package got me pretty far except there seems to be some issues with permissions when it comes to saving changes. It keeps throwing errors like this:
```
Rendering process failed
An error occurred during rendering process:

EACCES: permission denied, open '/home/user/Documents/Publii/sites/test/input/themes/simple/assets/css/style.css'
```
For example when pressing the "Preview your changes" button:

![image](https://github.com/NixOS/nixpkgs/assets/5476164/02765604-3a61-4819-98a4-4b314c10834e)

This seems to be nodejs related though I'm not sure what's exactly wrong here.

**Comment by SebTM** [comment]
As mentioned [here](https://github.com/NixOS/nixpkgs/pull/271107#issuecomment-1833574215), know issue but unsure how I can fix it maybe worth asking at NixOS-discourse or upstream at Publii if there is a known / easy-solution. Quick look through the issues on GitHub (Publii) didn't showed something to me but sadly no time atm. to dig deeper.

**Comment by Granitosaurus** [comment]
> As mentioned [here](https://github.com/NixOS/nixpkgs/pull/271107#issuecomment-1833574215), know issue but unsure how I can fix it maybe worth asking at NixOS-discourse or upstream at Publii if there is a known / easy-solution. Quick look through the issues on GitHub (Publii) didn't show something to me but sadly no time atm. to dig deeper.

Thanks! Forcing chmod 644 on all Publii project files does fix this (e.g. `cd ~/Documents/Publii && fd --type f --exec chmod 664 {}`). My bet is it's related to Node runtime as it's notoriously clunky as a desktop runtime.

**Comment by SebTM** [comment]
Just to track as it's really annoying when working with more regularly, created an upstream-issue to maybe resolve it: https://github.com/GetPublii/Publii/issues/1322

**Comment by SebTM** [comment]
> Thanks! Forcing chmod 644 on all Publii project files does fix this (e.g. cd ~/Documents/Publii && fd --type f --exec chmod 664 {}). My bet is it's related to Node runtime as it's notoriously clunky as a desktop runtime.

Yes I agree, we debugged quite deep but couldn't find a solution so I guess this workaround will be needed for now - as the app is packaged I'm closing this for now 🙏🏻
