### ISSUE TITLE
Remove apple-music-electron

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#193593]
## Issue description

It is EOL.

This seem to be not needed anymore as well.

https://github.com/NixOS/nixpkgs/blob/77ea361da585bfd729735ef83768e3fe30d39168/pkgs/build-support/appimage/default.nix#L200

cc maintainer @IvarWithoutBones

Use https://github.com/ciderapp/Cider instead.

### Steps to reproduce

https://github.com/ciderapp/Apple-Music-Electron

**Comment by IvarWithoutBones** [comment]
Thanks for letting me know, ive opened a PR which removes it.
