### ISSUE TITLE
🦝 NixOS 22.11 - Release schedule

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#193585]
Hi, we are [Janne Heß](https://github.com/dasJ) & [Martin Weinelt](https://github.com/mweinelt), the release managers for NixOS 22.11 🦝 ("*Raccoon*").

Below you can find the release calendar for the next two months running up to the planned release at the end of November 2022. If something feels unclear to you, don't hesitate to reach out, we are here to guide the process and make sure this will be a satisfying release for all of us.

Stay tuned for updates!

## Schedule

<table>
    <tr>
        <td></td>
        <td>Date</td>
        <td>Affects</td>
        <td>Events</td>
    </tr>
    <tr>
        <td>✔️</td>
        <td>2022-10-03</td>
        <td>—</td>
        <td>Start <a href="https://github.com/NixOS/nixpkgs/issues/194208">discussion</a> about "Feature Freeze & Release Blockers" with ecosystem maintainers</td>
    </tr>
    <tr>
        <td>✔️</td>
        <td>2022-10-17</td>
        <td>all branches</td>
        <td>Restrict breaking changes to <a href="https://nixos.github.io/release-wiki/Release-Critical-Packages.html">Release Critical Packages</a></td>
    </tr>
    <tr>
        <td>✔️</td>
        <td>2022-10-31</td>
        <td><tt>staging</tt>, <tt>staging-next</tt></td>
        <td>Restrict all breaking changes with the exception of desktop environments</td>
    </tr>
    <tr>
        <td rowspan="2">✔️</td>
        <td rowspan="2">2022-11-07</td>
        <td><tt>master</tt></td>
        <td>Wait for <tt>staging-next</tt> merge into <tt>master</tt>; begin first <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Begin <a href="https://github.com/NixOS/nixpkgs/issues/199919">Zero Hydra Failures</a> campaign</td>
    </tr>
    <tr>
        <td rowspan="2">✔️</td>
        <td rowspan="2">2022-11-14</td>
        <td><tt>master</tt></td>
        <td>Wait for first <tt>staging-next</tt> merge into <tt>master</tt>; begin second <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>staging</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td rowspan="8">✔️</td>
        <td rowspan="8">2022-11-21</td>
        <td><tt>master</tt></td>
        <td>Wait for second <tt>staging-next</tt> merge into <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>staging-next</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Mark failing packages as broken</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-22.11</tt></td>
        <td>Branch-off</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-22.11</tt></td>
        <td>Tag <tt>22.11-beta</tt> on <tt>release-22.11</tt><br /> and <tt>23.05-unstable</tt> on <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-22.11</tt></td>
        <td>Create release channels</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-22.11</tt></td>
        <td>ZHF fixes go into <tt>master</tt> and need to be backported to <tt>release-22.11</tt></td>
    </tr>
    <tr>
        <td><tt>release-22.11</tt></td>
        <td>Prepare for release, finish remaining issues</td>
    </tr>
    <tr>
        <td>✔️</td>
        <td>2022-11-30</td>
        <td><tt>release-22.11</tt></td>
        <td>Release! Also, ZHF ends</td>
    </tr>
    <tr>
        <td></td>
        <td>2022-12-09.</td>
        <td>—</td>
        <td>Release Retrospective, everyone is invited to give feedback!</td>
    </tr>
</table

---

## Definitions

- Backport
    - Cherry-picking a change from `master` into `release-22.11`
    - Use the backport action by applying the `backport: release-22.11` tag
- Breaking change
    - A change that is likely to break downstream consumers
- Ecosystem maintainers
    - Maintainer teams that have enabled `enableFeatureFreezePing`  in [`maintainers/team-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix)
- [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html)
    - List of packages that usually cause widespread breakages
- Restriction
    - Changes of the mentioned kind cannot be merged while the restriction is active
- ZHF
    - Zero Hydra Failures
    - Period in which contributors focus on stabilizing packages
    - Usually through PRs targeted at the `master` branch

**Comment by NobbZ** [comment]
I found this issue by accident, it would be nice if the release schedule would be announced on the forum like it has happened the last releases, and if it is just a "schedule is available at GitHub, please follow the link".

The release schedule is a major piece of information and relevant to all of us, not only to those that follow GH issues. It should therefore be announced on all available channels.

In my opinion this includes, but is not limited to:

* The discourse
* The website (blog?)
* Matrix channel subject

**Comment by mweinelt** [comment]
- We will create a discourse post for the start of the zero hydra failures (ZHF) effort some time next week.
- We don't control the Matrix room topics, will talk to the infra team to do the update
- There will be a blog entry once we finish the release.

**Comment by mweinelt** [comment]
We currently have one more staging cycle planned before the branch-off. It's about time to get the latest **non-breaking** changes in. Also please be responsive when your changes on staging break in the next week.

**Comment by mweinelt** [comment]
That staging-next has been opened earlier today and that means `staging` is now free to receive breaking changes again. They will not arrive in the release.

We started staging-next two days early due to the available compute capacity on hydra, but if there are still changes that should pass through there they can still be targeted at `staging-next`.

**Comment by mweinelt** [comment]
The retrospective has been scheduled for 2022-12-09, 18:00 UTC and will likely happen on a Jitsi Meet call announced in the release management room on Matrix. Feel free to join!

**Comment by winterqt** [comment]
I think this can be unpinned now. Thanks to everyone involved, and see you in May!

![EE9D19D8-8202-4BD7-A0C2-C800176C4A1E](https://user-images.githubusercontent.com/78392041/206867061-492c8f43-22a7-4425-9ff8-4a913be69817.jpeg)
