### ISSUE TITLE
XFCE - Minimizing Firefox main window causes Picture-in-Picture to disappear

### ISSUE THREAD

**Issue by rickytower** [NixOS/nixpkgs#193510]
### Describe the bug
This bug is related to Mozilla Firefox 105.0.1 on xfce 4.16. 
 I click on this icon (circled in red below, in the image)
![picture-in-picture](https://user-images.githubusercontent.com/33136381/193023684-4bc350c6-badf-4f46-88e6-6e72678002ed.png)

to activate the picture-in-picture mode as below.
![immagine](https://user-images.githubusercontent.com/33136381/193023853-9d1f934d-de89-4017-9b25-382e9314fa16.png)

It works well except when I minimize the Firefox main window (where I activated the picture-in-picture mode) that minimizes also the picture-in-picture window. 
This bug is reported also here: https://gitlab.xfce.org/xfce/xfwm4/-/issues/525

### Steps To Reproduce
1. watch a video from YouTube (for example)
2. click on the button picture-in-picture
3. minimize Firefox window

### Expected behavior
When I minimize Firefox main window, the picture-in-picture window should remain visible as before minimizing.
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[nix-shell:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.70, NixOS, 22.05 (Quokka), 22.05.3328.0c97cb06a5b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by bobby285271** [comment]
> This bug is reported also here: https://gitlab.xfce.org/xfce/xfwm4/-/issues/525

The fix for this issue is part of xfwm 4.18.0, so I am assuming https://github.com/NixOS/nixpkgs/pull/206282/commits/d81262fb733698e2acc0dc2d569a6dca01dc4976 addressed this, please re-open if you still have this issue
