### ISSUE TITLE
X11/extensions/XInput2.h

### ISSUE THREAD

**Issue by auroraanna** [NixOS/nixpkgs#193573]
**Project description**
It handles X user input. (I have no idea really but it's a dependency of a library I want to build)

**Metadata**

* homepage URL: https://cgit.freedesktop.org/xorg/lib/libXi/tree/include/X11/extensions/XInput2.h
* source URL: https://cgit.freedesktop.org/xorg/lib/libXi/tree/include/X11/extensions/XInput2.h
* license: several?: https://cgit.freedesktop.org/xorg/lib/libXi/tree/COPYING
* platforms: linux

**Comment by vcunat** [comment]
It's there already:
```
$ nix build -f. xorg.libXi.dev
$ ls -l result-dev/include/X11/extensions/XInput2.h
```

**Comment by auroraanna** [comment]
Thanks, package naming obscurities I guess…

**Comment by auroraanna** [comment]
@vcunat: Do you know which package corresponds to `X11/extensions/Xge.h`? I can't find any reference for this. Where do I look this up?

**Comment by auroraanna** [comment]
Got it now. It's `xorg.libXext

**Comment by vcunat** [comment]
I believe the naming is the same as almost everywhere else, except for the `xorg.` prefix.

**Comment by kira-bruneau** [comment]
I usually use nix-index + nix-locate to find deps like this: https://github.com/bennofs/nix-index
