### ISSUE TITLE
[Packaging Request] Sunshine

### ISSUE THREAD

**Issue by IceDBorn** [NixOS/nixpkgs#193688]
**Project description**
Sunshine is a Game stream host for Moonlight. Sunshine is a self hosted, low latency, cloud gaming solution with support for AMD, Intel, and Nvidia gpus. It is an open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield. Connect to Sunshine from any Moonlight client, available for nearly any device imaginable.

**Metadata**

* homepage/source URL: https://github.com/LizardByte/Sunshine
* license: GPL-3.0
* platforms: linux, darwin

**Comment by adisbladis** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/197413.
