### ISSUE TITLE
dotnet-sdk_6 has files at the root of its $out directory

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nixpkgs#193656]
### Describe the bug

The package `dotnet-sdk_6` includes files at the root of its `$out` directory, increasing the chances for conflicts. (related [discourse discussion](https://discourse.nixos.org/t/collision-between-2-license-txt-from-2-different-packages/22071)).

### Steps To Reproduce
1. `nix build github:NixOS/nixpkgs#dotnet-sdk_6`
2. ls -l ./result

You will see a `LICENSE.txt`, a `dotnet` and other files in there.

### Expected behavior

There should only be folders in `./result/`.

### Notify maintainers

@kuznero @mdarocha 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.9-200.fc36.x86_64, Fedora Linux, 36 (Workstation Edition), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `""`
 - nixpkgs: `/home/cassou/Documents/projects/nix-system/nixpkgs`

```

**Comment by mdarocha** [comment]
I made a PR with a fix, when it's merged this will be fixed.
