### ISSUE TITLE
Mesa 22.2.0

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#193655]
###### Checklist
https://docs.mesa3d.org/relnotes/22.2.0.html

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: legacyPackages.x86_64-linux.mesa

current version: 22.1.7
desired version: 22.2.0

###### Notify maintainers

maintainers: @primeos @vcunat 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/192243#issuecomment-1254183723
