### ISSUE TITLE
 [UPDATE] catppuccin-gtk: unstable-2022-02-24 -> 0.2.7

### ISSUE THREAD

**Issue by jtrees** [NixOS/nixpkgs#193769]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: catppuccin-gtk

current version: unstable-2022-02-24
desired version: 0.2.7 (or newer)

###### Notify maintainers

maintainers: @fufexan 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by fufexan** [comment]
It was updated https://github.com/NixOS/nixpkgs/pull/187245.

**Comment by jtrees** [comment]
Oh, I'm sorry. I checked both git and used the package search and obviously missed both results. Gotta get some more sleep.

**Comment by jtrees** [comment]
Looking more closely I see that themes resulting from the nix package don't line up with the ones from the GitHub release.

Here we've got names like "Catppuccin-Purple" and "Catppuccin-Purple-Dark", upstream (pre-packaged) the names are "Catppuccin-Latte-Muave" and "Catppuccin-Mocha-Muave". In this case, I presume they can be inter-changed but others such as "Catppuccin-Frappe-Muave" and "Catppuccin-Macchiato-Muave" seem to be missing.

I presume this is an upstream bug (no way to build the pre-packaged versions).  Perhaps you could simply grab the pre-packaged themes instead of building them?

**Comment by fufexan** [comment]
I've thought about that, but it would just be a temporary fix on our end. We would revert to building from source as soon as they support it from the install scripts.

I've seen some work on that in [this branch](https://github.com/catppuccin/gtk/tree/dev0.2).
