### ISSUE TITLE
davinci-resolve: error while loading shared libraries: libc++.so.1

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#193750]
### Describe the bug

Since the last update, it does not start anymore.

```
[davidak@gaming:~]$ davinci-resolve 
/nix/store/zdzpakjhppr6hd47y3ardxnl9hyfm45s-davinci-resolve-17.4.3/bin/resolve: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```

### Steps To Reproduce
1. Install davinci-resolve
2. Run davinci-resolve

### Expected behavior
Working Program.

### Additional context

**Workaround**: Use the package from unstable channel.

### Notify maintainers
@jshcmpbll

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.05 (Quokka), 22.05.3284.b542cc75fa0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidak** [comment]
I don't have this issue on unstable, so i don't know if we should fix this only on stable. We will soon have a new release and one can easily use the version from unstable.

We could mark it as broken, so people don't build it just to find out it does not start.

**Comment by jshcmpbll** [comment]
@davidak I haven't had any issues building lately. Are you still having this issue or is it okay to close?

**Comment by pbsds** [comment]
Considering it works on `23.05` i believe we can close this
