### ISSUE TITLE
Remove leaps

### ISSUE THREAD

**Issue by aaronjheng** [NixOS/nixpkgs#193713]
## Issue description
From https://github.com/Jeffail/leaps
```
WARNING: This project is no longer actively maintained.
```

cc @qknight

**Comment by gilice** [comment]
Is it certain that this has to be removed? I do not think that I know enough about Nix packaging standards to know policies, but the project could be "completed" with no new features to come, too.

**Comment by aaronjheng** [comment]
I'm trying to update leaps to the latest version 0.9.1 (with `buildGoModule`). There are some vendoring problems on macOS. So maybe we could remove it if it is not actively maintained.

**Comment by wamserma** [comment]
As long as it works and has no (serious) security issues, we can keep it. If a maintained fork emerges, we should switch to it.
Once things break, we should consider removal.
