### ISSUE TITLE
Update mongodb-tools

### ISSUE THREAD

**Issue by rvl** [NixOS/nixpkgs#19395]
Hello, is someone able to update mongodb-tools to the newest version? E.g. [r3.3.11](https://github.com/mongodb/mongo-tools/releases/tag/r3.3.11).

I tried, but couldn't manage to properly set up `GOPATH` for go2nix.

Cheers

/cc @kamilchm

**Comment by kamilchm** [comment]
Hi, I can look at it tomorrow. Could you provide a list of steps you tried with go2nix?

**Comment by rvl** [comment]
Thanks, I tried this:
```
git clone git@github.com:mongodb/mongo-tools.git
cd mongo-tools
nix-shell -p go2nix go
source ./set_gopath.sh
./build.sh
go2nix save
# => Current dir mongo-tools is outside of GOPATH(...). Can't get current package name
```

**Comment by rvl** [comment]
Closing this for the time being because I don't need mongo-tools any more. Can reopen if anyone would like to pick it up.
