### ISSUE TITLE
Missing Package: DNGLab - A camera RAW to DNG file format converter

### ISSUE THREAD

**Issue by xave** [NixOS/nixpkgs#193967]
**Project description**
DNGLab - A camera RAW to DNG file format converter

Command line tool to convert camera RAW files to Digital Negative Format (DNG).

**Metadata**

* homepage URL: n/a
* source URL: https://github.com/dnglab/dnglab
* license: GNU Lesser General Public License v2.1
* platforms: unix, linux, darwin

**Comment by dit7ya** [comment]
@xave Can you please test the linked PR and let me know if it works for you (I have not personally tested the program)?
