### ISSUE TITLE
Newsboat won't display non-ascii characters

### ISSUE THREAD

**Issue by kickerofelves** [NixOS/nixpkgs#194060]
### Describe the bug
Newsboat doesn't display characters that are non-ascii. I'm trying out newsboat due to the Debian package being two years out-of-date.

### Steps To Reproduce
I installed newsboat from the unstable branch using `nix-env -iA nixpkgs.newsboat`

### Expected behavior
Nix's newsboat should look the same as Debian's.

### Screenshots
![Picture comparison](https://i.postimg.cc/c1kQ1JWx/newsboat-compare.png)

### Additional context
I'm using single-user mode because of [#6966](https://github.com/NixOS/nix/issues/6966). I found #60845 but it doesn't seem relevant.

When I switch back to Debian's newsboat everything appears correctly. Is Nix's newsboat unable to access Debian's system fonts?

``` 
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
```
### Notify maintainers

@dotlambda @nicknovitski
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.0-1-amd64, Debian GNU/Linux, noversion, nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.3`
 - channels(user): `"nixpkgs"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

```

**Comment by onemoresuza** [comment]
This seems to be related with Nix's [559](https://github.com/NixOS/nix/issues/599) issue, since, by doing its workaround, the problem looks like it has gone away.

Workaround as provided in [Stack Exchange](https://unix.stackexchange.com/questions/187402/nix-package-manager-perl-warning-setting-locale-failed):
1. `nix-env -iA nixpkgs.glibcLocales`
2. `export LOCALE_ARCHIVE="$(nix-env --installed --no-name --out-path --query glibc-locales)/lib/locale/locale-archive"`

**Comment by kickerofelves** [comment]
Thanks @onemoresuza. the issue prompted me to move to elfeed but your link led me to https://nixos.wiki/wiki/Locales (your step 2) which worked without needing to install anything else.
