### ISSUE TITLE
Mono being built from source when adding steam run to `environment.systemPackages`

### ISSUE THREAD

**Issue by drishal** [NixOS/nixpkgs#194087]
### Describe the bug
For some reason if I add steam-run to my environment.systemPackages, it starts to compile mono from source instead of using the binary cache, which takes a long time on my device  (on NixOS unstable branch) (after using `nixos-rebuild switch` on flake
However if I remove `steam-run` and add mono as it is, then it pulls from binary without any problems 

### Expected behavior
Mono should have been pulled from the cache instead of being built from source when trying to add steam-run to `environment.systemPackages`

### Notify maintainers
@obadz @vrthra 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.11, NixOS, 22.11 (Raccoon), 22.11.20220930.10ecda2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(drishal): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
my dotfiles: https://github.com/drishal/dotfiles

**Comment by MaeIsBad** [comment]
Looks like pkgs.i686Linux.mono wasn't built by hydra for whatever reason
