### ISSUE TITLE
wpa_supplicant service not started

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19409]
## Issue description
I just switched from a 16.09 system onto a build from master.
After rebooting, `wpa_supplicant` does not connect me to my WiFi.
There does not even seem to be an attempt to start it.

This is output from **16.09**:
```
~> systemctl | grep wpa
wpa_supplicant.service    loaded active running   WPA Supplicant
```

**17.03.git**:
```
~> systemctl | grep wpa
exit 1
~> systemctl status wpa_supplicant.service
● wpa_supplicant.service - WPA Supplicant
   Loaded: loaded (/nix/store/ac45kz2svv1xfyliarwckd6ym7z77857-unit-wpa_supplicant.service/wpa_supplicant.service; st
   Active: inactive (dead)
exit 3
```

Note that restarting the service will connect me to my WiFi:

```
~> systemctl status wpa_supplicant.service                 
● wpa_supplicant.service - WPA Supplicant
   Loaded: loaded (/nix/store/ac45kz2svv1xfyliarwckd6ym7z77857-unit-wpa_supplicant.service/wpa_supplicant.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2016-10-09 19:24:23 EDT; 7min ago
 Main PID: 1507
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/wpa_supplicant.service
           └─1507 wpa_supplicant -s -u -Dnl80211,wext -c /nix/store/9664kfvy9mr0bbfbs28dgak3gn6fzd3c-wpa_supplicant.conf -iwlp1s0
```

### Steps to reproduce
- `nixos-rebuild boot --upgrade -I nixpkgs=/home/nequi/dev/nixpkgs`
- Reboot

## Technical details

* System: 17.03.git.48907cb (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre93234.2e255a2"

**Comment by vcunat** [comment]
Useful info from the duplicate issue:

> The relevant change appears to be changing After=network-interfaces.target to After=network.target. I don't know what this does, or what this is supposed to do, but the effect seems to be that it stops wpa_supplicant from starting.

**Comment by vcunat** [comment]
@groxxda: it seems like you changed some related stuff recently, e.g. in 60a9edbbe.

**Comment by groxxda** [comment]
As stated in another issue on `wpa_supplicant` misbehavior https://github.com/NixOS/nixpkgs/issues/19029#issuecomment-250216237 `wantedBy` is wrong in both modules. Also I think that @shlevy s fix is not needed.

> Both look broken to me since they have `wantedBy = [ "network.target" ]` when they really should have `wants = [ "network.target" ]` and _maybe_ `wantedBy = [ "multi-user.target" ];`.

[upstream service file](http://w1.fi/cgit/hostap/tree/wpa_supplicant/systemd/wpa_supplicant.service.in)

Here's an untested patch
```
From 02fa8d07ad0671ee41b0fdaf015d686b65d4c514 Mon Sep 17 00:00:00 2001
From: Alexander Ried <ried@mytum.de>
Date: Wed, 19 Oct 2016 00:09:49 +0200
Subject: [PATCH] supplicant: fix dependencies

---
 nixos/modules/services/networking/supplicant.nix     | 3 ++-
 nixos/modules/services/networking/wpa_supplicant.nix | 6 ++++--
 2 files changed, 6 insertions(+), 3 deletions(-)

diff --git a/nixos/modules/services/networking/supplicant.nix b/nixos/modules/services/networking/supplicant.nix
index e433ec7..0c459fb 100644
--- a/nixos/modules/services/networking/supplicant.nix
+++ b/nixos/modules/services/networking/supplicant.nix
@@ -34,7 +34,8 @@ let
       '';
     in
       { description = "Supplicant ${iface}${optionalString (iface=="WLAN"||iface=="LAN") " %I"}";
-        wantedBy = [ "network.target" ] ++ deps;
+        wantedBy = [ "multi-user.target" ] ++ deps;
+        wants = [ "network.target" ];
         bindsTo = deps;
         after = deps;
         before = [ "network.target" ];
diff --git a/nixos/modules/services/networking/wpa_supplicant.nix b/nixos/modules/services/networking/wpa_supplicant.nix
index a344d78..5657b91 100644
--- a/nixos/modules/services/networking/wpa_supplicant.nix
+++ b/nixos/modules/services/networking/wpa_supplicant.nix
@@ -128,9 +128,11 @@ in {
     in {
       description = "WPA Supplicant";
 
-      after = [ "network.target" ] ++ lib.concatMap deviceUnit ifaces;
+      after = lib.concatMap deviceUnit ifaces;
+      before = [ "network.target" ];
+      wants = [ "network.target" ];
       requires = lib.concatMap deviceUnit ifaces;
-      wantedBy = [ "network-online.target" ];
+      wantedBy = [ "multi-user.target" ];
 
       path = [ pkgs.wpa_supplicant ];
 
```

Can someone who uses one of the broken modules please test if this fixes the issue (even better if both modules are tested)? I'm a bit reluctant on filing a PR blindly 


CC @shlevy @ttuegel @NeQuissimus

**Comment by vcunat** [comment]
Looks better:
```
$ sudo nixos-rebuild switch ...
...
the following new units were started: wpa_supplicant.service
```

BTW, I was unable to copy-and-apply the patch and had to overwrite it by hand. For other testers:
```
$ curl https://github.com/NixOS/nixpkgs/commit/3bd0dce70255.patch | git am
```

**Comment by shlevy** [comment]
I'm not on master, but FWIW supplicant.nix is working for me fine (and wasn't before my patch, as unneeded as I agree it should be)

**Comment by groxxda** [comment]
Oh of course the fix is not needed for supplicant.nix since the devices take care of pulling the service in.. Maybe a bit hacky :see_no_evil: But if it works.

Maybe someday someone unifies both modules and removes the hacks :pray:

**Comment by NeQuissimus** [comment]
@groxxda Could you wrap this into a proper PR?
