### ISSUE TITLE
Patchance

### ISSUE THREAD

**Issue by PowerUser64** [NixOS/nixpkgs#194023]
**Project description**
Patchance is a JACK patchbay GUI. It allows you to connect or disconnect audio programs to one another using JACK, much like RaySession (see #194022). However, it does not offer save/load functionality, or the ability to start programs from within the application. There is an AUR package for this here: https://aur.archlinux.org/packages/patchance.

**Metadata**

* homepage URL: https://github.com/Houston4444/Patchance
* source URL: https://github.com/Houston4444/Patchance
* license: gpl2
* platforms: linux

**Comment by Houston4444** [comment]
Note: last release contains a full package including sub-modules files.
