### ISSUE TITLE
fglrx crashing on startup with xorg 1.17.4 on flounder

### ISSUE THREAD

**Issue by ksf** [NixOS/nixpkgs#19407]
[Full xorg-server log on pastebin because github refuses to eat it](http://pastebin.com/8aGa9fgU), here's the salient part:

    (II) Loading /nix/store/cmblgg6wym7bwz6nqq0pyylxzf773zmk-ati-drivers-15.12-4.4.23/lib/xorg/modules/drivers/fglrx_drv.so
    (II) Module fglrx: vendor="FireGL - AMD Technologies Inc."
            compiled for 1.4.99.906, module version = 15.30.3
            Module class: X.Org Video Driver
    (EE) Backtrace:
    (EE) 0: /nix/store/f0xswf98jssaknfssrrdksa32zsplfbz-xorg-server-1.17.4/bin/X (OsSigHandler+0x29) [0x596f89]
    (EE) 1: /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/libpthread.so.0 (__restore_rt+0x0) [0x7f9697c12e8f]
    (EE) 2: /nix/store/cmblgg6wym7bwz6nqq0pyylxzf773zmk-ati-drivers-15.12-4.4.23/lib/xorg/modules/drivers/fglrx_drv.so (atiddxCheckXserverVersion+0x36a) [0x7f969302f6fa]
    (EE) 3: /nix/store/cmblgg6wym7bwz6nqq0pyylxzf773zmk-ati-drivers-15.12-4.4.23/lib/xorg/modules/drivers/fglrx_drv.so (atiddxSetup+0x4f) [0x7f969302f24f]
    (EE) 4: /nix/store/f0xswf98jssaknfssrrdksa32zsplfbz-xorg-server-1.17.4/bin/X (LoadModule+0x76f) [0x46c42f]
    (EE) 5: /nix/store/f0xswf98jssaknfssrrdksa32zsplfbz-xorg-server-1.17.4/bin/X (xf86LoadModules+0xbd) [0x47c45d]
    (EE) 6: /nix/store/f0xswf98jssaknfssrrdksa32zsplfbz-xorg-server-1.17.4/bin/X (InitOutput+0x816) [0x47ccf6]
    (EE) 7: /nix/store/f0xswf98jssaknfssrrdksa32zsplfbz-xorg-server-1.17.4/bin/X (dix_main+0x1ea) [0x43de6a]

### Reproduce:

Have my system, enable ati_unfree.

### Info:

* Card: 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Turks XT [Radeon HD 6670/7670] \(It's a 6670)

* System: 16.09.695.45b2a6d (Flounder)

**Comment by domenkozar** [comment]
cc @vcunat @heydojo

**Comment by davorb** [comment]
What version of the kernel are you running? AFAIK ```fglrx``` is unsupported (by AMD) on most newer kernels.

**Comment by ksf** [comment]
It's 4.4.23, which is the default for flounder.

**Comment by vcunat** [comment]
The same stack trace as https://github.com/NixOS/nixpkgs/issues/15988.
