### ISSUE TITLE
authentik

### ISSUE THREAD

**Issue by ibizaman** [NixOS/nixpkgs#194033]
**Project description**
_describe the project a little_

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by mweinelt** [comment]
How did you consider this completed? Did your interest vanish or did you find a packages somewhere?

**Comment by ibizaman** [comment]
The former, lack of interest.

**Comment by jvanbruegge** [comment]
I've managed to package it now: https://github.com/NixOS/nixpkgs/pull/271885
