### ISSUE TITLE
openrazer-daemon: Move application out of python package set

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#194095]
The python package set is for libraries only, packages that are only applications should be moved elsewhere in the tree. The openrazer library can stay in the package set and reuse the source from the application package, if necessary.

See https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#buildpythonapplication-function-buildpythonapplication-function.

cc @evanjs @roelvandijk @Lucus16

**Comment by TheOPtimal** [comment]
yup, my configuration has stopped builing because of this

**Comment by dywedir** [comment]
@TheOPtimal this should be fixed by #198358

**Comment by mweinelt** [comment]
No, it isn't.

**Comment by dywedir** [comment]
@mweinelt I was referring specifically to the build issue (sorry if that wasn't clear), which seems to be fixed. Please let me know if I'm wrong.

**Comment by SuperSandro2000** [comment]
It is technically used as a library in openrazer-pylib

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/openrazer/pylib.nix

**Comment by mweinelt** [comment]
Alright, thanks for digging up what the maintainers couldn't.
