### ISSUE TITLE
Add mkDefault to environment.etc.issue

### ISSUE THREAD

**Issue by the-argus** [NixOS/nixpkgs#194098]
## Issue description
I would like to be able to customize ``/etc/issue``. Adding mkDefault to its definition [https://github.com/NixOS/nixpkgs/blob/50f9b3107a09ed35bbf3f9ab36ad2683619debd2/nixos/modules/services/ttys/getty.nix#L149](https://github.com/NixOS/nixpkgs/blob/50f9b3107a09ed35bbf3f9ab36ad2683619debd2/nixos/modules/services/ttys/getty.nix#L149)
would allow for that.

**Comment by Kranzes** [comment]
Why don't you create a PR for that as it seems like you know what needs to be done? :^) In the meantime, just `mkForce` it.

**Comment by the-argus** [comment]
forgot to close this.
