### ISSUE TITLE
proposal: use netcat-openbsd as default netcat and remove netcat as a default package

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#19411]
The reason for switching over to BSD netcat is that the GNU netcat does not support IPv6. I found this very surprising because it would dial on IPv4 localhost while my application was listening on IPv6 localhost.

Also, I don't think this should be a default package because I don't think anything else that is default depends on it. If anyone wants it, they can easily install it.

**Comment by NeQuissimus** [comment]
I would second this, I have run into the same thing. And since we already have `netcat-openbsd`, a switch of defaults should be trivial.

**Comment by Mic92** [comment]
So `netcat` becomes `gnu-netcat` and `netcat-openbsd` becomes `netcat`.

**Comment by nhooyr** [comment]
Exactly.

**Comment by sternenseemann** [comment]
I will implement this.

**Comment by CMCDragonkai** [comment]
GNU Netcat also doesn't support unix domain sockets.

**Comment by sternenseemann** [comment]
PR was merged. Close?
