### ISSUE TITLE
Generic Colourizer

### ISSUE THREAD

**Issue by PowerUser64** [NixOS/nixpkgs#194131]
**Project description**
Generic Colourizer (`grc`) is a command-line program that colourizes the output of various command-line programs using regular expressions. `grc` can highlight the outputs of a variety of programs, including `gcc`, `make`, `ping`, `du`, `curl`, and much more. A complete list of supported programs and configuration examples can be found at https://github.com/garabik/grc/tree/master/colourfiles. It also includes optional shell aliases to automatically add color to the outputs of supported programs.

**Metadata**

* homepage URL: http://kassiopeia.juls.savba.sk/~garabik/software/grc.html
* source URL: https://github.com/garabik/grc
* license: gpl2
* platforms: linux

**Comment by imsofi** [comment]
Generic colourizer is currently already packaged in nixpkgs, under the name `grc`.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/misc/grc/default.nix

**Comment by PowerUser64** [comment]
Oops! Guess I missed it somehow. Thanks!

**Comment by imsofi** [comment]
You may need to source it in your bashrc/zshrc. With nix profiles it would be for example `source ~/.nix-profile/etc/grc.zsh`. You can also use `which grc` and look for where the `../etc/grc.zsh` would be on your system.

**Comment by PowerUser64** [comment]
Yeah, I missed that it was in the repo. I went to https://search.nixos.org/packages and searched for 'grc' and it was not there. I guess I must have miss-typed it or something because I see it there now. Sorry for the bogus request!

**Comment by imsofi** [comment]
Yeah its no problem at all. Its a good package you requested. :+1:
Hope you get it working!

**Comment by PowerUser64** [comment]
Thanks! :grin:
