### ISSUE TITLE
Update facetimehd for 4.8

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#19410]
The facetimehd kernel driver for 16.09 doesn't compile on the 4.8 series kernel. An upstream fix is available, see: https://github.com/patjak/bcwc_pcie/issues/92

We should update master to `mainline`, and backport the patch somehow to 16.09.

**Comment by womfoo** [comment]
Thanks for working on the fix. Haven't hit any issues in 4.8 so far.

I'm also in favor or switching to mainline but I couldn't find anything upstream that mentions deprecating their master branch. Any sources?

**Comment by grahamc** [comment]
This was resolved a while ago.
