### ISSUE TITLE
simple-scan has no icons in toolbar

### ISSUE THREAD

**Issue by timor** [NixOS/nixpkgs#19423]
## Issue description
Installed simple-scan. There are only place-holder icons in the toolbar.

### Steps to reproduce
`nix-env -i simple-scan`
run `simple-scan`

look at toolbar with only place-holder icons
## Technical details

* System: NixOS: 16.09.git.e47a15a
* Nix version:nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.git.e47a15a"

**Comment by NeQuissimus** [comment]
What is your window manager?

**Comment by timor** [comment]
I am using Enlightenment (e19).

**Comment by peterhoeg** [comment]
@timor, do you mind confirming that this works?

**Comment by timor** [comment]
@peterhoeg:
Yes, it works. Thank you very much.
