### ISSUE TITLE
python module tensorflow-bin

### ISSUE THREAD

**Issue by PlumpMath** [NixOS/nixpkgs#194217]
error: builder for '/nix/store/nvcrjrjlamyhkadqa8f35kgrz1932gxw-python3.10-tensorflow-2.9.1.drv' failed with exit code 1;
       last 10 log lines:
       > Processing ./tensorflow_cpu-2.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
       > Requirement already satisfied: six>=1.12.0 in /nix/store/qb8l07yw65mhmnvffvcn3sj0dnp7jww1-python3.10-six-1.16.0/lib/python3.10/site-packages (from tensorflow-cpu==2.9.1) (1.16.0)
       > Requirement already satisfied: termcolor>=1.1.0 in /nix/store/q685b9rgwpscrg4gdkc3j6wygsl9c1bd-python3.10-termcolor-2.0.1/lib/python3.10/site-packages (from tensorflow-cpu==2.9.1) (2.0.1)
       > Requirement already satisfied: numpy>=1.20 in /nix/store/im3vjpskp1ismclgasz8466klyjiz0sr-python3.10-numpy-1.23.3/lib/python3.10/site-packages (from tensorflow-cpu==2.9.1) (1.23.3)
       > Requirement already satisfied: grpcio<2.0,>=1.24.3 in /nix/store/kd0sy48r02vgpbmqd9nj0gn3765i0g0z-python3.10-grpcio-1.48.1/lib/python3.10/site-packages (from tensorflow-cpu==2.9.1) (1.48.1)
       > Requirement already satisfied: setuptools in /nix/store/3jb3dgp57429y07my17hnhbd5q9f1rm8-python3.10-setuptools-65.3.0/lib/python3.10/site-packages (from tensorflow-cpu==2.9.1) (65.3.0.post0)
       > Requirement already satisfied: typing-extensions>=3.6.6 in /nix/store/cyw1g8k4cx9sbhcriyrmn1cjpp3qk7wv-python3.10-typing-extensions-4.3.0/lib/python3.10/site-packages (from tensorflow-cpu==2.9.1) (4.3.0)
       > ERROR: Could not find a version that satisfies the requirement tensorboard<2.10,>=2.9 (from tensorflow-cpu) (from versions: none)
       > ERROR: No matching distribution found for tensorboard<2.10,>=2.9
       >
       For full logs, run 'nix log /nix/store/nvcrjrjlamyhkadqa8f35kgrz1932gxw-python3.10-tensorflow-2.9.1.drv'.
error: 1 dependencies of derivation '/nix/store/6nplv3x96ss068x75yw5k0ypypm3rfck-python3-3.10.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hcr62717yy3rbyqqiwznrlpxypbijivx-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jvcb0wmmydsp2axw2snmwp0v9m3hqnv4-nixos-system-gram-22.11.20221003.5f53dac.drv' failed to build

**Comment by PlumpMath** [comment]
$ nix log /nix/store/nvcrjrjlamyhkadqa8f35kgrz1932gxw-python3.10-tensorflow-2.9.1.drv
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing wheel setup hook
Using wheelUnpackPhase
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
Executing wheelUnpackPhase
Finished executing wheelUnpackPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
/tmp/nix-build-python3.10-tensorflow-2.9.1.drv-0/dist /tmp/nix-build-python3.10-tensorflow-2.9.1.drv-0
Unpacking to: unpacked/tensorflow_cpu-2.9.1...OK
Repacking wheel as ./tensorflow_cpu-2.9.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl...OK
/tmp/nix-build-python3.10-tensorflow-2.9.1.drv-0
no configure script, doing nothing
configurePhase completed in 1 minutes 15 seconds
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Executing pipInstallPhase
/tmp/nix-build-python3.10-tensorflow-2.9.1.drv-0/dist /tmp/nix-build-python3.10-tensorflow-2.9.1.drv-0
Processing ./tensorflow_cpu-2.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Requirement already satisfied: six>=1.12.0 in /nix/store/qb8l07yw65mhmnvffvcn3sj0dnp7jww1-python3.10-six-1.16.0/lib/python3.10/site-packages (from tensorflo>
Requirement already satisfied: termcolor>=1.1.0 in /nix/store/q685b9rgwpscrg4gdkc3j6wygsl9c1bd-python3.10-termcolor-2.0.1/lib/python3.10/site-packages (from>
Requirement already satisfied: numpy>=1.20 in /nix/store/im3vjpskp1ismclgasz8466klyjiz0sr-python3.10-numpy-1.23.3/lib/python3.10/site-packages (from tensorf>
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /nix/store/kd0sy48r02vgpbmqd9nj0gn3765i0g0z-python3.10-grpcio-1.48.1/lib/python3.10/site-packages (fro>
Requirement already satisfied: setuptools in /nix/store/3jb3dgp57429y07my17hnhbd5q9f1rm8-python3.10-setuptools-65.3.0/lib/python3.10/site-packages (from ten>
Requirement already satisfied: typing-extensions>=3.6.6 in /nix/store/cyw1g8k4cx9sbhcriyrmn1cjpp3qk7wv-python3.10-typing-extensions-4.3.0/lib/python3.10/sit>
ERROR: Could not find a version that satisfies the requirement tensorboard<2.10,>=2.9 (from tensorflow-cpu) (from versions: none)
ERROR: No matching distribution found for tensorboard<2.10,>=2.9

**Comment by FRidh** [comment]
Please use the provided template when opening an issue.

We might want to revert the tensorboard upgrade made in f256380dc2d3ad45f2d7bee8ca7cfc4fa89df675 but it is up to the maintainers to decide.

**Comment by PlumpMath** [comment]
@FRidh Again I will try to register as a maintainer, so please do it. (I don't know how to use git and it's annoying, haha I have to watch the ms staff uncle's utop lecture again and follow it.)
 I will do my best to report bugs. In my life, there is only dev pleasure nix.

**Comment by PlumpMath** [comment]
error: builder for '/nix/store/cd3j3ilh7zfb4arxymc2gyf1h3l0w7rn-tensorflow-2.10.0-deps.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       > INFO: 0 processes.
       > Analyzing: 2 targets (288 packages loaded, 4563 targets configured)
       >     currently loading: @local_config_rocm//rocm
       > FAILED: Build did NOT complete successfully (288 packages loaded, 4563 targets\
       >  configured)
       >     currently loading: @local_config_rocm//rocm
       > FAILED: Build did NOT complete successfully (288 packages loaded, 4563 targets\
       >  configured)
       >     currently loading: @local_config_rocm//rocm
       >
       For full logs, run 'nix log /nix/store/cd3j3ilh7zfb4arxymc2gyf1h3l0w7rn-tensorflow-2.10.0-deps.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/b0xavx8sl1abns5kwdny3mscahdqmp9d-tensorflow-2.10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zfmr1smlyrm3plcwv3vzqlkxmfmmspdx-python3.10-tensorflow-2.10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r487r9slxbv6yxbszwkvvajyjw503465-python3-3.10.7-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/n12il73h96rc28baif56j517wlckpjli-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/z065vy58528a7zswgi5h3y7r2ns3fmky-darwin-system-22.11.20221004.d51fd78+darwin4.02d2551.drv' failed to build
Already up-to-date.

**Comment by PlumpMath** [comment]
I just downloaded the stable nixpkgs version and the build was successful.
