### ISSUE TITLE
SuperSlicer

### ISSUE THREAD

**Issue by MohrJonas** [NixOS/nixpkgs#194229]
**Project description**
SuperSlicer is a fork of PrusaSlicer, a slicer for 3d-printing, with advanced features.

**Metadata**

* homepage URL: https://github.com/supermerill/SuperSlicer
* source URL: https://github.com/supermerill/SuperSlicer
* license: AGPL-3.0
* platforms: linux, darwin

**Comment by newAM** [comment]
This is already packaged: https://search.nixos.org/packages?channel=22.05&show=super-slicer&from=0&size=50&sort=relevance&type=packages&query=super-slicer

**Comment by MohrJonas** [comment]
Sorry, didn't see that.
Thanks
