### ISSUE TITLE
Rust update to 1.12.0

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19428]
## Issue description
Updating the Rust derivation to 1.12.0 is a pain for me :D
I tried but got stuck after updating versions and hashes with the following

```
src/libcore/lib.rs:87:1: 87:24 error: #[feature] may not be used on the stable release channel
src/libcore/lib.rs:87 #![feature(staged_api)]
                      ^~~~~~~~~~~~~~~~~~~~~~~
src/libcore/lib.rs:88:1: 88:30 error: #[feature] may not be used on the stable release channel
src/libcore/lib.rs:88 #![feature(unboxed_closures)]
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/libcore/lib.rs:89:1: 89:27 error: #[feature] may not be used on the stable release channel
src/libcore/lib.rs:89 #![feature(question_mark)]
```

I was going to try out Rust and figured I could easily update to the latest stable release and use that then, but that did not work out :D

I have no idea what is going on here, I am pulling 1.12.0, which is stable, why would it try to use features that are not allowed?

@the-kenny @Ericson2314 @dvc94ch seem to be some of the people that know Rust :)

**Comment by the-kenny** [comment]
You likely need to update the bootstrap-binaries (in `bootstrap.nix`) too. Rust stable is bootstrapped from the previous stable version and uses a hack (a secret key) to enable nightly-features in the stable-compiler. If the secret key doesn't match, you get error messages exactly like this.

**Comment by NeQuissimus** [comment]
I'm going to build both rustc and cargo. The build seems to take a long time, though :D
