### ISSUE TITLE
zfs-2.1.6

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#194311]
###### Checklist

https://github.com/openzfs/zfs/releases/tag/zfs-2.1.6

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 2.1.5
desired version: 2.1.6

###### Notify maintainers

maintainers: @hmenke @jcumming @wizeman @globin @jonringer 

###### Note for maintainers

Please tag this issue in your merge request.

The kernel version needs to be bumped to 5.19.x. It's not ready for 6.0.x.

**Comment by SamLukeYes** [comment]
Resolved in https://github.com/NixOS/nixpkgs/pull/194405

**Comment by mainrs** [comment]
Anyway I can track when this hits nixpkgs? either unstable or a stable release branch?
