### ISSUE TITLE
python310Packages.wxPython_4_1 fails to build

### ISSUE THREAD

**Issue by wentasah** [NixOS/nixpkgs#194354]
### Steps To Reproduce
1. build *python310Packages.wxPython_4_1*

### Build log
```
@nix { "action": "setPhase", "phase": "pythonOutputDistPhase" }
pythonOutputDistPhase
Executing pythonOutputDistPhase
mv: cannot stat 'dist': No such file or directory
```

### Additional context

I think that this is caused by #190487. @FRidh Can you suggest a fix?

I'd prefer fixing the package rather than marking it broken (#193811).

### Notify maintainers

@tfmoraes

### Metadata

nixpkgs 22.05-pre-80690-gfd54651f5ff

**Comment by superherointj** [comment]
> I'd prefer fixing the package rather than marking it broken (#193811).

Ideally we should mark package as broken (while it is broken) to avoid false positives in upstream builds.
Anyone fixing it can remove the broken mark. There is no gain from delaying marking broken a package that is known to be broken already.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/pull/194404
