### ISSUE TITLE
`nixopsUnstable` does not build on `x86_64-darwin` because of `zfs-user-2.1.5`

### ISSUE THREAD

**Issue by ethnt** [NixOS/nixpkgs#194333]
### Steps To Reproduce

I made a [repository that can reproduce the issue](https://github.com/ethnt/nixops-build-failure).

### Build log
```
❯ nix build .#nixops_unstable
error: Package ‘zfs-user-2.1.5’ in /nix/store/7vr1ir078ybxzqg85ndc0b0cfdxizrcn-source/pkgs/os-specific/linux/zfs/default.nix:196 is not supported on ‘x86_64-darwin’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

I _think_ the issue is with `libvirtd`, but I can't prove it unfortunately.

### Notify maintainers

@roberth

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.34 MiB download, 2.06 MiB unpacked):
  /nix/store/nsikv84v16n9dgmfnmpr5fc572nhfs1y-bash-interactive-5.1-p12-dev
  /nix/store/z7r4pl0q7kvqjgd87zc60jj4b4djhn4h-bash-interactive-5.1-p12-doc
copying path '/nix/store/z7r4pl0q7kvqjgd87zc60jj4b4djhn4h-bash-interactive-5.1-p12-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/nsikv84v16n9dgmfnmpr5fc572nhfs1y-bash-interactive-5.1-p12-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixpkgs"`
 - channels(ethan): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by roberth** [comment]
You were correct about `python3Packages.libvirt`, see #194439. There's a second build problem though, involving missing `setuptools` dependencies. This may be the same problem that blocked #193552; not sure how to proceed.

**Comment by ethnt** [comment]
@roberth Ah, that makes sense to me. I also ran into that second issue with `setuptools` when I tried to build `nixops` without the `libvirt` plugin. Unfortunate that we'll need to wait for a new release of `poetry2nix`!

**Comment by mweinelt** [comment]
Python packages need to add `setuptools` into `nativeBuildInputs` since 8895944c571bb37800e7c4641f2495dc21d0ed68. Poetry2nix does not seem to account for that yet.

**Comment by roberth** [comment]
They're already aware of the problem (in https://github.com/nix-community/poetry2nix/pull/736). I don't know how far along they are. Maybe they could use some help with identifying new overrides that `nixops_unstable` happens to need for its deps.

**Comment by cpcloud** [comment]
I think the fix for adding setuptools is pretty much done in poetry2nix (cc @K900), but there's a long tail of packages that will stop working because they depend on setuptools, and aren't yet packaged up in `nixpkgs`.

**Comment by cpcloud** [comment]
@ethnt If you want to dump a list somewhere on the poetry2nix issue tracker then that would be helpful. If you want to do a PR there that'd also be very welcome!

**Comment by roberth** [comment]
@K900 has repackaged it without poetry2nix, and after #292099 it builds on x86_64-darwin.
