### ISSUE TITLE
Update btsync to resilio

### ISSUE THREAD

**Issue by apeyroux** [NixOS/nixpkgs#19436]
BitTorrent Sync (btsync) change to resilio https://www.resilio.com/. 
- We keep the old btsync?
- We are creating a new package or is it just a new version of btsync?

**Comment by joachifm** [comment]
cc btsync maintainers @thoughtpolice @domenkozar

**Comment by thoughtpolice** [comment]
Resilio Sync is still fully compatible with BitTorrent Sync. So we can just change the expression name, rename `bittorrentSync = resilioSync` in `all-packages.nix` and I think that should take care of it just fine.

We might still have the old 1.x BTSync package though. We should probably nuke it as part of this, too.

**Comment by jeremejevs** [comment]
What's the progress on this?

**Comment by joachifm** [comment]
@jeremejevs  Just waiting for somebody to make a PR, I think
