### ISSUE TITLE
GHCJS builds on NixOS-16.09 but is marked as broken

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#19443]
@peti I just installed GHCJS on a recent nixos-16.09 using `{ allowBroken = true; }` and it succeeds to build:

```
nix-build -A haskell.compiler.ghcjs                    
/nix/store/kcwpwm0jl9sm33pvawp581a53s5lg8q4-ghcjs-0.2.0
```

So I think https://github.com/NixOS/nixpkgs/commit/8f07d4bd780a24dcf33be46d8cbfc6163fcdde0e can be reverted.

**Comment by joachifm** [comment]
Fixed by 56d033ac1b00a8b29bc29589312d2f5024656bd3
