### ISSUE TITLE
cmake 2.8.12

### ISSUE THREAD

**Issue by aryeh-looker** [NixOS/nixpkgs#194513]
**Project description**
CMake is an open-source, cross-platform family of tools designed to build, test and package software. CMake is used to control the software compilation process using simple platform and compiler independent configuration files, and generate native makefiles and workspaces that can be used in the compiler environment of your choice. The suite of CMake tools were created by Kitware in response to the need for a powerful, cross-platform build environment for open-source projects such as ITK and VTK.

**More info**
Support for cmake 2.8.12 and lower is being deprecated; thus having an older release available would allow for compilation of older packages

```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Metadata**

* homepage URL: https://cmake.org/
* source URL: https://cmake.org/download/
* license: BSD 3-clause
* platforms: linux amd64/x86_64

**Comment by NickCao** [comment]
Is there any specific ETA for this *future* version? If that is not an immediate problem, we can try to port these old software to newer versions of cmake in the meantime instead.
