### ISSUE TITLE
gnomeExtensions.tophat not working

### ISSUE THREAD

**Issue by icyrockcom** [NixOS/nixpkgs#194524]
### Describe the bug

`gnomeExtensions.tophat` installs, but doesn't work. It shows the no-entry-permitted icon and the error message when clicking:

```
Something went wrong while starting TopHat

It looks like your computer is missing GIRepository (gir) bindings for the following libraries: GTop

Error details

Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
```

### Steps To Reproduce
1. Add `pkgs.gnomeExtensions.tophat` to `environment.systemPackages` in `configuration.nix`
2. Log out / log in
 
### Expected behavior
It should work.

### Screenshots
Error message:

![image](https://user-images.githubusercontent.com/785140/193954914-1157b191-b964-4d36-a610-991696c5ce47.png)

### Additional context

Using flakes for configuration management.

### Notify maintainers

@piegamesde 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.11 (Raccoon), 22.11.20220926.62228cc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by not-my-segfault** [comment]
The following addition to my `configuration.nix` has worked for me on Xorg, but not on Wayland:

```
services.xserver.desktopManager.gnome.sessionPath = [ 
  pkgs.libgtop
];
```
(via https://github.com/NixOS/nixpkgs/issues/30022#issuecomment-334570296)

**Comment by piegamesde** [comment]
The already packaged extension system-monitor also uses Gtop, so looking at that might be a good point to start. In the patches that we apply, I see

```diff
diff --git a/system-monitor@paradoxxx.zero.gmail.com/extension.js b/system-monitor@paradoxxx.zero.gmail.com/extension.js
index de5e3d7..2d7824d 100644
--- a/system-monitor@paradoxxx.zero.gmail.com/extension.js
+++ b/system-monitor@paradoxxx.zero.gmail.com/extension.js
@@ -18,6 +18,9 @@
 
 // Author: Florian Mounier aka paradoxxxzero
 
+imports.gi.GIRepository.Repository.prepend_search_path('@gtop_path@');
```

**Comment by boustanihani** [comment]
> The following addition to my `configuration.nix` has worked for me on Xorg, but not on Wayland:
> 
> ```
> services.xserver.desktopManager.gnome.sessionPath = [ 
>   pkgs.libgtop
> ];
> ```
> 
> (via [#30022 (comment)](https://github.com/NixOS/nixpkgs/issues/30022#issuecomment-334570296))

Doing this results in a new error:
`Gio.IOErrorEnum: Fehler beim Holen der Informationen für Datei »/usr/local«: No such file or directory`
