### ISSUE TITLE
Packaging Request: Lokinet

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#194593]
**Project description**
Lokinet is the reference implementation of LLARP (low latency anonymous routing protocol), a layer 3 onion routing protocol. The relay node is backed by proof of stake blockchain that will act as an incentivizer for the node owner to keep it stable and alive. 

**Metadata**

* homepage URL: https://lokinet.org/
* source URL: https://github.com/oxen-io/lokinet
* license: GPLv3
* platforms: Linux

**Comment by wyndon** [comment]
It's present in unstable. There's also a module.
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=lokinet
https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=lokinet

**Comment by tengkuizdihar** [comment]
thank you! I thought there isn't one because I searched in the packages
instead of options
