### ISSUE TITLE
Upgrade default gcc to 6.x

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#19456]
Title says all. This will be nice to have for 17.03.

We should set up a branch+jobset with gcc 6 to see how much breaks.

http://hydra.nixos.org/jobset/nixos/gcc-6

**Comment by copumpkin** [comment]
Out of curiosity, why not LLVM+clang? Are there any major blockers for that left nowadays?

**Comment by edolstra** [comment]
That's a separate issue really.

**Comment by groxxda** [comment]
Do we really need a separate branch with all the merge work it implies?
Wouldn't it be possible to only have a jobset that overrides `gcc = gcc6` but uses `master`?

If we _fix_ a package for gcc6, it should not break gcc5.

**Comment by vcunat** [comment]
I don't think it will need much "merge work".

**Comment by vcunat** [comment]
There's a new problem with `-isystem`: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/Q5SWCUUMWQ4EMS7CU2CBOZHV3WZYOOTT/

On Hydra it currently shows up with [openjdk](http://hydra.nixos.org/build/42228686/nixlog/36/raw) but I've already seen another instance.

**Comment by domenkozar** [comment]
How far is this work?

**Comment by vcunat** [comment]
In this branch I can't see any commits towards fixing the general problem from my last comment (and I didn't work on it since posting that comment).

**Comment by vcunat** [comment]
Hmm, I guess we might skip gcc-6 default, as gcc-7 is [expected in about a month](https://gcc.gnu.org/ml/gcc/2017-03/msg00066.html).  We've done at least one similar leap already, some time with 5.x.

**Comment by copumpkin** [comment]
Looks like gcc 7 is out. Anyone still looking at this?

**Comment by edolstra** [comment]
Yes, I am. GCC 7 is probably too bleeding edge for the next release, so GCC 6 would be better. I'd like to merge the gcc-6 branch into staging soon.

**Comment by copumpkin** [comment]
Awesome, thanks!

**Comment by vcunat** [comment]
GCC 7.1 is from May and the next release is in September, so it might not be that bad, but it seems safer and perfectly OK to wait after that.

**Comment by edolstra** [comment]
FYI, I've changed the nixos/gcc-6 jobset (as well as the nixos/staging jobset) to build on x86_64-linux only. Otherwise evaluation kept barfing with a Boehm out-of-memory error. (No idea why, given that master does evaluate...)

http://hydra.nixos.org/eval/1378105

The last eval (from > a month ago) showed only a handful of major failing dependencies (mostly clucene-core and akonadi, breaking a lot of KDE, and gnome-control-center, breaking some of Gnome). So I think we should fix those and then merge this into staging in a few days. Remaining failures can be dealt with as part of a ZHF push for 17.09.

@fpletz

**Comment by vcunat** [comment]
@edolstra: any particular reason why you haven't staged this yet?

**Comment by edolstra** [comment]
@vcunat Sorry, I've been on vacation. I've merged gcc-6 into staging now.

**Comment by fpletz** [comment]
Thanks!
