### ISSUE TITLE
[android-sdk] Trying to run an AVD results in a permission denied error (qemu needs RW?)

### ISSUE THREAD

**Issue by michalrus** [NixOS/nixpkgs#19452]
## Issue description

After installing the Android SDK and trying to run an AVD, I’m getting:

> Starting emulator for AVD 'AVD_for_Nexus_4_by_Google'
> 
> qemu-system-x86_64: -drive if=none,index=0,id=system,file=/nix/store/r9y9lgc5gjzf2ryhxv39zx6ngyprpj8n-android-sdk-25.2.2/libexec/system-images/android-21/x86_64//system.img: could not open disk image /nix/store/r9y9lgc5gjzf2ryhxv39zx6ngyprpj8n-android-sdk-25.2.2/libexec/system-images/android-21/x86_64//system.img: Could not open '/nix/store/r9y9lgc5gjzf2ryhxv39zx6ngyprpj8n-android-sdk-25.2.2/libexec/system-images/android-21/x86_64//system.img': Permission denied

The `system.img` file has `-r--r--r--` permissions, as expected in `/nix/store`.

Some people suggest, that it has to be writable (?!):
1. > ­QEMU must have write permissions to the disk image, otherwise it complains with "Permission denied" error. The solution is to mark the file writable — https://serverfault.com/a/525977
2. > You should make sure that one of those folders are NOT read-only. — https://stackoverflow.com/a/39777377

**This seems not true to me, as I was able to run the emulator without problems before—on NixOS!**
### Steps to reproduce
1. Install `androidsdk`.
2. Run `android`.
3. Choose Tools → Manage AVDs → Device Definitions → choose any device → Create Device.
4. Switch back to Android Virtual Devices tab, select the device and press Start.
## Technical details
- System: 16.09.680.4e14fd5 (Flounder)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: "16.09.733.246c937"

---

/cc @taku0 @svanderburg

**Comment by taku0** [comment]
Reproduced. I could start emulator before, but I cannot start it now.

For manual invocation of emulators from a terminal, we can specify a writable image with `-system` option, but can we work around this issue with AVD Manager?

**Comment by Profpatsch** [comment]
(triage) can you still reproduce?

**Comment by michalrus** [comment]
I don’t know, stopped using it.
