### ISSUE TITLE
tailscale module: warning about strict reverse path filtering should be disable-able

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#194623]
### Describe the bug

I really appreciate this message, but also would like to be able to disable it. Most of my Tailscale machines are not exit nodes, nor do they act as subnet routers, hence I would prefer to leave strict filtering enabled and also not have these warnings.

It seems like a small thing, but these warnings tend to make me blind to other new, more relevant warnings.

```
trace: warning: Strict reverse path filtering breaks Tailscale exit node use and some subnet routing setups. Consider setting `networking.firewall.checkReversePath` = 'loose'
```

I'm hacking on something here: https://github.com/colemickens/nixpkgs/tree/tailscale-path-warning

**Comment by LunNova** [comment]
Thanks for raising this, have been ignoring this issue for ages and meaning to try to do something about it but never got around to it :sweat_smile:
