### ISSUE TITLE
pcre doesn't build with PaX

### ISSUE THREAD

**Issue by yotann** [NixOS/nixpkgs#19468]
## Issue description

When `pcre` is built on a system with PaX enabled, the build fails in the `make check` step. It appears `make check` builds a couple of executables to test the JIT, but they fail to run because they don't have PaX exceptions.
### Steps to reproduce
- Be on any system with PaX enabled
- Run `nix-build '<nixpkgs>' -A pcre` without using a cached copy of `pcre`
## Technical details
- System: NixOS 17.03pre92039.adfcc2d; also occurs on Arch Linux
- Nix version: 1.11.4
- Nixpkgs version: 17.03pre92039.adfcc2d; also occurs with master
### dmesg

```
[ 1131.778500] grsec: denied RWX mmap of <anonymous mapping> by /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcre_jit_test[lt-pcre_jit_tes:6400] uid/euid:30001/30001 gid/egid:30000/30000, parent /nix/store/d1prcspbh2qsviipvnaxizcj8l3g7fpw-bootstrap-tools/bin/bash[bash:6399] uid/euid:30001/30001 gid/egid:30000/30000
[ 1131.789606] lt-pcre_jit_tes[6400]: segfault at 28 ip 000003b08de71008 sp 000003f9f9da4310 error 4 in libc-2.24.so[3b08ddfa000+195000]
[ 1131.789626] grsec: Segmentation fault occurred at 0000000000000028 in /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcre_jit_test[lt-pcre_jit_tes:6400] uid/euid:30001/30001 gid/egid:30000/30000, parent /nix/store/d1prcspbh2qsviipvnaxizcj8l3g7fpw-bootstrap-tools/bin/bash[bash:6399] uid/euid:30001/30001 gid/egid:30000/30000
[ 1131.797761] grsec: denied resource overstep by requesting 4096 for RLIMIT_CORE against limit 0 for /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcre_jit_test[lt-pcre_jit_tes:6400] uid/euid:30001/30001 gid/egid:30000/30000, parent /nix/store/d1prcspbh2qsviipvnaxizcj8l3g7fpw-bootstrap-tools/bin/bash[bash:6399] uid/euid:30001/30001 gid/egid:30000/30000
[ 1132.248233] grsec: denied RWX mmap of <anonymous mapping> by /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcretest[lt-pcretest:6606] uid/euid:30001/30001 gid/egid:30000/30000, parent /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/RunTest[RunTest:6441] uid/euid:30001/30001 gid/egid:30000/30000
[ 1132.261474] grsec: denied RWX mmap of <anonymous mapping> by /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcretest[lt-pcretest:6606] uid/euid:30001/30001 gid/egid:30000/30000, parent /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/RunTest[RunTest:6441] uid/euid:30001/30001 gid/egid:30000/30000
[ 1132.279115] grsec: denied RWX mmap of <anonymous mapping> by /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcretest[lt-pcretest:6606] uid/euid:30001/30001 gid/egid:30000/30000, parent /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/RunTest[RunTest:6441] uid/euid:30001/30001 gid/egid:30000/30000
[ 1132.287154] grsec: denied RWX mmap of <anonymous mapping> by /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/.libs/lt-pcretest[lt-pcretest:6606] uid/euid:30001/30001 gid/egid:30000/30000, parent /tmp/nix-build-pcre-8.38.drv-0/pcre-8.38/RunTest[RunTest:6441] uid/euid:30001/30001 gid/egid:30000/30000
[ 1132.295109] grsec: more alerts, logging disabled for 10 seconds
```
### Partial build output

```
make  check-TESTS
make[2]: Entering directory '/tmp/nix-build-pcre-8.38.drv-0/pcre-8.38'
make[3]: Entering directory '/tmp/nix-build-pcre-8.38.drv-0/pcre-8.38'
./test-driver: line 107:  5022 Segmentation fault      "$@" > $log_file 2>&1
FAIL: pcre_jit_test
FAIL: RunTest
PASS: RunGrepTest

...(output omitted)...

Test 12: JIT-specific features (when JIT is available)
--- ./testdata/testoutput12 2015-09-02 08:53:57.000000000 +0000
+++ testtry 2016-10-12 01:00:05.074522100 +0000
@@ -9,7 +9,7 @@
 Need char = 'c'
 Subject length lower bound = 3
 No starting char list
-JIT study was successful
+JIT study was not successful

...(output omitted)...

Makefile:2718: recipe for target 'check-TESTS' failed
```

**Comment by joachifm** [comment]
You can use `paxmark m` to disble `mprotect()` hardening for a given executable.

**Comment by joachifm** [comment]
I think the appropriate solution is to use an RBAC policy that disables certain PaX protections for nix build users. Patching packages to permit them to *build* on a grsec system does not seem worthwhile to me.

**Comment by yotann** [comment]
I disagree. Disabling PaX for nix build users could open security holes under certain circumstances. And extremely few packages will need PaX exceptions to build, but not to run—PCRE may even be the only one.

I'm planning to make a patch for this once I find the time.

**Comment by joachifm** [comment]
Can you elaborate on the security holes introduced by disabling `mprotect()` hardening for build users (assuming sandboxing is enabled, of course)?

**Comment by spacekitteh** [comment]
relevant https://github.com/NixOS/nixpkgs/pull/20964

**Comment by jeaye** [comment]
@spacekitteh's PR #20964 was closed, not merged. Has there been any other progress on this?

**Comment by vcunat** [comment]
No other progress, most likely.

**Comment by jeaye** [comment]
On Mon, Apr 10, 2017 at 08:49:05AM -0700, Vladimír Čunát wrote:
> No other progress, most likely.

That's unfortunate. PCRE is effectively broken for anyone running 17.03 with grsecurity = true, right? That seems like something that should be affecting a lot of people, so I'm surprised there isn't much activity on this issue.

**Comment by vcunat** [comment]
**Building it on** a PaX-enabled machine is broken, but not using it AFAIK, e.g. you should be able to just pull binaries from our binary cache.

**Comment by jeaye** [comment]
Oh, I see. I think I ended up here due to a related issue, which is my journal being spammed with:

```text
Apr 10 10:52:31 nixums kernel: grsec: From 50.168.44.39: denied RWX mmap of <anonymous mapping> by /nix/store/7gvylfn1mrxh2sc1r5vdh5sg4pyhfpx0-pcre-8.40-bin/bin/pcregrep[pcregrep:20602] uid/euid:0/0 gid/egid:0/0, parent /etc/admin/rejected-emails[rejected-emails:20600] uid/euid:0/0 gid/egid:0/0
```

I think this would be affecting anyone who pulled from the binary cache. In my case, I'm just running a script in cron and pcregrepis being denied an mmap each time.

**Comment by joachifm** [comment]
@jeaye you can patch the build to apply paxmark to the offending binary or just disable per-executable PaX outright if it's a problem for you.

**Comment by jeaye** [comment]
On Mon, Apr 10, 2017 at 01:46:28PM -0700, Joachim F. wrote:
> @jeaye you can patch the build to apply paxmark to the offending binary or just disable per-executable PaX outright if it's a problem for you.

Right. Wouldn't every NixOS user with grsecurity = true and PCRE installed have this issue?

**Comment by joachifm** [comment]
Not really ... I have never had any problems because of this.

**Comment by jeaye** [comment]
On Mon, Apr 10, 2017 at 03:24:07PM -0700, Joachim F. wrote:
> Not really ... I have never had any problems because of this.

To be very clear, are you saying that you get that warning in your journal, but it doesn't cause problems? Or are you saying that you've never seen this warning when using pcregrep with grsecurity enabled?

**Comment by joachifm** [comment]
I have seen the warning on occasion, never noticed any ill effects from it.

**Comment by yotann** [comment]
That warning happens because the PCRE library is trying to JIT-compile your regex, and grsecurity is preventing it from doing so. Fortunately, PCRE recovers from the error nicely and falls back to a non-JIT version, which works fine.

**Comment by joachifm** [comment]
grsecurity is no longer supported.
