### ISSUE TITLE
powerline-config tmux setup fails in 16.09 due to out-of-date powerline vs. new tmux

### ISSUE THREAD

**Issue by therealpxc** [NixOS/nixpkgs#19466]
## Issue description

If you use powerline with tmux, `powerline-config tmux setup` fails with a message about 'unknown option: status-utf8'. This is fixed in newer Powerline releases
### Steps to reproduce

Install powerline and tmux and run `powerline-config tmux setup` on NixOS 16.09 or newer, or from nixpkgs-16.09.
## Technical details
- System:16.09.git.6f41624
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: "16.09.git.6f41624"

**Comment by therealpxc** [comment]
The simple fix ([updating powerline](https://github.com/therealpxc/nixpkgs/commit/6f41624689c1511fe09884ce44a017a1e04593f4)) seems to work, but I haven't examined the fix to see if it causes other problems or misses some files in the new release or anything like that.

**Comment by NeQuissimus** [comment]
You are more than welcome to send in a pull request. And using `nox` you can verify all packages depending on your updated package (at least compile time).
