### ISSUE TITLE
julia-git miss libLLVM.so

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#19472]
## Issue description

If I add to a nix-shell environment julia-git, I can enter the environment but julia does not work.
### Steps to reproduce

Use this [nix-shell](https://gist.github.com/nico202/4aff0037f63993f871caa59bedaafe0d).
## Technical details

```
/nix/store/5izbllvwhvwawaqw23c82rbns5gd9fmg-julia-0.5.0-dev-2016-06-10/bin/julia: error while loading shared libraries: libLLVM-3.7.1.so: cannot open shared object file: No such file or directory
```
- System: 17.03pre92039.adfcc2d (Gorilla)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: "17.03pre92039.adfcc2d"

**Comment by nico202** [comment]
It's not "usabilty". It's broken even with nix-env -iA nixos.julia-git

**Comment by 7c6f434c** [comment]
A few magic passes and an upgrade made `julia-git` work in master. Upgrading `julia` to `0.5.0` is non-trivial for some reason (I did expect a combination between `0.4.6` and fresh `master` expressions to work, but no…)

**Comment by nico202** [comment]
julia-git seems now to be working, right? I think we can close this

**Comment by 7c6f434c** [comment]
I think in `master` both work right now.
