### ISSUE TITLE
Support for singularity-tools definition files

### ISSUE THREAD

**Issue by dmadisetti** [NixOS/nixpkgs#194789]
**Project description**
Currently singularity-tools (https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/singularity-tools/default.nix) supports a bare container with a script to run. It'd be nice if we could extend to the full definition file spec: https://docs.sylabs.io/guides/3.5/user-guide/definition_files.html

pinging relevant people: @jbedo, @cfhammill

**Comment by jbedo** [comment]
Do you have a particular motivation or use case we could think about? Definition files aren't useful for the way singularity-tools works as we build the container directly rather than having singularity do so. Most of what the definition files allow you to do is achievable with the root script.

**Comment by dmadisetti** [comment]
I just have existing definition files and though it would be nice to maintain consistency that way. Also this would allow for different build methods (say from a docker container)

**Comment by dmadisetti** [comment]
I think there's been movement on singularity, and I found a work around, so closing out
