### ISSUE TITLE
Many fetch options don't support proxies

### ISSUE THREAD

**Issue by Jookia** [NixOS/nixpkgs#19473]
## Issue description

Many fetch options so far don't support proxying using the http_proxy or https_proxy environment variables. So far only fetchurl, fetchsvn and git work using proxies but only when using http links. So things like bzr://, svn://, git:// or ftp:// don't work. GIT_PROXY_COMMAND breaks with sandboxing.
### Steps to reproduce

Set http_proxy and https_proxy to an appropriate proxy then try to build a package using a git://, svn:// or bzr:// source.
## Technical details
- System: NixOS based on a commit from 20160830.
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: 16.09.git.2a7929b (custom branch)
## Solutions

Let non-fetchurl builders use socat to forward the server and requested port to a local port then have the builders fetch from there.

Wrap non-fetchurl builders with proxychains. This is probably the easiest and cleanest solution and supports all kinds of proxies as well as being protocol independent.

**Comment by Profpatsch** [comment]
(triage) is this still the case?
