### ISSUE TITLE
Intltool refers to a broken URL

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#19487]
If you `nix-build -A intltool` on 7098404505003887b62cdee10ee74dfa56ead741, it barfs with

```
trying https://anonscm.debian.org/viewvc/pkg-gnome/desktop/unstable/intltool/debian/patches/perl5.22-regex-fixes?revision=47255&view=co
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

And indeed the URL fails. I'm not sure if it's a data loss issue on the upstream server (other revisions seem to still work fine) or when it broke, but this prevents common packages like `mesa` from building.

cc @7c6f434c

**Comment by copumpkin** [comment]
It actually looks like @vcunat added the patch in question: https://github.com/NixOS/nixpkgs/commit/117183e27e273f6c8c121b8281d06d07e9b502c2

**Comment by copumpkin** [comment]
Oh, it looks like someone renamed the file through history to add a .patch to its name, but somehow the historical version that @vcunat pulled in doesn't work even if I add a .patch to the URL.

**Comment by copumpkin** [comment]
Thanks @vcunat!

**Comment by jpierre03** [comment]
@vcunat @copumpkin @NeQuissimus it fails again : 
https://anonscm.debian.org/viewvc/pkg-gnome/desktop/unstable/intltool/debian/patches/perl5.22-regex-fixes?revision=47258&view=co -> HTTP 404

Correct url : 
 https://anonscm.debian.org/viewvc/pkg-gnome/desktop/unstable/intltool/debian/patches/perl5.22-regex-fixes.patch?revision=47258&view=co

(".patch" added)

Here on a non-official hydra build (run sucessfully on hydra.nixos.org) : 

checked with nixpkgs revision : 6189145

![image](https://cloud.githubusercontent.com/assets/954536/19831900/a2f00d6e-9e15-11e6-92af-b2e91d8b32d6.png)

**Comment by vcunat** [comment]
@jpierre03: right, I think I made a mistake due to our `fetchurl` preferring to use the binary cache instead of the actual URLs. Now it should *really* work.
