### ISSUE TITLE
dotnetCorePackages.combinePackages: fails with dotnet-sdk_6

### ISSUE THREAD

**Issue by Zylanx** [NixOS/nixpkgs#194867]
### Describe the bug
As of #194061 combinePackages fails when sdk_6_0 is added to the package list.  

The LICENSE.txt and ThirdPartyNotices.txt files are no longer in the root of the package as that derivation expects which breaks the build if sdk_6_0 is included.

### Steps To Reproduce
1. Add ```(with dotnetCorePackages; combinePackages [ sdk_6_0 sdk_3_1 ])``` to your packages or inputs.
2. Build

### Notify maintainers
Not sure who to notify
@mdarocha made the commit and is the last commit to be made

### Metadata
- system: `"x86_64-linux"`
 - host os: `Linux 5.19.12, NixOS, 22.11 (Raccoon), 22.11pre413974.59d2991d425`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixos-hardware"`
 - channels(zyl): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Zylanx** [comment]
I'm still not great at making issues. I hope this is the correct way to do it.
Thank you for your patience

**Comment by mdarocha** [comment]
I already have a fix :) https://github.com/NixOS/nixpkgs/pull/194797

**Comment by Zylanx** [comment]
Awesome, I didn't notice you already made the pull request.
Thank you!
