### ISSUE TITLE
Stop shipping Linux 5.19.12, may damage LCD displays

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixpkgs#194810]
### Describe the bug
Kernel 5.19.2 has potential to damage LCD displays
https://lore.kernel.org/all/YzwooNdMECzuI5+h@intel.com/

Please bump kernel 5.19 to use 5.19.13 or 5.19.14 and stop shipping 5.19.12 ASAP

### Steps To Reproduce
1. ...
2. ...
3. ...

### Notify maintainers

@Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Ma27** [comment]
5.19.14 is already out on master and release-22.05.
In fact, even `nixos-unstable` contains the fix already: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/kernel/linux-5.19.nix

The channel bump with the kernel update for 22.05 is in progress and finished as soon as https://hydra.nixos.org/build/193816017 has passed.

If you're using 22.05 and having that issue please downgrade either your kernel or your system. Alternatively, you can use a newer `kernelPackages` for `boot.kernelPackages` by importing it from a newer nixpkgs rev (i.e. not a channel).

Nothing actionable to do for the maintainers (for the record, I'm not the only kernel maintainer!), hence closing.
