### ISSUE TITLE
`hy` with `nix run` and packages which depend on `hy` cannot find `hy` binary

### ISSUE THREAD

**Issue by shadowrylander** [NixOS/nixpkgs#194988]
### Describe the bug
Using `nix run` with `hy` and any packages depending on `hy` results in the following error:
```console
error: unable to execute '/nix/store/[hash]-python3.9-hy-1.0a4/bin/hy': No such file or directory
```

However, packages not depending on `hy` work fine, as does running `nix develop` on packages depending on `hy` and entering the `repl` manually.

### Steps To Reproduce
1. Use the following flake:

```nix
{
    inputs = {
        nixpkgs.url = github:nixos/nixpkgs/nixos-22.05;
        flake-utils.url = github:numtide/flake-utils;
    };
    outputs = inputs@{ self, nixpkgs, flake-utils, ... }: with nixpkgs.lib; with flake-utils.lib; eachDefaultSystem (system: let
        mkApp = name: drv: { type = "app"; program = "${drv}${drv.passthru.exePath or "/bin/${drv.meta.mainprogram or drv.executable or drv.pname or drv.name or name}"}"; };
        pkgs = nixpkgs.legacyPackages.${system};
    in {
        packages = genAttrs [ "hyrule" "addict" ] (ppkg: pkgs.hy.withPackages (ppkgs: toList ppkgs.${ppkg}));
        app = mapAttrs mkApp packages;
        devShell = mapAttrs (n: v: pkgs.mkShell { buildInputs = toList v; }) packages;
    });
}
```

3. Run `nix run ".#hyrule" --show-trace` and `nix run ".#addict" --show-trace`
4. Observe that `hyrule` fails while `addict` succeeds.

### Expected behavior
To be dropped in a `hy repl` with packages depending on `hy`.

### Notify maintainers

@thiagokokada 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/bxda5g1plsd9y3cm2phyab8k3q9n9qnc-nix-info
copying path '/nix/store/bxda5g1plsd9y3cm2phyab8k3q9n9qnc-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.11, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.10.0pre20220706_f6316b4`
 - channels(shadowrylander): `"j"`
 - channels(root): `"j, nixos-21.11.336282.ed02c2ba038"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nagy** [comment]
While I could reproduce your case with nixos-22.05, on master, in both cases, I get dropped to a python shell, not a hy shell.

Here is a version of your flake that overrides the `meta.mainProgram` so that you land in a hy repl.

```nix
{
  # if we dont specify inputs, we take values out of the flake-registry
  outputs = { self, nixpkgs, flake-utils }:
    with nixpkgs.lib;
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in {
        packages = genAttrs [ "hyrule" "addict" ] (ppkg:
          (pkgs.hy.withPackages (ppkgs: [ ppkgs.${ppkg} ])).overrideAttrs
          (old: { meta = mergeAttrs old.meta { mainProgram = "hy"; }; }));
      });
}
```

But I think it would be better to put this into `hy.withPackages` eventually.

**Comment by shadowrylander** [comment]
I'd done that with `nixos-22.05`, but hadn't thought to do it with `master`; it works! Thanks! Should one of us submit a pull request?

**Comment by shadowrylander** [comment]
Or perhaps @thiagokokada would want to?

**Comment by thiagokokada** [comment]
> Or perhaps @thiagokokada would want to?

Not really, if you want to open a PR I can review/merge.

**Comment by shadowrylander** [comment]
Sorry, the instructions for contributing are a little confusing to me; could someone give me a summary of steps I need to take?

**Comment by shadowrylander** [comment]
Also, I just realized I don't know how to merge this with `withPackages`...

**Comment by shadowrylander** [comment]
And my own problem was fixed after changing the way the flake apps were made; thanks for all the help!
