### ISSUE TITLE
SSH host key changing on every boot

### ISSUE THREAD

**Issue by Baitinq** [NixOS/nixpkgs#195073]
### Describe the bug
Hi!

I have recently installed nixos on my raspberry pi 4B (aarch64-linux) and I have noticed that everytime I try to ssh to it its ssh host key has changed and i have to edit my known_hosts. After "debugging" it, I have confirmed that everytime the pi boots the ssh host key generation produces a new key.

This has not happend on any other of my nixos installations (all of them are x86_64-linux), so I am maybe wondering if this is a bug with any aarch64-linux nixpkgs/ssh implementation or its maybe a hardware specific issue with the pi 4B.

Thank you for your help!

### Steps To Reproduce
1. Install nixos-22.05 on aarch64-linux
2. Enable openssh server
3. Profit?

### Expected behavior
ssh host key stays the same across reboots

### Actual behaviour
ssh host key changes on each reboot

### Additional context
Running nixos 22.05 on the raspberry pi 4B
Configuration: https://github.com/baitinq/nixos-server

### Notify maintainers
@edolstra 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.20221001.9cac458`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by rapenne-s** [comment]
Is your root filesystem a tmpfs?

**Comment by mweinelt** [comment]
> Is your root filesystem a tmpfs?

This.

https://github.com/Baitinq/nixos-server/blob/587e04cb3a48d3e99f5ee15e225b1b5e831d99a1/hardware/pi/disks.nix#L53-L57

You don't have a persistent storage for the generated ssh keypair below /etc/ssh, so they vanish when you reboot.

**Comment by Baitinq** [comment]
Hi @rapenne-s @mweinelt , yes my / is a tmpfs. I figured this might be part of the issue but this doesnt happen on any other hosts which also have a tmpfs / (https://github.com/baitinq/nixos-config).

Do you have any idea of what could cause this different behaviour?

**Comment by rapenne-s** [comment]
You may want something like this

```
 environment.etc."ssh/ssh_host_rsa_key".source
    = "/nix/persist/etc/ssh/ssh_host_rsa_key";
  environment.etc."ssh/ssh_host_rsa_key.pub".source
    = "/nix/persist/etc/ssh/ssh_host_rsa_key.pub";
  environment.etc."ssh/ssh_host_ed25519_key".source
    = "/nix/persist/etc/ssh/ssh_host_ed25519_key";
  environment.etc."ssh/ssh_host_ed25519_key.pub".source
    = "/nix/persist/etc/ssh/ssh_host_ed25519_key.pub";
```
from https://elis.nu/blog/2020/05/nixos-tmpfs-as-root/

**Comment by Baitinq** [comment]
> You may want something like this

Thank you, I will try that asap.

Should I leave this issue open in case there is further info/research on what causes the different behavior between my hosts? I am still quite baffled by that.

**Comment by rnhmjoj** [comment]
If you have / on tmpfs you better be using some tool to diff the state before shutting down the system, otherwise you risk loosing data that hasn't been made persistent.
A simple solution is this:

```nix
{ lib, pkgs, ... }:

with lib;

let
  # Utility to save a snapshot of the root tree
  save-root = pkgs.writers.writeDashBin "save-root"
    ''
      ${pkgs.findutils}/bin/find \
        / -xdev \( -path /tmp -o -path /var/tmp -o -path /var/log/journal \) \
        -prune -false -o -print0 | sort -z | tr '\0' '\n' > "$1"
    '';

  # Utility to compare the root tree
  diff-root = pkgs.writers.writeDashBin "diff-root"
    ''
      export PATH=${with pkgs; makeBinPath [ diffutils less ]}:$PATH
      current="$(mktemp current-root.XXX --tmpdir)"
      trap 'rm "$current"' EXIT INT HUP
      ${save-root}/bin/save-root "$current"
      diff -u /run/initial-root "$current" --color=always | ''${PAGER:-less -R}
    '';

in

{
  environment.systemPackages = [ diff-root ];

  systemd.services.save-root-snapshot =
    { description = "save a snapshot of the initial root tree";
      wantedBy = [ "sysinit.target" ];
      requires = [ "-.mount" ];
      after = [ "-.mount" ];
      serviceConfig.Type = "oneshot";
      serviceConfig.RemainAfterExit = true;
      serviceConfig.ExecStart = ''${save-root}/bin/save-root /run/initial-root'';
    };

}
```

You can see a list of all files that have been created since boot with `sudo diff-root`.

**Comment by Baitinq** [comment]
> ```nix
> save-root
> ```

Thank you! Ill definitely implement that to my config.

**Comment by SuperSandro2000** [comment]
Closing since configuration error and all the questions where answered.
