### ISSUE TITLE
Package javacpp-presets

### ISSUE THREAD

**Issue by romildo** [NixOS/nixpkgs#19501]
I am developing a Java application with my compiler construction students. We are using LLVM to generate code in a toy compiler implemented in Java. For that we need the library [javacpp-presets](https://github.com/bytedeco/javacpp-presets/). The project is managed using Maven.

Normally maven works great, but this particular library has a platform dependent shared library (built on a CentOS system according to the documentation) which interfaces to LLVM. Because of that the jar downloaded by maven does not work in NixOS.

Ideally I want to continue using maven for our project because we develop in different platforms, including other linux distributions and also Windows.

I am trying to package javacpp-presets in NixOS to overcome this issue. But I do not know how to do that because it is also built by maven, and NixOS does not have support for packaging maven projects, as far as know.

Can someone help with that?

**Comment by romildo** [comment]
Maybe some Java developers can give some hints on this.

**Comment by romildo** [comment]
Here is my very first attempt:
``` nix
{ stdenv, fetchFromGitHub, maven }:

stdenv.mkDerivation rec {
  name = "javacpp-${version}";
  version = "1.2.4";  

  src = fetchFromGitHub {
    owner = "bytedeco";
    repo = "javacpp";
    rev = version;
    sha256 = "0xd7k0aw2yzxb1yc3wqlmaqi3qn9v9w9x4n4wm0h3jhv68bcrfig";
  };

  nativeBuildInputs = [ maven ];

  buildInputs = [ ];

  buildPhase = ''
    mvn compile
  '';

  # other stuff to install
  
  meta = with stdenv.lib; {
    homepage = https://github.com/bytedeco/javacpp;
    description = "Efficient access to native C++ inside Java";
    license = licenses.asl20;
    platforms = platforms.unix;
    maintainers = [ maintainers.romildo ];
  };
}
```

Building this expression gives:
```
[ERROR] Could not create local repository at /var/empty/.m2/repository -> [Help 1]
```

**Comment by NeQuissimus** [comment]
Take a look at #12770

You are going to have more issues than just this :D

**Comment by romildo** [comment]
Is there any example of using [build-maven](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-maven.nix) and [mvn2nix-maven-plugin](https://github.com/NixOS/mvn2nix-maven-plugin) to package Java projects in NixOS? I want to try them and examples can be helpful. I am not finding any on nixpkgs.

cc @shlevy @copumpkin

**Comment by Profpatsch** [comment]
Closing, since the issue stagnated.
