### ISSUE TITLE
process described in "building rpm deb with nixpkgs" doesn't work

### ISSUE THREAD

**Issue by grindhold** [NixOS/nixpkgs#195143]
i am trying to build a debian package from a derivation as described in https://nixos.wiki/wiki/Nixpkgs/Building_RPM_DEB_with_nixpkgs . i am on nixpkgs master. when i trigger the process, i receive

```
error: attribute 'diskImageFormat' missing

       at /home/grindhold/prj/nixpkgs3/pkgs/build-support/vm/default.nix:397:40:

          396|       if test -d "$origImage"; then origImage="$origImage/disk-image.qcow2"; fi
          397|       ${qemu}/bin/qemu-img create -F ${attrs.diskImageFormat} -b "$origImage" -f qcow2 $diskImage
             |                                        ^
          398|     '';
(use '--show-trace' to show detailed location information)
```
i am not really sure whether the documentation is missing something or whether this is a bug.

## Checklist

- [ ] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [ ] checked [open documentation issues] for possible duplicates
- [ ] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by sikmir** [comment]
Add `diskImageFormat = "qcow2";` to your `debBuild` arguments.

**Comment by sikmir** [comment]
Updated [nixos.wiki](https://nixos.wiki/wiki/Nixpkgs/Building_RPM_DEB_with_nixpkgs)
