### ISSUE TITLE
Vscode crashes on Aarch64/Apple Silicon

### ISSUE THREAD

**Issue by miniBill** [NixOS/nixpkgs#195153]
### Describe the bug
Visual Studio Code crashes on startup

### Steps To Reproduce
1. nix-shell -p vscode
2. code
3. `/nix/store/1vcp9adz3wmsgknfcigspn6ns2nlnax0-vscode-1.69.2/bin/.code-wrapped: line 63:  3056 Segmentation fault      ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"`

### Additional context
I'm running this inside Asahi Linux. Not sure if the bug is related to aarch64 or to Apple Silicon in particular.

### Notify maintainers
@eadwu @Synthetica9 @maxeaubrey @bobby285271 

### Metadata
```console
[minibill@samyazaz:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.19.0-asahi-5-1-ARCH, Arch Linux ARM, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs-22.05"`
 - channels(minibill): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by viiibe** [comment]
This bug likely happened due to lack of support of 16K pages in Chromium, as mentioned in [initial Asahi Linux release post](https://asahilinux.org/2022/03/asahi-linux-alpha-release/). This bug [was fixed upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=1301788), and in my tests VSCode opens just fine.

Here's my metadata:

```
[vibe@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.2.0-asahi, NixOS, 23.05 (Stoat), 23.05pre475225.645bc49f34f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(vibe): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by miniBill** [comment]
@viiibe thanks for the update
