### ISSUE TITLE
rPackages.car is broken due to missing dependency

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#19527]
## Issue description

While trying to build rPackages.mosaic, I get the following error:

```
** libs
ERROR: dependency 'pbkrtest' is not available for package 'car'
* removing '/nix/store/i1m0ix1lb6xqy49l6a0kp0n7k7p86sqd-r-car-2.1-1/library/car'
/nix/store/gnapiykf78yfmbdnx7p1gwx019ym3jk4-gfortran-wrapper-5.4.0/bin/g++ -I/nix/store/p1m7rd9zx97zcz4ipz4my4jlx7gvl0zv-R-3.2.3/lib/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR  -I"/nix/store/qfd1121icsjd4qy56vrc70vyh62x08c0-r-Rcpp-0.12.3/library/Rcpp/include" -I"/nix/store/cgimazfxh3j94gl3d0i4saivn3hzgpnc-r-BH-1.60.0-1/library/BH/include"   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
builder for ‘/nix/store/4wq48fq5v4y4v9ccnchxvijigjbc2q1p-r-car-2.1-1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/g6zvg99kg5kd4y1ilp20i1rvzwg3cbdb-r-mosaic-0.13.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/g6zvg99kg5kd4y1ilp20i1rvzwg3cbdb-r-mosaic-0.13.0.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```
### Steps to reproduce
1. `nix-env -i rPackages.mosaic`
## Technical details
- System: 17.03.git.ecb596b (Gorilla)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by siddharthist** [comment]
And indeed:
```
 > nix-env -f '<nixpkgs>' -iA rPackages.pbkrtest
error: attribute ‘pbkrtest’ in selection path ‘rPackages.pbkrtest’ not found
```

**Comment by siddharthist** [comment]
[It's on CRAN](https://cran.r-project.org/web/packages/pbkrtest/index.html), I'm going to try to regenerate the package set and see if that fixes the problem.

**Comment by siddharthist** [comment]
Turns out, we're going to have to fix `nlopt`. They've fixed it in the master branch, but have yet to release a new version: https://github.com/stevengj/nlopt/issues/87. If it doesn't get done soon, we should consider supporting Octave 3.x in order to un-break dozens of R packages.

**Comment by siddharthist** [comment]
Maintainers: To fix nlopt, would it be better for me to add Octave 3.x to our package set, or to create a build of nlopt from HEAD?

**Comment by matthewbauer** [comment]
Currently builds correctly on nixpkgs-unstable.
