### ISSUE TITLE
Avahi-daemon is stopped after suspend/resume cycle

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#19525]
## Issue description

When the system is put to sleep (suspend) and resumed again, then the avahi daemon service is stopped. 

## Related effects

Avahi is commonly required to find network printers, so if you are noticing that CUPS says something along the lines of "couldn't locate printer foobar.local" after resuming from suspend, then you are affected by this bug as well. 

## Cause

The reason for this is the following line in the service configuration of `avahi-daemon.service`:

```
~ (master=) systemctl show avahi-daemon | grep PartOf
PartOf=post-resume.target
```

This means that any stop event sent to `post-resume.target` is propagated to the avahi daemon.

To fix this bug, we need to investigate what the intention of setting that option was and figure out a way to implement what was intended, because the current behavior is just broken.

The option was added as part of cdd7310a503481e3c40266be45b6b8256d95ecbd.

**Comment by groxxda** [comment]
The comment one line above:
```
        # Receive restart event after resume
        partOf = [ "post-resume.target" ];
```
suggests that this should cause avahi to be started after resume.
