### ISSUE TITLE
networking.interfaces.<name?>.ip4 address lost after suspend

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#19521]
## Issue description

A static IPv4 address set with the `networking.interfaces.<name?>.ip4` interface is lost after the manchine has been suspended. When the machine wakes up again, the interface has no address.
### Steps to reproduce

``` nix
  networking.interfaces.enp2s0 = {
    ip4 = [ { address = "192.168.9.1"; prefixLength = 24; } ];
  };
```

```
$ nixos-rebuild test
(see that interface has IPv4 address
(enter suspended mode + wake up)
(see that interface has no address)
```
## Technical details
- System: NixOS 16.09

**Comment by dezgeg** [comment]
Maybe worth toggling `networking.useNetworkd` and see if the alternative works.

**Comment by bjornfor** [comment]
Hm, with ```networkign.useNetworkd = true;``` I don't get an address at all.
