### ISSUE TITLE
Update Jetbrains to 2022.2.3

### ISSUE THREAD

**Issue by patflynn** [NixOS/nixpkgs#195390]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: Jetbrains versions

current version: 2022.2.1
desired version: 2022.2.3

###### Notify maintainers

maintainers: @Olliroxx @fabianhjr

###### Note for maintainers

Please tag this issue in your PR.

**Comment by fabianhjr** [comment]
I am not a JetBrains maintainer:

Also, its probably easier to run `pkgs/applications/editors/jetbrains/update.py` and open a PR tagging me (would gladly review the MR)

**Comment by patflynn** [comment]
Got it. Sorry I think I just saw your username and some previous PRs and added you based on that.  I created a PR from the update script. No idea how to test the updates.
