### ISSUE TITLE
Missing default profile in a fresh install of 16.09

### ISSUE THREAD

**Issue by alexvorobiev** [NixOS/nixpkgs#19537]
## Issue description
I have just installed NixOS 16.09 in a VM on WMware Workstation (not sure if it matters) using the standard installation DVD image. After the install the link /root/.nix-profile is created but its target /nix/var/nix/profiles/default does not exist so the link points nowhere.

### Steps to reproduce
Install NixOS 16.09 according to the instructions (partition, format, nixos-install, etc)

## Technical details

* System: 16.09.741.354fd37 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.741.354fd37

**Comment by vcunat** [comment]
It should get created when you install something "into the profile". I'm not certain that adding some empty directories would really improve the situation.

It's really a nix "issue", not nixos specific and not root-specific.

**Comment by vcunat** [comment]
Issue moved to [NixOS/nix #1101](https://github.com/NixOS/nix/issues/1101) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vcunat** [comment]
Heh, the issue-moving button is weird.
