### ISSUE TITLE
r-modules/generate-shell.nix is missing wget

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#19530]
## Issue description

Running `nix-shell --pure generate-shell.nix` and then `Rscript generate-r-packages.R cran  > cran-packages.nix.new`

Results in a lot of 

```
sh: wget: command not found
sh: wget: command not found
sh: wget: command not found
sh: wget: command not found
sh: wget: command not found
```

The solution is to include `wget` in the `nativeBuildInputs`. I'll take care of this soon!
### Steps to reproduce

Given above
## Technical details
- System: 17.03.git.ecb596b (Gorilla)

**Comment by NeQuissimus** [comment]
It would be great if you could send in a PR for this :) Thanks!

**Comment by siddharthist** [comment]
@NeQuissimus Already did :smile: It's the PR that references this issue (#19531). I ran into some difficulty using `nix-shell --pure` and have been waiting for a response from someone more knowledgeable!

**Comment by dtzWill** [comment]
It might be a good idea to fix the missing wget dependency regardless of using `nix-shell --pure`?
