### ISSUE TITLE
libfive

### ISSUE THREAD

**Issue by lboklin** [NixOS/nixpkgs#195327]
Current version is broken and outdated. I managed to get the most recent version working and I submitted a pull request to the repo with a flake that has the changes (https://github.com/libfive/libfive/pull/506) (but the author isn't willing to take on the burden of maintaining a flake).

I'm not looking to be a maintainer, so I would appreciate if someone would update the [nixpkgs derivation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libfive/default.nix) using (or based on) the [default.nix](https://github.com/lboklin/libfive/blob/4823444ee852231a114e835156c9f9bb48690fcf/default.nix) I made.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: libfive

current version: 2020-02-15
desired version: 2022-05-19

###### Notify maintainers

maintainers:

Hopefully these are the accounts of the derivation's maintainers:
@Hodapp87 @KoviRobi 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by KoviRobi** [comment]
Sounds good, hopefully I can have a look at it, though sadly my mental health hasn't been good enough these past two years for me to do that much for Nix (and I'm impressed and grateful for the auto-updates that nixpkgs do)
