### ISSUE TITLE
Windscribe 2.0 desktop client

### ISSUE THREAD

**Issue by gregoriomoss** [NixOS/nixpkgs#195429]
**Project description**
Windscribe 2.0 desktop client for Windows, Mac and Linux 

**Metadata**

* homepage URL: https://windscribe.com/
* source URL: https://github.com/Windscribe/Desktop-App
* license: , GPL-2.0 license 
* platforms:  Windows, Mac and Linux

**Comment by wegank** [comment]
Duplicate of #158368.
