### ISSUE TITLE
darwin: qemu does not build with vmnet support

### ISSUE THREAD

**Issue by colin-arnott-xero** [NixOS/nixpkgs#195459]
### Describe the bug
[vmnet.framework](https://developer.apple.com/documentation/vmnet) support [landed in qemu 7.1.0](https://gitlab.com/qemu-project/qemu/-/issues/465) and works on homebrew. Unfortunately we appear not to be exposing that interface during configuration.

### Steps To Reproduce
1. `nix build nixpkgs#qemu --print-build-logs`
2. see `qemu> Run-time dependency appleframeworks found: NO (tried framework)` and `qemu>     vmnet.framework support      : NO`
3. confirm `7.1.0` and no vmnet flags:
```
[user@system:~]$ qemu-system-x86_64 -version
QEMU emulator version 7.1.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
[user@system:~]$ qemu-system-x86_64 -help | grep vmnet

```

### Expected behavior
two `YES`s and runtime support for `-netdev vmnet-*` flags

### Additional context
while I think it is unrelated, since this is failing during configuration before enable flags are processed, homebrew passes different configuration flags than we do, specifically, they add these:
```
          --enable-capstone
          --enable-curses
          --enable-libssh
          --enable-slirp=system
          --enable-vde
          --enable-virtfs
          --enable-zstd
          --extra-cflags=-DNCURSES_WIDECHAR=1
```

### Notify maintainers
@edolstra @alyssais

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(user): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by colin-arnott-xero** [comment]
are there any other features or flags we should be enabling to maintain compatibility with homebrew? (as that is how the qemu docs suggest installing on macos)

**Comment by alyssais** [comment]
Colin Arnott ***@***.***> writes:

> are there any other features or flags we should be enabling to maintain compatibility with homebrew? (as that is how the qemu docs suggest installing on macos)

Yes, I'd merge PRs to add any other features our QEMU package is still missing.

**Comment by ajbouh** [comment]
Is there a chance this has this regressed?

```
$ qemu-system-x86_64 -help | grep vmnet
$ qemu-system-x86_64 -version
QEMU emulator version 8.1.1
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 23.0.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

When I look at the build logs for the qemu, I see:
```
$ nix --extra-experimental-features 'nix-command flakes' log --store https://cache.nixos.org /nix/store/xxszflxbwz0wxbff2rs68vzy8wnqvqc3-qemu-8.1.1/

...

Run-time dependency appleframeworks found: YES (vmnet)
Header "vmnet/vmnet.h" has symbol "VMNET_BRIDGED_MODE" with dependency appleframeworks: NO
../meson.build:917: WARNING: vmnet.framework API is outdated, disabling

...
```
