### ISSUE TITLE
OpenJDK 19

### ISSUE THREAD

**Issue by Jonpez2** [NixOS/nixpkgs#195638]
OpenJDK19 has gone GA - https://openjdk.org/projects/jdk/19/

Is there a way for me to help out here?  The setup for the other jdks look quite intimidating...

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: pkgs.jdk18

current version: 18
desired version: 19

###### Notify maintainers

maintainers: @edwtjo @asbachb

###### Note for maintainers

Please tag this issue in your PR.

**Comment by Jonpez2** [comment]
Ping please?

**Comment by jerith666** [comment]
I have a build that works locally at https://github.com/jerith666/nixpkgs/compare/home-alpha-i9...jerith666:nixpkgs:openjdk-19.  Haven't done anything for Darwin, tested it much beyond a brief `jshell` session, or tested any of the adoptopenjdk stuff, though.

**Comment by Jonpez2** [comment]
Exciting thank you!
