### ISSUE TITLE
Komorebi Package Request

### ISSUE THREAD

**Issue by JoolthePlanet** [NixOS/nixpkgs#195664]
**Project description**
Animated wallpaper manager for Linux.

**Purpose**
I wanted to set live wallpapers, but I can't find a good program to set live wallpapers seamlessly.

**Metadata**

* homepage URL: https://github.com/cheesecakeufo/komorebi
* source URL: https://github.com/cheesecakeufo/komorebi
* license: gpl3
* platforms: linux

**Comment by JoolthePlanet** [comment]
Do I need to put (unofficial) if I didn't write this program?

**Comment by pinkcreeper100** [comment]
no afaik

**Comment by dit7ya** [comment]
Closing as duplicate of #190814.
