### ISSUE TITLE
fido2luks: incorrect licensing info

### ISSUE THREAD

**Issue by ehllie** [NixOS/nixpkgs#195634]
The license listed for `fido2luks` is incorrect. It has been re-licensed upstream: https://github.com/shimunn/fido2luks/commit/4136b1bfad95b996e9575dc454b74b038a227aca

###### Checklist
- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `fido2lusk`
current version: `0.2.20`
desired version: n/a

###### Notify maintainers
maintainers: @prusnak @mmahut 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by prusnak** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/195645
