### ISSUE TITLE
Cannot build `chromiumDev`

### ISSUE THREAD

**Issue by niknetniko** [NixOS/nixpkgs#195631]
### Steps To Reproduce
1. build `chromiumDev`

### Build log
```console
$ nix shell nixpkgs#chromiumDev
error: builder for '/nix/store/qzgg6zbd54v14xqhvgm96zjrw0has4s1-chromium-unwrapped-108.0.5327.0.drv' failed with exit code 1;
      last 10 log lines:
      > Current dir: /build/chromium-108.0.5327.0/out/Release/
      > Command: python3 /build/chromium-108.0.5327.0/tools/clang/scripts/update.py --print-revision --verify-version=16.0.0
      > Returned 1 and printed out:
      >
      > The expected clang version is llvmorg-16-init-5189-gbfcd536a-1 but the actual version is
      > Did you run "gclient sync"?
      >
      > See //build/config/BUILDCONFIG.gn:347:3: which caused the file to be included.
      >   "//build/config/compiler:thinlto_optimize_default",
      >   ^-------------------------------------------------
      For full logs, run 'nix log /nix/store/qzgg6zbd54v14xqhvgm96zjrw0has4s1-chromium-unwrapped-108.0.5327.0.drv'.
error: 1 dependencies of derivation '/nix/store/iv4szff695ksvg33zchs8s2vyn1fncbf-chromium-dev-108.0.5327.0.drv' failed to build
```

### Notify maintainers

@primeos @thefloweringash

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.0, NixOS, 22.11 (Raccoon), 22.11.20221008.c592415`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(niko): `"android-nixpkgs"`
 - channels(root): `"android, nix-ld, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by primeos** [comment]
Yes, I'm aware of that issue and `chromiumBeta` is currently broken as well (for the same reason).

The beta and especially the dev versions regularly fail to build and are only in Nixpkgs to prepare for future stable releases (ideally they should always build fine but I'm currently the only Chromium maintainer and have far too few time to keep them green - patches are welcome of course :smile:).

https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/chromium/README.md
> chromiumBeta and chromiumDev: For testing purposes only (not build on Hydra). We use these channels for testing and to fix build errors in advance so that chromium updates are trivial and can be merged fast.

It could make sense to always mark `chromiumBeta` and `chromiumDev` as broken to avoid confusion.

**Comment by primeos** [comment]
I had time for fixing the configuration phase of `chromiumBeta` today: https://github.com/NixOS/nixpkgs/pull/197779
A full build is still pending (I started one locally and via CI as CI is faster than my setup) and I didn't check `chromiumDev` yet but hopefully there won't be many surprises left (it'd be especially bad if the build would require LLVM 15 as we don't have it in Nixpkgs yet).

**Comment by primeos** [comment]
I forgot to close this issue. I fixed that chromeDev revision quite a while ago but chromiumBeta and chromiumDev are currently broken again. I'll replace this issue with https://github.com/NixOS/nixpkgs/issues/213862.
