### ISSUE TITLE
 portmaster

### ISSUE THREAD

**Issue by gregoriomoss** [NixOS/nixpkgs#195714]
**Project description**
Portmaster is a free and open-source application that puts you back in charge over all your computer's network connections. Developed in the EU eu, Austria.

**Metadata**

* homepage URL: https://safing.io/portmaster/
* source URL: https://github.com/safing/portmaster
* license:  AGPL-3.0 license 
* platforms: win, linux

**Comment by dit7ya** [comment]
Closing as duplicate of #174194.
