### ISSUE TITLE
Adjust recent attribute deprecations

### ISSUE THREAD

**Issue by infinisil** [NixOS/nixpkgs#195702]
Deprecation first needs a warning, then an error, then a removal, each of which separated by at least one release if not more.

- https://github.com/NixOS/nixpkgs/pull/192870 skips these steps entirely for this release, going straight from not even a warning to removal. This is not acceptable and needs to be reverted.
- https://github.com/NixOS/nixpkgs/pull/192681 skips the warning step and directly throws an error. This is not okay, a warning needs to be thrown first, this PR needs adjustments.

**Comment by Artturin** [comment]
The aliases file cannot use warnings so I made the removal script just convert them to throws and then remove https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/remove-old-aliases.py

**Comment by piegamesde** [comment]
With https://github.com/NixOS/rfcs/pull/127, it will be possible to have warnings for aliases. I plan on implementing this as a follow-up to the RFC as soon as #177272 is merged.

My rough idea so far for this:

- Have a local `injectWarning` function in `aliases.nix`, and change all aliases to the form `some-pkg = injectWarning "some-pkg has been renamed to other-pkg" other-pkg`;
- The warning kind will be `alias`. Used aliases will contain to fail evaluation if used, but adding `"*.alias"` to `config.ignoreWarnings` will print a trace warning instead.
- I haven't decided on whether `"*.alias"` should be part of the default value for `config.ignoreWarnigns`. Maybe have it in there but only on the stable channels?
- Depending on how we decide on those default values, removing aliases might involve a second stage with a kind `removal` warning for some time. Not sure about that either.

**Comment by infinisil** [comment]
@Artturin The solution should be to fix whatever causes us to not be able to use warnings then. A proper deprecation timeline is much more important than removing a bunch of aliases that have no negative impact. So I really appreciate the effort by @piegamesde here.

In this case we should fully revert both PR's and wait with deprecations of aliases until something like RFC 127 is implemented.

**Comment by roberth** [comment]
Here's a PR to revert it https://github.com/NixOS/nixpkgs/pull/196001
