### ISSUE TITLE
KDE won't build on i686

### ISSUE THREAD

**Issue by sg2002** [NixOS/nixpkgs#195710]
### Steps To Reproduce
1. Try building KDE on i686 machine.

### Build log
[Build log is availible on Hydra](https://hydra.nixos.org/build/194574376)
### Additional context
I've been struggling with building KDE for a few recent NixOS versions. I've managed to get it running recently and made 2 MRs that fix it: #192903 and #192907. The first one was merged, while the other one wasn't.

Creating this as an issue to add as a 22.11 blocker to hopefully get KDE running on i686 in 22.11. Whether it is really a blocker and whether #192907 should be merged is up to the dev team to decide of course. 

### Notify maintainers

@NixOS/qt-kde

**Comment by mweinelt** [comment]
I think it is time to let go of i686-linux. Keeping it around of wine/steam is fine, but we haven't even been able to build firefox for i686-linux since 2020.

**Comment by FRidh** [comment]
Note we also have an RFC covering this. i686-linux is a tier 3 platform. Tier 3 platforms are non-blocking.
https://github.com/NixOS/rfcs/blob/553b132ca05e0ad19b563b80b08d17330df205cf/rfcs/0046-platform-support-tiers.md

**Comment by vcunat** [comment]
The build log in OP is misleading, as that's from 22.05 and doesn't apply anymore.  Here's a link that should work all the time:
https://hydra.nixos.org/job/nixos/trunk-combined/nixos.closures.kde.i686-linux

**Comment by sg2002** [comment]
The build log I've provided as an example of what's going on there in 22.05, the last stable version, trunk may or may not have some other issues on top of the ones present in 22.05, since it obviously changes all the time.

Since I'm commenting on this issue again, can someone elaborate on the existence of binary cache for i686? From what I could gather, even if we get Hydra jobs working correctly, the binary cache still wouldn't exist as it was disabled for the entire i686 architecture?

**Comment by vcunat** [comment]
cache.nixos.org has everything that's built on Hydra.nixos.org.  Immediately.

**Comment by sg2002** [comment]
I'm sorry, but I keep getting conflicting information on this and all of it got me somewhat confused.

What about Nix? If a binary cache for i686 should exist and I'm rebuilding Nixos from a local nixpkgs repo copy set to a revision already built Hydra, for example the latest 22.05 revision from status.nixos.org, it should not be building Nix from scratch, right? It should get it from the binary cache?

**Comment by vcunat** [comment]
Yes, you do get it (just tried).

**Comment by sg2002** [comment]
Did you try it on i686? For some reason it's trying to build it from scratch for me.

**Comment by vcunat** [comment]
I got i686-linux version of the `nix` attribute on the latest `nixos-22.05` channel.  You can download e.g. by
```
nix-store --realize -Q /nix/store/wxrffrz1kaqjrfm3fa16j2m30ddfvc7i-nix-2.8.1
```

**Comment by SuperSandro2000** [comment]
Now upower fails to build.

Personally I don't think we need to support i686 beyond wine and steam because 4GB RAM is to little to run nix comfortable anyway and more and more upstream projects done support it.
I would vote for closing this.

**Comment by sg2002** [comment]
[Upower issue is already reported upstream](https://gitlab.freedesktop.org/upower/upower/-/issues/214). Seems like some kind of Python integer precision issue, I'll make an MR to fix it.

**Comment by mweinelt** [comment]
A month ago with no reaction so far. Doesn't look promising. We could patch that test downstream, or disable the specific test, if the test runner supports that.
