### ISSUE TITLE
Deno 1.26.1 fails to build on aarch64-linux

### ISSUE THREAD

**Issue by jmbaur** [NixOS/nixpkgs#195716]
### Steps To Reproduce
1. `nix build .#legacyPackages.aarch64-linux.deno` on master

### Build log
https://gist.github.com/jmbaur/99338e5432f62212c12f7d1557fe2327

### Additional context
The issue is posted on deno's repo: https://github.com/denoland/deno/issues/16207

### Notify maintainers

@06kellyjac 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.14, NixOS, 22.11 (Raccoon), 22.11.20221011.285e77e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/7xlnfnx4pc3bv0kp719jr1r8jbsxkv54-source`
```

**Comment by 06kellyjac** [comment]
Thanks for reporting. LMK when there is an upstream fix

**Comment by tjni** [comment]
Closing because this is now passing on Hydra (presumably after version bumps): https://hydra.nixos.org/build/197666738
