### ISSUE TITLE
nix-shell fails with "Argument list too long" for an npm package

### ISSUE THREAD

**Issue by zohl** [NixOS/nixpkgs#19581]
## Issue description

When I try to build `nodePackages.eslint` on master branch everything goes fine. Running nix-shell for the same package fails with message: 

```
Can't exec "bash": Argument list too long at /run/current-system/sw/bin/nix-shell line 309.
Died at /run/current-system/sw/bin/nix-shell line 310.
```
### Steps to reproduce

```
nix-build -A nodePackages.eslint  ~/path/to/nixpkgs # ok
nix-shell -A nodePackages.eslint  ~/path/to/nixpkgs # errored
```
## Technical details
- System: nixos-version: 16.09.git.f4d07ac (Flounder)
- Nix version: nix-env (Nix) 1.11.2
- Nixpkgs version: "15.09.1076.9220f03"

**Comment by abbradar** [comment]
The problem seems to be in `nix-shell` -- I think it doesn't respect `passAsFile`.

**Comment by Profpatsch** [comment]
works on current nixpkgks
