### ISSUE TITLE
rPackages.png broken

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixpkgs#19580]
## Issue description

rPackages.png doesnt build on nixos-unstable
### Steps to reproduce

`nix-build '<nixpkgs>' -A rPackages.png`
## Technical details

the fix: https://gist.github.com/cleverca22/377e2d7b2f01fe8197a78f36f0209887

but i dont have experience with how nixpkgs handles rPackages, dont know how to make it into a PR

**Comment by svenkeidel** [comment]
This issue seams to be fixed in master.
