### ISSUE TITLE
Nautilus Audio/Video Properties: Your GStreamer installation is missing a plug-in.

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#195936]
### Describe the bug
When attempting to view audio or video properties in GNOME Files (nautilus), it shows nothing but the error message "Your GStreamer installation is missing a plug-in".

### Steps To Reproduce
1. Launch GNOME Files
2. Right-click on an audio or video file and go to its "Properties"
3. Go to "Audio/Video Properties"

### Expected behavior
It should show Audio/Video Properties without errors.

### Screenshots
![图片](https://user-images.githubusercontent.com/12882091/195799001-420c2722-6df4-4e7d-ae49-00106e94a3f0.png)

### Additional context
Image Properties works as expected.

### Notify maintainers

@NixOS/gnome 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.72, NixOS, 22.11 (Raccoon), 22.11pre417295.ba187fbdc5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(yes): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SamLukeYes** [comment]
Related output from console:
```
(org.gnome.Nautilus:5262): TotemPropertiesPage-WARNING **: 16:39:44.631: Couldn't get information about 'file:///home/yes/Music/429211_8_bit_Impression.mp3': Your GStreamer installation is missing a plug-in.
```

Tried removing `pkgs.gnome.totem` from `environment.gnome.excludePackages`, but the issue persists. I've also set `environment.sessionVariables.GST_PLUGIN_PATH_1_0 = ["${pkgs.gst_all_1.gst-vaapi}/lib/gstreamer-1.0"];` in my NixOS configuration. Not sure whether it is related.

**Comment by jtojnar** [comment]
The panel does not need Totem any more these days, the name contains Totem because it was originally part of Totem but it has been moved to Nautilus.

This is a duplicate of https://github.com/NixOS/nixpkgs/issues/53631.

Until that is resolved, you can set the following:

```nix
environment.sessionVariables.GST_PLUGIN_SYSTEM_PATH_1_0 = lib.makeSearchPathOutput "lib" "lib/gstreamer-1.0" [
  pkgs.gst_all_1.gst-plugins-good
  pkgs.gst_all_1.gst-plugins-bad
  pkgs.gst_all_1.gst-plugins-ugly
  pkgs.gst_all_1.gst-plugins-libav
]
```

**Comment by SamLukeYes** [comment]
OK, I see.

**Comment by desmond-git** [comment]
I am having the same issue.
When I try to use the option from @jtojnar but but I get error "error: undefined variable 'lib'"

So how do I make this work? Noob here -_-

**Comment by SamLukeYes** [comment]
> I am having the same issue.
> When I try to use the option from @jtojnar but but I get error "error: undefined variable 'lib'"
> 
> So how do I make this work? Noob here -_-

You'll probably need to add the argument `lib` to the top of your configuration file. See my commit above for how I actually did this.

**Comment by desmond-git** [comment]
> > I am having the same issue.
> > When I try to use the option from @jtojnar but but I get error "error: undefined variable 'lib'"
> > So how do I make this work? Noob here -_-
> 
> You'll probably need to add the argument `lib` to the top of your configuration file. See my commit above for how I actually did this.

You are right. I missed that one.

This works:
```

{ config, lib, pkgs, ... }:

environment.sessionVariables.GST_PLUGIN_SYSTEM_PATH_1_0 = lib.makeSearchPathOutput "lib" "lib/gstreamer-1.0" (with pkgs.gst_all_1; [
  gst-plugins-good
  gst-plugins-bad
  gst-plugins-ugly
  gst-libav
]);
```

Thanks
