### ISSUE TITLE
kaleido

### ISSUE THREAD

**Issue by thyol** [NixOS/nixpkgs#195960]
**Project description**
Python package for static plots export. Uses a binary that doesn't work under nixos.

Building from scratch seems to require to build chrome. patchelf requires a missing library for `libnspr4`.

**Metadata**

* homepage URL: https://github.com/plotly/Kaleido
* source URL: https://github.com/plotly/Kaleido
* license: mit + apache
* platforms: linux

**Comment by KMIJPH** [comment]
If anyone really needs to use kaleido now, it can be patched with patchelf (set interpreter and rpaths).

I also had to change the following line in `kaleido/scopes/base.py`:
```python
proc_args = self._build_proc_args()
```
to
```python
proc_args = ["sh"] + self._build_proc_args()
```

**Comment by xieby1** [comment]
I am trying to use plotly.py on NixOS and have encountered the kaleido problem.
Following [KMIJPH](https://github.com/KMIJPH)'s suggestion, I hastily packaged the kaleido wheel.

I tested a simple plotly script to export a PDF, and it worked😺.
I haven't conducted further investigation yet;
perhaps when I completely migrate from matplotlib to plotly, I will conduct more tests.
If anyone wants to investigate more, feel free to use the following snippets.

Below is the kaleido wheel package `kaleido.nix`:

```nix
{ buildPythonPackage
, lib
, nss
, nspr
, expat
, fetchPypi
}:
let
  rpath = lib.makeLibraryPath [
    nss
    nspr
    expat
  ];
in buildPythonPackage rec {
  pname = "kaleido";
  version = "0.2.1";
  format = "wheel";
  src = fetchPypi {
    inherit pname version format;
    platform = "manylinux1_x86_64";
    hash = "sha256-qiHPG/HHj4+lCp99ReEAPDh709b+CnZ8+780S5W9w6g=";
  };
  doCheck = false;
  postFixup = ''
    for file in $(find $out -type f \( -perm /0111 -o -name \*.so\* \) ); do
      patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" "$file" || true
      patchelf --set-rpath ${rpath}:$out/lib/x86_64-linux-gnu $file || true
    done
    sed -i 's,#!/bin/bash,#!/usr/bin/env bash,' $out/lib/python3.11/site-packages/kaleido/executable/kaleido
  '';
}
```

The nix-shell script to run the simple plotly test shell.nix:

```nix
let
  pkgs = import <nixpkgs> {};
  kaleido = pkgs.python3Packages.callPackage ./kaleido.nix {};
in pkgs.mkShell {
  packages = with pkgs; [
    python3
    pkgs.python3Packages.plotly
    pkgs.python3Packages.pandas
    pkgs.python3Packages.packaging
    kaleido
  ];
}
```

And here is the simple plotly test `plot.py` script, which exports a PDF:

```python
#!/usr/bin/env python3
import plotly.graph_objects as go
# https://github.com/plotly/plotly.py/issues/3469
import plotly.io as pio   
pio.kaleido.scope.mathjax = None

fig = go.Figure(
    data = [go.Bar(x=[1,2,3,4], y=[1,3,1,4])],
    layout=go.Layout(title=go.layout.Title(text="A Fig by a graph_objects")),
)
fig.write_image("./graph_objects.pdf")
```

**Comment by carschandler** [comment]
Can this be closed now? Thanks to @Pandapip1 (legend). I bet this one was a doozie.

**Comment by Pandapip1** [comment]
Yup. I ended up using the binary wheel and replacing as much vendored stuff as I could.
