### ISSUE TITLE
Was exercism dropped from nixpkgs?

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#19597]
Hello,

I wanted to install exercism http://exercism.io/cli/linux and thought that I should first look if there is not a Nix package for it.
I did not find it with `nix-env -qaP | grep exercism` nor with http://nixos.org/nixos/packages.html but I found traces that there existed such a package (first as a binary, then as a goPackage) by searching this repository.
Was support for this package dropped? If so, was it dropped voluntarily? I did not find any trace of a discussion on dropping it but maybe it happened somewhere anyway.
If the package is still there, somehow, what should I have done to find it?

Thanks!

PS: tagging @wjlroe since he was listed as maintainer of the original binary package.

**Comment by Mic92** [comment]
I think, it go removed by this pull request: https://github.com/NixOS/nixpkgs/pull/16017
You can restore this package, if you want.

**Comment by Zimmi48** [comment]
Indeed! For some reason it did not appear in `pkgs/top-level/all-packages.nix` and thus was forgotten from this pull request. Not being a Go developer myself, I'm not sure how I could restore it properly.

**Comment by copumpkin** [comment]
cc @kamilchm

**Comment by kamilchm** [comment]
It looks like it wasn't exposed to `top-level` before and that's why it was removed.
I can get it back and expose it as top level package if you want.

**Comment by copumpkin** [comment]
FWIW, I used to refer to lots of `goPackages.X` (just like I do with `pythonPackages` and so on; would you delete most of those too?) so exposing at the top level doesn't really feel like the right criterion.

**Comment by Zimmi48** [comment]
The distinction between this particular package and most `goPackages` or `pythonPackages` is that this is providing an executable and not a library. It is a final-user package, not a development package.  It was probably a mistake from the beginning not to expose it in `top-level`.

Now, it is true that lots of packages providing executable utilities for developers (and not libraries) are hidden inside such attribute sets as well. Drawing an example from what I know, `ocamlPackages.utop` is in such case. `ocamlPackages.findlib` as well, but at least if I type

```
$ ocamlfind
The program ‘ocamlfind’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.ocamlPackages.findlib
```

the response tells me what its location is. Whereas, if I type

```
$ utop
utop: command not found
```

the response is unhelpful.

But at least I can find it with http://nixos.org/nixos/packages.html. Whereas in the case of the Emacs mode Proof-General, I don't even find it there or with `nix-env -qaP | grep proof`.

I do not understand these distinctions. But I know that I have digressed.

Coming back to the original problem, if you restore the package, note that the latest version is now v2.3: https://github.com/exercism/cli/releases

**Comment by rbasso** [comment]
I'm not a *Go* programmer and I'm still trying to understand *Nix* and *Nixpkgs*, but I would like to pack `exercism` because it is too boring to compile and install it manually.

I would love some directions here... 

##### What I have

###### pkgs/top-level/all-packages.nix
```
  ...

  exercism = callPackage ../applications/misc/exercism { };

  ...
```
###### pkgs/applications/misc/exercism/default.nix
```
{ stdenv, buildGoPackage, fetchFromGitHub }:


buildGoPackage rec {
  name    = "exercism-${version}";
  version = "2.3.0";

  goPackagePath = "github.com/exercism/cli";

  src = fetchFromGitHub {
    owner  = "exercism";
    repo   = "cli";
    rev    = "v${version}";
    sha256 = "1zhvvmsh5kw739kylk0bqj1wa6vjyahz43dlxdpv42h8gfiiksf5";
  };

}
```

##### Questions

1. It seems to work, but I don't know if this is the proper way to do it. Is it right? Suggestions?
2. The way it is, the package name comes out as `go1.7-exercism-2.3.0` instead of `exercism-2.3.0`. Is this name structure also used for executable or just for libraries?
3. To install it, I have to type `nix-env -iA exercism`. Is it possible to make it work with `nix-env -i exercism` ?

**Comment by kamilchm** [comment]
1. It's ok, add some meta to it like https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/deis/default.nix#L28
2 + 3. There's no difference for libs/exec in `buildGoPackage` now and I think that it could be a good move to change it to `buildGoApplication` like `buildPythonApplication` that won't prefix app name.
