### ISSUE TITLE
How to fix "warning: not applying UID change ..." warnings

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/nixpkgs#19599]
## Issue description

On boot and `nixos-rebuild`, I get the following warning:

```
warning: not applying UID change of user ‘ntp’ (3 -> 179)
```

Are there way to remove remove such warning?

**Comment by bjornfor** [comment]
AFAIK, you have to do that manually, with e.g. find/chown/usermod.

**Comment by sternenseemann** [comment]
Why is it not done automatically? I always wonder.

**Comment by vcunat** [comment]
@sternenseemann: the UID change of the user is easy enough, but you may want to change it also on files somewhere on your disk(s).

**Comment by vcunat** [comment]
I suppose we could start a FAQ section in the nixos manual, with a short explanation to this entry.

**Comment by sternenseemann** [comment]
Oh okay, I see! But it would also be pretty tedious to do it manually then.

**Comment by vcunat** [comment]
I think in most cases you don't need to care, really, e.g. simply delete `/var/lib/ntp` in this case (or maybe the UID change would go through without any changes).

**Comment by sternenseemann** [comment]
Ah, I see!

**Comment by adrianopol** [comment]
Just leave it here: I was trying to change a normal user ID by setting `users.users.somename.uid = 1234;`, but `nixos-rebuild switch` failed with the same warning even after making `chown -R 1234:users /home/someuser`. In order to make it work you should also change the UID in /etc/passwd:
```
someuser:x:1234:100::/home/...
```
