### ISSUE TITLE
Getting more developers to contribute to Nixpkgs documentation

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#1960]
In order for documentation to be written by different contributors, it has to be trivial to write it. I believe docbook is not appropriate for such task. Markup has to be easy and we don't need something very semantic.

I've made an experiment and converted current docbook to RestructuredText (using pandoc) and generated html documentation with [Sphinx](http://sphinx-doc.org/).

See http://static.domenkozar.com/nixpkgs-manual-sphinx-exp/

For examples of documentation see https://cryptography.io/en/latest/ or http://phpsecurity.readthedocs.org/en/latest/ (note "Edit on Github" button)

Notes:
- some by-hand correction were made (and some typos still need to be fixed)
- Sphinx supports language domains and we could have inline documentation
- conversion was made manually, we could integrate that to build man/pdf/epub/html with Nix for each build

**Comment by bachp** [comment]
Sorry for commenting on such an old issue, but I just wanted to say that docbook really doesn't make it easy to contribute to the documentation. And I think solutions like [Asciidoctor](http://asciidoctor.org/) or [Sphinx](http://www.sphinx-doc.org/) are more accessible and I believe they are powerful enough to allow writing well structured documentation.
Another advantage is that GitHub can directly render reStructuredText and Asciidoc in the web UI, which is not the case for docbook.

**Comment by davidak** [comment]
I would also rather contribute to a rST documentation than docbook. Have done it once and it was a pain!

**Comment by vyp** [comment]
With [Commonmark](http://commonmark.org) the output is not a guessing game because it's actually a spec. Lead by the author of pandoc. Sorry just mentioning because not already mentioned here.

**Comment by phile314** [comment]
Just as some anecdotal evidence, using rST documentation has worked very well for the [Agda](https://github.com/agda/agda) project. We started using rST for our user manual about 1 year ago, and today we have ~100 pages of [rST documentation](https://media.readthedocs.org/pdf/agda/latest/agda.pdf). Note that you can also do fancy stuff like math formulas, see e.g. [here](http://agda.readthedocs.io/en/latest/language/with-abstraction.html#technical-details).

Using rST has led to much more documentations contributions for us, both from outsiders *and* existing contributors. Having Nixpkgs (and Hydra) documentation in rST would make contributing for me much easier.

**Comment by domenkozar** [comment]
I haven't lost all hope here, I'll reopen.

Note that today we have some documentation in markdown that is auto-converted using pandoc: https://github.com/NixOS/nixpkgs/tree/master/doc/languages-frameworks

This is discouraged (because it makes things really hard to have different toolchains for building docs), but also hints for the change of tooling.

**Comment by bachp** [comment]
It's also worth noting that the Linux kernel is starting to use rST and sphinx: https://lwn.net/Articles/692704/

**Comment by aneeshusa** [comment]
I'm a big fan of Asciidoc (with the Asciidoctor toolchain), which is markdown-like but doesn't suffer from variant explosion, has well defined extension points, and was created with Docbook in mind, meaning it has really good Docbook compatibility and the toolchain can do conversions out of the box. This makes it easy to use in parallel with Docbook, but it also has easy outputters for HTML, PDF, man pages and more.

**Comment by aneeshusa** [comment]
Also, the Linux kernel originally was leaning towards switching to Asciidoctor, but moved to rst/Sphinx later on due to concerns about adding Ruby code (Asciidoctor) to their build toolchain. IMO, in our case Asciidoctor is a lighter-weight dependency than Pandoc in Haskell which we're already using.

**Comment by bachp** [comment]
@aneeshusa I originally also preferred Sphinx and rST but recently learned to appreciate Asciidoc with Asciidoctor. However I think if the transition would be done everything should be converted in one batch and then move on from there.

**Comment by AndersonTorres** [comment]
I can say by myself, but in my personal blogs I use rST (as a
HTML-generator, not directly). It's a lot easier to maintain, and have
great support for html, latex and more. There's even docbook support for it
(https://github.com/Abstrys/rst2db).

2016-10-14 11:14 GMT-03:00 Pascal Bach <notifications@github.com>:

**Comment by Mic92** [comment]
@aneeshusa what I dislike about the current documentation is, that everything is one hard to navigate page. Does Asciidoctor splitting documentation in multiple pages, while offering an offline search like Sphinx does? I also think we do not need global ordering of chapters. We have independent topics here.

**Comment by aneeshusa** [comment]
@Mic92 It is possible to have separate Asciidoc files that are rendered to separate pages; I'm not sure what you mean by "offline search". I agree there is no natural global ordering of chapters, but I think it is useful to put all the content in some order to render for e.g. single page HTML or a single PDF with the complete docs for ease of offline usage.

**Comment by Mic92** [comment]
@aneeshusa https://cs-volttron.readthedocs.io/en/latest/ the search box in upper right, is a javascript based search-engine.

**Comment by aneeshusa** [comment]
@Mic92 It seems this is [not yet implemented in Asciidoctor](https://github.com/asciidoctor/asciidoctor/issues/626) (scroll down to see comments about search capabilities). Personally, Ctrl-F fulfills my needs, but if javascript-based search is important to have then I'd support using Sphinx, as it's also a great toolset (and better than DocBook).

**Comment by domenkozar** [comment]
Another example how this is stalling documentation efforts: https://github.com/NixOS/hydra/pull/316

**Comment by gilligan** [comment]
@domenkozar Nothing happened here in over a year..  do you think there is even any chance of making decisions here?

**Comment by bachp** [comment]
I think one other issues with Docbook, besides being XML, is the lack of open source editors for it.

**Comment by domenkozar** [comment]
As this is not really looking to have a solution, I'll close it.

https://github.com/NixOS/nixpkgs/issues/29324 is promising for easing the contributions.
