### ISSUE TITLE
Expose mkOcamlPackages

### ISSUE THREAD

**Issue by Chattered** [NixOS/nixpkgs#19602]
Our team uses a hacked version of the Ocaml compiler against which I want to build ocaml packages. Can mkOcamlPackages be exposed under ocaml-ng as it was previously?

**Comment by aske** [comment]
OK, I'll make the change in a minute.

Also, just being curious -- what kind of changes have you made to the compiler?

**Comment by Chattered** [comment]
Thanks! That's great!

The changes are mostly to the toplevel, including the data-structure for the toplevel environment. We use the HOL Light theorem prover, which is run entirely at the toplevel, and we've extended the toploop module so we can get metadata on theorems proven.
