### ISSUE TITLE
mesa: build doesn't include device-select and overlay layers

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#196086]
### Describe the bug
Our mesa build is missing the device-select and overlay layers so that functionality doesn't work.

Add `"-D vulkan-layers=device-select,overlay"` to mesonFlags and 

```
      mv -t $drivers/lib $out/lib/libVkLayer*
      for js in $drivers/share/vulkan/implicit_layer.d/*.json; do
        substituteInPlace "$js" --replace '"libVkLayer_' '"'"$drivers/lib/libVkLayer_"
      done
```

to postInstall to get device-select working. This doesn't get the overlay working, probably needs a similar change.

Other distros eg arch do include these layers: https://github.com/archlinux/svntogit-packages/blob/a66847a882888b0c2e1f55085224ba8ac2fb3474/trunk/PKGBUILD#L56

The functionality these layers enable is described [here for device-select](https://docs.mesa3d.org/envvars.html#vulkan-mesa-device-select-layer-environment-variables).

**Comment by LunNova** [comment]
Ah, got the overlay working too, needs that replace in explicit_layer.d too.

![image](https://user-images.githubusercontent.com/782440/195968290-a043324f-0fcd-4d49-81bf-90bd6d08c6d6.png)

**Comment by natto1784** [comment]
https://github.com/NixOS/nixpkgs/issues/165636
https://github.com/NixOS/nixpkgs/issues/165616
