### ISSUE TITLE
Steam games now crash back to desktop

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#196078]
### Describe the bug

Yesterday I was able to run games using Steam. Today *all* of them quit immediately, probably because of a bug introduced in the Steam client:

```
$ steam steam://rungameid/1282730
steam.sh[30389]: Running Steam on nixos 22.05 64-bit
steam.sh[30389]: STEAM_RUNTIME is enabled automatically
setup.sh[30470]: Steam runtime environment up-to-date!
run.sh[30482]: Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 127
steam.sh[30389]: Steam client's requirements are satisfied
```

### Steps To Reproduce
Steps to reproduce the behavior: see above.

### Expected behavior
The games should play.

### Additional context
I'm not sure whether this is something which we have to fix in nixpkgs, or whether it could be fixed upstream.

### Notify maintainers
@jagajaga @jonringer

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.72, NixOS, 22.05 (Quokka), 22.05.3620.e06bd4b64bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by jonringer** [comment]
did you hibernative at all? then try to run something.

I'm having issues where post sleep, some graphic related scenarios aren't working like they should

**Comment by l0b0** [comment]
No, I'm on desktop. But a couple restarts of Steam seems to have fixed the issue, at least for now. :shrug:

**Comment by l0b0** [comment]
Closing since the issue seems to have resolved itself.
