### ISSUE TITLE
WayDroid

### ISSUE THREAD

**Issue by gregoriomoss** [NixOS/nixpkgs#196034]
**Project description**
Android on Wayland

**Metadata**

* homepage URL: https://github.com/Waydroid/
* source URL: https://github.com/waydroid/waydroid
* license: GPL-3.0 license 
* platforms:  linux

**Comment by Kranzes** [comment]
We have [virtualisation.waydroid.enable](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=waydroid), is there anything else you might need related to Waydroid?
