### ISSUE TITLE
nix-optimise.timer empty

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19610]
## Issue description
Upon boot (messages taken from `dmesg`), I always see an error about `nix-optimise.timer`.

```
[    2.166140] systemd[1]: nix-optimise.timer: Timer unit lacks value setting. Refusing.
```

Checking the systemd timer makes clear why the error is being emitted:

```
systemctl cat nix-optimise.timer
# /nix/store/3zv276cxsrw0jfmsfbn89nj2j1zc0jdw-unit-nix-optimise.timer/nix-optimise.timer
[Unit]

[Timer]

```

I am fairly certain that nothing is being optimised here :)

### Steps to reproduce
- Set `nix.extraOptions` to `auto-optimise-store = true` in `configuration.nix`
- `nixos-rebuild boot`
- Reboot

## Technical details

* System: 17.03pre93766.14139d1 (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre93766.14139d1"

**Comment by joachifm** [comment]
I believe the cause is that the nix-optimise module generates a systemd unit unconditionally, but a proper timer is only generated if it the service is set to run automatically (false by default).

**Comment by NeQuissimus** [comment]
How would I set the service to run?

**Comment by nhooyr** [comment]
Add `nix.optimise.automatic = true` to `/etc/nixos/configuration.nix`.

**Comment by nhooyr** [comment]
Regardless, is there any way to avoid throwing that error?

**Comment by joachifm** [comment]
It's a bit surprising that `startAt = []` would result in an empty timer unit, I'd expect the backend to not generate anything in that case.

**Comment by NeQuissimus** [comment]
Enabling `nix.optimise.automatic` seems to work.
Why does this option not show up at https://nixos.org/nixos/manual/options.html ?

**Comment by nhooyr** [comment]
I think it was very recently added. I don't think we need anything in `[Unit]`. It should run `nix-optimise.service` which you can view with `systemctl cat nix-optimise.service`.

**Comment by NeQuissimus** [comment]
ah, that makes sense. I did not know it automatically called the service with the same name, I have never dealt with systemd timers.
