### ISSUE TITLE
gtk-layer-shell is missing vapi file in dev

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#196173]
### Describe the bug
gtk-layer-shell is missing the VAPI file, I found this with a Flake I've been working on.
After I ran a GC on the store, the VAPI file disappeared.

### Steps To Reproduce
1. `nix-shell -p gtk-layer-shell`
2. `find $(pkg-config --cflags gtk-layer-shell-0 | sed -e 's/-I//g' -e 's|include/gtk-layer-shell||g')`

### Expected behavior
`find $(pkg-config --cflags gtk-layer-shell-0 | sed -e 's/-I//g' -e 's|include/gtk-layer-shell||g')` should print a line with `share/vala/vapi/gtk-layer-shell-0.vapi`.

### Additional context
gtk-layer-shell generates the VAPI file in meson, at [`src/meson.build:43-49`](https://github.com/wmww/gtk-layer-shell/blob/3ac6dbcbd8d53d5f1dadd055680555d08c56368a/src/meson.build#L43-L49).

### Notify maintainers
@eonpatapon

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.71, NixOS, 22.05 (Quokka), 22.05.3441.fe76645aaf2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"expidus, nixos-22.05"`
 - channels(ross): `"expidus"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
There hasn't been a release since https://github.com/wmww/gtk-layer-shell/commit/3ac6dbcbd8d53d5f1dadd055680555d08c56368a

**Comment by RossComputerGuy** [comment]
Strange. I'm not sure why the VAPI file is gone then.

**Comment by Artturin** [comment]
the code to generate the vapi file is not in any release

**Comment by RossComputerGuy** [comment]
Alright, not sure why I am suddenly getting VAPI errors for one of my projects which require the file. I didn't have the problem until I updated the Flake.

**Comment by RossComputerGuy** [comment]
gtk-layer-shell reports as 0.6.0 when there's 0.7.0 that has the fix.

**Comment by RossComputerGuy** [comment]
v0.8.0 is now out and it has the necessary changes.

**Comment by Aleksanaa** [comment]
```
nix-shell -p gtk-layer-shell pkg-config
find $(pkg-config --cflags gtk-layer-shell-0 | sed -e 's/-I//g' -e 's|include/gtk-layer-shell||g')
```
shows `/nix/store/xxwyl9hmz1vgbgbm4zzvnm6m3c03dyc8-gtk-layer-shell-0.8.2-dev/share/vala/vapi/gtk-layer-shell-0.vapi` now.
