### ISSUE TITLE
pmount isn't installed with suid root

### ISSUE THREAD

**Issue by anfelor** [NixOS/nixpkgs#19617]
## Issue description
Apparently the suid hasn't been set for pmount. 
```    
$ pmount /dev/sdb1
Error: this program needs to be installed suid root
```
I would consider this a bug, but it seems that it [was done on purpose](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/pmount/default.nix#L32). 
If so, I would appreciate a description of how to mount usb drives then on NixOS.

### Steps to reproduce
Install pmount and try to mount a usb drive
This happens both with nix-env installation and system-wide installation.

## Technical details

* System: (NixOS: 16.09)
* Nix version: 1.11.4
* Nixpkgs version: 16.09.680.4e14fd5

**Comment by vbgl** [comment]
Here is a hint: http://nixos.org/nixos/manual/options.html#opt-security.setuidPrograms
An example of configuration for slock: https://nixos.org/wiki/Slock

**Comment by anfelor** [comment]
Ah, great! It works now.

Thank you!

**Comment by grahamc** [comment]
setuidPrograms has been replaced with security.wrappers:

```
 security.wrappers = {
   pmount.source = "${pkgs.pmount}/bin/pmount"; 
   pumount.source = "${pkgs.pmount}/bin/pumount";
 };
```
https://nixos.org/nixos/options.html#security.wrappers
```
