### ISSUE TITLE
pkgsStatic.go: build fails

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#196111]
Description copied from https://github.com/NixOS/nixpkgs/issues/191941

### Steps To Reproduce

1. nix build .#pkgsMusl.go
2. nix build .#pkgsStatic.go

### Build log

* nix build .#pkgsMusl.go
  [logs](https://termbin.com/ra65)
  ![image](https://user-images.githubusercontent.com/5861043/191064073-1b349e50-fd1f-4e27-9aa9-f31d9e3d015f.png)

  Notice: Musl error is related to package: `bootstrap116`

* nix build .#pkgsStatic.go
  [logs](https://termbin.com/nv1i2)
  ![image](https://user-images.githubusercontent.com/5861043/191067253-085e61c8-4c4a-42a9-b602-36a25e93ce29.png)

### Metadata

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.8, NixOS, 22.11 (Raccoon), 22.11.20220918.f677051`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - channels(intj): `""`
 - nixpkgs: `/nix/store/fr68dr66gmggn62jir7vp1bcnignwxp9-source`
```

**Comment by yu-re-ka** [comment]
As a workaround I provide my own bootstrap binaries in my musl-nixos overlay: https://cyberchaos.dev/cyberchaoscreatures/musl-nixos/-/blob/aa87dc76996b4f9920ee2ce09a278fd62e4876d8/overlay.nix#L361

**Comment by superherointj** [comment]
> As a workaround I provide my own bootstrap binaries in my musl-nixos overlay: https://cyberchaos.dev/cyberchaoscreatures/musl-nixos/-/blob/aa87dc76996b4f9920ee2ce09a278fd62e4876d8/overlay.nix#L361

What is the source of: `https://yaya.yuka.dev/public/go${version}.${platform}.tar.gz`?

**Comment by yu-re-ka** [comment]
> What is the source of, or process to generate: `https://yaya.yuka.dev/public/go${version}.${platform}.tar.gz`?

`nix build .#pkgsCross.musl64.go`

and a small diff because that does not build otherwise:

```diff
diff --git a/pkgs/development/compilers/go/1.19.nix b/pkgs/development/compilers/go/1.19.nix
index a406b21458d..a218b0ba147 100644
--- a/pkgs/development/compilers/go/1.19.nix
+++ b/pkgs/development/compilers/go/1.19.nix
@@ -141,13 +141,13 @@ stdenv.mkDerivation rec {
     # Contains the wrong perl shebang when cross compiling,
     # since it is not used for anything we can deleted as well.
     rm src/regexp/syntax/make_perl_groups.pl
-  '' + (if (stdenv.buildPlatform != stdenv.hostPlatform) then ''
+  '' + (if (stdenv.buildPlatform.system != stdenv.hostPlatform.system) then ''
     mv bin/*_*/* bin
     rmdir bin/*_*
     ${lib.optionalString (!(GOHOSTARCH == GOARCH && GOOS == GOHOSTOS)) ''
       rm -rf pkg/${GOHOSTOS}_${GOHOSTARCH} pkg/tool/${GOHOSTOS}_${GOHOSTARCH}
     ''}
-  '' else if (stdenv.hostPlatform != stdenv.targetPlatform) then ''
+  '' else if (stdenv.hostPlatform.system != stdenv.targetPlatform.system) then ''
     rm -rf bin/*_*
     ${lib.optionalString (!(GOHOSTARCH == GOARCH && GOOS == GOHOSTOS)) ''
       rm -rf pkg/${GOOS}_${GOARCH} pkg/tool/${GOOS}_${GOARCH}
```

Now PRed here:
https://github.com/NixOS/nixpkgs/pull/202856

**Comment by yu-re-ka** [comment]
@superherointj this is the tracking issue for pkgsMusl.go, let's discuss that here.

We need a (bootstrap) go compiler to build our go compiler. For glibc, we download the official binary distribution.
But the official binary distribution does not provide a musl version.
gccgo is a potential solution, but I tried and it is a lot of work to get it running.

Another option is to build an own musl bootstrap go compiler (via nixpkgs pkgsCross.musl64.go), host it somewhere and in the pkgsMusl package set download and use that.

And a third option, is using [gcompat](https://git.adelielinux.org/adelie/gcompat) to run the glibc bootstrap compiler with musl using a shim. This is what void-linux does.

**Comment by superherointj** [comment]
First. Thanks for taking the time to answer on this topic. It's been a while I am looking for a solution to this.

> - The most simple and obvious option is to build an own musl bootstrap go compiler (via nixpkgs pkgsCross.musl64.go), host it somewhere and in the pkgsMusl package set download and use that.

Do you think would be possible to do this without having to host the binary externally? I don't know how to avoid the loop between pkgsCross.musl64.go and pkgsMusl.go.

I made some experiments today with this but they went nowhere.

**Comment by yu-re-ka** [comment]
That is pointless. If you can depend on a package set that is using glibc, you can just use pkgsCross.musl64 in the first place and not have this problem.

**Comment by yu-re-ka** [comment]
This will never be included in nixpkgs. _But, that said, here is how it can be done:_

```diff
diff --git a/pkgs/development/compilers/go/1.19.nix b/pkgs/development/compilers/go/1.19.nix
index a406b21458d..f539a30eabc 100644
--- a/pkgs/development/compilers/go/1.19.nix
+++ b/pkgs/development/compilers/go/1.19.nix
@@ -1,4 +1,5 @@
 { lib
+, path
 , stdenv
 , fetchurl
 , tzdata
@@ -17,7 +18,11 @@
 }:
 
 let
-  goBootstrap = buildPackages.callPackage ./bootstrap116.nix { };
+  goBootstrap = let
+    buildPackages = if stdenv.buildPlatform.isMusl
+    then import path { system = "x86_64-linux"; }
+    else buildPackages;
+  in buildPackages.callPackage ./bootstrap116.nix { };
 
   skopeoTest = skopeo.override { buildGoModule = buildGo119Module; };
 
```

**Comment by nmeum** [comment]
> * gccgo is a potential solution, but I tried and it is a lot of work to get it running, since it does not build with musl libc without patches. Alpine does this, and they are working towards upstreaming the patches, so it might become a viable solution in the future.

Hello, I maintain the Alpine Go package 👋 With the exception of [a single libucontext-related patch](https://gcc.gnu.org/pipermail/gcc-patches/2022-December/608793.html) all of our patches have been upstreamed. You only need to backport these patches from [gofrontend Git HEAD]( https://github.com/golang/gofrontend) to whatever GCC version you are using. I believe this to straightforward at this point (many patches are also already part of the GCC 12 release branch). Using gccgo over a pre-built Go binary also has the advantage that the [bootstrap process becomes more transparent](https://bootstrappable.org/benefits.html).

**Comment by sternenseemann** [comment]
I feel like getting gccgo to work is probably a better investment, since it also gains us something for the glibc based go packages.

**Comment by nmeum** [comment]
> With the exception of [a single libucontext-related patch](https://gcc.gnu.org/pipermail/gcc-patches/2022-December/608793.html) all of our patches have been upstreamed.

FYI: This patch has now also been [merged upstream](https://github.com/golang/gofrontend/commit/ecc2a2e70e44fa76a75b12d0893bc1702b72a1b4). I am presently not aware of any remaining gccgo compatibility issues with musl 1.2.3 for basic usage (i.e. bootstrapping Google Go). Let me know if you run into any issues with musl and gccgo on nixos.

**Comment by yu-re-ka** [comment]
@nmeum: I picked the following commits on top of gcc 12.2.0:

https://github.com/gcc-mirror/gcc/commit/cf79b1117bd177d3d4c6ed24b6fa243c3628ac2d
https://github.com/gcc-mirror/gcc/commit/7f195a2270910a6ed08bd76e3a16b0a6503f9faf
https://github.com/gcc-mirror/gcc/commit/762fd5e5547e464e25b4bee435db6df4eda0de90
https://github.com/gcc-mirror/gcc/commit/e73d9fcafbd07bc3714fbaf8a82db71d50015c92
https://github.com/gcc-mirror/gcc/commit/b6c6a3d64f2e4e9347733290aca3c75898c44b2e
https://github.com/gcc-mirror/gcc/commit/2b1a604a9b28fbf4f382060bebd04adb83acc2f9

This fails to build with the error `go1: error: ‘-fsplit-stack’ is not supported by this compiler configuration`

full log:
https://termbin.com/8z5p
