### ISSUE TITLE
pipewire + alsa is broken

### ISSUE THREAD

**Issue by sshilovsky** [NixOS/nixpkgs#196191]
### Describe the bug
With `pipewire.alsa.enable = true`, alsa output doesn't work.

`aplay -l` works correctly, but `pactl list cards` outputs empty list.

`mpv --ao=alsa ...` doesn't play the file, it just hangs in the beginning at `-00:00` file position:

### Steps To Reproduce
1. Configure `services.pipewire { enable = true; alsa.enable = true; };`
2. Try `pactl list cards` # empty output
3. Try playing a file with alsa. # hangs

### Expected behavior
`pactl list cards` shouldn't be empty; playing a file should work.

### Additional context
switching from pipewire to pulseaudio fixes the sound

### Notify maintainers

@Kranzes 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.72, NixOS, 22.05 (Quokka), 22.05.3620.e06bd4b64bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I've tried with `unstable` channel off, same result.

**Comment by MtP76** [comment]
@sshilovsky have you tried if deleting ~/.asoundrc would help?

**Comment by sshilovsky** [comment]
> @sshilovsky have you tried if deleting ~/.asoundrc would help?

I don't have any, I've also tried it with empty user home dir.

**Comment by MtP76** [comment]
Ok. so then your problem must be about something else. I had problem with one of my setups and got it solved by removing content from .asoundrc.

**Comment by m911t** [comment]
Came across this, can confirm that pipewire+alsa is fine

**Comment by bjornfor** [comment]
And I ran pipewire + alsa for a short while on nixos 22.11 and got working audio output from qmmp music player.

@sshilovsky: please comment if something still doesn't work and we can re-open.
