### ISSUE TITLE
KDE partition manager does not work

### ISSUE THREAD

**Issue by sg2002** [NixOS/nixpkgs#196280]
### Describe the bug
KDE Partition Manager runs but it does not show any disks and nothing inside of its GUI works.

### Steps To Reproduce
1. Install partition-manager package.
2. Run it under a normal user or a superuser.

### Expected behavior
It should work.

### Additional context
Here's the command line output when you run partitionmanager, maybe something in it is relevant:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Loaded backend plugin:  "pmsfdiskbackendplugin"
Installation might be wrong, we can't locate `org.kde.kpmcore.externalcommand.policy` on the polkit actions folder.
Please check if your Installation is on a different prefix and copy it to /usr/share/polkit-1/actions
That's specified for your distro. Since this is distro specific, you need to look at your distribution documentation.
QWidget::setMinimumSize: (MessageWidgetDock/QDockWidget) Negative sizes (0,-1) are not possible
QWidget::setMaximumSize: (MessageWidgetDock/QDockWidget) Negative sizes (0,-1) are not possible

```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.68, NixOS, 22.05 (Quokka), 22.05.3632.78a37aa630f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by SuperSamus** [comment]
Did you install it via `programs.partition-manager.enable`?

**Comment by sg2002** [comment]
Nope, just dumped it into environment.systemPackages. Enabling it the way you described works. Thank you.

I guess the question now is can it be made to work when dumped into systemPackages? Gparted works fine that way IIRC. Like how would you discover that you have to install it with programs.partition-manager.enable?

**Comment by huantianad** [comment]
Dang I got got my this as well, thanks for the solution, really wish there was some kind of guard against this kind of thing though.

**Comment by SuperSandro2000** [comment]
> I guess the question now is can it be made to work when dumped into systemPackages?

It easily because it requires a running service.

> Like how would you discover that you have to install it with programs.partition-manager.enable?

Right now you need to know that but that's a general issue being tracked in nixos-search repo.

**Comment by huantianad** [comment]
Weird, even enabling `security.polkit` doesn't fix the issue, nor does manually adding the packages to systemPackages. Is there some other config I'm missing here? (program still can't locate the polkit action)

**Comment by SuperSamus** [comment]
Looming at the option, it needs:

```nix
services.dbus.packages = [ pkgs.libsForQt5.kpmcore ];
```

**Comment by SuperSandro2000** [comment]
It requires the following:

```
services.dbus.packages = [ pkgs.libsForQt5.kpmcore ];
# `kpmcore` need to be installed to pull in polkit actions.
environment.systemPackages = [ pkgs.libsForQt5.kpmcore pkgs.partition-manager ];
```

**Comment by huantianad** [comment]
Yes, I’ve tried both enabling the module and adding both packages to systemPackages and the one to dbus, but they still result in the program not detecting any drives and the same error from the terminal.

**Comment by deftdawg** [comment]
Applying `programs.partition-manager.enable = true` to my `configuration.nix` allowed the `partitionmanager` to complete it's startup and show devices.

Not sure this should be closed though; end user expectation is if a package installs it's going to work; at a minimum there should be a warning or something that tells me additional manual configuration will be required.   Silently failing and have to google for this issue to know why isn't really cool.

**Comment by SuperSandro2000** [comment]
> end user expectation is if a package installs it's going to work

Then we must better document that if there is a options under programs, you most likely want to use that instead. Unfortunately I don't know where the best place would be to put this or how to tackle this problem.

**Comment by Zahrun** [comment]
I suggested concerned packages to give the indication about the corresponding option in longDescription, such as [solaar indicates appropriate option in longDescription](https://search.nixos.org/packages?channel=22.11&show=solaar&from=0&size=50&sort=relevance&type=packages&query=solaar)

**Comment by Zahrun** [comment]
See https://github.com/NixOS/nixpkgs/pull/222397

**Comment by makoConstruct** [comment]
Installing via `programs.partition-manager.enable = true;` didn't solve it for me. I used to get the same issue OP described, at this point it just segfaults.

If more options are required, it's still not documented anywhere.

**Comment by makoConstruct** [comment]
The installation instructions here https://search.nixos.org/packages?channel=22.11&show=partition-manager&from=0&size=50&sort=relevance&type=packages&query=partition still say

> **How to install partition-manager?**
> Add the following Nix code to your NixOS Configuration, usually located in /etc/nixos/configuration.nix
> ```
>   environment.systemPackages = [
>     pkgs.partition-manager
>   ];
> ```

**Comment by SuperSandro2000** [comment]
Yes and that will not change in near future because it is auto generated by the search page. If you see the instructions above, there are more instructions. Also 22.11 didn't get the backport and won't get it because it is near EOL.

**Comment by SuperSandro2000** [comment]
> Installing via `programs.partition-manager.enable = true;` didn't solve it for me. I used to get the same issue OP described, at this point it just segfaults.
> 
> If more options are required, it's still not documented anywhere.

No, there shouldn't be more required. Please try restarting to see if that fixes maybe some qt problems or so.

**Comment by makoConstruct** [comment]
Thanks.

I had no idea at all that the version of nix I installed a week ago is near EOL.
I'll get back to you if the problem recurs after I upgrade (probably wont do so for a while)
