### ISSUE TITLE
localectl fails to find x11 keyboard definitions

### ISSUE THREAD

**Issue by imuli** [NixOS/nixpkgs#19629]
## Issue description

`localectl` (apparently part of `systemd`) looks in `/usr/share/X11/xkb` for keyboard definitions, not `/etc/X11/xkb' or '/nix/store/.../`.

### Steps to reproduce

    $ localectl list-x11-keymap-options
    Failed to open keyboard mapping list. No such file or directory

    $ strace localectl list-x11-keymap-options |& grep xkb
    open("/usr/share/X11/xkb/rules/base.lst", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

## Technical details

* System: 16.09.733.246c937 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.733.246c937"

**Comment by laMudri** [comment]
Can confirm on a recent nixos-unstable (`17.03.git.5bf15b0 (Gorilla)`). My guess is that it's something to do with e7ded267bd39f8509c7c4ab2927c6aec9d567540, so I'll look into that. Removing patches seems like a bad thing, since I rely on patches.

**Comment by laMudri** [comment]
Okay, so reverting that commit fixes my issue (that my version of [this](https://gist.github.com/binarin/380eda7b08a1c230abbc186887fc5823) wasn't working), but I don't know whether it's relevant to you. I still get the same outputs for those commands.

**Comment by imuli** [comment]
I also came across this on my quest to get my personal keyboard layout working, but didn't run into your problem. And yeah, that patch doesn't look like it's the culprit here.

**Comment by laMudri** [comment]
Have these commands worked previously? If not, I'll open a separate issue.

**Comment by groxxda** [comment]
It probably has not worked before my patch: [localectl source](https://github.com/systemd/systemd/blob/cf647b69baee4c478d3909c327e3d917e1563f44/src/locale/localectl.c#L397)

Fixing this to read from `/etc/X11/xkb/..` should be straight forward.
Having systemd depend on xkb seems like a bad idea to me.

**Comment by imuli** [comment]
Agreed on all points. I'll put together a patch if noone else does it first.

**Comment by groxxda** [comment]
@imuli (just in case): we maintain a fork of systemd at http://github.com/NixOS/systemd .
Please submit the patch as a pr over there :+1:

**Comment by imuli** [comment]
I'm closing this as it'll be fixed by NixOS/systemd#8 eventually.

**Comment by laMudri** [comment]
Is there any way to prod someone into merging that? Maybe this issue should be kept open until that is done.

**Comment by teto** [comment]
on master, seems it is still failing
```
localectl                                                                                                                                                ~/gpgme
   System Locale: LANG=fr_FR.UTF-8
       VC Keymap: fr
      X11 Layout: us,fr
       X11 Model: pc104
     X11 Options: eurosign:e

teto@jedha> localectl list-keymaps                                                                                                                                       
Failed to read list of keymaps: No such file or directory
[1] teto@jedha> localectl list-locales                                                                                                                                  
teto@jedha> localectl list-x11-keymap-models                                                                                                                             
Failed to open keyboard mapping list. No such file or directory
```

**Comment by imuli** [comment]
@teto You need `services.xserver.exportConfiguration = true;` in your `nixos configuration, which will make sure `/etc/X11/xkb` is populated.

**Comment by groxxda** [comment]
So `true` should be the sane default for `services.xserver.exportConfiguration` (on systemd setups).

**Comment by teto** [comment]
@imuli thanks for the tip. 
I got bitten by that once again when trying to use `localectl list-x11-keymap-layouts` and set `services.xserver.exportConfiguration = true;` which solved it. What about changing the defaullt ?

Note, enabling it gave a warning:
```
sudo nixos-rebuild -I nixos-config=/home/teto/dotfiles/nixpkgs/configuration-lenovo.nix -I nixpkgs=/home/teto/nixpkgs switch                                                                                                                            
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/8yinyj4m1qv898lh7bgqzpgkislv4kpz-etc-unnamed-10.3.drv
  /nix/store/cghhm24kp87qydfm08wj6y7nqakhzbc2-etc.drv
  /nix/store/waqh5nn31ym6k74ci4wx97vfdbsnawkl-nixos-system-jedha-18.09.git.baa158d.drv
building '/nix/store/8yinyj4m1qv898lh7bgqzpgkislv4kpz-etc-unnamed-10.3.drv'...
building '/nix/store/cghhm24kp87qydfm08wj6y7nqakhzbc2-etc.drv'...
building '/nix/store/waqh5nn31ym6k74ci4wx97vfdbsnawkl-nixos-system-jedha-18.09.git.baa158d.drv'...
activating the configuration...
setting up /etc...
reloading user units for teto...
Linux jedha 4.14.24 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
 13:28:45  actif 1 jour  2:40,  0 utilisateur,  charge moyenne : 0,56, 0,58, 1,02
^a pour editer la commande courante
Failed to connect to bus: No such file or directory
setting up tmpfiles

```

**Comment by chreekat** [comment]
I disagree that an installed-by-default utility (localectl) should be broken unless a non-default option value is specified in configuration.nix.

I think the problem in this case is localectl. The option (`services.xserver.exportConfiguration`) is fine. If we're patching it anyway, shouldn't it be patched be to look in the nix store?

**Comment by chreekat** [comment]
Or at least patched to say, "Please enable services.xserver.exportConfiguration" rather than the default, useless, "Failed to open keyboard mapping list. No such file or directory"

**Comment by con-f-use** [comment]
I just ran into this same problem in NixOS 20.09 and this issue with the workaround was very hard to find. Please reconsider your stance on that.

**Comment by stelcodes** [comment]
Also just ran into this problem. I set `services.xserver.exportConfiguration = true;` and I can see the available options now. I have the `caps:swapescape` option set, but it's not working for me.

**Comment by Ashvith10** [comment]
I think that `services.xserver.exportConfiguration = true;` should be the default. This problem persists even in 2023.

**Comment by devvythelopper** [comment]
apparently this might happen due to how x is configured to start. see https://github.com/NixOS/nixpkgs/issues/254523

**Comment by mxvce** [comment]
I had the same problem with `localectl` as well. The workaroud I found is that here [https://wiki.nixos.org/wiki/Keyboard_Layout_Customization#Advanced](url) it's descibed that you can use `$(nix-build --no-out-link '<nixpkgs>' -A xorg.xkeyboardconfig)/etc/X11/xkb/` in order to cd to `/etc/X11/xdb/` and as per [https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Setting_keyboard_layout](url) you can search in `/usr/share/X11/xkb/rules/base.lst` or in case of nix `$(nix-build --no-out-link '<nixpkgs>' -A xorg.xkeyboardconfig)/etc/X11/xkb/rules/base.lst` since all the outputs of the `localectl list-x11-keymap-*` commands are in `base.lst` file anyways
