### ISSUE TITLE
Microsoft Intune Portal

### ISSUE THREAD

**Issue by JamieMagee** [NixOS/nixpkgs#196237]
**Project description**
App to manage access to corporate apps, data, and resources.

**Metadata**

This requires 3 packages:
- [`intune-portal`](https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/i/intune-portal/intune-portal_1.2210.50_amd64.deb)
- [`msalsdk-dbusclient`](https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/msalsdk-dbusclient/msalsdk-dbusclient_1.0.1_amd64.deb)
- [`microsoft-identity-broker`](https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/microsoft-identity-broker/microsoft-identity-broker_1.4.0_amd64.deb)

A nix port currently exists[^1], but needs to be migrated into nixpkgs

* homepage URL: https://learn.microsoft.com/en-gb/mem/intune/user-help/microsoft-intune-app-linux
* source URL: N/A
* license: unfree
* platforms: linux

[^1]: https://github.com/astatide/nixos-intune

**Comment by JamieMagee** [comment]
I am working on `microsoft-identity-broker` package and initial `intune` module, but currently stuck with dbus permissions when running the service.

https://github.com/JamieMagee/nix-config/tree/intune

**Comment by samos667** [comment]
Maybe is not possible to Nixos architecture But have the possibility to setup mdatp will be a great addition for Nixos deployment on Work environment.
Microsoft tell that a systemd distrib is needed.
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide

**Comment by samos667** [comment]
I can take a look. But do you think at first see that mdatp can be compatible with Nixos ?

**Comment by Algram** [comment]
@samos667  Any update on packaging mdatp? I would be really interested, since my work requires it.

**Comment by samos667** [comment]
> @samos667  Any update on packaging mdatp? I would be really interested, since my work requires it.

Nah sorry I've not look more into this subject.

So I use Ubuntu at work (with home manager)

**Comment by JohanLeirnes** [comment]
Isnt this covered here?
https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/in/intune-portal/package.nix
