### ISSUE TITLE
Foxit Reader crashes when trying to add signature image

### ISSUE THREAD

**Issue by simeoncarstens** [NixOS/nixpkgs#196254]
## Issue description

When trying to insert a signature image, Foxit Reader crashes with the following error:
> (FoxitReader:14762): GLib-GIO-ERROR **: 11:17:44.660: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'
Trace/breakpoint trap (core dumped)

### Steps to reproduce

1. `nix-shell -p foxitreader`
2. Open an arbitrary PDF document via `FoxitReader /some/document.pdf`
3. Click "Protect" -> "PDF Sign" -> "Image" -> "Add Image"

Foxit Reader should then crash with the above error.

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-132-generic, Ubuntu, 18.04.5 LTS (Bionic Beaver), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels([myusername]): `"nixpkgs-22.11pre417910.26b7e6ab6a8"`
 - nixpkgs: `/home/myusername/.nix-defexpr/channels/nixpkgs`

**Comment by tomodachi94** [comment]
Package was dropped in February 2023 with https://github.com/NixOS/nixpkgs/pull/213422. Closing accordingly. Feel free to reopen if the package ever reappears and the bug is still an issue.
