### ISSUE TITLE
Upgade request: code-server:  4.0.1 -> 4.7.1

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#196247]
The `code-server` package has been out-of-date for a while now, but now the very nice [Nix IDE plugin](https://marketplace.visualstudio.com/items?itemName=jnoortheen.nix-ide) has broken due to its age:

```
Activating extension 'jnoortheen.nix-ide' failed: The language client requires VS Code version ^1.67.0 but received version 1.63.0.
```

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: code-server

current version: 4.0.1
desired version: 4.7.1

###### Notify maintainers

maintainers: @offlinehacker

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ZenQy** [comment]
Its's 4.8.3 now.
I use release binary instead.
