### ISSUE TITLE
FreshRSS greader API failing

### ISSUE THREAD

**Issue by pakaca** [NixOS/nixpkgs#196307]
The greader API from the [FreshRSS service](https://github.com/NixOS/nixpkgs/pull/190172) fails.

### Steps To Reproduce

1. Enable `services.freshrss`, set a `virtualHost`, `defaultUser` and `passwordFile`.
2. In `services.nginx`, set the virtualHost options `enableACME` and `forceSSL`;

### Behavior

The profile page links to the API url, `https://myserver.xxx/api`, where it reports the address and state of the Google Reader API.
It shows a red cross, no good.

Also, I see the words FAIL and the address reported as `https://myserver.xxx/api/api/greader.php` (note the double api). But @Stunkymonkey [gets a different result](https://github.com/NixOS/nixpkgs/pull/190172#issuecomment-1280024358): while he also sees the red cross, it says OK instead of FAIL, and the address is reported properly with no duplicated "api/api" in it. 

If I navigate to `https://myserver.xxx/api/greader.php` I also see "OK". Yet, I am failing to connect from mobile apps or newsboat, which reports "Authentication failed".

@Stunkymonkey @etu 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre417910.26b7e6ab6a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixos-unstable"`
 - channels(pakaca): `"home-manager, nixpkgs"`
 - nixpkgs: `/home/pakaca/.nix-defexpr/channels/nixpkgs`
```

**Comment by Stunkymonkey** [comment]
seems to me like:
https://github.com/FreshRSS/FreshRSS/issues/3741
improved via
https://github.com/FreshRSS/FreshRSS/pull/3934

So if we stick to: https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/admins/10_ServerConfig.md this should be solved.

**Comment by pakaca** [comment]
Yes! Other apps indeed succeed in connecting to the API after adding to nginx virtual host:

```
locations."~ ^.*?\.php(/.*)?$".extraConfig = ''
  set $path_info $fastcgi_path_info;
  fastcgi_param PATH_INFO $path_info;
'';
```
