### ISSUE TITLE
NixOS Installer unable to find disk device

### ISSUE THREAD

**Issue by kuwii** [NixOS/nixpkgs#196335]
### Describe the bug
When booting using live CD, the NixOS Installer cannot find a disk device, showing error `There are no partitions to install on`. But the machine does have at lease one disk.

### Steps To Reproduce

1. Download [NixOS live CD](https://releases.nixos.org/nixos/unstable/nixos-22.11pre417962.83b198a2083/nixos-plasma5-22.11pre417962.83b198a2083-x86_64-linux.iso).
2. Boot using the live CD.
3. Open NixOS Installer and the issue will occur.

Can repro this on Hyper-V, KVM and my physical PC.

### Expected behavior

Should normally install NixOS.

### Screenshots

Error:

![image](https://user-images.githubusercontent.com/10705175/196066432-255395c4-4adb-41e8-a6b0-57c5f7a0ba2c.png)

But as you can see the disk does exist:

![image](https://user-images.githubusercontent.com/10705175/196066497-a07255b1-33a3-475b-a52f-43de21d8709d.png)

### Additional context

Live CD:  [nixos-plasma5-22.11pre417962.83b198a2083-x86_64-linux.iso](https://releases.nixos.org/nixos/unstable/nixos-22.11pre417962.83b198a2083/nixos-plasma5-22.11pre417962.83b198a2083-x86_64-linux.iso)

### Notify maintainers

Ping recent maintainers of [`calamares-nixos`](https://search.nixos.org/packages?channel=unstable&show=calamares-nixos&from=0&size=50&sort=relevance&type=packages&query=calamares-nixos):

@r-ryantm  @ryantm @vlinkz 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre417962.83b198a2083`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11pre417962.83b198a2083"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vlinkz** [comment]
Yeah, I've noticed the issue. It's a combination of multiple things. The partition not being detected is an issue with kpmcore not working in unstable after some newer commits. Would be fixed by https://github.com/NixOS/nixpkgs/pull/191822.

Some issues with locales being inputted incorrectly would be fixed by https://github.com/NixOS/nixpkgs/pull/193041.

**Comment by alciono** [comment]
Having the same issue with nixos-plasma5-22.11pre424902.09326850228-x86_64-linux.iso  2022-11-10

**Comment by mweinelt** [comment]
Both PRs were merged and have reached nixos-unstable.

- #191822
- #193041

Can you retry with yesterdays ISO? https://hydra.nixos.org/build/198722895

**Comment by kuwii** [comment]
Have tried the ISO. Issue is resolved now. Thanks for the fix.
