### ISSUE TITLE
gold: Doesn't correctly set rpath in certain instances

### ISSUE THREAD

**Issue by wkennington** [NixOS/nixpkgs#1963]
I'll get back to documenting this.

**Comment by Profpatsch** [comment]
(triage) @abbradar Can you check whether this still happens?

**Comment by abbradar** [comment]
At least for `crawl` it works now; I'm not sure if it's fixed or something in `crawl` has changed.

**Comment by Profpatsch** [comment]
Then we should close this until it happens again. @jagajaga
