### ISSUE TITLE
qgis fails to build with "error: 'QVariant sipQgsSettingsEntryColor::convertToVariant(const QVariant&) const' marked 'override', but does not override" and other errors

### ISSUE THREAD

**Issue by das-g** [NixOS/nixpkgs#196432]
### Steps To Reproduce
1. build `qgis` (or, more specifically, `qgis-unwrapped`):
   ```bash
   nix build /nix/store/8hjjm962r6mrhbqdnpcirfxcckaw82sg-qgis-unwrapped-3.26.2.drv
   ```

### Build log
see [this Gist](https://gist.github.com/das-g/7028006c2e326a636f56ecdbd6225a40)

### Additional context
This is on `nixos-unstable`, but `master` currently (814dbe2a4f33e46bf76e57347b885766ed0c38a1) has has the same problem ([log](https://gist.github.com/das-g/9a97e7e8078800b40dff83148be347ff)).

### Notify maintainers
@lsix, @sikmir, @erictapen, @willcohen

### Metadata
Result of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre417962.83b198a2083`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(das-g): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by das-g** [comment]
(Edited description after trying to build from `master`.)

**Comment by das-g** [comment]
Reverting 9ab916905a5cd0bb4f47ada93f81b587d1fc8565 (python-modules/sip: 6.6.2 -> 6.7.1) and 8b091f7c247a5057d3f31aaf07759021d1782a16 (python-modules/pyqt-builder: 1.13.0 -> 1.14.0) (both parts of PR #194833) would fix this, but would probably break other stuff, wouldn't it? @hqurve in https://github.com/NixOS/nixpkgs/pull/199535#issuecomment-1312455943 suggests to rather bump python-modules/sip further to 6.9.4.

Either would cause 261 rebuilds.

@nrdxp, what do you (as new maintainer of python-modules/sip, author of PR #194833 and as one of the NixOS release-engineers) advise? It'd be really nice to have working QGIS versions in the NixOS 22.11 release.

**Comment by willcohen** [comment]
@nrdxp I defer to whatever is better for the python ecosystem! For QGIS's part, Qt6 is irrelevant -- it doesn't even build fully using it at the moment.

**Comment by nrdxp** [comment]
I would suggest to bump sip, since that is something we will have to do eventually. We should fall back on reverting the other two commits only if that doesn't work out.

**Comment by das-g** [comment]
PR for bumping `python-modules/sip`: #201400
