### ISSUE TITLE
OVE-20221017-0001: PolyMC appears to be compromised

### ISSUE THREAD

**Issue by LunNova** [NixOS/nixpkgs#196460]
There is a developing situation involving polymc, the package is potentially compromised.

PolyMC relies on meta files retrieved from `meta.polymc.org` to determine what jars (the java executable file format) to download when launching mod packs. Due to this online feature, it is not safe to continue using old versions of PolyMC if the maintainer has been compromised as these meta files could be updated to download a malicious jar.

Here is an example of one of the meta files [org.quiltmc.quilt-loader/0.17.5-beta.9.json](https://github.com/PolyMC/meta-polymc/blob/669011a9ff599f3080e569f8a8e643d0b7c6e654/org.quiltmc.quilt-loader/0.17.5-beta.9.json). This file does not appear to be malicious, it is just here to demonstrate how the meta system works and why this is a problem.

Situation started with this commit <https://github.com/PolyMC/PolyMC/commit/ccf282593dcdbe189c99b81b8bc90cb203aed3ee> and the owner dropping all other maintainers from the repo.

I do not know for sure whether this is an account hack or "just" drama / the owner going rogue, figured it's best to open this to track the situation. In either case a maintainer suddenly removing access from all other maintainers is a bad sign.

---

See also:

* [OVE-20221017-0001: PolyMC appears to be compromised](https://xeiaso.net/blog/OVE-20221017-0001)
* [PolyMC compromised apparently according to essential mod devs](https://old.reddit.com/r/feedthebeast/comments/y6kfty/polymc_compromised_apparently_according_to/)
* [Modrinth Discord Announcement about Compromise](https://discord.com/channels/734077874708938864/734084055225597973/1031649111159623711) - requires joining [Modrinth server](https://discord.gg/modrinth-734077874708938864) to view

**Comment by LunNova** [comment]
ccing maintainers @cleverca22 @starcraft66

**Comment by Infinidoge** [comment]
Some additional information from the (now former) maintainers who were removed by Lenny Lennington. These messages from the Discord server they made (Titled PlaceholderMC), as they work to fork the project (See the [PlaceholderMC org](https://github.com/PlaceholderMC) and [PlaceholderMC repository](https://github.com/PlaceholderMC/PlaceholderMC)
The Discord server these messages are in can be found [here](https://discord.gg/hX4g537UNE)

From #announcements:
> LennyMcLenington (one of the founders of polymc and a maintainer), who had most of the access, went rouge. We don't know at this time if it's him or if his account was compromised
he removed all of our perms and removed us from the github org
I suggest not downloading or updating PolyMC until this situation is over
Flatpak and MPR (Ubuntu/Debian) are under my control and should be safe. Currently checking status of the other packages.
however i wouldnt open polymc even from these 
ABOUT CURRENT INSTALLATIONS:
IF you turn off internet everything is safe, but if you create new instances or shit updates itself metaserver could possibly be compromised

Also CCing some of the former PolyMC maintainers, who are in the PlaceholderMC discord:
@Scrumplex, @dada513, @txtsd

**Comment by Scrumplex** [comment]
Can confirm

**Comment by LunNova** [comment]
Should we yank the package?

Is there a patch we can apply to disable the online updating features to make it safe?

**Comment by an-empty-string** [comment]
> Is there a patch we can apply to disable the online updating features to make it safe?

The meta server seems to be configurable, and information is circulating about how to use the MultiMC metaserver instead: https://gist.github.com/Earthcomputer/dc65391f84a2c19ebac6c33506fd7751 -- but this by itself is probably not a workable solution for nixpkgs, given the history here.

Not using a meta server at all doesn't appear to be an option, but the current full contents of the PolyMC meta server are available at https://github.com/PolyMC/meta-polymc -- anyone forking could use this + the update scripts at https://github.com/PolyMC/meta to populate a trusted meta server, it looks like.

**Comment by Infinidoge** [comment]
To effectively disable using the metadata server, you can fill the server setting box with garbage/a dead URL. (Settings -> APIs, Metadata Server)

**Comment by samueldr** [comment]
Instead of yanking, there's a `meta` attribute that can be used for insecure packages, the `OVE` link could be used I suppose. See `meta.knownVulnerabilities` uses.

**Comment by LunNova** [comment]
We can make a PR after finishing up work in a few hours, I'd appreciate if someone else gets it sooner.

**Comment by starcraft66** [comment]
Not using a metadata server will effectively make the launcher useless unless you already have instances created and don't intend to modify them. Since there doesn't seem to be any alternative meta-server other than the MultiMC one at the moment (afaik MultiMC is _not_ okay with other launchers and forks using their official meta, correct me if I am wrong), I will put up a PR marking the package vulnerable for the time being.

**Comment by starcraft66** [comment]
It looks like https://github.com/an-empty-string/nixpkgs/commit/9d27de8105d5f9493695711a574542bc051ae005 was committed while I was typing this message, thanks.

**Comment by leo60228** [comment]
> Is there a patch we can apply to disable the online updating features to make it safe?

This would make the launcher at least mostly unusable (though it might be cached for existing users).

**Comment by TheArcaneBrony** [comment]
as for a possible patch, the binary could be renamed and replaced with a shellscript that sed's the url out of configs

**Comment by LunNova** [comment]
Probably best to keep this open as a tracking issue until we have a replacement?

**Comment by starcraft66** [comment]
@LunNova opened tracking issue https://github.com/NixOS/nixpkgs/issues/196480

**Comment by Infinidoge** [comment]
The PlaceholderMC developers have created a new Metadata Server which is not compromised:
`https://meta.scrumplex.rocks/v1/`

**Comment by Scrumplex** [comment]
> The PlaceholderMC developers have created a new Metadata Server which is not compromised: `https://meta.scrumplex.rocks/v1/` (Uses [this](https://github.com/PlaceholderMC/meta-polymc) underlying repository)

Can confirm!

**Comment by KaspianDev** [comment]
@oxalica nothing ever was compromised, just saying
