### ISSUE TITLE
NixOS 22.05: emacs package lsp-treemacs broken

### ISSUE THREAD

**Issue by brprice** [NixOS/nixpkgs#196414]
### Describe the bug

In NixOS 22.05, the emacs melpa packages lsp-treemacs and treemacs have incompatible versions, breaking lsp-treemacs.
(In particular, the "Errors List" does not work: I cannot expand the tree to see individual errors, and attempting to do so just replicates the top-level tree heading)
This is an instance of https://github.com/emacs-lsp/lsp-treemacs/issues/137.

NB: see "Additional Context" below for a (hacky) fix

### Steps To Reproduce
Unfortunately I don't have a small/simple reproducer to hand, but could cobble one together if requested.

1. Run (emacs+packages from) NixOS-22.05: `systemPackages = [ pkgs.emacsWithPackages(epkgs: [epkgs.melpaPackages.lsp-treemacs])]`
2. Have some project with a language server which will display an error (I notice this with haskell-language-server, but I assume it is independent of which lsp server one runs)
3. Open the code in emacs and run `M-x lsp-treemacs-errors-list` to open the error list, which starts collapsed
4. Attempt to unfold the tree of errors (using `<TAB>`) and notice that it does not unfold, but replicates the top-level text.

### Expected behavior
The tree should unfold.

### Screenshots
Buggy: 
![2022-10-17-131921_824x170_scrot](https://user-images.githubusercontent.com/5623458/196175433-de24c511-4a21-4253-8afd-59ee544a47bf.png)

Expected:
![2022-10-17-131746_768x221_scrot](https://user-images.githubusercontent.com/5623458/196175431-83db89a1-2ab3-4d8c-8c59-b20fec14cd4e.png)

### Additional context

This issue started recently, with https://github.com/NixOS/nixpkgs/pull/193992 which bumped the version of treemacs to one which included a breaking change.
Potentially this affects other packages that integrate with treemacs.
(In unstable (just judging from the source code) this would have been a problem after the PR https://github.com/NixOS/nixpkgs/pull/191769, but fixed in the next melpa bump 6a6e746bbfbaccbf605c89286b539b894f8306a7)

I have manually edited `recipies-archive-melpa.json` to update the lsp-treemacs version and can confirm it works, but I don't know what the proper solution is since it appears that NixOS 22.05 does not normally get emacs package bumps.
See https://github.com/brprice/nixpkgs/tree/fix-melpa-lsp-treemacs

### Notify maintainers
@adisbladis (emacs maintainer)
@AndersonTorres (often updates melpa packages)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
(Note: I am running a flakes-based system without any channels added, so I have adjusted the command, and it warns about nix search paths. I am also running a version of nix from 
https://github.com/edolstra/nix/tree/lazy-trees.)

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9: (source not available)
(use '--show-trace' to show detailed location information)
 - system: `0`
 - host os: `Linux 5.15.72, NixOS, 22.05 (Quokka), 22.05.20221017.b96156f`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0pre20221012_12dd8d4`
 - channels(root): `""`
 - channels(ben): `""`
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:1: (source not available)
 - nixpkgs: `0`
```

**Comment by brprice** [comment]
A related question: is there a nice way to override the version of a melpa package without having to fork nixpkgs?

**Comment by AndersonTorres** [comment]
Usually people employ overlays when they want to patch nixpkgs without downloading nixpkgs:

https://ryantm.github.io/nixpkgs/using/overlays/

https://nixos.wiki/wiki/Overlays

**Comment by brprice** [comment]
Thanks. I am now able to work around this via an overlay:
```
final: prev: {
  emacsWithPackages = ((prev.emacsPackagesFor prev.emacs).overrideScope' (self: super: {
    melpaPackages = super.melpaPackages // {lsp-treemacs = super.melpaPackages.lsp-treemacs.override (args: {
      melpaBuild = drv: args.melpaBuild (drv // {
       version = "20220918.742";
        src = final.fetchFromGitHub {
          owner = "emacs-lsp";
          repo = "lsp-treemacs";
          rev = "f7ae97560cfbc88e781a2d5b9253dace7175b918";
          sha256 = "09zcv0zjzikf1f5l6bkjafwb6icx4vpd625as01d4b2cywnzsyhl";
      };});
    });};
  })).withPackages;
}
```

**Comment by AndersonTorres** [comment]
I will try to update epkgs tomorrow.

**Comment by brprice** [comment]
@AndersonTorres ping. What's the status of this?
(No rush on this, I have a decent workaround with the above overlay.)

**Comment by AndersonTorres** [comment]
@brprice I have tried a local update, however it is slow as hell. I will retry it tomorrow.

**Comment by brprice** [comment]
This issue only affected NixOS 22.05, which is now deprecated. There is also a workaround for anybody still using 22.05. Thus I will close the issue.
