### ISSUE TITLE
`git gui` no longer available in 22.05

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#196548]
### Describe the bug

The `git gui` command seems to be unavailable with recent versions of `gitFull`.

### Steps To Reproduce
1. Install `gitFull`
2. Run `git gui`

### Expected behavior
`git gui` should launch the Git GUI.

### Additional context
The command is now available as `git citool`, for unknown reasons. The application identifies itself as "Git Gui" and "git-gui". It also seems to require installing the `tk` package separately.

(If someone knows another Git GUI which has the killer feature of being able to stage individual lines and chunks I'd be happy to switch.)

### Notify maintainers
@figsoda

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.05 (Quokka), 22.05.3688.1935dd8fdab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - channels(victor): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
`git citool` is a alias for `git gui citool` https://git-scm.com/docs/git-gui/#Documentation/git-gui.txt-codegitcitoolcode

```
nix shell "github:nixos/nixpkgs/release-22.05#gitFull"
git gui
```
![image](https://user-images.githubusercontent.com/56650223/196472826-2b5115c3-ca97-4583-85ec-39b74099f646.png)
and it doesn't work outside of the shell

**Comment by l0b0** [comment]
In that case I guess something else must've broken the `git gui` command on my machine.

**Comment by l0b0** [comment]
In case anyone else runs into this: `nix-env --uninstall home-manager-path` fixed the `git gui` command.
