### ISSUE TITLE
What is the status & plan for lispPackages vs .._new?

### ISSUE THREAD

**Issue by hraban** [NixOS/nixpkgs#196545]
As @rapenne-s remarks in an unrelated PR:

> I see some packages build failures with `nixpkgs-review` and I'm not aware of the state of lispPackages_new, but given the name I suppose it's a work in progress?

_Originally posted by @rapenne-s in https://github.com/NixOS/nixpkgs/issues/195378#issuecomment-1273733682_

I'd love to know what exactly the plan is with lispPackages vs lispPackages-new. Which one is the future? Are we supposed to figure it out as users? Is this a competition? Or is there a consensus that _new will definitely overtake the regular one? Or is it perhaps abandoned? (it was recently updated so I guess not)

I'm currently using _new because of the name, really :/ I don't have the nix chops to evaluate it by any other metric.

There are some TODOs in the _new readme which I'm loath to investigate if the entire thing is moribund.

**Comment by hraban** [comment]
Never mind I just found my answer: https://github.com/NixOS/nixpkgs/issues/155851 -- it's WIP, and it's intended to replace existing lispModules.

**Comment by 7c6f434c** [comment]
>As @rapenne-s remarks in an unrelated PR:
>
>> I see some packages build failures with `nixpkgs-review` and I'm not aware of the state of lispPackages_new, but given the name I suppose it's a work in progress?
>
>_Originally posted by @rapenne-s in https://github.com/NixOS/nixpkgs/issues/195378#issuecomment-1273733682_
>
>I'd love to know what exactly the plan is with lispPackages vs lispPackages-new. Which one is the future? Are we supposed to figure it out as users? Is this a competition? Or is there a consensus that _new will definitely overtake the regular one? Or is it perhaps abandoned? (it was recently updated so I guess not)
>
>I'm currently using _new because of the name, really :/ I don't have the nix chops to evaluate it by any other metric.

If it works for you, that's a useful data point!

>There are some TODOs in the _new readme which I'm loath to investigate if the entire thing is moribund.

**Comment by hraban** [comment]
Somewhat but not exactly. I've shared details of a bug I'm running into in that thread, maybe it's useful info.
