### ISSUE TITLE
Cups (canon pixma mg6150) “Color Manager: no profiles specified in PPD”

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#19653]
current master (but problem existed for > half a year now).

I add my printer like so:

```
Description:    Canon MG6100 series
Location:   
Driver: Canon PIXMA MG6150 - CUPS+Gutenprint v5.2.11 (color, 2-sided printing)
Connection: usb://Canon/MG6100%20series?serial=13DC2C&interface=1
Defaults:   job-sheets=none, none media=iso_a4_210x297mm sides=one-sided
```

and when I try to print a document, it changes the job state to `"Color Manager: no profiles specified in PPD"`.

The log looks like this:

```
Oct 18 17:27:29 katara cupsd[16395]: REQUEST localhost - - "POST /printers/Canon_MG6100_series HTTP/1.1" 200 296224 Print-Job successful-ok
Oct 18 17:27:29 katara cupsd[16395]: Color Manager: no profiles specified in PPD
Oct 18 17:27:29 katara cupsd[16395]: Sending data to printer.
"Color Manager: no profiles specified in PPD
```

Maybe someone has some experience with cups?

**Comment by groxxda** [comment]
Maybe you can narrow the problem down a bit by enabling debug in [cupsd.conf](https://linux.die.net/man/5/cupsd.conf) (`services.printing.extraConf`, `LogLevel`)

**Comment by Profpatsch** [comment]
I think I’ll just skip on this one. I’m set on not wasting any more hours of my life with malicious printers (and printer companies).
