### ISSUE TITLE
iperf: broken on darwin

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#19669]
## Issue description

iperf3 does not build on darwin
### Steps to reproduce

Consult the hydra [build log](http://hydra.nixos.org/build/42199642/log/raw)
## Technical details

I think `_mach_init_routine` needs to be added to `pkgs/os-specific/darwin/apple-source-releases/Libsystem/system_kernel_symbols` but I have not tested this as it requires a lot of compiling.
- System: darwin
- Nix version: 1.11.4
- Nixpkgs version: "17.03pre-git"

**Comment by acowley** [comment]
A bit more detail on why I suggested what I did since I may well be misinterpreting something. On OS X 10.11.6

```
$ nm /usr/lib/libSystem.dylib | grep "_mach"
                 U __mach_fork_child
0000000000001b56 t _mach_init_old
00000000000022b0 D _mach_init_routine
```

And if, when building `iperf3`, I manually run the failing step with the addition of `-L/usr/lib -lSystem`, it links successfully.

**Comment by mitchty** [comment]
As a note, adding _mach_init_routine to the system_kernel_symbols gets iperf working again. No issues in anything else I use. I'll submit a PR tonight if I remember.

**Comment by LnL7** [comment]
adding the symbol to `system_kernel_modules` works by accident, I'm testing some changes that fix this properly.

**Comment by LnL7** [comment]
I pushed the fix to staging https://github.com/NixOS/nixpkgs/commit/16a90832cd52dc2a6aa30cb15a128babddd095c9
