### ISSUE TITLE
nuget-to-nix: base_addresses[$used_source]: unbound variable

### ISSUE THREAD

**Issue by vtrf** [NixOS/nixpkgs#196676]
### Describe the bug
I'm getting an error `/nix/store/jx2hdq8n3fdj0bm58qxgy0psyyl0vd05-nuget-to-nix/bin/nuget-to-nix: line 56: base_addresses[$used_source]: unbound variable
` when trying to generate a lockfile for [fantomas](https://github.com/fsprojects/fantomas).

### Steps To Reproduce
1. Create this simple `flake.nix` file:
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, utils, ... }:
    utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        packages = {
          fantomas = pkgs.buildDotnetModule rec {
            name = "fantomas";
            version = "5.0.6";

            src = pkgs.fetchFromGitHub {
              owner = "fsprojects";
              repo = "fantomas";
              sha256 = "sha256-b95Yha2VKA2Qr3IGCBc2lMXbQjg+FoFPtPwnGsWrOwA=";
              rev = "v${version}";
            };

            projectFile = "fantomas.sln";
          };
        };
      });
}
```
2. Run `nix build .#fantomas.fetch-deps` to generate the script
3. Run `./result`
4. See the `/nix/store/<hash>-nuget-to-nix/bin/nuget-to-nix: line 56: base_addresses[$used_source]: unbound variable` error

### Expected behavior
Be able to generate the lockfile.

### Notify maintainers

I guess @corngood was the one to introduce the variable there.

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11.20221016.104e808`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/mrpx61vyrmhqhr2ms9svscyc1h523gf1-source`
```

**Comment by corngood** [comment]
could you give #196681 a try?

**Comment by corngood** [comment]
The problem seems to be that there's a repo in the sdk at `sdk/6.0.401/FSharp/library-packs`, containing only `FSharp.Core.6.0.6.nupkg`.  This is somehow referenced implicitly.

I'm not sure if we should do anything more to handle this situation, but the message fix should do for now.
