### ISSUE TITLE
nodePackages.prisma-language-server

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#196730]
**Project description**
A language server for prisma files

**Metadata**

* homepage URL: https://www.npmjs.com/package/@prisma/language-server
* source URL: https://www.npmjs.com/package/@prisma/language-server
* license: apache 2.0
* platforms: all

**Comment by jupblb** [comment]
This is already packaged: https://github.com/NixOS/nixpkgs/blob/e8c05fe2e1a31a92731b92b6f78c2ff997d25e61/pkgs/development/node-packages/node-packages.json#L264
