### ISSUE TITLE
Haskell development shells are not very useful

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nixpkgs#196753]
`nix develop nixpkgs#haskellPackages.foo` gives me a shell without cabal, and if I add cabal myself it fails most of the time because of a missing system dependency (`pkg-config`, `zlib`, ...).

cc @sternenseemann @cdepillabout @maralorn

**Comment by ncfavier** [comment]
Thanks for writing such detailed answers to such an underspecified question! It seems like both `foo.env` and `shellFor` do what I want (use Nix for dependencies) and I can add `cabal-install` to the build inputs so this is good.

`developPackage` doesn't seem to use `ghcWithPackages` so it still runs into missing `pkg-config` stuff when trying to build a package depending on e.g. `gnuidn`.

Agreed that there's no bug here, just needs better documentation.

**Comment by maralorn** [comment]
I guess that makes this a duplicate of #121403. :D
