### ISSUE TITLE
networking.interfaces.<name?>.macAddress fails on some systems.

### ISSUE THREAD

**Issue by FPtje** [NixOS/nixpkgs#19676]
## Issue description

Setting a MAC address on an interface will fail when that interface is up and running. The code for setting the MAC address does not put the interface down:

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces.nix#L996

I can imagine that this code might work on some systems, where the service would be started before the interface is loaded, but on my system (a Raspberry pi 2) this definitely doesn't work:

```
stopping the following units: network-local-commands.service
activating the configuration...
setting up /etc...
starting the following units: network-local-commands.service
the following new units were started: network-addresses-eth0.service
warning: the following units failed: network-link-eth0.service

● network-link-eth0.service - Link configuration of eth0
   Loaded: loaded (/nix/store/3dqihpl96vk2w2qyqc5pfjvq7vazyhbw-unit-network-link-eth0.service/network-link-eth0.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2016-10-19 10:56:20 CEST; 336ms ago
  Process: 5764 ExecStart=/nix/store/h9w8lyahj2bsp2kghzn44w5akcck14jn-unit-script/bin/network-link-eth0-start (code=exited, status=2)
 Main PID: 5764 (code=exited, status=2)

Oct 19 10:56:20 rpibuild systemd[1]: Starting Link configuration of eth0...
Oct 19 10:56:20 rpibuild network-link-eth0-start[5764]: Configuring link...
Oct 19 10:56:20 rpibuild network-link-eth0-start[5764]: setting MAC address to <REDACTED>...
Oct 19 10:56:20 rpibuild network-link-eth0-start[5764]: RTNETLINK answers: Device or resource busy
Oct 19 10:56:20 rpibuild systemd[1]: network-link-eth0.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 19 10:56:20 rpibuild systemd[1]: Failed to start Link configuration of eth0.
Oct 19 10:56:20 rpibuild systemd[1]: network-link-eth0.service: Unit entered failed state.
Oct 19 10:56:20 rpibuild systemd[1]: network-link-eth0.service: Failed with result 'exit-code'.
error: unable to activate new configuration
```
## Solution

The solution is simple. Instead of just [setting the MAC address](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces.nix#L996), take the interface down and up too:

``` nix
ip link set dev "${i.name}" down
ip link set "${i.name}" address "${i.macAddress}"
ip link set dev "${i.name}" up
```

I've kind of tested this approach by using the above code in the `networking.localCommands` option. I don't know whether the interface is to be down when the MTU is set.
## Technical details

Nix version: 17.03.git.adfcc2d
nixpkgs: 1.11.4

**Comment by Profpatsch** [comment]
(triage) can you still reproduce this?

**Comment by FPtje** [comment]
Huh, no. I set up a few arm devices (non-pi) a couple of weeks ago and I wasn't confronted with this issue.

And nixos for our arm devices is still on 17.03. Odd.
