### ISSUE TITLE
pythonPackages.virtualenv fails to build because of dependency on freezegun-1.2.2 not supported for python 2.7

### ISSUE THREAD

**Issue by DrPyser** [NixOS/nixpkgs#196784]
### Steps To Reproduce
1. `nix build --show-trace nixpkgs#pythonPackages.virtualenv`

### Build log
https://gist.githubusercontent.com/DrPyser/25be8480294fdea1b0dc7b78619d3731/raw/2540fc8e8e88a226a573dc2f07d3d6639a37cecb/nix-build-pythonPackages.virtualenv.log

### Additional context
Trying to setup a basic python 2 development environment with support for virtualenv.

### Notify maintainers
@cillianderoiste 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.55, NixOS, 22.05 (Quokka), 22.05.20220720.26fe761`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-21.11.337967.573603b7fdb, nixos-unstable"`
 - channels(drpyser): `"home-manager-21.11, nixos-21.11.337011.e7d63bd0d50, nixos-unstable-22.05pre363562.30d3d79b7d3, nixpkgs-22.05pre363562.30d3d79b7d3"`
 - nixpkgs: `/home/drpyser/.nix-defexpr/channels/nixpkgs`
```

**Comment by fabaff** [comment]
`freezegun` dropped support for Python 2 a little over 2 years ago with [1.0.0](https://github.com/spulec/freezegun/blob/1.0.0/CHANGELOG). And I guess that `freezegun` would only be the start of module which dropped support for Python 3.

**Comment by DrPyser** [comment]
Ok, but why is it required ? If I understand correctly it's used for testing? I didn't ask to install this library, I asked for virtualenv from the python 2 package set. 
If freezegun is indeed required to build virtualenv for python 2, can't it be frozen to a previous version that supports python 2?

Or in other words, is there a way to get a working python 2 environment with virtualenv support through nix?

**Comment by mkohler** [comment]
> is there a way to get a working python 2 environment with virtualenv support through nix?

The way I'm handling a project that is being ported from Python 2 to Python 3 is that I'm using a Nixpkgs commit from the 20.09 release to create the Python 2 environment, and a commit from the 22.05 series to create the Python 3 environment.

**Comment by DrPyser** [comment]
Ok, thanks I'll try that!

**Comment by SuperSandro2000** [comment]
We could add an older version of freezegun to the python2 overlay but python2 is EOL and more and more parts are being removed. Also this seems to be broken for a longer time. Closing
