### ISSUE TITLE
llvm_39 llvm-config changes

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#19672]
## Issue description

The addition of the `lib` output also changes the user interface (!) of `llvm-config`.

### Steps to reproduce

`llvm-config` must now be invoked with nix-specific flags, `--link-static` or `--link-shared`.

## Problem

This means that any downstream uses of `llvm-config` will need nix-specific patches, which is not going to fly in my world at least.

## Question

Would having an `llvm_39-full` variant in `nixpkgs` that doesn't require special support be okay?

**Comment by acowley** [comment]
I'll try to figure out a solution on my end so I can offer a more concrete proposal beyond just disabling the `lib` output. I may be able to use a wrapper around `llvm-config` for scenarios where I want static linking.

**Comment by vcunat** [comment]
Are you sure about this? I tested this on Linux and it seemed OK (I patched llvm-config myself).

**Comment by vcunat** [comment]
BTW, the flags were always in there. I only added switching the libdir based on them.

**Comment by acowley** [comment]
Yes, but I think you could fairly say it's not your problem. `llvm-config --ldflags`, before this change, was enough for a build script that wanted to pull in specific static libraries. So it's a case of doing the wrong thing no longer working.

**Comment by vcunat** [comment]
I see. It's also possible I didn't fix some cmake detection. Fighting widely holding assumptions is complicated, sometimes.

**Comment by acowley** [comment]
I should also mention, despite this change causing me a bit of trouble, it's a really clever bit of patching. It's wonderful the way it works out in enabling smaller closure sizes without major surgery anywhere.

**Comment by vcunat** [comment]
:-) Well, autotools-based packages are often much easier to split, now that the framework is in place. (I've split roughly a hundred of them.)
