### ISSUE TITLE
Unable to update modified time on files in docker image

### ISSUE THREAD

**Issue by m4dc4p** [NixOS/nixpkgs#196804]
### Describe the bug
I'd like to update the modified date on some files stored in a docker image I'm building using `buildImage`, but I'm unable to figure out a way to do it.

### Steps To Reproduce
I would expect `extraCommands` to do what I want, but so far it does not. For example, I tried the following to set the modified date to today on all files in the layer:

```
  extraCommands = ''
    # Set modified time on all files to (now - 30 days); otherwise, all modified dates
    # are Jan 1, 1980 and browser's cache these assets indefinitely. Subtracted
    # 30 days in order to avoid clock drift.
    ${fd}/bin/fd . . -t f -x touch -am $(date +%s)
   '';
```

When I inspected the image, all the files were still date Jan 1, 1980.

I tried using `runAsRoot`, but don't have access to a linux machine with `kvm` so I wasn't able to try that.

### Expected behavior
I would expect the files (in the docker image) to have the date I set.

### Additional context
This docker image is used to serve static web content; I don't have ETag support, so the modified date on the file is a useful hint to browser's for caching (and, more importantnly, invalidating their cache).

### Notify maintainers
@roberth @zowoq @SuperSandro2000 

### Metadata

I'm using nixpkgs 21.11 release.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.10.3`
 - channels(...): `"home-manager-22.05.tar.gz, nixpkgs, nixpkgs-21.11-darwin-21.11-darwin"`
 - nixpkgs: `/Users/.../.nix-defexpr/channels/nixpkgs````

**Comment by SuperSandro2000** [comment]
Nix hardcodes a specific time to files to be reproducible. That cannot be turned off.

**Comment by m4dc4p** [comment]
> Nix hardcodes a specific time to files in the nix store to be reproducible. That cannot be turned off.

Understood. Is there any way to modify the files after they are put in the layer? It seemed like `runAsRoot` would do it, but that requires `kvm` & Linux ... hard for me to come by (don't ask).

Thanks for looking!

**Comment by roberth** [comment]
The other function `buildLayeredImage` has a `fakeRootCommands` that can be used to set all file attributes that go directly into an image layer tarball. If automatic separation into layers is ok for you, you may be able to use that function instead.
Otherwise, https://github.com/NixOS/nixpkgs/pull/122608 or some other refactoring is needed to achieve a similar effect.

**Comment by m4dc4p** [comment]
@roberth It looks like `tar` will override any modification time to `$SOURCE_DATE_EPOCH`:

```
              tar \
                --sort name \
                --numeric-owner --mtime "@$SOURCE_DATE_EPOCH" \
                --hard-dereference \
                -cf $out/layer.tar .
```

(https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/docker/default.nix#L902)

So in `fakeRootCommands` I could change `SOURCE_DATE_EPOCH` to get the effect I want?

**Comment by m4dc4p** [comment]
It didn't work. At least in 22.05, the `layer` tarball gets built before I have any chance to set `SOURCE_DATE_EPOCCH`. Honestly I just don't think this is possible with the tooling available (as you said). Thanks for looking at it! Closing for now.

**Comment by madjam002** [comment]
You can just patch `build-support/docker/default.nix` to remove all occurrences of `--mtime="@$SOURCE_DATE_EPOCH"` and then it works fine.

I have the same issue where I want to serve static assets and the modified date/time is needed like you said, this fixes it for me.

**Comment by m4dc4p** [comment]
How do I set the modified date on the files in that case? Glad to read docs
or look at an example! Thank you!
