### ISSUE TITLE
Remove `ardour_6` package once ardour 7 is stable

### ISSUE THREAD

**Issue by anoadragon453** [NixOS/nixpkgs#196841]
## Issue description

https://github.com/NixOS/nixpkgs/pull/196290 is adding ardour 7.0 to the repository. As noted by @magnetophon, 7.0 still experiences crashes. Thus we've opted to keep version 6.9 around for a little while for people to optionally use as a more stable base for their projects.

Once ardour 7.x (package name `ardour`) is deemed stable, ardour 6.x (package name `ardour_6`) should be removed from nixpkgs.

**Comment by ctem** [comment]
#259979 updated `ardour_6` to `ardour_7` in preparation for 8.0, so this issue should be either closed or updated. Fwiw, maintaining the package of the last stable release of the previous major version seems like a good tradition for Ardour.

**Comment by anoadragon453** [comment]
Thanks for pointing that out. I agree that keeping (at least) the last version around is helpful for some people who can't update for one reason or another.

If someone objects, they can create a new issue.
