### ISSUE TITLE
cc-wrapper doesn't process @option files

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#19680]
## Issue description

gcc accepts command line options to be passed as files, with the `gcc @option-file` syntax. The custom flag processing in our wrappers, however, doesn't recognize option files, thus can skip over flags that it would need to process.
This came up during chromium's transition from GYP to GN, as the latter utilizes `@option` files.

cc @aszlig @shlevy 
### Steps to reproduce

specify a `-l` .so library flag within an `@options` file, and watch ld not putting it on `rpath`
### WIP fix

I've attempted to fix this here https://github.com/bendlas/nixpkgs/commit/5718be35136f4c0d9021c407bb43ac2614cc59e3

but it's a pretty heavy rebuild, also bootstrap-cc-wrapper fails to build for some reason, so I'd like to get some feedback.
## Technical details
- System: 17.03-pre-eafa13369ffc19f5 (Gorilla)
- Nix version: 1.11.4

**Comment by shlevy** [comment]
FYI, I'm looking into options to seriously simplify our wrappers, in part because of this issue, but it will probably be a while so :+1:  on the general concept here.

**Comment by copumpkin** [comment]
Yeah, they're getting pretty big. It seems like the main job of the wrapper is to override default behavior that is not nix-friendly? Perhaps it's time to start looking at integrating our overrides into the underlying compiler codebases so we don't have to rederive a lot of their option parsing?

**Comment by shlevy** [comment]
Yeah, see thread starting at https://gcc.gnu.org/ml/gcc/2016-10/msg00122.html and especially the exchange with @civodul

**Comment by bendlas** [comment]
That's an interesting exchange. It seems though, that guix' approach doesn't deal with `@response` files either. There doesn't seem to be a way around unpacking them in the wrapper ...

**Comment by shlevy** [comment]
It gets rid of the cc wrapper and the ld wrapper could probably be removed by adding a simple patch to ld (haven't checked that yet though)

**Comment by bendlas** [comment]
Fixed in master https://github.com/NixOS/nixpkgs/commit/225602d9f2fc5d437e4996c9697dd272d18846c0

I've created a nixos test for this, but I can submit that as a separate PR
