### ISSUE TITLE
Oracle JDK no longer installable due to missing downloads

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#19690]
## Issue description

oracle did lots of updates, the old files cant be found

```
$ nixos-version 
16.09.741.354fd37 (Flounder)
```

pinging @grahamc as requested on irc

**Comment by RonnyPfannschmidt** [comment]
userconfig:

{
  allowUnfree = true;
  
  firefox = {
    jre = true;
    enableGoogleTalkPlugin = true;
    enableAdobeFlash = true;
  };

  chromium = {
    jre = true;
    enablePepperFlash = true; # Chromium's non-NSAPI alternative to Adobe Flash
    enablePepperPDF = true;
  };
}
```

**Comment by NeQuissimus** [comment]
Don't you have to pre-fetch the Oracle JDK yourself?
Oracle does not delete builds, they just move them into the Archive section of the website. The download URL should not change.

**Comment by RonnyPfannschmidt** [comment]
the download url was not given and from the website i could not find them, simply changing the url with a few experiments did not help

**Comment by NeQuissimus** [comment]
If I try to install Oracle JDK, it looks like this:

```
~> nix-env -i oraclejdk
installing ‘oraclejdk-8u102’
these derivations will be built:
  /nix/store/95nbz2hv1mkbagnixrqi55cnw7dbr0il-jdk-8u102-linux-x64.tar.gz.drv
  /nix/store/mp4gl0l9hgi7ybybsahmv6f6j8k2zmr8-oraclejdk-8u102.drv
these paths will be fetched (2.99 MiB download, 8.28 MiB unpacked):
  /nix/store/3spv495g80l4fzavczl8bahnkzi2nxi3-libav-0.8.17
  /nix/store/5ap0w9wvx3lx8im1x6k0kqq2hzrib4lm-pango-1.40.2-bin
  /nix/store/mlqr12j3yc032vn7ac5yjzhjyw4r91as-libav-0.8.17-bin
  /nix/store/x5rzzvpcf9sj29h6b55q4wpqgqg5szdq-libxslt-1.1.29-bin
fetching path ‘/nix/store/3spv495g80l4fzavczl8bahnkzi2nxi3-libav-0.8.17’...
fetching path ‘/nix/store/x5rzzvpcf9sj29h6b55q4wpqgqg5szdq-libxslt-1.1.29-bin’...
fetching path ‘/nix/store/5ap0w9wvx3lx8im1x6k0kqq2hzrib4lm-pango-1.40.2-bin’...
building path(s) ‘/nix/store/yx27ad4sn2l3bvzyyilyxhy2w254bjdg-jdk-8u102-linux-x64.tar.gz’

***
Unfortunately, we cannot download file jdk-8u102-linux-x64.tar.gz automatically.
Please go to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html to download it yourself, and add it to the Nix store
using either
  nix-store --add-fixed sha256 jdk-8u102-linux-x64.tar.gz
or
  nix-prefetch-url --type sha256 file:///path/to/jdk-8u102-linux-x64.tar.gz

***

builder for ‘/nix/store/95nbz2hv1mkbagnixrqi55cnw7dbr0il-jdk-8u102-linux-x64.tar.gz.drv’ failed to produce output path ‘/nix/store/yx27ad4sn2l3bvzyyilyxhy2w254bjdg-jdk-8u102-linux-x64.tar.gz’
killing process 11742
killing process 11741
killing process 11740
cannot build derivation ‘/nix/store/mp4gl0l9hgi7ybybsahmv6f6j8k2zmr8-oraclejdk-8u102.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/mp4gl0l9hgi7ybybsahmv6f6j8k2zmr8-oraclejdk-8u102.drv’ failed
exit 1
```

You can find 8u111 there. I agree it is a little confusing because 8u102 is nowhere on that page (the page always points to the latest Oracle JDK).
If you go to http://www.oracle.com/technetwork/java/javase/downloads/index.html you can find 8u102 in the `Java Archive`

**Comment by pradeepcheers** [comment]
@NeQuissimus I'm facing the same issue when I try to install Oracle JDK. So how can I fix the issue?

**Comment by vcunat** [comment]
@pradeepcheers: as written above, the files are still there but in the archive: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html

In any case, nix can't download the sources automatically, due to Oracle requiring you to agree with an EULA.

**Comment by pradeepcheers** [comment]
@vcunat, Then whats the easy way to install oracle jdk 8 on nixos? I'm new to nixos.

**Comment by vcunat** [comment]
There's nothing easier for *oracle* jdk; you have to download the tarball manually.

**Comment by tohl** [comment]
@pradeepcheers manual download, then nix-prefetch-url

**Comment by volth** [comment]
I have seen plenty of ```Dockerfile```s (Puppet scripts, etc) downloading Oracle JDK using ```wget --header 'Cookie: oraclelicense=accept-securebackup-cookie'```
Any legal restriction to do the same?

https://github.com/search?q=accept-securebackup-cookie&ref=simplesearch&type=Code&utf8=%E2%9C%93

**Comment by NeQuissimus** [comment]
You can download like that but not re-distribute.

**Comment by xpe** [comment]
When I run `nix-env -i oraclejdk` I get:

```
error: selector ‘oraclejdk’ matches no derivations
```

Is this the expected behavior?

I'm running macOS Sierra and `nix-env --version` returns "nix-env (Nix) 1.11.6".

**Comment by NeQuissimus** [comment]
Oracle Linux is marked as only functional on Linux systems: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/oraclejdk/jdk-linux-base.nix#L195

**Comment by xpe** [comment]
@NeQuissimus Thanks; this is expected then. It would then be a separate issue to ask for macOS support for the Oracle JDK.

**Comment by bledari** [comment]
Can this be applied to oracle's  Java server jre ?
