### ISSUE TITLE
MultiMC packaging request

### ISSUE THREAD

**Issue by DylanJava** [NixOS/nixpkgs#196912]
**Project description**
MultiMC is a custom launcher for Minecraft that focuses on predictability, long term stability and simplicity.
**Metadata**

* homepage URL: https://multimc.org/
* source URL: https://github.com/MultiMC/Launcher
* license: Apache 2.0 && MS-PL
* platforms: linux && macos

**Comment by pinkcreeper100** [comment]
@DylanJava I think this is unlikely to happen, but if you want a launcher similar, you could check out PrismLauncher, which will be in nixpkgs very soon

**Comment by zarlo** [comment]
@DylanJava you dont want this MultiMC's project owner will have a fit if we did this

**Comment by lucasew** [comment]
PolyMC and PollyMC are also great alternatives.

You can override PolyMC with PollyMC sources and it just works.

**Comment by zarlo** [comment]
i would use https://github.com/PrismLauncher/PrismLauncher over PolyMC as that project is more or less dead

**Comment by DylanJava** [comment]
Hey thank you for responding and suggesting prism launcher as an alternative to multimc and polymc as I don't want to use polymc [due to the recent drama](https://www.youtube.com/watch?v=FyS8ELbafN0) which sparked me to make this request.

Thank you,
Dylan.
