### ISSUE TITLE
LibreOffice 7.3.6.2 & 7.4.2.4 *.desktop files have incorrect binary names in Exec command

### ISSUE THREAD

**Issue by ianmjones** [NixOS/nixpkgs#196981]
### Describe the bug

The current unstable versions of libreoffice-still and libreoffice-fresh are unable to be launched via their *.desktop files as found in the derivation's `share/applications/` directory.

This means that for me, Rofi can no longer launch LibreOffice Writer etc.

### Steps To Reproduce
1. Update unstable channel
2. Add `libreoffice`, `libreoffice-still` or `libreoffice-fresh` as a package to be installed
3. nixos-rebuild switch
4. Try and run Writer or any other LibreOffice app from a desktop launcher

### Expected behavior

Should be able launch LibreOffice applications from a desktop launcher, e.g. Rofi.

### Screenshots

![2022-10-20-22-17-47_3000x2000_scrot](https://user-images.githubusercontent.com/4710/197060813-1b02aa3a-b83c-4252-a988-787f728a0839.png)

### Additional context

The desktop files are expecting `libreoffice7.3` as the binary name, but it's `libreoffice`:

![2022-10-20-22-24-15_2574x820_scrot](https://user-images.githubusercontent.com/4710/197061655-eb039af9-9da0-4561-b3bf-e7937503d17f.png)

It looks like in https://github.com/NixOS/nixpkgs/pull/196535 the renaming of binaries in *.desktop was removed.

The following was taken out for some reason...

```bash
    for f in $out/share/applications/*.desktop; do
      substituteInPlace "$f" \
        --replace "Exec=libreofficedev${major}.${minor}" "Exec=libreoffice" \
        --replace "Exec=libreoffice${major}.${minor}"    "Exec=libreoffice"
    done
```

### Notify maintainers

@gador

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.2, NixOS, 22.11 (Raccoon), 22.11pre418904.db25c4da285`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixos2205-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by peterhoeg** [comment]
Workaround until the fix hits a channel:

```
{
  environment.systemPackages = [
    (pkgs.resholve.writeScriptBin "libreoffice7.4"
    {
      interpreter = lib.getExe pkgs.bash;
      inputs = [ pkgs.libreoffice-qt ];
      execer = [ "cannot:${pkgs.libreoffice-qt}/bin/libreoffice" ];
    }
    ''
      set -eEuo pipefail

      exec libreoffice "$@"
    '')
  ];
}
```

You can of course also use `runCommand` or one of the many other script helpers to do this.
