### ISSUE TITLE
Port to stable

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19694]
We apply the label `Port to stable` if we want a PR to be merged into `master` as well as the latest release branch.

Maybe it is my git foo that is weak here but could somebody describe how you guys do that? GitHub seems to have no support for something like this in the web interface, so I assume there is a set of `git` commands to make this happen.
I have tried creating a second PR against the release branch but that would be a disaster as it merges everything from master, not just the PR's original commit.

And while we're at it: Should we create some sort of documentation for this?

**Comment by dezgeg** [comment]
From command line: checkout the release branch, then `git cherry-pick -x <commit-hash-of-master-commit>`.

Would be nice to have some web service / GUI to help with cherry-pick management.

**Comment by NeQuissimus** [comment]
I think I'm doing it :D
I needed an extra `-m 1` since my commit was a merge commit. But it works like a charm, thanks!

One thing left is whether we want to document this or is this general git knowledge people are assumed to know?

**Comment by grahamc** [comment]
Documented here: https://nixos.org/nixpkgs/manual/#idm140737317704208

**Comment by vcunat** [comment]
Nothing left, I guess.

> Would be nice to have some web service / GUI to help with cherry-pick management. 

Side note: gitlab does offer a button for cherry-picking, but that's not much of a help in this repo.
