### ISSUE TITLE
On OSX python package breaks on upgrade

### ISSUE THREAD

**Issue by jnsaff** [NixOS/nixpkgs#19691]
## Issue description
On OSX packages python-2.7.12 and python-2.7.12-bootstrapped-pip-8.1.2 get confused. One can manually request python-2.7.12 but on nix-env --upgrade it gets automatically upgraded to python-2.7.12-bootstrapped-pip-8.1.2 which is actually pip only and does not provide python.

### Steps to reproduce
Jaanuss-MacBook-Pro:~ jaanus$ nix-env -q

Jaanuss-MacBook-Pro:~ jaanus$ which python
/usr/bin/python

Jaanuss-MacBook-Pro:~ jaanus$ nix-env -i python
installing ‘python-2.7.12-bootstrapped-pip-8.1.2’

Jaanuss-MacBook-Pro:~ jaanus$ which python
/usr/bin/python

Jaanuss-MacBook-Pro:~ jaanus$ nix-env -e python-2.7.12-bootstrapped-pip-8.1.2
uninstalling ‘python-2.7.12-bootstrapped-pip-8.1.2’

Jaanuss-MacBook-Pro:~ jaanus$ nix-env -q

Jaanuss-MacBook-Pro:~ jaanus$ nix-env -i python-2.7.12
installing ‘python-2.7.12’

Jaanuss-MacBook-Pro:~ jaanus$ which python
/Users/jaanus/.nix-profile/bin/python

**Jaanuss-MacBook-Pro:~ jaanus$ nix-env -u
upgrading ‘python-2.7.12’ to ‘python-2.7.12-bootstrapped-pip-8.1.2’**

Jaanuss-MacBook-Pro:~ jaanus$ which python
/usr/bin/python

Jaanuss-MacBook-Pro:~ jaanus$

## Technical details

* System: macOS Sierra 

* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre91860.124f25b"

**Comment by vcunat** [comment]
This isn't Darwin-specific.
```
$ nix-env -qa python
python-2.6.9
python-2.7.12
python-2.7.12
python-2.7.12
python-2.7.12-bootstrapped-pip-8.1.2
python-3.5.2-bootstrapped-pip-8.1.2
```
