### ISSUE TITLE
Pulseaudio works incorrectly

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nixpkgs#19695]
## Issue description

I'm using PA for 2 years. Today I've updated nixos to the latest nixos-unstable (https://hydra.nixos.org/build/42069678) and the sound quality became awful. Because every program is using ALSA somehow :confused:.
What is that? Am I alone with this problem?

cc @lovek323

**Comment by ericsagnes** [comment]
Have you tried to clean the pulseaudio related files in `/tmp`? 

I had a problem with pulseaudio not working after a recent update, cleaning `/tmp` by setting `boot.clearTmpDir = true` and rebooting solved the problem.

**Comment by jagajaga** [comment]
@ericsagnes that didn't help :(

**Comment by jagajaga** [comment]
It seems that everything is trying to use alsa... Ideas?

**Comment by Mic92** [comment]
@jagajaga you could debugs this strace. Applications use unix sockets to connect to pulseaudio.

```bash
strace mpv ~/Musik/song.mp3
...
connect(12, {sa_family=AF_UNIX, sun_path="/run/user/1000/pulse/native"}
...
````

1000 is your user id.

**Comment by jagajaga** [comment]
@Mic92 
```
connect(9, {sa_family=AF_UNIX, sun_path="/run/user/1000/pulse/native"}, 110) = 0
```
I have such line but application still using alsa.

**Comment by Mic92** [comment]
any errors, when writing to fd 9 afterwards?

**Comment by jagajaga** [comment]
@Mic92 
https://gist.github.com/jagajaga/49a8c9376795dc993f60ce7c94657706
I see this. So it is closing `9` and trying native.
