### ISSUE TITLE
Clicking on links does not open browser on discord.

### ISSUE THREAD

**Issue by j0lol** [NixOS/nixpkgs#197088]
### Describe the bug
Whenever i click on a link in discord, it does not open the link in discord.

### Steps To Reproduce
1. launch discord
2. click link

### Expected behavior
Link to open in firefox

### Notify maintainers
MP2E@archlinux.us 
drsingh2518@icloud.com 
artturin@artturin.com 
infinidoge@inx.moe

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.2, NixOS, 22.11 (Raccoon), 22.11pre419179.b7d8c687782`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Artturin** [comment]
the emails won't ping us.

open discord via the terminal and try to open a link, if it fails silently then its https://github.com/NixOS/nixpkgs/issues/78961, if there's a error then send it

**Comment by j0lol** [comment]
whoops! yeah it fails silently.
