### ISSUE TITLE
python3Packages.cupy is broken

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#197073]
### Describe the bug

From what I could tell this was only mentioned in some comment of a closed PR.

This is blocking me from wrapping up a flake for Invoke AI (a Stable Diffusion webui).

Any help/advice would be appreciated.

This was described on Discourse by @aidalgol : https://discourse.nixos.org/t/undefined-symbol-in-pyx-based-package/22025

```
cupy_backends/cuda/libs/cutensor.cpp:5717:17: error: ‘CUTENSOR_VERSION’ was not declared in this scope; did you mean ‘CUTENSOR_OP_SIN’?
```

**Comment by tpwrules** [comment]
What commit of nixpkgs are you using? I might have some cycles this weekend to spend on this.

**Comment by tpwrules** [comment]
Looks like the cause is an outdated version of cutensor. It appears cupy is the only dependent of that so hopefully an upgrade is simple.
