### ISSUE TITLE
eog: add libjxl for jpegxl support

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#197005]
### Describe the bug
Image Viewer (previously eye of gnome) can't display jpeg xl images. According to [this bug report](https://gitlab.gnome.org/GNOME/eog/-/issues/167), all it would take for it to show images is to install libjxl, but on nixOS this isn't enough.

### Steps To Reproduce
1. Open a jpegxl image with eog
2. It says that it's an unrecognized format
3. ...

### Expected behavior
Being able to see jpegxl images

### Notify maintainers
@jtojnar 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.2-zen1, NixOS, 22.11 (Raccoon), 22.11pre418157.104e8082de1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(m911t): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by jtojnar** [comment]
Right, NixOS does not support just installing libraries and having programs find them, see https://nixos.wiki/wiki/FAQ#I_installed_a_library_but_my_compiler_is_not_finding_it._Why.3F.

Specifically, for this to work, we need:

- Building gdk-pixbuf module for libjxl https://github.com/NixOS/nixpkgs/blob/0b8181e2640ddb98ac1c4e76cd5e8e68dde4dd79/pkgs/development/libraries/libjxl/default.nix#L135
- Support for merging/multiple GDK pixbuf caches: https://github.com/NixOS/nixpkgs/pull/153275
- Adding `libjxl` as a dependency to `eog` and all other programs that want to use it.

See also the same thing for [webp](https://github.com/NixOS/nixpkgs/issues/196428) and [avif](https://github.com/NixOS/nixpkgs/pull/102189) codecs and [geeqie program](https://github.com/NixOS/nixpkgs/issues/182594).
