### ISSUE TITLE
ocaml build system is not documented in nixpgs manual

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#19716]
## Issue description

The nixpkgs manual has a section for many programming language, but not ocaml. buildOcaml should be documented there.

**Comment by aske** [comment]
Yeah, we should do this. Though, I'm thinking about changing current ocaml system further-- maybe even more like current haskell infrastructure  (not likely to actually happen, though, aside from some cosmetic and utilitarian changes); probably require some discussion once I'll have a clearer idea where to go.

**Comment by FlorentBecker** [comment]
Are you thinking of something like opam2nix?

**Comment by aske** [comment]
Wow, I've missed it for some strange reason. Thanks!
Yeah, opam2nix plus possibly some kind of oasis2nix.

**Comment by mpickering** [comment]
Some documentation about this would be good! Even one paragraph would help people to get started.

**Comment by CMCDragonkai** [comment]
How does `buildOcaml` work with `ocaml-ng`?

**Comment by sternenseemann** [comment]
`buildDunePackage` which is the most relevant atm is documented in the manual by now. If any issues persist its probably better to open a new one.
