### ISSUE TITLE
ImHex finds multiple builtin plugins

### ISSUE THREAD

**Issue by Garmelon** [NixOS/nixpkgs#197109]
### Describe the bug
When launching `imhex`, the main window is greyed out and can't be interacted with. A second window opens with the following text:

> ImHex found and attempted to load multiple built-in plugins!
> Make sure you installed ImHex correctly and, if needed,
> cleaned up older installations correctly,
> There should be exactly one 'builtin.hexplug' file in any one your plugin folders.

A list of paths follows. Only the following two have a checkmark in the "Exists" column, all others have a cross:
- `/run/current-system/sw/share/imhex/plugins/builtin.hexplug`
- `/nix/store/kqwpmv4mlxqvd785g46gnr8zr9c9rb13-imhex-1.19.3/bin/plugins/builtin.hexplug`

On stdout, `imhex` prints `[21:31:21] [ERROR] [main] Found more than one built-in plugin!`

### Steps To Reproduce
0. Use gnome?
1. Install and launch ImHex

### Expected behavior
ImHex launches normally and can be interacted with.

### Screenshots
![image](https://user-images.githubusercontent.com/11077553/197277646-f86b20b6-b89e-49fa-8ced-9c944b6a12a3.png)

### Additional context
A few days ago in #184488, it seemed to work for people. The `imhex/default.nix` file wasn't changed since then.

### Notify maintainers
@Luis-Hebendanz @peterhoeg

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre419179.b7d8c687782`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager, nixos"`
 - channels(joscha): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by Garmelon** [comment]
Possible workaround:
1. Launch imhex with a non-existing file as argument. The "file could not be opened" error message seems to prevent the built-in plugin error message from showing up.
2. Close the error popup
3. Open files via the UI normally.

If imhex crashes, just retry from step 1. If the UI layout is messed up after step 3, reset it via the "Layout" menu option.

This is the "Loaded Plugins" table when using this workaround:
![image](https://user-images.githubusercontent.com/11077553/197279108-e8ddecb9-192b-48fe-bce3-6cd35f24f778.png)

**Comment by Garmelon** [comment]
Another note: When running imhex via nix-shell on a system where it is not installed, it seems to find no built-in plugins at all.

**Comment by LegitMagic** [comment]
I've also had this issue, although something odd that I had occur was ImHex working on one user, but not working on another user.
