### ISSUE TITLE
ocamlPackages.foo.overrideDerivation does not put new buildInputs in OCAMLPATH

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#19718]
## Issue description

using overrideDerivation with an ocaml package to add an (ocaml) buildInput does not add the new buildInput to OCAMLPATH. This makes adding a new ocaml dependency to an ocaml derivation tedious.
### Steps to reproduce

See attached file. Running 'nix-shell issue.nix' should not echo 'cannot find uchar'
[issue.nix.txt](https://github.com/NixOS/nixpkgs/files/541398/issue.nix.txt)
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.2
- Nixpkgs version:  
  $ echo `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion` `git describe --long`
  "17.03pre-git" 16.09-beta-3435-ge2bb0c5

**Comment by aske** [comment]
That shoud work with `overrideAttrs` function from #18660.
I'll try it a bit later; please write here if that successfully deals with the problem.

**Comment by aske** [comment]
Just tested with cherry-picked change from that PR. Seems to be working fine.

**Comment by aneeshusa** [comment]
I believe this issue can be closed now that `overrideAttrs` is merged.
