### ISSUE TITLE
Enhancement: enable dynamic triple/double buffering (v4) in gnome.mutter

### ISSUE THREAD

**Issue by VolodiaPG** [NixOS/nixpkgs#197181]
**Project description**
This [merge request 1441](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1441) in mutter enables smoother animations and thus a global quality of life improvement on the responsiveness and feel of the whole gnome DE (tested on both a high-end and a lower-end device with respectively external and integrated GPUs).

Additionnaly, this patch is already present in other distros, such as Ubuntu in their [launchpad, here for Kinetic (22.10)](https://git.launchpad.net/ubuntu/+source/mutter/tree/debian/patches/debian/Support-Dynamic-triple-double-buffering.patch).

I believe it would be a good quality of life enhancement to include this patch in Nixos' gnome.

**Feasibility**
From this [commit](https://github.com/NixOS/nixpkgs/blob/c737f113067b5f5bd118c027d5b4a0b9db5e2068/pkgs/desktops/gnome/core/mutter/default.nix) of mutter in nixpkgs I had to override the package `src` to use the latest version on the main branch of mutter. I had to remove patch 2627 about color-device because it was failing to apply for reasons I did not investigate ; Ubuntu applies the same patch successfully with 1441 too, so it looks feasible.

**Maintainers**
@jtojnar 

**P.S.**
<details>
<summary>The override looks something like that</summary>
In an overlay:

```nix
final: prev: {  
  gnome = prev.gnome.overrideScope' (gself: gsuper: {
    mutter = gsuper.mutter.overrideAttrs (oldAttrs: {
      src = prev.fetchgit {
        url = "https://gitlab.gnome.org/GNOME/mutter";
        rev = "184055b2bb7119566cada1eb632a5ab9471fe558";
        sha256 = "sha256-hMzPzZEJPyF1H47y2X4uSVnDPbtyMkELNZxV2c1RPck=";
      };
      
      patches = [
          # Fix build with separate sysprof.
          # https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2572
          (prev.fetchpatch {
            url = "https://gitlab.gnome.org/GNOME/mutter/-/commit/285a5a4d54ca83b136b787ce5ebf1d774f9499d5.patch";
            sha256 = "/npUE3idMSTVlFptsDpZmGWjZ/d2gqruVlJKq4eF4xU=";
          })
        ./1441-main.patch
      ];
    });
  });
}
```

where `1441-main.patch` is directly generated from applying [mutter's 1441 MR](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1441.patch) on rev `184055b2bb7119566cada1eb632a5ab9471fe558` of mutter and then issuing a git diff.
</details>

**Comment by jtojnar** [comment]
Thanks for the suggestion.

I believe Ubuntu ships the patch because they created it. We are aiming for as close to a vanilla GNOME experience as practical so I do not think it makes sense to apply random patches, especially when they are still being worked on. Moreover, we do not have resources to review the patch in depth and QA it, especially with release freeze in effect.

**Comment by VolodiaPG** [comment]
Understood, I was finding odd such a patch was not applied yet, now I get why ; the reason was way above my head ^^'

Thanks for taking time to reply, I'll close this then.

**Comment by Henry-Hiles** [comment]
What about an option? Or a seperate package?

**Comment by jtojnar** [comment]
Adding that would be easy, the hard part is continued maintenance as GNOME Shell receives updates. That is what we want to avoid.

Nothing prevents you from maintaining an overlay, if you are interested, though.

**Comment by Henry-Hiles** [comment]
Yes I know, I'd just prefer what I mentioned.
