### ISSUE TITLE
Add information on contributing documentation in the nixpkgs manual

### ISSUE THREAD

**Issue by yukiisbored** [NixOS/nixpkgs#197233]
## Problem

The Nixpkgs manual contains information on how to contribute packages but lacks information on how to contribute content to the manual itself.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

As the manual contains detailed project-specific information on contributing to the project, it should also contain information on contributing to the manual itself.

**Comment by ncfavier** [comment]
Did you find https://nixos.org/manual/nixpkgs/unstable/#chap-contributing yet?

**Comment by yukiisbored** [comment]
Thanks, I must have missed it.
