### ISSUE TITLE
KWinFT

### ISSUE THREAD

**Issue by aarmn** [NixOS/nixpkgs#197356]
**Project description**
Wayland compositor and X11 window manager (a reboot of KWin)

* homepage URL:
* source URL: https://gitlab.com/kwinft/kwinft
* license: gpl
* platforms: linux

**Comment by InternetUnexplorer** [comment]
I think there's already https://github.com/NixOS/nixpkgs/issues/158827?

**Comment by aarmn** [comment]
> I think there's already #158827?

I checked from [nixpkgs search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=kwinft) on unstable channel

**Comment by kunihir0** [comment]
KwinFT would be amazing to have on a nixos kde build

**Comment by kunihir0** [comment]
https://gitlab.com/kwinft/kwinft

its actively being developed

**Comment by aarmn** [comment]
> I think there's already #158827?

I don't know why that day I didn't get it, you mean it's duplicate issue, sure I close it as duplicate of #158827
