### ISSUE TITLE
Trilium Notes

### ISSUE THREAD

**Issue by aarmn** [NixOS/nixpkgs#197340]
**Project description**
Build your personal knowledge base with Trilium Notes

* homepage URL: https://github.com/zadam/trilium/wiki
* source URL: https://github.com/zadam/trilium
* license: AGPL v3
* platforms: linux, darwin

**Comment by SuperSamus** [comment]
Isn't `trilium-desktop` already in nixpkgs?

**Comment by aarmn** [comment]
Right, my fault
