### ISSUE TITLE
widelands 1.1

### ISSUE THREAD

**Issue by jcumming** [NixOS/nixpkgs#197395]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: widelands
current version: 1.0
desired version: 1.1

###### Notify maintainers

maintainers: @jcumming 

###### Note for maintainers

The widelands devs sent us an email about the release. I think this is a first for me.

---

> Dear package maintainers,
>
> the Widelands Development Team is proud to announce that a new version
> of Widelands, 1.1, has been released.
>
> Widelands is a free, cross-platform economy strategy game in which
> players control the fate of a small tribe that can grow into a big
> empire, in a style of play that is unique in the open source world.
> Please visit our homepage at https://www.widelands.org to learn more.
>
> The source code for release 1.1 as well as the full release statement
> can be found under the following link:
> https://github.com/widelands/widelands/releases/tag/v1.1
>
> There have been several changes to the dependencies of Widelands since
> the release of version 1.0:
>
> - Minizip is now an optional and recommended dependency. If it is
> packaged on your system, please use it as a dependency. If Widelands
> does not detect it as a system library, the embedded minizip sources
> will be used.
> - Boost is no longer a dependency.
> - Asio is a new dependency. On systems where Asio is not packaged, you
> can use the `utils/download_asio.sh` script to pull in the sources
> before compiling.
> - Generated binaries are now placed in standards-compliant directories.
> Visit https://github.com/widelands/widelands/pull/5359 to learn more in
> case you need to update any paths.
> - I would like to note that Lua is not a dependency for Widelands. We
> ship a complete non-standard Lua implementation with the source code.
>
> Please update your packaging workflows accordingly.
>
> We would greatly appreciate it if the new version was picked up into the
> repositories of the various operating systems and distributions.
>
> Thank you very much!
> Best regards,
> Benedikt Straub

**Comment by jcumming** [comment]
I'm working on a PR for this (and once I figure out the github UI, I'll assign it to myself)..

**Comment by tjni** [comment]
Closing since https://github.com/NixOS/nixpkgs/pull/197492 fixes this. Please reopen if I'm wrong.
