### ISSUE TITLE
Kibana still failing with Elasticsearch - cherry pick request

### ISSUE THREAD

**Issue by jpierre03** [NixOS/nixpkgs#19739]
## Issue description

Refers to #19012 .  Kibana is broken at runtime "_This version of Kibana requires Elasticsearch ^2.4.0 on all nodes. I found the following incompatible nodes in your cluster: Elasticsearch v2.3.4 @ 127.0.0.1:9200 (127.0.0.1)_" 

This bug is fixed on "master" but is not backported in "release-16.09". 

### Steps to reproduce

1. in `configuration.nix` -> 
~~~
services.elasticsearch = {
    enable = true;
    port = 9200;
    listenAddress = "127.0.0.1";
};

services.kibana = {
    enable = true;
    elasticsearch.url = "http://127.0.0.1:9200";
    port = 8000;
}; 
~~~

2. with a browser (http://localhost:8000)[http://localhost:8000]

## Technical details

* System: NixOS: 16.09.773.b8ede35 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.773.b8ede35

**Comment by abuibrahim** [comment]
+1 for merging it to into release-16.09.

I cherry-picked it from master locally and was able to bring up Kibana with ElasticSearch.

**Comment by jpierre03** [comment]
cc @rasendubi

**Comment by rasendubi** [comment]
https://github.com/NixOS/nixpkgs/pull/19974

**Comment by jpierre03** [comment]
Thanks !
