### ISSUE TITLE
`drive` can't pull files, needs update

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#19749]
The version of the `drive` package in nixpkgs is affected by [an
issue] [drive issue] that prevents it from pulling (downloading)
files from Google Drive; this issue should be fixed if the package is
updated to version 0.3.8 or newer (the current version being 0.3.8.1).

(I would update it myself, but I lack sufficient familiarity with Go
and `go2nix`.)

[drive issue]: <https://github.com/odeke-em/drive/pull/735>

**Comment by Mic92** [comment]
If the following works for you, can open it as a pull request:

```
https://gist.github.com/anonymous/c76c620c789b099f06b60108232b3676
```

**Comment by 8573** [comment]
@Mic92: That seems to work, thanks! Did you mean that you or I would
file the PR?

**Comment by Mic92** [comment]
@8573 you can.

**Comment by 8573** [comment]
I've filed the PR.

**Comment by vcunat** [comment]
Merged.
