### ISSUE TITLE
CPU frequency is always pushed at max on NixOS

### ISSUE THREAD

**Issue by gnidorah** [NixOS/nixpkgs#19757]
## Issue description

On Dell 7559 laptop with Intel Skylake 6300HQ CPU frequency is always seen pushed to max on NixOS, no matter which kernel version I use or whether I'm on battery or not; while frequency is seen lowered fine on Ubuntu. Am I missing something?

### Steps to reproduce

lscpu | grep MHz
powertop
both NixOS installer and installed system are affected

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by gnidorah** [comment]
Ah, its just the cpufreq scaling governor is set to powersave on Ubuntu, but to performance on NixOS.
Closing, sorry for the noise.

**Comment by NeQuissimus** [comment]
Ah, you figured it out already...
I was about to post that this is what works for me:

```
  powerManagement = {
    enable = true;
    cpuFreqGovernor = "ondemand";
  };
```

**Comment by gnidorah** [comment]
@NeQuissimus Thank you! Additionally I found this: https://github.com/NixOS/nixpkgs/issues/9611#issuecomment-138880363

**Comment by Mic92** [comment]
I was not aware of this setting, is `performance` really a good default for most people?

**Comment by gnidorah** [comment]
@Mic92 I believe it should be either ondemand or powersave (for recent Intel CPUs) https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/power-management.nix#L72
But setting to powersave is still not fixed, that's why I got performance.

**Comment by concatime** [comment]
> Depending on the scaling driver, one of these governors will be loaded by default:
ondemand: for AMD and older Intel CPU.
powersave: for Intel CPUs using the intel_pstate driver (Sandy Bridge and newer).

https://wiki.archlinux.org/index.php/CPU_frequency_scaling#Scaling_governors

But this issue is now resolved with https://github.com/NixOS/nixpkgs/pull/21423
