### ISSUE TITLE
emojione font not picked up by system

### ISSUE THREAD

**Issue by despairblue** [NixOS/nixpkgs#19754]
## Issue description

The [emojione](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/data/fonts/emojione/default.nix) is not picked up by the system.

It's not in `/run/current-system/sw/share/X11-fonts` although `fonts.enableFontDir` is set to `true`.

I had to do `gnome-font-viewer /run/current-system/sw/share/fonts/truetype/EmojiOneColor-SVGinOT.ttf` and click install, so that it is installed to `~/.local/share/fonts`, to make it work.

Otherwise neither chrome, nor atom nor the gnome-font-viewer would pick it up.

### Steps to reproduce

Add `emojione` to `environment.systemPackages = with pkgs; [ ... `.

## Technical details

* System: 16.09.741.354fd37 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.741.354fd37"

**Comment by Mic92** [comment]
try the following instead:

```
# /etc/nixos/configuration.nix
  fonts = {                                                                                                                                                                  
     enableFontDir = true;                                                                                                                                                   
     fonts = with pkgs; [ 
         emojione                                                                                                                                                                                                                                                                                                                     
     ];                                                                                                                                                                      
  }; 
```

**Comment by despairblue** [comment]
@Mic92 awesome, that worked!
