### ISSUE TITLE
Running the brackets editor in a terminal fails

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#19760]
## Issue description
Launching `brackets` after installation yields the following error:
```
→ brackets
/home/nix/.nix-profile/bin/brackets: /nix/store/xrkgb8r0qpm6c5n25ddansxqyv0pw3iw-brackets-1.5/opt/brackets/.brackets-wrapped: /bin/bash: bad interpreter: No such file or directory
/home/nix/.nix-profile/bin/brackets: line 3: /nix/store/xrkgb8r0qpm6c5n25ddansxqyv0pw3iw-brackets-1.5/opt/brackets/.brackets-wrapped: Success
```
### Steps to reproduce
In a terminal:
1. → nix-env -iA nixos.brackets
2. → brackets

## Technical details

* System: 
```
→ nixos-version 
16.09.773.b8ede35 (Flounder)
```

**Comment by NeQuissimus** [comment]
Let me take a look. I think `brackets` is skipping the `fixupPhase`

**Comment by NeQuissimus** [comment]
I fixed the package and gave you an update while I was at it :) See the linked PR

**Comment by PierreR** [comment]
Thanks, it works like charm.
