### ISSUE TITLE
bind: binary collision / multiple outputs

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19761]
## Issue description

The symlinking between the multiple outputs of `bind` seems to prevent it from installing.
I was looking to install it to have the dig command available.

```
~> nix-env -i bind
zsh: correct 'bind' to 'bin' [nyae]? n
warning: name collision in input Nix expressions, skipping ‘/home/nequi/.nix-defexpr/channels_root/nixos’
warning: there are multiple derivations named ‘bind-9.10.4-P3’; using the first one
installing ‘bind-9.10.4-P3’
building path(s) ‘/nix/store/8zy9ryikg7g1rzb5hdqnd1afbq3c9yy7-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/6gsiyapnwdclchhwrc85q6xgnc4iy109-bind-9.10.4-P3-dnsutils/bin/dig’ and ‘/nix/store/3w0qvrrhfa5q357g9wj2idfwb3gldpq3-bind-9.10.4-P3-bin/bin/dig’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/wpb6vi8dzhji4gsmcbm8g904zwv6m0as-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/wpb6vi8dzhji4gsmcbm8g904zwv6m0as-user-environment.drv’ failed
exit 100
```
### Steps to reproduce
- `nix-env -i bind`
## Technical details
- System: 17.03pre94050.9b2fbb7 (Gorilla)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: "17.03pre94050.9b2fbb7"

**Comment by vcunat** [comment]
1.11.4 still doesn't contain https://github.com/NixOS/nix/pull/815 :-( How could we have that as default in 16.09? I consider it quite an important feature for `nix-env` + multiple outputs. @edolstra: would you be against porting that PR to 1.11.5 and making that default in 16.09 and master?

**Comment by NeQuissimus** [comment]
+1 for a 1.11.5 Nix release in general :)

**Comment by NeQuissimus** [comment]
Since this seems to be an issue for multiple packages, I am raising the severity on here.

**Comment by bjornfor** [comment]
Looks like the same kind of issue as https://github.com/NixOS/nixpkgs/issues/18839. So +1 for Nix 1.11.5 on NixOS 16.09, if that's what it takes to fix this.

**Comment by vcunat** [comment]
@edolstra: ping about nix-1.11.5 (my comment above).
