### ISSUE TITLE
Don't log network rejects to console on NixOS ISO

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#19764]
## Issue description

I'm maintaining a server which was on net for several years before, having loaded NixOS ISO for that. It's very difficult to work with terminal because I get interrupted every several seconds with rejected scanning attempts -- I need to write every command several times hoping that this time no reject would come while I type it and verify that everything is correct. It therefore introduces possibilities for typos (because often you don't see the full line you typed) and general frustration (disclosure: my current main concern ~_^).

![rejects](https://cloud.githubusercontent.com/assets/1174810/19618369/74d825d6-9859-11e6-968c-8ea5f5496758.jpg)
### Steps to reproduce
1. Boot server from NixOS ISO;
2. Spam it with TCP connections on closed ports from outside;
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) NixOS pre17.03 09e4b78

**Comment by NeQuissimus** [comment]
I tend walk to into our server room and rip out the Ethernet cords until I am done with the initial setup for that very reason :D

**Comment by jokogr** [comment]
I personally change `boot.consoleLogLevel` for my ISO images as seen at https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/nixos/modules/installer/cd-dvd/iso-image.nix#L235, but I guess lowering it could hide more important system issues.

**Comment by dtzWill** [comment]
On my NixOS install I use `networking.firewall.logRefusedConnections = false` in configuration.nix to squelch these from spamming constantly, perhaps that should be the default?

Sounds like the real issue is it's logging to your console, interrupting your workflow, which definitely should only be done for critical problems per suggestions by @jokogr.

**Comment by vcunat** [comment]
Heh, my actions are logged as abbradar's.

**Comment by vcunat** [comment]
GitHub seems to have fixed this fast!
