### ISSUE TITLE
Have hydra mark available PRs

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#19773]
Is there a way we could have Hydra mark PRs with a label or something similar once the change has been released to the targeted channel.

Say I have a PR in master, Hydra would over time add labels for `available: nixpkgs-unstable`, `available: nixos-unstable-small` and `available: nixos-unstable`. Similarly, changes to 16.09 would eventually tagged with labels for the two channels for it.

**Comment by vcunat** [comment]
That's just about `git branch --reachable PR-commit` run on nixpkgs-channels repo. Maybe it's possible to make github show such info, perhaps some bot can do it.

**Comment by NeQuissimus** [comment]
But then we would have to go across repos, would we not? Grab master on `nix-channel` and see if a PR from `nixpkgs` is in there?!
I figured it would be easier to have Hydra do that since it already touches both repos.

**Comment by vcunat** [comment]
Pushing to git and commenting on issues (or labeling them) are rather different things, but yes, it shouldn't be difficult to implement as part of the channel-update mechanism run on Hydra.

**Comment by domenkozar** [comment]
I think it's better to zoom out here and think about what information exactly you need and then we can discuss the implementation.

**Comment by NeQuissimus** [comment]
I was thinking about this in the context of updates that fix vulnerabilities. Once we commit the fix, it still takes a little while until users can pull the update off the channels. How do users know when the update is available?

**Comment by domenkozar** [comment]
I'd then propose to close this and continue in https://github.com/NixOS/nixpkgs/issues/13515

**Comment by NeQuissimus** [comment]
OK, sure. I had simply hoped for a more general solution.

**Comment by vcunat** [comment]
Hmm, there's a relatively easy way to find out, e.g. click link https://github.com/NixOS/nixpkgs-channels/commit/c2922a9 and you see a list of channels containing the commit in there. It's not perfect, e.g. this one doesn't show nixos-unstable-small, presumably because it points to exactly the same commit as nixos-unstable ATM.
