### ISSUE TITLE
Bugfix -> deltachat-desktop 

### ISSUE THREAD

**Issue by stnert** [NixOS/nixpkgs#197796]
According to the tests made with the binary, the problem is in the libdeltachat version, I have up the default.nix for more information. 

Thanks to support -> @hugosenari

Print of build -> ![Screenshot from 2022-10-25 17-36-12](https://user-images.githubusercontent.com/48295298/197886399-2f32f894-0a37-4779-809b-3a03642e8462.png)

Default.nix with the corrections  -> https://github.com/stnert/My-Configuration-NixOS/blob/main/default.nix

###### Notify maintainers
@thiagokokada @Misterio77 

maintainer:
 
@dotlambda

**Comment by hugosenari** [comment]
https://github.com/NixOS/nixpkgs/issues/195741
