### ISSUE TITLE
Packaging request: nodePackages.webppl

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#197750]
**Project description**
 Probabilistic programming for the web 

**Metadata**

* homepage URL: https://www.npmjs.com/package/webppl
* source URL: https://github.com/probmods/webppl
* license: mit
* platforms: unix, linux, darwin

**Note**

I had problems getting this to work. I always got an error message stating that the package `canvas` (part of nodejs) was not available. I hope someone can figure this out!

**Comment by SuperSandro2000** [comment]
Closing because of staleness
