### ISSUE TITLE
Virtual devices created in pipewire do not show up as audio inputs in qtwebengine-based browsers

### ISSUE THREAD

**Issue by Astavie** [NixOS/nixpkgs#197728]
### Describe the bug
I found this bug while trying to create a package for [discord-screenaudio](https://github.com/maltejur/discord-screenaudio) (mentioned in #186957), but it seems all qtwebengine-based browsers like Qutebrowser and Falkon have the same issue.

These browsers are able to pick up my microphone just fine, but any virtual devices created via pipewire do not show up. discord-screenaudio creates a virtual source to pipe desktop audio through, which then is meant to be detected as an audio input inside a qtwebengine window linked to discord.com.

Creating virtual devices manually via `pactl` (following [this guide](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices)) also doesn't work, as they do not show up in Qutebrowser or Falkon. They do show up in Firefox, Chromium, and the native Discord client, however.

### Steps To Reproduce
1. have pipewire running as the audio server
2. create a virtual audio device using `pactl load-module module-null-sink media.class=Audio/Source/Virtual sink_name=my-virtual-source channel_map=front-left,front-right`
3. go to [mictests.com](https://mictests.com/) on Falkon or Qutebrowser and see that `my-virtual-source` does not show up in the input list.

### Expected behavior
`my-virtual-source` does show up in Falkon or Qutebrowser

### Additional context
One final difference I see is within the Helvum program, where I can see how audio devices are connected. When Firefox, Chromium and Discord use my microphone a connection is made in Helvum, but when Qutebrowser, Falkon, or discord-screenaudio do no connection is visible. To me it seems that qtwebengine-based browsers must not be connecting to pipewire or pipewire-pulse at all, but talking to the audio devices directly somehow.

### Notify maintainers
@matthewbauer (qtwebengine)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/x8mymrkpsmpwyvqssjbwsq851kscf1kw-bash-interactive-5.1-p16-dev
copying path '/nix/store/x8mymrkpsmpwyvqssjbwsq851kscf1kw-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.05 (Quokka), 22.05.20221022.3933d8b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Astavie** [comment]
I'm unsure if I should also mention the maintainers of Falkon and Qutebrowser here since it seems the issue lies with qtwebengine

**Comment by rnhmjoj** [comment]
You should, I think it's safe to say qtwebengine is pretty much maintained for qutebrowser alone.
I don't use pipewire/pulse but I think @nrdxp does.

**Comment by Astavie** [comment]
Alright then:
falkon's maintainer is @peterhoeg 
other qutebrowser maintainers that have not been mentioned yet are @jagajaga @ebzzry @dotlambda

**Comment by nrdxp** [comment]
> You should, I think it's safe to say qtwebengine is pretty much maintained for qutebrowser alone. I don't use pipewire/pulse but I think @nrdxp does.

I do use pipewire, but not virtual audio devices. Have you ensured that you have xdg-desktop-portal-wlr setup correctly?
I have to run this sequence of commands in order to get screensharing to work, for example:
```
systemctl --user stop xdg-'*'.service pipewire'*'.service wireplumber.service
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
systemctl --user start wireplumber
```
Where `XDG_CURRENT_DESKTOP` is set to `wlroots`

**Comment by Astavie** [comment]
Weird. I'm on X11, not wayland. I added both wireplumber and xdg-desktop-portal via the nixos configuration options and it still doesn't make a difference, even when running those commands before running these browsers

**Comment by Astavie** [comment]
Is xdg-desktop-portal required for pipewire audio support in qtwebengine?

**Comment by nrdxp** [comment]
I don't think so since the mic was working even when video capture is not (and the later does requre it).

However there appears to have been a regression recently, I just bumped my `nixos-unstable` pin just yesterday and now my mic is not working at all.

**Comment by IceDBorn** [comment]
@Astavie Can you paste the code for creating the package you have so far?

**Comment by Astavie** [comment]
@IceDBorn https://github.com/Astavie/dotfiles/blob/49180dc4315b5b490a2c97ae43f71b3238da074b/modules/home/discord.nix#L14-L34

**Comment by huantianad** [comment]
This still seems like an issue, see further attempts at packaging discord-screenaudio in ##199379.

**Comment by Astavie** [comment]
The issue has indeed been fixed!
