### ISSUE TITLE
home-manager is severly out of date / unmaintained in nixpkgs

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#197907]
Since home-manager is quite outdated in nixpkgs, it is currently affected by https://github.com/nix-community/home-manager/issues/3342, meaning building a home-manager switch will plainly not work currently if the home-manager modules are taken from nixpkgs (by importing `pkgs.home-manager.src + "/nixos"`).

We should either make an effort to keep home-manager up to date or remove it altogether. The lack of home-manager updates in nixpkgs seems to indicate to me that most people either have a dedicated `home-manager` channel or use flakes to get home-manager. 

I don't use home-manager myself, so it'd be great if an actual home-manager user could step up for this.

**Comment by vcunat** [comment]
https://github.com/NixOS/nixpkgs/pull/197735

**Comment by sternenseemann** [comment]
Resolved for now, but it'd be nice to have someone dedicated to keeping it somewhat up to date in nixpkgs.
