### ISSUE TITLE
gcloud CLI 

### ISSUE THREAD

**Issue by mihok** [NixOS/nixpkgs#197909]
**Project description**
gcloud lets you interact with GCP, includes `gcloud`, `gsutil`, `kubectl`, `bq`

**Metadata**

* homepage URL: https://cloud.google.com/cli
* source URL: https://cloud.google.com/sdk/docs/install
* license: I believe its proprietary
* platforms: unix, linux, darwin, windows

**Comment by sternenseemann** [comment]
`kubectl` is part of the `kubectl` and `kubernetes` packages, additionally.
