### ISSUE TITLE
Android-Tools outdated

### ISSUE THREAD

**Issue by genofire** [NixOS/nixpkgs#197939]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: android-tools

current version: 31.0.x
desired version: 33.0.x

###### Notify maintainers

maintainers: @primeos

###### Note for maintainers

Please tag this issue in your PR.

**Comment by liketechnik** [comment]
See #196144

**Comment by SebTM** [comment]
I've used the PR mentioned today as I was in need of >= 33.X, I offered to make a PR if offer can't

**Comment by genofire** [comment]
Oh sorry, i have overseen this PR in Draft.

**Comment by SebTM** [comment]
See #199212
