### ISSUE TITLE
Neuron (Simulator) Out of Date

### ISSUE THREAD

**Issue by CyborgPotato** [NixOS/nixpkgs#198090]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: neuron

current version: 7.5
desired version: 8.2.1

###### Notify maintainers

maintainers: [Adrien Devresse](https://github.com/adevress) <[adev@adev.name](mailto:adev@adev.name)>

###### Note for maintainers

Please tag this issue in your PR.

**Comment by tomodachi94** [comment]
Appears to have been fixed by #198093.
