### ISSUE TITLE
Can't use HaskellPackages.servant_0_9

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#19819]
## Issue description

Trying to use `haskellPackages.servant_0.9` results in a compilation error:

```
src/Servant/API/ContentTypes.hs:93:1: error:
    Failed to load interface for ‘Web.FormUrlEncoded’
    Use -v to see a list of the files searched for.
```
### Steps to reproduce

→ nix-shell -p '(import <nixpkgs> {}).haskellPackages.ghcWithPackages (p: with p; [servant_0_9])'
## Technical details
- System: 
  → nixos-version 
  16.09.824.e4fb65a (Flounder)

**Comment by PierreR** [comment]
`servant_0_9` requires `http-api-data_0_3_1` which in turn requires `QuickCheck_2_9_2`.

As a note, trying to override to get this right using [the following](https://www.refheap.com/123493) in my ~/.nixpkgs/config.nix file would output this error message:
```
abort because of serious configure-time warning from Cabal
```

**Comment by PierreR** [comment]
Using master at 9088abc, it would also fail with:
```
→ NIX_PATH=nixpkgs=/home/vagrant/projects/nix/nixpkgs nix-shell -p '(import <nixpkgs> {}).haskellPackages.ghcWithPackages (p: with p; [servant_0_9_0_1])'

Setup: Encountered missing dependencies:
http-api-data ==0.3.*

**Comment by teh** [comment]
@PierreR - would you be able to create a PR that does something similar to [1]?

[1]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix#L545

**Comment by PierreR** [comment]
I will have a look over this week-end.
