### ISSUE TITLE
Upgade request: portmod: 2.1.0 -> 2.4.2

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#198109]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: portmod

current version: 2.1.0
desired version: 2.4.2

###### Notify maintainers
@marius851000

maintainers:

###### Note for maintainers

Please tag this issue in your PR.

**Comment by marius851000** [comment]
Oh, yeah... Guess I'm late for an update... It made quite some time I haven't touched morrowind, but I'll take a quick look at it. If it's easy, it should be done in the following days.

**Comment by marius851000** [comment]
Sorry, but I had some personnal stuff that prevented me to work on this. I’ll go work on this right now (and a few other Nix related stuff)

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/commit/00ee658dfbcaac61a80a0b7ba1bb33d5b5caca44
