### ISSUE TITLE
enable ipv6 for cache.nixos.org (cloudfront)

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#19811]
## Issue description

According to this article https://aws.amazon.com/de/about-aws/whats-new/2016/10/ipv6-support-for-cloudfront-waf-and-s3-transfer-acceleration/ Amazon Cloudfront now supports ipv6,
which means it could be enabled for cache.nixos.org.

**Comment by Mic92** [comment]
One might even ask, why Amazon not just enable it by default, 
because it is just a CNAME:

```
cache.nixos.org.        1166    IN      CNAME   d3m36hgdyp4koz.cloudfront.net.
```

**Comment by edolstra** [comment]
I've enabled IPv6 support in CloudFront. The change might take a while to take effect.

**Comment by edolstra** [comment]
Seems to work!

**Comment by vcunat** [comment]
Great!

Heh, the IPv* records have only 60 seconds TTL; that's not too cache-friendly...

**Comment by Mic92** [comment]
Cool!
