### ISSUE TITLE
nix-build fails to build gdal from source on WSL, nixpkgs 22.05

### ISSUE THREAD

**Issue by Sintrastes** [NixOS/nixpkgs#198161]
### Steps To Reproduce

1. Download the [default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gdal/default.nix) for gdal on the 22.05 tag.
2. Build with `nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'`

Expected: The package builds successfully.

Actual: The build fails.

### Build log

https://gist.github.com/Sintrastes/912480e075fb7818345f80e4f4ddeebb

### Additional context

I am attempting to build a variant of gdal from source, as the only gdal packages I could find on nixpkgs do not include the java bindings, which I need.

Thus, I downloaded the `default.nix` for building gdal from [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/gdal/default.nix) on the 22.05 tag (which is the same as the version of nixpkgs I am using), and attempted to modify it to include the java bindings I need.

However, it seems that for some reason I am unable to build this `default.nix` on my machine even without any modifications.

### Notify maintainers

@risicle

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/jkv35nzx1nh8g0d5p94k8i4zjg8j8i37-nix-info
copying path '/nix/store/jkv35nzx1nh8g0d5p94k8i4zjg8j8i37-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.16.3-microsoft-standard-WSL2, Ubuntu, 20.04 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(bedelln): `"nixpkgs-22.05"`
 - nixpkgs: `/home/bedelln/.nix-defexpr/channels/nixpkgs`
```

**Comment by risicle** [comment]
A few things to unpack here:

 - Grabbing the `default.nix` for the package you're interested in and running `callPackage` against it isn't the best approach to start modifying packages. Firstly if you look at where this package is referenced, `pkgs/top-level/all-packages.nix` approx line 17440 (file too big to link directly :cry:), you'll see it's being called with non-default values for the `pythonPackages` and `autoreconfHook` arguments. In this particular case it looks like it will be the `pythonPackages` not being `python3Packages` causing it to be called with python 2. (huh, you'd think we'd be should just change that to `python3Packages` by default now, I doubt our `gdal` packages have built with python 2 for ages).
   - If you're just looking to make a quick custom modification for yourself, I'd look at modifying the `gdal` package with the `.override` and/or `.overrideAttrs` functions, perhaps done in an overlay (https://nixos.org/manual/nixpkgs/stable/#chap-overlays).
   - If you're interested in developing an enhancement to contribute back to nixpkgs I would just clone the nixpkgs repo, hack away at the relevant files and build using e.g. `nix-build . -A gdal` from the repo root. This is how I work 99% of the time.
 - Let's look at adding the java bindings if we can find a neat way of exposing them without pulling in java for every gdal user.
 - WSL blimey best of luck.

**Comment by Sintrastes** [comment]
Thanks @risicle. I figured it must have been some sort of difference between context -- but I wasn't able to figure out where this was actually being called in nixpkgs.

I'd definitely like to contribute if possible -- but I'll look into an overlay as well.

After messing around with the `pythonPackages`, and disabling some of the tests, I was able to get my standalone version to compile -- and then, after adding some dependencies (e.x. jdk, ant) and some configure flags, I was able to get this mostly working with:

```nix
buildPhase = ''                                                                                                                                        
    make

    cd swig/java/
    make
    cd ../../
'';

installPhase = ''
    make install

    cd swig/java
    make install
    cd ../../
'';
```

The only issue I'm running into now is the following error:

```
RPATH of binary /nix/store/5gqniz0dic4cxm02bms1xabgc41cfq3k-gdal-java-3.4.2/lib/libgdalalljni.so contains a forbidden reference to /build/
```

I'll try again either using an overlay, or your suggested approach to contributing to nixpkgs, but I'm guessing I may need to use `patchelf` or something here to stop nix from complaining about this.

> Let's look at adding the java bindings if we can find a neat way of exposing them without pulling in java for every gdal user.

I'm not super familiar with how SWIG works, but do you think it would be possible to add a new derivation to `nixpkgs` called `gdal-java` which depends on `gdal`, and builds the java bindings? I messed around with this a little bit, but I'm not sure how feasible this would be, or if there's another approach we could use with nix.

**Comment by risicle** [comment]
Cool - looking into this made me realize we have to do a bump to gdal 3.5 and use cmake for building before we end up in a sticky situation with an unexpected security fix (#179406), so I'll probably see if I can jam the java bindings in after that's all merged.

**Comment by Sintrastes** [comment]
@risicle If it'd be helpful, I can make a WIP PR for this with my changes.

Also, I noticed there's a `netcdfSupport` parameter in the gdal derivation. Were you thinking about something along similar lines for adding optional support for building the java bindings -- e.x. adding a `javaSupport ? false` parameter?

**Comment by risicle** [comment]
I'd hold back on any PRs because the gdal PR we're getting ready to merge #179406 make a lot of changes, and I have a feeling afterwards we may be able to enable the java bindings with the simple addition of a cmake flag or two.

We can certainly add a `javaSupport`-style flag, the only issue with these is if there isn't a package that hydra builds that enables this flag it's liable to get broken as our tests won't exercise it. We could in theory add a `gdalWithJava` just for this purpose but we obviously can't do that for every possible option a package has.
