### ISSUE TITLE
neovim-remote: regression due to change in nixpkgs Python packaging

### ISSUE THREAD

**Issue by jupblb** [NixOS/nixpkgs#198281]
### Steps To Reproduce
Just build [neovim-remote](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/neovim/neovim-remote.nix).

### Build log
https://pastebin.com/xaR4rL2X

### Notify maintainers
@FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.14`
 - channels(jupblb): `"darwin, nixpkgs-22.11pre421626.f44ba1be526"`
 - nixpkgs: `/Users/jupblb/.nix-defexpr/channels/nixpkgs`
```

**Comment by FRidh** [comment]
Thanks for reporting.

PR adding stdenv to an exceptions list https://github.com/NixOS/nixpkgs/pull/198284.

**Comment by FRidh** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/198284
