### ISSUE TITLE
pdfjam needs pdflatex

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#19826]
## Issue description

after installing pdfjam i tried to use pdfjoin,
the command failed complaining about a missing pdflatex

local installation of texlife fixed the issue

however pdfjoin seems to be to old to uspport more recent pdf files, so i wont follow up
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by Mic92** [comment]
How did this ever worked? I thought pdfjam, needs latex for everything.

**Comment by NeQuissimus** [comment]
When you say "too old", would you suggest we remove the package altogether? I have no experience with this particular package.

**Comment by Mic92** [comment]
Is it the same pdfjam, which is included in texlive?
