### ISSUE TITLE
nixos/hedgedoc: StateDirectory= path is absolute, ignoring

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#198250]
### Describe the bug
`services.hedgedoc` sets `StateDirectory=` to absolute paths, which systemd warns about and ignores:

```
systemd[1]: /etc/systemd/system/hedgedoc.service:19: StateDirectory= path is absolute, ignoring: /var/lib/hedgedoc
systemd[1]: /etc/systemd/system/hedgedoc.service:20: StateDirectory= path is absolute, ignoring: /var/lib/hedgedoc/uploads
```

### Steps To Reproduce
1. Enable hedgedoc service.
2. Check log.
3. See warning.

### Expected behavior
No warnings/ignored service settings.

### Additional context
I guess the problem starts with `services.hedgedoc.workDir` being a user configurable option (absolute path), because AFAICT, that's incompatible with StateDirectory=, which takes a relative path below `/var/lib`.

It appears this issue was fixed in becff585796094f75d0ccbe1df5418ef873897ac, but for some reason it was reverted again in 57617daaff5ed1f519b1ae4e54d48364a2649972 (commit message doesn't say why).

### Notify maintainers
TODO.

### Metadata
nixos-22.05 and nixpkgs-unstable are affected.

**Comment by bjornfor** [comment]
> It appears this issue was fixed in https://github.com/NixOS/nixpkgs/commit/becff585796094f75d0ccbe1df5418ef873897ac, but for some reason it was reverted again in https://github.com/NixOS/nixpkgs/commit/57617daaff5ed1f519b1ae4e54d48364a2649972 (commit message doesn't say why).

Why it was reverted: https://github.com/NixOS/nixpkgs/pull/177536#issuecomment-1166478808

**Comment by Stunkymonkey** [comment]
I am not sure if the `StateDirectory` should be an array...
my current workaround:
`systemd.services.hedgedoc.serviceConfig.StateDirectory = lib.mkForce "/var/lib/hedgedoc";`

**Comment by bjornfor** [comment]
> I am not sure if the `StateDirectory` should be an array...

Generally, systemd supports it: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=

```
These options take a whitespace-separated list of directory names. [...]
```

**Comment by rhendric** [comment]
Still an issue on 23.05.

**Comment by Stunkymonkey** [comment]
there might be a fix in https://github.com/NixOS/nixpkgs/commit/6cd8da76f9fa62343e22a0cbeda3ade5345901ec to set the `StateDirectory`. Has anybody tested this?

**Comment by bjornfor** [comment]
@Stunkymonkey: I looked at the diff and it seems fixed to me. Closing. :tada: 

(Ping me to re-open if I was wrong.)
