### ISSUE TITLE
boot.plymouth.theme available options missing

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#198380]
### Describe the bug

Here you see all official themes: https://gitlab.freedesktop.org/plymouth/plymouth/-/tree/main/themes

### Steps To Reproduce
1. ...
2. ...
3. ...

### Screenshots
![Screenshot from 2022-10-29 04-39-14](https://user-images.githubusercontent.com/91113/198782622-6fe1cf2f-ff48-4c81-8a99-2ed03b290d45.png)

**Comment by Ashvith10** [comment]
@davidak  there's not a lot of context to this issue. Would you mind elaborating?

**Comment by eclairevoyant** [comment]
It seems like they want to see all available themes listed in the desc. Though of course you can install custom themes, so we don't want to restrict the list to just the defaults.

**Comment by SuperSandro2000** [comment]
Closing because of missing information and it is unclear what should actually be done here.
