### ISSUE TITLE
X server randomly terminates

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#19840]
## Issue description

My X server is randomly terminating "successfully" after 5-10 minutes of begin logged in. [Here's a gist of the log](https://gist.github.com/siddharthist/4c0df84d047dad8178954e62e339e580)

I'm using SLiM and i3-gaps, but can reproduce with gdm, lightdm, kdm, and i3. 
### Steps to reproduce

Here's my xserver configuration:

```
  services.xserver = {
    enable = true;
    layout = "us";

    synaptics = {
      enable = true;
      # OSX-like "Natural" two-finger scrolling
      twoFingerScroll = true;
      horizTwoFingerScroll = true;
      horizEdgeScroll = false;
      additionalOptions = ''
        Option "VertScrollDelta"  "-75"
        Option "HorizScrollDelta" "-75"
      '';
    };

    #multitouch.enable = true;
    displayManager.slim.enable = true;
    #displayManager.slim.defaultUser = "siddharthist";
    windowManager.i3-gaps.enable = true;
    windowManager.i3-gaps.configFile = "/home/siddharthist/.config/i3/config";
    monitorSection = ''
      DisplaySize   294 166
    '';
  };
```
## Technical details
- System: 17.03.git.e376ed8 (Gorilla)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by NeQuissimus** [comment]
What does your `/home/siddharthist/.Xresources` look like?

**Comment by siddharthist** [comment]
It's generated using Ansible from this template: https://raw.githubusercontent.com/siddharthist/dots/master/templates/Xresources.j2

Looks like this right now: https://gist.github.com/siddharthist/a0dd5e9198ba1b31ab83f0a40a4eb8b4

**Comment by NeQuissimus** [comment]
Holy giant everything :D I should probably not have just blindly copy/pasted it xD

**Comment by NeQuissimus** [comment]
So, it says something about a bluetooth device before it goes down, are you listening to something in `audacious` by chance? I found this: http://antix.freeforums.org/viewtopic.php?f=53&t=6353&start=0&view=print

**Comment by siddharthist** [comment]
@NeQuissimus No, I'm not. I will try disabling Bluetooth. Thanks for looking, though!

I've also fixed the Xresources errors, to no avail. I'll post a log of the next crash after I do that.

**Comment by siddharthist** [comment]
I've reinstalled NixOS, and this no longer happens to me.
