### ISSUE TITLE
Audacity on `unstable` is the alpha version

### ISSUE THREAD

**Issue by MikiVanousek** [NixOS/nixpkgs#198439]
### Describe the bug
Audacity on `unstable` is the `3.2.1-alpha` version. Every time I open it, I am warned people should not use this version.
I experienced miscellaneous bugs, freezes and crashes over the past months. I improved the situation by installing the version from `nixos-22.05` instead. It is also an alpha version, but while still sometimes freezes, overall behaves much better.

### Expected behavior
Even though the channel is called unstable, I believe this just means 'newest functioning version'. I think the version of audacity should be the one they recommend installing, namely [3.2.1]( as of writing).
### Notify maintainers

@lheckemann @veprbl 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11pre421411.2001e2b31c5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(miki): `"nixgl"`
 - channels(root): `"android-nixpkgs, nixos, stable-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by veprbl** [comment]
The tag should have been 3.2.1, see #194937 cc @wegank

**Comment by wegank** [comment]
Wait, I don't think I set the flag wrong in #194937. What should it be other than `Audacity-3.2.1`?
