### ISSUE TITLE
VeraCrypt is missing dependency `sudo`

### ISSUE THREAD

**Issue by 6e6f61** [NixOS/nixpkgs#198569]
### Describe the bug
VeraCrypt uses `sudo` when mounting devices, but its NixOS package does not depend on it.

### Steps To Reproduce
1. `security.sudo.enable = false;`
2. `environment.systemPackages = [ pkgs.veracrypt ];`
3. Attempt to mount a volume using VeraCrypt

### Expected behavior
VeraCrypt finds `sudo`, or VeraCrypt is patched to use whatever subexecutor the system uses (e.g. `doas`).

### Screenshots
![image](https://user-images.githubusercontent.com/109554668/198856575-1d1b4313-ca3a-4c65-b2a1-75605d489cd6.png)

### Notify maintainers
@dsferruzza 

### Metadata
```
[i@fw:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.3, NixOS, 22.05 (Quokka), 22.05.3826.e6e675cafe6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(i): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by NickCao** [comment]
Adding sudo to the dependencies of VeryCrypt won't work as intended, as sudo has to be a suid program.

**Comment by 6e6f61** [comment]
Got it, I'll bring this up with the VeraCrypt maintainers instead. Thanks anyway.
