### ISSUE TITLE
libopusfile not found on lutris

### ISSUE THREAD

**Issue by Zaechus** [NixOS/nixpkgs#198581]
### Describe the bug
Lutris on NixOS can't launch DOSBox games by itself.

### Screenshots
![image](https://user-images.githubusercontent.com/19353212/198858618-f0a765b3-e49f-4a3f-b310-095698f131ae.png)

### Additional context
Likely just needs the opusfile input

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75, NixOS, 22.11 (Raccoon), 22.11.20221025.f994293`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.05"`
 - channels(zaechus): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by l0b0** [comment]
Can confirm. Installing `pkgs.opusfile` did not help.

**Comment by Zaechus** [comment]
For now, the following workaround works:
```
(lutris.override {
  extraPkgs = pkgs: [ opusfile SDL2_net ]; # fix dosbox
})
```

**Comment by l0b0** [comment]
Thank you!

**Comment by mexisme** [comment]
It looks like Meson is working now, with an update to https://github.com/dosbox-staging/dosbox-staging?
- https://github.com/dosbox-staging/dosbox-staging/issues/2319#issuecomment-1462927993

**Comment by Zaechus** [comment]
I tested the dosbox runner in lutris and confirmed that it worked without the override workaround. Closing this.
