### ISSUE TITLE
libfprint: 1.94.4 -> 1.94.5

### ISSUE THREAD

**Issue by yswtrue** [NixOS/nixpkgs#198530]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: libfprint

current version: 1.94.4
desired version: 1.94.5

###### Notify maintainers

maintainers:
abbradar

###### Note for maintainers

Please tag this issue in your PR.

**Comment by FliegendeWurst** [comment]
I can't find the release announcement for 1.94.5. Do you have a link?

**Comment by yswtrue** [comment]
@FliegendeWurst

**Comment by yswtrue** [comment]
sorry is libfrpint not fprintd
