### ISSUE TITLE
librewolf-unwrapped-106.0.1-1 fails to build on aarch64; Raspberry Pi 4

### ISSUE THREAD

**Issue by llirium** [NixOS/nixpkgs#198531]
### Steps To Reproduce
1. build librewolf-unwrapped-106.0.1-1

### Build log
https://gist.github.com/llirium/0b90cbdd067e77a048db94d80fa9c24d

### Notify maintainers
@squalus 

### Metadata
[llirium@hostname:~]$ nix-shell -p nix-info --run "nix-info -m"
these 5 paths will be fetched (0.35 MiB download, 1.80 MiB unpacked):
  /nix/store/43v65lf5pwgh7mv2jgki6jgz563gi31x-hook
  /nix/store/9k9cklb49ka9mrp0kcpq8sfpam5hh5cl-gnu-config-2021-01-25
  /nix/store/a0kn4p6wq7vhjqf6x78jlfz7srfj20g4-stdenv-linux
  /nix/store/d1crb0sl1dv2xpcy5n033j1q729v6qmf-bash-interactive-5.1-p16-dev
  /nix/store/kf3nn5rnynbllgbwz8f5blx63yb59j1c-gnumake-4.3
copying path '/nix/store/d1crb0sl1dv2xpcy5n033j1q729v6qmf-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/9k9cklb49ka9mrp0kcpq8sfpam5hh5cl-gnu-config-2021-01-25' from 'https://cache.nixos.org'...
copying path '/nix/store/kf3nn5rnynbllgbwz8f5blx63yb59j1c-gnumake-4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/43v65lf5pwgh7mv2jgki6jgz563gi31x-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/a0kn4p6wq7vhjqf6x78jlfz7srfj20g4-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.32, NixOS, 22.05 (Quokka), 22.05.3848.c132d0837df`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by squalus** [comment]
Does #197849 fix this for you?

**Comment by llirium** [comment]
Still relatively new to NixOS and don't know where to start with backporting.  Will attempt the build, but need some instructions on how to do it properly, please.

**Comment by squalus** [comment]
It was already backported to 22.05 in #198013.

Here's a tool to show you whether the PR has hit the various channels: https://nixpk.gs/pr-tracker.html?pr=198013

**Comment by llirium** [comment]
May have just missed it, was building on Oct. 26th.  Will attempt a rebuild and let you know how it goes.

**Comment by llirium** [comment]
Yes, the rebuild went just fine with no errors, thanks for letting me know about it.
