### ISSUE TITLE
jekyll-favicon

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#198542]
**Project description**
>  Favicon generator and tag for Jekyll.

**Metadata**

* [homepage](https://afaundez.github.io/jekyll-favicon)
* [source](https://github.com/afaundez/jekyll-favicon)
* license: MIT
* platforms: Any

**Comment by Stunkymonkey** [comment]
@l0b0 I guess the issue can be closed due to #198600. Reopen if I am incorrect

**Comment by l0b0** [comment]
Oh, weird. The "Closes #198542" in #198600 wasn't applied automatically. Thank you!
