### ISSUE TITLE
nextcloud-client segfaults at startup

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#198535]
### Describe the bug
Since 2868077cdc900cc66ea642e3f088edefe765579b (on nixos-22.05), nextcloud-client segfaults at startup. (I bisected it.)

### Steps To Reproduce
1. `git checkout 2868077cdc900cc66ea642e3f088edefe765579b`
2. `nix-build -A nextcloud-client && ./result/bin/nextcloud`
3. Watch it fail to start with a segfault.

### Expected behavior
Application starts, no segfault.

### Metadata
NixOS 22.05

**Comment by bjornfor** [comment]
Ugh, it must have been something related to the runtime environment of my system, as I'm unable to reproduce it anymore :shrug:

**Comment by amesgen** [comment]
My nextcloud-client also segfaults/core dumps on startup, and it continues doing so across multiple reboots on multiple machines. @bjornfor Did you change anything about your setup since you got these errors?

FTR: This is my startup log: https://gist.github.com/amesgen/a18d2454a91ad0122c724bd696577b75

**Comment by bjornfor** [comment]
> @bjornfor Did you change anything about your setup since you got these errors?

No. That's the weird part. This is how I remember the sequence of events:

* On nixos 22.05 I see nextcloud segfault / fail to start.
* I checkout an old nixpkgs and see nextcloud working fine. (I'm not rebuilding my whole system, just building nextcloud-client and launching it.)
* I'm confident enough in the behaviour (tried multiple good/bad revisions) that I set off an automated bisect. (Still no reboots in between.)
* Bisect completes.
* I run `nextcloud` from `nixpkgs-unstable` to see if it's affected too, but it works there.
* I re-check `nextcloud` on nixos-22.05 and now it works there too!

I actually didn't reboot until *after* everything started working again -- and it continues to work now after rebooting. (Did running `nextcloud` from `nixpkgs-unstable` fix it?!)

**Comment by amesgen** [comment]
No, the `nextcloud-client` from latest nixpkgs-unstable does not work for me. Right now, I have a suspicion that something with qt is wrong on my system, as my qt theme also stopped working... I will try to investigate and report back when I know more.

**Comment by bjornfor** [comment]
I experienced the same segfault on another machine with similar NixOS 22.05 setup. Here's my terminal session:

```
$ nextcloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Segmentation fault (core dumped)

$ nix --extra-experimental-features "nix-command flakes" build nixpkgs#nextcloud-client

$ ./result/bin/nextcloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QApplication: invalid style override 'adwaita' passed, ignoring it.
        Available styles: Windows, Fusion
^C
[...it started fine, I stopped it manually...]

$ nextcloud
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
^C
[...it started fine, I stopped it manually...]

$ nixos-version
22.05.git.c132d08 (Quokka)
```

So to me it seems running once with nextcloud-client from nixpkgs-unstable really does help. Weird.

This machine was rebooted into its nixos-version just before testing, and I didn't reboot during testing.

**Comment by amesgen** [comment]
Ok, after temporarily switching back to an older generation (but changing nothing about my current system), nextcloud-client works fine again 🤷

**Comment by amesgen** [comment]
> Deleting `~/.cache/Nextcloud/` fixed it for me.

Thanks, that directly fixes it for me on a different machine! From my POV, this issue can be closed then.

**Comment by bjornfor** [comment]
Did anyone get a copy of a broken `~/.cache/Nextcloud`? It would be interesting to compare broken vs working directory. (And ping upstream.)

**Comment by bjornfor** [comment]
Related:
* https://github.com/NixOS/nixpkgs/issues/114468
* 788119f78101a10b2c58de0690c23572ac348076

Also, I seem to remember seeing something about a Qt/QML cache fix in nixpkgs recently, like a more general fix than the above, but I can't seem to find it. (`~/.cache/Nextcloud` contains only QML cache files on one of my systems.)

**Comment by bjornfor** [comment]
> Also, I seem to remember seeing something about a Qt/QML cache fix in nixpkgs recently, like a more general fix than the above, but I can't seem to find it

Here: https://github.com/NixOS/nixpkgs/pull/197010. (Landed to staging just now.)

**Comment by SuperSandro2000** [comment]
Didn't encounter this issue because I am already running the linked PR.
