### ISSUE TITLE
AdGuardHome no longer builds in non-declarative configuration

### ISSUE THREAD

**Issue by mateon1** [NixOS/nixpkgs#198665]
### Steps To Reproduce
1. set `services.adguardhome.enabled = true;` in configuration.nix
2. rebuild
3. see assertion failures

### Build log
```
building Nix...
building the system configuration...
error:
       Failed assertions:
       - AdGuard setting dns.bind_host or dns.bind_hosts needs to be configured for a minimal working configuration
       - AdGuard setting dns.bootstrap_dns needs to be configured for a minimal working configuration
(use '--show-trace' to show detailed location information)
```

### Additional context
Related to #173938, introduced by #176701

Prior to this PR, setting just the enabled flag with no other settings builds and works correctly.
After this PR, the settings map is no longer empty by default. If you check in a nix-repl, you get:
```nix
nix-repl> config.services.adguardhome.settings
{ bind_host = "0.0.0.0"; bind_port = 3000; schema_version = 14; }
```

If non-declarative configurations are not supported anymore, this needs to be made clear, and the assertions need to be fixed so they don't check for the settings not being empty.

### Notify maintainers
Maintainers:
@numkem
@iagocq

PR author: @CRTified 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[mateon@hydra:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.11 (Raccoon), 22.11.git.8ee9c8d3ed0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixpkgs"`
 - channels(mateon): `"nixos, nixpkgs"`
 - nixpkgs: `/home/mateon/.nix-defexpr/channels/nixpkgs`
```

**Comment by CRTified** [comment]
I see the problem. 

I'll take a look on how this can be resolved. One problem that I see is the conflict between `settings` needing some default values *if* it's used to configure AdGuardHome, and an implicit way of detecting non-declarative configurations.

**Comment by surfaceflinger** [comment]
offtopic, but it would be nice if we could put interface names, not just ips as bind_host. Would help reproducibility for example with tailscale.

**Comment by CRTified** [comment]
@surfaceflinger This is probably better noted as a feature request on AdGuardHome directly. A quick search revealed https://github.com/AdguardTeam/AdGuardHome/issues/3635 as a similar request :)
