### ISSUE TITLE
mypyc command (in mypy package) setuptools error

### ISSUE THREAD

**Issue by aarmn** [NixOS/nixpkgs#198614]
### Describe the bug
mypyc doesn't work

### Steps To Reproduce
1. add mypy in system pkgs (NixOS unstable) and rebuild
2. run mypyc

### Expected behavior
not to, throwing an error

### Screenshots
![Screenshot_20221030_112559](https://user-images.githubusercontent.com/29726901/198868316-5efb47df-457c-44e5-b9a4-b56c691964c0.png)

### Notify maintainers
@martingms @lnl7 @SuperSandro2000

**Comment by SuperSandro2000** [comment]
mypyc creates a build directory with a setup.py file that contains the following

```
from setuptools import setup
from mypyc.build import mypycify

setup(name='mypyc_output',
      ext_modules=mypycify([], opt_level="3", debug_level="1"),
)
```

For that to work we would need to leak setuptools into the user environment. Also I think mypyc is a build tool that you shouldn't normally execute like you did which means this is not a bug. You likely want to execute mypy or dmpypy.

**Comment by aarmn** [comment]
Indeed you are right, I assumed it would at very least have a `--help`, it seems like not
