### ISSUE TITLE
hplip: "ImportError: No module named scanext"

### ISSUE THREAD

**Issue by canndrew** [NixOS/nixpkgs#19878]
## Issue description

A very similar issue to https://github.com/NixOS/nixpkgs/issues/279

I'm trying use an hp scanner on NixOS. If I try to use a scanner tool like simple-scan or xsane they complain about missing drivers. I've installed the hplip package and followed the instructions on the wiki [here](https://nixos.org/wiki/Scanners).

hplip comes with a tool called `hp-scan`. If I run it it complains 'hplip: "ImportError: No module named scanext"'. This can be worked around by modifying the `PYTHONPATH` env variable to point into the hplip python directory in /nix/store. However if I do that it then complains "error: No device selected/specified or that supports this functionality". If I specify the device on the command line it says "error: 'DeskJet_3630' device doesn't support this feature (or) Invalid printer name".

Any idea what to do about this? The package clearly isn't setup properly if I need to fiddle with paths to make things run, but I don't know if that's causing the larger issue of it not finding the scanner.
- System: 17.03.git.09e4b78 (Gorilla)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 17.03.git.09e4b78

**Comment by ericsagnes** [comment]
Should be related to #19469.

**Comment by FRidh** [comment]
the issue should be solved if you're on the nixpkgs-unstable channel. Could you check it?

**Comment by canndrew** [comment]
I don't get the python import error anymore but it still doesn't detect the scanner. I tried it on my gentoo box and it worked fine.

Closing because I have no idea whether this is a nixpkgs issue and because the import error is fixed.

**Comment by FRidh** [comment]
I'm afraid I can't help you with that.

**Comment by canndrew** [comment]
I figured as much. Thanks for fixing this though.
