### ISSUE TITLE
${pkg_install_dir}/share/pkgconfig does not in PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by yuchangyuan** [NixOS/nixpkgs#19886]
## Issue description

Some package like "eigen" can not find by pkg-config, because "*.pc" is not install inside `${pkg_install_dir}/lib/pkgconfig`, but `${pkg_install_dir}/share/pkgconfig`
### Steps to reproduce

Add eigen to environment.systemPackages, then try command `pkg-config --cflags eigen3`. The command fail to give a result.
## Technical details

Add below lines to NixOS config will fix the problem:

```
  environment.pathsToLink = [
    "/share/pkgconfig"
  ];

  environment.profileRelativeEnvVars = {
    PKG_CONFIG_PATH = [ "/share/pkgconfig" ];
  };
```
- System: 16.09.773.b8ede35 (Flounder)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 16.09.773.b8ede35

**Comment by pschuprikov** [comment]
`PKG_CONFIG_PATH` is set by `pkgconfig`'s setup hook. When you simply add package to `systemPackages` this hook does not run, and this is intentional, AFAIU.

 If you want `eigen` to be seen by `pkg-config`, you can run: 
```bash
$ nix-shell -p pkgconfig -p eigen
$ pkg-config --cflags eigen3
```

**Comment by vcunat** [comment]
Yes, `systemPackages` and stuff installed by `nix-env` isn't meant for development dependencies. `pathsToLink` is relatively small on purpose.

`nix-shell` is the simplest way for development environments with nix(os).
