### ISSUE TITLE
xen: xen-bridge serves invalid netmask

### ISSUE THREAD

**Issue by michalpalka** [NixOS/nixpkgs#19883]
## Issue description

The xen-bridge.service serves an invalid netmask over DHCP to VMs.
### Steps to reproduce

Start with a NixOS host with Xen dom0 enabled using the following option in `/etc/nixos/configuration.nix`.

```
virtualisation.xen.enable = true;
```

By default, the VMs’ network controllers will be connected to a bridge `xenbr0` set up by the xen-bridge.service. The network on `xenbr0` is set to `172.16.0.0/16`, but the VMs set up their networks as `172.16.0.0/12`.
### Analysis

The VMs get their networks configured using DHCP, through dnsmasq running on dom0. Looking at the DHCP exchange using `tcpdump` reveals that the netmask sent to the clients (VMs) is `172.16.0.0` instead of `255.255.0.0`, as DHCP option 1 (shown below).

```
Subnet-Mask Option 1, length 4: 172.16.0.0
```

The DHCP client on the VM side is likely ignoring the invalid netmask, and guessing a `/12` netmask instead.

The problem can be fixed by removing the wrong netmask from the dnsmasq configuration file. Then, dnsmasq will infer the correct netmask by looking at how xenbr0 is configured.

Will submit a PR.
## Technical details
- System: `17.03.git.28aa92d (Gorilla)`
- Nix version: `nix-env (Nix) 1.11.4`
- Nixpkgs version: `"17.03.git.28aa92d"`

**Comment by michalpalka** [comment]
The issue no longer appears

**Comment by praduca** [comment]
Dont know if related to this (not sure if it is a bug really) but if you set the mask for the aforementioned bridge, it set it incorrectly. I tried to set it as 24, get 255.0.0.0 as a result... Both 16.04 and this new 17.03 have this behaviour.
I understand that this is not the best place to ask, but if what i am doing is producing the expected behaviour, I will apreciate any guidance on using it correctly.

**Comment by michalpalka** [comment]
@praduca Could you explain your issue in more detail, for example how to reproduce it? I am not sure how you are setting the net mask.

**Comment by praduca** [comment]
Hi, i am just using the configurations on virtualisation.xen section of configuration options. so:
Setting virtualisation.xen.bridge.address to some valid ip adress _works_
but
Setting virtualisation.xen.bridge.prefixLength to anything other than the default gives a 8 bit mask.

**Comment by michalpalka** [comment]
Can't see what could be wrong. Anyway, this looks like a separate issue that should be reported. There might be something wrong with the scripts under `systemd.services.xen-bridge` in [`xen-dom0.nix`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/xen-dom0.nix).

**Comment by praduca** [comment]
Opened at #24588.
