### ISSUE TITLE
Nextcloud Client 3.6.1 doesn't start

### ISSUE THREAD

**Issue by Nebucatnetzer** [NixOS/nixpkgs#198944]
### Describe the bug
The Nextcloud client doesn't start anymore after the update to 3.6.1
When run from the console it shows:
`Segmentation fault (core dumped)`

### Steps To Reproduce
1. `nix-shell -p nextcloud-client --run nextcloud`

### Expected behavior
The Nextcloud client starts and shows it's main screen.

### Additional context
Attached the log from the home-manager service file.
[nextcloud.txt](https://github.com/NixOS/nixpkgs/files/9910095/nextcloud.txt)

My last working flake version is from the 18. October.

### Notify maintainers
@Kranzes @SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75, NixOS, 22.05 (Quokka), 22.05.20221018.47edaa3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `""`
 - nixpkgs: `/nix/store/c2ashkynf2ihx7mkjwbsjcbd03wl1nd7-source`
```

**Comment by bjornfor** [comment]
See duplicate issue with workaround/solution here https://github.com/NixOS/nixpkgs/issues/198535#issuecomment-1297253963.

**Comment by Nebucatnetzer** [comment]
Ah shit my bad and I even searched and debuged for two hours :see_no_evil:
