### ISSUE TITLE
Gnome 3.22 breakage / feedback

### ISSUE THREAD

**Issue by groxxda** [NixOS/nixpkgs#19896]
- [ ] https://github.com/NixOS/nixpkgs/commit/c2922a9157a8d8db62cee763e254113c3766461e

**Comment by DamienCassou** [comment]
First try, first error: #19985

**Comment by vcunat** [comment]
That's most likely due to the revert we discussed at https://github.com/NixOS/nixpkgs/issues/19930. The situation is still unresolved AFAIK.

**Comment by bjornfor** [comment]
I'm still unable to boot into GNOME 3.22 desktop. On latest master branch (840f2987d181fb8e501ac7138b9d9e8fac605820) I get

```
17:56:03 [...]-gdm-3.22.0/libexec/gdm-x-session[3372]: Fatal server error:
17:56:03 [...]-gdm-3.22.0/libexec/gdm-x-session[3372]: (EE) xf86OpenConsole: Cannot open virtual console 7 (Permission denied)
[...]
17:56:03 [...]-gdm-3.22.0/libexec/gdm-x-session[3372]: (WW) xf86CloseConsole: KDSETMODE failed: Bad file descriptor
17:56:03 [...]-gdm-3.22.0/libexec/gdm-x-session[3372]: (WW) xf86CloseConsole: VT_GETMODE failed: Bad file descriptor
```

While this is happening, I'm stuck on a console with login prompt, but unable to login. It seems the prompt randomly misses some keystrokes, so I guess I'm not able to type my password correctly. The display (console) flickers, so I guess there is something bad going on.

**Comment by jgeerds** [comment]
This is not fixed yet, right? :disappointed:

**Comment by jgeerds** [comment]
@groxxda are you planning to fix this issue? or should we revert your changes? It's really sad because nixos-unstable with gnome is broken for all of us and I don't have the time to dig into it

**Comment by dezgeg** [comment]
The error message sounds like GDM wants `services.xserver.tty = null;`

**Comment by groxxda** [comment]
The `-terminate` [option](https://github.com/nixos/nixpkgs/blob/81adb91c40d553b0b55a9f4889ce3fa472bb3a86/nixos/modules/services/x11/xserver.nix#L551) must also be removed. I have no idea how to fix it.

**Comment by vcunat** [comment]
Well, gdm even applies the X arguments by itself, and it's not so difficult to filter them.

**Comment by bjornfor** [comment]
@vcunat: Thanks!

**Comment by jgeerds** [comment]
@vcunat thank you so much! :heart:
