### ISSUE TITLE
We have a ton of db versions

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#19897]
This is the current situation in all-packages.nix: 

``` nix
{
  db = db5;
  db4 = db48;
  db44 = callPackage ../development/libraries/db/db-4.4.nix { };
  db45 = callPackage ../development/libraries/db/db-4.5.nix { };
  db47 = callPackage ../development/libraries/db/db-4.7.nix { };
  db48 = callPackage ../development/libraries/db/db-4.8.nix { };
  db5 = db53;
  db53 = callPackage ../development/libraries/db/db-5.3.nix { };
  db6 = db60;
  db60 = callPackage ../development/libraries/db/db-6.0.nix { };
}
```

Do we really need all those versions of 4.x? The curmudgeon in me wants to get rid of all `db4` versions and only leave 5 and 6. But if we can't get rid of all 4.x, can we at least kill all but 4.8?

**Comment by copumpkin** [comment]
cc @LnL7

**Comment by copumpkin** [comment]
I see no references to `db44` in nixpkgs. `db45` is used:

```
pkgs/misc/my-env/default.nix:        buildInputs = [ libtool stdenv perl curl bzip2 openssl db45 autoconf automake zlib ];
```

and `db47` is referenced in all-packages.nix:

```
  python26 = callPackage ../development/interpreters/python/cpython/2.6 {
    db = db47;
    self = python26;
  };

  aprutil = callPackage ../development/libraries/apr-util {
    bdbSupport = true;
    db = if stdenv.isFreeBSD then db47 else db;
    # XXX: only the db_185 interface was available through
    #      apr with db58 on freebsd (nov 2015), for unknown reasons
  };
```

**Comment by LnL7** [comment]
The [patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/db/clang-5.3.patch) for `llvm-3.8` needs to be applied to each version.
It looks like I almost have to create a new one for each version, and I'm not sure if it's a good idea to solve this with substitution.

**Comment by copumpkin** [comment]
Yeah, mostly trying to avoid doing that by deleting other versions 😃
