### ISSUE TITLE
Mastodon default settings not sensibly usable, mastodon not a login user

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#199029]
### Describe the bug

When one installs mastodon via the following minimal config:

```
{
  services.mastodon = {
    enable = true;
    localDomain = "mastodon.mydomain.org";
    configureNginx = true;
    smtp = {
      fromAddress = "admin@mydomain.org";
    };
  };
}
```
Then there is no obvious way to run tootctl. `root` or any other login user doesn't have the `mastodon-env` executable by default, nor can this be enabled in an obvious way. `mastodon` is not a login user, so can't (and shouldn't?) log in as `mastodon` and execute `mastodon-env tootctl`.

### Steps To Reproduce
1. Install mastodon as per minimal config above
2. `mastodon-env tootctl foo`... nope.
3. `sudo -u mastodon mastodon-env tootctl foo`... nope.
4. `su - mastodon`... nope.
5. `login mastodon`... nope.

### Expected behavior

Any of:

* a setting `users.users.<myuser>.mastodonEnv` such that `mastodon-env` is installed for that user
* an explanation in the docs what to do
* `mastodon` as a login user (probably bad idea?)

Workaround: `su -s /bin/sh - mastodon`

CC @happy-river @erictapen

**Comment by turion** [comment]
In the mastodon docs, it is described the following way:

> first we must create the user Mastodon will be running as:

> `adduser --disabled-login mastodon`

> We can then switch to the user:

> `su - mastodon`

https://docs.joinmastodon.org/admin/install/

But `su - mastodon` is not possible, it gives the error `This account is currently not available.` They do recommend `--disabled-login` (which is what I meant by it shouldn't be a login user), but still they seem to do something different than nixos does.

> My way for doing that is just running sudo -su mastodon and continuing in that shell.

Maybe that's fine, and it would be helpful to document this somewhere, so people don't spend a long time trying to find it out.

**Comment by SuperSandro2000** [comment]
> But `su - mastodon` is not possible, it gives the error `This account is currently not available.`

This is default for almost all service users because they have no login shell. Use ``sudo -u mastodon bash``

> sudo inherits PATH from the user you are coming from?

This is wrong. Sudo resets all path like variables like PATH and PYTHON PATH. Also inheriting needs to be turned on explicitly and PATH mist always ve inherited explicitly.

**Comment by erictapen** [comment]
> Other services like nextcloud include a wrapper that sudos to the right user. This should be added for mastodon, too.

Sounds like a good solution. Then we could make the `mastodon_env` command globally available.

**Comment by SuperSandro2000** [comment]
> Then we could make the `mastodon_env` command globally available.

That isn't? I would have expected that it is very similar to nextcloud-occ.

**Comment by erictapen** [comment]
No currently it is only available to the mastodon user, so tootctl never gets called as the wrong user.

**Comment by SuperSandro2000** [comment]
Yes, this should be adapted. Changing the mastodon to a login user would not be the correct fix.
