### ISSUE TITLE
cpython dev headers

### ISSUE THREAD

**Issue by showierdata9978** [NixOS/nixpkgs#199037]
**Project description**
Python Developer headers

**Metadata**

* homepage URL:  https://github.com/python/cpython/tree/3.11/Include
* source URL: https://github.com/python/cpython/tree/3.11/Include
* license: mit, bsd, gpl2+ , ... PSF License

(i looked and looked, where i could not find them)

**Comment by tjni** [comment]
Here's where I was able to find them:
```
❯ nix build nixpkgs#python310
❯ ls result/include/python3.10/
```
Is identifying where they build to enough for your use case, or do you want to use these in a nix derivation? If the latter, making the cpython derivation a [split derivation](https://nixos.org/manual/nixpkgs/stable/#sec-multiple-outputs-using-split-packages) seems like the best way to design this according to the documentation, but the cpython derivation is [not trivial](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/cpython/default.nix).

**Comment by showierdata9978** [comment]
(spcificly for cython compiling lmao)

**Comment by tjni** [comment]
It sounds like your goal is to set up a development environment for [cython](https://github.com/cython/cython)? If so, I do think it needs to be constructed by reverse engineering how its `setup.py` works. Since `nix` does not install into a [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) directory, builds often need to be told where to find files. Can you share what you have currently?

**Comment by showierdata9978** [comment]
```nix
{ pkgs }: {
  deps = [
    pkgs.llvmPackages_8.clangUseLLVM
    pkgs.python39Packages.cython
    pkgs.python38Full
  ];
  env = {
    PYTHON_LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
    #no external python dependencies

    ];
    PYTHONBIN = "${pkgs.python38Full}/bin/python3.8";
    LANG = "en_US.UTF-8";
  };
}
```

**Comment by showierdata9978** [comment]
nix could prob set the PATH env var for compilers, then put headers there

**Comment by SuperSandro2000** [comment]
Mixing python versions like you do is usually a bad idea and in some situations totally unsupported.

You get the headers in the normal package. NixOS does dev packages differently and some have an dev output. You can get that programmatically with lib.getDev pkgs.python3.
If you need the PC files you want the source which you can get via python3.src.

Also NixOS is not Debian based and does things differently.

**Comment by showierdata9978** [comment]
btw. i found 40 instences of the word header in 'pkgs/top-level/all-packages.nix`

**Comment by SuperSandro2000** [comment]
There are some exceptions and sometimes the package name just happens to contain headers but it is not the rule.

**Comment by tjni** [comment]
If you provide a test project that exhibits a failure message due to not being able to find some files, I can try to help you use the building blocks that Sandro mentions.
