### ISSUE TITLE
git: git-promp.sh is not sourced

### ISSUE THREAD

**Issue by raindev** [NixOS/nixpkgs#199046]
### Describe the bug
git package includes `git-prompt.sh` which defines functions for shell prompt customization like `__git_ps1`. Even though the file is included it's not sourced by default and doesn't make the functions available.

### Steps To Reproduce

1. Install `git` package system-wide.
2. Call one of the functions provided:

```console
$ __git_ps1
__git_ps1: command not found
```

3. Source the file manually:

```console
$ source /run/current-system/sw/share/bash-completion/completions/git-prompt.sh
```

4. The function becomes available:

```console
$ __git_ps1
(main *=)
```

### Expected behavior
`__git_ps1` shell function being available out of the box when `git` package installed.

### Additional context

Making the prompt functions available when bash completions are enabled seem to have been the original intention of #3678. However one might also argue that the functions should not be sourced by default if someone doesn't use git prompt customisations provided. It could be placed behind an option but I'm not sure it's worth the hassle.

### Notify maintainers

cc @primeos @wmertens @globin

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75, NixOS, 22.11 (Raccoon), 22.11pre422531.d40fea9aeb8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tjni** [comment]
I'm not a maintainer or expert, but I read your linked Discourse thread and your ticket because it sounded interesting. Great analysis and writeup.

My interpretation is that `git-prompt.sh` was never intended to be sourced automatically when completions are enabled, for two reasons. First, inside of `git-prompt.sh`:

```
# To enable:
#
#    1) Copy this file to somewhere (e.g. ~/.git-prompt.sh).
#    2) Add the following line to your .bashrc/.zshrc:
#        source ~/.git-prompt.sh
```

which is an explicit instruction to source it explicitly. Second, the [initial commit message](https://github.com/git/git/commit/af31a456b4cd38f2630ed8e556e23954f806a3cc) for `git-prompt.sh` says:

```
bash-completion 1.90 shipped with support to load completions
dynamically[1], which means the git completion script wouldn't be loaded
until the user types 'git <tab>'--this creates a problem to people using
__git_ps1(); that function won't be available when the shell is first
created.

For now distributions have workarounded this issue by moving the git
completion to the "compatdir"[2]; this of course is not ideal.

The solution, proposed by Kerrick Staley[3], is to split the git script
in two; the part that deals with __git_ps1() in one (i.e.
git-prompt.sh), and everything else in another (i.e.
git-completion.bash).

Another benefit of this is that zsh user that are not interested in the
bash completion can use it for their prompts, which has been tried
before[4].
```

which leads me to believe that `git-prompt.sh` was created so that it can be used independently from bash completion. Prior to its creation, it might have been available automatically as a consequence of completion scripts being loaded eagerly, but that was accidental.

**Comment by raindev** [comment]
Thanks for digging deeper into this, Theodore! I agree with your conclusion: it does look like the prompt script wasn't intended to be sourced automatically. I think the best way to approach this in NixOS would be to have a `programs.git.prompt.enable` option that would enable sourcing of the file.

**Comment by tjni** [comment]
I think something like this sounds reasonable. I'm sorry I can't help with it right now, because I haven't set up NixOS yet. (I'm just using nix on my Mac right now.)

**Comment by raindev** [comment]
No worries, thanks for your help so far :) I might eventually give it a shot myself.
