### ISSUE TITLE
nixpkgs-review broken due to nixpkgs "linux_xanmod_tt: remove" commit

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#199030]
### Describe the bug
`nixpkgs-review pr <PR>` fails for me now with `error: linux_xanmod_tt was removed because upstream no longer offers this option`.

### Steps To Reproduce
1. `nixpkgs-review pr 198904`
2. Watch it fail with `error: linux_xanmod_tt was removed because upstream no longer offers this option`

### Expected behavior
nixpkgs throws are made so that `nixpkgs-review` still works(?).

### Additional context
The problematic change was done a day ago: 0a242b15735b7375e9842d54545f3b8dd93c3ddf, cc @fortuneteller2k.

**Comment by QuantMint** [comment]
> ### Describe the bug
> 
> `nixpkgs-review pr <PR>` fails for me now with `error: linux_xanmod_tt was removed because upstream no longer offers this option`.
> ### Steps To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. `nixpkgs-review pr 198904`
> 
>     2. Watch it fail with `error: linux_xanmod_tt was removed because upstream no longer offers this option`
> 
> 
> ### Expected behavior
> 
> nixpkgs throws are made so that `nixpkgs-review` still works(?).
> ### Additional context
> 
> The problematic change was done a day ago: [0a242b1](https://github.com/NixOS/nixpkgs/commit/0a242b15735b7375e9842d54545f3b8dd93c3ddf), cc @fortuneteller2k.

If you rebase the pr on top of the latest nixpkgs it works.

**Comment by bjornfor** [comment]
> If you rebase the pr on top of the latest nixpkgs it works.

I didn't know, thanks!
