### ISSUE TITLE
Use .tbd files for pure Darwin builds even against impure runtimes

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#19906]
This will likely be a sweeping change but should make some impure things a lot cleaner and less questionably legal.

**Comment by copumpkin** [comment]
Now that TAPI is open source, this is a lot more feasible

**Comment by matthewbauer** [comment]
I have a branch trying to get this in for iOS SDK support:

https://github.com/matthewbauer/nixpkgs/commit/69347697d3336d4b6add8276d9f75daf6f0cacf3

Unfortunately I get infinite recursion if I enableTapiSupport everywhere.

**Comment by thefloweringash** [comment]
still important to me

**Comment by stephank** [comment]
I believe this issue can be closed? (Seems like GitHub didn't pick up the 'closes x' instruction from the PR description in #98541.)

There's already a separate issue for the bootstrap: #104580
