### ISSUE TITLE
Should xorg.libXrender depend on xorg.renderproto?

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#19909]
## Issue description

I was building the X11-xft haskell packages, which depends on xorg.libXrender. When I was building it, I got the following error: 

```
   Configuring X11-xft-0.3.1...
    Building X11-xft-0.3.1...
    Preprocessing library X11-xft-0.3.1...
    In file included from /nix/store/c2agadvhwg3cz3qbzsy5fbmcgjkbsn78-libXft-2.3.2-dev/include/X11/Xft/Xft.h:42:0,
                     from Xft.hsc:62:
    /nix/store/s8lm5v6aafjahj186y9dfmj7i83686sr-libXrender-0.9.9-dev/include/X11/extensions/Xrender.h:33:35: fatal error: X11/extensions/render.h: No such file or directory
    compilation terminated.
```

This suggests that libXrender depends on `X11/extensions/render.h`, which is contained in `xorg.renderproto`. Should we add this to the `buildInputs` for libXrender?

## Technical details

* System: 17.03pre93673.09e4b78 (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre93673.09e4b78

**Comment by groxxda** [comment]
`libXrender` has the dependency in `buildInputs`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/default.nix#L902-L911
But it looks like none of our x packages propagates inputs. Since the linked file is autogenerated, I would suggest adding `libXrender.renderproto` to X11-xft's buildInputs.

**Comment by sid-kap** [comment]
You mean add to the haskell package? I installed it using stack---not using nix---so that wouldn't be an option. (I mean, I could add it, for those who build using haskellPackages.X11-xft, but it wouldn't apply to my situation.)

**Comment by sid-kap** [comment]
Hmm. That's strange that the x packages don't propagate inputs. Do you think that's a bug?

**Comment by vcunat** [comment]
We do have quite some propagation added to xorg packages; see https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/overrides.nix This missing dependency is relatively easy to fix; I staged 4fee7fc.

**Comment by groxxda** [comment]
Thanks for clarification and the fix @vcunat  :+1:

**Comment by sid-kap** [comment]
Thank you!!
