### ISSUE TITLE
gnome.gnome_icon_theme install doesn't work

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#19908]
## Issue description

According to https://nixos.org/nixos/packages.html, gnome-icon-theme can be installed by adiding the attribute name `gnome.gnome_icon_theme` to my environment.systemPackages. However, this gives the error that gnome.gnome_icon_theme cannot be found.

If I instead type `gnome2.gnome_icon_theme`, then it works. Is there a typo in the packages list?
## Technical details
- System: 17.03pre93673.09e4b78 (Gorilla)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 17.03pre93673.09e4b78

**Comment by jtojnar** [comment]
This does not seem to be an issue any more – the package lists `gnome2.gnome_icon_theme` as the attribute name..

**Comment by sid-kap** [comment]
I don't have another example, but fairly often the two are out of sync. Why is this? Is it because I'm on unstable?

**Comment by jtojnar** [comment]
@sid-kap Yes, the website only tracks stable release. See https://github.com/NixOS/nixos-homepage/issues/53

**Comment by sid-kap** [comment]
Okay, thanks!
