### ISSUE TITLE
python: pyfilesystems2

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nixpkgs#199166]
**Project description**

Python file system abstraction layer

**Metadata**

* homepage URL: https://www.pyfilesystem.org/
* source URL: https://github.com/pyfilesystem/pyfilesystem2
* license: MIT
* platforms: linux

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/fs/default.nix#L64

**Comment by armijnhemel** [comment]
> https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/fs/default.nix#L64

Yeah, I totally missed that one, because of the name. Anyway, the license in the default.nix is wrong, but that is something that can be fixed later. Closing, thanks!
