### ISSUE TITLE
Gitea v1.17.3: "159 bad syscall" when running systemd pre-exec script

### ISSUE THREAD

**Issue by h7x4** [NixOS/nixpkgs#199234]
### Describe the bug
Running the pre-execution script for gitea `v1.17.3` on nixpkgs-unstable results in error `159: bad syscall` during migration.

This does not happen when running the offending command from the script directly.

### Steps To Reproduce

I have not been able to test these steps, but this should reproduce the error:

1. Create a gitea instance + database with nixpkgs 22.05
2. Rebuild the system using gitea `v1.17.3` from nixpkgs unstable
3. This should force it to run the (probably faulty?) pre-execution script.

### Expected behavior

It should run without any problems, or at least display a proper error message.

### Additional context

<details>
  <summary><b>Relevant output from journalctl</b></summary>

```
Nov 02 18:26:24 Tsuki systemd[1]: Starting gitea...
░░ Subject: A start job for unit gitea.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit gitea.service has begun execution.
░░
░░ The job identifier is 50735.
Nov 02 18:26:25 Tsuki gitea-pre-start[115796]: /nix/store/6xgk9qsl5r9nahg8ml2jh0y6g4vvbfxh-unit-script-gitea-pre-start/bin/gitea-pre-start: line 42: 115810 Bad system call         (core dumped) /nix/store/j3dp9rv3nnav6bssi1vnmd52wg7rfaqy-gitea-1.17.3/bin/gitea migrate
Nov 02 18:26:25 Tsuki systemd[1]: gitea.service: Control process exited, code=exited, status=159/n/a
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ An ExecStartPre= process belonging to unit gitea.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 159.
Nov 02 18:26:25 Tsuki systemd[1]: gitea.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit gitea.service has entered the 'failed' state with result 'exit-code'.
Nov 02 18:26:25 Tsuki systemd[1]: Failed to start gitea.
░░ Subject: A start job for unit gitea.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit gitea.service has finished with a failure.
░░
░░ The job identifier is 50735 and the job result is failed.
```

</details>

- This happened when I was trying to upgrade from gitea `v1.17.2` to `v1.17.3` on nixpkgs unstable.

- I also found (#74849) from 2019, with a similar error code. It seems like the fix had something to do with the `SystemCallFilter`. If the error lies in the systemd unit settings, it might explain why I'm able to run the command alone without problems.

- `SystemCallFilter` was recently changed in (#197472) due to (#197443).

- When I run `gitea migrate` manually, I need to run it as the gitea user (`git` in my case), and point it to the `app.ini` in its stateDir with the `-c` flag in order to run properly.

- I have verified that the database was properly migrated afterwards by inspecting its tables and columns.

### Notify maintainers

@srhb @Ma27

@MidAutumnMoon, do you know what might be happening, since you authored #197472?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/qypk3gzaf4p5bhzmyzjmlycs8v2sdw2h-nix-info
copying path '/nix/store/qypk3gzaf4p5bhzmyzjmlycs8v2sdw2h-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-21.11, nixos-21.11.334625.86453059bf8"`
 - channels(h7x4): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**NOTE:** the system configuration is built from a flake, so the channels above are not up to date, nor representative for the actual version of gitea installed. These are the pinned versions of nixpkgs from the flake lock:

**Nixpkgs 22.05**:
  "rev": "b3a8f7ed267e0a7ed100eb7d716c9137ff120fe3"

**Nixpkgs unstable**:
  "rev": "d40fea9aeb8840fea0d377baa4b38e39b9582458"
  
```console
~ > /nix/store/j3dp9rv3nnav6bssi1vnmd52wg7rfaqy-gitea-1.17.3/bin/gitea --version
Gitea version 1.17.3 built with go1.19.2 : pam, sqlite, sqlite_unlock_notify
```

**Comment by h7x4** [comment]
This was a stupid error on my part.

The syscall that made the program crash was `160: setrlimit`, which is part of `@resources`, which was reallowed in #197472. I had configured the gitea package to be from nixpkgs unstable, but the `services.gitea` module itself was still from nixpkgs stable. As a consequence, the systemd unit for gitea still had `@resources` blacklisted.

No action needed.

**Comment by nico202** [comment]
I'm on channel [22.11](https://nixos.org/channels/nixos-22.11) and I'm experiencing this, has it been backported?


```
/nix/store/prsfpcqvfrvz5awdvcjb843p4pnzjbil-unit-script-gitea-pre-start/bin/gitea-pre-start: line 42: 2650806 Bad system call         (core dumped) /nix/store/rh6vgb8l7dzjsh7ybynz89vibr43aq72-gitea-1.17.4/bin/gitea migrate
```

**Comment by nico202** [comment]
Damn, I had a "gitea.serviceConfig.SystemCallFilter" override in my config file for some reason which was causing this
