### ISSUE TITLE
tt-rss package: setup missing out of the box

### ISSUE THREAD

**Issue by NoraCodes** [NixOS/nixpkgs#199299]
The tt-rss package has an option, `services.tt-rss.database.createLocally`, which should set up the database locally. It does set up the database, but doesn't initialize the schema. This is awkward.

I'm filing this issue primarily so that the search results for "nixos tt-rss base database schema" will be useful.

Users will see an error message like:

> Base database schema is missing. Either load it manually or perform a migration (update.php --update-schema)

You do need to do this. Enter a `nix-shell -p php`, then switch users to your configured tt-rss user (by default, `sudo -u tt_rss -i`) and run the command `/var/lib/tt-rss/www/update.php --update-schema`.

**Comment by linuxissuper** [comment]
thanks for the comment  
this was really helpful :)   

this is what I ended up using: `sudo -u tt_rss php /var/lib/tt-rss/www/update.php --update-schema`

**Comment by Kaligule** [comment]
Also helpful to me, thank you.

@NoraCodes Why have you closed this issue immediately? Isn't this fix-worthy?

**Comment by NoraCodes** [comment]
Doesn't seem like it's really NixOS' responsibility, but I'm open to being wrong on that.

**Comment by Kaligule** [comment]
I would expect that tt-rrs would work "out of the box" if the nixos-config is right. This doesn't seem to be the case, you had to call an php script after the nixos-rebuild. Interactivly, not declarativly. That sounds like it doesn't fit into nixos's way of doing things. I would expect that there is some canonical way to do this in [tt-rss.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-apps/tt-rss.nix) (though I don't know enough about nixpkgs or php to be sure). Would you agree?
