### ISSUE TITLE
 Can't find Firefox in GNOME on Fedora

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#19934]
## Issue description

This is definitely a stupid question, so please have patience. I'm trying nix on a non-NixOS distribution (Fedora) for the first time, and have installed Firefox with Nix and uninstalled it via dnf. However, Firefox no longer appears in the Gnome menu. Is there a way to fix this?
### Steps to reproduce
1. Install any X program on another distribution while using GNOME
2. Look for it in the menu
## Technical details
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: "17.03pre94297.6dc6147"

**Comment by vcunat** [comment]
I expect this is about `$XDG_DATA_DIRS` environment variable missing `${HOME}/.nix-profile/share`.

**Comment by siddharthist** [comment]
@vcunat Any idea how to fix that? I've tried setting that variable in my `~/.profile`, but GNOME won't allow me to log in after that.

**Comment by vcunat** [comment]
They most likely rely on it [defaulting](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to ` /usr/local/share/:/usr/share/`; extending it instead of overwriting will probably fix that, though this mixing probably also isn't completely without dangers.

**Comment by siddharthist** [comment]
Ah, I already tried using the colon-separation trick: 
```
export XDG_DATA_DIRS=${XDG_DATA_DIRS}:/home/siddharthist/.nix-profile/share
```

**Comment by vcunat** [comment]
Yeah, but you probably need to put in the default explicitly. Standard distros leave it empty and they probably rely on that to default to `/usr/local/share/:/usr/share/` as required by the XDG spec.

**Comment by siddharthist** [comment]
@vcunat You're absolutely right, I added those two directories and it worked! Is this something we could fix in nixpkgs?

**Comment by siddharthist** [comment]
And it works!! I can now see my nix packages in GNOME (after logging out and logging back in). Thanks so much @vcunat!

**Comment by vcunat** [comment]
Maybe, but I personally don't feel like spending much time on such details for non-nixos only.
