### ISSUE TITLE
packaging request: Memento Video Player

### ISSUE THREAD

**Issue by zoro11031** [NixOS/nixpkgs#199453]
**Memento**
Memento is a FOSS, mpv-based video player for studying Japanese.

**Metadata**

* homepage URL: https://github.com/ripose-jp/Memento
* source URL: https://github.com/ripose-jp/Memento/find/master
* license: gpl2
* platforms: linux

**Comment by teto** [comment]
wip at https://github.com/NixOS/nixpkgs/pull/230786
