### ISSUE TITLE
Elm Package installation fail

### ISSUE THREAD

**Issue by dyrnade** [NixOS/nixpkgs#19943]
## Issue description

First time ever i  was installing elm and i got below errors.

building path(s) ‘/nix/store/4r6fw84g0k0y7bfx7ggbav9z26m0x9ln-elm-0.17.1’
created 8 symlinks in user environment
building path(s) ‘/nix/store/9vshyngqc8gqi7zdywa0xxaxxvm9ksp4-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/59ld06whck9pr9yyg0g57zi49679v5dg-elm-format-0.4.0/bin/elm-format-0.16’ and ‘/nix/store/4r6fw84g0k0y7bfx7ggbav9z26m0x9ln-elm-0.17.1/bin/elm-format-0.16’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/wfyxszic0kp26qsxs130zprm0rs8ryi7-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/wfyxszic0kp26qsxs130zprm0rs8ryi7-user-environment.drv’ failed
### Steps to reproduce

nix-env -iA nixos.elmPackages
## Technical details
- System: (NixOS: `16.09.840.27b37f1 (Flounder)`)
- Nix version: (`nix-env (Nix) 1.11.4`)
- Nixpkgs version: (`"16.09.846.0195ab8"`)

**Comment by NeQuissimus** [comment]
Looks similar to #19761

**Comment by domenkozar** [comment]
Use an older version for the time being like https://github.com/domenkozar/kamdanes.si/blob/master/frontend/default.nix#L1
