### ISSUE TITLE
Incorrect superuser setup instructions for paperless service

### ISSUE THREAD

**Issue by joepie91** [NixOS/nixpkgs#199568]
## Problem

The documentation for [services.paperless.passwordFile](https://search.nixos.org/options?channel=22.05&show=services.paperless.passwordFile&from=0&size=50&sort=relevance&type=packages&query=paperless) says the following:

> A file containing the superuser password. A superuser is required to access the web interface. If unset, you can create a superuser manually by running `${dataDir}/paperless-manage createsuperuser`.

... however, actually trying to do so results in the following error:

```
/home/sven〉/var/lib/paperless/paperless-manage createsuperuser                                                                                                                                                                                                       11/04/2022 09:59:36 PM
SystemCheckError: System check identified some issues:

ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
        HINT: Set the permissions of 
drwxr-xr-x /var/lib/paperless/consume
 to be writeable by the user running the Paperless services
?: PAPERLESS_DATA_DIR is not writeable
        HINT: Set the permissions of 
drwxr-xr-x /var/lib/paperless
 to be writeable by the user running the Paperless services
?: PAPERLESS_MEDIA_ROOT is not writeable
        HINT: Set the permissions of 
drwxr-xr-x /var/lib/paperless/media
 to be writeable by the user running the Paperless services
```

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

Either the documentation should be updated to remove this instruction, or (preferably) the package should be fixed such that the imperative setup instructions actually work.

**Comment by Atemu** [comment]
@joepie91 are you still able to reproduce?

**Comment by joepie91** [comment]
I don't think I will be able to reproduce this any more accurately than anyone else; as the command is possibly destructive, I can't try to run it locally without risking trashing my existing installation. Given that it's a setup command, if the bug still exists it *should* be reproducible in a clean environment. I don't currently have the time to reproduce in a clean environment either, unfortunately.

**Comment by Atemu** [comment]
Okay. In my recent installation setting up a superuser from scratch worked as expected, so this probably just works now.

**Comment by Mastermindaxe** [comment]
I have the same error here. Could it be that it wants that command to already run under the `paperless` user?

Trying to set up paperless rn and can't seem to figure out the default password that's why I tried that command.

**Comment by Atemu** [comment]
Oh yes that's right, you need to `sudo -u paperless /var/lib/paperless-manage`. I forgot I was doing that because it's so obvious. Not doing that would indeed confuse a permissions check.
