### ISSUE TITLE
Allow specifying custom "site start" in Emacs

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#19956]
## Issue description

I opened PR #17806 to enable something like this. Basically, I want an option to do something like:

```
{pkgs ? (import <nixpkgs>)}:
with pkgs;
{
  emacs = emacsWrapper {
    pkgs = [ ];
    siteStart = ''
      ;; my elisp configuration
      ;; setup pkgs from above
    '';
  };
}
```

This would make it easier to integrate the emacs config and the emacs packages all within nixpkgs. 

The PR has been reverted and I can't quite figure out how to fix it.

**Comment by rlupton20** [comment]
@ttuegel do you recall why the pull request got rejected (8 months ago I know, so perhaps pushing it a bit to expect you to remember :smile: )? The commit message is a little vague on details as to what the exact problem is.

I'm happy to help fix this up with @matthewbauer as needed.

**Comment by matthewbauer** [comment]
IIRC the pr was merged but then it broke some evaluation with Hydra. Somewhere Emacs was being used in an unusual way...

**Comment by rlupton20** [comment]
Hmm ok. I'm not seeing why that would be the case - I'll take a closer look soon.

**Comment by matthewbauer** [comment]
Ok this is the issue that caused the reversion: #17853
