### ISSUE TITLE
Won't boot when root on raid0 with `boot.initrd.systemd=true`

### ISSUE THREAD

**Issue by kchibisov** [NixOS/nixpkgs#199551]
### Describe the bug

The system doesn't boot being stuck at systemd looking for device by uuid. 
My disks setup is relatively simple. I have 2 nvme disks in raid0 with ext4 on them.
So nothing really special. The exact same config without `boot.initrd.systemd` works fine.

### Steps To Reproduce

Do `boot.initrd.systemd.enable = true;` having root on software `mdadm` raid.

The systemd will stuck looking for the disk by uuid and won't be able to find it...

### Expected behavior

It boots and the default initrd with systemd could figure out that I have root on raid0 (I see 
it adding stuff related, maybe the order it starts things is weird?).

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6, NixOS, 22.11 (Raccoon), 22.11pre423682.7d09cc075f4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by ajs124** [comment]
iirc this is a known issue/intended behavior. do you have `boot.initrd.services.swraid.enable = true;` set?

**Comment by kchibisov** [comment]
@ajs124 I don't and there's no such option?

```
error: The option `boot.loader.services' does not exist. Definition values:
       - In `/etc/nixos/hosts/Zodiac/hardware.nix':
           {
             swraid = {
               enable = true;
             };
           }
(use '--show-trace' to show detailed location information)

```

There's an `boot.initrd.services.swraid.mdadmConf` which I have
set to 
```
  boot.initrd.services.swraid.mdadmConf = ''
    DEVICE /dev/nvme0n1p2 /dev/nvme1n1p1
    ARRAY /dev/md/nixos:zodiac-raid metadata=1.2 name=nixos:zodiac-raid UUID=f2eb8feb:45479c47:9291aed0:a31a629b
  '';

```

Which I got from running `mdadm --detail --scan`. Still doesn't work.

Maybe it's timing/order issue since normal initrd works without anything special.

**Comment by ajs124** [comment]
`boot.initrd.services` not `boot.loader.services`. It's in `nixos/modules/tasks/swraid.nix`, there's a test for it in `nixos/tests/systemd-initrd-swraid.nix`.

**Comment by kchibisov** [comment]
Still doesn't work.

The config I have.

hardware-configuration.nix
```nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d3ec791c-96ec-41e4-adda-f21bb36dd0c5";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3947-F2F9";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

```

And the extra stuff I wrote
```nix
{ config, pkgs, ... }:

{
  boot.initrd.systemd.enable = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.initrd.services.swraid.enable = true;
  boot.initrd.services.swraid.mdadmConf=''
    DEVICE /dev/nvme0n1p2 /dev/nvme1n1p1
    ARRAY /dev/md/nixos:zodiac-raid metadata=1.2 name=nixos:zodiac-raid UUID=f2eb8feb:45479c47:9291aed0:a31a629b
  '';
}
```

**Comment by kchibisov** [comment]
![photo_2022-11-09_21-45-10](https://user-images.githubusercontent.com/27620401/200914870-03b91a10-314f-47db-9c30-04a015dea600.jpg)

**Comment by mmarx** [comment]
For some reason, it seems the `/dev/disk/by-uuid/…` labels are not yet available in the initrd (although they are there once the system has booted) in 22.11 (they were in 22.05). My current workaround is using the `/dev/dis/by-id/md-name-…` links, which are already present in the initrd.

**Comment by kchibisov** [comment]
The `by-uuid` stuff is brought by udev so if you don't start udev and wait for it to enumerate stuff you won't have by-uuid labels. I think I've tried without them, but maybe I was doing it wrong. Though, it's not like I need systemd in initrd that badly on this system.

**Comment by mmarx** [comment]
It's just the `by-uuid` links for the `md` devices that are missing, though, the underlying partitions do get `by-uuid` links. So likely there has been some change in the udev rules that is involved here?

**Comment by kravemir** [comment]
> My current workaround is using the /dev/disk/by-id/md-name-… links, which are already present in the initrd.

This gets more complex to configure with multiple mdadm RAIDs. I've described a workaround tutorial in a comment for a similar issue:

- https://github.com/NixOS/nixpkgs/issues/196800#issuecomment-1382712060

**Comment by brprice** [comment]
> `boot.initrd.services` not `boot.loader.services`. It's in `nixos/modules/tasks/swraid.nix`, there's a test for it in `nixos/tests/systemd-initrd-swraid.nix`.

As I understand it, this option will only have an effect if `boot.initrd.systemd.enable = true`, but this option is documented as "this is in very early development and is highly experimental", so I imagine most people are not running that.

**Comment by brprice** [comment]
Another workaround that works for my testing on a VM (using raid->crypt->ext4, based on https://github.com/NixOS/nixpkgs /commit/a14d1a2e7e8c19087897bc646a37f50096b736b1 -- this is the `git bisect` blamed commit, according to #196800) is adding `boot.initrd.preLVMCommands = "udevadm trigger --settle";` to my configuration.

**Comment by kchibisov** [comment]
It seems to work just fine for me now with `stateVersion 23.11` and `boot.swraid.enable = true`.

**Comment by shackra** [comment]
> It seems to work just fine for me now with `stateVersion 23.11` and `boot.swraid.enable = true`.

it broke for me, coming from `23.05` I have /var on a RAID device

![image](https://github.com/NixOS/nixpkgs/assets/1055216/a30f62e8-7f28-4763-b0a8-8bbbd66d4796)

**Comment by shackra** [comment]
nvm, it was because I had this line `environment.etc = { "mdadm.conf".text = raid0; };` duplicating the contents of `/etc/mdadm.conf`
