### ISSUE TITLE
Doesn't boot with root on nvme on aarch64

### ISSUE THREAD

**Issue by kchibisov** [NixOS/nixpkgs#199552]
### Describe the bug

I can't get to boot `aarch64` system on nvme (Tried explicitly putting nvme into initrd, different initrd options, ect, ect, nothing helps).

The system is UEFI based (using Tow-Boot) with emmc and nvme drives attached to it.
During boot it's getting stuck on finding (waiting for device timeouts) nvme drives and fails to do so.

The initramfs contains the modules for nvme, etc, etc. I see them being added when `initrd`
builds and I also explicitly added them as modules. The kernel does provide the modules.
Everything I use is from `nixpkgs`, the kernel is latest available.

The same system boots fine and operates normally if I put root on `emmc` and
the rest into `nvme` (swap and home particions). 

The system is `Rock Pi 4B` with an nvme drive.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.0.5, NixOS, 22.05 (Quokka), 22.05.3935.b3a8f7ed267`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.05"`
 - channels(kchibisov): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by chrissound** [comment]
I seem to have run into a similar or the same problem. If you enter recovery mode via grub (I think by pressing `r`), and do a `ls -l` - do you see the drive listed with the correct UUID? As that is what see.

The actual error in my case is `"Timed out waiting for device /dev/disk/by-uuid/... to appear"`.

**Comment by kchibisov** [comment]
@chrissound I don't think you have the same issue as mine, because in my case it doesn't matter whether you're using UUID or something else (the disk is just not there early on). The issue only happens on AArch64 board for me and only with nixOS (worked with gentoo), the exact same config on X86 boots just fine.

Though, I'll try to troubleshoot my issue in a near future a bit, maybe it's already fixed though, since it was a while ago.

**Comment by kchibisov** [comment]
Ok, after getting some help from `nixos arm` matrix channel, my device required `nvme phy_rockchip_pcie pcie_rockchip_host` in `initrd`, after adding them it all worked. The key part were `phy_rockchip_pcie`.
