### ISSUE TITLE
udevRules: missing documentation

### ISSUE THREAD

**Issue by laikq** [NixOS/nixpkgs#199671]
## Problem

If I'm correct, `stdenv.mkDerivation` accepts an argument `udevRules`. I found it in the code, but not in the nixpkgs manual.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

Document it in nixpkgs manual section 6.4 Attributes?

**Comment by bjornfor** [comment]
Almost everything passed to stdenv.mkDerivation gets exposed as environment variables in the builder processes, so `udevRules` isn't anything special to mkDerivation.

**Comment by laikq** [comment]
Hmm, now I see that every package making use of `udevRules` uses it in the install phase separately. I thought the `stdenv.mkDerivation` builder would use it. OK.
