### ISSUE TITLE
openssl.bin depends on perl because of c_rehash

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixpkgs#19965]
Trying to build a small docker image of a nodejs project I noticed that `openssl` depends on `perl`:

```
3.4M    /nix/store/55azyw1bcrzn8q5ganaav0cnqs2viwdn-openssl-1.0.2i
48M     /nix/store/xcp6lrq3ynj75cqcyy7b32jgizf9jr4b-perl-5.22.2
```

The reason for this runtime dependency is the inclusion of `c_rehash`:

```
# Perl c_rehash script, scan all files in a directory
# and add symbolic links to their hash values.
```

There are no references to `c_rehash` in nixpkgs. Would any oppose dropping this from `openssl-bin`?

/cc @edolstra

**Comment by vcunat** [comment]
Actually, it seems that nodejs does *not* need to depend on `openssl.bin`. All the references I see in the resulting binary are to `${openssl.bin}/include` and `${openssl..bin}/lib`, neither of which exists.

**Comment by gilligan** [comment]
@vcunat Hm, while this of course not the core issue you are indeed right I suppose. I guess this could be fixed by passing in `openssl.lib` to the nodejs derivation instead of `openssl`?

```
/nix/store/7agkqzpq2qnb1ab6gq7chmjf8x42hqcx-nodejs-6.6.0
+---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
+---/nix/store/ly5dbisg2h0k3xnfdbk955m3pc4knvjk-gcc-5.4.0-lib
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/ly5dbisg2h0k3xnfdbk955m3pc4knvjk-gcc-5.4.0-lib [...]
+---/nix/store/09rfjicwds107wknldxjhi3swwml1pig-http-parser-2.7.0
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/ly5dbisg2h0k3xnfdbk955m3pc4knvjk-gcc-5.4.0-lib [...]
+---/nix/store/55azyw1bcrzn8q5ganaav0cnqs2viwdn-openssl-1.0.2i
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/55azyw1bcrzn8q5ganaav0cnqs2viwdn-openssl-1.0.2i [...]
+---/nix/store/47ddkjfrphqp8zxd8cq9xa10l0xr8qkv-openssl-1.0.2i-bin
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/55azyw1bcrzn8q5ganaav0cnqs2viwdn-openssl-1.0.2i [...]
|   +---/nix/store/xcp6lrq3ynj75cqcyy7b32jgizf9jr4b-perl-5.22.2
|       +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|       +---/nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25
|       |   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|       |   +---/nix/store/6h29qi09p6p4kh04n3pyg7wa0sn7gryv-acl-2.2.52
|       |   |   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|       |   |   +---/nix/store/scblgh0h3sh65s0rp0nv79rr82mjd6cm-attr-2.4.47
|       |   |   |   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|       |   |   |   +---/nix/store/scblgh0h3sh65s0rp0nv79rr82mjd6cm-attr-2.4.47 [...]
|       |   |   +---/nix/store/6h29qi09p6p4kh04n3pyg7wa0sn7gryv-acl-2.2.52 [...]
|       |   +---/nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25 [...]
|       +---/nix/store/xcp6lrq3ynj75cqcyy7b32jgizf9jr4b-perl-5.22.2 [...]
+---/nix/store/b5mwbrx8cldkchiqgwgkaagw91xfjr89-zlib-1.2.8
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
+---/nix/store/mh7snrv03k9d6pz7xz7ysc98l6r8phnl-libuv-1.9.1
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/mh7snrv03k9d6pz7xz7ysc98l6r8phnl-libuv-1.9.1 [...]
+---/nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46 [...]
+---/nix/store/w9020qsqapllmfcdh2x686y8ng6n15mh-python-2.7.12
|   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   +---/nix/store/55azyw1bcrzn8q5ganaav0cnqs2viwdn-openssl-1.0.2i [...]
|   +---/nix/store/9jplq6zqlfixn2drgq07jgvcabjrmn47-bzip2-1.0.6.0.1
|   |   +---/nix/store/6fix3zqpnahyml8zp2sxi2rwan55rgb8-glibc-2.24 [...]
|   |   +---/nix/store/9jplq6zqlfixn2drgq07jgvcabjrmn47-bzip2-1.0.6.0.1 [...]
|   +---/nix/store/b5mwbrx8cldkchiqgwgkaagw91xfjr89-zlib-1.2.8 [...]
|   +---/nix/store/nyj6xd7s1n1w8c0xdwk5ddhi7bjcyi9x-bash-4.3-p46 [...]
|   +---/nix/store/zhhb02yrp03xzfrpk06ixb0gmwrjmjff-coreutils-8.25 [...]
|   +---/nix/store/w9020qsqapllmfcdh2x686y8ng6n15mh-python-2.7.12 [...]
+---/nix/store/7agkqzpq2qnb1ab6gq7chmjf8x42hqcx-nodejs-6.6.0 [...]
```

**Comment by vcunat** [comment]
I do have a solution already; I'm just polishing it.

**Comment by gilligan** [comment]
@vcunat :+1:

**Comment by vcunat** [comment]
I'm having a bit of hard time with nodejs trying to inject include paths into the output binary.

**Comment by gilligan** [comment]
@vcunat i would still say that the core issue is that openssl-bin which in itself is just 3MB introduces a 48MB dependency via perl because of that `c_rehash` script- regardless of whether nodejs needs openssl or not. The same obviously applies for anything else using `openssl-bin`.

**Comment by vcunat** [comment]
But nodejs doesn't need openssl-bin at all, same as most other packages. They use the libraries.

**Comment by gilligan** [comment]
Yes I get that. Those are two separate issues though - both of which should be fixed I guess.

**Comment by vcunat** [comment]
Further splitting openssl-bin to two outputs would seem confusing to me &ndash; the current convention is that if `pkg.bin` exists, it contains all the executables.

**Comment by gilligan** [comment]
Well this perl script really does not seem like an integral part of openssl to me. I am doubtful that most people want that when they install openssl

**Comment by gilligan** [comment]
Then again I am certainly not an openssl expert. Wonder if other distributions openssl packages include it

**Comment by vcunat** [comment]
[Debian](https://packages.debian.org/jessie/amd64/openssl/filelist) and [Arch](https://www.archlinux.org/packages/core/x86_64/openssl/) do so; Fedora splits away [openssl-perl "output"](https://apps.fedoraproject.org/packages/openssl-perl/) that also contains some more utilities.

**Comment by vcunat** [comment]
BTW, another big dependency is python, referred only from `lib/node_modules/npm/node_modules/node-gyp/gyp` but I know too little about nodejs to get into such internals.

**Comment by vcunat** [comment]
@gilligan: for now I'd fix up nodejs at least. Can you test the change 95a0766dd1e with the stuff you use?

It builds, but there seems to be a tiny chance that some node package actually relied on some ability to query which include paths were used.

**Comment by gilligan** [comment]
@vcunat will do so later and report back.

**Comment by gilligan** [comment]
> BTW, another big dependency is python, referred only from lib/node_modules/npm/node_modules/node-gyp/gyp but I know too little about nodejs to get into such internals.

Yep, I have a PR for that ready. It adds a `slim` variation that packages node without npm. Which is a common variation anyway.

**Comment by gilligan** [comment]
@vcunat I tried the change to nodejs and from what I can tell from testing it is working just fine!

**Comment by gilligan** [comment]
By the way I created #19973 to address the  `nodejs -> npm -> python` dependency

**Comment by gilligan** [comment]
@vcunat I incorporated your change into #19973

**Comment by vcunat** [comment]
Great; I was just about to suggest that.

**Comment by copumpkin** [comment]
Maybe just stick `c_rehash` into an output by itself, and make `$bin/bin/c_rehash` into a script that tells you where to find the real one?

**Comment by vcunat** [comment]
Interesting idea with the script, but it apparently has some downsides with `which c_rehash` and environment collisions. I didn't want to act on this myself, as I didn't see much to gain:
-  there are very few explicit `openssl.bin` references in nixpkgs and I don't expect many more implicit ones;
- perl is a very common dependency &ndash; in particular, nixos users are forced to depend on it anyway.

**Comment by Profpatsch** [comment]
(triage) was this fixed by now?

**Comment by vcunat** [comment]
It seems to be the same, but I personally don't consider it wrong.

**Comment by gilligan** [comment]
Well, “wrong”..  the fact remains that openssl itself is < 4MB and the perl dependency increases the closure size by almost 50MB for something i haven’t even ever heard anyone mention anywhere ever so.. i guess “meh”

**Comment by goertzenator** [comment]
Could we add a flag `withPerlScripts ? true` to control the existence of `c_rehash`?

Context: I am working on a space limited embedded system.  I do need the 600kB binary found in `openssl.bin`, but I don't need `c_rehash` and its 50MB perl dependency.

**Comment by gnprice** [comment]
It seems this has been fixed!

Here's the closure of `openssl.bin` -- no Perl, and total size <8MB excluding glibc:
```
$ nix path-info -s $(nix-store -qR $(nix-build -A openssl.bin))
/nix/store/0gr5bsynx3qnxwplqdzgj0gb60mhnzy0-libunistring-0.9.10	    1634416
/nix/store/2lygwhmhagpi7k6pxnw8wimh6aiih5z2-openssl-1.1.1d     	    4146504
/nix/store/5ljnwy2i3gg6irysjyqacj61qs90y9cr-openssl-1.1.1d-bin 	     771744
/nix/store/7s4pysk2smm1xdp787lkfz31l39l5lvf-libidn2-2.3.0      	     222672
/nix/store/9rabxvqbv0vgjmydiv59wkz768b5fmbc-glibc-2.30         	   31082264
```

I got here from looking at #83446. @oxalica observes there:
> now the perl script `c_rehash` produced by `openssl.bin` has shebang `#!/usr/bin/env perl`, which means we don't need to substitute it anymore.

and I think that same change in the (upstream?) shebang line would also have fixed this issue.

**Comment by vcunat** [comment]
I confirm this seems fixed on all maintained branches (i.e. including 19.09).

**Comment by thomasjm** [comment]
This seems to be broken again on master, could we reopen this issue?

```
nix path-info -sh $(nix-store -qR $(nix-build -A openssl.bin))
/nix/store/176gh50y24c0lx2bnnmsvf9wazb73php-coreutils-9.0          1.8M
/nix/store/5b40cks3m9nhkxiy4g9jsaqbp1vipc6g-attr-2.5.1            78.7K
/nix/store/6wcdxh3h5jp9qgrccq3n71wnalca5mf5-perl-5.34.0           53.1M ***
/nix/store/f472rqx45rdhq2dl8xhjlwwj56wjpjsj-openssl-1.1.1m-bin   760.5K
/nix/store/nq7z9djyxaj6j7w9mgp94a6sds1jppi4-libidn2-2.3.2        254.7K
/nix/store/rf9d67pk49l2sq26qiwwp1wl727qf11f-acl-2.3.1            108.9K
/nix/store/s9qbqh7gzacs7h68b2jfmn9l6q4jwfjz-glibc-2.33-59         29.8M
/nix/store/y8v9k1mjr73ns140bfzfyf3sm5avh4gc-openssl-1.1.1m         4.0M
/nix/store/ymr28y3gfbjp25cwn7nqihbciasxxgna-libunistring-0.9.10    1.6M
```

I notice that this was fixed for the cross-compiling case in https://github.com/NixOS/nixpkgs/pull/115911. But what about the non cross-compiling case when using something like `nodejs-slim`?

There's an [assert](https://github.com/NixOS/nixpkgs/blob/c1d77e4dd1c05cfd7efe6b0ecff001514e48c867/pkgs/development/libraries/openssl/default.nix#L12) keeping you from overriding the `withPerl` arg that was added. I'd suggest this assert should be removed to use with things like `nodejs-slim` where you know you don't need `c_rehash`.

**Comment by YoshiRulz** [comment]
From [Arch Linux bug #54887](https://bugs.archlinux.org/task/54887#comment194294):
> We could probably just either
> - make Perl an optdepends "for the c_rehash script"
> - replace the c_rehash script with a tiny shell script that invokes `openssl rehash "$@"`
>
> The latter relies on the fact that openssl-rehash is an identical, modern built-in C implementation of c_rehash.pl

Arch now lists `perl` as an optional dependency for `openssl`. But I like the other suggestion better: just drop Perl. You don't lose any functionality and, unlike with Arch, you don't need to worry about breaking anyone's workflow.

**Comment by adrian-gierakowski** [comment]
> > replace the c_rehash script with a tiny shell script that invokes `openssl rehash "$@"`
> 
> Sounds amazing, want to make the PR?

might be relevant: https://github.com/vmware/photon/commit/875d985717579e0042e356cf59bd9d9190b36200#diff-d65f4e155b4acda25e9e4c7c87be1ee83a6537666e3a0f1c52a8bdbef2f0d507R8
