### ISSUE TITLE
Some systemd timers don't start until systemd restart

### ISSUE THREAD

**Issue by figsoda** [NixOS/nixpkgs#199708]
### Describe the bug

I have set `autoUpgrade.dates = "04:00"`, and also set `WakeSystem` to be true, but my laptop wakes up from suspend at 04:00, does nothing, and goes back to sleep ([journal](https://paste.rs/eOB)). I have overwritten its `script`, but the same thing happens for nix-gc so I doubt that's the cause. The timer doesn't fire even when I turn on my machine, it only fires when I run 'nixos-rebuild/switch-to-configuration switch', which reloads systemd services, I tried omitting `WakeSystem` and/or setting `persistent` to `false`, also rebooted my system several times, none of which fixed the issue.

Here is my config: [nix-gc](https://github.com/figsoda/dotfiles/blob/55cbfcf0951de2b17d5606674e41ee5615e225f2/lib/nix.nix#L7-L11) [nixos-upgrade](https://github.com/figsoda/dotfiles/blob/55cbfcf0951de2b17d5606674e41ee5615e225f2/lib/misc.nix#L85-L88)  [systemd](https://github.com/figsoda/dotfiles/blob/55cbfcf0951de2b17d5606674e41ee5615e225f2/lib/services.nix#L56-L70). I don't know if bug is specific to my config.

This is the last auto upgrade that worked: https://github.com/figsoda/dotfiles/commit/a1b0df36811ddaf3195da7d6b208a9741bebc8bc, I skimmed through the nixpkgs diff (https://github.com/nixos/nixpkgs/compare/32096899af23d49010bd8cf6a91695888d9d9e73...db25c4da285c5989b39e4ce13dea651a88b7a9d4) but nothing in particular caught my eye. It could also because I have rebooted my machine after this commit and some things have changed, so the issue could have been introduced before 32096899af23d49010bd8cf6a91695888d9d9e73.

All my other systemd timers (fstrim, logrotate, and systemd-tmpfiles-clean) seems to be working fine atm, so It might be because of some incompatibility between the specific modules (system.autoUpgrade and nix.gc.automatic) and systemd

### Expected behavior
nixos-upgrade.timer to fire at 04:00 and upgrade my system

### Additional Context
I am using ROG Zephryus G14 with the nixos-hardware module 

### Notify maintainers
@NixOS/systemd 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6, NixOS, 22.11 (Raccoon), 22.11.20221103.a2a7775`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/brqf6qdrsq5s3k0siv47wbgrgz1i9dxz-source`
```

**Comment by flokli** [comment]
> All my other systemd timers (fstrim, logrotate, and systemd-tmpfiles-clean) seems to be working fine atm, so It might be because of some incompatibility between the specific modules (system.autoUpgrade and nix.gc.automatic) and systemd

I'm not entirely sure I understand what's the problem here. Some timers wake up your system when suspended, but then don't run, and some do? Or in general, you didn't see any timer recently run properly after being woken up by suspend?

If it's only some timers, I'd probably propose carefully inspecting the timer definitions, see if you can spot any difference.

**Comment by figsoda** [comment]
nix-gc and nixos-upgrade doesnt run until I do a nixos-rebuild, WakeSystem wakes up the system at the specified time even though the timer doesn't trigger. There could be something wrong with their definitions, but I haven't changed my config and they used to be working before the commit I mentioned.

**Comment by flokli** [comment]
Can you check if this is https://github.com/NixOS/nixpkgs/pull/199618#issuecomment-1310224853, and if the backport fixed it for you as well?

**Comment by figsoda** [comment]
I have 100 packages to build, since it's in master already, I will just wait for it to get into nixos-upgrade and see if that fixes the issue

**Comment by figsoda** [comment]
seems to be working now
