### ISSUE TITLE
Packaging request: ALIRE, Ada LIbrary REpository

### ISSUE THREAD

**Issue by coolshaurya** [NixOS/nixpkgs#199825]
**Project description**

A catalog of ready-to-use [Ada](https://en.wikipedia.org/wiki/Ada_(programming_language))/[SPARK](https://en.wikipedia.org/wiki/SPARK_(programming_language)) libraries plus a command-line tool (alr) to obtain, build, and incorporate them into your own projects. It aims to fulfill a similar role to Rust’s cargo or OCaml’s opam.

**Metadata**

* homepage URL: https://alire.ada.dev/
* source URL: https://github.com/alire-project/alire
* license: GPL 3.0
* platforms: Linux, MacOS

**Comment by steve-chavez** [comment]
Closing as this was completed on https://github.com/NixOS/nixpkgs/pull/244743
