### ISSUE TITLE
Remove hbase 1.7

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#199935]
Apache HBase 1.7 EOL was in 2022/08, can we remove it?

via https://endoflife.date/hbase

@illustris

**Comment by illustris** [comment]
Hey. Thanks for reminding me. I have a WIP PR for this:
https://github.com/NixOS/nixpkgs/pull/193740
I'm not sure why I left it as a draft... I'll go over it again and open it if it's ready.
