### ISSUE TITLE
File-roller extracts an empty file from apk

### ISSUE THREAD

**Issue by linsui** [NixOS/nixpkgs#199992]
### Describe the bug
Test file.
[EarthViewForMuzei-2.1.zip](https://github.com/NixOS/nixpkgs/files/9949492/EarthViewForMuzei-2.1.zip)
When open and extract it with file-roller, an empty file with the same name will be extracted, i.e. `EarthViewForMuzei-2.1`. This file does not exist in the apk and I can't see that with unzip and bsdtar.

### Notify maintainers

@jtojnar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by jtojnar** [comment]
What version are you running? I am unable to reproduce with 43.0, with neither `unzip` on `PATH` or not. Do you have some other compression CLI programs installed (`_7zz`, …)?

**Comment by linsui** [comment]
Good catch! I guess 7zz is used automatically. Sadly, without 7zz I'll suffer from https://github.com/NixOS/nixpkgs/issues/166241... Thanks for your help!

**Comment by jtojnar** [comment]
I cannot reproduce with `7zz` on `PATH` either. Are you sure it works if you uninstall 7zz, or mask the path?

```
env PATH= "$(type -p file-roller)"
```

**Comment by linsui** [comment]
Yes. After I uninstall 7zz the dummy empty file disappeared. I can also reproduce the problem with `7zz l`.

**Comment by jtojnar** [comment]
Weird, it works for me:

```ShellSession
$ result/bin/7zz l /tmp/mozilla_jtojnar0/EarthViewForMuzei-2.1.zip

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
 64-bit locale=en_GB.UTF-8 Threads:8, ASM

Scanning the drive for archives:
1 file, 854093 bytes (835 KiB)  

Listing archive: /tmp/mozilla_jtojnar0/EarthViewForMuzei-2.1.zip

--
Path = /tmp/mozilla_jtojnar0/EarthViewForMuzei-2.1.zip
Type = zip
Physical Size = 854093

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-11-06 13:56:44 .....      1113224       853865  EarthViewForMuzei-2.1.apk
------------------- ----- ------------ ------------  ------------------------
2022-11-06 13:56:44            1113224       853865  1 files
```

**Comment by jtojnar** [comment]
Ah, I see.

Maybe try opening an issue in https://sourceforge.net/p/sevenzip/bugs/

**Comment by linsui** [comment]
If I have a SF account I have done that...
