### ISSUE TITLE
hyprpicker (Wayland color picker)

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#199913]
**Project description**
A wlroots-compatible Wayland color picker that does not suck.

**Metadata**

* homepage URL: https://github.com/hyprwm/hyprpicker
* source URL: https://github.com/hyprwm/hyprpicker
* license: [BSD 3-clause "New" or "Revised" License](https://github.com/hyprwm/hyprpicker/blob/main/LICENSE)
* platforms: linux

Just because you made [hyprpaper](https://github.com/NixOS/nixpkgs/pull/180192) available on NixOS, I wanted to point you on hyprpicker, too - if you're interested to have a look into this(?)

@wozeparrot

**Comment by wozeparrot** [comment]
I'll take a look into packaging this.
