### ISSUE TITLE
Bumblebee gives an error on ThinkPad - DRM interface version 1.4: Permission denied

### ISSUE THREAD

**Issue by KibaFox** [NixOS/nixpkgs#20009]
## Issue description

With bumblebee enabled, and trying to run `optirun glxgears` or `optirun -vv nvidia-settings`, I get the following error:

```
/dev/dri/card0: failed to set DRM interface version 1.4: Permission denied
```

Here's the exact output I get from _glxgears_:

```
$ optirun glxgears
[27399.443626] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[27399.443651] [ERROR]Aborting because fallback start is disabled.
```

And here's the exact output I get from _nvidia-settings_:

```
 $ optirun -vv nvidia-settings
[27263.604447] [DEBUG]Reading file: /nix/store/4kzhdhbcs0cy0g9gvgjsmlswp86ydylb-bumblebee-3.2.1/etc/bumblebee/bumblebee.conf
[27263.604617] [DEBUG]optirun version 3.2.1 starting...
[27263.604622] [DEBUG]Active configuration:
[27263.604624] [DEBUG] bumblebeed config file: /nix/store/4kzhdhbcs0cy0g9gvgjsmlswp86ydylb-bumblebee-3.2.1/etc/bumblebee/bumblebee.conf
[27263.604625] [DEBUG] X display: :8
[27263.604627] [DEBUG] LD_LIBRARY_PATH: /nix/store/l5rpp0k4l2npcxkd461s0i3dnfsvq8w5-nvidia-x11-367.35-4.4.24/lib:/nix/store/ywk3jz6j7yz404hcyc42nx4v8xl5cch3-nvidia-x11-367.35/lib
[27263.604629] [DEBUG] Socket path: /var/run/bumblebee.socket
[27263.604630] [DEBUG] Accel/display bridge: auto
[27263.604640] [DEBUG] VGL Compression: proxy
[27263.604642] [DEBUG] VGLrun extra options:
[27263.604644] [DEBUG] Primus LD Path: /usr/lib/primus:/usr/lib32/primus
[27263.604658] [DEBUG]Using auto-detected bridge virtualgl
[27263.835471] [INFO]Response: No - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[27263.835487] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) /dev/dri/card0: failed to set DRM interface version 1.4: Permission denied

[27263.835492] [DEBUG]Socket closed.
[27263.835502] [ERROR]Aborting because fallback start is disabled.
[27263.835507] [DEBUG]Killing all remaining processes.
```
### Steps to reproduce

I'm producing this on my ThinkPad T530.  It has an NVIDIA NVS 5400M with Optimus support.  I added the following to my configuration:

```
hardware.bumblebee.enable = true;
hardware.bumblebee.connectDisplay = true;
```

After finding an article on the Arch Wiki on troubleshooting Bumblebee I followed [the suggestion on resolving this issue](https://wiki.archlinux.org/index.php/bumblebee#.2Fdev.2Fdri.2Fcard0:_failed_to_set_DRM_interface_version_1.4:_Permission_denied), and I tried adding the following to my configuration:

```
  services.xserver.config = ''
    Section "Screen"
      Identifier "Default Screen"
      Device "DiscreteNvidia"
    EndSection
  '';
```

However, this did not fix the issue.  It might be because this doesn't change `/etc/bumblebee/xorg.conf.nvidia` (or equivalent in NixOS).

You can find my exact configuration here: [nixos/hardware/thinkpad_t530.nix](https://github.com/KibaFox/nixos/blob/7dbfecc0d1d26db3989fca9319120948f3cd56b5/hardware/thinkpad_t530.nix#L43-L55)
## Technical details
- System: NixOS: 16.09.733.246c937 (Flounder)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 16.09.733.246c937
- Hardware: ThinkPad T530 Type 2429AW8 w/ NVIDIA NVS 5400M

**Comment by gnidorah** [comment]
Does this help?
Add the following to your `/etc/nixos/configuration.nix` under `nixpkgs.config` section:
```nix
packageOverrides = pkgs: rec {
  bumblebee = pkgs.bumblebee.override {
    extraNvidiaDeviceOptions = ''
EndSection # close option section
Section "Screen"
  Identifier "Default Screen"
  Device "DiscreteNvidia"
    '';
  };
};
```
Do `nixos-rebuild switch`. Check if your `xorg.conf.nvidia` is correct:
```bash
cat $(dirname $(readlink -f $(which bumblebeed)))/../etc/bumblebee/xorg.conf.nvidia
```

**Comment by KibaFox** [comment]
Thank you, @gnidorah!  I've been excited to give this a try once I got home from work.

Sadly, it did not work.  I still have the issue when I try to run `optirun glxgears`.

I was able to verify that the `xorg.conf.nvidia` was correct:

```
$ cat $(dirname $(readlink -f $(which bumblebeed)))/../etc/bumblebee/xorg.conf.nvidia                                                                                                 
Section "ServerLayout"
    Identifier  "Layout0"
    Option      "AutoAddDevices" "false"
    Option      "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier  "DiscreteNvidia"
    Driver      "nvidia"
    VendorName  "NVIDIA Corporation"

#   If the X server does not automatically detect your VGA device,
#   you can manually set it here.
#   To get the BusID prop, run `lspci | egrep 'VGA|3D'` and input the data
#   as you see in the commented example.
#   This Setting may be needed in some platforms with more than one
#   nvidia card, which may confuse the proprietary driver (e.g.,
#   trying to take ownership of the wrong device). Also needed on Ubuntu 13.04.
#   BusID "PCI:01:00:0"

#   Setting ProbeAllGpus to false prevents the new proprietary driver
#   instance spawned to try to control the integrated graphics card,
#   which is already being managed outside bumblebee.
#   This option doesn't hurt and it is required on platforms running
#   more than one nvidia graphics card with the proprietary driver.
#   (E.g. Macbook Pro pre-2010 with nVidia 9400M + 9600M GT).
#   If this option is not set, the new Xorg may blacken the screen and
#   render it unusable (unless you have some way to run killall Xorg).
    Option "ProbeAllGpus" "false"

    Option "NoLogo" "true"

EndSection # close option section

Section "Screen"
  Identifier "Default Screen"
  Device "DiscreteNvidia"

# our section is closed later

EndSection
```

**Comment by KibaFox** [comment]
I was able to verify that the hardware is working.  I disabled all the Bumblebee configuration and added the following to my NixOS configuration:

```
services.xserver.videoDrivers = [ "nvidia" ];
```

After a `nixos-rebuild switch` and a reboot, X would not start, so I went into my BIOS and changed my display settings from Optimus to Discrete.  After that, X was able to start.  I connected a monitor to the display port and used `xrandr` to get my display working on the extra monitor.

So, it doesn't look like a hardware issue.  I'd prefer not to have to keep my laptop in Discrete settings and keep my Nvidia graphics card on all the time, this uses extra battery power and makes my machine hot.

My goal is to be able to attach an external monitor to my laptop, which requires using the Nvidia graphics card.  I'd also like my laptop to be portable and I'd prefer to not have to keep switching it back between Discrete and Integrated manually (especially since I'll have to change my NixOS configuration too).  Optimus could prevent me from having to do that, but this Bumblebee issue has me stumped.

**Comment by gnidorah** [comment]
Sadly Bumblebee errors are not informative. Seen a lot of bug reports in Bumblebee tracker with all similar errors but different issues underneath. For example I have `/dev/dri/card0: failed to set DRM interface version 1.4: Permission denied` too, but only in `systemctl status bumblebeed` output and Bumblebee works fine here. These reports usually have Xorg log though, dunno where it is on NixOS (the [only hint](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/xserver.nix#L554) I see), and that probably would be useful to debug issues.

Do optirun and primusrun at least work using internal display? So no `hardware.bumblebee.connectDisplay = true` and external monitor connected. 

Found articles on using Bumblebee with external monitor on your hardware like [this one](http://www.unixreich.com/blog/2013/linux-nvidia-optimus-on-thinkpad-w520w530-with-external-monitor-finally-solved/) and there is some trickery involved. There is more actual [russian writeup](https://translate.google.ru/translate?sl=ru&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fhtrd.su%2Fwiki%2Fzhurnal%2F2014%2F11%2F13%2Flinux_thinkpad_t530_i_minidp_displayport&edit-text= ) from it, but exactly about your laptop, which states that at least you should have `intel-virtual-output` binary installed (cast @paraseba ).

P.S.: https://github.com/Bumblebee-Project/Bumblebee/wiki/Multi-monitor-setup

**Comment by Profpatsch** [comment]
(triage) were you able to fix this?

**Comment by KibaFox** [comment]
Unfortunately, no.  I had to give up on this.
