### ISSUE TITLE
VirtualBox appliance does not boot to KDE login

### ISSUE THREAD

**Issue by fleimgruber** [NixOS/nixpkgs#20007]
## Issue description

Using the official VirtualBox `.ova` from [here](https://d3g5gsiof5omrk.cloudfront.net/nixos/16.09/nixos-16.09.877.5b08a40/nixos-16.09.877.5b08a40-x86_64-linux.ova), no KDE login appears, contrary to the description following it ("... When the KDE login screen appears ...").
### Steps to reproduce

Download, install and start `.ova` as described on http://nixos.org/nixos/download.html.
## Technical details
- VirtualBox 5.0.28

`journalctl` log http://pastebin.com/eG3EFVxX.

**Comment by matthewbauer** [comment]
I believe this is from #16641 being broken again.
