### ISSUE TITLE
utsushi-networkscan no longer builds

### ISSUE THREAD

**Issue by felipeqq2** [NixOS/nixpkgs#200060]
### Steps To Reproduce
1. Try to build *utsushi-networkscan*
2. Download URL https://download2.ebz.epson.net/imagescanv3/fedora/latest1/rpm/x64/imagescan-bundle-fedora-32-3.65.0.x64.rpm.tar.gz is no longer valid (returns 404)

### Build log
```
trying https://download2.ebz.epson.net/imagescanv3/fedora/latest1/rpm/x64/imagescan-bundle-fedora-32-3.65.0.x64.rpm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0    10    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download imagescan-bundle-fedora-32-3.65.0.x64.rpm.tar.gz from any mirror
```

### Additional context
AUR is facing the [same issue](https://aur.archlinux.org/packages/imagescan-plugin-networkscan#comment-888563). I guess that updating the package is enough to get a valid URL and fix the issue, but I couldn't find anything about an update.

### Notify maintainers
@abbradar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.76, NixOS, 22.11 (Raccoon), 22.11.20221105.3bacde6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Artturin** [comment]
from the aur

> It seams that Epson has abandoned this software. I have changed the package to download from a mirror hosted by me.

https://buzo.eu/mirror/epson/imagescan-bundle-fedora-32-3.65.0.x64.rpm.tar.gz

**Comment by felipeqq2** [comment]
Is there any Nixpkgs policy regarding third-party mirrors in cases like this? I'm not sure if we should rely on it, or use some other mechanism (maybe even remove the package, since it's no longer supported).

**Comment by Artturin** [comment]
> Is there any Nixpkgs policy regarding third-party mirrors in cases like this? I'm not sure if we should rely on it,

In this case we should be able to verify that the file is the same one as before because it's the same version and we have the hash. The file won't ever be updated so no need to worry about that

> use some other mechanism 

Normally we'd use the internet archive if it's available there , but it's slow

(Archived it https://web.archive.org/web/20230405232854/https://buzo.eu/mirror/epson/imagescan-bundle-fedora-32-3.65.0.x64.rpm.tar.gz)


> (maybe even remove the package, since it's no longer supported).

I think it's good to keep it if there's no replacement or the replacement doesn't support older hardware

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/225019
