### ISSUE TITLE
zoom-us: crash on meeting start

### ISSUE THREAD

**Issue by ryanartecona** [NixOS/nixpkgs#20008]
## Issue description

Using the zoom-us package, the zoom client starts up and most screens seem to work. However, when I go to actually start a meeting, video from my webcam never shows in the window, and after a few seconds, the whole zoom client crashes. If started from a shell, I get this output (last few lines printed upon crash).

<details><summary>zoom-us crash output</summary>
```
AppIconMgr::systemDesktopName log Desktop Name: none + i3 
pmap: argument missing
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: D0:17:C2:D1:B2:5D][client: Linux][OS: NixOS 16.09.773.b8ede35 (Flounder)][Hardware: CPU Core:4 Frenquency:3.4 G Memory size:15993MB CPU Brand:Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz][Req ID: ]
Linux Client Version is 2.0.52458.0531
Graphics Card Info:: 01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 760](rev a1)
QSG_RENDER_LOOP is 
Fontconfig warning: line 146: blank doesn't take any effect anymore. please remove it from your fonts.conf
pmap: argument missing
pmap: argument missing
pmap: argument missing
ALSA lib pcm_dsnoop.c:654:(snd_pcm_dsnoop_open) unable to open slave
pmap: argument missing
error was 0
pmap: argument missing
pmap: argument missing
pmap: argument missing
pmap: argument missing
pmap: argument missing
QSocketNotifier: Can only be used with threads started with QThread
QSocketNotifier: Can only be used with threads started with QThread
CSBConfUI::OnConfStatusChanged  cmd:59, ret:0
CSBConfUI::OnConfStatusChanged  cmd:23, ret:0
CSBConfUI::OnConfStatusChanged  cmd:27, ret:1
CSBConfUI::OnConfStatusChanged  cmd:28, ret:1
CSBConfUI::OnConfStatusChanged  cmd:25, ret:0
CSBConfUI::OnConfStatusChanged  cmd:71, ret:0
CSBConfUI::OnConfStatusChanged  cmd:79, ret:0
CSBConfUI::OnConfStatusChanged  cmd:9, ret:1
CSBConfUI::OnConfStatusChanged  cmd:59, ret:0
CSBConfUI::OnConfStatusChanged  cmd:23, ret:0
CSBConfUI::OnConfStatusChanged  cmd:27, ret:1
CSBConfUI::OnConfStatusChanged  cmd:28, ret:1
CSBConfUI::OnConfStatusChanged  cmd:25, ret:0
CSBConfUI::OnConfStatusChanged  cmd:71, ret:0
CSBConfUI::OnConfStatusChanged  cmd:79, ret:0
CSBConfUI::OnConfStatusChanged  cmd:9, ret:1
CSBConfUI::OnConfStatusChanged  cmd:73, ret:0
CSBConfUI::OnConfStatusChanged  cmd:6, ret:0
CSBConfUI::OnConfStatusChanged  cmd:8, ret:0
CSBConfUI::OnConfStatusChanged  cmd:7, ret:0
zoom-us: pcm.c:2828: snd_pcm_area_copy: Assertion `src < dst || src >= dst + bytes' failed.
fish: “zoom-us” terminated by signal SIGABRT (Abort)
```
</details>

I can't tell if this is just a weird issue with my webcam, the zoom package, something else, or what. I'm a little at a loss for debugging on my own, so any ideas would be helpful.

I'd love to get this fixed, though, since it's the last major obstacle keeping me from switching from macOS to NixOS for daily work.

cc @k0001
### Steps to reproduce

``` bash
nix-env -iA nixpkgs.zoom-us
zoom-us
# log in
# start a meeting
```
## Technical details
- System: 16.09.773.b8ede35 (Flounder)
- Nix version: nix-env (Nix) 1.11.4
- Nixpkgs version: 16.09.773.b8ede35

**Comment by NeQuissimus** [comment]
The guys at Zoom have recently changed a few things in their backend from what I have heard. I wonder if a package update will fix the issue.

**Comment by NeQuissimus** [comment]
Can you attach the log output you mentioned?
I am building this overnight, it's late here. PR should come in tomorrow.

**Comment by ryanartecona** [comment]
@NeQuissimus Ah, ok. I had goofed the formatting in the issue description. You should be able to see the log output there now.

The app seems to behave normally until this line.

```
zoom-us: pcm.c:2828: snd_pcm_area_copy: Assertion `src < dst || src >= dst + bytes' failed.
```

After some googling, this appears to be an issue with the alsa lib: there's an alsa-devel thread about this bug starting [here](http://mailman.alsa-project.org/pipermail/alsa-devel/2016-June/thread.html#108915). 

There's also a small mention of the same bug on the page for Arch's zoom [here](https://aur.archlinux.org/packages/zoom/?comments=all) (scroll down the comment "pmig commented on 2016-05-02 14:51"), in which the user says "installing pulseaudio" made the issue go away. I guess I'll try that next, but I'm not super hopeful.

**Comment by NeQuissimus** [comment]
hmm, so updating zoom is not as easy as I had thought. I know nothing about Qt, so I am not sure what to do about it. Hopefully, somebody else can jump in.

One thing I found is that the URL needs to be changed to `https://d11yldzmag5yn.cloudfront.net/prod/2.0.70790.1031/zoom_x86_64.tar.xz`.

**Comment by ryanartecona** [comment]
Yeah, I think that's been identified elsewhere: #17524

**Comment by bdimcheff** [comment]
The new zoom #20992 works fine for me except for video (though the old one did too for audio only).  Are you still unable to join a meeting at all?

**Comment by ryanartecona** [comment]
@bdimcheff Thanks for the heads up, I hadn't noticed zoom got updated.

Looks like I'm in the same boat now. The new zoom works for me except for video, so at least it no longer crashes at the start of a meeting.

Trying to figure out the remaining problem, it looks like it doesn't get the video feed from my webcam. I have a Logitech C310, and it seems to work everywhere but in zoom, including guvcview, chromium, and firefox. In zoom, once I start a meeting, the zoom seems to find my webcam and the webcam light comes on, but I don't get any video on my screen. Recording just gives me a black frame too. Audio seems to work fine. Is that what you're seeing? If this isn't just me, I can open a separate ticket and maybe reach out to zoom support.

**Comment by ryanartecona** [comment]
Also pinging @savannidgerinel, since googling around found me [these #nixos chat logs](https://botbot.me/freenode/nixos/2016-12-06/?msg=77572777&page=11) that sound like you may also have the same problem with zoom.

**Comment by bdimcheff** [comment]
@ryanartecona exactly the same issue for me.  Camera light comes on, but just black video feed.  I think it's capturing video via the embedded webkit, so perhaps that's what's broken.

**Comment by savannidgerinel** [comment]
I'm sorry for being so late no this.

I got zoom to the point that it doesn't crash on startup, and put that change into the nixpkgs master branch. However, my camera does not appear to capture video, either. The camera light is turned on, but I just get a blank screen where my video feed should be. Sound from the camera's built-in mic, video from other users, and even screensharing all seems to work.

**Comment by tdroxler** [comment]
Same problem as above, everything's fine except for the video (Camera light on but no video).

**Comment by bdimcheff** [comment]
fwiw i gave up on this and i'm just using the chrome app for zoom, which works with video

**Comment by savannidgerinel** [comment]
Where is the Chrome app? When I go to Zoom's website from Chrome, I can only find the thing that launches the standalone app.

**Comment by ryanartecona** [comment]
Looks like it's here: https://chrome.google.com/webstore/detail/zoom/hmbjbjdpkobdjplfobhljndfdfdipjhg?hl=en-US

I also had no idea this thing existed! It looks like it doesn't have some of the settings and meeting scheduling functionality the standalone app does, but if it can get me through a meeting, that's probably good enough for me now too. Thanks for the note @bdimcheff .

**Comment by ryanartecona** [comment]
Looks like the zoom package has been removed anyway (https://github.com/NixOS/nixpkgs/commits/master/pkgs/applications/networking/instant-messengers/zoom-us), so I'll just close this out unless anyone else still wants this specific issue resolved.

**Comment by danbst** [comment]
Let's try again https://github.com/NixOS/nixpkgs/pull/26446
