### ISSUE TITLE
ncdu-2.1.2: build failure on aarch64-darwin, curses.h not found

### ISSUE THREAD

**Issue by osnyx** [NixOS/nixpkgs#200273]
### Steps To Reproduce
1. build `ncdu` from nixpkgs-unstable
2. see the build failure `./zig-cache/o/d0a8ac215165bb11af5e7ef562aa759c/cimport.h:1:10: note: 'locale.h' file not found`

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/i4bmvx3d5ihihz0lp1c2hx2qg6wc70n2-ncdu-2.1.2.tar.gz
source root is ncdu-2.1.2
setting SOURCE_DATE_EPOCH to timestamp 1651137660 of file ncdu-2.1.2/ncdu.1
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: SHELL=/nix/store/kv4p5wk0q5h77fr2f8cbwrdlacffha7p-bash-5.1-p16/bin/bash
zig build -Drelease-safe -Dcpu=baseline
Semantic Analysis [368/983] Semantic Analysis [712/1305] Semantic Analysis [875/1562] Semantic Analysis [979/1666] Semantic Analysis [979/1666] Semantic Analysis [1250/1900] Semantic Analysis [1661/2350] Semantic Analysis [2124/2677] Code Generation [460/2137] std.dwarf.DwarfInfo.scanAllFunctions... Code Generation [1703/2137] std.array_list.ArrayListAligned([]const u8,null).app... LLVM Emit Object... LLVM Emit Object... warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -iframework
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: /nix/store/k5jgin0ppbc2w5mwds67pzx2m68zvm5h-apple-framework-CoreFoundation-11.0.0/Library/Frameworks
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -iframework
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: /nix/store/k5jgin0ppbc2w5mwds67pzx2m68zvm5h-apple-framework-CoreFoundation-11.0.0/Library/Frameworks
error(compilation): clang failed with stderr: /private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/src/ncurses_refs.c:5:10: fatal error: 'curses.h' file not found

./src/main.zig:13:11: error: C import failed
const c = @cImport(@cInclude("locale.h"));
          ^
./zig-cache/o/d0a8ac215165bb11af5e7ef562aa759c/cimport.h:1:10: note: 'locale.h' file not found
#include <locale.h>
         ^
ncdu...The following command exited with error code 1:
/nix/store/7j2dckwf5c99y5d5pxjj6mg4ri0vk44a-zig-0.9.1/bin/zig build-exe /private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/src/main.zig /private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/src/ncurses_refs.
c -lc -lncursesw -OReleaseSafe --cache-dir /private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/zig-cache --global-cache-dir /private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/Cache/zig --name ncdu -target
native-native -mcpu generic --enable-cache
error: the following build command failed with exit code 1:
/private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/zig-cache/o/05c56e55efc4aa462aac6124ed68e0d7/build /nix/store/7j2dckwf5c99y5d5pxjj6mg4ri0vk44a-zig-0.9.1/bin/zig /private/tmp/nix-build-ncdu-2.1.2.drv-0/
ncdu-2.1.2 /private/tmp/nix-build-ncdu-2.1.2.drv-0/ncdu-2.1.2/zig-cache Cache/zig -Drelease-safe -Dcpu=baseline
make: *** [Makefile:15: release] Error 1
```

### Additional context

built from nixpkgs revision bc5ad970780580ec272b3a6bc5f9bddf4e250d3c

### Notify maintainers

@SuperSandro2000 @pSub 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixpkgs"`
 - channels(os): `"NUR, darwin, home-manager, nixpkgs"`
 - nixpkgs: `/Users/os/.nix-defexpr/channels/nixpkgs`
```

**Comment by wegank** [comment]
Zig also seems to be [broken on nixpkgs-unstable](https://hydra.nixos.org/job/nixpkgs/nixpkgs-unstable-aarch64-darwin/zig.aarch64-darwin). Is this only the case for macOS 13?

**Comment by osnyx** [comment]
At least on macOS 12, zig is still building fine for me. It is only the ncdu build which is failing then. But yeah, it is not in the binary cache and I had to build it locally myself.

Currently trying to bisect the failure, because ncdu-2.1.2 had already been built succesfully once.

**Comment by osnyx** [comment]
Superficially, this looks related to https://github.com/ziglang/zig/issues/11631

**Comment by SuperSandro2000** [comment]
I'll let people with Macs figure this out. If you have a solution I would review it.

**Comment by osnyx** [comment]
I bisected the build failure down to a bunch of commits:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 7419a3a676e4e2deae7142297b7bb4d3bf362efd
> 05169bd4e41e715dd1ed6351b796f9820c896355
> 3dbb5dfa2971870e5095cb86f8c935d11ec34014
> 0856bf8144233a1209a3069179ce79d5e9f70781
> 9a71828f00f06e46a401ad4f4e8785cab04a75ca
> 3f3f318a6ba69e7d1453b02a5ed0c8ea1828c9ba
> 60abfb419a9ee58aa71bf28ce96735c843a0be10
> 1ea4a3bab629f62ce28730c41a415076bd8c99f0
> b409fdd3ce85d2759a2bb3f383b22f6d03bed248
> e1656e231c8352c56d8e78e916700ef98026a4c7
> e61c4306f1ab9ac61f38781d4241bbbb33a216bd
> 16a848885ebc8bdb02f0816df7c7d09d0457364a
> 6b836517dba469b8aea63c7317cd1ad3e4ae32f2
> 14adc91759c0566ae6be8c659c7c708a706cdf7e
> 1c93ab362bc9c2a9275d7d2dd0a6268be86e495a
> 2be1bcb3d2291d406a280d38860e42706e5bcf76
> 556884e3659bf284a6c223f005af0cb5e0095067
> 0f64ae72eae13bff1d1d5d8b50ea6932c172a1ef
> d65d8002c7fbca2144fce2480a65bec36768da9a
> 0b151fbe0388f03405acfb3b55bb30db12434675
> 37ae722e8867ca49569c7e99587e898a7487942d
> bb97e96c23a8831b765e8c7d1f2a8d6709394414
> f035fcf4f3f7d69191263e8e15afa468a0773ef9
> 49bdf1e727796e5dfdbb600614f7e01c90035878
> 8db2124b57ce5e577ee931fb0595488806ac5155
> 9a68f7419baa788f1475319a4070437bc97d0356
> c625d6771fb514693ff4c94a7ab7453d76b27b7f
> 2634e6bf6c08f1fc40e58615808f8f7f3ec55e7f
> 6a378e9c44064628234a1c783504f5a1ea833e11
> fef040afae46c0471820ecfd0b3657b52096f167
> We cannot bisect more!

The build of ncdu first fails at 6a378e9c44064628234a1c783504f5a1ea833e11, but transitively with a different reason: binutils-2.39 fails to build as a dependency. As a consequence, I told git bisect to skip all these commits where binutils does not build.
This binutils issue is fixed in fef040afae46c0471820ecfd0b3657b52096f167, but afterwards ncdu itself fails to build as described above.
Maybe @trofi as the author of these two commit might have an idea what's going on there?

**Comment by trofi** [comment]
https://github.com/NixOS/nixpkgs/commit/6a378e9c44064628234a1c783504f5a1ea833e11 `binutils: 2.38 -> 2.39` update looks most plausible breakage, but unfortunately from your build log it's not clear at all how binutils is implicated in headers search.

Looking at `master` hydra it looks like `ncdu` does not fail on at least `ncdu.x86_64-darwin` https://hydra.nixos.org/eval/1785148?filter=ncdu&compare=1785130&full=#tabs-still-fail

Looking at `staging-next` (has `aarch64-darwin`): `ncdu` builds successfully there as well: https://hydra.nixos.org/eval/1785128?filter=ncdu&compare=1785087&full=#tabs-still-fail

Does `stagind-next` build fail for you as well?  Should be a matter of running `$ nix build github:NixOS/nixpkgs/staging-next#ncdu` (or equivalent) to test.

Do you know what is different from your setup and hydra? Which `nixpkgs` commit do you run?

Raw logs are not very verbose: https://hydra.nixos.org/log/cmmlhndki9702fghh3x363zwpx706ws4-ncdu-2.1.2.drv. Try adding a bit of verbosity to `zig` to get something material out of it (maybe $CC execution?).

**Comment by osnyx** [comment]
I'll update my device to macOS 13 tonight, currently it's still running 12.x. I don't know whether our Hydra darwin builders already use macOS 13 as a base and whether that makes a difference.

I am running from nixpkgs commit bc5ad970780580ec272b3a6bc5f9bddf4e250d3c.

**Comment by osnyx** [comment]
But I can already confirm that ncdu from staging-next (f3a93620b183a16fbfdba1675a717f3c74b12328) builds and runs successfully.
So I gues whatever caused the build failure is already resolved and will reach the master branch soon. Sorry about the fuss then.

**Comment by dbaynard** [comment]
> Which `nixpkgs` commit do you run?

For me it was 093268502280540a7f5bf1e2a6330a598ba3b7d0 — glad this is working, now.

**Comment by knl** [comment]
I'm seeing this error on x86_64-darwin for `staging-next` (eb29401d):

```
this derivation will be built:
  /nix/store/1m33y2hrci4pr76vb8y6avjvp21g059f-ncdu-2.2.1.drv
building '/nix/store/1m33y2hrci4pr76vb8y6avjvp21g059f-ncdu-2.2.1.drv'...
unpacking sources
unpacking source archive /nix/store/svq0069g9kf3vgkf4awjh02kbharhgsq-ncdu-2.2.1.tar.gz
source root is ncdu-2.2.1
setting SOURCE_DATE_EPOCH to timestamp 1666678440 of file ncdu-2.2.1/ncdu.1
patching sources
configuring
no configure script, doing nothing
building
build flags: SHELL=/nix/store/1bsjl5incfnszv7scdh4d02sh45vw2w1-bash-5.1-p16/bin/bash
zig build -Drelease-safe -Dcpu=baseline
LLVM Emit Object... Semantic Analysis... Semantic Analysis [66/148] Semantic Analysis [102/416] Semantic Analysis [275/734] Semantic Analysis [391/993] Semantic Analysis [543/1213] Semantic Analysis [712/1304] Semantic Analysis [712/1332] Semantic Analysis [712/1340] Semantic Analysis [800/1532] Semantic Analysis [934/1633] Semantic Analysis [935/1633] Semantic Analysis [977/1662] Semantic Analysis [982/1675] Semantic Analysis [982/1675] Semantic Analysis [982/1675] Semantic Analysis [982/1675] Semantic Analysis [1139/1815] Semantic Analysis [1261/1913] Semantic Analysis [1410/2086] Semantic Analysis [1612/2309] Semantic Analysis [1675/2364] Semantic Analysis [1801/2491] Semantic Analysis [1998/2616] Semantic Analysis [2140/2692] Code Generation [0/2146] Code Generation [410/2146] std.sort.sort... Code Generation [830/2146] std.mem.Allocator.reallocAdvancedWithRetAddr... Code Generation [1325/2146] std.hash_map.HashMapUnmanaged([]const u8,std.build.A... Code Generation [1753/2146] std.fmt.allocPrint... LLVM Emit Object... LLVM Emit Object... warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -iframework
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: /nix/store/zvr4wypbgskhhw9cawfn7mmxfa75nh8f-swift-corefoundation-unstable-2018-09-14/Library/Frameworks
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: -iframework
warning: Unrecognized C flag from NIX_CFLAGS_COMPILE: /nix/store/zvr4wypbgskhhw9cawfn7mmxfa75nh8f-swift-corefoundation-unstable-2018-09-14/Library/Frameworks
error(compilation): clang failed with stderr: /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/src/ncurses_refs.c:5:10: fatal error: 'curses.h' file not found

LLVM Emit Object... Semantic Analysis... Semantic Analysis [76/134] Semantic Analysis [79/477] Semantic Analysis [351/716] Semantic Analysis [612/883] ./src/main.zig:14:11: error: C import failed
const c = @cImport(@cInclude("locale.h"));
          ^
./zig-cache/o/356c67affaf769d60b57bfe8a19c5ea1/cimport.h:1:10: note: 'locale.h' file not found
#include <locale.h>
         ^
ncdu...The following command exited with error code 1:
/nix/store/cp0qiwlf7amjl2v65w631l8h0vl11s67-zig-0.9.1/bin/zig build-exe /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/src/main.zig /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/src/ncurses_refs.c -lc -lncursesw -OReleaseSafe --cache-dir /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/zig-cache --global-cache-dir /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/Cache/zig --name ncdu -target native-native -mcpu x86_64 --enable-cache
error: the following build command failed with exit code 1:
/private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/zig-cache/o/4d788ca669675035286d6f3818e58d66/build /nix/store/cp0qiwlf7amjl2v65w631l8h0vl11s67-zig-0.9.1/bin/zig /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1 /private/tmp/nix-build-ncdu-2.2.1.drv-0/ncdu-2.2.1/zig-cache Cache/zig -Drelease-safe -Dcpu=baseline
make: *** [Makefile:15: release] Error 1
error: builder for '/nix/store/1m33y2hrci4pr76vb8y6avjvp21g059f-ncdu-2.2.1.drv' failed with exit code 2
```

I'm not sure the issue is gone. Just to be precise, I'm seeing the same issue with the latest master, too.

**Comment by osnyx** [comment]
current master head 68bd364831a89859b40d67bf94618e6163486cae is building fine for me, so I still assume this to be fixed.
