### ISSUE TITLE
Mesos is broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#20033]
@grahamc recently marked Mesos as broken due to a security issue in one of its dependencies. I took a look at the expression to try to fix it and am unsure of how `fetch-mesos-deps.sh` was generated. Was the script generated by some sort maven dependency walker or something? It also looks like there's a couple of newer versions out that might obviate the need for some of the patches we have in place today. 

cc @cstrahan @kevincox @offlinehacker @rushmorem who are all marked as maintainers of the package

**Comment by kamilchm** [comment]
@copumpkin there's ongoing PR for Mesos update https://github.com/NixOS/nixpkgs/pull/19064

**Comment by cstrahan** [comment]
Also see https://github.com/NixOS/nixpkgs/pull/21416

**Comment by kevincox** [comment]
I'm closing this as mesos was fixed. It's currently broken on master but working on most branches.
