### ISSUE TITLE
lib.trivial.toHexString should only accept integers.

### ISSUE THREAD

**Issue by Quantenzitrone** [NixOS/nixpkgs#200384]
### Describe the bug
I encountered this when trying to convert floats to Hexadecimal with lib.strings.toHexString.
For example:
```sh
nix-repl> lib.toHexString (255.0)
error: attribute '15.937500' missing

       at /nix/store/9lqfkdbzfb019hw3b08r000xljjvvc84-nixos/nixos/lib/trivial.nix:485:11:

          484|         else
          485|           {
             |           ^
          486|             "10" = "A";
```
is a really weird error message and should just be caught with a small 
``` nix
if buildins.isInt i then 
   ... 
else abort "toHexString only accepts integers"
```
 or something similar

### Steps To Reproduce
- try it out in `nix repl`

### Expected behavior
Understandable error messages

### Notify maintainers

@basvandijk 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.3-zen2, NixOS, 22.11 (Raccoon), 22.11pre423979.3bacde6273b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(qz): `""`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Quantenzitrone** [comment]
i was actually aware of lib.toBaseDigits, but i wasn't sure, if it is able to handle floats because i dont understand how it does what it does

**Comment by wegank** [comment]
Given an integer, e.g. $255$, its first digit in base $16$ is determined by $\lfloor\frac{255}{16}\rfloor = 15$. In Nix, we do have `255 / 16 == 15`, but given a float, we will have `255.0 / 16 == 15.9375` instead. So, in the case of the issue, $255.0$ is incorrectly converted to `[ 15.9345 0 ]`, causing the error in the hex character conversion.
