### ISSUE TITLE
Ladybird: 2022-11-09

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#200495]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: unstable-2022-09-29
desired version: unstable-2022-11-09

###### Notify maintainers

maintainers: @fgaz 

###### Note for maintainers

I was looking to bump the version of this library with this diff:

```diff
diff --git a/pkgs/applications/networking/browsers/ladybird/default.nix b/pkgs/applications/networking/browsers/ladybird/default.nix
index 0bd3cc79df2..315a9eb92e5 100644
--- a/pkgs/applications/networking/browsers/ladybird/default.nix
+++ b/pkgs/applications/networking/browsers/ladybird/default.nix
@@ -1,5 +1,5 @@
 { lib
-, gcc11Stdenv
+, gcc12Stdenv
 , fetchFromGitHub
 , cmake
 , ninja
@@ -14,20 +14,20 @@
 let serenity = fetchFromGitHub {
   owner = "SerenityOS";
   repo = "serenity";
-  rev = "a0f3e2c9a2b82117aa7c1a3444ad0d31baa070d5";
-  hash = "sha256-8Xde59ZfdkTD39mYSv0lfFjBHFDWTUwfozE+Q9Yq6C8=";
+  rev = "a2a4ad3b9dfa77cce8d27872631ad3928f918306";
+  hash = "sha256-bYW4OKHjhMH13TMryRbD5/mH2CAzcmHJbPpbsJYMb+U=";
 };
 
-in gcc11Stdenv.mkDerivation {
+in gcc12Stdenv.mkDerivation {
   pname = "ladybird";
-  version = "unstable-2022-09-29";
+  version = "unstable-2022-11-09";
 
   # Remember to update `serenity` too!
   src = fetchFromGitHub {
     owner = "SerenityOS";
     repo = "ladybird";
-    rev = "d69ad7332477de33bfd1963026e057d55c6f222d";
-    hash = "sha256-XQj2Bohk8F6dGCAManOmmDP5b/SqEeZXZbLDYPfvi2E=";
+    rev = "f0f2dcef893655c8dd1dafcd87f6f509a5dd3bd9";
+    hash = "sha256-ublnC2INIIYa/GqG0nxj5r6jCxPn3UdkzJjQ+vQ9DsM=";
   };
 
   nativeBuildInputs = [
```

But I got some CMake errors. I know nothing of the C++ tooling, but it looks like LibLocaleData is missing from SerenityOS (perhaps [this line](https://github.com/SerenityOS/serenity/blob/6490529ef76ebf37f9e58bf76c6271be6842afa1/Userland/Libraries/LibLocale/CMakeLists.txt#L9)). I have no idea how to handle this. Error log:

```
@nix { "action": "setPhase", "phase": "qtPreHook" }
qtPreHook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/bsyyzy4hh3fqflbhmyvx0p867317l9yn-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -GNinja -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/>
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/pcryvps6mrlm2hjlpadbb5aymsv8k74b-gcc-wrapper-12.2.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
INFOLLD not found, cannot use to link. Disabling option...
-- Using pre-existing SERENITY_SOURCE_DIR: /nix/store/wn7pg2zs1wimy0gyfhzkf43gszh2a3kd-source
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/pcryvps6mrlm2hjlpadbb5aymsv8k74b-gcc-wrapper-12.2.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at /nix/store/wn7pg2zs1wimy0gyfhzkf43gszh2a3kd-source/Meta/Lagom/CMakeLists.txt:433 (install):
  install TARGETS given target "LibLocaleData" which does not exist.


-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /nix/store/9kh8qb3brld29ii4d6n54b4lr44ws6g0-libGL-1.5.0/lib/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /nix/store/2191qhhgvshb1sy8lql8byw1zz3khfiq-libxkbcommon-1.4.1/lib/libxkbcommon.so (Required is at least version "0.5.0") 
-- Found WrapVulkanHeaders: /nix/store/4kxghwsz5igc004axpk7rlzw1z8zfrik-vulkan-headers-1.3.231.0/include  
-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
```

**Comment by fgaz** [comment]
I also recently tried to upgrade the package and got the same error. I suspect it's because of [this commit](https://github.com/SerenityOS/serenity/commit/ce2f1b845fbd94013e36377aaa7375466cf1241d) but didn't have time to try patch-reverting it.

**Comment by ADKaster** [comment]
This is  erroring out because the default.nix file is completely disabling the UCD and CLDR downloads, rather than providing a local copy of them from nixpkgs. Looks like we broke non-unicode DB downloads recently. 

However, the browser is severely limited without those files, as any and all unicode and calendar and timezone support will just error out the JS engine.

See https://github.com/NixOS/nixpkgs/pull/186484/files#diff-14f7abcc87051d753d55fcb19df574b2b603f37ac730a906a9f718f5026b6599R37-R59


You can set the expected location of the extracted files with -DUCD_PATH, -DTZDB_PATH, -DCLDR_PATH and their respective UCD_ZIP_PATH, CLDR_ZIP_PATH, TZDB_ZIP_PATH cmake variables.

Note that if the version of those packages (tzdata, unicode-character-database, cldr-annotations-json) and the dumped version.txt for each must match the expected versions in `serenity/Meta/CMake/{time_zone_data, unicode_data, locale_data}.cmake` or it will try to download them anyway.

Note that the build also wants to download the "emoji-test.txt" file, which is not part of either unicode.org data set .zip file.:
```
set(EMOJI_TEST_URL "https://unicode.org/Public/emoji/${EMOJI_VERSION}/emoji-test.txt")
set(EMOJI_TEST_PATH "${UCD_PATH}/emoji-test.txt")
```

As long as that file exists in the UCD_PATH before running cmake, it won't try to download it.

**Comment by fgaz** [comment]
I updated ladybird in #211266, but I didn't fix the issue pointed out by @ADKaster yet.

**Comment by fgaz** [comment]
The package was updated so I'm closing. I opened #212792 to track the UCD/CLDR issue
