### ISSUE TITLE
channel 22.05 broken for nvidia_x11{,_beta} users

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nixpkgs#200415]
### Describe the bug

For users of nvidia hardware, the 22.05 nixos channel is broken for the `root` profile.

Staying on 5.19 is no longer supported, resulting in a failing system config during `nixos-switch`:

> error: linux 5.19 was removed because it reached its end of life upstream

Moving to 6.0 is not possible b/c the packaged versions of `nvidia_x11` and `nvidia_x11_beta` are not compatible with 6.0

I'm filing a new issue for this as this is no longer "cannot use _latest" but a "can't use anything" situation. This one is also more descriptive to pin if desired.

### Steps To Reproduce
1. `nix-channel --update` on 22.05
2. set  `services.xserver.videoDrivers = [ "nvidia" ];`
3. `nixos-rebuild switch`

### Expected behavior
A working configuration.

### Additional context
Bug for the lesser impact situation: https://github.com/NixOS/nixpkgs/issues/195654 ... looks like the backport failed and was forgotten about.

* might make sense to have an integration test for this

### Notify maintainers
@jonringer as per https://github.com/NixOS/nixpkgs/blob/df2bcbbd1c2aa144261cf1b0003c889c075dc693/pkgs/os-specific/linux/nvidia-x11/generic.nix#L118

### Metadata

```console
╰$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.17, NixOS, 22.05 (Quokka), 22.05.3977.f09ad462c5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(e): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by blablablerg** [comment]
> I'm filing a new issue for this as this is no longer "cannot use _latest" but a "can't use anything" situation. 

You can use kernel 5.15

**Comment by cornerman** [comment]
I am having this issue as well and cannot downgrade to kernel 5.15, because my xserver would not start then. I do not remember exactly, but there was an issue between the kernel 5.15 and 5.18. I previously got it working with 5.18, but now that it is end-of-life, I cannot use any configuration.

For now, I have disabled the nvidia driver and just use the intel driver, but there hardware acceleration is not working.

Anything that I can do?

**Comment by vcunat** [comment]
I suppose we close it, as support of 22.05 ended with year 2022.
