### ISSUE TITLE
Unable to use HIP/ROCM with Blender on a 5600G

### ISSUE THREAD

**Issue by lucasew** [NixOS/nixpkgs#200467]
### Describe the bug
Nixpkgs' blender is at 3.1 at the moment so it's understandable that it doesn't work yet. Blender got real support for HIP/ROCm only at 3.3.

When the blender from nixpkgs doesnt solve the problem I use blender-bin from nix-warez.

It works pretty well with CUDA. Only thing to take care is to setup nixGL if running on a container or a non NixOS system and enable the `hardware.opengl.enable` option in NixOS.

How is the procedure to make it work with an AMD GPU? Should it work out of the box? What are the stuff I need to have enabled?

### Steps To Reproduce
1. nix run blender-bin#blender_3_3
2. Edit -> Preferences -> System -> HIP
3. "No compatible GPUs found for cycles ... and AMD driver version 22.10 or newer"

### Expected behavior
Blender recognizes the GPU and allows exploring it's potential

### Screenshots

![Captura de tela_2022-11-09_23-02-56](https://user-images.githubusercontent.com/15693688/200987903-b15447ae-e199-4e74-9580-ca07f7f8f7d5.png)

### Additional context
https://github.com/lucasew/nixcfg/blob/586488fb89df3387af0594742b9cede2a72818bd/nodes/whiterun/default.nix#L28

### Notify maintainers
@Madouura  @Flakebi @lovesegfault @acowley 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
lucasew@whiterun ~ 0$  nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.05 (Quokka), 22.05.20221026.e6e675c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/etc/flake/nixpkgs`


```

**Comment by lucasew** [comment]
So a HIP capable is present in master

![Captura de tela_2022-11-10_00-09-33](https://user-images.githubusercontent.com/15693688/200991560-f0741aad-f90a-45e1-ab27-719e6126eb76.png)

But how to make it work with blender-bin packages? Those are packaged from the official binaries.

**Comment by lucasew** [comment]
Pro-tip for the bpy club if the GPU doesn't appear at first
```
bpy.context.preferences.addons['cycles'].preferences.get_devices()
bpy.context.preferences.addons['cycles'].preferences.devices
```

**Comment by Madouura** [comment]
I would suggest also doing this.
```nix
hardware = {
  opengl.extraPackages = with pkgs; [
    rocm-opencl-icd
    rocm-opencl-runtime
];
```

**Comment by Madouura** [comment]
~~Reading comprehension strikes again...~~
Anyway, I would suggest just adding a ``nixpkgs-unstable`` input to your flake and using blender 3.3.1 in the meantime.
https://github.com/lucasew/nixcfg/blob/586488fb89df3387af0594742b9cede2a72818bd/flake.nix#L59-L61

**Comment by Flakebi** [comment]
We patch our blender for HIP support, so if you want to use unpatched blender, you need to make `/opt/rocm/hip` available in a chroot or so. https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/blender/default.nix#L91-L94

**Comment by lucasew** [comment]
> We patch our blender for HIP support, so if you want to use unpatched blender, you need to make `/opt/rocm/hip` available in a chroot or so. https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/blender/default.nix#L91-L94

I think I can workaround it using systemd-tmp files. Isn't it overridable by an environment variable?

**Comment by lucasew** [comment]
It seems that it isn't (yet)

https://github.com/blender/blender/blob/0b4bd3ddc016298e868169a541cf6c132b10c587/extern/hipew/src/hipew.c#L256

**Comment by lucasew** [comment]
![Captura de tela_2022-11-10_10-18-14](https://user-images.githubusercontent.com/15693688/201102071-daaf86d2-41bf-4e9e-9566-2bfbe9e78371.png)

IT'S WORKING, I CAN'T BELIEVE

blender-bin is working

@Flakebi gave me the insight I was looking for

The magic module, if anyone is interested: https://github.com/lucasew/nixcfg/blob/24bd0f2a3cbb8cd51e11a35ddf33019d968b104d/nodes/whiterun/rocm-gambiarra.nix#L1

**Comment by lucasew** [comment]
I've updated the NixOS WIki with a HIP section telling about this solution.

https://nixos.wiki/wiki/AMD_GPU

**Comment by Flakebi** [comment]
nixos-unstable has the `blender-hip` package. The default blender package has no hip support because hip and its dependencies increase the closure size by a lot.
Looking at the blender code again, the first entry searches just for the library name. So probably one can just set `LD_LIBRARY_PATH` instead of relying on some global directory?

**Comment by Madouura** [comment]
>So probably one can just set ``LD_LIBRARY_PATH`` instead of relying on some global directory?

That's what I did to get some stable-diffusion stuff working, so I think that's likely the correct answer.

**Comment by nonetrix** [comment]
I added everything to my configs, despite this I still have no support with `blender-hip`  with my RX 6800

amd-gpu.nix
```
{
  config,
  pkgs,
  ...
}: {
  # TODO: Figure out how to add pro drivers as well
  boot.initrd.kernelModules = ["amdgpu"];
  services.xserver.videoDrivers = ["amdgpu"];

  hardware.opengl.extraPackages = with pkgs; [
    rocmPackages.clr.icd
    rocm-opencl-icd
    rocm-opencl-runtime
    amdvlk
  ];

  hardware.opengl.extraPackages32 = with pkgs; [
    driversi686Linux.amdvlk
  ];

  systemd.tmpfiles.rules = [
    "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  ];

  hardware.opengl.driSupport = true;
  hardware.opengl.driSupport32Bit = true;

  environment.systemPackages = [
    pkgs.rocmPackages.rocm-smi
    pkgs.rocmPackages.rocminfo
  ];
}
```
unconfigured.nix
```
{
  config,
  pkgs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    # ...
    blender-hip
     # ...
  ];
}
```
![image](https://github.com/NixOS/nixpkgs/assets/45698918/d5c000e6-989e-4263-9dc0-9fffbd18eee9)

Running it in the terminal seems to reveal this:
```
HIP hipInit: Invalid device
```
Also it seems there is no folder under `/opt/` named `rocm` despite me adding this like:
```
systemd.tmpfiles.rules = [
    "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  ];
```

**Comment by lucasew** [comment]
> I added everything to my configs, despite this I still have no support with `blender-hip` with my RX 6800
> 
> amd-gpu.nix
> 
> ```
> {
>   config,
>   pkgs,
>   ...
> }: {
>   # TODO: Figure out how to add pro drivers as well
>   boot.initrd.kernelModules = ["amdgpu"];
>   services.xserver.videoDrivers = ["amdgpu"];
> 
>   hardware.opengl.extraPackages = with pkgs; [
>     rocmPackages.clr.icd
>     rocm-opencl-icd
>     rocm-opencl-runtime
>     amdvlk
>   ];
> 
>   hardware.opengl.extraPackages32 = with pkgs; [
>     driversi686Linux.amdvlk
>   ];
> 
>   systemd.tmpfiles.rules = [
>     "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
>   ];
> 
>   hardware.opengl.driSupport = true;
>   hardware.opengl.driSupport32Bit = true;
> 
>   environment.systemPackages = [
>     pkgs.rocmPackages.rocm-smi
>     pkgs.rocmPackages.rocminfo
>   ];
> }
> ```
> 
> unconfigured.nix
> 
> ```
> {
>   config,
>   pkgs,
>   ...
> }: {
>   environment.systemPackages = with pkgs; [
>     # ...
>     blender-hip
>      # ...
>   ];
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/45698918/294722360-d5c000e6-989e-4263-9dc0-9fffbd18eee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODQzNTUsIm5iZiI6MTcwNDU4NDA1NSwicGF0aCI6Ii80NTY5ODkxOC8yOTQ3MjIzNjAtZDVjMDAwZTYtOTg5ZS00MjYzLTlkYzAtOWZmZmJkMThlZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIzMzQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMjIyNDA2YjIwZjA5MGM3NmRiMzgxODgyODU2NTQwNWU1MThkMmY5NjBjMmM2NDExMTFjMWI2YWM3ZWRiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FuSCoTvW8XiKU6QFOruf1gtlaq97Lu5oUNgnJZwqnOk)
> 
> Running it in the terminal seems to reveal this:
> 
> ```
> HIP hipInit: Invalid device
> ```

Is `hardware.opengl.enable` enabled?

**Comment by nonetrix** [comment]
I enabled it, no changes. But thanks regardless likely best to do that explicitly

**Comment by C0D3-M4513R** [comment]
> I added everything to my configs, despite this I still have no support with `blender-hip` with my RX 6800
> 
> amd-gpu.nix
> 
> ```
> {
>   config,
>   pkgs,
>   ...
> }: {
>   # TODO: Figure out how to add pro drivers as well
>   boot.initrd.kernelModules = ["amdgpu"];
>   services.xserver.videoDrivers = ["amdgpu"];
> 
>   hardware.opengl.extraPackages = with pkgs; [
>     rocmPackages.clr.icd
>     rocm-opencl-icd
>     rocm-opencl-runtime
>     amdvlk
>   ];
> 
>   hardware.opengl.extraPackages32 = with pkgs; [
>     driversi686Linux.amdvlk
>   ];
> 
>   systemd.tmpfiles.rules = [
>     "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
>   ];
> 
>   hardware.opengl.driSupport = true;
>   hardware.opengl.driSupport32Bit = true;
> 
>   environment.systemPackages = [
>     pkgs.rocmPackages.rocm-smi
>     pkgs.rocmPackages.rocminfo
>   ];
> }
> ```
> 
> unconfigured.nix
> 
> ```
> {
>   config,
>   pkgs,
>   ...
> }: {
>   environment.systemPackages = with pkgs; [
>     # ...
>     blender-hip
>      # ...
>   ];
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/45698918/294722360-d5c000e6-989e-4263-9dc0-9fffbd18eee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODQ1MDQsIm5iZiI6MTcwNzM4NDIwNCwicGF0aCI6Ii80NTY5ODkxOC8yOTQ3MjIzNjAtZDVjMDAwZTYtOTg5ZS00MjYzLTlkYzAtOWZmZmJkMThlZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA5MjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYTI4NmRiODVmMTlmNWUxMzJjZjI0YjU3NjhkMTM5Zjk0MjRiNWExZDExOGI5YjBhN2JlOTE0YzVmMjU3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_psqsV4L89BsB1Z0lMxcl7IsBzwid6tgszOaQmQooA)
> 
> Running it in the terminal seems to reveal this:
> 
> ```
> HIP hipInit: Invalid device
> ```

I'm running into the same issue. I also installed blender via system packages.
```
{pkgs,...}:
{
  #thanks to https://nixos.wiki/wiki/AMD_GPU
  boot.initrd.kernelModules = [ "amdgpu" ];
  services.xserver.videoDrivers = [ "amdgpu" ];
  hardware.opengl.extraPackages = with pkgs; [
    #glibc
    #amdvlk
    rocm-opencl-icd
    rocm-opencl-runtime
    rocmPackages.clr
    rocmPackages.clr.icd
  ];

  hardware.opengl.enable = true;
  hardware.opengl.driSupport = true;
  # For 32 bit applications
  hardware.opengl.driSupport32Bit = true;

  systemd.tmpfiles.rules = [
    "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  ];


  environment.systemPackages = with pkgs; [
    amdgpu_top
    glxinfo
    vulkan-tools
  ];
}
```

**Comment by nonetrix** [comment]
Fixed for me now but seems super slow compared to what I would expect, even the basic cube scene takes 1 minute weirdly. Also, despite being on a RDNA2 card I do not have Hip RT only just Hip
