### ISSUE TITLE
Trouble importing / exporting in Zotero

### ISSUE THREAD

**Issue by jokogr** [NixOS/nixpkgs#20049]
## Issue description

Zotero starts, but I cannot use it effectively.

When I try to import stuff (either from file or the clipboard), an error dialog shows up: 

> The selected file is not in a supported format.

When I try to export a library, the dropdown menu of the format appears to be empty.

CC @ttuegel 

### Steps to reproduce

* Include `pkgs.zotero` in `environment.systemPackages` 

## Technical details

* System: NixOS 17.03.git.a06e649 (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: 16.09pre90254.6b20d5b

**Comment by ttuegel** [comment]
Sorry, I'm not maintaining Zotero anymore. I haven't used the standalone version in years because it was so unreliable, but lately I'm not even using the Firefox plugin.

**Comment by vcunat** [comment]
I was always using the FF plugin, without any such problems (but also almost stopped using zotero about half a year ago).

**Comment by jokogr** [comment]
The Firefox plugin works as intended and since there is currently no maintainer for the standalone version, I'll close this. Thanks for the feedback.
