### ISSUE TITLE
vnstat fails to start on unstable

### ISSUE THREAD

**Issue by awjamison** [NixOS/nixpkgs#20042]
## Issue description

> Error: Unable to open database directory "/var/lib/vnstat": No such file or directory
The vnStat daemon should have created this directory when started.
Check that it is is configured and running. See also "man vnstatd".

Looks like the database wasn't created.

### Steps to reproduce
Install vnstat
`$ vnstat`

## Technical details
* System: 17.03pre94121.210b3b3 (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: 17.03pre94694.fa4167c

**Comment by joachifm** [comment]
So you ran the executable directly as an unprivileged user? I think failure in that case is expected, if the daemon needs to write to system directories. Either configure vnstat to write somewhere else or use the proposed vnstat module https://github.com/NixOS/nixpkgs/pull/19809

**Comment by awjamison** [comment]
The daemon wasn't running. Starting it fixed this. 
`$ sudo vnstatd -d`
