### ISSUE TITLE
Mercurial: drop support for hgk GUI extension

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#20059]
hgk extension (which requires Tk) is [unloved feature](https://www.mercurial-scm.org/wiki/HgkExtension) in mercurial and [wasn't updated 19 months](https://www.mercurial-scm.org/repo/hg/log/tip/contrib/hgk). Maybe it is a good idea to remove hgk from default mercurial installation, as we already have packaged TortoiseHg.

**Comment by FRidh** [comment]
What benefit does removing `hgk` have? It won't make the closure size smaller because `tkinter` isn't passed in to `mercurial` so by default `hgk` won't work.

**Comment by danbst** [comment]
The main benefit is expression will become simpler. 

>so by default hgk won't work

this is another benefit: we won't lie to users that we have working hgk

```
$ hg view --config "extensions.hgk="
/bin/sh: hgk: command not found
```

**Comment by FRidh** [comment]
ah, check `pkgs.mercurialFull`

**Comment by danbst** [comment]
yep, that works.
