### ISSUE TITLE
Discord Canary 0.0.143 fails to build with `withOpenASAR = true;`

### ISSUE THREAD

**Issue by fufexan** [NixOS/nixpkgs#200561]
### Steps To Reproduce
1. build `(discord-canary.override {withOpenASAR = true;})`

### Build log
https://gist.github.com/fufexan/0cfa71fa45e51578381a03161a9cecc3

### Additional context
It is working fine either without OpenASAR or with OpenASAR on 0.0.142.

### Notify maintainers

@MP2E @devins2518 @Artturin @Infinidoge 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.5, NixOS, 22.11 (Raccoon), 22.11.20221030.412b991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/etc/nix/flake-channels/nixpkgs`

**Comment by dibusure** [comment]
same, but with ordinary discord

**Comment by fufexan** [comment]
Seems to have been fixed for me, about 1-2 weeks ago.

**Comment by Infinidoge** [comment]
> same, but with ordinary discord
@dibusure 

Ordinary Discord failing to build should probably its own separate issue.

**Comment by fufexan** [comment]
Since my issue has been resolved, I think it can be closed.

**Comment by dibusure** [comment]
> > same, but with ordinary discord
> 
> @dibusure
> 
> Ordinary Discord failing to build should probably its own separate issue.

no, it builds, but without openasar

**Comment by Infinidoge** [comment]
That would also be its own separate issue.
