### ISSUE TITLE
Quarto

### ISSUE THREAD

**Issue by schlichtanders** [NixOS/nixpkgs#200503]
**Project description**
Quarto® is an open-source scientific and technical publishing system built on [Pandoc](https://pandoc.org/)

**Metadata**

* homepage URL: https://quarto.org/
* source URL: https://github.com/quarto-dev/quarto-cli
* license: gpl2+
* platforms: unix, linux, darwin, ...

**Comment by dit7ya** [comment]
We already have https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/quarto/default.nix#L56. If that meets your requirements, please close this issue.

**Comment by schlichtanders** [comment]
yes, that is it. Sorry for haven't looked upon unstable channel.

The more thank you for pointing me to the package.
