### ISSUE TITLE
NixOS 22.11 - Zero Hydra Failures on i686

### ISSUE THREAD

**Issue by sg2002** [NixOS/nixpkgs#200691]
Part of #199919.

I've got a permission @mweinelt to open this discussion to try and improve the i686 support somewhat in the upcoming release.

Since i686 is a legacy platform that's getting rarer every year, there are plenty of calls for dropping support for it outright, but I feel like the way to go for the immediate future is just refocusing the support for it somewhat.

In 22.11 we would get the DEs working out of box on i686 again.

Among the remaining failures we should decide, which packages do we really care enough to try and support, since plenty of them(or their dependencies) are dropping or would be dropping x32 support in the foreseeable future or are just too costly to maintain in terms of manpower in proportion to the actual userbase.

The remaining [200+](https://hydra.nixos.org/eval/1785178?filter=i686&compare=1785171&full=#tabs-still-fail) failures should probably be first categorized by whether the failure is i686 exclusive. There are plenty of cases where it isn't.

Then we can roughly split the remaining failures by purpose:
1. General use software. One currently failing example is keepassxc, but it's in the broken everywhere category. Ideally we want to maintain at least the most popular tools.
3. Developer and server software. We maybe want to maintain some of those, but they can be somewhat costly to do so in terms of work. Currently [nginx](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.nginx.i686-linux) and at least some [mariadb](https://hydra.nixos.org/eval/1785178?filter=mariadb&compare=1785171&full=#tabs-still-fail) versions do not work.
4. Specialized and rare software. It ranges from MuseScore(fails everywhere) to things like rss2email(generic failure too) and [nitter](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.nitter.i686-linux). This is the most obvious category for us to look into cutting.

Then there's another category, software that currently does not have a Hydra job, but someone cares about it enough and is willing to maintain. Personally I want to get ncdu and streamlink running again.

Finally, if you are a i686 user and (want to) use any of the software that's currently failing on Hydra, please comment here, so that we would know for sure that that there are still users who care about those particular packages.

**Comment by sg2002** [comment]
Hope nobody minds me keeping this issue open for now, since I still have a few packages that I want to get working again with the end goal of reaching that coveted ZHF state.

**Comment by SuperSandro2000** [comment]
22.11 is done. Is there still anything left here? Otherwise I would close this.

**Comment by sg2002** [comment]
Sure, lets close it, I'm still planning to fix a few other things on i686, but this can be done outside of this.
