### ISSUE TITLE
Kodi 19.4 build hangs at installCheckPhase

### ISSUE THREAD

**Issue by jonseitz** [NixOS/nixpkgs#200635]
### Describe the bug

I'm trying to build the Kodi 19.4 package from source, cross-compiling from `x86_64` to `aarch64` to deploy on a Raspberry Pi via Nixops. The compile process generally runs for a few hours, and when it reaches the `installCheckPhase`, it [prints the Kodi version information](https://github.com/NixOS/nixpkgs/blob/350fd0044447ae8712392c6b212a18bdf2433e71/pkgs/applications/video/kodi/unwrapped.nix#L245) from `$out/bin/kodi --version`, but does not continue past that process.

I have been able to get it to work by setting `doInstallCheck = false;` via `overrideAttrs`, and the process continues fine. 

### Steps To Reproduce
1. Configure `x86_64` Arch workstation to cross-compile nix packages using `qemu-static-bin`, [as described in the wiki](https://nixos.wiki/wiki/NixOS_on_ARM#Compiling_through_binfmt_QEMU)
2. Create a nixops deployment to [install Kodi as desktopManager](https://nixos.wiki/wiki/kodi)
3. Run deployment, wait for Kodi compilation to finish

### Expected behavior

The Kodi build should complete, and the new version of Kodi should be installed and copied to the remote system. Or if the install did fail, it should provide an error message.

### Screenshots

This config snippet fails:

```nix
{
  services.xserver = {
    enable = true;
    desktopManager.kodi = {
      enable = true;
    };
    displayManager.autoLogin = {
      enable = true;
      user = "kodi";
    };
  };
}
```

But this one works: 

```nix
{
  services.xserver = {
    enable = true;
    desktopManager.kodi = {
      enable = true;
      package = pkgs.kodi.overrideAttrs (final: prev: { doInstallCheck = false; });
    };
    displayManager.autoLogin = {
      enable = true;
      user = "kodi";
    };
  };
}
```

### Additional context
I ran into the same problem trying to compile a generic sd-image for the Pi, with the same `x86_64` to `aarch64` build setup, so I don't think nixops is affecting the build. 

My guess is that it has something to do with the cross-compilation via `qemu`, like maybe it's not closing the process properly?

### Notify maintainers

@aanderse 
@cpages
@edwtjo
@minijackson
@peterhoeg
@sephalon

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6-zen1-1-zen, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - channels(seitz): `"nixos-hardware, nixpkgs-22.05"`
 - nixpkgs: `/home/seitz/.nix-defexpr/channels/nixpkgs`
```

**Comment by jonseitz** [comment]
Did a bit more testing, and the issue does seem to be related to running `kodi` via `qemu-aarch64-static` and `systemd-binfmt` while building. I tested a native `x86_64` version of `kodi` installed from `pacman` and `kodi --version` runs and exits as expected. Similarly, running the nix-build `aarch64` package on the raspberry pi runs and exits as expected.

I also grabbed an `aarch64` build from [hydra](https://hydra.nixos.org/build/198436967) and running that via `qemu-aarch64-static` on the same Arch box also hangs without exiting. (For good measure I also pulled down [an `x86_64` build](https://hydra.nixos.org/build/198434619) and it works correctly).

**Comment by aanderse** [comment]
Thanks for filing the issue. Unfortunately you pinged the wrong team. The `kodi` team signed up for maintaining `kodi` and related packages, not for cross compilation which is an entirely different ball game. We have some community members active in cross compilation stuff and you'll have much better luck if you ping them. Feel free to mention [discourse](https://discourse.nixos.org) or our `matrix` channel... you might find some people who can help there.

**Comment by jonseitz** [comment]
Ah, got it. Thanks for the tip @aanderse. I'll give it a shot on discourse and see what I can find out.

**Comment by aanderse** [comment]
Out of curiosity is this still an issue?
