### ISSUE TITLE
Trying to launch polychomatic getting error [qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""]

### ISSUE THREAD

**Issue by jrgiacone** [NixOS/nixpkgs#200780]
### Steps To Reproduce
Install base system and enable openrazer, install polychromatic from unstable
launch polychromatic-controller in terminal

### Expected behavior
polychromatic launches

### Notify maintainers
@SuperSandro2000 @evanjs 

### Metadata

```console
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.77, NixOS, 22.11 (Raccoon), 22.11.20221109.872fcee`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(jrgiacone): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
Works for me on plasma

**Comment by jrgiacone** [comment]
> Works for me on plasma

I made a pull request that fixes the missing library for lixcb, normally i think it is included with plasma, but for window managers that do not use plasma it may be required. I have another issue pending where the icon does not show up.

**Comment by evanjs** [comment]
#200782
Didn't see the issue/PR linked elsewhere
