### ISSUE TITLE
hledger-web cannot be installed

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nixpkgs#20076]
## Issue description

running `nix-env -iA nixpkgs.haskellPackages.hledger-web` fails to build.

The `cabal configure` step fails with:

```
Configuring hledger-web-1.0.1...
Setup: Encountered missing dependencies:
hledger >=1.0.1, hledger-lib >=1.0.1
```

## Technical details

* System: 17.03pre94694.fa4167c (Gorilla)
* Nix version:  nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03.git.c872b84M

**Comment by gebner** [comment]
Yes, hledger got a new release last week (with API changes) and so most tools that depend on hledger have already upgraded.  However, hledger is in the LTS Haskell set and is updated on a different schedule than the other haskell packages.

The good news is, LTS Haskell 7.6 already has the new versions.  @peti can you update the LTS package set?

**Comment by peti** [comment]
I'll merge the latest update after the test builds at http://hydra.nixos.org/jobset/nixpkgs/haskell-updates are complete. That should fix hledger-web.
