### ISSUE TITLE
joplin-desktop: clicking on links does not open a browser

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#200833]
### Describe the bug
When I click on a link in joplin-desktop, it doesn't open my browser.

### Steps To Reproduce
1. Install and open `joplin-desktop`.
2. In the sample documents, e.g. "Welcome to Joplin", try clicking on some links.
3. Nothing happens.

### Expected behavior
Clicking on links should open a web browser.

### Additional context
This is perhaps a generic issue related to how AppImage applications get packaged in nixpkgs?

### Notify maintainers
@HugoReeves 

### Metadata
NixOS 22.05 / GNOME.

**Comment by SuperSamus** [comment]
I also noticed the same issue on `zettlr`. Being both Electron note-taking apps running on an AppImage, it's probably related. (`nixpkgs-unstable`)

**Comment by bjornfor** [comment]
`joplin-desktop` uses `appimage.wrapType2`, which is built on `buildFHSUserEnv`, so I guess https://github.com/NixOS/nixpkgs/issues/160923 is relevant.

I ran joplin with strace and see that it uses `xdg-open`, which eventually invokes `/run/current-system/sw/bin/firefox` correctly, but firefox fails to start/open the link.

**Comment by bjornfor** [comment]
> I ran joplin with strace and see that it uses `xdg-open`, which eventually invokes `/run/current-system/sw/bin/firefox` correctly, but firefox fails to start/open the link.

More data from strace:
```

**Comment by bjornfor** [comment]
Closing due to already existing root cause issue: https://github.com/NixOS/nixpkgs/issues/160923

**Comment by AshleyYakeley** [comment]
Is there a workaround for this?

I tried
```
xdg.portal = { enable = true; xdgOpenUsePortal = true; };
```

but it didn't help.

**Comment by AshleyYakeley** [comment]
This worked (on my MATE desktop):

```
    xdg.portal =
    {
        enable = true;
        xdgOpenUsePortal = true;
        extraPortals = [pkgs.xdg-desktop-portal-gtk];
    };
```
and then logging out and back in to my session.
