### ISSUE TITLE
building go 1.8 fails

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#20082]
## Issue description
I'm trying to build go 1.8 on nixOS. I get the the following error:

https://gist.githubusercontent.com/nhooyr/5449d049f29d3e0ed95e1bf1ef76ebb8/raw/abe8d654a0feb890de47710a77467a1dd5aac193/gistfile1.txt

### Steps to reproduce
1. Add the following to `/etc/nixos/configuration.nix`
```
  nixpkgs.config.packageOverrides = pkgs: with pkgs; {
    go = lib.overrideDerivation go (attrs: rec {
      name = "go-${version}-dev";
      version = "1.8";
      src = fetchgit {
        url = "https://github.com/golang/go";
        rev = "c57a443e8777de0f34444dd512fbcb099e7b3e29";
        sha256 = "14q3fv0k6llca7pldlx6hp28wd85dd5pj04f8wdlf4a42a8sip7f";
        leaveDotGit = true;
      };
      buildInputs = [ pcre git ];
    });
  };
```
2. `nixos-rebuild switch` should give you the error

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.03.git.9a4ba2b (Gorilla)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.03.git.9a4ba2bM"

**Comment by nhooyr** [comment]
This only happens on NixOS. Go 1.8 builds fine with nix on darwin for me.

**Comment by nhooyr** [comment]
I got it to build by skipping tests:
```
  nixpkgs.config.packageOverrides = pkgs: with pkgs; {
    go = lib.overrideDerivation go (attrs: rec {
      name = "go-${version}-dev";
      version = "1.8";
      src = fetchgit {
        url = "https://github.com/golang/go";
        rev = "5b147122d6094b792a027b892884b994fe77a4d6";
        sha256 = "10559jqy6cmq8dpyws2zg8q6df0hm93r9r46x469nd3mqf3mmdxn";
        leaveDotGit = true;
      };
      buildInputs = go.buildInputs ++ [git];
      installPhase =
      ''
      cp -r . $GOROOT
      ( cd $GOROOT/src && ./make.bash )
      '';
    });
    buildGoPackage = callPackage /etc/nixos/nixpkgs/pkgs/development/go-modules/generic {};
  };
```

**Comment by ixmatus** [comment]
I believe I have fixed this without remove all of the test (specifically, applying a patch to remove the internal pie linking behavior in the test.go).

I will put up a PR soon and link to this ticket.

**Comment by ixmatus** [comment]
@nhooyr @grahamc this issue can be closed too, now.
