### ISSUE TITLE
passwordless (sshAgentAuth) sudo does not work

### ISSUE THREAD

**Issue by benaryorg** [NixOS/nixpkgs#20088]
## Issue description

NixOS provides [`security.pam.enableSSHAgentAuth`](https://nixos.org/nixos/manual/options.html#opt-security.pam.enableSSHAgentAuth) and [`security.pam.services.<name?>.sshAgentAuth`](https://nixos.org/nixos/manual/options.html#opt-security.pam.services._name__.sshAgentAuth) for passwordless pam authentication, but there are quite few resources on how to properly configure that and I *think* I've used "The Correct Way" but it does not work.

What I am trying to achieve is a system configuration that:
- enables only SSHing into it
- all user accounts without password (without password ≠ empty password)
- login **and** sudo only via SSH pub-key

Yes, I could just set the `NOPASS` thing, but while looking for it I found the above options and wanted to try them.

### Steps to reproduce

The relevant parts of my configs:

```nix
{
  services.openssh.enable = true;
  services.openssh.permitRootLogin = "no";

  security.sudo.enable = true;
  security.pam.enableSSHAgentAuth = true;
  security.pam.services.sudo.sshAgentAuth = true;

  users.users.benaryorg =
  {
    isNormalUser = true;
    uid = 1000;
    extraGroups = ["wheel"];
    shell = pkgs.zsh;
    createHome = true;
    openssh.authorizedKeys.keys =
    [
      "ssh-rsa somekey benaryorg@gnutoo"
    ];
}
```

SSH works, but as soon as I try to use `sudo` it desperately asks for a password (which the account does not have) and *journald* logs this:

```journal
Nov 02 14:22:30 nixos sudo[1324]: pam_ssh_agent_auth: Failed Authentication: `benaryorg' as `benaryorg' using ~/.ssh/authorized_keys:~/.ssh/authorized_keys2:/etc/ssh/authorized_keys.d/%u
Nov 02 14:22:34 nixos sudo[1324]: pam_unix(sudo:auth): authentication failure; logname=benaryorg uid=1000 euid=0 tty=/dev/pts/0 ruser=benaryorg rhost=  user=benaryorg
Nov 02 14:22:36 nixos sudo[1324]: pam_ssh_agent_auth: Failed Authentication: `benaryorg' as `benaryorg' using ~/.ssh/authorized_keys:~/.ssh/authorized_keys2:/etc/ssh/authorized_keys.d/%u
Nov 02 14:22:39 nixos sudo[1324]: pam_ssh_agent_auth: Failed Authentication: `benaryorg' as `benaryorg' using ~/.ssh/authorized_keys:~/.ssh/authorized_keys2:/etc/ssh/authorized_keys.d/%u
Nov 02 14:22:41 nixos sudo[1324]: benaryorg : 3 incorrect password attempts ; TTY=pts/0 ; PWD=/home/benaryorg ; USER=root ; COMMAND=/run/current-system/sw/bin/echo hi
```

This *is* the result when using `ssh -A`.

## Resolution

It would be enough if someone could tell me what I did wrong and this issue would be found via DuckDuckGo/Google/Bing so others would be able to find it.
It would however be preferable to create some documentation related to this on some official-ish part of the NixOS project or even clarify usage within the links at the top of this post.

## Technical details

* System: NixOS: `16.09.901.9902430 (Flounder)`
* Nix version: `nix-env: (Nix) 1.11.4`
* Nixpkgs version: `"16.09.901.9902430"`

**Comment by benaryorg** [comment]
Definitely my fault, I am sorry I did not triple check, I have not yet added the key to my ssh-agent since I restored the last backup.

**Comment by lionello** [comment]
Me too! This message at least got me to double check my local agent setup!

**Comment by srd424** [comment]
For people randomly googling, another stupid mistake to check for: make sure you're actually forwarding your agent to the target machine..

Going to go sit in the dunce's corner for a bit now.

**Comment by jeslinmx** [comment]
```
> ssh-add -L
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOt/JmiwxM1ob/1k+Jw9nyQkh3dB3IGRm34+9Zv97l58 jeslinmx@jeshua-fedora

> sudo printenv | grep SSH
[sudo] password for jeslinmx: 
SSH_AUTH_SOCK=/tmp/ssh-XXXX1YS1nJ/agent.63486
```

Hmm. Doesn't seem that we have a /var/log/auth.log on NixOS either to help with the troubleshooting, unless it's behind some option.
