### ISSUE TITLE
flutter: Expose flutterDrv, patch directories for external use

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#200986]
The [Flutter package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/flutter/default.nix) provides a `mkFlutter` function to allow customized Flutter derivations to be made.

Internally, however, it uses a `flutterDrv` function that calls `mkFlutter` with URLs generated from the given version number. Patches are also used internally, but there is no way (that I know of) to access these externally.

I propose that `flutterDrv` and `flutter2Patches`/`flutter3Patches` attributes get added to the attribute set along with `mkFlutter`, to make it easier to create custom Flutter derivations.

**Comment by hacker1024** [comment]
@babariviere @ericdallo

**Comment by pmarreck** [comment]
I was actually just about to file a bug about `fluffychat` which produces this error instead of building, wonder if it's related, since it's breaking on flutter? cc @mkg20001 

```
error: hash mismatch in fixed-output derivation '/nix/store/h4pc4zxns82zllgc2r68aabs2mlgwvrz-fluffychat-1.2.0-deps-flutter-v2.10.5-x86_64-linux.tar.gz.drv':
         specified: sha256-1PDX023WXRmRe/b1L+6Du91BvGwYNp3YATqYSQdPrRY=
            got:    sha256-9nQaxpStbb8obsTqeuQnzEORFB/r9soW43kNEeTpn2E=
```

**Comment by ericdallo** [comment]
Sounds good @hacker1024
