### ISSUE TITLE
Please package Zap

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#200970]
**Project description**

> Play all your favorite sound effects! This handy soundboard makes your livestreams and videocasts more entertaining.
> Import audio files, arrange them in collections and customize their appearance.

We don't have a soundboard packaged yet and this has a great design.

**Metadata**

* homepage URL: https://gitlab.com/rmnvgr/zap
* source URL: https://gitlab.com/rmnvgr/zap
* license: gplv3+ and 5 others
* platforms: linux, maybe other where gnome apps work

**Comment by davidak** [comment]
@NixOS/gnome can you maintain this package?

I can try to package it. Does look quite easy.

**Comment by jtojnar** [comment]
IMO teams should be focused and narrowly scoped. We are already maintaining more apps than we should (apps like GNOME LaTeX are GNOME in name only). GNOME Circle apps, while following GNOME HIG, are still not part of GNOME proper.

**Comment by Aleksanaa** [comment]
The project is archived
