### ISSUE TITLE
services.ddclient not linking /etc/ddclient.conf

### ISSUE THREAD

**Issue by pshendry** [NixOS/nixpkgs#20101]
## Issue description

After upgrading, ddclient fails to start due to `/etc/ddclient.conf` being missing, doubtless due to 9f4775dbb509602b3a65f26aac708c1dabf79a4f (which changes `services.ddclient` to use `environment.etc`). I'm able to manually define files (e.g. `test.conf`) using environment.etc, but if I try to manually define a file named `ddclient.conf` using `environment.etc`, no corresponding file appears in `/etc` after a rebuild. I'm not sure whether that's a symptom of the same underlying problem, or whether that's just a conflict with the `environment.etc` defined in `ddclient.nix` somehow.

No errors are displayed during the rebuild to explain why the file fails to be linked.

### Steps to reproduce

My ddclient config:

    services.ddclient = {
      enable = true;
      use = "web, web=dynamicdns.park-your-domain.com/getip";
      protocol = "namecheap";
      server = "dynamicdns.park-your-domain.com";
      username = "domain.com";
      password = "password";
      domain = "@";
    };

## Technical details

* System: 17.03pre94694.fa4167c (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre94694.fa4167c"

**Comment by rycee** [comment]
Is the `/etc/static/ddclient.conf` file created?

Perhaps related to 5bca9297ffb7806b3b350938ab652befb2cd1c24? Maybe the `enable` in the `environment.etc` is not actually set to true? Would you mind trying to build your environment with this patch applied?

```patch
diff --git a/nixos/modules/services/networking/ddclient.nix b/nixos/modules/services/networking/ddclient.nix
index 5050ecb..7a46cd3 100644
--- a/nixos/modules/services/networking/ddclient.nix
+++ b/nixos/modules/services/networking/ddclient.nix
@@ -119,7 +119,7 @@ in
       home = stateDir;
     };
 
-    environment.etc."ddclient.conf" = {
+    environment.etc."ddclient.conf" = builtins.trace config.services.ddclient.configFile {
       enable = config.services.ddclient.configFile == /etc/ddclient.conf;
       uid = config.ids.uids.ddclient;
       mode = "0600";
```

It should print `trace: /etc/ddclient.conf`.
