### ISSUE TITLE
systemd: why is not compiled with release mesonFlags?

### ISSUE THREAD

**Issue by rodrgz** [NixOS/nixpkgs#201058]
Is there any reason systemd is not compiled with the -Dmode=release or -Dbuildtype=release or -Doptimization=3 mesonFlags?

**Comment by Artturin** [comment]
@NixOS/systemd arch uses `-Dmode=release` https://github.com/archlinux/svntogit-packages/blob/de85bd896ddaf3fe1850e4a59d89e06af9ce10cb/systemd/trunk/PKGBUILD#L113

**Comment by rodrgz** [comment]
> @NixOS/systemd arch uses `-Dmode=release` https://github.com/archlinux/svntogit-packages/blob/de85bd896ddaf3fe1850e4a59d89e06af9ce10cb/systemd/trunk/PKGBUILD#L113

Fedora uses `-Dmode=release` too
https://src.fedoraproject.org/rpms/systemd/blob/rawhide/f/systemd.spec#_454

**Comment by Mic92** [comment]
Our meson setup hook currently specifies "plain" optimization level: https://github.com/NixOS/nixpkgs/blob/69f8e94c46904a3194afcc8b232402287c7f91c9/pkgs/development/tools/build-managers/meson/setup-hook.sh#L19

This means `-O2` as this is what our compiler wrapper sets.

See also: https://mesonbuild.com/Builtin-options.html

**Comment by Mic92** [comment]
After reading what the implication of this flag is and how it is currently used, I think we should that this for sure.
