### ISSUE TITLE
rPackages.XML cannot find xml2-config

### ISSUE THREAD

**Issue by ibor** [NixOS/nixpkgs#20105]
## Issue description

 rPackages.XML cannot find xml2-config during compilation

**Notes:** 
- xml2-config is part of libxml2
- packagesWithNativeBuildInputs contains "XML = [ pkgs.libtool pkgs.libxml2.dev pkgs.xmlsec pkgs.libxslt ]"
- see https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/r-modules/default.nix

### Steps to reproduce

$ nix-shell -p rPackages.XML

[...]
checking for pkg-config... /nix/store/jklxb0jl7jchv79gkm49bhd9n6zh1a2i-pkg-config-0.29/bin/pkg-config
checking for xml2-config... no
Cannot find xml2-config
ERROR: configuration failed for package 'XML'
removing '/nix/store/gqff0m40s9466y4m4vdyypi2bilnf9p9-r-XML-3.98-1.4/library/XML'
builder for ‘/nix/store/cdgrcrfv7445m4hspvvfwh7mnr0d0bxr-r-XML-3.98-1.4.drv’ failed with exit code 1
error: build of ‘/nix/store/cdgrcrfv7445m4hspvvfwh7mnr0d0bxr-r-XML-3.98-1.4.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies

## Technical details

* System: 16.09.901.9902430 (Flounder)
* Nix version: 1.11.4
* Nixpkgs version: "16.09.901.9902430"

**Comment by vcunat** [comment]
I think b2113f78 would need backport to stable, and perhaps other changes. /cc @peti (author of most of late changes there)

There are a couple intriguing points for me:
- specifying `.dev` in *build inputs shouldn't be required &ndash; I suppose it's due to some non-standard overriding done;
- it seems like native and non-native inputs are switched &ndash; the expressions pass `.dev` etc. inputs as native and `pkgconfig` etc. as non-native.

**Comment by vcunat** [comment]
For the first point, I expect using the new `overrideAttrs` instead of `overrideDerivation` would solve the problem, though that one is *not* on 16.09 (but IMO it's non-intrusive enough to get backported).

**Comment by ibor** [comment]
As a note, overriding nativeBuildInputs (or buildInputs) to include pkgs.libxml2 (without .dev) does not help.

`myXML = pkgs.stdenv.lib.overrideDerivation pkgs.rPackages.XML (oldAttrs: { nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ pkgs.libxml2 ]; });`

**Comment by vcunat** [comment]
Well, the work-around used in the patch is to have it *with* `.dev`.

**Comment by ibor** [comment]
Oh sorry. However, adding `pkgs.libxml2.dev` in stable likewise does not help.

**Comment by matthewbauer** [comment]
No longer an issue for me. Feel free to reopen if it hasn't actually been fixed.
