### ISSUE TITLE
grub: debug output is unreproducible

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#201143]
Building the debug output of this package twice does not produce the bit-by-bit identical result each time. Fixing bit-by-bit reproducibility has various advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems. You can read more about this at https://reproducible-builds.org/ .

This case is particularly interesting because it is part of our milestone to build the complete build closure of nixos.iso_minimal.x86_64-linux reproducibly. It might also be worth looking into why a debug output is part of the build closure.

### Steps To Reproduce

`nix-build '<nixpkgs>' -A grub.debug` doesn't seem to work, so not sure how to reproduce this.

### Additional context

https://arnout.engelen.eu/nixos-iso-minimal-r13y/diff/b0e0fd3c3fc95dffbd3cfdf995fecb9f8c923b32146c1b2ac49f86f17c4d08ac-5337ba472efc43a651343b3d716371759cce92de9d07f4526e10d03be7e14672.html

**Comment by iblech** [comment]
I cannot reproduce this: `nixos/modules/system/boot/loader/grub/grub.nix` does not seem to include a `debug` output. However, the command I always used for creating an ISO image, `nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=...` currently fails (`error: builder for '/nix/store/qci7qk64355i68ijzkhxkik69akdjzmv-squashfs.img.drv' failed with exit code 1`), hence I cannot test any further. Is this just me?

**Comment by raboof** [comment]
> I cannot reproduce this: `nixos/modules/system/boot/loader/grub/grub.nix` does not seem to include a `debug` output.

Oops, sorry about that, indeed `nix-build '<nixpkgs>' -A grub.debug` does not work :/

> Also, creating an ISO image using `nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=...` does not pull in any `grub-2.06-debug`-like paths in the Nix store.

You can find the derivations with `nix-store -q --requisites $(nix-instantiate ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux) | grep grub`: this returns 3 results: the source and two derivations.

Then you can build them with `nix-build /path/to/drv -A debug`. Sorry about the detour!

**Comment by raboof** [comment]
I can reproduce the problem with `nix-build '<nixpkgs>' -A grub2.debug --check --keep-failed`

Or also: `nix-build /nix/store/hash-for-grub-2.06.drv\!debug --check --keep-failed`

**Comment by raboof** [comment]
so, both /nix/store/07bws5lfvgz0a6psxbyhzzz0sbrnqdab-grub-2.06/lib/grub/i386-pc/kernel.img and /nix/store/07bws5lfvgz0a6psxbyhzzz0sbrnqdab-grub-2.06/lib/grub/i386-pc/kernel.exec have the same build id (02cf30971fcd392b489a3449e75101961d017adc). My guess is we need something like:

```
diff --git a/pkgs/build-support/setup-hooks/separate-debug-info.sh b/pkgs/build-support/setup-hooks/separate-debug-info.sh
index ca651b4393a..516a22ab143 100644
--- a/pkgs/build-support/setup-hooks/separate-debug-info.sh
+++ b/pkgs/build-support/setup-hooks/separate-debug-info.sh
@@ -41,5 +41,5 @@ _separateDebugInfo() {
             # Also a create a symlink <original-name>.debug.
             ln -sfn ".build-id/${id:0:2}/${id:2}.debug" "$dst/../$(basename "$i")"
         ) || rmdir -p "$dst/${id:0:2}"
-    done < <(find "$prefix" -type f -print0)
+    done < <(find "$prefix" -type f -print0 | sort)
 }
```

... and maybe print a warning in this case
