### ISSUE TITLE
python3Packages.pip: unreproducible vendored .exe files

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#201146]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A ... --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A ...)
```

### Additional context

https://arnout.engelen.eu/nixos-iso-minimal-r13y/diff/ffa37e4adce50539c65c4062f803e2c6d34fda37c2061b039db029123d3942e9-a645067984e633a18d01c8de9eb2a0929ef47d6586e1b92e7cd878c24415aa0d.html

Also seen in https://github.com/NixOS/nixpkgs/issues/192728

**Comment by rnhmjoj** [comment]
Why does a Linux package contain Windows PE binaries in the first place? What are they for?
