### ISSUE TITLE
nixos-rebuild: adding a space to time.timeZone breaks NixOS

### ISSUE THREAD

**Issue by dunn** [NixOS/nixpkgs#20115]
## Issue description

An invalid timezone value can cause NixOS to crash.

### Steps to reproduce

1. Add `time.timeZone = "America/Los Angeles"` to `/etc/nixos/configuration.nix`
2. `nixos-rebuild switch`

The window manager will crash if it is running, and in three out of four attempts to reproduce, the system will become unresponsive.  After doing a hard reboot, starting up with the default configuration will cause systemd to freeze:
```
[ 12.725406 ] systemd[1456]: Failed to execute /etc/systemd/system-generators/cpufreq.service: Permission denied
.... # many more like the above
[ 13.110838 ] systemd[1]: Failed to load default target: No such file or directory
[ 13.110960 ] systemd[1]: Failed to load rescue target: No such file or directory
[!!!!!!] Failed to load rescue target, freezing.
[ 13.111562 ] systemd[1]: Freezing execution
```

Recovering the system requires booting into a previous configuration.

## Technical details

* System: `16.09.892.cc29d3d (Flounder)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `"16.09.892.cc29d3d"`

**Comment by rycee** [comment]
Maybe something like
```patch
diff --git a/nixos/modules/config/timezone.nix b/nixos/modules/config/timezone.nix
index 39a4504..4ea75f2 100644
--- a/nixos/modules/config/timezone.nix
+++ b/nixos/modules/config/timezone.nix
@@ -41,9 +41,12 @@ in
     systemd.globalEnvironment.TZDIR = tzdir;
 
     environment.etc.localtime =
-      { source = "/etc/zoneinfo/${config.time.timeZone}";
-        mode = "direct-symlink";
-      };
+      let
+        tzFile = builtins.replaceStrings [" "] ["_"] config.time.timeZone;
+      in
+        { source = "/etc/zoneinfo/${tzFile}";
+          mode = "direct-symlink";
+        };
 
     environment.etc.zoneinfo.source = tzdir;
```
could help?

**Comment by ericsagnes** [comment]
`time.timeZone` should be made a `types.enum` or at least have a `check` function that check the value set is a valid timezone.

**Comment by c0bw3b** [comment]
@dunn can this issue be closed? 

PR #30258 will prevent it from now on.

**Comment by dunn** [comment]
I guess so! Thank you all!
