### ISSUE TITLE
haskellPackages.map-syntax is broken in master

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#20127]
When I try to install `haskellPackages.map-syntax` on the master branch I get the following error:

```
output path ‘/nix/store/xb56ijb247nqsyz569s4j311skir2sa4-map-syntax-0.2.0.1-r1.cabal’ has sha256 hash ‘0xl0236s9vmaayawknvyrcyjczi3hq9833896c360qm8763wvmlq’ when ‘16261kpz4himb452j6hrnflihcbcglwan9xjjpfk7l3wv6qd65qy’ was expected
killing process 10608
cannot build derivation ‘/nix/store/kw9bjdpdsmi4j30zrm7x9g5kz6xgiil2-map-syntax-0.2.0.1.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/kw9bjdpdsmi4j30zrm7x9g5kz6xgiil2-map-syntax-0.2.0.1.drv’ failed
```

`git bisect` tells me that the faulty commit is e0ef9e9.
But I'm surprised to see this kind of error as the commit was generated by `hackage2nix`.

Tagging @peti as the author of the problematic commit.

**Comment by peti** [comment]
It appears that this file was changed on Hackage! The re-generated file in https://github.com/peti/nixpkgs/tree/haskell-updates has the correct hash. I'll merge that to `master` in a minute.
