### ISSUE TITLE
Darwin opensource packages are no longer available

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nixpkgs#201348]
###### Project name
This is in the file: `pkgs/os-specific/darwin/apple-source-releases/macos-11.0.1.nix`

###### Notify maintainers

maintainers: ???

###### Note for maintainers

`bootstrap_cmds`, for example, is given at version 121, but fails to download from every machine I've tried:
```
wget http://www.opensource.apple.com/tarballs/bootstrap_cmds/bootstrap_cmds-121.tar.gz
```

**Comment by jwiegley** [comment]
The files are there, but the hashes don't seem to match:
```
error: hash mismatch in fixed-output derivation '/nix/store/97mpz3g7vb4lppnx9qjqm6lzh4i0794j-bootstrap_cmds-121.tar.gz.drv':
         specified: sha256-2w3a8RDyOIUrA7q9StWqZLY2I3Fl4ORnWL0pozllfCU=
            got:    sha256-dJmwRgUoBilkfgEeebsJBTbB/YqSHPtSrbifLSN/62E=
error: hash mismatch in fixed-output derivation '/nix/store/xm511ckrrry02h9lz9qvykslz2lv1c1g-dyld-433.5.tar.gz.drv':
         specified: sha256-E+Nw7RLBN/AVOpa6sS4dRoltsH+KQLrGsFKVhc6skmA=
            got:    sha256-JmKnOZtBPf96zEx7vhYHLBSTOPyKN71IdYE3R0IeJww=
error: hash mismatch in fixed-output derivation '/nix/store/26xsr9mk5kn5s725pv0g0406m11fjj5q-ICU-66108.tar.gz.drv':
         specified: sha256-HeJ7DLeDFzlYl5ZLu5xi2dVOn7akSuU6lX/yi71n5rQ=
            got:    sha256-p3CYITMljHVuwijeYnUbKaIWp/xPC4/hg1G1lO6PlFU=
error: hash mismatch in fixed-output derivation '/nix/store/la3mhpmx6p7rihvvg8rrr36mf2gr4abl-libiconv-50.tar.gz.drv':
         specified: sha256-nlqgZNZHhqKJRN6eAqn5uEpS9O9+H7ThCgVNjb6B5b0=
            got:    sha256-ZzPFkchK3EU95UQUVVrR0t8iilhi/VnIkjjtP6KT2oI=
```

**Comment by jwiegley** [comment]
I also tried with `archive` instead of `archive/refs/tags`.

**Comment by Artturin** [comment]
Github archives are a bit different so perhaps it's because of that

If someone can get the old source then running diffoscope on the extracted files should be enough to verify they're the same

**Comment by wegank** [comment]
The old source is available on web.archive.org ([link](https://web.archive.org/web/20221012012431/http://www.opensource.apple.com/tarballs/bootstrap_cmds/bootstrap_cmds-121.tar.gz)). Verified that they're the same.

**Comment by billksun** [comment]
@jwiegley, were you able to have this issue resolved? One of my coworkers using an Intel MBP just hit the hash mismatch problem with `dyld`, is there a workaround?

**Comment by jwiegley** [comment]
It's not resolved for me, what I discovered is that building with certain flags on my macOS box caused it to requires different dependencies. Once I eliminated that, it didn't need the dependencies which led to the missing artifacts.

**Comment by billksun** [comment]
> It's not resolved for me, what I discovered is that building with certain flags on my macOS box caused it to requires different dependencies. Once I eliminated that, it didn't need the dependencies which led to the missing artifacts.

@jwiegley, what flags did you disable?

**Comment by jwiegley** [comment]
This is going to sound really strange, but the difference is whether I use `--substituters ssh://hermes` to pull package from my laptop. With that, I get lots of errors about hash mismatches on core Apple packages; without that option, everything builds fine.

**Comment by animusnull** [comment]
I've not used a patch like this before. What's the best way to apply this patch, or the pr to a local derivation?  I was trying a `pkgs.callPackages` which I don't is the right approach.
