### ISSUE TITLE
gnome-keyring: 100%CPU since glib 2.74.1

### ISSUE THREAD

**Issue by pschyska** [NixOS/nixpkgs#201324]
### Describe the bug
Since glib 2.74.1 (https://github.com/NixOS/nixpkgs/commit/0b5be61ca10651c60fb762e4332d9725a5cc4624), gnome-keyring via PAM
(`session optional …gnome-keyring-42.1/lib/security/pam_gnome_keyring.so auto_start`) gets stuck at 100%CPU usage without appearent reason. AFAICT it works correctly (the user-session instance, e.g. via DBUS, successfully unlocks the login keyring with the user's password).

### Steps To Reproduce
```nix
{
  security.pam.services.login.enableGnomeKeyring = true;

  systemd.user = {
    # Eagerly start gnome-keyring to not time out the pam daemon when we don't start a
    # consumer in time.
    services.gnome-keyring = {
      serviceConfig.Type = "dbus";
      serviceConfig.BusName = "org.gnome.keyring";
      serviceConfig.Restart = "on-failure";

      script =
        "/run/wrappers/bin/gnome-keyring-daemon --start --foreground --components=secrets";
    };
    # To wait until pam instance has started.
    paths.gnome-keyring = {
      wantedBy = [ "default.target" ];
      partOf = [ "default.target" ];
      pathConfig = { PathExists = "%t/keyring/control"; };
      unitConfig = { ConditionUser = "…"; };
    };
  };
}
```

### Additional context
Problems disappears when overriding gnome-keyring with the glib version before 0b5be61ca10651c60fb762e4332d9725a5cc4624.

### Notify maintainers
@bobby285271
@hedning
@jtojnar
@dasj19
@maxeaubrey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.8, NixOS, 22.11 (Raccoon), 22.11.20221113.fc07622`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by bobby285271** [comment]
I guess https://github.com/NixOS/nixpkgs/pull/201229 should fix this? :thinking:

**Comment by pschyska** [comment]
hey @bobby285271, thanks for the quick response, and sorry that your PR slipped my attention. I probably didn't search for issues correctly.

I "recreated" your patch with the following overlay (on top of github:nixos/nixpkgs/fc07622617a373a742ed96d4dd536849d4bc1ec6) and can confirm it fixes my gnome-keyring issue:

```nix
final: prev: {
  gnome = prev.gnome // {
    gnome-keyring = (prev.gnome.gnome-keyring.override {
      glib = prev.glib.overrideAttrs (a: rec {
        patches = a.patches ++ [
          (final.fetchpatch {
            url =
              "https://gitlab.gnome.org/GNOME/glib/-/commit/2a36bb4b7e46f9ac043561c61f9a790786a5440c.patch";
            sha256 = "b77Hxt6WiLxIGqgAj9ZubzPWrWmorcUOEe/dp01BcXA=";
          })
        ];
      });
    });
  };
}
```

I'm gonna stick with that until the massive rebuild is done as this appears in nixos-unstable 🙂 

Side note because I realized I had a gnome-keyring overlay since a while that I stumbled over again investigating this:
```nix
.overrideAttrs (a: {
      NIX_CFLAGS_COMPILE =
        ''-DGNOME_KEYRING_DAEMON="/run/wrappers/bin/gnome-keyring-daemon"'';
    })
```
I think without that that pam daemon would spawn "$out/bin/gnome-keyring-daemon" w/o `cap_ipc_lock=ep` and IIRC there was some warning about insecure memory being used. Is that something you considered and worthwhile to open a PR for it?

**Comment by 06kellyjac** [comment]
I think the `cap_ipc_lock=ep` part is resolved by `nixos/modules/services/desktops/gnome/gnome-keyring.nix`

**Comment by pschyska** [comment]
@06kellyjac It is not, because `pam_gnome_keyring.so` doesn't use the commandlines in `$out/etc/xdg/autostart/* $out/share/dbus-1/services/*` that are patched in `gnome-keyring.nix`.

They are running the binary directly from `$PREFIX/bin/gnome-keyring-daemon`, (which is `/nix/store/…-gnome-keyring-42.1`), or use `GNOME_KEYRING_DAEMON` when it is defined.

**Comment by pschyska** [comment]
> I see. is there an issue tracking this?

No, I'll open a PR this weekend.
