### ISSUE TITLE
kubecolor `0.0.20` has a `0.0.21` fork

### ISSUE THREAD

**Issue by senges** [NixOS/nixpkgs#201330]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: kubecolor

current version: 0.0.20
desired version: 0.0.21

###### Notify maintainers

maintainers: @ivankovnatsky @SuperSandro2000
new repo maintainer : @prune998

###### Note for maintainers

Original [hidetatz/kubecolor](https://github.com/hidetatz/kubecolor) repo remains unmaintained and current version (`0.0.20`) faces few behavior problems, for example alias completion is half-broken on Zsh.
A fork [kubecolor/kubecolor](https://github.com/kubecolor/kubecolor) is working on these issues, that seems to be fixed for me in the new release `0.0.21`.

Maybe switching to the main kubecolor fork could be considered a good mid-long term solution ?

Thanks alot :pray:

**Comment by prune998** [comment]
Do I have to do anything for this to happen  ?

**Comment by prusnak** [comment]
> Do I have to do anything for this to happen ?

No, thanks

Update in PR https://github.com/NixOS/nixpkgs/pull/201334

**Comment by SuperSandro2000** [comment]
Refined GitHub messed up that fixed 😂
