### ISSUE TITLE
ZSH getent

### ISSUE THREAD

**Issue by tomberek** [NixOS/nixpkgs#20138]
## Issue description

The `getent` command is replaced by zsh with a function. In share/zsh/5.2/function/compaudit there is a check

```
[[ -x /usr/bin/getent ]] || getent() {
...etc
```

Should we just undefine that function or is this better to address with upstream?

### Steps to reproduce

Use zsh on a machine where getent is not at that location.

## Technical details

* System: (NixOS: 17.03.git.ad50658)
* Nix version: (1.11.4)
* Nixpkgs version: 17.03pre94694.fa4167c

**Comment by Mic92** [comment]
This could be rewritten as:

```
[[ -n ${commands[getent]} ]] || getent() {
```

**Comment by tomberek** [comment]
@Mic92 I sent your suggestion to upstream.

**Comment by tomberek** [comment]
Upstream'ed: https://github.com/zsh-users/zsh/commit/c282abc6bd9bbc6dc204d217d8e94ea4565e68ca
