### ISSUE TITLE
building python twisted fails to build on aarch64-darwin when running twisted.trial

### ISSUE THREAD

**Issue by spott** [NixOS/nixpkgs#201436]
### Describe the bug
Python twisted won't install on a M1 MacBook Pro.

### Steps To Reproduce
See attached gist: https://gist.github.com/spott/9bf63c1d47d0904ab98dcf461ae2c464 for flake.nix and flake.lock

Python twisted build errors out with the `Trace/BPT trap: 5` error when running `python3.10 -m twisted.trial twisted`.

This happens when build is attempted using python 3.9 or python 3.10 (shown), on aarch64-darwin, with (shown) or without the `pkgsx86_64Darwin` package function.

### Expected behavior
Twisted installs.

### Notify maintainers
@SuperSandro2000

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixpkgs"`
 - channels(spott): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by SuperSandro2000** [comment]
works now
