### ISSUE TITLE
zotero installs x86_64 binaries on aarch64

### ISSUE THREAD

**Issue by vilvo** [NixOS/nixpkgs#201454]
### Describe the bug

Trying to run zotero from unstable on macbook m1 fails. Tries to execute x86_64 architecture binaries on aarch64.

### Steps To Reproduce
1. 
```console
$ sudo nix-channel --list 
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

2. 
```console
$ nix-env -i zotero
installing 'zotero-6.0.16'
...
``` 
3.
 
```console
$ zotero
/nix/store/isq4zqdrsp9vzq9707y8vwafyak2rg2g-zotero-6.0.16/bin/.zotero-wrapped: line 13: /nix/store/isq4zqdrsp9vzq9707y8vwafyak2rg2g-zotero-6.0.16/usr/lib/zotero-bin-6.0.16/zotero-bin: cannot execute binary file: Exec format error
$ file /nix/store/isq4zqdrsp9vzq9707y8vwafyak2rg2g-zotero-6.0.16/usr/lib/zotero-bin-6.0.16/zotero-bin
/nix/store/isq4zqdrsp9vzq9707y8vwafyak2rg2g-zotero-6.0.16/usr/lib/zotero-bin-6.0.16/zotero-bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/g14swv4f0rg83naqj87g1mjmyvrmrxmf-glibc-2.35-163/lib/ld-linux-aarch64.so.1, for GNU/Linux 2.6.26, BuildID[sha1]=f34d317495486bc5a1d99c97565dbda17d513147, stripped
$ uname -a
Linux asahi 5.19.0-asahi-5-1-ARCH #1 SMP PREEMPT_DYNAMIC Sat, 20 Aug 2022 09:23:11 +0000 aarch64 GNU/Linux
```

### Expected behavior
Install aarch64 build of zotero on aarch64 architecture machines.

### Additional context
Nix packaging prebuilt x86_64 binaries from upstream is intentional but the packaging does not limit architecture to x86_64 only:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/office/zotero/default.nix#L48

### Notify maintainers
@i077

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"aarch64-linux"`
 - host os: `Linux 5.19.0-asahi-5-1-ARCH, Arch Linux ARM, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by i077** [comment]
Oh, looks like the `src` in the derivation is fetching the x86_64 source, regardless of architecture. I'm not so sure Zotero has official builds for aarch64-linux, but you can use AUR's [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zotero) and Zotero's [build instructions](https://www.zotero.org/support/dev/client_coding/building_the_standalone_client).

Unfortunately I no longer have access to a Linux machine with a desktop environment, so I'm not really able to test this out.

Also related: #145438

**Comment by kouyk** [comment]
> Unfortunately I no longer have access to a Linux machine with a desktop environment, so I'm not really able to test this out.

Are you still maintaining the package in this case? Or should someone try to takeover?

**Comment by i077** [comment]
> Are you still maintaining the package in this case? Or should someone try to takeover?

It would probably be best if someone else took over maintaining this package.
