### ISSUE TITLE
haskellPackages.download-curl needs to use a new revision

### ISSUE THREAD

**Issue by neilmayhew** [NixOS/nixpkgs#20141]
## Issue description

`haskellPackages.download-curl` no longer builds. This is a result of `tagsoup` being updated to 0.14 back in July (`641fc0e`). The revision-1 cabal file for `download-curl` specifies `< 0.14`. I persuaded one of the Hackage trustees to add a revision 2 today to take care of this, so I think someone just needs to regenerate the package list from Hackage.

I'm not sure why no-one's noticed this before. I have a project that depends on `download-curl`, but I hadn't tried to build it since July's `tagsoup` change.

### Steps to reproduce

```
$ nix-shell -p haskellPackages.download-curl
```

The output is:

```
these derivations will be built:
  /nix/store/4vgh2kj0y5vqi3fbi8h2ay0x7xxrwi94-download-curl-0.1.4.drv
building path(s) ‘/nix/store/aps99krpyzs1lli2dg6i5vmwvlk03jv2-download-curl-0.1.4’
setupCompilerEnvironmentPhase
Build with /nix/store/njls663z633511jlz0pf79v98az32x2n-ghc-8.0.1.
unpacking sources
unpacking source archive /nix/store/gaq55pj3sijqa1iv6bi2zbj92k29s5mp-download-curl-0.1.4.tar.gz
source root is download-curl-0.1.4
setting SOURCE_DATE_EPOCH to timestamp 1331047344 of file download-curl-0.1.4/Setup.lhs
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/download-curl-0.1.4/revision/1.cabal.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-download-curl-0.1.4.drv-0/package.conf.d -j5 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-download-curl-0.1.4.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/aps99krpyzs1lli2dg6i5vmwvlk03jv2-download-curl-0.1.4 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-download-curl-0.1.4.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/aps99krpyzs1lli2dg6i5vmwvlk03jv2-download-curl-0.1.4/lib/ghc-8.0.1/download-curl-0.1.4 --enable-split-objs --disable-library-profiling --disable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring download-curl-0.1.4...
Setup: Encountered missing dependencies:
tagsoup >=0.8 && <0.14
builder for ‘/nix/store/4vgh2kj0y5vqi3fbi8h2ay0x7xxrwi94-download-curl-0.1.4.drv’ failed with exit code 1
error: build of ‘/nix/store/4vgh2kj0y5vqi3fbi8h2ay0x7xxrwi94-download-curl-0.1.4.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

## Technical details

* System: NixOS 16.09.909.238c7e0
* Nix version: 1.11.4
* Nixpkgs version: 16.09.909.238c7e0

**Comment by joachifm** [comment]
The package set is regenerated at regular intervals, so if this is fixed upstream it will be fixed by itself here as well.

**Comment by neilmayhew** [comment]
@joachifm OK, thanks for explaining that. Is the schedule for the regeneration published anywhere? I'd like to know whether it's worth my setting up a modified derivation of `download-curl` so I can build my own project. If it's going to happen only a few days from now then I won't bother.

**Comment by joachifm** [comment]
@neilmayhew I don't know the schedule (or if there actually is a fixed schedule  ), @peti knows.

**Comment by peti** [comment]
I merge updates approx. once per week from https://github.com/peti/nixpkgs/tree/haskell-updates (which is updated hourly) to master.

**Comment by neilmayhew** [comment]
@peti Thanks, that's helpful. I can wait that long.

I'm curious to know, though, why the breakage wasn't detected before. I assume the `download-curl` derivation hasn't been building since the upgrade of `tagsoup` in July. Do we just ignore breakages like this, and wait for someone to decide to do something about it? I imagine a lot of Hackage packages are broken at any one time, due to the widespread fragility of upper bounds.

**Comment by neilmayhew** [comment]
@joachifm, @peti What do I need to do to request that this be fixed in `release-16.09` as well as `master`? I assume that's more complicated because we may not want to bring every Hackage change into 16.09. Should I create a pull request with that one change to `hackage-packages.nix`?

**Comment by peti** [comment]
The new version is available in `master` already. For `release-16.09`, a PR that modifies `hackage-packages.nix` is probably a good-enough solution. These manual changes will be overwritten when `release-16.09` is updated the next time, but that won't hurt anyone.

**Comment by neilmayhew** [comment]
@peti Thanks for the input. I've done as you suggest.
