### ISSUE TITLE
sourcehut: many missing /query-locations for nginx config

### ISSUE THREAD

**Issue by selkie-diligent** [NixOS/nixpkgs#201424]
### Describe the bug
On 5f588eb4a958f1a526ed8da02d6ea1bea0047b9f (nixos-unstable) the `services/misc/sourcehut`-module is missing most of the nginx `/query`-locations for the `*-api`-services (e.g git, hg, builds, paste, man, list, hub, todo) and therefore is not functioning.
Similar to how it is already defined for the metasrht-api, https://github.com/NixOS/nixpkgs/blob/5f588eb4a958f1a526ed8da02d6ea1bea0047b9f/nixos/modules/services/misc/sourcehut/default.nix#L1314-L1332

### Notify maintainers

@tomberek

**Comment by christoph-heiss** [comment]
This was fixed with #245394.
