### ISSUE TITLE
cjdns needs grsec permissions added

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20146]
## Issue description
grsec stops cjdns from working  without 'setcap "cap_net_admin+eip cap_net_raw+eip" cjdroute".

**Comment by spacekitteh** [comment]
@joachifm

**Comment by spacekitteh** [comment]
Also possibly paxflags on the nodejs if that's not done already.

[This video](https://vimeo.com/130200697) shows setting up cjdns on grsec'd debian machine.

**Comment by joachifm** [comment]
Nodejs is covered by https://github.com/NixOS/nixpkgs/pull/19951. As for setcap, cjdns currently runs as root. I'd think that setcap would be required for running as non-root regardless of grsec.

**Comment by spacekitteh** [comment]
Yikes, the number of things which run as root is scary.

**Comment by joachifm** [comment]
Yep. You can reign in the caps via the `serviceConfig.CapabilityBoundingSet` option and related options (or via MAC of course).
