### ISSUE TITLE
services.thermald.configFile option always ignored due to --adaptive flag

### ISSUE THREAD

**Issue by Yeshey** [NixOS/nixpkgs#201402]
### Describe the bug
Even when services.thermald.configFile is specified, it is ignored due to [--adaptive being passed](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/nixos/modules/services/hardware/thermald.nix), according to `man thermald`:
```
       --adaptive
              Use DPTF adaptive tables when present. This will ignore thermald config via xml files.
```

### Steps To Reproduce
```nix
  services.thermald = {
    enable = true;
    configFile = ./configFiles/thermal-conf.xml; 
  };
```

### Expected Behavior
thermald service uses the config File

### Notify maintainers
CC: @rapenne-s 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.11, NixOS, 22.11 (Raccoon), 22.11.20221003.fd54651`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(yeshey): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

## Possible Fixes

1. The documentation on thermald is very sparse so I can't say for sure what removing  --adaptive would do when there is no configFile, but that might be an answer.
2. Changing the line with `--adaptive` (line 52 of [thermald.nix file](https://github.com/NixOS/nixpkgs/blob/nixos-22.05/nixos/modules/services/hardware/thermald.nix))to something like:
```
${optionalString (cfg.configFile == null) "--adaptive"} 
```
So when there is no configFile it still starts with that option. This is untested!

**Comment by Yeshey** [comment]
If I was more knowledgeable and knew how to make a testing environment I could submit a pull request, but in the meantime for people who get here, to circumvent this, I have in my configuration file:
```nix
  services.thermald = {
    debug = false;
    enable = true;
    configFile = ./configFiles/thermal-conf.xml; #(https://github.com/linux-surface/linux-surface/blob/master/contrib/thermald/thermal-conf.xml)
  };
  systemd.services.thermald.serviceConfig.ExecStart = let # running with --adaptive ignores the config file. (issue https://github.com/NixOS/nixpkgs/issues/201402)
    cfg = config.services.thermald;
  in lib.mkForce ''
          ${cfg.package}/sbin/thermald \
            --no-daemon \
            --config-file ${location}/hosts/surface/configFiles/thermal-conf.xml \
        '';
```

with the path to your config file

**Comment by jian-lin** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/310819
