### ISSUE TITLE
nimble refresh throws errors about invalid certificates

### ISSUE THREAD

**Issue by CGenie** [NixOS/nixpkgs#201456]
### Describe the bug

I install `nim` from upstream repos and I get this error:

```
nimble refresh
Downloading Official package list
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Failed to verify the SSL certificate for https://github.com/nim-lang/packages/raw/master/packages.json
      Hint: Use --noSSLCheck to ignore this error.
```

### Additional context

A recent discussion on Discord

https://discord.com/channels/371759389889003530/753721959308853319/1042028868158099537

revealed that one should use openssl-1.1 instead of 3.x. And indeed, `nix repl` shows this:

```
nix-repl> openssl
«derivation /nix/store/pw9ysk9rzxxqv67cz0jj0b9c78lkqwl9-openssl-3.0.7.drv»

nix-repl> nim     
«derivation /nix/store/c77cnicmvicvs5v908fmvpwhff6j8fqc-x86_64-unknown-linux-gnu-nim-wrapper-1.6.8.drv»
```

I guess with nix this is easy to change.

### Notify maintainers

@shassard @malob @FRidh @ehmry 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-46-generic, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(przemek): `"nixpkgs"`
 - nixpkgs: `/home/przemek/.nix-defexpr/channels/nixpkgs`
```

**Comment by ehmry** [comment]
I consider this an upstream problem and they should link instead of using `dlload` at runtime. Patches on our side are still welcome.

**Comment by huantianad** [comment]
Hm weird I can't seem to reproduce this:
```
> nix shell nixpkgs#nim -c nimble refresh
Downloading Official package list
    Success Package list downloaded.
```
Am I missing something?

**Comment by ehmry** [comment]
Fixed at https://github.com/nim-lang/Nim/pull/20669

**Comment by towry** [comment]
![截屏2024-07-09 10 58 33](https://github.com/NixOS/nixpkgs/assets/8279858/714b9b34-f9b4-45e9-a3ef-a6b67bc5b405)

**Comment by ehmry** [comment]
Paste text not images.

**Comment by towry** [comment]
Why?

**Comment by towry** [comment]
Fixed by installing nimble with choosenim.

```
nimble v0.14.2 compiled at 2024-07-09 04:56:57
git hash: couldn't determine git hash
```
