### ISSUE TITLE
sourcehut: gitsrht-api no write permissions for repos directory

### ISSUE THREAD

**Issue by selkie-diligent** [NixOS/nixpkgs#201425]
### Describe the bug
On 5f588eb4a958f1a526ed8da02d6ea1bea0047b9f (nixos-unstable) in the `services/misc/sourcehut`-module the service file `gitsrht-api.service` https://github.com/NixOS/nixpkgs/blob/5f588eb4a958f1a526ed8da02d6ea1bea0047b9f/nixos/modules/services/misc/sourcehut/default.nix#L1101-L1104
is missing a `serviceConfig.BindPaths = [ "${cfg.settings."git.sr.ht".repos}:/var/lib/sourcehut/gitsrht/repos" ];` and thus has no write permissions.

### Steps To Reproduce
1. Setup sourcehut with gitsrht
2. Try to create a repository

### Additional context
The web-frontend does not return an error message. However, you can also use the API directly by using curl and a _personal access token_ and it will return `{"errors": [{"reason": "mkdir /var/lib: read-only file system"}]}`.

### Notify maintainers

@tomberek

**Comment by christoph-heiss** [comment]
This was fixed with #245394.
