### ISSUE TITLE
flutter: Packaging the Flutter engine

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#201574]
**Project description**
At the moment, the Flutter package uses the prebuilt engine from Google, downloaded by the SDK.
This is not ideal, as prebuilt engine artifacts require patching for Nix(OS) compatibility.

It'd be great if we could build the Flutter engine from source.

Useful references:

- https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
- https://github.com/flutter/flutter/wiki/Compiling-the-engine
- https://github.com/flutter/engine/blob/dda667f8f093599e99a81124fc5b578fe9b13134/CONTRIBUTING.md

**Metadata**

* homepage URL: https://github.com/flutter/engine
* source URL: https://github.com/flutter/engine
* license: bsd
* platforms: linux, darwin

(cc: @mkg20001 @dotlambda)

**Comment by hacker1024** [comment]
I'm running into issues with Google's `gclient` syncing tool. It's configured to use SSH remotes, but GitHub do not allow anonymous SSH clones.

Does anyone know of a way to work around this problem?

<details>
<summary>What I have so far</summary>

```nix
{ stdenv
, lib
, fetchgit
, fetchFromGitHub
, writeText
, writeShellScriptBin
, python310
, git
, openssh
}:
let
  depot_tools = fetchgit {
    url = "https://chromium.googlesource.com/chromium/tools/depot_tools.git";
    rev = "25cf78395cd77e11b13c1bd26124e0a586c19166";
    sha256 = "0r8yk95driva36yy9swmw6z0pfxihpkcs67wr5dqmhdygnljnza2";
  };
  gclient = writeShellScriptBin "gclient" ''
    ${python310.withPackages (py: with py; [ google-auth-httplib2 ])}/bin/python ${depot_tools}/gclient.py "$@"
  '';
  ssh = writeShellScriptBin "ssh" ''
    if [ ! -f id_rsa ]; then
      ${openssh}/bin/ssh-keygen -t rsa -N "" -f id_rsa > /dev/null
    fi
    ${openssh}/bin/ssh -i id_rsa.pub -o StrictHostKeyChecking=no "$@"
  '';

  src = stdenv.mkDerivation rec {
    pname = "flutter-engine-sources";
    version = "857bd6b74c5eb56151bfafe91e7fa6a82b6fee25";

    nativeBuildInputs = [ gclient git ssh ];

    unpackPhase = ''
      runHook preUnpack

      mkdir engine && cd engine
      ln -s ${
        writeText ".gclient" ''
          solutions = [
            {
              "managed": False,
              "name": "src/flutter",
              "url": "git@github.com:flutter/engine.git@${version}",
              "custom_deps": {},
              "deps_file": "DEPS",
              "safesync_url": "",
            },
          ]
        ''
      } .gclient
      gclient sync

      runHook postUnpack
    '';

    outputHashAlgo = "sha256";
    outputHash = lib.fakeSha256;
  };
in

stdenv.mkDerivation {
  pname = "flutter-engine";
  inherit (src) version;

  inherit src;
}
```
</details>

**Comment by milahu** [comment]
> * https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment

misleading

we just need
https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux

a bit cleaned up

```nix
/*
https://github.com/NixOS/nixpkgs/issues/201574
*/

{ stdenv
, lib
, fetchgit
, fetchFromGitHub
, writeShellScriptBin
, python3
, git
, cacert
, ninja
}:

let
  # TODO buildPythonPackage
  # https://github.com/input-output-hk/gclient2nix
  # https://discourse.nixos.org/t/installing-depot-tools/5134
  depot_tools = fetchgit {
    url = "https://chromium.googlesource.com/chromium/tools/depot_tools";
    rev = "30e3ce8b1c670be00c4957fe773ffb8ff986ed8f";
    sha256 = "sha256-R9CX/xzvLiOVQmAsviTFUFv6DiStxa0b6O0zHNaH6SY=";
  };
  gclient = writeShellScriptBin "gclient" ''
    ${python3.withPackages (py: with py; [ google-auth-httplib2 ])}/bin/python ${depot_tools}/gclient.py "$@"
  '';
in

stdenv.mkDerivation rec {
  pname = "flutter-engine";
  version = "unstable-2022-11-21";

  # https://github.com/flutter/engine
  src = fetchFromGitHub {
    owner = "flutter";
    repo = "engine";
    # last passing test
    rev = "981fe92ab998d655abded58f1f0ef2a8daeadd02";
    sha256 = "sha256-9uY7Q8ZR51vB7vsjEPGAWyvhOKRfdj5B8o0KwypwdTY=";
  };

  deps = stdenv.mkDerivation {
    inherit src;
    name = "${pname}-${version}-deps";
    nativeBuildInputs = [
      gclient
      git
      cacert # fix: error:16000069:STORE routines::unregistered scheme
    ];
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    outputHash = ""; # TODO
    # "gclient sync" will take some time ... seems to hang, but should work
    #    gclient sync --revision src@${version} --shallow --verbose # TODO?
    # TODO copy less? copy only some folders, then merge with source
    buildPhase = ''
      (
        set -x
        gclient config https://github.com/flutter/engine
        gclient sync --revision src@${version} --verbose
        cp -r . $out
      )
    '';
  };

  postUnpack = ''
    (
      cd $sourceRoot
      echo TODO merge with source. copy or symlink ${deps}
      exit 1
    )
  '';

  nativeBuildInputs = [
    ninja
  ];

  /*
    TODO
    https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux
    this will take forever ...
  */
  buildPhase = ''
    ./flutter/tools/gn --unoptimized # to prepare your build files.
    ninja -C out/host_debug_unopt # to build a desktop unoptimized binary.
  '';
}
```

**Comment by silvergasp** [comment]
I came here as I'm currently looking to package google/pigweed using nix (via a search for cipd). I think cipd can be built from source relatively easily and could potentially be packaged in nix itself. e.g.

`go get go.chromium.org/luci/cipd/client/cipd`

Will fetch and build cipd.

**Comment by milahu** [comment]
building cipd with buildGoModule is like 20 lines of nix code
but so far we dont need cipd in nixpkgs

https://nixos.wiki/wiki/Go
https://ryantm.github.io/nixpkgs/languages-frameworks/go/

**Comment by hacker1024** [comment]
I didn't realize that cipd was a simple Go program, but I did notice that it was statically linked.

I've been retrieving it by parsing the depot_tools version metadata like so:

```dart
let
  depot_tools = fetchgit {
    url = "https://chromium.googlesource.com/chromium/tools/depot_tools.git";
    rev = "25cf78395cd77e11b13c1bd26124e0a586c19166";
    sha256 = "sha256-Qn0rqX2+wYpbyfwYzeaFsbsLvuGV6+S9GWrH3EqaHmU=";
  };
  cipd =
    let
      cipdVersion = builtins.readFile "${depot_tools}/cipd_client_version";
      cipdHashes = builtins.listToAttrs (
        map
          (line:
            let
              segments = builtins.split " +" line;
            in
            { name = builtins.head segments; value = lib.last segments; })
          (lib.filter (line: !(lib.hasPrefix "#" line || line == "")) (lib.splitString "\n" (builtins.readFile "${depot_tools}/cipd_client_version.digests")))
      );
      cipdPlatform =
        if stdenv.isDarwin then
          (if stdenv.isAarch64 then "mac-arm64" else "mac-amd64")
        else
          (if stdenv.isAarch64 then "linux-arm64" else "linux-amd64");
      cipdBinary = fetchurl {
        name = "cipd-${cipdPlatform}-${cipdVersion}-unwrapped";
        url = "https://chrome-infra-packages.appspot.com/client?platform=${cipdPlatform}&version=${cipdVersion}";
        sha256 = cipdHashes.${cipdPlatform};
      };
    in
    runCommandLocal "cipd-${cipdPlatform}-${cipdVersion}" { } "mkdir -p $out/bin; install -m 755 ${cipdBinary} $out/bin/cipd";
  gclient = writeShellScriptBin "gclient" ''
    ${python310.withPackages (py: with py; [ google-auth-httplib2 ])}/bin/python ${depot_tools}/gclient.py "$@"
  '';
in
# ...
```

**Comment by hacker1024** [comment]
> what exactly is the benefit of a source build?
flutter is a giant project and takes forever to build

The Flutter SDK fetches many executable components from Google's servers at runtime. These all have FHS dependencies.

By building the Flutter SDK manually, we can make sure everything is linked to Nix store libraries and is available offline.

Other alternatives would be to do one of the following:

- Patch the Flutter SDK to patch executables with `patchelf` after downloading them (this can be patched without building as this is done entirely in JIT-compiled Dart part of the SDK)
- Download every runtime component and patch it when building the derivation

The former seems tricky to implement, and the latter requires somehow curating a list of all external components. I don't think these are enumerated in any one place.

A FHS user environment is sub-optimal, because parts of the Flutter engine are copied into apps built with Flutter. This would mean that all packaged Flutter apps would have to be patched with `patchelf`, even if they're built from source, which really should not be necessary.

**Comment by milahu** [comment]
> The Flutter SDK fetches many executable components from Google's servers at runtime.

thats bad, but does not justify a source build.
we can prefetch all these binaries on build time

> By building the Flutter SDK manually, we can make sure everything is linked to Nix store libraries

flutter spent ONE HOUR just to fetch sources ...
so ideally, you will do a split build (one nix derivation per node in the build graph)
maybe overriding some packages with cached versions from nixpkgs (to save build time)

i collected some links in https://nixos.wiki/wiki/Gn

im not saying that source build is a bad idea
im just warning you that it could be a lot of work (developer time + cpu time)

**Comment by RossComputerGuy** [comment]
I've been working on this and was able to build the embedded engine on host but not inside of Nix. Yesterday, I managed to pull all dependencies and "lock" them in with Nix. Currently working on trying to build the actual engine in Nix.

**Comment by RossComputerGuy** [comment]
I managed to successfully compile the embedded engine completely in Nix. I've got issues with reproduction because of `gclient`'s requirement for having `.git` folders. So I've decided to ditch `gclient` and fake doing what it does. I'll probably have a PR out next month with the essentials for a working Flutter Engine build.

**Comment by hacker1024** [comment]
IIRC there is a way to make .git directories reproducible, I'll see if I can find what I've done before soon.

**Comment by dotlambda** [comment]
> IIRC there is a way to make .git directories reproducible, I'll see if I can find what I've done before soon.

`leaveDotGit` is known to cause reproducability issues.

**Comment by RossComputerGuy** [comment]
Yes, and that's why I am working on being able to build without `leaveDotGit`. I've almost got it working. Currently running into this error:
```
flutter-engine-jit_release> unpacking sources
flutter-engine-jit_release> unpacking source archive /nix/store/4c7vpcdgi62ss7231asy36sppmsql1z6-flutter-engine-src-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25
flutter-engine-jit_release> source root is flutter-engine-src-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25
flutter-engine-jit_release> patching sources
flutter-engine-jit_release> configuring
flutter-engine-jit_release> Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
flutter-engine-jit_release> Generating GN files in: /nix/store/ghd4arg0hga5zw1yaknrcrsb7zd8rqgr-flutter-engine-jit_release-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/lib/flutter/out/jit_release
flutter-engine-jit_release> ERROR at //third_party/dart/runtime/bin/BUILD.gn:5:1: Can't load input file.
flutter-engine-jit_release> import("../../build/config/gclient_args.gni")
flutter-engine-jit_release> ^-------------------------------------------
flutter-engine-jit_release> Unable to load:
flutter-engine-jit_release>   /build/flutter-engine-src-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/src/third_party/dart/build/config/gclient_args.gni
flutter-engine-jit_release> I also checked in the secondary tree for:
flutter-engine-jit_release>   /build/flutter-engine-src-857bd6b74c5eb56151bfafe91e7fa6a82b6fee25/src/build/secondary/third_party/dart/build/config/gclient_args.gni
flutter-engine-jit_release> See //flutter/BUILD.gn:101:9: which caused the file to be included.
flutter-engine-jit_release>         "//third_party/dart/runtime/bin:gen_snapshot",
flutter-engine-jit_release>         ^--------------------------------------------
flutter-engine-jit_release>
```

**Comment by RossComputerGuy** [comment]
I have resolved all errors but now I am stuck with this error:
```
flutter-engine-jit_release> [0/1] Regenerating ninja files
flutter-engine-jit_release> [0/1] Regenerating ninja files
flutter-engine-jit_release> [0/1] Regenerating ninja files
flutter-engine-jit_release> [0/1] Regenerating ninja files
flutter-engine-jit_release> [0/1] Regenerating ninja files
flutter-engine-jit_release> [0/1] Regenerating ninja files
flutter-engine-jit_release> ninja: error: manifest 'build.ninja' still dirty after 100 tries, perhaps system time is not set
```
