### ISSUE TITLE
tor-browser: startup failure when running under KDM

### ISSUE THREAD

**Issue by bendlas** [NixOS/nixpkgs#20157]
## Issue description

On startup, tor-browser fails with
```
% /nix/store/v58aj73h1hckgmqs1xjhghm66jnx2rna-tor-browser-6.0.5/bin/tor-browser       
No protocol specified
Error: cannot open display: :0.0
```

## Technical details

* System: 17.03-pre-7c2306ceba5568d4 (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03-pre-7c2306ceba5568d4
* Nixpkgs branch: https://github.com/bendlas/nixpkgs/tree/dev (based on nixos-unstable)
* Nixos config: https://github.com/bendlas/nixos-config/blob/master/desktop.nix
  (KDM+stumpwm/gnome session)

## Related

https://github.com/NixOS/nixpkgs/issues/17750
cc @rqcy @joachifm @ng-0

**Comment by joachifm** [comment]
I'm unable to reproduce this.

**Comment by joachifm** [comment]
@bendlas I don't know what to do about this, without more information. Can you elaborate?

**Comment by bendlas** [comment]
Hm, I've worked around the problem with an FHSEnv to run the official tor-browser binary.
I'll try to get some useful debug info out of our tor-browser and also will try on our gnome and kde ...

**Comment by bendlas** [comment]
Here is the tail of the systrace

```
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, 20) = 0
getpeername(4, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}, [124->20]) = 0
uname({sysname="Linux", nodename="nitox", ...}) = 0
access("/home/herwig/.torbrowser4/.Xauthority", R_OK) = -1 ENOENT (No such file or directory)
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
writev(4, [{iov_base="l\0\v\0\0\0\0\0\0\0\0\0", iov_len=12}, {iov_base="", iov_len=0}], 2) = 12
recvfrom(4, 0x7ffff6968380, 8, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}], 1, -1)    = 1 ([{fd=4, revents=POLLIN|POLLHUP}])
recvfrom(4, "\0\26\v\0\0\0\6\0", 8, 0, NULL, NULL) = 8
recvfrom(4, "No protocol specified\n\0\0", 24, 0, NULL, NULL) = 24
write(2, "No protocol specified\n", 22No protocol specified
) = 22
shutdown(4, SHUT_RDWR)                  = 0
close(4)                                = 0
write(2, "Error: cannot open display: :0.0"..., 33Error: cannot open display: :0.0
) = 33
exit_group(1)                           = ?
+++ exited with 1 +++
```

Looks like X server doesn't like what tor-browser is sending in the `writev(4 ..` and responds with that error message. Let me check on other desktops ...

**Comment by bendlas** [comment]
Problem is also present on KDE, as well as Gnome3. That would leave the X server, right?

```
$ X -version

X.Org X Server 1.18.4
Release Date: 2016-07-19
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.14.58 x86_64
Current Operating System: Linux nitox 4.8.6 #1-NixOS SMP Mon Oct 31 11:26:46 UTC 2016 x86_64
Kernel command line: BOOT_IMAGE=(hd0,msdos1)//kernels/rjzmvkd8amck704qmgykfp8ipxjgr6cs-linux-4.8.6-bzImage systemConfig=/nix/store/hs5r9wcynrwfxivz9xv05pm512zg2y9s-nixos-system-nitox-17.03-pre-7f94dc15cc5f2ae7 init=/nix/store/hs5r9wcynrwfxivz9xv05pm512zg2y9s-nixos-system-nitox-17.03-pre-7f94dc15cc5f2ae7/init loglevel=4 nomodeset resume=UUID=b3254264-6843-4eed-b817-81f692d2ca07
Build Date: 26 October 2016  10:08:19PM

Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
```

With a recent unstable update, I had gdm refuse to start (hence switched to kdm). I put that down to gdm 3.22 and incomplete wayland support, but maybe it's also related to this ...

I'll give it a try with a VM straight from current `unstable-channel`

**Comment by bendlas** [comment]
Ooh, it happens with KDM

**Comment by bendlas** [comment]
So .. when running sessions with lightdm, sddb, slim and gdm, tor-browser works. I can reproduce the failure in a vm with this profile:

```nix
{ config, pkgs, ... }:
{
  users.extraUsers.root.password = "123";
  users.extraUsers.vm.password = "123";
  users.extraUsers.vm.isNormalUser = true;
  users.mutableUsers = false;
  networking.hostName = "vm";
  environment.systemPackages = with pkgs; [
    torbrowser
  ];

  services.xserver = {
    enable = true;
    layout = "us";
    xkbOptions = "eurosign:e";
    displayManager.kdm.enable = true;
    desktopManager.xterm.enable = true;
  };
}
```

**Comment by joachifm** [comment]
@bendlas interesting. Thanks for all the info, looks like this narrows it down fairly well. Regrettably, I'm none the wiser :)

**Comment by bendlas** [comment]
Here is a diff of the `nix-store -qR ..` of both vms. http://hastebin.com/miwazehera.diff
There isn't much to go on. Those etc dirs are equal, content-wise.
Strange thing is: the official version works in an FHSUserEnv

**Comment by bendlas** [comment]
Hmm .. apparently KDM has been discontinued in favor of SDDM. Maybe we don't even want to fix this breakage and instead get rid of KDM?

**Comment by joachifm** [comment]
@bendlas in general, I'm inclined towards removing stuff, so that gets my vote.

**Comment by lverns** [comment]
Just thought I'd mention that this also effects my 16.09 install of NixOS.

**Comment by lverns** [comment]
Found a workaround [here](https://trac.torproject.org/projects/tor/ticket/1945). Running `XAUTHORITY="$HOME/.Xauthority" tor-browser` should work just fine.

**Comment by flosse** [comment]
I can reproduce it (running `awesome` + `kdm`) :-\

**Comment by joachifm** [comment]
The wrapper now sets defaults.
