### ISSUE TITLE
Systemd Stage 1 includes unnecessary fsPackages

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#201519]
As mentioned in #201396, if you have `boot.initrd.systemd.enable = true;`, then initrd will contain the `bin` directories of *all* `system.fsPackages`, which is undesirable. For instance, this by default includes `dosfstools` in initrd, which is obviously not necessary for almost anyone.

**Comment by LunNova** [comment]
> which is obviously not necessary for almost anyone.

Is that accurate? I remember my system failing to run fsck.fat on boot a few times because it's trying to check /boot. FAT32 /boot is very common for UEFI systems.
