### ISSUE TITLE
pam_ssh_agent_auth is old

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20155]
## Issue description
Could we update the `pam_ssh_agent_auth` package to `0.10.2`? (We last changed this in 2013 :D)
I tried doing so but the patch file we apply seems way off what they have now.

Pinging @edolstra as the maintainer

**Comment by joncfoo** [comment]
[This](https://github.com/NixOS/nixpkgs/commit/643703366dd44bd0848dc302a959c5cce9a4d2bf) commit updates the version - maybe this issue can be closed?
