### ISSUE TITLE
podman.socket failed when running podman with -v $XDG_RUNTIME_DIR/podman/podman.sock

### ISSUE THREAD

**Issue by stratdev3** [NixOS/nixpkgs#201538]
### Describe the bug
Unable to pass the user's podman.sock to podman container

### Steps To Reproduce
my configuration.nix
```
virtualisation = {
    ## setup podman
    podman = {
      enable = true;
      dockerCompat = true;
      defaultNetwork.dnsname.enable = true;
    };
```

start podman socket as simple (no root) user

```console
[user@nixos:~]$ systemctl --user start podman.socket
```

run docker image for testing purpose

```console
[user@nixos:~]$ podman run -it --name test --rm -v $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock docker.io/docker
```
it will failed the podman.socket service

![image](https://user-images.githubusercontent.com/115271718/202270221-adf8439b-b17f-4273-80d2-26dc7bd72d6f.png)

and so i can't use the `docker ps` command to show running docker container in the host from the inside the container

![image](https://user-images.githubusercontent.com/115271718/202270544-cceac6f9-47a9-4869-a16d-78adc03c169b.png)

### Expected behavior

`docker ps` should return the actual running container

![image](https://user-images.githubusercontent.com/115271718/202270785-20a44026-c169-4728-aedc-75aeb47f5a2c.png)

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/blob/54be84c3ac0122c2b2272fc68a9015304bc0bb73/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L34-L40

**Comment by stratdev3** [comment]
```console 
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.78, NixOS, 22.05 (Quokka), 22.05.4243.814f8f3363c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

The output log of the error is reporting problem with systemd socket limit

```console 
[user@system:~]$ journalctl
Nov 17 10:07:08 nixos systemd[922]: Failed to start Podman API Service.
Nov 17 10:07:08 nixos systemd[922]: podman.socket: Trigger limit hit, refusing further activation.
Nov 17 10:07:08 nixos systemd[922]: podman.socket: Failed with result 'trigger-limit-hit'.
```

I'm trying to change `TriggerLimitIntervalSec=0` and `TriggerLimitBurst=0` and check if it fix bug...

**Comment by stratdev3** [comment]
@zowoq thanks for the pointer ! the workaround is perfect. closing the issue.
