### ISSUE TITLE
systemd syslog-ng service fails to activate

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#20153]
I'm upgrading my systems from NixOS 16.03 to 16.09 and I'm trying to get syslog-ng working again. It's currently configured as:

```nix
{ syslog-ng.enable = true; }
```

The issue is that systemd is not noticing that syslog-ng has started:

```
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Start operation timed out. Terminating.
Nov 04 12:47:08 mymachine systemd[1]: Failed to start syslog-ng daemon.
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Unit entered failed state.
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Failed with result 'timeout'.
Nov 04 12:47:08 mymachine systemd[1]: syslog-ng.service: Service hold-off time over, scheduling restart.
```

I do see that syslog-ng is running:

```
# ps -AH a | grep syslog
/nix/store/kag473gb3w8zaqw09qkgsjg2qn4ra5zc-syslog-ng-3.6.2/sbin/syslog-ng --foreground --module-path=/nix/store/kag473gb3w8zaqw09qkgsjg2qn4ra5zc-syslog-ng-3.6.2/lib/syslog-ng --cfgfile=/nix/store/8f9npiv1fyc487haxj0ff957ag7zqzld-syslog-ng.conf --control=/run/syslog-ng/syslog-ng.ctl --persist-file=/var/syslog-ng/syslog-ng.persist --pidfile=/run/syslog-ng/syslog-ng.pid
```

Note that the systemd syslog-ng service is [configured](https://github.com/NixOS/nixpkgs/blob/release-16.09/nixos/modules/services/logging/syslog-ng.nix#L87) with `Type = "notify";` This [means](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) that syslog-ng should notify systemd when it has started up. My current hypotheses is that with the systemd upgrade to 231 something in the notification protocol has changed causing the syslog-ng notification to fail.

**Comment by danbst** [comment]
It has strange config:
```
      wantedBy = [ "multi-user.target" ];
      after = [ "multi-user.target" ]; # makes sure hostname etc is set
```
how could this work ?

@basvandijk could you test this? syslog-ng at least starts for me
```
diff --git a/nixos/modules/services/logging/syslog-ng.nix b/nixos/modules/services/logging/syslog-ng.nix
index 21be286..fd6ab7d 100644
--- a/nixos/modules/services/logging/syslog-ng.nix
+++ b/nixos/modules/services/logging/syslog-ng.nix
@@ -82,9 +82,9 @@ in {
       description = "syslog-ng daemon";
       preStart = "mkdir -p /{var,run}/syslog-ng";
       wantedBy = [ "multi-user.target" ];
-      after = [ "multi-user.target" ]; # makes sure hostname etc is set
+      after = [ "network.target" ]; # makes sure hostname etc is set
       serviceConfig = {
-        Type = "notify";
+        Type = "simple";
         StandardOutput = "null";
         Restart = "on-failure";
         ExecStart = "${cfg.package}/sbin/syslog-ng ${concatStringsSep " " syslogngOptions}";
```

**Comment by basvandijk** [comment]
thanks @danbst, with those changes syslog-ng starts up correctly.

**Comment by fpletz** [comment]
> how could this work ?

`wantedBy` means that the syslog-ng unit will be activated (started) when `multi-user.target` gets activated. By itself this relation defines no order. That's why you can add `after` and `before` relations as you wish.

As I've mention in #20211, the root problem is that our current version of syslog-ng can't be built with our current version of systemd and thus the sd-notify feature is not present.

**Comment by basvandijk** [comment]
Hi @fpletz, I did some work on the syslog-ng upgrade. I've managed to get syslog-ng-3.9.1 to build with https://github.com/LumiGuide/nixpkgs/commit/ee0826e6a0fb58c07f7a3efca634d8847bb8bde7. I will now test this a bit.
