### ISSUE TITLE
[question] Why all node modules don't have x86-64?

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#201629]
Only have i686-linux, aarch64-linux, aarch64-darwin. Like <https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=prettier>

**Comment by 06kellyjac** [comment]
Which package are you expecting to see x86_64 on? The one you linked to shows x86_64 platforms just fine

![image](https://user-images.githubusercontent.com/9866621/202738253-ba707fcb-f5e1-4b9c-b8fb-b5debf5e7ce0.png)

**Comment by Freed-Wu** [comment]
![screen-2022-11-18-23-32-57](https://user-images.githubusercontent.com/32936898/202741707-0a3e1d7e-0e57-48a4-9dc2-fe61093cecf4.jpg)
I just am curious why the left only have three platforms :smile:

**Comment by 06kellyjac** [comment]
Oh, you mean on the left sidebar, no idea
There should be a repo on the nixos org for the search

**Comment by garbas** [comment]
I'm moving this issue.
