### ISSUE TITLE
Kdenlive: cannot set pitch compensation because "MLT must be compiled with the rubberband library"

### ISSUE THREAD

**Issue by fee1-dead** [NixOS/nixpkgs#201654]
### Describe the bug
cannot use pitch compensation in kdenlive despite having mlt and rubberband installed/introduced via nix-shell

### Steps To Reproduce
1. open kdenlive
2. add video with audio or just audio
3. right click on audio, select "Change Speed"
4. see that Pitch Compensation is disabled because "MLT must be compiled with the rubberband library"

### Expected behavior

There should be some way to enable this.

### Screenshots
![image](https://user-images.githubusercontent.com/43851243/202512491-1c7860ba-a9d4-4f99-b627-6dfa0413ca4e.png)

### Notify maintainers

kdenlive: @turion 
rubberband: @cillianderoiste @MarcWeber 
mlt: @tohl @peti 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.8, NixOS, 22.11 (Raccoon), 22.11.20221114.dad4de1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(beef): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by turion** [comment]
I can confirm except for this part:

>  because "MLT must be compiled with the rubberband library"

I don't see such a tooltip.

**Comment by fee1-dead** [comment]
> I don't see such a tooltip.

have you tried hovering over the disabled option?

**Comment by turion** [comment]
Yes right, thanks. No idea why it didn't show up the first time, probably I was too hasty.

**Comment by turion** [comment]
Nevermind, I mixed up `mlt/default.nix` and `mlt/qt5.nix`. Seems it can be fixed easily, will send a PR.

**Comment by fee1-dead** [comment]
@Felipecconde I have no idea what you are on about.
