### ISSUE TITLE
flexoptix-app 5.13.0 -> 5.13.1

### ISSUE THREAD

**Issue by lugeha** [NixOS/nixpkgs#201695]
###### Checklist

- [+] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [+] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: flexoptix-app

current version: 5.13.0
desired version: 5.13.1

###### Notify maintainers

maintainers: Janne Heß <janne@hess.ooo>

###### Note for maintainers

Please tag this issue in your PR.

5.13.0 is no longer available for download.

**Comment by skorpy2009** [comment]
Already done, can be closed.
