### ISSUE TITLE
docker running sh command inside a podman container do not return to prompt

### ISSUE THREAD

**Issue by stratdev3** [NixOS/nixpkgs#201630]
### Describe the bug

In a podman container, running another container using `docker run -c` argument do not return to prompt

### Steps To Reproduce

Just run into a podman container as simple user

```console 
[user@system:~]$ systemctl --user start podman.socket
[user@system:~]$ podman run -it --rm --name test -v $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock docker.io/docker
```
So, we're in the container and running command with `-c` arg using docker

```console 
/ # docker run --rm node sh -c "echo hello"
hello
```

The command never end and do not return to the current prompt

### Expected behavior

running the `sh -c` arg should return to prompt after command is ended

```console 
/ # docker run --rm node sh -c "echo hello"
hello
/ # 
```

### Metadata

 ```console 
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m" 
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.78, NixOS, 22.05 (Quokka), 22.05.4243.814f8f3363c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by 06kellyjac** [comment]
Hello

1. any kind of mismatch between podman's docker compat socket and docker behavior should be directed to the podman team, this isn't related to NixOS
2. This is exactly how docker behaves
  * You're not using `-it` to retain an interactive tty
  * Even if you add that your process is dead. If in `zsh` you run `sh -c "echo hello"` you won't stay in `sh` you drop back into `zsh` because the process is done
  
Also you shouldn't have to systemctl start anything if you're configuring podman via nixos config

**Comment by stratdev3** [comment]
@06kellyjac 

> 1. any kind of mismatch between podman's docker compat

it is not.

> 2. You're not using -it to retain an interactive tty

Did you just run the command i post ?
Test in another distro, like ubuntu, and you will understand the underlying bug : after the `docker run --rm node sh -c "echo hello"`, i should return to prompt.

**Comment by 06kellyjac** [comment]
ok, you mean the prompt of the `docker` container, not the `node`

yes I tried it and I stay within the `docker` container on nixos-unstable as you desire. Either it's a podman update thing or something in the nixos configuration that has been fixed already. Are you able to try out unstable or wait for 22.11?

**Comment by stratdev3** [comment]
You're right, this bug in the 22.05 is fixed in the unstable channel.
That's good to me.

Thanks for your help
