### ISSUE TITLE
bluetuith

### ISSUE THREAD

**Issue by kennethbruskiewicz** [NixOS/nixpkgs#201660]
**Project description**

A Bluetooth connection manager via TUI

**Metadata**

* homepage URL: https://golangexample.com/a-tui-based-bluetooth-connection-manager-which-can-interact-with-bluetooth-adapters-and-devices/
* source URL: https://github.com/darkhz/bluetuith
* license: MIT
* platforms: Linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/198612

It's already packaged and available in the unstable channel
