### ISSUE TITLE
binutils-unwrapped-all-targets does not include `as` on aarch64-darwin

### ISSUE THREAD

**Issue by Cloudef** [NixOS/nixpkgs#201753]
### Describe the bug

binutils-unwrapped-all-targets does not include `as` on aarch64-darwin

### Steps To Reproduce
1. get aarch64-darwin platform
2. `file "$(nix eval --raw -f '<nixpkgs>' binutils-unwrapped-all-targets)/bin/as"`

### Expected behavior
`/nix/store/iiijz081lrslpg8b9w2py5mxz969xgr3-binutils-2.39/bin/as: Mach-O 64-bit executable arm64`

### Additional context
This is most likely oversight in binutils build system that GNU assembler does not support aarch64-darwin target, however all-targets should still contain GNU assembler that can assemble to other targets.

### Notify maintainers

@Ericson2314 
@lovesegfault 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(jari): `"nixpkgs"`
 - channels(root): `""`
 - nixpkgs: `/Users/jari/.nix-defexpr/channels/nixpkgs`
```

**Comment by trofi** [comment]
Looking at `staging-next`'s build log: https://hydra.nixos.org/log/p1691fwmmb3qb03k75gvdm7lbakzhk57-binutils-2.39.drv `gas`, `gprof` and `ld` were indeed skipped when built:

```
*** This configuration is not supported in the following subdirectories:
     zlib ld gas gprof
    (Any other directories should still work fine.)
```

It's explicitly filtered out in a top-level configure:

```
# configure.ac
case "${target}" in
  ...
  aarch64-*-darwin*)
    noconfigdirs="$noconfigdirs ld gas gdb gprof"
    noconfigdirs="$noconfigdirs sim target-rda"
```

I suggest filing an upstream bug to check if it's a feature. There are probably some limitations building it as the default target will be unselectable and thus would have to be named anything but `gas`.
