### ISSUE TITLE
Yabridge and yabridgectl 4.0.2 not propagated? (still 3.8.1, out of date)

### ISSUE THREAD

**Issue by the-argus** [NixOS/nixpkgs#201702]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: ``yabridge``

current version: 3.8.1
desired version: 4.0.2

###### Notify maintainers

maintainers: @kira-bruneau 

###### Note for maintainers

Please tag this issue in your PR.

###### Further notes

I haven't thoroughly searched the chain of evaluation, so it is possible that this is something I just don't understand in nixpkgs- but if I install yabridge from nixos-unstable at ``2f0c3be57c348f4cfd8820f2d189e29a685d9c41`` then I get yabridge 3.8.1. You can see this occurring if you try using the home-manager module from [my flake](https://github.com/the-argus/audio-plugins-nix). Both are 3.8.1.
This is also holds true for nixpkgs-unstable at ``fd54651f5ffb4a36e8463e0c327a78442b26cbe7``, a more recent commit.

This should not be the case after [PR #181135](https://github.com/NixOS/nixpkgs/pull/181135) was merged. It doesn't seem to have taken effect.

###### Ramblings of an insane person

I *swear* that my flake was broken during development, and I had to use 4.0.2 for it to work. I can't find evidence of this anywhere in my commit history... but I think 4.0.2 was working at some point.

**Comment by kira-bruneau** [comment]
Oh, it looks like you're installing yabridge through a module, which isn't tied down to specific nixpkgs version. It's version would be affected by whatever flake is importing the module.

**Comment by the-argus** [comment]
I see. I was really confused because ``nix search nixpkgs yabridge`` showed 4.0.2, but ``nix-shell -p yabridgectl`` yielded version 3.8.1. I've heard that this has something to do with legacyPackages or something...

Thanks for all your work packaging this.  Every day I get closer to having a declarative audio production setup, thanks in no small part to you :)

**Comment by kira-bruneau** [comment]
Aww thank you! :heart: I just wish I was better at staying on top of maintenance. I've been procrastinating the 5.0.0 update :cry: I'll hopefully get to that this weekend!
