### ISSUE TITLE
Can't disable services.gnome.gnome-keyring to replace it with home manager services.pass-secret-service

### ISSUE THREAD

**Issue by BenediktBroich** [NixOS/nixpkgs#201766]
### Describe the bug
Can't disable [`services.gnome.gnome-keyring.enable = false;`](https://search.nixos.org/options?channel=unstable&show=services.gnome.gnome-keyring.enable&from=0&size=50&sort=relevance&type=packages&query=services.gnome.gnome-keyring.enable) to replace it with [`services.passSecretService.enable= true;`](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=services.passSecretService.enable) or home  manager [`services.pass-secret-service.enable= true;`](https://github.com/nix-community/home-manager/blob/master/modules/services/pass-secret-service.nix#blob-path) when [`services.xserver.desktopManager.gnome.enable = true;`](https://search.nixos.org/options?channel=unstable&show=services.xserver.desktopManager.gnome.enable&from=0&size=50&sort=relevance&type=packages&query=services.xserver.desktopManager.gnome.enable) is enabled.

But i get following error.
```
error: The option `services.gnome.gnome-keyring.enable' has conflicting definition values:
       - In `/nix/store/fkx24s5smqs2xw88n7yx3xy2jk1gx80l-source/profiles/gnome': false
       - In `/nix/store/da9dyx30lsdgw2x2gnxkc88aq1d9fwik-source/nixos/modules/services/x11/desktop-managers/gnome.nix': true
```

### Steps To Reproduce

configuration.nix
```nix
services = {
    xserver = {
      enable = true;
      displayManager.gdm.enable = true;
      desktopManager.gnome.enable = true;
    };
    gnome.gnome-keyring.enable = false;
    # passSecretService.enable = true;
  };
}
```

Home Manager
```nix
services.pass-secret-service.enable = true;
```

### Expected behavior
I should be able to disable gnome.gnome-keyring.enable. Or maybe there should be an option to override org.freedesktop.secrets.service Exec as described in [this Issue](org.freedesktop.secrets.service).?

### Additional context
Last patch
- [pass-secret-service: unstable-2020-04-12 -> unstable-2022-03-21](https://github.com/NixOS/nixpkgs/pull/168879/files)

Source
- [pass_secret_service](https://github.com/mdellweg/pass_secret_service)
- [pypass](https://github.com/aviau/python-pass)
- [Secret Service API](https://specifications.freedesktop.org/secret-service/latest/)

Issue insights
- [Documentation on how to enable](https://github.com/mdellweg/pass_secret_service/issues/23#issuecomment-1239364257) 
- `busctl --user | grep secret` output: `org.freedesktop.secrets                      21200 .gnome-keyring- bene :1.163        user@1000.service -       -` 
- but should be `pass_secret_service`

Related Issues
- [Gnome-keyring auto-start files (DBus etc) conflict with other Secret Service providers](https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/86)
- [Register as the default Secret Service provider (DBus service)](https://github.com/keepassxreboot/keepassxc/issues/6274)

### Notify maintainers
Pass Secret Service Maintainer
@aidalgol you are the maintainer of [`services.passSecretService`](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=services.passSecretService.enable) so maybe you have some insights.

Gnome Maintainers
@bobby285271 @hedning @jtojnar @dasj19 @maxeaubrey

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.6, NixOS, 22.05 (Quokka), 22.05.20221105.f09ad46`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.1`
 - channels(root): `"nixos-22.11pre425577.0533be43f1c"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Thanks for you help!

**Comment by jtojnar** [comment]
You can use `lib.mkForce` to override the option. I think we did not make the gnome-keyring option just enabled by default because we were not sure if something won’t seriously break without the service.

**Comment by BenediktBroich** [comment]
Thanks. That did work. Here is my full configuration if someone else is searching for this.

configuration.nix
```
  services = {
    xserver = {
      enable = true;
      displayManager.gdm.enable = true;
      desktopManager.gnome.enable = true;
    };
    gnome.gnome-keyring = pkgs.lib.mkForce { enable = false; };
  };
```

home-manager
```
  services.pass-secret-service.enable = true;
  programs = {
    password-store = {
      enable = true;
      settings = {
        PASSWORD_STORE_DIR = ".password-store"; # pypass will search for this folder in your home directory DON'T ADD ~/
      };
    };
  };
```
