### ISSUE TITLE
Drop Qt 5.12 and 5.14

### ISSUE THREAD

**Issue by K900** [NixOS/nixpkgs#201765]
We have 32 packages that depend on pre-5.15 Qt. Those are (as determined by `rg '\s+(.*) = libsForQt51[24]\.callPackage' --no-line-number -o -r '$1'`):

- [x] antimony (upstream, see https://github.com/mkeeter/antimony/pull/235)
- [x] apmplanner2 https://github.com/NixOS/nixpkgs/pull/203064
- [x] bitcoin-classic https://github.com/NixOS/nixpkgs/pull/202664
- [x] bitcoin-gold https://github.com/NixOS/nixpkgs/pull/202664
- [x] bitcoin-unlimited https://github.com/NixOS/nixpkgs/pull/202664
- [ ] boomerang
- [x] brewtarget https://github.com/NixOS/nixpkgs/pull/203064
- [x] cb2bib https://github.com/NixOS/nixpkgs/pull/203064
- [x] digibyte https://github.com/NixOS/nixpkgs/pull/202664
- [x] digitalbitbox https://github.com/NixOS/nixpkgs/pull/203064
- [ ] fontmatrix
- [ ] foxitreader
- [x] graphia https://github.com/NixOS/nixpkgs/pull/203057
- [x] ipe https://github.com/NixOS/nixpkgs/pull/203064
- [ ] kexi
- [x] kvirc #201771
- [x] mythtv https://github.com/NixOS/nixpkgs/pull/203145
- [x] notepadqq #202075
- [ ] olive-editor
- [x] polyphone #201974 
- [ ] pulseview (upstream, see https://github.com/NixOS/nixpkgs/issues/201765#issuecomment-1320084833)
- [ ] quiterss
- [x] rosegarden https://github.com/NixOS/nixpkgs/pull/203064
- [x] sayonara #202142
- [x] smtube: https://github.com/NixOS/nixpkgs/pull/201770
- [x] subsurface #202145
- [ ] swift-im
- [ ] tony
- [x] vertcoin https://github.com/NixOS/nixpkgs/pull/202664
- [x] wkhtmltopdf https://github.com/NixOS/nixpkgs/pull/203064
- [x] xygrib https://github.com/NixOS/nixpkgs/pull/203058

The old Qt versions are a big maintenance burden, as evidenced by them breaking yet again with https://github.com/NixOS/nixpkgs/pull/200872, and we should really get rid of them.

Ping @NixOS/qt-kde

Also general ping to all the maintainers of affected packages:

- antimony: @rnhmjoj
- apmplanner2: @wucke13
- bitcoin-classic: @jefdaj
- bitcoin-gold: @mmahut
- bitcoin-unlimited: @DmitryTsygankov
- boomerang: @dtzWill
- brewtarget: @mmahut
- cb2bib: @edwtjo
- digibyte: @mmahut
- digitalbitbox: @vidbina
- foxitreader: @p-h, @rhoriguchi
- graphia: @bgamari
- ipe: @ttuegel
- kexi: @zraexy
- kvirc: @suhr
- mythtv: @titanous
- notepadqq: @rszibele
- olive-editor: @balsoft
- polyphone: @Maxdamantus
- pulseview: @bjornfor
- quiterss: @primeos
- rosegarden: @lebastr
- sayonara: @deepfire
- smtube: @vbgl
- subsurface: @mguentner, @adisbladis
- swift-im: @orivej
- tony: @orivej
- vertcoin: @mmahut
- wkhtmltopdf: @jb55
- xygrib: @johannesloetzsch, @SuperSandro2000

**Comment by vbgl** [comment]
smtube: #201770

**Comment by bjornfor** [comment]
Re: pulseview. I tried updating to default qt version and it failed to build. Then I pinged upstream: https://sourceforge.net/p/sigrok/mailman/message/37736944/.

**Comment by rnhmjoj** [comment]
Antimony is on very low maintenance but I should be able to fix it and get a patch merged, not so soon though. Do you intend to drop Qt <5.15 for 22.11 or a later release?

**Comment by K900** [comment]
I think it's too late for 22.11, but I want to do it early in the 23.05 cycle.

**Comment by Maxdamantus** [comment]
polyphone: #201974

**Comment by flokli** [comment]
There seems to already be an issue about that: https://github.com/NixOS/nixpkgs/issues/53079

Can we check if something important is still missing from there?

**Comment by K900** [comment]
That issue is about deprecating the QtWebKit module from all Qt versions (5.15 included). This one is about deprecating the older versions entirely. There's some overlap, but it's not all.

**Comment by LunNova** [comment]
notepadqq: #202075

**Comment by K900** [comment]
Tried updating mythtv, v32 should be buildable with Qt 5.15, but it fails to link its own vendored ffmpeg and I don't want to dig into 15k lines of bash that are their build system. WIP patch if anyone wants to continue: https://termbin.com/e1o6

**Comment by K900** [comment]
Doing a quick audit on the remaining packages:

| Package | Builds on 5.15 | Dead | Notes |
|-|-|-|-|
| `apmplanner2` | yes | no ||
| `boomerang` | no | [very](https://github.com/BoomerangDecompiler/boomerang) ||
| `brewtarget` | yes | no | [had a 3.0 release recently](https://github.com/Brewtarget/brewtarget/releases), update? |
| `cb2bib` | yes | yes ||
| `digitalbitbox` | yes | [yes](https://github.com/digitalbitbox/dbb-app) ||
| `fontmatrix` | no | [slightly alive](https://github.com/fontmatrix/fontmatrix) | ours is very old, update? |
| `foxitreader` | ? | no | can't fetch the source, package hasn't been updated for over a year |
| `graphia` | no | no | [latest is 3.2](https://github.com/graphia-app/graphia/releases), ours is 2.2, update? |
| `ipe` | yes | no | [slightly out of date](https://ipe.otfried.org/) |
| `mythtv` | no | no | god help me |
| `olive-editor` | no | ? | upstream is [active](https://github.com/olive-editor/olive), but last numbered release in 2019 - update to unstable? |
| `pulseview` | no | yes? | deadness of upstream needs confirmation |
| `quiterss` | yes | yes ||
| `rosegarden` | yes | no | ours is very outdated |
| `swift-im` | no | [very](https://github.com/swift/swift/) ||
| `tony` | no | [very](https://code.soundsoftware.ac.uk/projects/tony/repository) ||
| `wkhtmltopdf` | yes | maybe? ||
| `xygrib` | no | no | upstream is [active](https://github.com/opengribs/XyGrib), but no stable release - update to unstable? |

**Comment by K900** [comment]
I think it might be worth trying to save `graphia`, `mythtv` and `xygrib`, and the rest should be good to drop.

**Comment by lilyinstarlight** [comment]
@K900, there is an open PR for the `mythtv` update already that seems to work: #197930

**Comment by K900** [comment]
Awesome, I must have missed it. So, should we get all of this merged and rip off the bandaid?
