### ISSUE TITLE
haskellPackages.hostname Hydra failure on i686

### ISSUE THREAD

**Issue by sg2002** [NixOS/nixpkgs#201880]
ZHF: https://github.com/NixOS/nixpkgs/issues/199919
ZHF i686: https://github.com/NixOS/nixpkgs/issues/200691

[Currently](https://malob.github.io/nix-review-tools-reports/nixos:trunk-combined/nixos_trunk-combined_1785737.html) hostname-1.0 is the most significant broken package on i686, since it leads to other 33 failures, with some important ones like pantheon.

But, I could not reproduce it on my test machine and was able to get pantheon running just fine. I'm currently checking other failures, but I strongly suspect that this is a Hydra-only issue.

Our tools lead us to [the redmine pgsql](https://hydra.nixos.org/build/198293536) job, which seems to be the initial place where haskellPackages.hostname is getting built in our jobset. So my working theory is that when the Redmine job fails due to some unrelated issue, it happens when the hostname is getting built and it mistakenly marks it as broken, even though it's not.

Forgive me if I'm all wrong, since my Hydra knowledge is limited. Anyway, here I need someone with more Hydra knowledge(and access) to look into this.

**Comment by vcunat** [comment]
That sounds like a wrong theory, as you can see the log for `hostname` linked from that page: https://hydra.nixos.org/log/hc1yfxkmb4md7g2sx37697sknw8w2hzv-hostname-1.0.drv
But I confirm that the same build succeeds for me (`pkgsi686Linux.haskellPackages.hostname`, same derivation hash).

**Comment by vcunat** [comment]
Hydra also succeeded when I restarted the job 🤷🏽
https://hydra.nixos.org/build/199010017

**Comment by vcunat** [comment]
The issue hasn't reappeared since then: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.allDrivers.redmine.pgsql.i686-linux
