### ISSUE TITLE
Missing Documentation for common lisp

### ISSUE THREAD

**Issue by binarydigitz01** [NixOS/nixpkgs#201882]
## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

Currently there is no documentation for common lisp setup. I'm having troubles trying to setup sbcl with libraries that need c libraries like gtk 4, but sbcl can't find it. I have looked at a lot of places for help, but none have worked.

We can make a wiki page for sbcl setup, along with some sample configuration that help sbcl find C libraries in the correct place.

**Comment by justinmakes** [comment]
There's a handful of hackey solutions for getting quicklisp running with sbcl but there always seems to be some compromise. Would making a derivation that runs sbcl in an FHS environment solve the issue?

**Comment by binarydigitz01** [comment]
Enough Documentation has been added in the latest version, this can be closed.
