### ISSUE TITLE
Package "fakeroute" as a systemd service

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20181]
This is a tool that helps hide your (network topological) location by emulating extra hops when you are traceroute'd.

See: https://moxie.org/software/fakeroute/
and see https://code.google.com/p/paris-traceroute/wiki/Fakeroute for usage examples

**Comment by rnhmjoj** [comment]
The license is not specified, or is it? Can we package it?

**Comment by rnhmjoj** [comment]
Packaged.

**Comment by joachifm** [comment]
We have a fakeroute service module now, thanks to @rnhmjoj
