### ISSUE TITLE
mastodon: using different processes for sidekiq queues to increase scaling ?

### ISSUE THREAD

**Issue by rgrunbla** [NixOS/nixpkgs#201800]
## Issue description

On https://docs.joinmastodon.org/admin/scaling/, one of the advices to scale Mastodon is the following:

```
The way Sidekiq works with queues, it first checks for tasks from the first queue, and
if there are none, checks the next queue. This means, if the first queue is overfilled,
the other queues will lag behind.

As a solution, it is possible to start different Sidekiq processes for the queues to ensure
truly parallel execution, by e.g. creating multiple systemd services for Sidekiq with different
arguments.
```

It would be nice in the mastodon nixos module if there was a setting allowing to enable this behaviour.

Tagging the maintainers @erictapen, @happy-river, @izorkin and @ghuntley

**Comment by teutat3s** [comment]
There's now a PR for this: #202408

**Comment by rgrunbla** [comment]
Thanks for the heads up, closing this issue in favor of https://github.com/NixOS/nixpkgs/pull/202408 !
