### ISSUE TITLE
ALPS TouchPad in absolute mode

### ISSUE THREAD

**Issue by Zimmi48** [NixOS/nixpkgs#20189]
## Issue description

I'm having the same issue as is described on this forum: https://bbs.archlinux.org/viewtopic.php?id=40141
When I put my finger somewhere on the touchpad, the cursor moves to the corresponding absolute position on the screen.

### Steps to reproduce

I am not sure that this is reproducible because I don't have this problem with the installation image booted from a USB key.
The problem also disappears sometimes after I used an external mouse long enough.

## Technical details

* System: NixOS 16.09
* Nix version: 1.11.4
* Nixpkgs version: 16.09.733.246c937

The output of `xinput` is
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ HID 413c:8158                           	id=10	[slave  pointer  (2)]
⎜   ↳ AlpsPS/2 ALPS DualPoint TouchPad        	id=13	[slave  pointer  (2)]
⎜   ↳ AlpsPS/2 ALPS DualPoint Stick           	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ HID 413c:8157                           	id=9	[slave  keyboard (3)]
    ↳ Laptop_Integrated_Webcam_0.3M           	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=15	[slave  keyboard (3)]
```

The output of `dmesg | grep Synaptics` is void. The output of `dmesg | grep ALPS` is
```
[   19.914892] input: AlpsPS/2 ALPS DualPoint Stick as /devices/platform/i8042/serio1/input/input16
[   19.932817] input: AlpsPS/2 ALPS DualPoint TouchPad as /devices/platform/i8042/serio1/input/input13
```

My `hardware-configuration.nix` is:
```
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/245c8490-4e85-4836-aa1a-13a3fc9d94c3";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c464e14f-1002-4828-8859-a55766355b9c";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/36b77ea3-bb39-4458-92cf-374308ff52d4"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
```

**Comment by sid-kap** [comment]
I don't know why this works, but for me adding
```
services.synaptics.enable = true;
```
fixed the problem.

**Comment by Zimmi48** [comment]
I think you mean

    services.xserver.synaptics.enable = true;

It fixed the problem for me too. If this option is need for touchpads, I don't get why it isn't proposed in the default `configuration.nix` file.

**Comment by Zimmi48** [comment]
I'll leave it to someone else to take the decision whether to close this issue or to leave it open. The problem is fixed for me but it still feels like it is a bad user experience that could be solved by improving the default `configuration.nix` file which is proposed to new users.

**Comment by vcunat** [comment]
I suspect the intention was not to include the driver for those who don't need it. Still, the savings are probably very small.

**Comment by dezgeg** [comment]
I have one laptop affected by this, IIRC it affects the install ISOs as well. Sufficiently annoying such that we really should figure this one out for 17.03.

**Comment by dezgeg** [comment]
I guess we can just set `services.xserver.libinput.enable = true;` by default. According to Arch wiki, the synaptics driver is deprecated / not updated anymore.

**Comment by vcunat** [comment]
Last [xf86-input-synaptics release](https://www.x.org/releases/individual/driver/) was in November 2016, but I don't know developer plans.  Maybe X is getting deprecated already :-)
