### ISSUE TITLE
Locales: C.UTF-8 is not available

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#20192]
## Issue description

The C.UTF-8 locale is missing (`locale -a`). We do have lots of other UTF-8 locales, but those are all country specific.

- https://sourceware.org/glibc/wiki/Proposals/C.UTF-8
- https://lists.fedoraproject.org/pipermail/glibc/2015-September/000081.html

**Comment by vcunat** [comment]
We use the list provided by upstream in the `localedata/SUPPORTED` file. Any idea why they don't put it in there?

**Comment by FRidh** [comment]
Apparently there is a strong push for putting C.UTF-8 in the binary instead, so that it can be guaranteed that it is available on all systems.
https://sourceware.org/bugzilla/show_bug.cgi?id=17318

**Comment by FRidh** [comment]
While we could try and add C.UTF-8 support ourselves (like some other distro's have done or are planning) I think it's something best left to upstream, so I am closing this. If you think it should remain open, feel free to reopen.

**Comment by vcunat** [comment]
The last inter-linked discussions were in February 2015, so it's possible the push isn't so strong and the issue is just stalled long-term.

I agree we would best leave this to upstream, at least until they to the first step of agreeing on some semantic details and adding `C.UTF-8` among the regular generated locales.

**Comment by FRidh** [comment]
It's likely that [PEP 538](https://www.python.org/dev/peps/pep-0538/) is accepted and that would mean Python 3.7 is going to try and use `C.UTF-8` by default.

**Comment by bennofs** [comment]
The patch from Fedora is quite simple: https://src.fedoraproject.org/cgit/rpms/glibc.git/tree/glibc-c-utf8-locale.patch

**Comment by concatime** [comment]
Anything evolved since last discussion?

**Comment by FRidh** [comment]
Reopening because we are going to need this with Python 3.7.

**Comment by FRidh** [comment]
Latest discussion on the topic upstream:
https://sourceware.org/bugzilla/show_bug.cgi?id=17318

**Comment by vcunat** [comment]
Still not resolved upstream, not even in glibc-2.28 which we don't have yet.

**Comment by FRidh** [comment]
@Mic92 I see you have a patch in your branch. Did you test it?

**Comment by Mic92** [comment]
@FRidh I think there was a problem somewhere, which is why I never made a pull request.

**Comment by FRidh** [comment]
This is in master, so closing now.

**Comment by dtzWill** [comment]
YES! Looking forward to this and resulting cleanups! (like the python PR ^_^)
