### ISSUE TITLE
glib fails to configure meson due to missing xsltproc command while cross compiling for aarch64

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#201994]
### Describe the bug

`glib-2.74.1` fails to configure with meson as it couldn't find `xsltproc`. This occurs while cross compiling from x86_64 to aarch64 Linux.
```
Program xgettext found: YES (/nix/store/ahb1jl345mpn3v8my8aj77df294q59ij-gettext-0.21/bin/xgettext)
Program msgfmt found: YES (/nix/store/ahb1jl345mpn3v8my8aj77df294q59ij-gettext-0.21/bin/msgfmt)
Program msginit found: YES (/nix/store/ahb1jl345mpn3v8my8aj77df294q59ij-gettext-0.21/bin/msginit)
Program msgmerge found: YES (/nix/store/ahb1jl345mpn3v8my8aj77df294q59ij-gettext-0.21/bin/msgmerge)
Program xgettext found: YES (/nix/store/ahb1jl345mpn3v8my8aj77df294q59ij-gettext-0.21/bin/xgettext)
Configuring config.h using configuration
Program xsltproc found: NO

meson.build:2413:2: ERROR: Program 'xsltproc' not found or not executable

A full log can be found at /build/glib-2.74.1/build/meson-logs/meson-log.txt
```

### Steps To Reproduce
1. Use `nixos-unstable` to cross compile `glib` from `x86_64-linux` to `aarch64-linux`

### Expected behavior
`glib` should properly configure and compile.

### Screenshots
From Hydra
![image](https://user-images.githubusercontent.com/19699320/202876976-6d691a4d-25a2-4bbf-a7e3-5bc6688c1d02.png)

### Additional context

This was found on my Hydra instance running under NixNG and `nixos-unstable`.

[View raw logs](http://hydra.expidusos.com/log/qhvlzm14hyayqx20n7s47zkn5grkv4cf-glib-aarch64-unknown-linux-gnu-2.74.1.drv)

### Notify maintainers

@lovek323 @7c6f434c 

### Metadata

*n/a: see additional comments*

**Comment by NickCao** [comment]
Already fixed by https://github.com/NixOS/nixpkgs/pull/200760 (currently in staging)

**Comment by RossComputerGuy** [comment]
Alright, good to see that. I'll close the issue as this is solved.
