### ISSUE TITLE
Darktable not recognizing Sony A7 camera

### ISSUE THREAD

**Issue by mkroehnert** [NixOS/nixpkgs#20209]
## Issue description

With the current Darktable version in  nixpkgs it is not possible for me to apply lens corrections, since the Sony A7 camera is not recognized and also not present in the list of available cameras.
The model identifier of the camera is ILCE-7.

However, Darktable on macOS recognizes the camera  since at least version 2.0.3.
My guess is, that this is probably related to the dependency on the lensfun library which is either outdated, or Darktable itself ships with more up to date camera and lens profile files.

### Steps to reproduce

1. download this photo https://plus.google.com/photos/114028348973158711682/album/6051066416705696785/6051066423977314866
2. open Darktable, select 'Import -> Directory', and import the directory containing the downloaded file
3. open darkroom mode by double clicking on the imported photo
4. go to the 'correction group' (second icon from the right; below the histogram)
5. open the 'lens correction' module
6. the lens is detected correctly but the camera model is missing (the model is also not available in the dropdown menu), thus making it impossible to apply any lens corrections

## Technical details

* System: NixOS: 17.03pre94121.210b3b3 (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre94694.fa4167c"

**Comment by NeQuissimus** [comment]
I sent in a PR, which fixes your issue.
I updates Darktable, while I was at it.
Took a while because lensfun changes their build system but it should be good now :) Enjoy!

**Comment by mkroehnert** [comment]
@NeQuissimus thanks for the fast response.
I am going to test the updated version and report back, once PR #20220 is merged.

**Comment by mkroehnert** [comment]
Thank you very much for the quick update.
I can confirm that my issue has been resolved.
