### ISSUE TITLE
Strange error when looking for ghcjs packages

### ISSUE THREAD

**Issue by simendsjo** [NixOS/nixpkgs#20201]
## Issue description

```
error: anonymous function at /nix/store/4gy7vzsdny8xs5ksqhnnmk0pvji9pq1g-nixos-16.09.929.80cbb8a/nixos/pkgs/development/haskell-modules/hackage-packages.nix:51506:6
  called without required argument ‘ghci’, at
  /nix/store/4gy7vzsdny8xs5ksqhnnmk0pvji9pq1g-nixos-16.09.929.80cbb8a/nixos/lib/customisation.nix:56:12
```

### Steps to reproduce

Run `nix-env -qaP -A nixos.haskell.packages.ghcjs`

## Technical details

* System: 16.09.929.80cbb8a (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.929.80cbb8a

**Comment by Profpatsch** [comment]
It’s a bug in that particular version of `hackage-packages.nix` that is fixed on master.

Generally all packages from hackage are available for ghc/ghcjs, though some might fail. So just type in the package you want to install (same name as on hackage). If something doesn’t build, don’t hesitate to open an issue and mention me.
