### ISSUE TITLE
Hosts: force adding hostname to ::1 causes issues with dnsmasq

### ISSUE THREAD

**Issue by voidzero** [NixOS/nixpkgs#202097]
https://github.com/NixOS/nixpkgs/blob/b68a6a27adb452879ab66c0eaac0c133e32823b2/nixos/modules/config/networking.nix#L174-L189

Here, adding the hostname to ::1 causes dnsmasq to respond to queries for the hostname with ::1:

```
$ host foobar
foobar.local.lan has address 192.168.1.1 # router running nixos
foobar.local.lan has address ::1 # it shouldn't do this
```
@kira-bruneau can you take a look please?

**Comment by voidzero** [comment]
In short - I don't want hosts to contain `::1 localhost localhost.localdomain foobar`

**Comment by kira-bruneau** [comment]
I'm not that familiar with this module, but I could take a look. Was there a specific reason you pinged me? It looked like @primeos added this.

**Comment by voidzero** [comment]
@kira-bruneau Oh! Sorry about that. I followed the suggestion of someone to issue 'git blame' on a file in order to figure out who the last maintainer was. I'm new to Nix and NixOS and I really don't know how to properly find the right maintainer here yet. My apologies! :sweat_smile:

**Comment by kira-bruneau** [comment]
No worries! This almost seems like a bug in dnsmasq (because it's not also returning 127.0.0.1)

**Comment by voidzero** [comment]
It's doing this because of the fact that I'm using it a DNS server which uses /etc/hosts to answer to DNS requests. Not a bug, a feature : )

**Comment by primeos** [comment]
> In short - I don't want hosts to contain ::1 localhost localhost.localdomain foobar

You should be able to use something like this (not tested):
```
networking.hosts = {
  "127.0.0.1" = lib.mkForce [ ];
  "::1" = lib.mkForce [ ];
}
```

Please re-open if something like this doesn't work.

> It's doing this because of the fact that I'm using it a DNS server which uses /etc/hosts to answer to DNS requests. Not a bug, a feature : )

A bit of an "interesting" setup... :D But dnsmasq hopefully also has an option not to answer queries for addresses like `::1`.

**Comment by voidzero** [comment]
Hi @primeos thanks. There is an option to not respond to such queries (`rebind-localhost-ok`), but these hostnames are also used for, as it says in the man page, "black hole servers", and as such blocking it might disable such services.

I already tried to redefine 127.0.0.1 and ::1 in the way you suggested, but without the `lib.mkForce`. Using that, it seems to does the trick. Thank you. : )
