### ISSUE TITLE
Python 3.10.8 pointer being freed was not allocated

### ISSUE THREAD

**Issue by HolgerPeters** [NixOS/nixpkgs#202155]
### Describe the bug

Python 3.10.8's REPL  crashes another time with `pointer being freed was not allocated`.

```
Python 3.10.8 (main, Nov  5 2022, 22:39:44) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 36./11
3.272727272727273
>>> 2022-1953
69
>>> python(1572,0x1ebe7e500) malloc: *** error for object 0x104cd3ee4: pointer being freed was not allocated
python(1572,0x1ebe7e500) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    1572 abort      python
```

### Steps To Reproduce
1. have Python REPL open with a few "pocket calculator" expressions
2. forget about open REPL
3. come back to computer to find segfault

I should note that this isn't happening every time.

### Notify maintainers

@FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
% nix-shell -p nix-info --run "nix-info -m"
these 2 paths will be fetched (0.01 MiB download, 0.11 MiB unpacked):
  /nix/store/6wszgsh6igfr953q3m0c30mjhnyv2gss-DarwinTools-1
  /nix/store/zla64n0bgd7mi62813ghm8268r4q3wzq-nix-info
copying path '/nix/store/6wszgsh6igfr953q3m0c30mjhnyv2gss-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/zla64n0bgd7mi62813ghm8268r4q3wzq-nix-info' from 'https://cache.nixos.org'...
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - channels(holger): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by siddharthverma314** [comment]
I'm facing the same issue after a recent update. I've pasted the result of `nix-shell -p nix-info --run "nix-info -m"` below:

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by tjni** [comment]
Would it be possible to attach `lldb` to the process, type `continue` to let it run, and extract a backtrace when it crashes?

**Comment by tjni** [comment]
I have some hope that this will also be fixed by https://github.com/NixOS/nixpkgs/pull/151090 (in staging currently).

**Comment by tjni** [comment]
I'm going to optimistically close this now that https://github.com/NixOS/nixpkgs/pull/151090 has made it to `master`. Please reopen if you can still reproduce the issue.

**Comment by sersorrel** [comment]
I confirm that this is fixed in unstable now (the issue originally being reproducible by resizing the window a couple of times or moving the terminal emulator to another display and back).
