### ISSUE TITLE
Provide better defaults for packages with plugins or useful hints

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nixpkgs#2021]
As mentioned in #1756, some packages are kind of downgrading now.
I'll be talking about Firefox as that's what actually hit me, not sure about other packages.

I believe that `firefox-with-plugins` should be the default one. We can call them `firefox` and `firefox-vanilla` or something like this. That's what most of the users expect, I'm sure.

Alternatively, we can make nix-env _suggest_ other versions of this same package interactively. E.g. if I do `nix-env -i firefox` it asks me whether I want `firefox` or `firefox-with-plugins`, and those, who know what they want can use `-A`.
I'm not sure how to properly implement this, as matching by a prefix is definitely a bad idea. Maybe add an attribute to package expressions called `suggested` or `seeAlso` and if you `nix-env -i` a package with such an attribute you get a list of suggestions.

**Comment by zimbatm** [comment]
Closing as `firefox = wrapFirefox firefox-unwrapped {}` in master. I believe that the rest of the repository will converge over time.
