### ISSUE TITLE
Missing licenses in wordpressPackages set

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#202191]
## Issue description

The package with `wordpressPackages` that are automatically fetched carry no license.

### Steps to reproduce

````
nix-repl> wordpressPackages.plugins.gutenberg.meta.license
error: attribute 'license' missing

       at «string»:1:1:

            1| wordpressPackages.plugins.gutenberg.meta.license
             | ^
````

cc @onny

**Comment by mweinelt** [comment]
Poking upstream does not seem to yield anything. They did indicate they wouldn't support this use case, so what are you expecting from them?

**Comment by onny** [comment]
I talked to the authors of wp4nix and they are happy for new contributions. It would be nice if the wp4nix script would somehow handle license informations, for example by manually defining them. Not quite sure yet how to implement it

**Comment by mweinelt** [comment]
If we don't know the licenses to these packages we honestly cannot keep them around. For example, it is absolutely unclear, whether we have a license to even redistribute them.

Of course upstream will take patches, but they're not exactly in the same boat we are.

I think your attitude towards the whole licensing situation around wp4nix/nc4nix and its resulting packages is alarming.

**Comment by onny** [comment]
As written [here](https://github.com/NixOS/nixpkgs/issues/238402): Fixing this for Wordpress packages and themes (wp4nix) and Nextcloud apps (nc4nix) in a foreseeable time exceeds my skills and competence. Therefore I would like to offer to add a `broken` flag to these package sets and remove them for the next release 23.11 if it's not resolved by then.

**Comment by mohe2015** [comment]
Couldn't we mark them as unfree so they don't get cached on hydra but people can still use them if they want? Unfortunately it seems like the wordpress plugins repository https://wordpress.org/plugins/ doesn't seem to provide the license information in an easy manner. And I don't know whether it is stored somewhere else or can even be extracted from the derivation without import-from-derivation.

**Comment by mohe2015** [comment]
Actuallly we seem to be safe in theory. https://wordpress.org/plugins/developers/ claims
> Your plugin must be compatible with the [GNU General Public License v2](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses), or any later version. We strongly recommend using the same license as WordPress — “GPLv2 or later.”

**Comment by mweinelt** [comment]
In an ideal world, that would hold true, but it is up to the user and distributor to validate the final outcome. I therefore think this situation remains unresolved.
