### ISSUE TITLE
rocksdb core-dumps on certain x86-64 CPUs

### ISSUE THREAD

**Issue by jibbs02** [NixOS/nixpkgs#202209]
### Describe the bug
The `rocksdb` derivation enables `SSE4.2` for all x86 Linux platforms ([nixpkgs src](https://github.com/erikarvstedt/nixpkgs/blob/e32b81f3b33e62a6ea1930ecf12c90ee4d406254/pkgs/development/libraries/rocksdb/default.nix#L51)).
This causes `rocksdb` to fail on CPUs that don't support `SSE4.2`.

Example CPU that fails to run `rocksdb`:
**AMD G-T56N 64-bit dual core on AMD Fusion Controller Hub A55E Chipset** Hardware: **[fit-PC3](https://www.fit-pc.com/web/products/specifications/fit-pc3-models/?model%5B%5D=fit-PC3-T56N-WB-FM4U)**

### Steps To Reproduce

1. Use the system `x86_64-linux` in configuration
2. Configure the package `electrs`. I am using nix-bitcoin for this
3. Deploy the changes in nix-bitcoin on AMD G-T56N 64-bit dual core chip

### Expected behavior
Electrs should start up and run. Instead it throws a core-dump.

Systemd journal:
```
nix-home-node systemd[1]: Started electrs.service.
nix-home-node kernel: traps: electrs[2862259] trap invalid opcode ip:7f80b0cc2505 sp:7ffec1460a20 error:0 in librocksdb.so.6.23.3[7f80b097f000+5b2000]
nix-home-node systemd[1]: electrs.service: Main process exited, code=dumped, status=4/ILL
nix-home-node systemd[1]: electrs.service: Failed with result 'core-dump'.
```

### Additional context
Here's my [complete systemd journal](https://pastebin.com/CVVKhCUR).

### Notify maintainers
@adev @magenbluten

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
[operator@nix-home-node:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/x8mymrkpsmpwyvqssjbwsq851kscf1kw-bash-interactive-5.1-p16-dev
copying path '/nix/store/x8mymrkpsmpwyvqssjbwsq851kscf1kw-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.77, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05-small"`
 - nixpkgs: `/var/src/nixpkgs`
```

**Comment by prusnak** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/202252
