### ISSUE TITLE
`qrenderdoc` in renderdoc package: Segmentation fault

### ISSUE THREAD

**Issue by KiruyaMomochi** [NixOS/nixpkgs#202291]
### Describe the bug
I tried to run `qrenderdoc` from `renderdoc` package, but I always get "Segmentation fault" (`SIGSEGV`). On the other hand, `renderdoccmd` command works correctly.

### Steps To Reproduce
1. `nix profile install nixpkgs#renderdoc`
2. `qrenderdoc`
3. Get `fish: Job 1, 'qrenderdoc' terminated by signal SIGSEGV (Address boundary error)`

### Expected behavior

The software runs correctly with GUI shown on my screen.

### Screenshots

N/A

### Additional context

- I also have tried #191978 from @jansol but it does not work too.
- I tried setting CMake built type to debug, but still can't get function signature from stack trace, so maybe this problem come from other place?
- [strace log](https://github.com/NixOS/nixpkgs/files/10063291/qrenderdoc-strace.log)

### Notify maintainers

No maintainers.

### Metadata

```console
kyaru@gourmet ~/Project> nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.11 (Raccoon), 22.11.20221121.af50806`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - channels(kyaru): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jansol** [comment]
It's been ages since I touched renderdoc, but since it's specifically the GUI that crashes it's probably worth checking if it is related to the Qt version it is built against.

**Comment by KiruyaMomochi** [comment]
Yes this is related to Qt, see https://github.com/baldurk/renderdoc/issues/2752.
This has been fixed in upstream and works for me after setting rev in nixpkgs, thanks.

**Comment by KiruyaMomochi** [comment]
https://github.com/NixOS/nixpkgs/pull/204552
