### ISSUE TITLE
mastodon regularly crashes with "rb_vm_insn_addr2insn: invalid insn address"

### ISSUE THREAD

**Issue by turion** [NixOS/nixpkgs#202215]
### Describe the bug

The mastodon puma service frequently crashes with an error message like this:

```
Nov 21 18:05:24 manuelbaerenz puma[1018998]: /nix/store/1m8li3dkfj33kk4xhx6bhjbqi6y9bq6x-mastodon-gems-4.0.2/lib/ruby/gems/3.0.0/gems/sanitize-6.0.0/lib/sanitize.rb:204: [BUG] rb_vm_insn_addr2insn: invalid insn address: 0x00007f0646b56e20
Nov 21 18:05:27 manuelbaerenz puma[1018976]: /nix/store/1m8li3dkfj33kk4xhx6bhjbqi6y9bq6x-mastodon-gems-4.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/core_ext/hash/indifferent_access.rb:10: [BUG] rb_vm_insn_addr2insn: invalid insn address: 0x00007f0646b56e20
```

### Steps To Reproduce
1. `services.mastodon.enable = true;`
2. `journalctl | grep BUG`
3. See lines as described above

### Additional context

This is probably an internal ruby bug, but since I didn't find it discussed anywhere else, I'm suspecting that it might be related to nixos in some way. I reported it upstream: https://bugs.ruby-lang.org/issues/19140

I'm wondering whether any other ruby applications on recent nixos-unstable run into that problem.

I'd expect that anyone running a Mastodon instance from 4.0.2 upwards with some regular load should experience these crashes. If not, I'm very puzzled.

### Notify maintainers

CC @erictapen @happy-river @Izorkin 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.72, NixOS, 22.11 (Raccoon), 22.11.20221121.7da50a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/k903flv5a8fj32mh4k0qkhmg1xjhs2g1-source`

**Comment by Izorkin** [comment]
I did not find such an error on my instance.

**Comment by turion** [comment]
FWIW, my ruby version should be:

```
# /nix/store/yfbi30xd53mnsh4ax1zppmr5bsr2r669-ruby-3.0.4/bin/ruby --version
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
```

**Comment by turion** [comment]
> I did not find such an error on my instance.

Are you running mastodon 3.5 or 4.0?

**Comment by Izorkin** [comment]
> Are you running mastodon 3.5 or 4.0?

Ruby - 3.0.4
Mastodon - 4.0.2

**Comment by turion** [comment]
Very strange. There is next to no mention of this bug in the internet. Why am only I running into it? I tried to rule out cross compilation by rebuilding the system from the server itself. Can it be a hardware fault? A memory or disk fault?

**Comment by Izorkin** [comment]
Have you tried rebooting the server?
Try checking physical memory. 
There are no other variants.

**Comment by turion** [comment]
I rebooted now. Maybe it's really a volatile fault, I haven't had 502s since. :crossed_fingers:
