### ISSUE TITLE
nix fails to build on Hydra (aarch64-darwin)

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#202251]
### Steps To Reproduce
1. build *nix*

### Build log

https://hydra.nixos.org/build/203876466/nixlog/1

### Additional context

Not reproducible on my machine.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by marsam** [comment]
I think it's related to https://github.com/NixOS/nix/issues/3605

**Comment by vcunat** [comment]
It succeeded after restarting.  (so the log above got overwritten, too)
We also had some transient failure on `x86_64-linux`.

**Comment by wegank** [comment]
And now it fails again due to `aws-sdk-cpp-nix`.

**Comment by vcunat** [comment]
It succeeded after restarting. (so the log above got overwritten, too)

**Comment by nmattia** [comment]
Just had the same failure on recent master ([68403fe04f6c85853ddd389c9e58dd9b9c8b0a36](https://github.com/NixOS/nixpkgs/commit/68403fe04f6c85853ddd389c9e58dd9b9c8b0a36))

```
[ 93%] Linking CXX shared library libaws-cpp-sdk-s3.dylib
[ 93%] Built target aws-cpp-sdk-s3
make: *** [Makefile:136: all] Error 2
error: builder for '/nix/store/pwc13flk4yzzgmj8xwmkpnkbac5hiili-aws-sdk-cpp-1.9.294.drv' failed with exit code 2;
       last 10 log lines:
       > [  FAILED  ] DirectoryTreeTest.CreateDirectoryIfNotExistedTest
       >
       > 11 FAILED TESTS
       > make[2]: *** [aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/build.make:881: aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests] Error 1
       > make[2]: *** Deleting file 'aws-cpp-sdk-core-tests/aws-cpp-sdk-core-tests'
       > make[1]: *** [CMakeFiles/Makefile2:396: aws-cpp-sdk-core-tests/CMakeFiles/aws-cpp-sdk-core-tests.dir/all] Error 2
       > make[1]: *** Waiting for unfinished jobs....
       > [ 93%] Linking CXX shared library libaws-cpp-sdk-s3.dylib
       > [ 93%] Built target aws-cpp-sdk-s3
```

will try to restart and see if it helps

**Comment by vcunat** [comment]
Now the same build succeeded after restarting: https://hydra.nixos.org/build/206157991
(at least I think it was the same one)

**Comment by nmattia** [comment]
Appears to be solved now! @wegank I'm closing because it looks like it was transient, but feel free to reopen.
