### ISSUE TITLE
bun fails at startup

### ISSUE THREAD

**Issue by jkozak** [NixOS/nixpkgs#202331]
### Describe the bug
bun fails at startup

### Steps To Reproduce
```console
$ nix-shell -p bun

[nix-shell:~]$ bun
Illegal instruction (core dumped)
```

### Expected behavior
bun starts

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.05 (Quokka), 22.05.4274.cf63ade6f74`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(jk): `""`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jkozak** [comment]
Interestingly this works fine on my laptop, running also running nixos:

```console
$ nix-shell -p bun

[nix-shell:~]$ bun
bun: a fast bundler, transpiler, JavaScript Runtime and package manager for web software.

  dev       ./a.ts ./b.jsx        Start a bun Dev Server
  bun       ./a.ts ./b.jsx        Bundle dependencies of input files into a .bun

  create    next ./app            Start a new project from a template (bun c)
  run       test                  Run a package.json script or executable
  install                         Install dependencies for a package.json (bun i)
  add       astro                 Add a dependency to package.json (bun a)
  remove    browserify            Remove a dependency from package.json (bun rm)

  upgrade                         Get the latest version of bun
  completions                     Install shell completions for tab-completion
  discord                         Open bun's Discord server
  help                            Print this help menu

[nix-shell:~]$
exit
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.76, NixOS, 22.05 (Quokka), 22.05.3977.f09ad462c5a`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mathletedev** [comment]
Bun requires a CPU that has AVX2 instructions. See https://github.com/oven-sh/bun/issues/67
There is a build of Bun designed for other CPUs, `bun-baseline`, but it isn't in the Nix repositories.
Unfortunately, my machine has an older CPU without AVX2 so I can't run Bun either. Installing the executable directly from GitHub (https://github.com/oven-sh/bun/releases/download/bun-v0.2.2/bun-linux-x64-baseline.zip) results in an error with the linker or interpreter.
Hope this input helps

**Comment by jkozak** [comment]
Yes, that's it.  Thanks very much!  Should have RTFM'd the upstream docs.

As a quick hack I created a `bun-baseline` package which builds the `baseline` variant - this does actually start but I haven't tried to do anything substantive.  Let me know if you'd like a copy.

**Comment by mathletedev** [comment]
I opened a PR for a new bun-baseline package a few months ago: https://github.com/NixOS/nixpkgs/pull/203379, but it's taking a while to get reviewed. Might make it easier to install in the future!
