### ISSUE TITLE
Generalize dockerTools to other container platforms

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#20238]
It would be nice to do our part in reducing everyone's dependence on docker, in favor of tools like rkt and so on. I'm wondering if anyone would be opposed to renaming `dockerTools` to `containerTools` (possibly with an alias) and then iteratively adding support for e.g., rkt's ACI format. It seems like there's a lot of potential shared code between the different ecosystems, and the main thing that differs is the output format and a few smaller details.

cc @lethalman

**Comment by lethalman** [comment]
Sure agreed. But for the design I wouldn't suggest a common front API. I'm pretty sure it will be more headaches than anything. Rather have dockerTools, rktTools that use some common shared nix code.

**Comment by copumpkin** [comment]
Fair enough!

**Comment by Profpatsch** [comment]
There is the [container workgroup](https://nixos.wiki/wiki/Workgroup:Container) now, rkt has been deprecated in favor of `OCI` images, docker supports `OCI` images as well.

The next step would be to convert `dockerTools` to produce `OCI` images.
