### ISSUE TITLE
gnome-keyring-daemon uses 100% CPU

### ISSUE THREAD

**Issue by wahjava** [NixOS/nixpkgs#202313]
### Describe the bug

As [mentioned](https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/123) in the gnome-keyring-daemon bug tracker, it uses 100% CPU

### Steps To Reproduce
1. ...
2. ...
3. ...

### Expected behavior

It should idle, instead of running that poll/read sequence taking 100% CPU

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20221120.690ffff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/0p5dnqxcz5zwkn24mjaysddx6j3q269i-source`
```

**Comment by bobby285271** [comment]
690ffff does not contain https://github.com/NixOS/nixpkgs/pull/201229, can you upgrade your system to a more recent commit and see if that resolves your problem?

**Comment by wahjava** [comment]
Thanks, the overlay fixes it. Sorry for opening this issue, I searched for `gnome-keyring-daemon` instead of `gnome-keyring`
