### ISSUE TITLE
pam_p11 broken in 22.11

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/nixpkgs#202312]
### Describe the bug
pam_p11 causes login segfault in NixOS 22.11. GDM and Gnome lock screen are also affected.

### Steps To Reproduce
1. ```security.pam.p11.enable = true;```
2. Attempt to log in on the console or run ``gdb login``:

```
login: sb

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e2c2c4 in pthread_rwlock_wrlock@GLIBC_2.2.5 () from /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff7e2c2c4 in pthread_rwlock_wrlock@GLIBC_2.2.5 () from /nix/store/4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163/lib/libc.so.6
#1  0x00007ffff79374d9 in CRYPTO_THREAD_write_lock () from /nix/store/fzb7khbic8vpcr3m69v6y8qp6jqspdgw-openssl-1.1.1s/lib/libcrypto.so.1.1
#2  0x00007ffff7896e61 in ENGINE_finish () from /nix/store/fzb7khbic8vpcr3m69v6y8qp6jqspdgw-openssl-1.1.1s/lib/libcrypto.so.1.1
#3  0x00007ffff78b9d94 in EVP_PKEY_free () from /nix/store/fzb7khbic8vpcr3m69v6y8qp6jqspdgw-openssl-1.1.1s/lib/libcrypto.so.1.1
#4  0x00007ffff7a2bd13 in key_find.part () from /nix/store/4962m52qlc9crm6ccq6bg23z50yj67m8-pam_p11-0.3.1/lib/security/pam_p11.so
#5  0x00007ffff7a2c343 in pam_sm_authenticate () from /nix/store/4962m52qlc9crm6ccq6bg23z50yj67m8-pam_p11-0.3.1/lib/security/pam_p11.so
#6  0x00007ffff7fafdf2 in _pam_dispatch () from /nix/store/hk0qw5ynzy1h7w4vn4bg6hwirf2a2y56-linux-pam-1.5.2/lib/libpam.so.0
#7  0x00007ffff7faf670 in pam_authenticate () from /nix/store/hk0qw5ynzy1h7w4vn4bg6hwirf2a2y56-linux-pam-1.5.2/lib/libpam.so.0
#8  0x0000000000403ee4 in main ()
```

### Metadata
22.11.git.00b9de629bf

Bug was not present in 22.05.

**Comment by ajs124** [comment]
Can you open a pull request with that patch?

**Comment by ajs124** [comment]
It's generally preferred to do basically everything through PRs, so some basic CI checks can run & maintainers can be pinged automatically. We can just self-merge though. I created #202345 containing your diff and adding a comment for explanation.

**Comment by FossPrime** [comment]
This seems to be whats causing my 22.11-beta19 install on an Alder Lake 12700H (no gpu) to not boot into GDM.

This is a pretty heinous issue that should be tested for. The graphical installer doesn't install Vim, WPA_Supplicant or anything useful for figuring out what went wrong, despite having Vim and WPA Supplicant available on the installation media/calamares.
