### ISSUE TITLE
fnm doesn't work without steam-run

### ISSUE THREAD

**Issue by jankaifer** [NixOS/nixpkgs#202401]
### Describe the bug
node binaries installed with fnm are not patched.

Tried both `unstable` and `22.05`.

### Steps To Reproduce
```bash
nix-shell -p fnm steam-run
eval "$(fnm env --use-on-cd)"
fnm use v16.0.0
node --version # broken
steam-run node --version
v16.0.0
```
### Expected behavior
It should work without steam-run

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.9, NixOS, 22.05 (Quokka), 22.05.git.cf63ade6f74`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/persist/home/pearman/dev/jankaifer/nixos/modules/nixpkgs`
```

**Comment by JanKaifer** [comment]
My config: https://github.com/JanKaifer/nixos/blob/438d501cb890441c8747511cca80e279dfa04225/machines/vercelframe/configuration.nix

**Comment by JanKaifer** [comment]
cc @kidonng

**Comment by JanKaifer** [comment]
For now, I just have these aliases:
```
pnpm='steam-run pnpm'
node='steam-run node'
corepack='steam-run corepack'
```
But it feels hacky.

**Comment by jankaifer** [comment]
This is not a steam issue. It's more of a general unpatched binaries issue.

Anyway I've been using https://github.com/Mic92/nix-ld for while now and it solved all my issues with `node`.

**Comment by SuperSandro2000** [comment]
This is expected when downloading pre-compiled binaries. You can use something like nix-ld or steam-run or others to work around this.

**Comment by jankaifer** [comment]
To me it seems like a broken package if it doesn't work unless you implement some workaround that is not documented anywhere (spent non-trivial amount of time by figuring out why it's broken and how to fix it).

Is it at least possible to add some "installation notes" into the official nixpkgs package search [here](https://search.nixos.org/packages?channel=24.05&show=fnm&from=0&size=50&sort=relevance&type=packages&query=Fnm)?

Do you know whether this was already discussed somewhere (I was not able to find it)? This probably is cross-package issue that is not specific to fnm.

**Comment by SuperSandro2000** [comment]
Feel free to open a PR that expands the description to mention this.

IDK, generally any package manager that installs binaries is broken like this.
