### ISSUE TITLE
Prosody NixOS tests time out

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#202458]
### Describe the bug
The NixOS tests for prosody and prosody-mysql time out on hydra, unnecessarily delaying the channel by about 9 hours.

### Steps To Reproduce
e.g.
https://hydra.nixos.org/build/199758102
https://hydra.nixos.org/build/199758852

### Expected behavior
Tests should finish promptly or fail, not stall the channel.

### Notify maintainers
@Izorkin @NinjaTrappeur 

### Metadata
Happens on both nixos-22.11 and nixos-unstable.

**Comment by NinjaTrappeur** [comment]
I'm on it.

**Comment by NinjaTrappeur** [comment]
https://github.com/NixOS/nixpkgs/pull/202491
