### ISSUE TITLE
haskellPackages.purescript_0_10_1 build breaks at the test stage

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#20240]
## Issue description

When i try to install purescript-0.10.1,
it wants to build it and falls (in the end)
with an error message —
<pre>tests: npm: callProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite tests: FAIL
Test suite logged to: dist/test/purescript-0.10.1-tests.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for ‘/nix/store/psa[...]r5kj-purescript-0.10.1.drv’ failed with exit code 1</pre>
I also tried to install nodejs before purescript as in
https://pr06lefs.wordpress.com/2015/01/11/get-started-with-purescript-on-nixos/
with approximately the same result.

Switched to unstable (17.03pre94694.fa4167c). Result is the same.

### Steps to reproduce

Just try to install haskellPackages.purescript_0_10_1

## Technical details

* System: (NixOS: `nixos-version`)
16.09.824.e4fb65a (Flounder)
17.03pre94694.fa4167c (Gorilla)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4
nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.940.8a5c376"
"17.03pre94694.fa4167c"

## Solution (i'm not sure)?...
Do we need something like
purescript_0_10_1 = dontCheck super.purescript_0_10_1;
in pkgs/development/haskell-modules/configuration-common.nix
to disable tests?

**Comment by jazmit** [comment]
+1

**Comment by jazmit** [comment]
That exact change fixed it for me.

**Comment by jazmit** [comment]
You can get purescript 0.10.1 up and running by cloning the repo with the fix in, then `sudo nixos-rebuild switch -I nixpkgs=/path/to/repo`

**Comment by comonoid** [comment]
Thank you for testing!
May be we should wait for nixos-unstable builds to close this ticket?...
(Certainly i can use master branch. But most people do not want it?)

**Comment by comonoid** [comment]
Upgraded to 17.03pre96298.b09435e (Gorilla) where we have purescript-0.10.2
At the first sight, all works fine.
