### ISSUE TITLE
Cannot build Intellij IDEA

### ISSUE THREAD

**Issue by choochootrain** [NixOS/nixpkgs#20248]
## Issue description
Its not clear if this is the wrong way to do this or not, but I haven't been able to start a `nix-shell` with Intellj IDEA installed in it.

### Steps to reproduce
```
$ nix-shell -p idea --show-trace
error: while evaluating the attribute ‘nativeBuildInputs’ of the derivation ‘shell’ at /etc/nixos/nixpkgs/pkgs/build-support/trivial-builders.nix:10:14:
cannot coerce a set to a string, at /etc/nixos/nixpkgs/pkgs/build-support/trivial-builders.nix:10:14
```

## Technical details

```bash
$ nixos-version
17.03.git.fa4167c (Gorilla)

$ nix-env --version
nix-env (Nix) 1.11.4

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.git.fa4167c"
```

Same thing happens on master of nixpkgs.

If I could get a pointer on what I'm supposed to be looking at from this trace I can take a shot at this.

**Comment by gebner** [comment]
The attribute is called `idea.idea-community`:
```
$ nix-shell -p idea.idea-community
```

**Comment by choochootrain** [comment]
worked, thanks! would love to know how to parse that trace from `nix-shell` though

**Comment by NeQuissimus** [comment]
Generally, if you see `cannot coerce a set to a string` or something telling you there is a function when a list/set/value was expected, it means, you did not go deep enough into the attributes. It is a little hard to debug...
