### ISSUE TITLE
dotnet 3.1 is EOL

### ISSUE THREAD

**Issue by mdarocha** [NixOS/nixpkgs#202572]
## Issue description

Since December 13, .NET 3.1 is unsupported, as per https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

We should work on updating packages that make use of it, and deprecating this dotnet version

### Steps to reproduce

See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

### Replacing packages using `dotnet-sdk_3`

- [x] ./pkgs/applications/blockchains/wasabibackend/default.nix - https://github.com/NixOS/nixpkgs/pull/209429
- [x] ./pkgs/tools/games/opentracker/default.nix - https://github.com/NixOS/nixpkgs/pull/209427
- [x] ./pkgs/servers/web-apps/baget/default.nix - https://github.com/NixOS/nixpkgs/pull/222006
- [x] ./pkgs/development/tools/azure-functions-core-tools/default.nix - https://github.com/NixOS/nixpkgs/pull/209593
- [x] ./pkgs/development/compilers/inklecate/default.nix - https://github.com/NixOS/nixpkgs/pull/208554
- [x] ./pkgs/development/dotnet-modules/python-language-server/default.nix - https://github.com/NixOS/nixpkgs/pull/209586
- [x] ./pkgs/applications/editors/vscode/extensions/ms-vsliveshare-vsliveshare/default.nix - https://github.com/NixOS/nixpkgs/pull/220704

cc @IvarWithoutBones @GGG-KILLER

**Comment by mdarocha** [comment]
Also we should probably update the documentation examples to refer to newer .NET versions.

**Comment by mdarocha** [comment]
> I don't know if we should address this at the same time, but .NET 5.0 has already hit EOL and it has no warnings at all:
> 
> https://github.com/NixOS/nixpkgs/blob/f9cdaba46e67f71663fe03c4174cab9f7b03520b/pkgs/development/compilers/dotnet/default.nix#L19

See https://github.com/NixOS/nixpkgs/issues/173115 :)

**Comment by GGG-KILLER** [comment]
Have checked the listed packages that depend on .NET Core 3.1:

- `wasabibackend`: if we update it, we'll be able to move it to .NET 6.0
- `alttpr-opentracker`: if we update it, we'll be able to move it to .NET 6.0
- `baget`: **still on .NET Core 3.1 on source** (will block full removal, we'll probably need to mark .NET Core 3.1 with a warning as deprecated or get rid of this package)
- `azure-functions-core-tools`: if we update it, we'll be able to move it to .NET 6.0
- `inklecate`: if we update it, we'll be able to move it to .NET 6.0
- `python-language-server`: repo has been archived, should be removed

**Comment by mdarocha** [comment]
What's the alternative to `python-language-server` then? I use it personally, for example.

And as for `baget`: is there any work done on the upstream to migrate it? Or should we remove the package as the upstream is not maintained?

I remember @IvarWithoutBones attempted to add a warning for .NET 5 in https://github.com/NixOS/nixpkgs/pull/175354 but it could not be merged, since throwing warnings caused ofborg to fail.

**Comment by mdarocha** [comment]
> * `wasabibackend`: if we update it, we'll be able to move it to .NET 6.0 (already in progress in [wasabiwallet: 2.0.1.3 -> 2.0.2 #202582](https://github.com/NixOS/nixpkgs/pull/202582))

Note that `wasabibackend` and `wasabiwallet` seem to be different packages

**Comment by JamieMagee** [comment]
The replacement for `python-language-server` is [`python-lsp-server`][1].

There are currently 2 packages that depend on `python-langauge-server` in nixpkgs:

- [`pyls-mypy`][2]
- [`pyls-black`][3]

Both of those packages currently have upstream PRs to migrate from `python-language-server` to `python-lsp-server`:

- https://github.com/tomv564/pyls-mypy/pull/52
- https://github.com/rupert/pyls-black/pull/37

Once those PRs are merged, and they are updated in nixpkgs, we can remove `python-language-server`.

[1]: https://github.com/python-lsp/python-lsp-server
[2]: https://github.com/tomv564/pyls-mypy
[3]: https://github.com/rupert/pyls-black

**Comment by JamieMagee** [comment]
I attempted to updated `allptr-opentracker` to `1.8.5`, which targets .NET 6.0, but there was an issue with the build. I opened an issue upstream: https://github.com/trippsc2/OpenTracker/issues/86

**Comment by JamieMagee** [comment]
The upstream maintainer for `baget` appears to be unresponsive right now. I think we need to wait and see if a supported fork appears: https://github.com/loic-sharma/BaGet/pull/717#issuecomment-1368544083

**Comment by GGG-KILLER** [comment]
> 

Looking into pyls-mypy and pyls-black, both seem to be unmaintained (former having the most recent commit in 2020 and latter in 2021).

Don't know if we should put much hope in having them move over to the maintained LSP

**Comment by GGG-KILLER** [comment]
> I attempted to updated `allptr-opentracker` to `1.8.5`, which targets .NET 6.0, but there was an issue with the build. I opened an issue upstream: [trippsc2/OpenTracker#86](https://github.com/trippsc2/OpenTracker/issues/86)

This is something we can solve temporarily by using `dotnet sln remove` in `prePatch` or `postPatch`, isn't it?

**Comment by JamieMagee** [comment]
> This is something we can solve temporarily by using `dotnet sln remove` in `prePatch` or `postPatch`, isn't it?

Yeah. I was hoping for an upstream fix, but we can patch in the meantime.

**Comment by JamieMagee** [comment]
> Looking into pyls-mypy and pyls-black, both seem to be unmaintained (former having the most recent commit in 2020 and latter in 2021).
> 
> Don't know if we should put much hope in having them move over to the maintained LSP.
> 
> UPDATE: Both seem to depend on [palantir's language server](https://github.com/palantir/python-language-server) which is Python-only, not microsoft's.

Lets replace them with their maintained forks

- [`pyls-mypy`][1] with [`pylsp-mypy`][2]
- [`pyls-black`][3] with [`python-lsp-black`][4]

Then remove `python-language-server` as it's unmaintained, and won't have any dependencies on it anymore.

[1]: https://github.com/tomv564/pyls-mypy
[2]: https://github.com/python-lsp/pylsp-mypy
[3]: https://github.com/rupert/pyls-black
[4]: https://github.com/python-lsp/python-lsp-black

**Comment by JamieMagee** [comment]
- #209582
- #209585

**Comment by mdarocha** [comment]
> Update on this, it seems like the VSCode live share extension also depends on 3.1:
> 
> https://github.com/NixOS/nixpkgs/blob/b096dcbd08536f4b753422c428f35c0cf24d70af/pkgs/applications/editors/vscode/extensions/ms-vsliveshare-vsliveshare/default.nix#L118-L121

I updated the todo list. Is there an update or a replacement of that package that bumps the used dotnet version?

**Comment by GGG-KILLER** [comment]
> I updated the todo list. Is there an update or a replacement of that package that bumps the used dotnet version?

I have downloaded the latest version of the extension and haven't found the binary being patched, I'm unsure if it is now being downloaded at runtime or if they replaced it entirely with js.

**Comment by GGG-KILLER** [comment]
After a quick check on the latest version of the liveshare extension, it seems like it no longer uses a .NET binary for the live share functionality and everything got reimplemented in javascript.

If someone else confirms this I think it's safe to just upgrade it and remove the .NET patching from it.

@jraygauthier @deviant, can any of you confirm this as package maintainers?

**Comment by JamieMagee** [comment]
That means the only remaining package to update is BaGet. What should we do? Apply patches to the existing package or migrate to [the maintained fork][1]?

[1]: https://github.com/pieroviano/BaGet

**Comment by mdarocha** [comment]
> That means the only remaining package to update is BaGet. What should we do? Apply patches to the existing package or migrate to [the maintained fork][1]?
> 
> 
> 
> [1]: https://github.com/pieroviano/BaGet

Migrating to the fork should be fine?

**Comment by GGG-KILLER** [comment]
> That means the only remaining package to update is BaGet. What should we do? Apply patches to the existing package or migrate to [the maintained fork](https://github.com/pieroviano/BaGet)?

I think we could migrate to the fork. The only thing that worries me a bit are the recent commit messages but I don't know if I'm just being a pedantic.

**Comment by mdarocha** [comment]
Unfortunately I had problems bulding the fork, I posted [a comment in the PR](https://github.com/loic-sharma/BaGet/pull/754) about the issues.

**Comment by GGG-KILLER** [comment]
I don't know if this is the place to discuss this, but should we really replace the official package by a fork that was only made for a PR and has no issues enabled (therefore no support)?

I think a better alternative would be to remove the package while a proper fork is found

**Comment by mdarocha** [comment]
That's probably the better course of action

**Comment by mdarocha** [comment]
I made a PR for removal of baget, after it we can remove .NET 3.1 completely from nixpkgs :)

**Comment by mdarocha** [comment]
And its done :)

**Comment by JamieMagee** [comment]
Thanks! See you all for .NET 7 EOL :joy:
