### ISSUE TITLE
Console app (and others) freeze when maximized ongnome 43.1 nixos 22.11 

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#202503]
### Describe the bug

@NixOS/gnome 

I already updated my system to `release-22.11` and it generally works well, but i have one bug so far:

When i maximize apps, some of them freeze when maximized. They don't seem to crash but the window's content visibly freezes.

### Steps To Reproduce

1. start gnome `console`
2. maximize by double-clicking the title bar or pressing alt+up
3. type stuff in the shell, observe that the window content is frozen and doesn't show the inputs
4. un-maximize it and see that the app indeed accepted the inputs.

This does not occur with all apps, only some. It also seems to work with `system monitor` most of the time, but `console` is my most reliable reproducer so far.

### Expected behavior

Maximizing an app does not make its window content freeze

### Screenshots

A screenshot of a frozen app would not show anything helpful

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager-21.11.tar.gz, nixos-21.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos````

**Comment by dasJ** [comment]
cc @jtojnar

**Comment by jtojnar** [comment]
Are you using Wayland or X11 session? (See e.g. `$XDG_SESSION_TYPE` environment variable.)

I can reproduce this consistently on unstable as well with GNOME Terminal, Boxes, Console and gedit (all GTK 3 apps) but not with GNOME Text Editor, Control Center or Calculator (GTK 4).

GTK version: 3.24.34

**Comment by tfc** [comment]
i am on x11
