### ISSUE TITLE
golangci-lint shells out to go

### ISSUE THREAD

**Issue by colin-arnott-xero** [NixOS/nixpkgs#202592]
### Describe the bug
while `golangci-lint` correctly builds, it shells out to the `go` executable, as such 

### Steps To Reproduce
steps to reproduce the behavior:
1. ensure `pkgs.go` is not installed on your system
2. `nix run nixpkgs#golangci-lint`
```
WARN Failed to discover go env: failed to run 'go env': exec: "go": executable file not found in $PATH
ERRO Running error: context loading failed: failed to load packages: failed to load with go/packages: err: go resolves to executable in current directory (./go): stderr:
```

### Expected behavior
it just works:
```
```

### Additional context
the repo does shell out to other binaries, but not as part of the `golangci-lint` binary, so those can likely be ignored

### Notify maintainers
@anpryl @manveru @mic92

### Metadata
```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 21.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(user): `"darwin, home-manager"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/lxfwcg0km6p3rrr307i9k6pgnc4brmzb-source`
```

**Comment by Mic92** [comment]
I don't think golangci-lint should hardcode a compiler since people might easily want to switch out the used go version. We also don't hardcode specific compilers in other areas for the same reason. cc @zowoq

**Comment by colin-arnott-xero** [comment]
I am thinking about this from a reproducibility perspective: a derivation must describe all of its dependencies, right? and if needed, one can override the input attrs:
```
pkgs.golangci-lint.override {
  go = pkgs.go_1_20;
};
```

**Comment by zowoq** [comment]
I think it would be rather surprising if it _didn't_ use the `go` in PATH.

```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
mkShell {
  buildInputs = [
    go_1_21
    golangci-lint 
  ];
}
```
```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
mkShell {
  buildInputs = [
    go_1_21
    (golangci-lint.override {
      go = pkgs.go_1_21;
    })
  ];
}
```

`nix run nixpkgs#golangci-lint` not working isn't ideal but at least it's a simple error, hardcoding or wrapping `go` makes it complicated.

**Comment by colin-arnott-xero** [comment]
counterpoint, what if two of my tools need different versions of go? this is the reason that while building python packages, you get eighty different versions of the rust compiler. I agree it is not optimal, but it is how I though I understood nix worked.

asking this differently, why is shelling out somehow fundamentally different to linking against a shared library. those are not "required" at compile time either. we could just load them dynamically too?

also, I have successfully merged changes like this to other tools that shell out, so this seemed non-controversial: #198048

**Comment by zowoq** [comment]
We can't handle every scenario.

> also, I have successfully merged changes like this to other tools that shell out, so this seemed non-controversial: https://github.com/NixOS/nixpkgs/pull/198048

Afraid it is now. I'm the `kubernetes` maintainer and I've removed `kubectl` and other deps from other packages several times because it's confusing, problematic (version skew), difficult to override and sometimes just unwanted bloat.

**Comment by colin-arnott-xero** [comment]
I am not looking to handle every scenario, I am more concerned with determinism and shipping broken packages. I get that optional dependencies are one thing, but `golangci-lint` does not function without `go`, and there is no indicating from the derivation that you MUST include a go binary in `PATH`.

I am also concerned that different maintainers have different policies on this, especially as it is undocumented, since it means that you do not know if a derivation is missing core dependencies. going to cc the reviewer that has merged a bunch of my changes: @SuperSandro2000.

meta question, why is having a dependency on `kubectl` or any binary dependency confusing, problematic, and difficult to override (seemed easy enough [above](https://github.com/NixOS/nixpkgs/issues/202592#issuecomment-1326178987))? especially, when this is exactly how it works for linked linked libraries?

**Comment by SuperSandro2000** [comment]
Yes, this is expected. Also you need gcc when some dependencies use cgo.



> meta question, why is having a dependency on `kubectl` or any binary dependency confusing, problematic, and difficult to override (seemed easy enough [above](https://github.com/NixOS/nixpkgs/issues/202592#issuecomment-1326178987))? especially, when this is exactly how it works for linked linked libraries?

Because you need to rebuild the package just to change the kubectl version which is not resource-friendly. 

I am working with ~~multiple~~ a lot kubernetes clusters at my work and requires different kubectl versions for the different versions they are running. If a k8s tool works with all of them at the same time and just needs different kubectl versions in PATH than not having it hardcoded in the wrapper is preferred and makes things easier for us.

Their are other tools which have similar problems like gox or many linters and static analyzers.

**Comment by zowoq** [comment]
Guess something like this might work? 
```diff
diff --git a/pkgs/applications/networking/cluster/helm/chart-testing/default.nix b/pkgs/applications/networking/cluster/helm/chart-testing/default.nix
index 016eb40745b..376551882f9 100644
--- a/pkgs/applications/networking/cluster/helm/chart-testing/default.nix
+++ b/pkgs/applications/networking/cluster/helm/chart-testing/default.nix
@@ -48,14 +48,10 @@ buildGoModule rec {
       --zsh <($out/bin/ct completion zsh) \
       --fish <($out/bin/ct completion fish) \

-    wrapProgram $out/bin/ct --prefix PATH : ${lib.makeBinPath [
-      coreutils
-      git
-      kubectl
-      kubernetes-helm
-      yamale
-      yamllint
-    ]}
+    wrapProgram $out/bin/ct \
+      --run "command -v helm >/dev/null || echo 'requires: helm' && exit 1" \
+      --run "command -v kubectl >/dev/null || echo 'requires: kubectl' && exit 1" \
+      --prefix PATH : ${lib.makeBinPath [ coreutils git yamale yamllint ]}
   '';

   meta = with lib; {

```
We could add something to `makeWrapper` if we want something nicer? e.g.
```
  wrapProgram $out/bin/ct \
    --needs helm kubectl \
    --prefix PATH : ${lib.makeBinPath [ coreutils git yamale yamllint ]}
```

**Comment by SuperSandro2000** [comment]
I don't think we need to track this. The program will most likely complain anyway if the program is missing in PATH and will abort.
