### ISSUE TITLE
prismlauncher: Split into wrapped and unwrapped derivations

### ISSUE THREAD

**Issue by hacker1024** [NixOS/nixpkgs#202545]
It's common to use custom builds of GLFW with Minecraft, for things like improved Wayland support.

At the moment, Prism Launcher is built and wrapped in a [single derivation](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/prismlauncher/default.nix). This means that overriding libraries such as GLFW, that aren't actually used in the build process but rather used by prebuilt copies of Minecraft at runtime, result in a binary cache miss - triggering local a rebuild of the entire launcher.

I propose that the wrapping pattern is implemented here, building the launch wrapper in a new derivation. This way, runtime dependencies can be changed without changing the hash of the launcher binary derivation.

**Comment by Minion3665** [comment]
This sounds like a good idea to me, let's do this
