### ISSUE TITLE
isync / mbsync: SSL error "Socket error: ... unexpected eof while reading"

### ISSUE THREAD

**Issue by JonathanReeve** [NixOS/nixpkgs#202595]
### Describe the bug

When checking mail with isync, using `mbsync -a`, and a gmail account, mbsync suddenly reports the errors, "Socket error: secure read from imap.gmail.com (142.251.163.109:993): error:0A000126:SSL routines::unexpected eof while reading" for each gmail account. 

It didn't used to do this. I've been checking mail using isync for years, without any issues, so I know everything's configured correctly. This just started happening after a recent update. 

[Here's my home-manager config which shows my configuration, if it applies.](https://github.com/JonathanReeve/dotfiles/blob/master/dotfiles/home.nix#L53)

I have a feeling this is SSL related, and not a problem with the isync / mbsync package itself, but I don't know. 

### Steps To Reproduce
1. Run `mbsync -a` with a gmail configuration. Or probably any other configuration which uses SSL
2. Notice that you get the error above. 

### Expected behavior
It should check mail without these errors. 

### Notify maintainers

@primeos @lheckemann

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.9, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(jon): `"nixos"`
 - channels(root): `"nixos-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by mfuchs1** [comment]
I can confirm this issue. I'm getting the same error. Sorry  - but I still haven't found a solution yet.

**Comment by primeos** [comment]
Seems to be a known issue with a patch available. Could someone test/confirm if https://github.com/NixOS/nixpkgs/pull/203227 fixes it?

**Comment by tshu-w** [comment]
I'm still facing this error with `mail.cstnet.cn` (198.18.1.29:993)
```
Socket error: secure read from mail.cstnet.cn (198.18.1.29:993): error:0A000126:SSL routines::unexpected eof while reading
```
