### ISSUE TITLE
marksman

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#202562]
**Project description**
marksman is a language server protocol for markdown documents

**Metadata**

* homepage URL: https://github.com/artempyanykh/marksman
* source URL: https://github.com/artempyanykh/marksman
* license: MIT
* platforms: Unix, Linux, Darwin

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/184873

**Comment by pinkcreeper100** [comment]
Understood, I should have checked
