### ISSUE TITLE
Cygwin: missing x86_64-cygwin in sbcl prevents any action

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#20254]
## Issue description
x86_64-cygwin is not an option in the file pkgs/development/compilers/sbcl/bootstrap.nix

Because of this, the evaluation fails and Is not possible to install anything.

I bypassed this just by putting 
    x86_64-cygwin = armv7l-linux;

Since I was NOT trying to install sbcl, it was not a problem. Windows binary are however available here http://www.sbcl.org/platform-table.html , so I think it can just be fixed adding an entry for cygwin.

**Comment by tohl** [comment]
commit 97b9c5407968aa9862fc3251841045d4d13b8157 should fix this

**Comment by matthewbauer** [comment]
Can we close this?
