### ISSUE TITLE
tlwg: 0.7.3

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#202651]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 0.6.4
desired version: 0.7.3

###### Notify maintainers

maintainers: @yrashk 

###### Note for maintainers

It's been several years since the dependency has been updated, and the latest release is a year old (https://github.com/tlwg/fonts-tlwg/releases/tag/v0.7.3).

I tried to do the low-hanging, quick update, but it did not work because of a error with autoreconf. I'm unfamiliar with the toolchain.

```nix
stdenv.mkDerivation rec {
  pname = "tlwg";
  version = "0.7.3";

  src = fetchFromGitHub {
    owner = "tlwg";
    repo = "fonts-tlwg";
    rev = "v${version}";
    sha256 = "sha256-hWiH5KJnYTdcrm+Kzn9HUQry8ry3SKzjA6/0536kCLQ=";
  };
  # ...
}
```

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/203014
