### ISSUE TITLE
nixos/matrix-synapse: use `registration_shared_secret_path`

### ISSUE THREAD

**Issue by RyanGibb** [NixOS/nixpkgs#202694]
As `services.matrix-synapse.settings.registration_shared_secret` says...
>https://github.com/NixOS/nixpkgs/blob/f10cdcf31dd2a436edbf7f0ad82c44b911804bc8/nixos/modules/services/matrix/matrix-synapse.nix#L237

In order to avoid putting secrets in the public nix store https://github.com/NixOS/nix/issues/8

https://github.com/matrix-org/synapse/pull/13614 adds support for `registration_shared_secret_path`, which allows us to point to a path with the shared secret. This would be a cleaner solution.

### Notify maintainers

From `teams.matrix.members`:
@ma27
@fadenb
@mguentner
@ekleog
@ralith
@dandellion
@sumnerevans

**Comment by Ma27** [comment]
FWIW `settings` is already a freeform type, so you can already use that option.

**Comment by RyanGibb** [comment]
Thank you @Ma27! I believe that resolves this
