### ISSUE TITLE
qt6Packages.qtools - binaries are in .dev output

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#202622]
### Describe the bug
qt6Packages.qttools contains a number of tools, that are also useful outside of package building. I am specifically thinking about qdbus and qdbusviewer.

In qt5, they are part of qttools.bin but with qt6, they are in qttools.dev which means bringing them into your environment causes a long list of other .dev dependencies to be brought in.

Cc: @nickcao

Reference: #202293

**Comment by NickCao** [comment]
I found that these tool kind of tools are declared in cmake as `qt_internal_add_app` or `qt_internal_add_tool`, there must be a way to programmatically separate them.

**Comment by NickCao** [comment]
The current behavior is due to us unconditionally moving `$out/bin` to `$dev/bin`, while in qt-5 only the devtools are cherry picked:
https://github.com/NixOS/nixpkgs/blob/878cb61054ad018729171107120e282ab7051adc/pkgs/development/libraries/qt-6/qtModule.nix#L36

**Comment by NickCao** [comment]
Also partly due to my cmake patch determining that all directory ending in bin should go to the dev output.
