### ISSUE TITLE
SDRangel is missing 2 decoders

### ISSUE THREAD

**Issue by Tungsten842** [NixOS/nixpkgs#202721]
### Describe the bug
Sdrangel is currently missing(compared to the flatpak version):
DAB Demodulator
SigMF File Sink

### Notify maintainers
 @alkeryn  

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `0`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 23.05 (Stoat), 23.05.20221123.42337aa`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - channels(quantmint): `""`
```

**Comment by alkeryn** [comment]
@QuantMint hey !
i'm no longer using nixos, nor sdrangel for that matter, i will get back to it eventually though.

what version does it work in ubuntu ?
maybe it's as simple as a version upgrade, otherwise it may be a dependency thing.
can you run sdrangel from the terminal and tell me if it says any errors ? :)

**Comment by QuantMint** [comment]
> @QuantMint hey ! i'm no longer using nixos, nor sdrangel for that matter, i will get back to it eventually though.
> 
> what version does it work in ubuntu ? maybe it's as simple as a version upgrade, otherwise it may be a dependency thing. can you run sdrangel from the terminal and tell me if it says any errors ? :)

This is the entire [log](https://gist.github.com/QuantMint/6cf2b8661d5a096ac49505aca256b025), I am using the latest version of sdrangel 7.8.3.

**Comment by alkeryn** [comment]
hey @QuantMint sorry for hte late reply, so it seems these are sdr angel plugins and should be enabled at compile time with a cmake flag or environement variable, see the following cmakefile: https://github.com/f4exb/sdrangel/blob/master/plugins/CMakeLists.txt

i think it shouldn't be too much work to enable those flags on the existing .nix
you may even be able to do it with a simple package override.
