### ISSUE TITLE
Packaging Request: Sapling (on Darwin)

### ISSUE THREAD

**Issue by davidbarsky** [NixOS/nixpkgs#202703]
**Project description**
Sapling is a replacement for Git from Meta/Facebook. It was packaged for Linux in https://github.com/NixOS/nixpkgs/pull/201798, but maintainers have encountered some Darwin-specific packaging difficulties and have said that opening an issue specifically for Darwin is warranted (https://github.com/NixOS/nixpkgs/pull/201798#issuecomment-1325839165, https://github.com/NixOS/nixpkgs/pull/201798#issuecomment-1325800475), so I'm opening this issue.

**Metadata**

- homepage URL: https://github.com/facebook/sapling/
- source URL: https://github.com/facebook/sapling/
- license: GPLv2
- platforms: Linux, Darwin, NT

(disclaimer: the people who work on Sapling and I share an employer, but I haven't spoken to them about this. My interest in seeing Sapling be packaged for Darwin is entirely selfish.)

**Comment by lf-** [comment]
I've root caused this. I'm on it
