### ISSUE TITLE
'gnome-online-accounts': Signing in with Google account doesn't work

### ISSUE THREAD

**Issue by MikiVanousek** [NixOS/nixpkgs#202862]
### Describe the bug
If I open Gnome Settings and try to sign in with Google, nothing appears in the dialog:
![image](https://user-images.githubusercontent.com/33402194/204004970-ff38365f-b128-4ed6-a9e7-922a2d9bb75e.png)

If I run settings from terminal, try adding an account and then dismiss the empty dialog:
```
GLib-GIO: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)GLib-GIO: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’GLib: unsetenv() is not thread-safe and should not be used after threads are createdGLib-GIO: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’GLib: unsetenv() is not thread-safe and should not be used after threads are createdGoaBackend: Loading all providers: GoaBackend:  - googleGoaBackend:  - owncloudGoaBackend:  - windows_liveGoaBackend:  - exchangeGoaBackend:  - lastfmGoaBackend:  - imap_smtpGoaBackend:  - kerberosGoaBackend: activated kerberos providerGoaBackend:  - media-serverbwrap: Can't mkdir parents for /run/current-system/sw/share/fonts: No such file or directory
Failed to create account: Dialog was dismissed
(gnome-control-center:36149): online-accounts-cc-panel-WARNING **: 15:27:06.225: Error showing account: Child process exited with code 1
```

### Expected behavior
I should be able to sign in 

### Notify maintainers

@maxeaubrey @hedning 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by buckley310** [comment]
This seems to be a more general issue with GNOME web.
![image](https://user-images.githubusercontent.com/2379774/204156606-b6736d70-6fb2-4bca-afb6-2f8eb466de2a.png)

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.9, NixOS, 22.11 (Raccoon), 22.11.20221122.c9538a9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/l87rh6axkgs7sh3ba4aqnw2wqvlzc3wg-source`
```

**Comment by MikiVanousek** [comment]
Whoa, its fixed for me. GNOME Web works again. Is it also true for you @buckley310? I am on `22.11`.

**Comment by buckley310** [comment]
Nope.

**Comment by MikiVanousek** [comment]
Interesting. I have had this issue for months, but now it is gone :smile:. I will keep the issue open for you.

**Comment by MikiVanousek** [comment]
No, I use an integrated Intel graphics. I don't think I changed drivers.

**Comment by buckley310** [comment]
My machine still has this issue.

**Comment by Aleksanaa** [comment]
Yesterday I used gnome-control-center to log in to my google account on hyprland. It was normal. Maybe it has something to do with gnome desktop?

**Comment by jtojnar** [comment]
The OP was probably fixed by https://github.com/NixOS/nixpkgs/pull/201219

The empty GNOME Web and sometimes gnome-online-accounts is probably https://github.com/NixOS/nixpkgs/issues/32580
