### ISSUE TITLE
No man page for GHC

### ISSUE THREAD

**Issue by w3rs** [NixOS/nixpkgs#20281]
## Issue description

I have ghc-8.0.1 installed with `nix-env -i`, but `man ghc` doesn't work. Seems like regression: https://github.com/NixOS/nixpkgs/issues/9265

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.733.246c937 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.733.246c937"

**Comment by lverns** [comment]
Looking at the previous issue you mentioned, it does look like a regression. However, I can see that the old documentation was built using docbook, but the [list of tools to build GHC](https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Tools) doesn't mention docbook, but _does_ mention sphinx. 

So it isn't quite just a matter of applying the old fix to the new version. At least, that didn't do it for me.
