### ISSUE TITLE
Required NixOS packages to build wine from source

### ISSUE THREAD

**Issue by mikael-andersson** [NixOS/nixpkgs#20283]
## Issue description

I have a WinTV USB stick from Hauppauge and would like to get the software running on NixOS. Apparently there should be a fix for it in the latest Wine version. I downloaded wine and have been able to resolve some package dependencies such as flex and bison. Now configure complains about this:

"...
checking for X... no
configure: error: X 64-bit development files not found. Wine will be built
without X support, which probably isn't what you want. You will need
to install 64-bit development packages of Xlib/Xfree86 at the very least.
..."

I did add xorg.libX11 and libx86 but that did not resolve the problem.

### Steps to reproduce

Clone latest wine from git repository and build with:
Add the packages wine, bison and flex to configure.nix and run nixos-rebuild switch

In wine source folder, run:
./configure --prefix ~/bin --enable-win64

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.953.96f9c3a (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.953.96f9c3a"

**Comment by Mic92** [comment]
How did you add xorg.libX11 and libx86? Usually it is required to use a `nix-shell` to get the development version including headers of a package.

**Comment by mikael-andersson** [comment]
I just added them to configuration.nix

OK, I did not know that. :) Is there a wiki page where I can read more
about how to go about setting this up?

Thanks,

Mikael

**Comment by mikael-andersson** [comment]
Many thanks for the information, I will try that out and get back to you soon.

**Comment by avnik** [comment]
@mikael-andersson why just not use packaged wine? It should works for both just-add-patch case, as well as full override src attribute with snapshot. I try to keep wine in master up today with unstable+staging releases

**Comment by mikael-andersson** [comment]
@Mic92 I have not yet tried what you proposed, I am thinking about trying out @avnik's solution first.

 @avnik it certainly sounds interesting, although I do not have a clue how to do it. :) Can you please point me to a page with some examples on how to do or can you add some examples here?

Many thanks in advance!

**Comment by mikael-andersson** [comment]
@avnik, do you have any references or examples on how to set this up?

**Comment by vcunat** [comment]
@mikael-andersson: we have some documentation on overrides http://nixos.org/nixpkgs/manual/#sec-pkg-overrideDerivation

**Comment by mikael-andersson** [comment]
Thanks @vcunat. 

This did not work. I can run rebuild switch fine but nothing happens, i.e. the wine version below is not downloaded and installed.

nixpkgs.config.packageOverrides = pkgs: rec {
myWine = pkgs.wine.overrideDerivation (oldAttrs: {
    name = "wine-1.9.23";
    src = pkgs.fetchurl {
      url = "https://dl.winehq.org/wine/source/1.9/wine-1.9.23.tar.bz2";
      sha256 = "";
      };
    patches = [];
  });
};

What am I doing wrong?

**Comment by vcunat** [comment]
@mikael-andersson: you want to use `myWine`, e.g. `systemPackages = [ pkgs.myWine ];`

You should get an evaluation error immediately due to not specifying any hash for the download ;-)

**Comment by mikael-andersson** [comment]
Now I was able to install it, wonderful, many thanks for the help everybody! :)

Unfortunately the Windows software my WinTV USB stick still does not work, but it is great to know how to override a package.

**Comment by joachifm** [comment]
Can this be closed?

**Comment by mikael-andersson** [comment]
Absolutely, thanks for the reminder. :)
