### ISSUE TITLE
i3 4.13 update

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20296]
i3 has been updated to 4.13.
I attempted to update our derivation but they switched to `autoconf` and I don't know how that works :)

If somebody could update i3, I would really appreciate that.

/cc maintainers @garbas @modulistic

**Comment by fmthoma** [comment]
FYI, for `autoreconf` to work it is sufficient to add `autoreconfHook` to the `nativeBuildInputs` (see https://github.com/NixOS/nixpkgs/pull/20345/commits/092d7e9705e5dae05be0b59c7df02f1b460ff8ab#diff-931be7832374b1b1e5333a952c328a38R14).

**Comment by NeQuissimus** [comment]
Thanks :) I think with the main i3 the issue was that the `configureFlags` needed to change and I did not know what to set them to.

**Comment by fmthoma** [comment]
Yes, and indeed the `./configure` and `Makefile` are already included with the source distribution for `i3`, but I had to add the `autoreconfHook` for `i3-gaps`.
