### ISSUE TITLE
The `slade` package doesn’t create a desktop entry for Slade

### ISSUE THREAD

**Issue by Jayman2000** [NixOS/nixpkgs#202944]
### Describe the bug
The `slade` package doesn’t create a desktop entry for Slade.

### Steps To Reproduce
1. Install `slade`.
2. Check your DE’s application launcher for Slade.

### Expected behavior
There should be a desktop entry for Slade

### Notify maintainers

@abbradar

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.05 (Quokka), 22.05.4328.68ba2f40991`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by ncfavier** [comment]
Looks like this is fixed on master (and will be in 22.11). Doesn't look like we can backport it though.
