### ISSUE TITLE
zfs-import-* attempts to load all keys, not just its own

### ISSUE THREAD

**Issue by vs49688** [NixOS/nixpkgs#203083]
### Describe the bug

When multiple ZFS filesystems are present and configured to import, each individual `zfs-import-pool` attempts to load the keys for ALL pools/datasets, instead of just its own.

### Steps To Reproduce
1. Have encrypted zfs filesystems in your NixOS configuration.
2. Rebuild & Reboot

### Expected behavior

All `zfs-import-*` targets complete successfully

#### `collection1` zfs pool failing on loading `data2/private`s key, completely unrelated
```
$ systemctl status zfs-import-collection1.service
× zfs-import-collection1.service - Import ZFS pool "collection1"
     Loaded: loaded (/etc/systemd/system/zfs-import-collection1.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-11-27 00:20:24 AEST; 1h 2min ago
    Process: 2208 ExecStart=/nix/store/9v7v8sbhvv667plrdmaaiqnz9bjyg295-unit-script-zfs-import-collection1-start/bin/zfs-import-collection1-start (code=exited, status=255/EXCEPTION)
   Main PID: 2208 (code=exited, status=255/EXCEPTION)
         IP: 0B in, 0B out
        CPU: 112ms

Nov 27 00:20:19 CAPRICA systemd[1]: Starting Import ZFS pool "collection1"...
Nov 27 00:20:24 CAPRICA zfs-import-collection1-start[2208]: importing ZFS pool "collection1"...
Nov 27 00:20:24 CAPRICA zfs-import-collection1-start[4139]: Key load error: Key already loaded for 'data2/private'.
Nov 27 00:20:24 CAPRICA systemd[1]: zfs-import-collection1.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 27 00:20:24 CAPRICA systemd[1]: zfs-import-collection1.service: Failed with result 'exit-code'.
Nov 27 00:20:25 CAPRICA systemd[1]: Failed to start Import ZFS pool "collection1".
```

#### Cause

The below snippet from the services's `ExecStart` script. It's `zfs list -Ho name,keylocation,keystatus  | while IFS=$'\t' read`'ing, and just looping over all pools/datasets. Instead, it should just specify the name directly in the `zfs list` command.

(Generated in `nixos/modules/tasks/filesystems/zfs.nix`)

```bash
if poolImported "collection1"; then
  /nix/store/7l4v5aq85kc0sv8kzbr17x0ca4lrff0v-zfs-user-2.1.6/sbin/zfs list -Ho name,keylocation,keystatus  | while IFS=$'\t' read ds kl ks; do
  {
  if [[ "$ks" != unavailable ]]; then
    continue
  fi
  case "$kl" in
    none )
      ;;
    prompt )
      tries=3
      success=false
      while [[ $success != true ]] && [[ $tries -gt 0 ]]; do
        /nix/store/q11j05nqg829dkvgc8851mscbzi2iq8n-systemd-251.7/bin/systemd-ask-password "Enter key for $ds:" | /nix/store/7l4v5aq85kc0sv8kzbr17x0ca4lrff0v-zfs-user-2.1.6/sbin/zfs load-key "$ds" \
          && success=true \
          || tries=$((tries - 1))
      done
      [[ $success = true ]]
      ;;
    * )
      /nix/store/7l4v5aq85kc0sv8kzbr17x0ca4lrff0v-zfs-user-2.1.6/sbin/zfs load-key "$ds"
      ;;
  esac
  } < /dev/null # To protect while read ds kl in case anything reads stdin
done

  echo "Successfully imported collection1"
else
  exit 1
fi
```

### Notify maintainers

@ElvishJerricco 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.11 (Raccoon), 22.11.20221121.20fc948`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`

**Comment by ElvishJerricco** [comment]
@vs49688 Can you post the relevant Nix config you used? Do you have `requestEncryptionCredentials` set to anything?

**Comment by ElvishJerricco** [comment]
Ok, I think this is fundamentally the same issue as #202164. Basically, when there are multiple pools and `boot.zfs.requestEncryptionCredentials` is a list, we accidentally run `zfs list` with no dataset argument in the import service for pools that have no datasets in the list. So those services end up iterating over *all datasets on all pools* instead of none.
