### ISSUE TITLE
rPackage.seewave can't find libsndfile

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#20308]
### Steps to reproduce
Add in nix-shell rPackages.seewave and nix-shell it

## Technical details
stft.c:3:61: fatal error: sndfile.h not found

* System: 16.09.940.8a5c376
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.940.8a5c376

**Comment by FRidh** [comment]
likely seewave needs libsndfile.out instead of libsndfile which points to libsndfile.bin

**Comment by mimadrid** [comment]
@frerich I fixed this bug some time ago. Could you close it? Thanks in advance!
