### ISSUE TITLE
Include the force_bind package 

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20306]
https://github.com/meebey/force_bind

It's a utility to force processes to only bind to allowed IP's/ports.

**Comment by avnik** [comment]
@spacekitteh does you mean https://github.com/meebey/force_bind
Would be nice if you supply link for software which you want to have packaged.

**Comment by danbst** [comment]
hm? didn't test though

```
let
  pkgs = import <nixpkgs> {};
in pkgs.stdenv.mkDerivation {
  name = "force_bind";
  src = pkgs.fetchgit {
    url = "git://github.com/meebey/force_bind.git";
    rev = "2500b54fd8537bc063739a59344b76957dba1c6f";
    sha256 = "06ps39w2ni8c6byf2g5adh9s08dx9c4pvdzmzrglsr2ywf1anc35";
  };

  postPatch = ''
    patchShebangs .
  '';

  makeFlags = "DESTDIR=$(out)";
}

**Comment by avnik** [comment]
@danbst  just $out/lib/force_bind.so looks meaningless. So or simple wrapper script need to be added (just export ``LD_PRELOAD=$out/lib/force_bind.so && exec $@``), or it need to be packaged in conjuction with something, which will use it.

**Comment by danbst** [comment]
@avnik 

> or it need to be packaged in conjuction with something, which will use it.

actually I thought this will be used this way 

```
systemd.services.foobar.script = ''
  LD_PRELOAD="${pkgs.force_bind}/lib/force_bind.so:$LD_PRELOAD" \
  FORCE_BIND_PORT_V4=${cfg.port} \
  foobar
'';
```

or an equivalent with `wrapProgram`.

Any other API will be much more intrusive for nixpkgs IMO. Can you share an example of how you'd like to use this `force_bind` in Nix?
