### ISSUE TITLE
(Gnome Extension) Arc Menu

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#203004]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)
Closest was #189308
###### Project name
`nix search` name: gnomeExtensions.arcmenu

current version: 37
desired version: 42

###### Notify maintainers

maintainers:
@dkabot 
@piegamesde 
@jtojnar 
###### Note for maintainers

Please tag this issue in your PR.

**Comment by piegamesde** [comment]
Hoo boi, our "package out of date template" is so bad :/

Anyways, this might be a good opportunity to try and get automatic packaging for that extension.

**Comment by Krutonium** [comment]
Can't disagree - it's... Confusing to fill out, to say the least. GitHub offers a form like option as well, perhaps that might be somthing to look at :thinking:

**Comment by Krutonium** [comment]
For example https://github.com/OpenRCT2/OpenRCT2/blob/develop/.github/ISSUE_TEMPLATE/bug_report.yaml
