### ISSUE TITLE
Can't install pkgs.plasma5Packages.kdeGear

### ISSUE THREAD

**Issue by LouisDK1** [NixOS/nixpkgs#203270]
## Issue description

When I try to put "plasma5Packages.kdeGear" in the pkgs entry in /etc/nixos/configuration.nix the fails with the error:

> unpacking channels...
> building Nix...
> building the system configuration...
> error: A definition for option `environment.systemPackages."[definition 1-entry 12]"' is not of type `package'. Definition values:
>        - In `/etc/nixos/configuration.nix':
>            {
>              akonadi = <derivation /nix/store/g1x8n30i0342yzbqjg83xzck25jr2xgg-akonadi-22.08.3.drv>;
>              akonadi-calendar = <derivation /nix/store/zid41z6dbyq9j5mkg0q58n7xmpawhkz0-akonadi-calendar-22.08.3.drv>;
>              akonadi-calendar-tools = <derivation /nix/store/l6zfyck3yxmc623rs3cq872nnhqrjwqk-akonadi-calendar-tools-22.08.3.drv>;
>              akonadi-contacts = <derivation /nix/store/jqb26z0fd572haxkdr4sm1h7r5c7wglx-akonadi-contacts-22.08.3.drv>;
>            ...
> (use '--show-trace' to show detailed location information)
> 

### Steps to reproduce

Put pkgs.plasma5Packages.kdeGear in /etc/nixos/configuration.nix and rebuild

## Technical details

>  - system: `"x86_64-linux"`
>  - host os: `Linux 6.0.9, NixOS, 23.05 (Stoat), 23.05pre429553.5dc7114b7b2`
>  - multi-user?: `yes`
>  - sandbox: `yes`
>  - version: `nix-env (Nix) 2.11.0`
>  - channels(louis): `""`
>  - channels(root): `"nixos"`
>  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by apfelkuchen6** [comment]
Well, `pkgs.plasma5Packages.kdeGear` is not a package, but an attrSet of derivations (and the the override function).

The following should do:
```
environment.systemPackages = with pkgs; [ firefox emacs sl ] 
    ++ (with lib; attrValues (filterAttrs (const isDerivation) pkgs.plasma5Packages.kdeGear));
```
