### ISSUE TITLE
Ceph is attempting to use the wrong version of Lua

### ISSUE THREAD

**Issue by dmoonfire** [NixOS/nixpkgs#203298]
### Steps To Reproduce

I'm in the process of trying to build a local version of ceph to try getting around the modprobe issue from #147801 but I was unable to copy a local version for my overlay.

1. Copy https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/ceph/default.nix locally without any changes
2. Create an overlay to use the file
3. Build the package that uses ceph

### Build log

The relevant sections:

```
-- Performing Test HAS_VTA                                                                                                             
-- Performing Test HAS_VTA - Success
Cmake Error at /nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:23    0 (message):
  Could NOT find Lua (missing: LUA_INCLUDE_DIR) (Required is at least version
  "5.3")
Call Stack (most recent call first):
  /nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAI    LURE_MESSAGE)
  /nix/store/rxb9zl1mdx9f2n3z0nyv9zhngj3f2pw0-cmake-3.24.3/share/cmake-3.24/Modules/FindLua.cmake:236 (FIND_PACKAGE_HANDLE_STANDARD_ARG    S)
  src/CMakeLists.txt:580 (find_package)
```

### Additional context

While looking at the problem, I noticed on lines [18](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/ceph/default.nix#L18) and [171](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/filesystems/ceph/default.nix#L171), the packages are referencing `lua` but according to [search.nixos.org](https://search.nixos.org/packages?channel=unstable&show=lua&from=0&size=50&sort=relevance&type=packages&query=lua), `lua` is version 5.2.4. Switching this to [lua5_3_compat](https://search.nixos.org/packages?channel=unstable&show=lua&from=0&size=50&sort=relevance&type=packages&query=lua) had the minimum version required and let me get past that build step.

### Notify maintainers

@adev @ak @johanot @krav

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.05pre358459.3e072546ea9"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

This is for a flake-based system against the latest unstable.

Thank you.

**Comment by teto** [comment]
diagnostic looks ok, PR welcome ? (I've got no involvment with ceph)

**Comment by dmoonfire** [comment]
Closed as this has been solved with a top-level alias.
