### ISSUE TITLE
libjpeg 6.2: missing patches

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20330]
To help out with #4491 I just came across `libjpeg62`, which builds using two patches that no longer exist. (and it can therefore not be built anymore)
A derivation called `warsow` depends on this version (seems to be a game).
The patches are Darwin-only.

I don't have a Darwin machine that I can experiment with. 
Judging by how long the `warsow` derivation has not been updated (except for mass-replacements), I would suggest removing both it and `libjpeg62`.

/cc maintainer @astsmtl

**Comment by knedlsepp** [comment]
See: https://github.com/NixOS/nixpkgs/issues/18346

**Comment by vcunat** [comment]
Correct.
