### ISSUE TITLE
wvdial segmentation fault

### ISSUE THREAD

**Issue by FPtje** [NixOS/nixpkgs#20344]
## Issue description
Wvdial crashes and burns with a segmentation fault when run. The cause is probably in wvstreams somewhere.

### Steps to reproduce
- Connect some USB modem
- Make sure it's switched to the right mode with `usb_modeswitch`
- import `<nixpkgs/nixos/modules/programs/wvdial.nix>` in configuration
- Set the following option (or use your own config):

```nix
environment.wvdial.dialerDefaults = ''
    Init1 = ATZ0
    Init2 = ATQ0 V1 E1 S0=0
    Init3 = AT+CGDCONT=1,"IP","internet"
    Modem Type = Analog Modem
    ISDN = 0
    Phone = *99#
    Modem = /dev/ttyUSB1
    Username = <retracted>
    Password = <retracted>
    Baud = 9600
  '';
```

- run `sudo wvdial`
- Observe the following output:

```
$ sudo wvdial
--> WvDial: Internet dialer version 1.61
--> Initializing modem.
--> Sending: ATZ0
ATZ0
OK
--> Sending: ATQ0 V1 E1 S0=0
ATQ0 V1 E1 S0=0
OK
--> Sending: AT+CGDCONT=1,"IP","internet"
AT+CGDCONT=1,"IP","internet"
OK
--> Modem initialized.
--> Sending: ATDT*99#
--> Waiting for carrier.
ATDT*99#
CONNECT
--> Carrier detected.  Waiting for prompt.
[1]    17578 segmentation fault  sudo wvdial
```

## Notes
- It might be related to #16113
- I've tried rebuilding wvstreams with `-O0` as described [here](https://bystricky.de/?p=4), but had no effect. I'm currently trying other things. I'll update the issue when progress is made.
- The problem is reproducible on both a Raspberry Pi device and my x86_64 laptop.
- This is what I was able to get on the raspberry Pi from gdb. Note that the Raspberry Pi has the segmentation fault after `Modem initialized` as opposed to my laptop, which has it thrown after `Carrier detected.  Waiting for prompt.`.
```
--> Modem initialized.

Program received signal SIGSEGV, Segmentation fault.
0xb6d39564 in WvTaskMan::_stackmaster() () from /nix/store/nrx3wjg7vyji31s3dnbqvgazaldd750f-wvstreams-4.6.1/lib/libwvbase.so.4.6
(gdb) list
1	../../../gcc-5.4.0/libgcc/config/arm/lib1funcs.S: No such file or directory.
```

- When building `wvstreams` and `wvdial` with debugging symbols I get the following error instead of a segfault:
```
wvdial: utils/wvtask.cc:500: static void WvTaskMan::do_task(): Assertion `task' failed.
```

- I downloaded a whole bunch of patches from the [Debian package](https://packages.debian.org/source/testing/wvstreams), but it doesn't fix the issue. The Debian version of `wvdial` *does* work, which is odd.
- The very hopeful "magic number fix" patch from [this discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=674006) does not resolve the issue.

## Technical details
NixOS version: `16.09pre-git (Flounder)`
Nix: 1.11.4
nixpkgs: 16.09pre-git (1e1112e)

**Comment by makefu** [comment]
wow, it indeed seems that the issue is still not fixed ....
@FPtje fyi, this is how i am using wvdial to this date:

```nix
let
  nixpkgs-1509 = import (pkgs.fetchFromGitHub {
    owner = "NixOS"; repo = "nixpkgs-channels";
    rev = "91371c2bb6e20fc0df7a812332d99c38b21a2bda";
    sha256 = "1as1i0j9d2n3iap9b471y4x01561r2s3vmjc5281qinirlr4al73";
  }) {};
  wvdial = nixpkgs-1509.wvdial; # https://github.com/NixOS/nixpkgs/issues/16113
 in {   
  systemd.services.umts.serviceConfig = {
        Type = "simple";
        Restart = "always";
        RestartSec = "10s";
        ExecStart = "${wvdial}/bin/wvdial -n";
    };
};
```

**Comment by globin** [comment]
`wvdial` has been removed for 17.09 as it has not been maintained upstream nor has received care in nixpkgs.
