### ISSUE TITLE
headscale: 0.16.4 -> 0.17.0

### ISSUE THREAD

**Issue by LogicalOverflow** [NixOS/nixpkgs#203446]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `headscale`

current version: v0.16.4
desired version: v0.17.0

Link to the new version: https://github.com/juanfont/headscale/releases/tag/v0.17.0

This version upgrade also most likely requires a change to the `headscale` module, as the `log_level` option has been moved.

I am happy to create a PR for this, if desired

###### Notify maintainers

maintainers: @kradalby @06kellyjac @NKJe

###### Note for maintainers

Please tag this issue in your PR.

**Comment by kradalby** [comment]
Posted on #203694

**Comment by LogicalOverflow** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/203938
