### ISSUE TITLE
xdg-desktop-portal-validate-icon re-runs itself in sandbox using unwrapped binary

### ISSUE THREAD

**Issue by ilya-fedin** [NixOS/nixpkgs#203506]
### Describe the bug
xdg-desktop-portal-validate-icon uses gdk-pixbuf to check icons, but it's not wrapped leading to the portal not accepting any icons for notifications

### Steps To Reproduce
1. Get a notification with an image via the notification portal

### Expected behavior
The image is displayed

### Screenshots
![изображение](https://user-images.githubusercontent.com/17829319/204372843-b1ea4aa6-e83f-456c-9a2d-f8ef71ae5e50.png)

### Notify maintainers
@jtojnar

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-zen1, NixOS, 22.11 (Raccoon), 22.11.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/etc/static/nixpkgs`
```

**Comment by jtojnar** [comment]
I can see it being wrapped in nixos-unstable (it uses a binary wrapper).

**Comment by ilya-fedin** [comment]
Maybe the wrapper doesn't provide paths to gdk-pixbuf plugins?

**Comment by jtojnar** [comment]
It does.

**Comment by ilya-fedin** [comment]
I'll try to update my system

**Comment by jtojnar** [comment]
It should be hermetic, and there have been no recent changes: https://github.com/NixOS/nixpkgs/commits/5fe4c60e49e10afd624fd0b022f92da4511f671e/pkgs/development/libraries/xdg-desktop-portal/default.nix

**Comment by ilya-fedin** [comment]
Interesting, last time I tried to run it manually check a png file, it returned it can't read it, now it returns me an INI output. But it still doesn't work when started by the service telling only that child process exited with exit code 1...

**Comment by ilya-fedin** [comment]
Ok, update didn't help...

**Comment by ilya-fedin** [comment]
Ok, I ran it with ptrace and found it tries to run itself in a bwrap container, but uses the .wrapped binary. Then I found in source code it has a `--sandbox` argument that is probably used by portal, I tried to run it with `--sandbox` and it indeed complains it can't find itself...

**Comment by jtojnar** [comment]
That is weird, it should be in [`storeDir`](https://github.com/NixOS/nixpkgs/blob/9121a522fdc31fb108e1e98ab66688eccc74cb53/pkgs/development/libraries/flatpak/fix-icon-validation.patch#L18), which we are [already substituting](https://github.com/NixOS/nixpkgs/blob/9121a522fdc31fb108e1e98ab66688eccc74cb53/pkgs/development/libraries/flatpak/default.nix#L188).

We are already testing with `--sandbox`:

https://github.com/NixOS/nixpkgs/blob/9121a522fdc31fb108e1e98ab66688eccc74cb53/pkgs/development/libraries/xdg-desktop-portal/default.nix#L98-L101

Here is the relevant source code:

https://github.com/flatpak/xdg-desktop-portal/blob/dc898cac4d7075b45fe9294acb959b07cd7ecf6a/src/validate-icon.c#L180

**Comment by jtojnar** [comment]
Well, unwrapped should be fine, we are [inheriting the `GDK_PIXBUF_MODULE_FILE` variable](https://github.com/NixOS/nixpkgs/blob/9121a522fdc31fb108e1e98ab66688eccc74cb53/pkgs/development/libraries/flatpak/fix-icon-validation.patch#L26-L27).

**Comment by ilya-fedin** [comment]
`bwrap: execvp /nix/store/c2ib59rvvqwpfwy78c14hgr9b3ibl8bz-xdg-desktop-portal-1.15.0/libexec/.xdg-desktop-portal-validate-icon-wrapped: No such file or directory`

**Comment by ilya-fedin** [comment]
my guess it's because /nix/store is not in sandbox, so it can't find the interpreter (ld-linux)

**Comment by jtojnar** [comment]
It should be as per https://github.com/NixOS/nixpkgs/blob/9121a522fdc31fb108e1e98ab66688eccc74cb53/pkgs/development/libraries/flatpak/fix-icon-validation.patch#L18 and as demonstrated by https://github.com/NixOS/nixpkgs/blob/9121a522fdc31fb108e1e98ab66688eccc74cb53/pkgs/development/libraries/xdg-desktop-portal/default.nix#L98-L101

**Comment by ilya-fedin** [comment]
Thanks, I have an overlay with a patch, but have no `oldAttrs.patches ++`
