### ISSUE TITLE
makeInitrdNG: malformed squashfs images when filesize exceeds 2GB

### ISSUE THREAD

**Issue by jhvst** [NixOS/nixpkgs#203593]
### Describe the bug
If you create initrd files over 2GB, for example, with [this configuration](https://github.com/jhvst/nix-config/blob/main/nvidia.nix) and try to boot it, the bootup will fail when mounting the squashfs image in init-1-stage with an error `squashfs error unable to read id index table`. As suggested, e.g., by #26230, this is indeed caused by data corruption. However, the corruption does _not_ happen in transport, it happens when creating the initrd. Furthermore, and what's the real bug, is that the data corruption only happens when the resulting initrd exceeds 2GB in size. The data corruption can be verified by comparing the `sha256sum` of the squashfs images: first on the computer that build the image (i.e., from nix store path echoed on the final parts of the build process), and then on the computer that tries to boot the image from the initrd root folder in emergency shell. The files will be exact in size, but differ in their hash signature. If one is to use the emergency shell to fetch the squashfs image from the nix store and manually initialize init-2-stage, the OS will boot successfully.

### Steps To Reproduce

1. Build an initrd file which exceeds 2GB in size. For example, [with my configuration](https://github.com/jhvst/nix-config/blob/main/nvidia.nix) run `nix-build -A pix.ipxe nvidia.nix -I home-manager=https://github.com/nix-community/home-manager/archive/master.tar.gz -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.zip`. Alternatively, you can [download a pre-built version of mine](http://boot.ponkila.com/initrd).
2. Either modify the `kernelModules` in the Nix config file to include drivers necessary you to fetch the original squashfs image. This would be keyabord, filesystem drivers, and/or network drivers. Alternatively, you can [download a kernel that I used](http://boot.ponkila.com/phasedKernel).
3. Ensure you are running latest Linux kernel _on your current system_. We are going to use kexec, which only recently supports files over 2GB in size. `linux_latest` from nixpkgs will do.
4. In the result folder from step 2, you will find a file called `kexec-boot`. If you modified the Nix configuration file to include kernelModules for your system, you can execute this script. If you decided to use my prebuilt images, run `kexec --load phasedKernel --initrd=initrd -c "boot.shell_on_fail"`. Then, when you are ready to halt the system, run `kexec -e`.
5. During the bootup, you should see the squashfs error described. Press `f` for emergency shell. Then, you will find the malformed squashfs from the root folder. Check its `sha256sum`. This should differ from your self-built image, or the file at http://boot.ponkila.com/squashfs.img.  Bug reproduced. Done.
6. You can continue with the bootup process by acquiring the original squashfs image used in the built process. I store mine [here](http://boot.ponkila.com/squashfs.img). With the original squashfs acquired, delete the one found from initrd, and rename the downloaded/mounted squashfs with the same name as the original file. Then, run `./init` or prepare the filesystem manually to eventually launch `switch_root`. [You can refer to this document for more details](https://github.com/jhvst/jhvst.github.io/blob/main/ramdisk.md). Finally, the OS will boot successfully.

### Expected behavior

I expect it's fine if my initrd is over 2GB. Currently, it's not: I'm unable to boot. Kexec shows that this is not BIOS related issue.

### Screenshots
N/A

### Additional context

[I wrote more details here](https://github.com/jhvst/jhvst.github.io/blob/main/ramdisk.md). I have triaged this issue a lot, from cancelling out BusyBox issues, to UEFI compatibility, to RAM running out, and to kernel configuration issues with tmpfs files over 2GB. I have looked at the current implementation of the [`makeInitrdNG`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/kernel/make-initrd-ng), which I _believe_ is at least related to the bug, but I cannot see how this issue could arise from the current Rust code. This bug does not seem to be an issue with any of the userspace or kernel code, hence, it's specific to the way the images are built on Nix.

This issue is probably not very high in priority -- in practice, the 2GB limit can be circumvented by modifying the init-1-stage script to download a rootfs over the Internet, much like what is done in reproducing this bug. However, I don't think this issue should exist unless there is something awry happening in the initrd build process, hence, should probably taken a look at.

### Notify maintainers

@dasJ @elvishjerricco @k900 @lheckemann

### Metadata

N/A

**Comment by K900** [comment]
The Rust bits don't touch the contents of the initrd at all, they're just copied and then fed to cpio. I wonder if you're hitting some cpio bug.

**Comment by jhvst** [comment]
Sound plausible given that cpio is quite old to my understanding. Bit more context from my triaging: the Linux kernel code for kexec had a bug/feature regarding the 2GB size due to use of the `int` datatype in the `read_file` code: https://lore.kernel.org/lkml/20220527025535.3953665-2-pasha.tatashin@soleen.com/T/

@K900 do you think this issue should be kept open until the issue is found from the dependencies, or closed as unrelated to NixOS?

**Comment by K900** [comment]
I think we should at least look into this and maybe fix our cpio build to make it work.

**Comment by tupakkatapa** [comment]
Found a lot of threads where people discuss this and the magic value of 2GB where problems start to occur. Then I found the following, which actually makes a lot of sense:

"Downloads are placed in the 32-bit address space (i.e., below 4GB). It is very plausible that a large chunk of this address space is allocated for PCI BARs, and so you may have only ~2GB of actual RAM within this address space."
 https://ipxe-devel.ipxe.narkive.com/YA1ZoMfx/size-limit-in-ipxe

Unfortunately, I think it is game over regarding this; we are stuck with the squashfs method. Or what do you guys think?

**Comment by lheckemann** [comment]
Yeah, the only solution I see for that is a more complex setup where only a small initrd is fetched at PXE time and that initrd then obtains the Nix store squashfs (or otherwise getting the nix store -- depending on the use case nfs or similar might make sense too and allow for faster boots) from the netboot server some other way. That would require setting up networking and stuff in the initrd though.

**Comment by tupakkatapa** [comment]
That is exactly what we are currently using as a workaround. It required some changes to the stage-1-init script: https://github.com/majbacka-labs/nixpkgs/commits/patch-init1sh. It should be stated that this does not have anything to do with fixing kexec, which is annoying since I would like to have both functionalities for the same output format.

If you are also convinced that this does not directly relate to nixpkgs, as far as I am concerned, this issue should be closed.

**Comment by jhvst** [comment]
The 2GB limit has nothing to do with PXE. The  limit is most likely a cpio bug.

The linked issue above to PXE forums is irrelevant in this context because: 1) the initrd is created post-boot while using 64 bit addressing, and 2) the squashfs is mounted in the init1 stage, which can use 64 bit addressing. Kexec itself supports images of over 4GB, so that is not the problem.

The problem you linked would only make sense before the kernel is started. But, the moment the kernel is started, which is always the case when you are handling squashfs, you have full access to RAM.

To fix this problem, the way the cpio is packaged, alongside its arguments, have to be reviewed.

Juuso

**Comment by ElvishJerricco** [comment]
@jhvst Isn't the argument that the initrd itself, which is loaded before the kernel starts, is too big because it contains the squashfs? i.e. The problem is not mounting the squashfs; it's loading the initrd in the first place.

**Comment by jhvst** [comment]
I do not think so, but I may be wrong: the `shell_on_fail` boot option drops you into a initrd environment, right? The bootup certainly works to this stage. Moreover, as the squashfs image can be fetched from the network and then continued successfully while in the supposed initrd environment (and we do this quite often with @tupakkatapa, as we daily-drive our patchset which implements the workaround suggestion of @lheckemann above) it seems that the initrd is actually fine, but the problem is with the squashfs file which extends over 2GB limit. It might of course be possible that the initrd is somehow pruned to an extent, but it affecting only one file but not the integrity of anything else seems unlikely to me given the current information.

FWIW, we wish to eventually upstream the changes for the workaround (see: #203750), but I guess an alternative solution would be to troubleshoot this issue. However, both options are low priority for us, while the required effort seems coincidentally high.

My current ETA is that I _may_ take a look at this sometime in June/July, but cannot promise any resolution.

**Comment by ElvishJerricco** [comment]
@jhvst Look at how this initrd is created: https://github.com/NixOS/nixpkgs/blob/fd2ac5b6f33ef73d6019587eb1e7982db46eab15/nixos/modules/installer/netboot/netboot.nix#L90-L99

The ordinary initrd is used in `prepend`, meaning this initrd contains two compressed initrds; one is the normal one, and then after it is one containing only the squashfs.

This means that if the initrd is being truncated during load because it is too long, only the squashfs would be affected.

So I think my explanation is still very likely correct.

**Comment by jhvst** [comment]
Now I see, makes sense then. This might be a good test case then. I will most likely start debugging this expression. Thanks!

**Comment by jhvst** [comment]
It seems that this issue has now resolved itself -- initrds over 2GB boot fine. Thanks to everyone who shared their comments. This has been tested both on kexec and via ipxe netboot.

**Comment by Eason20000** [comment]
This seems to be happening again when specifying boot.kernelPackages = pkgs.linuxPackages_6_6.

``` nix
# server.nix — PXE netboot server for Minecraft club
# Builds a custom netboot image from netboot-base.nix, serves via pixiecore.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  cfg = config.my.nixos.mcc-netboot.server;

  sys = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";
    modules = [
      (
        {
          config,
          pkgs,
          lib,
          modulesPath,
          ...
        }:
        {
          imports = [
            (modulesPath + "/installer/netboot/netboot-base.nix")
            ../../../pkgs
            ../hardware
          ];
          config = {
            netboot.squashfsCompression = "zstd -Xcompression-level 6";

            boot.initrd.systemd.emergencyAccess = true;

            time.timeZone = "Asia/Shanghai";
            i18n.defaultLocale = "zh_CN.UTF-8";

            system.stateVersion = config.system.nixos.release;

            nixpkgs.config.allowUnfree = true;
            my.nixos = {
              hardware = {
                # This gets a 6.6 kernel and it's some how not booting
                # from a big initrd like if we enable xfce stuff.
                # https://github.com/NixOS/nixpkgs/issues/203593
                # https://github.com/NixOS/nixpkgs/pull/203750
                # TODO: fix this
                zhaoxin.enable = true;
                # it sets:
                #boot.kernelPackages = pkgs.linuxPackages_6_6;

                zramSwap.enable = true;
              };
            };

            services.xserver = {
              enable = true;
              desktopManager = {
                xterm.enable = false;
                xfce = {
                  enable = true;
                  enableScreensaver = false;
                };
              };
            };
            services.displayManager = {
              defaultSession = "xfce";
              autoLogin.user = "nixos";
            };

            programs.firefox.enable = true;

            environment.systemPackages = with pkgs; [ hmcl ];

            fonts = {
              fontDir.enable = true;
              enableDefaultPackages = true;
              packages = with pkgs; [
                corefonts
                noto-fonts
                noto-fonts-cjk-sans
                noto-fonts-cjk-serif
                noto-fonts-color-emoji
              ];
              fontconfig = {
                defaultFonts = {
                  sansSerif = [
                    "Noto Sans"
                    "Noto Sans CJK SC"
                  ];
                  serif = [
                    "Noto Serif"
                    "Noto Serif CJK SC"
                  ];
                  monospace = [
                    "Noto Sans Mono"
                    "Noto Sans Mono CJK SC"
                  ];
                };
              };
            };

          };
        }
      )
    ];
  };

in
{
  options.my.nixos.mcc-netboot.server = {
    enable = lib.mkEnableOption "PXE netboot server for Minecraft club";
  };

  config = lib.mkIf cfg.enable {
    services.pixiecore = {
      enable = true;
      openFirewall = true;
      dhcpNoBind = true;
      kernel = "${sys.config.system.build.kernel}/${sys.pkgs.stdenv.hostPlatform.linux-kernel.target}";
      initrd = "${sys.config.system.build.netbootRamdisk}/initrd";
      cmdLine = "init=${sys.config.system.build.toplevel}/init loglevel=4";
    };

  };
}
```

Commenting out the Xfce desktop settings above and obtaining a file smaller than 2 GB allows the system to boot successfully.

**Comment by Eason20000** [comment]
A fix is to download the rootfs inside the initrd:

``` nix
# server.nix — PXE netboot server for Minecraft club
# Builds a custom netboot image from netboot-base.nix, serves via pixiecore.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  cfg = config.my.nixos.mcc-netboot.server;

  sys = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";
    modules = [
      (
        {
          config,
          pkgs,
          lib,
          modulesPath,
          ...
        }:
        {
          imports = [
            (modulesPath + "/installer/netboot/netboot-base.nix")
            ../../../pkgs
            ../hardware
          ];
          config = {
            netboot.squashfsCompression = "zstd -Xcompression-level 6";

            boot.initrd.availableKernelModules = [
              "r8169"
              "e1000e"
            ];

            boot.initrd.systemd.emergencyAccess = true;

            boot.initrd.systemd.network = {
              enable = true;
              networks."10-wired" = {
                matchConfig.Name = "en*";
                networkConfig = {
                  DHCP = "yes";
                };
              };
            };

            boot.initrd.systemd.storePaths = with pkgs; [ pkgs.aria2 ];
            boot.initrd.systemd.services.download-squashfs = {
              description = "Download Nix Store SquashFS";
              wantedBy = [ "initrd-fs.target" ];
              after = [ "network-online.target" ];
              requires = [ "network-online.target" ];
              before = [ "sysroot-nix-.ro\\x2dstore.mount" ];
              requiredBy = [ "sysroot-nix-.ro\\x2dstore.mount" ];
              unitConfig.DefaultDependencies = "no";
              serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
              };
              script = ''
                SQUASHFS_URL=""
                for o in $(cat /proc/cmdline); do
                  case "$o" in
                    squashfs_url=*)  SQUASHFS_URL="''${o#squashfs_url=}" ;;
                  esac
                done
                [ -n "$SQUASHFS_URL" ]  || { echo "FATAL: no squashfs_url=";  exit 1; }
                ${pkgs.aria2}/bin/aria2c \
                  --allow-overwrite=true \
                  --auto-file-renaming=false \
                  "$SQUASHFS_URL" \
                  --dir=/ \
                  --out=nix-store.squashfs
              '';
            };

            time.timeZone = "Asia/Shanghai";
            i18n.defaultLocale = "zh_CN.UTF-8";

            system.stateVersion = config.system.nixos.release;

            nixpkgs.config.allowUnfree = true;
            my.nixos = {
              hardware = {
                # This get you a 6.6 kernel and it's some how not booting
                # from a big initrd like if we enable xfce stuff.
                # https://github.com/NixOS/nixpkgs/issues/203593
                # https://github.com/NixOS/nixpkgs/pull/203750
                # TODO: fix/report this
                # Bypassed with initrd download
                zhaoxin.enable = true;
                zramSwap.enable = true;
              };
            };

            services.xserver = {
              enable = true;
              desktopManager = {
                xterm.enable = false;
                xfce = {
                  enable = true;
                  enableScreensaver = false;
                };
              };
            };
            services.displayManager = {
              defaultSession = "xfce";
              autoLogin.user = "nixos";
            };

            programs.firefox.enable = true;

            environment.systemPackages = with pkgs; [ hmcl ];

            fonts = {
              fontDir.enable = true;
              enableDefaultPackages = true;
              packages = with pkgs; [
                corefonts
                noto-fonts
                noto-fonts-cjk-sans
                noto-fonts-cjk-serif
                noto-fonts-color-emoji
              ];
              fontconfig = {
                defaultFonts = {
                  sansSerif = [
                    "Noto Sans"
                    "Noto Sans CJK SC"
                  ];
                  serif = [
                    "Noto Serif"
                    "Noto Serif CJK SC"
                  ];
                  monospace = [
                    "Noto Sans Mono"
                    "Noto Sans Mono CJK SC"
                  ];
                };
              };
            };

          };
        }
      )
    ];
  };

in
{
  options.my.nixos.mcc-netboot.server = {
    enable = lib.mkEnableOption "PXE netboot server for Minecraft club";
  };

  config = lib.mkIf cfg.enable {
    services.pixiecore = {
      enable = true;
      openFirewall = true;
      dhcpNoBind = true;
      kernel = "${sys.config.system.build.kernel}/${sys.pkgs.stdenv.hostPlatform.linux-kernel.target}";
      initrd = "${sys.config.system.build.initialRamdisk}/initrd";
      cmdLine = "init=${sys.config.system.build.toplevel}/init squashfs_url=http://$\${next-server}:8080/nix-store.squashfs loglevel=4";
    };

    systemd.tmpfiles.rules = [
      "L+ /var/lib/mcc-netboot/nix-store.squashfs - - - - ${sys.config.system.build.squashfsStore}"
    ];

    systemd.services.mcc-netboot-files = {
      description = "MCC Netboot SquashFS HTTP Server";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];
      serviceConfig = {
        ExecStart = "${pkgs.darkhttpd}/bin/darkhttpd /var/lib/mcc-netboot --port 8080 --no-server-id";
        Restart = "always";
      };
    };
    networking.firewall.allowedTCPPorts = [ 8080 ];

  };
}
```
