### ISSUE TITLE
valgrind reports `Unknown option: --leak-check=full` even though no such option is being used

### ISSUE THREAD

**Issue by pca006132** [NixOS/nixpkgs#203756]
### Describe the bug
Valgrind reports `Unknown option: --leak-check=full` even though no such option is being used.

### Steps To Reproduce
1. Run `valgrind --tool=cachegrind <program>`

### Expected behavior

Run cachegrind on the target program

### Screenshots

```
valgrind: Unknown option: --leak-check=full
valgrind: Use --help for more information or consult the user manual.
```

### Additional context

The same error occurs when using `--tool=none` or other tools, as long as not using `memcheck`. I tried nixos-22.05, unstable, overriding valgrind version to 3.20.0 but nothing works.

### Notify maintainers

@edolstra

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 22.05 (Quokka), 22.05.4338.695b3515251`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05, nixpkgs-unstable"`
 - channels(pca006132): `"home-manager-22.05.tar.gz, nixpkgs-22.05, nixpkgs-unstable"`
 - nixpkgs: `/home/pca006132/.nix-defexpr/channels/nixpkgs`
```

**Comment by alarsyo** [comment]
I'm unable to reproduce this on unstable, do you have some global options set somewhere? (See https://valgrind.org/docs/manual/manual-core.html#manual-core.defopts)

**Comment by pca006132** [comment]
Ah, I am unaware of the repository I am testing have these global options, thanks!
