### ISSUE TITLE
Mention Bot

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20375]
## Issue description
In #20373 (and previous Atom PRs, I assume), the Mention Bot has been tagging `jhasse` (intentionally not pinging GH handle directly) despite him being on the blacklist.

@domenkozar has reported this upstream in facebook/mention-bot#178

I played with my own instance of Mention Bot for a bit and don't seem to run into the issue described there.
I am wondering if it has to do with the load on https://mention-bot.herokuapp.com

Setting up our own "NixOS Butler" is trivial and free. The only thing we would need it to change are the webhooks.

Of course, this is rather low priority but I can understand it being annoying to `jhasse` if he does not want to be pinged every time I update Atom.

**Comment by FRidh** [comment]
since there are more issues with the current instance of mention-bot I am in favor of having our own one.

**Comment by domenkozar** [comment]
I see potential problems with heroku since if you don't pay it will inactivate your worker. You can get around that with uptimerobot.com but..

**Comment by NeQuissimus** [comment]
Are we really reliant on the bot that trying out own instance would disrupt anything in a major way?
@FRidh What are these "other" issues?

I am aware of it not ignoring blacklisted users and not pinging those on the "always ping" lists.
It seems, both may be triggered by it falling back to a default config.

**Comment by FRidh** [comment]
> Are we really reliant on the bot that trying out own instance would disrupt anything in a major way?

Currently its not functioning as it is supposed to, so I am in favor of trying out our own instance.

> @FRidh What are these "other" issues? 

That which you also mention, not pinging those that explicitly opted in for certain files.
