### ISSUE TITLE
nix-channel should be able to accept git URLs for channel paths

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20376]
For example, instead of wasting bandwidth re-downloading master.zip every time with -I (not to mention manually specifying it), nix should just be able to pull from a git repo.

**Comment by andjscott** [comment]
You can set up [NixOS with a local nixpkgs checkout instead of channels](http://anderspapitto.com/posts/2015-11-01-nixos-with-local-nixpkgs-checkout.html). Upgrading then becomes
```
cd $NIXPKGS
git pull
nixos-rebuild switch
```
It would be nice for official support.

**Comment by vcunat** [comment]
Note: you need to pass `-I nixpkgs=.` to `nixos-rebuild`, otherwise the channel nixpkgs is used. I've been using this channel-less approach for years on my main machine. (Binaries are checked independently of being on a channel, nowadays.)

**Comment by vcunat** [comment]
I believe we *can* say that such way is "officially supported", i.e. shouldn't break in future, at least not without a good reason and warning.

**Comment by Profpatsch** [comment]
Newer nix versions (>2.0) should do caching by default.
