### ISSUE TITLE
broadcom_sta fail to build due `linux-4.8.patch' checksum mismatch

### ISSUE THREAD

**Issue by yuchangyuan** [NixOS/nixpkgs#20382]
## Issue description

broadcom_sta fail to build due a patch file checksum mismatch

### Steps to reproduce

With `config.boot.kernelPackages.broadcom_sta` included in `boot.extraModulePackages`, then update channel, and then rebuild system.
    
## Technical details

When build broadcom_sta, file `linux-4.8.patch` need to download from [https://aur.archlinux.org/cgit/aur.git/plain/004-linux48.patch?h=broadcom-wl-dkms](url) ,
however the download file has a different sha256sum than the on specified in broadcom_sta package.

It seems that the file in AUR is just updated( [https://aur.archlinux.org/packages/broadcom-wl-dkms/](url) ), but our package has not update yet. Maybe we should specify the commit in URL or just mirror the file to avoid this kind of problem in the future.

* System: NixOS 16.09.773.b8ede35 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.773.b8ede35 (Flounder)

**Comment by NeQuissimus** [comment]
I fixed this in #20412
