### ISSUE TITLE
xonotic-0.8.1: fatal error: zlib.h: No such file or directory

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#20388]
## Issue description

Cannot install Xonotic 0.8.1 game.

### Steps to reproduce

Running
```shell
nix-env -iA nixos.xonotic
```
ends with
```
../../../fs.c:118:18: fatal error: zlib.h: No such file or directory
```

## Technical details

* NixOS: `16.09.1024.c859ea0 (Flounder)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `16.09.1024.c859ea0`

**Comment by pSub** [comment]
Fixed in 4c39fe5d6631bcb98526e440ddc66f7c13b8f256 on release-16.09.

**Comment by alexeymuranov** [comment]
Hm, i still get the same.  What am i doing wrong?

**Comment by pSub** [comment]
The this isn't yet in the 16.09 channel. You have to checkout nixpkgs on branch release-16.09 and build against it.
