### ISSUE TITLE
Add Apache Kafka KRaft support

### ISSUE THREAD

**Issue by fogti** [NixOS/nixpkgs#203987]
## Issue description
Apache Kafka now seems to also support an alternative coordination backend besides Zookeeper, dubbed "[KRaft](https://kafka.apache.org/documentation/#kraft)", and NixOS doesn't appear to support that yet, at least I was unable to any reference in nixpkgs, besides an indirect mention in an issue comment https://github.com/NixOS/nixpkgs/issues/127226#issuecomment-1085914763

**Comment by srhb** [comment]
PTAL ^ :smile_cat:

**Comment by srhb** [comment]
I think so, yes :)
