### ISSUE TITLE
big closure size of gdb due to multitarget

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#203962]
Since f8741c38cd546e3ff18ce9d708de14ff2aae68ab gdb is always built with `--enable-targets=all`, which makes its out store path almost a gigabyte big.

It would be nice if one could have a version of gdb that is built without that flag, which would reduce its size by 90%,

**Comment by yu-re-ka** [comment]
CC @Ericson2314

**Comment by yu-re-ka** [comment]
I will now use gdbHostCpuOnly in my config so this issue is solved for me

**Comment by Ma27** [comment]
I'm actually wondering if we should flip the default here (i.e. `gdb` is only built for the host CPU architecture and we re-add a `gdb-multiarch` for all targets). Right now, `nix-shell -p gdb` means downloading ~800MiB of runtime closure which will most likely be unused by the majority of gdb users (each `run-*` executable in gdb's `$out/bin` means ~20MiB and we have 31 of them.

cc @Ericson2314 (who introduced this), @lsix @globin @nbp (maintainers), @trofi @dasJ @alyssais (who recently touched this package), opinions?

**Comment by trofi** [comment]
Sounds fine to me. I don't have a strong opinion. I occasionally use `gdb` against `qemu` and most of the time doing native poking.

Some thoughts:
Pros: single target match single-target `binutils` (for making `gdb` leaner).
Cons: it feels like 800MB is not a lot given that `dwarffs` is effectively a requirement to fetch symbols from hydra. And those are usually huge (for keeping `gdb` as is). Compressed NAR is probably a lot smaller, might be worthwile comparing compressed single/multi.
