### ISSUE TITLE
Test for unchanged hashes

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nixpkgs#20393]
For sake of refactoring, it would be nice to have a test that shows all hashes that changed between two commits. Obviously every PR would not be held to the standard of 0 changed hash, but for certain ones it would be a useful tool for both the developer and reviewer.

CC @nbp @DavidEGrayson

**Comment by vcunat** [comment]
This is basically a duplicate of https://github.com/NixOS/nixpkgs/issues/19045, if I understand you correctly.

**Comment by Ericson2314** [comment]
Yes it is, thanks
