### ISSUE TITLE
Build fails; works when retried repeatedly

### ISSUE THREAD

**Issue by stapelberg** [NixOS/nixpkgs#20394]
## Issue description

My apologies in advance for a not well-researched issue, but the feedback cycle of multiple days makes it incredibly time-consuming to gather more details.

For testing https://github.com/NixOS/nixpkgs/issues/18538, I added
```
  nixpkgs.config.packageOverrides = pkgs: {
    libffi = pkgs.stdenv.lib.overrideDerivation pkgs.libffi (attrs: {
      outputs = attrs.outputs or ["out"] ++ ["debug"];
      buildInputs = attrs.buildInputs ++ [<nixpkgs/pkgs/build-support/setup-hooks/separate-debug-info.sh>];
    });
  };
```

to my `/etc/nixos/configuration.nix` and ran `nixos-rebuild switch`.

The build failed, I retried. It failed again, I retried, it eventually worked.

I set `nix.useSandbox = true`, so I’m not sure why builds are flaky. Are flaky builds a problem which is also observed/tracked elsewhere already?

Unfortunately, I don’t have much more detail than that, and I’m not sure in which logs you might be interested, so please let me know.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
17.03pre95306.a24728f (Gorilla)
```

* Nix version: (run `nix-env --version`)

```
nix-env (Nix) 1.11.4
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
```
"17.03pre95306.a24728f"
```

**Comment by awjamison** [comment]
Possibly related, I have observed transient build failures for dbus after updating the unstable channel. It succeeded on the third attempt.

**Comment by copumpkin** [comment]
Useful logs would be to see how it fails and how it succeeds? Are all the failures producing the same or similar log output? I'd just paste all examples of the thing so we can diff to see what's causing the breakage.

**Comment by stapelberg** [comment]
Are build logs stored on disk, or are they just printed on stdout?

From what I remember, I did see the same failure twice, but then later on the build passed (did not see the build output).
