### ISSUE TITLE
rocm-opencl-runtime: "Output limit exceeded" on Hydra

### ISSUE THREAD

**Issue by SuperSamus** [NixOS/nixpkgs#203949]
https://hydra.nixos.org/build/200341028

### Notify maintainers
@acowley @lovesegfault @Flakebi

**Comment by Madouura** [comment]
``rocm-llvm`` is built before it, and adding ``clang-tools-extra`` adds I think about 1k new lines or more in the build output.
From what I see, the issue isn't ``rocm-opencl-runtime``, but something to do with ``rocm-llvm``.

**Comment by Madouura** [comment]
My bad, that error would be different if it were the amount of lines.
This is strange, nothing has changed except for adding ``clang-tools-extra``.
I haven't testing closure sizes for the difference, but it shouldn't be above the output limit (4.7GiB IIRC).
Looking at some of the other similar errors it's possible this may be a memory error while compressing.

**Comment by Madouura** [comment]
``rocm-llvm`` with ``clang-tools-extra`` exceeds 3GiB.
The above PR should fix this by reverting the commit adding it.

**Comment by vcunat** [comment]
The limit is 2 GiB for the sum of build outputs (non-transitive) of a single build.

**Comment by vcunat** [comment]
Oh right, it was raised surely, as the ISO (still) doesn't fit into 2 GiB.  I forgot, clearly.
