### ISSUE TITLE
Wrong hash of linux-4.8.patch

### ISSUE THREAD

**Issue by regellosigkeitsaxiom** [NixOS/nixpkgs#20409]
## Issue description
When trying to install `nixos.linuxPackages_4_8.broadcom_sta`, build fails on:

> building path(s) ‘/nix/store/4i0sircd91p1wszj7wm2xdf3kz11rlfd-linux-4.8.patch’
> 
> *** Downloading ‘https://cache.nixos.org/nar/0r70sr5n7lv5jz8n45y22jm17nzyws5h4779rvglg94yhp7brm27.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/wv9sd95zfjq6k4zx837kg7kjxc8q0wq1-linux-4.8.7’...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> trying https://aur.archlinux.org/cgit/aur.git/plain/004-linux48.patch?h=broadcom-wl-dkms
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1835  100  1835    0     0   3511      0 --:--:-- --:--:-- --:--:--  3508
> output path ‘/nix/store/4i0sircd91p1wszj7wm2xdf3kz11rlfd-linux-4.8.patch’ has sha256 hash ‘1g1gazxx67kxyw242cli6bf62il7ikzmf0w6v14k44j6b4bihcax’ when ‘0s8apf6l3qm9kln451g4z0pr13f4jdgyval1vfl2abg0dqc5xfhs’ was expected

### Steps to reproduce

`$ nix-env -iA nixos.linuxPackages_4_8.broadcom_sta`

## Technical details

> $ nixos-version
> 16.09.1024.c859ea0 (Flounder)

> $ nix-env --version
> nix-env (Nix) 1.11.4

> $ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
> "17.03pre95306.a24728f"

It also reproduces with nixos-16.09 channel:

> $ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
> "16.09.1024.c859ea0"

**Comment by seanparsons** [comment]
@NeQuissimus I've just had this after doing a `nixos-rebuild switch` on 17.03...
