### ISSUE TITLE
`cargo test` and `buildRustCrate` disagree on test module names

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nixpkgs#204051]
### Describe the bug
There's a `module_path!` macro in Rust standard library that I think takes a value from `--crate-name` passed to `rustc` at compile time.

If I have a crate with integration tests, the value of this ends up being different when I invoke `cargo test` and when I use nix via `buildRustCrate`.

### Steps To Reproduce

I've made a repro at https://github.com/Fuuzetsu/nixpkgs-rust-integration-test-repro , please take a look. Set your preferred `nixpkgs` with `-I` or `NIX_PATH` or whatever.

You can see the output in there.

### Expected behavior
I would expect the behaviour to match that of `cargo`.

### Additional context

I believe this is a problem with the below

```bash
build_bin_test_file() {
    local file="$1"
    local derived_crate_name="${file//\//_}"
    derived_crate_name="${derived_crate_name%.rs}"
    build_bin_test "$derived_crate_name" "$file"
}
```
It's invoked as follows in `build-crate.nix`:

```bash
      find tests -maxdepth 1 \( -type f -o -type l \) -a -name '*.rs' -print0 | while IFS= read -r -d ''' file; do
        mkdir -p target/bin
        build_bin_test_file "$file"
      done

      # find all the subdirectories of tests/ that contain a main.rs file as
      # that is also a test according to cargo
      find tests/ -mindepth 1 -maxdepth 2 \( -type f -o -type l \) -a -name 'main.rs' -print0 | while IFS= read -r -d ''' file; do
        mkdir -p target/bin
        build_bin_test_file "$file"
      done
```

I think the solution is to always strip the leading `tests` directory for `derived_crate_name` and then it will just work.

### Notify maintainers
Not sure who's in charge. @Ericson2314 ? @aanderse ?

### Metadata
Testing on nixpkgs `975b5083923b915d33dd57670e03553de1e5a3d6`, rest seems irrelevant...

**Comment by aanderse** [comment]
@Fuuzetsu not sure how my name came up here, but I haven't dealt much with the lower level `rust` stuff in `nixpkgs`. Sorry!

**Comment by Fuuzetsu** [comment]
> @Fuuzetsu not sure how my name came up here, but I haven't dealt much with the lower level `rust` stuff in `nixpkgs`. Sorry!

I think I saw your name on some recent Rust-related merge. Apologies for mis-notification!

**Comment by winterqt** [comment]
Is there a reason you're using `buildRustCrate` over `buildRustPackage`?

**Comment by Fuuzetsu** [comment]
> Is there a reason you're using `buildRustCrate` over `buildRustPackage`?

We're using [`crate2nix`](https://github.com/kolloch/crate2nix). AFAIU `buildRustPackage` just builds 1 thing in isolation with help of `cargo`, without caching of dependencies and so on: only really useful to build a binary or something. We're instead developing Rust software with large dependency tree and such.
