### ISSUE TITLE
Nuclear Music Player OOD

### ISSUE THREAD

**Issue by isaacbrown92** [NixOS/nixpkgs#204006]
Nuclear Music Player isn't up to date, won't play songs.

ivar.scholten@protonmail.com is maintainer.

https://search.nixos.org/packages?channel=unstable&show=nuclear&from=0&size=50&sort=relevance&type=options&query=nuclear+music is OOD.

Sorry I couldn't understand the formatting for this thing.

Thank you!

**Comment by eclairevoyant** [comment]
#245680
