### ISSUE TITLE
mcfly is not just for bash

### ISSUE THREAD

**Issue by voidzero** [NixOS/nixpkgs#204018]
https://github.com/NixOS/nixpkgs/blob/596a8e828c5dfa504f91918d0fa4152db3ab5502/pkgs/tools/misc/mcfly/default.nix#L24

@marsam I think you're the person to contact about this? Just a trivial issue with the description - mcfly is not only for bash but also for zsh and fish.

**Comment by abathur** [comment]
It looks like Marsam touched it last, but just to remove the period. The maintainer, @melkor333, wrote the description.

**Comment by Melkor333** [comment]
IIRC I copied the description from the Mcfly project page. It probably makes sense to replace it with the current tldr:
```
An upgraded ctrl-r where history results make sense for what you're working on right now.
```

**Comment by voidzero** [comment]
Much thanks. 🌞
