### ISSUE TITLE
`openjdk17` FTBFS on WSL2 specifically

### ISSUE THREAD

**Issue by K900** [NixOS/nixpkgs#204152]
```
       > checking for greadlink... [not found]
       > checking for readlink... /nix/store/a7gvj343m05j2s32xcnwr35v31ynlypr-coreutils-9.1/bin/readlink
       > checking for cygpath... [not found]
       > checking for wslpath... [not found]
       > checking for lsb_release... [not found]
       > checking for cmd.exe... [not found]
       > checking for cmp... /nix/store/j9p3g8472iijd50vhdprx0nmk2fqn5gv-diffutils-3.8/bin/cmp
       > checking for uniq... /nix/store/a7gvj343m05j2s32xcnwr35v31ynlypr-coreutils-9.1/bin/uniq
       > checking build system type... x86_64-pc-wsl
       > checking host system type... x86_64-pc-wsl
       > checking target system type... x86_64-pc-wsl
       > checking openjdk-build os-cpu... windows-x86_64
       > checking openjdk-target os-cpu... windows-x86_64
       > checking compilation type... native
       > checking Windows environment type... wsl1
       > configure: error: Incorrect wsl1 installation. Neither cygpath nor wslpath was found
       > configure exiting with result code 1
```

They're trying to be smart: https://github.com/openjdk/jdk17u-dev/blob/da6fca4d78465625775f7b384ba752185694f699/make/autoconf/build-aux/config.guess#L59

We should probably patch that check out, but maybe people with actual Java experience will have better ideas.

@edwtjo @asbachb

**Comment by SuperSandro2000** [comment]
We need to patch that. Neither do we want to provide cygpath nor can we wslpath because that would most likely try to escape the sandbox.

**Comment by K900** [comment]
The thing here is that they see WSL and automatically assume we're cross-compiling to a Windows target, which we're not. We can patch this out, or maybe we can force it to not cross-compile somehow, or maybe we can make `uname` lie.

**Comment by SuperSandro2000** [comment]
I would recommend to just patch that out.

**Comment by andreaugustoaragao** [comment]
I'm trying to use it on aarch64 and this is failing:

`[6/257] Building CXX object libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
/nix/store/fsn9mccnjinl212ypa3rx8b8647s9klh-gcc-wrapper-12.2.0/bin/g++ -DCEF_USE_SANDBOX -DNDEBUG -DWRAPPING_CEF_SHARED -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -I/build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal -O3 -DNDEBUG -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++14 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -MF libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o.d -o libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -c /build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal/libcef_dll/base/cef_lock.cc
g++: error: unrecognized command-line option '-m64'
ninja: build stopped: subcommand failed.
error: builder for '/nix/store/a7r53z6050vvhlmwnxac6c6kp41gcz2g-jcef-jetbrains-654.drv' failed with exit code 1;
       last 10 log lines:
       > g++: error: unrecognized command-line option '-m64'
       > [5/257] Building CXX object libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o
       > FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o
       > /nix/store/fsn9mccnjinl212ypa3rx8b8647s9klh-gcc-wrapper-12.2.0/bin/g++ -DCEF_USE_SANDBOX -DNDEBUG -DWRAPPING_CEF_SHARED -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -I/build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal -O3 -DNDEBUG -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++14 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o -MF libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o.d -o libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_callback_internal.cc.o -c /build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal/libcef_dll/base/cef_callback_internal.cc
       > g++: error: unrecognized command-line option '-m64'
       > [6/257] Building CXX object libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
       > FAILED: libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o
       > /nix/store/fsn9mccnjinl212ypa3rx8b8647s9klh-gcc-wrapper-12.2.0/bin/g++ -DCEF_USE_SANDBOX -DNDEBUG -DWRAPPING_CEF_SHARED -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -I/build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal -O3 -DNDEBUG -fno-strict-aliasing -fPIC -fstack-protector -funwind-tables -fvisibility=hidden --param=ssp-buffer-size=4 -pipe -pthread -Wall -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-error=comment -Wno-comment -Wno-deprecated-declarations -m64 -march=x86-64 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++14 -Wsign-compare -Wno-undefined-var-template -Wno-literal-suffix -Wno-narrowing -Wno-attributes -O2 -fdata-sections -ffunction-sections -fno-ident -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -MD -MT libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -MF libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o.d -o libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/base/cef_lock.cc.o -c /build/source/third_party/cef/cef_binary_104.4.26+g4180781+chromium-104.0.5112.102_linux64_minimal/libcef_dll/base/cef_lock.cc
       > g++: error: unrecognized command-line option '-m64'
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/a7r53z6050vvhlmwnxac6c6kp41gcz2g-jcef-jetbrains-654.drv'.
error: 1 dependencies of derivation '/nix/store/9mds0h6675lnh8hgam63xycvv8lrb01v-jetbrains-jdk-jcef-17.0.6-b829.5.drv' failed to build`

**Comment by K900** [comment]
WSL2 on aarch64? Also, this error is for Chromium.

**Comment by andreaugustoaragao** [comment]
Sorry, never mind. I'm having an issue with jetbrains.jdk, that has a dependency on CEF. I posted in an incorrect place. I opened a separate ticket. Please ignore.
