### ISSUE TITLE
Change wiki migration announcement language

### ISSUE THREAD

**Issue by shanemikel** [NixOS/nixpkgs#20419]
> The NixOS wiki is outdated and is being shut down.

Not to appear nit-picky, but I think this announcement should be changed.  My first impression was that it sounds like a going out of business sign.  Also, is there a link to the new wiki?

**Comment by NeQuissimus** [comment]
I think it is "going out of business". AFAIK all the information is being migrated into the NixOS manual.

Follow this milestone for progress:
https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Move+the+wiki%21%22

**Comment by shanemikel** [comment]
That seems odd to me.  So there will be no user wiki?  The manual itself reads very nicely as it is, and has a very reasonable scope:  Basic use and features, fundamental concepts, expression language reference and a small packaging tutorial.  As it is I can actually read through the manual "cover to cover" with a good experience.

Putting a bunch of recipes for (somewhat ephemeral, in the sense they are tied to nixpkgs organization and package config apis) specific software configurations in a blessed semi-static manual feels misguided.  Unless the plan is to simply trash everything that doesn't fit or is likely to change.

**Comment by shanemikel** [comment]
Cleaning it up, consolidating redundant information and removing old irrelevant stuff is a great idea.  Though I'm getting good use of the wiki right now.

Perhaps the wiki model could be revised a little to better fit the nature of the content?

-  Prominent dating and historical information for articles (linking code examples to the current nixpkgs release at publishing time, for instance)
- An easy way for readers to mark whether following a particular guide worked for them (like buttons on code blocks, for instance) using a particular nixpkgs release?

Combing the nixpkgs code for configuration options is surprisingly easy, I'm starting to realize.  Are there plans yet for generating documentation from the configuration attributes and example strings?

**Comment by shanemikel** [comment]
I noticed that milestone doesn't give any explanation for the decision.
