### ISSUE TITLE
`webkitgtk`,`webkitgtk_4_1`: fail to build on Hydra

### ISSUE THREAD

**Issue by azahi** [NixOS/nixpkgs#204124]
### Steps To Reproduce
1. Update to the latest `nixpkgs-unstable`.
2. `nixos-rebuild switch` or try to install, for instance, `telegram-desktop` or `lutris`.

### Build log
https://hydra.nixos.org/build/200398100
https://hydra.nixos.org/build/200399787

### Additional context
WebKitGTK is not cached and forces a local rebuild. I didn't test whether the local build fails or not but judging by Hydra logs it seems like the build job got OOM'd or otherwise timed out. Building WebKitGTK locally is too burdensome for most of the users and it currently blocks updating a few packages.

### Notify maintainers
@NixOS/gnome
@grahamc (In case that's an issue with Hydra)

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 23.05 (Stoat), 23.05.20221125.55b3f68`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/bakb5md3rx6p1dvsf8p4fpaflg5aakd4-source`

**Comment by Vinetos** [comment]
I have tried to built it locally but it is consuming way more than 16 Go of RAM.

Maybe it is the reason of the failed build.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/issues/195522

The build of webkitgtk keeps getting heavier and heavier :/

**Comment by azahi** [comment]
> #195522

The issue seems to be [resolved](https://hydra.nixos.org/build/200398100) now. I'll close this since we already have a separate issue to track high memory usage.
