### ISSUE TITLE
hardware.sane.enable conflicts with opengl

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixpkgs#20420]
I just updated to the latest nixos-unstable. nixos-rebuild gives

error: The unique option `environment.sessionVariables.LD_LIBRARY_PATH' is defined multiple times, in `/etc/nixos/nixpkgs/nixos/modules/services/hardware/sane.nix' and `/etc/nixos/nixpkgs/nixos/modules/hardware/opengl.nix'.

setting `hardware.sane.enable = false` gets rid of the error, but that's obviously not ideal

**Comment by ericsagnes** [comment]
Look similar to https://github.com/NixOS/nixpkgs/pull/20145#discussion_r87717658.
What is the `nixos-version`?

**Comment by ttuegel** [comment]
This seems to be fixed in master, but it's still a problem in the unstable channel.

**Comment by anderspapitto** [comment]
I'm on commit a24728fe295f28648f1812b3565541f7ef6269f1. if it's fixed in master feel free to close (i'll also check again sometime after the next channel update)
