### ISSUE TITLE
rust-analyzer installed by rustup not in path

### ISSUE THREAD

**Issue by theduke** [NixOS/nixpkgs#204208]
### Describe the bug

rustup distributes the `rust-analyzer` binary, which can be installed with `rustup component add rust-analyzer`.

Unlike the other binaries that are managed by rustup (`rustc`, `cargo`) the `rust-analyzer` binary will not have a wrapper that forwards to the installed binary, which is located at paths like: `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer`

This needs to be added to the path manually for editors that use RA to work properly.

### Expected behavior

rust-analyzer is in the path after running `rustup component add rust-analyzer`.

### Notify maintainers

@Mic92 

```

**Comment by miangraham** [comment]
This is [a known deficiency of current rustup](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#rust-analyzer-is-now-available-via-rustup) that's expected to get fixed on their end soon. I don't think this is a nixpkgs problem.

**Comment by theduke** [comment]
I concur.
