### ISSUE TITLE
dockerTools.pullImage should have a documented working example

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20436]
The manual documents an example, but it doesn't actually work, not is it self-contained. Given the mutable nature of sha256 hashes, I suggest there should be a script which writes a valid self-contained example to stdout (for example something which installs Debian).

**Comment by domenkozar** [comment]
@lethalman

**Comment by Profpatsch** [comment]
There’s an `./examples.nix` file now.
