### ISSUE TITLE
hp-setup is broken

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20438]
```
hp-setup 
Traceback (most recent call last):
  File "/nix/store/svcq6lq2j0lycmcr9c9j55y72fc338gw-hplip-3.16.5/share/hplip/setup.py", line 48, in <module>
    from base import device, utils, tui, models, module, services, os_utils
  File "/nix/store/svcq6lq2j0lycmcr9c9j55y72fc338gw-hplip-3.16.5/share/hplip/base/device.py", line 42, in <module>
    from . import status
  File "/nix/store/svcq6lq2j0lycmcr9c9j55y72fc338gw-hplip-3.16.5/share/hplip/base/status.py", line 33, in <module>
    import cupsext
ImportError: No module named cupsext
```
NixOS 16.09

**Comment by ericsagnes** [comment]
See also #19469 and #19882.

**Comment by domenkozar** [comment]
@FRidh can we backport https://github.com/NixOS/nixpkgs/pull/19882

**Comment by FRidh** [comment]
Fixed with 80aef869b29f2341727de1410d46def1218ce341 and 787d61d5c712ef3f63d779d1d88b6b805e827c82

**Comment by fubarbaz** [comment]
This doesn't work yet on 16.09.git.80aef86 (Flounder).

```
 hp-setup 
Traceback (most recent call last):
  File "/run/current-system/sw/bin/hp-setup", line 48, in <module>
    from base import device, utils, tui, models, module, services, os_utils
  File "/nix/store/i7kkg79ax0sbnrayzkfawhn3cpz11lwn-python2.7-hplip-3.16.5/share/hplip/base/device.py", line 42, in <module>
    from . import status
  File "/nix/store/i7kkg79ax0sbnrayzkfawhn3cpz11lwn-python2.7-hplip-3.16.5/share/hplip/base/status.py", line 33, in <module>
    import cupsext
ImportError: No module named cupsext
```

**Comment by FRidh** [comment]
Correct, https://github.com/NixOS/nixpkgs/commit/787d61d5c712ef3f63d779d1d88b6b805e827c82 is needed as well.
```
$ nix-env  -f https://github.com/NixOS/nixpkgs/archive/787d61d5c712ef3f63d779d1d88b6b805e827c82.tar.gz -iA hplip && hp-setup
```

**Comment by fubarbaz** [comment]
@FRidh While auto-discovery didn't work, all I had to do is provide an IP of the printer. Great. Yes, it is fixed.

**Comment by listx** [comment]
This does not work for me. I did

```
nix-env  -f https://github.com/NixOS/nixpkgs/archive/787d61d5c712ef3f63d779d1d88b6b805e827c82.tar.gz -iA hplipWithPlugin && hp-setup
```
and although I can discover my printer by typing in the IP manually, it then needs to download a plugin binary and the recommended option fails with `error: GPG command not found`. I tried to download the plugin manually from https://www.openprinting.org/download/printdriver/auxfiles/HP/plugins/ but that doesn't work either when I run hp-plugin (pasted below is the error I get when I try to make it use the downloaded file directly):

```Downloading plug-in from: file:///home/l/hplip-3.16.5-plugin.run
sh: lsb_release: command not found
warning:  distro is not found in AUTH_TYPES                                                                                                                                     100%error: Failed to open URL: file:///home/l/hplip-3.16.5-plugin.run.asc
error: Plug-in GPG file [file:///home/l/hplip-3.16.5-plugin.run.asc] download failed.
Creating directory plugin_tmp
Verifying archive integrity... All good.
Uncompressing HPLIP 3.16.5 Plugin Self Extracting Archive................................................
/home/l/.hplip/hplip-3.16.5-plugin.run: ./hplip-plugin-install: /bin/bash: bad interpreter: No such file or directory
error: Python gobject/dbus may be not installed                                                                                                                                   error: Plug-in install failed
```

**Comment by FRidh** [comment]
>  it then needs to download a plugin binary and the recommended option fails with error: GPG command not found.

Guess we need to add gpg to PATH then.

>  I tried to download the plugin manually from https://www.openprinting.org/download/printdriver/auxfiles/HP/plugins/ but that doesn't work either when I run hp-plugin (pasted below is the error I get when I try to make it use the downloaded file directly):

Nope, installers typically won't work on Nix.

**Comment by FRidh** [comment]
@listx could you open a new issue for this?

**Comment by listx** [comment]
@FRidh will do.
