### ISSUE TITLE
broken package: Pitivi

### ISSUE THREAD

**Issue by dermetfan** [NixOS/nixpkgs#20449]
## Issue description

`nix-env -iA nixos.pitivi`

On launch:
```
Could not import 'gi'. Make sure you have pygobject available.
```

## Technical details

* System: `17.03.git.33afbf8 (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `17.03pre95306.a24728"`

**Comment by FRidh** [comment]
That error occurs because the interpreter cannot find the Python modules. The "old" solution is to create a wrapper that sets `PYTHONPATH`. A better solution is to instead create a Python environment that can find the modules without setting `PYTHONPATH`. 

I've tried that, and found out that, while Pitivi requires Python 3, some modules it depends on were build against Python 2. This is a problem.

**Comment by moretea** [comment]
It broke for me on stable with a different cause:

```
[maarten@maarten-laptop:~]$ nix-shell --pure -p pitivi --command pitivi
Couldn't set locale. /nix/store/1dpfyblhgrad7knv0n6k9n8ajmdll0lh-pitivi-0.96/share/locale unsupported locale setting

(.pitivi-wrapped:19980): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
ERROR - The following hard dependencies are unmet:
==================================================
- gstgtk not found on the system
Missing soft dependency:
- pycanberra not found on the system
    -> enables sound notifications when rendering is complete
```

**Comment by davidak** [comment]
```
[davidak@dc7800:~]$ nix-shell --pure -p pitivi --command pitivi

** (.pitivi-wrapped:4153): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
ERROR - The following hard dependencies are unmet:
==================================================
- gstgtk not found on the system
Missing soft dependency:
- pycanberra not found on the system
    -> enables sound notifications when rendering is complete
```

---

 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.70, NixOS, 18.03pre123130.1bc288591ea (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"nixos-18.03pre123130.1bc288591ea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

**Comment by mogorman** [comment]
@davidak  on 17.09 it runs for me in a pure nix-shell or normally @dermetfan can you confirm and close?

**Comment by davidak** [comment]
Pitivi also starts on my NixOS 17.09 system. It has other issues unrelated to this.
