### ISSUE TITLE
BlueZ: Auxiliary config files are loaded from the package directory (`input.conf` / `network.conf`)

### ISSUE THREAD

**Issue by jbit** [NixOS/nixpkgs#204418]
### Describe the bug
BlueZ is currently setup to read auxiliary config files (i.e. `input.conf`, `network.conf`) from its package directory, which makes it hard to write to them properly on a NixOS system.

These configuration files are the only way to configure certain behaviours of `bluetoothd`, such as `IdleTimeout` in `input.conf`, which is an important setting for device power saving.

It's not possible to specify these options in  `/etc/bluetooth/main.conf`. And it's not possible to specify the path of `input.conf` at runtime.

### Steps To Reproduce
1. Write a `/etc/bluetooth/input.conf` file, either manually or from a nix configuration.
2. Restart `bluetoothd` with `systemctl restart bluetooth`.
3. Notice `bluetoothd` hasn't loaded any settings from `input.conf`.
4. (It's easy to test if you fill `input.conf` with trash since it should log: `Key file contains line “fasdfasdfasdfasdfadsfasdf” which is not a key-value pair, group, or comment`).

### Expected behavior
It should be possible to configure all aspects of `bluetoothd` in the same way.

### Additional context
BlueZ loads `input.conf` from a hardcoded path: https://github.com/bluez/bluez/blob/35947e26771c89d965aec5ad059267bb8c15298e/profiles/input/manager.c#L83
```c
	config = load_config_file(CONFIGDIR "/input.conf");
```

The same is try for `network.conf`: https://github.com/bluez/bluez/blob/35947e26771c89d965aec5ad059267bb8c15298e/profiles/network/manager.c#L161
```c
	read_config(CONFIGDIR "/network.conf");
```

The `CONFIGDIR` define is set to the package directory by default.

For `main.conf` a symlink is setup, however no such link is setup for `input.conf` or `network.conf`: https://github.com/NixOS/nixpkgs/blob/8bc39a24bcef4d2aefebaa06b3ed75128599a262/pkgs/os-specific/linux/bluez/default.nix#L122

I wonder if a fix for this might be adding `--sysconfdir=/etc` to the `.configureFlags` of BlueZ?

### Notify maintainers
There's no maintainer listed in `bluez/main.conf`, so I'm pinging the people who last touched it :)

@ymatsiuk , @Artturin, @fgaz

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.05 (Quokka), 22.05.4394.5d7d1d5f742`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ymatsiuk** [comment]
I feel like this could be easily fixed rather in the [module](https://github.com/NixOS/nixpkgs/blob/61a8a98e6d557e6dd7ed0cdb54c3a3e3bbc5e25c/nixos/modules/services/hardware/bluetooth.nix#L89) by adding 2 more options for `inputs` and `network` under `hardware.bluetooth.pofiles` (?)
Let me see if I can carve out some time later this week..

**Comment by fgaz** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/204653
