### ISSUE TITLE
KDE 5 packages missing from binary cache

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixpkgs#20445]
## Issue description

Gwenview, kdenlive and possibly others are missing from the release-16.09 jobset, see e.g. http://hydra.nixos.org/eval/1304471?filter=gwenview&compare=1304397. Thus they get built from source which is annoying.

### Steps to reproduce

```
$ nix-build '<nixpkgs>' -A kde5.gwenview
```

## Technical details

* System: 16.09.1026.5ddaca1

**Comment by edolstra** [comment]
Ping @ttuegel.

**Comment by ttuegel** [comment]
What actually determines the release-channel packages that get built into the cache? For the trunk-combined job, `nixos/release-combined.nix` calls `pkgs/top-level/release.nix`, but I don't see that anywhere in `nixos/release.nix`.

**Comment by vcunat** [comment]
I think it should be mainly `recurseIntoAttrs` and `meta.platforms`, though it is possible to add packages explicitly.

**Comment by vcunat** [comment]
`kde5.gwenview.meta.platforms` is missing; this should be (also) fixed by #19990 in future.

**Comment by ttuegel** [comment]
> kdeWrapper is eating meta, apparently.

Oops! Thanks for pointing that out.

**Comment by edolstra** [comment]
Thanks!
