### ISSUE TITLE
github-runner: working directory out of memory

### ISSUE THREAD

**Issue by newAM** [NixOS/nixpkgs#204503]
## Issue description

Working with large repositories on low-memory systems (such as aarch64-linux SBCs) can lead to out-of-storage scenarios with the github-runner service because the working directory is set to `/run/` by default [[1]](https://github.com/NixOS/nixpkgs/blob/660e7737851506374da39c0fa550c202c824a17c/nixos/modules/services/continuous-integration/github-runner/service.nix#L9), which is sized to 25% of the system memory by default [[2]](https://github.com/NixOS/nixpkgs/blob/660e7737851506374da39c0fa550c202c824a17c/nixos/modules/tasks/filesystems.nix#L265).

Ideally there can be an option to use storage instead of memory for the working directory.

I'm opening an issue first because I am not sure if there is a way to work around this already; can the `runtimeDir` argument in the service be overridden, or is there another way to change `%t` for this service with a systemd setting?

If there isn't a straightforward solution I can open a PR to add this as an option.

Maintainers: @veehaitch @newam @kfollesdal @aanderse

**Comment by veehaitch** [comment]
I also experienced issues with no space left on `/run/`. So far, however, increasing the size of `/run` did the job.

Nevertheless, I'd also appreciate the option to use another filesystem for the runtime directory. We won't be able to use systemd for that as it demands a `tmpfs`-like filesystem for the runtime directory.

**Comment by aanderse** [comment]
Yeah, in our case using the runtime directory that `systemd` provides makes the most sense for dynamic user, again, with documentation on how to increase the size of the runtime directory.

Currently our module doesn't support static users so `--work` isn't very useful... though I'm guessing our lack of support for static users is an oversight - see details here:
https://github.com/NixOS/nixpkgs/blob/f21f11aa2a02cb78651c6d57546c7d7541f9240c/nixos/modules/services/continuous-integration/github-runner/service.nix#L253-L255
