### ISSUE TITLE
hexyl 0.10.0 -> 0.11.0

### ISSUE THREAD

**Issue by sharifhsn** [NixOS/nixpkgs#204646]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: hexyl

current version: 0.10.0
desired version: 0.11.0

###### Notify maintainers

maintainers:
@dywedir 
@SuperSandro2000 
###### Note for maintainers

Please tag this issue in your PR.

**Comment by tjni** [comment]
Thanks for your work optimizing the program!
