### ISSUE TITLE
HeroicGamesLauncher v2.4.3 is outdated

### ISSUE THREAD

**Issue by Nokogiri** [NixOS/nixpkgs#204651]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: heroic

current version: 2.4.3
desired version: 2.5.0

###### Notify maintainers

maintainers: @aidalgol 
###### Note for maintainers

Please tag this issue in your PR.

**Comment by aidalgol** [comment]
Looks like they've changed the build system so I need to do more than just bump the tag in the fetcher.

**Comment by aidalgol** [comment]
Updated and rebased against recent `master`.
