### ISSUE TITLE
faust2jaqt miss qmake-qt4/qmake-qt5

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#20473]
## Issue description
faust2jaqt missing qmake-qt4/qt5

https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/applications/audio/faust/faust2jaqt.nix

**Comment by Profpatsch** [comment]
Seems to be fixed.
