### ISSUE TITLE
installer iso not booting on some cpus due to glibc bug

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#204721]
Specifically systems with AVX but without BMI2

Same as this debian bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019855

They solved it by pulling the latest stable 2.35 patches:
https://salsa.debian.org/glibc-team/glibc/-/commit/751bcc1071fd7ca6352e00ab51936ea1c50180be

https://sourceware.org/git/?p=glibc.git;a=history;f=sysdeps/x86_64;hb=refs/heads/release/2.35/master

For NixOS, one workaround is to install a NixOS system to a usb drive with microcode updates enabled, and use that for the installation. This is because for this series of CPUs (Haswell, 3rd/4th gen) the BMI2 instructions are added via a microcode update.

Rebuilding the iso with this overlay also works, but this is a mass-rebuild:
```nix
{ modulesPath, pkgs, ... }:

{
  imports = [
    (modulesPath + "/installer/cd-dvd/installation-cd-minimal.nix")
  ];

  nixpkgs.overlays = [
    (final: prev: {
      glibc = prev.glibc.overrideAttrs (oldAttrs: {
        version = "2.35-220";
        patches = oldAttrs.patches ++ [
          ./glibc-2.35-163-to-220.diff
        ];
      });
    })
  ];
}
```

The diff is produced like this:

```
git clone https://sourceware.org/git/glibc.git
cd glibc
git checkout e7019eeeb5f9eb3bab956fb1ecfc867bf257bc9d
git show --minimal --reverse 0e5b239f45992e4b54c6f946ecb0c410afc8bb08.. > glibc-2.35-163-to-220.diff
```
Where `e7019eeeb5f9eb3bab956fb1ecfc867bf257bc9d` corresponds to 2.35-220 and `0e5b239f45992e4b54c6f946ecb0c410afc8bb08` corresponds to 2.35-163 (our previous state).

**Comment by yu-re-ka** [comment]
It was attempted to update glibc to the latest stable patches in https://github.com/NixOS/nixpkgs/pull/201805, but this led to some issues.

**Comment by vcunat** [comment]
A temporary fix without rebuilds would be via `system.replaceRuntimeDependencies`, I suppose.

Real fix (taking more time, `staging` etc.): most likely update glibc to latest 2.35.x and somehow resolve the `.twisted` regression (and possibly others), and then backport to 22.11 as well.

**Comment by vcunat** [comment]
Redoing update as PR #205133 for now.

**Comment by vcunat** [comment]
The glibc update is contained in `nixos-unstable` and `nixos-22.11` channels now.
