### ISSUE TITLE
Dwarf Fortress does not display window contents on macOS

### ISSUE THREAD

**Issue by 2xsaiko** [NixOS/nixpkgs#204851]
### Describe the bug
Running Dwarf Fortress (`nix run nixpkgs#pkgsx86_64Darwin.dwarf-fortress`) on darwin-aarch64 opens a window that is completely white. It receives inputs and sound also plays, but nothing is displayed. This might be due to the package not having an app bundle as an output (e.g. 'Applications/Dwarf Fortress' next to bin)

### Steps To Reproduce
1. Run dwarf-fortress on macOS

### Expected behavior
Window opens with graphics displayed

### Screenshots
![image](https://user-images.githubusercontent.com/3987560/206016408-c7131816-5a0b-498c-96e1-49d6282ad4f0.png)

### Notify maintainers

@a1russell @robbinch @roconnor @abbradar @numinit @shazow 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
saiko@mulex-copan ~ % nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.0`
 - channels(saiko): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by 2xsaiko** [comment]
I should have tested the files from the official website first, since it turns out it has the same issue. Changing PRINT_MODE to STANDARD made it display correctly.

I don't know if the init.txt should still be patched in nixpkgs to include this so that you can leave the link to the store for the file. Feel free to close this otherwise.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixpkgs/pull/212423
