### ISSUE TITLE
Request for support of popular Minecraft launcher "PrismLauncher"

### ISSUE THREAD

**Issue by Ahptt** [NixOS/nixpkgs#204880]
**PrismLauncher is a custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once**

**I'm on a custom build of Debian and am loving the Nix installer. I noticed there wasn't a package for this wonderful program, and was curious if anyone was willing to maintain one for this program.**

_The Github page has a makedeb installer, but currently it isn't working, and it would be really nice to have a more efficient way to install. Thanks to anyone willing! Your work is much appreciated._

* homepage URL: https://prismlauncher.org/
* source URL: https://github.com/PrismLauncher/PrismLauncher
* license: GPL-3.0
* platforms: Linux

**Comment by OPNA2608** [comment]
The packages `prismlauncher` and `prismlauncher-qt5` are already available on the 22.11 and unstable channels: https://search.nixos.org/packages?type=packages&query=prismlauncher

**Comment by Ahptt** [comment]
@OPNA2608 Thanks, I am new to Nix. I should've checked that. :/ Many thanks once more! :D
