### ISSUE TITLE
IPMITool 1.8.19 update breaks IANA registry loading

### ISSUE THREAD

**Issue by melvyn2** [NixOS/nixpkgs#204926]
### Describe the bug
Since #201171, `ipmitool` will search for the IANA registry file `enterprise-numbers`:
```c
openat(AT_FDCWD, "/root/.local/usr/share/misc/enterprise-numbers", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/nix/store/xi0xpcb1mxfj5rc07r15br2hww1fkfh5-ipmitool-1.8.19/share/misc/enterprise-numbers", O_RDONLY) = -1 ENOENT (No such file or directory)
```
These calls are not present in the previous version. However, this file is not present in the nix package, and so the tool complains on every use.

### Steps To Reproduce
1. Install ipmitool 1.8.19
2. Run a command such as `sudo ipmitool sdr`
3. See that the first line of the output is: `IANA PEN registry open failed: No such file or directory`

### Expected behavior
The behavior shown before this update, or the lack of the above line.

### Additional context
The registry file is available at https://www.iana.org/assignments/enterprise-numbers.txt ([license](https://www.iana.org/help/licensing-terms)). Downloading it to the first location checked above (`/root/.local/usr/share/misc/enterprise-numbers`) works as a temporary fix, though the file should really be packaged with the tool instead.

### Notify maintainers
@fpletz

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"                                                                                                                                                   
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.60, NixOS, 22.11 (Raccoon), 22.11.656.52e3e80afff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11, unstable"`
 - channels(***): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Myaats** [comment]
Adding the enterprise numbers will need some kind of mirroring that will ensure the source does not break daily. There is already something similar done for the IANA protocol numbers with https://github.com/Mic92/iana-etc/

**Comment by NickCao** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/220508, and the internet archive was used instead of mirroring it ourselves.
