### ISSUE TITLE
Many font derivations broken due to fetchzip interface change

### ISSUE THREAD

**Issue by endgame** [NixOS/nixpkgs#204925]
I decided to build nixos 22.11 with no substituters to test whether the build instructions still work. I filed #204734 and then discovered that basically all fonts using `fetchzip` + `postBuild` are broken (about half of all font derivations).

### Steps To Reproduce

Steps to reproduce the behavior on an example font:

1. `nix build --no-link github:nixos/nixpkgs/4f4073186f4714a6fbca4e649e568fb35ac8811e#ultimate-oldschool-pc-font-pack`
2. `nix build -L --no-link --rebuild github:nixos/nixpkgs/4f4073186f4714a6fbca4e649e568fb35ac8811e#ultimate-oldschool-pc-font-pack`

### Build log
```
trying https://int10h.org/oldschool-pc-fonts/download/oldschool_pc_font_pack_v2.2_linux.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0 >
unpacking source archive /build/oldschool_pc_font_pack_v2.2_linux.zip
error: zip file must contain a single file or directory.
hint: Pass stripRoot=false; to fetchzip to assume flat list of files.
```

### Additional context
Baking the "build" step for these fonts into the `postBuild` attribute of `fetchzip` was done to prevent one additional derivation per font, but they silently broke when 5a6a31e54ddaf59aa8e1c5e7e9b02623d4881c34 added a `postBuild` argument to `fetchzip`. I am of the opinion that an optimisation must not enable silent breakage and favour rewriting them to use `stdenvNoCC`, but I am open to other suggestions.

### Affected packages
These were found by fetching from the cache, and then attempting to rebuild each font as per the repro instructions above:

- [ ] aileron - 404s
- [ ] andagii - build failure
- [ ] andika - build failure
- [ ] ankacoder - build failure
- [ ] ankacoder-condensed - build failure
- [ ] annapurna-sil - build failuer
- [ ] anonymousPro - 404s
- [ ] aurulent-sans - build failure
- [ ] babelstone-han - build failure
- [ ] baekmuk-ttf - build failure
- [ ] bakoma-ttf - build failure
- [ ] barlow - build failure
- [ ] behdad-fonts - build failure
- [ ] borg-sans-mono - build failure
- [ ] cabin - build failure
- [ ] caladea - build failure
- [ ] cascadia-code - build failure
- [ ] charis-sil - build failure
- [ ] cherry - build output nondeterministic
- [ ] cm-unicode - build failure
- [ ] comfortaa - build failure
- [ ] comic-mono-font - build failure
- [ ] comic-relief - build failure
- [ ] courier-prime-unstable - build failure
- [ ] Cozette - build failure
- [ ] crimson - build failure
- [ ] culmus - build failure
- [ ] curie - build failure
- [ ] d2codingfont - build failure
- [ ] dancing-script - build failure
- [ ] dina-font - build output nondeterministic
- [ ] dosis - build failure
- [ ] doulos-sil - build failure
- [ ] eb-garamond - build failure
- [ ] emacs-all-the-icons-fonts - build failure
- [ ] emojione - build output nondeterministic
- [ ] encode-sans - build failure
- [ ] et-book - build failure
- [ ] eunomia-font - build failure
- [ ] ezra-sil - build failure
- [ ] f5_6-font - build failure
- [ ] fantasque-sans-mono - build failure
- [ ] ferrum-font - build failure
- [ ] fira - build failure
- [ ] fira-code - build failure
- [ ] fira-code-symbols - build failure
- [ ] fira-mono - build failure
- [ ] fraunces - build failure
- [ ] galatia-sil - build failure
- [ ] gandom-fonts - build failure
- [ ] gelasio - build failure
- [ ] gentium - build failure
- [ ] gentium-book-basic - build failure
- [ ] gyre-fonts - build failure
- [ ] hack-font - build failure
- [ ] hanazono - timed out trying to fetch from upstream
- [ ] hasklig - build failure
- [ ] hyperscript-font - build failure
- [ ] ia-writer-duospace - build failure
- [ ] ibm-plex - build failure
- [ ] inriafonts - build failure
- [ ] inter - build failure
- [ ] ipaexfont - build failure
- [ ] ipafont - build failure
- [ ] iwona - 404s
- [ ] JetBrainsMono - build failure
- [ ] jost - build failure
- [ ] junicode - build failure
- [ ] kacst - build failure
- [ ] kawkab-mono - build failure
- [ ] khmeros - build failure
- [ ] kreative-square-fonts-unstable - build failure
- [ ] lalezar-fonts-unstable - build failure
- [ ] lao - build failure
- [ ] lato - build failure
- [ ] libre-franklin - build failure
- [ ] lklug-sinhala - build failure
- [ ] lmmath - build failure
- [ ] lmodern - build failure
- [ ] luculent - build failure
- [ ] manrope - build failure
- [ ] marathi-cursive - build failure
- [ ] material-design-icons - build failure
- [ ] material-icons - build failure
- [ ] medio-font - build failure
- [ ] mno16 - build failure
- [ ] mononoki - build failure
- [ ] MPH - build failure
- [ ] mro-unicode - build failure
- [ ] myrica - build failure
- [ ] nahid-fonts - build failure
- [ ] nanum - build failure
- [ ] national-park-typeface - build failure
- [ ] nika-fonts - build failure
- [ ] norwester - build failure
- [ ] office-code-pro - build failure
- [ ] oldsindhi - build failure
- [ ] oldstandard - build failure
- [ ] open-dyslexic - build failure
- [ ] open-sans - build failure
- [ ] openmoji (black) - build output nondeterministic
- [ ] openmoji (color) - build output nondeterministic
- [ ] orbitron - build failure
- [ ] overpass - build failure
- [ ] oxygenfonts - build failure
- [ ] parastoo-fonts - build failure
- [ ] paratype-pt-mono - build failure
- [ ] paratype-pt-sans - build failure
- [ ] paratype-pt-serif - build failure
- [ ] penna-font - build failure
- [ ] powerline-fonts - build failure
- [ ] public-sans - build failure
- [ ] quattrocento - build failure
- [ ] quattrocento-sans - build failure
- [ ] raleway - build failure
- [ ] recursive - build failure
- [ ] redhat-official - build failure
- [ ] RhodiumLibre - build failure
- [ ] roboto - build failure
- [ ] rounded-mgenplus - build failure
- [ ] route159-font - 404s
- [ ] sahel-fonts - build failure
- [ ] samim-fonts - build failure
- [ ] sampradaya - build failure
- [ ] scheherazade - build failure
- [ ] scheherazade-new - build failure
- [ ] seshat-font - build failure
- [ ] shabnam-fonts - build failure
- [ ] shrikhand - build failure
- [ ] source-code-pro - build failure
- [ ] source-han-code-jp - build failure
- [ ] source-sans - build failure
- [ ] source-sans-pro - build failure
- [ ] source-serif - build failure
- [ ] source-serif-pro - build failure
- [ ] stix-otf - 404s
- [ ] stix-two - build failure
- [ ] sudo-font - build failure
- [ ] tai-ahom - build failure
- [ ] takao - build failure
- [ ] tempora-lgc - build failure (maybe not fetchzip?)
- [ ] tenderness-font - build failure
- [ ] terminus-font-ttf - build failure
- [ ] theano - build failure
- [ ] tibentan-machine - build failure
- [ ] times-newer-roman-unstable - build failure
- [ ] TT2020 - build failure
- [ ] ttf-bitstream-vera - build failure
- [ ] twitter-color-emoji - build output nondeterministic
- [ ] ultimate-oldschool-pc-font-pack - build failure
- [ ] undefined-medium - build failure
- [ ] unfonts-core - build failure
- [ ] uw-ttyp0 - build output nondeterministic
- [ ] vazir-code-font - build failure
- [ ] vazir-fonts - build failure
- [ ] vdrsymbols - build failure
- [ ] vegur-font - 404s
- [ ] victor-mono - hash mismatch
- [ ] vollkorn - build failure
- [ ] weather-icons - build failure
- [ ] work-sans - build failure
- [ ] wqy-microhei - build failure
- [ ] wqy-zenhei - build failure
- [ ] yanone-kaffeesatz - build failure
- [ ] zilla-slab - build failure

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/af5cj5flawmadxfjnfmr5yjqgws4h8ny-nix-info
copying path '/nix/store/af5cj5flawmadxfjnfmr5yjqgws4h8ny-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.20221204.e169cf5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.05, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Mindavi** [comment]
See https://github.com/NixOS/nixpkgs/pull/193478 and the PR: https://github.com/NixOS/nixpkgs/pull/173430

cc @Artturin

**Comment by Artturin** [comment]
I'll do a sprint to convert them all to mkDerivation

**Comment by vcunat** [comment]
`mkDerivation` has the slight disadvantage of getting rebuilt on every stdenv change (which is roughly every other week on master/unstable).  Though yes, the rebuilds will be cheap on CPU at least, so if the data (fonts) are relatively small...

**Comment by SuperSandro2000** [comment]
Also using a derivation just to copy files from $src to $out is a bit wasteful since an extra derivation is cheap but not free and this adds up.

**Comment by SuperSandro2000** [comment]
> I'll do a sprint to convert them all to mkDerivation

Please use stdenvNoCC

**Comment by rnhmjoj** [comment]
The packages marked "build output not deterministic" are actually all unrelated to fetchzip.
The non-determinism is coming from the gzip, of course.
