### ISSUE TITLE
unity - No usable version of libssl was found

### ISSUE THREAD

**Issue by lizelive** [NixOS/nixpkgs#205019]
### Steps To Reproduce
1. install unityhub
2.create new 2021.3.15f project
3.get error

### Expected behavior
that it would work

### Screenshots
![image](https://user-images.githubusercontent.com/40217331/206239700-b570448f-25ac-44cd-b9a1-e05fecb80b2d.png)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[lizelive@l05:~/Documents]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.656.52e3e80afff`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(lizelive): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lizelive** [comment]
previously had an old version of unity
but not possible to use anymore
also the desktop link doesn't work

**Comment by Zeerooth** [comment]
I'm currently also experiencing this, have you managed to solve it somehow?

**Comment by benley** [comment]
I'm seeing this too with unityhub 3.4.2 on nixos-unstable.

**Comment by loco-choco** [comment]
Found the same issue with unityhub 3.4.2 on nixos-23.05. From searching the issue online people seem to find that downloading the downgraded version of libssl (1.1) made it start to work, which should be the package openssl_1_1 (a insecure package). I tried to install openssl_1_1 but it seems the editor (2021.3.26f1) still could not find it.

I also tried with unity editor 2019, but it wouldn't even start to create a project (I don't think it is related to this issue, but didn't let me test if 2019 was affect anyway).

**Comment by huantianad** [comment]
If you're currently experiencing this issue, first try upgrading your editor to the latest point release, which should support OpenSSL 3. 

If that does not work, you can try adding `openssl_1_1` to the unityhub package like so:
```nix
environment.systemPackages = [
  (pkgs.unityhub.override {
    extraLibs = pkgs: with pkgs; [
      openssl_1_1
    ];
  })
];
```
Make sure you restart unityhub between this switch. If it doesn't work, try launching unityhub from terminal to make sure you're using the modified version, or reboot your PC.

Do note that `openssl_1_1` will be removed eventually, and after that point we won't be able to support Unity editor that uses OpenSSL 1.1. The best solution is to update to a version that supports OpenSSL 3.

I'm closing this issue for now, will reopen if there's any additional related issues.
