### ISSUE TITLE
norminette (42 schools)

### ISSUE THREAD

**Issue by 42fh** [NixOS/nixpkgs#205010]
check if a C project is formatted according to "the norm" specified in the provided PDF

* homepage URL: https://github.com/42School/norminette
* source URL: https://github.com/42School/norminette
* license: MIT
* platforms: 

also see this project that ?packages norminette for nix:
https://github.com/lightdiscord/nix-norminette

**Comment by wegank** [comment]
@lightdiscord Would you like to do the PR?

**Comment by lightdiscord** [comment]
Unfortunately, I recently stopped using nix. So I won't be able to create the package, test it or maintain it.
