### ISSUE TITLE
qtcreator: symbol lookup error: /nix/store/[...]-qtbase-5.5.1/lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface19registerTouchDeviceEP12QTouchDevice

### ISSUE THREAD

**Issue by jdanekrh** [NixOS/nixpkgs#20502]
## Issue description

qtcreator fails to start due to a linking error

### Steps to reproduce

    $ nix-channel --update
    downloading Nix expressions from ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.03pre95306.a24728f/nixexprs.tar.xz’...
    downloading ‘https://d3g5gsiof5omrk.cloudfront.net/nixos/unstable/nixos-17.03pre95306.a24728f/nixexprs.tar.xz’... [0/0 KiB, 0.0 KiB/ [7727/7835 KiB, 183.6 KiB/s]
    unpacking channels...

    $ nix-env -iA nixos.qtcreator && qtcreator
    warning: name collision in input Nix expressions, skipping ‘~/.nix-defexpr/channels_root/nixos’
    replacing old ‘qtcreator-4.1.0’
    installing ‘qtcreator-4.1.0’
    ~/.nix-profile/bin/qtcreator: symbol lookup error: /nix/store/3jblx6kq8j113sn9r7lql6k5gabk0dy9-qtbase-5.5.1/lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface19registerTouchDeviceEP12QTouchDevice

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
 -- `16.03.1299.a8e0739 (Emu)`
* Nix version: (run `nix-env --version`)
 -- `nix-env (Nix) 1.11.2`
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
-- `"16.09.773.b8ede35"`

**Comment by bjornfor** [comment]
I'm unable to reproduce on NixOS 17.09 (current stable).

**Comment by jdanekrh** [comment]
Thanks for checking into this. I stopped using qtcreator since, so I was not keeping watch on this. Good to hear it works now, though.
