### ISSUE TITLE
Fail to build RISC-V GNU Compiler Toolchain in NixOS;

### ISSUE THREAD

**Issue by PedroAntunes178** [NixOS/nixpkgs#205069]
### Steps To Reproduce
- git clone git@github.com:PedroAntunes178/MyNixOS_conf.git
- cd riscv-gnu-toolchain
- nix-build default.nix  

### Build log
```
building
/bin/sh: /build/source/scripts/march-to-cpu-opt: not found
cd /build/source && \
flock `git rev-parse --git-dir`/config git submodule init /build/source/gcc/ && \
flock `git rev-parse --git-dir`/config git submodule update /build/source/gcc/
error: pathspec '/build/source/gcc/' did not match any file(s) known to git
make: *** [Makefile:282: /build/source/gcc/.git] Error 1
error: builder for '/nix/store/7jfli9kxq4fnhl3w57xq84qcy012wlyy-riscv-gnu-toolchain-2022.11.23.drv' failed with exit code 2;
       last 10 log lines:
       > config.status: creating Makefile
       > config.status: creating scripts/wrapper/awk/awk
       > config.status: creating scripts/wrapper/sed/sed
       > building
       > /bin/sh: /build/source/scripts/march-to-cpu-opt: not found
       > cd /build/source && \
       > flock `git rev-parse --git-dir`/config git submodule init /build/source/gcc/ && \
       > flock `git rev-parse --git-dir`/config git submodule update /build/source/gcc/
       > error: pathspec '/build/source/gcc/' did not match any file(s) known to git
       > make: *** [Makefile:282: /build/source/gcc/.git] Error 1
       For full logs, run 'nix log /nix/store/7jfli9kxq4fnhl3w57xq84qcy012wlyy-riscv-gnu-toolchain-2022.11.23.drv'.
```

### Additional context
The error occurs when `git submodule init /build/source/gcc` is executed explicitly or by the riscv-gnu-toolchain Makefile.
You can see the default.nix build script [here](https://github.com/PedroAntunes178/MyNixOS_conf/blob/main/riscv-gnu-toolchain/default.nix).

The build steps basically follow the steps explained in https://github.com/riscv-collab/riscv-gnu-toolchain to build the Newlib and the Linux cross-compiler. 

I am not interested in using Nix cross-compiling RISC-V tools.  Since, while trying to use them, I have had linker problems in my project that I did not have while using the riscv-gnu-toolchain. Furthermore, there were problems of compatibility when I started using NixOS. Also with the NixOS cross-compiling tools I tried to do `riscv64-none-elf-gcc -print-multi-lib` and there was no output.

Also, I started using Nix recently and moved to NixOS to force myself to learn Nix and the correct ways to use it. But to use it has my daily driver, having the riscv-gnu-toolchain is essential.

### Notify maintainers
I don't really know who to notify. Therefore, the people mention are because I think they could be able to help. 
If you know someone else who could help, please mention them.
Thank you.
@Madouura 
@NickCao
@shlevy

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[pantunes@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.632.e169cf5b3b1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(pantunes): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by NickCao** [comment]
It would be a hard task, as the upstream build system downloads various things from the internet. However if you just wish to make it work, check https://zimbatm.com/notes/nix-packaging-the-heretic-way out for someways to get it done quick and dirty.

**Comment by NickCao** [comment]
The git issue seems to be related to our git fetcher, trying to run `git status` in postPatch shown that the repo is in a dirty status, and none of the submodules exists.

**Comment by NickCao** [comment]
Hacked a working version: https://gist.github.com/NickCao/bf6249c10cef5f8039e3618372abbc6a

**Comment by PedroAntunes178** [comment]
Thanks for the quick reply and the solution.
It works on NixOS.

For future reference if someone stumbles into this issue:
- In configuration.nix I had to add `nix.settings.sandbox = "relaxed";`. This was explained in [the first link](https://zimbatm.com/notes/nix-packaging-the-heretic-way) @NickCao provided. However, there it is not explicit how to alter the sandbox value in the nix.conf. You can not alter nix.conf directly, since it is manged by the NixOS configuration file.
- To build the package, you have to enter the riscv-gnu-toolchain directory and execute `nix-shell -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'` I did not find another way, but there probably is.

I would like to be able to import the package in configuration.nix and in a shell.nix (which imports all software needed to develop a project). I read that it can be done by cloning the nixpkgs repository, adding your package to your clone and passing your clone directory to the package's statement in the *nix. 
Is there a better way to do it?
For example, could I just pass an `import /path/to/package`?

Also, is the git issue a Nix problem or a repository compatibility problem?

Please correct me if I made a wrong statement, and once again thank you for your help.
I think this issue could be closed.

**Comment by NickCao** [comment]
You may reference it in your configurations as `pkgs.callPackage ./riscv-gnu-toolchain.nix { }`. The git issue should be a nixpkgs problem, namely `nix-prefetch-git` might be doing something wrong.

**Comment by PedroAntunes178** [comment]
>  The git issue should be a nixpkgs problem, namely `nix-prefetch-git` might be doing something wrong.

Should I open another issue referencing to this one?

**Comment by NickCao** [comment]
I double checked the output of `fetchFromGitHub`, it is producing the right files, something must have happened in the unpackPhase or patchPhase.

**Comment by NickCao** [comment]
Ah, It's simply that all files are untracked, I wonder if this even counts as an issue.
