### ISSUE TITLE
[Package Request] Pulsar

### ISSUE THREAD

**Issue by TenTypekMatus** [NixOS/nixpkgs#205152]
**Project description**
Fork of Atom, which was killed recently.

**Metadata**

* homepage URL: https://pulsar-edit.dev
* source URL: https://github.com/pulsar-edit/pulsar
* license: MIT
* platforms: Unix, Linux, Darwin

**Comment by davidak** [comment]
It was added in this PR (https://github.com/NixOS/nixpkgs/pull/221862) 5 days ago and is available in unstable channel.
