### ISSUE TITLE
[vim-plugin request] vim-zettel

### ISSUE THREAD

**Issue by heitorPB** [NixOS/nixpkgs#205167]
**Project description**

The plugin vim-zettel extends the [vimwiki](https://github.com/vimwiki/vimwiki/) plugin.

**Metadata**

* homepage URL: https://github.com/michal-h21/vim-zettel/
* source URL: https://github.com/michal-h21/vim-zettel/
* license: mit
* platforms: plugin for vim/neovim

I'd like to work on getting this plugin into nixpkgs, but I am getting a ton of `urllib.error.HTTPError: HTTP Error 429: too many requests` when I run the `update.py` script to add this plugin. Is this normal?

Could someone mentor me on this task?

**Comment by heitorPB** [comment]
Ah, found the way to solve the rate limiting issue with the Github Token...

**Comment by teto** [comment]
without the token, you have to use `--proc 1` to slow down the script :(

**Comment by heitorPB** [comment]
Working on this on #205178.
