### ISSUE TITLE
`prusa-slicer` fails to build

### ISSUE THREAD

**Issue by SeungheonOh** [NixOS/nixpkgs#205215]
### Steps To Reproduce
`nix run nixpkgs#prusa-slicer` on `nixpkgs-unstable`

It builds in `nix-shell`. I'm not sure why.

### Build log
https://gist.github.com/SeungheonOh/e1087bdd3551ceaa57495786c07e7f83

### Notify maintainers
@Moredread

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 23.05 (Stoat), 23.05.20221208.52665b0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wegank** [comment]
See https://github.com/NixOS/nixpkgs/pull/201678#issuecomment-1339879649.

**Comment by SeungheonOh** [comment]
When will it get merged into the `nixpkgs-unstable`?

**Comment by wegank** [comment]
In my experience (#200567), within two or three weeks.

**Comment by SeungheonOh** [comment]
Awesome. Thank you!

**Comment by SeungheonOh** [comment]
It's been solved in: https://github.com/NixOS/nixpkgs/commit/cfe4a8d8702a18389e95c81d89c15adf87bc1b40
