### ISSUE TITLE
protontricks: 1.7.0 -> 1.10.0

### ISSUE THREAD

**Issue by Qbxs** [NixOS/nixpkgs#205292]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 1.7.0
desired version: 1.10.0

###### Notify maintainers

maintainers: @kira-bruneau 

###### Note for maintainers

[1.10.0 release](https://github.com/Matoking/protontricks/releases/tag/1.10.0)

Please tag this issue in your PR.

**Comment by kira-bruneau** [comment]
Updated in #211976!
