### ISSUE TITLE
nix-prefetch-git --leave-dotGit not deterministic?

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixpkgs#20521]
Occasionally I notice that the resulting sha256 hash of:

```
nix-prefetch-git --leave-dotGit https://github.com/NixOS/nixpkgs.git c859ea0821644f4edc64ec4abe6bc2c36fa5b1eb
```

is different across invocations. Could this be explained by `nix-prefetch-git` not properly making the `.git` directory deterministic which happens [here](  https://github.com/NixOS/nixpkgs/blob/release-16.09/pkgs/build-support/fetchgit/nix-prefetch-git#L237)?

**Comment by copumpkin** [comment]
Yeah, definitely. See https://github.com/NixOS/nixpkgs/issues/8567

**Comment by basvandijk** [comment]
I see. Thanks for pointing me to that issue. Closing this one as a duplicate.
