### ISSUE TITLE
"/nix/store/i0ziry58d9sfa7x5sv7i7ky8qkqimvya-systemd-252.1.drv" failed to build

### ISSUE THREAD

**Issue by harryprayiv** [NixOS/nixpkgs#205352]
### Steps To Reproduce
1.   nix build .#homeConfigurations.bismuth-edp.activationPackage --show-trace
2.   activateHM

### Build log
```
error: builder for '/nix/store/i0ziry58d9sfa7x5sv7i7ky8qkqimvya-systemd-252.1.drv' failed with exit code 1;
       last 10 log lines:
       > applying patch /nix/store/6cpcq20riypmwr79vwj1rxsg3rjv69hm-0016-pkg-config-derive-prefix-from-prefix.patch
       > patching file src/core/systemd.pc.in
       > applying patch /nix/store/svhjykyn1vr61g611gb4g51fx1xyp3i2-0017-inherit-systemd-environment-when-calling-generators.patch
       > patching file src/core/manager.c
       > applying patch /nix/store/2kyl5mm7m2d24rgdi5vfp611ycv1h1w7-0018-core-don-t-taint-on-unmerged-usr.patch
       > patching file src/core/manager.c
       > applying patch /nix/store/mfnlm8xvf12c11fnpn6gkk5ikqik3fcw-systemd.patch
       > patching file src/libsystemd/sd-device/device-monitor.c
       > Hunk #1 FAILED at 445.
       > 1 out of 1 hunk FAILED -- saving rejects to file src/libsystemd/sd-device/device-monitor.c.rej
       For full logs, run 'nix log /nix/store/i0ziry58d9sfa7x5sv7i7ky8qkqimvya-systemd-252.1.drv'.
error: 1 dependencies of derivation '/nix/store/ppj81b67wl3i66jrjp6slv5iiwslmxsi-ledger-live-desktop-2.50.0-usr-target.drv' failed to build
error: 1 dependencies of derivation '/nix/store/599dzyp8rg9mjczn7x11a8xmpz9m2hki-ledger-live-desktop-2.50.0-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cjs6azkzcdwplkjifw5bk9h7zy7ad4x1-ledger-live-desktop-2.50.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ykn56rncv12afd5frk1as1vfz8q72h05-ledger-live-desktop-2.50.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/349bm42lyh8k7gqs94qjajhzardlf4vq-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/wy5w41cgvr1sh20yi298nqg8s4vnbm1r-ledger-live-desktop-2.50.0-fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4wxzma64fkvnww40xly01l5b114w8sh2-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nmvnmb3c7q43xm4xpf9qj9vs5a135654-home-manager-generation.drv' failed to build
```

### Additional context
Here is that log: 
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/6jmdy5fvmxl8fwfm8q1mf1irxizv7awj-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/4awl8kgivyw267n96wl3gzsp0paq2zix-0001-Start-device-units-for-uninitialised-encrypted-devic.patch
patching file rules.d/99-systemd.rules.in
applying patch /nix/store/5yf3cdhksj1rs370aycxbr1pdwjll2a3-0002-Don-t-try-to-unmount-nix-or-nix-store.patch
patching file src/shared/fstab-util.c
patching file src/shutdown/umount.c
applying patch /nix/store/m8cr8cgqk2klwrvpg81dbj90jdxn2188-0003-Fix-NixOS-containers.patch
patching file src/nspawn/nspawn.c
applying patch /nix/store/hqwvzrqjwp14hw4f2v4dqly38hl6p9xr-0004-Look-for-fsck-in-the-right-place.patch
patching file src/fsck/fsck.c
applying patch /nix/store/2h6yp3512c4m072s03plg8315cbxak01-0005-Add-some-NixOS-specific-unit-directories.patch
patching file src/basic/path-lookup.c
patching file src/core/systemd.pc.in
applying patch /nix/store/z17adqibcz7k6vvqvscxf2abp2v7jw7l-0006-Get-rid-of-a-useless-message-in-user-sessions.patch
patching file src/core/manager.c
applying patch /nix/store/82135dsrrb84zxlddsil6y0g0n0j5c1c-0007-hostnamed-localed-timedated-disable-methods-that-cha.patch
patching file src/hostname/hostnamed.c
patching file src/locale/localed.c
patching file src/timedate/timedated.c
applying patch /nix/store/vqvbhvjcdrxn7dj6nw50z7vc9bxzq825-0008-Fix-hwdb-paths.patch
patching file src/libsystemd/sd-hwdb/hwdb-internal.h
applying patch /nix/store/3yp8b4jxw60x5065is0smx6wdc04acf4-0009-Change-usr-share-zoneinfo-to-etc-zoneinfo.patch
patching file man/localtime.xml
patching file src/basic/time-util.c
patching file src/firstboot/firstboot.c
patching file src/nspawn/nspawn.c
patching file src/timedate/timedated.c
applying patch /nix/store/gzr2ibgn9azwlxh7h4d9kwc5n3gw7z2l-0010-localectl-use-etc-X11-xkb-for-list-x11.patch
patching file src/locale/localectl.c
applying patch /nix/store/i22skjc35qznvvf8nsczk6p4d0g6kafd-0011-build-don-t-create-statedir-and-don-t-touch-prefixdi.patch
patching file meson.build
Hunk #1 succeeded at 4069 (offset 2 lines).
applying patch /nix/store/krabvdhsf0461lrw1yzmy8na8wmqrwc7-0012-add-rootprefix-to-lookup-dir-paths.patch
patching file src/basic/def.h
applying patch /nix/store/i8qy44l1l4qbcm2hvvzqm7bnkvf1fmp3-0013-systemd-shutdown-execute-scripts-in-etc-systemd-syst.patch
patching file src/shutdown/shutdown.c
applying patch /nix/store/61ksv4hsyi90fb9hm36qcs9qgg06ya9k-0014-systemd-sleep-execute-scripts-in-etc-systemd-system-.patch
patching file src/sleep/sleep.c
applying patch /nix/store/k8g0nxvldy3h1xjyz3mf8ywsgjkslqk6-0015-path-util.h-add-placeholder-for-DEFAULT_PATH_NORMAL.patch
patching file src/basic/path-util.h
applying patch /nix/store/6cpcq20riypmwr79vwj1rxsg3rjv69hm-0016-pkg-config-derive-prefix-from-prefix.patch
patching file src/core/systemd.pc.in
applying patch /nix/store/svhjykyn1vr61g611gb4g51fx1xyp3i2-0017-inherit-systemd-environment-when-calling-generators.patch
patching file src/core/manager.c
applying patch /nix/store/2kyl5mm7m2d24rgdi5vfp611ycv1h1w7-0018-core-don-t-taint-on-unmerged-usr.patch
patching file src/core/manager.c
applying patch /nix/store/mfnlm8xvf12c11fnpn6gkk5ikqik3fcw-systemd.patch
patching file src/libsystemd/sd-device/device-monitor.c
Hunk #1 FAILED at 445.
1 out of 1 hunk FAILED -- saving rejects to file src/libsystemd/sd-device/device-monitor.c.rej

### Metadata
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/m142rmlj114xwgwgf6k2gvvm33zxkbia-nix-info
copying path '/nix/store/m142rmlj114xwgwgf6k2gvvm33zxkbia-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11, NixOS, 23.05 (Stoat), 23.05.20221208.2787fc7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(onyx): `""`
 - channels(root): `"nixos"`
 - channels(bismuth): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11, NixOS, 23.05 (Stoat), 23.05.20221208.2787fc7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(onyx): `""`
 - channels(root): `"nixos"`
 - channels(bismuth): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

I apologize if I missed anything.  This is my first time submitting an Issue.

**Comment by harryprayiv** [comment]
At the moment, it looks to be an issue with the recent ledger-live-desktop commit by @edef1c since it is now building with that commented out of my home.nix file.  I'll update when the build is finished.

**Comment by Artturin** [comment]
fixed iin https://github.com/NixOS/nixpkgs/pull/205193

**Comment by harryprayiv** [comment]
The problem persists....

**Comment by Artturin** [comment]
it's not in nixos-unstable yet https://nixpk.gs/pr-tracker.html?pr=205193

**Comment by harryprayiv** [comment]
> it's not in nixos-unstable yet https://nixpk.gs/pr-tracker.html?pr=205193

aha!  Thanks.  Sorry for any newbish foolishness.
