### ISSUE TITLE
Franz will not start with grsec

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20539]
## Issue description
When trying to start `Franz`, it prints the following into the system log:

```
Nov 18 22:10:09 nixus kernel: grsec: denied RWX mmap of <anonymous mapping> by /nix/store/4lqxlyz6r9xj9az0iapm3zwvzai4g1la-franz-4.0.4/share/franz/Franz[Franz:3991] uid/euid:1000/1000 gid/egid:100/100, parent /nix/store/jq0zgpz3cwjk14n5k60zcmxdl4rq8w6b-zsh-5.2/bin/zsh[zsh:3988] uid/euid:1000/1000 gid/egid:100/100
```

There is no output whatsoever on the command line and the application does not return to the prompt either.

### Steps to reproduce
- Activate grsecurity NixOS module
- Use grsec_nixos kernel
- Install Franz
- Open Terminal
- Issue `Franz`

## Technical details

* System: 17.03.git.775a729 (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre95730.ba73dbb"

/cc @joachifm

**Comment by joachifm** [comment]
It most likely needs `paxmark m` on the relevant binary. Ideally, you'd patch or change the build to prevent it from triggering the PaX exception but that is often difficult.

**Comment by joachifm** [comment]
To elaborate, pretty much all programs that rely on executing code generated at runtime are at risk for triggering a PaX exception, unless carefully coded.
