### ISSUE TITLE
Freecad: cannot be called without required argument "gitpython"

### ISSUE THREAD

**Issue by MrTarantoga** [NixOS/nixpkgs#205301]
### Steps To Reproduce
sudo nixos-rebuild switch --upgrade 

### Build log
```
error: Function called without required argument "gitpython" at /nix/store/v8cyxca406hl8yf95d6qqc6zdcm2jdaq-nixos/nixos/pkgs/applications/graphics/freecad/default.nix:7, did you mean "GitPython"?
```

### Additional context
It seems to be commit 26d68b5350e4c5f6e283f153d43d19083a1df450 the problem. 

### Notify maintainers

@viric @gebner @AndersonTorres 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11, NixOS, 23.05 (Stoat), 23.05pre432338.6e51c97f1c8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos"`
 - channels(goetz): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lilyinstarlight** [comment]
This should already be fixed by #205058, which hit nixos-unstable ~6 hours ago (so not long after you opened the issue)

Can you try pulling/updating nixos-unstable again?
