### ISSUE TITLE
[Package request] unigine

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20547]
3D benchmarking on Linux using open-source tools is rather limited; this page lists a couple of proprietary packages which I would like to use:
https://unigine.com/en/products/benchmarks

**Comment by vcunat** [comment]
We do have one already:
```
nix-repl> unigine-valley.name
"unigine-valley-1.0-1"
```

**Comment by kierdavis** [comment]
If you want some of the other Unigine benchmarks (Heaven, Tropics, Sanctuary) packaged, I can give that a shot. I imagine the expressions for them should be almost identical to unigine-valley.

**Comment by kierdavis** [comment]
Can this be closed now?

**Comment by tomberek** [comment]
(triage) close
