### ISSUE TITLE
How to override a package for all of nixpkgs *except for* a small number of packages?

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20543]
## Issue description
I'm trying to switch to LibreSSL, and some packages aren't compatible with it yet. So, I'm trying to do the following:

```nix
 nixpkgs.config.packageOverrides =
  let 
    no_libressl_yet = ["nodejs" "cyrus_sasl"];
  in pkgs: rec {
    openssl = pkgs.libressl;
  } // ( lib.listToAttrs (map (pkgId: lib.nameValuePair pkgId
    (pkgs.${pkgId}.override { openssl = pkgs.openssl_1_1_0; })) no_libressl_yet));
```

However, that does not work. If I changed the last line to include mkForce (i.e. `openssl = mkForce pkgs.openssl_1_1_0;`) I get the following errors for the contents of the list: 

```bash  error: cannot coerce a set to a string,  at <location>```

## Technical details

* System: master
* Nix version: 1.11.4
* Nixpkgs version: master

**Comment by joachifm** [comment]
`mkForce` is for setting module option values, not passing expression parameters.

**Comment by vcunat** [comment]
I'd write this more easily as
```nix
let # fix higlighting
  packageOverrides = pkgs: rec {
    openssl = pkgs.libressl;
    inherit (pkgs) nodejs cyrus_sasl;
  };
```
but it doesn't work. I think it *should* work; I can't see where's the catch now.

**Comment by spacekitteh** [comment]
Hmm. This is really bugging me.

**Comment by vcunat** [comment]
I suppose you haven't found a cause/solution?

**Comment by spacekitteh** [comment]
I did, turns out to have been a problem with the specific version of openssl. :(

**Comment by vcunat** [comment]
I can't see how that's related to the overriding mechanism. Can you link more information?

**Comment by spacekitteh** [comment]
What I had in the OP worked. The problem is, they weren't compatible with the version of OpenSSL I was passing, and I missed it in the error logs.
