### ISSUE TITLE
[Package request] tsung with all features

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20546]
See: http://tsung.erlang-projects.org/

Dependencies include gnuplot, perlPackages.TemplateToolkit, erlang, etc.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR. I'm closing this issue now as its basically noise on this issue tracker, but feel free to discuss or list other details regarding this package here.
