### ISSUE TITLE
remove: gradle_5

### ISSUE THREAD

**Issue by lorenzleutgeb** [NixOS/nixpkgs#205455]
The last release of Gradle with major version number 5 was on 2019-11-01, and there seems to be just two dependent packages:

 * [`jd-gui`](https://github.com/NixOS/nixpkgs/blob/f8fc2323e9ba9d25aebef0a15cec5ca5cabdc495/pkgs/tools/security/jd-gui/default.nix) (I'd have to check whether this builds with Gradle 7.)
 * [`javaPackages.openjfx15`](https://github.com/NixOS/nixpkgs/blob/f8fc2323e9ba9d25aebef0a15cec5ca5cabdc495/pkgs/development/compilers/openjdk/openjfx/15.nix) (I am fairly certain that could be built with Gradle 7. This version is EOL.)
 
 Let's remove Gradle 5.

/cc @tjni @liff @thiagokokada

**Comment by thiagokokada** [comment]
I think we can build `openjfx15` with `gradle6` at least. I will try to bump it in #205169.

**Comment by thiagokokada** [comment]
Done: https://github.com/NixOS/nixpkgs/pull/205169/commits/97691ff9f987ec505fba96ec925bfd30546a09e7

**Comment by thiagokokada** [comment]
Merged https://github.com/NixOS/nixpkgs/pull/205841, this should be good to go.

Remember that #205169 is only on `staging` right now, so if you want to do it before the changes get to `master` you will need to target `staging.

**Comment by lorenzleutgeb** [comment]
Thanks. Waiting for #205169 to reach `master`, then I will PR removal of Gradle 5.
