### ISSUE TITLE
discord text-to-speech missing

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#205494]
### Describe the bug
Text-to-speech functionality is not working, according to the [ArchWiki](https://wiki.archlinux.org/title/Discord#Enabling_Text-to-Speech) this functionality is disabled by default on Linux. I have tried doing what was suggested over there but it didn't work, I assume this has to do with how it is packaged over in Nix. 

What I tried was entering `nix-shell -p speechd` and then running `speech-dispatcher`. Doing `spd-say test` worked which confirmed that the dispatcher was working, however, starting discord via terminal with the flag `discord --enable-speech-dispatcher` did not fix it for discord.

### Notify maintainers
@MP2E @devins2518 @Artturin  @Infinidoge  

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.466.596a8e828c5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(mathiassven): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by MatthewCroughan** [comment]
The same is true of the `godot_4` package which also includes speechd but will not be guaranteed to work, depending on environment (such as the display server you use)
