### ISSUE TITLE
No such file or directory for dependency

### ISSUE THREAD

**Issue by NeQuissimus** [NixOS/nixpkgs#20555]
## Issue description
I am trying to install `nodejs` (but I suspect it has nothing to do with the specific package, it worked a couple of days ago).
I had it installed earlier this week, then `nix-env -e nodejs` it.

It complains like so:

```
$ nix-env -i nodejs
installing ‘nodejs-7.1.0’
error: opening file ‘/nix/store/aycnxxa2x81y4wjvlq4q08jmk11szrj4-python2.7-gyp-2015-06-11.drv’: No such file or directory
```

Should it not fetch gyp if it is not available? Did something corrupt?

### Steps to reproduce
- `nix-env -i nodejs`

## Technical details

* System: 17.03pre95909.b69f568 (Gorilla)
* Nix version: nix-env (Nix) 1.11..4
* Nixpkgs version: "17.03pre95909.b69f568"

**Comment by vcunat** [comment]
*.drv files aren't fetched; they should be created during evaluation.

**Comment by vcunat** [comment]
I can't reproduce it, same nixpkgs and `nix-env` versions.

**Comment by NeQuissimus** [comment]
Yeah, I wonder if something got corrupted somewhere... How would I reset this? Or tell `nix-env` to start over? I don't really want to go into `/nix/store` and start removing things by hand :)

**Comment by vcunat** [comment]
Maybe running garbage collection will fix it.

**Comment by NeQuissimus** [comment]
`nix-collect-garbage -d` did not help...

**Comment by NeQuissimus** [comment]
This has gotten a lot more interesting just now:

```
$ nix-env -i irssi
error: opening file ‘/nix/store/pb1fc39m1wkgcqric34hg048gnmzar5j-nix-prefetch-git.drv’: No such file or directory
```

**Comment by NeQuissimus** [comment]
Installing as root works...

**Comment by vcunat** [comment]
Something wrong around nix daemon, most likely.

**Comment by NeQuissimus** [comment]
FYI: This seems to be the magic command

```
nix-store --verify --check-contents --repair
```

It is still running (a LOT of stuff seems to be corrupt for me oO) but it is finding issues, so I am letting it run... If this fixes the problem, I will close the issue.
