### ISSUE TITLE
Yadm build fails

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#205510]
### Describe the bug
Trying to build yadm fails with:
```
error: pyyaml-6.0 not supported for interpreter python2.7
```
Probably related to: https://github.com/NixOS/nixpkgs/pull/204023

### Steps To Reproduce
`nix build nixpkgs#yadm
`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `0`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 23.05 (Stoat), 23.05.20221130.e76c78d`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `""`
 - channels(quantmint): `""`
```

**Comment by ncfavier** [comment]
Can you try again on master? Should be fixed by the linked PR

**Comment by dotlambda** [comment]
fixed by https://github.com/NixOS/nixpkgs/pull/205387
