### ISSUE TITLE
Haskell packages pipes binary won't build

### ISSUE THREAD

**Issue by Chattered** [NixOS/nixpkgs#20553]
## Issue description

The tests for the pipes-binary haskell library depend on an old version of binary (<0.8). Potential fix is to disable the tests:

[#20545](https://github.com/NixOS/nixpkgs/pull/20545/commits/3adc6516f862d6fed3d47688dcc5aaf7c19fc1f1)

### Steps to reproduce

nix-shell -p haskellPackages.pipes-binary

## Technical details

* System: NixOS 17.03pre95306.a24728f (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: 17.03pre95406.a24728f

**Comment by Profpatsch** [comment]
Seems to be fixed in current nixpkgs.
