### ISSUE TITLE
services.elasticsearch.listenAddress does not work with special values like '_eth0_'

### ISSUE THREAD

**Issue by fadenb** [NixOS/nixpkgs#20560]
## Issue description
The postStart script of elasticsearch fails when a special values like `_local_` or `_eth0:ipv4_` ( https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-network.html#network-interface-values ) is used for services.elasticsearch.listenAddress as the script expects an IP or a hostname.

Using an ip as listenAddress ist not always a viable option especially when generating NixOS images upfront for a dynamic deployment (e.g. on Azure or EC2)

I am not sure how to address this issue. Perhaps one shall check netstat output to find out which ip was bound to?

### Steps to reproduce
```
services = {
  elasticsearch = {
    enable = true;
    listenAddress = "_local_";
  };
};
```

/cc @offlinehacker

**Comment by offlinehacker** [comment]
Yes i agree, we should implement another option for es url, I'm fine even with removing postStart. You can create pull request if you need fix asoap, I will put it on to-do.
