### ISSUE TITLE
"ultrastardx" fails to build

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#20568]
## Issue description
The "ultrastardx" derivation fails to build with
```
/tmp/nix-build-ultrastardx-1.1.drv-0/ultrastardx-1.1-src/src/lib/ffmpeg/avutil.pas(115,4) Error: User defined: Linked version of libavutil is not yet supported!
```

I noticed this when building another derivation's reverse dependencies. (portaudio)

### Steps to reproduce
```
nix-build '<nixpkgs>' -A ultrastardx
```

## Technical details

Fails on NixOS and Gentoo hosting Nix.

```
nix-env (Nix) 1.11.4
nixpkgs "17.03pre95922.13491f9"
```

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by joachifm** [comment]
@viric added the package initially, they might know more

**Comment by yegortimoshenko** [comment]
Not anymore:

```
$ nix-build ~/Projects/nixpkgs/ -A ultrastardx
/nix/store/528r4l1nhgfrij4a2q2knyiwmgznmz2h-ultrastardx-2017.8.0
```
