### ISSUE TITLE
dolibarr: assertion error when not using nginx

### ISSUE THREAD

**Issue by GaetanLepage** [NixOS/nixpkgs#205760]
### Describe the bug
I would like to use the dolibarr module without nginx. I plan to use caddy instead.
In my NixOS configuration, I have `services.nginx.enable = false;`.

All the nginx-related settings in the dolibarr module are ignored if `cfg.nginx != null` which is good.
However, this line is not: https://github.com/NixOS/nixpkgs/blob/64e0bf055f9d25928c31fb12924e59ff8ce71e60/nixos/modules/services/web-apps/dolibarr.nix#L318

I get the following output:
```
error:
       Failed assertions:
       - Exactly one of users.users.nginx.isSystemUser and users.users.nginx.isNormalUser must be set.

       - users.users.nginx.group is unset. This used to default to
       nogroup, but this is unsafe. For example you can create a group
       for this user with:
       users.users.nginx.group = "nginx";
       users.groups.nginx = {};
(use '--show-trace' to show detailed location information)
```

This happens with simply adding `services.dolibarr.enable = true;` to my config.

### Notify maintainers
@RaitoBezarius 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 23.05 (Stoat), 23.05.20221209.2dea0f4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(gaetan): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by RaitoBezarius** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/205765 for the fix, as I do not use any other web server beyond NGINX, I have no plan to maintain advanced integrations of other web servers, if you are interested into this, I will need another co-maintainer :).
