### ISSUE TITLE
python310Packages.autopep8: Build fails

### ISSUE THREAD

**Issue by GaetanLepage** [NixOS/nixpkgs#205733]
### Steps To Reproduce
1. build `python310Packages.autopep8`

Python tests are failing

### Build log
https://gist.github.com/GaetanLepage/5d7650a187bc80fa6364e4f396d53fee

### Notify maintainers

@bjornfor 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 23.05 (Stoat), 23.05.20221209.2dea0f4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(gaetan): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by bjornfor** [comment]
Bisected to the first bad commit: 3a2e1fcdd319f5bb4dce8b69abafc1fd0635079d
