### ISSUE TITLE
vimPlugins.magma-nvim

### ISSUE THREAD

**Issue by Dioprz** [NixOS/nixpkgs#205797]
**Project description**

Interact with Jupyter from NeoVim.

**Metadata**

* homepage URL: https://github.com/dccsillag/magma-nvim
* source URL: https://github.com/dccsillag/magma-nvim
* license: GPL v3
* platforms: Unix, Linux, Darwin

**Comment by jfvillablanca** [comment]
A fork to magma-nvim is currently packaged in unstable. 
[vimPlugins.magma-nvim-goose](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=magma-nvim)

Do we need to package the upstream? I could make a PR

**Comment by Wisehh** [comment]
I don't really need the plugin anymore, but checking the repositories, I think the upstream still has more activity (not in commits, but in issues and PR), so if you could do the PR and it doesn't take you too much time, I think it could be helpful for someone else!
