### ISSUE TITLE
snipe-it package not working in NixOS 22.11

### ISSUE THREAD

**Issue by Dehumanizer77** [NixOS/nixpkgs#205791]
### Describe the bug
The package snipe-it builds correctly in NixOS 22.11, but it doesn't work, most probably because Snipe-IT v6.0.13 lists PHP >= 7.4 < v8.1.2, but 22.11 does have PHP 8.1.3 as default.

### Steps To Reproduce
1. enable snipe-it module by services.snipe-it.enable = true;
2. the snipe-it-setup service fails with an error

### Expected behavior
snipe-it-setup service finishes successfully

### Additional context
The maintainer of the package (Yaya) is currently on a sick leave and cannot investigate on the issue at the moment, but has acknowledged the problem. It would be nice if someone else could take a look at the problem.

### Notify maintainers
@yayayayaka

**Comment by yayayayaka** [comment]
Heya, I am back again.

Unfortunately, I couldn't reproduce the reported behaviour with the latest `release-22.11` branch. I tried the following to reproduce the behaviour:
- Install NixOS 22.05
  ```console
  [user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
   - system: `"x86_64-linux"`
   - host os: `Linux 6.0.11, NixOS, 22.05 (Quokka), 22.05pre-git`
   - multi-user?: `yes`
   - sandbox: `yes`
   - version: `nix-env (Nix) 2.8.1`
   - nixpkgs: `/etc/src/nixpkgs`
  ```
- Configure Snipe-IT with the following config:
  ```nix
  { ... }:

  {
    services.snipe-it = {
      enable = true;
      appKeyFile = /path/to/dummy-secret;
      hostName = "debugsnipeit.example.invalid";
      database.createLocally = true;
      mail = {
        # ...
      };
      nginx = {
        enableACME = true;
        forceSSL = true;
      };
    };

    networking.firewall.allowedTCPPorts = [ 80 443 ];
  }
  ```
- Visit debugsnipeit.example.invalid, run the setup wizard, creating an admin user
  ![2022-12-19T15:25:32+01:00](https://user-images.githubusercontent.com/73759599/208448247-10ee8a18-269c-406f-ab2b-30cc07898149.png)
- Upgrade to NixOS 22.11 and reboot
  ```console
  [user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
   - system: `"x86_64-linux"`
   - host os: `Linux 6.1.0, NixOS, 22.11 (Raccoon), 22.11pre-git`
   - multi-user?: `yes`
   - sandbox: `yes`
   - version: `nix-env (Nix) 2.11.1`
   - nixpkgs: `/etc/src/nixpkgs`
  ```
  ![2022-12-19T15:07:35+01:00](https://user-images.githubusercontent.com/73759599/208448470-28a3f788-3c16-44f6-b573-34e063a266bd.png)

**Comment by yayayayaka** [comment]
Okay, I take everything back. Now `snipe-it-setup.service` just broke on my test instance.

**Comment by yayayayaka** [comment]
This kinda explains why the setup script worked once but not twice.

**Comment by Dehumanizer77** [comment]
Thank you, I'll test it first thing after the New Yar

**Comment by Dehumanizer77** [comment]
I confirm that it's working now, thanks!
