### ISSUE TITLE
python310Packages.jpylyzer fails to build on zfs

### ISSUE THREAD

**Issue by mpasternacki** [NixOS/nixpkgs#205780]
### Steps To Reproduce
1. Make sure `/nix` is on ZFS
2. Run `nix build --rebuild github:NixOS/nixpkgs/nixpkgs-unstable\#python310Packages.jpylyzer` (`--rebuild` might not be necessary, I built a patched package already)

### Build log
```
error: creating file '/nix/store/k0ll2isnlwfpaylid97k15c3940gsjdk-source/�񠊾𜰸􉵢󦲀.jp2': Invalid or incomplete multibyte or wide character
error: some substitutes for the outputs of derivation '/nix/store/3zy4yv3ym1jhfrivxhq78azw738l1qkr-source.drv' failed (usually happens due to networking issues); try '--fallback' to build derivation from source
error: 1 dependencies of derivation '/nix/store/vwvi0p7xbvmfqm7lfd2nzghr74qbhcjw-python3.10-jpylyzer-2.1.0.drv' failed to build
```

### Additional context

The path that fails to unpack is this package's test files. A comment in https://github.com/NixOS/nixpkgs/pull/201019/files says "don't depend on testFiles on darwin as it may not be extractable due to weird filenames" and disables `testFiles` on darwin. Disabling test files in an overlay makes it build:

```
      python310 = prev.python310.override {
        packageOverrides = pyself: pysuper: {
          jpylyzer = pysuper.jpylyzer.overrideAttrs (_:{
            preCheck = null;
            disabledTestPaths = ["tests/unit/test_testfiles.py"];
          });
        };
      };
```

### Notify maintainers
@risicle 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11, NixOS, 23.05 (Stoat), 23.05.20221209.6bc6f77`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `""`
 - channels(japhy): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by risicle** [comment]
Damnit ZFS.

**Comment by risicle** [comment]
Welp, see the above PR if you still think a change would be best.

**Comment by Shawn8901** [comment]
Sorry, i am currently a bit sick :mask:.
Nevertheless, as i got another machine with zfs and `normalization=formD` for nix stores dataset i was able to verify that the PR builds fine.
Sadly i am not sure that to test beside that.
