### ISSUE TITLE
wire-desktop blocks UI with login screen

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#205707]
### Describe the bug
wire-desktop will show the login screen after a few seconds on startup, even after clearing `~/.config/Wire` and logging into a new session.

### Steps To Reproduce
1. Launch Wire
2. If not already logged into an account, log in
3. Wait a few seconds
4. The UI will redirect to the login screen with no way to return to the normal UI for your logged-in account

### Expected behavior
To be able to navigate the account UI without interruption.

### Screenshots
![image](https://user-images.githubusercontent.com/2313201/206950415-507ede49-20c4-41c1-b092-b856d26872ad.png)

### Notify maintainers
@arianvp @Kiwi @toonn 

### Metadata
```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12, NixOS, 22.11 (Raccoon), 22.11.20221210.9c5e57f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by toonn** [comment]
@flokli has experienced this same problem. This [outstanding version bump](https://github.com/NixOS/nixpkgs/pull/200189) didn't seem to resolve the problem either.

The macOS version has kept working over all the bumps. Maybe the wire-desktop deb has accrued a new dependency that we're not providing?

**Comment by aidalgol** [comment]
I tried again with the `--devtools` flag to see the browser console, and there wasn't anything helpful in there.
```console
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=415cc9e7-49f3-4c92-b8d6-327568b6a77c" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=415cc9e7-49f3-4c92-b8d6-327568b6a77c" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=415cc9e7-49f3-4c92-b8d6-327568b6a77c" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=415cc9e7-49f3-4c92-b8d6-327568b6a77c" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
Navigated to file:///nix/store/lwg5xv7hq3ilray8cv5x6g3f2p0lkjz1-wire-desktop-3.29.2997/opt/Wire/resources/app.asar/electron/renderer/index.html?env=https%253A%252F%252Fapp.wire.com%252F%253Fhl%253Den&focus=true
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=415cc9e7-49f3-4c92-b8d6-327568b6a77c" ...
Navigated to file:///nix/store/lwg5xv7hq3ilray8cv5x6g3f2p0lkjz1-wire-desktop-3.29.2997/opt/Wire/resources/app.asar/electron/renderer/index.html?env=https%253A%252F%252Fapp.wire.com%252F%253Fhl%253Den&focus=true
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=3b10bd51-97b9-41a6-a31a-cd42a3ea4d35" ...
bundle.js:2 Loading WebApp URL "https://app.wire.com/?hl=en&id=415cc9e7-49f3-4c92-b8d6-327568b6a77c" ...
```

**Comment by tlebon** [comment]
theres multiple dev tools levels in the wire app. can you try 
`Wire --devtools=1 --enable-logging`
this should get more substantive logs

**Comment by aidalgol** [comment]
That's more like it!
[wire-desktop.log](https://github.com/NixOS/nixpkgs/files/10211899/wire-desktop.log)

**Comment by flokli** [comment]
I ran the same log line, and in my case, didn't see that multiple tabs error message. Seems to be an unrelated red herring.

But I could see the "GPU process crashed. Will reload the window" in both mine and your logs.

**Comment by aidalgol** [comment]
It's probably a long shot, but could this possibly be related to electron/electron#32317?

**Comment by flokli** [comment]
@aidalgol why do you think it's related? The issue complains about silent fallback to software rendering, but no crash.

In the `GPUFeatureStatus`, I see most of the rendering to be disabled / software rendering too:

```
ℹ️  @wireapp/desktop/main [2022-12-22 15:23:52] GPUFeatureStatus: {
  '2d_canvas': 'disabled_software',
  canvas_oop_rasterization: 'disabled_off',
  direct_rendering_display_compositor: 'disabled_off_ok',
  gpu_compositing: 'disabled_software',
  multiple_raster_threads: 'enabled_on',
  opengl: 'disabled_off',
  rasterization: 'disabled_software',
  raw_draw: 'disabled_off_ok',
  video_decode: 'disabled_software',
  video_encode: 'disabled_software',
  vulkan: 'disabled_off',
  webgl: 'disabled_off',
  webgl2: 'disabled_off',
  webgpu: 'disabled_off'
}
⚠️  @wireapp/desktop/main [2022-12-22 15:23:52] 2D canvas unavailable, disabling hardware acceleration
```

…but even slow software rendering doesn't seem to work.

**Comment by akshaymankar** [comment]
I also ran into this issue after upgrading nixos (unstable). I even tried the latest version `3.30.3016`.

**Comment by flokli** [comment]
> I also ran into this issue after upgrading nixos (unstable). I even tried the latest version `3.30.3016`.

Same issue with 3.30.3016. What GPU do you use?

**Comment by akshaymankar** [comment]
> What GPU do you use?
Its the AMD GPU integrated into Ryzen 7 4800H.

In case someone really wants to get around this: I could get wire-desktop running by deleting these lines: https://github.com/wireapp/wire-desktop/blob/3bb7456e7c194287b853eaee8d23552cfb938ac0/electron/src/main.ts#L343-L352

**Comment by flokli** [comment]
The docs of the deprecated `gpu-process-crashed` mention "it isn't always because it's crashed":

> Deprecated: This event is superceded by the child-process-gone event which contains more information about why the child process disappeared. It isn't always because it crashed. The killed boolean can be replaced by checking reason === 'killed' when you switch to that event.

I sent a PR at https://github.com/wireapp/wire-desktop/pull/6267, which uses the recommended event handler, removed the `main.reload()` call, and added more logging of the event details.

**Comment by flokli** [comment]
Yup, the suspicion was right :-)

With the above PR applied, `wire-desktop` logs the following event details:

```
❌  @wireapp/desktop/main [2022-12-23 10:37:57] {
  type: 'Utility',
  reason: 'crashed',
  exitCode: 139,
  serviceName: 'audio.mojom.AudioService',
  name: 'Audio Service'
}
```

… which clearly isn't a gpu rendering crash, at least nothing where reloading the GUI would help much.

It also seems to recover.

A .deb including the fix (draft release) can be found at https://github.com/wireapp/wire-desktop/releases/tag/untagged-96578680e212bbabe724.

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/pull/200189 has been updated to include the fixed version.

@akshaymankar , @aidalgol can you take a look?
