### ISSUE TITLE
mariadb uses incorrect relative path in mysql_install_db

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nixpkgs#20585]
The `mysql_install_db` script provided by mariadb incorrectly falls back to 
```
print_defaults="./bin/my_print_defaults"
```
which prevents finding the `my_print_defaults` script. It should use an absolute path instead.

Attn: @thoughtpolice @wkennington

**Comment by Profpatsch** [comment]
(triage) still a problem?

**Comment by luzpaz** [comment]
@ttuegel is this still relevant to https://github.com/NixOS/nixpkgs/pull/44343 ?
