### ISSUE TITLE
qtwebengine can crash with nouveau graphics card

### ISSUE THREAD

**Issue by vandenoever** [NixOS/nixpkgs#20580]
## Issue description

QtWebEngine has an issue with Nouveau graphics cards. This patch disables OpenGL for such cards.

https://build.opensuse.org/package/view_file/KDE:Qt5/libqt5-qtwebengine/disable-gpu-when-using-nouveau-boo-1005323.diff?expand=1

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by vandenoever** [comment]
I do not have a need for nouveau driver, but suse still ships that patch.

**Comment by siraben** [comment]
Any updates?

**Comment by ttuegel** [comment]
I don't have time to take care of this right now, but it would be a good bug for a beginner. We can add the patch to [this list](https://github.com/NixOS/nixpkgs/blob/ca6fafaf236ce1a827c0c3e9ef3d4dfe8428616c/pkgs/development/libraries/qt-5/5.15/default.nix#L86) with `fetchpatch`. There are also patch lists for Qt 5.12 and Qt 5.14; I suppose it should be added there, too.

**Comment by Artturin** [comment]
I wonder why only opensuse carries this patch

Is anyone on nixos affected by this?
