### ISSUE TITLE
Changes to the git package trigger to many rebuilds

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#205804]
## Issue description

See i.e. https://github.com/NixOS/nixpkgs/pull/205682; 5000+ on Linux and Darwin.

Why?

@SuperSandro2000 pointed out one reason which is that nearly all rust packages depend on git via `buildRustPackage`: https://github.com/NixOS/nixpkgs/blob/d2578f1dacedb207649a590459f91bf66158637a/pkgs/build-support/rust/build-rust-package/default.nix#L118-L126

**Comment by Atemu** [comment]
It was initially added by @madjar in https://github.com/NixOS/nixpkgs/commit/7d67efa3f23f7d5c494c90b79a63756a3917be6e but AFAICT it's not actually used? The fetcher obviously uses it but I don't see why the derivation needs it.

I was able to build `fd` and `ripgrep` without git in nativeBuildInputs.

**Comment by SuperSandro2000** [comment]
Should become a lot better with #207804

**Comment by Atemu** [comment]
Great to have that in. We'll see the effect on the next git bump I hope.
