### ISSUE TITLE
crypthography cross build produces host's rust library

### ISSUE THREAD

**Issue by Cynerd** [NixOS/nixpkgs#205807]
### Describe the bug
By attempting to cross-compile python cryptography I get build but rust bindings are build for host architecture.

### Steps To Reproduce
1. `nix build .#legacyPackages.x86_64-linux.pkgsCross.aarch64-multiplatform.python3Packages.cryptography`
2. `file result/lib/python3.10/site-packages/cryptography/hazmat/bindings/_rust.abi3.so` gives `x86-64`
3. `file result/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so` gives `aarch64`

### Expected behavior
The rust should be cross compiled as well.

### Additional context

I tried to look into it and discovered this https://github.com/PyO3/setuptools-rust/issues/294 but nothing more. 

### Notify maintainers
@SuperSandro2000 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10, NixOS, 23.05 (Stoat), 23.05.20221209.9e4a15b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
FYI @Artturin didn't you work on python cross or am I mistaken your for someone else?

**Comment by Cynerd** [comment]
This seems to be something generic for all python packages with rust extension. I also tried other packages that use `setultools-rust`, and all I tried were built for the host platform, not for the target.

Probably somebody skilled with Cargo should look into it.

**Comment by Cynerd** [comment]
I might have gotten a little bit further...
```diff
diff --git a/pkgs/development/python-modules/cryptography/default.nix b/pkgs/development/python-modules/cryptography/default.nix
index d5e4af33f60..560b8861fdc 100644
--- a/pkgs/development/python-modules/cryptography/default.nix
+++ b/pkgs/development/python-modules/cryptography/default.nix
@@ -2,8 +2,12 @@
 , stdenv
 , callPackage
 , buildPythonPackage
+, python
 , fetchPypi
 , rustPlatform
+, rust
+, rustc
+, cargo
 , setuptools-rust
 , openssl
 , Security
@@ -47,9 +51,11 @@ buildPythonPackage rec {
   nativeBuildInputs = lib.optionals (!isPyPy) [
     cffi
   ] ++ [
-    rustPlatform.cargoSetupHook
     setuptools-rust
-  ] ++ (with rustPlatform; [ rust.cargo rust.rustc ]);
+    rustPlatform.cargoSetupHook
+    rustc
+    cargo
+  ];
 
   buildInputs = [ openssl ]
     ++ lib.optionals stdenv.isDarwin [ Security libiconv ];
@@ -69,6 +75,9 @@ buildPythonPackage rec {
     pytz
   ];
 
+  CARGO_BUILD_TARGET = "${rust.toRustTargetSpec stdenv.hostPlatform}";
+  PYO3_CROSS_LIB_DIR = "${python}/lib/${python.libPrefix}";
+
   pytestFlagsArray = [
     "--disable-pytest-warnings"
   ];
```
But still, it fails to build when cross-compiling. For some reason, it can't find linker.

**Comment by Cynerd** [comment]
It seems that I might have crack it. The pull request is here https://github.com/NixOS/nixpkgs/pull/208401.
