### ISSUE TITLE
"octaveFull" fails to build

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#20589]
## Issue description
The `octaveFull` package fails to build with:

```
/nix/store/9kxhc2f3j5lcyh00zcrifvfly33n5m4r-binutils-2.27/bin/ld: cannot find -ltiff
/nix/store/9kxhc2f3j5lcyh00zcrifvfly33n5m4r-binutils-2.27/bin/ld: cannot find -llzma
/nix/store/9kxhc2f3j5lcyh00zcrifvfly33n5m4r-binutils-2.27/bin/ld: cannot find -ljpeg
```

Seems like some libraries are simply missing. Found while building portaudio's reverse dependencies.

### Steps to reproduce
```
nix-build '<nixpkgs>' -A octaveFull
```

## Technical details

Fails on NixOS and Gentoo hosting Nix.

```
nix-env (Nix) 1.11.4
nixpkgs "17.03pre95922.13491f9"
```

**Comment by knedlsepp** [comment]
First failing build: https://hydra.nixos.org/build/43282962
Did maybe https://github.com/NixOS/nixpkgs/pull/20227 break it?

**Comment by armijnhemel** [comment]
Doesn't this package just build fine now?

https://hydra.nixos.org/build/51591799

**Comment by vcunat** [comment]
Yes, apparently it builds on unstable, 17.03 and 16.09.
