### ISSUE TITLE
No title bars in KDE

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#205880]
### Describe the bug

After logging in, windows have no titlebar in Plasma (X11). Setting the theme in the settings restores title bars, but they disappear again after logout/login.

### Steps To Reproduce
1. Run Plasma (X11)

### Expected behavior
Title bars should not disappear.

### Screenshots
![Screenshot_20221213_090134](https://user-images.githubusercontent.com/65870/207238900-463a4b5d-f06e-4d51-957d-941e1f181905.png)

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 23.05 (Stoat), 23.05pre433819.2dea0f4c2d6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(suhr): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Deiru2k** [comment]
Same issue here.

```
[user@system:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 22.11 (Raccoon), 22.11.964.0152de25d49`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11, unstable"` // Unstable is used for some ad-hoc packages, system is built from 22.11
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```
Relevant config options

```
  environment.variables = {
    QT_QPA_PLATFORMTHEME = "qt5ct";
  };

  services.xserver.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;
  services.xserver.displayManager.sddm.enable = true;
```

**Comment by jtamagnan** [comment]
@Deiru2k or @suhr, were either of you able to find a solution other than relaunching `kwin_x11`?

**Comment by bobby3605** [comment]
I ran into this issue when switching between i3 and kde. I had forgot to disable picom when enabling kde. Once I did, the problem went away.

**Comment by zayez** [comment]
Can confirm, disabling picom solved the problem. Thanks @bobby3605!
