### ISSUE TITLE
Screen goes black with Looking Glass since 22.11 (NVIDIA+GNOME)

### ISSUE THREAD

**Issue by wyndon** [NixOS/nixpkgs#205915]
### Describe the bug
I have a GPU passthrough setup, and I am using Looking-Glass to have access to the VM.

Since the upgrade to 22.11, I've noticed, on boot, my right screen displaying some weird, glitchy lines before GDM's appearance.

**On Wayland**, If I move the cursor on Looking-Glass, the screen where Looking-Glass is instantly goes black, and it does so as long as I move my cursor. When clicking on Looking-Glass so that it grabs the mouse, this issue goes away, until I move the cursor out and back in. It can also happen that the other screen goes black, though much rarer.

**On X**, I do not have the exact same issue, but I do have a similar one; instead of the screen going completely black and preventing me from doing anything until it reappears, I only get a minor flicker.

### Steps To Reproduce
1. Configure your VM so it can use Looking-Glass and launch it
2. Launch Looking-Glass, wait for it to display something, and try to move your cursor in and out.

### Additional context
These are logs being generated when the screen goes completely black (Wayland) :
```console
Dec 13 14:15:11 astronaut .gnome-shell-wr[21590]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:11 astronaut .gnome-shell-wr[21590]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:11 astronaut .gnome-shell-wr[21590]: Failed to scan out client buffer: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:11 astronaut .gnome-shell-wr[21590]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:11 astronaut .gnome-shell-wr[21590]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:12 astronaut .gnome-shell-wr[21590]: Failed to scan out client buffer: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:12 astronaut .gnome-shell-wr[21590]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:12 astronaut .gnome-shell-wr[21590]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:12 astronaut .gnome-shell-wr[21590]: Failed to scan out client buffer: drmModeAtomicCommit: Invalid argument
Dec 13 14:15:12 astronaut .gnome-shell-wr[21590]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
```

I do not have any error logs on X.

### Notify maintainers

Not sure who to notify, but the error seems to come from gnome-shell, so I'll notify @hedning @jtojnar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.7-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20221209.e8ec26f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/store/ks1cdxhsc0jsyqwd905x5b5cl7kmf0zn-source`
```

**Comment by jtojnar** [comment]
Your NixOS version has an [older GNOME Shell version](https://github.com/NixOS/nixpkgs/blob/e8ec26f41fd94805d8fbf2552d8e7a449612c08e/pkgs/desktops/gnome/core/gnome-shell/default.nix#L71). Could you please try with https://github.com/NixOS/nixpkgs/pull/205135?

**Comment by wyndon** [comment]
FYI, I just tried Plasma, and everything works fine. I also updated to the latest `nixos-22.11`, without any luck.

**Comment by jtojnar** [comment]
Possibly this upstream bug: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6206

**Comment by wyndon** [comment]
Closing as I don't experience the issue anymore since a while.
