### ISSUE TITLE
404 when clicking "how to Review contributions" in contributing.md

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#20594]
## Issue description

At the end of [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) is a link "[Review contributions](http://hydra.nixos.org/job/nixpkgs/trunk/manual/latest/download-by-type/doc/manual#chap-reviewing-contributions)".

When I click it, I'm redirected to http://hydra.nixos.org/build/43818136/download/1/nixpkgs/manual.html#chap-reviewing-contributions , which gives an HTTP 404.

### Steps to reproduce

Click the last link in CONTRIBUTING.md.

**Comment by vcunat** [comment]
Hmm, I don't know how to get there. Our Hydra front end doesn't store files anymore and this part isn't present http://nixos.org/ yet because it wasn't added to 16.09. /cc @ericsagnes.

**Comment by ericsagnes** [comment]
Hydra issue https://github.com/NixOS/hydra/issues/321.
Shall we remove that link until this is fixed?

**Comment by vcunat** [comment]
@ericsagnes: this topic could well get cherry-picked to 16.09 and thus appear on nixos.org soon, but I don't understand why it's always mentioning nix**pkgs** but got added to nix**os** manual (even the link is wrong).

**Comment by ericsagnes** [comment]
> but I don't understand why it's always mentioning nixpkgs but got added to nixos manual (even the link is wrong).

@vcunat This was indeed a mistake, thanks for noticing!
