### ISSUE TITLE
S3 backed AMIs only have 2GB for root partition

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixpkgs#20596]
Since ab0ddac8f97cc7e05fe2e9376a47ddb3e6db3554 EBS and S3 backed AMIs have only 2GB for root partition.

For EBS that's fine since it's indeed can be resized, but that's not possible for S3. If you want to deploy something to the instance it will run out of disk space.

I propose we always create 8GB images, but use `qemu-img resize` to scale them down for EBS/HVM type.

cc @edolstra @rbvermaa

**Comment by copumpkin** [comment]
The fact that nobody's complained about this in over a year is probably reasonable indication that nobody uses the instance store AMIs anyway. Amazon's been discouraging/phasing out the instance store for a while. At some point (maybe 17.03 or the next release) it'll probably make sense for us to stop generating those AMIs.

**Comment by domenkozar** [comment]
Agreed, I've moved over to EBS. Let's just leave it around for some time and remove it..

**Comment by edolstra** [comment]
The ideas was that on instance-store instances, we can use the ephemeral disks as a unionfs on top of /nix and /var, so we don't need a lot of space for the root filesystem. However, many recent instance types don't have (much) ephemeral storage. So indeed you're better of using EBS.
