### ISSUE TITLE
gdm doesn't respect security.pam.loginLimits

### ISSUE THREAD

**Issue by e-user** [NixOS/nixpkgs#20608]
## Issue description

GDM currently uses custom PAM configuration that doesn't cover all items that are generated when `security.pam.services` is used, especially `pam_limits.so` for sessions. As a result, logging in via GDM doesn't apply custom limits set via `security.pam.loginLimits`.

### Steps to reproduce

1. Set custom limits that apply to the current user via `security.pam.loginLimits`
2. `nixos-rebuild switch`
3. Log out and back in again (via GDM)
4. Check `ulimit -a` output
5. `su - $(id -un) # Correctly applies limits because pam.d/su is used`
5. Check `ulimit -a` output again, compare

## Technical details

* System: 16.09.1066.417e04f (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1066.417e04f

**Comment by JeffreyVdb** [comment]
Also facing this issue.

**Comment by Profpatsch** [comment]
Closing in favor of open PR.
