### ISSUE TITLE
home-manager install fails on clean nixos 22.11

### ISSUE THREAD

**Issue by jimfarrand** [NixOS/nixpkgs#206050]
### Describe the bug

I am trying to install home-manager on a fresh Nixos 22.11 install using the instructions att
https://rycee.gitlab.io/home-manager/index.html#sec-install-standalone
but this fails with the following error:

```
$  nix-shell '<home-manager>' -A install

Creating initial Home Manager generation...

error: undefined variable 'mkPackageOption' at /nix/store/nlxa89jmpxf5k6gx0mm7baykx64lafhg-home-manager-22.11/home-manager/modules/programs/borgmatic.nix:154:17
(use '--show-trace' to show detailed location information)
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues
```

### Steps To Reproduce
1. (Install nixos 22.11 using the manual)
2. (Added "neovim" and "git" packages to nixos)
3. (Configure wifi in Gnome)
4. Added my username to `nix.allowedUsers` in `configuration.nix` and ran `nixos-rebuild switch`
5. ` nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz home-manager`
6. ` nix-channel --update`
7. Skipped the step about `NIX_PATH` since I am on nixos and the doc says this only applies to non-Nixos.
8. Ran `nix-shell '<home-manager>' -A install`
9. Observed failure to install

I've tried a few workarounds.  I tried running the step skipped at 7, just in case.  I also (separately) tried adding the home-manager channel as root.  I also tried using the master home-manager channel.  None of these worked, they all resulted either in the same error message or a different one.

### Expected behavior

It should be possible (and easy) to install `home-manager` on a fresh nixos install by following the instructions in the user manual.  Either there is a bug that needs fixing here (in home-manager or nixos) or the documentation is out of date and should be corrected.

### Screenshots

```
[jifarra@phaedra:~]$  nix-shell '<home-manager>' -A install

Creating initial Home Manager generation...

error: undefined variable 'mkPackageOption' at /nix/store/nlxa89jmpxf5k6gx0mm7baykx64lafhg-home-manager-22.11/home-manager/modules/programs/borgmatic.nix:154:17
(use '--show-trace' to show detailed location information)
Uh oh, the installation failed! Please create an issue at

    https://github.com/nix-community/home-manager/issues

if the error seems to be the fault of Home Manager.
```

### Additional context

I'm a long term Linux user but don't have huge expertise in NixOS.  I'm aware that it's a bit surprising that lots of people aren't hitting this (since it happens with such a plain unmodified install of nixos), so it's possible I'm doing something dumb.  I guess it's also possible that there's some change that people often make to their nixos installs that creates the right conditions for home-manager to install, but which isn't mentioned in the documentation - ie the fact that I'm on a fresh install is working against me.

I have sucessfully installed `home-manager` before (on older versions).  I also hit his bug on the last install I did many months ago, but unfortunately I can't remember how I worked around it.

The following bug might be related or a duplicate, though it references a different version (and has some other differences).
https://github.com/nix-community/home-manager/issues/3091

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
[jifarra@phaedra:~]$ nix-shell -p nix-info --run "nix-info -m" 
these paths will be fetched (42.44 MiB download, 184.23 MiB unpacked):
  /nix/store/3zwby038sph2lwvyz93nch1nfm9pafsa-linux-headers-5.14
  /nix/store/6r5amdvwn55yi79sk61a3fdjmxcnryzg-nix-info
  /nix/store/8rmwwv30162vnhn5l74m0vjiyq7dnm90-binutils-wrapper-2.35.2
  /nix/store/al0y3y2668icw7mzhagbb8ywg93dgnzh-glibc-2.33-123-bin
  /nix/store/b6ak2wii6k6j7m606c67rwyng1m7whnx-stdenv-linux
  /nix/store/djnfvbvkiv8yynavrl0bwl070sb2ppya-expand-response-params
  /nix/store/gwdq0r345gjpnsbllqjgrb8c8z23aiw9-gcc-10.3.0
  /nix/store/myjrqkb583ak29f3r5wmxrazy33i90pi-gcc-wrapper-10.3.0
  /nix/store/nzgdh8ak106kqk1snc0b3ckna8gjx354-glibc-2.33-123-dev
copying path '/nix/store/6r5amdvwn55yi79sk61a3fdjmxcnryzg-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/djnfvbvkiv8yynavrl0bwl070sb2ppya-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/3zwby038sph2lwvyz93nch1nfm9pafsa-linux-headers-5.14' from 'https://cache.nixos.org'...
copying path '/nix/store/al0y3y2668icw7mzhagbb8ywg93dgnzh-glibc-2.33-123-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/nzgdh8ak106kqk1snc0b3ckna8gjx354-glibc-2.33-123-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/gwdq0r345gjpnsbllqjgrb8c8z23aiw9-gcc-10.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/8rmwwv30162vnhn5l74m0vjiyq7dnm90-binutils-wrapper-2.35.2' from 'https://cache.nixos.org'...
copying path '/nix/store/myjrqkb583ak29f3r5wmxrazy33i90pi-gcc-wrapper-10.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/b6ak2wii6k6j7m606c67rwyng1m7whnx-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.89, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337975.eabc3821918"`
 - channels(jifarra): `"home-manager-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by jimfarrand** [comment]
I think I opened this against the wrong project somehow, so I'm going to close.  Apologies!

**Comment by rtacconi** [comment]
I have updated home-manager but now it's broken with this error, where can I get some help?
