### ISSUE TITLE
meld: shows "empty folder" for non-empty folders

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#206066]
### Describe the bug

When I try to compare two folders, it claims they are empty even though they are not - also after removing all file filters.

### Steps To Reproduce

```
$ rm -rf a b
mkdir a
echo "hello" > a/hello.txt
mkdir b
echo "hello again" > b/hello.txt
meld a b
```

### Expected behavior

Trees showing the differences

### Additional context

Comparing two files does work

### Screenshots

![out](https://user-images.githubusercontent.com/131856/207590240-5e796c2f-b7d6-46ce-9dc9-8a3276e1f89a.png)

### Notify maintainers

@jtojnar @mimame 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11, NixOS, 23.05 (Stoat), 23.05.git.64e0bf055f9M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos-20.03pre194293.2436c27541b"`
 - nixpkgs: `/home/aengelen/nixpkgs`
```

**Comment by jtojnar** [comment]
Works for me here. Do you perhaps have some file filters active?

**Comment by raboof** [comment]
> Are there any messages in the console or journal when running meld?

No, the console remains empty, and I checked the journal with `journalctl -f` - that should show everything, right?

**Comment by shelper** [comment]
i have the same problem, 
is this resovled?

**Comment by Piratara** [comment]
I have the same problem on Ubuntu 22.04, which appeared for no apparent reason. It's really annoying.

**Comment by Piratara** [comment]
I just fixed it. The display of new and modified files was disabled. The options to turn it back on are in Menu → View → File Status; enable all three entries there.

**Comment by raboof** [comment]
On NixOS unstable (meld 3.22.0), I don't see a "Menu → View → File Status" option, but there is a "File Status" at the top level.

I'm not sure if it was fixed in the mean time, or that I was just confused whether the checkboxes in the "File Filters" mean "Show these kinds of files" or "Hide these kinds of files". In any case, when I enable the checkbox for the "Modified" File Filter meld now correctly shows the differences in the reproducer above. I like to think I tried that when I opened this issue, but I'm not *entirely* sure.

Closing as fixed (or perhaps never an issue, sorry about the noise in that case ;) ).

**Comment by ace280** [comment]
Thank you for raising this report. I can confirm that it is all about the filters. In meld's basic setting it filters out many file types. 

In my case I wanted to compare two folders containing JPGs. but as long as the check mark is set for 'media' it wouldn't show any of those files. In fact it showed no files at all to be in those folders, as even the thumbs.db and the like where filtered with the 'OS-specific metadata'-filter.

This is on meld 3.22.0 running on Windows 10.

![grafik](https://github.com/NixOS/nixpkgs/assets/25365744/a6637d6e-4f15-466c-8f4c-28764913bada)
