### ISSUE TITLE
Discord's disable breaking updates script breaks if settings.json is invalid

### ISSUE THREAD

**Issue by rafaelsgirao** [NixOS/nixpkgs#206106]
### Describe the bug
Discord's package has a script which disables breaking updates, by looking and modifying the settings.json file.
This script breaks if said `settings.json` exists but is empty (fails to load the JSON object)
For some reason all values in this file cleared to me and I encountered this issue.
(tested on NixOS 22.11 but the script hasn't changed in master)
### Steps To Reproduce
1. Exit discord
2. Truncate `~/.config/discord/settings.json`
3. Launch discord
4. Discord should not launch at all (silently, unless launched from a terminal)

### Expected behavior
`disable-breaking-updates.py` should handle the exception `json.decoder.JSONDecodeError` which arises from this issue.

### Screenshots
N/A

### Additional context
Some logs of when this happens:
```txt
Traceback (most recent call last):
  File "/nix/store/r1r4a5yjkmkjwl0lp0hn9s9fg6sz9c1j-disable-breaking-updates.py/bin/disable-breaking-updates.py", line 27, in <module>
    settings = json.load(settings_file)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/zdba9frlxj2ba8ca095win3nphsiiqhb-python3-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Notify maintainers

@devins2518 @Artturin @Infinidoge 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.20221130.596a8e8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos-22.11"`
 - channels(rg): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

~ took 4s 
❯ 
```

**Comment by Infinidoge** [comment]
Hmm, interesting that Discord doesn't launch at all.
This is a pretty simple fix though, 
```py
except JSONDecodeError:
    print("[Nix] settings.json is malformed, letting Discord fix itself")
```
Or something like that

**Comment by vivlim** [comment]
Tangentally related: I installed discord on a new machine, and the disable breaking updates script didn't appear to have any effect until I created an empty `settings.json` containing just `{}`. There were other files in `~/.config/discord`, but not `settings.json`. Creating that would be nice.

Also, the only real indication that it was missing is that when I ran `discord` from a terminal, the first line of the output was `[Nix] settings.json doesn't yet exist, can't disable it yet`. This is quite easy to miss because it's at the top of the output, so maybe it would be good to show these errors in a `zenity` dialog or something similar.

**Comment by eadwu** [comment]
I'm surprised this is even in tree - I don't think we should be changing program behavior - especially when you're calling it `discord`.

I doubt the majority of the users even knew this was happening outside of those involved in PRs for nixpkgs. This is a matter of convenience like stated in the script that has a trade off causing a degradation in the security of the application - causing users to not update - relying on maintainers to do it.

Please create a separate package for this at the same time when fixing this - call it whatever - just not `discord|discord-canary|discord-ptb`. Or enclose it in an arg that is disabled by default.

**Comment by mayl** [comment]
I hit this same issue and adding an `~/.config/discord/settings.json` with contents `{}` got it running for me as well.

**Comment by bhipple** [comment]
Thanks for opening an issue and describing the fix.  This broke for me too and it took me a while to figure out why ...

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/225357
