### ISSUE TITLE
SSSD config file moved, programs rely on its exact location

### ISSUE THREAD

**Issue by tavi-vi** [NixOS/nixpkgs#206260]
### Describe the bug
The SSSD config file location was changed as a result of 87942da08e3221f32c7a43a17b165fabfdb04082, but sudo (and possibly other programs, but none I'm aware of) relies on its exact location when the system is configured to get sudo rules from FreeIPA. This happens with nixos 22.11 or newer.

### Steps To Reproduce
1. Build sudo with withSssd set to true
2. Add the following to /etc/sudo.conf
```
Debug sudo /var/log/sudo_debug.log all@debug
Debug sudoers.so /var/log/sudo_debug.log all@debug
```
3. Try to authenticate with sssd over sudo (this might only work if a rule is supplied to sudo via SSSD that contains a netgroup)
4. The logs will contain a line that matches `netgroup [^ ] matches` but the short hostname will be in the first field in the parenthesis instead of the full hostname

### Expected behavior
sudo should be able to find the ipa_hostname via the SSSD config

### Additional context
This is probably best resolved by symlinking /etc/sssd/sssd.conf to /var/lib/sssd/sssd.conf in case there are other programs that rely on reading the sssd config.

Also I noticed in the code that there's still a stray `config.environment.etc."sssd/sssd.conf".source` in the `systemd.services.sssd-kcm` configuration in nixos/modules/services/misc/sssd.nix that should probably be settingsFileUnsubstituted

### Notify maintainers
@yayayayaka
@bbigras
@Ma27

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 22.11 (Raccoon), 22.11.20221213.265caf3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wucke13** [comment]
https://github.com/NixOS/nixpkgs/pull/206273 partially addresses the issue mentioned here.

**Comment by bjornfor** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/220379
