### ISSUE TITLE
"callPackage /dir/with-trailing-slash/ {}" throws misleading error

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#20621]
## Issue description
```
$ nix-repl '<nixpkgs>'
nix-repl> pkgs.callPackage /tmp/mytest/ {}
error: value is a set while an integer was expected, at (string):1:1
```

By removing the trailing slash, everything is fine:

```
nix-repl> pkgs.callPackage /tmp/mytest {}
«derivation /nix/store/6wyvf5wwx2cxic6ydxgaky6mq22m2c14-bash-4.3-p48.drv»
```

Contents of /tmp/mytest:

```
$ cat /tmp/mytest/default.nix 
{ pkgs }:

pkgs.bash
```

It took a while to figure out that I simply had to remove the slash :-/

## Technical details

* System: 16.09.1066.417e04f (Flounder)
* Nix version: 1.11.4

**Comment by copumpkin** [comment]
Weird! Is it interpreting it as a division symbol somehow? Or what explains the error message? This feels like it might belong in the Nix repo.

**Comment by cleverca22** [comment]
yeah, its trying to divide a path by a set, i've run into this a few times as well

**Comment by copumpkin** [comment]
Seems like the lexer could be amended to slurp up the trailing slash rather than emitting a new token, since there's zero legitimate reasons to have a path followed by a division symbol. Either way this is a Nix issue, not a nixpkgs one.

**Comment by bjornfor** [comment]
Thanks for the feedback. Moved to https://github.com/NixOS/nix/issues/1138.
