### ISSUE TITLE
makeDesktopItem incorrectly requires GenericName

### ISSUE THREAD

**Issue by lverns** [NixOS/nixpkgs#20624]
## Issue description

[The spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) says that Desktop Entries are not required to have a GenericName key. However, the handy [makeDesktopItem](https://github.com/NixOS/nixpkgs/blob/a80cacd3ec8582bf3236fcd5031b0715358b3c82/pkgs/build-support/make-desktopitem/default.nix) function requires that it be specified. 

## Technical details

* System: NixOS: `17.03.git.322f5e5 (Gorilla)`
* Nix version:  `nix-env (Nix) 1.11.4`
* Nixpkgs version: `"16.09.877.5b08a40"`

**Comment by Profpatsch** [comment]
Closing in favor of the open PR.
