### ISSUE TITLE
vimPlugins.copilot-cmp

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#206236]
**Project description**
Lua plugin to turn github copilot into a cmp source

**Metadata**

* homepage URL: https://github.com/zbirenbaum/copilot-cmp
* source URL: https://github.com/zbirenbaum/copilot-cmp
* license: mit
* platforms: all

**Comment by nash-pillai** [comment]
I think that already exists
![image](https://user-images.githubusercontent.com/47931961/208308596-4b50233d-770f-40f9-a925-266f948399bf.png)

**Comment by Alexnortung** [comment]
Oh, great, thanks. I must've searched for copilot-cmp

**Comment by Alexnortung** [comment]
This is actually not the same plugin
https://github.com/zbirenbaum/copilot-cmp
and
https://github.com/hrsh7th/cmp-copilot/

**Comment by figsoda** [comment]
added in https://github.com/NixOS/nixpkgs/pull/208755
