### ISSUE TITLE
Rust toolchain can't build hello world crate on `aarch64-darwin`

### ISSUE THREAD

**Issue by athre0z** [NixOS/nixpkgs#206242]
### Describe the bug

Rust toolchains installed from nixpkg `rustup` tool can't build hello world crate on `aarch64-darwin` due to a linker error against `libiconv`.

### Steps To Reproduce

1. Spin up a `aarch64-darwin` machine
2. `nix build nixpkgs#rustup`
3. `result/bin/cargo new helloworld`
4. `cd helloworld`
5. `../result/bin/cargo build `

### Expected behavior

I expect the rustup cargo to be able to compile things.

### Error message from cargo

```
   Compiling testblah v0.1.0 (/Users/ath/Desktop/testblah)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/var/folders/jv/jm_5dpd13k1czv1qhs_v89h00000gn/T/rustcG7f5px/symbols.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.14zk7xfwqfsi8obc.rcgu.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.2i6y6y31mosa6scy.rcgu.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.2tio27vfxt1a8lu5.rcgu.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.4exdptxntusv1fad.rcgu.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.58xrho40r656pdxz.rcgu.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.eg5oyg41tbtyj2m.rcgu.o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca.2nytofdm5s8bcmvm.rcgu.o" "-L" "/Users/ath/Desktop/testblah/target/debug/deps" "-L" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-e24e0c7fd09714c0.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-b21ee2fb93f4a334.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-4ce05f7a889fff94.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-066d562bc324b771.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-8cb0c59b12697637.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-07d89e6b9536e071.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-c65b90a0ba43b683.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-9f8f7348c047b33a.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-34c451524b66e414.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-b1a98f39eda4ff6a.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-1c7622591b95f47e.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-5ee0c1cf171b84b0.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-3ee364d970255739.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-85b53c7fb22d1018.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-b5372de70a998108.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-945b7af0c9f21aac.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-0251f0b5857602a2.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-9382e8c089006a25.rlib" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-6b5d600bff28faab.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/ath/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/ath/Desktop/testblah/target/debug/deps/testblah-0add0e46f6f9b1ca" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: library not found for -liconv
          collect2: error: ld returned 1 exit status
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `0`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
```

This is a flake-based deployment without any channels configured and `nix-info` bails out after that.

CC @Mic92

**Comment by winterqt** [comment]
1. This has nothing to do with `rustup`, FWIW, you're using Nixpkgs' Cargo.
2. This is expected behavior (but will be fixed with 1.66), you can fix it by adding `libiconv` to your environment.

I'll keep this open until 1.66 hits unstable.

**Comment by winterqt** [comment]
> Hm, yes and no: using the repro steps in the original post, I use the cargo downloaded by rustup and in my [second comment](https://github.com/NixOS/nixpkgs/issues/206242#issuecomment-1353028084) I use nixpkg cargo. Both have the same issue.

Oops, you're right, didn't notice that.

> > you can fix it by adding libiconv to your environment.
> 
> If you allow me the somewhat off-topic question: how do I actually do that idiomatically? I tried `nix shell --impure nixpkgs#libiconv` but am still running into the same issue. It appears that it's only adding the `/bin` directory to my PATH.

So this is going to sound weird, but does `nix-shell -p libiconv` properly set `LIBRARY_PATH`? (Not sure off the top of my head.)

The idiomatic method is to use per-project development environments by way of `pkgs.mkShell` ([manual](https://nixos.org/manual/nixpkgs/unstable/#sec-pkgs-mkShell)), which will definitely specify the library where it's needed.

**Comment by athre0z** [comment]
> So this is going to sound weird, but does nix-shell -p libiconv properly set LIBRARY_PATH? (Not sure off the top of my head.)

No, but it does set two more other environment variables: `NIX_CFLAGS_COMPILE` and `NIX_LDFLAGS` which makes things work. I'm guessing that `NIX_LDFLAGS` is probably picked up by the ld wrapper. Interesting, so it looks like the nix3-shell isn't really a full replacement yet. Anyway, that's certainly a topic for a separate issue!

> The idiomatic method is to use per-project development environments by way of pkgs.mkShell ([manual](https://nixos.org/manual/nixpkgs/unstable/#sec-pkgs-mkShell)), which will definitely specify the library where it's needed.

Thanks! I was trying to avoid that variant because I can't upstream Nix config for the project I'm working on, but I guess I can just keep a corresponding Nix expression outside the source tree.

**Comment by winterqt** [comment]
> > So this is going to sound weird, but does nix-shell -p libiconv properly set LIBRARY_PATH? (Not sure off the top of my head.)
> 
> No, but it does set two more other environment variables: `NIX_CFLAGS_COMPILE` and `NIX_LDFLAGS` which makes things work. I'm guessing that `NIX_LDFLAGS` is probably picked up by the ld wrapper.

Correct, yup.

> Interesting, so it looks like the nix3-shell isn't really a full replacement yet. Anyway, that's certainly a topic for a separate issue!

Yeah, they use completely different methods of adding dependencies to the shell. Feel free to file an issue at https://github.com/NixOS/nix if you'd like, even if just for clarification of why the behavior is different/if it's intentional or not :)

**Comment by athre0z** [comment]
Closing this since this is no longer an issue with newer Rust toolchains.

**Comment by rupurt** [comment]
@athre0z what are the newer toolchains?

I'm still running into this problem with rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) which is installed as a nix package

**Comment by NoRePercussions** [comment]
Running into this with `rustc-1.78.0` in 24.05 when cross-compiling rust programs from `aarch64-darwin` to `gnu64`, but not when compiling natively on either platform. `nix build nixpkgs#legacyPackages.aarch64-darwin.pkgsCross.gnu64.static-web-server` (warning, may take half an hour or more)

**Comment by jsternberg** [comment]
I'm also running into this on 1.89.

```
$ rustc --version
rustc 1.89.0 (29483883e 2025-08-04) (built from a source tarball)
$ cargo --version
cargo 1.89.0 (c24e10642 2025-06-23)
```

Happens while linking with `cc`.

```
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: ld: library not found for -liconv
          collect2: error: ld returned 1 exit status
error: could not compile `zstd-sys` (build script) due to 1 previous error
```
