### ISSUE TITLE
vimPlugins.copilot-lua

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#206235]
**Project description**
Fully featured & enhanced replacement for copilot.vim complete with API for interacting with Github Copilot

**Metadata**

* homepage URL: https://github.com/zbirenbaum/copilot.lua
* source URL: https://github.com/zbirenbaum/copilot.lua
* license: mit
* platforms: all

**Comment by figsoda** [comment]
#207709
