### ISSUE TITLE
NetworkManager crashes trying to connect to Wi-Fi

### ISSUE THREAD

**Issue by tpwrules** [NixOS/nixpkgs#206478]
### Describe the bug
When supplying a WiFi password to a GUI version of NetworkManager (e.g. in `nm-connection-editor`), the GUI will crash and the password will not be saved. The following message is visible in the terminal:

```
(nm-connection-editor:1645): GLib-GIO-ERROR **: 21:44:47.629: settings object created with schema 'org.gnome.nm-applet.eap' and path '/org/gnome/nm-applet/eap/<uuid>/', but path '/org/gnome/nm-applet/eap/' is specified by schema
Trace/breakpoint trap (core dumped)
```

`nmtui` and `nmcli` are able to save passwords fine.

### Steps To Reproduce
1. Connect to new Wi-Fi network (or edit existing network)
2. Supply Wi-Fi password
3. Click Save or Connect

### Expected behavior
The connection is made.

### Additional context
Appears to be an upstream issue.

Other distro reports: https://forum.endeavouros.com/t/cannot-add-new-connection-in-nm-applet-and-nm-connection-editor-crash/33694/5

Upstream report: https://gitlab.gnome.org/GNOME/libnma/-/issues/18

Possible (temporary?) fix: https://gitlab.gnome.org/GNOME/libnma/-/merge_requests/44

### Notify maintainers

@jtojnar @NixOS/gnome 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.0-asahi, NixOS, 23.05 (Stoat), 23.05pre435044.0f5996b524c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(thomaswatson): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bobby285271** [comment]
Hi, can you please help test #205687?

**Comment by tpwrules** [comment]
Yes, that patch solves my issue.
