### ISSUE TITLE
`yubioath-flutter` creates a `desktop` entry on `~/.local/share/applications` at build time

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#206532]
### Describe the bug
When I installed `yubioath-flutter` a symlink was created from `~/.local/share/applications` to the desktop entry inside the store, this was done outside of Nix.

### Expected behavior
The desktop item should not be linked there as it breaks reproducibility. For example, changing the derivation (and thus its hash) or removing it does not delete the symlink as it is not managed by nix. I am not sure if this is a problem upstream or if the implementation of `mkFlutterApp` is somehow doing this.

### Notify maintainers
@lukegb 

### Metadata
```console
~ ✦ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 23.05 (Stoat), 23.05pre434773.b9a0cd40ede`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(mathiassven): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by lukegb** [comment]
I can't reproduce this: running

```
$ nix-shell -p yubioath-flutter --run authenticator
```

results in no observable change in my $HOME/.local/share/applications.

How are you installing this? nix-env? home-manager?

**Comment by MathiasSven** [comment]
Sorry I have tried reproducing it again for the last few days myself with no success... Initially, I installed it via `home-manager` and it was available as a broken desktop item on my KDE Desktop search, now I have tried rebuilding it multiple times under different conditions and garbage collecting to force a new result on the store and none of these lead to a desktop item... I might play around with this at another time to see what really happened but for now I am gonna blame this as a fluke caused by my DE.
