### ISSUE TITLE
lightdm fails to start the greeter

### ISSUE THREAD

**Issue by grwlf** [NixOS/nixpkgs#2065]
Hi! After recent update from   
70798243a221c4cf1e9a30135d5ea7f326a7c8b2
to
562f937d2123d98d200e8b62bc0c41a5c69843c6

the system fails to start the lightdm display manager. The worst thing is that booting to previous configuration also stops working. Probably, the /etc files are no longer compatible with the manager. 

Running the manager with --test-mode -d shows that the greeter (a part of lightdm) reports an error:

Failed to open PAM session: Cannot make/remove an entry for the specified session

The only workaround I've found is to switch to (buggy, AFAIK) slim.
Please, fix the lightdm!

**Comment by grahamc** [comment]
This seems to work for me on 16.03-beta.
