### ISSUE TITLE
Haskell packages that depend on JVM fail to build: "missing C library: jvm"

### ISSUE THREAD

**Issue by TikhonJelvis** [NixOS/nixpkgs#20669]
## Issue description

Haskell packages that depend on `jvm` (just `jni` and `HJVM` as far as I can tell) fail to build on both NixOS and OS X with the following error message:

```
Setup: Missing dependency on a foreign library:
* Missing C library: jvm
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

Both look like this in `hackage-packages.nix`:

```
"HJVM" = callPackage ({ ... }:
  mkDerivation {
    ...
    librarySystemDepends = [ jvm ];
    ...
  }) {jvm = null;};
```

They don't build by themselves. I also tried building them with `{ jvm = openjdk7 }` and `{ jvm = gcj }` (via `haskellPackages.callPackage haskellPackages.jni { jvm = gcj; }`), but that didn't work either.

### Steps to reproduce

Build `haskellPackages.HJVM` or `haskellPackages.jni`:

    nix-repl> :l <nixpkgs>
    nix-repl> :b haskellPackages.HJVM

## Technical details

* System: NixOS and OS X
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 17.03pre96005.caa81f7

**Comment by srhb** [comment]
Something like this in configuration-common.nix might be useful. I'm not sure exactly how it should be packaged, though.

    jni =  overrideCabal super.jni (drv: {
      extraLibraries = [pkgs.openjdk];
      configureFlags = ["--extra-lib-dirs=${pkgs.openjdk}/lib/openjdk/jre/lib/amd64/server"];
    });

**Comment by TikhonJelvis** [comment]
The extra lib flag looks like it's on the right track, thanks! Still haven't been able to make it work though.

I tried building a version of the `jni` package with that configure flag by adding this to my `config.nix`:

```
  haskellPackageOverrides = self: super: {
    ...
    jni2 = super.jni.override (args: args // {
      mkDerivation = drv: args.mkDerivation (drv // {
        extraLibraries = [ pkgs.openjdk7 ];
        configureFlags = ["--extra-lib-dirs=${pkgs.openjdk7}/lib/openjdk/jre/lib/amd64/server"];
      });
    });
  };
```

I still don't understand exactly how to override package attributes so I'm not 100% sure this is correct, but I think it had the desired effect:

```
configureFlags: --verbose --prefix=/nix/store/qn6qfpxi94wv3vjg75q7x7bli7fp1vwb-jni-0.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=clang --package-db=/private/var/folders/my/71d693qj5szdm986z1wj06krlrw5ms/T/nix-build-jni-0.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests --extra-lib-dirs=/nix/store/dfmh7qh5hc21wx4v5rxq6as5xjfcj2pq-openjdk-7u60b30/lib/openjdk/jre/lib/amd64/server --extra-include-dirs=/nix/store/dfmh7qh5hc21wx4v5rxq6as5xjfcj2pq-openjdk-7u60b30/include --extra-lib-dirs=/nix/store/dfmh7qh5hc21wx4v5rxq6as5xjfcj2pq-openjdk-7u60b30/lib
```

I'm not sure where all the other flags came from, but it had three that seem relevant:

```
--extra-lib-dirs=/nix/store/dfmh7qh5hc21wx4v5rxq6as5xjfcj2pq-openjdk-7u60b30/lib/openjdk/jre/lib/amd64/server
--extra-include-dirs=/nix/store/dfmh7qh5hc21wx4v5rxq6as5xjfcj2pq-openjdk-7u60b30/include
--extra-lib-dirs=/nix/store/dfmh7qh5hc21wx4v5rxq6as5xjfcj2pq-openjdk-7u60b30/lib
```

However, I'm still getting the same "Missing C library: jvm" error when I actually build the `jni2` package I defined.

**Comment by srhb** [comment]
Adding my snippet to configuration-common.nix made it build and it was loadable in ghci, so that was meant as inspiration to a more permanent patch for nixpkgs. :)

This should work in your configuration.nix:

    pkgs :
    {
      packageOverrides = super: let self = super.pkgs; in
      {
        haskellPackageOverrides = with self.haskell.lib; super.haskellPackages.override {
          overrides = hself: hsuper: {
            jni3 = overrideCabal hself.jni (drv: {
              extraLibraries = (drv.extraLibraries or []) ++ [ self.openjdk ];
              configureFlags = (drv.configureFlags or []) ++ [
                "--extra-lib-dirs=${self.openjdk}/lib/openjdk/jre/lib/amd64/server"
              ];
            });
          };
        };
      };
    };

**Comment by srhb** [comment]
Oh, and sorry about the extra bits (extraLibraries or [] etc...) - I just realized that wasn't very pedagogical. They're not necessary for building it, I was just cleaning it up earlier to keep it more in line with other package specific override fixes.

**Comment by TikhonJelvis** [comment]
Looks like that fixed the problem on NixOS, but I'm still getting the same error on MacOS, even with the correct `--extra-lib` flag.

**Comment by srhb** [comment]
I don't have a MacOS system, so I can't really investigate, but I suspect it's related to the library version. Can you try  `${pkgs.openjdk}/lib/openjdk/jre/lib/server` instead of `${pkgs.openjdk}/lib/openjdk/jre/lib/amd64/server` ?

**Comment by TikhonJelvis** [comment]
Okay, after poking around a bit, it looks like `${pkgs.openjdk}` on MacOS is the same as `${pkgs.openjdk}/lib/openjdk/` on NixOS, so `--extra-lib-dirs=${pkgs.openjdk7}/jre/lib/server` worked.

I ran into a different error, but I think it's specific to the `jni` package.

Still, this leaves the question of how Haskell packages like this should be handled in general.

**Comment by peti** [comment]
The attribute `extraLibraries` is obsolete and should no longer be used. `librarySystemDepends` is the proper new attribute to use instead.

Packages listed in `librarySystemDepends` have `--extra-lib-dirs` and `--extra-include-dirs` flaga generated for them automatically, but unfortunately this doesn't work for the jvm because its headers and libs reside in strange locations that don't match what we normally expect.

I've committed https://github.com/NixOS/cabal2nix/commit/84cfd79b3682a17d02182db321733ec913101248 to remedy the `jvm = null` argument to the expression, but we'll still need some solution for finding out the proper lib path in a portable way that doesn't make too many assumptions about the version of the JDK people are using.
