### ISSUE TITLE
Packages using NIXOS_OZONE_WL need wayland dep.

### ISSUE THREAD

**Issue by KenMacD** [NixOS/nixpkgs#206744]
### Describe the bug

When running an application with `NIXOS_OZONE_WL=1` on nixos-unstable results in the following error:

```
wayland_connection.cc(157)] Failed to load libwayland-cursor.so.0.
ERROR:ozone_platform_wayland.cc(220)] Failed to initialize Wayland platform
ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
```
Adding wayland as a runtime dependency through an overlay appears to fix the program.

An example program with this issue is `signal-desktop`. Overlay that fixed it:

```
  signal-desktop = super.signal-desktop.overrideAttrs (old: {
    runtimeDependencies = old.runtimeDependencies ++ [super.wayland];
  });
```

From a grep I would guess this probably affects:

```
pkgs/applications/office/micropad/default.nix
pkgs/applications/misc/whalebird/default.nix
pkgs/applications/misc/obsidian/default.nix
pkgs/applications/misc/1password-gui/linux.nix
pkgs/applications/networking/browsers/chromium/default.nix
pkgs/applications/networking/instant-messengers/teams-for-linux/default.nix
pkgs/applications/networking/instant-messengers/session-desktop/default.nix
pkgs/applications/networking/instant-messengers/feishu/default.nix
pkgs/applications/networking/instant-messengers/schildichat/schildichat-desktop.nix
pkgs/applications/networking/instant-messengers/slack/default.nix
pkgs/applications/networking/instant-messengers/signal-desktop/generic.nix
pkgs/applications/networking/instant-messengers/jitsi-meet-electron/default.nix
pkgs/applications/networking/instant-messengers/discord/linux.nix
pkgs/applications/networking/instant-messengers/element/element-desktop.nix
pkgs/applications/networking/browsers/brave/default.nix
pkgs/applications/networking/browsers/google-chrome/default.nix
pkgs/applications/editors/vscode/generic.nix
```

It looks like there's one fix PR fro the vscode one in  #206695.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.19700101.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/store/5nl9sdpbqcgiq4qjd6ah5hms5kh6j4x3-source`
```

**Comment by Croissong** [comment]
Does anyone have an overlay fix for slack?
I tried 
```nix
slack = super.slack.overrideAttrs (old: {
      rpath =
        super.lib.makeLibraryPath [
          ...
          super.wayland
```
but that doesn't seem to work.

**Comment by Artturin** [comment]
`rpath = old.rpath ++ super.lib.makeLibraryPath ...`

**Comment by Mic92** [comment]
vscode and signal have been fixed now.

**Comment by Mic92** [comment]
> Does anyone have an overlay fix for slack? I tried
> 
> ```nix
> slack = super.slack.overrideAttrs (old: {
>       rpath =
>         super.lib.makeLibraryPath [
>           ...
>           super.wayland
> ```
> 
> but that doesn't seem to work.

Why not fix this upstream?

**Comment by Mic92** [comment]
This should fix all packages that use our electron binary: https://github.com/NixOS/nixpkgs/pull/206978 i.e. element-desktop

**Comment by winterqt** [comment]
Why did this just start cropping up, did something change in Electron?

**Comment by Mic92** [comment]
I have not tracked it down but something is dlopen this particular wayland library.

**Comment by SebTM** [comment]
The basic issue was solved with #206808, is there something left, to close this issue? :)

**Comment by KenMacD** [comment]
I'm not sure they all work, but the ones I tested do, so I'll close this.

**Comment by aidenmadaffri** [comment]
This does not seem to have been resolved with 1Password. Also adding an overlay to rpath or runtimeDependencies for it does not allow the configuration to be created.

**Comment by SebTM** [comment]
> This does not seem to have been resolved with 1Password. Also adding an overlay to rpath or runtimeDependencies for it does not allow the configuration to be created.

This is on purpose (https://github.com/NixOS/nixpkgs/pull/237925)
