### ISSUE TITLE
iputils: 20211215 -> 20221126

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#206772]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: iputils

current version: 20211215
desired version: 20221126

###### Notify maintainers

maintainers: @primeos @lheckemann

###### Note for maintainers

Please tag this issue in your PR.

**Comment by NickCao** [comment]
Done in https://github.com/NixOS/nixpkgs/pull/209264
