### ISSUE TITLE
freerdp: review build options

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#206886]
###### Checklist

I reported some flakey test in freerdp upstream and they hinted that maybe we could be building freerdp better:
https://github.com/FreeRDP/FreeRDP/issues/8526#issuecomment-1357134746

Filing this so I don't forget to look at it.

**Comment by peterhoeg** [comment]
I use freerdp *all* the time, so I have patched things up on my side and will open a proper PR when I have been running with it for a while.

FYI, we are in fact already building against ffmpeg.
