### ISSUE TITLE
vhs auto-update does not work

### ISSUE THREAD

**Issue by brumhard** [NixOS/nixpkgs#206908]
Currently, the auto update of the vhs package does not work (see logs from [r-ryantm](https://r.ryantm.com/log/vhs/2022-12-15.log)).
It looks like the problem is that the `vendorHash` property is not updated as it is not recognized. Since this property got introduced in August or sth (see [here](https://github.com/NixOS/nixpkgs/commit/0d5c464ad611c9d7b8ba20717591ad435404ebcf)) I guess it's not covered in `nixpkgs-update` yet. I would guess changing to the property `vendorSha256` like in the other packages should work. Sadly I cannot validate that on my machine since I'm having a M1 mac and `nixpkgs-update` is not available for that.

I also opened https://github.com/ryantm/nixpkgs-update/issues/332 for the overall issue.

###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: vhs

current version: 0.1.0
desired version: 0.2.0

###### Notify maintainers

maintainers:
@maaslalani 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by ryantm** [comment]
This should be fixed now.
