### ISSUE TITLE
Cannot get wiki-js git storage working.

### ISSUE THREAD

**Issue by blargg** [NixOS/nixpkgs#206964]
### Describe the bug

With a working services.wiki-js config, I'm attempting to use git as a storage medium. This can be done from the admin options. More info about this at https://docs.requarks.io/storage/git

While setting git storage up, I keep running into various issues, like `Error: spawn git ENOENT`, and warnings about read only file systems (on file systems that are not read only).

I wanted to check in and see if anyone has this working (and I just have something weird with my setup) before going into more investigation. 

### Steps To Reproduce

1. Enable wiki-js
2. Open the admin page, and go to the storage settings.
3. Set the options for the git storage. I created a new github repo, and filled in my user information for the settings.
    1. auth type: ssh
    2. set the repo uri to the one you create
    3. ssh key mode: contents
    4. ssh private key contents: your private key that is registered with github
    5. default author name: your name
    6. default author email: your email
    7. local repo path: `./repo` (I turned off DynamicUser in the wiki-js service config. that might allow this to work, if you can't get any files to write at all, let me know and I can give you the change I made).
    8. Set the storage to bi-directional
4. Click on "Add untracked files"
5. Click on "Force Sync"

This will create the folder for the git repo at `./repo` and add the files for the wiki, but it will not create the git repo and not be able to add and upload the files.

Here are some logs from the journal:
```
Dec 24 06:13:15 server node[13684]: 2022-12-24T06:13:15.610Z [MASTER] info: (STORAGE/GIT) Adding page home.html...
Dec 24 06:13:15 server node[13684]: 2022-12-24T06:13:15.621Z [MASTER] warn: Error: spawn git ENOENT
Dec 24 06:13:15 server node[13684]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
Dec 24 06:13:15 server node[13684]:     at onErrorNT (node:internal/child_process:485:16)
Dec 24 06:13:15 server node[13684]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)

```
### Expected behavior
I expect this to create a local repo in the directory from the settings

### Notify maintainers

@Ma27 (or anyone) just let me know if anyone has this working, or if this is a known issue.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 23.05 (Stoat), 23.05.20221224.d9d66ce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos-22.11pre422248.412b9917cea"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by blargg** [comment]
I started looking into this on my own. I updated the repro steps and added the error messages I'm getting.

Wiki-js can write out the files, but none of the git opterations (repo creation, adding the files, committing) seem to work. Looking through the logs, I get `Error: spawn git ENOENT`. It seems like either wiki-js cannot find or use git somehow, though I confirmed that git is installed and the wiki-js user can run it.

**Comment by Ma27** [comment]
Globally installed packages are not available to systemd units by default. You can take a look at the path of a unit by looking at the `Environment=PATH=...` line from `systemctl cat wiki-js.service`.

This should be solvable by adding `git` to `systemd.services.wiki-js.path`. If that works for you, feel free to file a PR!

**Comment by blargg** [comment]
Ah, that makes a lot of sense, thanks for the help!

I'll test this out and do a PR in the next couple days or so.
