### ISSUE TITLE
`httpie-3.2.1` on unstable fails to install (tests are failing)

### ISSUE THREAD

**Issue by x3rAx** [NixOS/nixpkgs#206976]
### Steps To Reproduce
1. Add unstable channel:
   ```
   $ nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
   $ nix-channel --update nixos-unstable
   ```
2. Set the unstable channel as temporary default:
   ```
   $ export NIX_PATH="nixpkgs=/nix/var/nix/profiles/per-user/$USER/channels/nixos-unstable:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/$USER/channels"
   ```
2. Install `httpie` either way:
   - `nix-shell -p httpie`
   - `nix-env -iA nixos-unstable.httpie`
   - through `configuration.nix` and `nixos-rebuild build`
   - through `home-manager`

### Build log
https://gist.github.com/x3rAx/682292d32420967d5c3381119c9d7894#file-nix-httpie-bild-log-txt-L410

### Additional context
One of my systems runs on unstable channel. It happens to me since 2022-12-18 when I ran `nixos-rebuild switch --upgrade`.

### Notify maintainers

@antono @relrod @schneefux @SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 23.05 (Stoat), 23.05pre435935.04f574a1c0f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos-22.11"`
 - channels(x3ro): `"home-manager, n, n-22-11-22.11, nixos-unstable, nu"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fabaff** [comment]
Failing tests disabled https://github.com/NixOS/nixpkgs/pull/207035

**Comment by tom-tubeless** [comment]
Sorry, I tried `nix flake update` with a `sudo nixos-rebuild switch --upgrade --flake .#hostname` after that, but I still got the error ([log](https://gist.github.com/tom-tubeless/337037fc92893c7991e7399b77299e53)).

```console
~~> nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.11-zen1, NixOS, 23.05 (Stoat), 23.05.20221209.2dea0f4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `""`
 - channels(lgo): `"nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/user/channels/nixos-unstable`
 ```

**Comment by xanderio** [comment]
The fix hasn't been merged into the unstable branch. https://nixpk.gs/pr-tracker.html?pr=207035
