### ISSUE TITLE
R has a large number of superfluous dependencies.

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nixpkgs#20695]
## Issue description
The R derivation enables almost every optional interpreter feature. At the very least I would expect to be able to configure whether or not the resulting interpreter supports:

- X11
- Cairo
- tcl/tk
- TeX
- graphviz

Not only are all of those dependencies pulled in, in order to build an interpreter without them one must write their own derivation. Ideally the R derivation would make these features optional, and I would expect them to be switched off by default.

What's the most idiomatic way to go about doing this? Would adding derivation arguments that simply switch these features on and off be sufficient?

### Steps to reproduce
- Build the R derivation on a headless system.
- Notice that X11 is being pulled in.
- Frown.

## Technical details

nixpkgs: "17.03pre96125.a6f392a"

**Comment by FRidh** [comment]
> Ideally the R derivation would make these features optional, and I would expect them to be switched off by  default.

That would be up to the maintainer. If it is generally expected, that all those packages are needed for producing a proper R, then they would be enabled by default.

Even so, we might want to use multiple outputs, putting those files that are needed for, say, X11, in a separate output.

**Comment by TravisWhitaker** [comment]
> If it is generally expected, that all those packages are needed for producing a proper R, then they would be enabled by default.

I can't say what constitutes a "proper R," but I can say that I would expect to be able to easily use R without X11.

> Even so, we might want to use multiple outputs, putting those files that are needed for, say, X11, in a separate output.

I'm not sure that multiple outputs would be sufficient, since the interpreter needs to link (or not link) against several different libraries for X11 support. Are you suggesting that there be multiple outputs, each with its own R interpreter with different integrations linked in?

**Comment by FRidh** [comment]
> I'm not sure that multiple outputs would be sufficient, since the interpreter needs to link (or not link) 
against several different libraries for X11 support. Are you suggesting that there be multiple outputs, each with its own R interpreter with different integrations linked in?

In e.g. Python the `tkinter` module of the standard library requires `libX11`. It's just a Python module, so Python can be used without it, and therefore we can put it into another store path without breaking Python. Maybe the same goes for R, I don't know. If this cannot be done with R, then it would be nice to have parameters for the different options to support.

**Comment by TravisWhitaker** [comment]
I assume in that case `libX11` is linked in when the `tkinter` module is loaded. With R, the interpreter itself links against `libX11` and friends, so if multiple outputs were used then each store path would need its own R interpreter.

**Comment by FRidh** [comment]
Indeed. No extra outputs then, but extra parameters.

**Comment by Profpatsch** [comment]
(triage) any progress on this?

**Comment by TravisWhitaker** [comment]
I no longer have a stake in this issue, so I'll close it.
