### ISSUE TITLE
rustUnstable builds rustc twice

### ISSUE THREAD

**Issue by qknight** [NixOS/nixpkgs#20692]
## Issue description

with nixpkgs in revision `d074a5a07ee5fa96d5f4994b489c50dea1e4745a` i want to build rustUnstable and see this:

```
time nix-env -I nixpkgs=/root/nixpkgs -f /root/nixpkgs/default.nix -iA rustUnstable --cores 8 -j1
installing ‘cargo-master-2016-07-25’
installing ‘rustc-master-1.13.0-g308824a’
these derivations will be built:
  /nix/store/4r3isl9m0x72l9psz2vw6nw8a6fgj3d8-rustc-beta-2016-08-17-ge627a2e.drv
  /nix/store/qq2ykk0nafgq9in0vxr7jjgfdxc3y0q2-cargo-0.14.0.drv
  /nix/store/jq840z5ii6mywn01scwykya7bga93kp8-cargo-beta-2016-07-25-fetch.drv
  /nix/store/2qlnahc6cvhxamsddilmm64qzh1aahl0-cargo-beta-2016-07-25.drv
  /nix/store/w6r4mbxrgq3mzpdglk7ybpv4rzcgf56a-rustc-master-1.13.0-g308824a.drv
  /nix/store/6gdzbb3y6160yjizcc1nxwp4qg6mf2q0-cargo-master-2016-07-25.drv
```

so, does it really make sense to build `rustc-master` and `rustc-beta`?

@shlevy @the-kenny 

## Technical details

* System: (NixOS: `16.09 but with nixpkgs master`)

**Comment by the-kenny** [comment]
`rustc-unstable` is bootstrapped by `rustc-beta` which is bootstrapped by `rustc-stable`. See https://github.com/rust-lang/rust/blob/master/src/stage0.txt#L5-L8

That said, I don't recommend to use `rustc-unstable` form `nixpkgs`. We currently don't have the manpower to update it every day (and don't really want to as nightlies don't belong in `nixpkgs`). 

For playing with unstable I currently use the following file in a `nix-shell` environment: http://p.tarn-vedra.de/nightly.nix.html

It downloads the *current* nightly build. This is inherently impure, but fine for development (or even basic non-public deployments).

**Comment by 8573** [comment]
> It's a modified version of a gist someone in the irc channel gave me, but I can't find it anymore (else I'd like to give credit).

@the-kenny: that looks to me like @Ericson2314's rustc-nightly expression, which, as I understand it, is currently maintained as: <https://github.com/solson/rust-nightly-nix>

**Comment by the-kenny** [comment]
@8573 You're right. Thanks for pointing me to this repo :)

**Comment by NeQuissimus** [comment]
Should we maybe look to remove the nightlies if they are essentially unmaintained?
If somebody really needs a nightly, they can always create a custom Nix expression for it...

**Comment by the-kenny** [comment]
@NeQuissimus I would vote in favor of a removal of `nightly`, but we should at least ask around the mailing list. I know of at least one person who wouldn't like to see it removed.

**Comment by qknight** [comment]
we fixed the `rust beta` and `rust nightly` build and will soon come up with a PR. we want to have `rust nightly` (not updated every night though) in nixpkgs since we are working with it.

**Comment by qknight** [comment]
i've created this PR: https://github.com/NixOS/nixpkgs/pull/20780

@the-kenny please review and merge
