### ISSUE TITLE
clisp fails to build

### ISSUE THREAD

**Issue by jackwoodside** [NixOS/nixpkgs#206958]
### Steps To Reproduce
1. build *clisp*

### Build log
```
base/lisp.run -B . -M base/lispinit.mem -norc -q -i i18n/i18n -i syscalls/posix -i regexp/regexp -i readline/readline -x (saveinitmem "base/lispinit.mem")
;; Loading file /build/clisp-2.49/builddir/i18n/i18n.fas ...
;; Loaded file /build/clisp-2.49/builddir/i18n/i18n.fas
;; Loading file /build/clisp-2.49/builddir/syscalls/posix.fas ...
;; Loaded file /build/clisp-2.49/builddir/syscalls/posix.fas
;; Loading file /build/clisp-2.49/builddir/regexp/regexp.fas ...
;; Loaded file /build/clisp-2.49/builddir/regexp/regexp.fas
;; Loading file /build/clisp-2.49/builddir/readline/readline.fas ...
*** - FFI::FIND-FOREIGN-VARIABLE: foreign variable
      #<FOREIGN-VARIABLE "rl_readline_state" #x00007FFFF7FBC640> does not have
      the required size or alignment

./clisp-link: failed in /build/clisp-2.49/builddir
make: *** [Makefile:2623: base] Error 1
error: builder for '/nix/store/rbykd92038rp80a71diyxqmbiz4m8f60-clisp-2.49.drv' failed with exit code 2;
```

### Notify maintainers
@7c6f434c

### Metadata
```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 23.05 (Stoat), 23.05pre435935.04f574a1c0f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(user): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jboyens** [comment]
It seems to build just fine on `master` (ee986012fe5e9f65f3d953a47f375349bff8cf25), but fails on `nixos-unstable` (04f574a1c0fde90b51bf68198e2297ca4e7cccf4).

For the life of me, I can't see any difference between the two branches that stands out as a culprit here.

**Comment by jboyens** [comment]
Here's the commit/change that's needed to fix the build: 83f6beddab6999712d93f4f865055be4f0d0c63f

**Comment by jboyens** [comment]
Confirmed (on my systems at least) slamming the fix mentioned in https://github.com/NixOS/nixpkgs/pull/206745 into an overlay fixes my build.

**Comment by 42triangles** [comment]
I ran into this issue and used the work around from x418, but after I got an error due to it not finding `readline6` when updating today I tried removing the workaround, and this issue seems to now be fixed as far as I can tell.

**Comment by 7c6f434c** [comment]
By the way, should we care about the last release, or just accept that while maintenance continues, we probably won't see any new releases tagged?
