### ISSUE TITLE
Neovim uv_dlopen cannot open libstdc++

### ISSUE THREAD

**Issue by victor-timofei** [NixOS/nixpkgs#207003]
### Describe the bug
Neovim cannot load the `libstdc++.so.6`. This prevents me using plugins such as `treesitter`.

### Steps To Reproduce
```sh
nix-env -iA nixpkgs.neovim
nvim +checkhealth
```

In the checkhealth there are errors saying:
```
failed to load: Failed to load parser: uv_dlopen: libstdc++.so.6: cannot open shared     object file: No such file or directory
```

### Expected behavior
Ability to load that library.

### Additional context
OS Ubuntu 22.04

### Notify maintainers
@manveru @rvolosatovs

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-56-generic, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by Sciencentistguy** [comment]
I also am having this issue. Solved it by explicitly setting LD_LIBRARY_PATH in my neovim wrapper. See https://github.com/Sciencentistguy/nixfiles/blob/a3adfece4d4c2caf1686c6899b2958e2ed0a7014/home/core/neovim/neovim.nix#L68

**Comment by teto** [comment]
install your treesitter grammars via nix and the issue goes away.

**Comment by davegallant** [comment]
> install your treesitter grammars via nix and the issue goes away.

This works for me. It's documented [here]( https://nixos.wiki/wiki/Treesitter).

**Comment by teto** [comment]
related https://github.com/nvim-treesitter/nvim-treesitter/pull/4059

**Comment by Soliprem** [comment]
It happened to me twice. Simply uninstalling all the parsers and installing them back fixes it for me

**Comment by onemoresuza** [comment]
The solution seems to have been found on [this issue](https://github.com/NixOS/nixpkgs/issues/130152#issue-944062384).

Solution:

``` sh
nix-shell -p gcc --run "nvim -c 'TSUpdate all'"
```
