### ISSUE TITLE
enable lxd socket and not service

### ISSUE THREAD

**Issue by alkeryn** [NixOS/nixpkgs#207048]
hey, is it possible to enable lxd but as a socket and not a service ?
that way it runs only once we ask for it and not by default.

**Comment by bjornfor** [comment]
Would that be the same or different from a systemd socket activated service?

**Comment by alkeryn** [comment]
@bjornfor well the same, i'd like for lxd to not start at boot, but start only once i want to use it for example by typing "lxc list".

i figured out how to do it by doing services.lxd.wantedBy = lib.mkForce []; but that does seems like an ugly solution.
also the service is still enabled it just never starts by itself.

on other distros you can do stuff like systemctl disable lxd.service and systmectl enable lxd.socket.
that way the service will start only when you try to use it (for example by running an lxc command).

**Comment by adamcstephens** [comment]
Using `systemd.services.lxd.wantedBy = lib.mkForce [];` is the best way to handle this.

**Comment by alkeryn** [comment]
@adamcstephens it does work but it seems like a ugly hack to me, it would be nice if we separated services and sockets generally speaking, or add the socket option and when enabled it disables the service.

but i guess it also works like that.

**Comment by adamcstephens** [comment]
The only other service I’ve seen that does something like this is sshd. That’s a service that runs everywhere though so more people care about reducing its resource use.

If you’d like to PR updating the module to accept a similar option, I’ll review it. But it’ll be more code than the workaround and may not be used by anybody else. :)
