### ISSUE TITLE
transmission leaks memory

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#207047]
### Describe the bug
After upgrading to 22.11, I noticed that a host I run transmission on had steadily increasing memory usage.
When looking at what runs on this host, I managed to narrow this issue down to transmission.

![image](https://user-images.githubusercontent.com/1229027/208774826-21a090e0-267c-4a96-af2b-019cd41f762c.png)
The host was upgraded on 09.12. On 13.12. transmission was restarted when switching to a new configuration.

I'm currently trying to see if building transmission (from unstable) without the patch introduced in https://github.com/NixOS/nixpkgs/pull/196687, but using `openssl_legacy` (currently only on `master`/`staging-22.11`) instead, might fix this.

Since this occurs in 22.11, but did not in 22.05, I'd assume it's not really an upstream issue.

cc @NickCao 

### Notify maintainers
@astsmtl @vcunat @wizeman

**Comment by vcunat** [comment]
I expect there's still some upstream issue, even if it's only triggered by some combination of versions (and config, etc.)  but either way, getting more details will probably help with fixing it.

**Comment by vcunat** [comment]
Or maybe that patch is buggy.  I know neither their code nor openssl APIs, but e.g. on this place I'd expect additional `free(handle);` at a very quick glance:
https://salsa.debian.org/debian/transmission/-/blob/debian/3.00-2.1/debian/patches/openssl3-compat.patch#L71

**Comment by ajs124** [comment]
Maybe we should report that to debian then.

So we have a bunch of options:
1. fix the patch
2. drop the patch and use `openssl_1_1`
3. drop the patch and use either `openssl_legacy`

 `openssl_1_1` kind of sucks, because `libevent`, which is in transmission's `buildInputs` propagates `openssl` (aka `openssl_3`), so we'd end up with two different major versions of openssl instead of just two times openssl 3.x with different configs.
although `openssl_legacy` also isn't ideal, because it enables the legacy provider everywhere, instead of only where it's needed, like the patch does.

**Comment by NickCao** [comment]
Debian should be notified of the issue instead of keeping the broken patch in circulation. @vcunat would  you like to take the time？

**Comment by vcunat** [comment]
I think at this point it's just a speculation that the patch is at fault.  If it's the error I thought, it would probably leak with older openssl as well.

**Comment by vcunat** [comment]
I certainly won't have time for this _today_, but probably I could have another deeper look within a week.

**Comment by ajs124** [comment]
> Maybe we should report that to debian then.
> 
> So we have a bunch of options:
> 
>     1. fix the patch
> 
>     2. drop the patch and use `openssl_1_1`
> 
>     3. drop the patch and use either `openssl_legacy`
> 
> 
> `openssl_1_1` kind of sucks, because `libevent`, which is in transmission's `buildInputs` propagates `openssl` (aka `openssl_3`), so we'd end up with two different major versions of openssl instead of just two times openssl 3.x with different configs. although `openssl_legacy` also isn't ideal, because it enables the legacy provider everywhere, instead of only where it's needed, like the patch does.

I've opted for option 3 for my setup as a quick fix in an overlay, which seems to work.

If you have time in the next week or two, I think that's soon enough, because this issue has been in a ubuntu release for half a year, so apparently it doesn't affect most users too badly. Although I have seen issues reported upstream, which I'd attribute to this, if I had to guess. Can try to find links, if anyone interested.

**Comment by Shados** [comment]
While the patch may be at fault, it's worth noting that there are a [bunch of known memory leaks in transmission 3.00](https://github.com/transmission/transmission/issues/3055), that have been fixed subsequently. We're still running 3.00 in nixpkgs because there's been no non-beta release since -- the next release has been slow as a result of transmission being rewritten in C++. 4.0.0-beta.2 is available, perhaps it might be worth packaging this as a separate `transmissionUnstable` package or such?

**Comment by ajs124** [comment]
While yes, the issue you linked does link to memory leak fixes after transmission 3.00, the bug report was created by someone on Ubuntu, after the release of 22.04, so it's likely that the really bad memory leak they're hitting is actually the one caused by the Ubuntu downstream patch.

I've had this overlay (where unstable is `nixos-unstable-small`, as part of `super`, for reasons) :
```
(self: super: {
    transmission = (super.unstable.transmission.overrideAttrs (oA: {
      patches = [];
    })).override { openssl = super.unstable.openssl_legacy; };
  }) ];
```
running for the last two weeks and transmission has been running fine again. Same as before 22.11, where we already were on transmission 3.00.

**Comment by vcunat** [comment]
My [trivial attempt at version 4](https://github.com/NixOS/nixpkgs/compare/master...vcunat:nixpkgs:p/transmission-4) fails with `error: 'dht_callback_t' has not been declared`.

So I don't know... perhaps the working variant with `openssl_legacy` for now.

**Comment by ajs124** [comment]
See #209341 for `openssl_legacy`.

Also, I left a comment [here](https://bugs.launchpad.net/ubuntu/+source/transmission/+bug/1946215) asking the Ubuntu people if they might also want to look into this.

**Comment by rnhmjoj** [comment]
> While yes, the issue you linked does link to memory leak fixes after transmission 3.00

It's not only memory leaks (which lead to the process being killed by the oom_killer): I noticed at least two different crashes, something than has never happened before 3.0. I would seriously consider downgrading to 2.94 because this version is barely usable.

**Comment by vcunat** [comment]
Uh, that's a surprise to me.  We've used "3.00" version in nixpkgs for years (in stable 20.09 already).

**Comment by rnhmjoj** [comment]
> Uh, that's a surprise to me. We've been using "3.00" version in nixpkgs for years (in stable 20.09 already).

You're right, I implicitly assumed it was a new update but it isn't: the trouble started with NixOS 22.11.

**Comment by ajs124** [comment]
> My [trivial attempt at version 4](https://github.com/NixOS/nixpkgs/compare/master...vcunat:nixpkgs:p/transmission-4) fails with `error: 'dht_callback_t' has not been declared`.

`dht` also needed an update. See https://github.com/NixOS/nixpkgs/pull/215316 for that.
