### ISSUE TITLE
Invalid nftables configuration flushes rulesets.

### ISSUE THREAD

**Issue by richousrick** [NixOS/nixpkgs#207058]
### Describe the bug
nftables.service's Exec stop runs `nft flush ruleset`: https://github.com/NixOS/nixpkgs/blob/0938d73bb143f4ae037143572f11f4338c7b2d1c/nixos/modules/services/networking/nftables.nix#L126

Therefore, any problems in the firewall configuration when the service starts (or if it crashes) leads to the rules being cleared, and you having no firewall.
This is additionally problematic when using a rulsetFile as it seems to only apply on system restart; whos behaviour goes against the documentation. https://github.com/NixOS/nixpkgs/blob/0938d73bb143f4ae037143572f11f4338c7b2d1c/nixos/modules/services/networking/nftables.nix#L81

### Steps To Reproduce
1. Enable nftables with a rulset file e.g. 
``` Nix
  networking.nftables = {
    enable = true;
    rulesetFile = builtins.toString ./netfilter;
  };
```
Where ./netfilter is a file with nftables rules in the same directory as the nix file this is written in.
e.g.
```
table ip firewall {
  chain output {
    type filter hook output priority -1; policy drop;
    oifname lo accept
  }
}
```

2. Configure the ruleset file properly and apply the changes
3. Restart and you have a valid firewall
4. Modify the ruleset file to have a problem, e.g. add `add chain ip this_table_does_not_exist somechain`
5. Apply the changes, check that they have not been applied with `nft list ruleset`
6. Restart, and see that you have no firewall.

### Expected behavior
Rules are not cleared if the service fails.

Not sure what the proper strategy is regarding the firewall silently dying in the background; possibly some recovery mechanism to attempt to rollback to a previous successful configuration.
Personally I setup a network-manager hook that requires the service to exist before any network interface can go online.

### Additional context
I'm not that versed in network administration, so if this is intended behaviour please close this ticket, but it seemed surprising to me.

Personally I resolved this (mostly) for myself but I thought I would mention it just incase it affects anyone else.
To fix it for myself I overwrote the shutdown hook to prevent rules being deleted:
 ``` Nix
systemd.user.services.nftables.serviceConfig.ExecStop = lib.mkForce "";
```
And added a network-manager hook to require the nftables service to be running before interfaces can come online:
```Nix 
  environment.systemPackages = with pkgs; [ networkmanager ];
  networking.networkmanager = {
    enable = true;
    dispatcherScripts = [ {
      # Prevent interface up if no firewall
      source = pkgs.writeText "assertFirewallForNIfUp" ''
        if ! $(systemctl is-active nftables --quiet service); then
          ip link set $1 down
        fi
        '';
        type = "pre-up";
    }];
  };
```

### Notify maintainers
@Izorkin 
@ajs124 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.740.7a6a010c3a1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"home-manager, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ajs124** [comment]
I don't actually use that module, just the package.

Although https://github.com/NixOS/nixpkgs/pull/203606 might solve this issue.

**Comment by Izorkin** [comment]
What script did generated in `ExecReload` and `ExecStart`?
Should be like this:
```
cat /nix/store/iy6favanxwy8m141fcvbs1kvr1yk7286-nftables-rules
```
```
#! /nix/store/42bkki7pnmd9x94bhi5dwlacyq8w7p56-nftables-1.0.5/bin/nft -f
flush ruleset
include "/nix/store/ph2jwddg39j76k7vzndf1hq5vigbhq6g-nftables-rules"
```

Before applying any rule changes, all previous ones are automatically flushed.

**Comment by richousrick** [comment]
@Izorkin Both reference the same file which looks like you said. 

But applying the system (without restarting) after a change to the ruleset file does not seem to trigger the nftables service to restart.

I noticed that if I make a change to `nftables.ruleset`, and apply the system (Using `nixos-rebuild switch` ) I get an additional line output `reloading the following units: nftables.service`.

However if I make a change to the rulset file (and dont change the `nftables.rulesetFile` variable) applying does not lead to this line being output.

**Comment by Izorkin** [comment]
NixOS cannot automatically track changes in the ruleset file.
It's best to write rules in a nix file. Example:
```
  networking = {
    nftables.ruleset = ''
      table inet filter {
        chain INPUT {
          type filter hook input priority filter; policy drop;
...
        }
        chain OUTPUT {
          type filter hook output priority filter; policy accept;
        }
        chain FORWARD {
          type filter hook forward priority filter; policy drop;
        }
      }
    '';
  };

```

**Comment by richousrick** [comment]
Ahh sorry, I was not aware of that. 
Did I misunderstand the documentation, or is it incorrect where it says that the ruleset will be updated atomically?
https://github.com/NixOS/nixpkgs/blob/0938d73bb143f4ae037143572f11f4338c7b2d1c/nixos/modules/services/networking/nftables.nix#L94

I read that as meaning that the changes will be automatically applied after rebuild, not after restart.

**Comment by Izorkin** [comment]
The difference is that when using `rulesetFile`, NixOS does not keep track of changes in firewall rules, so the nftables service is not restarted automatically. Probably, did not encounter such a situation and did not mention it in the documentation.

**Comment by richousrick** [comment]
Ok.
Sorry for taking up your time.

Should the documentation be updated to reflect that behaviour?

**Comment by Izorkin** [comment]
> Should the documentation be updated to reflect that behaviour?

Yes, if possible :)

**Comment by richousrick** [comment]
Thank you.

What should I do regarding this ticket?

**Comment by Izorkin** [comment]
Open PR first. After the merge, the ticket can be closed.

**Comment by ajs124** [comment]
Ah, so this is only an issue if `rulesetFile` isn't a storepath? So your usecase where you have the file separately would probably be fixed by doing `networking.nftables.rulesetFile = ./netfilter;` instead of `networking.nftables.rulesetFile = toString ./netfilter;`.

**Comment by duament** [comment]
> 6. Restart, and see that you have no firewall.

You should reload `nftables.service` instead of restarting it.

**Comment by richousrick** [comment]
Sorry for the late response.

@ajs124 
>  your usecase where you have the file separately would probably be fixed by doing networking.nftables.rulesetFile = ./netfilter; instead of networking.nftables.rulesetFile = toString ./netfilter;.

This solved that issue; really sorry, for some reason I thought that it was expecting a string.

@duament I meant restart the system.

**Comment by ajs124** [comment]
don't worry, the nix language and nixos module system can be quite tricky, sometimes

**Comment by richousrick** [comment]
Cheers,

Considering there is a MR (#207758) that seems to cover the main issue, and the rest is user error. I'll close this ticket, unless anyone has any reason for me not to ... ?
