### ISSUE TITLE
Setup of Rmilter and Rspamd for spam filtering?

### ISSUE THREAD

**Issue by mikael-andersson** [NixOS/nixpkgs#20715]
## Issue description

I am trying to setup up some simple spam filter on my local machine and will interact with it from my email client MU4E in Emacs. Can anyone provide some information about how to setup these? I can probably figure out how to use the client from Emacs, but if you can help out with setting up the server parts, I would be happy.

I was first thinking about setting up Spamassassin but when I found out about Rmilter and Rspamd I thought I would give it a try. Do you have any recommendations for one or the other?

On this page https://rspamd.com/doc/quickstart.html#rmilter-setup, I read "...install rmilter package instead of rspamd...".

What I understand, since they on the above page and here https://rspamd.com/doc/quickstart.html#running-rspamd say that both daemons must be run, I suppose I need to set these to true:
services.rmilter.rspamd.enable
services.rspamd.enable

Is this right?

What I undersstand I need to install both rmilter and rspamd packages, since the latter contains the client rspamc.

It would be great if someone can clarify things for me, thanks. :)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.1062.daed850 (Flounder)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.1062.daed850"

**Comment by Mic92** [comment]
Rmilter seems to open a unix socket at `/run/rmilter/rmilter.sock`, there is also an option to listen on tcp, but is not enabled by default: `services.rmilter.bindInetSockets`. Rmilter also seems to be configured to use Rspamd if both are enabled.

**Comment by joachifm** [comment]
cc @avnik as the original contributor

**Comment by fpletz** [comment]
### General rspamd/rmilter usage with NixOS on a mail server

For quickly checking out rspamd/rmilter with postfix you can use the following NixOS config snippet:

```
  services.rspamd.enable = true;
  services.rmilter = {
    enable = true;
    socketActivation = false;
    rspamd.enable = true;
    postfix.enable = true;
  };
```

The config above adds the recommended milter config snippet for rmilter into postfix's main.cf.

You can also integrate rspamc for learning spam and ham for example into dovecot with the antispam plugin like this:

```
  services.dovecot2 = {
    enable = true;
    enableImap = true;
    enablePop3 = false;
    modules = with pkgs; [ dovecot_antispam ];
    extraConfig = ''
      # … other config …

      protocol imap {
        mail_plugins = $mail_plugins antispam
      }

      plugin {
        antispam_backend = mailtrain
        antispam_spam    = Junk
        antispam_trash   = Trash
        antispam_mail_sendmail = ${pkgs.rspamd}/bin/rspamc
        antispam_mail_spam     = learn_spam
        antispam_mail_notspam  = learn_ham
        antispam_mail_sendmail_args = -h;localhost:11334;-P;q1
      }
    '';
  };
```

### Local usage

If you want to use rspamd locally, you just have to enable the service. rmilter is not needed if you don't have to integrate into a MTA that support the milter protocol. You can use the tool rspamc to talk to rspamd to check mail for spam and learn spam/ham. You can probably set this up in your MUA pretty easily.

**Comment by avnik** [comment]
```
    rspamd.enable = true;
    rmilter.postfix.enable = true;
```
Snippet with milter socket will be add to postfix automatically.

@fpletz ``socketActivation=true;`` need for proper permissions, if you use domain socket.

Also on local usage:
```
    rmilter.rspamd.extraConfig = ''
      spamd_never_reject = true;
    ''
```
if you want to just mark spam, and not reject it (important if you forward mail from external MX to local host, otherwise spam will be bounced, not rejected)

**Comment by mikael-andersson** [comment]
Many thanks for your replies. I have not had time to look into it yet but I hope I have time in the coming week. I will report back to you.

**Comment by avnik** [comment]
btw, newer rspamd have built-in milter, so I have plans to deprecate/abandon rmilter.

**Comment by fpletz** [comment]
@avnik Before we do the same work twice: I've already wrote code for rspamd proxy support and have it running. I have yet to rebase and fix conflicts because my changes are based on 17.09.

**Comment by avnik** [comment]
@fpletz you plan to pose rspamd as smtp proxy, not milter?

**Comment by fpletz** [comment]
The proxy worker has milter support: https://rspamd.com/doc/workers/rspamd_proxy.html :smile:

**Comment by avnik** [comment]
On Wed, Feb 28, 2018 at 03:29:17PM +0000, Franz Pletz wrote:

> The proxy worker has milter support: https://rspamd.com/doc/workers/rspamd_proxy.html :smile: 
> 

If you about self-scan, and you have some working code -- proceed with
it ;)
