### ISSUE TITLE
[pkg-request] julia: upgrade stable from 0.4.6 to 0.5.0

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#20714]
## Issue description
It has been a while since julia 0.5.0 is stable (2 months now). Julia git cannot be used because of the "-dev" added to the version number that leads to bug like this in Compat: https://github.com/JuliaLang/Compat.jl/issues/241

I've checked out julia-git to 3c9d75391c72d7c32eea75ff187ce77b2d5effc8 and it does work (except for #19472 that needs LD_LIBRARY_PATH to be fixed)

Thanks

**Comment by 7c6f434c** [comment]
Hm, correctly upgrading to 0.5.0 is not trivial…

**Comment by 7c6f434c** [comment]
5d5346d824fdf19d5ac879bb4c98e6381d41c76d contains some approximation…

**Comment by nico202** [comment]
Closing since there's 0.6.0
