### ISSUE TITLE
Frequent Firefox crashes: error marshalling arguments for activate (signature so): null value passed for arg 1

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#207121]
### Describe the bug

Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1806856. So far has only affected NixOS users based on the signature (or the signature may just be unique to NixOS in general).

### Notify maintainers

@lovesegfault  @mweinelt

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05pre435935.04f574a1c0f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(kevincox): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by kevincox** [comment]
This is occurring on the 108.0.1 build but doesn't appear to be occurring on 108.0.

**Comment by mweinelt** [comment]
Does this affect `firefox` or `firefox-bin`? I see `109.0b4` in the crash-stats and we only have binary packages for that version.

**Comment by kevincox** [comment]
I saw it on `firefox` but other users may be using `firefox-bin` 🤷

**Comment by kevincox** [comment]
Interesting that there are examples on 108.0. I've been using that for a week or so and didn't see any crash. However after upgrading I saw very frequent crashes. Maybe every 5-15min.

**Comment by supermarin** [comment]
Same here, 108.1 both firefox, firefox-bin and firefox developer edition.

**Comment by Darkspirit** [comment]
This should be [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1802327#c5) in 109 (beta) and later (https://nightly.mozilla.org).

**Comment by supermarin** [comment]
hm, thought I saw it on 109 developer edition, but could be wrong. Will follow up here if I ever see it again.

**Comment by Darkspirit** [comment]
You can see your crash reports on about:crashes.

**Comment by mweinelt** [comment]
> This should be [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1802327#c5) in 109 (beta) and later ([nightly.mozilla.org](https://nightly.mozilla.org)).

Firefox 109 is due on 2023/01/17.

**Comment by supermarin** [comment]
Hm, reports are mixed between browsers but these are versions I'm seeing 108.0.1, 108.0b9.
Not sure why I thought I was running a 109 beta. Hopefully won't see this anymore after 109!

**Comment by kevincox** [comment]
I'm going to optimistically close this. The nixos-unstable channel has only been updated for a few hours but I've been running 109 since then without a crash which is very statically significant for my machine. I also don't see any crashes reported for 109 yet: https://crash-stats.mozilla.org/signature/?product=Firefox&signature=libwayland-client.so.0%400xb989
