### ISSUE TITLE
Inkscape won't run, can't load libpoppler.

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#207117]
### Describe the bug

Inkscape fails to run. the error message is

```
inkscape: error while loading shared libraries: libpoppler.so.125: cannot open shared object file: No such file or directory
```

### Steps To Reproduce
1. Include `inkscape` in `environment.systemPackages`.
2. `sudo nixos-rebuild switch --upgrade`
3. Launch inkscape.

### Expected behavior

Inkscape should launch OK.

### Screenshots

Not applicable.

### Additional context

I see [here](https://github.com/NixOS/nixpkgs/commit/3b3f77b1815388c6a320265ea4262dadb47914ed) that some libpoppler stuff was removed recently.

### Notify maintainers
@jtojnar 

### Metadata

```console
✦ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 23.05 (Stoat), 23.05pre435935.04f574a1c0f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Do you perhaps have `LD_LIBRARY_PATH` environment variable in your environment?

**Comment by mhwombat** [comment]
No. Should I?

**Comment by jtojnar** [comment]
No. Nix packages should be self-contained, listing paths to libraries in `DT_RUNPATH` entry in ELF. Some environment variables like `LD_LIBRARY_PATH` can interfere with that.

**Comment by bjornfor** [comment]
inkscape launches fine for me (NixOS) on nixpkgs branch `nixpkgs-unstable` and `nixos-22.11`.

**Comment by mhwombat** [comment]
I just did a nixos-rebuild, but it's still not working for me. Same error message. I'm on `nixos-unstable`.

**Comment by mhwombat** [comment]
Did another nixos-rebuild today, and the problem has vanished.
