### ISSUE TITLE
dvorak keymap test fails

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#207181]
### Describe the bug

The dvorak test is failing.

### Steps To Reproduce

Build https://hydra.nixos.org/build/202787191

Copy of the log 
[4gfnq33lz3i8g6qyq9a64491s984p8wz-vm-test-run-keymap-dvorak.drv.txt](https://github.com/NixOS/nixpkgs/files/10282601/4gfnq33lz3i8g6qyq9a64491s984p8wz-vm-test-run-keymap-dvorak.drv.txt)

### Expected behavior

Dvorak works, test works, channel progresses.

### Notify maintainers

Test has no maintainers.

```
nix-repl> nixosTests.keymap.dvorak.meta.maintainers
[ ]
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by vcunat** [comment]
All keymap tests have been flaky for quite a long time.  I don't know why.  Restarting them helps, e.g. the build linked above succeeded on the second attempt.

**Comment by vcunat** [comment]
Speaking of blockers here's a current one: https://github.com/NixOS/nixpkgs/pull/206286#issuecomment-1362528344

**Comment by aszlig** [comment]
> All keymap tests have been flaky for quite a long time.

@vcunat: You don't happen to know the rough time frame when they became flaky?

**Comment by vcunat** [comment]
No, I can't recall.  Practically it became worse because we added `aarch64-linux` to standard `tested` jobs, so the number of keymap tests doubled.

**Comment by aszlig** [comment]
@vcunat: Yeah, I can see why this gets a lot more annoying. Is the flakiness exclusively for the `openvt`-tests or the `xdotool`-ones as well?

**Comment by aszlig** [comment]
Tried to reproduce it via the following (mainly for myself as a reference when switching locations) and didn't get a single failure after several runs:

```nix
let
  origTest = (import nixos/tests/keymap.nix {}).dvorak;
in builtins.genList (num: origTest.hostPkgs.stdenv.mkDerivation {
  name = "${origTest.name}-${toString num}";
  buildCommand = ''
    mkdir -p $out
    LOGFILE=/dev/null ${origTest.driver}/bin/nixos-test-driver -o $out
  '';
}) 100
```

I'm guessing that the build nodes were on high load, so need to employ a different strategy...

**Comment by vcunat** [comment]
We might run smaller amount of them; that should be easy.  I don't know why it's useful to run it on so many keymaps.

**Comment by roberth** [comment]
Or a larger amount with more logging so we can find the cause.

**Comment by roberth** [comment]
Also not all hardware is equal. Maybe keep track of hostnames?

**Comment by roberth** [comment]
I've found a fix that runs the test dozens of times without issue on a machine that otherwise reproduces the issue fairly reliably.
 - #207563
