### ISSUE TITLE
ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by retrry** [NixOS/nixpkgs#20716]
## Issue description
I get this error, when using creating dev environment with nix-shell. How should I go about fixing it?
My default.nix file:
```
with import <nixpkgs> {}; {
    pythonEnv = stdenv.mkDerivation {
        name = "foo";
        buildInputs = [
            stdenv
            libxml2
            libxslt
            vim
            bashInteractive
            python34
            python34Packages.pew
        ];
        shellHook =
        ''
        export SHELL=${bashInteractive}/bin/bash
        pew mktmpenv -r requirements/dev.txt
        '';
    };
}
```

Python requirements/dev.txt file:
```
# requirements/dev.txt
celery>=4.0.0
flower>=0.9.1
requests>=2.12.1
lxml>=3.6.4
pylint>=1.6.4
pep8>=1.7.0

```
Pinging @domenkozar and @FRidh as I know they maintain Python infrastructure.
### Steps to reproduce
Run command nix-shell --pure with given files.

## Technical details

* System: 17.03pre95306.a24728f (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre95306.a24728f

**Comment by FRidh** [comment]
See section 8.10.3.4 in the manual. You need to set SOURCE_DATE_EPOCH.

**Comment by retrry** [comment]
Thanks and sorry that I missed it.

**Comment by vcunat** [comment]
There's also `ensureNewerSourcesHook`, which has the advantage of producing always the same timestamps (but for shell envs you probably don't care).

**Comment by drupol** [comment]
Sorry to dig up old topics, but I have this issue with Python 3.10.

![image](https://user-images.githubusercontent.com/252042/209678646-914676bf-4ff1-405a-a6cb-5d4d0e0fa996.png)

There's also a new post on Discourse about this: https://discourse.nixos.org/t/using-pip-in-a-nix-shell-source-date-epoch-not-helping/
