### ISSUE TITLE
Allow root login with password into installation image

### ISSUE THREAD

**Issue by bachp** [NixOS/nixpkgs#20718]
## Issue description

I was trying to get access to a nixos installer image via ssh. However I'm not able to login even after enabling sshd and setting a password.

I assume by setting `permitRootLogin = "yes";` for the generated installer ISO would allow to enable SSH via the steps described below would be an improvement.

### Steps to reproduce

1. boot the nixos installation iso for 17.03-pre
2. enable sshd with `systemctl start sshd`
3. set a password for root with `passwd`
4. try to login from another machine via `ssh root@your-machine.local`
5. login is not possible with the password set.

## Technical details

* System: NixOS 17.03pre95306.a24728f (Gorilla)nix
* Nix version: 1.11.4
* Nixpkgs version: -

**Comment by cleverca22** [comment]
nixos-rebuild can be used to flip that on, but i do agree that defaulting to allow it would be better for the ISO images

**Comment by fpletz** [comment]
I'm using SSH keys in this case. As a workaround and if you don't have your pubkeys hosted anywhere you can just use Github and do something like:

    mkdir ~/.ssh; curl https://github.com/bachp.keys > ~/.ssh/authorized_keys

But I also agree that password authentication for root should be enabled in installer images by default. It should be even safe by default because root doesn't have a password set by default. :+1:

**Comment by bachp** [comment]
@fpletz That's a neat trick 👍 

I don't see a problem either with allowing it. As far as I can tell you have to start sshd manually anyway.

**Comment by cleverca22** [comment]
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/installation-device.nix#L48
