### ISSUE TITLE
Package request: Fly-Pie is an innovative marking menu written as a GNOME Shell extension. 

### ISSUE THREAD

**Issue by Birdthatcantfly** [NixOS/nixpkgs#207103]
**Project description**
Fly-Pie is an extension for GNOME Shell which lets you open marking menus via keyboard shortcuts. And — to the best of my knowledge — it is the [first GNOME Shell extension with achievements](https://www.youtube.com/watch?v=Lj-uefp36Jk)! trophy

You can use it to launch applications, simulate hotkeys, open URLs and much more. It features a continuous learning curve which lets you gradually lift-off from a grumpie menu rookie to a snappie menu pielot.

**Metadata**

* homepage URL: http://schneegans.github.io/tags/fly-pie/
* source URL: https://github.com/Schneegans/Fly-Pie
* license: mit
* platforms: linux

**Comment by jackwilsdon** [comment]
It seems like this is already packaged. It was disabled a while back but has been re-enabled as of #274080.

**Comment by cyplo** [comment]
closing as now available
