### ISSUE TITLE
llvm package has broken symbolic link libLLVM.so

### ISSUE THREAD

**Issue by andrewrk** [NixOS/nixpkgs#20723]
After updating to 17.03.git.a24728f (Gorilla):

```
andy@xps ~/d/zig> file /nix/store/p4l83x4zijag969n8phhvl7zj8qhn1yp-llvm-3.9.0/lib/libLLVM.so
/nix/store/p4l83x4zijag969n8phhvl7zj8qhn1yp-llvm-3.9.0/lib/libLLVM.so: broken symbolic link to libLLVM-3.9.so
```

This breaks the build for projects looking for libLLVM.so.

**Comment by andrewrk** [comment]
cc @lovek323 @viric @vcunat @gebner @acowley

**Comment by vcunat** [comment]
Note: if someone's searching for it there explicitly, it's a bad location.

**Comment by vcunat** [comment]
If you need a quick fixup, you can apply the patch below. I want to eradicate such surprises globally, which will require a stdenv rebuild.

```diff
diff --git a/pkgs/development/compilers/llvm/3.9/llvm.nix b/pkgs/development/compilers/llvm/3.9/llvm.nix
index 8086f98..378aa2e 100644
--- a/pkgs/development/compilers/llvm/3.9/llvm.nix
+++ b/pkgs/development/compilers/llvm/3.9/llvm.nix
@@ -88,8 +88,8 @@ in stdenv.mkDerivation rec {
 
   postInstall = ""
   + stdenv.lib.optionalString (enableSharedLibraries) ''
-    moveToOutput "lib/libLLVM-*" "$lib"
     moveToOutput "lib/libLLVM.${shlib}" "$lib"
+    moveToOutput "lib/libLLVM-*" "$lib"
     substituteInPlace "$out/lib/cmake/llvm/LLVMExports-release.cmake" \
       --replace "\''${_IMPORT_PREFIX}/lib/libLLVM-" "$lib/lib/libLLVM-"
   ''
```

**Comment by andrewrk** [comment]
> Note: if someone's searching for it there explicitly, it's a bad location in any case. (EDIT: that doesn't mean I won't fixup the failure to move the link.)

Here's how I'm finding it:

https://github.com/andrewrk/zig/blob/master/cmake/Findllvm.cmake#L32

Seems pretty innocuous to me.

In fact I'm surprised this didn't break more things. I'm pretty sure this is the best way to link against LLVM on nixos. For example if clang did it then we would probably make clang faster on nixos (See #19195)

Thanks for the quick fixup! I'm using the fixup to work on the project in a nix-shell :+1:
