### ISSUE TITLE
grsec: Switch to paxctl-ng.

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20729]
## Issue description
paxctl doesn't support XATTR flags; only PT flags. paxctl-ng supports both. XATTR flags live in the filesystem; PT flags live in the ELF header.

See [here](https://wiki.gentoo.org/wiki/Hardened/PaX_Quickstart#paxctl-ng) for a guide!

**Comment by joachifm** [comment]
For use with Nix, ELF header markings are the only reliable way of doing this. There's no provision for transmitting xattrs via nar, as far as I can tell. What is more, the fact that xattrs are even permitted in the store is considered an oversight iirc.

**Comment by spacekitteh** [comment]
>What is more, the fact that xattrs are even permitted in the store is considered an oversight iirc.

Why?

**Comment by joachifm** [comment]
https://github.com/NixOS/nix/issues/185#issuecomment-30861622
