### ISSUE TITLE
Documentation for `boot.loader.timeout` doesn't match behavior in `iso-image.nix`

### ISSUE THREAD

**Issue by n8henrie** [NixOS/nixpkgs#207289]
## Problem

The behavior [documented](https://github.com/NixOS/nixpkgs/blob/cbe419ed4c8f98bd82d169c321d339ea30904f1f/nixos/modules/system/boot/loader/loader.nix#L16) for `boot.loader.timeout` is that `null` should display the loader menu indefinitely, but it looks like [setting it to null leads to a timeout of `0`](https://github.com/NixOS/nixpkgs/blob/2379de680d8c7d652cfc9a94b7e42691846c70a4/nixos/modules/installer/cd-dvd/iso-image.nix#L74), which [according to the syslinux docs](https://wiki.syslinux.org/wiki/index.php?title=SYSLINUX#TIMEOUT_timeout) should "disable the timeout" (which I interpret as meaning "boot immediately without waiting").

`null` should probably instead go to `35996`, which is the maximum allowable timeout, to be in keeping with the documentation. Either that, or the documentation should be updated.

- Additional discussion at my PR review here: https://github.com/NixOS/nixpkgs/pull/204669#pullrequestreview-1221614770
- Related PR for systemd-boot: https://github.com/NixOS/nixpkgs/pull/201202

## Checklist

- [ ] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [ ] checked [open documentation issues] for possible duplicates
- [ ] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

As per above, it would be nice if the meaning of `boot.loader.timeout` were as consistent as possible across bootloaders, perhaps with the documentation guiding expected behavior and the implementation doing its best to match.

Current documentation says `null` should mean `wait forever`, so I'm going to change <https://github.com/NixOS/nixpkgs/pull/204669> to match and submit a PR to update syslinux to match as well.

**Comment by n8henrie** [comment]
Perhaps should also update the documentation to say "forever **or as long as possible**"?

**Comment by CyberShadow** [comment]
> which I interpret as meaning "boot immediately without waiting"

@n8henrie  I don't think that's correct. See these lines in the syslinux source code:

> `    /* Note: for both key_timeout and timeout == 0 means no limit */`

and

> `while (!cm->timeout || timeout_left) {`

**Comment by n8henrie** [comment]
@CyberShadow yes, it looks like you're right -- I should have done more dd.

https://github.com/NixOS/nixpkgs/pull/207290 should probably be reverted (or possibly just `s/35996/0/').

Opened https://github.com/NixOS/nixpkgs/issues/327122
