### ISSUE TITLE
Configuring airscan (sane) stopped working

### ISSUE THREAD

**Issue by liketechnik** [NixOS/nixpkgs#207262]
### Describe the bug

Configuring airscan by writing to `/etc/sane.d/airscan.conf` via `environment.etc` silently does nothing, i. e. the file still has the default content.

### Steps To Reproduce

1. Add airscan to sane backends:
```
hardware.sane.extraBackends = [ pkgs.sane-airscan ];
```
2. Configure airscan, e. g. specific devices:
```
etc.environment."sane.d/airscan.conf".text = ''
  [devices]
  Epson@Home = http://192.168.178.55:443/eSCL/, eSCL
'';
```

### Expected behavior
After `nixos-rebuild switch` (or `boot` & reboot, etc) `/etc/sane.d/airscan.conf` should contain 
```
[devices]
Epson@Home = http://192.168.178.55:443/eSCL/, eSCL
```

### Additional context

This stopped working when upgrading from 22.05 to 22.11. I suspect the change to the `sane` module in #199667 is the root cause.

### Notify maintainers

I didn't find a `meta.maintainers` entry in the sane module, so excuse me pinging the last few people who touched the module / were involved in the discussion of #199667:

@bjornfor @symphorien 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix run "nixpkgs-unstable#nix-info" -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.75-xanmod1, NixOS, 22.11 (Raccoon), 22.11.20221208.7a6a010`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
Since this worked before, doesn't that mean airscan isn't using `$SANE_CONFIG_DIR`, and instead hardcodes `/etc/sane.d`?

**Comment by bjornfor** [comment]
@liketechnik: You can use this workaround for now:

```
  hardware.sane.extraBackends = [
    (pkgs.runCommand "local-sane-airscan.conf" {} ''
      mkdir -p "$out/etc/sane.d"
      cat >"$out/etc/sane.d/airscan.conf" << EOF
      [devices]
      Epson@Home = http://192.168.178.55:443/eSCL/, eSCL
      EOF
    '')
  ];
```

**Comment by bjornfor** [comment]
> Since this worked before, doesn't that mean airscan isn't using `$SANE_CONFIG_DIR`, and instead hardcodes `/etc/sane.d`?

According to `man sane-airscan` it's using the enviroment variable `$SANE_CONFIG_DIR` first, then falling back to `/etc/sane.d`.

I guess that means in nixos 22.05 it was reading both the airscan.conf found in $SANE_CONFIG_DIR (/nix/store/...) and then also /etc/sane.d/airscan.conf?

I guess we can bring back the old behaviour by just pointing `$SANE_CONFIG_DIR` to `/etc/sane-config` or something instead of `/etc/sane.d`. Thoughts?

**Comment by bjornfor** [comment]
I made https://github.com/NixOS/nixpkgs/pull/207279.

**Comment by liketechnik** [comment]
> Btw, you wrote etc.environment (wrong order) in the first post :-)

Oops, I should start to copy paste this option, I always mess up the order

> You can use this workaround for now:

That is a lot cleaner than what I came up with. Thanks.

> I made https://github.com/NixOS/nixpkgs/pull/207279.

Wow, that was fast. Again, many thanks to you :)
