### ISSUE TITLE
builds.sr.ht still have NixOS 22.05 and not 22.11

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#207331]
### Describe the bug

builds.sr.ht is still using NixOS 22.05 which will be EOL soon.

### Notify maintainers

@fgaz

**Comment by fgaz** [comment]
I've had a lot on my plate recently so I delayed the update. If you'd submit a patch you'd do me a favor. Otherwise I guess I'll do it myself after Christmas.

This isn't really a nixpkgs issue and should probably go in the sourcehut mailing list or issue tracker instead.

**Comment by RaitoBezarius** [comment]
Apologies for submitting it here, will try to see if I can submit the patch for you.

**Comment by fgaz** [comment]
Thanks! Instructions are [here](https://man.sr.ht/builds.sr.ht/image-maintenance.md), please do not remove 22.05 until it reaches EOL

**Comment by winterqt** [comment]
As this isn't a Nixpkgs issue (since we don't officially maintain the builds.sr.ht image), I'm going to close this. Thanks to you both, though! :)
