### ISSUE TITLE
tensorflow: protobuf-3.0.0-beta-2 not supported for interpreter python3.5m

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#20738]
## Issue description

Trying to install `python35Packages.tensorflow`, I get the following error:

```
error: protobuf-3.0.0-beta-2 not supported for interpreter python3.5m
```

### Steps to reproduce

Add the package to `environment.systemPackages` and then `nixos-rebuild switch --upgrade`.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
# nixos-version
17.03pre95306.a24728f (Gorilla)
```

* Nix version: (run `nix-env --version`)

```
# nix-env --version
nix-env (Nix) 1.11.4
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre95306.a24728f"
```

**Comment by FRidh** [comment]
Occasionally packages are not supported on certain interpreter versions either by upstream, or by our maintainer. In such cases the packages are explicitly disabled for these interpreter versions.

In this case `disabled = isPy3k || isPyPy;` was added to the function that builds the `protobuf` Python package. I don't know whether `protobuf` works on Python 3.x. Does it? If so, the expression can be fixed.

If you want to see this package working with Python 3.x I suggest opening a PR instead.

**Comment by tindzk** [comment]
I encountered the same problem. You could try out my updated TensorFlow package from https://github.com/NixOS/nixpkgs/pull/20794. It is compatible with Python 2 and 3.
