### ISSUE TITLE
nixpkgs missing packages on macOS. "matches no derivations"

### ISSUE THREAD

**Issue by KentJames** [NixOS/nixpkgs#20737]
## Issue description

Variety of packages not available on macOS. (Can neither see with nix-env -qA, or install with nix-env -i)

### Steps to reproduce

Attempt to install gnu chess and xboard on my OSX(macOS 10.12.1) machine as part of a transition to nix for package management, and trying to mirror my home-brew setup. Despite xboard and gnuchess being available in nixpkgs and easily installed on my other development computer(CentOS 7)

All packages work fine through home-brew, so it is certainly a nixpkgs problem.

Example:

CentOS:
[XXX]>nix-env -qa 'xboard.*'
xboard-4.9.1

macOS:

XXX$ nix-env -qa 'xboard.*'
error: selector ‘xboard.*’ matches no derivations

Therefore install also fails. Other packages are affected like gnuchess. But some other packages like gnugo work just fine, so not too sure what the issue is here.

## Technical details

* System: macOS 10.12.1
* Nix version: 1.11.4
* Nixpkgs version: 17.03pre96205.8f63cc6

**Comment by 7c6f434c** [comment]
It is a package-by-package question.

Most packages have a set of platforms declared as supported. You can try `NIXPKGS_ALLOW_BROKEN=1 nix-env -iA gnuchess` to check whether it was an unlucky guess by the last person touching the platform set of the specific package not to add `darwin` or whether there are real problems with a specific package that need to be worked around.

When you find out, you can file specific complaints about specific packages. A pull request fixing a `darwin` build and not changing the `linux` hash has quite a large chance of acceptance…

**Comment by KentJames** [comment]
Allow broken worked fine, same with xboard. I'll open up a PR and submit.

Thanks very much!
