### ISSUE TITLE
`haskellPackages.gi-webkit2` doesn't build due to wrong javascriptcore dependency

### ISSUE THREAD

**Issue by teh** [NixOS/nixpkgs#20739]
## Issue description

`haskellPackages.gi-webkit2` doesn't build.

### Steps to reproduce

`nix-shell haskellPackages.gi-webkit2`

## Technical details

Current gi-webkit2 is looking for  `gi-javascriptcore` v4, so the correct dependencies would be: 

```
    gi-webkit2-fixed = haskell.lib.overrideCabal gi-webkit2 (drv:
      {
        libraryHaskellDepends = [
          base bytestring containers gi-atk gi-cairo gi-gdk gi-gio gi-glib
          gi-gobject gi-gtk gi-javascriptcore_4_0_6 gi-soup haskell-gi-base text
          transformers
       ];
      });
```

I'm filing an issue instead of a PR because I'm not super sure where these fixes go now. Will prepare branch if you're OK with putting this in configuration-common.

**Comment by srhb** [comment]
Can you make this into a PR without changing the name of the package? Using `overrideCabal super.gi-webkit2 ...`

**Comment by teh** [comment]
This is turning out to be too much work, so closing as "too much effort for what we gain".
