### ISSUE TITLE
google chrome mirror possibly down

### ISSUE THREAD

**Issue by jascase901** [NixOS/nixpkgs#20748]
## Issue description
Google chrome fails to download. Complains for 404 error

## Add google-chrome to pkgs in configuration.nix
environment.systemPackages = with pkgs; [
  google-chrome
  ...
];

## rebuild nix
nixos-rebuild switch 

## Technical details

[build.txt](https://github.com/NixOS/nixpkgs/files/614583/build.txt)

* System: 16.09.1119.ece0cea (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version:"16.09.1119.ece0cea"

**Comment by yamafaktory** [comment]
I am currently facing the same issue as @jascase901. We had this issue in the past too (unavailable mirrors).

**Comment by grahamc** [comment]
In https://github.com/NixOS/nixpkgs/commit/f74f42b1b10b9e1e0517d1483a46fe11f0abefaf I updated Google Chrome in 16.09, which should have fixed this issue. Closing for now, please comment if it isn't fixed in a day -- the update will take a bit of time to get through Hydra.
