### ISSUE TITLE
Update boehm-gc to 7.6

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#20753]
## Issue description
Currently there is a patch applies to boehm-gc when building on cygwin:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/boehm-gc/cygwin.patch

It would be nice if we can update boehm-gc to 7.6 without breaking it on cygwin, but I have no idea how to do this.
cc @garbas 

Thank you.

**Comment by sifmelcara** [comment]
By the way, the current way I build the new version of boehm-gc is a172266a83fda28dea376c83d24a5aaa873cf2ca. (a workaround for me)
It seems that the new version of boehm-gc requires libatomic_ops to be installed or have its source avaliable before building. The strange thing is `buildInputs = [ libatomic_ops ];` have no effect (libatomic_ops still cannot be found when configuring), so I use the latter approach.

**Comment by dezgeg** [comment]
It gets found when `pkgconfig` is added: https://github.com/dezgeg/nixpkgs/commit/6d786fe7259ce25ddccfc8ea62430534c5dd4f51
I checked the cygwin patch and at appears to be already applied in the 7.6 branch.

However, what's currently confusing me (if I'm looking at it right) is that the latest 7.6.x release doesn't appear to have a fix for this CVE: https://github.com/ivmai/bdwgc/issues/135

**Comment by nathan7** [comment]
@dezgeg The vuln isn't *new* though, is it? Unless it is, there's no real need to hold a version upgrade back.
