### ISSUE TITLE
Why does Jami have a custom ffmpeg?

### ISSUE THREAD

**Issue by Atemu** [NixOS/nixpkgs#207574]
## Issue description

I'm currently in the progress of [refactoring ffmpeg](https://github.com/NixOS/nixpkgs/pull/204198/). Why does Jami require a patched version? What's so special about it?

If it's just ffmpeg with hwaccel, we should provide that in regular plain old ffmpeg.  
What are the patches for?

cc @linsui

**Comment by linsui** [comment]
I don't know. I just do what upstream does. Jami in AUR uses the plain ffmpeg but I don't knew if it works well.

**Comment by Atemu** [comment]
If it's good enough for the AUR, I think we're fine doing the same here.

Thanks!
