### ISSUE TITLE
gnome-shell hangs occasionally during alt-tab

### ISSUE THREAD

**Issue by pwaller** [NixOS/nixpkgs#207539]
### Describe the bug

Rarely, gnome-shell hangs when using alt-tab. If I pkill gnome-shell over SSH or from a VT, I get back control of my system.

I've particularly encountered this while playing the game Beyond All Reason (which doesn't have full screen, the gnome-shell titlebar is visible at the top of the screen at all times). However, I have also encountered this while using firefox, vscode and a terminal window for the first time, none of them having any fullscreen-like behaviour.

### Steps To Reproduce
1. Use computer for a while
2. alt-tab

### Expected behavior

Alt tab should work.

### Screenshots

I don't have a screenshot of the stuck state, but the window selector UI widget is visible even with no keys pressed, and the screen is frozen in this state, the mouse can move, but the machine isn't responsive to inputs other than to switch to a VT.

### Additional context

There is nothing in dmesg to suggest a segfault.

### Notify maintainers

@nixos/gnome (I don't have a hint from the GitHub UI if I've written the team correctly, so pinging most recent maintainers from the list for good measure) @bobby285271 @maxeaubrey

### Metadata

I'm using a flake-based NixOS system on nixos-unstable @ 652e92b8064949a11bc193b90b74cb727f2a1405. 

```
$ gnome-shell --version
GNOME Shell 43.2
```

**Comment by AlanBlanchet** [comment]
Hello,

I have a screenshot of the bug. My screen get's stuck on this window... I can't do anything and have to hold the power button to restart...
Edit : I can press ALT+F3, login, enter `killall -3 gnome-shell`, ALT+F2 and the window causing the problem should have closed.

And it's happening more occasionaly I believe.

I'm on Ubuntu 22.04.3 LTS.
I'm using X11 as windowing system.
I have an RTX 2070 Mobile.
I'm using Gnome 42.9

![IMG20231223103308.jpg](https://github.com/NixOS/nixpkgs/assets/22567306/845e6251-47b6-4b12-9c9e-4909c006b7bd)

**Comment by pwaller** [comment]
I have not encountered this in a long time (years?), and the last report was a year ago, so I'm going to guess this is fixed or that I'm running in a configuration where it doesn't happen. Closing, but please comment (and link a new bug if needed) if you still encounter.
