### ISSUE TITLE
Remove buildFHSUserEnv from heroku

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#20752]
## Issue description

@peterhoeg to remove the use of ```buildFHSUserEnv``` from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/heroku/default.nix.

Prerequisites:

- [X] Merge https://github.com/NixOS/nixpkgs/pull/18532
- [ ] Fix https://github.com/NixOS/patchelf/issues/66

**Comment by rasendubi** [comment]
Fixed by #22341.
