### ISSUE TITLE
Forgejo

### ISSUE THREAD

**Issue by lolo-frank** [NixOS/nixpkgs#207601]
**Project description**
Forgejo is a soft-fork of Gitea. It provides an intuitive interface, light and easy hosting and a lot of builtin functionality.

**Metadata**

* homepage URL: https://forgejo.org/
* source URL: https://codeberg.org/forgejo/forgejo
* license: MIT
* platforms: darwin, linux

**Comment by RaitoBezarius** [comment]
https://github.com/NixOS/nixpkgs/pull/206493
