### ISSUE TITLE
NetClient a NetMaker client.

### ISSUE THREAD

**Issue by shakor0** [NixOS/nixpkgs#207654]
**NetMaker and NetClient**
Netmaker is a networking platform built on the groundbreaking WireGuard protocol. Netmaker unifies your hybrid/multi-cloud, edge, IoT, and Kubernetes environments.

**Metadata**

* homepage URL: https://www.netmaker.org/
* source URL: https://github.com/gravitl/netmaker/releases
* license: mit, bsd, gpl2+ , SSPL
* platforms: unix, linux, darwin, 

Would like to request a nix package for NetClient, but both NetMaker and NetClient would also be nice.

**Comment by shakor0** [comment]
Thanks for this fast fix!
Would it be possible to have netclient and netmaker as separate packages?
As netmaker is the server, netclient is the client.
Now it installs both and I think that is not really wanted on all client systems.

Thanks.

**Comment by pizzaandcheese** [comment]
someone split the netclient into its own package #244197 recently

> Thanks for this fast fix! Would it be possible to have netclient and netmaker as separate packages? As netmaker is the server, netclient is the client. Now it installs both and I think that is not really wanted on all client systems.
> 
> Thanks.
