### ISSUE TITLE
ld.gold is missing for `pkgsCross.riscv64.buildPackages.bintools`

### ISSUE THREAD

**Issue by NickCao** [NixOS/nixpkgs#207672]
### Describe the bug
Despite the bintools for riscv64-linux advertises the existence of ld.gold, it is actually missing.

### Steps To Reproduce
1. eval `pkgsCross.riscv64.buildPackages.bintools.bintools.hasGold`, returns `true`
2. build `pkgsCross.riscv64.buildPackages.bintools.bintools`
3. check the output, there is only `ld.bfd`, no `ld.gold`
4. repeat the same process for `aarch64-multiplatform`, `ld.gold` is both advertised and available.

### Expected behavior
Either `pkgsCross.riscv64.buildPackages.bintools.bintools.hasGold` evaluates to `false`, or `ld.gold` is available in `pkgsCross.riscv64.buildPackages.bintools.bintools`

### Notify maintainers

@Ericson2314 @lovesegfault

**Comment by trofi** [comment]
Looking at https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gold/configure.tgt;h=d6ea06c8b1ae84b2621263e94a0ef7511b1099a0;hb=HEAD `gold` is not supported on riscv64.

https://sourceware.org/PR27035 tracks it upstream. I don't expect progress implementing the support any time soon.

**Comment by NickCao** [comment]
Then we should accept the second solution: mark `pkgsCross.riscv64.buildPackages.bintools.bintools.hasGold` as false, we should also double check the availability of gold on other ELF platforms.
