### ISSUE TITLE
darktable 4.2 fails to build with nixpkg version of lensfun 0.3.95

### ISSUE THREAD

**Issue by paperdigits** [NixOS/nixpkgs#207610]
I'm updating the darktable package to the newly release version 4.2, but the build fails because now darktable explicitly doesn't support lensfun 0.3.95, which is the version packaged in nixpkgs.

lensfun 0.3.95 is (1) an alpha version at best, (2) is quite old, and (3) lensfun release 0.3.3 is newer (and compatible with darktable)

I don't mind packaging up lensfun 0.3.3, as I already carry an overlay for it on my system, but I'd like to work out whatever governance issues may arise before I put in that time.

TIA & happy holidays

@flokli  @goibhniu @flosse @mrVanDalo  @jtojnar

**Comment by jtojnar** [comment]
cc #207531

**Comment by flokli** [comment]
The update from 0.3.2 to 0.3.95 was included in ac91e6ae04ac014184bac9f29c0ceed4442c46c4, which links to https://github.com/NixOS/nixpkgs/pull/43754.

And https://github.com/NixOS/nixpkgs/pull/43754#issuecomment-887929942 already mentioned this shouldn't have happened (as it was a prerelease which wasn't flagged appropriately in repology) but there apparently never was a revert of that bump.

I think it'd make sense to change lensfun to 0.3.3, which is "their latest stable release", so https://github.com/NixOS/nixpkgs/pull/207531 looks like the right call to me.

**Comment by paperdigits** [comment]
https://github.com/NixOS/nixpkgs/pull/207531 is incomplete, as it'll use the wrong version XML files, since the XML files in master are v2 and release 0.3.3 requires v1. 

I am going to create a git repo that pulls the tarball from the website and checks it into git, which will provide the correct version of the xml files

or

we can run the conversion script on the profiles, as is done in the flatpak: https://github.com/flathub/org.darktable.Darktable/blob/master/org.darktable.Darktable.json#L68

**Comment by raspher** [comment]
@flokli @paperdigits still open but seems fixed. Is this still relevant?

**Comment by paperdigits** [comment]
No, darktable 4.6.x does not support that version of lensfun at all. It is an alpha version and was never officially released by the lensfun team. TBH it should've never been packaged.

I think we haven't changed it because it would impact people who are already using that version negatively.

I have an overlay version of the newer 0.3.4 if we are interested in packaging that.

**Comment by paperdigits** [comment]
Oops, we have changed it, this can be closed.
