### ISSUE TITLE
Succeeding pythonPackages opencv & netcdf4 not in binary cache

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nixpkgs#20764]
## Issue description
The two packages `pythonPackages.opencv` and `pythonPackages.netcdf4` build fine on my NixOS virtual machine. But hydra does not provide any binaries for these packages.
For netcdf4 I can find a page which states: "it was removed from the jobset": http://hydra.nixos.org/job/nixpkgs/trunk/python27Packages.netcdf4.x86_64-linux
And for opencv I cannot even find the pythonPackages one: http://hydra.nixos.org/search?query=opencv

As I rely on the binary cache on my machine this is a bit of a bummer for me. (Our admin did only provide me with a `/nix` symlink on my main machine instead of a mount and thus all local builds fail due to this impurity.)

What is the reason that those packages don't show up on hydra? How do jobs get on the http://hydra.nixos.org/jobset/nixpkgs/trunk jobset?

### Steps to reproduce
All the following commands start a successful build instead of fetching from cache.
```
nix-shell -p python27Packages.opencv
nix-shell -p python35Packages.opencv
nix-shell -p python27Packages.opencv3
nix-shell -p python35Packages.opencv3
nix-shell -p python27Packages.netcdf4
nix-shell -p python35Packages.netcdf4
```

## Technical details

* System: openSUSE 13.2
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre96125.a6f392a"

**Comment by FRidh** [comment]
Hydra jobs are based on the `release*.nix` files in https://github.com/NixOS/nixpkgs/tree/master/pkgs/top-level and
https://github.com/NixOS/nixpkgs/tree/master/nixos
For example, `nixpkgs/trunk` uses `pkgs/top-level/release.nix` as can be seen at http://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-configuration.

The larger package sets, like the Python package set, and Haskell package set, are by default not build. Only packages that are depended on will be build.

**Comment by FRidh** [comment]
(Also, how are you going to work with the packages then? `nix-shell` will work because it won't write to the store, but you cannot use `python.withPackages` unless you have the env built already on the other machine.)

**Comment by knedlsepp** [comment]
Ok. Currently I'm quite happy with only the `nix-shell` variant as most of the important compiled packages worked out of the box (numpy, pandas, ...). However it's unfortunate that the python bindings for the compiled packages opencv, netcdf, gdal, etc. are not on hydra.

**Comment by knedlsepp** [comment]
Ok. So as I understand they are not built by default, because of hardware limitations: https://github.com/NixOS/nixpkgs/commit/ccd1029f58a3bb9eca32d81bf3f33cb4be25cc66
While this is unfortunate, it does however answer my question, so I will close this.
