### ISSUE TITLE
google-crome no longer installs on stable

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#20762]
it seems the debian archive for `google-chrome-stable/google-chrome-stable_54.0.2840.90-1_amd64.deb`
is gone

`/nix/store/fd8b4p1x55ydzc45hy3bclbvaj00cnnc-google-chrome-stable_54.0.2840.90-1_amd64.deb.drv` cant be made

```
$ nixos-version
16.09.1026.5ddaca1 (Flounder)
$ nix-env --version
nix-env (Nix) 1.11.4
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.1119.ece0cea"
```

**Comment by vcunat** [comment]
See #20748.
