### ISSUE TITLE
packaging request: ocaml 5.0.0

### ISSUE THREAD

**Issue by moba1** [NixOS/nixpkgs#207640]
[OCaml 5.0.0 is released](https://ocaml.org/news/ocaml-5.0).
Would you package OCaml 5?

**Project description**
https://ocaml.org/about

**Metadata**

* homepage URL: https://ocaml.org/
* source URL:https://github.com/ocaml/ocaml/releases/tag/5.0.0
* license: LGPL v2.1
* platforms: unix, linux, darwin

**Comment by wegank** [comment]
We already have OCaml 5.0 through `ocaml-ng.ocamlPackages_5_0`, see #206361.
