### ISSUE TITLE
grafana started to listen globally by default instead of only on localhost (22.05 -> 22.11)

### ISSUE THREAD

**Issue by herbetom** [NixOS/nixpkgs#207769]
## Issue description

#191768 changed on which address Grafana listens by default. Previously (under 22.05) it was localhost only and it was necessary to explicitly adjust this if so desired. Now (with 22.11) Grafana is listening on all IPs.

Previously:

https://github.com/NixOS/nixpkgs/blob/79e63f30ed2ff36cd0d9c2f7dadae5925c1a65db/nixos/modules/services/monitoring/grafana.nix#L293-L297

```
[root@stats:~]# ss -tlnp | grep -E "State|grafana"
State  Recv-Q Send-Q Local Address:Port Peer Address:PortProcess                                                  
LISTEN 0      4096       127.0.0.1:3000      0.0.0.0:*    users:(("grafana-server",pid=774,fd=8))
```

New default is to listen on all IPs:
https://github.com/NixOS/nixpkgs/blob/becdf0edefcd52c13a60994f264f779b89bdf708/nixos/modules/services/monitoring/grafana.nix#L366-L370

```
[root@stats:~]# ss -tlnp | grep -E "State|grafana"
State  Recv-Q Send-Q Local Address:Port Peer Address:PortProcess                                                     
LISTEN 0      4096               *:3000            *:*    users:(("grafana-server",pid=286547,fd=11))
```

Without enabled (and properly configured) firewall this could result in situations where people are exposing their Grafana installation unintentionally.

@offline @fpletz @willibutz @globin @ma27 @Frostman @KFearsoff

## Technical details

```
[root@stats:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.77, NixOS, 22.11 (Raccoon), 22.11.1137.dac57a4eccf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
> Without enabled (and properly configured) firewall this could result in situations where people are exposing their Grafana installation unintentionally.

but the default settings should suffice to catch this, right?

**Comment by herbetom** [comment]
> but the default settings should suffice to catch this, right?

Yes, I would think so. Therefore not really dramatic in most cases.
