### ISSUE TITLE
freshrss installation is not working

### ISSUE THREAD

**Issue by Xyz00777** [NixOS/nixpkgs#207728]
### Describe the bug
Hi first sorry for not using the template the correct way, i hope its okay.
At the moment i try to install an freshrss instance on my system.
i have an first installed 22.05 and updated to 22.11 nixos system.
beside of there is no manual how to install it and what are pre requirements i have to need, here is my configuration file:
```
{ config, pkgs, ... }:

{
  services.freshrss = {
    enable = true;
    package = pkgs.freshrss;
    language = "en";
    defaultUser = "picard";
    passwordFile = "/run/secrets/freshrss";
    dataDir = "/var/lib/freshrss";
    baseUrl = "https://freshrss.localhost";
    virtualHost = "freshrss";
    database = {
      user = "spock";
      port = 3306;
      name = "freshrss";
      host = "localhost";
      tableprefix = "freshrss";
#      passFile = "/run/secrets/freshrss";
      type = "pgsql";
    };
  };
  services.postgresql = {
    enable = true;
    package = pkgs.postgresql;
    dataDir = "/mnt/postgresql1/";
    ensureDatabases = [ "freshrss" ];
    ensureUsers = [
      {
        name = "freshrss";
        ensurePermissions = {
          "DATABASE freshrss" = "ALL PRIVILEGES";
        };
      }
      {
        name = "superuser";
        ensurePermissions = {
          "ALL TABLES IN SCHEMA public" = "ALL PRIVILEGES";
        };
      }
    ];
    port = 3306;
  };
}
```

I have the following problem at the moment:
When i use the default dataDir directory (the one whos standing in the config atm) than freshrss can create the needed files and directorys but the systemd fails with the following error:
![freshrss_setup_fail](https://user-images.githubusercontent.com/52142054/209480745-ea096d31-d593-4fa8-b3cb-6a9c98e6018f.png)
and i dont come further anymore.

But when i use an complete other dataDir like "/mnt/freshrss/" (what i want to do) than i get the following systemd error:
![freshrss_setup_fail2](https://user-images.githubusercontent.com/52142054/209480914-0873b09c-a9ea-49a1-93f6-98f396e51a70.png)
the service is still not working (with the same error) even when i create the /mnt/freshrss/ folder and even when i give the folder 777 permission and give it the freshrss user and group.
![freshrss_setup_fail3](https://user-images.githubusercontent.com/52142054/209480987-2f8782bb-e601-4908-a821-dab775e8c2e3.png)

### Notify maintainers
@Stunkymonkey 

### Metadata
```console
[root@NCC-1031:/mnt]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 22.11 (Raccoon), 22.11.1105.9898811c658`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Stunkymonkey** [comment]
could you please verify the installation with `sqlite` first? After this we should debug the `postgresql`. I currently using the  sqlite successfully.

**Comment by Stunkymonkey** [comment]
and maybe have a look at: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/freshrss.nix the failure of `freshrss-update.service` is expected if the config is not working.

**Comment by Stunkymonkey** [comment]
looking at the first link something does not line up with the mysql und postgresql parameters...

**Comment by miangraham** [comment]
I just migrated from freshrss-via-container to the new nixos module myself and had a similar issue with a non-default dataDir causing permission breakage in the systemd.services. I was able to get around it with these tweaks:

```
  systemd.services.freshrss-config = {
    serviceConfig.ReadWritePaths = [ "/srv/freshrss" ];
  };
  systemd.services.freshrss-updater = {
    serviceConfig.ReadWritePaths = [ "/srv/freshrss" ];
  };
```

**Comment by Xyz00777** [comment]
@miangraham nice idea but sadly its not working, now i get other systemd errors :( 
![freshrss_setup_fail4](https://user-images.githubusercontent.com/52142054/209727539-6d6b7135-0d1a-4227-83f3-603e9fed4722.png)
i tried your systemd.service... at the start and also after my config, both didnt worked... could you provide me with an example of your config or at least try your config inside a fresh installed vm?
@Stunkymonkey with sqlite its working, but still not with an other file system path :(

**Comment by miangraham** [comment]
@Xyz00777 `/srv/freshrss` is my custom file path to put the data on a separate disk's existing mount. If you're using it as-is you probably don't have a directory there. You'll want something else that reflects your system. This is my entire related config, minus the extension additions which you don't need:

```
  services = {
    freshrss = {
      enable = true;
      baseUrl = "http://freshrss";
      dataDir = "/srv/freshrss/data";
      defaultUser = "ian";
      passwordFile = "/srv/freshrss/freshrss_admin_phrase";
    };
  };
  systemd.services.freshrss-config = {
    serviceConfig.ReadWritePaths = [ "/srv/freshrss" ];
  };
  systemd.services.freshrss-updater = {
    serviceConfig.ReadWritePaths = [ "/srv/freshrss" ];
    startAt = pkgs.lib.mkForce "hourly";
  };
```

Links to the whole thing in context:
https://codeberg.org/mian/nixos-config/src/branch/master/box/futaba/services.nix#L73-L80
https://codeberg.org/mian/nixos-config/src/branch/master/box/futaba/services.nix#L174-L182
https://codeberg.org/mian/nixos-config/src/branch/master/common/overlays-stable.nix#L9-L17

**Comment by Xyz00777** [comment]
It still dont create the folder automaticly and give it the correct user. also same permissions error than before.
its working when i manually create the /mnt/freshrss folder and give it to freshrss:freshrss.
greetings.

**Comment by miangraham** [comment]
> It still dont create the folder automaticly and give it the correct user

Correct, it does not. I have a pre-existing path that I've set up which is why I'm changing the default. If you need it configured for you, you should probably stick with the default setting.

**Comment by Stunkymonkey** [comment]
please have a look at #209254 and test it. I added a test for postgresql as well and tested the installation in a different directory.

**Comment by miangraham** [comment]
Nice! I'll try to test the perm change over the weekend.

**Comment by Xyz00777** [comment]
Nice to hear that :)
I will first be able to test that next week :/
