### ISSUE TITLE
elinks 0.16.0

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#207718]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: elinks

current version: 0.15.1
desired version: 0.16.0

###### Notify maintainers

maintainers: @iblech @gebner

###### Note for maintainers

https://github.com/rkd77/elinks/releases/tag/v0.16.0rc1
https://github.com/rkd77/elinks/releases/tag/v0.16.0

**Comment by iblech** [comment]
Thank you for bringing this to my attention :-) I just submitted a corresponding pull request.
