### ISSUE TITLE
Application launcher menu is not updated

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#20776]
## Issue description

The application launcher (KDE Plasma) is not updated, and therefore many links do not function anymore because they refer to old store paths.

## Technical details
NixOS at ff1c76e9ebf7268da04611cbbf7e14b4ddfcf732

**Comment by FRidh** [comment]
@ttuegel any idea what could have caused this?

**Comment by ttuegel** [comment]
Which version of KDE?

**Comment by FRidh** [comment]
KDE Frameworks 5.27.0

**Comment by ttuegel** [comment]
Have you logged out and logged back in? Have you run `kbuildsycoca5`?

**Comment by fstamour** [comment]
I noticed the same behaviour with KDE5 _and_ gnome3. But login-out and back in always fixed the problem. I never really complained as I often shutdown this computer (since it boots so quickly).

My guess is that if a package is installed which adds a *.desktop file, nix should somehow trigger the update of the desktopManager's cache.

**Comment by FRidh** [comment]
I restarted my computer, but that didn't have any effect. Also, it takes a long time to log out (5~25 seconds), even with an entirely empty desktop. `kbuildsycoca5` doesn't make a difference either.

**Comment by ttuegel** [comment]
I can reproduce half of this issue, specifically, restarting does not update the menu. However, running `kbuildsycoca5` manually *does* update the menu for me. `startkde` is supposed to run `kbuildsycoca5` during startup, so I think something is wrong there.

**Comment by FRidh** [comment]
I think I've seen this parse error before
```
$ kbuildsycoca5
kbuildsycoca5 running...
Reusing existing ksycoca
Recreating ksycoca file ("/home/freddy/.cache/ksycoca5_en_sUSppqk9Rzy0lXtK_M1wog_1CoY=", version 303)
Still in the time dict (i.e. deleted files) ("apps")
kf5.kservice.sycoca: Parse error in  "/home/freddy/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu" , line  1 , col  1 :  "unexpected end of file"
Menu "applications-kmenuedit.menu" not found.
Saving
```

**Comment by yochai** [comment]
I've encountered the bug too, running the following two commands after updating gets the menu updated.
```
rm ~/.cache/ksycoca5_* -rf
kbuildsycoca5
```

**Comment by ttuegel** [comment]
If removing the ksycoca cache fixes the problem, that suggests to me the problem is the timestamps in the Nix store not being updated. We may need to patch kbuildsycoca.

**Comment by FRidh** [comment]
> rm ~/.cache/ksycoca5_* -rf
> kbuildsycoca5

That fixes the issue

**Comment by FRidh** [comment]
I just ran in this issue again after a `nixos-install` and using my old `$HOME`

**Comment by ttuegel** [comment]
> I just ran in this issue again after a nixos-install and using my old $HOME

Could you share your `configuration.nix` please? I'm still having difficulty reproducing this.

**Comment by FRidh** [comment]
@ttuegel here is my `configuration.nix` https://github.com/FRidh/nix-config/blob/f25424d80d8d04c9471cc1a500636040b7810d6a/machines/fr-desktop.nix

**Comment by ttuegel** [comment]
Hm, OK, now I am suddenly able to reproduce this on my own setup, and I'm not sure why. Well, at least now I can investigate it!

**Comment by johnramsden** [comment]
I'm getting this issue as well. Specifically I installed google-chrome under kde plasma and no new applications show up in the menu.

I ran ```kbuildsyscoca``` and got the following:

```
john@zero> kbuildsycoca5                                                                      ~
kbuildsycoca5 running...
Reusing existing ksycoca
Recreating ksycoca file ("/home/john/.cache/ksycoca5_en_6FxOgM3ZXYKNjZBZboMCi7opGwA=", version 303)
Still in the time dict (i.e. deleted files) ("apps")
kf5.kservice.sycoca: Parse error in  "/home/john/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu" , line  1 , col  1 :  "unexpected end of file"
Menu "applications-kmenuedit.menu" not found.
Saving
```

**Comment by itszero** [comment]
just providing a datapoint: I also have this issue with a fresh nixos unstable install.

**Comment by bkchr** [comment]
Yeah, I also have the same problem, I just removed `xdg-desktop-menu-dummy.menu` and `kbuildsyscoca5` works again. But we should find out what created this dummy file.

**Comment by FRidh** [comment]
Just now I encountered the issue again with
```
$ nixos-version
18.03pre131587.b6ddb9913f2 (Impala)
```
Grepping Nixpkgs for `kbuildsycoca5` does not show any place where it is explicitly called. Is it called from Plasma already?

**Comment by ttuegel** [comment]
> Grepping Nixpkgs for kbuildsycoca5 does not show any place where it is explicitly called. Is it called from Plasma already?

It is supposed to be called from `startkde` (per our modifications for NixOS) but that call seems to have evaporated.

**Comment by Chiiruno** [comment]
A hook for executing `kbuildsycoca5` when upgrading your system would be nice.

**Comment by jlelse** [comment]
I still get this issue with this output:

``kbuildsycoca5 running...
kf5.kservice.services: The desktop entry file "/run/current-system/sw/share/applications/org.kde.systemmonitor.desktop" has Type= "Application" but no Exec line
kf5.kservice.sycoca: Invalid Service :  "/run/current-system/sw/share/applications/org.kde.systemmonitor.desktop"
``

**Comment by Vskilet** [comment]
I'm on Nixos 18.09 and when I use `kbuildsycoca5` nothing appears on command line ... And one day when I `nix-env -ia something` ... menu updated ... Strange ?

**Comment by va1entin** [comment]
@Vskilet Same here. Since I switched to 18.09 the application menu started working again but manual execution of kbuildsycoca5 didn't seem to do anything for me either.

**Comment by Vskilet** [comment]
When I delete my home cache (`.cache`) and do a `kbuildsycoca5`, my desktop is correctly regenerate.

**Comment by schmittlauch** [comment]
providing a data point: Affected by this as well on 18.09.1676.7e88992a8c7 (Jellyfish), a `rm ~/.cache/ksycoca5_* -rf && kbuildsycoca5` fixed it so far for me.
Let's see how long that holds…

**Comment by ttuegel** [comment]
At the moment, we call `kbuildsycoca5` from somewhere early in the login script, but it sounds like that does not correctly invalidate the cache. We should just delete `$HOME/.cache/ksycoca5_*` and let the cache be regenerated as-needed.

**Comment by hyperfekt** [comment]
Another datapoint: Running just `kbuildsycoca5` (without clearing the cache) manually rebuilds the application launcher, but the call in userActivationScripts doesn't do the job.

**Comment by pirboazo** [comment]
> @Vskilet Same here. Since I switched to 18.09 the application menu started working again but manual execution of kbuildsycoca5 didn't seem to do anything for me either.

I worked for me :-) thank

**Comment by matthewbauer** [comment]
Potential fix here: https://github.com/NixOS/nixpkgs/pull/57037

**Comment by FRidh** [comment]
I am not aware of this issue happening anymore so closing now.

If the issue does occur for you, please drop a comment here.

**Comment by scarf005** [comment]
hi, could you reopen this issue? installed `ark,` `kdeconnect` and `filelight` and had to use the method in [comment](https://github.com/NixOS/nixpkgs/issues/20776#issuecomment-263951927) above to create program icons. using nixos 22.05 with unstable channel.

**Comment by alphabet5** [comment]
This was still an issue with a fresh NixOSinstall last week.  Running this worked though.

```
rm ~/.cache/ksycoca5_* -rf
kbuildsycoca5
```

**Comment by EternityForest** [comment]
Is there any chance of solving this with a more general cache management solution?  Something that can t

**Comment by doublevoid** [comment]
This is still an issue in Plasma 6.

**Comment by tahuffman1s** [comment]
I'm having this issue with Plasma 6.0 on the Unstable channel.

Clearing the cache doesn't work for me.

**Comment by DaKingof** [comment]
> I'm having this issue with Plasma 6.0 on the Unstable channel.
> 
> Clearing the cache does indeed work for me. With Plasma 6 run these commands:
> 
> rm ~/.cache/ksycoca6_* -rf kbuildsycoca6

This doesn't work for me. I can only launch from a terminal instance. Using .desktop links are still broken.
