### ISSUE TITLE
lldb output unicode codes

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nixpkgs#20773]
## Issue description

run `lldb` and enter any key

```
$ lldb
(lldb) \U+0780A\U+0780A\U+0780A\U+0780A\U+0780A
```

### Steps to reproduce
$ nix-env -i lldb
$ lldb
<press any key>

## Technical details
lldb version 3.7.1

nixos-version
17.03pre95306.a24728f (Gorilla)

nix-env --version
nix-env (Nix) 1.11.4

nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion                /etc/nixos
"17.03pre95306.a24728f"

same issue here: http://superuser.com/questions/1098503/characters-turn-into-unicode-in-gnome-terminal-with-lldb

**Comment by vcunat** [comment]
ATM I saw nothing better than disabling libedit in lldb.
