### ISSUE TITLE
olaris-server is missing ffmpeg dependency.

### ISSUE THREAD

**Issue by kevincox** [NixOS/nixpkgs#207877]
### Describe the bug
Olaris server requires ffmpeg to be available and raises an error when it can't be found:

```
INFO[0332] Starting ffprobe with args [ffprobe -show_data -show_format -show_streams file:///mnt/media/some-video.avi -print_format json -v quiet]
INFO[0332] scanning file                                 filepath="/mnt/media/some-video.avi"
DEBU[0332] received error while opening file for stream inspection  error="Failed to probe with ffmpeg: exec: \"ffprobe\": executable file not found in $PATH"
```

### Steps To Reproduce
1. Run olaris-server
2. Add a library.

### Expected behavior

The software runs correctly.

### Additional context

There are two main ways to fix this:

1. Patch the software to use the full path to the ffmpeg dependency (ideally upstream).
2. Wrap the program to add ffmpeg to its path.

### Notify maintainers
@urandom2 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05pre436728.652e92b8064`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(kevincox): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by kevincox** [comment]
In fact it looks like it needs a custom https://gitlab.com/olaris/ffmpeg image as it passes arguments that only exist on the modified version.

**Comment by kevincox** [comment]
Actually it looks like the fork is no longer required: https://gitlab.com/olaris/olaris-server/-/commit/593a58b7b3ccfd35669c606a46448e192993a2dc. But this doesn't seem to be released yet. But probably is still a better option than packaging the custom ffmpeg.

**Comment by urandom2** [comment]
yep, this looks like an easy fix; I am keen to try building the ffmpeg fork so that we can stick to an unstable, but released version, however if that proves prohibitively difficult, just using the tip of the default branch until they cut a new release sounds good to me

**Comment by urandom2** [comment]
no action required, but note the way I used `Fixes #207877` in the pr and commit, means this issue would have autoclosed when the change merged

**Comment by kevincox** [comment]
That is what happened.

**Comment by urandom2** [comment]
sorry, I only saw this issue's update and assumed that you manually closed it; I assume most people involved in nixpkgs prs do not have merge perms, and github really needs to work on their ux.

terribly sorry for the hassle, and assuming you were a more novice user

**Comment by kevincox** [comment]
No worries, GitHub really doesn't make it clear.
