### ISSUE TITLE
discord-canary: Failed to load libwayland-cursor.so.0.

### ISSUE THREAD

**Issue by LudovicoSforza** [NixOS/nixpkgs#207820]
### Describe the bug
Can't launch discordcanary with NIXOS_OZONE_WL=1

### Steps To Reproduce
1. set NIXOS_OZONE_WL = "1"; in environment.variables
2. open discordcanary with `discordcanary --enable-features=UseOzonePlatform --ozone-platform=wayland`

### Expected behavior
Discord should open without any errors

### Additional context
I got this error 
```
DiscordCanary 0.0.145
[36668:1226/200832.445890:ERROR:wayland_connection.cc(155)] Failed to load libwayland-cursor.so.0.
[36668:1226/200832.445979:FATAL:ozone_platform_wayland.cc(221)] Failed to initialize Wayland platform
```

### Notify maintainers
@MP2E @devins2518 @artturin @infinidoge
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-xanmod1, NixOS, 23.05 (Stoat), 23.05.20221222.652e92b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/ih6hk2bn9v0g9zf6v4wk1lpb1bj48nhd-source`
 ```

**Comment by LunNova** [comment]
Library should be from `nixpkgs#wayland /nix/store/miklmfs1s6im3iwh072bb40fpl3x8sjy-wayland-1.21.0/lib/libwayland-cursor.so.0.21.0`

**Comment by LunNova** [comment]
Please try with #207854
