### ISSUE TITLE
epsonscan2 - scanning utility for Epson scanners

### ISSUE THREAD

**Issue by kravemir** [NixOS/nixpkgs#207853]
**Project description**
Epson Scan 2  is a scanning utility for epson printers and scanners.

**Metadata**

* homepage URL: https://support.epson.net/linux/en/epsonscan2.php
* source URL: http://support.epson.net/linux/src/scanner/epsonscan2/
* license: [LGPL-2.1-or-later](https://spdx.org/licenses/LGPL-2.1-or-later.html)
* platforms: linux

**Comment by kravemir** [comment]
I spent some time on this, but probably packaging epsonscan2 isn't worth the effort. My findings:

- build is quite tricky, as the sources contain some amount of tweaks (overrides) to standard cmake variables for build/install paths, and some install commands don't use `CMAKE_INSTALL_PREFIX`,
- non-free software plugin is required for network scanning:
  - sources of epsonscan2 are hard-coded to search the plugin in same path as is the installation path of epsonscan2, which doesn't play nice the immutability,
- the scanner might be supported already by http://www.sane-project.org/sane-mfgs.html#Z-EPSON.

----

My all-in-one printer is EcoTank L3160, which isn't listed in http://www.sane-project.org/sane-mfgs.html, but is similar to EcoTank L3150. And, all that was need is the following config:

```nix
hardware.sane.enable = true;
```

Terminal output:

```
❯ scanimage -L
device `escl:https://192.168.88.152:443' is a Epson L3160 Series platen scanner

❯ scanimage --device 'escl:https://192.168.88.152:443' --format=png --output-file test.png --progress
scanimage: rounded value of br-x from 215.9 to 215.9
scanimage: rounded value of br-y from 297.18 to 297.18
Progress: 100.0%
```

**Comment by james-atkins** [comment]
I've managed to get this working on PR #241532. As you said, building `epsonscan2` is a complete pain and required a fair bit of patching.

It would be great if other Epson scanner owners could test this!

**Comment by romildo** [comment]
> I've managed to get this working on PR #241532. As you said, building `epsonscan2` is a complete pain and required a fair bit of patching.
> 
> It would be great if other Epson scanner owners could test this!

Works for me with Epson L3150 with wifi connection and non free plugins.
