### ISSUE TITLE
docker-py does not work on master

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20789]
I was using 16.09, then I switched to master and I was unable to build the system configuration: 

```error: docker-py-1.10.6 not supported for interpreter python3.5m```

Does docker not work at all in master?

**Comment by RonnyPfannschmidt** [comment]
@fubarbaz there is work to go for python3 as default, i suspect you want to switch some things to python2 explicitly

**Comment by FRidh** [comment]
cc @jgeerds who disabled it on Python 3 with 8d36794046f9796f7c71c97c3057dd1acc4ea89b

**Comment by FRidh** [comment]
(note that the package could use a maintainer)

**Comment by jgeerds** [comment]
Fixed in bfc2721ebf08a414f0268e9f4913a563a6b86999
