### ISSUE TITLE
Use repro-get as a fixed-output-derivation fetcher in Nixpkgs

### ISSUE THREAD

**Issue by MatthewCroughan** [NixOS/nixpkgs#207981]
I stumbled upon a FOSDEM talk titled [Bit-for-bit reproducible builds with Dockerfile](https://fosdem.org/2023/schedule/event/container_reproducible_dockerfile/) which states:

> The second part will introduce a new tool called repro-get [3] which can be used to deterministically install a specific snapshot of apt, dnf, apk, and pacman packages. The packages are fetched by their SHA256 hash from various file providers including HTTP(S) sites, local filesystems, OCI registries, and even IPFS. The repro-get tool is expected to be used for containers in conjunction with the SOURCE_DATE_EPOCH work, but it can also be useful in non-container environments.

If this is true, then we can start using `repro-get` in Nixpkgs as a fixed-output-derivation, to expose ourselves to even more software, and inherit a lot more of the existing software ecosystem. It may also be the case that repro-get gives us the sha256sums ahead of time, like a sort of lock file that we can read with a Nix builtin.

https://github.com/reproducible-containers/repro-get

**Comment by tomodachi94** [comment]
`repro-get` is soft-deprecated, according to [its repository](https://github.com/reproducible-containers/repro-get):

> ⚠️ Soft-deprecated
> repro-get is soft-deprecated due to its complexity.

Is this still worth pursuing?

**Comment by MatthewCroughan** [comment]
Probably not, I think they were a bit optimistic and realised that that stuff isn't reproducible. They idea that it could be was exciting, but probably not realistic.
