### ISSUE TITLE
Font rendering issue on Brave/Chromium on nixos unstable

### ISSUE THREAD

**Issue by silasdavis** [NixOS/nixpkgs#207984]
### Describe the bug
The fonts on Brave/Chromium (and some other, I presume, GTK apps) 'look bad'. They are blurry since an update in the last few weeks, whereas before they were not.

The contrast can be seen comparing between Brave and Firefox. Brave use to have the same sharpness of text.

I'm guessing this has something to do with anti-aliasing (sub-pixel rendering?). I am on a 4K laptop screen.

### Steps To Reproduce
1. Use nixpkgs-unstable at revision `b139e44d78c36c69bcbb825b20dbfa51e7738347`

2. With Brave installed from `/nix/store/nddh0x2ahy0qlq5zdqnag7r7lf0yym1n-brave-1.46.133.drv`

3. and Firefox from `/nix/store/2dyh7yf53dg9hcgiv873sv2sz7ywmnkq-firefox-108.0.1.drv`

Then on my intel graphics based system compare a github issue page, for example. The fonts used for menus in the chrome and toolbar are particularly bad.

### Expected behavior
Fonts look nice and sharp, like they did before

### Screenshots.

Firefox on left, Brave on right (note: Firefox looks even sharper than in the image without the PNG compression)

![image](https://user-images.githubusercontent.com/99715/209689496-4c41d04d-07bd-4d63-9c27-ba87f58aa630.png)

### Additional Context

Semi-relevant looking: https://www.reddit.com/r/NixOS/comments/z9op73/any_idea_why_switching_to_nixos_2211_breaks/

Though the machine I am running (note: I am on unstable as above, but state version 22.05)

### Notify maintainers

To Brave maintainers:

@uskudnik 
@JeffLabonte 

Apologies for disturbing you, since I'm fairly sure there is an issue usptream here since I see bad font rendering elsewhere (for instance, in intellij). Perhaps you can direct me elsewhere if needed (GTK something?)

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(silas): `""`
 - channels(root): `"home-manager-21.11.tar.gz, nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by silasdavis** [comment]
To add to this, fonts on intellij can only be described as 'upsetting'...

![image](https://user-images.githubusercontent.com/99715/209802515-e392187b-c55c-43cc-916d-c1061ec32aec.png)

**Comment by GrabbenD** [comment]
I'm not seeing this issue if I compare Firefox and Brave on my 4K HIDPI display. Here's my config (unstable nix channel with Hyprland WM):
```
# .nix
nixpkgs.config.allowUnfree = true;
services.xserver.videoDrivers = [ "nvidia" ]; # Wayland
hardware.opengl.enable = true;

hardware.video.hidpi.enable = true;
fonts.fonts = with pkgs; [
  noto-fonts
  noto-fonts-emoji
];
```

**Comment by buckley310** [comment]
@silasdavis can you clarify the questions above?

**Comment by buckley310** [comment]
My thought is that if firefox is using native wayland, but brave and intellij are using xwayland, and the issue occurs because xwayland gets something wrong about DPI, either because of mismatching multi-monitor DPI, or something else. Can't try to recreate it until I know what to recreate though :P so I need those answers.

**Comment by GrabbenD** [comment]
@silasdavis I experimented with various settings and here's some new discoveries with my ultrawide 3840x1600 monitor:
* `hardware.video.hidpi.enable = true;` makes fonts pixelated on unstable branch  (upcoming 23 release), this can be fixed with: `fonts.fontconfig.antialias = true`
* I noticed that without `fonts.fontconfig.hinting.enable = true` I get blurry fonts just like you
* `fonts.fontconfig.subpixel.rgba = "rgb";` gives my fonts the right height

In summary this works extremely well on my end:
```
# .nix
nixpkgs.config.allowUnfree = true;
services.xserver.videoDrivers = [ "nvidia" ]; # Wayland
hardware.opengl.enable = true;

# Ultrawide 4K Monitor
hardware.video.hidpi.enable = false; # Breaks TTY font size & antialiasing

# Styling
fonts = {
  fonts = with pkgs; [
    noto-fonts
    noto-fonts-emoji
  ];

  fontconfig = {
    # Fixes pixelation
    antialias = true;

    # Fixes antialiasing blur
    hinting = {
      enable = true;
      style = "hintfull"; # no difference
      autohint = true; # no difference
    };

    subpixel = {
      # Makes it bolder
      rgba = "rgb";
      lcdfilter = "default"; # no difference
    };
  };
};
```
(hinting.style, hinting.autohint & subpixel.lcdfilter didn't make any difference with noto fonts on my end).

**Comment by silasdavis** [comment]
Sorry for long delay on this.

I can joyously report that https://github.com/NixOS/nixpkgs/pull/222236 seems to have fixed _everything_ for me. Just removing this and now fonts are not burning my eyes. Thanks to @K900 .
