### ISSUE TITLE
Add updater script for `xorg.*` packages

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#207978]
`xorg.*` packages use https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/generate-expr-from-tarballs.pl to generate about 200 packages based on https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/tarballs.list tarball list.

There are a few problems with it:
1. It's tedious to update these packages: need to change the file, fetch 200 tarballs from internet to generate one hash
2. The autogeneration script injects questionable and outdated things like `hardeningDisable = [ "bindnow" "relro" ];`. I don't think it's relevant for most packages (or any at all).
3. It uses custom `builder.sh` we probably don't need any more.
4. It has massive overrides file
5. Most packages have no maintainer assigned. Probably because it's not as easy to plug yourself in via overrides.

~~I suggest moving packages out of `xorg.*` one by one until `xorg.*` disappears.~~

I suggest at least adding an updater that can handle there packages via `$ nix-shell maintainers/scripts/update.nix  --argstr package $p`. That way r-ryantm (or lazy me) can update packages at least individually.

**Comment by SuperSandro2000** [comment]
Not sure about moving the packages out of xorg.* but I support having one combined and not auto generated nix file.

**Comment by Artturin** [comment]
> The autogeneration script injects questionable and outdated things like hardeningDisable = [ "bindnow" "relro" ];. I don't think it's relevant for most packages (or any at all).

personally i like the autogeneration script


> The autogeneration script injects questionable and outdated things like hardeningDisable = [ "bindnow" "relro" ];. I don't think it's relevant for most packages (or any at all).

https://github.com/nixos/nixpkgs/commit/27b9f5d65ee452c9a1a49a2e245b2a45ee1d65ab

> Breaks the module system at runtime otherwise.

**Comment by trofi** [comment]
> > The autogeneration script injects questionable and outdated things like hardeningDisable = [ "bindnow" "relro" ];. I don't think it's relevant for most packages (or any at all).
> 
> personally i like the autogeneration script

If we are to keep it it would be nice to have an update script for its packages. It looks like our existing scripts assume 1-to-1 mapping of `.nix`<->package.

> > The autogeneration script injects questionable and outdated things like hardeningDisable = [ "bindnow" "relro" ];. I don't think it's relevant for most packages (or any at all).
> 
> [27b9f5d](https://github.com/NixOS/nixpkgs/commit/27b9f5d65ee452c9a1a49a2e245b2a45ee1d65ab)
> 
> > Breaks the module system at runtime otherwise.

Do you know the details of it? What module system is it talking about: Mesa's, Xorg's or something else? I would like to poke at the details to narrow it down to really affected programs.

The only time I saw problems with any of that is non-inline IFUNC resolvers: https://bugs.gentoo.org/788625#c9. Anything else has a high chance of being a genuine bug.

I don't see any reason to apply it to, say, `xorg.xset`.

**Comment by trofi** [comment]
Reworded the issue to be less ambitious.

I personally just want these packages not lag too much behind as I keep getting into bugs that were already fixed upstream.

We can sort out minor things later.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/262669 will close this

**Comment by rnhmjoj** [comment]
> It's tedious to update these packages

Yeah, but how often do you need to do this? Most of the packages have not changed substantially in 20 years.

> The autogeneration script injects questionable and outdated things li
> It uses custom builder.sh we probably don't need any more.

Then update the script, I guess.

> It has massive overrides file

So does `haskellPackages`, why do you think this is a problem?

> Most packages have no maintainer assigned

Because, again, most of the X.org software have not changed in ages: there's not much to maintain...

**Comment by trofi** [comment]
> > It's tedious to update these packages
> 
> Yeah, but how often do you need to do this?

`git log` says I did it 19 times. None of them was as simple as running `nix-update`. I think none of those should be as tedious. If we look at the past history for the `last year` it was updated 46 times:

```
$ git log --oneline --no-merges --since='last year' tarballs.list | wc -l
46
```

That makes updates weekly on average.

I find the visual view of `tarballs.list` history a good indicator of typical maintenance churn: https://github.com/NixOS/nixpkgs/commits/master/pkgs/servers/x11/xorg/tarballs.list

Those `xorg.*` commits brought `nixpkgs` staleness back on track.

And for completeness the release frequency of a mailing list at a glance (as `nixpkgs` used to lag for quite a while behind upstream):
- 4 releases on October: https://lists.x.org/archives/xorg/2023-October/thread.html
- 4 releases in September: https://lists.x.org/archives/xorg/2023-September/thread.html
- 3 releases in August: https://lists.x.org/archives/xorg/2023-August/thread.html
- ...

> Most of the packages have not changed substantially in 20 years.

I would say the important detail here is if the packages were changed/released or not.

I would not judge the "substance" of the change in the software over so long periods of time. Many things came and went over that time. Especially on a set of 200 packages.

> > It has massive overrides file
> 
> So does `haskellPackages`

I would prefer not to drag into discussion a massive package ecosystem with a dedicated set of maintainers.

> why do you think this is a problem?

It spreads a package definition over multiple files. in `xorg`'s case it has at least 3 files: `tarballs.list`, `default.nix` and `overrides.nix`. Each of them is prone to conflicts. Existing tooling does not know how to update it automatically.

> > Most packages have no maintainer assigned
> 
> Because, again, most of the X.org software have not changed in ages: there's not much to maintain...

You might want to look at the history of a `tarballs.list` file to see the amount of churn it experiences: https://github.com/NixOS/nixpkgs/commits/master/pkgs/servers/x11/xorg/tarballs.list

**Comment by rnhmjoj** [comment]
> If we look at the past history for the last year it was updated 46 times:

It's not that much considering it contains more than 200 packages. I didn't make a histogram, but it looks like most of the updates are coming from a few actively developed libraries.
Wouldn't it be easier to split out those on a needs basis?

> It spreads a package definition over multiple files
> Existing tooling does not know how to update it automatically.

Agreed, but again, only a few of these packages requires overrides and/or frequent updates.

**Comment by trofi** [comment]
> > If we look at the past history for the last year it was updated 46 times:

> It's not that much considering it contains more than 200 packages.

Or you could look at it as nobody wants to update them until it looks too bad. For example these 3 commits updated ~200 packages:

- 90 libs and apps: https://github.com/NixOS/nixpkgs/commit/5a450bdd9f3d5f79b5a95c5c0905509516bd7ab7
- 73 fonts: https://github.com/NixOS/nixpkgs/commit/3c176486ef173b050edcb44b71048be888873c33
- 106 apps: https://github.com/NixOS/nixpkgs/commit/528afff1f95bf82c4e3d4f24a8f740500c9bdebf

**Comment by rnhmjoj** [comment]
But that's my point: right now it's easy to update all of them at once and there's not much checking to do because the X.org fonts and apps are almost never changed.

**Comment by sdht0** [comment]
There are two orthogonal issues being discussed here: having a generation script and implementing an updater script.

It should be possible to write a script that updates `tarballs.list` and runs `generate-expr-from-tarballs.pl`, if the generation script is kept. AFAIU, there is no such script right now and one has to manually check whether any of the packages needs an update?

I do think the generation script as it is right now is not optimal. I just went through the process of updating xorg-server (#263689). For even a single update, the script needs to download _all_ the tarballs, which is pointless IMO. 

> the X.org fonts and apps are almost never changed.

This is actually a reason for moving them out of the generation script. If they are never updated, why go through the process of downloading their tarballs and generating the nix expression every time.

**Comment by NickCao** [comment]
> AFAIU, there is no such script right now and one has to manually check whether any of the packages needs an update?

There was a (partially working) update script that I used in https://github.com/NixOS/nixpkgs/pull/241012

https://gist.github.com/NickCao/fa592237f768c32ff26688d99b20f81f

**Comment by sdht0** [comment]
Ah nice. Maybe we can add this as a `passthru.updateScript`?

**Comment by NickCao** [comment]
Still has to be modified to work with individual packages, and polish some rough edges.

**Comment by sdht0** [comment]
Yeah it works for me with some changes. Doesn't look like there are any updates apart from xorg-server :)

> Still has to be modified to work with individual packages

Right. I think the simplest things to do for now would be to add this script alongside `generate-expr-from-tarballs.pl` so atleast there'd be a way to check for updates without having to manually go through `tarballs.list`. @NickCao would you have a chance to do this anytime soon?

Next step could be to add support for individual packages, although `generate-expr-from-tarballs.pl` will still need to run for all. We can wait to see if #262669 gets merged.

**Comment by sdht0** [comment]
Added a simplified script (based on @NickCao's) to update all xorg packages together at #293704.

It uses the perl script which regenerates all expressions even if only 1 package is updated. Next step could be to put the package expression in `default.nix` in separate  files so that they can be generated independently.
