### ISSUE TITLE
bottles: Fail to launch app when path has a single quote

### ISSUE THREAD

**Issue by X9VoiD** [NixOS/nixpkgs#207994]
### Describe the bug
[Bottles](https://github.com/NixOS/nixpkgs/blob/ed28b99cd3633ad1b84fd8356c625b7197d8c28e/pkgs/applications/misc/bottles/default.nix) fail to launch an app when there's a single quote in its path and is launched via 'Launch with Terminal' option. This scenario works fine on official flatpak build, though I am not sure if this is even a fault of nix either.

### Steps To Reproduce
1. `nix-shell -p bottles`
2. `bottles`
3. Download and extract [HoloCure](https://kay-yu.itch.io/holocure) to any path as long as it has a single quote in it, or use any other game/app of choice.
4. Create a wine bottle in Bottles with the environment "Gaming" (probably doesn't matter which environment)
5. Press 'Add Shortcuts...' and navigate to the game/app's executable.
6. Add the executable.
7. Click on the hamburger menu then press 'Launch with Terminal'
 
### Expected behavior
It will launch completely fine.

### Additional context
```
02:30:42 (INFO) Setting Key e8b62045-9393-48bd-bf7b-be1989e343a0={'executable': 'HoloCure.exe', 'name': 'HoloCure', 'path': "/home/oscar/Games/Holo'Cure/HoloCure.exe", 'id': 'e8b62045-9393-48bd-bf7b-be1989e343a0'} for bottle test… 
02:30:50 (INFO) Launching an executable… 
/nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin/sh: -c: line 2: syntax error: unexpected end of file
```

The first line is when I added the executable via step 6, and the third line is when I did step 7.

If the game/app is launched normally it will run fine.

### Notify maintainers

@psydvl @SCOTT-HAMILTON @SuperSamus

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 23.05 (Stoat), 23.05pre437630.fad51abd42c`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(oscar): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by psydvl** [comment]
Is's not nixpkgs, but bottles itself bug
Open issue here: https://github.com/bottlesdevs/Bottles/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
