### ISSUE TITLE
paperless: scheduler service can't start, "Unknown command: 'qcluster'"

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#207965]
### Describe the bug

Since 6c7ee71a3669b1f944caf08ba7d3289fcfe2377d which updated `paperless-ngx` from 1.9.2 to 1.10.2, the scheduler service can't be started, the error reported in the logs is:

```text
Unknown command: 'qcluster'
Type 'manage.py help' for usage.
```

### Steps To Reproduce
1. enable `services.paperless.enable`
2. use `systemctl status` or `journalctl -u` to see error as above in the logs 

### Expected behavior

The service starts succesfully

### Notify maintainers

* Module maintainers: 
  * @erikarvstedt 
  * @Flakebi 
* Package maintainers:
  * @erikarvstedt 
  * @lukegb 
  * @gador 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.20221225.fad51ab`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.0pre20221223_3dbf9b5`
 - channels(aroemer): `"nixpkgs-21.11"`
 - channels(nmelzer): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by erikarvstedt** [comment]
Probably fixed by https://github.com/NixOS/nixpkgs/pull/207754#event-8108862793.
