### ISSUE TITLE
Haskell sparkle package fails to build with Gradle error

### ISSUE THREAD

**Issue by TikhonJelvis** [NixOS/nixpkgs#20802]
## Issue description

First, `haskellPackages.sparkle` failed with `gradle: command not found`.  I fixed this by adding `gradle` as a build tool:

```
sparkle = overrideCabal super.sparkle (drv: {
  libraryToolDepends = [ pkgs.gradle ];
});
```

After that, it fails with an error from Gradle:

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Confusingly, `gradle build` seems to work correctly when launched manually from a clone of the `sparkle` repo, so this is probably something to do with the Nix build environment. I tried running `gradle` with `--stacktrace` and `--debug --info` by editing the `Setup.hs` file, but that didn't change the output.

### Steps to reproduce

Build `sparkle` after adding `gradle` to Sparkle's `libraryToolDepends`:

    nix-shell -p haskellPackages.sparkle

## Technical details

* System: 17.03pre92039.adfcc2d (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre92039.adfcc2d

**Comment by puffnfresh** [comment]
It's trying to use $HOME and failing, because $HOME under a nix-build user is `/var/empty`. You need to set $GRADLE_USER_HOME for the Gradle command:

```nix
overrideCabal sparkle (drv: {
  libraryToolDepends = [
    (stdenv.mkDerivation {
      name = "gradle-wrapped";
      buildInputs = [ pkgs.makeWrapper ];
      phases = [ "installPhase" ];
      installPhase = "makeWrapper ${gradle}/bin/gradle $out/bin/gradle --set GRADLE_USER_HOME /tmp";
    })
  ];
})
```

**Comment by TikhonJelvis** [comment]
Awesome. That fixed the immediate Gradle problem, but now Gradle can't find the JVM dependencies it needs (ie `spark-core`).

I tried adding `spark` to `libraryToolDepends`, but it didn't fix the problem.
