### ISSUE TITLE
Androidenv is missing cmdline-tools

### ISSUE THREAD

**Issue by hadilq** [NixOS/nixpkgs#208047]
**Project description**
I noticed the tools in Android SDK is obsolete now, so I tried to add the cmdline-tools to the sdk and make sure the avdmanager is working properly. All my work is in https://github.com/hadilq/nixpkgs/tree/android-sdk/refactor-to-fix-problems branch, but right now it has problems to create a PR. So I'll create multiple PRs to merge the changes. However, these changes related to other problems as well:

- mkrepo.rb missed while merging packages, so there's a fix related to this problem in that branch.
- Fix mips-android-sysimage-license
- Fix system image download url for default type
- Missing package.xml in packages by generating them
- Just one example for shell.nix, so here I add two others
- Add cmdline-tools and patcher
- Update all package versions
- Update platform-tools to depend on libc++
- Fix problem with avdmanager when trying to create an avd, to do so replaced deploy-androidpackage.nix with deploy-androidpackages.nix to handle deplying multiple system images with the same apiVersion and type in one derivation
- Fix example/android-sdk-with-emulator-shell.nix to work as expected

This is my first contribution here so please feel free to let me know how many PRs are suitable for these changes, with what order, or any other concerns. Have to mention that it was fun to work with Nix.

**Notify maintainers**
@jakobkukla @Artturin

**Metadata**
It's only tested on NixOS  22.05

References:
- [avdmanager](https://developer.android.com/studio/command-line/avdmanager?hl=id)
- [cmdline-tools](https://developer.android.com/studio/command-line)
- [changes branch](https://github.com/hadilq/nixpkgs/tree/android-sdk/refactor-to-fix-problems)

**Comment by hadilq** [comment]
Finally I merged most of the code inside this branch, so it's time to close this issue. Some more work that comes to my mind:

 - Use dependencies of each package in the XML files to automatically add dependencies of a package. It needs a refactor.
 - The way we handle ndk-bundle here needs to be reviewed.

Maybe I'll spend some time in the future on them, but I don't have any plan to do so. In the end, especial thanks to @numinit, @Artturin , @SuperSandro2000.

**Comment by numinit** [comment]
Thanks @hadilq !
