### ISSUE TITLE
PATH in /var/lib/cups/cupsd.conf can become outdated

### ISSUE THREAD

**Issue by jerith666** [NixOS/nixpkgs#20806]
## Issue description

In the pre-start script for `cups`, we symlink the `cupsd.conf` template from the nix store into `/var/lib/cups/`: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/printing/cupsd.nix#L308.

However, if changes are made to CUPS via the GUI -- for example, enabling network access -- this symlink is overwritten with a plain file.  And it contains a `SetEnv PATH` line with paths into the nix store.  This effectively freezes some version of the cups binaries into this config file, which is no longer managed by nix.

As a result, CUPS can break, e.g. when `nix-collect-garbage` deletes the referenced store paths.  For me, this meant nothing would print, and I started seeing this error in `journalctl -u cups`:

`Nov 29 21:50:56 alpha cupsd[1535]: gs: No such file or directory`

Manually editing `/var/lib/cups/cupsd.conf` to update the store paths on the `SetEnv PATH` line (while the `cups` systemd service was stopped) got printing working again for me.  I guess we could make the pre-start script do this (with a sed or something), but that seems kind of hacky ...

cc @abbradar; commit 4701747 seems especially relevant here.

## Technical details

* System: `17.03.git.4173f5d (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `"17.03.git.4173f5d"`

**Comment by jerith666** [comment]
Hm, maybe the right approach is to make `cupsd.nix` just put `SetEnv PATH /var/lib/cups/path` in the `cupsd.conf` template, and then have it also ensure that `/var/lib/cups/path` points to the correct location in the nix store?  Then CUPS can write whatever other changes it wants to its config file, while the nix expression continues to have control over the "final destination" of the path ... ?

**Comment by abbradar** [comment]
I think we want Nix to take priority here because that's what would be expected of declarative configuration and what's already done in other places. So as a quick fix towards this we can force replcaement by symlinks. This should also be documented.

However, we can leave some option (like `mutableUsers` currently exists for users) that reverses this and instead makes `preStart` just insert `SetEnv` and other required options.

The best of both worlds, of course, would be to split the configuration into generated by Nix and values changed in CUPS on top but I doubt this can be implemented.

Thoughts?

**Comment by abbradar** [comment]
For the record, I had the same problem in OctoPrint service. It was solved by writing a small piece of software for updating YAML trees (like `recursiveUpdate` in Nix) and making `preStart` "patch" current configuration with Nix-overridden values. Works perfectly but it would be much more difficult in CUPS (`cupsd.conf` is some kind of ad-hoc mix between XML and custom plain format).

**Comment by jerith666** [comment]
> The best of both worlds, of course, would be to split the configuration into generated by Nix and values changed in CUPS on top but I doubt this can be implemented.

Yeah, I don't see any `Import` directive on the manpage for `cupsd.conf`.  :-(

Overwriting the config file on every restart of `cups` might lead to confusion if folks are trying to use the GUI to get things configured the way they want.  In particular, when I made changes in the GUI to enable remote access, it modified some of the `<Location/>` stanzas that're currently hard-coded in `services.printing.extraConf` at https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/printing/cupsd.nix#L337.  So I'm not sure how I would preserve that under this approach.

(I tried to just set `services.printing.browsing = true` via `configuration.nix`, but that wasn't enough -- I don't really understand why ...)

**Comment by jerith666** [comment]
> cupsd.conf is some kind of ad-hoc mix between XML and custom plain format

Its man page says:

```
CONFORMING TO
       The cupsd.conf file format is based on the Apache HTTP Server configuration file format.
```

... but a bit of googling didn't turn up any pre-existing programs designed to read / write that format.  (Maybe there is something buried in apache `httpd`, who knows?)

**Comment by dezgeg** [comment]
There is http://search.cpan.org/dist/Config-General/General.pm. But then you need to write Perl, which might not be an improvement.
