### ISSUE TITLE
Prism Launcher can't find MangoHud or GameMode

### ISSUE THREAD

**Issue by dacioromero** [NixOS/nixpkgs#208182]
### Describe the bug

Prism Launcher doesn't allow enabling Feral GameMode or MangoHud under the "Performance" tab because it can't find it.

### Steps To Reproduce

1. Install GameMode (configuration.nix: `programs.gamemode.enable = true;`)
2. Install MangoHud (home.nix: `home.packages = [pkgs.mangohud]`)
3. Install Prism Launcher (home.nix: `home.packages = [pkgs.prismlauncher-qt5]`)
4. Create new instance in Prism Launcher
5. Edit instance and go to "Performance" tab

### Expected behavior

GameMode and MangoHud should be able to be enabled when installed.

### Screenshots

![image](https://user-images.githubusercontent.com/12436128/209898012-42519b60-9814-4654-b8ae-8cf489318e1b.png)

![image](https://user-images.githubusercontent.com/12436128/209898033-3900b6f3-e697-49f1-b071-cf87810f81c2.png)

### Notify maintainers

@Scrumplex
@Minion3665 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 22.11 (Raccoon), 22.11.20221224.dac57a4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos"`
 - channels(xxxxx): `"home-manager-22.05.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Kranzes** [comment]
Addressed here -> https://github.com/NixOS/nixpkgs/pull/209047
