### ISSUE TITLE
StumpWM is outdated and broken

### ISSUE THREAD

**Issue by arcadio** [NixOS/nixpkgs#208198]
###### Description of issue

StumpWM is currently broken and fails to build on nixos-22.11 and nixos-unstable, which affects `services.xserver.windowManager.stumpwm`. #203659 mentions StumpWM, but does not refer to its current broken state.

Updating the generated package at `pkgs/development/lisp-modules/quicklisp-to-nix-output/stumpwm.nix`, which is outdated, would solve the issue. Alternatively, it might be desirable to use `lisp-modules-new` by @Uthar?

###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

`nix search` name: `lispPackages.stumpwm`

current version: 20211209-git
desired version: 20221106-git

maintainers: @sternenseemann

###### Note for maintainers

Please tag this issue in your PR.

**Comment by sielicki** [comment]
https://github.com/NixOS/nixpkgs/pull/209405

**Comment by sielicki** [comment]
brokenness was an upstream issue, see: https://www.reddit.com/r/stumpwm/comments/x0ncro/error_installing_through_roswellquicklisp/

**Comment by a12l** [comment]
Is there a way to get StumpWM running on a NixOS 22.11 system? I'm hesitant to use the version from 22.05 since it no longer receives updates. Any suggestions?

**Comment by Uthar** [comment]
I tested stumpwm-21.11 from [here](https://github.com/NixOS/nixpkgs/pull/216051) with Xephyr and it looked OK.

**Comment by a12l** [comment]
> 



> I tested stumpwm-21.11 from [here](https://github.com/NixOS/nixpkgs/pull/216051) with Xephyr and it looked OK.

Thanks @Uthar! Guess that when  #218870 get merged this issue should get solved?

**Comment by Uthar** [comment]
> Thanks @Uthar! Guess that when https://github.com/NixOS/nixpkgs/pull/218870 get merged this issue should get solved?

Yes (-:

**Comment by Uthar** [comment]
You might want to check again, using nixpkgs master branch, and see if it works for you

**Comment by kenranunderscore** [comment]
I just did so and it works great. I'm excited to dive deeper into Common Lisp, as having great support in Nix just makes everything more fun 😊 thanks for all the hard work that you and others put into #218870 @Uthar!

**Comment by arcadio** [comment]
Thanks @Uthar.

StumpWM no longer fails to build now.
