### ISSUE TITLE
Give a more useful error message when running non-nix ELF binaries on NixOS

### ISSUE THREAD

**Issue by tejing1** [NixOS/nixpkgs#208187]
## Issue description
```
$ ./foo
bash: ./foo: No such file or directory
```
This error message is just awful.

We all know what the issue is and why this can't be made to work, but we *could* at least improve the error message by creating a stub ELF interpreter in the default location that just prints out an error message when called.

This would need to interact with modules like `nix-ld` appropriately, but seems doable enough.

Thoughts?

**Comment by eclairevoyant** [comment]
Should be controlled by a module option, on by default, and easy to disable; otherwise I agree

**Comment by tejing1** [comment]
I'm in the process of implementing and testing this now.

In the process, I also discovered something interesting. bash has changed the error message it shows in this scenario:
```
bash: ./foo: cannot execute: required file not found
```

Which at least points in roughly the right direction.

**Comment by tejing1** [comment]
Draft PR is up. I would appreciate feedback on what the message should look like, in particular.

**Comment by bjornfor** [comment]
Can't we try to get this upstream behaviour

```
$ ./binaryfile
ERROR: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
```

in all Linux distros, instead of making something bespoke for NixOS?

**Comment by eclairevoyant** [comment]
Not really, because that error message is unhelpful for everyone who needs it, and the NixOS solution is different from other distros
