### ISSUE TITLE
pavucontrol: no controls (no desktop-xmonad)

### ISSUE THREAD

**Issue by ThisIsSavo** [NixOS/nixpkgs#20829]
## Issue description
I discovered today that when i open pavucontrol I am unable to raise or lower the volume, as the sliders are no longer present. I think it started to behave like that after I updated the system to 17.03, but I'm not 100% sure on that, as I noticed this problem today, because I don't open pavucontol that often.
It's not much of a problem for the master volume, as I have keyboard shortcuts for that, but for individual apps, such as chromium or firefox (if I accidentaly lower the volume I am not able to raise it again).
I use xmonad with no desktop environment.

Here is a screenshot, hope it clarifies what I described above.
![pavucontrol-with-no-controls](http://i.imgur.com/WLT8vjp.png)

### Steps to reproduce
I dunno, I think it was because of the update, so:
`sudo nixos-rebuild switch`

## Technical details

* System: 17.03pre96298.b09435e (Gorilla)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 17.03pre96298.b09435e

**Comment by jokogr** [comment]
Could you post a bit more info, such as what is the GTK theme you are using?

A way to possibly solve this, albeit crude, would be to reset the respective settings, e.g. deleting your `~/.config/gtk-3.0` directory.

**Comment by ThisIsSavo** [comment]
I am using Breeze Dark theme. Deleting the gtk-3.0 directory solves this problem and it works fine until the gtk-3.0 directory is created again. Below is my settings.ini file (don't know what is causing the problem). Anyway, thanks for your help, maybe the solution is not ideal, but it works for me, as i don't use individual app volume controls at all, if i have to i lower/raise only the master volume, and I have keyboard shortcuts for that. If you (or anyone who sees this) have any clues what could solve the problem, you can tell me and I'll try it, but if not I can close this issue.
[Settings]
gtk-theme-name=Breeze-Dark
gtk-icon-theme-name=masalla-icon-theme-0.8-2
gtk-font-name=Sans 10
gtk-cursor-theme-name=Breeze
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb

**Comment by bugarela** [comment]
Same problem here, I'm also on xmonad. My config is fairly simple:
```
[Settings]
gtk-icon-theme-name=rose-pine
gtk-theme-name=rose-pine
```

I don't want to stop using this theme tho, so I'm trying some alternatives (just installed `pulsemixer`)

Btw, for me the controls on pavucontrol are still there, only invisible. Attempting to click and slide many times results in me eventually hitting the invisible slider and I can change the volume. Mine is also transparent and really small:
![image](https://github.com/user-attachments/assets/4780c2d4-9609-4ae9-988a-b90d3c16ca15)
