### ISSUE TITLE
apcupsd: apcaccess does not respect config from services.apcupsd

### ISSUE THREAD

**Issue by Infinidoge** [NixOS/nixpkgs#208204]
### Describe the bug
As per the title,
When enabling `apcupsd` via `services.apcupsd`, the `apcaccess` it includes in the PATH does not respect the configuration file it uses to run the daemon.
This becomes problematic when trying to restrict the interfaces on which the NIS server is listening, because `apcaccess` may no longer properly be able to access the server running on the local machine without explicitly providing the host information. (Normally it is read from the configuration file.)

### Steps To Reproduce
1. `services.apcupsd.enable = true;`
2. `services.apcupsd.configText = "NISIP some.ip.address.here";`
3. Run `apcaccess`
4. Observe the resulting error: `Error contacting apcupsd @ localhost:3551: Connection refused`

### Expected behavior
`apcaccess` should be able to read from the configuration file generated from the service, and behave accordingly.

### Additional context
This could likely be solved by having the service install a wrapper which adds `-f [config file]` into the options when running.

### Notify maintainers
@bjornfor 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.20221218.04f574a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Can provide flake locks if necessary.

**Comment by bjornfor** [comment]
@Infinidoge: Do you know if we need to wrap all of `$out/bin/*` with `-f /path/to/apcupsd.conf`?

FYI:
* I don't have a working APC UPS anymore.
* I briefly looked into whether we can build apcupsd with `--sysconfdir=/etc`, but it wants to install stuff to sysconfdir at build time, which breaks the Nix model.

**Comment by bjornfor** [comment]
I have a fix locally, it builds on top of https://github.com/NixOS/nixpkgs/pull/208225. When that's merged I'll post the fix.

**Comment by Infinidoge** [comment]
> Do you know if we need to wrap all of `$out/bin/*` with `-f /path/to/apcupsd.conf`?

I think everything but `apcupsd` itself needs to be wrapped (so `apcaccess`, `apctest`, `apccontrol`), but I don't know about the latter 2 for sure, and will check when I'm back on my PC.

> I don't have a working APC UPS anymore.

Makes sense.

> I briefly looked into whether we can build apcupsd with `--sysconfdir=/etc`, but it wants to install stuff to sysconfdir at build time, which breaks the Nix model.

Yeah I thought about that too, figured it would do something like that.
It might be possible to apply a patch to change where it places things during build time/where it looks for a config, might look into that later.

**Comment by Infinidoge** [comment]
> I have a fix locally, it builds on top of https://github.com/NixOS/nixpkgs/pull/208225. When that's merged I'll post the fix.

Neat, thanks!

**Comment by bjornfor** [comment]
This should fix it: https://github.com/NixOS/nixpkgs/pull/208295.
