### ISSUE TITLE
supergfxd.service not running when using `services.supergfxd.settings`

### ISSUE THREAD

**Issue by Sumi-Sumi** [NixOS/nixpkgs#208206]
### Describe the bug
`supergfxd.service` does not running when you edit `services.supergfxd.settings`.

### Steps To Reproduce
1. Edit JSON value of `services.supergfxd.settings`
2. Start `supergfxd.service`

### Expected behavior
Running service with my setting.

### Screenshots
![image](https://user-images.githubusercontent.com/24451978/209926135-fc76bdb9-8e5e-4359-a98e-7704617ae74d.png)

- Left is generated by nixos, Right is generated by supergfxd and edit me.
![image](https://user-images.githubusercontent.com/24451978/209926795-675271f8-31ed-4002-be0d-a485c9a3fd0b.png)

### Additional context
I can run without `services.supergfxd.settings` and can edit conf generated by `supergfxd`.
However, I cannot run with same setting. (edit `services.superegfxd.settings`)
I use **zephyrus G14**.

### Notify maintainers

@K900 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.1, NixOS, 23.05 (Stoat), 23.05.20221226.1eb875e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(sumi): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by K900** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/208220

**Comment by Sumi-Sumi** [comment]
Complete !
Thank you !
