### ISSUE TITLE
`makePkgconfigItem` is broken when cross-compiling

### ISSUE THREAD

**Issue by BurNiinTRee** [NixOS/nixpkgs#208341]
### Describe the bug
Trying to cross compile a package that uses the [`makePkgconfigItem`] function results in a build failure:
```
> /build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 10: /nix/store/n4diskhakykfp755lhr12m9zk105ki4q-aarch64-unknown-linux-gnu-pkg-config-wrapper-0.29.2/bin/pkg-config: No such file or directory
```
### Steps To Reproduce
1. Find a package that uses [`makePkgconfigItem`], e.g. [`stb`].
2. Try to cross compile the package, e.g. from a `x68_64-linux`-host: `nix build nixpkgs#pkgsCross.aarch64-multiplatform.stb`
3. Observe build failure in `*.pc.drv`

### Expected behavior
The build should succeed.

### Additional context
[`makePkgconfigItem`] has a  `checkPhase` that invokes `pkg-config` through its store-path instead of the `$PKG_CONFIG` variable set in a setup-hook of the `pkgconfig` package. Either [`makePkgconfigItem`] should invoke the setup-hook manually or [`writeTextFile`] should expose a `nativeCheckInputs` or `checkInputs` argument that [`makePkgconfigItem`] could then use.

I don't know which approach if any is better otherwise I would have opened a PR directly.

### Notify maintainers
[`makePkgconfigItem`] was introduced by @Artturin.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
> nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.12.0, channels(root): "nixpkgs", nixpkgs: /var/home/user/.nixpkgs
```

[`makePkgconfigItem`]: https://github.com/NixOS/nixpkgs/blob/9a56a9a8a1f446cb6f93d59ae584e591401aaea0/pkgs/build-support/make-pkgconfigitem/default.nix
[`stb`]: https://github.com/NixOS/nixpkgs/blob/9a56a9a8a1f446cb6f93d59ae584e591401aaea0/pkgs/development/libraries/stb/default.nix
[`writeTextFile`]: https://github.com/NixOS/nixpkgs/blob/be5e767930fe85d91823aa3d5d53c8f8939f1365/pkgs/build-support/trivial-builders.nix#L116

**Comment by Artturin** [comment]
Fix in https://github.com/NixOS/nixpkgs/pull/208358
