### ISSUE TITLE
`webdav` package is no longer maintained upstream

### ISSUE THREAD

**Issue by aanderse** [NixOS/nixpkgs#208310]
### Describe the bug

`webdav` package is no longer maintained [upstream](https://github.com/hacdias/webdav/issues/144). We should track this issue and eventually remove the software from `nixpkgs` if it doesn't gain any maintainers.

### Notify maintainers

@pmeiyu

**Comment by pmeiyu** [comment]
`webdav-server-rs` package is a recommended better option.  `webdav` package can be removed.

**Comment by aanderse** [comment]
@pmeiyu since you are the listed maintainer can you please take care of this?

**Comment by aanderse** [comment]
author has started maintaining the project again
