### ISSUE TITLE
no support for fast user switching or multiple active gui logins

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#20833]
followup to #20687

it simply seems impossible to log in more than one user on the graphical interface of nix, no matter the window manager

**Comment by edolstra** [comment]
Fast user switching works fine with KDE 4 (kdm). For KDE 5 (sddm), you need 69bea26ea9a6ec97927f45bea78f2148325c2cd9 which is in master but not release-16.09.

**Comment by edolstra** [comment]
Cherry-picked 69bea26 to release-16.09.

**Comment by RonnyPfannschmidt** [comment]
@edolstra whats needed to make something similar work for gdm?

**Comment by edolstra** [comment]
No idea, I don't use gdm. @lethalman may know.

**Comment by vcunat** [comment]
GDM is blocked by #19896 now.

**Comment by vcunat** [comment]
I tested gdm+gnome on master after resolving that issue, and it seems to work smoothly &ndash; gdm remains active on ctrl+alt+1 and the user sessions are spawned on 2, 3, ...

**Comment by RonnyPfannschmidt** [comment]
tested the same, works on master
