### ISSUE TITLE
torbrowser: cannot reproduce mp4/h.264 encoded <video>

### ISSUE THREAD

**Issue by Unode** [NixOS/nixpkgs#20840]
## Issue description

On nixos torbrowser fails to recognize h.264 video.
Other systems (Gentoo and Debian/Ubuntu) this doesn't happen.

Firefox on the same system can reproduce h.264.

### Steps to reproduce

Launch tor-browser
Open http://www.quirksmode.org/html5/tests/video.html
The mp4/h.264 video should show a gray box with a MIME error.

## Technical details

* System: nixos-16.09

**Comment by joachifm** [comment]
https://github.com/NixOS/nixpkgs/commit/96be6a11a85e9e253cf733e57ce7c67fd1a3b81c works for me
