### ISSUE TITLE
Request: lua package - Lmod

### ISSUE THREAD

**Issue by unode** [NixOS/nixpkgs#20842]
[Lmod](http://lmod.readthedocs.io/) is a package used in cluster setups to manage environments with different sets of dependencies. It supersedes the original [modules](http://modules.sourceforge.net/) system.
Neither of these packages is available via nix.

With that said, I'd like to request Lmod to be included in the set of lua packages available via nix.

**Comment by knedlsepp** [comment]
As I'm also using a modules system at work I'd like to know how you are planning to use both nix and lmod in conjunction. Personally I think that once you've got nix installed the `nix-shell` command replaces all my needs for using any modules system.

**Comment by Unode** [comment]
@knedlsepp True, I also see `nix-shell` as a possible solution but one with a bigger overhead for the user at least as it is and without some extra simplification layer on top.

The two main obstacles I see have to do with usability and setup:
* Need to learn how to write nix expressions to obtain the combination of software/libraries required.
* Need to have a way to contact the nix-daemon on each computing node (in cluster environments). Nix is not setup in each machine individually but on a remote (shared) disk - this was not setup by cluster admins and lives in a custom /path/to/share/nix location.

On the other hand, you can already find collections of Lmod recipes that integrate with most systems and work well in cluster environments.
My plan is to use lmod to easily activate and deactivate specific softwares, not all provided by nix (at least at the moment).
