### ISSUE TITLE
[Package Request] Clipboard

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#208588]
**Project description**
An alternative way to copy/cut/paste files on the command line

**Metadata**

* homepage URL: https://github.com/Slackadays/Clipboard
* source URL: https://github.com/Slackadays/Clipboard/LICENSE
* license: gpl3+
* platforms: Unix, MacOS, Linux, Windows

**Comment by Krutonium** [comment]
Here's a short video showing off how it works.

**Comment by zowoq** [comment]
https://github.com/NixOS/nixpkgs/pull/207928

**Comment by Krutonium** [comment]
Oops, I didn't see that! My mistake!
