### ISSUE TITLE
androidndk-pkgs: attribute 'triple' missing

### ISSUE THREAD

**Issue by sivizius** [NixOS/nixpkgs#208527]
### Describe the bug
`targetInfo` in [nixpkgs](https://github.com/NixOS/nixpkgs)/[pkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs)/[development](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development)/[androidndk-pkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/androidndk-pkgs)/androidndk-pkgs.nix is set to `ndkInfoFun stdenv.targetPlatform;`. The function `ndkInfoFun` takes a `{ config, ... }` and accesses a attribute set with `config`. Some of these attributes are attribute sets with a `triple`, but some are attribute sets without and a `double` instead. `targetInfo` is later used without ever checking if it is actually attribute set with an `triple` attribute. Similar with `buildInfo`.

### Steps To Reproduce
e.g. in a nix repl:
```
nix-repl> (__getFlake "github:NixOS/nixpkgs/master").legacyPackages.x86_64-linux.androidndkPkgs
error: attribute 'triple' missing

       at /nix/store/21rv0j7nyrawaxir6xfl764y78c4bnzp-source/pkgs/development/androidndk-pkgs/androidndk-pkgs.nix:78:50:

           77|
           78|       if [ ! -d $out/toolchain/sysroot/usr/lib/${targetInfo.triple}/${sdkVer} ]; then
             |                                                  ^
           79|         echo "NDK does not contain libraries for SDK version ${sdkVer}";
«derivation
```

### Expected behavior
If build/target-platform are not suitable, it should surely throw an error, but an attribute-missing-error aborts the evaluation and cannot be catched by tryEval. Not sure if it possible to add such assertions like in the module-system or only with the builtin `throw`.

### Notify maintainers
@cidkidnix @Cloudef

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/256180
