### ISSUE TITLE
orange3

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#208574]
**Project description**

[Orange] is a data mining and visualization toolbox for novice and expert alike. To explore data with Orange, one requires __no programming or in-depth mathematical knowledge__. We believe that workflow-based data science tools democratize data science by hiding complex underlying mechanics and exposing intuitive concepts. Anyone who owns data, or is motivated to peek into data, should have the means to do so.

![img](https://raw.githubusercontent.com/irgolic/orange3/README-shields/distribute/orange-example-tall.png)

**Metadata**

* homepage URL: https://orangedatamining.com
* source URL: https://github.com/biolab/orange3/releases
* license: GPLv3
* platforms: unix, linux, darwin

[Orange]: https://orangedatamining.com

**Comment by totoroot** [comment]
I'm working on packaging this, but since it has a ton of dependencies that are not yet packaged, it might take a little more time to get a PR ready.
