### ISSUE TITLE
Spyder IDE doesn't start

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#208567]
### Describe the bug
Can't run `spyder` IDE

### Steps To Reproduce
1. add `spyder` pkgs in configuration.nix
2. run `spyder` in terminal.

### Expected behavior
the application runs properly.

### Additional context

```
➜  ~ spyder 
Traceback (most recent call last):
  File "/nix/store/yxmyyvpimj4rilwk9s5vcjwpnc86bz3s-python3.10-spyder-5.4.0/bin/..spyder-wrapped-wrapped", line 6, in <module>
    from spyder.app.start import main
  File "/nix/store/yxmyyvpimj4rilwk9s5vcjwpnc86bz3s-python3.10-spyder-5.4.0/lib/python3.10/site-packages/spyder/app/start.py", line 42, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```
### Notify maintainers

@gebner 

### Metadata

```console
➜  ~ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.11 (Raccoon), 22.11.1198.913a47cd064`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(hervyqa): `""`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by bjornfor** [comment]
I wonder if something clears PYTHONPATH between the wrapper setting it up and spyder importing `zmq`. Because if you look at the `spyder` wrapper script, it does add pyzmq to the search path.

**Comment by bjornfor** [comment]
Fix here: https://github.com/NixOS/nixpkgs/pull/208734

If anyone has time/motivation to discuss this with upstream that'd be great.

**Comment by hervyqa** [comment]
sorry, duplicated issue. https://github.com/NixOS/nixpkgs/issues/205497

**Comment by hervyqa** [comment]
![Screenshot_20230111_044615](https://user-images.githubusercontent.com/45872139/211669143-a449ea99-a1c2-4171-b8c1-7dbb396147f3.png)

i found double `.desktop` in `/nix/store/1339apxlb2wnhghq6z1dkk1l57k7cxhi-python3.10-spyder-5.4.0/share/applications/`, can you delete one of them?

remove this.
```
  desktopItem = makeDesktopItem {
    name = "Spyder";
    exec = "spyder";
    icon = "spyder";
    comment = "Scientific Python Development Environment";
    desktopName = "Spyder";
    genericName = "Python IDE";
    categories = [ "Development" "IDE" ];
  };
```
or
```
cp -r $desktopItem/share/applications/ $out/share
```

**Comment by bjornfor** [comment]
> i found double .desktop in /nix/store/1339apxlb2wnhghq6z1dkk1l57k7cxhi-python3.10-spyder-5.4.0/share/applications/, can you delete one of them?

Thanks for reporting. See https://github.com/NixOS/nixpkgs/pull/210170.
