### ISSUE TITLE
Labels for dockerTools

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20852]
Docker has a feature called labels. I'd like to see this exposed too. 

See https://docs.docker.com/engine/userguide/labels-custom-metadata/ for more information.

**Comment by datakurre** [comment]
@fubarbaz @NeQuissimus Docker image labels are supported in ``config`` argument ``buildImage``:

```
    config = {
         Labels = {
             "com.acme.label" = "value";
         }
    }
```

our problem is probably that while our docs say

> config is used to specify the configuration of the  containers that will be started off the built image in Docker. The available options are listed in the Docker Image Specification v1.2.0

[Docker Image Specification](https://github.com/moby/moby/tree/master/image/spec) does not seem to be updated to include labels.

**Comment by tomberek** [comment]
fixed?

**Comment by sarcasticadmin** [comment]
@tomberek labels are working and I was able to leverage this successfully with `pkgs.dockerTools.buildImage` as @datakurre mentioned. See this [nix expression](https://github.com/Nebulaworks/nix-garage/blob/a9203de2cfdb83ebb9b6b0b5c53627efe70b6dd8/imgs/awsutils/default.nix#L22-L26 ) for context.

Resulted in:
```
$ skopeo inspect docker://docker.io/nebulaworks/awsutils:dz783iaashdby6phqf9pcydxsw1bbjq0                 
{
    "Name": "docker.io/nebulaworks/awsutils",
    "Digest": "sha256:4df34c1e6ab561b3aa6f0c250122ce121ff18e6803d72733f041978b87979df4",                                       
    "RepoTags": [
        "dz783iaashdby6phqf9pcydxsw1bbjq0"
    ],
    "Created": "1970-01-01T00:00:01Z",
    "DockerVersion": "",
    "Labels": {
        "com.nebulaworks.packages": "awscli:1.17.13,bash:4.4,coreutils:8.31,curl:7.68.0,jq:1.6",                               
        "org.opencontainers.image.authors": "Nebulaworks Inc.",
        "org.opencontainers.image.source": "https://github.com/Nebulaworks/nix-garage"                                         
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:6f29a11d541b258cbfb4956ccc442ac0ecf8a6c052f10d1ed0d6d6078ae30f2a"                                              
    ]
}
```

**Comment by purcell** [comment]
Seems like this can be closed.
