### ISSUE TITLE
fishPlugins.grc error regarding cat

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#208597]
### Describe the bug
Installing `grc` and `fishPlugins.grc` on Nixos 22.11 yields `cat: /nix/store/rhnplhpv0y8kbaybaypdgvgqqh8pbdld-fishplugin-grc-unstable-2022-05-24/share/fish/vendor_conf.d/executables: No such file or directory` when building. This error also appears everytime the fish shell is started and makes it hardly usable.

### Steps To Reproduce
1. install `grc` and `fishPlugins.grc` on Nixos 22.11 with `fish` as your shell
2. see the error message during build and when starting the fish shell afterwards

### Expected behavior
The Plugin working without further configuration.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Schweber** [comment]
@onny could you please take a look at this? Unfortunately, i don't have the required understanding of nix to do it myself.

**Comment by onny** [comment]
I'll have a look, thank you for reporting the issue! I'm still using this plugin but not sure what the error is here

**Comment by Schweber** [comment]
@onny any progress? 🙂

**Comment by onny** [comment]
Can you provide your configuration?

This is how I'm using the grc plugin in fish with Home Manager https://nixos.wiki/wiki/Fish#Configuration

Maybe this solves the problem for you

**Comment by Schweber** [comment]
Hah, you finally made me use home-manager! 😉

With home-manager it works. Previously, i installed the fishPlugins as environmentPackages and configured fish the ordinary way via its `config.fish` file. All other Plugins from Nixos worked fine but the `grcPlugin` doesn't because of the error with `cat`. 

So i guess that this could be fixed but i'm no expert.

**Comment by onny** [comment]
Hey @Schweber

I can reproduce the problem now in a virtual machine. I'll try to fix the package and add an additional section to the NixOS wiki page on how to use plugins without Home Manager (by just putting them into environment.systemPackages)

**Comment by Schweber** [comment]
Thanks!

**Comment by onny** [comment]
Added an example configuration for enabling plugins system wide to the Wiki page https://nixos.wiki/wiki/Fish#System_wide

The following PR fixes system wide usage https://github.com/NixOS/nixpkgs/pull/214144

Thank you for the bug report :)

**Comment by Schweber** [comment]
Thank you!

**Comment by tqwewe** [comment]
Is there any advice on how I could use this change as of now? I'm new to NixOS and am having the same issue currently. I'm wondering if I can use this patch before its released

**Comment by Schweber** [comment]
As a general tip, at the beginning of your `configuration.nix` add the following:

```
{ config, pkgs, lib, ... }:

let
  unstableTarball = fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
 in {
  imports = [
    ./hardware-configuration.nix
  ];
  nixpkgs.config = {
    packageOverrides = pkgs: {
      unstable = import unstableTarball { config = config.nixpkgs.config; };
    };
  };
```

and then you can prefix every package with `unstable.` that you want from unstable. In this case, you could have added `unstable.fishPlugins.grc` to `environment.systemPackages = with pkgs; [`
