### ISSUE TITLE
X11: Different deviceSection for different GPU devices

### ISSUE THREAD

**Issue by jokogr** [NixOS/nixpkgs#20861]
## Issue description

I recently got a secondary graphics card and I set in configuration.nix the following:

```
services.xserver.deviceSection = ''
   BusID       "PCI:1:0:0"
 '';
```

This configuration propagates to all my GPU devices, which is an issue. Any thoughts on how to tackle with this?

## Technical details

* System: NixOS 17.03.git.5f25ae3
* Nix version: 1.11.4
* Nixpkgs version: 16.09pre90254.6b20d5b

**Comment by 7c6f434c** [comment]
>This configuration propagates to all my GPU devices, which is an issue. Any thoughts on how to tackle with this?

Short term dirty hack:
```
       videoDrivers = lib.mkForce [];
       drivers = [
       ({ driverName = ''nouveau"
        BusID "PCI:1:0:0'';
        name = "nouveau";
        modules = [pkgs.xorg.xf86videonouveau]; 
        })
       ({ driverName = ''intel"
        BusID "PCI:0:2:0''; 
        name = "intel";
        modules = [pkgs.xorg.xf86videointel];
        })
```

(it is like SQL injection, only with Nix!)

Long term this could be probably supported by adding some attributes 
that don't need breaking out of the quoting…

**Comment by Profpatsch** [comment]
(triage) is there anything additional that should be done here?

**Comment by 7c6f434c** [comment]
Well, functionality as requested in the original message would be useful and it is still not in NixOS.

**Comment by Profpatsch** [comment]
Would you be willing to submit a pull request?

**Comment by 7c6f434c** [comment]
Me — probably not.

**Comment by Profpatsch** [comment]
Hm, I guess if someone wants it, they will implement it.
