### ISSUE TITLE
Bluetooth not working (DBus permission issue)

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#20864]
## Issue description

On rebuilds and boots after `hardware.bluetooth.enable` is set to `true`:
```
warning: the following units failed: dbus-org.bluez.service

● dbus-org.bluez.service - Bluetooth Service
   Loaded: loaded (/nix/store/4dndnjnk0pl2lxdypc4m6p3lk4kx7gpx-unit-dbus-org.bluez.service/dbus-org.bluez.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-12-02 19:05:18 GMT; 23ms ago
  Process: 1363 ExecStart=/nix/store/jbcf5za79gvhllayq9pzn1v15c96gvh0-bluez-5.40/bin/bluetoothd -n (code=exited, status=1/FAILURE)
 Main PID: 1363 (code=exited, status=1/FAILURE)
   Status: "Starting up"

Dec 02 19:05:18 computer systemd[1]: Starting Bluetooth Service...
Dec 02 19:05:18 computer bluetoothd[1363]: bluetoothd[1363]: Bluetooth daemon 5.40
Dec 02 19:05:18 computer bluetoothd[1363]: Bluetooth daemon 5.40
Dec 02 19:05:18 computer bluetoothd[1363]: D-Bus setup failed: Connection ":1.252" is not allowed to own the service "org.bluez" due to security policies in the configuration file
Dec 02 19:05:18 computer bluetoothd[1363]: bluetoothd[1363]: Unable to get on D-Bus
Dec 02 19:05:18 computer systemd[1]: dbus-org.bluez.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 19:05:18 computer systemd[1]: Failed to start Bluetooth Service.
Dec 02 19:05:18 computer systemd[1]: dbus-org.bluez.service: Unit entered failed state.
Dec 02 19:05:18 computer systemd[1]: dbus-org.bluez.service: Failed with result 'exit-code'.
```

### Steps to reproduce

Set `hardware.bluetooth.enable` to `true`, `nixos-rebuild switch`

## Technical details

* System: 16.09.1135.b833b10 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1135.b833b10"

**Comment by lheckemann** [comment]
I think this might somehow be caused by `etc/dbus-1/system.d/bluetooth.conf` from bluez not being taken into account by D-Bus, but that's just a guess.

**Comment by ari-becker** [comment]
Just downloaded NixOS to try it out and suffering from the same problem on a clean build

**Comment by lheckemann** [comment]
> on a clean build

All builds are clean on NixOS, that's what's so nice about it ;) I'm going to take a look to see if I can fix it myself one of these days.

**Comment by joepie91** [comment]
Also experiencing this issue. I'm unable to find a workaround, but I know that this worked fine on an older NixOS setup about a year ago. I'm not sure what has changed?

**Comment by joepie91** [comment]
An update: as a result of #19034 I went to investigate whether *restarting* the DBus daemon solves the problem. I managed to crash my system that way, but yes, after a restart of the daemon, the service works fine. It's only *reloading* the configuration that causes a problem.

**Comment by polyrod** [comment]
Workaround: add the user owning dbus process to group lp

**Comment by bast** [comment]
Confirming that adding the user to group "lp" and explicitly setting `hardware.bluetooth.enable = false` solved this issue for me.

**Comment by joepie91** [comment]
@bast That's odd. What necessitated setting `hardware.bluetooth.enable = false`? This seems like it should do the opposite...

**Comment by bast** [comment]
Sorry I should have given more context: I was interested in installing gnome3 (and not in Bluetooth support) which failed with the error on top of this thread. Then I added the user to "lp", still same or similar error (don't have that screen anymore), then finally I set `hardware.bluetooth.enable = false` and then my gnome3 installation ran smoothly.

**Comment by Mic92** [comment]
It seems to me that dbus has to be restarted in order to load bluez's configuration policies. Does the problems persist after reboot?

**Comment by joepie91** [comment]
@Mic92 For me, the issue was resolved after a DBus restart. The original post suggests that the issue wasn't solved by a reboot for @lheckemann, though.

It has kept working for me after reboots, but I don't know whether this is just because I manually restarted DBus once, or whether it would automatically work after a reboot anyway.

**Comment by Mic92** [comment]
Hopefully solved in future by: https://github.com/NixOS/nixpkgs/pull/20871

**Comment by Mic92** [comment]
Because of #20871 Dbus should be now restarted automatically after `hardware.bluetooth.enable` is changed.
