### ISSUE TITLE
Ephemeral rootfs setup:  root user doesn't get password set

### ISSUE THREAD

**Issue by sjau** [NixOS/nixpkgs#208766]
### Describe the bug
On my server I followed @grahamc 's guide on setting up an ephemeral rootfs server (see his blog post [https://grahamc.com/blog/erase-your-darlings](https://grahamc.com/blog/erase-your-darlings) ). However I'm having problem giving the root user a password. Whenever I look at the shadow file, it does not contain any password hash.

So I wanted to test this out now in a VM and I have the same results. For easier testing I did write a small bash script to automate the partitioning and zfs setup as well as  a basic configuration file to be used with it.

### Steps To Reproduce
1. Setup a VM (100GB virtual disk), copy `installer` script and the `configuration.nix` (see blow) to the same folder
2. Run the `installer` script. This will just do the partitioning and setup the zpool and copy the configuration.nix to its proper location
3. Run `nixos-install` and then reboot

Password for both (user `root` and user `hyper`) is: `thisisatest`

### Expected behavior
After reboot you should be able to login as `root` user with the password above. Also you should see the hashed password in the `/etc/shadow` file.

However you can't login and the hashed password entry for the root user in the shadow file is empty. For the user `hyper` login works.

The `/etc/shadow` looks after reboot like this:
```
[...]
root:!:1::::::
[...]
hyper:$6$t/ER3ncagRvDGY/d$IL9OEPymL8.t97V/PKOA4CRX9wWsvqcHp.6oGAnfRACB54FqlSTa7FLlQqKrcqr2uH.iohlJnNgHnZdm2U2A5[...]
```

### Additional context
I tried with omitting the `mutableUserscd` option and setting it to false. Neither worked.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 23.05 (Stoat), 23.05pre435935.04f574a1c0f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Files
`Installer`:
```
#!/usr/bin/env bash

# Restore partition layout
echo 'label: gpt
label-id: 6B6AEDAF-736B-A145-8753-D9C27A82D7F2
device: /dev/sda
unit: sectors
first-lba: 34
last-lba: 209715166
sector-size: 512

/dev/sda1 : start=        2048, size=       20480, type=21686148-6449-6E6F-744E-656564454649, uuid=B88A0C6F-1835-4D9B-9AF3-C71ACDC7F9BF, name="BIOS boot partition"
/dev/sda2 : start=       22528, size=     2097152, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=6C90F2B6-9D19-43FC-8C99-C6D1717A2626, name="EFI system partition"
/dev/sda3 : start=     2119680, size=   207593472, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=CF83F42F-BE1A-4366-8CB3-8E7383A50491, name="Linux filesystem"' > part_table

sfdisk --force /dev/sda < part_table

# Format EFI partition
mkfs.fat -F 32 /dev/sda2

# Create Pool
zpool destroy tankTest
zpool create -f -o ashift=12 -o altroot="/mnt" -O mountpoint=none -O compression=zstd-2 -O atime=off -O xattr=sa -O acltype=posixacl -O normalization=formD -O relatime=on "tankTest" "/dev/sda3"

# Create Base Datasets
zfs create tankTest/encZFS
zfs create -o mountpoint=legacy tankTest/encZFS/Nixos

# Create Perma Datasets
zfs create tankTest/encZFS/Nixos/p
zfs create tankTest/encZFS/Nixos/p/data
zfs create tankTest/encZFS/Nixos/p/etc
zfs create tankTest/encZFS/Nixos/p/etc/nixos
zfs create tankTest/encZFS/Nixos/p/home
zfs create tankTest/encZFS/Nixos/p/root

# Create Volatile Datasets
zfs create tankTest/encZFS/Nixos/v
zfs create tankTest/encZFS/Nixos/v/rootfs
zfs create tankTest/encZFS/Nixos/v/nix

# Create Blank Snapshot
zfs snapshot tankTest/encZFS/Nixos/v/rootfs@blank

# Mount Partitions and Datasets
mount -t zfs tankTest/encZFS/Nixos/v/rootfs /mnt
mkdir /mnt/boot
mount /dev/sda2 /mnt/boot
mkdir /mnt/data
mount -t zfs tankTest/encZFS/Nixos/p/data /mnt/data
mkdir -p /mnt/etc/nixos
mount -t zfs tankTest/encZFS/Nixos/p/etc/nixos /mnt/etc/nixos
mkdir /mnt/home
mount -t zfs tankTest/encZFS/Nixos/p/home /mnt/home
mkdir /mnt/root
mount -t zfs tankTest/encZFS/Nixos/p/root /mnt/root
mkdir /mnt/nix
mount -t zfs tankTest/encZFS/Nixos/v/nix /mnt/nix

# Create Nixos Configurations
nixos-generate-config --root /mnt

# Copy configuration.nix
cp configuration.nix /mnt/etc/nixos/configuration.nix
```

`configuration.nix`:
```
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, ... }:

{
    imports =
        [ # Include the results of the hardware scan.
            ./hardware-configuration.nix
        ];

    # Use the systemd-boot EFI boot loader.
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = true;

    # Rollback RootFS Dataset
    boot.initrd.postDeviceCommands = lib.mkAfter ''
        zfs rollback -r tankTest/encZFS/Nixos/v/rootfs@blank
    '';

    # Add more filesystems
    boot.supportedFilesystems = [ "zfs" ];
    boot.zfs.enableUnstable = true;
    boot.zfs.devNodes = "/dev";
    services.zfs.autoScrub = {
        enable = true;
        interval = "monthly";
        pools = [ ]; # List of ZFS pools to periodically scrub. If empty, all pools will be scrubbed.
    };

    # Trust hydra. Needed for one-click installations.
    nix.settings.trusted-substituters = [ "http://hydra.nixos.org" ];

    networking = {
        useDHCP = true;
        nameservers = [ "10.10.10.1" "8.8.8.8" "8.8.4.4" ];
        hostName = "testi"; # Define your hostname.
        hostId = "100000cc";
        firewall = {
            enable = false;
            allowPing = true;
	};
    };



    # Enable dbus
    services.dbus.enable = true;

    # Select internationalisation properties.
    console.font = "Lat2-Terminus16";
    console.keyMap ="sg-latin1";
    i18n = {
        defaultLocale = "en_US.UTF-8";
        supportedLocales = [ "all" ];
    };

    # Enable the OpenSSH daemon.
    services.openssh = {
        enable = true;
        hostKeys = [
            {   path = "/data/ssh_host_ed25519_key";
                type = "ed25519"; }
            {   path = "/data/ssh_host_rsa_key";
                type = "rsa";
                bits = 4096; }
        ];
        permitRootLogin = "yes";
        ports = [ 22 23 ];
    };

    # Enable nscd
    services.nscd = {
        enable = true;
    };

    # Enable ntp or rather timesyncd
    services.timesyncd = {
        enable = true;
        servers = [ "0.ch.pool.ntp.org" "1.ch.pool.ntp.org" "2.ch.pool.ntp.org" "3.ch.pool.ntp.org" ];
    };

    # Time.
    time.timeZone = "Europe/Zurich";

    # Enable sudo
    security.sudo = {
        enable = true;
        wheelNeedsPassword = true;
    };

    # Define a user account. Don't forget to set a password with ‘passwd’.
    users.defaultUserShell = "/run/current-system/sw/bin/bash";
    users.mutableUsers = false;
    users.users = {
        root = {
            hashedPassword = "$6$t/ER3ncagRvDGY/d$IL9OEPymL8.t97V/PKOA4CRX9wWsvqcHp.6oGAnfRACB54FqlSTa7FLlQqKrcqr2uH.iohlJnNgHnZdm2U2A5/";
        };
        hyper = {
            isNormalUser = true;    # creates home, adds to group users, sets default shell
            createHome = false;
            home = "/home/hyper";
            description = "hyper";
            extraGroups = [ "networkmanager" "vboxusers" "wheel" "audio" "cdrom" "kvm" ]; # wheel is for the sudo group
            uid = 1000;
            hashedPassword = "$6$t/ER3ncagRvDGY/d$IL9OEPymL8.t97V/PKOA4CRX9wWsvqcHp.6oGAnfRACB54FqlSTa7FLlQqKrcqr2uH.iohlJnNgHnZdm2U2A5/";
        };
    };

    # Enable Locate
    services.locate.enable = true;

    # Bash completion
    programs.bash.enableCompletion = true;

    # Setup nano
    programs.nano.nanorc = ''
        set nowrap
        set tabstospaces
        set tabsize 4
        set constantshow
        # include /usr/share/nano/sh.nanorc
    '';



    system.stateVersion = "23.05"; # Did you read the comment?

    nixpkgs.config.allowUnfree = true;

    environment.systemPackages = with pkgs; [
        bash-completion
    	curl
    	htop
        jq
    	mc
    	tmux
    ];

}
```

**Comment by lilyinstarlight** [comment]
Does setting `users.users.root.initialHashedPassword = null` fix it?

I'm not great at following Perl code, but it looks like `initialHashedPassword` may override `hashedPassword` unconditionally when a user is first created (see code [here](https://github.com/NixOS/nixpkgs/blob/677ed08a50931e38382dbef01cba08a8f7eac8f6/nixos/modules/config/update-users-groups.pl#L215-L223)), which is always true when `users.mutableUsers = false`, and root's `initialHashedPassword` value is defaulted to `"!"`: https://github.com/NixOS/nixpkgs/blob/677ed08a50931e38382dbef01cba08a8f7eac8f6/nixos/modules/config/users-groups.nix#L539-L546

**Comment by sjau** [comment]
I think you are right. For user root I did set now the and rebuild `initalHashedPassword = "$......";` --> password was set for root.
I did then set `ìnitialHashedPassword = null; hashedPassword = "$..."` --> password was set for root.

After that, I removed the `mutableUser = false;` line and again set `ìnitialHashedPassword = null; hashedPassword = "$..."` --> password was set for root.

The problem really seems to be the `initialHashedPassword`.

**Comment by tejing1** [comment]
> I'm not great at following Perl code, but it looks like initialHashedPassword may override hashedPassword unconditionally when a user is first created (see code here), which is always true when users.mutableUsers = false, and root's initialHashedPassword value is defaulted to "!":

There must be more to it than this, since I'm [using](https://github.com/tejing1/nixos-config/tree/0357261dc1f99361baa065119febc293c49d8597/nixosConfigurations/tejingdesk) `mutableUsers = false` and `hashedPassword` yet my root password works fine, despite `initialHashedPassword` evaluating to `"!"`.

**Comment by lilyinstarlight** [comment]
So reading over the Perl script more, it actually does still do some merge-ish logic even when `mutableUsers = false` (rather than just obliterating `/etc/{passwd,shadow,group}` like I had assumed)

I'm assuming you do not have an ephemeral rootfs then @tejing1?

**Comment by tejing1** [comment]
> I'm assuming you do not have an ephemeral rootfs then @tejing1?

That's the funny thing, I *do*.

**Comment by tejing1** [comment]
I *can*, however, reproduce the issue with a pretty minimal setup:

```
$ cat tmpvm.nix
{
  users.mutableUsers = false;
  users.users.root.hashedPassword = "$6$HuX6Gw0FULy9.XRh$D.Z7qB7PkM69LHD5O/2ThmKJJ9p6R6A4qa9nfuXAkPRkur0GNkK7JECDi45YkA8G6XQToJjvTGnpbGPw.1WA.1";
}
$ command nixos-rebuild build-vm -I nixos-config="$PWD/tmpvm.nix" --no-flake && rm -f nixos.qcow2 && ./result/bin/run-nixos-vm
```
and adding `users.users.root.initialHashedPassword = null;` does indeed solve it.

(Don't worry about that password hash, it's throwaway; the password is "test")

**Comment by tejing1** [comment]
Aha, I've found out why my main machine doesn't appear to have the problem: The *second* time the activation script is run, it fixes itself due to the root user already existing in /etc/shadow. So on my main machine, since I've run a rebuild since my last boot, it works.

You can show this with my `tmpvm.nix` above by starting the vm a second time without deleting `nixos.qcow2`. On the second boot you can log in.

**Comment by lilyinstarlight** [comment]
Thanks for digging into that @tejing1!

I feel like `initialHashedPassword` shouldn't overwrite `hashedPassword` if its already set in general, so I may make a PR to adjust that behavior (because I can't imagine a scenario where that wouldn't be a surprising behavior), and I'll see if I can add a test too

Not looking forward to touching Perl code though... (or testing it enough to ensure I didn't break something else in that spaghetti-logic...)

**Comment by sjau** [comment]
> Thanks for digging into that @tejing1!
> 
> I feel like `initialHashedPassword` shouldn't overwrite `hashedPassword` if its already set in general

I agree with that. If I set a hashedPassword I expect it to be set. That's why I originally just used hashedPassword and did not set ```initialHashedPassword = null;```

**Comment by sjau** [comment]
I don't really know perl also, but shouldn't it be like this:

```
    } else {
        $u->{uid} = allocUid($name, $u->{isSystemUser}) if !defined $u->{uid};

        if (defined $u->{hashedPassword}) {
            # a set hashedPassword doesn't need any change and superseeds the rest
        } elsif (defined $u->{initialPassword}) {
            $u->{hashedPassword} = hashPassword($u->{initialPassword});
        } elsif (defined $u->{initialHashedPassword}) {
            $u->{hashedPassword} = $u->{initialHashedPassword};
        }
    }
```

**Comment by lilyinstarlight** [comment]
> I don't really know perl also, but shouldn't it be like this:
> 
> ```
>     } else {
>         $u->{uid} = allocUid($name, $u->{isSystemUser}) if !defined $u->{uid};
> 
>         if (defined $u->{hashedPassword}) {
>             # a set hashedPassword doesn't need any change and superseeds the rest
>         } elsif (defined $u->{initialPassword}) {
>             $u->{hashedPassword} = hashPassword($u->{initialPassword});
>         } elsif (defined $u->{initialHashedPassword}) {
>             $u->{hashedPassword} = $u->{initialHashedPassword};
>         }
>     }
> ```

Something like that, yeah! I'll try to do some testing and make a PR within the next week, unless you or someone else would like to first

**Comment by sjau** [comment]
Maybe add another condition that hashedPassword must not be "" or "!". Although no idea if that is important. What I gather from the /etc/shadow file is that hashed passwords always start with $.

**Comment by lilyinstarlight** [comment]
PR: 209606

**Comment by sjau** [comment]
Thanks for that. But why also change the shadow.nix file?

**Comment by tejing1** [comment]
> Thanks for that. But why also change the shadow.nix file?

If you study the changes more closely, you'll notice the only change was to the testing system. A test was added, to ensure this kind of usecase behaves appropriately.
