### ISSUE TITLE
glaxnimate

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#208707]
**Project description**

simple and fast vector graphics animation program. glaxnimate works with vector graphics, this means images are described with objects like lines, curves, and points.

![img](https://glaxnimate.mattbas.org/img/screenshots/main_window/main_window.png)

**Metadata**

* homepage URL: https://glaxnimate.mattbas.org
* source URL: https://gitlab.com/mattbas/glaxnimate/-/releases
* license: GPLv3+ <https://gitlab.com/mattbas/glaxnimate#license>
* platforms: unix, linux, darwin

**Comment by Schweber** [comment]
`kdenlive` shows 

```
Missing MLT module: glaxnimate
required to load Lottie animations
```

on Nixos 22.11. It still works but it would be nice to have glaxnimate available.

@turion Is it possible to package `glaxnimate` and include it in `kdenlive`?

**Comment by tobiasBora** [comment]
Just can up with this
```
{ lib
, stdenv
, fetchFromGitLab
, cmake
, zlib
, potrace
, ffmpeg
, libarchive
, python3
, full
, wrapQtAppsHook
  # Python3
}:

stdenv.mkDerivation rec {
  pname = "glaxnimate";
  version = "0.5.1";

  src = fetchFromGitLab {
    owner = "mattbas";
    repo = "${pname}";
    rev = "${version}";
    sha256 = "G4ykcOvXXnVIQZUYpRIrALtDSsGqxMvDtcmobjjtlKw=";
    fetchSubmodules = true;
  };

  nativeBuildInputs = [
    cmake
    wrapQtAppsHook
  ];
  
  buildInputs = [
    zlib
    potrace
    ffmpeg
    # gst_all_1.gst-libav # Note that since gst-libav-1.6, libav is actually ffmpeg
    libarchive
    python3
    full    
  ];

  meta = with lib; {
    homepage = "https://gitlab.com/mattbas/glaxnimate";
    description = "Simple vector animation program.";
    license = licenses.gpl3;
    maintainers = with maintainers; [ tobiasBora ];
    platforms = platforms.linux;
  };
}

```
it works but when I integrate it in nixpkgs I get an error about 
```
Package ‘qtwebkit-5.212.0-alpha4’ in /home/leo/nixpkgs/pkgs/development/libraries/qt-5/qtModule.nix:72 is marked as insecure, refusing to evaluate.
```
so I need to investigate

**Comment by Schweber** [comment]
Thank you for your effort!

> it works but when I integrate it in nixpkgs I get an error about
> 
> ```
> Package ‘qtwebkit-5.212.0-alpha4’ in /home/leo/nixpkgs/pkgs/development/libraries/qt-5/qtModule.nix:72 is marked as insecure, refusing to evaluate.
> ```
> 
> so I need to investigate

You can override that with `nixpkgs.config.permittedInsecurePackages = [ "qtwebkit-5.212.0-alpha4" ];`.

Unfortunately, this package is compiled locally and takes quite a while. I don't know why it's not built by hydra.

**Comment by turion** [comment]
:+1: for adding `glaxnimate`. It looks like a sane program that can be packaged without headaches.

It's weird that `qtwebkit` is pulled in here. `qtwebkit` is insecure afaik and shouldn't be used anymore. See https://github.com/NixOS/nixpkgs/issues/53079. And it seems to me that `glaxnimate`  doesn't need `qtwebkit`, so it's added as a transitive dependency somehow.

**Comment by tobiasBora** [comment]
Qtwebkis just go added because I used qtfull instead of manually adding the libraries one by one.

But please test the program in https://github.com/NixOS/nixpkgs/pull/209669 as I don't know how to test it beside runnig it. In particular the python stuff might need some wrapping but no idea/time how to test it.

**Comment by turion** [comment]
> `kdenlive` shows
> 
> ```
> Missing MLT module: glaxnimate
> required to load Lottie animations
> ```
> 
> on Nixos 22.11. It still works but it would be nice to have glaxnimate available.

Can you give more details on how to reproduce? I can't see this error. Do I have to do anything special to trigger it?

**Comment by turion** [comment]
(Ideally, as a separate issue.)

**Comment by hervyqa** [comment]
hi @turion. how do i know if this pkgs status goes into repo 22.11?

**Comment by turion** [comment]
You can use git for example. There is also a webservice: https://nixpk.gs/pr-tracker.html You have to enter the number of the PR there.

**Comment by Schweber** [comment]
> Can you give more details on how to reproduce? I can't see this error. Do I have to do anything special to trigger it?

@turion It happened when launching `kdenlive` for the first time i.e. without config files in my home directory. Then it apparently registered that i aknowledged the message and didn't show it again. It was a message window that had to be aknowledged with "ok" or something like that. No fatal error, just an information.

I think that `kdenlive` is working correctly in this regard and that i shouldn't file an issue about that.

**Comment by tobiasBora** [comment]
Oh very true… I just tried by doing
```
$ mkdir /tmp/home
$ export HOME=/tmp/home
$ nix run github:NixOs/nixpkgs/0c9aadc8eff6daaa5149d2df9e6c49baaf44161c#kdenlive
```
![image](https://user-images.githubusercontent.com/2164118/211380665-4985ba84-5aca-44bf-b90c-0da52e9a1e5b.png)

I created an issue here https://github.com/NixOS/nixpkgs/issues/209923
