### ISSUE TITLE
Nitter is unable to fetch a token if service starts before network is fully up

### ISSUE THREAD

**Issue by erdnaxe** [NixOS/nixpkgs#208797]
### Describe the bug

This issue was described by kvtb at https://discourse.nixos.org/t/how-to-append-string-to-existing-value-from-a-module/24335/6

Quoting:
> This is specific to the Nitter module. If the systemd service starts before the network is fully up, Nitter will not be able to fetch a token and you will always get this message:
> Instance has been rate limited.
> Use another instance or try again later.

### Proposed solution (courtesy of kvtb)

Extende the ExecStartPre with something like:

```nix
systemd.services.nitter.serviceConfig.ExecStartPre = ''
   ${pkgs.busybox}/bin/sh -c '(while ! ${pkgs.busybox}/bin/nc -z -v -w1 twitter.com 443 2>/dev/null; do
        echo "Waiting for Twitter to be reachable...";
        sleep 2;
      done); sleep 2'
''
```

### Additional notes

Currently the unit depends on `After=network.target`, maybe there is something smarter to do.

**Comment by justinas** [comment]
> Currently the unit depends on `After=network.target`, maybe there is something smarter to do.

`network-online.target` might be more suitable?

> `network-online.target` is a target that actively waits until the nework is "up", where the definition of "up" is defined by the network management software. Usually it indicates a configured, routable IP address of some kind.
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
