### ISSUE TITLE
Discord (ordinary) with openasar doesn't work

### ISSUE THREAD

**Issue by dibusure** [NixOS/nixpkgs#208749]
### Describe the bug
When i open the discord (at cli too) it crashes with error:
```[OpenAsar > BuildInfo] { releaseChannel: 'stable', version: '0.0.22' }
[OpenAsar > Modules] Checking
Error: Cannot find module '/home/dibusure/.config/discord/0.0.22/modules/discord_desktop_core'
Require stack:
- /nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/utils/requireNative.js
- /nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/bootstrap.js
- /nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (/nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/utils/requireNative.js:1:74)
    at startCore (/nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/bootstrap.js:1:1448)
    at EventEmitter.<anonymous> (/nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/bootstrap.js:1:2467)
    at Object.onceWrapper (events.js:421:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/utils/requireNative.js',
    '/nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/bootstrap.js',
    '/nix/store/30i97k1vnv44j23qrw8xix0bh9xyrirs-discord-0.0.22/opt/Discord/resources/app.asar/index.js',
    undefined
  ]
} uncaughtException
```

### Steps To Reproduce
1. Install discord with openasar according to [wiki](https://nixos.wiki/wiki/Discord#OpenAsar)
2. Run `discord` in terminal

### Expected behavior
Discord is launching normally with openasar and opening openasar settings

### Screenshots
Output in "Describe the bug"

### Additional context
0-0

### Notify maintainers
@MP2E @devins2518 @artturin @infinidoge

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.11 (Raccoon), 22.11.20221230.6a0d270`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Infinidoge** [comment]
Hmm,
Given that it's saying it's missing a module in the Discord `.config` folder, I'm not sure if it's a Nix problem, it might just be that Discord updated and changed things which separately broke OpenAsar.

Will try and build/run on my machine once I'm back on a computer

**Comment by dibusure** [comment]
>I'm not sure if it's a Nix problem, it might just be that Discord updated and changed things which separately broke OpenAsar.

I'm sure it is

**Comment by Artturin** [comment]
> > I'm not sure if it's a Nix problem, it might just be that Discord updated and changed things which separately broke OpenAsar.
> 
> I'm sure it is

then have you confirmed that it does not replicate with https://github.com/GooseMod/OpenAsar/wiki/Install-Guide ?


does discord_desktop_core contain these 3 files?
```
$ ls .config/discord/0.0.22/modules/discord_desktop_core
core.asar  index.js  package.json
```

**Comment by dibusure** [comment]
> does discord_desktop_core contain these 3 files?

i installed via nixpkgs overlay
i said this in "Steps To Reproduce" block

**Comment by Artturin** [comment]
discord downloads its main files at runtime which we can't control

**Comment by dibusure** [comment]
> 

So what can i do?

**Comment by Infinidoge** [comment]
Hmm. If that is the case, then this does seem to be a flaw with how OpenAsar is handled Nix-side then.
I'm not really sure how that could be fixed, though, outside of trying to run Discord during/before the build to generate the necessary files, which seems... bad.

**Comment by 6e6f61** [comment]
IMO this issue should stay open until a workaround is implemented, or this is at least documented somewhere. $VERY_POPULAR_PROGRAM inexplicably breaking every update is pretty poor UX.

**Comment by Artturin** [comment]
openasar isn't $VERY_POPULAR_PROGRAM, it's a unsupported mod.

Is there anything nixpkgs specific to do here, or is it a upstream documentation issue.

**Comment by Artturin** [comment]
Added workaround instruction to https://nixos.wiki/wiki/Discord#OpenAsar_.2F_Vencord

**Comment by Artturin** [comment]
Maybe there could be a script which launches an unmodified discord when there's an error containing `MODULE_NOT_FOUND`, but then the discord size will be duplicated

**Comment by 6e6f61** [comment]
> openasar isn't $VERY_POPULAR_PROGRAM, it's a unsupported mod.
> 
> Is there anything nixpkgs specific to do here, or is it a upstream documentation issue.
> 
> Anyone can edit the nixos wiki so quirks can be added there.

I agree, I was wrong. I apologise. I don't think there much more we can do here; Nix pulling `discord_desktop_core` itself seems too brittle IMO, so this is up to OpenASAR.

**Comment by RGBCube** [comment]
> Maybe there could be a script which launches an unmodified discord when there's an error containing `MODULE_NOT_FOUND`, but then the discord size will be duplicated. It could print instructions.

Instructuons would be the best solution
