### ISSUE TITLE
Pandoc + LaTeX? Compose/sequence derivations?

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#20887]
I'd like to build a derivation that runs Pandoc to convert my markdown file into a .tex file, and then uses the outputted .tex file as the input to `pkgs.texFunctions.runLaTeX`. Is this possible?

**Comment by FRidh** [comment]
Sure. Any particular reason you don't want to use pandoc to go to pdf via latex?

Here's an example of how to use runCommand to convert from markdown to latex with pandoc.
```
with import <nixpkgs> {};
let
  markdown_to_latex = filename: let
    name = lib.nameFromURL (builtins.toString filename) ".";
  in pkgs.runCommand  "${name}.tex" {
    buildInputs = [ pandoc ];
  } ''
    pandoc ${filename} -o $out
  '';
in markdown_to_latex ./example.md
```

**Comment by sid-kap** [comment]
It seems like this derivation converts the md to a tex. How do I then use pdflatex to convert it to a pdf? In other words, if I have one derivation that converts md -> tex, and another derivation that converts tex -> pdf, can I somehow make a derivation that does both in sequence?

**Comment by FRidh** [comment]
@sid-kap maybe pass it to `runLatex`?

**Comment by vcunat** [comment]
Also, `pandoc` can directly produce a `*.pdf` if you ask it, but you would probably need to pass extra build inputs.

**Comment by sid-kap** [comment]
@FRidh I don't see any argument in [https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/typesetting/tex/nix/default.nix](runLaTeX) that allows me to provide a pre-build argument. Could I maybe use overrideDerivation to add a pre-processing step?

**Comment by sid-kap** [comment]
@vcunat Do you know what the standard packages needed to run pdflatex are? Is it tetex?

**Comment by vcunat** [comment]
`texlive.combined.scheme-basic` might be enough.

**Comment by FRidh** [comment]
@sid-kap 
```nix
with import <nixpkgs> {};
let
  markdown_to_pdf = filename: let
    name = lib.nameFromURL (builtins.toString filename) ".";
  in pkgs.runCommand  "${name}.pdf" {
    buildInputs = [ pandoc texlive.combined.scheme-small ];
  } ''
    pandoc ${filename} -o $out
  '';
in markdown_to_pdf ./example.md
```

**Comment by sid-kap** [comment]
@FRidh That worked for me, thanks!
