### ISSUE TITLE
Distrobox and GUI apps

### ISSUE THREAD

**Issue by k1mbl3** [NixOS/nixpkgs#208817]
It seems that distrobox is failing to get access to the host's display

```
k1mbl3@main:~$ steam 
steam.sh[214411]: Running Steam on fedora 36 64-bit
steam.sh[214411]: STEAM_RUNTIME is enabled automatically
setup.sh[214484]: Updating Steam runtime environment...
No protocol specified

(zenity:214492): Gtk-WARNING **: 19:04:43.013: cannot open display: :0.0
```
```
k1mbl3@main:~$ xterm
No protocol specified
xterm: Xt error: Can't open display: :0.0
```
```
k1mbl3@distrobox-LKzkeccip8:~$ dolphin 
No protocol specified
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```
```
k1mbl3@distrobox-UINYSTzj7R:~$ gnome-terminal
No protocol specified
# Failed to parse arguments: Cannot open display: 
```
Versions:
```
k1mbl3@nixos:~$ docker --version
Docker version 20.10.21, build v20.10.21
k1mbl3@nixos:~$ distrobox --version
distrobox: 1.4.1
k1mbl3@nixos:~$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.83, NixOS, 22.11 (Raccoon), 22.11.1105.9898811c658`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vivlim** [comment]
I hit this too, in my case the issue was X blocking access from the container.

distrobox [suggests using](https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#compatibility-notes) `xhost +si:localuser:$USER` on the host to grant access. I'm not sure if this is the best way to grant access to the container, but it seems to work for me.

**Comment by k1mbl3** [comment]
> 

Nice! Is there any way to run it on the configuration.nix?

**Comment by vivlim** [comment]
I'm not sure, it probably depends on what desktop environment you use if any, and how you manage your dotfiles.

I think the important thing is that it runs as your user after you log in & start a graphical x session.

**Comment by k1mbl3** [comment]
> 

I'm new to nix. It would be nice to have this preconfigured during installation, otherwise other newcomers could become completely lost like i was

**Comment by Pherrara** [comment]
> I hit this too, in my case the issue was X blocking access from the container.
> 
> distrobox [suggests using](https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#compatibility-notes) `xhost +si:localuser:$USER` on the host to grant access. I'm not sure if this is the best way to grant access to the container, but it seems to work for me.

Thanks, fixed the issue for me.
