### ISSUE TITLE
Packaging Request: Upscayl

### ISSUE THREAD

**Issue by AmeerTaweel** [NixOS/nixpkgs#208865]
**Project description**

Free and Open Source AI Image Upscaler for Linux, MacOS and Windows built with Linux-First philosophy.

**Metadata**

* Homepage URL: https://upscayl.github.io
* Source URL: https://github.com/upscayl/upscayl
* License: AGPL-3.0
* Platforms: Linux + Darwin

**Comment by QuantMint** [comment]
[#192465](https://github.com/NixOS/nixpkgs/pull/192465)
