### ISSUE TITLE
spark2014 'gnatprove' does not work out of the box due to missing gnatwhy3

### ISSUE THREAD

**Issue by thoughtpolice** [NixOS/nixpkgs#208830]
/cc @jiegec

Consider the following example: https://gist.github.com/thoughtpolice/df01ea4fb712ff4804ff92b2f9d01599

```bash
git clone https://gist.github.com/thoughtpolice/df01ea4fb712ff4804ff92b2f9d01599 spark-example
cd spark-example/
nix-shell -I nixpkgs=$HOME/src/nixpkgs -p spark2014 -p gnat -p gprbuild
```

(with a recent `nixpkgs`)

Now, try to prove an error via `gnatprove -Pmain`:

```
Phase 1 of 2: generation of Global contracts ...
Phase 2 of 2: flow analysis and proof ...
+===========================GNAT BUG DETECTED==============================+
| 1.0 (spark) GCC error:                                                   |
|
raised CONSTRAINT_ERROR : spark_semaphore_wrapper.adb:61 access            |
|     check failed
                                                                           |
| No source file position information available                            |
| Compiling /home/austin/tmp/df01ea4fb712ff4804ff92b2f9d01599/hello_world.adb|
| Please submit a bug report; see https://gcc.gnu.org/bugs/ .              |
| Use a subject line meaningful to you and us to track the bug.            |
| Include the entire contents of this bug box in the report.               |
| Include the exact command that you entered.                              |
| Also include sources listed below.                                       |
+==========================================================================+

Please include these source files with error report
Note that list may not be accurate in some cases,
so please double check that the problem can still
be reproduced with the set of files listed.
Consider also -gnatd.n switch (see debug.adb).

/home/austin/tmp/df01ea4fb712ff4804ff92b2f9d01599/hello_world.adb

compilation abandoned
gnatprove: error during flow analysis and proof
```

The `spark_semaphore_wrapper` program and the line of the error is here: https://github.com/AdaCore/spark2014/blob/976bffefdc7c0319af990fb70662a05603c59408/src/gnatprove/spark_semaphore_wrapper.adb#L61

Which means it's failing during the spawning of a process. To reveal the culprit: `strace -f -s99999 -e trace=clone,execve gnatprove -Pmain`, which gives us:

```
[pid 2698938] execve("/nix/store/b2pz8v7qiwdi9w9fmnrs60a7f3izpzyl-spark2014-unstable-2022-05-25/bin/spark_semaphore_wrapper", ["/nix/store/b2pz8v7qiwdi9w9fmnrs60a7f3izpzyl-spark2014-unstable-2022-05-25/bin/spark_semaphore_wrapper", "why3server1202697839", "gnatwhy3", "--timeout", "5", "--steps", "0", "--memlimit", "1000", "--prover", "altergo", "--proof", "per_check", "--socket", "/run/user/1000/why3server1202697839.sock", "-j", "12", "--counterexample", "off", "--giant-step-rac", "off", "--debug-why3", "vc:do_not_keep_trace", "--warn-prover", "altergo", "--ce-timeout", "5", "/home/austin/src/ada-spark-demo/examples/hello_world/gnatprove/hello_world.gnat-json"], 0x7ffc1e0fa9c8 /* 119 vars */) = 0
[pid 2698938] +++ exited with 1 +++
```

It is trying to spawn a `gnatwhy3` executable, which does not exist anywhere in path.

## Root cause: wrong why3 build

After more investigation I think the original dependency on `why3` in the spark2014 expression is simply incorrect. The default version of why3 does *not* have the necessary features/tweaks for `gnatprove` to work; see this reference email: https://www.mail-archive.com/why3-club@lists.gforge.inria.fr/msg00229.html and this document: https://github.com/AdaCore/spark2014/blob/976bffefdc7c0319af990fb70662a05603c59408/docs/develguide/gnatwhy3.rst#L390

So it's a vendored dependency, i.e. evil, but a necessary evil. I don't think we should be in the business of second guessing this considering we're tampering with the underlying verification tools that are the whole selling point here...

The `why3` submodule in the original `spark2014` package is what we should be using, and what we should be pointing the `gnatprove` executable too, and what will contain `gnatwhy3` for us. So what's probably happening here is either:

1) We aren't building it at all, or
2) We aren't installing it in the right place during `installPhase`

I don't have the immediate time to figure this out, but I'm filing here so people can get a head start.

**Comment by jiegec** [comment]
Nice job! I got similar errors but was unable to find the culprit.
