### ISSUE TITLE
Commit message editor

### ISSUE THREAD

**Issue by mbledkowski** [NixOS/nixpkgs#208913]
**Project description**
Commit is an editor that helps you write better Git and Mercurial commit messages.

**Metadata**

* homepage URL: https://commit.sonny.re/
* source URL: https://github.com/sonnyp/Commit
* license: gpl3
* platforms: linux

**Comment by tomodachi94** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/318705.
