### ISSUE TITLE
Please Update Virtualbox to Latest

### ISSUE THREAD

**Issue by friczky** [NixOS/nixpkgs#208976]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: virtualbox

current version: 6.1.40
desired version: 7.0,4

###### Notify maintainers

maintainers: @svanderburg 
###### Note for maintainers

Please tag this issue in your PR.

**Comment by lucc** [comment]
@corpix do you plan to make a PR with aeef2f3?

Or maybe @svanderburg wants to cherry pick that commit?

**Comment by bjornfor** [comment]
Failed/WIP attempt at updating to 7.x: https://github.com/NixOS/nixpkgs/pull/213934
