### ISSUE TITLE
lsp-plugins, provide version-less file names.

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#208960]
Every time there's a version bump it breaks scripts and other things, a versionless lib would go a long way in making it easy to maintain references, especially for "ad-hoc" software like DAWs, that load plugins outside of nix's control.

currently I only have ` /run/current-system/sw/lib/ladspa/lsp-plugins-ladspa-1.2.4.so` in my environment, and pipewire breaks, because I have to have a reference to the file name inside it's config.

```
   {
                            type = ladspa
                            name = compress
                            plugin = lsp-plugins-ladspa-1.2.3
                            label = "http://lsp-plug.in/plugins/ladspa/compressor_stereo"
                            control = {
                                "Attack threshold (G)" = 0.0316
                                "Attack time (ms)"      = 12
                                "Knee (G)"             = 0.2585
                                "Release time (ms)"     = 250
                                "Ratio"            = 4
                                "Makeup gain (G)"      = 4
                                }
                         }
```

I would much prefer if all I had to do was specify `lsp-plugins-ladspa`, and version management can be delegated to Nix(OS), by passing the package to the service & systemPackages.

@magnetophon

**Comment by magnetophon** [comment]
@YellowOnion This seems like an upstream issue to me, not a NixOS one, as we are just using the upstream pkg as is.
Feel free to correct me if I'm wrong!
