### ISSUE TITLE
llvm-3.9: Include Polly optimiser

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20890]
Starting with Polly/LLVM 3.9, all that is needed to use Polly is download and extract the Polly source to `llvm_tools/polly` before building. After that, it's [just a matter](http://polly.llvm.org/docs/ReleaseNotes.html#polly-directly-available-in-clang-opt-bugpoint) of passing "-mllvm -polly" to clang to use it.

Thus, there should be a flag to download and build Polly in the llvm derivation (and preferably enabled by default).

**Comment by vcunat** [comment]
If it doesn't significantly increase the size of `libllvm` output, I think it might be included unconditionally (to simplify things).

**Comment by spacekitteh** [comment]
I don't think it does, actually!

**Comment by Profpatsch** [comment]
Closed in favor of PR.
