### ISSUE TITLE
git immediately dies on aarch64-darwin

### ISSUE THREAD

**Issue by Sciencentistguy** [NixOS/nixpkgs#208951]
### Describe the bug
Running `git` from nixpkgs master `nix shell github:nixos/nixpkgs/master#git` fails (it is sent signal 9 by the OS)

This appears to be a codesigning issue: (from the system log)

```
Termination Reason:    Namespace CODESIGNING, Code 2 
```
Forcing nix to build git locally solves the problem: `nix-shell --pure --run "git"` with `default.nix`: 
```nix
with import <nixpkgs> {}; let
  git = pkgs.git.overrideAttrs (old: {
      rebuildMe = true;
    });
in
  mkShell {
    buildInputs = [git];
  }
```

### Steps To Reproduce
1. be on aarch64-darwin
2. run git
3. `zsh: killed     git`

### Expected behavior
git should work

### Notify maintainers
@NixOS/darwin-maintainers 
@primeos 
@wmertens 
@globin 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.5.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(jamie): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nix/path/nixpkgs`
```

**Comment by kubukoz** [comment]
Works for me:

```bash
$ nix run github:nixos/nixpkgs/master#git status                                                                                                                                                                                                                                                                 
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
$ nix run nixpkgs#nix-info -- -m                                                                                                                                                                                                                                                                                     
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.5.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(kubukoz): `"nixpkgs"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/Users/kubukoz/.nix-defexpr/channels/nixpkgs`
```

**Comment by tricktron** [comment]
Works for me as well:

```console
nix shell github:nixos/nixpkgs/master#git
git status
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
nix run nixpkgs#nix-info -- -m
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.2`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.11.0`
 - channels(tricktron): `"darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

I am using bash though instead of zsh.

**Comment by mikroskeem** [comment]
What git rev did your nix shell pick up? This will end up different on anyone who tests this later than you, making reproducing more complicated.

**Comment by Sciencentistguy** [comment]
I first noticed it on 7ba7b4599367c07f2f5d1e26151b68a71a1336b2, and it still happens as of 92f9580a4c369b4b51a7b6a5e77da43720134c9f

**Comment by Sciencentistguy** [comment]
Interestingly, it is fine on https://github.com/NixOS/nixpkgs/commit/a2d2f70b82ada0eadbcb1df2bca32d841a3c1bf1, but broken on https://github.com/NixOS/nixpkgs/commit/f289c49211399f2b050fd09a2674b3ca5388c753

**Comment by viraptor** [comment]
I see various reports of this happening randomly to people in 10.15.4 and a few mentions of other versions with completely random apps. This may not be a nix issue specifically, but rather some mac weirdness. Does that happen on any other apps, or just git?

**Comment by Sciencentistguy** [comment]
@viraptor I've only noticed it with git, but that doesn't necessarily rule out it happening elsewhere.

**Comment by kamalmarhubi** [comment]
I've been seeing this for a while. Eg, current `nixpkgs-unstable` (7cc30fd5372ddafb3373c318507d9932bd74aafe):

```
$ nix --extra-experimental-features 'nix-command flakes' \
    run github:NixOS/nixpkgs/nixpkgs-unstable#git
Killed: 9
```
Metadata:
```
$ nix --extra-experimental-features 'nix-command flakes' \
    flake metadata github:NixOS/nixpkgs/nixpkgs-unstable
Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstable
Locked URL:    github:NixOS/nixpkgs/7cc30fd5372ddafb3373c318507d9932bd74aafe
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/vv31n6dpig07j7jj4xbdllppklgp81jm-source
Revision:      7cc30fd5372ddafb3373c318507d9932bd74aafe
Last modified: 2023-06-17 01:20:35
```

According to `codesign`, the git binary is not signed:
```
$ codesign --verify --verbose \
    "$(nix --extra-experimental-features 'nix-command flakes' \
        path-info github:NixOS/nixpkgs/nixpkgs-unstable#git)/bin/git"
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: code object is not signed at all
In architecture: arm64
```

In case relevant,
```
$ uname -a
Darwin kamal-FL932PQ21V 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:43 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8112 arm64
```

**Comment by mikroskeem** [comment]
Cannot reproduce on my end - git command runs fine.Metadata (same, except last modified):Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstableLocked URL:    github:NixOS/nixpkgs/7cc30fd5372ddafb3373c318507d9932bd74aafeDescription:   A collection of packages for the Nix package managerPath:          /nix/store/vv31n6dpig07j7jj4xbdllppklgp81jm-sourceRevision:      7cc30fd5372ddafb3373c318507d9932bd74aafeLast modified: 2023-06-17 08:20:35Code signature:/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: valid on disk/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: satisfies its Designated Requirementuname -a:Darwin phoebus 22.6.0 Darwin Kernel Version 22.6.0: Wed Jun  7 17:30:08 PDT 2023; root:xnu-8796.140.23.0.2~38/RELEASE_ARM64_T8103 arm64 arm DarwinOn 17. Jun 2023, at 21:26, Kamal Marhubi ***@***.***> wrote:﻿
I've been seeing this for a while. Eg, current nixpkgs-unstable (7cc30fd):
$ nix --extra-experimental-features 'nix-command flakes' \
    run github:NixOS/nixpkgs/nixpkgs-unstable#git
Killed: 9

Metadata:
$ nix --extra-experimental-features 'nix-command flakes' \
    flake metadata github:NixOS/nixpkgs/nixpkgs-unstable
Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstable
Locked URL:    github:NixOS/nixpkgs/7cc30fd5372ddafb3373c318507d9932bd74aafe
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/vv31n6dpig07j7jj4xbdllppklgp81jm-source
Revision:      7cc30fd5372ddafb3373c318507d9932bd74aafe
Last modified: 2023-06-17 01:20:35

According to codesign, the git binary is not signed:
$ codesign --verify --verbose \
    "$(nix --extra-experimental-features 'nix-command flakes' \
        path-info github:NixOS/nixpkgs/nixpkgs-unstable#git)/bin/git"
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: code object is not signed at all
In architecture: arm64

In case relevant,
$ uname -a
Darwin kamal-FL932PQ21V 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:43 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8112 arm64

**Comment by mikroskeem** [comment]
Cannot reproduce on my end - git command runs fine.

Metadata (same, except last modified):

```
❯ nix --extra-experimental-features 'nix-command flakes' \
    flake metadata github:NixOS/nixpkgs/nixpkgs-unstable
Resolved URL:  github:NixOS/nixpkgs/nixpkgs-unstable
Locked URL:    github:NixOS/nixpkgs/7cc30fd5372ddafb3373c318507d9932bd74aafe
Description:   A collection of packages for the Nix package manager
Path:          /nix/store/vv31n6dpig07j7jj4xbdllppklgp81jm-source
Revision:      7cc30fd5372ddafb3373c318507d9932bd74aafe
Last modified: 2023-06-17 08:20:35
```

Code signature:

```
❯ codesign --verify --verbose \
    "$(nix --extra-experimental-features 'nix-command flakes' \
        path-info github:NixOS/nixpkgs/nixpkgs-unstable#git)/bin/git"
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: valid on disk
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: satisfies its Designated Requirement
```

System info:

```
❯ uname -a
Darwin phoebus 22.6.0 Darwin Kernel Version 22.6.0: Wed Jun  7 17:30:08 PDT 2023; root:xnu-8796.140.23.0.2~38/RELEASE_ARM64_T8103 arm64 arm Darwin
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.5
BuildVersion:		22G5048d
```

nix-info:
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(mark): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/22m41xwqmzigqcspaf8bwjwljg3vpvpw-source`

**Comment by Sciencentistguy** [comment]
I have not seen this issue again since i first reported it - at some point I forgot that I was running a pinned rev, and updated with no problems. I think @viraptor is right, in that it is somewhat random and it is mac weirdness.

@kamalmarhubi if you force nix to build from source (`nix-build '<nixpkgs>' -A git --check`) does the resulting binary work?

**Comment by mikroskeem** [comment]
After forcing a rebuild this time:

```
❯ /nix/store/viy8kdwngv0wa348mj9m44x683yj5dac-git-2.40.1/bin/git --version
zsh: killed     /nix/store/viy8kdwngv0wa348mj9m44x683yj5dac-git-2.40.1/bin/git --version
❯ codesign --verify --verbose /nix/store/viy8kdwngv0wa348mj9m44x683yj5dac-git-2.40.1/bin/git
/nix/store/viy8kdwngv0wa348mj9m44x683yj5dac-git-2.40.1/bin/git: invalid signature (code or signature have been modified)
In architecture: arm64
```

**Comment by kamalmarhubi** [comment]
@Sciencentistguy that command reports:
```
$ nix-build '<nixpkgs>' -A git --check
[... lots of build output ...]
error: derivation '/nix/store/cqafml8i3c03dhg58n576bq253n7vcyw-git-2.38.1.drv' may not be deterministic: output '/nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1' differs
```

The binary at that store path works and codesign is happy with it:
```
$ /nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1/bin/git --version
git version 2.38.1
$ codesign --verify --verbose /nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1/bin/git
```

I don't know if the binary at that path is the downloaded artifact or the locally built one, so I reran the command with `--keep-failed`:
```
$ nix-build '<nixpkgs>' -A git --check --keep-failed
[... lots of build output ...]
note: keeping build directory '/private/tmp/nix-build-git-2.38.1.drv-2'
error: derivation '/nix/store/cqafml8i3c03dhg58n576bq253n7vcyw-git-2.38.1.drv' may not be deterministic: output '/nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1' differs from '/nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1.check'
```

Checking those two store paths' git binaries:
```
$ /nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1/bin/git --version
git version 2.38.1
$ codesign --verify --verbose /nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1/bin/git
/nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1/bin/git: valid on disk
/nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1/bin/git: satisfies its Designated Requirement
```
and the `.check` version:
```
$ /nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1.check/bin/git --version
Killed: 9
$ codesign --verify --verbose /nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1.check/bin/git
/nix/store/2dmvb1q91cj3h528ma9mphm99bgmkyyh-git-2.38.1.check/bin/git: invalid signature (code or signature have been modified)
In architecture: arm64
```

I think this means the downloaded artifact is fine but the locally built one isn't?

Aside: I'm not where my `<nixpkgs>` is set since I only use flakes on this machine; `nix-channel --list` has no output. But apparently this is with a5f661b80e4, which is from late December:
```
$ nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
"23.05pre432461.a5f661b80e4"
```

I ran what I think is the flake equivalent command at the current `nixpkgs-unstable` (2c09e8eb8), which also complains of non-determinism:
```
$ nix --extra-experimental-features 'nix-command flakes' \
    build --cores 8 --rebuild --keep-failed github:NixOS/nixpkgs/nixpkgs-unstable#git
note: keeping build directory '/private/tmp/nix-build-git-2.40.1.drv-3'
error: derivation '/nix/store/l4gkv9n392bjka197ahp264khnc51z1y-git-2.40.1.drv' may not be deterministic: output '/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1' differs from '/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check'
```

But in this case, both outputs' git binaries are SIGKILLed:
```
$ /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git
Killed: 9
$ /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git
Killed: 9
```

Looking slightly closer, the (presumably?) downloaded one is unsigned (different from above), and the locally built one has an invalid signature (similar to above):
```
$ codesign --verify --verbose /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1/bin/git: code object is not signed at all
In architecture: arm64
$ codesign --verify --verbose /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git: invalid signature (code or signature have been modified)
In architecture: arm64
```

Not sure what to make of this? At some point artifacts in cache.nixos.org stopped being signed? Why are my local builds producing binaries with invalid signatures?

I don't know anything about how substitution works, so I can't figure out how to fetch the built artifact for an arbitrary `nixpkgs-unstable` and investigate more. Ideally I'd like to be able to reproduce the non-determinism and then bisect across nixpkgs-unstable for when it was introduced or something like that?

**Comment by Sciencentistguy** [comment]
A bisect may be useful, but I'm not certain it will tell us much - last time, it just came up with a rev that didn't touch `git`'s closure at all.

Testing on my machine (2021 M1 Max MBP) with rev https://github.com/NixOS/nixpkgs/commit/2c09e8eb8717e240ef9c5727c1cc9186db9fb309 gives the following:

The downloaded (substituted) binary works, and is signed:
```
nix build "github:nixos/nixpkgs/2c09e8e"#git && ./result/bin/git --version && codesign --verify --verbose ./result/bin/git
# <nix output cut...>
git version 2.40.1
./result/bin/git: valid on disk
./result/bin/git: satisfies its Designated Requirement
```

The locally built binary does not match - nix complains about determinism
```
nix build "github:nixos/nixpkgs/2c09e8e"#git --rebuild --keep-failed
note: keeping build directory '/private/tmp/nix-build-git-2.40.1.drv-1'
error: derivation '/nix/store/l4gkv9n392bjka197ahp264khnc51z1y-git-2.40.1.drv' may not be deterministic: output '/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1' differs from '/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check'
```
and is killed my macos and fails codesign:
```
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git --version
zsh: killed     /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git --versio

codesign --verify /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git --verbose
/nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/bin/git: invalid signature (code or signature have been modified)
In architecture: arm64
```

Interestingly, I can't even strip the signature
```
cp /nix/store/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check /tmp
# output cut
cd /tmp/r1f29k5x419hwmpjhysaqbv5zgjd9lmz-git-2.40.1.check/
codesign --remove-signature ./bin/git
./bin/git: internal error in Code Signing subsystem
```

**Comment by emilazy** [comment]
See also: https://github.com/LnL7/nix-darwin/issues/693 (in particular https://github.com/LnL7/nix-darwin/issues/693#issuecomment-1652936332, https://github.com/LnL7/nix-darwin/issues/693#issuecomment-1656561991). This may be related to store optimization?

**Comment by emilazy** [comment]
I don't know if this is a bug with the Nixpkgs Git package. It seems to involve a derivation getting somehow replaced with one that is almost identical but subtly broken, perhaps a Nix bug involving substituters or store optimization (which is quite broken on macOS in general). I don't know where the broken "shadow derivation" is coming from, especially since we don't know its derivation hash, but at least in the case of the issue I linked it was fixed by repairing the store path.

**Comment by Sciencentistguy** [comment]
This is cropping up again for me, btw. The workaround of forcing it to rebuild still works.

@emilazy i don't seem to be able to run `nix store optimise <path>`? It is failing with
```
error: operation 'repairPath' is not supported by store 'daemon'
```

**Comment by reckenrode** [comment]
Sorry about the commit message spam. I believe this will be fixed by the ld64 upgrade in https://github.com/NixOS/nixpkgs/pull/307880. As part of the upgrade, the post-link signing hook is being dropped. ld64 will automatically handle code-signing, and cctools will automatically preserve linker-generated signatures (which ld64 creates).

**Comment by winterqt** [comment]
It overrides the store path in the binaries, which breaks the code signatures of (at least) libraries (as they have their path embedded within). I forget offhand why this also applies to executables.

**Comment by futile** [comment]
+1 for not being able to use `git` anymore on aarch64-darwin (M3).

> AFAIU, this is some fun nondeterminism somewhere (cc [@reckenrode](https://github.com/reckenrode)).
> 
> `--check` producing invalid code signatures is expected, but if you do something along the lines of `nix-store --delete /nix/store/xxx-git` and then rebuild it with substituters disabled, you should get a working Git binary without having to make some random change to the derivation.

I can't run that `--delete`, because the path is still 'live'. I'll switch back to my previous home-manager generation/configuration probably.

This might qualify for some kind of urgent fix/escalation if we have something like that (I know it's mostly volunteers etc.)?

**Comment by philiptaron** [comment]
CC @me-and as a new `git` co-maintainer. What a fascinating thread.

**Comment by futile** [comment]
@chrisportela 

**Workaround** that worked for me: The pkg that's broken seems to be `pkgs.gitFull`, switching to just `pkgs.git` gave me a working `git`-binary again (so you don't have to rollback).

**Comment by judofyr** [comment]
Today I updated to the latest unstable channel and `gitFull` appears to be working fine.

**Comment by winterqt** [comment]
@tomberek Can you try deleting the store path and building the same derivation locally without our substituter?

**Comment by felixscheinost** [comment]
I am experiencing the same issue with fish.

I think it is https://github.com/NixOS/nixpkgs/issues/507531

**Comment by amarshall** [comment]
Happening with ffmpeg now as well: https://github.com/NixOS/nixpkgs/issues/511265. Probably the title of this issue should be changed to be more generic.

**Comment by futile** [comment]
This PR is trying to fix the issue, but confirmation is currently hard because creating a test setup that we're positive reproduces _this exact issue_ is hard: https://github.com/NixOS/nix/pull/15638

It contains detailed write-ups in the comments about what's happening and all the subtleties involved, for whoever is interested :)

**Comment by afh** [comment]
Seems this now also affects musikcube #517508

**Comment by lunrox-luna** [comment]
Opencode seems also affected by this - have not created an issue yet but I can fix it by running codesign -f -s - [binary] in postBuild, which might be an avenue for some people to fix this while waiting for a fix.

Snippet looks like this - this was AI-generated as a note so please keep that in mind, it wont be perfect:

```
nativeBuildInputs =
            (previousAttrs.nativeBuildInputs or [])
            ++ prev.lib.optionals prev.stdenv.hostPlatform.isDarwin [
              prev.darwin.cctools
              prev.darwin.sigtool
            ];

        postBuild = (previousAttrs.postBuild or "") + prev.lib.optionalString
            prev.stdenv.hostPlatform.isDarwin
            ''
              echo "Re-signing opencode binary..."

              codesign -f -s - \
                dist/opencode-darwin-arm64/bin/opencode
            '';
      });
```

**Comment by amarshall** [comment]
Such a complicated change is not necessary. *Any* change to the derivation (e.g. a simply `env.WHATEVER = ""`) that causes a rebuild under a different path will workaround the issue.
