### ISSUE TITLE
gamescope: not sure how to set capabilities since it uses bubblewrap

### ISSUE THREAD

**Issue by colemickens** [NixOS/nixpkgs#208936]
### Describe the bug

`gamescope` encourages people to set capabilities on the binary to enable it to change its nice level.

However, this doesn't work with the nix store. I've tried a security wrapper, but it doesn't seem to work right with bubblewrap.

Ideally for gaming users, we could solve this in a module or something so that gamescope can work as good as possible.

**Comment by surfaceflinger** [comment]
+, gamescope is literally unusable for gaming without proper nice.

**Comment by bayazidbh** [comment]
Is this why I'm getting this error:

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'AMD Radeon Graphics': queue family 1
vulkan: physical device does not support DRM format modifiers
vulkan: vkAllocateDescriptorSets failed
Failed to initialize Vulkan
```

**Comment by altwazar** [comment]
> However, this doesn't work with the nix store. I've tried a security wrapper, but it doesn't seem to work right with bubblewrap.

I get errors only with steam, steam-run, lutris, flatpak, but not with general applications like gimp. I think bubblewrap don't go well with another wrappers. This is unfortunate, because at the same time you can't run gamescope within steam on nixos .
Error:
```
bwrap: Unexpected capabilities but not setuid, old file caps config?
```

**Comment by colemickens** [comment]
I think @nrdxp fixed this in https://github.com/NixOS/nixpkgs/pull/187507/files (ctrl+f `capsysnice`)

**Comment by nrdxp** [comment]
As @colemickens pointed out, there is already a module option to set the proper capability on the gamescope binary correctly, at least on NixOS. Not sure what can be done on other distros.

**Comment by colemickens** [comment]
Thanks for confirming (and implementing) as the opener, I'm going to go ahead and close this.

**Comment by altwazar** [comment]
@nrdxp there is option `programs.gamescope.capSysNice = true;`, but bwrap stop execution in some cases.
For example on nixos unstable:
```
❯ gamescope steam
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: selecting physical device 'AMD Radeon RX 550 / 550 Series (RADV POLARIS12)': queue family 1
vulkan: physical device does not support DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB48 (0x38344241)
vulkan:   XB48 (0x38344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:63] Failed to bind socket @/tmp/.X11-unix/X0: Address already in use
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
wlserver: [types/wlr_compositor.c:673] New wlr_surface 0x15c35e0 (res 0x179e350)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 76
pipewire: renegotiating stream params (size: 1280x720)
bwrap: Unexpected capabilities but not setuid, old file caps config?
```
Same with lutris, steam-run.

**Comment by jonseppanen** [comment]
In current unstable, setting capsysnice to true prevents gamescope running from steam entirely. This issue needs re-opening.

**Comment by urioTV** [comment]
Yep It needs reopening. I noticed some problems with gamescope that renicing could resolve so that should be mandatory.

**Comment by urioTV** [comment]
I'll add my logs for context.

`pressure-vessel-wrap[127378]: W: "/run/current-system/sw/bin/getent" is unlikely to appear in "/run/host"
pressure-vessel-wrap[127378]: W: Found more than one possible libdrm data directory from provider
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
ATTENTION: default value of option vk_x11_override_min_image_count overridden by environment.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
chdir "/home/urio/.local/share/Steam/steamapps/common/Cyberpunk 2077"
ERROR: ld.so: object '/home/urio/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
failed to inherit capabilities: Operation not permittedUploaded AppInterfaceStats to Steam
Adding process 127844 for gameID 1091500
Removing process 127844 for gameID 1091500`

I think that line is a problem `failed to inherit capabilities: Operation not permittedUploaded AppInterfaceStats to Steam` I'm not a specialist about this topic so if someone wants me to provide more data I will.

**Comment by JaysFreaky** [comment]
I can confirm Steam games are still starting and immediately stopping when programs.gamescope.capSysNice is enabled. Disabling it allows games to load correctly, but others have mentioned, after about 30 minutes, the performance degrades. This issue needs to be re-opened.

**Comment by feijoas** [comment]
I think the new issue is here: https://github.com/NixOS/nixpkgs/issues/351516
