### ISSUE TITLE
yubioath-flutter cannot capture QR codes

### ISSUE THREAD

**Issue by aidalgol** [NixOS/nixpkgs#208953]
### Describe the bug
The yubioath-flutter application fails to read QR codes on the scree.

### Steps To Reproduce
1. Open yubiath-flutter
2. Click the YubiKey icon in the top-right corner of the window.
3. Select "Add account
4. Click "Scan QR Code"
5. You will get an error popup at the bottom of the window

### Expected behavior
The account fields to be populated from the information in the QR code.

### Screenshots
![image](https://user-images.githubusercontent.com/2313201/210458805-5cbb438d-5161-4546-b9d6-73ddda1af44c.png)

### Additional context
No relevant errors on stdout/stderr.

### Notify maintainers
@lukegb 

### Metadata
```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.12, NixOS, 22.11 (Raccoon), 22.11.20221210.9c5e57f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(aidan): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`
```

**Comment by Kranzes** [comment]
I encountered this as well but haven't had the time to dig deeper into this. If I reach a conclusion I will comment it here.

**Comment by Kranzes** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/209038
