### ISSUE TITLE
allow using mkDefault/mkForce with PHP buildEnv

### ISSUE THREAD

**Issue by shyim** [NixOS/nixpkgs#209058]
### Describe the bug

I have assigned a custom build PHP to one option in another file I want to overwrite it, but that does not work

```
Definition values:
       - In `/Users/shyim/Code/platform/devenv.local.nix': <derivation php-with-extensions-8.1.13>
       - In `/Users/shyim/Code/platform/devenv.nix': <derivation php-with-extensions-8.1.13>
```

When I now add to the relevant one a lib.mkForce or the other one a lib.mkDefault:

```
           5|
            6|     languages.php.package = lib.mkForce pkgs.php.buildEnv {
             |                             ^
            7|         extensions = { all, enabled }: with all; enabled ++ [ amqp redis blackfire grpc xdebug ];

       error: attempt to call something which is not a function but a set

```

### Expected behavior
mkForce/mkLib does work with packages build with `buildEnv`

### Notify maintainers
@NixOS/php 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - channels(shyim): `"darwin"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by aanderse** [comment]
Did you try this?:
```
languages.php.package = lib.mkForce (pkgs.php.buildEnv { ... });
```

Also, should this have been reported on the [devenv](https://github.com/cachix/devenv) issue tracker instead?

**Comment by shyim** [comment]
It's working. I feel now stupid 😆 

Thanks! :) 

I thought it's more generic as it is 😅

**Comment by aanderse** [comment]
All good. Glad you're up and running.
