### ISSUE TITLE
nix.useSandbox needs documentation

### ISSUE THREAD

**Issue by lverns** [NixOS/nixpkgs#20900]
## Issue description

Searching through the Nixpkgs manual, the Nix manual, and the NixOS manual, no mention of `nix.useSandbox` occurs.

Following the mailing list/IRC, it is obvious that people use it. Also, when one creates a pull request to the repo, the default text asks you to specify whether or not you use it.

## Solution

Add a short description of the `nix.useSandbox` item to the documentation.

**Comment by joachifm** [comment]
It is documented in `man 5 configuration.nix` along with all the other options.

**Comment by vcunat** [comment]
http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox on the web.

**Comment by vcunat** [comment]
And in nix manual it's called `build-use-sandbox` and the related options are around it...

**Comment by vcunat** [comment]
It might be confusing that the naming used to be *chroot* instead of *sandbox*.

**Comment by FRidh** [comment]
> http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox on the web.

If you go to the typical link for the Nixpkgs manual, https://nixos.org/nixos/manual/, you won't find anything. It's the first time I see the link you showed (although I am familiar with http://nixos.org/nixos/options.html). 

> Also, when one creates a pull request to the repo, the default text asks you to specify whether or not you use it.

A link is included to http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox. 

While it may be considered an implementation detail, I think it would be good if the NixOS options would mention the corresponding Nix option (so `nix.useSandbox` would mention `build-use-sandbox`).

**Comment by vcunat** [comment]
The option list *is* linked from the manual. It's not all in a single HTML, as the option list is really large nowadays.
