### ISSUE TITLE
hid_apple kernel module parameters not working

### ISSUE THREAD

**Issue by xwvvvvwx** [NixOS/nixpkgs#20906]
## Issue description

I have nixos 16.09 installed on my macbook pro retina, and I would like to fix a few keyboard mapping issues by setting the `fnmode` and `iso_layout` parameters for the `hid_apple` kernel module (as described [here](https://wiki.archlinux.org/index.php/Apple_Keyboard)).

When I set the parameters in my configuration.nix and rebuild and reboot, the mappings have not changed, and the value of the parameters does not appear to have changed either. 

The values are written to `/etc/modprobe.d/nixos.conf` but are not propagated to `/sys/module/hid_apple/parameters`.

Full output of all the tools that I could think to run in [this gist](https://gist.github.com/xwvvvvwx/e2761e2d9408d19dd80ee26973fcbd04)

### Steps to reproduce

1. Add the following lines to `/etc/nixos/configuration.nix`:

```
  boot.extraModprobeConfig = ''
    options hid_apple fnmode=2
    options hid_apple iso_layout=0
  '';
```

2. `sudo nixos-rebuild switch && reboot`

### Expected

2. module parameters at `/sys/module/hid_apple/parameters/` have been updated to the values set in `configuration.nix`

### Actual

2. module parameters are not the same as those set in `configuration.nix`. `fnmode` and `iso_layout` are set to 1.

## Technical details

* System: NixOS: `16.09`
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1198.6a9f087

**Comment by peterhoeg** [comment]
Just to check the obvious, you have either rebooted or unloaded/loaded the module after making the change?

**Comment by xwvvvvwx** [comment]
Hi :relaxed: 

I have rebooted multiple times, and the issue still persists. If I manually unload the module (`modprobe -r hid_apple`) the keyboard stops working so I can't load it again without a reboot.

**Comment by xwvvvvwx** [comment]
Here is the output of `journalctl -b`:

https://gist.github.com/xwvvvvwx/bfd8323a063257059a95245ee04ed110

**Comment by peterhoeg** [comment]
I'll take a look tonight - I have an apple keyboard at home.

**Comment by xwvvvvwx** [comment]
Figured out how to manually unload / load the module (`sudo modprobe -r hid_apple && sudo modprobe hid_apple`).

After running this command the keyboard mappings are correct, and the module parameters are applied (correct values shown in `/sys/module/hid_apple/parameters`)

**Comment by vith** [comment]
I have the same problem here, but with a Matias Quiet Pro *for PC* keyboard that needs `fnmode=2`.

Setting the parameter manually every boot with `echo 2 | sudo tee /sys/module/hid_apple/parameters/fnmode` works but
```
  boot.extraModprobeConfig = ''
    options hid_apple fnmode=2
  '';
```
does not.

**Comment by jeremiehuchet** [comment]
As a workaround I did like https://gist.github.com/dmjio/3679898135b25fa49723 and passed module options using the bootloader kernel params
```
boot.kernelParams = [
  "hid_apple.fnmode=2"
];
```

**Comment by peterhoeg** [comment]
Ahh, it's probably that the driver is being loaded as part of initrd and therefore the module options are not yet available.

**Comment by arianvp** [comment]
Could we document this 'workaround' to close this issue? Or does it require changes to modules to be a default?

**Comment by Fuzen-py** [comment]
I have been using this without issue for a little while now.
```
  boot.extraModprobeConfig = ''
      options hid_apple fnmode=2
  '';
  boot.kernelModules = [ "hid-apple"  ];
```

**Comment by peterhoeg** [comment]
There isn't anything directly actionable here. Closing.

**Comment by AdsonCicilioti** [comment]
> I have been using this without issue for a little while now.
> 
> ```
>   boot.extraModprobeConfig = ''
>       options hid_apple fnmode=2
>   '';
>   boot.kernelModules = [ "hid-apple"  ];
> ```

Thanks!!
