### ISSUE TITLE
services.ananicy: add rulesProvider option

### ISSUE THREAD

**Issue by delet-this** [NixOS/nixpkgs#209177]
### Motivation
I wanted to configure `services.ananicy` to use [CachyOS' ananicy rules](https://github.com/CachyOS/ananicy-rules), however there wasn't an ergonomic way to do that with the existing options. Even if I came up with a way to plug all the rules to extraRules, I'd still be missing custom types and cgroups. I ended up modifying the option definitions such that I could source /etc/ananicy.d/ from a different package. I thought upstream would benefit from something like this.

### Proposal
Add an option `services.ananicy.rulesProvider` (or rules, rulesPackage, rulesetProvider, rulesetPackage... Looking for feedback on naming.) of type package, which accepts a package that provides /etc/ananicy.d/. Default value would be `pkgs.ananicy`. This option would be used for configuring ananicy with alternative rulesets.

`services.ananicy` [is currently hardcoded](https://github.com/NixOS/nixpkgs/blob/e9ade2c8240e00a4784fac282a502efff2786bdc/nixos/modules/services/misc/ananicy.nix#L62) to use the ruleset from `pkgs.ananicy`. We would change this to `cfg.rulesProvider` instead. We would package alternative rulesets like [CachyOS'](https://github.com/CachyOS/ananicy-rules), [minq-ananicy's](https://github.com/kuche1/minq-ananicy) (well this is actually a whole ananicy fork) and maybe in the future [ananicy-cpp's community rules](https://gitlab.com/ananicy-cpp/ananicy-cpp/-/issues/6#note_587066634) to go with this option.

---
Is this something that would fit nixpkgs? Would something like an overridable package option be a better fit? Is packaging configs the wrong approach here? I suppose we should also implement `extraTypes` and `extraCgroups`, but even then I'd still like a way to easily use rulesets from the mentioned git repos.

In case this seems feasible, I could take a shot at creating a PR.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/242309 for extraX

**Comment by ninioArtillero** [comment]
so it's merged I see, what options are available now for rulesProvider?

**Comment by Artturin** [comment]
> so it's merged I see, what options are available now for rulesProvider?

`ananicy-rules-cachyos`
