### ISSUE TITLE
kodi: kodi-send doesn't find python module 'kodi'

### ISSUE THREAD

**Issue by Mynacol** [NixOS/nixpkgs#209190]
### Describe the bug
For a long time I have a small shell script wrapping around kodi-send to play different media. I am now in the process of moving kodi to NixOS, but kodi-send seems to be borked.
Everytime `kodi-send` is executed with(out) any arguments, it fails immediately.

### Steps To Reproduce
1. `nix-shell -p kodi-gbm --run 'kodi-send "--action=PlayMedia(https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4)"'`

```console
[root@rpi:~]# nix-shell -p kodi-gbm --run 'kodi-send "--action=PlayMedia(https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4)"'
Traceback (most recent call last):
  File "/nix/store/ys5agqcwykb3823rbgpj08g5x2p10hyy-kodi-19.5/bin/.kodi-send-wrapped", line 27, in <module>
    from kodi.xbmcclient import *
ModuleNotFoundError: No module named 'kodi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/ys5agqcwykb3823rbgpj08g5x2p10hyy-kodi-19.5/bin/.kodi-send-wrapped", line 30, in <module>
    from xbmcclient import *
ModuleNotFoundError: No module named 'xbmcclient'
```

### Expected behavior
Big Buck Bunny plays in Kodi (and kodi-send doesn't throw an error).

### Additional context
I found a workaround by setting `PYTHONPATH=${kodi-gbm}/lib/python3.10/site-packages` in my script.
For ad-hoc testing, this is on my machine:
`nix-shell -p kodi-gbm --run 'PYTHONPATH=/nix/store/ys5agqcwykb3823rbgpj08g5x2p10hyy-kodi-19.5/lib/python3.10/site-packages kodi-send "--action=PlayMedia(https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4)"'`
AFAIK PYTHONPATH _should not_ be used, but kodi [uses it already](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/kodi/wrapper.nix#L32).

FYI: Kodi had to be recompiled, as libcec was modified by me.
### Notify maintainers

@peterhoeg @aanderse

### Metadata

```console
[root@rpi:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.74, NixOS, 22.11 (Raccoon), 22.11.1347.0bf3109eeb6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

----
(first nixpkgs issue, bear with me)

**Comment by aanderse** [comment]
Thanks for reporting. Sorry for the delay on this. Can you please give https://github.com/NixOS/nixpkgs/pull/210802 a quick test to confirm everything is working as expected? I was able to run the program with `--help` and it looked fine, and the source code is pretty simple so I feel like we're good here... but I would appreciate you actually running and confirming your case is fixed.
