### ISSUE TITLE
abuse update available

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#209240]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: [abuse](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/abuse/default.nix)

current version: 0.8
desired version: [0.9.1](https://github.com/Xenoveritas/abuse/releases/tag/v0.9.1)

###### Notify maintainers

maintainers: @iblech 

###### Note for maintainers

Please tag this issue in your PR.

###### Other notes

This update is provided by a fork of the original Abuse SDL port from http://abuse.zoy.org/
More about that project -> https://github.com/Xenoveritas/abuse#abuse-readme

**Comment by applePrincess** [comment]
:+1: [Information in repology](https://repology.org/project/abuse) for abuse is using the fork version. And according to that, Fedora is packaging the fork.

**Comment by wegank** [comment]
Closed in #288145.
