### ISSUE TITLE
python3.10 cryptography  do not know how to unpack source archive

### ISSUE THREAD

**Issue by Ravi-9654** [NixOS/nixpkgs#209291]
## Issue description
python3.10 cryptography  do not know how to unpack source archive

### Steps to reproduce

add azure-identity package in pyproject.toml and run nix build command

# nix build -L .#docker 2>&1 | ts -s
00:00:03 these 13 derivations will be built:
00:00:03   /nix/store/fcsfi8zyb990hcjkd3ahi6cjb7qddh32-python3.10-cryptography-39.0.0.drv
00:00:03   /nix/store/pfi7nqc1va48h57k2cg7d5gyk4py6ks5-python3.10-pyjwt-2.6.0.drv
00:00:03   /nix/store/m5kdlzmd6zq10an0bc891ymczqjj3d3g-python3.10-msal-1.20.0.drv
00:00:03   /nix/store/czqcc81dh5gjffn7x9xkxrwbvqznd7gd-python3.10-msal-extensions-1.0.0.drv
00:00:03   /nix/store/abcgxl8s9mcjd81jyhmf0ws5rfwwidld-python3.10-azure-identity-1.12.0.drv
00:00:03   /nix/store/s4912j679a0v9qzphx6nlksr7ri9ng24-python3.10-application-api-1.1.0.drv
00:00:03   /nix/store/bycx2da9xvvhgjx9fxbkqrp0cqzvn59z-application-api-base.json.drv
00:00:03   /nix/store/yq8l1iyxp8d50dgd1xd82k2h0gnzr8cz-application-api-customisation-layer.drv
00:00:03   /nix/store/wqq87px91s4jylcm9hg94dfswjj3v981-closure.drv
00:00:03   /nix/store/v60zsa6yxxsjm4s2yvvc69iz8ycjaxdp-closure-paths.drv
00:00:03   /nix/store/wqba7jwhpzj5fhfpcs4p70fl0vz7p4d3-application-api-conf.json.drv
00:00:03   /nix/store/fbnjfa2zssadmqq6w1xqni7w5lsi2zw3-stream-application-api.drv
00:00:03   /nix/store/hdgzpvyks7g46rfr4j0sl6kqj6zfsl63-application-api.tar.gz.drv
00:00:03 building '/nix/store/fcsfi8zyb990hcjkd3ahi6cjb7qddh32-python3.10-cryptography-39.0.0.drv'...
00:00:03 python3.10-cryptography> Sourcing python-remove-tests-dir-hook
00:00:03 python3.10-cryptography> Sourcing python-catch-conflicts-hook.sh
00:00:03 python3.10-cryptography> Sourcing python-remove-bin-bytecode-hook.sh
00:00:03 python3.10-cryptography> Sourcing pip-build-hook
00:00:03 python3.10-cryptography> Using pipBuildPhase
00:00:03 python3.10-cryptography> Using pipShellHook
00:00:03 python3.10-cryptography> Sourcing pip-install-hook
00:00:03 python3.10-cryptography> Using pipInstallPhase
00:00:03 python3.10-cryptography> Sourcing python-imports-check-hook.sh
00:00:03 python3.10-cryptography> Using pythonImportsCheckPhase
00:00:03 python3.10-cryptography> Sourcing python-namespaces-hook
00:00:03 python3.10-cryptography> unpacking sources
00:00:03 python3.10-cryptography> unpacking source archive /nix/store/ljbbynl46mj6m8541w5qki49pghv19xy-cryptography-39.0.0.tar.gz
00:00:03 python3.10-cryptography> source root is cryptography-39.0.0
00:00:03 python3.10-cryptography> Executing cargoSetupPostUnpackHook
00:00:03 python3.10-cryptography> unpacking source archive
00:00:03 python3.10-cryptography> do not know how to unpack source archive
00:00:03 error: builder for '/nix/store/fcsfi8zyb990hcjkd3ahi6cjb7qddh32-python3.10-cryptography-39.0.0.drv' failed with exit code 1
00:00:03 error: 1 dependencies of derivation '/nix/store/abcgxl8s9mcjd81jyhmf0ws5rfwwidld-python3.10-azure-identity-1.12.0.drv' failed to build
00:00:03 error: 1 dependencies of derivation '/nix/store/s4912j679a0v9qzphx6nlksr7ri9ng24-python3.10-application-api-1.1.0.drv' failed to build
00:00:03 error: 1 dependencies of derivation '/nix/store/bycx2da9xvvhgjx9fxbkqrp0cqzvn59z-application-api-base.json.drv' failed to build
00:00:03 error: 1 dependencies of derivation '/nix/store/yq8l1iyxp8d50dgd1xd82k2h0gnzr8cz-application-api-customisation-layer.drv' failed to build
00:00:03 error: 1 dependencies of derivation '/nix/store/wqba7jwhpzj5fhfpcs4p70fl0vz7p4d3-application-api-conf.json.drv' failed to build
00:00:03 error: 1 dependencies of derivation '/nix/store/fbnjfa2zssadmqq6w1xqni7w5lsi2zw3-stream-application-api.drv' failed to build
00:00:03 error: 1 dependencies of derivation '/nix/store/hdgzpvyks7g46rfr4j0sl6kqj6zfsl63-application-api.tar.gz.drv' failed to build
``

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
nix-shell -p nix-info --run "nix-info -m"
these 40 paths will be fetched (66.90 MiB download, 306.88 MiB unpacked):
  /nix/store/0gi11bgivf54kbxmns7cw53jjv05n541-readline-8.1p2
  /nix/store/3nxvwpxmvv5sv2bb88plhs4ys1jl0bmm-attr-2.5.1
  /nix/store/49y3r0gr9m6k20d91kl6dgp4b9a6m72v-diffutils-3.8
  /nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16
  /nix/store/5dv5cq1lwvsijr9p16p2kp79g1dbajk3-gnused-4.8
  /nix/store/62fb427ncxaaksa2k59rhbilfg68v20x-binutils-wrapper-2.39
  /nix/store/6fid553s8qb5vgwq8namz4dcmjpklvr1-libidn2-2.3.2
  /nix/store/793iwfbjvg7wgpqq7r83a1qjl1yg02sf-patch-2.7.6
  /nix/store/7q3p2y40p0q8i63xprvfmc61avp5xqz4-pcre-8.45
  /nix/store/89zbjdkb48ma61k76l2mzn3s0ra0wn2c-gnutar-1.34
  /nix/store/a3mwv26f99ycsv9w6hrx0jjjjywvcb1n-xz-5.2.9-bin
  /nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224
  /nix/store/ba3sgrhx7ccp4nwq8lyj7l0mr53p0v1z-ed-1.18
  /nix/store/bcvccw6y9bfil6xrl5j7psza7hnd16ry-gnugrep-3.7
  /nix/store/camlh5laf1wsklghk0vcaw7gvx4rpzd1-file-5.43
  /nix/store/cp65c8nk29qq5cl1wyy5qyw103cwmax7-stdenv-linux
  /nix/store/crj2i8d82fff4hk94nlxmyzi1ir2z0cz-libunistring-1.0
  /nix/store/dnwi357xww3rxdvr79gbvvs8zqm1x47m-acl-2.3.1
  /nix/store/f7cyasjd42qgr2hsr4w28rs4q907fyi1-xz-5.2.9
  /nix/store/frh9l9nrdysasdi2gs7i241s241ngjw2-binutils-2.39
  /nix/store/g2nfbpind37b3v3y6zbszmcgfmrj5v7x-patchelf-0.15.0
  /nix/store/h8gvq6r4hgpa71h44dmg9qfx03mj81sv-coreutils-9.1
  /nix/store/i0x4pzj96qwvkrm94317l6jbi53a2rdj-gnumake-4.4
  /nix/store/ifs2ghiwngx45a0bkq2lymf4gh8zdr9i-ncurses-6.3-p20220507
  /nix/store/j4mx37iy9lkkvcg41c9347sn7zwvnnw4-gmp-with-cxx-stage4-6.2.1
  /nix/store/kxdyx0dqy8gpx8yp61wybn2dr1va0vn8-bzip2-1.0.8
  /nix/store/l1fp0hyca54xbb85vfhppd16bskzx8dg-gawk-5.1.1
  /nix/store/mb6pgv5w5ki64k5s2m83dqvg8i2b239n-linux-headers-6.0
  /nix/store/mmmjp0xcmr0dm307jv1l34hvi95z6d8s-glibc-2.35-224-dev
  /nix/store/qs8qb1swpivkfq7i9yd52n0mw6z4ij81-gzip-1.12
  /nix/store/s7ip867mrpnnjlppbnxlcsq10gv13x2x-glibc-2.35-224-bin
  /nix/store/sxdx80lmk4zkhb51f4x5dgqvxgmx55wl-gcc-11.3.0
  /nix/store/szznid54xdgn4idxym2dsg166swah5dc-nix-info
  /nix/store/wn31i3dzwahz6ccws8bs1nwyqrpgsvj7-gcc-wrapper-11.3.0
  /nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib
  /nix/store/wwkyfg8b34xy16zzc9p6rkh59p4q37qx-bzip2-1.0.8-bin
  /nix/store/x40p83k9mk03kklpfahqppp6kz85yx99-bash-interactive-5.1-p16
  /nix/store/ymn3x7lkd5q0ndb2mh4dqa7am4nrdap1-expand-response-params
  /nix/store/zaflwh2nwzj1f0wngd7hqm3nvlf3yhsx-zlib-1.2.13
  /nix/store/zml88vnkpm8if114qkbbqd1q7n3ypqqy-findutils-4.9.0
copying path '/nix/store/crj2i8d82fff4hk94nlxmyzi1ir2z0cz-libunistring-1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/mb6pgv5w5ki64k5s2m83dqvg8i2b239n-linux-headers-6.0' from 'https://cache.nixos.org'...
copying path '/nix/store/6fid553s8qb5vgwq8namz4dcmjpklvr1-libidn2-2.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/ayfr5l52xkqqjn3n4h9jfacgnchz1z7s-glibc-2.35-224' from 'https://cache.nixos.org'...
copying path '/nix/store/3nxvwpxmvv5sv2bb88plhs4ys1jl0bmm-attr-2.5.1' from 'https://cache.nixos.org'...
copying path '/nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16' from 'https://cache.nixos.org'...
copying path '/nix/store/dnwi357xww3rxdvr79gbvvs8zqm1x47m-acl-2.3.1' from 'https://cache.nixos.org'...
copying path '/nix/store/kxdyx0dqy8gpx8yp61wybn2dr1va0vn8-bzip2-1.0.8' from 'https://cache.nixos.org'...
copying path '/nix/store/ba3sgrhx7ccp4nwq8lyj7l0mr53p0v1z-ed-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/wwkyfg8b34xy16zzc9p6rkh59p4q37qx-bzip2-1.0.8-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/ymn3x7lkd5q0ndb2mh4dqa7am4nrdap1-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/l1fp0hyca54xbb85vfhppd16bskzx8dg-gawk-5.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/wprxx5zkkk13hpj6k1v6qadjylh3vq9m-gcc-11.3.0-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/s7ip867mrpnnjlppbnxlcsq10gv13x2x-glibc-2.35-224-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/j4mx37iy9lkkvcg41c9347sn7zwvnnw4-gmp-with-cxx-stage4-6.2.1' from 'https://cache.nixos.org'...
copying path '/nix/store/mmmjp0xcmr0dm307jv1l34hvi95z6d8s-glibc-2.35-224-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/h8gvq6r4hgpa71h44dmg9qfx03mj81sv-coreutils-9.1' from 'https://cache.nixos.org'...
copying path '/nix/store/i0x4pzj96qwvkrm94317l6jbi53a2rdj-gnumake-4.4' from 'https://cache.nixos.org'...
copying path '/nix/store/49y3r0gr9m6k20d91kl6dgp4b9a6m72v-diffutils-3.8' from 'https://cache.nixos.org'...
copying path '/nix/store/zml88vnkpm8if114qkbbqd1q7n3ypqqy-findutils-4.9.0' from 'https://cache.nixos.org'...
copying path '/nix/store/5dv5cq1lwvsijr9p16p2kp79g1dbajk3-gnused-4.8' from 'https://cache.nixos.org'...
copying path '/nix/store/89zbjdkb48ma61k76l2mzn3s0ra0wn2c-gnutar-1.34' from 'https://cache.nixos.org'...
copying path '/nix/store/qs8qb1swpivkfq7i9yd52n0mw6z4ij81-gzip-1.12' from 'https://cache.nixos.org'...
copying path '/nix/store/ifs2ghiwngx45a0bkq2lymf4gh8zdr9i-ncurses-6.3-p20220507' from 'https://cache.nixos.org'...
copying path '/nix/store/793iwfbjvg7wgpqq7r83a1qjl1yg02sf-patch-2.7.6' from 'https://cache.nixos.org'...
copying path '/nix/store/g2nfbpind37b3v3y6zbszmcgfmrj5v7x-patchelf-0.15.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7q3p2y40p0q8i63xprvfmc61avp5xqz4-pcre-8.45' from 'https://cache.nixos.org'...
copying path '/nix/store/0gi11bgivf54kbxmns7cw53jjv05n541-readline-8.1p2' from 'https://cache.nixos.org'...
copying path '/nix/store/bcvccw6y9bfil6xrl5j7psza7hnd16ry-gnugrep-3.7' from 'https://cache.nixos.org'...
copying path '/nix/store/x40p83k9mk03kklpfahqppp6kz85yx99-bash-interactive-5.1-p16' from 'https://cache.nixos.org'...
copying path '/nix/store/szznid54xdgn4idxym2dsg166swah5dc-nix-info' from 'https://cache.nixos.org'...
copying path '/nix/store/f7cyasjd42qgr2hsr4w28rs4q907fyi1-xz-5.2.9' from 'https://cache.nixos.org'...
copying path '/nix/store/zaflwh2nwzj1f0wngd7hqm3nvlf3yhsx-zlib-1.2.13' from 'https://cache.nixos.org'...
copying path '/nix/store/a3mwv26f99ycsv9w6hrx0jjjjywvcb1n-xz-5.2.9-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/frh9l9nrdysasdi2gs7i241s241ngjw2-binutils-2.39' from 'https://cache.nixos.org'...
copying path '/nix/store/camlh5laf1wsklghk0vcaw7gvx4rpzd1-file-5.43' from 'https://cache.nixos.org'...
copying path '/nix/store/62fb427ncxaaksa2k59rhbilfg68v20x-binutils-wrapper-2.39' from 'https://cache.nixos.org'...
copying path '/nix/store/sxdx80lmk4zkhb51f4x5dgqvxgmx55wl-gcc-11.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wn31i3dzwahz6ccws8bs1nwyqrpgsvj7-gcc-wrapper-11.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/cp65c8nk29qq5cl1wyy5qyw103cwmax7-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-46-generic, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`

**Comment by FliegendeWurst** [comment]
Works with current nixpkgs
