### ISSUE TITLE
vimPlugins.oxocarbon-nvim

### ISSUE THREAD

**Issue by Alexnortung** [NixOS/nixpkgs#209289]
**Project description**
A colorscheme for neovim

**Metadata**

* homepage URL: https://github.com/nyoom-engineering/oxocarbon.nvim
* source URL: https://github.com/nyoom-engineering/oxocarbon.nvim
* license: mit
* platforms: all

**Comment by figsoda** [comment]
https://github.com/NixOS/nixpkgs/pull/209355
