### ISSUE TITLE
libpciaccess: support macOS

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#20939]
## Issue description
I was trying to build redshift on macOS and it requires libdrm. When installing libdrm, nix-env errored:

```
installing ‘libdrm-2.4.74’
error: Package ‘libpciaccess-0.13.4’ in ‘/nix/store/cjca2yf2wbrv7k38v9p4p5jkbahlbg0v-nixpkgs-17.03pre96799.571cf4f2/nixpkgs/pkgs/servers/x11/xorg/default.nix:1024’ is not supported on ‘x86_64-darwin’, refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
``` 

### Steps to reproduce
1. `nix-env -i libdrm`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) macOS Sierra 10.12.1
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.03pre96799.571cf4f2"

**Comment by matthewbauer** [comment]
Are you sure libpciaccess is compatible with macOS?

**Comment by nhooyr** [comment]
Ah yes, my fault. Building with `./configure --disable-dependency-tracking --enable-quartz --with-systemduserunitdir=no --disable-gui` works great!

Also, you need to set `$ACLOCAL_PATH` to `/Users/name/.nix-profile/share/aclocal`
