### ISSUE TITLE
NixOS 22.11 does not support AMD Raphael 7000 series integrated graphics

### ISSUE THREAD

**Issue by chafey** [NixOS/nixpkgs#209327]
### Describe the bug
Following the getting started documentation for a graphical install using Gnome will result in blank screen on the latest AMD Raphael 7000 cpus when using integrated graphics

### Steps To Reproduce
1. Launch 22.11 Gnome, 64-bit Intel/AMD ISO on an AMD Raphael 7000 based system using integrated graphics
2. Observe that the installer comes up in 1024x768 mode on a 4k monitor
3. Install using the gnome desktop
4. Reboot
5. Observe that the system boots into a blank screen with a flash cursor in the upper left corner of the screen

### Expected behavior
1) The installer should come up using the full monitor resolution
2) After reboot, the display manager should come up instead of the blinking cursor

### Additional context
I am pretty sure this is due to 22.11 using the LTS kernel 5.15 which does not have support for AMD Raphael integrated graphics which was added in 5.18.  I was able to workaround this by using a newer kernel version, but it took me several hours as a new user to figure out how to do this.  A workaround should be documented somewhere so new users with AMD Raphael chips using integrated graphics can successfully install NixOS.

### Notify maintainers

@ryantm - tagging you since documenting this is probably a good short term solution
@fricklerhandwerk - tagging you for documentation

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

This is from my install after I got it working by rebuilding with latest kernel:

```console
% ssh nixos "nix-shell -p nix-info --run \"nix-info -m\""
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.16, NixOS, 22.11 (Raccoon), 22.11.1421.e9ade2c8240`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by stffffn** [comment]
I have encountered the same issue using the IGPU of my 7950x.  
Did you add/change anything else besides switching to the latest kernel?

With the latest kernel I'm able to boot into the display manager (LightDM), but I still have issues with desktop environments. They are either completely white and I can only see the cursor (KDE Plasma and GNOME) or I have a white flashing screen (XFCE).

**Comment by bjornfor** [comment]
> I am pretty sure this is due to 22.11 using the LTS kernel 5.15 which does not have support for AMD Raphael integrated graphics which was added in 5.18. I was able to workaround this by using a newer kernel version, but it took me several hours as a new user to figure out how to do this.

NixOS 23.05 uses Linux 6.1 by default. Closing.
