### ISSUE TITLE
Packaging request: Mirdorph

### ISSUE THREAD

**Issue by SharkLava** [NixOS/nixpkgs#209342]
**Project description**
Open source GTK client for Discord

**Metadata**

* homepage URL: https://gitlab.gnome.org/ranchester/mirdorph
* source URL: https://gitlab.gnome.org/ranchester/mirdorph
* license: GPL3
* platforms: Linux

**Comment by Aleksanaa** [comment]
Can't build this for you but there are also `gtkcord4` and `abaddon` (https://github.com/NixOS/nixpkgs/pull/227776)

**Comment by Aleksanaa** [comment]
Closing since this haven't been updated in 2 years, and some functionalities may be broken. Feel free to reopen this if needed!
