### ISSUE TITLE
nginx needs to me manually restarted on cert changes

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#20947]
When something with the certificates changes (e.g. they go from non-valid to valid) at a system switch, `nginx.service` is restarted at that system switch, but one has to manually restart it again afterwards to make it service the new certificates.

There seems to be a dependency on an other service that is restarted afterwards.

cc @fpletz

**Comment by fpletz** [comment]
[ ] Update ACME documentation (see https://github.com/NixOS/nixpkgs/pull/21320)

**Comment by fpletz** [comment]
We haven't encountered this problem with the fixes to the acme module anymore. I think this can be closed.
