### ISSUE TITLE
atop: atopgpud fails to start when programs.atop.atopgpu.enable is true

### ISSUE THREAD

**Issue by davidwilemski** [NixOS/nixpkgs#209416]
### Describe the bug
`atop` provides the ability to monitor (Nvidia) GPU utilization as optional functionality. When `programs.atop.atopgpu.enable` is set, a systemd service is enabled to start `atopgpud` which is required to enable this ability. `atopgpud` appears to be a Python program that `atop` communicates with in order to monitor the GPU.

When checking the status of the systemd service after enabling atopgpu in my config, I saw:

```console
$ systemctl status atopgpu.service
● atopgpu.service - Atop GPU stats daemon
     Loaded: loaded (/etc/systemd/system/atopgpu.service; linked; preset: enabled)
     Active: active (exited) since Fri 2023-01-06 21:52:42 CST; 13s ago
       Docs: man:atopgpud(8)
    Process: 771782 ExecStart=/nix/store/arn1wq05k8is8j99kfflp20vvhwbvb2b-atop-2.7.1/bin/atopgpud (code=exited, status=0/SUCCESS)
   Main PID: 771782 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out
        CPU: 42ms

Jan 06 21:52:42 faolin systemd[1]: Starting Atop GPU stats daemon...
Jan 06 21:52:42 faolin .atopgpud-wrapp[771782]: atopgpud ERROR: Shared lib 'libnvidia-ml' probably not installed!
Jan 06 21:52:42 faolin systemd[1]: Finished Atop GPU stats daemon.

```

### Steps To Reproduce
1. set `programs.atop.atopgpu.enable = true` in config
2. Run `systemctl status atopgpu.service` and see the process failed.
3. Run `atop`, press 'e' to enter the GPU view. See error message about missing `atopgpud`.

### Expected behavior

`systemctl status atopgpu.service` should show that `atopgpud` was started successfully.

When inside of `atop`, when I press 'e' it should load its GPU utilization view.

### Screenshots

Result when pressing 'e' inside of `atop`:
![image](https://user-images.githubusercontent.com/403152/211130925-f593f4db-cf5c-489f-922b-9dc750ed03b0.png)

### Additional context
I've done some initial debugging and will comment with my findings below.

### Notify maintainers
@7c6f434c 

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.82, NixOS, 22.11 (Raccoon), 22.11.1169.619a61fcfde`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(dtw): `"home-manager-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by davidwilemski** [comment]
When looking into this, I did a search for nvidia-ml in [nixpkgs search](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=nvidia-ml) and was surprised to see `nvidia-ml-py`, a different python package than the one that `atop` depends on. Atop depends on [`pynvml`](https://github.com/NixOS/nixpkgs/blob/a518c77148585023ff56022f09c4b2c418a51ef5/pkgs/os-specific/linux/atop/default.nix#L34) instead. This was initially confusing to me but looking at each of these packages in PyPI, I found they were both owned by Nvidia and are supposedly the same interface. Deeper inspection showed this to be more or less the case, though the `nvidia-ml-py` package appears to have more recent updates

This initially lead me astray as I attempted overrides on the atop package to replace `pynvml` with `nvidia-ml-py` which fixed the issue with finding the shared object but didn't completely fix the problem as I then ran into a Python exception about decoding strings from bytes. (This was a Python 2 vs 3 compatibility thing, it seems `atop` implements that compatibility since the Nvidia library didn't but the more recent versions of `nvidia-ml-py` _do_ have Python 3 compatibility and so the `atop` compatibility layer failed.) In the end, that side path doesn't really matter (though I was also able to fix the atop gpu functionality by switching to that package and then writing a patch in the `atop` nix derivation to fix the Python error).

Examination of the `nvidia-ml-py` package in nixpkgs revealed the issue - `nvidia-ml-py` has a patch to fix loading the `libnvidia-ml` library for NixOS whereas the current packaging of `pynvml` _does not_ include a version of that patch. 

Implementing a similar patch for `pynvml` locally and overriding the `pynvml` package with my patch, and then overriding the `pythonPath` package with my custom `pynvml` package resulted in successfully executing `atopgpud`:

```console
dtw@faolin ~> systemctl status atopgpu.service
● atopgpu.service - Atop GPU stats daemon
     Loaded: loaded (/etc/systemd/system/atopgpu.service; linked; preset: enabled)
     Active: active (exited) since Fri 2023-01-06 22:15:51 CST; 13s ago
       Docs: man:atopgpud(8)
    Process: 772192 ExecStart=/nix/store/jcl1q9g7jasb88hm3nsrhsv0yvacsbg3-atop-2.7.1/bin/atopgpud (code=exited, status=0/SUCCESS)
   Main PID: 772192 (code=exited, status=0/SUCCESS)
         IP: 0B in, 0B out
         IO: 104.0K read, 0B written
      Tasks: 2 (limit: 38424)
     Memory: 19.7M
        CPU: 68ms
     CGroup: /system.slice/atopgpu.service
             └─772196 /nix/store/lbn7f0d2k36i4bgfdrjdwj7npy3r3h5d-python3-3.10.8/bin/python3 -Es /nix/store/jcl1q9g7jasb88hm3nsrhsv0yvacsbg3-atop-2.7.1/bin/.atopgpud-wrapped

Jan 06 22:15:51 faolin systemd[1]: Starting Atop GPU stats daemon...
Jan 06 22:15:51 faolin .atopgpud-wrapp[772196]: atopgpud INFO: Number of GPUs: 1
Jan 06 22:15:51 faolin .atopgpud-wrapp[772196]: atopgpud INFO: Initialization succeeded
Jan 06 22:15:51 faolin systemd[1]: Finished Atop GPU stats daemon.
```

I was then able to view GPU utilization in atop!

![image](https://user-images.githubusercontent.com/403152/211131824-ea373701-d304-46d9-bed0-f9d73c112a3e.png)


I suppose this boils down to a bug in the packaging of `pynvml`, not sure if that warrants a separate issue but either way I can put a PR up with the patch for loading the shared library as a starting point. Not sure if there's a more ideal fix.

**Comment by 7c6f434c** [comment]
I am absolutely incompetent about the non-Nouveau drivers for Nvidia… But `pynvml` PR looks reasonable, so if it gets stuck and forgotten, you are welcome to remind me to merge it (I guess now there is still a chance to get a useful review from someone who understands this better)
