### ISSUE TITLE
Steam FHS env should populate /usr/share/fonts

### ISSUE THREAD

**Issue by danderson** [NixOS/nixpkgs#209424]
### Describe the bug

Some Steam games try to load fonts from the hardcoded path /usr/share/fonts.

Well behaved Unity games embed the fonts they use into their game assets, so when the game requests font `Foo`, Unity can just pull it from the game assets.

But some games/mods, for example some of Kerbal Space Program's mods, request well-known Windows fonts that are not in the game asset bundle. In this case, Unity will go and search for that font in an OS-dependent way. Unfortunately, on linux, that OS-dependent way is "see if the font is present in /usr/share/fonts".

If Unity fails to find a requested font, helpfully it doesn't fail or print errors or anything: it just doesn't render any text that was printed in that font, and so you end up with in-game UIs that look like this:

![foo](https://user-images.githubusercontent.com/1918/211134947-ebcf595f-322c-4587-bd6a-f3e756e2c94b.png)

One way to reproduce this: install Kerbal Space Program, install the Kerbal Engineer mod, go in-game and open any Kerbal Engineer info screen. Empty borked UI widgets like above is what you'll get.

### Expected behavior

If /usr/share/fonts is not present, the steam runtime wrapper should construct one, so that Unity games that rely on system fonts have a chance to work.

### Ways to fix this

I'm not sure, or I would have sent a PR :/

If you're running Nix on a non-NixOS system, most probably /usr/share/fonts exists and contains the right fonts already. So, in that case, the steam runtime env shouldn't override /usr/share/fonts.

If you're running on NixOS, /usr/share/fonts never exists, and we need to make it. Easiest way to do that, afaict, is to require `fonts.fontDir.enable = true` in your NixOS config, which creates a symlink farm of fonts at `/run/current-system/sw/share/X11/fonts`, and we can then tell brap to `--symlink` that to /usr/share/fonts... I think.

buildFHSUserEnv is not quite flexible enough to allow optionally doing bind mounts at runtime, so we can't trivially do conditional mounting based on whether /usr/share/fonts already exists. But we can do it non-trivially!

buildFHSUserEnv accepts `extraBwrapArgs` and `runScript`. So, what we can do is construct a sneaky symlink chain that allows the steam runScript to make this decision at runtime. Something like:

```
extraBwrapArgs = [
  "--tmpfs /hack"
  "--tmpfs /usr/share/fonts"
  "--ro-bind-try /usr/share/fonts /hack/sys-fonts"
  "--ro-bind-try /run/current-system/sw/share/X11/fonts /hack/nixos-fonts"
]
```

With this, the bwrap env spawns with an empty /usr/share/fonts, and /hack gives access to the union of non-NixOS system fonts and NixOS fonts, if they exist. Then:

```
runScript = ''
  ...

  for f in /hack/sys-fonts/* /hack/nixos-fonts/*; do
    ln -sf $(readlink -f $i) /usr/share/fonts/$(basename $i)
  done

  ...
```

This dumps a merge of any system fonts and any nixos fonts that are available into /usr/share/fonts, so the steam FHS ends up with a union of all possible NixOS and non-NixOS system fonts available at the hardcoded location.

As an alternative to the bind-try hacks, we could also have the runscript use the output of `fc-list` (part of fontconfig, so already in the steam FHS) to populate /usr/share/fonts. This correctly reads the containerized font config at /etc/fonts, so arguably it's a more "principled" result, because it's just materializing the container's fontconfig in a new location, which will make fontconfig and hardcoded programs have access to the same set of fonts.

### Notify maintainers

@jagajaga @jonringer . Sorry to bring horrible hacks to your inbox, and thank you for maintaining Steam on NixOS! I'm more than happy to send a PR along the lines above, I just wanted to write this down in case you have a much better way to do this that I didn't think of.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.16, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(dave): `"nixos-unstable-22.05pre356435.7f9b6e2babf, nixpkgs-20.09.4407.1c1f5649bb9"`
 - nixpkgs: `/home/dave/.nix-defexpr/channels/nixpkgs`
```

**Comment by QuantMint** [comment]
https://github.com/NixOS/nixpkgs/pull/195521

**Comment by mabster314** [comment]
Switching to Steam Linux Runtime under compatibility options fixed the issue for me if anyone is googling this
