### ISSUE TITLE
pygtk build is broken

### ISSUE THREAD

**Issue by mdorman** [NixOS/nixpkgs#20943]
http://hydra.nixos.org/build/44579911 has the log of a failing build, which I can reproduce verbatim locally (so it would not appear to be transient).

This would appear to be a consequence of the big python infrastructure changes?  Maybe @FRidh (I'm guessing, and I apologize in advance if I'm guessing incorrectly)?

**Comment by FRidh** [comment]
Thanks for the report.

So it seems that c1d98d959b38df00a1d933a5a9a381aa80096024 fixed certain packages but broke others.

**Comment by avnik** [comment]
@FRidh may be
```
configurePhase = attrs.configurePhase or '' runHook ....
```
will works better?

**Comment by FRidh** [comment]
yes

**Comment by avnik** [comment]
@FRidh at least it fix pygtk, I can make PR when my build complete (if you like)

**Comment by FRidh** [comment]
@avnik I'm testing a couple of other packages first and then I'll push it. But thanks!
