### ISSUE TITLE
Kubelet fail to run /sbin/modprobe

### ISSUE THREAD

**Issue by yuchangyuan** [NixOS/nixpkgs#20949]
## Issue description

When try to use cephfs volume with kubernetes, the cephfs volume fail to mount.

### Steps to reproduce

create any pod with cephfs volume,  below are some examples:
[https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/cephfs](url)

## Technical details

Something like below will appear in system log:
> kubelet[2087]: Output: sh: /sbin/modprobe: No such file or directory

* System: NixOS 16.09.1024.c859ea0 (Flounder)
* Nix version: nix-env (Nix) 1.11.4 
* Nixpkgs version: 17.03pre96298.b09435e(I use unstable version of kubernetes package)

**Comment by Profpatsch** [comment]
(triage) still an issue?
