### ISSUE TITLE
x42-plugins: do not know how to unpack source archive

### ISSUE THREAD

**Issue by magnetophon** [NixOS/nixpkgs#20950]
## Issue description
The package [x42-plugins](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/x42-plugins/default.nix) alternates between building fine and ["do not know how to unpack source archive"](https://hydra.nixos.org/build/44408606/log).
It has been doing this for months, even for different versions of the pkg.
It has the same storepath for the .tar.xz, for both the good and bad builds.

**Comment by FRidh** [comment]
This has indeed been noticed more often, but no solution was found. See also https://github.com/NixOS/nixpkgs/issues/18209#issuecomment-244542006.

**Comment by magnetophon** [comment]
@x42 Any idea what could cause this?

**Comment by x42** [comment]
What does `file x42-plugins-20170428.tar.xz` say?  Do you have `xz` installed on the build-machine or a `tar` built with lzma support?

Does the file's sha1sum match the upstream release?
```
fd96c827aac170e22deb038966f3d2e55b5740c7 x42-plugins-20170428.tar.xz
```

**Comment by magnetophon** [comment]
@x42 The error is intermittent. 
The build environment is the same each time, so the software to unpack is present.
The ``sha256 `` sum is checked each time, directly after the download, and never errors.

This error has been occurring on and of trough many versions of your plugins.
AFAIK it has never happened on other packages.

**Comment by x42** [comment]
I thought maybe download fails on occasion but If the sha256 sum matches that cannot be the case.
I don't have an explanation for that: If an identical file only works sometimes, it must be something on  NixOS side.

https://github.com/NixOS/nixpkgs/issues/8694 has the same error message for a different package, file-extension being the issue there.

**Comment by magnetophon** [comment]
@x42 It indeed looks like the issue is on the NixOS side;I was just hoping you could provide some insight.

The issue you linked seems different, in that it tries to unpack something that shouldn't be unpacked, and it happens consistently.

Thanks for your time.

**Comment by timokau** [comment]
The same thing happens with newsboat: https://github.com/NixOS/nixpkgs/issues/60845

**Comment by magnetophon** [comment]
still important to me
