### ISSUE TITLE
clangStdenv doesn't seem to work

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#20963]
So, I think that clangStdenv is implemented rather naively. It seems to force compilation of stages 0-3 with clang, meaning that it tries to build glib and the kernel with clang. This barfs out.

Can it be fixed to apply set clang to be cc after building the kernel and glib?

**Comment by Atemu** [comment]
`clangStdenv` is working nowadays and is actually used in some packages.
