### ISSUE TITLE
Impurity in boost build

### ISSUE THREAD

**Issue by ckauhaus** [NixOS/nixpkgs#20976]
## Issue description

I'm trying to build boost-1.59 and boost-1.60 @ release-16.09 on a Gentoo host with nixpkgs installed. It failes due to an impure access of `/usr/share/boost-build/site-config.jam`. The relevant traceback is:
```
/tmp/nix-build-boost-1.60.0.drv-0/boost_1_60_0/tools/build/src/build/feature.jam:494: in feature.validate-value-string from module feature
error: "none" is not a known value of feature <optimization>
error: legal values: "off" "speed" "space"
/tmp/nix-build-boost-1.60.0.drv-0/boost_1_60_0/tools/build/src/build/property.jam:276: in validate1 from module property
/tmp/nix-build-boost-1.60.0.drv-0/boost_1_60_0/tools/build/src/build/property.jam:302: in property.validate from module property
/tmp/nix-build-boost-1.60.0.drv-0/boost_1_60_0/tools/build/src/tools/builtin.jam:380: in variant from module builtin
/usr/share/boost-build/site-config.jam:9: in modules.load from module site-config
```

See the attached log file for a full build log. I think this impurity should be removed, so that the outcome of Nix boost does not depend on any boost build system artefacts on the host OS. In this case, a custom option from Gentoo causes the build failure.

### Steps to reproduce

```
# cd into a checked out 16.09 source tree
$ ls /usr/share/boost-build
ls: cannot access /usr/share/boost-build: No such file or directory
$ nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; callPackage pkgs/development/libraries/boost/1.60.nix {}'
# ... lots of output ...
/nix/store/d4ff5i7cx4dm0660idirv9849kfrvpjd-boost-1.60.0
$ rm result; nix-collect-garbage -d
$ mkdir /usr/share/boost-build
$ echo 'variant gentoo : release : <optimization>none <debug-symbols>none <runtime-link>shared ;' > /usr/share/boost-build/site-config.jam
$ nix-build -I nixpkgs=. -E 'with import <nixpkgs> {}; callPackage pkgs/development/libraries/boost/1.60.nix {}'
# ... lots of output ...
builder for ‘/nix/store/50s4yiwxn24hcwnbl1myysdvkza37icn-boost-1.60.0.drv’ failed with exit code 1
```

## Technical details

* System: Gentoo Base System release 2.2
* Nix version: nix-env (Nix) 1.11.2
* Nixpkgs version: 16.09pre-git (37f53d97a8fd798ac83d3392b909c4569b3cde81)

[boost-1.60.log.txt](https://github.com/NixOS/nixpkgs/files/637178/boost-1.60.log.txt)

**Comment by vcunat** [comment]
Such impurities are certainly better removed. On the other hand I strongly recommend to use [sandboxing](http://nixos.org/nix/manual/#conf-build-sandbox-paths), especially on non-NixOS systems that want to do more building from source.

**Comment by ckauhaus** [comment]
You're right, the issue disappears with `build-use-sandbox = true` in nix.conf. Perhaps it is a good idea to fix it regardless of sandboxing is used or not.

**Comment by ckauhaus** [comment]
issue redrawn
