### ISSUE TITLE
Missing libunwind.h on darwin

### ISSUE THREAD

**Issue by vbgl** [NixOS/nixpkgs#20977]
## Issue description

On darwin, package `libunwind` does not provide the file `include/libunwind.h`.

git bissection lead me to commits e6ea302c47c58c2ad525263305853b03739df34d and 28a0da5edc23b8af5396f1725a05965a81ab3513

cc @copumpkin 

## Technical details

* System: macosx 10.11.6
* Nix version: 1.11.4

**Comment by LnL7** [comment]
Looks like there are `include/*.h.in` files in the output, it currently just copies the files. https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/libunwind/default.nix
