### ISSUE TITLE
Tokodon - Mastodon Client

### ISSUE THREAD

**Issue by aquada** [NixOS/nixpkgs#209734]
**Project description**
Tokodon is a Mastodon client for Plasma and Plasma Mobile

**Metadata**

* homepage URL:  https://invent.kde.org/network/tokodon
* source URL: https://github.com/KDE/tokodon
* license: GNU General Public License 3
* platforms: Linux

**Comment by matthiasbeyer** [comment]
Tokodon is packaged in nixpkgs in plasma-mobile (`libsForQt5.plasma-mobile`). It is just not exposed yet.

**Comment by Aleksanaa** [comment]
> Tokodon is packaged in nixpkgs in plasma-mobile (`libsForQt5.plasma-mobile`). It is just not exposed yet.

Then why is it still not exposed?
