### ISSUE TITLE
vte and vte-ng collision

### ISSUE THREAD

**Issue by denisshevchenko** [NixOS/nixpkgs#20979]
## Issue description

I'm trying to install `gnome3` just after minimal installation (I used `Minimal installation CD, 64-bit Intel/AMD`). I do (from non-root user):

```
# nix-env -iA nixos.gnome3
```

After long installation I see an error, during building `user-environment`. The problem is a collision between `vte-ng-0.42.4.a/etc/profile.d/vte.sh` and `vte-0.36.3/etc/profile.d/vte.sh`.

How should I set `priority` **correctly** to solve this collision?

### Steps to reproduce

Every time after `nix-env -iA nixos.gnome3` I see the same error message.

## Technical details

* System: NixOS 16.09.1217.0016d36
* Nix version: 1.11.4
* Nixpkgs version: "16.09.1217.0016d36"

**Comment by vcunat** [comment]
That command probably wouldn't do what you expect. Most likely you want to set `services.xserver.desktopManager.gnome3.enable = true;` in your `configuration.nix`.

**Comment by vcunat** [comment]
I forgot to say: doing that will allow you to select gnome3 in when logging in and start that desktop, including all its default apps.

**Comment by denisshevchenko** [comment]
Thanks @vcunat, it works now!
