### ISSUE TITLE
[package request] hadoop-lzo

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#20987]
See: https://github.com/twitter/hadoop-lzo.
lzo has already been packaged in nixpkgs.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR.
