### ISSUE TITLE
MRAN retirement

### ISSUE THREAD

**Issue by Kupac** [NixOS/nixpkgs#209871]
`generate-r-packages.R` relies on MRAN mirror, which [is about to retire](https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161) at the end of this month. Could we switch to another mirror such as CRAN/posit package manager?

@jbedo

**Comment by jbedo** [comment]
We do need to switch, not just the update script but currently CRAN packages are fetched from MRAN. Official CRAN mirrors would be preferable but the organisation is not ideal as the archive tarballs are at a different path to the latest release.

**Comment by Kupac** [comment]
[Posit Public Package Manager](https://packagemanager.rstudio.com/client/#/repos/2/overview) is a similar service. I'm not sure if it's equivalent to MRAN. `https://packagemanager.rstudio.com/cran/${datestr}` or `/latest` could work
