### ISSUE TITLE
Missing pager in pure env: git fails 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#20997]
```
$ git diff
less -R: less: command not found

$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09.1219.c1068dc"

```

**Comment by Mic92** [comment]
Could be added to gitFull probably?

**Comment by FRidh** [comment]
This is a common issue with applications that need a pager. You'll notice it also e.g. when calling the help function from Python when using --pure. When I noticed I added less to the closure but this was later reverted (https://github.com/NixOS/nixpkgs/issues/17034).

**Comment by matthewbauer** [comment]
I guess it's an open question whether $PAGER should be included/wrapped in drvs? I think it's probably best to leave them separate since it will lead to bloated closures. Another potential issue is $EDITOR which git will also expect.

**Comment by mmahut** [comment]
Any news on this issue?

**Comment by FRidh** [comment]
I agree with @matthewbauer Let's leave these to be impure.
