### ISSUE TITLE
RFC: Declarative disk layout

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#209988]
**Project description**

One of the hardest parts of setting up a NixOS (or any Linux) system from scratch is setting up the disk itself. Deciding how big each partition needs to be, making sure it's UEFI compliant, whether to use LUKS inside LVM or LVM inside LUKS, remembering to set a partition bootable, etc. It would be fantastic to have a declarative way to deal with this. Features which come to mind include:

- Integrates with the GUI installer. Point the installer to a `configuration.nix` with a disk layout somewhere, and it just goes and does all the necessary setup, asking for things like passphrases where necessary.
- A tool to extract the Nix configuration from currently mounted file systems, expanding on what `nixos-generate-config` already does.
- Optionally some way to apply the relevant part of a `configuration.nix` file to a system manually, like [disko](https://github.com/nix-community/disko).

**Comment by gbtb** [comment]
I'm not sure, but maybe this issue should be raised at https://github.com/NixOS/rfcs ?

**Comment by surfaceflinger** [comment]
Bad repo + you might want to checkout [disko](https://github.com/nix-community/disko)
