### ISSUE TITLE
hhvm: missing libdwarf.so.1

### ISSUE THREAD

**Issue by tari** [NixOS/nixpkgs#20994]
## Issue description

HHVM is broken because it looks for libdwarf.so.1, while it looks like libdwarf only provides an unversioned libdwarf.so. It broke somewhere between 16.03 and 16.09, since it didn't start failing until I upgraded to 16.09.

Might be the same problem as #5072 since libdwarf has since been updated in 16.09 but not in 16.03.

### Steps to reproduce

Install HHVM.

```
$ hhvm
hhvm: error while loading shared libraries: libdwarf.so.1: cannot open shared object file: No such file or directory
```

## Technical details

nixos 16.09 - I don't have a precise version since I had to roll back. Verified issue exists in master as well.

**Comment by tari** [comment]
libdwarf [started setting a soname](https://sourceforge.net/p/libdwarf/code/ci/db5765d22395412f63634e832a0b96777ed5df3f/) with #18968. Installing libdwarf.so.1 and symlinking libdwarf.so should fix it; I'm preparing a PR.

**Comment by vcunat** [comment]
Hmm, I understand now &ndash; it was broken by our previous update fcb41707f1 and not the last one.
