### ISSUE TITLE
Mlt glaxnimate missing from Kdenlive

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#209923]
### Describe the bug

When starting KDEnlive from a fresh install/user, a warning is printed:

![image](https://user-images.githubusercontent.com/2164118/211380665-4985ba84-5aca-44bf-b90c-0da52e9a1e5b.png)

saying that `mediainfo` is missing (so technical info regarding video can't be displayed), and the `Missing MLT module: glaxnimate` needed for Lottie animation (vectorial animations).

Note that that you can still ignore the error, the message being displayed only the first time Kdenlive starts. It can be seen again by going into `Settings / Run config wizzard`

### Steps To Reproduce
```
$ mkdir /tmp/home # or go to «Settings / Run config wizzard»
$ export HOME=/tmp/home
$ nix run github:NixOs/nixpkgs/0c9aadc8eff6daaa5149d2df9e6c49baaf44161c#kdenlive
```

Note that glaxnimate is packaged into nixpkgs since today https://github.com/NixOS/nixpkgs/issues/208707 and the issue was initially reported here https://discourse.nixos.org/t/kdenlive-missing-mlt-module-glaxnimate/24486/4

### Possible fix

The error on mediainfo can easily be fixed by installing `mediainfo`. No idea how to solve glaxnimate, installing glaxnimate is not enough… however after installing glaxnimate the tool appears in Settings / Settings KDEnlive / Environment / Default app / Animation editing`:

![image](https://user-images.githubusercontent.com/2164118/211384479-34b0bf3a-1f66-4e34-91d3-94a6184c5325.png)

Note however that in the previous tab `MLT environment` you can see the path to MLT `profile` folder, contained in:
```
$ ls /nix/store/parkimd4avly3ahwsyy869yba9pibp1k-mlt-7.0.1/share/mlt-7/
avformat  core  decklink  frei0r  jackrack  kdenlive  metaschema.yaml  movit  normalize  oldfilm  plus  plusgpl  presets  profiles  qt  resample  rtaudio  sdl  sox  vid.stab  vorbis  xml
```
### Notify maintainers

@turion 

### Related

https://forums.opensuse.org/t/ontbrekende-mlt-module-glaxnimate-vereist-om-lottie-animaties-te-maken/153692/10
the code
https://github.com/KDE/kdenlive/blob/master/src/dialogs/wizard.cpp#L345

**Comment by tobiasBora** [comment]
Note also that KDEnlive states that pip can't be found when going in the settings/ vocal recognition tab:

![image](https://user-images.githubusercontent.com/2164118/211382653-af5652d4-81c8-4988-b757-294b4aed3eac.png)

**Comment by tobiasBora** [comment]
Ok, seems like this option can be enabled at compile time https://github.com/KDE/kdenlive/blob/cb9d880e36a04ddd6836d932a7453329b30ec853/packaging/flatpak/org.kde.kdenlive-nightly.json#L719 using

```
-DMOD_GLAXNIMATE=ON
```

**Comment by tobiasBora** [comment]
This PR adds also a new functionality in KDEnlive to edit vectorial animations. See tutorial here https://www.youtube.com/watch?v=em-km2xzVnw (french, but should be fairly easy to follow)

**Comment by lcuevastodoit** [comment]
BTW on Ubuntu Jammy 22.04
You can install mediainfo like this using apt
`sudo apt install mediainfo`
You can install glaxnimate via snap using snap at the same time
`snap install glaxnimate`
And always you can have the kdenlive ppa optional
sudo add-apt-repository ppa:kdenlive/kdenlive-stable -y

**Comment by richardpickett** [comment]
> You can install glaxnimate via snap using snap at the same time
> `snap install glaxnimate`

Negative ghostrider.

Ubuntu 22.04
snap installed kdenlive (23.04.3)

When it starts up, it throws the same "missing glaxnimate" as the OP (only mine is in English).
Aborted, snap installed glaxnimate, same error.

**Comment by AdrieVanDijk** [comment]
> @lcuevastodoit said:
> 
> > You can install glaxnimate via snap using snap at the same time
> > `snap install glaxnimate`
> 
> Negative ghostrider.
> 
> Ubuntu 22.04 snap installed kdenlive (23.04.3)
> 
> When it starts up, it throws the same "missing glaxnimate" as the OP (only mine is in English). Aborted, snap installed glaxnimate, same error.

After installing the glaxnimate snap, I entered '/usr/bin/snap' as path for 'Animation editing' in the 'Default Apps' tab, (see 'Possible fix' from the OP) and then the error message did not appear anymore.

**Comment by fir3-1ce** [comment]
For those of you on Ubuntu 22.04 who don't want to use Snap (like me), You can just go to glaxnimate's website and download a deb package. The prompt went away on kdenlive after doing that.

**Comment by turion** [comment]
@lcuevastodoit @richardpickett @fir3-1ce @AdrieVanDijk Are your comments at all related to nixpkgs? Or should they rather be moved to a Ubuntu forum?

**Comment by RichardJActon** [comment]
I've just encountered a similar issue. When I try and do a render it opens a window titled MLT that just says 'invalid' in big letters - it gets to 99% render then just hangs - I'm not getting any of the mlt missing warnings but it seems to be an mlt issue.

I'm on NixOS 24.05.20240611.47b604b (Uakari) x86_64

(I installed the flatpak version an that worked for me)
