### ISSUE TITLE
pipelight lacks mozilla plugin

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#21004]
## Issue description
```
$ ls -l $(nix-build -A pipelight)/lib/mozilla/plugins
total 0
```

Even though the expression has this bit:

```nix
postInstall = ''
  $out/bin/pipelight-plugin --create-mozilla-plugins
'':
```

That build step doesn't create any output in the build log. There is no sign of error, but still the plugin isn't built.

Tested both on NixOS 16.09 and latest master.

The reason for wanting pipelight for firefox is to watch HBO Nordic :-)

**Comment by 7c6f434c** [comment]
>Even though the expression has this bit:
>
>```nix
>postInstall = ''
>  $out/bin/pipelight-plugin --create-mozilla-plugins
>'':
>```
>
>That build step doesn't create any output in the build log. There is no sign of error, but still the plugin isn't built.

Clarification requested: does the following command work:
```
LANG=en_US.ISO8859-1 LC_ALL= WINE=$(nix-build --no-out-link '<nixpkgs>' -A pipelight.wine)/bin/wine WINEPREFIX=$HOME/.wine-pipelight WINEARCH=win32 MOZ_PLUGIN_PATH=$(nix-build --no-out-link '<nixpkgs>' -A pipelight)/lib/pipelight/ firefox
```

That is approximately (up to locale and a trivial nix-build wrapper) the command I have used when I last used pipelight. I didn't care enough to learn how to install everything fully properly, and I needed to override both locale and Wine anyway.

>The reason for wanting pipelight for firefox is to watch HBO Nordic

Oh well, I had a more annoying reason to need pipelight… But I did use it with Firefox, succesfully.

By the way, it looks like Firefox changes about plugins may break pipelight relatively soon…

**Comment by bjornfor** [comment]
That command does not enable the plugin in firefox for me. The "about:plugins" page does not list anything new and HBO Nordic complains about missing Adobe Flash.

**Comment by 7c6f434c** [comment]
>That command does not enable the plugin in firefox for me. The "about:plugins" page does not list anything new and HBO Nordic complains about missing Adobe Flash.

Do you need Silverlight/pipelight or Adobe Flash?

**Comment by bjornfor** [comment]
According to my information (https://ubuntuforums.org/showthread.php?t=2274467), I need both flash _and_ silverlight. Both are provided by/via pipelight, right? I'm not familiar with this stuff.

**Comment by 7c6f434c** [comment]
>According to my information (https://ubuntuforums.org/showthread.php?t=2274467), I need both flash _and_ silverlight. Both are provided by/via pipelight, right? I'm not familiar with this stuff.

We definitely have a separate `flashplayer`.

But maybe pipelight downloads a Windows version and runs it under Wine…

Looking into it, seems to be that the `master` version of `pipelight` 
upstream still contains URLs that give 404.

**Comment by bjornfor** [comment]
> We definitely have a separate `flashplayer`.

Right. I did try that yesterday, but on a different machine than I'm using now. (Sorry for the confusion.) With firefox.enableAdobeFlash = true, HBO Nordic didn't report any error about missing flash, but when I pressed play on a video it was showing me the "loading" screen forever... (I found that other people have had this issue and solved it with pipelight).

> But maybe pipelight downloads a Windows version and runs it under Wine…

Right, that is my understanding, pipelight enable Linux systems to run _Windows_ plugins (unmodified).

**Comment by 7c6f434c** [comment]
Looks like a few URLs `pipelight` uses are out-of-date even in the 
upstream master… Any ideas where to get a fresher `install-dependency`
script? Or maybe you are willing to update the upstream script so we can
overwrite the shipped one with a newer one during the installation.

**Comment by bjornfor** [comment]
I'll add it to my TODO :-)

**Comment by bjornfor** [comment]
Pipelight is now officially discontinued: http://pipelight.net/

I found some issues with the nixpkgs package[1], but fixing those didn't fix HBO Nordic :-)

[1] A bad substituteInPlace messing up a "cabextract" function name, wrong --wine-path=... pointing to a directory instead of wine binary, reference to /usr/bin/id. Found via "pipelight-plugin --system-check".
