### ISSUE TITLE
nixos/nextcloud recommends PostgreSQL

### ISSUE THREAD

**Issue by dotlambda** [NixOS/nixpkgs#210063]
## Problem
Our manual [says](https://nixos.org/manual/nixos/stable/index.html#module-services-nextcloud-basic-usage)
> it's recommended to use [services.postgresql](https://nixos.org/manual/nixos/stable/options.html#opt-services.postgresql.enable)

but upstream [says](https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/linux_database_configuration.html)

> The MySQL or MariaDB databases are the recommended database engines.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

## Proposal

Explain why our recommendation differs from upstream's or update ours to match theirs.

cc @Ma27 @RaitoBezarius @SuperSandro2000 @Enzime

**Comment by SuperSandro2000** [comment]
My guess would be that we always prefer nginx and postgres because they are well integrated and tested and our preferred software.

**Comment by Ma27** [comment]
Yes. In fact I won't recommend MySQL because we had to implement super-nasty workarounds because our mariadb was too new for Nextcloud and upstream didn't manage to fix the issues on their side (not sure if it's fixed today).

Using postgresql with Nextcloud has proven to work extremely well on multiple production instances, so strong :-1: to change that.

Hence, won't fix.

**Comment by dotlambda** [comment]
> Using postgresql with Nextcloud has proven to work extremely well on multiple production instances, so strong :-1: to change that.

You should read my issue closely:

> Explain why our recommendation differs from upstream's *or* update ours to match theirs.
