### ISSUE TITLE
Enable extra fonts in kernel configuration

### ISSUE THREAD

**Issue by 9ary** [NixOS/nixpkgs#210070]
## Issue description

NixOS's default kernel configuration only enables the 8x8 and 8x16 fonts. This is not ideal, because they are too small for high-resolution displays. The current workaround used by `config.hardware.video.hidpi.enable` is to set `console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-v32n.psf.gz"`. There are problems with this however:
- during early boot, before the GPU drivers are loaded, the firmware or bootloader may initialize the display at a lower resolution, resulting in an oversized font
  - in fact, the hidpi module sets `boot.loader.systemd-boot.consoleMode = mkDefault "1"`, which in my opinion is a bad idea, because it will force switching to a low resolution when the firmware could have set us up with a high-res framebuffer; this also breaks seamless boot for those who care (sd-boot's default is to keep the mode unchanged)
- resolution switches reset the font to the kernel default, and under certain circumstances it seems a race condition can prevent userspace from setting the font correctly again

The kernel is actually able to select an appropriate font for the current resolution using a simple heuristic since mid-2019 (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dfd19a5004eff03755967086aa04254c3d91b8ec). This bypasses the problems listed above and ensures a good font is always selected after resolution switches. The only requirement appears to be that the fonts must be built into the kernel.

## Technical details

Font-related kconfig options as configured by NixOS:
```
CONFIG_FONT_SUPPORT=y
# CONFIG_FONTS is not set
CONFIG_FONT_8x8=y
CONFIG_FONT_8x16=y
```

Arch Linux:
```
CONFIG_FONT_SUPPORT=y
CONFIG_FONTS=y
# CONFIG_FONT_8x8 is not set
CONFIG_FONT_8x16=y
# CONFIG_FONT_6x11 is not set
# CONFIG_FONT_7x14 is not set
# CONFIG_FONT_PEARL_8x8 is not set
# CONFIG_FONT_ACORN_8x8 is not set
# CONFIG_FONT_MINI_4x6 is not set
# CONFIG_FONT_6x10 is not set
# CONFIG_FONT_10x18 is not set
# CONFIG_FONT_SUN8x16 is not set
# CONFIG_FONT_SUN12x22 is not set
CONFIG_FONT_TER16x32=y
# CONFIG_FONT_6x8 is not set
```

So Arch enables the default 8x16 and Terminus 16x32 (the same font that the hidpi module sets). The observed behavior on Arch is that it seamlessly switches fonts after mode switches, and I've never seen this break since it has been enabled.

**Comment by xRiot** [comment]
Same issue here with a NVIDIA card and a 3840x2160 monitor. The tty0 console text covers the entire screen. I couldn't resolve this issue manually with `boot.initrd.availableKernelModules = [ "nvidia" ];` and `boot.kernelParams = [ "video=DP-3:3840x2160@60" ];` (DP-3 is my monitor).

Setting the font manually to the default value (`console.font = "Lat2-Terminus16";`) gives the right font size but this particular font doesn't have antialiasing which looks quite bad on a HIDPI monitor.

**Comment by 9ary** [comment]
There's no antialiasing in console fonts, they're all bitmap fonts.

**Comment by xRiot** [comment]
Gotcha, thanks.

On side note, I looked for a different consolefont and came up with this. Looks a lot better now:
```
console = {
  earlySetup = true;
  font = "${pkgs.tamzen}/share/consolefonts/TamzenForPowerline8x16.psf"; 
  packages = with pkgs; [ tamzen ];
};
```
