### ISSUE TITLE
zathura - epub plugin doesn't seem to be loaded/handling epub files

### ISSUE THREAD

**Issue by Arteneko** [NixOS/nixpkgs#210119]
### Describe the bug

The [zathura package definition](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/applications/misc/zathura/wrapper.nix#L26), per my understanding, shows that epub-supporting plugins are installed by default.
I am trying to load and display/read epub files since it's my main document format, but zathura only loads (and fails) them as PDFs.

### Steps To Reproduce
1. install `zathura` from nixos 22.11 package index
2. run `zathura ./file.epub`

### Expected behavior

zathura opens the document without complaining and works out of the box.

### Screenshots

```
zathura Dans\ La\ Peau\ D\'Un\ Chien\ -\ Alexandra\ Horowitz.epub                                
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
warning: name is too long
warning: ... repeated 6 times...
error: invalid key in dict
warning: name is too long
warning: ... repeated 4 times...
error: invalid key in dict
warning: name is too long
warning: ... repeated 5 times...
error: invalid key in dict
error: invalid key in dict
error: invalid key in dict
error: invalid key in dict
error: invalid key in dict
warning: name is too long
warning: ... repeated 2 times...
error: invalid key in dict
warning: name is too long
error: invalid key in dict
warning: name is too long
error: invalid key in dict
error: invalid key in dict
error: invalid key in dict
error: invalid key in dict
error: invalid key in dict
warning: name is too long
error: invalid key in dict
warning: name is too long
error: no objects found
error: could not open document
```

### Additional context

I installed zathura using home-manager, with home-manager configured to inherit the nixos `configuraiton.nix` nixpkgs block.

### Notify maintainers

cc @grwlf @globin  @TethysSvensson

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.11 (Raccoon), 22.11.1137.dac57a4eccf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-unstable"`
 - channels(nyx): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ralismark** [comment]
The zathura I get with `nix run github:nixos/nixpkgs/nixos-22.11#zathura` seems to open epub files file.

This is very much a guess, but can you try adding this to your configuration.nix?
```
  environment.systemPackages = [ pkgs.shared-mime-info ];
  environment.pathsToLink = [
    "/share/mime"
  ];
```
If the issue is zathura's filetype detection, this might fix it.

**Comment by Arteneko** [comment]
I forgot to retry the issue before trying this fix, but since I didn't do anything new with my laptop after this bug report, and since trying this change makes zathura behave as expected with epub files, I'll consider it fixed.

Thanks a lot!

**Comment by x64x2** [comment]
Did you resolve this issue?
