### ISSUE TITLE
Enable IPv6 support on CloudFront / cache.nixos.org

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#21020]
## Issue description

CloudFront now supports ipv6 in multiple edge locations, and appears to be in all edges we use: https://ipv6deployedtoyouredgelocation.com/index.html

Users should be able to fetch substitutions using IPv6 to access our cache.

**Comment by domenkozar** [comment]
This should go to https://github.com/NixOS/nixos-homepage/issues

**Comment by grahamc** [comment]
👍 I'll move the other too. Thanks!

**Comment by grahamc** [comment]
Moved: https://github.com/NixOS/nixos-homepage/issues/116
