### ISSUE TITLE
tinyMediaManager

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixpkgs#210273]
**Project description**
tinyMediaManager is a media management tool written in Java/Swing. It is written to provide metadata for the Kodi Media Center (formerly known as XBMC), MediaPortal and Plex media server. Due to the fact that it is written in Java, tinyMediaManager will run on Windows, Linux and macOS (and possible more OS).

**Metadata**

* homepage URL: https://www.tinymediamanager.org/
* source URL: https://mediaarea.net/en/MediaInfo/Download
* license:  ...
* platforms: linux, darwin

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/191163

**Comment by phpcitizen** [comment]
Thanks for letting me know, closing.
