### ISSUE TITLE
Steam: Clicking Stream to start steam play in the classic UI gives 'Cannot read property TakeFocus of undefined'

### ISSUE THREAD

**Issue by lucasew** [NixOS/nixpkgs#210369]
### Describe the bug
I have a PC and a laptop. The PC I use mostly headless, but with a dummy HDMI plug. All screens are connected to the laptop.

Any game that is downloaded in the PC that I try to stream to the laptop gives this error:
![Captura de tela_2023-01-12_11-40-14](https://user-images.githubusercontent.com/15693688/212095902-732002da-c38c-4db2-93e8-cb11e48ab1cd.png)

From my phone, over WiFi, it works, although it gives some flickering to black.

Both the laptop and the PC are connected using a gigabit table switch that is connected to the main router. The same situation happened when I used the PC connected to the router and both the laptop and the phone connected over WiFi.

### Steps To Reproduce
1. Configure a PC as a steam play server (in this case, NixOS)
2. Install some games
3. Connect to the steam play PC
4. On phone it should work with at most some black flickering, on PC it should render the error in the first image.

### Expected behavior
Game starts streaming over the local network.

### Screenshots

![photo_2023-01-12_11-42-00](https://user-images.githubusercontent.com/15693688/212096441-b3ac1073-6333-4f17-b1fa-d62d28b170f2.jpg)

### Additional context
Both machines are running the latest stable branch

### Notify maintainers

@jagajaga @jonringer 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

PC: Ryzen 5600G 16GB RAM 1TB SSD
```console
lucasew@whiterun ~ 0$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.15, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/etc/flake/nixpkgs`
```

Laptop: Acer A3 5151SL i5 7200U 12GB RAM 1TB SSD
```console
lucasew@riverwood ~ 130$ nix-shell -p nix-info --run 'nix-info -m'
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.15, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/etc/flake/nixpkgs`
```

**Comment by lucasew** [comment]
I got a workaround to this problem.

Steam play works nice if you open Steam in Big Picture

Works awesomely well
![Captura de tela_2023-01-12_14-18-02](https://user-images.githubusercontent.com/15693688/212135705-ccf39913-cb5c-4ebd-9832-6cf3f32d2475.png)

**Comment by raspher** [comment]
@lucasew still relevant on latest nixos version?
