### ISSUE TITLE
Dolphin starts a new window everytime a new folder is opened + keeps old tabs

### ISSUE THREAD

**Issue by tobiasBora** [NixOS/nixpkgs#210335]
### Describe the bug

In my old system (1ffba9f2f68) when I opened a new dolphin instance, for instance using `dolphin /tmp` it would start a new tab in the already opened windows (which is great… even if it was not switching to it if the tab was already opened but it's another issue that seems to be fixed now). Since I upgraded my system to the latest unstable (aa1d74709f5dac623adb4d48fdfb27cc2c92a4d4), this actions not only opens a new window, but it also reopens all the tabs already opened in other dolphin instances, which can take quite some time when many tabs were open as it also restarts a shell in each folder and my shell takes a few seconds to start (the number of open tabs in the system after $n$ commands is $O(n^2)$…).

By tweaking configuration I can get rid of this behavior, but it would be better to automatically do it by default as the experience is pretty bad otherwise.

### Steps To Reproduce
Steps to reproduce the behavior: install kde plasma and dolphin, that should already be present in plasma5 (from aa1d74709f5dac623adb4d48fdfb27cc2c92a4d4)
```
  services.xserver.displayManager.sddm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;
```
and start 
```
$ dolphin /tmp
$ dolphin /home
```

Observe the new window and the tab that gets added to it.

To get a sane behavior again, you can go to the dolphin configuration:

![image](https://user-images.githubusercontent.com/2164118/212034441-0d042ce2-e817-4936-a01c-0a195bd51a91.png)

### Expected behavior
Ideally the two above options should be on by default… or at least one of them as having none of them gives a really strange experience as explained above. 

### Notify maintainers

@NixOS/qt-kde

**Comment by peterhoeg** [comment]
So the upstream defaults changed. We don't really have mechanisms in place to override that (and there's of course a whole different conversation about whether or not we should) - I suggest you take this up with upstream instead.

**Comment by Philipp91** [comment]
Dolphin user here, who has no idea what NixOS is. Just wanted to give kudos to this bug report('s author): It references the exact git commits, it has a problem analysis with O-notation, it has exact repro instructions, it explains a workaround (that I was able to use) and it politely asks for a change.

It's a little strange that Dolphin just changed its default behavior like that. But anyone who prefers the old behavior will easily find this bug through Google and can just flip that bit and move on with life.
