### ISSUE TITLE
ansible2: backport ansible 2.2 from master to release-16.09

### ISSUE THREAD

**Issue by mikefaille** [NixOS/nixpkgs#21036]
## Issue description
Actually, RedHat (owner of Ansible) mainly support Ansible 2.2 on RHEL7. Then, I think it's safe to upgrade Ansible 2.1.1.0->Ansible 2.2 on from master branch to release-16.09.

Thank you !

@copumpkin @jgeerds

**Comment by jgeerds** [comment]
@mikefaille done
