### ISSUE TITLE
dnscrypt: Spawn multiple instances to allow multiple resolvers

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#21035]
This is how upstream says to do it: https://github.com/jedisct1/dnscrypt-proxy/issues/128

Service description: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/dnscrypt-proxy.nix

cc'ing @joachifm

**Comment by joachifm** [comment]
Closing due to https://github.com/NixOS/nixpkgs/issues/33540
