### ISSUE TITLE
Plugin specification for postgres service

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#21042]
## Issue description

Currently, to add additional plugins to postgres you have to do this:
```
      services.postgresql = {
        enable = true;
        package = pkgs.postgresql95;
        extraPlugins = [ (pkgs.pg_repack.override { postgresql = pkgs.postgresql95; }) ];
      };
```

More user-friendly would be to make overriding implicit or reference to plugins as `with pkgs.postgresql95.plugins; [ pg_repack ]`.

## Technical details

* System: nixos-16.09

**Comment by FRidh** [comment]
I'm not familiar with postgresql. Are there many plugins? Maybe it is indeed worth having a package set of plugins per postgresql package, and add a withPlugins.

**Comment by danbst** [comment]
I know only of two packaged plugins - [postgis](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/libraries/postgis/default.nix) and pg_repack. Looking at https://github.com/dhamaniasad/awesome-postgres#extensions I think there could be more in future.

**Comment by FRidh** [comment]
In my opinion it is fine for then to manually override them, or, even better, use overridePackages on the whole pkgs to select another default postgresql version.

**Comment by danbst** [comment]
You see, the actual intent is like this:
```
      services.postgresql = {
        enable = true;
        package = pkgs.postgresql95;
        extraPlugins = [ (pkgs.pg_repack.override { postgresql = config.services.postgresql.package; }) ];
      };
```
so the actual override depends on NixOS option. I don't know if it makes sense to bind plugin with incompatible postgresql version, but my guess is it may be fatal.

**Comment by phile314-fh** [comment]
I just accidentally tested what happens when the postgis plugin is used with an incompatible postgres version; it does not work. My mistake was that I forgot the override:
<pre>
        extraPlugins = [ pkgs.postgis.v_1_2_3 ];
</pre>
instead of
<pre>
        extraPlugins = [ (pkgs.postgis.override {postgresql = ...}).v_1_2_3 ];
</pre>
I think with the current module it's too easy to make this mistake, there are no type errors, warnings or anything else.

**Comment by domenkozar** [comment]
This is going to be resolved with https://github.com/NixOS/nixpkgs/pull/38698

**Comment by danbst** [comment]
Yeah, closing as duplicate of https://github.com/NixOS/nixpkgs/issues/38616
