### ISSUE TITLE
containers: some tests always succeed

### ISSUE THREAD

**Issue by montag451** [NixOS/nixpkgs#21044]
Since c37e76b4d2ac59139df8956cc2b1ec6921bea11d `machinectl shell` is used to run commands inside containers instead of `nsenter + su`. However `machinectl shell` does not forward the return code of the command to the caller (see systemd/systemd#4215) so all the tests that use `nixos-container run` always succeed (e.g [container-physical_interfaces.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/containers-physical_interfaces.nix#L121)). So as long as systemd/systemd#4215 is not solved some tests may succeed when in fact they should have failed.

**Comment by montag451** [comment]
cc @kampfschlaefer

**Comment by kampfschlaefer** [comment]
So we need a test to check that the nixos-container tool works as expected?

Wouldn't it be kind of better to revert c37e76b until upstream fixes that?

**Comment by wlhlm** [comment]
I think switching to `systemd-run --wait` is the best option here. Also see https://github.com/systemd/systemd/issues/4215#issuecomment-269059851

**Comment by fpletz** [comment]
@wlhlm Thanks a lot for the hint! If nobody wants to take a shot at it I'll try to implement and test this in the next few days.

**Comment by wlhlm** [comment]
The pull request #18825 that first introduced this behavior has been [reverted](https://github.com/NixOS/nixpkgs/commit/cb49c1432417f9576ed12613f0374b3bc23587c2#diff-de8d44b6decd56e2faadb52ff18e2eba), so this issue shouldn't apply anymore and can be closed.

**Comment by montag451** [comment]
As suggested by @wlhlm, I will close this issue as it is not relevant anymore
