### ISSUE TITLE
drbd is packaged incorrectly

### ISSUE THREAD

**Issue by joachifm** [NixOS/nixpkgs#21051]
```shell
% ls $(nix-build -A drbd)
lib/  nix/  tmp/
```

**Comment by joachifm** [comment]
This also breaks the drbd service.

**Comment by vcunat** [comment]
The layout should be OK now; no idea about the service.

**Comment by joachifm** [comment]
I meant it breaks the service in the sense that it assumes the layout is sensible :) If the service is broken in other ways that can be dealt with later, I think.
