### ISSUE TITLE
Findex

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#210519]
**Project description**
Findex is a highly customizable application launcher written in Rust and uses Gtk3.

**Metadata**

* homepage URL: https://github.com/mdgaziur/findex
* source URL: https://github.com/mdgaziur/findex
* license: gpl3
* platforms: linux

**Comment by pinkcreeper100** [comment]
I am currently trying to package this myself

**Comment by figsoda** [comment]
packaged in #211336
