### ISSUE TITLE
No output defined for shell (bash/zsh/fish) completion files

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#21053]
## Issue description

I want to add several completion files for several packages, and don't know in which output should i place completion files. The best one seems `doc` output, or should i introduce new output for shell completion files?

@edolstra @vcunat @dezgeg

**Comment by offlinehacker** [comment]
I would introduce `completion` output that would have autocompletions. We also have man output, so this does seem similar the way how we currently do things.

**Comment by dezgeg** [comment]
So far we've put it in `bin`. I don't think there's much need to have a separate output for that since the completion files are quite small, I think.

**Comment by offlinehacker** [comment]
Cool, so let's have `bin` output if it's used by derivation, `out` otherwise. I will open a new issue for documenting this.

**Comment by vcunat** [comment]
I recommend `${!outputBin}`.
