### ISSUE TITLE
nautilus lacks (runtime) dependency on sgdisk

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#21054]
## Issue description
If you right click on a device in nautilus and select "Format", fill inn the following form and press "go" (or whatever it's called), you'll be presented with an error message indicating that sgdisk is missing and the operation fails.

![image](https://cloud.githubusercontent.com/assets/133602/21076583/80e465d6-bf2f-11e6-84d3-b003441559dd.png)

As this the format operation clearly is a built-in functionality of nautilus, we should ensure that it works out of the box.

EDIT: added screenshot.

## Technical details

* System: NixOS 16.09

**Comment by Profpatsch** [comment]
(triage) can you still reproduce?

**Comment by bjornfor** [comment]
The feature seems to work on NixOS 18.03.
