### ISSUE TITLE
google_apputils disabled for py3k -- why?

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#21061]
a959cc91c disables google apputils for python 3. I can't tell why, and based on a cursory check it seems to work fine on python 3 as well. @wkennington ?

**Comment by wkennington** [comment]
idk, maybe it was broken with older versions of python3?

**Comment by Mic92** [comment]
fixed in https://github.com/NixOS/nixpkgs/commit/d568cb971be3c1a9f732e2d254baf74dff84fa2a
