### ISSUE TITLE
cjdns doesn't put hostname into /etc/hosts anymore

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#21067]
## Issue description

on 16.09, i get the cjdns hostnames in /etc/hosts

on unstable, this is no longer the case

### Steps to reproduce

1) install cjdns on 16.09 and unstable

2) compare /etc/hosts

## Technical details

* System: NixOS: 17.03pre96925.1c50bdd (Gorilla)
* Nix version: nix-env (Nix) 1.11.4

**Comment by joachifm** [comment]
See 60ded3f3632d221ca3f82a52392e155517880456

**Comment by tohl** [comment]
@joachifm ok, thanks! although it is a shame i have to do it manually now
