### ISSUE TITLE
In krita, shift stays pressed when using the brush resize shortcut 

### ISSUE THREAD

**Issue by koalp** [NixOS/nixpkgs#210691]
### Describe the bug

When using the shift+click input in krita to resize the brush size, it acts like shift is is stuck : clicking and dragging the cursor after that makes the brush change size instead of drawing and middle-click also behave like shift is pressed (it rotates instead of dragging the canvas).

It isn’t my keyboard and the issue stops if I put my cursor out of the windows and come back.
This issue doesn’t occur with the krita appimage 
This issue does't occur with  krita 5.0.2 from nixpkgs 22.05.

### Steps To Reproduce
1. Open krita (krita 5.1.3 in nixpkgs 22.11 or 5.1.4 in unstable)
2. Press shift, then left-click and drag the cursor to change the brush size
3. Stop pressing shift and stop clicking
4. Click again to draw, it changes the brush size instead of drawing  

### Expected behavior

That it doesn’t act like the shift key is stuck.

### Additional context

I’m using x11 (i3wm)
I made [a post on krita-artists forum](https://krita-artists.org/t/shift-stays-pressed-when-using-the-brush-resize-shortcut/55384/1)) where I found out that the appimage (5.1.1 and 5.1.5, couldn’t find 5.1.3 =/ ) didn’t have this behaviour.

### Notify maintainers
@abbradar @sifmelcara @nek0 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon), 22.11.1442.2dea8991d89`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.11, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by sifmelcara** [comment]
I cannot reproduce this with 5.1.4 krita in unstable channel. I tried both xmonad and i3. Since in the forum post you mentioned that only shift key has problem, maybe it conflicts with your i3 key binding? Can you try deleting your i3 config or try out plasma desktop to see if you can still reproduce the issue?

**Comment by koalp** [comment]
Thank you for your help !
Deleting my i3 config didn’t work but using a nixos with only i3 or plasma and krita installed makes the issue disapear.
When I have time, I will try to gradually add other nixos options and user config to find what is wrong.
What I find strange is that the appimage works (will also try with 5.1.5 once it’s in unstable)

I think I will close the issue while I can’t find a minimal nixos configuration that reproduces the issue.
