### ISSUE TITLE
Package request: Watir

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nixpkgs#21073]
http://watir.github.io/

An open source Ruby library for automating tests. Watir interacts with a browser the same way people do: clicking links, filling out forms and validating text.

**Comment by moretea** [comment]
It appears that Watir is also published as a ruby gem and is supposed to be used as a DSL. Are you familiar with the ruby ecosystem?

You could package it yourself locally with the following few steps.
1. Create a `Gemfile` containing
```
source "https://rubygems.org"
gem "watir"
```
2. Resolve all ruby dependencies with bundler. This generates a `Gemfile.lock` file
```
`nix-build '<nixpkgs>' -A bundler`/bin/bundler lock
```
3. Run bundix to create a `gemset.nix` file from `Gemfile.lock`
```
`nix-build '<nixpkgs>' -A bundix`/bin/bundix
```
4. Use it in a nix expression (skeleton provided below)
```
with import <nixpkgs> {};
{
  env = bundlerEnv {
    name = "watir-env";
    gemfile = ./Gemfile;
    lockfile = ./Gemfile.lock;
    gemset = ./gemset.nix;
  };
}
```

For a walkthrough see e.g. http://blog.arkency.com/2016/04/packaging-ruby-programs-in-nixos/

**Comment by moretea** [comment]
@0xABAB if you need some help to get this done, I'd be willing to go throuh this together.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR.
