### ISSUE TITLE
nixos/wordpress: DB_PASSWORD not always set

### ISSUE THREAD

**Issue by urandom2** [NixOS/nixpkgs#210893]
### Describe the bug

Some wordpress applications, [civicrm](https://civicrm.com/), assume this variable is present, even if they do not use it. I am unclear if this is undefined behaviour or a convention, but I have had to set `define( 'DB_PASSWORD', null );` to get wordpress to not crash after activating the plugin. Could we use `null` or `""` as the fallback, instead of leaving it undefined?

### Steps To Reproduce

```nix
{pkgs, ...}: {
  services.wordpress.sites.localhost = {
    extraConfig = ''
      define( 'DB_PASSWORD', null );
    '';
    plugins = [pkgs.wordpressPackages.plugins.civicrm];
  };
}
```

### Notify maintainers

@onny 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 23.05 (Stoat), 23.05.20230110.c07552f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `""`
 - channels(Colin Arnott): `"nixos-22.05-22.05"`
 - channels(colin): `""`
 - nixpkgs: `/nix/store/d81qdgaz0v760w7bdai42hb84p0dzzlr-source`
```

**Comment by onny** [comment]
We should check what the Wordpress installer does in this case and if `define( 'DB_PASSWORD', null );` is usually written into `wp-config.php`

**Comment by urandom2** [comment]
I have not manually tested it, but as best as I can grok, they set whatever the user provides, so `define( 'DB_PASSWORD', "" );` seems more canonical?

**Comment by onny** [comment]
Tested in a VM and you're right, setting DB_PASSWORD to '' seems to be the default case

![image](https://user-images.githubusercontent.com/757752/212552309-4e122027-a64a-4cb5-bb77-a537d2e2a48e.png)

We should fix that and add a comment in the Wordpress module that this is the default behavior.
Thanks for pointing that issue out!

**Comment by onny** [comment]
Trying to fix this in this PR https://github.com/NixOS/nixpkgs/pull/210701
