### ISSUE TITLE
Unable to build subversion-1.9.4

### ISSUE THREAD

**Issue by cloudhan** [NixOS/nixpkgs#21091]
## Issue description
subversion-1.9.4 has been moved into http://archive.apache.org/dist/subversion/ after subversion-1.9.5 is released, the mirror path should be updated.

### Steps to reproduce
``` bash
nix-env -i subversion
```

**Comment by cloudhan** [comment]
actually, it stuck on mirror http://apache.cict.fr/ for quite a long time, I think http://archive.apache.org/dist/ should be on the first of mirror list, because it also include newer releases.

**Comment by jgeerds** [comment]
Since we're not using a specific mirror it might be hard to change the order:
`url = "mirror://apache/subversion/${name}.tar.bz2";`

Would your issue be solved if we backport `1.9.5` to 16.09?

**Comment by cloudhan** [comment]
forgot to mention I do not just NixOS cause I am not the admin of the server. And nix is install in my home dir to walkaround requiring `sudo` to install pkgs.
I just use `NIX_MIRRORS_apache nix-env -i blah_blah` to temporarily walk around this issue, but I think you need to fix this just by reordering the mirror list in https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/mirrors.nix

**Comment by vcunat** [comment]
I wish they had a generic URL that would choose an appropriate mirror automatically (a "close" one).

**Comment by pSub** [comment]
Closing as subversion-1.9.4 is no longer present in supported versions of nixpkgs.
