### ISSUE TITLE
Scilab unable to load shared library libtinfo.so.5

### ISSUE THREAD

**Issue by mskf1383** [NixOS/nixpkgs#210916]
### Describe the bug
When I run Scilab it shows this error and does not run:
```console
scilab-bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
This fixed when I installed `libtinfo5` from APT.

### Steps To Reproduce
1. Install `scilab-bin`
2. Run `scilab`

### Expected behavior
Run.

### Additional context
`libtinfo` is not in nix repository.

### Notify maintainers

@wegank

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-1-amd64, Debian GNU/Linux, noversion, nobuild`
```

**Comment by wegank** [comment]
Oh, I actually only maintain the macOS part. Is the Linux part of the package unmaintained?

**Comment by mskf1383** [comment]
I don't know. No one is in maintaners list in https://search.nixos.org. I mention other contributors from [history](https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/applications/science/math/scilab-bin/default.nix).
@risicle @Stunkymonkey @jonringer

**Comment by jonringer** [comment]
The linux version is very out of date.
