### ISSUE TITLE
devhelp fails to start

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#21094]
## Issue description
```
% devhelp

(devhelp:24237): GLib-GIO-ERROR **: Settings schema 'org.gnome.desktop.interface' is not installed

zsh: trace trap  devhelp
```

### Steps to reproduce
Install (in this case, using nix-env) and try running devhelp. I suspect that it will work correctly in a GNOME environment, but it doesn't in my i3.

## Technical details

* System: 16.09.1229.f52eaf4
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1229.f52eaf4"

**Comment by lheckemann** [comment]
Wow, thanks for the rapid fix @vcunat !

**Comment by vcunat** [comment]
:-) We've had loads of gschemas errors, and probably have lots of them still.  I think they typically wouldn't manifest if running from within the gnome desktop.
