### ISSUE TITLE
Builder helm from source

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#21106]
## Issue description

Currently helm is downloaded as static binary, but could be built from source. While this is not a party breaker, we tend to have packages built from source. If someone will have time and will to learn how to package go packages, it's a good example to package. In general using `buildGoPackage` could do the trick, but not always. `go2nix` could also be usefull sometimes.

**Comment by offlinehacker** [comment]
@rlupton20 can't assign you, but here's the issue :)

**Comment by rlupton20** [comment]
Thanks. I'll try to take a look at this.

**Comment by Profpatsch** [comment]
(triage) has this been fixed?

**Comment by edude03** [comment]
@Profpatsch I'm working on this at the moment, it hasn't been fixed

**Comment by edude03** [comment]
Done and merged into master :D
