### ISSUE TITLE
error: cannot download flash_player_ppapi_linux.x86_64.tar.gz from any mirror

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#21119]
git version: current master.

```
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download flash_player_ppapi_linux.x86_64.tar.gz from any mirror
```

**Comment by m0rphism** [comment]
I get the same error with the current `nixos-unstable` channel. Prevents my `chromium` from building.

**Comment by alexeymuranov** [comment]
@joachifm, this error is back.  I suppose this is related to a recent update of Adobe Flash [with security fixes](https://helpx.adobe.com/security/products/flash-player/apsb17-15.html).

**Comment by tpanum** [comment]
... and it's back again :cry:

**Comment by numkem** [comment]
What can we do? I can't seem to update my system without it.
