### ISSUE TITLE
MPD fails to start

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#211103]
### Describe the bug

The MPD service fails to start, it fails to set up its state and run directories in `/var/lib/mpd` and `/run/mpd`

### Steps To Reproduce
`services.mpd.enable = true`

```
# journalctl -u mpd
systemd[1]: Starting Music Player Daemon...
systemd[1815]: mpd.service: Failed to set up special execution directory in /var/lib: Not a directory
systemd[1815]: mpd.service: Failed at step STATE_DIRECTORY spawning /nix/store/hc13x29j9ilb5j03xwfj7h41v3lic7c1-unit-script-mpd-pre-start/bin/mpd-pre-start: Not a directory
systemd[1]: mpd.service: Control process exited, code=exited, status=238/STATE_DIRECTORY
systemd[1]: mpd.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Music Player Daemon.
```

```
# cat /nix/store/hc13x29j9ilb5j03xwfj7h41v3lic7c1-unit-script-mpd-pre-start/bin/mpd-pre-start
#!/nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin/bash
set -e
set -euo pipefail
install -m 600 /nix/store/iddi5bdjql4lsxhr99g0c6wa0pbldf95-mpd.conf /run/mpd/mpd.conf
```

### Expected behavior

MPD starts

### Additional context

This has been broken for a long time perhaps since the last change to the directory provisioning mechanism in commit 77a849690798ae0c1acd6f5a8e8b6106ae9d11c9

### Notify maintainers

@aanderse @rnhmjoj 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3-zen1, NixOS, 23.05 (Stoat), 23.05pre441223.35f1f865c03`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos-22.11, nixos-unstable, nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by rnhmjoj** [comment]
I can't reproduce it, there must be something else in your configuration. You can check [here](https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.mpd.x86_64-linux) that the test (using the default configuration) is passing. An even simpler test is also passing:
```nix
import ./make-test-python.nix ({ pkgs, lib, ... }:
{
  name = "mpd";
  nodes.server = { ... }: { services.mpd.enable = true; };

  testScript = ''
    start_all()
    server.wait_for_unit("mpd.service")
  '';
})
```

**Comment by tg-x** [comment]
there's nothing else related to mpd in my config, what else could influence this?

**Comment by rnhmjoj** [comment]
> mpd.service: Failed to set up special execution directory in /var/lib: Not a directory

This line is coming directly from systemd, not the start script: it's failing to set the state directory (/var/lib/mpv) up. So, the problem could has something to do with the file system or systemd.
I would check that /var/lib is mounted (if it's a mount point), the permissions are ok, the file system is not corrupted...

**Comment by tg-x** [comment]
so the problem was that `/var/lib/mpd/music/` and `playlists/` were a symlink, which at some point became unsupported.
setting `musicDirectory` and `playlistDirectory` fixed it
