### ISSUE TITLE
Discord update check is not getting disabled on fresh installs

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nixpkgs#211197]
### Describe the bug

The `discord` update-check disabler is not able to work if there is no pre-existing config, making it break when someone installs an "old" version. This can happen when discord updates their version, but the update has not yet been merged or fully propagated through the channels.

### Steps To Reproduce
1. Delete the `~/.config/discord/settings.json`
2. `nix run nixpkgs/22.11#discord` (This will always use a version that is outdated by the time of writing steps)
3. See the update dialog

### Expected behavior

A config should be created that is empty besides `"SKIP_HOST_UPDATE": true` **OR** a stronger error/warning should be printed that explains how to mitigate. The current oneliner gets lost in the discord "boot" message noise.

### Additional Context

It seems as if a preceeding `echo '{}' > ~/.config/discord/settings.json` is a sufficient workaround after having identified the problem in the first place (which was the quite longer part)

### Notify maintainers

* @MP2E
* @devins2518
* @Artturin
* @Infinidoge

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0, NixOS, 23.05 (Stoat), 23.05.20230111.6c8644f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.0pre20230112_eaa20f2`
 - channels(aroemer): `"nixpkgs-21.11"`
 - channels(nmelzer): `""`
 - channels(root): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by tejing1** [comment]
Discussion on discord revealed that when the user has a read-only `settings.json` (such as when it's installed through home-manager), the wrapper prints some spurious errors. This should probably be fixed at the same time.

**Comment by NobbZ** [comment]
I think you misunderstood the discussion there. The wrapper has a simple catch all with a generic oneline error.

Discord though likes to fail when it can't write the config. Or in case of a symlink, likes to simply replace the link with a regular file.

**Comment by deftdawg** [comment]
@NobbZ Thanks for the `echo {}` workaround, I tried to open discord today for the first time on a new install and it was just telling me I need to upgrade to discord-0.0.25 (0.0.24 is what is packaged) and would offer to let me download a deb or a tarball and then just close.

Doing the echo to make an empty config allowed discord to start and for me to get logged in.

Hopefully this gets addressed so folks don't have to find this issue in order to get going with a fresh install.

**Comment by l1n** [comment]
Heads up that this should actually go to `~/Library/Application Support/discord/settings.json` on MacOS - happy to make a PR if someone points me in the right direction
