### ISSUE TITLE
docker run --add-host=NAME:host-gateway does not work

### ISSUE THREAD

**Issue by yrashk** [NixOS/nixpkgs#211124]
### Describe the bug

When trying to use the `add-host` feature from Docker, I get an `nil` entry in `/etc/hosts` inside of the container

### Steps To Reproduce

1. `docker run -ti --add-host=test:host-gateway ubuntu:latest`
2. `cat /etc/hosts`
3. It will contain

```
<nil>    test
```

### Expected behavior

`/etc/hosts` should contain a mapping between host's IP and `test`

### Notify maintainers

@offline @tailhook @vdemeester @periklis @mikroskeem @maxeaubrey 

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.86, NixOS, 22.11 (Raccoon), 22.11.1421.e9ade2c8240`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11.1421.e9ade2c8240"`
 - channels(yrashk): `"nixos-unstable-23.05pre439706.9813adc7f7c, release-22.11.tar.gz-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by mikroskeem** [comment]
This sounds like upstream bug?

**Comment by yrashk** [comment]
I have it working on Ubuntu, macOS, etc. That's what I thought it may be something NixOS specific, but I can't put my finger on it just yet.

**Comment by NateWright** [comment]
I am also having this issue.

**Comment by mikroskeem** [comment]
Does this issue still appear?

Built a system using `nixos-22.11` channel (7dc71aef32e8faf065cb171700792cf8a65c152d), Docker version `20.10.21`, and I couldn't reproduce this:

```
[root@docker-playground:~]# docker run --rm -ti --add-host=test:host-gateway ubuntu:latest
root@f5913104e560:/# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.1	test
172.17.0.2	f5913104e560
```

**Comment by NateWright** [comment]
I am running the same versions and do see test mapped in. I can ping test but I cannot curl a website running on the host.

**Comment by mikroskeem** [comment]
Do you have firewall enabled but Docker interface not added into [`networking.firewall.trustedInterfaces`](https://search.nixos.org/options?channel=22.11&show=networking.firewall.trustedInterfaces&from=0&size=50&sort=relevance&type=packages&query=trustedInter)?

**Comment by NateWright** [comment]
That does fix the issue. Thank you

**Comment by mikroskeem** [comment]
I suppose that this problem has disappeared and issue can now be closed.

**Comment by Naim-Bijapure** [comment]
I have faced this issue. 
this is a firewall-related issue. if anyone facing this issue you can disable the firewall. 
networking.firewall.enable = false; ( not a good practice :) )

**Comment by musjj** [comment]
> Do you have firewall enabled but Docker interface not added into [networking.firewall.trustedInterfaces](https://search.nixos.org/options?channel=22.11&show=networking.firewall.trustedInterfaces&from=0&size=50&sort=relevance&type=packages&query=trustedInter)

Are there any resources for a way to do this? Some assistance would be appreciated.

**Comment by mikroskeem** [comment]
Docker usually creates `docker0` (and other bridge interfaces with `docker network create`). Check your network interfaces using `ip link`

**Comment by musjj** [comment]
Strangely, `ip link` does not list `docker0`. This is my docker config:

```nix
virtualisation.docker.rootless = {
  enable = true;
  package = pkgs.docker_26;
  setSocketVariable = true;
};
```

Do I need to set any additional options?
