### ISSUE TITLE
ruby_2_7 will go EOL 2023-03-31, change default to ruby_3_0 or ruby_3_1

### ISSUE THREAD

**Issue by ajs124** [NixOS/nixpkgs#211134]
### Describe the bug
So we'll have an EOL `ruby` for a few months on 22.11, which isn't ideal, but we really shouldn't go into 23.05 like that.

Also, `ruby_2_7` does not support `openssl_3`, which is why I noticed this when looking into stuff for #210452

### Notify maintainers
@vrthra @manveru @marsam

**Comment by RaitoBezarius** [comment]
Ruby 2.7 support status ended yesterday.

**Comment by ajs124** [comment]
The default is `ruby_3_1` with the merge of #224018 :partying_face:
Thanks for taking care of this @marsam!

Now… do we want to mark `ruby_2_7` as EOL e.g. through `knownVulnerabilities`?
