### ISSUE TITLE
(Not sure how to reproduce) On one of my accounts, Firefox doesn't appear in the Gnome application list

### ISSUE THREAD

**Issue by falsifian** [NixOS/nixpkgs#21113]
## Issue description

In Gnome, if I click "show applications" on the dock, firefox isn't in the list of applications, and if I press the super (windows) key and search for "firefox", the only option is "Search the web for firefox".

Why I expect firefox should be there:
* I'm using release-16.09, and have `firefox` in `environment.systemPackages`.
* `firefox.desktop` seems to be in the right place. This is from a terminal in my Gnome session:
```
$ echo $XDG_DATA_DIRS
/home/falsifian/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
$ cat /run/current-system/sw/share/applications/firefox.desktop 
[Desktop Entry]
Type=Application
Exec=firefox %U
Icon=firefox
Comment=
Terminal=false
Name=Firefox
GenericName=Web Browser
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp
Categories=Application;Network;WebBrowser;

```

Closest existing issue I could find is #19934.

### Steps to reproduce

I'm not sure how to reproduce this. When I add a new user to my system, that user sees firefox in the Gnome application list.

(Old steps to reproduce:)
* In `configuration.nix`, add firefox to `environment.systemPackages` and set `desktop.gnome3.enable = true`.
* Log in
* Press the super/windows key and type "firefox" in the search box; observe only "Search the web for firefox" and no actual Firefox application.
* In the dock, press "show applications" and see no firefox listed.

## Technical details

* System: `16.09.1229.f52eaf4 (Flounder)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `"16.09.1229.f52eaf4"`

**Comment by falsifian** [comment]
I tried running `nix-env -i firefox` and logging out and in again. Firefox still doesn't appear, even though now a file exists at `~/.nix-profile/share/applications/firefox.desktop`.

**Comment by vcunat** [comment]
But on NixOS `$XDG_DATA_DIRS` should be setup correctly by default: `$HOME/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share`

**Comment by falsifian** [comment]
Indeed, my `XDG_DATA_DIRS`
is `/home/falsifian/.nix-profile/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share`.

But this only happens on one of my accounts; when I create a new account Firefox appears in the Gnome menu. So somehow I've gotten myself into a strange state.
