### ISSUE TITLE
Packaging Request: terminal-stocks

### ISSUE THREAD

**Issue by andriy-git** [NixOS/nixpkgs#211183]
**Project description**
Fetch stock information, market summary right in your terminal.

**Metadata**

* homepage URL: https://shashi.dev/terminal-stocks/#/
* source URL: https://github.com/shweshi/terminal-stocks
* license: mit
* linux

**Comment by mislavzanic** [comment]
PR made: [#211349](https://github.com/NixOS/nixpkgs/pull/211349).
