### ISSUE TITLE
[Package request ] s4cmd

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#21115]
Package request for s4cmd: https://github.com/bloomreach/s4cmd

**Comment by Mic92** [comment]
looks like it would be a simple package using `buildPythonApplication`, 
as `buildInputs`:  boto3 and pytz from pythonPackage has to be passed.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out (as shown here by @Mic92), and especially when discussing a PR.
