### ISSUE TITLE
package request for texlive package: expl3

### ISSUE THREAD

**Issue by Mikilio** [NixOS/nixpkgs#211145]
**Project description**
Wrapper package for experimental LATEX3

**Metadata**

* homepage URL: https://ctan.org/pkg/expl3
* source URL: https://github.com/latex3/latex3
* license: LPPL Version 1.3c 2008-05-04
* platforms: Unix, Linux, darwin, ...

This means basically updating the mirror and the year which I don't understand how to do myself.

**Comment by veprbl** [comment]
Is this just `texlive.l3kernel`?

**Comment by Mikilio** [comment]
Maybe it was. It was missing when I tried compiling my LaTeX doc. 
I already solved the issue for me by manually upgrading the mirror on my fork. I've noticed that nixpkgs uses a mirror at the end of every year to pull texlive packages. So my request would be to update the mirror being used since 2022 has ended. If it hasn't been done already while I wasn't looking ofc.

​

**Comment by veprbl** [comment]
We are currently using a month-old snapshot:
https://github.com/NixOS/nixpkgs/blob/22a908687751c8423213f94c1c5b09244b30bbf9/pkgs/tools/typesetting/tex/texlive/default.nix#L120-L124

The next planned update to target nixos 23.05 is to switch to texlive 2022-final once that is frozen sometime in March. You are welcome to do an update in between, feel free to submit a PR.
