### ISSUE TITLE
vagrant fails to build on NixOS x86_64

### ISSUE THREAD

**Issue by aij** [NixOS/nixpkgs#211153]
### Steps To Reproduce
1. build *vagrant*

### Build log
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/6vgym9mwsq0dy9l370rqwjn9a4xv6xpk-v2.2.19.tar.gz
source root is vagrant-2.2.19
setting SOURCE_DATE_EPOCH to timestamp 1636146944 of file vagrant-2.2.19/website/vercel.json
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/fwad3q8absnzn5f69vdlm6qxsqjnxsa1-unofficial-installation-nowarn.patch
patching file bin/vagrant
Hunk #1 succeeded at 204 (offset 49 lines).
applying patch /nix/store/8j72vpds1r418jisgcv0gbgn1q2acm6x-use-system-bundler-version.patch
patching file lib/vagrant/bundler.rb
Hunk #1 succeeded at 484 (offset 14 lines).
applying patch /nix/store/l8daz6dfgaw0yirvj5hk46fh3104f7d3-0004-Support-system-installed-plugins.patch
patching file lib/vagrant/plugin/manager.rb
patching file lib/vagrant/plugin/state_file.rb
applying patch /nix/store/92hnx2irdvxwjilfh6z3lch1plzi75vg-0001-Revert-Merge-pull-request-12225-from-chrisroberts-re.patch
patching file bin/vagrant
patching file lib/vagrant.rb
patching file lib/vagrant/bundler.rb
patching file lib/vagrant/errors.rb
Hunk #1 succeeded at 644 (offset 8 lines).
patching file lib/vagrant/plugin/manager.rb
patching file templates/locales/en.yml
Hunk #2 succeeded at 1251 (offset 13 lines).
Hunk #3 succeeded at 3026 (offset 28 lines).
patching file test/unit/bin/vagrant_test.rb
patching file test/unit/vagrant/bundler_test.rb
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
@nix { "action": "setPhase", "phase": "installPhase" }
installing
buildFlags: 
failure: $gempkg path unspecified

```

### Additional context

Error encountered when upgrading to the latest nixos-unstable-small c85d08692966cf022b0a741a794cb1650602d8af.

It looks like it broke with the last staging-next merge, but I have no idea which of the changes is relevant. https://github.com/NixOS/nixpkgs/pull/209180

### Notify maintainers

@Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.17, NixOS, 23.05 (Stoat), 23.05.git.befc83905c96`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos-21.11pre329341.9e70e9f732f"`
 - nixpkgs: `/etc/nixos/aij/unstable`

```

**Comment by jerith666** [comment]
There's a similar error from `bundix`.

**Comment by SuperSandro2000** [comment]
Is this fixed by the linked PR?

**Comment by etu** [comment]
I just tried to build it on current master, it doesn't build on current master (1d72880e164a6c2ddbabe354e8dc2c9105df08db).

**Comment by CorbanR** [comment]
I am also experiencing the same issue on current master

`nix-shell -p nix-info --run "nix-info -m"`

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.6.0, macOS 12.6.2`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/qvkzwk5awk8np49w7yd8alisl316l2dr-source`
```

**Comment by jerith666** [comment]
Note that the linked PR merged to `staging`, not `master`.

**Comment by aij** [comment]
I can't say I understand the fix, but I cherry-picked 68f1182b659a8ea57c78d8e94d74f803065cac24 onto `nixos-unstable-small` and was able to build both `vagrant` and `bundix` after working around a seemingly unrelated `libuv` failure. https://github.com/NixOS/nixpkgs/compare/master...aij:nixpkgs:issue-211153-testing

It did take quite a while though, so I'll wait until it hits nixos-unstable-small before doing a full system build. I'm guessing CAS could have helped reduce the number of rebuild required quite a bit, since I don't expect the change would affect most packages.

FWIW, here are errors I get from building `libuv` (even without this patch). 

```
not ok 261 - tcp_bind6_error_addrinuse
# exit code 134
# Output from process `tcp_bind6_error_addrinuse`:
# Assertion failed in test/test-tcp-bind6-error.c on line 60: r == UV_EADDRINUSE
ok 262 - tcp_bind6_error_addrnotavail
ok 263 - tcp_bind6_error_fault
ok 264 - tcp_bind6_error_inval
ok 265 - tcp_bind6_localhost_ok
not ok 266 - tcp_bind_error_addrinuse_connect
# exit code 134
# Output from process `tcp_bind_error_addrinuse_connect`: (no output)
Output from process `tcp_bind_error_addrinuse_connect`:
# Assertion failed in test/test-tcp-bind-error.c on line 67: UV_EADDRINUSE == uv_tcp_getsockname(&conn, (struct sockaddr*) &addr, &addrlen)
not ok 267 - tcp_bind_error_addrinuse_listen
# exit code 134
# Output from process `tcp_bind_error_addrinuse_listen`:
# Assertion failed in test/test-tcp-bind-error.c on line 99: r == UV_EADDRINUSE
```

I'm sure it must be something specific to my setup / machine state since it obviously did build in Hydra, and on a different machine `nix-build . -A libuv --check` works too.

**Comment by vcunat** [comment]
That's this kernel bug, I suspect: https://utcc.utoronto.ca/~cks/space/blog/linux/KernelBindBugIn6016

**Comment by aij** [comment]
@vcunat Wow, that would explain it. I thought it could somehow be related to the kernel version, but I wasn't expecting an actual kernel bug. The machine where it failed is running Linux 6.0.17 while it worked on 5.15.86.

**Comment by etu** [comment]
Well, this is interesting, I just checked out 1b1f50645af that just passed all the tests and could become the next unstable: https://hydra.nixos.org/build/206740134

And... I've been tracking https://nixpk.gs/pr-tracker.html?pr=211323 which isn't on master yet...

However, I just managed to build vagrant on this commit. I didn't even build it. I got it cached from the cache so it's been built by hydra.

```
copying path '/nix/store/agd24wrbpbrkk5dnwdibzay5cfsxm4dj-vagrant-2.2.19' from 'https://cache.nixos.org'...
/nix/store/agd24wrbpbrkk5dnwdibzay5cfsxm4dj-vagrant-2.2.19
```

So I guess this could be considered fixed? I'm not sure *what* fixed it though.

**Comment by aij** [comment]
Looks like @yu-re-ka's PR https://github.com/NixOS/nixpkgs/pull/211899 to fix https://github.com/NixOS/nixpkgs/issues/211671 would have done it.

So, I think we can close this before the original fix in staging hits master. Thanks everyone! :tada:
