### ISSUE TITLE
Python: improve determinism

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#21123]
## Issue description

- Python 3 interpreters are not build deterministic (http://hydra.nixos.org/build/44710243#tabs-buildsteps)
- Python packages are not build determinic (should be addressed by 2bcd41b9ffc629c7c9df402b7a39700340fdf52e)

Related issue: https://github.com/NixOS/nixpkgs/pull/2281

**Comment by FRidh** [comment]
We might do some shopping at Debian
- 2.7: https://sources.debian.net/src/python2.7/2.7.12-7/debian/patches/
- 3.4: https://sources.debian.net/src/python3.4/3.4.2-1/debian/patches/
- 3.5: https://sources.debian.net/src/python3.5/3.5.2-8/debian/patches/
- 3.6: https://sources.debian.net/src/python3.6/3.6.0~rc1-1/debian/patches/

**Comment by globin** [comment]
Hasn't this been fixed?

**Comment by FRidh** [comment]
yep, it has! At least, for most interpreters.

**Comment by FRidh** [comment]
There's a PR to incorporate in CPython some of the modifications I made to our CPython.
https://github.com/python/cpython/pull/296
