### ISSUE TITLE
`python*Packages.jedi-language-server` is missing `lsprotocol`

### ISSUE THREAD

**Issue by RTUnreal** [NixOS/nixpkgs#211215]
### Steps To Reproduce
1. build `python*Packages.jedi-language-server`

### Build log
https://gist.github.com/RTUnreal/113368ce35c7e11aa4f4e907e029feb6

### Additional context
I was trying to use this ls in vscodium with the ms-python.python extension and it failed to build

### Notify maintainers
@doronbehar 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.86, NixOS, 22.11 (Raccoon), 22.11.1629.2f9fd351ec3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixosUnstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by NotAShelf** [comment]
Can confirm this.
```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 23.05 (Stoat), 23.05.20230113.befc839`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(notashelf): `"home-manager"`
 - nixpkgs: `/nix/store/ci0324339l5i3x7q68vigpfcf1jicsgs-source`
 - ```

**Comment by mfenniak** [comment]
Encountered the same build failure here, while updating nixpkgs from:
```
• Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/befc83905c965adfd33e5cae49acb0351f6e0404' (2023-01-13)
  → 'github:NixOS/nixpkgs/6dccdc458512abce8d19f74195bb20fdb067df50' (2023-01-15)
```

(Diff: https://github.com/nixos/nixpkgs/compare/befc83905c965adfd33e5cae...6dccdc458512abce8d19f74195bb20fdb067)

I would estimate that the cause is commit 246b3cd378de888c5acbed50deb690cfd44699fc, introduced by #208232, as it's a direct upgrade to the package impacted by this failure.

**Comment by austinbutler** [comment]
There's a draft PR that introduces `lsprotocol`: https://github.com/NixOS/nixpkgs/pull/204457.

**Comment by samsky72** [comment]
Same issue when YouCompleteMe plugin enabled for vim/neovim
