### ISSUE TITLE
patchShebangs doesn't select correct /bin/sh for cross builds

### ISSUE THREAD

**Issue by elitak** [NixOS/nixpkgs#21138]
## Issue description

`pkgs/build-support/setup-hooks/patch-shebangs.sh` uses `command -v` to determine the substitute for the shebang path. This selects the wrong path during cross-builds and results in x86_64 binaries getting pulled in as dependencies to cross-built binaries that can't possibly use them at runtime.

I don't know if we can reliably pick the correct /bin/sh without it being in the PATH envvar. I presume patchShebangs works fine for binaries that don't overlap with stdenv's and are included in buildInputs.

### Steps to reproduce

If you cross-build some packages to ARM platforms, patchShebangs runs in the fixup phase and run `head -n1 /nix/store/*-glibc-2.24-arm*-bin/bin/sotruss`, you'll see it points to the native /bin/sh rather than the cross one. I was considering a PR to just add `dontPatchShebangs=true;` to the cross build of glibc, but figured it'd be better if the root issue were fixed instead.

## Technical details
* System: "16.03pre75806.77f8f35"
* Nix version: nix-env (Nix) 1.12pre1234_abcdef
* Nixpkgs version: 17.03.git.01febe0 (Gorilla)

**Comment by bjornfor** [comment]
/participate. (I've stumbled across this too.)

**Comment by elitak** [comment]
Is it safe to assume `/bin/{ba,a}sh` are the only paths that will ever realistically have this problem? If so, how and where would we pull in `bash.crossDrv` as a buildInput without it clobbering the native /bin/sh used by stdenv to run the builder? Once we're already executing `patchShebangs`, it's too late to find any `.crossDrv`s.

This problem overlaps with another, #21191, which is that crossDrvs clobber stdenv's binaries in the PATH.

The best solution I can come up with is to manually include `bash` in `buildInputs` of e.g. glibc, add logic in pks/stdenv/generic/setup.sh to not add `${bash.crossDrv}/bin` to the PATH when crossbuilding, based on some new derivation attr like `excludeBuildInputsFromPath = [ bash ];`, then search `$crossPkgs/bin` during `patchShebangs`, independently of what's set in the PATH.

Or we could just make setup.sh smarter about importing /bin/ PATHs that contain elements of the stdenv, namely: `coreutils bash busybox`.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/issues/1080 is essential to fix this without greatly complicating bootstrapping.

**Comment by Ericson2314** [comment]
@matthewbauer don't forget to close.

**Comment by matthewbauer** [comment]
Addressed in https://github.com/NixOS/nixpkgs/pull/43833
