### ISSUE TITLE
Lower than expected battery life on NixOS

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#211345]
### Describe the bug
Two people in addition to myself (1st was on reddit, I *think* and the 2nd here:
https://www.reddit.com/r/NixOS/comments/10eplqo/terrible_battery_life_on_nixos/) are seeing lower than expected battery life on laptops running NixOS.

In my case it's an Acer Swift 3 SF314-43, but I think I have experienced this on other laptops too.

I have never gotten more than 3 hours. A poster here gets 6 to 7 hours: https://community.acer.com/en/discussion/636230/battery-life-new-laptop-low-swift-3-sf314-42

This issue is for now just a place holder. Let's collect all the information here to see if we can get to the bottom of it.

**Comment by NotAShelf** [comment]
I believe I can more or less confirm this on my device. A device - albeit old - that could get around 4-5 hours of battery life on my previous choice of distro, now lives a bit longer than 2 hours on battery despite every optimization I've implemented.

**Comment by surfaceflinger** [comment]
If y'all running power-profiles-daemon with tlp then keep in mind that they conflict with each other. Personally, I prefer tlp so disable p-p-d with

```
services.power-profiles-daemon.enable = false;
```

Also, try running thermald, which should improve thermals, in some cases INCREASE performance and reduce power draw.

```
services.thermald.enable = true;
```

While tlp has mostly good config by default, try changing its governor and turbo boost settings.

```
services.tlp = {
  settings = {
    CPU_BOOST_ON_AC = 1;
    CPU_BOOST_ON_BAT = 0;
    CPU_SCALING_GOVERNOR_ON_AC = "performance";
    CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
  };
};
```

If you have older Intel CPU with passive intel_pstate then set scheduler to schedutil instead. (and ofc get rid of CPU_SCALING_GOVERNOR_ON_* from tlp config)

```
powerManagement.cpuFreqGovernor = lib.mkDefault "schedutil";
```

Personally, I've never noticed my battery life being shorter on two laptops running NixOS with this configuration which were running multiple other distros and Windows 10/11 before.

**Comment by alois31** [comment]
Almost all of the benefit that TLP had, at least on my machine, was achieved by allowing the disk controllers to enter power saving mode. I don't use TLP any more and instead set `ahci.mobile_lpm_policy=3` on the kernel command-line. It might be a good idea to make this default using `CONFIG_SATA_MOBILE_LPM_POLICY=3`, like Fedora does.

**Comment by peterhoeg** [comment]
I think that I may have found the culprit on my current device:

```
Power est.              Usage       Events/s    Category       Description
  13.3 W    100.0%                      Device         USB device: HD User Facing (SunplusIT Inc)
```

13.3 *just* for the camera seems more than a little excessive....

**Comment by collares** [comment]
@peterhoeg Are all (or almost all) other USB power estimates suspiciously zero? I was in a similar situation and, after disabling the camera, the audio adapter started reporting a large number instead. So I think this number is actually a sum being reported in a misleading way.

**Comment by peterhoeg** [comment]
Good point @collares, yes, apart from the wifi (wtf is that on usb rather than pcie???), all other USB devices show 0.

*However*, by using this, the power usage has now dropped and powertop reports I have 4+ hours of battery (not great, but better):

```nix
{
      systemd.tmpfiles.rules = map
        (e:
          "w /sys/bus/${e}/power/control - - - - auto"
        ) [
        "pci/devices/0000:00:01.0" # Renoir PCIe Dummy Host Bridge
        "pci/devices/0000:00:02.0" # Renoir PCIe Dummy Host Bridge
        "pci/devices/0000:00:14.0" # FCH SMBus Controller
        "pci/devices/0000:00:14.3" # FCH LPC bridge
        "pci/devices/0000:04:00.0" # FCH SATA Controller [AHCI mode]
        "pci/devices/0000:04:00.1/ata1" # FCH SATA Controller, port 1
        "pci/devices/0000:04:00.1/ata2" # FCH SATA Controller, port 2
        "usb/devices/1-3" # USB camera
      ];
}
```

**Comment by Lillecarl** [comment]
Wouldn't this be better discussed on the community forums? There's no issue other than configuration here.

I'd recommend reading https://wiki.archlinux.org/title/Power_management 

I'm on AMD, using PipeWire for Audio, KDE PowerDevil for power mgmt (for now), amd pstate driver in kernel and schedutil scheduler. On a ThinkPad T14s Gen2 I can play YouTube in Brave Browser from falling asleep til waking up (Though this is on lowest monitor brightness), which I find to be outstanding.

NixOS defaults generated by nixos-generate-config is an issue in itself, new people joining the NixOS club being greeted by the most generic untuned system ever is hardly great. Though it seems we manage to lure in people anyways 😄 
(This issue isn't just for newcomers though, I still discover new knobs I should've known about "daily").

**Comment by flokli** [comment]
Yeah, I think this is not a nixpkgs issue.

We should provide more documentation on how to tune Laptops power-wise, and maybe `nixos-generate-config`, or whatever is used as an installer could enable more of this if it detects a laptop.
