### ISSUE TITLE
amdvlk: Failed to CreateInstance in ICD 0.  Skipping ICD.

### ISSUE THREAD

**Issue by Elinvention** [NixOS/nixpkgs#211408]
### Describe the bug

The AMDVLK driver cannot be loaded on NixOS 22.11, while RADV works fine.

If I try to run `env VK_ICD_FILENAMES=/run/opengl-driver/share/vulkan/icd.d/amd_icd64.json vulkaninfo` I get this message:

```
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
ERROR: [Loader Message] Code 0 : terminator_CreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/source/vulkaninfo/vulkaninfo.h:672:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

### Steps To Reproduce
1. install AMDVLK vulkan driver with the configuration from https://nixos.wiki/wiki/AMD_GPU#Vulkan
2. run `env VK_ICD_FILENAMES=/run/opengl-driver/share/vulkan/icd.d/amd_icd64.json vulkaninfo` 
3. get error message and AMDVLK can't be used

### Expected behavior
AMDVLK should work fine.

### Notify maintainers

@Flakebi 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 22.11 (Raccoon), 22.11.1629.2f9fd351ec3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - channels(elia): `"home-manager-22.05.tar.gz, release-22.11.tar.gz-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by Flakebi** [comment]
Hi,
I’m on nixos-unstable, but using amdvlk from the 22.11 channel works fine for me.
Can you try a few things?
1. Can you post the output of `vulkaninfo --summary` for radv? (It shows things like layers and the gpu)
2. Can you try with `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1` in your environment? This disables the switchable graphics layer.
3. If that doesn’t work, can you upload a log of running vulkaninfo with `LD_DEBUG=libs` please?

**Comment by Flakebi** [comment]
Thanks!
Seems like the bug that amdvlk doesn’t recognize the gfx10.3 iGPU. There’s an upstream report here that says it will be fixed in the next release (which shouldn’t be far away): https://github.com/GPUOpen-Drivers/AMDVLK/issues/310

**Comment by Elinvention** [comment]
Thanks! That was it! As soon as I disabled the integrated GPU from UEFI, it started working properly. The odd thing is that I used a different distro to test this and there it worked, probably because I used linux 5.15 that doesn't recognize gfx1036 at all.

**Comment by Flakebi** [comment]
Closing as this is an upstream bug that should be fixed by now.
