### ISSUE TITLE
Tracking issue: treewide rewrite of `data/fonts` to use stdenvNoCC

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#211429]
Given the quick and not so clean change done in #211158 caused by the change on semantics of `fetchzip` (#173430), it is imperative to use a cleaner approach.

**Comment by wegank** [comment]
I also wonder if a conversion from `fetchzip` to `fetchurl` is preferable for tarballs, since the latter does not introduce `unzip` as an extra dependency.

**Comment by AndersonTorres** [comment]
It depends. Sometimes `fetchurl` a tarball is not fixed because the tarball is generated on the fly, and any change on timestamps wild change the checksum.

For these cases `fetchzip` is recommended.

**Comment by wegank** [comment]
It seems to me that more fonts are affected: #211447 targets 30 files, while only 1 of them is in the 78-font PR.
