### ISSUE TITLE
Upgrade Terraform package

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#21140]
Current version is 0.7.13.

**Comment by nixy** [comment]
Could you make a pull request for this? 

The nix expression for terraform looks pretty straightforward, but I am not terribly familiar with this project.

**Comment by kamilchm** [comment]
Updated in https://github.com/NixOS/nixpkgs/pull/21139

**Comment by spy-tech** [comment]
@joachifm ,@kamilchm:

This doesn't work without weird error messages:
```grep: Invalid range end```
