### ISSUE TITLE
worth using `--enable-alt-array-implementation` in bash 5.2+?

### ISSUE THREAD

**Issue by abathur** [NixOS/nixpkgs#211490]
I read over the [short release notes](https://tiswww.case.edu/php/chet/bash/NEWS) for bash 5.2 since I noticed it's recently become the default in nixpkgs and noticed the following:

```
u. There is an alternate array implementation, selectable at `configure' time,
   that optimizes access speed over memory use (use the new configure
    --enable-alt-array-implementation option).
```

I haven't played with the feature yet, but IIRC stdenv and other shell builders make extensive use of arrays--so it _might_ be interesting to see what this speed/performance tradeoff is like at nixpkgs-scale?

**Comment by Artturin** [comment]
openSUSE has

https://github.com/bmwiedemann/openSUSE/commit/ac02cc0f225644e6190b0b0ab89458156507a19f
> - Disable alternate array implementation as it eats a lot of memory
