### ISSUE TITLE
Eventual near-hangs with transparent hugepages

### ISSUE THREAD

**Issue by alois31** [NixOS/nixpkgs#211548]
### Describe the bug
After the system was operative for some time, applications attempting to fault in memory previously subjected to `MADV_HUGEPAGE` will cause 100% kernel CPU usage for a significant amount of time. This appears like a hang, but usually resolves after several seconds or minutes.

### Steps To Reproduce
1. Boot the system
2. Run it for some time, perform various operations (presumably to cause fragmentation of physical RAM)
3. Compile and run the following reproducer (possibly adjust `len` a bit according to machine RAM size, mine has 8GB):
```
#include <sys/mman.h>

int main()
{
        size_t len = 1ULL << 30;
        char *ptr = mmap(0, len, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
        if (ptr == MAP_FAILED) {
                return 1;
        }
        if (madvise(ptr, len, MADV_HUGEPAGE) < 0) {
                return 1;
        }
        for (size_t i = 0; i < len; i += 1 << 21) {
                ptr[i] = 1;
        }
}
```
4. If the reproducer finishes quickly, go to step 2 and try again after some time.

### Expected behavior
The program finishes very quickly, taking at most a couple of seconds.

### Actual behavior
The program runs for minutes. Checking e.g. in htop one sees the memory usage remaining constant for large amounts of time while the kernel CPU usage is near 100%.

### Additional context
I originally noticed the behavior in libvirt/qemu VMs starting about a month ago. Relevant updates in this timeframe seem to include kernel 6.0->6.1, qemu 7.1.0->7.2.0 and possibly libvirt 8.9.0->8.10.0. While it's very likely a kernel bug or misconfiguration, it may have existed before 6.1 and be uncovered by an update in the virtualization stack enabling transparent hugepage support.

### Notify maintainers
@TredwellGit @Ma27 @NeQuissimus @alyssais @thoughtpolice kernel maintainers
@edolstra @alyssais QEMU maintainers
@fpletz @globin @lovesegfault libvirt maintainers

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 23.05 (Stoat), 23.05.20230115.6dccdc4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ValdikSS** [comment]
I'm not a Nix user but I experience something similar. Did by a chance update to Kernel 6.1 enable MGLRU by default? `cat /sys/kernel/mm/lru_gen/enabled`

**Comment by alois31** [comment]
Yes, MGLRU was enabled shortly after the update to 6.1, and it is fully enabled (0x0007) on my system. Disabling MGLRU when I'm already able to reproduce the bug does not help. I will check whether I can reproduce when disabling MGLRU just after boot.

**Comment by alois31** [comment]
I can reproduce the behavior even when disabling MGLRU just after boot. There are no hangs for some time afterwards, but they eventually start and get progressively worse, just like with MGLRU enabled.

**Comment by ValdikSS** [comment]
When it hangs, does reading `/proc/PID/cmdline` for qemu process also hangs? `ps aux` listing stops on qemu process and htop won't start for me.

**Comment by ValdikSS** [comment]
If I attach strace to qemu process, it also hangs and seem to ignore the signals (`ctrl+c` does nothing).

**Comment by alois31** [comment]
Yes, that also hangs.

**Comment by ValdikSS** [comment]
I'm running Fedora 37.
Could not trigger this bug on kernel 6.0.18.
On 6.1.7 it could be triggered with MGLRU much faster than without it.

I'm testing on a laptop with 8 GB RAM.
The test is as follows:
1. Run Debian 11 KDE x86 in qemu, wait until it fully boots to KDE: `sudo qemu-system-i386 -enable-kvm -m 1024 -smp 2 -drive file=/dev/sdc,if=virtio,cache=unsafe -nic user`
2. create empty 8 GB file on the host file system: `fallocate -l 8G file.bin`
3. read it into memory several times: `pv file.bin > /dev/null`
4. run reproducer from the first post

With 6.1.7+MGLRU reproducer usually hangs after the first try. Without MGLRU, it may take multiple `pv` invocations or `qemu` restarts.

The reproducer hangs on `madvise(addr, len, MADV_HUGEPAGE)` call.

**Comment by ValdikSS** [comment]
Recorded perf kernel events with symbols. It seems that the slow path is compact_zone→migrate_pages.
[bug.tar.gz](https://github.com/NixOS/nixpkgs/files/10528168/bug.tar.gz)

@alois31, could you please file a bug in kernel bugzilla, as I assume you have more experience with such kind of bugs?

**Comment by alois31** [comment]
Thanks for the reproducer. I'll try a bisect. Kernel bugzilla seems to be mostly useless for this kind of bug.

**Comment by ValdikSS** [comment]
Yu Zhao, the developer of MGLRU, replied me privately:
>This is not a MGLRU bug -- it's likely caused by missing a recent fix for v6.1:
95e7a450b819 Revert "mm/compaction: fix set skip in fast_find_migrateblock"

**Comment by ValdikSS** [comment]
Applying this patch (revering the original patch) did not help.

**Comment by alois31** [comment]
Other people reported this problem on mailing lists (https://lore.kernel.org/kvm/b8017e09-f336-3035-8344-c549086c2340@kernel.org/). Somebody wrote there that things fixed by dropping caches are a different bug. I'm going to test stuff again when 6.1.9 hits unstable (currently running with transparent hugepages turned off, since their benefit is quite small and completely negated by this bug).

**Comment by alois31** [comment]
I've had no issues now with 6.1.9 after multiple days of cumulated uptime (including hibernation). I consider this fixed.
