### ISSUE TITLE
NixOS 17.03pre96925.1c50bdd -> stat --printf (unrecognized option)

### ISSUE THREAD

**Issue by Krofek** [NixOS/nixpkgs#21152]
## Issue description

After upgrading to the latest version the shell outputs the following:

> stat: unrecognized option '--printf'
> WARNING: bad ownership on $NIX_USER_PROFILE_DIR" >&2

The error occurs in the environment.shellInit option found in:

```
//modules/programs/shell.nix
if test "$(stat --printf '%u' $NIX_USER_PROFILE_DIR)" != "$(id -u)"; then
    echo "WARNING: bad ownership on $NIX_USER_PROFILE_DIR" >&2
fi
```

Works ok if the following change is made:

```
if test "$(stat -f '%u' $NIX_USER_PROFILE_DIR)" != "$(id -u)"; then
    echo "WARNING: bad ownership on $NIX_USER_PROFILE_DIR" >&2
fi
```

The system configuration hasn't changed before the upgrade.

### Steps to reproduce

1. `nixos-rebuild switch --upgrade`
2. open a new shell

## Technical details

* System: NixOS: 17.03pre96925.1c50bdd (Gorilla)
* Nix version: 1.12pre4523_3b81b26
* Nixpkgs version: 17.03pre96925.1c50bdd
* Coreutils: 8.25
* BusyBox v1.23.2 () multi-call binary.

**Comment by Moredread** [comment]
Hi @Krofek, is this still an issue? Are you using the busybox shell?

**Comment by Krofek** [comment]
Hello, it looks like the issue is fixed.

**Comment by tomberek** [comment]
Close?
