### ISSUE TITLE
steam: can not pair with steam controller

### ISSUE THREAD

**Issue by baracoder** [NixOS/nixpkgs#21159]
## Issue description

Can't pair Steam Controller with steam.  

From the startup log this bit could be relevant:
```
Created shared memory when not owner SteamController_Shared_mem
CHIDDeviceListSDL(): Couldn't load libSDL2-2.0.so.0, not enumerating devices
```

No controllers detected. Even though the udev rule exists and device access is set ( see #10646)

```
ls -l /dev/input/by-id 

lrwxrwxrwx 1 root root  9 14. Dez 23:44 usb-Valve_Software_Steam_Controller-event-mouse -> ../event0
lrwxrwxrwx 1 root root  9 14. Dez 23:44 usb-Valve_Software_Steam_Controller-mouse -> ../mouse0
```

```
ls -l /dev/input
crw-rw---- 1 root input 13, 64 14. Dez 23:44 event0
crw-rw---- 1 root input 13, 32 14. Dez 23:44 mouse0
```

```
id
uid=1000(bara) gid=1000(bara) groups=1000(bara),1(wheel),17(audio),26(video),55(adm),100(users),131(docker),174(input)
```

### Steps to reproduce

on nixos 16.09

1. add udev rules for steam controller see #10646
2. add `steam` to packages list
3. run `nixos-rebuild switch`
4. start steam
5. start big picture mode
6. go to settings and try to pair controller

## Technical details

* System: `nixos-version`, 16.09.1119.ece0cea (Flounder)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 16.09.1119.ece0cea

**Comment by abbradar** [comment]
It's strange because SDL2 should be in Steam Runtime. Try adding `SDL2` to `multiPkgs` list in `pkgs/games/steam/chrootenv.nix`; does it help?

**Comment by baracoder** [comment]
thank you for the reply @abbradar 
unfortunately this did not solve it.

added SDL2 to multiPkgs, built and installed with `nix-env -f path_to_nixpkgs -i steam` same error in the logs 

the lib seams to be there
```
find /nix/store -iname 'libSDL2-2.0.so.0'|grep wzbcwjidyc4rwncmdzv42c0icdx7j19p
find: ‘/nix/store/q9ci39sfbkygr5gwlg061b90gazh704y-slack-2.1.2/usr’: Permission denied
/nix/store/wzbcwjidyc4rwncmdzv42c0icdx7j19p-steam-fhs/usr/lib64/libSDL2-2.0.so.0
/nix/store/wzbcwjidyc4rwncmdzv42c0icdx7j19p-steam-fhs/usr/lib64/steam-runtime/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
/nix/store/wzbcwjidyc4rwncmdzv42c0icdx7j19p-steam-fhs/usr/lib32/libSDL2-2.0.so.0
/nix/store/wzbcwjidyc4rwncmdzv42c0icdx7j19p-steam-fhs/usr/lib32/steam-runtime/usr/lib/i386-linux-gnu/libSDL2-2.0.so.0
```

but the same error

**Comment by baracoder** [comment]
Found it, looks like something changed in steam so the udev rules need updating http://steamcommunity.com/app/353370/discussions/0/490123197956024380/

after fixing the udev rule, it works again
