### ISSUE TITLE
use of `type` in setup.sh caused conflict with ruby gem build script.

### ISSUE THREAD

**Issue by wavewave** [NixOS/nixpkgs#211671]
### Describe the bug
ruby gem script uses the env variable `type` for specifying the source is "gem",  "git" or "url".. 
see [this code](https://github.com/NixOS/nixpkgs/blob/a4f710e8584dea15a801b75a03abc400bec6c683/pkgs/development/ruby-modules/gem/default.nix#L161)
However [this line](https://github.com/NixOS/nixpkgs/blob/a4f710e8584dea15a801b75a03abc400bec6c683/pkgs/stdenv/generic/setup.sh#L223) seems to override the variable (which seems to be introduced [here](https://github.com/NixOS/nixpkgs/commit/11c3127e38dafdf95ca71a85b1591a29b67e0c09) 

We should use different name for such global variables for both ruby side and stdenv side. 
and looks like `type` in setup.sh can be declared as local.

cc: @Artturin

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/211323

**Comment by wavewave** [comment]
oh! it was fixed now. thanks!!!
