### ISSUE TITLE
coreutils-8.24: ARM patch hash out of date [does not affect master]

### ISSUE THREAD

**Issue by kierdavis** [NixOS/nixpkgs#21179]
## Issue description

The [expression for coreutils 8.24][patch-use] includes an [external patch][patch] required for the package to build on ARM architecture. The hash of this patch has changed recently (though I can't identify exactly how it's changed). The 15.09 release channel, and potentially other channels, includes coreutils 8.24, so this issue causes most source builds of 15.09 on ARM to fail.

Old hash (as recorded in expression): 1dnlszhc8lihhg801i9sz896mlrgfsjfcz62636prb27k5hmixqz
New hash (computed today): 12lm74yahcbyrk6hlhrdgjxlinlalkmha62ygg5p7w8hm66f83yi

This patch looks like it was merged into coreutils mainline in 8.25, so it's no longer explicitly used in the derivation. As such this issue doesn't affect recent versions of NixOS; however, release 15.09, and potentially other releases, do still use coreutils 8.24 and so are affected by this issue.

This should be a simple one-line change, though I don't know what branch to PR against, since this issue doesn't affect master.

### Steps to reproduce

Attempt to build coreutils 8.24 from source on ARM.

## Technical details

* System: NixOS 15.06pre-git (Dingo) on ARM
* Nix version: 1.8
* Nixpkgs version: 15.09.1262.3727911

[patch]: http://git.savannah.gnu.org/cgit/coreutils.git/patch/?id=3ba68f9e64fa2eb8af22d510437a0c6441feb5e0
[patch-use]: https://github.com/NixOS/nixpkgs/blob/release-15.09/pkgs/tools/misc/coreutils/default.nix#L23

**Comment by Mic92** [comment]
the branch is `release-15.09`

**Comment by joachifm** [comment]
This doesn't affect 16.03 upwards. I suspect your time would be better spent moving to an actually supported channel.

**Comment by kierdavis** [comment]
@Mic92 cheers. Thought it might be that but wanted to make sure.

@joachifm unfortunately, I need to build from 15.09 in order to accomplish exactly that.

I'm attempting to get NixOS set up on my Raspbery Pi 2. The only SD card image available is the one on the [wiki][image], which is built from a nixpkgs near version 15.06 or so. Since cache.nixos.org doesn't host ARM builds, most things have to be built from source, and due to the low power processor in the Pi a nixos-rebuild can take several hours. Annoyingly, the version of Nix in the SD card image is too old to evaluate 16.09, so at the least I have to use an earlier release as a stepping stone to get a newer version of Nix.

[image]: https://nixos.org/wiki/Raspberry_Pi_2#Download

**Comment by Mic92** [comment]
clever runs, not sure, if it useful in your case: http://hydra.earthtools.ca/eval/1944?compare=nixpkgs-arm-unstable#tabs-new

**Comment by dezgeg** [comment]
I believe http://nixos-arm.dezgeg.me/installer/sd-image-armv7l-linux.img should boot out-of-the box on Raspberry Pi 2. The wiki unfortunately has lots of obsolete stuff...

**Comment by kierdavis** [comment]
@Mic92 @dezgeg thanks, i'll check those out
