### ISSUE TITLE
tmuxp depends on old libtmux package

### ISSUE THREAD

**Issue by martiert** [NixOS/nixpkgs#211743]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: tmuxp

current version: 1.12.1
desired version: 1.23.0

###### Notify maintainers

maintainers: 1.23.0

###### Note for maintainers

https://github.com/NixOS/nixpkgs/pull/211742

**Comment by natsukium** [comment]
updated in https://github.com/NixOS/nixpkgs/pull/211742
