### ISSUE TITLE
mtxclient, nheko fail to build on aarch64-linux

### ISSUE THREAD

**Issue by uninsane** [NixOS/nixpkgs#211758]
### Steps To Reproduce
1. `nix build '.#legacyPackages.aarch64-linux.nheko'`

### Build log
```
error: builder for '/nix/store/x2p0k768qavk91cwq9jv4xwcgpyhrscm-mtxclient-0.9.0.drv' failed with exit code 2;
       last 10 log lines:
       > make[2]: *** [CMakeFiles/matrix_client.dir/build.make:370: CMakeFiles/matrix_client.dir/lib/structs/events/encrypted.cpp.o] Error 1
       > In file included from /build/source/include/mtxclient/crypto/client.hpp:17,
       >                  from /build/source/lib/crypto/utils.cpp:17:
       > /build/source/include/mtx/identifiers.hpp:12:10: fatal error: compare: No such file or directory
       >    12 | #include <compare>
       >       |          ^~~~~~~~~
       > compilation terminated.
       > make[2]: *** [CMakeFiles/matrix_client.dir/build.make:132: CMakeFiles/matrix_client.dir/lib/crypto/utils.cpp.o] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/matrix_client.dir/all] Error 2
       > make: *** [Makefile:136: all] Error 2
       For full logs, run 'nix log /nix/store/x2p0k768qavk91cwq9jv4xwcgpyhrscm-mtxclient-0.9.0.drv'.
error: 1 dependencies of derivation '/nix/store/szdzykpfiknzmzl5j0mar4kvngnq7hig-nheko-0.11.1.drv' failed to build
```

### Additional context
- i noticed the break after the nheko 0.10.2 -> 0.11.0 upgrade landed in nixos-unstable: <https://github.com/NixOS/nixpkgs/pull/210471>
- hydra failure (click `log` for the build log): <https://hydra.nixos.org/build/205928297>
- build is currently broken in both master (5ed481943351e9fd354aeb557679624224de38d5) and ~~nixos-22.11 branches~~has been fixed in nixos-22.11, see https://github.com/NixOS/nixpkgs/pull/211776#issuecomment-1399363381

### Notify maintainers

- tagging @rnhmjoj for having initiated the backport.
- tagging @fpletz as maintainer of both mtxclient and nheko. 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[colin@uninsane.org:~/dev/3rd/nixpkgs]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.86, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - nixpkgs: `/home/colin/dev/3rd/nixpkgs`
```

**Comment by uninsane** [comment]
tested against the outstanding mtxclient 0.9.0 -> 0.9.1 PR: <https://github.com/NixOS/nixpkgs/pull/211684>. still broken.

**Comment by rnhmjoj** [comment]
I have no idea why a standard library [header](https://en.cppreference.com/w/cpp/header/compare) would depend, let alone be missing, on a different architecture.

**Comment by NickCao** [comment]
Likely due to us using outdated gcc (gcc9) on aarch64-linux. The story is complicated, but is being addressed.

**Comment by rnhmjoj** [comment]
It seems so: I tested by cross-compiling mtxclient (I don't have an aarch64 system).

**Comment by rnhmjoj** [comment]
Opened #211776

**Comment by rnhmjoj** [comment]
Great... now coeurl fails to build.

**Comment by uninsane** [comment]
hope nobody minds this extra notification that is me thanking you all for jumping in so readily to fix things, even for someone you’ve never met. ❤️ anyone reading this: what you’re doing here has more impact than you know.
