### ISSUE TITLE
Build rustdesk with Flutter GUI

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#211751]
### Describe the bug

I can't use rustdesk, because it uses unfree libraries, which are forbidden on my system.

It seem now possible to build it with Flutter.

Upstream issue: https://github.com/rustdesk/rustdesk/issues/900

### Steps To Reproduce

```
[davidak@gaming:~]$ nix run nixpkgs#rustdesk
error: Package ‘libsciter-4.4.8.23-bis’ in /nix/store/ld350gbq2w5654yw4q95kxhxp4569zi6-source/pkgs/development/libraries/libsciter/default.nix:40 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "libsciter"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

### Expected behavior

>the open source TeamViewer alternative

### Additional context

https://github.com/rustdesk/rustdesk/commit/f830b395b97358fcccc7cd96ce94fe31fcd42c26
https://github.com/rustdesk/rustdesk/issues/103

I think we have to wait for a new release if the change is already committed to master.

### Notify maintainers
@Leixb

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 22.11 (Raccoon), 22.11.1629.2f9fd351ec3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by fgaz** [comment]
@davidak meanwhile you might be interested in a similar program I just packaged: #226155

**Comment by dr460nf1r3** [comment]
Rustdesk is now built with flutter in `nixos-unstable`.

**Comment by Leixb** [comment]
@dr460nf1r3 Unfortunately, it's not built with flutter.

I could not get `flutter.buildFlutterApplication` to work (as explained in the PR). I opted to update the sciter and leave the flutter build for when I have more time. If anyone wants to pick this up, feel free to do so, I probably won't have time to look at it until late November.

**Comment by dr460nf1r3** [comment]
Now that is embarrassing. My apologies!

**Comment by sjau** [comment]
> Rustdesk is now built with flutter in `nixos-unstable`.

I can't find any options for Rustdesk server in the nixos options page https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=rustdesk

**Comment by anoadragon453** [comment]
An additional benefit to being able to mark `rustdesk` as free is that it can then be built and cached by hydra.nixos.org.

*Sent from a very warm laptop that just built `rustdesk`*.

**Comment by Leixb** [comment]
There is now `rustdesk-flutter` #286129 thanks to the amazing work from @dasJ

**Comment by XBagon** [comment]
> I like to mention, that there might be good reasons to not provide Ruskdesk at all.
> 
> https://www.reddit.com/r/selfhosted/comments/14kjvkg/community_consensus_on_rustdesk_with_all_the/
> 
> https://news.ycombinator.com/item?id=39256493

Does this sufficiently address at least this issue? https://github.com/rustdesk/rustdesk/discussions/6444#discussioncomment-12039260
