### ISSUE TITLE
metasploit broken on master and on stable

### ISSUE THREAD

**Issue by nico202** [NixOS/nixpkgs#21186]
## Issue description
metasploit is missing ruby. Installing ruby (2_0, 2_1, 2_2, 3_3) triggers different error messages

### Steps to reproduce
nix-env -iA nixos.msf
msfcli / msfconsole

**Comment by c0bw3b** [comment]
The metasploit-framework package is out of date and should be updated to 4.x
See PR #16256 for that. It seems a bit of work is needed to properly package all the required rubygems.

**Comment by nico202** [comment]
Thanks, sorry to not have noticed that PR
Closing this
