### ISSUE TITLE
collectd's datadir is not readable by others

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21198]
collectd service writes RRD files to the datadir (default /var/lib/collectd) where other programs run under other users (e.g. CGI-scripts)  read the RRD files making visual representation of them.
But the directory is [created with access permissions 700](https://github.com/NixOS/nixpkgs/blob/50466c2d4feca9eee52815eebb30ab6c62dc4deb/nixos/modules/services/monitoring/collectd.nix#L111) that means noone except collectd user (the writer) could read the files back.
This looks nonsense.
The directory has access permissions 755 on Ubuntu.

**Comment by joachifm** [comment]
cc @offlinehacker
