### ISSUE TITLE
paper-note: build failed 

### ISSUE THREAD

**Issue by me00001** [NixOS/nixpkgs#211985]
### Steps To Reproduce
1. be in nixos-unstable
2. upgrade 
3. paper-note build will failed 
### Build log
https://paste.dismail.de/?c7d3b6c1b6897ee4#Eme9MdchDD3uFhVyGj72tDsVbnuj2QSZ3d6NzmCL68Wo

### Additional context
```
Dependency libadwaita-1 found: NO found 1.2.1 but need: '1.2.0'
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libadwaita-1 found: NO 
```
### Notify maintainers

@j0lol
me@j0.lol

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 23.05 (Stoat), 23.05pre443927.6dccdc45851`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos"`
 - channels(suliman): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ocfox** [comment]
You can override paper-note by adding the following section and it should work fine.
```  
patchPhase = ''
    sed -i 's/1.2.0/1.2.1/g' src/meson.build
'';
```
