### ISSUE TITLE
discussion about PIE and golang

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nixpkgs#211951]
Currently, pkgsMusl.rclone fails to build:

```
/nix/store/dbgdbpda30rscjlps73glkgz3w8gqszp-binutils-2.39/bin/ld: /build/go-link-354073529/go.o: warning: relocation in read-only section `.gopclntab'
/nix/store/dbgdbpda30rscjlps73glkgz3w8gqszp-binutils-2.39/bin/ld: warning: creating DT_TEXTREL in a PIE
@nix { "action": "setPhase", "phase": "checkPhase" }
running tests
?       github.com/rclone/rclone        [no test files]
@nix { "action": "setPhase", "phase": "installPhase" }
installing
/nix/store/khv74mid5pm7b24ji369psdvdi3bjqgj-stdenv-linux/setup: line 113: 16821 Segmentation fault      (core dumped) $out/bin/rclone genautocomplete $shell rclone.$shell
/nix/store/khv74mid5pm7b24ji369psdvdi3bjqgj-stdenv-linux/setup: line 129: pop_var_context: head of shell_variables not a function context
```

Or rather, it builds, but produces a faulty binary that segfaults later on.

From my research, this happens when the external linker defaults to PIE while golang defaults to non-PIE, which is the case in pkgsMusl (but not in the normal glibc package set, since the pie hardening flag is disabled there).

Our options are adding `hardeningDisable = [ "pie" ];` to buildGoModule or [patching go to set the default buildmode to PIE](https://github.com/NixOS/nixpkgs/commit/73e05c425713aab7e06de8b3fcd6bf74cd2ed0e9)

What do you think?

CC @zowoq @superherointj

**Comment by zowoq** [comment]
>  which is the case in pkgsMusl (but not in the normal glibc package set, since the pie hardening flag is disabled there).

Why is it enabled for musl? A quick grep through the repo shows that it's disabled in quite a few places for musl, seems like something that isn't `go` specific, shouldn't this be fixed in `stdenv` instead?

**Comment by yu-re-ka** [comment]
### On PIE in general

It is enabled by default for musl, because it can be. We generally want this hardening option, just that nobody ever got it working in nixpkgs with glibc. I tried to enable it in the glibc package set, but it fails early on.

> A quick grep through the repo shows that it's disabled in quite a few places

I wouldn't say that.
It is mostly explicitly disabled for the build of build tools like gcc, ghc, binutils. Otherwise it is enabled for almost all packages.

```
[yuka@m1:~/proj/nixpkgs]$ rg -i "disable.*pie" | wc -l
40

[yuka@m1:~/proj/nixpkgs]$ rg -i "disable.*pie" | grep gcc | wc -l
10

[yuka@m1:~/proj/nixpkgs]$ rg -i "disable.*pie" | grep ghc | wc -l
17

[yuka@m1:~/proj/nixpkgs]$ 
```

So 13 occurrences left that are not in gcc or ghc.

Other distros, which have figured out how to make it work with glibc, have enabled it by default.
Quote from wikipedia: Beginning with Fedora 23, Fedora maintainers decided to build packages with PIE enabled as the default. Ubuntu 17.10 has PIE enabled by default across all architectures. Gentoo's new profiles now support PIE by default. Around July 2017, Debian enabled PIE by default.

### On go and PIE

The issue is specific to go, because go itself produces either PIE or non-PIE code and this has to match with what the linker does (which is controlled by NIX_HARDENING_ENABLE env variables through the wrapper), otherwise we get faulty binaries.
The question is do we want to have PIE for golang builds _always_ disabled, even if it is supported in nixpkgs on that system? Or do we want to explicitly enable PIE in golang builds when available? By default it will always be disabled in the go compiler (default buildmode=exe is non-PIE), and we don't have a mechanism to enable it yet.

I also found [this commit](https://github.com/golang/go/commit/53aec79ce05cd5eff1c8f5576b553d3c429227c3) in upstream Go, which is supposed to prevent the mismatch of go producing non-PIE code and it getting linked into a faulty PIE binary by the external linker, by passing `no-pie` to the linker. Probably this doesn't work because of how PIE is enabled in stdenv via the wrappers. But I think this is not necessarily something we have to fix, the way that CC wrapper and hardening flags work in nixpkgs it is expected that the CC wrapper overrides flags that the build system passes(?)

Also in my opinion it would be good if buildGoModule would also have PIE enabled when the environment supports it, which would definitely require explicitly enabling the flag for the go compiler by setting `buildmode=pie`.
Alpine used to have a patch that changes the default build mode, but now passes `-buildmode=pie` via the GOFLAGS environment variable in their global build environment: https://github.com/alpinelinux/abuild/blob/master/abuild.conf#L5

**Comment by yu-re-ka** [comment]
For now I think we could just add `hardeningDisable = [ "pie" ]` to build-go-module (maybe add that to https://github.com/NixOS/nixpkgs/pull/211850?) and later look into properly enabling PIE when possible?

**Comment by zowoq** [comment]
> It is enabled by default for musl, because it can be. We generally want this hardening option, just that nobody ever got it working in nixpkgs with glibc. I tried to enable it in the glibc package set, but it fails early on.

> I wouldn't say that.
> It is mostly explicitly disabled for the build of build tools like gcc, ghc, binutils.

My point was it doesn't seem like an isolated issue. It doesn't work with glibc but it doesn't seem like it really work with musl either? Are we just perpetuating a problem by disabling it in `go` when really it just shouldn't be enabled in stdenv?

> Otherwise it is enabled for almost all packages.

Don't see that this means much really unless they're known to be working?

**Comment by yu-re-ka** [comment]
> Don't see that this means much really unless they're known to be working?

I know that most packages in the pkgsMusl package set are working, since I have a laptop running NixOS with musl libc using the [musl-nixos overlay](https://cyberchaos.dev/cyberchaoscreatures/musl-nixos) with my normal desktop config.

demonstration that most applications (commands are run in the musl-nixos flake)
```
$ nix build .#hello

$ file result/bin/hello 
result/bin/hello: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#htop

$ file result/bin/htop
result/bin/htop: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#tmux

$ file result/bin/tmux 
result/bin/tmux: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#fd

$ file result/bin/fd
result/bin/fd: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#wofi

$ file result/bin/wofi 
result/bin/wofi: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#wireshark

$ file result/bin/.wireshark-wrapped 
result/bin/.wireshark-wrapped: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#gimp

$ file result/bin/.gimp-2.10-wrapped 
result/bin/.gimp-2.10-wrapped: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#firefox-unwrapped

$ file result/lib/firefox/firefox
result/lib/firefox/firefox: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, BuildID[xxHash]=ac62824554ed4e46, not stripped

$ nix build .#libreoffice-fresh-unwrapped

$ file result/lib/libreoffice/program/oosplash 
result/lib/libreoffice/program/oosplash: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, not stripped

$ nix build .#python3

$ file result/bin/python3.10
result/bin/python3.10: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/l4s97qxbavb0l4q8n6ivb23yxnly4b7a-musl-1.2.3/lib/ld-musl-x86_64.so.1, BuildID[sha1]=337ce6765b5183bce740c394ed4ba0728d9e6ad2, not stripped
```

So yeah it is really working everywhere except those few build tools _and_ haskellPackages, and now we have to decide if we want to support it in buildGoModule or explicitly disable it.

**Comment by yu-re-ka** [comment]
@alyssais  might also be interested in improving PIC/PIE support in nixpkgs

**Comment by yu-re-ka** [comment]
in addition to haskellPackages, ziglang also doesn't produce PIE binaries

**Comment by zowoq** [comment]
> It is enabled by default for musl, because it can be

This was rather vague.

> Otherwise it is enabled for almost all packages

Enabled != works.

This would have been a simpler discussion if you had been explicit that most of the musl package set does actually work with pie.

Does this work to enable it?
```diff
diff --git a/pkgs/build-support/go/module.nix b/pkgs/build-support/go/module.nix
index 647f2a2f7ad..f06fc76b498 100644
--- a/pkgs/build-support/go/module.nix
+++ b/pkgs/build-support/go/module.nix
@@ -165,7 +165,7 @@ let
     inherit (go) GOOS GOARCH;
 
     GO111MODULE = "on";
-    GOFLAGS = lib.optionals (!proxyVendor) [ "-mod=vendor" ] ++ lib.optionals (!allowGoReference) [ "-trimpath" ];
+    GOFLAGS = lib.optionals stdenv.buildPlatform.isMusl [ "-buildmode=pie" ] ++ lib.optionals (!proxyVendor) [ "-mod=vendor" ] ++ lib.optionals (!allowGoReference) [ "-trimpath" ];
     inherit CGO_ENABLED;
 
     configurePhase = args.configurePhase or ''
diff --git a/pkgs/build-support/go/package.nix b/pkgs/build-support/go/package.nix
index ba1ab37a0c0..1ecc3e3932b 100644
--- a/pkgs/build-support/go/package.nix
+++ b/pkgs/build-support/go/package.nix
@@ -95,7 +95,7 @@ let
     inherit CGO_ENABLED;
 
     GO111MODULE = "off";
-    GOFLAGS = lib.optionals (!allowGoReference) [ "-trimpath" ];
+    GOFLAGS = lib.optionals stdenv.buildPlatform.isMusl [ "-buildmode=pie" ] ++ lib.optionals (!allowGoReference) [ "-trimpath" ];
 
     GOARM = toString (lib.intersectLists [(stdenv.hostPlatform.parsed.cpu.version or "")] ["5" "6" "7"]);
 

```

**Comment by yu-re-ka** [comment]
_yes_, that _would_ work, however I think we should still give the option to disable pie, either by respecting the Nix hardening flags or only setting the `-buildmode=pie` flag if none of the user-provided flags starts with `-buildmode`

**Comment by zowoq** [comment]
> either by respecting the Nix hardening flags

How's this?

```diff
diff --git a/pkgs/build-support/go/module.nix b/pkgs/build-support/go/module.nix
index 647f2a2f7ad..ecdae2234ff 100644
--- a/pkgs/build-support/go/module.nix
+++ b/pkgs/build-support/go/module.nix
@@ -171,6 +171,10 @@ let
     configurePhase = args.configurePhase or ''
       runHook preConfigure
 
+      if [[ $NIX_HARDENING_ENABLE =~ "pie" ]]; then
+        export GOFLAGS="-buildmode=pie $GOFLAGS"
+      fi
+
       export GOCACHE=$TMPDIR/go-cache
       export GOPATH="$TMPDIR/go"
       export GOPROXY=off

```

> setting the `-buildmode=pie` flag if none of the user-provided flags starts with `-buildmode`

Currently these are multiple ways of setting these and they are assembled during the buildPhase so it'll get dropped if the user mangles the flags for whatever reason or if the buildPhase is overridden.

**Comment by yu-re-ka** [comment]
Perfect! That should make it "just work".
