### ISSUE TITLE
substituteInPlace: no warning when "--replace" doesn't match

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#21195]
## Issue description

substituteInPlace doesn't tell me when a "--replace " line doesn't match once. I'm thinking it should give some warning like:

```
substituteInPlace: line NN: "X" doesn't match anything in FILE
```

**Comment by globin** [comment]
IMHO this should actually be an error, similar to the change that made the `substitute*` error out on files that don't exist. (#18019, #9744)

**Comment by vcunat** [comment]
Yes, it would be nice, but we would have to change the implementation significantly, as bash's pattern substitution feature does not support such a thing (manual page doesn't mention it).

**Comment by matthewbauer** [comment]
I guess be warned that I there are probably tons and tons of these cases throughout nixpkgs.

**Comment by volth** [comment]
> Yes, it would be nice to make this an error, but we would have to change the implementation significantly, as bash's pattern substitution feature does not support such a thing (manual page doesn't mention it).

```substituteInPlace``` could use ```sed``` internally, whose exit code is non-zero when there were no match.

**Comment by bjornfor** [comment]
How do you get sed to exit non-zero if no match? I've been wanting to do that but never found out how.

**Comment by volth** [comment]
oops, sorry, confused with ```patch``` :(

**Comment by volth** [comment]
But it is possible with ```sed``` too with some hacks: https://stackoverflow.com/questions/15965073/return-code-of-sed-for-no-match

**Comment by bjornfor** [comment]
So if we have _gnu_ sed everywhere (the 'q' command is a GNU extension) we can have that. Good to know.

**Comment by Profpatsch** [comment]
I’d really love to see this tackled. It just feels wrong to have it silently skip explicit replacement lines and we’ll probably notice lots of buggy replacements once we default to failing.

**Comment by volth** [comment]
@Profpatsch I submitted a PR against ```staging```. Not sure how many places are there to fix fruitless ```substitute*``` because ```stdenv``` does not even bootstrap with it.

**Comment by volth** [comment]
I changed fatal error to warning

**Comment by katrinafyi** [comment]
(completed by https://github.com/NixOS/nixpkgs/pull/260776)
