### ISSUE TITLE
Add Motrix

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#212068]
**Project description**
A full-featured download manager

**Metadata**

* homepage URL: https://motrix.app/
* source URL: https://github.com/agalwood/Motrix
* license: mit
* platforms: linux, darwin, dos

**Comment by dit7ya** [comment]
Already exists on nixpkgs - https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=motrix


Please search the nixpkgs repo once for existing packages/ issues/ PRs before creating new issues.
