### ISSUE TITLE
Cinny v2.2.3 Is Producing A White Screen

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#212064]
### Describe the bug
Cinny is producing a white screen, when inspecting the window, I can actually see that it's actually rendered because `ctrl+a` followed by `ctrl+c` actually copied the elements of the window like the username and password fields.

### Steps To Reproduce
1. Install cinny-desktop
2. Open Cinny

### Expected behavior
Not having a whitescreen

### Additional context
Produces a line that says `GStreamer element appsink not found. Please install it`

### Notify maintainers
@aveltras 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.79, NixOS, 22.05 (Quokka), 22.05.4389.97e88a936cf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - channels(notroot): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by aveltras** [comment]
@tengkuizdihar Are you using an nvidia card by any chance ? If so you may try the following https://github.com/tauri-apps/tauri/issues/4315#issuecomment-1207755694

It's a known bug with tauri based apps.

**Comment by tengkuizdihar** [comment]
@aveltras Just tried it and it works! Do you have an idea how to automatically append `WEBKIT_DISABLE_COMPOSITING_MODE=1` to the executable via desktop items? Because I mostly open my application using a launcher called `j4-dmenu-desktop`.

![image](https://user-images.githubusercontent.com/22078730/214030018-08fd5ed6-f684-4e45-afe6-cd3c91204c65.png)

**Comment by aveltras** [comment]
It should be doable but I don't have any example code on hand. I usually set the env variable globally for my configuration.
I'll close the ticket since it's not related to cinny-desktop per se.
