### ISSUE TITLE
Add ProtonUp-Qt

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#212071]
**Project description**
Install and manage GE-Proton, Luxtorpeda & more for Steam and Wine-GE & more for Lutris with this graphical user interface.

**Metadata**

* homepage URL: https://davidotek.github.io/protonup-qt/
* source URL: https://github.com/DavidoTek/ProtonUp-Qt
* license: gpl3
* platforms: linux

**Comment by QuantMint** [comment]
https://github.com/NixOS/nixpkgs/pull/199294
