### ISSUE TITLE
bootctl complaining about $KERNEL_INSTALL_LAYOUT

### ISSUE THREAD

**Issue by urandom2** [NixOS/nixpkgs#212102]
### Describe the bug
during my most recent nixos-rebuild switch, systemd-boot was updating

### Steps To Reproduce
1. `nixos-rebuild switch`
2. `updating systemd-boot from 252.1 to 252.4`
3. `Read $KERNEL_INSTALL_LAYOUT from /etc/machine-info. Please move it to the layout= setting of /etc/kernel/install.conf.`

### Actual behavior
```
Read $KERNEL_INSTALL_LAYOUT from /etc/machine-info. Please move it to the layout= setting of /etc/kernel/install.conf.
```

### Additional context

I cannot find any references in nixpkgs, so this must come from upstream. unclear what the correct fix is, but upstream seems to suggest that `/etc/machine-info` is [not being used](https://github.com/systemd/systemd/issues/22376), so if we are not intentionally using the default `KERNEL_INSTALL_LAYOUT=bls` value, we should be good to remove it. otherwise, we can enable it in `${pkgs.systemd}/lib/kernel/install.conf`, like the error says; unclear if that would need to be symlinked into `/etc`.

### Notify maintainers

@flokli @kloenk @mic92

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 23.05 (Stoat), 23.05.20230120.5ed4819`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `""`
 - channels(Colin Arnott): `"nixos-22.05-22.05"`
 - channels(colin): `""`
 - nixpkgs: `/nix/store/d81qdgaz0v760w7bdai42hb84p0dzzlr-source`
```

**Comment by Mic92** [comment]
I just deleted the file, it's not part of nixos.

**Comment by urandom2** [comment]
sgtm; at least now a record exists of the official resolution
