### ISSUE TITLE
Commix package fails to run

### ISSUE THREAD

**Issue by dinko-pehar** [NixOS/nixpkgs#212150]
### Describe the bug

`commix` package provides txt files for some reason in it's `src` folder. When running commix, these files are missing and cause critical error. 

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Install `commix` package
2. Run commix on some target
3. If it's a valid target, it's should pass "Testing the connection" but it would immediately fail after that stating that txt files are not found.

### Expected behavior
To be able to run `commix` properly.

### Screenshots
![Commix](https://user-images.githubusercontent.com/17788124/213933021-4614eaf8-9083-4de5-b4ce-df85304cae0b.png)

### Notify maintainers
@fabaff 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(raziel): `"darwin, home-manager, unstable"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by fabaff** [comment]
https://github.com/NixOS/nixpkgs/pull/212311 should include those missing files.

**Comment by dinko-pehar** [comment]
> https://github.com/NixOS/nixpkgs/pull/212311 should include those missing files.

Great, thank you for fixing this quickly.
