### ISSUE TITLE
Lib32 Gnutls

### ISSUE THREAD

**Issue by stealthswor** [NixOS/nixpkgs#212103]
**Project description**
The 32 bit version of gnutls. Required to run Grapejuice.

**Metadata**

* homepage URL:https://gnutls.org/index.html
* source URL: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-3.7.8-w32.zip
* license: lgpl 2.1
* platforms: arch/steamOS

**Comment by stealthswor** [comment]
Didn't seem to work...

**Comment by symphorien** [comment]
what did you attempt precisely?

**Comment by vcunat** [comment]
You need to provide more information (and reopen).

The package above builds.  We also package `grapejuice` which starts up (for me on x86_64 NixOS), including installation of Roblox Studio up to login.
