### ISSUE TITLE
Use Tesseract 5 for ocrmypdf

### ISSUE THREAD

**Issue by QuantMint** [NixOS/nixpkgs#212163]
Ocrmypdf supports tesseract 5, but the current version in nixpkgs is using the very outdated tesseract 3.
Tesseract 5 is much better than tesseract 3 and having it in ocrmypdf would be awesome.
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Notify maintainers

maintainers: @Kiwi @dotlambda 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by dotlambda** [comment]
Ocrmypdf uses Tesseract 5 since https://github.com/NixOS/nixpkgs/commit/d61d1ec883fa.
