### ISSUE TITLE
`python3Packages.mpi4py` fails tests with segfault on unstable

### ISSUE THREAD

**Issue by hmenke** [NixOS/nixpkgs#212220]
### Describe the bug

`python3Packages.mpi4py` fails the build, because running the tests terminates with a segfault on unstable.

```
running test
[hwloc/linux] failed to find sysfs cpu topology directory, aborting linux discovery.
[hwloc/linux] failed to find sysfs cpu topology directory, aborting linux discovery.
[1674458416.055205] [localhost:611  :0]       tcp_iface.c:816  UCX  ERROR opendir(/sys/class/net) failed: No such file or directory
[0@localhost] Python 3.10 (/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin/python3.10)
[0@localhost] MPI 3.1 (Open MPI 4.1.4)
[0@localhost] mpi4py 3.1.4 (/nix/store/va7lbji2dfwdgc1ndqzazbrip1bnvcc1-python3.10-mpi4py-3.1.4/lib/python3.10/site-packages/mpi4py)
....s........................................................................................................................................................................................................................................................................................................................ssssssssssssssssssssssss..............................................................ss...................................................................ssssssssssss............................................................sss.......................................................................................................................................................................................................s.....................................s.sss..s....s............sssssssss......ssssssssssssssssssssssssss.................ssssssssssssssssss......sss...s...s..................................................................................................................................................................s...s...............[localhost:611  :0:611] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:    611) ====
 0 0x000000000003dbf0 __GI___sigaction()  ???:0
 1 0x00000000000bf40d mca_btl_ofi_acswap()  ???:0
 2 0x0000000000207433 ompi_osc_rdma_compare_and_swap()  ???:0
 3 0x00000000000a7936 PMPI_Compare_and_swap()  ???:0
 4 0x00000000000d8d4d __pyx_pw_6mpi4py_3MPI_3Win_61Compare_and_swap()  ???:0
 5 0x00000000001dd26d method_vectorcall_VARARGS_KEYWORDS()  ???:0
 6 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
 7 0x00000000001e827f _PyEval_Vector()  ???:0
 8 0x000000000011ecd8 method_vectorcall()  ???:0
 9 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
10 0x00000000001e827f _PyEval_Vector()  ???:0
11 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
12 0x00000000001e827f _PyEval_Vector()  ???:0
13 0x000000000011ec42 method_vectorcall()  ???:0
14 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
15 0x00000000001e827f _PyEval_Vector()  ???:0
16 0x0000000000129642 _PyObject_Call_Prepend()  ???:0
17 0x000000000016ab49 slot_tp_call()  ???:0
18 0x00000000000bcc84 _PyObject_MakeTpCall.localalias()  ???:0
19 0x000000000006f42c _PyEval_EvalFrameDefault()  ???:0
20 0x00000000001e827f _PyEval_Vector()  ???:0
21 0x000000000011ec42 method_vectorcall()  ???:0
22 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
23 0x00000000001e827f _PyEval_Vector()  ???:0
24 0x0000000000129642 _PyObject_Call_Prepend()  ???:0
25 0x000000000016ab49 slot_tp_call()  ???:0
26 0x00000000000bcc84 _PyObject_MakeTpCall.localalias()  ???:0
27 0x000000000006f42c _PyEval_EvalFrameDefault()  ???:0
28 0x00000000001e827f _PyEval_Vector()  ???:0
29 0x000000000011ec42 method_vectorcall()  ???:0
30 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
31 0x00000000001e827f _PyEval_Vector()  ???:0
32 0x0000000000129642 _PyObject_Call_Prepend()  ???:0
33 0x000000000016ab49 slot_tp_call()  ???:0
34 0x00000000000bcc84 _PyObject_MakeTpCall.localalias()  ???:0
35 0x000000000006f42c _PyEval_EvalFrameDefault()  ???:0
36 0x00000000001e827f _PyEval_Vector()  ???:0
37 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
38 0x00000000001e827f _PyEval_Vector()  ???:0
39 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
40 0x00000000001e827f _PyEval_Vector()  ???:0
41 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
42 0x00000000001e827f _PyEval_Vector()  ???:0
43 0x000000000011ecd8 method_vectorcall()  ???:0
44 0x0000000000070cf2 _PyEval_EvalFrameDefault()  ???:0
45 0x00000000001e827f _PyEval_Vector()  ???:0
46 0x000000000011ecd8 method_vectorcall()  ???:0
47 0x0000000000070cf2 _PyEval_EvalFrameDefault()  ???:0
48 0x00000000001e827f _PyEval_Vector()  ???:0
49 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
50 0x00000000001e827f _PyEval_Vector()  ???:0
51 0x000000000006e5b9 _PyEval_EvalFrameDefault()  ???:0
52 0x00000000001e827f _PyEval_Vector()  ???:0
53 0x000000000006d69f _PyEval_EvalFrameDefault()  ???:0
54 0x00000000001e827f _PyEval_Vector()  ???:0
55 0x00000000000cea08 PyVectorcall_Call.localalias()  ???:0
56 0x0000000000068169 _PyEval_EvalFrameDefault()  ???:0
57 0x00000000001e827f _PyEval_Vector()  ???:0
=================================
/nix/store/8ppzfvsc14b8v1fbsyzpgi0nmmv1yjz3-setuptools-check-hook/nix-support/setup-hook: line 4:   611 Segmentation fault      /nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/bin/python3.10 nix_run_setup test
```

Complete build log: [nix.log](https://github.com/NixOS/nixpkgs/files/10477510/nix.log)

### Steps To Reproduce

```
nix build github:NixOS/nixpkgs/676c80dcc2f0ba780c8ab204f92c5abd69fa1245#python3Packages.mpi4py
```

### Expected behavior
Build succeeds.

### Screenshots
N/A

### Additional context
N/A

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-56-generic, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(henri): `"nixpkgs"`
 - nixpkgs: `/home/henri/.nix-defexpr/channels/nixpkgs`

**Comment by hmenke** [comment]
Bisected to https://github.com/NixOS/nixpkgs/commit/ef1b67da0ec3d89d2075537d34997f463f68c7a3

@bzizou

**Comment by markuskowa** [comment]
I just tried `libfabric-1.16.x`: it does not segfault, but it causes the `mpi4py` test to hang. However, with the latest version from `libfabric`'s master branch it works again.

**Comment by markuskowa** [comment]
It seems that there are at lest two problems: the segfault in the `mpi4py` test and the hanging test.
I suggest reverting the `libfabric` upgrade back to version `1.15.1` for now.
Maybe @bzizou has an idea or wants to report the issue upstream?

**Comment by bzizou** [comment]
Well, there's a bunch of ways to start openmpi, with many many options and some combinations may lead to such segfault. I see that before the backtrace, there's an UCX error about the tcp interface not found. Then, the OFI BTL seems to be used. But OFI (open fabric interface) is meant to be used on computing nodes hosting a specific network interface. I suggest trying to force the mpi4py test to use the "VADER" or "SELF" interface:
`--mca btl vader,self` or `export OMPI_MCA_btl="ofi"`
You may also try `--mca pml ob1 --mca btl tcp,vader,self` or `--mca pml ob1 --mca btl vader,self`

**Comment by markuskowa** [comment]
> Well, there's a bunch of ways to start openmpi, with many many options and some combinations may lead to such segfault.

That is true, but I think the default should just work and not segfault. You can make the tests in mpi4py pass by setting `OMPI_MCA_btl="vader,self` in its test phase, but I don't think this is a good solution. Rather should the auto-detect mechanism just work without crashing.

**Comment by hmenke** [comment]
Maybe let's start with adding `OMPI_MCA_btl="vader,self"` to the test phase to get the ball rolling and improve further at a later time if necessary.

**Comment by markuskowa** [comment]
> Maybe let's start with adding OMPI_MCA_btl="vader,self" to the test phase to get the ball rolling and improve further at a later time if necessary.

Isn't that just masking the problem? It then may just break at run time, which is could be super annoying for someone who does not know why this happens.

**Comment by markuskowa** [comment]
@hmenke I agree, that we should update libfabric at some point, but at least we have everything in a well working state right now.  IMHO that should have higher priority than updating at any cost.
I would expect that we can either find a proper solution to fix the problem or that, ideally, libfabric is fixed upstream. Is someone willing to report this issue upstream?

**Comment by hmenke** [comment]
I reported it here https://github.com/ofiwg/libfabric/issues/8450
