### ISSUE TITLE
factor: a standard working directory is set to be in /nix/store

### ISSUE THREAD

**Issue by gunnihinn** [NixOS/nixpkgs#212254]
### Describe the bug

This is a regression of [46300](https://github.com/NixOS/nixpkgs/issues/46300).

The Factor programming language sets up a repl that expects to live in a writable directory, but lives in `/nix/store` instead.

### Steps To Reproduce
1. Install the `factor-lang` package.
2. Run the first two steps of the tutorial:
```
USE: tools.scaffold
"palindrome" scaffold-work
```

Error message:
```
Unix system call “mkdir” failed:

Read-only file system (30)

It was called with the following arguments:

"/nix/store/yg965y0vqcjkqaflg1f1vwf4r4574rv5-factor-lang-0.98/..."
511
```

### Expected behavior
Factor should write to `/var/lib/factor` as per the patches in [MR 48727](https://github.com/NixOS/nixpkgs/pull/48727). That directory exists, is owned by my system user and group, and has 775 permissions.

### Notify maintainers

@vrthra @spacefrogg 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.81, NixOS, 22.11 (Raccoon), 22.11.726.04a75b2eecc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(gunnarm): `""`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by spacefrogg** [comment]
Thank you for reporting! Please have a look at #220739. For the fix.

**Comment by spacefrogg** [comment]
Fixed but not propagated here due to a hickup on github.
