### ISSUE TITLE
Update Microsoft Edge Stable to 109

### ISSUE THREAD

**Issue by jcollie** [NixOS/nixpkgs#212274]
###### Checklist

- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 107.0.1418.52
desired version: 109.0.1518.61

###### Notify maintainers

maintainers: zanculmarktum kuwii

###### Note for maintainers

Please tag this issue in your PR.

**Comment by MGlolenstine** [comment]
Closed by #218037
