### ISSUE TITLE
groff date and time registers show to 1980-1-1 1:0:0 when using nix develop

### ISSUE THREAD

**Issue by afh** [NixOS/nixpkgs#212239]
### Describe the bug
When using the date and time registers in groff with `nix develop` they show 1980-1-1 1:0:0 instead of the actual current date and time.

### Steps To Reproduce
1. 🙆 Check that the groff date registers display the current date when run in `nix shell`:
```console
% echo ".tm $(date +'%Y-%m-%dT%H:%M:%S') ~= \\\n[year]-\\\n[mo]-\\\n[dy]T\\\n[hours]:\\\n[minutes]:\\\n[seconds]" \
| nix shell nixpkgs#groff --command groff -Tutf8
2023-01-23T11:03:43 ~= 2023-1-23T11:3:43
```

2. 🙅 Verify that the groff date registers display the current date when run in `nix develop`:
```console
% echo ".tm $(date +'%Y-%m-%dT%H:%M:%S') ~= \\\n[year]-\\\n[mo]-\\\n[dy]T\\\n[hours]:\\\n[minutes]:\\\n[seconds]" \
| nix develop nixpkgs#groff --command groff -Tutf8
2023-01-23T11:03:53 ~= 1980-1-1T1:0:0
```

### Expected behavior
The date and time displayed by groff is the actual current time when using `nix develop` 

### Actual behavior
The date and time displayed by groff when run with `nix develop` is 1980-1-1 1:0:0

### Screenshots
**N/A** ~~If applicable, add screenshots to help explain your problem.~~

### Additional context
I'm uncertain whether this is an actual bug or lack of understanding of `nix` and `nix develop` in particular on my part, hence I'd appreciate any info to clear things up or that could help in identifying the underlying cause of the potential issue.

### Notify maintainers

@pSub 

### Metadata

```console
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"darwin, home-manager"`
 - channels(afh): `"darwin, home-manager, nixpkgs-22.11-darwin"`
 - nixpkgs: `/Users/afh/.nix-defexpr/channels/nixpkgs`
```

**Comment by symphorien** [comment]
Try unsetting the SOURCE_DATE_EPOCH environment variable. It is used to ensure reproducible builds.

**Comment by afh** [comment]
Thanks, @symphorien, that works very well :pray:

FWIW: The [Nixpkgs Manual](https://nixos.org/manual/nixpkgs/stable) suggests something along the lines below—which does not work verbatim for me yet `shellHook` does.

```
  postShellHook = ''
    # […]
    unset SOURCE_DATE_EPOCH
  '';
````
