### ISSUE TITLE
Packagekit not compiling with Nix-backend enabled

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#21230]
## Issue description
packagekit won't compile on my machines, fixed it for myself temporarily by disabling the nix backend. would be nice to have a working nix backend on nixos. discussion was started at https://github.com/NixOS/nixpkgs/pull/21157.

long story short:
build-error: http://hastebin.com/tiyomifipe.log (by @bendlas)
commit that probably breaks it: https://github.com/NixOS/nixpkgs/commit/c94454a45a7410f9fdd84896c693c1c4df5e10f1 (by @matthewbauer)

### Steps to reproduce
rebuild system with current master (with packagekit pulled in by anything ;) )

## Technical details
* System: 17.03.git.0b65f85 (Gorilla) (on a custom branch, where nix-backend is disabled atm - rebased on todays master)

**Comment by matthewbauer** [comment]
Yeah so I'm mostly waiting for 1.12 to hit nix stable. Hopefully won't be too much longer.

**Comment by jtojnar** [comment]
What is the status of this, @matthewbauer?

**Comment by matthewbauer** [comment]
It's on my todo list... There were some breaking changes in the Nix bindings, but I can look into fixing them now that Nix 2.0 is out.

**Comment by matthewbauer** [comment]
Would anyone else like to adopt maintainership of PackageKit? I have authored https://github.com/hughsie/PackageKit/commit/f31ab6e8636b991e867a6adcd5dc5cda521f0830 which should fix this (although it's not extensively tested). It will hopefully be released soon. Ideally someone could integrate the new ```nix search``` & its JSON db here, but I haven't looked at it.

**Comment by jtojnar** [comment]
I would be willing to maintain it, but will not be able to contribute to the further integration until later in the summer.

**Comment by benley** [comment]
Has anyone looked at this recently? I'm curious what the current state of packagekit is

**Comment by dtzWill** [comment]
Well, packagekit at least builds w/Nix these days, tested while updating to 1.1.13 but likely has built for some time now. (cc #77498).

Not sure status of packagekit service when enabling the `nix` backend (which the NixOS module presently sets to `test_noop`--somethign like [this](https://github.com/dtzWill/nixpkgs/commit/f463191d4fcac6371a89e5cec5b4590eefe276ba) should enable the right backends, for testing?)... anyone know its status?

**Comment by matthewbauer** [comment]
With Nix flakes caching support, I think we can get much better performance with this. I will work on updating this soon.

**Comment by matthewbauer** [comment]
I have a WIP branch for this here:

https://github.com/NixOS/nixpkgs/pull/94055

If you could test it out with any PackageKit clients you want to use and report back, that would be helpful!

**Comment by wmertens** [comment]
so... does that mean gnome-software actually uses nix-env now?

Can we backport this to stable?

**Comment by jtojnar** [comment]
GNOME Software is still empty – it probably depends on https://github.com/NixOS/nixpkgs/issues/15932.
