### ISSUE TITLE
Package request: Crystal

### ISSUE THREAD

**Issue by mimadrid** [NixOS/nixpkgs#21247]
I've updated a lot of packages and I've added several ones but I'm still very newbie for doing this.
I would be very grateful if someone could do it.
Thanks in advance.

https://github.com/crystal-lang/crystal: a compiled language with Ruby like syntax and type inference.
https://github.com/crystal-lang/shards: dependency manager for the Crystal language.

**Comment by sifmelcara** [comment]
Hi, I have created a nix expression for crystal compiler and I'm willing to open a pr.
But boehm-gc 7.6.0 is required for the newest version of crystal, so I have to wait until #20929 to be merged.

**Comment by mimadrid** [comment]
Awesome work @sifmelcara! 
Write me if You need help with something.
Best regards.
