### ISSUE TITLE
Understanding systemd integration in nixos

### ISSUE THREAD

**Issue by toogley** [NixOS/nixpkgs#21248]
Good afternoon :)

when i type `systemctl --version`, i receive `systemd 231`. but the last release of [our forked systemd repo](https://github.com/NixOS/systemd/releases) is `v224` - i don't understand that. Are we currently shipping the upstream version directly?

I mean, it doesn't make sense that the last systemd version on our nixos repository is **older** than what i receive via `systemctl --version`.

------------------------

Furthermoore, what are the problems regarding integrating systemd upstream version? I mean, what are the reasons why we can't ship systemd upstream version directly?

**Comment by joachifm** [comment]
A good entrypoint is https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/systemd/default.nix; the build uses a specific checkout of our systemd repo, it's just not tagged.

**Comment by toogley** [comment]
@joachifm Ah, i forgot to look into that. I guess, that means [GH:nixOS/systemd](https://github.com/NixOS/systemd) is obsolete?

**Comment by joachifm** [comment]
@toogley no, that's the repo our systemd package pulls from

**Comment by Mic92** [comment]
@toogley you can get an idea, what is required to integrate systemd into nixos by reading the commits added by @abbradar and @edolstra: https://github.com/NixOS/systemd/commits/nixos-v230

**Comment by abbradar** [comment]
@toogley If I understood your question correctly, we are just lazy in updating GitHub's default branch. There is `nixos-v231` branch in that repo.

**Comment by joachifm** [comment]
I believe the question has been answered. Please re-open if that is not the case.
