### ISSUE TITLE
herbstluftwm package fails to build in nixos-unstable

### ISSUE THREAD

**Issue by codingkoi** [NixOS/nixpkgs#212470]
### Steps To Reproduce
1. nix build -L nixpkgs/nixos-unstable#herbsluftwm
2. The build hangs at 87%

### Build log
This Hydra log matches my local logs
https://hydra.nixos.org/build/206734320/nixlog/1

### Additional context
Looking into it, it seems like the `test_rules` set of tests has started to hang for some reason. The version of the source hasn't changed so I suspect it's a dependency change that is making it hang.

### Workaround
Override the package to disable the `test_rules` test.
```nix
patchedHlwm = pkgs.herbstluftwm.overrideAttrs
    (old: { disabledTests = old.disabledTests ++ [ "test_rules" ]; });
```
I don't think this is the right long-term solution though.

### Notify maintainers
@ThibautMarty 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.3, NixOS, 23.05 (Stoat), 23.05.20230107.f6f4456`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(jshoemaker): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/2crav2vgmqs4zcypgi7z1j9yv3s0dw5f-source`
```

**Comment by ThibautMarty** [comment]
Thanks for reporting :)

**Comment by codingkoi** [comment]
Thanks for taking care of it!
