### ISSUE TITLE
Feature Request:  define firefox settings from about:config declaratively

### ISSUE THREAD

**Issue by toogley** [NixOS/nixpkgs#21244]
Hello.

[Firefox](https://github.com/NixOS/nixpkgs/blob/81428dd022c26764e9066d381ece90b1e88bd0d2/pkgs/applications/networking/browsers/firefox/wrapper.nix) provides a way of customizing it further than the settings page in the gui: When you type [about:config](http://kb.mozillazine.org/Firefox_:_FAQs_:_About:config_Entries) ([second link](http://kb.mozillazine.org/About:config)) into your browser, you can view lots of its settings - which i would love to describe declaratively via `configuration.nix`

**Comment by nico202** [comment]
If I'm not wrong, is not something nix can do, since firefox configuration is per-profile and resides under the user folder.

However, you can achieve it by following this:
http://askubuntu.com/questions/313483/how-do-i-change-firefoxs-aboutconfig-from-a-shell-script

The file `user.js` can be generated from nix with
```
pkgs.writeText "user.js" ''
configuration example
''
```

And then linked/copied to the firefox profile dir.

Correct me if I'm wrong

**Comment by toogley** [comment]
> If I'm not wrong, is not something nix can do, since firefox configuration is per-profile and resides under the user folder.
> 
> However, you can achieve it by following this:
> http://askubuntu.com/questions/313483/how-do-i-change-firefoxs-aboutconfig-from-a-shell-script
> 
> The file `user.js` can be generated from nix with
> ```
> pkgs.writeText "user.js" ''
> configuration example
> ''
> ```
> 
> And then linked/copied to the firefox profile dir.
> 
> Correct me if I'm wrong

I missed that feature, so thank you. I'll try it the next weeks or so.

**Comment by jtojnar** [comment]
On Ubuntu there is `/usr/lib/firefox/browser/defaults/preferences/syspref.js`, not sure what is an equivalent on NixOS.

**Comment by jtojnar** [comment]
Apparently, Firefox only reads the default preferences from `/usr/lib/firefox` making the configuration change impossible without recompiling Firefox. There exists a patch but it was not accepted very warmly, see [bug 1170092](https://bugzilla.mozilla.org/show_bug.cgi?id=1170092). We could apply the patch locally, as RHEL probably does; it would not be very useful for `-bin` packages, though.

**Comment by joachifm** [comment]
See the tor browser bundle for an idea of how to do this: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/tor-browser-bundle/default.nix#L134

**Comment by oxij** [comment]
I'd say it needs to be done in `firefoxWithPackages`. So, this is related to #15959.

**Comment by xaverdh** [comment]
On a related note, there is policies.json.
https://support.mozilla.org/en-US/kb/customizing-firefox-using-policiesjson
https://github.com/mozilla/policy-templates/
This is kept in the install directory, so it might be easier to nixify.

**Comment by offlinehacker** [comment]
That was probably the only missing piece, why I was using chromium, declarative policies. I didn't know they exist in Firefox.

**Comment by xaverdh** [comment]
Policies seem to be rather experimental still.
Another (older?) option seems to be
https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig

**Comment by joachifm** [comment]
@xaverdh see the issue linked above for discussion of such a solution.

**Comment by xaverdh** [comment]
Hmm. Unlike the tor-browser-bundle, the standard firefox wrapper does not have an extraPrefs option as far as I can see.

**Comment by anund** [comment]
Looks like [programs.firefox.preferences](https://search.nixos.org/options?channel=22.11&show=programs.firefox.preferences&from=0&size=50&sort=relevance&type=packages&query=firefox) and [programs.firefox.policies](https://search.nixos.org/options?channel=22.11&show=programs.firefox.policies&from=0&size=50&sort=relevance&type=packages&query=firefox) are in nixpkgs. Home-manager has more options starting at [programs.firefox.enable](https://rycee.gitlab.io/home-manager/options.html#opt-programs.firefox.enable)

```nix
  programs.firefox = {
    enable = true;
    preferences = {
      # force hardware decoding
      "media.ffmpeg.vaapi.enabled" = true;
      "gfx.webrender.all" = true;
    };
  };
```

https://github.com/nix-community/home-manager/issues/606 has more discussion on the topic. 

I believe this issue can be closed.

**Comment by jtojnar** [comment]
Or if you want to stick with Nixpkgs, you can override the wrapper arguments:

```nix
pkgs.firefox.override (args: args // {
  cfg = args.cfg or {} // {
    enableGnomeExtensions = true;
  };

  extraPrefs = ''
    // Downloading random PDFs from http website is super annoing with this.
    lockPref("dom.block_download_insecure", false);

    // Always use XDG portals for stuff
    lockPref("widget.use-xdg-desktop-portal.file-picker", 1);

    // Enable userChrome.css
    lockPref("toolkit.legacyUserProfileCustomizations.stylesheets", true);

    // Avoid cluttering ~/Downloads for the “Open” action on a file to download.
    lockPref("browser.download.start_downloads_in_tmp_dir", true);
  '';
});
```
