### ISSUE TITLE
libreoffice: No package 'mdds-2.0' found

### ISSUE THREAD

**Issue by toastal** [NixOS/nixpkgs#212556]
### Steps To Reproduce
1. build libreoffice-fresh off master

### Build log
```
checking for mdds-2.0 >= 2.0.0... no
configure: error: Package requirements (mdds-2.0 >= 2.0.0) were not met:

No package 'mdds-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables MDDS_CFLAGS
and MDDS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.7, NixOS, 23.05 (Stoat), 23.05.20230125.dirty`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(toastal): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by JeffreyBenjaminBrown** [comment]
Is this issue closed because it is solved? It's still happening to me. I'm using the `nixos-unstable` channel. If I include `libreoffice` in my config, `nixos-rebuild` fails with the message `No package 'mdds-2.0' found`. If I exclude `libreoffice` from my config, rebuilding succeeds.

**Comment by wegank** [comment]
Yes, it's just that the commit hasn't arrived yet at nixos-unstable, see [here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/mdds/default.nix).
