### ISSUE TITLE
Packaging request for csvq

### ISSUE THREAD

**Issue by maxmoehl** [NixOS/nixpkgs#212595]
**csvq**
From the homepage:
> Csvq is a command line tool to operate CSV files. You can read, update, delete CSV records with SQL-like query.
> 
> You can also execute multiple operations sequentially in managed transactions by passing a procedure or using the interactive shell. In the multiple operations, you can use variables, cursors, temporary tables, and other features.

**Metadata**

* homepage URL: https://mithrandie.github.io/csvq/
* source URL: https://github.com/mithrandie/csvq
* license: mit
* platforms: unix, linux, darwin, bsd, netbsd, openbsd, (windows)

**Note**

I'm just getting started with nix and don't have a lot of experience with the nix DSL. If I find time I could look into this myself but some pointers where to start when submitting new packages are appreciated. If someone else is interested in doing this, that's also fine for me (and will probably be a lot quicker :smile:)

**Comment by tomodachi94** [comment]
@maxmoehl beat you to it! The PR is #212722.
