### ISSUE TITLE
Fix gmic-qt 3.2.0 build

### ISSUE THREAD

**Issue by NinjaTrappeur** [NixOS/nixpkgs#212563]
We broke gmic-qt during the https://github.com/NixOS/nixpkgs/pull/211600 bump.

After contacting upstream, it seems like the cmake build is not maintained anymore: https://github.com/c-koi/gmic-qt/issues/171#issuecomment-1403332887. They migrated to `qmake`.

We should align with them and rewrite a qmake derivation for gmic-qt.

Edit: jtojnar advise not to migrate to qmake but instead fix the cmake issue.

**Comment by PowerUser64** [comment]
Any idea what I can do so I can build my system while this is a WIP?

**Comment by ShivanshuKantPrasad** [comment]
Install the build from an older version of nixpkgs where the package you want still builds properly. The version in `22.11` branch should be building properly.

https://nixos.wiki/wiki/Flakes#Importing_packages_from_multiple_channels

**Comment by PowerUser64** [comment]
Thank you so much!! That section of the wiki described exactly what I was trying to do!

**Comment by lilyinstarlight** [comment]
I just posted an upstream PR to fix this: https://github.com/c-koi/gmic-qt/pull/174

**Comment by lilyinstarlight** [comment]
I've opened #218074 with a proper fix if anyone here would like to do some testing (it works for me now)
