### ISSUE TITLE
postgres: call initdb on macOS

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#21253]
## Issue description
On macOS initdb is not called when postgres is installed. You have to do this manually. It'd be nice if nix could do this for you. I suspect this is related to #21252 as it would make more sense to call initdb if we could install a service definition.

**Comment by knedlsepp** [comment]
I actually don't think this would be expected behaviour of an installation of postgres. Additionally I don't think this happens on a Linux+nix installation either. This seems like a non-issue to me.

**Comment by mmahut** [comment]
Are there any updates on this issue, please?

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
