### ISSUE TITLE
nixos-rebuild overrides configuration.nix with weird XML 404 garbage

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#212614]
### Describe the bug

When I run `sudo nixos-rebuild switch` or `sudo nixos-rebuild test`, my `/etc/nixos/configuration.nix` gets completely overridden with the following content:

```
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

### Steps To Reproduce

Two main things that are probably important:
- I'm running on Amazon AWS machine.
- I'm pinning nixpkgs

My `configuration.nix`:

```
{ config, pkgs, lib, ... }:

let
  nixpkgs = import ../nixpkgs.nix;
in {
  imports = [
    <nixpkgs/nixos/modules/virtualisation/amazon-image.nix>
  ];

  # A workaround:
  # https://github.com/NixOS/nixpkgs/issues/62824#issuecomment-516369379
  boot.loader.grub.device = lib.mkForce "/dev/nvme0n1";

  ec2 = {
    hvm = true;
    efi = false;
  };

  system.stateVersion = "18.09";  # NOTE: Never edit this!

  # Put the pinned nixpkgs under /etc/nixpkgs so we can point to /etc/nixpkgs
  # and it'll update where it points to.
  environment.etc = {
    nixpkgs = {
      source = nixpkgs;
    };
  };

  networking.firewall.enable = true;

  security.sudo.wheelNeedsPassword = false;

  services.openssh = {
    enable = true;
    openFirewall = true;
    passwordAuthentication = false;
  };

  users = { ...... };

  environment.systemPackages = with pkgs; [
    vim
    git
  ];
}
```

And the file `../nixpkgs.nix` that is imported:

```
builtins.fetchTarball {
  name = "my-nixpkgs";
  # nixos-unstable branch Jan 10, 2023
  url = "https://github.com/NixOS/nixpkgs/archive/c07552f6f7d4eead7806645ec03f7f1eb71ba6bd.tar.gz";
  sha256 = "sha256:1lw6wa6akj16ia6jjqb9dhq0yx6rkxzzqsb2bjh3r3f7s138bl0q";
}
```

Then, run `sudo nixos-rebuild switch`

### Expected behavior

I've had this kind of setup for a few years now and it has worked. After I changed the pinned `nixpkgs`, it broke.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.86, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(root): `"nixos-19.09pre174426.acbdaa569f4"`
 - channels(arttu): `""`
 - nixpkgs: `/etc/nixpkgs`
```

**Comment by jluttine** [comment]
I got it fixed by running:

```
nixos-rebuild -I nixpkgs=/etc/nixpkgs switch
```

After that, the system was updated properly and I was able to continue using `nixos-rebuild switch` as before.

I don't really know why the original issue happened and why this solved. Perhaps this issue can be closed but I'll leave it open in case someone wants to check if there was an actual bug somewhere in nixpkgs.

**Comment by superherointj** [comment]
> I got it fixed by running:
> 
> ```
> nixos-rebuild -I nixpkgs=/etc/nixpkgs switch
> ```
> 
> After that, the system was updated properly and I was able to continue using `nixos-rebuild switch` as before.
> 
> I don't really know why the original issue happened and why this solved. Perhaps this issue can be closed but I'll leave it open in case someone wants to check if there was an actual bug somewhere in nixpkgs.

As no further work is necessary, ideally it should be closed. Search also lists closed issues.

**Comment by nixinator** [comment]
that;s really really weird....if nixos was a city, this would be 'weird city'.

can you make it do it again?

**Comment by raphaelr** [comment]
I have a suspicion but I don't have an aws account to verify.

1. The [ec2-metadata-fetcher.sh](https://github.com/NixOS/nixpkgs/blob/34ab27401705b3eb62fa1e3bf3d81c6e664b864e/nixos/modules/virtualisation/ec2-metadata-fetcher.sh) (invoked by [azure-image.nix](https://github.com/NixOS/nixpkgs/blob/34ab27401705b3eb62fa1e3bf3d81c6e664b864e/nixos/modules/virtualisation/amazon-image.nix#L76-L83) uses curl to [download a "user-data" file](https://github.com/NixOS/nixpkgs/blob/34ab27401705b3eb62fa1e3bf3d81c6e664b864e/nixos/modules/virtualisation/ec2-metadata-fetcher.sh#L65) from an AWS infrastructure server.
2. amazon-init.nix (also imported by amazon-image.nix) then tries to interpret that file as provisioning data. If it [matches a certain regex](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/amazon-init.nix#L29-L33), then it [copies](https://github.com/NixOS/nixpkgs/blob/34ab27401705b3eb62fa1e3bf3d81c6e664b864e/nixos/modules/virtualisation/amazon-init.nix#L45) that file to /etc/nixos/configuration.nix

If the file downloaded in step 1 is a 404, then this can result in /etc/nixos/configuration.nix to contain a 404 error message. So setting `virtualisation.amazon-init.enable = false;` could be a workaround. If this is really the root casue of the problem, then I assume AWS changed something that makes the ec2-metadata-fetcher.sh script fail now.

**Comment by nixinator** [comment]
Ok, that makes perfect sense, but blimey, it could probably do with some error checking that if it fails it should abort. Network resources are never guaranteed  to be available....

**Comment by samueldr** [comment]
Closing as fixed, if my understanding of the linked PR and issue is proper.

Feel free to re-open if the PR wasn't a solution to this problem.
