### ISSUE TITLE
Documentation about single-user mode and read-only /nix/store

### ISSUE THREAD

**Issue by lethalman** [NixOS/nixpkgs#2126]
It says to `chgrp nixbld /nix/store`, but this is not possible because /nix/store is mounted read only.

**Comment by Profpatsch** [comment]
(triage) still an issue?

**Comment by siddharthist** [comment]
Here's the multi-user documentation: https://github.com/NixOS/nix/blob/312bab008d835dd9c8939b803d2bc7af4f82a811/doc/manual/installation/multi-user.xml
and here's the single-user documentation: https://github.com/NixOS/nix/blob/312bab008d835dd9c8939b803d2bc7af4f82a811/doc/manual/installation/single-user.xml

The single-user documentation still contains this phrase, which I believe is an example of the problem:
> In single-user mode, all Nix operations that access the database in prefix/var/nix/db or modify the Nix store in prefix/store must be performed under the user ID that owns those directories. This is typically root. (If you install from RPM packages, that’s in fact the default ownership.) However, on single-user machines, it is often convenient to chown those directories to your normal user account so that you don’t have to su to root all the time.

**Comment by Profpatsch** [comment]
(triage) and now? :)
