### ISSUE TITLE
Python: function to remove requirements.txt/setup.py constraints

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#21278]
## Issue description

Python developers often pin their dependencies to exact versions. This is bad practice and most of the times absolutely not necessary either.

Typically we use `substituteInPlace` to remove the dependency requirement. It would be useful to have a function that would strip such exact requirements.

I've also opened an issue at setuptools with a request for a flag that ignores version pinning.
https://github.com/pypa/setuptools/issues/894

**Comment by FRidh** [comment]
Example why we should have this: https://github.com/NixOS/nixpkgs/pull/21321/files

**Comment by johbo** [comment]
I can see the need in regards to the setup.py file. I've myself sometimes patched away a specific version pinning in a setup.py.

How do you see the use related to a requirements.txt file? Wouldn't this typically be used in a scenario to generate nix code e.g. via pip2nix or pypi2nix?

**Comment by FRidh** [comment]
Actually, many developers wrongly load the `requirements.txt` file and add the items to `install_requires`. Therefore, a method to just filter the `install_requires` and `setup_requires` values should be sufficient.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by FRidh** [comment]
Reading https://github.com/pypa/setuptools/issues/894 again. The `buildPhase` will produce a wheel, and that will contain the constraints (in METADATA, the Requires-Dist rows). We can thus fix it at our side by patching the wheel. Would also need to fix then the hash for METADATA in RECORD. The are tools to manipulate wheels. This can be implemented in a hook.

**Comment by danbst** [comment]
continuing my line of though with `sed` patching, I came with following hook:
```
function pythonJailbreak {
    local file="$1"; shift

    for dep in $@; do
        if [[ "$file" =~ requirements*.txt ]]; then
            sed -r -i "s/$dep[><=].*?/'$dep'/g" $file
        else
            sed -r -i "s/['\"]$dep[><=].*?['\"]/'$dep'/g" $file
        fi
    done
}

function toJailbreak {
    local file="$1"
    if [[ "$file" =~ requirements* ]]; then
        sed -rn "s/([a-zA-Z0-9+-]+)[><=].*/\1/p" $file
    else
        sed -rn "s/.*['\"]([a-zA-Z0-9_-]+)[><=].*['\"].*/\1/p" $file
    fi
}

function jailbreakHook {
    if [[ "$doJailbreak" != "false" ]]; then
        if [ -f setup.py ]; then
            pythonJailbreak setup.py $(toJailbreak setup.py)
        fi
        for reqtxt in $(ls -d requirements*.txt); do
            pythonJailbreak "$reqtxt" $(toJailbreak $reqtxt)
        done
    fi
}
```
It jailbreaks ~95% of dependencies for apache-airflow, so is not "production-grade", but package is built and tested fine.

**Comment by Artturin** [comment]
Added by https://github.com/NixOS/nixpkgs/pull/170813
