### ISSUE TITLE
rpcemu

### ISSUE THREAD

**Issue by danwdart** [NixOS/nixpkgs#212790]
**Project description**
RiscPC Emulator

**Metadata**

* homepage URL: https://www.marutan.net/rpcemu/index.php
* source URL: https://www.marutan.net/rpcemu/cgi/download.php?sFName=0.9.4/rpcemu-0.9.4.tar.gz
* license: gpl2
* platforms: linux, darwin

This also includes ROM images which could also be downloaded, as ROOL maintains these on an open source licence. Not sure the best idea for these... /var/lib?

Thanks very much for all your hard work.

**Comment by AndersonTorres** [comment]
Builds and compiles. I will upload it tomorrow

**Comment by AndersonTorres** [comment]
The roms are mostly optional, in the sense the software will seek them in `./roms/`. There is no such a need for include them now.

**Comment by danwdart** [comment]
Thanks very much.

**Comment by daemonspudguy** [comment]
@AndersonTorres how did you get it to work? I can't get it to recognize the existence of the hostfs folder.

**Comment by danwdart** [comment]
Nor could I, now that I return to it.
I also only see the rpcemu-interpreter rather than recompiler file. Something to do with it, perhaps?

**Comment by danwdart** [comment]
Aha, it seems that the distribution packaged for other systems in rpcemu did not include the poduleroms directory with the hostfs driver. Copy the windows distribution's directory from its zip file into the root of your extracted directory. This is clearly their oversight, not the packager's.

cc @daemonspudguy
