### ISSUE TITLE
Zim broken (maybe other Python apps)

### ISSUE THREAD

**Issue by zarelit** [NixOS/nixpkgs#21270]
## Issue description

When I start zim it complains with a popup error "failed running: <directory>" with the current working directory.

It happens both on NixOS and Nix on Arch (so release-16.09 and unstable).

I bisected this regression finding that 787d61d5c712ef3f63d779d1d88b6b805e827c82 is the first bad commit

**Comment by FRidh** [comment]
Short answer: `zim` doesn't work because nobody maintains it.

Long answer: `wrapPythonPrograms` is now handled by `mkPythonDerivation` which `buildPythonApplication` calls. This expression calls `wrapPythonPrograms` again, but it shouldn't.
