### ISSUE TITLE
buildah: fails to create containers since the switch to `netavark` network stack

### ISSUE THREAD

**Issue by NickCao** [NixOS/nixpkgs#212728]
### Describe the bug
buildah fails to find binaries required for the `netavark` network stack.

### Steps To Reproduce
1. ensure `virtualisation.podman.enable` is set
2. `$ buildah from alpine:edge`
3. ``Error: could not find "netavark" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.``

### Additional context
https://github.com/NixOS/nixpkgs/pull/199965

### Notify maintainers
@zowoq

**Comment by zowoq** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/212751.

**Comment by NickCao** [comment]
Confirms it does fix this issue.
