### ISSUE TITLE
Parted 3.2 not building on Hydra anymore

### ISSUE THREAD

**Issue by aristidb** [NixOS/nixpkgs#21281]
## Issue description

Parted fails to run some of the device-mapper tests. Until now, they have always been skipped due to not running as they were not run with uid 0. Unstable Nix seems to use user namespaces with uid 0.

See the log here: http://hydra.nixos.org/build/45093914/nixlog/1
It's causing multiple builds like this to fail: http://hydra.nixos.org/build/45093914

Similar issue: #21145

### Steps to reproduce

Build parted with unstable nix, using the user namespaces rather than the traditional chroot.

## Technical details

hydra.nixos.org

**Comment by vcunat** [comment]
I personally hope for improving the Hydra setup instead of fixing up all those packages individually.

**Comment by aristidb** [comment]
@vcunat Parted seems to be the only thing failing in Nixos Unstable right now.

**Comment by grahamc** [comment]
There are over 1,200 failing builds, aristidb. +7,000 more if we add tests back to pytest.

**Comment by vcunat** [comment]
All those mass failures remain in staging.  I think many of the unstable packages are not possible to rebuild on Hydra anymore.

**Comment by grahamc** [comment]
@vcunat staging hasn't seen a mass rebuild recently, so many things are invisibly broken over there.

**Comment by vcunat** [comment]
[>15k failures](http://hydra.nixos.org/eval/1314532) seem enough to me.  There's been a coreutils bump (which I managed to revert on master).

**Comment by grahamc** [comment]
Sorry, I was looking at nixos:staging: https://hydra.nixos.org/jobset/nixos/staging

**Comment by vcunat** [comment]
Oh, I tend to forget about that jobset, as we've only had it for a few months.

**Comment by aristidb** [comment]
nixos-unstable-small succeeds now, and that's what I use, but I guess until the uid issues are figured out, this is still a bit of a time bomb.
