### ISSUE TITLE
Lies on https://nixos.org/nixpkgs/download.html

### ISSUE THREAD

**Issue by spy-tech** [NixOS/nixpkgs#21284]
https://nixos.org/nixpkgs/download.html states:

```
Note: if you are a NixOS user, you already have Nixpkgs. You can update your copy of Nixpkgs to the latest version by running nixos-checkout.
```

I observe:
```
nixos-checkout
nixos-checkout: command not found
```

I expected: 

At the very least that nixos-checkout was found and executed.

**Comment by joachifm** [comment]
`nixos-checkout` was removed in 25387a1bedefb391db9f8585cfa1d160fc3bacfe.

I very much doubt the intent was deception.

The source for nixos.org is hosted elsehwere, however; please open an issue against the correct repository.
