### ISSUE TITLE
trash-cli || TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'

### ISSUE THREAD

**Issue by Schweber** [NixOS/nixpkgs#212817]
### Describe the bug
Running `trash-restore` yields

```
~ ❯ trash-restore
Traceback (most recent call last):
  File "/nix/store/r2y30jfi20krkf2dplf5cj1mvx7j2qbw-trash-cli-0.22.10.20/bin/.trash-restore-wrapped", line 6, in <module>
    sys.exit(main())
  File "/nix/store/r2y30jfi20krkf2dplf5cj1mvx7j2qbw-trash-cli-0.22.10.20/lib/python3.10/site-packages/trashcli/restore.py", line 117, in main
    ).run(sys.argv)
  File "/nix/store/r2y30jfi20krkf2dplf5cj1mvx7j2qbw-trash-cli-0.22.10.20/lib/python3.10/site-packages/trashcli/restore.py", line 307, in run
    trashed_files = sorted(trashed_files,
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

It used to work before, i don't know why it doesn't anymore.

### Steps To Reproduce
1. install `trash-cli`
2. run `trash-restore`

### Expected behavior
Showing a list of the files in trash with index numbers for selecting them to be restored.

### Notify maintainers

@rycee 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by Schweber** [comment]
@rycee I don't know if you've been pinged because the section was commented out when first posting the issue.

**Comment by rycee** [comment]
Interesting, I don't think this has anything to do with the packaging in Nixpkgs and is some upstream issue. I created a above bug report in the trash-cli project and we'll see what they say.

In any case, I tried running `trash-restore` from latest Nixpkgs unstable and it seems to work for me. The

    TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'

error seems to me like it could be caused by a failure to parse the deletion date.

Could you try running `trash-restore --sort none` and see what it prints?

**Comment by Schweber** [comment]
Thank you for reporting the issue. I didn't know that it wasn't a problem with the nix package, sorry.

Running `trash-restore --sort none` works so it seems that you are right in your bug report that `trash-cli` can't handle some files in my trash bin.
