### ISSUE TITLE
Outdated package: jetbrains.idea-ultimate

### ISSUE THREAD

**Issue by jamesward** [NixOS/nixpkgs#212996]
###### Checklist
- [X] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `legacyPackages.x86_64-linux.jetbrains.idea-ultimate`
current version: `2022.3.1`
desired version: `2022.3.2`

###### Notify maintainers
maintainers:
@edwtjo
@gytis-ivaskevicius
@steinybot
@AnatolyPopov

###### Note for maintainers

Please tag this issue in your PR.

**Comment by fabianhjr** [comment]
For future reference, it is relatively easy to do that update. (Just run `pkgs/applications/editors/jetbrains/update.py` on the root of the nixpkgs repo)

**Comment by jamesward** [comment]
Thanks! Noob question: Is there anything else I need to do to get this into unstable?

**Comment by fabianhjr** [comment]
It should be there a long time ago (4 days at least)

**Comment by jamesward** [comment]
Thanks! Sure enough. I didn't realize I had to do a `sudo nix-channel --update` (likely due to how I use unstable for this package) instead of just the usual `sudo nixos-rebuild switch --upgrade`

Really appreciate the help!
