### ISSUE TITLE
Package request: nix-gui

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#212959]
**Project description**
Nix-Gui is a tool which loads data including option paths, option types, default values, configured values, descriptions, etc. The option hierarchy is made explorable and the value of individual options are editable. Changes are committed by writing to modules within the configuration path. It makes NixOS usable for non-technical users through a settings / package management GUI.

**Metadata**

* homepage URL:[nix-gui/nix-gui](https://github.com/nix-gui/nix-gui)
* source URL: [nix-gui/nix-gui](https://github.com/nix-gui/nix-gui)
* license: mit
* platforms: unix, linux, darwin

**Comment by peterhoeg** [comment]
Considering this is a nix tool, once upstream thinks it's ready, I'm sure they will get it packaged here.

**Comment by sogreatandpowerfull** [comment]
Good point!
