### ISSUE TITLE
Outdated package: gnomeExtensions.material-shell (unstable)

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#212964]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: legacyPackages.x86_64-linux.gnomeExtensions.material-shell

current version: 28
desired version: 31

###### Notify maintainers

maintainers: @piegamesde

###### Note for maintainers

Please tag this issue in your PR.

**Comment by piegamesde** [comment]
Should be fixed by #212666
