### ISSUE TITLE
Bypass cache.nixos.org for huge packets.

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21297]
## Issue description

Download from ```cache.nixos.org``` works very slow from some locations such as Russia (under 1Mbps on 100Mbps connection), so huge binary packages such as JDK, Google Fonts, Intellij IDEA require about an hour for download. (```nix-cache.s3.amazonaws.com``` is a bit faster but often drops the connection).

Ironicaly, all of these packages can be downloaded quickly from their fast Oracle's and Google's servers and they do not require CPU intensive compilation nor downloading of GCC.

I propose to add option to avoid using ```cache.nixos.org``` and ```tarballs.nixos.org``` for such packages and always download them from the original webserver and go through the build process.

**Comment by Mic92** [comment]
Currently cache.nixos.org is powered by  Amazon's Cloudfront. Is this service bound to regions?
If yes, Is it maybe possible to extend this?

**Comment by abbradar** [comment]
If you are accessing cache.nixos.org from Russia you may be interested in [a mailing list thread on that](http://lists.science.uu.nl/pipermail/nix-dev/2016-October/022021.html).

**Comment by volth** [comment]
@abbradar I saw it, and wanted to reply in the mailing list but I found no way how to reply to the old messages, which were sent before I subscribed to the mailing list.

```cache.nixos.org``` is not blocked by my ISP. The closest Cloudflont's edge is in London (which is far away) and someone (my ISP, cloudfront or a transit provider) throttles the international bandwidth. May be it has sense to add an extra mirror on another CDN (for instance CloudFlare [tolerates 400Tb/month on the free tariff plan](https://blog.opengem.org/2016/december-1st-update/) and has much more edges than Cloudfront).
Anyway, "caching" huge files which are already on Google's CDN could be avoided.

**Comment by vcunat** [comment]
There [should be some](https://aws.amazon.com/cloudfront/details/) geographically closer one's than London, but I guess Sweden/Poland/... still aren't "close enough".

**Comment by volth** [comment]
@vcunat London is what I saw on ```traceroute```. Ability to explicitly choose the mirror (like ```se.archive.ubuntu.com``` for Sweden) would be a nice addition as well.

**Comment by volth** [comment]
Another posible improvement of cached packages distribution would be using P2P technologies (BitTorrent or DC++).
This would be good also for local networks with many NixOS instances. They would download caches from each other instead of each one of them download directly from ```cache.nixos.org```.

**Comment by vcunat** [comment]
Yes, there have been discussions about IPFS in particular, but no P2P is really deployed now AFAIK.
