### ISSUE TITLE
add devcontainer cli 

### ISSUE THREAD

**Issue by behrica** [NixOS/nixpkgs#213018]
**Project description**
devcontainer CLI, which can take a devcontainer.json and create and configure a dev container from it.

**Metadata**

* homepage URL: https://github.com/devcontainers/cli
* source URL: https://github.com/devcontainers/cli
* license: MIT
* platforms: unix

**Comment by behrica** [comment]
Thanks for taking care.
I am a newby in both Nix and NodeJS.
Nevertheless I am interested in Nix and could maybe help in the testing of the nix package.

**Comment by behrica** [comment]
seems to work well.

**Comment by sikmir** [comment]
Done in #301313
