### ISSUE TITLE
Package request: blox

### ISSUE THREAD

**Issue by spy-tech** [NixOS/nixpkgs#21304]
Blox provides container management and orchestration on Amazon ECS:

See: https://blox.github.io/

**Comment by jgeerds** [comment]
only `ecs-cli` ?

**Comment by spy-tech** [comment]
@jgeerds No, all components.

**Comment by FRidh** [comment]
Thanks for your request. If you like to get a package in, then the best approach would be to roll up your sleeves and open a PR! :) People on this tracker and the NixOS IRC channel are typically quite willing to help out, and especially when discussing a PR.
