### ISSUE TITLE
cloudflare-warp isn't working

### ISSUE THREAD

**Issue by ewwhash** [NixOS/nixpkgs#213177]
### Describe the bug
cloudflare-warp client is not working, neither wgcf is. It works in docker vm, so it's clearly a problem with managing DNS/nixos-fw. 
filestat /etc/resolv.conf is not changed at all, but on other distros it does. 
CloudflareWarp adapter isn't exist, and warp-svc says that network is unreachable. However, the RUST_BACKTRACE=debug hasn't enough information to properly identify the problem
ip route is still points to default gateway
iptables -vnL has 0.0.0.0/0 in every chain, but in other distros it creates firewall rules 

### Steps To Reproduce

1. /etc/nixos/configuration.nix
networking.nameservers = [ "1.1.1.1" "1.1.0.1" ];
services.resolved.enable = false;
networking.networkmanager.dns = "none";
environment.systemPackages = with pkgs; [cloudflare-warp nft]
2. sudo warp-svc && warp-cli register && warp-cli connect
3. warp-svc points that network is unreachable 

### Expected behavior
warp-svc should change the DNS and ip route, CloudflareWarp tun adapter should exist,

### Notify maintainers
@WolfangAukang

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.88, NixOS, 23.05 (Stoat), 23.05pre444846.d7705c01ef0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(chebuya): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by drishal** [comment]
exactly the same issue here, used to work before with just using 
```nix
 environment.systemPackages = with pkgs; [cloudflare-warp];
 systemd.packages = with pkgs; [ cloudflare-warp ];
  ```
  
  Now the systemd service no longer works

**Comment by WolfangAukang** [comment]
@drishal Can you test it with [this module](https://github.com/NixOS/nixpkgs/pull/168092#issuecomment-1432710743)? I have it working just fine, or at least I am getting `warp=on` on my device.
@BrightYC To be honest, I never used these options you indicate together with Cloudflare Warp, so I have no idea on how to proceed here. If you have any recommendations, I can gladly help.

**Comment by jeslinmx** [comment]
Any chance you could upload your `journalctl -u warp-svc`?

**Comment by drishal** [comment]
> @drishal Can you test it with [this module](https://github.com/NixOS/nixpkgs/pull/168092#issuecomment-1432710743)? I have it working just fine, or at least I am getting `warp=on` on my device. @BrightYC To be honest, I never used these options you indicate together with Cloudflare Warp, so I have no idea on how to proceed here. If you have any recommendations, I can gladly help.

Unfortunately for now I switched back to arch Linux a few weeks back since nix had completrly broken mesa and vaapi on my system after an upgrade 😅

**Comment by jeslinmx** [comment]
`cloudflare-warp` seems to now be working for me out of the box without any custom modules/configuration, or calling `sudo warp-svc` manually. Not sure when this was fixed, but thanks!

**Comment by muneebusmani** [comment]
> ```nix
>  systemd.packages = with pkgs; [ cloudflare-warp ];
> ```

how do you run and connect to warp? i tried but i have to manually run sudo warp-svc, which i absolutely hate to do, any proper solution yet?

**Comment by muneebusmani** [comment]
> `cloudflare-warp` seems to now be working for me out of the box without any custom modules/configuration, or calling `sudo warp-svc` manually. Not sure when this was fixed, but thanks!

**Comment by jeslinmx** [comment]
In your `configuration.nix`,

```
  environment.systemPackages = [ pkgs.cloudflare-warp ]; # for warp-svc
  systemd.packages = [ pkgs.cloudflare-warp ]; # for warp-cli
  systemd.targets.multi-user.wants = [ "warp-svc.service" ]; # causes warp-svc to be started automatically
```

Then all you will need to do is `warp-cli connect` as an ordinary user.

**Comment by muneebusmani** [comment]
@ewwhash i think you should mark this as closed as the solution is here:


> In your `configuration.nix`,
> 
> ```
>   environment.systemPackages = [ pkgs.cloudflare-warp ]; # for warp-svc
>   systemd.packages = [ pkgs.cloudflare-warp ]; # for warp-cli
>   systemd.targets.multi-user.wants = [ "warp-svc.service" ]; # causes warp-svc to be started automatically
> ```
> 
> Then all you will need to do is `warp-cli connect` as an ordinary user.

**Comment by jeslinmx** [comment]
Is there any interest to implement this as a module so we can simply do `services.cloudflare-warp.enable`?

**Comment by muneebusmani** [comment]
not yet

**Comment by treyfortmuller** [comment]
Now that https://github.com/NixOS/nixpkgs/pull/321142 is merged I think we're in good shape to close this issue. Happy to follow up if you run into any issues with the new module @ewwhash @jeslinmx

**Comment by pxp9** [comment]
Hi, I got one issue,

Does anyone know what it is happening with warp-taskbar ?

![image](https://github.com/user-attachments/assets/a06d7efc-e7d4-481c-ad1e-33be2c2ededa)

I tried to open it but it crashed because of GTK

**Comment by pxp9** [comment]
I am running Nixos 24 branch unstable

**Comment by jeslinmx** [comment]
I am also getting crashes but with a massive core dump. But maybe we should take this up in a different issue.

![image](https://github.com/user-attachments/assets/6638453a-22a3-4b8f-884d-1bb60046806d)
![image](https://github.com/user-attachments/assets/d481215e-a219-46d8-a553-5c47f354d8a7)
![image](https://github.com/user-attachments/assets/eecf8b77-f91d-4bf5-85f1-e7115238c87c)
![image](https://github.com/user-attachments/assets/25be187d-ef69-4f4c-9547-6263e4b80fac)
![image](https://github.com/user-attachments/assets/7f7d7451-1a29-4331-b6e0-8cefa3c790aa)
![image](https://github.com/user-attachments/assets/4d90288d-9ccd-4fb4-b62f-d11dc76a3888)
![image](https://github.com/user-attachments/assets/bf2c5836-b3d0-4dd7-947e-1976399b1e6f)
![image](https://github.com/user-attachments/assets/004bfce1-480e-49f5-a8e0-73cd102bf81a)
![image](https://github.com/user-attachments/assets/7c86c319-14f4-4c4f-b4d1-63e435e35ee1)
![image](https://github.com/user-attachments/assets/f8bde9d1-a0be-4a04-9236-518e9ebb7ff6)

**Comment by musjj** [comment]
Are there any perquisites for the service to work? I enabled it, but https://one.one.one.one/help stills shows `No` for every entry.

I'm also getting this error, not sure if it's relevant:

```
Aug 11 23:36:26 $HOST warp-svc[1115]: 2024-08-11T16:36:26.383Z ERROR warp::root_ca: This OS does not support custom root CA management
```

**Comment by marcusramberg** [comment]
For the warp-taskbar, you'll need to be using the provided user systemd service, see https://github.com/NixOS/nixpkgs/pull/323580 . @musjj even after enabling the cloudflare-warp service you'll need to connect with warp-cli or using the taskbar menu. (and register with your zero trust org if you're using it as a zero trust client.) I think this issue should be closed in favor of more specific issues with the package/module.

![image](https://github.com/user-attachments/assets/36f95ad4-85d2-4456-abca-0d856f70286d)

**Comment by pxp9** [comment]
new issue created so this issue can be closed.
