### ISSUE TITLE
Add support for Cinnamon|Maui

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#2132]
Hello, 

A time ago I left Nixos and stopped with Cinnamon. 
If there is no problems. I would like to give it another try. 

Also I would like to try to make this work : http://www.maui-project.org 

Roelof

**Comment by Mathnerd314** [comment]
Can this be closed? Cinnamon is abandoned per https://github.com/NixOS/nixpkgs/issues/2384, anyone who works on it will presumably open a new issue/PR rather than posting to this old one.
