### ISSUE TITLE
buildFHSUserEnv doesn't work for non-root users in grsecurity

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#21327]
## Issue description
Trying to set up an AOSP build environment to nix-shell into. nix-shelling into it with a non-root user errors out. It succeeds with root and sudo.

### Steps to reproduce
shell.nix:
``` nix
{ pkgs ? import <nixpkgs> {} }:

let
  jdk = pkgs.jdk8;
  fhs = pkgs.buildFHSUserEnv {
    name = "android-env";
    targetPkgs = pkgs: with pkgs;
      [ git
        gitRepo
        gnupg1
        python2
        curl
        procps
        openssl
        gnumake
        nettools
        androidenv.platformTools
        ccache
        ncurses
        jdk
        schedtool
        utillinux
        m4
        gperf
        perl
        libxml2
        zip
        unzip
        bison
        flex
        lzop
        bc
        which
        gcc
      ];
    multiPkgs = pkgs: with pkgs;
      [ zlib
      ];
    extraOutputsToInstall = [ "dev" ];
    runScript = "bash";
    profile = ''
      export USE_CCACHE=1
      export ANDROID_JAVA_HOME=${jdk.home}
    '';
  };
in fhs.env
```
``` bash
[spacekitteh@spaceserv:~/code/copperhead]$ nix-shell
/nix/store/qxdag2fs1qh4alr19ax3s9lqh5dw2m24-chroot-user:44:in `block in make_fcall': Operation not permitted (Errno::EPERM)
        from /nix/store/qxdag2fs1qh4alr19ax3s9lqh5dw2m24-chroot-user:114:in `<main>'
```

## Technical details

* System: 17.03pre96925.1c50bdd (Gorilla)
* uname -a: Linux spaceserv 4.8.14-grsec #1-NixOS SMP Sat Dec 10 18:09:59 UTC 2016 x86_64 GNU/Linux
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version:"17.03pre96925.1c50bdd"

**Comment by copumpkin** [comment]
That's expected, I think. Grsec disables unprivileged user namespaces because it doesn't trust them. This also caused some pain with chromium/chrome sandboxing. Not sure what they did to fix it there.

**Comment by spacekitteh** [comment]
I seem to remember grsecurity having a privileged_chroot_group or something? I know it has other special groups.

**Comment by copumpkin** [comment]
Here's the context from last time we encountered this: https://github.com/NixOS/nixpkgs/issues/17460#issuecomment-237601115

**Comment by spacekitteh** [comment]
So, how can this be fixed?

**Comment by joachifm** [comment]
You probably need to go via a suid wrapper

**Comment by spacekitteh** [comment]
Howso?

**Comment by joachifm** [comment]
The general idea is to have an initially privileged stub that sets up the sandbox, marked suid (called via wrapper most likely, in our case) to allow ordinary logins to use it. You'd need to read the `buildFHSEnv` sandbox code to see exactly what its sandbox init involves. The privileged stub would do pretty much the same thing (possibly sans user namespace, depending on whether it's just used to allow non-privileged users to perform the sandbox init).

**Comment by Mic92** [comment]
It would be basically mount namespaces + setuid back to the unprivileged user.

**Comment by spacekitteh** [comment]
I don't speak Ruby.

``` ruby
<snip>
    $unshare.call CLONE_NEWNS
<snip>
    $mount.call nil, '/', nil, MS_REC | MS_SLAVE, nil
<snip>
    $unshare.call CLONE_NEWNS | CLONE_NEWUSER
<snip>
      write_file '/proc/self/setgroups', 'deny'
<snip>
    write_file '/proc/self/uid_map', "#{uid} #{uid} 1"
    write_file '/proc/self/gid_map', "#{gid} #{gid} 1"
<snip>
  # Do rbind mounts.
  mounts.each do |from, rto|
    to = "#{root}/#{rto}"
    FileUtils.mkdir_p to
    $mount.call from, to, nil, MS_BIND | MS_REC, nil
  end

  # Don't make root private so privilege drops inside chroot are possible
  File.chmod(0755, root)
```

These things seem to be the issue - IIRC, grsec allows reading from /proc/self/, but does it allow writing to it?

**Comment by copumpkin** [comment]
The issue is that grsec doesn't allow that unshare call with CLONE_NEWUSER unless you're root or have equivalent capabilities.

**Comment by spacekitteh** [comment]
Ah, okay. So does that mean the env.rb file has to be rewritten in C or something, or?

**Comment by spacekitteh** [comment]
Would fakeroot work, do you think?

**Comment by abbradar** [comment]
@spacekitteh I can't talk about Grsecurity because I haven't used it much, but if I understood https://github.com/NixOS/nixpkgs/issues/17460#issuecomment-237601115 correctly you won't be able to use `CLONE_NEWUSER` and, therefore, `CLONE_NEWNS` as a regular user _at all_ with current NixOS Grsecurity configuration. What this means is that you either need some sort of setuid wrapper, yes, or to disable this particular Grsecurity limitation.

See also https://github.com/NixOS/nixpkgs/issues/19047 as setuid interpreted scripts are forbidden (so Ruby is out of question).

Fakeroot won't likely help, but something like proot may (but you need to rewrite `chroot-user.rb`'s logic as `proot` call). Proot has its limitations (as it's implemented as a "debugger" which overrides several syscalls).

**Comment by copumpkin** [comment]
The main issue here is that spender doesn't trust the user namespace code enough to grant unprivileged access to it. You might disagree, in which case I'd just turn off the kernel patch rather than try to circumvent it with a setuid wrapper that will basically have the same effect in a more roundabout way.

**Comment by abbradar** [comment]
@copumpkin Exactly, see #21387 (that's why I closed it). However I left this one open because I don't know if we have any mechanism to change this grsecurity setting (e.g. with a build flag) currently.

**Comment by joachifm** [comment]
AFAIK, there's no way to disable this restriction. So if a setuid wrapper is not desired, this issue has to be closed as a wontfix.

**Comment by joachifm** [comment]
Closing, this is a feature and not a bug :) See https://github.com/NixOS/nixpkgs/issues/21387#issuecomment-269756654 for a solution that doesn't require modifying `buildFHSUserEnv`, if you really, really need this.

**Comment by spacekitteh** [comment]
But https://github.com/NixOS/nixpkgs/issues/21387#issuecomment-269756654 would disable it for EVERYTHING, whereas a stub would disable it only when setting up a FHS env, right?
