### ISSUE TITLE
Warnings in update-users-groups.pl

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#21330]
## Issue description

Our users/groups update script outputs several warnings which look dangerous.when I set root password to an empty string (only for a temporary VM, I assure you ^_^).

![screenshot_2016-12-21_11-30-29](https://cloud.githubusercontent.com/assets/1174810/21382297/5fbe063a-c779-11e6-8133-d426d055fedb.png)

### Steps to reproduce

1. `{ users.extraUsers.root.password = ""; }`
2. `NIXOS_CONFIG=path/to/config/above.nix nixos-rebuild build-vm`
3. Run it and observe the warnings.

## Technical details

* Nix version: (run `nix-env --version`) 1.12pre4523_3b81b26
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) c1ecf36b9320481837b688e32ee4bd6cfcf315f9

**Comment by Profpatsch** [comment]
(triage) can you still reproduce?
