### ISSUE TITLE
texlive: eqexam missing in scheme-full

### ISSUE THREAD

**Issue by steveeJ** [NixOS/nixpkgs#21334]
## Issue description
I downloaded a tex file that uses the `eqexam` package, which is not included in scheme-full nor can I find it manually in the texlive pkgs file. There is a CTAN package: https://www.ctan.org/pkg/eqexam, so I'm not sure why it's missing from the generated pkgs.nix

@vcunat

**Comment by vcunat** [comment]
Note that (1) [upstream TeX Live](https://www.tug.org/texlive/) doesn't necessarily include everything on ctan.org, and (2) we lag behind upstream on the order of months (and they "release" yearly anyway).

**Comment by steveeJ** [comment]
Can the _combine_ mechanism be used to include extra ctan.org packages?

**Comment by vcunat** [comment]
It *is* possible to include additional nix store paths. It was already discussed, probably here on github.com/nixos/nixpkgs.

**Comment by vcunat** [comment]
Link: https://github.com/NixOS/nixpkgs/issues/17748#issuecomment-242558135

**Comment by Mic92** [comment]
It took my a while how I have to construct this expression in the first place. A variable like extraPackages would be probably easier to use.

**Comment by steveeJ** [comment]
With the help of @vcunat and @Mic92 I was able to install the package manually.
This is simplified *shell.nix* that I use to work on related documents:

```nix
let 
  nixpkgs = import <nixpkgs> {};
  pkgsSrc = nixpkgs.pkgs.fetchFromGitHub {
    owner = "nixos";
    repo = "nixpkgs-channels";
    rev = "adfcc2d9531e78bf6a9e3b56e2f4fc873cb3d87b";
    sha256 = "101mh6gb9wlx0lq5pw2m0n1fi3h2pag3ndg184rrqzvn9ynp28iw";
  };
  pkgs = import pkgsSrc {};

  eqexam.pkgs = [
    (pkgs.stdenv.mkDerivation rec {
      version = "2012-05-17";
      pname = "eqexam";
      name = "${pname}-${version}";
      tlType = "run";

      src = pkgs.fetchurl {
        url = "http://www.math.uakron.edu/~dpstory/eqexam/eqexam_pack.zip";
        sha256 = "0g4w9ma6cr277li5b8dps9fm9jkjlwzwjc6ix01mw4kva4h5fdrj";
      };

      buildInputs = [ pkgs.unzip pkgs.texlive.combined.scheme-basic ];

      buildPhase = "
        latex eqexam.ins
      ";

      installPhase = "
        mkdir -p $out/tex/latex/eqexam
        cp -va *.sty *.cfg *.def $out/tex/latex/eqexam
        mkdir -p $out/doc/latex/eqexam
        cp -va doc/* $out/doc/latex/eqexam
      ";

      meta = {
        branch = "3";
        platforms = pkgs.stdenv.lib.platforms.unix;
      };
    })
  ];

  mytexlive =  (pkgs.texlive.combine {
    inherit (pkgs.texlive) scheme-basic;
    inherit eqexam;
  });

in pkgs.stdenv.mkDerivation {
  name = "texlive-combined-custom";
  buildInputs = [ 
    mytexlive
    pkgs.zathura
  ]; 
}
```
