### ISSUE TITLE
Request: Waterfox

### ISSUE THREAD

**Issue by filip2cz** [NixOS/nixpkgs#213351]
**Project description**
It is fork of Firefox with better privacy, something like LibreWolf but different

**Metadata**

* homepage URL: https://www.waterfox.net/
* source URL: https://github.com/WaterfoxCo/Waterfox
* license: Mozilla Public License 2.0 (more info here: https://www.waterfox.net/docs/policies/terms/)
* platforms: Linux, Windows, MacOS officialy supported

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/issues/188883

**Comment by filip2cz** [comment]
It is duplicate, but there is not Waterfox in Nix repos and I do not understand why

**Comment by Atemu** [comment]
See https://github.com/NixOS/nixpkgs/issues/188883.

Librewolf was added instead.

The original issue is still open though because Waterfox was not added.
