### ISSUE TITLE
`tutanota-desktop` has no icon in system tray

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#213455]
### Describe the bug
tutanota-desktop has no icon in system tray inside KDE
![image](https://user-images.githubusercontent.com/10415894/215358164-4769c815-2429-40e1-937f-32aefa54d06d.png)

### Notify maintainers

@WolfangAukang 

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.90, NixOS, 22.11 (Raccoon), 22.11.2058.ce20e9ebe19`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(aroun): `""`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by WolfangAukang** [comment]
I can see it on Pantheon:
![Screenshot from 2023-01-31 21-34-36](https://user-images.githubusercontent.com/8378365/215938974-8cf486f2-e977-42ed-a449-c143779e29f4.png)

![Screenshot from 2023-01-31 21-34-26](https://user-images.githubusercontent.com/8378365/215938996-aaafdead-71de-49f6-8804-da6097bbecbe.png)

Any clues on how KDE handles the icons?

**Comment by Zahrun** [comment]
Fixed
