### ISSUE TITLE
CertificateError: hostname 'translate.google.com' doesn't match either of '*.safezone.mcafee.com', 'safezone.mcafee.com'

### ISSUE THREAD

**Issue by pdeitel** [NixOS/nixpkgs#213412]
When I try to do a simple translation as follows

```python
# autodetect source language and translate to Spanish
spanish = GoogleTranslator(source='auto', target='es').translate(blob.string)  
```

blob.string is a Python str object with an English phrase stored in it.

I get the following exception -- there are multiple mentions of mcafee in here and unless that is an internal part of some python module, I don't have any mcafee products on my computer:
---------------------------------------------------------------------------
CertificateError                          Traceback (most recent call last)
File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/connectionpool.py:703, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    702 # Make the request on the httplib connection object.
--> 703 httplib_response = self._make_request(
    704     conn,
    705     method,
    706     url,
    707     timeout=timeout_obj,
    708     body=body,
    709     headers=headers,
    710     chunked=chunked,
    711 )
    713 # If we're going to release the connection in ``finally:``, then
    714 # the response doesn't need to know about the connection. Otherwise
    715 # it will also try to release it and we'll have a double-release
    716 # mess.

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/connectionpool.py:386, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385 try:
--> 386     self._validate_conn(conn)
    387 except (SocketTimeout, BaseSSLError) as e:
    388     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/connectionpool.py:1042, in HTTPSConnectionPool._validate_conn(self, conn)
   1041 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1042     conn.connect()
   1044 if not conn.is_verified:

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/connection.py:467, in HTTPSConnection.connect(self)
    458         warnings.warn(
    459             (
    460                 "Certificate for {0} has no `subjectAltName`, falling back to check for a "
   (...)
    465             SubjectAltNameWarning,
    466         )
--> 467     _match_hostname(cert, self.assert_hostname or server_hostname)
    469 self.is_verified = (
    470     context.verify_mode == ssl.CERT_REQUIRED
    471     or self.assert_fingerprint is not None
    472 )

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/connection.py:540, in _match_hostname(cert, asserted_hostname)
    539 try:
--> 540     match_hostname(cert, asserted_hostname)
    541 except CertificateError as e:

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/util/ssl_match_hostname.py:150, in match_hostname(cert, hostname)
    149 if len(dnsnames) > 1:
--> 150     raise CertificateError(
    151         "hostname %r "
    152         "doesn't match either of %s" % (hostname, ", ".join(map(repr, dnsnames)))
    153     )
    154 elif len(dnsnames) == 1:

CertificateError: hostname 'translate.google.com' doesn't match either of '*.safezone.mcafee.com', 'safezone.mcafee.com'

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/requests/adapters.py:489, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    488 if not chunked:
--> 489     resp = conn.urlopen(
    490         method=request.method,
    491         url=url,
    492         body=request.body,
    493         headers=request.headers,
    494         redirect=False,
    495         assert_same_host=False,
    496         preload_content=False,
    497         decode_content=False,
    498         retries=self.max_retries,
    499         timeout=timeout,
    500     )
    502 # Send the request.
    503 else:

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/connectionpool.py:787, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    785     e = ProtocolError("Connection aborted.", e)
--> 787 retries = retries.increment(
    788     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    789 )
    790 retries.sleep()

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/urllib3/util/retry.py:592, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    591 if new_retry.is_exhausted():
--> 592     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    594 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=es&sl=auto&q=Yesterday+was+a+beautiful+day.+Tomorrow+looks+like+bad+weather. (Caused by SSLError(CertificateError("hostname 'translate.google.com' doesn't match either of '*.safezone.mcafee.com', 'safezone.mcafee.com'")))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
Cell In[24], line 2
      1 # autodetect source language and translate to Spanish
----> 2 spanish = GoogleTranslator(source='auto', target='es').translate(blob.string)  

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/deep_translator/google.py:65, in GoogleTranslator.translate(self, text, **kwargs)
     62 if self.payload_key:
     63     self._url_params[self.payload_key] = text
---> 65 response = requests.get(
     66     self._base_url, params=self._url_params, proxies=self.proxies
     67 )
     68 if response.status_code == 429:
     69     raise TooManyRequests()

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/requests/api.py:73, in get(url, params, **kwargs)
     62 def get(url, params=None, **kwargs):
     63     r"""Sends a GET request.
     64 
     65     :param url: URL for the new :class:`Request` object.
   (...)
     70     :rtype: requests.Response
     71     """
---> 73     return request("get", url, params=params, **kwargs)

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/requests/api.py:59, in request(method, url, **kwargs)
     55 # By using the 'with' statement we are sure the session is closed, thus we
     56 # avoid leaving sockets open which can trigger a ResourceWarning in some
     57 # cases, and look like a memory leak in others.
     58 with sessions.Session() as session:
---> 59     return session.request(method=method, url=url, **kwargs)

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/requests/sessions.py:587, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    582 send_kwargs = {
    583     "timeout": timeout,
    584     "allow_redirects": allow_redirects,
    585 }
    586 send_kwargs.update(settings)
--> 587 resp = self.send(prep, **send_kwargs)
    589 return resp

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/requests/sessions.py:701, in Session.send(self, request, **kwargs)
    698 start = preferred_clock()
    700 # Send the request
--> 701 r = adapter.send(request, **kwargs)
    703 # Total elapsed time of the request (approximately)
    704 elapsed = preferred_clock() - start

File ~/anaconda3/envs/pydsft/lib/python3.10/site-packages/requests/adapters.py:563, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    559         raise ProxyError(e, request=request)
    561     if isinstance(e.reason, _SSLError):
    562         # This branch is for urllib3 v1.22 and later.
--> 563         raise SSLError(e, request=request)
    565     raise ConnectionError(e, request=request)
    567 except ClosedPoolError as e:

SSLError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=es&sl=auto&q=Yesterday+was+a+beautiful+day.+Tomorrow+looks+like+bad+weather. (Caused by SSLError(CertificateError("hostname 'translate.google.com' doesn't match either of '*.safezone.mcafee.com', 'safezone.mcafee.com'")))

Any ideas?

**Comment by FliegendeWurst** [comment]
Works for me. There must be something wrong with your network..
