### ISSUE TITLE
firejail: cannot switch euid/egid to root

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#21356]
## Issue description

❯ firejail
Warning: cannot switch euid to root
Warning: cannot switch egid to root
Warning: cannot switch euid to root
Warning: cannot switch egid to root
Warning: cannot switch euid to root
Warning: cannot switch egid to root

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03pre96925.1c50bdd (Gorilla)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre96925.1c50bdd"

* uname -a
Linux nixos 4.8.12 #1-NixOS SMP Fri Dec 2 08:11:45 UTC 2016 x86_64 GNU/Linux

**Comment by joachifm** [comment]
Did you add
```
security.setuidPrograms = [ "firejail" ];
```

**Comment by tex** [comment]
No I did not. I added it and it works. Thank you very much!
Somehow I expected that package that provides firejail will do whatever is necessary.

BTW: I'm new user of NIXOS (installed yesterday for first time) and so far it feels great!

**Comment by 7c6f434c** [comment]
Nix model means that everyone can write (not just take from the central repository) and install a package without breaking anything; so a package cannot make anything setuid on its own.

Security policies are global, so they are managed on the NixOS side.
