### ISSUE TITLE
Using docker during a nix build

### ISSUE THREAD

**Issue by bhoudebert** [NixOS/nixpkgs#213526]
Hello,

## Situation

We are building a Rust application which need to contact at build time a live instance of a postgres instance (sqlx crate), so let's say a docker container. We know this is quite an unorthodox thing and we do not wish to use any offline pattern.

We tried to move forward using `buildRustPackage`,but as expected, it does not work as is when it tries to connect to the database. We got either connection failure or cannot connect to docker (when we tried to start a docker container).

## Questions

- Is it possible to contact the host docker daemon via docker.sock?
- Is there any way to start a daemon during the `buildPhase`?

We are a bit short on how to solve that part and we really want to avoid at all cost using the `cargo sqlx prepare` (offline mode) as it does not totally enforce discrepancies between sql/schema.

Thanks.

**Comment by NickCao** [comment]
If all you need is a live postgresql database, you can use `postgresqlTestHook`.

**Comment by bhoudebert** [comment]
Oh very interesting, I am gonna give it a try thanks.
