### ISSUE TITLE
ntpd: `systemctl stop` hangs

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#21357]
## Issue description

This is very annoying during power off or restart where it is waiting untill it gets killed by systemctl watchdog.

### Steps to reproduce

> systemctl stop ntpd

(this hangs, nothing happens)
CTRL-C

> systemctl status ntpd

```
[root@nixos:/home/milan]# systemctl status ntpd
● ntpd.service - NTP Daemon
   Loaded: loaded (/nix/store/1q89vsw1643flfhbk4n4xmvswzxsdiap-unit-ntpd.s
   Active: deactivating (stop-sigterm) since Thu 2016-12-22 13:45:08 UTC; 
  Process: 767 ExecStart=ntpd -g -c /nix/store/lhzvvf71jmqml7hq5xix2h3cj12
  Process: 729 ExecStartPre=/nix/store/m0cms7a6ycbamva2mr95p5614jlk3cwq-un
 Main PID: 825 (ntpd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/ntpd.service
           ‣ 825 [ntpd]

Dec 22 13:14:05 nixos ntpd[825]: proto: precision = 0.053 usec (-24)
Dec 22 13:14:05 nixos ntpd[825]: Listen and drop on 0 v6wildcard [::]:123
Dec 22 13:14:05 nixos ntpd[825]: Listen and drop on 1 v4wildcard 0.0.0.0:1
Dec 22 13:14:05 nixos ntpd[825]: Listen normally on 2 lo 127.0.0.1:123
Dec 22 13:14:05 nixos ntpd[825]: Listen normally on 3 lo [::1]:123
Dec 22 13:14:05 nixos ntpd[825]: Listening on routing socket on fd #20 for
Dec 22 13:14:05 nixos ntpd[825]: ntpdmain: seccomp_init(SCMP_ACT_KILL) suc
Dec 22 13:14:05 nixos ntpd[825]: ntpdmain: seccomp_load() succeeded
Dec 22 13:14:06 nixos systemd[1]: Started NTP Daemon.
Dec 22 13:45:08 nixos systemd[1]: Stopping NTP Daemon...
```

> systemctl stop ntpd
> 

(success immediately)

## Technical details

* System: (NixOS: nixos-version, Ubuntu/Fedora: lsb_release -a, ...)
17.03pre96925.1c50bdd (Gorilla)

* Nix version: (run nix-env --version)
nix-env (Nix) 1.11.4

* Nixpkgs version: (run nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion)
"17.03pre96925.1c50bdd"

* uname -a
Linux nixos 4.8.12 #1-NixOS SMP Fri Dec 2 08:11:45 UTC 2016 x86_64 GNU/Linux

**Comment by joachifm** [comment]
See also https://github.com/NixOS/nixpkgs/issues/21136. As we've switched to `timesyncd` as the default ntp client, I'm unsure whether anybody is working on fixing ntpd.

**Comment by tex** [comment]
Well, I did install and upgrade to unstable channel, my config has nothing about ntpd, but ntpd is on my system. How do I get rid of ntpd and start using timesyncd?

**Comment by tex** [comment]
I added services.timesyncd.enable = true; to my configuration.nix and it seemed to remove ntpd and included timesyncd. Is this correct way to proceed?

**Comment by joachifm** [comment]
Enabling `timesyncd` will disable other clients, I believe, so that's a reasonable thing to do.

**Comment by tex** [comment]
Thanks!

**Comment by joachifm** [comment]
Once https://github.com/NixOS/nixpkgs/pull/21160 hits the channel, it should no longer be necessary to do this manually. The unstable channel currently lags quite a bit, however.
