### ISSUE TITLE
SD card does not boot on Raspberry PI 4 (or at least uart does not work)

### ISSUE THREAD

**Issue by uzytkownik** [NixOS/nixpkgs#213504]
## Issue description
When booting the system hangs after 'Starting kernel...':

```
Retrieving file: /boot/extlinux/../nixos/wypcmxwhqdpx78vw9xiqxgcmvkdlwha5-initrd-linux-5.15.90-initrd
Retrieving file: /boot/extlinux/../nixos/pz72mib07l57s2nrknbrirs0qdfw24dl-linux-5.15.90-Image
append: init=/nix/store/rimzkr9pydqwk8h7cyrp918h3v59bhs7-nixos-system-nixos-22.11.2117.22c4a7a4796/init console=ttyS0,115200n8 console=ttyAMA0,115200n8 console=tty0 nohibernate loglevel=7
Retrieving file: /boot/extlinux/../nixos/pz72mib07l57s2nrknbrirs0qdfw24dl-linux-5.15.90-dtbs/broadcom/bcm2711-rpi-4-b.dtb
Moving Image from 0x80000 to 0x200000, end=3580000
## Flattened Device Tree blob at 04700000
   Booting using the fdt blob at 0x4700000
   Using Device Tree in place at 0000000004700000, end 000000000470c2a2

Starting kernel ...
```

If RPI is connected to computer, it cannot enumerate USB devices. This does not happen with Raspberry OS image.

This happens both on stable and unstable.

### Steps to reproduce

1. Download SD image from hydra
2. dd it on SD card
3. Try to boot it

## Technical details

N/A. Cannot boot system

**Comment by uzytkownik** [comment]
Some more info:

- Ethernet doesn't work or at least dhcp request is not sent
- Firmware update doesn't help

**Comment by samueldr** [comment]
Given this is over a year old, and other people have been using the current images on Raspberry Pi, I'm tentatively closing.

Note, for anyone reading this in the future, that `Starting kernel ...` is the last thing that U-Boot outputs when starting the kernel. At this point ***it has to be assumed*** that the kernel is actually running.

If anyone is seeing similar symptoms, please open a new issue with details about your current situation. Keeping this open for possible future boot issues on Raspberry Pi 4 is problematic as it is possible many are unrelated.
