### ISSUE TITLE
pkgsStatic.cmocka: build fails

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#213623]
### Steps To Reproduce
1. nix build .#pkgsStatic.cmocka

### Build log
Logs with tests disabled: https://termbin.com/udmx
Logs with tests enabled: https://termbin.com/t4wo

### Additional context
* Fixing `pkgsStatic.cmocka` fixes tests for `pkgsStatic.libcbor`.
* While problem isn't solved. Made a PR to (1) enable tests, (2) set static flag (3) set broken for static:
  - #213625

### Notify maintainers
@kragniz @rasendubi

**Comment by FliegendeWurst** [comment]
Fixed in #235275
