### ISSUE TITLE
Package request: vivarium

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#213611]
**Project description**
A dynamic tiling Wayland compositor using wlroots 

**Metadata**

* homepage URL: https://github.com/inclement/vivarium
* source URL: https://github.com/inclement/vivarium
* license: gpl3
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/172052
