### ISSUE TITLE
Allow local in virtualisation.docker.logDriver?

### ISSUE THREAD

**Issue by boozedog** [NixOS/nixpkgs#213603]
## Issue description
`virtualisation.docker.logDriver` allows one of `"none", "json-file", "syslog", "journald", "gelf", "fluentd", "awslogs", "splunk", "etwlogs", "gcplogs"`

Any reason not to allow / use `local` as described below?

https://docs.docker.com/config/containers/logging/local/

@offlinehacker  @tailhook  @vdemeester  @periklis  @mikroskeem  @maxeaubrey 

https://discourse.nixos.org/t/allow-local-in-virtualisation-docker-logdriver/24884

**Comment by mikroskeem** [comment]
I think reason is that noone know about its existence, [though it seems to have been around for a while](https://github.com/docker/docs/commit/e50e4c09db1688eb373d30a370237b550dc7a7a6).

**Comment by mikroskeem** [comment]
#213604 got merged, closing.
