### ISSUE TITLE
Broken download links on nixpkgs/download.html

### ISSUE THREAD

**Issue by l2dy** [NixOS/nixpkgs#21372]
## Issue description
`Release nixpkgs-0.13 doesn't exist.
`
`File /nix/store/5idsdfgrxc7x6k2w5dj1av2m7w2fc4wa-nixpkgs-tarball-17.03pre97623.556ca97/tarballs/nixpkgs-17.03pre97623.556ca97.tar.xz has disappeared.
`

**Comment by joachifm** [comment]
Please open an issue against https://github.com/NixOS/nixos-homepage
