### ISSUE TITLE
configure of many packages uses hardcoded path /usr/bin/file

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21373]
## Issue description

configure of many packages (```libvirt```, ```xfce4-terminal``` to name a few) uses hardcoded path /usr/bin/file resulting in warnings during configurePhase

```./configure: line 51121: /usr/bin/file: No such file or directory```

```./configure: line 8293: /usr/bin/file: No such file or directory```

The packages are compiled nevertheless.

### Steps to reproduce

```
nix-shell '<nixpkgs>' -A libvirt
unpackPhase
cd libvirt*
configurePhase
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
NixOS 16.09.1338.5d03aab (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A
lib.nixpkgsVersion`)
"16.09.1338.5d03aab"

**Comment by jgeerds** [comment]
It is generally a good idea to report these "issues" upstream (e.g. `libvirt` or `xfce4-terminal`). I think they shouldn't hardcode `/usr/bin/file`

**Comment by volth** [comment]
It is not about the two packages, it was in almost every packages I have compiled.

**Comment by Mic92** [comment]
Autoconf is responsible for that. The packages mentioned here come with pre-generated configure scripts. So it seems like we can not do much here, as it is out of scope of nixos to fix this.

**Comment by grahamc** [comment]
I disagree, we fix stuff like this all the time in order to make it compatible with NixOS. I was noticing this the other day, too. Many projects seem to use `/usr/bin/file` in the same place and in the same way. I was thinking we could add a patch stage by default for these cases. (Just my $0.02, it might be a bad idea.)

**Comment by dezgeg** [comment]
Auto-patching it would require adding the `file` package to `stdenv` thus bloating it more. Not really worth it for the sake of getting rid of a single warning (AFAIK there are no other effects).

**Comment by volth** [comment]
Can ```file``` be added to ```autoconf``` instead of ```stdenv``` ?

@dezgeg Then it would be honest to patch it to ```${coreutils}/bin/false```

**Comment by Mic92** [comment]
@volth the projects in questions do not depend on autoconf. Autoconf was used to generate the release tarball.

**Comment by dezgeg** [comment]
You really can't blindly patch them to `${coreutils}/bin/false` because some package might actually be using `/usr/bin/file` in other places than those where the lack of `file` causes no problems.
