### ISSUE TITLE
ghcjs haddock doesn’t build linked source

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nixpkgs#21376]
For ghcjs packages haddocks the modules are built just fine, but the sources are not linked (`html/src` folder is missing).

```
> nix-shell -E 'haskell.packages.ghcjsHEAD.ghcWithPackages (h: [h.ghcjs-base])'
$ chromium $nativeBuildInputs
``` 

For reference, here is the build log of that command:
[log.txt](https://github.com/NixOS/nixpkgs/files/671054/log.txt)

cc @cstrahan @peti @ryantrinkle @TravisWhitaker

**Comment by matthewbauer** [comment]
Looks like it's fixed in ghcjs 8.4.
