### ISSUE TITLE
Update sunshine to 0.18.0

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#213769]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: sunshine

current version: 0.16.0
desired version: 0.18.0

###### Notify maintainers

maintainers: @devusb

###### Note for maintainers

Please tag this issue in your PR.

**Comment by devusb** [comment]
I opened a draft PR to upgrade to 0.18.1 https://github.com/NixOS/nixpkgs/pull/214799, but still having trouble finding the issue with NVFBC -- should work otherwise, but holding off (or will just remove `cudaSupport` for now).
