### ISSUE TITLE
Add pkg => Mail-in-a-Box

### ISSUE THREAD

**Issue by stnert** [NixOS/nixpkgs#213810]
**Project description**
Mail-in-a-Box helps individuals take back control of their email by defining a one-click, easy-to-deploy SMTP+everything else server: a mail server in a box.

**Metadata**

* homepage URL: https://mailinabox.email/
* source URL: https://github.com/mail-in-a-box/mailinabox
* license:  CC0-1.0 license
* platforms: Linux (.deb)

**Comment by squalus** [comment]
That's not packagable in Nix unfortunately. It has a heavy tie-in to Ubuntu's apt package manager. It does a ton of mutations to the file system. It would be nice to have an equivalent project in Nix though.

**Comment by stnert** [comment]
> That's not packageable in Nix, unfortunately. It has a heavy tie-in to Ubuntu's apt package manager. It does a ton of mutations to the file system. It would be nice to have an equivalent project in Nix though.

It makes sense.
