### ISSUE TITLE
Packaging Request: Duelyst

### ISSUE THREAD

**Issue by jtrees** [NixOS/nixpkgs#213840]
**Project description**
Digital collectible card game and turn-based strategy hybrid developed by Counterplay Games and released in 2016.

**Metadata**

* homepage URL: https://github.com/open-duelyst/duelyst
* source URL: https://github.com/open-duelyst/duelyst
* licenses: CC0
* platforms: Linux, Mac, Windows

**Comment by raspher** [comment]
it's interesting, nice initiative, however their staging environment is now down and last commit to repo was 9 months ago

there is nice documentation how to build client, but for now i don't know if it will be back online or not

**Comment by jtrees** [comment]
Meh, I've lost interest. Feel free to re-open if you want to see this.
