### ISSUE TITLE
Closure size: go applications depend on go compiler

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nixpkgs#21397]
## Issue description
Applications programmed in go, like syncthing, camlistore and go-ethereum depend on the go compiler at runtime. I lack wizardry to work out exactly why and what to do about it, but I suspect that this is related to debugging info that is kept in executables even if the go compiler is asked to strip them (debugging symbols for debuggers are removed, but paths for mapping machine code to source code are kept). This results in nix detecting the reference and making go a dependency of the application.

### Steps to reproduce
`nix-env -iA nixos.syncthing`
<watch as go is downloaded and installed>

## Technical details

* System: 16.09.1349.ce7e9cb (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1349.ce7e9cb"

**Comment by dezgeg** [comment]
Doesn't happen with `fzf` for instance:
````
/nix/store/7ddxv1k0r8cpsg39rayfj2pslbabwgyn-fzf-0.15.9-bin
+---/nix/store/8lbpq1vmajrbnc96xhv84r87fa4wvfds-glibc-2.24
|   +---/nix/store/8lbpq1vmajrbnc96xhv84r87fa4wvfds-glibc-2.24 [...]
+---/nix/store/aacmjq0zmkcwchaxz7zs5lnh176jv9qf-tzdata-2016f
+---/nix/store/hs9zk8bc1w6hc8s8k7hyl5p0sx02l25w-bash-4.3-p46
|   +---/nix/store/8lbpq1vmajrbnc96xhv84r87fa4wvfds-glibc-2.24 [...]
|   +---/nix/store/hs9zk8bc1w6hc8s8k7hyl5p0sx02l25w-bash-4.3-p46 [...]
+---/nix/store/n50qwzb3j5lh9ybx2z9illl6qkg9d9m5-ncurses-6.0
    +---/nix/store/8lbpq1vmajrbnc96xhv84r87fa4wvfds-glibc-2.24 [...]
    +---/nix/store/n50qwzb3j5lh9ybx2z9illl6qkg9d9m5-ncurses-6.0 [...]
````

Maybe it's something broken with those specific applications.

**Comment by lheckemann** [comment]
Good catch, I think maybe it's because fzf uses buildGoPackage while the others use stdenv.mkDerivation.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lheckemann** [comment]
Yes, I think it's [this little bit of evil](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-modules/generic/default.nix#L44-L46) that's responsible for the smaller closure size for fzf and friends.

**Comment by lheckemann** [comment]
#23560 is relevant

**Comment by Mic92** [comment]
I think this is solved now.

**Comment by lheckemann** [comment]
The following packages still reference go and probably shouldn't:

- go-ethereum
- fleet
- direnv
- storebrowse probably would if it built
- peco
- tmsu
- gotools
- godep
- prometheus
- prometheus-pushgateway
- prometheus-snmp-exporter
- prometheus-alertmanager
- cadvisor
- rkt
- docker-proxy
- acbuild
- arangodb
- md2man (attrpath go-md2man)
- hub (attrpath gitAndTools.hub)

This list may not be complete; I built it using `rg '\bgo\s*,'` (to find hopefully all the package functions that take go as an argument), building each of them, and checking if the result referenced go.

Shoutout to @joachifm for already fixing it for runc, docker, containerd, and kubernetes — thanks!
