### ISSUE TITLE
provide our manuals (nix, nixOS, nixOps) as pdf

### ISSUE THREAD

**Issue by toogley** [NixOS/nixpkgs#21391]
Hey.

I've read on IRC, that our manuals ([nix](http://nixos.org/nix/manual/), [nixops](http://nixos.org/nixops/manual/) and [nixos](http://nixos.org/nixos/manual/)) do already exist as epub. 

But i'd love if those manuals would also be automatically available as pdf's.

**Comment by FRidh** [comment]
See https://nixos.org/nix/download.html for the Nix manual. It includes a link to the PDF.
In the case of NixOS and Nixpkgs the direct links seem to be missing.

**Comment by toogley** [comment]
@FRidh Ah, i missed that. Is there a way to receive those pdf manuals? enabling `system.build.manual.manual` in configuration.nix doesn't seem to do that.

**Comment by FRidh** [comment]
Both Nixpkgs and NixOS don't seem to provide function that builds the PDF versions, but it shouldn't be hard to add that.

### Nixpkgs
https://github.com/NixOS/nixpkgs/blob/master/doc/default.nix
Checkout `nixpkgs`, then `$ nix-build -A doc`. There doesn't seem to be a function for building a PDF but that should be straightforward to add.

### NixOS
https://github.com/NixOS/nixpkgs/blob/master/nixos/release.nix#L97
Checkout `nixpkgs`, then `$ nix-build -A manual nixos/release.nix`

**Comment by LnL7** [comment]
I knew I had seen a somewhere, just couldn't find it. I was a bit surprised that we don't have it in the manual builds.

**Comment by ericsagnes** [comment]
There was a pdf manual for NixOS but it was removed in https://github.com/NixOS/nixpkgs/commit/d5756cdf0afb066af91b837856867bd8e1bc7fe0.

**Comment by toogley** [comment]
Hm, i personally like to have some kind of up-to-date offline manual - when my system breaks and i don't have internet connection, its good to have some documentation.

Furthermore, i think the reason given by @edolstra is a bit flawed, because providing the manual additionally as pdf doesn't hurt in any way (IMHO).

**Comment by FRidh** [comment]
@toogley you can `nix-build` the html docs yourself. That way you have them offline, and the latest version.  You could even add them to your `environment.systemPackages` or `system.extraDependencies` to make sure you have them always on your system.

**Comment by ericsagnes** [comment]
On NixOS, there is always an offline version of the maual available by running the `nixos-help` command.

**Comment by toogley** [comment]
Okay, thanks @ericsagnes - that means, i don't need an pdf version. Thanks!

**Comment by HeinrichHartmann** [comment]
I have interest in this as well. I am trying to make up my mind if I should give NIX a shot, and want to print the manual to give it a thorough review.

* The [online version](https://nixos.org/nix/manual/) does not print for me on Firefox. Safari works, but it's not exactly pretty.
* The pdf links on the download page that @FRidh mentioned have disappeared.
* I was not able to find the epub version that @toogley mentioned. Where can I find them?
* I don't have NIX/NIXOS installed so building them myself is not so easy for me.

So, it looks like pdf versions of the manual are not readily available at this point in time. I would certainly appreciate having them.

PS: Nix is great. Thanks for making this!

**Comment by HeinrichHartmann** [comment]
Update: Reading the comments again, it looks like there are no (built-in) ways to make a pdf version from NixOS, just the HTML versions. So the last bullet is not an option.
