### ISSUE TITLE
vscode-extensions.julialang.language-julia

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#214076]
**Project description**

The [Julia programming language](https://julialang.org/) is a high level and dynamic language built for speed and simplicity. Julia is commonly used in areas such as data science, machine learning, scientific computing, but is still a general purpose language that can handle most programming use cases.

The [Julia extension](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) for Visual Studio Code includes built-in dynamic autocompletion, inline results, plot pane, integrated REPL, variable view, code navigation, and many other advanced language features.

![image](https://user-images.githubusercontent.com/45872139/216199334-1d7fd0d8-7110-4a5c-b7c1-14109ac6f6f9.png)

**Metadata**

* homepage URL: https://www.julia-vscode.org
* source URL: https://github.com/julia-vscode/julia-vscode/releases
* license: MIT
* platforms: unix, linux, darwin

**Comment by superherointj** [comment]
`julialang.language-julia` (version `1.75.2`) is already packaged.
