### ISSUE TITLE
`openssl ciphers ALL:-EXP:-SRP:-SEED:-CAMELLIA:-DSS:-RC2:-DES-CBC-MD5:-DES-CBC3-MD5 | grep DH-DSS-AES256-GCM-SHA384` returns a result when it shouldn't

### ISSUE THREAD

**Issue by spacekitteh** [NixOS/nixpkgs#21408]
## Issue description
The underlying call, SSL_set_cipher_list, appears to not correctly parse the filter list. This occurs both from the commandline, (running `openssl ciphers ALL:-EXP:-SRP:-SEED:-CAMELLIA:-DSS:-RC2:-DES-CBC-MD5:-DES-CBC3-MD5` ) and from calling the function directly ([as AOSP's conscrypt does](https://github.com/multi-os-engine/conscrypt/blob/master/src/main/java/org/conscrypt/NativeCrypto.java#L696))

### Steps to reproduce
run `openssl ciphers ALL:-EXP:-SRP:-SEED:-CAMELLIA:-DSS:-RC2:-DES-CBC-MD5:-DES-CBC3-MD5` with 

## Technical details

* OpenSSL: 1.0.2j
* System: 17.03.git.ed5e446 (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: 17.03pre96925.1c50bdd

**Comment by Mic92** [comment]
Did you report this to upstream?

**Comment by spacekitteh** [comment]
Not yet. I wasn't sure if it was NixOS specific or not and was waiting for results from another OS. I'm reporting it now, though!

**Comment by Mic92** [comment]
Upstream said, the behavior is intended.
