### ISSUE TITLE
Package request: openrefine

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#214080]
**Project description**

[<img src="https://raw.githubusercontent.com/OpenRefine/OpenRefine/master/graphics/icon/open-refine-320px.png" align="center">](https://openrefine.org)

OpenRefine is a Java-based power tool that allows you to load data, understand it, clean it up, reconcile it, and augment it with data coming from the web. All from a web browser and the comfort and privacy of your own computer.

**Metadata**

* homepage URL: https://openrefine.org/
* source URL: https://github.com/OpenRefine/OpenRefine/releases
* license: BSD-3-Clause license 
* platforms: unix, linux, darwin,

**Comment by TanvirOnGH** [comment]
It has been merged long ago. Why is this issue not closed yet?
