### ISSUE TITLE
firejail firefox desktop

### ISSUE THREAD

**Issue by tex** [NixOS/nixpkgs#21413]
## Issue description
How to modify desktop entries from NixOS configuration.nix to run Firefox in Firejail?
The end state is that uses clicks on Firefox icon and Firefox gets executed as 'firejail firefox'.

**Comment by rnhmjoj** [comment]
I don't know if this is the best way but I would simply change the `desktopItem` by overriding the firefox derivation. Something like this should work
```
nixpkgs.config.packageOverrides = pkgs: with pkgs; {
  firefox = stdenv.lib.overrideDerivation firefox (_: {
    desktopItem = makeDesktopItem {...};
  });
};
```

**Comment by tex** [comment]
Thank you! It works.

**Comment by vcunat** [comment]
@tex: zathura doesn't use the `desktopItem` attribute (it's nothing standard AFAIK), so overriding it changes basically nothing.

**Comment by tex** [comment]
So is there any way how to to what I want? Should I directly modify Zathura expression to use desktopItem attribute? Or is there any way how to overwrite package's file from configuration.nix?

**Comment by vcunat** [comment]
The expression basically does overwrite the original expression, almost as if you did it in that file directly, but you have to add code that actually replaces that file, e.g. during `postInstall` phase.
