### ISSUE TITLE
Runescape

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#214152]
### Steps To Reproduce
1. Attempt to install `pkgs.Runescape`

### Build log

[runescape.log](https://github.com/NixOS/nixpkgs/files/10567728/runescape.log)

### Additional context
Seems to be missing `libcrypto` and `libssl`

### Notify maintainers

@GRBurst

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.0.10-zen2, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(krutonium): `""`
 - channels(root): `"nixos-21.11.335665.0f316e4d72d, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Krutonium** [comment]
Just realized it's only broken on `nixos-22.11`, Works fine on Unstable and Master.

**Comment by Aleksanaa** [comment]
`nixos-22.11` is not supported now.

**Comment by ElijahHW** [comment]
Hi, trying to play runescape by adding it to `environment.systemPackages`, but on `nixos-23.11`, and not able to run `sudo nixos-rebuild switch` after that.  Can paste the logs if needed.

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/208642

**Comment by gepbird** [comment]
> Hi, trying to play runescape by adding it to `environment.systemPackages`, but on `nixos-23.11`, and not able to run `sudo nixos-rebuild switch` after that. Can paste the logs if needed.

@subcidr since this package depends on an insecure library, it's not recommended to use it. You can bypass this warning by putting this in your nixos config:
```nix
nixpkgs.config.permittedInsecurePackages = [
  "openssl-1.1.1w"
];
```

Also you might want to try the `runelite` package instead.
