### ISSUE TITLE
hydra not building - known issue, but no warning in manual for hydra

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#21424]
## Issue description
I tried to set up hydra for a test-run on my laptop and it failed at:

> g++ -DHAVE_CONFIG_H -I. -I../..    -I/nix/store/xibmb4s2xah92zx2m34gng55in38l2cq-boehm-gc-7.2g-dev/include -I/nix/store/i90xvxfz44hg85yyv9px2vkkvdarfn85-nix-1.12pre4523_3b81b26-dev/include/nix -Wall -laws-cpp-sdk-s3 -g -O2 -std=c++11 -c -o s3-binary-cache-store.o s3-binary-cache-store.cc
> s3-binary-cache-store.cc:6:29: fatal error: aws/s3/S3Client.h: No such file or directory
> compilation terminated.

I have tried it as described in: ```https://nixos.org/hydra/manual/``` - i did not try the one-click install, but the channel method.

Later I found the error in ```https://github.com/NixOS/hydra/issues/322``` with links to the workarounds, but those should be mentioned either in the manual itself, or fixed. It's an inconvenience for new hydra users, that the official manual isn't working.

Posting this in ```nixpkgs``` instead of ```hydra```, so more people see it.

Happy Holidays,
ikervagyok

**Comment by joachifm** [comment]
I don't think it's appropriate to use the manual as a bug tracker.

**Comment by ikervagyok** [comment]
@joachifm: it is not - still, trying to install a software "by the book" and failing is bad. it's even worse, if we - the nix-guys, who are all about reproducable builds are unable to provide the best CI (hydra) in the world - can't install hydra... it's so bad, that i would love to skip the informal rule of "manuals are for the standards, not the workarounds" and state that it's WIP and we will fix it ASAP. 

Explanation: i tried to show people how cool this system is for university-applications and i couldn't set up my test instance. We suck hard at the moment and can't even be honest - that's sending people the worst possible message. also this issue is in my eyes just to show people who wont follow the hydra git and bugtracker, that we care and we will fix it one way or another.

sorry for the long post, but i think this important - not for people knowing their way around NixOS, but for the ones that want to try our tooling.

**Comment by joachifm** [comment]
@ikervagyok the issue you linked is unrelated to the current build failure, as far as I can tell (https://github.com/NixOS/nixpkgs/pull/21418 looks like an attempt at fixing it). What is the workaround you're thinking of? Builds break on unstable as a matter of routine, updating the manual whenever it happens makes no sense to me.

**Comment by ikervagyok** [comment]
you are right, not to update the manual every time stuff breaks - as long as breakage isn't something so common, that it is expected to happen every now and then. in that case you should at least mark stuff experimental or broken.

@joachifm @domenkozar : if you point me into a direction, how to at least update the docs that this is unsupported/-stable/whatever and add some pointers how to try and fix breakage on affected setups, i'm glad to write that part to the docs, to be included as long as this remains an issue affecting every other release. at least as long as https://github.com/NixOS/hydra/issues/322 is open, i think we should be including a warning in the official docs for hydra.

**Comment by ikervagyok** [comment]
@joachifm thanks for following my not straight-to-the-point comments, being tired doesn't help me explain myself correctly ;)
i'll try again, reporting about what works/doesn't work.

**Comment by Zer0-** [comment]
+1 I cannot enable services.hydra because the hydra package won't build. I get the same error as OP.

Hydra wasn't in 16.03 but I could still get it working by following the wiki, now it's broke :(

**Comment by grahamc** [comment]
Yikes, hydra on 16.09 is broken due to issues with s3. Backport the patch from master upgrading hydra and then it fails because nixUnstable is 1.12pre instead of 1.11.5, I think. @domenkozar what should we do here?

**Comment by grahamc** [comment]
Using hydra from master yields:

```
Jan 13 03:31:53 hydra hydra-server[2566]: [warn] Unicode::Encoding plugin is auto-applied, please remove this from your appclass and make sure to define "encoding" config
Jan 13 03:31:53 hydra hydra-server[2566]: Compress::Raw::Bzip2 version 2.07 required--this is only version 2.064 at /nix/store/v4b73k27ijng18d38d79hghxmjisif1k-hydra-perl-deps/lib/perl5/site_perl/5.22.2/IO/Compress/Adapter/Bzip2.pm line 9.
Jan 13 03:31:53 hydra hydra-server[2566]: BEGIN failed--compilation aborted at /nix/store/v4b73k27ijng18d38d79hghxmjisif1k-hydra-perl-deps/lib/perl5/site_perl/5.22.2/IO/Compress/Adapter/Bzip2.pm line 9.
Jan 13 03:31:53 hydra hydra-server[2566]: Compilation failed in require at /nix/store/v4b73k27ijng18d38d79hghxmjisif1k-hydra-perl-deps/lib/perl5/site_perl/5.22.2/IO/Compress/Bzip2.pm line 11.
Jan 13 03:31:53 hydra hydra-server[2566]: BEGIN failed--compilation aborted at /nix/store/v4b73k27ijng18d38d79hghxmjisif1k-hydra-perl-deps/lib/perl5/site_perl/5.22.2/IO/Compress/Bzip2.pm line 11.
Jan 13 03:31:53 hydra hydra-server[2566]: Compilation failed in require at /nix/store/b20crf8yisk36kwnvfdiqcqf0d8ryih4-hydra-2016-12-09/libexec/hydra/lib/Hydra/View/NixExprs.pm line 7.
Jan 13 03:31:53 hydra hydra-server[2566]: BEGIN failed--compilation aborted at /nix/store/b20crf8yisk36kwnvfdiqcqf0d8ryih4-hydra-2016-12-09/libexec/hydra/lib/Hydra/View/NixExprs.pm line 7.
Jan 13 03:31:53 hydra hydra-server[2566]: Compilation failed in require at /nix/store/v4b73k27ijng18d38d79hghxmjisif1k-hydra-perl-deps/lib/perl5/site_perl/5.22.2/Catalyst/Utils.pm line 309.
Jan 13 03:31:53 hydra hydra-server[2566]: Compilation failed in require at /nix/store/v4b73k27ijng18d38d79hghxmjisif1k-hydra-perl-deps/lib/perl5/site_perl/5.22.2/Catalyst/ScriptRunner.pm line 50.
```

looks like we just don't have a working hydra? What is hydra.nixos.org running?

**Comment by grahamc** [comment]
Update: using nixpkgs master at e2be232c65432d8e543be80b1ba67756c389ab10 works fine.

```
let
  pkgs = import <nixpkgs> {};
  unstable = import (pkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "e2be232c65432d8e543be80b1ba67756c389ab10";
    sha256 = "1dz3wlbz97pk0csjdzy2zlz9hsjdrd96yb5x7v33ksv7hyl9c7ld";
  }) {};
in
{
  hydra =
    { config, pkgs, ... }:
    { deployment.targetEnv = "virtualbox";
      deployment.virtualbox.memorySize = 1024;

      networking.firewall.enable = true;
      networking.firewall.allowedTCPPorts = [ 22 3000 ];


      services = {
        hydra = {
          package = unstable.hydra;
        };
      };
    };
}
```

**Comment by domenkozar** [comment]
Hydra package has been since fixed.
