### ISSUE TITLE
gphoto2: insufficient permissions (includes workaround)

### ISSUE THREAD

**Issue by league** [NixOS/nixpkgs#21420]
## Issue description

I could not access my USB digital camera as a non-root user, due to insufficient permissions. The file in `/dev/bus/usb` popped up with user and group set to `root`.

I'm new to NixOS and I'm not sure of the best way to solve something like this. Below I'll document a workaround that I used in my `configuration.nix` that solved the problem, in case that's helpful to others. But if a NixOS option along with some facility in the `gphoto2` package could solve it, that would be ideal.

### Steps to reproduce

  - Plug camera into USB
  - Ensure it shows up in `lsusb`
  - Run `gphoto2 -L`
  - At first it died with "unknown error", but if you do `gphoto2 --debug -L` you see the "insufficient permissions" message.

## Technical details

* System: 16.09.1357.9625cae (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1357.9625cae

## Workaround

I added these to my `configuration.nix`:

```
let
  gphoto2-udev-rules = pkgs.stdenv.mkDerivation {
    name = "gphoto2-udev-rules";
    phases = ["installPhase"];
    src = ./40-gphoto.rules;
    installPhase = ''
      mkdir -p $out/etc/udev/rules.d
      stripHash $src
      cp $src $out/etc/udev/rules.d/$strippedName
    '';
  };
in
{  # ... other settings ...

  users.extraGroups.camera.members = ["league"];  #  My user name
  services.udev.packages = [gphoto2-udev-rules];
}
```

where I copied the `40-gphoto.rules` file [from the ArchLinux distribution](https://www.archlinux.org/packages/extra/x86_64/libgphoto2/).

**Comment by league** [comment]
Tagging the gphoto2 maintainer @jcumming, thanks.

**Comment by Mic92** [comment]
@league you can graft a `programs` module, which does exactly this to fix this in long term.
