### ISSUE TITLE
MEGASync Out Of Date 4.6.7.0 -> 4.8.1

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#214369]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: `megasync`

current version: `4.6.7.0`
desired version: `4.8.1-1.1`

###### Notify maintainers

maintainers: @michojel 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by bbigras** [comment]
fixed by #220903
