### ISSUE TITLE
Cinnamon tracker

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#2143]
cjs: Accepted
cinnamon-desktop: Accepted. 
cinnamon-session; Accepted.
cinnamon-translations: Accepted
cinnamon-settings-daemon : Accepted. 
cinnamon-control-center: Accepted
muffin: Send in patch https://github.com/NixOS/nixpkgs/pull/2317
cinnamon: Still to be ported
nemo: Still to be ported
cinnamon-screensaver: Still to be ported,

**Comment by domenkozar** [comment]
No need for multiple issues
