### ISSUE TITLE
Packaging Request: xemu

### ISSUE THREAD

**Issue by lasers** [NixOS/nixpkgs#214348]
**Project description**

Original Xbox Emulator.

**Metadata**

* homepage URL: https://xemu.app
* source URL: https://github.com/xemu-project/xemu
* license: gpl2
* platforms: unix

**Comment by GenericNerdyUsername** [comment]
I've tried to get this working, but I'm getting a link error. Here are both of my attempts:
```
{ stdenv
, fetchFromGitHub
, lib
, qemu

, libpcap
, libsamplerate
, python3
}:

(qemu.override (_: {
  guestAgentSupport = false;
  numaSupport = false;
  seccompSupport = false;
  alsaSupport = false;
  pulseSupport = false;
  sdlSupport = true;
  jackSupport = false;
  gtkSupport = true;
  vncSupport = false;
  smartcardSupport = false;
  spiceSupport = false;
  ncursesSupport = false;
  libiscsiSupport = false;
  tpmSupport = false;
  uringSupport = false;
  hostCpuTargets = [ "i386-softmmu" ];
})).overrideAttrs (new: old: rec {
  name = "xemu";
  version = "0.7.83";

  src = fetchFromGitHub {
    owner = "xemu-project";
    repo = name;
    rev = "d0d3e7b";
    fetchSubmodules = true;
    hash = "sha256-ryL7u2sKR5nBkKNUseit8iuep0Ga6R7TwVHh1F5OQoE=";
  };

  patches = [];

  buildInputs = old.buildInputs ++ [ libpcap libsamplerate python3.pkgs.pyyaml ];

  setOutputFlags = false;

  configureFlags = old.configureFlags ++ [
    "--enable-lto"
    "--disable-werror"
  ];

  preConfigure = ''
    chmod +x ./scripts/shaderinclude.pl
    patchShebangs . >/dev/null
    configureFlagsArray+=("--extra-cflags=-DXBOX=1 -Wno-error=redundant-decls")
  '';

  meta = with lib; {
    homepage = "https://xemu.app/";
    description = "Original xbox emulator";
    maintainers = with maintainers; [ ];
    license = qemu.meta.license;
  };
})
```
```
{ stdenv
, fetchFromGitHub
, lib
, qemu

, pkg-config
, python3
, ninja
, meson
, which
, perl

, glib
, gtk3
, libpcap
, openssl
, libepoxy
, libsamplerate
, SDL2
, SDL2_image
, mesa
, libdrm
, libGLU
, gettext
, vte
}:

stdenv.mkDerivation rec {
  name = "xemu";
  version = "0.7.83";

  src = fetchFromGitHub {
    owner = "xemu-project";
    repo = name;
    rev = "v${version}";
    fetchSubmodules = true;
    hash = "sha256-L6ax7u2PL1QpTmDFM8Os0Wwj3zFWXQXqM7AGqZql1F0=";
  };

  nativeBuildInputs = [ pkg-config python3 python3.pkgs.pyyaml ninja which meson perl ];

  buildInputs = [ glib gtk3 openssl mesa libepoxy libdrm libpcap libsamplerate SDL2 libGLU SDL2_image gettext vte ];

  separateDebugInfo = true;

  dontUseMesonConfigure = true;

  setOutputFlags = false;

  configureFlags = [
    "--disable-strip"
    "--meson=meson"
    "--extra-ldflags="
    "--target-list=i386-softmmu"
    "--enable-lto"
    "--disable-werror"
    "--enable-opengl"
  ];

  buildFlags = [ "qemu-system-i386" ];

  preConfigure = ''
    patchShebangs . >/dev/null
    configureFlagsArray+=("--extra-cflags=-DXBOX=1 -Wno-error=redundant-decls")
  '';

  preBuild = ''
    cd build
    substituteInPlace ./build.ninja --replace /usr/bin/env $(which env)
  '';

  postBuild = ''
    rm -rf dist
    mkdir -p dist
    cp build/qemu-system-i386 dist/xemu
    python3 ./scripts/gen-license.py > dist/LICENSE.txt
  '';

  installPhase = ''
    runHook preInstall

    cp -r dist $out
 
    runHook postInstall
  '';

  meta = with lib; {
    homepage = "https://xemu.app/";
    description = "Original xbox emulator";
    maintainers = with maintainers; [ ];
    license = qemu.meta.license;
  };
}
```

**Comment by lasers** [comment]
I haven't tried anything. I will test this. I wanted emulators (i.e. Vita3k, xenia, etc) and emulator-related tools to be part of NixOS ecosystem too.

Yes, it worked for me. I'm seeing `xemu` just right now. I will need to test this a bit more after setting things up. Will let you know the end results after poking around and opening everything.

**Comment by lasers** [comment]
Got an issue - `xemu: GLib-GIO: No GSettings schemas are installed on the system`.

**Comment by GenericNerdyUsername** [comment]
Push what I hope is a fix, can you try it again?

**Comment by lasers** [comment]
You got that one fixed. I'm now able to select files. Now, I'm stuck at `Please insert an Xbox disc...`.  Weird thing is that the titlebar is `xemu | v`.  Not sure if that's intentional or if something got stripped.

If I restarted (after renaming ISO), I get a missing file dialog so I know it's working (i.e. xemu recognizes the file is missing), but it still throw me `Please insert an Xbox disc...` message.

**Comment by lasers** [comment]
The input screen works. It recognizes my controller and the buttons seems to be responding correctly. Taking a screenshot works too. I have finished adding necessary files. I just can't get it to load a disc.

**Comment by lasers** [comment]
Oh wait. I think I know what the problem is... I forget to do a step here. Hold on.

**Comment by lasers** [comment]
Yes! The game loads! Thank you!

**Comment by lasers** [comment]
As for `xemu | v` titlebar, the version is missing. I looked at few `xemu screenshot` Google images.
Same with version, branch, commit. 

![image](https://user-images.githubusercontent.com/852504/219124459-28f33b77-3ab0-417a-a1e1-8cf5b8902aed.png)

**Comment by GenericNerdyUsername** [comment]
the version/commit info depends on the `.git` directory being present, which is possible but makes it _really_ hard to be reproducible

**Comment by lasers** [comment]
Honestly, this is great for initial package. Version fixing can come later. I recall `citra` and `cemu` have similar issue with versioning too. `citra` reports lack of version and `cemu` reports vague version. Dolphin does it perfectly. Something for experienced coders to look into. Thank you. Please merge it. :-)

**Comment by GenericNerdyUsername** [comment]
Got the version stuff to work, also added a desktop item
