### ISSUE TITLE
Packaging request: `idris2-lsp` - Idris 2 Language Server

### ISSUE THREAD

**Issue by phijor** [NixOS/nixpkgs#214412]
**Project description**

`idris2-lsp` is a [Language Server](https://microsoft.github.io/language-server-protocol/) for [Idris 2](https://www.idris-lang.org/), the dependently typed functional programming language.

I have attempted to package the language server [here](https://gist.github.com/phijor/57c9a0a0ab233b8da54992b41001a475), but have run into an issue: The current Nix package for Idris2 does not install the _Compiler API_ (Idris) package, `idris2api`. This package is require to build the language server. Currently, I "fix" this issue by installing it in `postInstall`:

```nix
  idris2 = pkgs.idris2.overrideAttrs (attrs: {
    postInstall =
      ''
        $out/bin/idris2 --install idris2api.ipkg
      ''
      + (attrs.postInstall or "");
  });
```

I'd like to know what the proper way of patching `idris2` would be.

Pinging @wchresta @fabianhjr who are listed as maintainers of Idris in nixpkgs.

**Metadata**

* homepage URL: https://github.com/idris-community/idris2-lsp
* source URL: https://github.com/idris-community/idris2-lsp
* license: BSD-3-Clause license
* platforms: Anything that runs Idris 2

**Comment by oati** [comment]
@phijor Is your repository private? I'm getting 404 on your hyperlinks.

**Comment by fabianhjr** [comment]
I do have access to those repos (though can't currently work on packaging)

**Comment by phijor** [comment]
> @phijor Is your repository private? I'm getting 404 on your hyperlinks.

Oh this is embarrassing, I didn't notice the repo was private! I updated the OP to make stuff visible.

> I do have access to those repos (though can't currently work on packaging

Understandable. If you know of other people currently packaging Idris-related things, feel free to point me in their direction :)

**Comment by oati** [comment]
I think the best way to approach this would be to improve the `idris2` derivation.

I think `idris2` should be self-hosted by default, though I'm not sure what the best way to achieve this would be in nixpkgs. For self-hosting, the [Idris2 flake](https://github.com/idris-lang/Idris2/blob/main/flake.nix) uses a [derivation with an optional dependency](https://github.com/idris-lang/Idris2/blob/main/nix/package.nix) `idris2Bootstrap` to toggle the equivalent of this in nixpkgs:

```nix
pkgs.idris2.overrideAttrs (oldAttrs: {
  nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ pkgs.idris2 ];
  buildFlags = [ ]; # replaces [ "bootstrap" "SCHEME=scheme" ]
})
```

We could use [multiple outputs](https://nixos.org/manual/nixpkgs/stable/#chap-multiple-output) for the `idris2-api`, and for docs and bash completion while we're at it.

Build commands: https://github.com/idris-lang/Idris2/blob/main/INSTALL.md

**Comment by thelissimus** [comment]
Any updates since?

**Comment by oati** [comment]
I wrote this a while back:

https://github.com/CS-222-Idris2/nix-idris

**Comment by oati** [comment]
> I think the best way to approach this would be to improve the `idris2` derivation.
> 
> I think `idris2` should be self-hosted by default, though I'm not sure what the best way to achieve this would be in nixpkgs. For self-hosting, the [Idris2 flake](https://github.com/idris-lang/Idris2/blob/main/flake.nix) uses a [derivation with an optional dependency](https://github.com/idris-lang/Idris2/blob/main/nix/package.nix) `idris2Bootstrap` to toggle the equivalent of this:
> 
> ```nix
> pkgs.idris2.overrideAttrs (oldAttrs: {
>   nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ pkgs.idris2 ];
>   buildFlags = [ ]; # replaces [ "bootstrap" "SCHEME=scheme" ]
> })
> ```
> 
> We could maybe use a `selfhosted ? true` flag with a "self-dependency," but I don't know enough nix to know if that will work, or if there are better ways of doing it in nixpkgs.
> 
> We could use [multiple outputs](https://nixos.org/manual/nixpkgs/stable/#chap-multiple-output) for the `idris2-api`, and for docs and shell completions while we're at it.
> 
> Build commands: https://github.com/idris-lang/Idris2/blob/main/INSTALL.md

Pinging the maintainers of the `idris2` package.
@fabianhjr @wchresta

**Comment by fabianhjr** [comment]
I haven´t been using idris lately but will gladly review any merge request sent. (Also if anyone wants to be added as maintainer)

**Comment by prehonor** [comment]
> > I think the best way to approach this would be to improve the `idris2` derivation.
> > I think `idris2` should be self-hosted by default, though I'm not sure what the best way to achieve this would be in nixpkgs. For self-hosting, the [Idris2 flake](https://github.com/idris-lang/Idris2/blob/main/flake.nix) uses a [derivation with an optional dependency](https://github.com/idris-lang/Idris2/blob/main/nix/package.nix) `idris2Bootstrap` to toggle the equivalent of this:
> > ```nix
> > pkgs.idris2.overrideAttrs (oldAttrs: {
> >   nativeBuildInputs = oldAttrs.nativeBuildInputs ++ [ pkgs.idris2 ];
> >   buildFlags = [ ]; # replaces [ "bootstrap" "SCHEME=scheme" ]
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We could maybe use a `selfhosted ? true` flag with a "self-dependency," but I don't know enough nix to know if that will work, or if there are better ways of doing it in nixpkgs.
> > We could use [multiple outputs](https://nixos.org/manual/nixpkgs/stable/#chap-multiple-output) for the `idris2-api`, and for docs and shell completions while we're at it.
> > Build commands: https://github.com/idris-lang/Idris2/blob/main/INSTALL.md
> 
> Pinging the maintainers of the `idris2` package. @fabianhjr @wchresta

I got builed error : " idris2 --build idris2-lsp.ipkg
       > Uncaught error: EmptyFC:Failed to resolve the dependencies for idris2-lsp:
       >   idris2-0.6.0; network-0.6.0; linear-0.5.1; contrib-0.6.0; required lsp-lib any but no matching version is installed
       >
       > make: *** [Makefile:25: build] Error 1

**Comment by mattpolzin** [comment]
I'll close this issue unless someone wants to reopen it with a more refined request since the LSP server is now packaged at [`idris2Packages.idris2Lsp`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/idris2/idris2-lsp.nix).
