### ISSUE TITLE
zsh-completion

### ISSUE THREAD

**Issue by PierreR** [NixOS/nixpkgs#21443]
## Issue description
While using `oh-my-zsh`, after installing `zsh-completions` I have got:
```
λ ~ → ag --all 
_store_cache:46: read-only file system: /nix/store/dz2ly4dhxn2s0whmjj1z9dhpbivadb6g-oh-my-zsh-git-2016-08-01/share/oh-my-zsh//cache//_AG_OPTS
```

### Steps to reproduce
* install `oh-my-zsh` together with `zsh-completions`
* open a terminal and try: `ag --all` + TAB

As a note, the completion does work, pressing `TAB` again does give:
```
λ ~ → ag --all-t
--all-text   -- search all text files, excluding hidden ones
--all-types  -- search all text files, excluding hidden ones and not obeying ignore files (.agignore, .gitignore...)
```

## Technical details

* System: nixos
* Nix version: (run `nix-env --version`): nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1368.435b5f8
* both `oh-my-zsh` and `zsh-completions` comes from nixpkgs
* zshrc config:
```
λ ~ → cat .zshrc 
ZSH_CUSTOM=$HOME/.zsh_custom
ZSH_THEME="lambda-mod"

plugins=()

source $ZSH/oh-my-zsh.sh
source $(autojump-share)/autojump.zsh
```

**Comment by PierreR** [comment]
Using `ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh` fixes the problem.

Maybe that should be the default ?

**Comment by joachifm** [comment]
cc @NeQuissimus

**Comment by NeQuissimus** [comment]
We could probably make that `ZSH_CACHE_DIR` entry part of `oh-my-zsh`. Does it cause any harm if `zsh-completions` is not installed?

**Comment by Mic92** [comment]
@NeQuissimus I have `programs.zsh.enableCompletion = true` without having ZSH_CACHE_DIR set.

**Comment by NeQuissimus** [comment]
My NixOS blew up over the holidays. It will be a little bit before I can do this but I can take a look in the new year, unless somebody wants to fix this now

**Comment by rycee** [comment]
Sorry, I'm not a zsh user so I'm a bit out of the loop. Is this possible to fix in Nixpkgs? I've got a pull request to work around this issue in Home Manager but to my, admittedly uninformed, eye it seems like it should be fixed in Nixpkgs instead…

**Comment by periklis** [comment]
Can we assume `$HOME/.cache` to be a valid place on each users' machine? I suppose not. Oh-my-zsh let the user decide where `ZSH_CACHE_DIR` points to. You can add this in your `.zshrc` instead to hardcode a path for each user of oh-my-zsh.

**Comment by uvNikita** [comment]
@periklis But that could be a default value instead of the wrong one that is used now. And users can still change it if they want in their `.zshrc`.

**Comment by rycee** [comment]
I would suggest the default to be something like `ZSH_CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/oh-my-zsh` or `ZSH_CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/zsh`? I believe this would be according to the XDG spec:
> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

**Comment by PierreR** [comment]
Seems to work alright so I am closing this issue. Thanks for all help and support.
