### ISSUE TITLE
font-manager looks terrible

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#21454]
![font-manager-broken](https://cloud.githubusercontent.com/assets/23479333/21520672/6621b3f0-ccf6-11e6-9718-92922b8e7b05.png)
command executed: `font-manager`

Output:

```
[WARNING 12:05:15] Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[WARNING 12:05:15] [Gtk] Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.This may indicate that pixbuf loaders or the mime database could not be found.
```
## Issue description
The UI looks rather broken. E.g. the text on the left column is hardly visible, even though the window is more than large enough to display the text. From my memory this does work on other operating systems, so something must have gone wrong in the packaging. 

### Steps to reproduce
I am running it inside KDE4. 

## Technical details
16.09.git.81428dd (Flounder)

**Comment by fubarbaz** [comment]
This is highly likely an instance of the same problem as in #21463.

**Comment by vcunat** [comment]
I don't see anything bad, really, except that the left part is "too small by default" and thus not fully visible &ndash; but that can be easily worked around by dragging the splitter to the right.

/cc maintainer @romildo.

**Comment by vcunat** [comment]
BTW, I'm not getting that pixbuf error on master but still I didn't notice any difference between master and 16.09, and there's no change in the expression for this package itself.

**Comment by vcunat** [comment]
Hmm, and your screenshot is missing icons (which show for me), so these are probably missing in our wrapping.

**Comment by fubarbaz** [comment]
@vcunat Yes, you are right that the splitter can also be moved. Probably this usability problem is then an upstream issue, but the missing icons thing is a packaging problem.

**Comment by lheckemann** [comment]
`nix-env -iA nixos.gnome3.adwaita-icon-theme` might fix the icons issue. I think the problem here is that it doesn't entirely make sense for an application to depend on a specific icon theme, but it still needs to get icons from somewhere.

**Comment by vcunat** [comment]
We do insert dependencies on a default theme for gtk3 stuff.

**Comment by fubarbaz** [comment]
An obvious solution seems to be that such icon themes, which are also user dependent need to be configured as part of the user definition as a default (where the ssh public key is defined). If the user then changes the configuration at run-time, it should select another one (but only if that wouldn't fail). Additionally, a wrong run-time configuration should report a message with meta-data as to what the previously configured Nix attribute was which was used to configure it in the first place. 

Now, this scope might be a bit big, but that's what I would like to see. Having a system in which every application just doesn't work out of the box is not an interesting proposition. 

One could argue that this should be fixed in GTK3, though.

How are we going to make progress on this?

**Comment by vcunat** [comment]
> How are we going to make progress on this?

Add that theme into the wrapper, most likely.
