### ISSUE TITLE
nix is broken when gvfs is used

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#21459]
## Issue description

On NixOS, the current unstable channel, Nix fails to run:

```
building path(s) ‘/nix/store/fjafzzyg7d6b007af8vyxddnyn6c4cxm-nethack-3.6.0’
error: while setting up the build environment: unable to make filesystem ‘/run/user/1000/gvfs’ private: Permission denied
```

If I unmount this fs manually the problem is solved.

### Steps to reproduce

1. Boot into a DE which uses gvfs (Xfce should work);
2. Run `nix-build -A hello` where `hello` should be unavailable from the cache.

## Technical details

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) 5ba7f33e3a4f8ebee9944e5e7f092edf4cb57f3e (with several seemingly unrelated patches on top).

**Comment by joachifm** [comment]
I've resigned to restarting the nix-daemon when this happens.

**Comment by bjornfor** [comment]
Same issue as https://github.com/NixOS/nix/issues/1112

**Comment by abbradar** [comment]
Thanks! Let's close this.
