### ISSUE TITLE
xonotic doesn't render UTF-8

### ISSUE THREAD

**Issue by 9gay** [NixOS/nixpkgs#214550]
instead of UTF-8 characters there are often rectangles, spaces and random symbols
![kuva](https://user-images.githubusercontent.com/112729446/216769786-3fdc0c28-d469-4d8e-8054-a984a5808ce5.png)
![kuva](https://user-images.githubusercontent.com/112729446/216769822-3a87271c-d3e0-40b1-a4e1-504c60e95c70.png)
![kuva](https://user-images.githubusercontent.com/112729446/216769868-675054fc-e15c-4195-93d5-00f664cf7dd2.png)
![kuva](https://user-images.githubusercontent.com/112729446/216769928-b56270cd-2976-4353-8df1-e9808fcf584d.png)

**Comment by 9gay** [comment]
@astsmtl @umazalakain

**Comment by mxkrsv** [comment]
Same here. Xonotic should have its own Xolonium font, but somewhy that one on screenshots is used instead.
