### ISSUE TITLE
gdbgui fails to start: KeyError: WERKZEUG_SERVER_FD

### ISSUE THREAD

**Issue by milahu** [NixOS/nixpkgs#214614]
### Describe the bug

gdbgui fails to start

### Steps To Reproduce

```
gdbgui /bin/sh
```

### Notify maintainers

@yrashk @jollheef (dump_stack)

### Metadata

nixpkgs 3aafe6adf55993abab29f513a9d93d20d29a50b4

similar #182750

**Comment by deftdawg** [comment]
Same issue for me :cry: 

Looks related to this cs01/gdbgui/issues/425
