### ISSUE TITLE
Dynamic libraries with dependencies no longer link in nix-shells

### ISSUE THREAD

**Issue by zhaofengli** [NixOS/nixpkgs#214626]
### Describe the bug

Since around e3945057be467f32028ff6b67403be08285ad8c8, dynamic libraries with their own dependencies no longer link in an interactive Nix shell environment. Interestingly, everything works fine in sandboxed builds.

### Steps To Reproduce

```nix
# repro.nix
# nix-shell --pure repro.nix --run "echo \"int main(){}\">test.c; gcc -lbar test.c"
let
  pkgs = import ./. {};
  foo = pkgs.runCommandCC "libfoo" {} ''
    echo "void foo(){}">foo.c
    mkdir -p $out/lib
    gcc -shared -o $out/lib/libfoo.so foo.c
  '';
  bar = pkgs.runCommandCC "libbar" {
    buildInputs = [ foo ];
  } ''
    echo "void foo(); void bar(){ foo(); }">bar.c
    mkdir -p $out/lib
    gcc -shared -o $out/lib/libbar.so -lfoo bar.c
  '';
in pkgs.runCommandCC "repro" {
  buildInputs = [ bar ];
} ''
  echo "int main(){}">test.c
  gcc -o $out -lbar test.c
''
```

Everything works fine when built in a sandbox:

```bash
nix-build repro.nix
```

However, in a nix-shell it longer links (since around e3945057be467f32028ff6b67403be08285ad8c8):

```console
$ nix-shell --pure repro.nix --run "echo \"int main(){}\">test.c; gcc -lbar test.c"
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libfoo.so, needed by /nix/store/p3g8b38ivxsr6kyv5dd7dr5c83kq2dj8-libbar/lib/libbar.so, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: /nix/store/p3g8b38ivxsr6kyv5dd7dr5c83kq2dj8-libbar/lib/libbar.so: undefined reference to `foo'
collect2: error: ld returned 1 exit status
```

Return to ea692c2ad1afd6384e171eabef4f0887d2b882d3 and everything works fine again:

```console
$ git checkout ea692c2ad1afd6384e171eabef4f0887d2b882d3
Previous HEAD position was e3945057be4 Merge pull request #213671 from Luflosi/update/python3Packages.humanize
HEAD is now at ea692c2ad1a Merge pull request #213718 from r-ryantm/auto-update/komga

$ nix-shell --pure repro.nix --run "echo \"int main(){}\">test.c; gcc -lbar test.c"
```

This seems to affect any dynamic library with their own dependencies, like `openssl`, `nix`, and [`folly`](https://github.com/NixOS/nixpkgs/pull/214417).

### Expected behavior

Dynamic linking in a nix-shell should just work.

### Additional context

The regression occurred between ea692c2ad1afd6384e171eabef4f0887d2b882d3 and e3945057be467f32028ff6b67403be08285ad8c8.

**Comment by winterqt** [comment]
This was fixed by #213185, keeping this open until -next is merged.

**Comment by christoph-cullmann** [comment]
Thanks for fixing this, just got hit by that, too, for my KDE dev env.

**Comment by winterqt** [comment]
The fix has hit master, going to keep this pinned for a bit, though.

In case anyone comes across this: update your Nixpkgs.
