### ISSUE TITLE
Windscribe VPN CLI

### ISSUE THREAD

**Issue by williameast** [NixOS/nixpkgs#214732]
**Windscribe CLI**
_the CLI  client for the Windscribe VPN service_

* homepage URL: https://windscribe.net/guides/linux
* source URL: https://github.com/Windscribe/Desktop-App
* license: mit, bsd, gpl2+ , ... gpl2
* platforms: unix, linux, darwin, ... linux

**Comment by pluiedev** [comment]
Duplicate of #158368
