### ISSUE TITLE
Jellyfin unable to find `ffprobe`

### ISSUE THREAD

**Issue by onny** [NixOS/nixpkgs#214722]
### Describe the bug
During Jellyfin media library scan, music is not properly recognized due ffprobe not being found

### Steps To Reproduce
1. Enable Jellyfin server
2. Scan music / media files
3. See Jellyfin logs

### Expected behavior
`ffprobe` should be found and used to recognize media files

### Additional context

Snippet of the Jellyfin logs
```
Feb 05 10:35:19 picloud jellyfin[985]: [10:35:19] [ERR] [77] MediaBrowser.Providers.Music.AudioMetadataService: Error in ffprobe
Feb 05 10:35:19 picloud jellyfin[985]: System.InvalidOperationException: Cannot start process because a file name has not been provided.
Feb 05 10:35:19 picloud jellyfin[985]:    at System.Diagnostics.Process.Start()
Feb 05 10:35:19 picloud jellyfin[985]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process) in /build/source/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:line 753
Feb 05 10:35:19 picloud jellyfin[985]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken) in /build/source/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:line 493
Feb 05 10:35:19 picloud jellyfin[985]:    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken) in /build/source/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:line 533
Feb 05 10:35:19 picloud jellyfin[985]:    at MediaBrowser.Providers.MediaInfo.FFProbeAudioInfo.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken) in /build/source/MediaBrowser.Providers/MediaInfo/FFProbeAudioInfo.cs:line 77
Feb 05 10:35:19 picloud jellyfin[985]:    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken) in /build/source/MediaBrowser.Providers/Manager/MetadataService.cs:line 800
```

Setting the static full path to the Ffmpeg binary in the Jellyfin-Web settings fixes this problem. My guess is that probably Jellyfin isn't able to resolve the `ffprobe` path by using the nix-store path to the `ffmpeg` binary supplied as a command line flag by the wrapper ( possible function in the Jellyfin source https://github.com/ploughpuff/jellyfin/blob/c59cfc42b1e9a327fa2dcca858b78b49e5771962/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L354 ).

### Notify maintainers
@minijackson

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.8, NixOS, 22.11 (Raccoon), 22.11.20230203.f7543a7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - channels(onny): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by puppe** [comment]
This is probably the same issue as the following: https://github.com/NixOS/nixpkgs/issues/178123. See [this comment](https://github.com/NixOS/nixpkgs/issues/178123#issuecomment-1159814884) for the solution. You need to clear the path to ffmpeg in the UI, and then save your settings. Afterwards, Jellyfin should display and use the path that is already supplied to it via the --fmpeg command line option by the wrapper script with which Jellyfin is packaged in nixpkgs.

**Comment by onny** [comment]
Thank you @puppe this worked! Wasn't able to figure this out :) Since this will hopefully not affect any new installations in the future I guess this issue is solved :)
