### ISSUE TITLE
systemd 250.9 causes loopback to lose addresses when resuming from suspend

### ISSUE THREAD

**Issue by exzombie** [NixOS/nixpkgs#214767]
### Describe the bug
After upgrading two machines running NixOS 22.05 from nixpkgs 5d7d1d5f742e6bb57dd2e3d7b433fb4010c7af22 to 0874168639713f547c05947c76124f78441ea46c, suspend breaks networking by removing addresses from the `lo` interface. Yeah, no more `127.0.0.1` and `::1`, which causes all sorts of problems.

Commit 79decf8ea0dc9ff6e077e6fb3032302a2e0a1882 appears to be the culprit.

### Steps To Reproduce
1. Run `ip a show dev lo` and confirm that it has both `127.0.0.1` and `::1` addresses.
2. Suspend and resume.
3. Run `ip a show dev lo`; no addresses are present

### Expected behavior
The output of `ip a show dev lo` should be identical before and after suspend.

### Additional context
I noticed that, in the new generation, the log of `systemd-networkd.service` shows
```
lo: Unmanaging interface
```
where no such entries are logged in the old (i.e. working) generation. Based on this, I tested commit 79decf8ea0dc9ff6e077e6fb3032302a2e0a1882 and its parent. Indeed, the commit that introduced systemd 250.9 exhibits the problematic behaviour, whereas its parent with systemd 250.8 does not. Checking out 0874168639713f547c05947c76124f78441ea46c (which is the current version of nixos-22.05) and reverting 79decf8ea0dc9ff6e077e6fb3032302a2e0a1882 on top also fixes the problem.

### Notify maintainers
@flokli @kloenk @mic92

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-21.11.336020.2128d0aa28e, nixos-hardware, nixos-unstable-22.05pre335103.6daa4a5c045"`
 - channels(exzombie): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by flokli** [comment]
How does your system configuration, and the files in `/etc/systemd/network` look like?

**Comment by exzombie** [comment]
The two machines have very different network configurations. One is a laptop with NetworkManager and several internal networks that I need for development. The other is much simpler, with a static configuration, so that's what I'm quoting below. All I do there is rename the interfaces, although it doesn't work consistently (a separate issue), which is why there's the `wifi`/`wlan0` discrepancy in the current config.

`network.nix`:
```
{ config, pkgs, lib, ... }:

{
  networking.hostName = config.myMachineName;

  boot.extraModulePackages = [ config.boot.kernelPackages.rtl88x2bu ];

  networking.wireless.enable = true;
  networking.wireless.networks = {
    # private stuff
  };

  networking.useDHCP = false;
  networking.interfaces.wlan0.useDHCP = true;

  systemd.network.links."10-wired" = {
    matchConfig.MACAddress = "xx:xx:xx:xx:xx:xx";
    linkConfig.Name = "wired";
  };

  # There is a race with wpa_supplicant. Used to work, but hasn't for months.
  systemd.network.links."10-wifi" = {
    matchConfig.MACAddress = "xx:xx:xx:xx:xx:xx";
    linkConfig.Name = "wifi";
  };

  networking.wireguard.interfaces = {
    wg0 = {
      ips = [ "private" ];
      privateKeyFile = "/etc/secrets/wg-private.key";
      peers = [
        # private stuff
      ];
    };
  };

  networking.firewall.enable = false;

  environment.systemPackages = with pkgs; [
    wireguard-tools
  ];
}
```

Contents of `/etc/systemd/network`:
```
==> 10-wired.link <==
[Match]
MACAddress=xx:xx:xx:xx:xx:xx

[Link]
Name=wired


==> 10-wifi.link <==
[Match]
MACAddress=xx:xx:xx:xx:xx:xx

[Link]
Name=wifi


==> 40-wlan0.network <==
[Match]
Name=wlan0

[Network]
DHCP=yes
IPv6PrivacyExtensions=kernel
```

**Comment by flokli** [comment]
You also set `networking.useNetworkd` somewhere, do you?

**Comment by exzombie** [comment]
Ah yes, you are correct. I missed it as it is in a separate file that is the same for both machines. No other `networking` configuration is present, though.

**Comment by flokli** [comment]
NixOS stable is using systemd 251.10. Can you confirm if it's still an issue there?

**Comment by exzombie** [comment]
Interesting, I thought it was still on 250 because release notes mention that version.

I did a quick test and it appears that upgrading to NixOS 22.11 resolves this issue. Upgrading is an acceptable solution for me as I was planning to do it soonish anyway, I'm just waiting for the right opportunity to go through the whole of release notes. But 22.05 is supposed to be supported for a while yet; do you plan to backport a newer systemd? I could perhaps test a later release from the 250 series, even though I'm not looking forward to rebuilding webkitgtk again ;)

**Comment by flokli** [comment]
22.05 was only supported until December 2022. The previous stable release currently is only supported for one more month after the release: https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-22.05

If jumping to the current stable version will fix it for you, that'd be the easiest course of action. Unsupported old releases usually don't get hydra builds anymore either, and changing systemd would be a world rebuild.

**Comment by exzombie** [comment]
Huh, I apparently misremembered how long a release is supported, I didn't realize 22.05 is already unsupported. All the more thanks to you for taking the time for this issue.
