### ISSUE TITLE
textadept-12.0

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#214776]
_Note: At the time of opening this issue, the new release isn't available yet. I've started working on the new package, but since there are some significant changes, I wanted to get some feedback. I thought the best way to do that was to create a pull request for people to comment on. (If there's a better way to do this, let me know.)_

###### Checklist

- [x ] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)
- [ x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name: textadept
current version: 11.4
desired version: 12.0

###### Notify maintainers

maintainers: @raskin @mirrexagon @patricksjackson 

###### Note for maintainers

Please tag this issue in your PR.

**Comment by pbsds** [comment]
fixed in #214780
