### ISSUE TITLE
chromium vaapi support

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#21481]
## Issue description

Ubuntu and Debian, as far as i can tell, have a [hardware video acceleration patch](https://github.com/saiarcot895/chromium-ubuntu-build/blob/master/debian/patches/enable_vaapi_on_linux.diff) to enable chromium hardware acceleration on linux.
It seems that user-side patching for chromium is not very doable for now, maybe that's another thing that could change (but the build takes a long time anyways).

See also: https://aur.archlinux.org/packages/chromium-vaapi/

It might be a good idea to also include this patch (with updated paths).

**Comment by hyperfekt** [comment]
Is there anything speaking against including this patch? If not, should it be included by default or behind an option? If the latter, should a version with the patch be in the top level and thus built by Hydra?

**Comment by yorickvP** [comment]
The main thing with this patch is that it only applies to the chrome version it's for, and it's hard to test it working correctly (5 hours of compiling and then video playback will use less battery maybe?). Since ubuntu includes it by default that should be an okay thing to do.

**Comment by yorickvP** [comment]
Arch just added this patch. https://bbs.archlinux.org/viewtopic.php?id=244031

**Comment by hyperfekt** [comment]
That does it for me, I'll work on a PR to include this by default.

**Comment by amazari** [comment]
Hey there,
I have quite a rudimentary patch at #56794 adding the option to enable vaapi decoding. Would you mind giving it a try so we can make it mergeable?
Use it via override or overlay.
`pkgs.chromium-dev.override {
        VAAPISupport = true;
} 
`
Thanks!

**Comment by colemickens** [comment]
BTW: My PR for this was dropped, but my commit was merged into master. This can be closed.
