### ISSUE TITLE
We still support Apache 2.2

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#21484]
## Issue description

Apache 2.2 runs out of support in June of 2017, which means if we want to get it out of next stable we need to do so in the next few months.

@domenkozar what is the process of deleting a package like this?

**Comment by vcunat** [comment]
gnome-user-share still depends on it, though it might be easy to switch.

**Comment by domenkozar** [comment]
Just remove it, change all reverse dependencies so they all build, mention removal in the changelog.

**Comment by globin** [comment]
Fixed in 8769ddc
