### ISSUE TITLE
Packaging request: SiriKali

### ISSUE THREAD

**Issue by kevin-stuart** [NixOS/nixpkgs#214950]
**Project description**

SiriKali is a Qt/C++ GUI application that manages ecryptfs, cryfs, encfs, gocryptfs, fscrypt and securefs based encrypted folders

**Metadata**

* homepage URL: https://mhogomchungu.github.io/sirikali/
* source URL: https://github.com/mhogomchungu/sirikali
* license: gpl2+
* platforms: linux, darwin

**Comment by Chebuya** [comment]
Wrote a simple derivation for it

```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.stdenv.mkDerivation rec {
  version = "1.5.0";
  name = "Sirikali-${version}";

  src = pkgs.fetchurl {
    url = "https://github.com/mhogomchungu/sirikali/archive/refs/tags/${version}.tar.gz";
    sha256 = "sha256-oW9P5kKCCC2SUDgtbIivmVVfYAPbVz40r7aprbofO6I=";
  };

  patches = [
  (pkgs.fetchpatch {
    name = "hardcoded-backends.patch";
    url = "https://gist.githubusercontent.com/Chebuya/1a5b81a456bcd551b993b99bb39c8fdb/raw/0d250f357e8407f0bc04142932605538179cf6f5/patch.diff";
    sha256 = "sha256-eM88XgG6NeD627H+rerARKxKpBoTzZYGg6GUJJTc6+w=";
  })
];

  cmakeFlags = [
    "-DCMAKE_C_COMPILER=${pkgs.gcc}/bin/gcc -DCMAKE_CXX_COMPILER=${pkgs.gcc}/bin/g++ -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE"
  ];

  buildInputs = [ pkgs.qt5.qtbase pkgs.gcc pkgs.cmake pkgs.libgcrypt pkgs.gocryptfs ];
  nativeBuildInputs = [ pkgs.qt5.wrapQtAppsHook ];

  meta = with pkgs.lib; {
    homepage = https://mhogomchungu.github.io/sirikali/;
    description = "A Qt/C++ GUI front end to sshfs, ecryptfs-simple, cryfs, gocryptfs, securefs, fscrypt and encfs";
    license = licenses.gpl2Plus;
    platforms = platforms.linux;
    maintainers = [ "Chebuya" ];
  };
}
```

**Comment by Chebuya** [comment]
Wrote a simple derivation for it :d

```nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.stdenv.mkDerivation rec {
  version = "1.5.0";
  name = "Sirikali-${version}";

  src = pkgs.fetchurl {
    url = "https://github.com/mhogomchungu/sirikali/archive/refs/tags/${version}.tar.gz";
    sha256 = "sha256-oW9P5kKCCC2SUDgtbIivmVVfYAPbVz40r7aprbofO6I=";
  };

  patches = [
  (pkgs.fetchpatch {
    name = "hardcoded-backends.patch";
    url = "https://gist.githubusercontent.com/Chebuya/1a5b81a456bcd551b993b99bb39c8fdb/raw/0d250f357e8407f0bc04142932605538179cf6f5/patch.diff";
    sha256 = "sha256-eM88XgG6NeD627H+rerARKxKpBoTzZYGg6GUJJTc6+w=";
    })
  ];

  cmakeFlags = [
    "-DCMAKE_C_COMPILER=${pkgs.gcc}/bin/gcc -DCMAKE_CXX_COMPILER=${pkgs.gcc}/bin/g++ -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE"
  ];

  desktopItems = [
    (pkgs.makeDesktopItem {
      name = name;
      desktopName = "Sirikali";
      genericName = "Encryption";
      exec = "sirikali";
      icon = "sirikali";
      comment = "A Qt/C++ GUI front end to sshfs, ecryptfs-simple, cryfs, gocryptfs, securefs, fscrypt and encfs";
      categories = [ "Utility" ];
    })
  ];

  buildInputs = [ pkgs.qt5.qtbase pkgs.gcc pkgs.cmake pkgs.libgcrypt ];
  nativeBuildInputs = [ pkgs.qt5.wrapQtAppsHook ];

  meta = with pkgs.lib; {
    homepage = https://mhogomchungu.github.io/sirikali/;
    description = "A Qt/C++ GUI front end to sshfs, ecryptfs-simple, cryfs, gocryptfs, securefs, fscrypt and encfs";
    license = licenses.gpl2Plus;
    platforms = platforms.linux;
    maintainers = [ "Chebuya" ];
  };
}
```

**Comment by kevin-stuart** [comment]
Wow, that is amazing, thank you! I still have to yet try it, I had no time the last week.

Is there any chance this can be upstreamed so we can just go `nix-shell -p sirikali` or something on a nix install out of the box? How would one go about that?

**Comment by Chebuya** [comment]
> Wow, that is amazing, thank you! I still have to yet try it, I had no time the last week.
> 
> Is there any chance this can be upstreamed so we can just go `nix-shell -p sirikali` or something on a nix install out of the box? How would one go about that?

I don't think so, and unmount option doesn't work, and i don't know why honestly :(

**Comment by TomaSajt** [comment]
Completed in https://github.com/NixOS/nixpkgs/pull/237080

**Comment by kevin-stuart** [comment]
Excuse me for asking this now, but I do not quite understand what I am seeing.

When I go to https://search.nixos.org and choose "unstable" as channel, I can find a result for sirikali now.

However, if I run `nix-shell -p sirikali` as advised, I get an error:

```
error: undefined variable 'sirikali'

       at «string»:1:107:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (sirikali) ]; } ""
             |
                       ^
(use '--show-trace' to show detailed location information)
```

I then noticed that it says

```
Platforms
This package is not available on any platform.
```

in the lower right of the package of the expanded package details.

What is going on? This is the first time I have a nix package, that I found that behaves this way. Am I doing something wrong? Or is there more to this problem I am seeing?

Is it correct to reply here? Or should I have created a new issue for this? If I do not get feedback here after some time, I think I will open a new issue, but for now, I try to reply here to see if I can get help.

**Comment by TomaSajt** [comment]
@kevin-stuart the issue is that `nix-shell` uses the stable channel by default.
You'll need to use the unstable channel. I don't really know what your setup is, so you might need to do some browsing on how to install from unstable. I don't have much experience with using Nix on a non NixOS machine, sorry.

**Comment by kevin-stuart** [comment]
Thank you very much for this insight. I did not realize that nix-shell was using the stable channel. I actually had a NixOS machine that I used for testing this. According to the FAQ you just have to use `nix-shell -I nixpkgs=channel:nixpkgs-unstable -p somepackage` to use unstable. And it worked!

I am still a bit confused about the whole "This package is not available on any platform." thing. But Sirikali works on my NixOS machine now. Thank you again!

**Comment by TomaSajt** [comment]
> I am still a bit confused about the whole "This package is not available on any platform." thing. 

It looks like the package maintainer forgot to set `meta.platforms` to anything, that's why it shows that. I might open a PR which sets the supported platforms, once I get home.
