### ISSUE TITLE
wai-app-file-cgi mentions non-existant attribute

### ISSUE THREAD

**Issue by mpickering** [NixOS/nixpkgs#21498]
The common haskell configuration file defines some overrides for wai-app-file-cgi but the override for http-client no longer exists. I'm unsure whether the right thing to do is to delete the line or a more intricate fix is required.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix#L1097

**Comment by teh** [comment]
I think a simple replacement with `http-client_0_5_5` should work (that exists in `pkgs/development/haskell-modules/hackage-packages.nix`).
