### ISSUE TITLE
light broken because tries to use `/etc`

### ISSUE THREAD

**Issue by jluttine** [NixOS/nixpkgs#21499]
## Issue description

`light` doesn't work because it tries to use `/etc`.

### Steps to reproduce

```
$ light -G -v 3
error: "/etc/light does not exist and could not be created", in "src/light.c" on line 244.
error: "Initialization failed", in "src/main.c" on line 13.
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

```
$ nixos-version
17.03pre96799.571cf4f2 (Gorilla)
```

* Nix version: (run `nix-env --version`)

```
$ nix-env --version
nix-env (Nix) 1.11.4
```

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre96799.571cf4f2"
```

**Comment by bjornfor** [comment]
cc @puffnfresh, @asymmetric (from git log)

**Comment by puffnfresh** [comment]
I think you have to give it an argument to change the configuration file.

**Comment by puffnfresh** [comment]
I think I'm wrong and it doesn't work on NixOS :(

**Comment by womfoo** [comment]
@jluttine any chance you have tried using 

`programs.light.enable = true;`

in your `configuration.nix` ?

**Comment by jluttine** [comment]
No, I didn't use that configuration. Thanks! I'm not able to test whether that solves the issue now, but I believe so, so I close the issue.

I'm quite new to NixOS, is there some easy way to know if it is sufficient to just add a package to the package list or whether it should be configured separately outside the system package list? I think I have made similar mistakes before..

**Comment by Mic92** [comment]
@jluttine Unfortunately no, it would be cool to have package level documentation.
