### ISSUE TITLE
NixOS VMs: `boot.tmpOnTmpfs` tmpfs masks 9P mount-points

### ISSUE THREAD

**Issue by 8573** [NixOS/nixpkgs#21490]
## Issue description

In a NixOS virtual machine (the sort started with `run-<hostname>-vm`), there are two directories, `/tmp/shared` and `/tmp/xchg`, intended for exchanging data with the host via 9P.

If the VM's NixOS configuration includes `boot.tmpOnTmpfs = true`, that option causes an empty tmpfs to be mounted at `/tmp` *after* `/tmp/shared` and `/tmp/xchg` are mounted, thus rendering those two directories inaccessible.

### Steps to reproduce

- Build and run such a VM with `boot.tmpOnTmpfs = true`.
- With `findmnt` or `mount | grep`, note that `/tmp/shared` and `/tmp/xchg` are indeed 9P mount-points, and that `/tmp` is indeed a tmpfs.
- With `ls /tmp`, note that `/tmp` does not contain a directory named `shared` or `xchg`.

## Technical details

* System: NixOS `17.03pre97748.da70d3d (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `"17.03pre94694.fa4167c"`

**Comment by abbradar** [comment]
Can be fixed by using NixOS's `filesystems` instead of systemd's `.mount` file. This way they will be toposorted correctly.

**Comment by 8573** [comment]
I tried setting the following in the VM's configuration:

```
boot.tmpOnTmpfs = false;
fileSystems."/tmp" = {
  device = "tmpfs";
  fsType = "tmpfs";
  neededForBoot = true;
};
```

This resulted in the 9P directories being accessible, but no tmpfs being visibly mounted at `/tmp` (according to `findmnt`).

**Comment by 8573** [comment]
After rebooting the VM, the 9P directories (and their contents) are owned by root and have file mode 700, also making them inaccessible (except for root).

**Comment by 8573** [comment]
Oh, the file modes are the same as on the host, which makes sense, but raises the question of why I could access them as non-root before.

**Comment by abbradar** [comment]
It probably shouldn't be marked as `neededForBoot` but I don't immediately see why won't it work even then. Just to be sure, try it without this option -- would it work? 
-- 
Nikolay.

**Comment by abbradar** [comment]
I've fixed this; because of `mkVMOverride` you need `/tmp` mount to be defined inside `qemu-vm.nix` module, or it won't work.

**Comment by 8573** [comment]
Thanks!
