### ISSUE TITLE
`stack exec` fails to find installed executables (nix support enabled)

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixpkgs#21494]
## Issue description
`stack` fails to find `intero`, despite the latter being in ${PATH}.

### Steps to reproduce
```
deepfire@andromedae:~/src/gamesim$ nsh

[nix-shell:~/src/gamesim]$ which intero
/nix/store/68vxqg3nch8v0lbni3h2kabbzyzn7fps-ghc-8.0.1-with-packages/bin/intero

[nix-shell:~/src/gamesim]$ stack exec intero
Executable named intero not found on path: ["/home/deepfire/src/gamesim/.stack-work/install/x86_64-linux-nix/ghc-8.0.1/8.0.1/bin","/home/deepfire/.stack/snapshots/x86_64-linux-nix/ghc-8.0.1/8.0.1/bin","/nix/store/i7vid8fncc8k521ag0akr92mws6v0vs6-ghc-8.0.1/bin","/nix/store/f1ba8h5f8zwpl0ff32f755y8bp297yq5-patchelf-0.9/bin","/nix/store/9xiq017g22sp5aawphkya2wyfiwslnj9-paxctl-0.9/bin","/nix/store/cymbr3a1s7d1zj4073mb85hb0vdrr4la-coreutils-8.26/bin","/nix/store/r2g04csk4flx3v9kf5g0i3h6j7m5wfq1-findutils-4.6.0/bin","/nix/store/4l6izrwsf5kxjacy4382mlvpqhfb5z2b-diffutils-3.5/bin","/nix/store/64xlllqh7gak9kf7g608ck5axd29r98k-gnused-4.2.2/bin","/nix/store/rff8mpdyx6782qr12y65vc05f7n16qhb-gnugrep-2.27/bin","/nix/store/ls5w3k30k9f7vvg46wv43zhy7nvaam7y-gawk-4.1.3/bin","/nix/store/lsbbm5734yyga96xq4sjkgi3gvmqhwh6-gnutar-1.29/bin","/nix/store/gb1z43qn3qm8ybhw8wqbrwvvcmn160hc-gzip-1.8/bin","/nix/store/2m5r1yjck44b7fccqdif89wz30rxhw0q-bzip2-1.0.6.0.1-bin/bin","/nix/store/f0mycwxbzgj50p6958gd9n7mnx9cxk4i-gnumake-4.2.1/bin","/nix/store/hs9zk8bc1w6hc8s8k7hyl5p0sx02l25w-bash-4.3-p46/bin","/nix/store/f2bv1zcjdab3jhqa2p51vdkp6v03ia11-patch-2.7.5/bin","/nix/store/0bwaf47jwaikrgpnklxa2l9p7blq1yzj-xz-5.2.2-bin/bin"]

[nix-shell:~/src/gamesim]$  emacs --batch --eval '(load-library "intero")' --eval '(message "installedp: %s" (intero-installed-p))'
Loading /nix/store/yl5mbp2k0gh8fh2l4z9xix4i6kfr9r7p-emacs-25.1/share/emacs/site-lisp/site-start.el (source)...
Loading intero...
installedp: not-installed
```

## Technical details
* System: very recent `master`
* Nix version: latest stable as of today
* Nixpkgs version: "17.03.git.09af945e3fM" (descendant of very recent `master`)

**Comment by anderspapitto** [comment]
note that `/nix/store/68vxqg3nch8v0lbni3h2kabbzyzn7fps-ghc-8.0.1-with-packages/bin` isn't in the list of path components printed out by stack. Do you have `nix: enable: true` set?

also see my comment https://github.com/NixOS/nixpkgs/issues/21495#issuecomment-269883229 for how I would recommend to deal with this

**Comment by deepfire** [comment]
@anderspapitto, `{}` was my `config.yaml` for a long time, indeed -- but that has stopped working recently.  I'm going to try following your recipe more closely -- that is setting 'system-ghc: true`.

**Comment by deepfire** [comment]
@anderspapitto, and you are exactly right!

The combination of:
1. `nix: enable: false`, and
2. `system-ghc: true`
..is precisely enough to make stack find the nix-provided executables!

**Comment by deepfire** [comment]
Suggested action item: document this way of bringing Nix and Stack into harmony.

**Comment by deepfire** [comment]
Suggested action item: document this way of bringing Nix and Stack into harmony.

@peti?

**Comment by peti** [comment]
Please feel free to extend the documentation at https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.md.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by cdepillabout** [comment]
This has been addressed in the new Stack Nix integration documentation:

https://docs.haskellstack.org/en/stable/nix_integration/
