### ISSUE TITLE
helix to 22.12

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#215022]
###### Checklist

- [x] Checked the [nixpkgs master branch](https://github.com/NixOS/nixpkgs)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

###### Project name
`nix search` name:

current version: 22.08.1
desired version: 22.12

###### Notify maintainers

maintainers: @danth @yusdacra 

###### Note for maintainers

No PR.

**Comment by kilianar** [comment]
Your desired version is already in nixpkgs. Relevant pr: https://github.com/NixOS/nixpkgs/pull/204931

**Comment by hervyqa** [comment]
thanks. apparently it hasn't gotten into 22.11.
