### ISSUE TITLE
Riemann-tools service could use more options

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#21506]
Currently there are options

* `services.riemann-tools.enableHealth`
* `services.riemann-tools.riemannHost`

At the moment I'm really wishing there were a `riemannPort` option as well.

Though ideally I think we could support all of these:

```
  -h, --host=<s>              Riemann host (default: 127.0.0.1)
  -p, --port=<i>              Riemann port (default: 5555)
  -e, --event-host=<s>        Event hostname
  -i, --interval=<i>          Seconds between updates (default: 5)
  -t, --tag=<s>               Tag to add to events
  -l, --ttl=<i>               TTL for events
  -a, --attribute=<s>         Attribute to add to the event
  -m, --timeout=<i>           Timeout (in seconds) when waiting for acknowledgements (default: 30)
  -c, --tcp, --no-tcp         Use TCP transport instead of UDP (improves reliability, slight overhead. (Default: true)
  -u, --cpu-warning=<f>       CPU warning threshold (fraction of total jiffies) (default: 0.9)
  -r, --cpu-critical=<f>      CPU critical threshold (fraction of total jiffies) (default: 0.95)
  -d, --disk-warning=<f>      Disk warning threshold (fraction of space used) (default: 0.9)
  -s, --disk-critical=<f>     Disk critical threshold (fraction of space used) (default: 0.95)
  -o, --load-warning=<i>      Load warning threshold (load average / core) (default: 3)
  --load-critical=<i>         Load critical threshold (load average / core) (default: 8)
  -y, --memory-warning=<f>    Memory warning threshold (fraction of RAM) (default: 0.85)
  --memory-critical=<f>       Memory critical threshold (fraction of RAM) (default: 0.95)
  -k, --checks=<s+>           A list of checks to run. (Default: cpu, load, memory, disk)
```

**Comment by bjornfor** [comment]
Personally I feel having an "extraOptions" option, of (type listOf str) is fine. (Although a dedicated "port" option seems OK.)

My reasoning:

1) Programs change. Keeping NixOS options up-to-date is more work. (And annoying if you're testing out some new/old version with incompatible interface and the NixOS module insists on passing options that the program doesn't accept.
2) "man configuration.nix" is crowded enough as is. I think each "service.*" should have its own manpage, but until that happens, no need to bloat it more.

**Comment by chris-martin** [comment]
Fair, I see the maintenance hassle.

Regarding the "annoying" point: As a NixOS user, don't I *want* my build to
fail if a Nix upgrade introduces a new version of some software that
doesn't work with my previous options? Isn't failure at runtime more
annoying?

**Comment by bjornfor** [comment]
> Regarding the "annoying" point: As a NixOS user, don't I *want* my build to
fail if a Nix upgrade introduces a new version of some software that
doesn't work with my previous options? Isn't failure at runtime more
annoying?

Yes, that's true. In a way, that's the ideal situation (given "endless" manpower to maintain NixOS). But unless the module has full test coverage (for all options), I think configuration incompatibilities will be detected by end users at runtime, not buildtime. (The only way to verify the command line options is to try them.)

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by chris-martin** [comment]
As of 5bbde1e1cab31e7559fb76f0fd22aac5d1e561fe there is the `services.riemann-tools.extraArgs` option, which I think suffices.
