### ISSUE TITLE
Document NIX_REMOTE_SYSTEMS

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#21517]
The documentation for the configuration file and setup for distributed builds is extremely lacking. We need to document the setup and the [format of the configuration file](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix#L343-L353). @cleverca22 

This would also be a great time to document the process for setting up package signing on multiuser remotes.

**Comment by cleverca22** [comment]
another area that isnt documented very much, hydra will accept a : seperated list of files in NIX_REMOTE_SYSTEMS but the nix perl hook does not

**Comment by spinus** [comment]
I think this is nix feature, not nixos feature. It's documented in http://nixos.org/nix/manual/#chap-distributed-builds

NixOS as far as I could find uses buildMachines and distributedBuilds configuration attributes (they are not very well documented).

I think this ticket should be closed or a reference should be created to Nix manual.

**Comment by 3noch** [comment]
@spinus I think there is a glaring hole in documentation *somewhere*. It may not be here though. Before closing this let's at least open a ticket in the right place.

**Comment by 3noch** [comment]
But you're right that a link to the docs might be all that's needed.

**Comment by spinus** [comment]
Let me know if https://github.com/NixOS/nixpkgs/issues/24914 is good enough

**Comment by 3noch** [comment]
@spinus Perfect!
