### ISSUE TITLE
Package fxlinuxprint does not build anymore

### ISSUE THREAD

**Issue by Dehumanizer77** [NixOS/nixpkgs#215117]
### Steps To Reproduce
1. build fxlinuxprint

### Build log
```
trying https://onlinesupport.fujixerox.com/driver_downloads/fxlinuxpdf112119031.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: onlinesupport.fujixerox.com
```

### Additional context
fujixerox.com website apparently ceased to exist. The driver file is nowhere to be found on the internet. If anyone has it cached, I would appreciate if you could at least send it to me so that we can continue to use our (not so old, but really expensive) printer.

### Notify maintainers
@delan

**Comment by wegank** [comment]
https://support-fb.fujifilm.com/driver_downloads/fxlinuxpdf112119031.zip

**Comment by Dehumanizer77** [comment]
Same problem again :-/ They have moved or removed the file once again...

**Comment by wegank** [comment]
[fxlinuxpdf112119031.zip](https://github.com/NixOS/nixpkgs/files/12232817/fxlinuxpdf112119031.zip)
