### ISSUE TITLE
lld_14 with clang_14 cannot use libstdc++.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by inclyc** [NixOS/nixpkgs#215260]
### Describe the bug
llvm-tblgen can not find libstdc++.so.6. 

```
FAILED: include/llvm/IR/Attributes.inc <llvm-project>/llvm-project/build/include/llvm/IR/Attributes.inc 
cd <llvm-project>/llvm-project/build && <llvm-project>/llvm-project/build/bin/llvm-tblgen -gen-attrs -I <llvm-project>/llvm-project/llvm/include/llvm/IR -I<llvm-project>/llvm-project/build/include -I<llvm-project>/llvm-project/llvm/include <llvm-project>/llvm-project/llvm/include/llvm/IR/Attributes.td --write-if-changed -o include/llvm/IR/Attributes.inc -d include/llvm/IR/Attributes.inc.d
<llvm-project>/llvm-project/build/bin/llvm-tblgen: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Confirmed that g++/clang++ can generate correct minimal C++ binary (with libstdc++), but recently llvm-tblgen breaks.

### Steps To Reproduce
1. Use recent nixpkgs/nixos-unstable
2. build the llvm-project

LLVM Revision: d768b97424f9e1a0aae45440a18b99f21c4027ce

Flags:

```console

LLVM=~llvm-project

llvm_base="$LLVM"
build_mode="Debug"
build_dir="build"
build_base="${llvm_base}/${build_dir}"
llvm_enable_projects="clang;mlir"


cmake -DBUILD_SHARED_LIBS:STRING=On \
-DCMAKE_BUILD_TYPE:STRING=${build_mode} \
-DLLVM_APPEND_VC_REV:STRING=Off \
-DLLVM_ENABLE_LLD:STRING=On \
-DLLVM_ENABLE_PROJECTS:STRING="${llvm_enable_projects}" \
-DLLVM_LINK_LLVM_DYLIB:STRING=Off \
-DLLVM_OPTIMIZED_TABLEGEN=Off \
-DLLVM_CCACHE_BUILD:BOOL=FALSE \
-DLLVM_USE_SPLIT_DWARF=On \
-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
-DCMAKE_C_COMPILER:FILEPATH=${CC:-"gcc"} \
-DCMAKE_CXX_COMPILER:FILEPATH=${CXX:-"g++"} \
-S${llvm_base}/llvm \
-B${build_base} -G Ninja \
-DLLVM_TARGETS_TO_BUILD="host;RISCV;"

```

### Expected behavior
Compile LLVM successfully as before

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9, NixOS, 23.05 (Stoat), 23.05.20230206.5a350a8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by inclyc** [comment]
According to some of my local tests, `-DLLVM_ENABLE_LLD` is important to reproduce. BFD linker gives me other warnings:

```console
[user@system:~]$ cmake --build build
[313/5616] Linking CXX executable bin/not
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
[328/5616] Linking CXX executable bin/UnicodeNameMappingGenerator
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
[331/5616] Linking CXX executable bin/split-file
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
[333/5616] Linking CXX executable bin/yaml-bench
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
[529/5616] Linking CXX executable bin/FileCheck
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
[553/5616] Linking CXX executable bin/llvm-tblgen
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
[594/5616] Linking CXX executable bin/clang-tblgen
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: librt.so.1, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: warning: libdl.so.2, needed by lib/libLLVMSupport.so.17git, not found (try using -rpath or -rpath-link)
```

**Comment by inclyc** [comment]
CC @Ericson2314

**Comment by ocfox** [comment]
Working fine with following shell.
```nix
with import <nixpkgs> { };
pkgs.clangStdenv.mkDerivation {
  name = "test";
  nativeBuildInputs = with pkgs; [
    lld
  ];
}
```

**Comment by inclyc** [comment]
> Working fine with following shell.
> 
> ```nix
> with import <nixpkgs> { };
> pkgs.clangStdenv.mkDerivation {
>   name = "test";
>   nativeBuildInputs = with pkgs; [
>     lld
>   ];
> }
> ```

I made a nix flake that reproduces this problem:

```Nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }@inputs:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShells.default = pkgs.mkShell
          {
            nativeBuildInputs = with pkgs; [
              clang_14
              lld_14
            ];
          };
      });
}
```

https://gist.github.com/inclyc/8df38510fd141965da238c6d4d6edeca

**Comment by inclyc** [comment]
CC maintainers: @Ericson2314 @sternenseemann @lovek323 @dtzWill @primeos

**Comment by trofi** [comment]
Does `staging-next` branch work for you? Chances are it is fixed by https://github.com/NixOS/nixpkgs/pull/213185

**Comment by inclyc** [comment]
> Does `staging-next` branch work for you? Chances are it is fixed by #213185

Happy to test whether the current staging-next branch nixpkgs would solve the issue. However, after I switch to staging-next, lld_14 and clang_14 need to compile a lot of packages when I tried to enter `nix develop` shell. Is there any way to speed up the compilation? The solutions I think of are: increase the number of parallel compilations? , looking for binaryCache for staging-next?

> increase the number of parallel compilations

`nix develop` compiles the required dependencies almost sequentially, and a lot of time is spent on "configuring xx, checking for xxx" on a single core. Is there any way to increase the scale of parallelism? (I've set big-parallel option).

**Comment by trofi** [comment]
`nix develop -j <N>` should increase job parallelism. `nix develop --cores <N>` should increase build parallelism within a job. If you want to build less you can sync to latest commit hydra already built for `staging-next`. For https://hydra.nixos.org/jobset/nixpkgs/staging-next looks like 123c88b is reasonably complete.

**Comment by kidq330** [comment]
Came upon the same error down to the minimal repro when trying to build llvm with nix-provided mold. 
```
[nix-shell:~/repos/llvm-project]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-119-generic, Ubuntu, 22.04.4 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
Should I open an issue?

**Comment by nh2** [comment]
# Solution

For others that got this error when trying to link with `lld` during Nix/NixOS builds:

```
libstdc++.so.6: cannot open shared object file: No such file or directory
```

You need to use `llvmPackages.bintools`, NOT `pkgs.lld` or `llvmPackages.lld`. **Use this:**

```nix
nativeBuildInputs = [
  # provides `lld`; do NOT use `pkgs.lld` or `llvmPackages.lld` as those is not wrapped, and will cause error
  #     libstdc++.so.6: cannot open shared object file: No such file or directory
  # See https://github.com/NixOS/nixpkgs/issues/215260#issuecomment-3067161637
  llvmPackages.bintools
];
```

Found via:

* https://github.com/NixOS/nixpkgs/issues/242816 (that issue description points it out)
  * https://matklad.github.io/2022/03/14/rpath-or-why-lld-doesnt-work-on-nixos.html
    > turns out there’s more than one lld on NixOS. There’s `pkgs.lld`, the thing I have been using in the post. And then there’s `pkgs.llvmPackages.bintools` package, which also contains lld. And that version is actually wrapped into an rpath-setting shell script, the same way `ld` is. 

---

* For `mold`:
  Use `pkgs.mold-wrapped`, which makes correct wrapping, see
  * https://github.com/NixOS/nixpkgs/pull/257158
  * I had previously suggested to use `pkgs.stdenvAdapters.useMoldLinker` but I no longer recommend that, because that hacks mold in with [`NIX_CFLAGS_LINK`](https://github.com/NixOS/nixpkgs/commit/299a7bd35e552fe6e444096658d7e9ebafb038af#diff-cea9c91ed8344102b5d5fbf28eae400b8182d3b51d718f88345de8c7a187165fR210) which is invisible to and unoverridable by build tools, e.g. setting `CC_LD=lld` in `meson` will have no effect if `useMoldLinker` is in effect.
