### ISSUE TITLE
request for packaging lunarvim

### ISSUE THREAD

**Issue by jackyliu16** [NixOS/nixpkgs#215251]
**Project description**
An improved version of neovim out of the box

**Metadata**

* homepage URL:https://www.lunarvim.org/
* source URL:https://github.com/LunarVim/LunarVim
* license:  GPL-3.0 license
* platforms: unix, linux, darwin, ...

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/178488

**Comment by siph** [comment]
Closed as duplicate.
