### ISSUE TITLE
Usability: a2ps not operational when installed

### ISSUE THREAD

**Issue by spy-tech** [NixOS/nixpkgs#21521]
`a2ps` doesn't generate `foo.ps` in the example below.

Minimal example to reproduce:
```
echo a > a &&
a2ps -o foo.ps a # to make sure we don't actually send anything to the printer
a2ps: unknown medium `libpaper'
```
Work around: 
```
echo a > a &&
a2ps -o foo.ps --medium=A4 a
```

Affected NixOS versions: probably all

Related issue in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/a2ps/+bug/149551
Related issue in FreeBSD: https://lists.freebsd.org/pipermail/freebsd-ports/2014-September/095639.html
Potentially related: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=85742

```
ldd `which a2ps`
        linux-vdso.so.1 (0x00007fff67fbb000)
        libm.so.6 => /nix/store/27binbdy296qvjycdgr1535v8872vz3z-glibc-2.24/lib/libm.so.6 (0x00007f4439507000)
        libpaper.so.1 => /nix/store/87qqdhy74dfgxgbgh8k29skdrpj87s1r-libpaper-1.1.24/lib/libpaper.so.1 (0x00007f4439303000)
        libc.so.6 => /nix/store/27binbdy296qvjycdgr1535v8872vz3z-glibc-2.24/lib/libc.so.6 (0x00007f4438f65000)
        /nix/store/27binbdy296qvjycdgr1535v8872vz3z-glibc-2.24/lib/ld-linux-x86-64.so.2 (0x00007f443980c000)
```

This should probably be fixed upstream, but setting it to `A4` in Europe (as determined by the timezone of the system) and to `letter` in the US by default would be a better solution than what we have now. Feel free to implement something better.

**Comment by bennofs** [comment]
Thanks for reporting this issue! This could explain the problems I've had with my printing driver, I'm working on a fix...

**Comment by bennofs** [comment]
I let it default to letter unconditionally, since this is what `paperconf` (the command line utility) does as well. You can still override this decision by setting the `PAPERSIZE` environment variable.
