### ISSUE TITLE
Option to add extra entries to systemd-boot

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#21534]
## Issue description
While the GRUB bootloader has the `boot.loader.grub.extraEntries` and `boot.loader.grub.extraConfig` options, there is nothing similar under `boot.loader.systemd-boot`.

I have another distro on a second partition, is there a workaround for configuring systemd-boot to see it?

### Steps to reproduce
n/a

## Technical details
    System: 17.03pre97896.d15c62a
    Nix version: 1.11.4
    Nixpkgs version: 17.03pre97896.d15c62a

**Comment by siddharthist** [comment]
Perhaps this is out-of-scope? Configuration of `/boot` might not be in the same wheelhouse as `/etc`?

**Comment by lheckemann** [comment]
Yeah, I think NixOS leaves boot entries it didn't create itself alone. At least this is the case for me — my Debian boot entries appear in the NixOS-installed systemd-boot.

**Comment by siddharthist** [comment]
@lheckemann Thanks for the feedback! I'll close this as off-topic.

**Comment by michelk** [comment]
Did you manage to see the other distro?

**Comment by lheckemann** [comment]
@michelk if you have the EFI system partition mounted correctly in the other distro and install systemd-boot in it, it should in principle just add the entries which will then be detected by nixos's systemd-boot (or nixos's entires will be detected by the other distro's systemd-boot).

**Comment by michelk** [comment]
On debian I can't find a package `systemd-boot`

**Comment by lheckemann** [comment]
Sorry, didn't realise systemd-boot was not in debian. It used to have gummiboot (which is what systemd-boot was called before it moved into systemd) but apparently doesn't support systemd-boot yet. I'd say your best bet is to chainload debian's grub in that case — add something like `/boot/loader/entries/debian.conf`, with contents like
```
title Debian
efi /efi/debian/grubx64.efi
```

**Comment by michelk** [comment]
Thanks, this worked.
