### ISSUE TITLE
Python3.4

### ISSUE THREAD

**Issue by AverseABFun-windows** [NixOS/nixpkgs#215327]
Python. I want python 3.4 because Linux from scratch says to use python 3.4 and it isn't on nix.

**Metadata**

* homepage URL: python.org
* source URL: python.org/downloads/source/
* license: lots and lots of them
* platforms: everything

**Comment by wegank** [comment]
Stable LFS now [uses Python 3.10](https://www.linuxfromscratch.org/lfs/view/stable/chapter07/Python.html).

**Comment by AverseABFun-windows** [comment]
![image](https://user-images.githubusercontent.com/81586710/217589782-52e880b3-495e-4843-a4df-5800d22de55d.png)
Really?

**Comment by wegank** [comment]
`Your host system should have the following software with the minimum versions indicated.`

**Comment by AverseABFun-windows** [comment]
Oh ok nevermind then

**Comment by AverseABFun-windows** [comment]
I need to get better at reading that stuff.
