### ISSUE TITLE
Package request: Celeste

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#215322]
**Project description**

A tool that can synchronize multiple cloud providers to your computer;  including

    Dropbox
    Google Drive
    Nextcloud
    Owncloud
    WebDAV
    
 With more planned.

**Metadata**

* homepage URL: https://github.com/hwittenborn/celeste
* source URL: https://github.com/hwittenborn/celeste
* license: gplv3
* platforms: Linux

**Comment by gonzoknows** [comment]
+1 vote

**Comment by TheHolyTachanka** [comment]
Was just gonna make a issue about that
+1

**Comment by dotlambda** [comment]
Please test https://github.com/NixOS/nixpkgs/pull/215626 using
```
nixpkgs-review pr 215626
```
You should be able to run `celeste` from the shell that you're put into after a successful build.

**Comment by dotlambda** [comment]
@Krutonium @gonzoknows @TheHolyTachanka ping

**Comment by gonzoknows** [comment]
> @Krutonium @gonzoknows @TheHolyTachanka ping

Thank you, but I'll wait for the official update. Just an end users here with no coding experience

**Comment by dotlambda** [comment]
> Thank you, but I'll wait for the official update.

What official update do you mean? Someone should test the functionality before we merge the PR.

**Comment by Krutonium** [comment]
Testing Now

**Comment by Krutonium** [comment]
So the applications compiles and runs, however:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', celeste/src/login/gdrive.rs:46:18
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <O as gtk4::auto::button::ButtonExt>::connect_clicked::clicked_trampoline
   4: _g_closure_invoke_va
   5: g_signal_emit_valist
   6: g_signal_emit
   7: _gtk_marshal_VOID__INT_DOUBLE_DOUBLEv
   8: _g_closure_invoke_va
   9: g_signal_emit_valist
  10: g_signal_emit
  11: gtk_gesture_click_end
  12: g_cclosure_marshal_VOID__BOXEDv
  13: _g_closure_invoke_va
  14: g_signal_emit_valist
  15: g_signal_emit
  16: _gtk_gesture_check_recognized
  17: gtk_gesture_handle_event
  18: gtk_gesture_single_handle_event
  19: gtk_event_controller_handle_event
  20: gtk_widget_run_controllers
  21: _gtk_widget_captured_event
  22: gtk_propagate_event_internal
  23: gtk_main_do_event
  24: surface_event
  25: _gdk_marshal_BOOLEAN__POINTERv
  26: gdk_surface_event_marshallerv
  27: _g_closure_invoke_va
  28: g_signal_emit_valist
  29: g_signal_emit
  30: gdk_surface_handle_event
  31: gdk_event_source_dispatch
  32: g_main_context_dispatch
  33: g_main_context_iterate.constprop.0
  34: g_main_loop_run
  35: glib::main_context_futures::<impl glib::auto::main_context::MainContext>::block_on
  36: celeste::mpsc::Receiver<T>::recv
  37: celeste::login::login
  38: celeste::launch::launch
  39: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
  40: g_closure_invoke
  41: signal_emit_unlocked_R.isra.0
  42: g_signal_emit_valist
  43: g_signal_emit
  44: g_application_real_local_command_line
  45: g_application_run
  46: <O as gio::application::ApplicationExtManual>::run_with_args
  47: celeste::main
  ```
  
  Is what I get whenever I try to connect to any service.

**Comment by Krutonium** [comment]
Tracking down the line mentioned, it looks like it's failing to find `rclone` https://github.com/hwittenborn/celeste/blob/main/celeste/src/login/gdrive.rs#L41-L46

**Comment by Krutonium** [comment]
Yep, I did `nix-shell -p rclone --run celeste` and it all works now.

**Comment by Krutonium** [comment]
Update:
When I attempted to syncronize my Dropbox, I went to select a local folder to sync and it crashed with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.ServiceUnknown")))), Some("The name com.hunterwittenborn.Celeste.App was not provided by any .service files"), Msg { type: Error, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 268, body: Signature("s") })', celeste-tray/src/main.rs:77:25
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <O as gtk::auto::menu_item::GtkMenuItemExt>::connect_activate::activate_trampoline
   4: g_closure_invoke
   5: signal_emit_unlocked_R.isra.0
   6: g_signal_emit_valist
   7: g_signal_emit
   8: item_activated
   9: g_closure_invoke
  10: signal_emit_unlocked_R.isra.0
  11: g_signal_emit_valist
  12: g_signal_emit
  13: dbusmenu_menuitem_handle_event
  14: event_local_handler
  15: g_timeout_dispatch
  16: g_main_context_dispatch
  17: g_main_context_iterate.constprop.0
  18: g_main_context_iteration
  19: gtk_main_iteration_do
  20: gtk::auto::functions::main_iteration_do
  21: celeste_tray::main
  ```

**Comment by dotlambda** [comment]
> Tracking down the line mentioned, it looks like it's failing to find `rclone` https://github.com/hwittenborn/celeste/blob/main/celeste/src/login/gdrive.rs#L41-L46

I added rclone to the executable's `$PATH`.



> When I attempted to syncronize my Dropbox, I went to select a local folder to sync and it crashed with

No idea how to fix this. What desktop environment are you running? I hope it just works in GNOME and KDE.

**Comment by Krutonium** [comment]
> > Tracking down the line mentioned, it looks like it's failing to find `rclone` https://github.com/hwittenborn/celeste/blob/main/celeste/src/login/gdrive.rs#L41-L46
> 
> I added rclone to the executable's `$PATH`.
> 
> > When I attempted to syncronize my Dropbox, I went to select a local folder to sync and it crashed with
> 
> No idea how to fix this. What desktop environment are you running? I hope it just works in GNOME and KDE.

Sorry about the delay, I'm running on Gnome.
