### ISSUE TITLE
Build failure: playwright

### ISSUE THREAD

**Issue by adam248** [NixOS/nixpkgs#215450]
***DISCLAIMER: I just installed NixOS for the first time (about a week ago) and I am IN LOVE!!! (and have a lot of passion right now) so excuse any over the top excitment***

### Steps To Reproduce

1. build `playwright` on NixOS via the `configuration.nix`
2. run the required `playwright install` command after install
3. you will get a warning that `BEWARE: your OS is not officially supported by Playwright; downloading fallback build.`
4. if you try to run any `playwright` commands after that you get the error (see at the end):

### Additional context

[Here is the BUG on the playwright's github package](https://github.com/microsoft/playwright/issues/5501)](https://github.com/microsoft/playwright/issues/5501)

It sounds like they are willing to support NixOS if only someone from the Nix community will help them with the dependency management. 

# (This is what Nix does best people! Let's do this!)

### Notify maintainers

@techknowlogick 
@yrd 
@SuperSandro2000 

### Metadata

```
playwright open

╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgobject-2.0.so.0                              ║
║     libglib-2.0.so.0                                 ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libgio-2.0.so.0                                  ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libexpat.so.1                                    ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2                                   ║
║     libwayland-client.so.0                           ║
╚══════════════════════════════════════════════════════╝

```

**Comment by adam248** [comment]
https://github.com/microsoft/playwright

**Comment by adam248** [comment]
Can we create a single `default.nix` and offer to add it to the Microsoft repo?
I am not sure if that is the Nix way, but it might help the maintainers of the `playwright` package begin to understand how `nix` can help them even??? :kneeling_man:

**Comment by yrd** [comment]
> Is there a way to make nix use the [Microsoft playwright github repo](https://github.com/microsoft/playwright) to install directly onto NixOS?
> Can we create a single default.nix and offer to add it to the Microsoft repo?

That would be what's called an [IFD](https://nixos.wiki/wiki/Import_From_Derivation), which is not allowed in the Nixpkgs repository because it hinders parallelism while building.

>  I think the current version of playwright on nix is the Python wrapped version?

That's correct.

> but I think playwright should be a standalone package in Nix

We've actually had this discussion before: https://github.com/NixOS/nixpkgs/pull/184511#issuecomment-1236400428. Personally, I still don't think there's a need to split up the package any further than it already is. Correct me if I'm wrong, but Python shouldn't be a dependency on `playwright.browsers` (at least not on Linux, on Darwin it's a build-time dependency). So you can still set the environment variable as a described in your other issue when using the JavaScript library.

**Comment by adam248** [comment]
thanks, I seemed to have missed #184511 in my previous search.
will read though soon.
Still wondering how to get the playwright CLI working (even if I am misunderstanding the wrapped version being ok) ...
maybe a `playwright-cli` version is needed... (will try to read a bit more...)

**Comment by adam248** [comment]
After a quick second review, I can confirm that the official nix package `playwright` is not really made to be the `playwright` cli tool. It is mainly focused on being the Python library implementation of `playwright` from the [MS playwright for python repo](https://github.com/microsoft/playwright-python/). This is misleading as far as I can tell...
![image](https://user-images.githubusercontent.com/85082674/217777543-1dfc1d5b-a269-4214-bde7-4054fed85b96.png)

As this is a Python library it is not built to be used as a cli tool but rather imported into a Nix-packaged Python project.
Once again, if I have misread anything, please let me know.
I do believe that having a Nix package called just `playwright` that is a Python library is confusing...

**Comment by adam248** [comment]
no, just tried to install dependencies with the CLI and no luck... It doesn't know how to install from Nix, it is looking for Ubuntu...
```
playwright install-deps chrome
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
sh: apt-get: not found
Failed to install browser dependencies
Error: Installation process exited with code: 127

```

**Comment by adam248** [comment]
The thing is I know the browser dependencies are installed as I have `firefox` and `chrome` currently installed on my system and working.
`playwright` is just not symlinked correctly to Nix Store locations...
Any suggestion?

**Comment by yrd** [comment]
Okay, a few points here:

1. Are you running Ubuntu (or another distribution) with Nix install oder NixOS? Either way, running Playwright from Nixpkgs should work, as long as you're using the browser bundle from there as well, and not installing it through Playwright (and **not** using `playwright install` or `playwright install-deps`) .

2. The [`playwright`](https://pypi.org/project/playwright/) Python package includes a CLI. It's what you get when running `python -m playwright`. Python's packaging system (and by extension, Nixpkgs) exposes this as a `playwright` binary for convenience: 

<details>
<summary>Example</summary>

```shell
$ nix build --impure --expr 'with builtins; with getFlake "nixpkgs"; legacyPackages.x86_64-linux.python3.withPackages (p: [p.playwright])'
$ ./result/bin/python -m playwright
Usage: playwright [options] [command]

Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  install-deps [options] [browser...]    install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
  screenshot [options] <url> <filename>  capture a page screenshot
  pdf [options] <url> <filename>         save page as pdf
  show-trace [options] [trace...]        show trace viewer
  help [command]                         display help for command
```

</details>

3. `playwright install-deps chrome` won't work. This is expected, because Playwright doesn't know how to install dependencies on NixOS. You'll instead need use the browser bundle (which come with all dependencies in the closure) packaged in Nixpkgs.

All in all, if you want a CLI, try this one-liner:

```shell
PLAYWRIGHT_BROWSERS_PATH=$(nix build --print-out-paths --no-link nixpkgs#playwright.browsers) nix run nixpkgs#playwright -- open nixos.org 
```

> the official nix package `playwright` is not really made to be the `playwright` cli tool

As mentioned above, the Nixpkgs package currently points to `python3Packages.playwright`, which includes the CLI. Although when developing using Playwright, you won't actually be needing the CLI. Set the `PLAYWRIGHT_BROWSERS_PATH` environment variable to the output of `nixpkgs#playwright.browsers` instead.

> I know the browser dependencies are installed

You probably have system-wide Firefox and / or Chrome installations, which are completely independent of Playwright. In fact, this is also the case when using Playwright on non-Nix(OS), since `playwright install` would normally install custom browser builds which are only used by Playwright and nothing else.

**Comment by adam248** [comment]
1. I am running `NixOS 22.11.2345.af96094e9b8 (Raccoon) x86_64` with no other OS on my system. I also have the unstable channel enabled for a few packages, but playwright is on stable so not relevant I think.
2. This is what I believe I have misunderstood. Thank you. The CLI tool is a Python CLI script. (not a separate compiled binary.)
3. Yes, I understand that. However, I am installing `playwright` in `/etc/nixos/configuration.nix`, and there isn't any information about how to install the `browser bundle` separately that I can see. I have installed it at the user level `users.users.<myuser>. packages = with pkgs; [ playwright ];`, should it be at the system level?


```
PLAYWRIGHT_BROWSERS_PATH=$(nix build --print-out-paths --no-link nixpkgs#playwright.browsers) nix run nixpkgs#playwright -- open nixos.org
```
Thank you very much for the script, it worked beautifully. This is advanced magic that I need to learn! 

Finally, my main and last question is this, how can I setup my `configuration.nix` to have all this install on the system for easy reuse? Or is this script the only way available for now to run `playwright` directly.

Thank you very much for your help. :grinning:

**Comment by yrd** [comment]
Ah, now I see what you're trying to do 😉 If you're only looking for the CLI, try something like this:

```nix
{
  users.users.myuser.packages = [
    (pkgs.runCommand "wrapped-playwright" {} ''
      mkdir -p "$out/bin"
      makeWrapper "${pkgs.playwright}/bin/playwright" "$out/bin/playwright" \
        --set PLAYWRIGHT_BROWSERS_PATH "${pkgs.playwright.browsers}
    }))
  ];
}
```

This will create a new package with a single binary `playwright`, which is a script that executes the Playwright CLI preconfigured with the environment variable.

**Comment by adam248** [comment]
Thank you very much.
Unfortunately, I tried adding it to my `/etc/nixos/configuration.nix`, my only config file at the moment.
This is the config that builds my entire OS.
I modified your example to fit with my current config.
```
users.users.adam = {
  isNormalUser = true;
  extraGroups = [ "wheel" "docker" "video" "audio" "networkmanager" "lp" "scanner" ];
  initalPassword = "...";
  packages = with pkgs; [
    (runCommand "wrapped-playwright" {} ''
    mkdir -p "$out/bin"
    makeWrapper "${playwright}/bin/playwright" "$out/bin/playwright" \
      -- set PLAYWRIGHT_BROWSERS_PATH "${playwright.browsers}"
  '')
  # my other packages for my sys are listed here below this ^ command
  ];
};
```
Ran: `sudo nixos-rebuild switch`
And got this error:
```
building Nix...
building the system configuration...
these 4 derivations will be built:
  /nix/store/bsx7xzh0sx2c23nbn2nn3b575rzql71m-wrapped-playwright.drv
  /nix/store/ng1i7fvj43pdrxdwr5havkjm6r4lsxir-user-environment.drv
  /nix/store/6y7145wam7pc4j479basmxpyz0mvpsxp-etc.drv
  /nix/store/j0x3ajrq8i0gv0dinwkzrrbm7xw0jjw4-nixos-system-nxbx-dsktp-22.11.2483.49efda9011e.drv
building '/nix/store/bsx7xzh0sx2c23nbn2nn3b575rzql71m-wrapped-playwright.drv'...
/build/.attr-0l2nkwhif96f51f4amnlf414lhl4rv9vh8iffyp431v6s28gsr90: line 2: makeWrapper: command not found
error: builder for '/nix/store/bsx7xzh0sx2c23nbn2nn3b575rzql71m-wrapped-playwright.drv' failed with exit code 127
error: 1 dependencies of derivation '/nix/store/ng1i7fvj43pdrxdwr5havkjm6r4lsxir-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6y7145wam7pc4j479basmxpyz0mvpsxp-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j0x3ajrq8i0gv0dinwkzrrbm7xw0jjw4-nixos-system-nxbx-dsktp-22.11.2483.49efda9011e.drv' failed to build

```

I tried to add `makeWrapper` to the initial imports but it didn't work the way I thought it would.
I tried reading the docs about `makeWrapper` but they were all talking about package building not system wide configurations, so I wasn't sure how to apply the knowledge to my global config.

Should I start making a "sub" config where these special wrapper commands go? 
Then reference/include them in my main config?

**Comment by yrd** [comment]
Dammit, I forgot to add `makeWrapper` in my snippet. Try replacing the `runCommand` line with this:

`(runCommand "wrapped-playwright" { buildInputs = [ pkgs.makeWrapper ]; } ''`

**Comment by adam248** [comment]
```
      (runCommand "wrapped-playwright" { buildInputs = [ makeWrapper ]; } ''
      mkdir -p "$out/bin"
      makeWrapper "${playwright}/bin/playwright" "$out/bin/playwright" \
        --set PLAYWRIGHT_BROWSERS_PATH "${playwright.browsers}"
      '')
```

Worked like a charm!
Thank you so much.
AND I LEARNT STUFF TOOO!

`playwright open nixos.org` 
works as expected...
Nix is the coolest thing ever!

**Comment by adam248** [comment]
I used to use Arch BTW... lol

**Comment by yrd** [comment]
Awesome, glad to hear!
I'll close this for now, feel free to reopen if you find any more bugs.

**Comment by pbek** [comment]
Should the `playwright.browsers` part still work? I always get at:

```
error: attribute 'browsers' missing

       at /etc/nixos/hosts/gaia/configuration.nix:59:43:

           58|       makeWrapper "${playwright}/bin/playwright" "$out/bin/playwright" \
           59|         --set PLAYWRIGHT_BROWSERS_PATH "${playwright.browsers}"
             |                                           ^
           60|       '')
```

my config:

```nix
  users.users.omega = {
    packages = with pkgs; [
      playwright
      (runCommand "wrapped-playwright" { buildInputs = [ makeWrapper ]; } ''
      mkdir -p "$out/bin"
      makeWrapper "${playwright}/bin/playwright" "$out/bin/playwright" \
        --set PLAYWRIGHT_BROWSERS_PATH "${playwright.browsers}"
      '')
    ];
  };
```

**Comment by teto** [comment]
There was a bit of shuffling recently and playwright.browsers does'nt exist anymore pkgs/development/python-modules/playwright/default.nix . You can use `playwright-driver.browsers` instead. 
Btw I am looking for insight on how people use playwright if you wanna comment on https://github.com/NixOS/nixpkgs/issues/217693
You might be interested in trying out https://github.com/NixOS/nixpkgs/pull/227071 too

**Comment by pbek** [comment]
This went through now, thank you:

```nix
  users.users.omega = {
    packages = with pkgs; [
      playwright
      (runCommand "wrapped-playwright" { buildInputs = [ makeWrapper ]; } ''
      mkdir -p "$out/bin"
      makeWrapper "${playwright}/bin/playwright" "$out/bin/playwright" \
        --set PLAYWRIGHT_BROWSERS_PATH "${playwright-driver.browsers}"
      '')
    ];
  };
```

But when I did a `playwright install` and then a `playwright open nixos.org`, I still got:

```
[Error: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgobject-2.0.so.0                              ║
║     libglib-2.0.so.0                                 ║
║     libnss3.so                                       ║
║     libnssutil3.so                                   ║
║     libsmime3.so                                     ║
║     libnspr4.so                                      ║
║     libatk-1.0.so.0                                  ║
║     libatk-bridge-2.0.so.0                           ║
║     libcups.so.2                                     ║
║     libgio-2.0.so.0                                  ║
║     libdrm.so.2                                      ║
║     libdbus-1.so.3                                   ║
║     libatspi.so.0                                    ║
║     libX11.so.6                                      ║
║     libXcomposite.so.1                               ║
║     libXdamage.so.1                                  ║
║     libXext.so.6                                     ║
║     libXfixes.so.3                                   ║
║     libXrandr.so.2                                   ║
║     libgbm.so.1                                      ║
║     libexpat.so.1                                    ║
║     libxcb.so.1                                      ║
║     libxkbcommon.so.0                                ║
║     libpango-1.0.so.0                                ║
║     libcairo.so.2                                    ║
║     libasound.so.2                                   ║
╚══════════════════════════════════════════════════════╝]
```

**Comment by teto** [comment]
@pbek the browsers installed by `playwright install` wont work on nixos as you noticed, they can't link dynamically. Your playwright should use the browsers passed via PLAYWRIGHT_BROWSERS_PATH. What might happen (I am still new to playwright) is that playwright is picky when it comes to browser choice, the folder must be named with the same version as your plawyright. Maybe let's stop hijacking this thread and create a new one with a proper Minimal Working Example, ideally a test we could just add to nixpkgs ?

**Comment by pbek** [comment]
I need to get back to a system where I don't have nixos on first to produce a working playwright test. 😆

**Comment by pbek** [comment]
I took this over to https://github.com/NixOS/nixpkgs/pull/227071#issuecomment-1532938884.
