### ISSUE TITLE
mdcat miss mdless and its shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#215459]
### Describe the bug

mdcat has a program named mdless and its shell completion is missing.

### Notify maintainers
@SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by SuperSandro2000** [comment]
ref https://github.com/archlinux/svntogit-community/blob/packages/mdcat/trunk/PKGBUILD

**Comment by SuperSandro2000** [comment]
Thanks for the notice. I didn't know that was missing and did a PR to add it.
