### ISSUE TITLE
Cppcheck "Failed to load std.cfg"

### ISSUE THREAD

**Issue by rycee** [NixOS/nixpkgs#215462]
### Describe the bug

Running `cppcheck` with the `--std` option errors out:

``` console
$ cppcheck --std=c++20 ./src
…
Failed to load std.cfg. Your Cppcheck installation is broken, please re-install.
The Cppcheck binary was compiled without FILESDIR set.
Either the std.cfg should be available in /nix/store/mw3r6vcf8jqbiixq6d6z44lvjfxkg4xk-cppcheck-2.10/bin/cfg
or the FILESDIR should be configured. [failedToLoadCfg]
```

Seems it is trying to find configuration files inside the `bin` directory but the configuration files are available inside

    /nix/store/mw3r6vcf8jqbiixq6d6z44lvjfxkg4xk-cppcheck-2.10/share/cppcheck/cfg

### Steps To Reproduce
1. Run the command above.

### Expected behavior

Cppcheck runs successfully.

### Notify maintainers

@joachifm 

### Metadata

Tested with cppcheck from Nixpkgs rev fab09085df1b60d6a0870c8a89ce26d5a4a708c2.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.91, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/82hffg3k242whzz4ipxvjif6mkgk250i-ml9lxsmpsn6287h8wv5valam7iwnsmwa-source`

**Comment by MatthewCroughan** [comment]
This seems to be caused by https://github.com/NixOS/nixpkgs/commit/e35051ad37f117ef27b23cf86c89aad222910445 which is just a version upgrade to 2.10 from 2.9.3

It effects all `cppcheck` usage in Nixpkgs. The `rsstail` package is effected by this, and you can see the following bisect of `e35051ad37f117ef27b23cf86c89aad222910445` and the prior commit `50e4dbf35b95fd2b96718b656ebcbc6f9fa3a4ab` shows that rsstail fails to build when using the newer 2.10 version of cppcheck
```
user: matthew 🌐 swordfish in ~ took 14s 
❯ nix build github:nixos/nixpkgs/50e4dbf35b95fd2b96718b656ebcbc6f9fa3a4ab#rsstail

user: matthew 🌐 swordfish in ~ took 15s 
❯ nix build github:nixos/nixpkgs/e35051ad37f117ef27b23cf86c89aad222910445#rsstail
error: builder for '/nix/store/2vy1zfvn4r28dfd1k8l6888valq7mi3l-rsstail-2.1.drv' failed with exit code 2;
       last 10 log lines:
       > no configure script, doing nothing
       > building
       > build flags: -j32 SHELL=/nix/store/qqa28hmysc23yy081d178jfd9a1yk8aw-bash-5.2-p15/bin/bash prefix=\$\(out\)
       > gcc -O3 -Wall -DVERSION=\"2.1\" -g   -c -o r2t.o r2t.c
       > gcc -Wall -W r2t.o -lmrss -g -o rsstail
       > running tests
       > check flags: -j32 SHELL=/nix/store/qqa28hmysc23yy081d178jfd9a1yk8aw-bash-5.2-p15/bin/bash prefix=\$\(out\) VERBOSE=y check
       > cppcheck -v --enable=all --std=c++11 --inconclusive -I. . 2> err.txt
       > cppcheck: Failed to load library configuration file 'std.cfg'. File not found
       > make: *** [Makefile:39: check] Error 1
       For full logs, run 'nix log /nix/store/2vy1zfvn4r28dfd1k8l6888valq7mi3l-rsstail-2.1.drv'.
```

**Comment by rycee** [comment]
Fixed by #216118.

**Comment by SuperSandro2000** [comment]
IMO if we just close this issue the update might be created again, merged again and the same issue happens again.

**Comment by rycee** [comment]
@SuperSandro2000 I opened #216533, which does the version update. This time, hopefully, without breaking. I added an installation check to avoid future problems.

**Comment by SuperSandro2000** [comment]
Removed cppcheck as a linter #216543
