### ISSUE TITLE
pythonPackages.html5lib: revert the update

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixpkgs#21544]
## Issue description

Recently html5lib was bumped. This caused more packages to fail than I had noticed. PR's are now opened to use the older version of html5lib for certain libraries/applications, however, having multiple versions of a Python library in the same closure causes trouble, so this is something we really don't want.

Therefore, either all dependents have to be fixed in order to use the latest html5lib or we revert the html5lib bump. The former isn't going to work so I am planning to do the latter.

## Technical details

This applies to both stable and unstable.

# Related issues:

Original bump: https://github.com/NixOS/nixpkgs/pull/21299
Additional fixes: 
Calibre issue: https://github.com/NixOS/nixpkgs/issues/21504
Bleach issue: https://github.com/NixOS/nixpkgs/pull/21450
Flexget issue: https://github.com/NixOS/nixpkgs/pull/21543

cc @phanimahesh @mdorman @spacekitteh @grahamc @tari

**Comment by grahamc** [comment]
From a security perspective, the reported CVEs seem slightly contrived.

It is probably fixed in 0.99999999 which is older than our `0.999999999`.

Are there other known broken applications? Seems all the ones people have had issues with have been fixed with an update. Could we revert on stable and leave unstable?

**Comment by grahamc** [comment]
I'm OK with a revert.

**Comment by FRidh** [comment]
So far each each issue has been solved with using an older version of html5lib. This is fine along as it is only applications that use this version. As soon as a Python library needs an older version we'll run into trouble (e.g. bleach).

**Comment by phanimahesh** [comment]
Having two versions of html5lib is not a good idea, especially with their versioning scheme. I can't even read those version numbers without a finger.
Upstream code changes are significant, not sure if we can backport them as patches.
Revert seems like the lesser evil. What will be the full impact of a revert?

Short of checking everything reverse-depending on html5lib, is there any simpler heuristic to see what else broke with the update?

**Comment by FRidh** [comment]
It seems there are no more issues. Some applications use the older version of html5lib which is ok. As long as libraries don't depend on it.

**Comment by FRidh** [comment]
I haven't seen anymore issues so there doesn't seem to be any need to revert the upgrade. Closing.
