### ISSUE TITLE
teams-for-linux: JavaScript TypeError "properties of undefined (reading 'play')"

### ISSUE THREAD

**Issue by a-sebi** [NixOS/nixpkgs#215593]
### Describe the bug
Audio notifications in `teams-for-linux` do not play and a pop-up appears with a JavaScript error. The error raised is quoted below:
```
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'play')
```
A screenshot of the error is also provided which references the `nix` store path pointing to `index.js`.

### Steps To Reproduce
1. Start `teams-for-linux`.
2. Get a notification from either a direct message, or the start of a meeting.
3. Popup with error appears.

### Expected behavior
Notifications play an audio tone and do not create a Javascript error.

### Screenshots
![image](https://user-images.githubusercontent.com/9432990/217955101-b43c12c2-5762-4951-adae-f860539f7be6.png)

### Additional context
- NixOS configuration using flakes.
- `teams-for-linux` version is 1.0.45.
- Other notifications in my system work fine such as Slack and Firefox.
- Running Hyprland, Gnome is also installed. Issue is not dependent on desktop environment as it occurs in both Gnome and Hyprland.
- Using `pipewire` for audio. Config below:
```
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    config.pipewire = {
      "context.properties" = {
      "link.max-buffers" = 16; # version < 3 clients can't handle more than this
      "log.level" = 2; # https://docs.pipewire.org/page_daemon.html
      };
    };
  };
```

### Notify maintainers
@muscaln 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9, NixOS, 23.05 (Stoat), 23.05.20230202.a100acd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/n14283gcxp1l2qj0h53lngw4rl4y9xkd-source`
```

**Comment by lilyinstarlight** [comment]
Hmm, I'm surprised I haven't had this issue (and I also use sway/pipewire). I'll look into it some time in the next few days if no one else figures it out first

I also planned to update the package to 1.0.49 which may fix it, but that update is waiting on #214062 because of changes to the yarn.lock that need newer parsing for lockfile fixup

**Comment by lilyinstarlight** [comment]
@a-sebi, it seems like this might be fixed by #219393. Do you think you could give that PR a try?

**Comment by lugeha** [comment]
I still get it using the PR.

**Comment by lilyinstarlight** [comment]
> I still get it using the PR.

Can you try it again? I think I found the issue and just made another push to that PR

**Comment by a-sebi** [comment]
What's the best way to test PRs? Sorry, still fairly new to NixOS. I've tried building from a tarball with [this method](https://nix-tutorial.gitlabpages.inria.fr/nix-tutorial/first-package.html) but I'm getting an error as follows:
```
> unpacking sources
> variable $src or $srcs should point to the source
```

I also tried the method of using a tarball in my `configuration.nix` as per [here](https://dumpstack.io/1563582225_nixos_installing_software_from_pull_requests.html) but I got a different error about `attribute ‘currentSystem’ missing`.

**Comment by lilyinstarlight** [comment]
The easiest method to test is probably `nix --extra-experimental-features 'nix-command flakes' run github:NixOS/nixpkgs/refs/pull/219393/merge#teams-for-linux` when the teams-for-linux client isn't already running. That builds and runs the package from that PR

**Comment by lugeha** [comment]
I'm no longer getting the error.

**Comment by a-sebi** [comment]
Also no longer getting the error. Thanks @lilyinstarlight!
