### ISSUE TITLE
nixos-17.03 (unstable): ${package}/etc does not appear in /etc

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21556]
## Issue description

In 16.09, files from ```/nix/store/${somepackage}/etc``` were visible (via symlinks) in ```/etc```.

For example, there was ```/etc/mercurial/hgrc``` after installing ```mercurial``` (by adding it to ```environment.systemPackages``` list in ```/etc/nixos/configuration.conf```).

After upgrading to 17.03, these symlinks disappear from ```/etc```.

I tend to think that this is not a bug but a new feature. It has sense that in case if few mercurials installed each one should have own ```hgrc```. But I failed to find info about this change and mercurial is still looking for ```hgrc``` in ```/etc```.

If so, what is the roadmap?
Should ```mercurial``` and similar packages be patched in order to look for their files in nix store instead of ```/etc```  ?

**Comment by vcunat** [comment]
I'm actually surprised that `/etc/` of packages used to be visible, except perhaps in `/run/current-system/sw/etc`.  In my experience, packages often by default search the location they installed to, i.e. `"$out"/etc`.

**Comment by vcunat** [comment]
I personally believe `systemPackages` should not (by themselves) change `/etc/**`, and in many cases they probably shouldn't even read settings from there.

**Comment by volth** [comment]
It would be interesting to get feedback also about ```fontconfig``` and its xml-files in ```/etc/fonts```.
Should they actually be there or in ```/nix/store/*fontconfig*``` ?

**Comment by vcunat** [comment]
That's different &ndash; it's not through `systemPackages` &ndash; there's a special nixos module for font config that handles this.

**Comment by volth** [comment]
@vcunat I see, but is in necessary to support ```/etc/fonts``` ? If yes, what for? Does any program except fontconfig read those xml files? It prevents to use more than one fontconfig in the system (e.g. another fontconfig settings or even another library for phantomjs taking screenshots).

**Comment by vcunat** [comment]
It doesn't prevent you.  You can define `FONTCONFIG_FILE` variable; we do that already in some tests IIRC.  There's also presumption that typically users want font config to be determined by the OS, so e.g. nixpkgs on a different Linux will utilize their `/etc/fonts` and thus "be consistent with the rest of the system".

**Comment by volth** [comment]
close for a while, seems like mercurial-only issue.
