### ISSUE TITLE
dxvk - The vendored setup script is not performing the DLL overrides

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#215555]
The DXVK setup script installs the DXVK DLLS in the WINEPREFIX by copying the files. That still works. However, when it uses `wine reg` to perform the necessary DLL overrides it's not doing so correctly. Instead of overriding the Direct3D3 DLLS, it's overriding a DLL named `srcpath`. That seemed like a variable name to me, and sure enough here you can that the `srcpath` variable is missing the `$`; It should be `$srcpath`: https://github.com/NixOS/nixpkgs/blob/16e9b550259092803b1d7fcf9f98863060c22862/pkgs/misc/dxvk/setup_dxvk.sh#L264

You can see the result of this in the screenshot below:

![dxvk-srcpath](https://user-images.githubusercontent.com/13485450/217901653-a29b22fe-8070-4be6-a47f-8d3307061afa.png)

If fact, the `install_override()` and `uninstall_override()` functions expect the argument to be a path to the DLL, so perhaps `${action}_override "$(basename srcpath)"` should be `${action}_override "$srcpath"`

**Comment by reckenrode** [comment]
Thanks for the report. I’m currently working through a binutils issue on Darwin that causes the build to fail, but I’ll take a look at this next.

**Comment by reckenrode** [comment]
This was fixed in #220824.
