### ISSUE TITLE
Update request: flutter 3.3.8 → 3.7.2

### ISSUE THREAD

**Issue by gilice** [NixOS/nixpkgs#215537]
- Package name: `flutter`
- Latest released version: 3.7.0
-  Current version on the unstable channel: 3.3.8
- Current version on the stable/release channel: 3.3.8

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@babariviere  @ericdallo 
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/215754
