### ISSUE TITLE
Package request: Shopify-cli 3.x

### ISSUE THREAD

**Issue by xgroleau** [NixOS/nixpkgs#215520]
**Project description**
Cli to initialize, build, dev, and deploy Shopify apps

Note that shopify-cli 2.x is already in nixpkgs, but 3.x is not.

**Metadata**

* homepage URL: https://shopify.dev/docs/apps/tools/cli
* source URL: https://github.com/Shopify/cli
* license: mit
* platforms: linux, darwin

**Comment by Nintron27** [comment]
+1 vote
Was just about to put in a request myself. I am eager to start contributing to Nix, so if no one else takes this before the weekend I'll try to knock out a PR for it.

**Comment by Nintron27** [comment]
Seems I've bitten off more than I can chew with this one. If anyone else feels more eager or qualified don't let me hold you back. I'll perhaps keep trying to peck away at this but no idea if or when I'll get it.

**Comment by nathanscully** [comment]
I've started work on having a go packaging this up. Hopefully will share a CR within the week. 
The change moves it from Ruby to Node so it needs some work to repackage it.

**Comment by nathanscully** [comment]
I started repackaging it but the realised that nodePackages already includes @shopify/cli. It was added end of April here: https://github.com/NixOS/nixpkgs/pull/228894 

You can run it now using:  `nix shell nixpkgs#nodePackages."@shopify/cli"`

The current version of [shopify-cli in nixpkgs ](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/web/shopify-cli/default.nix#L28) is officially EOL: https://shopify.dev/changelog/cli-2-x-is-deprecated 

So 3 potential options for the existing package:
1. Deprecate and remove it. Update the top level alias to instruct users to install it via nodePackages. 
2. Update the current package to depend on the node version, and essentially duplicate the nodePackage one
3. Rename the current package to shopify-cli-2 to indicate its version 2. But given its EOL seems not the best approach.

My recommendation would be 1 (remove it) as the current version is not supported. However discoverability seems harder. Using both the web and CLI search for shopify the nodePackage one does not appear. I can see other packages, e.g. `nodePackages.eslint` if I search for `eslint`. Is it something with the @ symbol that impacts the search?

CC @onny who is listed as a maintainer for input.

**Comment by Nintron27** [comment]
The Node package `nixpkgs#nodePackages."@shopify/cli"` is non-functional. It was never tested past just a basic version command. Attempting to spin up a theme or do anything else isn't possible because the Ruby dependencies and the theme dependency aren't there either.

**Comment by nathanscully** [comment]
Ah you are right, apologies. I installed it but didn't attempt to setup any themes yet. Looks like it needs @shopify/theme for the actual theme commands. 
Ok let me go back to repackaging it and just upgrade it with all its dependencies.

**Comment by fd** [comment]
We packaged the v3 shopify cli as a flake. You can find at [mrhenry/nix-shopify-cli](https://github.com/mrhenry/nix-shopify-cli). Suggestions are very welcome.

**Comment by fd** [comment]
https://github.com/NixOS/nixpkgs/pull/324811 adds v3 to nixpkgs. It will be available in `nixos-unstable` [soon](https://nixpk.gs/pr-tracker.html?pr=324811).
