### ISSUE TITLE
`python3Packages.flax` was broken by fe0048c7f8

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#215556]
## Issue description
@mweinelt your commit https://github.com/NixOS/nixpkgs/commit/fe0048c7f8d869993b486b243dec94204bcf0c08 broke `python3Packages.flax` due to https://github.com/google/flax/issues/2707. Please test your changes with `nixpkgs-review` or at least `nix-build` before committing them to master.

Can you please issue a fix by reverting your change and downgrading to 0.6.2? There is not currently a fix available upstream.

**Comment by dotlambda** [comment]
@samuela That commit is from the regular Python batch updates. While we try to fix as many build failures as possible we can't guarantee every package continues to work. I suggest you file a PR reverting that change.

**Comment by samuela** [comment]
@dotlambda I understand that python-updates is a messy process. But in the case that you do not know or do not test whether an update will build successfully, please do not update it. There is no need to upgrade flax, and the risks of pushing untested code to master are simply much higher than the reward.

**Comment by dotlambda** [comment]
I think it would be a good idea to maintain a list of packages that shouldn't be updated in python-updates. Let's discuss that over at [#python:nixos.org](https://matrix.to/#/#python:nixos.org).

**Comment by samuela** [comment]
I think that's a great idea! will switch over to matrix
