### ISSUE TITLE
Package request: spyglass

### ISSUE THREAD

**Issue by mainrs** [NixOS/nixpkgs#215659]
**Project description**

A personal search engine, crawl & index websites/files you want with a simple set of rules.

**Metadata**

* homepage URL: https://docs.spyglass.fyi
* source URL: https://github.com/a5huynh/spyglass
* license: mit
* platforms: unix, linux, darwin

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/208977

**Comment by mainrs** [comment]
Sorry!
