### ISSUE TITLE
Build failure: libva1-minimal on unstable

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#215664]
### Steps To Reproduce

`nixos-rebuild switch` on latest unstable.

### Build log

https://gist.githubusercontent.com/YellowOnion/38dda10a7b50cad2464a5a48dd5884f9/raw/9b98cda53a4164777b7800ebab71530685ef055d/gistfile1.txt

### Notify maintainers

@SuperSandro2000 

### Metadata

``` nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.0-02440-gb8060a52c0aa, NixOS, 23.05 (Stoat), 23.05pre438971.8ba56d7c0d7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(daniel): `"home-manager"`
 - channels(root): `"nixos, nixos-unstable, nixpkgs-master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by kirillrdy** [comment]
libva1-minimal builds on unstable ( and on master )
```
nix build github:NixOS/nixpkgs/nixpkgs-unstable#libva1-minimal
```

so maybe try updating nixpkgs-unstable channel,

if issue persist, can you provide configuration to reproduce the issue ?

**Comment by YellowOnion** [comment]
it's the 32bit binary pulled by steam I think: 

```

error: builder for '/nix/store/09i95nwb112cxmz531jywzq1vp4ky8pz-libva-minimal-1.8.3.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/zyf3z4xbnjb4w53qyg5pk4xl4pimmwxd-libva-1.8.3.drv' failed to build
building '/nix/store/4mzl8sg2ixpkb13h6h8h7bgs0gwmxahd-libvirtd.conf.drv'...
error: 1 dependencies of derivation '/nix/store/22f3mdc3l9mklyf55w0d19dcmbdfj6c1-steam-run-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cmjb4lfd3d74x5iay6sqc6psibpizb7n-steam-run-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dzg6gqpr7czjjgi84kwq9naxbk086gaz-steam-usr-multi.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3cmgcvjs0sc7y681r80ivfdq982l0qmn-steam-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/b1z67274zv281a31mhxnw94pq7g3vshf-steam-run-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dy6cxrxakdqdbxychmxr9mri8p69bmaq-steam-run-fhs.drv' failed to build
error: 1 dependencies of derivation '/nix/store/83nr0rz53wvn005cwbhijl7z64n12scv-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kj8c0hz4hkmfrbrx9sjc96d1049pjnpg-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7salk1j43vlckdap6dgc4ghhs6291ik6-steam.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hkwhv91zs7p08n892cayhljnml9jjqmn-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jjlpgb64krq4bsjcg0y3f9kdgxgs455y-steam-run.drv' failed to build
error: 1 dependencies of derivation '/nix/store/if298f5z9cf4ifh0llljrnlyh2mr4wmm-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hwf1vi6ak3kfldp6z4mx036v1v0j4giw-nixos-system-Purple-Sunrise-23.05pre452935.724bfc08923.drv' failed to build
```

**Comment by YellowOnion** [comment]
@SuperSandro2000 please reopen

**Comment by SuperSandro2000** [comment]
The problem you are having is unrelated to libva-minimal and probably breaks most other source builds. If you take a look at your build logs you will notice  ``do not know how to unpack source archive /nix/store/rnjfs2snrhqifr5z2337qzjh021x68sv-source``.

For good measure I tried building  ``pkgsi686Linux.libva1-minimal`` which was already cached.

**Comment by YellowOnion** [comment]
According nixpkgs shows steam pulls `pkgsi686Linux.libva`, but the versions don't match, I will grant you that it's probably nixos-enter being shit at seting up the right environment for builds (since I'm having issues booting the system), but I still don't understand why it's not just pulling from the cache unless it 1: never builds it, or 2: fails to build and the cache is a problem.

it's just `programs.steam.enable = true` in my nixos config, and it's only just recently stopped working, atleast for this system.

**Comment by kirillrdy** [comment]
@YellowOnion 
I've added `programs.steam.enable = true` to my configuration, and it builds

you can try building it locally using
```
nixos-rebuild build --flake github:kirillrdy/dotfiles#shinseikai
```
it also built libva from source but without issues,

this is also on "x86_64-linux"

1) if you remove `programs.steam.enable = true` ? does it build passes ? ( just checking )
2) if so, then you need to try disabling other parts of your configuration ( overlays etc )

also, if you can provide steps to try reproduce the issue, i would be happy to give it a try

**Comment by YellowOnion** [comment]
I pulled the package and then built the system, and then booted it, and reenabled the package and it rebuilt fine, I guess something weird about the host os leaking in to the chroot.
