### ISSUE TITLE
xdot: crashes when used from a buildEnv

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#215675]
### Describe the bug

The `xdot` attribute doesn't seem to be properly wrapped and fails to find its python dependencies when used through a `buildEnv` (e.g. `environment.systemPackages`)

### Steps To Reproduce
1. Try `nix-shell -p xdot --command xdot` and it works fine
2. Try `nix-shell xdot-shell.nix --command xdot` with `buildEnv`-based `xdot-shell.nix` attached below, and it fails with `ValueError: Namespace Gtk not available`

### Expected behavior

That `xdot` works regardless

---

```nix
# xdot-shell.nix
with (import <nixpkgs> { });

let
  env = buildEnv {
    name = "could-be-system-path";
    paths = [ xdot ];
  };
in

mkShell {
  packages = [ env ];
}
```

**Comment by kirillrdy** [comment]
@SomeoneSerge 
I tied using your `xdot-shell.nix`, and it worked for me,

I pinned  nixpkgs to latest master, give this a try
```nix
# xdot-shell.nix
with (import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/ef28602c852604fc9c0381f217938d08e005514f.tar.gz") { });

let
  env = buildEnv {
    name = "could-be-system-path";
    paths = [ xdot ];
  };
in

mkShell {
  packages = [ env ];
}

```

```
nix-shell xdot-shell.nix --command xdot
```

**Comment by SomeoneSerge** [comment]
Ouch, you're right. I should've checked the master myself. For the reference, the error can be reproduced with this revision of nixpkgs:

```
# xdot-shell.nix
with (import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/285b3ff0660640575186a4086e1f8dc0df2874b5.tar.gz") { });

let
  env = buildEnv {
    name = "could-be-system-path";
    paths = [ xdot ];
  };
in

mkShell {
  packages = [ env ];
}
```

Closing the issue since it works on the current master and unstable
