### ISSUE TITLE
"nixos-container destroy" cannot delete /var/lib/container/$name/var/emply

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21573]
## Issue description

```nixos-container destroy``` cannot delete ```/var/lib/container/$name/var/emply``` due to its [immutable attribute](https://github.com/NixOS/nixpkgs/blob/6da8b0d/nixos/modules/system/activation/activation-script.nix#L149) 

### Steps to reproduce

```
nixos-container create aaa
nixos-container start aaa
nixos-container stop aaa
nixos-container destroy aaa
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
NixOS 17.03 unstable

* Nix version: (run `nix-env --version`)
1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre98014.5f1ebf8"

**Comment by fpletz** [comment]
This PR introduced that behaviour: #18365
