### ISSUE TITLE
Build failure: rustup - OOM with 16GB RAM

### ISSUE THREAD

**Issue by snoopdouglas** [NixOS/nixpkgs#215711]
### Steps To Reproduce

1. build rustup

### Build log

https://gist.github.com/snoopdouglas/971a07fb0c3f7c8ce2e937356a9f3ec6

### Additional context

I'm running this on a system with 16GB RAM, no swap. Here's what System Monitor looked like just before the OOM:

![Screenshot from 2023-02-10 18-30-19](https://user-images.githubusercontent.com/4892574/218170357-f69ddee4-a3ec-4676-a310-d538ce7c7beb.png)

### Notify maintainers

@mic92

nb. @vcunat upgraded rustup to 1.25.2 yesterday.

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
~ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.92, NixOS, 22.11 (Raccoon), 22.11.2483.49efda9011e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mlen** [comment]
For me it failed while executing tests: https://gist.github.com/mlen/ca19ab9a5e21c97b43d1571c2d12c9af

**Comment by vcunat** [comment]
If you have only 1 G RAM per thread (my guess), this can happen with various packages.  Some are just expensive to build.

**Comment by mlen** [comment]
My machine has 128GiB and it still failed, but for a different reason (as seen in the gist).

**Comment by vcunat** [comment]
That's log from the old version.  Issue that I fixed by updating to .2

**Comment by mlen** [comment]
@vcunat any chance to include it in 22.11 too?

**Comment by vcunat** [comment]
Channels take some time; see https://nixos.wiki/wiki/Nix_channels#Channel_update_process

**Comment by mlen** [comment]
Thanks for the explanation!

**Comment by snoopdouglas** [comment]
I should note that rustup installed for me fine beforehand at 1.25.1, I think because it wasn't attempting to build from source.

As 1GB/thread isn't (I'd imagine) that uncommon, I wonder whether this is indicative of a deeper problem; should derivations that build from source specify minimum system requirements, or moderate their resource usage in some way? The OOM killer took down my WM when running `nixos-rebuild` in this case, meaning I lost some work.

**Comment by Atemu** [comment]
This is not a Nixpkgs issue.

If your hardware can't handle a build at full core breadth, it's up to you to reduce parallelism.

If a Nix build can cause your WM to get reaped, you need to fix that. Decrease its OOM score and increase Nix builds' OOM scores.  
Also, you need swap.

There isn't really anything we can do here. Moderating resource usage is up to the build processes themselves and they likely won't care either.  
We already provide some knobs if you're resource-constrained. Automatic systems here would add unwanted complexity.

**Comment by vcunat** [comment]
I can generally recommend setting `zramSwap.enable = true;`

**Comment by Mic92** [comment]
If the build requires much more ram per build core than what it's "common" we can also in general reduce parallelism. Most of the time rustup will be build in CI anyway.
