### ISSUE TITLE
TexLive classico package missing

### ISSUE THREAD

**Issue by sid-kap** [NixOS/nixpkgs#21577]
I'd like to use `pkgs.texlive.classico` ([listed on CTAN here](https://www.ctan.org/pkg/classico)), but for some reason it doesn't seem to be in nixpkgs. Has someone outlined how packages are added to Nix texlive somewhere, so that I can troubleshoot it and figure out why the classico not being added?

**Comment by Mic92** [comment]
Not all packages on CTAN are part of texlive. We had a similar question here: https://github.com/NixOS/nixpkgs/issues/21334

**Comment by veprbl** [comment]
I think @Mic92's answer explains it all. The reason why classico cannot be included in the texlive upstream is because it's not licensed under a "free software" license. This doesn't mean that we couldn't package it in nixpkgs, but it would not be a part of our texlive package.
