### ISSUE TITLE
Unity3d permission error

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nixpkgs#21579]
## Issue description

Unity seems to have some thoughts on the sandbox file's permissions: 

```
Chromium Embedded Framework requires that the file '/nix/store/r911yc6y8yvw9s5ifrf7sxlgavzkc5qh-unity-editor-5.3.5f1/opt/Unity/Editor/chrome-sandbox' is owned by root and has permissions 4755.
```

![2017-01-02-115549_543x160_scrot](https://cloud.githubusercontent.com/assets/31167/21588052/0a32b044-d0e3-11e6-82be-c18f942b80c4.png)

### Steps to reproduce

```
% nix-shell -p unity3d --command unity-editor
```

## Technical details

* System: 1fa75a5bb7cdb9f2413d8b20726ce69523bfe4c6
* Nix version: 1.11.4
* Nixpkgs version: `"17.03.git.b02e6cc70d"`

**Comment by abbradar** [comment]
You need to install Chromium SUID binary (`security.chromiumSuidSandbox.enable = true;`).

**Comment by the-kenny** [comment]
Thanks, that works! Is this documented somewhere?

Nikolay Amiantov <notifications@github.com> writes:

> You need to install Chromium SUID binary (`security.chromiumSuidSandbox.enable = true;`).
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/issues/21579#issuecomment-269967595

--

**Comment by abbradar** [comment]
Nope. I'm not sure where exactly we want to document this to be visible enough -- any ideas?

**Comment by velovix** [comment]
It seems like the wiki would be a good place to document this. Packages that have gotchas seem to be documented there. For instance, see the one on PCManFM: https://nixos.wiki/wiki/PCManFM
