### ISSUE TITLE
awscli upgrade

### ISSUE THREAD

**Issue by spy-tech** [NixOS/nixpkgs#21591]
Current version is 1.11.30 in nixpkgs. Newest version is 1.11.35.

**Comment by Mic92** [comment]
@spy-tech do you want to make a pull request?

**Comment by LnL7** [comment]
I expect this to be fairly straightforward, since it's a minor update. https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L1510-L1551

**Comment by spy-tech** [comment]
@Mic92 Yes, I will do so. I believe I already got it it to work on my machine. It also required upgrading a different package.
