### ISSUE TITLE
Roundcube: Passwordfile failing with non-local PostgreSQL

### ISSUE THREAD

**Issue by everlanes** [NixOS/nixpkgs#215986]
### Describe the bug
I tried to install Roundcube with an non-local PostgreSQL. The DB user password should be stored in a password file.

I ran into problems with this setup: the password file is used in two locations:
1. in the Roundcube [config.php](https://github.com/NixOS/nixpkgs/blob/21f23dd537d996ea64b695cb97c53d0331bf5752/nixos/modules/services/mail/roundcube.nix#L127)
2. in the systemd [setup service](https://github.com/NixOS/nixpkgs/blob/21f23dd537d996ea64b695cb97c53d0331bf5752/nixos/modules/services/mail/roundcube.nix#L226) that initializes the roundcube database

Unfortunately the neccessary file content differs for these two services:
1. For the roundcube config.php the passwordfile should only contain the PASSWORD (even without a trailing newline)
2. psql expects an entry like "hostname:port:database:username:password" ([see here](https://www.postgresql.org/docs/current/libpq-pgpass.html))

So one of these two services will fail.

### Steps To Reproduce
Setup Roundcube with remote PostgreSQL server and password file for DB user password.

### Additional context
My solution for now would be, to add a line to the roundcube config.php:
```
$password = file_get_contents('/var/lib/roundcube/postgresql');
$password = end(explode(":", $password));
```

### Notify maintainers
@symphorien 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.53, NixOS, 22.05 (Quokka), 22.05.1627.4aceab3cadf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Cheers, Andreas

**Comment by symphorien** [comment]
Your solution sounds reasonable to me, if you replace `explode` with something that takes into account escaped `:`. Would you mind opening a PR? Tag me on it, I'll review it.

As you can see the remote db feature of the module has probably never been used except by you; if you want this use case to be better maintained consider contributing a nixos test exercising it.

**Comment by symphorien** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/227782
