### ISSUE TITLE
Sway does not start with WLR_RENDERER=vulkan on Nvidia

### ISSUE THREAD

**Issue by suhr** [NixOS/nixpkgs#216002]
### Describe the bug
With `WLR_RENDERER=vulkan` and Nvidia proprietary drivers, sway terminates with the ERROR_LAYER_NOT_PRESENT error.

### Steps To Reproduce
1. Use NVidia proprietary driver
2. Add `WLR_RENDERER=vulkan` to session variables
3. Try to run sway

### Expected behavior
Sway should run with Vulkan as renderer.

### Additional context
Using Sway with OpenGL renderer results in flickering. To fix that, Hyprland Wiki [suggests to patch wlroots](https://wiki.hyprland.org/Nvidia/#fixing-random-flickering-method-1). But the vulkan renderer should be a more principled solution for this kind of issues.

### Notify maintainers

@primeos @synthetica 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.10, NixOS, 23.05 (Stoat), 23.05.20230209.724bfc0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(suhr): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by QuantMint** [comment]
This is a wlroots specific [issue](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3283), it has already been [fixed upstream](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3850), but the latest version doesn't contain the fix yet.
