### ISSUE TITLE
less / lesspipe: no strings command when decompressing brotli file.

### ISSUE THREAD

**Issue by YellowOnion** [NixOS/nixpkgs#216087]
### Describe the bug

```
$ less log.br
==> (lesspipe 2.07) append : to filename to view the original brotli file
/nix/store/ffq874rlpwjgj2ix6varyj483bbn05mb-lesspipe-2.07/bin/.lesspipe.sh-wrapped: line 195: strings: command not found
```
### Notify maintainers
@martijnvermaat 

```
 nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.10-bcachefs-5fc458d, NixOS, 23.05 (Stoat), 23.05pre452935.724bfc08923`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(daniel): `"home-manager"`
 - channels(root): `"nixos, nixos-unstable, nixpkgs-master"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by YellowOnion** [comment]
According to documentation of the app: https://github.com/wofr06/lesspipe#3-required-programs

there's a dozen dependencies we don't explicitly have a dependency on, so there's multitude of bugs that might appear depending on what's on $PATH.

**Comment by roconnor** [comment]
Do we need a new maintainer of `lesspipe` to move this issue forward?

**Comment by YellowOnion** [comment]
We should pull the package from NixOS core...absolutely no reason to have such a bloated less ship by default.
