### ISSUE TITLE
yarn2nix: `pkgsCross.aarch64-multiplatform.yarn2nix` fails to build

### ISSUE THREAD

**Issue by nagisa** [NixOS/nixpkgs#216061]
### Describe the bug

Building `pkgsCross.aarch64-multiplatform.yarn2nix` fails with the following error:

```
error: makeWrapper/makeShellWrapper must be in nativeBuildInputs
… while evaluating the attribute 'shell' of the derivation 'hook' 
… while evaluating the attribute 'nativeBuildInputs' of the derivation 'yarn2nix-1.0.0-x86_64-unknown-linux'
… while evaluating the attribute 'buildCommand' of the derivation 'yarn.nix'
...
```

### Steps To Reproduce

1. Checkout the nixpkgs repository and go into the checkout;
1. `nix-build . -A pkgsCross.aarch64-multiplatform.yarn2nix`.

### Expected behavior
This should build and give a working yarn2nix.

### Notify maintainers

None are specified

### Metadata

The reproduction has been confirmed at 469aec905bab3be98838c7eb996ceffb2ea44404.

**Comment by doronbehar** [comment]
yarn2nix is deprecated, see https://github.com/NixOS/nixpkgs/issues/324246 . If you want to talk about cross compilation support in general for yarn packages that's legitimate, but there is no point in discussing it in Nixpkgs' sphere when it is not clear if the Yarn ecosystem even supports that in principal. In either case, I'm closing this issue so this should be discussed in a separate, more concise issue.
