### ISSUE TITLE
Retire committers who haven't contributed since 2022-01-01 (RFC55)

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#216177]
https://github.com/NixOS/rfcs/blob/master/rfcs/0055-retired-committers.md

Reporting from 2022-01-01 00:00:00
RateLimit(core=Rate(remaining=4233, limit=5000))
- @aycanirican          https://github.com/NixOS/nixpkgs/commits?author=aycanirican
- @basvandijk           https://github.com/NixOS/nixpkgs/commits?author=basvandijk
- @cleverca22           https://github.com/NixOS/nixpkgs/commits?author=cleverca22
- @cpages               https://github.com/NixOS/nixpkgs/commits?author=cpages
- @elseym               https://github.com/NixOS/nixpkgs/commits?author=elseym
  - related: https://github.com/NixOS/nixpkgs/pull/180157
- @falsifian            https://github.com/NixOS/nixpkgs/commits?author=falsifian
- <del>GrahamcOfBorg        https://github.com/NixOS/nixpkgs/commits?author=GrahamcOfBorg</del>
- @lilyball             https://github.com/NixOS/nixpkgs/commits?author=lilyball
- @LnL7                 https://github.com/NixOS/nixpkgs/commits?author=LnL7
- @nbp                  https://github.com/NixOS/nixpkgs/commits?author=nbp
- @obadz                https://github.com/NixOS/nixpkgs/commits?author=obadz

@tilpner @grahamc @Mic92

**Comment by mweinelt** [comment]
@aycanirican @basvandijk @cleverca22 @cpages @falsifian @lilyball @LnL7 @nbp @obadz

**Comment by falsifian** [comment]
No objection from me. I don't use nix much right now.

**Comment by domenkozar** [comment]
Removed listed members, note that you can reapply for commit access if you wish so!

**Comment by obadz** [comment]
Hi both,

I'm not a frequent contributor by any stretch but I did review a handful of PRs from 2022 (and some from early 2023):

### 2022
#159856 created on 2022-02-13
#174305 created on 2022-05-24
#190656 created on 2022-09-10
#193270 created on 2022-09-28
#196987 created on 2022-10-20
#199206 created on 2022-11-02
#201593 created on 2022-11-17

### 2023
#208566 created on 2023-01-01
#208740 created on 2023-01-02
#209133 created on 2023-01-05
#209476 created on 2023-01-07
#211884 created on 2023-01-21

It seems that because I did not select the option to create a merge commit, the reference implementation script in the RFC does not see any of these. Instead I'd suggest something like the below to see who merged each PR (unfortunately it's slower as it requires loading each PR individually):

```python
import bz2
import json
from datetime import datetime
from pathlib import Path
from time import sleep
from typing import Dict, Any

import requests

# https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
GITHUB_TOKEN = '<YOUR_TOKEN_HERE>'
GITHUB_OWNER = 'NixOS'
GITHUB_REPO = 'nixpkgs'
MIN_PR_NUMBER = 149645
MAX_PR_NUMBER = 1_000_000


def get_github_url_data(session: requests.Session, endpoint: str, cache_key: str) -> Any:
    print(endpoint)

    cached_file_name = f"{cache_key}.json.bz2"
    if Path.exists(Path(cached_file_name)):
        with bz2.open(cached_file_name, 'rb') as f:
            content = f.read()
    else:
        headers = {'Authorization': 'token ' + GITHUB_TOKEN}
        url = f"https://api.github.com{endpoint}"
        result = session.get(url, headers=headers)

        if retry_after := result.headers.get('Retry-After'):
            print(f"Retry-After: {retry_after}")

        while result.status_code == 403 and (ratelimit_reset := result.headers.get('X-RateLimit-Reset')) is not None:
            need_to_sleep_for = int(ratelimit_reset) - datetime.now().timestamp() + 5
            print(f"Sleeping {need_to_sleep_for}s due to rate limiting...")
            sleep(need_to_sleep_for)
            result = session.get(url)

        result.raise_for_status()
        content = result.content

        with bz2.open(cached_file_name, 'wb') as f:
            f.write(content)

    data = json.loads(content)

    return data


def fetch_merge_data() -> Dict[str, Dict[str, str]]:
    session = requests.Session()
    page = 1

    merged_by: Dict[str, Dict[str, str]] = dict()
    while True:
        try:
            page_data = get_github_url_data(
                session,
                f"/repos/{GITHUB_OWNER}/{GITHUB_REPO}/pulls?state=closed&page={page}&per_page=100",
                f"page-{page:04d}",
            )

            for pull_info in page_data:
                pull_number = int(pull_info['number'])

                if pull_number < MIN_PR_NUMBER:
                    raise StopIteration

                if pull_number <= MAX_PR_NUMBER:
                    pull_data = get_github_url_data(
                        session,
                        f"/repos/{GITHUB_OWNER}/{GITHUB_REPO}/pulls/{pull_number}",
                        f"pull-{pull_number}",
                    )

                    if pull_data.get('merged'):
                        login = pull_data['merged_by']['login']
                        time = datetime.fromisoformat(pull_data['created_at'].replace('Z', '+00:00'))
                        print(f"#{pull_number} created on {time} was merged by {login}")
                        merged_by.setdefault(login, {})[str(pull_number)] = str(time)

            page += 1

        except KeyboardInterrupt:
            print('Ctrl+C')
            break

        except StopIteration:
            break

    return merged_by


if __name__ == '__main__':
    merged_by = fetch_merge_data()

    with open('merged_by.json', 'wt') as f:
        json.dump(merged_by, f, indent=4, sort_keys=True)
```

**Comment by Mic92** [comment]
I think for simplicity we should just click on each link because you can see commits in there. (could be a comment in the output of a script).

**Comment by mweinelt** [comment]
Click on the link for obadz and the last interaction you see is 2021/10.

https://github.com/NixOS/nixpkgs/commits?author=obadz

**Comment by Mic92** [comment]
> Click on the link for obadz and the last interaction you see is 2021/10.
> 
> https://github.com/NixOS/nixpkgs/commits?author=obadz

Yeah but this says otherwise: https://github.com/NixOS/nixpkgs/pull/159856

**Comment by mweinelt** [comment]
> Removed listed members, note that you can reapply for commit access if you wish so!

They should have been added to https://github.com/orgs/NixOS/teams/retired-nixpkgs-contributors/members

**Comment by obadz** [comment]
> Mhm it seems to show merge commits in 2021 but than it stopped doing this for 2022.

Probably because I clicked rebase instead of merge?

**Comment by obadz** [comment]
Running a bit more analysis on the data collected with the above script, it seems 20.2% of 2022 reviews were *self* merged and a total of 155 contributors did this at least once.

It seems to be me, from a security standpoint, it would be highly desirable to restrict self-merge rights to a very small number of highly trusted contributors (which probably should be counted on one hand), if any.

**Comment by 7c6f434c** [comment]
> It seems to be me, from a security standpoint, it would be highly desirable to restrict self-merge rights to a very small number of highly trusted contributors (which probably should be counted on one hand), if any.

From a security point of view, this would be a pointless security theater with some real harm to development throughput. 

You cannot check for person-self-merges, only for the same-account merges. And we do have some fine contributions from fresh accounts.

**Comment by obadz** [comment]
> You cannot check for person-self-merges, only for the same-account merges.

That's a very good point, but nevertheless the current situation is a bit worrisome. Don't know what the right fix for this is.
