### ISSUE TITLE
Update request: mesa 22.3.4 → 22.3.5

### ISSUE THREAD

**Issue by amz-x** [NixOS/nixpkgs#216137]
- Package name: mesa
- Latest released version: 22.3.5
- Current version on the unstable channel: 22.3.4
- Current version on the stable/release channel: 22.2.5
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Release Notes: https://docs.mesa3d.org/relnotes/22.3.5.html

**Notify maintainers**

@primeos @vcunat 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by vcunat** [comment]
22.3.5 included in `staging` branch.

**Comment by amz-x** [comment]
Thank you @vcunat!
