### ISSUE TITLE
Shavee

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixpkgs#216172]
**Project description**
Shavee is a Program to automatically decrypt and mount ZFS datasets using Yubikey HMAC as 2FA or any File on USB/SFTP/HTTPS drive with support for PAM to auto mount home directories. 

**Metadata**

* homepage URL:https://ashu.io/projects/shavee/
* source URL:https://github.com/ashuio/shavee
* license: mit
* platforms: unix, linux, darwin, ...

**Comment by jasonodoom** [comment]
I'm working on this. I contacted @ashuio to tag the latest version as the current is alpha and is missing a `Cargo.lock` file.

**Comment by jasonodoom** [comment]
Hi, this was merged. And you can begin using it. I see it's only on unstable at the moment though.
