### ISSUE TITLE
gdtoolkit: Replace lark080 override

### ISSUE THREAD

**Issue by hesiod** [NixOS/nixpkgs#216243]
As posted in #160040:

            
Overrides like that are no allowed when using `buildPythonPackage`.

See https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#using-pythonrelaxdepshook-using-pythonrelaxdepshook

_Originally posted by @mweinelt in https://github.com/NixOS/nixpkgs/pull/160040#discussion_r1027113889_

**Comment by kirillrdy** [comment]
https://github.com/NixOS/nixpkgs/pull/216280
