### ISSUE TITLE
Darwin reproducible builds

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#21629]
## Issue description

Currently, Darwin stdenv doesn't have reproducible builds. According to [this post](http://stackoverflow.com/questions/21765444/clang-compiler-produces-different-object-files-from-same-sources) it looks like Clang _should_ support reproducible builds. It looks like macOS has some special PIE/ASLR that may be contributing to this.

Does anyone have insight on what's going on? Perhaps passing ```--no_pie``` to LLVM configure will fix something?

### Steps to reproduce

```sh
$ nix-build -A hello --check
...
error: derivation ‘/nix/store/cq72li3c6vs7vabnlikfrz5vmjd4syj1-hello-2.10.drv’ may not be deterministic: output ‘/nix/store/la0bdn94l74vscz7bivhvi6qg7ih3v0p-hello-2.10’ differs
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
macOS Sierra 10.12.2
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.03pre-git

**Comment by LnL7** [comment]
I noticed before that a lot of stuff on darwin didn't seem to be reproducible, didn't realise that it was because of the stdenv.

**Comment by LnL7** [comment]
I hope I can play around with this soon, if you have some changes in mind but don't want to rebuild everything yourself let me know.

**Comment by matthewbauer** [comment]
So not much available on this topic. Right now the most comprehensive info is what I found here:

https://www.chromium.org/developers/testing/isolated-testing/deterministic-builds#TOC-OSX

**Comment by LnL7** [comment]
I'm not sure if this was always the case, but hello looks reproducible now. However only when built on the same machine/os version.

I wonder where 10.12/10.13 is leaked from, it's possible that is the cause of the offset differences.

```diff
 Load command 0
       cmd LC_SEGMENT_64
   cmdsize 72
@@ -108,10 +108,10 @@
    nsects 7
     flags 0x0
 Section
-  sectname __got
+  sectname __nl_symbol_ptr
    segname __DATA
       addr 0x0000000100005000
-      size 0x0000000000000028
+      size 0x0000000000000010
     offset 20480
      align 2^3 (8)
     reloff 0
@@ -120,16 +120,16 @@
  reserved1 41 (index into indirect symbol table)
  reserved2 0
 Section
-  sectname __nl_symbol_ptr
+  sectname __got
    segname __DATA
-      addr 0x0000000100005028
-      size 0x0000000000000010
-    offset 20520
+      addr 0x0000000100005010
+      size 0x0000000000000028
+    offset 20496
      align 2^3 (8)
     reloff 0
     nreloc 0
      flags 0x00000006
- reserved1 46 (index into indirect symbol table)
+ reserved1 43 (index into indirect symbol table)
  reserved2 0
 Section
   sectname __la_symbol_ptr
@@ -196,9 +196,9 @@
   cmdsize 72
   segname __LINKEDIT
    vmaddr 0x0000000100006000
-   vmsize 0x00000000000018fc
+   vmsize 0x0000000000001904
   fileoff 24576
- filesize 6396
+ filesize 6404
   maxprot 0x00000007
  initprot 0x00000001
    nsects 0
@@ -209,19 +209,19 @@
      rebase_off 0
     rebase_size 0
        bind_off 24576
-      bind_size 112
+      bind_size 120
   weak_bind_off 0
  weak_bind_size 0
-  lazy_bind_off 24688
+  lazy_bind_off 24696
  lazy_bind_size 648
-     export_off 25336
+     export_off 25344
     export_size 1224
 Load command 5
      cmd LC_SYMTAB
  cmdsize 24
-  symoff 26672
+  symoff 26680
    nsyms 132
-  stroff 29140
+  stroff 29148
  strsize 1832
 Load command 6
             cmd LC_DYSYMTAB
@@ -238,7 +238,7 @@
         nmodtab 0
    extrefsymoff 0
     nextrefsyms 0
- indirectsymoff 28784
+ indirectsymoff 28792
   nindirectsyms 89
       extreloff 0
         nextrel 0
@@ -251,12 +251,12 @@
 Load command 8
      cmd LC_UUID
  cmdsize 24
-    uuid E0DB2092-9D68-378E-919B-11F4FBC178C8
+    uuid 4490662C-1618-3452-91F7-B931CA6CE292
 Load command 9
       cmd LC_VERSION_MIN_MACOSX
   cmdsize 16
   version 10.10
-      sdk 10.12
+      sdk 10.13
 Load command 10
       cmd LC_SOURCE_VERSION
   cmdsize 16
@@ -280,10 +280,10 @@
 Load command 14
       cmd LC_FUNCTION_STARTS
   cmdsize 16
-  dataoff 26560
+  dataoff 26568
  datasize 96
 Load command 15
       cmd LC_DATA_IN_CODE
   cmdsize 16
-  dataoff 26656
+  dataoff 26664
  datasize 16
```

**Comment by copumpkin** [comment]
Probably obvious, but I'm pretty sure we could fight the `LC_UUID` randomness quite easily. There's a `-no_uuid` flag to `ld` that would do it, but I don't know if other tooling would dislike binaries produced that way.

**Comment by LnL7** [comment]
I found `-no_version_load_command`, that gets rid of the entire `LC_VERSION_MIN_MACOSX` section. That makes a trivial binary/dylib reproducable, but the offsets of hello are still inconsistent. 😞
