### ISSUE TITLE
nix-channel --update buries SSL cert problems

### ISSUE THREAD

**Issue by dckc** [NixOS/nixpkgs#21628]
### Steps to reproduce

Do a `nix-channel --update` when one of your channels has a bad SSL cert.

The diagnostic is:
```
nix-channel: unable to check ‘https://ci.monte-language.org/project/monte/channel/latest’
```

Using curl, I can see that the problem is:

```
$ curl https://ci.monte-language.org/project/monte/channel/latest
curl: (51) SSL: certificate subject name (hydra.matador.cloud) does not match target host name 'ci.monte-language.org'
```

**Comment by NeQuissimus** [comment]
I think this is probably NixOS/nix#728

**Comment by dckc** [comment]
yes... "unable to check ..." symptoms look similar.

**Comment by yegortimoshenko** [comment]
This is not a Nixpkgs issue: NixOS/nix#728.
