### ISSUE TITLE
nix-prefetch-git: too strict validation

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21620]
## Issue description

```
    src = fetchFromGitHub {
      owner = "neutrinolabs";
      repo = "xrdp";
      rev = "v0.9.1";
      fetchSubmodules = true;
      sha256 = "1d5n81b8fl21g597aqlcy7d7c4889bcylxgrslw298z7bdjwya0g";
    };
```
does not pass [this validation](https://github.com/NixOS/nixpkgs/blame/47d0d3d46f5520fba39c5376ea5449d51f44635d/pkgs/build-support/fetchgit/nix-prefetch-git#L283) which permits only hex-digits in ```rev```.

```fetchSubmodules = true``` is important, it forces to use ```git``` instead of ```curl```

ping @zimbatm

**Comment by zimbatm** [comment]
Yeah that test is a bit pointless since branch or tag names are quite arbitrary

**Comment by volth** [comment]
```v0.9.1``` also works with the validation commented out.

**Comment by volth** [comment]
```nix
fetchFromGitHub {
  owner = "aerospike";
  repo = "aerospike-server";
  rev = "3.14.0.1";
  sha256 = "1kzkwvir9j9jdlwp8gi9p3wkv3qhbrn62x1mb1xlnrdc7rk32kyn";
  fetchSubmodules = true;
}
```
fails with ```Bad commit hash or bad reference```

```nix
fetchFromGitHub {
  owner = "aerospike";
  repo = "aerospike-server";
  rev = "refs/tags/3.14.0.1";
  sha256 = "1kzkwvir9j9jdlwp8gi9p3wkv3qhbrn62x1mb1xlnrdc7rk32kyn";
  fetchSubmodules = true;
}
```
fails with ```invalid character ‘/’ in name ‘aerospike-server-refs/tags/3.14.0.1-src’```

**Comment by volth** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/26877 (this issue should be closed automatically, but...)
