### ISSUE TITLE
Documentation: nix-update-script

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nixpkgs#216321]
## Problem

`nix-update-script` is undocumented.

## Proposal

Add it to the manual.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by BenediktBroich** [comment]
Here you can find the source: [nix-update-script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/common-updater/nix-update.nix)
So basically it runns [nix-update](https://github.com/Mic92/nix-update) on your package with some [extra flags](https://github.com/Mic92/nix-update/pull/115).
