### ISSUE TITLE
Python blackd not working

### ISSUE THREAD

**Issue by jduan-highnote** [NixOS/nixpkgs#216346]
### Describe the bug
When I run blackd, it crashes:
```
$ blackd
Traceback (most recent call last):
  File "/nix/store/5xzx8q1zdg48z3sb31i693y27zpw2511-python3.10-black-22.10.0/bin/.blackd-wrapped", line 6, in <module>
    from blackd import patched_main
  File "/nix/store/5xzx8q1zdg48z3sb31i693y27zpw2511-python3.10-black-22.10.0/lib/python3.10/site-packages/blackd/__init__.py", line 14, in <module>
    raise ImportError(
ImportError: aiohttp dependency is not installed: No module named 'aiohttp'. Please re-install black with the '[d]' extra install to obtain aiohttp_cors: `pip install black[d]`
```

### Steps To Reproduce
See above

### Expected behavior
Blackd shouldn't crash. Btw, `black` runs just fine.

### Additional context
I'm using this channel: https://nixos.org/channels/nixpkgs-22.11-darwin

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(jduan): `"home-manager, nixpkgs-22.11-darwin"`
 - nixpkgs: `/Users/jduan/.nix-defexpr/channels/nixpkgs`
```

**Comment by FRidh** [comment]
Yes, as the message shows, it's optional functionality for which you need another package. You can use `python3.withPackages` for that.

**Comment by jduan-highnote** [comment]
@FRidh thanks for your quick response! I didn't realize I had to install that optional package myself. 

I just installed it via `nix-env -iA nixpkgs.python310Packages.aiohttp` but blackd still fails with the same error. Did I do anything wrong? Thanks!

**Comment by FRidh** [comment]
Python packages can't find each other when they are installed separate from each other. The Nixpkgs documentation shows how to use `python3.withPackages`.

**Comment by jduan-highnote** [comment]
Thank you. I'll look at how to use python3.withPackages!
