### ISSUE TITLE
Package request: mpv_inhibit_gnome as part of mpv

### ISSUE THREAD

**Issue by l0b0** [NixOS/nixpkgs#216455]
**Project description**

> This mpv plugin prevents screen blanking in GNOME while playing media.

Should fix https://github.com/mpv-player/mpv/issues/5459 on NixOS.

**Metadata**

* homepage URL: https://github.com/Guldoman/mpv_inhibit_gnome
* source URL: https://github.com/Guldoman/mpv_inhibit_gnome
* license: MIT
* platforms: unknown

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/mpv/scripts/inhibit-gnome.nix

**Comment by l0b0** [comment]
@AndersonTorres Has this actually been completed? MPV in 22.11 at least still shows the buggy behaviour of not preventing screen blanking.

**Comment by l0b0** [comment]
@AndersonTorres @zendo Shouldn't mpv-inhibit-gnome be part of the main MPV package rather than separate? It's a bug fix, after all.

**Comment by AndersonTorres** [comment]
I don't think it is a "bugfix".

It is a plugin, and you are free to include it or not to your particular setup.

- Do you use GNOME? Include it in your list of mpv plugins.
- Don't you use GNOME? One plugin less to worry.

Or there is another thing we are not catching here?

**Comment by l0b0** [comment]
It *is* a workaround for a [bug reported to MPV](https://github.com/mpv-player/mpv/issues/5459), which is still being pinged as unresolved. For convenience it would probably be good to include it iff Wayland is enabled.

**Comment by AndersonTorres** [comment]
This workaround cites GNOME, it is mostly tied to GNOME Wayland and there is some failure of communication between them - mpv and gnome are not implementing a common layer.

I am not convinced about how to solve this besides documenting the issue and the workaround.

How precisely other distros solved it?

**Comment by l0b0** [comment]
From https://github.com/Guldoman/mpv_inhibit_gnome#flatpak-support:

> This plugin has been integrated into the [Flatpak release of mpv](https://flathub.org/apps/details/io.mpv.Mpv), so you should already be good to go.

I don't know which distros use Flatpak.

**Comment by AndersonTorres** [comment]
> I don't know which distros use Flatpak.

https://flatpak.org/setup/NixOS
https://flathub.org/apps/details/io.mpv.Mpv
