### ISSUE TITLE
Some optional features of the systemd package are not exposed as configurable options

### ISSUE THREAD

**Issue by filakhtov** [NixOS/nixpkgs#216461]
### Describe the bug
👋🏻 Hey Nix-ers!

Another day - another report. I am building minimal LXC container images based on NixOS and I am striving to reduce the final image size as much as possible for some of them. In the process I have noticed that `systemd` package as provided can be shrunk by disabling some of the optional flags (`withRemote`, `withImportd`, `withCryptsetup`, `withHomed`, etc) which I take advantage of. However, some of the optional dependencies are not exposed as such, for example `kmod`, `audit`, `pam`, `acl` or `libidn2` to name a few. Instead they are hardcoded in the [`buildInputs`](https://github.com/NixOS/nixpkgs/blob/2b54954fdb4a25c6f9cf80cfd36c43e4c4577c0b/pkgs/os-specific/linux/systemd/default.nix#L374-L385) and their options are [forcefully set to true](https://github.com/NixOS/nixpkgs/blob/2b54954fdb4a25c6f9cf80cfd36c43e4c4577c0b/pkgs/os-specific/linux/systemd/default.nix#L461). I think it would be great to provide more configurability and expose flags for all these features.

### Steps To Reproduce
not applicable

### Expected behavior
I would love to have an ability to disable some additional optional features using something like `withLibidn2`, `withAudit`, `withKmod`, etc flags.

### Screenshots
not applicable

### Additional context
not applicable

### Notify maintainers
@flokli @Kloenk @Mic92 please do let me know if that is a bad idea 😉 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@nixos:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85-1-pve, NixOS, 23.05 (Stoat), 23.05pre454549.545c7a31e5d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by flokli** [comment]
Hey! There already is a `systemdMinimal` and a `systemdStage`.

The former one is used as udev for many packages, and also to bootstrap the full `systemd` build itself itself (as cryptsetup needs `udev`/`systemd` during build).

The latter one is used to link stage1 things against.

I'd guess there won't be much objection to also expose these additional configuration knobs in the systemd package definition, and maybe also trim `systemdMinimal` further by setting these to false.

Would you be up to open a PR to propose these changes?

**Comment by filakhtov** [comment]
Thank you very much @flokli, this is exactly what I was thinking myself. I am more than happy to open up a PR and work through this. I am new to Nix/NixOS, so it might take me some time to get my head around all the things, but I will start working on it as time permits and open up a draft PR with the progress I get for early feedback.
