### ISSUE TITLE
arduino: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by baracoder** [NixOS/nixpkgs#21647]
## Issue description

Starting the arduino IDE I get the following error and the program exits
```
Picked up JAVA_TOOL_OPTIONS: 

(java:9959): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
/home/bara/.nix-profile/bin/arduino: line 34:  9959 Trace/breakpoint trap   "$JAVA" "${JAVA_OPTIONS[@]}" processing.app.Base "$@"
```

### Steps to reproduce

```
nix-env -i arduino
arduino
```

## Technical details

* System: NixOS: ` 16.09.1229.f52eaf4 (Flounder)
* Nix version: 1.11.4
* Nixpkgs version:  16.09.1229.f52eaf4

**Comment by mogorman** [comment]
is a problem on my box as well

**Comment by baracoder** [comment]
i have tried to add `wrapGAppsHook` to `buildInputs` but it seams to be not enough.

**Comment by deepfire** [comment]
I get the same issue with `system-config-printer`, when I click a button to provide the `.ppd` file for a new printer:
```
(system-config-printer.py:1472): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap
```

**Comment by probonopd** [comment]
The same happens when trying to run Arduino on Deepin.

**Comment by Hodapp87** [comment]
Running into this on NixOS 18.03.

**Comment by probonopd** [comment]
@stale

**Comment by baracoder** [comment]
Arduino IDE works and linked issues are also resolved, so I am closing this one.
