### ISSUE TITLE
Package request: Muse Sounds Manager

### ISSUE THREAD

**Issue by colin-heffernan** [NixOS/nixpkgs#216432]
**Project description**
Muse Hub allows for the installation of MuseSounds, a high-quality selection of sounds for MuseScore. MuseScore already exists within the Nixpkgs repo, so having access to MuseSounds would be incredibly useful to MuseScore users using Nix.

**Metadata**

* homepage URL: https://www.musehub.com/
* source URL: N/A (closed-source)
* license: proprietary
* platforms: Linux

**Notes**
~~Muse Hub also acts as an installer for MuseScore, Audacity, and other apps, which may conflict with Nix's model. I am unsure of how feasible this all is, but I would like to be able to take advantage of MuseSounds on NixOS if at all possible.~~

***EDIT***
Muse Hub on Linux only provides MuseSounds, so please disregard the previous note. However, MuseSounds is installed in /srv, not within the home folder.

**Comment by Soliprem** [comment]
I second this, but I don't know how to write a nixos package at all. I'll add, though, that if installing in /srv is a problem, that directory can be  changed (potentially by default, but not having it installed I can't check which file would have to be edited

**Comment by adam248** [comment]
Looking at [AUR for Arch](https://aur.archlinux.org/packages/muse-hub-bin) they seem to use this URL for the src of the build:
https://pub-c7a32e5b5d834ec9aeef400105452a42.r2.dev/Muse_Hub.deb

When I went to the musehub site and tried to download the linux version of MuseHub I got the same URL:
https://pub-c7a32e5b5d834ec9aeef400105452a42.r2.dev/Muse_Hub.deb

The main problem with this URL is that the file doesn't change it's name with a version update (so checksum/hashing is going to be an issue.) (aka, can't pin down a version)

I will try and contact MuseHub and ask if they can have each version available as well for easier packaging in linux.
... to be continued...

**Comment by adam248** [comment]
oh, just found a comment detailing a manual build on Fedora...
https://musescore.org/en/node/336003#comment-1148388
Worth a read if you need to know how MuseHub works under the hood.

**Comment by adam248** [comment]
found their beta release URL:
https://pub-c7a32e5b5d834ec9aeef400105452a42.r2.dev/Muse_Hub_Beta.deb

**Comment by adam248** [comment]
It appears that MuseHub is no longer releasing for Linux. 
See the website here: https://www.musehub.com/
However, they have changed the name to `Muse Sounds Manager BETA`, so they are making it clear that this app for Linux is only for Muse Sounds and not MuseHub.

**Comment by Hachem-H** [comment]
any updates perhaps?

**Comment by colin-heffernan** [comment]
> any updates perhaps?

Since source code is not provided AFAIK, the `deb`/`rpm` would have to be unpacked and repacked, and even then it may not work. In other words, I don't know how possible it is. I guess this issue is just to see if anyone else knows.

**Comment by thilobillerbeck** [comment]
A solution I found to use an archived version of the app from arhive.org, this is kind of a hack but works for now.

I wrote a flake which packages Muse Sounds Manager based on the rpm package. You can find it here. Testing is greatly appreciated. If this turns out to work, I may also merge this into nixpkgs:

https://github.com/thilobillerbeck/muse-sounds-manager-nix

**Comment by ShawkMusic** [comment]
> A solution I found to use an archived version of the app from arhive.org, this is kind of a hack but works for now.
> 
> I wrote a flake which packages Muse Sounds Manager based on the rpm package. You can find it here. Testing is greatly appreciated. If this turns out to work, I may also PR this into nixpkgs:
> 
> https://github.com/thilobillerbeck/muse-sounds-manager-nix

How do I install this on my system? I'm new to NixOS and don't entirely understand what a flake is or how to use it

**Comment by BasilYes** [comment]
> > A solution I found to use an archived version of the app from arhive.org, this is kind of a hack but works for now.
> > I wrote a flake which packages Muse Sounds Manager based on the rpm package. You can find it here. Testing is greatly appreciated. If this turns out to work, I may also PR this into nixpkgs:
> > https://github.com/thilobillerbeck/muse-sounds-manager-nix
> 
> How do I install this on my system? I'm new to NixOS and don't entirely understand what a flake is or how to use it

@ShawkMusic  here [guide](https://nixos-and-flakes.thiscute.world/introduction/) for you

**Comment by adam248** [comment]
@vandenoever 
@doronbehar 

Hi, just notifying the maintainers of the Nix Musescore package that someone has made a flake that packages Muse Sounds Manager for NixOS.

https://github.com/thilobillerbeck/muse-sounds-manager-nix

I might be able to package it myself but not right now. Maybe you two could be able to do it as you already maintain the main application that Muse Sounds Manager is for?

Thanks

**Comment by adam248** [comment]
@colin-heffernan @Soliprem @Hachem-H @thilobillerbeck @ShawkMusic @BasilYes 

please help this pull request https://github.com/NixOS/nixpkgs/pull/341856
by either :+1:  or by testing/reviewing the code.

let's get this finished!

**Comment by doronbehar** [comment]
As mentioned in this https://github.com/NixOS/nixpkgs/pull/341856#issuecomment-2351576544 comment, due to the issues described in https://github.com/NixOS/nixpkgs/issues/318210 I am a bit hesitant in merging such a package, as it seem to have the potential to break Musescore . I will test again though when the PR is slightly more mature.

**Comment by orivej** [comment]
If MuseScore becomes unreliable after using `muse-sounds-manager` (which is not the case for me), the solution is to delete `~/.local/share/MuseSampler/`. If you want to restore it back, just launch `muse-sounds-manager` again, it will immediately recreate it (and print `|INFO|Muse.Common.Interop.ServiceCore|Installing MuseSampler` to the console).
