### ISSUE TITLE
coreutils: cp does not support xattrs

### ISSUE THREAD

**Issue by bluescreen303** [NixOS/nixpkgs#21649]
## Issue description
When trying to copy a file with extended attributes, the attributes don't get copied.
When forcing `cp` to copy the attributes, it reports:
`cp: cannot preserve extended attributes, cp is built without xattr support`

### Steps to reproduce
`cp --preserve=xattr src dst`

## Technical details

The issue was probably introduced with multiple outputs support. Previously, `coreutils` would find `attr` libs&headers while building, propagated through `acl`. But now, only the libs propagate and not `.dev`, so `coreutils` can't find the header and disables `xattr` support. Not sure if coreutils should just list `attr` as a `buildInput` (when `acl` is) or if `attr` should somehow signal that its `.dev` output should propagate too.

* System: `nixos 16.09.1272.81428dd (Flounder)`
* Nix version: `nix-env (Nix) 1.11.4`
* Nixpkgs version: `16.09.1272.81428dd`

**Comment by dezgeg** [comment]
Hmm, as far as I can tell from the git logs, `acl` at least explicitly didn't propagate `attr`.

**Comment by dezgeg** [comment]
When I tested 16.03 it doesn't have xattr support there either. But anyway, #21661 enables it.

**Comment by bluescreen303** [comment]
I'm pretty sure it used to work at some point, but it might have been a few years ago :)
Thanks!
