### ISSUE TITLE
Enhancement: include meta.inputLicenses and meta.outputLicenses

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#216571]
## Issue description

Sometimes, the license of a source code is distinct from the license of its output artifacts.

The example that comes to my mind is aegisub, whose source code is BSD but it links with GPLed libraries.

Therefore, I would suggest the inclusion of two attributes:

```
   meta = {
       inputLicenses = [ lib.licenses.bsd2 ];
       outputLicenses = [ lib.licenses.gpl3Plus ];
   }
```

The current `meta.licenses` can be deprecated and/or be an alias for both (when they are equal).

**Comment by YoshiRulz** [comment]
Isn't this already possible under the current system with e.g.
```nix
mkDerivation {
	src = fetchzip {
		meta.license = lib.licenses.bsd2;
	};
	meta.license = lib.licenses.gpl3Plus;
}
```

**Comment by AndersonTorres** [comment]
Indeed.
However it will require an update of documentation.

**Comment by SuperSandro2000** [comment]
> The example that comes to my mind is aegisub, whose source code is BSD but it links with GPLed libraries.

Isn't that already pictured by the dependency tree? If a direct dependency is GPL, then probably the linked output is also affected by that.

So, I don't think there is a need for any new meta attributes here.
