### ISSUE TITLE
Package request: shiboken6, pyside6

### ISSUE THREAD

**Issue by milahu** [NixOS/nixpkgs#216510]
[shiboken6](https://doc.qt.io/qtforpython/shiboken6/): code generator for python bindings to C++ code
[pyside6](https://wiki.qt.io/Qt_for_Python): python bindings to qt6 (alternative to pyqt6)

### needed by

- [cutter](https://github.com/rizinorg/cutter) with qt6
- https://github.com/NixOS/nixpkgs/pull/199294#issuecomment-1304544606 - ping @michaelBelsanti
- https://github.com/NixOS/nixpkgs/pull/197991

### draft

status unknown. i started this some months ago ...

https://github.com/milahu/nur-packages/tree/master/pkgs/shiboken6
https://github.com/milahu/nur-packages/tree/master/pkgs/autosub-by-abhirooptalasila/nix/shiboken6

https://github.com/milahu/nur-packages/tree/master/pkgs/pyside6
https://github.com/milahu/nur-packages/tree/master/pkgs/autosub-by-abhirooptalasila/nix/pyside6

### Metadata

* homepage URL: https://www.pyside.org/
* source URL: https://pypi.org/project/shiboken6/ and https://pypi.org/project/PySide6/
* license: lgpl
* platforms: all

**Comment by nomeata** [comment]
Just ran into a program I’d like to use that depends on PySide6 https://github.com/moritzgloeckl/overleaf-sync – so I’d be curious about having that in nixpkgs too

**Comment by Majiir** [comment]
Also needed for `streamdeck-ui` to upgrade past 2.0.13 (currently at 2.0.6 in nixpkgs, latest is 2.0.15).

Looks like a WIP PR got closed here: https://github.com/NixOS/nixpkgs/pull/216651

**Comment by cag3dbadg3r** [comment]
I'm a real noob but i'm trying to install mtkclient with termux on an android device but it requires shiboken6 and pysides6. any help?

**Comment by SebTM** [comment]
> Also needed for `streamdeck-ui` to upgrade past 2.0.13 (currently at 2.0.6 in nixpkgs, latest is 2.0.15).
> 
> Looks like a WIP PR got closed here: #216651

Came across this, too as I wanted to update streamdeck-ui :/
I'm not familiar enough to package pyside6, do you think you could do it and find time to have a look? (the streamdeck update and debugging if needed I can try to do)

Even OP got banned (and his PRs closed), the request for the PySide6 is still valid if better I can also create a new / issue for it.
