### ISSUE TITLE
Package request: kaniko

### ISSUE THREAD

**Issue by echaouchna** [NixOS/nixpkgs#216542]
**Project description**

kaniko is a tool to build container images from a Dockerfile, inside a container or Kubernetes cluster

**Metadata**

homepage URL: [https://github.com/GoogleContainerTools/kaniko](https://github.com/GoogleContainerTools/kaniko)
source URL: [https://github.com/GoogleContainerTools/kaniko](https://github.com/GoogleContainerTools/kaniko)
license: [Apache-2.0 license](https://github.com/GoogleContainerTools/kaniko/blob/main/LICENSE)
platforms: Linux

**Comment by superherointj** [comment]
Please test. And provide feedback.

You can use `nixpkgs-review` tool for that:
* https://github.com/Mic92/nixpkgs-review

> nix-shell -p nixpkgs-review
> nixpkgs-review pr 216654
> cd nixpkgs
> nix build .#kaniko
> ./result/bin/kaniko

**Comment by 06kellyjac** [comment]
FYI you can do the following to build a container with kaniko in it. Use the kaniko executor on your host system (outside of containers) [at your own risk](https://github.com/GoogleContainerTools/kaniko/tree/main#running-kaniko)

```
# nix bundle --bundler github:NixOS/bundlers#toDockerImage nixpkgs#hello
# docker load < kaniko-1.9.1.tar.gz
# docker run kaniko-1.9.1:latest executor --xyz
```

Note that you may need to build a container with kaniko/executor + credential helpers

https://github.com/GoogleContainerTools/kaniko/blob/main/deploy/Dockerfile#L52-L56
