### ISSUE TITLE
docker-compose_1 - (python import) no module named 'compose'

### ISSUE THREAD

**Issue by senorsmile** [NixOS/nixpkgs#216671]
### Describe the bug
With docker-compose v1, it's expected that you will have a python module available for import.  This is reproducible by installing docker-compose with pip on other distributions.  If memory serves, distribution packages for v1 would also provide the compose module to python in addition to the binary.  

### Steps To Reproduce
1. 
```yml
          environment.systemPackages = with pkgs; [
            (python3.withPackages (ps: with ps; [
              docker
              pkgs.docker-compose_1
            ]))
          ];
```
2. 
```console
nixos-rebuild switch
```
3. 
```console
$ python
>>> import compose

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'compose'
```

### Expected behavior
compose module is imported successfully. 

### Notify maintainers

@Frostman 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.80, NixOS, 22.11 (Raccoon), 22.11.20230209.49efda9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
> ```yaml
>           environment.systemPackages = with pkgs; [
>             (python3.withPackages (ps: with ps; [
>               docker
>               pkgs.docker-compose_1
>             ]))
>           ];
> ```

That will not work. You need to use a docker-compose from pythonPackages. If that does not exist yet, the attr needs to be added, maybe with toPythonModule.

**Comment by senorsmile** [comment]
I tried building just the docker-compose module itself (not the "binary") with the following

```console
  (python39.withPackages (ps: with ps; [
    ...

    (
      buildPythonPackage rec {
        pname = "docker-compose";
        version = "1.29.2";
        src = fetchPypi {
          inherit pname version;
          sha256 = "sha256-TIzZ0h0jdBJ5PRi9MxEASe6a+Nqz/iwhO70HM5WbCbc=";
        };
        doCheck = false;
        propagatedBuildInputs = [
          #pkgs.python3Packages.docker
          #pkgs.python3Packages.python-dotenv
          #pkgs.python3Packages.dockerpty
          #pkgs.python3Packages.jsonschema_3
          #pkgs.python3Packages.setuptools

          pkgs.pkgs-pyyaml5.python39Packages.docker
          pkgs.pkgs-pyyaml5.python39Packages.python-dotenv
          pkgs.pkgs-pyyaml5.python39Packages.dockerpty
          pkgs.pkgs-pyyaml5.python39Packages.jsonschema
          pkgs.pkgs-pyyaml5.python39Packages.setuptools
          pkgs.pkgs-pyyaml5.python39Packages.pyyaml
        ];
      }
    )

  ]))
```

I kept adding deps until I ran into pyyaml needing to be older than what's in 22.11.   So, I set up an additional input in my flake tracking nixpkgs when it still existed.  It took about 6 hours to build on a beefy ec2 instance, but still ran into an error (which I unfortunately didn't record).

**Comment by SuperSandro2000** [comment]
Mixing python versions like this is not supported. Either use one of the many python2nix like tools or you need to construct that manually.
