### ISSUE TITLE
`searx` : internal server error

### ISSUE THREAD

**Issue by qaristote** [NixOS/nixpkgs#216695]
### Describe the bug

I'm running a `searx` instance through the corresponding NixOS module. The system builds successfully and the `uwsgi` service manages to start, but when trying to connect to the instance I get an `Internal server error`. I believe the relevant part of the `uwsgi` log is the following:

```console
Traceback (most recent call last):
File "/nix/store/y6akp3d17rskpxgz769pmczlr5lh896y-python3-3.10.9-env/lib/python3.10/site-packages/searx/webapp.py", line 191, >
@babel.localeselector
AttributeError: 'Babel' object has no attribute 'localeselector'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

### Notify maintainers

@matejc @globin @danielfullmer

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.81, NixOS, 23.05 (Stoat), 23.05.20230215.6d33e5e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(qaristote): `"nixos-22.05pre333986.73369f8d086"`
 - channels(root): `"nixos-22.05pre369524.5181d5945ed"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Note that I'm building my configuration through a flake and thus use `nixpkgs-unstable`.

**Comment by SuperSandro2000** [comment]
Searx got dropped and we only have searxng which works for me.
