### ISSUE TITLE
Nvidia hardware video decode/CUDA broke

### ISSUE THREAD

**Issue by dunk1452** [NixOS/nixpkgs#216628]
### Describe the bug
Attemping to use CUDA for hardware decode on video results in the following:
[00:18:41:607] MPVProcess::parseLine: "[ffmpeg] AVHWDeviceContext: Cannot load libcuda.so.1
[00:18:41:607] MPVProcess::parseLine: "[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA"

### Steps To Reproduce
1. Install latest NVIDIA drivers on nixos-unstable channel
2. Configure media player to use CUDA/hardware decoding
3. Play video

### Expected behaviour
Hardware accelerated decode shouldn't fail. This stopped working after updating recently to latest NVIDIA drivers I believe. I've tried using hardware decode for Jellyfin-media-player and SMplayer both fail.
### Screenshots
![image](https://user-images.githubusercontent.com/21962987/219355028-db24426a-d419-4026-aa3f-0005cbf82440.png)
![image](https://user-images.githubusercontent.com/21962987/219353977-b4076cd6-96d5-4884-819c-a955eadf0471.png)

### Additional context
QEMU virtual environment
GPU: NVIDIA GTX 1070 ti

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.11, NixOS, 23.05 (Stoat), 23.05.20230213.545c7a3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(user): `"nixos"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by GGG-KILLER** [comment]
Have the same issue here but with plain ffmpeg (both when invoked through Jellyfin as well as CLI):
![image](https://user-images.githubusercontent.com/5892127/219878681-4bd09030-d40e-4c15-841a-05f5207a703d.png)

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.11, NixOS, 23.05 (Stoat), 23.05.20230213.545c7a3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/yxcvhxxlq7q6284hmwzvnzcg1g5aph47-source`
```

**Comment by GGG-KILLER** [comment]
cc ffmpeg maintainer: @Atemu

**Comment by GGG-KILLER** [comment]
Update, seems like adding `/run/opengl-driver/lib` to `LD_LIBRARY_PATH` works.

I don't know how that could be factored into the ffmpeg derivation.

**Comment by seandheath** [comment]
What is the fix for this? Is there a way to use an overlay to add the library somehow?

**Comment by GGG-KILLER** [comment]
Yes, the following overlay can be used while the linked PR doesn't arrive on master: https://github.com/GGG-KILLER/nixos-configs/blob/master/common/overlays/ffmpeg-cuda-fix.nix

**Comment by vcunat** [comment]
https://nixpk.gs/pr-tracker.html?pr=217044

**Comment by GGG-KILLER** [comment]
@seandheath the fix has arrived on unstable, could you test to see if it fixes your issue?

**Comment by vcunat** [comment]
Well, reopen if still happening.
