### ISSUE TITLE
meld-3.16.4 from unstable channel crashes

### ISSUE THREAD

**Issue by vmandela** [NixOS/nixpkgs#21669]
## Issue description

~~~~
~/tfs/3_01_00_03_nightly $ meld etc ../3_01_00_03/etc
Traceback (most recent call last):
  File "/nix/store/kkcq8h1dglay17rs52ig9g38sr4xb4my-meld-3.16.4/bin/..meld-wrapped-wrapped", line 289, in <module>
    setup_settings()
  File "/nix/store/kkcq8h1dglay17rs52ig9g38sr4xb4my-meld-3.16.4/bin/..meld-wrapped-wrapped", line 228, in setup_settings
    meld.settings.create_settings(uninstalled=uninstalled or frozen)
  File "/home/a0393778/.nix-profile/lib/python2.7/site-packages/meld/settings.py", line 116, in create_settings
    meldsettings = MeldSettings()
  File "/home/a0393778/.nix-profile/lib/python2.7/site-packages/meld/settings.py", line 46, in __init__
    settings.connect('changed', self.on_setting_changed)
TypeError: <Gio.Settings object at 0x7f2c8b2801e0 (GSettings at 0x22bfab0)>: unknown signal name: changed
~~~~

### Steps to reproduce

1. Install meld from the unstable channel.
2. Launch meld.

meld-3.14.0 works without crashing.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.03pre98135.3ac20e9"

* Nix channels in use: `nix-channel --list`
nixpkgs https://nixos.org/channels/nixpkgs-unstable
stable http://nixos.org/channels/nixos-16.03

**Comment by vcunat** [comment]
I believe there are purity problems in meld.  At least in my case it somehow picks up GIO/gvfs modules from the environment, which is what I suspect to cause a crash for one older version (which used to work fine for me).  We've had similar problems already #1357.

**Comment by vmandela** [comment]
I could avoid the crash after uninstalling unused python packages in my profile.

**pygobject-3.20.0**
python-curses-2.7.13
python2.7-pyserial-2.7
python2.7-pysqlite-2.8.3

I am assuming removing pygobject fixed the problem.
