### ISSUE TITLE
nginx recommends mainline as default branch

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#21665]
According to [this source](http://serverfault.com/questions/715049/what-s-the-difference-between-the-mainline-and-stable-branches-of-nginx), the nginx team recommends that people use the `mainline` branch of nginx unless `stable` is needed. In nixpkgs, [`nginx` is set to use the `stable` branch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L10304), and this is the default version of Nginx used in nixpkgs. Should we switch it?

**Comment by peterhoeg** [comment]
As a policy, I think it makes perfect sense to follow upstream as close as possible so 👍 from here.

**Comment by 3noch** [comment]
@peterhoeg Right...perhaps we could just add documentation telling people to change it if they want to use the recommended branch.

@Mic92 I'm not sure I understand your concern?

**Comment by Mic92** [comment]
@3noch when back porting security fixes to nixos stable like during our [Vulnerability Roundup](https://github.com/NixOS/nixpkgs/issues/21142)
we prefer to upgrade to patch releases provided by upstream. Those will be probably only provided for the stable release of nginx, while the `mainline` could also contain breaking changes in their update from my understanding.

**Comment by 3noch** [comment]
@Mic92 Ok that makes sense. So perhaps this "recommendation" should only be at the documentation level. I'd be happy to add a note to `services.nginx` if you guys would prefer that.

**Comment by fpletz** [comment]
To summarize:

 * On release branches, we update only to minor `nginxStable` versions (like 1.10.x, not 1.10 -> 1.12) but major `nginxMainline` versions (like 1.11 -> 1.13)
 * On the master branch, we update `nginxStable` & `nginxMainline` normally with breaking changes

Documentation update is coming up.

**Comment by 3noch** [comment]
Great solution. Thanks @fpletz!
