### ISSUE TITLE
lmms-1.1.90 crashes after reinstall

### ISSUE THREAD

**Issue by sunnystormy** [NixOS/nixpkgs#21668]
## Issue description
I receive the following when I try to run lmms:

`Notice: could not set realtime priority.
VST sync support disabled in your configuration
"Cannot load library /nix/store/hw0n3wmnxbrqk9xqqxaliy5v6d65p865-lmms-1.1.90/lib/lmms/ladspa/sifter_1210.so: (/nix/store/hw0n3wmnxbrqk9xqqxaliy5v6d65p865-lmms-1.1.90/lib/lmms/ladspa/sifter_1210.so: undefined symbol: q_sort)" 
Segmentation fault
`

### Steps to reproduce
Download lmms, then attempt to re-install it again. Try running it afterwards. That's what caused this error for me.

## Technical details

* System: 16.09
* Nix version: 1.11.4
* Nixpkgs version: "16.09.1423.b0539b9"

----UPDATE----
After removing the 'lmms' directory lmms places inside of your home directory, I was able to reinstall the application and get it to work. I'm going to post this issue on the LMMS github page and link this ticket. This is clearly an issue related to their code. Ticket opened here: https://github.com/LMMS/lmms/issues/3209

**Comment by yegortimoshenko** [comment]
Please build a new version and check if the issue still persists:

```
$ nix-build https://github.com/NixOS/nixpkgs/archive/15e42939cc96c4c2616c9c0222d49a134197dd5b.tar.gz -A lmms
$ result/bin/lmms
```

**Comment by prusnak** [comment]
Closing. LMMS works now.
