### ISSUE TITLE
nix-shell PS1 formatting issue

### ISSUE THREAD

**Issue by carnott-snap** [NixOS/nixpkgs#21663]
## Issue description
when I run nix-shell, I get a malformed PS1 that has printed escape characters.

currently:  \\[**\\][nix-shell:~/git/secproxy]$\\[**\\]
- bold represents green text in shell

### Steps to reproduce
run `nix-shell`
`echo $PS1` yields: `\n\[\033[1;32m\][nix-shell:\w]$\[\033[0m\]`

### Proposed solution

Modify line 297 of nix-shell executable:
currently: `            '[ -n "$PS1" ] && PS1="\n\[\033[1;32m\][nix-shell:\w]$\[\033[0m\] "; ' .`
works for me: `            '[ -n "$PS1" ] && PS1="\033[1;32m[nix-shell:\w]$\033[0m "; ' .`

- I assume this is a very hacky, non-portable fix, but this does fix the issue.

## Technical details

* System: macOS version: 10.12.2 (16C67)
* Nix version: nix-env (Nix) 1.11.5
* Nixpkgs version: 17.03pre98135.3ac20e9
* Shell: GNU bash version: 3.2.57(1)-release (x86_64-apple-darwin16)

**Comment by matthewbauer** [comment]
This is probably better suite for the [Nix](https://github.com/NixOS/nix) repo. nix-shell has been rewritten in C so the new file is at [src/nix-build/nix-build.cc line 431](https://github.com/NixOS/nix/blob/9000150a784d05a76455886b1ad8a95e0cff2115/src/nix-build/nix-build.cc#L431).

**Comment by carnott-snap** [comment]
Sounds good, I will close this issue and create an issue there.

**Comment by carnott-snap** [comment]
actually this looks like a dupe (possibly): nixos/nix#644
