### ISSUE TITLE
Update request: apx 1.4.2 → 1.7.0-1

### ISSUE THREAD

**Issue by yswtrue** [NixOS/nixpkgs#216768]
- Package name: apx
- Latest released version: 1.7.0-1

- Current version on the unstable channel:  1.4.2
- Current version on the stable/release channel:

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: @dit7ya

**Comment by dit7ya** [comment]
Looks like they added `nix` as a package manager to `apx` itself and made some other changes too. I am going to take a look at this by tomorrow.

**Comment by dit7ya** [comment]
@yswtrue I have created a PR but have not tested the package extensively myself. Could you please test it?

**Comment by yswtrue** [comment]
I have tried these two pr #216962  and #216407  by `nixpkgs-review` 
and it seams works well
