### ISSUE TITLE
Update request: vlang weekly.2022.20 → 0.3.3

### ISSUE THREAD

**Issue by knarkzel** [NixOS/nixpkgs#216764]
- Package name: vlang
- Latest released version: 0.3.3
- Current version on the unstable channel: weekly.2022.20
- Current version on the stable/release channel: weekly.2022.20
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Madouura

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by happysalada** [comment]
I tried the update at https://github.com/NixOS/nixpkgs/pull/231959
There are some pretty bad errors, if you have ideas about any of these, I'd be happy to try stuff.

**Comment by natsukium** [comment]
It should be a newer version now.
