### ISSUE TITLE
p7zip source is gone

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#216766]
## Issue description

p7zip source is gone

### Steps to reproduce

try to build p7zip.src without substituters

cc @7c6f434c @06kellyjac

**Comment by reedrw** [comment]
What commit are you having the issue from? it works for me at https://github.com/NixOS/nixpkgs/commit/9657e4f57ca49e2647353f9d5876b704ca640774

**Comment by fgaz** [comment]
Current master, that is 2abea38e0824edd57a3dcfe02f84e09a3a3734c5 sets `rev` to `v17.04`. There is no such tag at https://github.com/jinfeihan57/p7zip/tags

https://github.com/NixOS/nixpkgs/blob/2abea38e0824edd57a3dcfe02f84e09a3a3734c5/pkgs/tools/archivers/p7zip/default.nix#L10

**Comment by SuperSandro2000** [comment]
Maybe the fork cleared the tags by force pushing?

**Comment by 7c6f434c** [comment]
Hmm, I wonder if all the changes got merged into https://github.com/p7zip-project/p7zip with the fork then rebasing and force-pushing…

**Comment by 06kellyjac** [comment]
Yeah, looks like it. A bunch of jinfeihan57's commits are now in the commit history

https://github.com/p7zip-project/p7zip/compare/v17.03...v17.05

I'll change it to point back to p7zip-project's copy now
