### ISSUE TITLE
neo4j permissions fail on config, log, and data directories

### ISSUE THREAD

**Issue by svejcik** [NixOS/nixpkgs#21688]
## Issue description
Starting neo4j after nix-env -i fails due to systems (non-user) permissions on volatile directories, conf, var, data

### Steps to reproduce
neo4j start

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by lunamystry** [comment]
Hope comnting on an old post like this is now frowned upon.

I came across a similar problem recently. I am learning both neo4j and nix. I'll present my progress in getting it working for nix-shell but I think a similar thing would work for a globally used neo4j. Then I will present why I think this works in the hopes that someone can correct me if I am wrong or add to my knowledge. 

## How I got it to work
My project structure is like this: 

```
[nix-shell:~/Projects/dee-dee]$ tree -L 1 .
.
├── default.nix
├── neo4j
│   ├── certificates
│   ├── data
│   ├── logs
│   ├── neo4j.conf
│   └── run
├── README.md
└── src
```
The content of neo4j.conf is:

```
[nix-shell:~/Projects/dee-dee]$ cat neo4j/neo4j.conf 
dbms.directories.logs=/home/lunamystry/Projects/dee-dee/neo4j/logs
dbms.directories.data=/home/lunamystry/Projects/dee-dee/neo4j/data
dbms.directories.run=/home/lunamystry/Projects/dee-dee/neo4j/run
dbms.directories.certificates=/home/lunamystry/Projects/dee-dee/neo4j/certificates
```
Then when inside the nix-shell I run:
```
[nix-shell:~/Projects/dee-dee]$ NEO4J_CONF=$PWD/neo4j neo4j start
```
The permission error goes away. Not sure if neo4j is working fine though. Still gonna check. 

## Why I think it works
The way neo4j works by default can't really work with nix since it tries to modify global state. Global state in this case is the logs, data, run and certificates directories. This is a problem since nix is installed in a hashed path by nix and this path changes with each update of the package (I think) and that means if I am storing these values (state) in that directory, then they would be unavailable in subsequent neo4j upgrades. 
The second problem is that this might cause data to be shared between users in systems with multiple users or user-profiles. This is because nix points to the same package for multiple users. 
The reason my configuration works is because I am placing the "state" in the directory of my project thus isolating it. So now multiple projects can use neo4j at the same time. 

## Future works
Can I NOT hard code the full directory path in the neo4j config?
Can I run neo4j when I enter a project and stop it when I exit the project?

**Comment by lunamystry** [comment]
@flokli I was running that configuration on Ubuntu (I have a feeling you don't mean the OS) but a channel or something. 

That said, I want to ask what you mean by "works". I think the module works, just needed the correct configuration which I don't think is a problem.

**Comment by flokli** [comment]
@lunamystry I was referring to the NixOS module system, in that case, the [`services.neo4j` tree](https://nixos.org/nixos/options.html#services.neo4j)  - which only works on NixOS itself.

I can't really provide guidance on how to set this up manually - you might want to look into how the nixos module configures and starts it:
https://github.com/NixOS/nixpkgs/blob/release-18.09/nixos/modules/services/databases/neo4j.nix#L605

**Comment by lunamystry** [comment]
@flokli this is fine. Thank you.

**Comment by MelihDarcanxyz** [comment]
I'm getting a similar error on 23.05 branch, with the following config:

```
{ config, pkgs, ... }: {
  services.neo4j = {
    enable = true;
  };
}
```

Here is the traceback:

```
Directories in use:
home:         /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j
config:       /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/conf
logs:         /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/logs
plugins:      /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/plugins
import:       /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/import
data:         /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/data
certificates: /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/certificates
licenses:     /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/licenses
run:          /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run
Starting Neo4j.
Executing command line: /nix/store/k0wfgwiz9m6zzjwxq462brwpjflgrh20-openjdk-11.0.19+7/lib/openjdk/bin/java -cp /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/plugins/*:/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/conf/*:/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/lib/* -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -XX:MaxInlineLevel=15 -XX:-UseBiasedLocking -Djdk.nio.maxCachedBufferSize=262144 -Dio.netty.tryReflectionSetAccessible=true -Djdk.tls.ephemeralDHKeySize=2048 -Djdk.tls.rejectClientInitiatedRenegotiation=true -XX:FlightRecorderOptions=stackdepth=256 -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -Dlog4j2.disable.jmx=true -Dfile.encoding=UTF-8 org.neo4j.server.CommunityEntryPoint --home-dir=/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j --config-dir=/nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/conf
org.neo4j.server.startup.BootFailureException: Unexpected error while starting. Aborting. FileSystemException : /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run/neo4j.pid: Read-only file system
	at org.neo4j.server.startup.ProcessManager.run(ProcessManager.java:209)
	at org.neo4j.server.startup.BootloaderOsAbstraction.console(BootloaderOsAbstraction.java:74)
	at org.neo4j.server.startup.UnixBootloaderOs.console(UnixBootloaderOs.java:57)
	at org.neo4j.server.startup.Bootloader.console(Bootloader.java:151)
	at org.neo4j.server.startup.Neo4jCommand$Console.call(Neo4jCommand.java:56)
	at org.neo4j.server.startup.Neo4jCommand$Console.call(Neo4jCommand.java:47)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.neo4j.server.startup.Neo4jCommand.main(Neo4jCommand.java:166)
Caused by: java.nio.file.FileSystemException: /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run/neo4j.pid: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at java.base/java.nio.file.Files.write(Files.java:3425)
	at org.neo4j.server.startup.PidFileHelper.storePid(PidFileHelper.java:56)
	at org.neo4j.server.startup.ProcessManager.storePid(ProcessManager.java:292)
	at org.neo4j.server.startup.ProcessManager.run(ProcessManager.java:172)
	... 13 more
```

**Comment by flokli** [comment]
See this line:

> org.neo4j.server.startup.BootFailureException: Unexpected error while starting. Aborting. FileSystemException : /nix/store/b6dgxh8yjqxwsrw8ichqz625w6xqc60s-neo4j-4.4.11/share/neo4j/run/neo4j.pid: Read-only file system

As well as all paths after "Directories in use:". They point to the nix store, which can't be writable. Please open a new issue for this problem.
