### ISSUE TITLE
Octave broken on darwin

### ISSUE THREAD

**Issue by LnL7** [NixOS/nixpkgs#21687]
## Issue description

https://gist.github.com/LnL7/92c752f511836744aad1b986f4284bf0
```
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
```

### Steps to reproduce

```
nix-build -A octave --argstr system x86_64-darwin
```

## Technical details

* System: (macOS 10.11.6)
* Nix version: (1.11.5)
* Nixpkgs version: (master: 1f6bb81)

**Comment by peterhoeg** [comment]
```master``` now has 4.2 as there were problems with 4.0.3 on linux as well. 4.0.1 and 4.2.0 are OK on linux.

**Comment by knedlsepp** [comment]
For me 
`nix-shell -p octave --run "octave <(echo 'disp(ones(10,10))')"`
works on darwin. I think this can be closed.

**Comment by LnL7** [comment]
http://hydra.nixos.org/build/53560063
