### ISSUE TITLE
Documentation: confusing and incomplete mkFlutterApp documentation

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#216914]
## Problem

A beginner reported that there is few to no documentation about packaging Flutter apps.

https://github.com/NixOS/nixpkgs/pull/216843#discussion_r1110615371

## Checklist

- [ ] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [ ] checked [open documentation issues] for possible duplicates
- [ ] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by hacker1024** [comment]
I'm happy to take this task, though it's currently a little blocked by the conversation in https://github.com/NixOS/nixpkgs/pull/228282#discussion_r1177455022.

**Comment by hacker1024** [comment]
Closed by #229770.
