### ISSUE TITLE
postgresql_15 requires granting permissions on schema public, ensureUsers insufficient

### ISSUE THREAD

**Issue by exzombie** [NixOS/nixpkgs#216989]
### Describe the bug
I was trying to set up Nextcloud on 22.11 through NixOS modules, and failed with pkgs.postgres_15. It was trivial after downgrading to pkgs.postgres_14.

### Steps To Reproduce
1. Remove any existing databases and Nextcloud data to have a clean slate.
1. Enable postgresql and set `services.postgresql.package = pkgs.postgresql_15;`
2. Enable Nextcloud and set it up as documented in [the manual](https://nixos.org/manual/nixos/stable/index.html#module-services-nextcloud).
3. Run `nixos-rebuild` and observe the following error in the journal:

```
nextcloud-setup-start[15572]: Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
```

You can reproduce this with `psql` if you prefer, but the above are steps from the manual, using the latest available postgres.

### Expected behavior
`nixos-rebuild` succeeds, the Nextcloud database is initialized properly. This *does* work with `services.postgresql.package = pkgs.postgresql_14;`

### Additional context

To quote the [postgresql docs](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PRIV):

> A user can also be allowed to create objects in someone else's schema. To allow that, the CREATE privilege on the schema needs to be granted. In databases upgraded from PostgreSQL 14 or earlier, everyone has that privilege on the schema public.

It appears this only affects fresh databases.

If I understand correctly, to support the `services.nextcloud` module, the `services.postgresql` module needs to provide a way to either set the owner of the database or to grant permissions on a schema. Neither seems to be available, although, naturally, it's possible I missed something. It's *almost* possible to use `ensureUsers` to do this: the syntax for the `GRANT` does the right thing, but the problem is that you need to be connected to the database in question, and the `postgresql-post-start` script does not do that.

### Notify maintainers

@thoughtpolice @danbst @globin @marsam @ivan

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.92, NixOS, 22.11 (Raccoon), 22.11.20230207.af96094`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by happysalada** [comment]
I'm wondering if this PR https://github.com/NixOS/nixpkgs/pull/255961 has been considered, it looks like it gets the job done and its quite far along.

**Comment by Ma27** [comment]
Yes and I think it's a bad idea because it expands on the ensure anti-pattern.

I have a proposal lying around that will require a bit of polishing, but I'd submit it tonight.

**Comment by SuperSandro2000** [comment]
Which anti pattern do you mean? I couldn't find a comment mentioning this yet.

Also I hope I find some time to test this today, so kindly give me a ping.

**Comment by Ma27** [comment]
Basically https://github.com/NixOS/nixpkgs/issues/206467.
