### ISSUE TITLE
Documentation: NetworkManager module pulls plugins, whilst default documentation does not describe that

### ISSUE THREAD

**Issue by Shawn8901** [NixOS/nixpkgs#216952]
## Problem
I am not 100% sure if its a implementation issue or a wrong documentation.

If someone peeks for the network manager module and checks for the plugins its documented, that there are[ no extra plugins installed](https://github.com/NixOS/nixpkgs/blob/de5448dab588ad41aef40f8c7c0c230981656698/nixos/modules/services/networking/networkmanager.nix#L220).
But in fact the module [pulls 7 vpn plugins as default](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/nixos/modules/services/networking/networkmanager.nix#L500-L507). 

I assume either the documentation is wrong, or there is a module option missing, that gates the installation of those vpn plugins.
If one does check the commit that introduced the code it leads to #164531, which does give me the impression that its "just" wrong documentation

## Proposal

Either change the documentation to make it clear that there are 7 plugins installed or change the implementation that there is no plugin installed as default and users have to enable vpn plugins.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by jtojnar** [comment]
The description specifies:

> Some plug-ins are enabled by the NetworkManager module by default.

Maybe we should emphasize a bit more that it is the module, which enables them, not the option.

Or maybe just remove the default.

See also the following discussion: https://discourse.nixos.org/t/networkmanager-plugins-installed-by-default/39682/8?u=jtojnar

**Comment by Shawn8901** [comment]
i might just overread that sentence. but i still find the implementation confusing for having to mkForce the plugins to be empty. but as  its intended ill close the issue.
