### ISSUE TITLE
Meteor: Missing shared libraries: libcurl.so.4 & liblzma.so.5

### ISSUE THREAD

**Issue by tennox** [NixOS/nixpkgs#216969]
### Describe the bug
For some older project I need to run *meteor* (was pretty cool back then), which thinks it's extra special and downloads dependencies on it's own, which are not correctly set up in the [`meteor package`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/meteor/default.nix#L95):

```
/nix/store/yn2k3lf820n6rhi6rm1mbrrnbn88sc0p-meteor-2.7.3/packages/meteor-tool/.2.7.3.1mjjp3y.wu0o++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod:
error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
Unexpected mongo exit code 127. Restarting.
```

### Steps To Reproduce
1. (optional, for reproducibility) set up clean environment inside `docker run --rm -it ubuntu`:
```
apt update &&  apt install -y curl xz-utils
sh <(curl -L https://nixos.org/nix/install) --daemon
exec $SHELL
nix-shell -p meteor
cd /tmp
export METEOR_ALLOW_SUPERUSER=1
```
3. Create example meteor app: `meteor create test && cd test/`
4. Run meteor: `meteor`

### How to fix

I figured out how to do this manually:
(in addition to curl, it needs `liblzma.so.5`)
```
nix-shell -p meteor curl xz
export LD_LIBRARY_PATH='/nix/store/3rib24hxx729n6wjg3s464wmiahlazx4-curl-7.87.0/lib:/nix/store/502zrfyc2agh928111zhwy6959bqd8m0-xz-5.4.1/lib'
meteor
```
... this works, but I have no idea how to properly do this :shrug: 

### Notify maintainers
@cstrahan @sikmir

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.11-200.fc37.x86_64, Ubuntu, 22.04.1 LTS (Jammy Jellyfish), nobuild`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/root/.nix-defexpr/channels/nixpkgs`
```

**Comment by Artturin** [comment]
Adding curl and lzma to https://github.com/NixOS/nixpkgs/blob/d2c3bf424abb78f3879f5a9f9983e85f1bbaa4aa/pkgs/servers/meteor/default.nix#L82 may fix it

**Comment by tennox** [comment]
> Adding curl and lzma to
> 
> https://github.com/NixOS/nixpkgs/blob/d2c3bf424abb78f3879f5a9f9983e85f1bbaa4aa/pkgs/servers/meteor/default.nix#L82
> may fix it

Thanks for the tip! I've tried it, but it doesn't seem to help - until I figured I also need to add it to the patching script's library path - now it works :tada: 

https://github.com/NixOS/nixpkgs/pull/228755
