### ISSUE TITLE
picard has unnecessary build inputs

### ISSUE THREAD

**Issue by mineo** [NixOS/nixpkgs#21696]
## Issue description

(I'm not using Nix, just looking at how it handles software I'm involved with, so I've removed parts of the issue template)

Looking at https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/picard/default.nix, I can see that the buildInputs include ffmpeg and libofa, but both of them are not need anymore since a few years ago (https://github.com/metabrainz/picard/commit/504052ffc50608dec5431fcae7e5cefc7b213c70). Together with libofa, the build dependency on pkgconfig is also gone.

**Comment by FRidh** [comment]
go ahead and open a PR

**Comment by mimadrid** [comment]
Sorry for the intrusion, I've already done it.

**Comment by pSub** [comment]
Fix was merged in #21711.
