### ISSUE TITLE
Package request: KShutdown

### ISSUE THREAD

**Issue by Zaczero** [NixOS/nixpkgs#217090]
**Project description**

KShutdown™ is a graphical shutdown utility for Linux and Windows. It allows you to turn off or suspend a computer at a specified time. It features various time and delay options, command-line support, and notifications.

**Metadata**

* homepage URL: https://kshutdown.sourceforge.io/
* source URL: https://kshutdown.sourceforge.io/download.html
* license: GPL 2
* platforms:

**Comment by Guanran928** [comment]
https://github.com/NixOS/nixpkgs/pull/298729
