### ISSUE TITLE
libpulseaudio questions

### ISSUE THREAD

**Issue by efferifick** [NixOS/nixpkgs#21701]
## Issue description

libpulseaudio does not install on macOS

### Steps to reproduce

nix-shell -p libpulseaudio

## Technical details

* System: macOS 10.12.2
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "17.03pre98241.ad8f0b6"

Hello,
I needed to install another package that depended on libpulseaudio but libpulseaudio fails to install on darwin. I cloned this repository and I am currently attempting to submit a patch. However, I am uncertain of a couple of things. I am attaching the patch that I am working on. 

[simple.txt](https://github.com/NixOS/nixpkgs/files/688747/simple.txt)

* First, applying this patch will at least allow nixpkgs to continue without errors after using the following command `nix-env -f . --show-trace -i libpulseaudio`. Using `nix-env -q --installed` shows that I have libpulseaudio-9.0 installed but I have not confirmed it in any other way. I am not familiar with libpulseaudio but, as I said, a package I need has it listed as a dependency, so is there a way I can test it? I am trying to compile a simple C file with `libpulseaudio` headers but I am not sure where the libraries are located.
* Second, I am not sure about the differences between `libpulseaudio`, `pulseaudioLight`, and `pulseaudioFull`. It seems that all of them are important. In previous attempts to install `libpulseaudio` I ommitted the `inherit (darwin.apple_sdk....` statement from `pulseaudioLight` and `pulseaudioFull` but it seems that it is needed on all three. Otherwise I get the following error: 
```
e$ nix-env -f . --show-trace -i libpulseaudio
error: while evaluating ‘callPackageWith’ at /Users/e/Code/nixpkgs/lib/customisation.nix:95:35, called from /Users/e/Code/nixpkgs/pkgs/top-level/all-packages.nix:12459:10:
while evaluating ‘makeOverridable’ at /Users/e/Code/nixpkgs/lib/customisation.nix:54:24, called from /Users/e/Code/nixpkgs/lib/customisation.nix:99:8:
while evaluating anonymous function at /Users/e/Code/nixpkgs/pkgs/applications/video/bomi/default.nix:1:1, called from /Users/e/Code/nixpkgs/lib/customisation.nix:56:12:
while evaluating ‘callPackageWith’ at /Users/e/Code/nixpkgs/lib/customisation.nix:95:35, called from /Users/e/Code/nixpkgs/pkgs/top-level/all-packages.nix:10319:19:
while evaluating ‘makeOverridable’ at /Users/e/Code/nixpkgs/lib/customisation.nix:54:24, called from /Users/e/Code/nixpkgs/lib/customisation.nix:99:8:
anonymous function at /Users/e/Code/nixpkgs/pkgs/servers/pulseaudio/default.nix:1:1 called without required argument ‘CoreServices’, at /Users/e/Code/nixpkgs/lib/customisation.nix:56:12
```
So my question is, what is the difference between these three?
* Third, I included [this patch](https://bugs.freedesktop.org/attachment.cgi?id=127889) from `libpulseaudio`'s [bug tracking system](https://bugs.freedesktop.org/show_bug.cgi?id=98603) and just applied it as another patch. Is this the correct convention?

Thanks

**Comment by LnL7** [comment]
https://github.com/NixOS/nixpkgs/pull/21681 contains a fix for pulseaudio.

The reason you noticed the issues with the other variants is because you installed the package by name. In order for nix to find the correct name it has to evaluate each package.
I you use `-A` you can install a package by attribute name instead eg. `nix-env -iA pulseaudioFull`. This is actually quite a bit faster because nix does not evaluate all the packages in that case, but you have to know the exact attribute name.

**Comment by efferifick** [comment]
Awesome! Thanks for the link to pulse audio fix! I'll close this issue now.

**Comment by LnL7** [comment]
If you want to use a package like this as a dependency I highly recommend looking at how nix-shell works instead of installing dependencies in your user environment.
Building the project inside `nix-shell -p pulseaudio.dev` might be enough to make it find the dependency
