### ISSUE TITLE
Best practice for packaging a Pharo application?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#21715]
I have started working on a Pharo-based application ([Studio](http://github.com/studio/studio)) that I would like to build and install with Nix.

Question is: How should I build the Pharo image for my application?

I see options:

1. Build the image outside the Nix ecosystem (Pharo seems to use Bintray?) and import with `fetchurl`.
2. Get a close ancestor of the image I want (e.g. Moose-6.0) with `fetchurl` and then use Nix to add my own packages from source.
3. Get a basic image (e.g. Pharo-5.0) and add all relevant packages from the Pharo universe.

I am wondering which is most appropriate?

Seems like (1) would work and is the path of least resistance. With (2) I could have Hydra build images when I push changes which seems appealing. With (3) I would have all dependencies tracked with Nix but this may be a huge amount of work to replicate the existing inter-package dependencies in Nix.

Thoughts or experience reports would be welcome! cc @DamienCassou 

Relatedly: I wrote a little Nix expression for downloading a Pharo image and running code. I am a little confused that it seems to take 20 seconds to run a trivial expression. Could be due to e.g. special startup code that the image runs the first time on a new machine?

```nix
{ stdenv, fetchurl, unzip, runCommand, pharo-vm5 }:

with stdenv;

rec {
  pharo-50-image = mkDerivation rec {
    name = "pharo-image-5.0";

    buildInputs = [ unzip ];

    src = fetchurl {
	name = "pharo-image-5.0-50765.zip";
	url = "http://files.pharo.org/image/50/50765.zip";
	sha256 = "00hkxcj5kcdbp5kxk2b94bk811w1g2z620xq744gx7msh3kvlacc";
    };

    unpackPhase = ''
      unzip $src
    '';

    installPhase = ''
      mkdir -p $out
      cp *.image *.changes $out/
      ln -s $out/*.image $out/Pharo.image
      ln -s $out/*.changes $out/Pharo.changes
    '';
  };

  test = runCommand "test" { buildInputs = [ pharo-vm5 ]; } ''
    pharo-nox ...
  '';
}
```

**Comment by DamienCassou** [comment]
Hi @lukego,


> 1.  Build the image outside the Nix ecosystem (Pharo seems to use Bintray?) and import with fetchurl.

I've never seen any use of Bintray and I don't even know what that is. I recommend this approach as it means the process is fully reproducible on the nix side: nix will always have exactly the same store path for a given hash. You can use https://ci.inria.fr/pharo-contribution/ to build your images.

> 2.    Get a close ancestor of the image I want (e.g. Moose-6.0) with fetchurl and then use Nix to add my own packages from source.

This is feasible but the nix store path for a given hash will not be fixed. The nix ecosystem tries hard to have binary-reproducible builds: it means that for a given hash, nix will try to always output the same store path. Pharo doesn't guarantee that and several users building the same derivation will get different store paths.

> 3.    Get a basic image (e.g. Pharo-5.0) and add all relevant packages from the Pharo universe.

This is probably a lot of work and will suffer from the same problem as 2.

> Relatedly: I wrote a little Nix expression for downloading a Pharo image and running code. I am a little confused that it seems to take 20 seconds to run a trivial expression. Could be due to e.g. special startup code that the image runs the first time on a new machine?

there is an option you can pass to `pharo-nox` on the command line to tell it to avoid loading user preferences. I don't see any other reason why it is so slow. Ask the mailing list.

**Comment by lukego** [comment]
Thanks for the great answers @DamienCassou!
