### ISSUE TITLE
Update request: eduke32 20221225 → 20230123 + additional build flag request

### ISSUE THREAD

**Issue by revuwa** [NixOS/nixpkgs#217140]
- Package name: [eduke32](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/eduke32/default.nix)
- Latest released version: [20230123](https://dukeworld.com/eduke32/synthesis/latest/)

- Current version on the unstable channel: 20221225
- Current version on the stable/release channel: 20221026

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@mikroskeem @svanderburg 

-----

Note for maintainers: Please tag this issue in your PR.

###### Please add build flag voidsw

I realized through the [eduke32's changelog](https://dukeworld.com/eduke32/synthesis/latest/ChangeLog.txt), which refers to the source code of the following repo: "See https://voidpoint.io/terminx/eduke32 for more details.", that eduke32 seems to support Shadow Warrior, which the [eduke32 wiki](https://wiki.eduke32.com/wiki/Frequently_Asked_Questions) confirms with: "Shadow Warrior (Note: Supported by VoidSW ONLY, not EDuke32 itself!)".

Furthermore it seems that this "EDuke32's VoidSW launcher" (to run Shadow Warrior) could be build with a eduke32 build flag, as Gentoo did it, for example: 
- https://bugs.gentoo.org/754951
- https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4888ef21474c75ca7570e356be326a66ee09f853

-> flag name="voidsw" Enable support for Shadow Warrior (Classic) through VoidSW

In addition to the apparently uninteresting project: [raze](https://github.com/NixOS/nixpkgs/issues/189163), this could be another option to start Shadow Warrior emulated under NixOS, or is there anything against it? What do you think?

**Comment by raspher** [comment]
#258457
