### ISSUE TITLE
nixos: systemd doesn't respect fileSystems.<name>.depends

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nixpkgs#217179]
### Describe the bug
systemd doesn't respect the `depends` option for file systems. Usually this is ok because systemd will mount file systems in the correct topological ordering. The `depends` option is useful because it allows you to express dependencies on e.g. the file systems that an `overlay` FS's lower/upper/work directories exist on.

### Steps To Reproduce
This test *should* hang forever. Instead, it exits cleanly.

```nix
import ./nixos/tests/make-test-python.nix ({ lib, pkgs, ... }: {
  name = "should-hang";

  nodes.machine = {
    systemd.services.block-foo = {
      unitConfig.DefaultDependencies = false;
      serviceConfig = {
        ExecStart = "${pkgs.coreutils}/bin/sleep infinity";
        Type = "oneshot";
      };
    };

    virtualisation.fileSystems = {
      "/foo" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["nofail" "x-systemd.requires=block-foo.service" "x-systemd.after=block-foo.service"];
      };

      "/bar" = {
        device = "tmpfs";
        fsType = "tmpfs";
        depends = ["/foo"];
        # This would fix it:
        # options = ["x-systemd.requires-mounts-for=/foo"];                                                                                                                                   
      };
    };
  };

  testScript = ''                                                                                                                                                                             
    machine.wait_for_unit("bar.mount")                                                                                                                                                        
    machine.fail("mount | grep foo")                                                                                                                                                          
  '';
})
```

### Expected behavior
The `block-foo` service never exits, so `/foo` is never mounted, and therefore `/bar` should never be mounted. So the test should hang.

### Additional context
This is also a problem for systemd stage 1, but it's worse because we also have to account for the `/sysroot` prefix. We can fix this by adding `x-systemd.requires-mounts-for=` options for every dependency, and prefixing `/sysroot` for the systemd stage 1 file systems.

**Comment by nikstur** [comment]
Do we even need the `depends` option? I don't think they're particularly useful. The overlay also shouldn't be a concern since https://github.com/NixOS/nixpkgs/pull/286176 anymore.

**Comment by ElvishJerricco** [comment]
@nikstur Well, currently `depends` literally only does anything in scripted stage 1. In stage 2 and in systemd stage 1, you have to use `x-systemd.requires-mounts-for=`, which is what the `overlay` stuff does. That's fine, but it's an incompatibility between scripted and systemd stage 1. So we need to either deprecate it or implement it, and it's really easy to implement (I just need to fixup https://github.com/NixOS/nixpkgs/pull/233707). It's a handy convenience for people I guess, though far from a necessary one.
