### ISSUE TITLE
libX11 1.8.3 breaks video rendering in some games, please patch/upgrade

### ISSUE THREAD

**Issue by jpotier** [NixOS/nixpkgs#217237]
### Describe the bug

Here's the upstream bug in libX11 (https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/174) which includes a link to a merged patch (https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/180.patch).

This is a request to either patch or upgrade libX11 in nixpkgs.

### Notify maintainers

@trofi was the last person to upgrade xorg.libX11

**Comment by trofi** [comment]
https://github.com/NixOS/nixpkgs/pull/216391 recently updated it to `1.8.4`. https://github.com/NixOS/nixpkgs/pull/216391/commits/a57fd65b7bd074e5fe19f95e8d58a0ed6ea1867d says it's already in `staging-next`. Can you give it a go an check it it works fine there?

**Comment by vcunat** [comment]
If I read this right, our stable 22.11 shouldn't be affected, as we still have libX11 `1.8.1` in there.

**Comment by jpotier** [comment]
Currently in the process of building my nixos configuration against https://github.com/NixOS/nixpkgs/commit/a57fd65b7bd074e5fe19f95e8d58a0ed6ea1867d. Lots of building happening

**Comment by vcunat** [comment]
@jpotier: don't do that.  Use the latest `staging-next` branch.

**Comment by trofi** [comment]
Yeah, or even better pick latest commit with enough builds at https://hydra.nixos.org/jobset/nixpkgs/staging-next. Like,  09e298d.

**Comment by jpotier** [comment]
I had assumed (wrongly) all commits would have a gone through hydra, thanks for the pointer!

**Comment by vcunat** [comment]
No, it would be very expensive to build everything on every commit.  That's the reason why big rebuilds get merged to `staging` branch.

**Comment by jpotier** [comment]
Sadly, I'm still trying to get a full build go through. firefox, linux and other big packages need building, and it's taking a while. I had to remount my tmp to disk because I was running out etc.

**Comment by jpotier** [comment]
@trofi I can confirm the issue is gone with libX11 1.8.4

**Comment by trofi** [comment]
That's great! Thank you to the test! This issue should close automatically once PR gets merged to `master` automatically. Should take 1-2 weeks worst case.

**Comment by wllianwd** [comment]
Just out of curiosity, how could I specify this version of libX11 in my system meanwhile it is not merged? I tried override but seems not working.

Here my nix config:
https://github.com/wllianwd/my-nix-os

**Comment by jpotier** [comment]
I've had no success successfully building my system by just overriding my configuration with the new version of libX11. It rebuilds too many things, and some things didn't even build correctly against the new version. By far, it was easier to pin my system to https://github.com/NixOS/nixpkgs/commit/09e298dc8ef984f8b604bf74e26794c4018aec10 as suggested above. I had to remove (until unstable channel catches up) some software which also didn't build from staging-next.

Concretely, in my `flake.nix`:

```
  inputs = {
    # Picking commit from staging-next containing newer libX11 (> 1.8.3)
    nixpkgs.url = "github:NixOS/nixpkgs?rev=09e298dc8ef984f8b604bf74e26794c4018aec10";
   ...
```

**Comment by vcunat** [comment]
Yes.  It's in `master` branch already; I'd hope that `nixos-unstable` could catch up later today, but we'll see.

**Comment by jpotier** [comment]
Oh nice! I thought this issue would auto-close when that was the case, so I missed it.

**Comment by jpotier** [comment]
Leaving this here if others are interested in the status of this change: https://nixpk.gs/pr-tracker.html?pr=216391

**Comment by vcunat** [comment]
All the channels have this now.
