### ISSUE TITLE
Package request: Cryptpad

### ISSUE THREAD

**Issue by Anderssorby** [NixOS/nixpkgs#217231]
**Project description**

CryptPad is a collaborative office suite that is end-to-end encrypted and open-source. Enable this a service for NixOS.

**Metadata**

* homepage URL: https://cryptpad.org
* source URL: https://github.com/xwiki-labs/cryptpad
* license: agpl2 
* platforms: unix, linux, darwin, ...

**Comment by kilianar** [comment]
CryptPad used to be included in nixpkgs, but it was removed because there weren't enough maintainers. The removal occurred with the commits 126bd386d802ac9b99b9a2deb30d3800dd26013c and 1c0cc017b5e8788451e919cbf81b29b60916dda1.

**Comment by Pamplemousse** [comment]
> it was removed because there weren't enough maintainers

Not quite true: it was removed because they had a strong dependency on out-of-date software. [Which was eventually tackled](https://github.com/cryptpad/cryptpad/pull/989).

Now, there is an ongoing effort to re-introduce it in `nixpkgs`: https://github.com/NixOS/nixpkgs/pull/251687 .
