### ISSUE TITLE
mousepad: eats 100% CPU

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21725]
## Issue description

After few seconds after the launch ```mousepad``` starts eating cpu

in journald there are thousands of lines like
```
Jan 06 21:07:06 nixos .mousepad-wrapp[27545]: gtk_source_style_scheme_get_id: assertion 'GTK_IS_SOURCE_STYLE_SCHEME (scheme)' failed
Jan 06 21:07:06 nixos .mousepad-wrapp[27545]: gtk_source_style_scheme_manager_get_scheme: assertion 'scheme_id != NULL' failed
Jan 06 21:07:06 nixos .mousepad-wrapp[27545]: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
Jan 06 21:07:06 nixos .mousepad-wrapp[27545]: gtk_source_style_scheme_get_id: assertion 'GTK_IS_SOURCE_STYLE_SCHEME (scheme)' failed
Jan 06 21:07:06 nixos .mousepad-wrapp[27545]: g_variant_new_string: assertion 'string != NULL' failed
```

### Steps to reproduce

launch ```mousepad``` and ```journalctl -f```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09-stable, 17.03-unstable

* Nix version: (run `nix-env --version`)
1.1.15

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03.git.5ebee164fa"

**Comment by Mic92** [comment]
Seems to require `dconf`

**Comment by volth** [comment]
duplicate #14862
