### ISSUE TITLE
Python: do not use pip to install wheels in buildPythonPackage

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#21736]
## Issue description

i created a fresh default.nix for a python repo i use, i forgot a few dependencies
the install process fetches them while happyly breaking building wheels 

i expected to get a hard failure

i believe should not use pip to install packages

### Steps to reproduce

branch in the repo upcoming

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`) `nix-env (Nix) 1.11.5`

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) : `"17.03pre98383.7ee897a"`

**Comment by FRidh** [comment]
1. If you have network access (which you do in a `nix-shell`) then yes, any program can fetch. This is expected and will happen with more programs.
2. How should we install packages? Saying that we shouldn't do a certain thing without further argumentation nor alternatives isn't very constructive.

**Comment by RonnyPfannschmidt** [comment]
for 1. i would expect no network action possible while building the environment (in order to stay reasonably close to the real env)

as for installing python packages, it i believe it should be much saver to have a wheel as a output, and use that to generate a target folder

unfortunately im not sure how to prototype such a pip-free builder - there would be a need for a stage1 set of setuptools/wheel packages to bootstrap setuptools/wheel wheels and go with the rest

**Comment by FRidh** [comment]
> for 1. i would expect no network action possible while building the environment (in order to stay reasonably close to the real env)

How would you do that in `nix-shell`? Anyway, that is something to discuss on the Nix tracker, not here.

> as for installing python packages, it i believe it should be much saver to have a wheel as a output, and use that to generate a target folder

By default we use build wheels, and then install the wheels. The wheels can be build in different ways. We could use `python -m wheel install wheel_file.whl` but we have certain arguments we pass to `pip` and I don't know whether `wheel` accepts those.

> unfortunately im not sure how to prototype such a pip-free builder - there would be a need for a stage1 set of setuptools/wheel packages to bootstrap setuptools/wheel wheels and go with the rest

Building the wheel, and installing the wheel is already separated. We only use `pip` for installing the wheel. 
If  `python -m wheel install wheel_file.whl` would be sufficient we could get rid of `pip`.

Bootstrapping isn't such a big problem; that's basically just unzipping the wheels as we do already.

**Comment by Ekleog** [comment]
(triage) Needs closing? :)

**Comment by FRidh** [comment]
There is no good alternative so closing.
