### ISSUE TITLE
Dota 2 fails to launch after recent update

### ISSUE THREAD

**Issue by jtrees** [NixOS/nixpkgs#217344]
## Issue description

When attempting to launch Dota 2 via Steam a window pops up with this message:

> Failed to create an OpenGL context.
> Your graphics card must support at least OpenGL v3.1.

### Steps to reproduce

Add the following to your config:

```nix
programs.steam.enable = true;
```

1. Open Steam
2. Find Dota 2 in the UI
3. Click on PLAY

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 22.11 (Raccoon), 22.11.2643.0cf4274b5d0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-unstable, vuizvui"`
 - channels(josh): `"release-22.11.tar.gz-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 - gpu: AMD Radeon RX 6600

## Additional Notes

- this setup has been working for months
- glxgears works
- I tried an old NixOS generation where the game was definitely working. It still fails the same way so I presume the root cause if from some Valve changes.
- found this in my logs:

```
Feb 20 19:25:23 themis xmonad[27327]: libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri, suffix _dri)
Feb 20 19:25:23 themis xmonad[27327]: libGL error: MESA-LOADER: failed to open swrast: /usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/dri:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/dri, suffix _dri)
```

## Workaround

Thanks to @pongo1231 for [this](https://github.com/NixOS/nixpkgs/issues/216361#issuecomment-1435997142):

1. Open Steam
2. Find the "Steam Linux Runtime - Soldier" tool in your library.
3. Right click -> Properties -> Betas
4. Select the "previous_release" beta from the dropdown

**Comment by LowYieldFire** [comment]
This does not just affect Nixos users https://github.com/ValveSoftware/steam-runtime/issues/566.
A temporary fix is to revert back to the previous version of the `Steam Linux Runtime` as detailed in https://github.com/ValveSoftware/steam-runtime/issues/566#issuecomment-1438586783.

**Comment by LowYieldFire** [comment]
I ran steam with `STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1 steam` to produce these logs of both the old and new versions of the runtime.
 - Steam Linux Runtime soldier (old, working): https://gist.github.com/LowYieldFire/8e185402f4d952745aadc45d616550db
 - Steam Linux Runtime soldier (new, broken): https://gist.github.com/LowYieldFire/7204295d6d487b5342ad20f1f04dfd48

**Comment by LowYieldFire** [comment]
@smcv You are right, the issue seems to be resolved with this merge https://github.com/NixOS/nixpkgs/pull/216883. For any Nixos users ending up here, you can just rebuild your system from the latest nixos-unstable to fix the issue.

**Comment by leiserfg** [comment]
> We are trying to figure out what is happening in 566,

No idea if it helps but I noticed it only breaks when playing online, not when playing against bots. Moving to unstable fixed the issue indeed.

**Comment by smcv** [comment]
@leiserfg:
> Moving to unstable fixed the issue indeed.

Based on that, it is quite likely that what you are seeing is a variation of https://github.com/ValveSoftware/steam-runtime/issues/562, for which see https://github.com/ValveSoftware/steam-runtime/issues/562#issuecomment-1446942585 for a solution that is available to test via the *Steam Linux Runtime - soldier* beta.
