### ISSUE TITLE
nixops not installing because pyjwt tests fail

### ISSUE THREAD

**Issue by dan-passaro** [NixOS/nixpkgs#21730]
## Issue description

Running `nix-env -i nixops` fails to install nixops

### Steps to reproduce

    $ nix-env -i nixops
    [... failed build output, including pyjwt tests...]

For the curious, I've attached the [full output of the command](https://github.com/NixOS/nixpkgs/files/691296/build-output.txt). It looks like perhaps some internal API that pyjwt was relying on (RSA._RSAobj) is no longer available... but that's pure speculation on my part.

## Technical details

* System: Arch Linux rolling
* Nix version: nix-env (Nix) 1.11.5
* Nixpkgs version: 17.03pre98398.7215118

**Comment by FRidh** [comment]
I'll have a look at pyjwt, it seems it shouldn't depend on pycrypto anymore anyway. Unfortunately I can't test it right away since my Nix is broken at the moment.

**Comment by FRidh** [comment]
I've removed the `pycrypto` dependency and replaced it with `cryptography` which is what upstream recommends. Indeed, it seems they were relying on something internal which is likely why the dummy didn't work. `nixops` builds again with 969651aacaf79c96527931918dc3c6f6f6ba94ff
