### ISSUE TITLE
nix-prefetch-github?

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#21732]
Just wondering: Is there a `nix-prefetch-github` command somewhere?

Imaginary example:

```
$ nix-prefetch-github nixos nixpkgs 16.09
{
  owner = "nixos";
  repo = "nixpkgs";
  rev = "...";
  sha256 = "...";
}
```

Just thinking this could be very handy for automatically generating sources lists e.g. if you want to be able to address all releases of a given project. Just to avoid the busy-work of manually translating the branch/tag to a revision id and "use a fake sha256, get real sha256 from error message, copy-paste and build again" dance.

**Comment by Mic92** [comment]
It would be a thin wrapper around `fetchzip`. The wrapper could also implement the following helper:

- fetchFromBitbucket
- fetchFromGitLab
- fetchFromSavannah

Implementation details can be seen here:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L194

**Comment by domenkozar** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/21734

**Comment by zimbatm** [comment]
If it's just updating the sha256 then `nix-prefetch-url -A mypackage.src` can be used

**Comment by edolstra** [comment]
Closing because we already have `nix-prefetch-url -A`.

**Comment by Mic92** [comment]
This method is not documented as far as I know.

**Comment by domenkozar** [comment]
Agreed - we should change docs at least.

**Comment by dezgeg** [comment]
Does `nix-prefetch-url -A mypackage.src` even give the right answer given that `fetchFromGitHub` uses `fetchzip`? Or is it smart enough to do same as `nix-build --hash`?

**Comment by domenkozar** [comment]
At least two bits:

- `nix-prefetch-url -A` is not documented in `--help`
- prefetching nixpkgs is not easy with this method. As @lukego states we'd have to print the arguments to the `fetch*` function to really be iterative

**Comment by robinvd** [comment]
@domenkozar What does the -A flag do?

**Comment by domenkozar** [comment]
```
$ nix-prefetch-url -A linuxPackages.kernel.src
 [78443/90991 KiB, 11001.6 KiB/s]g/pub/linux/kernel/v4.x/linux-4.9.49.tar.xz’... [0/0 KiB, 0.0 Ki [0/90991 KiB, 0.0 KiB/s]
path is ‘/nix/store/mbdwpv9cvyk3wfnd6mvzw0f6yklj9cgq-linux-4.9.49.tar.xz’
1ywiww2h1gf3ps305irzk7n9xkcgg9bclr2jw6r5cqxmh3qxrv2p
```

**Comment by domenkozar** [comment]
Impure world might not have:

a) access to Nix expressions
b) ability to update Nix expressions

so `nix-prefetch-url -A` is not an option in those cases (like cabal2nix).

**Comment by seppeljordan** [comment]
Hi, I wrote a little something to prefetch github sources.  Check it out here: [seppeljordan/nix-prefetch-github](https://github.com/seppeljordan/nix-prefetch-github) or install it from [pypi](https://pypi.org/project/nix-prefetch-github/).

**Comment by FRidh** [comment]
Added in #39214.

**Comment by nrolland** [comment]
(installing via `nix-env -i nix-prefetch-github`)

if I `nix-prefetch-github ghc ghc`, what does it do exactly ?
is it like nix-prefetch-url which downloads and stores in the content addressable store ?

**Comment by pSub** [comment]
@nrolland From what I've seen it just downloads the source and computes the hash, but it does not add it to the nix-store.

**Comment by pSub** [comment]
Closing. Such a program was added in #39214.
