### ISSUE TITLE
Incorrect timezone reported in logseq

### ISSUE THREAD

**Issue by meain** [NixOS/nixpkgs#217320]
### Describe the bug
Timezone and as a result time reported in logseq seems to be incorrect. https://github.com/NixOS/nixpkgs/pull/205057 seems to be what has affected it. I initially suspected it was from use not copying over `locale` folder, but that does not seem to it. I suspect it is from changing to running using appimage instead of electron.

### Steps To Reproduce
1. Start logseq
2. Go to developer tools
3. Run `new Date()`

### Expected behavior
Timezone should be properly identified, and correct time reported.

### Notify maintainers

@LoveIsGrief @kilianar @weihua-lu 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-60-generic, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(meain): `"home-manager-21.11, nixpkgs-22.05pre363562.30d3d79b7d3, stable-21.11.336824.ccb90fb9e11, unstable-22.05pre363562.30d3d79b7d3"`
 - channels(root): `"nixpkgs-22.05pre336690.f225322e3be"`
 - nixpkgs: `/home/meain/.nix-defexpr/channels/nixpkgs`
```

**Comment by LoveIsGrief** [comment]
Out of curiosity, when you run `date` in your console, is it correct?

FYI both versions before the PR a are using an app image. Before, the contents were extracted and stored in /nix/store, now appimage-run stores them in ~/.cache/... The difference might be that before the system's electron was being run , whereas now the electron that was extracted from the app image is being used.
I'm curious if there's an extra wrapper that appimage-run generates that isn't setting the timezone correctly, but that would be an appimage-run problem. Maybe somebody who's more intimate with the script might know.

The only test I can think of is to run `date` from within the same environment as the one logseq is being run.

**Comment by meain** [comment]
> The only test I can think of is to run `date` from within the same environment as the one logseq is being run.

I'm not sure if this is what you mean by same environment, but running `date` from the same shell as the one I was running the built `./result/bin/logseq` reports correct date.

**Comment by meain** [comment]
Just for more context, reverting back to the old commit works, as well as just applying the version bump without the appimage run changes also report the correct time. So, it is possible that you are probably correct about the following.

> I'm curious if there's an extra wrapper that appimage-run generates that isn't setting the timezone correctly, but that would be an appimage-run problem. Maybe somebody who's more intimate with the script might know.

**Comment by meain** [comment]
Yup, looks like reverting that seems to have fixed the issue with time.
