### ISSUE TITLE
Package request: session manager plugin for awscli2

### ISSUE THREAD

**Issue by i10416** [NixOS/nixpkgs#217443]
**Project description**

It requires session manager plugin to port-forward requests to AWS private instances. 
With aws-cli and session manager plugin, you can connect to instances in private subnet in secure way.

Is it possible to add option to awscli2 like `pkgs.awscli2.override { enableSSM = true; }` so that we can optionally install session manager plugin?

**Metadata**

* homepage URL: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
* source URL: https://github.com/aws/session-manager-plugin
* license: Apache License 2.0
* platforms: unix, linux, darwin

**Related package**: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/awscli2/default.nix

**Comment by zvictor** [comment]
What you need is `ssm-session-manager-plugin`.

Try:
```nix
nix-shell -p awscli2 ssm-session-manager-plugin --run "aws ssm start-session --target <your-target>"
```
