### ISSUE TITLE
teams package is broken

### ISSUE THREAD

**Issue by daef** [NixOS/nixpkgs#217473]
### Describe the bug
I tried to install teams, but the download of the referenced .deb package fails
( https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb via https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/applications/networking/instant-messengers/teams/default.nix )

```console
$ sudo nixos-rebuild switch --flake ~d/nixig#doti
[sudo] password for d:
building the system configuration...
error: builder for '/nix/store/q52fa2j5bn9cyqvajqk4y350n34sgq1q-teams_1.5.00.23861_amd64.deb.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0   162    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download teams_1.5.00.23861_amd64.deb from any mirror
       For full logs, run 'nix log /nix/store/q52fa2j5bn9cyqvajqk4y350n34sgq1q-teams_1.5.00.23861_amd64.deb.drv'.
error: 1 dependencies of derivation '/nix/store/4znrzrax77dn8ryyrmzfz6s37jxa0sbf-teams-1.5.00.23861.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sgx3mwjcjidhmnqp92iv411k7nnxvanw-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/95n288gfbmnjc8xvmv3hqb27irilhjj3-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lhwzhm32cy5zw8z06kwfxa35ynjq6wm9-nixos-system-doti-23.05.20230207.fab0908.drv' failed to build

$
```

### Steps To Reproduce
1. Try to install teams

### Expected behavior
Teams gets installed

### Notify maintainers
@liff @tricktron 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.10, NixOS, 23.05 (Stoat), 23.05.20230207.fab0908`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by liff** [comment]
The download links on the [download page](https://www.microsoft.com/en-us/microsoft-teams/download-app) are broken. Perhaps if it’s just temporary?

**Comment by daef** [comment]
Oh - I didn't think about checking one step further up...

**Comment by daef** [comment]
I found https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/ (via https://answers.microsoft.com/en-us/msteams/forum/all/i-can-no-longer-download-teams-for-linux-desktop/457e2e64-a4ea-4753-91e1-2d25b98810c6 ) which is supposed to list the missing file (it isn't).

**Comment by liff** [comment]
[Here’s a more recent thread](https://answers.microsoft.com/en-us/msteams/forum/all/ms-teams-download-is-borken/b2dba16e-0d86-4ab5-a64f-7a9b13f12cc2), with no resolution as of yet.

**Comment by 4o4forbidden** [comment]
having the same problem since yesterday !

**Comment by parided** [comment]
https://repology.org/project/teams/information

**Comment by liff** [comment]
Hmm, the latest version seems to be available from archive.org, so maybe we can use that as an alternative source in `fetchurl`.

**Comment by liff** [comment]
Meanwhile, for those having problems with this, you can preload the package from archive.org with `nix-prefetch-url`:

```shell
nix-prefetch-url 'https://web.archive.org/web/20221130115842if_/https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb' 'sha256-h0YnCeJX//l4TegJVZtavV3HrxjYUF2Fa5KmaYmZW8E='
```

It should build and install successfully after that.

**Comment by xeals** [comment]
Download links have probably been pulled as Microsoft has [sunset the Linux client](https://techcommunity.microsoft.com/t5/microsoft-teams/end-of-the-road-for-teams-linux-desktop-client/td-p/3630968) in favour of their web version. In my experience the web client does work much better than the native one, including desktop sharing through Pipewire, for what it's worth.
