### ISSUE TITLE
Update request: NetworkManager 1.40.6 → 1.42.0

### ISSUE THREAD

**Issue by RicArch97** [NixOS/nixpkgs#217510]
See https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/1.42.0/NEWS

- Package name: NetworkManager
- Latest released version: 1.42.0

- Current version on the unstable channel: 1.40.6
- Current version on the stable/release channel: 1.40.6

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by bobby285271** [comment]
https://github.com/NixOS/nixpkgs/pull/219688 (it missed staging-next 2023-03-04 so you need to wait for the next staging-next though)

**Comment by RicArch97** [comment]
Thanks, this landed in unstable, so closing this issue.
