### ISSUE TITLE
Move bootstrap binaries to nixos.org

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#2175]
Since 986f36194650e2a41451cbfb9f29ce1c66a62df3, we've been using `<nix/fetchurl>` to "fetch" the initial `fetchurl` bootstrapping binaries from the local filesystem. Now that that's been in place for a while, we should put those on nixos.org, change the URLs, and remove those binaries from the tree.

**Comment by wmertens** [comment]
Fixed by https://github.com/NixOS/nixpkgs/commit/d4f44d6db351bdfcd089a26fc9cc973254a48cae
