### ISSUE TITLE
helmfile version set to 0.0.0-dev

### ISSUE THREAD

**Issue by NelsonJeppesen** [NixOS/nixpkgs#217592]
### Describe the bug
`helmfile` reports the wrong version

```
❯ nix-shell -p helmfile -I nixpkgs=/nix/var/nix/profiles/per-user/nelson/channels/nixos-unstable --run 'helmfile --version'
helmfile version 0.0.0-dev
```

This is a problem because it causes issues with `helmfile.lock` file

e.g. 
```
helmfile deps
```
```
$ git diff
+++ b/namespaces/kube-system/helmfile.lock
@@ -1,10 +1,10 @@
-version: 0.145.2
+version: 0.0.0-dev
...
```

### Steps To Reproduce
1. install `helmfile` from `unstable`
2. observe the version number is wrong 

### Expected behavior
1. the version should be set using the git version tag

### Additional context
The version path changed from
```github.com/helmfile/helmfile/pkg/app/version.Version```
to
```go.szostok.io/version.version```
in commit
https://github.com/helmfile/helmfile/pull/412/commits/8e45843aa651bcad833221d3984bb598e9fd0f34

### Notify maintainers
@yurrriq

**Comment by yurrriq** [comment]
thanks for reporting! and thanks again to @azuwis for the patch!
