### ISSUE TITLE
Build failure: sphinx-5.3.0 on master

### ISSUE THREAD

**Issue by tfc** [NixOS/nixpkgs#217647]
### Steps To Reproduce

1. Build `pkgs.python3Packages.sphinx` on current master

Applying the following patch which disables 3 test cases, fixes the build:

```
diff --git a/pkgs/development/python-modules/sphinx/default.nix b/pkgs/development/python-modules/sphinx/default.nix
index 74abbe90c96..bec6df6da3a 100644
--- a/pkgs/development/python-modules/sphinx/default.nix
+++ b/pkgs/development/python-modules/sphinx/default.nix
@@ -97,6 +97,10 @@ buildPythonPackage rec {
   '';
 
   disabledTests = [
+    "test_viewcode"
+    "test_additional_targets_should_not_be_translated"
+    "test_additional_targets_should_be_translated"
+
     # requires network access
     "test_anchors_ignored"
     "test_defaults"
```

I don't have enough project knowledge to reason if these tests fail for good or bad reasons.

### Build log

https://gist.github.com/tfc/980d1a45c88d1b5c2a50338f04c0bcd8

### Notify maintainers

@SuperSandro2000 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
09:53 tfc@build01 ~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.91, NixOS, 22.11 (Raccoon), 22.11.20230205.cff83d5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSandro2000** [comment]
Can't reproduce.

**Comment by tfc** [comment]
You're right, on master this is not reproducible, it seems to be due to the changes in this PR: https://github.com/NixOS/nixpkgs/pull/217637

Thank you for looking into this, could you please try build sphinx again in that branch?
