### ISSUE TITLE
Make fetchzip support urls like fetchurl does

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#21769]
@grahamc pointed out that `fetchurl` supports a `urls` parameter for trying multiple URLs for the same resource. However, `fetchzip` is built in such a way that it doesn't support this feature. Hacking around it doesn't work either: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/default.nix#L83

**Comment by Artturin** [comment]
Fixed in 9f78dd4a1cb4b20c820ed98c7a69e9c6534fff71
