### ISSUE TITLE
compress-man-pages.sh broken by recent changes in 'master'

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#21777]
The following derivation used to work fine:

~~~
    ledgerEnv = self.stdenv.mkDerivation {
      name = "ledger-env-0";
      unpackPhase = ":";
      installPhase = ''
        mkdir -p $out/{bin,share}
        ln -sv ${self.ledger2}/bin/ledger $out/bin/ledger2
        ln -sv ${self.ledger3}/bin/ledger $out/bin/ledger3
        ln -sv ledger3 $out/bin/ledger
        ln -sv ${self.ledger3}/share/man $out/share/
      '';
    };
~~~

But now it's broken in current Nixpkgs `master`, giving the following error message:

~~~~
[...]
'/nix/store/9mwh4azklkq62ss1rrpl0v0pv928q76f-ledger-env-0/share/man' -> '/nix/store/9szv7hrhplvw8b931bqv5fgpza91vcvb-ledger-3.1.1/share/man'
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/9mwh4azklkq62ss1rrpl0v0pv928q76f-ledger-env-0
gzipping man pages in /nix/store/9mwh4azklkq62ss1rrpl0v0pv928q76f-ledger-env-0
/nix/store/cc7k5l8k7q0lqsanciz3q4mili9bwxpy-compress-man-pages.sh: line 13: /nix/store/9mwh4azklkq62ss1rrpl0v0pv928q76f-ledger-env-0/share/man/man1/ledger.1.gz.gz: Permission denied
rm: cannot remove '/nix/store/9mwh4azklkq62ss1rrpl0v0pv928q76f-ledger-env-0/share/man/man1/ledger.1.gz.gz': No such file or directory
builder for ‘/nix/store/ayhif4mj1zmvx6hij1nc79baas791gji-ledger-env-0.drv’ failed with exit code 1
error: build of ‘/nix/store/ayhif4mj1zmvx6hij1nc79baas791gji-ledger-env-0.drv’ failed
~~~~

**Comment by peti** [comment]
This is what git bisect had to say:

    git bisect start
    # good: [e17b483669535d60d802cc979cad5e463e8ea114] glslang, spirv-tools, vulkan-loader: add metainformation
    git bisect good e17b483669535d60d802cc979cad5e463e8ea114
    # bad: [3aca77a7f24f8c4e11dc4ef2a9a596e4d84b774d] universal-ctags: 2016-12-17 -> 2017-01-08
    git bisect bad 3aca77a7f24f8c4e11dc4ef2a9a596e4d84b774d
    # bad: [674a2077dd10600e2f56c0824a0d0a0f5456e0ec] r-modules: fix rJava package
    git bisect bad 674a2077dd10600e2f56c0824a0d0a0f5456e0ec
    # good: [1f6bb81b06a0e5511153404ffd68ac5acc636cd3] Merge pull request #21679 from volth/chromium-command-line-args
    git bisect good 1f6bb81b06a0e5511153404ffd68ac5acc636cd3
    # good: [99c8e8e71f734ebc48ac6d3e8a6ac3e760ca7529] Merge pull request #21711 from mimadrid/fix/picard
    git bisect good 99c8e8e71f734ebc48ac6d3e8a6ac3e760ca7529
    # bad: [d442a0ffc0ad7e33fa0fddaf0365caf80193a224] wine*: fixup build by using older flex
    git bisect bad d442a0ffc0ad7e33fa0fddaf0365caf80193a224
    # good: [ea7b252c9ae0117b8f150950d730a7445d3f5e2d] Merge branch 'master' into staging
    git bisect good ea7b252c9ae0117b8f150950d730a7445d3f5e2d
    # bad: [f803270b7e00fa7124282809838d5652083b6aad] bash: switch the default 4.3 -> 4.4
    git bisect bad f803270b7e00fa7124282809838d5652083b6aad
    # good: [be489cf48ca25a2e8349ff2dcce82a2738e17290] gnused: 4.2.2 -> 4.3
    git bisect good be489cf48ca25a2e8349ff2dcce82a2738e17290
    # good: [6f2840c158e93d4d40bd6557078c2f539cb39cbb] Merge #21661: coreutils: build with xattr support
    git bisect good 6f2840c158e93d4d40bd6557078c2f539cb39cbb
    # good: [57fc4d21b717410d0c044609e3182a0df96acfa8] bash-4.4: p0 -> p5 + a security patch from Gentoo
    git bisect good 57fc4d21b717410d0c044609e3182a0df96acfa8
    # first bad commit: [f803270b7e00fa7124282809838d5652083b6aad] bash: switch the default 4.3 -> 4.4

f803270b7e00fa7124282809838d5652083b6aad is the first bad commit
Author: Vladimír Čunát <vcunat@gmail.com>
Date:   Thu Jan 5 01:07:36 2017 +0100

    bash: switch the default 4.3 -> 4.4
    
    ... and remove the now-unused 4.3 expression.

**Comment by vcunat** [comment]
Reading the compression hook, I can't see how it could ever work in this case.

**Comment by vcunat** [comment]
There aren't many of those, right?  We could just do `dontGzipMan = true;` as a quick work-around.

**Comment by ttuegel** [comment]
The root cause of this is that `GLOBIGNORE` does not work the way it sounds. One way to fix this would be to forget about setting `GLOBIGNORE` in `compress-man-pages.sh` and instead test each candidate filename and skip it if it's already compressed.

**Comment by peti** [comment]
Is anyone working on fixing this issue?

**Comment by Mic92** [comment]
@peti I made an attempt.

**Comment by peti** [comment]
Thank you very much for your efforts, @vcunat. ❤️

**Comment by vcunat** [comment]
:-)  In 17.03 now as well.
