### ISSUE TITLE
Migrate AsciiDoc to TeXLive, mark Tetex as broken

### ISSUE THREAD

**Issue by langston-barrett** [NixOS/nixpkgs#21770]
## Issue description
The source archive URL for tetex [is broken](http://downforeveryoneorjustme.com/cam.ctan.org). In fact, the whole subdomain is. Here's a build log:
```
code/nixpkgs > nix-build -A tetex
these derivations will be built:
  /nix/store/dn0a380kgqs23kbfd56dqqm93bwxyppv-tetex-src-3.0.tar.gz.drv
  /nix/store/r2sykvgi6zy3hb35ri9k9a634adbknfp-tetex-texmf-3.0.tar.gz.drv
  /nix/store/ip8ixqwr0pyfdhkgnls4csc35dmmbzrn-tetex-3.0.drv
building path(s) ‘/nix/store/bpv21kakgqx17va7ajc6hnbqv7nlld34-tetex-src-3.0.tar.gz’
building path(s) ‘/nix/store/ajq6rxxcjqzryn355py4gpvcvcx5fvj2-tetex-texmf-3.0.tar.gz’

trying ftp://cam.ctan.org/tex-archive/systems/unix/teTeX/current/distrib/tetex-texmf-3.0.tar.gz

trying ftp://cam.ctan.org/tex-archive/systems/unix/teTeX/current/distrib/tetex-src-3.0.tar.gz
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (6) Couldn't resolve host 'cam.ctan.org'
error: cannot download tetex-texmf-3.0.tar.gz from any mirror
builder for ‘/nix/store/r2sykvgi6zy3hb35ri9k9a634adbknfp-tetex-texmf-3.0.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/ip8ixqwr0pyfdhkgnls4csc35dmmbzrn-tetex-3.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ip8ixqwr0pyfdhkgnls4csc35dmmbzrn-tetex-3.0.drv’ failed
```

### Steps to reproduce
```
nix-build -A tetex
```

## Technical details
* System: 17.03pre98383.7ee897a (Gorilla)
* Nix version: nix-env (Nix) 1.11.5

**Comment by siddharthist** [comment]
This might have something to do with the fact that [the package is unsupported since 2006](https://www.tug.org/teTeX/).
>  I (Thomas Esser) have decided not to make new releases of teTeX any more (May 2006). The information below might get out of date as time goes by. I suggest anybody interested in teTeX to join the TeX Live project.

**Comment by siddharthist** [comment]
All three canonical download links are down:
    ftp://cam.ctan.org/tex-archive/systems/unix/teTeX/current/distrib/ (UK)
    ftp://dante.ctan.org/tex-archive/systems/unix/teTeX/current/distrib/ (GER)
    ftp://tug.ctan.org/tex-archive/systems/unix/teTeX/current/distrib/ (USA)

**Comment by Mic92** [comment]
we removed tetex actually in unstable

**Comment by vcunat** [comment]
We no longer build it on Hydra since 179218252, but I can still see it on master.

Still, is there a reason to have the old tetex?  I haven't heard of anyone wanting it recently, except by mistake.

**Comment by siddharthist** [comment]
It seems to be a dependency of a few packages https://github.com/NixOS/nixpkgs/search?p=1&q=tetex&utf8=%E2%9C%93

**Comment by vcunat** [comment]
They can almost certainly be migrated.

**Comment by siddharthist** [comment]
@vcunat Migrated to what? If you outline the process, I'm happy to make a change.

**Comment by vcunat** [comment]
To `texlive.*`.  There are some examples in nixpkgs, e.g. `git grep 'inherit (texlive)'`, or  `texlive.combined.scheme-small` might be enough in some cases. [texlive docs](http://nixos.org/nixpkgs/manual/#sec-language-texlive)

**Comment by siddharthist** [comment]
See discussion on the above PR. The only thing left is to migrate `asciidoc` and then mark tetex as broken/remove it.

**Comment by veprbl** [comment]
This appears to be resolved.
