### ISSUE TITLE
github-runner 404

### ISSUE THREAD

**Issue by DMaxter** [NixOS/nixpkgs#217721]
### Describe the bug
I'm trying to add the `github-runner` service in my machine, but when I do `nixos-rebuild switch` it gives me a 404 executing the preaction.
At first, it gave me a timeout, so I have defined my own timeout and now it gives a 404, since it is using an endpoint that doesn't exist

### Steps To Reproduce
1. Use the `unstable` channel
2. Add
```nix
  services = {
    # GitHub Runner
    github-runner = {
      enable = true;
      name = "RUNNER NAME";
      url = "URL TO REPO";
      tokenFile = "THE FILE WITH THE TOKEN";
      serviceOverrides.TimeoutSec = 900;
    };
```
3. `nixos-rebuild switch`

### Expected behavior
Runner get registered

### Screenshots
![image](https://user-images.githubusercontent.com/35278584/220710098-a8631d4d-1405-4cc5-93f9-612c064ac9e6.png)

### Notify maintainers

@veehaitch 
@newAM 
@kfollesdal 
@aanderse
@zimbatm

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85, NixOS, 23.05 (Stoat), 23.05pre456591.5a5adc2ad70`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"home-manager-22.05.tar.gz, nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by DMaxter** [comment]
- I am on the unstable [`5a5adc2`](https://github.com/NixOS/nixpkgs/commit/5a5adc2ad7009851d7d0fc26311e42a93b171d2e)
- This is not for an enterprise setup behind a proxy, it is for a VM I have

**Comment by newAM** [comment]
My bad, I didn't read enough to see that you got a response.  My proxy question is irrelevant.

Both our unstable versions include #217350.

Did you register with a runner token for an API token?

**Comment by DMaxter** [comment]
I tried with a runner token, the one it gives me at `<repo>/settings/actions/runners`

**Comment by Profpatsch** [comment]
We had the same problem, the fix for this is to use a fine-grained Personal Access Token instead of the runner token.

I have a PR that improves the documentation to make that clear: https://github.com/NixOS/nixpkgs/pull/217827

**Comment by DMaxter** [comment]
Thanks, it helped

I created a fine-grained PAT with read/write access to administration in repo
