### ISSUE TITLE
Helix additional language config fails because it cannot write to nix store

### ISSUE THREAD

**Issue by aldafu** [NixOS/nixpkgs#217860]
### Describe the bug
Helix allows to have a local configuration that adds support for other languages that are then highlighted based on that custom language configuration, see here for details: https://docs.helix-editor.com/languages.html

Once configured it is needed to "fetch" and "build" this configuration by running helix. Helix will then try to create a directory and generate some files, but that fails since it is not allowed to write to root owned /nix/store.

The error message is:
```shell
» hx --grammar fetch
Fetching 1 grammars
1 grammars failed to fetch
	Failure 1/1: Could not create grammar directory "/nix/store/py9sm09af0bj67jlrnlz2jwcsgkl5qag-helix-22.12/lib/runtime/grammars/sources/<actual-languagename-here>"
```

### Steps To Reproduce
1. Write/have tree-sitter grammar for additional language
2. hx --grammar fetch

### Expected behavior
Helix should work for custom languages that are added in the local configuration and be able to "fetch" and "build" these.

### Additional context
Happy to provide if needed.

### Notify maintainers
@danth @yusdacra @mweinelt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.2`
 - channels(<user-redacted>): `"nixpkgs, nixpkgs-22.11-darwin-22.11-darwin"`
 - channels(root): `""`
 - nixpkgs: `/Users/<user-redacted>/.nix-defexpr/channels/nixpkgs`
```

**Comment by gruhn** [comment]
same here

**Comment by n8henrie** [comment]
`hx --grammar fetch` is working for me on x86_64-linux and aarch64-darwin; it looks like a fix was merged in the issues you linked. @aldafu can you confirm and if so close?

**Comment by ofalvai** [comment]
I also think this can be closed. The latest docs say that `~/.config/helix/runtime` has a higher priority than `$HELIX_DEFAULT_RUNTIME` (which the derivation sets correctly)

https://docs.helix-editor.com/building-from-source.html#multiple-runtime-directories
