### ISSUE TITLE
nixpkgs-review shows error on master branch, possibly related to `emscriptenPackages.json_c`

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nixpkgs#217889]
### Describe the bug

nixpkgs-review reports failure on the master branch, at least since ac573e5046f1e2ff60e4260771a88b9862fa7148.

The trace information seems to point to a package named `emscripten-json-c`, which is probably `emscriptenPackages.json_c`.

```
$ nix-env --option system x86_64-linux -f /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs -qaP --xml --out-path --show-trace
error: cannot coerce a set to a string

       at /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs/pkgs/top-level/emscripten-packages.nix:145:7:

          144|       # we need to reset this setting!
          145|       env = (old.env or { }) // { NIX_CFLAGS_COMPILE = ""; };
             |       ^
          146|       dontStrip = true;

       … while evaluating the attribute 'env' of the derivation 'emscripten-zlib-1.2.13'

       at /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:293:7:

          292|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          293|       name =
             |       ^
          294|         let

       … while evaluating the attribute 'propagatedBuildInputs' of the derivation 'emscripten-json-c-0.16'
```

### Steps To Reproduce
1.  Fetch the master branch from remote.
2.  Run
    ```sh
    git switch -d ac573e5046f1e2ff60e4260771a88b9862fa7148
    nixpkgs-review rev HEAD
    ```
3.  See error.

### Expected behavior
`nixpkgs-review` passes on master.

### Additional context
<details>
<summary>Full error message</summary>
<pre>
nixpkgs_timeshift (ac573e5) [$] took 43s
❯ nix run nixpkgs-local#nixpkgs-review rev HEAD
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
$ git worktree add /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs ac573e5046f1e2ff60e4260771a88b9862fa7148
Preparing worktree (detached HEAD ac573e5046f)
Updating files: 100% (33717/33717), done.
HEAD is now at ac573e5046f Merge pull request #217865 from ncfavier/doc-ignore-result
$ nix-env --option system x86_64-linux -f /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs -qaP --xml --out-path --show-trace
error: cannot coerce a set to a string

       at /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs/pkgs/top-level/emscripten-packages.nix:145:7:

          144|       # we need to reset this setting!
          145|       env = (old.env or { }) // { NIX_CFLAGS_COMPILE = ""; };
             |       ^
          146|       dontStrip = true;

       … while evaluating the attribute 'env' of the derivation 'emscripten-zlib-1.2.13'

       at /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:293:7:

          292|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          293|       name =
             |       ^
          294|         let

       … while evaluating the attribute 'propagatedBuildInputs' of the derivation 'emscripten-json-c-0.16'

       at /home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs/pkgs/stdenv/generic/make-derivation.nix:293:7:

          292|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          293|       name =
             |       ^
          294|         let

       … while querying the derivation named 'emscripten-json-c-0.16'
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/cli/__init__.py", line 294, in main
    return cast(str, args.func(args))
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/cli/rev.py", line 12, in rev_command
    return review_local_revision(f"rev-{commit}", args, commit)
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 474, in review_local_revision
    review.review_commit(builddir.path, args.branch, commit, staged)
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 250, in review_commit
    self.start_review(self.build_commit(branch_rev, reviewed_commit, staged), path)
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 145, in build_commit
    base_packages = list_packages(str(self.worktree_dir()), self.system)
  File "/nix/store/zhw2zm6lff1zv7x2v6wik0jcq82kghmf-nixpkgs-review-2.7.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 317, in list_packages
    subprocess.run(cmd, stdout=tmp, check=True)
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-env', '--option', 'system', 'x86_64-linux', '-f', '/home/shamrock/.cache/nixpkgs-review/rev-ac573e5046f1e2ff60e4260771a88b9862fa7148/nixpkgs', '-qaP', '--xml', '--out-path', '--show-trace']' returned non-zero exit status 1.
</pre>
</details>

### Notify maintainers
Emscripten toolchain contributor: @qknight
json-c maintainer: @lovek323

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.86, NixOS, 22.11 (Raccoon), 22.11.20230110.54644f4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/store/3y1qwszq3vpyixr0jcisyind3wdgcbdb-source`
```

**Comment by davidak** [comment]
This also affects staging branch.

```
[davidak@gaming:~/code/nixpkgs]$ nix-build https://github.com/NixOS/nixpkgs/archive/refs/heads/staging.zip -A emscriptenPackages.json_c
error: cannot coerce a set to a string

       at /nix/store/vs7phvy95y2gac3m6f4mkjc1qvrynbaq-source/pkgs/top-level/emscripten-packages.nix:145:7:

          144|       # we need to reset this setting!
          145|       env = (old.env or { }) // { NIX_CFLAGS_COMPILE = ""; };
             |       ^
          146|       dontStrip = true;
```

**Comment by alyssais** [comment]
I think this was fixed in https://github.com/NixOS/nixpkgs/pull/217870, which should make it into staging very shortly.

**Comment by alyssais** [comment]
Now fixed in staging too.
