### ISSUE TITLE
purescript-0.10.5 needs newer bower-json

### ISSUE THREAD

**Issue by comonoid** [NixOS/nixpkgs#21784]
## Issue description

purescript-0.10.5 is now dependent on bower-json >=1.0.0.1 && <1.1.
Would you please upgrade dependences?

### Steps to reproduce

Just try to install purescript-0.10.5

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

17.03pre98383.7ee897a (Gorilla)
17.03pre98682.f673243 (Gorilla)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.5

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"17.03pre98383.7ee897a"
"17.03pre98682.f673243"

**Comment by domenkozar** [comment]
use `bower-json_1_0_0_1`

**Comment by comonoid** [comment]
How? I can install it, but it doesn't help —
when purescript builds, it can't see newer bower-json.
We need some changes in purescript package.

**Comment by sjmackenzie** [comment]
Yes, I have the same issue.

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/21938

**Comment by comonoid** [comment]
Now (in 17.03pre101267.a9584c9) —

Configuring purescript-0.10.7...
Setup: Encountered missing dependencies:
aeson >=0.8 && <1.0,
http-client >=0.4.30 && <0.5,
pipes >=4.0.0 && <4.3.0,
websockets ==0.9.*

Is it worth to raise an issue?

Similar things with idris:
Setup: Encountered missing dependencies:
ieee754 ==0.7.*, safe ==0.3.9
