### ISSUE TITLE
gnome-settings-daemon is not on the PATH

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nixpkgs#21782]
## Issue description
I would like to use `gnome-setings-daemon` under i3. I have the full gnome environment installed, but when I run `gnome-settings-daemon`, I get a `command not found` error. Why is this binary not on the PATH? In other distributions it is on the non-standard path `/usr/libexec/gnome-settings-daemon`, might this have something to do with it?

### Steps to reproduce
Install `gnome-settings-daemon` and try running it from a terminal. 

## Technical details

* System: 17.03pre98383.7ee897a (Gorilla)

**Comment by rvl** [comment]
I use the xmonad window manager, and the way I get `gnome-settings-daemon` to start is by selecting the "gnome3 + xmonad" session in slim display manager.

You may be able to achieve a similar result with i3.

I have these settings:

```
services.xserver = {
  windowManager.xmonad.enable = true;
  windowManager.default = "xmonad";
  desktopManager.default = "none";
  desktopManager.gnome3.enable = true;
};
```

At login time, I press <kbd>F1</kbd> to cycle through sessions and make sure "gnome3 + xmonad" is selected.

Furthermore, in my `xmonad.hs` I must make a DBus call to register with the GNOME Session Manager. i3 may already do this however.

**Comment by siddharthist** [comment]
@rvl Thank you for the tips! I've figured out a good workflow with xfce + i3, but I appreciate your tips. 

I'll leave this open since the original question is still valid, although my use case has been satisfied.

**Comment by rvl** [comment]
If you need `gnome-settings-daemon`, setup your xsession startup script with nix (`pkgs.writeScriptBin`) and refer to it as `${pkgs.gnome3.gnome_settings_daemon}/libexec/gnome-settings-daemon`.

I would consider `gnome-settings-daemon` to be an internal component of GNOME, not a user program.

**Comment by siddharthist** [comment]
@rvl Fair enough!

**Comment by layus** [comment]
@rvl Can you confirm that "gnome3 + xmonad" works for you ? For me "gnome3 + i3" starts gnome3 with gnome-shell, and i3 seems to be supersede or even killed by gnome-shell. Also, gnome3 and i3 both define waitPID, so only gnome3 is waited for. the same occurs for xmodad (I just checked), so I guess you must log out using gnome-session-quit, right ?

All in all, I think our "xsession" script does not handle custom "<session-manager>+<window-mananger>" as well as it looks.

**Comment by rvl** [comment]
Hi @layus, Yes "gnome3 + xmonad" session does work and I'm using it now (nixos-unstable 4450327c062a41f7df2f6756057df4ebb6548011). Is your i3 registering with the gnome session manager?
