### ISSUE TITLE
New package: sbt-extras

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#21783]
I'm told a lot of people favor Paul Phillips' SBT wrapper https://github.com/paulp/sbt-extras over vanilla SBT. We probably ought to have a package for it.

**Comment by copumpkin** [comment]
Minus the parts where it auto-downloads sbt for you, I expect 😄

**Comment by chris-martin** [comment]
Mmm, I don't know. Isn't it kind of important to be able to auto-download the appropriate version of sbt?

**Comment by copumpkin** [comment]
Maybe? Seems hard to keep it Nix-flavored though, given that it wants to retrieve unhashed versions from the outside. I guess we could either patch it to call out to nix to download scala and sbt, or we could leave it alone and users can decide whether they care about Nix-like behavior here.
