### ISSUE TITLE
Monophony

### ISSUE THREAD

**Issue by vagabondsajib** [NixOS/nixpkgs#217848]
**Linux app for streaming music from YouTube.**

**Metadata**

* homepage URL: https://gitlab.com/zehkira/monophony
* source URL: https://gitlab.com/zehkira/monophony
* license: mit
* platforms: linux

**Comment by Henry-Hiles** [comment]
I'd be interested in doing this if its not too hard, I'll look into it.

**Comment by Henry-Hiles** [comment]
The package is almost done, had some complications including unpackaged dependencies, but it should be good to go within the next few days.

**Comment by Henry-Hiles** [comment]
Just waiting for a merge now.
