### ISSUE TITLE
how should a persistent folder for a package be created?

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#21793]
## Issue description

If I have a server (this server has a nix package) that allows users to upload files, where should I be storing these files? somewhere in /var/lib/myserver? and should the server be responsible for creating this folder or should the package create it?

**Comment by 7c6f434c** [comment]
I guess something in `/var/` sounds reasonable; the server Nix package
cannot create anything writeable on its own; wrapping the server so it
creates the directory on launch is an option, and the cleanest option is
creating a package from server and also creating a NixOS module for 
starting the server, which would create the directory.

**Comment by nhooyr** [comment]
Alright, thanks!
