### ISSUE TITLE
Webapp Manager

### ISSUE THREAD

**Issue by vagabondsajib** [NixOS/nixpkgs#217927]
**Run websites as if they were apps.**

**Metadata**

* homepage URL: https://github.com/linuxmint/webapp-manager
* source URL: https://github.com/linuxmint/webapp-manager
* license: gpl3
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/212089

**Comment by das-g** [comment]
Closing as duplicate of #212089.
