### ISSUE TITLE
hplipWithPlugin: hp-setup and hp-plugin broken

### ISSUE THREAD

**Issue by listx** [NixOS/nixpkgs#21796]
## Issue description

Following https://nixos.org/wiki/Printers, I put 

    services.printing = {
      enable = true;
      drivers = [ pkgs.hplipWithPlugin ];
    };

in my configuration.nix. (My printer is not supported by Gutenprint and I must use the proprietary plugin). After a `sudo nixos-rebuild switch`, I first did `hp-setup`, which gave me this:

```
 > hp-setup                 

HP Linux Imaging and Printing System (ver. 3.16.5)
Printer/Fax Setup Utility ver. 9.0

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Found device: hp:/net/HP_LaserJet_Pro_MFP_M125nw?ip=192.168.0.2

HP Linux Imaging and Printing System (ver. 3.16.5)
Plugin Download and Install Utility ver. 2.1

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.


HP Linux Imaging and Printing System (ver. 3.16.5)
Plugin Download and Install Utility ver. 2.1

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Checking for network connection...                                                                                                                                                Downloading plug-in from: 
sh: lsb_release: command not found
warning:  distro is not found in AUTH_TYPES                                                                                                                                    Receiving digital keys: /home/l/.nix-profile/bin/gpg --homedir /home/l/.hplip/.gnupg --no-permission-warning --keyserver pgp.mit.edu --recv-keys 0x4ABA2F66DBD5A95894910E0673D770CDA59047B9                                                                                                                                                                             Creating directory plugin_tmp
Verifying archive integrity... All good.
Uncompressing HPLIP 3.16.5 Plugin Self Extracting Archive................................................
/home/l/.hplip/hplip-3.16.5-plugin.run: ./hplip-plugin-install: /bin/bash: bad interpreter: No such file or directory
error: Python gobject/dbus may be not installed                                                                                                                                   error: Plug-in install failed.

Done.
error:  The device you are trying to setup requires a binary plug-in. Some functionalities may not work as expected without plug-ins.  Please run 'hp-plugin' as normal user to install plug-ins.   Visit  http://hplipopensource.com  for more infomation. 

Done.
```

I then tried running just `hp-plugin`, which fails like this:

```
 > hp-plugin

HP Linux Imaging and Printing System (ver. 3.16.5)
Plugin Download and Install Utility ver. 2.1

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.


HP Linux Imaging and Printing System (ver. 3.16.5)
Plugin Download and Install Utility ver. 2.1

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Checking for network connection...                                                                                                                                                Downloading plug-in from: 
sh: lsb_release: command not found
warning:  distro is not found in AUTH_TYPES                                                                                                                                    Receiving digital keys: /home/l/.nix-profile/bin/gpg --homedir /home/l/.hplip/.gnupg --no-permission-warning --keyserver pgp.mit.edu --recv-keys 0x4ABA2F66DBD5A95894910E0673D770CDA59047B9                                                                                                                                                                             Creating directory plugin_tmp
Verifying archive integrity... All good.
Uncompressing HPLIP 3.16.5 Plugin Self Extracting Archive................................................
/home/l/.hplip/hplip-3.16.5-plugin.run: ./hplip-plugin-install: /bin/bash: bad interpreter: No such file or directory
error: Python gobject/dbus may be not installed                                                                                                                                   error: Plug-in install failed.

Done.
```

### Steps to reproduce

Install the `hplipWithPlugin` package (either with `nix-env -iA` or by editing configuration.nix as described above).
Run `hp-plugin`.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

16.09.1445.e9a8853 (Flounder)

* Nix version: (run `nix-env --version`)

nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

"16.09.1445.e9a8853"

**Comment by listx** [comment]
Is there anything I can do to try to resolve this issue? One big problem appears to be how the traditional paths like /bin/bash are not sed-replaced (according to the error messages I posted). I am not sure why this is the case, as the hplip derivation (https://github.com/NixOS/nixpkgs/blob/beef906d2e0494ac5750e775504d98e34a2dfd4b/pkgs/misc/drivers/hplip/default.nix#L78) appears to perform sed replacements of hardcoded paths to bash, etc. I am not familiar enough with the Nix expression language to spot an obvious problem.

**Comment by CMCDragonkai** [comment]
When using `hplibWithPlugin`, I don't actually see `hp-setup` command available. Does it come from somewhere else?

**Comment by WhittlesJr** [comment]
You have to run `nix run nixpkgs.hplipWithPlugin -c hp-setup`

**Comment by louwers** [comment]
I have a different problem:

```
[bart@nixos:~]$ nix run nixpkgs.hplipWithPlugin -c sudo hp-setup
[3 built, 10 copied (26.3 MiB), 24.8 MiB DL]

HP Linux Imaging and Printing System (ver. 3.19.12)
Printer/Fax Setup Utility ver. 9.0

Copyright (c) 2001-18 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Traceback (most recent call last):
  File "/nix/store/9daiqx258c84wlvhwqzrihhp4ppyassk-hplip-3.19.12/share/hplip/setup.py", line 314, in <module>
    ui = import_module(ui_package + ".setupdialog")
  File "/nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/9daiqx258c84wlvhwqzrihhp4ppyassk-hplip-3.19.12/share/hplip/ui5/setupdialog.py", line 31, in <module>
    from base import device, utils, models, pkit
  File "/nix/store/9daiqx258c84wlvhwqzrihhp4ppyassk-hplip-3.19.12/share/hplip/base/pkit.py", line 38, in <module>
    from gi import _gobject as gobject
ModuleNotFoundError: No module named 'gi'
```

**Comment by flokli** [comment]
At least on NixOS unstable, I didn't run into the `ModuleNotFoundError: No module named 'gi'` error.

Instead, it crashes after selecting the printer with a Python stacktrace:

```
Searching... (bus=net, timeout=5, ttl=4, search=(None) desc=0, method=slp)
Traceback (most recent call last):
  File "/nix/store/8lcsd6wk1myxxm1b39wvz3c7wk640ad6-hplip-3.20.5/share/hplip/ui5/setupdialog.py", line 1305, in NextButton_clicked
    self.showAddPrinterPage()
  File "/nix/store/8lcsd6wk1myxxm1b39wvz3c7wk640ad6-hplip-3.20.5/share/hplip/ui5/setupdialog.py", line 711, in showAddPrinterPage
    self.findPrinterPPD()
  File "/nix/store/8lcsd6wk1myxxm1b39wvz3c7wk640ad6-hplip-3.20.5/share/hplip/ui5/setupdialog.py", line 789, in findPrinterPPD
    self.ppds = cups.getSystemPPDs()
  File "/nix/store/8lcsd6wk1myxxm1b39wvz3c7wk640ad6-hplip-3.20.5/share/hplip/prnt/cups.py", line 329, in getSystemPPDs
    path = os.path.join(cups_ppd_path, ppd)
  File "/nix/store/7q4crsd8kvmma32ff2xw4w9ydj5k26cy-python3-3.8.3/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[1]    25194 abort (core dumped)  hp-setup
```

**Comment by Mesabloo** [comment]
I can also report the same problem as @louwers on my machine, on NixOS 20.03.

```
$ nix run nixpkgs.hplipWithPlugin -c sudo hp-setup

HP Linux Imaging and Printing System (ver. 3.19.12)
Printer/Fax Setup Utility ver. 9.0

Copyright (c) 2001-18 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

Traceback (most recent call last):
  File "/nix/store/5bf1k5qambnlkbsb7zq9awx217vkg950-hplip-3.19.12/share/hplip/setup.py", line 314, in <module>
    ui = import_module(ui_package + ".setupdialog")
  File "/nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/nix/store/5bf1k5qambnlkbsb7zq9awx217vkg950-hplip-3.19.12/share/hplip/ui5/setupdialog.py", line 31, in <module>
    from base import device, utils, models, pkit
  File "/nix/store/5bf1k5qambnlkbsb7zq9awx217vkg950-hplip-3.19.12/share/hplip/base/pkit.py", line 38, in <module>
    from gi import _gobject as gobject
ModuleNotFoundError: No module named 'gi'
```

--------

`nix-shell -p nix-info --run "nix-info -m"`
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.51, NixOS, 20.03.2593.aaa66d8d887 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(mesabloo): `"home-manager, nixos-unstable-20.09pre235212.a5cc7d31977"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by v0d1ch** [comment]
I tried building the latest master version of hplip (6de4b96228e) and replaced the hplip version to the latest one and got the gui to start (gui also starts with 3.20.5 version btw). 
Problem is you can't select ppd file, the console shows _Empty file passed to function_ 

```
HP Linux Imaging and Printing System (ver. 3.20.6)
Printer/Fax Setup Utility ver. 9.0

Copyright (c) 2001-18 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Searching... (bus=usb, search=(None), desc=0)
error: No PPD found for model laserjet_mfp_m28-m31 using old algorithm.
error: No appropriate print PPD file found for model hp_laserjet_mfp_m28-m31
Empty filename passed to function
```

**Comment by listx** [comment]
I'm happy to report that I tried out the instructions at https://nixos.wiki/wiki/Printing and was able to successfully print a CUPS test page out of my HP printer. Commit is https://github.com/listx/syscfg/commit/bb5ec9591804f5bf07187bbfece738c906b54fe4.

When I originally filed this issue I was just trying to get my HP printer to print *anything*. Now that I can print from CUPS a test page as well as just print in general from other applications, I'm satisfied.

According to https://developers.hp.com/hp-linux-imaging-and-printing/install/manual/hp_setup the whole point of `hp-setup` is to just add the printer to the system so that other apps can use it to print. As this has already been achieved through the CUPS web UI, I think this issue can be closed. FWIW the stacktrace that was posted in https://github.com/NixOS/nixpkgs/issues/21796#issuecomment-661797497 was also observed on my end when I ran `nix run nixpkgs.hplipWithPlugin -c sudo hp-setup` but that probably requires patching the upstream Python sources.

**Comment by khumba** [comment]
hplipWithPlugin's hp-plugin appears broken in 20.09 due to missing Python deps:

    Checking for network connection...
    Downloading plug-in from: 
    Traceback (most recent call last):
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/base/password.py", line 85, in get_distro_name
        os_name = platform.dist()[0]
    AttributeError: module 'platform' has no attribute 'dist'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/ui5/plugindialog.py", line 248, in NextButton_clicked
        status, download_plugin_file, error_str = self.pluginObj.download(self.plugin_path,self.plugin_download_callback)
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/installer/pluginhandler.py", line 254, in download
        core = core_install.CoreInstall()
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/installer/core_install.py", line 240, in __init__
        self.passwordObj = password.Password(ui_mode)
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/base/password.py", line 118, in __init__
        self.__readAuthType()  # self.__authType
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/base/password.py", line 141, in __readAuthType
        distro_name = get_distro_name().lower().replace(" ","")
      File "/nix/store/d0qmxn3ib3h4wvknkiaj5ibhinxml23w-hplip-3.20.5/share/hplip/base/password.py", line 87, in get_distro_name
        import distro
    ModuleNotFoundError: No module named 'distro'
    Aborted (core dumped)

**Comment by doronbehar** [comment]
@khumba this error appears when you launch a certain executable from `hplip`?

**Comment by khumba** [comment]
Oops, that was when I tried to run `hp-plugin` from `hplipWithPlugin`, but I realise now that `hp-plugin` (which downloads and installs the proprietary plugin from HP servers) isn't necessary when using `hplipWithPlugin`.

That said, I experience this when I try to run `hp-setup`:

    $ hp-setup
    
    HP Linux Imaging and Printing System (ver. 3.20.5)
    Printer/Fax Setup Utility ver. 9.0
    
    Copyright (c) 2001-18 HP Development Company, LP
    This software comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to distribute it
    under certain conditions. See COPYING file for more details.
    
    Searching... (bus=usb, search=(None), desc=0)
    Traceback (most recent call last):
      File "/nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/share/hplip/ui5/setupdialog.py", line 1305, in NextButton_clicked
        self.showAddPrinterPage()
      File "/nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/share/hplip/ui5/setupdialog.py", line 711, in showAddPrinterPage
        self.findPrinterPPD()
      File "/nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/share/hplip/ui5/setupdialog.py", line 789, in findPrinterPPD
        self.ppds = cups.getSystemPPDs()
      File "/nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/share/hplip/prnt/cups.py", line 329, in getSystemPPDs
        path = os.path.join(cups_ppd_path, ppd)
      File "/nix/store/v72cj06nk69cynckz2s12rhar25k1h7v-python3-3.8.5/lib/python3.8/posixpath.py", line 76, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    Aborted (core dumped)

The `getSystemPPDs()` function in `cups.py` is expecting the `getPPDPath()` function from the same file to return non-null in this case, but `prop.ppd_search_path` is only set to a bunch of FHS paths, and of course none of these exist:

    $ grep -rn ppd_search_path /nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/
    /nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/share/hplip/prnt/cups.py:212:    search_paths = prop.ppd_search_path.split(';') + addtional_paths
    /nix/store/3qkd2cfycava3l9rpkyyrz8shckcli2j-hplip-3.20.5/share/hplip/base/g.py:286:prop.ppd_search_path = '/usr/share;/usr/local/share;/usr/lib;/usr/local/lib;/usr/libexec;/opt;/usr/lib64'

**Comment by doronbehar** [comment]
I see now.

Unfortunately, upstream hardcodes hundreds of absolute paths such as /usr/share and /usr/lib and /usr/include.

Even now we replace a lot of them:

https://github.com/NixOS/nixpkgs/blob/f6e519f39e4d6ee694c2a3d5de8f3f263c57980b/pkgs/misc/drivers/hplip/default.nix#L97-L112

But I guess that's not enough. I think we should have a more versatile test / fix for this issue, and ideally talk about this with upstream.. It's also hard to distinguish when inspecting the tarball, which absolute paths are not used eventually and which are left in $out after install, since the build supports some configure flags which we do use:

https://github.com/NixOS/nixpkgs/blob/f6e519f39e4d6ee694c2a3d5de8f3f263c57980b/pkgs/misc/drivers/hplip/default.nix#L114-L126

**Comment by khumba** [comment]
That's a lot of paths being patched!  If I also patch the `prop.ppd_search_path` definition to include `/var/lib/cups/path/share` then that solves the crash for me, and I can add and use my printer.  I've opened a PR ^.

**Comment by doronbehar** [comment]
Resolved in https://github.com/NixOS/nixpkgs/pull/108830 .
