### ISSUE TITLE
Broadcom based Bluetooth does not work on Dell XPS 15 9550

### ISSUE THREAD

**Issue by spy-tech** [NixOS/nixpkgs#21797]
## Issue description
The manual solution for Ubuntu here should be adapted and automated such that it runs out of the box: http://askubuntu.com/questions/632336/bluetooth-broadcom-43142-isnt-working-on-ubuntu

```
# dmesg
[  947.674489] Bluetooth: hci0: BCM: chip id 102
[  947.690495] Bluetooth: hci0: BCM20703A1
[  947.691487] Bluetooth: hci0: BCM (001.001.005) build 0000
[  947.691533] bluetooth hci0: Direct firmware load for brcm/BCM-0a5c-6410.hcd failed with error -2
[  947.691534] Bluetooth: hci0: BCM: Patch brcm/BCM-0a5c-6410.hcd not found
```

### Steps to reproduce
See URL above

## Technical details
16.09

**Comment by Mic92** [comment]
You could adapt this project https://github.com/winterheart/broadcom-bt-firmware or this package https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bcm20702a1-firmware and create a new package in: `pkgs/os-specific/linux/firmware`
If the license is set to unfree, hydra won't build it automatically. That way license conditions would not be hurt. The resulting packages can be added to:

```
hardware = {
  firmware = [pkgs.<packagename>];
  enableAllFirmware = true;
}
```

It might also an option to add the package to `./nixos/modules/hardware/all-firmware.nix`. Then everybody using `enableAllFirmware` would automatically get it.
