### ISSUE TITLE
Blender is built without draco support

### ISSUE THREAD

**Issue by jansol** [NixOS/nixpkgs#217921]
### Describe the bug

Blender's glTF exporter supports compressing meshes with draco, but this is disabled at compile time due to `WITH_PYTHON_INSTALL=OFF`. With `WITH_PYTHON_INSTALL=ON`, the (vendored) draco library gets built and placed in `$out/share/blender/3.3/python/lib/python3.10/site-packages/libextern_draco.so`. Opening the glTF export dialog at run time however prints the following message to the console:

`ERROR: Draco mesh compression is not available because library could not be found at /nix/store/rimv365v1hlzb5lsjsbkgfh346w7l6na-blender-3.3.1/bin/3.3/python/lib/python3.10/site-packages/libextern_draco.so`

### Expected behavior
Compression options are available in the glTF exporter like on other platforms.

### Notify maintainers

@cillianderoiste @veprbl 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 23.05 (Stoat), 23.05.git.d0d55259081M`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by frostfyre** [comment]
This one just bit me too...
