### ISSUE TITLE
easyeffects: context connection failed

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#217972]
### Describe the bug

The program crashes. Maybe because i don't use PipeWire. Probably upstream has to make this situation better.

### Steps To Reproduce

```
[davidak@gaming:~/code/nixpkgs]$ nix run nixpkgs#easyeffects

(easyeffects:1152952): easyeffects-ERROR **: 06:48:57.879: 	pipe_manager.cpp:1457	context connection failed
Trace/breakpoint trap (core dumped)
```

```
[davidak@gaming:~/code/nixpkgs]$ nix run -f channel:nixos-unstable easyeffects

(easyeffects:1156381): easyeffects-ERROR **: 06:50:05.931: 	pipe_manager.cpp:1457	context connection failed
Trace/breakpoint trap (core dumped)
```

### Expected behavior
Error message instead of crash.

### Notify maintainers

@jtojnar

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12, NixOS, 22.11 (Raccoon), 22.11.2630.e6d5772f351`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by QuantMint** [comment]
Easyeffects doesn't support pulseaudio, this is not related to NixOS

**Comment by davidak** [comment]
>It is intentional.

>It seems not possible to solve this in the near future.

Source: https://github.com/wwmm/easyeffects/issues/1348
