### ISSUE TITLE
Package request: Taichi

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#218040]
**Project description**

Taichi is a domain-specific language embedded in Python that helps you easily write portable, high-performance parallel programs.

**Metadata**

* homepage URL: https://www.taichi-lang.org/
* source URL: https://github.com/taichi-dev/taichi
* license: Apache License 2.0
* platforms: I don’t know exactly

**Comment by SaltyKitkat** [comment]
Seems duplicate with #143181
