### ISSUE TITLE
liberation-fonts: broken hinting in 2.00 ?

### ISSUE THREAD

**Issue by volth** [NixOS/nixpkgs#21806]
## Issue description

With antialiasing turned off liberation fonts 2.00.1 (default in nixos) look weird, some lines have double width:

![screenshot_2017-01-11_13-28-39](https://cloud.githubusercontent.com/assets/508305/21851795/919b607c-d808-11e6-9bc6-32d017bf3cb2.png)
![screenshot_2017-01-11_13-48-59](https://cloud.githubusercontent.com/assets/508305/21851798/92b34b82-d808-11e6-941e-0e4769679d79.png)
![screenshot_2017-01-11_13-49-14](https://cloud.githubusercontent.com/assets/508305/21851800/948cd798-d808-11e6-9658-bc92a98dffb0.png)

liberation fonts 1.07.4 (default in Ubuntu, even in Ubuntu 17.04) do not have the problem

![screenshot_2017-01-11_13-50-30](https://cloud.githubusercontent.com/assets/508305/21851802/9645ae7a-d808-11e6-8a60-dfbd1881be75.png)
![screenshot_2017-01-11_13-51-11](https://cloud.githubusercontent.com/assets/508305/21851804/97abf238-d808-11e6-92cd-feec18b59ce0.png)
![screenshot_2017-01-11_13-51-35](https://cloud.githubusercontent.com/assets/508305/21851807/99116612-d808-11e6-8518-140fc224b2a6.png)

Wasn't it too early to upgrade to 2.00 ?

### Steps to reproduce

1. turn antialiasing off in desktop manager setting
2. ```pango-view   --font='Liberation Serif 12' --markup   --text 'abcdefghijklmnopqrstuvwxuzABCDEFGHIJKLMNOPQRSTUVWXUZ'```
3. ```pango-view   --font='Liberation Sans 12' --markup   --text 'abcdefghijklmnopqrstuvwxuzABCDEFGHIJKLMNOPQRSTUVWXUZ'```
4. ```pango-view   --font='Liberation Mono 12' --markup   --text 'abcdefghijklmnopqrstuvwxuzABCDEFGHIJKLMNOPQRSTUVWXUZ'```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03.git.d2d7740 (Gorilla)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.5  
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03.git.d2d7740f1bM"

**Comment by vcunat** [comment]
2.x is really a different font, as I understand it.
>  "On Jul 18, 2012, Liberation fonts 2.00.0 version is released based on croscore fonts to resolve long standing licensing problem and also get more coverage present in croscore fonts."

**Comment by volth** [comment]
Should we have both (1.07 and 2.00) in nixpkgs then ?
