### ISSUE TITLE
gnome.devhelp is empty

### ISSUE THREAD

**Issue by LoveIsGrief** [NixOS/nixpkgs#218091]
### Describe the bug

After installing `gnome.devhelp`, the UI is just empty.  https://github.com/NixOS/nixpkgs/issues/247#issuecomment-329415667 indicates that it's probably related to missing `.devhelp2` index files. They seem to be missing everywhere, including `glib`, so it's not possible to look up documentation for say [`g_build_filename`](https://docs.gtk.org/glib/func.build_filename.html).

### Steps To Reproduce
1. `nix-shell -p gnome.devhelp glib`
2. `devhelp`

Output:

```
** (process:2): WARNING **: 22:40:24.648: Failed to connect to bus: The given address is empty

** (WebKitWebProcess:2): WARNING **: 22:40:24.705: Can't connect to a11y bus: Error receiving data: Connection reset by peer
```

### Expected behavior

It should be possible to browse the documentation of at least `glib`.

### Screenshots

![empty window](https://user-images.githubusercontent.com/2829538/221299179-596673b1-b070-413d-b880-1eb93feb5f59.png)

### Additional context

-

### Notify maintainers

@jtojnar @bobby285271

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.93, NixOS, 22.11 (Raccoon), 22.11.2568.c43f676c938`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jtojnar** [comment]
Development documentation needs to be explicitly installed. One would either install it globally with a NixOS config:

```nix
{ pkgs }:
{
  {
    # Make sure devdoc outputs are installed.
  documentation = {
    dev.enable = true;
  };
  # Make sure legacy path is installed as well.
  environment.pathsToLink = [ "/share/gtk-doc" ];
  # Choose packages that you want to have development documentation available for.
  environment.systemPackages = [
    pkgs.glib
  ];
}
```

or run `devhelp` in `nix-shell` to get documentation for libraries your project uses.

**Comment by LoveIsGrief** [comment]
Hi @jtojnar , how do I do this in `nix-shell`? Is there something I have to pass to `mkShell`? I don't want to install dev documentation for all the packages I install on the system, only those specific to the current development environment (or only for specific packages if they're in my `configuration.nix`)

**Comment by jtojnar** [comment]
It would not install it for all packages on your system, only for those listed in `environment.systemPackages` and you typically would not add libraries there.

For shell, you will want to add something like the following to your `mkShell`.

```nix
env = {
  XDG_DATA_DIRS = lib.makeSearchPathOutput "devdoc" "share" [pkgs.glib pkgs.gtk4 pkgs.pango];
};
```

In the past, I vaguely recall the developer documentation sometime being picked up to `XDG_DATA_DIRS` by accident for libraries in `buildInputs` by some setup-hook but I do not think that happens any more so you are better of listing them explicitly.
