### ISSUE TITLE
autoreconf cannot find libtool out of /usr/bin

### ISSUE THREAD

**Issue by SchrodingerZhu** [NixOS/nixpkgs#218092]
### Describe the bug
As indicated in the title

![image](https://user-images.githubusercontent.com/20108837/221300141-e7069990-e68f-4518-a984-5d5072285411.png)

**Comment by symphorien** [comment]
You should not install compilation related tools from configuration.nix or with nix-env. All compilation adjacent tasks should be only handled with nix-shell (or nix develop).

**Comment by SchrodingerZhu** [comment]
I see. Adding the tool to a default.nix fixes the problem
