### ISSUE TITLE
Package Request: Jishaku

### ISSUE THREAD

**Issue by UnrealFar** [NixOS/nixpkgs#218189]
**Project description**

jishaku is an extension for bot developers that enables rapid prototyping, experimentation, and debugging of features for bots.

**Metadata**

* homepage URL: https://jishaku.readthedocs.io/
* source URL: https://github.com/Gorialis/jishaku
* license: mit
* platforms: unix, linux, darwin, windows

**Comment by itslychee** [comment]
See https://github.com/NixOS/nixpkgs/pull/287864

**Comment by itslychee** [comment]
The PR has been merged, closing
