### ISSUE TITLE
cjdns module doesnt support multiple networks

### ISSUE THREAD

**Issue by tohl** [NixOS/nixpkgs#21813]
## Issue description

At the moment, there can be one cjdns network only.  It would be nice, if one could configure many independent cjdns networks.

Now:
```
services.cjdns = {
   enable = true;
   ...
}
```
Multiple networks:
```
services.cjdns.networks = {
   home = {
      enable = true;
      ...
   };
   hyperboria = {
      enable = true;
      ...
   };
   test = {
      enable = true;
      ...
   };
}
````

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by tohl** [comment]
Marek Mahut <notifications@github.com> writes:
> Are there any updates to this issue, please?

https://github.com/NixOS/nixpkgs/pull/22637 seems to be duplicate of
this issue

see https://github.com/NixOS/nixpkgs/pull/22637#issuecomment-520794260

nixos has a good support for containers these days so one could install
multiple instances of the cjdns module in separate containers with
appropriate networking configuration

this issue can be closed

thank you
