### ISSUE TITLE
Build failure: pkgsMusl.directfb

### ISSUE THREAD

**Issue by superherointj** [NixOS/nixpkgs#218274]
### Steps To Reproduce

1. nix build .#pkgsMusl.directfb

### Build log

* Logs at version 1.7.7: https://termbin.com/fcskz

* After upgrade to last commit (b24f57f8335ef81acab10f395810a7fc2571fe5c): 

  - After patch: https://git.alpinelinux.org/aports/plain/community/directfb/0001-directfb-fix-musl-compile.patch
    - ```error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' undeclared here```
  - After adaptation of patch:
    - https://git.alpinelinux.org/aports/plain/community/directfb/0002-Fix-musl-PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP-comp.patch
    - Patch adapted: https://termbin.com/llvap
    - ```error: implicit declaration of function 'DIRECT_RECURSIVE_MUTEX_INITIALIZER';```
      Logs: https://termbin.com/80fkv

### Additional context

* Affects downstream: pkgsMusl.{webkitgtk,erlang,elixir}
* I will do a bisect of this problem later.

### Notify maintainers
@bjornfor

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 23.05 (Stoat), 23.05.20230223.7607a63`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/store/gpvjq2g2w70wf951a7v72wyh9mki443k-source`
```

### References

* Upstream: https://github.com/deniskropp/DirectFB
* Alpine: https://git.alpinelinux.org/aports/tree/community/directfb?h=master

**Comment by yu-re-ka** [comment]
Note that alpine builds with specific `--with-gfdrivers` and `--with-inputdrivers`, meaning they only build a small subset of the directfb code.

with the patches you mentioned, plus the following configureFlags, it builds:

```

    configureFlags = [
      "--enable-sdl"
      "--enable-zlib"
      "--with-gfxdrivers=${final.lib.concatStringsSep "," [
        "ati128"
        "ep9x"
        "gl"
        "gles2"
        #"gp2d"
        "i810"
        "i830"
        "mach64"
        #"matrox"
        "neomagic"
        "nsc"
        "nvidia"
        "omap"
        "pvr2d"
        "pxa3xx"
        #"radeon"
        #"savage"
        "sh772x"
        "sis315"
        "tdfx"
        #"unichrome"
        "vdpau"
        "vmware"
      ]}"
      "--with-inputdrivers=${final.lib.concatStringsSep "," [
        "dbox2remote"
        "dreamboxremote"
        "dynapro"
        "gunze"
        "h3600_ts"
        "input_hub"
        "joystick"
        "keyboard"
        "linuxinput"
        #"lirc"
        "mutouch"
        "penmount"
        "ps2mouse"
        "serialmouse"
        "tslib"
        "ucb1x00"
        "wm97xx"
        "zytronic"
      ]}"
      "--enable-devmem"
      "--enable-fbdev"
      "--enable-mmx"
      "--enable-sse"
      "--with-software"
      #"--with-smooth-scaling"
      "--enable-x11"
    ];
  });
  
```

**Comment by superherointj** [comment]
`pkgsMusl.directfb` is fixed in master. Closing.
