### ISSUE TITLE
prismlauncher fails to launch Minecraft due to java not finding GLIBC

### ISSUE THREAD

**Issue by Taneb** [NixOS/nixpkgs#218221]
### Describe the bug
The Prism Minecraft launcher, in the `prismlauncher` package, is unable to start Minecraft 1.19.3 (I have not tested other versions but I assume they fail similarly), giving the error

```
Could not start java:
/nix/store/glrwdxbgjwp2r9qszn5zjgkfcini6866-openjdk-17.0.3+7/bin/java: /nix/store/fz33c1mfi2krpg1lwzizfw28kj705yg0-glibc-2.34-210/lib/libc.so.6: version `GLIBC_2.35' not found (required by /nix/store/k88zxp7cvd5gpharprhg9ah0vhz2asq7-gcc-12.2.0-lib/lib/libgcc_s.so.1)
```

### Steps To Reproduce
1. start prismlauncher
2. try to launch Minecraft

### Expected behavior
Minecraft starts normally

### Screenshots
![image](https://user-images.githubusercontent.com/1901799/221354204-163aa8d3-3ac4-415c-91fa-5295f492a5e9.png)

### Additional context
This is on latest unstable

### Notify maintainers

@Minion3665 @Scrumplex 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[taneb@zoro:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 23.05 (Stoat), 23.05pre456790.988cc958c57`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - channels(taneb): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Minion3665** [comment]
I've just tried running a 1.19.3 profile on latest unstable and launched it successfully, however I've noticed a difference between prismlauncher on my system and on yours: I'm using `/nix/store/yza81ww9hc8rzfdachdy4fi4w0ppy8i5-openjdk-17.0.5+8/bin/java` whereas yours is 17.0.3 

Please may you send me a screenshot of what happens if you go into prismlauncher's `settings > java` and press autodetect, that way I can see what java versions prism can see.
Also, is this a new install or have you had prism working before on this system?

Thanks very much!

**Comment by Taneb** [comment]
![image](https://user-images.githubusercontent.com/1901799/221371872-e8bbb7e8-d311-495f-9595-47113b085426.png)

This is indeed an older install which has been working before. I think I may have fixed it to a particular version of Java to solve an earlier problem.

**Comment by Taneb** [comment]
After running that and making sure 17.0.5 was selected, it now works perfectly. Thank you for the suggestion,

**Comment by Majiir** [comment]
This issue bit me again when updating from 23.05 to unstable. Is there a way to patch `prismlauncher` to use a specific JDK path from the Nix store? @minion3665 @Scrumplex @getchoo

**Comment by getchoo** [comment]
everything in the `jdk` attributes of the wrapper will added to `PRISMLAUNCHER_JAVA_PATHS`, which will in turn allow you to select the specific jdk in the launcher's ui. by default, only `jdk8` and `jdk17` are in this attribute, but you can override them like so

```nix
{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    (prismlauncher.override { jdks = [ zulu8 zulu17 ]; })
  ];
}
```

the default `jdks` argument should be working fine on 23.05 and unstable though, so i'm not sure how this problem has come back

**Comment by lcnbr** [comment]
I have the same error on unstable, and even when I override it doesn't find glibc..

**Comment by Scrumplex** [comment]
> I have the same error on unstable, and even when I override it doesn't find glibc..

Make sure the re-select the java you are using in the settings of the launcher and perhaps in your instance settings too
