### ISSUE TITLE
Quicktile

### ISSUE THREAD

**Issue by INIGZ** [NixOS/nixpkgs#218288]
**Project description**

Keyboard-driven Window Tiling for your existing X11 window manager

**Metadata**

* homepage URL: 
[quicktile-master.zip](https://github.com/NixOS/nixpkgs/files/10831846/quicktile-master.zip)
https://github.com/ssokolow/quicktile
* source URL: https://github.com/ssokolow/quicktile
* license: gpl2+ 
* platforms: linux

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/164551
