### ISSUE TITLE
attribute 'xorgserver' missing

### ISSUE THREAD

**Issue by lukego** [NixOS/nixpkgs#21834]
## Issue description

I am attempting to run a [NixOS desktop in the cloud](http://nixer.ghost.io/nixos-in-the-cloud/) but I hit an unexpected error.

My config is:

```
      imports = [ <nixpkgs/nixos/modules/services/x11/terminal-server.nix> ];
      services.xserver.desktopManager.xfce.enable = true;
      services.xserver.desktopManager.default = "xfce";
```

but I hit this error:

```
while evaluating the option `systemd.services.terminal-server@.path':
while evaluating ‘apply’ at /nix/store/q52dh3bxr8f93s39ayp8876if3dqwqvk-nixos-16.03.1346.2946482/nixos/nixpkgs/nixos/modules/system/boot/systemd-unit-options.nix:196:15, called from /nix/store/q52dh3bxr8f93s39ayp8876if3dqwqvk-nixos-16.03.1346.2946482/nixos/nixpkgs/lib/modules.nix:282:11:
while evaluating ‘makeSearchPath’ at /nix/store/q52dh3bxr8f93s39ayp8876if3dqwqvk-nixos-16.03.1346.2946482/nixos/nixpkgs/lib/strings.nix:47:28, called from /nix/store/q52dh3bxr8f93s39ayp8876if3dqwqvk-nixos-16.03.1346.2946482/nixos/nixpkgs/nixos/modules/system/boot/systemd-unit-options.nix:196:22:
while evaluating anonymous function at /nix/store/q52dh3bxr8f93s39ayp8876if3dqwqvk-nixos-16.03.1346.2946482/nixos/nixpkgs/lib/strings.nix:48:32, called from undefined position:
attribute ‘xorgserver’ missing, at /nix/store/q52dh3bxr8f93s39ayp8876if3dqwqvk-nixos-16.03.1346.2946482/nixos/nixpkgs/nixos/modules/services/x11/terminal-server.nix:44:13
error: unable to build all machine configurations
```

## Technical details

Here are the details of the target system. However, I am getting the error in nixops on a different host.

* System: 16.03.1346.2946482 (Emu)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.03.1346.2946482"

Please let me know if I am supplying the wrong information for a multihost nixops deployment!

**Comment by domenkozar** [comment]
Backported to 16.03

**Comment by grahamc** [comment]
Please also consider upgrading to 16.09! :)

**Comment by lukego** [comment]
Just reporting that the backport to 16.03 is not fully working for me. I connect on VNC and the first step works - I get a graphical login prompt that I can authenticate with - but then I just get a blank desktop that does not seem to have any window manager running.

Any tips on finding the relevant logs for troubleshooting?

**Comment by lukego** [comment]
(Just confirming that this does work in NixOS 16.09 for me now.)
