### ISSUE TITLE
Package request: Valent

### ISSUE THREAD

**Issue by FedericoSchonborn** [NixOS/nixpkgs#218392]
**Project description**

Valent is an implementation of the KDE Connect protocol, built on GNOME platform libraries.

Seems to be a re-implementation of [GSConnect](https://github.com/GSConnect/gnome-shell-extension-gsconnect) without the GNOME Shell bits made by the same author, intended to work on more desktop environments but it also has a (separate) GNOME Shell extension.

I have packaged it myself ([here](https://github.com/FedericoSchonborn/valent-nix/blob/main/packages/valent/default.nix)) and it works surprisingly well for an alpha.

![imagen](https://user-images.githubusercontent.com/62166915/221396027-cbd92982-f7fb-4f95-85bf-e7a80746425e.png)

**Metadata**

* homepage URL: https://valent.andyholmes.ca/
* source URL: https://github.com/andyholmes/valent
* license: gpl3Plus, cc0
* platforms: linux

**Comment by foo-dogsquared** [comment]
The linked package works for the part. Tested the clipboard syncing, presentation mode, and remote input (among other things). I've yet to test the app with the GNOME Shell extension though. Looking forward for the PR.

![Screenshot from 2023-02-26 15-41-59](https://user-images.githubusercontent.com/34962634/221398484-af7f8a6f-d76f-4550-a3b6-e9b7665031bc.png)
