### ISSUE TITLE
Chromium WideVine plugin fails to fetch Chrome Dependency

### ISSUE THREAD

**Issue by ixxie** [NixOS/nixpkgs#21833]
## Issue description

Rebuilding chromium with the WideVine plugin fails to build due to missing chrome dependency:
                                                          
    curl: (22) The requested URL returned error: 404
    error: cannot download google-chrome-stable_54.0.2840.90-1_amd64.deb from any mirror 

### Steps to reproduce

`nixos-rebuild` this:

    { config, pkgs, ... }: 
    
    {
        system.stateVersion = "16.09";
        environment.systemPackages = [ pkgs.chromium ];
        nixpkgs.config.chromium.enableWideVine = true;
    }

**Comment by ixxie** [comment]
@aszlig @volth (sorry if I am tagging the wrong people here; had to guess somewhat.)

**Comment by volth** [comment]
That version was gone and version number in nix updated 2 months ago: https://github.com/NixOS/nixpkgs/issues/20748
Try ```nix-channel --update```

**Comment by ixxie** [comment]
Thanks, that seems to have resolved it.... but still requires Chromium to be built from scratch; oh well!

**Comment by globin** [comment]
Seems to be fixed, so I'm closing it :)
