### ISSUE TITLE
Package request: a4

### ISSUE THREAD

**Issue by evanrelf** [NixOS/nixpkgs#218328]
**Project description**

> A4 is a dynamic terminal window manager ... It is a partial rewrite of [dvtm](https://www.brain-dump.org/projects/dvtm/)

**Metadata**

* homepage URL: https://a4term.com/
* source URL: https://github.com/rpmohn/a4
* license: mit
* platforms: unix

**Comment by onemoresuza** [comment]
Hoping to package it, after the [libtickit pull request](https://github.com/NixOS/nixpkgs/pull/238657#issue-1764347994) is accepted.

**Comment by onemoresuza** [comment]
[Pull request](https://github.com/NixOS/nixpkgs/pull/245247) made.

**Comment by onemoresuza** [comment]
a4term merged into master.
