### ISSUE TITLE
`nix shell` doesn't provide completions

### ISSUE THREAD

**Issue by deemp** [NixOS/nixpkgs#218489]
### Describe the bug
Completions don't work when in a `nix shell`.
 
For example, `nix shell nixpkgs#cabal-install` doesn't provide completions for `cabal`.

### Steps To Reproduce

```
nix shell nixpkgs#cabal-install
cabal in<TAB>
cabal index.html
```

where `index.html` is a random file whose name prefix matches the prefix of a `cabal` command.

### Expected behavior

```
cabal in<TAB>
info     init     install
```

**Comment by cdepillabout** [comment]
`cabal-install` does ship completions:

```console
$ nix-build -A cabal-install
$ cat result/share/bash-completion/completions/cabal
...
```

**Comment by deemp** [comment]
@cdepillabout. You're right, it's not a `cabal`-specific issue. Please, consider removing the `6.topic-haskell` label.

**Comment by cdepillabout** [comment]
@deemp Label removed, thanks for the reminder.

Also, I'm not super familiar with the interaction between completions and `nix shell` or `nix-shell`, but it is possible that it makes more sense to post about this on the Nix issue tracker.  Maybe at least you should take a look there to see if anyone has posted something similar.

**Comment by deemp** [comment]
Thanks for a suggestion! Seems like https://github.com/NixOS/nix/issues/4453 addresses this issue.
