### ISSUE TITLE
current system in binfmt.emulatedSystems breaks with Too many levels of symbolic links

### ISSUE THREAD

**Issue by gardspirito** [NixOS/nixpkgs#218465]
### Describe the bug
On `x` system, after setting `boot.binfmt.emulatedSystems = [ "x" ];`, bash stops working for any command:
```
-bash: /run/current-system/sw/bin/ls: Too many levels of symbolic links
```

### Steps To Reproduce
1. Given `aarch64-linux system`
2. `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];`
3. `nixos-rebuild switch`
4. bash breaks, unable to rollback from the terminal.

### Expected behaviour
Such values of `boot.binfmt.emulatedSystems` should be disallowed.

**Comment by Artturin** [comment]
the way to fix this would be to use `type = types.listOf (types.enum [ ... ]);` but it would have to be kept up to date manually

**Comment by zhaofengli** [comment]
No, it's about having the current system listed in `boot.binfmt.emulatedSystems`. I also ran into this when converting an existing `x86_64-linux` install to `aarch64-linux` (the original config had `aarch64-linux` in `boot.binfmt.emulatedSystems`). We just need to add a simple assertion to fix this.

**Comment by nagy** [comment]
I also just ran into this. This can easily break the boot of a remote system, making it inaccessible.

> We just need to add a simple assertion to fix this.

Yes that would be great.
