### ISSUE TITLE
`rustPlatform.buildRustPackage` removes hidden directories from submodules during dependency vendoring when `cargoSha256` is used

### ISSUE THREAD

**Issue by wucke13** [NixOS/nixpkgs#218424]
### Describe the bug
The fetching of dependency crates in `rustPlatform.buildRustPackage` doesn't copy over folders starting with `.` in submodules when used with `cargoSha256`. In the concrete example this fails because:

- My package depends on the [`oqs-sys`](https://github.com/open-quantum-safe/liboqs-rust/tree/main/oqs-sys) crate
- `oqs-sys` has a git submodule for `liboqs`
- in that git submodule repo there is a folder `.CMake` which contains CMake scripts
- these are sourced during the build of the vendored dependencies using the `build.rs` of `oqs-sys`
- when building with `src = fetchFromGitHub` and `cargoSha256` the build fails, as the `.CMake` dir is missing

### Steps To Reproduce
1. Build the `rosenpass` package from https://github.com/wucke13/nixpkgs/tree/dev/cargo-lockfile-issue
2. Observe that the build fails due to
   - a missing `.CMake/compiler_opts.cmake`
   - a missing `.CMake/alg_support.cmake`
3. Both of which should be in a submodule of the `oqs-sys` crate
   - https://github.com/open-quantum-safe/liboqs-rust/tree/main/oqs-sys
   - https://github.com/open-quantum-safe/liboqs/tree/49164467b6456a217b09c5d1a6c830abb64fc1a6/.CMake
4. However, when unpacking the cargo vendored dependencies tarball, an `ls -lah` to `oqs-sys/liboqs/` yields no `.CMake` dir

### Expected behavior
I expect the build to work as it [__does__ when using a local `Cargo.lock` file](https://github.com/rosenpass/rosenpass/blob/main/flake.nix#L76-L78).

### Notify maintainers

@figsoda @linsui @sternenseemann @Artturin 

### Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.2, NixOS, 22.11 (Raccoon), 22.11.20230106.2dea899`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by figsoda** [comment]
@nixos/rust

**Comment by figsoda** [comment]
Might be an issue with `cargo vendor`, I can reproduce this without nix.

For now you can vendor the Cargo.lock and use `cargoLock`, we are planning to migrate to that for all rust packages: https://github.com/NixOS/nixpkgs/pull/217084

**Comment by dadada** [comment]
This can be fixed by including an include directive in the manifest of `liboqs-rust`.

https://github.com/open-quantum-safe/liboqs-rust/issues/188

**Comment by dadada** [comment]
See here for the resulting package that uses `cargoHash` https://github.com/dadada/nixpkgs/commit/92e46cc88976fc7901567eac920116c0063d1882
