### ISSUE TITLE
Hugin crashes

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#218452]
### Describe the bug
At first, it was crashing because addr2line was not found, which I fixed by installing binutils. Should it be a dependency?
Now it is crashing giving `IOT instruction (core dumped)  hugin` when running from zsh and `line 3: 566139 Aborted                 (core dumped) hugin` when running in nix-shell.

### Steps To Reproduce
1. `nix-shell -p hugin --run hugin`

### Expected behavior
Hugin works

### Notify maintainers

@hrdinka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 22.11 (Raccoon), 22.11.2720.50c23cd4ff6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(aroun): `""`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by hrdinka** [comment]
Hi! Thanks for your report.

I haven‘t found any reference for addr2line in hugins source code. It also runs for me without it. Maybe it is needed by some dependency. However if this fixes stuff I am for adding it in the wrapper.

I cannot replicate the other issue, it works just fine for me. It looks like you are running NixOS stable. Have you testet the current version from unstable? In case unstable works we should backport it to stable.

**Comment by Zahrun** [comment]
Hi! Thanks for the reply.

I can confirm that installing hugin from unstable does not complain about addr2line and also does not crash.
Would be good to backport.

**Comment by hrdinka** [comment]
Great, the new bug should be fixed here:
https://github.com/NixOS/nixpkgs/pull/217828

I guess it is best to wait for this PR and then cherry-pick everything onto stable.

**Comment by dandanua** [comment]
Can confirm, stable version crashes, but unstable works fine.

**Comment by hrdinka** [comment]
@dandanue thanks for your report!

Seems like a new problem has emerged and was patched 12h ago without my notice https://github.com/NixOS/nixpkgs/pull/252453.

Will be back-ported here https://github.com/NixOS/nixpkgs/pull/252567

I will close this issue for now. Please open a new one in case you still experience any errors.

**Comment by hrdinka** [comment]
Sorry I was wrong. I just gave it a closer look, 23.05 is still running on exiv 0.27.7. So this patch should not be needed. Do you have more information about the crash?

**Comment by dandanua** [comment]
Ah, it must be a different problem. When I run it from nix-shell it crashes with 
```
hugin

(hugin:45778): Gtk-CRITICAL **: 16:14:09.585: gtk_widget_set_size_request: assertion 'height >= -1' failed
```

Metadata
```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.119, NixOS, 22.11 (Raccoon), 22.11.4773.ea4c80b39be4`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by hrdinka** [comment]
I have just installed it from the stable channel and tried it within nix-shell and it does work for me.

Seems like you are using NixOS 22.11, which is not supported anymore. Please upgrade.

**Comment by hrdinka** [comment]
I will close this for now since the original problem is fixed. Please open a new issue if any problems persist.
