### ISSUE TITLE
Build failure: Erlang 24 fails to build with default openssl package

### ISSUE THREAD

**Issue by thlr1** [NixOS/nixpkgs#218575]
### Steps To Reproduce

1. Open a `nix-shell` With the following `shell.nix`

```
{
  pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/c95bf18beba4290af25c60cbaaceea1110d0f727.tar.gz") {}
}:

let
  erlang = pkgs.erlangR24.override {
    version = "24.1.7";
    sha256 = "R4rZVMn9AGvOy31eA1dsz2CFMKOG/cXkbLaJtT7zBrU=";
  };
in
pkgs.mkShell {
  buildInputs = [ erlang ];
}
```

2. Wait for erlang to build. It should fail.

### Build log

https://gist.github.com/thlr1/e558f0bdb076b7e2d276ea27a3bb54d3

### Additional context

The build works with `openssl_1_1` as the openssl package :

```
let erlang = pkgs.erlangR24.override {
    version = "24.1.7";
    sha256 = "R4rZVMn9AGvOy31eA1dsz2CFMKOG/cXkbLaJtT7zBrU=";
    opensslPackage = pkgs.openssl_1_1;
  };
```

### Notify maintainers

@ankhers @Br1ght0ne @DianaOlympos @gleber @minijackson @yurrriq

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 23.05 (Stoat), 23.05.20230222.988cc95`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

Edit : tagging my personal account here also @thlr

**Comment by kirillrdy** [comment]
on latest master 69326363f710ba45d722fa4e1e57d78b01a1513c

```
nix-build -A erlangR24
/nix/store/d97cmkp1zdghzwccrfr2a4whi33qyid4-erlang-24.3.4.9
```

I havent tried your specific version of erlang, do you need to use that specific version ?

**Comment by thlr1** [comment]
I am not sure, I haven't tried with your version of erlang. I did try with erlang 25 though, and got the same result.

**Comment by kirillrdy** [comment]
```
nix-build -A erlangR25
/nix/store/1nlng2am24va2m3giwwldqipq107pgvh-erlang-25.3
```

erlang 25 works as well, i suggest  you try latest master, or commit that I've used

**Comment by thlr1** [comment]
That seemed fast for a complete build, are you sure you are not retrieving a cached build?
Using another version is not an option. The project I worked with there was on erlang 24.1.7. Did you try my `shell.nix`?

**Comment by kirillrdy** [comment]
I have tried you shell, and it indeed fails.

Initially I assumed the issue was that elrlang 24 was not building with default openssl, ( as per title of this issue ). But you are trying to build erlang with incompatible version of openssl

You can see from build logs, 
``` 204 | OSSL_DEPRECATEDIN_3_0 int RSA_size(const RSA *rsa); ``` that elang 24.1.7 is not compatible with openssl 3

so, this is not an issue with nixpkgs

some options for you

1) migrate your project to latest erlangR24 
2) override erlagR24 until it works for you
3) find commit in nixpkgs when erlangR24 is right version then other dependencies should also be of the right version

**Comment by DianaOlympos** [comment]
Or inject an older version of openssl

**Comment by kirillrdy** [comment]
> Or inject an older version of openssl

if you mean via overlay, then yes, thats an other option, similar to option 2

**Comment by thlr1** [comment]
@kirillrdy , @DianaOlympos , this is *exactly* what I wrote on the issue.

The build works when *explicitely* injecting `openssl_1_1` instead of `openssl` in the build. All is fine, I can build Erlang and use it.

However as an end user I should not have to do this. I will not look for the exact commit of nixpkgs where `ErlangR24` builds fine. I will also not use Erlang 25 or even the latest Erlang 24, as this choice is not mine to make. I realize I wasn't very clear on these subjects, for that I apologize.

Sorry if I look annoyed, I am grateful for your help.

Now, maybe I did not understand something here. Isn't `ErlangR24` an alias to a correct build of Erlang 24? What happens if I use `ErlangR24` and override its version? How do you build Erlang in the first place, if the version of `openssl` you are using in the definition is not right?

**Comment by kirillrdy** [comment]
> @kirillrdy , @DianaOlympos , this is _exactly_ what I wrote on the issue.
> 
> The build works when _explicitely_ injecting `openssl_1_1` instead of `openssl` in the build. All is fine, I can build Erlang and use it.
> 
> However as an end user I should not have to do this. I will not look for the exact commit of nixpkgs where `ErlangR24` builds fine. I will also not use Erlang 25 or even the latest Erlang 24, as this choice is not mine to make. I realize I wasn't very clear on these subjects, for that I apologize.
> 
> Sorry if I look annoyed, I am grateful for your help.
> 
> Now, maybe I did not understand something here. Isn't `ErlangR24` an alias to a correct build of Erlang 24? What happens if I use `ErlangR24` and override its version? How do you build Erlang in the first place, if the version of `openssl` you are using in the definition is not right?


software is complicated :-), so no hard feelings

> However as an end user I should not have to do this.

because that precise version of erlang is not compatible with that version of openssl, you not going to find a distribution that offers you out of the box experience. 

its possible that some distributions haven't switched to openssl 3, so your precise version of erlang will build and work, its not the case for distributions that have switched

> Isn't ErlangR24 an alias to a correct build of Erlang 24

erlangR24 is usually the latest 24 release, but nixpkgs is a monorepo, so latest version of 24 is tested and build against latest version of everything including openssl. erlang team have introduced support for openssl3 in latest 24 release. this doesn't mean all 24 releases build with openssl 3.

> How do you build Erlang in the first place, if the version of openssl you are using in the definition is not right?

if erlang developers don't support that version of openssl, options is either adopt supported version of openssl, or fix erlang to work with version of openssl you wish


if some of this doesnt make sense, feel free to follow up questions. I think we  all benefit from more knowledge

**Comment by thlr1** [comment]
I see, thank you for your answers.

> its possible that some distributions haven't switched to openssl 3, so your precise version of erlang will build and work, its not the case for distributions that have switched

I am on NixOS here therefore the version of `openssl` that is used here is the one provided in the nixpkgs definition.

> erlang team have introduced support for openssl3 in latest 24 release. this doesn't mean all 24 releases build with openssl 3.

This part especially makes more sense to me now.

> Nixpkgs only promise that the erlangR24 works if used as is. Here you inject your own version so all bets are off

I had a gut feeling about this but I wasn't sure what the behavior was there, thanks for confirming.

I guess I am just annoyed that I can't simply write `version = 24.1.7` and have it work right out of the box. Would it be possible to choose the right version of `openssl` (it's just a matter on choosing `openssl_1_1` over `openssl`) depending on the given erlang version we want to build? Unless explicitly overwritten by the user.

**Comment by DianaOlympos** [comment]
> Would it be possible to choose the right version of `openssl` (it's just a matter on choosing `openssl_1_1` over `openssl`) depending on the given erlang version we want to build? Unless explicitly overwritten by the user.

in theory yes, all you have to do is to make one derivation per version and precise the version of openssl in its inputs.

In practice, we will not do that in nixpkgs. If someone wants to offer it, they are free to do so, it is not that hard. But nixpkgs already maintain at least 3 versions of erlang, with multiple inputs, to the point that I think we have a good dozen different versions and flavors available.

At this point, you better override yourself or use your own derivation. We already have enough problems keeping this running.

**Comment by thlr1** [comment]
Noted, this helps understanding how the packages are designed and maintained. I hope my fix will help other people that might encounter the same issue.
