### ISSUE TITLE
GDM doesn't unlock the GNOME keyring

### ISSUE THREAD

**Issue by e-user** [NixOS/nixpkgs#21859]
## Issue description

GDM's PAM modules are currently built so that the password stack of the keyring PAM module get loaded *before* a password input module is loaded, which results in the keyring never being unlocked automatically.

### Steps to reproduce

1. Log in with GDM
2. Try to use an application that has its password stored in GNOME keyring
3. It will ask you for the unlock password

## Technical details

* System: 16.09.git.fd1dbe5 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: 16.09.1465.fd1dbe5

**Comment by FRidh** [comment]
Relevant discussion on unified PAM settings https://github.com/NixOS/nixpkgs/issues/17044

**Comment by alexeymuranov** [comment]
Same with LightDM.

**Comment by alexeymuranov** [comment]
Automatic GNOME keyring unlocking with LightDM is fixed in NixOS 18.03, but GDM still does not unlock the keyring...

**Comment by eqyiel** [comment]
I wonder if this is resolved after https://github.com/NixOS/nixpkgs/pull/43992

**Comment by jtojnar** [comment]
@eqyiel If it is a PAM thing, I do not thinks so. We did not touch PAM.
