### ISSUE TITLE
GHC as a test case for complications with cross-compiling

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixpkgs#21874]
Since #21268 (or something like it) will hopefully be merged soon, I want to outline the ways in which GHC, as an example, violates the strict staging that PR wants.

First, the GHC build includes support libraries for the target system. In principle, this could be kept with the desired staging with multiple outputs, and including the target libs in the next stage, but it will likely be complicated to do. This issue exists for gcc which has libstdc++, and llvm as it currently exists with compiler-rt etc. build at the same time as the compiler.

Second, and harder to disentangle without upstream support for separating, the GHC build includes *binaries* intended to run on the target platform (in particular, `iserv`, whose whole purpose is to be able to run target code during compile time). Putting these in separate outputs won't be enough: They will also depend on target libs as inputs (e.g. `libiconv` in the `iserv` case).

In principle, both of these could (and probably should) be separated out into different builds from the core compiler itself. But I write this up as a guide to keep in mind until upstreams are as principled as we are :smile: 

cc @Ericson2314

**Comment by Ericson2314** [comment]
Yeah I've been glaring at GHC for a while for being horrible here.

Rustc is a bit closer and I hope to soon push it over the edge: see https://github.com/Ericson2314/rfcs/blob/cargo-libstd/text/0000-cargo-libstd-awareness.md which ironically Cabal does get right. The key thing will be when Cargo does do this, a simple `cargo build` can build a rustc binary (single bootstrapping stage) or standard library.

**Comment by Ericson2314** [comment]
A stop-gap hack is just to call the entire derivation, not just wrapper script, from https://github.com/Ericson2314/nixpkgs/blob/host-target/pkgs/top-level/build-wrappers.nix

**Comment by shlevy** [comment]
@Ericson2314 What're your thoughts on the current state here?

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nixpkgs/pull/26799 should close this.

**Comment by Ericson2314** [comment]
OTOH I didn't do any separate output for `iserv` or similar.
