### ISSUE TITLE
PHP extensions not working on CLI

### ISSUE THREAD

**Issue by berksmbl** [NixOS/nixpkgs#218797]
### Describe the bug
Although I have PHP Extensions installed, I cannot access these extensions via the PHP CLI.

### Steps To Reproduce
1. `$ nix-shell -p php82`
2. `$ nix-shell -p php82Extensions.mongodb`
3. `$ php -m`

### Expected behavior
Accessing the module on PHP CLI side after installing PHP Extension.
This causes commands executed by the CLI to result in errors in some PHP applications such as Laravel.

**Comment by henrikruscon** [comment]
From what I can tell, the install process in nixpkgs is assuming all you need to do is install the extension and then nothing more.

Possible that adding the `docker-php-ext-enable {pkgname}` command would solve this issue. Seems to be the suggested way to do it anyways.

Honestly Railway seems very much in its infancy as a service, a lot of bugs.

**Comment by henrikruscon** [comment]
From what I can tell, the install process in nixpkgs is assuming all you need to do is install the extension and then nothing more.

Possible that adding the `docker-php-ext-enable {pkgname}` command would solve this issue. Seems to be the suggested way to do it anyways.

**Comment by berksmbl** [comment]
`$ nix-shell -p "php82.withExtensions (pe: pe.enabled ++ [pe.all.mongodb])"`
