### ISSUE TITLE
Build failure: slstatus

### ISSUE THREAD

**Issue by lourkeur** [NixOS/nixpkgs#218899]
### Steps To Reproduce

1. build *slstatus* with a custom `conf` parameter

### Build log

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/881bsjyn3bpm6xpf3qfvd6hxc2vvf2rp-slstatus-b14e039
source root is slstatus-b14e039
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
/nix/store/3yfs41f4b60jya2gk6xikx4s97zsxjr0-stdenv-linux/setup: eval: line 113: syntax error near unexpected token `('

```

### Additional context
introduced by 402b1ebdcc6e9ecec91a384cfa1598aa89d362cc
To reproduce:
```nix
{
  description = "A very basic flake";

  inputs.nixpkgs.url = "nixpkgs/402b1ebdcc6e9ecec91a384cfa1598aa89d362cc";

  outputs = { self, nixpkgs }: {
    packages.x86_64-linux.slstatus = nixpkgs.legacyPackages.x86_64-linux.slstatus.override { conf = "stuff"; };
    packages.x86_64-linux.default = self.packages.x86_64-linux.slstatus;
  };
}
```

This is du to the construction of `preBuild` which should insert a new line. I will write a patch tomorrow.

### Notify maintainers

@oxzi, maintainer
@happysalada committed the breaking change

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12-zen1, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/etc/nix/channels/nixos`
```

**Comment by happysalada** [comment]
Thank you for finding this! Feel free to ping me when the patch is ready.

**Comment by oxzi** [comment]
It should be sufficient to add a semicolon after the preBuild's `cp`
command or, imho even better, merge these two strings into a multi-line
string with a line break in between.

Sorry for missing this during the PR review. I'll try to create a patch
and PR later this evening (CET).
