### ISSUE TITLE
Update request: yuzu-ea 2945 → 3493

### ISSUE THREAD

**Issue by rkunschke** [NixOS/nixpkgs#218827]
- Package name:  yuzu-ea
- Latest released version: 3493

- Current version on the unstable channel: 2945
- Current version on the stable/release channel: 2945

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

@kira64xyz @IvarWithoutBones @JoshuaFern @sbruder 

I hope there is an easy solution without to much struggle. The package is out-of-date since months. I think the mainline-build too.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by lheckemann** [comment]
Done in #228872
