### ISSUE TITLE
Update request: csvkit 1.0.5 → 1.1.1

### ISSUE THREAD

**Issue by vielmetti** [NixOS/nixpkgs#218995]
- Package name: csvkit
- Latest released version: 1.1.1

- Current version on the unstable channel: 1.0.5
- Current version on the stable/release channel: 1.0.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

attn @vrthra 

upstream at https://github.com/wireservice/csvkit
upstream docs at https://csvkit.readthedocs.io/en/latest/
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by fabaff** [comment]
#219146 contains the update.
