### ISSUE TITLE
Implement `systemd.services.<name>.createDirs`

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#2189]
Currently we don't have interface that would create data directories before service is started. People used to handle this on different ways, that worked more or less successfully:

- Using `user.createHome = true`. That didn't used to work very well, when new interface for users was introduced services used to break.
- Using activation scripts. I like this solution, because it's simple, but it's not used very much.
- Using something i call dual behaviour. So using systemd option `PermissionsStartOnly = true` systemd starts pre and post startup scripts as root. The problem is that you now have to use `su` to become user and then you have to handle dual behaviour if services are started as root (with systemd) or with some other implementation. I especially dislike that behaviour, it also does not work on user services implementation i use (https://github.com/kiberpipa/nix-rehash/tree/master/nix-services) in osx.

Now the question is how should i implement this?
- @shlevy proposed that pre and post start should be split into new service and service would depend on both of them. The problem here is that if we would only need this for creating data dirs, this is kind of overdesign, but on the other hand pre and post scripts could be started independantly.
- Use activation scripts to create directories
- ... ?

I would also need some help implementing this. I think this option is very much needed.

**Comment by Profpatsch** [comment]
(triage) @offlinehacker do you plan on following through with that? Is it even necessary anymore?

**Comment by aragnon** [comment]
In general, don't we just want to copy the same module set as other popular configuration management systems have? E.g. in Puppet, you have:

https://docs.puppetlabs.com/puppet/latest/reference/type.html#file . When I see NixOS configuration management it sort of feels like one still needs to build all the basics before getting to the real work. 

From a UI point of view something like the following: 

```
dir."/exports/foo".status = "present";
dir."/exports/foo".owner = "alice";
```
seems to be the way to go. The advantages of this is that it leverages well known terminology and seems to be fairly consistent with how NixOS already does configuration.

**Comment by Profpatsch** [comment]
I don’t quite understand what you are referring to, @aragnon. The case of systemd service files or sth. more general?

Since no followup in over a week we can close @jagajaga

**Comment by aragnon** [comment]
@Profpatsch Something more general; I don't think merely creating a directory should depend on systemd.

**Comment by Profpatsch** [comment]
You are probably overcomplicating things. You can put any file you want into the store, trivially (look into `pkgs/build-support/trivial-builders`.
And for `etc` there exists `environment.etc`, although it should be used very sparingly and only if that crude program behaviour cannot be patched out.

**Comment by aragnon** [comment]
The store is /nix, so how do I specify an arbitrary location like /constant?

**Comment by Profpatsch** [comment]
@aragnon Why do you want to do that? If you want to do anything on a package level, you should stay inside the store. If you want to do something elaborate on a module level (like having state files for services) you can create a new user that has its own home directory. See for example how I do it [here](https://github.com/NixOS/nixpkgs/pull/13587/files#diff-2b4f916891982406e7ba22f64770337dR101), where I create a home in `/var/lib`.

**Comment by aragnon** [comment]
@Profpatsch I want to setup an NFSv4 location at e.g. /nfs-export/constant.

**Comment by Profpatsch** [comment]
close @zimbatm
