### ISSUE TITLE
networkd-dispatcher does not work due to incorrect permissions

### ISSUE THREAD

**Issue by apfelkuchen6** [NixOS/nixpkgs#218930]
### Describe the bug
`networkd-dispatcher` refuses to work since it requires the directories containing the scripts to have mode 755, but the nixos module creates them with mode 750.

### Steps To Reproduce
1. 
 ```
services.networkd-dispatcher = {
  enable = true;
  scriptDir = "/etc/networkd-dispatcher";
};
environment.etc = {
  "networkd-dispatcher/configured.d/test".source =
    pkgs.writeShellScript "echo I WAS RUN > /tmp/test";
 };
  ```
2. (re)-configure an interface (for example by unplugging and replugging a network cable)
2. Observe something like `Mar 01 04:24:49 pumpkin networkd-dispatcher[1636325]: ERROR:invalid permissions on /etc/networkd-dispatcher/configured.d. expected mode=0o755, uid=0, gid=0; got mode=0o750, uid=0, gid=0` in the journal and that `/tmp/test` does not exist, i.e. the hook was never run.

### Expected behavior
networkd-dispatcher works.

### Notify maintainers

@onny 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.95, NixOS, 23.05 (Stoat), 23.05.20230228.6c42603`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/dcrhsvahgmbadn99zmbz0p9dd4w1mmni-source`
```

**Comment by onny** [comment]
Thank you for the report! I'm thinking about adding a rules option to the networkd-dispatcher module so this might solve your issue https://github.com/NixOS/nixpkgs/pull/218633
