### ISSUE TITLE
Implement standard interface for user services

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixpkgs#2190]
So i have a working implementation for user services using supervisord for managing processes avalible here: https://github.com/kiberpipa/nix-rehash (directory nix-services). It's using the current systemd interface for services to start user services.

I have found a few problems with systemd current interface for services that would be nice to get fixed in the future:
- Dual behaviour that we have for handling service pre and post start scripts if user is root or not. Fact is that the most of the times only data directories have to be created as root and everything else should be handled as normal user. I opened issue for createDataDirs here: https://github.com/NixOS/nixpkgs/issues/2189
- Some commands do not work on osx and this prevents running user services on osx.
- Post start scripts are not allways avalible in process managers, so relying on that kinda breaks functionality.

There's also an option to create different interface for user services, what do you think about that?

**Comment by Profpatsch** [comment]
(triage) Since someone’s gone forward and built https://github.com/NixOS/nixpkgs/pull/9250 this can be closed now.
cc @jagajaga
