### ISSUE TITLE
github-runner: file not found when using `workDir` and relative path

### ISSUE THREAD

**Issue by xgroleau** [NixOS/nixpkgs#219080]
### Describe the bug
A file cannot be found because of the systemd dynamic user private directory when using relative paths.

For example, when using the [`action/cache`](https://github.com/actions/cache), the post cache cleanup job fails.
```
0s
Post job cleanup.
/nix/store/c1bnxbgp7r1h2wzg3ifz9yah71ym5qrq-gnutar-1.34/bin/tar --posix -cf cache.tgz --exclude cache.tgz -P -C /var/lib/github-runner-work/nixos-runner/chow/chow --files-from manifest.txt -z
/nix/store/c1bnxbgp7r1h2wzg3ifz9yah71ym5qrq-gnutar-1.34/bin/tar: ../../../../private/github-runner-work/nixos-runner/chow/chow/target: Cannot stat: No such file or directory
/nix/store/c1bnxbgp7r1h2wzg3ifz9yah71ym5qrq-gnutar-1.34/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to save: "/nix/store/c1bnxbgp7r1h2wzg3ifz9yah71ym5qrq-gnutar-1.34/bin/tar" failed with error: The process '/nix/store/c1bnxbgp7r1h2wzg3ifz9yah71ym5qrq-gnutar-1.34/bin/tar' failed with exit code 2
```
The valid path is actually  ` ../../../../github-runner-work/nixos-runner` instead of ` ../../../../private/github-runner-work/nixos-runner`.

I'm not really sure what we can do about since we use dynamic users. Ideally actions should not use relative paths, but that is out of our control. Feel free to close if this issue is not relevant.
### Steps To Reproduce
Setup a runner
```nix
      services.github-runners.nixos-runner = {
        enable = true;
        replace = true;
        url = "https://github.com/HOP-Tech-Canada";
        tokenFile = config.age.secrets.ghRunner.path;
        workDir = "%S/github-runner-work/nixos-runner";
      };
```
Use [`action/cache`](https://github.com/actions/cache) and cache any file in the workflow,

### Expected behavior
The post target cache should work as expected.

### Notify maintainers
Maintainers: @veehaitch @newAM @kfollesdal @aanderse

**Comment by aanderse** [comment]
Have you tried not using a dynamic user? It sounds like that will solve your problem.

**Comment by xgroleau** [comment]
Just realized there is the `serviceOverrides` option, I totally missed it sorry. Disabling dynamic users will probably fix this.
