### ISSUE TITLE
ffmpeg: update to ffmpeg_6

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#219190]
- Package name: ffmpeg
- Latest released version: 6.0
- Current version on the unstable channel: 5.1.2
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@Atemu 

**Related:**

https://github.com/NixOS/nixpkgs/pull/218309

I think the way to go with such a rename should be to follow the instructions here:

https://github.com/NixOS/nixpkgs/blob/2e8194d47b7970f017f3d4e8896a605f62c69c95/pkgs/top-level/all-packages.nix#L19772-L19778

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by fabianhjr** [comment]
Current version is 4.x, this would probably be added as an extra package (ffmpeg_6 and variants)

**Comment by vcunat** [comment]
BTW, 5.1 is LTS and should be maintained by upstream for two years, if I got it right.

**Comment by vcunat** [comment]
I wonder if this should be closed, as default `ffmpeg` remained same.  (even 4 on `master`, but 5 soon from `staging-next`)

**Comment by Atemu** [comment]
I think

**Comment by NickCao** [comment]
ffmpeg defaults to 6 now on master
