### ISSUE TITLE
Update request: burpsuite 2023.1.2 → 2023.2.2

### ISSUE THREAD

**Issue by AkechiShiro** [NixOS/nixpkgs#219199]
- Package name: `burpsuite`
- Latest released version: `2023.2.2`

- Current version on the unstable channel: `2023.1.2`
- Current version on the stable/release channel: `2021.12`

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.
@bennofs 

Also could it be described why there is this huge gap version between the stable and unstable version ? Some tests are probably failing for the unstable version ?

**Comment by MGlolenstine** [comment]
Closed by #223260
