### ISSUE TITLE
Update request: geekbench 5.4.6 → 6.0.0

### ISSUE THREAD

**Issue by pogobanane** [NixOS/nixpkgs#219152]
- Package name: geekbench
- Latest released version: 6.0.0

- Current version on the unstable channel: 5.4.6
- Current version on the stable/release channel: 5.4.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@michalrus @wegank 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by MGlolenstine** [comment]
Closed by #220554
