### ISSUE TITLE
Proper way of creating a hook for network devices?

### ISSUE THREAD

**Issue by mikael-andersson** [NixOS/nixpkgs#21920]
## Issue description

What is the proper way in  NixOS to create a hook for network devices or more specifically for my builtin WWAN modem?

Background:
I do not want SpiderOak to sync when I am using my mobile broadband. Since SpiderOak does not have a way of pausing or halting the sync via CLI, at least what I am aware of, I simply want to kill SpiderOak when the modem gets connected and start SpiderOak when the modem gets disconnected. This way I ensure syncing with WiFi only.

### Steps to reproduce
N/A

## Technical details

Hardware: Lenovo X1 Carbon

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.1445.e9a8853 (Flounder)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.09.1445.e9a8853"

**Comment by Mic92** [comment]
One way would be to create a udev rule to stop spideroak, but I don't know if events are triggered for virtual interfaces such as ppp are creates. It is probably easier to just to use iptables and block the oakport port + interface

**Comment by mikael-andersson** [comment]
I have now googled and experimented a bit and found out that it seems to work well to put a script in '/etc/ModemManager/dispatcher.d'. The first argument that is received by the script is the name of the interface and the second argument can be either 'up' or 'down'. One strange thing is that the interface names are different depending on if it is an up or down event. Anyhow, that is not a big issue for me.

Since I am not so keen on explicitly creating scripts or even symbolic links in /etc/ModemManager/dispatcher.d, I would rather have it as part of the NixOS configuration. Could we add this support?

I am thinking about adding the following attributes in some kind of format for NixOS configuration:

_interface-name user-name execute-script_
_state user-name execute-script_
_interface-name state user-name execute-script_
_user-name execute-script_

I suppose it is rather self explaining, but I will explain anyhow. :)

The _user-name_ specifies what user should run the script.
The _interface-name_ specifies what interface to execute the script for.
The _state_ specifies the interface's state to execute the script for.

Feedback on this is very welcome.

**Comment by Mic92** [comment]
you mean something like this? https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/networkmanager.nix#L143

**Comment by mikael-andersson** [comment]
Thanks, I was unaware of this, but does it really work? I am not able to get it to work.

When I add something like this to my configuration.nix:
`networking.networkmanager.dispatcherScripts = [ { source = "path to script 1"; } { source = "path to script 2"; } ];`

**ll /etc/NetworkManager/dispatcher.d/** gives:
lrwxr-xr-x 1 root root 53 Jan 21 00:20 01nixos-ip-up -> /etc/static/NetworkManager/dispatcher.d/01nixos-ip-up
lrwxr-xr-x 1 root root 53 Jan 21 00:20 02overridedns -> /etc/static/NetworkManager/dispatcher.d/02overridedns
lrwxr-xr-x 1 root root 56 Jan 21 00:20 03userscript0001 -> /etc/static/NetworkManager/dispatcher.d/03userscript0001
lrwxr-xr-x 1 root root 56 Jan 21 00:20 03userscript0002 -> /etc/static/NetworkManager/dispatcher.d/03userscript0002

**ll /etc/static/NetworkManager/dispatcher.d/** gives:

lrwxr-xr-x 1 root root 57 Jan  1  1970 01nixos-ip-up -> /nix/store/as1jk3pfb5ldhdfpkd0dqfv01yr15ak1-01nixos-ip-up
lrwxr-xr-x 1 root root 57 Jan  1  1970 02overridedns -> /nix/store/ma4242p8r8ffvbwjavkg1q8yk60gyhzx-02overridedns
lrwxr-xr-x 1 root root 60 Jan  1  1970 03userscript0001 -> /nix/store/jsydpkqrfbywb20w93f34yzddq9ln2p9-etc-unnamed-12.9
lrwxr-xr-x 1 root root 61 Jan  1  1970 03userscript0002 -> /nix/store/0y91ndjiiy16i9mhvwlf572zgn44fa2b-etc-unnamed-12.10

**ll /nix/store/as1jk3pfb5ldhdfpkd0dqfv01yr15ak1-01nixos-ip-up** gives:
-r-xr-xr-x 1 root root 230 Jan  1  1970 /nix/store/as1jk3pfb5ldhdfpkd0dqfv01yr15ak1-01nixos-ip-up

However, **ll /nix/store/jsydpkqrfbywb20w93f34yzddq9ln2p9-etc-unnamed-12.9** gives:
-r--r--r-- 1 root root 62 Jan  1  1970 /nix/store/jsydpkqrfbywb20w93f34yzddq9ln2p9-etc-unnamed-12.9

The latter does not have the executable flag set. Am I doing or thinking wrong or is it actually wrong?

**Comment by Mic92** [comment]
The script has to be executable in the first place. You can take [`overrideNameserversScript`](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/networkmanager.nix#L59) as an example:

```
overrideNameserversScript = writeScript "02overridedns" ''
# ...
'';
```

The secret source here is to use: `writeScript`

**Comment by mikael-andersson** [comment]
Hmm, sorry, I still do not quite get this.

My scripts are executable and are working fine if I explicitly create symbolic links to them in the dispatcher.d folder.

I thought I could have a complete script ready to just give the path to 'source'. Do I need to define the script's source code in my configuration.nix?

When trying to do in a similar manner as the overrideNameserversScript and uses that as the value for the attribute 'source', I just get:

error: undefined variable ‘overrideTestScript’

I googled a bit but could not find how to solve this.

**Comment by Mic92** [comment]
you can also leave the scripts where they are and use:

```
overrideNameserversScript = writeScript "02overridedns" (builtins.readFile "/path/to/script");
```

**Comment by mikael-andersson** [comment]
Sorry for the late reply.

Do you really mean that I should add my stuff to the existing 02overridedns script? I prefer not to do that since my stuff has nothing to do with DNS.

Anyhow, here is how I solved it. You are very welcome to give me feedback. I suspect there is a simpler way of doing it.

I added this to my configuration.nix
```
{ config, pkgs, lib, ... }:

let
  wwan-upScript = pkgs.writeScript "wwan-up" (builtins.readFile "/home/mikael/Scripts/ModemManager/dispatcher.d/wwan-up");
  wwan-downScript = pkgs.writeScript "wwan-down" (builtins.readFile "/home/mikael/Scripts/ModemManager/dispatcher.d/wwan-down");
in
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];
...
  environment.etc = with config.networking.networkmanager.basePackages; [
    { source = wwan-upScript; target = "NetworkManager/dispatcher.d/wwan-up"; }
    { source = wwan-downScript; target = "NetworkManager/dispatcher.d/wwan-down"; }
  ];
...
```

I could of course have used only one script instead of two. Maybe I will change that.

**Comment by mikael-andersson** [comment]
Hi,

It would be great if you could answer my question, thanks.

Kind regards,

Mikael

**Comment by AttilaVM** [comment]
Hi,

 I a had a similar hardship to setup dispatcher scripts, but modifying mikael-andersson code I solved it in a slightly different way:

Since I am newbie (just switched from Gentoo) please take it with a grain of salt.

```
{ config, pkgs, ... }:

let synergy_dispatcher = (builtins.readFile /etc/nixos/scripts/attila-notebook/dispatchers/synergy_client.sh);
in
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];
...
networking = {
    wireless.enable = false; # disable wpa supplicant in favor of network manager
    networkmanager = {
      enable = true;
      dispatcherScripts = [ { source = synergy_dispatcher; } ];
    };
...
```
It works for me fine.

The effect:
A symbolic link become available at _/run/current-system/etc/NetworkManager/dispatcher.d_
which refers to my script in _/nix/store_
which has the permision: 444 So it is not executable. but still works

And I agree: Extending the included 02overridedns script to "append" other scripts is exactly the same kind of dirty fix, which I never want to do again in my systems, this is the very reason why I switched to NixOS.

**Comment by Mic92** [comment]
Is the issue resolved?

**Comment by mikael-andersson** [comment]
I do not know. Unfortunately I have not been using NixOS for quite a while. Any comments from @AttilaVM who seems to have poked with this most recently?

**Comment by Mic92** [comment]
Looks like he solved it so. So let's close this.
