### ISSUE TITLE
gnupg: unknown trust model 'tofu+pgp'

### ISSUE THREAD

**Issue by rqcy** [NixOS/nixpkgs#21923]
## Issue description

GPG does not recognize option:

    trust-model tofu+pgp

in gpg.conf.

### Steps to reproduce

place "trust-model tofu+pgp" in ~/.gnupg/gpg.conf

and try to use gpg, e.g., gpg2 -d asdf.gpg

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)

nixos-version
16.09.1465.fd1dbe5 (Flounder)

* Nix version: (run `nix-env --version`)

nix-env --version
nix-env (Nix) 1.11.4

* gnupg version

gpg2 --version
gpg (GnuPG) 2.1.15
libgcrypt 1.7.3
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by Mic92** [comment]
Works on nixos unstable. So I suspect your gnupg version is too old.

**Comment by joachifm** [comment]
tofu support was added in 3c104ca71c37b664b4bb62d32c6ffa398e716b18

**Comment by Mic92** [comment]
Is this worth a backport or do we wait until the next release?

**Comment by joachifm** [comment]
It's a fairly old feature, never heard of a downside to enabling it (at least insofar as violating the "stable" contract of not breaking existing configs) so I'm +1 on backporting. cc @globin

**Comment by rqcy** [comment]
> It's a fairly old feature, never heard of a downside to enabling it
> (at least insofar as violating the "stable" contract of not breaking
> existing configs) so I'm +1 on backporting. cc @globin

that would be great!  thanks for consideration!

**Comment by Mic92** [comment]
https://github.com/NixOS/nixpkgs/pull/21924

**Comment by fpletz** [comment]
Fixed by #21924.
