### ISSUE TITLE
rustc darwin broken on hydra

### ISSUE THREAD

**Issue by acowley** [NixOS/nixpkgs#21936]
## Issue description
rustc fails tests on hydra

### Steps to reproduce
The [Hydra build log](http://hydra.nixos.org/build/46497859/nixlog/2)

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by acowley** [comment]
cc @the-kenny

**Comment by Mic92** [comment]
weird, since there is no error message at all.

**Comment by acowley** [comment]
@Mic92 There is a failed test, but it's hard to find in all that output (search for `write_close`). It's similar to two other failing tests that @the-kenny recently disabled to get things working on `darwin`, so I'm hoping he can add this one to the collection. It's something where macOS doesn't always release sockets as quickly as the test expects. Local builds will often work.

**Comment by the-kenny** [comment]
I'll take a look

**Comment by the-kenny** [comment]
Can't find any issue upstream other than https://github.com/rust-lang/rust/pull/28437 (which doesn't seem relevant to us). Pushing a fix that disables this test on darwin in a minute.

**Comment by acowley** [comment]
Thank you for the quick fix!
