### ISSUE TITLE
Plymouth Themes

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixpkgs#219440]
Themes for plymouth boot animations.

**Metadata**

* homepage URL: https://github.com/adi1090x/plymouth-themes
* source URL: https://github.com/adi1090x/plymouth-themes
* license: gpl-3.0
* platforms: unix, linux, darwin, ...

**Comment by zendo** [comment]
https://github.com/NixOS/nixpkgs/pull/215693

**Comment by phpcitizen** [comment]
Thanks, closing.
