### ISSUE TITLE
separateDebugInfo breaks static builds on libs without executables/bin outputs

### ISSUE THREAD

**Issue by symphorien** [NixOS/nixpkgs#219466]
### Describe the bug
If a derivation only outputs non-elf files and static libraries (which is often the case on libraries in pkgsStatic) then setting separateDebugInfo to true will break the build with:
```
error: builder for '/nix/store/kv4ha6bxy6983cpyrsiikdj8d371snix-unibilium-static-x86_64-unknown-linux-musl-2.1.1.drv' failed to produce output path for output 'debug' at '/nix/store/kv4ha6bxy6983cpyrsiikdj8d371snix-unibilium-static-x86_64-unknown-linux-musl-2.1.1.drv.chroot/nix/store/2kxkaxkjckk4hl0kq8gqz8ggl7sbmjsi-unibilium-static-x86_64-unknown-linux-musl-2.1.1-debug'

```
because no elf files were stripped to $debug, so $debug was not created at all.

### Steps To Reproduce
1. edit unibilium to have separateDebugInfo set to true
2. build pkgsStatic.unibilium

### Expected behavior
it builds

### Additional context
See #219400 

I think this only comes up now because for example glib has a bin output, and this is enough to create a debug output even in pkgsStatic.

Reproduced on dcc47fef8bd1e91baeab8fb34a35337ab8f3a3fd (current nixos-unstable-small)

**Comment by vcunat** [comment]
Honestly I'm not even sure what would be the desired result of separate debug info for static libs.

**Comment by symphorien** [comment]
I expect a behavior like on darwin where separate debug info is unsupported: setting separateDebugInfo is a noop: no debug info but the build succeeds. This way we can set separateDebugInfo to true without having to think about darwin/static, and we won't have to edit the set of exceptions in dozens of derivations when the next corner case is discovered.

I see two possibilities:
- have the hook unconditionally `mkdir $debug`.  This has the downside of succeeding on wrappers or derivations without compiled stuff where separateDebugInfo makes no sense on any platform
- have the hook detect the presence of a static lib and `mkdir $debug` in this case.

What do you think?

**Comment by Artturin** [comment]
Add `!stdenv.hostPlatform.isStatic` here https://github.com/NixOS/nixpkgs/blob/df4084e1dd48960102e0d60f64887aa997eabc79/pkgs/stdenv/generic/make-derivation.nix#L174 ?

**Comment by symphorien** [comment]
https://github.com/NixOS/nixpkgs/pull/219683 for solution 2

**Comment by dominikh** [comment]
Related: #18530
