### ISSUE TITLE
Suggestion: expose man pages of temporarily installed (nix-shell) packages

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#21946]
## Issue description

I sometimes use `nix-shell` to test out a package. This way my profile isn't cluttered. Today I noticed that man pages of such packages isn't available. 

nix-shell is also used to setup development environments. Surly it's desirable to have access to the dependencies' man pages there?

It seems like it wouldn't be to hard to build `MANPATH` in `./pkgs/stdenv/generic/setup.sh` similarly to `PATH`. Is it a reason we don't want to do that?

Parent-ish issue: #11499

**Example**

    $ nix-shell -p rofi
    $ man rofi
    No manual entry for rofi
    $ exit
    $ nix-env -iA nixos.rofi
    $ man rofi
    <man page shown>

## Technical details

* System: NixOS: 16.09.1389.d7a3160 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1465.fd1dbe5"

**Comment by vcunat** [comment]
Interestingly, this does work for me, at least in the case of rofi (on 16.09).  Even in a pure shell
```
nix-shell --pure -Q -p rofi -p man -p less
```
(except for the problem that I need to specify `less` explicitly)

**Comment by olejorgenb** [comment]
Aha, I had set `MANPATH` myself to fix  #10572. Unsetting it causes man to use `manpath` (I think) which constructs the correct manpath. (seems check entries in `PATH` to do this)

Thanks

**Comment by LinArcX** [comment]
I have same issue. I'm not on NixOS. i'm on void-linux. and using lorri + direnv. Can't access man pagaes.

**Comment by steve-chavez** [comment]
For now this can be done manually. For example for enabling `openssl` man pages:

```nix
with import(builtins.fetchTarball{
  name = "2024-05-31";
  url = "https://github.com/NixOS/nixpkgs/archive/refs/tags/24.05.tar.gz";
  sha256 = "sha256:1lr1h35prqkd1mkmzriwlpvxcb34kmhc9dnr48gkm8hh089hifmx";
}){};
mkShell {
  shellHook = ''
    export MANPATH=${openssl.man}/share/man:$MANPATH
  '';
}
```

Then doing `man SSL_new` works.
