### ISSUE TITLE
Mono needs mprotect disabled when pax is enabled

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixpkgs#21944]
## Issue description
When `security.grsecurity.enable = true` mono has segfaults.

### Steps to reproduce
```
{
security.grsecurity.enable = true;
services.sonarr.enable = true;
}
```

Deploy/rebuild, sonarr works, then reboot to enable grsec/pax kernel and sonarr will not start.

## Technical details

* System: NixOS: `16.09pre-git (Flounder)`
* Nix version: `1.11.6`
* Nixpkgs version: `16.09pre-git`

**Comment by joachifm** [comment]
The usual workaround is `paxmark m $out/bin/foo`, though ideally you'd patch the software to work correctly with `mprotect()` hardening.

**Comment by Nekroze** [comment]
thanks, I am newish to pax so I appreciate the clarification.

By patching the software do you mean there is something we can do for example in the sonar (or any other mono app) package, or is this something that should be handled by the upstream developers of the application?

Would mono's ahead of time compile perhaps obviate this as it would no longer need to be interpreted by the mono executable? if so perhaps we could do that to resolve this without upstream changes to the software.

**Comment by joachifm** [comment]
Absent build-time configuration to tweak/disable problematic features, patching may be nontrivial. I can't say what it'd involve for mono. PaX is pretty strict about runtime codegen so it's probably more economical to just disable it for the software in question.

It's unfortunate that per-executable PaX protections are usually disabled for stuff that could use it the most (e.g., firefox), but that's just the way of things ... If you care to, you can bug upstream, they'd be better able to advise you.

**Comment by joachifm** [comment]
Ahead of time compile may be what you want, if that avoids runtime codegen/execution.

**Comment by Nekroze** [comment]
sounds like this is not something that should be done to the interpreter then. Will close, thanks.
