### ISSUE TITLE
Update request: openra release-20190314 → release-20230225

### ISSUE THREAD

**Issue by RTUnreal** [NixOS/nixpkgs#219422]
- Package name: openra
- Latest released version: 20230225
- Current version on the unstable channel: 20190314
- Current version on the stable/release channel: 20190314

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@fusion809 @msteen @rardiol

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by mdarocha** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/96600
