### ISSUE TITLE
config.networking.networkmanager.dns conflict

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixpkgs#219438]
### Describe the bug
networking.networkmanager.dns cannot be changed to "none"

```
error: The option `networking.networkmanager.dns' has conflicting definition values:
       - In `/nix/store/<hash>-source/<mysystemname>/system/initsystem/networking.nix': "none"
       - In `/nix/store/<hash>-source/nixos/modules/system/boot/resolved.nix': "systemd-resolved"
```
### Steps To Reproduce
1. set networking.networkmanager.dns = "none";

### Expected behavior
There would be no dns processing.

### Notify maintainers
@teams.freedesktop.members

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.14, NixOS, 22.11 (Raccoon), 22.11.20230302.96e1871`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

**Comment by apfelkuchen6** [comment]
You can always use `networking.networkmanager.dns = lib.mkForce "none";`.

[Apparently](https://developer-old.gnome.org/NetworkManager/stable/NetworkManager.conf.html) network-manager enables the resolved integration by default anyway if resolved is detected, so we can probably drop the line from the resolved module.
