### ISSUE TITLE
Build failure: libliftoff  Project version: 0.5.0-dev

### ISSUE THREAD

**Issue by Costabo1** [NixOS/nixpkgs#219571]
### Steps To Reproduce

1. Trying to use flake.nix to build nixos with hyprland wm for my raberrypi4
2. nixos-rebuild switch --show-trace
### Build log
building the system configuration...
error: builder for '/nix/store/dc175rzn9zfb4zyzy2jhp02qd6sfhzki-libliftoff-0.5.0-dev.drv' failed with exit code 1;
       last 10 log lines:
       > [8/38] Compiling C object example/simple.p/common.c.o
       > FAILED: example/simple.p/common.c.o
       > gcc -Iexample/simple.p -Iexample -I../example -I../include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -Wundef -Wmissing-prototypes -Walloca -Wdeclaration-after-statement -Wfloat-conversion -Wsign-conversion -Wno-missing-braces -Wno-unused-parameter -isystem/nix/store/fk97vrlkp8d1a0xmxwggp4wyraadpp4d-libdrm-2.4.114-dev/include/libdrm -MD -MQ example/simple.p/common.c.o -MF example/simple.p/common.c.o.d -o example/simple.p/common.c.o -c ../example/common.c
       > ../example/common.c: In function 'pick_crtc':
       > ../example/common.c:54:29: error: conversion to 'uint32_t' {aka 'unsigned int'} from 'int' may change the sign of the result [-Werror=sign-conversion]
       >    54 |     if (enc->possible_crtcs & (1 << j)) {
       >       |                             ^
       > cc1: all warnings being treated as errors
       > [9/38] Compiling C object example/simple.p/simple.c.o
       > ninja: build stopped: subcommand failed.
       For full logs, run 'nix log /nix/store/dc175rzn9zfb4zyzy2jhp02qd6sfhzki-libliftoff-0.5.0-dev.drv'.
error: 1 dependencies of derivation '/nix/store/qyz46ddxz1y24lf8lzq51ab3nima2fmb-wlroots-hyprland-hidpi-2023-03-02_5ae17de.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fn9bh09lmvpgabwa0rl52vhn4i4spg28-hyprland-0.22.0+date=2023-03-04_5184b54.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sx4bpmhrn8xw4w87356v87a8ynzvklw5-desktops.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7f71zp0xh5d86flkvdq1swb1d81iyq90-hyprland-0.22.0+date=2023-03-04_5184b54_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/bjh7lgykb9rslhphjawx03mdjhczaq95-hyprland-share-picker-0.pre+date=2023-02-11_2fa7e34.drv' failed to build
error: 1 dependencies of derivation '/nix/store/45y87rym0147azvh96zvcsld47hsvbjw-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1nh4d3z6447pjb7ilxxj3jgagb03hq53-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7lkd5cva2xpaii0ddancmwg1mv52vii1-nixos-system-Nixos-23.05.20230301.a08d697.drv' failed to build
```
log here if short otherwise a link to a gist
```
nix log /nix/store/dc175rzn9zfb4zyzy2jhp02qd6sfhzki-libliftoff-0.5.0-dev.dr
v
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/3n1w0rc8ybp1h83khh2n2b3hbym01dvx-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/lqlckzkvxsvqwjn9c03wjfj7barnnmrn-liblift>
The Meson build system
Version: 1.0.0
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: libliftoff
Project version: 0.5.0-dev
C compiler for the host machine: gcc (gcc 9.5.0 "gcc (GCC) 9.5.0")
C linker for the host machine: gcc ld.bfd 2.40
Host machine cpu family: aarch64
Host machine cpu: aarch64
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Walloca: YES 
Compiler for C supports arguments -Wdeclaration-after-statement: YES 
Compiler for C supports arguments -Wfloat-conversion: YES 
Compiler for C supports arguments -Wsign-conversion: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Found pkg-config: /nix/store/q196iiqlclci29zy8jkpiphmk3l8xwiq-pkg-config-wrapper-0.29.2/bin/pkg-con>
Run-time dependency libdrm found: YES 2.4.114
Build targets in project: 13

libliftoff 0.5.0-dev

  User defined options
    auto_features: enabled
    bindir       : /nix/store/lqlckzkvxsvqwjn9c03wjfj7barnnmrn-libliftoff-0.5.0-dev/bin
    buildtype    : plain
    includedir   : /nix/store/lqlckzkvxsvqwjn9c03wjfj7barnnmrn-libliftoff-0.5.0-dev/include

### Additional context
New to Nixos eco-system, still learning to use flake.nix properly. maybe I missed sth in my  .nix
Any guidance to install hyprland with flake.nix properly will help.

**Comment by kirillrdy** [comment]
@Costabo1 are you able to share configuration in order to reproduce ?

libliftoff from `nixpkgs` is still at 0.3.0

the 0.5.0 version comes from https://github.com/hyprwm/Hyprland/blob/main/flake.nix#L52

so, while version is not official, its possible that its some interaction between nixos module from flake ( I assume flake builds ) and something from nixpkgs

**Comment by Costabo1** [comment]
Thanks for the reply, here is my config files
[https://github.com/Costabo1/Nixos/blob/main/flake_bkup.nix](url)
[https://github.com/Costabo1/Nixos/blob/main/configuration.nix](url)
hopefully, have some guidance how to  properly utilize flake to install hyprland on a pi4 .

**Comment by kirillrdy** [comment]
@Costabo1 thank you for providing configuration.

With this I was able to reproduce the issue.

There are actually 2 issues libliftoff and wlroots don't build on `aarch64-linux` due to C compiler warnings being treated as errors
specifically       "-W-error=sign-conversion" for libliftoff and       "-W-error=maybe-uninitialized" for wlroots

simplest way to reproduce the error is to run on you raberrypi4 
```
nix build github:hyprwm/Hyprland
```

You can/should report this to Hyprland as they seem to support `aarch64-linux` and you can also report this upstream to libliftoff and wlroots, eg for libliftoff similar issue were fixed very recently in https://gitlab.freedesktop.org/emersion/libliftoff/-/commit/25dd6d662e6ee2ef756d3e6d6cf836dad9bdad85

meanwhile as a work around I was able to build Hyperland or aarch64-linux but disabling compile warnings
by adding

```
    env.NIX_CFLAGS_COMPILE = toString [
      "-Wno-error=sign-conversion"
    ];

```
to libliftoff derivation

and
```
    env.NIX_CFLAGS_COMPILE = toString [

      "-Wno-error=maybe-uninitialized"
    ];

```
to wlroots


hopefully this helps,

as for this issue, its not related to nixpkgs

**Comment by Costabo1** [comment]
Thanks for the guidance, still confuse how to disable the compile warnings properly. Should  I add those lines in my  configuration.nix when building libliftoff and wlroots packages or I  need to include them in the output of my flake.nix?

**Comment by kirillrdy** [comment]
@Costabo1 i couldnt find a simple way of overrigin derivation from the flake so just forked it

you can see code here, sorry due to auto formatting, the diff is huge

https://github.com/kirillrdy/Hyprland/tree/aarch64

but you should be able to use it in your configuration just by changing url in you flake inputs

```
hyprland = {
        url = "github:hyprwm/Hyprland";

        inputs.nixpkgs.follows = "nixpkgs";
      };
```
to
```
hyprland = {
        url = "github:kirillrdy/Hyprland/aarch64";

        inputs.nixpkgs.follows = "nixpkgs";
      };
```

you can for that repo so you have your own copy, until you get a better solution from upstream

**Comment by Costabo1** [comment]
@kirillrdy

Thank you for the effort, I try your git repo and able to build  the nixos+ hyprland. However, when I try starting the Hyprland it failed to start because of this error.

[libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory

I have only able to find this error  occurred in sway.
https://www.reddit.com/r/voidlinux/comments/mor7n5/getting_libseat_errors_when_starting_sway/

I try to create an env file  under  user/.config/hypr with the variable=hyprland, still unable to start up.  Any luck you are familiar with this error ?

**Comment by kirillrdy** [comment]
going to close as upstream considered it resolved https://github.com/hyprwm/Hyprland/issues/1733

let us know if its still an issue

**Comment by Costabo1** [comment]
@kirillrdy 
Still having trouble to start up the Hyprland on my pi4. I tried install seatd package and run sudo seatd in the tty terminal. After that I got another error, seem missing some sort of drivers for my set up?

Here is my log

https://github.com/Costabo1/Nixos/blob/main/aarch64_error_log

and when I try start sway, I got these errors:

costabo1@Nixos ~ $ sway Thu Mar 9 20:04:48 2023
00:00:10.024 [wlr] [backend/backend.c:217] Found 0 GPUs, cannot create backend
00:00:10.025 [wlr] [backend/backend.c:390] Failed to open any DRM device
00:00:10.039 [sway/server.c:73] Unable to create backend

**Comment by kirillrdy** [comment]
> @kirillrdy Still having trouble to start up the Hyprland on my pi4. I tried install seatd package and run sudo seatd in the tty terminal. After that I got another error, seem missing some sort of drivers for my set up?
> 
> Here is my log
> 
> https://github.com/Costabo1/Nixos/blob/main/aarch64_error_log
> 
> and when I try start sway, I got these errors:
> 
> costabo1@Nixos ~ $ sway Thu Mar 9 20:04:48 2023 00:00:10.024 [wlr] [backend/backend.c:217] Found 0 GPUs, cannot create backend 00:00:10.025 [wlr] [backend/backend.c:390] Failed to open any DRM device 00:00:10.039 [sway/server.c:73] Unable to create backend

I had a look at wlroots source code, and yes looks it cant find any drm devices

you can check devices 

```
ls -lah /dev/dri/by-path/*
```

**Comment by Costabo1** [comment]
[root@Nixos:~]# ls -lah /dev/dri/by-path/*
ls: /dev/dri/by-path/*: No such file or directory


this is my output. Any ideas how to install a wlroots version works on pi4 hardwares?

**Comment by kirillrdy** [comment]
> [root@Nixos:~]# ls -lah /dev/dri/by-path/* ls: /dev/dri/by-path/*: No such file or directory
> 
> this is my output. Any ideas how to install a wlroots version works on pi4 hardwares?

I think this means its not the issue with wlroots, but indeed something wrong with drivers or udev Have you tried non nixos distro ?

I dont have experience with raspberrypi, but if you have a working versions with non nixos, then we can try to figure out the difference
