### ISSUE TITLE
R's Sweave.sty not accessible to texlive

### ISSUE THREAD

**Issue by Hodapp87** [NixOS/nixpkgs#21952]
## Issue description

The R package in nixpkgs produces the directory `lib/R/share/texmf/tex/latex/` which has files like `Sweave.sty`. These files (to my knowledge) serve only to allow LaTeX to use the `.tex` files which Sweave produces - but texlive can't exactly find them.

I would solve this myself but I don't yet know Nix well enough. If anyone could point to any packages that solve a similar problem, that would help.

### Steps to reproduce

Install `R` and `texlive.combined.scheme-full` (other texlive packages may work similarly). Save the below as `example.Rnw`:

```latex
\documentclass{article}
\begin{document}
<<>>=
print("foo")
@ 
\end{document}
```

Then run:

    R CMD Sweave example.Rnw
    latex example.tex

latex will halt with:

    ! LaTeX Error: File `Sweave.sty' not found.

This has a somewhat kludgey workaround in the form of instead running something like:

    TEXINPUTS=".:/nix/store/i8cbhc7q0l1lkq3ynzxx0q5dh4s3dmd1-R-3.2.3/lib/R/share/texmf/tex/latex:" latex example.tex

## Technical details

* System: 16.09.1324.1dd0fb6 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1324.1dd0fb6"

**Comment by Mic92** [comment]
Did you try to create a texlive variant which includes R?

```
environment.systemPackages = [
  (pkgs.texlive.combine {                                                                                                                                                          
     inherit (pkgs.texlive) scheme-basic;
     inherit (pkgs) R;
  })
];    
```

**Comment by Hodapp87** [comment]
Did you try this? This might be a novice error, but from that I am only able to get:

    error: attribute ‘pkgs’ missing, at /nix/store/2jr0yrapv1j4igmgai0nhddg9naqggg7-nixos-16.09.1229.f52eaf4/nixos/pkgs/tools/typesetting/tex/texlive/default.nix:158:33

**Comment by Mic92** [comment]
The code I posted was not correct. The following at least compile. However I did not check the actually functionality: https://github.com/Mic92/nixpkgs/commit/8b65b516d097ab562958d09d64b44f39e2101456
If works for you, feel free to submit a pull request.

**Comment by vcunat** [comment]
That won't work by itself, as `texlive` expects `share/texmf` contents directly in the root of the package.

**Comment by Mic92** [comment]
mhm. Adding a symlink in the package or a split package might help here.

**Comment by Mic92** [comment]
(sorry hit the wrong button)

**Comment by vcunat** [comment]
Yes, it might work to have a simple symlink package with the additional attributes from your commit (i.e. without changing R altogether).

**Comment by Hodapp87** [comment]
By that, do you mean symlinking `lib/R/share/texmf` to `share/texmf` in R's root?

**Comment by vcunat** [comment]
No, creating a simple wrapper "package" that only contains that symlink and those attributes.

**Comment by Hodapp87** [comment]
Does texlive run through a wrapper? Would it be any simpler to optionally modify that wrapper to include R's LaTeX dependencies in one of the environment variables that texlive uses?

**Comment by vcunat** [comment]
`texlive.combine` is a huge wrapper-builder that aggregates all the packages passed to it (and adds lots of magic to make it all work together, mostly).  I do **not** think that changing it directly would be easier.

**Comment by erromerom** [comment]
Start R with administrator privileges.
library("tinytex")
r_texmf(action = "add")
