### ISSUE TITLE
slim changes session type to "xterm" after an failed login attempt

### ISSUE THREAD

**Issue by kierdavis** [NixOS/nixpkgs#21958]
## Issue description

When logging in with slim, if I entered my password correctly the first time, i3 is started as expected. If not, xterm appears to be started instead.

After doing some research I came across #4300, where it almost seems like the *opposite* problem is occurring (the user's desired display/window manager only starts if the password was entered incorrectly at least one).

I then tried again and I was indeed able to see that the session type that slim will use after login changed from the default and desired "none + i3" to be completely blank. Pressing F1 at this point allowed me to cycle it through "xterm", "xterm + i3" and back to "none + i3". (On a somewhat unrelated note, I would probably have noticed this earlier if the default styling for this text wasn't "white on almost-white").

### Steps to reproduce

1. Set up a VM as follows:

```bash
git clone https://github.com/NixOS/nixpkgs
cat >configuration.nix <<EOF
{
  users.mutableUsers = false;
  users.users.root.password = "root";
  users.users.test.password = "test";
  users.users.test.isNormalUser = true;
  services.xserver.enable = true;
  services.xserver.windowManager.i3.enable = true;
}
EOF
nixos-rebuild build-vm -I nixpkgs=./nixpkgs -I nixos-config=./configuration.nix
result/bin/run-nixos-vm
```

2. Log in to VM as user "test", password "test". The i3 window manager starts up.
3. Close and restart the VM.
4. Log in using any credentials other than test/test or root/root. The login attempt will be denied by slim. The session type changes from "none + i3" to "".
5. Log in as user "test", password "test". User is logged in and xterm is started.

## Technical details

* System: NixOS 17.03.git.3ab26fd (Gorilla) [nixpkgs master, as of time of writing]
* Nix version: 1.11.6
* Nixpkgs version: 17.03.git.3ab26fdb70 [master, as of time of writing]

**Comment by kierdavis** [comment]
The aforementioned issue, #4300, suggests adding

```nix
services.xserver.desktopManager.xterm.enable = false;
```

to `configuration.nix` to work around their problem.

When I tried this, `xterm` was indeed removed from the list of alternative session types I could switch between by pressing F1. However, if I didn't press F1 after failing a login, the session type is still left blank, and attempted to log in like this causes the X server to immediately restart. No error messages are produced in the journal, so presumably its doing something along the lines of running an empty session script, which of course terminates immediately.

**Comment by danbst** [comment]
I was bitten by this too.

But the real solution **should be** not to use SLiM as default DM, according to NixOS deprecation policies. [SLiM is discontinued](https://www.reddit.com/r/linux/comments/2hc72g/anyone_know_what_happened_to_the_slim_display/)

I remember there already was a discussion about switching default DM, but I don't remember what was proposed instead. 

Maybe SDDM?

**Comment by vcunat** [comment]
LightDM as well; see https://github.com/NixOS/nixpkgs/issues/12516  I think that (additional) closure size is one of the main concerns for the default.

**Comment by kierdavis** [comment]
SLiM is no longer NixOS's default display manager, and the SLiM project looks pretty dead now, so I think this issue can be closed.
