### ISSUE TITLE
Build failure: openjdk (staging-next, aarch64-linux)

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#219513]
### Steps To Reproduce

1. build *openjdk* (or any version from 11 to 19; 8 is not affected)

### Build log

https://hydra.nixos.org/build/211484263/nixlog/4

### Additional context

The expression

```nix
  buildFlags = [ "images" ];
```

translates to `make SHELL=$SHELL images`, which mysteriously fails; while the expression

```nix
  buildPhase = ''
    runHook preBuild

    make images

    runHook postBuild
  '';
```

works fine.

### Notify maintainers

#219444

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.2.0, NixOS, 23.05 (Stoat), 23.05.20230222.988cc95`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by mweinelt** [comment]
Already running a bisect, since openjdk maintenance is problematic.

**Comment by mweinelt** [comment]
Bisected to

```
87bfed87336d693fcf2de10c9a1861ea4d6ca6ae is the first bad commit
commit 87bfed87336d693fcf2de10c9a1861ea4d6ca6ae
Merge: 44fd51cd47a1 945ff62ef890
Author: Sergei Trofimovich <slyich@gmail.com>
Date:   Thu Mar 2 21:44:27 2023 +0000

    Merge pull request #218582 from trofi/gnumake-update
    
    gnumake: 4.4 -> 4.4.1

 pkgs/development/tools/build-managers/gnumake/default.nix | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

cc @trofi

**Comment by trofi** [comment]
Thank you! Looking. Probably an environment preservation behaviour change in `4.4 -> 4.4.1`. One of these two:

```
* WARNING: Backward-incompatibility!
  In previous releases it was not well-defined when updates to MAKEFLAGS made
  inside a makefile would be visible.  This release ensures they are visible
  immediately, even when invoking $(shell ...) functions.  Also, command line
  variable assignments are now always present in MAKEFLAGS, even when parsing
  makefiles.
  Implementation provided by Dmitry Goncharov <dgoncharov@users.sf.net>

* Previously target-specific variables would inherit their "export" capability
  from parent target-specific variables even if they were marked private.  Now
  private parent target-specific variables have no affect.  For more details
  see https://savannah.gnu.org/bugs/index.php?61463
```

I'll spend a few minutes reproducing and will likely reintroduce `gnumake-4.4` just for openjdk to workaround (unless opekjdk already fixed it).

**Comment by trofi** [comment]
Proposed `gnumake44` pin as https://github.com/NixOS/nixpkgs/pull/219579

**Comment by trofi** [comment]
Bisected `gnumake` change down to https://git.savannah.gnu.org/cgit/make.git/commit/?id=dc2d963989b96161472b2cd38cef5d1f4851ea34 `[SV 63347] Always add command line variable assignments to MAKEFLAG`. It's an intentional change: https://savannah.gnu.org/bugs/?63347

I'll try to find where `openjdk` relies on missing variables and report the bug there.

**Comment by trofi** [comment]
Ended up being an openjdk build system bug.

Proposed the fix to `jdk` upstream as https://github.com/openjdk/jdk/pull/12992

**Comment by trofi** [comment]
And proposed the swith back to `gnumake-4.4.1` in `nixpkgs` as https://github.com/NixOS/nixpkgs/pull/220821
