### ISSUE TITLE
nixos-rebuild switch produces warnings about systemd-udev-settle service

### ISSUE THREAD

**Issue by bennofs** [NixOS/nixpkgs#21954]
## Issue description

When running `nixos-rebuild switch`, sometimes `systemd-udev-settle` fails to start with an error message:

```
$ systemctl status systemd-udev-settle
● systemd-udev-settle.service - udev Wait for Complete Device Initialization
   Loaded: loaded (/nix/store/qzvya9kh5wh3bkcryd3g14xax48i1klc-systemd-231/example/systemd/system/systemd-udev-settle.s
   Active: failed (Result: exit-code) since Tue 2017-01-17 17:35:55 CET; 53min ago
     Docs: man:udev(7)
           man:systemd-udevd.service(8)
  Process: 3392 ExecStart=/nix/store/qzvya9kh5wh3bkcryd3g14xax48i1klc-systemd-231/bin/udevadm settle (code=exited, stat
 Main PID: 3392 (code=exited, status=1/FAILURE)

Jan 17 17:33:54 c-cube systemd[1]: Starting udev Wait for Complete Device Initialization...
Jan 17 17:35:55 c-cube systemd[1]: systemd-udev-settle.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 17:35:55 c-cube systemd[1]: Failed to start udev Wait for Complete Device Initialization.
Jan 17 17:35:55 c-cube systemd[1]: systemd-udev-settle.service: Unit entered failed state.
Jan 17 17:35:55 c-cube systemd[1]: systemd-udev-settle.service: Failed with result 'exit-code'.
```

### Steps to reproduce

Run `nixos-rebuild switch`

## Technical details

* System: NixOS: `17.03.git.f673243aff (Gorilla)`
* Nix version: `nix-env (Nix) 1.11.5`
* Nixpkgs version: `17.03.git.f673243aff`

**Comment by Mic92** [comment]
I can confirm this issue. It also delays starting of other units (probably dependent services).

I do:

```
$ systemctl stop systemd-udev-settle.service
```

as a workaround when this happens, so that the other services can restart faster.
It only happens on my physical machine. My v-server never had this problem.

**Comment by ocharles** [comment]
Can confirm this is still happens on 17.09 (just happened right now, and has been happening on every single `switch`).

**Comment by Mic92** [comment]
My workaround is to use:

```
systemd.service.systemd-udev-settle.serviceConfig.ExecStart = "${pkgs.coreutils}/bin/true";
```

**Comment by qrilka** [comment]
@Mic92 how do you specify that? I get:
```
error: The option `systemd.service' defined in `/etc/nixos/configuration.nix' does not exist.
```

**Comment by Mic92** [comment]
there was a typo:

```diff
- systemd.service.systemd-udev-settle.serviceConfig.ExecStart = "${pkgs.coreutils}/bin/true";
+ systemd.services.systemd-udev-settle.serviceConfig.ExecStart = "${pkgs.coreutils}/bin/true";
```

**Comment by chrissound** [comment]
The solution posted above https://github.com/NixOS/nixpkgs/issues/21954#issuecomment-367984759 no longer seems to work after upgrading to 18.09 - has anyone else solved this in a different way?

**Comment by chrissound** [comment]
Ran into this issue when  I didn't have the EFI boot partition mounted while rebuilding. I think I was starting up an old nixos configuration. Seems to work fine now.

**Comment by Mic92** [comment]
@chrissound I forgot to make it a list. The empty string makes systemd first resets the option so it can be overriden afterwards.

**Comment by Mic92** [comment]
A potential fix is also here:
https://github.com/NixOS/nixpkgs/pull/53446

I want to test this option a bit for myself first.
