### ISSUE TITLE
Ruby source checksum mismatch on OS X

### ISSUE THREAD

**Issue by duane** [NixOS/nixpkgs#21963]
## Issue description

Cannot install ruby 2_2_5

### Steps to reproduce
    nix-env -i ruby-2.2.5 
    ...
    building path(s) ‘/nix/store/mkd1xgqvrjmc1xmx9jcmbwdr5028h70y-CF-osx-10.9.5’
    cannot build derivation ‘/nix/store/c4wb04p6bbsbm8bhhmajvkb10k2qk70n-eap8021x-osx-10.11.6.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/jasgqiasg77xxzmhl2g1kxphxpgfbj6m-configd-osx-10.8.5.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/k7mqqnbf75r90azml1a5hqlcwdnwi288-python-boot-2.7.12.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/kjvblcfrbi82mh27nrjc8863fan16h93-llvm-3.7.1.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/cnk34na38g7r74lgbbnk1qm30vdik6mp-stdenv-darwin.drv’: 1 dependencies couldn't be built
    killing process 72876
    cannot build derivation ‘/nix/store/xh33z7b3dkw5gsq3x5j9jjd3y03s12di-stdenv-darwin.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/da4iwi8s3p9ahq445jgkb7gzl7pfsg8x-ruby-2.2.5.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/da4iwi8s3p9ahq445jgkb7gzl7pfsg8x-ruby-2.2.5.drv’ failed

I'm guessing either a) the hash is just flat out wrong or b) apple updated their source without updating the version. Either way, it leaves me unable to use nix to build any software on my computer.

## Technical details

* System: mac os 10.12.2
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 2723b3b0dac5fdd0f01dd6fd3a8920e5ec2ce6ae

**Comment by Mic92** [comment]
what is the commit of `nixpkgs` you currently have checked out?

```
$ git rev-parse HEAD
```

**Comment by duane** [comment]
@mic92 (also update original post): 2723b3b0dac5fdd0f01dd6fd3a8920e5ec2ce6ae

**Comment by Mic92** [comment]
@duane can you include the lines with the checksum error again.

**Comment by LnL7** [comment]
I was preparing this here https://github.com/LnL7/nixpkgs/commit/baf28d386e8b153af2de7d270773f171e4237779, but the build ran into another issue http://hydra.nixos.org/jobset/nixpkgs/lnl7-wip

**Comment by LnL7** [comment]
@dduane You can run `nix-store -r  /nix/store/hg5533ivmhyf0ilbq5zprfkz9fk2916c-eap8021x-222.40.1.tar.gz` as a temporary workaround.

**Comment by matthewbauer** [comment]
@LnL7 
>I was preparing this here LnL7@baf28d3, but the build ran into another issue. http://hydra.nixos.org/eval/1322731?compare=trunk

I've had the same issue on my MacBook. Setting libuv.doCheck = false seems to fix it. Can't find anything online about it though.

**Comment by duane** [comment]
@LnL7, @matthewbauer, thanks much!

@Mic92, I'll update later this week with logs; I've since lost them.

**Comment by Mic92** [comment]
@duane not needed, other people seem to have the same problem. Although I probably cannot reproduce this problem on linux.

**Comment by LnL7** [comment]
Sorry for the delay, I couldn't reproduce it myself and a darwin rebuild takes some time on hydra.

- [libuv](http://hydra.nixos.org/eval/1325203?filter=libuv&compare=1325111)
- [ruby_2_2](http://hydra.nixos.org/eval/1325203?filter=ruby_2_2&compare=1325111&full=#tabs-still-succeed)
