### ISSUE TITLE
Package request: Godot 4 Export Template

### ISSUE THREAD

**Issue by tengkuizdihar** [NixOS/nixpkgs#219635]
**Project description**

Godot 4, but only the export template. I think this would be beneficial because Godot 3 already has one and it could be used to build other Godot based Games.

**Metadata**

* homepage URL: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_linuxbsd.html#building-export-templates
* source URL: https://github.com/godotengine/godot
* license: MIT
* platforms: linux

**Comment by tengkuizdihar** [comment]
I think just doing 
```nix
{ godot, lib }:

# https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#building-export-templates
godot.overrideAttrs (oldAttrs: rec {
  pname = "godot_4_export_templates";
  sconsFlags = "platform=linuxbsd target=template_debug arch=x86_64";
  installPhase = ''
    # The godot export command expects the export templates at
    mkdir -p "$out/share/godot/templates/${oldAttrs.version}.stable"
    cp bin/godot.x11.opt.64 $out/share/godot/templates/${oldAttrs.version}.stable/linux_x11_64_release
  '';
  outputs = [ "out" ];
  meta.description = "Free and Open Source 2D and 3D game engine (export templates)";
})
```

I wonder how to customize the `arch` flag though, like detecting the architecture in nix.
CC: @Twey @shiryel

**Comment by shiryel** [comment]
If I'm not mistaken, the type of template depends on the `platform` value, and it would be nice to have templates for platforms like JavaScript, Android, macOS, etc...

We could do something similar to how the `sconsFlags` is configured on godot_4 derivation, it would also allow the customization of the `arch` flag.

**Comment by davidak** [comment]
> I wonder how to customize the `arch` flag though, like detecting the architecture in nix.

Something like `stdenv.hostPlatform.system` might help.

https://github.com/NixOS/nixpkgs/pull/218203/files#diff-182f3778f2f45f888846cdc1c0f7886d9b31dee98901373a03e958341255dd80L11
https://nixos.org/manual/nixpkgs/stable/#ssec-cross-platform-parameters

But can't the build system detect the arch?

**Comment by kgullion** [comment]
looks like export-templates for godot4 was added here https://github.com/NixOS/nixpkgs/pull/305118
