### ISSUE TITLE
Package request: nwjs-bin and nwjs-ffmpeg-prebuilt

### ISSUE THREAD

**Issue by bayazidbh** [NixOS/nixpkgs#219662]
**Project description**

NW.js is an app runtime based on Chromium and node.js. You can write native apps in HTML and JavaScript with NW.js. It also lets you call Node.js modules directly from the DOM and enables a new way of writing native applications with all Web technologies. It was created in the Intel Open Source Technology Center.

Also used in the game engines RPG Maker MV and MZ, in some cases running the game with a native nwjs can provide better compatibility and performance.

nwjs-ffmpeg-prebuilt provides additional prebuilt binaries of proprietary codecs for nw.js from ffmpeg.

(note: there is also an [nwjs and nwjs-sdk](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=nwjs) in nixpkgs, but it seems to be quite outdated as the latest version is 0.73, should I also create an outdated package report?)

**Metadata**

* **NW.js**
  * homepage URL: https://nwjs.io/
  * source URL: https://github.com/nwjs/nw.js
  * license: [MIT](https://github.com/nwjs/nw.js/blob/nw73/LICENSE)
  * platforms: [linux, macos](https://github.com/nwjs/nw.js#downloads)
  * AUR Link: https://aur.archlinux.org/packages/nwjs-bin

* **NW.js**
  * homepage URL: https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt
  * source URL: https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt
  * license: [GPL-2.0 license](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/blob/master/LICENSE)
  * platforms: [linux, macos](https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt#specific-guides)
  * AUR Link: https://aur.archlinux.org/packages/nwjs-ffmpeg-codecs-bin

**Comment by ilya-epifanov** [comment]
@bayazidbh I think this issue can be closed now that we have `nwjs` and `nwjs-ffmpeg-prebuilt`
