### ISSUE TITLE
Package request: libglib

### ISSUE THREAD

**Issue by Karvp** [NixOS/nixpkgs#219672]
**Project description**

Libglib library provides core application building blocks for Linux and other Unix-like systems.

**Metadata**

homepage URL: https://developer.gnome.org/glib/
source URL: https://download.gnome.org/sources/glib/2.70/glib-2.70.1.tar.xz
license: lgpl21Plus
platforms: Unix, Linux, darwin

**Comment by figsoda** [comment]
glib is already packaged in nixpkgs
https://github.com/NixOS/nixpkgs/blob/794f34657e066a5e8cc4bb34491fee02240c6ac4/pkgs/development/libraries/glib/default.nix#L58
