### ISSUE TITLE
[tor-browser] Proxy server refusing connections

### ISSUE THREAD

**Issue by a12l** [NixOS/nixpkgs#219750]
### Describe the bug

When you try to connect to the Tor network using the Tor browser you get the error message

![Tor error](https://user-images.githubusercontent.com/38804798/222985085-41f1a663-faca-4175-8e9e-943a1a876117.png)

When you try to visit a website after being shown the big red error message your get the error message

![tor_proxy error](https://user-images.githubusercontent.com/38804798/222985219-693da2a5-284d-4e89-b15b-b5df9bf212d1.png)

This problem appeared between one and two weeks ago. [Elserjo on the Discourse forum reported this issue eight days ago](https://discourse.nixos.org/t/tor-browser-crash/25799); can't find an existing Nixpkgs issue.

### Steps To Reproduce
1. Install the Tor browser from Nixpkgs
2. Start the Tor browser
3. Click on `Connect`
4. Read error message
5. Try to go to a website

### Expected behavior

When clicking on `Connect` the browser should connect to the Tor network and be able to browse.

#### Troubleshooting

The [Tor project has a troubleshooting guide on their website](https://tb-manual.torproject.org/troubleshooting/).

1. The browsers says that it can detect my internet connection.

![troubleshooting](https://user-images.githubusercontent.com/38804798/222985771-0b5bb82b-2f85-46fe-a058-d8c0e6569153.png)

2. The Tor logs doesn't seem to indicate any problems (from what I can interpret)

```
2023-03-05 20:53:12.260 [NOTICE] New control connection opened.
2023-03-05 20:53:12.260 [NOTICE] New control connection opened.
2023-03-05 20:53:12.266 [NOTICE] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
2023-03-05 20:53:13.209 [NOTICE] Opening Socks listener on /run/user/1000/Tor/socks.socket
2023-03-05 20:53:13.210 [NOTICE] Opened Socks listener connection (ready) on /run/user/1000/Tor/socks.socket
2023-03-05 20:53:13.281 [NOTICE] Bootstrapped 5% (conn): Connecting to a relay
2023-03-05 20:53:13.300 [NOTICE] Bootstrapped 10% (conn_done): Connected to a relay
2023-03-05 20:53:13.365 [NOTICE] Bootstrapped 14% (handshake): Handshaking with a relay
2023-03-05 20:53:13.500 [NOTICE] Bootstrapped 15% (handshake_done): Handshake with a relay done
2023-03-05 20:53:13.502 [NOTICE] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
2023-03-05 20:53:13.505 [NOTICE] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
2023-03-05 20:53:13.507 [NOTICE] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
2023-03-05 20:53:14.818 [NOTICE] Bootstrapped 100% (done): Done
2023-03-05 20:53:14.997 [NOTICE] New control connection opened.
2023-03-05 20:53:26.299 [NOTICE] New control connection opened.
```

I live in Sweden and this issue has appeared both when I've connected to the internet using my home connection (Sunet) and when I've connected over a VPN. I.e. no fuckery by an oppressive government.

The timeline match up-ish with when #217407 would have become available in the binary caches. Unsure if the error appeared before or after updating around that time.

After checking the original PR I see that this problem was noticed, but a workaround was applied. Doesn't seem to work for me :-/

The `network.proxy.socks` value is `127.0.0.1` for me. I'm using root  on tmpfs, and nothing under `/run` is persistently saved between boots.

![network proxy socks](https://user-images.githubusercontent.com/38804798/222986955-a0f8bf1e-7a5f-4126-891e-8b59883fd661.png)

### Notify maintainers

@offline @matejc @thoughtpolice @joachifm @hax404 @KarlJoad

@panicgh and @SuperSandro2000 because you seem to have actually researched the problem.

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.95, NixOS, 22.11 (Raccoon)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

The system is fully up-to-date as of 2023-03-05 22:15 CEST.

**Comment by SuperSandro2000** [comment]
> When you try to visit a website after being shown the big red error message your get the error message

The red error message indicates that Tor cannot find the tor socket. Everything else is bound to not work unless it goes over the normal internet.

Please see https://github.com/NixOS/nixpkgs/pull/205463#issuecomment-1345749870 and https://github.com/NixOS/nixpkgs/pull/205463#issuecomment-1436064480 for the underlying problem  and please check if the firefox setting points to the right socket file.

**Comment by a12l** [comment]
> > When you try to visit a website after being shown the big red error message your get the error message
> 
> The red error message indicates that Tor cannot find the tor socket. Everything else is bound to not work unless it goes over the normal internet.
> 
> Please see [#205463 (comment)](https://github.com/NixOS/nixpkgs/pull/205463#issuecomment-1345749870) and [#205463 (comment)](https://github.com/NixOS/nixpkgs/pull/205463#issuecomment-1436064480) for the underlying problem and please check if the firefox setting points to the right socket file.

```console
$ ls  /run/user/1000/
bus  dbus-1  dconf  env-vars  podman  pulse  ssh-agent  systemd  Tor

$ ls  /run/user/1000/Tor/
[empty]
```

I tested to set `network.proxy.socks` to  `/run/user/1000/Tor/`, but that didn't help.

**Comment by a12l** [comment]
Setting `network.proxy.socks` to `file:///run/user/1000/Tor` also doesn't work.

**Comment by panicgh** [comment]
Just to avoid ambiguities,  did you set `network.proxy.socks` to `file:///run/user/1000/Tor/socks.socket` (with **socks.socket** file name part)?

TBB is still working fine for me with the workaround.

> nothing under /run is persistently saved between boots.

Likewise for me, `/run/user/1000` is a tmpfs.

Have you modified (and forgotten about it) your torrc, e.g. to use a different control port/mechanism?

**Comment by a12l** [comment]
> Just to avoid ambiguities, did you set `network.proxy.socks` to `file:///run/user/1000/Tor/socks.socket` (with **socks.socket** file name part)?

That did it! I missed that you should specify the `socks.socket` file in the path.

```console
$ echo $XDG_SESSION_TYPE
x11
```
I'm using AwesomeWM.

**Comment by panicgh** [comment]
The person on [Discourse[(https://discourse.nixos.org/t/tor-browser-crash/25799/4) had the same problem and the same solution :-)

**Comment by a12l** [comment]
Why did you close this issue @panicgh? You can't seriously think that this temporary workaround is an acceptable permanent solution to this problem? While we still don't have a permanent solution, it should be as easy as possible for users to find information about this workaround. By closing this issue we signal to people that this problem has been solved. And people currently experiencing this problem on a fully up-to-date system will probably not think about looking into closed issues, because the issue is still there.

**Comment by schuelermine** [comment]
I am also experiencing this issue. The fix worked for me.

**Comment by ahen666** [comment]
Confirmed. The issue is still present. Default installed value of network.proxy.socks is 127.0.0.1. Changing it to file:///run/user/1000/Tor/socks.socket resolves the problem.

**Comment by felschr** [comment]
This issue only started happening on my machine after deleting `~/.local/share/tor-browser` today.

**Comment by javier-fuentes** [comment]
Still an issue. I'm using TBB with firejail and I have to apply the workaround at every restart. TBB creates the _~/.tor-browser/_ folder but not a profile inside (this wouldn't be a problem for me if connection works).

_about:config_ and then make _network.proxy.socks_ = _file:///run/user/1000/Tor/socks.socket_

tor-browser-bundle-bin 12.0.5
firejail-0.9.72
nixos-unstable

**Comment by uri3643** [comment]
By default, the service runs on port 9050 and the control port on 9051. This is configured in the torrc file:
https://github.com/torproject/tor/blob/main/src/config/torrc.sample.in

Your firewall may be blocking some of these ports bound by default to localhost which normally point to 127.0.0.1

**Comment by felschr** [comment]
The PR for Tor Browser 13 removes the current workaround again, because it seems the issue was fixed upstream:
https://github.com/NixOS/nixpkgs/pull/256934

I would be grateful if some of you could give this a try and report if it's still working (or working again).
