### ISSUE TITLE
Why is there both an `intel-gpu-tools` and an `xorg.intelgputools`?

### ISSUE THREAD

**Issue by glaebhoerl** [NixOS/nixpkgs#21976]
## Issue description

Both of these exist in master:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/default.nix#L605
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/intel-gpu-tools/default.nix

Is there a reason for it? As far as I can tell they seem to be the same software.

**Comment by vcunat** [comment]
Probably not.  @pSub: I guess the separate expression is easier for you to maintain so the xorg version should be removed?

**Comment by pSub** [comment]
Yes the separate expression is easier to maintain. In fact I wasn't are of the expression in xorg. I've created #21979 to remove xorg.intelgputools.
