### ISSUE TITLE
Update request: swt: 4.5→ 4.33

### ISSUE THREAD

**Issue by deftdawg** [NixOS/nixpkgs#219771]
- Package name: swt
- Latest released version: 4.33

- Current version on the unstable channel: 4.5
- Current version on the stable/release channel: 4.5

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

Link to upstream download page: https://download.eclipse.org/eclipse/downloads/index.html#Latest_Release

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

The swt package (which dates from 2015) no longer works with Gtk2 shipped in NixPkgs as it 21 point releases behind being current:
```
***WARNING: GTK+ version too new (major mismatch)
***WARNING: SWT requires GTK 2.18.0
***WARNING: Detected: 2.24.33
```

**Comment by IndeedNotJames** [comment]
cc @bb010g (maintainer of that package)

**Comment by daniel-sampliner** [comment]
I hit this issue while trying to build  https://github.com/BiglySoftware/BiglyBT, so I took a crack at updating to the latest SWT version [here](https://github.com/NixOS/nixpkgs/compare/master...daniel-sampliner:swt-4-27).

This seems to work for my purposes (in that BiglyBT builds and the entire UI appears functional), however there is a a conflict with trying to merge that back in. A couple of packages are relying on a jdk8 build of SWT, however SWT has not supported jdk8 [for a couple years](https://github.com/eclipse-platform/eclipse.platform.swt/commit/a5bcf2d76d3440a0bb5745054f89b191d3228c98); attempting to use jdk8 causes the build to fail:
```
     [exec] Building GTK3 bindings:
     [exec] gcc  -DSWT_VERSION=4958r2    -DLINUX -DGTK -I/nix/store/4agh2lx6ggpp5g3zl9a2w5a0h0a78nwy-openjdk-8u352-ga/lib/openjdk/include -I/nix/store/4agh2lx6ggpp5g3zl9>
     [exec] *** GTK3 Build failed, aborting further actions..
     [exec] swt.c: In function 'JNI_OnLoad':
     [exec] swt.c:24:16: error: 'JNI_VERSION_10' undeclared (first use in this function); did you mean 'JNI_VERSION_1_6'?
     [exec]    24 |         return JNI_VERSION_10;
     [exec]       |                ^~~~~~~~~~~~~~
     [exec]       |                JNI_VERSION_1_6
     [exec] swt.c:24:16: note: each undeclared identifier is reported only once for each function it appears in
     [exec] make: *** [make_linux.mak:142: swt.o] Error 1
```

The packages relying on swt_jdk8 appear to be:

* [tuxguitar](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L34885)
* [areca](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L38882)

I'll try to take a look at them to see if they can use newer jdk/SWT without much hassle.

**Comment by raspher** [comment]
@daniel-sampliner AFAIK BiglyBt relies on it's own jars of swt which are in their git repo for each architecture they support. It's from their ReadMe

Please correct me if i'm wrong, BiglyBt package is one i definitely want in NixOs

**Comment by doronbehar** [comment]
This issue is bothering me too, more details in https://github.com/NixOS/nixpkgs/issues/340048#issuecomment-2395558967 .

**Comment by doronbehar** [comment]
While trying to investigate why we don't update swt, I all of a sudden found this old attempt: 

- https://github.com/NixOS/nixpkgs/pull/75609 

I managed to update it also today, and it wasn't so hard. However, I wasn't sure if the `swt.jar` file and the shared objects are actually functional after the update, so I wanted to see if a the dependent packages work with the new swt. Apparently, some packages that seem to depend on swt don't really use or need it, and some other packages don't actually launch with or without the update, so I marked them as broken, and even tuxguitar is now updated and works with the new swt :tada:. All changes are available here:

- https://github.com/NixOS/nixpkgs/pull/347022

**Comment by doronbehar** [comment]
Update to 4.34 is available at:

- https://github.com/NixOS/nixpkgs/pull/371498

If anyone is interested.
