### ISSUE TITLE
mesa: intel vulkan driver not built for 32 bit

### ISSUE THREAD

**Issue by L911P** [NixOS/nixpkgs#219799]
### Describe the bug
The driver isnt being built. There's no libvulkan_intel.so nor libvulkan_intel_hasvk.so in /run/opengl-driver-32/lib/

### Steps To Reproduce
1. Enable gpu support
2. Use an Intel iGPU
3. 32bit games/software that use vulkan use llvmpipe.

### Expected behavior
32bit vulkan on intel gpus should work

### Notify maintainers

@vcunat 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.2-zen1, NixOS, 23.05 (Stoat), 23.05pre460365.3c5319ad3aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(l911p): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by vcunat** [comment]
You could already test https://github.com/NixOS/nixpkgs/pull/219802

**Comment by vcunat** [comment]
Should be solved.  You can watch progress at https://nixpk.gs/pr-tracker.html?pr=219802
