### ISSUE TITLE
Packaging request: nodePackages.prettierd

### ISSUE THREAD

**Issue by jay-aye-see-kay** [NixOS/nixpkgs#219761]
A similar project to [prettier_d_slim](https://github.com/mikew/prettier_d_slim) which is packaged already, that seems to be more active

**Project description**

prettier, as a daemon, for improved formatting speed.

**Metadata**

* homepage URL: https://github.com/fsouza/prettierd
* source URL: https://github.com/fsouza/prettierd
* license: ISC
* platforms: all

**Comment by dotlambda** [comment]
> do you think the project could add a package-lock.json ?

It already has a `yarn.lock` That can be used in combination with `fetchYarnDeps`.

**Comment by linsui** [comment]
I'm confused. I thought this prettierd has been added in https://github.com/NixOS/nixpkgs/pull/241339 but you are talking about repackaging it with buildNpmPackage which requires upsteam changes? Am I miss something?

**Comment by dotlambda** [comment]
Oh I didn't see that. In that case this issue can be closed.
@jay-aye-see-kay If you want you can make an issue adding `nodePackages.prettierd` as an alias.
