### ISSUE TITLE
sgdisk crashes with segmentation fault, can't create partition in GNOME Disks

### ISSUE THREAD

**Issue by ElnuDev** [NixOS/nixpkgs#219775]
### Describe the bug
When creating a partition of any type in GNOME Disks, it throws the following error:

```
Error creating partition on /dev/sdc: Failed to determine /nix/store/dvx2w3x83i8qrrdhr4xxhnv7zvjvl9jc-gptfdisk-1.0.9/bin/sgdisk's version from: Process killed with a signal (udisks-error-quark, 0)
```

I'm assuming this isn't an issue upstream.

### Steps To Reproduce
1. Go to a disk such as a USB stick in GNOME Disks that has free space
2. Create a new partition

### Expected behavior
GNOME Disks successfully creates the partition.

### Notify maintainers

@NixOS/gnome @ehmry

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```console
[elnu@elnu:~]$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/x6yjkzgmdppwi95y4gvm4lxi6q27936s-nix-info
copying path '/nix/store/x6yjkzgmdppwi95y4gvm4lxi6q27936s-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 23.05 (Stoat), 23.05.20230226.7f5639f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ElnuDev** [comment]
Seems like all `sgdisk` commands fail with `Segmentation fault (core dumped)`

**Comment by ehmry** [comment]
Could the problem be with popt?

**Comment by ElnuDev** [comment]
Seems to no longer be an issue after updating to 6c43a3495a11e261e5f41e5d7eda2d71dae1b2fe.
