### ISSUE TITLE
fastly: fastly compute serve does not work, viceroy not nix'fieid

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#219897]
The `fastly compute serve` command uses the Rust program <https://github.com/fastly/Viceroy/> to run stuff. It automatically fetches the latest release, but then that binary doesn’t work:

```
$ fastly compute serve
…

✓ Fetching latest Viceroy release
✓ Running local server

INFO: Command output:
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

ERROR: fork/exec /home/jojo/.config/fastly/viceroy: no such file or directory.

This error may be caused by a problem with your host environment, for example too-restrictive file permissions, files that already exist, or a full disk.
```

As usual on NixOS, the wrong linker is the (or at least one) problem:

```
/home/jojo/.config/fastly/viceroy: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ad6929dea160708e4501e5e365ca6b80469a480e, for GNU/Linux 3.2.0, stripped
```

I see two possible ways to approach the problem:
 
 1. Package `viceroy` for nixpkgs (straightforward `rustPlatform.buildRustPackage` seems to work), patch `fastly` to always use that version, disable auto-updating `viceroy`.
 2. Let `fastly` fetch the binary release, but patch it to run `patchelf` on it after downloading.

@ereslibre @shyim, do you have thoughts on this?

**Comment by shyim** [comment]
We should package it and adjust the PATH of fastly to find it. For Auto Update we should make a PR to allow disabling that feature and enable that by default with nix

**Comment by ereslibre** [comment]
> We should package it

I will open a couple of PR's tonight, for adding viceroy and another one to wrap fastly with the PATH properly set.

**Comment by Integralist** [comment]
👋🏻 cross-posting in case it's useful
https://github.com/fastly/cli/pull/859
