### ISSUE TITLE
Add tacentview

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#219830]
**Project description**

An image and texture viewer for tga, png, apng, exr, dds, ktx, ktx2, astc, qoi, gif, hdr, jpg, tif, ico, webp, and bmp files. Uses Dear ImGui, OpenGL, and Tacent. Useful for game devs as it displays information like the presence of an alpha channel and querying specific pixels for their colour.

**Metadata**

* homepage URL: https://github.com/bluescan/tacentview
* source URL: https://github.com/bluescan/tacentview
* license: isc
* platforms: linux

**Comment by avh4** [comment]
I made an attempt at this but was unable to make progress, since tacentview's CMake script seems to need to manually clone other git repositories, which is not allowed by nixpkgs.

**Comment by Zahrun** [comment]
Thank you for trying. I guess we would have to package all these dependencies and patch the cmakelist
