### ISSUE TITLE
Packaging requests: libgconf-2-4

### ISSUE THREAD

**Issue by Karvp** [NixOS/nixpkgs#219829]
**Project description**

libgconf-2-4 is a shared library for GConf, a configuration database system for storing application preferences. It supports default or mandatory settings set by the administrator, and changes to the database are instantly applied to all running applications (https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libgconf-2-4_3.2.6-4ubuntu1_amd64.deb.html).

**Metadata**

* homepage URL: https://projects.gnome.org/gconf/
* source URL: https://download.gnome.org/sources/GConf/3.2/GConf-3.2.6.tar.xz
* license: lgpl21

**Comment by TheOPtimal** [comment]
GConf is beyond deprecated these days.

**Comment by Aleksanaa** [comment]
New applications should no longer use gconf. If someone needs an application that depends on libgconf, they can add this library when adding that application.
