### ISSUE TITLE
Package request: Calcure

### ISSUE THREAD

**Issue by noelpilled** [NixOS/nixpkgs#219820]
**Project description**

Modern TUI calendar and task manager with customizable interface. Manages your events and tasks, displays birthdays from your [abook](https://abook.sourceforge.io/), and can import events and tasks from [calcurse](https://github.com/lfos/calcurse) and [taskwarrior](https://github.com/GothenburgBitFactory/taskwarrior).

**Metadata**

* homepage URL: https://anufrievroman.gitbook.io/calcure
* source URL: https://github.com/anufrievroman/calcure
* license: MIT
* platforms: linux, macos, windows

**Comment by dit7ya** [comment]
@noelpilled Can you please test the linked PR?
