### ISSUE TITLE
Package request: Castopod

### ISSUE THREAD

**Issue by TheOPtimal** [NixOS/nixpkgs#219888]
**Project description**

From their website:

>  **The free and open-source solution to your podcasting 2.0 journey**
> Self-host your podcasts with ease, keep control over what you create and talk to your audience without any middleman. Your podcast and your audience belong to you and you only.

Essentially, it's a self-hosted podcast server which has your standard RSS Podcasting, but also

- Works over ActivityPub so people can leave comments or like the episode, or follow the podcast.
- Sports an excellent Web UI
- Supports linking external podcasting platforms like Apple Podcasts or Spotify
- Also linking social platforms like Mastodon or Discord
- Has GUIDs, Location/Maps, Podcast Locking, OP3 Analytics, the `person` tag, Social Interaction, Soundbites, Chapters, Transcripts and a whole lot more.
- Supports Podcasting 2.0 and uses the XML `podcast-namespace`

**Metadata**

* homepage URL: https://castopod.org/
* source URL: https://code.castopod.org/adaures/castopod
* license: GNU AGPLv3
* platforms: Linux

**Comment by MohrJonas** [comment]
Maybe you could use the docker container they provide?

**Comment by sinavir** [comment]
Can be closed I guess : 
https://github.com/NixOS/nixpkgs/pull/255033

**Comment by balsoft** [comment]
Closed via #255033
