### ISSUE TITLE
nix-channel --update unable to fetch behind company ssl certificate mitm

### ISSUE THREAD

**Issue by DonPavlov** [NixOS/nixpkgs#219851]
### Describe the bug
I am unable to pull nix-channel updates and fetch home mananger behind my companies ssl certificate server.
Getting the following output:
```
sudo nix-channel --update
warning: error: unable to download 'https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz': SSL connect error (35); retrying in 254 ms
```

### Steps To Reproduce
1. I have added my company pem certificates using:
    security.pki.certificateFiles = ["${pkgs.cacert}/etc/ssl/certs/custom.crt"];
2. add home-manager channel
3. update nix-channels and get an error
4. additionally adding the cert using
```
export NIX_SSL_CERT_FILE=/etc/ssl/certs/custom.crt
```
5. Run curl test 
```
curl -L https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:16000069:STORE routines::unregistered scheme
```
### Expected behavior
curl and nix-channel respect the custom.crt file and update as expected.

### Notify maintainers

@worldofpeace
@schnusch
@figsoda 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-linux"`
 - host os: `Linux 5.15.95, NixOS, 22.11 (Raccoon), 22.11.2780.8bd260eb578`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by figsoda** [comment]
I don't know what it doesn't work, and also doesn't maintain any of the packages/modules mentioned

**Comment by DonPavlov** [comment]
Moved issue to nix project.
