### ISSUE TITLE
scotch package broken when installing on Debian

### ISSUE THREAD

**Issue by mdaiter** [NixOS/nixpkgs#21989]
## Issue description
When attempting to install the `scotch` package on Ubuntu, the `make` command fails with the following error:

`
../../lib/libscotch.a(parser_ll.o): In function `scotchyylex':
parser_ll.c:(.text+0xe87): undefined reference to `scotchyywrap'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:50: amk_grf] Error 1
make[2]: Leaving directory '/tmp/nix-build-scotch-6.0.4.drv-0/scotch_6.0.4/src/scotch'
make[1]: *** [Makefile:59: scotch] Error 2
make[1]: Leaving directory '/tmp/nix-build-scotch-6.0.4.drv-0/scotch_6.0.4/src/scotch'
make: *** [Makefile:94: scotch] Error 2
builder for ‘/nix/store/jdjr5x3sgjj9ca3whgcg6k2fbqqajkb8-scotch-6.0.4.drv’ failed with exit code 2
error: build of ‘/nix/store/jdjr5x3sgjj9ca3whgcg6k2fbqqajkb8-scotch-6.0.4.drv’ failed
`

### Steps to reproduce
1. Fresh-install a Nix package manager onto a Debian (Ubuntu) 14.04 system.
2. Update channel.
3. Attempt install.

## Technical details

* System: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I)

**Comment by mdaiter** [comment]
cc @bzizou

**Comment by bzizou** [comment]
OK, I'll take a look asap...

**Comment by mdaiter** [comment]
Looks like it's a problem with `yacc`

**Comment by mdaiter** [comment]
https://github.com/NixOS/nixpkgs/pull/22049

Solved through this. Key insight was to specify the `flex` version.

**Comment by globin** [comment]
As this appears to be fixed, closing.
