### ISSUE TITLE
impure path when trying to build opencv with cuda

### ISSUE THREAD

**Issue by jascase901** [NixOS/nixpkgs#21994]
## Issue description
running nix-shell . with default.nix that sets enableCuda to true causes opencv to fail building with
 
impure path `/lib64/libz.so' used in link
collect2: error: ld returned 1 exit status

### Steps to reproduce
nix-shell .

##### Default.nix:
```
let
  pkgs = import <nixpkgs> {};
  stdenv = pkgs.stdenv;
  cuda-opencv3 = pkgs.opencv3.override{
enableCuda = true;
};
in rec {
  examplecuda = stdenv.mkDerivation rec {
    name = "example-cuda";
    src = ./.;
    buildInputs = [pkgs.cmake cuda-opencv3 pkgs.cudatoolkit pkgs.linuxPackages.nvidia_x11 pkgs.makeWrapper ];

    preBuild = ''
      export CUDA_PATH="${pkgs.cudatoolkit}"
    '';

    installPhase = ''
      mkdir -p "$out/bin"
      cp -r ./bin/*/*/release/* "$out/bin"

      for file in `ls $out/bin`; do
      	  echo "$file";
	  wrapProgram "$out/bin/$file" \
	              --prefix LD_LIBRARY_PATH ":" "${pkgs.linuxPackages.nvidia_x11}/lib"
      done
    '';


  };
}
```

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
Centos 7
3.10.0-327.22.2.el7.x86_64

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.4

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
17.03pre97542.c1ecf36

**Comment by jascase901** [comment]
I forgot to mention that I had to add this file
~/.nixpkgs/config.nix:
{ allowUnfree = true; }

**Comment by sifmelcara** [comment]
I also encountered the exact same problem on Arch Linux. I would guess [These code in opencv's CMakeLists](https://github.com/opencv/opencv/blob/f34b2f7b8d10271d0e16bcab174bdacd51365f4f/CMakeLists.txt#L137-L163) causes problem, because Arch Linux also have /lib64/libz.so and opencv's cmake detects it.

**Comment by alexozer** [comment]
Status?

**Comment by sifmelcara** [comment]
cc opencv maintainers @viric @flosse
Maybe patch opencv's CMakeLists to stop it from using libraries in /lib/ is a possible solution?
