### ISSUE TITLE
Package request: nginx-rtmp-module

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#219964]
**Project description**

This module can be built into nginx to enable Restreaming of RTMP streams from one source to multiple destinations, among many other uses (which also include RTMP)

Properly adding this should probably also include the ability to configure it as part of the website configuration stuff.

**Metadata**

* homepage URL: https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/
* source URL: https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/
* license: BSD
* platforms: Linux

**Comment by Baitinq** [comment]
Isnt this already in nixpkgs?

**Comment by tnias** [comment]
Currenly https://github.com/arut/nginx-rtmp-module is in nixpkgs. And this request is about a fork.

https://github.com/NixOS/nixpkgs/blob/b18427fb2faed486bf90a6ab155e4d9041c5eb1c/pkgs/servers/http/nginx/modules.nix#L647-L663

**Comment by Krutonium** [comment]
Why does it not show up https://search.nixos.org/packages?channel=22.11&size=50&sort=relevance&type=packages&query=nginx-rtmp at all?

**Comment by SuperSandro2000** [comment]
Because the nginx modules are not a real package set and just some trivial attrset. Since this is a general issue with nginx and not specific to this module I am closing this.
