### ISSUE TITLE
Douane Application Firewall

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixpkgs#220029]
**Project description**

[The Douane firewall](https://douaneapp.com/) filters and limits the outgoing network traffic per application.
You can allow network traffic for some applications and deny network traffic for others.

**Metadata**

* homepage URL: https://douaneapp.com
* source URL:https://gitlab.com/douaneapp/Douane/-/wikis/home
* license: gpl2
* platforms:  linux

**Comment by RamKromberg** [comment]
Douane doesn't seem to be actively developed. Have you gave OpenSnitch a try? It's a little buggy so I haven't used it in a while but it worked for the most part.

**Comment by phpcitizen** [comment]
I am using Opensnitch now, icmp is not working, but it is adapted in beta now.

I am closing this as you say it is not active. Thanks.
