### ISSUE TITLE
Haskell: tasty-ant-xml is broken with ghc7103

### ISSUE THREAD

**Issue by woehr** [NixOS/nixpkgs#22008]
## Issue description

When trying to build tasty-ant-xml, the following error is reported.

```
Configuring tasty-ant-xml-1.0.4...
Setup: At least the following dependencies are missing:
directory >=1.2.6.2, filepath >=1.4.1.0
builder for ‘/nix/store/9c37m8ffxmplxgg2in95gcwli758vs1z-tasty-ant-xml-1.0.4.drv’ failed with exit code 1
```

### Steps to reproduce

```
nix-env -i -A haskell.packages.ghc7103.tasty-ant-xml -f <nixpkgs>
```

## Technical details

* System: Arch Linux (`uname -r` -> 4.8.13-1-ARCH)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "17.03pre-git" (commit 305e3e27b6a5346d24fd8cdbf71667245707bbb0)

**Comment by woehr** [comment]
I'll add that I'm happy to submit a pull request fixing this, I'm just not sure what to do to fix it.

**Comment by jpierre03** [comment]
On nixos-17.03pre98682.f673243  :
- `nix-env -i -A haskell.packages.ghc802.tasty-ant-xml -f "<nixpkgs>"` works fine
- `nix-env -i -A haskell.packages.ghc801.tasty-ant-xml -f "<nixpkgs>"` works fine
- `nix-env -i -A haskell.packages.ghc7103.tasty-ant-xml -f "<nixpkgs>"` same error

~~~
setupCompilerEnvironmentPhase
Build with /nix/store/09h8x5vbwsv1fnb44z55yxphlvavkszc-ghc-7.10.3.
unpacking sources
unpacking source archive /nix/store/g4bcqr7cpjdfq0d12k86h9j9sb0qw5w9-tasty-ant-xml-1.0.3.tar.gz
source root is tasty-ant-xml-1.0.3
setting SOURCE_DATE_EPOCH to timestamp 1482054684 of file tasty-ant-xml-1.0.3/Test/Tasty/Runners/AntXML.hs
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-tasty-ant-xml-1.0.3.drv-0/package.conf.d -j8 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-tasty-ant-xml-1.0.3.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/qpw1ixhgvncfsral3khvbkprmq6vnjgy-tasty-ant-xml-1.0.3 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-tasty-ant-xml-1.0.3.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/qpw1ixhgvncfsral3khvbkprmq6vnjgy-tasty-ant-xml-1.0.3/lib/ghc-7.10.3/tasty-ant-xml-1.0.3 --enable-split-objs --disable-library-profiling --disable-executable-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring tasty-ant-xml-1.0.3...
Setup: At least the following dependencies are missing:
directory >=1.2.6.2, filepath >=1.4.1.0
builder for ‘/nix/store/6rvsrlwzq0030jbsgp1s0y5nma9xq9k2-tasty-ant-xml-1.0.3.drv’ failed with exit code 1
error: build of ‘/nix/store/6rvsrlwzq0030jbsgp1s0y5nma9xq9k2-tasty-ant-xml-1.0.3.drv’ failed
~~~

@woehr  According to https://github.com/peti/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix   `directory` and `filepath` packages are disabled but I don't know why.
Maybe @peti can help you.

**Comment by peti** [comment]
`directory` and `filepath` are core libraries shipped by GHC. Apparently, current versions of `tasty-ant-xml` no longer support GHC 7.x.

**Comment by woehr** [comment]
I suppose overriding the ghc7103 package set with an older version would be the best solution then?

@ocharles appears to be the author/maintainer, would you mind commenting?

**Comment by peti** [comment]
Generally speaking, the `ghc7103` is not a supported package set, i.e. we don't necessarily make an effort to keep everything in there compiling. If someone were to provide a PR that remedies this particular issue, then we'd happily merge it, but keeping an open issue around on Github seems like overkill (since no Nixpkggs maintainer is going to care about it). Therefore, I'm closing this issue and encourage anyone who cares about this build to submit a PR that fixes it.
