### ISSUE TITLE
grapejuice can be broken by new wine versions

### ISSUE THREAD

**Issue by nullishamy** [NixOS/nixpkgs#220062]
### Describe the bug
When a new version of wine is packaged, the version pointed to by the config (.config/brinkervii/grapejuice/user_settings.json) (a store link) becomes invalid. At best, this will use an old wine version, and at worst will cause the app to fail to launch.

### Steps To Reproduce
1. Install old wine
2. Generate initial config (`grapejuice first-time-setup`)
3. Update wine
4. Run `grapejuice app`
5. Observe

### Expected behavior
The app should not crash.

### Screenshots
N/A

### Additional context
Unsure how Nix should handle this one. The *best* solution is to update the config file (which conforms to xdg), however that may be out of scope. A warning / doc would also help.

### Notify maintainers
@artturin @helium

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.91, NixOS, 22.11 (Raccoon), 22.11.20230204.8e82401`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

```console
amy:~/ $ nix-shell -p nix-info --run "nix-info -m"                                          [21:56:17]
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.91, NixOS, 22.11 (Raccoon), 22.11.20230204.8e82401`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.05.tar.gz, nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

amy:~/ $
```

**Comment by Artturin** [comment]
upstream should stop embedding a full path or if there's some valid reason for why they do it then maybe the could grab a new path from $PATH if the current one doesn't exist

**Comment by nullishamy** [comment]
It stores it under the key `default_wine_home`, implying that will be used as a fallback(?)

Could open an issue on the grapejuice repo and see what they have to say. Worth noting that regenerating the config file with `grapejuice first-time-setup` will resolve the new path and work fine.

**Comment by Artturin** [comment]
ah looks like its our fault https://github.com/NixOS/nixpkgs/blob/82cfa73fbfeb8ca63d2881dc0ea2851f747c3574/pkgs/games/grapejuice/default.nix#L87-L88 which was added in https://github.com/NixOS/nixpkgs/pull/176384

**Comment by Artturin** [comment]
you tagged the wrong helium btw 
@helium18

**Comment by nullishamy** [comment]
> you tagged the wrong helium btw 

I figured haha. Couldn't determine who it was supposed to be lol.

As for the substitution, I'm not sure why it wouldn't update for newer wine builds? Seems kinda weird..

**Comment by Artturin** [comment]
> As for the substitution, I'm not sure why it wouldn't update for newer wine builds? Seems kinda weird..

seems grapejuice copies the file to $HOME so the path won't be changed on wine hash changes

**Comment by nullishamy** [comment]
Sure. I think the issue mainly lies with the fact Nix does not edit the resulting config file, but the source itself. Unless Nix prods into XDG config home, there's not much we can do about it.
