### ISSUE TITLE
xivlauncher: closure does not include aria2

### ISSUE THREAD

**Issue by jesskay** [NixOS/nixpkgs#220065]
Despite being referenced by the aria2c path patching step, xivlauncher's closure (as seen by running `nix path-info -rsSh nixpkgs#xivlauncher`) does not contain aria2, allowing it to be garbage collected if nothing else on the system requires it, breaking patch downloads if that happens.

1. Install xivlauncher into a profile.
2. Verify that patch downloads work.
3. Manually garbage collect the store, or wait until after an automatic collection.
4. Patch downloads now fail with an "path not found" error for aria2c.

Workaround: Install aria2c to a profile explicitly, to ensure that it has a GC root.

(ping @sersorrel @witchof0x20 per bug template instructions)

### Metadata

```console
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.96, NixOS, 22.11 (Raccoon), 22.11.20230228.d70f5cd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by jesskay** [comment]
(My gut instinct here is that the process of compiling to CLR is, as an unintentional side effect, obfuscating the path enough that nix doesn't pick up on it, but I'm not sure how I'd go about verifying that, nor how to get nix to pick up the path anyway.)

**Comment by sersorrel** [comment]
argh, that's annoying.

```console
$ strings /nix/store/is5fyz8wq5g78hvibx9xi9f1ksgyglx3-XIVLauncher-1.0.3/lib/XIVLauncher/XIVLauncher.Core | rg aria2c
Aria2c
Aria2c downloads (recommended)
$ # `-e l`: search for 16-bit little-endian strings
$ strings -e l /nix/store/is5fyz8wq5g78hvibx9xi9f1ksgyglx3-XIVLauncher-1.0.3/lib/XIVLauncher/XIVLauncher.Core | rg aria2c
aria2c-xl
aria2c-xl.exe
/nix/store/4cznv3y10malvb54vrggnm4y3d94gc6l-aria2-1.36.0-bin/bin/aria2c
```

fixing the missing dependency should be fairly easy – you need to make a file as part of the xivlauncher build that contains the path to aria2c as ASCII/UTF-8 so that nix will see it. there's an idiomatic way to do this (ending up with a file under `nix-support`), but I can't remember the details; if you feel like looking into it, feel free to open a PR, else I'll try to get around to it at some point.

**Comment by sersorrel** [comment]
ok, seems like maybe there is not actually an idiomatic way to do it...

https://github.com/NixOS/nixpkgs/blob/237e2f744b3796598fda4c677f6e71d6885637e7/pkgs/development/tools/build-managers/bazel/bazel_5/default.nix#L646-L657

https://github.com/NixOS/nixpkgs/blob/d8ae00eb919e0650f93e81dab891f923038116b5/pkgs/development/tools/build-managers/gradle/default.nix#L93-L99
