### ISSUE TITLE
`chromium-110.0.5481.177` is not supported on `x86_64-darwin`

### ISSUE THREAD

**Issue by duckpuppy** [NixOS/nixpkgs#220169]
### Describe the bug
`chromium-110.0.5481.177` is not supported on `x86_64-darwin`. I do not directly reference the chromium package in my configs, so I'm having trouble finding where any reference to that package is coming from.

### Steps To Reproduce
1. Attempt to install `chromium` from nixpkgs-unstable on darwin

### Expected behavior
Package installs properly.

### Additional context
Many packages depend on chromium transitively making it hard to pin properly.

### Notify maintainers
@primeos 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.12.0`
 - channels(paikens): `"darwin, home-manager, nixpkgs, nur-duckpuppy, nur-gerschtli"`
 - nixpkgs: `/Users/paikens/.nix-defexpr/channels/nixpkgs`
```

**Comment by primeos** [comment]
> chromium-110.0.5481.177 is not supported on x86_64-darwin

Yes

> I do not directly reference the chromium package in my configs, so I'm having trouble finding where any reference to that package is coming from.

Can't really help with that.
I guess you'll unfortunately have to use `--show-trace` and sort through that.
Grepping for `chromium` in Nixpkgs might also help.

Mind if we close this issue as I don't see anything actionable for Nixpkgs here?
(We can also leave it open for a few days in case this is related to a recent Nixpkgs change that someone else might know about but I don't have time for this anyway and such issues tend to bitrot.)

**Comment by kirillrdy** [comment]
@duckpuppy are you able to share you configuration ?

**Comment by duckpuppy** [comment]
Posting my config would be hard - it's fairly large.

However - I CAN narrow down a bit, but I'm trying to bisect to find the problem. I can use the unstable channel at 8c619a1f3cedd16ea172146e30645e703d21bfc1 without issue. So... something between then and today is the problem. I just have to narrow it down to a commit, which will be tough.

**Comment by duckpuppy** [comment]
I'm closing this ticket and I'll take it up with the vhs maintainers.
