### ISSUE TITLE
rootcint not available

### ISSUE THREAD

**Issue by rtesse** [NixOS/nixpkgs#220160]
### Describe the bug
I want like to use root with nix. I successfully installed nix, and I ran the command `nix-shell -p root`. However, rootcint is not available. I used the 22.11 channel as the program is not provided in the unstable channel.

### Steps To Reproduce
1.  nix-shell -p root
2. go to the location of the executable
3. rootcint is not present

### Expected behavior
rootcint in installed

### Notify maintainers

@ShamrockLee @veprbl 

### Screenshots
![image](https://user-images.githubusercontent.com/26649180/223743593-a803f60a-a01c-4660-847d-1723ad2b85d2.png)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-darwin"`
 - host os: `Darwin 22.3.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(rtesse): `"home-manager-22.11.tar.gz, nixpkgs-22.11-darwin-22.11-darwin"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by rtesse** [comment]
Hello, thanks for your answer. It is interesting, I am moving from homebrew to nix and rootcint is installed with brew (root version 6.29). I tested to install root from scratch and rootcint is also present in the install directory. 

If it is not a bug, I think we can close the issue, I will modify my script and use rootcling. 

Maybe could I suggest removing rootcint from the root package on nixos.search ? 

![image](https://user-images.githubusercontent.com/26649180/223802915-f3458f61-626b-41ed-98cc-b2db226fad2d.png)

**Comment by ShamrockLee** [comment]
It's quite interesting to learn that "bin/rootcint" is available in ROOT 6.

As you say that you are using Nixpkgs 22.11 (i.e. the current stable), what is the exact commit of Nixpkgs? This piece of information happens to get lost in the nix-info output. Could you also provide the ROOT version from Nixpkgs 22.11 with bin/rootcint ?

I remember that there is no big changes made to `pkgs/applications/science/misc/root/defailt.nix` since the Nixpkgs 22.11 branch-off.

**Comment by rtesse** [comment]
If I correctly get the info: 

- commit id: `1e56d76f106e626764ee91785fe32b2342cc836e`
- root version: `6.26/10`

But if rootcint is installed when I build root from scratch, I don’t understand why this is not the case when I used nix-shell. Sorry, I am new to nix-environment :)

**Comment by veprbl** [comment]
I see `rootcint` in `/nix/store/fg8z777jpm1llbimla4wlndfmkq5qspj-root-6.24.06`
but not in `/nix/store/2xfr6nx56acghf31wafzsjfgzcbnild2-root-6.26.10`

**Comment by ShamrockLee** [comment]
It's still there in `/nix/store/8w34q85dfpwvqam09vvv99h98l4j9251-root-6.26.10/bin` built from 5aed5285a952e0b949eb3ba02c12fa4fcfef535f (on branch release-22.11).

```console
bash-5.1$ ls /nix/store/8w34q85dfpwvqam09vvv99h98l4j9251-root-6.26.10/bin
genreflex           rootls
hadd                rootmkdir
hist2workspace      rootmv
prepareHistFactory  rootnb.exe
proofserv           rootn.exe
proofserv.exe       rootprint
rmkdepend           rootrm
root                roots
rootbrowse          roots.exe
rootcint            rootslimtree
rootcling           setxrd.csh
root-config         setxrd.sh
rootcp              thisroot.csh
rootdrawtree        thisroot.fish
rooteventselector   thisroot.sh
root.exe            xpdtest
```

**Comment by veprbl** [comment]
Didn't we enable gnu directories since then?

**Comment by rtesse** [comment]
Could this be related to the operating system? I am on macOS.

**Comment by ShamrockLee** [comment]
> Could this be related to the operating system? I am on macOS.

It's reproducible on Linux, so no.

> Didn't we enable gnu directories since then?

Oops! You're right.

<details>
<summary>Build result</summary>
<pre>
$ nix build --no-link .?rev=c1027175c1cd3fa4c903e340dc7b75768ff99ede#root

$ nix path-info .?rev=c1027175c1cd3fa4c903e340dc7b75768ff99ede#root
/nix/store/kkvb829yd3sr4fbs8r0nw6w93m82fwa6-root-6.26.10

$ ls /nix/store/kkvb829yd3sr4fbs8r0nw6w93m82fwa6-root-6.26.10
bin  etc  include  lib  nix-support  share

$ ls /nix/store/kkvb829yd3sr4fbs8r0nw6w93m82fwa6-root-6.26.10/bin/
hadd                proofserv      root        root-config   rooteventselector  rootmkdir   rootn.exe  roots         setxrd.csh    thisroot.fish
hist2workspace      proofserv.exe  rootbrowse  rootcp        root.exe           rootmv      rootprint  roots.exe     setxrd.sh     thisroot.sh
prepareHistFactory  rmkdepend      rootcling   rootdrawtree  rootls             rootnb.exe  rootrm     rootslimtree  thisroot.csh  xpdtest

$ nix path-info .?rev=13e43fc0bc527373f50cbf9fb802c0da7d56ab81#root
this path will be fetched (117.65 MiB download, 424.13 MiB unpacked):
  /nix/store/ngkpxibxzjhb2k6kgmz0dzcrbij5ma27-root-6.26.10
error: path '/nix/store/ngkpxibxzjhb2k6kgmz0dzcrbij5ma27-root-6.26.10' is not valid

$ nix build --no-link .?rev=13e43fc0bc527373f50cbf9fb802c0da7d56ab81#root

$ ls /nix/store/ngkpxibxzjhb2k6kgmz0dzcrbij5ma27-root-6.26.10/bin/
genreflex           proofserv      rootbrowse   rootcp             rootls      rootn.exe  roots.exe     thisroot.csh
hadd                proofserv.exe  rootcint     rootdrawtree       rootmkdir   rootprint  rootslimtree  thisroot.fish
hist2workspace      rmkdepend      rootcling    rooteventselector  rootmv      rootrm     setxrd.csh    thisroot.sh
prepareHistFactory  root           root-config  root.exe           rootnb.exe  roots      setxrd.sh     xpdtest

$ ls /nix/store/ngkpxibxzjhb2k6kgmz0dzcrbij5ma27-root-6.26.10
bin  cmake  config  emacs  etc  fonts  geom  icons  include  js  lib  macros  nix-support  share  tutorials
</pre>
</details>

I think it's an upstream issue anyway.

> I tested to install root from scratch and rootcint is also present in the install directory.

@rtesse I guess it will no longer be there when building with the `-Dgnuinstall=ON` CMake flag.

I think it's an upstream issue / upstream decision anyway. Nevertheless, we can work around by providing a symbolic link or just `cp $out/bin/{rootcling,rootcint}`.

**Comment by ShamrockLee** [comment]
Sorry, I'm wrong. It was another commit in the same PR that causes the issue.

I deleted
```
    "-DCMAKE_INSTALL_BINDIR=bin"
    "-DCMAKE_INSTALL_LIBDIR=lib"
    "-DCMAKE_INSTALL_INCLUDEDIR=include"
```
from `cmakeFlags`, thinking they had been default, but the default was always `"$out/{bin,lib,include}"`.

Sorry for the trouble.

@veprbl But what's the original purpose for us to set these?

**Comment by veprbl** [comment]
Often downstream build systems don't handle absolute paths in BINDIR and such.

I did bisect and it also points to c09e03c1a69306c58d2f97453fe9f071171ec48a.

**Comment by rtesse** [comment]
Hello, 

Thanks a lot for the fix. I just have two questions: 

- Do I need to change the nix-channel by using: `nix-channel --add https://nixos.org/channels/nixpkgs-unstable`?
- I read in the documentation that there is a delay to update a channel but how can I update the derivations?

**Comment by veprbl** [comment]
> Hello,
> 
> Thanks a lot for the fix. I just have two questions:
> 
> * Do I need to change the nix-channel by using: `nix-channel --add https://nixos.org/channels/nixpkgs-unstable`?

The issue was fixed on unstable, there was no issue on stable, so any channel works as long as it gets updated by Hydra and you do `nix-channel --update`

> * I read in the documentation that there is a delay to update a channel but how can I update the derivations?  Is it sufficient to do `nix-channel --update` ?

There is a tracker https://nixpk.gs/pr-tracker.html?pr=220437
