### ISSUE TITLE
Update request: realvnc-vnc-viewer 6.22.515 → 7.0.1

### ISSUE THREAD

**Issue by Sepero** [NixOS/nixpkgs#220185]
- Package name: realvnc-vnc-viewer
- Latest released version: 7.0.1
https://www.realvnc.com/en/connect/download/viewer/
- Current version on the unstable channel: 6.22.515
- Current version on the stable/release channel: 6.22.515
- [Y] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
Emily Trau nix@angus.ws

**Comment by creaaidev** [comment]
Current package in nixpkgs is broken
(Version too old, I guess they don't have a mirror for it anymore)

**Comment by NickCao** [comment]
https://github.com/NixOS/nixpkgs/blob/e6e389917a8c778be636e67a67ec958f511cc55d/pkgs/tools/admin/realvnc-vnc-viewer/default.nix#L12
