### ISSUE TITLE
Package request: uosc

### ISSUE THREAD

**Issue by pinkcreeper100** [NixOS/nixpkgs#220334]
**Project description**

Feature-rich minimalist proximity-based UI for MPV player.

**Metadata**

* homepage URL: https://github.com/tomasklaen/uosc
* source URL: https://github.com/tomasklaen/uosc
* license: gpl3only
* platforms: unix, linux, darwin

**Comment by apfelkuchen6** [comment]
#219909

**Comment by pinkcreeper100** [comment]
oh ok
