### ISSUE TITLE
'nixos-rebuild (switch|boot)' doesn't name or date boot entries, or let you do so manually

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#22031]
When running `nixos-rebuild boot` or `nixos-rebuild switch`, it emits a new entry in the boot menu for the built configuration, but this entry is merely labeled "NixOS Generation #", with the # an incrementing integer. This means that when testing a number of configurations, it's very easy to end up with dozens of bootloader entries and no good way to tell which is which. At minimum, appending the date and time at which each one was built would be useful; what would be even better would be a way to append a name to a generation, either at build time or post hoc (e.g. `nixos-rename-generation "Known Good"`).

* System: 16.09.1512.6b28bd0 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 16.09.1512.6b28bd0

**Comment by fpletz** [comment]
Something like #10996?

This only applies to `systemd-boot` as `grub` will  at least have a timestamp to the boot entries. We should unify the naming for all bootloaders.

**Comment by fpletz** [comment]
Fixed by #10996.
