### ISSUE TITLE
Alt+Tab Scroll Workaround doesn't work

### ISSUE THREAD

**Issue by andreiburdusa** [NixOS/nixpkgs#220471]
### Describe the bug
The Gnome extesion [`Alt+Tab Scroll Workaround`](https://extensions.gnome.org/extension/5282/alttab-scroll-workaround/) works fine  when downloaded from its homepage and installed using the "Extensions" app, but it doesn't work when installed using the [NixOS configuration instructions](https://search.nixos.org/packages?channel=22.11&show=gnomeExtensions.alttab-scroll-workaround&from=0&size=50&sort=relevance&type=packages&query=Alt%2BTab+Scroll+Workaround) (i.e. adding `gnomeExtensions.alttab-scroll-workaround` to `configuration.nix`)

### Steps To Reproduce
1. Install `gnomeExtensions.alttab-scroll-workaround`
2. Scroll in browser (Brave, Chrome)
3. Scroll in VSCode, notice that the scroll done in the browser also affects VSCode

### Metadata
```console
$ nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/vy1gljyx0hx57bjnsyj05g3xw1bm2v6m-stdenv-linux
copying path '/nix/store/vy1gljyx0hx57bjnsyj05g3xw1bm2v6m-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.97, NixOS, 22.11 (Raccoon), 22.11.2999.a7cc81913bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(andrei): `"nixos-22.11"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.97, NixOS, 22.11 (Raccoon), 22.11.2999.a7cc81913bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(andrei): `"nixos-22.11"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by nicolas-goudry** [comment]
Did you enable the extension ?

This can be done either manually, or with a dconf profile:

```nix
{
  programs.dconf.profiles = {
    "org/gnome/shell".enabled-extensions = [
      "alt-tab-scroll-workaround@lucasresck.github.io"
    ];
  };
}
```

**Comment by andreiburdusa** [comment]
Thanks for the suggestion, but I'm not using gnome anymore

**Comment by nicolas-goudry** [comment]
> Thanks for the suggestion, but I'm not using gnome anymore 

Since this is not an issue anymore, could you maybe close this issue then?
