### ISSUE TITLE
Discord Unread notification badge

### ISSUE THREAD

**Issue by MathiasSven** [NixOS/nixpkgs#220768]
### Describe the bug
I never really noticed this until today, but apparently the discord task bar icon (if you have one, I am on KDE) is supposed to have a notification badge, I have included a screenshot.

### Expected behavior
The discord task bar icon should include a badge for the number of unread notifications

### Screenshots
![image](https://user-images.githubusercontent.com/24759037/224520366-98a6f5bb-824c-4184-a4a0-3cd6b0776b46.png)

### Additional context
Today I was setting up a `Kubuntu` system for someone else who was new to Linux, I installed Discord via flatpak, and then they asked me about the badge (since it is present on Windows but not on the [flatpak installed version](https://github.com/flathub/com.discordapp.Discord/issues/228)). From a little searching, it seems that Discord needs `libunity` to ba available in the system, so on Kubuntu this was fixed by doing `sudo apt-get install libunity-dev`.

Since `libunity` is already in `nixpkgs`, it might just be a matter of adding it to the `libPath`?

### Notify maintainers
@MP2E @devins2518 @Artturin @Infinidoge

### Metadata
```console
~ ✦❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.2-zen1, NixOS, 23.05 (Stoat), 23.05pre461539.c90c4025bb6`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(mathiassven): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Infinidoge** [comment]
Huh. I don't think I ever knew one was supposed to be there either.

I see an unread indicator (red circle in the top corner, no number), so that works fine, but I don't think I've ever seen a number.

Assuming that would be all it would take, sounds like a pretty simple PR that would be a good addition.

**Comment by MathiasSven** [comment]
I cloned `nixpkgs` and it does seem that simply adding 
```diff
```

**Comment by MathiasSven** [comment]
I have made a clone of `nixpkgs` and it does seem that all that was need was to add the library to `libPath`.
```diff
--- a/pkgs/applications/networking/instant-messengers/discord/linux.nix
+++ b/pkgs/applications/networking/instant-messengers/discord/linux.nix
@@ -5,6 +5,7 @@
 , libXScrnSaver, libXcomposite, libXcursor, libXdamage, libXext, libXfixes
 , libXi, libXrandr, libXrender, libXtst, libxcb, libxshmfence, mesa, nspr, nss
 , pango, systemd, libappindicator-gtk3, libdbusmenu, writeScript, python3, runCommand
+, libunity
 , wayland
 , branch
 , common-updater-scripts, withOpenASAR ? false }:
@@ -69,6 +70,7 @@ stdenv.mkDerivation rec {
     libnotify
     libX11
     libXcomposite
+    libunity
     libuuid
     libXcursor
     libXdamage
```
I found it to be a bit ugly myself since I had over 1000 unread notifications, and it seems disabling it is only possible outside the application. On `KDE` for example, you have to go to `System Settings > Notifications > Application-sepcific settings > Discord` and tick off "Show notification badges". Running the current `Discord` from `nixpkgs` afterwords does not remove the badges, it only freezes them in place, as in marking notifications as read will not update the number, so this is also cached somewhere outside `Discord`, meaning this couldn't be a toggleable functionality via an `override`.
