### ISSUE TITLE
Build failure: baresip, migrate to cmake

### ISSUE THREAD

**Issue by ehmry** [NixOS/nixpkgs#220762]
Baresip fails to build after 5a65a419627fa1746fac2d8b1a7219a47908e781 because the baresip `./configure` no longer finds librem through pkg-config.

Building baresip with Cmake resolves this, but then there is a new build failure:

```
CMake Error at cmake_install.cmake:75 (file):
  file RPATH_CHANGE could not write new RPATH:

    

  to the file:

    /nix/store/r3ycf5gqivja9krbrypbvh915vw6h3qg-baresip-2.9.0/bin/baresip

  The current RUNPATH is:

    /nix/store/r3ycf5gqivja9krbrypbvh915vw6h3qg-baresip-2.9.0/lib64:/nix/store/r3ycf5gqivja9krbrypbvh915vw6h3qg-baresip-2.9.0/lib:/nix/store/mg9l7phyhvi16p9g8g3g8fbyj4mr79gq-zlib-1.2.13/lib:/nix/store/5438qhyypn1kbdnm4312v8db4mkapwhl-openssl-3.0.8/lib:/nix/store/fnvyx1xa7hkah730bps4f9qm097wjms5-libre-2.9.0/lib:/nix/store/dkax2c0d6zjjkm4bwv52lsi8cgxg5n29-librem-2.10.0/lib:/nix/store/76l4v99sk83ylfwkz8wmwrm4s8h73rhd-glibc-2.35-224/lib:/nix/store/2w4k8nvdyiggz717ygbbxchpnxrqc6y9-gcc-12.2.0-lib/lib

  which does not contain:

    /var/empty/local/lib:/build/source/build:

  as was expected.
```

### Steps To Reproduce

1. build baresip

### Notify maintainers

@elohmeier @raskin

**Comment by ehmry** [comment]
@amjoseph-nixpkgs

**Comment by amjoseph-nixpkgs** [comment]
Sorry!

I think https://github.com/NixOS/nixpkgs/pull/218525 fixes this.  I developed and tested them together but wanted to take more time to be sure baresip was finding all of its dependencies.

I didn't realize that merging one without the other would break things.

We can either merge #218525 or else revert #218518 and 218520

**Comment by ehmry** [comment]
Waiting for #218525 is fine by me.
