### ISSUE TITLE
Update request: darktile 0.0.10 → 0.0.11

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#220883]
- Package name: darktile
- Latest released version: 0.0.11

- Current version on the unstable channel: 0.0.10
- Current version on the stable/release channel: 0.0.10

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@flexagoon

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by flexagoon** [comment]
Hi! Unfortunately, I'm no longer using NixOS. It should still be pretty trivial to create a PR, but I won't be able to test it. If I create a draft PR for this, will you be willing to download it and test whether it works?

@sogreatandpowerfull

**Comment by flexagoon** [comment]
Also, I'd appreciate it if you became the maintainer of this package instead of me (only if you want to, of course).

There are pretty much no updates to it, so you'll rarely have to do anything

**Comment by sogreatandpowerfull** [comment]
@flexagoon Sure, I would be happy to test the draft PR and become the maintainer of the package. Please let me know if there's anything else you need from me to proceed.

**Comment by flexagoon** [comment]
@sogreatandpowerfull ok, well, foremost, it seems like the hash of the package can't get obtained on systems without Nix. Could you please run `nix-prefetch-git --rev v0.0.11 https://github.com/liamg/darktile` and post the output here?

**Comment by flexagoon** [comment]
@sogreatandpowerfull ok, well, foremost, it seems like the hash of the package can't get obtained on systems without Nix. Could you please run `nix-prefetch-git --rev v0.0.11 https://github.com/liamg/darktile` and post the output here?

**Comment by sogreatandpowerfull** [comment]
@flexagoon Sure. Here:
```bash
~ nix-shell -p nix-prefetch-git
this path will be fetched (0.01 MiB download, 0.02 MiB unpacked):
  /nix/store/c4djb4fjcbi54ahis6hz8q9v0g0g1la0-nix-prefetch-git
copying path '/nix/store/c4djb4fjcbi54ahis6hz8q9v0g0g1la0-nix-prefetch-git' from 'https://cache.nixos.org'...

~ nix-prefetch-git --rev v0.0.11 https://github.com/liamg/darktile
Initialized empty Git repository in /run/user/1000/git-checkout-tmp-WIf3IsmA/darktile/.git/
remote: Enumerating objects: 1454, done.
remote: Counting objects: 100% (1454/1454), done.
remote: Compressing objects: 100% (1146/1146), done.
remote: Total 1454 (delta 252), reused 1382 (delta 236), pack-reused 0
Receiving objects: 100% (1454/1454), 11.49 MiB | 2.22 MiB/s, done.
Resolving deltas: 100% (252/252), done.
From https://github.com/liamg/darktile
 * tag               v0.0.11    -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is 93392fc149033cb49dfc39bbba7bc8427799ed6d
path is /nix/store/wdmc7pxznrz8vy0lq3v5sm75v6j4i7zg-darktile
git human-readable version is -- none --
Commit date is 2022-05-10 09:18:01 +0100
hash is 0pr38482an4kkml2lj2xd3z4xnynx5jiix6r8wfaphlq1i4g4yrk
{
  "url": "https://github.com/liamg/darktile",
  "rev": "93392fc149033cb49dfc39bbba7bc8427799ed6d",
  "date": "2022-05-10T09:18:01+01:00",
  "path": "/nix/store/wdmc7pxznrz8vy0lq3v5sm75v6j4i7zg-darktile",
  "sha256": "0pr38482an4kkml2lj2xd3z4xnynx5jiix6r8wfaphlq1i4g4yrk",
  "fetchLFS": false,
  "fetchSubmodules": false,
  "deepClone": false,
  "leaveDotGit": false
}
```

**Comment by flexagoon** [comment]
@sogreatandpowerfull I opened a draft PR which updates the package and makes you the maintainer. Please test if the updated package works.

#221013
