### ISSUE TITLE
Package request: nixpkgs-manual

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#220848]
**Project description**

The manual should be available for offline use.

The manual should be very easy to build, e.g. for drive-by contributions. With markdown, writing a small contribution is hardly an iterative process anymore, reading up on incremental manual builds should not be necessary.

**Metadata**

* homepage URL:
* source URL:
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by bjornfor** [comment]
> The manual should be available for offline use.

Isn't that already the case? I have a nixos-manual.desktop file in my (GNOME) NixOS closure, which opens the manual in a browser from `/nix/store/...` (offline).

**Comment by n8henrie** [comment]
@roberth I think @philiptaron seems to have accomplished this in https://github.com/NixOS/nixpkgs/commit/4252286f210a6c3b2310e6736eb1ef59917c9c89. Can this be closed?
