### ISSUE TITLE
itch: error: Package ‘electron-11.5.0’ is marked as insecure, refusing to evaluate.

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#220844]
### Describe the bug

I can't update my system when itch should be installed:

>error: Package ‘electron-11.5.0’ in /nix/store/5wja3wj4lq4gijjgg2lx3966pf6lzijc-nixos-22.11/nixos/pkgs/development/tools/electron/generic.nix:27 is marked as insecure, refusing to evaluate.

### Steps To Reproduce
1. have `itch` in 
2. `nixos-rebuild switch`

### Expected behavior
no error

### Additional context

also reproducible on unstable

i guess electron needs an update

or use a later electron version, if possible

### Notify maintainers

@pasqui23

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 22.11 (Raccoon), 22.11.2999.a7cc81913bb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-hardware, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by SuperSamus** [comment]
It's an upstream issue, trying to use a newer Electron version makes Itch straight up not work (it gets stuck at the initial loading).
https://github.com/itchio/itch unfortunately seems to be abandoned.
There technically is a new version (25.6.1-canary), but it hasn't been distributed as a binary on https://broth.itch.ovh/, and looking at the commits it doesn't change much.
There is really nothing that can be done here.
You can do this on your `configuration.nix` if you don't care about the security risks:
```nix
  nixpkgs.config.permittedInsecurePackages = [
    "electron-11.5.0"
  ];
```

**Comment by davidak** [comment]
Upstream issue: https://github.com/itchio/itch/issues/2839
