### ISSUE TITLE
trustedGrub build broken

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nixpkgs#22099]
## Issue description

TrustedGrub fails to build.
```
make[2]: *** [Makefile:7543: libgrubmods_a-grub_script.yy.o] Error 1
```
### Steps to reproduce
```
nix-build '<nixpkgs>' -A trustedGrub
```
## Technical details

* System: 17.03pre98682.f673243 (Gorilla)
* Nix version: 1.11.4
* Nixpkgs version: 17.03pre98682.f673243

**Comment by yorickvP** [comment]
It seems to be. Should this be worked around in the same way?

**Comment by yegortimoshenko** [comment]
Not anymore:

```
$ nix-build ~/Projects/nixpkgs/ -A trustedGrub
[...]
```

**Comment by yorickvP** [comment]
Still doesn't compile, but I wonder if anyone still uses it.
