### ISSUE TITLE
Build failure: netboot on aarch64-linux

### ISSUE THREAD

**Issue by javaonekenobi** [NixOS/nixpkgs#220994]
I'm trying to build the netboot files for a raspberry pi, I tried both on an Ampere aarch64 and on the rRPI itself, I alwasy get this error sometimes it happens directly in the netboot.drv, sometimes in replace-initrd-secrets.drv

1. nix-build '<nixpkgs/nixos/release.nix>' -A netboot
2. also tried -A netboot.aarch64-linux and adding --option system aarch64-linux, same results.

### Build log

error: a 'x86_64-linux' with features {} is required to build '/nix/store/jbyl55lz04dmfv6blcc47zqsn38568rh-netboot.drv', but I am a 'aarch64-linux' with features {benchmark, big-parallel, gccarch-armv8-a, kvm, nixos-test}

### Additional context
I altro tried cross compiling on a x86_64 machine but I get the same error when it gets to replace-initrd-secrets.drv

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```
this path will be fetched (0.06 MiB download, 0.30 MiB unpacked):
  /nix/store/x1q75v4ysr72w4x6c713cpf1dmfg18cq-bash-interactive-5.1-p16-dev
copying path '/nix/store/x1q75v4ysr72w4x6c713cpf1dmfg18cq-bash-interactive-5.1-p16-dev' from 'https://cache.nixos.org'...
 - system: `"aarch64-linux"`
 - host os: `Linux 5.15.85, NixOS, 22.05 (Quokka), 22.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.1`
 - channels(root): `"nixos-22.05pre-git"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by kirillrdy** [comment]
@javaonekenobi sorry i dont have any expirience in this area
but it looks like neboot builds on aarch64-linux, please test this PR https://github.com/NixOS/nixpkgs/pull/221300

**Comment by javaonekenobi** [comment]
Thanks for the answer, I'll try applying the fix, I'll let you know how it goes.
