### ISSUE TITLE
buildDotnetModule: solution-level --output option no longer valid for build-related commands

### ISSUE THREAD

**Issue by anpin** [NixOS/nixpkgs#220985]
### Describe the bug
Current implementation of build hooks for `buildDotnetModule` is emitting warning `NETSDK1194` due to the breaking change in sdk (https://github.com/dotnet/sdk/pull/29065 and [docs](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid)) 

### Steps To Reproduce
Solution has to contain multiple projects with `<IsPackable>true</IsPackable>` and at least one of them must reference another project from the same solution 
1. `git clone https://github.com/anpin/buildDotnetModuleReporduce`
2. `nix build && nix log` to to observe NETSDK1194
3. Go to `flake.nix` and `uncomment nixpkgs.url`
4. Run `nix build && nix log` again to see warning gone

### Expected behavior
No warnings

### Additional context
The docs above are mentioning some ways to mitigate the issue such as `dotnet build --property:OutputPath=DESIRED_PATH` or  `dotnet pack --property:PackageOutputPath=DESIRED_PATH`, but they were failing builds of some existing packages, so I had to change it to  `dotnet build --p:OutputPath=DESIRED_PATH` or  `dotnet pack --p:PackageOutputPath=DESIRED_PATH`

### Notify maintainers

@IvarWithoutBones @corngood  @mdarocha  @epetousis @SuperSandro2000 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.94, NixOS, 23.05 (Stoat), 23.05.20230304.3c5319a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(a): `"nixpkgs"`
 - channels(root): `"nixos"`
 - nixpkgs: `/home/a/.nix-defexpr/channels/nixpkgs`
```

**Comment by mdarocha** [comment]
I believe this issue can be closed, since the `--output` deprecation was reverted in 7.0.201, and didn't come back in any other dotnet version. The warning is valid and I don't think we should add workarounds to avoid it.

The `netcoredbg` you mentioned was unrelated and was fixed
