### ISSUE TITLE
Rootless podman service fails to start

### ISSUE THREAD

**Issue by DCsunset** [NixOS/nixpkgs#221084]
### Describe the bug

Systemd user service `podman.service` for rootless podman will show the following errors when started:
`Error: command required for rootless mode with multiple IDs: exec: "newuidmap": executable file not found in $PATH`

When I add `shadow` package to override the path of the systemd user service, a new error would occur:

```
newuidmap: write to uid_map failed: Operation not permitte
should have setuid or have filecaps setuid: exit status 1
```

### Steps To Reproduce
1. Set `virtualisation.podman.enable = true` in `/etc/nixos/configuration`
2. Start `podman.service` after login.

### Expected behavior

The user service `podman.service` should be started without error.

### Notify maintainers

@zowoq @pennae 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.2.5, NixOS, 23.05 (Stoat), 23.05pre462605.5a1dc8acd97`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by zowoq** [comment]
> 545c7a31e5d

There have been a few changes to podman since this commit, please update your nixpkgs.

**Comment by DCsunset** [comment]
Hi, Thanks for your reply. I've updated nixpkgs and updated the metadata in this issue. However, `podman.service` still fails to start and the error message is the same

**Comment by DCsunset** [comment]
After removing the shadow package, it now works without problem. Thank you very much!

**Comment by jkozak** [comment]
I get exactly the same issue.

I'm building and deploying to AWS with `morph`, pinning `nixpkgs` to commit
`abb2ade261c33516716aa21068d8c10c48d03367`.  Should I be using a later commit?

```console
[flatland@ec2-lucia:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.101, NixOS, 22.11 (Raccoon), 22.11.3139.67f26c1cfc5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
