### ISSUE TITLE
Update request: various libreoffice packages

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#221008]
I'm not using the regular form as libreoffice-(fresh|still|qt) are all affected.

 - fresh is v7.4.2.3 in unstable but should be 7.5.2.1
 - still is v7.3.7.2 but should be 7.4.6.2

I will not have time to look at this in the next 2 weeks or so, so just putting out there for others.

Cc: @doronbehar @7c6f434c

**Comment by doronbehar** [comment]
Hmm, [the website lists version 7.5.1.2](https://www.libreoffice.org/download/download-libreoffice/) as the latest, but version 7.5.2.1 is available [at the download website](https://download.documentfoundation.org/libreoffice/src/7.5.2/). Here's an untested PR (Don't have time to build it right now), with at least the hashes updated: https://github.com/NixOS/nixpkgs/pull/221192
