### ISSUE TITLE
Package request: fastfetch

### ISSUE THREAD

**Issue by hervyqa** [NixOS/nixpkgs#221150]
**Project description**

Fastfetch is a [neofetch](https://github.com/dylanaraps/neofetch)-like tool for fetching system information and displaying them in a pretty way. It is written mainly in C, with performance and customizability in mind. Currently, Linux, Android, FreeBSD, MacOS and Windows 7+ are supported.

**Metadata**

* homepage URL: https://github.com/LinusDierheimer/fastfetch
* source URL: https://github.com/LinusDierheimer/fastfetch/releases
* license: MIT license
* platforms: unix, linux, darwin.

**Comment by pinn3** [comment]
Duplicate of https://github.com/NixOS/nixpkgs/issues/176799

**Comment by sogreatandpowerfull** [comment]
@hervyqa FYI, It's available NUR: `nur.repos.vanilla.fastfetch`
