### ISSUE TITLE
Update request: pandoc 2.19.2 → 3.1.1

### ISSUE THREAD

**Issue by mhwombat** [NixOS/nixpkgs#221165]
- Package name: pandoc
- Latest released version: 3.1.1

- Current version on the unstable channel: 2.19.2
- Current version on the stable/release channel: 2.17.1.1

- [x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@peti 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by seam345** [comment]
I would like to preface with "I have no idea what I was doing" but I was able to get it to compile with these changes from master https://github.com/seam345/nixpkgs/commit/89e6e477c8357a087e863db562d2fa8d9fe5ba29
```
$ nix-shell -p haskellPackages.pandoc-cli -I nixpkgs=https://github.com/seam345/nixpkgs/archive/89e6e477c8357a087e863db562d2fa8d9fe5ba29.tar.gz
$ pandoc --version
pandoc 3.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/sean/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

This **may** be helpful to the person who actually understands how all the Haskell things work todo it properly, or if someone just wants to grab it from my branch for now :)

**Comment by chkno** [comment]
The trouble with https://github.com/seam345/nixpkgs/commit/89e6e477c8357a087e863db562d2fa8d9fe5ba29 is that pkgs/development/haskell-modules/hackage-packages.nix is routinely auto-regenerated, so changes made there by hand will be quickly lost.  pkgs/development/haskell-modules/HACKING.md describes the auto-regeneration process.

The auto-generation pulls version information from stackage.  Pandoc versions in stackage:

| Resolver | GHC version | Pandoc version |
| ---------- | ------------- | ------------ |
| lts-19.33 | 9.0.2 | 2.17.1.1 |
| lts-20.11 | 9.2.5 | 2.19.2 |
| lts-20.12 | 9.2.6 | 2.19.2 |
| lts-20.16 | 9.2.7 | 2.19.2 |
| nightly-2023-04-02 | 9.4.4 | 3.0.1 |

When i try various ways of following the HACKING.md process, I get these failures:

| Method | Target | Failure in | Error message |
| ---------- | --------- | ------------------- | ------------------- |
| HEAD | haskellPackages.pandoc_3_1_1 | pandoc-3.1.1 | Setup: Encountered missing or private dependencies: doctemplates >=0.11 && <0.12, gridtables >=0.1 && <0.2, jira-wiki-markup >=1.5 && <1.6, mime-types >=0.1.1 && <0.2, pandoc-types >=1.23 && <1.24, texmath >=0.12.6 && <0.13 |
| HEAD | haskell.packages.ghc944.pandoc_3_1_1 | string-qq-0.0.4 | Error: Setup: Encountered missing or private dependencies: text >=1.2 && <1.3 |
| resolver: LTS |  haskellPackages.pandoc_3_1_2 | pandoc-3.1.2 | Setup: Encountered missing or private dependencies: doctemplates >=0.11 && <0.12, gridtables >=0.1 && <0.2, jira-wiki-markup >=1.5.1 && <1.6, mime-types >=0.1.1 && <0.2, pandoc-types >=1.23 && <1.24, texmath >=0.12.7 && <0.13 |
| resolver: LTS | haskell.packages.ghc944.pandoc_3_1_2 | evaluation | error: attribute 'lens_5_2_1' missing |
| resolver: LTS + lens reference fix | haskell.packages.ghc944.pandoc_3_1_2 | string-qq | Error: Setup: Encountered missing or private dependencies: text >=1.2 && <1.3 |
| resolver: LTS + drop restrictions in update-stackage.sh | pandoc | pandoc-3.1.2 | Setup: Encountered missing or private dependencies: doctemplates >=0.11 && <0.12, gridtables >=0.1 && <0.2, jira-wiki-markup >=1.5.1 && <1.6, mime-types >=0.1.1 && <0.2, pandoc-types >=1.23 && <1.24, texmath >=0.12.7 && <0.13 |
| resolver: LTS + drop restrictions in update-stackage.sh | haskell.packages.ghc944.pandoc | evaluation | error: attribute 'lens_5_2_1' missing |
| resolver: LTS + drop restrictions in update-stackage.sh + lens reference fix | haskell.packages.ghc944.pandoc | string-qq | Error: Setup: Encountered missing or private dependencies: text >=1.2 && <1.3 |
| resolver: Nightly | pandoc | evaluation | error: infinite recursion encountered |
| resolver: Nightly | haskellPackages.pandoc_3_1_2 | evaluation | error: infinite recursion encountered |
| resolver: Nightly | haskell.packages.ghc944.pandoc | evaluation | error: attribute 'aeson_2_1_2_1' missing |
| resolver: Nightly | haskell.packages.ghc944.pandoc_3_1_2 | evaluation | error: attribute 'aeson_2_1_2_1' missing |

I don't know where to go from here.

**Comment by chkno** [comment]
History: 2022 Nov: [Latest pandoc [2.19.2] does not build](https://discourse.nixos.org/t/latest-pandoc-does-not-build/22911)

Trying another tack: 

| Method | Target | Failure in | Error message |
| --------- | --------- | ------------- | ------------------- |
| HEAD | haskellPackages.pandoc_3_1_1 | pandoc-3.1.1 | Setup: Encountered missing or private dependencies: doctemplates >=0.11 && <0.12, gridtables >=0.1 && <0.2, jira-wiki-markup >=1.5 && <1.6, mime-types >=0.1.1 && <0.2, pandoc-types >=1.23 && <1.24, texmath >=0.12.6 && <0.13 |
| HEAD | haskell.packages.ghc944.pandoc_3_1_1 | string-qq-0.0.4 | Error: Setup: Encountered missing or private dependencies: text >=1.2 && <1.3 |
| HEAD + doJailBreak | haskellPackages.pandoc_3_1_1 | pandoc-3.1.1 | src/Text/Pandoc/Shared.hs:850:17: error: Not in scope: data constructor ‘Figure’ |
| HEAD + doJailBreaks | haskell.packages.ghc944.pandoc_3_1_1 | pandoc-3.1.1 | src/Text/Pandoc/Shared.hs:850:17: error: Not in scope: data constructor ‘Figure’ |
| HEAD + doJailBreak + pandoc-types_1_23 | haskellPackages.pandoc_3_1_1 | pandoc-3.1.1 | src/Text/Pandoc/Parsing/GridTable.hs:141:16: error: Not in scope: ‘GT.arrayTableFoot’ NB: the module ‘Text.GridTable’ does not export ‘arrayTableFoot’.  Suggested fix: Perhaps use ‘GT.arrayTableHead’ (imported from Text.GridTable) |
| HEAD + doJailBreaks + pandoc-types_1_23 | haskell.packages.ghc944.pandoc_3_1_1 | pandoc-3.1.1 | src/Text/Pandoc/Parsing/GridTable.hs:141:16: error: Not in scope: ‘GT.arrayTableFoot’ NB: the module ‘Text.GridTable’ does not export ‘arrayTableFoot’.  Suggested fix: Perhaps use ‘GT.arrayTableHead’ (imported from Text.GridTable) |
| HEAD + doJailBreak + pandoc-types_1_23 + gridtables_0_1_0_0 | haskellPackages.pandoc_3_1_1 | pandoc-3.1.1 | /nix/store/...-binutils-2.40/bin/ranlib: unable to copy file 'dist/build/libHSpandoc-3.1.1-3qgYOMb5A4LEp1wMeZkvJA-ghc9.2.7.a'; reason: Success |
| HEAD + doJailBreaks + pandoc-types_1_23 + gridtables_0_1_0_0 | haskell.packages.ghc944.pandoc_3_1_1 | pandoc-3.1.1 | /nix/store/...-binutils-2.40/bin/ranlib: unable to copy file 'dist/build/libHSpandoc-3.1.1-3qgYOMb5A4LEp1wMeZkvJA-ghc9.2.7.a'; reason: Success |

So [this way](https://github.com/NixOS/nixpkgs/compare/master...chkno:nixpkgs:pandoc3-wip) seems to get much closer, but still doesn't quite get there.

**Comment by undefined-moe** [comment]
Now it's pandoc 3.1.2 with typst support added :)

**Comment by turion** [comment]
I'm completely puzzled by `string-qq-0.0.4` and `Error: Setup: Encountered missing or private dependencies: text >=1.2 && <1.3`. `string-qq` doesn't even seem to depend on `text`.

**Comment by disbolog** [comment]
Pandoc's Jgm has updated the flake in repo's root, would that be of any help?
https://github.com/jgm/pandoc/issues/8818

**Comment by camillemndn** [comment]
Hi, if like myself you don't want to wait for Pandoc to get updated, this solution works:
https://github.com/camillemndn/nixos-config/blob/main/pkgs/development/tools/pandoc/default.nix

**Comment by sternenseemann** [comment]
#240387 will contain the update for nixpkgs.
