### ISSUE TITLE
thunderbird + enigmail fails decrypt/encrypt/sign message

### ISSUE THREAD

**Issue by Unode** [NixOS/nixpkgs#22120]
## Issue description
When trying to sign, encrypt or decrypt a message with a gnupg key that is not open in the active gpg agent, thunderbird/enigmail displays a pop-up with an error stating that it failed to encrypt/decrypt the message.

### Steps to reproduce
* Flush your keychain/gpg-agent to ensure all keys are unloaded/removed.
* Run thunderbird. 
* Install the enigmail addon and configure it to use a private key
* Restart thunderbird
* In enigmail's settings, ensure it locates the gpg2 binary correctly
* Create a new private key if necessary
* Start a new message, select to sign and encrypted message.
* Send the message to yourself. (this should fail or prompt for a password before sending)

In the last step I don't see a password prompt and I see the pop-up error almost immediately.

### Notes
I'm currently not sure if the issue is caused by gpg2 failing to display a password prompt (failing to start pinentry-gtk or anything gui?) or some other reason.
* Using `gpg2` directly from the terminal shows a graphical (GUI) pinentry.
* I don't have any explicit pinentry binary on my `gpg-agent.conf` or `gpg.conf`.

## Technical details

* System: (NixOS: 16.09.1512.6b28bd0 (Flounder))
* Nix version: (1.11.6)

**Comment by vcunat** [comment]
Enigmail seems to work OK for me, popping up for passphrase if needed, but perhaps there's some significant detail different in my setup, e.g. I have additionally `gnupg1compat` package.

**Comment by lheckemann** [comment]
Works for me, I don't have gnupg1compat. I don't have an explicit pinentry configured either.

**Comment by Unode** [comment]
What kind of X desktop/window manager do you have? I have awesomewm if that matters.

I've come to notice that gpg-agent as well as ssh-agent get initialized by systemd. I used to use [keychain](www.funtoo.org/Keychain) but this also seems to have issues interacting with the gpg-agent.

On another note, if I kill the running gpg-agent and then start it manually thunderbird then shows me the password prompt and doesn't ask for a while which I understand as it using the new agent.

Could it somehow be that the environment used by systemd to spawn the agent is somehow incorrect leading to an inability to open the password dialog or to default to a console only pinentry which immediately fails?

Any suggestions on how to debug this further?

**Comment by vcunat** [comment]
I have xfce4-session (with XMonad), but I don't remember now how the agent(s) are started.

**Comment by lheckemann** [comment]
I'm on i3. I also just realised that I have no idea when my gpg agent is spawned; I don't see it mentioned in any of the files that start up my session. I suspect that it might be started by the client on demand. @Unode, what happens if you kill the running agent then try to use clients without manually restarting it? And do you know where the initially started agent keeps its sockets? (try `lsof -p $(pgrep gpg-agent)`)

**Comment by Unode** [comment]
I forgot to mention that I use `slim` as graphical login manager. It's the default after installation.

`lsof -c gpg-agent` gives me `/run/user/1000/gnupg/S.gpg-agent` in both cases (login and after kill).

One thing I also noticed is that after killing `gpg-agent` and confirming that no process is running nor started automatically, the moment I select an encrypted or signed message in Thunderbird, I see a password prompt and at this point a new `gpg-agent` is already running.
I don't know if this is a new feature with gnupg2 or some other systemd or otherwise magic.

I though `gpg-agent` was started by systemd but after further inspection it turns out that only `ssh-agent` is actually spawned. I don't know what spawns `gpg-agent` the first time.

I haven't tested it but considering the above, I may be able to workaround the issue by simply killing the agent moments after login.

**Comment by jbgi** [comment]
Had the exact same symptoms. Not using `keychain` to auto-start `gpg-agent` fixed the issue.

**Comment by Unode** [comment]
Indeed with the newer `gnupg` it gets started on demand as @lheckemann mentioned.
The issue seems to be that if the `gpg-agent` gets spawned in a non-X environment it doesn't know where to show the `pinentry` dialog.
Not starting the agent immediately after login and delaying it until its needed is usually sufficient since at that time X is likely running. I still get some issues if I login first on the console but I can workaround those.

In any case this seems more of a gnupg issue not specific to NixOS.
Thanks everyone and @jbgi for confirming.
