### ISSUE TITLE
Bundler installs gems using the wrong ruby

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#22127]
## Issue description

Bundler installs gems into the wrong directory as it uses the ruby on which it depends and ignores what you have chosen

Cc: @zimbatm @cstrahan 

### Steps to reproduce

1. Install ruby_2_4 into the system environment
2. Create a test directory ```mktemp -d``` and put the following files in:

Gemfile:
```ruby
source 'https://rubygems.org'
gem 'rake'
```
.envrc:
```sh
use nix -p bundler
layout ruby
```
3. Now ```direnv allow``` and ```bundle install --path $GEM_HOME```.

The problem is, that bundler has a dependency on ruby 2.3.3 (as of today) and so will install the gem into ```.direnv/ruby/ruby/2.3.3``` and not ```.direnv/ruby/ruby/2.4.0``` which means that trying to run ```rake -T```, you will get an error like "Your bundle is locked to rake (12.0.0), but that version could not be found..."

Running ```bundle exec rake -T``` works, because ruby 2.3.3 is used.

## Technical details

* NixOS: 17.03.git.c33f79c16aM (Gorilla)
* Nix: nix-env (Nix) 1.11.5
* nixpkgs: 17.03.git.c33f79c16aM

**Comment by zimbatm** [comment]
How do you select the version of ruby that's available?

The issue is a limitation of bundler. It has to be installed with the same version of ruby that you are using. If you are using rvm or other ruby version switcher then install bundler with that tool. For a pure nix solution use something like this:
```nix
{}:
let
  pkgs = import <nixpkgs> {};
  stdenv = pkgs.stdenv;
  ruby = ruby_2_3;
  bundler = bundler.override { inherit ruby; };
in
  stdenv.mkDerivation {
    name = "name";
    buildInputs = [ ruby bundler ];
  }
```

**Comment by peterhoeg** [comment]
I was looking for the pure nix way of doing - overriding the ruby dependency for bundler does indeed do the trick:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  ruby = pkgs.ruby_2_4;
  bundler = pkgs.bundler.override { inherit ruby; };

in pkgs.stdenv.mkDerivation rec {
  name = "org";

  buildInputs = [
    bundler
    ruby
  ] ++ (with pkgs; [
    gcc
    libffi
    nwdiag
  ]);
}
```

Thanks @zimbatm !

**Comment by zimbatm** [comment]
There is also the ruby `dev` passthru who contains both bundix and bundler for the selected ruby version. I'm not sure if I want to keep that in the future though as the whole development story is not streamlined yet.
