### ISSUE TITLE
systemd-networkd config rejects special option "none" for netdev MACAddress

### ISSUE THREAD

**Issue by jrouleau** [NixOS/nixpkgs#221348]
Netdev MACAddress field should accept special value of "none" but is rejected with error:
```
Systemd Netdev field `MACAddress' must be a valid mac address.
```

[systemd.netdev(5)](https://www.freedesktop.org/software/systemd/man/systemd.netdev.html):
```
[NETDEV] SECTION OPTIONS
[...]
       MACAddress=
           Specifies the MAC address to use for the device, or takes the special value "none". When "none", systemd-networkd does
           not request the MAC address for the device, and the kernel will assign a random MAC address. [...]
```

https://github.com/NixOS/nixpkgs/blob/ac718d02867a84b42522a0ece52d841188208f2c/nixos/modules/system/boot/networkd.nix#L167

**Comment by flokli** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/241365.
