### ISSUE TITLE
Build failure: colima

### ISSUE THREAD

**Issue by devusb** [NixOS/nixpkgs#221378]
### Steps To Reproduce

1. build colima on darwin or aarch64-linux

### Build log

https://hydra.nixos.org/build/212378003/log
https://hydra.nixos.org/build/212051803/log

### Additional context

Seems to still build successfully on x86_64-linux (https://hydra.nixos.org/build/212049981/log).

### Notify maintainers

@aaschmid @tricktron 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.3.0, macOS 13.2.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.14.1`
 - channels(root): `"nixpkgs"`
 - channels(mhelton): `"home-manager"`
 - nixpkgs: `/nix/store/rmw0kq593g38kj9dwpg5ka81bbskh9dm-source`
```

**Comment by tricktron** [comment]
@devusb Thanks for reporting. The `Test_extractZones` seems to be flaky.  I opened a pr to disable it so that the hydra build should succeed again.
