### ISSUE TITLE
NIX_LIB64_IN_SELF_RPATH leaks through to cross-builds

### ISSUE THREAD

**Issue by eliasnaur** [NixOS/nixpkgs#221350]
### Describe the bug
`lib64` directories are added to linker rpath flags for cross-compilation to platforms that don't need them.

### Steps To Reproduce
1. `nix build -L github:eliasnaur/nix-lib64-rpath` on a x86_64-linux system

output:

```
...
demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf> CC armv6l-unknown-linux-gnueabihf-gcc
demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf> NIX_LDFLAGS: -rpath /nix/store/lskdn4fvvjlz53dxkbkgb1x2dy4zkf7k-demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf/lib64 -rpath /nix/store/lskdn4fvvjlz53dxkbkgb1x2dy4zkf7k-demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf/lib
...
```

Note the `lib64` directory added to `NIX_LDFLAGS`.

See full build log at https://github.com/eliasnaur/nix-lib64-rpath/actions/runs/4428890865/jobs/7768605092.

Running the same command on a aarch64-darwin configuration (with a aarch64-linux builder configured):

```
% nix build -L
...
demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf> CC armv6l-unknown-linux-gnueabihf-gcc
demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf> NIX_LDFLAGS: -rpath /nix/store/sw8ymyqpavw0v4hl01q0xb9c9wr50v9z-demonstrate-lib64-rpath-armv6l-unknown-linux-gnueabihf/lib
...
```

Note that `NIX_LDFLAGS` doesn't contain a `lib64` directory.

### Expected behavior
`NIX_LDFLAGS` should not contain `lib64` directories when cross-compiling for non-x86_64-linux platforms.

### Additional context
Adding `lib64` to NIX_LDFLAGS is generally benign, except that I'm trying to achieve [bit-for-bit reproducible](https://discourse.nixos.org/t/bit-for-bit-reproducible-images-for-raspberry-pi/26333) builds. The extra `lib64` entries end up in slightly larger ELF sections that can't be saved by careful use of `patchelf`.

**Comment by eliasnaur** [comment]
I believe this is the offending line:

https://github.com/NixOS/nixpkgs/blob/4700c7a64bbb80783ed21c2f0a501c43a98a8829/pkgs/stdenv/linux/default.nix#L118

but I'm not sure whether the `x86_64-linux` check should be moved elsewhere or whether the check should use something else than `system`.

**Comment by amjoseph-nixpkgs** [comment]
> check should be moved elsewhere or whether the check should use something else than `system`.

The check should definitely be using `stdenv.hostPlatform`.  But you would need to thread `stdenv.hostPlatform.isx86_64` through as a new environment variable.  As you point out in #223861, it would be better to just stop adding these `-rpath` flags if possible.

**Comment by abathur** [comment]
Closing since it sounds like the merge of https://github.com/NixOS/nixpkgs/pull/223861 resolved this. Happy to reopen if I'm mistaken.
