### ISSUE TITLE
Update request: lfe 1.3 → 2.1.1

### ISSUE THREAD

**Issue by f3zhead** [NixOS/nixpkgs#221426]
- Package name: lfe (Lisp Flavored Erlang)
- Latest released version: 2.1.1

- Current version on the unstable channel: 1.3
- Current version on the stable/release channel: 1.3

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by superherointj** [comment]
@f3zhead Please test. Tracking: https://nixpk.gs/pr-tracker.html?pr=222411
But you can use nixpkgs-review too.

At nixpkgs git directory:
- `nix run github:mic92/nixpkgs-review pr 222411`
