### ISSUE TITLE
Firefox gets 'stuck' while starting for the first time

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#221452]
When starting Firefox from the GNOME dock on a new login session, it gets 'stuck': there are firefox processes running (and starting Firefox again correctly gives the 'firefox is already running but not responding' error). After killing it, starting it again seems to work fine.

I can reproduce this fairly reliably on a newly-installed NixOS unstable machines with GNOME. (I don't see it on my regular development laptop with NixOS unstable and sway, though)

/cc @hexa @lovesegfault

**Comment by bradb423** [comment]
I'm pretty certain I've had this issue before, both on GNOME with Wayland.

Have you tried using the environment variables: `MOZ_ENABLE_WAYLAND=1` and `XDG_CURRENT_DESKTOP=sway` ?

You can find more about them here: https://nixos.wiki/wiki/Firefox (Scroll to the bottom of the section labelled `Wayland`)

**Comment by raboof** [comment]
this *may* no longer be happening on latest nixos-unstable (897876e4c484f1e8f92009fd11b7d988a121a4e7), at least on one new machine it seemed fine. Closing for now.
