### ISSUE TITLE
What to do with the broken harmonia package

### ISSUE THREAD

**Issue by Mic92** [NixOS/nixpkgs#221498]
[Harmonia](https://github.com/helsinki-systems/harmonia) (a nix-serve alternative written in rust) in nixpkgs is currently broken. A functional [fork](https://github.com/nix-community/harmonia/) exists.

I had asked the people behind the project already what to do with. Response was like that:

> I don't know 100% how to deal with this. Because actually i want to keep supporting harmonia but i'm really busy right now. i'm sorry we haven't upstreamed harmonia into the nixpkgs either, the package in our repo is still building. just against nix2.11 iirc

So they are still using the project but they do not see maintaining a nixpkgs package as their priority. I didn't wanted to steal their name from them either.

https://github.com/NixOS/nixpkgs/pull/221320

Please thumbs up or down if we should switch to nix-community fork.

**Comment by AndersonTorres** [comment]
Can we ask them to let us adopt it?

**Comment by Mic92** [comment]
There seems to be not so much development on their part. They might merge again later with us. I am in close contact with the current upstream.

**Comment by Mic92** [comment]
See https://github.com/NixOS/nixpkgs/issues/221498

**Comment by Mic92** [comment]
I don't know why this is marked as complete. The pull request is still open and the problem not solved yet.

**Comment by Mic92** [comment]
PR was merged
