### ISSUE TITLE
Update request: python3Packages.torch 1.13.1 → 2.0.0

### ISSUE THREAD

**Issue by alex007sirois** [NixOS/nixpkgs#221545]
- Package name: python3Packages.torch
- Latest released version: 2.0.0

- Current version on the unstable channel: 1.13.1
- Current version on the stable/release channel: 1.12.1

- [ x ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@teh
@thoughtpolice
@tscholak

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by junjihashimoto** [comment]
This PR is for torch-bin.
https://github.com/NixOS/nixpkgs/pull/221652

**Comment by SomeoneSerge** [comment]
And the source-build: https://github.com/NixOS/nixpkgs/pull/222273

**Comment by alex007sirois** [comment]
https://github.com/NixOS/nixpkgs/pull/227420
https://github.com/NixOS/nixpkgs/pull/222273
