### ISSUE TITLE
nixos-generate-config suggests invalid Nix

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nixpkgs#221510]
### Describe the bug
`nixos-generate-config` generates the following commented out invalid syntax:
```
  # Configure keymap in X11
  # services.xserver.layout = "us";
  # services.xserver.xkbOptions = {
  #   "eurosign:e";
  #   "caps:escape" # map caps to escape.
  # };
```
Perhaps `= [ ... ]` was intended?

### Steps To Reproduce
1. `nixos-generate-config`
2. View `configuration.nix`

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.102, NixOS, 22.11 (Raccoon), 22.11.3184.9b8e5abb183`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11.3184.9b8e5abb183"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by paumr** [comment]
Nice catch!
`xkbOptions` requires a comma separated string.

I submitted a PR which will fix this issue.
