### ISSUE TITLE
virt-manager does not display device information from pci.ids file

### ISSUE THREAD

**Issue by jonhermansen** [NixOS/nixpkgs#221592]
### Describe the bug
When viewing the list of PCI devices in my system, virt-manager only displays the bus/device/function numbers of each. It does not give any descriptive information, which is usually pulled from `/usr/share/misc/pci.ids` or similar

### Steps To Reproduce
1. Open virt-manager
2. File -> New Virtual Machine
3. Continue through VM creation steps. The details are not necessary - you do not need to boot the VM
4. View hardware details for the virtual machine
5. Click "Add Hardware"
6. Click "PCI Host Device"

### Expected behavior
PCI devices in my system are listed with bus/device/function numbers as well as vendor / product description.

### Screenshots
What the UI should look like:
![image](https://user-images.githubusercontent.com/660911/225806051-04d74a28-2e0a-4b48-a644-4abbfe411e2f.png)

What it looks like on NixOS:
![Screenshot from 2023-03-16 23-33-19](https://user-images.githubusercontent.com/660911/225806159-f9c44414-e9bc-4c59-bf85-82edcd88afab.png)

### Additional context
Following nixos-unstable channel
virt-manager-4.1.0

### Notify maintainers
@qknight @offline @fpletz @globin @K900

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.6, NixOS, 23.05 (Stoat), 23.05pre464727.ac718d02867`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by abathur** [comment]
Closing since it sounds like this was fixed by the merge of #221885. Happy to reopen if I'm mistaken.
