### ISSUE TITLE
Enabling both kde5 and gnome3 breaks the build

### ISSUE THREAD

**Issue by ToxicFrog** [NixOS/nixpkgs#22155]
## Issue description

Enabling both `services.xserver.desktopManager.kde5` and `services.xserver.desktopManager.gnome3`; when trying to build the hwdb configuration, multiple packages try to provide `etc/udev/hwdb.d/69-libmtp.hwdb` and it explodes.

### Steps to reproduce

    services.xserver = {
      enable = true;
      displayManager.sddm.enable = true;
      desktopManager.kde5.enable = true;
      desktopManager.gnome3.enable = true;
    };

    # nixos-rebuild build
    building path(s) ‘/nix/store/p86lcc8ispms486kvyjm0il7snn5lk1a-hwdb.bin’
    Adding hwdb files for package /nix/store/5vvrpxviq3xp3fmizin2lmbxwp56rng0-systemd-231
    Adding hwdb files for package /nix/store/bx3cjvvpiiknf54x7pfzg2zi2y17f5h8-gnome-settings-daemon-3.20.1
    Adding hwdb files for package /nix/store/j7y2flk73668j2vk7w91ijl8zimkdc65-libmtp-1.1.11-bin
    Adding hwdb files for package /nix/store/100h7y9525ci6rkx93hrj1wd2fh90cqd-media-player-info-22
    Adding hwdb files for package /nix/store/g6fg06gnzi16z2alapd3y65dh1m8jkfb-mdadm-3.3.4
    Adding hwdb files for package /nix/store/asj0gw12yyixg2kc2smvhi7bimg7b1k3-lvm2-2.02.140
    Adding hwdb files for package /nix/store/9bvgmm6lfji4jq3xpv6c2fa7lwzndar6-zfs-user-0.6.5.8
    Adding hwdb files for package /nix/store/hr77n8z83976gfgfg40lbxxzf40d9n6p-xf86-input-wacom-0.32.0
    Adding hwdb files for package /nix/store/0d3454snfpkvli0wzn0r6i6qazcivjwx-libinput-1.3.3
    Adding hwdb files for package /nix/store/99gnhbl66s6hckpq1h2jc1qx0hdp2nps-colord-1.2.12
    Adding hwdb files for package /nix/store/p78bly6yza3g2vrsw83h6q6qhac58y9b-ModemManager-1.4.16
    Adding hwdb files for package /nix/store/7gvskrjl8l3p3c6g84391kyfbsaf7iik-network-manager-1.2.4
    Adding hwdb files for package /nix/store/zvgm9j3k7j8ir8jy7k4jpzj0h43l2k8y-NetworkManager-l2tp-gnome-1.2.4
    Adding hwdb files for package /nix/store/7p0wl7l2afy0fldxar3zsqaiy6px31c7-NetworkManager-openconnect-gnome-1.2.2
    Adding hwdb files for package /nix/store/l7bsk2pgc46ak2fnkrj4wsvs5n7vr5y6-NetworkManager-openvpn-gnome-1.2.6
    Adding hwdb files for package /nix/store/bpjlkiazpx7lwl9kb9b55vks6gwck965-NetworkManager-pptp-gnome-1.2.4
    Adding hwdb files for package /nix/store/npq9p3g346dmpfkp6liz74xkkdzr0w12-NetworkManager-vpnc-gnome-1.2.4
    Adding hwdb files for package /nix/store/biyifsvmvkfbwf9v0fmgn358badz06a8-wpa_supplicant-2.5
    Adding hwdb files for package /nix/store/q23i8f5j59jf7ypdya9y9512h1c0jcvv-upower-0.99.4
    Adding hwdb files for package /nix/store/5b39mw2k89vzgk7gqxagi6fgcqiwv8sr-udisks-2.1.6
    Adding hwdb files for package /nix/store/px3736lmrqr6xb6s38h0b79l07rb6v0m-extra-udev-rules
    Adding hwdb files for package /nix/store/q7vln9j7xni7cfz5r03n2mizna22g3a7-extra-hwdb-file
    Adding hwdb files for package /nix/store/2aqkijdw75mvnjgpkx692ijv01ih4vra-tlp-0.8
    Adding hwdb files for package /nix/store/yccbfikag361jz8hsd3rpnl0gmmbjj1y-bluez-5.40
    Adding hwdb files for package /nix/store/j7y2flk73668j2vk7w91ijl8zimkdc65-libmtp-1.1.11-bin
    ln: failed to create symbolic link 'etc/udev/hwdb.d/69-libmtp.hwdb': File exists
    builder for ‘/nix/store/w3hspvlrkwp1mc249i8z02vl06jnk6pv-hwdb.bin.drv’ failed with exit code 1
    [...]
    cannot build derivation ‘/nix/store/2h3wn6hxp2v7vpcvdlx1m4n37jjxfcz2-etc.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/ba5j6sj384f45c83szlr41z1bx7h5pr0-nixos-system-isis.ancilla.ca-16.09.1515.89c567c.drv’: 1 dependencies couldn't be built

## Technical details

System: 16.09.1512.6b28bd0 (Flounder)
Nix version: nix-env (Nix) 1.11.6
Nixpkgs version: "16.09.1515.89c567c"

**Comment by RonnyPfannschmidt** [comment]
there seem to be other collisions as well, i see them for gvfs as well

**Comment by hedning** [comment]
Think this is fixed, works for me on 17.03 after an update.

**Comment by RonnyPfannschmidt** [comment]
the hwdb issue was fixed by @abbradar
