### ISSUE TITLE
modules/config/resolvconf.nix: unconditionally installing openresolv

### ISSUE THREAD

**Issue by filakhtov** [NixOS/nixpkgs#221641]
### Describe the bug
Changes introduced in #166308 forcing `openresolv` package (or whatever the `networking.resolvconf.package` option is set to) installation even if the `networking.resolvconf.enable` set to `false`. This is because the `config/resolvconf.nix` module is unconditionally adding the package to the `environment.systemPackages`: https://github.com/NixOS/nixpkgs/blob/bdcedf61a096b34d33a014dccb998fdc9b8f5a22/nixos/modules/config/resolvconf.nix#L136

### Steps To Reproduce
1. Set both `networking.resolvconf.enable` and `services.resolved.enable` to `false` in order to avoid enabling the `resolvconf` service or systemd overriding the package with `systemd-resolved`.
2. Run `nixos-rebuild switch`
3. Check installed packages, for example using the `nix-store --query --requisites /run/current-system` command.

### Actual behavior
An `openresolv` package is installed into the system:
```console
[root@nixos:~]# nix-store --query --requisites /run/current-system | grep openresolv
/nix/store/cqis3kbabbifdg231ckc95m4mgygq3gs-openresolv-3.12.0

[root@nixos:~]# nix-store --query --referrers /nix/store/cqis3kbabbifdg231ckc95m4mgygq3gs-openresolv-3.12.0
/nix/store/cqis3kbabbifdg231ckc95m4mgygq3gs-openresolv-3.12.0
/nix/store/im82y09rfpfpp7vvah2hg93hr89yq1cv-system-path
```

### Expected behavior
An `openresolv` package should not be installed into the system.

### Additional context
I am on a quest to build a minimal NixOS system for usage in LXC containers and trying to trim things down to the minimum, without having to resort to forking, overriding, patching and maintaining individual modules. I am happy to open up a PR to move the package assignment to the `mkIf` block: https://github.com/NixOS/nixpkgs/blob/9b0777ffb3ab046e329af80a177d663387bf8f0f/nixos/modules/config/resolvconf.nix#L139 but would like to check if anyone has any objections or reasons why I shouldn't be doing so.

### Notify maintainers
👋🏻 @ncfavier @pennae @alyssais @flokli appreciate any insights 🙇🏻‍♂️ 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[root@nixos:~]# nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.85-1-pve, NixOS, 23.05 (Stoat), 23.05pre463258.7067edc68c0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by ncfavier** [comment]
As the author of that PR I have no objections to restoring the old behaviour.
