### ISSUE TITLE
xdg-user-dirs is currently broken (Freedesktop, NixOS desktop)

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#221604]
Reason: `xdg-user-dirs-update` is not called upon first login of the user.

---- Background, logs and outdated stuff
Functionality ("a way to customize the xdg-user-dirs") introduced in #33282 is currently broken.

In configuration.nix, this block is not executed and directories are not made.
```
environment.etc."xdg/user-dirs.defaults".text = ''
 DESKTOP=system/desktop
 DOWNLOAD=downloads
 TEMPLATES=system/templates
 PUBLICSHARE=system/public
 DOCUMENTS=documents
 MUSIC=media/music
 PICTURES=media/photos
 VIDEOS=media/video
'';
```

gives a 22.11 system with an env like this:
```
> env|grep -i xdg_config
XDG_CONFIG_DIRS=/nix/store/vvyh020yzcxg0dsdqbvarn4d0s7v7rh2-kio-5.100.0/etc/xdg:/nix/store/hawwx7wnmzmdy3m2m44z94j20nkmi8f1-kservice-5.100.0-bin/etc/xdg:/nix/store/yx5kn3pirxa8033plq518ms0nhhn6aj2-kxmlgui-5.100.0-bin/etc/xdg:/nix/store/8wzm110kbnapg3ljk56hfb53cqhrkjc2-plasma-workspace-5.26.4.1/etc/xdg:/nix/store/rgr8aynzyyzv8a67wxld1dcbgp0m8gc7-kdelibs4support-5.100.0/etc/xdg:/nix/store/n7fjqy7pnvfpnr20w9780kybclg5c10n-baloo-5.100.0/etc/xdg:/home/user/.config/kdedefaults:/etc/xdg:/home/user/.nix-profile/etc/xdg:/etc/profiles/per-user/user/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
```

^ notice above .. /home/user/.config/kdedefaults: **/etc/xdg** :/home/user/.nix-profile/etc/xdg: .. **:/run/current-system/sw/etc/xdg**

The only file in **/etc/xdg** is **user-dirs.defaults** containing changes matching configuration.nix:
```
> cat /etc/xdg/user-dirs.defaults 
DESKTOP=system/desktop
DOWNLOAD=downloads
TEMPLATES=system/templates
PUBLICSHARE=system/public
DOCUMENTS=documents
MUSIC=media/music
PICTURES=media/photos
VIDEOS=media/video
```

However, two stock files in **/run/current-system/sw/etc/xdg/** always override it:
```
> ls /run/current-system/sw/etc/xdg/user*
/run/current-system/sw/etc/xdg/user-dirs.conf
/run/current-system/sw/etc/xdg/user-dirs.defaults
```

```
> cat /run/current-system/sw/etc/xdg/user-dirs.conf 
# This controls the behaviour of xdg-user-dirs-update which is run on user login
# You can also have per-user config in ~/.config/user-dirs.conf, or specify
# the XDG_CONFIG_HOME and/or XDG_CONFIG_DIRS to override this
#

enabled=True
<. . . snip . . .>
```

```
> cat /run/current-system/sw/etc/xdg/user-dirs.defaults 
# Default settings for user directories
#
# The values are relative pathnames from the home directory and
# will be translated on a per-path-element basis into the users locale
DESKTOP=Desktop
DOWNLOAD=Downloads
TEMPLATES=Templates
PUBLICSHARE=Public
DOCUMENTS=Documents
MUSIC=Music
PICTURES=Pictures
VIDEOS=Videos
# Another alternative is:
#MUSIC=Documents/Music
#PICTURES=Documents/Pictures
#VIDEOS=Documents/Videos
```

**Comment by jtojnar** [comment]
> However, two stock files in **/run/current-system/sw/etc/xdg/** always override it

How did you determine that? Are you sure you do not have `~/.config/user-dirs.dirs` set by your desktop environment?

> * load /run/current-system/sw/etc/xdg early - just after /store/xxx-packages; load /etc/xdg always latest

I believe we determined in https://github.com/NixOS/nixpkgs/pull/67389, the first found config wins.

> * strip `xdg-user-dirs-0.18` of user-dirs.defaults if /etc/xdg/user-dirs.defaults is present to prevent overriding

That might require everyone to create `/etc/xdg/user-dirs.defaults` if they do not want all directories end up in their home directory.

**Comment by cx405** [comment]
@jtojnar 
Well, my system is built from scratch and only used  `environment.etc."xdg/user-dirs.defaults".text` to set these dirs up.

I noticed straighaway that Plasma5/Xorg and Firefox completely ignore them and try roll out the classic ones. I have no ~/.config/user-dirs.dirs anywhere.

```
> find / -name *user-dirs.dirs 2>/dev/null

> find / -name *-dirs.dirs 2>/dev/null

> find / -name *user-dirs.defaults 2>/dev/null
/etc/xdg/user-dirs.defaults
/nix/store/qi2l4wmcbn9028ygg67ki25na4fnrl2l-xdg-user-dirs-0.18/etc/xdg/user-dirs.defaults
/nix/store/az0zrqjf97ghq2pr6pl5jrnyjxqlrqjb-system-path/etc/xdg/user-dirs.defaults
/nix/store/k41ai7pzpyz527ph6gbfvmxys6a2658f-etc-user-dirs.defaults
/nix/store/qmb47hssgmnq6gn1nx9vms3xjmrr2n5k-etc/etc/xdg/user-dirs.defaults
/nix/store/d41v4aznn6471flnjj6jwrhsvhkzb2s4-system-path/etc/xdg/user-dirs.defaults
/nix/store/gi0ds0p50sz50fr8vkw69ak4xrc94kpi-etc/etc/xdg/user-dirs.defaults
/nix/store/akps29rpvpic75a4s35rsj1qymbvr0mk-system-path/etc/xdg/user-dirs.defaults
/nix/store/n3221c413n88jvmfzb9y19pgmyb330k5-etc/etc/xdg/user-dirs.defaults
```

I am aware of a different syntax and meaning between user-dirs.defaults and user-dirs.dirs

I know about default precedence of PATH variable, you are correct that the leftmost on the string takes priority over all further and just tested it myself by cping two simple echo scripts into two locations with different outputs..

However, I dont understand then why the system simply ignores all in /etc/xdg/user-dirs.defaults -> /etc/static/xdg/user-dirs.defaults -> /nix/store/k41ai7pzpyz527ph6gbfvmxys6a2658f-etc-user-dirs.defaults

Just verified, the text is stored in Linux new-line format (0A).

Here is [my full env](https://0bin.net/paste/yVTZ4Jww#N1SgMdKg9VND0Gcl6Pwkr6JZyI+tOl3u25FOCT1EMe2).

**Comment by cx405** [comment]
I checked all the /nix/store/*.defaults above.  All with /etc/etc contain my version from configuration.nix.  All system-path - stock file. The xdg-user-dirs-0.18 also contains stock file. Here is how stock file looks:
```
# Default settings for user directories
#
# The values are relative pathnames from the home directory and
# will be translated on a per-path-element basis into the users locale
DESKTOP=Desktop
DOWNLOAD=Downloads
TEMPLATES=Templates
PUBLICSHARE=Public
DOCUMENTS=Documents
MUSIC=Music
PICTURES=Pictures
VIDEOS=Videos
# Another alternative is:
#MUSIC=Documents/Music
#PICTURES=Documents/Pictures
#VIDEOS=Documents/Videos
```

**Comment by cx405** [comment]
@jtojnar sorry to disturb you - I found the reason: xdg-user-dirs-update must be called after first login of the user.  It is not invoked. I don't know who is supposed to call it, but after calling it manually - all directories appeared and I am very sure that user is not supposed to do this manually.

I have updated the bug description.


`/run/current-system/sw/etc/xdg/user-dirs.conf` explicitly mentions this should happen, but doesn't:
# This controls the behaviour of xdg-user-dirs-update which is run on user login
# You can also have per-user config in ~/.config/user-dirs.conf, or specify
# the XDG_CONFIG_HOME and/or XDG_CONFIG_DIRS to override this"

**Comment by jtojnar** [comment]
Oh, that’s right. Your desktop environment is responsible for calling it. You should have `xdg-data-dirs` in `environment.systemPackages`:

https://github.com/NixOS/nixpkgs/blob/f3f4e74d694d928e27962312ade98b220d2af085/nixos/modules/services/x11/desktop-managers/gnome.nix#L463

Which should link autostart file to `/run/current-system/sw/etc/xdg/autostart/`.

Then your DE should run it on startup.

**Comment by cx405** [comment]
Thank you very much for explaining. However this xdg implies this should happen automatically "xdg-user-dirs-update which is run on user login". I assume not everyone wants these directories in his home directory, other want them to be built automatically and customized. This looks like a valid future NixOS option.

**Comment by cx405** [comment]
Thank you very much for the information!

Because I see inconsistency between how NixOS handles xdg-dirs specification, I have opened a Feature Request to allow control over this feature. Unfortunately I am not apt in nix, but maybe this can be of use: #222904

**Comment by jtojnar** [comment]
There is no inconsistency. The desktop environment is responsible for this so when you are creating your own DE from scratch, you need to make sure to set up all XDG specifications correctly.

Ideally, we would have a documentation section that would help with setting up the XDG baseline but so far nobody found the time to do it.

**Comment by cx405** [comment]
Implementing (in any way) the #222904 - will close this issue.

**Comment by cx405** [comment]
Thank you for detailed information. I know about existence of home manager and difference between `user-dirs.defaults` and `user-dirs.dirs`. 
My issue is different: stock or modified settings in `user-dirs.defaults` are ignored on Plasma, this is likely due to Plasma currently preferring to just output a Desktop entry, (undocumented-ly) expecting user to add  `xdg-user-dirs-update` manually to autoexec or through any other form of invocation.

I imagine other desktops might prefer similar behavior (disable xdg, limit xdg to just Desktop folder, full xdg), hence I created #222904.

Of course, the other method is to write the whole issue into NixOS manual so user decides what to add, but this will keep behavior inconsisent across desktops.

Ideally all desktops must add autoexec to `xdg-user-dirs-update` by default, which then acts based upon the policy in #222904 (as far as I see it, you milage may vary).

**Comment by jtojnar** [comment]
> Ideally all desktops must add autoexec to `xdg-user-dirs-update` by default

That should be handled by `xdg-user-dirs` being in `envirohnment.systemPackages` and the desktop environment supporting [XDG autostart spec](https://specifications.freedesktop.org/autostart-spec/autostart-spec-0.5.html) – nothing DE-specific.

Unless the desktop explicitly decides to ignore `xdg-user-dirs.desktop` autostart entry. But it is probably more likely that autostart is broken.

**Comment by cx405** [comment]
@jtojnar I have opened #222925 based on this. Thank you VERY MUCH for your help. I will hence close this request to prevent parallel/spread discussion.
