### ISSUE TITLE
Key repeat rate changed

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixpkgs#22164]
I just pulled in the latest updates for NixOS 16.09, and for some reason my key repeat rate changed. When I hold down a key, characters are repeated much more slowly.

So far I've figured out how to fix it temporarily using `xset`. From some experimentation, `xset r rate 250 50` seems to get it roughly back to what it used to be.

So, two issues/questions here:

1. The fact that the repeat rate spontaneously changed with an update is a bug, right?
2. Is there a NixOS option to explicitly set the repeat rate to make sure I can avoid running into this issue again?

**Comment by cstrahan** [comment]
Dunno why it would spontaneously change, but check out `services.xserver.autoRepeatDelay` and  `services.xserver.autoRepeatInterval`.

**Comment by chris-martin** [comment]
(Note: the `autoRepeatDelay` and `autoRepeatInterval` options were added by f9a3835 and are not in NixOS 16.09.)

**Comment by rasendubi** [comment]
(triage) @chris-martin is repeat rate change still reproducible? With `autoRepeat*` options set?

**Comment by chris-martin** [comment]
Now that I have the autoRepeat options set, I have not encountered this problem. I think we can close this. I might suggest we set defaults for these NixOS options, though, other than `null`, to reduce the future risk that updates change the defaults out from under users.

**Comment by wilfreddenton** [comment]
I find that when using `gnome3` or `xfce` as my desktop manager with `gdm` as the display manager, `autoRepeatDelay` and `autoRepeatInterval` are not respected. Is this intended?

This does not work either.
```
services.xserver.displayManager.sessionCommands = ''
    ${pkgs.xlibs.xset}/bin/xset r rate 200 50
'';
```
