### ISSUE TITLE
phantomjs2 does not build on darwin

### ISSUE THREAD

**Issue by edofic** [NixOS/nixpkgs#22172]
## Issue description

Build fails because it depends on `cups`. But darwin support for `cups` [was removed here](https://github.com/NixOS/nixpkgs/commit/5d6da38d33)

### Steps to reproduce

`nix-shell -p phantomjs2` on a darwin machine.

## Technical details

* System: macOS Sierra
* Nix version: 1.11.5
* Nixpkgs version: 17.03pre98682.f673243

cc @NejcZupec

**Comment by copumpkin** [comment]
Perhaps cups works (or can be made to easily) nowadays? The removal was over 3 years ago, which  was before we put major effort into purifying the darwin stdenv.

**Comment by NejcZupec** [comment]
I tried to revert this commit (https://github.com/NixOS/nixpkgs/commit/5d6da38d33) and I still can't build phantomjs. I got the following error:

```
/nix/store/b2dgmram5q8ywz2gxvwsxizsffxynmhr-bash-4.4-p5/bin/bash: line 1:  3503 Trace/BPT trap: 5       ./genstrings > sample.c
make[1]: *** [Makefile:244: genstrings] Error 133
make: *** [Makefile:40: all] Error 1
builder for '/nix/store/v08zwx9yjim1ypw94jc9iad6rqq8r243-cups-2.1.4.drv' failed with exit code 2
cannot build derivation '/nix/store/np92hn4k2narg05ckrk48ypfn7dzml83-phantomjs-2.1.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/np92hn4k2narg05ckrk48ypfn7dzml83-phantomjs-2.1.1.drv' failed
```

**Comment by domenkozar** [comment]
Did you try just removing cups? it was probably there due to xcode.

**Comment by dmjio** [comment]
I'm still seeing this issue, this time due to `openssl` it seems.

Steps to reproduce: `nix-shell -p phantomjs2`
```
/private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/nix-build-phantomjs-2.1.1.drv-0/phantomjs/src/qt /private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/nix-build-phantomjs-2.1.1.drv-0/phantomjs
/private/var/folders/x4/92d7c1vd7wl88gdw6668rnr80000gp/T/nix-build-phantomjs-2.1.1.drv-0/phantomjs
configuring
no configure script, doing nothing
building

ERROR: Failed to build PhantomJS! Could not find OpenSSL
configuring Qt Base, please wait...
builder for ‘/nix/store/hhhcfakn9knzr8xwzbc5548dwx010cjj-phantomjs-2.1.1.drv’ failed with exit code 1
```

**Comment by JohnAZoidberg** [comment]
Can somebody on darwin please verify whether it works now?
