### ISSUE TITLE
KDE - Window Manager page in Info Center

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#221735]
### Describe the bug
KDE - Window Manager page in Info Center does not find qdbus

### Steps To Reproduce
1. Open Info Center
2. Open Graphics tab
3. Open Window Manager tab

### Expected behavior
Window Manager information displayed

### Screenshots
![image](https://user-images.githubusercontent.com/10415894/226070418-13d39cdb-4619-494b-b1f3-2043290b38ba.png)

### Notify maintainers

@ttuegel @nyanloutre 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.102, NixOS, 22.11 (Raccoon), 22.11.3184.9b8e5abb183`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(aroun): `""`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by SuperSamus** [comment]
It seems it's fixed in NixOS unstable.
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.3-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230316.194c2aa`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
![image](https://user-images.githubusercontent.com/40663462/226108790-007e382d-6a16-4a33-9560-937df65136e5.png)

**Comment by Zahrun** [comment]
Can confirm, thank you, @SuperSamus 
Would you be so kind and tell me if you can reproduce https://github.com/NixOS/nixpkgs/issues/220168?
