### ISSUE TITLE
Package request: codon

### ISSUE THREAD

**Issue by AnzenKodo** [NixOS/nixpkgs#221705]
**Project description**

Codon is a high-performance Python compiler that compiles Python code to native machine code without any runtime overhead. Typical speedups over Python are on the order of 10-100x or more, on a single thread. Codon's performance is typically on par with (and sometimes better than) that of C/C++. Unlike Python, Codon supports native multithreading, which can lead to speedups many times higher still. Codon grew out of the [Seq project](https://github.com/seq-lang/seq).

**Metadata**

* homepage URL: https://docs.exaloop.io/codon
* source URL: https://github.com/exaloop/codon
* license: Business Source License 1.1
* platforms: unix, linux, darwin

**Comment by aopom** [comment]
I didn't compile it properly, but if you want to run the official binaries on NixOS, this does the job:
```nix
{ stdenv, lib
, fetchurl
, autoPatchelfHook
}:

stdenv.mkDerivation rec {
  pname = "codon";
  version = "v0.15.5";

  src = fetchurl {
    url = "https://github.com/exaloop/codon/releases/download/v0.15.5/codon-linux-x86_64.tar.gz";
    sha256 = "sha256-lXtqJ8DMbJh9nTApVMkyQTFAB4VgU8JaIRZYJ3SVkZg=";
  };

  nativeBuildInputs = [
    autoPatchelfHook
  ];

  sourceRoot = ".";

  installPhase = ''
    mv codon-deploy $out
  '';

  meta = with lib; {
    homepage = "https://github.com/exaloop/codon";
    description = "A high-performance, zero-overhead, extensible Python compiler using LLVM";
    platforms = platforms.linux;
  };
}
```
