### ISSUE TITLE
request: add llvmPackages_16

### ISSUE THREAD

**Issue by nektro** [NixOS/nixpkgs#221736]
**Project description**
The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.

**Metadata**

* homepage URL: https://llvm.org/
* source URL: https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.0
* license: Apache License v2.0 with LLVM Exceptions
* platforms: x86_64-darwin, aarch64-darwin, aarch64-linux, i686-linux, x86_64-linux
* notes: previously added as llvmPackages_14, llvmPackages_15, etc

**Comment by primeos** [comment]
There's https://github.com/NixOS/nixpkgs/pull/223282 now :)

We also really need LLVM 16 ASAP as it seems to be required for Chromium 113 (https://github.com/NixOS/nixpkgs/issues/213862#issuecomment-1465043581) that will be released on 2023-05-02.

cc the `llvm` team: @dtzWill @Ericson2314 @lovek323 @primeos @alyssais @RaitoBezarius @rrbutani @sternenseemann

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.1

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.2

**Comment by nektro** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.3
