### ISSUE TITLE
cudaPackages.nccl: only ever builds with default version of `cudaPackages`

### ISSUE THREAD

**Issue by ConnorBaker** [NixOS/nixpkgs#221895]
### Describe the bug

`nccl` is only ever built with the default version of `cudaPackages` because the line which adds the derivation never changes the version of `cudaPackages` provided:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/cuda-packages.nix#L48

I confirmed this by making this change to the `nccl` derivation

```nix
cuda-redist = throw "cudaPackages.cudaVersion is ${cudaPackages.cudaVersion}";
```

and trying to build it with two different versions of `cudaPackages`. Notice that the error is the same:

<details>

```console
[connorbaker@fedora nixpkgs]$ nix build --impure -L .#cudaPackages.nccl
warning: Git tree '/home/connorbaker/Documents/nixpkgs' is dirty
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nccl-2.16.5-1-cuda-11.7'
         whose name attribute is located at /nix/store/bh247jakm9gvjrif38ssqz90zfgqxy05-source/pkgs/stdenv/generic/make-derivation.nix:302:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'nccl-2.16.5-1-cuda-11.7'

         at /nix/store/bh247jakm9gvjrif38ssqz90zfgqxy05-source/pkgs/stdenv/generic/make-derivation.nix:342:7:

          341|       depsBuildBuild              = lib.elemAt (lib.elemAt dependencies 0) 0;
          342|       nativeBuildInputs           = lib.elemAt (lib.elemAt dependencies 0) 1;
             |       ^
          343|       depsBuildTarget             = lib.elemAt (lib.elemAt dependencies 0) 2;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: cudaPackages.cudaVersion is 11.7
[connorbaker@fedora nixpkgs]$ nix build --impure -L .#cudaPackages_11_8.nccl
warning: Git tree '/home/connorbaker/Documents/nixpkgs' is dirty
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nccl-2.16.5-1-cuda-11.7'
         whose name attribute is located at /nix/store/bh247jakm9gvjrif38ssqz90zfgqxy05-source/pkgs/stdenv/generic/make-derivation.nix:302:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'nccl-2.16.5-1-cuda-11.7'

         at /nix/store/bh247jakm9gvjrif38ssqz90zfgqxy05-source/pkgs/stdenv/generic/make-derivation.nix:342:7:

          341|       depsBuildBuild              = lib.elemAt (lib.elemAt dependencies 0) 0;
          342|       nativeBuildInputs           = lib.elemAt (lib.elemAt dependencies 0) 1;
             |       ^
          343|       depsBuildTarget             = lib.elemAt (lib.elemAt dependencies 0) 2;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: cudaPackages.cudaVersion is 11.7
```

</details>

In `python-packages.nix` the pattern seems to be passing `pythonPackages = self`. However, it is relatively rare that the derivation takes `pythonPackages` as an argument. Instead, it seems to be preferred to have the derivation take, as arguments, the actual python packages required.

To bring the NCCL derivation in line with this pattern, it should take the CUDA packages it requires as arguments.

### Notify maintainers

@NixOS/cuda-maintainers

**Comment by SomeoneSerge** [comment]
https://github.com/NixOS/nixpkgs/blob/c60afb9cbe3390e7b57f1dd553774e79864cea4d/pkgs/development/libraries/science/math/nccl/default.nix#L5

We only expose nccl as `cudaPackages.nccl`. Let's change it to take cudaPackages' individual attributes as arguments, so that `overrideScope'` works properly. Nccl already uses solely the redist packages, so I guess we needn't worry about cuda10

**Comment by ConnorBaker** [comment]
> https://github.com/NixOS/nixpkgs/blob/c60afb9cbe3390e7b57f1dd553774e79864cea4d/pkgs/development/libraries/science/math/nccl/default.nix#L5
> 
> We only expose nccl as `cudaPackages.nccl`. Let's change it to take cudaPackages' individual attributes as arguments, so that `overrideScope'` works properly. Nccl already uses solely the redist packages, so I guess we needn't worry about cuda10

Agreed -- WIP at https://github.com/NixOS/nixpkgs/pull/217619. Running a `nixpkgs-review` now :)
