### ISSUE TITLE
Update request: spicetify-cli 2.16.1 → 2.16.2

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#221857]
- Package name: spicetify-cli
- Latest released version: 2.16.2

- Current version on the unstable channel: 2.16.1
- Current version on the stable/release channel: 2.14.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@jonringer

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by markbeep** [comment]
Has already been updated in #221053
