### ISSUE TITLE
Audacity fails: cannot write to `/run/user/1000`

### ISSUE THREAD

**Issue by MikiVanousek** [NixOS/nixpkgs#221992]
### Describe the bug
Audacity fails to import audio

### Steps To Reproduce
1. Install the newest version of audacity from `nixos-unstable` or `nixos-22.11`
2. Try to import audio
3. Get the following error message:

![image](https://user-images.githubusercontent.com/33402194/226168116-0d7e562f-010b-4dc5-8127-3a0a70c65ecf.png)
 

### Notify maintainers

@lheckemann @veprbl @wegank 

### Metadata
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.102, NixOS, 22.11 (Raccoon), 22.11.3196.cd34d6ed7ba`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(miki): `""`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by wegank** [comment]
Not reproducible on my aarch64-linux machine (and `/run/usr/1000` is perfectly writable)...

**Comment by MikiVanousek** [comment]
@wegank Notably, it really is `user` not `usr`. Are you on NixOS? Perhaps I could try deleting the entire `/run/user/1000`?

**Comment by wegank** [comment]
> @wegank Notably, it really is `user` not `usr`. Are you on NixOS? Perhaps I could try deleting the entire `/run/user/1000`?

Sorry, just a typo. Yes, I've tested it on NixOS.

**Comment by MikiVanousek** [comment]
No other program seems to suffer from issues with the folder.

**Comment by lheckemann** [comment]
Is there any relevant output if you run it in a terminal? Can you confirm if the tmpfs is maybe indeed full using `df -h /run/user/1000`?

**Comment by MikiVanousek** [comment]
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.6G  180K  1.6G   1% /run/user/1000
```
I see it is only 1.6G, 10% of the available ram.

**Comment by MikiVanousek** [comment]
I solved it by looking for every audacity directory in my home folder (with `find ./ -name "*audacity*"`), and then deleting all that I thought my keep state:
```
.config/audacity
.audacity-data
.run-user/audacity-miki/
.local/share/audacity
```
