### ISSUE TITLE
Package request: podman-desktop

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#221956]
**Project description**

A graphical tool for developing on containers and Kubernetes

**Metadata**

* homepage URL: https://podman-desktop.io/
* source URL: https://github.com/containers/podman-desktop
* license:  apache 2.0
* platforms: windows, linux, darwin

**Comment by sikmir** [comment]
Packaged in https://github.com/NixOS/nixpkgs/pull/222727
