### ISSUE TITLE
Cannot use localedef

### ISSUE THREAD

**Issue by danbst** [NixOS/nixpkgs#22192]
## Issue description
I tried to create new locale, but `localedef` fails hard.
```
$ localedef -i ru_RU -f CP1251 ru_RU.CP1251 --add-to-archive $PWD/locale-archive
cannot create temporary file: /nix/store/jm1n87rp8vr90j9ahcrfzr57nc2r8vgf-glibc-2.24/lib/locale/locale-archive.wPgnbS: No such file or directory
```

@vrthra has investigated into this issue in https://github.com/NixOS/nixpkgs/issues/15910, but without proper resolution.

## Technical details

* System: NixOS: 16.09.773.b8ede35
* Nixpkgs version: "16.09.773.b8ede35"

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by danbst** [comment]
I don't have a usecase for this. But the issue seems to be known and has workaround: https://github.com/NixOS/nixpkgs/blob/d27643bc0ae06ed52a5d88aa875d79d1da9ffcb1/pkgs/development/libraries/glibc/locales.nix#L20-L54
