### ISSUE TITLE
Package request: edgedriver

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#222021]
**Project description**

Microsoft Edge WebDriver, similar to chromedriver or geckodriver.

**Metadata**

* homepage URL: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
* source URL: N/A
* license: proprietary
* platforms: windows, linux, darwin

**Comment by SigmaSquadron** [comment]
Duplicate of #192050
