### ISSUE TITLE
zramSwap: add writeback device parameter.

### ISSUE THREAD

**Issue by L911P** [NixOS/nixpkgs#222032]
### Describe the bug
One of the features of zram (and of systemd-zram-generator) is that a swap partition (and hopefully someday in the future a swap file too) can be used to store incompressible pages instead of holding them in ram.
It's [here](https://github.com/systemd/zram-generator/blob/main/zram-generator.conf.example#L33)

### Notify maintainers
@NickCao (you're the last person I saw touch the zramSwap module.)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.2-zen2, NixOS, 23.05 (Stoat), 23.05pre461993.0c4800d579a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - channels(l911p): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by NickCao** [comment]
Our current zram module is implemented by retrofitting the old interface for our own set of bash scripts onto zram-generator, thus it's only possible to create multiple zram devices of identical configurations. However it should be illegal to share a single backing device among multiple zram devices, leaving us two choices in implementing this:

1. only allow creating a single zram device when backing device is set
2. rework the module to expose the full features of zram-generator

What's your opinion?

**Comment by L911P** [comment]
:thinking: It's not stated that the module uses zram-generator under the hood, and I'd say that I don't really think a lot of people use multiple zram devices, so perhaps \#1 is fine.
