### ISSUE TITLE
signal-desktop is broken on Wayland

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#222043]
### Describe the bug

NixOS unstable is affected by https://github.com/signalapp/Signal-Desktop/issues/6247 on Wayland.

### Steps To Reproduce
1. Run signal-desktop on Wayland.

### Expected behavior

No crash.

### Notify maintainers

@Mic92 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
- system: `"x86_64-linux"`
 - host os: `Linux 6.2.7, NixOS, 23.05 (Stoat), 23.05pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/prj7h0cg3vwbzds64hwh6bcwf62sakch-nixpkgs-src`
```

**Comment by Mic92** [comment]
I am also getting a crash every once in a while on startup. Starting it again works so far and it seems stable after that. Don't know what to do about that.

**Comment by Corristo** [comment]
The way I've fixed this locally is by using the following overlay:

```
  nixpkgs.overlays = [
    (self: super: {
      signal-desktop = super.signal-desktop.overrideAttrs (old: {
        preFixup = old.preFixup + ''
          gappsWrapperArgs+=(
            --add-flags "--enable-features=UseOzonePlatform"
            --add-flags "--ozone-platform=wayland"
          )
        '';
      });
    })
  ];
```

**Comment by RaitoBezarius** [comment]
Apparently, Signal beta works again on Wayland.

**Comment by PatrickShaw** [comment]
Just adding a data point. Having Wayland disabled actually caused more bugs for me.

Re-enabling Wayland via @Corristo 's overlay helped fix my compositor crashing whenever I clicked on certain UI like "preferences" in the "file" menu.

Currently running:
- [hyprland - rev df98db50924c05f0bd7a8c95cdab5d4ece13a1f1](https://github.com/hyprwm/Hyprland/tree/df98db50924c05f0bd7a8c95cdab5d4ece13a1f1) with `nvidiaPatches` set to `true`

and have the following env variables set:

```
WLR_NO_HARDWARE_CURSORS=1
WLR_RENDERER=vulkan
GBM_BACKEND=nvidia
LIBVA_DRIVER_NAME=nvidia
__GLX_VENDOR_LIBRARY_NAME=nvidia
```
