### ISSUE TITLE
solana: merge `solana-validator` and `solana-testnet-cli` into one package

### ISSUE THREAD

**Issue by 0xnetfox** [NixOS/nixpkgs#222144]
## Issue description

At the moment there are 2 different packages that build the same solana CLI binary, `solana-testnet-cli` and `solana-validator`. The only difference between the two is that `solana-validator` is capable of building the whole solana tool suite by default, while `solana-testnet-cli` only builds the main binary. Both are slightly outdated.

`solana-testnet-cli` is maintained by @happysalada while `solana-validator` is maintained by @0xperp . I would like to merge these two packages into one and re-brand it as `solana-cli`, which is the most generic name for the whole tool-suite.

I can do the changes myself, but wanted to make sure first that both of the initial maintainers are ok with it and I'm not breaking anything ! :D My plan is to take `solana-validator` as base, since it builds the whole tool suite, then apply the changes from `solana-testnet-cli` to make it darwin compatible, and update the version to the latest mainnet one.

So yeah, let me know if this is the best course of action in your opinion and if I can go ahead with it :)

**Comment by happysalada** [comment]
all good on my end, happy to remove the solana-testnet-cli anytime. I just added this initially to have something to play with
