### ISSUE TITLE
allow multiple SOCKS service instances

### ISSUE THREAD

**Issue by tg-x** [NixOS/nixpkgs#22216]
Currently it is only possible to configure a single dante and nylon instance:

- https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/dante.nix
- https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/nylon.nix

It would useful to allow multiple instances, just like in case of e.g. openvpn:

- `services.dante.<name>...`
- `services.nylon.<name>...`

**Comment by edwtjo** [comment]
I agree about this one. Right now you need to use containers and iptables to provide multiple uplink, or any service, instances. There was some discussion previously about this initiated by @MarcWeber(can't remember the PR..) but I got the feeling that many members were against having named multiple service instances like this. Perhaps @nbp or @edolstra can chime in?

**Comment by edwtjo** [comment]
closing with b08524bf01723a23f17d24487b6b528c603127fb

**Comment by nbp** [comment]
@edwtjo, this change is not backward compatible, please either revert it, or write a changelog entry explaining it and how people should transition from one to the other.

**Comment by edwtjo** [comment]
Right, I intend to add it to the release notes.

**Comment by globin** [comment]
@edwtjo ping

**Comment by Shados** [comment]
While I feel the command-line tooling for NixOS containers could be improved, I do quite like using them for providing multiple instances of a network service. Do you have any specific reasons to prefer having the service support multiple instances directly in this case?

**Comment by edwtjo** [comment]
In release notes 3c9d73f100f310a5b44497b66f391422a258d41e
