### ISSUE TITLE
Cannot set up Thunderbird with Gmail on one NixOS machine (but can on another one)

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nixpkgs#22229]
## Issue description

A have a dual-boot NixOS and Ubuntu laptop.  I have been mostly using Ubuntu, but i am trying now to configure NixOS to a usable condition.  My main account is shared between Ubuntu and NixOS.  I have many applications, like Thunderbird and Evolution, installed on both, sharing their data and configuration, but i have not yet used them all under NixOS.  This time i tried to use Thunderbird under NixOS, and it complained that it could not connect to Gmail server.  It also didn't download messages from my work email account, without showing any errors however.  I could read the messages which were already downloaded from under Ubuntu. There were other anomalies: i tried to remove my Gmail account, but couldn't, the removal operation silently failed.

**To try to debug this, i created a fresh user account** (under NixOS), installed Thunderbird, and tried to set up my Gmail account. I could not: at the authentication step a window popped up which had nothing inside, except the title, mentioning my Gmail credentials, and a long web address at the top. I could not do anything with this window other than close it, in which case the authentication (OAuth2) failed.

### Steps to reproduce

Try to set up an existing Gmail account in Thunderbird, using its default automatic configuration for Gmail. The authentication step pops up a window with blank interior, which can only be closed, causing the (OAuth2) authentication to fail.

## Technical details

* NixOS: `16.09.1555.3bdec6c`
* Nix version: `1.11.6`
* Nixpkgs version: `16.09.1555.3bdec6c`

**Comment by alexeymuranov** [comment]
I just tried the same on a different machine with NixOS after upgrading everything to the latest version (Thunderbird 45.7.0 instead of 45.6.0 as before), and i could set up my Gmail account: the authentication window that before was blank now opened a web page where i had to log into my Gmail account and authorize Thunderbird to manage my mail.  Strange.  I will try to experiment further.

**Comment by vcunat** [comment]
I suspect it might be some impurity that surfaces on non-nixos systems.  I would perhaps try `strace` and look if it loads some code outside of nix store.

**Comment by alexeymuranov** [comment]
I have just upgraded the first machine to the latest version of NixOS (with Thunderbird 45.7.0) and tried again with the fresh account. The window that pops up and is supposed to show a Gmail web page where i have to log into my account still pops up blank.

**Comment by alexeymuranov** [comment]
![screenshot from 2017-01-28 22-28-29](https://cloud.githubusercontent.com/assets/712698/22400054/57555552-e5ab-11e6-9bad-ef19ed304e1f.png)
![screenshot from 2017-01-28 22-28-56](https://cloud.githubusercontent.com/assets/712698/22400055/5eb25c78-e5ab-11e6-90d2-2345327b666b.png)
![screenshot from 2017-01-28 22-29-14](https://cloud.githubusercontent.com/assets/712698/22400056/6199d542-e5ab-11e6-8233-e387d5cffa27.png)

**Comment by alexeymuranov** [comment]
I tried `strace` and got a 25MB text file. What should i look for in it?

**Comment by vcunat** [comment]
@alexeymuranov: well, first... do you actually have binaries from Ubuntu mounted on some standard paths in NixOS? I mean mainly`/usr/**`. If so, it might generally help to avoid that.

In any case, you can check the opened files by filtering the strace output, e.g. `cat thunderbird.log | grep '^open' | grep -v '/nix/store\|/run/opengl\|ENOENT' | sort -u | less` or search for `/usr/` paths in there directly.

**Comment by alexeymuranov** [comment]
My NixOS and Ubuntu live on separate partitions, which are normally not even mounted simultaneously.  User directories are also on a separate `/home` partitions.  I really doubt there could be interaction for a fresh NixOS user account.

I tried to run `cat thunderbird.log | grep '/usr/'` after using `strace` with the *shared* account, here is the output:
```
stat("/usr/tmp", 0x7fff0fd54cb0)        = -1 ENOENT (No such file or directory)
access("/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}", F_OK) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/locale.alias", O_RDONLY) = -1 ENOENT (No such file or directory)
access("/usr/lib/mozilla/plugins", F_OK) = -1 ENOENT (No such file or directory)
```

I will try to do it later for the fresh NixOS user account too.

**Comment by alexeymuranov** [comment]
I am sorry for this confusing report, i do not understand what is going on.

I just tried again setting up Gmail in Thunderbird in a fresh NixOS account, and it worked. The pop up window which was blank yesterday now had a Gmail login prompt.  I did it all with `strace`, here is the output of `cat thunderbird.log | grep '/usr/'`:
```
stat("/usr/tmp", 0x7ffeae5882b0)        = -1 ENOENT (No such file or directory)
access("/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}", F_OK) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/locale.alias", O_RDONLY) = -1 ENOENT (No such file or directory)
access("/usr/lib/mozilla/plugins", F_OK) = -1 ENOENT (No such file or directory)
```

I would still appreciate any indication about how to debug Thunderbird malfunction in the shared NixOS/Ubuntu user account.

**Comment by alexeymuranov** [comment]
I am closing this for now. I disabled GNOME Keyring integration plugin in Thunderbird in the shared account, and it started working, at least the Gmail account.

Sorry about the confusion.
