### ISSUE TITLE
Update request: syslogng 3.38.1 → 4.1.1

### ISSUE THREAD

**Issue by vifino** [NixOS/nixpkgs#222265]
I tried to update it, but it seems like it wants to build a virtualenv and fetch dependencies.
Not sure how to to properly fix it. Maybe just customizing the python and adding the deps will be enough.

- Package name: syslogng
- Latest released version: 4.1.1

- Current version on the unstable channel: 3.38.1
- Current version on the stable/release channel: 3.38.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@ryantm @tobim 
-----

Note for maintainers: Please tag this issue in your PR.

**Comment by pbsds** [comment]
fixed by #222265
