### ISSUE TITLE
package: slmenu - upstream link is outdated or dead

### ISSUE THREAD

**Issue by sogreatandpowerfull** [NixOS/nixpkgs#222350]
Ref: [slmenu/default.nix#L8](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/misc/slmenu/default.nix#L8).

slmenu no longer exists in: https://bitbucket.org/rafaelgg/slmenu/

### Notify maintainers
@7c6f434c

**Comment by 7c6f434c** [comment]
So it looks like BitBucket dropped all the Mercurial repos. We do have a snapshot in cache, so we could re-upload it, I guess? Or do you think that fzf strictly supersedes slmenu?

**Comment by sogreatandpowerfull** [comment]
Perhaps it would be wise to remove it from the repository at this point. The software is outdated, hasn't received updates in several years, and there are many superior alternatives currently available.

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/225019
