### ISSUE TITLE
current version breaks flexget dependencies

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#22246]
## Issue description

with the newest profile flexget fails to start because of dependency problems it seems.

### Steps to reproduce

switch to newest stable profile
optionaly reboot

## Technical details

* System: 16.09.1589.4281374 (Flounder)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "16.09.1589.4281374"

> ● flexget-runner.service - FlexGet Runner
>    Loaded: loaded (/nix/store/wc76kz7k6aabmfx84br73ihcahyq5nm2-unit-flexget-runner.service/flexget-runner.service; bad; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Sun 2017-01-29 01:53:00 CET; 2s ago
>   Process: 17868 ExecStart=/nix/store/62mr428qrsbqc4kqs7scgibhxw8hda83-python2.7-FlexGet-1.2.337/bin/flexget -c /home/black/flexget.yml execute (code=exited, status=1/FAILURE)
>  Main PID: 17868 (code=exited, status=1/FAILURE)
> 
> Jan 29 01:53:00 mars flexget[17868]:   File "/nix/store/sbivss9cl06j327hh82f3avhibwi8jv0-python2.7-beautifulsoup4-4.1.3/lib/python2.7/site-packages/bs4/__init__.py", line 29, in <module>
> Jan 29 01:53:00 mars flexget[17868]:     from .builder import builder_registry
> Jan 29 01:53:00 mars flexget[17868]:   File "/nix/store/sbivss9cl06j327hh82f3avhibwi8jv0-python2.7-beautifulsoup4-4.1.3/lib/python2.7/site-packages/bs4/builder/__init__.py", line 306, in <module>
> Jan 29 01:53:00 mars flexget[17868]:     from . import _html5lib
> Jan 29 01:53:00 mars flexget[17868]:   File "/nix/store/sbivss9cl06j327hh82f3avhibwi8jv0-python2.7-beautifulsoup4-4.1.3/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 57, in <module>
> Jan 29 01:53:00 mars flexget[17868]:     class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
> Jan 29 01:53:00 mars flexget[17868]: AttributeError: 'module' object has no attribute '_base'
> Jan 29 01:53:00 mars systemd[1]: flexget-runner.service: Main process exited, code=exited, status=1/FAILURE
> Jan 29 01:53:00 mars systemd[1]: flexget-runner.service: Unit entered failed state.
> Jan 29 01:53:00 mars systemd[1]: flexget-runner.service: Failed with result 'exit-code'.
> warning: error(s) occurred while switching to the new configuration

**Comment by FRidh** [comment]
possibly related https://github.com/NixOS/nixpkgs/pull/21543

**Comment by FRidh** [comment]
is this fixed?

**Comment by spiderbit** [comment]
the related bug is not fixed, so I dont think so. that update needs to land in stable.

**Comment by FRidh** [comment]
https://github.com/NixOS/nixpkgs/commit/bcf97ef12398ecf821f3eff5100dc8d695e15aed is in stable

**Comment by spiderbit** [comment]
yes this bug is fixed, should have reported that back earlier :) working fine now.
