### ISSUE TITLE
Proposal: Non-TFC Terraform Providers in NixOS

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#222462]
Dear NixOS developers,

I recently made a pull request (#222376) to add terraform-providers-scalr that I believe can be used to change how Terraform providers not hosted in Terraform Cloud are implemented in NixOS. The PR added some logic to handle both GitHub repositories and TFC conditionally.  However, @zowoq was unhappy with the change and closed the PR, stating that my solution won't be accepted. I understand that my PR introduces a special case, but I believe that the maintenance burden would be acceptable, and I am more than happy to help out with scripting and package maintenance. Perhaps even having GitHub providers separate from TFC providers and maintained by myself if we're not comfortable with modifying this script.

I'd like to continue this discussion and see if we could come to a better solution for GitHub-hosted providers, such as Scalr which is not and will not be in TFC due to being a direct competitor to them. In order to run the script and generate packages, there are only a few things that we need to get from TFC. In order to calculate the hash, we need to retrieve the source from GitHub (or GitLab in some special cases), and in order to provide correct metadata we need the homepage. For the first two, the org and repo are retrieved from TFC in the existing script.

Please keep in mind that what I had at the time I closed it was not at all a final solution, and I would love to continue refining this solution. Assuming the Nix developers/maintainers are open to it, one idea that I had was to have two JSON files, one for TFC providers and one for GitHub providers, called `tfc-providers.json` and `github-providers.json`, respectively. The script can then be written in a way to handle both files, so metadata for providers doesn't have to be in the script itself. However, I didn't think of this before the PR was closed and the discussion on it ended, so I will describe what I did actually implement with the assumption that the JSON file for GitHub providers could replace the array in the script. Anyways...

What I did to address the GitHub repositories was to create an array/mapping in the `update-provider` script for all GitHub-hosted providers:
 
 ```
# Providers that are not hosted on terraform.io and have their source code in GitHub, using GitHub releases.
# This allows us to override values and use GitHub's release API to retrieve the values we need instead of TFC.
declare -A github_providers=(
    ["scalr","org"]="scalr"
    ["scalr","repo"]="terraform-provider-scalr"
    ["scalr","homepage"]="https://registry.scalr.io/scalr/scalr"
)

function is_github_provider {
    local provider=$1
    local provider_key="$provider,org"
    if [[ -n github_providers[$provider_key] ]]; then
        return 0
    else
        return 1
    fi
}
```

There are a few conditionals that I added, as well, where data is grabbed for TFC packages. In one such case, it was org and repo, which thanks to the metadata mappings, we already had, so I just wrote a block to use the existing values:

```
if is_github_provider "$provider"; then
  provider_source_url="https://github.com/$org/$repo}"
else
  provider_source_url="$(jq -r '.source' <<<"${registry_response}")"
  org="$(echo "${provider_source_url}" | cut -d '/' -f 4)"
  repo="$(echo "${provider_source_url}" | cut -d '/' -f 5)"
fi
```

However, not all cases are this straightforward. Particularly the provider revision. Assuming the repo is tagged with valid semantic versioning that matches up with what Terraform expects, we can trivially grab the revision from GitHub's release API.

```
if is_github_provider "$provider"; then
  org_key="${provider},org"
  org=${github_providers[$org_key]}
  repo_key="${provider},repo"
  repo=${github_providers[$repo_key]}
  rev=$(curl "https://api.github.com/repos/$org/$repo/releases/latest" | jq -r '.tag_name')
else
  registry_response=$(curl -s "${homepage//providers/v1/providers}")
  rev="$(jq -r '.tag' <<<"${registry_response}")"
fi
```

The only other 'special case' is the homepage, and this isn't even technically needed to have the script get the latest versions and hashes, it's just nice to have for accurate metadata. This simply grabs the value from the provider data and uses it rather than computing it:

```
  provider=$(basename "${provider}")
  if is_github_provider "$provider"; then
    homepage_key="${provider},homepage"
    homepage=${github_providers[$homepage_key]}
  else
    homepage="https://registry.terraform.io/providers/${provider}"
  fi
```

I believe that we can generalize this to handle many GitHub Terraform provider repositories, including the 'teleport' provider which was previously removed for not being updateable with the script. I haven't tried proving this out yet, but they do have a v12.1.1 tag and in theory, with a path of /teleport appended to the GitHub repo URL, it should work fine. I'm open to discussing other ideas or suggestions on this matter and would love to further explore how we can improve the implementation of Terraform providers.

Thank you for considering my proposal.

Dylan

**Comment by zowoq** [comment]
cc @zimbatm

**Comment by zowoq** [comment]
> Dear NixOS developers

Basically it's just zimbatm and myself that are the maintainers of the terraform providers.
___

I'm closing this as the discussion on the PR has mostly superseded what is proposed here and it's easier to keep the discussion in one place. Can always reopen it or make another if needed when the discussion on the PR is concluded.
