### ISSUE TITLE
python3Packages.torch-bin: misleading license

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#222468]
- Package name: python3Packages.torch-bin

https://github.com/NixOS/nixpkgs/blob/5d698290bd8c05f965b0a6600de17ccb6a5156af/pkgs/development/python-modules/torch/bin.nix#L74-L77

It would seem that the license per comment should be `licenses.unfreeRedistributable`.
Switching to that would prevent `allowUnfree = false` users from accidentally fetching the compromised artifacts.
I'm also not sure we want these in hydra cache

CC maintainer @junjihashimoto

**Comment by SomeoneSerge** [comment]
I expect users may experience breakages after the switch though

**Comment by fabaff** [comment]
The Intel Open Source License is a modified version of BSD clause 3 and [OSI approved](https://spdx.org/licenses/Intel.html). The CUDA EULA has [distribution requirements](https://docs.nvidia.com/cuda/eula/index.html#distribution-requirements). I'm not sure how those requirements apply in combination with `torch` but distribution requirements make something unfree quickly in the FSF definition.

**Comment by junjihashimoto** [comment]
Thank you for checking the current status. Is the free/unfree based on the FSF definition?

**Comment by SomeoneSerge** [comment]
Thanks @fabaff!
Pytorch wheels are [built with MKL BLAS](https://github.com/pytorch/pytorch/actions/runs/4337823562/jobs/7574087583#step:14:305), which they [download](https://github.com/pytorch/builder/blob/a007fbcc97b6f02a777104d6e0e94c80f3d2d41e/common/install_mkl.sh#L10) from the "intel" channel in anaconda: the license they specify there is [Intel Simplified Software License](https://www.intel.com/content/dam/develop/external/us/en/documents/pdf/intel-simplified-software-license.pdf), which in nixpkgs goes as unfree:

```bash
❯ nix eval nixpkgs#lib.licenses.issl.free
false
```

Not only unfree, MKL is not open source: it's just headers and pre-built static archives.
The same goes for CUDA: NVIDIA only ships pre-built binaries, together with some glue code.

**Comment by SomeoneSerge** [comment]
This would be addressed by https://github.com/NixOS/nixpkgs/pull/221652/commits/b73d050aa7ec8861cac4edc3d24a514daaf2ebea

**Comment by SomeoneSerge** [comment]
Since https://github.com/NixOS/nixpkgs/pull/227420:

```console
❯ nix eval github:nixos/nixpkgs/master#python3Packages.torch-bin.meta.license --json | jq
[
  {
    "deprecated": false,
    "free": true,
    "fullName": "BSD 3-clause \"New\" or \"Revised\" License",
    "redistributable": true,
    "shortName": "bsd3",
    "spdxId": "BSD-3-Clause",
    "url": "https://spdx.org/licenses/BSD-3-Clause.html"
  },
  {
    "deprecated": false,
    "free": false,
    "fullName": "Intel Simplified Software License",
    "redistributable": false,
    "shortName": "issl",
    "url": "https://software.intel.com/en-us/license/intel-simplified-software-license"
  },
  {
    "deprecated": false,
    "free": false,
    "fullName": "Unfree redistributable",
    "redistributable": true,
    "shortName": "unfreeRedistributable"
  }
]
```
