### ISSUE TITLE
packageOverrides in ~/.nixpkgs/config.nix overwrites /etc/nixos/configuration.nix

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#22259]
## Issue description
If I as a user, set a packageOverrides in my ~/.nixpkgs/config.nix, it will fully overwrite the packageOverrides in /etc/nixos/configuration.nix.

So say I overrode package go in /etc/nixos/configuration.nix. Then I overrode package neovim as a user in ~/.nixpkgs/config.nix. Now if I do `nix-env -i go` as the user, I will not get my overridden package from /etc/nixos/configuration.nix, I will get the regular package.

Is there any way to make it so the packageOverrides in ~/.nixpkgs/config.nix merges with the packageOverrides in /etc/nixos/configuration.nix?

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.03pre99759.f66d782 (Gorilla)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.03pre99759.f66d782"

**Comment by vcunat** [comment]
`nix-env` by itself knows nothing about `/etc/nixos/configuration.nix`, which seems OK to me &ndash; that way it works more similarly on NixOS and elsewhere. The value for the currently running system isn't normally stored anywhere.

I just share the stuff "manually", i.e. I have `/etc/nixos/nixpkgs-config.nix` that is used by `configuration.nix` and I symlink that from `~/.nixpkgs/config.nix`. (For systems used by multiple humans you could import and modify it instead.)  I'm not very fond of "merges magically", because I don't think there's any simple merging function that would satisfy most people.

**Comment by nhooyr** [comment]
Why symlink? If it is used by configuration.nix, shouldn't apply globally? Did you mean you are importing it in `~/.nixpkgs/config.nix`?

As for merging, what is wrong with handling collisions like: any packages defined in `~/.nixpkgs/config.nix` take precedence over the ones `configuration.nix`? What would not be satisfactory about that?

**Comment by vcunat** [comment]
I have a symlink: `ln -s /etc/nixos/nixpkgs-config.nix ~/.nixpkgs/config.nix`, but importing would do basically the same thing.

**Comment by nhooyr** [comment]
But why even symlink or import? If it's used by `configuration.nix`, it's applied globally already.

**Comment by vcunat** [comment]
> `nix-env` by itself knows nothing about `/etc/nixos/configuration.nix`

**Comment by nhooyr** [comment]
argh, I read that but misinterpreted. I understand why it's not working now, thanks! But what about the merging the way I described in my previous comment? Why would someone object or even expect anything different?

**Comment by vcunat** [comment]
I know of no universal way of "merging" two attrsets that would satisfy everyone.  I personally think it would perhaps be better to keep this explicit or configurable, as nixpkgs configuration commonly contains even functions...

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
