### ISSUE TITLE
_module in json for options

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#22258]
## Issue description
I generated a json file from a nix expression for some options for a service (my program accepts a JSON configuration file). https://gist.github.com/nhooyr/dee280772f1e12e05d1ec8f6fe0e360f. JSON, then the nix expression and then the module. what's with all the _module stuff for array sets?

### Steps to reproduce
1. create a module with an option that is an array of sets
2. take the nix expression for the options for that module and turn it into JSON

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.03pre99759.f66d782 (Gorilla)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.03pre99759.f66d782"

**Comment by copumpkin** [comment]
An artifact of the NixOS module system. I don't know how fundamental it is, but @nbp can probably speak more authoritatively about it. Either way, I'd probably just avoid things like this by picking only the keys you expect in your config. Or perhaps it's possible to do more centrally, but I don't know if other things use it.

**Comment by nbp** [comment]
the `_module` is an internal artifact of the module system evaluation.  In this case the options definitions are submodules, and all submodules got these extra `_module.args` and `_module.check` options added [1].  The name argument is provided by the `listOf` option type [2], which names the option based on their position in the list.

These options are part of the module system and are made to be used by the module / submodule system.  I would recommend against doing a `toJSON` for converting the configuration, as this would prevent the addition of options made to abstract common configuration in the future, if needed. (thus not modular)

Instead I would suggest that you create an option named `jsonConfig` with the `attrs` type, which aggregates what you want to generate, and filter out these `_module` options from the submodules.

[1] https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L39-L57
[2] https://github.com/NixOS/nixpkgs/blob/master/lib/types.nix#L184

**Comment by nhooyr** [comment]
Cool thanks!
