### ISSUE TITLE
`nix-env -i package` as root vs appending to environment.systemPackages

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#22250]
Since both install a package visible to every user on the system, what is the difference between them?

**Comment by nhooyr** [comment]
Other than being declarative of course.

**Comment by RonnyPfannschmidt** [comment]
nixos-rebuild will update them if they are in `environment.systemPackages`

so basically `nix-env` usage is imperative and opts you out of the full system update

**Comment by nhooyr** [comment]
Ah, updating.

**Comment by Mic92** [comment]
`environment.systemPackages` is a little different to `nix-env`. It maintains a number of symlinks in  
`/run/current-system/sw/`, while `nix-env` installs them to ~/.nix-profile.
