### ISSUE TITLE
man prints terminal escapes instead of overstrikes

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nixpkgs#22252]
## Issue description
In other operating systems, `man(1)` prints manpages with keywords and whatnot highlighted or bolded using overstrikes.

See http://www.iitk.ac.in/LDP/HOWTO/Text-Terminal-HOWTO-17.html#ss17.12

In nixOS, keywords are highlighted or bolded using the actual terminal escape codes like `^[[1m` for beginning bold mode.

This is a problem because some programs want the raw text of a manpage and expect `col -b`, which removes backspaces, to sanitize man output. However, since man on nixOS is printing terminal escapes, `col -b` does not properly sanitize man output.

### Steps to reproduce
1. `man printf > /tmp/somefile`
2. Open somefile in an editor and look at the escape codes
3. Repeat steps 1-2 on macOS

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...) 17.03pre99759.f66d782 (Gorilla)
* Nix version: (run `nix-env --version`) nix-env (Nix) 1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`) "17.03pre99759.f66d782"

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
