### ISSUE TITLE
small \No fix for babel-russian

### ISSUE THREAD

**Issue by frigatefreedom** [NixOS/nixpkgs#22254]
## Issue description
We have one regression in babel-russian:

ftp://sunsite.icm.edu.pl/pub/CTAN/macros/latex/contrib/babel-contrib/russian/russianb.pdf
> The macro \No is removed since the Cyrillic number sign is available
> on keyboard and can also be typed using the \textnumero macro.

Thats why some old documents created with use of eskdx packgages can not compile.

#Patch

There is patch for russianb.dtx located at babel-russian.source/source/generic/ called No-patch, but I dont know, how to add it to texlive.combine. 
[No-patch.tar.gz](https://github.com/NixOS/nixpkgs/files/737403/No-patch.tar.gz)
Patch adds string "\DeclareRobustCommand{\No}{\ifmmode{\nfss@text{\textnumero}}\else\textnumero\fi} ".
@vcunat

Source file: http://lipa.ms.mff.cuni.cz/~cunav5am/nix/texlive-2016/babel-russian.source.tar.xz

## Technical details

* System: NixOS: 17.03pre99626.f1ba2c8 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6

**Comment by vcunat** [comment]
Was this somehow accepted/discussed upstream?

**Comment by frigatefreedom** [comment]
No, because I dont't have any idea, how to modify texlive, it looks more complicated than other packages.

**Comment by vcunat** [comment]
Please, simply write to the maintainer of the package, so that the improvements are shared by everyone (in time). His address is near the top of [the readme file](https://www.ctan.org/tex-archive/macros/latex/contrib/babel-contrib/russian).

**Comment by frigatefreedom** [comment]
As I understood, maintainer do not want to fix sources.

**Comment by vcunat** [comment]
Hmm, well, at least there's that one-line workaround.
