### ISSUE TITLE
nscd failing to start with defaults in NixOS 16.09

### ISSUE THREAD

**Issue by nixy** [NixOS/nixpkgs#22267]
## Issue description

It looks like the default configuration for nscd is broken, causing the service to timeout at launch. I am not familiar with nscd's configuration and I don't really need it, but disabling the service to workaround this doesn't seem great.

Anyone familiar with nscd's configuration that might have some insights into why it is failing?

### Steps to reproduce

Deploy NixOS 16.09
Run nscd as a command

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

nix-env (Nix) 1.11.6

"16.09.1589.4281374"

**Comment by flokli** [comment]
I don't think this still applies - nowadays, nscd is enabled pretty much per default on nixos, and the nscd service is running properly.
