### ISSUE TITLE
haskellPackages.poppler fails to build

### ISSUE THREAD

**Issue by dbeecham** [NixOS/nixpkgs#22265]
## Issue description

    Preprocessing library poppler-0.14.1...
    In file included from /nix/store/49hz360b2i923wg8dcccwlbqc8yv4yii-glibc-2.24-dev/include/stdio.h:938:0,
                 from ./template-hsc-gtk2hs.h:4,
                 from Structs.hsc:26:
    /nix/store/49hz360b2i923wg8dcccwlbqc8yv4yii-glibc-2.24-dev/include/bits/stdio2.h: In function ‘sprintf’:
    /nix/store/49hz360b2i923wg8dcccwlbqc8yv4yii-glibc-2.24-dev/include/bits/stdio2.h:33:10: error: invalid use of ‘__builtin_va_arg_pack ()’
       return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,

etc.

[gist of full output](https://gist.github.com/dbeecham/b5d610c910b7c1cb5e892efc7f36354f)

### Steps to reproduce

`nix-build -E "(import <nixpkgs> {}).haskellPackages.poppler"`

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03pre99626.f1ba2c8 (Gorilla)
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre99759.f66d782"

**Comment by pSub** [comment]
This seems to be related to #19095

**Comment by matthewbauer** [comment]
This is no longer the case on nixpkgs-unstable.

**Comment by wavewave** [comment]
Really? I checked it today with the following command and had the same error.
```
$ nix-build -E "(import <nixpkgs> {}).haskellPackages.poppler" -I nixpkgs=http://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz

...
Preprocessing library for poppler-0.14.1..
In file included from /nix/store/fn2x7v3bs305xl55ynj698mjc0yfn1lh-glibc-2.26-131-dev/include/stdio.h:862:0,
                 from ./template-hsc-gtk2hs.h:4,
                 from Structs.hsc:26:
/nix/store/fn2x7v3bs305xl55ynj698mjc0yfn1lh-glibc-2.26-131-dev/include/bits/stdio2.h: In function ‘sprintf’:
/nix/store/fn2x7v3bs305xl55ynj698mjc0yfn1lh-glibc-2.26-131-dev/include/bits/stdio2.h:33:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/fn2x7v3bs305xl55ynj698mjc0yfn1lh-glibc-2.26-131-dev/include/bits/stdio2.h: In function ‘snprintf’:
/nix/store/fn2x7v3bs305xl55ynj698mjc0yfn1lh-glibc-2.26-131-dev/include/bits/stdio2.h:64:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...
```
