### ISSUE TITLE
Wrong data type for users.users.<name>.pamMount?

### ISSUE THREAD

**Issue by phpcitizen** [NixOS/nixpkgs#222611]
### Describe the bug (Not a bug but a missing feature?)
I was able to mount a luks2 partition via users.users.name.pamMount

      users.users.lorem.pamMount =
          {
            user = "lorem";
            fstype = "crypt";
            cipher = "aes-xts-plain64";
            options = "no_read_workqueue,no_write_workqueue,allow_discard,fstype=ext4";
            path = "/dev/disk/by-uuid/<uuid>";
            mountpoint = "/mnt/<mountname>";
       };

but how will I be able to mount a second one with this?
Shouldn’t this be a list of set of attributes instead of single set of attributes?

What am I missing?

### Notify maintainers

@dnr @edolstra @rnhmjoj @pennae @volth @rickynils

**Comment by dnr** [comment]
The intention of that option was just a generalized version of `cryptHomeLuks` to mount the user's home directory. You shouldn't really be specifying `user` or `mountpoint` there, they're implicit. If you want more arbitrary entries, just add them to `security.pam.mount.extraVolumes`.

**Comment by phpcitizen** [comment]
I understand now, thank you. Maybe it needs more explanation, examples. security.pam.mount.extraVolumes, too.

And security.pam.mount.extraVolumes can be list of set of attributes, so would be more nixified? Just a suggestion, I might be wrong.
