### ISSUE TITLE
Problem with Export. Time <1s, empty file #Gyroflow

### ISSUE THREAD

**Issue by DonebyDrone** [NixOS/nixpkgs#222786]
After some updates my Gyroflow doesn't export files.

### Steps To Reproduce
1. Open file to stablize - OK
2. Playback stabilized video - OK
3. Export stabilized video - program send information that stabilized vide is ready after less than 1s. But file is empty

### Expected behavior
Program should export stabilized video - it worded before update

### Screenshots
![Zrzut ekranu 2023-03-23 o 21 00 30](https://user-images.githubusercontent.com/128746261/227339214-bf473719-e8d7-48e7-b1ec-c71fe6f91656.png)
![Zrzut ekranu 2023-03-23 o 21 00 53](https://user-images.githubusercontent.com/128746261/227339236-d2fc5f17-583f-4506-bf79-9dbf6d665add.png)

### Additional context
Mac mini (M1, 2020)
macOS Monterey

### Notify maintainers

![Zrzut ekranu 2023-03-23 o 21 00 30](https://user-images.githubusercontent.com/128746261/227339616-3622e9fc-9d85-4e6d-9dd8-f8b13ba12e92.png)
![Zrzut ekranu 2023-03-23 o 21 00 53](https://user-images.githubusercontent.com/128746261/227339623-a6158b76-5282-4a98-a7dc-6b86b275a1d9.png)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by orivej-nixos** [comment]
Nixpkgs do not currently provide Gyroflow, so this issue must be unrelated to Nixpkgs. Gyroflow bug tracker is at https://github.com/gyroflow/gyroflow
