### ISSUE TITLE
`buildFHSEnvChroot` problem: can't create `usr/share/doc`

### ISSUE THREAD

**Issue by yajo** [NixOS/nixpkgs#222754]
### Describe the bug
When building a chrooted FHS for a package, I can't create `usr/share/doc`.

### Steps To Reproduce
Use this flake:

```nix
{
  outputs = {nixpkgs, ...} @ inputs:
    with inputs; let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      packages.${system}.default = pkgs.buildFHSUserEnv {
        name = "test";
        extraBuildCommands = ''
          mkdir -p usr/share/doc
        '';
      };
    };
}
```

Run `nix build -L`

### Expected behavior
I should be able to create that directory.

### Additional context
I'm unpacking a `.deb` file that contains that folder. Unpacking fails due to this problem.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.7-200.fc37.x86_64, Fedora Linux, 37.20230322.0 (Silverblue), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.12.0`
 - channels(yajo): `"nixpkgs"`
 - nixpkgs: `/var/home/yajo/.nix-defexpr/channels/nixpkgs`

**Comment by Atemu** [comment]
This has (sort of) been fixed by making buildFHSEnv use bubblewrap rather than chroot by default.

buildFHSEnvChroot still has this issue but it's deprecated, so it's unlikely to get fixed.

**Comment by Atemu** [comment]
(Great report btw., this was super easy to repro. Thanks!)
