### ISSUE TITLE
`python3Packages.numpyro` build is broken as of `73516442`

### ISSUE THREAD

**Issue by samuela** [NixOS/nixpkgs#222757]
## Issue description
https://github.com/NixOS/nixpkgs/commit/7351644224d60ba92f8491854263cd73e5637eb1 broke the build and was committed directly to master/staging apparently without running `nix-build -A python3Packages.numpyro` first.

### Steps to reproduce
* Checkout https://github.com/NixOS/nixpkgs/commit/7351644224d60ba92f8491854263cd73e5637eb1
* Run `nix-build -A python3Packages.numpyro`

```
Processing ./numpyro-0.11.0-py3-none-any.whl
Requirement already satisfied: tqdm in /nix/store/vnklvsi24gf5cm4386wrn32ldxd08k0r-python3.10-tqdm-4.64.1/lib/python3.10/site-packages (from numpyro==0.11.0) (4.64.1)
Requirement already satisfied: multipledispatch in /nix/store/0za3qmql62r46qdw22m967ppjzzrvih7-python3.10-multipledispatch-0.6.0/lib/python3.10/site-packages (from numpyro==0.11.0) (0.6.0)
[31mERROR: Could not find a version that satisfies the requirement jaxlib>=0.4 (from numpyro) (from versions: none)[0m[31m
[0m[31mERROR: No matching distribution found for jaxlib>=0.4[0m[31m
```

cc maintainers: @fabaff 

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.0-1030-gcp, Ubuntu, 20.04.5 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - channels(sam.ainsworth): `"home-manager, nixgl"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by samuela** [comment]
@mweinelt As author of https://github.com/NixOS/nixpkgs/commit/7351644224d60ba92f8491854263cd73e5637eb1, can you please either fix the build or revert this commit?

**Comment by fabaff** [comment]
>  can you please either fix the build or revert this commit?

Or update `jaxlib` which wasn't updated for a couple of months.

**Comment by samuela** [comment]
Yes, work updating jaxlib is ongoing in https://github.com/NixOS/nixpkgs/pull/219778
