### ISSUE TITLE
Package request: xwayland video bridge

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#222741]
**Project description**

This allows applications like Discord that use xwayland to capture Wayland windows.

**Metadata**

* homepage URL: https://invent.kde.org/davidedmundson/xwaylandvideobridge
* source URL: https://invent.kde.org/davidedmundson/xwaylandvideobridge
* license: GPL2+ https://invent.kde.org/davidedmundson/xwaylandvideobridge/-/blob/master/LICENSES/GPL-2.0-or-later.txt
* platforms: Linux

**Comment by dacioromero** [comment]
I wanted to test this and packaged it my config repo. https://github.com/dacioromero/nix-config/blob/4c06938ca39a992441937eefcd31969e8558a593/pkgs/xwaylandvideobridge.nix

I'm not interested in being a maintainer, but I can submit a PR or someone else can feel free to use mine as a base. The project is definitely beta though cause it segfaulted when resizing Dolphin and crashed Plasma entirely.

**Comment by FredM7** [comment]
If this is the wrong place to post, please let me know.

I can see the package here under `unstable`

https://search.nixos.org/packages?channel=unstable&show=xwaylandvideobridge&from=0&size=50&sort=relevance&type=packages&query=xwaylandvideobridge

However I'm getting the following error after adding to systemPackages when switching:
```
...
error: undefined variable 'xwaylandvideobridge'
       at /nix/store/s6j4damx0bxqm1cybmi7iyf3irx565n7-source/configuration.nix:362:3:
...
```

**Comment by jmastr** [comment]
@FredM7 I guess you jsut want to "cherry-pick" xwaylandvideobridge from unstable, but the rest of your system follows e.g. stable by default?

First you add unstable channel if not already done:
