### ISSUE TITLE
Update request: fourmolu 0.9.0.0 → 0.11.0.0

### ISSUE THREAD

**Issue by deemp** [NixOS/nixpkgs#222726]
- Package name: fourmolu
- Latest released version: [0.11.0.0](https://github.com/fourmolu/fourmolu/releases/tag/v0.11.0.0)

- Current version on the unstable channel: 0.9.0.0 (haskellPackages.fourmolu)
- Current version on the stable/release channel: 0.4.0.0 (22.11)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by MaxHearnden** [comment]
The latest version on the unstable channel is 0.10.1.0 and the attribute name is haskellPackages.fourmolu_0_10_1_0.
It will be updated in the next set of Haskell updates (not the current pr) and the update will be done automatically by running a script so it will be updated at the same time as other packages

**Comment by MaxHearnden** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/223827
