### ISSUE TITLE
cudaPackages: bump cudaPackages_11 -> cudaPackages_12

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#222778]
CC @NixOS/cuda-maintainers 

Blockers:

- [ ] pytorch official support for cuda 12: https://github.com/pytorch/pytorch/issues/91122
- [ ] ...

Thanks @ConnorBaker for the pytorch link

**Comment by nviets** [comment]
Will this bump happen after #220341? I am attempting to build 11_8 now on your latest branch to see if it fixes #224150. No idea if xgboost will be happy with 12, but I'll give it a shot. Thanks @SomeoneSerge for keeping me in the loop!

**Comment by SomeoneSerge** [comment]
> Will this bump happen after https://github.com/NixOS/nixpkgs/issues/220341?

I guess the bump will happen as soon as someone opens the bump PR and runs a nixpkgs-review on it (with `--extra-nixpkgs-config { cudaSupport = true; }`, which is going to be very compute-intensive). Right now the concern is that pytorch doesn't yet support CUDA12, but there are probably others, which is why the safest way to see whether we can update is by trial.

There's no reason we couldn't first update to 11.8: that would likely cause fewer regressions than 12, and would enable you to fix xgboost without resorting to overrides. Still, we'd have to run the builds first

**Comment by samuela** [comment]
Upgrading to CUDA 12 will happen eventually, but I don't realistically see it happening for another few weeks at least.

**Comment by SomeoneSerge** [comment]
Let's open a bump to `11.8` then. @nviets would you like to take that on?

**Comment by nviets** [comment]
Sure - what does the bump entail? An update to the default in all-packages.nix and a nixpkgs-review to see if anything downstream breaks?

**Comment by nviets** [comment]
I am not familiar with the derivation for pytorch, but I see it's coded to accept nixpkgs' default library for CUDA. Should that be left [as-is](https://github.com/nviets/nixpkgs/blob/master/pkgs/development/python-modules/torch/default.nix#L2) to build with 11.8, or should it be an option? I was under the impression in my [xgboost update](https://github.com/nviets/nixpkgs/blob/xgboost175/pkgs/development/libraries/xgboost/default.nix#L11) that it's better to have a configurable version of CUDA using `cudaPackages ? {}`

**Comment by SomeoneSerge** [comment]
We should've bumped long time ago, now we need to do it for https://github.com/NixOS/nixpkgs/pull/259068

**Comment by samuela** [comment]
Agree that we should bump, but why is it needed for https://github.com/NixOS/nixpkgs/pull/259068?

**Comment by SomeoneSerge** [comment]
> Agree that we should bump, but why is it needed for https://github.com/NixOS/nixpkgs/pull/259068?

To avoid spawning extra cudaPackageses: https://github.com/NixOS/nixpkgs/pull/259068/files#diff-7c765cc9768cdae049f8712b4ef719bc94ec8ec2e8df2dd50ddf14c6acd4e580R13927

**Comment by samuela** [comment]
ah right, my own comment all along :P

**Comment by Turakar** [comment]
Hello, what is the state of this? I am currently using `dnf` on Fedora 37 for all CUDA stuff, but I encounter issues with the upgrade to 38 due to GCC incompatibilities with CUDA on Fedora 38. This led me to maybe try CUDA with Nix, but it seems like we still do not have any CUDA 12 support, although Torch moved to CUDA 12.1 as the new default?

**Comment by SomeoneSerge** [comment]
> This led me to maybe try CUDA with Nix, but it seems like we still do not have any CUDA 12 support, although Torch moved to CUDA 12.1 as the new default?

Hi! Note that `cudaPackages` is just the default we set, and you can override* it locally. That said, it's definitely the time we bumped the default version, we were just caught up with other stuff


*An example of how to override the default (do ping [matrix](https://matrix.to/#/%23nix%3Anixos.org?via=someonex.net&via=matrix.org&via=tchncs.de&via=snug.si) or [discourse](https://discourse.nixos.org/) for details if needed!):
```nix
import <nixpkgs> {
  config.allowUnfree = true;
  overlays = [
    (final: prev: { cudaPackages = final.cudaPackages_12; })
  ];
}`

**Comment by Turakar** [comment]
> Hi! Note that `cudaPackages` is just the default we set, and you can override* it locally. That said, it's definitely the time we bumped the default version, we were just caught up with other stuff

Thanks, your suggestion worked! It seems like cuDNN 8.9.2 is not packaged, yet. I think it might be easier for me to go for CUDA 11.8 for now.

**Comment by SomeoneSerge** [comment]
@Turakar note the linked PR too: I had a few evaluation errors when I changed the default

**Comment by Dessix** [comment]
> It is in unstable. Nice 🙂

I just made a PR to add `cudnn` 8.9.6.50 and get it supported in 12.2, if that helps at all: #271201
