### ISSUE TITLE
FreeFileSync: No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by Zahrun** [NixOS/nixpkgs#222755]
### Describe the bug
(FreeFileSync:95639): GLib-GIO-ERROR **: 04:17:37.147: No GSettings schemas are installed on the system
zsh: trace trap (core dumped)  FreeFileSync

### Steps To Reproduce
1. `FreeFileSync`
2. Click on browse

### Expected behavior
Opens file picker.

### Additional context
Should be possible to fix this with wrapGAppsHook. cf. https://github.com/NixOS/nixpkgs/issues/16285

### Notify maintainers

@wegank 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.20, NixOS, 23.05 (Stoat), 23.05pre466479.19cf008bb18`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(aroun): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wegank** [comment]
Does adding `wrapGAppsHook` to `nativeBuildInputs` work for you?

**Comment by nPrevail** [comment]
> Does adding `wrapGAppsHook` to `nativeBuildInputs` work for you?

How does one add this in their configuration.nix file? Do we just add pkgs.wrapGAppsHook into our environment.systempackages?

**Comment by Artturin** [comment]
> > Does adding `wrapGAppsHook` to `nativeBuildInputs` work for you?
> 
> How does one add this in their configuration.nix file? Do we just add pkgs.wrapGAppsHook into our environment.systempackages?

No, it's not supposed to be used like that.
