### ISSUE TITLE
Mullvad GUI no longer works after ce546c7

### ISSUE THREAD

**Issue by jonhermansen** [NixOS/nixpkgs#222952]
### Describe the bug
Due to a discrepancy between mullvad and mullvad-vpn package versions, Mullvad VPN GUI refuses to connect and displays an error advising to restart the application. Restarting the application doesn't help, btw.

### Steps To Reproduce
1. Install `mullvad` and `mullvad-vpn` packages
2. `sudo systemctl start mullvad-daemon`
3. Run `mullvad-gui` and attempt to connect

### Expected behavior
Mullvad GUI should allow me to connect to their servers.

### Screenshots
![image](https://user-images.githubusercontent.com/660911/227638045-90d17437-983a-4646-a3ce-e2daa341d49d.png)

### Additional context
Tracking nixos-unstable
UI displays an error: "App is out of sync" "Please quit and restart the app"
mullvad version 2023.2
mullvad-vpn version 2023.1

### Notify maintainers
@Br1ght0ne @ymarkus @ataraxiasjel @cole-h 

### Metadata
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.7, NixOS, 23.05 (Stoat), 23.05pre466479.19cf008bb18`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
 ```

**Comment by cole-h** [comment]
Is there a reason you're installing both the `mullvad` and `mullvad-vpn` packages?

The `mullvad` package only provides the `mullvad` CLI binary, while `mullvad-vpn` provides the `mullvad` CLI binary _and_ the `mullvad-vpn` GUI binary (i.e. `mullvad-vpn` provides both the CLI and GUI tools you'd want to use, so there's no need to install the CLI-only package).

Please remove `mullvad` from your packages list, and everything will work again.

The problem arises because `mullvad-vpn` is packaged based on the `.deb` file Mullvad publishes, while `mullvad` is packaged from their source.

**Comment by jonhermansen** [comment]
> Is there a reason you're installing both the `mullvad` and `mullvad-vpn` packages?
> 
> The `mullvad` package only provides the `mullvad` CLI binary, while `mullvad-vpn` provides the `mullvad` CLI binary _and_ the `mullvad-vpn` GUI binary (i.e. `mullvad-vpn` provides both the CLI and GUI tools you'd want to use, so there's no need to install the CLI-only package).
> 
> Please remove `mullvad` from your packages list, and everything will work again.
> 
> The problem arises because `mullvad-vpn` is packaged based on the `.deb` file Mullvad publishes, while `mullvad` is packaged from their source.

Ok, I thought they were two complementary packages. I didn't realize that one package was a superset of the other.

I am new to Nix world, I suppose there is no way to mark these two packages as conflicting? I guess there is no harm in having them both installed, other than this particular problem.

**Comment by jonhermansen** [comment]
Nevertheless, I opened #222961 which should fix the issue, and both package versions will be in sync again.

It might be nice in the future to package the graphical Mullvad app from source.

**Comment by cole-h** [comment]
> Nevertheless, I opened #222961 which should fix the issue, and both package versions will be in sync again.

Thank you :)

> It might be nice in the future to package the graphical Mullvad app from source.

Agreed. However, I don't use the graphical app, so I'll leave that to someone who does.
