### ISSUE TITLE
`element-desktop`: config.json is ignored

### ISSUE THREAD

**Issue by AgathaSorceress** [NixOS/nixpkgs#222924]
### Describe the bug
Config.json is being ignored, despite other files in the same directory being read correctly.

### Steps To Reproduce
- Using `home-manager`:  
  1. Add this to the configuration:
  ```nix
  home-manager.users.username = {
    xdg.configFile."Element/config.json".text = ''
      {
        "showLabsSettings": true
      }'';
  };
  ```
  2. `cat ~/.config/Element/config.json` should be a symlink to a json file with the contents specified above
  3. Start `element-desktop`
  4. Observe labs settings (the large dropdown list that includes "rich text editor", "polls history", etc and not video rooms/new session manager) not being shown.
- Manual:
  1. Manually create a file called `config.json` in `~/.config/Element/`.
  2. Write these contents to the file:
  ```json
  {
    "showLabsSettings": true
  }
  ```
  3. Start `element-desktop`
  4. Observe labs settings not being shown.
- Using overlays:
  1. Add this to the configuration:
  ```nix
  nixpkgs.overlays = [
    (final: prev: {
      element-web =
        prev.element-web.override { conf = { showLabsSettings = true; }; };
    })
  ];
  ```
  2. Rebuild `element-desktop` using the overridden `element-web`
  3. Start `element-desktop`
  4. Observe labs settings not being shown.

### Expected behavior
The config.json file should affect the application settings

### Additional context
`--profile` is not being used, just the default .desktop file.
Running `element-desktop` in a terminal logs `/home/agatha/.config/Element exists: yes`
Running `strace` on `element-desktop` and grepping for `config.json` returns:
```
statx(AT_FDCWD, "/nix/store/c12hcc5l0nf8cn1nvwr7h1xf2x7qyir6-element-desktop-1.11.24/share/element/webapp/config.json", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444,stx_size=1594, ...}) = 0
statx(AT_FDCWD, "/nix/store/fkxapwpymnzzdljcvdbfmnax31yibxyi-element-web-wrapped-1.11.24/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=1594, ...}) = 0
openat(AT_FDCWD, "/nix/store/fkxapwpymnzzdljcvdbfmnax31yibxyi-element-web-wrapped-1.11.24/config.json", O_RDONLY|O_CLOEXEC) = 68
statx(AT_FDCWD, "/home/agatha/.config/Element/config.json", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=3589, ...}) = 0
statx(AT_FDCWD, "/home/agatha/.config/Element/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFLNK|0777, stx_size=90, ...}) = 0
statx(AT_FDCWD, "/home/agatha/.config/Element/config.json", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=3589, ...}) = 0
readlink("/home/agatha/.config/Element/config.json", "/nix/store/8cs4jvl7qfzy9kjc0cnn1"..., 4096) = 90
statx(AT_FDCWD, "/nix/store/8cs4jvl7qfzy9kjc0cnn1kmwrns17g4y-home-manager-files/.config/Element/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFLNK|0777, stx_size=65, ...}) = 0
statx(AT_FDCWD, "/nix/store/8cs4jvl7qfzy9kjc0cnn1kmwrns17g4y-home-manager-files/.config/Element/config.json", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=3589, ...}) = 0
readlink("/nix/store/8cs4jvl7qfzy9kjc0cnn1kmwrns17g4y-home-manager-files/.config/Element/config.json", "/nix/store/ipjch3r7x13axib40rf7y"..., 4096) = 65
```
I have verified that this is not an Element issue and not an invalid `config.json`. Outside of NixOS, I also tried reproducing this on an Arch desktop with Nix installed. The Arch package for `element-desktop` `1.11.24` reads the config file correctly, while running `nix run nixpkgs#element-desktop` on the same system successfully opens the nixpkgs version of element-desktop (also `1.11.24`) and loads up my existing logged-in session in ~/.config/Element, but ignores the same `config.json` file.

### Notify maintainers

@Ma27 
@fadenb 
@mguentner 
@Ekleog 
@Ralith 
@dali99 
@sumnerevans 

### Metadata
Output of `nix-shell -p nix-info --run "nix-info -m"`

NixOS laptop:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.97, NixOS, 22.11 (Raccoon), 22.11pre-git`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Arch desktop:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.7-arch1-1, Arch Linux, noversion, rolling`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(agatha): `"nixpkgs-22.11"`
 - nixpkgs: `/home/agatha/.nix-defexpr/channels/nixpkgs`
```

**Comment by fogti** [comment]
hmm when using home-manager, it will use a symlink, so... does it also not work if all symlinks along the way to /home/.../.config/Element/config.json are replaced with normal directories/files. (this is mostly speculation about the `readlink` calls...)?

**Comment by fogti** [comment]
hmm I managed to get it to work on NixOS-unstable with `config.json` containing:
```json
{
  "show_labs_settings": true
}
```

**Comment by fogti** [comment]
strace:
```
statx(AT_FDCWD, "/mnt/ZSEC/fogti/.config/Element/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=33, ...}) = 0
openat(AT_FDCWD, "/mnt/ZSEC/fogti/.config/Element/config.json", O_RDONLY|O_CLOEXEC) = 70
statx(70, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=33, ...}) = 0
read(70, "{\n  \"show_labs_settings\": true\n}"..., 33) = 33
close(70)                               = 0
```

**Comment by AgathaSorceress** [comment]
I just made sure that everything leading up to the file is not a symlink and has correct permissions and then replaced the `config.json` symlink with a normal file (same permissions as the rest of files in `~/.config/Element`); I still get the same default Element where the Labs tab doesn't display any of the hidden-by-default labs settings.

for what it's worth, I'm currently running NixOS 23.05 and not unstable, but the `element-desktop` package seems to be the same either way

**Comment by fogti** [comment]
I'm on nixos 23.11.20230606.0ce0c73 and my element executable is /nix/store/lgajzaqah17whsfsw5p4s49d5jqzp5aj-element-desktop-1.11.31/bin/element-desktop ... idk

**Comment by AgathaSorceress** [comment]
Different hash for me of course, but yeah also using 1.11.31

**Comment by AgathaSorceress** [comment]
The relevant part of the strace output (this time no symlinks): 
```
statx(AT_FDCWD, "/home/agatha/.config/Element/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=3589, ...}) = 0
openat(AT_FDCWD, "/home/agatha/.config/Element/config.json", O_RDONLY|O_CLOEXEC) = 68
statx(68, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=3589, ...}) = 0
read(68, "{\n  \"settingDefaults\": {\n    \"cu"..., 3589) = 3589
close(68)                               = 0
```
the correct `config.json` file does begin with `"settingDefaults": {` but still doesn't affect anything...

**Comment by fogti** [comment]
> the correct config.json file does begin with "settingDefaults": { but still doesn't affect anything...

huh, I managed to get it to work with exactly the content quoted above in my post...
the stock `config.json` (for me e.g. in `/nix/store/lgajzaqah17whsfsw5p4s49d5jqzp5aj-element-desktop-1.11.31/share/element/webapp/config.json` resolves to `/nix/store/zglzqaj5c0mwiw178sz23hlblvdxs814-element-web-1.11.31/config.json`)
looks like:
```json
{
  "default_server_config": {
    "m.homeserver": {
      "base_url": "https://matrix-client.matrix.org",
      "server_name": "matrix.org"
    },
    "m.identity_server": {
      "base_url": "https://vector.im"
    }
  },
  "disable_custom_urls": false,
  "disable_guests": true,
  "disable_login_language_selector": false,
  "disable_3pid_login": false,
  "brand": "Element",
  "integrations_ui_url": "https://scalar.vector.im/",
  "integrations_rest_url": "https://scalar.vector.im/api",
  "integrations_widgets_urls": [
    "https://scalar.vector.im/_matrix/integrations/v1",
    "https://scalar.vector.im/api",
    "https://scalar-staging.vector.im/_matrix/integrations/v1",
    "https://scalar-staging.vector.im/api",
    "https://scalar-staging.riot.im/scalar/api"
  ],
  "bug_report_endpoint_url": "https://element.io/bugreports/submit",
  "uisi_autorageshake_app": "element-auto-uisi",
  "default_country_code": "GB",
  "show_labs_settings": false,
  "features": {},
  "default_federate": true,
  "default_theme": "light",
  "room_directory": {
    "servers": [
      "matrix.org"
    ]
  },
  "enable_presence_by_hs_url": {
    "https://matrix.org": false,
    "https://matrix-client.matrix.org": false
  },
  "setting_defaults": {
    "breadcrumbs": true
  },
  "jitsi": {
    "preferred_domain": "meet.element.io"
  },
  "element_call": {
    "url": "https://call.element.io",
    "participant_limit": 8,
    "brand": "Element Call"
  },
  "map_style_url": "https://api.maptiler.com/maps/streets/style.json?key=fU3vlMsMn4Jb6dnEIFsx"
}
```

**Comment by fogti** [comment]
shouldn't thus `settingDefaults` actually be `setting_defaults`? where do these CamelCase config keys come from?

**Comment by AgathaSorceress** [comment]
As far as I'm aware, the element-web and Element-Desktop config.json are different. the config.json I used for testing is the same one that I have confirmed definitely works on Arch using the same element-desktop version

**Comment by fogti** [comment]
oof... so https://github.com/vector-im/element-web/blob/develop/docs/config.md documents the options of element-web, and element-desktop accesses the element-web configs (in the stated paths) on my NixOS install... does the element-desktop config.json deviation you suspect also have associated documentation?

**Comment by fogti** [comment]
ok, I hate it https://github.com/vector-im/element-desktop/blob/develop/element.io/release/config.json
who tf thought this would be a good idea (to have multiple names for the same config entry, and one of them works and the other doesn't... depending on who-knows-what idk)

**Comment by fogti** [comment]
every `/config.json` mention in strace
```
statx(AT_FDCWD, "/nix/store/lgajzaqah17whsfsw5p4s49d5jqzp5aj-element-desktop-1.11.31/share/element/webapp/config.json", AT_STATX_SYNC_AS_STAT, STATX_ALL,  <unfinished ...>
statx(AT_FDCWD, "/nix/store/zglzqaj5c0mwiw178sz23hlblvdxs814-element-web-1.11.31/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL,  <unfinished ...>
openat(AT_FDCWD, "/nix/store/zglzqaj5c0mwiw178sz23hlblvdxs814-element-web-1.11.31/config.json", O_RDONLY|O_CLOEXEC <unfinished ...>
statx(AT_FDCWD, "/home/fogti/.config/Element/config.json", AT_STATX_SYNC_AS_STAT, STATX_ALL,  <unfinished ...>
statx(AT_FDCWD, ".../fogti/.config/Element/config.json", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL,  <unfinished ...>
openat(AT_FDCWD, ".../fogti/.config/Element/config.json", O_RDONLY|O_CLOEXEC <unfinished ...>
```

**Comment by AgathaSorceress** [comment]
Right, so after looking into it more, I think the `config.json` files are actually the same, it's just that it tends to look very different depending on if it's used for an element-web instance or for configuring element-desktop.
I couldn't find good docs for a lot of the config options, but there's also [this](https://github.com/vector-im/element-web/blob/develop/docs/theming.md) page. It seems that some time after I originally wrote my config (looks like March 2022) they renamed everything to use snake case instead of camel case.

Weirdly enough, the config with camel case options works with `element-desktop 1.11.31` on Arch, but the same config doesn't work with `element-desktop 1.11.31` using the nix package unless everything is renamed to use snake case.

I'm still not sure why this is the case, but I guess the solution is "make sure your `config.json` does not have camel case keys"
