### ISSUE TITLE
X11 input broke

### ISSUE THREAD

**Issue by ikervagyok** [NixOS/nixpkgs#22290]
## Issue description
between 8a104aa..63f609b1 (current master) my x11-input broke, no easy way to log in/examine (behind a corporate firewall...) 

### Steps to reproduce
nixos-rebuild boot; reboot

## Technical details

* System: (NixOS: 8a104aa)
* Nix version: (1.11.6)
* Nixpkgs version: (17.03.git.63f609b1a4)

**Comment by ikervagyok** [comment]
maybe this is causing it: 82bcfef109ecf5
will look into it later.

**Comment by ikervagyok** [comment]
confirmed, reverting 82bcfef caused this issue to go away.
tested both with `services.xserver.libinput.enable = true` and `false`

**Comment by fpletz** [comment]
I can also confirm this. I'll have another look at the code to see if we can fix this before reverting.

Thanks for the report and the investigative work!

**Comment by MP2E** [comment]
Exact same issue is happening on my end, thank you for looking in to it!

**Comment by fubarbaz** [comment]
Is #22337 also related to this?

**Comment by mdorman** [comment]
This seems like a revert-first-fix-later sort of bug.

**Comment by fpletz** [comment]
Agreed, I couldn't find out what's wrong with that commit. :disappointed:
