### ISSUE TITLE
Feature request: Implement two NixOS options to control the xdg-user-dirs in a better way

### ISSUE THREAD

**Issue by cx405** [NixOS/nixpkgs#222904]
## Feature request
Implement two NixOS options to control the xdg-user-dir in a better way. 
Packages affected: [xdg-user-dirs](https://github.com/NixOS/nixpkgs/pkgs/tools/X11/xdg-user-dirs/default.nix)

## Issue description
At current point system owner has no control over xdg-dir specification, commonly known as "~/Documents, Videos, Music.." directories in home directory. Currently by default the (edit:) `xdg-user-dirs-update` script must be manually invoked, which contradicts with xdg-dir specification. At same time, I assume not everyone wants to get these directories in his home directory and hence its not invoked. However since (edit:) `xdg-user-dirs-update` script is still not masked, any application or user can call it and recreate at any random point.

To address the issue, I suggest two NixOS options:
1. option that controls xdg-user-dir, suggested name: "xdg.dirs", accepts variable of type string. 
- If "full", it either creates a service that starts during user login and calls (edit:) `xdg-user-dirs-update` script; or it should symlink (edit:) `xdg-user-dirs-update` script into the "/run/current-system/sw/etc/xdg/autostart/". Both ways will result in a call to (edit:) `xdg-user-dirs-update` script, which would rebuild all home directories to specification.
- If "desktop_only", same as enabled, but causes it just create the bare minimum - the "Desktop" directory instead of whole directory tree.
- If "disabled", then (edit:) `xdg-user-dirs-update` script from package "xdg-user-dirs" should be renamed to something else and (edit:) `xdg-user-dirs-update` instead output a text message about this option and quit. This completely prevents rebuilding of xdg dirs structure in user home.

All desktops should set default of this to "desktop_only", otherwise "disabled".

2. option to customize default directory names, "xdg.dirsDefault", accepts variable of type string.
With one check, the content in the string can be linked to existing expression (https://github.com/NixOS/nixpkgs/issues/33282#issuecomment-524555993) `environment.etc."xdg/user-dirs.defaults".text`.

The check is if its an empty string, that should produce no output and be ignored; hence default upstream home directory files  from "xdg-user-dirs" will be used.

## Example of options and implementation
All option names are suggested.

1. xdg.dirs = "full" / "desktop_only" / "disabled";
type: string
default: "desktop_only"
example: xdg.dirs-update="full"

4. xdg.dirsDefault=''  '';
type: string
default: '''';
example: xdg.dirs-default=''
 DESKTOP=system/desktop
 DOWNLOAD=downloads
 TEMPLATES=system/templates
 PUBLICSHARE=system/public
 DOCUMENTS=documents
 MUSIC=media/music
 PICTURES=media/photos
 VIDEOS=media/video
 '';

**Comment by jtojnar** [comment]
But I do not think the proposed module would be useful. `xdg-user-dirs` just does not allow you to configure the user dirs declaratively.

At best you could have a NixOS module with an option to the set the defaults:

- which would just be a thin wrapper around`environment.etc."xdg/user-dirs.defaults".text`

and make sure the `xdg-user-dirs-update` is run:

- add `pkgs.xdg-user-dirs` to `environment.systemPackages`,
- `/etc/xdg` from packages installed to `environment.systemPackages` is already linked to `/run/current-system/sw` by the [`environment.nix` module](https://github.com/NixOS/nixpkgs/blob/dda0967dce2f071b8f92232d431d84f1039cb870/nixos/modules/programs/environment.nix#L44).
- and possibly  another NixOS module for choosing an autostart file runner

**Comment by cx405** [comment]
@jtojnar 
Thank you for input! 

> It does not need to be manually invoked, it has a autostart entry so any desktop environment supporting XDG autostart will support it.

> If you do not use a pre-configured desktop environment, you are responsible for building your own.

My current configuration.nix does not add or reference "xdg-user-dirs". 
I am using preconfigured desktop:
```
services.xserver.enable=true;
services.xserver.displayManager.sddm.enable=true;
services.xserver.desktopManager.plasma5.enable=true;
```

* this configuration automatically pulls  `xdg-user-dirs` package
* default directories as per xdg-dirs spec are ignored
* it creates only "Desktop" directory: xdg-user-dir script is internally called only with xDESKTOP parameter
* defining manual directories `[in this way](https://github.com/NixOS/nixpkgs/issues/33282#issuecomment-524555993)` in configuration nix are completely ignored (#221604)
* I have to manually invoke xdg-user-dir script or manually place its invocation in service file or autostart for these directories to be created

Due to reasons above, I can't disable what (the way I see it) is broken. My suggestion allows precise control over xdg-user-dirs, the desktop directories can be completely ignored, built to minimum as only "Desktop", build per specification or manually customized.

> [xdg-user-dir](https://man.archlinux.org/man/xdg-user-dir.1) program reads the settings so having a service just calling does not make sense.

contents of:  /nix/store/qi2l4wmcbn9028ygg67ki25na4fnrl2l-xdg-user-dirs-0.18/bin/xdg-user-dir are as following (this is end point to where `whereis xdg-user-dir` on NixOS 22.11 points):

```
#!/nix/store/96ky1zdkpq871h2dlk198fz0zvklr1dr-bash-5.1-p16/bin/sh

test -f ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs && . ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs
if [ "x$1" = "xDESKTOP" ]; then
  eval echo \${XDG_${1}_DIR:-$HOME/Desktop}
else
  eval echo \${XDG_${1}_DIR:-$HOME}
fi
```
I am sure that eval statement actually writes out the directories.

> The way xdg-user-dirs works is that you need to set every directory (you can point it to $HOME if you want to disable it). And the Desktop directory is the least useful one – many modern DEs do not even have desktop.

As I see it, there is a file, which contains  default configuration "user-dirs.defaults". This file can be overriden with `environment.etc."xdg/user-dirs.defaults".text`. However, just overriding it brings no effect. Consider [this example](https://github.com/NixOS/nixpkgs/issues/221604#issuecomment-1473989401) about which files exist in the system with an override present in configuration.nix . 

Effect happens only when "xdg-user-dirs" script is manually invoked. With installed Plasma desktop, it is internally  invoked only with "xDESKTOP" argument, that produces only "Desktop" directory, thus (in other words) stock or overriden configuration is ignored. 

When manually invoked, the directories are written out and the file `~/.config/user-dirs.dirs` appears for the first time.

> This is super ugly. If you want to disable it, you should just not install xdg-user-dirs. Though then you will not have XDG compliant desktop environment.
I understand, I tried my best to produce some kind of inital solution, which would fit into everyone's way of use and allow to control how "xdg-user-dirs" is handled with NixOS tools.  Using boolean value won't suffice, because there are three ways (as I see it): completely ignore xdg-user-dirs, build only Desktop folder, fully adhere to the spec (plus the method to customize these directories).

 , and there are few scripts that use this file to flesh out (instantiate) that via shell variables with real locations.  When xdg-user-dir script is called, it writes out user-dirs.dirs

**Comment by jtojnar** [comment]
> default directories as per xdg-dirs spec are ignored

I doubt that it is the case. Most likely, `xdg-user-dirs-update` already wrote to `~/.config/user-dirs.dirs` so further changes to the defaults will be ignored, as expected by the xdg-user-dirs.

> I am sure that eval statement actually writes out the directories.

No, it just looks up the directory in the user config and prints it out. The desktop is special cased just to print a different default value when not found in the config.

**Comment by cx405** [comment]
> No, it just looks up the directory in the user config and prints it out. The desktop is special cased just to print a different default value when not found in the config.
You are absolutely correct, sorry I incorrectly stated in this thread what I invoked. Indeed, I followed your advice here and re-added override, rebooted into new generation into Plasma, - there were no dirs, also no `~/.config/user-dirs.dirs` - and after I manually invoked `xdg-user-dirs-update` these folders appeared, `~/.config/user-dirs.dirs` also appeared.

> I doubt that it is the case. Most likely, xdg-user-dirs-update already wrote to ~/.config/user-dirs.dirs so further changes to the defaults will be ignored, as expected by xdg-user-dirs.
Thats the problem - `~/.config/user-dirs.dirs` is not created, with override its also not created. Only manually invoking `xdg-user-dirs-update` appears. This is under Plasma. 
I think the reason why Plasma behaves like that is that not everyone wants those in home directory and lone "Desktop" folder suffices for Plasma, so the switch what to create might be of use.
On systems with users with different preferances, once could limit it to Desktop-only, so those users who wish it, should then add `xdg-user-dirs-update` manually to DE autostart.

**Comment by jtojnar** [comment]
I can only tell you that it correctly creates `~/.config/user-dirs.dirs` in GNOME and Pantheon (just re-tested both in fresh VMs).

Perhaps there is a bug with Plasma in NixOS but that needs to be brought up with Plasma maintainers.

https://github.com/NixOS/nixpkgs/blob/00766fe9ea6da19a5a44893d3ceac3292b7d6222/nixos/modules/services/x11/desktop-managers/plasma5.nix#L278

**Comment by cx405** [comment]
Thank you, you are correct. 
This is what I observe for NEW user with clean home. Configuration.nix has only plasma5 enabled.

```
> find ~ -name *dirs.dirs
> ls -1 ~
Desktop
> xdg-
xdg-desktop-icon      xdg-icon-resource     xdg-screensaver       xdg-user-dirs-update
xdg-desktop-menu      xdg-mime              xdg-settings          
xdg-email             xdg-open              xdg-user-dir          


> xdg-user-dirs-update
> find ~ -name *dirs.dirs
/home/testuser/.config/user-dirs.dirs
> ls -1 ~
Desktop
Documents
Downloads
Music
Pictures
Public
Templates
Videos
```

```
> ls -1 /run/current-system/sw/etc/xdg/autostart/
baloo_file.desktop
gmenudbusmenuproxy.desktop
kaccess.desktop
klipper.desktop
kwrited-autostart.desktop
org.kde.kdeconnect.daemon.desktop
org.kde.plasmashell.desktop
pam_kwallet_init.desktop
polkit-kde-authentication-agent-1.desktop
powerdevil.desktop
xdg-user-dirs.desktop
xembedsniproxy.desktop
> cat /run/current-system/sw/etc/xdg/autostart/xdg-user-dirs.desktop
[Desktop Entry]
Type=Application
Name=User folders update
TryExec=xdg-user-dirs-update
Exec=xdg-user-dirs-update
StartupNotify=false
NoDisplay=true

X-GNOME-Autostart-Phase=Initialization
X-KDE-autostart-phase=1
```

So, Plasma ignores the autostart of /run/current-system/sw/etc/xdg/autostart/xdg-user-dirs.desktop

**Comment by cx405** [comment]
@jtojnar I have opened #222925 based on this. Thank you VERY MUCH for your help. I will hence close this request to prevent parallel/spread discussion.
