### ISSUE TITLE
Update request: prusa-slicer 2.5.0 → 2.6.0 alpha 5

### ISSUE THREAD

**Issue by dmayle** [NixOS/nixpkgs#222937]
- Package name: prusa-slicer
- Latest released version: 2.5.0

- Current version on the unstable channel: 2.5.0
- Current version on the stable/release channel: 2.5.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@Moredread 
@thorstenweber83 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by dmayle** [comment]
I understand that you might wait until 2.6.0 is released, as it hopefully isn't too far away, but there are enough improvements that I wasn't willing to wait.

I've made a patched derivation that builds 2.6.0-alpha5, adding it here in case it's useful:
https://github.com/dmayle/nix-config/blob/main/packages/prusa-slicer-alpha.nix

**Comment by dmayle** [comment]
It uses the updated tbb, and recompiles openvdb so there isn't a conflict between the two packages.
It uses the latest wxGTX, disabling EGL for GLEW because it doesn't work properly (and fixing the Makefile which is broken in the fork).  Finally, it includes the recommended version of nanosvg

**Comment by ziguana** [comment]
Just used your derivation to slice a print with organic supports. Everything seems to work, thanks!

**Comment by Moredread** [comment]
Thanks :) I think we'll wait for the stable release, but I'll try yours asap.

**Comment by qhga** [comment]
Thanks for your work! I was also trying to make a flake for the alpha but was stuck with nanosvg. Thanks to your example I now know what I did wrong.

**Comment by trzpiot** [comment]
@dmayle Can this be closed? The current version `2.7.1` in Nixpkgs is the newest.

**Comment by dmayle** [comment]
Yup, of course
