### ISSUE TITLE
Build failure: minitube

### ISSUE THREAD

**Issue by klemensn** [NixOS/nixpkgs#223076]
### Steps To Reproduce

1. `nix-shell -p minitube`

### Build log

[`nix log /nix/store/7v4p6r1pla1rizbqs7bnjifwsm15ggqz-minitube-3.9.3.drv`](https://gist.github.com/klemensn/5b379988456afc0eda0202acce950731)

### Metadata

```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.104, NixOS, 22.11 (Raccoon), 22.11.3333.83607dae4e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(kn): `"nixos"`
 - channels(root): `"nixos-22.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by MaxHearnden** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/202598 which is only on the unstable branch
