### ISSUE TITLE
Disable tcp_wrappers where possible

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixpkgs#22312]
## Issue description

While working on https://github.com/NixOS/nixpkgs/pull/22303 I noticed that we still have tcp_wrappers support compiled for nfs-utils. Same goes for several other services:

* atftp
* tftp-hpa
* argus-clients
* argus
* sshl

tcp_wrappers feels to me a faulty way to impose security as we already have kernel-space iptables which should be more resilient and also much more configurable. I would be happy to go forward and remove its support where possible to promote NixOS firewall but first I want feedback as my opinion may be with flaws. For the record, Arch Linux [removed it some time ago](https://www.archlinux.org/news/dropping-tcp_wrappers-support/) but it's not exactly known as security-conscious distro.

If we progress with removing tcp_wrappers, it would also be a good idea to note this in NixOS manual because most NFS setup guides describe `/etc/hosts.{allow,deny}` as the way to secure NFS servers.

**Comment by joachifm** [comment]
From googling around, `tcp_wrappers` seems to do a somewhat better job at host-based acl than iptables and provides an additional layer to cover up holes in the fw.

**Comment by abbradar** [comment]
Hm, indeed, one feature that I noticed only now is that tcp_wrappers supports blocking by hostname.

It seems useful enough to let it stay -- please disregard this!
