### ISSUE TITLE
libreoffice no longer works headlessly

### ISSUE THREAD

**Issue by evils** [NixOS/nixpkgs#223186]
### Describe the bug
i can no longer use libreoffice headlessly
i suspect this is due to the rewrite of the wrapper

additionally, the `libreoffice` binary is no longer provided, only `swriter` etc, which are supposed to be usable headlessly too

and maybe more impactful, attempting to launch the GUI with `swriter ./some.odt` doesn't work either

### Steps To Reproduce
1. create `some.odt`
2. `swriter --headless --convert-to pdf some.odt` -> `Error: source file could not be loaded`
3. or, `libreoffice --headless --convert-to pdf some.odt` -> `The program 'libreoffice' is not in your PATH. It is provided by several packages.`

for a known working .odt file or project using the headless feature, see [here](https://gitlab.com/evils/kicad-workshop) (already amended to attempt to use `swriter` instead of `libreoffice`)

### Expected behavior
`libreoffice some.odt` to open libreoffice with the appropriate sub-app with that file open
`swriter some.odt` to open libreoffice writer with that file open
`swriter --convert-to pdf some.odt` to yield `some.pdf`
`nix-shell --pure -p libreoffice --run "libreoffice --convert-to pdf some.odt` to yield `some.pdf`

### Screenshots
error window on `swriter handout.odt`
![image](https://user-images.githubusercontent.com/30512529/227753308-4a3b4aed-9cee-4232-9278-39909db38bfa.png)

### Notify maintainers

@7c6f434c 
@doronbehar due to 3966519d12be2fb3fded3420f1cc82d681b17b5d, the wrapper rewrite which seems to have introduced this issue

### Metadata
```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.7, NixOS, 23.05 (Stoat), 23.05.git.9fd74a027f2`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos-21.11pre301044.87807e64a5e, nixos-hardware"`
 - channels(evils): `"home-manager, nixos-unstable, nixpkgs"`
 - nixpkgs: `/home/evils/.nix-defexpr/channels/nixpkgs`

```

**Comment by doronbehar** [comment]
> error window on `swriter handout.odt`

Aish... didn't realize this usage would break when I added the `--chdir` flag to `makeWrapper`... As a workaround, you can run the unwrapped executables in the meantime, this should work (works for me):

```
$(nix-build libreoffice.unwrapped)/lib/libreoffice/program/swriter --convert-to pdf some.odt
```

I'm a bit confused though, which `nixpkgs` revision are you evaluating exactly? `87807e64a5e` which is used in your `nix-info -m` report is before the wrapper rewrite.

**Comment by doronbehar** [comment]
I don't experience other issues you mention on current branch `master`.

**Comment by evils** [comment]
oh right, i had this issue on `nixpkgs` yesterday on my laptop
i filed the issue on my desktop

**Comment by evils** [comment]
i'm unclear about what issues you don't experience on current `master`
on the `master` branch, there's no `${libreoffice}/bin/libreoffice`

**Comment by doronbehar** [comment]
My bad :sweat_smile: My `nixpkgs` wasn't updated at all!

Adding `${libreoffice}/bin/libreoffice` won't be that hard, but fixing the `--chdir` issue is harder...
