### ISSUE TITLE
Packaging request: selfspy

### ISSUE THREAD

**Issue by AnzenKodo** [NixOS/nixpkgs#223150]
**Project description**

Selfspy is a daemon for Unix/X11, Mac OS X and Windows, that continuously monitors and stores what you are doing on your computer. This way, you can get all sorts of nifty statistics and reminders on what you have been up to.

**Metadata**

* homepage URL: https://github.com/selfspy/selfspy
* source URL: https://github.com/selfspy/selfspy
* license: gpl3+
* platforms: unix, linux, darwin

**Comment by Foxboron** [comment]
I'm 99% sure this project doesn't work anymore.

**Comment by AnzenKodo** [comment]
Sorry, Now that I read docs closely it only supports Python 2 :(
