### ISSUE TITLE
collission between postgresql and python*Packages.psycopg2

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [NixOS/nixpkgs#22311]
## Issue description

```
$ nix-shell .
these derivations will be built:
  /nix/store/2qb8sbvplwcjn74byybfbwz58l19s1yj-python-and-tools.drv
building path(s) ‘/nix/store/94fb8lvn7s9lnf24hshb52sz3a0gr3j2-python-and-tools’
collision between `/nix/store/pnhpxiww5mwksxsa3sxfn64jkhfpszna-postgresql-9.5.5/bin/clusterdb' and `/nix/store/b2308rcn1xgjmnypqlm0ai162s6f7ayx-python-2.7.13-env/bin/clusterdb'
builder for ‘/nix/store/2qb8sbvplwcjn74byybfbwz58l19s1yj-python-and-tools.drv’ failed with exit code 25
error: build of ‘/nix/store/2qb8sbvplwcjn74byybfbwz58l19s1yj-python-and-tools.drv’ failed
/run/current-system/sw/bin/nix-shell: failed to build all dependencies
```

### Steps to reproduce
```

let
  pkgs = import <nixpkgs> {};
  python = pkgs.python27Full.withPackages (ps: with ps;
    [

      virtualenv

      sqlalchemy_1_0
      pyyaml
      pip
      wheel
      lxml
      pycurl
      numpy
      flask
      psycopg2
      pycparser
      cffi
      flake8
      functools32

      msgpack
      pyzmq

      tornado

      cryptography
    ]);

  env = pkgs.buildEnv {
    name = "python-and-tools";
    paths = [python] ++ (with pkgs;
      [
        libffi
        nss
        curl
        postgresql95
        libxml2
        libxslt
      ]);
  };

  script = ''
    echo redacted
  '';

  shell = pkgs.stdenv.mkDerivation {
    name = "workenv-qe";
 
    buildInputs = [env];
    shellHook = script;
   };

in shell

```

## Technical details
```
$ nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03pre99626.f1ba2c8"
```

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
* Nix version: (run `nix-env --version`)
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by FRidh** [comment]
That's because `psycopg2` propagates `pkgs.postgresql`. 
I don't know what parts `psycopg2` actually needs, but I guess it only needs libraries so `pkgs.postgresql.lib` would sufficient. 

In any case, you will still have collisions and I don't think there is any way to prevent that aside from setting a priority.

**Comment by RonnyPfannschmidt** [comment]
i believe psycopg2 wont need an actual postgresql, just the shared libs linked correctly

**Comment by FRidh** [comment]
> Note that you can add non-Python packages to python.withPackages and it will add them to that environment, no need to symlink twice.

Actually, if you would do that, you wouldn't get any collisions.

**Comment by RonnyPfannschmidt** [comment]
im doing that now
is there any way to warn about such collisions? to ease debugging?

**Comment by FRidh** [comment]
The error reports the two Nix store paths. What else do you need? And you have the warning right there. Nix can't warn ahead of time (that is, during evaluation), because it doesn't know the contents of the store paths because they're not yet existing.

**Comment by RonnyPfannschmidt** [comment]
@FRidh but when the error happens, isnt is possible/sensible to backtrac the dependencies?

this would also help finding various recent other collision where the same package is in the path twice preventing kde5 and gnome3 at the same time for example

**Comment by FRidh** [comment]
In the end, this is *the* downside of symlinking. In the past, `python.buildEnv` would only symlink Python packages (that is, packages that had `pythonPath` set) however I changed that in https://github.com/NixOS/nixpkgs/pull/18696. See https://github.com/NixOS/nixpkgs/pull/18273 for the motivation.

> @FRidh but when the error happens, isnt is possible/sensible to backtrac the dependencies?

Exactly what would you want to see? At the left you see the store path of the actual package, and on the right of the `env`. If you want to find out how it appeared in the store path of the env you can use `nix-store -q --tree <hash of env>`.

**Comment by RonnyPfannschmidt** [comment]
@FRidh i would like to get nix itself tell me the derivations and their dependencies

python packages are not the only thing that have trouble ith unexpected collisions, it also happens for gnome and kde in the mainsystem,

**Comment by FRidh** [comment]
But that's a Nix issue, and doesn't belong on this tracker. I'm closing this now since the issue can be circumvented by passing `ignoreCollisions` to `python.buildEnv.override`. If you want to have discussion on whether https://github.com/NixOS/nixpkgs/pull/18696 should be reverted we could have a separate issue about that.

**Comment by CMCDragonkai** [comment]
Can we change `psycopg2` to only use the `pg.lib`? https://github.com/NixOS/nixpkgs/issues/22311#issuecomment-276348849

I just came across this problem as well, but because I was using a custom postgresql environment with postgis loaded into it.
