### ISSUE TITLE
man path not reliable

### ISSUE THREAD

**Issue by vcunat** [NixOS/nixpkgs#22318]
If you get `~/.nix-profile/man` from some (bogus) package, `~/.nix-profile/share/man` isn't used anymore.  This happened to me due to `gwenview` propagating `lmdb`.  Affected: current man on both master and 16.09.  It's possible the same happens with `/run/current-system/sw/`.

**Comment by knedlsepp** [comment]
I'm also having trouble showing man pages at the moment.

**Comment by knedlsepp** [comment]
I'm not really sure what helped in the end. But I couldn't view `man nix-env` and tried unsetting/setting $MANPATH, recreating the mandb cache `mandb -c`, clear bash cache `hash -r` installing/uninstalling man `nix-env -iA nixpkgs.man`. After reinstalling `nix` it suddenly worked.

**Comment by Mic92** [comment]
I found a declarative way of installing packages less surprising: `https://github.com/Mic92/nixos-configuration/blob/master/.nixpkgs/config.nix#L174`

**Comment by Mic92** [comment]
Guess so.
