### ISSUE TITLE
Automatically open ports for matrix synapse server

### ISSUE THREAD

**Issue by moretea** [NixOS/nixpkgs#22328]
Add a `openPortsInFirewall` option, with a default of `true`. It's pretty pointless to run a matrix server without connecting to other ones.

**Comment by copumpkin** [comment]
This could be said about most of our services. It'd be nice if we could abstract over common service patterns like the enable option and port settings. I.e., some sort of function that produces the `{ config, ... }: { options = ...; config = ... }` structure but takes care of automatically managing common repetitive crap like this.

Ideal to me feels like:

1. Global setting, `firewall.openServicePortsByDefault`, defaulting to `false`
2. Every service (via some abstraction over services) has a `service.foo.openPorts`, with a default value of `firewall.openServicePortsByDefault`
3. Now if you set `firewall.openServicePortsByDefault = true;`, services open ports by default, but you can opt individual services out by setting `service.foo.openPorts = false;`

Either way see #19504

**Comment by FRidh** [comment]
Closing because this is, as pointed out by @copumpkin, discussed in #19504.
