### ISSUE TITLE
services.kubo: ipfs CLI only works under root

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#223289]
### Describe the bug

When running an ipfs/kubo node using `services.kubo.enable = true`, the `ipfs` CLI is not usable unless executed with root privileges. E.g.:

```console
❯ ipfs id
Error: error loading plugins: open /var/lib/ipfs/config: permission denied
❯ sudo -E ipfs id
{
	"ID": ...
}
```

I don't know if that's a bug or the intended behaviour.
There's a NixOS test for kubo, which tests `ipfs ... id`, but only runs it with root privileges:
https://github.com/NixOS/nixpkgs/blob/151981821c03435ee8047f6c1b9367c1a26788ed/nixos/tests/kubo.nix#L30

### Steps To Reproduce
1. `services.kubo.enable = true`
2. `ipfs id` `->` get a "permission denied" error
3. `sudo -E ipfs id`

### Expected behavior

Both commands print the json with node public info.
If step 2 was supposed to fail after all, I expected to see a different description of the module or a comment in the test.

### Notify maintainers

- @Luflosi (`services.kubo` maintainer)
-  @Ericson2314 (edited the nixos test)

As I said, I don't know if this was the intended behaviour. Just in case, I apologize for the noise 🙃 
### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.19, NixOS, 23.05 (Stoat), 23.05.20230314.7067edc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`


```

**Comment by Luflosi** [comment]
This would have been fixed by https://github.com/ipfs/kubo/pull/9366 but the fix seems to have been ignored upstream.
I think I found a way to fix this without patching Kubo. Ping me in one month if I haven't gotten around to trying my idea by then.

**Comment by Luflosi** [comment]
This would have been fixed by https://github.com/ipfs/kubo/pull/9366 but the fix seems to have been ignored upstream.
I think I found a way to fix this without patching Kubo. Ping me in one month if I haven't gotten around to trying my idea by then.

**Comment by Luflosi** [comment]
See also #82580, which is a very similar issue.

**Comment by Luflosi** [comment]
I created #226288 to fix this.
