### ISSUE TITLE
xfsettingsd / xfce4-power-man crashes

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#22322]
## Issue description

```
[58934.974801] xfsettingsd[4668]: segfault at 0 ip 00007fd897c7bde9 sp 00007ffdedd61290 error 4 in libupower-glib.so.3.0.1[7fd897c6b000+25000]
```

causing the theme to be resetted to the (ugly) default.

### Steps to reproduce

Try to use an alternative theme (doesn't matter which, AFAICS) in xfce4-12.

## Technical details

* System: 17.03pre99626.f1ba2c8 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "17.03pre99626.f1ba2c8"

---

When running either of them with `--no-daemon`:

```
(xfsettingsd:6464): libupower-glib-WARNING **: Couldn't connect to proxy: Fehler beim Aufruf von StartServiceByName für org.freedesktop.UPower: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.UPower': timed out
Segmentation fault
```

From what I find with google, this issue is known. Either way, I'm not sure how to work around.
I tried explicitely installing the `upower` daemon and starting it... didn't help.

**Comment by vcunat** [comment]
Probably a consequence of https://github.com/NixOS/nixpkgs/issues/22302

**Comment by matthiasbeyer** [comment]
From what I read in the whole chain of issues - would a reboot fix my problem?

**Comment by matthiasbeyer** [comment]
The issue was fixed for me after a reboot.
