### ISSUE TITLE
Package exhibitor and create a NixOS module for it

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#22327]
We currently have a nice ZooKeper module and package, but apparently all the cool kids run ZK via [Exhibitor](https://github.com/soabase/exhibitor), which we don't have packaged or any module around. Anyone feel like packaging and/or writing a module for it?

cc @nathan-gs @cstrahan @pradeepchhetri who have dealt with ZK

**Comment by pradeepchhetri** [comment]
I would like to own this. Thank you for bringing this up.

**Comment by vcunat** [comment]
Let's assign it to you then &ndash; informally, as GitHub only allows that for organization members (or some similar condition).

**Comment by copumpkin** [comment]
Thanks @pradeepchhetri!

**Comment by puffnfresh** [comment]
@pradeepchhetri is this happening?

**Comment by pradeepchhetri** [comment]
@puffnfresh Sorry for the delay. Yes I am working on this.

**Comment by copumpkin** [comment]
@pradeepchhetri any progress?

**Comment by joelthompson** [comment]
FYI, I took a crack at this in #27508
