### ISSUE TITLE
KDE Plasma Wayland not launching with Mesa 23

### ISSUE THREAD

**Issue by MidAutumnMoon** [NixOS/nixpkgs#223331]
### Describe the bug

Related: https://github.com/NixOS/nixpkgs/pull/217883

### Additional context
CPU: AMD Ryzen 7 4800HS
GPU: (integrated)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.7-zen1, NixOS, 23.05 (Stoat), 23.05.20230326.a0be54d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/k8k2v1mf59d3gw32gbw15213jvag79af-source`
```

**Comment by andrevmatos** [comment]
I'm also experiencing this. Screen just freezes black when launding kde plasma wayland from terminal on my Rembrandt 680M APU.
The workaround for now is to rollback to mesa 22 with `hardware.opengl.mesaPackage = pkgs.mesa_22;`

**Comment by andrevmatos** [comment]
Could this be caused by `kwin_wayland` (and/or wayland or other libs) using `pkgs.mesa` (which is still defaulting to `mesa_22`) as dependency at compile time, but trying to use `mesa_23` at runtime?

**Comment by dacioromero** [comment]
Following Brian's example I made an overlay which was hard to figure out because I didn't want to use a local version nixpkgs.

```nix
final: prev: rec {
  libsForQt5 = prev.libsForQt5.overrideScope' (qt5final: qt5prev:
    let
      plasma5 = qt5prev.plasma5.overrideScope' (pFinal: pPrev: {
        kpipewire = pPrev.kpipewire.override { mesa = prev.mesa_23; };
        kwin = pPrev.kwin.override { mesa = prev.mesa_23; };
        xdg-desktop-portal-kde = pPrev.xdg-desktop-portal-kde.override { mesa = prev.mesa_23; };
      });
    in
    plasma5 // { inherit plasma5; });

  plasma5Packages = libsForQt5;
}
```

It might not be 100% how it should be done, but it got the unstable channel working for me again without rebuilding the world if I simply overrode `mesa` to `mesa_23`.
