### ISSUE TITLE
xclip does not work

### ISSUE THREAD

**Issue by fubarbaz** [NixOS/nixpkgs#22337]
I expect 
```
echo hi| xclip && konsole
```
followed by Control-Shift-v  (default binding to paste something) while the KDE clipboard manager is running to paste hi to the now displayed terminal window. 

Observed result: it pastes whatever was on the clipboard before the command was executed. 

16.09.git.89c567c (Flounder)

Relevant configuration

``` 
services.xserver.desktopManager.kde5.enable = true;
```

**Comment by puffnfresh** [comment]
I think you want `xclip -selection clipboard`.

**Comment by MatthiasvB** [comment]
It does not work for me on current stable KDE Plasma
