### ISSUE TITLE
Confusion about Lebanon DST change in tzdata-2023b

### ISSUE THREAD

**Issue by panicgh** [NixOS/nixpkgs#223323]
### Describe the bug

There is confusion about the recently announced daylight savings time changes in Lebanon. We have the latest tzdata-2023b with the contested DST postponing in staging (#222895) and staging-22.11 (#223223). We should ensure that it does not reach the master/release-22.11 branches until there is clarification from upstream (and Lebanon).

Upstream [recommends](https://mm.icann.org/pipermail/tz/2023-March/032767.html)
> In short: stick with 2023a for now, and tomorrow [Monday, 2023-03-27] let's see.

I'm not sure what exactly to do. Either revert the 2023b commits to prevent them from reaching master/release-22.11, or just make sure staging/staging-22.11 don't get merged into the -next branches as long as the DST situation is unclear.

### Context

tzdata-2023a was [released](https://mm.icann.org/pipermail/tz-announce/2023-March/000077.html) regularly on Wednesday 2023-03-22. On Thursday, the Lebanese government announced that the spring forward planned for midnight between Saturday/Sunday 2023-03-25/26 will be postponed to April. Upstream [released](https://mm.icann.org/pipermail/tz-announce/2023-March/000078.html) 2023b on Friday 2023-03-24 to reflect this change.

However, the decision to delay DST is [contested](https://mm.icann.org/pipermail/tz/2023-March/032752.html) in Lebanon as many institutions (banks, universities, ...) couldn't implement it in time.

### Notify maintainers

@ajs124 @fpletz 

@mweinelt @Mindavi (merged the PRs)

**Comment by panicgh** [comment]
> Neither have made it to staging-next yet

That's why I wrote "just make sure staging/staging-22.11 don't get merged into the -next branches as long as the DST situation is unclear.". At the moment everything is still not bad, but we should e.g. not blindly proceed with the next staging-next cycles today (or the coming days, depending on how long it takes to clarify the DST situation).

> Also, why is this labeled with security?

tzdata is usually released  with elevated priority, since it affects time and how time is displayed. This issue intends to raise awareness and prevent the branches to reach *-next. If you think it is mislabeled, you can of course remove it.

**Comment by mweinelt** [comment]
I do think we should defer to whatever upstream decides.

And in https://mm.icann.org/pipermail/tz/2023-March/032767.html Paul Eggert suggests sticking with 2023a for now, given that the only change in 2023b affects Lebanon and the change is contested.

**Comment by SuperSandro2000** [comment]
Since this seems to be the only change in 2023b, a revert is a good option

https://data.iana.org/time-zones/tzdb/NEWS

**Comment by ajs124** [comment]
Feel free to open a revert referencing the email linked above.
I tried to push one to a branch, but github seems to be having some issues rn:
```
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 12 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 724 bytes | 724.00 KiB/s, done.
Total 7 (delta 6), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: fatal error in commit_refs
To github.com:helsinki-systems/nixpkgs.git
 ! [remote rejected]         dwn/tzdata -> dwn/tzdata (failure)
error: failed to push some refs to 'github.com:helsinki-systems/nixpkgs.git'

**Comment by vcunat** [comment]
(Yes, even commenting often shows errors for me now.)
