### ISSUE TITLE
Wayland crashes gdm (Gnome) on nixos-unstable

### ISSUE THREAD

**Issue by naturallaw777** [NixOS/nixpkgs#223458]
### Describe the bug
If gdm is enabled with Gnome enabled, gdm will crash and not load into the login screen after logout or reboot. This is due to gdm using wayland as the default. Once wayland is disabled in gdm, the login works.

### Steps To Reproduce
1. Using channel nixos-unstable, "sudo nixos-rebuild switch upgrade-all" with Gnome enabled and gdm enabled in configuration.nix.
2. Reboot
3. Reboot will hang at the gdm check point.
4. Disable gdm wayland in configuration.nix and the reboot works but with Wayland not working. 

### Expected behavior
Reboot into gdm with Wayland

### Notify maintainers

@codyopel 

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05pre468261.4361baa782d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(free): `""`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by samhug** [comment]
I just hit the same issue. After updating to latest nixos-unstable, the boot hangs just before login screen
I think this is related to #223331, at least the workaround posted there worked for me also
> The workaround for now is to rollback to mesa 22 with `hardware.opengl.mesaPackage = pkgs.mesa_22;`

**Comment by naturallaw777** [comment]
> I just hit the same issue. After updating to latest nixos-unstable, the boot hangs just before login screen I think this is related to #223331, at least the workaround posted there worked for me also
> 
> > The workaround for now is to rollback to mesa 22 with `hardware.opengl.mesaPackage = pkgs.mesa_22;`

Would #223331 be relevant with a machine without AMD graphics and without KDE? As, I am running Intel's build in graphics and using Gnome. 

Also, I did find a "workaround" by disabling wayland in gdm then nixos-unstable will boot.

```
	services.xserver.displayManager.gdm.enable = true;
	services.xserver.desktopManager.gnome.enable = true;
	services.xserver.displayManager.gdm.wayland = false;
```

**Comment by SamLukeYes** [comment]
I managed to work around this issue with `hardware.opengl.mesaPackage = pkgs.mesa;`

Graphic card: Intel® Xe Graphics (TGL GT2)

**Comment by naturallaw777** [comment]
> I managed to work around this issue with `hardware.opengl.mesaPackage = pkgs.mesa;` on GNOME Wayland.
> 
> Graphic card: Intel® Xe Graphics (TGL GT2)

Totally worked! Thanks @samhug and @SamLukeYes !  

Should I leave this open as this is a bug or a new config that needs to be applied to 23.05?
