### ISSUE TITLE
Build failure: knot-resolver and others: error: cqueues not supported for interpreter lua

### ISSUE THREAD

**Issue by flokli** [NixOS/nixpkgs#223437]
### Steps To Reproduce

1. `nix-build -A knot-resolver`

### Build log

```
❯ nix-build -A knot-resolver
error: cqueues not supported for interpreter lua

```

### Additional context

Bisecting pointed to https://github.com/NixOS/nixpkgs/pull/219846

### Notify maintainers

cc @vcunat

**Comment by vcunat** [comment]
More precisely, it's evaluation-time failure already.  (`throw`)
