### ISSUE TITLE
🦦 NixOS 23.05 — Release Schedule

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#223562]
Hi, we are [Ryan Lahfa](https://github.com/RaitoBezarius) & [Martin Weinelt](https://github.com/mweinelt), the [release managers](https://nixos.github.io/release-wiki/Release-Managers.html) for NixOS 23.05 🦦 ("_Stoat_").

I also have the joy to work with [Lennart](https://lnrt.de/) [Mühlenmeier](https://github.com/riotbib/) and [Winter](https://github.com/winterqt) who will be [release editors](https://nixos.github.io/release-wiki/Release-Editors.html) for this NixOS 🦦 release.

Below you can find the release calendar for the next two months running up to the planned release at the end of May 2023. If something feels unclear to you, don't hesitate to reach out, we are here to guide the process and make sure this will be a satisfying release for all of us.

Stay tuned for updates!

<table>
    <tr>
        <td></td>
        <td>Date</td>
        <td>Affects</td>
        <td>Events</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-04-03</td>
        <td>—</td>
        <td>Start <a href="https://github.com/NixOS/nixpkgs/issues/224457">discussion</a> about "Feature Freeze & Release Blockers" with ecosystem maintainers</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-04-17</td>
        <td>all branches</td>
        <td>Restrict breaking changes to <a href="https://nixos.github.io/release-wiki/Release-Critical-Packages.html">Release Critical Packages</a></td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-05-01</td>
        <td>all branches</td>
        <td>Restrict all breaking changes with the exception of desktop environments</td>
    </tr>
    <tr>
        <td rowspan="2">:heavy_check_mark:</td>
        <td rowspan="2">2023-05-08</td>
        <td><tt>master</tt></td>
        <td>Wait for <tt>staging-next</tt> merge into <tt>master</tt>; begin first <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Begin Zero Hydra Failures campaign</td>
    </tr>
    <tr>
        <td rowspan="2">:heavy_check_mark:</td>
        <td rowspan="2">2023-05-15</td>
        <td><tt>master</tt></td>
        <td>Wait for first <tt>staging-next</tt> merge into <tt>master</tt>; begin second <tt>staging-next</tt> cycle</td>
    </tr>
    <tr>
        <td><tt>staging</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td rowspan="8">:heavy_check_mark:</td>
        <td rowspan="8">2023-05-22</td>
        <td><tt>master</tt></td>
        <td>Wait for second <tt>staging-next</tt> merge into <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>staging-next</tt></td>
        <td>Unrestrict all breaking changes; new changes will not be present in the release</td>
    </tr>
    <tr>
        <td><tt>master</tt></td>
        <td>Mark failing packages as broken</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.05</tt></td>
        <td>Branch-off</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.05</tt></td>
        <td>Tag <tt>23.05-beta</tt> on <tt>release-23.05</tt><br /> and <tt>23.05-unstable</tt> on <tt>master</tt></td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.05</tt></td>
        <td>Create release channels</td>
    </tr>
    <tr>
        <td><tt>master</tt>, <tt>release-23.05</tt></td>
        <td>ZHF fixes go into <tt>master</tt> and need to be backported to <tt>release-23.05</tt></td>
    </tr>
    <tr>
        <td><tt>release-23.05</tt></td>
        <td>Prepare for release, finish remaining issues</td>
    </tr>
    <tr>
        <td>:heavy_check_mark:</td>
        <td>2023-05-31</td>
        <td><tt>release-23.05</tt></td>
        <td>Release! Also, ZHF ends</td>
    </tr>
    <tr>
        <td></td>
        <td>2022-06-10</td>
        <td>—</td>
        <td>Release Retrospective, everyone is invited to give feedback!</td>
    </tr>
</table>

---

## Definitions

- Backport
    - Cherry-picking a change from `master` into `release-23.05`
    - Use the backport action by applying the `backport: release-23.05` tag
- Breaking change
    - A change that is likely to break downstream consumers
- Ecosystem maintainers
    - Maintainer teams that have enabled `enableFeatureFreezePing`  in [`maintainers/team-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix)
- [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html)
    - List of packages that usually cause widespread breakages
- Restriction
    - Changes of the mentioned kind cannot be merged while the restriction is active
- ZHF
    - Zero Hydra Failures
    - Period in which contributors focus on stabilizing packages
    - Usually through PRs targeted at the `master` branch

**Comment by mweinelt** [comment]
Breaking changes are now restricted, with the exception of desktop environments, to guarantee their stabilization can take place.

**Comment by RaitoBezarius** [comment]
NixOS 23.05 has been completely released: https://discourse.nixos.org/t/nixos-23-05-released/28649 !
