### ISSUE TITLE
Build failure: mastodon

### ISSUE THREAD

**Issue by chvp** [NixOS/nixpkgs#223534]
### Steps To Reproduce

1. build mastodon

### Build log

https://hydra.nixos.org/log/xx1wqfjx6avcwc70xinxz2712s6h3k1s-mastodon-modules-4.1.1.drv

### Additional context

One of the dependencies of mastodon isn't built correctly since https://github.com/NixOS/nixpkgs/pull/218114 (more specifically, the rubygems bump included in that PR). See https://github.com/Gargron/blurhash/pull/19 for more context. It was fixed in version 0.1.7 of the blurhash gem, but the current mastodon version still uses 0.1.6.

### Notify maintainers

@marsam @ghuntley @Izorkin @erictapen

**Comment by chvp** [comment]
I added an ugly fix to my personal config, but it feels too ugly to upstream: https://github.com/chvp/nixos-config/blob/main/patches/mastodon.patch

**Comment by IndeedNotJames** [comment]
#223547 has been merged and https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.mastodon.x86_64-linux builds again
E.g. https://hydra.nixos.org/build/214487941
