### ISSUE TITLE
Pleroma 2.5.1 crashes at startup

### ISSUE THREAD

**Issue by Elinvention** [NixOS/nixpkgs#223518]
### Describe the bug
I upgraded Pleroma to 2.5.1, but it stopped working after the update. It crashes at startup with this `reason: {on_load_function_failed,crypt, {error,{load,"Library load-call unsuccessful (1)."}}}`. This might have to to do with the fact that I'm installing pleroma from unstable, from NixOS 22.11.

### Steps To Reproduce
1. This is my pleroma config:
```nix
let
  unstable = import
    (builtins.fetchTarball https://github.com/nixos/nixpkgs/tarball/nixos-unstable)
    # reuse the current configuration
    { config = config.nixpkgs.config; };
in
pleroma = {
  enable = true;
  secretConfigFile = "/var/lib/pleroma/secrets.exs";
  package = unstable.pleroma;
  configs = [ "omitted" ];
}
```
2. Start pleroma
3. Crash

### Screenshots
```
Starting Pleroma social network...
22:44:44.553 [info] Migrations already up
Started Pleroma social network.
=SUPERVISOR REPORT==== 27-Mar-2023::22:44:49.581114 ===
    supervisor: {local,kernel_sup}
    errorContext: start_error
    reason: {on_load_function_failed,crypt,
                {error,{load,"Library load-call unsuccessful (1)."}}}
    offender: [{pid,undefined},
               {id,kernel_safe_sup},
               {mfargs,{supervisor,start_link,
                                   [{local,kernel_safe_sup},kernel,safe]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,infinity},
               {child_type,supervisor}]

=CRASH REPORT==== 27-Mar-2023::22:44:49.584357 ===
  crasher:
    initial call: supervisor:kernel/1
    pid: <0.3549.0>
    registered_name: []
    exception exit: {on_load_function_failed,crypt,
                        {error,{load,"Library load-call unsuccessful (1)."}}}
      in function  init:run_on_load_handlers/0
      in call from kernel:init/1 (kernel.erl, line 196)
      in call from supervisor:init/1 (supervisor.erl, line 330)
      in call from gen_server:init_it/2 (gen_server.erl, line 851)
      in call from gen_server:init_it/6 (gen_server.erl, line 814)
    ancestors: [kernel_sup,<0.3522.0>]
    message_queue_len: 0
    messages: []
    links: [<0.3524.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 199
  neighbours:

=CRASH REPORT==== 27-Mar-2023::22:44:50.587986 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.3521.0>
    registered_name: []
    exception exit: {{shutdown,
                      {failed_to_start_child,kernel_safe_sup,
                       {on_load_function_failed,crypt,
                        {error,
                         {load,"Library load-call unsuccessful (1)."}}}}},
                     {kernel,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 142)
    ancestors: [<0.3520.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.3522.0>,normal}]
    links: [<0.3520.0>,<0.3519.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 166
  neighbours:

=INFO REPORT==== 27-Mar-2023::22:44:50.592733 ===
    application: kernel
    exited: {{shutdown,
                 {failed_to_start_child,kernel_safe_sup,
                     {on_load_function_failed,crypt,
                         {error,
                             {load,"Library load-call unsuccessful (1)."}}}}},
             {kernel,start,[normal,[]]}}
    type: permanent

{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_su>
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup>

Crash dump is being written to: erl_crash.dump...done
pleroma.service: Main process exited, code=exited, status=1/FAILURE
pleroma.service: Failed with result 'exit-code'.
pleroma.service: Consumed 10.715s CPU time, received 564B IP traffic, sent 564B IP traffic.
```

### Notify maintainers

@NinjaTrappeur @petabyteboy @yu-re-ka 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.103-hardened1, NixOS, 22.11 (Raccoon), 22.11.3339.da26ae9f6ce`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by NinjaTrappeur** [comment]
I'm a bit confused by that one, there's likely a weird interaction happening between libxcrypt and your host system, but I can't pinpoint it.

The error message seems to point to something related with the [crypt](https://github.com/msantos/crypt) 1.0.0 -> 1.0.1 bump in https://github.com/NixOS/nixpkgs/pull/219304.

Libxcrypt seem to ship a different crypt ABI on NixOS-21.11 and NixOS-unstable: 1.1.0 for 11.11, 2.0.0 for unstable:

```
~/code-root/github.com/NixOS/nixpkgs (master*) » ll $(nix-build -A libxcrypt)/lib                                     ninjatrappeur@trantor
these 4 paths will be fetched (6.74 MiB download, 30.97 MiB unpacked):
  /nix/store/0bxlqaklbcjy1cn5xw03jd5kxn39jn0l-libxcrypt-4.4.33
  /nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224
  /nix/store/cnjwrrhnqn114jf5x0dwhx3jiaw6600d-libunistring-1.1
  /nix/store/dh0jscni558i609q1s299qlrdbdj9jxa-libidn2-2.3.2
copying path '/nix/store/cnjwrrhnqn114jf5x0dwhx3jiaw6600d-libunistring-1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/dh0jscni558i609q1s299qlrdbdj9jxa-libidn2-2.3.2' from 'https://cache.nixos.org'...
copying path '/nix/store/8xk4yl1r3n6kbyn05qhan7nbag7npymx-glibc-2.35-224' from 'https://cache.nixos.org'...
copying path '/nix/store/0bxlqaklbcjy1cn5xw03jd5kxn39jn0l-libxcrypt-4.4.33' from 'https://cache.nixos.org'...
total 124
-r-xr-xr-x 1 root root    963  1 janv.  1970 libcrypt.la
lrwxrwxrwx 1 root root     17  1 janv.  1970 libcrypt.so -> libcrypt.so.2.0.0
lrwxrwxrwx 1 root root     17  1 janv.  1970 libcrypt.so.2 -> libcrypt.so.2.0.0
-r-xr-xr-x 1 root root 116256  1 janv.  1970 libcrypt.so.2.0.0
dr-xr-xr-x 2 root root   4096  1 janv.  1970 pkgconfig
--------------------------------------------------------------------------------------------------------------------------------------------
~/code-root/github.com/NixOS/nixpkgs (master*) » git checkout nixos-21.11                                       130 ↵ ninjatrappeur@trantor
Mise à jour des fichiers: 100% (29218/29218), fait.
Basculement sur la branche 'nixos-21.11'
Votre branche est à jour avec 'origin/nixos-21.11'.
--------------------------------------------------------------------------------------------------------------------------------------------
~/code-root/github.com/NixOS/nixpkgs (nixos-21.11*) » ll $(nix-build -A libxcrypt)/lib                                ninjatrappeur@trantor
total 220
-r-xr-xr-x 1 root root    963  1 janv.  1970 libcrypt.la
lrwxrwxrwx 1 root root     17  1 janv.  1970 libcrypt.so -> libcrypt.so.1.1.0
lrwxrwxrwx 1 root root     17  1 janv.  1970 libcrypt.so.1 -> libcrypt.so.1.1.0
-r-xr-xr-x 1 root root 215104  1 janv.  1970 libcrypt.so.1.1.0
lrwxrwxrwx 1 root root     11  1 janv.  1970 libowcrypt.so -> libcrypt.so
lrwxrwxrwx 1 root root     13  1 janv.  1970 libowcrypt.so.1 -> libcrypt.so.1
lrwxrwxrwx 1 root root     11  1 janv.  1970 libxcrypt.so -> libcrypt.so
dr-xr-xr-x 2 root root   4096  1 janv.  1970 pkgconfig
```

My assumption here would be that libcrypto is somehow "leaking" somewhere through the NixOS closure and is in conflicts with the pleroma-provided one.

I'm not 100% sure about that. I'm gonna try to find somebody more knowledgeable around this libcrypto area to help.

**Comment by NinjaTrappeur** [comment]
Mic92's suggestion: could you set `LD_DEBUG=libs` to figure out which libcrypt is loaded?

EG:

```nix
systemd.services.pleroma.environment.LD_DEBUG = "libs"
```

**Comment by NinjaTrappeur** [comment]
It seems like the right libcrypt gets loaded (the one coming from unstable). I'm not sure what's happening here, sorry.

I guess your best bet might be looking at the Elixir/OTP docs and see if there's a way to make this DSO loader more chatty.

Maybe strac-ing the process might show what the OTP is exactly trying to do before crashing.

**Comment by Elinvention** [comment]
Since my server runs with `kernel.yama.ptrace_scope = 3`, I tried with nix-shell on my desktop and I can reproduce the issue here too. I attach the result of `env RELEASE_COOKIE=/var/lib/pleroma/.cookie strace -o pleroma.strace pleroma start` [pleroma.txt](https://github.com/NixOS/nixpkgs/files/11091078/pleroma.txt). I can't see anything wrong... thank you anyway.

**Comment by Atemu** [comment]
Note that this isn't really a supported config. Using packages from unstable in an otherwise stable system can work but sometimes you run into errors like this.

Unless you can reproduce this issue within a single channel, this isn't really something we can act on.

Best ask about this sort of thing in Discourse or Matrix.

**Comment by NinjaTrappeur** [comment]
@Elinvention the OTP spins up several processes at startup, that's probably why we don't see any libcrypt-related reads.

Can you add the `-f` (follow-forks) flag to your strace call to attach strace to the child processes and see if we get further informations?

**Comment by NinjaTrappeur** [comment]
@Atemu I'd like to at least understand the issue here before closing it as wontfix.

**Comment by leon-barrett** [comment]
I can reproduce this on a single channel. I am on unstable (https://nixos.org/channels/nixos-unstable), and my Pleroma fails with the same error.

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05pre468444.4bb072f0a8b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Here are my Pleroma logs: [pleroma-log.txt](https://github.com/NixOS/nixpkgs/files/11104769/pleroma-log.txt)

I have not run strace, as I'm not quite as advanced, and I don't know how to debug erlang. If it would be helpful, I can try to get specific debugging information when I have free time.

**Comment by NinjaTrappeur** [comment]
Mystery solved :tada:

4e300e071b97e1e3a6ba4d856cc65e5386366f6f is the culprit. It's been merged part of the [last staging-next](https://github.com/NixOS/nixpkgs/pull/221461) run.

Pleroma is definitely broken on unstable. I was lagging 3 days behind and failed to detect that. The NixOS VM test broke though, yet another instance where it'd have been nice to have a notification from hydra :/

We're lucky upstream decided to drop cyrpt at the same time, the two issues were unrelated in the end.

Let's wait for upstream response and act accordingly.

@mweinelt, FYI, we might have some other subtle breakages resulting from 4e300e071b97e1e3a6ba4d856cc65e5386366f6f.

**Comment by Elinvention** [comment]
@NinjaTrappeur thanks for your continued bug hunting. I confirm that pinning to that commit gave me back a working Pleroma 2.5.1. Thanks again.

**Comment by NinjaTrappeur** [comment]
@Elinvention @leon-barrett : I pushed a temporary fix on master. You can track when it'll reach the nixos-unstable channel there: https://nixpk.gs/pr-tracker.html?pr=223904
