### ISSUE TITLE
linuxKernel.packages.linux_6_1.zfs: unreproducible kernel modules

### ISSUE THREAD

**Issue by raboof** [NixOS/nixpkgs#223584]
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A linuxKernel.packages.linux_6_1.zfs --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A linuxKernel.packages.linux_6_1.zfs)
```

### Additional context

There seem to be different symbols included - perhaps some architecture/feature sniffing leaking through?

**Comment by RaitoBezarius** [comment]
Please do not hesitate to assign me or ping me (as I am maintainer of ZFS now. True for any package which I am maintainer of which is not reproducible.)

**Comment by K900** [comment]
Prior art: 
https://github.com/NixOS/nixpkgs/issues/220662
https://github.com/NixOS/nixpkgs/pull/181456

**Comment by delroth** [comment]
I have what I think is a fix in #231768. Please let me know if you still encounter unreproducibility with this patch applied -- in my (limited) testing this issue is fixed.

**Comment by K900** [comment]
Have we verified this works for everything and not just zfs?

**Comment by RaitoBezarius** [comment]
I think it was a generic pahole patch for BTF generation, but this issue is about ZFS anyway, there's other issues for the general kernel unreproducibility.
