### ISSUE TITLE
Documentation: Missing `op-vscode` VSCode extension package on Nixos search

### ISSUE THREAD

**Issue by francishamel** [NixOS/nixpkgs#223646]
## Problem

This [Nixos search query](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=op-vscode) using the `22.11` channel clearly lists the `vscode-extensions._1Password.op-vscode` package. When [querying](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=op-vscode) using the `unstable` channel, the package is not listed anymore.

It looks like it was renamed in https://github.com/NixOS/nixpkgs/commit/ec9655c09b4b41a6952b6ac9265a06aed71c9876 so maybe this could be the root cause of the issue.

## Checklist

- [x] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

**Comment by francishamel** [comment]
@schuelermine I think you were the one who committed this change so I'm tagging you. (Sorry if that's not the proper etiquette for this repo, first time opening an issue in nixpkgs).

**Comment by superherointj** [comment]
I don't think there is a problem here. If package was renamed the search won't find it anymore in forward versions. That's expected.

**Comment by schuelermine** [comment]
@superherointj It seems to me that the package isn't listed at all, even though the extension name was unchanged (and that's the part being searched for). So it seems like the search interface can't deal with attribute names that require quoting.

**Comment by superherointj** [comment]
> @superherointj It seems to me that the package isn't listed at all, even though the extension name was unchanged (and that's the part being searched for). So it seems like the search interface can't deal with attribute names that require quoting.

I don't know the right solution then.
1) Re-open this issue?
2) Open new issue for that?
3) Rename extensions?

I'm not particularly interested in this problem since I have other priority issues to deal with. But feel free to proceed as you wish.
