### ISSUE TITLE
mpd 0.20 has a crashing bug - 0.20.4 has the fix.

### ISSUE THREAD

**Issue by lakshmivyas** [NixOS/nixpkgs#22368]
## Issue description

MPD 0.20 crashes with error:

```
mpd: src/filter/plugins/ChainFilterPlugin.cxx:58: void ChainFilter::Append(const char*, Filter*): Assertion `out_audio_format.IsValid()' failed.
```

### Steps to reproduce

1. Ensure mpd server is running
2. Try to play using any method
3. mpd crashes

See: 
https://bugs.musicpd.org/view.php?id=4618

## Technical details

* System: NixOS: 16.09
* Nix version: 1.11.6
* Nixpkgs version: 17.03pre99759.f66d782

**Comment by Mic92** [comment]
Want to make a pull request? We can also back port the fix to stable.

**Comment by lakshmivyas** [comment]
@fpletz: Thank you.  @Mic92: Will do a PR next time around.  :+1:
