### ISSUE TITLE
ungoogled-chromium: reader mode (opt-in, `chrome://flags`) is missing "Material Icons"  

### ISSUE THREAD

**Issue by eyome** [NixOS/nixpkgs#223796]
When I use reader mode of Ungoogled Chromium, I can't set the font, background...
The button to set it is not visible as it comes from "Material Design Icons".
Please, refer to [this bug](https://github.com/ungoogled-software/ungoogled-chromium/issues/1525).
I tried with flatpak and indeed, I can see this icon.

**Comment by eyome** [comment]
(To activate reader mode, go to chrome://flags/ and search "reader mode")

**Comment by emilylange** [comment]
Given this is an experimental feature flag (which also seems to be somewhat deprecated now), we don't have any plans to add the fonts to the `ungoogled-chromium` wrapper.

You can, however, fix this by on your system locally, by simply adding `material-icons` (not `material-design-icons`) to your `fonts.packages` like so:

```nix
fonts.packages = with pkgs; [
  material-icons
];
```
