### ISSUE TITLE
nixos/k3s: `exec: "k3s-server": cannot run executable found relative to current directory` with k3s_1_26

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixpkgs#223766]
### Describe the bug

```nix
{
    package = pkgs.k3s_1_26; # err
    package = pkgs.k3s_1_25; # ok
}
```

### Additional context

```
mar 29 11:41:13 vps systemd[1]: Starting k3s service...
mar 29 11:41:13 vps k3s[76752]: time="2023-03-29T11:41:13-04:00" level=fatal msg="exec: \"k3s-server\": cannot run executable found relative to current directory"
```

Maybe related to the k3s changes referred in https://github.com/NixOS/nixpkgs/commit/c7132173806

### Notify maintainers

@asonix maybe

### Metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05pre468444.4bb072f0a8b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos, nixos-unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by asonix** [comment]
On first look - this doesn't seem related to the environmentFile change, but can you post more about your k3s configuration?

**Comment by asonix** [comment]
also pinging @superherointj

**Comment by bbigras** [comment]
my config:

```nix
{
  services.k3s = {
    enable = true;
    package = pkgs.k3s_1_25;
    role = "server";
    extraFlags = toString [
      "--kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%"
      "--kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%"
      "-disable=traefik"
    ];
  };

  # https://github.com/NixOS/nixpkgs/issues/103158
  systemd.services.k3s.after = [ "network-online.service" "firewall.service" ];
  systemd.services.k3s.serviceConfig.KillMode = lib.mkForce "control-group";
}
```

**Comment by superherointj** [comment]
I could not reproduce this issue.
- Needs more information.
- Suggest you simplify your configuration.
- Consider bisecting.
- Running same configuration in a new host.
- Cleaning-up past state:
  * backup first (will lose data).
  * As root:
  * systemctl stop k3s
  * umount kubelet
    - KUBELET_PATH=$(mount | grep kubelet | cut -d' ' -f3); \
      ${KUBELET_PATH:+umount $KUBELET_PATH}; sleep 1
  * delete k3s data
    - rm -rf /etc/rancher/{k3s,node}; \
      rm -rf /var/lib/rancher/k3s/; \
      rm -rf /var/lib/kubelet

**Comment by superherointj** [comment]
Btw, your fix is wrong. `network-online.service` => `network-online.target`
And that won't be necessary anymore: #223823

**Comment by bbigras** [comment]
I was able to reproduce using nixos/tests/k3s/single-node.nix.

`"-disable=traefik"` is wrong.

`"--disable=traefik"` or `"--disable" "traefik"` are OK.

so, sorry for the noise. and thank you very much for the quick replies.

and if you are on a bug killing spree, I also have this in my config:

```nix
{
  # https://github.com/NixOS/nixpkgs/issues/98766
  boot.kernelModules = [ "br_netfilter" "ip_conntrack" "ip_vs" "ip_vs_rr" "ip_vs_wrr" "ip_vs_sh" "overlay" ];
  networking.firewall.extraCommands = ''
    iptables -A INPUT -i cni+ -j ACCEPT
  '';
}
```
