### ISSUE TITLE
haskell.lib.buildStackProject: regression on OS X

### ISSUE THREAD

**Issue by mboes** [NixOS/nixpkgs#22386]
## Issue description

With the latest nixpkgs, haskell.lib.buildStackProject is unusable on OS X. Commit f4e67389ccf51c0d3a240f571724516ea9608926 added a reference to `cacert`, but such a variable does not seem to exist when targetting Darwin.

### Steps to reproduce

Create a `shell.nix`:

```
with (import <nixpkgs> {});
haskell.lib.buildStackProject {
  name = "foo";
  ghc = haskell.compiler.ghc802;
}
```

```
$ nix-shell
error: undefined variable ‘cacert’ at /nix/store/5v7r2jis6b0avlj5kkfmvgzaw6z8cyw0-nixpkgs-17.03pre99971.05ee547/nixpkgs/pkgs/development/haskell-modules/generic-stack-builder.nix:31:23
```

## Technical details

* System: OS X 10.10.5
* Nix version: 1.11.6

cc @domenkozar

**Comment by domenkozar** [comment]
I'm embarrassed. Thanks for the issue :)
