### ISSUE TITLE
Xmonad: Cannot use xmonad-contrib on NixOS.

### ISSUE THREAD

**Issue by aatxe** [NixOS/nixpkgs#22381]
## Issue description

I've tried setting up Xmonad on NixOS 16.09 using xmonad-contrib. However, I am unable to get it to compile anything using xmonad-contrib libraries (say `import XMonad.Hooks.ManageDocks`). The compilation always fails saying that the import couldn't be found, which seems like it's unable to find xmonad-contrib for whatever reason. I imagine I'm just missing something here (because it seems many other people have this working), but I can't find any resources about what might be wrong here. In addition to the configuration, I've tried to install `xmonad-contrib` separately with `nix-env` to no avail.

### Steps to reproduce

The relevant portion of my configuration file looks like:
```
  services.xserver.windowManager.xmonad = {
    enable = true;
    enableContribAndExtras = true;
    extraPackages = haskellPackages: with haskellPackages; [
      haskellPackages.xmonad-contrib
      haskellPackages.xmonad-extras
    ];
  }
```

**Comment by puffnfresh** [comment]
Doing `enableContribAndExtras` should be enough - you don't need the explicit `extraPackages` configuration.

**Comment by abbradar** [comment]
Anyway, this should work (even with duplication of contrib/extras with option); at least it works for me. No instant idea what goes wrong; try cleaning `~/.xmonad` maybe (from object files and such? Shouldn't be needed but who knows...

**Comment by aatxe** [comment]
Ah, strangely enough, @abbradar's suggestion fixed it. Thanks!

**Comment by aatxe** [comment]
I seem to have spoken too soon. While it worked once, upon reboot, the changes did not persist (I added avoidStruts because of xmobar) and it once again fails to compile, unable to find the import, when I do Meta-Q.

**Comment by blargg** [comment]
Saw a similar issue, #23545. Basically, if you have xmonad pulled in by another package, it may cause this. Removing xmonad from environment.systemPackages fixed the issue in my case. Let us know if this is the cause of your case. I'm curious why this is, and if we can either fix the problem or give an error message.

**Comment by praduca** [comment]
i can confirm that this happens if you had installed xmonad-with-packages via command line (nix-env or nox utlities). Also, when (by mistake) i invoked xmonad from command line after doing a succesfull recompilation via mod-q, i got the folowing error message:

```
XMonad is recompiling and replacing itself another XMonad process because the current process is called "xmonad" but the compiled configuration should be called "xmonad-x86_64-linux"
XMonad will use ghc to recompile, because "/home/flavio/.xmonad/build" does not exist.
XMonad skipping recompile because it is not forced (e.g. via --recompile), and neither xmonad.hs nor any *.hs / *.lhs / *.hsc files in lib/ have been changed.
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  7
  Current serial number in output stream:  8

```
Don't think the error is especially useful, except the part that says that a _build_ folder was not found. 

Anyway,  I saw in the past people complaining of strange behavior if you get the same package installed globally (via environment.system.packages) and at user space, so this is maybe a bit more deep than only with xmonad...

**Comment by cdepillabout** [comment]
I'm going to go ahead and close this, since `xmonad-contrib` is definitely working in NixOS now.
