### ISSUE TITLE
Xmonad: Fix ManageDocks bug

### ISSUE THREAD

**Issue by k0001** [NixOS/nixpkgs#22380]
## Issue description

This bug is present in the current version of Xmonad we ship:
  
https://wiki.haskell.org/Xmonad/Notable_changes_since_0.11#.2AURGENT.2A_Bug_in_0.12_ManageDocks

We should try and update the Xmonad version we install by default to include a fix for this bug, otherwise the out-of-the-box Xmonad user experience is frustrating.

**Comment by srhb** [comment]
XMonad 0.13 is shipped since 5d3bb96f622 -- does that close this issue?

**Comment by k0001** [comment]
The newer xmonad 0.13 is not even working for me:

```
k@z0 ~ 1 % xmonad --version  
xmonad 0.13
k@z0 ~ 0 % xmonad --recompile
xmonad: ghc: runProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by k0001** [comment]
My bad. I forgot to add our patch to the upstream `xmonad` distribution. It's working now, though not in 16.09. Maybe we should backport this new version of `xmonad` `xmonad-contrib` (and presumably, `xmonad-extras`) to 16.09?  The only Haskell dependency that I had to update was `X11`.

**Comment by vcunat** [comment]
I'm not sure it would qualify as non-intrusive bugfix-only update.

**Comment by ocharles** [comment]
I think the best we can do is add `xmonad_0_13_0` to the set of Haskell packages, then let people override `xmonadPackages` (or whatever it's called) to have this be the default version. In the next stable release, we can bump the default version to be 0.13.

**Comment by k0001** [comment]
@ocharles I like that compromise. I'll try and come up with a patch in the next few days.

**Comment by ocharles** [comment]
Is this still relevant now that 17.09 is out?

**Comment by vcunat** [comment]
release 17.03 has xmonad 0.13 (only).  Any older nixpkgs is certainly unsupported.
