### ISSUE TITLE
Update request: kubernetes-helmPlugins.helm-secrets 4.2.2 → 4.4.2

### ISSUE THREAD

**Issue by brianmay** [NixOS/nixpkgs#223980]
- Package name: kubernetes-helmPlugins.helm-secrets
- Latest released version: 4.4.2

- Current version on the unstable channel: 4.2.2
- Current version on the stable/release channel: not found

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@yurrriq

Tested update to https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/cluster/helm/plugins/helm-secrets.nix#L3-L12:

```nix
stdenv.mkDerivation rec {
  pname = "helm-secrets";
  version = "4.4.2";

  src = fetchFromGitHub {
    owner = "jkroepke";
    repo = pname;
    rev = "v${version}";
    hash = "sha256-GpPgjRqzH4fcnaHs9SWfdaCZimwBleXnxQLjqy8SArs=";
  };
...
}
```

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by yurrriq** [comment]
Resolved by #225538
