### ISSUE TITLE
Build failure: mailutils

### ISSUE THREAD

**Issue by NetaliDev** [NixOS/nixpkgs#223967]
### Steps To Reproduce

1. build `mailutils`

### Build log

https://pastebin.com/U5NEUP6k

### Notify maintainers

@orivej @vrthra

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[netali@satsuki:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05pre469092.9a6aabc4740`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by wentasah** [comment]
4e300e071b97e1e3a6ba4d856cc65e5386366f6f is the first bad commit. It makes sense that password checks in the test suite stop working after this change.

**Comment by orivej** [comment]
/cc @SFrijters

I think I'd opt for building mailutils with libxcrypt-legacy for compatibility, rather than disabling tests, but I'm not sure.

**Comment by SFrijters** [comment]
Maybe we can have our (non-legacy) cake and eat it too https://github.com/NixOS/nixpkgs/pull/224194 .
