### ISSUE TITLE
XFCE desktop slow start with various window managers

### ISSUE THREAD

**Issue by nat-418** [NixOS/nixpkgs#223982]
### Description
When using certain window managers like bspwm and fvwm, xfdesktop and xfce4-panel are slow to start on login.

### Steps To Reproduce
1. Enable XFCE desktop
2. Enable bspwm window manager
3. Log in with xfce+bspwm session

### Expected behavior
XFCE panel and desktop should start immediately. 

### Additional context
I have fixed this problem by disabling the enableDesktop option and manually installing xfce.xfdesktop and xfce.xfce4-panel. I then execute them with the --disable-wm-check flag and everything works normally.

*Adding the above flag resolves this issue* when using non-xfwm window managers. I just don't know how to modify the option code and make a PR to do it myself. If that flag could be added to the xfdesktop and panel start when a non-xfwm window manager session is launched, it would fix this bug. 

### Notify maintainers
@teams.xfce.members: @romildo @muscaln

**Comment by tom8347** [comment]
I'm having the exact same issue.  What exactly did you do for your workaround?  If I don't enable the xfce desktop and instead just download the panel and desktop manager, then launch them from a bare none+bspwm session (for example starting them from the bspwmrc) then the panel is broken - unable to add items and changes to settings don't persist after reboot etc.

**Comment by nat-418** [comment]
> I'm having the exact same issue. What exactly did you do for your workaround? If I don't enable the xfce desktop and instead just download the panel and desktop manager, then launch them from a bare none+bspwm session (for example starting them from the bspwmrc) then the panel is broken - unable to add items and changes to settings don't persist after reboot etc.

I put these lines at the end of my `bspwmrc` :
```
xfce4-panel --disable-wm-check
xfdesktop --disable-wm-check
```
