### ISSUE TITLE
Package request: reorder_python_imports

### ISSUE THREAD

**Issue by csjab** [NixOS/nixpkgs#223937]
**Project description**

Tool for automatically reordering python imports. Similar to isort but uses static analysis more.

**Metadata**

* homepage URL: https://github.com/asottile/reorder_python_imports
* source URL: https://github.com/asottile/reorder_python_imports
* license: mit
* platforms: anywhere Python runs (unix, linux, darwin, ...)

**Comment by thornycrackers** [comment]
This is already packaged https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/reorder-python-imports/default.nix

**Comment by csjab** [comment]
Sorry I missed that! I searched for "reorder_python_imports" (which is the name of the corresponding Python module) before opening this, for which there are currently [no results](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=reorder_python_imports). Do you happen to know if there is a separate ticket more generally tracking improving the search results for situations like this?

Closing this ticket in any case. Thanks for the pointer!

**Comment by thornycrackers** [comment]
No worries! I also missed it until I did some grepping. It’s an unfortunate side effect of how the package was named. [This search](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=reorder-python-imports) yields results but it is not intuitive. I don’t think there’s a corresponding ticket to track these kinds of issues

**Comment by csjab** [comment]
Thanks! Just filed https://github.com/NixOS/nixpkgs/issues/224734 to track improving the search quality for queries like this.
