### ISSUE TITLE
albatross: exec: java: not found

### ISSUE THREAD

**Issue by nomeata** [NixOS/nixpkgs#223923]
### Describe the bug

The TeXlive distribution comes with a tool called [`albatross`](https://gitlab.com/islandoftex/albatross), but it requires Java and does not build out of the box.

### Steps To Reproduce
1. Install texlive (I have `unstable.texlive.combined.scheme-full` in my `systemPackages`)
2. Run `albatross`

It prints 
```
~ $ albatross
/nix/store/2xdwjvk1v0k52avjx04ywpqzq2afyifa-texlive-albatross-0.4.0/scripts/albatross/albatross.sh: line 17: exec: java: not found
```

### Expected behavior

The tool should start :-)

### Additional context

I tried to run it in `nix-shell -p jdk`, but now I got

```
~ $ nix-shell -p jdk
~ $ albatross
Error: Unable to access jarfile
```

### Notify maintainers

Maybe @veprbl @lovek323 @raskin @jwiegley

### Metadata

```console
~ $ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.8, NixOS, 22.11 (Raccoon), 22.11.20230127.cc4bb87`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `""`
 - channels(jojo): `""`
 - nixpkgs: `/etc/nixpkgs/channels/nixpkgs`
```

**Comment by apfelkuchen6** [comment]
It doesn't work with java in PATH because their `albatross.sh` wrapper script assumes that it's called `albatross` when building the jar name.

The obvious solutions would be to either build our own wrapper in `combine.nix` or add an entry to `bin.nix`, with the latter probably being preferable. Something like
```nix
albatross = stdenv.mkDerivation rec {     
  pname = "albatross";     
  inherit (src) version;     
     
  src = lib.head (builtins.filter (p: p.tlType == "run") texlive.albatross.pkgs);     
     
  dontBuild = true;     
  doCheck = false;     
     
  passAsFile = [ "wrapperScript" ];     
  wrapperScript = ''     
   #!${runtimeShell}     
   exec ${jdk}/bin/java -jar $out/bin/.albatross-unwrapped.jar $@     
  '';     
     
  installPhase = ''     
    runHook preInstall     
     
    mkdir -p $out/bin     
    cp scripts/albatross/albatross.jar $out/bin/.albatross-unwrapped.jar     
    sed "s|\$out|$out|" $wrapperScriptPath > $out/bin/albatross     
    chmod +x $out/bin/albatross     
     
    runHook postInstall     
  '';     
     
  meta = with lib; {     
    description = "command line tool for finding fonts that contain a given (Unicode) glyph.";     
    homepage    = "https://ctan.org/pkg/albatross";     
    license     = licenses.bsd3;     
    sourceProvenance = with sourceTypes; [ binaryBytecode ];     
    maintainers = with maintainers; [ ];     
    platforms   = platforms.all;     
  };     
};  
```
works, but since the source is also distributed via tlnet (`  src = lib.head (builtins.filter (p: p.tlType == "run") texlive.albatross.pkgs); `), we also could (should?) build it from source.
