### ISSUE TITLE
Update Opera to Eliminate Transparency Errors

### ISSUE THREAD

**Issue by polynomial** [NixOS/nixpkgs#22390]
## Issue description

The current version of Opera in the tree throws security warnings because it is out of date

### Steps to reproduce

Install opera, try to use a secure site that requires transparency, i.e. slack, amazon.

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
16.09.1616.59d1d6e
* Nix version: (run `nix-env --version`)
1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
16.09.1616.59d1d6e

**Comment by joachifm** [comment]
The update has been merged.
