### ISSUE TITLE
Update request: pnpm v7.29.1 → v8.1.0

### ISSUE THREAD

**Issue by moba1** [NixOS/nixpkgs#224011]
- Package name: pnpm
- Latest released version: 8.1.0
- Current version on the unstable channel: 7.29.1
- Current version on the stable/release channel: v7.14.
- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@tjni

**Comment by nickgerace** [comment]
I have a PR for this, but with version `8.1.1`. Since `8.1.0` and `8.1.1` are solely differentiated by patch version, I presume my PR will resolve this issue. Is that alright?
