### ISSUE TITLE
Update request: helix 22.12 → 23.03

### ISSUE THREAD

**Issue by ilian** [NixOS/nixpkgs#224054]
- Package name: helix
- Latest released version: 23.03

- Current version on the unstable channel: 22.12
- Current version on the stable/release channel: 22.08.1

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@danth @yusdacra 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by eliasnaur** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/224397, I believe.

**Comment by ilian** [comment]
Closed by #224397
