### ISSUE TITLE
python3 support of pymacs 

### ISSUE THREAD

**Issue by spiderbit** [NixOS/nixpkgs#22408]
## Issue description

nox only shows me a python2.7 package of pymacs, pymacs supports python 3, so it would be nice to get a version 3 of it.

**Comment by FRidh** [comment]
The package has been disabled for Python 3.x as can be seen in the expression. Why I don't know. Maybe the maintainer @cillianderoiste can explain. 

In any case, if you want the Python 3.x version I suggest you fix the expression.

**Comment by FRidh** [comment]
Because this is a package request I am closing this issue. Do feel free to discuss further.
