### ISSUE TITLE
Package request: ovftool for macOS

### ISSUE THREAD

**Issue by khaled** [NixOS/nixpkgs#224002]
**Project description**

VMware OVF Tool is a command-line utility that helps you import and export OVF packages to and from many VMware products.

A package already exists for Linux ARM and x86-64.  VMWare ships package for macOS but, but support for it is missing from the package.

**Metadata**

* homepage URL: https://developer.vmware.com/web/tool/4.5.0/ovf-tool
* source URL: 
* license: unfree
* platforms: darwin

@numinit
@WolfangAukang

**Comment by WolfangAukang** [comment]
The main problem in my case is that I don't have an Apple machine nor somewhere to emulate one, so I might not be able to support this ovftool type.

**Comment by numinit** [comment]
Work in progress, doesn't function. I have a few questions on that PR about how to do this and not make it a complete mess.

#224440
