### ISSUE TITLE
Update request: lgogdownloader 3.10 → 3.11

### ISSUE THREAD

**Issue by turbohz** [NixOS/nixpkgs#224057]
- Package name: lgogdownloader
- Latest released version: 3.11

- Current version on the unstable channel: 3.10
- Current version on the stable/release channel: 3.9

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

> The current unstable release 3.10 contains a [bug](https://github.com/Sude-/lgogdownloader/commit/a81d63b3756c58578a35927535bf2967791d7ab0) that makes the tool almost unusable. 

**Notify maintainers**

@0x4A6F

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by marsam** [comment]
Addressed by https://github.com/NixOS/nixpkgs/pull/224095
