### ISSUE TITLE
Rust: Update to 1.15

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nixpkgs#22414]
Please someone update Rust to 1.15!

Pinging some rust packaging people...
@the-kenny @madjar @Ericson2314

**Comment by rushmorem** [comment]
A [pull request](https://github.com/NixOS/nixpkgs/pull/22403) has already been submitted 5 hours ago. I'm already testing it. The build has already been running for just as long. If it completes successfully I will merge it.

**Comment by matthiasbeyer** [comment]
Thank you very much! Can't wait! :tada: :birthday:

**Comment by rushmorem** [comment]
I have just merged it.
