### ISSUE TITLE
Cannot enable Nextcloud notify push daemon

### ISSUE THREAD

**Issue by tensor5** [NixOS/nixpkgs#224258]
### Describe the bug
Enabling `services.nextcloud.notify_push.enable` fails with:

```
Starting Push daemon for Nextcloud clients...
Error: php_literal_parser::unexpected_token
 × Error while parsing nextcloud config.php
 ╰─▶ Error while parsing '/var/lib/nextcloud/config/override.config.php':
     No valid token found, expected one of boolean literal, integer literal,
     float literal, string literal, 'null', 'array' or '['
   ╭─[18:1]
 18 │
 19 │   'dbpassword' => nix_read_secret(
   ·                   ┬
   ·                   ╰── Expected boolean literal, integer literal, float literal, string literal, 'null', 'array' or '['
 20 │   "/srv/nextcloud/secrets/db-password"
   ╰────
nextcloud-notify_push.service: Main process exited, code=exited, status=1/FAILURE
```

### Steps To Reproduce
1. Configure and enable Nextcloud
2. Enable `services.nextcloud.notify_push.enable`

### Expected behavior
The notify_push service starts.

### Notify maintainers

@ajs124

**Comment by ajs124** [comment]
Hm, I thought I had tested that. Can you test if it works if you modify the module to drop the `--glob-config '${cfgN.datadir}/config/config.php'` parameters from the script where it executes `${cfg.package}/bin/notify_push`?

**Comment by tensor5** [comment]
Doesn't work either. I don't know PHP, but it seems that `notify_push` is unable to parse the inline function.

**Comment by ajs124** [comment]
Yeah, notify_push is written in rust and doesn't actually execute php to parse the config, which is why this doesn't work.

**Comment by tensor5** [comment]
Upon further investigation, dropping only `--glob-config` works. Dropping the whole `--glob-config '${cfgN.datadir}/config/config.php'`  result a failure with:

```console
× No redis server is configured
```

It needs an option to set `REDIS_URL`.

**Comment by ajs124** [comment]
`REDIS_URL` can be set like `systemd.services.nextcloud-notify_push.environment.REDIS_URL = `.

Maybe we should transition away from putting a function into the nextcloud config and just modify the file in the setup service.

**Comment by SuperSandro2000** [comment]
> Steps to reproduce the behavior:
> 
>     1. Configure and enable Nextcloud
> 
>     2. Enable `services.nextcloud.notify_push.enable`

I have the same and I can't reproduce this issue.

**Comment by tensor5** [comment]
@SuperSandro2000, do you have the `dbpassword' => nix_read_secret(` line in your `override.config.php`? I think the reason is because I'm using an external DB and S3 storage.

https://github.com/NixOS/nixpkgs/blob/937a9d1ee7b1351d8c55fff6611a8edf6e7c1c37/nixos/modules/services/web-apps/nextcloud.nix#L764
https://github.com/NixOS/nixpkgs/blob/937a9d1ee7b1351d8c55fff6611a8edf6e7c1c37/nixos/modules/services/web-apps/nextcloud.nix#L795

**Comment by Shawn8901** [comment]
If you have passwords used in the config the nixos module does inject that lookup function. In the initial PR of notify_push was already a discussion how to handle that, and there was already a suggestion to drop `--glob-config` https://github.com/NixOS/nixpkgs/pull/201780#discussion_r1050234856

I dont remember why it was not done there, i basically withed to non password authentication (as everything is running on the same machine anyways, so using the socket solved the issue back then, so i forgot about it).

**Comment by SuperSandro2000** [comment]
> do you have the `dbpassword' => nix_read_secret(` line in your `override.config.php`?

nope, I am using socket authentication.
