### ISSUE TITLE
cudaPackages: consider splitting libnvcuvid out from nvidia_driver

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#224294]
- [ ] Verify if nvcuvid is actually hardware-depended and needs to be deployed impurely, like `libcuda.so`
- [ ] If it's not, split it out into a separate output or derivation
- [ ] Make other libraries link to it directly through Runpath

Motivated by https://github.com/NixOS/nixpkgs/issues/218859

**Comment by Kiskae** [comment]
> ❯ readelf -p .rodata /run/opengl-driver/lib/libnvcuvid.so | grep version
>  [5c97e0]  Library version doesn't match driver version [NV_ERR_LIB_RM_VERSION_MISMATCH]

Pretty much all the nvidia userspace libraries are version-locked to the associated driver version, so this won't work.

**Comment by SomeoneSerge** [comment]
Ah, so that's how this works! I guess that settles it
