### ISSUE TITLE
Package request: neovim-nightly

### ISSUE THREAD

**Issue by mbledkowski** [NixOS/nixpkgs#224261]
**Project description**

 Vim-fork focused on extensibility and usability. Nightly (dev) release.

**Metadata**

* homepage URL: https://neovim.io/
* source URL: https://github.com/neovim/neovim
* license: Apache 2.0
* platforms: unix, linux, darwin

@manveru 
@rvolosatovs

**Comment by teto** [comment]
we can't provide dev version for software in nixpkgs, it doesn't scale. You can use https://github.com/nix-community/neovim-nightly-overlay or neovim's flake check https://nixos.wiki/wiki/Neovim#Tips_and_tricks
