### ISSUE TITLE
mongodb 4.2 does not start correctly (with unifi-controller)

### ISSUE THREAD

**Issue by dnaq** [NixOS/nixpkgs#224201]
### Describe the bug
When trying to run the unifi controller on nixos-unstable mongo never starts up correctly, and the unifi controller logs are filled with messages about the database being down.

### Steps To Reproduce
1. `services.unifi.enable = true;`
2. `services.unifi.unifiPackages = pkgs.unifi7;`

### Expected behavior
That the unifi controller starts up correctly.

### Temporary workaround
1. Use the mongodb-4_2 derivation from nixos-22.11
```
services.unifi.mongodbPackage = inputs.nixpkgs-22.legacyPackages.aarch64-linux.mongodb-4_2;
```

### Notify maintainers
@bluescreen303 @cstrahan @erictapen @pennae 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05.20230330.e3652e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - nixpkgs: `/nix/store/fb5ci6653i73gr10by36bxg2f5v69lwf-source`

```

**Comment by dnaq** [comment]
That is definitely a possibility. Worth to mention might be that mongodb 4.2 didn’t build at all for a while on nixos-unstable on aarch64-linux, but now that it started building again this issue surfaced.

**Comment by dnaq** [comment]
Workaround no longer seems to work as well, mongodb never starts when started by the UniFi controller.

Looking at the logs it seems like UniFi tries to start mongo with the flag `--nohttpinterface` which seems to have been removed. Not sure if this is the cause of the issue or if it's something else.

**Comment by dnaq** [comment]
Fair enough. Then maybe deprecation of the unifi package would be the best way forward, maybe with a recommendation to use a docker image if necessary?

**Comment by dnaq** [comment]
I'm starting to think this is an issue with the unifi controller, my guess is that it somehow corrupts its database on write-heavy workloads (metrics enabled), and stops working. Saw something similar happen with a docker distribution of the unifi controller for aarch64.

**Comment by dnaq** [comment]
I’m leaning towards the unifi controller corrupting the mongo database when loads are more write heavy (more detailed metrics). Closing this issue, the only potential nixos specific parts of it would be better failure detection, since right now the systemd unit hangs and can’t be stopped if any database corruption has happened.

**Comment by Majiir** [comment]
See https://github.com/NixOS/nixpkgs/pull/207382#issuecomment-1371303817 and https://github.com/NixOS/nixpkgs/pull/207382#issuecomment-1377901344, and the [MongoDB upgrade instructions](https://www.mongodb.com/docs/manual/release-notes/4.0-upgrade-standalone/). Following the appropriate upgrade sequence and using `setFeatureCompatibilityVersion` as described in the update docs, I was able to get mongodb 4.4 working with Unifi Controller 6 on NixOS 23.05.

**Comment by Majiir** [comment]
To clarify, it works with nixpkgs as-is. The links above describe how a Unifi user on NixOS 22.11 can upgrade to 23.05 by properly upgrading the Unifi database first. I agree that an automatic upgrade feature would be overkill for Unifi.
