### ISSUE TITLE
Update request: podman-desktop 0.12.0 → 0.13.0

### ISSUE THREAD

**Issue by dylanmtaylor** [NixOS/nixpkgs#224301]
- Package name: podman-desktop
- Latest released version: 0.12.0

- Current version on the unstable channel: 0.12.0
- Current version on the stable/release channel: N/A

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

@panda2134 bad timing with this one, new version right after you got the package merged.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by devurandom** [comment]
Latest stable version is 1.11.1: https://github.com/containers/podman-desktop/releases/tag/v1.11.1

**Comment by gepbird** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/343648
