### ISSUE TITLE
Document nix-store auto-optimize feature

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixpkgs#22436]
`simpson` on `#nixos` pointed out that you can have nix-store optimize the database as its built. This would be great to have in the manual: http://lists.science.uu.nl/pipermail/nix-dev/2015-February/016180.html

**Comment by vcunat** [comment]
This is wrong repo, and it *is* documented on the expected place: http://nixos.org/nix/manual/

**Comment by 3noch** [comment]
@vcunat Ah thanks for this. But I'm still not satisfied. The link I posted specifically describes how to enable this feature globally for your store. I think connecting the dots is way too much to ask for the majority of folks (like me). I highly doubt I would have realized it could be enabled globally without that email thread.

**Comment by vcunat** [comment]
Any suggestion on improving the documentation?

**Comment by 3noch** [comment]
Neither the NixOS nor the Nixpkgs manuals mention `auto-optimise-store` at all. I'd recommend copying almost the entire email into the Nixpkgs manual and linking to it from the NixOS manual with a minor heading and description. Or possibly the other way around.

I'd be happy to do this if you can recommend a good spot for it.

**Comment by vcunat** [comment]
I'm inclined that NixOS and Nixpkgs manual should refer to Nix manual as a "prerequisite", as you do have to use nix.  Duplicating some brief explanation seems OK to me, but not such details as `auto-optimise-store` (but the description in Nix manual could be more verbose, I guess).

**Comment by 3noch** [comment]
@vcunat Yah I actually don't care as much *where* the detail goes. The key is that a nix feature combined with a NixOS/Nixpkgs feature is very valuable, but you have to compose those features entirely by yourself. That's just way too much to ask for most casual users and deserves a bit more exposure. I'm voicing this opinion after several people on `#nixos` all chimed in and said "That needs to be in the manual."
