### ISSUE TITLE
enabled samba, but no smbpasswd/pdbedit exists

### ISSUE THREAD

**Issue by kReoSo** [NixOS/nixpkgs#22435]
## Issue description

services.samba.enable = true;
smbd.service and nmbd.service work, 

```
zsh/3 523 % systemctl | grep -i samb                                                                                /etc/nixos
samba-nmbd.service                                                                                    loaded active running   Samba Service Daemon nmbd
samba-smbd.service                                                                                    loaded active running   Samba Service Daemon smbd
samba-winbindd.service                                                                                loaded active running   Samba Service Daemon winbindd
samba.target                                                                                          loaded active active    Samba Server
```

but when I invoke the command smbpasswd/pdbedit,

```
zsh/3 520 [1] % smbpasswd
The program ‘smbpasswd’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.samba
  nix-env -iA nixos.samba3
  nix-env -iA nixos.samba3_light
```

Do I need to install samba explicitly, even if I enabled the service and the services run? 

## Technical details
17.03pre99759.f66d782 (Gorilla)
nix-env (Nix) 1.11.6

**Comment by kReoSo** [comment]
I found the samba package is actually installed in the directory `/nix/store/.......-samba-4.5.3`, and there are all the binaries I sought. It's just not in my PATH variable.(perhaps related to that I enabled and used zsh?)

I don't know it is intended, but if so, it should be noted in the manual or wiki IMHO. 

Problem solved for me, so I'm closing this issue.

**Comment by danbst** [comment]
> Do I need to install samba explicitly, even if I enabled the service and the services run?

yes, but if you think it doesn't make sense, you can send a PR that adds line like

```
  environment.systemPackages = [ config.services.samba.package ];
```
to samba module. So everyone, who enabled samba service will get the binaries in their PATH
