### ISSUE TITLE
(22.11) openrazer module doesn't make user service available

### ISSUE THREAD

**Issue by paulhersch** [NixOS/nixpkgs#224371]
### Describe the bug
The service file for the openrazer-daemon.service is created (checked via `ls /nix/store`), but not executed. It can also not be found by `systemctl`.

### Steps To Reproduce
1. `hardware.openrazer.enable = true` in config

I really don't know what else could lead to this behaviour

### Expected behavior
- daemon is started on graphical-session.target
- i can start, stop, ... the daemon via `systemctl --user ...`

### Additional context
```
$ systemctl --user status openrazer-daemon.service
Unit openrazer-daemon.service could not be found.
```
When i manually copy the exec line from the service file that is being created, i can start the daemon (which also indicates that the daemon is not started by sysd, as you would get "unable to lock on the pidfile" otherwise.

~~Please tell me if something like this was fixed some time ago, as i have last updated my systems flake.lock one month ago (updates always take ages due to my network connection).~~
EDIT: updated to latest 22.11 revision, problem persists

whats weird, is that all other user services that i am aware of seem to be functioning properly, openrazer is the only bad fruit here

### Metadata
(Flake system, no channels)
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.0, NixOS, 22.11 (Raccoon), 22.11.20230307.a7cc819`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
```

**Comment by paulhersch** [comment]
Update: still not working as expected in 23.05. Using service exec line to run the service works without any issues (the file is created, just not used by systemd).
Checked journalctl because this is getting on my nerves again and this is what came up:
```
journalctl -b 0 | grep openrazer
Okt 10 13:21:29 snowstorm systemd[1714]: openrazer-daemon.service: Failed to open /home/paul/.config/systemd/user/openrazer-daemon.service: No such file or directory
```
so it seems like running the service/making it run on default.target works, it just doesn't use the derivations output to run it?

**Comment by bryanasdev000** [comment]
> Update: still not working as expected in 23.05. Using service exec line to run the service works without any issues (the file is created, just not used by systemd). Checked journalctl because this is getting on my nerves again and this is what came up:
> 
> ```
> journalctl -b 0 | grep openrazer
> Okt 10 13:21:29 snowstorm systemd[1714]: openrazer-daemon.service: Failed to open /home/paul/.config/systemd/user/openrazer-daemon.service: No such file or directory
> ```
> 
> so it seems like running the service/making it run on default.target works, it just doesn't use the derivations output to run it?

Do you have `hardware.openrazer.users = [ "youruser" ];` somewhere on your conifg?

https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/openrazer.nix#L98

**Comment by paulhersch** [comment]
Yes, i am using the name from `users.users.<name>`
```
hardware.openrazer.users = [ "paul" "luise" ];
```
(forgot to include that in the question, sorry)

**Comment by paulhersch** [comment]
ok found the issue, for some reason i do not understand there was always a symlink to a previous generations' output in the .config/systemd directory, that way it looked legit to me but i just didn't know that it was actually pointing to nothing.

Solved now :)
