### ISSUE TITLE
Package request: nodePackages.tsfmt

### ISSUE THREAD

**Issue by hashelq** [NixOS/nixpkgs#224320]
**Project description**
Formatter for Typescript.

**Metadata**
* homepage URL: https://www.npmjs.com/package/typescript-formatter
* source URL: https://github.com/vvakame/typescript-formatter
* license: MIT
* platforms: unix, linux

**Comment by hashelq** [comment]
may anyone finally add it? I am not familiar with nixpkgs, but it seems it just needs to add 5 lines of code.

**Comment by felschr** [comment]
typescript-formatter hasn't been maintained for over 4 years.
Is it possible for you to use prettier or another alternative instead?

**Comment by ocfox** [comment]
Good! I'll close my pull request! If you really want to use it, you could add it to your custom packages.
