### ISSUE TITLE
Scream does not compile with Jack support when enabled

### ISSUE THREAD

**Issue by Not-a-true-statement** [NixOS/nixpkgs#224467]
## Issue description

Scream does not compile with jack support when it is explicitly enabled through an overlay.

@arcnmx @r-ryantm @AndersonTorres 

### Steps to reproduce

`
  nixpkgs.overlays = [
    (final: prev: {
      scream = prev.scream.override { jackSupport = true; };
    })
]
`

**Comment by AndersonTorres** [comment]
Error message?

**Comment by Not-a-true-statement** [comment]
> Error message?

There is no error, it just skips compiling it.
someone else ran it and i think they said that it skips compiling it with jack support because soxr is missing

`
-- Checking for module 'jack'
--   Found jack, version 1.9.19
-- Checking for module 'soxr'
--   No package 'soxr' found
`

**Comment by arcnmx** [comment]
See #224493. In the meantime, you can try:
```
nixpkgs.overlays = [ (final: prev: {
  scream = (prev.scream.override { jackSupport = true; }).overrideAttrs (old: {
    buildInputs = old.buildInputs ++ [ final.soxr ];
  });
}) ]
