### ISSUE TITLE
Noisy output from nixos-rebuild with dictd enabled

### ISSUE THREAD

**Issue by olejorgenb** [NixOS/nixpkgs#22442]
## Issue description

Not sure if it's an error or not but after adding

     services.dictd.enable = true;
     services.dictd.DBs = [ pkgs.dictdWordnet ];

to configuration.nix

`nixos-rebuild switch` outputed:

    ... snip ...
    /nix/store/gabjbkwga2dhhp2wzyaxl83r8hjjfc37-bash-4.3-p48/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    dictfmt: option '--locale' requires an argument
    dictfmt-1.12.1
    Copyright 1997-2000 Rickard E. Faith (faith@cs.unc.edu)
    Copyright 2002-2007 Aleksey Cheusov (vle@gmx.net)
    
    Usage: dictfmt -c5|-t|-e|-f|-h|-j|-p [-u url] [-s name] [options] basename
           dictfmt -i|-I [options]
    Create a dictionary databse and index file for use by a dictd server
    
    -c5       headwords are preceded by a line containing at least 
                    5 underscore (_) characters
    -t        implies -c5, --without-headword and --without-info options
    -e        file is in html format
    -f        headwords start in col 0, definitions start in col 8
    -j        headwords are set off by colons
    -p        headwords are preceded by %p, with %d on following line
    -i        reformat stdin having three-column .index file format
    -u <url>  URL of site where database was obtained
    -s <name> name of the database
    --license
    -L        display copyright and license information
    --version
    -V        display version information
    -D        debug
    --utf8    for creating utf-8 dictionary
    --quiet
    --silent
    -q        quiet operation
    --help    display this help message
    --locale   <locale> specifies the locale used for sorting.
               if no locale is specified, the "C" locale is used.
    --allchars all characters (not only alphanumeric and space)
               will be used in search if this argument is supplied
    --headword-separator <sep> sets headword separator which allows
                         several words to have the same definition
                         Example: autumn%%%fall can be used
                         if '--headword-separator %%%' is supplied
    --index-data-separator <sep> sets index/data separator which allows
                         to explicitely set fourth column in .index file,
                         the default is "\034"
    --break-headwords    multiple headwords will be written on separate lines
                         in the .dict file.  For use with '--headword-separator.
    --index-keep-orig    fourth column in .index file stores original headword
                         which is returned by MATCH command
    --case-sensitive     Create .index/.dict files for case sensitive search
    --without-headword   headwords will not be copied to .dict file
    --without-header     header will not be copied to DB info entry
    --without-url        URL will not be copied to DB info entry
    --without-time       time of creation will not be copied to DB info entry
    --without-info       DB info entry will not be created.
                         This may be useful if 00-database-info headword
                         is expected from stdin (dictunformat outputs it).
    --columns            Set the number of columns for wrapping text
                         before writing it to .dict file.
                         If it is zero, wrapping is off.
    --default-strategy  Sets the default search strategy for the database.
                        Special entry 00-database-default-strategy is created
                        for this purpose.
    --mime-header       Sets MIME header stored in .data file which
                        prepend definition
                        when client sent OPTION MIME to `dictd'
    --without-ver      do not create 00-database-dictfmt-<VER> entry in .index
    awk: cmd. line:4: fatal: cannot open file `en_US.UTF-8' for reading (No such file or directory)
    ... snip ...

I think the output comes from pkgs/servers/dict/dictd-db-collector.nix which haven't changed in a long time

## Technical details

* System: NixOS: 16.09.1465.fd1dbe5 (Flounder)
* Nix version: nix-env (Nix) 1.11.4
* Nixpkgs version: "16.09.1465.fd1dbe5"

**Comment by layus** [comment]
Would you mind giving the full output ? Could this be a build failure for some dictd package instead of an issue with nixos-rebuild ?

**Comment by olejorgenb** [comment]
Hm, not sure how I trigger it again (without deleting all profiles (if there's a simple way do delete some profiles I can delete those that keep the dict derivation from beeing gc'ed))

**Comment by edwtjo** [comment]
Well.. you have `dictdWordnet` instead of `dictdDBs.wordnet` but your rebuild doesn't output that the attribute is missing, which it should since it isn't in top-level, so it seems unrelated to the change f59a1ee660060232891789cef8951cb9dfd9aeb9. On the other hand I seem to be able to reproduce your output so I'll look into it.

**Comment by layus** [comment]
@edwtjo, @olejorgenb Any progress on this ? Is it still reproducible ?

**Comment by olejorgenb** [comment]
@layus I haven't noticed any malfunction as a result and haven't noticed the messages again -> closing.
