### ISSUE TITLE
doas does not cross-compile

### ISSUE THREAD

**Issue by dsalaza4** [NixOS/nixpkgs#224490]
### Describe the bug
`doas` command does not build on `aarch64-multiplatform` and `aarch64-multiplatform-musl`.

### Steps To Reproduce

```console
nix-shell -p pkgsCross.aarch64-multiplatform.doas
...
building
build flags: SHELL=/nix/store/9zm6br2ri10a0b71dll2wrim5bnhg6b6-bash-5.1-p16/bin/bash
yacc  parse.y
/nix/store/9zm6br2ri10a0b71dll2wrim5bnhg6b6-bash-5.1-p16/bin/bash: line 1: yacc: command not found
make: *** [<builtin>: parse.c] Error 127
error: builder for '/nix/store/qgi06mxsqjn08rnvklkh0q1ckwrpwzxf-doas-aarch64-unknown-linux-gnu-6.8.2.drv' failed with exit code 2;
       last 10 log lines:
       > Checking for login_cap_h ...              no.
       > Checking for __attribute__ ...             yes.
       > Checking for pam_appl_h ...               yes.
       > Using auth method                 pam.
       > Using persist method                      timestamp.
       > building
       > build flags: SHELL=/nix/store/9zm6br2ri10a0b71dll2wrim5bnhg6b6-bash-5.1-p16/bin/bash
       > yacc  parse.y
       > /nix/store/9zm6br2ri10a0b71dll2wrim5bnhg6b6-bash-5.1-p16/bin/bash: line 1: yacc: command not found
       > make: *** [<builtin>: parse.c] Error 127
       For full logs, run 'nix log /nix/store/qgi06mxsqjn08rnvklkh0q1ckwrpwzxf-doas-aarch64-unknown-linux-gnu-6.8.2.drv'.
```

### Expected behavior

`doas` should compile properly for `aarch64-multiplatform` and `aarch64-multiplatform-musl`.

### Notify maintainers

@cole-h @cstrahan 

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05.20230328.49079a1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(nixos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cole-h** [comment]
`doas` cross compiles for me just fine:

```
$ nix-build -A pkgsCross.aarch64-multiplatform-musl.doas
/nix/store/lz44law50ipjjindnlasrm8b605fp8yn-doas-aarch64-unknown-linux-musl-6.8.2
$ nix-build -A pkgsCross.aarch64-multiplatform.doas
/nix/store/nizpkqa1xiijnj8fqdzv6wcz5n1j2cnf-doas-aarch64-unknown-linux-gnu-6.8.2
$ git rev-parse HEAD
74c56f2e51d08f0196ed48d32e01d5d408e64451
```

@dsalaza4 Can you confirm if cross-compilation is still broken for you on the latest `master`?

---

@jpverde I wouldn't expect `nix-shell -p doas` to work on a Macbook considering the package only supports Linux: 

https://github.com/NixOS/nixpkgs/blob/74c56f2e51d08f0196ed48d32e01d5d408e64451/pkgs/tools/security/doas/default.nix#L57

**Comment by dsalaza4** [comment]
@cole-h 

- I was using https://github.com/NixOS/nixpkgs/commit/53dad94e874c9586e71decf82d972dfb640ef044, which triggered the `yacc` error.
- I thought I was at the latest version based on the pkg source code history: https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/tools/security/doas/default.nix
- When I upgraded to https://github.com/NixOS/nixpkgs/commit/b01f185e4866de7c5b5a82f833ca9ea3c3f72fc4 it worked.

It looks like I'm missing something here 🤔 

Closing this issue!
