### ISSUE TITLE
PHP 8.0 removal

### ISSUE THREAD

**Issue by LeSuisse** [NixOS/nixpkgs#224505]
PHP 8.0 will reach end-of-life at the end in November 2023.

This issue is here to track the progress of its removal from `nixpkgs`.

This affects:
* [x] `grocy`
   - `master` [supports PHP 8.1](https://github.com/grocy/grocy/commit/38a4ad8ec480c29a1bff057b3482fd103b036848), not released yet (2023-04-03)
   - #232276
* [x] `limesurvey`
   -  #232276
   - #237389
* [x] `moodle`
   - PR to move to PHP 8.1 : #224491
* [x] `roundcube`
   - PR to move to PHP 8.1 #224494
* [x] `tt-rss`
  - They seem to use PHP 8.1 in [their test suites/Docker images](https://gitlab.tt-rss.org/tt-rss/tt-rss/-/blob/58450486a09d594172c9f5fd6260bb8bc3cc6ed4/.docker/app/Dockerfile#L7), should be OK to upgrade
  - PR to move the module to PHP 8.1 by default: #228492
* [ ] `n98-magerun`
  - Upstream ticket tracking PHP 8.1 progress: https://github.com/netz98/n98-magerun/issues/1275
* [x] `arcanist`
  - Upstream ticket tracking PHP 8 compatibility: https://secure.phabricator.com/T13588 (seems mostly done?)
  - #232272
* [x] Support of PHP 8.0 in `unit`
  - PR to drop PHP 8.0 support: #227026

**Comment by Atemu** [comment]
Wouldn't it be better to just mark php80 as "broken" rather than the individual packages?

Ideally, we'd also only mark it broken when `lib.isInOldestRelease 2305` which would "automatically" happen before branch-off of 23.11.

I think I might shoot a PR to do this while reverting https://github.com/NixOS/nixpkgs/pull/232276 so that Grocy can still be used until branch-off. In the mean time, upstream will hopefully have released a PHP 8.1 compatible version (https://github.com/grocy/grocy/issues/2251).

**Comment by Atemu** [comment]
https://github.com/NixOS/nixpkgs/pull/236904

**Comment by LeSuisse** [comment]
PHP 8.0 will be removed before 23.11 branch off as it will be end of life by then.

> Ideally, we'd also only mark it broken when lib.isInOldestRelease 2305 which would "automatically" happen before branch-off of 23.11.

It's the packages that are broken not PHP itself, marking the packages directly is the way to go IMO. It's also make things clear and put them on the path of removal if upstream cannot maintain them to a maintained version of PHP.

**Comment by LeSuisse** [comment]
@sreichel Do you know if there is any chance that a version of n98-magerun compatible with PHP 8.1 will be published soon(ish)? The upstream issue seems to be stalled for the past 2 weeks.

**Comment by sreichel** [comment]
@LeSuisse @cmuench i cant tell about release plans.

**Comment by sreichel** [comment]
@LeSuisse  magerun is nearly ready. There is a v3 dev-release for php81, that just need some improvments.
