### ISSUE TITLE
Support building `osrm-backend` on macOS

### ISSUE THREAD

**Issue by srid** [NixOS/nixpkgs#224535]
### Steps To Reproduce

1. `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix build nixpkgs#osrm-backend --impure`

### Build log

```
error: builder for '/nix/store/phyfv3vv06g2qjm46f8ipvql840bcjva-luabind-0.9.1.drv' failed with exit code 1;
       last 10 log lines:
       > Jamroot:16: Unescaped special character in argument [luabind
       > Jamroot:16: Unescaped special character in argument DEBUG]
       > Jamroot:93: Unescaped special character in argument prefix:
       > Jamroot:94: Unescaped special character in argument includes:
       > Jamroot:95: Unescaped special character in argument lib:
       > Jamroot:96: Unescaped special character in argument candidates:
       > Jamroot:97: Unescaped special character in argument to:
       > error: at Jamroot:101
       > error: *** Unable to find Lua library.
       >
       For full logs, run 'nix log /nix/store/phyfv3vv06g2qjm46f8ipvql840bcjva-luabind-0.9.1.drv'.
error: 1 dependencies of derivation '/nix/store/5r0j9xn0w1h3l6bc3vvjabm7bv4828r8-osrm-backend-5.26.0.drv' failed to build
```

### Additional context

FWIW: my fix is here, https://github.com/juspay/nixpkgs/pull/1/files - but it is using a fork of `luabind`.  If somebody has the time to create a minimal patch on top of the current source, please feel free to. 
### Notify maintainers

@erictapen 

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.2.0, macOS 13.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by erictapen** [comment]
Looks like you are on a good path. Unfortunately I have no access to Apple hardware at all, but would be happy to merge a PR.

**Comment by srid** [comment]
@erictapen Yes, @aravindgopall is working on it. 

There is a more active fork of luabind here: https://github.com/Oberon00/luabind - how about we switch to using it? It'll obviate a bunch of patches as well.

**Comment by erictapen** [comment]
> how about we switch to using it?

I agree, sounds sensible.

**Comment by aravindgopall** [comment]
#225008
