### ISSUE TITLE
Update request: breitbandmessung 3.1.0 → 3.3.0

### ISSUE THREAD

**Issue by davidak** [NixOS/nixpkgs#224524]
- Package name: breitbandmessung
- Latest released version: 3.3.0

- Current version on the unstable channel: 3.1.0
- Current version on the stable/release channel: 3.1.0

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

New release is available. Maybe that fixes the issue with EOL electron.

>        Known issues:
>         - Electron version 16.2.3 is EOL

**Notify maintainers**

@b4dm4n

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by pinpox** [comment]
This is fixed by the PR above (https://github.com/NixOS/nixpkgs/pull/233841)
