### ISSUE TITLE
emacsclient cannot open display

### ISSUE THREAD

**Issue by crawford** [NixOS/nixpkgs#224512]
### Describe the bug

I have the Emacs daemon enabled on my system (`services.emacs.enable = true;`). When I log in, I can see that the daemon is running but I am unable to start `emacsclient`:

```console
$ emacsclient -c
Waiting for Emacs...
*ERROR*: Display :0 can’t be opened
```

Restarting the daemon fixes the issue. Is the daemon starting too early and missing some variables from Wayland?

### Steps To Reproduce

1. Enable emacs daemon (`services.emacs.enable = true;`)
2. Log in and try to run `emacsclient`

### Expected behavior

`emacsclient` starts:

```console
$ emacsclient -c
Waiting for Emacs...
```

### Notify maintainers

@DamienCassou

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.103, NixOS, 22.11 (Raccoon), 22.11.3265.e2c97799da5`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"machines, nixos-22.11, nixos-hardware"`
 - channels(alex): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by DamienCassou** [comment]
I'm not the maintainer of this service and I don't use it. I use the Emacs service from home-manager which I recommend: https://rycee.gitlab.io/home-manager/.

**Comment by crawford** [comment]
My apologies. I saw that you were the original author, so I figured you were my best bet.

It looks like home-manager might be avoiding this by (optionally) using socket activation. Something similar might work here, but I'm sure there's a more robust solution. I'll have to dig into it a bit when I have time.

**Comment by DamienCassou** [comment]
Does https://github.com/nix-community/home-manager/issues/3443#issuecomment-1436135462 helps @crawford?

**Comment by crawford** [comment]
Yeah, ordering `emacs.service` after `graphical-session.target` seems to have worked. Thanks for the tip. I'm trying to work up a nice way to incorporate that into the service definition. Unfortunately, simply adding the "after" directive doesn't seem to be enough. I'm guessing that's because `default.target` is reached, or at least initiated, before `graphical-session.target`. I'm going to keep poking at it over the coming days.

**Comment by ibizaman** [comment]
Wanted to confirm `startWithUserSession = "graphical"` made this issue go away.

**Comment by jys1670** [comment]
Same here, "graphical" solution works. It would be nice to see @Atemu's pr merged.
