### ISSUE TITLE
python3Packages.torchWithRocm: 2.0.0 unnecessarily requires unfree dependencies

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#224689]
## Issue description

Once we [update `python3Packages.torch` to `2.X.X`](https://github.com/NixOS/nixpkgs/pull/222273), its `torchWithRocm` variation will depend on `cudaPacakges.cuda_nvcc` (through `python3Packages.openai-triton`), which is unfree. This means hydra won't be building and caching `torchWithRocm`.

Upstream enforces that there be a copy of `bin/ptxas` (from `cuda_nvcc`):
- https://github.com/pytorch/pytorch/blob/558e5a240e0c2a5e9a0d5350fe6c25b029efca6a/setup.py#L931
- https://github.com/openai/triton/blob/01a93185a1105cf4b3ab504ec385ff3585160932/python/setup.py#L211

However, they do not actually use it except for cuda support (obviosuly).
We should patch around this to re-enable caching, and we should work with upstream to make the dependency optional in the first place

CC @NixOS/rocm-maintainers

**Comment by Madouura** [comment]
Sadly, with the new ROCm updates, I've only made it worse.
We can't seem to reasonably patch `hsa-amd-aqlprofile` out of `rocprofiler` anymore.

**Comment by Madouura** [comment]
This was fixed in 6f3f5b64f2cb52294097f9b2b74762cb7776c95e and #263048.
