### ISSUE TITLE
Update request: organicmaps 2023.03.05-5 → 2023.04.02-7

### ISSUE THREAD

**Issue by Steinhagen** [NixOS/nixpkgs#224678]
- Package name: organicmaps
- Latest released version: 2023.04.02-7

- Current version on the unstable channel: 2023.03.05-5
- Current version on the stable/release channel: 2023.01.25-3

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**

 @fgaz

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by fgaz** [comment]
#224599
