### ISSUE TITLE
Package request: mullvad-browser

### ISSUE THREAD

**Issue by paveloom** [NixOS/nixpkgs#224631]
**Project description**

The Mullvad Browser is a privacy-focused web browser developed in a collaboration between [Mullvad VPN](https://mullvad.net/) and the [Tor Project](https://www.torproject.org/). It’s designed to minimize tracking and fingerprinting. You could say it’s a Tor Browser to use without the Tor Network. Instead, you can use it with a trustworthy VPN. The idea is to provide one more alternative – beside the Tor Network – to browse the internet with more privacy. To get as many people as possible to fight the big data gathering of today. To free the internet from mass surveillance.

**Metadata**

* homepage URL: https://mullvad.net/browser
* source URL: https://github.com/mullvad/mullvad-browser
* license: free
* platforms: linux, darwin

**Comment by nboehlke** [comment]
that would be awesome! Lookin' forward to test it

**Comment by paveloom** [comment]
Thank you very much, @felschr!
