### ISSUE TITLE
Build failure: linux (powerpc)

### ISSUE THREAD

**Issue by alyssais** [NixOS/nixpkgs#224694]
Building powerpc kernels (I only tested pkgsCross.powernv, but examination of the kernel source code suggests to me that 32-bit powerpc, and well as big-endian 64-bit will be the same) is broken since https://github.com/NixOS/nixpkgs/pull/221707.  This happens because on powerpc, the kernel target we install is vmlinux, rather than any derivative of it like zImage.  The kernel build system will strip when creating such a derivative image, but because we install vmlinux directly, we get an unstripped image.  This means the kernel contains references to its build directory, which since that PR will be the $dev output.

AIUI, 64-bit POWER boots via kexec, and a zImage is a self-extracting kernel ELF image, so hopefully the fix would just be to switch the kernel target for powerpc to zImage, and things will work again, and POWER users will get smaller kernel images as a bonus.

I'm not sure about 32-bit PowerPC, but this [kernel documentation](https://www.kernel.org/doc/html/latest/powerpc/bootwrapper.html) might be helpful.

If we can't use an *Image target for any powerpc targets, there is also a target called vmlinux.strip that we could fall back to, but let's take the opportunity to evaluate whether anything else is more suitable first, when we're changing this stuff anyway.

Apart from powerpc, the only [target](https://github.com/NixOS/nixpkgs/blob/cd1e297b9327ff3242227264977e4bea2b747d81/lib/systems/platforms.nix#L407-L483) we have that uses vmlinux as its kernel target is a MIPS machine called the Fuloong 2.0.  I don't know how it boots.

**Comment by amjoseph-nixpkgs** [comment]
I'll handle this.

I don't have big-endian POWER hardware, but @alyssais pointed out that qemu can probably boot a BE kernel under emulation at full hardware speeds.  So if that works I can take care of the 32-bit POWER (which is mostly BE) too.

**Comment by vkleen** [comment]
For reference, I managed to get a working kernel derivation for Power9 with
```
kernelPackages = pkgs.linuxKernel.packageAliases.linux_latest.extend
    (final: prev: lib.optionalAttrs pkgs.stdenv.hostPlatform.isPower64 {
      kernel = lib.makeOverridable
        (args:
          let
            kernel = prev.kernel.override args;
          in
          kernel.overrideAttrs (o: {
            buildFlags = o.buildFlags ++ [ "modules" "zImage" ];
            installFlags = o.installFlags ++ [ "KBUILD_IMAGE=$(boot)/zImage" ];
            installTargets = [ "install" ];
            postFixup = (o.postFixup or "") + ''
              strip -s $out/zImage
            '';
            inherit (kernel) passthru;
          }))
        { };
    });
```
Just setting building a zImage without fully stripping it afterwards wasn't enough. There still was a reference to `$dev` in the debug info somewhere.

**Comment by alyssais** [comment]
Yep, very plausible that there are other references as well.  We had [some of those](https://lore.kernel.org/linux-kbuild/20230326182120.194541-1-hi@alyssa.is/) for x86 and RISC-V, although that specific issue didn't apply to other architectures.

**Comment by amjoseph-nixpkgs** [comment]
I'll dig into this this evening.  @vkleen thank you for the tip!

Also putting this link here so I don't lose it: https://lore.kernel.org/linux-kbuild/20230326182120.194541-1-hi@alyssa.is/

**Comment by amjoseph-nixpkgs** [comment]
Verified (after fixing a bunch of other things) that `mips64el` is affected too.  Thanks again for the heads up @alyssais.  Working on a fix.

**Comment by alyssais** [comment]
I've done some investigation of my own.  Here are the results:

## PowerPC

PowerPC ends up with two sets of references.  One is from kexec purgatory, and is probably an oversight.  I expect I could upstream a patch to fix this, like I recently did for x86 and RISC-V[^1].  The other is from the VDSO.  Unlike every other architecture, PowerPC deliberately uses a non-stripped vdso, apparently because it made perf traces nicer.  So unless things I've changed there (I'll try to have a look — it seems a bit strange that PowerPC would be special here), we won't be able to get the kernel build system to give us a reference-free PowerPC image.  So even though I don't like it, ack to stripping manually on PowerPC.

[^1]: the only thing getting in the way here is that it's a bit annoying to test, because our kexec test is [currently broken](https://github.com/NixOS/nixpkgs/pull/207039#issuecomment-1555289200).  cc @RaitoBezarius.

## MIPS

MIPS offers vmlinux, vmlinuz, and uImage.  vmlinuz and uImage should both be reference-free, but I don't know enough about how MIPS boots to know whether either of those would be sensible default targets.  I'd appreciate your insight here.  If it's not feasible to change to either of those images, then we probably have to strip manually on MIPS too.

**Comment by amjoseph-nixpkgs** [comment]
Fixed by

- https://github.com/NixOS/nixpkgs/pull/245449
