### ISSUE TITLE
vscode packages are no longer downloadable

### ISSUE THREAD

**Issue by gebner** [NixOS/nixpkgs#22465]
## Issue description

`nix-build -A vscode` fails with:
```
these derivations will be built:
  /nix/store/qcf20qap9lfqm8s5iwmrq6i5i227zv44-code-stable-code_1.9.0-1486023356_amd64.tar.gz.drv
  /nix/store/389nvvpblfzh0c05mdp540xmig4wfq5k-vscode-1.9.0.drv
building path(s) ‘/nix/store/6sj3yp6vv9jwch4jycjjms3lzaaqhdn3-code-stable-code_1.9.0-1486023356_amd64.tar.gz’

trying https://az764295.vo.msecnd.net/stable/38746938a4ab94f2f57d9e1309c51fd6fb37553d/code-stable-code_1.9.0-1486023356_amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

@xwvvvvwx @jansuchomel How did you get the download links for vscode?  I wanted to update it and looked on the vscode website for the links, but couldn't find the ones with the timestamps.

## Technical details

* System: `17.03pre100133.a14217e (Gorilla)`
* Nix version: 1.11.6
* Nixpkgs version: c226a93a9effa2ee1d5eb0fb1aa22befa78192fc

**Comment by xwvvvvwx** [comment]
@gebner I ran the links from the website (e.g. https://go.microsoft.com/fwlink/?LinkID=620884) through a url unshortening service (e.g. http://www.linkexpander.com/) to get the long urls

**Comment by jansuchomel** [comment]
You can get the current url as a redirect from these urls:

- https://vscode-update.azurewebsites.net/latest/linux-x64/stable
- https://vscode-update.azurewebsites.net/latest/linux-ia32/stable
- https://vscode-update.azurewebsites.net/latest/darwin/stable .

To get the redirect url, run for example:
`curl -w "%{url_effective}\n" -I -L -s -S https://vscode-update.azurewebsites.net/latest/linux-x64/stable -o /dev/null`.

**Comment by gebner** [comment]
Thanks for the instructions!  I added them to the derivation, and linked to this issue.

Interestingly enough, only the revision has changed.  The hashes are still the same.

**Comment by mucaho** [comment]
Just for info: IIRC I got the revisions by looking at the [vscode's github](https://github.com/Microsoft/vscode). Each release tag was associated with a commit revision. This revision could be used to generate the download url then.

**Comment by benley** [comment]
The timestamp in the URLs for the x64 and ia32 versions gets in the way of generating the whole URL without manually fetching and comparing each time.  It's annoying that there isn't a more predictable download url for these.
