### ISSUE TITLE
`services.grafana.provision.datasources` is parsing `assertions` into the generated `yaml` file

### ISSUE THREAD

**Issue by budimanjojo** [NixOS/nixpkgs#224623]
### Describe the bug
The `services.grafana.provision.datasources` module seems to be generating wrong `yaml` file.

### Steps To Reproduce

I have this in my `configuration.nix`:
```
config.services.grafana = {
  enable = true;
  provision = {
    enable = true;
    datasources.settings.datasources = [
      {
        name = "prometheus";
        type = "prometheus";
        url = "localhost:${toString config.services.prometheus.port}";
        isDefault = true;
      }
    ];
  };
}
```

And the generated `datasource.yaml` looks like this:
```
 cat /nix/store/f2a3k24cq2hhf6y0apm5la0cz9yrp6fw-grafana-provisioning/datasources/datasource.yaml
apiVersion: 1
datasources:
- access: proxy
  assertions:
  - assertion: true
    message: 'The option definition `basicAuthPassword'' in  no longer has any effect;
      please remove it.

      `services.grafana.provision.datasources.settings.datasources.<name>.basicAuthPassword`
      has been removed
      in Grafana 9. Use `secureJsonData` instead.


      '
  - assertion: true
    message: 'The option definition `password'' in  no longer has any effect; please
      remove it.

      `services.grafana.provision.datasources.settings.datasources.<name>.password`
      has been removed

      in Grafana 9. Use `secureJsonData` instead.


      '
  editable: false
  isDefault: true
  name: prometheus
  secureJsonData: null
  type: prometheus
  uid: null
  url: localhost:9090
deleteDatasources: []
```
I have problem where `grafana` is creating 3 datasources from this, not sure if this is what causing it. (screenshot below)

### Expected behavior
The `datasources.assertions` shouldn't be there.

### Screenshots

![Screenshot from 2023-04-04 17-11-06](https://user-images.githubusercontent.com/13085918/229760508-cc61363f-0ca0-4008-897c-f30f8f7af97c.png)

### Additional context

This is the code where the data is being parsed: https://github.com/NixOS/nixpkgs/blob/53dad94e874c9586e71decf82d972dfb640ef044/nixos/modules/services/monitoring/grafana.nix#L16-L26

### Notify maintainers

@KFearsoff @Ma27 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05.20230402.7c65685`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by budimanjojo** [comment]
Seems like the duplicated datasources in the screenshot is not caused by this, it was my mistake and those were created when I was playing with the interface

**Comment by Shawn8901** [comment]
Sounds a bit like https://github.com/NixOS/nixpkgs/issues/211060 to me

**Comment by budimanjojo** [comment]
Yeah that's exactly the problem. Should this be closed for duplicate?
