### ISSUE TITLE
Package request: typst-fmt

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nixpkgs#224797]
**Project description**

Formatter for typst.

**Metadata**

* homepage URL: 
* source URL: https://github.com/astrale-sharp/typst-fmt/
* license: mit, bsd, gpl2+ , ...
* platforms: unix, linux, darwin, ...

**Comment by figsoda** [comment]
There is no CLI: https://github.com/astrale-sharp/typst-fmt/blob/dfffb0eaaf1c08b53e624144b930ca6368bf5319/cli/src/main.rs

**Comment by Freed-Wu** [comment]
Looks like the author use [wrong default branch](https://github.com/astrale-sharp/typst-fmt/branches).

**Comment by Freed-Wu** [comment]
@astrale-sharp

**Comment by astrale-sharp** [comment]
what do you mean wrong default branch?

Hi there, I wasn't sure there was interest for a cli, I'll merge the cli in a few days, want a ping then?

**Comment by astrale-sharp** [comment]
I merged my change, it should be good to package!

**Comment by Freed-Wu** [comment]
@astrale-sharp has renamed the project from typst-fmt to typstfmt in <https://github.com/astrale-sharp/typstfmt/pull/45#issuecomment-1636768986>.

**Comment by figsoda** [comment]
#243760
