### ISSUE TITLE
Improve search quality

### ISSUE THREAD

**Issue by csjab** [NixOS/nixpkgs#224734]
## Issue description

An existing package named like "foo-bar" is not returned as a result of searching for "foo_bar", and vice versa.

### Steps to reproduce

Examples:
* [Search for "zookeeper-mt"](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=zookeeper-mt) gives no results, even though [there is a "zookeeper_mt" package](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=zookeeper_mt)

* [Search for "reorder_python_imports"](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=reorder_python_imports) gives no results, even though [there is a "reorder-python-imports" package](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=reorder-python-imports)

**Comment by alyssais** [comment]
This issue probably belongs over at https://github.com/NixOS/nixos-search.

**Comment by csjab** [comment]
Thanks, moved to https://github.com/NixOS/nixos-search/issues/644.
