### ISSUE TITLE
python310Packages.openmm: causes ImportError when imported before other modules

### ISSUE THREAD

**Issue by mcwitt** [NixOS/nixpkgs#224831]
### Describe the bug
Importing `openmm` before other packages with C extensions results in `ImportError` with

> version \`GLIBCXX_3.4.30' not found`.

when the latter package is imported.

### Steps To Reproduce

In nixpkgs tree, on master:

```shell
nix-shell -E 'with import ./. {}; (python3.withPackages (ps: [ps.openmm ps.scipy])).env' --command 'python -c "import openmm; from scipy import optimize"'
```

results in

```
ImportError: /nix/store/i3vm9g088s7d75yl3z39flhbmmqav6ms-gfortran-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/c13gjqp3d29wks54xvg6w4hmns8djpby-python3-3.10.10-env/lib/python3.10/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-310-x86_64-linux-gnu.so)
```

Note: this does not occur if the import order is switched:

``` shell
nix-shell -E 'with import ./. {}; (python3.withPackages (ps: [ps.openmm ps.scipy])).env' --command 'python -c "from scipy import optimize; import openmm"'
```

does not result in an error.

Scipy is used as an example, but this also occurs when importing other packages with C extensions after openmm (e.g. rdkit):

```shell
nix-shell -E 'with import ./. {}; (python3.withPackages (ps: [ps.openmm ps.rdkit])).env' --command 'python -c "import openmm; from rdkit import Chem"'
```

### Expected behavior
The above commands should not result in `ImportError`s.

### Additional context
Seems likely to be a result of overriding `stdenv` and `gfortran` to use GCC 11 in https://github.com/NixOS/nixpkgs/pull/218757

(Removing these overrides results in a build failure with `internal compiler error`, so maybe not easy to fix..)

### Notify maintainers

@sheepforce 

### Metadata

- system: `"x86_64-linux"`
- host os: `Linux 5.15.105, NixOS, 22.11 (Raccoon), 22.11.20230401.884e3b6`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.11.1`
- channels(matt): `""`
- channels(root): `"nixos, nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by sheepforce** [comment]
I am afraid it is the override of stdenv and gfortran. The override became necessary due to https://github.com/NixOS/nixpkgs/pull/217481 and https://github.com/NixOS/nixpkgs/issues/216577 and I am afraid for the moment I cannot fix both this issue and #216577 until the upstream problems are gone.

However, #216577 only hits you if you compile the OpenCL kernels, so if disabling OpenCL in OpenMM is an option for you, you should be able to use plain `stdenv` and `gfortran` and work around the python import issue.
