### ISSUE TITLE
Firefox uses incorrect mouse cursor in Wayland sessions in KDE Plasma 5.27.3

### ISSUE THREAD

**Issue by xfix** [NixOS/nixpkgs#224860]
### Describe the bug
In NixOS unstable, Firefox uses incorrect mouse cursor in Wayland sessions within KDE Plasma 5.27.3. This problem doesn't happen on NixOS stable.

In HiDPI sessions the mouse cursor shown in Firefox doesn't scale resulting in a tiny cursor.

### Steps To Reproduce
1. Install Plasma
2. Boot into KDE Wayland session
3. Start Firefox
4. Look at the mouse cursor within Firefox session

### Expected behavior
Firefox should be using the same mouse cursor as rest of the system.

### Screenshots
![](https://user-images.githubusercontent.com/1297598/230183243-617c09fa-e12f-4a05-a991-6d83b988d150.png)

Above: mouse cursor as seen in Firefox, below: mouse cursor outside of Firefox.

### Additional context
This problem doesn't occur in Wayland session on NixOS stable or Fedora Linux running KDE Plasma 5.27.3 in Wayland session.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9, NixOS, 23.05 (Stoat), 23.05pre470275.53dad94e874`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos, nixos-hardware"`
 - channels(xfix): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by thall** [comment]
isn't this a duplicate of https://github.com/NixOS/nixpkgs/issues/207339?

**Comment by xfix** [comment]
Appears to be the case, closing.
