### ISSUE TITLE
apptainer Cannot open pixbuf loader module file

### ISSUE THREAD

**Issue by yswtrue** [NixOS/nixpkgs#224828]
### Steps To Reproduce
1. install apptainer 
2. build apptainer with `gtk dialog` app
3. open `gtk dialog`
4. and get this error `(nw:1054484): GdkPixbuf-WARNING **: 22:46:39.437: Cannot open pixbuf loader module file '/nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache': No such file or directory`

### Expected behavior
can open `gtk dialog` directly

### Additional context
```
apptainer exec -B /run wechat-web-devtools.sif /opt/apps/github.cytle.wechat-web-devtools/files/bin/wechat-devtools                   gdk-pixbuf 

(nw:1054484): Gtk-WARNING **: 22:46:35.594: Unknown key gtk-overlay-scrolling in /home/yswtrue/.config/gtk-3.0/settings.ini

(nw:1054484): GdkPixbuf-WARNING **: 22:46:35.598: Cannot open pixbuf loader module file '/nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache
to make things work again for the time being.
Gtk-Message: 22:46:35.615: Failed to load module "colorreload-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[1054535:1054535:0405/224636.208233:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[1054540:1054543:0405/224637.055668:ERROR:cert_verify_proc_builtin.cc(559)] No net_fetcher for performing AIA chasing.

(nw:1054484): Gtk-WARNING **: 22:46:39.437: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(nw:1054484): GdkPixbuf-WARNING **: 22:46:39.437: Cannot open pixbuf loader module file '/nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache
to make things work again for the time being.

(nw:1054484): Gtk-WARNING **: 22:46:39.437: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
fish: Job 1, 'apptainer exec -B /run wechat-w…' terminated by signal SIGABRT (Abort)
```

### Notify maintainers

@jbedo @ShamrockLee 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05.20230330.e3652e0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/fb5ci6653i73gr10by36bxg2f5v69lwf-source`
```

**Comment by ShamrockLee** [comment]
Sorry for the trouble.

To reproduce the issue, I would like to know how you build the image. Is there a way to reproduce it with tools inside Nixpkgs?

**Comment by yswtrue** [comment]
Hello,
  This is the build source [r2.yswtrue.com/apptainer.tar.gz](r2.yswtrue.com/apptainer.tar.gz). And I build with `build wechat-web-devtools.sif wechat-web-devtools.def` and run with `apptainer exec -B /run wechat-web-devtools.sif /opt/apps/github.cytle.wechat-web-devtools/files/bin/wechat-devtools`
and then click the `import`
![image](https://user-images.githubusercontent.com/1270490/230145149-3d59942c-2990-4d60-93f1-d001dc6f6bee.png)
then the app will crash.

**Comment by yswtrue** [comment]
I use the same build script works with x11docker, but not work with apptainer.

**Comment by ShamrockLee** [comment]
Which platform did you run the image on?

> This is the build source [r2.yswtrue.com/apptainer.tar.gz](r2.yswtrue.com/apptainer.tar.gz).

For people trying to get the file, it is at https://r2.yswtrue.com/apptainer.tar.gz , inside which include the Apptainer/Singularity definition file and files to be copied into the image with the `%files` section. The directory hierarchy is:

```
$ tree -a
.
├── keyrings
│   ├── appstore.gpg
│   └── deepin-archive-keyring.gpg
├── wechat-web-devtools.def
└── xdg-open

1 directory, 4 files
```

The content of `wechat-web-devtools.def` is:
```singularity
Bootstrap: docker
From: debian:buster

%post
  apt update
  apt install ca-certificates -y
  cat <<EOF > /etc/apt/sources.list
deb [by-hash=force] https://community-packages.deepin.com/deepin/ apricot main contrib non-free
deb https://com-store-packages.uniontech.com/appstore deepin appstore
EOF
  apt update
  dpkg --add-architecture i386
  apt install -y --no-install-recommends locales procps x11-utils socat file python2
  echo 'zh_CN.UTF-8 UTF-8' > /etc/locale.gen
  locale-gen
  apt install -y --install-recommends github.cytle.wechat-web-devtools
  DEBIAN_FRONTEND=noninteractive apt install -y fonts-wqy-microhei libglib2.0-0 libnss3 libgdk-pixbuf2.0-0 libgconf-2-4 libxss1 libasound2 libatk1.0-0 libcups2 libdrm2 xorg gtk+3.0
  rm -rvf /usr/share/icons/Adwaita
  find /var/lib/apt/lists -type f -delete
  find /var/cache -type f -delete
  find /var/log -type f -delete
  find /usr/share/doc -type f -delete
  find /usr/share/man -type f -delete
  find /usr/share/locale -type f -delete

%environment
  export DEBIAN_FRONTEND=noninteractive
  export GTK_IM_MODULE="fcitx"
  export XMODIFIERS="@im=fcitx"
  export QT_IM_MODULE="fcitx"
  export LANG=zh_CN.UTF-8
  export LANGUAGE=zh_CN.UTF-8
  export LC_ALL=zh_CN.UTF-8
  export LANG=zh_CN.UTF-8
  export TZ=UTC-8

%files
  keyrings/deepin-archive-keyring.gpg /etc/apt/trusted.gpg.d/
  keyrings/appstore.gpg   /etc/apt/trusted.gpg.d/
  xdg-open /usr/bin/
```

**Comment by yswtrue** [comment]
I am running on x86_64 nixos

**Comment by ShamrockLee** [comment]
Just went through the warning again. I guess it's caused by `/nix/store` not being mounted. A quick fix might be `--bind /nix/store`. I haven't test it yet.

Apptainer (Singularity) automatically binds several directories including `$PWD` and `$HOME`, but `/nix/store` is apparently not one of them. The second line of the error message

```
(nw:1054484): GdkPixbuf-WARNING **: 22:46:35.598: Cannot open pixbuf loader module file '/nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache': No such file or directory
```

suggests that a file `/nix/store/pc2pasl8bbb6ff5mf7vfjzpii2mvg996-gdk-pixbuf-loaders.cache`, which is a Nix store path, is missing. The program must have seen it somewhere (probably inside a configuration in your home directory or current working directory) but couldn't find it. Since the guest system is Debian, it should be safe to just bind the store.

The configuration functionality of the `programs.singularity` NixOS module hasn't been implemented yet. I encountered #200744 during the development.

**Comment by yswtrue** [comment]
And I get this error, can you help me to fix this problem?
```
(nw:2659441): Gtk-WARNING **: 17:11:33.092: Unknown key gtk-overlay-scrolling in /home/yswtrue/.config/gtk-3.0/settings.ini
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/dznrcc1ih3ww41nfiykwm67dxn0365j5-gvfs-1.50.3/lib/gvfs/libgvfscommon.so)
Failed to load module: /nix/store/dznrcc1ih3ww41nfiykwm67dxn0365j5-gvfs-1.50.3/lib/gio/modules/libgioremote-volume-monitor.so
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/dznrcc1ih3ww41nfiykwm67dxn0365j5-gvfs-1.50.3/lib/gio/modules/libgvfsdbus.so)
Failed to load module: /nix/store/dznrcc1ih3ww41nfiykwm67dxn0365j5-gvfs-1.50.3/lib/gio/modules/libgvfsdbus.so

(nw:2659441): Gtk-WARNING **: 17:11:33.109: Theme parsing error: gtk.css:3376:25: 'font-feature-settings' is not a valid property name
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2659488:2659488:0406/171133.866014:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[2659493:2659497:0406/171134.693044:ERROR:cert_verify_proc_builtin.cc(559)] No net_fetcher for performing AIA chasing.

(nw:2659441): Gtk-WARNING **: 17:11:36.427: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/current-system/sw/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /nix/store/0gpxzb4044hqgrcpshpgaxn2asi2ykdb-librsvg-2.55.1/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /nix/store/0gpxzb4044hqgrcpshpgaxn2asi2ykdb-librsvg-2.55.1/lib/librsvg-2.so.2) (gdk-pixbuf-error-quark, 5)
Cannot upload crash dump: cannot exec /usr/bin/wget

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
fish: Job 1, 'apptainer exec -B /nix/store -B…' terminated by signal SIGABRT (Abort)

```

**Comment by ShamrockLee** [comment]
> ```singularity
>   rm -rvf /usr/share/icons/Adwaita
> ```

Why do you delete the icon directory?
Just spent at least two hours `apt search`-ing the packages, `find`-ing the icons and browsing SO, but almost missed out the file-deletion lines in the %post section.

How about trying to comment out some of those file-deleting commands and see if it solves the issue?

**Comment by ShamrockLee** [comment]
I solve the problem. It's the XDG_DATA_DIRS environment variable.

After commenting out the above-mentioned file deletion commands, the error message becomes
```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: 无法识别的图像文件格式 (gdk-pixbuf-error-quark, 3)
```
which means `Unrecognized image file format`.

After some web searching, I saw some articles mentioning the environment variable XDG_DATA_DIRS, which also appears often in Nixpkgs code and issues.

https://askubuntu.com/questions/1351607/gtk-warning-could-not-load-a-pixbuf-from-icon-theme

In POSIX environment following FHS, the XDG_DATA_DIRS is usually set to `/usr/local/share:/usr/share`. But as you might have heard, Nix doesn't follow FHS, so the related variables are set otherwise, and that somewhat affects the guest system inside the container (probably through some configuration files or rc files inside the home directory). This can be verified by running

```sh
apptainer exec wechat-web-devtools.sif bash -c "echo \$XDG_DATA_DIRS"
```

Now, enter the shell by
```sh
apptainer exec wechat-web-devtools.sif bash
```
and
```console
Apptainer> XDG_DATA_DIRS=/usr/local/share:/usr/share
Apptainer> export XDG_DATA_DIRS
Apptainer> /opt/apps/github.cytle.wechat-web-devtools/files/bin/wechat-devtools
```

and voilà! A GUI app that can open the file selector without crashing.

So forget about `--bind /nix/store`. Just add

```singularity
%environment
    XDG_DATA_DIRS=/usr/local/share:/usr/share
```
to the def file, and you're good to go!

**Comment by yswtrue** [comment]
Thank you for helping me to fix this problem.
And I don't why I have a `GDK_PIXBUF_MODULE_FILE` env and I have to unset this env and then set `XDG_DATA_DIRS` this works now.

**Comment by yswtrue** [comment]
I haven't met this memory leak, I will try to run it for a few hours, and then check if this happens on my computer.
