### ISSUE TITLE
Some Linux games on Steam not working

### ISSUE THREAD

**Issue by joelmo** [NixOS/nixpkgs#22493]
## Issue description

This weekend I tried these games, all deadlocked in the menu or character selection.
- Nyheim
- Oh...Sir! The Insult Simulator
- Reigns
- Unturned (free to play)

You don't have to be worried to waste money in case you want to test a game. I have had no problem when requesting refunds, just go to https://help.steampowered.com/en/.

I have played these games and found no issues with them:
- Dota 2
- Counter-Strike
- TIS-100
- World of goo
- Faster Than Light
- You Must Build a Boat
- Risk of Rain

## Technical details

* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
17.03pre99759.f66d782 (Gorilla)

* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.11.6

* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"17.03pre99759.f66d782"

* Integrated graphics card, `lspci | grep -i vga`
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)

**Comment by nathanielbaxter** [comment]
This is normal with steam on nixos unfortunately. There are many steam games that don't work for various reasons, unfortunately many linux steam game developers only make sure their games *run* on ubuntu and don't really care about relying only on dependencies from the steam runtime. Some games don't play nice with certain graphics cards or drivers as well.

If you want to get a particular game working (I can list >150 games that work under nixos with nvidia card and drivers at least) then you'll need to do some work, or at least post any relevant logs from the game/steam so people can actually help you solve the problem. That is assuming that they own the game. :)

**Comment by Baughn** [comment]
There's a slowly-growing list of extra dependencies in the Steam package. If you can figure out what's missing, you can add it there; e.g. as in https://github.com/NixOS/nixpkgs/commit/70e4eab55b103207e42ae252ecd2683d7d9406eb

**Comment by abbradar** [comment]
I don't have enough motivation to actually buy games for the sole purpose of fixing them and then refunding, sorry. Nevertheless, I'm happy to help if you can post logs and/or `strace -e trace=file`s -- those two are the most helpful for determining FHS-related problems.
