### ISSUE TITLE
Add RAP support to our grsecurity kernel

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#22494]
I think we're fairly uniquely suited to doing this (among security-oriented distros) because we can compile with a patched GCC comparatively easily. See the recent announcement on https://grsecurity.net/rap_announce_ret.php

cc @joachifm

**Comment by copumpkin** [comment]
Actually, looking more carefully, I'm not sure it's in the non-commercial release yet. Would still be cool if it was 😄

**Comment by NeQuissimus** [comment]
It says it is included in the "test" patch, which is the non-commercial one, is it not?

**Comment by joachifm** [comment]
RAP has always been enabled, to the extent that it has been available in the test patch. Looks like we'll now get a better version (but still not as good as the commercially available one ...)

**Comment by joachifm** [comment]
That is, we'll get the "deterministic type-based return check portion" of RAP, which I think was previously only available to commercial users (at least that's how I've interpreted the language in the old RAP docs, which made it sound like the free version was somehow inferior or incomplete compared to commerical offerings).
