### ISSUE TITLE
blackd not working: "aiohttp dependency is not installed"

### ISSUE THREAD

**Issue by Brawl345** [NixOS/nixpkgs#224991]
### Describe the bug
The Python formatter "black" has a daemon binary called "blackd" that doesn't run. Seems like this was an issue in 2019 before: #53890

I am on macOS aarch64.

### Steps To Reproduce
1. `nix shell nixpkgs#black`
2. `blackd`
3. Error is shown:

```
Traceback (most recent call last):
  File "/nix/store/966nkwsm9yl7sdk7r2m5mrp37y1vlpmn-python3.10-black-23.1.0/bin/.blackd-wrapped", line 6, in <module>
    from blackd import patched_main
  File "/nix/store/966nkwsm9yl7sdk7r2m5mrp37y1vlpmn-python3.10-black-23.1.0/lib/python3.10/site-packages/blackd/__init__.py", line 14, in <module>
    raise ImportError(
ImportError: aiohttp dependency is not installed: No module named 'aiohttp'. Please re-install black with the '[d]' extra install to obtain aiohttp_cors: `pip install black[d]`
```

### Expected behavior
Black daemon should run

### Notify maintainers

Should be @sveitser or @autophagy?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.4.0, macOS 13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/store/w31p8y3w048ijfxc6ikg6hg2clb45hk4-source`
```

**Comment by Brawl345** [comment]
Ah I see, thanks for the tip! Your command does not work, same error. But this works:

```
nix-shell -p 'python3.withPackages (pkgs: [ pkgs.black ] ++ pkgs.black.optional-dependencies.d)'
```

And I can successfully use this in my home.packages :)

**Comment by Brawl345** [comment]
@nhooey I have this in my home-manager config:

```nix
{ pkgs, ... }:

{
  home.packages = [
    (pkgs.python3.withPackages (ps: with ps; [ black ] ++ pkgs.black.optional-dependencies.d))
  ]
}
```

Do you mean this?

**Comment by nhooey** [comment]
@Brawl345: I guess so. How would that co-exist with the rest of the `home.packages` value?

**Comment by Brawl345** [comment]
@nhooey The whole python3 expression needs to be inside brackets, just add the rest to the list:

```nix
{ pkgs, ... }:

{
  home.packages = [
     pkgs.ffmpeg
     pkgs.fq
     pkgs.somepackage
     (pkgs.python3.withPackages (ps: with ps; [ black ] ++ pkgs.black.optional-dependencies.d))
     pkgs.rclone
     pkgs.someotherpackage
  ]
}
```

See also: https://nixos.wiki/wiki/Nix_by_example#Lists

**Comment by jduan-highnote** [comment]
@Brawl345 is there a way to install `blackd` so I can use it from my regular shell instead of nix-shell? Thanks!

**Comment by Brawl345** [comment]
@jduan-highnote Depends on how you use and installed Nix/how you manage your config. I use home-manager with nix-darwin on my Mac for example and my config above makes it available to my normal shell. Should also work on Linux & NixOS via e.g. home-manager.

**Comment by jduan-highnote** [comment]
@Brawl345 thanks for your response! I don't have use home manager. I use plain old nix-env :). Let me ask a question in the forum.
