### ISSUE TITLE
Package request: llama.cpp

### ISSUE THREAD

**Issue by MostAwesomeDude** [NixOS/nixpkgs#224921]
[llama.cpp](https://github.com/ggerganov/llama.cpp) is a popular harness for LLaMA-derived large language models.

I'll probably make a bit of work towards getting this packaged, but I bet that somebody else has already gotten started. I'm just making the issue for visibility.

I would recommend that folks work on several distinct pieces, rather than trying to do this all in one go:

* Package the main `llama.cpp` C++ binaries
* Add in the extra `llama.cpp` Python scripts
* Write a shell script which does the model conversion routines listed in the `llama.cpp` readme
* Ask a neighbor to get the hashes for the models, so that we can add fixed-output derivation hashes to nixpkgs

I can do this final step, or any neighbor which uses e.g. [magnetico](https://boramalper.org/labs/magnetico/) can search for "llama" to find the magnet links and compute the hashes.

**Metadata**

* homepage URL: https://github.com/ggerganov/llama.cpp
* source URL: https://github.com/ggerganov/llama.cpp
* license: MIT
* platforms: Linux, Darwin

**Comment by dit7ya** [comment]
@MostAwesomeDude the linked PR adds support for first two of the bullets. Please let me know what you think.

**Comment by MostAwesomeDude** [comment]
Looks great! Thanks for your hard work.

**Comment by prusnak** [comment]
As per comments in https://github.com/NixOS/nixpkgs/pull/225058 the pace of development of llama.cpp is incredible. Moreover the upstream provides well maintained `flake.nix` file, so it should be trivial to use that instead of nixpkgs.

**Comment by Freed-Wu** [comment]
Hey, does anyone know how to allow user to decide if they can use cuda? In `default.nix`, we can

```nix
{ lib, pkgs, cuda ? true }:
pkgs.stdenv.mkDerivation
{
  ...
}
```

Then user can override it. How to provide similar choice in `flake.nix`?

**Comment by MostAwesomeDude** [comment]
@Freed-Wu When you import `nixpkgs`, you can configure CUDA support. Try:

```nix
pkgs = import nixpkgs {
  inherit system;
  config = {
    allowUnfree = true;
    cudaSupport = true;
  };
};
```
