### ISSUE TITLE
furtherance breaks on startup

### ISSUE THREAD

**Issue by mradke** [NixOS/nixpkgs#225010]
### Describe the bug
When trying to run the furtherance time tracker the application crashes with:

```
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', /build/furtherance-1.6.0-vendor.tar.gz/gtk4/src/subclass/widget.rs:1305:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps To Reproduce
1. Run furtherance from the unstable channel: `nix-shell -p furtherance --run "furtherance"`

### Expected behavior
I expected the application to start.

### Screenshots
n/a

### Additional context
This seems to be a problem with multiple gtk-rs applications at the moment. I think this is basically a duplicate of #219216 or #216770 but if I'm understanding it correctly the issue has to be addressed in each application separately.

### Notify maintainers

@CaptainJawZ 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.9, NixOS, 22.11 (Raccoon), 22.11.3535.799d153e4f3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(radke): `""`
 - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11, nixos-unstable"`
```

**Comment by CaptainJawZ** [comment]
I'll try to fix it this weekend, thank you for such a detailed report!

**Comment by mradke** [comment]
I think the source of the problem is described here: https://github.com/NixOS/nixpkgs/pull/217069/files

> The fix is to upgrade gtk-rs to >= 0.5.3.

Since lakoliu upgraded the version upstream 3 weeks ago (see https://github.com/lakoliu/Furtherance/commit/dff62a9e31ff85305eb2d70b036ee25c90e4feeb) I think we just have to bump the version to 1.7 and we should be golden :-)

(I just tested it, and at least locally, I got it working by just swapping out the version number and sha hashes)

**Comment by CaptainJawZ** [comment]
pull request is up, thanks for your suggestions!
thankfully it was an easy fix, sorry for the delay, it was holiday in my country.
https://github.com/NixOS/nixpkgs/pull/225656

**Comment by mradke** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/230249
Thanks for the great response :-)
