### ISSUE TITLE
wakeonlan perl exec format error on darwin

### ISSUE THREAD

**Issue by chrisportela** [NixOS/nixpkgs#225024]
### Describe the bug
Running `wakeonlan` on M1 MBP gets `exec format error`.

### Steps To Reproduce
1. `nix shell nixpkgs#wakeonlan`
2. `wakeonlan`

```
chris.portela@mbp ~ % wakeonlan
zsh: /nix/store/a15y23s1dy8yi2m7c9b0pzns9886rvan-perl5.36.0-wakeonlan-0.42/bin/wakeonlan: bad interpreter: /nix/store/3w3wskm2bc00rs5md7wqqwpw2vx4516q-perl-5.36.0/bin/perl -w -I/nix/store/3w3wskm2bc00rs5md7wqqwpw2vx4516q-perl-5.36.0/: exec format error
```

### Expected behavior
Text documenting the command

### Additional Information
[It seems like a previous PR fixed this by making the shebang shorter on Darwin which also requires disabling checks on Darwin.](https://github.com/NixOS/nixpkgs/pull/216259)

### Notify maintainers
@SuperSandro2000

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
chris.portela@mbp ~ % nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.4.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `not found`
```

**Comment by SuperSandro2000** [comment]
Sounds like https://github.com/NixOS/nixpkgs/blob/3cde9b5e4dbc83ea6ac3e9ff4fde8784a49eb5cb/doc/languages-frameworks/perl.section.md#:~:text=by%20calling%20the-,shortenperlshebang,-function%20from%20the
