### ISSUE TITLE
Build failure: nix-template-rpm

### ISSUE THREAD

**Issue by ulysses4ever** [NixOS/nixpkgs#225096]
### Steps To Reproduce

1. build `nix-template-rpm`. In this case I used:

```console
❯ NIXPKGS_ALLOW_INSECURE=1 nix shell nixpkgs#nix-template-rpm --impure
```

### Build log

```console
error: builder for '/nix/store/0ywrk5i0pki89ychl9mpynalxry38zy3-python2.7-toposort-1.10.drv' failed with exit code 1;
       last 10 log lines:
       > pythonRemoveBinBytecodePhase
       > pythonImportsCheckPhase
       > Executing pythonImportsCheckPhase
       > Check whether the following modules can be imported: toposort
       > Traceback (most recent call last):
       >   File "<string>", line 1, in <module>
       >   File "<string>", line 1, in <lambda>
       >   File "/nix/store/q5cd2idrc3fwiq1kjib6znzjzndzcm93-python-2.7.18.6/lib/python2.7/importlib/__init__.py", line 37, in import_module
       >     __import__(name)
       > ImportError: No module named toposort
       For full logs, run 'nix log /nix/store/0ywrk5i0pki89ychl9mpynalxry38zy3-python2.7-toposort-1.10.drv'.
error: 1 dependencies of derivation '/nix/store/m2s1fylaq86rva6kjf9xi53zh27k9379-nix-template-rpm-0.1.drv' failed to build
```

### Notify maintainers

None

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05.20230403.53dad94`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.14.1`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/fb5ci6653i73gr10by36bxg2f5v69lwf-source`
```

**Comment by MaxHearnden** [comment]
https://github.com/MaxHearnden/nixpkgs/commit/5618660b323416de55485d1659deec5d490d3e44 could fix the issue, however I used 2to3 and I am not sure of the quality of the resulting code.

**Comment by ulysses4ever** [comment]
@MaxHearnden thanks, would love to see it ported upstream! For a total NixOS noob: is there a quick way I could try your version locally?

**Comment by MaxHearnden** [comment]
if you are okay with flakes, try running `nix shell github:MaxHearnden/nixpkgs/5618660b323416de55485d1659deec5d490d3e44#nix-template-rpm`
or you could clone the nix-template-rpm branch locally from my repository at github.com/MaxHearnden/nixpkgs and run `nix-shell -p nix-template-rpm -I nixpkgs=.` from the git repository

**Comment by katexochen** [comment]
Closing, as package was removed.
