### ISSUE TITLE
Investigate building parallel gcc for stdenv bootstrap

### ISSUE THREAD

**Issue by alexanderkjeldaas** [NixOS/nixpkgs#2251]
The NixOS stdenv boostrap is slow due to building a profiledbootstrap gcc in serial.

There is a gcc bug where the wrong bootstrap compiler is used in the standard 3-stage bootstrap process.  This should hopefully be fixed in a new gcc release.

http://gcc.gnu.org/bugzilla/show_bug.cgi?id=59528

Another option is to look at using a 4-stage bootstrap.  I could not get a clear answer on whether a 4-stage bootstrap works with profile feedback.  It should be much faster to build a parallel 4-stage bootstrap than a serial 3-stage bootstrap.

**Comment by Profpatsch** [comment]
(triage) Is that still an issue?

**Comment by zimbatm** [comment]
Speeding up the boostrap time is a good idea but doesn't happen for most people. It's probably best addressed in a PR if someone wants to tackle the problem as a goal.
