### ISSUE TITLE
Update request: python3Packages.et_xmlfile 1.0.1 → 1.1.0

### ISSUE THREAD

**Issue by SamLukeYes** [NixOS/nixpkgs#225154]
- Package name: et_xmlfile
- Latest released version: 1.1.0

- Current version on the unstable channel: 1.0.1
- Current version on the stable/release channel: 1.0.1

- [X] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@symphorien 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by symphorien** [comment]
Looks like I'm not the maintainer of this package, but if you make a PR updating it feel free to ping me for review.
