### ISSUE TITLE
Boogie is broken on darwin

### ISSUE THREAD

**Issue by layus** [NixOS/nixpkgs#22519]
## Issue description

The status of Hydra job ‘nixpkgs:trunk:dotnetPackages.Boogie.x86_64-darwin’ is "Failed".  For details, see https://hydra.nixos.org/build/47914149.

The following dependent job also failed: nixpkgs:trunk:dafny.x86_64-darwin (https://hydra.nixos.org/build/47912762)

Apparently the builder (mono?) cannot find libgdiplus when it needs it. I have no way to debug this on darwin, so any help would be useful. The straightforward solution is to disable boogie on darwin.

/cc @taktoa, any idea ?

**Comment by taktoa** [comment]
I don't have a way to test Boogie on Darwin either, @vbgl was the one who claimed that it would build on Darwin.

**Comment by vbgl** [comment]
Fixed by 3a526deaeeb7a83dae6e4a3c2a4cddcb776b3985

See http://hydra.nixos.org/eval/1329797#tabs-now-succeed.

**Comment by layus** [comment]
Excellent! Thank you for your fast response :)
