### ISSUE TITLE
Installation of proprietary software

### ISSUE THREAD

**Issue by frigatefreedom** [NixOS/nixpkgs#22517]
## Issue description

Maybe it's very silly question, but I can't handle it myself.

I'm trying to install ANSYS at my laptop. If just run INSTALL script, it says, that can't find df.

I tried to create FHS environment using example for Android from Wiki (https://nixos.org/wiki/FHS_environments), but installer can't see any software installed at /bin and /usr/bin.

Tried to provide PATH to /usr/bin, but it didn't help.

## Technical details

* System: NixOS: 17.03pre99759.f66d782 (Gorilla)
* Nix version: 1.11.6
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)

**Comment by abbradar** [comment]
Try using `steam-run` -- it gives fairly close environment to the one used by Steam for games which is often also good enough for various proprietary applications. Install it:

```
environment.systemPackages = [ (steam.override { nativeOnly = true; newStdcpp = true; }).run ];
```

, where `nativeOnly` sets it to use native NixOS libraries instead of pre-built Steam ones, and `newStdcpp` pulls new C++ ABI. Use:

```
> steam-run ./proprietary-binary
```

**Comment by frigatefreedom** [comment]
@abbradar Thanks! Seems, that everything works properly.

**Comment by bugaev** [comment]
@frigatefreedom Could you please describe in more detail how you managed to install ANSYS?

I manage to start their InstallShield, but cannot proceed further - it complains that it cannot find JRE.

This is what I do:
`steam-run bash`
`ANS_IGNOREOS=true JAVA_HOME=/usr/lib/openjdk ./install -is:javahome /usr/libopenjdk/`

My relevant piece of configuration.nix: 
`environment.systemPackages = with pkgs; [
    (steam.override {
    nativeOnly = true;
    extraPkgs = pkgs: [ bc openjdk xpdf ];
    }).run ]`
