### ISSUE TITLE
Darwin `strip` is evil and can modify files even if they aren't valid Mach-O

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixpkgs#22520]
I just spent some time tracking down a super weird bug because the standard `fixupPhase` was corrupting a .class file. Turns out that if you run `strip -S` in `cctools` against a .class file, it'll complain that it's not a valid Mach-O file but flip the endianness of the magic number at the start of the file anyway, thus making it an invalid Java class file.

This will hurt us if we ever package things that contain raw class files not in jars.

Mostly leaving this as a reminder for myself to fix, but if someone else wants to look into it, please do!

**Comment by vcunat** [comment]
Maybe #15339.

**Comment by mmahut** [comment]
Are there any updates to this issue, please?

**Comment by prusnak** [comment]
No reaction. Closing. Please reopen if needed.
