### ISSUE TITLE
Curl: (7) Failed to connect to samba.org port 80

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixpkgs#22527]
## Issue description
I am unable to build openjdk from source. Nix build process fails to download
http://samba.org/ftp/pub/samba/stable/samba-4.5.3.tar.gz
The same fails with wget as well. However the same link with https works. How to update the above script or is there some way to redirect automatically to https if fails?

### Steps to reproduce
55 $ nix-env -iA nixpkgs.openjdk
installing ‘openjdk-8u121b13’
these derivations will be built:
  /home/royadav/opt/nix/store/1b4815k53asxprfacss2p63zjhb07a6z-samba-4.5.3.tar.gz.drv
  /home/royadav/opt/nix/store/wvhpjwhcqx00nhf99qlsgrpk6m4w2khs-talloc-2.1.8.tar.gz.drv
  /home/royadav/opt/nix/store/vxyd504x4x9mm9l3nq1j3gi78f1gl0h4-talloc-2.1.8.drv
  /home/royadav/opt/nix/store/9ligvipf14l40mx8przw0bqbf1flkqy9-samba-4.5.3.drv
  /home/royadav/opt/nix/store/w96v2jfxfa84w2l99cqx0jx02wcja9nf-gnome-vfs-2.24.4.drv
  /home/royadav/opt/nix/store/j8qhbdcwadswwbkbbhwp3jgjgjiiwhz8-openjdk-8u121b13.drv
building path(s) ‘/home/royadav/opt/nix/store/d31h70dzkr8wxsz6aiz60b8kf5hqr05k-samba-4.5.3.tar.gz’

trying http://samba.org/ftp/pub/samba/stable/samba-4.5.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to samba.org port 80: Connection refused

trying http://ftp.riken.jp/net/sambapub/samba/stable/samba-4.5.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: cannot download samba-4.5.3.tar.gz from any mirror
builder for ‘/home/royadav/opt/nix/store/1b4815k53asxprfacss2p63zjhb07a6z-samba-4.5.3.tar.gz.drv’ failed with exit code 1
cannot build derivation ‘/home/royadav/opt/nix/store/9ligvipf14l40mx8przw0bqbf1flkqy9-samba-4.5.3.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/home/royadav/opt/nix/store/w96v2jfxfa84w2l99cqx0jx02wcja9nf-gnome-vfs-2.24.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/home/royadav/opt/nix/store/j8qhbdcwadswwbkbbhwp3jgjgjiiwhz8-openjdk-8u121b13.drv’: 1 dependencies couldn't be built
error: build of ‘/home/royadav/opt/nix/store/j8qhbdcwadswwbkbbhwp3jgjgjiiwhz8-openjdk-8u121b13.drv’ failed

## Technical details
* System: Ubuntu 16.04
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "17.03pre100468.cd10e3c"
* Curl Version: 
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.10 libssh2/1.8.0 nghttp2/1.17.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy

**Comment by edolstra** [comment]
Hm, why does OpenJDK depend on Samba anyway? Looks like a bad case of dependency bloat.

**Comment by rowhit** [comment]
The fix worked. Nix is able to download and compile. However, it complains about number of pem files not matching at the end.
Below is the tail of the build log showing the issue.
=============================
/home/royadav/opt/nix/store/2cpgpp7srv20q020swkz90bhnjgf0zvn-openjdk-8u121b13-jre/lib/openjdk/jre/lib/security /tmp/nix-build-openjdk-8u121b13.drv-0/jdk8u-jdk8u121-b13
Number of .pem files produced does not match number of certs read from /home/royadav/opt/nix/store/z1647q87v1mrda1y02vjwd9bg0ypaq8g-nss-cacert-3.28.1/etc/ssl/certs/ca-bundle.crt. at /home/ro
yadav/opt/nix/store/fw0zb873ynjxlmi97yv5fawfx8xvxwjl-generate-cacerts.pl line 346.
170builder for ‘/home/royadav/opt/nix/store/x0l5gz4vpcw04llhllfs5wivj3pzpfmv-openjdk-8u121b13.drv’ failed with exit code 255
error: build of ‘/home/royadav/opt/nix/store/x0l5gz4vpcw04llhllfs5wivj3pzpfmv-openjdk-8u121b13.drv’ failed
