### ISSUE TITLE
Update request: onlyoffice-bin 7.2.0 → 7.3.3

### ISSUE THREAD

**Issue by Lord-Valen** [NixOS/nixpkgs#225249]
- Package name: onlyoffice-bin
- Latest released version: 7.3.3

- Current version on the unstable channel: 7.2.0
- Current version on the stable/release channel: 7.2.0

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@nh2
@GTrunSec 

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by deftdawg** [comment]
OnlyOffice 7.4.0 is out now  

It can be built with the following modifications, however the ability to install plugins such as `chatGPT` or `lang-tool` is not working with an error message (`failed to bind extensions`), not sure how to resolve that.

```diff
diff --git a/pkgs/applications/office/onlyoffice-bin/default.nix b/pkgs/applications/office/onlyoffice-bin/default.nix
index ba4a75ddfba..1b7709790a5 100644
--- a/pkgs/applications/office/onlyoffice-bin/default.nix
+++ b/pkgs/applications/office/onlyoffice-bin/default.nix
@@ -20,6 +20,7 @@
 , gst_all_1
 , gtk2
 , gtk3
+, libcef
 , libpulseaudio
 , libudev0-shim
 , libdrm
@@ -75,11 +76,11 @@ let
 in
 stdenv.mkDerivation rec {
   pname = "onlyoffice-desktopeditors";
-  version = "7.2.0";
+  version = "7.4.0";
   minor = null;
   src = fetchurl {
     url = "https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v${version}/onlyoffice-desktopeditors_amd64.deb";
-    sha256 = "sha256-O9gC/b5/eZ1YImuXpEZOJhI1rzCNuFrm5IqablnYo9Y=";
+    sha256 = "sha256-0UYqdU2XGhltRKbT2PURmlgnaAzwdcMAIZ7S8dEeQXk=";
   };
 
   nativeBuildInputs = [
@@ -104,6 +105,7 @@ stdenv.mkDerivation rec {
     gst_all_1.gstreamer
     gtk2
     gtk3
+    libcef
     libpulseaudio
     libdrm
     nspr
```

**Comment by deftdawg** [comment]
It looks as though plugins can still be manually installed, so perhaps is an issue with OnlyOffice being unable to download them into a temporary location

**Comment by deftdawg** [comment]
@nh2
@GTrunSec

Any thoughts on why the marketplace might be failing or updating onlyoffice-bin in general?
