### ISSUE TITLE
Package request: Spotube - a Flutter based lightweight Spotify client

### ISSUE THREAD

**Issue by Steinhagen** [NixOS/nixpkgs#225396]
**Project description**

Spotube is a [Flutter](https://flutter.dev/) based lightweight Spotify client. It utilizes the power of Spotify & Youtube's public APIs to create a reliable, robust & resource-light user experience.

**Metadata**

* homepage URL: https://spotube.netlify.app/
* source URL: https://github.com/KRTirtho/spotube
* license: BSD
* platforms: linux, darwin

**Comment by ocfox** [comment]
Duplicate #200120

**Comment by bjornfor** [comment]
See above.
