### ISSUE TITLE
Package request: audiobookshelf

### ISSUE THREAD

**Issue by ThatsNoMoon** [NixOS/nixpkgs#225337]
**Project description**

Audiobookshelf is a self-hosted podcast and audiobook server.

**Metadata**

* homepage URL: https://audiobookshelf.org
* source URL: https://github.com/advplyr/audiobookshelf
* license: GPL-3.0
* platforms: Linux

**Comment by pinn3** [comment]
This has already been packaged in https://github.com/NixOS/nixpkgs/pull/213265

It's available in the unstable channel

**Comment by ThatsNoMoon** [comment]
Ah, thanks! Should've checked.
