### ISSUE TITLE
Update request: heroic & heroic-unwrapped 2.6.2 → 2.7.0

### ISSUE THREAD

**Issue by bayazidbh** [NixOS/nixpkgs#225372]
- Package name: `heroic` `heroic-unwrapped`
- Latest released version: [2.7.0](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest)

- Current version on the unstable channel: [2.6.2](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=heroic)
- Current version on the stable/release channel: [2.4.3](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=heroic)

- [x] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+is%3Aopen+heroic)

**Notify maintainers**

@aidalgol 

Been five days, not sure if there will be a hotfix, but I guess in addition to bumping version to 2.7.0, should also remember to recheck in the next 5 days in case of hotfixes.

-----

Note for maintainers: Please tag this issue in your PR.

**Comment by aidalgol** [comment]
Blocked on #214952 (see [this comment](https://github.com/NixOS/nixpkgs/pull/214952#issuecomment-1498713830)).
