### ISSUE TITLE
Package request: python3*Packages.BCML

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nixpkgs#225486]
**Project description**
A cross platform mod loader for The Legend of Zelda: Breath of the Wild in CEMU.

**Metadata**

* homepage URL: https://github.com/NiceneNerd/BCML
* source URL: https://github.com/NiceneNerd/BCML
* license: GPL3+
* platforms: Windows, Linux

**Comment by lasers** [comment]
Maybe `U-King Mod Manager (UKMM)` should be made instead? [Final bugfix](https://github.com/NiceneNerd/BCML/releases/tag/v3.10.8)

> _**Setup and Use**_
> * Unlike BCML, setup is pretty much just download and unzip. For more details consult the Book.
> 
> _**Building from Source**_
> * Unlike BCML, building from source is easy.

**Comment by lasers** [comment]
Please test https://github.com/lasers/nixpkgs/tree/ukmm
