### ISSUE TITLE
fzf 0.39.0 missing runtime dependency bc

### ISSUE THREAD

**Issue by DanielSiepmann** [NixOS/nixpkgs#225579]
### Describe the bug
Installing and using fzf breaks with the following error message:

```
.nix-profile/bin/fzf-tmux: line 183: bc: command not found
```

### Steps To Reproduce
1. Install fzf with tmux integration, I did it via home manager modules
2. Call fzf with tmux integration within tmux

### Expected behavior
The tmux pop up appears with history to filter

### Notify maintainers

@Br1ght0ne @Ma27 @zowoq

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.105, NixOS, 23.05 (Stoat), 23.05pre470969.0e19daa510e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"nixos, nixos-hardware, phps"`
 - channels(daniels): `"home-manager, nixpkgs, phps"`
 - nixpkgs: `/home/daniels/.nix-defexpr/channels/nixpkgs`
```

Looks like this got introduced with https://github.com/NixOS/nixpkgs/pull/224377. The runtime dependency was added with that new version: https://github.com/junegunn/fzf/compare/0.38.0...0.39.0#diff-29747b0804ea04e1d230bd8651260a6b8687374cc1ae4c2d70ec26f05c4f719bR183 Line 183 of file `bin/fzf-tmux` I wasn't able to find a proper URL to link to that line within the diff.

**Comment by DanielSiepmann** [comment]
Workaround: Install `bc` as another package.

**Comment by DanielSiepmann** [comment]
@msfjarvis due to providing the update to 0.39.0 at https://github.com/NixOS/nixpkgs/pull/224377

**Comment by msfjarvis** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/237365, would be helpful if you could test it.

**Comment by DanielSiepmann** [comment]
Thanks @msfjarvis. I'm pretty new, is there any doc how I could test this on my machine?

**Comment by msfjarvis** [comment]
> Thanks @msfjarvis. I'm pretty new, is there any doc how I could test this on my machine?

If you're using Nix channels then you can replace your `nixpkgs` channel with `https://github.com/msfjarvis/nixpkgs/archive/refs/heads/hs/fix-fzf-tmux.tar.gz` and rebuild, which will build all your packages from my PR branch, including `fzf`.

If you're using Nix Flakes then you can change the nixpkgs input to be `github:msfjarvis/nixpkgs/hs/fix-fzf-tmux` which has the same effect.
