### ISSUE TITLE
qutebrowser will not launch

### ISSUE THREAD

**Issue by Soundtoxin** [NixOS/nixpkgs#22550]
## Issue description
qutebrowser does not launch

### Steps to reproduce
run 'qutebrowser' from a terminal or dmenu

## Technical details
/nix/store/dagn6yc6rdk5ccs4z0zmx9qw3g6gcq92-qutebrowser-0.8.2/bin/..qutebrowser-wrapped-wrapped: line 3: /nix/store/dagn6yc6rdk5ccs4z0zmx9qw3g6gcq92-qutebrowser-0.8.2/bin/..qutebrowser-wrapped-wrapped: Argument list too long
![quteproblemsarestillbad](https://cloud.githubusercontent.com/assets/3146494/22737728/f90978e4-edc9-11e6-8489-611351f76745.png)

* System: 17.03pre99759.f66d782 (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: "17.03pre99759.f66d782"

**Comment by FRidh** [comment]
cc @abbradar

**Comment by abbradar** [comment]
Strange; it works for me on 01fef3f7db4cc208faea31f26c9451b326058781 (current unstable channel); it has also worked before an update.

Can you show contents of `/nix/store/dagn6yc6rdk5ccs4z0zmx9qw3g6gcq92-qutebrowser-0.8.2/bin/..qutebrowser-wrapped-wrapped`?

**Comment by Soundtoxin** [comment]
` #! /nix/store/gabjbkwga2dhhp2wzyaxl83r8hjjfc37-bash-4.3-p48/bin/bash -e
export PATH=/nix/store/dahikpiipsk8qgih8y605czmn68vf4k0-python3-3.5.2/bin:/nix/store/dagn6yc6rdk5ccs4z0zmx9qw3g6gcq92-qutebrowser-0.8.2/bin:/nix/store/yfla    6in5zqjgl8z6aba6qrm5zp2g22hy-python3.5-setuptools-26.1.1/bin:/nix/store/qbh1zb3c2p2d7g1lv7m64zi0pz3l3adv-python3.5-PyQt-5.6/bin:/nix/store/5k7il30vgg5wmfa2    8hmy4fn5vvgnpif9-python3.5-sip-4.18.1/bin:/nix/store/lsvgxvg0wsbk90ifaw4k6l5v0fsvnsn8-python3.5-Pygments-2.1.3/bin:/nix/store/mi8vwsx0l4q7bdbqf98cnv2srw39d    m7r-python3.5-docutils-0.12/bin:/nix/store/vvryqybawqdbwfk934nzd6z3d5xf6rxj-python3.5-cssutils-0.9.9/bin${PATH:+:}$PATH
exec -a "$0" /nix/store/dagn6yc6rdk5ccs4z0zmx9qw3g6gcq92-qutebrowser-0.8.2/bin/..qutebrowser-wrapped-wrapped "${extraFlagsArray[@]}" "$@"
`

**Comment by abbradar** [comment]
Okay, nothing strange there; however I think I've seen this error when you environment is big -- here we make it bigger with `export` and then `exec` which triggers the error. Not sure how to measure that; what about:

```
> env | wc -m
5510
```

(mine given for comparison)?

**Comment by Soundtoxin** [comment]
[brad@kazuki:~]$ env | wc -m
3619

**Comment by abbradar** [comment]
Oh wait. I've noticed the root of the problem: your wrapper executes itself for some reason.

I've checked out your NixOS version and the wrapper seems okay there. Do you install your qutebrowser via `environment.systemPackages`? I think I saw this problem long time ago (5 months maybe), maybe you have leftovers in `nix-env`?

**Comment by Soundtoxin** [comment]
I installed it using 'nix-env -i qutebrowser'. I'm still new to NixOS so I don't have all my packages in my configuration.nix file or anything fancy like that.

**Comment by abbradar** [comment]
No problem! However, let's then check if you have any local channels:

```
> nix-channel --list
> sudo nix-channel --list
```

**Comment by Soundtoxin** [comment]
nix-channel --list shows nothing, and sudo nix-channel --list shows this:
`nixos https://nixos.org/channels/nixos-unstable
`
I did try to setup unstable as I am used to fairly new packages from running arch. I think I installed qutebrowser before I did this.

**Comment by abbradar** [comment]
Oh, that might be the problem! Do you want to keep at unstable or return to release?

**Comment by Soundtoxin** [comment]
I would like to stay at unstable.

**Comment by abbradar** [comment]
Then run:

```
> nix-env --always -u '*'
```

This should update all your packages to unstable versions. `--always` updates even packages that don't have a version bump but have hash changed (so it may be a bump of dependency or an actual change in the package -- we don't have separate concept of Arch's package revision).

BTW, I've checked and it seems that qutebrowser is indeed broken on stable. I'll backport a fix shortly.

**Comment by Soundtoxin** [comment]
Thank you so much for the help! After running that command to update my packages to the unstable versions, it works fine.

**Comment by abbradar** [comment]
You are welcome ^_^
