### ISSUE TITLE
Package request: trurl

### ISSUE THREAD

**Issue by NateEag** [NixOS/nixpkgs#225576]
**Project description**

trurl is a command-line tool for manipulating URLs, meant for use in writing shell scripts.

It uses libcurl and is connected to the curl project (it's written by Daniel Stenberg, curl's lead developer).

**Metadata**

* homepage URL: https://curl.se/trurl/
* source URL: https://github.com/curl/trurl
* license: curl
* platforms: unix, linux

**Comment by Kranzes** [comment]
#224526

**Comment by NateEag** [comment]
Oh, thanks! I searched and didn't see it - guess I forgot to check unstable. :facepalm: 

Sorry for the noise.
