### ISSUE TITLE
postman: can't run app (posix_spawn: No such file or directory (2))

### ISSUE THREAD

**Issue by mustafasegf** [NixOS/nixpkgs#225560]
### Describe the bug

can't run postman 10.12.0 in linux x86_64 on latest unstable branch. got error
`[80878:0410/172440.790463:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)`

### Notify maintainers
@johnrichardrinehart  @evanjs @tricktron @Craftzman7 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.2.8, NixOS, 23.05 (Stoat), 23.05.20230327.4bb072f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-22.11.tar.gz, nixpkgs-unstable, nixos-23.05pre440928.aa1d74709f5, nixos-stable-22.11, nixos-unstable"`
 - channels(mustafa): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by johnrichardrinehart** [comment]
Did you try https://github.com/NixOS/nixpkgs/pull/223988 already?

**Comment by mustafasegf** [comment]
I test #223988 and it works. Thanks for the fix. I'm going to close this issue.
