### ISSUE TITLE
nixpkgs.buildNpmPackage fails to build registry correctly

### ISSUE THREAD

**Issue by jmgilman** [NixOS/nixpkgs#225586]
### Describe the bug
The `nixpkgs.buildNpmPackage` function fails to build a project correctly. 

### Steps To Reproduce
1. Use the following lock file: https://gist.github.com/jmgilman/c23c402c72eb37189272fdf5f7f83d75
2. Attempt to build the project
3. Encounter the following error: `Error: https://registry.npmjs.org/js-sha3/-/js-sha3-0.8.0.tgz: Dns Failed: resolve dns name 'registry.npmjs.org:443': failed to lookup address information: Temporary failure in name resolution`

### Expected behavior
I expected the package to build.

### Screenshots
N/A

### Additional context
From my limited understanding of what this function is doing, it appears that the `js-sha3` dependency is not getting included in the temporary registry being built by Nix. However, in the lockfile, the package is present with the correct hash. So I don't understand why it's being excluded. 

If I do:

```
prefetch-npm-deps package-lock.json test
cd test && rg js-sha3
```

I get:

```
index-v5/80/06/e41f0acca6be1089915451a87af0b055580cecf7426629fbe15f38777d98
1:1a73d9a4090e769c4057654d15de3441509cf706      {"key":"make-fetch-happen:request-cache:https://registry.npmjs.org/js-sha3/-/js-sha3-0.8.0.tgz","integrity":"sha512-gF1cRrHhIzNfToc802P800N8PpXS+evLLXfsVpowqmAFR9uwbi89WvXg2QspOmXL8QL86J4T1EpFu+yUkwJY3Q==","time":0,"size":14762,"metadata":{"url":"https://registry.npmjs.org/js-sha3/-/js-sha3-0.8.0.tgz","options":{"compress":true}}}
```

If I understand, this means the package is in the local cache, and the URL is valid.

### Notify maintainers
@winterqt

**Comment by lilyinstarlight** [comment]
That lockfile with the following derivation seems to work fine:

```nix
{ lib
, buildNpmPackage
, pkg-config
, python3
, vips
}:

buildNpmPackage {
  pname = "voting-center-backend";
  version = "0.1.0";

  src = ./.;

  npmDepsHash = "sha256-aTQTuPChhArof+nERtXMqVQooPV2belLYNL9S8q5htw=";

  npmFlags = [ "--legacy-peer-deps" ];

  nativeBuildInputs = [ pkg-config python3 ];
  buildInputs = [ vips ];
}
```

Perhaps it was fixed in one of the recent `buildNpmPackage`-related PRs?

Are you still having issues?

**Comment by hacker1024** [comment]
I am having the same issue with this derivation:

```nix
{ fetchFromGitHub, buildNpmPackage }:

buildNpmPackage rec {
  pname = "mushroom";
  version = "2.7.1";

  src = fetchFromGitHub {
    owner = "piitaya";
    repo = "lovelace-${pname}";
    rev = "v${version}";
    hash = "sha256-KxPB8h/8VOzltMynV/Rzg2yoRgEnnWuNCw/hyUHPnFY=";
  };

  npmDepsHash = "";

  installPhase = ''
    mkdir $out
    cp -r dist/* $out
  '';
};
```

**Comment by marsam** [comment]
I think it's a network issue. Likely addressed by https://github.com/NixOS/nixpkgs/pull/238452

**Comment by lilyinstarlight** [comment]
#238452 has been merged with network error retry logic. Can both of you retry from master when you get a chance @hacker1024 and @jmgilman?

Thanks!

**Comment by hacker1024** [comment]
#238452 has indeed worked around the problem.

It is strange that I am getting frequent name resolution errors in the first place, though. I have noticed no problems with my network connection in any other context, and this issue is occurring on two very different devices (albeit on the same network).

The DNS timeouts are slowing down the build significantly, as they seem to block other packages from downloading until they time out completely.

**Comment by hacker1024** [comment]
@lilyinstarlight Yep, that's much better. Thanks.

**Comment by lilyinstarlight** [comment]
This should be fixed with the change from `ureq` to `isahc`. Feel free to reopen if you continue to have issues

Thanks for the report!
