### ISSUE TITLE
Removing Nux

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nixpkgs#225591]
Hi! I used be the package maintainer of dt-shell-colorscripts  and am the code maintainer of the nux package. After I discovered the nix profile command I realised that there is no need for the nux command, so I stopped maintaining it and therefore it can be removed.

Kind regards,

Jakob

**Comment by jakobneufeld** [comment]
Yes, I might keep it. Its just I don't use it anymore, so I see no need in maintaining it.

**Comment by Atemu** [comment]
Remove yourself as a maintainer, that's good enough.
