### ISSUE TITLE
element-desktop: Start automatically after system login option not working

### ISSUE THREAD

**Issue by adam248** [NixOS/nixpkgs#225674]
### Describe the bug
Setting the option in `Settings -> Preferences -> Start automatically after system login` does not work as described.

### Steps To Reproduce
1. Install pkgs.element-desktop
2. Set the option `Settings -> Preferences -> Start automatically after system login` to true.
3. Reboot the system

### Expected behavior
Element should automatically start on login.

### Screenshots
![image](https://user-images.githubusercontent.com/85082674/231048073-fa77c701-130b-414b-a293-c6fcadf5b429.png)

### Notify maintainers
@Ma27 
@fadenb 
@mguentner 
@Ekleog 
@Ralith 
@dali99 
@sumnerevans 

### Metadata
```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.10, NixOS, 22.11 (Raccoon), 22.11.2483.49efda9011e`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixos-22.11, nixpkgs, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

```

**Comment by adam248** [comment]
Ok, I am having trouble finding how to set it to auto launch after login in my desktop.
Can any one tell me what option to use in `configuration.nix`?

- I tried to build a systemd service, but that didn't work, nor made much sense for a desktop application anyway.
- I tried to use a simple bash script and just add `&` at the end, that didn't work.

I think it has something to do with starting the program as the user I am logged in as, instead of starting it as the root or system service.

Is there a simple nixpkgs option where I can simply add a package to a list in the config and that tells the system to auto start that package's binary?

If you can just give me a link to a page that points me in the right direction, I would be very grateful.

**Comment by dali99** [comment]
Startup applications are handled differently in each desktop environment, you should consult the documentation for whatever DE you use

**Comment by adam248** [comment]
Thanks, issue has been solved!

NOTE TO SELF: **not everything has to been done in a nix config**

![image](https://user-images.githubusercontent.com/85082674/232277555-0ab394f3-babf-4ec8-914a-63a314ded376.png)
