### ISSUE TITLE
[llvm] Desktop icons oversaturated with red after December 11 2016 update

### ISSUE THREAD

**Issue by pstn** [NixOS/nixpkgs#22567]
## Issue description
I had this llvm bug on a machine on unstable with radeonsi and one with amdgpu.
https://bugs.freedesktop.org/show_bug.cgi?id=99078

### Steps to reproduce
See the bugreport

## Technical details

* System: 17.03pre100522.01fef3f (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version:  "17.03pre100522.01fef3f"

**Comment by pstn** [comment]
Mentioning maintainers: @lovek323 @viric

**Comment by vcunat** [comment]
I suppose reverting https://github.com/llvm-mirror/llvm/commit/c280d74837d8 is the easiest course of action now.  I see we've left 16.09 branch on llvm-3.9.0, so it shouldn't be affected by this.

**Comment by pstn** [comment]
That is probably for the best since debian and gentoo did the same.

**Comment by pstn** [comment]
I can confirm that this issue is fixed. Thanks.
