### ISSUE TITLE
nixos-option: missing manpage and meta

### ISSUE THREAD

**Issue by GenericNerdyUsername** [NixOS/nixpkgs#225657]
`nix-shell -p nixos-option --command 'nixos-option --help'` gives an error about a missing manpage, and there is no description or homepage.

### Notify maintainers
@chkno

**Comment by GenericNerdyUsername** [comment]
I think the easiest way to solve this would be to move `nixos/doc/manual/default.nix` to the main `pkgs` tree, then get nixos-option to copy the manpage from that

**Comment by lolbinarycat** [comment]
important to note that `man nixos-option` does succeed.  the manpage exists, --help just can't find it for some reason.

**Comment by eclairevoyant** [comment]
seems this is itself a duplicate (of #115836, which has a bit more detail)
