### ISSUE TITLE
Python 3.5 bytecode caches not working

### ISSUE THREAD

**Issue by edanaher** [NixOS/nixpkgs#22569]
## Issue description

As far as I can tell, python packages are installed with populated \_\_pycache\_\_ directories contained cached bytecode.  Unfortunately, for reasons as of yet unknown to me, python isn't using these, and is trying to regenerate them after each run (which, of course, fails because the nix-store is immutable).

This is a non-trivial performance issue for simple command-line tools with relatively large import sets - e.g., for neovim-remote, the getting the help from the nvr command takes ~0.1s with proper cached files, and ~0.3s without.  For me, that's the difference between "almost instantaneous" and "perceptible delay".  I'd imagine similar issues in other cases.

In my brief tests, this also appears to happen with Python versions 3.3 and 3.4; I believe version 2.x uses a different caching mechanism that, AFAICT, isn't affected.

### Steps to reproduce

This probably works with pretty much any python program, but here's a fairly complete demo using a trivial load; initially, running an empty python script gives an EROFS writing back a .pyc file (only one is shown for brevity; there are several).  After running this empty script with a writable nix-store, the EROFS is gone, and the nix-store has been changed.

```
[edanaher@gemedet:~]$ nix-store --verify --check-contents
reading the Nix store...
checking path existence...
checking hashes...

[edanaher@gemedet:~]$ nix-shell --pure -p python35 -p strace --run 'strace python -c "" 2>&1 | grep stat.*EROFS' 
open("/nix/store/42p7bp41vr94bb8ip0nq0v91fcb8ixmr-python3-3.5.2/lib/python3.5/__pycache__/stat.cpython-35.pyc.140579024365240", O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC, 0644) = -1 EROFS (Read-only file system)

[edanaher@gemedet:~]$ sudo unshare -m

[root@gemedet:/home/edanaher]# mount -orw,remount /nix/store

[root@gemedet:/home/edanaher]# nix-shell --pure -p python35 -p strace --run 'python -c ""' 2>&1

[root@gemedet:/home/edanaher]# logout

[edanaher@gemedet:~]$ nix-shell --pure -p python35 -p strace --run 'strace python -c "" 2>&1 | grep stat.*EROFS' 

[edanaher@gemedet:~]$ nix-store --verify --check-contents
reading the Nix store...
checking path existence...
checking hashes...
path ‘/nix/store/42p7bp41vr94bb8ip0nq0v91fcb8ixmr-python3-3.5.2’ was modified! expected hash ‘5bf67a2e24cc54c1506484fe0d178e8f98b8a2c176b77cecc11a5a1a050f9e9c’, got ‘51051e52289038a615b349ad09cbb0ae7e5bbed6d66522170025b37bbb457159’
warning: not all errors were fixed
```

A further demo of nvr showing the timing difference (starting from a clean nix-store; there are also EROFS's here, but I'm not bothering to show them):

```
[edanaher@gemedet:~]$ nix-shell --pure -p python35Packages.neovim-remote --run 'time nvr >/dev/null' 

real	0m0.325s
user	0m0.315s
sys	0m0.009s

[edanaher@gemedet:~]$ sudo unshare -m

[root@gemedet:/home/edanaher]# mount -orw,remount /nix/store

[root@gemedet:/home/edanaher]# nix-shell --pure -p python35Packages.neovim-remote --run 'time nvr >/dev/null' 

real	0m0.405s
user	0m0.321s
sys	0m0.032s

[root@gemedet:/home/edanaher]# logout

[edanaher@gemedet:~]$ nix-shell --pure -p python35Packages.neovim-remote --run 'time nvr >/dev/null' 

real	0m0.101s
user	0m0.090s
sys	0m0.010s
```

## Technical details

* System: NixOS 17.03pre100522.01fef3f (Gorilla)
* Nix version: nix-env (Nix) 1.11.6
* Nixpkgs version: 17.03pre100522.01fef3f

**Comment by FRidh** [comment]
Funny, I was just looking at the reproducibility of Python and its packages (https://github.com/NixOS/nixpkgs/issues/22570) and how we should fix the bytecode. Now, here's another related issue.

Anyway, it would be nice if it wouldn't bother when the `.pyc` file is in `/nix/store`

**Comment by edanaher** [comment]
Thanks @FRidh for that comment!  That got me to [this post](http://stackoverflow.com/questions/23775760/how-does-the-python-interpreter-know-when-to-compile-and-update-a-pyc-file) on stackoverflow, which pointed me to [this line](https://github.com/python/cpython/blob/master/Lib/importlib/_bootstrap_external.py#L471) which checks that the timestamp stored in the .pyc is *identical* (not after) the mtime of the .py file.  And since the timestamp isn't set to unix time 0 until after the build, it ends up with the wrong timestamp and refuses to use the cached version.

Since your bug describes the root cause concisely, I'm going to close this and use that ticket for tracking.
