### ISSUE TITLE
systemd-boot failed to install bootloader when install nixos using live CD

### ISSUE THREAD

**Issue by sifmelcara** [NixOS/nixpkgs#22561]
## Issue description

When doing a fresh nixos install on UEFI system, command `nixos-install` failed to install bootloader (systemd-boot)

Here is the log
```
finalising the installation...
Created "/boot/EFI/systemd".
Created "/boot/EFI/BOOT".
Created "/boot/loader".
Created "/boot/loader/entries".
Copied "/nix/store/zs7cny1d4g81m5fvggj8jg4d5s9wrmb2-systemd-232/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/zs7cny1d4g81m5fvggj8jg4d5s9wrmb2-systemd-232/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Failed to get machine did: No such file or directory
Traceback (most recent call last):
  File "/nix/store/kdzd5x98ppq0sy0lddf5wh5w2iyyxsm6-systemd-boot-builder.py", line 132, in <module>
    main()
  File "/nix/store/kdzd5x98ppq0sy0lddf5wh5w2iyyxsm6-systemd-boot-builder.py", line 110, in main
    subprocess.check_call(["/nix/store/zs7cny1d4g81m5fvggj8jg4d5s9wrmb2-systemd-232/bin/bootctl", "--path=/boot", "install"])
  File "/nix/store/42p7bp41vr94bb8ip0nq0v91fcb8ixmr-python3-3.5.2/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/zs7cny1d4g81m5fvggj8jg4d5s9wrmb2-systemd-232/bin/bootctl', '--path=/boot', 'install']' returned non-zero exit status 1
```

However, this problem do not occur on nixos-graphical-16.09.1650.d2cd8a0-x86_64-linux.iso , so I think it is due to a recent update/modification to systemd-boot related code.

### Steps to reproduce

1. Boot the machine with nixos-graphical-17.03pre100522.01fef3f-x86_64-linux.iso (Released on 2017-02-08 12:52:44 from Git commit 01fef3f7db4cc208faea31f26c9451b326058781 via Hydra evaluation 1329966.)
2. mount an empty ext4 filesystem at /mnt, mkdir /mnt/boot, then mount a preexisting EFI filesystem at /mnt/boot
3. nixos-generate-config --root /mnt
4. nixos-install

I can also reproduce the problem using a fresh EFI partition

## Technical details

Macbook Pro Early 2015 13"

Please tell me if there is anything I can help you with, thank you

**Comment by Mic92** [comment]
Looks like systemd 232 now requires `/etc/machine-id` to be present. A quick-fix for your problem would be to run `systemd-machine-id-setup --root=/mnt` before `nixos-install`. The long term fix would be to run the same command in `nixos/modules/system/boot/loader/systemd-boot/systemd-boot-builder.py`

**Comment by sifmelcara** [comment]
I just installed NixOS again and can confirm execute `systemd-machine-id-setup --root=/mnt` before `nixos-install` fixes the issue.

**Comment by dezgeg** [comment]
There is indeed a test that started failing since v232: http://hydra.nixos.org/build/47719561
